### ISSUE TITLE
Rewards: "Next Contribution Date" Sometimes displays a past date

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#2206]
## Description 

In `Rewards Settings --> Auto-Contribute`, the "Next Contribution Date" sometimes displays dates that are in the past:
![image](https://user-images.githubusercontent.com/3299098/48810125-76822100-ecdc-11e8-9b66-8cf56c7299eb.png)
Above picture courtesy of @Miyayes 
Below picture from Community user (oddly enough it displays the same date, not sure if relevant)
![image](https://user-images.githubusercontent.com/3299098/48810165-a9c4b000-ecdc-11e8-9b54-6fe14f4520a8.png)

## Steps to Reproduce

No STR as far as I know. cc @Miyayes for additional info.
Note: This issue occured _before_ the update today to v0.56.14

## Actual result:

(See image in Description)

## Expected result:
Next Contribution Date should display a valid (and accurate) date.

## Reproduces how often: 

Unclear/No STR

## Brave version (brave://version info)

Release build v0.55.12

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Unclear

### Additional Information

Link to Community user encountering the issue:
https://community.brave.com/t/2-brave-rewards-payments-bugs/37847

**Comment by reedriley** [comment]
For what it's worth, I seem to have hit this as well, on v0.56.15.

**Comment by patrickkostjens** [comment]
I'm having the same problem. Just updated to v0.57.18 and it still doesn't seem to trigger contributions.

**Comment by Miyayes** [comment]
More info: I still have this in 0.57.18, and right upon updating to 0.57.18 on Friday (Dec. 7th, 2018), I got the message "Your contribution did not go through due to insufficient funds". (I definitely have enough funds to cover my contribution since I have over 100 BAT.) Not sure whether this is related to the strange state of my wallet (of which this issue is a symptom), or if it was just a quirk upon updating.

**Comment by reedriley** [comment]
I'm still hitting this on v0.57.18.

**Comment by MiMoHo** [comment]
![brave_browser_contribution_date_in_the_past](https://user-images.githubusercontent.com/37556964/49974648-994dd100-ff3a-11e8-9f56-eeb3954a6ebd.jpg)
Same issue here with Brave 0.57.18 on Windows 10

**Comment by LaurenWags** [comment]
My contribution date is stuck in the past as well on Dev 

Brave | 0.60.5 Chromium: 72.0.3626.28 (Official Build) dev (64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Mac OS X

Also, looks like I'm getting a message about insufficient funds but I do have more than enough:
<img width="1069" alt="screen shot 2019-01-03 at 3 19 37 pm" src="https://user-images.githubusercontent.com/28145373/50659585-13d2a500-0f6b-11e9-97cc-b749e70f269b.png">
<img width="395" alt="screen shot 2019-01-03 at 3 19 56 pm" src="https://user-images.githubusercontent.com/28145373/50659589-17662c00-0f6b-11e9-92aa-1972b508ad7f.png">

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.59.26 Chromium: 72.0.3626.64 (Official Build) beta(64-bit)
-- | --
Revision | eaa9668e80ce5405e7f1902579558ea725c06ca1-refs/branch-heads/3626@{#708}
OS | Linux

* Verified steps from https://github.com/brave/brave-core/pull/1168
* Verification done on staging wallet

**Comment by DivineOmega** [comment]
Unfortunately, I've just started seeing this issue.

The screenshot below was taken today (29 August 2019). It display a past auto-contribution date of the 23 August.

![Screenshot from 2019-08-29 10-41-23](https://user-images.githubusercontent.com/650645/63929610-a1f32280-ca49-11e9-9b80-b3726fd87e3c.png)

I'm running Brave Version 0.68.131 Chromium: 76.0.3809.100 (Official Build) (64-bit).

**Comment by NejcZdovc** [comment]
@DivineOmega if you go to chrome://rewards-internals/ do you have any contributions in progress?

**Comment by DivineOmega** [comment]
@NejcZdovc I see the following. I've redacted the IDs as I'm not sure if there are privacy implications of revealing them publicly.

```
Key Info Seed: Valid
Wallet Payment ID: 064[REDACTED]2f2

Current Reconcile 1
Viewing ID: 3e7[REDACTED]623
Amount: 0.2
Retry Step: Payload
Retry Level: 3
Persona ID: 7a3[REDACTED]f47
User ID: 7a3[REDACTED]f47
Wallet created: 21/06/2019
```

**Comment by NejcZdovc** [comment]
@DivineOmega this is what I though. So your contribution is in retry flow. After retry will be done (successfully or not) contribution date will be moved. Do you have enough funds to complete this transaction? We can improve UI in this regard and say something like (in progress or retrying)

**Comment by DivineOmega** [comment]
@NejcZdovc I do have sufficient funds in place (5.1 BAT, earned from ads).

To try to get this working, I removed all pending contributions and restarted the browser. I then received a message stating there was an error processing my contribution.

The rewards-internal page still shows a contribution in progress. However, the next contribution date has correctly advanced to the next month (28 Sep).

**Comment by bsclifton** [comment]
@DivineOmega money earned from rewards is (behind the scenes) treated differently than money you have deposited yourself. @NejcZdovc is there a problem here where the balance from advertising grant is not considered?

**Comment by NejcZdovc** [comment]
@bsclifton I think the problem is that @DivineOmega had some recurring tips set up. And we combine AC and recurring tips and check against balance as one. So for example if you have 5 BAT AC and 3 publishers with 1 BAT recurring you need 8 BAT to process it. It's all or nothing approach.

**Comment by DivineOmega** [comment]
@NejcZdovc @bsclifton I'm afraid I've not made use of the tips system at all yet, recurring or otherwise.

**Comment by NejcZdovc** [comment]
Oh ok, sorry I misread it then. Will try couple of things to reproduce it

**Comment by archer5** [comment]
I'm getting this issue also on the latest Brave Android version, but have no retry attempt listed in chrome://rewards-internals/
