### ISSUE TITLE
[Android VPN] [Beta User Feedback] Fix VPN Icon (under settings) color

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#22072]
**User Feedback**
VPN icon (under settings page) is too dark when dark theme enabled.

![image](https://user-images.githubusercontent.com/28269287/161607912-71e70efc-8c53-4888-b254-db95860decb9.png)

**Comment by timchilds** [comment]
@deeppandya here is the Figma for new VPN logo:
https://www.figma.com/file/QqaIjdrXobryTT3Zd9wcKM/Android-settings?node-id=0%3A1#176348315

**Comment by Uni-verse** [comment]
Verified using 1.40.53, Chromium 102.0.5005.50

- Confirmed that the VPN Settings icon matches the spec sheet. 

spec | mobile | tablet
-|-|-
![Screen Shot 2022-05-13 at 2 43 54 PM](https://user-images.githubusercontent.com/17885425/168396693-5df6954a-8484-48a4-822b-5c9f88be99d9.png) | ![Screen Shot 2022-05-13 at 2 44 11 PM](https://user-images.githubusercontent.com/17885425/168396698-c43a345a-6196-4db2-a395-ae6c677b1e63.png) | ![Screen Shot 2022-05-13 at 3 18 54 PM](https://user-images.githubusercontent.com/17885425/168396701-fb47ee0f-a955-4146-9cb1-e26b3c1b6b6c.png)

**Comment by Uni-verse** [comment]
Created follow up issue per product - https://github.com/brave/brave-browser/issues/22848
