### ISSUE TITLE
Loopring.io L2 activation fails for 2nd sign request (eth_signTypedData_v4)

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#22070]
It turns out that solidity supports `uintN` and `intN` types where `0 < N <= 256; N%8 == 0`, so types like `uint56` are supported. Our sign typed data implementation currently only supports `uint[N]` and `intN` types where N is `[8, 16, 32,64, 128, 256]`

**Comment by kjozwiak** [comment]
Above requires `1.38.99` or higher for `1.38.x` verification.
