### ISSUE TITLE
Enable Sync by default

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#2208]

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta(64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Linux

- Running `--disable-brave-sync` doesn't show Brave sync option in hamburger menu
- Running `--disable-brave-sync` doesn't show Brave sync in brave://extensions
- Running `--disable-brave-sync` and the visiting brave://bravesync loads an error page
