### ISSUE TITLE
Filter out Dialog Insight trackers from URLs

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#22082]
I found this in a Qtrade email:

    <img alt="" width="3" height="2" src="http://link.mail.qtrade.ca/T/OFC4/T/5916/946.../1Enu....gif" />

It's a CNAME to `ofsys.com`:
```
$ dig link.mail.qtrade.ca
link.mail.qtrade.ca.	3078	IN	CNAME	secure.ofsys.com.
secure.ofsys.com.	1313	IN	A	208.91.248.10
```
and sure enough the [final link](https://www.qtrade.ca/fr/investor/about/news/Perspective-de-Patrimoine-Aviso-sur-la-crise-russo-ukrainienne-2022.html?utm_source=Openfield&utm_medium=email&utm_campaign=qtoyou&oft_id=946...&oft_k=1Enu...&oft_lk=kea...&oft_d=637...) ends up being decorated with extra query string parameters: `oft_id`, `oft_k`, `oft_lk` and `oft_d`. The [unsubscribe link](http://link.mail.qtrade.ca/T/OFC4/OO/en-US/5916/946.../1Enu.../245.../Ehu....html) doesn't use any of these query parameters but both `oft_id` and `oft_k` are present in the path, the same ones used in the image tracker.

There are [lots of examples in the wild](https://www.google.com/search?q=%22oft_id%22). My best guess is that these parameters are useful in [conversion tracking on external e-commerce platforms](https://support.dialoginsight.com/fr/support/solutions/folders/1000227892).

I found a [landing page](http://ladingpage.tcmlesaffaires.pages.dialoginsight.com/politique-confidentialite) in a [GitHub repo](https://github.com/mariamaOlive/projeto2-nlp-sidi-residencia/blob/96076dc231c60cac6e7ae93cdf8ebe646db7239b/dados/train%20v0.2/72/1559200872.html#L2588) but it doesn't seem to have any real JS code running (other than an animation).

For user journey tracking:
- https://support.dialoginsight.com/fr/support/solutions/folders/1000227042/page/1?url_locale=fr
- https://support.dialoginsight.com/fr/support/solutions/articles/1000249545-ajouter-des-domaines-%C3%A0-un-site
- https://support.dialoginsight.com/fr/support/solutions/articles/1000249546-configurer-le-module-de-suivi-parcours

there is a Dialog Insight [script to add](https://support.dialoginsight.com/fr/support/solutions/articles/1000249546-configurer-le-module-de-suivi-parcours) the scripts looks like [this one](https://t.ofsys.com/js/Journey/1/SAMAADJrR3owTmAYAABOcTZoSUdvAQAA/DI.Journey-min.js), as found on [this website](http://signaturemt.ca.bitverzo.com/). The script is already in EasyPrivacy.

The full unminified source code was [accidentally left online](https://t.ofsys.com/js/Journey/1/SAMAADJrR3owTmAYAABOcTZoSUdvAQAA/DI.Journey.js) and so this is the full list of parameters they use:
```
    GetOfsysParameters : function()
    {
        return ["oft_id", "oft_k", "oft_lk", "oft_d", "oft_c", "oft_ck", "oft_campaign", "oft_ids", "oft_sk"];
    },
```
It seems like they can identify individual visitors based on any of the parameters, except for `oft_campaign`:
```
        for(var i = 0; i < ofsysParameters.length;i++)
        {
            var pName = ofsysParameters[i];                        
            if(typeof allValuesDic[pName] !== "undefined")
            {
                visitValue[pName] = allValuesDic[pName];

                if(pName == "oft_campaign")
                    continue;

                visitorIsIdentified = true;
                if(typeof visitorValue[pName] !== 'undefined')
                    delete visitorValue[pName];
            }
        }
```
This links to [another tracker](https://t.ofsys.com/js/Tracking2/package-min.js) though I didn't find anything interesting there.

**Comment by stephendonner** [comment]
### Verified `PASSED` using 

Brave | 1.39.51 Chromium: 100.0.4896.88 (Official Build) nightly (x86_64)
-- | --
Revision | 4450653bfa91182e85723d8f1dee64dd6ce40ed4-refs/branch-heads/4896@{#1086}
OS | macOS Version 11.6.5 (Build 20G527)

#### Steps:
1. installed `1.39.51`
2. launched Brave
3. loaded `https://brave.com/?oft_id=946&oft_k=1Enu&oft_lk=kea&oft_d=637`

#### Ensured that the four (4) tracking parameters were dropped via an internal (Brave) redirect, ending up just `https://brave.com/`

<img width="1661" alt="Screen Shot 2022-04-12 at 4 30 05 PM" src="https://user-images.githubusercontent.com/387249/163071087-173a8b95-1a86-4831-a86d-728ab4bbb545.png">

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+` running `Android 12` using the following build(s):

```
Brave | 1.39.109 Chromium: 102.0.5005.50 (Official Build) (64-bit)
--- | ---
Revision | f6e2cf8f59ec714bdcff8499991d55898875f287-refs/branch-heads/5005@{#648}
OS | Android 11; Build/RP1A.200720.012
```

STR/Cases used as per https://github.com/brave/brave-core/pull/12893#issue-1192575722:

1. installed `1.39.109 Chromium: 102.0.5005.50`
2. launched Brave
3. loaded `https://brave.com/?oft_id=946&oft_k=1Enu&oft_lk=kea&oft_d=637` via `brave://inspect`

Ensured that the four (4) tracking parameters were dropped via an internal (Brave) redirect, ending up just `https://brave.com/`

![image](https://user-images.githubusercontent.com/2602313/169398469-547b36fb-2d4e-44ad-beb7-2df51a5b31a8.png)
