### ISSUE TITLE
Shields v2, match labels for cookies and fingerprinting to spec

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#22084]
## Description 

See: https://www.figma.com/file/3A6F6VrxVahiZFxLr7j7FO/Desktop-Brave-Shields

## Steps to Reproduce

   1. Use 1.39.28 and higher
   2. Open shields and open up menu items for fingerprinting and cookies in advanced controls
   3. Notice label order. Should match spec with aggressive and block all (respectively) as the top most items.

## Actual result:
<img width="375" alt="Screen Shot 2022-04-04 at 4 35 21 PM" src="https://user-images.githubusercontent.com/5951041/161649605-0b0fabaf-aa05-4565-becf-f5e5af6f1aa4.png">
<img width="382" alt="Screen Shot 2022-04-04 at 4 35 29 PM" src="https://user-images.githubusercontent.com/5951041/161649608-b58b48a3-1594-495a-9853-77902f637fd0.png">

## Expected result:
<img width="869" alt="Screen Shot 2022-04-04 at 4 41 07 PM" src="https://user-images.githubusercontent.com/5951041/161649863-74aa1056-d325-4e5f-af98-74d45d8d7123.png">

## Reproduces how often: 

Easily.

## Brave version (brave://version info)

1.39.28.x and higher

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

Needs to uplift to 1.38.x once issue is verified in 1.39.x

**Comment by rebron** [comment]
cc: @aguscruiz

**Comment by kjozwiak** [comment]
Above requires `1.38.85` or higher for `1.38.x` verification.

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.38.104 Chromium: 101.0.4951.41 (Official Build) (x86_64)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | macOS Version 12.4 (Build 21F5058e)

Confirmed the ordering of cookies and fingerprint-blocking options now match the Figma spec.

<img width="869" alt="161649863-74aa1056-d325-4e5f-af98-74d45d8d7123 (1)" src="https://user-images.githubusercontent.com/387249/164611384-9b1afd98-5dc8-4286-9709-36b6da328ac3.png">


Default panel | Trackers & ads | Fingerprinting | Cookies
----------------|---------------|--------------|------------
<img width="1312" alt="Screen Shot 2022-04-21 at 10 45 42 PM" src="https://user-images.githubusercontent.com/387249/164611160-0a94eeba-0559-4746-bce7-5d05f929d05b.png"> | <img width="1198" alt="Screen Shot 2022-04-21 at 10 25 26 PM" src="https://user-images.githubusercontent.com/387249/164610883-7aa1c7d3-d206-40f5-897b-7c319205af89.png"> | <img width="1194" alt="Screen Shot 2022-04-21 at 10 27 09 PM" src="https://user-images.githubusercontent.com/387249/164610893-2a4718d1-d1d3-431f-8bc0-08887ae3f244.png"> | <img width="1204" alt="Screen Shot 2022-04-21 at 10 27 39 PM" src="https://user-images.githubusercontent.com/387249/164610902-449e5891-4162-40db-9425-56ed03957737.png">
