### ISSUE TITLE
https://brave.com/welcome/ shows on each browser launch

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#221]
## Description 
https://brave.com/welcome/ shows on each browser launch

## Steps to Reproduce

   1. Build from source and launch browser
   2. Ensure first time launch shows https://brave.com/welcome/ in a new tab
   3. Open a new tab and make it active tab and close the browser
   4. Launch browser again, a second welcome tab is shown
   5. Repeat steps 3 & 4, every time a new tab with welcome page is shown

 ## Actual result:

https://brave.com/welcome/ shows on each browser launch

## Expected result:
Should show only at first launch
## Reproduces how often: 
Easy

## Brave version (about:brave info)
Version 66.0.3359.170 

### Additional Information
#85 
cc: @AlexeyBarabash @bbondy

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7

Passes with minor change. Welcome page is: chrome://welcome/
