### ISSUE TITLE
Speedreader inconsistancies 

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#22106]
## Description 

<Summary>Scenario 1: If the Speedreader was toggled off in the reader mode icon, Speedreader was not disabled in the global settings </Summary>

<details>

## Steps to Reproduce

   1. Install 1.38.80
   2. Launch Brave
   3. Disabled `Speedreader` in brave://settings/Appearance
   4. Visit `https://brave.com/blog`
   5. Reader-mode icon is visible
   6. Clicked to `Turn on Speedreader`
   7. Verified `Speedreader` is enabled in the `brave://settings/Appearance`
   8. Toggle `Speedreader` `off` in `reader-mode` icon

## Actual result:

`Speedreader` in `brave://settings/Appearance` is still enabled

https://user-images.githubusercontent.com/98358127/161818913-cd0c39f8-badd-4a0a-972b-353f650acf48.mp4

## Expected result:
`Speedreader`in `brave://settings/Appearance` should be disabled
</details>

<Summary>Scenario 2: When clicked on Reader-mode icon, window  doesn't display after it was dismissed couple of times without `Turning on Speedreader` </Summary>

<details>

1. Install `1.38.80`
2. Launch Brave
3. Disabled `Speedreader` in `brave://settings/Appearance`
4. Visit `https://brave.com/blog`
5. `Reader-mode` icon is visible
6. Click on the Reader-mode icon but do not `Turn on Speedreader`
7. Click away to close the Reader-mode window
9. Click reader-mode icon two more times. 
10. After third time, reader-mode window is not displayed
11. Visit Washingtonpost.com and open an article in another tab
13. Click the reader-mode icon.  
14. It appears the page is on Speedreader mode without the visible Speedreader icon 

## Actual result:

Reader-mode window is not available to  `Turn on Speedreader`.   

https://user-images.githubusercontent.com/98358127/161825043-7610c47a-5451-4c91-9a87-887fcc5a9e2f.mp4

## Expected result:
Reader mode window should be available to `Turn on Speedreader`.   

</details>

## Brave version (brave://version info)

Brave | 1.38.80 Chromium: 100.0.4896.79 (Official Build) beta (64-bit)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | Windows 11 Version 21H2 (Build 22000.593)

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by iefremov** [comment]
Should be fixed with https://github.com/brave/brave-core/pull/12678
@MadhaviSeelam can you please check?
