### ISSUE TITLE
Create .deb package

### ISSUE THREAD

**Issue by FinixFighter** [brave/brave-browser#22103]
## Description 
Not everyone use snap, so having a .deb package would be very useful, and it will reach everyone using a Debian based distro. Moreover, deb packages are lighter than flatpaks (note that I'm not saying a flatpak version of Brave shouldn't exist, but just that deb should have more priority imo). Here is the procedure for packaging Brave for Debian: https://wiki.debian.org/Packaging

## Expected result:
Users on Linux can install Brave from their software manager. As simple as a click.

**Comment by FinixFighter** [comment]
Just found this: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=864795
Is there anything that could be done to speed up the process?

**Comment by mihaiplesa** [comment]
Please see https://brave.com/linux/ and https://github.com/brave/brave-browser/releases

**Comment by fmarier** [comment]
Mihai has already shared a link to our official package repository which is our recommended installation method on Linux at the moment.

We are also thinking about maybe switching to a simpler [downloadable package-based installation flow](https://github.com/brave/brave-browser/issues/9050) like Chrome.
