### ISSUE TITLE
center the number of trackers on the shields panel - follow up to 21601

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#22102]
## Description 

Follow up to #21601 

When you hover over the trackers/ads blocked (and likely the HTTPS count and blocked scripts count), the number is not centered in the hover area. See screenshots below.

## Steps to Reproduce

   1. Visit a page with 99+ trackers/ads blocked (ex. https://d3ward.github.io/toolz/adblock.html)
   2. Open shields
   3. View Advanced if it's not shown
   4. Hover over the `99+` on the same line as "Trackers & ads blocked"

## Actual result:

`99+` looks like it's right aligned, not centered in the hover area:

Dark theme | Light theme
----- | -----
<img width="411" alt="dark" src="https://user-images.githubusercontent.com/28145373/161798781-c5d08f34-7a4d-4690-b881-613a40635250.png"> | <img width="408" alt="light" src="https://user-images.githubusercontent.com/28145373/161798898-7ac683cf-ec93-42fb-a3c6-05bbf3586b3b.png">

## Expected result:

`99+` to be centered in hover area

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.38.80 Chromium: 100.0.4896.79 (Official Build) beta (x86_64)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | macOS Version 12.3.1 (Build 21E258)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 1.37.x n/a
- Can you reproduce this issue with the beta channel? 1.38.x yes
- Can you reproduce this issue with the nightly channel? 1.39.x yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
cc: @aguscruiz @nullhook

**Comment by rebron** [comment]
Closing as wontfix. We do want this right aligned.
