### ISSUE TITLE
SolanaProviderTest.* browser tests crash in Debug 

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#22107]
On `master` branch, Debug build, run any of the `SolanaProviderTest.*` browser tests, for example, `SolanaProviderTest.Connect` and the test will crash.

The top of the stack trace on Windows is:
<pre>
#
# Fatal error in ../../v8\src/objects/tagged-impl.h, line 90
# Debug check failed: kCanBeWeak || (!IsSmi() == HAS_STRONG_HEAP_OBJECT_TAG(ptr_)).
#
#
#
#FailureMessage Object: 000000E4C82FBE98[627624:566036:0405/132529.857:INFO:CONSOLE(128)] "This API is intended for internal use.", source:  (128)
Backtrace:
        base::debug::CollectStackTrace [0x00007FFA55D45637+39] (C:\brave-browser\src\base\debug\stack_trace_win.cc:305)
        base::debug::StackTrace::StackTrace [0x00007FFA55A141FD+77] (C:\brave-browser\src\base\debug\stack_trace.cc:222)
        base::debug::StackTrace::StackTrace [0x00007FFA55A14195+37] (C:\brave-browser\src\base\debug\stack_trace.cc:219)
        gin::`anonymous namespace'::PrintStackTrace [0x00007FFA16BB98F9+57] (C:\brave-browser\src\gin\v8_platform.cc:47)
        V8_Fatal [0x00007FFA02D8C442+210] (C:\brave-browser\src\v8\src\base\logging.cc:166)
        v8::base::`anonymous namespace'::DefaultDcheckHandler [0x00007FFA02D8BD63+19] (C:\brave-browser\src\v8\src\base\logging.cc:57)
        v8::internal::Object::IsJSReceiver [0x00007FFA16C0FC66+150] (C:\brave-browser\src\v8\src\objects\objects-inl.h:91)
        v8::internal::JSPromise::Resolve [0x00007FFA174BDE6F+223] (C:\brave-browser\src\v8\src\objects\objects.cc:5468)
        v8::Promise::Resolver::Resolve [0x00007FFA16C6243B+299] (C:\brave-browser\src\v8\src\api\api.cc:7611)
        brave_wallet::JSSolanaProvider::SendResponse [0x00007FF701CE8497+1095] (C:\brave-browser\src\brave\components\brave_wallet\renderer\js_solana_provider.cc:739)
        brave_wallet::JSSolanaProvider::OnConnect [0x00007FF701CE40B3+1411] (C:\brave-browser\src\brave\components\brave_wallet\renderer\js_solana_provider.cc:542)
</pre>

**Comment by darkdh** [comment]
In cr101, Release build will crash as well because cr101 makes LOGGING_FATAL crash now instead of DCHECK

**Comment by emerick** [comment]
@darkdh These are failing in the same way in cr102 in Linux and Windows CI (possibly other platforms as well). I believe the cr102 branch is up-to-date with cr101, so I think unfortunately it's no longer true that it's a Debug-only problem (at least for cr102). 

Sample failure log here: https://ci.brave.com/job/pr-brave-browser-cr102-windows/29/execution/node/289/log/
