### ISSUE TITLE
"A free token grant is available" line item appears in Brave Rewards summary (in Spanish)

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#22104]
## Description

"A free token grant is available" string and line item shouldn't exist. 

![image](https://user-images.githubusercontent.com/11497541/161820873-ea4e794f-5840-4fe5-95f5-2008c9c64f0c.png)

**Comment by szilardszaloki** [comment]
https://github.com/brave/brave-core/blob/b34d1208962dfd6960c3c7f54e242e5adc9c0af3/components/resources/strings/brave_components_resources_es.xtb#L207

**Comment by kjozwiak** [comment]
Above requires `1.37.114` or higher for `1.37.x` verification.

**Comment by LaurenWags** [comment]
Verified using

```
Brave | 1.37.114 Chromium: 100.0.4896.88 (Build oficial) (x86_64)
-- | --
Revisión | 4450653bfa91182e85723d8f1dee64dd6ce40ed4-refs/branch-heads/4896@{#1086}
Sistema operativo | macOS Versión 12.3.1 (Compilación 21E258)
```

Reproduced the issue using 1.37.113. Confirmed translation updated with 1.37.114.

1.37.113 | 1.37.114
----- | -----
<img width="398" alt="1 37 113" src="https://user-images.githubusercontent.com/28145373/163176493-813e214a-a623-4442-8279-671598ed05e2.png"> | <img width="403" alt="1 37 114" src="https://user-images.githubusercontent.com/28145373/163176501-f15c1fd4-eb7e-4da2-bb36-40498efc3268.png">
