### ISSUE TITLE
Create and automatically publish silent installers for Brave-Core (Windows)

### ISSUE THREAD

**Issue by davidtemkin** [brave/brave-browser#2210]
## Description 

In order to support distribution partners who are offering Brave for download, we need to make a set of silent installers available with each release for Win32 and Win64.

These installers should require no interaction and ideally be invisible. 
They should automatically launch the newly-installed app following installation.
With each release, the silent installers should automatically be published to the web, just as existing installers are today. The distribution partners will link to the files that Brave hosts. 

A more detailed spec is here:

https://docs.google.com/document/d/1gcpVFtHQqk1TndFFRiCFepil4isc_RhRNS6JCKMSQ1s/edit

**Comment by bbondy** [comment]
marking 0.57.x milestone

**Comment by kjozwiak** [comment]
Labelling this as `QA/No`. @davidtemkin @mbacchi please let me know if there's anything QA can specifically check/verify.

**Comment by bsclifton** [comment]
@mbacchi @w0ts0n was this closed out? (ex: we publish these on Releases page) or do we still have work to do?

I know you all helped provide me personally with a silent installer, but I don't recall seeing silent install versions on https://github.com/brave/brave-browser/releases

**Comment by mbacchi** [comment]
@bsclifton I have finished the parts that build and upload the silent installer (and untagged installer) to Github. The part that uploads this silent installer to the S3 bucket we use for the releases (`brave-browser-downloads`) is still manual for now but will be automated soon.

I probably should have not used this issue with the closing keywords for the PR above, instead I should have opened another issue for the PR only, and referenced that here when merged. In the future I'll try to do that so as not to close a tracking issue such as this one.
