### ISSUE TITLE
Multichain set defaultAccount upon first account creation

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#22114]
## Description 
If a user has not yet created a `Solana` or `Filecoin` account, upon creating either account for the `first` time, We should set the `defaultAccount` for that `cointType`.

cointype Solana:
defaultAccount = `new account`

cointype Filecoin:
defaultAccount = `new account`

**Comment by darkdh** [comment]
we can set selected account in c++ whenever the first account of that coin is created
ETH
- https://github.com/brave/brave-core/blob/5ea519b59a8dc356433035b39aabcf5d7f40f7ad/components/brave_wallet/browser/keyring_service.cc#L732
- https://github.com/brave/brave-core/blob/5ea519b59a8dc356433035b39aabcf5d7f40f7ad/components/brave_wallet/browser/keyring_service.cc#L758

SOL
- https://github.com/brave/brave-core/blob/5ea519b59a8dc356433035b39aabcf5d7f40f7ad/components/brave_wallet/browser/keyring_service.cc#L772
- https://github.com/brave/brave-core/blob/5ea519b59a8dc356433035b39aabcf5d7f40f7ad/components/brave_wallet/browser/keyring_service.cc#L837

FIL
- https://github.com/brave/brave-core/blob/5ea519b59a8dc356433035b39aabcf5d7f40f7ad/components/brave_wallet/browser/keyring_service.cc#L765
- https://github.com/brave/brave-core/blob/5ea519b59a8dc356433035b39aabcf5d7f40f7ad/components/brave_wallet/browser/keyring_service.cc#L837

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.43.79 Chromium: 104.0.5112.102 (Official Build) beta (64-bit) 
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | Linux

- Verified steps from [ brave/brave-core#14135](https://github.com/brave/brave-core/pull/14135)
- Verified after creating a new account correct network is selected
- Verified last created account is properly selected when switching networks
- Verified correct network is selected when switching between accounts
- Verified with create account/import/hardware import accounts 
- Encountered [#24885](https://github.com/brave/brave-browser/issues/24885) & [#24888](https://github.com/brave/brave-browser/issues/24888)

------------------------
Verification passed on

Brave | 1.43.79 Chromium: 104.0.5112.102 (Official Build) beta (64-bit) 
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | Windows 11 Version 21H2 (Build 22000.795)

- Verified steps from [ brave/brave-core#14135](https://github.com/brave/brave-core/pull/14135)
- Verified after creating a new account correct network is selected
- Verified last created account is properly selected when switching networks
- Verified correct network is selected when switching between accounts
- Verified with create account/import/hardware import accounts 
- Encountered [#24885](https://github.com/brave/brave-browser/issues/24885) & [#24888](https://github.com/brave/brave-browser/issues/24888)

------------------------
Verification passed on

Brave | 1.43.79 Chromium: 104.0.5112.102 (Official Build) beta (64-bit) 
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [ brave/brave-core#14135](https://github.com/brave/brave-core/pull/14135)
- Verified after creating a new account correct network is selected
- Verified last created account is properly selected when switching networks
- Verified correct network is selected when switching between accounts
- Verified with create account/import/hardware import accounts 
- Encountered [#24885](https://github.com/brave/brave-browser/issues/24885) & [#24888](https://github.com/brave/brave-browser/issues/24888)
