### ISSUE TITLE
Update sync to production server

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#2211]
with corresponding DEPS

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Windows 7 x64

Used testcase from https://github.com/brave/brave-core/pull/944
