### ISSUE TITLE
Manual test run on` Android ARM` for `1.37.x - Release #4`

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#22116]
## Installer

- [x] Check that installer is close to the size of the last release
- [x] Check the Brave version in About and make sure it is EXACTLY as expected

### Rewards

- [x] Verify that you are able to successfully join Rewards on a fresh profile

## Upgrade

Pre-Requisite: Visit several websites so Top Tiles under New Tab Page get updated and add several sites via `Add to Home screen` (from 3 dots menu) using a previous build/installation before upgrading.

- [x] Make sure that data from the last version appears in the new version OK
- [x] Ensure that `brave://version` lists the expected Brave & Chromium versions
- [x] With data from the last version, verify that
  - [x] Bookmarks are preserved (Folders/Sites)
  - [x] Cookies are preserved
  - [x] Per site shield settings are preserved
  - [x] Opened tabs can be reloaded
  - [x] Stored passwords are preserved
  - [x] Sync chain created in previous version is retained
  - [x] Setting changes are preserved (Default SE, Shield settings, Homepage etc..)
  - [x] Top Tiles under New Tab Page are preserved
  - [x] Home screen shortcuts are preserved
  - [x] Rewards
    - [x] Wallet balance is retained
    - [x] Auto-contribute list is retained
    - [x] Both Tips and Monthly Contributions are retained
    - [x] Wallet panel transactions list is retained
    - [x] Changes to rewards settings are retained
  - [x] Ads
    - [x] Both `Estimated pending rewards` & `Ad notifications received this month` are retained
    - [x] Changes to ads settings are retained
    - [x] Ensure that ads are not being enabled when upgrading to a new version if they were disabled
    - [x] Ensure that ads are not disabled when upgrading to a new version if they were enabled

**Comment by kjozwiak** [comment]
As per the discussion with @SergeyZhukovsky, we'll need to go through the above using the following upgrade paths:

* [ ] `1.37.109` -> `1.37.112`
* [ ] `1.37.110` -> `1.37.112`
* [ ] `1.37.111` -> `1.37.112`
* [ ] `1.37.109` -> `1.37.110` -> `1.37.111` - > `1.37.112`

**Comment by Uni-verse** [comment]
Verified using version `1.37.112, Chromium 110.0.4896.79` on `Samsung Galaxy S21` running `Android 12`

**Upgrade scenario: 1.37.110 C: 100.0.4896.60 -> 1.37.112 C: 100.0.4896.79**

PASS - Data
PASS - Rewards
PASS - Ads
PASS - Toggling P3A in privacy settings

**Clean Install 1.37.112**

PASS - Toggling On/Off P3A in privacy settings
PASS - Opting in/out P3A screen
PASS - User able to successfully complete onboarding flow when opting in/out of P3A
PASS - Able to join rewards on clean profile


<img width="416" alt="Screen Shot 2022-04-05 at 10 58 11 PM" src="https://user-images.githubusercontent.com/17885425/161906658-0756bd18-4752-404c-9eb6-29d3ccc33e9d.png">

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 12` running `1.37.112, Chromium 110.0.4896.79`

![Screenshot_20220406-021647](https://user-images.githubusercontent.com/2602313/161909797-185a3f13-883f-4534-b3ab-9dd6eebc634a.png)

Upgrading from `1.37.111 C: 100.0.4896.79` to `1.37.112 C: 100.0.4896.79` - **PASSED**

* Went through the checklist via https://github.com/brave/brave-browser/issues/22116#issue-1194003254 and ensured that all the data was retained after an upgrade.
