### ISSUE TITLE
Dapps panel: Open accounts selection in a DApps panel

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#22126]
We should open a list of accounts to pick from when we click on Account image in the DApps panel.

**Comment by kjozwiak** [comment]
The above will require `1.40.78` or higher for `1.40.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.40.101 x64 build
- Verified steps from [brave/brave-core#13359](https://github.com/brave/brave-core/pull/13359)
- Verified able to switch between accounts on wallet panel 
- Verified able to add a new account from the add account panel while switching between accounts

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/174068250-5c76ba55-f5a8-46c6-a680-41dc451dedd5.mp4> | <video src=https://user-images.githubusercontent.com/17010094/174068859-7ca6e753-6759-4d5a-9c9f-23f7fffe9665.mp4>
