### ISSUE TITLE
Browser crash when selecting 'Send to your devices'

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#22128]
## Description 
Brave crashes when clicking on send to device in Android.

## Steps to reproduce 

Prerequisite: ensure that syncing is enabled and `Open Tabs` is selected on both the `Desktop` & `Android` devices.

   1. Open the menu
   2. Click on share
   3. Select 'send to your devices'

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
Above will require `1.37.113` or newer for `1.37.x` verification.

**Comment by steveharman** [comment]
I'm still getting this on Android with 1.37.112 - is that expected?

**Comment by steveharman** [comment]
Cool. Thanks

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 12` using the following build(s):

```
Brave | 1.37.114 chromium: 100.0.4896.88 (official build) (32-bit)
--- | ---
Revision | 4450653bfa91182e85723d8f1dee64dd6ce40ed4-refs/branch-heads/4896@{#1086}
OS | android 12; build/sp2a.220405.004
```

Went through the STR/Cases outlined via https://github.com/brave/brave-browser/issues/22128#issue-1194876899 & https://github.com/brave/brave-core/pull/12920#issuecomment-1091783187. Example:

**`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------|-----------------
![Screenshot_20220413-134014](https://user-images.githubusercontent.com/2602313/163240918-63327cdd-58c5-48e4-a623-103ed7d1c06b.png) | ![Screenshot_20220413-134018](https://user-images.githubusercontent.com/2602313/163240928-5bbb8978-ffc3-47be-9041-4ec1a23de854.png) | ![desktopSharing1](https://user-images.githubusercontent.com/2602313/163240978-9274cdc5-93e5-498c-af6a-4238a6d83eaf.png) | ![sharedOpened](https://user-images.githubusercontent.com/2602313/163241016-46314f08-532c-46dc-92dd-b03db56ea172.png)

**Comment by marc0der** [comment]
Hi @samartnik @kjozwiak sadly this is still broken in 1.37.113. The verification only seemed to be for 114. If that indeed fixes it, when will this be released? This is a feature that I hugely rely on and would love to see working again.

**Comment by AdnanHodzic** [comment]
I can also confirm problem is still here on 1.37.113.

**Comment by bsclifton** [comment]
cc: @mkarolin @emerick

**Comment by marc0der** [comment]
This has been resolved now, thanks all!

**Comment by bsclifton** [comment]
1.37.116 is out now - so we should be good to go 😄 Closing
