### ISSUE TITLE
PR CI build StandaloneSetup.exe ends with "Installation failed"

### ISSUE THREAD

**Issue by mherrmann** [brave/brave-browser#22122]
## Description 

Running `BraveBrowserStandaloneNightlySetup_<version>.exe` produced by a PR CI build ends with error "Installation failed". This does not happen for "official" builds, such as Brave's release builds (on any channel), or builds produced by CI job `test-brave-browser-build-windows-x64`. It does appear on CI jobs `brave-core-build-pr-windows`.

## Steps to Reproduce

   1. Create a Pull Request in brave-core.
   2. Run the file `BraveBrowserStandaloneNightlySetup_<version>.exe` uploaded to S3 by the associated CI build.
   3. Accept the UAC dialog with Yes to install Brave as admin.

## Actual result:

A Brave browser window opens. Behind it, the installer window stays open and says "Installation failed".

Looking at the PC, "Brave Development" gets installed in `%LOCALAPPDATA%. This is interestingly similar to https://github.com/brave/brave-browser/issues/18711

## Expected result:

A Brave browser window should open. The installer window behind it should say "Installation succeeded".

Brave should be installed in `C:\Program Files`.

## Reproduces how often: 

Always.

## Brave version (brave://version info)

1.39.33.

**Comment by mherrmann** [comment]
The problem also appears when building locally with:

```
npm run build -- Static --channel=nightly --skip_signing --target_arch=x64
npm run create_dist -- Static --channel=nightly --skip_signing --target_arch=x64 --build_omaha --tag_ap=x64-ni
```

I suspect it occurs because this is not an ["official" build](https://www.chromium.org/developers/gn-build-configuration/#official-chrome-build) in Chromium's definition.

**Comment by Neustradamus** [comment]
There is a problem with user profile which is not in the good folder!

Linked to:
- https://github.com/brave/brave-browser/issues/1473
- https://github.com/brave/brave-browser/issues/4609

**Comment by mherrmann** [comment]
We no longer build StandaloneSetup.exe for PR CI builds since https://github.com/brave/devops/pull/10163. So this issue has become obsolete.

**Comment by Neustradamus** [comment]
@mherrmann: The cited link is 404 error...

Why have you stopped?

**Comment by mherrmann** [comment]
@Neustradamus this issue is about problems with copies of StandaloneSetup.exe that were produced by CI builds. CI builds no longer create this file. So this issue is obsolete. Therefore, I closed it.
