### ISSUE TITLE
Clear clipboard after pasting into restore seed words box

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#22129]
We should be clearing the clipboard after it is used to paste in recovery seed words 

Also please do this for importing private key via pasting.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.39.108 Chromium: 101.0.4951.67 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>8888ee7a24e2c36661ddb9536c35b7d4852a3a98-refs/branch-heads/4951@{#1230}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22621.1)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/12924>brave/brave-core#12924</a></li>
         <li>Verified clipboard is cleared once contents are pasted in restore seed word box and private key import screen</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/169225749-a532e071-525a-4ead-886a-133aee6b8899.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/169227767-4d75e68d-b71a-42c7-9493-ccb9b5106226.mov>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/169227849-615c7d8a-d39a-4f67-a3cb-35196d5c9576.mov>
      </td>
   </tr>
</table>
