### ISSUE TITLE
Discord Scrolling mainly through chats is messed up since atleast a few months

### ISSUE THREAD

**Issue by washingleavesandthensome23-434** [brave/brave-browser#22134]
## Description 

while scrolling up or down... chat jumps back up to beginning scroll point

## Steps to Reproduce

   1. while scrolling up or down... chat jumps back up to beginning scroll point
   2. 
   3. 

## Actual result:

while scrolling up or down ...chat jumps back up to beginning scroll point

## Expected result:
smooth scrolling up and down without jumps back to scroll start position

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.39.36 Chromium: 100.0.4896.79 (Official Build) (64-bit)
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | Windows 10 

## Version/Channel Information:

no , happens on any 

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? no idea

**Comment by washingleavesandthensome23-434** [comment]
would be nice to see this fixed

**Comment by rebron** [comment]
cc: @ryanbr

**Comment by ryanbr** [comment]
Is this still an issue @washingleavesandthensome23-434 ? I Recently checked this, had no issues scrolling. Does aggressive mode in shields help? Does every discord channel cause it, or a specific channel ? Happy to join a discord channel to test.

**Comment by ryanbr** [comment]
Closing, still works for me. Tested in clean Brave profile (latest build). Version 1.41.96  @washingleavesandthensome23-434
