### ISSUE TITLE
eliminate or sandbox wallet some npm dependencies

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#22139]
this issue is to track removal or sandboxing (ex: load using lavamoat or move into a `chrome-untrusted` frame) of NPM dependencies in wallet webUI that either have a lot of subdependencies or aren't well-audited:

- [x] fuse.js - currently only used in swap, which is another feature we can consider moving into an untrusted frame; will be used in the new coingecko market data view
- [ ] recharts - generally used for drawing wallet charts

**Comment by bbondy** [comment]
I would guess recharts is harder to get rid of and can easily be chrome-untrusted frame'd. cc @petemill to please give an example in the issue of something already doing this. 
I think fuse.js could be eliminated fairly easily. cc @onyb

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.62.130 Chromium: 120.0.6099.199 (Official Build) beta (64-bit)
-- | --
Revision | `6d589c6dc0f3489830d40332c82cdd5597e41c88`
OS | Windows 11 Version 23H2 (Build 22631.2861)

- Verified steps from [brave/brave-core#20678](https://github.com/brave/brave-core/pull/20678)
- Verified portfolio chart and asset value chart work as expected based on time selection

---------------------

**Verification passed on**

Brave | 1.62.130 Chromium: 120.0.6099.199 (Official Build) beta (64-bit)
-- | --
Revision | `6d589c6dc0f3489830d40332c82cdd5597e41c88`
OS | Linux

- Verified steps from [brave/brave-core#20678](https://github.com/brave/brave-core/pull/20678)
- Verified portfolio chart and asset value chart work as expected based on time selection

---------------------

**Verification passed on**

Brave | 1.62.130 Chromium: 120.0.6099.199 (Official Build) beta (arm64)
-- | --
Revision | `6d589c6dc0f3489830d40332c82cdd5597e41c88`
OS | macOS Version 14.2.1 (Build 23C71)

- Verified steps from [brave/brave-core#20678](https://github.com/brave/brave-core/pull/20678)
- Verified portfolio chart and asset value chart work as expected based on time selection
