### ISSUE TITLE
Brave News: re-enable peeking card on Android

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#22135]
## Description 
Re-enable the peeking card on new tab page 

This was disabled with https://github.com/brave/brave-browser/issues/21477 for 1.36

## Steps to reproduce 

1. Go to new tab page
2. At the bottom, there should be a peeking card

## Actual result 
No peeking card

## Expected result
Should be a peeking card you can swipe up and opt-in to Brave News

**Comment by alexsafe** [comment]
Should this be release-notes/exclude? @bsclifton @kjozwiak @anthonypkeane

**Comment by bsclifton** [comment]
Maybe this can be `release-notes/include` and we can capture `Enable Brave News in NTP by default` for issue title (or something like this)

**Comment by kjozwiak** [comment]
The above requires `1.38.107` or higher for `1.38.x` verification.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+` running `Android` using the following build(s):

```
Brave | 1.38.108 Chromium: 101.0.4951.41 (Official Build) (64-bit)
--- | ---
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | Android 12; Build/SP1A.210812.016
```

Basically ensuring that reverting the above via https://github.com/brave/brave-core/pull/13180 didn't cause any issues via the following:

* ensured that the Brave News opt-in card isn't visible when first launching Brave
* ensured that the Brave News opt-in card isn't appearing after restarting the browser several times
* ensured that the Brave News opt-in card isn't appearing when switching between vertical/horizontal views
* ensured that you can enable Brave News via `Settings` without any issues
* ensured that you can disable Brave News via `Settings` without any issues
