### ISSUE TITLE
Incorrect Pending message for uphold

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#22133]
## Description 

Incorrect Pending message for uphold

## Steps to Reproduce

   1. Follow the steps from https://github.com/brave/brave-browser/issues/22131#issue-1194953525
  

## Actual result:

![image](https://user-images.githubusercontent.com/38657976/162042065-01bbb90e-045f-40c6-a0d0-4b4ad4bc8ed3.png)

## Expected result:
![image](https://user-images.githubusercontent.com/38657976/162042132-ef0edded-f421-450a-872b-8cef37b980bd.png)

## Reproduces how often: 

Easy
## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @Miyayes @gpestana @szilardszaloki @LaurenWags 

Please refer slack thread for more info https://bravesoftware.slack.com/archives/C0NPFB6H5/p1649265976224599?thread_ts=1648750147.596179&cid=C0NPFB6H5

**Comment by Miyayes** [comment]
Should already be solved by: https://github.com/brave/brave-core/pull/12806 Will close issue.
