### ISSUE TITLE
Websites won't auto-translate to English (or chosen language)

### ISSUE THREAD

**Issue by LITDataScience** [brave/brave-browser#22144]
## Description 
Automatic page language translation does not happen in Brave. When we browse a new website in a different language, it doesn't automatically translate it for us. If there is a feature in the settings, it's so hidden that I cannot find it. Please add the feature (if already present) in a more dynamic/presentable way or create this new Feature (if absent in brave)

## Steps to Reproduce

   1. Go to any website to try which is not in your native language. I tried navigating to [https://global.jd.com/](JD.com)
   2. My native language is English. It does not automatically translate the web page for me into English.
   3. Couldn't find a setting on how to set it up in Brave.
   4. To translate it, we have to use third-party software like Google Translate. The issue with GT is that every time we navigate or refresh, we have to manually click on translate again.

## Actual result:
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/42968469/162103177-598ea79f-cd12-4beb-9b36-93ffa4e56e20.png">

## Expected result:
Should translate to English, or any native language region specific.

## Reproduces how often: 
Easily reproduced every time.

## Brave version (info found on brave://version)
Brave | 1.37.111 Chromium: 100.0.4896.79 (Official Build) (64-bit)
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | Windows 11 Version 22H2 (Build 22581.200)

## Version/Channel Information:
All channels/websites not in native English

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Not tried.
- Can you reproduce this issue with the nightly channel? Not tried

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? No. It happens automatically in chrome and other browsers like Edge

## Miscellaneous Information:
NA

**Comment by atuchin-m** [comment]
Implemented in https://github.com/brave/brave-browser/issues/23813
