### ISSUE TITLE
Change unstoppable domains user opt-in interstitial from Cloudflare DoH to ethereum option

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#22148]
We're soon retiring DoH option, so we should use ethereum option in the interstitial for user onboarding.

Interstitial was first introduced by https://github.com/brave/brave-core/pull/7702.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.40.80 Chromium: 102.0.5005.78 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22621.1)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/13256>brave/brave-core#13256</a></li>
         <li>Verified when method to resolve is set to <code>Ask</code>, interstitial page is shown</li>
         <li>Verified selecting proceed on interstitial page, sets method to resolve to <code>Ethereum</code></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td><b><code>.crypto</code> domain</b>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/171417805-a3de7eea-3a80-4ca1-b382-cac1ff85f1ae.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/171419415-7762746f-35a4-4ee8-8c25-4a6cf99cc231.mov>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/171419193-92bbc2f3-f265-4886-b6d5-90d1f00a0453.mov>
      </td>
   </tr>
   <tr>
      <td><b><code>.eth</code> domain</b>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/171419727-3b4df5cf-9a83-430f-a398-9abdd91d38f6.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/171420018-b8aabe44-11cb-43cd-b7fd-a130542de077.mov>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/171419758-b84ac555-fe02-4c6a-8623-4d532de105f7.mov>
      </td>
   </tr>
</table>

**Comment by srirambv** [comment]
Verification passed the following devices running 1.40.101 x64 build
- Verified steps from [brave/brave-core#13256](https://github.com/brave/brave-core/pull/13256)
- Verified when method to resolve is set to `Ask`, interstitial page is shown
- Verified selecting proceed on interstitial page, sets method to resolve to `Ethereum`

**Oppo Reno 5 (Android 12)**

`.crypto` domain | `.eth` domain
-- | --
<video src=https://user-images.githubusercontent.com/17010094/174278544-cf2dfaa1-49d9-477b-9ce8-0e5352448561.mp4> | <video src=https://user-images.githubusercontent.com/17010094/174278910-f1cc90cc-80d1-4988-8db9-049b17e62ca1.mp4>

**Samsung Tab A (Android 10)**

`.crypto` domain | `.eth` domain
-- | --
<video src=https://user-images.githubusercontent.com/17010094/174279115-39688f79-b86f-4a17-93a8-dcb3163422ee.mp4> | <video src=https://user-images.githubusercontent.com/17010094/174279075-a94f5a1a-bc59-48a8-a51b-644327e6d5cf.mp4>
