### ISSUE TITLE
Retire the option of using DNS over HTTPS for unstoppable domains resolution

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#22149]
Once we have L2 solution working, we should retire the option of using DNS over HTTPS for unstoppable domains and remove related codes.

See https://github.com/brave/brave-core/pull/7702 for reference.

**Comment by yrliou** [comment]
We would like to do the same for ENS too. And we can remove the obsolete codes for supporting DoH option.

**Comment by yrliou** [comment]
@supermassive FYI, We also need to retire the option in Android at the same time too, see https://github.com/brave/brave-core/pull/8520.

**Comment by kjozwiak** [comment]
The above requires `1.40.80` or higher for `1.40.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.40.105 x64 build
- Verified steps from <a href=https://github.com/brave/brave-core/pull/13354>brave/brave-core#13354</a>
- Verified if the setting was set to `DNS over HTTPS`, upgrading reset it back to `Ask`
- Verified UD and ENS still work correctly with Ethereum option.

Remove DoH upon upgrade | Ask/UD /Ethereum Name Service
-- | --
<video src=https://user-images.githubusercontent.com/17010094/174642190-2f893d6e-5818-4446-bc30-a905afd48ca0.mp4> | <video src=https://user-images.githubusercontent.com/17010094/174642201-c06b7643-9c42-4fec-87b0-79f50c4552e3.mp4>
