### ISSUE TITLE
Unstoppable Domains layer 2 support for resolving domains in URL bar

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#22147]
Ability to resolve domain registries under the Unstoppable Naming System (UNS) (.crypto, .x, .coin, .nft, .dao, .wallet, .888, .blockchain, and .bitcoin registries) on both Ethereum and Polygon chains in the URL bar.

We should revise `UnstoppableDomainsProxyReaderGetMany` to get result from Polygon chain, then ethereum mainnet if not found on Polygon.

Ref: layer 1 support was implemented by https://github.com/brave/brave-core/pull/8456.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.40.68/75 Chromium: 102.0.5005.61 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22621.1)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/13202>brave/brave-core#13202</a></li>
         <li>Verified visiting UD domains triggers browser permission to use UD Layer 2 to resolve domains</li>
         <li>Verified once approved loads the correct page or redirects based on how its setup</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>uns-devtest-fda7a9.x
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/170673877-583208d0-608c-43d2-95f9-1cba0890ca0e.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/170677892-6f6440c5-d52d-45fe-9cb3-fac0c81e93e5.mov>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/170677875-a5435930-8b4a-4e34-a934-3c5932f67bda.mov>
      </td>
   </tr>
   <tr>
      <td>uns-devtest-brave.x
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/170673854-96ef6390-77de-4084-b0ba-51f0560a8c72.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/170677865-23b2f56d-aa7c-4810-ab80-10b74ba61b87.mov>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/170677829-42315c49-bca1-4c0d-aa27-dfa8c3fcb025.mov>
      </td>
   </tr>
</table>

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.40.83 x64 beta build
- Verified steps from [brave/brave-core#13202](https://github.com/brave/brave-core/pull/13202)
- Verified visiting UD domains triggers browser permission to use UD Layer 2 to resolve domains
- Verified once approved loads the correct page or redirects based on how its setup 
- Encountered [#23231](https://github.com/brave/brave-browser/issues/23231)


uns-devtest-fda7a9.x | uns-devtest-brave.x
-- | -- 
<video src=https://user-images.githubusercontent.com/17010094/171838907-6d2ce2fb-1794-4a52-8f11-f0ef4e5ee0d6.mp4> | <video src=https://user-images.githubusercontent.com/17010094/171838895-230539f2-fd69-48cf-91ae-799a8fe95d22.mp4>

----------------------
Verification passed on Samsung Tab A with Android 10 running 1.40.83 x64 beta build
- Verified steps from [brave/brave-core#13202](https://github.com/brave/brave-core/pull/13202)
- Verified visiting UD domains triggers browser permission to use UD Layer 2 to resolve domains
- Verified once approved loads the correct page or redirects based on how its setup 
- Encountered [#23231](https://github.com/brave/brave-browser/issues/23231)


uns-devtest-fda7a9.x | uns-devtest-brave.x
-- | -- 
<video src=https://user-images.githubusercontent.com/17010094/171840160-5ecf619b-1514-4039-ab3a-4363803eaa75.mp4> | <video src=https://user-images.githubusercontent.com/17010094/171840144-56c847c5-3bb6-4b67-ba30-2abd7cd7f688.mp4>
