### ISSUE TITLE
Unstoppable Domains layer 2 support for resolving eth address in brave wallet

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#22146]
Ability to resolve domain registries under the Unstoppable Naming System (UNS) (.crypto, .x, .coin, .nft, .dao, .wallet, .888, .blockchain, and .bitcoin registries) on both Ethereum and Polygon chains to eth address in brave_wallet.

Resolving flow:
![Resolve L2 and L1 domain](https://user-images.githubusercontent.com/4730197/162117607-e53b30c3-2ddb-4c42-b285-4e325ba59ca3.png)

We should revise `JsonRpcService::UnstoppableDomainsGetEthAddr` to call contracts on Polygon first then ethereum if not found in Polygon.

Ref: Layer 1 support was implemented by https://github.com/brave/brave-core/pull/10447.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.40.80 Chromium: 102.0.5005.78 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22621.1)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified address on both L1 and L2 are resolved</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/171447002-cddb2680-7814-4caf-8c63-d36294bf6cab.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/171447348-c256bcf7-3fa5-4a3b-98b6-c858599975aa.mov>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/171447023-c82363c2-ac0c-4596-b915-cd1dd16311bf.mov>
      </td>
   </tr>
</table>

**Comment by srirambv** [comment]
Removing Android label as this is be handled separately on Android via #23223
