### ISSUE TITLE
Do not use selected network when resolving UD/ENS domains to eth address

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#22151]
Currently we are using selected network when resolving UD/ENS domains to eth address in brave wallet, which doesn't make much sense. 
For UD, we should always call unstoppable domains' contracts on ethereum mainnet (and polygon once we have L2 support).
For ENS, we should always call the contracts on ethereum mainnet.
And we should allow the resolution on all EVM network instead of just a few networks, for example, we only allow UD on mainnet and rinkeby at the moment.

**Comment by supermassive** [comment]
UD part is fixed here https://github.com/brave/brave-core/pull/13085
ENS part is fixed here https://github.com/brave/brave-core/pull/13202

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/22147#issuecomment-1139471688

**Comment by srirambv** [comment]
Android verification done as part of https://github.com/brave/brave-browser/issues/22147#issuecomment-1145840696
