### ISSUE TITLE
Return ETH and BAT as visible tokens for new accounts

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#22156]
## Description 
`getUserAssets` method should return `ETH` and `Bat` as a visible token on `Ethereum Mainnet` by default for a new/restored account and return `ETH` as a visible token for all `Test networks`

https://user-images.githubusercontent.com/40611140/162225663-9b7a2fd4-86e6-4303-806c-c9518c03165a.mov

**Comment by yrliou** [comment]
Regressed due to https://github.com/brave/brave-core/pull/12905
