### ISSUE TITLE
Unable to Check or Uncheck a Native assets in the Edit Visible Assets modal

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#22159]
## Description 
Currently the `Edit Visible Assets` modal is not allowing you to check or uncheck a native asset.

**Comment by kjozwiak** [comment]
Above requires `1.38.105` or higher for `1.38.x` verification 👍

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">  1.38.107 Chromium: 101.0.4951.41 (Official Build)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22598.200)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td>
      </td>
      <td colspan=3>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/12955> brave/brave-core#12955</a></li>
         <li>Verified able to select/unselect native token from edit visible asset modal and updates the tokens under account</li>
         <li>Encountered <a href=https://github.com/brave/brave-browser/issues/22556>#22556</a></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/165285891-2c80d491-f8d1-4cd4-9fc1-1d046f392fae.mp4>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/165281318-4979a989-c798-413e-87b8-654dda3417c2.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/165281265-235ccd67-49f7-4863-ab51-ed56aeb2b394.mov>
      </td>
   </tr>
</table>
