### ISSUE TITLE
Selecting a Network is not dismissing the Network List

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#22165]
## Description 
Selecting a Network is not dismissing the Network List in the `Buy/Send/Swap` widget.

https://user-images.githubusercontent.com/40611140/162332101-68ce6300-fec7-423d-a89f-c0c94a5bcc01.mov

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.39.96 Chromium: 101.0.4951.54 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>67da1aeb32cedd27634ca6634fb79cbd85d3f0ab-refs/branch-heads/4951@{#1126}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22616.1)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from issue description</li>
         <li>Verified selecting a network automatically closes the network selector list</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/168002351-aa5e5765-e7a4-442e-890a-9a42912dfe6b.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/168002964-d7324a01-778d-4f11-89d5-a7eb86a88a69.mov>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/168003015-5de993ce-56ea-4bd7-8b66-15750bef1534.mov>
      </td>
   </tr>
</table>
