### ISSUE TITLE
Wrong ko translation in shields v2 panel

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#22167]
When shields is on, shields say `사이트가 깨져 보이는 것 같습니다.`
`사이트가 깨져 보이는 것 같습니다.` equals `This site seems broken.`
However, original eng sentence is `If this site seems broken,`.
So, it should be translated to `사이트가 깨져 보이면,`

<img width="413" alt="스크린샷 2022-04-08 오전 9 45 41" src="https://user-images.githubusercontent.com/6786187/162341777-74232ef9-6f06-4dcf-a32a-7003fd353850.png">

**Comment by simonhong** [comment]
one more - "brave.com 에 대해 **실드 활성화됨**" would be better instead of "**다음에 대해 실드** 활성화됨 brave.com"

**Comment by simonhong** [comment]
Updated to transifex

**Comment by rebron** [comment]
cc: @mkarolin

**Comment by mkarolin** [comment]
Update on Transifex. The new translation will get pulled for 1.38.x

**Comment by mkarolin** [comment]
Fixed via https://github.com/brave/brave-core/pull/13147

**Comment by kjozwiak** [comment]
The above requires `1.38.106` or higher for `1.38.x` verification.

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```

Brave | 1.38.106 Chromium: 101.0.4951.41 (공식 빌드) (64비트)
-- | --
개정 | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | Windows 10 Version 21H2 (Build 19044.1645)

```
- Verified the description and ensured that the string `If this site seems broken` is translated in `Korean`
![image](https://user-images.githubusercontent.com/38657976/165265848-709f8513-b4bf-4a4b-9634-e0d5caee5375.png)
