### ISSUE TITLE
Shields' blocked count gets clipped when 4 or more digits

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#22161]
## Description 

Shields' blocked count gets clipped when 4 or more digits

## Steps to Reproduce

   1. install `1.39.39`
   2. launch Brave
   3. load a site with heavy ads/trackers (Words with Friends, Facebook games, etc.)
   4. click on the `99+` after some time
   5. look at the formatting of the blocked-elements count

## Actual result:

Clipping of the 4th digit in the blocked-elements count.

example | example
---------|---------
<img width="826" alt="Screen Shot 2022-04-07 at 1 54 32 PM" src="https://user-images.githubusercontent.com/387249/162305337-3f56c123-9fb7-495c-885e-d8d21140a429.png"> | <img width="504" alt="Screen Shot 2022-04-07 at 1 55 50 PM" src="https://user-images.githubusercontent.com/387249/162305385-9f0c61dc-c4fe-42d1-aa0a-6966abca2668.png">

## Expected result:

No clipping of the blocked elements #.

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.39.39 Chromium: 100.0.4896.79 (Official Build) nightly (x86_64)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | macOS Version 11.6.5 (Build 20G527)

cc @nullhook @Tonev

**Comment by rebron** [comment]
cc: @aguscruiz

**Comment by kjozwiak** [comment]
Above requires `1.38.102` or higher for `1.38.x` verification.
