### ISSUE TITLE
Windows Standalone installer: Two browser windows open when installing as non-admin

### ISSUE THREAD

**Issue by mherrmann** [brave/brave-browser#22179]
## Steps to Reproduce

   1. Run Brave's StandaloneSetup.exe.
   2. Reject the UAC dialog asking for admin privileges.
   3. Accept the follow-up dialog "do you want to install as normal user?" with yes. This installs Brave for just the current user into `%LOCALAPPDATA%` instead of `C:\Program Files`.

## Actual result:

Two browser windows open, in addition to the installer dialog:

![2022-04-08 19_05_41-Window](https://user-images.githubusercontent.com/1076393/162489362-f7a7c30b-53fc-44cd-8726-ba706b9d2fc3.png)

## Expected result:

Just one browser window should open.

## Reproduces how often: 

Always.

## Brave version (brave://version info)

Release 1.37.111.

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Probably
- Can you reproduce this issue with the nightly channel? Yes

## Miscellaneous Information:

A very similar bug #1833 affected Brave's online installer.

**Comment by mherrmann** [comment]
Just ran into https://github.com/brave/brave-browser/issues/22122 while working on this.

**Comment by LaurenWags** [comment]
@brave/legacy_qa we should check Win 10 and 11 at a minimum. Win 8 and 7 would be helpful, but not strictly necessary.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using

Brave | 1.39.83 Chromium: 101.0.4951.41 (Official Build) beta (64-bit)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | Windows 11 Version 21H2 (Build 22000.613)

- Downloaded `BraveBrowserStandaloneBetaSetup.exe` from https://github.com/brave/brave-browser/releases/tag/v1.39.84
- Double-clicked to install
- Click No on the User Access Control prompt 
- Clicked Yes when prompted Brave can be installed without admin privileges. Continue?
- Let installation finish
- Checked # of launched Brave windows, post-install
- Verified only one (1) browser window was launched, post-install.

ex1|ex2|ex3|ex4|ex5|ex6|ex7
---|---|---|---|---|---|---
<img width="950" alt="downloads" src="https://user-images.githubusercontent.com/98358127/165840277-55a84ba1-f83f-41ad-a82e-dcaf737ed4e7.png">|<img width="296" alt="admin" src="https://user-images.githubusercontent.com/98358127/165840473-8f286734-69b2-4bae-a781-2c6eca287892.png">|<img width="950" alt="ss1" src="https://user-images.githubusercontent.com/98358127/165840970-0112c79d-04ba-4a65-ab3b-4546cf2c3ff1.png">|<img width="950" alt="ss4" src="https://user-images.githubusercontent.com/98358127/165841979-bc9cb5f1-e9ce-469b-ad64-4ae670541ed6.png">|<img width="950" alt="ss2" src="https://user-images.githubusercontent.com/98358127/165841145-040ea4f3-8186-421d-a516-290173f37776.png">|<img width="950" alt="downloads" alt="ss3" src="https://user-images.githubusercontent.com/98358127/165841438-7a30c9d4-5656-4602-a275-bbd6a6dc0bb3.png">|<img width="950" alt="version" src="https://user-images.githubusercontent.com/98358127/165844053-f5155890-9f17-45d9-ad6d-bb3ddb378954.png">
