### ISSUE TITLE
Rewards ad earnings claim CAPTCHA cannot be completed (starting April 2022) 

### ISSUE THREAD

**Issue by johngilbert2000** [brave/brave-browser#22180]
Just ran into this same issue from 2018, which is closed: 
https://github.com/brave/brave-browser/issues/1350

## Description 

I can't claim brave rewards, as the captcha keeps failing. I disabled all extensions. Tried two different monitors (22" and 14"). Zooming in and out doesn't affect the pop up, but I tried it anyway. Resolution is 1920x1080, with no additional scaling on Ubuntu 20.04.

## Steps to Reproduce

   1. Install Brave Beta
   2. Navigate to Brave Rewards
   3. Attempt to claim token grant.

## Actual result:
"Hmm… Not Quite. Try Again." message gets displayed every time.

## Expected result:
I get my rewards.

## Reproduces how often: 
Every time.

## Brave version (brave://version info)
```
Brave | 1.37.111 Chromium: 100.0.4896.79 (Official Build) (64-bit)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | Linux
JavaScript | V8 10.0.139.9
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.79 Safari/537.36
```

## Miscellaneous Information:
References:

https://github.com/brave/brave-browser/issues/1350

https://community.brave.com/t/cant-claim-tokens-due-to-prove-youre-human-bug/101361

https://www.reddit.com/r/brave/comments/q7vn61/cant_prove_im_human_to_claim_my_ads_rewards/

https://community.brave.com/t/can-t-claim-tokens-due-to-prove-you-re-human-bug-again-accidently-put-the-wrong-gif-on-my-other-one-sorry/289555

https://community.brave.com/t/prove-that-human-fails/288713

https://www.reddit.com/r/brave/comments/q3hd1v/verify_you_are_human_drag_brave_triangle/

**Comment by Miyayes** [comment]
In the meantime, try 150% or 125%, etc. scaling factors to see if they work. We are taking another look at it to see if we can roll another round of improvements to the captcha's reliability.

**Comment by Miyayes** [comment]
+1 https://www.reddit.com/r/BATProject/comments/tvcjtw/weekly_bat_discussion_thread/i3xopgy/?context=3

**Comment by zenparsing** [comment]
Great find @Miyayes

**Comment by Miyayes** [comment]
> Great find @Miyayes

Credit to Emerick :)

**Comment by kjozwiak** [comment]
The above requires `1.38.106` or higher for `1.38.x` verification 👍

**Comment by LaurenWags** [comment]
@brave/legacy_qa added `QA/Test-All-Platforms` per https://github.com/brave/brave-core/pull/13072#issue-1208696805

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```

Brave | 1.38.107 Chromium: 101.0.4951.41 (Official Build) (64-bit)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | Windows 10 Version 21H2 (Build 19044.1645)

```

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.38.107 Chromium: 101.0.4951.41 (Official Build) (64-bit)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/13072

Scaling 100%

<details>

![1_1](https://user-images.githubusercontent.com/34715963/165353672-e0287007-cc4c-4528-abe0-6ae5b1eb7bfc.png)
![1_2](https://user-images.githubusercontent.com/34715963/165353676-128cdbb6-427e-4e5f-b92c-4cf90f9dc6aa.png)
![1_3](https://user-images.githubusercontent.com/34715963/165353680-7948cffe-ead6-4a3a-bccf-5b967e647f26.png)
![1_4](https://user-images.githubusercontent.com/34715963/165353683-364f315b-f609-4beb-a9f5-e0bceba9487b.png)
![1_5](https://user-images.githubusercontent.com/34715963/165353687-ee7a7328-0a32-4401-8e9c-041f9e597c61.png)


</details>

Scaling 150%

<details>

![2_1](https://user-images.githubusercontent.com/34715963/165353797-320cc305-1b53-4941-ab11-9bd433f4d43a.png)
![2_2](https://user-images.githubusercontent.com/34715963/165353804-8288cab8-047f-40e8-8076-12c23873cde3.png)
![2_3](https://user-images.githubusercontent.com/34715963/165353807-e32fdcf9-0fe5-4ada-9de1-3d7a6d46cf43.png)
![2_4](https://user-images.githubusercontent.com/34715963/165353809-45532bdb-1bab-4b8a-9596-c8aa66dd9a58.png)
![2_5](https://user-images.githubusercontent.com/34715963/165353811-b4b1479d-aea9-490a-b2c2-d04e9e8e74d8.png)


</details>

Scaling 200%

<details>

![3_1](https://user-images.githubusercontent.com/34715963/165353872-a46fda7b-87f2-41ef-a8b1-50cdb0ebba93.png)
![3_2](https://user-images.githubusercontent.com/34715963/165353879-dcb6bd12-21ee-48e6-b256-49d3acfb97dd.png)
![3_3](https://user-images.githubusercontent.com/34715963/165353881-073bd4b0-5a66-4ffc-8864-9a3bd339de5a.png)
![3_4](https://user-images.githubusercontent.com/34715963/165353884-a0608335-56c9-435f-918f-433ec45cdcf0.png)
![3_5](https://user-images.githubusercontent.com/34715963/165353887-dec50dc5-101c-42aa-8531-5479d444a0b6.png)



</details>
