### ISSUE TITLE
tapping on `Load new content` takes users to second card in feed rather than at the beginning of feed

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#22183]
## Description 

This is another follow up to https://github.com/brave/brave-browser/issues/20408 & https://github.com/brave/brave-browser/issues/21403 to basically fix the original issue on the tablet. As per the verification notes via https://github.com/brave/brave-core/pull/12852#issuecomment-1093352027, you'll notice that https://github.com/brave/brave-core/pull/12852 didn't fix the issue on the tablet. Rather than moving the user to the top of the feed as expected, it's moving users to the second card in the feed rather than at the top as expected.

## Steps to reproduce 

   1. Install Brave and enable Brave News via `Settings`
   2. once enabled, scroll through the feed and select the Brave News `Settings` hamburger menu
   3. enable several random news feeds and back to Brave News by pressing `<--` (or close `Settings` using the `X`)
   4. tap on the `Load new content` button

## Actual result 

https://user-images.githubusercontent.com/2602313/162528221-4efef61d-3675-4f13-a76f-a922a7b60791.mp4

## Expected result

When a user taps on `Load new content`, the feed should be refreshed and the view port should start at the top of the Brave News feed and not on the second card within the feed,

## Issue reproduces how often 

100% reproducible using the STR/Cases outlined above.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `No` (Different issues via https://github.com/brave/brave-browser/issues/20408 & https://github.com/brave/brave-browser/issues/21403)
- Can you reproduce this issue with the current Play Store Beta version? `Yes` 
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Samsung Galaxy Tablet A`
   - Android version: `Android 12`
   
## Brave version

```
1.39.42 Chromium: 100.0.4896.79
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

### Additional information

CCing @bsclifton @alexsafe @tapanmodh @anthonypkeane @brave/qa-team

**Comment by Uni-verse** [comment]
Able to reproduce this issue on version `1.39.42 Chromium: 100.0.4896.79` using STR from above on `Samsung Galaxy Tab S7` running `Android 12`

- Tapping on `Load new content` takes user to second card in news feed.

**Comment by Uni-verse** [comment]
Verified using version

```
Brave	1.38.113 Chromium: 101.0.4951.61 (Official Build) (64-bit) 
Revision	3b3633b32c491b4cba5fd7df3c7c0f628547cbcc-refs/branch-heads/4951@{#1189}
OS	Android 12; Build/SP1A.210812.016
```

- Ensured changing sources and tapping on `Load new content` takes user to the beginning of feed rather than second card.

https://user-images.githubusercontent.com/17885425/167745079-d8ebb750-54a2-436f-93d1-320cd56609c8.mp4

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+` running `Android 12` using the following build(s):

```
Brave | 1.38.118 Chromium: 101.0.4951.67 (Official Build) (64-bit)
--- | ---
Revision | 8888ee7a24e2c36661ddb9536c35b7d4852a3a98-refs/branch-heads/4951@{#1230}
OS | Android 12; Build/SP1A.210812.016
```

Went through the STR/Cases outlined via https://github.com/brave/brave-browser/issues/22183#issue-1197819096 and ensured that tapping on `Load new content` took the user to the start of the news feed rather than the second/third card.

https://user-images.githubusercontent.com/2602313/168516270-a6811388-eee3-419d-98e6-adc5e949c700.mp4


Verification **PASSED** on `Samsung Galaxy Tablet A` running `Android 11` using the following build(s):

```
Brave | 1.38.118 Chromium: 101.0.4951.67 (Official Build) (64-bit)
--- | ---
Revision | 8888ee7a24e2c36661ddb9536c35b7d4852a3a98-refs/branch-heads/4951@{#1230}
OS | Android 11; Build/RP1A.200720.012
```

Went through the STR/Cases outlined via https://github.com/brave/brave-browser/issues/22183#issue-1197819096 and ensured that tapping on `Load new content` took the user to the start of the news feed rather than the second/third card.

https://user-images.githubusercontent.com/2602313/168517150-fdbd0b07-fe03-4d6b-8b84-c83298817e1d.mp4
