### ISSUE TITLE
janky toggle animation when enabling/disabling websites from sources

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#22186]
## Description 

Whenever you enable/disable a Brave News source via `Settings` using the toggles, you'll notice they appear very janky. It starts out smooth then slows down and finally completes the animation sequence. When you're enabling multiple sources in fast succession, it will feel like the entire browser is slowing down due to the janky animations.

BTW, I'm running into this using a `Pixel 6` which is considered the latest/high end device so it's not due to lack of resources.

iOS has different toggles, but compared to Android, they're a lot smoother and the entire experience is a lot better. Example shown below on how iOS has smooth animations compared to Android.

## Steps to reproduce 

   1. install Brave and enable Brave News
   2. once enabled, go into the `Settings` of Brave News and pick any category under `Default Sources`
   3. start enabling/disabling websites via the toggles on the right hand side

You'll notice the slow/janky animation.

## Actual result 

https://user-images.githubusercontent.com/2602313/162552287-9f73719c-eeb2-4ef2-a767-783d2224db96.mp4

## Expected result

Example of iOS but shows you how smooth the animations are compared to `Android`:

https://user-images.githubusercontent.com/2602313/162552319-ab8113a8-d3af-425b-a22f-8ef515267eb0.mp4

## Issue reproduces how often 

100% reproducible using the STR/Cases outlined above.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `Yes`
- Can you reproduce this issue with the current Play Store Beta version? `Yes` 
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Pixel 6` (Phone)
   - Android version: `Android 12`
   
## Brave version

```
1.39.42 Chromium: 100.0.4896.79
```

### Website problems only

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

### Additional information

CCing @bsclifton @alexsafe @tapanmodh @anthonypkeane @brave/qa-team

**Comment by alexsafe** [comment]
@petemill turns out this is related to this line https://github.com/brave/brave-core/blob/8e77b4cfe3b594836f9905babb2b7dfaf6b2fade/components/brave_today/browser/brave_news_controller.cc#L293
When i comment it out things seem to be smooth. Do you think that's smth that could be improved?

**Comment by fallaciousreasoning** [comment]
I think this could be the same issue as https://github.com/brave/brave-browser/issues/23909. Would you mind retesting @kjozwiak, on Beta or Nightly?

**Comment by kjozwiak** [comment]
@fallaciousreasoning still an issue so I don't think https://github.com/brave/brave-browser/issues/23909 resolved it. Went through the STR/Cases using `1.44.41 Chromium 104.0.5112.81` on two different devices:

### `Pixel 6` running `Android 13`

https://user-images.githubusercontent.com/2602313/184450957-c9fa8546-b0ae-470a-a163-9cc986fb1575.mp4

### `Samsung S10+` running `Android 12`

https://user-images.githubusercontent.com/2602313/184451587-99c11a71-c1b8-468a-b619-d7f3ffb670f8.mp4

**Comment by fallaciousreasoning** [comment]
Hmmm, yeah, that doesn't look great. I'll add this to my list.

**Comment by deeppandya** [comment]
@kjozwiak this issue is irrelevant with new brave news settings changes. Can you please confirm and close the issue ?

**Comment by kjozwiak** [comment]
> @kjozwiak this issue is irrelevant with new brave news settings changes. Can you please confirm and close the issue ?

Nope, not valid anymore as the UI changed with `NewsV2`. There is a small lag when you `Follow & `Unfollow` a bunch of sources really quickly, but nothing compared to the original issue. Used the following build for verification:

```
Brave | 1.52.112 Chromium: 114.0.5735.35 (Official Build) (32-bit)
--- | ---
Revision | 2295354895fa3652ae47b651481831484f16d1ff-refs/branch-heads/5735@{#713}
OS | Android 13; Build/UPB2.230407.014; 33; UpsideDownCake
```

https://github.com/brave/brave-browser/assets/2602313/61d65456-1f26-4582-bfcc-265c0ab1bfb8
