### ISSUE TITLE
Solana connected status

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#22184]
Phantom’s connect status is different than MetaMask, it is not directly tied to permission, it is a separate state.
Permission is required to do connect, or eagerly connect but disconnect doesn’t remove permission, removing has to go through its “Trusted apps” (equivalent to our content settings page). 
That being said, having permission doesn't mean connected in Solana so we need an addition indicator to show that to users
<img width="353" alt="Screen Shot 2022-06-24 at 09 40 24" src="https://user-images.githubusercontent.com/11330831/175601915-30af2124-1675-477f-8405-92a2f1ae77cd.png">
<img width="352" alt="Screen Shot 2022-06-24 at 09 40 58" src="https://user-images.githubusercontent.com/11330831/175601933-a02a5623-2fca-4108-bb4f-bf9d3993a7d5.png">
<img width="361" alt="Screen Shot 2022-06-24 at 09 41 38" src="https://user-images.githubusercontent.com/11330831/175601942-0922a5c3-949c-4134-bd45-b66c92e26043.png">

For Phantom a site has to call connect API every page load to get connected state
But for MetaMask or us, connected means site has permission, so we always show connected once an user approved first connect

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.43.81 Chromium: 104.0.5112.102 (Official Build) (64-bit)
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | Linux

- Verified steps from [brave/brave-core#13993](https://github.com/brave/brave-core/pull/13993)
- Verified all 3 states for Solana account via [#22471 (comment)](https://github.com/brave/brave-browser/issues/22471#issuecomment-1227580022)

Solana (Panel)

Connected | Disconnected | Blocked 
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/186729822-4bc15978-cefa-4b9b-96ab-02da2f8dc230.png) | ![image](https://user-images.githubusercontent.com/17010094/186729701-09face8f-df41-46ce-9981-57a8bad1f789.png) | ![image](https://user-images.githubusercontent.com/17010094/186730046-990ae591-467d-43d4-afd1-2ac428f6897a.png)

------------------------
Verification passed on

Brave | 1.43.81 Chromium: 104.0.5112.102 (Official Build) (64-bit)
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | Windows 11 Version 21H2 (Build 22000.795)

- Verified steps from [brave/brave-core#13993](https://github.com/brave/brave-core/pull/13993)
- Verified all 3 states for Solana account via [#22471 (comment)](https://github.com/brave/brave-browser/issues/22471#issuecomment-1227580022)

Solana (Panel)

Connected | Disconnected | Blocked 
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/186733146-ac64a5ed-309b-4a0a-8e37-10ec82997642.png) | ![image](https://user-images.githubusercontent.com/17010094/186733058-602b481f-e1d9-46aa-9155-c52b42df7be2.png) | ![image](https://user-images.githubusercontent.com/17010094/186733534-0d4964b1-1674-4173-8d04-9fb2376a09c5.png)

------------------------
Verification passed on

Brave | 1.43.81 Chromium: 104.0.5112.102 (Official Build) (arm64)  
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [brave/brave-core#13993](https://github.com/brave/brave-core/pull/13993)
- Verified all 3 states for Solana account via [#22471 (comment)](https://github.com/brave/brave-browser/issues/22471#issuecomment-1227580022)

Solana (Panel)

Connected | Disconnected | Blocked 
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/186727570-c26b2f5b-dfc0-4dc2-898b-218274c88d02.png) | ![image](https://user-images.githubusercontent.com/17010094/186727615-9679736f-e4e2-41d1-aba9-c86884337243.png) | ![image](https://user-images.githubusercontent.com/17010094/186727636-08490dd8-3869-4a24-8935-d4b7228da2f4.png)
