### ISSUE TITLE
improve starting point of feed when tapping on `Load new content`

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#22182]
## Description 

This is another follow up to https://github.com/brave/brave-browser/issues/20408 & https://github.com/brave/brave-browser/issues/21403 to improve the behaviour of Brave News when tapping on the `Load new content` button after enabling/disabling news sources via `Settings`.

Currently, when you tap `Load new content` on a phone, it will refresh the feed and move the user to the top. However, rather than moving the view right where the feed starts, we're also displaying a large area of the NTP which is blank. We should follow the same behaviour that `iOS` in terms of starting at the beginning of the feed without any dead space. 

## Steps to reproduce 

   1. Install Brave and enable Brave News via `Settings`
   2. once enabled, scroll through the feed and select the Brave News `Settings` hamburger menu
   3. enable several random news feeds and back to Brave News by pressing `<--` (or close `Settings` using the `X`)
   4. tap on the `Load new content` button

## Actual result 

![deadSpace](https://user-images.githubusercontent.com/2602313/162525971-ec38133b-af02-4acc-abf5-1bf08c247a9f.png)

## Expected result

**`Example of what it should look like on Android`** | **`iOS Example`**
----------------------------------------------------------|---------------------
![Screenshot_20220408-162039](https://user-images.githubusercontent.com/2602313/162526068-329a0a40-8ff5-4283-b2d5-92aaf1a08de1.png) | ![IMG_3858](https://user-images.githubusercontent.com/2602313/162526078-dbca060f-eccf-4fd2-adc5-fa8f61ce4cc3.PNG)

## Issue reproduces how often 

100% reproducible using the STR/Cases outlined above.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `Yes`
- Can you reproduce this issue with the current Play Store Beta version? `Yes` 
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Pixel 6` (Phone)
   - Android version: `Andriid 12`
   
## Brave version

```
1.39.42 Chromium: 100.0.4896.79
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

### Additional information

CCing @bsclifton @alexsafe @tapanmodh @anthonypkeane @brave/qa-team

**Comment by timchilds** [comment]
@kjozwiak I can reproduce this. I don't see as much NTP empty space on my Galaxy A51 vs. your device. 

@alexsafe @tapanmodh we should try to improve this after the scrolling velocity is fixed.

https://user-images.githubusercontent.com/28269287/162535455-1ee64238-f48f-4fb0-a276-ea62a294f8ef.mp4

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+` running `Android 12` using the following build(s):

```
Brave | 1.38.118 Chromium: 101.0.4951.67 (Official Build) (64-bit)
--- | ---
Revision | 8888ee7a24e2c36661ddb9536c35b7d4852a3a98-refs/branch-heads/4951@{#1230}
OS | Android 12; Build/SP1A.210812.016
```

Went through the STR/Cases outlined via https://github.com/brave/brave-browser/issues/22182#issue-1197797305 and ensured that the large gap between the NTP and the first news card isn't appearing once `Load new content` as been tapped. Also see https://github.com/brave/brave-browser/issues/22183 for more examples of the above working as expected.

![Screenshot_20220516-001956_Brave](https://user-images.githubusercontent.com/2602313/168519303-7e542785-e0a6-4d7f-a6f6-fb63b0b047aa.jpg)
