### ISSUE TITLE
Inconsistent pluralization and missing period at end of sentence, in Brave Shields Up/Down texts

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#22189]
## Description 

Inconsistent pluralization and missing period at end of sentence, in Brave Shields Up/Down texts

## Steps to Reproduce

   1.  install `1.39.22`
   2. launch Brave
   3. load `cnn.com`
   4. click on the Shields icon in the URL bar
   5. compare text between Shields UP and DOWN states

## Actual result:

Shields UP: `Note: this may reduce Brave's privacy protections.`
Shields DOWN: `You are viewing this site without Brave's privacy protection`

Shields UP | Shields DOWN
---------------|------------
<img width="661" alt="Screen Shot 2022-04-08 at 7 57 16 PM" src="https://user-images.githubusercontent.com/387249/162561896-727f45a7-b022-488b-af7d-22c2690388b8.png"> | <img width="661" alt="Screen Shot 2022-04-08 at 7 57 21 PM" src="https://user-images.githubusercontent.com/387249/162561897-7bf7e0a5-3a90-471c-8af4-f260c3f7271b.png">

## Expected result:

Shields DOWN text should probably read `"You are viewing this site without Brave's privacy protections."`

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.39.22 Chromium: 100.0.4896.60 (Official Build) nightly (x86_64)
-- | --
Revision | 6a5d10861ce8de5fce22564658033b43cb7de047-refs/branch-heads/4896@{#875}
OS | macOS Version 12.4 (Build 21F5048e)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `no`
- Can you reproduce this issue with the beta channel?  `yes`
- Can you reproduce this issue with the nightly channel? `yes`

cc @nullhook @jenn-rhim @rmcfadden3 @rebron

**Comment by stephendonner** [comment]
Interested, @Tonev ?

**Comment by Tonev** [comment]
Hey, @stephendonner!

https://github.com/brave/brave-core/pull/12959

![6c1uv2](https://user-images.githubusercontent.com/20608253/162600486-228a8cad-a4cc-4cab-a0ae-0b0af76fc3e4.jpg)

**Comment by stephendonner** [comment]
## Verified `PASSED` using this issue's URL as a testcase, with build 

Brave | 1.39.45 Chromium: 100.0.4896.79 (Official Build) nightly (x86_64)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | macOS Version 11.6.5 (Build 20G527)

#### Confirmed text changes; thanks @Tonev!

`Shields UP` | `Shields DOWN`
---------|---------
<img width="1349" alt="Screen Shot 2022-04-11 at 3 39 14 PM" src="https://user-images.githubusercontent.com/387249/162844990-eca0b8fc-f641-4371-a322-e5da66d41aaf.png"> | <img width="1349" alt="Screen Shot 2022-04-11 at 3 39 20 PM" src="https://user-images.githubusercontent.com/387249/162844999-19eb42d1-c096-4a30-96b6-2e4fcb72c2d9.png">

**Comment by kjozwiak** [comment]
Removing `QA Pass-macOS` as this is going to be uplifted into `1.38.x` via https://github.com/brave/brave-core/pull/12991 so worth checking again just in case. However, we'll use https://github.com/brave/brave-browser/issues/22189#issuecomment-1095661528 as the verification needed to get the above uplifted.

**Comment by kjozwiak** [comment]
Above will require `1.38.93` or higher for `1.38.x` verification.

**Comment by stephendonner** [comment]
### Verified `PASSED` using 

Brave | 1.38.93 Chromium: 100.0.4896.88 (Official Build) beta (x86_64)
-- | --
Revision | 4450653bfa91182e85723d8f1dee64dd6ce40ed4-refs/branch-heads/4896@{#1086}
OS | macOS Version 12.4 (Build 21F5048e)

#### Confirmed text changes

`Shields UP` | `Shields DOWN`
-------------|------------------
<img width="1552" alt="Screen Shot 2022-04-16 at 3 03 42 AM" src="https://user-images.githubusercontent.com/387249/163670848-e86ed7e0-3fbd-4de0-a515-042c616e705c.png"> | <img width="1552" alt="Screen Shot 2022-04-16 at 3 03 46 AM" src="https://user-images.githubusercontent.com/387249/163670851-ea85ca16-2393-4e88-92c3-f42e4de240df.png">
