### ISSUE TITLE
Update l10n for 1.37.x (Chromium 100) - Part II.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#22185]
Download the latest l10n from Transifex.

Test plan:

https://github.com/orgs/brave/teams/legacy_qa should run through a few locals just to make sure that nothing obvious has regressed. Shouldn't spend too much time on this though.

**Comment by kjozwiak** [comment]
Above requires `1.37.114` or higher for `1.37.x` verification.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.37.114 Chromium: 100.0.4896.88 (Official Build) (x86_64)
-- | --
Revision | 4450653bfa91182e85723d8f1dee64dd6ce40ed4-refs/branch-heads/4896@{#1086}
OS | macOS Version 12.3.1 (Build 21E258)
```

**Comment by Uni-verse** [comment]
Verification in Progress for Android

**Comment by Uni-verse** [comment]
Verification in Progress for Android Tab..
