### ISSUE TITLE
download / save file stopped working

### ISSUE THREAD

**Issue by hoteit** [brave/brave-browser#22191]
## Description 
when I try to download a Pdf or save a file, the browser blinks for a second and nothing happens. 

## Steps to Reproduce

   1.  search for an image in google. say https://duckduckgo.com/?q=google+images&t=brave&iax=images&ia=images
   2.  select an image, right click 
   3. try to download

## Actual result:

download does not work

## Reproduces how often: 

it is happening across all images

## Brave version (brave://version info)

v 1.37.111
## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

running on Arch Linux, Linux Kernel 5.15.33-1-lts, gnome 42.1

**Comment by rebron** [comment]
We verified on macOS and Ubuntu and looks like download and saving is working. Looks like this is Arch Linux specific.

**Comment by hoteit** [comment]
I don't know what happened but I cannot reproduce it anymore. Sorry for the inconvenience.
