### ISSUE TITLE
Add background for top site

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#22196]
This issue is to add background similar to brave stats to improve readability of the text in Top site. 

For more details : https://bravesoftware.slack.com/archives/C0816QH3R/p1649557699341779?thread_ts=1649472632.648009&cid=C0816QH3R

**Comment by bsclifton** [comment]
Example how it would look:
![image](https://user-images.githubusercontent.com/4733304/162642648-f01bf458-bff3-48f7-8dba-6130729c9a3f.png)

**Comment by kjozwiak** [comment]
The above will require `1.38.106` or higher for `1.38.x` verification.

**Comment by Uni-verse** [comment]
Verified using `1.38.106, Chromium 101.0.4951.41`

Devices: 
Samsung GS 21 | Android 12
Samsung Tab S7  | Android 12

- Confirmed background for top sites
- Design matches brave stats background. 

mobile | tablet
-|-
<img width="420" alt="Screen Shot 2022-04-24 at 11 25 01 PM" src="https://user-images.githubusercontent.com/17885425/165034670-ae4645aa-f4a7-4af0-8bed-cebffa134af7.png"> | <img width="578" alt="Screen Shot 2022-04-24 at 11 39 25 PM" src="https://user-images.githubusercontent.com/17885425/165034677-09563255-8f74-4f80-be5e-0828779c0b15.png">
