### ISSUE TITLE
Spell Check not working on many sites and fields

### ISSUE THREAD

**Issue by rahulraj80** [brave/brave-browser#22195]
## Description 

Spell check works on some text fields and does not work on others. It used to work on Discord but has stopped working recently.

## Steps to Reproduce

   1. Spell Chekc works in the text box being used to raise the bug report, and also in the fields like Subject and Filter but it does not work in the search field on top left of Github, and does not work (any more) in the chat fields in Discord 

   2. I have tried changing between English (US) and English (UK) as well.
   3. Cleared cache on websites and disabled all extensions. Did not help.

## Actual result:

Attaching screenshots to show where a typo like "Chekc" had been caught and not caught.

Image1 - Issues and Bugs - Filter : Spell Check is working
![image](https://user-images.githubusercontent.com/11489601/162621049-2072e22e-195c-4db7-817d-f0434bdee769.png)

Image2 - Bug filing edit box : Spell Check is working:
![image](https://user-images.githubusercontent.com/11489601/162621060-b40fb486-5747-4ebd-b8ab-8a8105bc4b07.png)

Image3 - Search box on top left of Github : Spell Check NOT working
![image](https://user-images.githubusercontent.com/11489601/162621064-7e26062e-809a-4fdb-bec4-46ee6b166a0e.png)

Image4 - Message box of Discord (web) : Spell Check NOT working
![image](https://user-images.githubusercontent.com/11489601/162621156-7b198e00-a9be-4c07-b74f-db0ddd6511e1.png)

## Expected result:

Spelling errors should be highlighted.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

1.37.111 Chromium: 100.0.4896.79 (Official Build) (64-bit) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? YES
- Can you reproduce this issue with the beta channel?  Don't have access
- Can you reproduce this issue with the nightly channel? Don't have access

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Don't have Chrome

**Comment by rebron** [comment]
Looks like this maybe specific to discord as there are other reports of spell check no longer working there. Some places with github may set spell check to be set as false so it won't show up.

**Comment by rahulraj80** [comment]
@rebron :

Thanks for the hint - that made me look at it again.

I did not have Chrome to check, but I had MS-Edge and Opera. 

The surprising thing is that Discord chat textbox shows up with spellcheck="true" on both Opera and MS-Edge, but on Brave, that field shows up as spellcheck="false". I tested in In-Private mode with all extensions disabled as well. Any idea why that might be - is Brave being specifically crippled by Discord? Spellcheck was a feature according to [them](https://support.discord.com/hc/en-us/articles/360000877191-Spellcheck-in-Discord).

Brave (autocorrect="false" spellcheck="false") :
![image](https://user-images.githubusercontent.com/11489601/162917196-aefe0e6e-6120-4cb4-ba68-aa4591072e7f.png)

`<div role="textbox" spellcheck="false" aria-haspopup="listbox" aria-invalid="false" aria-autocomplete="list" class="markup-eYLPri editor-H2NA06 slateTextArea-27tjG0 fontSize16Padding-XoMpjI" autocorrect="false" data-can-focus="true" aria-label="Message #😺chatter-box" aria-multiline="true" autocapitalize="false" data-slate-editor="true" data-slate-node="value" contenteditable="true" zindex="-1" style="position: relative; outline: none; white-space: pre-wrap; overflow-wrap: break-word;"><div data-slate-node="element"><span data-slate-node="text"><span data-slate-leaf="true" class="emptyText-1o0WH_"><span data-slate-zero-width="n" data-slate-length="0">﻿<br></span></span></span></div></div>`

MS-Edge (autocorrect="off" spellcheck="true") :
![image](https://user-images.githubusercontent.com/11489601/162915962-a3aabf41-9fff-437c-8451-482c9549161d.png)

`<div role="textbox" spellcheck="false" aria-haspopup="listbox" aria-invalid="false" aria-autocomplete="list" class="markup-eYLPri editor-H2NA06 slateTextArea-27tjG0 fontSize16Padding-XoMpjI" autocorrect="false" data-can-focus="true" aria-label="Message #😺chatter-box" aria-multiline="true" autocapitalize="false" data-slate-editor="true" data-slate-node="value" contenteditable="true" zindex="-1" style="position: relative; outline: none; white-space: pre-wrap; overflow-wrap: break-word;"><div data-slate-node="element"><span data-slate-node="text"><span data-slate-leaf="true" class="emptyText-1o0WH_"><span data-slate-zero-width="n" data-slate-length="0">﻿<br></span></span></span></div></div>`

Opera (autocorrect="off" spellcheck="false") :
![image](https://user-images.githubusercontent.com/11489601/162917338-fd231492-0569-4263-9e2c-2b2419d32638.png)

`<div role="textbox" spellcheck="true" aria-haspopup="listbox" aria-invalid="false" aria-autocomplete="list" class="markup-eYLPri editor-H2NA06 slateTextArea-27tjG0 fontSize16Padding-XoMpjI" autocorrect="off" data-can-focus="true" aria-label="Message #😺chatter-box" aria-multiline="true" data-slate-editor="true" data-slate-node="value" contenteditable="true" zindex="-1" style="position: relative; outline: none; white-space: pre-wrap; overflow-wrap: break-word;"><div data-slate-node="element"><span data-slate-node="text"><span data-slate-leaf="true" class="emptyText-1o0WH_"><span data-slate-zero-width="n" data-slate-length="0">﻿<br></span></span></span></div></div>`

These are the fields which are not the same in all three browsers - I copied the elements from the three browsers and aligned them by fields:

`
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/rahul/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/rahul/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Brave | MS-Edge | Opera
-- | -- | --
aria-invalid="false" |   | aria-invalid="false"
autocapitalize="false" |   |  
autocorrect="false" | autocorrect="off" | autocorrect="off"
  | data-gramm="false" |  
  | data-key="66" |  
data-slate-node="value" |   | data-slate-node="value"
editor-H2NA06 |   | editor-H2NA06
spellcheck="false" | spellcheck="true" | spellcheck="true"
zindex="-1" |   | zindex="-1"
position:relative |   | position:relative
  | -webkit-user-modify:read-write-plaintext-only |  
data-slate-node="element"><span |   | data-slate-node="element"><span
data-slate-node="text"><span |   | data-slate-node="text"><span
data-slate-leaf="true" |   | data-slate-leaf="true"
class="emptyText-1o0WH_"><span |   | class="emptyText-1o0WH_"><span
  | data-slate-object="block" |  
  | data-key="67" |  
  | style="position: |  
  | relative;"><span |  
  | data-slate-object="text" |  
  | data-key="68"><span |  
  | data-slate-leaf="true" |  
  | data-offset-key="68:0"><span |  
data-slate-zero-width="n" | data-slate-zero-width="z" | data-slate-zero-width="n"



</body>

</html>

`

Is there any way for us to control it? Or is it something Discord alone can fix?

**Comment by rebron** [comment]
cc: @ryanbr Can you take a look? Is Discord detecting and blocking Brave on purpose? Something we can fix via filter lists?

**Comment by ryanbr** [comment]
Need more info on replicating how this is done @rahulraj80 , below is screenshots from Chrome and Edge, with misspellings in the text fields. Neither of them corrected, or even highlighted the incorrect spellings.

![discordd](https://user-images.githubusercontent.com/1659004/163098222-48847b75-7a75-45eb-9014-dd08b91414db.png)

**Comment by rahulraj80** [comment]
@ryanbr :

This seems very strange!! Even for me MS-Edge today shows `spellcheck="false"` - it was definitely different earlier (refer old screenshots).

On Opera, this is still showing as `spellcheck="true"`. Any chance you can check/confirm that? Or is there some magic happening on my machine that I don't know about!? 🤦 :-)

**Comment by ryanbr** [comment]
Feels like a discord issue so far, does it occur only on discord? How about in Github comments? Does Brave spellcheck work here? @rahulraj80

**Comment by rahulraj80** [comment]
@ryanbr :

Yes : On Discord, the relevant fields have `spellcheck="true"`. 

I had mentioned in the first post, that it does not work in the search field on top left, and it was pointed out to me that, that particular field has `spellcheck="false"`.

The unusual behaviour I see is that on Opera, Discord shows the same fields with spellcheck enabled, unlike the other browsers.

I have not come across another site which chooses which browsers can have spellcheck enabled.

Is there some way for the users to use the internal scripting engine to define their own 'userscripts' in Brave without installing an extension. I am testing ViolentMonkey meanwhile but would be awesome if I can do it without an extension.

**Comment by ryanbr** [comment]
Not currently, userJS like violentmonkey is the best bet here. We wouldn't change the defaults of a website regarding the spellcheck.

**Comment by rahulraj80** [comment]
Makes sense.

I have uploaded the script on [OpenUserJS : https://openuserjs.org/scripts/rahuraj80/Discord_SpellCheck] (https://openuserjs.org/scripts/rahuraj80/Discord_SpellCheck) for anyone who runs into the same issue. You can search for Discord Spell Check, or navigate using the URL

Also attached as an attachment with this post. 

**IMP: Remove the .txt extension before importing it in TamperMonkey - the extension should be user.js for TamperMonkey to accept it.**

This can be installed using the TamperMonkey extension for Chromium based browsers.

With a slight modification in the wildcard parameters in the @match section, and the class name of the field to be modified, it can be used for any website, where you need to enable Spellcheck. 

Closing this report given this seems to be a Discord issue.
