### ISSUE TITLE
Wireguard implementation for VPN 

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#22199]
This issue is updating existing VPN implementation with Wireguard.  
It also includes tunnel .aar for wireguard : https://search.maven.org/artifact/com.wireguard.android/tunnel

**Comment by Uni-verse** [comment]
Verification in Progress using 

Brave	1.40.62 Chromium: 102.0.5005.50 (Official Build) canary (64-bit) 
Revision	f6e2cf8f59ec714bdcff8499991d55898875f287-refs/branch-heads/5005@{#648}
OS	Android 12; Build/SP1A.210812.016

Test Plan: 

- VPN Menu/Settings

- UI/Design

- Purchase Flow

- Notifications/Email Confirmations

- Badging/Icons

- Sharing/Restore

- Services
