### ISSUE TITLE
Fix top site tile size

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#22198]
## Description
Before the widget was introduced on Android, the top sites were roughly the same size
![image](https://user-images.githubusercontent.com/4733304/162643033-91709636-c497-426c-8571-a6f0dfe4ae86.png)

Sometime after the widget was added the logic for rendering the top site tiles must have changed. This became easy to see when we removed the widget. When an favicon isn't found, it will generate one with a letter. This seems to be significantly smaller than sites which have an icon
![image](https://user-images.githubusercontent.com/4733304/162643067-ec870cfb-a4d3-41ef-acb3-a27b8fe24233.png)

**Comment by anthonypkeane** [comment]
Can we bundle the default icons in the app?

**Comment by kjozwiak** [comment]
The above will require `1.38.106` or higher for `1.38.x` verification.

**Comment by Uni-verse** [comment]
Verified using `1.38.106, Chromium 101.0.4951.41`

Devices:
`Samsung GS 21` | `Android 12`
`Samsung Tab S7` | `Android 12`

- Verified if the icon is not found, the letter generated with match the size of the other favicons.
- Confirmed using top site links will load the site. 
- Confirmed user is able to remove/undo remove top site. 
- Confirmed 3 icons are visible on mobile portrait, 4 in landscape. (GS 21)

tablet | mobile
-|-
<img width="578" alt="Screen Shot 2022-04-24 at 11 39 25 PM" src="https://user-images.githubusercontent.com/17885425/165035528-8bae20b4-96a5-4d07-b889-47f79c74ad4b.png"> | <img width="420" alt="Screen Shot 2022-04-24 at 11 25 01 PM" src="https://user-images.githubusercontent.com/17885425/165035525-e2fb872b-c6bd-45db-b36c-95ab83d4dfab.png">
