### ISSUE TITLE
Shields panel has extra padding to right

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#222]
## Description 
Shields panel doesn't fit in 

## Steps to Reproduce

   1. Build from source( 46eaccaf)
   2. Visit any site and open shields
   3. Has extra padding to right causing 

 ## Actual result:
![image](https://user-images.githubusercontent.com/17010094/40492954-b145ecd4-5f3f-11e8-844f-ddbb09e66716.png)

## Expected result:
Should not contain extra padding 
## Reproduces how often: 

Easy

### Website problems only:  
- Does the issue gets fixed with Brave Shields disabled? 
- Does the issue reproduces on Chrome?

**Comment by cezaraugusto** [comment]
@srirambv can you confirm this is still a bug?

if so could you please try opening dev tools from inside the extension popup and looking for the ` <body>` tag and remove the property `width` and adding it to the data-test-id `braveShieldsPanel` instead to see if this solves the issue? Something similar to the below screenshot. This doesn't seem to reproduce on macOS.

<img width="394" alt="screen shot 2018-07-26 at 11 52 16 am" src="https://user-images.githubusercontent.com/4672033/43270059-8de7737c-90ca-11e8-9436-740256f94caa.png">

** note that <body> has `width: auto` and `braveShieldsPanel` has the current 280px

If it does fix it please let me know I can help you cook a PR for it. Thanks!

**Comment by srirambv** [comment]
@cezaraugusto this is what i get with the above settings
![image](https://user-images.githubusercontent.com/17010094/43591366-2fcede48-9641-11e8-840a-5350d231b15c.png)

**Comment by emerick** [comment]
@cezaraugusto I see it as well on Windows. I think the scrollbar is to blame somehow, as when I collapse the "Advanced Controls" section the scrollbar (and the extra space on the right) both go away.

**Comment by lukemulks** [comment]
![shield-padding-and-scroll](https://user-images.githubusercontent.com/8979240/44301511-150d7900-a2cd-11e8-943a-79d87c09dca3.PNG)

FYI - I'm seeing the scrolling and the padding on win10 x64. 

I believe I'm on the latest build. If I'm not on the latest build, disregard. I'm not re-opening this issue, just in case this is resolved and I am just not updated. 

Here's what I'm getting for about:brave 
```
Brave is up to date
Version 0.54.0 Chromium: 69.0.3497.32 (Official Build) dev (64-bit)
```

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7

Extra padding in not shown even when clicked on blocked element #771
![222_pass](https://user-images.githubusercontent.com/34715963/45879605-6e256c80-bda5-11e8-82d0-41c936488d0a.gif)
