### ISSUE TITLE
Edit Visible Assets Modal Performance Issue

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#22204]
## Description 
Upon opening the `Edit Visible Assets` modal, it is very slow to render and checking an `Asset` has a slow response time.
We should investigate ways to only render a set amount of tokens at a time.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.39.109 Chromium: 102.0.5005.50 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>f6e2cf8f59ec714bdcff8499991d55898875f287-refs/branch-heads/5005@{#648}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22621.1)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/12965>brave/brave-core#12965</a></li>
         <li>Verified scrolling down automatically loads the next 40 tokens from the list</li>
         <li>Verified scrolling tokens list is faster and doesn't hang while loading the remaining tokens</li>
        </ul>
      </td>
   </tr>
</table>
