### ISSUE TITLE
Disable chromium's web resource service

### ISSUE THREAD

**Issue by rht** [brave/brave-browser#2220]
## Description 

Disable chromium's web resource service. I am not particularly sure what it does, but it is deemed obnoxious according to [inox-patchset](https://github.com/gcarq/inox-patchset/blob/f7fa31418157a7fe7f793376889ad3673183e028/0007-disable-web-resource-service.patch).

**Comment by rht** [comment]
What it does: https://groups.google.com/a/chromium.org/d/msg/chromium-reviews/R3Iv2UgTcbg/jYoAamNvSOgJ.

**Comment by pilgrim-brave** [comment]
Do not disable this. It is used by PluginsResourceService to download information about security updates for plugins like Flash, and the network requests are already proxied through Brave servers by this patch: https://github.com/brave/brave-core/blob/master/patches/chrome-browser-plugins-plugins_resource_service.cc.patch per this commit: https://github.com/brave/brave-core/commit/0b507f8885254fcdc6f3f4a22f45f211f1031890#diff-a016d9d300e356fe44fa8b0846e90529
