### ISSUE TITLE
Fix custom Brave Ad notifications should not be transparent when using the `should_attached_ad_notification_to_browser_window` feature flag

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#22205]
Follow up to https://github.com/brave/brave-browser/issues/19464. 
Custom ad notification is transparent when attached to Brave Window

## Steps to Reproduce

1. Clean install
1. Run Brave with: `--enable-logging=stderr --vmodule="*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6,"*/bat_ads/*"=6 --brave-ads-staging --rewards=staging=true --variations-server-url=https://v --enable-features="CustomAdNotifications:should_attached_ad_notification_to_browser_window/true"`
1. Enable rewards and ads
1. Trigger a notification ad

## Actual result:

Notification ad is transparent

The ad is at top right corner:
![image](https://user-images.githubusercontent.com/34715963/162776136-0bc2101b-a657-4c4a-add6-62b9d508e53d.png)

## Expected result:
Notification ad is not transparent

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.38.83 Chromium: 100.0.4896.79 (Official Build) beta (64-bit)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | Ubuntu 18.04 LTS

cc @brave/qa-team @jsecretan @tmancey @aseren

**Comment by aseren** [comment]
The issue will be fixed here: https://github.com/brave/brave-browser/issues/29744
