### ISSUE TITLE
Fix custom Brave notification ads should be attached to the browser window

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#22203]
Follow up to https://github.com/brave/brave-browser/issues/19464. 
On Windows the custom ad notification is not anchored to Brave Window so the z-ordering does not work, the ad stays on top.

## Steps to Reproduce

1. Clean install
1. Run Brave with: `--enable-logging=stderr --vmodule="*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6,"*/bat_ads/*"=6 --brave-ads-staging --rewards=staging=true --variations-server-url=https://v --enable-features="CustomAdNotifications:should_attached_ad_notification_to_browser_window/true"`
1. Enable rewards and ads
1. Trigger a notification ad

## Actual result:

Notification ad is not anchored to the browser window, the ad stays on top
![19464_Windows_covered](https://user-images.githubusercontent.com/34715963/163005923-72ed5042-5c80-4ee6-b063-691d1925fdd9.gif)

## Expected result:
Notification ad is anchored to the browser window

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.38.83 Chromium: 100.0.4896.79 (Official Build) beta (64-bit)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | Windows 10 Version 21H2 (Build 19044.1586)

cc @brave/qa-team @jsecretan @tmancey @aseren

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave 1.52.109 Chromium: 114.0.5735.26 (Official Build) beta (x86_64)
Revision 7075cbb66f0542ac3e01ddfde6b813e7d61118a5-refs/branch-heads/5735@{#454}
OS macOS Version 11.7.7 (Build 20G1345)
```

Issue still reproducible. Per our process, @btlechowski  logged https://github.com/brave/brave-browser/issues/30508

**Comment by aseren** [comment]
The parameter name was changed to `should_attach_ad_notification_to_browser_window` for Beta 1.52. For Nightly version it was renamed to `use_same_z_order_as_browser_window` and set to true by default: https://github.com/brave/brave-browser/issues/30508#issuecomment-1559716691

**Comment by tmancey** [comment]
I will raise an issue to add the latest feature/param/values to a README.md you can access in the repo.

**Comment by btlechowski** [comment]
Thanks @aseren @tmancey . We will retest with the new parameter.
