### ISSUE TITLE
Global defaults  inconsistent appearance when Shields are down

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#22217]
## Description 
When Shields are down, Global default hyperlink display black initially and after hovering over second time, it turns blue.

## Steps to Reproduce

1. Install 1.38.83
2. Launch `Brave`
3. Visit `Washingtonpost.com`
4. Click `Shields` icon 
5. Disable Shields

## Actual result:

Global defaults hyperlink appears black.  Appeared blue after hovered over twice.

<image width="950" alt="globaldefaultslink" src="https://user-images.githubusercontent.com/98358127/162792985-04c33178-fe3f-4ae2-b4f1-477917f6bcdf.png">

## Expected result:
Global defaults hyperlink should display blue.

## Reproduces how often: 

Easy

## Version/Channel Information:

Brave | 1.38.83 Chromium: 100.0.4896.79 (Official Build) beta (64-bit)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | Windows 11 Version 21H2 (Build 22000.593)

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
cc: @aguscruiz Can you clarify the hover state in @MadhaviSeelam's example for the Global defaults link. Closed Shields panel (black hyperlink, blue on hover) is different from Shields on/Advanced controls expanded for Filter lists and Global defaults link (blue hyperlink, no change on hover).

**Comment by aguscruiz** [comment]
Global default button should be:

Light mode: blurpee 400 - hover: blurpee 500
Dark mode: blurpee 300 - hover: blurpee 400

**Comment by kjozwiak** [comment]
Above requires `1.38.102` or higher for `1.38.x` verification.

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
Brave | 1.38.103 Chromium: 100.0.4896.127 (Official Build) beta (64-bit)
-- | --
Revision | ff0d0695743e65305d7194f9bd309e5e1c824aa0-refs/branch-heads/4896_88@{#4}
OS | Windows 10 Version 21H2 (Build 19044.1645)

```
- Verified the STR from the description and ensured `Global defaults` is shown in blue color when shields are down
![image](https://user-images.githubusercontent.com/38657976/164197689-b5490dff-1770-4f1b-b8fe-d294f8dec550.png)

**Comment by MadhaviSeelam** [comment]
Verification `Passed` on 

Brave | 1.38.104 Chromium: 101.0.4951.41 (Official Build) (64-bit)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | Windows 11 Version 21H2 (Build 22000.613)

Verified the bug fix on Shields UP and Shields Down panels.  QA complete. 

<img width='550' alt="shields panel" src="https://user-images.githubusercontent.com/98358127/165130187-dc234ecc-0284-47de-921e-e303b2ad5264.png">
