### ISSUE TITLE
x86 Windows machines are not updating

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#2221]
## Description 

Updates are currently failing on x86 machines. I initially ran into the issue when we were releasing `0.56.14` but no one else had x86 machines that could double check if I was the only one receiving this issue on my VM's. @GeetaSarvadnya mentioned that she also ran into the issue once on her x64 machine so we thought it was an intermittent issue. However, getting reports from reddit that x86 users are not getting new updates:

https://www.reddit.com/r/brave_browser/comments/9ywwpb/brave_version_05614_now_available_on_release/ea8p9jv

When attempting to update my Win x86 machine, I'm getting the following error under `brave://settings/help`:

```
An error occurred while checking for updates: The installer encountered error 255. (error code 7: 0x80040902: 255 -- system level).
```

* Win 10 x86 logs: [OmahaUpdate.log](https://github.com/brave/brave-browser/files/2609706/OmahaUpdate.log)
* Win 7 x86 logs: [OmahaUpdate.log](https://github.com/brave/brave-browser/files/2609719/OmahaUpdate.log)

## Steps to Reproduce

   1. launch a Win x86 VM and install https://github.com/brave/brave-browser/releases/download/v0.56.14/BraveBrowserStandaloneSetup32.exe
   2. once installed, attempt to update Brave via `brave://settings/help`

## Actual result:

When attempting to update an x86 machine, you'll get the following error and Brave won't upgrade:

```
An error occurred while checking for updates: The installer encountered error 255. (error code 7: 0x80040902: 255 -- system level).
```

## Expected result:

x86 machines should be updating to the latest version without any issues.

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

Brave | 0.56.15 Chromium: 70.0.3538.110 (Official Build) (32-bit)
--- | ---
Revision | ca97ba107095b2a88cf04f9135463301e685cbb0-refs/branch-heads/3538@{#1094}
OS | Windows

Brave | 0.56.14 Chromium: 70.0.3538.102 (Official Build) (32-bit) 
--- | ---
Revision | 4bbeebac88fdc09c97265e47c205868bbd190497-refs/branch-heads/3538@{#1077}
OS | Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

I'm not 100% sure if the other channels are available as there's no standalone installers for the previous versions

### Additional Information

* Win 10 x86 - Reproduced
* Win 8.1 x86 - Reproduced
* Win 7 x86 - Reproduced

**Comment by simonhong** [comment]
I read the above reddit post and I think it is different issue with this because user saw `up to date` not `0x80040902`(this error means silent installer failed)

**Comment by mihaiplesa** [comment]
Reproduced on Win 7 x64 using 32-bit standalone installer.

After the error message appears and an update is re-attempted it tries to get updates from the `x86-rel-full` channel which doesn't exist.

The correct channel name is `x86-rel` which it has tried initially before the error so there seems to be some logic in the installer that allows that.

Full output at [BraveUpdate.log](https://github.com/brave/brave-browser/files/2611016/BraveUpdate.log)

```
[11/23/18 14:22:49.182][BraveUpdate:goopdate][3804:4000][Send][url=https://updates.bravesoftware.com/service/update2][request=<?xml version="1.0" encoding="UTF-8"?><request protocol="3.0" version="1.3.99.0" shell_version="1.3.99.0" ismachine="1" sessionid="{0346E18A-D973-405C-811B-9EBCA073033D}" installsource="update3web-ondemand" testsource="auto" requestid="{B7CA0179-D530-4C00-B07F-212B26DAE1F2}" dedup="cr"><hw physmemory="4" sse="1" sse2="1" sse3="1" ssse3="1" sse41="1" sse42="1" avx="1"/><os platform="win" version="6.1.7601.0" sp="Service Pack 1" arch="x64"/><app appid="{AFE6A462-C574-4B8A-AF43-4CC60DF4563B}" version="70.0.56.14" nextversion="" ap="x86-rel-full" lang="en" brand="GGLS" client="" installage="0" installdate="4340"><updatecheck/><ping active="0" rd="4344" ping_freshness="{913B83FB-9121-4453-9DFF-C8805F197FE6}"/></app></request>][filename=]
[11/23/18 14:22:49.552][BraveUpdate:goopdate][3804:4000][Send response received][result 0x0][status code 200][<?xml version='1.0' encoding='UTF-8'?>
<response protocol="3.0" server="prod">
  <daystart elapsed_seconds="51768" elapsed_days="4344"/>
  <app status="ok" appid="{AFE6A462-C574-4B8A-AF43-4CC60DF4563B}">
    <updatecheck status="noupdate"/>
    <ping status="ok"/>
  </app>
</response>
```

**Comment by mihaiplesa** [comment]
The unexpected `appid` above also appears in logs attached in https://github.com/brave/brave-browser/issues/2129

**Comment by mihaiplesa** [comment]
@mbacchi any ideas?

**Comment by kjozwiak** [comment]
> I read the above reddit post and I think it is different issue with this because user saw `up to date` not `0x80040902`(this error means silent installer failed)

Agreed, I think it was a different issue as the user managed to finally update their Brave. However, once you receive the error I mentioned above, every other attempt will display `Brave is up to date` even though there's a new version available.

**Comment by simonhong** [comment]
@kjozwiak I see. I also saw error one time and then `up to date` is visible.

**Comment by simonhong** [comment]
Hmm, root cause of this issue is `-full` is appended to our ap. When I manually remove it from `regedit`, everything works fine. Finding where and why this `-full` is appended.

**Comment by mihaiplesa** [comment]
This is where I see it used https://github.com/brave/brave-core/search?q=-full&type=Code

**Comment by simonhong** [comment]
Hmm, I built standalone installer on my local and did update test.
Unfortunately, this problem wasn't reproduced with that. I'll dig more about this.

**Comment by kjozwiak** [comment]
> Hmm, I built standalone installer on my local and did update test.
> Unfortunately, this problem wasn't reproduced with that. I'll dig more about this.

@simonhong let me know if you need any help debugging 👍I can pretty much reproduce this 100% of the time using the STR in https://github.com/brave/brave-browser/issues/2221#issue-383702615 using either Win 10 x86 or Win 7 x86.

**Comment by simonhong** [comment]
Yep, I also can reproduce this with released standalone installer and update trying... (So it's weird why manually built standalone and update trying works fine).
Anyway, I'll take a look more.

I think the main problem is the update file on first trying.
Because of that fail, I assume `-full` isn't removed from `ap`.
I think not reverted `ap` caused `up to date` problem.

**Comment by simonhong** [comment]
@mbacchi @mihaiplesa Finally I reproduced this on my local with manually built installer.
When I omit update action in omaha server, I got same error.
Can you check install/update action was set properly for each x86 versions in official server?
I can't access our official omaha server.
Every versions should have install/update event in Actions sections.

**Comment by mihaiplesa** [comment]
Have just checked and the uploaded versions look fine (unless it was happening on an older version we removed).

Will make sure we do it right from now.

Just curious, what happens if we mismatch and put `--chrome-dev-` instead of `--chrome-beta` for a `beta` version?

**Comment by simonhong** [comment]
If we use wrong argument(ex using `--chrome-dev` to beta), it will cause the problem.
installer determines which channel it should install by using this arguments.
I think using wrong arguments could cause install error.

**Comment by mihaiplesa** [comment]
Thanks for clarifying, we'll see if this happens again.

**Comment by kjozwiak** [comment]
@simonhong I went through the following when we released `0.57.18` and didn't run into `An error occurred while checking for updates: The installer encountered error 255. (error code 7: 0x80040902: 255 -- system level).`:

* macOS - installed `0.56.15 Chromium: 70.0.3538.110` and updated to `0.57.18 Chromium: 71.0.3578.80` using chrome://settings/help - **PASSED** [Confirmed by @laurenwags]
* Win 10 x64 - installed `0.56.15 Chromium: 70.0.3538.110` and updated to `0.57.18 Chromium: 71.0.3578.80` using chrome://settings/help -  **PASSED** [Also confirmed by @Sri & @rebron]
* Win 10 x86 - installed `0.56.15 Chromium: 70.0.3538.110` and updated to `0.57.18 Chromium: 71.0.3578.80` using chrome://settings/help -  **PASSED**
* Win 8.1 x64 - installed `0.56.15 Chromium: 70.0.3538.110` and updated to `0.57.18 Chromium: 71.0.3578.80` using chrome://settings/help -  **PASSED**
* Win 8.1 x86 - installed `0.56.15 Chromium: 70.0.3538.110` and updated to `0.57.18 Chromium: 71.0.3578.80` using chrome://settings/help -  **PASSED**
* Win 7 x64 - installed `0.56.15 Chromium: 70.0.3538.110` and updated to `0.57.18 Chromium: 71.0.3578.80` using chrome://settings/help -  **PASSED**
* Win 7 x86 - installed `0.56.15 Chromium: 70.0.3538.110` and updated to `0.57.18 Chromium: 71.0.3578.80` using chrome://settings/help -  **PASSED**

**Comment by simonhong** [comment]
@kjozwiak Great! 👍

**Comment by mihaiplesa** [comment]
Re-opening to create secondary channels suffixed with `-full` and server updates to them so they come back to the regular channel. https://github.com/brave/devops/issues/1957 can provide some info.

**Comment by bsclifton** [comment]
Thanks @mihaiplesa and @mbacchi for looking into solutions. After discussion, I think this is a fairly isolated problem. @mbacchi and I are working on a help article that we can review with @Brave-Matt for what to do when update isn't working that would resolve this scenario

**Comment by mbacchi** [comment]
Documentation added here: https://support.brave.com/hc/en-us/articles/360042816611-Why-isn-t-Brave-updating-automatically-on-Windows-
