### ISSUE TITLE
Add host related information to vpn notification

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#22212]
This issue is the follow up issue to : https://github.com/brave/brave-browser/issues/22199 to add host related information to vpn notification.

**Comment by kjozwiak** [comment]
@deeppandya adding the missing `1.41.x` milestone as this was merged into `1.41.x` so the appropriate milestone needs to be added. If this wasn't being uplifted, QA would never see the issue. Please see https://github.com/brave/brave-browser/wiki/Triage-Guidelines#uplifting.

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.41.52 x64 Nightly build
- Verified steps from [ brave/brave-core#13640](https://github.com/brave/brave-core/pull/13640)
- Verified host info is added to VPN notification
- Verified VPN notification has information for transfer bytes and received bytes
- Verified VPN notification has `Disconnect` button
- Verified VPN connection can be terminated via the disconnect button in the VPN notification

<img width=300 src=https://user-images.githubusercontent.com/17010094/177376406-3f7ea7e0-d630-4349-a5d0-e979ee0fa307.png>


Note: Verification done on nightly after confirming with @deeppandya as there is no purchase on Beta channel

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy Tab S7 ` using 

```
Brave	1.41.94 Chromium: 103.0.5060.114 (Official Build) (64-bit) 
Revision	a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS	Android 12; Build/SP1A.210812.016
```

Used Test Plan in https://github.com/brave/brave-core/pull/13640

- Verified Host info is added to VPN notification
- Verified Host is updated when changing location in VPN settings
- Verified VPN notification can be expanded/collapsed. Disconnect button is shown when expanded.
- Verified VPN notification has information for transfer bytes and received bytes
- Verified transfer byte statistics are not updated when device network connectivity is disabled
- Verified VPN notification has Disconnect button
- Verified VPN connection can be terminated via the disconnect button in the VPN notification
- Verified VPN notification cannot be dismissed by swiping or clear notifications

Example | Example | Example
-|-|-
![screenshot-1657154554158](https://user-images.githubusercontent.com/17885425/177674489-fd9a28f4-b2fc-4d27-ba58-7776cdff517e.png) | ![screenshot-1657154563663](https://user-images.githubusercontent.com/17885425/177674491-afbb1bdd-7f72-4151-9f12-d6cfe20d7768.png) | ![screenshot-1657154626978](https://user-images.githubusercontent.com/17885425/177674493-347bcb11-8136-46a4-bc7f-e10ddd0bdd7c.png)
