### ISSUE TITLE
Local site favicon is replaced by Brave favicon when clicked Learn more link 

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#22214]
## Description 

Website favicon is replaced by Brave favicon when clicked Learn more link in the shields panel

## Steps to Reproduce

1. Install 1.38.83
2. Launch Brave
3. Visit `Washingtonpost.com`
4. Click `Shields` icon
5. Click Learn more link below `Trackers, ads and more blocked` in the shields panel
6. Click Shields icon in Brave.com/privacy-features page 
7. Return to previous tab `Wasingtonpost.com`
8. Click `Shields`

## Actual result:

 Washingtonpost.com favicon is replaced by `Brave` favicon in the shields panel

<image width="950" alt="Learnmore" src="https://user-images.githubusercontent.com/98358127/162787459-ae71947a-7382-4c13-b119-d468aa1a810a.png">

## Expected result:
Washingtonpost.com favicon should display as expected in the shields panel

## Reproduces how often: 
 Easy

## Brave version (brave://version info)

Brave | 1.38.83 Chromium: 100.0.4896.79 (Official Build) beta (64-bit)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | Windows 11 Version 21H2 (Build 22000.593)
## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  No
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
Above requires `1.38.102` or higher for `1.38.x` verification.

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```

Brave | 1.38.103 Chromium: 100.0.4896.127 (Official Build) beta (64-bit)
-- | --
Revision | ff0d0695743e65305d7194f9bd309e5e1c824aa0-refs/branch-heads/4896_88@{#4}
OS | Windows 10 Version 21H2 (Build 19044.1645)

```
- Verified the STR from the description and ensured the site favicon is shown correctly on both the sites.

**Comment by MadhaviSeelam** [comment]
Verification `Passed` on 

Brave | 1.38.104 Chromium: 101.0.4951.41 (Official Build) (64-bit)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | Windows 11 Version 21H2 (Build 22000.613)

Verified the bug fix. QA complete.
