### ISSUE TITLE
Add an option to disable vpn in notification

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#22211]
This issue is the follow up issue to : https://github.com/brave/brave-browser/issues/22199 to add option to disable vpn in notification.

**Comment by kjozwiak** [comment]
@deeppandya adding the missing `1.41.x` milestone as this was merged into `1.41.x` so the appropriate milestone needs to be added. If this wasn't being uplifted, QA would never see the issue. Please see https://github.com/brave/brave-browser/wiki/Triage-Guidelines#uplifting.

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/22212#issuecomment-1175298880

**Comment by Uni-verse** [comment]
`Android Tab` verified in https://github.com/brave/brave-browser/issues/22212#issuecomment-1176959182
