### ISSUE TITLE
Add statistics to Brave Vpn notification

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#22210]
This issue is the follow up issue to : https://github.com/brave/brave-browser/issues/22199 to add statistics to the vpn notification.

**Comment by kjozwiak** [comment]
@deeppandya adding the missing `1.41.x` milestone as this was merged into `1.41.x` so the appropriate milestone needs to be added. If this wasn't being uplifted, QA would never see the issue. Please see https://github.com/brave/brave-browser/wiki/Triage-Guidelines#uplifting.

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/22212#issuecomment-1175298880
