### ISSUE TITLE
Fix custom Brave Ad notifications should not disappear after minimizing and restoring the browser

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#22218]
Follow up to https://github.com/brave/brave-browser/issues/19464. 
custom ad notification disappears when attached to Brave Window after minimizing and restoring the browser

## Steps to Reproduce

1. Clean install
1. Run Brave with: `--enable-logging=stderr --vmodule="*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6,"*/bat_ads/*"=6 --brave-ads-staging --rewards=staging=true --variations-server-url=https://v --enable-features="CustomAdNotifications:should_attached_ad_notification_to_browser_window/true"`
1. Enable rewards and ads
1. Trigger a notification ad
1. Minimize the browser
1. Restore the browser

## Actual result:

custom ad notification disappears
There is no logs registered
![19464_Ubuntu_minimized](https://user-images.githubusercontent.com/34715963/162796843-2b71e4c6-2ef3-40fd-9547-67cd6686944a.gif)

## Expected result:
custom ad notification re-appears with the browser window

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.38.83 Chromium: 100.0.4896.79 (Official Build) beta (64-bit)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | Ubuntu 18.04 LTS

cc @brave/qa-team @jsecretan @tmancey @aseren

**Comment by tmancey** [comment]
Closed as resolved by #22203
