### ISSUE TITLE
Hide ad earnings claim toast notification in Rewards panel if a promotion is `OVER` (no longer active) 

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#22215]
## Description

Currently, if a promotion goes into `OVER` (or some other non-active state), the ad earnings claim notification remains in the Rewards panel and does not disappear like it does on the Rewards settings page. When clicked, it will just disappear with no other UX. 

## Solution

We should make it like the brave://rewards settings page (and Rewards NTP widget), which will display the ad earnings claim button in sync with what the promotion status/availability is.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.39.84 Chromium: 101.0.4951.41 (Official Build) beta (x86_64)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | macOS Version 12.3.1 (Build 21E258)
```

**Comment by MadhaviSeelam** [comment]
Brave | 1.39.96 Chromium: 101.0.4951.54 (Official Build) beta (64-bit)
-- | --
Revision | 67da1aeb32cedd27634ca6634fb79cbd85d3f0ab-refs/branch-heads/4951@{#1126}
OS | Windows 11 Version 21H2 (Build 22000.613)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.39.100 Chromium: 101.0.4951.61 (Official Build) beta (64-bit)
-- | --
Revision | 3b3633b32c491b4cba5fd7df3c7c0f628547cbcc-refs/branch-heads/4951@{#1189}
OS | Ubuntu 18.04 LTS


<details>
<summary>Test Case 1 - Staging UGP grant (claim from panel) - PASSED, follow up issue logged</summary>

From https://github.com/brave/brave-core/pull/12971#issue-1200460743: 

- Open browser with a new profile pointed to Rewards staging.
- Open the Rewards panel and enable rewards.
- Dismiss the onboarding tour.
- Do not click the "Claim" button in the UGP grant notification.
- Close the Rewards panel.
- Disconnect from the network.
- Open the rewards panel.
  - Verify that the grant notification is not displayed.
  - Noticed red bubble remains and will not be dismissed. Encountered https://github.com/brave/brave-browser/issues/22622 as a follow up.
- Close the rewards panel.
- Connect to the network.
- Open the rewards panel.
  - Verify that the grant notification is displayed.
- Claim the grant.
  - Verify that captcha claiming is successful.
  - At this point, the red bubble goes away.

![22215_1](https://user-images.githubusercontent.com/34715963/167855068-098b3e07-30a1-4693-a391-0ce1e153540a.gif)


</details>

<details>
<summary>Test Case 3 - Staging UGP grant (claim from brave://rewards) - PASSED w/ follow up issue</summary>

From https://github.com/brave/brave-core/pull/12971#issue-1200460743: 

- Open browser with a new profile pointed to Rewards staging.
- Open the Rewards panel and enable rewards.
- Dismiss the onboarding tour.
- Do not click the "Claim" button in the UGP grant notification.
- Close the Rewards panel.
- Disconnect from the network.
- Open the rewards panel.
  - Verify that the grant notification is not displayed.
  - Noticed red bubble remains and will not be dismissed. Encountered https://github.com/brave/brave-browser/issues/22622 as a follow up.
- Close the rewards panel.
- Connect to the network.
- Open the rewards panel.
  - Verify that the grant notification is displayed, dismiss the grant (click on "x")
- Navigate to brave://rewards
- Claim the grant from brave://rewards
  - Verify that captcha claiming is successful.

![22215_3](https://user-images.githubusercontent.com/34715963/167857113-cf9db9ed-fe34-4b20-a26e-cb4b6abfa0c8.gif)

</details>

<details>
<summary>Test Case 4 - Staging UGP grant (claim from NTP)- PASSED w/ follow up issue</summary>

From https://github.com/brave/brave-core/pull/12971#issue-1200460743: 

- Open browser with a new profile pointed to Rewards staging.
- Open the Rewards panel and enable rewards.
- Dismiss the onboarding tour.
- Do not click the "Claim" button in the UGP grant notification.
- Close the Rewards panel.
- Disconnect from the network.
- Open the rewards panel.
  - Verify that the grant notification is not displayed.
  - Noticed red bubble remains and will not be dismissed. Encountered https://github.com/brave/brave-browser/issues/22622 as a follow up.
- Close the rewards panel.
- Connect to the network.
- Open the rewards panel.
  - Verify that the grant notification is displayed, dismiss the grant (click on "x")
- Open NTP
- Claim the grant from widget on NTP
  - Verify that captcha claiming is successful.

![22215_4](https://user-images.githubusercontent.com/34715963/167859663-0dcb724f-3b88-4ea7-9086-8e48984f3adf.gif)


</details>


<details>
<summary>Test Case 2 - Staging Ad grant - PASSED w/ follow up issue</summary>

From https://github.com/brave/brave-core/pull/12971#issue-1200460743: 

1. Open browser with a new profile pointed to Rewards staging.
2. Open the Rewards panel and enable rewards.
3. Generate an Ad grant for the current rewards payment ID.
4. Wait for the Ad grant to become available to the browser.
5. Open the rewards panel.
  - Verify that the "Claim" notification is displayed.
6. Do not click the "Claim" button.
7. Close the Rewards panel.
8. Have a server-side team member remove the Ad grant.
9. Wait for the grant to disappear from the rewards page.
10. Open the rewards panel.
  - Verify that the grant notification is not displayed.
  - Noticed red bubble remains and will not be dismissed. Encountered https://github.com/brave/brave-browser/issues/22622 as a follow up.


</details>
