### ISSUE TITLE
Fix custom Brave Ad notifications should be attached to the browser window when repositioning ads on the screen

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#22216]
Follow up to https://github.com/brave/brave-browser/issues/19464. 

## Steps to Reproduce

1. Clean install
1. Run Brave with: `--enable-logging=stderr --vmodule="*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6,"*/bat_ads/*"=6 --brave-ads-staging --rewards=staging=true --variations-server-url=https://v --enable-features="CustomAdNotifications:should_attached_ad_notification_to_browser_window/true"`
1. Enable rewards and ads
1. Trigger a notification ad

## Actual result:

Notification ad is attached to the screen when ad is moved rather than Brave Window
![19464_Ubuntu_screen](https://user-images.githubusercontent.com/34715963/162790944-3daf052a-a7a9-4e64-ac83-1847fd6abd61.gif)

Note: Notice that the ad is cropped, this is logged under https://github.com/brave/brave-browser/issues/22206

## Expected result:
Notification ad is attached to Brave Window when ad is moved

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.38.83 Chromium: 100.0.4896.79 (Official Build) beta (64-bit)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | Ubuntu 18.04 LTS

cc @brave/qa-team @jsecretan @tmancey @aseren

**Comment by aseren** [comment]
As I understand, a custom ad notification should have the same Z-order as a browser window. But should be attached to the edges of the screen. 
So it seems like we have a wrong feature parameter naming here. It should be something like `same_zorder_browser_window`.
cc @tmancey

**Comment by tmancey** [comment]
Closed by #29744
