### ISSUE TITLE
Please restore the stand alone installer on the github page.

### ISSUE THREAD

**Issue by ToddAndMargo** [brave/brave-browser#22226]
Dear Brave,

I am a consultant.  I have spread Brave Browser across two counties.  A lot of my customer do not have good Internet access, so I carry the stands alone installer with me on a write protected flash drive.   I have written a program to go out and download new releases of all the programs I support -- about 70 of them.

Problem,  you removed the Windows stand alone installer from the general release page:
https://github.com/brave/brave-browser/releases/tag/v1.37.112

The page says to use the stub installer, which is not always practical

Previously, the stand alone installer would be:
https://github.com/brave/brave-browser/releases/download/v1.37.112/BraveBrowserStandaloneSetup.exe

Please restore this functionality.  Or tell me where I can find the stinker.

Many thanks,
-T

**Comment by ToddAndMargo** [comment]
Looks like it is back on 1.37.113

Thank you!

**Comment by bsclifton** [comment]
Apologies for any outage of the binary @ToddAndMargo - definitely wasn't intentional. We always do try to have the standalone executables there 😄

**Comment by ToddAndMargo** [comment]
Hi Bsclifton,

I also updated my update routine to make sure the file was actually there before I triggered an update.

By the way, you guys sure  make the release update pretty hard to find at times.


This is Raku (Perl 6)

      $Page = -1;
      while $Page < 21  {
         $Page += 1;
         my Str $WebSitePage = $WebSite ~ "?page=" ~ "$Page";
         if $Debug  { PrintGreen "$SubName\: Checking Page $Page\n"; }

         if  CurlExists( $WebSitePage )  {
            ( $WebPage, $PageStatus ) = CurlGetWebSite( $WebSitePage, True );
            
            if $WebPage.contains( "Release v" ) { 
               my Str $Clicker;
               my Str$Rev;

               $Rev = $WebPage;
               $Rev ~~ s/ .*? "Release v" //;
               $Rev ~~ s/ $( Q[ ] ) .* //;
               if $Debug  { PrintBlue  "$SubName\: Rev = <$Rev> on Page <$Page>\n"; }
               
               $Clicker = $WebPrefix ~ "/brave/brave-browser/releases/download/v" ~ $Rev ~ "/BraveBrowserStandaloneSetup.exe";

               if $Debug  { PrintGreen "$SubName\: Checking if a Windows 64 bit exe exists:\n   <$Clicker>\n"; }
               # note: sometimes the latest release does not contain a Widows new release, so check for it
               if  CurlExists( $Clicker )  {
                  $NewRev    = $Rev;
                  $ClickHere = $Clicker;
                  if $Debug  { PrintGreen "$SubName\: release located on page $Page\n   <$WebSitePage>\n"; }
                  last;
               }  else { next; }  # if clicker
            } # contains
         } else { last }  # if else curl exists
         
      } # while
