### ISSUE TITLE
Center the Add button on `Add networks` setting screen

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#22220]
## Description 
The button is not in the center

## Steps to reproduce 

   1. Goto Settings
   2. Choose Brave Wallet => Networks
   3. Click on Add networks

## Actual result 
The Add button on the left

## Expected result
The Add button should be in the center

## Issue reproduces how often 
easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version?  Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes 
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): All
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
All

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

### Additional information

- Also fix the padding issue [21056](https://github.com/brave/brave-browser/issues/21056)
- Add a little space at the bottom of the add button as well, to separate its edges from the bottom bar.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.40.101 x64 build
- Verified `Add` button is center aligned in `Add Networks` settings screen

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/174069733-392e73f3-56a0-4584-b69a-0f581b2b2d84.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/174069754-6cfb546d-8544-4083-ab23-ccc6d140cb4b.png>
