### ISSUE TITLE
[De-AMP] Add support for checking de_amp_enabled user pref in cosmetic js filter

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#22228]
Add support for checking of DeAmp pref and flag in Cosmetic Filters JS Handlers, and add the boolean to the wrapping pre-init script. 

This is done so that we can add a new scriptlet for removing `jsaction` HTML attributes from anchor tags on Google SERP. 

More details here: https://docs.google.com/document/d/1kvHbQMdE_vxmRWRz0LfAHzf6XoTT_pQXSwxth5rVhsk/edit#heading=h.okf43yiuecg5

**Comment by kjozwiak** [comment]
The above will require `1.38.105` or higher for `1.38.x` verification 👍 Examples verification being completed can be found via https://github.com/brave/brave-core/pull/12923#issuecomment-1105953427.

**Comment by MadhaviSeelam** [comment]
Verification `In-progress`

Brave | 1.38.106 Chromium: 101.0.4951.41 (Official Build) (64-bit)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | Windows 11 Version 21H2 (Build 22000.613)

**Comment by stephendonner** [comment]
Verified `PASSED` using

Verification `Passed`

Brave | 1.38.107 Chromium: 101.0.4951.41 (Official Build) (x86_64)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | macOS Version 11.6.5 (Build 20G527)

Pre-requisites:  Mobile emulation via DevTools and set to Samsung Galaxy S8+

`de-AMP Disabled`

- ensured that Auto-redirect AMP pages was disabled via `brave://settings/shields`
- Loaded `https://www.google.co.uk` and then searched for Top Stories
- inspected the first article via DevTools and ensured that `jsaction` attribute appeared in the anchor link
- clicked on the link and ensured that the AMP version of the website/news article was being loaded
  -  URL: `https://www.nytimes.com/live/2022/04/25/world/ukraine-russia-war-news.amp.html`
- validated with google.com as well and results were same as expected

<details>  

ex1|ex2|ex3|ex4
---|---|---|---


</details>  

`de-AMP Enabled`

- ensured that Auto-redirect AMP pages was enabled via `brave://settings/shields`
- loaded  `https://www.google.co.uk` and then searched for Top Stories
- inspected the first article via DevTools and ensured that `jsaction` attribute didn't appear in the anchor link
- clicked on the link and ensured that the de-AMP version of the website/news article was being loaded
- validated with `google.com` as well and results were same as expected

<details>  

ex1|ex2|ex3|ex4
---|---|---|---


</details>

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+` running `Android 12` using the following build(s):

```
Brave | 1.40.3 Chromium: 101.0.4951.41 (Official Build) canary (32-bit)
--- | ---
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | Android 12; Build/SP1A.210812.016
```

Went through the STR/Cases outlined via https://github.com/brave/brave-core/pull/12923#issue-1195180651.

### **`de-AMP Disabled`**

* ensured that `Auto-redirect AMP pages` was disabled via `brave://settings/privacy`
* loaded `https://www.google.com` and then searched for `Top Stories`
* inspected the first article via `DevTools` and ensured that `jsaction` attribute appeared in the anchor link
* clicked on the link and ensured that the AMP version of the website/news article was being loaded
  * Example --> `https://www.cbc.ca/amp/1.6425708`

**`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------|-----------------
![Screenshot_20220426-140000_Brave](https://user-images.githubusercontent.com/2602313/165363499-a4b65c0d-b224-4fd4-aa15-dcb991c4f927.jpg) | ![image](https://user-images.githubusercontent.com/2602313/165363146-51af3579-0e99-43fe-b67d-7c421e7eb965.png) | ![Screenshot_20220426-140048_Brave](https://user-images.githubusercontent.com/2602313/165363685-de362e09-f5cc-47ae-a214-69885d52ab76.jpg) | ![Screenshot_20220426-140256_Brave](https://user-images.githubusercontent.com/2602313/165365054-7e249f71-2fd8-4c8c-b9ff-6b78c9b7d3de.jpg)

### **`de-AMP Enabled`**

* ensured that `Auto-redirect AMP pages` was enabled via `brave://settings/privacy`
* loaded `https://www.google.com` and then searched for `Top Stories`
* inspected the first article via `DevTools` and ensured that `jsaction` attribute wasn't appeared in the anchor link
* clicked on the link and ensured that the de-AMP version of the website/news article was being loaded

**`Example`** | **`Example`** | **`Example`** 
---------------|-----------------|---------------
![Screenshot_20220426-141338_Brave](https://user-images.githubusercontent.com/2602313/165366249-78dc7f34-d883-4674-a255-2533a8fcd1cd.jpg) | ![image](https://user-images.githubusercontent.com/2602313/165365348-e477a04e-97b7-41fe-9b46-82c8c04548e3.png) | ![Screenshot_20220426-141441_Brave](https://user-images.githubusercontent.com/2602313/165366274-b7d7dacd-d305-468c-b700-c02b24bcc1e3.jpg)

Quick note: I also tried `https://www.google.ca` & `https://www.google.co.uk`

**Comment by kjozwiak** [comment]
After speaking with @ShivanKaul, running through the mobile cases should be enough and tablet can be skipped. Tablet doesn't use AMP as much as the mobiles due to the view usually being `Desktop` due to the bigger screens. However, double checked and ensured that the feature has been enabled by default.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.38.107 Chromium: 101.0.4951.41 (Official Build) (64-bit)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | Ubuntu 18.04 LTS

Pre-requisites:  Mobile emulation via DevTools and set to Samsung Galaxy S8+

`de-AMP Disabled`

- ensured that Auto-redirect AMP pages was disabled via brave://settings/shields
- Loaded https://www.google.co.uk and then searched for Top Stories
- inspected the first article via DevTools and ensured that jsaction attribute appeared in the anchor link
- clicked on the link and ensured that the AMP version of the website/news article was being loaded
  -  URL: https://www.nytimes.com/live/2022/04/25/world/ukraine-russia-war-news.amp.html
- validated with google.com as well and results were same as expected

<details>  

![image](https://user-images.githubusercontent.com/34715963/165382522-9fa441a3-a477-4ec9-8fd3-3c6a5b6ff253.png)
![image](https://user-images.githubusercontent.com/34715963/165383160-081a919b-81d3-4604-aa97-f875dec10f24.png)
![image](https://user-images.githubusercontent.com/34715963/165383245-7c6573aa-bb5c-423b-b299-233e89ffec9a.png)

</details>  

`de-AMP Enabled`

- ensured that Auto-redirect AMP pages was enabled via brave://settings/shields
- loaded  https://www.google.co.uk and then searched for Top Stories
- inspected the first article via DevTools and ensured that jsaction attribute wasn't appeared in the anchor link
- clicked on the link and ensured that the de-AMP version of the website/news article was being loaded
- validated with google.com as well and results were same as expected

<details>  

![image](https://user-images.githubusercontent.com/34715963/165384137-8499164f-7d85-48e3-aa2a-c87cd7563281.png)
![image](https://user-images.githubusercontent.com/34715963/165384830-07e48b8d-9233-4e60-b483-7b374528c4f5.png)
![image](https://user-images.githubusercontent.com/34715963/165384932-6abbcb1a-9401-4bc8-a677-085ee9bbacfb.png)


</details>
