### ISSUE TITLE
How can I check why my url is being shield-blocked

### ISSUE THREAD

**Issue by Goufix** [brave/brave-browser#22248]
## Description 
I have an application where the users usually get the images from a company profile and put it into the application. Somehow those images are being blocked by brave shield

## Steps to Reproduce

   1. Go to https://62559f56721df.htmlsave.net/ with `shields` enabled
   2. See at the shield that the image was blocked

## Actual result:
![image](https://user-images.githubusercontent.com/9171169/163002681-acdaad40-78c1-40c9-9a71-ac2ffaa38b54.png)

## Expected result:
none. I just want to know what is blocking that image and if I can do something to bypass that.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
1.37.111 Chromium: 100.0.4896.79 (Official Build) (64-bit) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? I don't know
- Can you reproduce this issue with the nightly channel? I don't know

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:
I just want to know what is blocking that image and if I can do something to bypass that.

**Comment by ryanbr** [comment]
Hey @Goufix What is the full url being blocked? is there a sample page I can test?

**Comment by Goufix** [comment]
> Hey @Goufix What is the full url being blocked? is there a sample page I can test?

I don't know a good way to make a public HTML page. But if you create an HTML file with the follow content, it should be blocked.

```html
<img src="https://media-exp1.licdn.com/dms/image/C4D0BAQE-rEavR6_FZQ/company-logo_400_400/0/1526655992645?e=1651708800&v=beta&t=318RVPb2ZGasYunY2bmczrgGkPN5RpGMfGKtZITvCHQ" />

```

**Comment by ryanbr** [comment]
Is LinkedIn
