### ISSUE TITLE
Changes to sync codephrase

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#22242]
See details at https://github.com/brave/internal/issues/869, Android and Desktop part

**Comment by iccub** [comment]
iOS issue to track here
https://github.com/brave/brave-ios/issues/5362

**Comment by stephendonner** [comment]
Verification `IN-PROGRESS` using 

Brave | 1.41.59 Chromium: 103.0.5060.42 (Official Build) nightly (x86_64)
-- | --
Revision | de0d840bf9439c31bd86bf74f065c31fdf9b208d-refs/branch-heads/5060@{#667}
OS | macOS Version 12.5 (Build 21G5037d)



I. Old sync words are accepted before sync words sunset date
<details>

Create chain on old desktop browser, 24 words;
Connect new desktop browser to the chain - it should connect;
Connect new Android browser to the chain with words - it should connect.
Connect new Android browser to the chain with QR - it also should connect.

</details>

II. Old sync words are not accepted after sync words sunset date
<details>

Create chain on old desktop browser, 24 words;
magic room blind room mimic suspect interest fiber above south end injury quality wonder maid book syrup brush right alter fit weasel buffalo stove
Modify current date on the desktop to 2nd of June;
Try to connect new desktop browser to the chain - it should say
This code was generated by a deprecated version of Brave, please upgrade your other device first;
Modify current date on the desktop to 2nd of June;
Try to connect new Android browser to the chain with words - it also should say
This code was generated by a deprecated version of Brave, please upgrade your other device first;

</details>



III. Normal flow between new versions
<details>

Create sync chain on new desktop version, 25 words.
Connect new browser desktop to chain via words - it should succeed;
Connect new browser Android to chain via words - it also should succeed;

</details>

IV. Case for expired error
<details>

Create sync chain on new desktop version, 25 words.
Adjust time on 2nd desktop device 2 days forward;
Connect new browser desktop to chain via words - it should say
This code has expired. Please generate a new one on your other device and try again;
Adjust time on Android device 2 days forward;
Connect new browser Android to chain via words - it also should say
This code has expired. Please generate a new one on your other device and try again;

</details>

V. Case for too far in the future error
<details>

Create sync chain on new desktop version, 25 words.
Adjust time on 2nd desktop device 2 days backwards;
Connect new browser desktop to chain via words - it should say
This code is invalid. Please check that the time and timezone are set correctly on your device;
Adjust time on 2nd Android device 2 days backwards;
Connect new browser Android to chain via words - it also should also say
This code is invalid. Please check that the time and timezone are set correctly on your device.

</details>

VI. Case for general error of wrong code
<details>

Try to enter the sync chain on new dektop with words AAA BBB CCC - it should say
This code is invalid
Try to enter the sync chain on new Android with words AAA BBB CCC - it should also say
Wrong sync code

<img width="1312" alt="Screen Shot 2022-06-13 at 11 52 21 AM" src="https://user-images.githubusercontent.com/387249/173424580-81787941-023d-47a4-bc1d-ba0f91848980.png">

</details>

**Comment by stephendonner** [comment]
Verification `IN-PROGRESS` using 

Brave | 1.41.74 Chromium: 103.0.5060.53 (Official Build) beta (x86_64)
-- | --
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | macOS Version 11.6.7 (Build 20G630)




### Case I: Old sync words are accepted before sync words sunset date -
<details>

1. Created a new sync chain on `1.40.105` desktop browser (24 words)
2. Connected `1.41.x` desktop browser to the chain - it should connect

example | example | example | example
---------|--------|-----------|---------



</details>

### Case II. Old sync words are NOT accepted after sync words sunset date - PASSED
<details>

1. Create chain on `1.39.122` desktop browser (24 words)
2. Modify current date on the desktop to `August 2, 2022`
3. Try to connect `1.41.x` desktop browser to the chain - it should say `This code was generated by a deprecated version of Brave, please upgrade your other device first.`


example | example | example | example | example
---------|---------|----------|----------|---------




</details>



### Case III. Normal flow between new (`v2`) versions - PASSED
<details>

1. Create sync chain on `1.41.59` desktop version (25 words)
2. Connect new browser desktop to chain via words - it should succeed

Sync chain | new client joined | Synch chain updated
-----------|-------------------|---------------------



</details>

### Case IV. Expired error - PASSED
<details>

1. Create sync chain on`1.41.x` desktop version (25 words)
2. Adjust time on 2nd desktop device 2 days forward (`June 15, 2022` in my case)
4. Connect new browser desktop to chain via words - it should say `This code has expired. Please generate a new one on your other device and try again.`

example | example | example | example
---------|----------|---------|---------


</details>

### Case V. Too-far-in-the-future codes - PASSED
<details>

1. Create sync chain on `1.41.x` desktop version (25 words)
2. Adjust time on 2nd desktop device 2 days backwards (`June 19, 2022` in my case)
3. Connect new browser desktop to chain via words - it should say `This code is invalid. Please check that the time and timezone are set correctly on your device.`

example | example | example | example | example
---------|----------|---------|----------|--------





</details>

### Case VI. General errors for incorrect codes - PASSED
<details>

- Try to enter the sync chain on `1.41.x` desktop with words `AAA BBB CCC`, etc.- it should say `This code is invalid`

`AAA BBB CCC` | `AAA -> YYYY`
-----------------|----------------


Also made sure we got errors using `24` `25` and `26`word-count entries.

`24-count error` | `25-count error` | `26-count error`
---|----|----


</details>

**Comment by MadhaviSeelam** [comment]
Verification `In-progress` using
``
Brave | 1.41.74 Chromium: 103.0.5060.53 (Official Build) beta (64-bit)
-- | --
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | Windows 11 Version 21H2 (Build 22000.739)
```

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 



### Case I: Old sync words are accepted before sync words sunset date -
<details>

1. Created a new sync chain on `1.40.105` desktop browser (24 words)
2. Connected `1.41.74` desktop browser to the chain - it should connect

example | example | example
---------|--------|----------




</details>

### Case II. Old sync words are NOT accepted after sync words sunset date -
<details>

1. Create chain on `1.39.122` desktop browser (24 words)
2. Modify current date on the client (2nd) desktop to `August 2, 2022`
3. Try to connect `1.41.x` desktop browser to the chain - it should say `This code was generated by a deprecated version of Brave, please upgrade your other device first.`


example | example | example | example
---------|---------|----------|---------






</details>



### Case III. Normal flow between new (`v2`) versions -
<details>

1. Create sync chain on `1.41.59` desktop version (25 words)
2. Connect new browser desktop to chain via words - it should succeed

Sync chain | new client joined | Synch chain updated
-----------|-------------------|---------------------







</details>

### Case IV. Expired error -
<details>

1. Create sync chain on`1.41.x` desktop version (25 words)
2. Adjust time on 2nd desktop device 2 days forward (`June 23, 2022` in my case)
4. Connect new browser desktop to chain via words - it should say `This code has expired. Please generate a new one on your other device and try again.`

example | example | example | example | example
---------|----------|---------|----------|---------






</details>

### Case V. Too-far-in-the-future codes -
<details>

1. Create sync chain on `1.41.x` desktop version (25 words)
2. Adjust time on 2nd desktop device 2 days backwards (`June 19, 2022` in my case)
3. Connect new browser desktop to chain via words - it should say `This code is invalid. Please check that the time and timezone are set correctly on your device.`

example | example | example | example
---------|----------|---------|---------







</details>

### Case VI. General errors for incorrect codes -
<details>

- Try to enter the sync chain on `1.41.x` desktop with words `AAA BBB CCC`, etc.- it should say `This code is invalid`

`AAA BBB CCC` | `AAA -> YYYY`
-----------------|----------------


Also made sure we got errors using `24` `25` and `26`word-count entries.

`24-count error` | `25-count error` | `26-count error`
---|----|----


</details>

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5(Android 12) /Samsung Tab A (Android 10) running 1.41.94 x64 build

<details>
<Summary><b>Case 1: Sync between devices running v2 version with cross time zones</b></summary>

- Verified able to sync devices running Sync v2 
- Verified both devices are listed correctly 
- Verified switching time zones on the devices and resetting Sync and creating a new one works fine

Sync v2 code | Device 1 (Source) | Device 2
-- | -- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/177964096-c2c11cc5-2c59-49cf-8eb8-6eac2e701107.png> | <img width=300 src=https://user-images.githubusercontent.com/17010094/177964169-ffe88015-b19d-4f3d-991c-45cab316e907.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/177964260-e6545221-1c48-45d7-a08e-ed9920e998d0.png>

</details>
<details>
<Summary><b>Case 2: Old sync words are accepted before sync words sunset date </b></summary>

- Verified creating Sync chain on Device A using 1.40.101 which uses `24 sync words` works fine
- Verified able to connect Device B to Sync chain using QR Code
- Verified able to connect Device C to Sync chain using code words
- Verified Device B adds the 25th word to the list which is time based and not sync'd back to Device A

Device A (24 words) | Device B (25 Words ) 
-- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/177990630-e37cd1df-1ed5-45e7-a0be-67ab200c0e76.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/177990687-ab0371b7-3803-4022-8830-931fb6b9bc13.png>

</details>

</details>
<details>
<Summary><b>Case 3: Old sync words are NOT accepted after sync words sunset date (Partial Pass)</b></summary>

- Verified creating Sync chain on Device A using 1.39.123 which uses `24 sync words` works fine
- Verified when trying to enter Sync code words on Device B running 1.41.94 throws error message `Sync could not be setup [This code was generated by a deprecated version of Brave, please upgrade your other device first]`
- Encountered [#23936](https://github.com/brave/brave-browser/issues/23936) when trying add sync chain via QR code 

Device A (24 words) | Device B (25 Words ) 
-- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/177990630-e37cd1df-1ed5-45e7-a0be-67ab200c0e76.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/177990687-ab0371b7-3803-4022-8830-931fb6b9bc13.png>

</details>
<details>
<Summary><b>Case 4: Case for expired error</b></summary>

- Verified able to create sync chain with 25 words on Device A
- Move Device B dates ahead by 2 days and try to sync with QR Code, shows error `This code has expired. Please generate a new one on your other device and try again`

QR Code | Code Words
-- | --
![image](https://user-images.githubusercontent.com/17010094/178028502-2e5aee88-341d-41b6-84f5-d9318991a473.png) | ![image](https://user-images.githubusercontent.com/17010094/178028520-284025f3-d6c2-4f7e-a770-bf0133ebe7d1.png)

</details>
<details>
<Summary><b>Case 5: Case for too far in the future error</b></summary>

- Verified able to create sync chain with 25 words on Device A
- Move Device B dates behind by 2 days and try to sync with QR Code, shows error `This code is invalid. Please check that the time and timezone are set correctly on your device.`
- Encountered [#23948](https://github.com/brave/brave-browser/issues/23948)

</details>
<details>
<Summary><b>Case 6: Case for general error of wrong code</b></summary>

- Verified entering `AAA BBB CCC` says `Wrong sync code`
<img width=300 src=https://user-images.githubusercontent.com/17010094/178035026-ac9c6860-c244-4dde-bce7-f7a7b42b9f6d.png>

</details>
