### ISSUE TITLE
Shields cosmetic filitering preference is not set to "allow", when the user setting is set to "allow"

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#22249]
## Description 

The internal cosmetic filtering preference is not set correctly when adjusting ad-block settings for a specific domain, using the new Shields UI. This does not affect Shields functionality, but does affect an assumption made by the new Shields P3A reporting functionality.

To test fix, change ad-block setting to "allow" for one domain, and validate that `brave://prefs-internals` shows `1` for the domain's cosmetic filtering setting.

i.e.
```
         "cosmeticFiltering": {
           "www.reddit.com,*": {
              "expiration": "0",
              "last_modified": "13294255498893083",
              "model": 0,
              "setting": 1
           },
           "www.reddit.com,https://firstparty": {
              "expiration": "0",
              "last_modified": "13294255498893134",
              "model": 0,
              "setting": 1
           }
        }
```

## Miscellaneous Information:

Fixed in PR brave/brave-core#12583

**Comment by kjozwiak** [comment]
Above requires `1.38.93` or later for `1.38.x` verification.

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.38.99 Chromium: 100.0.4896.127 (Official Build) beta (x86_64)
-- | --
Revision | ff0d0695743e65305d7194f9bd309e5e1c824aa0-refs/branch-heads/4896_88@{#4}
OS | macOS Version 12.4 (Build 21F5048e)



Steps:
1. installed `1.38.99`
2. launched Brave
3. loaded `cnn.com`
4. clicked on the Shields icon in the URL bar
5. changed `Block ads and trackers` to `Allow ads and trackers`
6. opened `brave://prefs-internals`
7. searched for `cnn.com`
8. confirmed the entries for `cnn.com` have a value of `1`

example | example | example
---------|----------|---------
<img width="1312" alt="Screen Shot 2022-04-18 at 4 38 44 PM" src="https://user-images.githubusercontent.com/387249/163893822-bab2cd15-9201-4ad4-89ed-492dd616287a.png"> | <img width="1312" alt="Screen Shot 2022-04-18 at 4 38 50 PM" src="https://user-images.githubusercontent.com/387249/163893827-dbf0058f-9dc2-457f-b15d-c1973d293525.png"> | <img width="1312" alt="Screen Shot 2022-04-18 at 4 39 12 PM" src="https://user-images.githubusercontent.com/387249/163893836-79c00b01-5344-4f08-ab03-057dd995df3e.png">
