### ISSUE TITLE
typo for blocked scripts panel

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#22254]
## Description 

In Shields blocked scripts panel, main label should read `Blocked` versus `Block`

## Steps to Reproduce

   1. Go to any website and open up shields panel in greater than 1.38.x
   2. Go to Advanced controls and select Block scripts.
   3. Select the number on blocked scripts to go to the Blocked Scripts panel.

## Actual result:
Notice it read n Block scripts.

<img width="388" alt="screen_shot_2022-04-12_at_12 12 53_pm" src="https://user-images.githubusercontent.com/5951041/163038216-32418dcb-5038-46e7-a83d-81bf6a32b5a2.png">

## Expected result:
Should read Blocked scripts
<img width="838" alt="image" src="https://user-images.githubusercontent.com/5951041/163038312-7026ba69-0d95-4e3d-b1f2-443287780b41.png">

## Reproduces how often: 

Easily.

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
cc: @aguscruiz @nullhook

**Comment by 4444dogs** [comment]
I can confirm that this issue can be reproduced on the latest stable release of Brave.

**Comment by rebron** [comment]
<img width="444" alt="Screenshot 2024-06-14 at 7 38 47 AM" src="https://github.com/brave/brave-browser/assets/5951041/6198c57a-f6de-4274-88c6-e3f92cc2b3d4">
Closing as stale. Fixed in prior milestone. Checked in 1.67.115
