### ISSUE TITLE
Can't disable shield for local site

### ISSUE THREAD

**Issue by Haxy89** [brave/brave-browser#2225]
In my local lan network I can't disable shield, after reload the page shield is enabled.

http://192.168.0.18:9998/
http://192.168.0.17:8096/web/index.html#!/home.html
https://192.168.0.5:8081/cgi-bin/

**Comment by eljuno** [comment]
+1 from Community https://community.brave.com/t/unable-to-turn-off-shields-up-after-upgrade/39291?u=eljuno

**Comment by damassi** [comment]
Just noticing this too and it breaks our local development environment. Is there a way to access site shield settings via a config file or is the only way to turn it on / off via the dragger?

**Comment by mckenzieja** [comment]
+1 

Have this issue as well and would preferably NOT use another browser.

**Comment by allisonphillips** [comment]
+1

**Comment by simonhong** [comment]
duplicated issue. merged into https://github.com/brave/brave-browser/issues/1896
