### ISSUE TITLE
Brave Google Play Services dependence

### ISSUE THREAD

**Issue by minimalist-on-github** [brave/brave-browser#22253]
## Description
Brave constantly telling me that I must enable Google Play Services to use it. Privacy-respective browser shouldn't depend on proprietary services!
## Steps to reproduce 

   1. Install any version of Brave for Android.
   2. Wait 1-2 days.
   3. Brave'll start sending you a notification ''Enable Google Play Services''. By the way, you can see this dependence on Aurora Store.

## Actual result 
Brave depends on proprietary software.

## Expected result

Brave is FOSS browser without trash and with good privacy protection.
## Issue reproduces how often 

Easily reproduced
## Version/Channel Information:

All channels
- Can you reproduce this issue with the current Play Store version? 
Yes.
- Can you reproduce this issue with the current Play Store Beta version? 
Yes.
- Can you reproduce this issue with the current Play Store Nightly version?
Yes.

## Device details
   - Install type (ARM, x86): 
Any Android version.
   - Device type (Phone, Tablet, Phablet):
Phone
   - Android version:
11 RKQ1.200826.002
   
## Brave version
Any Brave version for Android.

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
No.
- Does the issue resolve itself when disabling Brave Rewards?
No.
- Is the issue reproducible on the latest version of Chrome? 
Most likely (I use degoogled device)
### Additional information
![SAVE_20220412_222814_1.jpg](https://user-images.githubusercontent.com/101062623/163039685-cb92c7e4-0d4b-4da0-a4d2-9deecd897965.jpg)
Brave developers should remove this dependence immediately.

**Comment by diracdeltas** [comment]
cc @SergeyZhukovsky, not sure what could be causing this

**Comment by m77e4t** [comment]
Have you enabled Brave Rewards? As I know it, brave uses google play services to prompt the notification ads and for some other stuff. Turn Off brave rewards and see if it stops these notifications.

I, too, am on degoogled custom android ROM, with no gsf, play services etc and I do not get such notifications. I have not enabled brave rewards as it being dependent on google plays serves and users reporting getting problems claiming their rewards https://teddit.net/r/brave_browser/comments/r96nzb/whats_the_best_way_to_submit_a_feature_request_i/.

But, I likewise have a problem related to brave browser on android due to its dependence on play services https://github.com/brave/brave-browser/issues/20229.

**Comment by dob777** [comment]
The same issue here.

<img src="https://github.com/brave/brave-browser/assets/121567421/174a6bff-205f-4dce-9ea9-4a43fa85cf41" width="300" />

I can't use Brave on my LineageOS 19.1 (with gapps disabled) cause it's just spamming a notification even if I close Brave. Imo this dependence is not acceptable for a real privacy browser so I ask devs to remove it as well

**Comment by ddubnyk** [comment]
It also seems as if brave sync is reliant on Google Play Services.  I use a Pixel, and OnePlus 6T with Lineage and no GApps package and in order to use sync it requires play services.  Come on guys, drop this dependance on propreitary crap

**Comment by bsclifton** [comment]
Thanks for the report folks - this is a known issue

We depend on Google Play Services for Safe Browsing, Brave Rewards, and more. We do have an existing issue for folks w/ LineageOS that you can +1 here:
https://github.com/brave/brave-browser/issues/7027

Let's move the conversation there 😄 

To recap: this dependence on Google Play Services is expected and we don't have plans to address. 
I know this isn't a happy answer, but maybe we can carry on conversation in https://github.com/brave/brave-browser/issues/7027
