### ISSUE TITLE
Re-allow cosmetic filtering to override in-page `!important` styles after regression

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#22264]
https://github.com/brave/brave-core/pull/12038 originally provided a fix for https://github.com/brave/brave-browser/issues/20177, allowing cosmetic filters returned by the adblock engine to be injected into pages with a higher precedence than the page's stylesheets.

Unfortunately, the new method used to inject those CSS rules involved creating a new stylesheet for each rule, rather than the previous method which would simply add rules to a single stylesheet. That turned out to have a significant performance impact, especially for some users and websites; it was reverted in https://github.com/brave/brave-core/pull/12950.

There doesn't appear to be a way exposed by Chromium to inject a privileged stylesheet from JS that also works on Android, or from C++ that doesn't involve creating an entire new stylesheet. Fixing this will likely involve patching [`StyleEngine`](https://github.com/brave/brave-core/pull/12950) to support a new stylesheet specifically used for cosmetic filtering.

**Comment by antonok-edm** [comment]
Note that #13079 fixed it for all cases except for general class/id injections in standard blocking mode. That will be solved in a followup and is tracked in https://github.com/brave/brave-browser/issues/22474.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` with 
```
Brave | 1.38.118 Chromium: 101.0.4951.67 (Official Build) (64-bit)
-- | --
Revision | 8888ee7a24e2c36661ddb9536c35b7d4852a3a98-refs/branch-heads/4951@{#1230}
OS | Windows 11 Version 21H2 (Build 22000.675)
```

### **`Test Case #1`** - https://github.com/brave/brave-browser/issues/22030#issuecomment-1090632101

* `1.38.115 Chromium: 101.0.4951.64` - without fix
* `1.38.118 Chromium: 101.0.4951.67` - with fix

**`Shields enabled:`**
*Using `1.38.115 Chromium: 101.0.4951.64`: `290ms`, `276ms`, `298ms`. `288ms`
*Using `1.38.118 Chromium: 101.0.4951.67`:  `237ms`, `297ms`, `287ms`. `339ms`

**`1.38.115 Chromium: 101.0.4951.64`**|**`1.38.118 Chromium: 101.0.4951.67`**
---|---
<img width="944" alt="drun1" src="https://user-images.githubusercontent.com/98358127/168654173-61862ddf-0e26-480a-a99e-3e7e3e63a480.png">|<img width="956" alt="Run 1" src="https://user-images.githubusercontent.com/98358127/168647130-bea33034-c928-4b91-b878-ed5531ce08b9.png">

**`Shields disabled:`**

*Using `1.38.115 Chromium: 101.0.4951.64` - `289ms`, `455ms`, `252ms`, `275ms`
*Using `1.38.118 Chromium: 101.0.4951.67` - `217ms`, `250ms`, `229ms`, `287ms`

**`1.38.115 Chromium: 101.0.4951.64 Example`**|**`1.38.118 Chromium: 101.0.4951.67`**
---|---
<img width="944" alt="drun1" src="https://user-images.githubusercontent.com/98358127/168653835-7ee5bd23-41d8-4aac-a959-b6ab08f89012.png">|<img width="957" alt="run1" src="https://user-images.githubusercontent.com/98358127/168649230-1965d69e-c00f-414b-9817-64f3fa79d291.png">

### **`Test Case #2`** -https://www.foodnetwork.com/recipes/food-network-kitchen/classic-shrimp-scampi-8849846

**`1.38.115 Chromium: 101.0.4951.64 Example`**|**`1.38.118 Chromium: 101.0.4951.67 Example`**
---|---
<img width="948" alt="Screenshot 2022-05-16 110655" src="https://user-images.githubusercontent.com/98358127/168655737-ef3dbc4c-7262-45b3-8b25-5359b172241d.png">|<img width="957" alt="ex1" src="https://user-images.githubusercontent.com/98358127/168650759-43880132-4133-4a71-bc6c-27e0369d0d3a.png">

**Comment by Uni-verse** [comment]
Verification in Progress using 1.38.118, Chromium 101.0.4951.67

Test Case 1: https://news.ycombinator.com/item?id=30932095 - In Progress 

Shields ON:

1.38.118 : 572s, 702s, 668s, 630s, 504s
1.38.113: 

Shields OFF: 

1.38.118: 474s, 622s, 664s, 576s, 404s 
1.38.113: 


Test Case 2: In Progress

**Comment by Uni-verse** [comment]
Verification Completed using `1.38.118, Chromium 101.0.4951.67` on `Samsung Tab S7` running `Android 12`

Test Case 1: https://news.ycombinator.com/item?id=30932095

Shields ON:

1.38.118 : 731ms, 883ms, 789ms, 766ms, 847ms
1.38.113: 881ms, 755ms, 877ms, 922ms, 840ms

Shields OFF:

1.38.118: 678ms, 713ms, 681ms, 615ms, 627ms
1.38.113: 766ms, 799ms, 706ms, 952ms, 742ms

Test Case 2: https://www.foodnetwork.com/recipes/food-network-kitchen/classic-shrimp-scampi-8849846

1.38.118 | 1.38.113
-|-
![Screen Shot 2022-05-16 at 8 03 16 PM](https://user-images.githubusercontent.com/17885425/168720199-a62f9ee8-23cd-4945-9f77-02d53f29b788.png) | ![Screen Shot 2022-05-16 at 8 12 22 PM](https://user-images.githubusercontent.com/17885425/168720810-92931dc4-ad71-4598-89d9-4a4c34680def.png)
