### ISSUE TITLE
Display warning for SolanaSPLTokenTransferWithAssociatedTokenAccountCreation Transactions

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#22260]
## Description 
We need to display a warning in the `ConfirmTransaction` Panel for `SolanaSPLTokenTransferWithAssociatedTokenAccountCreation` Transactions abou additional `SOL` fee's.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.39.109 Chromium: 102.0.5005.50 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>f6e2cf8f59ec714bdcff8499991d55898875f287-refs/branch-heads/5005@{#648}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22621.1)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/13036>brave/brave-core#13036</a></li>
         <li>Verified warning message is shown the first a SPL token is transacted</li>
        </ul>
      </td>
   </tr>
</table>
