### ISSUE TITLE
[De-AMP] Miscellaneous fixes

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#22262]
- Tweak DeAMP regexes to be lazy, based on https://bravesoftware.slack.com/archives/G15HNQKV5/p1649699670558059?thread_ts=1649351034.570879&cid=G15HNQKV5
- The amp html attribute might have empty value i.e. amp=""
- Move DeAMP (from Security & Privacy section) and ReduceLanguage (from bottom of brave://settings/shields) settings to be near-top of brave://settings/shields so as to separate them from other per-site privacy settings after discussion with @pes10k

**Comment by Uni-verse** [comment]
Verification completed on Samsung GS 21, Samsung Tab S7 using 

```
Brave	1.38.106 Chromium: 101.0.4951.41 (Official Build) (64-bit) 
Revision	93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS	Android 12;
```
- Checked the urls in Test plan https://github.com/brave/brave-core/pull/12999#issue-1202435157 and confirmed the amp attribute is not shown anywhere when de-AMP option is enabled.

Enabled | Disabled
-|-
![Screen Shot 2022-04-25 at 11 36 35 AM](https://user-images.githubusercontent.com/17885425/165154604-abc65241-cfba-497e-8f18-0945d6fc1df0.png) | ![Screen Shot 2022-04-25 at 11 48 06 AM](https://user-images.githubusercontent.com/17885425/165154624-0f3502ff-0cae-460a-ad88-b32a4b27a3a9.png)
![Screen Shot 2022-04-25 at 11 39 09 AM](https://user-images.githubusercontent.com/17885425/165154609-b7d16abe-81cb-4e52-a7da-bbfe9f0361cd.png)  | ![Screen Shot 2022-04-25 at 11 47 22 AM](https://user-images.githubusercontent.com/17885425/165154621-77462af7-8abc-43e3-b447-d31de5bac6f4.png)
![Screen Shot 2022-04-25 at 11 39 51 AM](https://user-images.githubusercontent.com/17885425/165154610-32b4a66a-4d2f-4473-b865-09c1869cc037.png) | ![Screen Shot 2022-04-25 at 11 46 11 AM](https://user-images.githubusercontent.com/17885425/165154619-7c53fd98-f2fa-4ec6-a37e-0d40efc26e4f.png)
![Screen Shot 2022-04-25 at 11 41 39 AM](https://user-images.githubusercontent.com/17885425/165154612-4a703926-9de7-4fdd-b1b2-d49ff8a91ac2.png) | ![Screen Shot 2022-04-25 at 11 44 12 AM](https://user-images.githubusercontent.com/17885425/165154615-b2f952d1-6828-446a-9cb7-03d7980fcdb2.png)

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```

Brave | 1.38.106 Chromium: 101.0.4951.41 (Official Build) (64-bit)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | Windows 10 Version 21H2 (Build 19044.1645)

```

**Comment by stephendonner** [comment]
Verified `PASSED` using 


Brave | 1.38.107 Chromium: 101.0.4951.41 (Official Build) (x86_64)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | macOS Version 11.6.5 (Build 20G527)

`Enabled` | `Disabled`
-----------|-----------
<img width="1312" alt="Screen Shot 2022-04-26 at 11 42 45 AM" src="https://user-images.githubusercontent.com/387249/165370602-3ac392fe-fdea-4b2b-9e07-66f8e85bd813.png"> | <img width="1312" alt="Screen Shot 2022-04-26 at 11 44 22 AM" src="https://user-images.githubusercontent.com/387249/165370612-119458fc-2d44-48fc-bf91-993c0fac4e28.png">
