### ISSUE TITLE
Brave crash after changing the shield settings

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#22276]
## Description 

Brave crash after changing the shield settings

## Steps to Reproduce

   1. Clean profile 1.38.x
   2. Open a cnn.com website in win 1 and theverge.com in win 2
   3. Open the shield panel and change the shield settings to "Allow" and then "Aggressive" and then "Block" in win 1
   4. Keep the browser idle for 15 to 20 mins
   5. Open the browser and try to change the shield settings in win1 
   6. Brave crashes

## Actual result:

Brave crash

## Expected result:
Should not be any crash

## Reproduces how often: 

80%

## Brave version (brave://version info)

<html>
<body>

Brave | 1.38.90 Chromium: 100.0.4896.79 (Official Build) beta (64-bit)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | Windows 10 Version 21H2 (Build 19044.1586)

</body>
</html>
## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @rebron

**Comment by GeetaSarvadnya** [comment]
Now I can reproduce the issue consistently. 


```
Status:	Uploaded
Uploaded Crash Report ID:	f3140000-fb20-0d08-0000-000000000000
Upload Time:	Wednesday, April 13, 2022 at 11:41:08 PM
```

**Comment by rebron** [comment]
cc: @iefremov

**Comment by nullhook** [comment]
This needs to be re-tested after https://github.com/brave/brave-core/pull/13029 gets uplifted

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
Brave | 1.38.103 Chromium: 100.0.4896.127 (Official Build) beta (64-bit)
-- | --
Revision | ff0d0695743e65305d7194f9bd309e5e1c824aa0-refs/branch-heads/4896_88@{#4}
OS | Windows 10 Version 21H2 (Build 19044.1645)

```

- Verified the STR from the issue and ensured there is no crash when shield settings are changed in two windows

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.38.105 Chromium: 101.0.4951.41 (Official Build) (x86_64)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | macOS Version 11.6.5 (Build 20G527)

Also confirmed no crash with the steps to reproduce from this issue, and exploratory testing 👍
