### ISSUE TITLE
Unblinded token confirmation does not contain catalog `id`

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#22279]
Follow up to #18100 Add RPill to unblinded token and unblinded payment token redemption

## Steps to Reproduce

   1. Check Unblinded token confirmation request for `id`

## Actual result:

'id' is missing

## Expected result:
'id' is included in the request

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)
Brave | 1.38.83 Chromium: 100.0.4896.79 (Official Build) beta (64-bit
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | Ubuntu 18.04 LTS

cc @brave/qa-team @tmancey @jsecretan

**Comment by kjozwiak** [comment]
Above requires `1.38.95` or higher for `1.38.x` verification.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.38.96 Chromium: 100.0.4896.88 (Official Build) beta (64-bit)
-- | --
Revision | 4450653bfa91182e85723d8f1dee64dd6ce40ed4-refs/branch-heads/4896@{#1086}
OS | Ubuntu 18.04 LTS

Verified id is included in the confirmation

![image](https://user-images.githubusercontent.com/34715963/163593136-bdcf4a95-4d5b-4258-a701-2ca8bdd08a13.png)
