### ISSUE TITLE
Implement displaying of waiter message in sync-UI

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#2227]
## Description 

Initialization of sync takes a time, usually 2..7 seconds. 

Currently during this time the popup dialog is on the page and nothing happens.

It would be good to let the user know that 'operation is in progress' , like:
1) show yet another popup blocking the page
or
2) disable controls on current popup and show some message on popup
or 
3) some other cool way.

The waiter message should be shown between these points:
A) chrome.send('setupSyncHaveCode', ...) or
   chrome.send('setupSyncNewToSync'
B) function syncSetupError(error: string) or 
   function showSettings (settings: any, devices: any)

## Steps to Reproduce

   1. Create sync chain on one device 1
   2. Connect device 2 to sync chain with code words 
   3. While it does processing should be displayed waiter message

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
yes

### Additional Information

Related issue https://github.com/brave/brave-browser/issues/2130

**Comment by cezaraugusto** [comment]
thanks @AlexeyBarabash I'm closing this in favor of https://github.com/brave/brave-browser/issues/2567
