### ISSUE TITLE
No module named ‘urlparse’

### ISSUE THREAD

**Issue by JaKuth99** [brave/brave-browser#2228]
## Description 
Upon the attempt to run urlparse is not found, producing npm errors

## Steps to Reproduce

   1. Run npm install
   2. Run npm run init 

## Actual result:
ModuleNotFoundError

## Expected result:
Successful init run

## Reproduces how often
Easily reproducible

## Brave version (brave://version info)

Newest version 

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by sbuller** [comment]
Looks like gclient uses python2 (which is being retired in one year) without having the courtesy of stating it in their shebangs. They've been aware of the problem since 2010. So... yeah. You'll have to hack around with your path in order to get gclient to use python2. :(

**Comment by sbuller** [comment]
Also, this is me contemplating whether the nuisance of doing the same is worth my while. (probably not)

**Comment by JaKuth99** [comment]
Would it be possible to set the default environment to python 2, build it, then set it back to python 3?

**Comment by srirambv** [comment]
cc: @bbondy @bridiver @bsclifton

**Comment by bsclifton** [comment]
I'd recommend using something like virtualenv to get this using Python 2

**Comment by vitarnja** [comment]
instead
-----
import urlparse
------
switch to
----
try:
    import urlparse
except ImportError:
    import urllib.parse as urlparse
----
