### ISSUE TITLE
The incorrect site favicon is shown in the shield panel when switching between the two sites

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#22284]
## Description 

The incorrect site favicon is shown in the shield panel when switching between the two sites

## Steps to Reproduce

   1. Clean profile 1.38.x or 1.39.x
   2. Open a cnn.com in tab 1 and theverge.com in tab2
   3. Open the shield in tab2 and ensure the correct site favicon is shown for theverge.com
   4. Open the shield in tab1 and check the site favicon for cnn.com, the site favicon is shown from the tab 2 which is incorrect

**Note**: reload the site fixes the issue

## Actual result:

The incorrect site favicon is shown in the shield panel when switching between the two sites

![favicon changes for a site in shiled when switch between the tabs](https://user-images.githubusercontent.com/38657976/163250060-4003d411-06af-4fa6-aa08-b9d8ad96d3aa.gif)

![image](https://user-images.githubusercontent.com/38657976/163250244-4d99fff5-843a-431d-be3f-e26a018b444c.png)

## Expected result:
The correct site favicon should be shown in the shield panel when switching between the two sites

## Reproduces how often: 

Easy
## Brave version (brave://version info)

<html>
<body>

Brave | 1.38.90 Chromium: 100.0.4896.79 (Official Build) beta (64-bit)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | Windows 10 Version 21H2 (Build 19044.1586)

</body>
</html>
## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @rebron @nullhook

**Comment by kjozwiak** [comment]
Above requires `1.38.102` or higher for `1.38.x` verification.

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```

Brave | 1.38.103 Chromium: 100.0.4896.127 (Official Build) beta (64-bit)
-- | --
Revision | ff0d0695743e65305d7194f9bd309e5e1c824aa0-refs/branch-heads/4896_88@{#4}
OS | Windows 10 Version 21H2 (Build 19044.1645)

```
- Verified the STR from the description and ensured the shield panel is showing up the correct site favicon when switching between the two sites.

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.38.103 Chromium: 100.0.4896.127 (Official Build) beta (x86_64)
-- | --
Revision | ff0d0695743e65305d7194f9bd309e5e1c824aa0-refs/branch-heads/4896_88@{#4}
OS | macOS Version 11.6.5 (Build 20G527)

Confirmed the Shields panel shows the correct site favicon when switching between two sites.
