### ISSUE TITLE
update shields down design 

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#22283]
## Description 

Current design for shields down in beta/nightly 1.38.x/1.39.x could be simpler. Currently has a lot of text when primary actions are to toggle shields back on or to report a broken web site.

1. Remove string "You're viewing this site without Brave's privacy protections."
2. Make "Report site" button wider and more visible.

See new designs below.

## Steps to Reproduce

   1. Use 1.38.x or higher. Go to a website and turn off shields.
   3. Notice the design in actual result. Currently too much text.

## Actual result:

<img width="441" alt="Screen Shot 2022-04-13 at 11 19 18 AM" src="https://user-images.githubusercontent.com/5951041/163246417-8dce8fa9-10d0-4e3e-85c3-9fa4bed28c70.png">

## Expected result:
https://www.figma.com/file/3A6F6VrxVahiZFxLr7j7FO/Desktop-Brave-Shields?node-id=1804%3A30480
<img width="747" alt="Screen Shot 2022-04-13 at 1 00 49 PM" src="https://user-images.githubusercontent.com/5951041/163260695-b5b5657d-b38a-42bc-beb9-87defc22297c.png">

## Reproduces how often: 

Easily.

## Brave version (brave://version info)

1.38.x and higher

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by kjozwiak** [comment]
Above requires `1.38.102` or higher for `1.38.x` verification.

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```
Brave | 1.38.103 Chromium: 100.0.4896.127 (Official Build) beta (64-bit)
-- | --
Revision | ff0d0695743e65305d7194f9bd309e5e1c824aa0-refs/branch-heads/4896_88@{#4}
OS | Windows 10 Version 21H2 (Build 19044.1645)

```

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.38.103 Chromium: 100.0.4896.127 (Official Build) beta (x86_64)
-- | --
Revision | ff0d0695743e65305d7194f9bd309e5e1c824aa0-refs/branch-heads/4896_88@{#4}
OS | macOS Version 11.6.5 (Build 20G527)

Confirmed Shields are to Figma spec.

`light` mode | `dark` mode
-----|-----
<img width="393" alt="Screen Shot 2022-04-20 at 8 54 46 AM" src="https://user-images.githubusercontent.com/387249/164272552-5edce04f-de40-4337-b2ec-c4579843261a.png"> | <img width="393" alt="Screen Shot 2022-04-20 at 8 53 48 AM" src="https://user-images.githubusercontent.com/387249/164272643-fe805557-d863-425b-990d-7012a0d60b1e.png">

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.38.105 Chromium: 101.0.4951.41 (Official Build) (64-bit)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | Ubuntu 18.04 LTS

Confirmed Shields are to Figma spec.


![image](https://user-images.githubusercontent.com/34715963/164814474-5413bc68-ce5f-475e-b411-d5c7d6a55f14.png)
![image](https://user-images.githubusercontent.com/34715963/164814510-6afdc39e-1f25-4e6e-b823-2251e78328c8.png)
