### ISSUE TITLE
Connect with site panel showing other CoinType Accounts

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#22280]
## Description 
The second  `step` in the `Connect With Site` panel is showing `Accounts` for other `CoinTypes` as select by user.

![Screen Shot 2022-04-12 at 4 08 42 PM](https://user-images.githubusercontent.com/40611140/163207547-4874f103-08fb-4a5f-9b0e-708ba494a7ba.png)

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.39.111 Chromium: 102.0.5005.61 (Official Build) (64-bit) </th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22621.1)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/13009>brave/brave-core#13009</a></li>
         <li>Verified connect with site panel only shows Ethereum Accounts</li>
         <li>Encountered <a href=https://github.com/brave/brave-browser/issues/22999>#22999</a></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/169785232-53026fd6-f76b-4243-b2d7-22864e5c2acb.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/169785330-a94aeef7-e060-41d7-b6cc-75e2117cd085.mov>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/169785255-2f21be4e-abd9-459d-82e8-50dd6a6f5234.mov>
      </td>
   </tr>
</table>
