### ISSUE TITLE
Console Warning in Confirm Transaction Panel

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#22303]
## Description 
There is a console warning in the `Confirm Transaction` panel for a map needing a unique key.

![Screen Shot 2022-04-14 at 9 20 54 AM](https://user-images.githubusercontent.com/40611140/163421953-c3bef0ce-302c-43c0-b272-3f023379400a.png)

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.39.101 Chromium: 101.0.4951.64 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>d1daa9897e1bc1d507d6be8f2346e377e5505905-refs/branch-heads/4951@{#1208}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22616.1)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified no console warning for confirm transaction via panel</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/168280022-5aabc97b-0533-4047-ba65-fb6e99e0020d.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/168282857-659f52a4-6592-4439-b373-814a9fa94509.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/168282827-a6b673b0-562f-4679-9281-916559cb20a1.png>
      </td>
   </tr>
</table>
