### ISSUE TITLE
[Feature] Add Mailvelope Extension

### ISSUE THREAD

**Issue by asdfghjz** [brave/brave-browser#2230]
**Feature**: Install [Mailvelope](https://www.mailvelope.com/) preferably by default.
**Why**? Mailvelope is a PGP/GPG client for your web browser. PGP/GPG is a tool utilized to encrypt emails. More Info: https://www.mailvelope.com/en/help#how_it_works
**How**? Mailvelope already has a free software [Chrome extension](https://github.com/mailvelope/mailvelope). It could also sync with the default password manager, making key management easier.

**Comment by srirambv** [comment]
There won't be any extensions bundled by default. Users can always download the extension from CWS as its at user discretion as to what extension they want to use and won't be forced upon

**Comment by asdfghjz** [comment]
@srirambv I think my issue may have been confusing. I meant to add it in the same way you add HTTPS-everywhere by default.You don't, you add its functionality.

**Comment by srirambv** [comment]
cc: @bbondy @diracdeltas @rebron for adding this
