### ISSUE TITLE
Amount you entered for asset in Swap will keep changing market price and result in error

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#22308]
## Description 
When entering an amount for an asset on the swap screen, it will proceed to count the value and then display an error

## Steps to reproduce 

   1. Using quick action, select Swap
   2. Enter an amount for the assets
   3. 

## Actual result 
The amount changes

https://user-images.githubusercontent.com/17885425/163455566-b679b3c6-bbf9-4fe5-a6c2-12f325f87109.mp4

## Expected result
The amount you entered should remain

## Issue reproduces how often 
Easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): `Samsung Galaxy S21`
   - Android version: 12
   
## Brave version
`1.38.93, Chromium 100.0.4896.88`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
Above requires `1.38.99` or higher for `1.38.x` verification.

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.38.108 x64 build
- Verified steps from issue description
- Verified Swap value doesn't auto-update constantly
- Verified with multiple Swap To tokens
---------- 
Verification passed on Samsung Tab A with Android 10 running 1.38.108 x64 build
- Verified steps from issue description
- Verified Swap value doesn't auto-update constantly
- Verified with multiple Swap To tokens
