### ISSUE TITLE
npm audit failing due to 'async' in wdp

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#22337]
https://github.com/advisories/GHSA-fwr7-v2mv-hh25

**Comment by kjozwiak** [comment]
This was added into the `1.37.x` branch but moving it into `1.38.x` as I don't think we'll have another `1.37.x` release. However, if we do end up getting a `C100` bump, we'll move this back into the `1.37.x` milestone that will be created at that point.
