### ISSUE TITLE
Getting less BAT since last two months

### ISSUE THREAD

**Issue by newuser-web** [brave/brave-browser#22334]
## Description 
 It was showing I'll be getting 8.357 BAT but I received 8.250 BAT. 

## Steps to reproduce 

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by newuser-web** [comment]
![Screenshot_2022-04-15-00-24-50-13_e4424258c8b8649f6e67d283a50a2cbc](https://user-images.githubusercontent.com/67158882/163517627-1c503c81-1c7b-407e-be11-8f6fbcda2291.jpg)
![Screenshot_2022-04-02-07-09-38-06_e4424258c8b8649f6e67d283a50a2cbc](https://user-images.githubusercontent.com/67158882/163517716-06b1c3c9-1348-4478-9842-422e76ede963.jpg)

**Comment by newuser-web** [comment]
![IMG_20220415_094830](https://user-images.githubusercontent.com/67158882/163517886-4377a93d-a9f7-497d-8c2c-2012fdc694b9.jpg)
![IMG_20220415_094816](https://user-images.githubusercontent.com/67158882/163517890-941790f9-28d6-4120-aa13-7c77ac14e36f.jpg)

**Comment by newuser-web** [comment]
@Miyayes @jonathansampson @tmancey 
Please see.

**Comment by tmancey** [comment]
@newuser-web can you please report this in our forums/community so that our support teams can help. Thank you, Terry
