### ISSUE TITLE
Refactor Brave Ads file access

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#22340]

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.40.87 Chromium: 102.0.5005.78  (Official Build) (64-bit)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | Ubuntu 18.04 LTS

Verified in https://github.com/brave/internal/issues/877
