### ISSUE TITLE
Brave Talk - share a tab (during a call)

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#22349]
## Description 
When using Brave Talk (talk.brave.com), users in a meeting should be able to share an open Brave tab.

We could detect that a person is in a call and then show an extra context menu item when doing right click on a tab. There could be a new entry `Share tab`.

#### UX (added by @petemill based on ongoing work by @fallaciousreasoning and feedback from design)
- API exposed to talk.brave.com surrounding frame which is called when a call starts (`brave.beginAdvertiseShareDisplayMedia`)
- Button exposed on all active tabs with tooltip "Share contents of this Tab to current Brave Talk call"
- When button is clicked a confirmation dialog is shown (via `chrome::ShowConfirmBubble`)
  - Title: `"Share this tab?"
  - Message: `"The contents of this tab will be shared with your active Brave Talk call"`
- If the user clicks "Accept" then the Tab's device Id is sent as a callback to the `beginAdvertiseShareDisplayMedia` API call.
- The talk.brave.com surrounding frame then performs a postMessage to the 8x8 frame which then calls `window.navigator.mediaDevices.getUserMedia` and passes the deviceId.
- If the Tab is currently being shared, then another button shows up which the user can click to "Stop sharing this Tab"

**Comment by mrose17** [comment]
@mrose17 is intersted in following this issue!

**Comment by bsclifton** [comment]
In GDrive, search for `Brave Talk "Push a Tab to Stream" in Brave Browser` for more info

**Comment by fallaciousreasoning** [comment]
I've had a talk to @petemill and I'm working on this at the moment

**Comment by bsclifton** [comment]
Closing as `wontfix` for now
