### ISSUE TITLE
Remove sign in message on person profile icon

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#2234]
## Description 

There's been a lot of users asking for sigin details on the profile icon. This should be removed so that it avoids confusion for the user
https://community.brave.com/t/how-do-i-log-in-to-brave/38219
https://community.brave.com/t/how-to-sign-in-to-brave-browser/36571/
https://community.brave.com/t/signing-into-brave-browser/36045/
https://community.brave.com/t/how-to-sign-in-to-brave-browser/36571/
https://community.brave.com/t/sign-in-on-brave-browser/36094/

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/49025310-56ad9a00-f1c1-11e8-832b-b93f4811d770.png)

## Expected result:
Nothing should say sign in and not allow you to sign in

## Brave version (brave://version info)

All

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @bbondy @rebron to prioritize the issue

**Comment by srirambv** [comment]
Verification passed on 
![screenshot from 2018-12-11 22-51-38](https://user-images.githubusercontent.com/17010094/49817863-60292b80-fd97-11e8-968d-971f93e570c6.png)

**Comment by tomlowenthal** [comment]
I'm still seeing the sync/sign-in notice on dev. Here, I have a more than one profile.

<img width="299" alt="screen shot 2018-12-11 at 11 56 31 am" src="https://user-images.githubusercontent.com/639937/49826550-021b2a80-fd3c-11e8-951e-d13d0773d1d4.png">

Brave | 0.59.2 Chromium: 71.0.3578.80 (Official Build) dev (64-bit)
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

**Comment by mkarolin** [comment]
@tomlowenthal, the fix hasn't made it into a dev build yet. 0.59.2 was built on Dec. 4. The fix was checked in on Dec. 6.
