### ISSUE TITLE
Enable Solana feature flag by default on Desktop

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#22348]
Enable the Solana feature flag by default on Desktop, current Solana feature includes the ability to create Solana accounts, get balances, transfer SOL, transfer SPL tokens, and manage visible user assets on Solana networks.

UI issues for this feature:
Add Solana accounts: https://github.com/brave/brave-browser/issues/21054  
Transfer SOL: https://github.com/brave/brave-browser/issues/21891  
Transfer SPL tokens: https://github.com/brave/brave-browser/issues/22039  
Display Solana transactions: https://github.com/brave/brave-browser/issues/21892 
Display Warning for Associated Token Account Creation: https://github.com/brave/brave-browser/issues/22260

Test Plan:
Check Solana feature flag is enabled by default on Desktop browsers, and disabled by default on Andriod.
For actual feature testing, please refer to those UI issues listed above.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.39.109 Chromium: 102.0.5005.50 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>f6e2cf8f59ec714bdcff8499991d55898875f287-refs/branch-heads/5005@{#648}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22621.1)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from issue description</li>
         <li>Verified Solana network is shown in network list</li>
         <li>Verified Solana is listed under Add account </li>
         <li>Verified Solana is listed under Import Account</li>
         <li>Verified all UI related sub tasks work as expected</li>
        </ul>
      </td>
   </tr>
</table>
