### ISSUE TITLE
Update webpack to v5 (or later)

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#22351]
Webpack 4 is now becoming quite legacy and 5 is pretty mature, offering more configuration and some potential performance benefits.

Actions:
- ...
- Remove workaround introduced in https://github.com/brave/brave-core/pull/13021

**Comment by mihaiplesa** [comment]
This is biting us hard now. Anything we can do to upgrade webpack?

https://github.com/nodejs/node/issues/40455
https://github.com/storybookjs/storybook/issues/19692

```
[2022-11-09T09:29:03.750Z] <s> [webpack.Progress] 10% building 1/4 modules 3 active /Users/jenkins/jenkins/workspace/pr-brave-browser-fix-compiledb-patch-macos/src/brave/node_modules/babel-loader/lib/index.js??ref--4-0!/Users/jenkins/jenkins/workspace/pr-brave-browser-fix-compiledb-patch-macos/src/brave/.storybook/preview.js-generated-config-entry.js

[2022-11-09T09:29:04.067Z] node:internal/crypto/hash:71

[2022-11-09T09:29:04.067Z]   this[kHandle] = new _Hash(algorithm, xofLen);

[2022-11-09T09:29:04.067Z]                   ^

[2022-11-09T09:29:04.067Z] 

[2022-11-09T09:29:04.067Z] Error: error:0308010C:digital envelope routines::unsupported

[2022-11-09T09:29:04.067Z]     at new Hash (node:internal/crypto/hash:71:19)

[2022-11-09T09:29:04.067Z]     at Object.createHash (node:crypto:133:10)

[2022-11-09T09:29:04.067Z]     at module.exports (/Users/jenkins/jenkins/workspace/pr-brave-browser-fix-compiledb-patch-macos/src/brave/node_modules/webpack/lib/util/createHash.js:135:53)

[2022-11-09T09:29:04.067Z]     at NormalModule._initBuildHash (/Users/jenkins/jenkins/workspace/pr-brave-browser-fix-compiledb-patch-macos/src/brave/node_modules/webpack/lib/NormalModule.js:417:16)

[2022-11-09T09:29:04.068Z]     at handleParseError (/Users/jenkins/jenkins/workspace/pr-brave-browser-fix-compiledb-patch-macos/src/brave/node_modules/webpack/lib/NormalModule.js:471:10)

[2022-11-09T09:29:04.068Z]     at /Users/jenkins/jenkins/workspace/pr-brave-browser-fix-compiledb-patch-macos/src/brave/node_modules/webpack/lib/NormalModule.js:503:5

[2022-11-09T09:29:04.068Z]     at /Users/jenkins/jenkins/workspace/pr-brave-browser-fix-compiledb-patch-macos/src/brave/node_modules/webpack/lib/NormalModule.js:358:12

[2022-11-09T09:29:04.068Z]     at /Users/jenkins/jenkins/workspace/pr-brave-browser-fix-compiledb-patch-macos/src/brave/node_modules/loader-runner/lib/LoaderRunner.js:373:3

[2022-11-09T09:29:04.068Z]     at iterateNormalLoaders (/Users/jenkins/jenkins/workspace/pr-brave-browser-fix-compiledb-patch-macos/src/brave/node_modules/loader-runner/lib/LoaderRunner.js:214:10)

[2022-11-09T09:29:04.069Z]     at iterateNormalLoaders (/Users/jenkins/jenkins/workspace/pr-brave-browser-fix-compiledb-patch-macos/src/brave/node_modules/loader-runner/lib/LoaderRunner.js:221:10)

[2022-11-09T09:29:04.069Z]     at /Users/jenkins/jenkins/workspace/pr-brave-browser-fix-compiledb-patch-macos/src/brave/node_modules/loader-runner/lib/LoaderRunner.js:236:3

[2022-11-09T09:29:04.069Z]     at context.callback (/Users/jenkins/jenkins/workspace/pr-brave-browser-fix-compiledb-patch-macos/src/brave/node_modules/loader-runner/lib/LoaderRunner.js:111:13)

[2022-11-09T09:29:04.069Z]     at /Users/jenkins/jenkins/workspace/pr-brave-browser-fix-compiledb-patch-macos/src/brave/node_modules/babel-loader/lib/index.js:59:71 {

[2022-11-09T09:29:04.069Z]   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],

[2022-11-09T09:29:04.069Z]   library: 'digital envelope routines',

[2022-11-09T09:29:04.069Z]   reason: 'unsupported',

[2022-11-09T09:29:04.069Z]   code: 'ERR_OSSL_EVP_UNSUPPORTED'

[2022-11-09T09:29:04.069Z] }

[2022-11-09T09:29:04.069Z] 

[2022-11-09T09:29:04.069Z] Node.js v18.12.1
```

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.63.24 Chromium: 120.0.6099.71 (Official Build) nightly (64-bit)
-- | --
Revision | 8858c508f9a33d9cb69c2b3f2da81a52a15040f6
OS | Windows 10 Version 22H2 (Build 19045.3758)
```

**Comment by kjozwiak** [comment]
Removing the `QA Pass` label as the above needs to be re-verified/checked on `1.62.x` now that it was uplifted via https://github.com/brave/brave-core/pull/21380. Used https://github.com/brave/brave-browser/issues/22351#issuecomment-1845895290 as the verification needed for uplift 👍

**Comment by kjozwiak** [comment]
The above requires `1.62.113` or higher for `1.62.x` verification 👍

**Comment by btlechowski** [comment]
Verified with

Brave | 1.62.122 Chromium: 120.0.6099.144 (Official Build) beta (64-bit)
-- | --
Revision | cfddebe77d394064c472fda64afcd9fbed34ceb4
OS | Linux


Verified using https://github.com/brave/brave-browser/issues/22351#issuecomment-1845895290

## WebTorrent

`torrent` | `magnet`
---------|------------
![image](https://github.com/brave/brave-browser/assets/34715963/da0977d9-46c2-4d1d-97bd-4378c9585fda)|![image](https://github.com/brave/brave-browser/assets/34715963/37a94723-115f-41a0-9a2a-03ff1f06ffc9)



## New-tab page

`Sponsored Image` | regular tab/customize dialog
---------------------|-------------
![image](https://github.com/brave/brave-browser/assets/34715963/b2defd6c-eacd-40c3-8d35-12f6978980a3)|![image](https://github.com/brave/brave-browser/assets/34715963/66723a3a-9eb5-405f-82b8-ce4397693b30)


## Brave Rewards

`logged out` | `custodian-loggedout`
--------------|-------------------------
![image](https://github.com/brave/brave-browser/assets/34715963/85c53a7d-d4a6-4b91-9bf5-83900fa1d3c3)|![image](https://github.com/brave/brave-browser/assets/34715963/e955e260-7f63-4b91-b6c7-586eaeb77936)



Encountered:
* https://github.com/brave/brave-browser/issues/34775

## Brave Wallet


![image](https://github.com/brave/brave-browser/assets/34715963/2f836744-b01f-458a-ad35-3331f15b12e9)|![image](https://github.com/brave/brave-browser/assets/34715963/4e8de090-b669-4f6c-b285-f1513ef9a15e)|![image](https://github.com/brave/brave-browser/assets/34715963/82ba1228-af63-4ac9-b8b6-44ae8f1e8239)|![image](https://github.com/brave/brave-browser/assets/34715963/cfa880b8-e4bc-41f4-ab4b-596eece12d0c)|![image](https://github.com/brave/brave-browser/assets/34715963/f8a45db0-e42f-483d-a6e3-dfc173cc9724)
--|--|--|--|--




## Brave Shields

`Shields up`, collapsed | `Shields up`, expanded | `Shields down`
-------------|-----------------|--------------
![image](https://github.com/brave/brave-browser/assets/34715963/1b0f575b-f350-4c3a-9235-d2257b3b7ef7)|![image](https://github.com/brave/brave-browser/assets/34715963/30a47dde-89d0-4604-8dd1-cdfe4ea8747b)|![image](https://github.com/brave/brave-browser/assets/34715963/e0304806-ebe8-4133-97ab-11f6df412f15)



## `Leo` AI chat

`onboarding` | `defaults` | `summarize` | `questions` | `settings overlay`
---------------|-----------|---------------|-------------|--------------------
![image](https://github.com/brave/brave-browser/assets/34715963/c973e9f3-5db7-4072-95fe-da4aa3fca7f4)|![image](https://github.com/brave/brave-browser/assets/34715963/0c194684-1099-4671-8106-2024c4c87e78)|![image](https://github.com/brave/brave-browser/assets/34715963/41a5abbb-441d-41bb-88c2-1d58dd0b90de)|![image](https://github.com/brave/brave-browser/assets/34715963/c48aef99-2447-4ad8-98c0-23e4ac0d4377)|![image](https://github.com/brave/brave-browser/assets/34715963/f1ee41b2-79e4-4eb9-ab99-fd6ff3568219)




## Shortcuts

example | example | example 
----------|-----------|----------
![image](https://github.com/brave/brave-browser/assets/34715963/2d712d9b-2b68-461c-9dca-62f6f4baf6de)|![image](https://github.com/brave/brave-browser/assets/34715963/8a541193-4e3c-4a67-8d70-e5652e9a3b4f)|![image](https://github.com/brave/brave-browser/assets/34715963/0f9e9915-8d0d-4825-951f-be5efc37f6c4)

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.62.123 Chromium: 120.0.6099.144 (Official Build) beta (x86_64)
-- | --
Revision | 680382264ff6ae655b3bba25e80567452f38fbee
OS | macOS Version 13.6.3 (Build 22G436)
```

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.62.121`

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.62.128 Chromium: 120.0.6099.144 (Official Build) beta (64-bit)
-- | --
Revision | 41f5844c06c7db1017f39b5b6dc9ba81a6b1b9d6
OS | Windows 11 Version 22H2 (Build 22621.2861)
```
### WebTorrent

`torrent` | `magnet`
---------|------------
<img width="957" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/fa151c8c-2cb3-48f7-8540-b499e997b6da">|<img width="948" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/e99c9289-52a5-42af-86ad-3e83473b0822">

### New-tab page

`Sponsored Image` | regular tab/customize dialog
---------------------|-------------
<img width="959" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/544a644c-df91-4ba4-abc0-fc1977eb6e82">|<img width="959" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/a5a63e10-8650-4bd8-af7c-3c95afb91961">

## Brave Shields

`Shields up`, collapsed | `Shields up`, expanded | `Shields down`
-------------|-----------------|--------------
<img width="954" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/729378cf-b298-47d5-aef8-4970ff4e0e3a">|<img width="961" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/aaf7082a-4e75-4f31-a0c4-0b459bee3e4d">|<img width="950" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/6c832890-534f-41ef-8bd4-fe26a0cc47fc">


## `Leo` AI chat

`onboarding` | `defaults` | `summarize` | `questions` | `settings overlay`
---------------|-----------|---------------|-------------|--------------------
<img width="957" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/b0cb3160-58dd-4f4d-b536-73dce24f98d9">|<img width="952" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/e03b4264-3955-4b6f-a466-937174071c92">|<img width="958" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/e18acd22-b96c-4713-a95a-c5b166820a7a">|<img width="951" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/875b6dfc-95d7-4e78-ba1f-3a2e69c76f61">

**Comment by Uni-verse** [comment]
In Progress on Samsung Galaxy Tab S7 using version: 

```
Brave	1.62.147 Chromium: 120.0.6099.234 (Official Build) (32-bit) 
Revision	3b25c3743150a54485dea24f0ceb1e69d6db51bc
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

Test Plan: https://github.com/brave/brave-browser/issues/22351#issuecomment-1871734450

<details><summary>Web Torrent</summary>

<img width="733" alt="Screenshot 2024-01-19 at 4 21 35 PM" src="https://github.com/brave/brave-browser/assets/17885425/776c930c-0699-4ace-8d69-ce5a41ca7aad">

</details>

<details><summary>New Tab Page</summary>

Example | Example
-|-
<img width="736" alt="Screenshot 2024-01-19 at 3 01 09 PM" src="https://github.com/brave/brave-browser/assets/17885425/573302f9-9d34-4b9f-a4fe-16964af1163f"> | <img width="736" alt="Screenshot 2024-01-19 at 3 01 24 PM" src="https://github.com/brave/brave-browser/assets/17885425/7070d4dc-2696-4d50-abdb-6bf41b2cd705">

</details>

<details><summary>Brave Rewards</summary>

<img width="736" alt="Screenshot 2024-01-19 at 3 30 47 PM" src="https://github.com/brave/brave-browser/assets/17885425/b44a6ad9-1691-4501-ac09-670e930a57bc">

</details>

<details><summary>Brave Wallet</summary>

Example | Example | Example
-|-|-
<img width="736" alt="Screenshot 2024-01-19 at 3 40 55 PM" src="https://github.com/brave/brave-browser/assets/17885425/c19209b0-8247-482c-82ee-4b107d55634e"> | <img width="736" alt="Screenshot 2024-01-19 at 3 41 11 PM" src="https://github.com/brave/brave-browser/assets/17885425/2269a626-3d02-4997-a340-d6d9b0b32510"> | <img width="736" alt="Screenshot 2024-01-19 at 3 41 21 PM" src="https://github.com/brave/brave-browser/assets/17885425/7f77a47f-7150-4991-98c1-9c2cd843d379">

</details>

<details><summary>Brave Shields</summary>

Example | Example | Example
-|-|-
<img width="735" alt="Screenshot 2024-01-19 at 3 42 25 PM" src="https://github.com/brave/brave-browser/assets/17885425/0d784f29-bf57-452b-87fb-a05ce8a958be"> | <img width="735" alt="Screenshot 2024-01-19 at 3 42 28 PM" src="https://github.com/brave/brave-browser/assets/17885425/bf4ba821-47d0-4ff4-82e2-9138cd99e87d"> | <img width="735" alt="Screenshot 2024-01-19 at 3 42 31 PM" src="https://github.com/brave/brave-browser/assets/17885425/517e8cbb-b918-4b44-a253-d5e7fb511b22">

</details>

<details><summary>Leo</summary>

Example | Example | Example | Example
-|-|-|-
<img width="735" alt="Screenshot 2024-01-19 at 3 49 57 PM" src="https://github.com/brave/brave-browser/assets/17885425/2968623d-391c-4641-9a3d-3d4db4a375aa"> | <img width="735" alt="Screenshot 2024-01-19 at 3 50 08 PM" src="https://github.com/brave/brave-browser/assets/17885425/3be25ebd-95a3-4b72-9d6f-c486035c6df4"> | <img width="735" alt="Screenshot 2024-01-19 at 3 50 53 PM" src="https://github.com/brave/brave-browser/assets/17885425/ddca8057-8896-4f32-8d5b-8188ddb00066"> | <img width="735" alt="Screenshot 2024-01-19 at 3 51 04 PM" src="https://github.com/brave/brave-browser/assets/17885425/fae04e46-5d90-4924-8d38-8b87e5d2fa5e">

</details>
