### ISSUE TITLE
no "back" UI within network selection screen

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#22357]
## Description 

Similar to https://github.com/brave/brave-browser/issues/22345, there's no obvious way from a UI standpoint that lets a user go back  to the previous screen within the network selection window. This only affects `1.38.x` & `1.39.x` as this seems like a new design compared to what we have in `1.37.x`.

Either way, we can't assume that users will know all the Android shortcuts and know that they can swipe left/right.

## Steps to reproduce 

   1. launch Brave and setup a Brave Wallet
   2. once you're on the main page/view on Brave Wallet, tap on the network selection to change your current visible network

## Actual result 

As you can see, there's no obvious UI that lets you go back to the previous screen. We can't assume users know Android shortcuts.

**`Example`** | **`Example`**
---------------|---------------
![Screenshot_20220413-002045](https://user-images.githubusercontent.com/2602313/163661003-d4148c04-fb39-4c39-bb2d-e37ea1f29f29.png) | ![Screenshot_20220413-002053](https://user-images.githubusercontent.com/2602313/163661006-0cac85ae-5ee8-4844-bd20-a4e42e2ac4ef.png)

## Expected result

There should be some obvious UI within network selection screen that lets you go back to the previous screen. We can't assume all our users know Android shortcuts re: swiping from side to side.

## Issue reproduces how often 

100% reproducible when using the STR/Cases outlined above.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `No` (different selection menu)
- Can you reproduce this issue with the current Play Store Beta version?  `Yes`
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Pixel 6` (Phone)
   - Android version: `Android 12`
   
## Brave version

* `1.38.96 Chromium: 100.0.4896.88` - **Reproduced**
* `1.39.63 Chromium: 100.0.4896.127` - **Reproduced**

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by simoarpe** [comment]
<img src="https://github.com/brave/brave-browser/assets/3308503/eb49242c-72ca-4931-881e-2868787ed34c" width="500" />
This issue has now been fixed as we display an X to close the network selection screen.
