### ISSUE TITLE
Brave News position not retained when switching tabs

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#22356]
## Description 

So this is basically a follow up to https://github.com/brave/brave-browser/issues/20580 which hasn't been fixed 100% by https://github.com/brave/brave-core/pull/12908. We still have some issues within Brave News where switching to a NTP tab doesn't keep the correct position within Brave News and either jumps back to the top or moves the feed in either direction so you're not in the same position as before. Sometimes it just moves a bit so technically it's still in the same area but still not a smooth experience.

A good example is iOS, you'll notice that the feed never jumps around when switching tabs and then returning to the tab with the feed. It always says in the same position making it a much smoother experience.

## Steps to reproduce 

**`Test Case #1`**

   1. ensure that you have Brave News enabled
   2. open a NTP and scroll through the feed so the first visible card is right near the top of the Brave News settings
   3. press the the tab button overview button and then select the same tab
   4. notice that you've jumped all the way back to the top rather than being in the same position as before

**`Test Case #2`**

   1. ensure that you have Brave News enabled
   2. open a NTP and scroll through the feed and randomly pick a spot/card to stop on
   3. press the the tab button overview button and then select the same tab
   4. you'll notice that sometimes the position won't be in the same spot as before

This basically happens often whenever you come back to a tab that you've used for Brave News and expect to be in a certain position within the feed but then notice it's not the same position as before.

## Actual result 

https://user-images.githubusercontent.com/2602313/163659741-c85f4876-b3aa-4634-9dfa-2aa47c13130b.mp4

## Expected result

Quick example of the smooth experience on iOS:

https://user-images.githubusercontent.com/2602313/163659806-e0d36df6-9db9-4f6e-8ce0-ae02f4453ccb.mp4

## Issue reproduces how often 

100% reproducible using the STR/Cases outlined above.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `Yes`
- Can you reproduce this issue with the current Play Store Beta version? `Yes` 
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Pixel 6` (Phone)
   - Android version: `Android 12`
   
## Brave version

```
1.39.63 Chromium: 100.0.4896.127
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

### Additional information

CCing @bsclifton @alexsafe @timchilds @anthonypkeane @srirambv @Uni-verse

**Comment by timchilds** [comment]
@kjozwiak I could not reproduce the jumping back to top but it does move up/down in the feed on my device (Galaxy A51 / Android 11). Unsure if this is related, but in the tab overview it seems to retain the tab preview of the first time you enter the tab overview screen. Regardless of whether you have moved away from what that tab preview is showing.

e.g. in the video below, the tab preview stays at the "U.S. Stocks Waver as Treasury..." news item.

Uploading Screen_Recording_20220418-092909_Brave - Nightly.mp4…

**Comment by Uni-verse** [comment]
Verified using version `1.38.118, Chromium 101.0.4951.67` on `Samsung Galaxy S21` running `Android 12`

-Confirmed i was not able to reproduce test case #1 & #2 using the STR from https://github.com/brave/brave-browser/issues/22356#issue-1205997563

- `Test Case #1` (position around first card)- `PASS`
- `Test Case #2` (random position in news feed) - `PASS`

https://user-images.githubusercontent.com/17885425/168665736-03f2fe21-cf55-462f-a5ca-5012c42ad580.mp4

**Comment by Uni-verse** [comment]
Verification in Progress using version 1.38.118, Chromium 101.0.4951.67 on Samsung Galaxy Tab S7 running Android 12
