### ISSUE TITLE
Inactive window's shields icon is not updated properly

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#22359]
## Description 

Inactive window's shields icon is not updated properly

## Steps to Reproduce

   1. Open two windows and load www.brave.com both
   2. Both windows' active tab is for www.brave.com
   3. Shields down in one window

## Actual result:

The other window's shields icon has still enabled state

## Expected result:
The other window's shields icon should also have disabled state

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
@simonhong @rebron do we want to uplift this, given I verified it on `nightly`?  Or too risky this late, for `1.38.x`?

**Comment by simonhong** [comment]
IMO, it's late for `1.38.x`. Although the fix for this is not risky, this bug is not critical and not reproducible frequently.
and problem is gone when active tab is changed.
I think uplifting to `1.39.x` seems fine.

**Comment by stephendonner** [comment]
Verified `PASSED` using the steps to reproduce as filed.  First reproduced the issue with `1.39.76`, easily.

Brave | 1.40.4 Chromium: 101.0.4951.41 (Official Build) nightly (x86_64)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | macOS Version 12.4 (Build 21F5058e)


* Confirmed toggling Shields `DOWN`/`UP` via the doorhanger panel in window A (`brave.com`) propagated icon and `DOWN`/`UP` state to window B (`brave.com`)
* Confirmed vice-versa of above -- toggling state
* Confirmed no new crashes
