### ISSUE TITLE
Block scripts heading label should read Blocked scripts

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#22364]
## Steps to Reproduce

1. install `1.39.65`
2. launch Brave
3. load `cnn.com`
4. click on the Shields icon in the URL bar
5. click `Advanced controls`
6. click on the blurple number to the right of `Block scripts`

## Actual result:

`10 Block scripts`

<img width="975" alt="Screen Shot 2022-04-17 at 2 46 07 AM" src="https://user-images.githubusercontent.com/387249/163709501-604eeaa0-1af5-4a73-b42a-0dbd9cd11dca.png">

## Expected result:

`10 Blocked scripts`

<img width="895" alt="Screen Shot 2022-04-17 at 2 44 09 AM" src="https://user-images.githubusercontent.com/387249/163709500-53565e20-35e3-4d95-bdf3-2cec85a1994c.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.39.65 Chromium: 101.0.4951.34 (Official Build) nightly (x86_64)
-- | --
Revision | 8f93af5d759634c5256b65997dedd138ed60992f-refs/branch-heads/4951@{#710}
OS | macOS Version 11.6.5 (Build 20G527)

cc @nullhook @rmcfadden3 @jenn-rhim @MadhaviSeelam @GeetaSarvadnya

**Comment by rebron** [comment]
Closed with https://github.com/brave/brave-core/pull/13209

**Comment by stephendonner** [comment]
## Verified `PASSED` using

Brave | 1.41.40 Chromium: 102.0.5005.78 (Official Build) nightly (x86_64)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | macOS Version 12.5 (Build 21G5037d)

Followed my original steps to reproduce.

### Confirmed it now reads `10 Blocked scripts`

example | example
---------|---------
<img width="1172" alt="Screen Shot 2022-06-06 at 5 35 27 PM" src="https://user-images.githubusercontent.com/387249/172271576-0694d44b-a5b8-4507-bded-0eb10630f87c.png"> | <img width="1172" alt="Screen Shot 2022-06-06 at 5 35 31 PM" src="https://user-images.githubusercontent.com/387249/172271581-586f6543-6be3-4afd-8075-d60005d32f85.png">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.41.65 Chromium: 103.0.5060.42 (Official Build) nightly (64-bit)
-- | --
Revision | de0d840bf9439c31bd86bf74f065c31fdf9b208d-refs/branch-heads/5060@{#667}
OS | Windows 11 Version 21H2 (Build 22000.739)
```
Followed original steps and reproduced in `1.39.122 `

### Confirmed it now reads `10 Blocked scripts`

1.39.122|1.41.65
---|---
<img width="944" alt="image" src="https://user-images.githubusercontent.com/98358127/173959639-b50042e3-b62d-44a3-8abb-0252cf743b6b.png">|<img width="946" alt="image" src="https://user-images.githubusercontent.com/98358127/173959632-5ab88127-4ed7-4533-8012-77d47f230420.png">

**Comment by rmcfadden3** [comment]
Will defer to @stephendonner on this one, but now that I see it in context, I wonder if this should actually read "XX scripts blocked"

(note no capitalization on the "s" or "b" and also ordering of words reversed)

**Comment by stephendonner** [comment]
> Will defer to @stephendonner on this one, but now that I see it in context, I wonder if this should actually read "XX scripts blocked"
> 
> (note no capitalization on the "s" or "b" and also ordering of words reversed)

Sounds good to me; I'll file a followup issue and cross-reference here, for posterity 👍
