### ISSUE TITLE
Shields shouldn't be available for HTTP 204 URLs

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#22361]
## Description 

Shields shouldn't be available for HTTP 204 URLs

## Steps to Reproduce

1. install `1.39.65`
2. launch Brave
3. load `https://superuser.com/questions/1213116/are-there-well-known-http-only-sites`
4. shift+click on the `http://google.com/generate_204` link
5. `http://google.com/generate_204` displays in the URL bar of a new window, but doesn't load
6. click on the Shields icon

notice the up/down toggle state doesn't work (nor do counts, etc.)

## Actual result:

Shields `DOWN` | Shields `UP`
---------|---------
<img width="790" alt="Screen Shot 2022-04-17 at 12 17 49 AM" src="https://user-images.githubusercontent.com/387249/163704926-018f36ef-28a9-4c11-817d-fd3e60f75db7.png"> | <img width="790" alt="Screen Shot 2022-04-17 at 12 17 56 AM" src="https://user-images.githubusercontent.com/387249/163704928-c030da7e-e42c-430c-9d3d-06827c9a8cce.png">

## Expected result:

The Shields icon should probably be disabled and clicking on it should do nothing.

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.39.65 Chromium: 101.0.4951.34 (Official Build) nightly (x86_64)
-- | --
Revision | 8f93af5d759634c5256b65997dedd138ed60992f-refs/branch-heads/4951@{#710}
OS | macOS Version 11.6.5 (Build 20G527)

@nullhook @rebron @simonhong @bridiver @MadhaviSeelam @GeetaSarvadnya

**Comment by bridiver** [comment]
What is the reasoning for not having shields active for certain types of responses? I don't see any reason why we would disable it for something like this, I think it should only be disabled for non http/https.

**Comment by stephendonner** [comment]
> What is the reasoning for not having shields active for certain types of responses? I don't see any reason why we would disable it for something like this, I think it should only be disabled for non http/https.

I defaulted to parity with `1.37.x`, which doesn't have Shields enabled in this case, just FYI - that might be a bug itself?

**Comment by bridiver** [comment]
> I defaulted to parity with `1.37.x`, which doesn't have Shields enabled in this case, just FYI - that might be a bug itself?

I just really can't see a reason why we would do that

**Comment by rebron** [comment]
Closing as wontfix per last comment.
