### ISSUE TITLE
Make the dark mode more of a neutral color

### ISSUE THREAD

**Issue by D0J0P** [brave/brave-browser#22368]
## Description 

The dark mode in Brave is a bit on the blue/slate side. I think it would be better if it was a neutral color, kind of like the Android version has. Most browser's dark mode uses neutral colors as well, e.g. Firefox

## Steps to Reproduce

   1. Open Brave
   2. Turn on Dark Mode
   3. Look at the tabs and address bar

## Actual result:

Brave:
![Screenshot from 2022-04-17 16 55 22](https://user-images.githubusercontent.com/19495660/163731814-fb68cb8b-9710-412e-bf5b-1344dc064c97.png)
Vivaldi:
![Screenshot from 2022-04-17 16 56 15](https://user-images.githubusercontent.com/19495660/163731815-d3a1cb1f-5cd1-43ac-8594-5a971282fd94.png)
Firefox:
![Screenshot from 2022-04-17 16 57 14](https://user-images.githubusercontent.com/19495660/163731816-da87dc87-9ec8-48a5-8503-ec252fb67d8e.png)
Gnome Web/Epiphany:
![Screenshot from 2022-04-17 16 58 30](https://user-images.githubusercontent.com/19495660/163731817-d1679241-ef4f-4155-8d82-ea6c90708683.png)

## Expected result:
That Brave's dark mode would use a neutral color like other browsers do.

## Brave version (brave://version info)

1.37.116 Chromium: 100.0.4896.127 (Official Build) (64-bit) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

I know Vivaldi's dark mode, a theme called Issuna, has the option to use the Operating System theme. I think that could be why all browsers look the same in dark mode, because they are set to use the OS dark theme, which is the same neutral color.

**Comment by ErikeSu** [comment]
![image](https://user-images.githubusercontent.com/65438348/163785557-60541286-b6f2-4479-ab8b-8b6d56fd5685.png)
how about that? you can choose your theme color in "brave://settings/manageProfile"
:-)

**Comment by D0J0P** [comment]
Well whaddya know, I missed it! Thanks :)
