### ISSUE TITLE
can not install brave browser from hongkong

### ISSUE THREAD

**Issue by chengweiv5** [brave/brave-browser#22371]
## Description 

As following the [install guide](https://brave.com/linux/#release-channel-installation), but it failed with "Connection refused".

```
tsocks curl -fvsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
*   Trying 104.244.43.167:443...
* connect to 104.244.43.167 port 443 failed: Connection refused
*   Trying 2001::1f0d:5036:443...
* Immediate connect fail for 2001::1f0d:5036: Network is unreachable
* Failed to connect to brave-browser-apt-release.s3.brave.com port 443: Connection refused
* Closing connection 0
curl: (7) Failed to connect to brave-browser-apt-release.s3.brave.com port 443: Connection refused
```

The socks proxy server located in hongkong.

## Steps to Reproduce

   1. The OS is debian 11
   2. open a terminal, execute command "tsocks curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg", use a socks proxy located in hongkong

## Actual result:

```
tsocks curl -fvsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
*   Trying 104.244.43.167:443...
* connect to 104.244.43.167 port 443 failed: Connection refused
*   Trying 2001::1f0d:5036:443...
* Immediate connect fail for 2001::1f0d:5036: Network is unreachable
* Failed to connect to brave-browser-apt-release.s3.brave.com port 443: Connection refused
* Closing connection 0
curl: (7) Failed to connect to brave-browser-apt-release.s3.brave.com port 443: Connection refused
```

## Expected result:

The gpg key saved in specified location.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
NA

## Version/Channel Information:
NA

## Other Additional Information:

NA

## Miscellaneous Information:
NA

**Comment by fmarier** [comment]
That's weird, `104.244.43.167` is a Twitter IP address:
```
$ whois 104.244.43.167

#
# ARIN WHOIS data and services are subject to the Terms of Use
# available at: https://www.arin.net/resources/registry/whois/tou/
#
# If you see inaccuracies in the results, please report at
# https://www.arin.net/resources/registry/whois/inaccuracy_reporting/
#
# Copyright 1997-2022, American Registry for Internet Numbers, Ltd.
#


NetRange:       104.244.40.0 - 104.244.47.255
CIDR:           104.244.40.0/21
NetName:        TWITTER-NETWORK
NetHandle:      NET-104-244-40-0-1
Parent:         NET104 (NET-104-0-0-0-0)
NetType:        Direct Allocation
OriginAS:       AS13414
Organization:   Twitter Inc. (TWITT)
RegDate:        2014-12-08
Updated:        2020-06-28
Ref:            https://rdap.arin.net/registry/ip/104.244.40.0


OrgName:        Twitter Inc.
OrgId:          TWITT
Address:        1355 Market Street
Address:        Suite 900
City:           San Francisco
StateProv:      CA
PostalCode:     94103
Country:        US
RegDate:        2010-03-08
Updated:        2021-10-11
Ref:            https://rdap.arin.net/registry/entity/TWITT


OrgTechHandle: NETWO3685-ARIN
OrgTechName:   Network Operations
OrgTechPhone:  +1-415-222-9670 
OrgTechEmail:  noc@twitter.com
OrgTechRef:    https://rdap.arin.net/registry/entity/NETWO3685-ARIN

OrgAbuseHandle: TNA33-ARIN
OrgAbuseName:   Twitter Network Abuse
OrgAbusePhone:  +1-415-222-9670 
OrgAbuseEmail:  net-abuse@twitter.com
OrgAbuseRef:    https://rdap.arin.net/registry/entity/TNA33-ARIN

OrgTechHandle: SOUTH69-ARIN
OrgTechName:   Southern, Timothy 
OrgTechPhone:  +1-415-222-9670 
OrgTechEmail:  tsouthern@twitter.com
OrgTechRef:    https://rdap.arin.net/registry/entity/SOUTH69-ARIN

OrgNOCHandle: NETWO3685-ARIN
OrgNOCName:   Network Operations
OrgNOCPhone:  +1-415-222-9670 
OrgNOCEmail:  noc@twitter.com
OrgNOCRef:    https://rdap.arin.net/registry/entity/NETWO3685-ARIN

OrgTechHandle: FENEC5-ARIN
OrgTechName:   Fenech, William 
OrgTechPhone:  +1-415-222-9670 
OrgTechEmail:  wfenech@twitter.com
OrgTechRef:    https://rdap.arin.net/registry/entity/FENEC5-ARIN


#
# ARIN WHOIS data and services are subject to the Terms of Use
# available at: https://www.arin.net/resources/registry/whois/tou/
#
# If you see inaccuracies in the results, please report at
# https://www.arin.net/resources/registry/whois/inaccuracy_reporting/
#
# Copyright 1997-2022, American Registry for Internet Numbers, Ltd.
#
```
I'm getting a different IP for `brave-browser-apt-release.s3.brave.com`:
```
$ dig brave-browser-apt-release.s3.brave.com
brave-browser-apt-release.s3.brave.com.	3600 IN	CNAME d9owkidwx4k9e.cloudfront.net.
d9owkidwx4k9e.cloudfront.net. 3600 IN	A	65.8.66.73
d9owkidwx4k9e.cloudfront.net. 3600 IN	A	65.8.66.116
d9owkidwx4k9e.cloudfront.net. 3600 IN	A	65.8.66.123
d9owkidwx4k9e.cloudfront.net. 3600 IN	A	65.8.66.129
```

**Comment by fmarier** [comment]
One thing you could try if you already have access to the Tor daemon is to use our Onion service. This is what I have in my `/etc/apt/sources.list.d/brave-browser-release.list`:
```
deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] tor+https://brave-browser-apt-release.s3.brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/ stable main
```
Of course, if you want to go that way, you'll need to first download the [signing key](https://brave-browser-apt-release.s3.brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/brave-browser-archive-keyring.gpg) using the Tor browser, or using another browser via the Tor daemon.

**Comment by chengweiv5** [comment]
> That's weird, `104.244.43.167` is a Twitter IP address:
> 
> ```
> $ whois 104.244.43.167
> 
> #
> # ARIN WHOIS data and services are subject to the Terms of Use
> # available at: https://www.arin.net/resources/registry/whois/tou/
> #
> # If you see inaccuracies in the results, please report at
> # https://www.arin.net/resources/registry/whois/inaccuracy_reporting/
> #
> # Copyright 1997-2022, American Registry for Internet Numbers, Ltd.
> #
> 
> 
> NetRange:       104.244.40.0 - 104.244.47.255
> CIDR:           104.244.40.0/21
> NetName:        TWITTER-NETWORK
> NetHandle:      NET-104-244-40-0-1
> Parent:         NET104 (NET-104-0-0-0-0)
> NetType:        Direct Allocation
> OriginAS:       AS13414
> Organization:   Twitter Inc. (TWITT)
> RegDate:        2014-12-08
> Updated:        2020-06-28
> Ref:            https://rdap.arin.net/registry/ip/104.244.40.0
> 
> 
> OrgName:        Twitter Inc.
> OrgId:          TWITT
> Address:        1355 Market Street
> Address:        Suite 900
> City:           San Francisco
> StateProv:      CA
> PostalCode:     94103
> Country:        US
> RegDate:        2010-03-08
> Updated:        2021-10-11
> Ref:            https://rdap.arin.net/registry/entity/TWITT
> 
> 
> OrgTechHandle: NETWO3685-ARIN
> OrgTechName:   Network Operations
> OrgTechPhone:  +1-415-222-9670 
> OrgTechEmail:  noc@twitter.com
> OrgTechRef:    https://rdap.arin.net/registry/entity/NETWO3685-ARIN
> 
> OrgAbuseHandle: TNA33-ARIN
> OrgAbuseName:   Twitter Network Abuse
> OrgAbusePhone:  +1-415-222-9670 
> OrgAbuseEmail:  net-abuse@twitter.com
> OrgAbuseRef:    https://rdap.arin.net/registry/entity/TNA33-ARIN
> 
> OrgTechHandle: SOUTH69-ARIN
> OrgTechName:   Southern, Timothy 
> OrgTechPhone:  +1-415-222-9670 
> OrgTechEmail:  tsouthern@twitter.com
> OrgTechRef:    https://rdap.arin.net/registry/entity/SOUTH69-ARIN
> 
> OrgNOCHandle: NETWO3685-ARIN
> OrgNOCName:   Network Operations
> OrgNOCPhone:  +1-415-222-9670 
> OrgNOCEmail:  noc@twitter.com
> OrgNOCRef:    https://rdap.arin.net/registry/entity/NETWO3685-ARIN
> 
> OrgTechHandle: FENEC5-ARIN
> OrgTechName:   Fenech, William 
> OrgTechPhone:  +1-415-222-9670 
> OrgTechEmail:  wfenech@twitter.com
> OrgTechRef:    https://rdap.arin.net/registry/entity/FENEC5-ARIN
> 
> 
> #
> # ARIN WHOIS data and services are subject to the Terms of Use
> # available at: https://www.arin.net/resources/registry/whois/tou/
> #
> # If you see inaccuracies in the results, please report at
> # https://www.arin.net/resources/registry/whois/inaccuracy_reporting/
> #
> # Copyright 1997-2022, American Registry for Internet Numbers, Ltd.
> #
> ```
> 
> I'm getting a different IP for `brave-browser-apt-release.s3.brave.com`:
> 
> ```
> $ dig brave-browser-apt-release.s3.brave.com
> brave-browser-apt-release.s3.brave.com.	3600 IN	CNAME d9owkidwx4k9e.cloudfront.net.
> d9owkidwx4k9e.cloudfront.net. 3600 IN	A	65.8.66.73
> d9owkidwx4k9e.cloudfront.net. 3600 IN	A	65.8.66.116
> d9owkidwx4k9e.cloudfront.net. 3600 IN	A	65.8.66.123
> d9owkidwx4k9e.cloudfront.net. 3600 IN	A	65.8.66.129
> ```

Thank you @fmarier very much, this did resolve my problem, I add an entry to my `/etc/hosts` and got brave-browser installed.

Thanks again!
