### ISSUE TITLE
Enable sending tab to iOS devices

### ISSUE THREAD

**Issue by ajgraves** [brave/brave-browser#22376]
## Description 
"Send to your devices" feature does not include iOS devices

## Steps to Reproduce

   1. Browse to any page
   2. Right click and select "Send to your devices"
   3. Observe that no iOS device is listed as an option to send to

## Actual result:
No iOS devices listed as available send destinations

## Expected result:
Expected to be able to send to iOS devices

## Reproduces how often: 
Reproducible every time

## Brave version (brave://version info)
Desktop: 1.37.116 Chromium: 100.0.4896.127 (Official Build) (64-bit) 
iOS: 1.37 (22.4.6.8) BraveCore 1.37.108 (100.0.4896.46)

## Version/Channel Information:
Only tested in release version

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Unknown
- Can you reproduce this issue with the nightly channel? Unknown

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

This is likely more a feature request than a bug, but wanted to make sure it was out there. I searched github and did not see this mentioned previously but my search-fu may not be the best here.

**Comment by ajgraves** [comment]
Just adding another note, but this goes both ways, I'd love to be able to share a page from iOS to the desktop browsers as well.

**Comment by iccub** [comment]
Fixed in https://github.com/brave/brave-ios/issues/3229
This is live on iOS 1.43
