### ISSUE TITLE
[Android] Failed monthly tip toast notification in Rewards panel needs design work on Android

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#22374]
## Description 
When there is an error processing your monthly tip, you get an error notification on the panel. This notification could use some design help.

## Steps to reproduce 

   1. Be on staging w/ a custodial wallet (such as Gemini)
   2. Do a monthly tip to a connected, Uphold, or bF creator
   3. Close browser
   4. Advance device date 1 month
   5. Launch browser
   6. Monthly tips attempt to contribute
   7. Tip fails (expected per https://github.com/brave/brave-browser/issues/20090), and you get a notification

## Actual result 

![1](https://user-images.githubusercontent.com/28145373/163821314-55c807d2-7d4e-4252-adf6-debce86d920e.png)

## Expected result

notification should look more like desktop

<img width="428" alt="desktop" src="https://user-images.githubusercontent.com/28145373/163822867-1938c871-eb72-4ccf-9de5-091b96cb33c5.png">

## Issue reproduces how often 
easily when conditions are met

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? unsure
- Can you reproduce this issue with the current Play Store Beta version? yes
- Can you reproduce this issue with the current Play Store Nightly version? yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): all
   - Android version: all
   
## Brave version
1.38.93

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc @Miyayes @deeppandya

**Comment by Miyayes** [comment]
Nice catch. We should just implement the same design as we have on desktop. cc: @deeppandya

**Comment by Miyayes** [comment]
"Monthly Tip" is better text, as opposed to "Monthly Contribution". We've renamed Monthly Contributions to be Monthly Tips. cc: @deeppandya

**Comment by GeetaSarvadnya** [comment]
Encountered the issue while testing the AC with uphold custodian connected.

Device and version details:
`Android ARM version 12` running `Bravemoarmx64.apk_1.44.95`
![Screenshot_20221022_201246 (1)](https://user-images.githubusercontent.com/38657976/191892476-307001a5-a196-49d9-89a3-60b8904af918.jpg)

**Comment by Miyayes** [comment]
Use this:

![image](https://user-images.githubusercontent.com/11497541/202813845-c2b53a63-0de1-46a5-8bc8-68867a982289.png)

**Comment by stephendonner** [comment]
## Verified `PASSED` using `Brave` `1.48.141`, `Chromium` `109.0.5414.119` on a `Google Pixel XL` running `Android 9`

### Steps:

1. set `Brave Rewards` to staging env., and logged in to my `Gemini` account
2. did a monthly tip to Uphold-verified creator `laurenwags.github.io`
3. closed Brave
4. advanced device date 1 month
5. launched Brave
6. monthly tips attempted to contribute (confirmed via 
7. confirmed tip fails (expected per https://github.com/brave/brave-browser/issues/20090), and I got a toast notification



#### Confirmed I saw `Monthly tip failed` "toast" notifications (missing button text; will follow-up separately)

`Light` | `Dark`
--------|-------
![Screenshot_20230228-025508](https://user-images.githubusercontent.com/387249/215264936-eb032b5e-383a-442d-91b7-464df18d50c1.png) | ![Screenshot_20230228-025602](https://user-images.githubusercontent.com/387249/215264940-e8ec48c3-60f3-4d6f-9b1a-97acc0ee4282.png)

### Steps for the above

example | example | example | example | example | example
---------|---------|----------|---------|----------|----------
![Screenshot_20230128-025213](https://user-images.githubusercontent.com/387249/215264737-d1fd5b50-36bd-46cd-b862-a782d153e1a4.png) | ![Screenshot_20230128-025254](https://user-images.githubusercontent.com/387249/215264790-40f78422-62c4-4a53-b4b7-a6099b302838.png) | ![Screenshot_20230128-025305](https://user-images.githubusercontent.com/387249/215264791-51c62004-8821-43cc-98b5-1609fc6da6f4.png) | ![Screenshot_20230128-025310](https://user-images.githubusercontent.com/387249/215264794-addb5498-22fb-44d5-ab33-8cb567ba0643.png) | ![Screenshot_20230128-025312](https://user-images.githubusercontent.com/387249/215264795-97116dd5-53ee-4eec-a85b-b5dc7c97f408.png) | ![Screenshot_20230228-025358](https://user-images.githubusercontent.com/387249/215264828-ddeb6e08-d9a7-426f-9a44-1a808f47d3a8.png)
