### ISSUE TITLE
Rewards panel should show spinner while waiting for captcha response

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#22375]
## Description 

When the user solves a grant captcha in the Rewards panel, if the server takes a moment to respond, the user does not have an indication that the request is in progress.

## Steps to Reproduce

   1. Receive a grant
   2. Open the Rewards panel and solve the captcha

## Actual result:

After dropping the triangle at the correct location, the UI does not show any indication that the solution is being checked.

## Expected result:

The UI should show a spinner or other indicator that the solution is current being checked.

## Reproduces how often: 

Intermittent issue: only noticeable when the grant server takes a moment to respond.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 

Brave | 1.39.83 Chromium: 101.0.4951.41 (Official Build) beta (64-bit)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | Windows 11 Version 21H2 (Build 22000.613)

Test Case 2: Verified Rewards panel displayed spinner while waiting for `CAPTCHA` response

Details

- New profile
- Launch brave with using --rewards=staging=true --brave-ads-staging
- Click Skip welcome tour
- Click BAT icon in the URL bar to open onboarding modal
- Click Start using Brave Rewards to complete onboarding process
- Click Claim Tokens button in the modal
- `CAPTCHA` displayed 
- Spinner displayed while waiting for `CAPTCHA` response

![2022-04-27_17h06_20](https://user-images.githubusercontent.com/98358127/165650988-e0fb34b3-1031-466c-985f-026585f5199d.gif)

</details>

**Comment by stephendonner** [comment]
Verified `PASSED` using 



Brave | 1.39.84 Chromium: 101.0.4951.41 (Official Build) beta (x86_64)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | macOS Version 11.6.5 (Build 20G527)

Followed the testplan from https://github.com/brave/brave-browser/issues/22375#issue-1207126725.

Confirmed we now show a loading-spinner icon while CAPTCHA challenge/response is processing.

new | old
---|-----
![new](https://user-images.githubusercontent.com/387249/165843960-48b85b0a-d315-41a2-a413-1d2904850725.gif) | ![old](https://user-images.githubusercontent.com/387249/165843990-6a2c4e9f-316b-43c4-a0c1-8dfd276e2e9f.gif)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.39.100 Chromium: 101.0.4951.61 (Official Build) beta (64-bit)
-- | --
Revision | 3b3633b32c491b4cba5fd7df3c7c0f628547cbcc-refs/branch-heads/4951@{#1189}
OS | Ubuntu 18.04 LTS

Followed the testplan from https://github.com/brave/brave-browser/issues/22375#issue-1207126725.

Confirmed we now show a loading-spinner icon while CAPTCHA challenge/response is processing.

#### Grant

![22375_grant](https://user-images.githubusercontent.com/34715963/167850407-b29ff761-a4eb-4ea6-a36c-3e15a27de67c.gif)


#### ad rewards

![22375_ad](https://user-images.githubusercontent.com/34715963/167850456-e105ad55-9829-4fc7-b8ed-7c2d1ab907e3.gif)
