### ISSUE TITLE
Shields panel doesn't always update immediately upon light/dark-mode toggle

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#22389]
## Description 

Shields panel doesn't always update immediately upon light/dark-mode toggle

## Steps to Reproduce

   1. install `1.39.68`
   2. launch Brave
   3. load `twitch.tv`
   4. click on the Shields icon in the URL bar
   5. in a new tab, open `brave://settings/appearance`
   6. if `Light`, choose `Dark`, and vice-versa
   7. in the `twitch.tv` tab, click again on the Shields icon in the URL bar

## Actual result:

<img width="1312" alt="Screen Shot 2022-04-18 at 8 13 20 PM" src="https://user-images.githubusercontent.com/387249/163913014-483ce9a4-7139-4df2-b8f6-c1ca1541f59c.png">

## Expected result:

The Shields panel should observe pref changes to `Light` / `Dark` and re-validate its cache

<img width="1312" alt="Screen Shot 2022-04-18 at 8 14 55 PM" src="https://user-images.githubusercontent.com/387249/163913124-1a715b1b-be1a-46f1-a24e-45fc951fab8e.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.39.68 Chromium: 101.0.4951.34 (Official Build) nightly (x86_64)
-- | --
Revision | 8f93af5d759634c5256b65997dedd138ed60992f-refs/branch-heads/4951@{#710}
OS | macOS Version 12.4 (Build 21F5048e)

cc @nullhook @rebron @MadhaviSeelam @GeetaSarvadnya

**Comment by stephendonner** [comment]
@simonhong wonder if you have a moment to take a look?  🙏

**Comment by simonhong** [comment]
This happens because shields bubble is destroyed after some delay. 
After some times passed(don't know the exact timing..), shields bubble will have proper theme color.
@nullhook Do you think shiels panel can monitor theme change and use it?

**Comment by rebron** [comment]
Closed with https://github.com/brave/brave-core/pull/13209

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.41.40 Chromium: 102.0.5005.78 (Official Build) nightly (x86_64)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | macOS Version 12.5 (Build 21G5037d)

example | example | example
---------|---------|----------
<img width="1172" alt="Screen Shot 2022-06-06 at 5 30 46 PM" src="https://user-images.githubusercontent.com/387249/172271155-58ef0396-f4be-4696-aef9-7aed5f3c2bf2.png"> | <img width="1172" alt="Screen Shot 2022-06-06 at 5 31 03 PM" src="https://user-images.githubusercontent.com/387249/172271157-09c7868f-bbb5-4dc2-8e19-d2c07e686bb2.png"> | <img width="1172" alt="Screen Shot 2022-06-06 at 5 31 09 PM" src="https://user-images.githubusercontent.com/387249/172271158-51209c76-328a-4b88-ab24-1fbc1651d05a.png">

**Comment by MadhaviSeelam** [comment]
Verification `Passed` using
```
Brave | 1.41.50 Chromium: 102.0.5005.99 (Official Build) nightly (64-bit)
-- | --
Revision | 870f7bcc58dfa811cc68c2186439721385e086d0-refs/branch-heads/5005@{#1125}
OS | Windows 11 Version 21H2 (Build 22000.675)
```

Image1|Image2|Image3
---|---|---
<image width="1950" alt="image1" src="https://user-images.githubusercontent.com/98358127/172956881-d6155db1-957a-4628-8c67-3da4a0c90a77.png">|<image width="950" alt="image2" src="https://user-images.githubusercontent.com/98358127/172956852-ccf6ddb6-73a1-414d-b19c-162ed80b3c63.png">|<image width="950" alt="image1" src="https://user-images.githubusercontent.com/98358127/172956907-17b99b8a-50e0-4631-9508-0c5e2415d338.png">

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.41.77 Chromium: 103.0.5060.53 (Official Build) beta (64-bit) 
--|--
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | Linux

example | example | example
---------|----------|---------
<img width="1286" alt="Screen Shot 2022-06-23 at 3 03 06 PM" src="https://user-images.githubusercontent.com/387249/175423001-6580e5d2-f0e5-430b-aae4-8c70a20bfcb9.png"> | <img width="1286" alt="Screen Shot 2022-06-23 at 3 03 14 PM" src="https://user-images.githubusercontent.com/387249/175423005-a8463f98-a1b6-4e87-87f9-dbc9b1ae9e86.png"> | <img width="1286" alt="Screen Shot 2022-06-23 at 3 03 19 PM" src="https://user-images.githubusercontent.com/387249/175423007-7d9d3e92-3bc3-4aa8-be47-fd477a725dc6.png">
