### ISSUE TITLE
"Look & feel" text should be removed from Shields global settings page

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#22382]
## Description 

`Look & feel` text should be removed from brave://settings/shields page

## Steps to Reproduce

   1.  Install 1.38.90
   2. Launch brave
   3. Navigate to brave://settings/shields page
   

## Actual result:

`Look & feel` text is still displayed/retained from Shields V1

<img width="980" alt="Look feel text" src="https://user-images.githubusercontent.com/98358127/163881312-3828742f-6fc5-4324-818e-fd90177b948b.png">

## Expected result:
`Look & feel` text  should be removed.

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Brave | 1.38.90 Chromium: 100.0.4896.79 (Official Build) beta (64-bit)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | Windows 11 Version 21H2 (Build 22000.593)

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by rebron** [comment]
Closed with https://github.com/brave/brave-core/pull/13209

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.41.47 Chromium: 102.0.5005.78 (Official Build) nightly (x86_64)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | macOS Version 12.5 (Build 21G5037d)

### Steps:
1. installed `1.41.47`
2. launched Brave
3. opened `brave://settings/shields`
4. looked at the `Shields` section

Confirmed `Look & feel` heading text is removed

`1.41.47` | `1.39.120`
----------|----------
<img width="1489" alt="Screen Shot 2022-06-08 at 4 40 22 PM" src="https://user-images.githubusercontent.com/387249/172735352-a0d35b83-4943-4621-aa49-01d2600d0cf8.png"> | <img width="1231" alt="Screen Shot 2022-06-08 at 4 43 28 PM" src="https://user-images.githubusercontent.com/387249/172735503-971d6255-97e7-4e24-9aed-8063e12675b1.png">
