### ISSUE TITLE
missing Windows 11 Rewards Ads notifications

### ISSUE THREAD

**Issue by xbotuk** [brave/brave-browser#22385]
## Description 

Brave is not registered in Windows 11 "Notifications from apps and other senders" and is not sending Rewards Ads notifications 

## Steps to Reproduce

   1. In Windows 11 go to Settings
   2. search for "Notifications & actions settings"
   3. Check the list of applications under  "Notifications from apps and other senders" 

## Actual result:

   Brave browser is not registered to be able to send notifications

## Expected result:
   1. Brave browser should be registered to be able to send notifications and it should send ads from time to time

## Reproduces how often: 

Always

## Brave version (brave://version info)

1.37.116

**Comment by tmancey** [comment]
@xbotuk I am unable to reproduce. Would you be able to screen-share with me so we can investigate further. Thank you, Terry

**Comment by xbotuk** [comment]
@tmancey sure I can screenshare and let me know a suitable date/time. Also, if you follow the steps above in Windows 11 you should be able to see the issue.

**Comment by tmancey** [comment]
@xbotuk apologies for the delay. Can you please let me know if this issue is still occurring with the latest version of Brave. Thanks
