### ISSUE TITLE
`ScriptTriggerWidevinePermissionRequestBrowserTest.SuggestPermissionIfWidevineDetected` failed in `x86`

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#22386]
Looks like `ScriptTriggerWidevinePermissionRequestBrowserTest.SuggestPermissionIfWidevineDetected` keeps failing on the `1.37.x` release channel on `x86` only. We've ran into this on two different occasions when pushing the last two `1.37.x` builds.

QA always goes through Widevine as per the manual passes so we verified things are working but we should look into the above and figure out why it's failing.

```
[  FAILED  ] ScriptTriggerWidevinePermissionRequestBrowserTest.SuggestPermissionIfWidevineDetected
Stacktrace
[ RUN      ] ScriptTriggerWidevinePermissionRequestBrowserTest.SuggestPermissionIfWidevineDetected

[5008:15440:0413/071750.990:WARNING:external_provider_impl.cc(506)] Malformed extension dictionary for extension: odbfpeeihdkbihmopkbjmoonfanlbfcl.  Key external_update_url has value "", which is not a valid URL.
```

CCing @mihaiplesa @simonhong @linhkikuchi

**Comment by simonhong** [comment]
As @goodov mentioned(https://github.com/brave/brave-core/pull/13103#issuecomment-1104974283), this is also flaky on Windows x64.
