### ISSUE TITLE
Display "Unlimited" in approve spend receipt, instead of large number.

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#22392]
![spend](https://user-images.githubusercontent.com/318119/164011760-28ce5a5a-0bad-4445-bfc8-e532b35fb613.png)

**Comment by onyb** [comment]
Not reproducible as of version **1.48.164**. Closing as already fixed.

<img width="360px" src="https://user-images.githubusercontent.com/3684187/220944798-a9781f18-2b16-4cbc-9a90-ecafc775ae6c.png">
