### ISSUE TITLE
Feature request: Ad notification prevention during Video play

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#2239]
Prevent launching new ad notifications if Brave browser is playing video content. This feature is a new ask that is required for both Android and Core for V1.0 Ads launch.

Duplicate for: https://github.com/brave-intl/bat-client-issues/issues/9
Please close the issue above 

cc @mrose17 @tmancey

**Comment by tmancey** [comment]
@mandar-brave Completed as part of `bat-native-ads`

**Comment by tmancey** [comment]
agreed with @mandar-brave that this ticket can be closed as this issue has been resolved with `bat-native-ads` repo
