### ISSUE TITLE
Selecting custom network takes time to load the native token

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#22397]
## Description 

Selecting custom network takes time to load the native token

## Steps to Reproduce

   1. Create/restore wallet
   2. Enable Solana flag (Not sure if its required)
   3. Add Polygon custom network
   4. Switch from Ethereum Mainnet to Polygon
   5. Token doesn't load stays empty
   6. Add a new account, Native token name shows but balance is still not shown. Takes a while to update the native token name and balance

## Actual result:

https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1650375565497879

## Expected result:
Load the token when the network is selected

## Reproduces how often: 

Easy for me on Beta channel

## Brave version (brave://version info)

Brave | 1.38.100 Chromium: 100.0.4896.127 (Official Build) beta (64-bit)
-- | --
Revision | `ff0d0695743e65305d7194f9bd309e5e1c824aa0-refs/branch-heads/4896_88@{#4}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Not checked

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @onyb @Douglashdaniel @josheleonard

**Comment by Douglashdaniel** [comment]
Closing since the `Buy/Send/Swap` widget has now been depreciated and is not actionable.
