### ISSUE TITLE
"Clear cookies and site data when you close all windows" is Now Severely Broken

### ISSUE THREAD

**Issue by bongochong** [brave/brave-browser#22408]
## Description 
As of Brave's latest stable release (1.37.116) the "Clear cookies and site data when you close all windows" setting is fundamentally broken. Having this setting enabled now results in only the cookies associated with domains under "Sites that can always use cookies" being registered **at all**. That is, cookies from other domains are not stored for the current browsing session. For example, if I open a tab and login to GitHub - if github.com is not on the "Sites that can always use cookies" list - once that GitHub tab is closed, I will have to login to GitHub again when revisiting the site. I have confirmed that the cookies of any active tab displaying content from a site not on the aforementioned list are not stored for the current session, via examining brave://settings/siteData?search=cookies. This affects all sites.

## Steps to Reproduce
   1. Enable "Clear cookies and site data when you close all windows".
   2. Visit any domain not on the "Sites that can always use cookies" list.
   3. Login to said site, change some preferences, etc...
   4. Visit brave://settings/siteData?search=cookies.
   5. No cookies for the site in question are displayed.
   6. Close the tab displaying the test site.
   7. Revisit that site in a new tab.

## Actual result:
Any interactions which required the use of cookies - and the cookies themselves - are not retained.

## Expected result:
Cookies from every site should be retained for the active browsing session when the setting in question is enabled, then cleared upon quitting, not beforehand.

## Reproduces how often: 
Always reproducible.

## Brave version (brave://version info)
Brave | 1.37.116 Chromium: 100.0.4896.127 (Official Build) (64-bit)
-- | --
Revision | ff0d0695743e65305d7194f9bd309e5e1c824aa0-refs/branch-heads/4896_88@{#4}
OS | Linux

## Other Additional Information:
Another issue, it appears that cookies for domains which are on the "Sites that can always use cookies" list, are only retained for the session now. I confirmed this by clearing all stored cookies then logging into several sites on my list, and restarting Brave. Even those cookies were removed upon quitting.

I am on Fedora 35, but users of other operating systems have reported this issue as well: https://community.brave.com/t/brave-clearing-cookies-when-i-close-tabs/366275

**Comment by Aloyah1** [comment]
Is there a solution ?

**Comment by diracdeltas** [comment]
is this a duplicate of https://github.com/brave/brave-browser/issues/22493 ?

**Comment by bongochong** [comment]
I'm not sure if it's a duplicate, but as of the latest stable release (V1.38.109), the issue appears to have been fixed, at-least for this guy.

**Comment by bongochong** [comment]
Oh boy, it appears that Brave's cookie handling has been significantly improved, and that the old _Always clear cookies when windows are closed_ blacklist has been renamed to _Sites that clear cookies when you close them_, now functioning similarly to that old Self-Destruct Cookies Firefox extension. Though I was obviously thrown for a loop, It all makes sense now. Closing this issue.
