### ISSUE TITLE
Send Asset is not Updated after Selecting an Account

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#22404]
## Description 
`Send Asset` is not Updated after Selecting an Account with a different `coinType`

https://user-images.githubusercontent.com/40611140/164066165-0bfa51d9-1fd2-4c68-8a0f-4056ccbf490e.mov

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.39.108 Chromium: 101.0.4951.67 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>8888ee7a24e2c36661ddb9536c35b7d4852a3a98-refs/branch-heads/4951@{#1230}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22621.1)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/13070>brave/brave-core#13070</a></li>
         <li>Verified changing accounts from Ethereum to Solana and vice-versa updates the assets accordingly</li>
         <li>Verified changing accounts to Solana on Swap tab switches to Send tab and updates the asset details</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/169283694-2b71b1ca-2965-4d39-8951-f8262ecedf06.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/169285210-e85ce933-9a75-4916-a348-0ef060aeb5ca.mov>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/169285173-e6abe596-32f9-4ed3-97e6-d72073a3ff11.mov>
      </td>
   </tr>
</table>
