### ISSUE TITLE
ipns:// should respect DNS resolver settings

### ISSUE THREAD

**Issue by lidel** [brave/brave-browser#22409]
## Problem

If Brave user decides to use custom DNS over HTTPS resolver via UI below, go-ipfs does not respect that choice, and uses cleartext resolver provided by the OS.

> ![2022-04-20_00-10](https://user-images.githubusercontent.com/157609/164110051-f823fc5c-5ffe-4537-9c08-b65725c46ede.png)

## Proposed change

Every time custom DNS over HTTPS resolver is set via the UI in "Privacy and security" settings, Brave should add/update `.` (top-level resolver) in [`DNS.Resolvers`](https://github.com/ipfs/go-ipfs/blob/master/docs/config.md#dns) map in the `$IPFS_PATH/config` file.
Making changes to this map requires node reboot for changes to be applied

**Comment by lidel** [comment]
I believe this should also be applied to `.eth` and `.crypto` TLDS when user resolves them via DoH:

>  ![2022-04-20_00-34](https://user-images.githubusercontent.com/157609/164112483-885e5561-f396-43d2-ae0c-38f4f5bf1abc.png)


Brave should set explicit DoH URLs in `DNS.Resolvers` for them.

**Comment by lidel** [comment]
cc @spylogsster thoughts on wiring this up?

**Comment by diracdeltas** [comment]
someone should double check that IPFS / IPNS / unstoppable domains / ENS are all still disabled in Tor windows, otherwise there is potentially a Tor DNS leak here.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.43.70 Chromium: 104.0.5112.81 (Official Build) beta (x86_64)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | macOS Version 11.6.8 (Build 20G730)

### Case 1: IPFS/IPNS URLs - `PENDING`
<details>

TBD

</details>


### Case 2: Secure DNS - `PENDING`
<details>

TBD

</details>

### Case 3: Custom DNS resolver - `TBD`

**Comment by stephendonner** [comment]
> someone should double check that IPFS / IPNS / unstoppable domains / ENS are all still disabled in Tor windows, otherwise there is potentially a Tor DNS leak here.

Done in https://github.com/brave/brave-browser/issues/23831 👍

**Comment by stephendonner** [comment]
Also did the following:

1. installed `1.43.73`
2. launched Brave
3. loaded `brave://ipfs`
4. clicked `Install and restart`
5. shut Brave down
6. removed the following from the `config` file in the `brave_ipfs` folder:
```
"/dnsaddr/bootstrap.libp2p.io/p2p/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa","/dnsaddr/bootstrap.libp2p.io/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb","/dnsaddr/bootstrap.libp2p.io/p2p/QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt",
```
7. set `With NextDNS` in `brave://settings/security`
8. launched Wireshark
9. filtered for `dns`
10. loaded `ipns://brad.crypto`

Confirmed DNS lookups went to my selected DoH provider, NextDNS.

`brave://settings/security` | Wireshark, `dns`
---------------------------|-----------------
<img width="1312" alt="Screen Shot 2022-08-17 at 12 08 35 PM" src="https://user-images.githubusercontent.com/387249/185223187-4894d2f9-b590-4f35-9dbe-66ff538b19e5.png"> | <img width="1366" alt="Screen Shot 2022-08-17 at 12 09 37 PM" src="https://user-images.githubusercontent.com/387249/185223193-b1284fe0-2802-4ba1-addf-70f73ccfdb5b.png">

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.43.78 Chromium: 104.0.5112.102 (Official Build) beta (x86_64)
-- | --
Revision | 8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}
OS | macOS Version 11.6.8 (Build 20G730)

### Case 1: no DoH override: loading IPFS and IPNS URLs works and there are DNS requests with _dnslink.<ipns part>

installed `1.43.x`
launched Brave
loaded `brave://ipfs`
clicked `Install and restart`
shut Brave down
launched Wireshark
filtered for `dns`

loaded `ipns://brad.crypto`
loaded `ipns://en.wikipedia-on-ipfs.org/wiki/Asia/#Economy`

### Case 2: DoH override: loading ipfs and ipns URLs works and there is are DNS requests with _dnslink.<ipns part>

installed `1.43.x`
launched Brave
loaded `brave://ipfs`
clicked `Install and restart`
shut Brave down
removed the following from the `config` file in the `brave_ipfs` folder:




set `With NextDNS` in `brave://settings/security`
launched Wireshark
filtered for `dns`
loaded `ipns://brad.crypto`
loaded `ipns://en.wikipedia-on-ipfs.org/wiki/Asia/#Economy`


* Confirmed DNS lookups went to my selected DoH provider, NextDNS.
* Confirmed I didn’t see any DNS requests to *dnslink.<ipns part>

### Case 3: Case 3: Invalid doh override: ipns url are not loading

installed `1.43.x`
launched Brave
loaded `brave://ipfs`
clicked `Install and restart`
set `With Custom` in `brave://settings/security` to `https://127.0.0.1`
loaded `ipns://brad.crypto`
loaded `ipns://en.wikipedia-on-ipfs.org/wiki/Asia/#Economy`

* Confirmed when DoH server is clearly wrong, for example `https://127.0.0.1`, ipns resolution doesn't work

**Comment by cypt4** [comment]
Some related issues found in Kubo:
https://github.com/ipfs/kubo/issues/9199
https://github.com/ipfs/kubo/issues/9204

**Comment by autonome** [comment]
Should this be reopened?
