### ISSUE TITLE
(Feature) Common Library: Ads native core

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#2240]
Develop a cross-platform library to support ads native core;
- support existing user model
- support events logging and collection

Please close issues;
https://github.com/brave-intl/bat-client-issues/issues/8
https://github.com/brave-intl/bat-client-issues/issues/7

cc @mrose17 @tmancey @NejcZdovc

**Comment by NejcZdovc** [comment]
closed with https://github.com/brave/brave-core/pull/765
