### ISSUE TITLE
Use React-Router for page routing/redirects in Wallet pages

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#22402]
## Description 

Non-standard routing logic is used in the Wallet UI pages, causing development slowdowns. Use React-Router to handle routing and redirects.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.41.93 Chromium: 103.0.5060.114 (Official Build) (64-bit) </th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.708)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
            <li>Verified steps from issue description</li>
            <li>Verified when wallet is not created, loading a direct route for portfolio/accounts automatically redirects to onboarding</li>
            <li>Verified loading a direct route without wallet created and then redirecting to onboarding and continuing allows to create the account and complete onboarding</li>
            <li>Verified Portfolio/Accounts/Account Detail/Assets/Backup Wallet/Add Account/Add visible asset screens are only accessible when wallet is unlocked</li>
            <li>Verified loading direct route for any of the above with wallet locked shows <code>brave://wallet/crypto/unlock</code>. Once unlocked loads the direct route that was entered</li>
            <li>Verified with wallet locked only Unlock and Restore wallet routes are accessible</li>
            <li>Verified wallet redirects to the last viewed page on session restore </li>
        </ul>
      </td>
   </tr>
</table>
