### ISSUE TITLE
Custom Reference Dot is showing wrong color

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#22405]
## Description 
Custom Reference Dot is showing wrong color for a `Selected Assets` price history.

![Screen Shot 2022-04-19 at 12 02 38 PM](https://user-images.githubusercontent.com/40611140/164067514-1e0fb96d-829f-4ac6-bd8e-11f2c0c95995.png)

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.39.109 Chromium: 102.0.5005.50 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>f6e2cf8f59ec714bdcff8499991d55898875f287-refs/branch-heads/5005@{#648}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22621.1)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified test plan from <a href=https://github.com/brave/brave-core/pull/13073>#13073</a></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>Portfolio
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/169472197-fc2ea521-dc90-4081-839f-1652ef937d72.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/169472712-80e0ec89-8453-4e75-b2e6-d29563fde302.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/169472665-d5086e97-9a52-42ba-83fb-7cda1b3976b2.png>
      </td>
   </tr>
   <tr>
      <td>Solana
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/169472246-269b1290-11a7-4b72-bab8-7bb7d29587bb.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/169472731-0cce0dec-0959-4877-b5ed-10fdf04ef8f4.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/169472781-b4a529c1-90d2-41b8-821c-a7a253edc41c.png>
      </td>
   </tr>
   <tr>
      <td>Ethereum Tokens (ETH/BAT)
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/169472284-462f8462-bedf-405e-852e-7df92f07312f.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/169472751-84c05e1e-8971-4a0b-b1c0-e8b514af2a92.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/169472683-890851d4-c808-421b-a293-f53d4fe0619d.png>
      </td>
   </tr>
</table>
