### ISSUE TITLE
Incorrect favicon is shown when the shield toggle is turned OFF and ON

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#22415]
## Description 

An incorrect favicon is shown when the shield toggle is turned OFF and ON

## Steps to Reproduce

   1. Clean profile 1.38.103
   2. Open Theverge.com or cnn.com or cnet.com
   3. Open the shield and turn OFF and ON the shield multiple times
   

## Actual result:

An incorrect favicon is shown when the shield toggle is turned OFF and ON

Recorded file path:
https://drive.google.com/file/d/1gopSKc8iHxrXr3KxMXFhcYIxKmx1MMj0/view?usp=sharing

## Expected result:

the correct favicon should be shown when the shield toggle is turned OFF and ON
## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.38.103 Chromium: 100.0.4896.127 (Official Build) beta (64-bit)
-- | --
Revision | ff0d0695743e65305d7194f9bd309e5e1c824aa0-refs/branch-heads/4896_88@{#4}
OS | Windows 10 Version 21H2 (Build 19044.1645)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @nullhook @rebron @brave/qa-team

**Comment by rebron** [comment]
Closed with https://github.com/brave/brave-core/pull/13209

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
Brave | 1.41.46 Chromium: 102.0.5005.78 (Official Build) nightly (64-bit)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | Windows 10 Version 21H2 (Build 19044.1706)

```
- Verified the STR from the description and ensured the correct favicon is shown when the shield is toggled
![favicon](https://user-images.githubusercontent.com/38657976/172767988-ce8bb657-bd93-4a8e-8b57-944e218c9d2a.gif)
