### ISSUE TITLE
Introduce De-Yandex.Turbo similar to De-AMP

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#22414]
Yandex provides a service similar to Google's AMP, named Yandex.Turbo https://yandex.com/dev/turbo/doc/concepts/index.html

Users from countries where Yandex is widespread demand that we allow to bypass Turbo pages as well.

**Comment by iefremov** [comment]
jfyi @pes10k @ShivanKaul

**Comment by pes10k** [comment]
Ah, interesting @iefremov , i wasn't aware of this!  Do you have documentation on the HTML markup for these pages? Is there a similar "tell" early in the document (a la `<html amp>`)?

**Comment by FFxSquall** [comment]
@pes10k I'm not sure about the label in html. But Yandex is currently using the domain turbopages.org 
Example:
https://08-mchs-gov-ru.turbopages.org/08.mchs.gov.ru/s/deyatelnost/press-centr/novosti/4726459

Previously the link looked something like this yandex.ru/turbo?text=${originalURL}

**Comment by iefremov** [comment]
@pes10k I haven't seen any reliable documentation about the markup, but this script seems up to date https://github.com/Autapomorph/userscripts/blob/main/src/avoid-yandex-turbo.user.js

Also AFAIR at some point yandex declared that turbo pages are mobile only, testing them with desktop sites was terminated.

**Comment by pes10k** [comment]
Okay from following up on this, here is first go at a plan:

the "tell":
1. served from turbopages.org
2. inclues markup like `<meta itemscope="" itemprop="mainEntityOfPage" itemtype="https://schema.org/WebPage" itemid="{URL}">` or `<link rel="canonical" href="{URL}">`

**Comment by pes10k** [comment]
(apologies did not mean to close that!)

**Comment by Seirdy** [comment]
Perhaps it'd be worth creating a meta-issue for all AMP and AMP-like providers. Yandex, Bing, and Cloudflare have their own caches.

**Comment by ShivanKaul** [comment]
Bing and Cloudflare are still AMP caches though  AFAIK

**Comment by ShivanKaul** [comment]
All the Turbo Pages URLs I'm seeing get opened as new tabs when searching on Yandex on (emulated) mobile and are of the type https://<publisher>.turbopages.org/<publisher>/s/<url for page>

These should be easy to debounce, just needs a minor change to support multiple regex capture groups for the regex-path action. 

If anyone comes across pages that don't follow the above pattern, please let me know.
