### ISSUE TITLE
(Feature) Common Library: Ads confirmations

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#2241]
Develop a common library for Core and Android to support;

- ad catalog json pulled from ad-server
- ad confirmations 
- ad payments integration into bat-wallet

Please close issues:
https://github.com/brave-intl/bat-client-issues/issues/1
https://github.com/brave-intl/bat-client-issues/issues/5

cc @mrose17 @kevinlawler @NejcZdovc

**Comment by tmancey** [comment]
Resolved as part of https://github.com/brave-intl/bat-native-confirmations/issues/57 which is currently under security review

**Comment by tmancey** [comment]
agreed with @mandar-brave that this ticket can be closed as this issue has been resolved with `bat-native-ads` and `bat-native-confirmations` repos
