### ISSUE TITLE
Userscript managers such as Violentmonkey and Tampermonkey do not execute scripts

### ISSUE THREAD

**Issue by JovoTheTurtle** [brave/brave-browser#22412]
## Description 
Updated to Brave 1.37.116 a few days ago. Userscripts from userscript managers such as tampermonkey and violentmonkey will no longer run on any website. On firefox both had worked fine. The previous release had worked fine as well.

## Steps to Reproduce

   1. Install either tampermonkey or violentmonkey userscript manager. 
   2. Install a userscript from greasyfork.org or from a trusted source. For example I will be using the [Return Youtube Dislike](https://www.returnyoutubedislike.com/) userscript.
   3. Navigate to the website that the userscript is supposed to run on, in this case Youtube.

## Actual result:

On ViolentMonkey, the number of scripts running is not shown, indicating none is running.

## Expected result:
Scripts run and execute their code to improve user experience.

## Reproduces how often: 

Ever since the last update.

## Brave version (brave://version info)

Brave: 1.37.116 Chromium: 100.0.4896.127 (Official Build) (64-bit)
Revision: ff0d0695743e65305d7194f9bd309e5e1c824aa0-refs/branch-heads/4896_88@{#4}

**Comment by JovoTheTurtle** [comment]
Disabling all other extensions also did not work.

**Comment by Tosoju** [comment]
I use Ungoogled Chromium 100.0.4896.127 and this issue does not exist on Ungoogled Chromium

**Comment by AlecKinnear** [comment]
Tampermonkey works for me on OS X 12.6.1 Brave Version 1.43.88 Chromium: 105.0.5195.68 (Official Build) (arm64). Glad the issue appears to be resolved, envious eyes were on my colleagues very useful modifications in Firefox.

**Comment by JovoTheTurtle** [comment]
Going back to this issue, I can say that one way or another, it was fixed and userscripts works again
