### ISSUE TITLE
Unable to finish wallet onboarding. Seed words are not generated

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#22413]
## Description 

Unable to finish wallet onboarding. Seed words are not generated

## Steps to Reproduce

   1. Clean profile on Nightly
   2. Start wallet onbording
   3. Can't skip and go past the backup phrase screen
   4. Select checkbox and continue to backup, no seed phrase is shown

## Actual result:

https://user-images.githubusercontent.com/17010094/164191463-457258bb-e71c-4d07-b1b1-9c1b05ef869b.mov

## Expected result:
Finish onboarding with or without skipping the backup wallet phrase

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.39.70 Chromium: 101.0.4951.34 (Official Build) nightly (64-bit)
-- | --
Revision | `8f93af5d759634c5256b65997dedd138ed60992f-refs/branch-heads/4951@{#710}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/crypto-wallets @Douglashdaniel @onyb @josheleonard

**Comment by kjozwiak** [comment]
The above will require `1.39.79` or higher for `1.39.x` verification 👍

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.39.89 Chromium: 101.0.4951.41 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22598.200)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td>
      </td>
      <td colspan=3>
         <ul>
         <li>Verified steps from issue description</li>
         <li>Verified able to create a wallet and go past the onboarding screen</li>
         <li>Verified mnemonic words are generated on wallet creation</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/166637206-06205a90-424f-4803-a74b-ea5dc76bd89b.mp4>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/166637167-6b57533b-96a7-4f4d-ad74-9c762f476856.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/166637232-cd8f0874-c8cc-4bfe-9e00-1fd91b649ba2.mov>
      </td>
   </tr>
</table>
