### ISSUE TITLE
blocked Trackers and ads count is shown when the shield is down

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#22422]
## Description 

blocked Trackers and ads count is shown when the shield is down

## Steps to Reproduce

   1. Clean profile `1.38.103`
   2. Open brave://settings/shields
   3. Enable global `Block scripts` settings
   4. Open cnn.com or buzzfeed.com
   5. Open shield and turn off and on the shield a couple of times, observe trackers count is shown when shield is down

## Actual result:

blocked Trackers and ads count is shown when the shield is down

Recorded file path:
https://drive.google.com/file/d/1CVn-FiEKQkCrWIG8WtigvFsIVJSqVfUt/view?usp=sharing

![image](https://user-images.githubusercontent.com/38657976/164260212-5db201b7-4336-449a-b655-516a68a09f27.png)

## Expected result:
blocked Trackers and ads count should not be shown when the shield is down

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.38.103 Chromium: 100.0.4896.127 (Official Build) beta (64-bit)
-- | --
Revision | ff0d0695743e65305d7194f9bd309e5e1c824aa0-refs/branch-heads/4896_88@{#4}
OS | Windows 10 Version 21H2 (Build 19044.1645)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @nullhook @rebron

**Comment by stephendonner** [comment]
Figma shows the 0 count, FWIW (not sure if it needs updating?). https://www.figma.com/proto/3A6F6VrxVahiZFxLr7j7FO/Desktop-Brave-Shields?node-id=1979%3A30280

**Comment by aguscruiz** [comment]
Design for Shields down here: https://www.figma.com/file/3A6F6VrxVahiZFxLr7j7FO/Desktop-Shields?node-id=1804%3A30480

- Changes number for a dash 
- Text below URL on header changes from "Trackers, ads, and more blocked" to "Not protected by Brave Shields" when shields down

<img width="851" alt="image" src="https://user-images.githubusercontent.com/15734630/165355585-5ab538fa-8803-48a8-8cfc-7f39bdff2b04.png">

**Comment by rebron** [comment]
Closed with https://github.com/brave/brave-core/pull/13209

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
Brave | 1.41.46 Chromium: 102.0.5005.78 (Official Build) nightly (64-bit)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | Windows 10 Version 21H2 (Build 19044.1706)

```
- Verified the new design for shield down https://github.com/brave/brave-browser/issues/22422#issuecomment-1110048388 and ensured the followings:
  - Confirmed that the blocked trackers and ads count is NOT shown when the shield is down
  - Confirmed that the dash `-` is shown in place of the number when the shield is down
  - Confirmed the changed text `Not protected by Brave Shields` is shown when the shield is sown

Dark theme | Light theme
-- | --
![image](https://user-images.githubusercontent.com/38657976/172762646-fe4177cf-d99f-4263-8418-2ef23f75041d.png) | ![image](https://user-images.githubusercontent.com/38657976/172762595-094fa001-1777-4f76-af97-36f404290dfb.png)

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.41.47 Chromium: 102.0.5005.78 (Official Build) nightly (x86_64)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | macOS Version 12.5 (Build 21G5037d)

NOTE: encountered https://github.com/brave/brave-browser/issues/23245

### Steps
1. installed `1.41.47`
2. launched Brave
3. loaded `thenextweb.com`
4. toggled Shields to `Off`/`Disabled`

Verified the new design for shield down https://github.com/brave/brave-browser/issues/22422#issuecomment-1110048388 and ensured the following:
* blocked trackers and ads count is NOT shown when the shield is down
* dash `-` is shown in place of the number when the shield is down
* changed text `Not protected by Brave Shields` is shown when Shields are down


Dark mode | Light mode
-----------|-------------
<img width="1312" alt="Screen Shot 2022-06-09 at 3 05 08 AM" src="https://user-images.githubusercontent.com/387249/172824133-a59c2b69-20b4-4dde-85cf-5c27786ac149.png"> | <img width="1312" alt="Screen Shot 2022-06-09 at 3 05 46 AM" src="https://user-images.githubusercontent.com/387249/172824139-e9a82e7d-9e56-4eb2-b938-964824a1fc88.png">
