### ISSUE TITLE
remove 'Google's Sync and Brave services' section

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#2242]
Shouldn't show 'Sync and Brave Services'. This is Google's sync services and not ours. 

<img width="682" alt="sync-setting" src="https://user-images.githubusercontent.com/5951041/49046755-0d8e2380-f18a-11e8-9c74-ea39d7c9a1c5.png">

Need to move these preferences back to Privacy and Security section and hide/delete Sync heading section until ready.

<img width="682" alt="sync-settings" src="https://user-images.githubusercontent.com/5951041/49097258-43cab200-f221-11e8-9a9e-4951d9c296c4.png">

**Comment by kjozwiak** [comment]
Agreed 👍We shouldn't be showing Google's logo anywhere within Brave. It's also the second item in the settings so the likely hood of folks noticing this are pretty high. Plus, Google is still getting a lot of slack from the general community regarding forcing folks to login etc.. We'll get some blowback/concerned users if we ship with that logo in the settings.

Example:

<img width="856" alt="screen shot 2018-11-27 at 1 55 29 pm" src="https://user-images.githubusercontent.com/2602313/49104517-2b23c180-f24c-11e8-9b39-64d060e8b633.png">

**Comment by bbondy** [comment]
marking 0.57.x milestone.

**Comment by kjozwiak** [comment]
Went through verification using the following build under `Ubuntu 18.04 x64` - **PASSED**

Brave | 0.57.12 Chromium: 71.0.3578.75 (Official Build) (64-bit)
--- | ---
Revision | 06ef00b5279f93f8e0c1e73acedd49d7dcc09767-refs/branch-heads/3578@{#836}
OS | Mac OS X

![screen shot 2018-12-03 at 4 32 06 pm](https://user-images.githubusercontent.com/2602313/49402837-0da59a80-f719-11e8-9f96-297ecd37bb21.png)

* ensured that the settings that were listed under `Google's Sync and Brave services` are still present/available under Brave.
