### ISSUE TITLE
Migrate away from Rewards Extension to WebUI: Make background page of Reward Extension non-persistent

### ISSUE THREAD

**Issue by atuchin-m** [brave/brave-browser#22423]
Currently if rewards is enabled `Reward Extension` lives forever and consumes user memory.
The extension process should be launched only if the panel opened.

The entry point in the code: [brave_rewards_panel_background.js](https://github.com/brave/brave-core/blob/master/components/brave_rewards/resources/extension/brave_rewards/background.ts#L5)

slack discussion: https://bravesoftware.slack.com/archives/CNH9Q6REV/p1650469219904509
<img width="562" alt="image (16)" src="https://user-images.githubusercontent.com/45488748/164276707-7cb6e4d2-5f8d-4c2b-8708-b4f9ac72407c.png">

**Comment by LaurenWags** [comment]
Marking as `QA/Blocked` until https://github.com/brave/brave-browser/issues/24546 is resolved via Griffin. Worst case scenario we can test via flag manipulation on brave://flags.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.43.71 Chromium: 104.0.5112.81 (Official Build) beta (x86_64)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | macOS Version 12.5 (Build 21G72)
```

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```
Brave | 1.43.78 Chromium: 104.0.5112.102 (Official Build) beta (64-bit)
-- | --
Revision | 8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}
OS | Windows 10 Version 21H2 (Build 19044.1889)

```

**Comment by LaurenWags** [comment]
Per discussion with @zenparsing @Miyayes, removed the `OS/Android` tag as there were no Android changes with this issue.
