### ISSUE TITLE
Dismiss button on adaptive captcha panel's "Solved" screen has incorrect French translation

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#22421]
The "Dismiss" button on the adaptive captcha panel's "Solved" screen has an incorrect French translation. It should probably be `Fermer` instead.

![capture_d_____cran_du_2022-04-19_21-54-41](https://user-images.githubusercontent.com/5033691/164259555-b478a31d-fa2d-43db-a65f-9f61005c2788.png)

```
"captchaDismiss": {
  "message": "Ignorer",
  "description": ""
},
```

**Comment by fmarier** [comment]
I have updated the suggested button label :)

**Comment by mkarolin** [comment]
I've updated all instances of "Dismiss" to use "Fermer" as the translation: https://www.transifex.com/brave/brave/translate/#fr/$/335640567?q=text%3ADismiss

**Comment by mkarolin** [comment]
Fixed via https://github.com/brave/brave-core/pull/13147

**Comment by kjozwiak** [comment]
The above requires `1.38.106` or higher for `1.38.x` verification.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.38.106 Chromium: 101.0.4951.41 (Official Build) (64-bit) 
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | Ubuntu 18.04 LTS

`Fermer` it is:
![image](https://user-images.githubusercontent.com/34715963/165304872-5bf7dd6b-ba1a-42eb-a69e-4924dafaac75.png)
