### ISSUE TITLE
Android and Desktop must use same code for sync QR code generation 

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#22420]
Currently Desktop uses `QRCodeGeneratorService` and Android uses `com.google.zxing.MultiFormatWriter`  and fills the bitmap.

Need to use the same code. Also the style of the QR code image might bi aligned with "Share page through QR style" - have rounded dots and the Brave's logo.

**Comment by iccub** [comment]
iOS counterpart https://github.com/brave/brave-ios/issues/5391

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.40.80 Chromium: 102.0.5005.78 (Official Build) beta (x86_64)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | macOS Version 11.6.6 (Build 20G624)

### Steps (chain creator):
1. install `1.40.80`
2. launch Brave
3. click on the `"Hamburger"` menu on the main toolbar
4. click on `Sync`
5. click on `Start using Sync`
6. click on `Start a new Sync Chain`
7. click on `Computer`
8. click on `OK`
9. confirm you can successfully start a new sync chain

### Steps (joining client):
1. install `1.40.80`
2. launch Brave
3. click on the `"Hamburger"` menu on the main toolbar
4. click on `Sync`
5. click on `Start using Sync`
6. click on `I have a Sync Code`
10. confirm you can successfully join the sync chain, and are listed accordingly

| chain creator | desktop client | Android client | iOS client |
|---------------|----------------|----------------|------------|
| desktop       |                |                |            |
| Android       |                |                |            |

**Comment by Uni-verse** [comment]
Verification in progress on Samsung Galaxy S21 & Tab S7 using 

```
Brave	1.40.91 Chromium: 102.0.5005.78 (Official Build) beta (64-bit) 
Revision	df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS	Android 12; Build/SP1A.210812.016
```
Creating Chain

- Confirmed user is able to start a new sync chain on device
- Confirmed QR Code contains the brave logo and rounded dots

Joining Chain

- Confirmed able to join sync chain by scanning QR code that contains brave logo and rounded dots. 

Devices on Sync Chain | Scanned to join | Created Chain
-|-|-
![screenshot-1654816926557](https://user-images.githubusercontent.com/17885425/172962361-43ecb532-abd3-4a59-a07f-752b1c948c3b.png) | ![screenshot-1654816877326](https://user-images.githubusercontent.com/17885425/172962374-7604d647-fc10-4c52-83a7-011ce6d05fcb.png) | ![screenshot-1654817992788](https://user-images.githubusercontent.com/17885425/172962489-555f8fdd-a05b-4243-9cea-c250089c4d1f.png)
