### ISSUE TITLE
Shields should be disabled for magnet links

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#22428]
## Description 

Shields should be disabled for magnet links

## Steps to Reproduce

   1. install `1.39.33`
   2. launch Brave
   3. load `https://webtorrent.io/free-torrents`
   4. click on `(magnet link)` for any file (such as `magnet:?xt=urn:btih:dd8255ecdc7ca55fb0bbf81323d87062db1f6d1c&dn=Big+Buck+Bunny&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&ws=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2F&xs=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2Fbig-buck-bunny.torrent` for Big Buck Bunny)
   5. reload the page (to work around a long-standing issue)
   6. examine/click on the Shields icon

## Actual result:

It appears toggleable, but doesn't really do anything, nor correctly reflect its state.

<img width="1770" alt="Screen Shot 2022-04-20 at 11 01 08 AM" src="https://user-images.githubusercontent.com/387249/164294402-bc0ee22f-3bd8-4660-a215-d1d9ce9b2ccc.png">

## Expected result:

Shields should be disabled (if we are looking for parity with current release).

<img width="1200" alt="Screen Shot 2022-04-20 at 11 00 50 AM" src="https://user-images.githubusercontent.com/387249/164294338-3f007066-c5d5-40e6-bc2f-b848fe753d9b.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.39.73 Chromium: 101.0.4951.34 (Official Build) nightly (x86_64)
-- | --
Revision | 8f93af5d759634c5256b65997dedd138ed60992f-refs/branch-heads/4951@{#710}
OS | macOS Version 11.6.5 (Build 20G527)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `no`
- Can you reproduce this issue with the beta channel? `yes`
- Can you reproduce this issue with the nightly channel? `yes`

cc @nullhook @rebron @GeetaSarvadnya @MadhaviSeelam

**Comment by rebron** [comment]
Closed with https://github.com/brave/brave-core/pull/13209

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.41.47 Chromium: 102.0.5005.78 (Official Build) nightly (x86_64)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | macOS Version 12.5 (Build 21G5037d)

### Steps
1. installed `1.41.47`
2. launched Brave
3. loaded `https://webtorrent.io/free-torrents
4. click on (magnet link) for any file (such as magnet:?xt=urn:btih:dd8255ecdc7ca55fb0bbf81323d87062db1f6d1c&dn=Big+Buck+Bunny&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&ws=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2F&xs=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2Fbig-buck-bunny.torrent` for Big Buck Bunny)
reload the page (to work around a long-standing issue)
examine/click on the Shields icon

#### Confirmed the Shields icon is:
1. default disabled when on a magnet URI
2. not enableable 

<img width="976" alt="Screen Shot 2022-06-09 at 2 20 38 AM" src="https://user-images.githubusercontent.com/387249/172813470-c83a2d9c-4a9e-459b-9df9-21c38618bd6a.png">
