### ISSUE TITLE
news scroll velocity stops when scrolling down at the start of the feed - follow up to #21475

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#22434]
## Test plan
See https://github.com/brave/brave-core/pull/13951

## Description 

So now that #21475 has been fixed, the experience in scrolling has drastically improved. However, the issue still exists when you start scrolling starting at the top of the Brave News feed. As @bsclifton mentioned, when you start scrolling, the velocity basically stops dead in its tracks unless you swipe a second time and then continue going through the feed. Before, you needed to swipe through the 

It's working as expected when scrolling from the bottom to the top but as mentioned above, it still runs into the same issue when you start at the top of the feed.

## Steps to reproduce 

   1. launch Brave and enable the Brave News feed
   2. once enabled, start swiping through the news feed and you'll notice that the velocity will stop
   3. swipe a second time to keep scrolling through the news feed
 
## Actual result 

https://user-images.githubusercontent.com/2602313/164299045-8a7f935c-40b2-48c1-8264-ce9e8a71a4d1.mp4

## Expected result

When scrolling, the velocity should stay the same and keep going/not stop in the middle of the feed.

## Issue reproduces how often 

100% reproducible using the STR mentioned above

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `Yes`
- Can you reproduce this issue with the current Play Store Beta version? `Yes` 
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Pixel 6` (Phone)
   - Android version: `Android 12`
   
## Brave version

* `1.39.73 Chromium: 101.0.4951.34`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

### Additional information

CCing @timchilds @mattmcalister @anthonypkeane @srirambv @Uni-verse @alekseva @deeppandya

**Comment by Uni-verse** [comment]
Verified on `Samsung GS 21` & `Samsung Galaxy Tab S7` running `Android 12` using

```
Brave	1.43.74 Chromium: 104.0.5112.102 (Official Build) beta (64-bit) 
Revision	8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}
OS	Android 12; Build/SP1A.210812.016
```

- Verified scrolling velocity doesn't stop in the middle of the feed.
- Verified scrolling velocity is consistent in `portrait` and `landscape` orientation.
- Verified scrolling is consistent with `background images` disabled from the `New Tab Page` settings menu 

<table><tr><td>Mobile</td><td>Tablet</td>
<tr><td>

https://user-images.githubusercontent.com/17885425/185438875-2dc2c486-2e7c-4950-a0d1-d73da687896c.mp4

</td><td>

https://user-images.githubusercontent.com/17885425/185439738-6ae9cb90-2989-4788-b82a-bad4b1fb6649.mp4

</td>
