### ISSUE TITLE
Favicons urls (chrome://favicon/size/url_name) are not processed on Android.

### ISSUE THREAD

**Issue by gdregalo** [brave/brave-browser#2243]
`FaviconSource` is not recognized as available `URLDataSource` when built for  Android.
It's included on Desktop implementation from `chrome/browser/ui/browsing_history_handler.cc`, which  is excluded for Android build.

**Comment by gdregalo** [comment]
The corresponding PR (https://github.com/brave/brave-core/pull/961) is closed.

The duplicate PR was opened for `android` branch.
PR: #1425.
Issue: [brave/browser-android-tabs#990](https://github.com/brave/browser-android-tabs/issues/990):

The code changes will be applied to `master` when it's merged with `android` .

**Comment by NejcZdovc** [comment]
closing based on top comment
