### ISSUE TITLE
News feed issue when changing orientation after new tab

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#22439]
## Test plan
See https://github.com/brave/brave-core/pull/13951

## Description 
When using tablet in the landscape orientation, begin scrolling through news feed, then open NTP and scroll feed again. When changing orientation to portrait, this will cut the feed off at the top and leave gap. 

## Steps to reproduce 

   1. Enable Brave News
   2. Change tablet orientation to landscape
   3. Begin scrolling through news feed
   4. Open new tab
   5. Begin scrolling through feed in the new tab
   6. Change orientation to portrait
   7. Continue scrolling news

## Actual result 
Leaves a gap at the top of new tab and cuts off feed

https://user-images.githubusercontent.com/17885425/164337919-7ffea196-b09a-43e2-bee7-426e3934ed85.mp4

## Expected result
Just like before

## Issue reproduces how often 
Easily, 100%

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung GS 21, Samsung Galaxy Tab S7
   - Android version: 12
   
## Brave version
`1.38.103, Chromium 100.0.4896.127`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
Removing from the `1.38.x` milestone as the above isn't labelled as `release/blocking`.

**Comment by deeppandya** [comment]
This bug is also reproducible on phones as well.

**Comment by Uni-verse** [comment]
Verified on `Samsung GS 21` & `Samsung Galaxy Tab S7` using

```
Brave	1.43.74 Chromium: 104.0.5112.102 (Official Build) beta (64-bit) 
Revision	8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}
OS	Android 12; Build/SP1A.210812.016
```

- Verified news feed is not cut off when changing orientation based on use case in https://github.com/brave/brave-browser/issues/22439#issue-1210308348

<table><tr><td>Example</td><td>Example</td></tr>
<tr><td>

https://user-images.githubusercontent.com/17885425/185506365-89500fd9-7328-43b2-92f3-c39f848e41df.mp4

</td><td>

https://user-images.githubusercontent.com/17885425/185506479-1b809384-03a6-4514-aa46-d81dd4ff38e9.mp4

</td><tr>
