### ISSUE TITLE
Debounced sites should never show a top-level document blocking interstitial

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#22437]
Some websites have `$document` options (either implicitly or explicitly) in adblock filter lists, preventing users from accidentally visiting them without first clicking through a top-level document blocking interstitial. Some of those same websites are listed in [our debounce list](https://github.com/brave/adblock-lists/blob/master/brave-lists/debounce.json). We should avoid bringing up the interstitial for debounced links, since there are no serverside calls required for the intermediate URL and thus no privacy risk involved.

Some links found in the wild that result in an interstitial, despite being debounced:

`https://clickserve.dartsearch.net/link/click?lid=92700067144412497&ds_s_kwgid=58700001236285396&ds_s_inventory_feed_id=97700000000001001&ds_a_cid=75683555&ds_a_caid=378324755&ds_a_agid=26777702795&ds_a_fiid=&ds_a_lid=pla-1457212127228&ds_a_extid=&&ds_e_adid=102712441595&ds_e_matchtype=search&ds_e_device=c&ds_e_network=g&ds_e_product_group_id=1457212127228&ds_e_product_id=202501682&ds_e_product_merchant_id=8740&ds_e_product_country=US&ds_e_product_language=en&ds_e_product_channel=online&ds_e_product_store_id=&ds_url_v=2&ds_dest_url=https://8808.xg4ken.com/trk/v1?prof=404&camp=19651&kct=google&kchid=7097773753&criteriaid=pla-1457212127228&campaignid=378324755&locphy=9061268&adgroupid=26777702795&adpos=&cid=102712441595&networkType=search&kdv=c&kext=&kadtype=pla&kmc=8740&kpid=202501682&url=https://www.homedepot.com/p/Lite-Line-8-ft-White-Track-Finished-HD-TR122/202501682?g_store=&source=shoppingads&locale=en-US&pla&mtc=Shopping-BF-F_Brand-G-Multi-NA-Multi-NA-Feed-PLA_LIA-NA-NA-Catchall_PLA&cm_mmc=Shopping-BF-F_Brand-G-Multi-NA-Multi-NA-Feed-PLA_LIA-NA-NA-Catchall_PLA-71700000014585962-58700001236285396-92700067144412497&gclsrc=aw.ds&gclid=EAIaIQobChMI3c322fag9wIVAcLCBB1ibwDvEAQYAyABEgJD3vD_BwE`

`https://go.redirectingat.com/?id=111346X1569486&url=https://duckduckgo.com&xcust=1-1-633804-1-0-0&sref=https://www.macworld.com/article/633804/brave-duckduckgo-updates-target-google-amp-sites-in-privacy-push.html`

**Comment by LaurenWags** [comment]
@pilgrim-brave @pes10k looks like this one is marked `QA/Yes` but is lacking a test plan, could either of you assist with a test plan? Thanks!

**Comment by pes10k** [comment]
Sure thing.  @pilgrim-brave should confirm this is correct, but i think this test should be fine

1. put shields in aggressive mode (globally)
2. go to brave://settings/shields/filters
3. add and save this rule as a custom filter `https://dev-pages.brave.software/navigation-tracking/error.html?brave_testing=www.brave.com$document`
4. visit this URL: https://dev-pages.brave.software/navigation-tracking/error.html?brave_testing=https://example.org/$document

If you see the interstitial, the test fails.  If you see the example.org page, the test passes

**Comment by pilgrim-brave** [comment]
Yes that looks correct.

**Comment by stephendonner** [comment]
## Verification `PASSED` using 

Brave | 1.53.75 Chromium: 114.0.5735.58 (Official Build) beta (64-bit)
-- | --
Revision | ef012197ab4bc867d7b1dd80a001d0be7da8a714-refs/branch-heads/5735_52@{#7}
OS | Windows 10 Version 22H2 (Build 19045.3031)


### No interstitial - `PASSED`
<details>


### Steps:
1. installed `1.53.75`
2. launched Brave
3. set `Trackers & ads blocking` to `Aggressive`, in `brave://settings/shields`
4. added `https://dev-pages.brave.software/navigation-tracking/error.html?brave_testing=www.brave.com$document` to `brave://settings/shields/filters` in the `Create custom filters` section
5. clicked `Save changes`
6. loaded `https://dev-pages.brave.software/navigation-tracking/error.html?brave_testing=https://example.org/$document`

### Confirmed `example.org/$document` loaded, without the interstitial-warning page

example | example | example
----------|----------|-----------
![image (2)](https://github.com/brave/brave-browser/assets/387249/4385f101-89c6-4d8e-8bda-cd91304475ef) | ![image](https://github.com/brave/brave-browser/assets/387249/b96174b7-c45c-42c5-8606-4a2e0eb1d513) | ![image](https://github.com/brave/brave-browser/assets/387249/61f4a98c-19d9-4eab-a28b-9e0c8b3ad8f1)

</details>

### Interstitial - `PASSED`
<details>

### Steps:
1. installed `1.53.75`
2. launched Brave
3. set `Trackers & ads blocking` to `Aggressive`, in `brave://settings/shields`
4. added `https://dev-pages.brave.software/navigation-tracking/warning-interstitial.html$document` to `brave://settings/shields/filters` in the `Create custom filters` section
5. clicked `Save changes`
6. loaded `https://dev-pages.brave.software/navigation-tracking/warning-interstitial.html`

### Confirmed the `This site may attempt to track you across...` interstitial-warning page appears, and can be clicked through via `Proceed`, to `https://dev-pages.brave.software/navigation-tracking/warning-interstitial.html`

example | example | example | example
----------|-----------|----------|----------
![image (2)](https://github.com/brave/brave-browser/assets/387249/ee10e219-2276-49a4-8d90-7683162766e3) | ![image (3)](https://github.com/brave/brave-browser/assets/387249/974e61ff-c50f-4ef8-a79d-10e3d019903c) | ![image (1)](https://github.com/brave/brave-browser/assets/387249/670366d2-1a26-4bfa-a66f-b11f04105880) | ![image](https://github.com/brave/brave-browser/assets/387249/2607033c-7de7-4453-ae31-311e4b72c56a)



</details>

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 



Brave | 1.53.81 Chromium: 114.0.5735.90 (Official Build) beta (x86_64)
-- | --
Revision | 386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}
OS | macOS Version 11.7.7 (Build 20G1345)




### No interstitial - `PENDING`
<details>


### Steps:
1. installed `1.53.81`
2. launched Brave
3. set `Trackers & ads blocking` to `Aggressive`, in `brave://settings/shields`
4. added `https://dev-pages.brave.software/navigation-tracking/error.html?brave_testing=www.brave.com$document` to `brave://settings/shields/filters` in the `Create custom filters` section
5. clicked `Save changes`
6. loaded `https://dev-pages.brave.software/navigation-tracking/error.html?brave_testing=https://example.org/$document`

### Confirmed `example.org/$document` loaded, without the interstitial-warning page

example | example | example
----------|----------|-----------

</details>

### Interstitial - `PENDING`
<details>

### Steps:
1. installed `1.53.81`
2. launched Brave
3. set `Trackers & ads blocking` to `Aggressive`, in `brave://settings/shields`
4. added `https://dev-pages.brave.software/navigation-tracking/warning-interstitial.html$document` to `brave://settings/shields/filters` in the `Create custom filters` section
5. clicked `Save changes`
6. loaded `https://dev-pages.brave.software/navigation-tracking/warning-interstitial.html`

### Confirmed the `This site may attempt to track you across...` interstitial-warning page appears, and can be clicked through via `Proceed`, to `https://dev-pages.brave.software/navigation-tracking/warning-interstitial.html`

example | example | example | example
----------|-----------|----------|----------




</details>

**Comment by vlad-hoff** [comment]
Hi @pes10k can you help me with the steps to test it on Android? I don't see `filters` option in Brave Shields.

![Screenshot_20230608-182436](https://github.com/brave/brave-browser/assets/128532965/38ff98bc-d96b-4225-aa07-9ac3b23da879)

**Comment by pes10k** [comment]
The custom filters option isn't currently available on android but is coming (cc @deeppandya @anthonypkeane )

In the meantime though, i think its fine to omit the tests on android, until we have custom filters, since the code paths are identical to desktop

**Comment by pes10k** [comment]
@vlad-hoff apologies, update, can you add the custom filters to brave://adblock on android as a short term option
