### ISSUE TITLE
Descriptive text for Wallet and VPN icons on toolbar need to be consistent

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#22436]
## Steps to Reproduce

   1. install `1.39.73`
   2. open `brave://flags`
   3. enable `Experimental VPN...`
   4. click `Relaunch`
   5. context-click on the `Wallet` icon on the browser toolbar; read its descriptive text (NOT tooltip)
   6. context-click on the `VPN` icon on the browser toolbar; read its descriptive text (NOT tooltip)

## Actual result:

`Wallet` | `VPN`
--------|--------
<img width="1476" alt="Screen Shot 2022-04-20 at 1 27 35 PM" src="https://user-images.githubusercontent.com/387249/164317535-a39e5901-8976-41d0-87ad-8cb9f10ee68e.png"> | <img width="1512" alt="Screen Shot 2022-04-20 at 1 27 44 PM" src="https://user-images.githubusercontent.com/387249/164317543-9f64b7aa-05ce-4f1c-98e3-ae1867fc58f0.png">

`Hide Brave Wallet icon on toolbar` vs. `Hide VPN button in Toolbar`

Note:
* casing differences
* mixed prepositions on/in

## Expected result:

Consistency.

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.39.73 Chromium: 101.0.4951.34 (Official Build) nightly (x86_64)
-- | --
Revision | 8f93af5d759634c5256b65997dedd138ed60992f-refs/branch-heads/4951@{#710}
OS | macOS Version 11.6.5 (Build 20G527)

cc @rmcfadden3 @rebron @bsclifton @jamesmudgett @jenn-rhim

**Comment by Tonev** [comment]
@stephendonner 

Maybe it would be the best if changed to `Hide Brave Wallet icon` and `Hide Brave VPN button` because https://github.com/brave/brave-browser/issues/22525 will introduce an option `Hide Brave Rewards icon`, which will leave us with 3 different messages if the messages for wallet and VPN remain the same.

**Comment by rmcfadden3** [comment]
@stephendonner @Tonev — yeah, I'd vote for consistency. Opted for "in" as reference to toolbar is a space rather than a surface. Also it avoids the repetition of "on" sound that would've appeared in "icon on."

- Hide Wallet icon in toolbar
- Hide VPN icon in toolbar

**Comment by jagadeshjai** [comment]
Seems this issue is fixed now @stephendonner
