### ISSUE TITLE
News feed will reappear when changing orientation

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#22444]
## Description 
After scrolling news feed, disabling brave news in settings will disable the feed but changing tablet orientation will show it again. 

Observed on 1.38.x, 1.39.x

**Does not impact mobile** 

## Steps to reproduce 

   1. Enabled Brave News
   2. In portrait mode, scroll news feed
   3. Disable Brave News in settings
   4. Confirm brave news is not shown
   5. Change orientation to landscape
   6. Observe

## Actual result 
News feed displayed again

https://user-images.githubusercontent.com/17885425/164350366-fa6179df-67af-4ccd-948a-72fc80500ae5.mp4

## Expected result
News feed should not show

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung Galaxy Tab S7, Samsung GS 21
   - Android version: 12
   
## Brave version
1.38.103, 1.39.73

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
Removing from the `1.38.x` milestone as the above isn't labelled as `release/blocking`.

**Comment by kjozwiak** [comment]
@brave/qa-team some additional STR/Cases outlined via https://github.com/brave/brave-core/pull/13203#issuecomment-1123069843 which basically double checks and ensured that the opt-in card is working as expected in various scenarios.

**Comment by kjozwiak** [comment]
Should wait to QA the above till https://github.com/brave/brave-browser/issues/22778 as been resolved and the opt-in card has been enabled via the NTP via `1.38.x`.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+` running `Android 12` using the following build(s):

```
Brave | 1.38.118 Chromium: 101.0.4951.67 (Official Build) (64-bit)
--- | ---
Revision | 8888ee7a24e2c36661ddb9536c35b7d4852a3a98-refs/branch-heads/4951@{#1230}
OS | Android 12; Build/SP1A.210812.016
```

Went through the STR/Cases outlined via https://github.com/brave/brave-browser/issues/22444#issue-1210372154 and ensured that Brave News doesn't re-appear once disabled when changing the device orientation.

https://user-images.githubusercontent.com/2602313/168518621-4c653d93-dd28-43fd-9d68-887854f5a15d.mp4

Verification **PASSED** on `Samsung Galaxy Tablet A` running `Android 11` using the following build(s):

```
Brave | 1.38.118 Chromium: 101.0.4951.67 (Official Build) (64-bit)
--- | ---
Revision | 8888ee7a24e2c36661ddb9536c35b7d4852a3a98-refs/branch-heads/4951@{#1230}
OS | Android 11; Build/RP1A.200720.012
```

Went through the STR/Cases outlined via https://github.com/brave/brave-browser/issues/22444#issue-1210372154 and ensured that Brave News doesn't re-appear once disabled when changing the device orientation.

https://user-images.githubusercontent.com/2602313/168518873-0b688d4c-9f6f-45e5-ba38-702aaf3c0e11.mp4
