### ISSUE TITLE
CAPTCHA not being displayed within rewards panel when initiated via `brave://rewards`

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#22447]
## Description 

CAPTCHA isn't being launched via the rewards panel when initiated using `brave://rewards`. Once you've dismissed the initial `Claim Rewads` button/modal that appears within the panel, you don't be able to claim your rewards via `brave://settings` due to the CAPTCHA not appearing in the panel.

## Steps to Reproduce

   1. launch brave using `--rewards=staging=true --brave-ads-staging`
   2. click on the rewards panel and run through the onboarding
   3. once you've stepped through all the onboarding screens, tap in `X` to dismiss the `Claim Rewards` modal
   4. once dismissed, go into `brave://rewards` and attempt to claim the reward/grant

## Actual result:

https://user-images.githubusercontent.com/2602313/164362810-19064114-7326-4f58-bad6-836dbfb1a328.mp4

## Expected result:

https://user-images.githubusercontent.com/2602313/164362821-44c150ed-8f3a-47c2-9c7f-7debcf03a469.mp4

## Reproduces how often: 

100% reproducible when using the STR/Cases outlined above.

## Brave version (brave://version info)

```
Brave | 1.39.73 Chromium: 101.0.4951.34 (Official Build) nightly (64-bit)
-- | --
Revision | 8f93af5d759634c5256b65997dedd138ed60992f-refs/branch-heads/4951@{#710}
OS | Windows 11 Version 21H2 (Build 22000.613)
```

```
Brave | 1.39.72 Chromium: 101.0.4951.34 (Official Build) nightly (x86_64)
--- | ---
Revision | 8f93af5d759634c5256b65997dedd138ed60992f-refs/branch-heads/4951@{#710}
OS | macOS Version 12.3.1 (Build 21E258)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `No` (need to wait for a `1.39.x` BETA to check)
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @emerick @Miyayes @LaurenWags @zenparsing

**Comment by GeetaSarvadnya** [comment]
Reproduced the issue in Windows 10 x64 

```

Brave | 1.39.73 Chromium: 101.0.4951.34 (Official Build) nightly (64-bit)
-- | --
Revision | 8f93af5d759634c5256b65997dedd138ed60992f-refs/branch-heads/4951@{#710}
OS | Windows 10 Version 21H2 (Build 19044.1645)

```

**Comment by kjozwiak** [comment]
The above requires `1.39.80` or higher for `1.39.x` verification.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using

Brave | 1.39.83 Chromium: 101.0.4951.41 (Official Build) beta (64-bit)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | Windows 11 Version 21H2 (Build 22000.613)

Test Case 1: Verified CAPTCHA displayed when initiated from brave://rewards after dismissing initial `Claim Tokens` modal
<details>

- Install 1.39.83
- Launch brave using --rewards=staging=true --brave-ads-staging
- Click `Skip welcome tour`
- Click `BAT` icon in the URL bar to open onboarding modal
- Click `Start using Brave Rewards` to complete onboarding process
- Click `X` to dismiss the `A token grant is available/Claim Tokens` modal
- Go to `brave://rewards` and click blue `CLAIM` button above rewards panel
- `CAPTCHA` is displayed and claimed the UGP grant

![2022-04-27_16h24_42](https://user-images.githubusercontent.com/98358127/165647332-3b356c05-5c58-4f4e-9368-b81d024fe748.gif)

</details>

Test Case 2: Verified `CAPTCHA` displayed when clicked on `Claim Tokens` button in the rewards panel
<details>

- New profile
- Launch brave with using --rewards=staging=true --brave-ads-staging
- Click Skip welcome tour
- Click `BAT` icon in the URL bar to open onboarding modal
- Click `Start using Brave Rewards` to complete onboarding process
- Click `Claim Tokens` button in the modal
- `CAPTCHA` is displayed and claimed the UGP grant

ex1|ex2|ex3|ex4|ex5|ex6|ex7|ex8
---|---|---|---|---|---|---|---
<img width= "950" alt="SS1" src="https://user-images.githubusercontent.com/98358127/165646355-b0cbd99f-8d11-4f7b-9f28-30ce3bc5c761.png">|<img width= "950" alt="SS2" src="https://user-images.githubusercontent.com/98358127/165632021-cdf29e76-6ab7-4353-8dea-1c9a7067d292.png">|<img width= "950" alt="SS3" src="https://user-images.githubusercontent.com/98358127/165632135-bff22a56-1a03-4cc3-a008-99ec24e4b6b6.png">|<img width= "950" alt="SS4" src="https://user-images.githubusercontent.com/98358127/165632259-7a5a29da-4876-45fe-8188-787d357f8b36.png">|<img width= "950" alt="SS5" src="https://user-images.githubusercontent.com/98358127/165632336-14016e33-6eb7-418f-b90a-691f2fbfe5cb.png">|<img width= "950" alt="SS6" src="https://user-images.githubusercontent.com/98358127/165632514-fe1d7d63-01d2-4eba-810a-523a1fbebb46.png">|<img width= "950" alt="SS7" src="https://user-images.githubusercontent.com/98358127/165632601-185040c0-b342-452a-8e21-c43885ebe2a1.png">|<img width= "950" alt="SS4" src="https://user-images.githubusercontent.com/98358127/165632259-7a5a29da-4876-45fe-8188-787d357f8b36.png">

</details>

Test Case 3: Complete onboarding from brave://rewards and click `Claim` button to launch `CAPTCHA` in the page
<details>

- New profile
- Launch brave with using --rewards=staging=true --brave-ads-staging
- Navigate to brave://rewards
- Click `Start using Brave Rewards` on the rewards page to complete onboarding process
- Click blue `CLAIM` button above rewards panel
- `CAPTCHA` is displayed and claimed the UGP grant

ex1|ex2|ex3|ex4|ex5|ex6
---|---|---|---|---|---
<img width= "950" alt="SS1" src="https://user-images.githubusercontent.com/98358127/165634989-3e31d844-4c88-4b4b-ac64-95311bd8384a.png">|<img width= "950" alt="SS2" src="https://user-images.githubusercontent.com/98358127/165635615-6d37e6e4-4f4a-4017-9eb8-e48858ab082b.png">|<img width= "950" alt="SS3" src="https://user-images.githubusercontent.com/98358127/165635682-df8dbbab-b78d-4a49-8358-df84c9a1f04d.png">|<img width= "950" alt="SS4" src="https://user-images.githubusercontent.com/98358127/165635691-0a52db37-3272-4a52-96dd-08b025d1b80c.png">|<img width= "950" alt="SS5" src="https://user-images.githubusercontent.com/98358127/165635686-987ed1f9-b198-4d6b-be77-c283720a4c52.png">|<img width= "950" alt="SS5" src="https://user-images.githubusercontent.com/98358127/165635687-65118759-a5ff-4e37-ba70-f7a41ec95ac9.png">|<img width= "950" alt="SS4" src="https://user-images.githubusercontent.com/98358127/165632259-7a5a29da-4876-45fe-8188-787d357f8b36.png">

</details>

Test Case 4: Launch onboarding from `Brave rewards` widget in NTP and initiate `CAPTCHA` via brave://rewards 
<details>

- New profile
- Launch brave using --rewards=staging=true --brave-ads-staging
- Complete welcome tour
- Click Start using Rewards button on the `Brave rewards` widget
- Click `Start using Brave Rewards` to complete onboarding process
- Click `X` to dismiss the `Claim Tokens` modal
- Go to `brave://rewards` and click blue `CLAIM` button above rewards panel
- `CAPTCHA` is displayed and was able to claim the UGP grant

ex1|ex2|ex3|ex4|ex5|ex6|ex7|ex8|ex9
---|---|---|---|---|---|---|---|---
<img width="955" alt="ss1" src="https://user-images.githubusercontent.com/98358127/165639583-9420eb39-98f3-4679-a534-1ee6d9639775.png">|<img width="955" alt="ss2" src="https://user-images.githubusercontent.com/98358127/165639604-d27b3adf-1f79-4159-a667-73703bcc641a.png">|<img width="955" alt="ss3" src="https://user-images.githubusercontent.com/98358127/165639709-bbd80371-b200-492e-b1cb-98b9ea18e883.png">|<img width="955" alt="ss54" src="https://user-images.githubusercontent.com/98358127/165639852-f5924749-969a-4404-a8e1-9f1f78e22ca1.png">|<img width="955" alt="ss5" src="https://user-images.githubusercontent.com/98358127/165639955-13c06334-3fe9-443c-879a-c0e6fd78ceae.png">|<img width="955" alt="ss6" src="https://user-images.githubusercontent.com/98358127/165640021-bc8c09e4-7261-4441-91c1-d6ec15706b14.png">|<img width="955" alt="ss7" src="https://user-images.githubusercontent.com/98358127/165640106-48604b79-f72c-46bc-a518-3d4766e80e3b.png">|<img width="955" alt="ss8" src="https://user-images.githubusercontent.com/98358127/165640182-8f3b1680-a4fc-4e63-9937-3d442d95da9c.png">|<img width="955" alt="ss9" src="https://user-images.githubusercontent.com/98358127/165641541-318a0680-c767-4047-bce2-2324c6c00105.png">
</details>

Test Case 5: Launch onboarding from `Brave rewards box` in in `NTPSI` and initiate `CAPTCHA` via brave://rewards 
<details>

- New profile
- Launch brave with using --rewards=staging=true --brave-ads-staging
- Open a NTP and refresh to view NTPSI 
- Click `Start using Rewards` Brave Rewards box
- Click `Start using Brave Rewards` to complete onboarding process
- Click `X` to dismiss the `Claim Tokens` modal
- Go to `brave://rewards` and click blue `CLAIM` button above rewards panel
- `CAPTCHA` is displayed and was able to claim the UGP grant

ex1|ex2|ex3|ex4|ex5|ex6|ex7
---|---|---|---|---|---|---
<img width="955" alt="ss1" src="https://user-images.githubusercontent.com/98358127/165640859-24040c5b-07a3-4bc6-ae3d-5f3eab2cbee9.png">|<img width="955" alt="ss2" src="https://user-images.githubusercontent.com/98358127/165640926-747b81c5-c7bc-4324-bd86-cc66746c4acc.png">|<img width="955" alt="ss3" src="https://user-images.githubusercontent.com/98358127/165640979-e6799ec9-f531-40ff-ae62-f439a22c6e58.png">|<img width="955" alt="ss4" src="https://user-images.githubusercontent.com/98358127/165641081-63a60c35-320e-47fa-8123-afe06335496f.png">|<img width="955" alt="ss5" src="https://user-images.githubusercontent.com/98358127/165641369-77060325-cb9d-45db-a9c8-505adb478322.png">|<img width="955" alt="ss6" src="https://user-images.githubusercontent.com/98358127/165641427-f8aabd92-c129-4459-ac2e-1987f86cfcdd.png">|<img width="955" alt="ss7" src="https://user-images.githubusercontent.com/98358127/165641541-318a0680-c767-4047-bce2-2324c6c00105.png">

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.39.86 Chromium: 101.0.4951.41 (Official Build) beta (x86_64)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | macOS Version 12.3.1 (Build 21E258)
```

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.39.100 Chromium: 101.0.4951.61 (Official Build) beta (64-bit)
-- | --
Revision | 3b3633b32c491b4cba5fd7df3c7c0f628547cbcc-refs/branch-heads/4951@{#1189}
OS | Ubuntu 18.04 LTS

Test Case 1: Verified CAPTCHA displayed when initiated from brave://rewards after dismissing initial `Claim Tokens` modal
<details>

- Install 1.39.x
- Launch brave using --rewards=staging=true --brave-ads-staging
- Click `Skip welcome tour`
- Click `BAT` icon in the URL bar to open onboarding modal
- Click `Start using Brave Rewards` to complete onboarding process
- Click `X` to dismiss the `A token grant is available/Claim Tokens` modal
- Go to `brave://rewards` and click blue `CLAIM` button above rewards panel
- `CAPTCHA` is displayed and solved to claim the grant

![image](https://user-images.githubusercontent.com/34715963/167845670-4afed8f2-ac8a-46c3-affa-6211271f0af2.png)
![image](https://user-images.githubusercontent.com/34715963/167845729-b9a264b7-8fb9-4411-aa44-4ce968365eed.png)


</details>

Note: Below are regression test cases to test all flows.

Test Case 2: Verified `CAPTCHA` displayed when clicked on `Claim Tokens` button in the rewards panel
<details>

- New profile
- Launch brave using --rewards=staging=true --brave-ads-staging
- Click `Skip welcome tour`
- Click `BAT` icon in the URL bar to open onboarding modal
- Click `Start using Brave Rewards` to complete onboarding process
- Click `Claim Tokens` button in the modal
- `CAPTCHA` is displayed and solved to claim the grant

![image](https://user-images.githubusercontent.com/34715963/167846608-753bddb0-1586-46ff-9c15-1952e6aab4d3.png)
![image](https://user-images.githubusercontent.com/34715963/167846700-1728a91e-edf2-48c6-a302-65d63cdbf311.png)

</details>

Test Case 3: Complete onboarding from brave://rewards and click `Claim` button to launch `CAPTCHA` in the rewards page
<details>

- New profile
- Launch brave with using --rewards=staging=true --brave-ads-staging
- Navigate to brave://rewards
- Click `Start using Brave Rewards` on the rewards page to complete onboarding process
- Click blue `CLAIM` button above rewards panel
- `CAPTCHA` is displayed and solved to claim the grant

![image](https://user-images.githubusercontent.com/34715963/167847212-4073c58c-163b-499e-aedc-d3cc6dd4a5ed.png)
![image](https://user-images.githubusercontent.com/34715963/167847272-31da4810-3f93-4405-b730-8b89d1a6b6cc.png)


</details>

Test Case 4: Launch onboarding from `Brave rewards` widget in NTP and initiate `CAPTCHA` via brave://rewards 
<details>

- New profile
- Launch brave using --rewards=staging=true --brave-ads-staging
- Complete welcome tour
- Click Start using Rewards button on the `Brave rewards` widget
- Click `Start using Brave Rewards` to complete onboarding process
- Click `X` to dismiss the `Claim Tokens` modal
- Go to `brave://rewards` and click blue `CLAIM` button above rewards panel
- `CAPTCHA` is displayed and solved to claim the grant

![image](https://user-images.githubusercontent.com/34715963/167847828-be393a3d-9d17-4842-8f9b-6accdd0c33c3.png)
![image](https://user-images.githubusercontent.com/34715963/167847868-dbb7c5fb-4457-44eb-a433-173143f447bd.png)


</details>

Test Case 5: Launch onboarding from `Brave rewards box` in `NTPSI` and initiate `CAPTCHA` via brave://rewards 
<details>

- New profile
- Launch brave with using --rewards=staging=true --brave-ads-staging
- Open a NTP and refresh to view NTPSI 
- Click `Start using Rewards` Brave Rewards box
- Click `Start using Brave Rewards` to complete onboarding process
- Click `X` to dismiss the `Claim Tokens` modal
- Go to `brave://rewards` and click blue `CLAIM` button above rewards panel
- `CAPTCHA` is displayed and solved to claim the grant

![image](https://user-images.githubusercontent.com/34715963/167848485-c2316ffe-799d-401c-95ba-10ddde762882.png)
![image](https://user-images.githubusercontent.com/34715963/167848730-21f18273-aa71-4ef2-95af-b49851ce8f20.png)
![image](https://user-images.githubusercontent.com/34715963/167848769-aa53b20b-b65a-4717-b01c-3f2904d7ecab.png)


</details>
