### ISSUE TITLE
NTP top site icons not consistent with original preloaded after visiting

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#22445]
## Description 
The initial top site vector icons that are preloaded on first launch will be replaced when visiting the top site url. The icons are replaced with what seems like a bitmap icon and it does not look consistent with the original. The url description also changes from the domain to a description of the url. This impacts the wikipedia and espn favicons especially and looks less polished.

This is less noticeable in the new design with the top sites being placed on the homepage. 

## Steps to reproduce 

   1. Clean install
   2. Open NTP
   3. Observe top site icons
   4. Click on wikipedia top site to load the page
   5. Return home
   6. Open new tab

## Actual result 
![Screen Shot 2022-04-20 at 4 45 26 PM](https://user-images.githubusercontent.com/17885425/164351942-449ff0c0-0e03-4274-b8f5-342f94a0f227.png)

## Expected result
![Screen Shot 2022-04-20 at 4 40 45 PM](https://user-images.githubusercontent.com/17885425/164351961-72d0ab19-d040-419a-b495-bf6d071e285f.png)

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung Galaxy Tab S21, Galaxy Tab S7 
   - Android version: 12
   
## Brave version
1.38.103

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by deeppandya** [comment]
@Uni-verse i think this issue is irrelavant because of https://github.com/brave/brave-core/pull/13012. can you confirm ?

**Comment by srirambv** [comment]
Closing in favour of https://github.com/brave/brave-browser/issues/22198
