### ISSUE TITLE
Unable to swipe homepage widget with brave news enabled in portrait mode [Tablet]

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#22443]
## Description 
With Brave News enabled, user is unable to swipe between the widgets on homepage. This works in landscape orientation perhaps because the widget is larger. 

## Steps to reproduce 

   1. Clean install
   2. Enable Brave News
   3. Using tablet in portrait orientation, swipe between stats and top sites

## Actual result 
Unable to swipe between widgets

![Screen Shot 2022-04-20 at 5 47 09 PM](https://user-images.githubusercontent.com/17885425/164349608-63d8fd97-a827-4c36-a68a-73627c12ec2e.png)

## Expected result
Should be able to switch the widgets by swiping vertically

## Issue reproduces how often 
Easily 100% 

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Galaxy Tab S7
   - Android version: 12
   
## Brave version
1.38.103, Chromium 100.0.4896.127

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
Removing from the `1.38.x` milestone as the above isn't labelled as `release/blocking`.

**Comment by kjozwiak** [comment]
Closing this one as this won't be valid once we uplift https://github.com/brave/brave-core/pull/12808 into `1.38.x` once @deeppandya fixes the issues with `CI`. @Uni-verse shouldn't see the above using `1.39.x` & `1.40.x` at this point.
