### ISSUE TITLE
Monthly Contribution Dropdown in Wallet Panel should retain value

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#2245]
This should call the functions `SaveRecurringDonation` and `RemoveRecurring`. The former should called when a non-0 value is set, and the latter when 0 is set.

## Steps to Reproduce

   1. Enable Brave Rewards
   2. Navigate to a site such as `brave.com`
   3. Bring up the wallet panel.
   4. Change monthly contribution amount to '5.0'
   5. Close and re-open panel

## Actual result:
New value is not returned, is 0.0

## Expected result:
Dropdown should be 5.0

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
Hope we can land this before `0.58.x` moves into `beta` or this will need to get uplifted 👍

**Comment by bbondy** [comment]
Reverted due to failing unit tests, re-opening.
https://github.com/brave/brave-core/commit/f77acbe1a00056ab14e4a069d92b6931e221442c

**Comment by GeetaSarvadnya** [comment]
Verification passed on 


Brave | 0.65.93 Chromium: 74.0.3729.131 (Official Build) beta (64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Windows 10 OS Build 17134.523




- Verified the test plan from https://github.com/brave/brave-core/pull/957
- Verified Twitch, YT and websites
