### ISSUE TITLE
[ Issue ] Brave Block Element Picker + Dark Reader

### ISSUE THREAD

**Issue by 8227846265** [brave/brave-browser#22450]
## Description 
If you have Dark Reader enabled on Brave Browser and you try to block an element with the Brave Ad Element Picker. The whole screen will become white like this.

![image](https://user-images.githubusercontent.com/66582769/164377068-c5724b0a-4cd5-42ba-948f-ba946ae171a8.png)

## Steps to Reproduce

   1. Install [Dark Reader](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh)
   2. Browse any website while Dark Reader is turned on
   3. Then Right click > Brave > Block Element

## Actual result:
![image](https://user-images.githubusercontent.com/66582769/164377068-c5724b0a-4cd5-42ba-948f-ba946ae171a8.png)

## Expected result:
The screen is not all white

## Reproduces how often: 
All the time

## Brave version (brave://version info)
[Version 1.37.116 Chromium: 100.0.4896.127 (Official Build) (64-bit)](https://brave.com/latest/)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Don't know
- Can you reproduce this issue with the nightly channel? Don't know

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by BunnyTheLifeguard** [comment]
A bit sad that the extension devs don't see it as "their issue", since I tried alternative extensions that do the same but don't cause this problem 😕

**Comment by candroid-man** [comment]
I am also experiencing this issue, and it is very very annoying
