### ISSUE TITLE
Performance degradation caused by solana provider script injection

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#22468]
This blocks the enabling of solana provider feature flag.
See https://bravesoftware.slack.com/archives/C3T9S9WKD/p1650536839273249 for more details.

**Comment by darkdh** [comment]
<img width="931" alt="Screen Shot 2022-04-21 at 09 41 07" src="https://user-images.githubusercontent.com/11330831/164510716-4e47dd08-d155-4515-b407-0208075d69a3.png">
