### ISSUE TITLE
Importer fails for legacy Crypto Wallets

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#22461]
## Description 

Importer fails for legacy Crypto Wallets

## Steps to Reproduce

   1. On a new profile create a legacy wallet by enabling flags on Nightly 
   2. Switch to `Brave Wallet` from settings
   3. No importer is shown

## Actual result:

https://user-images.githubusercontent.com/17010094/164441801-616770ce-0cf4-46de-bf6b-e3319392896b.mov

## Expected result:
Show importer similar to MM

https://user-images.githubusercontent.com/17010094/164444637-62d05748-9839-4a6c-acb2-4f0554556055.mov

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html><head></head>
<body>

Brave | 1.40.1 Chromium: 101.0.4951.41 (Official Build) nightly (64-bit)
-- | --
Revision | `93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}`
OS | Windows 11 Version 22H2 (Build 22598.200)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes on `1.37.116`
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @jamesmudgett @darkdh @Douglashdaniel @onyb

**Comment by kjozwiak** [comment]
The above will require `1.38.106` or higher for `1.38.x` verification.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">  1.38.106 Chromium: 101.0.4951.41 (Official Build)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22598.200)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td>
      </td>
      <td colspan=3>
         <ul>
         <li>Verified steps from issue description</li>
         <li>Verified Legacy CW is detected and is allowed to import</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/165072486-120b37ab-35b4-4cd5-89a1-dddf10a466e8.mp4>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/165072299-2bbd6232-5818-47aa-839d-6056d1e96f42.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/165072165-061dede3-e313-46c8-9152-777bdb251bca.mov>
      </td>
   </tr>
</table>
