### ISSUE TITLE
Removing Eth testnet tokens removes the mainnet Eth token and doesn't list anymore

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#22463]
## Description 

Removing Eth testnet tokens removes the mainnet Eth token and doesn't list anymore

## Steps to Reproduce

   1. Restore a wallet with Ether balance on both main and testnet
   2. Click on visible asset and disable any of the test net Ethereum token
   3. All Ethereum tokens for all network is disabled
   4. Save the visible list
   5. Ethereum on mainnet is also removed
   6. Click on visible asset again and search for Ethereum, only testnets are listed not the mainnet 

## Actual result:

https://user-images.githubusercontent.com/17010094/164458790-8365714b-f140-450d-ba4f-ff567903f205.mov

## Expected result:
Should only remove the token that is unchecked

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.38.104 Chromium: 101.0.4951.41 (Official Build) (arm64)
-- | --
Revision | `93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? No but on RC builds 
- Can you reproduce this issue with the beta channel? No, checked on `1.39.76`
- Can you reproduce this issue with the nightly channel? No, checked on `1.40.1`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @jamesmudgett @Douglashdaniel @josheleonard

**Comment by Douglashdaniel** [comment]
Fixed by https://github.com/brave/brave-core/pull/13107 and uplifted.

**Comment by kjozwiak** [comment]
> Fixed by [brave/brave-core#13107](https://github.com/brave/brave-core/pull/13107) and uplifted.

As per the above, closing this off as this was fixed via https://github.com/brave/brave-core/pull/12955 which was uplifted into `1.38.x` via https://github.com/brave/brave-core/pull/13107.

**Comment by srirambv** [comment]
Verification passed as part of https://github.com/brave/brave-browser/issues/22159#issuecomment-1109655437. 
- Verified unchecking testnet token doesn't cause the mainnet token to be removed as well
- Verified each network token can be individually unchecked/checked
- Encountered [#22556](https://github.com/brave/brave-browser/issues/22556)
