### ISSUE TITLE
Brave News ads should not be removed when they go off the screen

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#22476]
## Description 
Brave News ads are deleted from the feed once they go off the top of the screen. Ads should live for the lifetime of the feed and once the feed goes out of scope we should call `AdsService::PurgeOrphanedAdEventsForType`

## Steps to reproduce 

   1. Slowly scroll past a Brave News Ad without stopping so that it goes off the top of the screen

## Actual result 
The ad is removed from the feed

## Expected result
The ad should not be removed from the feed

## Issue reproduces how often 
Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
1.37.x

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by btlechowski** [comment]
Verification passed on Brave v1.38.119 on Samsung s7 (Android 8.0).

Verified ad do not disappear after going off screen
![Screenshot_20220517-202243_Brave](https://user-images.githubusercontent.com/34715963/168884514-af823e87-ae9f-4bf5-91b0-d3f608d3a621.jpg)|![Screenshot_20220517-202249_Brave](https://user-images.githubusercontent.com/34715963/168884517-4e16bcf9-aeb0-497c-a3c4-6642856bd539.jpg)|![Screenshot_20220517-202254_Brave](https://user-images.githubusercontent.com/34715963/168884518-4aa415dc-2244-44b0-aaea-659f118a20d1.jpg)|![Screenshot_20220517-202303_Brave](https://user-images.githubusercontent.com/34715963/168884519-908c0b23-ff68-44d1-9410-d8968dd4d8f9.jpg)|![Screenshot_20220517-202309_Brave](https://user-images.githubusercontent.com/34715963/168884520-575f11fb-def2-4160-936e-fc0564252b73.jpg)|![Screenshot_20220517-202320_Brave](https://user-images.githubusercontent.com/34715963/168884521-44a7504a-7f2b-4eaa-8cf6-9ace59b883b2.jpg)
--|--|--|--|--|--

**Comment by btlechowski** [comment]
Verification passed on Brave v1.38.119  on Samsung Galaxy Tab S5e (Android 11.0)

Verified ad do not disappear after going off screen

![Screenshot_20220517-210409_Brave](https://user-images.githubusercontent.com/34715963/168893379-26209f1d-ee9a-4535-ac20-7db2226402e0.jpg)|![Screenshot_20220517-210425_Brave](https://user-images.githubusercontent.com/34715963/168893383-d80d2f1f-0438-4a58-80c9-d8dd57068b79.jpg)|![Screenshot_20220517-210431_Brave](https://user-images.githubusercontent.com/34715963/168893384-d7a69a2a-26a4-4d23-beaa-5a3c6da65af7.jpg)|![Screenshot_20220517-210436_Brave](https://user-images.githubusercontent.com/34715963/168893386-41c1fe5e-49b5-4952-8db9-ea8c02f121a9.jpg)|![Screenshot_20220517-210442_Brave](https://user-images.githubusercontent.com/34715963/168893388-d187e1eb-9a22-4ebd-9a07-e8ec2470b4f2.jpg)
--|--|--|--|--
