### ISSUE TITLE
Brave Wallet provider block future requests from a website

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#22471]
<img width="1074" alt="Screen Shot 2022-04-21 at 09 19 46" src="https://user-images.githubusercontent.com/11330831/164507626-03d41730-d222-43ef-bbf0-5ea373eaa652.png">
<img width="730" alt="Screen Shot 2022-04-21 at 09 21 52" src="https://user-images.githubusercontent.com/11330831/164507632-6dbbfd08-863e-4814-bf4a-1ab2d2e379af.png">
With the content setting setup, we should be able to rejected all requests from github.com but our brave wallet permission manager doesn't respect it

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.43.81 Chromium: 104.0.5112.102 (Official Build) (64-bit)
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | Linux

- Verified steps from [brave/brave-core#14149](https://github.com/brave/brave-core/pull/14149)
- Verified on both settings and panel 
- Encountered [#24974](https://github.com/brave/brave-browser/issues/24974)

Ethereum | Solana 
-- | --
<video src=https://user-images.githubusercontent.com/17010094/186730263-5faf6678-fbc8-45e5-b25a-1c083e446701.mp4> | <video src=https://user-images.githubusercontent.com/17010094/186730916-5c800cf4-6d59-4803-af41-6c6a00929ad3.mp4>

Ethereum (Panel)

Connect| Connected | Blocked 
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/186729557-529bbd4f-53b6-4a8d-9898-aae06f7e41b2.png) | ![image](https://user-images.githubusercontent.com/17010094/186729617-a03d9ee2-d80e-45c1-a851-c10dae5f9d9c.png) | ![image](https://user-images.githubusercontent.com/17010094/186729436-391f8db6-f211-447a-a65a-97e7e1cc58a6.png)

Solana (Panel)

Connected | Disconnected | Blocked 
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/186729822-4bc15978-cefa-4b9b-96ab-02da2f8dc230.png) | ![image](https://user-images.githubusercontent.com/17010094/186729701-09face8f-df41-46ce-9981-57a8bad1f789.png) | ![image](https://user-images.githubusercontent.com/17010094/186730046-990ae591-467d-43d4-afd1-2ac428f6897a.png)

------------------------
Verification passed on

Brave | 1.43.81 Chromium: 104.0.5112.102 (Official Build) (64-bit)
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | Windows 11 Version 21H2 (Build 22000.795)

- Verified steps from [brave/brave-core#14149](https://github.com/brave/brave-core/pull/14149)
- Verified on both settings and panel 
- Encountered [#24974](https://github.com/brave/brave-browser/issues/24974)

Ethereum | Solana 
-- | --
<video src=

https://user-images.githubusercontent.com/17010094/186732733-25a7668e-b2d8-44a9-b693-1a28f066d9da.mp4

> | <video src=https://user-images.githubusercontent.com/17010094/186732283-296bbb1b-0ae4-4ad9-91f5-028f0e3ef1f4.mp4>

Ethereum (Panel)

Connect| Connected | Blocked 
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/186732908-ab914773-6a6a-487b-8c3d-2fc633964f4d.png) | ![image](https://user-images.githubusercontent.com/17010094/186732856-4e3d105c-bf18-42e9-988a-11c66f0bf0ee.png) | ![image](https://user-images.githubusercontent.com/17010094/186733016-508de436-db4f-4126-a3b5-d5f172b48679.png)


Solana (Panel)

Connected | Disconnected | Blocked 
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/186733146-ac64a5ed-309b-4a0a-8e37-10ec82997642.png) | ![image](https://user-images.githubusercontent.com/17010094/186733058-602b481f-e1d9-46aa-9155-c52b42df7be2.png) | ![image](https://user-images.githubusercontent.com/17010094/186733534-0d4964b1-1674-4173-8d04-9fb2376a09c5.png)

------------------------
Verification passed on

Brave | 1.43.81 Chromium: 104.0.5112.102 (Official Build) (arm64)  
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [brave/brave-core#14149](https://github.com/brave/brave-core/pull/14149)
- Verified on both settings and panel 
- Encountered [#24974](https://github.com/brave/brave-browser/issues/24974)

Ethereum | Solana 
-- | --
<video src=https://user-images.githubusercontent.com/17010094/186690052-b562b6dc-03c0-46ff-a81f-a139772b0e4e.mov> | <video src=https://user-images.githubusercontent.com/17010094/186690096-12c0d3eb-1000-4355-b45c-39ef1fa7d339.mov>

Ethereum (Panel)

Connect| Connected | Blocked 
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/186728054-9e4abe90-c17e-417e-9c3a-dc12c636b4c7.png) | ![image](https://user-images.githubusercontent.com/17010094/186728122-815aaf72-0b7f-4b54-af53-6d5690f73aa3.png) | ![image](https://user-images.githubusercontent.com/17010094/186728135-74365c1b-0062-4218-a3a7-a7a3ab2f522a.png)

Solana (Panel)

Connected | Disconnected | Blocked 
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/186727570-c26b2f5b-dfc0-4dc2-898b-218274c88d02.png) | ![image](https://user-images.githubusercontent.com/17010094/186727615-9679736f-e4e2-41d1-aba9-c86884337243.png) | ![image](https://user-images.githubusercontent.com/17010094/186727636-08490dd8-3869-4a24-8935-d4b7228da2f4.png)
