### ISSUE TITLE
omnibox color/styling is incorrect in dark theme - Chromium 101

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#22479]
## Description 

The macOS omnibox color/styling is incorrect in normal window when using the dark theme. It is the dark purple color, used in private/Tor/guest windows. Should be the same as 1.37.x.

It is fine on 1.37.116 (Chromium 100) and incorrect on 1.38.104 (Chromium 101)

## Steps to Reproduce

   1. Open 1.38.104 using dark theme
   2. Look at omnibox
   3. Check light theme, that appears to be ok

## Actual result:

Example | Example
----- | -----
<img width="1200" alt="1" src="https://user-images.githubusercontent.com/28145373/164549870-c3ccedbc-2af9-4c24-8b55-8c8fd11d5c80.png"> | <img width="1193" alt="2" src="https://user-images.githubusercontent.com/28145373/164549881-d57ebe64-6d10-4b5b-8f03-373dc5a1f1b0.png">

## Expected result:

Example | Example
----- | -----
<img width="1194" alt="3" src="https://user-images.githubusercontent.com/28145373/164549898-2cb00fae-188a-45a0-9ab9-61796f34946c.png"> | <img width="1193" alt="4" src="https://user-images.githubusercontent.com/28145373/164549909-cb6766b2-4bdd-44c7-8d66-150e2df9482f.png">

## Reproduces how often: 

easily

## Version/Channel Information:

- Can you reproduce this issue with the current release?  1.37.x no, 1.38.x yes
- Can you reproduce this issue with the beta channel? 1.39.x yes
- Can you reproduce this issue with the nightly channel? 1.40.x yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron @brave/legacy_qa

**Comment by stephendonner** [comment]
Can also reproduce using 1.38.104 on Windows 10; 1.37.116 is fine.

1.37.116 | 1.38.104
----------|----------
![image (1)](https://user-images.githubusercontent.com/387249/164554186-384a2303-76a1-46ab-a89e-431311986e22.png) | ![image](https://user-images.githubusercontent.com/387249/164554209-20cd6a76-4a86-4b62-a278-c1f907560be5.png)

**Comment by simonhong** [comment]
This regression comes from https://chromium-review.googlesource.com/c/chromium/src/+/3472345.
Beforer this change, `GetOmniboxColor()` is called by  `ThemeHelper::GetColor()` whereas it's called by `ThemeHelper::GetDefaultColor()` now.
Then, we get incognito's omnibox color due to our below code at `BraveThemeHelper::GetDefaultColor()`.
```
  // Make sure we fallback to Chrome's dark theme (incognito) for our dark theme
  if (type == dark_mode::BraveDarkModeType::BRAVE_DARK_MODE_TYPE_DARK) {
    incognito = true;
  }

  DCHECK(!is_brave_theme_properties);
  return ThemeHelper::GetDefaultColor(id, incognito, theme_supplier);
```

**Comment by kjozwiak** [comment]
The above will require `1.38.106` or higher for `1.38.x` verification 👍

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.38.106 Chromium: 101.0.4951.41 (Official Build) (x86_64)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | macOS Version 11.6.5 (Build 20G527)

`light` | `dark`
-----|------
<img width="1247" alt="Screen Shot 2022-04-25 at 1 18 00 PM" src="https://user-images.githubusercontent.com/387249/165175222-dd98946e-aac4-4783-ab55-1bafa8deb116.png"> | <img width="1247" alt="Screen Shot 2022-04-25 at 1 18 20 PM" src="https://user-images.githubusercontent.com/387249/165175235-18d0f354-3833-4692-9213-e57b18c02ec4.png">

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.38.106 Chromium: 101.0.4951.41 (Official Build) (64-bit) 
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | Ubuntu 18.04 LTS

Verified test plan from the description

<details>

![image](https://user-images.githubusercontent.com/34715963/165195329-d98bcb99-2e05-4f3b-8f77-c70c245807f0.png)
![image](https://user-images.githubusercontent.com/34715963/165195378-a4e81365-e75c-44c5-9983-7fd6f7fad840.png)

Private Window:
![image](https://user-images.githubusercontent.com/34715963/165195390-a755ad2d-ae83-45b8-8ad3-38a608283966.png)

Private Window with Tor
![image](https://user-images.githubusercontent.com/34715963/165195450-1c239ad8-8de9-4dbc-bc17-5ca17cc9540b.png)

Guest Window
![image](https://user-images.githubusercontent.com/34715963/165195489-52639d3a-bd1a-4db1-bbe0-38bc734a0247.png)

Custom profile
![image](https://user-images.githubusercontent.com/34715963/165195589-6bf70953-09d9-44f4-b5a6-ba22a32114f5.png)


</details>
