### ISSUE TITLE
Add support for Certificate Transparency in Brave

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#22482]
We [currently don't enforce certificate transparency](https://no-sct.badssl.com/) in Brave, unlike [Chrome and Safari](https://certificate.transparency.dev/useragents/).

This is what the interstitial looks like like Chrome:
![screenshot_from_2022-04-20_16-35-17](https://user-images.githubusercontent.com/167821/164551184-6447fef2-da2f-4445-8ce6-aacc270d2b21.png)

It involves the [*PKI metadata* component](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/component_updater/pki_metadata_component_installer.cc), which we enable in Brave, the [`ERR_CERTIFICATE_TRANSPARENCY_REQUIRED_ERROR` error code](https://source.chromium.org/chromium/chromium/src/+/main:net/base/net_error_list.h;l=542-544;drc=4218fffc00d1a23538095afcb0349af57c1fa706) as well as these feature flags:
- https://source.chromium.org/chromium/chromium/src/+/main:net/http/transport_security_state.h;l=399-402;drc=24c62dad2a729f8c0601c46e74959630484b6943
- https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/browser_features.cc;l=143-147;drc=b03884a3a1ffb3ad8ec269590843203db9e7a386
- https://source.chromium.org/chromium/chromium/src/+/main:components/certificate_transparency/ct_features.h;l=14-30;drc=bf4a6f76e26465d23d2d6a0af7e263a3e4f4ada7

Turning on these flags in `brave://flags` doesn't help:
![Screenshot from 2022-04-21 13-55-43](https://user-images.githubusercontent.com/167821/164551365-ef5cf0c3-ba6c-4159-b3e5-62cd77da1f07.png)

**Comment by fmarier** [comment]
From https://source.chromium.org/chromium/chromium/src/+/main:net/docs/certificate-transparency.md?q=CERTIFICATE_TRANSPARENCY_REQUIRED&ss=chromium%2Fchromium%2Fsrc&start=31:

> However, as Google Chrome looks to roll out a more rigorous enforcement of Certificate Transparency, by enforcing that newly-issued certificates are disclosed as a condition of being trusted, the risks to the CA and CT ecosystem significantly increase if embedders implement CT without the ability for reliable, rapid updates, keeping track with ongoing development in the main tree and reliably delivering security updates on the same cadence as Chromium branches and Google Chrome releases.
> 
> For this reason, the CT implementation is undergoing a refactoring to reduce those risks through code and implementation. As a result, **Chromium embedders will NOT have CT enforcement enabled by default, and are NOT encouraged to manually enable it at this time**.

**Comment by fmarier** [comment]
The reason CT enforcement is disabled in Brave is that the RequireCTDelegate [doesn't change the default CT policy](https://source.chromium.org/chromium/chromium/src/+/main:net/http/transport_security_state.cc;l=550;drc=f12eac9342eb88971851d46e31c97af8c2c27c87). This delegate [is set](https://source.chromium.org/chromium/chromium/src/+/main:services/network/network_context.cc;l=2682-2687;drc=11bd5b933cbb3cbd77cc505bfeeb5a57cc2323cb) based on `params_->enforce_chrome_ct_policy` which [is set](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/net/system_network_context_manager.cc;l=785-787;drc=11bd5b933cbb3cbd77cc505bfeeb5a57cc2323cb) based on [`IsCertificateTransparencyEnabled()`](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/net/system_network_context_manager.cc;l=881-901;drc=11bd5b933cbb3cbd77cc505bfeeb5a57cc2323cb).

Removing the `GOOGLE_CHROME_BRANDING` and `OFFICIAL_BUILD` checks:
```
diff --git a/chrome/browser/net/system_network_context_manager.cc b/chrome/browser/net/sys>
index 0269a74140c80..7b72a383bc279 100644
--- a/chrome/browser/net/system_network_context_manager.cc
+++ b/chrome/browser/net/system_network_context_manager.cc
@@ -896,7 +896,8 @@ bool SystemNetworkContextManager::IsCertificateTransparencyEnabled() {
   return true;
 #endif
 #else
-  return false;
+  //return false;
+  return true;
 #endif
 }
```
I was able to make the [test page](https://no-sct.badssl.com/) work.

**Comment by fmarier** [comment]
Before we enable this, we need to ensure that [SCT auditing](https://docs.google.com/document/d/16G-Q7iN3kB46GSW5b-sfH5MO3nKSYyEb77YsM7TMZGE/edit) is turned off and not sending any data.

**Comment by stephendonner** [comment]
## Verification `PASSED` using 

Brave | 1.53.67 Chromium: 114.0.5735.53 (Official Build) beta (x86_64)
-- | --
Revision | c499d7ea22c8b2dba278465a5df7b86a8efa4e64-refs/branch-heads/5735@{#970}
OS | macOS Version 11.7.7 (Build 20G1345)

### Steps:
1. installed `1.53.67`
2. launched Brave
3. opened `https://no-sct.badssl.com` in Brave
4. confirmed the TLS error page with code `NET::ERR_CERTIFICATE_TRANSPARENCY_REQUIRED`
5. opened `https://sct-exempted.bravesoftware.com` in Chrome
6. confirmed the TLS error page `NET::ERR_CERTIFICATE_TRANSPARENCY_REQUIRED`
7. opened `https://sct-exempted.bravesoftware.com` in Brave
8. confirmed that the page loaded fine
9. opened the same page in Chrome
10. confirmed I got the above ERR_CERTIFICATE... page

`no-sct.badssl.com` **Brave** | `no-sct.badssl.com` _Chrome_ | `sct-exempted.bravesoftware.com/` **Brave** | `sct-exempted.bravesoftware.com` _Chrome_
--|--|--|--
<img width="1086" alt="Screen Shot 2023-05-26 at 10 47 21 PM" src="https://github.com/brave/brave-browser/assets/387249/58c77b3a-5db1-401e-a528-68922146ca13"> | <img width="1873" alt="Screen Shot 2023-05-26 at 10 52 54 PM" src="https://github.com/brave/brave-browser/assets/387249/43858972-94f2-45ac-8795-a55551869726"> | <img width="1660" alt="Screen Shot 2023-05-26 at 10 53 59 PM" src="https://github.com/brave/brave-browser/assets/387249/a12e5588-5b77-45c2-9fc8-954dcda13337"> | <img width="1873" alt="Screen Shot 2023-05-26 at 10 54 16 PM" src="https://github.com/brave/brave-browser/assets/387249/923be694-b49a-413e-aa9a-967ced9e4177">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.53.76 Chromium: 114.0.5735.90 (Official Build) beta (64-bit)
-- | --
Revision | 386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}
OS | Windows 11 Version 22H2 (Build 22621.1702)
```

### Steps:
1. installed `1.53.76`
2. launched Brave
3. opened `https://no-sct.badssl.com` in Brave
4. confirmed the TLS error page with code `NET::ERR_CERTIFICATE_TRANSPARENCY_REQUIRED`
5. opened `https://sct-exempted.bravesoftware.com` in Chrome
6. confirmed the TLS error page `NET::ERR_CERTIFICATE_TRANSPARENCY_REQUIRED`
7. opened `https://sct-exempted.bravesoftware.com` in Brave
8. confirmed that the page loaded fine


Brave (step 4)  | Chrome (step 6) | Brave(step 8) 
--- | --- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/8094c49f-11f3-4fc9-a7a2-85635836cff5)|![image](https://github.com/brave/brave-browser/assets/98358127/87152094-5412-497c-916e-7fb28366dd52)|![image](https://github.com/brave/brave-browser/assets/98358127/5eef3f0f-56b4-4388-9ae4-1e65d3110081)

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave 1.53.87 Chromium: 114.0.5735.110 (Official Build) beta (64-bit) 
Revision 1c828682b85bbc70230a48f5e345489ec447373e-refs/branch-heads/5735_90@{#13}
OS Linux
```
