### ISSUE TITLE
Shields v2 broken for IPFS/IPNS schemes

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#22496]
## Description 

Shields broken for IPNS schemes

## Steps to Reproduce

   1. install `1.39.73`
   2. launch Brave
   3. load `ipns://ipfs.io`
   4. click on `Use a Brave local IPFS node`
   5. click on the Shields icon in the URL bar

## Actual result:

Toggle Shields; nothing happens.

<img width="998" alt="Screen Shot 2022-04-22 at 12 23 20 AM" src="https://user-images.githubusercontent.com/387249/164626987-674935ab-a135-42c7-8367-be6f30d43187.png">

## Expected result:

Shields should either work or be disabled.

<img width="1312" alt="Screen Shot 2022-04-22 at 12 25 29 AM" src="https://user-images.githubusercontent.com/387249/164627943-c38998fd-93d1-4333-a6ce-da5cb2720af6.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.40.4 Chromium: 101.0.4951.41 (Official Build) nightly (x86_64)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | macOS Version 12.4 (Build 21F5058e)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `NO`
- Can you reproduce this issue with the beta channel? `YES`
- Can you reproduce this issue with the nightly channel? `YES`

cc @spylogsster @nullhook @MadhaviSeelam @GeetaSarvadnya @rebron @kjozwiak

**Comment by stephendonner** [comment]
Note that this works for `http://docs.ipfs.io.ipns.localhost:48081/concepts/content-addressing/`:

<img width="1592" alt="Screen Shot 2022-04-22 at 1 33 50 AM" src="https://user-images.githubusercontent.com/387249/164650781-5d8377f0-154f-4947-98a7-12e7e3a7cc5a.png">

**Comment by stephendonner** [comment]
also cc @lidel @autonome

**Comment by vadimstruts** [comment]
The IPFS local node and scheme has been [deprecated](https://github.com/brave/brave-browser/issues/37735)

**Comment by kjozwiak** [comment]
> The IPFS local node and scheme has been [deprecated](https://github.com/brave/brave-browser/issues/37735)

Going to move this into https://github.com/brave/brave-browser/milestone/497 as per the above.
