### ISSUE TITLE
Brave Rewards uncollectible and stuck in Android

### ISSUE THREAD

**Issue by chenasraf** [brave/brave-browser#22497]
## Description 

On Android, the rewards page action pops up when clicked, then displays there are unclaimed BAT rewards.

When clicking "claim", an error message is given, and rewards fo not get collected. 

Opening the dialog again brings back all the rewards that are unclaimed, and the process never fixes.

## Steps to reproduce 

   1. Have Brave Rewards BAT to claim
   2. Try to claim using the popup OR settings page
   3. Get an error and fail

## Actual result

![Screenshot_20220422-103751.jpg](https://user-images.githubusercontent.com/167217/164632424-7b1c3edf-579b-4a0b-908d-5fe6916c9fea.jpg)

![Screenshot_20220422-103950.jpg](https://user-images.githubusercontent.com/167217/164632721-2b009f1c-fafe-4b46-98a2-237d7665962f.jpg)

## Expected result

Expected rewards to collect and disappear until the next ones are available.

## Issue reproduces how often 

All the time for me.

## Version/Channel Information:
No idea, I am using current play store version

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Unknown
- Can you reproduce this issue with the current Play Store Nightly version? Unknown

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone (OnePlus 7 Pro)
   - Android version: 11
   
## Brave version
1.37.116

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? Disabling or resetting rewards then trying again causes same problem
- Is the issue reproducible on the latest version of Chrome? N/A

### Additional information

* Happens when Uphold verified OR unverified

**Comment by bsclifton** [comment]
cc: @brave/rewards-support

**Comment by Miyayes** [comment]
@chenasraf Can you download a SafetyNet checker app, and see if your phone passes Android SafetyNet? If it does not, that would be the reason.
