### ISSUE TITLE
Invalid UD domain message sometimes does not match entered domain

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#22499]
https://user-images.githubusercontent.com/168356/164685737-211d1ab4-9d9e-42e7-b191-567814a41c4c.mp4

**Comment by supermassive** [comment]
@Douglashdaniel fyi

**Comment by Douglashdaniel** [comment]
Is no longer an issue after `Wallet V2`, closing as `Invalid`

https://github.com/brave/brave-browser/assets/40611140/9ffdc05e-51b2-4973-8724-4e8611b7ab24
