### ISSUE TITLE
Investigate search result ad handing if when ad was blocked

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#22495]

**Comment by ShivanKaul** [comment]
@aseren would you mind outlining how https://github.com/brave/brave-core/pull/13215 fixes this? Either here or in the PR. I also added a GitHub auto-close keyword to the PR description.

**Comment by aseren** [comment]
@ShivanKaul, changes in the PR https://github.com/brave/brave-core/pull/13215 imply that an ad viewed event will be raised only if javascript sends the ad loaded confirmation request. If the ad was blocked, then confirmation request won't be send and ad viewed event won't be raised.
