### ISSUE TITLE
Can't validate UD wallet address.

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#22498]
No way to get full wallet address when using UD domain.
Need, for example, a tooltip here or something better.
![image](https://user-images.githubusercontent.com/168356/164680073-bb5e5064-0273-4f54-9f94-c1babc942e8f.png)

**Comment by supermassive** [comment]
@Douglashdaniel fyi

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.40.80 Chromium: 102.0.5005.78 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22621.1)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/13210>brave/brave-core#13210</a></li>
         <li>Verified hovering over Account name shows account address in tooltip</li>
         <li>Verified hovering over receiving account name shows receiving account address in tooltip</li>
         <li>Verified account address is shown on token approval prompts</li>
         <li>Verified hovering over an UD name shows full account address in tooltip</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>UD Tooltip, Confirm Transaction Tooltips, Transaction Details Tooltips
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/171377872-55b6eafc-9b5a-4ed5-ad70-8fdf68706015.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/171377893-23472aff-59ce-483b-a4fa-76696b77ce92.mov>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/171377877-e8ba3070-ff10-4b6d-aabd-bc25e8238b1c.mov>
      </td>
   </tr>
   <tr>
      <td>ERC20 Approve Tooltip
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/171377777-1846a3ab-c447-40a0-9d27-0b9281d4c294.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/171377840-e7a2fa62-4be4-4c9b-a26e-7ede4b58338d.mov>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/171377799-1ee46e26-0b08-4df0-baf7-6cf64239e858.mov>
      </td>
   </tr>
</table>
