### ISSUE TITLE
[hackerone] #450097 - Clear history issue

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#2249]
https://hackerone.com/reports/450097
https://github.com/brave/internal/issues/458

**Comment by diracdeltas** [comment]
@jumde you verified that this repros on chrome?

wondering if we should wait for the upstream fix. i commented in h1 asking the reporter to report to chrome if applicable

**Comment by diracdeltas** [comment]
actually here's the chrome issue: https://bugs.chromium.org/p/chromium/issues/detail?id=823071

**Comment by diracdeltas** [comment]
i think we will wait for the fix to https://bugs.chromium.org/p/chromium/issues/detail?id=823071 to be merged upstream and then i will verify that it's in the corresponding brave release

**Comment by tomlowenthal** [comment]
Looks like Chrome has a `#rewrite-leveldb-on-deletion` flag specifically for the fix @mrose17 suggested (if I'm understanding right). Could we use that?

<img width="827" alt="screen shot 2018-12-18 at 1 34 42 pm" src="https://user-images.githubusercontent.com/639937/50184412-e2e74480-02c9-11e9-8421-4eead8f3a458.png">

**Comment by mrose17** [comment]
Winner!

**Comment by fmarier** [comment]
Is this a dupe of #1127?

**Comment by diracdeltas** [comment]
@fmarier hmm it does appear they are the same

**Comment by mrose17** [comment]
agreed.

**Comment by fmarier** [comment]
Closing as a dupe of #1127.
