### ISSUE TITLE
HTTPSE upgrades not working with Chromium 101

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#22503]
## Description 

HTTPSE upgrades are not working with 1.38.x w/ Chromium 101. They do work on 1.37.x with Chromium 100.

When using 1.38.x, doesn't matter if shields v2 are enabled or not.

Worked with 1.38.103 which had Chromium 100, does not work with Chromium 101 versions of 1.38.x.

## Steps to Reproduce

   1. Clean profile 1.38.105
   2. Navigate to http://https-everywhere.badssl.com/

## Actual result:

not upgraded to https with 1.38.x with either shields v1 or v2

v1 | v2
--- | ---
<img width="1195" alt="v1" src="https://user-images.githubusercontent.com/28145373/164726953-316bbc7b-94d2-4382-a2e6-6884d582f77c.png"> | <img width="1070" alt="v2" src="https://user-images.githubusercontent.com/28145373/164726967-168a4873-119d-417c-816e-9e1dfe2a1c80.png">

## Expected result:

upgraded to https as in 1.37.x

<img width="1196" alt="1 37 116" src="https://user-images.githubusercontent.com/28145373/164727022-a68c8bbe-7901-49af-92ed-ccbff6bf6f3e.png">

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.38.105 Chromium: 101.0.4951.41 (Official Build) (x86_64)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | macOS Version 12.3.1 (Build 21E258)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 1.37.x no, 1.38.x yes
- Can you reproduce this issue with the beta channel? probably
- Can you reproduce this issue with the nightly channel? 1.40.x yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron @mkarolin

**Comment by kjozwiak** [comment]
@LaurenWags hmmm so on `Win 11 x64`, I'm seeing the following:

* install and launch `1.37.116 Chromium: 100.0.4896.127`
* load http://https-everywhere.badssl.com
* you'll notice the same result as above (re: not redirecting to the `https` page)
* refresh the same tab (same result as before re: not redirecting the page to `https`
* load http://https-everywhere.badssl.com in a new tab and you'll get redirected as expected

But it seems to be working on my end with `1.38.105 Chromium: 101.0.4951.41` using a new profile. Example:

https://user-images.githubusercontent.com/2602313/164728232-00798022-27e9-4df7-a8b2-c8967e6c6403.mp4

**Comment by GeetaSarvadnya** [comment]
Reproduced with `1.38.105 CR101` and not reproducible with `1.38.103 CR100`

**Comment by kjozwiak** [comment]
The above will require `1.38.107` or higher for `1.38.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
Brave | 1.38.107 Chromium: 101.0.4951.41 (Official Build) (64-bit)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | Windows 10 Version 21H2 (Build 19044.1645)

```

**_Clean profile_**
- Confirmed that HTTPS upgrade works fine in `1.38.107` in a clean profile
![image](https://user-images.githubusercontent.com/38657976/165271214-36dcefb7-46b8-4b56-aa2a-dd159f1f0558.png)

**_Upgrade profile_**

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.38.107 Chromium: 101.0.4951.41 (Official Build) (x86_64)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | macOS Version 11.6.5 (Build 20G527)

**_Clean profile_**
- Confirmed that HTTPS upgrade works fine in `1.38.107` in a clean profile

<img width="1312" alt="Screen Shot 2022-04-26 at 8 48 52 AM" src="https://user-images.githubusercontent.com/387249/165340786-56926fdd-3dd2-4df3-bea8-49e4548f05a1.png">


**_Upgrade profile_**

- Confirmed that HTTPS upgrade works fine in an upgraded profile

<img width="1312" alt="Screen Shot 2022-04-26 at 8 47 38 AM" src="https://user-images.githubusercontent.com/387249/165340557-d96412dc-94c5-4c77-8cd2-b85705a47fe0.png">


- Confirmed that HTTPS upgrade works in a profile where `<userProfile> Data\oofiananboodjbbmdelgdommihjbkfag\1.0.91\6.0\httpse.leveldb` is already created

Example | Example
-- | --
<img width="1232" alt="Screen Shot 2022-04-26 at 8 43 47 AM" src="https://user-images.githubusercontent.com/387249/165340424-cfe3efd9-65ef-4aed-8f5a-3b9a84848305.png"> | <img width="1312" alt="Screen Shot 2022-04-26 at 8 47 38 AM" src="https://user-images.githubusercontent.com/387249/165340658-dffc56b1-bf77-4848-b5a6-2eaf81e0c7f5.png">

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.38.107 Chromium: 101.0.4951.41 (Official Build) (64-bit)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | Ubuntu 18.04 LTS

**_Clean profile_**
- Confirmed that HTTPS upgrade works fine in `1.38.107` in a clean profile

![image](https://user-images.githubusercontent.com/34715963/165354720-4d909a9e-70f0-4eb6-ae8a-63fcaef5bef4.png)


**_Upgrade profile_**

- Confirmed that HTTPS upgrade works fine in an upgraded profile

![image](https://user-images.githubusercontent.com/34715963/165354778-58bae30e-8fae-4426-81d2-44e7d0823a03.png)



- Confirmed that HTTPS upgrade works in a profile where `<userProfile> Data\oofiananboodjbbmdelgdommihjbkfag\1.0.91\6.0\httpse.leveldb` is already created

Example | Example
-- | --
![image](https://user-images.githubusercontent.com/34715963/165354897-4b8c300e-be2a-4111-9b8a-eb26f418a83f.png)|![image](https://user-images.githubusercontent.com/34715963/165354943-d787c4d0-8e65-4c41-860a-8aae562a2e40.png)
