### ISSUE TITLE
Webview crashes after click on Restore your wallet

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#2250]
## Description 
Browser for  ~10 mins, enable rewards and add few sites and YT videos to wallet, accept the free grants, click on Restore wallet causes the webview crash. Reload page resolves the issue.

## Steps to Reproduce

   1. Launch Brave with clean profile
   2.  Browser for ~ 10 mins
   3.  Enable Rewards through `Brave Rewards`
   4.  Add few sites and YT videos to wallet
   5.  Click on `Restore your wallet`

## Actual result:
Webview crashes after clicking on `Restore your wallet`
![image](https://user-images.githubusercontent.com/38657976/49078153-43eba180-f263-11e8-9ecd-c5b88a454fa7.png)

Crash Report ID d8fda59f4f7088f9
https://stats.brave.com/dashboard#crash/5bfd227f1bf836001ebfc97f
## Expected result:
Should not be any webview crash

## Reproduces how often: 

Intermittent Issue

## Brave version (brave://version info)

Brave | 0.57.7 Chromium: 71.0.3578.53 (Official Build) beta (64-bit)
-- | --
Revision | 599fb72e740eab9d10609f1ed28a2ad669f82c1a-refs/branch-heads/3578@{#669}
OS | Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds?  Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional Information
@kjozwiak @LaurenWags @srirambv @btlechowski

**Comment by NejcZdovc** [comment]
@GeetaSarvadnya is this still a problem?

**Comment by GeetaSarvadnya** [comment]
@NejcZdovc I am not seeing the issue now  (Tested on both  0.59.18 and 0.59.20. )

**Comment by NejcZdovc** [comment]
closing for now then
