### ISSUE TITLE
Implement error modal if user does not have `receives` OR `sends` capabilities on Uphold

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#22508]
## Description

If Uphold capabilities shows that user does not have `receives` || `sends` capabilities on Uphold, then

1. Make sure user does not enter `verified` Rewards wallet state in the browser
2. Insert check in part of flow that will preclude linking on backend 
3. State migration or continual checks for existing Uphold-verified users that calls `explicit disconnect`

**Comment by kjozwiak** [comment]
The above will require `1.40.85` or higher for `1.40.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.40.86 Chromium: 102.0.5005.78 (Official Build) beta (x86_64)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | macOS Version 12.4 (Build 21F79)
```

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress on `Samsung Galaxy Tab A7 version 11` running `Bravemonoarmx64.apk_1.40.99`

**Comment by Uni-verse** [comment]
Verification in progress on Samsung Galaxy S21 using 

```
Brave	1.40.100 Chromium: 102.0.5005.125 (Official Build) beta (64-bit) 
Revision	07573b09e385116e620ed12d5ef2402c4bfa929f-refs/branch-heads/5005@{#1159}
OS	Android 12; Build/SP1A.210812.016
```
