### ISSUE TITLE
Estimated earnings different on Rewards NTP widget than Rewards panel/settings page

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#22512]
## Description 

User reset Brave Rewards once. "Estimated amount 0.521  BAT has been appearing on NTP since before they reset the wallet and now it isn’t increased after receiving ads."

Edit: Also noticed that his next payment date field is empty/undefined.

![image](https://user-images.githubusercontent.com/11497541/164765038-32695a81-72e6-4a3a-9735-4b655df19f31.png)

![image](https://user-images.githubusercontent.com/11497541/164765053-3126c6af-e51b-4738-9aeb-378d8f915ba3.png)

cc: @A-t-s-u-s-h-i

**Comment by A-t-s-u-s-h-i** [comment]
Hi @Miyayes @zenparsing,

These are the screenshots from the other user who is facing the same issue. They had flagged wallet(I'm not sure "flagged" is related to the issue or not, but I can't reproduce the same issue with my rewards wallet), then reset the wallet. And the rewards wallet wasn't reset correctly. On `brave://rewards-internals`, it shows "wallet wasn't yet created" but it has estimated rewards that old wallet had. I can share their old wallet info, so let me know if you need it.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/79502386/167556726-3aae9fb2-0427-4636-a00d-740bcdc97b9e.png">
<img width="1424" alt="image (1)" src="https://user-images.githubusercontent.com/79502386/167556730-1c532e19-07ca-44b9-97d4-34167a87c1fe.png">

**Comment by A-t-s-u-s-h-i** [comment]
I tried to un-flag their previous wallet, then they could make new rewards wallet without any problem. The issue occurs because the previous wallet was flagged. It's okay if this is as designed. @Miyayes
