### ISSUE TITLE
Brave is leaking public IP address through WebRTC when using proxy

### ISSUE THREAD

**Issue by derzahla** [brave/brave-browser#22515]
## Description 

Brave is leaking public IP address through webRTC while using a VPN through a proxy.  Similar as reported and fixed here: https://github.com/brave/brave-browser/issues/9041 

## Steps to Reprod

   1. Set proxy using a basic extension sets a proxy via local PAC file 
   2.  Browse to https://browserleaks.com/webrtc 
   3.  True public IP address is shown rather than the public IP address of the proxy being used

## Expected result:
Public IP address detected should be that of the proxy server.  Brave should either route all WebRTC traffic through the proxy or should not send it at all

## Reproduces how often: 

Every time when using a proxy 

## Brave version (brave://version info)

Brave | 1.38.84 Chromium: 100.0.4896.79 (Official Build) dev (64-bit)
-- | --
Revision | 8fb749dcab8700c24213791969e59deb72fee36f-refs/branch-heads/4896@{#1015}
OS | Linux

## Version/Channel Information:

Untested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  Yes
- Does the issue resolve itself when disabling Brave Rewards?  Yes
- Is the issue reproducible on the latest version of Chrome?  Yes

**Comment by madhatr** [comment]
I'm using IPA extension as VPN and my actual public IP shows up on that webRTC test page.

**Comment by madhatr** [comment]
@NumDeP Thank you, that setting fixed my IP leak with the IPA extension.

**Comment by derzahla** [comment]
@NumDeP  Sorry for the late response.  Yes, I have a basic local extension template incorporated my proxy pac file.  That setting seems to work, thank you, I must have missed it.  Perhaps disabled by default would be the best config for brave though.
