### ISSUE TITLE
Tabbing away from wallet panel should keep it open

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#22516]
Sometimes data is copy / pasted into the panel.  E.g. both the value of a transaction and the address.  You need to tab away to get the data, but we auto close the panel in that case. Extensions stay open in that case though. This is a major UX problem that we need to fix.

**Comment by bbondy** [comment]
pls uplift to 1.39.x too @spylogsster

**Comment by srirambv** [comment]
This is still not fixed. Spoke with @spylogsster and it will be fixed as part of #23152

**Comment by bbondy** [comment]
Changed to exclude in release-notes given the above.
