### ISSUE TITLE
Temporarily remove ads for Brave news

### ISSUE THREAD

**Issue by alexsafe** [brave/brave-browser#22527]
## Description 
Disable Brave News Ads temporarily as per https://bravesoftware.slack.com/archives/C0816QH3R/p1650670699983049?thread_ts=1650553305.086149&cid=C0816QH3R

## Steps to reproduce 

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
Closing as this was uplifted into `1.38.x` via https://github.com/brave/brave-core/pull/13154. @brave/qa-team STR/Cases can be found via https://github.com/brave/brave-core/pull/13154#issue-1213513903 but the main check is to make sure we're not seeing any ads being placed into the Brave News feed. Once that's checked, a quick check should be enough to make sure the feed is still working and you can remove/add different sources.

**Comment by kjozwiak** [comment]
Quick recap: ads are being disabled on `1.38.x` as @tmancey found a few issues:
* https://github.com/brave/brave-browser/issues/22470
* https://github.com/brave/brave-browser/issues/22476

We wouldn't have enough time to get the above fixed and correctly QA'd as we're basically ~1-2 days away from the release.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+` running `Android `12` using the following build(s):

```
Brave | 1.38.107 Chromium: 101.0.4951.41 (Official Build) (32-bit)
--- | ---
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | Android 12; Build/SP1A.210812.016
```

**`Clean Install`**

* ensured that there's no ads being displayed within the Brave News feed
* ensured that there's no noticeable empty areas within the feed where an ad might have previously been displayed
* ensured that tapping/clicking on news articles within the news feed opens them within the same tab without issues
* ensured that you can remove/add default sources without any issues
* ensured that you can add your own sources without any issues
* ensured that disabling/enabling the news feed doesn't cause any issues/make ads re-appear

**`Upgrade from 1.37.x`**

* install `1.37.116 Chromium: 100.0.4896.127` and enable rewards staging via the `QA Preferences` settings under `Dev Options`
* once Brave has been relaunched, enable Brave News and ensure that you can see a few staging ads within the feed
* update to `1.38.107 Chromium: 101.0.4951.41` and ensure that ad are no longer being displayed within the news feed

**`1.37.116 Chromium: 100.0.4896.127`** | **`1.38.107 Chromium: 101.0.4951.41`**
---------------------------------------------|----------------------------------------------
![Screenshot_20220426-131437_Brave](https://user-images.githubusercontent.com/2602313/165356568-377ce5dd-e033-4c77-94c8-007bd9f0f374.jpg) | ![Screenshot_20220426-131554_Brave](https://user-images.githubusercontent.com/2602313/165356580-3646a04d-2f3c-48ba-96b9-b9e26fb5b426.jpg)
