### ISSUE TITLE
CORS issue because of Brave Shields

### ISSUE THREAD

**Issue by SilencerWeb** [brave/brave-browser#2252]
## Description 
I have a website deployed on netlify that makes requests to the server that deployed to heroku, they both are on different domains. I enabled CORS in my server setup but I keep getting error `Access to fetch at 'https://eslint-config-api-server.herokuapp.com/' from origin 'https://eslint-config-development.netlify.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.`. Works like that only in Brave.

## Steps to Reproduce
   1. Open https://eslint-config-development.netlify.com.
   2. Open console.

## Brave version (brave://version info)
0.56.15 Chromium: 70.0.3538.110 (Official Build) (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? I don't know, I don't use such builds.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? Yes.
- Is the issue reproducible on the latest version of Chrome? No.

**Comment by charlescrtr** [comment]
Can confirm I'm seeing the same issue when trying to log in to https://prisma.io. Issue fixes itself when Shields are disabled.

**Brave version**
Version 0.56.15 Chromium: 70.0.3538.110 (Official Build) (64-bit)

**Comment by OrKoN** [comment]
I experience the same problem when trying to perform a CORS request with Brave:

```
Brave | 0.56.15 Chromium: 70.0.3538.110 (Official Build) (64-bit)
-- | --
Revision | ca97ba107095b2a88cf04f9135463301e685cbb0-refs/branch-heads/3538@{#1094}
```

**Comment by dwwoelfel** [comment]
I think this is because Brave is stripping out the Origin header from the initial OPTIONS request.

**Comment by LukeDearden** [comment]
Azure Portal is unusable in Brave because of this

**Comment by SilencerWeb** [comment]
Some of the charts from chart.js brokes because of this:

![image](https://user-images.githubusercontent.com/20713191/49728229-01c75480-fc94-11e8-834d-42a20dd80888.png)

![image](https://user-images.githubusercontent.com/20713191/49728240-07249f00-fc94-11e8-949b-28176e0f6647.png)

Here is the link to this example - https://www.chartjs.org/samples/latest/charts/line/multi-axis.html

**Comment by bsclifton** [comment]
Several +1s from https://github.com/brave/browser-laptop/issues/15319

**Comment by renschler** [comment]
I also have this error (even with shields down).
I am collecting sensitive information within an iframe with a cross-domain src. The iframe page makes a fetch call to POST the information. I'm noticing (even with shields down) the CORS preflight OPTIONS request has the origin set to null. Not sure if that's why its failing? Things work in Firefox & Chrome.

**Comment by kxlt** [comment]
Same problem here. Gmail 2FA broken because of this.

On our website, https://www.wikiloc.com, we use Apple MapkitJS and all maps are broken as well.

**Comment by jamendub** [comment]
Got a similar problem that I described there : https://github.com/brave/browser-laptop/issues/15319

**Comment by jmadkins** [comment]
The users profile image doesn't load with Shields Up on the [Azure Portal](https://portal.azure.com). Shields Down allows the profile image and some panes to load. However, the majority of panes don't load regardless of Shield settings.

Version 0.57.18 Chromium: 71.0.3578.80 (Official Build) (64-bit)

**Comment by petethompson** [comment]
I'm experiencing the same cross-origin issue, with a javascript http request from one of my clients websites; requesting data from the service where they store their content. It seems like the Shield option for blocking cookies is responsible.

**Comment by iefremov** [comment]
This change seems to break all preflight CORS requests and hence all CORS requests that require preflight: https://github.com/brave/brave-core/pull/754/files

Since we always clean referrer for cross-origin requests, all these requests become redirects, and preflight redirects are not allowed by policy.

@bbondy @yrliou

**Comment by iefremov** [comment]
Also affects:
https://github.com/brave/brave-browser/issues/2034
https://github.com/brave/brave-browser/issues/1999

**Comment by srirambv** [comment]
@iefremov the following issues are all CORS related. 

- #2034
- #1999
- #1581
- #2341 
- #2286
- #2411 
- #2414

**Comment by hito** [comment]
+1 spent a longer than reasonable amount of time trying to debug this for a project I am developing, affects Brave Browser only regardless of shields up or down. Exact same project works fine under Firefox, Safari, and Chrome.

**Comment by jonathansampson** [comment]
@hito Are you sure that the issue you were facing is the same issue discussed here? The issue being discussed here is usually resolved by lowering the shields (or specifically, modifying the cookie-related settings, AFAIK). Are you able to share a link to the issue you're facing? Perhaps a reduced project to help us identify/confirm the root issue?

**Comment by johnspurlock** [comment]
@jonathansampson A repro case, but perhaps not the same one as @hito.

1. Go to https://convopage.com
2. Put `1077284887202316289` in the box, hit 'get convopage'

This works fine with shields down, but fails with an error [1] with shields up, desktop mac brave version [2] below.

[1] Access to XMLHttpRequest at '<url>' from origin '<origin>' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.

[2] Version 0.59.12 Chromium: 72.0.3626.17 (Official Build) beta (64-bit)

**Comment by hito** [comment]
Apologies @jonathansampson this isn't an issue with shields disabled, I mucked up there and will strike this part out of my response – this doesn't detract from the fact that silently editing CORS headers with the shield active (something almost all users will have) means this literally breaks some applications unless a proxy is used specifically for Brave, or if detection is added in js for Brave.

Both of which just hinder progress. This needs to be the highest priority item to fix imho.

**Comment by eljuno** [comment]
+1 from Community https://community.brave.com/t/cant-load-aws-logs/41473?u=eljuno

**Comment by Brave-Matt** [comment]
+1 from Community (most likely):
https://community.brave.com/t/problem-with-spotify/41580/4

☝️ It seems to be causing Spotify to skip to a random track (when first attempting playback), land on one, but not actually play it. This can be consistently produced until Shields are dropped or All Cookies are allowed. 
Console view:
![image](https://user-images.githubusercontent.com/3299098/50667200-fb638a00-0f6c-11e9-87d0-88e1fea40371.png)

**Comment by Brave-Matt** [comment]
I also get the same error on Amazon Prime video, but only in the Beta channel release (v0.59.14):
![apvcors](https://user-images.githubusercontent.com/3299098/50667580-d8d27080-0f6e-11e9-9f67-b2fb666a898a.gif)

**Comment by MisinformedDNA** [comment]
I'm seeing this on https://portal.azure.com as well. [Original issue.](https://community.brave.com/t/parts-of-portal-azure-com-do-not-load-even-with-shields-down/37053)

I'm on Brave v0.58.18

**Comment by cemerson** [comment]
> Azure Portal is unusable in Brave because of this even with Shields down
Ditto. Here's screen of messages in console when trying to approve credit card on Azure Signup Portal.

![](https://c1.staticflickr.com/5/4804/46662029591_6a329f1341_b.jpg)

**Comment by iefremov** [comment]
Closed all dupes I could find.
Not sure about #2580, cant test it quickly.
#2286 is not related to this issue.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.58.20 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Windows 7

Used test plan from OP.

**Comment by jamendub** [comment]
Updated to 0.58.21 and it now works perfectly !
I love u guys ;)
Keep the good work up !!!!

**Comment by maketroli** [comment]
I am having this issue right now.
```
Access to fetch at 'http://some/api/url' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by tggir1** [comment]
0.63.55 Chromium: 74.0.3729.131 (Official Build) (64-bit)

I'm receiving the same CORS preflight error as others. prevents signing in to medium.com (via email, twitter, google, and fb)

**Comment by michaeltintiuc** [comment]
Also happens on https://my.playstation.com/ for me with Brave 1.8.96 on Linux
