### ISSUE TITLE
No option to context-click remove Brave Rewards (BAT) icon, unlike Wallet and VPN icons

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#22525]
## Description 

No option to context-click remove Brave Rewards (BAT) icon, unlike Wallet and VPN icons

## Steps to Reproduce

   1. install `1.40.5`
   2. launch Brave
   3. context-click on the `Rewards` (BAT) icon in the URL bar
   4. context-click on the `Wallet` icon in the browser toolbar
   5. enable `VPN` and `SKUs SDKs` via `brave://flags`
   6. click on `Relaunch` to restart Brave
   7. context-click on the VPN icon in the browser toolbar 

## Actual result:

We provide the ability to remove the `Wallet` and `VPN` icons via context-clicks, but not the `Rewards`/BAT icon.  

## Expected result:

Consistency - note you can remove it via `Show Brave Rewards icon in address bar` in `brave://settings/appearance`.

Also note the text differences already, in https://github.com/brave/brave-browser/issues/22436.

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.40.5 Chromium: 101.0.4951.41 (Official Build) nightly (64-bit)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | Windows 10 Version 21H2 (Build 19044.1645)

cc @rebron @Miyayes @bsclifton

**Comment by Miyayes** [comment]
@mkarolin noted that we might've purposely disabled context menu/right click for icons that appear inside the address bar, and that it's our own code. That might've been intentional, so may need discussion about that functionality.

**Comment by mkarolin** [comment]
I looked back at the history here. We added a toggle in the settings to hide the icon in https://github.com/brave/brave-browser/issues/2975, but it was - at the time - limited to when Rewards was disabled (when we had a Rewards on/off switch). When we removed the Rewards on/off switch in https://github.com/brave/brave-browser/issues/11467 we also adjusted the toggle to always be able to hide the icon. Since we already have a way to hide it, there's no counterindication, IMO, to adding a way to do it via the context menu.

**Comment by mkarolin** [comment]
QA Plan:

1. Launch Brave
2. context-click on the Rewards (BAT) icon in the URL bar

Expected result:
Observe context menu with the option to hide the icon

3. Click on the menu option to hide the rewards icon

Expected result:
Rewards icon is no longer shown in the URL bar

4. Navigate to brave://settings/appearance

Expected result: 
Confirm that `Show Brave Rewards icon in address bar` setting is OFF

5. Toggle `Show Brave Rewards icon in address bar` setting to ON

Expected result:
Rewards icon is shown in the URL bar

**Comment by GeetaSarvadnya** [comment]
Verification is inorogress

```

Brave | 1.40.75 Chromium: 102.0.5005.61 (Official Build) beta (64-bit)
-- | --
Revision | 0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}
OS | Windows 10 Version 21H2 (Build 19044.1706)

```
- Verified the test plan from https://github.com/brave/brave-browser/issues/22525#issuecomment-1128151239

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.40.75 Chromium: 102.0.5005.61 (Official Build) beta (x86_64)
-- | --
Revision | 0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}
OS | macOS Version 12.5 (Build 21G5027d)

- Verified the test plan from https://github.com/brave/brave-browser/issues/22525#issuecomment-1128151239
- Confirmed that the context menu is provided with the option to hide the Brave rewards icon
- Confirmed that the user can hide the rewards icon by clicking on the context menu
- Confirmed that after hiding the rewards icon is no longer shown in the URL bar
- Confirmed that the hide rewards settings retained across the tabs and windows
- Confirmed that hide rewards settings retained after the browser restart
- Confirmed that Show Brave Rewards icon in address bar settings is set to OFF in `brave://settings/appearance`
- Confirmed that the user can enable the switch Show Brave Rewards icon in the address bar
- Confirmed that the Brave rewards icon is shown in the URL bar after enabling the settings in `brave://settings/appearance`

**Comment by Tonev** [comment]
Filled https://github.com/brave/brave-browser/issues/23124
