### ISSUE TITLE
Global defaults link in the Shields panel is not visible for some screen sizes

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#22539]
## Description 
Global defaults link in the Shields panel is not visible on smaller screens

## Steps to Reproduce

   1. Install 1.38.104
   2. Launch Brave 
   3. Visit www.usatoday.com
   4. Click Shields icon to open Shields panel
   

## Actual result:

Global defaults link is not visible in the Shields panel.  (tested on my windows laptop)

<img width="955" alt="small screens" src="https://user-images.githubusercontent.com/98358127/165126293-217f5214-766d-48e3-bd89-27b292a93ca3.png">

## Expected result:
Global defaults link should be available on  smaller screens

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Brave | 1.38.104 Chromium: 101.0.4951.41 (Official Build) (64-bit)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | Windows 11 Version 21H2 (Build 22000.613)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome?

**Comment by btlechowski** [comment]
Also reproduced for 4k with default scale (300%)

![shields 4k 300percent](https://user-images.githubusercontent.com/34715963/165579942-7905ef27-c190-44b9-be1e-68e7a7ee063e.png)

**Comment by rebron** [comment]
Closed with https://github.com/brave/brave-core/pull/13209

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.41.65 Chromium: 103.0.5060.42 (Official Build) nightly (64-bit)
-- | --
Revision | de0d840bf9439c31bd86bf74f065c31fdf9b208d-refs/branch-heads/5060@{#667}
OS | Windows 11 Version 21H2 (Build 22000.739)
```

Followed original steps

Confirmed `Global defaults` link is displayed on the `Shields` panel for smaller screen sizes


![image](https://user-images.githubusercontent.com/98358127/173960766-aeb73d74-490b-40f1-9a9b-6e906e9a3ac7.png)
