### ISSUE TITLE
suddenly crash at start (all the time)

### ISSUE THREAD

**Issue by jerome-diver** [brave/brave-browser#22536]
Yes, i did searched on Google since 5 days (not find how to fix).
I can not get error on vrave:/crash because i have not time to see a tab content to open. The application satrt, then show the tab canvas, but never the content... after 5 to 10 seconds, it crash. 
When start from terminal emulator, i can read error message: 

> [16986:16986:0425/194407.665303:ERROR:profile_attributes_storage.cc(848)] Failed to PNG encode the image.
> [17022:17022:0425/194407.791375:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.

If i try to call without gpu-process enabled, same result Failed to PNG encode.
If i delete all my .config/BraveSoftware/Brave-Browser directory, remove brave-browser and install again, it start well, and when i copyt back my content copied to recover all my contents... after to restart, it crash again with exactly the same error.

It looks like something is going wrong similar to a corrupted file or somthing, but no clue provide by Brave browser to know wich file is concerned.

I'm installing brave-browser on Fedora-34 distro and used it for a year on this OS without any problem before  last week...

Please, help me to recover all mùy content and to continue toi use Brave by try to fix the problem.

**Comment by Brave-Matt** [comment]
Seems like you are correct — some data you're copying over from your saved `User data` folder is causing the crash. I'm wondering if it might be as a result of a particular extension you had installed — did you have any extensions installed when experiencing the crash? Can you also confirm what version of the browser you installed/are using when you see this issue?

Thank you

**Comment by bsclifton** [comment]
@iefremov would there be a useful file we can analyze on Linux for crash dump?

**Comment by bsless** [comment]
I had the same issue. As a temporary workaround you can launch brave with `--no-sandbox` flag:
```
brave-browser --no-sandbox
```
This seems like a deeper issue with glibc though: https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1944468

**Comment by jerome-diver** [comment]
@bsless thank you for your answer. I tried with --no-sandbox flag but still same crash issue.

@Brave-Matt thank you for yoour answer. Is there a flag for brave can trace wich file is in fault at crash time ? (a kind of debug mode) I think it should have one.

@bsclifton thank you for your answer. Ho sorry, i missed to indicate the version used... It is the version 100.1.37.116, the official one from Fedora-34 repo.

**Comment by iefremov** [comment]
@jerome-diver thanks for the report. Debugging that could be tricky, because the problem sounds pretty uncommon. Can you please shed some more light on the problem by "bisecting" your profile dir? E.g. try to start the browser with the "bad profile", but remove Local State from it? Then remove Preferences, then something else to find out what particular file casuses the problem

**Comment by jerome-diver** [comment]
@iefremov thank you to try to help.
What i can do before to stop to use Brave is to ask you where is the logs files from Brave browser ? If there is no debug mode with Brave browser.
And i think, by the fact, that it is this missing crucial point that make Brave tricky to debug.
It is uncommon to see a good application with so much ambition about safety concern and still don't have any debug mode and then, to be unable to just indicate which file break things at exec time.
Please, increase Brave to help users to fix this kind of problem (it is not the first time this is happening, and it will not be the last time, also, it can become a safety issue).
You can also, sure, decide to deny and ignore the purppose. But there is no evolution possible on this way to think safety concern.
Let me know when Brave will increase his safety and issues concern the way to help users to just read a debug file to fix problem easy.

**Comment by iefremov** [comment]
@jerome-diver pls reopen if the issue still happens
