### ISSUE TITLE
 Trackers & Ads Blocking Setting Not Persisting

### ISSUE THREAD

**Issue by luv2dnce33** [brave/brave-browser#22531]
Originally posted by another user below but the issue is not being responded to any longer and seems to have gone abandoned.

cc @qazero 

_Originally posted by @qazero in https://github.com/brave/brave-browser/issues/11585#issue-692106975_

**Comment by bsclifton** [comment]
@luv2dnce33 do you have history / settings cleared on exit?

**Comment by luv2dnce33** [comment]
jeeze, thats what it was for me... i am so sorry for wasting everyone's time

**Comment by qazero** [comment]
I have the option to clear history, cookies, etc. on exit. But I don't see any option that would clear the settings on exit. Could you please post a screenshot?
