### ISSUE TITLE
Set `autocomplete=off` for every internal page

### ISSUE THREAD

**Issue by thypon** [brave/brave-browser#22538]
# Background

Any `input` field - non-password type- content is cached in the browser autocomplete cache in chromium-based browsers. That is true for any other input field that may show password content, for example:

- Password confirmation dialog for password change functionalities
- Recovery phrases input fields
- ...

As a mitigation setting, `autocomplete=off` is working if specified in that particular field. However, this condition is not ideal and leaves most chrome extensions vulnerable to this behavior.

# Proposal

As a general improvement, we should default any input field to `autocomplete="off"` for anything under brave*:// (or maybe anything that is not http/https:// ).

# Risks/Benefits

Risks:
- Brave will break extensions and internal-pages autocompletion.
- Brave drifts from the generic Chrome behavior

Benefits:
- Brave safeguards automatically against local credentials leakage
- Brave protects and serves better the userbase employing it for payments and safety reasons

Cc @bbondy @bridiver @iefremov

**Comment by thypon** [comment]
https://github.com/brave/brave-core/pull/13146#issuecomment-1202025188

**Comment by fmarier** [comment]
Also, since we may want to deny abusive websites the ability to disable password managers via `autocomplete=off`, we should make sure that our fix for `chrome://` pages doesn't rely on us honoring this attribute, but instead disables autocomplete in a non-overridable way.

**Comment by fmarier** [comment]
As a first step, I'd suggest we target just the `chrome://` scheme and leave `chrome-extension://` alone.
