### ISSUE TITLE
`View on block explorer` always opens mainnet link

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#22534]
## Description 

`View on block explorer` always opens mainnet link

## Steps to Reproduce

   1. Perform a transaction on Ropsten
   2. Select token and go to transactions
   3. Click on 3 dot menu and select `View on block explorer`
   4. Opens up `https://etherscan.io/tx/<TXHASH>` rather than `https://ropsten.etherscan.io/tx/<TXHASH>`

## Actual result:

https://user-images.githubusercontent.com/17010094/165080159-35f2e5fe-63a5-490a-a300-803ed50a233b.mov

## Expected result:
Should default to network specific block explorer as in current release version

https://user-images.githubusercontent.com/17010094/165080810-e1706233-2af5-4bf4-a9ad-8530a03ddbf6.mov

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.38.106 Chromium: 101.0.4951.41 (Official Build) (64-bit)
-- | --
Revision | `93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @muliswilliam

**Comment by kjozwiak** [comment]
Closing as https://github.com/brave/brave-core/pull/13181 was merged into `1.38.x`.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">  1.38.106 Chromium: 101.0.4951.41 (Official Build)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux (Rinkeby)</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22598.200) (Goerli)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52) (Ropsten)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td>
      </td>
      <td colspan=3>
         <ul>
         <li>Verified steps from issue description</li>
         <li>Verified <code>View on block explorer</code> opens the transaction link on the selected network as expected</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><Video src=https://user-images.githubusercontent.com/17010094/165516865-2082c7e3-1fee-4951-9754-6ce9d48e565f.mp4>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/165515608-70afa039-7a26-4b91-addd-7b22e7639acf.mov>
      </td>
      <td><video src=https://user-images.githubusercontent.com/17010094/165515579-0fca6222-304a-4db3-ac01-083266d06e74.mov>
      </td>
   </tr>
</table>
