### ISSUE TITLE
Users are not rewarded until the catalog has updated after upgrading to 1.39.x

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#22542]
## Steps to Reproduce

   1. Install 1.38.x
   2. Join rewards (wait for catalog to persist in database)
   3. Upgrade to 1.39.x
   4. Launch browser
   5. Wait for catalog update

## Actual result:

Users are not rewarded for viewing ads (cause: the creative ads databases tables are populated but the deposits table is empty)

## Expected result:
Users should be rewarded for viewing ads

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by amzero** [comment]
More than a week i receive ads and i don't get any bat.

https://user-images.githubusercontent.com/6620339/165175590-db04f3f7-02be-4c60-8027-7ec3b750ae1d.mp4

Is this issue for this especific error?

[Versão 1.37.116 Chromium: 100.0.4896.127 (Versão oficial) 64 bits](https://brave.com/latest/)
Windows 8.1

**Comment by tmancey** [comment]
@amzero this particular issue does not affect 1.37.x, thanks

**Comment by tmancey** [comment]
@amzero are you available for a screen-share to investigate? Thanks

**Comment by tmancey** [comment]
@amzero if you email me direct at terry@brave.com I can send a link via email. Thanks
