### ISSUE TITLE
Old versions of Brave show "access denied" message when trying to install an extension

### ISSUE THREAD

**Issue by G1tOnW1th1t** [brave/brave-browser#22554]
See post

 "Access denied" message when trying to install extensions #16611

Adding this post on a "just in case "closed" means no-one on support is seeing continuing reports that error is NOT fixed" basis.

## Steps to Reproduce

   1. Tried to install extension 11 days ago, ran into this issue (and posted a report - no official response)
   2. Tried to (re)install another extension today. same issue again
   3. Need to install third party .crx file to bypass this roadblock. That is simply not good enough.

## Actual result:
 See multiple posts this year (added since close I'd say) to say issue ongoing for me - Win7 Pro, Brave Version 1.25.72 Chromium: 91.0.4472.101 (Official Build) (64-bit) - note unsure if latest, get 'An error occurred while checking for updates: Update check failed to start (error code 3: 0x80004002 -- system level)' useful error message NOT.

## Expected result:
 Extensions on Play Store should simply "add" to Brave

**Comment by bsclifton** [comment]
@G1tOnW1th1t you're on an ancient version of Brave. Can you please try to upgrade to a newer version? 1.25 is from 8 months ago

**Comment by rebron** [comment]
Closing per last comment.
