### ISSUE TITLE
Brave News opt-in card is overlapping the NTP SI button at the bottom of the NTP

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#22552]
## Description 

On certain devices, the Brave News opt-in card slightly overlaps the NTP SI button at the bottom of the screen. This doesn't block users from clicking on the text and loading the sponsors landing page but should still be fixed.

## Steps to reproduce 

   1. download a version of Brave that has the Brave News opt-in card visible (`1.38.x` or higher)
   2. open a NTP until you hit a NTP SI
   3. notice that on certain devices, the card overlaps the NTP SI button/message.

## Actual result 

**`Example`** | **`Example`**
---------------|-----------------
![Screenshot_20220426-003118_Brave - Nightly](https://user-images.githubusercontent.com/2602313/165225343-9c1291bc-a22d-4eb2-bc01-320216ef47e3.jpg) | ![Screenshot_20220426-004842_Brave - Nightly](https://user-images.githubusercontent.com/2602313/165225347-9b9cdaab-c4e0-42d3-8490-5b2de5d13728.jpg)

## Expected result

The Brave News opt-in card shouldn't be overlapping any of the NTP SI next/buttons.

## Issue reproduces how often 

100% reproducible using the STR/Cases outlined above.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `Yes` (once `1.38.x` is released)
- Can you reproduce this issue with the current Play Store Beta version? `Yes` 
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Pixel 6` & `Samsung S10+`
   - Android version: `Android 12`
   
## Brave version

* `1.40.12 Chromium: 101.0.4951.41`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by bsclifton** [comment]
cc: @petemill who is working on the peeking card (on Desktop). We have it a bit easier on desktop as the promo is in the bottom left. But smaller screen sizes might experience the same thing on Desktop

**Comment by Uni-verse** [comment]
Verified PASSED on Samsung Galaxy S21 & Samsung Galaxy Tab S7 running Android 12 using

Brave	1.39.117 Chromium: 102.0.5005.78 (Official Build) (64-bit) 
Revision	df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS	Android 12; Build/SP1A.210812.016

- Confirmed opt-in card doesn't overlap the NTP SI button. 

1.39.115 (Mobile)  | 1.39.117 (Mobile)
-|-
![Screen Shot 2022-06-06 at 10 59 30 AM](https://user-images.githubusercontent.com/17885425/172218496-069bb9d2-ff44-472b-91f7-f5178a2cc5ee.png) | ![Screen Shot 2022-06-06 at 9 56 37 AM](https://user-images.githubusercontent.com/17885425/172218516-48c247e7-b975-4850-be7c-bfec6c0c0195.png)
