### ISSUE TITLE
NTP becomes scrollable and `Load new content` appears when changing device orientation when Brave News disabled

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#22569]
## Description 

While running through https://github.com/brave/brave-browser/issues/22135 on `1.38.x`, I noticed that the NTP page becomes scrollable when changing the orientation from `vertical` -> `horizontal` -> `vertical` and the `Load new content` button appears via the NTP even though Brave News has never been disabled.

## Steps to reproduce 

**`Test Case #1`** (in this case, you'll get the `Load new content` button appearing)

   1. install a version of Brave that has the opt-in card visible by default via NTP (used `1.38.107 Chromium: 101.0.4951.41`)
   2. disable the Brave News opt-in card via the NTP by pressing the `X` button
   3. once the opt-in card has been disabled, changed the orientation from `vertical` -> `horizontal` -> `vertical`
   4. notice that the NTP is scrollable and when you start scrolling, you'll see the `Load new content` button appear

**`Test Case #2`** (in this case, the NTP becomes scrollable but the `Load new content` button does't appear)

   1. install a version of Brave that has the opt-in card visible by default via NTP (used `1.38.107 Chromium: 101.0.4951.41`)
   2. ensure that the opt-in card is visible and change the orientation from `vertical` -> `horizontal` -> `vertical`
   3. notice that the NTP is scrollable

**`Note`**: opening a new tab resolves the above. The `Load new content` button doesn't appear across different NTP. However, it's 100% reproducible on every NTP page and only happens when changing orientations.

## Actual result 

https://user-images.githubusercontent.com/2602313/165386726-fca32b32-58de-4922-9219-ef833eda36bc.mp4

## Expected result

Changing the orientation of the device shouldn't make the NTP tab scrollable nor display the floating `Load new content` button.

## Issue reproduces how often 

100% reproducible using the STR/Cases outlined above.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `No` (`1.38.x` hasn't been released yet)
- Can you reproduce this issue with the current Play Store Beta version? `Yes`
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Samsung S10+`
   - Android version: `Android 12`
   
## Brave version

* `1.38.107 Chromium: 101.0.4951.41`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by kjozwiak** [comment]
This needs to be completed for the `1.38.x` maintenance release so we can re-enable https://github.com/brave/brave-browser/issues/22135.

**Comment by alexsafe** [comment]
@kjozwiak is some step missing in Test case #2? because NTP is supposed to be scrollable while the opt-in card is on

**Comment by kjozwiak** [comment]
> @kjozwiak is some step missing in Test case #2? because NTP is supposed to be scrollable while the opt-in card is on

Definitely missing some steps. The second case was related to enabling news via the opt-in card, disabling it via `Settings` and then changing the orientation. It's basically the same case as the first one but once enabled, I could never reproduce the issue of `Load new content` appearing. Edited the case 👍

**Comment by kjozwiak** [comment]
@brave/qa-team some additional STR/Cases outlined via https://github.com/brave/brave-core/pull/13203#issuecomment-1123069843 which basically double checks and ensured that the opt-in card is working as expected in various scenarios.

**Comment by kjozwiak** [comment]
Should wait to QA the above till https://github.com/brave/brave-browser/issues/22778 as been resolved and the opt-in card has been enabled via the NTP via `1.38.x`.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+` running `Android 12` using the following build(s):

```
Brave | 1.38.118 Chromium: 101.0.4951.67 (Official Build) (64-bit)
--- | ---
Revision | 8888ee7a24e2c36661ddb9536c35b7d4852a3a98-refs/branch-heads/4951@{#1230}
OS | Android 12; Build/SP1A.210812.016
```

Went through the STR/Cases outlined via https://github.com/brave/brave-browser/issues/22569 and ensured that:
* the NTP isn't scrollable like before while viewing NTP in both `portrait` & `landscape` modes
* ensured that changing the orientation doesn't display the `Load new content` button while Brave News is disabled

https://user-images.githubusercontent.com/2602313/168521185-cf15a617-0011-4f3a-b394-ff3c17ce4e36.mp4

https://user-images.githubusercontent.com/2602313/168521140-b99f3837-079d-4b49-9931-15dacecbfea0.mp4

Verification **PASSED** on `Samsung Galaxy Tablet A` running `Android 11` using the following build(s):

```
Brave | 1.38.118 Chromium: 101.0.4951.67 (Official Build) (64-bit)
--- | ---
Revision | 8888ee7a24e2c36661ddb9536c35b7d4852a3a98-refs/branch-heads/4951@{#1230}
OS | Android 11; Build/RP1A.200720.012
```

Went through the STR/Cases outlined via https://github.com/brave/brave-browser/issues/22569 and ensured that:
* the NTP isn't scrollable like before while viewing NTP in both `portrait` & `landscape` modes
* ensured that changing the orientation doesn't display the `Load new content` button while Brave News is disabled

https://user-images.githubusercontent.com/2602313/168521499-a7a0a822-61c3-4d85-a06a-518a63f980af.mp4

https://user-images.githubusercontent.com/2602313/168521735-c87d3456-61d8-4bcb-afa2-a9abcfea47bb.mp4
