### ISSUE TITLE
Sync should be able to accept an empty device name for existing sync code dialog

### ISSUE THREAD

**Issue by cezaraugusto** [brave/brave-browser#2256]
Per spec, similarly to Sync set up, the device name should fallback to `OS + Desktop` string and not throw a notification asking user input.

STR:

1. Enable Sync via flag;
2. Go to brave://bravesync, ensure it is disabled;
3. Click "I have an existing Sync code:"
4. Paste this code word `tuna gym prosper business double clump baby about slim mosquito this there awesome behind sniff injury duck mercy discover sick carbon govern month double`
5. Leave the `Enter a name for this device:` field emtpy

Result:

An alert is shown asking for a device name

Expected:

Sync should start setup with a default device name

**Comment by cezaraugusto** [comment]
this will not be needed in sync v2 as it doesn't accept device naming so closing

**Comment by srirambv** [comment]
@cezaraugusto ok to mark this as `QA/No`?

**Comment by LaurenWags** [comment]
or should it be labelled `wontfix` @cezaraugusto ?
