### ISSUE TITLE
Add "Force paste" option that bypasses onpaste handlers

### ISSUE THREAD

**Issue by bridiver** [brave/brave-browser#22567]
## Description 
Some sites use onpaste handlers to prevent pasting things like passwords. This is obviously bad (you should be using a password manager) and annoying. We should have a way to paste without triggering onpaste handlers

## Steps to Reproduce
   1. go to https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_onpaste
   2. copy and paste something into the input field
   3. "You pasted text!" appears

## Expected result:
   1. go to https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_onpaste
   2. copy and force paste something into the input field
   3. "You pasted text!" does not appear

**Comment by bridiver** [comment]
![image](https://user-images.githubusercontent.com/34129/165368371-3bfe9211-d1a1-411d-9a39-9f274d11c396.png)
![image (2)](https://user-images.githubusercontent.com/34129/165368441-548f9485-1b6f-4245-9771-9f127f70ce6a.png)
![image (1)](https://user-images.githubusercontent.com/34129/165368449-2b07cde8-5994-4182-8621-3bf1d108f1e6.png)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.41.50 Chromium: 102.0.5005.99 (Official Build) nightly (64-bit)
-- | --
Revision | 870f7bcc58dfa811cc68c2186439721385e086d0-refs/branch-heads/5005@{#1125}
OS | Windows 11 Version 21H2 (Build 22000.675)
```
Followed test plan from  #https://github.com/brave/brave-browser/issues/22567#issue-1216331974

1. Install 1.41.50
2. Launch brave 
3. Go to https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_onpaste
4. Confirmed `Force Paste` option is added to context menu
5. Copy text (`brave`) and `Force paste` into the input field
6. Confirmed  `Your pasted text!` is not shown
7. Verified `Your pasted text!` is still shown when copy and paste text (`brave`) into the input field


Step4|Step5&6|Step7
---|---|---
<img width="946" alt="image" src="https://user-images.githubusercontent.com/98358127/172953384-dba32801-9d92-4e41-a5f8-bd55da6f23ae.png">|<img width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/172953688-c2bfb059-a469-4cfe-ba78-c0ea76efad09.png">|<img width="953" alt="image" src="https://user-images.githubusercontent.com/98358127/172953753-574eee8a-f792-47ce-b642-3b2d9d13544e.png">

**Comment by stephendonner** [comment]
## Verification `PASSED` using

Brave | 1.41.50 Chromium: 102.0.5005.99 (Official Build) nightly (x86_64)
-- | --
Revision | 870f7bcc58dfa811cc68c2186439721385e086d0-refs/branch-heads/5005@{#1125}
OS | macOS Version 12.5 (Build 21G5037d)


Followed test plan from  #https://github.com/brave/brave-browser/issues/22567#issue-1216331974

### Steps
1. installed 1.41.50
2. launched Brave 
3. loaded `https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_onpaste`
4. confirmed `Force Paste` option is added to context menu
5. copied text (`brave`) and `Force paste`d into the input field
6. confirmed  `Your pasted text!` is not shown
7. verified `Your pasted text!` is still shown when copy and paste text (`brave`) into the input field


Step 4|Steps 5&6|Step 7
---|---|---
<img width="870" alt="Screen Shot 2022-06-09 at 3 34 46 PM" src="https://user-images.githubusercontent.com/387249/172956566-7f7cf0b7-ae32-4c1a-929f-10e2163debfb.png"> | <img width="980" alt="Screen Shot 2022-06-09 at 3 35 27 PM" src="https://user-images.githubusercontent.com/387249/172956570-3224104f-747a-46f8-9992-d5e963640d03.png"> | <img width="980" alt="Screen Shot 2022-06-09 at 3 36 08 PM" src="https://user-images.githubusercontent.com/387249/172956576-8b225c76-edea-47ca-8f13-368db3f9406d.png">

**Comment by stephendonner** [comment]
## Verification `PASSED` using


Followed test plan from  #https://github.com/brave/brave-browser/issues/22567#issue-1216331974

### Steps
1. installed 1.41.80
2. launched Brave 
3. loaded `https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_onpaste`
4. confirmed `Force Paste` option is added to context menu
5. copied text (`brave`) and `Force paste`d into the input field
6. confirmed  `Your pasted text!` is not shown
7. verified `Your pasted text!` is still shown when copy and paste text (`brave`) into the input field


Step 4|Steps 5&6|Step 7
---|---|---

**Comment by utdrmac** [comment]
How do I enable force paste by default? I don't want to have to keep clicking this menu. There should be an option to always force paste.
