### ISSUE TITLE
Dapps panel: bottom clock button implementation

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#22561]

**Comment by Pavneet-Sing** [comment]
Update: This is on hold till first MVP.

**Comment by AnmolBansalDEV** [comment]
Please provide more information on how to reproduce this

**Comment by simoarpe** [comment]
@SergeyZhukovsky , is this still relevant?

**Comment by SergeyZhukovsky** [comment]
I don't think we need any clock button currently, closing it.
