### ISSUE TITLE
Changing network on panel doesn't reflect on widget

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#22564]
## Description 

Changing network on panel doesn't reflect on widget

## Steps to Reproduce

   1. Unlock wallet via panel
   2. Change network to Ropsten 
   3. Widget doesn't update to Ropsten stays on Mainnet
   4. Reload the page, updates to Ropsten on widget

## Actual result:

https://user-images.githubusercontent.com/17010094/165339476-842f89b6-9ee4-4e12-b62f-9e4d65190599.mov

## Expected result:
Should update automatically without any page refresh

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html><head></head>
<body>

Brave | 1.38.107 Chromium: 101.0.4951.41 (Official Build) (64-bit)
-- | --
Revision | `93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}`
OS | All

</body>
</html>
## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes when 1.38.x is released
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel @josheleonard

**Comment by kjozwiak** [comment]
The above requires `1.39.109` or higher for `1.39.x` verification 👍

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.39.109 Chromium: 102.0.5005.50 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>f6e2cf8f59ec714bdcff8499991d55898875f287-refs/branch-heads/5005@{#648}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22621.1)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from issue description</li>
         <li>Verified changing network on panel reflects on widget and vice-versa</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/169475269-4b42e88c-68e4-4552-9746-e4e8bc0cc756.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/169476263-f366ea73-2ab0-4763-b816-2d3c31880459.mov>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/169476343-68d38ac2-796a-45a9-8f89-ee723894ef9c.mov>
      </td>
   </tr>
</table>
