### ISSUE TITLE
[De-AMP] Regex does not check for empty value of ⚡ attribute

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#22573]
From: https://bravesoftware.slack.com/archives/C03BE3VNL06/p1651027881491089?thread_ts=1650911256.912569&cid=C03BE3VNL06

"Regarding the buggy behavior: Our amp-detection (in part) looks for the ⚡ attribute without an explicit value (i.e. [⚡] vs [⚡=''] ). When the attribute is followed by ='', it no longer matches our current regular expression.
There is no reason why a web-author would provide the empty value, so this pattern is not likely to be encountered often, if ever, in the wild. That said, we found a scenario today which could yield this pattern.
When setting out to test an NBCNews AMP page locally, I downloaded the page via right-click, Save As on Windows. This process modifies the markup in a couple ways, one of which includes adding ='' after the ⚡ attribute.
So if an individual were to download an AMP page (via Save As), and re-upload it elsewhere, we would not properly bounce/redirect visitors to the second version."

We have this check for amp="", but not ⚡=""

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.40.75 Chromium: 102.0.5005.61 (Official Build) beta (x86_64)
-- | --
Revision | 0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}
OS | macOS Version 12.5 (Build 21G5027d)

**Followed the testplan/steps from https://github.com/brave/brave-core/pull/13182#issue-1216778702**

### Steps:
1. installed `1.40.75`
2. launched Brave
3. loaded `https://shivankaul.com/brave/de-amp/test-amp-lightning-empty-attribute.html` and confirmed it redirected to `brave.com`, with `Auto-redirect AMP pages` toggled to `ON`/`Enabled` in `brave://settings/shields`
4. new profile
5. toggled `Auto-redirect AMP pages` to `OFF`/`Disabled` via `brave://settings/shields`
6. loaded `https://shivankaul.com/brave/de-amp/test-amp-lightning-empty-attribute.html` and confirmed it did **NOT** redirect

Auto-redirect `ON` | Auto-redirect `OFF`
--------------------|----------------------
<img width="1312" alt="Screen Shot 2022-05-27 at 4 46 52 PM" src="https://user-images.githubusercontent.com/387249/170801321-e20627d0-a7f9-49bd-8b46-0bba3adc6c78.png"> |<img width="1312" alt="Screen Shot 2022-05-27 at 4 48 22 PM" src="https://user-images.githubusercontent.com/387249/170801325-a7ed2085-e476-4583-87da-24be86f12145.png">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.40.80 Chromium: 102.0.5005.78 (Official Build) beta (64-bit)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | Windows 11 Version 21H2 (Build 22000.675)
```

Followed the testplan/steps from https://github.com/brave/brave-core/pull/13182#issue-1216778702

Steps:

- Installed 1.40.80
- Launched Brave
- Loaded `https://shivankaul.com/brave/de-amp/test-amp-lightning-empty-attribute.html` and confirmed it redirected to brave.com, with `Auto-redirect AMP pages` toggled to `ON`/`Enabled` in `brave://settings/shields`
- New profile
- Toggled `Auto-redirect AMP pages` to `OFF`/`Disabled` via `brave://settings/shields`
-  Loaded https://shivankaul.com/brave/de-amp/test-amp-lightning-empty-attribute.html and confirmed it did NOT redirect

Auto-redirect `ON`|Auto-redirect `OFF`
----|----
<img width="950" alt="image1" src="https://user-images.githubusercontent.com/98358127/171294244-5907c7d0-eb0a-4b9b-8283-d1cc8c84d82c.png">|<img width="950" alt="image2" src="https://user-images.githubusercontent.com/98358127/171294270-416a30ee-ae37-4462-b7de-6c23f4bdb7b4.png">

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+` running `Android 12` using the following build(s):

```
Brave | 1.40.101 Chromium: 103.0.5060.42 (Official Build) (64-bit)
--- | ---
Revision | de0d840bf9439c31bd86bf74f065c31fdf9b208d-refs/branch-heads/5060@{#667}
OS | Android 12; Build/SP1A.210812.016
```

Went through the STR/Cases outlined via https://github.com/brave/brave-core/pull/13182#issue-1216778702 as per the following:

* installed/launched `1.40.101 Chromium: 103.0.5060.42`
* loaded `https://shivankaul.com/brave/de-amp/test-amp-lightning-empty-attribute.html` and ensured that it redirected to `brave.com`, with `Auto-redirect AMP pages` toggled to `ON`/`Enabled` via `Settings` -> `Brave Shields & privacy`
* removed/re-installed to launch `1.40.101 Chromium: 103.0.5060.42` via a new profile
* toggled  `Auto-redirect AMP pages` to `OFF`/`Disabled` via `Settings` -> `Brave Shields & privacy`
* loaded `https://shivankaul.com/brave/de-amp/test-amp-lightning-empty-attribute.html` and ensured it did **NOT** redirect

Auto-redirect `ON` | Auto-redirect `OFF`
--------------------|----------------------
![image](https://user-images.githubusercontent.com/2602313/174231596-1909b71e-304c-4929-8ee1-2f2892554d55.png) | ![image](https://user-images.githubusercontent.com/2602313/174231742-b1b792a8-a799-482c-83a8-b5166a8095a6.png)
