### ISSUE TITLE
Race condition could lead to startup ping not having referral code

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#2258]
The stats updater used to run 2 minutes after startup, but we recently changed it to run 3 seconds after startup. This introduces the potential for a race condition as we initialize our referral 3 seconds after startup as well. If we happen to initialize the referral first, then the usage ping will contain the referral code. However, if the usage ping occurs first it won't contain the referral code.

In order to address this, when the stats updater's startup ping fires it should check if we've read the promo code file yet. If we have, then it can continue as normal. If we haven't read the promo code file yet, it should kick off the startup ping timer again.

**Comment by kjozwiak** [comment]
@emerick could you please add a test plan that QA can use to make sure this is working as expected?

**Comment by kjozwiak** [comment]
@emerick I think there's still an issue here with the race condition. I've ran into this twice already where the ping was using `ref=none` even though there was a `promoCode` within the folder which was removed at startup. Here's an example of a ping that had a `promoCode` with `BRA941` which was removed at startup but still appeared as `ref=none`:

```[20331:775:1129/115848.724716:VERBOSE1:brave_stats_updater.cc(145)] Brave stats ping, url: https://laptop-updates.brave.com/1/usage/brave-core?platform=osx-bc&channel=beta&version=0.57.8&daily=true&weekly=true&monthly=true&first=true&woi=2018-11-26&ref=none```

Here's the STR that I've been using:

* create a `promoCode` under `~/Library/Application\ Support/BraveSoftware/Brave-Browser-Beta/`
* ensure that the referral being used is a valid production code
* launch brave using `/Applications/Brave\ Browser\ Beta.app/Contents/MacOS/Brave\ Browser\ Beta --enable-logging --v=1`
* wait till the `promoCode` is removed from  `~/Library/Application\ Support/BraveSoftware/Brave-Browser-Beta/` and close the browser
* open `chrome_debug.log` and look for the ping

I'll try it a few more times and see if I can get more pings with the referral missing but this is the second time I've ran into the above after going through the above ~8-10 times.

**Comment by kjozwiak** [comment]
Quickly talked to @emerick, looks like the above didn't make it into `0.57.8`:

* https://github.com/brave/brave-core/commits/0.57.x

Probably should have checked first but at least I know how a broken case looks like now 👍

**Comment by kjozwiak** [comment]
Went through verification using the following build under `Ubuntu 18.04 x64` - **PASSED**

Brave | 0.57.12 Chromium: 71.0.3578.75 (Official Build) (64-bit)
--- | ---
Revision | 06ef00b5279f93f8e0c1e73acedd49d7dcc09767-refs/branch-heads/3578@{#836}
OS | Mac OS X

Using the following referral codes, went through https://github.com/brave/brave-browser/issues/2258#issuecomment-442914680 5x each and ensured that that referral code was always appearing in the ping:

```[28055:775:1203/131028.364117:VERBOSE1:brave_stats_updater.cc(155)] Brave stats ping, url: https://laptop-updates.brave.com/1/usage/brave-core?platform=osx-bc&channel=release&version=0.57.12&daily=true&weekly=true&monthly=true&first=true&woi=2018-12-03&ref=KJO527```

```[28264:775:1203/131521.478903:VERBOSE1:brave_stats_updater.cc(155)] Brave stats ping, url: https://laptop-updates.brave.com/1/usage/brave-core?platform=osx-bc&channel=release&version=0.57.12&daily=true&weekly=true&monthly=true&first=true&woi=2018-12-03&ref=RED194```

```[28577:775:1203/134411.557578:VERBOSE1:brave_stats_updater.cc(155)] Brave stats ping, url: https://laptop-updates.brave.com/1/usage/brave-core?platform=osx-bc&channel=release&version=0.57.12&daily=true&weekly=true&monthly=true&first=true&woi=2018-12-03&ref=KAM253```
