### ISSUE TITLE
Add direct routes to specific Wallet Onboarding pages

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#22589]
## Description 

Add routes to directly open a specific Wallet onboarding step, so that the user can continue where they left off.

## Expected result:

All wallet onboarding steps of `wallet/crypto/onboarding` should have a corresponding URL

- Create password: `/crypto/onboarding/create-password`
- Backup wallet: `/crypto/onboarding/backup-wallet`
- Onboarding import from MetaMask = `/crypto/onboarding/import-metamask-wallet`
- Onboarding import from legacy crypto wallet = `/crypto/onboarding/import-legacy-wallet`

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.41.93 Chromium: 103.0.5060.114 (Official Build) (64-bit) </th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.708)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from issue</li>
         <li>Verified direct routes to Onboarding and Importing works fine</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/177576551-6b66b50f-eff2-4b9f-b0ec-783a91dcaf8d.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/177576717-d2be5c1d-3c25-49a7-9a8f-dc6e72f48e50.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/177581752-2686a9a4-140d-4124-ac09-05e9d957eb4c.mov>
      </td>
   </tr>
</table>
