### ISSUE TITLE
Build out NFT GridView

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#22585]
## Description 
Build out the NFT GridView on the `Portfolio` page

![Screen Shot 2022-04-27 at 3 05 58 PM](https://user-images.githubusercontent.com/40611140/165631391-c6762dd2-a126-47b0-b884-da30e5e7149f.png)

**Comment by diracdeltas** [comment]
Mentioned in #22627 but i think we should consider putting this in a chrome-untrusted frame.
