### ISSUE TITLE
Wallet onboarding redesign

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#22591]
## Description

Update the wallet onboarding flow to match this [Figma design](https://www.figma.com/file/oXIiv45pIhF2RGlpEjOfUg/Wallet-onboarding?node-id=0%3A1)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.44.93 Chromium: 105.0.5195.136 (Official Build) beta (64-bit) 
-- | --
Revision | `872774b783d0e674186a3adcd2f92e7aa22a219c-refs/branch-heads/5195_124@{#4}`
OS | Linux

- Verified steps from [brave/brave-core#13146](https://github.com/brave/brave-core/pull/13146)
- Verified new onboarding flow works as per design
- Encountered Filecoin issue from [#25139](https://github.com/brave/brave-browser/issues/25139)

Onboarding | Restore Wallet | Import from MM | Import from CW Extension | Buy/Deposit
-- | -- | -- | -- | --
<video src=https://user-images.githubusercontent.com/17010094/191333987-6083c1cc-ffab-47b5-a555-a56a8fdc6fab.mp4> | <video src=https://user-images.githubusercontent.com/17010094/191334072-3eb479e3-2153-4b2e-9b5f-dacc4a12969b.mp4> | <video src=https://user-images.githubusercontent.com/17010094/191334149-69d23582-48ab-4acf-8fd4-6385616196ac.mp4> | <video src=https://user-images.githubusercontent.com/17010094/191334514-40414023-596b-4580-8465-b52416ee4a4c.mp4> | <video src=https://user-images.githubusercontent.com/17010094/191334248-295fc7ed-f36c-491a-99e7-8e4e212a4a56.mp4>


------------------------
Verification passed on

Brave | 1.44.93 Chromium: 105.0.5195.136 (Official Build) beta (64-bit) 
-- | --
Revision | `872774b783d0e674186a3adcd2f92e7aa22a219c-refs/branch-heads/5195_124@{#4}`
OS | Windows 11 Version 21H2 (Build 22000.795)

- Verified steps from [brave/brave-core#13146](https://github.com/brave/brave-core/pull/13146)
- Verified new onboarding flow works as per design
- Encountered Filecoin issue from [#25139](https://github.com/brave/brave-browser/issues/25139)

Onboarding | Restore Wallet | Import from MM | Import from CW Extension | Buy/Deposit Flow
-- | -- | -- | -- | --
<video src=https://user-images.githubusercontent.com/17010094/191321802-75dcee57-9331-4bf7-a016-10a249afbd7e.mp4> | <video src=https://user-images.githubusercontent.com/17010094/191321898-ef1900df-1e65-4a7e-9707-8d4e7833cbab.mp4> | <video src=https://user-images.githubusercontent.com/17010094/191321884-25483b41-93d8-4ed7-9211-8a4afd828e3d.mp4> | <video src=https://user-images.githubusercontent.com/17010094/191321879-92a0d00c-5d86-47f1-aa0c-8625e80d04ce.mp4> | <video src=https://user-images.githubusercontent.com/17010094/191321852-2e22e1f2-18a5-4444-b172-7381eb54b461.mp4>

------------------------
Verification passed on

Brave | 1.44.93 Chromium: 105.0.5195.136 (Official Build) beta (arm64)
-- | --
Revision | `872774b783d0e674186a3adcd2f92e7aa22a219c-refs/branch-heads/5195_124@{#4}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [brave/brave-core#13146](https://github.com/brave/brave-core/pull/13146)
- Verified new onboarding flow works as per design
- Encountered Filecoin issue from [#25139](https://github.com/brave/brave-browser/issues/25139)

Onboarding | Restore Wallet | Import from MM | Import from CW Extension | Buy/Deposit
-- | -- | -- | -- | --
<video src=https://user-images.githubusercontent.com/17010094/191328051-1f48c1b8-f36a-4a93-96f0-32566f892b1c.mov> | <video src=https://user-images.githubusercontent.com/17010094/191329027-6756f0ca-3278-4eb8-9913-3d0e40fab739.mov> | <video src=https://user-images.githubusercontent.com/17010094/191329824-9c23c147-c90d-478e-a37f-d1c337934b5e.mov> | <video src=https://user-images.githubusercontent.com/17010094/191330320-1345ed36-e832-4e98-a948-fd95c1bdaace.mov> | <video src=https://user-images.githubusercontent.com/17010094/191331056-e00eccd3-0a78-436d-af23-2dfe5dfcb690.mov>
