### ISSUE TITLE
Separate Settings WebUI strings into its own GRDP file.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#22592]
`app/brave_generated_resources.grd` strings file has become quite crowded.
Let's split out Setting WebUI strings into a separate part (`app/brave_settings_strings.grdp`).

**Test plan**

Please, give a once over to the brave://settings to check if any strings don't appear correctly.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.40.86 Chromium: 102.0.5005.78 (Official Build) beta (x86_64)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | macOS Version 12.4 (Build 21F79)
```
