### ISSUE TITLE
Brave opens after quitting

### ISSUE THREAD

**Issue by DarthGigi** [brave/brave-browser#22595]
## Description 

On macOS, when quitting Brave, Brave reopens automatically.

## Steps to Reproduce

   1. Right-click the Brave app
   2. Select Quit (or hold Option and select Force Quit)
   3. Click on Quit (or Force Quit)

## Actual result:

Reopens after quitting.
Video: [Brave reopens after quitting](https://cln.sh/z9MupU)
Note: I'm not pressing any keys on my keyboard, so no shortcuts are being executed.

## Expected result:
Does not reopen after quitting like a normal macOS app.

## Reproduces how often: 
Easily reproduced (almost every time, 99%)

## Brave version (brave://version info)
1.38.109 Chromium: 101.0.4951.41 (Official Build) (x86_64) 
macOS Version 12.3.1 (Build 21E258)

## Version/Channel Information:
- Can you reproduce this issue with the current release? 
  - Yes
- Can you reproduce this issue with the beta channel? 
  - Not sure
- Can you reproduce this issue with the nightly channel? 
  - Not sure 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
  - No
- Does the issue resolve itself when disabling Brave Rewards? 
  - No
- Is the issue reproducible on the latest version of Chrome? 
  - Haven't tested it

## Miscellaneous Information:

Warn Before Quitting is turned off

**Comment by GitMyAccount** [comment]
This is still an issue as of 5/23/25 with MacOS Sequoia 15.5
