### ISSUE TITLE
Disable Network Filter Submenus if Testnetworks are disabled

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#22590]
## Description 
Disable Network Filter Submenus if Testnetworks are disabled in prefs.
![Screen Shot 2022-04-27 at 4 38 26 PM](https://user-images.githubusercontent.com/40611140/165642988-1f0514a5-3c6b-4467-9881-f0cd8ceca21f.png)

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.40.68 Chromium: 102.0.5005.50 (Official Build) beta (64-bit) </th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>f6e2cf8f59ec714bdcff8499991d55898875f287-refs/branch-heads/5005@{#648}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22621.1)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/13200>brave/brave-core#13200</a></li>
         <li>Verified when <code>Show test networks</code> setting is disabled, Network filter doens't show </li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/169980246-31dc093e-a2c8-4153-87e2-57ffd7ca53e1.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/169980287-b210b003-9a38-4fae-8583-c67365821456.mov>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/169980259-e7542ecc-cb6c-4c75-8d33-548480eb3b79.mov>
      </td>
   </tr>
</table>

**Comment by kjozwiak** [comment]
We'll need a quick spot check on `1.39.x` 👍 Used the verifications https://github.com/brave/brave-browser/issues/22590#issuecomment-1135539286 to uplift into `1.39.x`.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.39.117 Chromium: 102.0.5005.78 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>8888ee7a24e2c36661ddb9536c35b7d4852a3a98-refs/branch-heads/4951@{#1230}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22621.1)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td>
      </td>
      <td colspan=3>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/13200>brave/brave-core#13200</a></li>
         <li>Verified when <code>Show test networks</code> setting is disabled, Network filter doens't show </li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/171870314-52785f70-c47e-4bbb-bd18-2e57ed953fd9.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/171869140-1e32f629-bfe5-4b05-b990-7d2a0d0f94b9.mov>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/171870239-09ad50ef-3116-4e9f-b227-008972ba851e.mov>
      </td>
   </tr>
</table>
