### ISSUE TITLE
Download Torrent Buttons are misplaced

### ISSUE THREAD

**Issue by lkyuchukov** [brave/brave-browser#22596]
## Description 
Start Torrent/Save Torrent File/Copy Magnet Link buttons seem to be misplaced. 

## Steps to Reproduce

   1. Launch Brave and open https://webtorrent.io/torrents/big-buck-bunny.torrent 
   2. The Start Torrent/Save Torrent File seem to be awkwardly placed one above the other
   3. The same applies for magnet links 

## Actual result:
<img width="946" alt="Screenshot 2022-04-28 at 12 56 54" src="https://user-images.githubusercontent.com/45465568/165728154-d553f73d-2eac-4f27-8905-eafb02ec56c2.png">

## Expected result:
Buttons are placed one next to another with sufficient margin between them and the title of the torrent. 

## Reproduces how often: 
Everytime

## Brave version (brave://version info)

```
Brave | 1.37.116 Chromium: 100.0.4896.127 (Official Build) (arm64)
Revision | ff0d0695743e65305d7194f9bd309e5e1c824aa0-refs/branch-heads/4896_88@{#4}
OS | macOS Version 12.0.1 (Build 21A559)
```

## Version/Channel Information:
- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No such functionality in Chrome AFAIK

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.44.21 Chromium: 104.0.5112.81 (Official Build) nightly (x86_64)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | macOS Version 11.6.8 (Build 20G730)

### Confirmed:
* vastly improved layout (thanks @fallaciousreasoning !)
* `Stop Torrent` button stops and resets the file transfer (for both `.torrent` and `magnet:?` links)
* `Start Torrent` begins file transfer
* `Copy Magnet Link` populates the clipboard with the URI
* `Save .torrent File` prompts to save `big-buck-bunny.torrent`
* no 

`.torrent` file | `magnet:?` link 
-|-
<img width="1312" alt="Screen Shot 2022-08-05 at 3 19 59 PM" src="https://user-images.githubusercontent.com/387249/183219030-0168d299-aacf-4cea-80f5-f39e9ea0fb71.png"> | <img width="1312" alt="Screen Shot 2022-08-05 at 3 21 05 PM" src="https://user-images.githubusercontent.com/387249/183219038-e740f7a7-53c7-4bd0-9b39-a76638a11734.png">
