### ISSUE TITLE
Apple Music has improper font spacing

### ISSUE THREAD

**Issue by pilgrim-brave** [brave/brave-browser#22605]
![image](https://user-images.githubusercontent.com/43750833/165798567-441169c2-2a40-4ca9-9939-c45b239cd0f9.png)

**Comment by pilgrim-brave** [comment]
Turning off font whitelisting fixes it

**Comment by stephendonner** [comment]
@pilgrim-brave do you have a test plan you could attach, and/or expected-results screenshot?  Were you logged in or out (or does it matter?). Thanks!

Brave | 1.40.77 Chromium: 102.0.5005.61 (Official Build) beta (x86_64)
-- | --
Revision | 0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}
OS | macOS Version 11.6.6 (Build 20G624)



So far, I've:
1. installed `1.40.77`
2. launched Brave
3. loaded `https://music.apple.com/us/album/the-baby-teeth-album/64868585`
4. compared layout to `1.39.111`

`1.39.111` | `1.40.77`
----------|--------
<img width="1198" alt="Screen Shot 2022-05-27 at 4 06 54 PM" src="https://user-images.githubusercontent.com/387249/170798993-fcebb10e-c415-47fb-a559-7787df04a074.png"> | <img width="1281" alt="Screen Shot 2022-05-27 at 4 12 59 PM" src="https://user-images.githubusercontent.com/387249/170799231-a65beb6a-f784-42df-aa64-4b3437880ee7.png">

**Comment by pilgrim-brave** [comment]
Yes, that exactly shows the issue (being fixed). No further test plan required.

**Comment by kjozwiak** [comment]
Removed `QA Pass-macOS` as this was uplifted into` 1.39.x` as per https://github.com/brave/brave-core/pull/13550 and will need to be rechecked using `1.39.x` once we get the correct RC builds. Used the verification outlined via https://github.com/brave/brave-browser/issues/22605#issuecomment-1140097227 for the uplift as per https://github.com/brave/brave-core/pull/13550#pullrequestreview-993057322.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.39.117 Chromium: 102.0.5005.78 (Official Build) (x86_64)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | macOS Version 11.6.6 (Build 20G624)

### Steps:

1. installed `1.39.117`
2. launched Brave
3. loaded `https://music.apple.com/us/album/the-baby-teeth-album/64868585`
4. checked both `Light` and `Dark` modes

#### Confirmed font-spacing/layout is correct.

`Dark` | `Light`
-------|--------
<img width="1312" alt="Screen Shot 2022-06-03 at 9 28 14 AM" src="https://user-images.githubusercontent.com/387249/171907025-3393c12b-0819-414b-8fe8-f68ea6feb4d6.png"> |<img width="1312" alt="Screen Shot 2022-06-03 at 9 28 27 AM" src="https://user-images.githubusercontent.com/387249/171907034-555bf9b1-7514-469f-9786-c160477e6297.png">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using

Brave | 1.39.117 Chromium: 102.0.5005.78 (Official Build) (64-bit)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | Windows 11 Version 21H2 (Build 22000.675)

Followed test plan by @stephendonner 

- installed 1.39.117
- launched Brave
- loaded https://music.apple.com/us/album/the-baby-teeth-album/64868585
- compared layout to 1.39.111
(Not seeing specific issue (improper font spacing)  in 1.39.111 for Win 11x64)

1.39.111|1.39.117
---|---
<image width="850" alt="image1" src="https://user-images.githubusercontent.com/98358127/171906189-05ac62b6-aefd-44b1-855b-fb9d2c9299eb.png">|<image width="850" alt="image1" src="https://user-images.githubusercontent.com/98358127/171906375-749b4bc8-21ca-4041-9b2d-24a68db302cd.png">
