### ISSUE TITLE
Windows Media control popup re-appeared after last update

### ISSUE THREAD

**Issue by pilsnerbeer** [brave/brave-browser#22608]
## Description 
title. I had a custom setting in brave://flags that disabled this popup but I can't find it anymore .. did it disappear?

![Screenshot_1](https://user-images.githubusercontent.com/36133540/165820566-4365304c-97de-4df2-932b-8618586f9acc.png)

## Steps to Reproduce
1 play music on brave (youtube music for example)
2 annoying windows popup will appear

## Actual result:
media popup visible

## Expected result:
popup invisible since i disabled it earlier

## Reproduces how often: 
always

## Brave version (brave://version info)
<html>
<body>

Brave | 1.38.109 Chromium: 101.0.4951.41 (Official Build) (64-bit)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | Windows 10 Version 21H2 (Build 19044.1645)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by Rowsol** [comment]
Ugh... 
I hope this gets resolved.

**Comment by almdandi** [comment]
Same here. Really annoying. Under `brave://flags` the `#hardware-media-key-handling` setting is missing

**Comment by indig0F10w** [comment]
Disable both:
chrome://flags/#hardware-media-key-handling
chrome://flags/#global-media-controls-modern-ui

**Comment by almdandi** [comment]
With version `1.38.111 Chromium: 101.0.4951.54 ` the settings shows up again.

Thanks for fixing

**Comment by nsklaus** [comment]
> Disable both: chrome://flags/#hardware-media-key-handling chrome://flags/#global-media-controls-modern-ui

this doesn't work if wallet and sidebar button are disabled too, then the media button comes back despite the two flags listed above.

**Comment by almdandi** [comment]
Hallo

Since yesterday the media overlay is showing up again for example for yt videos. Also the media keys will control the first tab open with media.

Both flags mentioned above are gone.

Brave Version 1.64.109, Chromium: 123.0.6312.58

**Comment by indig0F10w** [comment]
Since flags have been removed you can add this on the shortcuts target.
--disable-features=HardwareMediaKeyHandling
When you are done it should look something like this:
![Capture123](https://github.com/brave/brave-browser/assets/17021548/fc6a1d49-3d0d-496c-9e80-312a59812bb0)

A warm hail Satan and credits go to this video: https://www.youtube.com/watch?v=pBPTFg3GcLo
