### ISSUE TITLE
"Sadly, no tokens yet" after importing wallet with non-zero balance

### ISSUE THREAD

**Issue by garrettr** [brave/brave-browser#2260]
## Description 
After importing a funded Brave Payments wallet into Brave Rewards, the Rewards Settings page shows the correct non-zero balance for the wallet, but continues to show the "Sadly, no tokens yet" sidebar. This is confusing because it contradicts the existence of the tokens from the imported wallet, which are reflected in the displayed non-zero wallet balance.

## Test plan / Steps to Reproduce

1. Import Muon/Brave Payments wallet into b-c/Brave Rewards (detailed test plan in brave/brave-core#736).
2. Click Brave Rewards icon in address bar, then Rewards Settings in the dropdown.

## Actual result:
![screen shot 2018-11-27 at 2 24 57 pm](https://user-images.githubusercontent.com/407302/49116169-a5a31000-f251-11e8-9cf1-7d1e9d18628f.png)

## Expected result:
If the wallet balance is zero, the sidebar should not say "no tokens yet."

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Brave | 0.59.1 Chromium: 71.0.3578.53 (Developer Build) (64-bit)
-- | --
Revision | 599fb72e740eab9d10609f1ed28a2ad669f82c1a-refs/branch-heads/3578@{#669}

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds?
Yes

**Comment by LaurenWags** [comment]
Still experiencing this with 

Brave | 0.57.17 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

![screen shot 2018-12-05 at 6 02 54 pm](https://user-images.githubusercontent.com/28145373/49549865-01a40f00-f8b8-11e8-933d-04643cf49fef.png)

**Comment by btlechowski** [comment]
Also reproducible on Windows:

Brave | 0.57.17 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Windows 7

**Comment by LaurenWags** [comment]
Using the below build

Brave | 0.57.17 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

Found that issue was not fixed, logged follow up issue https://github.com/brave/brave-browser/issues/2379
