### ISSUE TITLE
Missing string 'noActivity' in Rewards Panel

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#2261]
![image](https://user-images.githubusercontent.com/34715963/49113161-17e91400-f295-11e8-9ca6-f891dc3b43b5.png)

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta(64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

* Clean profile, enabled Rewards from BAT Logo. Verified 'MISSING: noActivity' not displayed:
![screen shot 2018-12-10 at 5 36 01 pm](https://user-images.githubusercontent.com/28145373/49766108-44902900-fca2-11e8-8e17-94baf622e88a.png)

* Existing profile (rewards was already enabled). Verified 'MISSING: noActivity' not displayed:
![screen shot 2018-12-10 at 5 39 39 pm](https://user-images.githubusercontent.com/28145373/49766218-9933a400-fca2-11e8-8d70-648ff7231b64.png)
* Logged https://github.com/brave/brave-browser/issues/2437 which was found while testing this issue
