### ISSUE TITLE
Implement search conversion promo's omnibox option

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#22616]

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.41.76 Chromium: 103.0.5060.53 (Official Build) beta (x86_64)
--|--
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | macOS Version 11.6.7 (Build 20G630)

### Button type

1. installed `1.41.76`
2. launched Brave using `--enable-features=BraveSearchOmniboxButton` command-line switch
3. set `Search engine used in the address bar` to `DuckDuckGo`
4. typed `brunch` and confirmed `Try Brave Search` button promo

`Dark` | `Light`
-------|--------
<img width="1312" alt="Screen Shot 2022-06-22 at 9 59 47 AM" src="https://user-images.githubusercontent.com/387249/175095876-a5469abb-2af5-49d1-a728-690a93d3df2d.png">


### Banner type

1. installed `1.41.76`
2. launch Brave using `--enable-features=BraveSearchOmniboxBanner` command-line switch
3. set `Search engine used in the address bar` to `Ecosia`
4. typed `brunch` and confirmed `Try Brave Search` banner promo

`Dark` | `Light`
-------|--------
<img width="1312" alt="Screen Shot 2022-06-22 at 9 57 37 AM" src="https://user-images.githubusercontent.com/387249/175095979-7fa4dc68-735c-4447-bae1-42cf144818d7.png"> | <img width="1312" alt="Screen Shot 2022-06-22 at 9 57 21 AM" src="https://user-images.githubusercontent.com/387249/175096052-40ccd3e9-ea4a-46f2-a552-e686578ca2c9.png">



### Private Browsing - banner

1. installed `1.41.76`
2. launch Brave using `--enable-features=BraveSearchOmniboxBanner` command-line switch
3. set `Search engine used in the address bar` to `Ecosia`
4. typed `brunch` and confirmed NO `Try Brave Search` banner promo

button | banner
-------|--------


### Private Browsing with Tor

1. installed `1.41.76`
2. launch Brave using `--enable-features=BraveSearchOmniboxBanner` command-line switch
3. set `Search engine used in the address bar` to `Ecosia`
4. typed `brunch` and confirmed NO `Try Brave Search` banner promo

button | banner
-------|--------


### Guest

1. installed `1.41.76`
2. launch Brave using `--enable-features=BraveSearchOmniboxBanner` command-line switch
3. set `Search engine used in the address bar` to `Ecosia`
4. typed `brunch` and confirmed NO `Try Brave Search` banner promo

button | banner
-------|--------


### When first item is not keyword match from default provider, promotion match will not be added because first item is highly recommended match

### When dismissed button or x button clicked, autocomplete match list are refreshed with same input data and promotion match will not be shown anymore.

### When user types an input that was tried by promotion match, promotion match will not be shown again. Instead promotion url could be visible as a history match.

### This conversion promotion is only enabled for below 5 countries
US, CA, DE, FR, GB

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

### Linux

### Button-type promo - `PASSED`
<details>

1. installed `1.41.82`
2. launched Brave using `--enable-features=BraveSearchOmniboxButton` command-line switch
3. set `Search engine used in the address bar` to `Startpage`
4. typed `typical search term` and confirmed `Try Brave Search` button promo
5. clicked on `Try Brave Search` button and confirmed it loaded `https://search.brave.com/search?q=brunch&action=makeDefault`

`Dark` | `Light` | `Try Brave Search` button
-------|--------|-----------
<img width="1301" alt="Screen Shot 2022-06-28 at 3 58 56 PM" src="https://user-images.githubusercontent.com/387249/176319296-abdbb493-af33-42e2-b48a-cbfbac1ecb4e.png"> | <img width="1301" alt="Screen Shot 2022-06-28 at 3 59 11 PM" src="https://user-images.githubusercontent.com/387249/176319217-aa593554-1c25-4cde-b8c6-2ffe86dbc59d.png"> | <img width="1301" alt="Screen Shot 2022-06-28 at 4 00 51 PM" src="https://user-images.githubusercontent.com/387249/176319218-3d6ebda8-d711-407b-9da8-487f28ad59d8.png">



</details>

### Banner-type promo - `.`
<details>

1. installed `1.41.82`
2. launched Brave using `--enable-features=BraveSearchOmniboxBanner` command-line switch
3. set `Search engine used in the address bar` to `Startpage`
4. typed `typical search term` and confirmed `Try Brave Search` banner promo
6. click on `Try Brave Search` button and confirmed `https://search.brave.com/search?q=brunch&action=makeDefault` loaded

`Dark` | `Light` | `Try Brave Search` URL
-------|---------|-----


</details>

### Private Browsing - `.`
<details>

1. installed `1.41.782`
2. launched Brave using `--enable-features=BraveSearchOmniboxButton` command-line switch
3. set `Search engine used in the address bar` to `Startpage`
4. typed `typical search term` and confirmed NO `Try Brave Search` banner promo
7. repeated the above with `--enable-features=BraveSearchOmniboxBanner` command-line switch
8. confirmed no promotional banners appeared

button | banner
-------|--------




</details>

### Private Browsing with Tor - `.`
<details>

1. installed `1.41.82`
2. launched Brave using `--enable-features=BraveSearchOmniboxButton` command-line switch
3. set `Search engine used in the address bar` to `Startpage`
4. typed `typical search term` and confirmed NO `Try Brave Search` banner promo
5. repeated the above with `--enable-features=BraveSearchOmniboxBanner` command-line switch
6. confirmed no promotional banners appeared

button | banner
-------|--------




</details>

### Guest - `.`
<details>

1. installed `1.41.82`
2. launched Brave using `--enable-features=BraveSearchOmniboxButton` command-line switch
3. set `Search engine used in the address bar` to `Startpage`
4. typed `typical search term` and confirmed NO `Try Brave Search` banner promo
5. repeated the above with `--enable-features=BraveSearchOmniboxBanner`

button | banner
-------|--------




</details>

### User-keyword matching - `.`

#### URL-visit/history precedence - `.`
<details>

1. install `1.41.82`
2. launch Brave
3. load `brave.com`
4. now, type `brave.com` but don't press `return`/`enter`
5. confirm the 1st populated result in the URL bar is from the `brave.com` history entry from step 3
6. confirm the 2nd populated result in the URL bar is the `🔍 brave - Brave Search`

</details>

#### promotional Brave Search entry - `.`
<details>

1. install `1.41.82`
2. launch Brave
3. now, type `brave.com` but don't press `return`/`enter`
4. confirm the 1st populated result in the URL bar is the promotional `🔍 brave.com - Brave Search` entry




</details>

### Dismiss button / `x` widget - `.`

Pre-requisite/setup:
* run `Button type` and `Banner type` tests (separately)

<details>

(with a search for `typical search term` already made)

`Button:`

1. typed `typical search term` again
9. clicked on `x` to dismiss the button promo
10. typed `typical search term` again
11. confirmed no promo shown
12. typed `dinner`
13. confirmed no promo shown

`x` widget | `brunch` search | `dinner` search
-----------|------------------|----------------




`Banner:`

1. typed `brunch` again
2. clicked on `Dismiss` to dismiss the button promo
3. typed `brunch` again
4. confirmed no promo shown
7. typed `dinner`
8. confirmed no promo shown

`Dismiss` button | `brunch` search | `dinner` search
-----------|------------------|----------------




</details>

### Repeat-matching input - `.`

Pre-requisite/setup:
* run `Button type` and `Banner type` tests (separately)

<details>

1. typed `typical search term`
14. clicked on `Try Brave Search`
15. confirmed `https://search.brave.com/search?q=typical&20&search&20term&action=makeDefault` loads
16. typed `typi` again
17. confirmed the promotional button/banner was removed
18. confirmed the search showed up in autocomplete history

`typical search term` - button | `typi` - banner
-------|--------


Also confirmed that changing the search term brings the promotions back.

`typical search term` - button | `typi` - banner
--------------------|------------------





</details>

### Promo-enabled countries - `PASSED`
<details>

#### `CA`

button | banner
-------|--------
<img width="1680" alt="Screen Shot 2022-06-22 at 11 43 09 AM" src="https://user-images.githubusercontent.com/387249/175112817-b5880a9f-f9cf-44d4-ad64-ebe39fc98eae.png"> | <img width="1680" alt="Screen Shot 2022-06-22 at 11 44 56 AM" src="https://user-images.githubusercontent.com/387249/175113178-dfefe86c-940a-4e93-8d85-e09a11bd4133.png">

#### `DE`

button | banner
-------|--------
<img width="1680" alt="Bildschirmfoto 2022-06-22 um 12 27 50" src="https://user-images.githubusercontent.com/387249/175121238-50f3f2cb-ffa3-4046-8249-330240df0186.png"> | <img width="1680" alt="Bildschirmfoto 2022-06-22 um 12 28 47" src="https://user-images.githubusercontent.com/387249/175121250-aa108e18-929a-4262-8ac9-796317a5163c.png">


#### `FR`

button | banner
-------|--------
<img width="1680" alt="Capture d’écran 2022-06-22 à 12 17 24" src="https://user-images.githubusercontent.com/387249/175121442-0c82f5a3-2020-4f92-90fd-baa81bab16a0.png"> | <img width="1680" alt="Capture d’écran 2022-06-22 à 12 18 12" src="https://user-images.githubusercontent.com/387249/175121451-1873b735-f256-408a-9f46-5aa2fb322f9d.png">



#### `GB`

button | banner
-------|--------
<img width="1680" alt="Screenshot 2022-06-22 at 12 33 32" src="https://user-images.githubusercontent.com/387249/175121817-60cda6a0-b825-45af-9311-dd783dede968.png"> | <img width="1680" alt="Screenshot 2022-06-22 at 12 38 48" src="https://user-images.githubusercontent.com/387249/175122071-9f9407b6-810d-46f8-aba2-10bd248bbaa7.png">





</details>

### Non promo-enabled countries - `PASSED`
<details>

#### `ES`

button | banner
-------|--------
<img width="1292" alt="Captura de pantalla 2022-06-22 a las 11 55 02" src="https://user-images.githubusercontent.com/387249/175115209-6b924307-f19c-481b-af76-6abdba0487bd.png"> | <img width="1269" alt="Captura de pantalla 2022-06-22 a las 11 55 52" src="https://user-images.githubusercontent.com/387249/175115214-bc7aff5b-e1a9-4c96-88b2-38bd6a2fac1a.png">


#### `AU`

button | banner
-------|-------
<img width="1680" alt="Screen Shot 2022-06-22 at 12 02 36 pm" src="https://user-images.githubusercontent.com/387249/175117655-2c46beba-5daa-4740-a73a-7c2a76741413.png"> | <img width="1680" alt="Screen Shot 2022-06-22 at 12 03 22 pm" src="https://user-images.githubusercontent.com/387249/175117668-10d0c71c-3e8b-4d89-bfce-fcf32cd27bc1.png">



#### `IN`

button | banner
-------|--------
<img width="1680" alt="Screenshot 2022-06-22 at 12 09 41 PM" src="https://user-images.githubusercontent.com/387249/175117483-84e0edd9-ccda-4697-894c-5642b0bc1cff.png"> |<img width="1680" alt="Screenshot 2022-06-22 at 12 10 31 PM" src="https://user-images.githubusercontent.com/387249/175117494-76cb979c-32fe-4f82-97d3-bf2bcb0e2e97.png">


</details>

Logged:
https://github.com/brave/brave-browser/issues/23607

**Comment by MadhaviSeelam** [comment]
Verification `In-Progress` using
```
Brave | 1.41.82 Chromium: 103.0.5060.66 (Official Build) beta (64-bit)
-- | --
Revision | 20b1569438a85e631d15e83eb355e3e326e5da6f-refs/branch-heads/5060@{#1066}
OS | Windows 11 Version 21H2 (Build 22000.739)
```

### Button-type promo - `PASSED`
<details>

1. installed `1.41.82`
2. launched Brave using `--enable-features=BraveSearchOmniboxButton` command-line switch
3. go to brave://settings/search and set `Search engine used in the address bar` to `Qwant`
4. typed `social` and confirmed `Try Brave Search` button promo is visible as a second item
5. clicked on `Try Brave Search` button and confirmed it loaded `https://search.brave.com/search?q=brunch&action=makeDefault`
7. Search for another term `app`in another tab and click `x` next to `Try Brave Search`
8. omnibox popup should be dismissed 

`Dark` 
Step 3|Step 4|Step 5|Step 6|Step 7
---|---|---|---|---
<image width="950" alt="step 3" src="https://user-images.githubusercontent.com/98358127/176568447-108682b9-c77e-495a-aaf0-e188e8c69901.png">|<image width="950" alt="step 4" src="https://user-images.githubusercontent.com/98358127/176563657-4637090f-3907-4577-92cc-26041f6a696a.png">|<image width="950" alt="step 3" src="https://user-images.githubusercontent.com/98358127/176563722-02fb35b7-4c4c-417a-a303-53e5aee63741.png">|<img width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/176568676-85889b87-ca87-48cb-9026-d19f2ac2c0e3.png">|<img width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/176568662-64a2aa8c-9b6d-444b-b511-f265728cadc6.png">


`Light` 
Step 3|Step 4|Step 5|Step 6|Step 7
---|---|---|---|---
<image width="950" alt="step 3" src="https://user-images.githubusercontent.com/98358127/176561180-65f41024-e4d5-4fda-bdb7-b2bddfdc3789.png">|<image width="950" alt="step 3" src="https://user-images.githubusercontent.com/98358127/176561423-bdcb6336-686e-4f51-932b-0c73fdfb3808.png">|<image width="950" alt="step 3" src="https://user-images.githubusercontent.com/98358127/176561511-69a6e887-300e-459c-8aea-07caea1fa4c8.png">|<image width="950" alt="step 6" src="https://user-images.githubusercontent.com/98358127/176567603-62cddba4-3427-4f41-bd22-55c64080cf77.png">|<img width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/176568224-80a7fd3c-7b69-4b4b-9da7-30eb5b59cbaf.png">

</details>

### Banner-type promo - `PASSED`
<details>

1. new profile 
2. launched Brave using `--enable-features=BraveSearchOmniboxBanner` command-line switch
3. go to brave://settings/search and set `Search engine used in the address bar` to `Bing`
4. typed `bb` and confirmed `Try Brave Search` banner promo
5. click on `Try Brave Search` button and confirmed `https://search.brave.com/search?q=brunch&action=makeDefault` loaded
7. Search for another term `ab`in another tab and click `Dismiss` 
8. Banner should be dismissed

`Light` 
Step 3|Step 4|Step 5|Step 6|Step 7
---|---|---|---|---
<image width="950" alt="step 3" src="https://user-images.githubusercontent.com/98358127/176564744-26eccd6a-e587-4e75-8abc-fe633de8a05c.png">|<image width="950" alt="step 3" src="https://user-images.githubusercontent.com/98358127/176565793-a9f34f4e-d90c-4019-a4ad-6d2f92b66c46.png">|<image width="950" alt="step 3" src="https://user-images.githubusercontent.com/98358127/176565373-2b69cabb-48f1-476b-a65a-d28268de98f0.png">|<image width="950" alt="step 3" src="https://user-images.githubusercontent.com/98358127/176565604-68ed98a5-dd73-4845-8bb4-9c4019996094.png">|<image width="950" alt="step 3" src="https://user-images.githubusercontent.com/98358127/176568224-80a7fd3c-7b69-4b4b-9da7-30eb5b59cbaf.png">

![image](https://user-images.githubusercontent.com/98358127/176568224-80a7fd3c-7b69-4b4b-9da7-30eb5b59cbaf.png)


`Dark` 
Step 3|Step 4|Step 5|Step 6|Step 7
---|---|---|---|---
<image width="950" alt="step 3" src="https://user-images.githubusercontent.com/98358127/176566123-e6ab821d-a494-46c7-bf23-64a75181c1c2.png">|<image width="950" alt="step 3" src="https://user-images.githubusercontent.com/98358127/176566100-9274c49b-d374-4879-acff-2ec7eef390ca.png">|<image width="950" alt="step 3" src="https://user-images.githubusercontent.com/98358127/176566273-71475d57-0dd2-4ebc-9de6-883a90596c82.png">|<image width="950" alt="step 3" src="https://user-images.githubusercontent.com/98358127/176566333-82c3937d-8086-4970-b062-9d0a3cc4cb9c.png">|<image width="950" alt="step 3" src="https://user-images.githubusercontent.com/98358127/176566377-d42bf7f6-2d44-4c29-83d9-94d9caf80580.png">
