### ISSUE TITLE
Implement Uphold unsupported region error modal

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#22612]
## Description

Uphold unsupported region modal by parsing redirect URL that comes back. 

`https://example.com/?error=invalid_request&error_description=Application%20not%20available%20for%20user%20geolocation`

**Actual:** `brave://rewards/uphold/authorization?error=invalid_request&error_description=Application%20not%20available%20for%20user%20geolocation`

The parameters are:

```
error: 'invalid_request',
error_description: 'Application not available for user geolocation'
```

**Comment by kjozwiak** [comment]
Adding missing `1.40.x` milestone as https://github.com/brave/brave-core/pull/13218 was merged into `master` which is currently on `1.40.x`.

**Comment by kjozwiak** [comment]
Above requires `1.39.89` or higher for `1.38.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.39.89 Chromium: 101.0.4951.41 (Official Build) beta (x86_64)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | macOS Version 12.3.1 (Build 21E258)
```
