### ISSUE TITLE
Auto-redirect AMP pages - Loops - page won't load.

### ISSUE THREAD

**Issue by RonnyTNL** [brave/brave-browser#22610]
## Description 
Loading this ULR causes a AMP redirect loop, page won't load, DevTools network shows looping pageload /amp 

## Steps to Reproduce
   1.  Open URL  https://t.co/0Ydr4haUQd which should land at
   2. https://www.airlive.net/new-footage-shows-an-ukrainian-mig-29-taking-off-from-mykolaiv-seconds-before-the-runway-is-shelled-by-the-russians/
   3.  Watch the Omnibox blink
   4.  Devtools watch the Network tab and see that it loads page then /amp and loops on that

## Actual result:
Page doesn't load (at all)

## Expected result:
Page should load

## Reproduces how often: 
Easy 100%

## Brave version (brave://version info)
[Version 1.38.109 Chromium: 101.0.4951.41 (Official Build) (64-bit)](https://brave.com/latest/)

## Version/Channel Information:
Not tested

- Can you reproduce this issue with the current release? 
- Yes
- Can you reproduce this issue with the beta channel? 
- Not Tested
- Can you reproduce this issue with the nightly channel? 
- Not Tested
- 
## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
No
- Does the issue resolve itself when disabling Brave Rewards? 
No enabled
- Is the issue reproducible on the latest version of Chrome? 
No (because no AMP auto-redirect)

## Miscellaneous Information:
All extensions disabled during testing so that cannot interfere.

**Comment by stephendonner** [comment]
Confirming using 

Brave | 1.39.84 Chromium: 101.0.4951.41 (Official Build) beta (x86_64)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | macOS Version 11.6.5 (Build 20G527)

cc @ShivanKaul 

<img width="1608" alt="Screen Shot 2022-04-28 at 1 41 26 PM" src="https://user-images.githubusercontent.com/387249/165842155-53bd2c5c-d48a-4030-a721-5cca78493874.png">

**Comment by ShivanKaul** [comment]
Looks like https://www.airlive.net/new-footage-shows-an-ukrainian-mig-29-taking-off-from-mykolaiv-seconds-before-the-runway-is-shelled-by-the-russians/ 301 redirects to https://www.airlive.net/new-footage-shows-an-ukrainian-mig-29-taking-off-from-mykolaiv-seconds-before-the-runway-is-shelled-by-the-russians/amp, which is an AMP page, causing a loop. 
cc @bridiver

**Comment by bridiver** [comment]
this STR doesn't properly replicate the problem because we're not redirecting from an amp page to the canonical page

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.40.68 Chromium: 102.0.5005.50 (Official Build) beta (x86_64)
-- | --
Revision | f6e2cf8f59ec714bdcff8499991d55898875f287-refs/branch-heads/5005@{#648}
OS | macOS Version 12.5 (Build 21G5027d)

### Steps:
1. installed `1.40.68`
2. launched Brave
3. opened a new-tab page
4. loaded `https://t.co/0Ydr4haUQd` (`https://www.airlive.net/new-footage-shows-an-ukrainian-mig-29-taking-off-from-mykolaiv-seconds-before-the-runway-is-shelled-by-the-russians/`)

#### Confirmed the page loaded without issue

<img width="1677" alt="Screen Shot 2022-05-24 at 3 09 11 PM" src="https://user-images.githubusercontent.com/387249/170140329-4319e44e-21a0-4466-b19d-051a03089898.png">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.40.80 Chromium: 102.0.5005.78 (Official Build) beta (64-bit)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | Windows 11 Version 21H2 (Build 22000.675)
```
Steps:

- installed 1.40.80
- launched Brave
- opened a new-tab page
- loaded https://t.co/0Ydr4haUQd (https://www.airlive.net/new-footage-shows-an-ukrainian-mig-29-taking-off-from-mykolaiv-seconds-before-the-runway-is-shelled-by-the-russians/)

Confirmed the page loaded without issue

![image](https://user-images.githubusercontent.com/98358127/171292167-77dbafdd-d10e-4461-a254-c55c6508fb15.png)

**Comment by kjozwiak** [comment]
Removed the `QA Pass-Win64` & `QA Pass-macOS` labels as this was uplifted into `1.39.x` via https://github.com/brave/brave-core/pull/13582 and will need a quick recheck using `1.39.x` just to make sure everything is still working on the `1.39.x` branch.

**Comment by MadhaviSeelam** [comment]
Verified `Passed` using
```
Brave | 1.39.117 Chromium: 102.0.5005.78 (Official Build) (64-bit)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | Windows 11 Version 21H2 (Build 22000.675)
```
Steps:

- installed 1.39.117
- launched Brave
- opened a new-tab page
- loaded `https://t.co/0Ydr4haUQd` `(https://www.airlive.net/new-footage-shows-an-ukrainian-mig-29-taking-off-from-mykolaiv-seconds-before-the-runway-is-shelled-by-the-russians/)`
- Confirmed the page loaded without issue

![image](https://user-images.githubusercontent.com/98358127/171881270-baec42c0-3db5-4ed1-9d5d-ee76d24b3f60.png)

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.39.117 Chromium: 102.0.5005.78 (Official Build) (x86_64)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | macOS Version 11.6.6 (Build 20G624)

### Steps:

1. installed `1.39.117`
2. launched Brave
3. opened a new-tab page
4. loaded `https://t.co/0Ydr4haUQd` (`https://www.airlive.net/new-footage-shows-an-ukrainian-mig-29-taking-off-from-mykolaiv-seconds-before-the-runway-is-shelled-by-the-russians/`)


#### Confirmed the page loaded without issue

<img width="1312" alt="Screen Shot 2022-06-03 at 9 21 13 AM" src="https://user-images.githubusercontent.com/387249/171905917-d630269b-7a51-4d3c-94fb-80b8f167ff45.png">

**Comment by Uni-verse** [comment]
Verification completed on Samsung Galaxy S21 running Android 12 using 

```
Brave	1.39.118 Chromium: 102.0.5005.78 (Official Build) (64-bit) 
Revision	df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS	Android 12; Build/SP1A.210812.016
```

https://user-images.githubusercontent.com/17885425/172483684-c0eafd4f-72fd-48e0-8584-950a701a40ea.mp4
