### ISSUE TITLE
Changing selected account does not emit accountsChanged event to ethereum dApps

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#22611]
## Description 
When switching accounts with a dApp open, we should be emitting an `accountsChanged` event
Note: chain change event is also broken.

## Steps to Reproduce
Using [eth-manual-tests](https://github.com/bbondy/eth-manual-tests)
   1. Connect >1 accounts to `eth-manual-tests`
   2. Open wallet panel
   3. Change selected account

## Actual result:
https://user-images.githubusercontent.com/5314553/165846231-beb764b8-c013-48a8-9384-93036e910313.mov

## Expected result:
Video taken from release (Version 1.37.116 Chromium: 100.0.4896.127 (Official Build) (arm64)). 

https://user-images.githubusercontent.com/5314553/165846396-9cb08c05-a22d-47b9-9dfd-e4edaed47d12.mov

## Brave version (brave://version info)
Version 1.40.19 Chromium: 101.0.4951.41 (Official Build) nightly (arm64)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
  -  No
- Can you reproduce this issue with the beta channel? 
  - TBD
- Can you reproduce this issue with the nightly channel? 
  - Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

Tested again with Version 1.38.109 Chromium: 101.0.4951.41 (Official Build) (arm64) and I am seeing the `accountsChanged` event fired

**Comment by kjozwiak** [comment]
The above requires `1.39.101` or higher for `1.39.x` verification 👍

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.39.108 Chromium: 101.0.4951.67 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>8888ee7a24e2c36661ddb9536c35b7d4852a3a98-refs/branch-heads/4951@{#1230}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22621.1)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from issue description</li>
         <li>Verified console logs <code>accountsChanged event: <account address></code> everytime a connected account is changed</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/169277971-3ce62f8e-d555-4a76-9ed4-20071d81f433.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/169279144-95df7236-a020-448c-a62e-9c51b5074f14.mov>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/169279227-637050e2-bcfb-412c-a2f2-f3072f314e51.mov>
      </td>
   </tr>
</table>
