### ISSUE TITLE
Shields Panel

### ISSUE THREAD

**Issue by UjCbFwtBayFM** [brave/brave-browser#22625]
The new Shields Panel is not very good. Add an option to revert to the old one.
Source: https://community.brave.com/t/new-brave-shields-button-now-much-less-useful-for-me/

**Comment by UjCbFwtBayFM** [comment]
Source 2: https://www.reddit.com/r/brave_browser/comments/uehis7/bring_back_the_advanced_view_for_brave_shields/

**Comment by gelatinbomb** [comment]
I would add the size of the panel is kind of big for screen that are smaller than 1080p.
I would recommend to simplify the stuff that appears on the top part of the panel. I'm more interested in the advanced tab settings that the general info at the top part.
Also I noticed I can't block scripts individually anymore. That feature was really amazing. 
Adding some extra options to allow scripts on a tab or that kind of stuff would be great too.
For now I will keep using the v1 version of the brave shields too. But I'm curious about the new functions that you might add in the future so I will see the progress of this.

![image](https://user-images.githubusercontent.com/31792239/166083345-fda682aa-f619-46d1-9f73-1cbb84296a5a.png)

**Comment by Johann999** [comment]
Please revert to Shield V1

**Comment by UjCbFwtBayFM** [comment]
Tried to redesign it a bit (left is current V2)
![braveshields_redesign](https://user-images.githubusercontent.com/22710992/166124595-365e854e-fad5-4b74-9fed-1e968ba6aff1.png)
.

**Comment by UjCbFwtBayFM** [comment]
I also noticed the ability to allow individual scripts is gone.

**Comment by NayamAmarshe** [comment]
+1
The old shield UI was way more modern and compact than this. This one does not even have good contrast between inputs and background, worse UI than before.

78 other people upvoted my post about this:
https://www.reddit.com/r/brave_browser/comments/ui271o/

**Comment by CrashTD** [comment]
Please don't go down the dumbing down UI route. Shield V1 was perfectly fine and there is NO reason to remove features whatsoever. Especially not features that are very useful and that I use regularly..

**Comment by UjCbFwtBayFM** [comment]
Overwhelmingly negative feedback about the Shield redesign:

- https://www.reddit.com/r/brave_browser/comments/ukn55y/problem_with_new_update/
- https://www.reddit.com/r/brave_browser/comments/ujv0tm/we_cant_choose_what_scripts_to_block_in_the_new/
- https://www.reddit.com/r/brave_browser/comments/ujrq2w/please_bring_back_the_old_shields_so_i_can/
- https://www.reddit.com/r/brave_browser/comments/ui271o/the_old_shield_ui_was_way_more_modern_and_compact/
- https://community.brave.com/t/brave-shields-panel-individual-javascript-source-selection-allow-function-lost-with-browser-v1-38-109-update/384302/
- https://community.brave.com/t/give-us-back-the-allow-specific-script-option-on-websites/385676/
- https://community.brave.com/t/new-brave-shield-ui/384392
- https://community.brave.com/t/updated-design-for-brave-shields/383855

**Comment by jtakeshi-nd** [comment]
With the recent update, the workaround of using the flag brave-shields-v1 is no longer available. Can we have this added back, or at least remove the extra click needed to open "Advanced Controls"? This is irritating when I just want a quick way to turn Javascript off/on.

**Comment by rebron** [comment]
@jtakeshi-nd https://github.com/brave/brave-browser/issues/23188 If you leave "Advanced Controls" open it will stay open until you want to close it again.

**Comment by jtakeshi-nd** [comment]
@rebron Thanks for the tip. This seems to only be on a per-window basis, though. It resets to the default (closed) in a new window.

**Comment by bsclifton** [comment]
I'm not sure there's an action we can take here - I'm going to close this issue

We do have a request to add the fine-grained shield controls (ex: block specific scripts) which is tracked here:
https://github.com/brave/brave-browser/issues/24593

Definitely give it a +1 or follow for more info 😄
