### ISSUE TITLE
Wire NFT Details Page to Backend

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#22623]
## Description 
- Show NFT tokens in Portfolio under NFTs list
- Fetch NFT metadata when an NFT is selected

![image](https://user-images.githubusercontent.com/40611140/148090114-58ad9099-357e-48db-8956-2495284a5ae4.png)

## Expected result:

NFTs should be listed in portfolio and when selected should navigate the user to NFTs details page

**Comment by srirambv** [comment]
Reopening the issue as this is now linked with https://github.com/brave/brave-core/pull/13370 which is still open and was reverted https://github.com/brave/brave-core/pull/13217 as confirmed by @muliswilliam. 

We will have to uplift brave/brave-core#13370 once it's merged in case we want this to be part of 1.40.x 

cc: @bbondy @kjozwiak @jamesmudgett

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.44.97 Chromium: 106.0.5249.40 (Official Build) (64-bit) 
-- | --
Revision | `4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}`
OS | Linux

- Verified steps from [brave/brave-core#13370](https://github.com/brave/brave-core/pull/13370)
- Verified able to add NFT as a custom asset lists NFT under NFT's section in portfolio
- Verified able to add multiple NFT's and list 
- Verified clicking on an NFT loads the NFT details view
- Verified NFT details view shows Chain details, Token Standard, Token ID, Description & owner address & any transactions done on the NFT
- Verified NFT details view shows both image and video images 
- Verified able to filter NFT's on portfolio page
- Verified able to filter NFT's based on network filter 
- Verified NFT is loaded in `chrome-untrusted://` iframe
- Encountered [#25588](https://github.com/brave/brave-browser/issues/25588) & [#25590](https://github.com/brave/brave-browser/issues/25590)

chrome://untrusted iframe | NFT details view | NFT listing on all netowrk | NFt listing by filter
-- | -- | -- | --
<img width=280 src=https://user-images.githubusercontent.com/17010094/192011217-1a52a67c-71e8-46f6-8da8-f3df7880a51b.png> | <img width=420 src=https://user-images.githubusercontent.com/17010094/192011951-33a973c5-6143-490d-a034-b005e1801238.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/192011780-5a0a6e7f-933b-469c-b771-4cd2ce2bf8c7.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/192012234-a0892a79-7206-43f9-ba23-ae7b8df8c06c.png>

------------------------
Verification passed on

Brave | 1.44.97 Chromium: 106.0.5249.40 (Official Build) (64-bit) 
-- | --
Revision | `4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}`
OS | Windows 11 Version 21H2 (Build 22000.978)

- Verified steps from [brave/brave-core#13370](https://github.com/brave/brave-core/pull/13370)
- Verified able to add NFT as a custom asset lists NFT under NFT's section in portfolio
- Verified able to add multiple NFT's and list 
- Verified clicking on an NFT loads the NFT details view
- Verified NFT details view shows Chain details, Token Standard, Token ID, Description & owner address & any transactions done on the NFT
- Verified NFT details view shows both image and video images 
- Verified able to filter NFT's on portfolio page
- Verified able to filter NFT's based on network filter 
- Verified NFT is loaded in `chrome-untrusted://` iframe
- Encountered [#25588](https://github.com/brave/brave-browser/issues/25588) & [#25590](https://github.com/brave/brave-browser/issues/25590)

chrome://untrusted iframe | NFT details view | NFT listing on all netowrk | NFt listing by filter
-- | -- | -- | --
<img width=280 src=https://user-images.githubusercontent.com/17010094/192019429-a8a12f62-b7cc-4290-92b0-98f79cf5d549.png> | <img width=420 src=https://user-images.githubusercontent.com/17010094/192019755-65e0b260-df16-46da-96cf-9dc2a78bfac4.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/192019117-d2241377-e396-4ed9-88b0-999803a0e96e.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/192018634-9df28310-c4b9-4ee5-a5d5-08b7e61580b2.png>

------------------------
Verification passed on

Brave | 1.44.97 Chromium: 106.0.5249.40 (Official Build) (arm64)
-- | --
Revision | `4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [brave/brave-core#13370](https://github.com/brave/brave-core/pull/13370)
- Verified able to add NFT as a custom asset lists NFT under NFT's section in portfolio
- Verified able to add multiple NFT's and list 
- Verified clicking on an NFT loads the NFT details view
- Verified NFT details view shows Chain details, Token Standard, Token ID, Description & owner address & any transactions done on the NFT
- Verified NFT details view shows both image and video images 
- Verified able to filter NFT's on portfolio page
- Verified able to filter NFT's based on network filter 
- Verified NFT is loaded in `chrome-untrusted://` iframe
- Encountered [#25588](https://github.com/brave/brave-browser/issues/25588) & [#25590](https://github.com/brave/brave-browser/issues/25590)

chrome://untrusted iframe | NFT details view | NFT listing on all netowrk | NFt listing by filter
-- | -- | -- | --
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/17010094/192026374-1a8ca126-3405-4719-af5a-215eb7f0cec4.png"> | <img width="1840" alt="image" src="https://user-images.githubusercontent.com/17010094/192026192-7e5f709c-1ce9-4f22-a954-c0bd14d85692.png"> | <img width="1840" alt="image" src="https://user-images.githubusercontent.com/17010094/192026447-43f84c73-d338-4585-9187-cfdad9d4ee33.png"> | <img width="1840" alt="image" src="https://user-images.githubusercontent.com/17010094/192026267-4fdcc519-029c-40a0-b57c-ea6b60ee741d.png">
