### ISSUE TITLE
Display Solana Networks By Default

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#22624]
## Description 
We need to display `Solana` networks by default in the network selectors, if a `Solana` account has not yet been created and a `Solana` network is selected, we should surface a `Create Account` button.

**Comment by kjozwiak** [comment]
The above requires `1.39.109` or higher for `1.39.x` verification.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.39.109 Chromium: 102.0.5005.50 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>f6e2cf8f59ec714bdcff8499991d55898875f287-refs/branch-heads/5005@{#648}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22621.1)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/13325>brave/brave-core#13325</a></li>
         <li>Verified Solana network is listed by default under networks</li>
         <li>Verified Solana account is created when selecting Yes on the prompt</li>
         <li>Encountered <a href=https://github.com/brave/brave-browser/issues/22909>#22909</a> and <a href=https://github.com/brave/brave-browser/issues/22957>#22957</a></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>Panel
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/169483677-455be334-7095-49f3-93e5-f0ca1099ff0d.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/169483883-cb33ceec-4104-4aae-8b61-30e95386eaeb.mov>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/169483964-4cfce325-b740-4d0e-9235-a6595d0cb25c.mov>
      </td>
   </tr>
   <tr>
      <td>Widget 
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/169483733-af32d0e3-a89f-45c9-8104-b8db22d8c1ff.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/169484011-9cf6e9dd-8817-45fe-b8c9-b700a5fa1bfc.mov>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/169484082-d5f3e22d-a9a2-43cb-8105-d2cc80726589.mov>
      </td>
   </tr>
</table>
