### ISSUE TITLE
Hostname field in submitted user-support data to Guardian lists city, rather than actual hostname

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#22628]
## Description 

Hostname field in submitted user-support data to Guardian lists city, rather than actual hostname

## Steps to Reproduce

 1. install `1.39.86`
 2. launch Brave using `--vmodule="*/skus/*"=1 --enable-logging=stderr`
 3. via `brave://flags`, set `Enable experimental SKU SDK` to `Enabled`
 4. also set `Experimental SKU Environment` to `Development`
 5. click to `Relaunch`
 6. load `account.brave.software`
 7. enter basic auth creds for site
 8. enter an email and click `Get login link`
 9. check your email inbox
 10. click `Log in to Brave` or the link in the email
 11. click on `Browse plans`
 12. scroll down and click on `Buy now` for `Brave VPN Subscription`
 13. enter payment details on `https://checkout.stripe.com/pay/cs_test…`
 14. click `Subscribe`
 15. you should get a `Complete your purchase...` screen
 16. click on `Complete payment`
 17. click on the VPN icon
 18. click on the `Settings` gear icon
 19. click on `Contact technical support`
 20. See that `VPN hostname` is checked
 21. Submit the issue with details by clicking on `Submit`
 22. Check with Guardian (once fixed) to ensure their `Hostname:` field (`VPN hostname:` in our UI) has the correct VPN-location endpoint populated

## Actual result:

Currently, that's populated with the city, rather than the hostname, which in my case below was: `sanjose-ipsec-1.guardianapp.com`

Submitted data | Received data from Guardian | BraveVPN in Windows
----------------|------------------------------|-----------------------
![15804-windows-7 (1)](https://user-images.githubusercontent.com/387249/165993817-a4045c84-0621-4f44-be98-978a4a0e1162.png) | <img width="226" alt="Screen Shot 2022-04-29 at 10 29 13 AM" src="https://user-images.githubusercontent.com/387249/165993936-3b6030af-ef40-439f-8b2e-bcfbee8e42c0.png"> | ![Screenshot 2022-04-29 103015](https://user-images.githubusercontent.com/387249/165994255-a04910f6-d217-40a1-9a37-2bef28f030ee.png)

## Reproduces how often: 

100%

## Brave version (brave://version info)

`1.39.86` on Windows 10

cc @bsclifton @rebron

**Comment by bsclifton** [comment]
For example it's submitting `San Jose, CA` instead of `sanjose-ipsec-1.guardianapp.com`

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.41.14 Chromium: 102.0.5005.61 (Official Build) nightly (x86_64)
-- | --
Revision | 0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}
OS | macOS Version 11.6.6 (Build 20G624)

#### Followed my original steps to reproduce (inline, above).

### Confirmed submitting a technical-support request correctly includes the hostname (`sanjose-ipsec-1.guardianapp.com`), rather than city name (`San Jose, CA`), as before.


client UI | from Guardian | macOS `Network` panel
---------|---------------|--------------------------
<img width="1186" alt="Screen Shot 2022-05-25 at 10 08 08 AM" src="https://user-images.githubusercontent.com/387249/170323298-6ac1cc18-b143-4bb9-a18a-c40ad7e4df30.png"> | <img width="911" alt="Bildschirmfoto 2022-05-25 um 19 12 07" src="https://user-images.githubusercontent.com/387249/170323020-017ea09a-0e18-4144-91d7-3d011f211f76.png"> | <img width="780" alt="Screen Shot 2022-05-25 at 10 17 06 AM" src="https://user-images.githubusercontent.com/387249/170323860-7da4bdaf-220a-4dd7-92c9-bc68919ef1ff.png">
