### ISSUE TITLE
Add NFT Details: fiatPrice, cryptoPrice and NFT Logo

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#22627]
## Description 
Add missing information to NFT details page:
 - FiatPrice
 - CryptoPrice
 - NFT Collection Logo

## Actual result:
![image](https://user-images.githubusercontent.com/40611140/148090114-58ad9099-357e-48db-8956-2495284a5ae4.png)

## Expected result:
- Above mentioned information visible in NFT details page

**Comment by diracdeltas** [comment]
need security review for this, in particular how the logo is displayed. since this is arbitrary data, please consider putting this view in a chrome-untrusted frame. cc @petemill

**Comment by muliswilliam** [comment]
Closing this issue because the values mentioned above: FiatPrice, CryptoPrice, NFT Collection Logo are not available in ERC721 metadata.
