### ISSUE TITLE
Sync should throw error if system time is not accurate with difference more than 2 minutes

### ISSUE THREAD

**Issue by cezaraugusto** [brave/brave-browser#2262]
This was originally a bullet from https://github.com/brave/brave-browser/issues/2103. Carried over from there as the PR for that issue does not address this.

If system time is not accurate, sync should throw an error warning the user.

cc @AlexeyBarabash

**Comment by darkdh** [comment]
This is handled by `ERR_SYNC_INIT_FAILED`
but we can specify more granular error info in https://github.com/brave/sync in the future.

**Comment by darkdh** [comment]
`ERR_SYNC_INIT_FAILED` will be triggered by
1.  unable to connect to sync server
2.  local machine time is out of date
