### ISSUE TITLE
Add custom asset button stays disabled for Solana networks

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#22633]
## Description 
The `Add` button in the `Add Custom Asset` modal stays disabled for `Solana` networks

![Screen Shot 2022-04-29 at 3 11 38 PM](https://user-images.githubusercontent.com/40611140/166069760-b3c342f7-9d60-4caf-a343-b4fcb4876989.png)

**Comment by kjozwiak** [comment]
Above requires `1.39.92` or higher for `1.39.x` verification.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.39.109 Chromium: 102.0.5005.50 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>f6e2cf8f59ec714bdcff8499991d55898875f287-refs/branch-heads/5005@{#648}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22621.1)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/13225> brave/brave-core#13225</a></li>
         <li>Verified able to add a custom asset for Soalana Mainnet Beta</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/169523857-65c93808-dfec-4298-beff-bd95075d2428.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/169524174-b919e153-1928-42a7-b708-e0921781be32.mov>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/169524133-ee1862ba-d520-46e4-a585-5093eee46679.mov>
      </td>
   </tr>
</table>
