### ISSUE TITLE
This new look breaks things I used.

### ISSUE THREAD

**Issue by FreeBornAngel** [brave/brave-browser#22635]
## Description 

The new version of brave shields doesn't allow me to choose which scripts to allow.

## Steps to Reproduce

   1. 
![image](https://user-images.githubusercontent.com/18445737/166087825-03b15f94-1ed9-4de6-a882-52ed4ce41c44.png)

   2.   This part of the ui allowed scripts to be individually enabled before this update.
   3. 
   4. 

## Actual result:

Please restore this feature.

## Brave version (info found on brave://version)

![image](https://user-images.githubusercontent.com/18445737/166087909-1a5cfbe3-50f0-4e16-a025-c36e45e30d93.png)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## This new change is a deal breaker for me.

# Please revert the code, or enable individual permissions for scripts in the new code.

**Comment by gelatinbomb** [comment]
For now you can disable the v2 version of the brave shields and use the v1. Just go to the brave flags and search "shield" then you will have two flags related to brave shields. Disable the v2 and enable the v1.
But yeah I miss that option too. I really like the brave shields but I think they can add more features to the script blocker to make it way more better.

**Comment by Johann999** [comment]
Please revert to Shield V1

**Comment by FreeBornAngel** [comment]
I'm having trouble finding the location to revert the shields.
Can I get a clue as to where I'm supposed to be looking?

**Comment by gelatinbomb** [comment]
Do you see those two flags over there? Just set those as the image I posted here:
![image](https://user-images.githubusercontent.com/31792239/166135890-89d8fdd8-9966-40b4-836c-1b1e206d0ebc.png)

**Comment by FreeBornAngel** [comment]
Thank you, very much!
Mine looks a little different.
![image](https://user-images.githubusercontent.com/18445737/166152276-9f7ab114-8b54-43bd-aa63-2c9f8c56b0ff.png)

Now I'll have to go through all that flippin' switches.
