### ISSUE TITLE
User has extremely slow wallet panel opening up

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#22649]
User has up to a minute wait with decent hardware specs when clicking the wallet button or when there's a transaction.
https://community.brave.com/t/brave-wallet-performance/354805

**Comment by raress96** [comment]
I also have a similar performance related issue. Just switched from Chrome with Metamask to using Brave and I said I'd try the built in Wallet. I am using BSC network, but every time I have to do a transaction it takes like 10 seconds for the gas fees to be fetched and the whole process is really slow and tedious, especially when I have to do 5-10 transactions in a row.

**Comment by lexansoft** [comment]
Very slow. Not just opening, everything.  

BTW 1. How to delete all these .... unneeded networks.  2. Who the .... decided to show the whole portfolio instead of the account balance?  Very bad decision. Probably another thing that slows down everything.
