### ISSUE TITLE
Can't install brave on Kali Linux

### ISSUE THREAD

**Issue by Rovel** [brave/brave-browser#2264]
## Description 
Can't install brave on Kali Linux

## Steps to Reproduce
I followed the Ubuntu instructions (Debian), but it seems it add a sourcelist specific for Kali intead a generic debian so when I call apt-get update the Brave server denies the connection 

## Expected result:

Add a .deb download file or add a proper Kali Kali source list

**Comment by RealGoodProgrammer** [comment]
Same problem

Err:6 https://brave-browser-apt-release.s3.brave.com kali-rolling InRelease                 
  403  Forbidden [IP: 151.101.86.217 443]
Hit:7 https://packagecloud.io/slacktechnologies/slack/debian jessie InRelease                    
Reading package lists... Done                                                                   
E: Failed to fetch https://brave-browser-apt-release.s3.brave.com/dists/kali-rolling/InRelease  403  Forbidden [IP: 151.101.86.217 443]
E: The repository 'https://brave-browser-apt-release.s3.brave.com kali-rolling InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by tomlowenthal** [comment]
The issue is that your `lsb_release -sc` doesn't match one of the Ubuntu ones we specifically name. Edit `sources.list.d/brave-browser-release-*.list` to replace `kali-rolling` with an applicable Ubuntu codename.

**Comment by Rovel** [comment]
thanks @tomlowenthal I know that, but it would be good to add a proper source to kali from the brave sources, since the'r all debian is just duplicate and rename at the source repo.
you know it's a good practice keeping all sources lists and its installs clean

**Comment by tomlowenthal** [comment]
I added an issue above to make more mention of this in the install instructions and consider adding more keywords.

But I'm also a little leery about explicitly adding more keywords to our apt repos. We test specifically to make sure that everything works on Ubuntu and Mint. We don't do that for Kali or Subgraph or even Debian itself. Using an Ubuntu keyword in your Kali sources makes it clear that the onus is on you to ensure that all the right packages/versions are available in your system. If we added `kali-rolling`, it would suggest that we were doing the testing to make sure that we definitely work with Kali's package versions every time we build packages.

**Comment by Rovel** [comment]
Thanks, my humble suggestion is then adding a debian source since Ubuntu, Kali and others derivate from it, also adding a .deb pkg for downloading released versions in the site would be great since Brave auto updates itself after the first install (atom editor and google chrome for linux uses a .deb download in site) I saw brave have .deb but only for -dev releases. so stable ones are out, I could dig them from sources lists and stuff, but the main point is making the installation process for more distros without a lot of hassle.

**Comment by tomlowenthal** [comment]
Yes, I think that those are both things we should certainly do.

**Comment by tomlowenthal** [comment]
FWIW, the `.deb`s are available from the [GitHub releases page](https://github.com/brave/brave-browser/releases), but I know that's not where anyone's going to look when trying to install Brave.

**Comment by Rovel** [comment]
Thanks @tomlowenthal

**Comment by Rovel** [comment]
Hey, i dpkg -i the latest .deb  the install runs good but when I start the application nothing happens.. any advice o debugging that?

**Comment by tomlowenthal** [comment]
Sounds like a whole separate issue.

**Comment by nu11secur1ty** [comment]
https://github.com/nu11secur1ty/brave-browser-Kali-Linux/blob/master/README.md
BR ;)

**Comment by ShinTakata** [comment]
> ## Description
> Can't install brave on Kali Linux
> 
> ## Steps to Reproduce
> I followed the Ubuntu instructions (Debian), but it seems it add a sourcelist specific for Kali intead a generic debian so when I call apt-get update the Brave server denies the connection
> 
> ## Expected result:
> Add a .deb download file or add a proper Kali Kali source list

you must enable user namespace

you can apply this method on kali linux. Visit this website: https://thehacktoday.com/how-to-create-non-root-user-in-kali-linux/ 

and install brave via snap in kali linux. it will run smoothly, :) 

or i think this will work also on your non root account in kali linux.

sudo apt install apt-transport-https curl

curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo apt-key --keyring /etc/apt/trusted.gpg.d/brave-browser-release.gpg add -

echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ trusty main" | sudo tee /etc/apt/sources.list.d/brave-browser-release-trusty.list

sudo apt update

sudo apt install brave-browser
