### ISSUE TITLE
Extension “Link to text fragment”

### ISSUE THREAD

**Issue by DutchPete** [brave/brave-browser#22642]
## Description 

This Chrome extension does not work on Brave because you have disabled the feature at #8342.

## Steps to Reproduce

   1. install extension
   2. select a text fragment on a webpage, right click and click on “Copy Link to Selected Text
   3. add the link to an app.

## Actual result:

When you click on the link it opens to the top of the webpage but not on the text fragment.

## Expected result:
Clicking on the link opens the web page and scrolls to the text fragment which will be highlighted in yellow.

## Brave version (info found on brave://version)

Brave | 1.38.109 Chromium: 101.0.4951.41 (Official Build) (x86_64)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | macOS Version 10.14.6 (Build 18G9323)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

I have not tried other channels.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by dylan-sessler** [comment]
+1 on this being an important feature for some of my workflows. It would be really nice to have this behind a flag.

**Comment by DutchPete** [comment]
@dylan-sessler thanks for the support. I am not sure the Brave devs will take any notice.

**Comment by hobbes444** [comment]
Did you see this [privacy concern](https://github.com/WICG/scroll-to-text-fragment/issues/76)? That could explain why it's not included.

**Comment by DutchPete** [comment]
@hobbes444 thanks for pointing that out. Out of frustration I stopped using not long after my last comment above. Turns out it was fortuitous in view of the issue page you linked to.

So, thanks again for that.

**Comment by pirate** [comment]
I've opened a new issue to formally request they re-add this flag: https://github.com/brave/brave-browser/issues/42393

Please comment/vote over there as comments on closed PRs and issues likely wont get seen.
