### ISSUE TITLE
"Confirm you are a human being" captcha for claiming Brave Rewards not working

### ISSUE THREAD

**Issue by charukiewicz** [brave/brave-browser#22647]
## Description 

Brave prompts me to "Claim Rewards" each time I open a new tab for my past month's BAT reward. When I click the button, it opens a captcha prompt that is seemingly impossible to satisfy.

## Steps to Reproduce

   1. Have private ads enabled.
   2. Accrue Brave Rewards.
   3. Open a new tab.
   4. Click "Claim Rewards"
   5. Attempt to resolve captcha.

## Actual result:

Captcha never succeeds, despite me being human.

![brave-bat](https://user-images.githubusercontent.com/6189390/166260309-d26daac7-9c5c-45a3-8044-ee1d7a6a5e73.gif)

## Expected result:

Captcha succeeds.

## Reproduces how often: 

Easily reproduced, if you can get to the captcha.

## Brave version (brave://version info)

[Version 1.37.109 Chromium: 100.0.4896.60 (Official Build) (64-bit)](https://brave.com/latest/)

**Comment by charukiewicz** [comment]
Upon a few further attempts, I did finally get it to work. It seems to be extremely particular about where the icon needs to be dragged. Leaving issue open in case this serves as feedback about the sensitivity of the implementation.

**Comment by Miyayes** [comment]
Since you're on 1.37, see this: https://github.com/brave/brave-browser/issues/22180.
