### ISSUE TITLE
Allow values to be set lower than current base fee

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#22648]
<img width="323" alt="Screen Shot 2022-05-02 at 11 26 52 AM" src="https://user-images.githubusercontent.com/831718/166261191-4c720be2-44d3-44eb-8ab6-7a2936226f08.png">

Currently the user can't set lower gas fees, just higher (they can get rid of the miner tip only)

We show the "Current base fee" to what our over estimation is (currently 33%).
I think we should probably show that as the actual current base fee, and not the inflated one. 
I.e. for display only.

Now I know the excess is returned to the user, but users are still confused about it. 
See here:
https://community.brave.com/t/cant-set-manual-gas-avalanche-chain/375388

Users are also confused why the save button ever goes to a disabled state.
This is because we allow them to set the max fee, and they can set it to an inconsistent value.
i.e. we force a value for the base fee that we decide. 

Should we allow a lower forced base fee to be set? I.e. the transaction wouldn't be eligible to go in a block until the base fee reached that range.  Maybe the user for example is ok if the transaction takes a day to be processed.

Thoughts?
cc @jamesmudgett @onyb

**Comment by jamesmudgett** [comment]
Maybe surface a warning if the fee is below the recommended value.

**Comment by scmart** [comment]
@bbondy @jamesmudgett 

Any movement on this?  Would love to actually be able to use the Brave wallet.

**Comment by krisbitney** [comment]
This issue makes the brave wallet useless for experienced users

**Comment by bbondy** [comment]
> This issue makes the brave wallet useless for experienced users

Thanks for the ping, we'll get it prioritized.

**Comment by scmart** [comment]
@bbondy I tried out the wallet again today, it seems like you've gone in the opposite direction and completely stripped any control the user might have.  The wallet refused to even send my test transaction.  Is there any hope the brave wallet will be something a non-beginner will ever use?  Or is this not your design goal and I should just stick with metamask.

**Comment by bbondy** [comment]
> it seems like you've gone in the opposite direction and completely stripped any control the user might have. The wallet refused to even send my test transaction.

Surely I don't think you think that I prioritized a direction of not allowing transactions? That would be odd indeed!
It does seem like you're running into a bug but I wonder if you could share more detail that might help us troubleshoot the new issue. Also instead of hijacking this issue it might be better to post a new issue.

**Comment by scmart** [comment]
The wallet refuses to send a 0 ETH transaction, or send it the wallet to ones own address (both transactions that have legitimate use cases, for example, in canceling a previous pending tx).  Seems like the purpose is to help beginners, but these sort of rails make the wallet a non-starter for advanced users.

**Comment by santoniusjearings** [comment]
Any update on this? I want to lower my gas fees

**Comment by raben1** [comment]
Hey there!
I like the wallet, it is working faster than MM for me, quite more indeed. Looks smooth and pretty, and the native implementation in the browser is a big deal. I would want to know if there is any plan to implement the lower gas fee for custom transactions, a very needed feature for an everyday use in my opinion.
I know this is not the thread but I must agree with @scmart about the 0 value and self-transactions, maybe less used but necessary in some cases. Maybe these functions could be added as an option in the wallet settings, like "Advanced functions" or so, and in the same way protect new users and allow a more custom wallet use.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta  (64-bit) 
-- | --
Revision | `46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}`
OS | Linux

- Verified steps from [brave/brave-core#16810](https://github.com/brave/brave-core/pull/16810)
- Verified able to set value lower than the current base fee for a send transaction

https://user-images.githubusercontent.com/17010094/221546160-bf34db28-0cd3-4ce8-bc26-685bdbf568f0.mp4


---------------------

Verification passed on 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta  (64-bit)
-- | --
Revision | `46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#16810](https://github.com/brave/brave-core/pull/16810)
- Verified able to set value lower than the current base fee for a send transaction

https://user-images.githubusercontent.com/17010094/221544996-3b718528-6450-4577-b9a2-186eba186c0b.mp4

---------------------

Verification passed on 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta  (arm64)
-- | --
Revision | `46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#16810](https://github.com/brave/brave-core/pull/16810)
- Verified able to set value lower than the current base fee for a send transaction

https://user-images.githubusercontent.com/17010094/221545684-a0e1949b-589e-4f58-baf0-29b72c0b28ed.mov
