### ISSUE TITLE
'Show Sponsored Images' button displays wrong colour

### ISSUE THREAD

**Issue by mrworldwide1** [brave/brave-browser#22645]
## Description 

On the new tab page, when Background Images are disabled, the 'Show Sponsored Images' button changes to orange.

## Steps to Reproduce

   1. Open a new tab
   2. On the bottom, click customize
   3. Go to the Background Image section
   4. Toggle Show Sponsored Images off

## Actual result:

![3](https://user-images.githubusercontent.com/66652566/166178739-ca399229-5cc9-4c87-9df2-9b37648ce578.png)

## Expected result:

The colour of the toggle should be white instead of orange, similar to how it is when Show Background Images is enabled but Show Sponsored Images is disabled.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

<html>
<body>

Brave | 1.38.109 Chromium: 101.0.4951.41 (Official Build) (64-bit)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | Windows 10 Version 21H2 (Build 19044.1682)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release?
Yes

- Can you reproduce this issue with the beta channel? 
Yes

- Can you reproduce this issue with the nightly channel? 
Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No

- Does the issue resolve itself when disabling Brave Rewards?
No

- Is the issue reproducible on the latest version of Chrome? 
N/A

**Comment by chitangchin** [comment]
I will work on this in a few hours. Have you attempted any solutions so far that havent worked?

**Comment by mrworldwide1** [comment]
@chitangchin 
> I will work on this in a few hours. Have you attempted any solutions so far that havent worked?

Reinstalling Brave, installing on a different Windows and Ubuntu device haven't worked.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.41.47 Chromium: 102.0.5005.78 (Official Build) nightly (64-bit)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | Windows 11 Version 21H2 (Build 22000.675)
```
- New profile
- Launch Brave
- Skip welcome tour
- Click cCustomize
- Toggle `Show Background Images` 'OFF` in the `Background Image` section

Confirmed `Show Sponsored Images` toggle is not displayed in yellow 

![image](https://user-images.githubusercontent.com/98358127/172724846-ba36155c-0f56-4331-b940-045d9f82eaad.png)

**Comment by rebron** [comment]
@wadehrarshpreet Thanks for the fix!
