### ISSUE TITLE
VPN context-menu items should use sentence casing

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#22653]
## Description 

VPN context-menu items should use sentence casing

## Steps to Reproduce

   1. install `1.39.87`
   2. launch Brave
   3.  set up VPN
   4. context-click on the VPN icon
   5. look at the text capitalization

## Actual result:

<img width="349" alt="Screen Shot 2022-05-02 at 10 12 07 AM" src="https://user-images.githubusercontent.com/387249/166293211-38c3cdbd-a041-457c-9fd9-d2a3e8dfbb9e.png">

## Expected result:

<img width="829" alt="Screen Shot 2022-05-02 at 10 17 41 AM" src="https://user-images.githubusercontent.com/387249/166293939-2230438f-3c0d-46ae-a0af-b49a62ee0abc.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.39.87 Chromium: 101.0.4951.41 (Official Build) beta (x86_64)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | macOS Version 11.6.5 (Build 20G527)

cc @rmcfadden3 @bsclifton @Tonev

**Comment by Tonev** [comment]
Hey, @stephendonner 👋 

This one might be intentional as there is a check for casing inside the strings file. I'm not sure how to proceed in this case, whether deleting the entries inside the titlecase check would be enough to resolve your ticket.

![image](https://user-images.githubusercontent.com/20608253/167066562-ee3ce1d7-8b30-4584-bb02-0d98306e3b30.png)

**Comment by stephendonner** [comment]
It's all good; @nullhook will know 👍 Thanks for looking!

**Comment by rmcfadden3** [comment]
@stephendonner — yeah, good catch. Should be sentence case. So:

- Hide VPN button in toolbar
- Send feedback
- About Brave VPN
- Manage my plan

**Comment by spylogsster** [comment]
Looks like this is fixed already:
<img width="252" alt="image" src="https://user-images.githubusercontent.com/2965009/195666810-5aa62a95-c808-4a20-86eb-ea3cfb292abe.png">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.46.83 Chromium: 107.0.5304.68 (Official Build) beta (64-bit)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | Windows 11 Version 21H2 (Build 22000.1098)
```
Verified using original STR from  https://github.com/brave/brave-browser/issues/22653#issue-1223134995

Confirmed correct sentence casing, matched with hamburger menu-->Brave VPN
(and as per https://github.com/brave/brave-browser/issues/22653#issuecomment-1122739396)

VPN context menu|Hamburger menu
---|----
<img width="959" alt="image" src="https://user-images.githubusercontent.com/98358127/198748200-0b20a1ee-521e-4507-8f21-88edd22f869d.png">|<img width="960" alt="image" src="https://user-images.githubusercontent.com/98358127/198748518-05392728-9653-4bce-a0be-9df8a3bb7c24.png">

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.46.86 Chromium: 107.0.5304.91 (Official Build) beta (x86_64)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | macOS Version 11.7.1 (Build 20G918)

This should actually only be changed for Windows (since we don't have VPN on Linux); macOS should use `Title Case`, rather than `Sentence case`.

So I'm going to verify it based on the above.

`VPN`-button's context menu | `Brave VPN` flyout menu
-------------------------------|--------------------------
<img width="1312" alt="Screen Shot 2022-10-31 at 11 38 13 AM" src="https://user-images.githubusercontent.com/387249/199084533-93ec0c4c-67d4-428e-8945-c9a43253d696.png"> | <img width="1312" alt="Screen Shot 2022-10-31 at 11 38 50 AM" src="https://user-images.githubusercontent.com/387249/199084546-ac90ace6-11a1-4f2b-bbc6-7330815958a3.png">
