### ISSUE TITLE
No longer getting a " Complete transaction on hardware device" modal when using a Ledger

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#22652]
Did Ledger and Trezor support regress?
https://community.brave.com/t/no-longer-getting-a-complete-transaction-on-hardware-device-modal-when-using-a-ledger/384267/2

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.39.92 Chromium: 101.0.4951.54 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>67da1aeb32cedd27634ca6634fb79cbd85d3f0ab-refs/branch-heads/4951@{#1126}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22598.200)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td>
      </td>
      <td colspan=3>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/13232>brave/brave-core#13232</a></li>
         <li>Verified able to submit a transaction on Ledger and approve it</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/168541288-928fcf47-c8ab-4db4-96fe-45b0b05aed7a.mp4>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/168541141-dc51f884-a9a9-4cc7-80a5-cada31df75da.mov>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/168541121-4f38f14c-69d4-413d-a4de-91731c79da5f.mov>
      </td>
   </tr>
</table>
