### ISSUE TITLE
Disable brandcode config fetcher

### ISSUE THREAD

**Issue by pilgrim-brave** [brave/brave-browser#2266]
When a user resets their profile ("Restore settings to their original defaults" option in settings), Chromium may decide to fetch a set of default settings from a Google-controlled server. This is gated on the "brand code", which is only set during non-organic installs of Google Chrome on desktop Mac and Windows, i.e. installs from a third party that Google has authorized to redistribute Chrome on their behalf (e.g. ISPs, PC manufacturers). Such parties may specify their own default settings, which would take effect when the user "resets" their profile.

I am 95% sure that this code is never executed, but the branding code is extremely complicated and involves looking at flags outside the original installation path (e.g. the Windows registry), so there is a chance that this code could trigger on a system that had a non-organic Chrome install but the user has  now chosen to install Brave.

As a defense-in-depth, I recommend disabling the brand code config fetcher altogether.

Note: the `BrandcodeConfigFetcher` class handles retrieving and modifying the settings, but it also takes a callback which is called once the "proper" default settings are in place. I recommend unconditionally calling this callback, then skipping the network fetch.

**Comment by bbondy** [comment]
merged label only needed for the PR. Thanks for marking things otherwise though, it's a big help!
