### ISSUE TITLE
Brave Wallet Faucet for Rinkeby is broken

### ISSUE THREAD

**Issue by StephenFluin** [brave/brave-browser#22669]
## Description 
When you try to use the "Get Ether" button after selecting the Rinkeby network within the Brave Wallet, you are forwarded to a site (https://www.rinkeby.io/#faucet) that does not work. 

## Steps to Reproduce

   1. Open Brave Wallet
   2. Select "Rinkeby" from the network drop down
   3. Click on "Get Ether"

## Actual result:
![image](https://user-images.githubusercontent.com/165056/166403801-63685cb0-827f-43e0-aacc-63358b057113.png)

## Expected result:
A working faucet (such as https://faucets.chain.link/rinkeby)

## Reproduces how often: 
Every time (weeks+)

## Brave version (brave://version info)
Brave | 1.38.109 Chromium: 101.0.4951.41 (Official Build) (64-bit)
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | Linux
JavaScript | V8 10.1.124.10

## Version/Channel Information:
Doesn't appear to be specific to a channel.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome?  Not applicable

## Miscellaneous Information:
None

**Comment by jamesmudgett** [comment]
We need to get a support or learn article to maintain a list of faucets per-network

**Comment by srirambv** [comment]
This is changed after https://github.com/brave/brave-browser/issues/23773. There is purchase link available for any testnet anymore. Closing as wontfix.
