### ISSUE TITLE
Not prompted to re-`Allow` enabling `Brave's VPN Configuration` until restart

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#22676]
## Description 

Not prompted to re-`Allow` enabling `Brave's VPN Configuration` until restart

Found while testing https://github.com/brave/brave-browser/issues/22109.

## Steps to Reproduce

   
1. follow steps 1-18 on `https://bravesoftware.slack.com/archives/CC5SA8CCB/p1651597201141019?thread_ts=1651597077.189229&cid=CC5SA8CCB`
2. when prompted to add VPN connections, click on `Don't Allow`
3. click on the `VPN` icon in the toolbar

## Actual result:

<img width="1312" alt="Screen Shot 2022-05-03 at 8 44 24 AM" src="https://user-images.githubusercontent.com/387249/166504444-55d483a3-406e-43c1-8950-34dcdba557f9.png">

You are shown the incorrect/incomplete error message, above; you don't get re-prompted until restart, nor do you get the error from the spec, shown below in `Expected result`.

Clicking `Try again` doesn't work either.

## Expected result:

After clicking `Don't Allow` for the 1st time, clicking again on the `VPN` icon should show the below error.  Toggling to `CONNECTED`/`ON` should re-prompt for the VPN-config addition to the OS

![161843580-95d32353-e671-4f19-a607-7440b0b4bb21](https://user-images.githubusercontent.com/387249/166503707-309c7f25-ce66-42da-bafb-e88ebe4b28c2.png)

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.39.89 Chromium: 101.0.4951.41 (Official Build) beta (x86_64)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | macOS Version 11.6.5 (Build 20G527)

cc @brave/qa-team

**Comment by stephendonner** [comment]
cc @simonhong @bsclifton @nullhook

**Comment by GeetaSarvadnya** [comment]
Windows don't prompt add VPN modal popup. Looks like macOS specific issue.

**Comment by spylogsster** [comment]
cannot reproduce, @stephendonner @GeetaSarvadnya can someone confirm on your side? thanks!

**Comment by bsclifton** [comment]
I'll close this out as stale - @stephendonner let's create a new issue if this still exists. Thanks!
