### ISSUE TITLE
PDFs are still opened in-browser even though "Download PDF files instead of automatically opening them in Brave" is on

### ISSUE THREAD

**Issue by wetlikewater** [brave/brave-browser#2267]
## SEE ISSUE 1531:
#1531 

## Description 
When I attempt to download any .pdf file, the file is opened by the built in brave PDF viewer even though "Download PDF files instead of automatically opening them in Brave" is turned on (Settings > Advanced Settings > Content Settings > PDF documents).

## Steps to Reproduce
1. Turn "Download PDF files instead of automatically opening them in Brave" on;
2. Close Browser
3. Reopen Browser
4. Open any link to a pdf
        ex: http://www.africau.edu/images/default/sample.pdf

## Actual result:
Opens PDF in-browser

## Expected result:
Opens file manager to ask for download location

## Reproduces how often: 

Occurs every time

## Brave version (brave://version info)

```
Brave | 0.56.15 Chromium: 70.0.3538.110 (Official Build) (64-bit)
-- | --
Revision | ca97ba107095b2a88cf04f9135463301e685cbb0-refs/branch-heads/3538@{#1094}
OS | Linux
JavaScript | V8 7.0.276.40
Flash | (Disabled)
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
Command Line | /usr/bin/brave-browser --enable-tab-audio-muting --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --enable-features=EnableEmojiContextMenu,DesktopPWAWindowing,fill-on-account-select,NewExtensionUpdaterService --disable-features=SharedArrayBuffer,DefaultEnableOopRasterization,VizDisplayCompositor,AutofillSaveCardSignInAfterLocalSave,kAutofillServerCommunication --flag-switches-begin --flag-switches-end
Executable Path | /opt/brave.com/brave/brave-browser
Profile Path | /home/alabamavtec/.config/BraveSoftware/Brave-Browser/Default
```

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Have not attempted on dev/beta

### Website problems only:  
- Can not disable brave shields for PDF viewer

- On Chromium (Version 70.0.3538.110 (Official Build) Built on Ubuntu, running on Ubuntu 18.10 (64-bit)) with the same settings on, the file manager is opened like it is supposed to and it asks for a download location

**Comment by Techguyprivate** [comment]
Duplicate issue. Have you searched for any similar issues before creating ? Anyway , thank you for confirming that the problem exists in 0.56.15 on Ubuntu 18.10 ( 64bit ) . I can confirm that the problem exists on Brave beta version 0. 57.8 & stable 0.56.15 on Ubuntu & windows too. 

https://github.com/brave/brave-browser/issues/1531

**Comment by wetlikewater** [comment]
> Duplicate issue. Have you searched for any similar issues before creating ? Anyway , thank you for confirming that the problem exists in 0.56.15 on Ubuntu 18.10 ( 64bit ) . I can confirm that the problem exists on Brave beta version 0. 57.8 & stable 0.56.15 on Ubuntu & windows too.
> 
> #1531

Ah, I am sorry to duplicate issue. Will link yours issue in comment and update version info.

**Comment by Techguyprivate** [comment]
>
> Ah, I am sorry to duplicate issue. Will link yours issue in comment and update version info.

Oh , My  Dear friend. You don't need to say sorry at all . In fact  , I am sorry if I  or my reply sounded as  
bossy or rude. I will fight for your right to post duplicate issues .Kidding. That will be liitle hard for awsome devs working on the awesome project.   Free to post any . Hope I didn't discourage you in anyway.
