### ISSUE TITLE
Feature Request : Allowing users to download the sponsored wallpapers shown on the browser

### ISSUE THREAD

**Issue by gssakash** [brave/brave-browser#22670]
### Issue : 
The Brave Browser does not allow users to download the sponsored images that are shown on the browser so far.

### Proposal : 
It would be really nice if the browser also provided the users with a download option allowing the users to download the images that are displayed on the Brave Browser. 

P.S. I'm not sure if it's legal, but it would be really nice if the Browser also got rid of the bottom credits displayed in the below image, when it downloads the wallpaper that the user wants.
<br />
![rXWVgk0](https://user-images.githubusercontent.com/52027687/166412126-b91e09ea-eb52-4b4e-a8ea-5850ba692504.jpg)

**Comment by simonhong** [comment]
@gssakash  FYI, there is unofficial site - https://brave.photos/ 
You can see and download current and previous sponrosed images from there

**Comment by gssakash** [comment]
Closing this issue as I've gotten what I wanted.
