### ISSUE TITLE
After restart, VPN status icon/button doesn't show connected status until clicked

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#22677]
## Description 

After restart, VPN status icon/button doesn't show connected status until clicked

## Steps to Reproduce

1. follow the steps to get an active VPN connection: `https://bravesoftware.slack.com/archives/CC5SA8CCB/p1651597201141019?thread_ts=1651597077.189229&cid=CC5SA8CCB`
2. once connected, disconnect from Brave VPN (either from `Network Preferences` or via Brave's `VPN` button toggle
3. shut down Brave
4. re-enable BraveVPN from the `Network Preferences`
5. launch Brave
6. look at the `VPN` button in the browser toolbar

## Actual result:

Appears to not be connected (without clicking the `VPN` button explicitly)

![restart-vpn-on](https://user-images.githubusercontent.com/387249/166506979-ca80d091-6d31-4ea0-b548-4f8d6350f6f5.gif)

## Expected result:

A single click on it shows the correct status.

## Reproduces how often: 

100%

## Brave version (brave://version info)

cc @brave/qa-team @bsclifton @nullhook @simonhong

**Comment by simonhong** [comment]
@stephendonner Thanks for catching. I think this came from last refactoring!

**Comment by LaurenWags** [comment]
++ reproduced. Good find @stephendonner 👍🏻

**Comment by stephendonner** [comment]
Maybe https://github.com/brave/brave-browser/issues/23028 will help with this too.

**Comment by stephendonner** [comment]
## Verified `PASSED` 

Brave | 1.41.37 Chromium: 102.0.5005.78 (Official Build) nightly (x86_64)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | macOS Version 11.6.6 (Build 20G624)

Used my original steps to reproduce.

### Steps:

1. follow the steps to get an active VPN connection: https://bravesoftware.slack.com/archives/CC5SA8CCB/p1651597201141019?thread_ts=1651597077.189229&cid=CC5SA8CCB
2. once connected, disconnect from Brave VPN (either from Network Preferences or via Brave's VPN button toggle
3. shut down Brave
4. re-enable Brave VPN from macOS' `Network Preferences`
5. launch Brave
6. look at the VPN button in the browser toolbar

#### Confirmed Brave automatically toggled VPN status on the icon to show `Connected`, when relaunched after enabling VPN from `Network Preferences`

![22677-image](https://user-images.githubusercontent.com/387249/172118832-836f1fb6-c1d1-4bf6-8b7b-1861c30a660b.gif)

**Comment by MadhaviSeelam** [comment]
Brave | 1.41.91 Chromium: 103.0.5060.114 (Official Build) beta (64-bit)
-- | --
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | Windows 11 Version 21H2 (Build 22000.739)

Reproduced the issue in `1.40.70`

#### Steps:
 
Followed above original steps for verification

#### Confirmed Brave automatically toggled VPN status on the icon to show `Connected`, when relaunched after enabling VPN from `Network Preferences`


![2022-07-06_14h54_10](https://user-images.githubusercontent.com/98358127/177652218-1fd5c52a-f9af-4f64-a11b-1a59775575cf.gif)
