### ISSUE TITLE
Brave Wallet as default wallet can be bypassed by extensions

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#22678]
When a user selects Brave Wallet explicitly in chrome://settings/wallet, other wallets should not be able to make it writable then overwrite it. Tally Ho was one such wallet doing that

Steps to reproduce:

# Test 1

i) Install Tally Ho extension https://chrome.google.com/webstore/detail/tally-ho/eajafomhmkipbjmfmhebemolkcicgfmd
ii) Go to brave//settings/wallet and select `Brave Wallet` as the default wallet.
iii) Open a new tab to any site
iv) Open Console and type `window.ethereum.enable()`

Expected:
Brave Wallet should show up

Actual:
Tally Ho shows up

# Test 2

Repeat with Brave Wallet (Prefer Extensions) as the default wallet.
i) Use a new tab
ii) Ensure that setting is set
iii) Open Console and type `window.ethereum.enable()`

Tally Ho should continue to show up

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.40.80 Chromium: 102.0.5005.78 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22621.1)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from issue description</li>
         <li>Verified when wallet provider is set to <code>Brave Wallet</code>, running <code>window.ethereum.enable()</code> trigger opens Brave Panel</li>
         <li>Verified when wallet provider is set to <code>Brave Wallet (Prefer Extensions)</code>, running <code>window.ethereum.enable()</code> trigger opens Extension Popup and not Brave Wallet Panel</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/171563134-3473cbc5-6d96-4f27-881e-881682f6a299.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/171564764-833ac6bf-1ba9-494b-a1da-6dde6dd5f4b1.mov>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/171564711-36eeae5d-6126-48f0-a571-26728bf10330.mov>
      </td>
   </tr>
</table>

**Comment by srirambv** [comment]
Removing `OS/Android` label as there is no way to switch Wallet provider and extensions are not supported on Android
