### ISSUE TITLE
Wallet Panel Crashes on Swap Tab

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#22680]
## Description 
The `Wallet Panel` crashes when changing assets in the `Swap` tab.

https://user-images.githubusercontent.com/40611140/166614175-e853aee5-e9de-45e6-a0b4-63bf32f016cc.mov

**Comment by kjozwiak** [comment]
The above requires `1.39.96` or higher for `1.39.x` verification.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.39.109 Chromium: 102.0.5005.50 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>f6e2cf8f59ec714bdcff8499991d55898875f287-refs/branch-heads/5005@{#648}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22621.1)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/13243>brave/brave-core#13243</a></li>
         <li>Verified no crash when switching between tokens on Swap panel</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/169557693-546814ea-c65c-4543-ab92-a17f92676d11.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/169558833-2b727d61-623d-4f3d-b222-d3f3e3139d4a.mov>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/169558989-d2878d35-ce34-4425-9638-cd52e4fbca20.mov>
      </td>
   </tr>
</table>
