### ISSUE TITLE
block `window.ethereum` completely in 3p iframes

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#22686]
see https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1651599186158609?thread_ts=1651594604.627819&cid=C023VS4HJ6Q for details

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.39.101 Chromium: 101.0.4951.64 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>d1daa9897e1bc1d507d6be8f2346e377e5505905-refs/branch-heads/4951@{#1208}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22616.1)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/13268> brave/brave-core#13268</a></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>Same origin
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/168127194-24cbbdba-756b-4230-b7d6-ef3be4f419b2.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/168128084-7c24b6ca-2b59-48df-9d99-90c598a86c77.mov>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/168128201-a3ccf47a-2e3e-44f3-b84f-2914d6decf01.mov>
      </td>
   </tr>
   <tr>
      <td>Third party origin
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/168127154-8f9c7c88-d968-4582-9917-71e6cce3d953.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/168128264-93fc2525-3813-4879-8ed9-cc9f4eec4cc0.mov>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/168128347-07a0282a-9f9a-4158-a70f-aab65dfa74a0.mov>
      </td>
   </tr>
</table>

**Comment by bbondy** [comment]
This is causing ImmutableX Dapp to stop working on all channels: https://github.com/brave/brave-browser/issues/23142
