### ISSUE TITLE
`yearn.finance` should be `Yearn.Finance` on Swap 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#22683]
## Description 

`yearn.finance` should be `Yearn.Finance` on Swap 

## Steps to Reproduce

   1. Install 1.39.31 x64 build
   2. Select Swap on portfolio page
   3. Search for `yearn`, shows lower case for `yearn.finance` other tokens with `Finance` is all in camel case

## Actual result:

Linux | Windows | macOS 
-- | -- | --
<img width=1200 src=https://user-images.githubusercontent.com/17010094/166639678-1dc1f90f-5e5e-4e80-8ee1-c472f7bf9c3d.png> | <img width=1000 src=https://user-images.githubusercontent.com/17010094/166639495-8bb07053-5ac8-410c-bac3-43c84770bec6.png> | <img width=1000 src=https://user-images.githubusercontent.com/17010094/166639568-0aea6892-6476-4b93-9bcb-9eb36104d0fb.png>

## Expected result:
Have proper casing 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

All

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @josheleonard

**Comment by HEagle18** [comment]
@srirambv I think that's the way it should be shown. See screenshots of matcha and uniswap now on swaps v2 

![Image](https://user-images.githubusercontent.com/12224304/220974897-3d4aa847-bb58-49bf-a331-3e707f6c25d3.png)
![Image](https://user-images.githubusercontent.com/12224304/220974896-8e2ece17-92e1-4e93-b4eb-28c4300e5c79.png)

**Comment by srirambv** [comment]
Closing the issue based on https://github.com/brave/brave-browser/issues/22683#issuecomment-1442107180
