### ISSUE TITLE
Preserve Whitespace in Brave Wallet Signing Message Text

### ISSUE THREAD

**Issue by devstein** [brave/brave-browser#22699]
## Description 

 
Hi 👋 , first of all I've switched to Brave a few months ago from Chrome and absolutely love it.

I'm working on a wallet-based OAuth 2.0 compatible identity provider, called [Picket](https://picketapi.com/), and as part of the authentication flow the user signs a custom message with an appended random nonce. User's want the custom messaging to be readable and friendly (signing a message is scary!) and typically include whitespace in the message. Unfortunately Brave Wallet, unlike Metamask and Rainbow, does not preserve whitespace. 

## Steps to Reproduce

In a Brave Browser,

1. Login to your wallet
2. Connect your wallet to ETH JS library, like ether.js
3. Sign a message with whitespace

```ts
const message = `
Hi,

this has whitespace.

please sign it!
`

await signer.signMessage(nonce);
```

## Actual result:

Whitespace is not preserved:

<img width="273" alt="Screen Shot 2022-05-04 at 4 15 48 PM" src="https://user-images.githubusercontent.com/7771049/166840467-b712fa65-be93-4fb9-9ec5-7ed89ff9114e.png">

## Expected result:

Whitespace is not preserved, like in Metamask: 

<img width="351" alt="Screen Shot 2022-05-04 at 4 15 21 PM" src="https://user-images.githubusercontent.com/7771049/166840451-c7cc5771-fb60-4fc7-87aa-f74830c2508a.png">

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

1.38.109 Chromium: 101.0.4951.41 (Official Build) (x86_64) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome?  N/A

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.41.82 Chromium: 103.0.5060.66 (Official Build) beta (64-bit) </th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>20b1569438a85e631d15e83eb355e3e326e5da6f-refs/branch-heads/5060@{#1066}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.708)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from issue description</li>
         <li>Verified whitespace is preserved on sign messages</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/176200361-13adb51d-480d-44d1-baa2-062d9a85d4c9.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/176199924-ce8d8e4b-c80b-47d7-8ff3-07ea6e4ef100.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/176199963-ae92222b-abac-4119-9feb-9bb46e1bfbe7.png>
      </td>
   </tr>
</table>
