### ISSUE TITLE
Mute tabs when pinned does not work for unmute

### ISSUE THREAD

**Issue by fedbalves** [brave/brave-browser#22690]
## Description 
When you pinned a tab and try to select it, this action mute a tab. No problem at all but user can't unmute from pinned tab.

## Steps to Reproduce

   1. Open Brave Browser;
   2. Pin a tab;
   3. Try to click on a tab in order to select it.
       > If you clicked right on sound Icon it should mute the tab;
   4. Try to click again for unmute.

## Actual result:
<no screenshots needed>

## Expected result:
Besides it could be a problem from UX side. My point here is at least allow user to unmute the tab. In case of unexpected behaviour.

## Reproduces how often: 
All time time. I use to listen music from a Youtube pinned tab. Always when I wish to change playlist it happens;

## Version/Channel Information:
[Version 1.38.109 Chromium: 101.0.4951.41 (Official Build) (arm64)](https://brave.com/latest/)

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? (???)
- Can you reproduce this issue with the nightly channel? (???) 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:
<N/A>

**Comment by simonhong** [comment]
Duplicated with https://github.com/brave/brave-browser/issues/23476
