### ISSUE TITLE
Hook `Manage subscription` link in `Settings` dialog up to the Accounts site

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#22694]
## Description 

Hook `Manage subscription` link in Settings dialog up to the accounts site

## Steps to Reproduce

   1. install `1.39.91`
   2. follow instructions to set up VPN: `https://bravesoftware.slack.com/archives/CC5SA8CCB/p1651597201141019?thread_ts=1651597077.189229&cid=CC5SA8CCB`
   3. click on the `VPN` button
   4. click on the `Settings` (gears) button
   5. click on `Manage subscription`

## Actual result:

Nothing happens

example | example
------------|------------
<img width="429" alt="Screen Shot 2022-05-04 at 10 43 47 AM" src="https://user-images.githubusercontent.com/387249/166747864-09b6c1bc-0e67-4a23-bbbb-2ac98e9c215f.png"> | <img width="475" alt="Screen Shot 2022-05-04 at 10 43 39 AM" src="https://user-images.githubusercontent.com/387249/166747885-aedd1e09-2bb5-4c0f-8af8-078f9b098b0e.png">

## Expected result:

IIRC it should go to (at least on `development`) `https://account.brave.software/` (`account.brave.com` in prod)

## Brave version (brave://version info)

Brave | 1.39.91 Chromium: 101.0.4951.54 (Official Build) beta (x86_64)
-- | --
Revision | 67da1aeb32cedd27634ca6634fb79cbd85d3f0ab-refs/branch-heads/4951@{#1126}
OS | macOS Version 11.6.5 (Build 20G527)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `no`
- Can you reproduce this issue with the beta channel? `yes`
- Can you reproduce this issue with the nightly channel? `yes`

cc @nullhook @bsclifton @brave/qa-team

**Comment by stephendonner** [comment]
Looks like we were going to include this as part of https://github.com/brave/brave-browser/issues/18467#issuecomment-1072971483 but have since punted, leaving `Manage subscription` pending; hence filing this issue 👍

**Comment by stephendonner** [comment]
I think @nullhook has a PR for this somewhere (hooking up the rest of the dialog UI, am I right?), but having explicit issues to verify individual changes is always good.

**Comment by stephendonner** [comment]
This is thrown in the console:

`[15650:259:0505/184712.138182:ERROR:CONSOLE(29)] "Uncaught TypeError: Cannot read properties of undefined (reading 'create')", source: chrome-untrusted://vpn-panel.top-chrome/brave_vpn_panel.bundle.js (29)`

**Comment by stephendonner** [comment]
@spylogsster looks like you already fixed this.

Was it fixed along with https://github.com/brave/brave-browser/issues/22874?

**Comment by spylogsster** [comment]
was fixed by https://github.com/brave/brave-core/pull/13348

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.41.55 Chromium: 102.0.5005.115 (Official Build) nightly (x86_64)
-- | --
Revision | 174dbe6e33bc81994fceb71d751be201d0b4803d-refs/branch-heads/5005_109@{#3}
OS | macOS Version 12.5 (Build 21G5037d)

Followed the steps to reproduce from https://github.com/brave/brave-browser/issues/22694#issue-1225690149.

Confirmed clicking on `Manage Subscription` on the `VPN` dialog loads `https://account.brave.software/account/`, when using the `development` environment.

`brave://flags` | `Manage Subscription` link | `https://account.brave.software/account/`
-------------|--------------------------|--------------------------------------------
<img width="1312" alt="Screen Shot 2022-06-10 at 11 40 42 AM" src="https://user-images.githubusercontent.com/387249/173130443-90354e66-46cb-4d0c-b8ca-d15a0c232c12.png"> | <img width="1312" alt="Screen Shot 2022-06-10 at 11 42 25 AM" src="https://user-images.githubusercontent.com/387249/173130486-d348170c-a5ba-400b-9064-e1d79aa6fa6c.png"> | <img width="1312" alt="Screen Shot 2022-06-10 at 11 42 38 AM" src="https://user-images.githubusercontent.com/387249/173130539-a301cb0c-85e2-4a93-996f-3a921718a536.png">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED`

```
Brave | 1.41.74 Chromium: 103.0.5060.53 (Official Build) beta (64-bit)
-- | --
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | Windows 11 Version 21H2 (Build 22000.739)
```
Followed the steps to reproduce from https://github.com/brave/brave-browser/issues/22694#issue-1225690149.

Confirmed clicking on `Manage Subscription` on the `VPN` dialog loads `https://account.brave.software/account/`, when using the `development` environment.

`Manage_Subscription`|`https://account.brave.software/account/`
---|---
<img width="953" alt="image" src="https://user-images.githubusercontent.com/98358127/174905501-6e7da59f-2509-4422-8a78-edee7a2b9a5a.png">|<img width="956" alt="image" src="https://user-images.githubusercontent.com/98358127/174905468-115a9e1c-3e33-4bd4-8ded-06ef4b6ccb37.png">
