### ISSUE TITLE
Improve database access API in bat-native-ledger

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#22700]
The current data access API in bat-native-ledger is quite verbose, and generally requires assembling a collection of Mojo messages that will be transmitted to the client (i.e. the browser process). We should introduce a new API that wraps these details.

This is a prerequisite for https://github.com/brave/brave-core/pull/12723.

**Comment by bsclifton** [comment]
Reverted with https://github.com/brave/brave-core/pull/13322
