### ISSUE TITLE
P3A default engine question: user switching to another engine and switching back in the same session

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#22708]
## Description 

If a user switches their default search engine to another, and then switches back to the original engine within the same session, the reported P3A value is not updated.

## Steps to Reproduce

   1. Open browser, change search engine.
   2. Access `brave://local-state`, validate that the `Brave.Search.DefaultEngine.4` answer corresponds to one of the engines defined for the question in the P3A wiki.
   3. Change the search engine back to the original one.
   4. In the local state page, validate that the P3A answer still contains the value from step 2.

## Expected result:

In step 4, the P3A answer should correspond to the search engine defined in the P3A wiki

## Reproduces how often: 
Easily reproduced

## Desktop Brave version:
1.40.x

## Miscellaneous Information:

Raising PR soon

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```
Brave | 1.40.75 Chromium: 102.0.5005.61 (Official Build) beta (64-bit)
-- | --
Revision | 0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}
OS | Windows 10 Version 21H2 (Build 19044.1706)

```
- Verified the STR from the description

**Comment by Uni-verse** [comment]
Verification in progress on Android ARM using 

```
Brave	1.40.96 Chromium: 102.0.5005.115 (Official Build) beta (64-bit) 
Revision	174dbe6e33bc81994fceb71d751be201d0b4803d-refs/branch-heads/5005_109@{#3}
OS	Android 12; Build/SP1A.210812.016
```
