### ISSUE TITLE
Follow up of #21519 - Incorrect response value for WeeklyAddedDirectFeedsCount in an upgraded profile

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#22709]
## Description 

Follow up of #21519 - Incorrect response value for WeeklyAddedDirectFeedsCount in an upgraded profile
## Steps to Reproduce

   1. Clean profile 1.38.x beta channel
   2. Add a RSS external feed  from `https://flipboard.com/@cnet.rss` via `Brave News->Add sources`
   3. Upgrade the profile 1.39.x beta channel
   4. Open brave://local-state
   5. Confirmed that the metrics `Brave.Today.DirectFeedsTotal` response value is `1` as expected
   6.  The response value for the metrics "Brave.Today.WeeklyAddedDirectFeedsCount" is `0` instead of `1`
 

## Actual result:

Follow up of #21519 - Incorrect response value for WeeklyAddedDirectFeedsCount in an upgraded profile
![image](https://user-images.githubusercontent.com/38657976/166977059-04730371-ecaa-4183-97b4-e670bf348377.png)

## Expected result:
The response value for the metrics "Brave.Today.WeeklyAddedDirectFeedsCount" should be `1`

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.39.92 Chromium: 101.0.4951.54 (Official Build) beta (64-bit)
-- | --
Revision | 67da1aeb32cedd27634ca6634fb79cbd85d3f0ab-refs/branch-heads/4951@{#1126}
OS | Windows 10 Version 21H2 (Build 19044.1645)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @DJAndries @mattmcalister

**Comment by DJAndries** [comment]
@GeetaSarvadnya This seems expected. The weekly metric was added in 1.39.x. We use a "weekly storage" preference to track feeds created in the past 7 days. Since the preference does not exist in 1.38.x, it would not be possible to track feeds that were added before the upgrade to 1.39.x.

**Comment by DJAndries** [comment]
@GeetaSarvadnya This seems expected. The weekly metric was added in 1.39.x. We use a "weekly storage" preference to keep track of feeds created in the past 7 days. Since the preference does not exist in 1.38.x, it would not be possible to get the weekly count from before the upgrade.
