### ISSUE TITLE
Hook up `Edit payment method` link in BraveVPN error dialog

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#22715]
## Description 

Hook up `Edit payment method` link in BraveVPN error dialog

## Steps to Reproduce

   1. install `1.39.92`
   2. launch Brave
   3. follow steps from Slack to start setting up a new VPN account on `account.brave.software`; however, don't complete the checkout (`https://bravesoftware.slack.com/archives/CC5SA8CCB/p1651597201141019?thread_ts=1651597077.189229&cid=CC5SA8CCB`)
   4. somehow, reach the `too many recovery attempts error` condition, which I think makes this problem worse/triggers it
   5. click on the `VPN` icon in the toolbar
   6. see error-message dialog
   7. click on `Edit payment method`

## Actual result:

Nothing happens

<img width="1312" alt="Screen Shot 2022-05-05 at 7 12 26 PM" src="https://user-images.githubusercontent.com/387249/167055421-9c6c7ba2-d5c3-4041-bf16-82825d28ec45.png">

## Expected result:

Goes to the appropriate `account.brave.software` (in `development`; `account.brave.com` in production) URL

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.39.92 Chromium: 101.0.4951.54 (Official Build) beta (x86_64)
-- | --
Revision | 67da1aeb32cedd27634ca6634fb79cbd85d3f0ab-refs/branch-heads/4951@{#1126}
OS | macOS Version 12.4 (Build 21F5071b)

cc @bsclifton @nullhook @rebron @brave/qa-team @simonhong @mattmcalister

**Comment by bsclifton** [comment]
This might have happened after moving to chrome-untrusted
cc: @spylogsster

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.41.17 Chromium: 102.0.5005.61 (Official Build) nightly (x86_64)
-- | --
Revision | 0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}
OS | macOS Version 11.6.6 (Build 20G624)

Used my original steps to reproduce.

#### Confirmed clicking on `Edit payment method` now loads `https://account.brave.software/account/` in a new window (we probably want to detect if the user has already loaded that URL, in a separate issue).

`account.brave.software/plans` | `account.brave.software.account`
---------|----------
<img width="1312" alt="Screen Shot 2022-05-26 at 6 54 41 PM" src="https://user-images.githubusercontent.com/387249/170613699-30d8e989-5c02-416d-ae39-8e936f45318c.png"> | <img width="1312" alt="Screen Shot 2022-05-26 at 6 56 17 PM" src="https://user-images.githubusercontent.com/387249/170613759-c4ea9d15-9add-41a7-afca-81e8e4348e55.png">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.41.74 Chromium: 103.0.5060.53 (Official Build) beta (64-bit)
-- | --
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | Windows 11 Version 21H2 (Build 22000.739)
```
Reproduced using original steps `1.40.100 Chromium: 102.0.5005.125 beta`

Confirmed clicking on Edit payment method now loads `https://account.brave.software/account/` in a new tab

Ex1|Ex2
---|---
<img width="953" alt="Screenshot 2022-06-21 131040" src="https://user-images.githubusercontent.com/98358127/174919701-71b0a634-85ec-4688-b8bb-cee4f7fa6529.png">|<img width="948" alt="image" src="https://user-images.githubusercontent.com/98358127/174920005-b1fc8641-607d-43f2-aa9f-bb148d0742ec.png">
