### ISSUE TITLE
Implement `Already purchased VPN?` button link on VPN dialog

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#22711]
## Description 

Implement `Already purchased VPN?` button link on VPN dialog

## Steps to Reproduce

1. install `1.39.92`
2. launch Brave
3. open `brave://flags`
4. set `brave://flags/#brave-vpn` to `Enabled`
5. set `brave://flags/#skus-sdk` to `Enabled`
6. set `brave://flags/#skus-environment` to `development`
7. click on the `Relaunch` button
8. click on the `VPN` button on the browser toolbar
9. click on `Already purchased VPN?`

## Actual result:

Nothing happens

<img width="895" alt="Screen Shot 2022-05-05 at 10 54 51 AM" src="https://user-images.githubusercontent.com/387249/166984471-34f2a65c-6bbc-4ff2-81a1-cbf2b8f005fc.png">

## Expected result:

Should go to `https://account.brave.software/` (in `development`; `account.brave.com` in production)

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.39.92 Chromium: 101.0.4951.54 (Official Build) beta (x86_64)
-- | --
Revision | 67da1aeb32cedd27634ca6634fb79cbd85d3f0ab-refs/branch-heads/4951@{#1126}
OS | macOS Version 11.6.5 (Build 20G527)

cc @nullhook @rebron @mattmcalister @simonhong @brave/qa-team

**Comment by bsclifton** [comment]
This might have happened after moving to chrome-untrusted
cc: @spylogsster

**Comment by stephendonner** [comment]
Verified `PASSED` over in https://github.com/brave/brave-browser/issues/22874#issuecomment-1139113839.

Not sure if we should dupe or just also add `QA Pass/macOS` here to this issue, as well?  cc @brave/qa-team
