### ISSUE TITLE
Hook up `Privacy Policy` link in `Contact technical support` form

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#22713]
## Description 

Hook up `Privacy Polic`y link in `Contact technical support` form

## Steps to Reproduce

   1. install `1.39.92`
   2. launch Brave
   3. set up a working VPN connection (use `https://bravesoftware.slack.com/archives/CC5SA8CCB/p1651597201141019?thread_ts=1651597077.189229&cid=CC5SA8CCB`)
   4. click on the `VPN` icon
   5. click on the gear/`Settings` icon
   6. click `Contact technical support`
   7. in the resulting technical-support request dialog, click on the `Privacy Policy` link

step 4 | step 5 | step 6/7
---------|---------|-------------
<img width="1565" alt="Screen Shot 2022-05-05 at 5 26 19 PM" src="https://user-images.githubusercontent.com/387249/167047956-818862fe-01d9-474f-ae1f-854b1f95a619.png"> | <img width="1565" alt="Screen Shot 2022-05-05 at 5 26 24 PM" src="https://user-images.githubusercontent.com/387249/167047968-175faae9-d560-4535-a1d7-c91be2247db7.png"> | <img width="1565" alt="Screen Shot 2022-05-05 at 5 26 39 PM" src="https://user-images.githubusercontent.com/387249/167047971-54582022-8243-4b86-a087-92dc1b43a09a.png">

## Actual result:

Nothing happens

## Expected result:

The `Privacy Policy` link should work and open the appropriate link (unsure destination URL)

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.39.92 Chromium: 101.0.4951.54 (Official Build) beta (x86_64)
-- | --
Revision | 67da1aeb32cedd27634ca6634fb79cbd85d3f0ab-refs/branch-heads/4951@{#1126}
OS | macOS Version 12.4 (Build 21F5071b)

cc @nullhook @simonhong @bsclifton @rebron @brave/qa-team

**Comment by GeetaSarvadnya** [comment]
++reproduced on windows 10 x64

**Comment by stephendonner** [comment]
This looks like it works fine in 

Brave | 1.41.19 Chromium: 102.0.5005.61 (Official Build) nightly (x86_64)
-- | --
Revision | 0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}
OS | macOS Version 11.6.6 (Build 20G624)

@spylogsster mind linking to the commit/issue which fixed this, too?  Thanks!

<img width="1165" alt="Screen Shot 2022-05-27 at 3 24 11 AM" src="https://user-images.githubusercontent.com/387249/170682422-7e186615-b207-447b-9bf7-15bdd5b89216.png">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.41.74 Chromium: 103.0.5060.53 (Official Build) beta (64-bit)
-- | --
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | Windows 11 Version 21H2 (Build 22000.739)
```
Working as expected.  Clicking on Privacy Policy Link, redirected to `Brave Browser Privacy Policy`  page

Ex1|Ex2
---|---
<img width="956" alt="image" src="https://user-images.githubusercontent.com/98358127/174903112-6d3957f0-d652-48a6-8f6e-82aa5a1cccf5.png">|<img width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/174903128-bd5689aa-73dd-4474-9be6-b71933290cbf.png">
