### ISSUE TITLE
Sometimes it takes multiple attempts to (re)connect to VPN after machine was idle/asleep

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#22728]
## Description 

Sometimes it takes multiple attempts to (re)connect to VPN after machine was idle/asleep

## Steps to Reproduce

   1. install `1.39.92`
   2. launch Brave
   3. follow setup steps to get a working VPN connection
   4. connect to any region
   5. (leave it connected for a little while/few minutes?)
   6. disconnect (but leave Brave open)
   7. put computer to sleep and/or leave it unattended for a bit
   8. click on the `VPN` icon in the toolbar

## Actual result:

![vpn-asleep-still](https://user-images.githubusercontent.com/387249/167211379-f7050880-5062-492f-a457-a43891c74cdf.gif)

## Expected result:

Should connect without issue, barring network outages, etc.

## Reproduces how often: 

100%, given time and circumstances, meaning end users will run into this.

## Brave version (brave://version info)

Brave | 1.39.92 Chromium: 101.0.4951.54 (Official Build) beta (x86_64)
-- | --
Revision | 67da1aeb32cedd27634ca6634fb79cbd85d3f0ab-refs/branch-heads/4951@{#1126}
OS | macOS Version 11.6.5 (Build 20G527)

cc @simonhong @bsclifton @rebron @mattmcalister @brave/qa-team

**Comment by LaurenWags** [comment]
++ encountered this as well

**Comment by GeetaSarvadnya** [comment]
++reproduced on windows 1-0 x64. When the user tries to re-connect, the local machine internet disconnects and reconnects immediately.

**Comment by stephendonner** [comment]
Hopefully https://github.com/brave/brave-browser/issues/23028 will help here.

**Comment by stephendonner** [comment]
Can no longer reproduce this; re-tested using 

Brave | 1.41.42 Chromium: 102.0.5005.78 (Official Build) nightly (x86_64)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | macOS Version 11.6.6 (Build 20G624)

Tried the following scenarios, using the original steps from this issue, as a springboard:
* `Apple` `->` `Sleep`
* `Apple` `->` `Shut Down...`
* `Apple` `->` `Lock Screen`

Confirmed, in all cases, I could successfully reconnect to Brave VPN using the browser, after each of the above.

NOTE: I *have* still witnessed occasional connect/disconnect issues, but they are not specific to the above scenarios, and I didn't encounter them while running through these.

**Comment by stephendonner** [comment]
@spylogsster feel free to resolve
