### ISSUE TITLE
Brave VPN from hamburger menu doesn't always show available sub menu

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#22726]
## Description 

Per https://github.com/brave/brave-browser/issues/17244, after you've purchased VPN the Brave VPN sub menu should be shown on hamburger menu. It is shown, until you restart the browser. On browser restart, the sub menu goes away until VPN button is clicked. 

I was expecting the sub menu to always be shown since I had purchased VPN and loaded my credentials.

## Steps to Reproduce

   1. Follow https://bravesoftware.slack.com/archives/CC5SA8CCB/p1651597201141019?thread_ts=1651597077.189229&cid=CC5SA8CCB (or generally, enable flags, relaunch, and load your credentials for VPN to the browser if you already have an account)
   2. At this point you can leave the VPN button shown, or hide it - it doesn't matter.
   3. At this point you can enable VPN or not - it doesn't matter. 
   4. Open hamburger menu, locate Brave VPN and see triangle indicating that there is a sub menu.
   5. Close browser and relaunch (Note, if VPN was enabled prior to close, you will encounter https://github.com/brave/brave-browser/issues/22677)
   6. Open hamburger menu again
   7. Note that there is no way to access the sub menu for Brave VPN
   8. Click on Brave VPN and it will show the box/modal (and "fix" https://github.com/brave/brave-browser/issues/22677).
   9. Open hamburger menu again, now the sub menu is visible

## Actual result:

Step 7

<img width="464" alt="Step 7" src="https://user-images.githubusercontent.com/28145373/167202804-7821ed3e-1a38-4d99-b368-1d9738c57d16.png">

## Expected result:

Step 9

<img width="770" alt="Step 9" src="https://user-images.githubusercontent.com/28145373/167202828-fe54f602-de80-4cef-9eb7-ac713564ac73.png">

## Reproduces how often: 

easily

## Brave version (brave://version info)

```
Brave | 1.39.89 Chromium: 101.0.4951.41 (Official Build) beta (arm64)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | macOS Version 12.3.1 (Build 21E258)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @brave/legacy_qa @bsclifton @simonhong

**Comment by GeetaSarvadnya** [comment]
++reproduced on windows 10 x64. Good catch @LaurenWags
![image](https://user-images.githubusercontent.com/38657976/170223196-ceff0db6-e344-457e-96bb-c0e4bf0e6248.png)

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.41.55 Chromium: 102.0.5005.115 (Official Build) nightly (x86_64)
-- | --
Revision | 174dbe6e33bc81994fceb71d751be201d0b4803d-refs/branch-heads/5005_109@{#3}
OS | macOS Version 12.5 (Build 21G5037d)


Followed the original steps to reproduce from https://github.com/brave/brave-browser/issues/22726#issue-1228304558.

Confirmed at step 4 I now see the `VPN >` flyout menu, previously only seen after step 9.

`brave://flags` | `VPN config added` | `credentials loaded` | `step 4`
---------------|---------|---------|----------
<img width="1312" alt="Screen Shot 2022-06-10 at 6 39 39 PM" src="https://user-images.githubusercontent.com/387249/173167875-4a4d8678-50de-43bc-b475-dd99230aedf9.png"> | <img width="799" alt="Screen Shot 2022-06-10 at 6 33 17 PM" src="https://user-images.githubusercontent.com/387249/173167717-86da46a7-efed-4596-984e-489de3b99903.png"> | <img width="799" alt="Screen Shot 2022-06-10 at 6 33 22 PM" src="https://user-images.githubusercontent.com/387249/173167718-0896ad23-8739-4203-990e-fa4d680cf07e.png"> | <img width="799" alt="Screen Shot 2022-06-10 at 6 33 30 PM" src="https://user-images.githubusercontent.com/387249/173167719-485dccf7-9b00-4bea-a199-ea2fa95f0fbb.png">

Also confirmed that without valid, active credentials, it still doesn't populate the flyout menu, but launches the `Buy` / `Already purchased?` dialog:

example | example
---------|---------
<img width="1312" alt="Screen Shot 2022-06-10 at 6 40 13 PM" src="https://user-images.githubusercontent.com/387249/173167856-d7a6b3c2-1bf6-4ff5-bf80-a777ae2eae8d.png"> | <img width="1312" alt="Screen Shot 2022-06-10 at 6 40 20 PM" src="https://user-images.githubusercontent.com/387249/173167857-a48557dc-65b6-41a9-b7e0-88777c4831ae.png">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.41.74 Chromium: 103.0.5060.53 (Official Build) beta (64-bit)
-- | --
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | Windows 11 Version 21H2 (Build 22000.739)
```
Followed the original steps to reproduce from https://github.com/brave/brave-browser/issues/22726#issue-1228304558.

Confirmed at step 7 I now see the `VPN >` flyout menu, previously only seen after step 9 (reproduced the issue in `Win 11 x64`)

ex1|ex2|ex3|ex4
---|---|---|---
<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/174911017-61a4fcaf-aa4b-40c5-bd55-ef3051536309.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/174910855-33dba25a-cac1-496a-9a9e-ed7f36c760ed.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/174910915-54e133a9-5922-4fce-9a37-9f57712038c5.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/174911399-4b198055-685c-42ca-9ad7-96ac54fc7df6.png">


Also confirmed that without valid, active credentials, it still doesn't populate the flyout menu, but launches the Buy / Already purchased? dialog:

Brave VPN (no config)|Buy/Already purchase? dialog
---|---
<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/174911550-16983444-cca4-4ce3-90b8-7a59bb6ae92d.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/174911535-5b8c8ecc-38f0-47bb-bdc9-5d10efb00f41.png">
