### ISSUE TITLE
Incorrect response value for the metrics Brave.Today.WeeklyMaxCardViewsCount when 1 card is viewed

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#22720]
## Description 

Incorrect response value for the metrics Brave.Today.WeeklyMaxCardViewsCount when 1 card is viewed

## Steps to Reproduce

   1. Clean profile 1.39.x
   2. Open an NTP and enable brave news
   3. View one brave news card
   4. Open brave://local-state
   5. Confirmed that the metrics `Brave.Today.WeeklyMaxCardViewsCount` response value is `0` instead of `1`

## Actual result:

Incorrect response value for the metrics Brave.Today.WeeklyMaxCardViewsCount when 1 card is viewed
![image](https://user-images.githubusercontent.com/38657976/167103429-1dc88603-a05c-456b-91a5-345f23ec6c1c.png)

## Expected result:
The response value for the metrics `Brave.Today.WeeklyMaxCardViewsCount` should be `1` when one card is viewed

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.39.92 Chromium: 101.0.4951.54 (Official Build) beta (64-bit)
-- | --
Revision | 67da1aeb32cedd27634ca6634fb79cbd85d3f0ab-refs/branch-heads/4951@{#1126}
OS | Windows 10 Version 21H2 (Build 19044.1645)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome?NA 

## Miscellaneous Information:

cc: @brave/qa-team @DJAndries @mattmcalister

**Comment by DJAndries** [comment]
With the way the scroll controller works, the user must scroll down enough in order for the count to be triggered (the card needs to be in the center of the viewport, at the very least). 

FYI, this is not specific to #22222 , but for all news P3A questions which depend on view counts.

Closing as invalid for now. Please feel free to reopen if more precision is needed, I'll be happy to look into it further @mattmcalister @GeetaSarvadnya .
