### ISSUE TITLE
The content on `brave://settings/braveHelpTips` disappears upon reload and direct access via the address bar

### ISSUE THREAD

**Issue by Tonev** [brave/brave-browser#22736]
## Description 

Just noticed that a reload while being on `brave://settings/braveHelpTips`, or directly accessing the page via the address bar, hides page's content. Users would have to click on `Help tips` from the menu in order to bring back the content on `brave://settings/braveHelpTips`.

This issue looks specific to `brave://settings/braveHelpTips` as I couldn't reproduce the issue with any other page.

## Steps to Reproduce

- Case 1:
1. Open `brave://settings/braveHelpTips` via the address bar.
2. Observe the content of the page.

- Case 2:
1. Open `brave://settings/`.
2. Click on `Additional settings` from the settings menu.
3. Click on `Help tips`.
4. Reload the page.

## Actual result:

The content disappears.

## Expected result:
The content shouldn't disappear.

## Reproduces how often: 

100%

## Brave version (brave://version info)

<html>
<body>

Brave | 1.38.111 Chromium: 101.0.4951.54 (Official Build) (64-bit)
-- | --
Revision | 67da1aeb32cedd27634ca6634fb79cbd85d3f0ab-refs/branch-heads/4951@{#1126}
OS | Windows 10 Version 21H2 (Build 19044.1682)

</body>
</html>

<html>
<body>

Brave | 1.39.92 Chromium: 101.0.4951.54 (Official Build) beta (64-bit)
-- | --
Revision | 67da1aeb32cedd27634ca6634fb79cbd85d3f0ab-refs/branch-heads/4951@{#1126}
OS | Windows 10 Version 21H2 (Build 19044.1682)

</body>
</html>

<html>
<body>

Brave | 1.40.38 Chromium: 101.0.4951.54 (Official Build) nightly (64-bit)
-- | --
Revision | 67da1aeb32cedd27634ca6634fb79cbd85d3f0ab-refs/branch-heads/4951@{#1126}
OS | Windows 10 Version 21H2 (Build 19044.1682)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Miscellaneous Information:

CC: @rebron

**Comment by stephendonner** [comment]
@spylogsster @rebron we need to uplift this to 1.42.x.

**Comment by kjozwiak** [comment]
> @spylogsster @rebron we need to uplift this to 1.42.x.

I don't think this one really needs to be uplifted as it's broken since `1.38.x` and haven't really received any reports from Community or Twitter. I don't think most users will directly go into `brave://settings/braveHelpTips` (most don't even know the URL) nor would refresh a settings page once they've visited it.

However, because this one is pretty easy to QA, we'll get it uplifted into `1.42.x` even thought it's a short cycle.

**Comment by kjozwiak** [comment]
The above will require `1.42.70` or higher for `1.42.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```

Brave | 1.42.73 Chromium: 103.0.5060.134 (Official Build) beta (64-bit)
-- | --
Revision | 8ec6fce403b3feb0869b0732eda8bd95011d333c-refs/branch-heads/5060@{#1262}
OS | Windows 10 Version 21H2 (Build 19044.1826)

```

**Comment by kjozwiak** [comment]
Moving this back into `1.43.x` as it was reverted from `1.42.x` as per https://github.com/brave/brave-core/pull/14341.
