### ISSUE TITLE
Enable HTTPS Only Mode by default

### ISSUE THREAD

**Issue by alfredonodo** [brave/brave-browser#22737]
## Description 
HTTPS Only mode is not available. Brave should provide and enable it by default and possibly ask the user to do so on first run. This will improve the privacy of many Brave users as it does for [Firefox](https://support.mozilla.org/en-US/kb/https-only-prefs?as=u&utm_source=inproduct#firefox:linux:fx101).

## Steps to Reproduce

   1. Open the Brave browser
   2. Open a non-HTTPS website

## Actual result:
The website is opened without any warning if it is not HTTPS

## Expected result:
Brave should provide a warning before uploading a non-HTTPS website.

## Reproduces how often: 
Easily reproduced

## Desktop Brave version:
All

**Comment by kemadev** [comment]
Just enable "http://192.168.1.1" and you will get the warning.
Anyway, I don't know if it's a default setting or not but agree that it should be

**Comment by alfredonodo** [comment]
On android 12 with the latest nightly version 1.40.38 there is an option, but it is disabled by default.
![image](https://user-images.githubusercontent.com/41476198/167351213-a13b2e1e-1d8f-4011-a7a5-a1925bf1c740.png)

On GNU/linux with the latest nightly version 1.40.38 the option is missing.
![image](https://user-images.githubusercontent.com/41476198/167351181-b2474061-7ec0-4795-9e7f-64ca6cd84eeb.png)

**Comment by jordan-bravo** [comment]
The [EFF is sunsetting its HTTPS Everywhere extension in January of 2023](https://www.eff.org/deeplinks/2021/09/https-actually-everywhere).  It gives instructions on how to enable HTTPS Only mode in several major browsers.  Brave is notably absent.  Hopefully this will be implemented before that date.

<img width="1150" alt="Screen Shot 2022-09-24 at 14 15 27" src="https://user-images.githubusercontent.com/62706808/192119078-6ef7ac44-baf6-4631-9d0f-69982da0bfb4.png">

**Comment by alfredonodo** [comment]
The problem will be solved with version [1.50](https://brave.com/privacy-updates/22-https-by-default/).

**Comment by arthuredelstein** [comment]
By default, Brave Desktop and Android now upgrade websites to HTTPS and fall back to HTTP only when HTTPS is not available. For users who want a stricter setting, they can switch to Strict Mode which will show a warning before falling back to an HTTP site. For more information, see https://support.brave.com/hc/en-us/articles/15513090104717-Strict-HTTPS-Upgrade-Mode-in-Brave-Browser
