### ISSUE TITLE
`Contact technical support` form doesn't dismiss after submission

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#22731]
## Description 

`Contact technical support` form doesn't dismiss after submission

## Steps to Reproduce

   1. install `1.39.92`
   2. launch Brave
   3. enable both `SKUs` flags and the `VPN` flag in `brave://flags`
   4. click to `Relaunch`
   5. on `account.brave.software`, initiate -- but don't successfully complete -- the Stripe purchase flow for Brave Firewall & VPN
   6. click on the `VPN` button
   7. you should now be on the `Edit payment method` dialog
   8. click on `Contact technical support`
   9. fill out the form
   10. click on `Submit`

## Actual result:

Doesn't appear to have been sent, and the dialog remains (I think @mattmcalister has an existing issue filed on this aspect)

![not-sent](https://user-images.githubusercontent.com/387249/167226574-5dd13ec8-45e8-46fb-b6f9-a23069436bae.gif)

Thrown in the console is this; not sure if it's informative or showing an error:

`[29679:259:0506/160342.445180:INFO:CONSOLE(683)] "function () { [native code] }", source: chrome-untrusted://vpn-panel.top-chrome/brave_vpn_panel.bundle.js (683)`

## Expected result:

If it sent successfully, there should be feedback indicating so, and at the least, close the dialog.

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.39.92 Chromium: 101.0.4951.54 (Official Build) beta (x86_64)
-- | --
Revision | 67da1aeb32cedd27634ca6634fb79cbd85d3f0ab-refs/branch-heads/4951@{#1126}
OS | macOS Version 11.6.5 (Build 20G527)

cc @bsclifton @nullhook @simonhong @mattmcalister @brave/qa-team

**Comment by stephendonner** [comment]
Not only does the dialog not auto-close upon submission, but it silently succeeds.  We should definitely fix this before widening testing on desktop, as users might submit several duplicate reports.

**Comment by LaurenWags** [comment]
++ @stephendonner

**Comment by stephendonner** [comment]
@spylogsster mind grabbing this one?

**Comment by spylogsster** [comment]
seems fixed in https://github.com/brave/brave-core/pull/13486

**Comment by GeetaSarvadnya** [comment]
++reproduced on Windows 10 x64

**Comment by stephendonner** [comment]
Mind double-checking again, @spylogsster ?

I just tried with 

Brave | 1.41.37 Chromium: 102.0.5005.78 (Official Build) nightly (x86_64)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | macOS Version 11.6.6 (Build 20G624)

and auto-closing isn't working for me.

**Comment by spylogsster** [comment]
@stephendonner this fix will be in **1.41.38**

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.41.39 Chromium: 102.0.5005.78 (Official Build) nightly (x86_64)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | macOS Version 11.6.6 (Build 20G624)

![feedback-auto-close](https://user-images.githubusercontent.com/387249/172235323-207fb7b6-b387-451c-a0e0-9319e4914e2c.gif)
