### ISSUE TITLE
Portfolio Network Filter Top Level Should Be Clickable

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#22746]
## Description 
For the `Portfolio Network Filter`,
the top level `coinType` should be `clickable` and default to the `MianNetwork` for that `cointType`.

https://user-images.githubusercontent.com/40611140/167443446-1828bad3-cd1b-4b56-b9b6-b9de9bb18a70.mov

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.40.68 Chromium: 102.0.5005.50 (Official Build) beta (64-bit) </th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>f6e2cf8f59ec714bdcff8499991d55898875f287-refs/branch-heads/5005@{#648}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22621.1)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/13265>brave/brave-core#13265</a></li>
         <li>Verified top level Network filter is clickable</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/169976365-0bfbcefe-dd74-4e00-a817-cc76f39e94e6.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/169977492-4d09a31e-5718-40f3-94a6-6b0d81100cfc.mov>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/169977433-c62bb719-51fa-46eb-bb26-252c03b189f7.mov>
      </td>
   </tr>
</table>

**Comment by kjozwiak** [comment]
We'll need a quick spot check on `1.39.x` 👍 Used the verification's https://github.com/brave/brave-browser/issues/22746#issuecomment-1135528564 to uplift into `1.39.x`.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.39.117 Chromium: 102.0.5005.78 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>8888ee7a24e2c36661ddb9536c35b7d4852a3a98-refs/branch-heads/4951@{#1230}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22621.1)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td>
      </td>
      <td colspan=3>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/13265>brave/brave-core#13265</a></li>
         <li>Verified top level Network filter is clickable</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/171872706-08779592-0325-4640-ba24-12931bd86c9d.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/171873077-7782f1ac-7afe-4ac4-8d6c-c3c2e600d156.mov>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/171873158-d916a41c-2fd8-4c5d-b40f-354d719cb7bf.mov>
      </td>
   </tr>
</table>
