### ISSUE TITLE
Need a better way to copy addresses on wallet

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#22740]
## Description 

Feedback from employee:

The “Copy to Clipboard” hover is a bit confusing. You see this when you hover over the address. If you try to move the mouse to the hover text, the hover text disappears. If you click over the address, there is no feedback that the address has been copied.

## Steps to Reproduce

   1. Try and copy your address from the wallet
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by muliswilliam** [comment]
@HEagle18 We can add a copy icon, show on `Copy to clipboard` on hover. The icon should change to indicate a successful copy action. I have added `design/need-mock-up` label, when the mock up is ready, I can pick this up.

https://user-images.githubusercontent.com/48117473/172839518-6215c6ca-e9be-494c-81c1-978249f4d20a.mov

**Comment by HEagle18** [comment]
This works on wallet page but not on portal. I'm on 1.42

**Comment by srirambv** [comment]
Removing milestone based on https://github.com/brave/brave-browser/issues/22740#issuecomment-1164600549. Should probably require an uplift for 1.41.x if we do plan to ship it in 1.41.x.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.43.79 Chromium: 104.0.5112.102 (Official Build) beta (64-bit)  
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | Linux

- Verified steps from [brave/brave-core#13986](https://github.com/brave/brave-core/pull/13986)
- Verified clicking on an address shows `Copied` message
- Verified on various screens where account address is shown 

https://user-images.githubusercontent.com/17010094/186227833-5773a4b7-783a-44d4-ae2e-26e773903144.MP4



------------------------
Verification passed on

Brave | 1.43.79 Chromium: 104.0.5112.102 (Official Build) beta (64-bit)  
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | Windows 11 Version 21H2 (Build 22000.795)

- Verified steps from [brave/brave-core#13986](https://github.com/brave/brave-core/pull/13986)
- Verified clicking on an address shows `Copied` message
- Verified on various screens where account address is shown 

https://user-images.githubusercontent.com/17010094/186227873-233e7638-f52d-4f6b-9a81-f81da43bc23d.mp4


------------------------
Verification passed on

Brave | 1.43.79 Chromium: 104.0.5112.102 (Official Build) beta (64-bit) 
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [brave/brave-core#13986](https://github.com/brave/brave-core/pull/13986)
- Verified clicking on an address shows `Copied` message
- Verified on various screens where account address is shown 

https://user-images.githubusercontent.com/17010094/186228142-bc159610-e06f-48f6-a812-1c8862b47440.mov
