### ISSUE TITLE
no notification after successful tip - follow up to 2114

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#2275]
## Description 
Per test plan for #2114 (in PR https://github.com/brave/brave-core/pull/896), there should be a notification after a tip is successful. No notification is being shown after successful tip.

## Steps to Reproduce

   1. Clean profile on 0.57.8
   2. Enable Rewards
   3. Accept UGP grant.
   4. Tip a site (or YT channel)

## Actual result:
No notification shown on BAT logo or when you view Brave Rewards Panel from logo.

## Expected result:
Notification should be displayed and should show correct tip amount.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.57.8 Chromium: 71.0.3578.53 (Official Build) beta(64-bit)
-- | --
Revision | 599fb72e740eab9d10609f1ed28a2ad669f82c1a-refs/branch-heads/3578@{#669}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
Reproduced by @btlechowski 
cc @brave/legacy_qa for verification on other platforms

**Comment by LaurenWags** [comment]
cc @rebron @NejcZdovc as the original issue 2114 was slated for 0.57.x

**Comment by NejcZdovc** [comment]
this was changed and now we only show notification for auto contribute. Closing as there is no plan to add it for tip
