### ISSUE TITLE
`Too many recovery attempts` on 5th-device VPN activation

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#22757]
## Description 

(Bear with me: this is likely a server-side config issue, best dealt with in #premium-dev on Slack, but I wanted to note here for visibility and traction on both sides.)

`Too many recovery attempts` on 5th-device VPN activation

## Steps to Reproduce

   1. using `1.39.x`, set up VPN using the same email address, on 4 devices (use `https://bravesoftware.slack.com/archives/CC5SA8CCB/p1651597201141019?thread_ts=1651597077.189229&cid=CC5SA8CCB` for each)
   2. try to follow the above steps, for the 5th device

## Actual result:

![device5](https://user-images.githubusercontent.com/387249/167507427-d7d6df38-fe13-4271-817e-26c3321bd48b.png)

1  | 2  | 3 | 4
-|-|-|-|
<img width="1312" alt="Screen Shot 2022-05-09 at 2 05 25 PM" src="https://user-images.githubusercontent.com/387249/167508071-4867a877-fc41-40ff-9ff9-32374caf3145.png"> | <img width="1312" alt="Screen Shot 2022-05-09 at 2 16 39 PM" src="https://user-images.githubusercontent.com/387249/167508073-a0f21111-7f0a-44d4-9c26-38cca75f13d4.png"> | <img width="1312" alt="Screen Shot 2022-05-09 at 2 21 14 PM" src="https://user-images.githubusercontent.com/387249/167508074-2adf2a7c-8c4d-4340-a90d-9ec2d2e063c7.png"> | ![device4](https://user-images.githubusercontent.com/387249/167508068-3688d638-8906-40f3-ba3b-11b33c418086.png)

## Expected result:

Should support 5 devices, per `https://brave.com/firewall-vpn/` (or is this iOS-specific copy, here?)

<img width="1312" alt="Screen Shot 2022-05-09 at 3 08 00 PM" src="https://user-images.githubusercontent.com/387249/167507581-50606bcd-da28-49f1-b926-950c87bb86ab.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.39.95 Chromium: 101.0.4951.54 (Official Build) beta (x86_64)
-- | --
Revision | 67da1aeb32cedd27634ca6634fb79cbd85d3f0ab-refs/branch-heads/4951@{#1126}
OS | macOS Version 11.6.5 (Build 20G527)

cc @mattmcalister @tackley @rebron @brave/qa-team

**Comment by bsclifton** [comment]
@stephendonner have you ran into this recently?

**Comment by stephendonner** [comment]
> @stephendonner @GeetaSarvadnya have you ran into this recently?

No, but I haven't been explicitly testing this of late, either, so will revisit 👍

**Comment by bsclifton** [comment]
Closing - we'll be revisiting this soon enough. We may want to log in https://github.com/brave/account-brave-com (repo is private currently)
