### ISSUE TITLE
Solana Networks Typo

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#22756]
## Description 
`Solana` is misspelled for `Mainnet`, `Testnet` and `Devnet`

![image](https://user-images.githubusercontent.com/40611140/167485695-ae604eea-70e6-4da3-9140-3efff445623f.png)

**Comment by kjozwiak** [comment]
The above will require `1.39.101` or higher for `1.39.x` verification.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.39.101 Chromium: 101.0.4951.64 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>d1daa9897e1bc1d507d6be8f2346e377e5505905-refs/branch-heads/4951@{#1208}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version Dev
         <br/> (Build 22616.1)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified <code>Solana</code> is correct </li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/168260864-a0096e7a-c3a0-409e-9591-43a2bf5f9bfa.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/168268787-1c5cf6d0-0b7a-4d12-935d-0114979f4261.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/168268741-2a692c8f-c3ce-45ff-bc4f-9360749fef88.png>
      </td>
   </tr>
</table>
