### ISSUE TITLE
Remove placeholder text for wallet sends on Solana

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#22755]
## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by HEagle18** [comment]
<img width="322" alt="Screen Shot 2022-05-09 at 19 06 04" src="https://user-images.githubusercontent.com/12224304/167484232-fcd9b525-9093-413a-9a86-1ce827788a85.png">

**Comment by Devjohn12** [comment]
Talk to a Solana Support on the [Live support page](https://sol-community.com/) so that your issue can be looked into.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.40.75 Chromium: 102.0.5005.61 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22621.1)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/13363>brave/brave-core#13363</a></li>
         <li>Verified placeholder text updates for Solana and Filecoin</li>
         <li>Verified placeholder text is updated on both widget and panel</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/170990841-337672a2-f6cd-405b-b078-e5c76fb8c297.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/170992004-b59467b1-1b4d-49ee-96e1-269cfb7fc843.mov>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/170992131-5a29bf8f-ecde-4510-854d-4c54098fb967.mov>
      </td>
   </tr>
</table>
