### ISSUE TITLE
Rewards Summary panel on brave://rewards doesn't update consistently

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#2276]
## Description 
Sometimes the Rewards Summary panel on brave://rewards doesn't update consistently. 

@davidtemkin and I have ran into this, in different ways. In David's case, he tipped a site (one-time tip). Tip showed up in his Tips panel, but the Rewards Summary took some time to reflect this.

In my case, I performed an auto-contribution. When I accessed the Brave Rewards panel (from BAT logo), the auto-contribution was shown. However, navigating to brave://rewards did not show this in my Rewards Summary. Close/reopen of the page did not help. It took 5-10 minutes for my Rewards Summary to reflect my auto-contribution.

## Steps to Reproduce

   1. Clean profile on 0.57.8.
   2. Launch with `--rewards=reconcile-interval=5`
   3. Enable Rewards.
   4. Quickly add a few sites to the table.
   5. In 5 minutes, a contribution occurs.
   6. Open a new tab and view Brave Rewards Panel from the BAT logo, your auto-contribution is reflected.
![screen shot 2018-11-28 at 5 42 26 pm](https://user-images.githubusercontent.com/28145373/49188456-d8740380-f338-11e8-8766-bcd283634b74.png)
   7. Go to brave://rewards. Note that your balance has gone down and your a-c table is cleared.

## Actual result:
Auto Contribution is not reflected in the Rewards Summary panel:
![screen shot 2018-11-28 at 5 45 27 pm](https://user-images.githubusercontent.com/28145373/49188485-f2154b00-f338-11e8-99a2-457f6826243a.png)

## Expected result:
Rewards Summary should reflect that an a-c has taken place (this happens eventually, but can take some time)
![screen shot 2018-11-28 at 5 52 03 pm](https://user-images.githubusercontent.com/28145373/49188514-08230b80-f339-11e8-80c0-879a46dfa98f.png)

## Reproduces how often: 
unsure, sometimes this seems to be reflected quickly, other times not so much.

## Brave version (brave://version info)

Brave | 0.57.8 Chromium: 71.0.3578.53 (Official Build) beta(64-bit)
-- | --
Revision | 599fb72e740eab9d10609f1ed28a2ad669f82c1a-refs/branch-heads/3578@{#669}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by diracdeltas** [comment]
ran into this today after sending a tip

**Comment by LaurenWags** [comment]
+1 on updating lag from https://community.brave.com/t/tip-not-reducing-balance-and-not-showing-up/42250/8

Note - User did see that Tips panel was behind by about 10BAT, but after some time the Tips panel did update appropriately.
