### ISSUE TITLE
BatAdsConversionsDatabaseTableTest.DoNotSaveDuplicateConversion unit test failed on linux

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#22765]
```
../../brave/vendor/bat-native-ads/src/bat/ads/internal/database/tables/conversions_database_table_unittest.cc:119: Failure
Value of: CompareAsSets(expected_conversions, conversions)
  Actual: false
Expected: true
```

**Comment by wknapik** [comment]
BatAdsConversionsDatabaseTableTest.SaveConversions failing on linux x64 nightly ([test report](https://ci.brave.com/job/brave-browser-build-linux-x64/4246/testReport/junit/(root)/BatAdsConversionsDatabaseTableTest/linux_x64___test_unit___SaveConversions/))
```
../../brave/vendor/bat-native-ads/src/bat/ads/internal/database/tables/conversions_database_table_unittest.cc:91: Failure
Value of: CompareAsSets(expected_conversions, conversions)
  Actual: false
Expected: true
```

**Comment by aseren** [comment]
Also BatAdsConversionQueueDatabaseTableTest.GetConversionQueueItemForCreativeInstanceId failed on linux x64 asan nightly
