### ISSUE TITLE
The sensor icon should not displayed on a desktop.

### ISSUE THREAD

**Issue by Johann999** [brave/brave-browser#22768]
![sensor](https://user-images.githubusercontent.com/53431361/167635998-d4be3751-1302-4f16-bcca-6a8ae59f32c8.png)

There are no motion sensors on a PC.

Other browser (Firefox, Opera, Vivaldi, Yandex) doesn't show this icon.

**Comment by rebron** [comment]
@Johann999 Here's a good article on this `https://grantwinney.com/websites-requesting-access-to-motion-sensors/`

**Comment by Johann999** [comment]
The problem is by no means solved by this article.
If this sensor display really is a tracker, why isn't it blocked by Brave?
There are no sensors on a desktop PC, so the display of this icon is per se incomprehensible.
And why don't other browsers show this icon?
