### ISSUE TITLE
Fix a potential bug while setting brave as default

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#22766]
## Description 
The `BraveSetDefaultBrowserUtils.setBraveDefaultSuccess();` will never be executed as [`MONTHLY_CONTRIBUTION_REQUEST_CODE`](https://github.com/brave/brave-core/blob/9179e6572a30d1b31b27d649bd25325323dd0e4d/android/java/org/chromium/chrome/browser/app/BraveActivity.java#L1330) and [`DEFAULT_BROWSER_ROLE_REQUEST_CODE`](https://github.com/brave/brave-core/blob/9179e6572a30d1b31b27d649bd25325323dd0e4d/android/java/org/chromium/chrome/browser/app/BraveActivity.java#L1334) Both have same values. [`MONTHLY_CONTRIBUTION_REQUEST_CODE`](https://github.com/brave/brave-core/blob/26500ac42019a44cb6a99cbd3798e5099935e9f7/android/java/org/chromium/chrome/browser/set_default_browser/BraveSetDefaultBrowserUtils.java#L36) == [`DEFAULT_BROWSER_ROLE_REQUEST_CODE`](https://github.com/brave/brave-core/blob/9179e6572a30d1b31b27d649bd25325323dd0e4d/android/java/org/chromium/chrome/browser/app/BraveActivity.java#L204)

```
        } else if (resultCode == RESULT_OK && requestCode == 36) {
            dismissRewardsPanel();

        } else if (resultCode == RESULT_OK
                && requestCode == 36) {
            BraveSetDefaultBrowserUtils.setBraveDefaultSuccess();
        }
```
so the `setBraveDefaultSuccess` will never be executed.
## Actual result
Haven't tested this use case but looks like it can affect set default browser flow, where it will always trigger `dismissRewardsPanel` instead of `setBraveDefaultSuccess`.

## Expected result
- `DEFAULT_BROWSER_ROLE_REQUEST_CODE` should have a different value than `MONTHLY_CONTRIBUTION_REQUEST_CODE` constant
- Alternately, Prefer to create a separate constant class for public constants (instead of in Utils file) and move `BraveActivity`'s public constant to the constant file as well if suitable.

## Issue reproduces how often 
easy

### Additional information

Not sure which constant value should be changed, though usually should be latter one.
cc: @tapanmodh, Tagging @srirambv to verify the flow, if required.

**Comment by tapanmodh** [comment]
@Pavneet-Sing Nice catch! I'll fix it

**Comment by Uni-verse** [comment]
Verification in progress using 

```
Brave	1.40.91 Chromium: 102.0.5005.78 (Official Build) beta (64-bit) 
Revision	df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS	Android 12; Build/SP1A.210812.016
```
- Confirmed user gets prompted to select default browser after using the set default browser in 3-dot menu
- Confirmed selecting brave from the default browser prompt will remove setting from menu.
- Confirmed opening link in browser option will launch url in brave browser.
- Confirmed user is able to make monthly contribution to publisher after setting brave as default.

1 | 2 | 3 | 4
-|-|-|-
![screenshot-1654887435014](https://user-images.githubusercontent.com/17885425/173133216-834bf794-fd92-4295-a64e-f338ba404717.png) | ![screenshot-1654887452734](https://user-images.githubusercontent.com/17885425/173133221-0b559114-15c7-472c-a772-69ea92ae3582.png) | ![screenshot-1654887603996](https://user-images.githubusercontent.com/17885425/173133222-f9e128fd-864c-4aea-870b-36141880e2f4.png) | ![screenshot-1654888228919](https://user-images.githubusercontent.com/17885425/173134201-95773aa8-9f1e-43e1-8499-fbfcf1411009.png)
