### ISSUE TITLE
Improve RPill

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#22770]

**Comment by tmancey** [comment]
Reverted change in https://github.com/brave/brave-core/pull/13487

**Comment by kjozwiak** [comment]
Closing we're not uplifting the above into `1.39.x` as it caused issues. Reverted from `1.40.x` & `1.41.x` via https://github.com/brave/brave-core/pull/13487 & https://github.com/brave/brave-core/pull/13491#event-6688155744.
