### ISSUE TITLE
Brave News: re-enable peeking card on Android - follow up to #22135

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#22778]
## Description 
Re-enable the peeking card on new tab page 

This was disabled with https://github.com/brave/brave-browser/issues/21477 for `1.36.x` and via https://github.com/brave/brave-browser/issues/22135 for `1.38.x` due to https://github.com/brave/brave-browser/issues/22569 & https://github.com/brave/brave-browser/issues/22444.

## Steps to reproduce 

1. Go to new tab page
2. At the bottom, there should be a peeking card

QA STR/Cases can be found via https://github.com/brave/brave-core/pull/13203#issuecomment-1123069843. Specifically `Test Case #1`

## Actual result 
No peeking card

## Expected result
Should be a peeking card you can swipe up and opt-in to Brave News

**Comment by kjozwiak** [comment]
@brave/qa-team there's STR/Cases outlined via https://github.com/brave/brave-core/pull/13203#issuecomment-1123069843 regarding running through/ensuring that the opt-in card is working as expected via the NTP. Specifically `Test Case #1 - Running through various opt-in scenarios` This includes upgrades and installs.

**Comment by Uni-verse** [comment]
Verification in Progress using version 1.38.118, Chromium 101.0.4951.67

Clean install/Fresh Profile - `PASS`

1 | 2 | 3 | 4
-|-|-|-
![Screen Shot 2022-05-16 at 2 30 09 PM](https://user-images.githubusercontent.com/17885425/168687926-e75f96e3-2e3d-4939-95a2-65c452b42034.png) | ![Screen Shot 2022-05-16 at 2 31 46 PM](https://user-images.githubusercontent.com/17885425/168687930-c37e98e1-41a9-4bdb-91f3-21eda0a3dc93.png) | ![Screen Shot 2022-05-16 at 2 43 08 PM](https://user-images.githubusercontent.com/17885425/168687931-f13e65b2-68b3-4352-85b8-344b8cd2b443.png) | ![Screen Shot 2022-05-16 at 2 29 15 PM](https://user-images.githubusercontent.com/17885425/168687915-4a7e59e6-d70d-4a86-83a3-0ebaec7fd777.png)


Upgrading (Brave News not enabled) - `PASS`



Upgrading (Brave News enabled but then disabled by user) In Progress 

Upgrading (Brave News enabled & visible) In Progress

**Comment by Uni-verse** [comment]
Verification PASSED using version 1.38.118, Chromium 101.0.4951.67 on Samsung Tab S7 on Android 12
