### ISSUE TITLE
Custom SPL Tokens are added with isErc20 true

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#22771]
## Description 
Custom `SPL` tokens are being added with the `isErc20={true}` flag
This will cause sending that token to fail.

https://community.brave.com/t/unable-to-transfer-bat-on-solana-network/391740

**Comment by kjozwiak** [comment]
The above requires `1.39.106` or higher for `1.39.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.39.111 Chromium: 102.0.5005.61 (Official Build) (64-bit)
-- | --
Revision | `0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}`
OS | Windows 11 Version 22H2 (Build 22621.1)

- Verified steps from issue description
- Verified able to send SPL tokens without any issues

https://user-images.githubusercontent.com/17010094/169814029-df1c0759-b4a7-4160-ba2b-c7b6cedc0914.mov
