### ISSUE TITLE
`panelHandler.setCloseOnDeactivate(true)` is not working correctly on Windows/Linux

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#22780]
## Description 

`panelHandler.setCloseOnDeactivate(true)` is not working correctly on Windows/Linux

## Steps to Reproduce

   1. Initiate a transaction via Trezor wallet
   2. Wait for the transaction to complete
   3. Click outside the panel, doesn't dismiss

## Actual result:

https://user-images.githubusercontent.com/17010094/167790182-e9885352-0782-4a2d-9fcb-6a7163b7b03f.mp4

## Expected result:
Should close when clicked outside the panel

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.40.48 Chromium: 101.0.4951.61 (Official Build) nightly (64-bit)
-- | --
Revision | `3b3633b32c491b4cba5fd7df3c7c0f628547cbcc-refs/branch-heads/4951@{#1189}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @spylogsster @Douglashdaniel @onyb

**Comment by kjozwiak** [comment]
The above requires `1.38.119` or higher for `1.38.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.38.119 Chromium: 101.0.4951.67 (Official Build) (64-bit)
-- | --
Revision | `8888ee7a24e2c36661ddb9536c35b7d4852a3a98-refs/branch-heads/4951@{#1230}`
OS | Windows 11 Version 21H2 (Build 22000.675)

- Verified as part of [#22759 (comment)](https://github.com/brave/brave-browser/issues/22759#issuecomment-1128468628)

---------------
Verification passed on 

Brave | 1.38.119 Chromium: 101.0.4951.67 (Official Build) (64-bit)
-- | --
Revision | `8888ee7a24e2c36661ddb9536c35b7d4852a3a98-refs/branch-heads/4951@{#1230}`
OS | Linux

- Verified as part of [#22759 (comment)](https://github.com/brave/brave-browser/issues/22759#issuecomment-1128468628)

---------------
Verification passed on 

Brave | 1.38.119 Chromium: 101.0.4951.67 (Official Build) (64-bit)
-- | --
Revision | `8888ee7a24e2c36661ddb9536c35b7d4852a3a98-refs/branch-heads/4951@{#1230}`
OS | macOS Version 12.3.1 (Build 21E258)

- Verified as part of [#22759 (comment)](https://github.com/brave/brave-browser/issues/22759#issuecomment-1128468628)
