### ISSUE TITLE
Add Icon to the All Networks filter option

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#22789]
## Description 
We need to add an `icon` to the `All networks` option in the `Network Filter` selector

![Screen Shot 2022-05-11 at 10 18 09 AM](https://user-images.githubusercontent.com/40611140/167898840-30395a77-0e6a-4415-a9df-823076c49161.png)

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.40.68 Chromium: 102.0.5005.50 (Official Build) beta (64-bit) </th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>f6e2cf8f59ec714bdcff8499991d55898875f287-refs/branch-heads/5005@{#648}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22621.1)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/13300>brave/brave-core#13300</a></li>
         <li>Verified All networks has an icon next to the text</li>
         <li>Verified switching networks updates the icon correctly</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/169953560-46c943e3-26b6-4741-9f14-abff5d1def70.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/169972654-021a353b-0b57-449c-a922-986cc9b7ce06.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/169972676-bba13dc7-08aa-4d58-9643-721ee4f4a8c3.png>
      </td>
   </tr>
</table>

**Comment by kjozwiak** [comment]
We'll need a quick spot check on `1.39.x` 👍 Used the verification's https://github.com/brave/brave-browser/issues/22746#issuecomment-1135528564 to uplift into `1.39.x`.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.39.117 Chromium: 102.0.5005.78 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>8888ee7a24e2c36661ddb9536c35b7d4852a3a98-refs/branch-heads/4951@{#1230}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22621.1)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td>
      </td>
      <td colspan=3>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/13300>brave/brave-core#13300</a></li>
         <li>Verified All networks has an icon next to the text</li>
         <li>Verified switching networks updates the icon correctly</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/171874478-af83d12f-b218-4dc4-98d5-595065f63f5f.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/171873815-44be28cc-db83-492c-8695-dc945f0d6c89.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/171873617-aeccf974-a056-4af3-b8e9-1b06b9472e83.png>
      </td>
   </tr>
</table>
