### ISSUE TITLE
Try not to show `Insufficient funds` in panel for a transaction unless there wallet is not having sufficient funds

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#22782]
## Description 

Try not to show `Insufficient funds` in panel for a transaction unless there wallet is not having sufficient funds

## Steps to Reproduce

   1. Have sufficient balance in wallet
   2. Initiate a send transaction
   3. Panel shows `Insufficient funds` message momentarily before you can approve/reject the transaction

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/167850375-b89825e8-5550-491d-938c-b39414d339e4.png)

## Expected result:
Don't show the message unless wallet is low on funds for transactions

## Reproduces how often: 

Easy

## Brave version (brave://version info)

All

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @mrose17 @jamesmudgett @HEagle18 @Douglashdaniel

**Comment by HEagle18** [comment]
@srirambv are you able to replicate this now ? Since we have safe sign and the new send UI ?

**Comment by josheleonard** [comment]
No longer valid

https://github.com/brave/brave-browser/assets/30185185/c8838670-e2a1-4370-bf0a-721eef41ba82
