### ISSUE TITLE
Testnetworks appear after switching to a custom chain

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#22788]
## Description 
With `Show testnetworks` disabled in `brave://settings/wallet/networks` if you switch to a custom chain `(example: BSC)`
All the `testnetworks` will appear in the `Select Network` selector.

https://user-images.githubusercontent.com/40611140/167898088-aa2648a3-8af3-4dae-a1f8-eb88f5581abf.mov

**Comment by kjozwiak** [comment]
The above requires `1.39.110` or higher for `1.39.x` verification 👍
