### ISSUE TITLE
Sync chain is deleted when relaunching browser in offline status

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#2278]
## Steps to reproduce
1.  Create a new sync chain on device A
2. Make sure sync chain is created
3. Quit browser
4. Setting device A to offline (no internet access)
5. Launch browser
6. Previously created sync chain got deleted

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta(64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

* Verified STR in description
