### ISSUE TITLE
NTP SI updater doesn't work properly with VPN

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#22793]
## Description 
See https://bravesoftware.slack.com/archives/CC5SA8CCB/p1652288889547089?thread_ts=1652286507.741139&cid=CC5SA8CCB

Per @deeppandya there are reports of NTP updater not working properly with VPN.

## Steps to reproduce 

To be provided by @deeppandya 

## Actual result 

NTP SI does not update properly when using VPN

## Expected result

NTP SI should update properly

## Issue reproduces how often 

unsure

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version

VPN enabled versions

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc @bsclifton @timchilds @anthonypkeane

**Comment by bsclifton** [comment]
From Slack conversation, this seems to have more to do with attribution than component updater. Needs more investigation. Related: https://github.com/brave/brave-browser/issues/22792

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/22792
