### ISSUE TITLE
Update text for Approval transaction in panel

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#22791]
## Description 

Update text for Approval transaction in panel

## Steps to Reproduce

   1. Initiate a swap transaction for approval
   2. Reject the transaction
   3. Open Panel and open recent transaction. Shows `Approved` instead of `Approve`

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/167902698-b8e8b90c-453c-438c-9c7c-2ab8a049319f.png)

## Expected result:
Should read `Approve Unlimited <Token Name>` instead of `Approved Unlimited <Token Name>`

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.39.96 Chromium: 101.0.4951.54 (Official Build) beta (64-bit)
-- | --
Revision | `67da1aeb32cedd27634ca6634fb79cbd85d3f0ab-refs/branch-heads/4951@{#1126}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel

**Comment by jamesmudgett** [comment]
thoughts @rmcfadden3?

**Comment by rmcfadden3** [comment]
@jamesmudgett — at a glance it makes sense to me. Infinitive ("Approve") rather than past tense ("Approved").

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.40.107 Chromium: 103.0.5060.53 (Official Build) (64-bit) </th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.708)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/13873>brave/brave-core#13873</a></li>
         <li>Verified <code>Approved</code> is replaced by <code>Swap</code> on the transactions history in panel</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/175500915-a3367a30-efe9-4c91-83b2-13b320d0f766.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/175498185-faa7205e-23d2-4929-9005-ee663ff0c38a.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/175502186-b5958897-64a6-45f8-9ec0-2ba733358e2f.png>
      </td>
   </tr>
</table>
