### ISSUE TITLE
Add better handling for web3_clientVersion

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#22799]
Android version of https://github.com/brave/brave-browser/issues/19278

> Issue posted here to discuss: https://github.com/brave/security/issues/650
> 
> But I think BraveWallet/v<chromium-version> is an appropriate value instead of asking Infura.
> 
> For test plan see the pull request https://github.com/brave/brave-core/pull/12900

**Comment by bbondy** [comment]
Nothing else needed here, it's already implemented via https://github.com/brave/brave-browser/issues/19278
