### ISSUE TITLE
Make VPN compatible with Rewards/Ads

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#22792]
VPN offering needs to be compatible with Rewards/Ads.

See https://bravesoftware.slack.com/archives/CC5SA8CCB/p1652286507741139

See also https://github.com/brave/internal/issues/874

**Comment by LaurenWags** [comment]
cc @bsclifton @deeppandya @rebron @timchilds @anthonypkeane @brave/legacy_qa @jsecretan

**Comment by LaurenWags** [comment]
See also https://bravesoftware.slack.com/archives/C0816QH3R/p1652814214601889

**Comment by bsclifton** [comment]
Region may be a problem when connected to VPN and viewing NTP SI (new tab page sponsored image)

**Comment by bsclifton** [comment]
Closing for now as `wontfix`; but we have the internal issue tracking this which we'll use
