### ISSUE TITLE
Remove verbose logging for Brave News

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#22796]
## Description 

Remove verbose logging for Brave News

## Steps to Reproduce

   1. Open a new tab in nightly
   2. Open developer tools
   3. Verbose logs are recorded in console 

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/167991216-cf4380e9-25e9-41b9-bf33-1355d93f46ce.png)

## Expected result:
Only show logs when verbose mode is enabled

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.40.49 Chromium: 101.0.4951.61 (Official Build) nightly (64-bit)
-- | --
Revision | `3b3633b32c491b4cba5fd7df3c7c0f628547cbcc-refs/branch-heads/4951@{#1189}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @petemill

**Comment by stephendonner** [comment]
## Verified `PASSED` using 



Brave | 1.40.68 Chromium: 102.0.5005.50 (Official Build) beta (x86_64)
-- | --
Revision | f6e2cf8f59ec714bdcff8499991d55898875f287-refs/branch-heads/5005@{#648}
OS | macOS Version 12.5 (Build 21G5027d)

### Steps:
1. installed `1.40.68`
2. launched Brave using `--enable-logging=stderr --vmodule="*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --v=0`
3. opened a new-tab page
4. opened the Developer Tools panel
5. clicked on the `Console` heading
6. scrolled down on the new-tab page
7. clicked on `Show Brave News`
8. scrolled, waited, and clicked articles
9. examined the console output


#### Confirmed no Brave-News debug output/logging

<img width="1620" alt="Screen Shot 2022-05-24 at 2 38 56 PM" src="https://user-images.githubusercontent.com/387249/170137683-be25a6f4-4ec1-46e8-9d30-157a87298fcb.png">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED`
```
Brave | 1.40.82 Chromium: 102.0.5005.78 (Official Build) beta (64-bit)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | Windows 11 Version 21H2 (Build 22000.675)
```
### Steps:
1. installed `1.40.82`
2. launched Brave using `--enable-logging=stderr --vmodule="*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --v=0`
3. opened a new-tab page
4. opened the Developer Tools panel
5. clicked on the `Console` heading
6. scrolled down on the new-tab page
7. clicked on `Show Brave News`
8. scrolled, waited, and clicked articles
9. examined the console output


#### Confirmed no Brave-News debug output/logging

<img width="957" alt="image" src="https://user-images.githubusercontent.com/98358127/171512081-2d156691-6117-4c17-b12e-79a1e8f2ccef.png">
