### ISSUE TITLE
brave makes request to update.googleapis.com on startup

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#2280]
on macOS, i started a fresh profile of brave built from master (commit 46601383bbc6da47c0ac60f0ba0bc5613de2944e, debug build) and noticed it was connecting to update.googleapis.com on startup again. will investigate more tomorrow.

cc @pilgrim-brave

**Comment by diracdeltas** [comment]
@pilgrim-brave thanks, @jumde has confirmed that is the case and will revert the crlset PRs.

**Comment by bbondy** [comment]
Moving to invalid milestone which I think is right since the PR that was causing it was reverted. Let me know if I'm not correct pls, thx.
