### ISSUE TITLE
Brave Shield settings crashes browser immediately

### ISSUE THREAD

**Issue by CuboidRaptor** [brave/brave-browser#22803]
Brave Version: 1.38.115  Chromium: 101.0.4951.64
Operating System: Windows NT 10.0.19044

URL (if applicable) where crash occurred: I tested on a random website and youtube, in private and normal, seems it happens everywhere.

Can you reproduce this crash? Yes, at least on my browser.

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Go in any tab
2. Click Brave Shields Icon
3.

Crash ID: crash/61bb0000-8c02-3208-0000-000000000000

**Comment by iefremov** [comment]
most probably dupe https://github.com/brave/brave-browser/issues/22814

**Comment by CuboidRaptor** [comment]
This wasn't just Google Meetings, this was _everywhere_.

**Comment by iefremov** [comment]
yes @CuboidRaptor , this is fixed everywhere
