### ISSUE TITLE
ipfs daemon has high cpu usage

### ISSUE THREAD

**Issue by bridiver** [brave/brave-browser#22808]
## Description 
The ipfs daemon is using 3-10% cpu continuously (m1 mac laptop) even when not in active use to load content. 

## Steps to Reproduce

   1. Visit an ipfs/ipns url
   2. Choose local node
   3. Check process stats

## Actual result:
High cpu usage

## Expected result:
Should have minimal cpu usage when not in active use and ideally shutdown after some period of non-use. @bbondy suggested it could have a pref to always run in the background (default to false)

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
1.40.16

## Version/Channel Information:
All channels

- Can you reproduce this issue with the current release?  yes
- Can you reproduce this issue with the beta channel?  yes
- Can you reproduce this issue with the nightly channel? yes

**Comment by cypt4** [comment]
@bridiver , on which OS do you see this issue?

**Comment by bridiver** [comment]
> @bridiver , on which OS do you see this issue?

macos m1

**Comment by lidel** [comment]
This may get better with each small improvement listed below:
- IF Brave node is lazy-loaded (does not run all the time), or not publicly diallable,  consider switching to client mode by setting [`Routing.Type`](https://github.com/ipfs/kubo/blob/master/docs/config.md#routingtype) to `dhtclient` 
  - By default, Kubo daemon will try to use uPnP and hole punching to become publiclly diallable, and if that is successful it will act as DHT server, accepting DHT PUTs from other peers – this introduces overhead of both CPU and additional bandwidth.
- update to Kubo 0.17 (https://github.com/brave/brave-browser/issues/26996)
  - it ships with ResourceManager enabled by default, and the defaults should help, but also Brave may decide to experiment and adjust limits (docs: [`Swarm.ResourceMgr`](https://github.com/ipfs/kubo/blob/master/docs/config.md#swarmresourcemgr))
- switch to universal binaries for macOS
  - this is blocked by https://github.com/ipfs/distributions/issues/770 → right now macos M1 runs Intel code, this will remove emulation and will run native ARM codes  (macos M1 specifically) :point_left:

**Comment by Pandapip1** [comment]
Is it possible to add an option to disable the daemon while it's not actively being used?

**Comment by vadimstruts** [comment]
The IPFS local node and scheme has been [deprecated](https://github.com/brave/brave-browser/issues/37735)
