### ISSUE TITLE
Unable to send transaction when account removed and added again

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#22801]
## Description 

The reason is that we do not refresh nonce for saved transactions.

1) Import account and make a couple of transactions to have non-zero nonce.
2) Remove account, restart ganache or make new transactions in other system to have different nonce from saved in our preferences
3) Import account back and try to make transactions, it will fail because we do not renew nonce for saved transactions

## Actual result:

unable to send transactions

## Expected result:

able to send transactions

## Reproduces how often: 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by yrliou** [comment]
This is due to ganache reset, where dev is responsible to reset the env manually via the fix in https://github.com/brave/brave-browser/issues/19760.
