### ISSUE TITLE
DApps: Implement Connected sites Settings item

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#22805]
It has to be called from a menu on a wallet panel as well.

**Comment by kjozwiak** [comment]
The above requires `1.40.85` or higher for `1.40.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.40.105 x64 build
- Verified a new setting for `Ethereum` is available under `Site Settings` options
- Verified connected sites are listed under Ethereum settings 
- Verified able to delete a connected site successfully
- Verified able to reconnect to a site after deleting the connected site

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/174594787-fac2ec71-7af6-4e3d-9228-246b691348e4.mp4> | <video src=https://user-images.githubusercontent.com/17010094/174595801-fbb3da6c-b053-44e4-aba0-0555f99fd42d.mp4>
