### ISSUE TITLE
Wallet is using an obsolete password policy

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#22817]
Wallet currently requires the following password policy:

![Screenshot from 2022-05-05 17-11-46](https://user-images.githubusercontent.com/167821/168162016-3318cd40-8e11-4639-ad5d-8893ccbe743b.png)

which is not in line with the [latest password policy guidelines from NIST](https://en.wikipedia.org/wiki/Password_policy#2017).

In particular, the following changes should be made:

- minimum length must be 8 characters
- different character types should not be required

(Also see https://auth0.com/blog/dont-pass-on-the-new-nist-password-guidelines/ for an explanation of the changes in NIST recommendations.)

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/22591#issuecomment-1252744160
