### ISSUE TITLE
crash when clicking on shields while using Google Meet

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#22814]
## Description 

When pressing on the `Brave Shields` icon while you're in a Google Meeting, the browser will crash. Reproduced this several times and originally reported by @lukaslevert and @iambrianfung.

Some `Uploaded Crash Report ID` from @lukaslevert @iambrianfung and myself:

* `99f50000-8c02-3208-0000-000000000000`
* `e4580500-04c8-2808-0000-000000000000`
* `b0e80000-8c02-3208-0000-000000000000`
* `aee80000-8c02-3208-0000-000000000000`

## Steps to Reproduce

Prerequisite: ensure that you're logged into Google so you can start a Hangout Meeting

   1. launch brave (used `1.40.52 Chromium: 101.0.4951.64` in this case)
   2. open Gmail in a new tab and click on `New Meeting` --> `Start Now`
   3. once the meeting is running, click on the `Brave Shields` icon and you'll notice Brave crashes 

## Actual result:

Brave crashes when clicking in on the shields icon while in a Google Meeting

## Expected result:

Brave shouldn't be crashing when interacting with shields while in a Google Meeting.

## Reproduces how often: 

100% reproducible when using the STR/Cases outlined above.

## Brave version (brave://version info)

```
Brave | 1.40.52 Chromium: 101.0.4951.64 (Official Build) nightly (64-bit)
-- | --
Revision | d1daa9897e1bc1d507d6be8f2346e377e5505905-refs/branch-heads/4951@{#1208}
OS | Windows 11 Version 21H2 (Build 22000.652)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `Causing the issue/crash (disabling shields)`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by iefremov** [comment]
cc @nullhook @petemill can you take a look?

**Comment by kjozwiak** [comment]
Above requires `1.39.109` or higher for `1.39.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `In-Progress`
```
Brave | 1.39.109 Chromium: 102.0.5005.50 (Official Build) (64-bit)
-- | --
Revision | f6e2cf8f59ec714bdcff8499991d55898875f287-refs/branch-heads/5005@{#648}
OS | Windows 11 Version 21H2 (Build 22000.675)
```

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.39.109 Chromium: 102.0.5005.50 (Official Build) (x86_64)
-- | --
Revision | f6e2cf8f59ec714bdcff8499991d55898875f287-refs/branch-heads/5005@{#648}
OS | macOS Version 12.3.1 (Build 21E258)
```
