### ISSUE TITLE
Web cache still stay / security risk

### ISSUE THREAD

**Issue by raisty** [brave/brave-browser#2282]
## Description 

Cache of websites stays in browser for more than week. In chrome it is changed immidieately. Mostly valid for images, css etc.

## Steps to Reproduce

   1. load website
   2. change image on website (logo or something cached)
   3. comapre it in chrome and brave

## Actual result:

Brave cache still contain old image, chrome new one.
Seems cache of Brave stays on disk. Even is not deleted. Maybe all the data stays like on Chrome.
This can be result of potentialy security risk (images with code, etc).

## Expected result:
Cache will be proper deleted by settings. No data on disk, which contain history - depends on settings.

## Reproduces how often: 

Always

## Brave version (brave://version info)

 
Brave: 0.25.2 
V8: 6.9.427.23 
rev: 8ea2a9ce5ca329478186e6393e07f1cf87d34a22 
Muon: 8.1.8 
OS Release: 18.2.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 69.0.3497.100

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Tested on production release

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 
No issues on chrome, just Brave.

**Comment by srirambv** [comment]
You are currently on the deprecated muon build. Please upgrade to the new version. You can download it from https://brave.com/download. This might be fixed on the new build. Please check on the new build and if it persists please reopen this issue and update the browser details
