### ISSUE TITLE
Wire up getSelectedCoin and setSelectedCoin in UI

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#22820]
## Description 
Wire up the `getSelectedCoin` and `setSelectedCoin` methods to the Wallet UI.

Reference: https://github.com/brave/brave-browser/issues/21465

**Comment by kjozwiak** [comment]
The above requires `1.39.109` or higher for `1.39.x` verification 👍

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.39.109 Chromium: 102.0.5005.50 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>f6e2cf8f59ec714bdcff8499991d55898875f287-refs/branch-heads/5005@{#648}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22621.1)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/13344>brave/brave-core#13344</a></li>
         <li>Verified selecting account from panel automatically updates the account on the widget</li>
         <li>Encountered <a href=https://github.com/brave/brave-browser/issues/22958>#22958</a> & <a href=https://github.com/brave/brave-browser/issues/22959>#22959</a></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/169512640-d4c834da-6318-4d35-98b9-71b97e6fd8f8.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/169513996-2a96ae94-535e-4556-aec5-4e3d4094df12.mov>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/169513970-70c4a572-67c7-4064-a1f5-0935e67659b6.mov>
      </td>
   </tr>
</table>
