### ISSUE TITLE
Sort by coinType Solana Networks First

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#22833]
## Description 
We need to sort by coinType `Solana` networks first.

![Screen Shot 2022-05-13 at 8 22 37 AM](https://user-images.githubusercontent.com/40611140/168305129-7e94e99e-af8f-4113-a266-29f526db67e0.png)

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.39.109 Chromium: 102.0.5005.50 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>f6e2cf8f59ec714bdcff8499991d55898875f287-refs/branch-heads/5005@{#648}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22621.1)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified network is sorted by coinType making Solana first </li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/169505472-ea956b26-257d-4ea6-a286-7f1490a691ec.png>
      </td>
      <td><img width=800 src=https://user-images.githubusercontent.com/17010094/169505976-7031e650-f24a-464d-8367-0ae2ee7d08ba.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/169505950-c157650b-3a65-4ac1-b03c-0d67baf87cc5.png>
      </td>
   </tr>
</table>
