### ISSUE TITLE
Not all of 5000 bookmarks are sent to sync sometimes

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#2283]
## Description 

Not all of 5000 bookmarks are sent to sync sometimes

## Steps to Reproduce

1. Initialize sync on device A
2. Connect to sync device B
3. On the device A do import of 5000 bookmarks
4. When bookmarks will start to appear on the device B, open brave://bookmarks on device A,  expand and scroll as far as you can

## Actual result:

Not all bookmarks are sent from A to B

## Expected result:
All bookmarks are sent from A to B

## Reproduces how often: 

from time to time

## Brave version (brave://version info)

Brave | 0.59.1 Chromium: 71.0.3578.53 (Developer Build) (64-bit)
Revision | 599fb72e740eab9d10609f1ed28a2ad669f82c1a-refs/branch-heads/3578@{#669}

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Not sure, reproducible on nightly.

**Comment by AlexeyBarabash** [comment]
Met this issue again when tried to see https://github.com/brave/brave-browser/issues/2367 .

**Comment by AlexeyBarabash** [comment]
Tried locally with https://github.com/brave/sync/pull/267 by @samartnik , issue gone, plus syncing was much faster.

**Comment by AlexeyBarabash** [comment]
Fixed with https://github.com/brave/brave-browser/issues/2811 .

**Comment by srirambv** [comment]
@AlexeyBarabash  could you add the test steps to the PR/issue for verification? From the original issue steps you have mentioned that not all bookmarks are sent. When I try to sync 5k bookmarks, the folder structure is sent across to device 2 and only the last nested folder has the bookmarks inside it. The higher nested bookmark folders start receiving chunks in successive fetch call. Is this expected or need to verify something else?

**Comment by AlexeyBarabash** [comment]
@srirambv 
Yes, this is expected.

Here are another STR, more precise: 
1. Initialize sync on device A
2. Connect to sync device B
3.  On the device A do import of bookmarks_big_folder_.html file (3956 bookmarks)
4. Expected: After sync completes ensure device B also has 3956 bookmarks in `BigFolder` bookmarks folder.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.59.18 Chromium: 72.0.3626.28 (Official Build) beta(64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Linux

![screenshot from 2019-01-07 19-53-20](https://user-images.githubusercontent.com/17010094/50773136-f298ee00-12b5-11e9-89f4-3190a9774562.png)
