### ISSUE TITLE
[speedreader] Big gaps instead of images/videos

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#22835]
https://www.latimes.com/world-nation/story/2022-05-12/california-expats-portugal-relocation-lisbon

 big empty spaces where images/videos were removed

<img width="725" alt="image" src="https://user-images.githubusercontent.com/3109556/168320459-87045e16-eda7-4cf8-be0a-3ee291186f28.png">

**Comment by keur** [comment]
It's caused by the `<source>` elements inside of the figures. If you inspect and delete them the pictures show up.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.45.35 Chromium: 105.0.5195.102 (Official Build) nightly (x86_64)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | macOS Version 13.0 (Build 22A5331f)

`1.43.89` | `1.45.35`
----------|---------
<img width="1312" alt="Screenshot 2022-09-08 at 3 20 10 PM" src="https://user-images.githubusercontent.com/387249/189236407-173048db-613a-491a-a03e-f906bc998a72.png"> | <img width="1065" alt="Screenshot 2022-09-08 at 3 22 20 PM" src="https://user-images.githubusercontent.com/387249/189236416-b51a468a-8c7a-4c8b-bc09-79ab70759a32.png">
