### ISSUE TITLE
Rewards panel loads slowly state when network is slow

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#22834]
Because some calls to the `chrome.braveRewards` API require network access, when the network is unavailable or slow the Rewards panel can stay in the "loading" state for some time. We should be able to display the current state to the user and update the UI when the data becomes available.

**Comment by zenparsing** [comment]
See #19287 for a more general issue.

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
Brave | 1.40.75 Chromium: 102.0.5005.61 (Official Build) beta (64-bit)
-- | --
Revision | 0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}
OS | Windows 10 Version 21H2 (Build 19044.1706)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/13329

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.40.82 Chromium: 102.0.5005.78 (Official Build) beta (x86_64)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | macOS Version 11.6.6 (Build 20G624)

Followed the testplan from https://github.com/brave/brave-core/pull/13329

-----

First, tried to reproduce the issue using Rewards staging env:

Brave | 1.39.111 Chromium: 102.0.5005.61 (Official Build) (x86_64)
-- | --
Revision | 0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}
OS | macOS Version 11.6.6 (Build 20G624)

#### Confirmed that clicking on the Brave Rewards panel displays content within 3 seconds when the network is disconnected
