### ISSUE TITLE
Rewards panel doesn't show creator publisher specific information for Vimeo

### ISSUE THREAD

**Issue by elizabethlexi2000** [brave/brave-browser#22832]
## Description 
Same as previously solved issue; https://github.com/brave/brave-browser/issues/11840

Rewards panel does not show creator specific information for vimeo publishers. Subsequently, you are unable to tip specific Vimeo publishers as well.

## Steps to Reproduce

   1. Clean Profile
   2. Enable Rewards, wait for publisher list indexes to be downloaded
   3. Visit a vimeo page (ex. vimeo.com/bravelaurenwags on staging)

## Actual result:

Vimeo publisher info is not shown in panel.
![vimeo bug](https://user-images.githubusercontent.com/105498473/168598501-afe98723-7278-4631-981a-2599ff9fb918.PNG)
In the above, it should say "Lauren on Vimeo" (or similar)
Additionally, choosing one of the tip buttons does not bring up the publisher's banner, but shows the generic banner for a non-verified publisher.

## Expected result:
Vimeo publisher info should be shown in the panel.

## Reproduces how often: 

Easily

## Brave version (brave://version info)

1.38x

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Yes

**Comment by elizabethlexi2000** [comment]
@LaurenWags

**Comment by LaurenWags** [comment]
@elizabethlexi2000 if you click on "Refresh Status" does that fix it

**Comment by elizabethlexi2000** [comment]
@LaurenWags Hi, unfortunately not. Rereshing the status, as well as the browser does not fix the issue.

I've also tried on a different PC with the same result. Is verification present on your end?

**Comment by LaurenWags** [comment]
Thanks @elizabethlexi2000 - I am able to reproduce also.

**Comment by elizabethlexi2000** [comment]
@LaurenWags Thank you for confirming the bug. I presume this means that Vimeo creators cannot receive any tips until the issue is resolved?

**Comment by Miyayes** [comment]
Doesn't repro for https://vimeo.com/user7039569, but does repro for https://vimeo.com/bravelaurenwags.

**Comment by elizabethlexi2000** [comment]
Hi @Miyayes, Thanks for the reply. The screenshot was taken from an older vimeo issue #11840. But I have now edited the post to reflect the 1.38x screenshot. As you have stated, it likewise doesn't repro for https://vimeo.com/user7039569, but does for https://vimeo.com/bravelaurenwags as well as other vimeo creators.

**Comment by emerick** [comment]
It does seem like something changed in the Vimeo DOM. From what I can tell, it seems to affect users who have customized their Vimeo URL (so `bravelaurenwags` vs `user12345`). Unfortunately, what we get back from Vimeo in the former case doesn't contain the publisher name anywhere ("Lauren Wagner" in this case). Perhaps we should just show the user ID (`bravelaurenwags`) in this case rather than failing out completely.

**Comment by elizabethlexi2000** [comment]
Hi @emerick, It appears, at least on my end, that the original functionality has been mostly restored. Previously bugged Vimeo creators with custom URLs are now displaying verified again. Such as these below;
https://vimeo.com/danelder
https://vimeo.com/hscottroth
https://vimeo.com/ericnathan

Curiously, https://vimeo.com/bravelaurenwags remains unverified. @LaurenWags I presume your channel is still connected?

**Comment by Miyayes** [comment]
Fallback on user ID sounds good to me. cc: @emerick

**Comment by GeetaSarvadnya** [comment]
The issue is not reproducible with current release component `1.0.174`

Verified the STR with dev component using `using --use-dev-goupdater-url ` and ensured rewards panel shows the correct creator publisher info for the Vimeo

```
Brave Local Data Updater - Version: 1.0.601
```
![image](https://user-images.githubusercontent.com/38657976/182888904-b4b98f27-f5b9-4eac-8b7d-6e98f76ef9e1.png)
