### ISSUE TITLE
VPN setting icon does not match spec

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#22848]
## Description 
VPN Settings icon in the menu should match spec exactly. The current design has the "VPN" in bold and doesn't look like it conforms to the rest of the icons due to the line weight.

![Screen Shot 2022-05-13 at 2 44 11 PM](https://user-images.githubusercontent.com/17885425/168399238-00a168aa-1ec0-4c43-af1c-57c01bef92e5.png)

## Actual result 
 ![Screen Shot 2022-05-13 at 3 26 36 PM](https://user-images.githubusercontent.com/17885425/168399124-17212191-8ba3-4c0d-b450-ce4ca3038bfc.png)

## Expected result
![Screen Shot 2022-05-13 at 3 26 46 PM](https://user-images.githubusercontent.com/17885425/168399115-64f7a3a1-1b29-42a4-8a74-9c2ca413bdff.png)

## Issue reproduces how often 
Easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung GS21, Tab S7
   - Android version: 12
   
## Brave version
version 1.40.53

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
Adding missing `1.41.x` milestone as this was merged into `master` via https://github.com/brave/brave-core/pull/13641 which is currently `1.41.x`.

**Comment by kjozwiak** [comment]
Labelling this as `QA/No` as this still seems to be broken as per https://github.com/brave/brave-browser/issues/23321

**Comment by kjozwiak** [comment]
@Uni-verse created https://github.com/brave/brave-browser/issues/23321 as a follow up but for this one lets just double check and make sure the icon looks correct throughout the browser. Basically a spot check. The issue re: making the `VPN` icon less bold will be addressed as a follow up via https://github.com/brave/brave-browser/issues/23321.

**Comment by kjozwiak** [comment]
The above will require `1.39.120` or higher for `1.39.x` verification 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+` running `Android 12` using the following build(s):

```
Brave | 1.39.120 Chromium: 102.0.5005.99 (Official Build) (64-bit)
--- | ---
Revision | 870f7bcc58dfa811cc68c2186439721385e086d0-refs/branch-heads/5005@{#1125}
OS | Android 12; Build/SP1A.210812.016
```

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** 
---------------|----------------|-----------------|----------------|----------------|---------------
![Screenshot_20220608-115151_Brave](https://user-images.githubusercontent.com/2602313/172666081-138b65c2-1c03-4ec5-990c-40e408bab260.jpg) | ![Screenshot_20220608-115212_Brave](https://user-images.githubusercontent.com/2602313/172666100-357cb77a-4b4f-4bb1-82e2-9a75400f8dcc.jpg) | ![Screenshot_20220608-121046_Brave](https://user-images.githubusercontent.com/2602313/172666141-b3f423a1-c32d-4c4c-a447-9477770d635c.jpg) | ![Screenshot_20220608-121053_Brave](https://user-images.githubusercontent.com/2602313/172666183-8e632fc7-5107-4e74-a762-c21c2cc9ca12.jpg) | ![Screenshot_20220608-124030_Brave](https://user-images.githubusercontent.com/2602313/172671354-2dfa9e43-6771-4c44-b872-16ddde3404f9.jpg) | ![Screenshot_20220608-124136_Brave](https://user-images.githubusercontent.com/2602313/172671351-e7e671ad-660a-45b6-bc17-2d75d24e069a.jpg)
