### ISSUE TITLE
Unable to add portal token using auto-populate via contract address

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#22845]
## Description 

Unable to add portal token using auto-populate via contract address

## Steps to Reproduce

   1. Select Solana network
   2. Open add custom asset
   3. Enter `EPeUFDgHRxs9xxEPVaL6kfGQvCon7jmAWKVUHuux1Tpz` in contract address, auto populates the token but adds it as `wormhle` rather than `portal`

## Actual result:

https://user-images.githubusercontent.com/17010094/168332466-0cfc0e90-5ecd-4e58-89a8-99f1d9dcc468.mp4

## Expected result:
Should add correct token 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.39.101 Chromium: 101.0.4951.64 (Official Build) beta (arm64)
-- | --
Revision | `d1daa9897e1bc1d507d6be8f2346e377e5505905-refs/branch-heads/4951@{#1208}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by onyb** [comment]
No longer valid. We now auto-populate correctly to Basic Attention Token (Portal).
