### ISSUE TITLE
Add 'feature request' button to wallet page

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#22843]
## Description 

Add feature request button to bottom right of the page

As much as possible it should be visible within wallet. there should be an easy to find this button. 

**Feedback (insert lightbulb)** should do it

Should link to https://community.brave.com/tags/c/wallet/131/feature-request

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.45.85 Chromium: 106.0.5249.91 (Official Build) beta (64-bit) 
-- | --
Revision | `fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}`
OS | Linux

- Verified Wallet page has a `Request a feature` button
- Verified button is linked to `https://community.brave.com/tags/c/wallet/131/feature-request`
- Verified clicking the button opens community page in a new tab
- Verified button is shown always on all Wallet screens

https://user-images.githubusercontent.com/17010094/194244354-cfd870c4-34f0-4818-bf3c-45a45deb089a.mp4

------------------------
Verification passed on

Brave | 1.45.85 Chromium: 106.0.5249.91 (Official Build) beta (64-bit) 
-- | --
Revision | `fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}`
OS | Windows 11 Version 21H2 (Build 22000.978)

- Verified Wallet page has a `Request a feature` button
- Verified button is linked to `https://community.brave.com/tags/c/wallet/131/feature-request`
- Verified clicking the button opens community page in a new tab
- Verified button is shown always on all Wallet screens

https://user-images.githubusercontent.com/17010094/194243809-26432e12-b9e1-40f6-9ed5-b7a8436d88b6.mp4

------------------------
Verification passed on

Brave | 1.45.85 Chromium: 106.0.5249.91 (Official Build) beta (arm64)
-- | --
Revision | `fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}`
OS | macOS Version 12.4 (Build 21F79)

- Verified Wallet page has a `Request a feature` button
- Verified button is linked to `https://community.brave.com/tags/c/wallet/131/feature-request`
- Verified clicking the button opens community page in a new tab
- Verified button is shown always on all Wallet screens

https://user-images.githubusercontent.com/17010094/194242340-85afae70-7b20-40ba-9c1f-3c96fbc95cab.mov
