### ISSUE TITLE
Manual test run on OSX/macOS for `1.40.x - Nightly` (Checking C102)

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#22841]
Following basically checks and ensured that you can install the latest Nightly that includes `C102` on older `macOS` versions without any issues/startup crashes. For reference, we had a startup crash on `C97` as per https://github.com/brave/brave-browser/issues/20351 that wasn't caught before we released.

* [x] macOS High Sierra
* [x] macOS Sierra
* [x] OS X El Captain

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS High Sierra 10.13.6 x64` using the following build:

```
Brave | 1.40.56 Chromium: 101.0.4951.67 (Official Build) nightly (x86_64)
--- | ---
Revision | 8888ee7a24e2c36661ddb9536c35b7d4852a3a98-refs/branch-heads/4951@{#1230}
OS | macOS Version 10.13.6 (Build 17G14042)
```

* verified that the `.dmg` can be installed without any issues
* ensured that `1.40.56 Chromium: 101.0.4951.67` launches without any issues
* ensure that you can restart the browser several times without any issues/crashes
