### ISSUE TITLE
`youtube.com on YouTube` gets added to Auto-Contribute list

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#22859]
## Description

STR:

1. Opened a fairly new/fresh profile on 

Brave | 1.40.56 Chromium: 101.0.4951.67 (Official Build) nightly (x86_64)
-- | --
Revision | 8888ee7a24e2c36661ddb9536c35b7d4852a3a98-refs/branch-heads/4951@{#1230}
OS | macOS Version 12.3 (Build 21E230)

2. Tried to test Auto-Contribute with YouTube video: https://www.youtube.com/watch?v=fAfOurUEcM8 from verified YouTube channel
3. Saw `youtube.com on YouTube` entry get added to A-C list. Shortly after, I saw "Vice News" properly added (see screenshot). **Perhaps it didn't pick up Vice channel info yet, so just added youtube.com generically to the A-C list, and then once it detected Vice channel info, then it added Vice on YouTube as a separate item on the A-C list?**

### Expected result

Never see `youtube.com on YouTube` get added to the A-C list. (If YouTube itself has a YouTube channel, then it would be YouTube on YouTube, but not `youtube.com on Youtube`, which looks like a bug.)

## Screenshot 

![image](https://user-images.githubusercontent.com/11497541/168584300-d4a30d16-48ff-4bd1-8778-cca842e732ff.png)

**Comment by Miyayes** [comment]
Check if it's greaselion, or filters on the tab listeners. (zenparsing)

**Comment by zenparsing** [comment]
In 1.49.x with a fresh profile I saw the following in the AC list:

<img width="592" alt="Screen Shot 2023-01-12 at 5 24 32 PM" src="https://user-images.githubusercontent.com/5995084/212194329-c817e1e5-71ab-4f5f-bf6e-361f10cc4d51.png">

It looks like perhaps the `YouTube on YouTube` issue has been fixed but we still don't necessary filter out the social platform site from AC.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.49.92 Chromium: 110.0.5481.77 (Official Build) beta (x86_64)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | macOS Version 12.6.3 (Build 21G419)
```

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Samsung Galaxy version 12` running `Bravemonoarm64.1pk_1.49.116`

- Confirmed no `youtube.com on YouTube` creator listed in Auto-Contribute list:

Example | Example
---------|----------
![Screenshot_20230303-165240_Brave - Beta](https://user-images.githubusercontent.com/38657976/222708601-46496bb3-eda3-4c74-93e8-311998e13b99.jpg) | ![Screenshot_20230303-165320_Brave - Beta](https://user-images.githubusercontent.com/38657976/222708612-ef400af1-04c0-4ab0-b70f-e539d3526858.jpg)
