### ISSUE TITLE
New window duplicates pinned tabs in Ubuntu 18.04

### ISSUE THREAD

**Issue by nunopimpaomartins** [brave/brave-browser#2285]
## Description 
When opening a new browser window or dragging a tab outside the main window to create one, this will duplicate all pinned tabs.
Is this intended or a bug?
Tried searching for it but could not find any information on this behaviour.

## Steps to Reproduce
   1. On the browser window, open a new window Ctrl+N
   2. Alternatively, drag any tab outside to create a new window

## Actual result:
![braveissue](https://user-images.githubusercontent.com/16762812/49234780-98705780-f3f0-11e8-8af5-d67d8d20d740.jpg)

## Reproduces how often: 
Happens everytime.

## Brave version (brave://version info)
Brave: 0.25.2 
V8: 6.9.427.23 
rev: 8ea2a9ce5ca329478186e6393e07f1cf87d34a22 
Muon: 8.1.8 
OS Release: 4.15.0-39-generic 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 69.0.3497.100

**Comment by srirambv** [comment]
You are currently on the deprecated muon version. Please upgrade to the current stable release. You can download using the following [setup instructions](https://brave-browser.readthedocs.io/).
