### ISSUE TITLE
Update themed app icon for Android 13

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#22861]
## Description 
In Android there is new themed app icon is used. We need to update it to use ours instead of Chromium's.

https://user-images.githubusercontent.com/30602739/168603317-d340252e-e5c4-4490-a91b-09a10a074a09.mp4

## Steps to reproduce 

   1. Install app on Android 13.
   2. You'll see Chromium's icon. 

## Actual result 
Chromium's icon

## Expected result
Brave's icon

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by samartnik** [comment]
As per @aguscruiz

**Comment by aguscruiz** [comment]
Follow up comment, so we don't loose track of an issue:

Ideally if we could swap the icons in light/dark modes, if there was a way to do it, that would be the best, since inverting the colors makes the lion look weird and out of the brand guidelines. (the lion face getting the color instead of the mane shouldn't happen).

If there was a way to force two icons, one for light and another for dark mode, that would solve the issue since we can use a different version that prevents it.

If there is a way, let me know and I'll prepare the dark theme version in a sec.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 13` using the following build(s):

```
Brave | 1.41.82 Chromium: 103.0.5060.66 (Official Build) beta (32-bit)
--- | ---
Revision | 20b1569438a85e631d15e83eb355e3e326e5da6f-refs/branch-heads/5060@{#1066}
OS | Android 13;
```

**`Nightly`** | **`BETA`**
--------------|-------------
![Screenshot_20220628-140913](https://user-images.githubusercontent.com/2602313/176252909-5b987a4f-29d1-453e-9648-57ba43534739.png) | ![Screenshot_20220628-140646](https://user-images.githubusercontent.com/2602313/176252915-46be63d0-82f9-4518-bcfb-185a978bc8c7.png)

**Comment by kjozwiak** [comment]
Going to close this off as verified. Once we get `1.41.x` RC builds, it should be pretty obvious if the wrong icon is being used.

**Comment by samartnik** [comment]
@kjozwiak sorry for not being clear, issue was with themed icons specifically, so to check it you need to turn this option on

![Screenshot_20220628_144229](https://user-images.githubusercontent.com/30602739/176258409-d53a62b4-b182-4aa5-8469-e37489a73cf8.png)

**Comment by kjozwiak** [comment]
@samartnik no worries 👍 Didn't know the feature existed! Ran through it again using the following STR/Cases:

* enabled `Themed icons` via `Settings` -> `Wallpaper and style`
* installed `Nightly` & `BETA` and ensured that the icons are being displayed correctly

**`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|---------------|-----------------|------------------
![Screenshot_20220628-145340](https://user-images.githubusercontent.com/2602313/176261637-cffb6359-189d-43d3-b37b-3887a1b454e7.png) | ![Screenshot_20220628-145358](https://user-images.githubusercontent.com/2602313/176261651-9c1bfd92-07d4-4f84-8bac-17a168faf01d.png) | ![Screenshot_20220628-150001](https://user-images.githubusercontent.com/2602313/176261671-e13d44dd-caa1-43ad-a24c-20eb2222e033.png) | ![Screenshot_20220628-145856](https://user-images.githubusercontent.com/2602313/176261679-712678fe-e8df-4e25-8b9b-4d27eb51e577.png)
