### ISSUE TITLE
Remove `Phone as a security key` setting from Brave Shields and Privacy setting

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#22860]
## Description 
Remove `Phone as a security key` setting from Brave Shields and Privacy setting

## Steps to reproduce 

   1. Open Brave Shields and privacy settings
   2. Scroll down to `Phone as a security key`

## Actual result 
<img width=300 src=https://user-images.githubusercontent.com/17010094/168600028-2865d30f-20f9-4953-9f01-e0d01c653071.png>

## Expected result
No settings

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): All
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
All

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @AlexeyBarabash @samartnik

**Comment by asheroto** [comment]
Hi, just curious, what's the bug here?

**Comment by mcfalld** [comment]
how do you disable this? My browser suddenly started asking me to insert my security key. I don't have one, when I cancel, it then asks me to use my phone.
