### ISSUE TITLE
Blocking functionality on www.wsj.com

### ISSUE THREAD

**Issue by Northshoot** [brave/brave-browser#2286]
## Description 

The printing functionality does not work with shields up. 

## Steps to Reproduce

   1. Go to www.wsj.com
   2. Select an article 
   3.  Press the print button

## Actual result:

Noting happens

## Expected result:
Print dialog opens

## Reproduces how often: 

Every time

## Brave version (brave://version info)

```

Brave | 0.58.9 Chromium: 71.0.3578.53 (Official Build) dev (64-bit)
-- | --
Revision | 599fb72e740eab9d10609f1ed28a2ad669f82c1a-refs/branch-heads/3578@{#669}
OS | Mac OS X
JavaScript | V8 7.1.302.21
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.53 Safari/537.36
Command Line | /Applications/Brave Browser Dev.app/Contents/MacOS/Brave Browser Dev --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --enable-features=EnableEmojiContextMenu,DesktopPWAWindowing,fill-on-account-select,NewExtensionUpdaterService --disable-features=SharedArrayBuffer,DefaultEnableOopRasterization,VizDisplayCompositor,AutofillSaveCardSignInAfterLocalSave,AutofillServerCommunication --flag-switches-begin --flag-switches-end
Executable Path | /Applications/Brave Browser Dev.app/Contents/MacOS/Brave Browser Dev

```

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
I am on dev

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

disabling Brave Shields resolve the issue
Works in Chome

### Additional Information

should not block printing functionality.

**Comment by kirkins** [comment]
Can't reproduce issue on Version 0.59.2 Chromium: 71.0.3578.80 (Official Build) dev (64-bit) for Ubuntu 18.04.

Have shields up and the print button still works as expected.

**Comment by Northshoot** [comment]
I tested several links and sometimes it works. See here:


does not work:
https://www.wsj.com/articles/state-funeral-for-president-george-h-w-bush-suggests-its-possible-to-unite-as-well-as-divide-1544048342 
https://www.wsj.com/articles/its-time-for-your-job-interview-youll-be-talking-to-yourself-1543418495

works:
https://www.wsj.com/articles/restrained-inflation-reduces-urgency-for-quarterly-rate-increase-pattern-1544127856?mod=hp_lead_pos1

The spinner on these pages does not stop and pages seem to have trouble loading fully.
Console errors I get:

```
Access to XMLHttpRequest at 'data:text/plain,' (redirected from 'https://dpm.demdex.net/id?d_visid_ver=1.6.0&d_fieldgroup=AAM&d_rtbd=json&d_ver=2&d_orgid=CB68E4BA55144CAA0A4C98A5%40AdobeOrg&d_nsid=0&d_mid=76478904207623275102774838652099960571&d_blob=j8Odv6LonN4r3an7LhD3WZrU1bUpAkFkkiY1ncBR96t2PTI&ts=1544134311619') from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by iefremov** [comment]
@srirambv  FYI this doesn't seem related to #2252

**Comment by mrzealot** [comment]
The missing print dialog is just a symptom of the page not being able to finish loading fully (just like @Northshoot said). Why that happens is related to how we treat the blocking of Google's IMA library (as also encountered in #2931): when it is 307 redirected to an empty data url, the site thinks it should be there, but since it isn't, it retries in an endless loop. If we modify the 307 response to actual blocking, the loop stops, and the corresponding video (and the site) loads.

As a temporary workaround, one can set up a DevTools-based blocking by

1. Opening DevTools
2. Clicking on the Network tab
3. Finding a reference to https://imasdk.googleapis.com/js/sdkloader/ima3.js
4. Right clicking and selecting "Block requerst URL"

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.63.35 Chromium: 74.0.3729.61 (Official Build) beta(64-bit)
-- | --
Revision | 5df2c8936783bd7575987e45d72a92fcf528496b-refs/branch-heads/3729@{#645}
OS | Mac OS X

* Verified going to articles (such as https://www.wsj.com/articles/state-funeral-for-president-george-h-w-bush-suggests-its-possible-to-unite-as-well-as-divide-1544048342) on Release version (0.62.51) and going to Share > Print on the article does not bring up the print window. Repeating same steps on 0.63.35 does bring up Print window.
