### ISSUE TITLE
Wire up Solana Address Validation in UI

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#22879]
## Description 
Wire up Solana Address Validation in UI

Reference: https://github.com/brave/brave-browser/issues/22141

**Comment by kjozwiak** [comment]
The above requires `1.39.109` or higher for `1.39.x` verification 👍

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.39.109 Chromium: 102.0.5005.50 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>f6e2cf8f59ec714bdcff8499991d55898875f287-refs/branch-heads/5005@{#648}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22621.1)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/13349>brave/brave-core#13349</a></li>
         <li>Verified Solana Address validation is done against Invalid SOL address, Contract Address and Same address</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/169583936-44f16cb7-d30a-416d-b746-16cd1f235bfb.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/169584630-b3ba8b94-58cd-48de-a3a2-8c6bc8859406.mov>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/169584610-2616f010-a1bf-4502-8ee0-3e0b6eb61085.mov>
      </td>
   </tr>
</table>
