### ISSUE TITLE
Update Widgets previews to remove Chrome defaults

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#22875]
## Description 
We should update the previews for our widgets to include Brave Search, remove Google's example links.

## Steps to reproduce 

   1. Go to your home screen
   2. Tap on "Add widget"
   3. See Brave's widgets

## Actual result 
![Screenshot_20220516-143024_One UI Home](https://user-images.githubusercontent.com/15734630/168650482-51217347-ab5c-40de-acea-7419839daf5e.jpg)
![Screenshot_20220516-143030_One UI Home](https://user-images.githubusercontent.com/15734630/168650496-8af9b760-523c-462f-85e5-b0a1f73a96bc.jpg)
![Screenshot_20220516-143033_One UI Home](https://user-images.githubusercontent.com/15734630/168650502-5f98bdb9-c2fd-4c32-bbcf-67528cea2e6a.jpg)
![Screenshot_20220516-143040_One UI Home](https://user-images.githubusercontent.com/15734630/168650506-249abbeb-8d4b-4daf-baed-016e4adcc424.jpg)
![Screenshot_20220516-143059_One UI Home](https://user-images.githubusercontent.com/15734630/168650510-5a701a42-bb70-4726-b37a-cd6c3fc0c0b9.jpg)

## Expected result
We should remove every chrome reference

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version: 11
   
## Brave version
All

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by lukemulks** [comment]
+1 

Confirming that the Quick action search and Dino widgets contain the mismatch in static image. 

Android, Samsung 

The Quick action search widget = excellent, btw.
![Screenshot_20220609-224658_One UI Home](https://user-images.githubusercontent.com/8979240/173000259-18209c34-4065-4266-b6d5-33e6b221030b.jpg)

**Comment by Uni-verse** [comment]
In progress on Samsung Galaxy S21 using version: 

```
Brave	1.47.169 Chromium: 109.0.5414.87 (Official Build) (64-bit) 
Revision	2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS	Android 12; Build/SP1A.210812.016
```
Spec: https://github.com/brave/internal/issues/942#issue-1426313155

**Clean Profile**

**Quick Action Widget**

Adding Quick Action Widget via menu (long press and drag)
Adding Quick Action Widget via menu (Add button)
Adding Widget via callout in url box
Adding Widget from home screen widget windo
Updating SE 
Using Widget features (search, private tab)
Removing widget

**Brave Search Widget**

Adding search widget from home screen
Using search feature
Changing SE

**Brave Bookmarks Widget**
Adding widget using home screen widget window
Adding bookmarks
Removing bookmarks 
Loading bookmarks

**Upgraded Profile**

Existing widgets
Adding quick action widget
Adding brave quick search widget
Changing SE post upgrade
Adding bookmarks post upgrade
