### ISSUE TITLE
It is not possible to change the download location in the "Save as" dialog

### ISSUE THREAD

**Issue by pgrepds** [brave/brave-browser#22871]
## Description 

It is not possible to change the download location in the "Save as" dialog.

## Steps to Reproduce

   1.  Choose any file, e.g. a PDF document, and open the "Save as" dialog 
   2.  Choose a location which differs from the default download location set in the settings
   3.  Click "Save"

## Actual result:

Nothing happens. The file is not saved. No error message.

Saving to the default location works.

## Expected result:

The file is saved to the location choosen in the "Save as" dialog.

## Reproduces how often: 

Every time.

## Brave version (brave://version info)

Brave | 1.38.115 Chromium: 101.0.4951.64 (Official Build) (64-bit)
-- | --
Revision | d1daa9897e1bc1d507d6be8f2346e377e5505905-refs/branch-heads/4951@{#1208}
OS | Linux

My complete OS info:

OS: Manjaro 21.2.6 Qonos
Kernel: x86_64 Linux 5.15.38-1-MANJARO

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No.
- Does the issue resolve itself when disabling Brave Rewards? No.
- Is the issue reproducible on the latest version of Chrome? Yes.

Thus, it seems to be related to the newest version of chrome.

**Comment by i23098** [comment]
Same thing happens to me, it seems the save dialog is not the system dialog, it's different than before...

**Comment by ECon87** [comment]
same, also cannot edit file name

**Comment by pgrepds** [comment]
This issue seems to be fixed in: **Version 1.39.111 Chromium: 102.0.5005.61 (Official Build) (64-bit)**. I have just retested with the newest version.
