### ISSUE TITLE
Clicking by "already purchased" link does nothing on VPN bubble

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#22874]
Clicking by "already purchased" link does nothing on VPN bubble 
![image](https://user-images.githubusercontent.com/2965009/168650000-9df78c4f-5327-433e-848c-e370c9df9336.png)

**Comment by stephendonner** [comment]
Hmm, https://github.com/brave/brave-browser/issues/22711 was earlier, but since the fix is here, I guess we should dupe or at least cross-link (and check/verify in one issue, when verifying).

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.41.17 Chromium: 102.0.5005.61 (Official Build) nightly (x86_64)
-- | --
Revision | 0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}
OS | macOS Version 11.6.6 (Build 20G624)

### Steps:

1. launch Brave
2. open `brave://flags`
3. set `brave://flags/#brave-vpn` to `Enabled`
4. set `brave://flags/#skus-sdk` to `Enabled`
5. set `brave://flags/#skus-environment` to `development`
6. click on the `Relaunch` button
7. click on the `VPN` button on the browser toolbar
8. click on `Already purchased VPN?`
9. follow remaining flows to restore already-purchased account (I used `vpn-test-19@mailinator.com`)

#### Confirmed I was able to successfully restore an already-purchased VPN account via the `Already purchased VPN?` link.

example | example | example | example | example | example
---------|----------|---------|----------|---------|---------
<img width="1312" alt="Screen Shot 2022-05-26 at 3 16 22 PM" src="https://user-images.githubusercontent.com/387249/170589653-aa304ed4-b03a-4e26-bf45-b8a99d8d3072.png"> |<img width="1312" alt="Screen Shot 2022-05-26 at 3 16 35 PM" src="https://user-images.githubusercontent.com/387249/170589662-7ec43c3d-d80c-418c-acff-9116e22d987f.png"> | <img width="1735" alt="Screen Shot 2022-05-26 at 2 50 06 PM" src="https://user-images.githubusercontent.com/387249/170589855-75ee71cf-f5fd-419e-b31a-fc592e8a712f.png"> | <img width="1735" alt="Screen Shot 2022-05-26 at 2 50 11 PM" src="https://user-images.githubusercontent.com/387249/170589861-e5bd5d3d-1ce6-45b2-ae0b-af8aa0cd9921.png"> |<img width="1680" alt="Screen Shot 2022-05-26 at 2 50 19 PM" src="https://user-images.githubusercontent.com/387249/170589864-4d84defc-8fe1-4100-a95c-6306dc4a1527.png"> |<img width="1680" alt="Screen Shot 2022-05-26 at 2 50 44 PM" src="https://user-images.githubusercontent.com/387249/170589867-f560e956-5042-4b7e-b57f-7129fe5397f9.png">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.41.74 Chromium: 103.0.5060.53 (Official Build) beta (64-bit)
-- | --
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | Windows 11 Version 21H2 (Build 22000.739)
```

### Steps:

1. launch Brave
2. open `brave://flags`
3. set `brave://flags/#brave-vpn` to `Enabled`
4. set `brave://flags/#skus-sdk` to `Enabled`
5. set `brave://flags/#skus-environment` to `development`
6. click on the `Relaunch` button
7. click on the `VPN` button on the browser toolbar
8. click on `Already purchased VPN?`
9. `https://account.brave.software/`  is loaded in a new tab
10. followed remaining flows to restore already-purchased account with my existing account

#### Confirmed, able to successfully restore an already-purchased VPN account via the `Already purchased VPN?` link.


Step 8|Step 9|ex|ex|ex
---|---|---|---|---
<img width="959" alt="image" src="https://user-images.githubusercontent.com/98358127/174856845-27e307bc-2438-449e-80b7-de96ded4a2ad.png">|<img width="956" alt="image" src="https://user-images.githubusercontent.com/98358127/174857410-a3a8ae94-317b-4f4d-9b18-30de5d77c84b.png">|<img width="953" alt="image" src="https://user-images.githubusercontent.com/98358127/174857507-7585eb8f-1e90-424b-8795-b113c665e52c.png">|<img width="961" alt="image" src="https://user-images.githubusercontent.com/98358127/174857556-ed8a303b-d9a9-42e2-b824-30f3b825e07c.png">|<img width="957" alt="image" src="https://user-images.githubusercontent.com/98358127/174857606-2ed24c2b-9b95-49e9-bc0c-0cbee16e40d4.png">
