### ISSUE TITLE
Reloading page resets network selection

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#22873]
## Description 

Reloading page resets network selection

## Steps to Reproduce

   1. Create Solana wallet on nightly
   2. Select Solana under network list on portfolio
   3. Reload the page, resets to all network

## Actual result:

https://user-images.githubusercontent.com/17010094/168631364-582614ac-09ad-484b-93f3-8a13c3c272b1.mov

## Expected result:
Should retain the network selection

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html><head></head>
<body>

Brave | 1.40.58 Chromium: 102.0.5005.50 (Official Build) nightly (64-bit)
-- | --
Revision | `f6e2cf8f59ec714bdcff8499991d55898875f287-refs/branch-heads/5005@{#648}`
OS | Windows 11 Version 22H2 (Build 22621.1)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by Douglashdaniel** [comment]
We will need a `networkFilter` pref with `getNetworkFilter` and `setNetworkFilter` methods from the core side to make this persist.
