### ISSUE TITLE
Fix wrongly computed insufficient funds errors

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#22877]
### Case 1

<img src="https://user-images.githubusercontent.com/3684187/168667362-fb7ec1ff-3b53-43a3-a571-d6c60c4d4f32.png" width="300px">

**Remark:** total fiat amount in swap transaction is too low for the gas fee + ETH amount

### Case 2

<img src="https://user-images.githubusercontent.com/3684187/168669987-4f9aa217-9797-4c22-9542-e34e189e7d0b.jpeg" width="300px">

**Remark:** everything appears "normal", but it's not clear if the error is due to insufficient gas or insufficient token balance

**Comment by kjozwiak** [comment]
The above requires `1.39.109` or higher for `1.39.x` verification 👍

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.39.111 Chromium: 102.0.5005.61 (Official Build) (64-bit) </th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22621.1)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/13347>brave/brave-core#13347</a></li>
         <li>Verified insufficient funds message is not shown when there is sufficient balance while doing a transaction</li>
         <li>Verified error message is retained and confirm button doesn't get enabled</li>
         <li>Verified closing and reopening panel doesn't allow the confirm button to be clicked when the error message is shown</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/169816693-796cae96-1f90-4eeb-b1cf-0a63961463ed.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/169815925-d965519c-cac6-48c2-8541-efca1e1fc97f.mov>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/169815893-c80f1b35-fd00-4567-8899-9efafe62aaf0.mov>
      </td>
   </tr>
</table>
