### ISSUE TITLE
Add pre-loaded EVMs into wallet network selector (supported by 0x)

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#22888]
- Polygon
- Binance Smart Chain
- Celo
- Avalanche
- Fantom
- Optimism

**Comment by kjozwiak** [comment]
The above requires `1.40.80` or higher for `1.40.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.40.83 x64 beta build
- Verified selected EVM's are prepopulated on a clean install
- Verified existing custom EVM's take precedence while upgrading
- Encountered [#23205](https://github.com/brave/brave-browser/issues/23205) & [#23234](https://github.com/brave/brave-browser/issues/23234)

Clean Install | Upgrade
-- | --
<video src=https://user-images.githubusercontent.com/17010094/171849036-9175442e-10d1-4534-bcc5-499f9818ed1b.mp4> | <video src=https://user-images.githubusercontent.com/17010094/171849068-e795a6f0-b130-48fd-89e9-20cb3455ad8c.mp4>

-----------
Verification passed on Oppo Reno 5 with Android 12 running 1.40.83 x64 beta build
- Verified selected EVM's are prepopulated on a clean install
- Verified existing custom EVM's take precedence while upgrading
- Encountered [#23205](https://github.com/brave/brave-browser/issues/23205) & [#23234](https://github.com/brave/brave-browser/issues/23234)

Clean Install | Upgrade
-- | --
<video src=https://user-images.githubusercontent.com/17010094/171850301-1458bd4c-ba7f-494b-b11f-2741e50250ea.mp4> | <video src=https://user-images.githubusercontent.com/17010094/171850349-eac51f59-30ad-4e65-bda1-eab36fa09fd5.mp4>

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.40.91 Chromium: 102.0.5005.78 (Official Build) beta (64-bit) </th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.708)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/13369>brave/brave-core#13369</a></li>
         <li>Verified selected EVM's are prepopulated on a clean install</li>
         <li>Verified existing custom EVM's take precedence while upgrading</li>
         <li>Encountered [#23359](https://github.com/brave/brave-browser/issues/23359)</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/172854580-023d7965-97c9-416b-83e1-18bd033d82a6.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/172855271-e1bd6fcf-7f95-4bb1-bda4-b43bd0a2f97e.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/172856055-f520528f-6818-4d4b-b722-f75b4dc9b89a.mov>
      </td>
   </tr>
</table>
