### ISSUE TITLE
Sync security improvements: Delete account

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#22884]
A user who wants to stop using Sync should have the ability to delete their encrypted data from our server. Next to the “Leave Sync chain” button at the bottom of the page, we should have a “Delete Sync account” button. It would trigger the following confirmation dialog:

```
   Deleting your account will remove your encrypted data from Brave servers and 
   disable Sync on all of your connected devices. 
   It will not however delete the data that is stored locally on those devices.
   This deletion is permanent and there is no way to recover the data. Should you decide to 
   start using Sync again, you will need to create a new account and re-add each device one by one.
         [ Permanently delete account ] [ Cancel ]
```

Spec: https://docs.google.com/document/d/1X7glDHmeIjgipcPWn__S9rSxrI39P9rNw0RmuEuC3BI/edit#heading=h.f9zbg4b885l

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.48.125 Chromium: 109.0.5414.87 (Official Build) beta (x86_64)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | macOS Version 11.7.2 (Build 20G1020)

### Case A: Initial case
<details>

1. Create the sync chain between desktop deviceA and deviceB
2. Keep Sync settings page opened on both A and B
3. On deviceA press Delete Sync account, agree with warning
4. Expected on deviceB sync state will be reset.
5. Expected not to see the informer.

</details>

### Case B: Informer on 2nd device
<details>

Create the sync chain
On device B: close tab brave://settings/braveSync/setup, close browser app
On deviceA press Delete Sync account, agree with warning
Open browser on device B
Expected to see the informer on deviceB. Press re-create the account
Expected on deviceB sync state will be reset

</details>

### Case C: Deny enter deleted chain
<details>

Create sync chain
Save the sync code
Delete sync account
Try to enter the chain with words from pt2
Expected to get message
Could not join this sync chain. Account was deleted.

</details>

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.48.131 Chromium: 109.0.5414.87 (Official Build) beta (64-bit)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | Windows 11 Version 21H2 (Build 22000.1455)
```


### Case A: Initial case - `PASSED`
<details>

1. installed `1.48.131`
2. launched Brave
3. created the sync chain between desktop `deviceA` (`Win 11 x64`) and `deviceB` (`Win 11 xArm`)
4. kept the Sync settings page opened on both A and B
5. on `deviceA`, pressed the `Delete Sync account` button
6. confirmed `deviceB`'s sync state was also reset
7. confirmed I did *not* see the informer

`deviceA` | `deviceB` | `deviceA` | `deviceA` | `deviceB`
-----------|-----------|-----------|------------|----------
<img width="450" alt="image" src="https://user-images.githubusercontent.com/98358127/213318976-f0ba4709-1606-4583-b514-f0cf17e78e9c.png">

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using `Brave` `1.48.141` `Chromium` `109.0.5414.119` on a `Google Pixel XL` (`arm64`) running `Android 9`
