### ISSUE TITLE
VPN connect / reconnecting may not have a proper timeout

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#22883]
## Description 
Reported by @stephendonner. He had connected to VPN and then turned off WiFi. Clicking VPN button, it looks like it's trying to reconnect - but there's no timeout. It should timeout and transition to the error state

This may have the same root cause as https://github.com/brave/brave-browser/issues/22754

## Steps to Reproduce
   1. Enable VPN (see test plan in https://github.com/brave/brave-browser/issues/15804 for more information)
   2. Click VPN button (next to hamburger menu) and connect to a server
   3. Disconnect your network (if plugged in with ethernet unplug, if on WiFi disable)
   4. Click VPN button again - it should be trying to reconnect

## Actual result:
It gets stuck saying "Connecting..."
![image](https://user-images.githubusercontent.com/4733304/168739611-9a7e3e1e-ebcb-4652-81de-f21955c907c8.png)

## Expected result:
It should error out and show the error page in VPN panel

**Comment by spylogsster** [comment]
This may have the same root cause as https://github.com/brave/brave-browser/issues/23028

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.41.36 Chromium: 102.0.5005.78 (Official Build) nightly (x86_64)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | macOS Version 12.5 (Build 21G5027d)

Followed the test plan from https://github.com/brave/brave-core/pull/13504#issue-1250619720.

### Steps:
1. enabled VPN (see test plan in https://github.com/brave/brave-browser/issues/15804 for more information)
2. clicked `VPN` button (next to hamburger menu) and connected to `USA (West)`, which is my geo-detected default
3. disabled Wi-Fi
4. clicked `VPN` button again - it should quickly try to reconnect, then...
5. confirmed `VPN` dialog's status is accurate, and now says `Disconnected`
6. confirmed toggling `VPN` when `Connected`/`Disconnected` keeps accurate connection state(s)

Initial disconnect is much slower then subsequent ones - I'll have to chase that up separately 👍 

![issue-22883](https://user-images.githubusercontent.com/387249/171993258-a9b858ca-1d83-45ec-b076-34aa40414db1.gif)

**Comment by MadhaviSeelam** [comment]
@spylogsster  
I am confused as to expected result for this issue on `Win 11x64`.  I see error modal `Can't connect server` in `Win 11 x64`.  
Expected result mentioned in the issue says `show error page` and test plan in the PR says show `disconnection status`.  @stephendonner tested this in `1.41.36 nightly` and got correct status as per the test plan.  It's failing for me in the `1.41.36 nightly` as well.  I am not sure if this behavior is restricted to `macOS` 

![2022-07-06_16h03_47](https://user-images.githubusercontent.com/98358127/177658806-84c1d1bb-c5a1-49ea-afe2-a86dcb8a5b52.gif)

**Comment by MadhaviSeelam** [comment]
This issue `VPN connect / reconnect` is not working as expected.  @stephendonner filed a follow up issue #23294 as above.  
@spylogsster @rebron
