### ISSUE TITLE
[Sync] GenerateCryptoErrorForTypes error, Sync isn't working

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#22898]
## Description 
There are complains that on Android sometimes appears `Sync isn't working`  popup and sync-internals contains GenerateCryptoErrorForTypes errors. Sync settings contains the controls with the placeholders for formatting.

I could reproduce it by making actions with the local server.

| First Header  | Second Header |
| ------------- | ------------- |
|![Screenshot_20220517-211541](https://user-images.githubusercontent.com/24739341/168884635-c640e2aa-b680-4bc8-a506-2b81b63d7435.png)|![Screenshot_20220517-211547](https://user-images.githubusercontent.com/24739341/168884690-127ba258-ccfd-484a-846b-25156d83134c.png)|

## Steps to reproduce 

   1. Configure local sync server, use https://github.com/brave/go-sync 
   2. Ensure you can connect the desktop and Android device into the sync chain on the local sync server
   3. Leave the sync chain on Android device
   4. Open QR code on desktop
   5. Shut down the local sync server 
   6. Connect the Android device to the sync chain by QR code - expected to fail
   7. Exit Android browser
   8. Run the local sync server 
   9. Launch Android browser
   10. go to brave://sync-internals

## Actual result 
`GenerateCryptoErrorForTypes` errors

## Expected result
No errors

## Steps to reproduce if you can't run local sync server:

1. Open QR code on desktop
2. On Android open the sync QR code scanner, but don't scan QR image
3. On Android turn off the internet
4. On Android scan the QR image
5. Exit Android browser
6. Turn on the internet
7. Launch Android browser

## Actual: 
the image on screen, and `GenerateCryptoErrorForTypes` in sync-internals
## Expected: 
sync works

## Issue reproduces how often 
Easily reproduced, but needs the local server and Android browser modification to be able connect the local server (hardcode local server ip)

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by AlexeyBarabash** [comment]
With the steps provided, at https://source.chromium.org/chromium/chromium/src/+/main:components/sync/nigori/nigori_sync_bridge_impl.cc;l=321?q=NigoriSyncBridgeImpl::NigoriSyncBridgeImpl&ss=chromium%2Fchromium%2Fsrc  `state_.pending_keys` is not empty, this causes the error.

We provide the passphrase to make the decryption on normal sync setup flow. As for the broken sync setup flow I checked, whether it is enogh to make the same:
https://github.com/brave/brave-core/commit/edb2bcf0b504c10f5b59cc187aa2ac815769bc32 , and it was enough.

So I am implementing to gave passphase supplied for such cases.

**Comment by AlexeyBarabash** [comment]
As per https://github.com/brave/brave-ios/issues/5304, iOS is also affected.

**Comment by kjozwiak** [comment]
We'll need some STR/Cases for `Desktop`. @AlexeyBarabash mind providing some? Sounds like the above is also happening on desktop as per https://github.com/brave/brave-browser/issues/22898#issuecomment-1131843313.

Looks like it's working well on `Android` as per https://github.com/brave/brave-core/pull/13397#issuecomment-1148168804.

**Comment by LaurenWags** [comment]
Removed `QA/Blocked` due to additional detail from @AlexeyBarabash 😄

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.39.118 Chromium: 102.0.5005.78 (Official Build) (x86_64)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | macOS Version 12.4 (Build 21F79)
```
