### ISSUE TITLE
Unexpected script blocked even when block script is off

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#22897]
## Steps to Reproduce

   1.  Launch with fresh profile
   2. Navigate to `brave://settings/content/javascript`
   3. Add an entry in Not allowed to use Javascript for example `www.bloomberg.com`
<img width="715" alt="Screen Shot 2022-05-17 at 13 06 36" src="https://user-images.githubusercontent.com/11330831/168900709-7e8274d4-ae8b-4fe8-846f-d0c3b8cace2a.png">

   5. Open a new tab and navigate to any sites that use scripts like youtube.com
   6. Open shield and see block scripts number

## Actual result:

<img width="393" alt="Screen Shot 2022-05-17 at 11 23 52" src="https://user-images.githubusercontent.com/11330831/168884130-55dca61c-a038-435c-9b21-54b7f2892f20.png">

## Expected result:
No scripts is blocked when block script is off
## Reproduces how often: 

Always

## Brave version (brave://version info)

1.40.59 Chromium: 102.0.5005.50 (Official Build) nightly (x86_64) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 
    - Yes, starting with chromium 102, chromium 101 has no issue

## Other Additional Information:
Note that removing the individual blocking rule in brave://settings/content/javascript will bypass the issue
so if anyone is experiencing similar issue, just clear the block section of  brave://settings/content/javascript

**Comment by GeetaSarvadnya** [comment]
Reproduced the issue in an upgraded profile. If scripts are blocked for one site in CR101 after upgrade to CR102 the scripts are blocked for all the opened sites. 

1. Clean profile `1.40.22 cr101`
2. Open twitter.com and open shield and block the scripts
3. Open a few sites (e.g cnn.com, theverge.com)
4. Confirmed scripts are not blocked for cnn.com and theverge.com
5. Upgrade the profile to `1.40.62 cr102`
6. Open twitter.com and ensured scripts are blocked as expected
7. Open cnn.com and theverge.com
8. Scripts blocked count is shown in the shield for cnn.com and theverge.com even though the scripts block switch is OFF in the shield

step 6 | step 8 | step 8
-- | -- | --
![image](https://user-images.githubusercontent.com/38657976/168961558-451d4fd2-7c41-4505-8dd1-6348ce944a3a.png) | ![image](https://user-images.githubusercontent.com/38657976/168961609-f34ed76f-e5af-4525-86e8-36700406d78d.png) | ![image](https://user-images.githubusercontent.com/38657976/168961680-e7f1dc0a-5070-4f10-baf0-ec976e3d6959.png)

**Comment by kjozwiak** [comment]
The above requires `1.39.109` or higher for `1.39.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```
Brave | 1.39.109 Chromium: 102.0.5005.50 (Official Build) (64-bit)
-- | --
Revision | f6e2cf8f59ec714bdcff8499991d55898875f287-refs/branch-heads/5005@{#648}
OS | Windows 10 Version 21H2 (Build 19044.1706)

```

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.39.109 Chromium: 102.0.5005.50 (Official Build) (x86_64)
-- | --
Revision | f6e2cf8f59ec714bdcff8499991d55898875f287-refs/branch-heads/5005@{#648}
OS | macOS Version 12.3.1 (Build 21E258)
```
