### ISSUE TITLE
Issues with Bitbucket site

### ISSUE THREAD

**Issue by Northshoot** [brave/brave-browser#2289]
## Description 

For some reason, bitbucket pipeline functionality does not work in brave. I have been in contact with Bitbucket and they have created a public issue that they as well investigate https://bitbucket.org/site/master/issues/17648/add-brave-browser-support

But it seems that the changes in chrome somehow mess up their site.

## Steps to Reproduce

   1. Create a repo in bitbucket
   2. Goto setting
   3. Try enabling pipeline

## Actual result:

<img width="769" alt="2018-11-28_15-14-39" src="https://user-images.githubusercontent.com/7857361/49237980-51fd0780-f3b4-11e8-9172-558762bb9d5f.png">

Confirmed via pipeline window:

<img width="1031" alt="2018-11-28_15-30-26" src="https://user-images.githubusercontent.com/7857361/49238022-66410480-f3b4-11e8-8524-e44415d178e7.png">

## Expected result:
In fact, pipelines are enabled and visible when using chrome browser.

## Reproduces how often: 

Every time.

## Brave version (brave://version info)

```
Brave | 0.58.9 Chromium: 71.0.3578.53 (Official Build) dev (64-bit)
-- | --
Revision | 599fb72e740eab9d10609f1ed28a2ad669f82c1a-refs/branch-heads/3578@{#669}
OS | Mac OS X
JavaScript | V8 7.1.302.21
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.53 Safari/537.36

```

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
I am on dev version

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
No, the issue remains

- Is the issue reproducible on the latest version of Chrome? 
No, works fine in Chrome.

**Comment by imperugo** [comment]
Just got the same problem and now I can't use atlassian platform (jira, confluence and Bitbucket)
@Northshoot did you find a way to restore everything like before the change of the pipeline?

Now for me is important to restore atlassian platform to work with brave

Thanks

**Comment by Northshoot** [comment]
> Just got the same problem and now I can't use atlassian platform (jira, confluence and Bitbucket)
> @Northshoot did you find a way to restore everything like before the change of the pipeline?
> 
> Now for me is important to restore atlassian platform to work with brave
> 
> Thanks

The only thing that worked was using firefox or chrome. Bitbucket said they won't support Brave. But it seems that pipelines are the only issue that I run into after disabling shields.

**Comment by wranvaud** [comment]
I had issues today to comment on commits (error on save) and approve PRs (I click the button but nothing happens). That's pretty much the core of my interaction with bitbucket.

**Comment by 0x49D1** [comment]
I had issue today during adding WebHooks and adding users to the repository (cross site request warning appears). No problem with same functions on Firefox.
![image](https://user-images.githubusercontent.com/1378866/64962639-d15ab980-d8a8-11e9-9782-9e2f9986f171.png)

**Comment by carlos8alb** [comment]
![Sin título](https://user-images.githubusercontent.com/35976960/94102382-5b067500-fe75-11ea-9dcb-460e517edb0b.jpg)

**Comment by ryanbr** [comment]
Hey, just checking on this ticket @Northshoot @0x49D1 @wranvaud 

We made changes to allow cookies to work correctly on bitbucket. Is this ticket still causing issues?

**Comment by ryanbr** [comment]
Before closing this, have re-checked,

* Able to login
* Able to create a repo.
*  Enable, and deploy Pipeline (and staging and production successful)
*  and Re-run pipelines.


![bb-pite](https://user-images.githubusercontent.com/1659004/115487607-2a70a780-a2ad-11eb-9c41-ace210c94704.png)
![pp-pite2](https://user-images.githubusercontent.com/1659004/115487612-2e9cc500-a2ad-11eb-8edb-6022ef4683bb.png)
