### ISSUE TITLE
Implement improved UI/UX for supported/unsupported regions per custodian (custodian selection modal)

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#22905]
## Description

Depending on whether a custodian is available in a given user's region, gray out and provide messaging (or not) in the Rewards linking/verification UI/UX. 

**See: https://github.com/brave/internal/issues/876**

**Comment by Miyayes** [comment]
Behind: https://github.com/brave/brave-browser/issues/24542

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.46.87 Chromium: 107.0.5304.91 (Official Build) beta (x86_64)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | macOS Version 12.6.1 (Build 21G217)
```

**Comment by Uni-verse** [comment]
In Progress on Android ARM
