### ISSUE TITLE
[De-AMP] If link tag is not within first chunk, AMP page does not get De-AMPed

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#22917]
## Description 

By design, for performance and ease of implementation, we only check the first raw chunk of HTML for the AMP html tag and link canonical tag. If that is not the case, we don't De-AMP an AMP page.

We have two options:
1. Inject JS to check if a page is an AMP page and navigate to canonical version. This is what iOS does. This is easy but loses the privacy advantage of using the throttle and URL loader.
2. Continue looking past the first chunk for the canonical link. This maintains the privacy advantages of the current brave-core approach, but is slightly more involved to implement - have to make sure the body_sniffer state machine is correctly modified.

Note that with the second option we would still only be looking for the canonical link, and only if it's an AMP page. 

## Steps to Reproduce

   1. Make sure De-AMP is enabled in brave://settings/shields
   2. Go to a page like https://www-nytimes-com.cdn.ampproject.org/c/s/www.nytimes.com/wirecutter/blog/burner-browser-to-hide-internet-searches/amp/
 

## Actual result:

![image](https://user-images.githubusercontent.com/5284154/169087887-53341e20-2157-4f8b-9002-6a62db6ea830.png)

## Expected result:

Go to https://www.nytimes.com/wirecutter/blog/burner-browser-to-hide-internet-searches/

## Other example URLs

1. https://lifehacker-com.cdn.ampproject.org/c/s/lifehacker.com/do-this-android-app-privacy-audit-i-beg-you-1849151056/amp
2. https://www-technologyreview-com.cdn.ampproject.org/c/s/www.technologyreview.com/2020/07/01/1004725/redesign-internet-apps-no-one-controls-data-privacy-innovation-cloud/amp/

## Reproduces how often: 

Always

## Version/Channel/Platform
This happens for both Android and Desktop, Stable (1.38+)

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.44.79 Chromium: 105.0.5195.102 (Official Build) beta (x86_64)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | macOS Version 13.0 (Build 22A5331f)

### Steps:
1. installed `1.44.79`
2. launched Brave
3. opened `brave://settings/shields`
4. confirmed `Auto-redirect AMP pages` was toggled to `On` / `Enabled`
5. loaded the URLs mentioned in the original test plan

step 4 | site 1 | site 2 | site 3
-------|------|-------|------
<img width="1312" alt="Screenshot 2022-09-08 at 12 57 19 PM" src="https://user-images.githubusercontent.com/387249/189215128-50b03bcb-bb7d-4319-b14c-67432d93e70a.png"> | <img width="1312" alt="Screenshot 2022-09-08 at 12 57 52 PM" src="https://user-images.githubusercontent.com/387249/189215170-24ac6619-3834-4caa-b49d-91b0d5d7dd0f.png"> | <img width="1312" alt="Screenshot 2022-09-08 at 12 58 06 PM" src="https://user-images.githubusercontent.com/387249/189215173-5b8101a5-9875-431d-be04-9238b604885c.png"> | <img width="1312" alt="Screenshot 2022-09-08 at 12 58 20 PM" src="https://user-images.githubusercontent.com/387249/189215175-4b65a00a-66ac-4e6d-be6e-057e56e5dbf7.png">

#### Confirmed all sites loaded full-desktop views.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.44.85 Chromium: 105.0.5195.127 (Official Build) beta (64-bit)
-- | --
Revision | 912488396852bf658ab32465980c0b93a3c27a83-refs/branch-heads/5195@{#1109}
OS | Windows 11 Version 21H2 (Build 22000.978)
```

1. Installed 1.44.85
2. launched Brave
3. opened `brave://settings/shields` 
4. confirmed `Auto-redirect AMP pages` setting is `Enabled/ON`
5. verified below URLs loaded as expected

#### URL 1:
- https://www-nytimes-com.cdn.ampproject.org/c/s/www.nytimes.com/wirecutter/blog/burner-browser-to-hide-internet-searches/amp/ redirected to https://www.nytimes.com/wirecutter/blog/burner-browser-to-hide-internet-searches/

#### URL  2: 
- https://lifehacker-com.cdn.ampproject.org/c/s/lifehacker.com/do-this-android-app-privacy-audit-i-beg-you-1849151056/amp
redirected to https://lifehacker.com/do-this-android-app-privacy-audit-i-beg-you-1849151056

#### URL 3: 
- https://www-technologyreview-com.cdn.ampproject.org/c/s/www.technologyreview.com/2020/07/01/1004725/redesign-internet-apps-no-one-controls-data-privacy-innovation-cloud/amp/ redirected to https://www.technologyreview.com/2020/07/01/1004725/redesign-internet-apps-no-one-controls-data-privacy-innovation-cloud/

#### URL 4: 
- [test-very-big-amp-outside-max-chunk.html](https://shivankaul.com/brave/de-amp/test-very-big-amp-outside-max-chunk.html)  should not de-amp - page loaded with lot of `a` s

#### URL 5: 
- [test-very-big-amp-inside-max-chunk.html](https://shivankaul.com/brave/de-amp/test-very-big-amp-inside-max-chunk.html) should de-amp - redirected to brave.com

step 4|URL1|URL 2|URL 3|URL 4|URL 5
----|----|----|----|----|-----
<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/190249273-85ee3394-78c7-4bda-8d8d-5f8905f0b8a8.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/190245985-354f07e6-0d30-4564-94b2-8120b6425b0a.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/190246713-2cd20bf9-bc07-40e4-89f2-5ea28233dc1e.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/190247055-c3245cee-359b-4758-8353-6e27ba939b5d.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/190247760-ba44a320-3a0f-4df5-9a56-2d7f99e51788.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/190248334-02463cb4-85f7-49e9-b790-5822da2b1bb7.png">

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.44.88 Chromium: 105.0.5195.136 (Official Build) beta (64-bit)
--|--
Revision | 872774b783d0e674186a3adcd2f92e7aa22a219c-refs/branch-heads/5195_124@{#4}
OS | Linux

### Steps:
1. Installed `1.44.88`
2. launched Brave
3. opened `brave://settings/shields` 
4. confirmed `Auto-redirect AMP pages` setting is `Enabled/ON`
5. verified below URLs loaded as expected

#### URL 1:
- https://www-nytimes-com.cdn.ampproject.org/c/s/www.nytimes.com/wirecutter/blog/burner-browser-to-hide-internet-searches/amp/ redirected to https://www.nytimes.com/wirecutter/blog/burner-browser-to-hide-internet-searches/

#### URL  2: 
- https://lifehacker-com.cdn.ampproject.org/c/s/lifehacker.com/do-this-android-app-privacy-audit-i-beg-you-1849151056/amp
redirected to https://lifehacker.com/do-this-android-app-privacy-audit-i-beg-you-1849151056

#### URL 3: 
- https://www-technologyreview-com.cdn.ampproject.org/c/s/www.technologyreview.com/2020/07/01/1004725/redesign-internet-apps-no-one-controls-data-privacy-innovation-cloud/amp/ redirected to https://www.technologyreview.com/2020/07/01/1004725/redesign-internet-apps-no-one-controls-data-privacy-innovation-cloud/

#### URL 4: 
- [test-very-big-amp-outside-max-chunk.html](https://shivankaul.com/brave/de-amp/test-very-big-amp-outside-max-chunk.html)  should not de-amp - page loaded with lot of `a` s

#### URL 5: 
- [test-very-big-amp-inside-max-chunk.html](https://shivankaul.com/brave/de-amp/test-very-big-amp-inside-max-chunk.html) should de-amp - redirected to brave.com

step 4|URL1|URL 2|URL 3|URL 4|URL 5
----|----|----|----|----|-----

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 13` using the following build(s):

```
Brave | 1.44.95 Chromium: 106.0.5249.40 (Official Build) (32-bit)
--- | ---
Revision | fab1d91915d2722d6339aaa7f4e9ce44f1e9b103-refs/branch-heads/5249@{#442}
OS | Android 13; Build/T1B1.220819.006
```

STR/Cases:

* launched `1.44.95 Chromium: 106.0.5249.40`
* ensured that `Hamburger Menu` -> `Settings` -> `Brave Shields & privacy` -> `Auto-redirect AMP pages` is enabled by default

Ensured that the following URL are correctly being redirected:

* ensured that https://www-nytimes-com.cdn.ampproject.org/c/s/www.nytimes.com/wirecutter/blog/burner-browser-to-hide-internet-searches/amp/ redirects to https://www.nytimes.com/wirecutter/blog/burner-browser-to-hide-internet-searches/ without any issues

* ensured that https://lifehacker-com.cdn.ampproject.org/c/s/lifehacker.com/do-this-android-app-privacy-audit-i-beg-you-1849151056/amp redirects to https://lifehacker.com/do-this-android-app-privacy-audit-i-beg-you-1849151056 without any issues.

* ensured that https://www-technologyreview-com.cdn.ampproject.org/c/s/www.technologyreview.com/2020/07/01/1004725/redesign-internet-apps-no-one-controls-data-privacy-innovation-cloud/amp/ redirects to https://www.technologyreview.com/2020/07/01/1004725/redesign-internet-apps-no-one-controls-data-privacy-innovation-cloud/ without any issues.

* ensured that https://shivankaul.com/brave/de-amp/test-very-big-amp-outside-max-chunk.html didn't re-direct and page loaded with a bunch of `aaaaaaaaaaaaaaaaaaaaaaa`

* ensured that https://shivankaul.com/brave/de-amp/test-very-big-amp-inside-max-chunk.html redirected to `brave.com`
