### ISSUE TITLE
Placeholder is missing in a string

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#22914]
## Test plan
See https://github.com/brave/brave-core/pull/13621

## Description
The string `IDS_BRAVE_VPN_PAYMENT_FAILURE_REASON` currently reads:

> Looks like your most recent payment for did not go through. Access to this subscription will pause until the payment issue is resolved. Try to edit your payment method, or contact Brave support.

According to Figma the text should include a placeholder:

> Looks like your most recent payment for [subscription_name] did not go through. Access to this subscription will pause until the payment issue is resolved. Try to edit your payment method, or contact Brave support.

The placeholder `[subscription_name]` is missing.

cc: @nullhook

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.41.55 Chromium: 102.0.5005.115 (Official Build) nightly (x86_64)
-- | --
Revision | 174dbe6e33bc81994fceb71d751be201d0b4803d-refs/branch-heads/5005_109@{#3}
OS | macOS Version 12.5 (Build 21G5037d)

Can't believe I missed this before!

Tested using the testplan from https://github.com/brave/brave-core/pull/13621#issue-1261709663 (I advanced the system clock, to make it easy).

Confirmed the text now reads:

```
Looks like your most recent payment for Brave Firewall + VPN did not go through. Access to this subscription will pause until the payment issue is resolved. Try to edit your payment method, or contact Brave support.
```

`1.41.55` | `1.40.91`
----------|---------
<img width="1359" alt="Screen Shot 2022-08-12 at 2 44 27 PM" src="https://user-images.githubusercontent.com/387249/173155188-00a111d1-b9b5-490b-bfbf-f6e730f347f8.png"> | <img width="1312" alt="Screen Shot 2022-06-10 at 2 37 30 PM" src="https://user-images.githubusercontent.com/387249/173154892-d94d7c35-e20a-41f8-82e7-f315c8d33ea3.png">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.41.74 Chromium: 103.0.5060.53 (Official Build) beta (64-bit)
-- | --
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | Windows 11 Version 21H2 (Build 22000.739)
```
Tested using the testplan from https://github.com/brave/brave-core/pull/13621#issue-1261709663
(Verified this modal by testing with `Too many recovery attempts` page with the same account and advancing the system clock.)
Reproduced in `1.40.100`
Confirmed correct text and now reads:
```
Looks like your most recent payment for Brave Firewall + VPN did not go through. Access to this subscription will pause until the payment issue is resolved. Try to edit your payment method, or contact Brave support.
```
`1.41.74-A`| `1.41.74-B`|`1.40.100`
---|---|---
<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/174885101-13944230-6bb0-42c9-8b79-7a8c3d255824.png">|<img width="959" alt="image" src="https://user-images.githubusercontent.com/98358127/174894120-fedf7f1a-135f-472d-ad8b-1ae9de9f65c4.png">|<img width="953" alt="image" src="https://user-images.githubusercontent.com/98358127/174886176-13be84b4-72fb-4922-912d-f9b8f9995ae5.png">
