### ISSUE TITLE
DApps: Do not show wallet panel on NTP 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#22910]
## Description 
Do not show wallet panel on NTP 

## Steps to reproduce 
Note: May need to disable bottom toolbar 

   1. Connect to a Dapp so wallet icon is shown in URL bar
   2. Swipe tabs to switch context
   3. Wallet icon is shown in URL on NTP and can still be opened to show an empty state

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/169044115-ce540e7c-9c49-4da7-8167-bda9f01f3f76.png)

## Expected result
No wallet icon in URL bar when on NTP or on a non-web3 page

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? On custom build

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 11
   
## Brave version
Custom build with Dapp support

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @Pavneet-Sing @SergeyZhukovsky @jamesmudgett

**Comment by kjozwiak** [comment]
The above will require `1.40.78` or higher for `1.40.x` verification 👍
