### ISSUE TITLE
DApps: Add bottom padding to signature request message

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#22913]
## Description 
Add bottom padding to signature request message

## Actual result 
<img width=400 src=
![image](https://user-images.githubusercontent.com/17010094/169046984-067f74f9-2a48-4577-9c90-7896b4f4ae82.png)

## Expected result
More padding on bottom of the text

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version?NA

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 11
   
## Brave version
Custom Dapp support build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @jamesmudgett @Pavneet-Sing @SergeyZhukovsky

**Comment by kjozwiak** [comment]
The above requires `1.40.78` or higher for `1.40.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.40.105 x64 build
- Verified buttons are now aligned at the bottom to maintain consistency

Oppo Reno 5(Android 12) | Samsung Tab A (Android 10)
-- | --
<img width=290 src=https://user-images.githubusercontent.com/17010094/174057799-0a30a16e-caab-46bb-ab0c-d10fa312afa0.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/174059449-e55fc34d-4c64-49f6-8750-cb63622071f3.png>
