### ISSUE TITLE
DApps: Consider reducing the spacing between icons in URL bar

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#22912]
## Description 
Consider reducing the spacing between icons in URL bar

## Steps to reproduce 

   1. Disable bottom toolbar
   2. Visit a Dapp to show wallet icon in URL bar
   3. 3 icons in URL bar is spaced out causing to show only part of URL which can be of security concern 

## Actual result 
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/17010094/169045874-1f925505-d847-4e04-9dea-98bbbae3dd2c.png">

## Expected result
Better design for URL bar icons

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version?NA

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 11
   
## Brave version
Custom Dapp support build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/sec-team @jamesmudgett @SergeyZhukovsky @Pavneet-Sing

**Comment by jenn-rhim** [comment]
There's minimum thumb-friendly spacing between the interactive elements on mobile and this may be even beyond that in order to accommodate the number of the tools on our bar.  Reducing further will start causing users to make frequent mistakes or at a minimum causing them to take time and be precise about targeting. 

We should have a UX rule that defines helps us keep the URL bar usable.  @Sam-Sibley

**Comment by Sam-Sibley** [comment]
We generally aim for a minimum 44px tap area. But it looks like its more than that in production on my Android device and by the look of that screenshot. So we may have have room to tighten them up. I'll do a quick QA check against the design files and post a screenshot.

**Comment by Sam-Sibley** [comment]
Based on a quick analysis, it looks like there is extra padding in production compared to the Figma Designs we have, so we should reduce padding between icons by about 5px to visually reduce space while still maintaining a usable tap area:
<img width="1581" alt="Screenshot 2022-05-23 at 10 51 56 am" src="https://user-images.githubusercontent.com/99699532/169724432-6130af4d-0860-4e4a-bc6a-d21b7780f35f.png">

**Comment by Sam-Sibley** [comment]
@srirambv the above is quick fix to alleviate some of the problem, while we look at other options for our url bar icons
