### ISSUE TITLE
Unify IPFS DNSLink  behaviors for local and public gateway

### ISSUE THREAD

**Issue by lidel** [brave/brave-browser#22927]
Public gateways inline DNSLink names  into a single label: 

- `https://dweb.link/ipns/en.wikipedia-on-ipfs.org` → redirect → `https://en-wikipedia--on--ipfs-org.ipns.dweb.link/wiki/`

Localhost gateway does not do that, it keeps the subdomains as they are:

- `http://localhost:48080/ipns/en.wikipedia-on-ipfs.org` → redirect → `http://en.wikipedia-on-ipfs.org.ipns.localhost:48080/wiki/`

## Proposed change

To unify website behaviors, the embedded Kubo (go-ipfs) gateway that is backing `ipns://en.wikipedia-on-ipfs.org` should do the same inlining, ensuring Origins are constructed the same way on public and local gateways.

### How

- (A)  This can be done by setting `X-Forwarded-Proto: https` on all `ipns://{dnslink-name}` requests sent to the embedded gateway.
  - Upside: it will enable inlining and does not require new Kubo release
  - Downside: this will return redirect to `https://*.ipns.localhost:48080`  and brave needs to revertit back to `http://`
- (B) Alternative is to add new flag to Kubo and make a new release
   - Upside: clean and future proof
   - Downside needs new Kubo release

**Comment by lidel** [comment]
@cypt4 we should prioritize this, if possible (ask @bridiver and @diracdeltas  for full context)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.48.132 Chromium: 109.0.5414.87 (Official Build) beta (64-bit) 
-- | --
Revision | `2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}`
OS | Linux

- Verified steps from [brave/brave-core#16129](https://github.com/brave/brave-core/pull/16129)
- Verified IPFS DNSLink loads correctly on both localhost and public gateway

Localhost | Public Gateway
-- | --
<video src=https://user-images.githubusercontent.com/17010094/214049890-39b60149-3608-4d77-be47-6331b3500e0f.mp4> | <video src=https://user-images.githubusercontent.com/17010094/214050167-0e179c48-0d9b-4434-9c9d-9111cead4b79.mp4>

---------------------

Verification passed on 

Brave | 1.48.132 Chromium: 109.0.5414.87 (Official Build) beta (64-bit)
-- | --
Revision | `2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#16129](https://github.com/brave/brave-core/pull/16129)
- Verified IPFS DNSLink loads correctly on both localhost and public gateway

Localhost | Public Gateway
-- | --
<video src=https://user-images.githubusercontent.com/17010094/214043924-21ceced6-ea7c-49ae-961b-24924da1b874.mp4> | <video src=https://user-images.githubusercontent.com/17010094/214043279-de4e8658-887c-4d25-b1a7-ff77cf7bc1e1.mp4>

---------------------

Verification passed on 

Brave | 1.48.132 Chromium: 109.0.5414.87 (Official Build) beta (arm64)
-- | --
Revision | `2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#16129](https://github.com/brave/brave-core/pull/16129)
- Verified IPFS DNSLink loads correctly on both localhost and public gateway

Localhost | Public Gateway
-- | --
<video src=https://user-images.githubusercontent.com/17010094/214051546-47a1107e-9ff6-457e-a29f-d426b17a2403.mov> | <video src=https://user-images.githubusercontent.com/17010094/214051394-5689a0c2-ce79-4ed4-a356-f13905bf57b5.mov>
