### ISSUE TITLE
Hide the All Networks Icon when Selected

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#22920]
## Description 
We need to hide the `All networks` icon when it is selected.

![Screen Shot 2022-05-18 at 11 44 33 AM](https://user-images.githubusercontent.com/40611140/169108124-be933059-d2e4-43df-aeb3-d6e9adf576e6.png)

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.39.117 Chromium: 102.0.5005.78 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>8888ee7a24e2c36661ddb9536c35b7d4852a3a98-refs/branch-heads/4951@{#1230}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22621.1)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td>
      </td>
      <td colspan=3>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/13378>brave/brave-core#13378</a></li>
         <li>Verified All Networks icon is only shown when the drop-down list is opened</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/171876075-07732b7e-1652-4f91-afcd-0c45341e79ff.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/171876030-dd52570f-c721-426f-86d8-604771688eba.mov>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/171875835-10e236e3-a279-4e05-b54b-3a758e498384.mov>
      </td>
   </tr>
</table>
