### ISSUE TITLE
ENS L2 support

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#22930]
https://docs.ens.domains/dapp-developer-guide/ens-l2-offchain
Domain records could now be on L2 chains or propriety database based on above doc, we need to implement what's mentioned in the doc to support this.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.45.88 Chromium: 106.0.5249.91 (Official Build) beta (64-bit) 
-- | --
Revision | `fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}`
OS | Linux

- Verified steps from [brave/brave-core#14447](https://github.com/brave/brave-core/pull/14447)
- Verified `offchainexample.eth` resolves  to `0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045` in `Send To` field

https://user-images.githubusercontent.com/17010094/194524518-8cab4f9e-6d14-4441-9b5c-ff0cf451f875.mp4

------------------------
Verification passed on

Brave | 1.45.88 Chromium: 106.0.5249.91 (Official Build) beta (64-bit) 
-- | --
Revision | `fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}`
OS | Windows 11 Version 21H2 (Build 22000.978)

- Verified steps from [brave/brave-core#14447](https://github.com/brave/brave-core/pull/14447)
- Verified `offchainexample.eth` resolves to `0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045` in `Send To` field

https://user-images.githubusercontent.com/17010094/194525120-126c04c2-7b3c-4540-8679-140b4ccbebf5.mp4


------------------------
Verification passed on

Brave | 1.45.88 Chromium: 106.0.5249.91 (Official Build) beta (arm64)
-- | --
Revision | `fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [brave/brave-core#14447](https://github.com/brave/brave-core/pull/14447)
- Verified `offchainexample.eth` resolves to `0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045` in `Send To` field

https://user-images.githubusercontent.com/17010094/194486679-07b43bbe-c1c8-4f0a-84a7-45ee21ad1d61.mov
