### ISSUE TITLE
[Android VPN] [Beta User Feedback] Split Tunneling

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#22938]
**Beta User Feedback**
> Last observation is there is no split tunnel option so I can't choose specific apps to bypass the VPN. Ideally banking apps and ones that need local access (eg. Home NAS, File Explorer to SMB shares) should allow VPN bypass.

> Can you all add split tunneling in this browser? If I'm ever going to download while I'm using the vpn in this browser, I won't be able to play my games properly.

> There is no split tunnel option so I can't choose specific apps to bypass the VPN. Ideally banking apps and ones that need local access (eg. Home NAS, File Explorer to SMB shares) should allow VPN bypass.

> I would also like to see more in depth configuration options, such as split tunneling.

**Requirements**
Add new settings option under Settings -> Brave Firewall + VPN:
Header: Split Tunneling
Option: Choose Trusted Apps.

Under this new option the user should be able to
1. Enable and disable trusted apps (bypass the VPN for these apps).
2. Search for a specific app.
3. Hide/show system apps.

For reference, here is a video of the split tunneling UX/UI in NordVPN:

https://user-images.githubusercontent.com/28269287/171226389-0238408d-ca4c-4f1b-aaf9-a11222c94478.mp4

**Comment by deeppandya** [comment]
@timchilds we need to update this issue as we have changes the design as per the conversation.

**Comment by Uni-verse** [comment]
Verified on `Android ARM` and `Android Tablet` in https://github.com/brave/brave-browser/issues/24576#issuecomment-1230660763 & https://github.com/brave/brave-browser/issues/24576#issuecomment-1230705014 respectively.

as https://github.com/brave/brave-browser/issues/24576 is a follow to this issue.
