### ISSUE TITLE
Reset button is not properly aligned

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#22941]
## Description 

Reset button is not properly aligned

## Steps to Reproduce

   1. Set locale to German
   2. Open Send/Swap on widget
   3. Reset button isn't properly aligned 

## Actual result:

https://user-images.githubusercontent.com/17010094/169360105-430cfebb-3d36-4513-bdc7-c6431694cb5a.mov

## Expected result:
Properly aligned reset button

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html><head></head>
<body>

Brave | 1.38.119 Chromium: 101.0.4951.67 (Offizieller Build) (64-Bit)
-- | --
Überarbeitung | `8888ee7a24e2c36661ddb9536c35b7d4852a3a98-refs/branch-heads/4951@{#1230}`
Betriebssystem | Windows 11 Version 22H2 (Build 22621.1)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @josheleonard @Douglashdaniel

**Comment by Douglashdaniel** [comment]
Closing as `not actionable` since the `Buy/Send/Swap` widget has been depreciated.
