### ISSUE TITLE
Add three News P3A questions related to usage time

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#22945]
## Description 

Adding three new News P3A questions related to sessions/usage timing:

"As an opted in Brave News user, when was the last time I used Brave News?"
`Brave.Today.LastUsageTime`

1) This week
2) 1 week ago
3) 2 weeks ago
4) 3 weeks ago
5) A month ago
6) Over a month ago

"As an opted in Brave News user, how many days did I use Brave News in the last 30 days?"
`Brave.Today.DaysInMonthUsedCount`

0) 0 days
1) 1 day
2) 2 days
3) 3 to 5 days
4) 6 to 10 days
5) 11 to 15 days
6) 16 to 20 days
7) More than 20 days

"As a first time user of Brave News this week, did I return again to use it during the week?"
`Brave.Today.NewUserReturning`

0) I have never used Brave News
1) I have used Brave News, but I'm not a first time Brave News user this week
2) I'm a first time Brave News user this week but, no, I did not return the rest of the week
3) I'm a first time Brave News user this week and, yes, I returned and used it again the following day
4) I'm a first time Brave News user this week and, yes, I returned and used it again this week but not the following day

**The first two questions will only be reported if Brave News was used at least once.**

## Miscellaneous Information:
Will raise PR soon.

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```
Brave | 1.41.82 Chromium: 103.0.5060.66 (Official Build) beta (64-bit)
-- | --
Revision | 20b1569438a85e631d15e83eb355e3e326e5da6f-refs/branch-heads/5060@{#1066}
OS | Windows 10 Version 21H2 (Build 19044.1766)

```

**Comment by GeetaSarvadnya** [comment]
@DJAndries I am not understanding the logic to calculate the `A month ago` and `Over a month ago` stats. Is there definite logic to calculating these stats? 
**Case 1:** `A month ago` is triggered even when a month is not yet completed after enabling/viewing the brave news. On the 29th day itself, I am getting a month ago response value `5` which looks incorrect - Logged https://github.com/brave/brave-browser/issues/23759
**Case 2:** After enabling/viewing the brave news today (29th June), If I set the system date to 30th or31 st July or 1st Aug or 5th Aug or 10th Aug - I am getting the month ago response value `5` which looks incorrect 

What is the threshold of `a month ago` and  `over a month ago? How many days after a month is considered as over a month ago, could you give a brief explanation on calculating the `a month ago` and `over a month ago` stats?

cc: @mattmcalister

**Comment by GeetaSarvadnya** [comment]
@DJAndries Need few clarifications on the `Brave.Today.DaysInMonthUsedCount`

For the `opted-in brave news` state also metrics value should get changed? currently, only for brave news view state, the metrics response value is getting increased

In Android, we have the option to enable the brave news via settings. So just wanted to know the value of the metric when `opted-in brave news` state and brave news view states.

**Comment by DJAndries** [comment]
The metric should only be increased when a user has scrolled down to see the News view, and they haven't used News on that day. This applies to both Android and Desktop.

**Comment by GeetaSarvadnya** [comment]
@DJAndriesThis implementation does not apply to the existing users who have viewed brave news in 1.40.x profile correct? Does it apply from 1.41 onwards?

**Comment by DJAndries** [comment]
Yes, 1.41.x onwards

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.41.95 x64 
- Verified steps from [brave/brave-core#13396](https://github.com/brave/brave-core/pull/13396)
- Verified P3A values for News is properly calculated

<details>
<summary><i>Brave.Today.LastUsageTime</i> - <b>Passed</b></summary>

- Verified `Brave.Today.LastUsageTime` doesn't exist on a clean profile
- Verified after enabling and viewing News `Brave.Today.LastUsageTime` is updated to `1`
- Verified moving date ahead by 1 week, updates `Brave.Today.LastUsageTime`  to `2`
- Verified moving dates ahead updates the value of `Brave.Today.LastUsageTime` correspondingly 

Case 1: 0 - 6 days | Case 2: 7 - 13 days | Case 3: 14 - 20 days | Case 4: 21 - 27 days | Case 5: 28 - 59 days | Case 6: 60 days ago
--  | -- | -- | -- | -- | --
 ![image](https://user-images.githubusercontent.com/17010094/178320821-d72a8584-d7ac-4949-a65c-5410d3e45c26.png) | ![image](https://user-images.githubusercontent.com/17010094/178320924-f473c799-a82d-4db4-a160-5a5b29901120.png) | ![image](https://user-images.githubusercontent.com/17010094/178320982-6f592464-b1f4-4ff5-bb39-d1f82095ce5d.png) | ![image](https://user-images.githubusercontent.com/17010094/178320992-f331fb53-361b-488e-ae61-4447c6f8c141.png) | ![image](https://user-images.githubusercontent.com/17010094/178321004-cb272491-c22e-4526-874b-1488ad84c8a0.png) | ![image](https://user-images.githubusercontent.com/17010094/178321016-57e7ec0c-9295-4b94-8f40-c1a8774d7d1d.png)


</details>
<details>
<summary><i>Brave.Today.DaysInMonthUsedCount</i> - <b>Passed</b></summary>

- Verified on clean install metric `Brave.Today.DaysInMonthUsedCount` isn't shown in `brave://local-state`
- Verified enabling news and viewing feed cards updates `Brave.Today.DaysInMonthUsedCount` to `1`
- Verified other metric values are calculated correctly 

Case 0: 0 days | Case 1: 1 days | Case 2: 2 days | Case 3: 3 to 5 days | Case 4: 6 to 10 days | Case 5: 11 to 15 days | Case 6: 16 to 20 days | Case 7: More than 20 days
-- | -- |-- | -- | -- | -- | -- | -- 
![image](https://user-images.githubusercontent.com/17010094/178321578-b2ba0eb9-1bb5-43e0-bb26-958aebbf583f.png) | ![image](https://user-images.githubusercontent.com/17010094/178321593-81b1366c-f34c-45b0-a66b-1eb682913274.png) | ![image](https://user-images.githubusercontent.com/17010094/178321601-256e3f73-95b6-450f-93e0-43ec6b98de70.png) | ![image](https://user-images.githubusercontent.com/17010094/178321613-a07c6a81-22b2-4d94-8303-ffe30d4a2edf.png) | ![image](https://user-images.githubusercontent.com/17010094/178321624-ee2ba239-e454-486d-987a-ae0b6c2e5c0f.png) | ![image](https://user-images.githubusercontent.com/17010094/178321634-cece5dc4-4db5-4e1a-9282-38caf3a27544.png) | ![image](https://user-images.githubusercontent.com/17010094/178321642-07db2f95-ee2d-4435-acad-5541825d8b8e.png) | ![image](https://user-images.githubusercontent.com/17010094/178321656-811dc466-3208-41a4-a894-504c5caadc65.png)

</details>
<details>
<summary><i>Brave.Today.NewUserReturning</i> - <b>Passed</b></summary>

<details>
<summary>Case 1: I have never used Brave News</summary>

- Verified `Brave.Today.NewUserReturning` is set to `0` when News is not enabled
![image](https://user-images.githubusercontent.com/17010094/178324280-3cdaabaf-68d0-4dbd-a812-d211cded388a.png)

</details>
<details>
<summary>Case 2: I have used Brave News, but I'm not a first-time Brave News user this week</summary>

- Verified `Brave.Today.NewUserReturning` is not available on clean isntall
- Verified enabling News and view feed updates `Brave.Today.NewUserReturning` to 2
![image](https://user-images.githubusercontent.com/17010094/178324373-45477c11-6c01-4b4f-aeaf-219fe9569d57.png)

- Verified closing browser and moving date ahead by 3 days and relaunch and viewing feed updates `Brave.Today.NewUserReturning`  to `4`
![image](https://user-images.githubusercontent.com/17010094/178324403-7f70df92-f812-40d5-a34f-72dc521ba893.png)

- Verified closing browser and moving date ahead by a week and relaunch and checking `Brave.Today.NewUserReturning`  shows value as `1`
![image](https://user-images.githubusercontent.com/17010094/178324425-9f8db9a0-191b-4f83-9def-34d3ffc0f178.png)


</details>
<details>
<summary>Case 3: I'm a first-time Brave News user this week but, no, I did not return the rest of the week</summary>

- Verified enabling News this week and not using it for the rest of the week sets  `Brave.Today.NewUserReturning` to 2 as expected
![image](https://user-images.githubusercontent.com/17010094/178324569-db6d6cd5-2ddc-4145-b2e0-27dcbf27cbfd.png)

</details>
<details>
<summary>Case 4: I'm a first-time Brave News user this week and, yes, I returned and used it again the following day</summary>

- Verified enabling News for the first time and using it in the same week and using it the next day sets `Brave.Today.NewUserReturning` to `3` as expected 
![image](https://user-images.githubusercontent.com/17010094/178324731-77f11127-7859-4498-984e-dd84e6cc993f.png)

</details>
<details>
<summary>Case 5: I'm a first-time Brave News user this week and, yes, I returned and used it again this week but not the following day</summary>

- Verified enabling news and viewing feed today sets value of `Brave.Today.NewUserReturning` to 2 
![image](https://user-images.githubusercontent.com/17010094/178324851-f9abfe40-bffc-48c4-8d9e-2a44bb34b921.png)
- Verified moving date ahead by 2 days and viewing news feed updates `Brave.Today.NewUserReturning` to 4 
![image](https://user-images.githubusercontent.com/17010094/178324828-e54da90b-ebd7-41ff-bdc8-5e8e80d5beb6.png)

</details>

</details>
