### ISSUE TITLE
Button/Images are not properly aligned for translated string

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#22942]
## Description 

Button are not properly aligned for translated string

## Steps to Reproduce

Transaction

   1. Set locale to German
   2. Initiate transaction
   3. Check the panel, text and button doesn't have padding

Limit Approval 

   1. Set locale to German
   2. Initiate limit approval transaction
   3. Check the panel, warning icon is not aligned on the same line as the warning text 

## Actual result:

Transaction | Approval 
-- | --
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/17010094/169358949-93a4be1b-df7b-42b9-8fcd-6e4a4c3dc42a.png"> | <img width="1728" alt="image" src="https://user-images.githubusercontent.com/17010094/169359249-991f8b2f-bd2a-4140-8aa0-1f2660ec6006.png">

## Expected result:
Properly aligned text/icons

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html><head></head>
<body>

Brave | 1.39.108 Chromium: 101.0.4951.67 (Offizieller Build) beta (64-Bit)
-- | --
Überarbeitung | `8888ee7a24e2c36661ddb9536c35b7d4852a3a98-refs/branch-heads/4951@{#1230}`
Betriebssystem | Windows 11 Version 22H2 (Build 22621.1)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel @josheleonard

**Comment by jamesmudgett** [comment]
@srirambv are you referring to the edit gas link? I think it's ok since it's a different color.

**Comment by srirambv** [comment]
@jamesmudgett taking specifically about these 
<img width="639" alt="image" src="https://user-images.githubusercontent.com/17010094/172550203-1a5bc440-fce5-4853-b501-aa94dfce5c89.png">
<img width="639" alt="image" src="https://user-images.githubusercontent.com/17010094/172550280-f4cefd1e-8904-4e8d-8ce4-e4d8eb8fabd9.png">

**Comment by josheleonard** [comment]
Doesn't look like this issue is valid anymore. Closing.

![Image](https://github.com/brave/brave-browser/assets/30185185/713ed884-9ffd-429b-a843-713c85d237f2)



![Image](https://github.com/brave/brave-browser/assets/30185185/14fd724a-eaba-4b7c-bd28-ed39214ec512)
