### ISSUE TITLE
Add new setting to show/hide bookmarks and history from the address bar autocomplete results 

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#22948]
## Description 

Users should have the ability to show or hide results from bookmarks and history in the address bar (omnibox). 
These settings should live in:
brave://settings/appearance 
(also considering these settings to live in brave://settings/privacy)

- Create 4 new boolean preferences, which all default to _true_.
- If any preference is set to _false_ by the user, then those items are not shown as autocomplete items in the omnibox.
- If the existing "show autocomplete suggestions in the address bar" pref is set to _false_, then these 4 preferences will appear disabled.
- Also carry over and simplify labelling for "Show top sites in autocomplete suggestions" to "Top sites" and "Show suggested sites in autocomplete suggestions" to "Suggested sites"

## Design

<img width="542" alt="165543395-2e718966-5c7f-4f8e-a88f-9df8ef365860" src="https://user-images.githubusercontent.com/5951041/169403146-dd5fdc9c-320e-45b3-bbaa-52643513c8d3.png">

## Brave version (brave://version info)

Target release 1.41.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

https://github.com/brave/brave-browser/issues/12292

## Test Plan
https://github.com/brave/brave-browser/issues/22948#issuecomment-1151645141

**Comment by petemill** [comment]
Edited description to include more spec

**Comment by waldyrious** [comment]
> Create 4 new boolean preferences, which all default to true.

If the idea is to be privacy-friendly by default, shouldn't the initial setting for the "Browsing history" preference be false? That would be more in line with the general sentiment in #12292, IIUC.

**Comment by fallaciousreasoning** [comment]
@waldyrious I worry that it would degrade the default user experience a bit, as all of a sudden a bunch of things that used to show up would stop. I know that the omnibox is the way I normally find things (i.e. I remember, vaguely, a bit of the title of the page I visitied and it shows up in my suggestions).

I wonder if it would be worth having a separate toggle for search results @petemill? It looks like this is exposed and wouldn't be too hard to add. It does seem like it might be hard to explain the difference though, so I dunno.

![image](https://user-images.githubusercontent.com/7678024/170895364-b1e14af0-24ff-487c-9651-80a305bab22f.png)

**Comment by fallaciousreasoning** [comment]
In addition, I wonder if these settings, rather than living the appearance or privacy section or settings, should live in the search settings, as that seems what they're most closely related too. It seems like these new settings should be grouped with `Auto-complete searches and URLs` in the privacy section.

**Comment by fallaciousreasoning** [comment]
# Test Plan

1. Open `brave://settings/appearance`. 
    There should be new settings for 'Bookmarks' & 'Browsing History' in the Autocomplete section. *Note:* In the old version the preferences for Top sites & Suggested sites were there but with different wordings.
    'Show autocomplete in address bar' should be enabled
    'Top sites' should be enabled
    'Suggested sites' should be disabled
    'Browsing history' should be enabled
    'Bookmarks' should be enabled.

2. Toggling 'Show auto complete suggestions in address bar' should show/hide the Top Sites/Suggested Sites/Browsing History/Bookmarks settings. Restore to the original settings.
3. In a new tab, search for `Hello`.
4. Click on the first result (for me, it's a video of Adele singing Hello) and Bookmark it.
5. Type 'Hel' into the search bar. There should be a search suggestion for `Hello` and a suggestion for the page you bookmarked.
6. Disable the browsing history toggle and type 'hel' into the search bar. There should be a suggestion for the bookmarked page but not for 'hello' from your search history.
7. Disable the 'Bookmark' toggle and type 'hel' into the search bar. You should have an option to search for 'hel' but no suggestions for 'hello'.

**Note:** When you disable 'Browsing history' you also don't get tab suggestions (i.e. searching for an open tab). This is expected behavior, though not ideal.

**Comment by bsclifton** [comment]
Added to 1.42.x milestone 😄 
cc: @fallaciousreasoning

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.42.65 Chromium: 103.0.5060.114 (Official Build) beta (x86_64)
-- | --
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | macOS Version 13.0 (Build 22A5295i)

### Steps:

1. installed `1.42.65`
2. launched Brave
3. opened `brave://settings/appearance`
4. compared to `1.41.96`
5. confirmed `Show autocomplete suggestions in address bar` was checked
6. confirmed `Bookmarks` & `Browsing History` were added
7. confirmed all options except for `Suggested Sites` were `Enabled`

1.42.65 | 1.41.96
--------|--------
<img width="1312" alt="Screenshot 2022-07-14 at 5 32 30 PM" src="https://user-images.githubusercontent.com/387249/179123324-e1003aa1-b76c-4c7a-af03-7a55d12ac1c9.png"> | <img width="1312" alt="Screenshot 2022-07-14 at 5 22 26 PM" src="https://user-images.githubusercontent.com/387249/179123228-2ab3b6ca-5a05-4eb7-bcd8-5c311637ef06.png">


1. toggled 'Show auto complete suggestions in address bar' to `Disabled` and confirm it collapses the subcategories.  Toggle it back to `Enabled`
2. opened a new tab and searched for `Hello`
3. clicked on the first result and bookmarked it
4. typed `Hel` into the search bar. Confirmed search suggestion for `Hello` and a suggestion for the YouTube page I bookmarked.
5. disabled the `Browsing History` toggle and typed `hel` into the search bar. Confirmed suggestion for the bookmarked YouTube page but **not** for 'hello' from my search history.
6. disabled the 'Bookmarks' toggle and type `hel` into the search bar. Confirmed option to search for `hel` but no suggestions for `hello`.

step 1 | step 2 & 3 | step 4 | step 5 | step 6
------|------------|--------|-------|--------
<img width="1312" alt="Screenshot 2022-07-14 at 5 28 21 PM" src="https://user-images.githubusercontent.com/387249/179124290-aca56fce-2009-45bd-a15c-ff88fe27fd93.png"> | <img width="1312" alt="Screenshot 2022-07-14 at 5 35 26 PM" src="https://user-images.githubusercontent.com/387249/179124335-f3847549-870d-4e69-a760-f7c117656843.png"> | <img width="1312" alt="Screenshot 2022-07-14 at 5 35 57 PM" src="https://user-images.githubusercontent.com/387249/179124367-2b5f6511-9714-4fdb-890d-648be20c9bf1.png"> | <img width="1312" alt="Screenshot 2022-07-14 at 5 36 54 PM" src="https://user-images.githubusercontent.com/387249/179124460-e32aa4e9-f857-4da3-953c-90610c8995f5.png"> | <img width="1312" alt="Screenshot 2022-07-14 at 5 37 17 PM" src="https://user-images.githubusercontent.com/387249/179125062-de4f375c-5910-4fa8-8fb8-89c0d23df2f8.png">

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```

Brave | 1.42.73 Chromium: 103.0.5060.134 (Official Build) beta (64-bit)
-- | --
Revision | 8ec6fce403b3feb0869b0732eda8bd95011d333c-refs/branch-heads/5060@{#1262}
OS | Windows 10 Version 21H2 (Build 19044.1826)

```

**Comment by LeuschkeTressa** [comment]
For others coming across this: in Brave 1.48, this option can be found under the "Appearance" heading in Settings. It's called "Show autocomplete suggestions in address bar". If the setting is enabled, check-boxes for more fine-grained control is shown.
