### ISSUE TITLE
no notification when a-c table is empty and contribution is attempted - follow up to 2114

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#2294]
## Description 
Per issue description in #2114 there should be an error notification when Auto Contribute table is empty. 

## Steps to Reproduce

   1. Launch with clean profile on 0.57.8 and `--rewards=reconcile-interval=3`
   2. Enable Rewards
   3. Accept UGP grant.
   4. Do not visit any sites. After specified time (3 minutes from `--rewards=reconcile-interval=3` flag), a contribution should be attempted. 

## Actual result:
No notification is displayed indicating that a contribution could not take place since Auto-Contribute table is empty.

## Expected result:
Notification is displayed.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.57.8 Chromium: 71.0.3578.53 (Official Build) beta(64-bit)
-- | --
Revision | 599fb72e740eab9d10609f1ed28a2ad669f82c1a-refs/branch-heads/3578@{#669}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by NejcZdovc** [comment]
This was decided to be ignored intentionally, so not a bug
