### ISSUE TITLE
Allow to create Mainnet Filecoin accounts

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#22947]
Create Filecoin account according to currently selected network. If FIlecoin Mainnet is selected then we have to create Mainnet accounts, otherwise testnet

![image](https://user-images.githubusercontent.com/2965009/169398841-53fb052b-ee4d-4717-aa1d-c326012cb671.png)

**Comment by kjozwiak** [comment]
The above requires `1.40.80` or higher for `1.40.x` verification 👍
