### ISSUE TITLE
Copy for error messages needs updating in Android VPN flow

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#22949]
## Description 
Error messages/copy needs to be updated for production in the Android VPN Flow. Looks very generic and unpolished.

Scenario 1: User selects one of the subscription plans in the purchase modal and then clicks outside or cancels.
Scenario 2: User taps the cancel CTA in the connection request modal after installing VPN profile.
Scenario 3: Purchase fails when attempting to subscribe.
Scenario 4: The user encounters this error message if the current VPN subscription has expired and they are trying to enable the VPN from the menus. They are taken to the purchase VPN modal and error message is displayed.

For Scenario 4: 
1. User goes through the subscription flow, connects to VPN successfully. 
2. Subscription period has elapsed.
3. User attempts to re-enable the VPN in the app via the 3-dot menu or the settings menu.
4. User is re-directed to VPN subscription page and error is displayed.

Cancel Subscription | Cancel Connection Request | Purchase Fails | Enabling after expiration
-|-|-|-
![screenshot-1652912002675](https://user-images.githubusercontent.com/17885425/169406172-299deb00-c455-4e73-9773-bb2fc55feffe.png) | ![screenshot-1652994923600](https://user-images.githubusercontent.com/17885425/169406223-5a4d2a45-ebc3-4d4c-80d2-e5efe5a6f871.png) | ![screenshot-1652997534541](https://user-images.githubusercontent.com/17885425/169411944-fbb096b0-d2e5-4a48-9b16-832f76b1b1b7.png) | ![screenshot-1652998079479](https://user-images.githubusercontent.com/17885425/169412722-c450b429-17df-4ac8-a2fa-dcd530412afe.png)

Spec - https://docs.google.com/document/d/1TXEn25pLhNlDyaQCqTZPQ4ua9G8CxK0eBGKhfKrqn6k/edit#

## Issue reproduces how often 
Easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung GS 21, Tab S7
   - Android version: 12
   
## Brave version
1.40.x, 1.41.x

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by timchilds** [comment]
Here are my suggestions for the updated copy. @rmcfadden3 please let us know if these need edits?

Scenario 1: User selects one of the subscription plans in the purchase modal and then clicks outside or cancels.
_"Subscription purchase cancelled by user."_

Scenario 2: User taps the cancel CTA in the connection request modal after installing VPN profile.
_"VPN profile installation cancelled by user."_

Scenario 3: Purchase fails when attempting to subscribe.
_"Purchase failed. Please contact Google Play support."_ 
@deeppandya  I am assuming the purchase failure is on Google Plays end. Please correct me if I am wrong.

Scenario 4: User enabling VPN after subscription expires.
@Uni-verse unsure what the use case is here. Can you please add more details?

**Comment by Uni-verse** [comment]
> 

@timchilds Updated the scenario description for clarity

**Comment by timchilds** [comment]
Thanks @Uni-verse. I updated my previous comment with the Scenario 4 copy.

**Comment by rmcfadden3** [comment]
@timchilds — I'd suggest we avoid the passive voice and, if we want, personalize to second person. Also, if we go with second person I'd suggest avoiding the word "cancel" as it implies an active action, rather than a passive one (or one that was even a mistake). But moot point if we don't do second-person.

Your scenarios 3 & 4 lgtm, but I've adjusted 1 & 2:

Scenario 1: "You've quit your subscription purchase." (or  "Subscription purchase canceled")
Scenario 2: "You've stopped the installation of the VPN profile." (or "VPN profile installation canceled")
Scenario 3: "Purchase failed. Please contact Google Play support."
Scenario 4: "Your subscription has expired. You can subscribe again at any time."

Also: Is there a link for Google Play support?

**Comment by timchilds** [comment]
@rmcfadden3 those edits look good to me. I prefer the second options for scenario 1 and 2.

Re: scenario 3, there's this Google Play support page: https://support.google.com/googleplay/answer/1267137?hl=en&co=GENIE.Platform=Android

Let's wait for @deeppandya to confirm the purchase failure is indeed on Google Plays end.

**Comment by deeppandya** [comment]
> Here are my suggestions for the updated copy. @rmcfadden3 please let us know if these need edits?
> 
> Scenario 1: User selects one of the subscription plans in the purchase modal and then clicks outside or cancels. _"Subscription purchase cancelled by user."_
> 
> Scenario 2: User taps the cancel CTA in the connection request modal after installing VPN profile. _"VPN profile installation cancelled by user."_
> 
> Scenario 3: Purchase fails when attempting to subscribe. _"Purchase failed. Please contact Google Play support."_ @deeppandya I am assuming the purchase failure is on Google Plays end. Please correct me if I am wrong.
> 
> Scenario 4: The user encounters this error message if the current subscription has expired and they are trying to enable the VPN from the menus. They are taken to the purchase VPN modal and error message is displayed. _"Your subscription has expired. You can subscribe again at any time."_

@timchilds purchase failure is from Google play when for some reason purchase failed from server

**Comment by kjozwiak** [comment]
The above will require `1.39.110` or higher for `1.39.x` verification 👍

**Comment by Uni-verse** [comment]
Verification in progress on `Samsung Galaxy S21` & `Galaxy Tab S7` using version `1.39.111, Chromium 102.0.5005.61`

Scenario 1:
<details>

Before | After
-|-


</details> 

Scenario 2: 

Scenario 3: 

Scenario 4:
