### ISSUE TITLE
Selecting Localhost sets both Ethereum and Solana Localhost

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#22959]
## Description 

Selecting Localhost sets both Ethereum and Solana Localhost

## Steps to Reproduce

   1. Create wallet
   2. Select `Localhost` under `Ethereum` from network dropdown
   3. Widget/Panel shows `Solana Localhost` as localhost of both networks are selected

## Actual result:

https://user-images.githubusercontent.com/17010094/169513984-318a38f7-153f-4e7f-90f4-9ec3f72dedc9.mov

## Expected result:
Should only set the selected network localhost

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.39.109 Chromium: 102.0.5005.50 (Official Build) (64-bit)
-- | --
Revision | `f6e2cf8f59ec714bdcff8499991d55898875f287-refs/branch-heads/5005@{#648}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel @jamesmudgett

**Comment by Uni-verse** [comment]
Verification `PASSED` using

```
Brave	1.41.91 Chromium: 103.0.5060.114 (Official Build) beta (64-bit) 
Revision	a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS	Windows 11 Version 21H2 (Build 22000.318)
```

Followed STR in https://github.com/brave/brave-browser/issues/22959#issue-1242985507

- Confirmed localhost will be set for the selected network and shown properly in hover state.
- Confirmed localhost correctly displayed in `Buy` and `Send` Tabs

Example | Example
-|-
![Screen Shot 2022-07-08 at 12 41 26 PM](https://user-images.githubusercontent.com/17885425/178060215-5ecdc5c5-1de6-4a8b-9e31-554159c3e75a.png) | ![Screen Shot 2022-07-08 at 12 41 39 PM](https://user-images.githubusercontent.com/17885425/178060218-ddebb5c5-fa0e-48c9-b64a-217ee1a9e4f2.png)

**Comment by Uni-verse** [comment]
Verification `PASSED` using

```
Brave	1.41.91 Chromium: 103.0.5060.114 (Official Build) beta (64-bit) 
Revision	a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS	Linux (Debian version 11)
```

Followed STR in https://github.com/brave/brave-browser/issues/22959#issue-1242985507

- Confirmed localhost will be set for the selected network and shown properly in hover state.
- Confirmed localhost correctly displayed in `Buy` and `Send` Tabs

Example | Example
-|-
![Screen Shot 2022-07-08 at 2 04 33 PM](https://user-images.githubusercontent.com/17885425/178070393-87c1a95d-0ef0-4cb3-b312-ea33ee99ca7b.png) | ![Screen Shot 2022-07-08 at 2 05 19 PM](https://user-images.githubusercontent.com/17885425/178070396-e04f36a7-d123-4676-884b-341fc38e5ccd.png)
