### ISSUE TITLE
VPN Support page url needs to be updated on Android 

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#22950]
## Description 
Launching the VPN Support page via settings > Brave Firewall + VPN > VPN Support will load brave support page referencing VPN setup on iOS. 

Current URL: https://support.brave.com/hc/en-us/articles/360045045952

![screenshot-1652913502437](https://user-images.githubusercontent.com/17885425/169409687-979a921f-8271-4710-a67e-3302809606ad.png)

## Issue reproduces how often 
Easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung GS 21, Tab S7
   - Android version: 12
   
## Brave version
1.40.x, 1.41.x

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by diracdeltas** [comment]
cc @Brave-Matt

**Comment by deeppandya** [comment]
@mattmcalister do we have android vpn specific support page ? the page we redirect to is mainly for IOS VPN support.
CC @anthonypkeane @bsclifton

**Comment by bsclifton** [comment]
@deeppandya there's an Android page up now (no idea when it went live):
https://support.brave.com/hc/en-us/articles/4410838268429-How-do-I-use-the-Built-in-VPN-Firewall-Android-

This should be a quick one to knock out 😄👍

**Comment by kjozwiak** [comment]
The above requires `1.56.11` or higher for `1.56.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version: 

```
Brave	1.56.13 Chromium: 115.0.5790.136 (Official Build) (64-bit) 
Revision	85c2a5a25b8821a0e33a48fae903d4e80c8067cd-refs/branch-heads/5790_85@{#6}
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

- Ensured that VPN support link will load the Android version of VPN on mobile 

<img width="500" alt="0" src="https://github.com/brave/brave-browser/assets/17885425/f59321a2-087a-4b75-8ac8-672742c799d1">
