### ISSUE TITLE
Setting a test network and disabling it causes the network dropdown to not fallback to default network

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#22953]
## Description 

Setting a test network and disabling it causes the network dropdown to not fallback to default network

## Steps to Reproduce

   1. Enable test networks to be shown
   2. Select any of the test network
   3. Go back to settings and disable show test networks
   4. Reload the wallet page, test network is removed and doesn't fall back to default network

## Actual result:

https://user-images.githubusercontent.com/17010094/169454015-40c35e38-4b36-4637-b734-24f09eb1ce0a.mov

## Expected result:
Should fall back to default network or the mainnet for the selected test network

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html><head></head>
<body>

Brave | 1.41.4 Chromium: 102.0.5005.50 (Official Build) nightly (64-bit)
-- | --
Revision | `f6e2cf8f59ec714bdcff8499991d55898875f287-refs/branch-heads/5005@{#648}`
OS | Windows 11 Version 22H2 (Build 22621.1)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel

**Comment by Douglashdaniel** [comment]
This should be handled on the core-end!

**Comment by Douglashdaniel** [comment]
The `Show Test networks` pref was removed a while back, closing as `Invalid`
