### ISSUE TITLE
Brave Action Item sizing

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#2295]
Icons change from 16px to 18px

Notification bubble not cover lion eye

Spec forthcoming in comment below...

## Test plan
- Shields and Rewards icons look pixel perfect at new 18px size on 1x, 2x and 3x screens
- Badge position is as indicated below, always anchored 12px from right edge of hover background on button. Same with 1, 2 or 3 character length strings.
- Badge colors are as indicated below.
- With 3 character length string in badge, badge extends right past edge of hover background of button

**Comment by rossmoody** [comment]
![sizing and spacing](https://user-images.githubusercontent.com/29072694/49324755-43fcd300-f4e9-11e8-9fa5-0d3166aa1735.png)

**Comment by davidtemkin** [comment]
Let's bump the priority of this issue, make it a requirement for 1.0 at the latest @rebron @bradleyrichter

**Comment by petemill** [comment]
@rossmoody please can we add some detail as to what the horizontal anchor point of the notification bubbles should be for both shields and rewards items? Then we'll know how they both expand / contract with different width text.

**Comment by rossmoody** [comment]
![notificationspec](https://user-images.githubusercontent.com/29072694/49398209-7cbbc880-f6f2-11e8-930c-43aaedc5fa69.png)

**Comment by petemill** [comment]
@rossmoody this is useful but what I'm looking for is where in the bounding box that bubble is positioned when it changes width. i.e. is it fixed to the right position (which for shields is about -2px to the right)? And for Rewards.

**Comment by petemill** [comment]
The answer is that the shields notification bubble is left-aligned to the blue dashed line below, which is Xpx from the left of the image.

![image](https://user-images.githubusercontent.com/741836/50600000-a4e04800-0ea7-11e9-849e-46f2cfb106fc.png)

@rossmoody are we going with the shields icon displaying '0' for no blocked items? If so, please can we create a separate issue as that needs to be done within the shields extension.

**Comment by rossmoody** [comment]
Thanks for following up here, forgot to circle back and elaborate. 

Filed an issue for the updated shields number behavior: https://github.com/brave/brave-browser/issues/2793

**Comment by petemill** [comment]
FYI @rossmoody this other issue is stopping me achieving the above spec perfectly https://github.com/brave/brave-browser/issues/2807
For now I could remove the 2px gap between the buttons? Since multiple buttons won't have the hover affect at the same time.

**Comment by srirambv** [comment]
@petemill @rossmoody On Linux with 100% DPI setting the icons look a little pixelated/blurry and the lion icon looks a little soft edged. 

at 100% DPI
 ![screenshot from 2019-02-15 12-47-49](https://user-images.githubusercontent.com/17010094/52840738-291d2080-3120-11e9-9bca-550e204ecaac.png)
at 200% DPI 
![screenshot from 2019-02-15 12-47-29](https://user-images.githubusercontent.com/17010094/52840739-291d2080-3120-11e9-8a08-87b74d56c2db.png)

Device display setting is as follows
![image](https://user-images.githubusercontent.com/17010094/52840724-1a366e00-3120-11e9-9f3c-04b5fb5b2b5a.png)

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.60.44 Chromium: 72.0.3626.109 (Official Build) (64-bit)
-- | --
Revision | fae8db7ab9280fa6704a59980263c804f809ebd5-refs/branch-heads/3626@{#857}
OS | Windows 7

Used test plan from the description and the comments.

Logged https://github.com/brave/brave-browser/issues/3434

**Comment by kjozwiak** [comment]
@srirambv will file a new issue regarding the icons still appearing blurry while using 100% DPI under linux as outlined https://github.com/brave/brave-browser/issues/2295#issuecomment-463934760.

@srirambv once created, mention the new issue in this issue 👍
