### ISSUE TITLE
Unable to re-select a native asset

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#22952]
## Description 
Unable to re-select a `Native Asset` until you save and reopen the `Edit Visible Assets` modal.

https://user-images.githubusercontent.com/40611140/169424224-c99fa76d-72d2-4fe5-a2c4-d46ba44cec05.mov

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.39.117 Chromium: 102.0.5005.78 (Official Build) (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>8888ee7a24e2c36661ddb9536c35b7d4852a3a98-refs/branch-heads/4951@{#1230}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22621.1)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td>
      </td>
      <td colspan=3>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/13399>brave/brave-core#13399</a></li>
         <li>Verified able to check/uncheck native token and save</li>
         <li>Verified uncheck testnet token doesn't remove native token as well</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/171881458-02059c8d-d2db-43bb-b9e2-7f15a0c6f4c8.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/171879198-ed07e498-77d7-4a54-a509-08d8c24d2b30.mov>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/171878516-6b5189c7-4902-4c29-8938-3806fdf81583.mov>
      </td>
   </tr>
</table>
