### ISSUE TITLE
Create Solana wallet prompt is shown when (re)creating a new wallet profile

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#22957]
## Description 

Create Solana wallet prompt is shown when (re)creating a new wallet profile

## (Possible) Steps to Reproduce

   1. Create a new browser profile and create wallet account
   2. Select Solana from network to trigger create account message 
   3. Select Yes and create Solana account
   4. _Change network to `Solana Devnet` (Not mandatory but found doing this causes the issue to repro easily)_
   5. Reset wallet
   6. Create a new wallet account
   7. Widget already has the create Solana account message 
   8. Click on `No` on the widget doesn't dismiss the message
   9. Open Panel and click `No`, message is dismissed 

## Actual result:

https://user-images.githubusercontent.com/17010094/169486129-b7824b16-f060-4dd0-8f91-333c650041a4.mp4

## Expected result:
Should only show the message when user selects Solana network for the first time

## Reproduces how often: 

Easy if you are lucky

## Brave version (brave://version info)

Brave | 1.39.109 Chromium: 102.0.5005.50 (Official Build) (64-bit)
-- | --
Revision | `f6e2cf8f59ec714bdcff8499991d55898875f287-refs/branch-heads/5005@{#648}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel @jamesmudgett

**Comment by Douglashdaniel** [comment]
Is no longer an issue with `Wallet V2` updates, closing as `Invalid`
