### ISSUE TITLE
Update Brave Action Icon states and behavior

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#2296]
Spec forthcoming...

**Comment by rossmoody** [comment]
The below spec is for updated icon behavior in relation to System, Private and On/Off states in regards to Shields and Rewards elements.

![brave action bar behavior](https://user-images.githubusercontent.com/29072694/49467450-5d3aa380-f7b7-11e8-9aec-ccce9916b0e8.png)
![brave action bar behavior icons](https://user-images.githubusercontent.com/29072694/49467451-5dd33a00-f7b7-11e8-8379-67a7a2fa9641.png)

**Comment by rossmoody** [comment]
Getting ducks in a row, reviewing as a larger team and will circle back with more concise direction on Brave Action item behavior/styling.
