### ISSUE TITLE
View on Block explorer for Solana retains the previous selected network settings

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#22966]
## Description 

View on Block explorer for Solana retains the previous selected network settings

## Steps to Reproduce

   1. Create a Solana Account
   2. Switch to Solana Testnet and perform a transaction
   3. Select `View on block explorer`, opens transaction in Testnet explorer(`?cluster=testnet`)
   4. Switch to `Solana Mainnet Beta` and perform a transaction
   5. Select `View on block explorer` from transaction list, still opens transaction in Testnet explorer (`?cluster=testnet`)

## Actual result:

https://user-images.githubusercontent.com/17010094/169550447-ac909f75-d850-4c7c-99a1-456442df6c34.mov

## Expected result:
Should link to the correct block explorer

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.39.109 Chromium: 102.0.5005.50 (Official Build) (64-bit)
-- | --
Revision | `f6e2cf8f59ec714bdcff8499991d55898875f287-refs/branch-heads/5005@{#648}`
OS | Windows 11 Version 22H2 (Build 22621.1)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NO
- Can you reproduce this issue with the beta channel? Probably yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel @yrliou

**Comment by josheleonard** [comment]
Could not replicate. @srirambv can you confirm that this issue is no longer valid?

**Comment by srirambv** [comment]
Verified on current Release 1.60.110 and issue is no longer reproducible. Closing as stale/invalid
