### ISSUE TITLE
Implement account discovery of Solana Accounts when restoring wallet from seed

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#22969]
Similar to #18104, we should consider restoring Solana Accounts if there has been any transactions done. 

cc: @jamesmudgett @darkdh

**Comment by darkdh** [comment]
use https://docs.solana.com/developing/clients/jsonrpc-api#gettransactioncount

**Comment by jamesmudgett** [comment]
https://github.com/brave/brave-browser/issues/23061 related

**Comment by yrliou** [comment]
Seems like Solana getTransactionCount is not what we want, we can use https://docs.solana.com/api/http#getsignaturesforaddress instead.

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/28002#issuecomment-1596666092
