### ISSUE TITLE
BAT for tip withdrawn twice if internet connection lost after tipping

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#2297]
## Description 
Found while testing https://github.com/brave/brave-browser/issues/1483

If you tip a site and immediately lose internet connection, when you come back online you'll see that your wallet balance has gone down by the amount of the tip, but no tip is recorded. If you wait a couple minutes, you see your wallet balance go down again, and your tip is recorded (once).

## Steps to Reproduce

   1. Fresh profile with 0.56.8.
   2. Enable Rewards, claim grant.
   3. Navigate to a site.
   4. Tip the site and immediately cut wifi/internet.
   5. Wait a few minutes.
   6. Enable wifi/internet again.

## Actual result:
When internet returns, your balance is less the tip amount (mine was 1BAT), but no tips displayed in tips panel or Rewards Summary. If you wait a couple more minutes --> wallet balance goes down again (the amount of the tip) and now a single tip is displayed in Tips panel/Rewards Summary.

![screen shot 2018-11-29 at 4 49 01 pm](https://user-images.githubusercontent.com/28145373/49254939-a1652700-f3f8-11e8-8664-3621e8c7c0cd.png)

![screen shot 2018-11-29 at 5 02 52 pm](https://user-images.githubusercontent.com/28145373/49254943-a3c78100-f3f8-11e8-96c0-e58b9ebeb293.png)

## Expected result:
Tip should only be deducted from balance once, not twice.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.57.8 Chromium: 71.0.3578.53 (Official Build) beta(64-bit)
-- | --
Revision | 599fb72e740eab9d10609f1ed28a2ad669f82c1a-refs/branch-heads/3578@{#669}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
cc @brave/legacy_qa to check other platforms

**Comment by GeetaSarvadnya** [comment]
Issue is reproducible on Win also - `0.57.8`. Tip amount was 10 BAT for my test

![image](https://user-images.githubusercontent.com/38657976/49270669-67dffa80-f490-11e8-81d9-8c506cd331b4.png)

**Comment by GeetaSarvadnya** [comment]
Issue is reproducible on Linux as well - `0.57.8`. Tip amount was 1 BAT for this step

![image](https://user-images.githubusercontent.com/38657976/49272447-98776280-f497-11e8-944f-c1595357992a.png)

**Comment by kjozwiak** [comment]
Good find @LaurenWags 👍 IMO, this should be a `P2` at the very least even though it's a corner case. We should never be dinging users twice for a single tip. This will become a lot more noticeable when users start using larger tip amounts.

**Comment by LaurenWags** [comment]
Encountered again while testing https://github.com/brave/brave-browser/issues/3052 which changes retry logic for tips. Here's what I'm seeing:
* Fresh profile with 0.60.28 (used staging env).
* Enable Rewards, claim grant.
* Navigate to a site.
* Tip the site and immediately cut wifi/internet.
* Wait a few minutes. Get notification about Tip unable to go thru.
* Enable wifi/internet again.
* Balance goes down by the amount of the tip, but no tip is recorded. It is expected that no tip is recorded because you received the notification about the tip is unable to go thru. However, my balance should not have gone down at all.

**Comment by ryanml** [comment]
@LaurenWags are you able to see if you can reproduce on latest master and nightly and list your STR? I have had a hard time trying to repro this one, and last I checked on was 0.64. (Note I also tried issuing a keyboard interrupt in addition to just cutting my network connection, same results). Thank you!

**Comment by LaurenWags** [comment]
@ryanml I reproduced on latest nightly available on macOS:

Brave | 0.65.28 Chromium: 74.0.3729.61 (Official Build) nightly(64-bit)
-- | --
Revision | 5df2c8936783bd7575987e45d72a92fcf528496b-refs/branch-heads/3729@{#645}
OS | Mac OS X

1. Fresh profile with 0.65.28 (used staging env - launched with `--rewards=staging=true`)
2. Enable Rewards, claim grant.
3. Navigate to a site (used ddg as it's verified on staging)
4. Tip the site and immediately cut wifi/internet. I did this by clicking on the wifi symbol on my top menu bar on macOS and selecting 'Turn WiFi Off'.
5. Wait a few minutes. Note, this time I did *not* get notification about how Tip was unable to go thru.
6. Enable wifi/internet again.
7. Balance goes down by the amount of the tip, but no tip is recorded on wallet summary or in Tips table. 

Is there any other info I can provide? Maybe launch with additional parameters from terminal?

**Comment by NejcZdovc** [comment]
@LaurenWags so it didn't tip twice now, the only problem now was that transaction was not recorded?

**Comment by LaurenWags** [comment]
Tried it again @NejcZdovc and this time the tip did happen twice (but was only recorded once, so could be something to do with timing and I didn't wait long enough last time I tried.

**Comment by NejcZdovc** [comment]
closing as we changed contribution flow completely. Please reopen if still a problem
