### ISSUE TITLE
Incorrect error dialog used when credentials fail

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#22972]
## Description 

Incorrect error dialog used when credentials fail

## Steps to Reproduce

1. Complete the steps under `Brave Premium login` > `Purchasing VPN with a new account` from https://github.com/brave/brave-browser/issues/15804, making sure to specify the current month and year for the credit card's expiration date
2. confirm you can connect to your new `Brave VPN` account
3. shut down Brave
4. open `Date & Time` in `System Preferences` and advance the OS date to the `1st of next month`
5. relaunch Brave
6. connect to `Brave VPN`

## Actual result:

<img width="1312" alt="Screen Shot 2022-06-01 at 11 32 02 AM" src="https://user-images.githubusercontent.com/387249/169591357-8234bf4c-166b-4662-ac48-4afa0699454d.png">

## Expected result:
From Figma:

![Screen Shot 2022-05-20 at 11 05 52 AM](https://user-images.githubusercontent.com/387249/169591172-5d6f1202-3fcf-43dc-a06c-cd9856b9bf63.png)

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.41.5 Chromium: 102.0.5005.50 (Official Build) nightly (x86_64)
-- | --
Revision | f6e2cf8f59ec714bdcff8499991d55898875f287-refs/branch-heads/5005@{#648}
OS | macOS Version 11.6.6 (Build 20G624)

@aguscruiz @bsclifton @simonhong @brave/qa-team

**Comment by spylogsster** [comment]
@stephendonner cannot reproduce, could you recheck pls?

**Comment by stephendonner** [comment]
> @stephendonner cannot reproduce, could you recheck pls?

Can still reproduce using 

Brave | 1.42.13 Chromium: 103.0.5060.53 (Official Build) nightly (x86_64)
-- | --
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | macOS Version 12.5 (Build 21G5046c)

<img width="1680" alt="Screen Shot 2022-07-01 at 4 51 06 PM" src="https://user-images.githubusercontent.com/387249/174915025-93061155-22c9-4588-a7bc-f86859ab2d95.png">

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.46.68 Chromium: 107.0.5304.36 (Official Build) nightly (x86_64)
-- | --
Revision | 2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}
OS | macOS Version 13.0 (Build 22A379)

Followed my original steps to reproduce from https://github.com/brave/brave-browser/issues/22972#issue-1243494819.

#### Confirmed the correct payment-error dialog is triggered in this specific case, with the correct wording.

`10/18/2022` | `11/1/2022` | `Edit payment method` dialog
---------|---------|---------
<img width="1260" alt="Screenshot 2022-10-18 at 9 10 54 PM" src="https://user-images.githubusercontent.com/387249/196596483-a9112f99-e171-458b-8ffc-9798f6d99f83.png"> | <img width="1262" alt="Screenshot 2022-11-01 at 9 11 40 PM" src="https://user-images.githubusercontent.com/387249/196596557-2923b530-7a34-40f7-8005-ef4ec1abf08a.png"> | <img width="1082" alt="Screenshot 2022-11-01 at 9 12 48 PM" src="https://user-images.githubusercontent.com/387249/196596559-657fad8f-2cd3-45b5-a9d4-14008e2abc0c.png">

**Comment by stephendonner** [comment]
> @stephendonner @MadhaviSeelam I have followed the STR from the description. When I advance the system date to 1st of next month (1st Dec 2022) I am not getting `Edit payment menthod` popup when I tap on the VPN icon in the URL bar. VPN is still in the connected state.
> 
> **`23rd Nov`**	**`1st Dec`**	**`1st Dec`**
> ![image](https://user-images.githubusercontent.com/38657976/203564487-b2af249f-6da8-4a6f-b941-28361752e82b.png)	![image (1)](https://user-images.githubusercontent.com/38657976/203564539-0945055f-c683-415b-bb0e-9ad2f0dcc922.png)	![image](https://user-images.githubusercontent.com/38657976/203565132-6f1dea1f-51eb-4d37-8440-67f81893ee90.png)

Same.  Using 

Brave | 1.46.126 Chromium: 108.0.5359.48 (Official Build) beta (64-bit)
-- | --
Revision | 18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}
OS | Windows 10 Version 22H2 (Build 19045.2311)

I follow the same steps, and after advancing to the 1st of next month (from today's correct issue date of 11-23-2022, and relaunch Brave, `BraveVPN` is still able to connect without throwing up the `Edit your payment` dialog we see on macOS.

![image](https://user-images.githubusercontent.com/387249/203615637-cbdd8539-1bb1-4326-8be0-d88d9f4f40e0.png)

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
Brave | 1.46.131 Chromium: 108.0.5359.71 (Official Build) (64-bit)
-- | --
Revision | 1e0e3868ee06e91ad636a874420e3ca3ae3756ac-refs/branch-heads/5359@{#1016}
OS | Windows 10 Version 21H2 (Build 19044.2251)

```

**_Nov 30th_**

Example | Example
---------|----------
![image](https://user-images.githubusercontent.com/38657976/204873599-a7e672da-9ba2-4dd1-955b-71fc8b458e36.png) | ![image](https://user-images.githubusercontent.com/38657976/204873333-e73a8514-c9ff-47f5-815e-3523c258d153.png)

**_Nov 30th_**

Example | Example
---------|----------
