### ISSUE TITLE
Bookmarks are not hidden in a new tab when "show bookmarks" is disabled

### ISSUE THREAD

**Issue by cdes5804** [brave/brave-browser#22987]
## Description 
Bookmarks bar shows up even when "show bookmarks" is disabled in a new tab. 

## Steps to Reproduce

   1.  Disable "show bookmarks"
   2. Open a new tab

## Actual result:

Bookmarks are displayed.

## Expected result:
Bookmarks should always be hidden when "show bookmarks" is disabled.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

1.38.119 Chromium: 101.0.4951.67 (Official Build) (x86_64) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

https://user-images.githubusercontent.com/48202567/169638064-282052ca-e986-41b1-891e-c1aca2c918bf.mp4

**Comment by rebron** [comment]
Hi @cdes5804 There's a setting brave://settings/appearance `Always show bookmarks on new tab page` Disable that and bookmarks bar on the new tab page should go away.
