### ISSUE TITLE
Use `cxx` for adblock-rust FFI

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#22985]
The FFI for adblock-rust is our oldest Rust FFI, and still uses handwritten bindings to go from Rust through C to C++. We've since trialled `cxx` for automatic FFI generation with great results. We should port adblock-rust's bindings to `cxx` as well.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.58.84 Chromium: 116.0.5845.82 (Official Build) beta (x86_64)
-- | --
Revision | b1eb6c7b59795a7a26ae5f6aba87cca8ede0ede2
OS | macOS Version 11.7.9 (Build 20G1426)
