### ISSUE TITLE
Incorrect response value for the metrics Brave.Today.WeeklyMaxCardViewsCount when various numbers of cards are viewed

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#22997]
## Description 

Incorrect response value for the metrics Brave.Today.WeeklyMaxCardViewsCount when 9 cards are viewed, please note incorrect responses are shown when 11, 21, and 40 cards are viewed. Logged a common issue, I hope a fix for one response will fix the issue for all the responses.

## Steps to reproduce 

   1. Clean profile 1.39.x
   2. Open an NTP and enable brave news
   3. View 9 brave news card
   4. Open brave://local-state
   5. Confirmed that the metrics `Brave.Today.WeeklyMaxCardViewsCount` response value is `4` instead of `2`
   

## Actual result 
Incorrect response value for the metrics Brave.Today.WeeklyMaxCardViewsCount when 9 cards are viewed

## Expected result
The response value for the metrics `Brave.Today.WeeklyMaxCardViewsCount` should be `2` when 9 cards are viewed

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung Galaxy A52s version 11
   - Android version: 11
   
## Brave version

Bravearmx64.apk_1.39.109
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/qa-team @DJAndries @mattmcalister

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress on `Samsung Galaxy Tab A7` running `Bravemonoarmx64.apk_1.41.50`

**Comment by Uni-verse** [comment]
Verification in progress
