### ISSUE TITLE
Switches to Tor Window Automatically

### ISSUE THREAD

**Issue by sagarkrp** [brave/brave-browser#22990]
## Description 

 When clicking on some specific links, it opens directly in Tor Window. (It also opens a normal window)
 I have seen 2 places where this happens
 1. Setting -> Brave Version ( To get to release notes)
 2. Proton mail sign in
 3. Toggle on/off brave shields in the release notes page of brave

## Steps to Reproduce

   1.  Open Brave Settings , click on the brave version number with Chromium details in About brave 
   2.  Sign in to Proton mail
   3. Toggle brave shield on/off on the release notes page of brave

## Actual result:

It opens a tor window and a normal window

https://user-images.githubusercontent.com/42873729/169661489-be601033-ddff-4753-9686-6ffde9c484de.mp4

## Expected result:

Tor window should not be opened

## Reproduces how often: 

Easily reproduced. Happens every time

## Brave version (brave://version info)

<html>
<body>

Brave | 1.38.119 Chromium: 101.0.4951.67 (Official Build) (64-bit)
-- | --
Revision | 8888ee7a24e2c36661ddb9536c35b7d4852a3a98-refs/branch-heads/4951@{#1230}
OS | Windows 11 Version 21H2 (Build 22000.675)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release?
 Yes
- Can you reproduce this issue with the beta channel? 
Not sure
- Can you reproduce this issue with the nightly channel? 
- Not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- No
- Does the issue resolve itself when disabling Brave Rewards? 
- No idea
- Is the issue reproducible on the latest version of Chrome? 
- No idea

**Comment by sagarkrp** [comment]
The video above is not playing properly in browser, download to view the actual behaviour

**Comment by fmarier** [comment]
Do you have this setting enabled by any chance in `brave://settings/extensions`?
![Capture d’écran du 2022-05-22 17-31-05](https://user-images.githubusercontent.com/167821/169723231-baa56bd8-530e-4825-91fa-1c5e5425b08d.png)

**Comment by sagarkrp** [comment]
> Do you have this setting enabled by any chance in `brave://settings/extensions`?
> ![Capture d’écran du 2022-05-22 17-31-05](https://user-images.githubusercontent.com/167821/169723231-baa56bd8-530e-4825-91fa-1c5e5425b08d.png)
> 

Hi, yes this was turned on. 
Closing this issue now. Than you.
