### ISSUE TITLE
Unable to apply patches on brave@1.41.6

### ISSUE THREAD

**Issue by bobajeff** [brave/brave-browser#22992]
## Description 
I've been trying to build brave from source for a few weeks. I'm stuck on the `npm run init` step. I've modified the arguments in the _"gclient sync"_ step _(as discussed in this issue  #6444 )_ to be ` gclient sync --nohooks --no-history --shallow --jobs=16 --revision src@refs/tags/102.0.5005.61 --force --reset --upstream`

However on the _"applying patches"_ step it fails. I've tried running `git fetch origin`, `git pull` and even deleting brave-core and re-downloading via the `npm run init` command but no dice.

## Actual result:
```
36 failed patches:
...
-------------------------------
Done applying patches.
Exiting as not all patches were successful!
null
null
```

full log attached:
[npm_run_init_output.log](https://github.com/brave/brave-browser/files/8748059/npm_run_init_output.log)

## Brave version (brave://version info)
1.41.6

**Comment by message** [comment]
Same for me

**Comment by yuppiestechdev** [comment]
Any luck?

**Comment by bobajeff** [comment]
No. I've long given up on compiling brave. I think they want you to use a build server. Chromium I've had luck with though. However you still have the issue of long build and linking times. Building the `content-shell` target was probably the best I could do as far as playing around and experimenting with the code base. However, even that wasn't satisfactory to me so I'm no longer messing with chromium based projects.

**Comment by NaaeemMalik** [comment]
@message @kim0 @bsclifton @pes10k 
this should be possible

**Comment by pes10k** [comment]
im not sure im the right person for this. @bridiver may also have ideas though

**Comment by bridiver** [comment]
`--shallow` checkouts don't work unfortunately. There's a chromium step that looks back at the previous commit for version info (I forget the details, maybe @mihaiplesa remembers) and it fails because there is no previous commit. We tried this as a way to speed up our own build process, but  ended up abandoning it. Unfortunately atm you need to wait through the chromium gclient sync for the full repo which I know can take a very long time, but after the initial sync it's much faster.

**Comment by bridiver** [comment]
It is definitely possible to build without a build server, we did it all the time before we got goma running. It will build on a laptop, but a clean build might take all day. On my mac pro (not macbook pro) it takes about 40 minutes.

**Comment by bsclifton** [comment]
This is correct - since the top level question is about behavior with `--no-history`, I'll close this issue as it's unsupported
