### ISSUE TITLE
Default flags configuration file

### ISSUE THREAD

**Issue by rauldipeas** [brave/brave-browser#2300]
On Linux, Chromium has a file /etc/chromium-browser/default, where i can set some flags, Brave has something like that?

**Comment by maximbaz** [comment]
On Arch Linux we use [the following `chromium-launcher`](https://github.com/foutrelis/chromium-launcher), which knows how to read `$XDG_CONFIG_HOME/chromium-flags.conf`. Perhaps this is something that can be used for Brave as well?

**Comment by maximbaz** [comment]
This has been beautifully solved in the Arch Linux package for Brave using the following wrapper:

```
#!/bin/sh

XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
BRAVE_USER_FLAGS_FILE="$XDG_CONFIG_HOME/brave-flags.conf"
if [[ -f $BRAVE_USER_FLAGS_FILE ]]; then
    USER_FLAGS="$(cat $BRAVE_USER_FLAGS_FILE)"
fi

/usr/bin/brave $@ $USER_FLAGS
```

**Comment by bsclifton** [comment]
@rauldipeas you can try creating that file (`/etc/chromium-browser/default`) or also trying to create `/etc/brave-browser/default`. It should work, if Chromium supports it

I've used the solution @maximbaz shared in the past personally

**Comment by bsclifton** [comment]
Closing as I think the question is answered? Please re-open or just post again if the above doesn't work and we can help from there 😄

**Comment by r3pek** [comment]
@bsclifton doesn't work :) Maybe just implement it on the /usr/bin script provided by brave?

**Comment by astralblue** [comment]
For those using Ubuntu (or any Linux distro using dpkg), I use this script (a variant of https://github.com/brave/brave-browser/issues/2300#issuecomment-504907440) to wrap and replace the original wrapper script installed by the `brave-browser` package (`/usr/bin/brave-browser-stable`).  This way, desktop entries (used when launched from Dock) that directly reference `/usr/bin/brave-browser-stable` continue to work with `~/.config/brave-flags.conf`.

Steps:

1. Divert the original wrapper script:
   ```sh
   sudo dpkg-divert --add --rename --divert /usr/bin/brave-browser-stable.original /usr/bin/brave-browser-stable
   ```
2. Install the following wrapper script into `/usr/bin/brave-browser-stable`:
   ```sh
   #!/bin/sh
   : ${XDG_CONFIG_HOME="${HOME}/.config"}
   unset -v flags_conf
   flags_conf="${XDG_CONFIG_HOME}/brave-flags.conf"
   if [ -f "${flags_conf}" ]
   then
           unset -v flags
           flags="$(sed 's/#.*//' < "${flags_conf}")"
           set -- ${flags} "$@"
   fi
   /usr/bin/brave-browser-stable.original "$@"
   ```
3. Ensure the script ownership/mode:
   ```sh
   sudo chown --reference=/usr/bin/brave-browser-stable.original /usr/bin/brave-browser-stable
   sudo chmod --reference=/usr/bin/brave-browser-stable.original /usr/bin/brave-browser-stable
   ```
