### ISSUE TITLE
Suggest using Lingvanex's translation API 

### ISSUE THREAD

**Issue by tachibana-shin** [brave/brave-browser#23000]
Hi,

Brave doesn't have a website translator which is the only reason I can't switch from Chrome -> Brave (Google Translate Extension didn't work for me)

I don't know why translate.brave.com isn't ready yet but i suggest in its development Brave will use Lingvanex to do translation API like Vivaldi did

Thank for read

**Comment by CavaleriOmar** [comment]
Or like FIrefox-Translator (totally offline)?

**Comment by diracdeltas** [comment]
this is already being worked on: https://github.com/brave/go-translate/pull/12

**Comment by rebron** [comment]
Closing as duplicate of https://github.com/brave/go-translate/pull/12 and https://github.com/brave/brave-browser/issues/23538
