### ISSUE TITLE
Expiry date should specify if its for trial or for subscription

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23004]
## Description 
Expiry date should specify if its for trial or for subscription

## Steps to reproduce 

   1. Purchase a monthly subscription
   2. Go to VPN Settings
   3. Shows Expiry in 7 days which is the trial expiry not the actual subscription expiry

## Actual result 
<img width=500 src=https://user-images.githubusercontent.com/17010094/169855100-be5652f7-cf60-4951-a7dc-20ed1d989100.png>

## Expected result
Specify the expiry is for Trial or subcsription

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? N/A
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.39.111

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @deeppandya @Uni-verse @kjozwiak

**Comment by kjozwiak** [comment]
Adding missing `1.41.x` milestone as this was merged into `master` via https://github.com/brave/brave-core/pull/13641 which is currently `1.41.x`.

**Comment by kjozwiak** [comment]
The above will require `1.39.120` or higher for `1.39.x` verification 👍

**Comment by Uni-verse** [comment]
Verification in Progress..
