### ISSUE TITLE
Allow user to add user resources in Brave Adblock

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#23014]
Allow user to add custom javascript to be used by Adblock Rust (such as https://github.com/pixeltris/TwitchAdSolutions/ ). Would also help with debugging and trialing of user resources.

Similar to what uBO does in their `Advanced Settings`, under the Settings Tab. 

![ubo-userresources](https://user-images.githubusercontent.com/1659004/169899291-13d3c178-ae4e-4363-9daa-6d9c2e7796b4.png)

**Comment by antonok-edm** [comment]
duplicate: https://github.com/brave/brave-browser/issues/25586
