### ISSUE TITLE
Push notifications broken in brave-core

### ISSUE THREAD

**Issue by capouch** [brave/brave-browser#2301]
## Description 
HTML5 push notifications, which were previously working, no longer function in the brave-core milieu.

## Test Plan
Specified here: https://github.com/brave/brave-core/pull/3390

## Steps to Reproduce

   1.  Go to this site: [https://serviceworke.rs/push-payload_demo.html](url)
   2. Choose "Allow" when presented with push notification popup
   3. Enter message and request notification.

## Actual result:
Popup posts, and site is registered with browser as "allowed" to send notifications.  But nothing happens when the "Request sending . . .  " button is pushed.

## Expected result:
Browser should respond with a notification popup

## Reproduces how often: 
Always.

## Brave version (brave://version info)
0.57.8

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
No.
- Is the issue reproducible on the latest version of Chrome? 
Works just fine in latest version of Chrome Beta.

### Additional Information
Subscription object is never sent to backend for processing, as verified with two sites I control which both are able to successfully send push notifications to instances of Chrome.

**Comment by rebron** [comment]
@srirambv can you investigate maybe with a different HTML 5 push notification test suite? Need more info on this one.

**Comment by Brave-Matt** [comment]
+1 from Reddit:
https://www.reddit.com/r/brave_browser/comments/a5xy25/cant_enable_facebook_notifications_in_brave/

**Comment by Brave-Matt** [comment]
May also be related to #2362

**Comment by mucanyu** [comment]
Still facing the issue. 
> Version 0.58.21 Chromium: 71.0.3578.98 (Official Build) (64-bit)

**Comment by FelschR** [comment]
Looks like the issue I mentioned in the following comment over here is related to this:
https://github.com/brave/brave-browser/issues/2143#issuecomment-473970079
The promise from `pushManager.subscribe` is stuck in status pending.

**Comment by Indjov** [comment]
Any news ? When we see the update witch will fix that notification problem?

**Comment by stefanmaric** [comment]
I'm also seeing that after allowing notifications, and maybe a refresh or something, the site settings says notifications are enabled but `registration.pushManager.getSubscription()` resolves `null`.

**Comment by ACheshirov** [comment]
Ya, this bug is very annoying. I hope they will fix it soon. I was struggling to enable Facebook notifications and now I understand why it was unsuccessful.

**Comment by snowbound** [comment]
The main reason why I went back to Chrome after trying Brave for a month back in Nov/Dec last year and now MS has entered the chromium fray

**Comment by Indjov** [comment]
@rebron , any info about that bug?

**Comment by ishinome** [comment]
@rebron I would also like to confirm that these notifications are faulty. For example site: d2jsp.org wont register push notifications with brave, but does it on chrome.

**Comment by WorldLanguages** [comment]
+1
Please work on this Brave team. I want to receive web push notifications from Twitter, Youtube, etc.

**Comment by nexxai** [comment]
@rebron Any update on this?  I love the idea of this browser but broken Facebook and Twitter notifications are kind of a deal breaker.

**Comment by snowbound** [comment]
Yup with me its YouTube notifications have to work. The reason why I was one of the people who reported this issue back in Dec 2018.  Using Firefox right now on Win10.

**Comment by rebron** [comment]
@nexxai Dependent on https://github.com/brave/brave-browser/issues/4431 Can't give you a timeline on the fix but we have this on our board to address.

**Comment by nexxai** [comment]
@rebron Can I humbly request that this have a due date set prior to Google's Declarative Web Request/Manifest v3 enabling (I believe this is expected in October)? I imagine that there will be *many* people looking to switch around that time (when ad blockers like uBlock Origin will no longer work, at least in their current form), and so the easier the transition for them, the more likely they'll be to choose Brave over something like Firefox or Opera.

**Comment by saccodd** [comment]
Hi all! is there any workaround from a developer point of view? I'd really need to enable notifications for my website also for Brave users

**Comment by bsclifton** [comment]
@saccodd unfortunately, I don't think there's a work-around. We have prioritized this and will be looking at a proper fix coming soon. I believe @jumde will be able to help with this (like he did with getting Chromecast working). Stay tuned!

**Comment by Adrymate9** [comment]
Hi guys!. I have the same problem but with the android version. I can't enable push notifications on websites. Simply a pop-up window appears asking to accept the receipt of notifications, but nothing I can do. The popup window is frozen and I can only go back then site notifications are blocked.

**Comment by szaimen** [comment]
Any update on this?

**Comment by Adrymate9** [comment]
At the moment I have not had news. I'm currently in version 1.3.1 of Brave for Android. 

Another detail is that this private problem on an LG phone with Android 7 notifications work correctly. There is no way to run my Huawei phone with Android 8.

**Comment by szaimen** [comment]
Is this going to be implemented in Android as well?

**Comment by WorldLanguages** [comment]
Finally

**Comment by jumde** [comment]
Fix for this issue enables Push notifications in Brave, but push notifications on some sites including Youtube, Twitter might not work because of an upstream issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1011244  - we are working with the chromium team to fix this. We are using issue https://github.com/brave/brave-browser/issues/2362 to track the fix. Stay tuned!

**Comment by jumde** [comment]
> Is this going to be fixed in Brave for Android as well?

cc: @anthonypkeane @SergeyZhukovsky

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.1.5 Chromium: 78.0.3904.97 (Official Build) beta (64-bit)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | macOS Version 10.13.6 (Build 17G5019)

* Verified test plan from https://github.com/brave/brave-core/pull/3390 using second site listed in the PR (first site listed was taken down).
* Verified on clean and upgrade profiles.
<img width="703" alt="Screen Shot 2019-11-20 at 1 43 20 PM" src="https://user-images.githubusercontent.com/28145373/69268312-dedc3a80-0b9c-11ea-876f-9890d3a84aea.png">
<img width="707" alt="Screen Shot 2019-11-20 at 1 43 27 PM" src="https://user-images.githubusercontent.com/28145373/69268322-e6034880-0b9c-11ea-9e20-8d30885085cf.png">

![PR3390-clean profile](https://user-images.githubusercontent.com/28145373/69268442-24006c80-0b9d-11ea-90d1-7ad9f130adde.png)


* Encountered https://github.com/brave/brave-browser/issues/2301#issuecomment-538553596 / https://github.com/brave/brave-browser/issues/7031. Intermittent push notification failures observed during testing with site from PR, however per discussion with @jumde this could be due to rate limiting to avoid bots.

**Comment by snowbound** [comment]
Sorry but in Windows10 I am still not seeing notifications in the browser
nor in Windows Action Center from YouTube when a subscribed channel goes
live. I have notications enabled for Brave in Windows10 just like I do for
Chrome and Firefox which both work wrt Windows 10 Action Center.  I am
currently using Version 1.1.5 Chromium: 78.0.3904.97 (Official Build) beta
(64-bit).  <https://brave.com/latest/>

**Comment by GeetaSarvadnya** [comment]
@snowbound https://github.com/brave/brave-browser/issues/2301#issuecomment-538553596

**Comment by capouch** [comment]
OMG it looks like we're broken again in 1.1.11!!  I'll revert ASAP and re-test, but just tested with several sites that worked OK last week.  None work now.

**Comment by neerajsrivastava** [comment]
I noticed that the "Use Google Services for Push Notifications" is turned off by default on Brave (Version 1.1.20 Chromium: 79.0.3945.74 (Official Build) (64-bit)). 

Is it mandatory to enable it for Push Notifications or there is any other way to send Push Notifications without enabling this setting? 
Push Notifications does not work if I do not enable this settings and throws below error .
We can check it on URL https://gauntface.github.io/simple-push-demo/ 

"Ooops a Problem Occurred
AbortError: Registration failed - push service not available"

**Comment by bsclifton** [comment]
@neerajsrivastava it's required to enable that setting (as far as I know), as there is a service call being made to GCM / FCM ☹️

**Comment by totomaze** [comment]
Where is the option to enable google services ?
Brave is up to date
Version 0.70.123 Chromium: 78.0.3904.97 (Official Build) (64-bit)

I can't see any option in chrome://settings/privacy

Thanks

**Comment by snowbound** [comment]
"Use Google Services for Push Messaging" in Windows Version 1.1.23 Chromium: 79.0.3945.88 (Official Build) (64-bit)

**Comment by nexxai** [comment]
When I try to enable "Use Google Services for Push Messaging" in the Advanced settings section, it prompts me to relaunch, but as soon as I do, the option is disabled again.

<img width="685" alt="Screen Shot 2020-01-01 at 9 13 55 PM" src="https://user-images.githubusercontent.com/4316564/71651538-a0798580-2cdb-11ea-9d64-b841f3e1ce32.png">

Version 1.1.23 Chromium: 79.0.3945.88 (Official Build) (64-bit) 
MacOS 10.15.2

**Comment by bsclifton** [comment]
@totomaze you're several versions behind

@nexxai I believe we fixed that bug, but the fix may not be live yet (cc: @jumde). Instead of clicking the relaunch helper button, can you try just closing Brave manually?

**Comment by totomaze** [comment]
![image](https://user-images.githubusercontent.com/3665830/71651981-9d2eda00-2d6d-11ea-81e2-72385b01d340.png)
I guess the up to date status is not working.

I downloaded the latest version from the website and I can see the option now . Thanks

**Comment by nexxai** [comment]
> @nexxai I believe we fixed that bug, but the fix may not be live yet (cc: @jumde). Instead of clicking the relaunch helper button, can you try just closing Brave manually?

This seems to have done the trick.  After just closing the browser with CMD-Q and re-opening, the toggle stayed enabled.  Thanks!

**Comment by jumde** [comment]
@nexxai @bsclifton - Yes this issue is fixed, but is not yet part of the stable release - https://github.com/brave/brave-core/pull/4042

**Comment by jshan17** [comment]
Hello I have Google push notifcations enabled AND I have Notifcations settings set to allow sites to ask. Only popular sites like Facebook and Trading View are successfully asking for notifications when I visit them, then their push notifications actually send. But news sites like Bitcoinist.com and Youtube are not asking. Does anyone know how to enable website push notifications? I’ve already gone to settings and selected, Allow Sites to ask for permission, but my crypto news sites won’t ask for permission to send notifications. I'm using Windows 10 -Brave is up to date: Version 1.5.113 Chromium: 80.0.3987.149 (Official Build) (64-bit) - just updated today. But I cannot receive notifications from sites like Youtube, Twitter, or Crypto news sites. I've seen many different threads on this topic but none have solved my issue. I've also been able to receive notifications from testing sites listed, but still no improvement. Help??

**Comment by SebasG22** [comment]
> When I try to enable "Use Google Services for Push Messaging" in the Advanced settings section, it prompts me to relaunch, but as soon as I do, the option is disabled again.
> 
> <img alt="Screen Shot 2020-01-01 at 9 13 55 PM" width="685" src="https://user-images.githubusercontent.com/4316564/71651538-a0798580-2cdb-11ea-9d64-b841f3e1ce32.png">
> 
> After relaunching:
> 
> <img alt="Screen Shot 2020-01-01 at 9 16 31 PM" width="680" src="https://user-images.githubusercontent.com/4316564/71651585-049c4980-2cdc-11ea-8a93-b73dc908dcc3.png">
> 
> Version 1.1.23 Chromium: 79.0.3945.88 (Official Build) (64-bit)
> MacOS 10.15.2

Nice solution. This works for me.
