### ISSUE TITLE
Sometimes it takes multiple attempts to connect/disconnect Brave VPN from Hamburger menu

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#23018]
## Description 

When connecting/disconnecting Brave VPN from flyout menu, have to click multiple times on the toggle. This could be perhaps the connect/disconnect is in the process.  The statuses are displayed incorrect as well particularly after toggle `ON` which shows `Disconnecting` instead of `Connecting`.   

## Steps to Reproduce

   1. Install 1.40.x and launch Brave
   2. Purchase VPN and enable VPN (follow setup steps to get a working VPN connection)
   3. Click Hamburger and select Brave VPN
   4. Toggle `ON` and `OFF`  

## Actual result:

Toggle `ON` and `OFF` to connect and disconnect takes multiple attempts
Connected and Disconnected statuses do not update for few seconds and even after reopening hamburger menu

https://user-images.githubusercontent.com/98358127/169927257-cb562283-3294-477d-9964-1e0c4f56ac5b.mp4

## Expected result:
Correct statuses should be displayed
Brave VPN Toggle `ON` and `OFF` behavior should be as expected.

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Brave | 1.40.71 Chromium: 102.0.5005.61 (Official Build) beta (64-bit)
-- | --
Revision | 0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}
OS | Windows 11 Version 21H2 (Build 22000.675)

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
cc: @rebron @stephendonner @LaurenWags @GeetaSarvadnya

**Comment by bsclifton** [comment]
Closing as stale - this shouldn't be happening anymore 😄
