### ISSUE TITLE
Install cargo binary tools without `--locked` flag during sync/init

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#23011]
https://bravesoftware.slack.com/archives/C7VLGSR55/p1653318029759329

**Comment by rillian** [comment]
This was intended to fix the problem
```
$ cargo +1.59.0 install cargo-audit --locked --version 0.17.0
error: failed to select a version for the requirement `libgit2-sys = "^0.13.4"`
candidate versions found which didn't match: 0.13.2+1.4.2, 0.13.1+1.4.2, 0.13.0+1.4.1, ...
location searched: crates.io index
required by package `git2 v0.14.4`
    ... which satisfies dependency `git2 = "^0.14"` (locked to 0.14.4) of package `rustsec v0.26.0`
    ... which satisfies dependency `rustsec = "^0.26"` (locked to 0.26.0) of package `cargo-audit v0.17.0 (/home/giles/src/cargo-audit-0.17.0/cargo-audit-0.17.0)`
```

We're now reverting this fix for #28223, so it bears further investigation. I looked a bit, but it's not clear why cargo isn't able to match the specified `libgit2-sys 0.13.4` which has't been yanked. Resolves fine with 1.60.0 and 1.67.0.

Maybe it was just a cargo bug? Don't see anything likely [in the changelog](https://github.com/rust-lang/cargo/blob/master/CHANGELOG.md#cargo-160-2022-04-07).
