### ISSUE TITLE
Improve UI for VPN connection errors

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#23028]
## Description 

I had an issue with connection to guardianapp
```
curl -X CONNECT connect-api.guardianapp.com:443
curl: (28) Failed to connect to connect-api.guardianapp.com port 443 after 21056 ms: Timed out
```
and it was not clear from current UX, need to improve and add explanation with suggestions how to fix that.
<img width="313" alt="image" src="https://user-images.githubusercontent.com/2965009/170100956-b20f1f70-1294-48ac-a9c8-dca1ee530ebc.png">

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.41.40 Chromium: 102.0.5005.78 (Official Build) nightly (x86_64)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | macOS Version 12.5 (Build 21G5037d)

Followed the testplan provided in https://github.com/brave/brave-core/pull/13486

#### Confirmed that when unable to reach `connect-api.guardianapp.com`, we show the appropriate error-messaging UI (*most of the time, see final note, below).

example | example
---------|---------
<img width="682" alt="Screen Shot 2022-06-06 at 6 10 13 PM" src="https://user-images.githubusercontent.com/387249/172275603-4fdfa09d-0a91-45ae-9a7f-a2acd56ddfa7.png"> | <img width="1312" alt="Screen Shot 2022-06-06 at 6 16 45 PM" src="https://user-images.githubusercontent.com/387249/172275640-7dc5ada9-8ae1-4611-8652-64c4be4fe8e5.png">

Looks like we're still hitting https://github.com/brave/brave-browser/issues/22882 (just noting):

![still-wonky](https://user-images.githubusercontent.com/387249/172275779-39c475fa-fd64-473c-a958-a47cc5ef80f5.gif)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using

Brave | 1.41.91 Chromium: 103.0.5060.114 (Official Build) beta (64-bit)
-- | --
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | Windows 11 Version 21H2 (Build 22000.739)


Followed the testplan provided in https://github.com/brave/brave-core/pull/13486

### Steps: 
- Install `1.41.91`
- Block `connect-api.guardianapp.com` in Fiddler
- Purchase and set up BraveVPN via [account.brave.software](https://account.brave.software/) 
- Click on VPN button next to URL bar
- Confirmed error message modal displayed 

![image](https://user-images.githubusercontent.com/98358127/177841093-08524261-118c-40f3-a20f-80f9867a1b72.png)


![2022-07-07_11h07_49](https://user-images.githubusercontent.com/98358127/177841038-b4ed2e23-d366-434e-9e9c-216781f640f1.gif)
