### ISSUE TITLE
Yearly subscription discount price should show local currency instead of USD

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23027]
## Description 
Yearly subscription discount price should show local currency instead of USD

## Steps to reproduce 

   1. Install 1.39.111
   2. Select VPN from menu
   3. Yearly subscription shows USD for discount price instead of local currency

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/170087836-dc12306d-7b5d-4817-bee5-49df487e199d.png)

## Expected result
Should show the local currency

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
All

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @deeppandya @mattmcalister @timchilds @anthonypkeane @Uni-verse

**Comment by deeppandya** [comment]
@srirambv this issue should be fixed with https://github.com/brave/brave-core/pull/21126. would it be possible to verify and close the issue ?

**Comment by srirambv** [comment]
This is fixed now
<img width=300 src=https://github.com/brave/brave-browser/assets/17010094/cfb2367a-4b20-409d-920b-20a261115326>
