### ISSUE TITLE
[hackerone] url debouncing issue

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#23026]
https://hackerone.com/reports/1579374

short-term solution:

1. narrow down overly-broad debounce rules like the one for FB 
2. remove "high profile redirectors" for now

https://bravesoftware.slack.com/archives/G2KN13Z8C/p1653502351425129?thread_ts=1653409613.492429&cid=G2KN13Z8C

**Comment by fmarier** [comment]
https://github.com/brave/adblock-lists/pull/862 covers the second point above.

We should still address the first point by looking through the existing rules to see if we can tighten up the URLs and remove as many wildcards as possible.

**Comment by fmarier** [comment]
https://github.com/brave/adblock-lists/issues/871 will cover the first point.

**Comment by fmarier** [comment]
Both tasks are now done.
