### ISSUE TITLE
[Sync] Do not propose send tabs to iOS devices 

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#23025]
Currently  iOS devices have only Bookmarks, History and Passwords sync. 

But other devices which have some desktop OS or Android propose to send tabs to iOS devices.

This should be disabled till iOS will not have the actual ability to do this.

**Comment by bsclifton** [comment]
Related (once we're ready to implement `Send to your devices`)
https://github.com/brave/brave-ios/issues/3229

@soner-yuksel currently looking onto adding in tab sync to iOS

**Comment by AlexeyBarabash** [comment]
Similar to https://github.com/brave/brave-browser/issues/22376 .
Implemented in https://github.com/brave/brave-ios/issues/3229 .
