### ISSUE TITLE
Selecting VPN causes browser to crash

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23037]
## Description 
Selecting VPN causes browser to crash

## Steps to reproduce (Not 100% sure just possible steps)

   1. Purchase a subscription for VPN and enable it
   2. Go to system settings and enable `Always On` and `Block all connections not using VPN` from Device VPN settings
   3. Auto-connect to the nearest server
   4. Background app while VPN is connected
   5. Change device locale/region to a different country
   6. Launch Brave 
   7. Subscription has expired message is shown (Assuming because the playstore region is changed and subscription is not valid)
   8. Switch back to the original locale where subscription was purchased
   9. Click on VPN from menu, browser crashes

## Actual result 
Browser crashes when selecting VPN after getting subscription has expired message

- Uploaded crash report ID:	e33b0500-6540-3b08-0000-000000000000 (Not found on backtrace)
- Uploaded crash report ID:	e13b0500-6540-3b08-0000-000000000000 (https://share.backtrace.io/api/share/UNnHWFuaCGWA7S8LIbwvf2)
- Uploaded crash report ID:	e03b0500-6540-3b08-0000-000000000000 (https://share.backtrace.io/api/share/CAJ8bZEHdml1x2dvL4yean1)
- Uploaded crash report ID:	df3b0500-6540-3b08-0000-000000000000 (https://share.backtrace.io/api/share/pwjNYLhyZKYGVmax3qx3PW81)

## Expected result
No crash

## Issue reproduces how often 
Once

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Not tested
- Can you reproduce this issue with the current Play Store Nightly version? Not tested

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version:12
   
## Brave version
1.39.111

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @deeppandya @kjozwiak @anthonypkeane @timchilds @mattmcalister @bsclifton @SergeyZhukovsky @Uni-verse

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.39.112 x64 build
- Verified steps from issue description
- Verified no crash when selecting VPN from menu
- Encountered [#23071](https://github.com/brave/brave-browser/issues/23071), [#23072](https://github.com/brave/brave-browser/issues/23072), [#23073](https://github.com/brave/brave-browser/issues/23073), [#23074](https://github.com/brave/brave-browser/issues/23074), [#23075](https://github.com/brave/brave-browser/issues/23075), [#23076](https://github.com/brave/brave-browser/issues/23076)

**Comment by kjozwiak** [comment]
While using `1.39.113 Chromium 102.0.5005.61`, @LaurenWags went through the following to ensure that `VPN` was disabled on `x86` devices as per the following:

```
Verification **PASSED** on `Asus Zenfone (x86)` running `Android 6` as per the following:

* Confirmed no mention of VPN on menu or in Settings with clean install of 1.39.113
* Installed 1.38.119 (pre-VPN), upgraded to 1.39.113, confirmed no mention of VPN on menu or in Settings
* Installed 1.39.111 and saw VPN on menu but crashed when trying to open Settings, upgraded to 1.39.113, confirmed no mention of VPN on menu or in Settings, no crash opening settings
```

@LaurenWags also verified that Brave wasn't crashing via https://github.com/brave/brave-browser/issues/23063#issuecomment-1138530783 using the ` Asus Zenfone (x86)` device that was running `Android 6`.
