### ISSUE TITLE
Remove `on toolbar` in `Hide Brave Wallet icon on toolbar` in its context-menu text

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#23033]
## Description 

Remove `on toolbar` in `Hide Brave Wallet icon on toolbar` in its context-menu text

## Steps to Reproduce

   1. install `1.41.11`
   2. launch Brave
   3. context/right-click on the `Brave Wallet` icon on the toolbar
   4. note its descriptive text

## Actual result:

`Hide Brave Wallet icon on toolbar`

<img width="1527" alt="Screen Shot 2022-05-24 at 3 57 15 PM" src="https://user-images.githubusercontent.com/387249/170145886-6d07f527-3aa6-4c99-8bb9-c178ad90ccac.png">

## Expected result:

Should shorten it to at least `Hide Brave Wallet icon` a la Rewards?

<img width="1100" alt="Screen Shot 2022-05-24 at 4 06 42 PM" src="https://user-images.githubusercontent.com/387249/170146322-ec2cfebe-32fd-49a1-8d53-9b1c5cfbea81.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.41.11 Chromium: 102.0.5005.61 (Official Build) nightly (x86_64)
-- | --
Revision | 0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}
OS | macOS Version 12.5 (Build 21G5027d)

cc @spylogsster @rebron @rmcfadden3 @jamesmudgett

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.41.21 Chromium: 102.0.5005.61 (Official Build) nightly (x86_64)
-- | --
Revision | 0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}
OS | macOS Version 12.5 (Build 21G5027d)

### Confirmed it now reads `Hide Brave Wallet icon`

<img width="1113" alt="Screen Shot 2022-05-27 at 5 13 44 PM" src="https://user-images.githubusercontent.com/387249/170802026-4b194f69-7b6a-40cb-be94-ec379c15859a.png">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.41.47 Chromium: 102.0.5005.78 (Official Build) nightly (64-bit)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | Windows 11 Version 21H2 (Build 22000.675)
```
Confirmed it now reads `Hide Brave Wallet icon`

![image](https://user-images.githubusercontent.com/98358127/172720009-42040d8e-d74f-4b75-b32f-9a2730669274.png)
