### ISSUE TITLE
HTTPS-Only Mode for Private Windows with Tor

### ISSUE THREAD

**Issue by arthuredelstein** [brave/brave-browser#23030]
To enhance the safety of users of Tor windows, we should enable HTTPS-Only Mode by default.

HTTPS-Only Mode is currently opt-in. When it is enabled, attempting to visit an insecure website results in the following interstitial page from Chromium:

![image](https://user-images.githubusercontent.com/355566/170125006-c45561b9-abcf-431a-b3f0-2a93943f627c.png)

We can consider whether to add more information to the message on this page that is Tor-specific.

**Comment by diracdeltas** [comment]
bumping this to p2 since tor browser is now doing this: https://betanews.com/2022/07/17/tor-browser-11-5-is-here-with-https-only-mode-by-default-and-automatic-censorship-circumvention/

**Comment by ArshErgon** [comment]
is it still open? @diracdeltas and @arthuredelstein ? can you assign me this? and guide me how will I going to set it up locally?

**Comment by Sranjan0208** [comment]
Hey! Is anyone working on this issue? If not can you assign me this? Also it would be really helpful if you can provide any resources which can help us in this issue.

**Comment by diracdeltas** [comment]
nobody has been working on this, PRs are welcome. but if you get stuck let us know and we can figure out someone at brave to assign.

**Comment by arthuredelstein** [comment]
I'll be taking on this issue shortly. @ArshErgon or @Sranjan0208: if you already started working on this, please let me know -- you can reach me at aedelstein AT brave DOT com.

**Comment by kristiankauffeld** [comment]
I'd like to take a look at it, but can you give any hints at what files to look at in the src code?

**Comment by fmarier** [comment]
Related issue: https://github.com/brave/brave-browser/issues/1136

**Comment by arthuredelstein** [comment]
Ideas for QA tests on Brave Desktop:

**Test 1**
Please test the following insecure websites in a normal window, a Private Windows, and a Private Window with Tor.
 * http://http.badssl.com
 * http://insecure.arthuredelstein.net

In normal and Private Windows, these sites should load with `http://`. In a Private Window with Tor, the browser should show an interstitial warning page with the message "The connection to $website is not secure." For each website, if you press "Continue to Site" it should load the website under `http://`. If you press "Go back" it should show the previous page.

**Test 2**
Please test the following upgradable websites in a normal window, a Private Window, and a Private Window with Tor:
 * http://example.com
 * http://upgradable.arthuredelstein.net
 
 In normal and Private Windows, these sites should load with `http://`. In a Private Window with Tor, the site should automatically load with `https://`. No warning pages should be shown.

**Test 3**
Please test the following self-upgrading secure websites in a normal window, a Private Window, and a Private Window with Tor:
* http://brave.com
* http://github.com

These sites should automatically upgrade to `https://` in all windows without any warning pages.

**Test 4**
Please test the following .onion sites in a Private Window with Tor:
* Riseup: http://vww6ybal4bd7szmgncyruucpgfkqahzddi37ktceo3ah7ngmcopnpyyd.onion/
* Tor Project: http://2gzyxa5ihm7nsggfxnu52rck2vv4rvmdlkiu3zzui5du4xyclen53wid.onion/
* Keybase: http://keybase5wmilwokqirssclfnsqrjdsi7jdir5wy7y7iu3tanwmtp6oid.onion/
Each of these sites uses `http://`, but should load without showing an error page because .onion sites are secure without requiring `https://`.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.45.74 Chromium: 106.0.5249.55 (Official Build) beta (x86_64)
-- | --
Revision | 4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}
OS | macOS Version 11.7 (Build 20G817)

### Test 1

#### `http://http.badssl.com/`

normal window | private window | private window w/tor
----------------|----------------|---------------------
<img width="1312" alt="Screen Shot 2022-09-26 at 7 29 09 PM" src="https://user-images.githubusercontent.com/387249/192398553-4002d452-d6bc-40e7-9640-1c2cae1ab5ab.png"> | <img width="1312" alt="Screen Shot 2022-09-26 at 7 30 06 PM" src="https://user-images.githubusercontent.com/387249/192398600-9251aef6-d8a2-4641-841b-a0cd9dcdfc40.png"> | <img width="1312" alt="Screen Shot 2022-09-26 at 7 31 09 PM" src="https://user-images.githubusercontent.com/387249/192398601-5ed911b3-1e61-4199-854c-eff67acbb2be.png">

#### `http://insecure.arthuredelstein.net`

normal window | private window | private window w/tor
----------------|----------------|---------------------
<img width="1312" alt="Screen Shot 2022-09-26 at 7 29 33 PM" src="https://user-images.githubusercontent.com/387249/192398782-d71184a5-1945-473c-9e59-534572d3631f.png"> | <img width="1312" alt="Screen Shot 2022-09-26 at 7 29 56 PM" src="https://user-images.githubusercontent.com/387249/192398783-a1c0388e-d61a-4226-8f45-d0255f5c9f5b.png"> | <img width="1312" alt="Screen Shot 2022-09-26 at 7 34 46 PM" src="https://user-images.githubusercontent.com/387249/192398868-ef399397-2f05-4c25-a934-af5566ebc60c.png">




### Test 2

normal window | private window | private window w/tor
----------------|----------------|---------------------



### Test 3

normal window | private window | private window w/tor
----------------|----------------|---------------------

### Test 4

normal window | private window | private window w/tor
----------------|----------------|---------------------

**Comment by stephendonner** [comment]
@arthuredelstein thank you so much for the testcases!  🙏

**Comment by arthuredelstein** [comment]
@stephendonner Thank you for the great QA! To confirm -- does "full" refer to what happens after pressing the "continue to site" button?

**Comment by stephendonner** [comment]
> @stephendonner Thank you for the great QA! To confirm -- does "full" refer to what happens after pressing the "continue to site" button?

Yes, let me change it to "fully loaded" for clarify 👍

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using 
```
Brave | 1.46.69 Chromium: 107.0.5304.36 (Official Build) beta (64-bit)
-- | --
Revision | 2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}
OS | Windows 11 Version 22H2 (Build 22621.674)
```

Test 1

http://http.badssl.com/


Normal|Private window|Private window w/TOR, interstitial|Fully loaded|previous page, click back
------------|-------------|-----------------|----------------|-------
<img width="959" alt="image" src="https://user-images.githubusercontent.com/98358127/198678832-5ec5c0c7-fa67-4619-af79-92066088f493.png">|<img width="955" alt="image" src="https://user-images.githubusercontent.com/98358127/198678970-9a882b31-200b-4d05-9e57-13881be6be19.png">|<img width="960" alt="image" src="https://user-images.githubusercontent.com/98358127/198679520-d30c7a16-3261-4843-9eea-399e9e40c8bd.png">|<img width="958" alt="image" src="https://user-images.githubusercontent.com/98358127/198679650-debe7500-3cfc-4734-9d6f-8a37ed64d7be.png">|<img width="957" alt="image" src="https://user-images.githubusercontent.com/98358127/198679698-10f092ab-d5b5-4a8f-aacb-9f4cb0001916.png">

**Comment by MadhaviSeelam** [comment]
@arthuredelstein thanks for fixing the URL. Was going to reach out to you infact and that worked.  Now I need help again from you. `Keybase` onion site is throwing an error `This site can't be reached`

![image](https://user-images.githubusercontent.com/98358127/198725992-e385bd8a-0146-4720-9f9e-9bd1ac1034b6.png)

**Comment by fmarier** [comment]
I have the same problem with Keybase, it seems like their Onion site/gateway might be down.

**Comment by MadhaviSeelam** [comment]
Thanks @fmarier for confirming!!

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.46.106 Chromium: 107.0.5304.110 (Official Build) beta (64-bit) 
Revision	2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}
OS	Linux
```
