### ISSUE TITLE
Content setting defaults are set incorrectly and ignored

### ISSUE THREAD

**Issue by bridiver** [brave/brave-browser#23031]
The content settings are registered with incorrect values and the registered values are ignored (probably leftover code from plugin id removal)

**Comment by bridiver** [comment]
QA should do normal setting checks for shields

**Comment by stephendonner** [comment]
> QA should do normal setting checks for shields

Note: wait until https://github.com/brave/brave-browser/issues/23245 and others are in and verified before circling back to this /cc @brave/qa-team

**Comment by LaurenWags** [comment]
@brave/qa-team no longer need to wait for https://github.com/brave/brave-browser/issues/23245 to test this issue as https://github.com/brave/brave-browser/issues/23245 has been closed as a duplicate.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.41.74 Chromium: 103.0.5060.53 (Official Build) beta (x86_64)
-- | --
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | macOS Version 12.5 (Build 21G5046c)

### Steps:
1. installed `1.41.74`
2. launched Brave
3. opened `brave://settings/shields`
4. loaded `cnn.com` and clicked on the Shields icon
5. compared content-blocking defaults


brave://settings/shields | Shields icon
-------------------------|-------------
Trackers & ads blocking `Standard` | `Block trackers & ads`
Upgrade connections to HTTPS `ON` | Upgrade connections to HTTPS `ON`
Block scripts `OFF` | Block scripts `OFF`
Block fingerprinting `Standard` | Block fingerprinting
Block cookies `Only cross-site` | Block cross-site cookies

`brave://settings/shields` | Shields icon
---------------------------------|-----------------
<img width="1181" alt="Screen Shot 2022-06-21 at 1 51 18 PM" src="https://user-images.githubusercontent.com/387249/174895257-c689cf93-f6ae-4959-8a74-d1208275e28a.png"> | <img width="385" alt="Screen Shot 2022-06-21 at 1 51 00 PM" src="https://user-images.githubusercontent.com/387249/174895286-42c9b739-0052-46ed-8ea3-6f72aedd7402.png">

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.41.77 Chromium: 103.0.5060.53 (Official Build) beta (64-bit) 
--|--
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | Linux


#### Confirmed defaults matched between brave://settings/shields and the Shields icon, and worked.

### Steps:
1. installed `1.41.77`
2. launched Brave
3. opened `brave://settings/shields`
4. loaded `cnn.com` and clicked on the Shields icon
5. compared content-blocking defaults


brave://settings/shields | Shields icon
-------------------------|-------------
Trackers & ads blocking `Standard` | `Block trackers & ads`
Upgrade connections to HTTPS `ON` | Upgrade connections to HTTPS `ON`
Block scripts `OFF` | Block scripts `OFF`
Block fingerprinting `Standard` | Block fingerprinting
Block cookies `Only cross-site` | Block cross-site cookies

`brave://settings/shields` | Shields panel
---------------------------------|-----------------
<img width="1603" alt="Screen Shot 2022-06-23 at 2 33 02 PM" src="https://user-images.githubusercontent.com/387249/175407095-0a5c93f8-c606-4bd7-9fb5-3be36ab3eb1d.png">
<img width="349" alt="Screen Shot 2022-06-23 at 2 33 30 PM" src="https://user-images.githubusercontent.com/387249/175407099-389e87b9-4e9d-4107-9974-934d09cfcac4.png">

**Comment by MadhaviSeelam** [comment]
Verification `Passed` using 
```
Brave | 1.41.86 Chromium: 103.0.5060.66 (Official Build) beta (64-bit)
-- | --
Revision | 20b1569438a85e631d15e83eb355e3e326e5da6f-refs/branch-heads/5060@{#1066}
OS | Windows 11 Version 21H2 (Build 22000.739)
```

#### Confirmed defaults matched between brave://settings/shields and the Shields icon.

### Steps:
1. installed `1.41.86`
2. launched Brave
3. loaded `nytimes.com` and clicked on the Shields icon
4. click Advanced controls>>Global defaults 
5. compared content-blocking defaults on `brave://settings/shields` page

brave://settings/shields | Shields icon
-------------------------|-------------
Trackers & ads blocking `Standard` | `Block trackers & ads`
Upgrade connections to HTTPS `ON` | Upgrade connections to HTTPS `ON`
Block scripts `OFF` | Block scripts `OFF`
Block fingerprinting `Standard` | Block fingerprinting
Block cookies `Only cross-site` | Block cross-site cookies

shields panel|settings page
----|----
<img width="951" alt="image" src="https://user-images.githubusercontent.com/98358127/176957602-b6114878-33a5-412e-967b-0637038f7d2f.png">|<img width="194" alt="image" src="https://user-images.githubusercontent.com/98358127/176957624-e32cc8b9-5f6e-4786-a6df-b3df2e90926e.png">

Performed regression on global defaults page:
**Steps:**

1. installed 1.41.86
2. launched Brave
3. load nytimes.com
4. click `Shields` icon to open shields panel
5. click Advanced controls>Global defaults 
6. switch to `Aggressive in `Trackers & ads blocking` 
7. switch to `All` in `Block cookies`
8. return to `nytimes.com` and verified correct values shown in the shields panel
9. go to brave://settings/cookies and verified `Block all cookies` was selected
10. reset global defaults to original settings from clear browsing data>>Advanced>>Site and Shields settings
11. also click Reset settings on brave://settings page to reset values in the global defaults page
12. default values are shown in the brave://settings/shields page

Step 6 & 7|Step 8|Step 9|Step 10|Step 12
--------|--------|---------|---------|---------
<img width="952" alt="image" src="https://user-images.githubusercontent.com/98358127/176957861-3b9a0ab5-d451-4e4c-88bf-655a594e3780.png">|<img width="952" alt="image" src="https://user-images.githubusercontent.com/98358127/176958228-82c49dd6-406f-4ca3-8c3a-01a04f39360a.png">|<img width="944" alt="image" src="https://user-images.githubusercontent.com/98358127/176958298-b247722a-a68d-409d-8959-625a85a7a1a6.png">|<img width="953" alt="image" src="https://user-images.githubusercontent.com/98358127/176958767-17f0aaab-e27d-4e63-91a4-5ed328b455f6.png">|<img width="953" alt="image" src="https://user-images.githubusercontent.com/98358127/176958901-e3ff6949-1f4e-4373-b5ff-fd65f1f16950.png">
