### ISSUE TITLE
Wallet auto-lock doesn't hide ApproveTxBottomSheetDialog

### ISSUE THREAD

**Issue by wchen342** [brave/brave-browser#23049]
## Description 
Approve tx bottom sheet is not hidden when wallet is auto-locked.

## Steps to reproduce 

   1. Unlock wallet, init a transaction but do not approve or reject.
   2. Go back to portfolio screen.
   3. Click on the bell icon to bring up the bottom sheet.
   4. Wait for auto-lock.
   5. The bottom sheet is not hidden when wallet is locked.

## Version/Channel Information:
Nightly

**Comment by srirambv** [comment]
Unable to repro it with or without fingerprint enabled

**Comment by wchen342** [comment]
Updated with extra steps.
