### ISSUE TITLE
Selecting Filecoin from network selector causes it to show `Not a valid address` for address field

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23046]
## Description 

Selecting Filecoin from network selector causes it to show `Not a valid address` for address field

## Steps to Reproduce

   1. Enable Filecoin flag on nightly
   2. Create a Filecoin account
   3. Select Filecoin from Network selector under Send, shows `Not a valid address` error message even when address field is empty

## Actual result:

https://user-images.githubusercontent.com/17010094/170198594-360ff7b7-56b8-4c93-a909-f9eb432f0a20.mov

## Expected result:
Should only show the error when an incorrect address is typed/pasted

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html><head></head>
<body>

Brave | 1.41.11 Chromium: 102.0.5005.61 (Official Build) nightly (64-bit)
-- | --
Revision | `0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}`
OS | Windows 11 Version 22H2 (Build 22621.1)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @spylogsster

**Comment by kjozwiak** [comment]
The above requires `1.40.80` or higher for `1.40.x` verification 👍
