### ISSUE TITLE
Rewire correct block explorer for Filecoin Transactions

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23048]
## Description 

Rewire correct block explorer for Filecoin Transactions

## Steps to Reproduce

   1. Initiate a transaction on Filecoin
   2. Click on `View on block explorer`
   3. Opens a new tab and loads `https://calibration.node.glif.io/rpc/v0/tx/<TX_ID>` which shows `{"message":"Missing Authentication Token"}` message

## Actual result:

https://user-images.githubusercontent.com/17010094/170230528-6261b724-9b45-4166-93bb-e90eafc5e069.mov

## Expected result:
Load correct block explorer to view transactions

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html><head></head>
<body>

Brave | 1.41.11 Chromium: 102.0.5005.61 (Official Build) nightly (64-bit)
-- | --
Revision | `0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}`
OS | Windows 11 Version 22H2 (Build 22621.1)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? nA

## Miscellaneous Information:

cc: @jamesmudgett @spylogsster @muliswilliam @Douglashdaniel

**Comment by kjozwiak** [comment]
The above will require `1.40.89` or higher for `1.40.x` verification 👍

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.40.95 Chromium: 102.0.5005.115 (Official Build) beta (64-bit) </th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>174dbe6e33bc81994fceb71d751be201d0b4803d-refs/branch-heads/5005_109@{#3}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.708)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from issue description</li>
         <li>Verified correct block explorer is loaded for both Mainnet and Testnet</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/173344032-e93899a3-429d-47c6-b8d3-80e5e6ba559c.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/173344076-4c1f9802-530a-41f7-971a-7674c0eb6b74.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/173344041-e3277f94-bcf4-4494-8025-22bbac4802da.mov>
      </td>
   </tr>
</table>
