### ISSUE TITLE
Unable to connect to VPN

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23051]
## Description 

Unable to connect to VPN

## Steps to Reproduce

   1. Follow steps from https://bravesoftware.slack.com/archives/CC5SA8CCB/p1651597201141019?thread_ts=1651597077.189229&amp;cid=CC5SA8CCB
   2. Click on Connect in the VPN modal
   3. Install the config when prompted
   4. Goes into infinite connect state
   5. Close panel and open, shows Disconnecting
   6. Go to System Preferences and delete the config 
   7. Quit browser and restart and try to enable again, no prompt is shown to re-install config

## Actual result:

https://user-images.githubusercontent.com/17010094/170292140-eaefd2cb-9bdb-4747-b8e5-8e1a57aa2aac.mov

## Expected result:
Should connect VPN without any issues. If config has been removed, trying to reconnect should prompt reinstall of the config file

## Reproduces how often: 

Easy on my profile

## Brave version (brave://version info)

Brave | 1.41.11 Chromium: 102.0.5005.61 (Official Build) nightly (64-bit)
-- | --
Revision | `0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}`
OS | macOS Version 12.3.1 (Build 21E258)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @bsclifton @brave/legacy_qa

**Comment by bsclifton** [comment]
@srirambv can you re-test this scenario on Nightly once we get a new build? Basically 1.41.39 or later

**Comment by srirambv** [comment]
I'll keep an eye on this one. I was able to connect without issues on macOS and Windows. Will keep trying on the next update as well and close the issue

**Comment by bsclifton** [comment]
Closing as stale; if we have more problems, let's re-open with some more specific steps (now that process is more robust)
