### ISSUE TITLE
Add rotating hash to payload

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#23055]
See https://github.com/brave/security/issues/880 for context

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.43.63 Chromium: 104.0.5112.81 (Official Build) beta (64-bit)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | Ubuntu 18.04 LTS

#### rotating hash is the same for different versions for the same ad
1.44.x
![image](https://user-images.githubusercontent.com/34715963/184019855-56631029-af6e-47f2-accf-05a9c65a0306.png)

1.43.x
![image](https://user-images.githubusercontent.com/34715963/184020526-ef935b61-8165-40e5-973d-32d0b36e8358.png)

#### rotating hash is different for different creative instance ids
![image](https://user-images.githubusercontent.com/34715963/184023801-97d72728-17d7-4a41-a0ed-2fd1509448d5.png)
Different ad:
![image](https://user-images.githubusercontent.com/34715963/184025406-5cf79339-b40f-4b42-9a30-d6407a02490c.png)


#### rotating hash is rotating every 1h

![image](https://user-images.githubusercontent.com/34715963/184021522-4995d3bd-8b90-43b7-9f15-cb1cc18fdf18.png)
