### ISSUE TITLE
Enable `Warn me before closing window with multiple tabs` as a default 

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#23056]
## Description 

Currently `Warn me before closing window with multiple tabs` preference is disabled as a default option in `Help tips` section in `brave://settings`

This setting should be enabled by default for new and existing users.

## Steps to Reproduce

   1. Install 1.40.x
   2. Launch brave
   3. Open Help and tips section in brave://settings/

## Actual result:

`Warn me before closing window with multiple tabs` is toggled `OFF` as a default
![image](https://user-images.githubusercontent.com/98358127/170320407-80037342-acd3-4e85-a170-586e2f59ada9.png)

## Expected result:
Toggle `ON`  for `Warn me before closing window with multiple tabs` as a default 
![image](https://user-images.githubusercontent.com/98358127/170320462-80ff168e-337c-4c9d-b9d4-7b05cbf72a3a.png)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
cc: @rebron

**Comment by MadhaviSeelam** [comment]
### Verification `PASSED` using
```
Brave | 1.41.47 Chromium: 102.0.5005.78 (Official Build) nightly (64-bit)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | Windows 11 Version 21H2 (Build 22000.675)
```
Install 1.41.x
Launch brave
Open `Help tips` section in `brave://settings`
Verified `Warn me before closing window with multiple tabs` toggle is `Enabled` as a default
`Close all tabs?` functionality worked as expected

Toggle ON|Close all tabs
----|----
<image width="950" alt="enable" src="https://user-images.githubusercontent.com/98358127/172664751-b331fb18-7ded-4354-b30c-bc2680e1a2eb.png">|<image width="950" alt="closed modal" src="https://user-images.githubusercontent.com/98358127/172664935-6b65c1b9-86c4-4e44-8b91-dd4011fe2fee.png">

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.41.47 Chromium: 102.0.5005.78 (Official Build) nightly (x86_64)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | macOS Version 12.5 (Build 21G5037d)

### Steps:
1. installed `1.41.47`
2. launched Brave
3. opened `brave://settings/braveHelpTips`
4. confirmed `Warn me before closing windows with multiple tabs` is set to `Enabled` by default
5. opened multiple tabs
6. clicked on the close-window widget

Confirmed I saw the `Close all tabs?` dialog and tested its functionality

`brave://settings/braveHelpTips` | `Close all tabs?`
---------------------------------|------------------
<img width="1312" alt="Screen Shot 2022-06-08 at 4 35 56 PM" src="https://user-images.githubusercontent.com/387249/172734985-e5c6ad46-0560-4e8c-bb92-8ad83c8583a2.png"> | <img width="1312" alt="Screen Shot 2022-06-08 at 4 37 16 PM" src="https://user-images.githubusercontent.com/387249/172734987-dcb9df80-c321-4224-8f34-8c1acb314d89.png">

**Comment by kjozwiak** [comment]
Removing the `QA Pass` labels as we'll need to re-check this via `1.40.x` as the above was uplifted into` 1.40.x` via https://github.com/brave/brave-core/pull/13677. Used the verification from https://github.com/brave/brave-browser/issues/23056#issuecomment-1150116913 & https://github.com/brave/brave-browser/issues/23056#issuecomment-1150518602 for the uplift. This is a big feature so glad we checked it on two platforms before uplifting 👍

**Comment by MadhaviSeelam** [comment]
Verification `Passed` using 
```
Brave | 1.40.91 Chromium: 102.0.5005.78 (Official Build) beta (64-bit)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | Windows 11 Version 21H2 (Build 22000.675)
```

- Install 1.41.47
- Launch brave
- Open `Help tips` section in `brave://settings`
- Open another tab
- Verified `Warn me before closing window with multiple tabs` toggle is `Enabled` as a default
- `Close all tabs?` functionality worked as expected

default|close_all_tabs
---|---
<img width="949" alt="image" src="https://user-images.githubusercontent.com/98358127/172920525-0d9fad7c-f67b-45e7-8e05-99d074e7e3b5.png">|<img width="949" alt="image" src="https://user-images.githubusercontent.com/98358127/172931711-4138791f-4fcb-4ce0-874d-0522031ac9e3.png">

**Comment by stephendonner** [comment]
## Verified `PASSED` using 



Brave | 1.40.91 Chromium: 102.0.5005.78 (Official Build) beta (x86_64)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | macOS Version 12.5 (Build 21G5037d)


### Steps:
1. installed `1.40.97`
2. launched Brave
3. opened `brave://settings/braveHelpTips`
4. confirmed `Warn me before closing windows with multiple tabs` is set to `Enabled` by default
5. opened multiple tabs
6. clicked on the close-window widget

Confirmed I saw the `Close all tabs?` dialog and tested its functionality

`brave://settings/braveHelpTips` | `Close all tabs?`
---------------------------------|------------------
<img width="1312" alt="Screen Shot 2022-06-09 at 10 00 15 PM" src="https://user-images.githubusercontent.com/387249/172993744-24e8ecbb-b3d2-46e1-a4be-05f1a50119f7.png"> | <img width="1312" alt="Screen Shot 2022-06-09 at 10 01 01 PM" src="https://user-images.githubusercontent.com/387249/172993746-18c8432f-e151-49c6-a592-636c24a7e511.png">
