### ISSUE TITLE
DApps:  Crashes when all accounts are selected and then deselected from top to bottom

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#23050]
## Description 
On permission dialog, App crashes when all (> one) accounts are selected and deselected from top to bottom

## Steps to reproduce 

   1. Create more then one account
   2. Trigger permission dialog to connect accounts with DApps and Select all accounts
   3. Deselect all accounts from top (will crash)

## Actual result 
App is crashing when multiple accounts are selected and deselected

## Expected result
Should be able to select and deselect any account

## Issue reproduces how often 
easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? NA

**Comment by kjozwiak** [comment]
The above requires `1.40.78` or higher for `1.40.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.40.101 x64 build
- Verified steps from issue descriptoin
- Verified no crash when selecting and deselecting accounts in any order

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/174315934-3ec87335-7169-48ea-8d87-d6957238c586.mp4> | <video src=https://user-images.githubusercontent.com/17010094/174315977-76959958-c89e-4847-bbce-ad66b6acfd2d.mp4>
