### ISSUE TITLE
Disable Import from hardware wallet for Solana

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#23059]
## Description 
We do not yet support importing a `Solana` address from a hardware wallet, we need to disable this in the UI until that feature is available.

![Screen Shot 2022-05-25 at 1 01 53 PM](https://user-images.githubusercontent.com/40611140/170348310-ab25a9a2-33ae-4e3c-9ded-9a1a8156f8b9.png)

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.41.82 Chromium: 103.0.5060.66 (Official Build) beta (64-bit) </th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>20b1569438a85e631d15e83eb355e3e326e5da6f-refs/branch-heads/5060@{#1066}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.708)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/13470>brave/brave-core#13470</a></li>
         <li>Verified Solana is not available via <code>Import from Hardware Wallet</code></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/176172684-dcfa20a0-2796-494d-a93b-5491a7cc28d9.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/176168294-abd8f718-02e7-4421-9823-d69434fb90c9.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/176169523-68a582ae-1330-4e9a-9316-c7c8297ceb40.mov>
      </td>
   </tr>
</table>

**Comment by Douglashdaniel** [comment]
Changing to `release-notes/exclude` since https://github.com/brave/brave-browser/issues/23061 was uplifted to `1.41.x`, `Hardware Wallet` support should now be expected for `Solana` in `1.41.x`.
