### ISSUE TITLE
Off-center placeholder top sites icons on address bar

### ISSUE THREAD

**Issue by intrnl** [brave/brave-browser#23069]
## Description 
The placeholder icons/letters used to show top sites on the address bar view is off center.

## Steps to reproduce 

   1. Have a top site that hasn't had its icons fetched yet
   2. Tap on the address bar

## Actual result 
The placeholders are off center

## Expected result
It shouldn't be.

## Issue reproduces how often 
Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Not tested
- Can you reproduce this issue with the current Play Store Beta version? Not tested
- Can you reproduce this issue with the current Play Store Nightly version? Yes, 1.41.14

## Device details
   - Install type (ARM, x86): ARM 64
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: Android 11
   
## Brave version
Nightly 1.41.14

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No, Chrome doesn't have this afaik

### Additional information

![Screenshot_20220526-161239_Brave_-_Nightly](https://user-images.githubusercontent.com/20620901/170457996-165dcf1a-759f-449e-a3a6-611f9dc9cc10.png)

**Comment by intrnl** [comment]
It looks like non-placeholder ones are also affected now as of recent Nightly releases.

![Screenshot_2022-08-25-08-29-54-34_82cebf612ef3f9a8762672c971adaed4](https://user-images.githubusercontent.com/20620901/186553574-443b3113-1d4a-4907-86a6-5cea9380e9c5.jpg)

**Comment by urbenlegend** [comment]
Yep I've been seeing this for a while on Android as well.

**Comment by intrnl** [comment]
Seems like this is no longer happening as of Nightly 1.46.32

Closing for now.
