### ISSUE TITLE
[VPN] Crash: Android 6 VPN vector image 

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#23063]
## Description 
It looks like on Android 6 VPN is just crashing as something is wrong with a vector image there.

## Steps to Reproduce

   1. Open settings menu on Android 6 device.

## Actual result:
App crashes.

## Expected result:
Settings menu opens.

## Reproduces how often: 
Easily reproduced

**Comment by LaurenWags** [comment]
Verified using Asus Zenfone (x86) running Android 6 with 1.39.112.

* Reproduced crash opening Settings via 3 dots menu with `1.39.111` (installed from GitHub)
* Confirmed no crash when opening Settings via 3 dots menu with `1.39.112` using upgraded or clean profiles
* Confirmed no mention of VPN on 3 dots menu with `1.39.112` using upgraded or clean profiles
* Confirmed no mention of VPN in Settings with `1.39.112` using upgraded or clean profiles

**Comment by kjozwiak** [comment]
@deeppandya also verified that Brave wasn't crashing anymore using his `Android 6` device and ensured that `VPN` was disabled.
