### ISSUE TITLE
Settings should not be available in private windows with Tor

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#2306]
It's not possible to open a settings page ([brave://settings](brave://settings)) in a private window. If you try, or use any menus &c to open settings, you instead open that settings page in a regular non-private window. Because windows with Tor are implemented on top of guest windows, this behavior doesn't apply. It should.

**Comment by rebron** [comment]
@toml Right now in release we're showing a blank settings page in a private window with Tor. Do we want to redirect to a normal window brave:/settings tab?

**Comment by tomlowenthal** [comment]
Yes, that should redirect to a normal window.

**Comment by agulab** [comment]
Using Settings in TOR browser, I had configured a Search Engine for an onion site that's really useful. Now I can't access that configuration, even though that Search Engine is still configured and I can use it. I tried to configure it in another computer and couldn't. I added it in regular Settings' Search Engine but it doesn't work in TOR browser, even after a computer restart. Have we lost that functionality? Onion site Search Engine configuration was something REALLY useful and as I said, it seems to be in a middle state now, where I can't configure it but it remains from when I could...

**Comment by tomlowenthal** [comment]
Tor windows don't currently have their own persistent settings. They're built on top of guest windows, which use a blank profile and are fully ephemeral. There's ongoing work to port Tor windows to the incognito profile model, at which point all your saved search engines will be available in Tor windows.

**Comment by yrliou** [comment]
It is fixed by https://github.com/brave/brave-core/pull/3319, now we'll open the settings page in the original regular profile, and global settings in Tor are inherited from it.
