### ISSUE TITLE
[Android] Search Engine Default Promo

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#23062]
**Spec**
https://bravesoftware.slack.com/archives/C02SC5AKTAS/p1653579929433229

**Comment by anthonypkeane** [comment]
QA Note: Please note we got a small design change (just text it seems) on this issue. @deeppandya will link that issue to here once created.

**Comment by kjozwiak** [comment]
STR/Cases for @brave/qa-team can be found via https://github.com/brave/brave-core/pull/14350#issue-1319129566 & https://github.com/brave/brave-core/pull/14350#issuecomment-1231063327.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+` running `Android 12` using the following build(s):

```
Brave | 1.43.87 Chromium: 105.0.5195.68 (Official Build) (32-bit)
--- | ---
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | Android 12; Build/SP1A.210812.016
```

### `Test Case #1` (Supported Regions - US/CA/DE/FR/UK/AT/ES/MX)

* installed `1.43.87 Chromium: 105.0.5195.68`
* ensured that the system language is set to either `US`, `CA`, `DE`, `FR`, `UK`, `AT`, `ES` or `MX`
* launched brave and changed the default SE from `Brave` to anything else within the list (Google, DDG, Startpage etc..)
* added `--enable-features=BraveSearchOmniboxBanner` into `Command Line String` via `QA Preferences`
* re-launched the browser tapped on the URL bar and ensured that the Brave search promo is displayed via the omnibox
* ensured that the Brave search promo appears when tapping/editing a URL and the promo hasn't been closed/dismissed
* ensured that the Brave search promo doesn't appear if `Private` is set to another SE but `Standard` is still selected as `Brave`
* ensured that tapping on `Maybe Later` closes the promo within the omnibox and doesn't appear again within the session
  * ensured that it doesn't appear via the omnibox via NTP when starting to enter a URL/search term
  * ensured that tapping on a URL in an existing tab doesn't display the promo
* ensured that tapping on `Try Brave Search` opens `https://search.brave.com/search?q=motorsport&action=makeDefault`
  * ensured that the search term is also appended as per `search?q=motorsport`
  * ensured that tapping on `Try Brave Search` adds `action=makeDefault` into the URL

**`Germany`**

**`Example`** | **`Example`** | **`Example`** |  **`Example`** | **`Example`** | **`Example`** 
---------------|-----------------|----------------|----------------|-----------------|---------------
![Screenshot_20220901-010515_Brave](https://user-images.githubusercontent.com/2602313/187836694-10a87419-94c2-4c9f-a894-2b4624b0d521.jpg) | ![Screenshot_20220901-010620_Brave](https://user-images.githubusercontent.com/2602313/187836722-9927e883-ade0-445f-a950-2c9d56b377c6.jpg) | ![Screenshot_20220901-010634_Brave](https://user-images.githubusercontent.com/2602313/187836729-ff0e663a-bd6f-4f95-8b8c-c2d1ec869c68.jpg) | ![Screenshot_20220901-010715_Brave](https://user-images.githubusercontent.com/2602313/187836767-0bf872bc-6240-40fe-821a-d5494ec8e791.jpg) | ![Screenshot_20220901-010738_Brave](https://user-images.githubusercontent.com/2602313/187836773-b0b8125e-32f4-4841-b1d4-b3904296dec0.jpg) | ![Screenshot_20220901-010747_Brave](https://user-images.githubusercontent.com/2602313/187836779-b0d40b7e-c05f-4576-9b9e-2629149b73d9.jpg)

**`UK`**

**`Example`** | **`Example`** | **`Example`** |  **`Example`** | **`Example`** | **`Example`** 
---------------|-----------------|----------------|----------------|-----------------|---------------
![Screenshot_20220901-012036_Brave](https://user-images.githubusercontent.com/2602313/187837941-94fa883b-4257-4dce-82e3-ca27f420464b.jpg) | ![Screenshot_20220901-012110_Brave](https://user-images.githubusercontent.com/2602313/187837942-5ac0e1fe-9ead-4774-be52-2d25bcb5db26.jpg) | ![Screenshot_20220901-012120_Brave](https://user-images.githubusercontent.com/2602313/187837949-7969048d-47c5-4d06-b4fc-06d3f9be0bec.jpg) | ![Screenshot_20220901-012159_Brave](https://user-images.githubusercontent.com/2602313/187837959-a94228b7-430f-46e1-84c2-90865badf7bc.jpg) | ![Screenshot_20220901-012214_Brave](https://user-images.githubusercontent.com/2602313/187837976-6d168cfb-35d0-42c5-96e5-367b9e6468a3.jpg) | ![Screenshot_20220901-012220_Brave](https://user-images.githubusercontent.com/2602313/187837981-5930bd49-25af-4270-adf7-6475ccaab49c.jpg)

### `Test Case #2` (Regions that don't have Brave Search as default SE/Still use SE onboarding)

* installed `1.43.87 Chromium: 105.0.5195.68`
* ensured that the system language is set to the correct locale (in this case, `Poland`)
* launched brave and added `--enable-features=BraveSearchOmniboxBanner` into `Command Line String` via `QA Preferences`
* re-launched the browser tapped on the URL bar twice and ensured that the SE onboarding screen is displayed
* ensured that Google was selected as the default via the onboarding screen
* ensured that Google is default SE for both `Standard` & `Private` windows once the onboarding screen has been dismissed
* ensured that the Brave search promo isn't appearing via the omnibox when a text/search term is entered

**`Poland`**

**`Example`** | **`Example`** | **`Example`** |  **`Example`**
---------------|-----------------|----------------|----------------
![Screenshot_20220901-013337_Brave](https://user-images.githubusercontent.com/2602313/187839109-cb088874-22fd-4376-a139-40f452ae9d90.jpg) | ![Screenshot_20220901-013349_Brave](https://user-images.githubusercontent.com/2602313/187839118-467311d4-f314-48f1-b726-703ffc5dbfc8.jpg) | ![Screenshot_20220901-013400_Brave](https://user-images.githubusercontent.com/2602313/187839122-cf45f295-923e-4d76-a52a-49a48e3dcfb7.jpg) | ![Screenshot_20220901-013407_Brave](https://user-images.githubusercontent.com/2602313/187839126-26113c69-e363-4b47-a99e-3468dff64a37.jpg)

### `Test Case #3` (Maybe Later & Dismiss)

* ensured that closing the Brave search promo via `Maybe Later` doesn't re-appear in the same session
  * ensure the promo is not re-appearing when typing into the omnibox via NTP
  * ensure the promo  is not re-appearing when taping on a URL on an existing opened tab
* ensured that the promo re-appears again when the browser is re-launched after tapping on `Maybe Later`
  * ensure that the `Dismiss` button is visible and not the `Maybe Later` as per https://github.com/brave/brave-core/pull/14350#issue-1319129566
* ensured that once a user taps/clicks on `Dismiss`, the promo never re-appears (tried via several re-launches)

**`Example`** | **`Example`** | **`Example`** |  **`Example`**
---------------|-----------------|----------------|----------------
![Screenshot_20220901-012942_Brave](https://user-images.githubusercontent.com/2602313/187838567-e2915cd2-0407-41d8-a4e2-c8dc3879c1d7.jpg) | ![Screenshot_20220901-012946_Brave](https://user-images.githubusercontent.com/2602313/187838580-d29902db-84b1-4188-9913-40989af175c5.jpg) | ![Screenshot_20220901-012955_Brave](https://user-images.githubusercontent.com/2602313/187838586-a8ebf3cc-e695-4bd3-a1a2-f065229158f9.jpg) | ![Screenshot_20220901-012958_Brave](https://user-images.githubusercontent.com/2602313/187838589-1beb9e2d-6faf-4a46-a860-206b7fe59dd7.jpg)

### `Test Case #4` (Automatically dismiss after 15 days)

* installed `1.43.87 Chromium: 105.0.5195.68`
* ensured that the system language is set to either `US`, `CA`, `DE`, `FR`, `UK`, `AT`, `ES` or `MX`
* launched brave and changed the default SE from `Brave` to anything else within the list (Google, DDG, Startpage etc..)
* added `--enable-features=BraveSearchOmniboxBanner` into `Command Line String` via `QA Preferences`
* re-launched the browser tapped on the URL bar and ensured that the Brave search promo is displayed via the omnibox
* moved the time/date on the device ahead ~16 days and re-launched the browser
* ensured that the Brave search promo doesn't appear via the omnibox when tapping via NTP
* ensured that the Brave search promo doesn't appear when tapping on the omnibox if an already opened tab
