### ISSUE TITLE
VPN disconnects after upgrading app via Playstore

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23071]
## Description 
VPN disconnects after upgrading app via Playstore

## Steps to reproduce 

   1. Install 1.39.111 and subscribe for VPN
   2. Connect to a preferred or nearest location
   3. Update to 1.39.112 via PlayStore
   4. System is disconnected from VPN
   5. Launching browser and selecting VPN automatically reconnects to the previous location

## Actual result 
VPN disconnects after upgrading app via Playstore

## Expected result
Should not disconnect when upgrading the App

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Most likely Yes
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 12
   
## Brave version
1.39.112

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @deeppandya @Uni-verse @kjozwiak @bsclifton @mattmcalister

**Comment by deeppandya** [comment]
@srirambv its the default behaviour for any app as during the upgrade we are replacing the package.

**Comment by srirambv** [comment]
Closing the issue based on previous comment. Can reopen if required
