### ISSUE TITLE
DApps: Improve account switch transition in panel

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23079]
## Description 
Improve account switch transition in panel

## Steps to reproduce 

   1. Create wallet and have multiple accounts created
   2. Trigger wallet icon in URL bar
   3. Select Accounts, has a weird transition where both accounts are selected before the panel closes

## Actual result 

https://user-images.githubusercontent.com/17010094/170487834-107302e0-97c7-4d9b-af13-b6071e6003ff.mp4

## Expected result
Have a more smoother/fluid transition when selecting accounts 

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version?NA

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 12
   
## Brave version
Custom Build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @Pavneet-Sing @qamarngr @SergeyZhukovsky

**Comment by Pavneet-Sing** [comment]
DApps UI is yet to be polished so I think we can keep [a single list of issues to keep track of minor UI changes](https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1652880653525139?thread_ts=1652851949.648739&cid=C023VS4HJ6Q)?

**Comment by Pavneet-Sing** [comment]
Note: Reassigning to @qamarngr as he has the bandwidth to work on it. [The whole list can be update at once with notifyDataSetChanged but the catch is to avoid the flicker](https://bravesoftware.slack.com/archives/C02SC5AKTAS/p1653568133033729?thread_ts=1653566500.573419&cid=C02SC5AKTAS).

**Comment by srirambv** [comment]
Removing milestone as this is not yet fixed on master

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.48.155 x64 build
- Verified account change transition is smooth on both wallet panel and on wallet screen
- Verified test networks are nested inside of the main network name for both Solana and Ethereum
- Verified changing network via panel and via wallet home page works as expected 
- Verified changing account from picker updates the network as expected

Oppo Reno 5 (Android 13) | Lenovo Tab (Android 12)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/216881422-b16c5389-088e-429f-bc20-86f6f6897021.mp4> | <video src=https://user-images.githubusercontent.com/17010094/216881443-2ba4a7eb-99de-49ee-9eac-779ce1d60431.mp4>
