### ISSUE TITLE
VPN auto-disconnects when device goes to sleep/auto-lock

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23070]
## Description 

VPN auto-disconnects when device goes to sleep/auto-lock

## Test plan / Steps to Reproduce

   1. Install VPN profile on macOS and auto-connect to a preferred location
   2. Set device to turn off display after half hour so it goes into lock screen
   3. Keep the device idle after display turns off (say half hour)
   4. Unlock device 

## Actual result:
System isn't connected to VPN anymore
VPN auto-disconnects when device goes to sleep/auto-lock

## Expected result:
Should not disconnect from VPN

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.41.14 Chromium: 102.0.5005.61 (Official Build) nightly (arm64)
-- | --
Revision | `0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}`
OS | macOS Version 12.4 (Build 21F79)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @bsclifton @simonhong @spylogsster

**Comment by spylogsster** [comment]
unable to reproduce, @GeetaSarvadnya can you recheck pls? thanks

**Comment by stephendonner** [comment]
## Verified `PASSED` using 


Brave | 1.43.71 Chromium: 104.0.5112.81 (Official Build) beta (x86_64)
--|--
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | macOS Version 13.0 (Build 22A5321d)

### Steps:

1. installed `1.43.71`
2. launched Brave
3. opened `brave://flags/`
4. toggled `Enable experimental Brave VPN` to `Enabled`
5. toggled `Enable experimental SKU SDK` to `Enabled`
6. restarted Brave
7. loaded `account.bravesoftware.com`
8. entered basic auth
9. entered issue23070@mailinator.com and clicked `Get login link`
10. clicked on the link in the email
11. clicked on `Browse plans`
12. scrolled down and clicked on `Buy now` for Brave VPN
13. completed the Stripe checkout
14. connected to VPN
15. configured lockscreen w/password and screensaver, set to 30 minutes
16. waited 30 minutes for lock screen
17. waited another 30 minutes for good measure
18. entered OS password
19. checked VPN connection status

#### Confirmed I was still connected

OS settings | after unlocking (~4:04 pm PDT)
---|----------------
<img width="827" alt="Screenshot 2022-08-17 at 2 55 14 PM" src="https://user-images.githubusercontent.com/387249/185258676-59c20327-c30f-45bc-92d7-ac382f412122.png"> | <img width="1680" alt="Screenshot 2022-08-17 at 3 57 01 PM" src="https://user-images.githubusercontent.com/387249/185258711-23a7f69f-7b31-40fd-8d5b-189c1aecf7a7.png">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.43.73 Chromium: 104.0.5112.81 (Official Build) beta (64-bit)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | Windows 11 Version 21H2 (Build 22000.856)
```

Reproduced the issue in `1.41.14`

Ex1|Ex2
----|----
<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/185282557-866bbe25-13e4-464c-83e2-c0c7a02f8c44.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/185282581-01ff63ff-b5e2-4afb-8734-994e045fa1a5.png">


1. installed `1.43.73`
2. launched Brave
3. opened `brave://flags/`
4. toggled `Enable experimental Brave VPN` to `Enabled`
5. toggled `Enable experimental SKU SDK` to `Enabled`
6. restarted Brave
7. loaded `account.bravesoftware.com` (staging)
8. enter credentials from 1Password
9. enter a unique test email address (e.g. vpn-test-0823@mailinator.com) and click Get login link
10. clicked on the link in the email
11. clicked on `Browse plans`
12. scrolled down and clicked on `Buy now` for Brave VPN
13. completed the Stripe checkout
14. connected to VPN
15. configured to put the device to sleep and turn off the display after for 30 minutes in settings
16. waited 30 minutes to lock the screen and stayed idle another 30 minutes 
17. unlocked my machine
18. checked VPN-connection status

#### Confirmed still connected

Step 15-16|Results
-----|------
<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/185281966-1876be28-3734-46d1-b429-ee6bd50da34f.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/185282157-4b9d50a1-4de8-468d-98c9-f5950b656cb2.png">

**Comment by srirambv** [comment]
Just adding a note, This is working fine for me as well on staging. VPN isn't disconnected when device goes to sleep/auto-lock
