### ISSUE TITLE
Install config graphic is not centered 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23074]
## Description 
Install config graphic is not centered 

## Steps to reproduce 

   1. Purchase VPN and try to install the config
   2. Wait till the logo shows up
   3. The lock icon is not centered 

## Actual result 
<img width=300 src=https://user-images.githubusercontent.com/17010094/170469519-56f462ba-bd10-4f9f-bbed-c2aa809f0466.png>

## Expected result
Graphic should be centered

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 12
   
## Brave version
1.39.112

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @deeppandya @Uni-verse @kjozwiak

**Comment by kjozwiak** [comment]
Just adding more info/examples of this being more visible while using a tablet. Example:

![Screenshot_20220614-013659_Brave](https://user-images.githubusercontent.com/2602313/173501568-d7d925fc-263a-4164-a7bc-4e3f5295d3a4.jpg)

**Comment by Uni-verse** [comment]
Verified on `Samsung GS 21` & `Samsung Tab S7` using 

```
Brave	1.42.80 Chromium: 104.0.5112.57 (Official Build) (64-bit) 
Revision	212fd173a0da1e0a024f328295bb56a2529190bb-refs/branch-heads/5112@{#1042}
OS	Android 12; Build/SP1A.210812.016
```

- Verified config graphic is centered in the modal

Mobile | Tablet
-|-
![screenshot-1658880267711](https://user-images.githubusercontent.com/17885425/181132912-6fddb8aa-3b87-49d5-9196-f5127df6c636.png) | ![screenshot-1658880421601](https://user-images.githubusercontent.com/17885425/181133012-ed3d82e9-ad95-432b-9302-725777d53024.png)
