### ISSUE TITLE
VPN shows connected when in fact its disconnected

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23073]
## Description 
VPN shows connected when in fact its disconnected

## Steps to reproduce 

   1. Purchase subscription and enable VPN
   2. Enable Always ON from device settings
   3. Enable Block network option
   4. Remove Brave from memory/recent app list
   5. Switch locale and region to something else
   6. VPN auto reconnects open Brave and check IP still connected to VPN
   7. Quit browser/remove from memory/recent app list
   8. Change back to locale/region of subscription purchase
   9. System VPN notification shows connected, Browser also shows VPN connected but checking IP shows local IP

## Actual result 
VPN shows connected when in fact its disconnected

## Expected result
Should be connected to VPN even if device locale/region is changed 

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 12
   
## Brave version
1.39.112

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @deeppandya @brave/legacy_qa @mattmcalister @anthonypkeane @bsclifton

**Comment by deeppandya** [comment]
@srirambv what you post the screenshot of it ? Are you talking about the lock icon in the notification tray ? It shows up when you have always on enabled. It doesnt mean vpn is connected.

**Comment by deeppandya** [comment]
@srirambv what you post the screenshot of it ? Are you talking about the lock icon in the notification tray ? It shows up when you have always on enabled. It doesnt mean vpn is connected.

**Comment by srirambv** [comment]
@deeppandya  actually I missed taking screenshot of it. I didn't have VPN icon in notification area but the VPN button on menu was enabled but when I checked the IP it was showing local IP not the one set in VPN

**Comment by timchilds** [comment]
@Sam-Sibley could you please help with the designs here? We basically want to add a VPN settings option that helps guide users towards an Android device setting which enables a kill switch. When that kill switch is enabled it will help with scenarios like the one described in the ticket description. I'll slack you a video of how another VPN product handles this setting.

**Comment by deeppandya** [comment]
@srirambv this issue should be fixed with https://github.com/brave/brave-core/pull/19576. would it be possible to verify and close the issue ?

**Comment by srirambv** [comment]
This is fixed now. closing as stale
