### ISSUE TITLE
VPN pricing is not shown

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23076]
## Description 
VPN pricing is not shown

## Steps to reproduce 
TBD 

## Actual result 
<img width=400 src=https://user-images.githubusercontent.com/17010094/170470593-5018cbe5-f648-4d9d-bb27-9023a6822460.png>

## Expected result
Always show the pricing

## Issue reproduces how often 
Difficult as there is no steps

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 12
   
## Brave version
1.39.112

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @deeppandya @Uni-verse @kjozwiak @bsclifton

**Comment by deeppandya** [comment]
@srirambv it happens when for some reason we are unable to fetch the pricing from google api. And in your case, you have blocked the connection without VPN so there is not internet connection to get the prices.

**Comment by srirambv** [comment]
Closing based on the above comment
