### ISSUE TITLE
VPN disconnects when region is changed

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23072]
## Description 
VPN disconnects when region is changed

## Steps to reproduce 

   1. Clean install and restore VPN subscription
   2. Connect to a specific or nearest location
   3. Remove app from memory
   4. Change Region to US (not language)
   5. Start Browser, VPN is disconnected
   

## Actual result 
VPN disconnects when region is changed

## Expected result
Shouldn't disconnect VPN unless manually done

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version? 

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 12
   
## Brave version
1.39.112

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @deeppandya @brave/legacy_qa @bsclifton @anthonypkeane

**Comment by deeppandya** [comment]
@srirambv whenever someone opens the application, we check for valid subscription. And we check it with google play api. When you change the region, google api needs reset and that's why it return invalid subscription response.

**Comment by srirambv** [comment]
Closing based on the above. Can reopen the issue if required
