### ISSUE TITLE
Use current filecoin network instead of selector

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#23078]
## Description 

In the import dialog for Filecoin Ledger need to remove Network selector and use current FIL network instead 

<img width="792" alt="image" src="https://user-images.githubusercontent.com/2965009/170473481-8059676d-26c7-4a10-a4d9-9f6cc9f91a72.png">

**Comment by kjozwiak** [comment]
The above will require `1.40.89` or higher for `1.40.x` verification 👍

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.40.96 Chromium: 102.0.5005.115 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>174dbe6e33bc81994fceb71d751be201d0b4803d-refs/branch-heads/5005_109@{#3}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.708)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/13523>brave/brave-core#13523</a></li>
         <li>Verified imported Filecoin accounts only lists the current selected Filecoin networks</li>
         <li>Verified when a different network/EVM is selected it just retains the previous Filecoin network accounts</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/173803334-2639bbef-5821-464b-bc6f-c8ae5ad0f094.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/173769935-30e73f9a-0f2d-4ec7-8e6b-501b2a5c0444.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/173771813-5a07dd72-bbd7-4cb7-9ff2-2e85a9e97a83.mov>
      </td>
   </tr>
</table>
