### ISSUE TITLE
Reset config message reads `vpn` instead of `VPN`

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23075]
## Description 
Reset config message reads `vpn` instead of `VPN`

## Steps to reproduce 

   1. Install a VPN profile
   2. Open settings -> VPN -> Reset configuration
   3. Message reads `vpn` instead of `VPN`

## Actual result 
<img width=400 src=https://user-images.githubusercontent.com/17010094/170470098-2ebf466d-91e1-4a5e-84e0-3558e3ef6538.png>

## Expected result
Proper casing for VPN

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 12
   
## Brave version
1.39.112

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @deeppandya @rmcfadden3 @Uni-verse @kjozwiak @bsclifton

**Comment by kjozwiak** [comment]
The above will require `1.40.91` or higher for `1.40.x` verification 👍

**Comment by Uni-verse** [comment]
Verified `PASSED` on` Samsung GS 21` & `Tab S7 using `

```
Brave	1.40.96 Chromium: 102.0.5005.115 (Official Build) beta (64-bit) 
Revision	174dbe6e33bc81994fceb71d751be201d0b4803d-refs/branch-heads/5005_109@{#3}
OS	Android 12; Build/SP1A.210812.016
```

- Verified copy change in the reset config prompt using STR from https://github.com/brave/brave-browser/issues/23075#issue-1249390292

1 | 2 | 3
-|-|-
![screenshot-1655253265109](https://user-images.githubusercontent.com/17885425/173712250-051939e6-c97b-44f4-9b34-13d2f7b55c59.png) | ![screenshot-1655253219165](https://user-images.githubusercontent.com/17885425/173712246-bc798dd5-5c98-4fa6-a039-a7d590e800ab.png) |  ![screenshot-1655253291592](https://user-images.githubusercontent.com/17885425/173712252-5ef24707-0412-4d8b-9ff7-6db052e7ded4.png)
