### ISSUE TITLE
Shields only shows one number when there are `99+` items blocked

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23085]
## Description 

Shields only shows one number when there are `99+` items blocked

## Steps to Reproduce

   1. Visit a page so blocked items on Shields go beyond 100
   2. See shields, only shows `9...` instead of `99+`

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/170519175-dda8d970-8380-4313-9f50-66b34705d2e5.png)

## Expected result:
Should show `99+` in shields 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.39.111 Chromium: 102.0.5005.61 (Official Build) (arm64) 
-- | --
Revision | `0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron @nullhook

**Comment by stephendonner** [comment]
See discussion in https://bravesoftware.slack.com/archives/CD495CWLR/p1647039657532839.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.45.75 Chromium: 106.0.5249.65 (Official Build) beta (x86_64)
-- | --
Revision | 3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}
OS | macOS Version 11.7 (Build 20G817)

### Steps:
1. installed `1.45.75`
2. launched Brave
3. loaded `https://apps.facebook.com/wordswithfriends/?ref=bookmarks&fb_source=web_shortcut&count=0`
4. logged in to Facebook
5. switched Shields to `Aggressively block trackers & ads` (to increase the blocked count more quickly)
6. waited for blocked counts to rise
7. looked at the `99+` counter on the Shields icon/Brave logo

#### Confirmed `99+` was legible, both in `Light` and `Dark` modes

`Light` mode | `Dark` mode
--------------|--------------
<img width="449" alt="Screen Shot 2022-09-27 at 4 48 00 PM" src="https://user-images.githubusercontent.com/387249/192632428-63baca7c-3afc-4888-a0cd-a180e667a19d.png"> | <img width="440" alt="Screen Shot 2022-09-27 at 4 48 19 PM" src="https://user-images.githubusercontent.com/387249/192632430-2b03363b-c3af-4378-9918-24bb3c8ae4af.png">
