### ISSUE TITLE
VPN status doesn't show the connected state when brave is auto-upgraded

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#23080]
## Description 

VPN status doesn't show connected state when brave is auto-upgraded from `1.40.68` to `1.40.75`

## Steps to Reproduce

   1. Clean profile 1.40.68
   2. Follow the steps to connect VPN 
   3. Make sure VPN is connected
   4. Open brave://settings/help wait for the update and click on `Relaunch`
   5. After upgrading to `1.40.75` VPN status doesn't show the connected state also encountered https://github.com/brave/brave-browser/issues/22726

## Actual result:

VPN status doesn't show the connected state when brave is auto-upgraded from `1.40.68` to `1.40.75`

1.40.68 | 1.40.75
-- | --
![image](https://user-images.githubusercontent.com/38657976/170488256-723273fe-2c5e-4fe4-a456-9ede7b3085f1.png) | ![image](https://user-images.githubusercontent.com/38657976/170488339-5208fdde-5fa8-4d3c-bfd1-90ef4ffa79a6.png)

## Expected result:
VPN status should show the connected state when brave is auto-upgraded from `1.40.68` to `1.40.75`

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.40.75 Chromium: 102.0.5005.61 (Official Build) beta (64-bit)
-- | --
Revision | 0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}
OS | Windows 10 Version 21H2 (Build 19044.1706)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @simonhong @bsclifton @spylogsster @brave/qa-team

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```

Brave | 1.41.39 Chromium: 102.0.5005.78 (Official Build) nightly (64-bit)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | Windows 10 Version 21H2 (Build 19044.1706)

```
- Verified the STR from the description and ensured the following:
   - Confirmed VPN status is connected in an upgraded profile
   - Confirmed VPN connected status is retained after the browser restart
   - Confirmed VPN can be connected to other regions and status stays connected even after browser restart

1.41.34 | 1.41.45
-- | --
![image](https://user-images.githubusercontent.com/38657976/172777569-441c68cc-afac-4f70-8a41-c6640e946a73.png)

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.41.55 Chromium: 102.0.5005.115 (Official Build) nightly (x86_64)
-- | --
Revision | 174dbe6e33bc81994fceb71d751be201d0b4803d-refs/branch-heads/5005_109@{#3}
OS | macOS Version 12.5 (Build 21G5037d)

### Steps:
1. installed `1.41.49`
2. launched Brave
3. set up VPN via dev (`account.brave.software`)
4. ensured I connected to `USA (West)` region successfully
5. opened `brave://settings/help` and confirmed it found an update
6. clicked on `Restart` to restart the browser
7. confirmed VPN was still connected

`1.41.49` | `1.41.55`
----------|----------
<img width="1312" alt="Screen Shot 2022-06-11 at 12 52 29 AM" src="https://user-images.githubusercontent.com/387249/173179095-3f09833a-94ed-4860-9663-4d4361d785c3.png"> | <img width="1312" alt="Screen Shot 2022-06-11 at 12 52 45 AM" src="https://user-images.githubusercontent.com/387249/173179101-9ed42ed3-918f-4620-acdb-ca249daa05c1.png">
