### ISSUE TITLE
Disable VPN feature for android 7

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#23089]
This issue is to restrict vpn feature for android 7.  

Test Plan : 

We shouldn't have any menu item or settings related to vpn.

**Comment by kjozwiak** [comment]
While using `1.39.113 Chromium 102.0.5005.61`, @LaurenWags went through the following to ensure that `VPN` was disabled on `Android 7` as per the following:

```
Verification **PASSED** on `Samsung Galaxy J7 Neo (ARM)` running `Android 7` as per the following:

* Confirmed no mention of VPN on menu or in Settings with clean install of 1.39.113
* Installed 1.38.119 (pre-VPN), upgraded to 1.39.113, confirmed no mention of VPN on menu or in Settings
* Installed 1.39.111 and saw VPN on menu/in Settings, upgraded to 1.39.113, confirmed no mention of VPN on menu or in Settings
```

@deeppandya also confirmed that `VPN was disabled on his `Android 7` device via Slack.
