### ISSUE TITLE
Implement linking limit solution for bitFlyer (remove linking limits)

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#23083]
## Description

Followup to https://github.com/brave/brave-browser/issues/18572 to remove linking limits for bitFlyer as well.

**Comment by tallthom** [comment]
Thank you for opening this...

**Comment by tallthom** [comment]
When this goes live, I'll be happy to report back on how it works. Please keep us posted. Thanks for all the efforts!

**Comment by tallthom** [comment]
Any news on this issue? Is it really challenging after making Uphold and Gemini limitless? Just curious about why there is such a delay.

**Comment by Miyayes** [comment]
@tallthom If you need help in the meantime, I can help you. You can send me the brave://rewards-internals (general info) of one of your devices that is *successfully* linked to bitFlyer to christopher at brave dot com. 

That said, this issue in progress now.

**Comment by tallthom** [comment]
Thank you for working on this issue, @Miyayes -- I really appreciate it.

Unfortunately, I checked all my devices, all my profiles, and none of them are linked to bitflyer as far as I can see. In the process of reinstalling machines and migrating information, I seem to have disconnected each one of my browsers. If I could log into my instances and "see" which machines have got "stale" connections, I could be more helpful to you... 

Apologies for that. If there is anything else I might be able to do to provide assistance, please let me know.

Again, thanks for working on it.

**Comment by Miyayes** [comment]
Hi @tallthom, I should still be able to help you in the meantime if you do this:

1. enable brave://flags > rewards verbose logging
2. restart browser
3. Try verifying with bitFlyer again
4. It will fail, but that's fine. Once that happens, go to brave://rewards-internals > logs, and download full logs
5. Email those logs to me at christopher at brave dot com

**Comment by tallthom** [comment]
It has been quite a while... are there any updates on this issue? Apologies @Miyayes for continuing to harp on this, but I'd really love to have access to BitFlyer from any Brave browser I'm using.

If the issue is not going to be resolved, I would also like to know that as well. Thanks in advance for any updates.

**Comment by Miyayes** [comment]
@tallthom It's still actively in progress, and it should be getting resolved. We're waiting on confirmation on our partner at this time.

**Comment by tallthom** [comment]
Thanks for the update! I hope the partner responds in a timely manner.

**Comment by tallthom** [comment]
I was suddenly able to connect to my BitFlyer accounts on two browsers this morning... Has this issue been added to the latest build/release? If so, it appears to be working now! Do you need me to test more? I can do that...

**Comment by tallthom** [comment]
Thank you very much, Chris! Thanks to you and all the Brave team. Very happy about this.
