### ISSUE TITLE
Disintermediate requests for common web assets

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#2308]
The [Decentraleyes](https://decentraleyes.org/) extension intercepts requests for commonly-CDN'd web resources like `jquery` and serves from a local cache instead, removing the need for a network transaction. This improves privacy since there's no outbound request to log, security since there's no way to tamper with a request which isn't made, and performance since reading from disk is faster than a network request.

We could implement an extended variant of this with two broad approaches.

We could curate a list (like Decentraleyes') of content that is consistently loaded from CDNs. When a request is made for these assets, instead return the local version. This list and these assets are distributed and updated just like our other blocklists.

Any time we see a reference to a resource with an SRI hash, we cache that resource indefinitely. Any future requests for a resource with the same hash are loaded from disk, regardless of URI. We could drop resources from the cache after an extended duration (months?) or when we start seeing consistent references to a resource at the same URI with a different hash.

**Comment by mwarrenus** [comment]
Decentraleyes provides a list of hosts for which it provides local CDN services.  Is there a place to list these hosts within Brave (perhaps within brave://settings, "Brave shields defaults" or under brave://flags?).  Here are the uBlock Origin rules/list of hosts Decentraleyes covers:

```
* ajax.googleapis.com * noop
* ajax.aspnetcdn.com * noop
* ajax.microsoft.com * noop
* cdnjs.cloudflare.com * noop
* code.jquery.com * noop
* cdn.jsdelivr.net * noop
* yastatic.net * noop
* yandex.st * noop
* apps.bdimg.com * noop
* libs.baidu.com * noop
* lib.sinaapp.com * noop
* upcdn.b0.upaiyun.com * noop
* cdn.bootcss.com * noop
* sdn.geekzu.org * noop
* ajax.proxy.ustclug.org * noop

```

**Comment by tomlowenthal** [comment]
@mwarrenus Not sure what you're asking for?

**Comment by mwarrenus** [comment]
The Decentraleyes extension can already disintermediate requests for common web assets, however, the Brave browser apparently has  a (hidden?) set of rules that blocks requests to these assets before they get to Decentraleyes. I’d like to modify Brave browser’s block list/rules to allow requests to the above set of domains to pass through to Decentraleyes (I’ve installed the extension in Brave, but Brave isn’t passing any requests to the extension).  

This might be easier to implement than the full disintermediation project.

**Comment by tomlowenthal** [comment]
If we're going to do work to support Decentraleyes, it'll be to integrate the functionality directly. This is on the to-do list.

**Comment by tomlowenthal** [comment]
It seems like the next step is to run a crawl and identify the common libraries/files which are used most frequently across sites. That seems like a task for @snyderp?

**Comment by superusercode** [comment]
![image](https://user-images.githubusercontent.com/60588434/75612555-9cf35680-5af2-11ea-9de4-d16358c772aa.png)
I think for the time being the basic list included by decentraleyes would be good enough (as there aren't any other extensions out there that do this as far as I am aware).

**Comment by pes10k** [comment]
The current plan is for @antonok-edm and I to use PageGraph and the existing resource-replacement adblock-rs code to automatically build proxies for these widgets, so that

1. we don't need to add any new shipping machinery 
2. we can programmatically rebuild these local replacements
3. we can confidently fetch downstream resources (which the PageGraph instrumentation will allow us to pick up)
4. we can share the generated replacements with uBO and other tools that have the same capability, both to give back, and to get more people using / reporting on them

**Comment by pes10k** [comment]
As mentioned in https://github.com/brave/brave-browser/issues/11548, it doesn't look like we'll be able to use this approach, bc there is too much interactivity, and too much unpredictability in what these social widgets (and similar) pull in.  https://github.com/brave/brave-browser/issues/11548 gives the new plan for this problem
