### ISSUE TITLE
DApps: Fix dapps wallet panel UI

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#23088]
## Description 
Fix DApps panel UI

- [x] Connected and network selector UI elements' padding, text, and icons
- [x] Change background gradient as per account
- [x] Margin, Padding, textual details and move the account selector arrow inwards if possible
- [x] Fix wallet icon size and theme color
- [x] Apply square styling and shadow on the panel

## Actual result 
![Screenshot from 2022-05-26 22-25-54](https://user-images.githubusercontent.com/11755381/170536956-67ac91a5-a19c-41c5-83fc-68f39f22ed9c.png)

## Expected result (without bottom button panel)

![Screenshot from 2022-05-26 22-20-29](https://user-images.githubusercontent.com/11755381/170692393-aa48cdf1-8b9f-4ce7-9da4-8ede82a89cd8.png)

**Comment by kjozwiak** [comment]
The above will require `1.40.91` or newer for `1.40.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.40.105 x64 build
- Verified steps from [brave/brave-core#13603](https://github.com/brave/brave-core/pull/13603)
- Verified text alignment is correct below the account

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<img width=280 src=https://user-images.githubusercontent.com/17010094/174767462-6dd6ae49-acfc-49a0-9542-2afd812a9da2.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/174767419-e6776fab-8793-40bb-b567-18b3e1825e10.png>
