### ISSUE TITLE
`-32000: replacement transaction underpriced` when trying to submit a transaction

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23098]
## Description 

`-32000: replacement transaction underpriced` when trying to submit a transaction

## Steps to Reproduce

   1. Try to submit a transaction from wallet on 1.41.17
   2. Transaction immediately fails with error
   3. Hover over the info bubble, shows `-32000: replacement transaction underpriced`

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/170650886-769329fb-adef-4f51-a564-4bcf2674dbdf.png)

## Expected result:
Should submit the transaction. And also provide meaning full message for the error

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.41.17 Chromium: 102.0.5005.61 (Official Build) nightly (64-bit)
-- | --
Revision | `0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Not checked
- Can you reproduce this issue with the beta channel? Not checked
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @onyb

**Comment by SergeyZhukovsky** [comment]
@srirambv is this still valid?
