### ISSUE TITLE
Help tips loads blank page on initial load 

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#23090]
## Description 

After loading brave://settings page and selecting `Help tips, blank` page loads. Had to tap second time, to load the entries on the page. 

## Steps to Reproduce

   1. Launch brave
   2. Load `brave://settings` 
   3. Select `Help tips` in the Additional settings
   4. Also load brave://settings/braveHelpTips

## Actual result:

1. Page is blank when loaded brave://settings -->Addtional settings--->Help tips
2. Page is blank for brave://settings/braveHelpTips

## Expected result:
Help tips section should load with following entries
- Show Wayback Machine prompt on 404 pages
- Warn me before closing window with multiple tabs

## Reproduces how often: 

Intermittent issue

<img width="953" alt="image" src="https://user-images.githubusercontent.com/98358127/170561803-e7e3ca70-02bf-4613-90e5-0045813db758.png">

## Brave version (brave://version info)

```
Brave | 1.40.75 Chromium: 102.0.5005.61 (Official Build) beta (64-bit)
-- | --
Revision | 0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}
OS | Windows 11 Version 21H2 (Build 22000.675)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes (1.39.x)
- Can you reproduce this issue with the beta channel? Yes (1.40.x)
- Can you reproduce this issue with the nightly channel? Yes (1.41.x)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
cc: @rebron @simonhong

**Comment by simonhong** [comment]
@MadhaviSeelam I can't repro below first one. I test first one with all channels and loaded properly.
However, Second one is reproduced on all channels.
```
1. Page is blank when loaded brave://settings -->Addtional settings--->Help tips
2. Page is blank for brave://settings/braveHelpTips
```

**Comment by MadhaviSeelam** [comment]
@simonhong - Yes, `1` is an intermittent issue.  I mentioned that in `Reproduces how often` section but forgot to mention in the Actual result.

**Comment by stephendonner** [comment]
Just reproduced this pretty easily with 1.40.82 on macOS-x64.

**Comment by stephendonner** [comment]
There's more (recent) activity here, but https://github.com/brave/brave-browser/issues/22736 was logged first, so which one should we dupe to which?

**Comment by rebron** [comment]
closing. dupe of https://github.com/brave/brave-browser/issues/22736
