### ISSUE TITLE
Add setting to allow separate search engine usage for Private Window

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#23091]
## Description 
Users should be able to specify their search engine of choice in Private Windows. In brave://settings/search, add a new setting under "Search engine used in address bar" to allow users to use a different search engine in Private Windows separate from Normal Windows.

The list for Private Windows should be the same as Normal Windows as specified per locale. 
The default for Private Windows should be Brave Search for all regions.

## Expected Result

   1. Go to brave://settings/search
   2. Be able to select a search engine of choice for Private Windows. For QA, notice that Brave Search is the default choice. Choose a different search engine from that list.
   3. Open a new private window. Notice the favicon upon entering the address bar matches the search engine of choice setting. Perform a search and notice the search results come from the selected search engine from step 2.

## Design:
https://github.com/brave/brave-browser/issues/23091#issuecomment-1138966475

## Brave version (brave://version info)

Targeted for 1.40.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

Related issue: https://github.com/brave/brave-browser/issues/22566
This setting already exists for Android and iOS and should be syncable.

**Comment by simonhong** [comment]
@rebron Should we maintain below UI (ddg toggle button) for some existing users?
![image](https://user-images.githubusercontent.com/6786187/170921807-4117aea6-de52-4776-9320-74bc75c48265.png)

**Comment by simonhong** [comment]
Initial provider:
* for ddg toggle on users: DDG
* all other existing users: normal profile's provider
* fresh user: same provider with normal profile

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.42.62 Chromium: 103.0.5060.114 (Official Build) beta (x86_64)
-- | --
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | macOS Version 13.0 (Build 22A5295i)

### Case one: new profile - `PASSED`
<details>

1. install `1.42.62`
2. launch Brave
3. open `brave://settings/search` and check `Brave` is the listed provider for both `Normal Window` and `Private Window`
4. expand the list and ensure search-engine order and names match the spec (they should be the same between both window types)
5. change `Brave` to `Qwant` for `Private Window`
6. click on the "hamburger" menu and choose `New Private Window`
7. perform a search and confirm you're using `Qwant`
8. perform a search using a `Normal Window` and confirm it uses `Brave`
9. perform a search using a `Private Window with Tor` and confirm it uses `Brave`
10. perform a search using a `Guest Window` and confirm it uses `Brave`
11. opened `brave://settings/searchEngines`
12. clicked on the `pencil` icon to edit `Brave`
13. changed `Brave` to `Bravest`
14. clicked `Save`
15. confirm the name has been updated in both `Window` options list
16. open `brave://settings/reset`
17. click on `Restore settings to their original defaults`
18. confirm by clicking on `Reset settings`
19. confirm default search providers have been restored

</details>


### Case two: migrations - `PENDING`

From `1.41.96` to `1.42.62`
<details>
.
</details>

From `1.40.113` -> `?`
<details>
.
</details>

From `1.30.89` -> `1.41.96` -> `1.42.62`
<details>

**From 1.30.89 (part A, -> 1.41.96)**

1. install `1.30.89`
2. launch Brave
3. open a `New Private Window`
4. toggle `Search with DuckDuckGo` to `On`
5. shut down Brave
6. trigger an update via `brave://settings/help`
7. confirm you get `1.41.96`
8. open a `New Private Window`
9. confirm you see `Search with DuckDuckGo` toggled to `On`
10. perform a search and confirm you are using `DuckDuckGo`

(continued...)

**From 1.41.96 (part B, -> 1.42.62)**

1. (on macOS) rename `Brave-Browser` to `Brave-Browser-Beta`
2. launch `1.42.62`
3. open a `New Private Window`
4. perform a search and confirm you are (still) using `DuckDuckGo`
5. confirm `DuckDuckGo` is selected for `Private Window` on `brave://settings/search`


</details>

### Case three: Sync

Android
<details>
.
</details>

desktop
<details>
.
</details>

iOS
<details>
.
</details>

Android, desktop, iOS
<details>
.
</details>

**Comment by MadhaviSeelam** [comment]
Verification `In-progress` using
```

Brave | 1.42.73 Chromium: 103.0.5060.134 (Official Build) beta (64-bit)
-- | --
Revision | 8ec6fce403b3feb0869b0732eda8bd95011d333c-refs/branch-heads/5060@{#1262}
OS | Windows 11 Version 21H2 (Build 22000.469)
```

### Case one: new profile - `PASSED`
<details>

1. install `1.42.62`
2. launch Brave
3. open `brave://settings/search` and check `Brave` is the listed provider for both `Normal Window` and `Private Window`
4. expand the list and ensure search-engine order and names match the spec (they should be the same between both window types)
5. change `Brave` to `StartPage` for `Private Window`
6. click on the "hamburger" menu and choose `New Private Window`
7. perform a search and confirm you're using `Qwant`
8. perform a search using a `Normal Window` and confirm it uses `Brave`
9. perform a search using a `Private Window with Tor` and confirm it uses `Brave`
10. perform a search using a `Guest Window` and confirm it uses `Brave`
11. opened `brave://settings/searchEngines`
12. Click three dots (...) for Ecosia 
13. Delete `Ecosia`
15. confirm lists have been updated in both `Window` options list
16. open `brave://settings/reset`
17. click on `Restore settings to their original defaults`
18. confirm by clicking on `Reset settings`
19. confirm default search providers have been restored


Step 3|Step4(NW)|Step4(PW)|Step 5|Step 7|Step8|Step 9|Step 10|Step 12|Step 15|Step 19
----|----|----|----|----|----|----|----|----|----|----
<img width="800" alt="image" src="https://user-images.githubusercontent.com/98358127/180103637-a05dd0cc-42d8-48ec-8fd8-ffbf78bfb3d5.png">|<img width="800" alt="image" src="https://user-images.githubusercontent.com/98358127/180103705-36b35bbb-d770-4aec-899f-eeef4c049fd9.png">|<img width="800" alt="image" src="https://user-images.githubusercontent.com/98358127/180103102-dc6421b3-bfd7-42e2-8fcc-47339ece0377.png">|<img width="800" alt="image" src="https://user-images.githubusercontent.com/98358127/180103832-7a8cc61e-9a75-4df5-8d2d-2af67b94af61.png">|<img width="800" alt="image" src="https://user-images.githubusercontent.com/98358127/180103320-10a80332-485d-43e5-a1c7-9e19892db3f6.png">|<img width="800" alt="image" src="https://user-images.githubusercontent.com/98358127/180103239-b31b1f36-b2b1-4a97-9638-7fd868b5fc3c.png">|<img width="800" alt="image" src="https://user-images.githubusercontent.com/98358127/180104604-070684df-e10a-410b-a9b8-485c4cf23af5.png">|<img width="800" alt="image" src="https://user-images.githubusercontent.com/98358127/180104429-ef18fcbe-2446-4745-89ef-73b4c594902d.png">|<img width="800" alt="image" src="https://user-images.githubusercontent.com/98358127/180107292-91f2f9b3-daa0-46eb-8e9b-92e20b9d970d.png">|<img width="800" alt="image" src="https://user-images.githubusercontent.com/98358127/180107522-5c7876af-1072-486c-9b75-3e33b455506a.png">|<img width="800" alt="image" src="https://user-images.githubusercontent.com/98358127/180107648-284b5599-0643-4a2a-8a68-21858aef5b95.png">
</details>











### Case three: Sync - `PASSED`

<details>

#### Verified on two profiles on the same desktop:
* profile 1 
* create another profile `profile 2-sync`


**profile 1 **

1. open `brave://settings/search`
2. change `Normal Window` from `Brave` to `Ecosia`
3. change `Private Window` from `Brave` to `Bing`
4. click on the "hamburger" menu, and then `Sync`
5. click on `Start a new Sync Chain`
6. click on `Computer`
7. copy the codewords
8. under `Sync Settings`, click on the `Sync everything'


steps 2 & 3 | step 7|Step 8
-------|-----|-------
<img width="850" alt="image1" src="https://user-images.githubusercontent.com/98358127/180108779-7dafee74-3f78-4105-95d0-8886be8b3bab.png">|<img width="850" alt="image1" src="https://user-images.githubusercontent.com/98358127/180109504-ce994c13-bb0a-4f09-8e32-8fc3f5034f95.png">|<img width="850" alt="image1" src="https://user-images.githubusercontent.com/98358127/180109595-100ab036-8a12-4084-9a64-d5e53306bf20.png">

**profile 2-sync**

1. click on the "hamburger" menu, and then `Sync`
2. click `I have a Sync Code`
3. enter/paste the codewords from `profile 1`
4. click `Confirm`
5. click `OK`
6. under `Sync Settings`, click on the `Sync everything` toggle
7. open `brave://settings/search`
8. confirm `Normal Window` is `Ecosia`
9. confirm `Private Window` is `Bing`

Step 5|Step 7|Step 8&9
----|----|----
<img width="850" alt="image1" src="https://user-images.githubusercontent.com/98358127/180109795-ab9db746-fe63-4bd4-9ee2-49aa281ba810.png">|<img width="850" alt="image1" src="https://user-images.githubusercontent.com/98358127/180109875-651b6e68-0573-4e4a-b2fa-4fb3baebb490.png">|<img width="850" alt="image1" src="https://user-images.githubusercontent.com/98358127/180110007-bec61f5d-b116-45cc-921e-7b9926310d35.png">

</details>
