### ISSUE TITLE
Alignment between radio buttons and their labels is off

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#23097]
## Description 

Alignment between radio buttons and their labels is off

## Steps to Reproduce

   1. install `1.41.19`
   2. launch Brave
   3. set up VPN
   4. click on the `VPN` button and ensure you're connected
   5. click on the currently-connected region link (in my case, `USA (West) >`

## Actual result:

example | example | example | example
---------|----------|---------|---------
<img width="199" alt="Screen Shot 2022-05-26 at 3 37 55 PM" src="https://user-images.githubusercontent.com/387249/170647879-9ea3f1e3-a069-4137-bb6a-9dc6f7350462.png"> | <img width="340" alt="Screen Shot 2022-05-26 at 11 53 25 PM" src="https://user-images.githubusercontent.com/387249/170647884-03d6d642-37fe-4532-82dd-fb4634683dc2.png"> | <img width="364" alt="Screen Shot 2022-05-26 at 3 37 48 PM" src="https://user-images.githubusercontent.com/387249/170648429-afcb7246-e671-424f-8baf-5a2f32bc82f7.png"> | <img width="375" alt="Screen Shot 2022-05-26 at 11 53 09 PM" src="https://user-images.githubusercontent.com/387249/170648477-817eafdc-a96b-4dc4-95a5-c9bd5dbf75ec.png">

## Expected result:

Better vertical alignment

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.41.19 Chromium: 102.0.5005.61 (Official Build) nightly (x86_64)
-- | --
Revision | 0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}
OS | macOS Version 11.6.6 (Build 20G624)

cc @nullhook @aguscruiz @spylogsster @bsclifton @srirambv

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS

```
Brave | 1.46.141 Chromium: 108.0.5359.99 (Official Build) (64-bit)
-- | --
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | Windows 10 Version 21H2 (Build 19044.2251)

```

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.46.141 Chromium: 108.0.5359.99 (Official Build) (x86_64)
-- | --
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | macOS Version 13.1 (Build 22C65)

example | example | example | example
---------|---------|-----------|---------
<img width="156" alt="Screenshot 2022-12-09 at 12 40 08 PM" src="https://user-images.githubusercontent.com/387249/206792642-d4841a9c-6ad5-4a24-82e3-c98a4b89a65a.png"> | <img width="184" alt="Screenshot 2022-12-09 at 12 40 51 PM" src="https://user-images.githubusercontent.com/387249/206792644-3a35b27b-b6a8-4709-9ba9-333780ae83ca.png"> |<img width="1312" alt="Screenshot 2022-12-09 at 12 40 20 PM" src="https://user-images.githubusercontent.com/387249/206792687-ba3b51c3-be32-4d9e-88f5-c05400ef619f.png"> | <img width="1312" alt="Screenshot 2022-12-09 at 12 40 33 PM" src="https://user-images.githubusercontent.com/387249/206792719-86806657-5392-436f-9014-c9c5bbcedf92.png">
