### ISSUE TITLE
Block scripts needs better wordings

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#231]
## Description 
Wording doesn't seem to convey what needs to be done. Should have better wordings.

 ## Actual result:

![image](https://user-images.githubusercontent.com/17010094/40587850-e0ea297c-61a2-11e8-82b7-b9d7abb4fd76.png)
Current noscript modal for reference
![image](https://user-images.githubusercontent.com/17010094/40587859-f90b3d16-61a2-11e8-88c7-725ca97c1474.png)

## Brave version (about:brave info)

2e9c470

cc: @bbondy @yrliou

**Comment by bsclifton** [comment]
cc: @tomlowenthal
