### ISSUE TITLE
Update Wyre and Ramp Asset List

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#23103]
## Description 
- Update Wyre asset list to reflect the list [here](https://docs.sendwyre.com/docs/supported-currencies#available-currencies---blockchains)
- Add Basic Attention Token on Solana in Ramp Asset List

**Comment by srirambv** [comment]
@muliswilliam is this a QA/Yes or QA/No? Can you please add the QA labels

**Comment by srirambv** [comment]
(64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>8888ee7a24e2c36661ddb9536c35b7d4852a3a98-refs/branch-heads/4951@{#1230}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 22H2
         <br/> (Build 22621.1)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td>
      </td>
      <td colspan=3>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/13529>brave/brave-core#13529</a></li>
         <li>Verified BAT is listed under tokens for Buy on Solana network</li>
         <li>Verified only RAMP is available for BAT under Solana network</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/172355751-22c6fe9a-16d3-415e-9dc6-a6fa626d33df.mp4>
      </td>
      <td><video width=800 src=https://user-images.githubusercontent.com/17010094/172354282-c5ebbd7c-2660-4dbb-b1c8-f349658c5979.mov>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/172354373-90508410-b696-49cd-a5e8-40b760e96d57.mov>
      </td>
   </tr>
</table>
