### ISSUE TITLE
Crash with no option of recovery

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#2310]
## Description 
I Just had a crash with 0.56.15 (Windows 10) that was unique. Usually after a crash the browser offers to restore tabs. This crash didn't. All tabs were completely lost, and no opportunity to restore was presented.

Crash ID: 5a78d9c8710fcf89

## Steps to Reproduce
N/A

## Actual result:
Crash with no tab-recovery option.

## Expected result:
No crash. Or crash with tab-recovery option.

## Reproduces how often: 
Only once so far.

## Brave version (brave://version info)
0.56.15

### Additional Information
Crash ID: 5a78d9c8710fcf89

**Comment by rebron** [comment]
@jonathansampson Is this still an issue?

**Comment by jonathansampson** [comment]
@rebron I haven't seen this in a while.
