### ISSUE TITLE
Countries flag needs a bolder border on light theme esp for Japan 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23101]
## Description 

Countries flag needs a bolder border on light theme esp for Japan 

## Steps to Reproduce

   1. Open country selector on VPN screen 
   2. Check for Japan
   3. There is no border which causes the flag to show up wrong

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/170676940-9c0c3f6f-e0d1-40bf-acdd-a2497c04eff8.png)

## Expected result:
All flags to have  border or a shadow to make it look more prominent

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.41.17 Chromium: 102.0.5005.61 (Official Build) nightly (64-bit)
-- | --
Revision | `0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}`
OS | macOS

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @nullhook @brave/legacy_qa

**Comment by bsclifton** [comment]
This was fixed when we moved to icons in Nala 😄 Credit to @simonhong for the fix
![image](https://github.com/brave/brave-browser/assets/4733304/6c33618c-3d02-49f9-88b1-3b46355faebf)
