### ISSUE TITLE
Dapps: fix dapps main ui

### ISSUE THREAD

**Issue by qamarngr** [brave/brave-browser#23105]
https://www.figma.com/file/elYYVr6qkkvNnRiRpBcZSx/Android-Dapp-Support?node-id=0%3A1
https://bravesoftware.slack.com/archives/C03H854K19V/p1654181154094749

**Comment by qamarngr** [comment]
will also fix [2311](https://github.com/brave/brave-browser/issues/23111)

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.40.105 x64 build
- Verified steps from [brave/brave-core#13608](https://github.com/brave/brave-core/pull/13608)
- Verified UI updates look as per figma spec

Disabled | Enabled | Approve | Switch Network
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/174645473-82ff8949-73f3-4b80-8437-094a7ab1af62.png) | ![image](https://user-images.githubusercontent.com/17010094/174645481-ab78f34b-a0f9-492c-9cac-2fe0e4475477.png) | ![image](https://user-images.githubusercontent.com/17010094/174645488-807d7a0d-4fd1-415c-bbef-be0e67016c12.png) | ![image](https://user-images.githubusercontent.com/17010094/174645500-7d0cb4c6-6a10-441f-935d-9c31ec85d4aa.png)

-----------
Verification passed on Samsung Tab A with Android 10 running 1.40.105 x64 build
- Verified steps from [brave/brave-core#13608](https://github.com/brave/brave-core/pull/13608)
- Verified UI updates look as per figma spec

Disabled | Enabled | Approve | Switch Network
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/174645850-001c0669-3673-46aa-aa57-ae5c82104445.png) | ![image](https://user-images.githubusercontent.com/17010094/174645861-45c6d9c9-3109-414e-ae1b-3ac888b89b21.png) | ![image](https://user-images.githubusercontent.com/17010094/174645875-52db61a5-d869-4f30-b8f7-1f9bddef662a.png) | ![image](https://user-images.githubusercontent.com/17010094/174645889-4b507b2c-58b3-4b43-9ca2-71a9eeaab845.png)
