### ISSUE TITLE
Brave Rewards doesn't display correctly under Wayland session

### ISSUE THREAD

**Issue by wassou93** [brave/brave-browser#23117]
## Description 

When I click on Brave Reward icon in the address bar while being under wayland the window pops up bery small with horizontal scroll bar and it can't be resized while in XWayland it displays correctly.

## Steps to Reproduce

   1. Enable Wayland from brave://flags#Preferred Ozone platform set to Auto
   2. Restart Brave.
   3. Open Brave reward

## Actual result:

Brave rewards appears very small and it can't be resized. _(Check attachment below)_

## Expected result:
I expect it to have the same behavior under XWayland. _(Check attachment below)_

## Reproduces how often: 
 
Just follow steps above.

## Brave version (info found on brave://version)
 
1.39.111 Chromium: 102.0.5005.61 (Official Build) (64-bit) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Didn't test
- Can you reproduce this issue with the dev channel? Didn't test
- Can you reproduce this issue with the nightly channel? Didn't test

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? N/a
- Is the issue reproducible on the latest version of Chrome? N/a

## Miscellaneous Information:

This is under Wayland:
![Screenshot from 2022-05-27 19-19-23](https://user-images.githubusercontent.com/8655283/170769555-29e3d1d5-f39c-434b-bed1-34c669fcd8c7.png)

This is under XWayland
![Screenshot from 2022-05-27 19-18-24](https://user-images.githubusercontent.com/8655283/170769568-4907b2dd-2c23-453e-a454-45bcdb575a9b.png)

**Comment by Miyayes** [comment]
This may be resolved soon when we move away from Rewards extension. https://github.com/brave/brave-browser/issues/22423

**Comment by wassou93** [comment]
@zenparsing @Miyayes ,

Hi Guys,

I have noticed this issue also with chromium,
Tested on current stable release: **101.0.4951.64 (Official Build) snap (64-bit)** 

### Results:

**Wayland:**
![Screenshot from 2022-05-28 11-15-18](https://user-images.githubusercontent.com/8655283/170821217-c6979a04-8d00-4251-9998-95cd105ca83b.png)

**XWayland:**
![Screenshot from 2022-05-28 11-17-38](https://user-images.githubusercontent.com/8655283/170821203-c9c8f12e-f57b-4b54-914a-a8ad5af9f02a.png)

**Comment by wassou93** [comment]
For all people experiencing same issue,

This is not from Brave it's a factional scaling issue, there is already a chromium bug still open for it:
https://bugs.chromium.org/p/chromium/issues/detail?id=1282790&q=wayland%20extension&can=2

It seems after disabling and enabling back fractional scaling on Ubuntu issue got resolved.

**Result under wayland:**
![Screenshot from 2022-05-28 11-49-02](https://user-images.githubusercontent.com/8655283/170822195-b696c378-9479-434d-8e9c-57267d77c6f7.png)

I will close the case as no further requests pending.
