### ISSUE TITLE
Consider disabling FTP 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#2311]
Relating muon issue https://github.com/brave/browser-laptop/issues/14712

Chrome want to disable it as well as per [report](https://www.bleepingcomputer.com/news/google/chrome-and-firefox-developers-aim-to-remove-support-for-ftp/).

@diracdeltas @tomlowenthal @jumde does the upstream changes good enough or do we need to have the same fix from muon onto bc?

**Comment by bbondy** [comment]
I prefer to just follow upstream's lead here. Thoughts?

**Comment by diracdeltas** [comment]
@bbondy as mentioned in https://github.com/brave/browser-laptop/issues/14712#issuecomment-404306032, the main reason for disabling FTP entirely was that muon's implementation did not disallow navigation to `chrome-extension://` from an FTP origin. i just checked and brave-core does not do this.
