### ISSUE TITLE
[Android] New Ads Auth Refresh Flow 

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#23114]
## Description

**See: https://github.com/brave/internal/issues/880**

Android version of https://github.com/brave/internal/issues/769. 

cc: @emerick

**Comment by deeppandya** [comment]
@Miyayes i have excluded the issue from the release notes. can you please update if you feel otherwise ?

**Comment by Uni-verse** [comment]
Verification in progress on `Samsung Galaxy Tablet` using the following build(s):

```
Brave	1.43.82 Chromium: 105.0.5195.68 (Official Build) canary (32-bit) 
Revision	ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS	Android 12; Build/SP1A.210812.016
```

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+` running `Android 12` using the following build(s):

```
Brave | 1.43.82 Chromium: 105.0.5195.68 (Official Build) canary (32-bit)
--- | ---
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | Android 12; Build/SP1A.210812.016
```

Verification notes can be found via https://github.com/brave/internal/issues/880#issuecomment-1234541469.
