### ISSUE TITLE
After reconnecting to network,  Brave VPN is taking longer to connect  hence connection fails

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#23119]
## Description 

After connecting to the network, Brave VPN is not enabled.  The status shows `connecting` for almost a minute.  Had to disconnect and reconnect Brave VPN. 

## Steps to Reproduce

Steps to Reproduce

1. Complete the steps under Brave Premium login > Login to an existing account which has VPN
2. Unplug your network cable (or disable Wi-Fi)
3. Click the VPN button (top right, next to hamburger button)
4. Click the toggle to ENABLE
5. You should see the error about not being able to connect
6. Plug network cable back in OR enable Wi-Fi (disabled in step 2)
7. Click the Try again button
8. It should work now

## Actual result:

1. `Try again` button didn't work as Brave VPN is taking longer to connect
2. Disconnected and reconnected Brave VPN in the Network & Internet in the settings

https://user-images.githubusercontent.com/98358127/170798494-5c29b3a3-d81d-4e81-9069-b3cf41c25e37.mp4

## Expected result:
Brave VPN should be enabled/connected with in the optimal time OR provide a message OR Spinner

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Brave | 1.40.75 Chromium: 102.0.5005.61 (Official Build) beta (64-bit)
-- | --
Revision | 0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}
OS | Windows 11 Version 21H2 (Build 22000.675)

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
@rebron  @simonhong

**Comment by GeetaSarvadnya** [comment]
@MadhaviSeelam Looks like dup of #23081
