### ISSUE TITLE
VPN onboarding modal flashes before loading the VPN modal state

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23116]
## Description 

VPN onboarding modal flashes before loading the VPN modal state

## Steps to Reproduce

   1. Enable VPN and connect to a node
   2. Click on VPN button in URL bar
   3. Before the modal loads VPN connect state it briefly flashes the onboarding screen

## Actual result:

https://user-images.githubusercontent.com/17010094/170744490-0f7c5371-7d3f-4629-aad6-9f5211b54d6d.mov

## Expected result:
Do not show onboarding screen before loading the actual modal state

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.41.17 Chromium: 102.0.5005.61 (Official Build) nightly (64-bit)
-- | --
Revision | `0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}`
OS | macOS Version 12.4 (Build 21F79)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

Also seen this on [#21754](https://github.com/brave/brave-browser/issues/21754) & [#22882](https://github.com/brave/brave-browser/issues/22882)

cc: @bsclifton @spylogsster @simonhong @brave/legacy_qa

**Comment by GeetaSarvadnya** [comment]
++reproduced on windows 10 x64

**Comment by GeetaSarvadnya** [comment]
Could be macOS specific issue, not reproducible in Windows 10 x64

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.42.2 Chromium: 103.0.5060.53 (Official Build) nightly (64-bit)
-- | --
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | Windows 11 Version 21H2 (Build 22000.739)
```

Was able to reproduce in 1.41.47 using the recording.  It was a faint modal 

<img width="472" alt="Screenshot 2022-06-16 153413" src="https://user-images.githubusercontent.com/98358127/174194797-0028e21c-e1c0-41ff-83b4-050d267cf238.png">

Confirmed the fix and onboarding modal no longer flashed

![2022-06-16_16h47_38](https://user-images.githubusercontent.com/98358127/174196105-7a9db29c-0788-4a1c-98fe-961bef2ec68f.gif)
