### ISSUE TITLE
Provide an option to remove Top Tiles from NTP

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#23118]
## Description 
This person makes a fair point [here](https://reddit.com/r/brave_browser/comments/uz3zs3/dear_brave_developers_please_give_an_option_to/), 

Let's provide an option to remove Top Tiles from NTP.  

Settings details TBD @timchilds

**Comment by anthonypkeane** [comment]
Related to: https://github.com/brave/brave-browser/issues/22921

**Comment by kjozwiak** [comment]
@brave/qa-team please see the STR/Cases that I created/went through via https://github.com/brave/brave-core/pull/13519#issuecomment-1156005079 when verifying via `1.40.x` 👍

**Comment by kjozwiak** [comment]
The above will require `1.40.100` or higher for `1.40.x` verification 👍

**Comment by Uni-verse** [comment]
@Uni-verse Check below case when next release build is available.

Case: 

- [ ] downloaded/installed 1.40.x build with feature
- [ ] disabled Show Top sites from Settings -> New Tab Page and restarted re-launched the browser as specified
- [ ] Upgraded 1.40.x app 
- [ ] ensured that Top Top tiles are not being displayed under NTP
- [ ] ensured that Show Top sites is disabled via Settings -> New Tab Page
