### ISSUE TITLE
DApps: Remove wallet icon from URL when you navigate away from Dapp 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23110]
## Description 
Remove wallet icon from URL when you navigate away from Dapp 

## Steps to reproduce 

   1. Visit `https://chainlist.org` and initiate Dapp interaction
   2. Connect the wallet to Dapp
   3. On the same tab visit a different page, continues to show Wallet icon
   4. Visit another page, continues to show the wallet icon and allows to connect

## Actual result 

https://user-images.githubusercontent.com/17010094/170708893-6a601e16-b40d-4c9c-9781-ba7cc90df17c.mp4

## Expected result
Should remove the wallet icon when you navigate away from Dapp

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? NA

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 12
   
## Brave version
1.41.18 Custom Dapp build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @SergeyZhukovsky @jamesmudgett @Pavneet-Sing @qamarngr

**Comment by diracdeltas** [comment]
> Visit another page, continues to show the wallet icon and allows to connect

marking this as security in case this means wallet permissions are being applied to origins other than the one that the user gave permission to. cc @deeppandya @SergeyZhukovsky

**Comment by SergeyZhukovsky** [comment]
@diracdeltas no, nothing applied to a diff origin, it's a UI bug that we don't hide the icon on origin change.

**Comment by kjozwiak** [comment]
The above will require `1.40.96` or higher for `1.40.x` verification 👍
