### ISSUE TITLE
DApps: [Follow up to #22913] Incorrect position of buttons 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23111]
## Description 
[Follow up to #22913] Incorrect position of buttons 

## Steps to reproduce 

   1. 
   2. 
   3. 

## Actual result 

<img src=https://user-images.githubusercontent.com/17010094/170714508-1dc872ba-13c6-473f-828d-c083e748f197.png>

## Expected result
Something similar to 

<img src=https://user-images.githubusercontent.com/17010094/170715569-a8aea2ed-4e73-44cd-9c5f-2d7ea5b29196.png>

## Issue reproduces how often 
Easy

### Additional information

Discussion here https://bravesoftware.slack.com/archives/C02SC5AKTAS/p1653571881555799

**Comment by Pavneet-Sing** [comment]
I think it's easy to press the button at the bottom, default on android as well as it offers better UX. Many of the dialog have button at the bottom as well on desktop, probably should be fixed on desktop?

**Comment by jamesmudgett** [comment]
bottom placement is good, should also fix styling to match (content border is missing in the first example) @Pavneet-Sing @qamarngr

**Comment by qamarngr** [comment]
> bottom placement is good, should also fix styling to match (content border is missing in the first example) @Pavneet-Sing @qamarngr

will do that and post screenshot on slack

**Comment by kjozwiak** [comment]
The above will require `1.40.96` or higher for `1.40.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.40.105 x64 build
- Verified steps from [brave/brave-core#13608](https://github.com/brave/brave-core/pull/13608)
- Verified UI updates look as per figma spec
- Encountered [#23392](https://github.com/brave/brave-browser/issues/23392)

Disabled | Enabled | Approve | Switch Network
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/174645473-82ff8949-73f3-4b80-8437-094a7ab1af62.png) | ![image](https://user-images.githubusercontent.com/17010094/174645481-ab78f34b-a0f9-492c-9cac-2fe0e4475477.png) | ![image](https://user-images.githubusercontent.com/17010094/174645488-807d7a0d-4fd1-415c-bbef-be0e67016c12.png) | ![image](https://user-images.githubusercontent.com/17010094/174645500-7d0cb4c6-6a10-441f-935d-9c31ec85d4aa.png)

-----------
Verification passed on Samsung Tab A with Android 10 running 1.40.105 x64 build
- Verified steps from [brave/brave-core#13608](https://github.com/brave/brave-core/pull/13608)
- Verified UI updates look as per figma spec
- Encountered [#23392](https://github.com/brave/brave-browser/issues/23392)

Disabled | Enabled | Approve | Switch Network
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/174645850-001c0669-3673-46aa-aa57-ae5c82104445.png) | ![image](https://user-images.githubusercontent.com/17010094/174645861-45c6d9c9-3109-414e-ae1b-3ac888b89b21.png) | ![image](https://user-images.githubusercontent.com/17010094/174645875-52db61a5-d869-4f30-b8f7-1f9bddef662a.png) | ![image](https://user-images.githubusercontent.com/17010094/174645889-4b507b2c-58b3-4b43-9ca2-71a9eeaab845.png)
