### ISSUE TITLE
Unable to login into nintendo.com (due to fingerprinting)

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#23127]
## Description 
Unable to login into nintendo.com

## Steps to Reproduce

   1. Open `https://nintendo.com/`
   2. Click on top right hand corner to login
   3. Click Login Button.
   4. Try to click on `Sign In`.  Fails to open with default shields

## Actual result:
No errors in console. Endless loading when clicking on `Sign In`
![nint](https://user-images.githubusercontent.com/1659004/170865130-4bcbdc2c-3a82-429f-be6d-6c606bcd2707.png)

## Expected result:
Should redirect too this page:
![nintt](https://user-images.githubusercontent.com/1659004/170865196-c2c64c98-f0fe-410c-95c3-195244e0f8da.png)

## Reproduces how often: 

Easily

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
Disabling Fingerprinting, resolves it.

**Comment by ryanbr** [comment]
Bisect: https://github.com/brave/brave-browser/compare/v1.39.22...v1.39.23

```
Nightly v1.39.23 (Chromium 100.0.4896.60)  BAD
Nightly v1.39.22 (Chromium 100.0.4896.60)  GOOD
```

**Comment by pes10k** [comment]
@ryanbr this worked fine for me.  I'm on `1.41.20 Chromium: 102.0.5005.61 (Official Build) nightly (arm64) ` FWIW

**Comment by ryanbr** [comment]
Okay, works for me now. Closing
