### ISSUE TITLE
`Hide Brave Rewards icon` option requires a left-click on the `Brave Rewards` icon every time browser is restarted

### ISSUE THREAD

**Issue by Tonev** [brave/brave-browser#23124]
## Description 

Users can't use the new `Hide Brave Rewards icon` option without an extra left-click on the icon in advance. This is required after every browser restart.

## Steps to Reproduce

   1. Clean user profile in `Brave Beta` or `Brave Nightly`.
   2. Right-click on the `Brave Rewards` icon in the address bar.

## Actual result:
The `Hide Brave Rewards icon` option doesn't appear. For users to be able to use the option, they'll have to left-click on the `Brave Rewards` icon in the address bar, and then they'll be able to hide the icon through a right-click until they close the browser.

## Expected result:
I would expect to be able to use the `Hide Brave Rewards icon` option with one click every time.

## Reproduces how often: 

100%

## Brave version (brave://version info)

<html>
<body>

Brave | 1.40.75 Chromium: 102.0.5005.61 (Official Build) beta (64-bit)
-- | --
Revision | 0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}
OS | Windows 10 Version 21H2 (Build 19044.1706)

</body>
</html>

<html>
<body>

Brave | 1.41.20 Chromium: 102.0.5005.61 (Official Build) nightly (64-bit)
-- | --
Revision | 0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}
OS | Windows 10 Version 21H2 (Build 19044.1706)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CC: @mkarolin @rebron

**Comment by Miyayes** [comment]
May be resolved for free with https://github.com/brave/brave-browser/issues/22423

**Comment by Tonev** [comment]
@Miyayes 

Isn't the linked issue supposed to introduce changes only when `Brave Rewards` is enabled?

**Comment by mkarolin** [comment]
This was addressed via https://github.com/brave/brave-browser/issues/22423
