### ISSUE TITLE
Able to select DAI -> DAI Swap on Ropsten

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23134]
## Description 

Able to select DAI -> DAI Swap on Ropsten

## Steps to Reproduce

   1. Create new wallet
   2. Enable Testnet from Wallet settings
   3. Select Swap and select DAI from send token list
   4. Select To token list, DAI is still shown and can be selected

## Actual result:

https://user-images.githubusercontent.com/17010094/170917880-d8e23492-7dbe-40bf-9a59-9309db93f56b.mov

## Expected result:
Should only show in one field if its not selected

## Reproduces how often: 

Intermittent issue

## Brave version (brave://version info)

Brave | 1.41.20 Chromium: 102.0.5005.61 (Official Build) nightly (64-bit)
-- | --
Revision | `0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}`
OS | Windows 11 Version 22H2 (Build 22621.1)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes, Repro'd on `1.39.111`
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel @muliswilliam

**Comment by jamesmudgett** [comment]
@Douglashdaniel are these two separate contract addresses, see the title is different? cc @onyb

**Comment by jamesmudgett** [comment]
@Douglashdaniel are these two separate contract addresses, see the title is different? cc @onyb

**Comment by HEagle18** [comment]
I don't think this is still relevant with swaps 2.0 @srirambv ?

**Comment by srirambv** [comment]
Yes not relevant anymore. Going to close this as stale
