### ISSUE TITLE
Brave's adblock doesnt reposition elements of a webpage after blocking ads

### ISSUE THREAD

**Issue by mdalch** [brave/brave-browser#2313]
## Description 
After loading a webpage Brave's adblock block indeed ads but leave their positions empty without repositioning the webpage elements.

## Actual result:

[
![screenshot from 2018-11-30 00 33 36](https://user-images.githubusercontent.com/10380737/49286674-36b8f780-f49b-11e8-9663-380bd42bf1ca.png)
](url)

## Expected result:
repositioning the webpage elements after blocking ads. Photo taken from firefox with "uBlock origin" addon installed
[
![screenshot from 2018-11-30 00 34 26](https://user-images.githubusercontent.com/10380737/49286709-4afcf480-f49b-11e8-878e-1e15e808e53c.png)
](url)

## Brave version 
Version 0.56.15 Chromium: 70.0.3538.110 (Official Build) (64-bit) on Linux (elementary os up to date)

**Comment by antonok-edm** [comment]
I don't see any problems on allgemeine-zeitung.de, so it looks like this can be closed.

In general this should now be handled by cosmetic blocking (https://github.com/brave/brave-browser/issues/5381), although feel free to open issues with specific urls if there are still issues.
