### ISSUE TITLE
Ethereum Testnet is listed after all pre-populated networks

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23133]
## Description 

Ethereum Testnet is listed after all pre-populated netwroks

## Steps to Reproduce

   1. Enable `Show test networks` from `brave://settings/wallet/networks`
   2. Open Network selector dropdown
   3. Ethereum Testnet's are shown after all pre-populated mainnets. Not the same with Solana

## Actual result:

https://user-images.githubusercontent.com/17010094/170916883-68d6e2c8-eed5-46e8-9851-6ccb1e341b5f.mov

## Expected result:
Should list testnets below the Ethereum Mainnet 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html><head></head>
<body>

Brave | 1.41.20 Chromium: 102.0.5005.61 (Official Build) nightly (64-bit)
-- | --
Revision | `0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}`
OS | Windows 11 Version 22H2 (Build 22621.1)

</body>
</html>
## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel @muliswilliam

**Comment by Douglashdaniel** [comment]
Is no longer an issue with the `Wallet V2` updates. Closing as `Invalid`
