### ISSUE TITLE
Side panel button missing

### ISSUE THREAD

**Issue by Yiannis128** [brave/brave-browser#23130]
## Description 
The sidebar button and option in brave flags are missing the side panel options.

## Steps to Reproduce

   1. Go to [Brave flags](brave://flags)
   2. Search for side panel
   3. No side panel option to enable.

## Actual result:

![image](https://user-images.githubusercontent.com/9535618/170889757-6a5fcc54-6199-4609-bc7d-31ae520efe7d.png)

## Expected result:

Expect a listing to enable side panel button in the header area of the browser.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
1.39.111 Chromium: 102.0.5005.61 (Official Build) (64-bit) 
0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}
Linux

**Comment by bsclifton** [comment]
cc: @petemill

**Comment by bsclifton** [comment]
Closing as this is now implemented and the button is showing for folks 😄 We have an issue to allow for toggling the button here:
https://github.com/brave/brave-browser/issues/25272
