### ISSUE TITLE
Remove P2A protobuf reporting

### ISSUE THREAD

**Issue by rillian** [brave/brave-browser#23146]
## Description 

With #22079 we started sending P2A reports to a new json-format endpoint. Once we're confident the new reports are being correctly ingested we should stop sending the old protobuf-format reports and can remove the associated generation code.

**Comment by rillian** [comment]
We're seeing good match with the json data channel, so this issue can go ahead.

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```
Brave | 1.44.79 Chromium: 105.0.5195.102 (Official Build) beta (64-bit)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | Windows 10 Version 21H2 (Build 19044.1889)

```
