### ISSUE TITLE
Blank page for few seconds on initial load

### ISSUE THREAD

**Issue by wooque** [brave/brave-browser#23154]
## Description 
Some websites have delay in showing full page, they show as blank white page at first and after few seconds they reveal in full. Inspecting it I noticed that html tag has `async-hide` class that is removed after few seconds and that lead me to past issue that seems to be back again https://github.com/brave/brave-browser/issues/4402

## Steps to Reproduce

   1. Open https://www.kupujemprodajem.com/index.php

## Actual result:

It shows blank white page, after few seconds it shows fully

## Expected result:
No artificial blank white page delay

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.39.111 Chromium: 102.0.5005.61 (Official Build) (64-bit)
-- | --
Revision | 0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}
OS | Linux
JavaScript | V8 10.2.154.4
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36
Command Line | /opt/brave.com/brave/brave --enable-features=OverlayScrollbar,VaapiVideoDecoder --enable-gpu-rasterization --enable-zero-copy --disable-features=UseChromeOSDirectVideoDecoder --disable-smooth-scrolling --enable-crashpad --disable-client-side-phishing-detection --disable-domain-reliability --enable-dom-distiller --no-pings --component-updater=url-source=https://go-updater.brave.com/extensions --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --variations-insecure-server-url=https://variations.brave.com/seed --enable-features=VaapiVideoDecoder,OverlayScrollbar --disable-features=UseChromeOSDirectVideoDecoder --flag-switches-begin --flag-switches-end
Executable Path | /opt/brave.com/brave/brave
Profile Path | /home/vuk/.config/BraveSoftware/Brave-Browser/Default
Variations | AdRewardsStudy:NextPaymentDayAdServingStudy:DefaultAdNotificationsPerHour=10/MaximumAdNotificationsPerDay=100/MaximumInlineContentAdsPerHour=12/MaximumInlineContentAdsPerDay=60BraveAds.UserActivityStudy:Triggers=EMPTY/Threshold=0.0/IdleTimeThreshold=5BraveDebounceStudy:EnabledConversionsStudy:NewDefaultPatternDefault1pBlockingStudy:DisabledEphemeralStorageStudy:EnabledExtendedVariationsSafeMode5:SignalAndWriteViaFileUtil5FirstPartyEphemeralDomainBlockStudy:EnabledForceDisableBlinkFeatures:EnabledNativeCosmeticFilteringStudy:EnabledNavigationThreadingOptimizationsCompat:DisabledPartitionBlinkMemoryCacheStudy:EnabledPartitionConnectionsByNetworkIsolationKeyStudy:EnabledPermissionLifetimeReleaseStudy:EnabledRequestAdsEnabledApiStudy:EnabledSpeedreaderReleaseStudy:Enabled

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? /
- Can you reproduce this issue with the nightly channel? / 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards? /
- Is the issue reproducible on the latest version of Chrome? /

**Comment by wooque** [comment]
I had similar issue on accuweather.com and I solved it with customer filters
```
accuweather.com##+js(remove-attr, class, .ads-not-loaded, stay)
kupujemprodajem.com##+js(remove-attr, class, .async-hide, stay)
polovniautomobili.com##+js(remove-attr, class, .async-hide, stay)
```

**Comment by bsclifton** [comment]
@wooque is this still happening?
cc: @ryanbr

**Comment by ryanbr** [comment]
Sorry I missed the post, has these delays always been here? just tested FF on `https://www.polovniautomobili.com/auto-oglasi/19998599/bmw-520?attp=p8_pv0_pc1_pl9_plv0`  Noticed a delay here also @wooque

**Comment by wooque** [comment]
@ryanbr Fix has a bug, only accuweather.com is fixed by removing `.ads-not-loaded`, kupujemprodajem.com i polovniautomobili.com are fixed by removing `.async-hide`
