### ISSUE TITLE
Fix Brave Ads crash when creating a new profile

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#23150]
Caused by fix for https://github.com/brave/brave-browser/issues/22654

**Comment by bsclifton** [comment]
@tmancey if QA is required, can you please add test steps? If not, please mark as `QA/No` - thanks 😄

**Comment by tmancey** [comment]
@bsclifton thanks. QA is not required as this will be tested as part of https://github.com/brave/brave-browser/issues/22654
