### ISSUE TITLE
Add Asset Balances to taker asset dropdown on swaps

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#23161]
## Description 

I want to see the balances of assets I have in my account when I select the dropdown on 'swap to'. 

## Steps to Reproduce

   1.  Try do a swap with your wallet connected 
   2. pick your 'from' asset 
   3. then go to select your 'to' asset from dropdown

## Expected result:
See screenshot attached from Matcha.
![Screenshot 2022-05-31 at 17 07 48](https://user-images.githubusercontent.com/12224304/171206955-a7549e3e-6d91-425c-972c-6bac903550fd.png)

## Reproduces how often: 
 yes easy to reproduce. Try do a swap with your wallet connected, pick your 'from' asset and then go to select your 'to' asset from dropdown. We would like to see your balances listed beside these assets.

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? yes

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/26632#issuecomment-1409052849
