### ISSUE TITLE
Sync should handle library/client errors

### ISSUE THREAD

**Issue by cezaraugusto** [brave/brave-browser#2316]
Sync should handle library/client errors. We have this mechanism in the back-end but interface should be aware of it.

The error happens when sync client (browser) can't connect with the sync server for N reasons, so the message needs to be generic.

Worth mentioning that the offline error is already handled so this is different.

cc @rebron @bradleyrichter to cook a good phrase for this.

**Test Plan:**

1. Create a sync chain and ensure you see two devices
2. Quit Brave
3. Launch Brave without internet
4. You should see a `Couldn't contact Sync servers` error dialog

**Comment by rebron** [comment]
https://github.com/brave/brave-browser/issues/1149 related issue.

I think we can go with something like:

Title: Sync servers can't be reached
Body: The sync servers might temporarily be down. Please try again later.

cc: @tomlowenthal

**Comment by tomlowenthal** [comment]
Title: Couldn't contact Sync servers
Body: You might be having network trouble, or there could be a problem with the Sync servers.

**Comment by srirambv** [comment]
Marking as `QA/Yes` as this requires text verification.

**Comment by rebron** [comment]
@cezaraugusto can we get this in for 58.x too? Use toml text above/repeated here:
Title: Couldn't contact Sync servers
Body: You might be having network trouble, or there could be a problem with the Sync servers.

Can you also create a test plan for QA.

**Comment by GeetaSarvadnya** [comment]
@cezaraugusto Verified the issue on 0.59.12. I am not seeing `Couldn't contact Sync servers` error dialog

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.59.14 Chromium: 72.0.3626.28 (Official Build) beta (64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Windows

- Verified the STR from description

![image](https://user-images.githubusercontent.com/38657976/50640477-fe6d7300-0f8a-11e9-82ee-b54641ddcf62.png)
