### ISSUE TITLE
VPN button in toolbar - Design adjustments

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#23163]
## Description 

The current VPN button in the toolbar is a bit different from the design spec. It should be adjusted to match height and color provided in the design files.

## Steps to Reproduce

   1. Open browser
   2. See VPN button on toolbar

## Actual result:

<img width="670" alt="image" src="https://user-images.githubusercontent.com/15734630/171246539-7e45ae9c-ff1c-469a-ba2a-b73039e49062.png">

## Expected result:
https://www.figma.com/file/qtMYwoj3JWJO5xzwLt6j2f/?node-id=0%3A1

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

[Version 1.41.11](https://brave.com/latest/)

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.41.40 Chromium: 102.0.5005.78 (Official Build) nightly (x86_64)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | macOS Version 12.5 (Build 21G5037d)


`Dark`


`Connected` | `1.40.83` | `Disconnected` | `1.40.83`
--------------|-----------|-----------------|----------
<img width="60" alt="Screen Shot 2022-06-06 at 5 25 25 PM" src="https://user-images.githubusercontent.com/387249/172272182-698e2826-72c2-468b-85bd-ae9f59f718d3.png"> |  <img width="61" alt="Screen Shot 2022-06-06 at 5 47 51 PM" src="https://user-images.githubusercontent.com/387249/172272629-37cacacc-6e58-4585-a91e-a3b8f4042935.png"> |<img width="60" alt="Screen Shot 2022-06-06 at 5 25 14 PM" src="https://user-images.githubusercontent.com/387249/172272191-dd6f45f0-2e1f-475e-bc61-aab2664d857a.png"> | <img width="63" alt="Screen Shot 2022-06-06 at 5 48 02 PM" src="https://user-images.githubusercontent.com/387249/172272691-2b3c10b5-0ff0-47ce-9522-941d60df7c0d.png">



`Light`

`Connected` | `Disconnected`
--------------|-----------------
<img width="73" alt="Screen Shot 2022-06-06 at 5 24 44 PM" src="https://user-images.githubusercontent.com/387249/172272148-76f8a1b2-40bf-4229-823b-495c08fc1857.png"> | <img width="67" alt="Screen Shot 2022-06-06 at 5 24 56 PM" src="https://user-images.githubusercontent.com/387249/172272151-4d83fc20-b2cf-4624-ab20-716ac315915f.png">

**Comment by stephendonner** [comment]
@MadhaviSeelam might want to give this a look on Windows, too, when you get a chance 👍
