### ISSUE TITLE
amp redirect cause endless load loop

### ISSUE THREAD

**Issue by 424344** [brave/brave-browser#23178]
## Description 

enable amp redirect and load this page:
https://www.ilgiorno.it/cronaca/green-pass-1.7731883
the page never stops loading. it is refreshed in an endless loop.

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
Hi @424344 Can you update to our latest 1.39.120? Fix should be in that version. 
Can go to brave://settings/help to get the update.

I checked the link you provided with 1.39.120 and it looks like it was working properly.

**Comment by kjozwiak** [comment]
@424344 the above issues should be resolved by either https://github.com/brave/brave-browser/issues/22610 or https://github.com/brave/brave-browser/issues/23320 👍 https://github.com/brave/brave-browser/issues/22610 went out via `1.39.120` about a week ago. https://github.com/brave/brave-browser/issues/23320 went out today on `Android` via `1.39.123` and will make it into the desktop release in a few days.

I also tried opening https://www.ilgiorno.it/cronaca/green-pass-1.7731883 with `de-amp` enabled several times and it appears that it's loading without getting stuck in the loading loop. If you're still experiencing the same issue, just re-open the issue or create a new one. Really appreciate the bug report.
