### ISSUE TITLE
`Always Show Full URLs` should be `Always show full URLs` in `brave://settings/appearance`

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#23179]
## Description 

`Always Show Full URLs` should be `Always show full URLs` in `brave://settings/appearance`

## Steps to Reproduce

   1. install `1.41.21`
   2. launch Brave
   3. open `brave://settings/appearance`
   4. read the `Always Show Full URLs` pref description, and compare to `Always show bookmarks on new tab page` (sic)

## Actual result:

`Always Show Full URLs`

<img width="1323" alt="Screen Shot 2022-05-31 at 10 51 54 PM" src="https://user-images.githubusercontent.com/387249/171337218-78496037-c88e-4e1b-8249-544c51efb749.png">

## Expected result:

`Always show full URLs`

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.41.21 Chromium: 102.0.5005.61 (Official Build) nightly (x86_64)
-- | --
Revision | 0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}
OS | macOS Version 12.5 (Build 21G5027d)

cc @rmcfadden3

**Comment by Tonev** [comment]
Hey, @stephendonner 👋 

Let's give it a go https://github.com/brave/brave-core/pull/13612 🤞

**Comment by stephendonner** [comment]
Thanks for taking a stab at this, @Tonev!  Looking at your PR, it appears it's for this context-menu option, rather than `brave://settings/appearance` (or is it used in both?)

<img width="990" alt="Screen Shot 2022-06-06 at 12 47 04 PM" src="https://user-images.githubusercontent.com/387249/172236583-cf427715-7579-4efa-89cf-4748dc2bdbfc.png">

@mkarolin or @emerick mind helping with this one?  Sorry for the ping!

**Comment by fallaciousreasoning** [comment]
Also fixes https://github.com/brave/brave-browser/issues/16939

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.43.56 Chromium: 104.0.5112.81 (Official Build) dev (x86_64)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | macOS Version 11.6.8 (Build 20G730)


Confirmed it now reads `Always show full URLs`

<img width="1312" alt="Screen Shot 2022-08-03 at 9 51 10 AM" src="https://user-images.githubusercontent.com/387249/182665105-ed2b8d5f-620a-4545-b22f-4af44b763186.png">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.43.91 Chromium: 105.0.5195.102 (Official Build) (64-bit)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | Windows 11 Version 21H2 (Build 22000.856)
```

Couldn't reproduce the issue in `1.41.21`.   `Always show full URLs` shown as expected in `brave://settings/appearance` in both `1.41. 21` and `1.43.91`
 
 
 `1.41. 21`|`1.43.91`
 ----|----
<image width="900" alt="1.41.21" src="https://user-images.githubusercontent.com/98358127/189426277-476888d4-8dda-4c06-a83c-e35744d335de.png">|<image width="900" alt="1.41.21" src="https://user-images.githubusercontent.com/98358127/189426237-3e4b91d2-e952-46c0-8a31-c0fd15ee842b.png">
