### ISSUE TITLE
Enable 1PES by default

### ISSUE THREAD

**Issue by goodov** [brave/brave-browser#23180]
Enable these features by default in code: `BraveFirstPartyEphemeralStorage, BraveDomainBlock1PES`.

**Comment by LaurenWags** [comment]
Could we get a test plan for this issue please? Thanks!

cc @brave/qa-team @rebron

**Comment by goodov** [comment]
This PR enables two features by default, so they're now should be enabled without the Griffin study.
Test cases are similar to the ones in the original task https://github.com/brave/brave-browser/issues/19099#issuecomment-1002028516

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.42.69 Chromium: 103.0.5060.114 (Official Build) beta (x86_64)
-- | --
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | macOS Version 12.4 (Build 21F79)
```

**Comment by MadhaviSeelam** [comment]
Verification `Complete` using
```
Brave | 1.42.73 Chromium: 103.0.5060.134 (Official Build) beta (64-bit)
-- | --
Revision | 8ec6fce403b3feb0869b0732eda8bd95011d333c-refs/branch-heads/5060@{#1262}
OS | Windows 11 Version 21H2 (Build 22000.469)
```

Per https://github.com/brave/brave-browser/issues/23180#issuecomment-1169588598, ran through the cases from https://github.com/brave/brave-browser/issues/19099#issuecomment-1002028516 on initial launch of 1.42.x (that is, did not launch a second time, so griffin seed was not pulled). Also, do not change any flag values on brave://flags when testing this issue.

<details>
<summary>Case 1: standard mode - PASSED</summary>

1. loaded https://www.media.net/ (from [this list](https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&mimetype=plaintext))
2. opened `brave://settings/cookies`
* Confirmed that https://www.media.net/ is present under `Sites that clear cookies when you close them`
* Confirmed that there were no cookies or local storage for `https://www.media.net/`

Example | Example | Example | Example | Example
-- | -- | -- | -- | --
<Image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/180079372-65df0558-b31c-4743-8a70-37c8a50f153b.png">|<Image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/180079690-9dd1853e-aa19-43ba-97ba-d08e345914e8.png">|<Image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/180079598-30c8c878-b197-40ec-8592-4bd48326887e.png">|<Image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/180079730-3dc9683e-1c8e-4773-9159-832073e2d7d9.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/180079814-77392c6c-d04a-48e5-bfb7-db055f92a58d.png">
</details>

<details>
<summary>Case 2: aggressive mode - PASSED</summary>

1. Fresh profile
2. set Trackers & ads blocking to `Aggressive` from the brave://settings/shields dropdown
3. loaded `raresummer.com`
4. confirmed I saw the blocking interstitial
5. clicked the `Proceed` button
6. opened `brave://settings/cookies`
* Confirmed `raresummer.com` is added to `Sites that clear cookies when you close them` in `brave://settings/cookies`
* Confirmed there were no cookies or local storage for `raresummer.com` 

Example | Example | Example | Example | Example
-- | -- | -- | -- | --
<Image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/180081827-eec0aeb7-e860-4301-80e0-21241a5dd62f.png">|<Image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/180084584-1505cc01-4e4a-4a0b-a5e6-e4f7fcee1ca7.png">|<Image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/180084612-c6276809-9fe1-4f78-acd6-322da302c1b1.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/180094138-ff8fc330-6e3f-40a0-a312-8f88580901d7.png">|<Image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/180084960-a2785681-c204-4a9e-b1a4-2b850e7ba0a4.png">

</details>

<details>
<summary>Case 3: aggressive mode w/checkbox - PASSED</summary>

1. set Trackers & ads blocking to `Aggressive` from brave://shields
2. loaded https://services.hearstmags.com
3. confirmed I got a blocking interstitial
4. clicked the checkbox for `Don't warn me about this site again`
5. clicked on `Proceed`
6. opened `brave://settings/cookies`

* Confirmed `services.hearstmags.com` is not listed in `Sites that clear cookies when you close them`
* Confirmed there were cookies stored
* Confirmed a few entries in local storage

Example | Example | Example | Example | Example | Example | Example
---------|----------|---------|----------|---------|----------|---------
<img width="1195" alt="a" src="https://user-images.githubusercontent.com/98358127/180096531-cb0207de-9849-4809-86b3-21f40182ce3a.png">|<Image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/180095536-a9ae5a10-d071-4c30-a157-6812380177ab.png">|<Image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/180095861-7c054430-d7c3-4fa4-b9cd-2ded6ba39f6c.png">|<Image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/180095901-677e4211-aa73-4393-9231-d0b196cf15bf.png">|<Image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/180095938-b06f85a4-531a-46cf-a728-f8e8c01c4a3b.png">|<Image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/180095975-7dcd0a6c-e071-4ad5-ac4a-be83833a6437.png">|<Image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/180096024-8cda6247-c98f-4831-b711-cbd1d4a2f9b3.png">

</details>
