### ISSUE TITLE
Persist "Advanced Controls" section in Shields v2 panel

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#23188]
## Description

Some users have complained that the "Advanced Controls" section does not stay open, and that they prefer to always see Advanced Controls when opening the Shields panel. (In the past, this would be like the "Advanced View" in Shields v1.)

**Currently:**

>The UI panel by default keeps advanced view section hidden unless you’ve expanded it before. Internally, it keeps a cache of the panel and while it’s in the cache, it remembers that it was previously expanded. If you’re coming back to it after a 1-2min the cache gets destroyed and you start the flow over i.e it creates a fresh panel UI instance again.

per @nullhook 

## Proposed solution

Persist the Advanced Controls section, and do not let it expire after 1-2 minutes.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.43.61 Chromium: 104.0.5112.81 (Official Build) beta (x86_64)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | macOS Version 11.6.8 (Build 20G730)

### Steps:
1. installed `1.43.61`
2. launched Brave
3. visited `huffpost.com` and clicked on the Brave icon on the right the URL bar
4. clicked on the "Advanced controls" button and confirmed it expanded
5. opened a new browser window
6. loaded `espn.com`
7. clicked on the Brave icon; confirmed Shields' controls were expanded
8. waited 5min idle so the current panel instance destroys and open a new one
9. confirmed the panel was still expanded
10. restarted Brave
11. loaded `cnn.com`
12. confirmed `Advanced controls` are expanded by default
13. loaded `brave.com`
14. clicked on `Advanced controls` to collapse the widget
15. confirmed it was collapsed and persisted after restart

step 3-4 | step 7 | step 9 | step 11-12 | step 13-14 | step 15
---------|--------|-----------|---------|-------|-----------
<img width="1312" alt="Screen Shot 2022-08-08 at 2 45 53 PM" src="https://user-images.githubusercontent.com/387249/183522946-096a9a63-2328-4396-a624-0023e112624b.png"> | <img width="1312" alt="Screen Shot 2022-08-08 at 2 46 07 PM" src="https://user-images.githubusercontent.com/387249/183523025-a6abb6ca-696e-46e7-aa7c-11a0863e1170.png"> | <img width="1312" alt="Screen Shot 2022-08-08 at 3 15 55 PM" src="https://user-images.githubusercontent.com/387249/183523919-9ee18677-3c66-47d5-89b2-5d35a62e18b8.png"> | <img width="1312" alt="Screen Shot 2022-08-08 at 2 53 04 PM" src="https://user-images.githubusercontent.com/387249/183523161-7f7c6eb3-7bba-4057-b047-4a1996986f3b.png"> | <img width="1312" alt="Screen Shot 2022-08-08 at 2 58 26 PM" src="https://user-images.githubusercontent.com/387249/183523442-6ad31ac7-f360-4f24-8d0d-2bdb6f81cca9.png"> | <img width="1312" alt="Screen Shot 2022-08-08 at 2 58 43 PM" src="https://user-images.githubusercontent.com/387249/183524011-f4c05a76-9241-45c7-a148-b0c431f83fc7.png">

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using 
```
Brave | 1.43.91 Chromium: 105.0.5195.102 (Official Build) (64-bit)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | Windows 11 Version 21H2 (Build 22000.856)
```

### Steps:
1. installed `1.43.61`
2. launched Brave
3. visited `nytimes.com` and clicked on the Brave icon on the right the URL bar
4. clicked on the "Advanced controls" button and confirmed it expanded
5. opened a new browser window
6. loaded `espn.com`
7. clicked on the Brave icon; confirmed Shields' controls were expanded
8. waited 5min idle so the current panel instance destroys and open a new one
9. opened a NTP and loaded `bbc.com`
10. clicked on the Brave icon; confirmed Shields' controls were expanded
11. opened a new private window 
12. loaded `nbcnews.com`
13. clicked to confirm the panel was still expanded
14.  restarted Brave
16. loaded `cnn.com`
17. confirmed `Advanced controls` are expanded by default
18. loaded `brave.com`
19. clicked on `Advanced controls` to collapse the widget
20. confirmed it was collapsed and persisted after restart

step 3-4 | step 5-7 | step 9-10 | step 11-13 
---------|--------|-----------|---------
<image width = "950" alt="step 3-4" src="https://user-images.githubusercontent.com/98358127/189457697-fd71ec55-6e14-48e8-8332-968cf8fd0130.png">|<image width = "950" alt="step 7" src="https://user-images.githubusercontent.com/98358127/189460651-fb0f8d23-cd99-4e7a-909d-338feffbea4b.png">|<image width = "950" alt="step 3-4" src="https://user-images.githubusercontent.com/98358127/189460803-6ba213d2-5018-477c-bc85-da64f12aabfd.png">|<image width = "950" alt="step 3-4" src="https://user-images.githubusercontent.com/98358127/189460651-fb0f8d23-cd99-4e7a-909d-338feffbea4b.png">
