### ISSUE TITLE
Wrong Images on PopYard.org

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#2318]
## Description 
Same issue as https://github.com/brave/browser-laptop/issues/3181

## Brave version (brave://version info)
0.56.15

### Reproducible on current release:
Yes

### Website problems only:  
Yes, lowering shields resolves the issue.

### Additional Information
The problem is with Brave replacing the `referer` header. This header is used by the image-host to determine which image should be returned.

**Comment by ryanbr** [comment]
@jonathansampson can you confirm this is resolved? site seems to okay (comparing Chrome with current release Brave)
