### ISSUE TITLE
[Android] Add an explicit "Block connections without VPN" setting to VPN (VPN kill switch)

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#23193]
## Description
When users purchase and use VPN on Android, a new connection will be created by the OS for the VPN (w/ hostname/user/pass)

When visiting in settings, you can enable `Always on` functionality which should force a reconnection if service is lost. We could offer a new setting (screenshot below has for reference) where we can block any outbound traffic on the device  when the VPN is not used. Here's an example from Express VPN:
![image](https://user-images.githubusercontent.com/4733304/171504570-f2b0fb52-c50e-49db-ac20-092bfcb19f12.png)

This is useful so that DNS or other info isn't leaked if the VPN connection is unintentionally dropped

cc: @mattmcalister

**Comment by deeppandya** [comment]
@bsclifton @mattmcalister i checked with latest release. if you have `Block connections without VPN` selected and turn off the vpn connection, it stops the connections from all other apps except Brave as tunnel is created with the Brave app.

**Comment by igornazarov1991** [comment]
@deeppandya , is "kill switch" available on iOS platform as well?

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.67.113`

- Verified as part of #38853 - verification notes are linked in https://github.com/brave/brave-browser/issues/38853#issuecomment-2165069937
