### ISSUE TITLE
Add Brave Search omnibox & SERP default engine promo P3A questions

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#23191]
Add two P3A questions for the new Brave Search omnibox Banner/Button promos (added in #22616), combined with default engine switches.

Did the participant in Group A click on "Try Brave Search" and did they switch their default engine to Brave Search?
`Brave.Search.Promo.Button`

0. No, No
1. Yes, No
2. No, Yes
3. Yes, Yes

Did the participant in Group B click on "Try Brave Search" and did they switch their default engine to Brave Search?
`Brave.Search.Promo.Banner`

0. No, No
1. Yes, No
2. No, Yes
3. Yes, Yes

Will raise PR soon.

**Comment by kjozwiak** [comment]
The above will require `1.41.79` or higher for `1.41.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```
Brave | 1.41.82 Chromium: 103.0.5060.66 (Official Build) beta (64-bit)
-- | --
Revision | 20b1569438a85e631d15e83eb355e3e326e5da6f-refs/branch-heads/5060@{#1066}
OS | Windows 10 Version 21H2 (Build 19044.1766)

```
