### ISSUE TITLE
Adblock redesign follow-up to #8838 

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#23194]
## Description 

Remove "Brave Ad block" item from the app menu as it is already available in Shields UI as "Filter lists" and available in settings
Change Shields UI "Filter lists" link from brave://adblock to brave://settings/shields/content-filters

## Expected result:

1. Go to hamburger/app menu and notice that Brave Ad Block is no longer listed.
2. Go to Shields and notice that link link for Filter list goes to brave://settings/shields/content-filters

## Reproduces how often: 

n/a

## Brave version (brave://version info)

Target release 1.41.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

Related issue: 
https://github.com/brave/brave-browser/issues/8838

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using

```
Brave | 1.41.65 Chromium: 103.0.5060.42 (Official Build) nightly (64-bit)
-- | --
Revision | de0d840bf9439c31bd86bf74f065c31fdf9b208d-refs/branch-heads/5060@{#667}
OS | Windows 11 Version 21H2 (Build 22000.739)
```

1. Confirmed `Brave Ad Block` no longer listed in the hamburger/app menu
2. Confirmed `Shields`-->`Filter List` link opens to `brave://settings/shields/filters` in NTP
3. Confirmed `brave://adblock` redirected to `brave://settings/shields/filters`

Note: As per #23222, the new URL is `brave://settings/shields/filters` Not `brave://settings/shields/content-filters` as the PR mentioned.

Step1|Step2|Step2A&Step3
---|---|---
<img width="954" alt="image" src="https://user-images.githubusercontent.com/98358127/173954870-26c9a74f-4a5c-45ec-ab35-8a61cc2d661f.png">|<img width="953" alt="image" src="https://user-images.githubusercontent.com/98358127/173955131-403858f2-c34e-4eec-b30a-7858d06016ca.png">|<img width="954" alt="image" src="https://user-images.githubusercontent.com/98358127/173955148-05289d2c-e03f-44ff-bc38-627f063e7dae.png">
