### ISSUE TITLE
Manage script should not show enforced by extension

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#232]
## Description 
Need to allow users to be able to change content settings set by shield extension. 

## Steps to Reproduce

   1. Build from source () and load any site in new tab
   2. Block scripts on the page 
   3. Click on Block script icon in URL bar and click manage, settings page shows exception added
   4. Hover over extension icon shows `This setting is enforced by the "" extension`

 ## Actual result:

![image](https://user-images.githubusercontent.com/17010094/40587972-b510bec2-61a4-11e8-9613-a8f90482988b.png)

## Expected result:
Should show shields as extension
## Reproduces how often: 

Easy

## Brave version (about:brave info)

2e9c470

**Comment by simonhong** [comment]
The enum value `SETTING_SOURCE_EXTENSION` of `enum SettingSource` in `content_settings.h` would have some clues.

**Comment by simonhong** [comment]
`chrome.braveShields.javascript.set({})` works well from shield with this https://github.com/brave/brave-core/pull/439/commits/228d872f0805e5fbebc0281d4cb329eea1f966ce,
When shields set javascript setting with this new api, user can edit this setting from page info bubble and setting page.

There are two issues are remained.
1. Async doesn't work `chrome.braveShields.javascript.setAsync({})` causes type error.
2. If shield set content settings, user can't edit because chrome disallow edit settings touched by extension.

**Comment by simonhong** [comment]
Waiting to https://github.com/brave/brave-extension/pull/62 to build brave-extension for test.

**Comment by simonhong** [comment]
Testing is in progress with https://github.com/brave/brave-extension/pull/63.

**Comment by simonhong** [comment]
Need to check current behavior isn't affected.
* BraveContentSettingsObserver
* BraveContentSettingsStore

**Comment by simonhong** [comment]
With current PR, user only can edit after user changes from shields because settings by extension is cleared when shields set is called.
User can't edit from page info bubble or settings page before user changes settings from shields.
Need to find a way to make user be able to edit always.

**Comment by simonhong** [comment]
@bbondy  So far, we are using different for set content settings.
 When shields changes settings,

**Comment by bbondy** [comment]
@simonhong please post an issue for the last comment that you made and we can move forward with landing what you have for this one.  I think we can not have the second part you mention for 0.55.x.

**Comment by simonhong** [comment]
@bbondy Ok, I'll create new issue about above my last comment after finishing review of https://github.com/brave/brave-core/pull/439 because that will be happened when https://github.com/brave/brave-core/pull/439 is merged.

**Comment by simonhong** [comment]
User can edit script settings from settings or page info bubble with https://github.com/brave/brave-extension/pull/63.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.55.11 Chromium: 70.0.3538.35 (Official Build) beta(64-bit)
-- | --
Revision | 28dcb499844fa40c28d5f62e337876cb936f79f5-refs/branch-heads/3538@{#678}
OS | Linux

![screenshot from 2018-10-05 15-47-56](https://user-images.githubusercontent.com/17010094/46556951-3266c880-c8b6-11e8-99df-7ce55e0675d6.png)
![screenshot from 2018-10-05 15-48-37](https://user-images.githubusercontent.com/17010094/46556952-3266c880-c8b6-11e8-801e-b5758212b74b.png)
