### ISSUE TITLE
Update spelling of image on NTP

### ISSUE THREAD

**Issue by rossmoody** [brave/brave-browser#2320]
Need to fix the spelling from "Tuolome Meadows" to "Tuolumne Meadows".

![image](https://user-images.githubusercontent.com/29072694/49323740-d050cb00-f4d4-11e8-9f97-7ed14b137cbe.png)

Also need an update from "Paris: Conciergeri" to "Paris: Conciergerie"

**Comment by Arthur111** [comment]
Same with "Paris conciergeri"
Its "Paris conciergerie"
