### ISSUE TITLE
Sync Nightly code causes failure on Beta and Stable

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#23206]
## Description 

Time-limited sync code words from current Nightly (1.41.x) when are entered into Beta (1.40.x) or Stable (1.39.x) causes Error: GenerateCryptoErrorsForTypes@components/sync/driver/data_type_manager_impl.cc:35, cryptographer error was encountered:	

## Steps to Reproduce

   1. Take Nightly browser (1.41.x)
   2. Create a sync chain, copy sync code for desktop into clipboard
   3. Take Beta (1.40.x)
   4. Join the sync chain with words from the clipboard

## Actual result:

Device list is empty

![image](https://user-images.githubusercontent.com/24739341/171610214-80c691b0-bf47-47f0-9afb-803be2939e55.png)

sync-internals page has error messages
![image](https://user-images.githubusercontent.com/24739341/171610343-d391375d-c5a0-45f7-8eef-1d73e45a69c1.png)

## Expected result:
It should be error displayed after attempt to reach the sync chain.

## Reproduces how often: 

***Easily***

## Brave version (brave://version info)

Brave | 1.40.80 Chromium: 102.0.5005.78 (Official Build) unknown (64-bit)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards?  N/A
- Is the issue reproducible on the latest version of Chrome?  N/A

**Comment by kjozwiak** [comment]
This was a desktop specific fix but we should verify/ensure that restoring a new time-based sync code that's `25 words` fails on `1.40.x` which doesn't include https://github.com/brave/brave-core/pull/12300. @brave/qa-team some more context/STR can be found via https://github.com/brave/brave-core/pull/13574#issuecomment-1148129475. Please ping me if anyone has any questions re: QA.

**Comment by kjozwiak** [comment]
Closing as https://github.com/brave/brave-core/pull/13574 was merged into `1.40.x`. The above will require `1.40.87` or higher for `1.40.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.40.87 Chromium: 102.0.5005.78 (Official Build) beta (x86_64)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | macOS Version 11.6.6 (Build 20G624)

and 

Brave | 1.41.42 Chromium: 102.0.5005.78 (Official Build) nightly (x86_64)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | macOS Version 11.6.6 (Build 20G624)

### Steps:
1. installed `1.40.87` (`beta`) and `1.41.42` (`nightly`)
2. launched Brave `nightly`
3. opened `brave://sync`
4. clicked on `Start a new Sync Chain` (`25`-word count)
5. copied Sync code
6. launched Brave `beta`
7. opened `brave://sync`
8. clicked on `I have a Sync Code`
9. pasted the Sync code from `nightly`
10. clicked on `Confirm`
11. clicked on `OK`

Confirmed I saw the `Invalid sync code, please check and try again.` error message on the `Enter a sync code` dialog

`nightly sync code` | `brave://sync` (`confirm`) | `brave://sync` (`OK`) | `error message` | `brave://sync-internals`
-----------------------|-----------------------|------------------|------------|--------
<img width="1518" alt="Screen Shot 2022-06-07 at 3 18 10 PM" src="https://user-images.githubusercontent.com/387249/172494413-35d640fb-3d31-4862-9619-0017d2ae3397.png"> | <img width="1455" alt="Screen Shot 2022-06-07 at 3 20 54 PM" src="https://user-images.githubusercontent.com/387249/172494449-b96e66bc-3214-4d0c-9d1d-c1becd7d2602.png"> | <img width="1455" alt="Screen Shot 2022-06-07 at 3 21 01 PM" src="https://user-images.githubusercontent.com/387249/172494452-5e9a62f8-f016-49f9-a334-4c06d143e514.png"> | <img width="1455" alt="Screen Shot 2022-06-07 at 3 21 26 PM" src="https://user-images.githubusercontent.com/387249/172494682-9025d418-4b25-445e-8bb6-1d8ebea1e50b.png"> | <img width="1455" alt="Screen Shot 2022-06-07 at 3 23 05 PM" src="https://user-images.githubusercontent.com/387249/172494650-b6f8a46e-33d6-440f-b40e-f6baa492250a.png">

**Comment by MadhaviSeelam** [comment]
### Verification `PASSED` using 

```
Brave	1.41.42 Chromium: 102.0.5005.78 (Official Build) nightly (64-bit) 
Revision	df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS	Windows 11 Version 21H2 (Build 22000.675)
```
and 

```
Brave	1.40.87 Chromium: 102.0.5005.78 (Official Build) beta (64-bit) 
Revision	df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS	Windows 11 Version 21H2 (Build 22000.675)
```

### Steps:
1. installed `1.40.87` (`beta`) and `1.41.42` (`nightly`)
2. launched Brave `nightly`
3. opened `brave://sync`
4. clicked on `Start a new Sync Chain` (`25`-word count)
5. copied Sync code
6. launched Brave `beta`
7. opened `brave://sync`
8. clicked on `I have a Sync Code`
9. pasted the Sync code from `nightly`
10. clicked on `Confirm`
11. clicked on `OK`

Confirmed I saw the `Invalid sync code, please check and try again.` error message on the `Enter a sync code` dialog

`nightly sync code` | `brave://sync` (`confirm`) | `brave://sync` (`OK`) | `error message` | `brave://sync-internals`
----|----|----|----|----
<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/172501286-4262a642-a178-47ed-8e96-21629ab8bbf6.png">|<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/172501216-07cfdd67-ea28-4718-a2dc-75e7a4e78f98.png">|<img width="455" alt="image" src="https://user-images.githubusercontent.com/98358127/172501206-417012ed-1bee-435a-a5f2-ce7592287a14.png">|<img width="460" alt="image" src="https://user-images.githubusercontent.com/98358127/172501417-faefa445-2fe5-4ee9-979f-333848cb5a60.png">|<img width="798" alt="image" src="https://user-images.githubusercontent.com/98358127/172501606-6b321969-7781-4b77-8ab8-3cf36effcc06.png">

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21 5G` & `Tab S7` using 

```
Brave	1.40.96 Chromium: 102.0.5005.115 (Official Build) beta (64-bit) 
Revision	174dbe6e33bc81994fceb71d751be201d0b4803d-refs/branch-heads/5005_109@{#3}
OS	Android 12; Build/SP1A.210812.016
```

- Confirmed sync error message is displayed when joining sync chain generated by nightly release that contains 25 word sync code by entering the code words.
- Confirmed sync fails and displays error message on Android ARM using sync code from Nightly Desktop.
- Confirmed sync fails and displays error message on Android ARM using sync code from Nightly build on mobile.

Mobile | Tablet
-|-
![screenshot-1655345032341](https://user-images.githubusercontent.com/17885425/173978710-860f6014-afd3-43a7-8adf-a567983539ce.png) | ![screenshot-1655346633381](https://user-images.githubusercontent.com/17885425/173978713-72b7b3b7-47e5-4e8e-aa70-038f72c29e0e.png)
