### ISSUE TITLE
Add a loading state when switching between Filecoin Mainnet to Testnet

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23201]
## Description 

Add a loading state when switching between Filecoin Mainnet to Testnet

## Steps to Reproduce

   1. Import Filecoin from Ledger
   2. Switch to Testnet
   3. Shows Mainnet accounts for a few seconds before loading Testnet accounts

## Actual result:

https://user-images.githubusercontent.com/17010094/171572162-db074d4a-eeba-4deb-bfac-fcffed8472e3.mov

## Expected result:
Add a loading state so user doesn't pick mainnet accounts for testnet

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.40.80 Chromium: 102.0.5005.78 (Official Build) beta (64-bit)
-- | --
Revision | `df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel @muliswilliam @cypt4

**Comment by yrliou** [comment]
Removing 1.40.x as testnet will be disabled.
