### ISSUE TITLE
Browser crashes when trying to remove a pre-populated network

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23205]
## Description 
Reported by @supermassive, Browser crashes when trying to remove a pre-populated network

## Steps to reproduce 

   1. Install 1.40.83 Beta build
   2. Open Settings -> Wallet -> Networks
   3. Tap on menu button for pre-populated network and click on remove, browser crashes

## Actual result 

https://user-images.githubusercontent.com/17010094/171601204-f6f56b7a-f46b-4073-9afe-f1e0345db52f.mp4

## Expected result
No crash just remove the network from the list

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 12
   
## Brave version
1.40.83

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @supermassive @Pavneet-Sing @SergeyZhukovsky

**Comment by kjozwiak** [comment]
The above will require `1.40.91` or higher for `1.40.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.40.101 x64 build
- Verified known EVM's that are pre-loaded are not listed as custom networks hence no way to delete it. More info here https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1654684730512659

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/174317145-d5ef561b-7df3-46bf-865f-b633da88908e.mp4> | <video src=https://user-images.githubusercontent.com/17010094/174317128-4f676650-c438-4f3b-8cbf-ee99259f322a.mp4>
