### ISSUE TITLE
Selecting Testnet Token shows Mainnet account details 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23200]
## Description 

Selecting Testnet Token shows Mainnet account details 

## Steps to Reproduce

   1. Have a wallet with balance on both Mainnet and Testnet
   2. Enable Show Testnets from settings
   3. Go back to portfolio and filter out to a testnet (Ropsten or Filecoin)
   4. Click on the token name 
   5. Loads Mainnet details, accounts listed are showing balance from Mainnet rather than testnet

Note: this is more clear when using Filecoin as the account names are different for mainnet and testnet

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/171571758-a61e1fac-1fec-4625-ae1c-c7d7adbc6f9c.png)

## Expected result:
Should show Testnet when Token from Testnet is selected

## Reproduces how often: 

Easy

## Brave version (brave://version info)

All

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @muliswilliam

**Comment by yrliou** [comment]
Removing 1.40.x as testnet will be disabled.
