### ISSUE TITLE
Toggle to hide networks in wallet ui

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#23208]
Wallet network settings should have a per-network toggle to control network visibility in wallet ui.

**Comment by Uni-verse** [comment]
Verification `PASSED` using

```
Brave	1.41.91 Chromium: 103.0.5060.114 (Official Build) beta (64-bit) 
Revision	a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS	Windows 11 Version 21H2 (Build 22000.318)
```
Using STR/Test Plan in https://github.com/brave/brave-core/pull/13710#issue-1265860635

- Confirmed there is now an "Eye" button for each network to toggle its visibility in wallet ui.
- Confirmed the active network is marked with `bold` and always visible.
- Confirmed user is able to toggle visibility on `non-preloaded networks` and `custom networks` manually added.
- Confirmed when network is `as as active`, the eye icon is not shown.
- Confirmed eye icon shows correct state for `visible/hidden` setting.
- Confirmed changing the active network in the wallet panel will be reflect in the `brave://settings/wallet/networks` page (user has to reload page)


Example | Example | Example
-|-|-
![Screen Shot 2022-07-08 at 11 59 46 AM](https://user-images.githubusercontent.com/17885425/178058854-9943e75b-ac5a-4fde-8b52-23e20906c21e.png) | ![Screen Shot 2022-07-08 at 12 03 19 PM](https://user-images.githubusercontent.com/17885425/178058856-287430ea-b53a-4713-b622-89b18d0259b6.png) | ![Screen Shot 2022-07-08 at 11 59 06 AM](https://user-images.githubusercontent.com/17885425/178058847-c1954b46-1178-4478-8929-bad674d4decd.png)

**Comment by Uni-verse** [comment]
Verification `PASSED` using

```
Brave	1.41.91 Chromium: 103.0.5060.114 (Official Build) beta (64-bit) 
Revision	a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS	Linux (Debian version 11)
```

Using STR/Test Plan in https://github.com/brave/brave-core/pull/13710#issue-1265860635

- Confirmed there is now an "Eye" button for each network to toggle its visibility in wallet ui.
- Confirmed the active network is marked with `bold` and always visible.
- Confirmed user is able to toggle visibility on `non-preloaded networks` and `custom networks` manually added.
- Confirmed when network is `as as active`, the eye icon is not shown.
- Confirmed eye icon shows correct state for `visible/hidden` setting.
- Confirmed changing the active network in the wallet panel will be reflect in the `brave://settings/wallet/networks` page (user has to reload page)

![Screen Shot 2022-07-08 at 2 00 49 PM](https://user-images.githubusercontent.com/17885425/178071121-62d61dd7-a7a7-483b-aa30-abebf62f0db0.png)
