### ISSUE TITLE
DApps: Crash on a 3 dots click on a panel on Android 6 and 7

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#23215]
We have a crash on Android 6 and 7 devices when we click 3 dots on the right upper corner on a DApps panel.
That's because Android 6 and 7 don't work properly with `androidx.appcompat.widget.PopupMenu` and the menu cannot be anchored to any element in a PopupWindow which is our panel.
I anchored it to a toolbar, the same anchor as for the whole panel. Plus we won't have icons on Android 6 and 7 in the menu. We can probably improve that later, but I don't think it's worth an effort as we have a very small fraction of users on such old devices.

**Comment by kjozwiak** [comment]
The above will require `1.40.88` or higher for `1.40.x` verification 👍
