### ISSUE TITLE
100% 'Browser' CPU Usage in Bult-inTask Manager

### ISSUE THREAD

**Issue by SibilantScream** [brave/brave-browser#23225]
## Description 
Right off starting the browser it consumes 100% in bultin Task Manage (25% in windows's).
Even with no tabs open (1 blank tab)
RAM is at 200MB.
The Windows process lingers untill I force-kill it.

## Steps to Reproduce
Simply start the app, no need to do anything else.

## Brave version (brave://version info)
Latest version as of the date of this post.
About page says 

> [Version 1.39.111 Chromium: 102.0.5005.61 (Official Build) (64-bit)](https://brave.com/latest/)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- There's no hard disable on Shield I can find but I did try disabling all sliders.
- 
- Does the issue resolve itself when disabling Brave Rewards? 
- No.
- 
- Is the issue reproducible on the latest version of Chrome? 
- No.

## Miscellaneous Information:
Windows 7, i7 Intel CPU, FirePro 5800m, 8gb RAM.

**Comment by TechMaz** [comment]
Having a similar problem on Mac since updating to the latest release.

**Comment by rebron** [comment]
cc: @btlechowski For Windows 7.
@atuchin-m

**Comment by SibilantScream** [comment]
Forgot to mention that this coincides with me recently switching Override software rendering list on, yet not instantly & turning it off doesn't help.
Also tried Cosmetic Filtering on\off.

**Comment by SibilantScream** [comment]
> @SibilantScream What other flags do you have set in brave://flags? That type of information is important. Can you update to the latest 1.40.105 and see if that helps and toggle any of those flags back to default.

Forced Colors is toggled off, the rest is set to default.
[Version 1.40.105 Chromium: 103.0.5060.53 (Official Build) (64-bit)](https://brave.com/latest/)
Problem no longer persists as of the latest 2 versions or so.

> With no tabs open you mean you're seeing only the default new tab page correct? Or did you set new tab page to display as blank page?
Totally blank page, no background & wallet info etc.

> Also wanted to check to see if in brave://settings/search you have Web Discovery Project on.
It's off.

**Comment by rebron** [comment]
@SibilantScream Going to close this one off as it sounds like per your last comment it's no longer happening with the current release (or 2 releases ago). If it does happen again we can reopen this issue.
