### ISSUE TITLE
Dapps: Notification badge implementation on Wallet Icon in address bar

### ISSUE THREAD

**Issue by qamarngr** [brave/brave-browser#23220]
We need to show the Notification Badge (Red Dot) on Wallet icon in address bar

**Cases for badge to show**

Ff the user doesn't interact with the toast notification then wallet icon should have that notification.

- Dapp trying to connect

- Incomplete transaction

- Signature request but user closes the sign window

**Comment by kjozwiak** [comment]
The above will require `1.40.102` or higher for `1.40.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.40.105 x64 build
- Verified steps from issue description
- Verified a notification badge is shown when there is a pending action on the wallet
- Verified with pending transaction in place closing and reopening browser and triggering the Dapp interaction shows the notification dot on the wallet icon

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/174775407-e8655a34-d6f7-4b5f-b78c-8eb70fcaa1b8.mp4> | <video src=https://user-images.githubusercontent.com/17010094/174778141-6506402c-b7d9-4883-9975-917392a15e26.mp4>
