### ISSUE TITLE
Follow up issues on Shields adblock section in settings

### ISSUE THREAD

**Issue by nullhook** [brave/brave-browser#23222]
Fine-tune the Shield's Adblock settings frontend:

- Add "Fade out" of filter lists at the bottom
- First title of the page should be "Content filters" and not "Content Filtering"
- Casing inconsistencies - "Custom Filters" -> "Custom filters"
- "Custom lists" table section title should be 14px not 12px
- Colors in the table:
   - Table heading color
   - Different row bg based on if the item is enabled
   - Red color for "Download failure"
- Last updated should show time last updated even if latest try was failure
- Subtitles get their different color style

## Design
<img width="682" alt="Screen Shot 2022-06-13 at 3 06 49 PM" src="https://user-images.githubusercontent.com/5951041/173453256-c9d452ce-3042-4ad5-a27c-acb4238c0454.png">

Figma link: https://www.figma.com/file/tLXWGCpNoiJxDZDdpfordj/branch/A3RrnDB8Iib4k2ExACTNpM/Desktop-Settings

**Comment by antonok-edm** [comment]
Two more now that https://github.com/brave/brave-core/pull/13421 is merged:
- `title` field from the list data can be shown instead of the subscription URL, if available (and the column header should change from `List URL` to just `Filter list`)
- `homepage` field from the list data can be presented as an additional link in the subscription's dropdown menu, if available

see older designs from https://github.com/brave/brave-browser/issues/8107 for reference

**Comment by nullhook** [comment]
Created a separate issue for "Reset to defaults" as it's more involved: https://github.com/brave/brave-browser/issues/23309

**Comment by MadhaviSeelam** [comment]
Verification `In-progress` using
```
Brave | 1.41.65 Chromium: 103.0.5060.42 (Official Build) nightly (64-bit)
-- | --
Revision | de0d840bf9439c31bd86bf74f065c31fdf9b208d-refs/branch-heads/5060@{#667}
OS | Windows 11 Version 21H2 (Build 22000.739)
```

- Confirmed "Fade out" of filter lists at the bottom
- First title of the page should be "Content filters" and not "Content Filtering"
- Casing inconsistencies - "Custom Filters" -> "Custom filters"

Dark|Light
---|---
<img width="946" alt="image" src="https://user-images.githubusercontent.com/98358127/173892351-f956e5ef-52c0-48de-a29e-4ba95776fc7f.png">|<img width="955" alt="image" src="https://user-images.githubusercontent.com/98358127/173892408-182c03ec-7116-4cff-9858-443e8e387dde.png">

**Comment by aguscruiz** [comment]
Updated figma link here:
https://www.figma.com/file/tLXWGCpNoiJxDZDdpfordj/branch/A3RrnDB8Iib4k2ExACTNpM/Desktop-Settings?node-id=1636%3A30096
