### ISSUE TITLE
Left pane of settings is hidden on windows of width 890 and smaller

### ISSUE THREAD

**Issue by lil5** [brave/brave-browser#23232]
## Description 
Left pane of settings is hidden on windows of width 890 and smaller

Here is a youtuber @heavyelement showing the bug
https://youtu.be/JHvMsZMYnsE?t=342

## Steps to Reproduce
   1. Open brave
   2. Open settings
   3. Resize the browser window to less than 900 width

## Actual result:
Left pane is hidden

## Expected result:
A hamberger menu or select button include the links of the left pane.

## Reproduces how often: 
Always

## Desktop Brave version:
1.39.111

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by IronMaltese** [comment]
I would love to see this implemented since it turns a lot of people away and causes needless confusion, also settings don't show up when I split my screen on my laptop

**Comment by lil5** [comment]
@IronMaltese please just add a thumbs up 👍 instead of adding unnecessary commentary

**Comment by brunolpsousa** [comment]
@lil5 I think this can be closed now as the issue was fixed at some point, right?

**Comment by lil5** [comment]
Thanks for the reminder @brunolpsousa , yes this issue is by now fixed!
