### ISSUE TITLE
Browser crash when selecting `Ethereum Name Service` from Shields & Privacy settings

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23231]
## Description 
Browser crash when selecting `Ethereum Naming Service` from Shields & Privacy settings

## Steps to reproduce 

   1. Clean install 1.40.83
   2. Go to Menu -> Shields & privacy -> ENS
   3. Browser crashes when ENS is selected
   
## Actual result 

https://user-images.githubusercontent.com/17010094/171838918-93e51065-e651-49d1-8aa5-cee89d73a0fc.mp4

## Expected result
No crash

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 12
   
## Brave version
1.40.83

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @yrliou @SergeyZhukovsky

**Comment by kjozwiak** [comment]
The above will require `1.40.91` or higher for `1.40.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.40.101 x64 build
- Verified no crash when selecting `Ethereum Name Service` from Brave Shields & privacy settings
------
Verification passed on Samsung Tab A with Android 10 running 1.40.101 x64 build
- Verified no crash when selecting `Ethereum Name Service` from Brave Shields & privacy settings
