### ISSUE TITLE
Delete a URL entry from omnibar

### ISSUE THREAD

**Issue by PunnyBoi** [brave/brave-browser#2323]
## Description 
Is there any way to delete a URL suggestion from omnibar? I tried shift+delete method (as I used to do in Chrome) but it didn't work?

## Brave version (brave://version info)
Brave: 0.56.15 Chromium: 70.0.3538.110 (Official Build) (64-bit)
OS: Windows

**Comment by tomlowenthal** [comment]
Seems to be working normally on MacOS.

**Comment by tomlowenthal** [comment]
@brave/legacy_qa Can y'all check this out?

**Comment by srirambv** [comment]
@PunnyBoi mind recording what you are seeing? Are you saying you don't want to see the site suggestions come up in URL bar when you start typing? 

Please use the template to fill out as much details as possible. Would avoid back and forth conversations

**Comment by kjozwiak** [comment]
I'm assuming @PunnyBoi wants to remove the baked in auto suggestions from the Alexa 500 list that we use by default. I'm not sure if there's a way to actually disable that.

**Comment by PunnyBoi** [comment]
Hello, sorry for replying so late. @kjozwiak I don't think that's what I mean (though I am unable to understand completely what you said as I am unknown to the terms like 'Brave's baked'). Let me give you an example. Suppose there is a particular website you visited say 'www.youtube.com/watch_BlahBlahBlah'. The URL is unique, i.e. it is not general like 'www.google.com' or 'www.youtube.com'. But now whenever you start writing 'www.you...' in the omnibar, Brave auto-suggests the URL 'www.youtube.com/watch_BlahBlahBlah'. I don't want brave to suggest me this URL. So what I do, I will clear my history, cookies etc. Even after doing so, Brave still indicates this URL in the omnibar. In Chrome, there is a way to delete this URL (without clearing history etc.):
1) Write the complete URL in the omnibar.
2) Highlight or select the URL.
3) Press 'shift+delete'.
But in brave, this method doesn't work. @tomlowenthal said it works on Mac. I am on windows, and that's why I asked someone to confirm whether this trick works on Windows or not? For me, it doesn't seem to be working.

**Comment by bsclifton** [comment]
Shift + delete works great now (tested on Windows 10, x64)
