### ISSUE TITLE
Browser crash when trying to close a background tab with active connect to Dapp

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23239]
## Description 

Browser crash when trying to close a background tab with active connect to Dapp

## Steps to Reproduce (Possible steps)

   1. Unlock wallet
   2. Open a dapp in a new tab and initiate connection (I used `https://app.1inch.io` and `https://app.uniswap.org` that had a connection popup)
   3. Switch to a different tab so the tab from step 2 is a background tab
   4. With Dapp tab being in background close the tab, browser crashes

## Actual result:

Browser crash

## Expected result:
No crash just close tab

## Reproduces how often: 

Easy 

## Brave version (brave://version info)

Brave | 1.39.117 Chromium: 102.0.5005.78 (Official Build) (64-bit)
-- | --
Revision | `df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Dont know
- Can you reproduce this issue with the nightly channel? Dont know

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

Mac Uploaded crash report ID : `19f50600-2578-4408-0000-000000000000`
Linux Uploaded crash report ID: `68f90600-2578-4408-0000-000000000000`

**Comment by iefremov** [comment]
@srirambv can you re-repro the crash please?

**Comment by srirambv** [comment]
Can't repro this crash anymore. Closing as stale
