### ISSUE TITLE
DApps: sign message Fragment doesn't show a real message

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#23242]
## Steps to reproduce 

   1. Execute `eth_sign` with some message

## Actual result 
Observe that there is no an actual message

## Expected result
Should be a message

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above will require `1.40.89` or higher for `1.40.x` verification 👍
