### ISSUE TITLE
Aw, Snap! This is happening all the time now

### ISSUE THREAD

**Issue by crsssl** [brave/brave-browser#23248]
## Description 
For the last couple months, the browser on Android keeps failing, and on many pages (even Brave's help pages) 

## Steps to Reproduce
--> Just click to a page

## Actual result:
See screenshots

## Expected result:
Display the page!

## Reproduces how often: 
All the time, many pages

## Brave version (info found on brave://version)
See screenshot

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

![Screenshot_20220604-085502_Brave](https://user-images.githubusercontent.com/2931768/172003499-515881ff-3506-4d00-98dc-942f3158c7b8.jpeg)
![Screenshot_20220604-085552_Brave](https://user-images.githubusercontent.com/2931768/172003500-58316e40-0ada-42d4-a153-34076f71a617.jpeg)
![20220604_085417](https://user-images.githubusercontent.com/2931768/172003502-4f731657-cca9-4ae6-b45d-968436caa0bb.jpeg)

**Comment by bridiver** [comment]
This is an extremely old version of Brave, can you try updating to the latest version?

**Comment by bridiver** [comment]
Actually I'm a little confused here because it shows a copyright of 2022, but a chromium version of 81 which is very old. Did you get this from the google app store?

**Comment by crsssl** [comment]
Yes. Off the Google App Store. Is Brave not informing the store about updates?

**Comment by crsssl** [comment]
I forced an upgrade to1.39.115. Let's see a what happens.

**Comment by bridiver** [comment]
> Yes. Off the Google App Store. Is Brave not informing the store about updates?

No, I was wondering if you got it someplace else and that's why it was such an old version.

**Comment by crsssl** [comment]
> No, I was wondering if you got it someplace else and that's why it was such an old version.

Sorry for the delayed reply...
I can't be 100% sure, as I've had Brave for quite awhile. In any case, the problem is pretty much resolved now, thanks to you looking into this.
