### ISSUE TITLE
Use separate keyrings and correct root paths for filecoin mainnet and non-mainnet accounts

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#23241]
https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1654279051831389

**Comment by yrliou** [comment]
We should
1) revise GetCoinForKeyring to use separate keyring (different keyring ID) for filecoin mainnet and non-mainnet accounts. Can use `GetCurrentChainId` from brave_wallet_utils.cc for the current network info.
2) revise `GetRootPath` in keyring_service.cc to return correct and different root path for filecoin mainnet and non-mainnet keyrings.

cc @darkdh

**Comment by darkdh** [comment]
Also need to take care of `KeyringService::GetKeyringIdForCoin` for ` mojom::CoinType::FIL` when current network info is non-mainet

**Comment by yrliou** [comment]
Remove release/blocking since we are going to disable testnets instead first https://github.com/brave/brave-browser/issues/23367.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.43.81 Chromium: 104.0.5112.102 (Official Build) (64-bit)
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | Linux

- Verified steps from [ brave/brave-core#13895](https://github.com/brave/brave-core/pull/13895)
- Verified Filecoin mainnet accounts have a different naming convention starting with `f`
- Verified Filecoin testnet accounts have a different naming convention starting with `t`
- Verified when no Filecoin account is created, selecting Filecoin (Mainnet/Testnet) prompts to create an account on the selected network
- Verified able to create both Mainnet and Testnet accounts and are listed one below the other irrespective of how its created
- Verified transaction works on Mainnet 
- Encountered [#24824](https://github.com/brave/brave-browser/issues/24824), [#24946](https://github.com/brave/brave-browser/issues/24946), [#24947](https://github.com/brave/brave-browser/issues/24947) & [#24949](https://github.com/brave/brave-browser/issues/24949)


------------------------
Verification passed on

Brave | 1.43.81 Chromium: 104.0.5112.102 (Official Build) (64-bit)
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | Windows 11 Version 21H2 (Build 22000.795)

- Verified steps from [ brave/brave-core#13895](https://github.com/brave/brave-core/pull/13895)
- Verified Filecoin mainnet accounts have a different naming convention starting with `f`
- Verified Filecoin testnet accounts have a different naming convention starting with `t`
- Verified when no Filecoin account is created, selecting Filecoin (Mainnet/Testnet) prompts to create an account on the selected network
- Verified able to create both Mainnet and Testnet accounts and are listed one below the other irrespective of how its created
- Verified transaction works on Mainnet
- Encountered [#24824](https://github.com/brave/brave-browser/issues/24824), [#24946](https://github.com/brave/brave-browser/issues/24946), [#24947](https://github.com/brave/brave-browser/issues/24947) & [#24949](https://github.com/brave/brave-browser/issues/24949)


------------------------
Verification passed on

Brave | 1.43.81 Chromium: 104.0.5112.102 (Official Build) (arm64)  
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [ brave/brave-core#13895](https://github.com/brave/brave-core/pull/13895)
- Verified Filecoin mainnet accounts have a different naming convention starting with `f`
- Verified Filecoin testnet accounts have a different naming convention starting with `t`
- Verified when no Filecoin account is created, selecting Filecoin (Mainnet/Testnet) prompts to create an account on the selected network
- Verified able to create both Mainnet and Testnet accounts and are listed one below the other irrespective of how its created
- Verified transaction works on Mainnet
- Encountered [#24824](https://github.com/brave/brave-browser/issues/24824), [#24946](https://github.com/brave/brave-browser/issues/24946), [#24947](https://github.com/brave/brave-browser/issues/24947) & [#24949](https://github.com/brave/brave-browser/issues/24949)
