### ISSUE TITLE
`Prevent sites from fingerprinting...` pref is listed twice in `brave://settings/shields`

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#23246]
## Description 

`Prevent sites from fingerprinting...` pref is listed twice in `brave://settings/shields`

## Steps to Reproduce

   1. install `1.41.36`
   2. launch Brave
   3. open `brave://settings/shields`
   4. look for `Prevent sites from fingerprinting...`

## Actual result:

It's repeated, and either toggle toggles the other's state, so they're in-sync

<img width="978" alt="Screen Shot 2022-06-04 at 12 38 13 AM" src="https://user-images.githubusercontent.com/387249/171989890-12cc400e-a4f8-4130-9ff4-d6e650978196.png">

## Expected result:

Shows only once, in the appropriate section

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.41.36 Chromium: 102.0.5005.78 (Official Build) nightly (x86_64)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | macOS Version 12.5 (Build 21G5027d)

cc @pes10k @ShivanKaul @rebron

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.41.62 Chromium: 103.0.5060.42 (Official Build) nightly (x86_64)
-- | --
Revision | de0d840bf9439c31bd86bf74f065c31fdf9b208d-refs/branch-heads/5060@{#667}
OS | macOS Version 12.5 (Build 21G5037d)

#### Followed my original steps to reproduce, and confirmed the redundant pref entry is gone

<img width="1312" alt="Screen Shot 2022-06-14 at 2 31 30 PM" src="https://user-images.githubusercontent.com/387249/173692716-4185296a-d47b-44ef-9f14-6f3a302b9206.png">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED`
```
Brave | 1.41.72 Chromium: 103.0.5060.42 (Official Build) beta (64-bit)
-- | --
Revision | de0d840bf9439c31bd86bf74f065c31fdf9b208d-refs/branch-heads/5060@{#667}
OS | Windows 11 Version 21H2 (Build 22000.739)
```
Followed STR above
Confirmed the redundant pref entry `Prevent sites from fingerprinting...` is removed
<img width="959" alt="image" src="https://user-images.githubusercontent.com/98358127/174413773-8cdeb525-d95b-43a5-9920-2baab9bef7d4.png">
