### ISSUE TITLE
Scroll position in viewport not retained on `Back` navigation after clicking article

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#23244]
## Description 

(Found while testing https://github.com/brave/brave-browser/issues/20129.)

Scroll position in viewport not retained on `Back` navigation after clicking article

## Steps to Reproduce

   1. install `1.41.36`
   2. launch Brave
   3. open a new-tab page
   4. scroll down
   5. click on `Show Brave News`
   6. scroll to find an article
   7. note the article and your scroll position within the viewport
   8. click on the article
   9. wait for the page to finish loading in the current tab
   10. click on the `Back` `<` button on the browser toolbar
   11. confirm correct article and scroll position

## Actual result:

 initial viewport position | article loaded | `Back`-button navigation | after scroll 
---|---|---|---|
<img width="1312" alt="Screen Shot 2022-06-03 at 2 47 20 PM" src="https://user-images.githubusercontent.com/387249/171958496-4add52d5-9a46-4065-b8bd-4764e0d70263.png"> | <img width="1312" alt="Screen Shot 2022-06-03 at 2 47 28 PM" src="https://user-images.githubusercontent.com/387249/171958506-e7daf665-da7d-474c-b974-b66ef266f0bd.png"> | <img width="1312" alt="Screen Shot 2022-06-03 at 2 47 34 PM" src="https://user-images.githubusercontent.com/387249/171958509-bb9b511e-340c-47eb-ab48-67b4174aa008.png"> | <img width="1312" alt="Screen Shot 2022-06-03 at 2 47 39 PM" src="https://user-images.githubusercontent.com/387249/171958514-3cf4fd84-7c6e-4465-9f66-901b42f384cf.png">

Returned to viewing a different article(s)

## Expected result:

Your scroll position within the viewport should be restored to your initial viewport position.

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.41.36 Chromium: 102.0.5005.78 (Official Build) nightly (x86_64)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | macOS Version 11.6.6 (Build 20G624)

@petemill @mattmcalister @srirambv

**Comment by stephendonner** [comment]
This should be something either @petemill or @fallaciousreasoning could fix.

**Comment by mattmcalister** [comment]
Fixed by #28351
