### ISSUE TITLE
Make an option to set solid color background for NTP

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#23255]
sub task of #15252 . Overall design also can be found there.

Spec:
  * Users can choose a solid color for NTP background
  * This will be applied only to the current local machine.
  * When Users choose another option like `custom background` and `brave background`, the background should be changes to it.

Open discussion:
  * ~~What about `sponsored images`?  The official version seems to show SI once per 4 new tabs. Need to check if this works same.~~ Currently, the same SI policy is applied to solid color bg too.

**Comment by sangwoo108** [comment]
@simonhong , is there any way to enable sponsored image feature when building Brave?

**Comment by petemill** [comment]
From a User Experience perspective, my opinion is that this needs the items to have a "selected" state. At the moment, in both the design and the implementation in this PR, there is no indicator as to which option is chosen. 

In the following, a solid color is chosen, but it is not clear:
<img width="437" alt="image" src="https://user-images.githubusercontent.com/741836/177075798-e1718ef5-1e5f-4821-96a1-754cb585fc58.png">

Perhaps we could use the same selection state from Top Sites' "Favorites" / "Frequently Visited" items: the border color and the "tick" ✅ icon overlay:

<img width="222" alt="image" src="https://user-images.githubusercontent.com/741836/177075554-2a8de1ca-3b40-4900-90bb-10077456d120.png">

And it could work like this:
- If the user has chosen "Brave backgrounds", then that item will have the selected state.
- If a user clicks on "Solid colors", it will **not** be selected, but if the user clicks on a specific solid color, then both that solid color **and** the general "Solid colors" item will both be selected.
- All items get the hover state border color.
- We can also fix the custom backgrounds option to also have the selected and hover states.

I'm not sure what the `:active:` (pressed) state would be as I don't believe the Top Sites' section has that defined.

@sangwoo108 we can confirm with @brave/design-team that they want this specific option. Do you want to address this in this PR or as a follow-up? I'm fine with a follow-up as long as it can land before the next channel migration to beta, as I think it's a release blocker.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.44.73 Chromium: 105.0.5195.68 (Official Build) beta (64-bit)
-- | --
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | Windows 11 Version 21H2 (Build 22000.856)
```

1. install 1.44.73
2. launch Brave
3. click `Skip welcome tour`
4. click `Customize` bottom right on the NTP
5. click Solid colors
6. select a color
7. confirmed NTP background is set to selected color
8. select another color and NTP background is set to selected color
9. verify Brave News is peeked as it's existing functionality 
10. click `Brave Backgrounds` to return to original background

step 4|step 5|step 6-7|step8-9|Step 10
----|----|----|----|----
<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/188246026-b845b390-2404-40c1-8a84-1e179c65d282.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/188246019-ed076977-2869-438d-8753-56a9b43ac6cc.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/188246038-7bc5cd02-d5d6-4be9-b832-fd2c30114d7f.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/188246047-7c94c7dc-f08a-408b-8059-9147e781acea.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/188246086-047e4288-75e6-4350-9b97-a7d9646fcc0d.png">

**Comment by stephendonner** [comment]
## Verified `PASSED` using 


Brave | 1.44.79 Chromium: 105.0.5195.102 (Official Build) beta (x86_64)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | macOS Version 13.0 (Build 22A5331f)

### Steps:
1. install 1.44.73
2. launch Brave
3. click Skip welcome tour
4. click Customize bottom right on the NTP
5. click Solid colors
6. select a color
7. confirmed NTP background is set to selected color
8. select another color and NTP background is set to selected color
9. verify Brave News is peeked as expected
10. click Brave Backgrounds to return to original background

step 4 | step 5 | step 6-7 | step 8-9 | step 10
-------|-------|----------|----------|--------
<img width="1312" alt="Screenshot 2022-09-08 at 11 42 06 AM" src="https://user-images.githubusercontent.com/387249/189201726-4e6b54c5-a759-493a-83b4-6ded4f557199.png"> | <img width="1312" alt="Screenshot 2022-09-08 at 11 42 26 AM" src="https://user-images.githubusercontent.com/387249/189201753-ebcd508e-e0dd-4546-9b7c-17fc392a74d1.png"> | <img width="1312" alt="Screenshot 2022-09-08 at 11 42 36 AM" src="https://user-images.githubusercontent.com/387249/189201758-2615f0be-8061-4458-b989-9acee8c22141.png"> | <img width="1312" alt="Screenshot 2022-09-08 at 11 42 41 AM" src="https://user-images.githubusercontent.com/387249/189201760-fcf32e56-0841-4289-ae7f-ed025a2f2a6a.png"> | <img width="1312" alt="Screenshot 2022-09-08 at 11 42 56 AM" src="https://user-images.githubusercontent.com/387249/189201762-1f2a8a8c-6586-4b8c-a3b1-6595acac71d0.png">

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

### Steps:

1. install `1.44.88`
2. launch Brave
3. click `Skip welcome tour`
4. click `Customize` bottom right on the NTP
5. click `Solid colors`
6. select a color
7. confirmed NTP background is set to selected color
8. select another color and NTP background is set to selected color
9. verify Brave News is peeked as expected
10. click `Brave Backgrounds` to return to original background

example | example | example | example | example | example
---------|----------|---------|----------|---------|----------
<img width="1752" alt="Screen Shot 2022-09-16 at 12 18 39 AM" src="https://user-images.githubusercontent.com/387249/190580082-f217daa6-6ffc-4074-b397-e379c54fb6d3.png"> | <img width="1752" alt="Screen Shot 2022-09-16 at 12 18 44 AM" src="https://user-images.githubusercontent.com/387249/190580101-c03f4bc3-ee92-4f93-bed9-0ec51a825e88.png"> | <img width="1752" alt="Screen Shot 2022-09-16 at 12 18 48 AM" src="https://user-images.githubusercontent.com/387249/190580111-af8d2584-5eb9-4009-915b-0b4dcfb63a91.png"> | <img width="1752" alt="Screen Shot 2022-09-16 at 12 18 57 AM" src="https://user-images.githubusercontent.com/387249/190580115-604239ca-1e78-448c-a06f-dcec76cf1afe.png"> | <img width="1752" alt="Screen Shot 2022-09-16 at 12 19 08 AM" src="https://user-images.githubusercontent.com/387249/190580116-ad506cfd-ac28-4696-a0cb-f2eb1ecb1aa9.png"> | <img width="1752" alt="Screen Shot 2022-09-16 at 12 19 39 AM" src="https://user-images.githubusercontent.com/387249/190580119-f2bef037-e5de-423d-a47f-25b6a17252c9.png">
