### ISSUE TITLE
[Feature] Support Firefox extensions

### ISSUE THREAD

**Issue by DaniellMesquita** [brave/brave-browser#2325]
I'm developing a Linux distro, and will be easier to move from Firefox to Brave, if it supports their extensions

Will be very good to see Brave showing colored tabs like Vivaldi does, thanks to a Firefox extension made by @nt1m (and it is just a powerful example of the possibilities)

**Comment by tomlowenthal** [comment]
It is extremely unlikely that Brave will ever support Firefox extensions.

**Comment by DaniellMesquita** [comment]
Duplicate of what?

**Comment by DaniellMesquita** [comment]
Also, why support Chrome extensions but not also support Firefox extensions? They aren't so different

**Comment by tomlowenthal** [comment]
Chrome extension support comes from the fact that Brave is based on Chromium.

**Comment by DaniellMesquita** [comment]
@srirambv labeled it as "feature/extension-request", but you'd removed the label and consider it as duplicate, but isn't showing what is the duplicate

**Comment by tomlowenthal** [comment]
It's not a duplicate. It's in the milestone for issues which have been closed for reasons other than "we finished building this".
