### ISSUE TITLE
Unable to copy code words from existing sync chain

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#23262]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/22420
Unable to copy code words from existing sync chain
## Steps to Reproduce

   1. Clean profile 1.40.x
   2. Create a sync chain between two devices
   3. Click on `View Sync Code`
   4. Copy QR code and confirm code words can be copied
   5. Click on `View QR Code`
   6. Click on `View Sync Code`
   7. Try to copy sync code, unable to copy sync code
   8. Click on close `x` on sync modal 
   9. Sync modal popup is not dismissed
   10. Enter `Esc` button modal popup gets dismissed
   
## Actual result:

Unable to copy code words from existing sync chain
![unable to copy sync code](https://user-images.githubusercontent.com/38657976/172201824-2a18dbaa-7f89-4ddc-b20f-5cb9040a4242.gif)

## Expected result:
Should be able to copy sync code

## Reproduces how often: 

100%
## Brave version (brave://version info)

Brave | 1.40.83 Chromium: 102.0.5005.78 (Official Build) beta (64-bit)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | Windows 10 Version 21H2 (Build 19044.1706)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @AlexeyBarabash @rebron @brave/qa-team 

Reproduced by @srirambv

**Comment by AlexeyBarabash** [comment]
thanks @GeetaSarvadnya , I also can reproduce it

**Comment by stephendonner** [comment]
Also reproduces on 

Brave | 1.41.39 Chromium: 102.0.5005.78 (Official Build) nightly (x86_64)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | macOS Version 11.6.6 (Build 20G624)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.42.2 Chromium: 103.0.5060.53 (Official Build) nightly (64-bit)
-- | --
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | Windows 11 Version 21H2 (Build 22000.739)
```

### Verified the fix, able to copy sync code

![2022-06-16_17h11_08](https://user-images.githubusercontent.com/98358127/174198068-63420103-9521-47df-b7cf-269abefeb743.gif)

**Comment by kjozwiak** [comment]
Removing the `QA Pass` labels as this was uplifted into `1.40.x` via https://github.com/brave/brave-core/pull/13813 and should be rechecked. However, I used the verification that @MadhaviSeelam completed via https://github.com/brave/brave-browser/issues/23262#issuecomment-1158317005 as the Nightly verification for the uplifts as mentioned via https://github.com/brave/brave-core/pull/13643#issuecomment-1158453624.

The above will require `1.40.103` or higher for `1.40.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
Brave | 1.40.103 Chromium: 103.0.5060.53 (Official Build) (64-bit)
-- | --
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | Windows 10 Version 21H2 (Build 19044.1706)

```
- Verified the STR from the description and ensured sync code words can be copied from the existing sync chain
![Sync code copy](https://user-images.githubusercontent.com/38657976/174276605-27f962b9-116c-47dd-b246-b58ca94fb000.gif)

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.40.103 Chromium: 103.0.5060.53 (Official Build) (x86_64)
-- | --
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | macOS Version 11.6.7 (Build 20G630)


Confirmed I could copy (and paste) code words
Confirmed I could join using code words
Confirmed I could join using QR code

example | example | example
---------|---------|----------
<img width="1312" alt="Screen Shot 2022-06-17 at 9 46 56 AM" src="https://user-images.githubusercontent.com/387249/174341974-f051b982-58e5-463c-9f61-048d20d6dcbf.png"> | ![Image from iOS](https://user-images.githubusercontent.com/387249/174342426-16f67eb0-0f57-4bb0-9033-822d2722fd34.png) | <img width="1312" alt="Screen Shot 2022-06-17 at 9 46 59 AM" src="https://user-images.githubusercontent.com/387249/174341987-e15c249d-6b72-482f-82d1-18fd0f7e4977.png">
