### ISSUE TITLE
DApps: Add an eTLD on transaction confirmation screen

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#23265]
We should show an eTLD of the website the same as we do on other screens. Desktop has it
![Screenshot from 2022-06-06 13-32-12](https://user-images.githubusercontent.com/12011303/172214366-7aa19e3f-04bf-446f-a727-3aeb4478dca5.png)

**Comment by kjozwiak** [comment]
The above will require `1.40.94` or higher for `1.40.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.40.105 x64 build
- Verified transaction confirmation screen shows `eTLD+1` details

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<img width=290 src=https://user-images.githubusercontent.com/17010094/174619411-faed1eca-6a43-4294-ac22-7a5d818434c1.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/174620029-3111e0cf-529a-434f-90c1-5fb97dec8d9a.png>
