### ISSUE TITLE
Brave installs are failing when installed via MS store

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#23266]
## Description 

Brave install fails on a fresh install when attempted to install from `MS store` where no prior `Brave release` instance is installed. Also if a `Brave release` instance is already installed and installing `Brave` from `MS store` shows an error. 

## Steps to Reproduce

Case 1: Brave release instance already installed and tried to install `Brave` via `MS store`
   1. Verify `Brave release (1.39.111)` already installed
   1. Install  `Brave` browser via `MS store`
   2. `Brave` opens in a new window  
   3. UAC modal isn't  displayed

Case 2: No prior `Brave` release instance is available and install `Brave` via `MS store`

   1. Un installed prior `Brave` release version (`1.39.111`)
   2. Install `Brave` browser via `MS store`
   
## Actual result:

Issue was reproduced in Win 11 and Win 10
Case 1: MS store page shows `Something unexpected happened` with a code: 0x8A150006`
![image](https://user-images.githubusercontent.com/98358127/172218172-e511e332-3f2e-43ec-8469-fac1a8d83a4a.png)

Issue was reproduced in Win 11x64
Case 2: MS store page shows `Something unexpected happened` with a code: 0x8A150006`

![image](https://user-images.githubusercontent.com/98358127/172218101-98a5cd4c-b127-4735-bdc3-7ec74971b57a.png)

## Expected result:
Brave should install without errors

## Reproduces how often: 

Easily

## Brave version (brave://version info)

This test is via Microsoft store

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@rebron @brave/devops-team

**Comment by laurentiugruia** [comment]
@mherrmann Still waiting to hear back from them. Followed up just now.

**Comment by laurentiugruia** [comment]
Hi @mherrmann ,

Only feedback I received is that we should use this: https://docs.microsoft.com/en-us/windows/uwp/publish/images/installer-return-code-settings.png

Unfortunately from our previous conversation I understand that our installer only returns "0" at the moment no matter the context? Could/should we set up different response codes for the different scenarios?

**Comment by mherrmann** [comment]
@laurentiugruia it won't be easy to return different exit codes, I think. Also, I don't see how Microsoft's response makes much sense. We're always returning 0. So from the perspective of the Store, it should be fine. Yet it returns an error. My feeling is that they gave you a canned response without really considering the problem.

**Comment by mherrmann** [comment]
@MadhaviSeelam are you still able to reproduce this?

**Comment by MadhaviSeelam** [comment]
@mherrmann Successfully installed 1.63.174.  Silent installed Brave.  Closing the issue. 

example | example 
---- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/27471ca9-b09c-4e34-a43e-b578bb4c6419)|![image](https://github.com/brave/brave-browser/assets/98358127/cc32c124-b60f-472a-9af8-72d26d73b3fe)
