### ISSUE TITLE
DApps: Add decrypt request screen

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#23260]
Use skiff.org to test it.

**Comment by kjozwiak** [comment]
The above will require `1.41.77` or higher for `1.41.x` verification 👍

**Comment by srirambv** [comment]
Blocked on #23769

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.41.91
- Verified Decrypt request screen is shown and able to view the decrypted message

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/177336821-d5771780-b4ee-48a1-83eb-a60dce2b8750.mp4> | <video src=https://user-images.githubusercontent.com/17010094/177336802-06616fbb-3b14-4f21-879e-4f148d444100.mp4>
