### ISSUE TITLE
Update l10n for 1.39.x maintenance release (Chromium 102) 

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#23278]
Download the latest l10n from Transifex.

Test plan:

https://github.com/orgs/brave/teams/legacy_qa should run through a few locals just to make sure that nothing obvious has regressed. Shouldn't spend too much time on this though.

**Comment by kjozwiak** [comment]
The above will require `1.39.119` or higher for `1.39.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```
Brave | 1.39.120 Chromium: 102.0.5005.99 (Official Build) (64-bit)
-- | --
Revision | 870f7bcc58dfa811cc68c2186439721385e086d0-refs/branch-heads/5005@{#1125}
OS | Windows 10 Version 21H2 (Build 19044.1706)
```
