### ISSUE TITLE
Icons in toolbar are too thick on non retina screens

### ISSUE THREAD

**Issue by rossmoody** [brave/brave-browser#2327]
Reported by @bradleyrichter and @alexwykoff. 

Icons in the toolbar are rendering too thick in comparison to their retina counterpart. Need to thin them down a little bit. 

<img width="790" alt="screen shot 2018-12-02 at 5 08 45 pm" src="https://user-images.githubusercontent.com/29072694/49347628-103ebc00-f655-11e8-91a0-1a59311897e3.png">

## Test plan
On https://github.com/brave/brave-core/pull/1005

**Comment by LaurenWags** [comment]
Verified passed with
Top image is released version 0.58.16 for comparison with bottom is 0.59.12 beta
![screen shot 2018-12-21 at 2 50 41 pm](https://user-images.githubusercontent.com/28145373/50360964-f1369a00-052f-11e9-85a2-e763c1f783b5.png)
