### ISSUE TITLE
Switching between Filecoin Mainnet to Testnet resets to Ethereum default account

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23286]
## Description 

Switching between Filecoin Mainnet to Testnet resets to Ethereum default account

## Steps to Reproduce

   1. Import Filecoin accounts for both Mainnet and Testnet
   2. On widget switch networks from Filecoin Mainnet to Filecoin Testnet
   3. Account resets to Ethereum default account have to manually change it

## Actual result:

https://user-images.githubusercontent.com/17010094/172331394-e8a7b5af-363a-4573-b38d-525fe24ff977.mov

## Expected result:
Should show proper account when switching network

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.41.39 Chromium: 102.0.5005.78 (Official Build) nightly (64-bit)
-- | --
Revision | `df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | Windows 11 Version 22H2 (Build 22621.1)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @spylogsster @cypt4 @yrliou

**Comment by yrliou** [comment]
Removing 1.40.x as testnet will be disabled.

**Comment by josheleonard** [comment]
Closing as stale (This widget is no longer used)
