### ISSUE TITLE
Extension request: Kee + invalid link in settings

### ISSUE THREAD

**Issue by vertigo220** [brave/brave-browser#2328]
Please add support for the Kee extension (https://chrome.google.com/webstore/detail/kee/mmhlniccooihdimnnjhamobppdhaolme). Also, the link in settings that says "Looking for a favorite extension? Let us know through our community." just leads to a page that says "Oops! That page doesn’t exist or is private."

**Comment by srirambv** [comment]
You can install any extension from Chrome Webstore. The Brave webstore link in `brave://extensions` will be fixed once https://github.com/brave/brave-browser/issues/790 is fixed.

**Comment by vertigo220** [comment]
Thanks. I thought that was the case but it wasn't giving me the option. Turns out I had the old Brave installed, even though it's still updating. I would've thought it would notify me to switch to the new version, or just update to it automatically.

**Comment by srirambv** [comment]
Auto migrations is not yet done from older version to the new one. It would be done soon for Windows and macOS. If you have not yet installed the new version you can download it from https://brave.com/download
