### ISSUE TITLE
Remove `Select HD account` message for Filecoin Import as there is no dropdown any more

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23287]
## Description 

Remove `Select HD account` message for Filecoin Import as there is no dropdown any more

## Steps to Reproduce

   1. Import Filecoin account from Ledger
   2. Import dialog shows message about switching to HD accounts but there is no option to select HD/legacy 

## Actual result:

<img width="1728" alt="Screen Shot 2022-06-07 at 4 09 44 AM" src="https://user-images.githubusercontent.com/17010094/172332458-dece86fc-125d-408b-80f1-5200f48df67f.png">

## Expected result:
Remove info text if not applicable

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.41.39 Chromium: 102.0.5005.78 (Official Build) nightly (64-bit)
-- | --
Revision | `df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | Windows 11 Version 22H2 (Build 22621.1)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @spylogsster @cypt4 @yrliou

**Comment by yrliou** [comment]
Don't think it needs to block 1.40.x, removing the 1.40.x milestone.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.67.94 Chromium: 125.0.6422.112 (Official Build) beta (64-bit)
-- | --
Revision | 3e4d210c91412b82ad8cffca556b12bbe40ff962
OS | Windows 11 Version 23H2 (Build 22631.3593)

- Verified steps from [brave/brave-core#23238](https://github.com/brave/brave-core/pull/23238)
- Verified  `Select HD account` message is now removed from the Filecoin import account screen

https://github.com/brave/brave-browser/assets/17010094/56b19ee9-9de8-48b9-9c46-1bfbbbe5eaa1
