### ISSUE TITLE
Bug - Buys on wallet are hardcoded in the url to USD 

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#23295]
## Description 
BuyUrl for all ramp providers currently hard code fiat currency to USD, as a result, a user's preferred currency is not used used in on ramp provider's UI. This creates a confusing UX for users.

**Comment by yrliou** [comment]
Reverted via https://github.com/brave/brave-core/pull/14075.

**Comment by srirambv** [comment]
Removing Android and iOS labels as they need frontend work to be done. 

Android specific issue : https://github.com/brave/brave-browser/issues/25477
iOS specific issue: https://github.com/brave/brave-ios/issues/6032

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.44.95 Chromium: 106.0.5249.40 (Official Build) (64-bit) 
-- | --
Revision | `fab1d91915d2722d6339aaa7f4e9ce44f1e9b103-refs/branch-heads/5249@{#442}`
OS | Linux

- Verified steps from [brave/brave-core#14089](https://github.com/brave/brave-core/pull/14089)
- Verified able to select from USD/EUR/GBP for Buy token

https://user-images.githubusercontent.com/17010094/191590946-dde19134-7615-4da7-88af-b46f4bc855dc.mp4



------------------------
Verification passed on

Brave | 1.44.95 Chromium: 106.0.5249.40 (Official Build) (64-bit) 
-- | --
Revision | `fab1d91915d2722d6339aaa7f4e9ce44f1e9b103-refs/branch-heads/5249@{#442}`
OS | Windows 11 Version 21H2 (Build 22000.978)

- Verified steps from [brave/brave-core#14089](https://github.com/brave/brave-core/pull/14089)
- Verified able to select from USD/EUR/GBP for Buy token

https://user-images.githubusercontent.com/17010094/191591821-50ffa79a-c1d9-4a08-84b9-3f7bae1f8034.mp4


------------------------
Verification passed on

Brave | 1.44.95 Chromium: 106.0.5249.40 (Official Build) (arm64)
-- | --
Revision | `fab1d91915d2722d6339aaa7f4e9ce44f1e9b103-refs/branch-heads/5249@{#442}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [brave/brave-core#14089](https://github.com/brave/brave-core/pull/14089)
- Verified able to select from USD/EUR/GBP for Buy token

https://user-images.githubusercontent.com/17010094/191592135-e964f624-970c-4e9b-ab9d-6aeed9a11c3a.mov
