### ISSUE TITLE
Customize the message for extensions that cant be installed via Google webstore

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#233]
## Description 
Customize the message for extensions that cant be installed via Google webstore

 ## Actual result:

![image](https://user-images.githubusercontent.com/17010094/40588324-d40260e2-61a9-11e8-8242-e776e610623f.png)

**Comment by bbondy** [comment]
QA notes: it should just remove the part about `about:extensions`.

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | -- 
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Linux

* Verified no blocking message shown on installing extensions
* Verified installing extensions shows warning message

**Comment by kjozwiak** [comment]
Can't QA this at this point due to not having any extensions from the GPS in the blacklist. Double checked and this particular case is also covered by automation hence adding `QA/No`.
