### ISSUE TITLE
Shields cookies/fingerprinting settings not saving in brave://settings/shields

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#23304]
## Description 

Cookies/fingerprinting settings not saving in brave://settings/shields

## Steps to Reproduce

   1. Visit brave://settings/shields
   2. Change "Block cookies" or "Block fingerprinting" setting
   3. Close tab
   4. Reopen brave://settings/shields

## Actual result:

Old cookie/fingerprinting setting shows.

## Expected result:
New cookie/fingerprinting setting shows.

## Reproduces how often: 

Easily.

## Brave version (brave://version info)

Latest master (I'm on Windows 11).

## Version/Channel Information:

Started in version 1.41.32

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
cc: @nullhook

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.41.65 Chromium: 103.0.5060.42 (Official Build) nightly (x86_64)
-- | --
Revision | de0d840bf9439c31bd86bf74f065c31fdf9b208d-refs/branch-heads/5060@{#667}
OS | macOS Version 11.6.7 (Build 20G630)

### Steps:
1. installed `1.41.65`
2. launched Brave
3. opened a couple tabs
4. opened `brave://settings/shields`
5. confirmed pref defaults
6. changed `Block fingerprinting` to `Strict, may break sites`
7. changed `Block cookies` to `All`
8. closed the `Settings` tab
9. opened `brave://settings/shields` in a new tab
10. noted values of `Block fingerprinting` and `Block cookies`
11. opened `cnn.com` in a new tab
12. expanded the Shields UI to see the defaults coming through

#### Confirmed default Shields values were those I customized from steps 6 & 7

step 5 | step 6 & 7 | step 10 | step 12
---|---|---|---
<img width="1312" alt="Screen Shot 2022-06-15 at 4 49 55 PM" src="https://user-images.githubusercontent.com/387249/173961434-faaf0459-a2e9-454e-9fa2-ef5988aab1ca.png"> | <img width="1312" alt="Screen Shot 2022-06-15 at 4 51 04 PM" src="https://user-images.githubusercontent.com/387249/173961437-f5a2979b-e3c5-42a5-a9f0-49ba6f89e8b2.png"> | <img width="1312" alt="Screen Shot 2022-06-15 at 4 59 12 PM" src="https://user-images.githubusercontent.com/387249/173961787-eef49dae-2ad9-4a3d-bd2b-7d94b9089d59.png"> | <img width="1312" alt="Screen Shot 2022-06-15 at 4 59 38 PM" src="https://user-images.githubusercontent.com/387249/173961793-3bd92172-c99e-446a-8288-b4aa86c86bb6.png">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.41.72 Chromium: 103.0.5060.42 (Official Build) beta (64-bit)
-- | --
Revision | de0d840bf9439c31bd86bf74f065c31fdf9b208d-refs/branch-heads/5060@{#667}
OS | Windows 11 Version 21H2 (Build 22000.739)
```
### Steps:
1. installed `1.41.72`
2. launched Brave
3. opened a couple tabs
4. opened `brave://settings/shields`
5. confirmed pref defaults
6. changed `Block fingerprinting` to `Strict, may break sites`
7. changed `Block cookies` to `All`
8. closed the `Settings` tab
9. opened `brave://settings/shields` in a new tab
10. New values are saved for `Block fingerprinting` and `Block cookies`
11. opened `cnn.com` in a new tab
12. expanded the Shields UI 

#### Confirmed default Shields values were those I customized from steps 6 & 7

Step 5|Step6&7|Step9&10|Step 12
---|---|---|---
<img width="956" alt="image" src="https://user-images.githubusercontent.com/98358127/174406324-306572c4-845b-41e6-b205-cc5a5fe252c4.png">|<img width="957" alt="image" src="https://user-images.githubusercontent.com/98358127/174406316-596b8ca2-9b11-46d6-a574-eea46f7e551d.png">|<img width="956" alt="image" src="https://user-images.githubusercontent.com/98358127/174406303-72b55695-00c2-4baa-a668-694544318432.png">|<img width="949" alt="image" src="https://user-images.githubusercontent.com/98358127/174405846-9d78a1d8-1468-4967-b6d3-d75313d94bbb.png">

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 


### Steps:
1. installed `1.41.84`
2. launched Brave
3. opened a couple tabs
4. opened `brave://settings/shields`
5. confirmed pref defaults
6. changed `Block fingerprinting` to `Strict, may break sites`
7. changed `Block cookies` to `All`
8. closed the `Settings` tab
9. opened `brave://settings/shields` in a new tab
10. noted values of `Block fingerprinting` and `Block cookies`
11. opened `cnn.com` in a new tab
12. expanded the Shields UI to see the defaults coming through

#### Confirmed default Shields values were those I customized from steps 6 & 7

step 5 | step 6 & 7 | step 10 | step 12
---|---|---|---
