### ISSUE TITLE
Universal builds on macOS roll-out

### ISSUE THREAD

**Issue by mihaiplesa** [brave/brave-browser#23307]
We're re-enabling universal builds on macOS hence the following will happen:
- our website will only serve universal binaries on all channels https://github.com/brave/brave-com-resources/issues/537
- universal binaries will be added in GitHub alongside arm64 https://github.com/brave-intl/go-vault/issues/106
- update servers will still serve native updates and deltas https://github.com/brave/devops/issues/7682

A new user installing the universal build from the website or GitHub will be updated to their native architecture with the next newer version. Delta updates, DRM video and everything else should still work.

**Comment by kjozwiak** [comment]
QA mostly using Slack and the above GH issues for verification so closing this one off 👍
