### ISSUE TITLE
Reduce Language fingerprinting preference causes website to break

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#23306]
## Description 

Navigating to https://www.ticketweb.ca/ with Reduce Language fingerprinting preference on results in an empty page. With the pref turned off, page loads fine.

## Steps to Reproduce

   1. Go to https://www.ticketweb.ca/ with Reduce Language fingerprinting preference in brave://settings/shields turned on
   2. 

## Actual result:

![image](https://user-images.githubusercontent.com/5284154/172459769-fc696393-368e-4ab3-9ada-f7ce3e93bea0.png)

## Expected result:
![image](https://user-images.githubusercontent.com/5284154/172459811-dc2f755d-a3c9-41c7-a9bb-3336489f27c3.png)

## Reproduces how often: 

It seems like the issue is a lack of a weight being sent in the `Accept-Language` header when Reduce Language pref is turned on. There's a 1/6 chance that it will be set to nothing: https://github.com/brave/brave-core/blob/master/browser/brave_shields/reduce_language_navigation_throttle.cc#L98
My `Accept-Language` header is `en-US` with Reduce Language on and `en-US,en;q=0.9` with it off.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.41.65 Chromium: 103.0.5060.42 (Official Build) nightly (x86_64)
-- | --
Revision | de0d840bf9439c31bd86bf74f065c31fdf9b208d-refs/branch-heads/5060@{#667}
OS | macOS Version 11.6.7 (Build 20G630)
--------
Reproduced using:

Brave | 1.41.39 Chromium: 102.0.5005.78 (Official Build) nightly (x86_64)
-- | --
Revision | df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}
OS | macOS Version 11.6.7 (Build 20G630)

`1.41.39`
--------
<img width="1523" alt="Screen Shot 2022-06-15 at 3 37 24 PM" src="https://user-images.githubusercontent.com/387249/173951227-27a37c9e-85c3-4a72-aeb0-0f051d55caeb.png">

`1.41.65` | `brave://settings/shields`
--------|-------
 | <img width="1523" alt="Screen Shot 2022-06-15 at 3 39 31 PM" src="https://user-images.githubusercontent.com/387249/173952432-2b6e02f2-6e33-4904-88a9-1f23076d64bc.png">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.41.72 Chromium: 103.0.5060.42 (Official Build) beta (64-bit)
-- | --
Revision | de0d840bf9439c31bd86bf74f065c31fdf9b208d-refs/branch-heads/5060@{#667}
OS | Windows 11 Version 21H2 (Build 22000.739)
```
Couldn't reproduce in older builds Beta and Nightly (1.40.100 Chromium: 102.0.5005.125 beta, 1.41.39 Chromium: 102.0.5005.78)

Page rendered as expected in `1.41.72`

Steps:

- installed Brave
- launched Brave
- loaded https://ticketweb.ca
- confirmed page rendered
- opened brave://settings/shields
- confirmed Prevent sites from fingerprinting me based on my language preferences was toggled to ON by default

`1.41.72`|`brave://settings/shields`
---|---
<img width="947" alt="image" src="https://user-images.githubusercontent.com/98358127/174412988-14436b7a-3d12-4d8f-bcb6-f98e6ef7c9af.png">|<img width="947" alt="image" src="https://user-images.githubusercontent.com/98358127/174413040-8e542bfe-4c61-40c6-b170-ce35d087b60b.png">

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.41.84 Chromium: 103.0.5060.66 (Official Build) beta (64-bit) 
--|--
Revision | 20b1569438a85e631d15e83eb355e3e326e5da6f-refs/branch-heads/5060@{#1066}
OS | Linux

#### NOTE: until things are a bit more smoothed out, this isn't enabled by default any longer, in the client, and is instead now controlled by a Griffin study.


### Confirmed:
* pref is now `OFF` by default (see above)
* `ticketweb.ca` displays fine even with `Prevent sites from fingerprinting me based on my language preferences` toggled to `ON`

`1.41.84` | `brave://settings/shields`
---------|---------
<img width="1560" alt="Screen Shot 2022-06-29 at 7 12 37 PM" src="https://user-images.githubusercontent.com/387249/176578143-8586c5ba-e986-4297-8acf-a7c67a4271b3.png"> | <img width="1560" alt="Screen Shot 2022-06-29 at 7 11 49 PM" src="https://user-images.githubusercontent.com/387249/176578243-1eacad35-d010-4559-a3c5-d8b205fca274.png">

### Also, could NOT reproduce the issue in `1.41.39`:

`1.41.39` | `brave://settings/shields`
----------|-------------------------
<img width="1560" alt="Screen Shot 2022-06-29 at 7 01 43 PM" src="https://user-images.githubusercontent.com/387249/176579319-c32c4043-d93c-44c1-8369-79c69dc2e529.png"> | <img width="1560" alt="Screen Shot 2022-06-29 at 7 01 39 PM" src="https://user-images.githubusercontent.com/387249/176579314-aba5ba4d-1eef-4199-af80-4db0086a19dc.png">

**Comment by srirambv** [comment]
Removing Android label as this need to be implemented via https://github.com/brave/brave-browser/issues/23918 which is blocked on https://github.com/brave/brave-browser/issues/23919
