### ISSUE TITLE
VPN config auto installs when a new server location is selected

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23301]
## Description 

VPN config auto installs when a new server location is selected

## Steps to Reproduce

   1. Create a VPN account and install profile
   2. Disconnect if already connected
   3. Go to Windows Settings -> Network & internet
   4. Delete the Brave VPN config
   5. Go back to browser profile and select VPN
   6. Try to connect to the previous server, shows error
   7. Try a few more times, same error is shown
   8. Select a different server, automatically connects and re-adds the Brave VPN profile

## Actual result:

VPN config auto installs when a new server location is selected

## Expected result:
Not sure. I'd expect it to sign out of subscription and ask to re-authenticate to re-install the config as the credentials are part of the config

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html><head></head>
<body>

Brave | 1.41.39 Chromium: 102.0.5005.78 (Official Build) nightly (64-bit)
-- | --
Revision | `df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}`
OS | Windows 11 Version 22H2 (Build 22621.1)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @spylogsster @bsclifton

**Comment by bsclifton** [comment]
I believe this is fixed now - @simonhong had fixed a very similar issue

@simonhong can you confirm?

**Comment by simonhong** [comment]
> I believe this is fixed now - @simonhong had fixed a very similar issue
> 
> @simonhong can you confirm?

Yeah, already fixed. Closed as duplicated issue with https://github.com/brave/brave-browser/issues/25895
