### ISSUE TITLE
Android on-ramp updates on Android (Sardine, Transak)

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#23316]

**Comment by Pavneet-Sing** [comment]
Update: Ramp network support has been [added](https://github.com/brave/brave-core/pull/16558). Now needs to expand ramp network support.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.50.83 x64 Beta build
- Verified steps from [brave/brave-core#16872](https://github.com/brave/brave-core/pull/16872)
- Verified the new screen `Select purchase method` is shown 
- Verify that tapping on the `Buy with Ramp` button opens a new page on Ramp network
- Verify that tapping on the `Buy with Sardine` button opens a new page on Sardine
- Verify that tapping on the `Buy with Transak` button opens a new page on Transak
- Verified Sardine is shown only for US 

Oppo Reno 5 (Android 13) | Lenovo Tab (Android 12)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/224671898-29a56ec3-f593-4de3-b775-ed63bcf89de2.mp4> | <video src=https://user-images.githubusercontent.com/17010094/224671939-b9f864a9-30bd-4eeb-b3f2-9f252952b326.mp4>
