### ISSUE TITLE
"Copy clean URL" feature

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#23315]
We currently have a privacy feature to [strip out identifying parameters across sites](https://github.com/brave/brave-browser/wiki/Query-String-Filter). Users are asking us to go further and [remove anything that's not needed when copying URLs](https://twitter.com/brendaneich/status/1514652839234052102?s=21&t=vyR2fXUxYGIY7DSUHUiYBA).

For example, there are first-party parameters which are not in-scope for the existing query filter:

- Amazon has URLs like `https://www.amazon.com/Echo-Dot/dp/B07FZ8S74R/ref=sr_1_1?crid=1JM4ODN4MKLZO&keywords=alexa+echo&qid=1654644603&sprefix=alexa%2Caps%2C136&sr=8-1` where only `https://www.amazon.com/dp/B07FZ8S74R/` is needed.
- Twitter has [unnecessary `t` and `s` parameters](https://twitter.com/luca/status/1432780065109155855?lang=en) which seem to identify the application and user who shared the link.

There are also parameters which aren't privacy-harming but which clutter shared links needlessly.

This should be opt-in to avoid surprising users who may be thinking that Brave is broken and unable/unwilling the copy the full URL from the URL bar.

Spec: https://docs.google.com/document/d/1ea7eF3s0WTsTlmMPr8LYp5KUyNg8eK4omjizo27qvJE/edit#

**Comment by Novack** [comment]
I think this pollutes the context menu unnecessarily. What about having only one "Copy Link" on context that removes trackers by default, while in the settings an option "Allow trackers on copied links" if the user wants or needs it for some reason?

**Comment by spylogsster** [comment]
waiting for https://github.com/brave/adblock-rust/issues/166

**Comment by bsclifton** [comment]
@spylogsster is this implemented on Android too? I don't think it is (checked Nightly) so I'm removing `OS/Android` label

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.45.87 Chromium: 106.0.5249.91 (Official Build) beta (x86_64)
-- | --
Revision | fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}
OS | macOS Version 11.7 (Build 20G817)

Share widget

Context-click on URL bar

**Comment by snowbound** [comment]
Problem with this [URL](https://github.com/brave/adblock-lists/blob/master/brave-lists/clean-urls.json) The ?taid= is not being stripped off the URL. The URL loads fine without that parameter and its associated string on the URL.

**Comment by fmarier** [comment]
@snowbound It looks like you pasted the wrong URL. I suggest you file an issue in https://github.com/brave/adblock-lists/issues to get that unnecessary parameter added to the list.

**Comment by snowbound** [comment]
@fmarier As your link did not point to a specific  thread I created this[ post](https://github.com/brave/adblock-lists/issues/986) to which I will continue to add parameters that are not being stipped out

**Comment by vrindavan** [comment]
In the address bar, the URLs are still not cleaned. I do not want to use extensions like CleanURL. So, does brave remove those?Parameters from URLs including trackers but keeps that in the address bar or it just does not remove it from the URL?

**Comment by fmarier** [comment]
@vrindavan There are two different features in Brave:

1. The copy clean URLs feature (the topic of this issue) which is about removing all unnecessary elements from URLs when you copy a URL. It doesn't remove it from the URL otherwise, just when you copy (for example to share a link with someone). Note that this is **not** a privacy feature, but rather a convenience feature to allow users to share shorter URLs.
2. The query string filter which removes parameters which are known to track **users** across multiples sites. That privacy feature is described in https://github.com/brave/brave-browser/wiki/Query-String-Filter. Note that we do not remove all unnecessary elements from URLs in this filter, just the ones that meet our definition of tracking.

If you want to remove all unnecessary elements from URLs by default, you can always add a third-party list (like [Adguard's](https://github.com/AdguardTeam/FiltersRegistry/blob/master/filters/filter_17_TrackParam/filter.txt)) to `brave://settings/shields/filters`.

**Comment by vrindavan** [comment]
Thank you for the info @fmarier. I tried putting the URL but looks like something's wrong. I am not sure if there is another format or URL I have to put here.

![image](https://user-images.githubusercontent.com/50140643/216383604-83e520f9-6461-4dc8-806f-11f8f3ae6cc3.png)

**Comment by fmarier** [comment]
@vrindavan Sorry, I should have given you the link to the raw TXT file instead of the GitHub page. This is what you need to put in the browser settings: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_17_TrackParam/filter.txt

**Comment by vrindavan** [comment]
Tried that @fmarier  but looks like something is not working: 
![image](https://user-images.githubusercontent.com/50140643/216530849-c0752d29-fbb7-4015-988a-a9aeefe17970.png)

**Comment by vrindavan** [comment]
Hey, it turns out this has something to do with my ISP. Their DNS is blocking raw.githubusercontent.com. I have contacted them, hoping they would whitelist this.

More about that: https://github.com/community/community/discussions/42655

Thanks for the filter list. I am using it with CloudFare Warp but it still keeps the parameters in the URL.

**Comment by fmarier** [comment]
> Thanks for the filter list. I am using it with CloudFlare Warp but it still keeps the parameters in the URL. Only [the extension](https://docs.clearurls.xyz/1.26.1/) works for me, it removes all parameters.

And the parameters you want to remove are listed in the [Adguard list](https://github.com/AdguardTeam/FiltersRegistry/blob/master/filters/filter_17_TrackParam/filter.txt)?

**Comment by fmarier** [comment]
@vrindavan If you can provide sample URLs, we can check. Support for these kinds of rules was recently added to Brave by @antonok-edm and so it's possible there are still bugs / limitations.

**Comment by vrindavan** [comment]
You can try opening Netflix for instance, and play anything and the address bar contains `?trackId` which is mentioned in the Adguard list. In the issue it seems to be working as mentioned by others, but I think Brave is unable to implement these rules using filter list URL.

https://github.com/AdguardTeam/AdguardFilters/issues/126395
