### ISSUE TITLE
Upgrade from Chromium 102.0.5005.78 to 102.0.5005.99

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#23311]
Minor Chromium bump.

https://chromium.googlesource.com/chromium/src/+log/102.0.5005.78..102.0.5005.99?pretty=fuller&n=10000

QA tests:

Check branding items
Check for version bump

Additional checks:

No specific code changes in Brave (only line number changes in patches).

**Comment by kjozwiak** [comment]
Closing as https://github.com/brave/brave-core/pull/13672 was merged into `1.39.x` 👍

**Comment by LaurenWags** [comment]
Verified using

```
Brave | 1.39.120 Chromium: 102.0.5005.99 (Official Build) (x86_64)
-- | --
Revision | 870f7bcc58dfa811cc68c2186439721385e086d0-refs/branch-heads/5005@{#1125}
OS | macOS Version 12.4 (Build 21F79)
```

<img width="1192" alt="Screen Shot 2022-06-08 at 7 19 37 AM" src="https://user-images.githubusercontent.com/28145373/172604069-c7f5177b-a83c-4666-a616-ea8d7096ee67.png">

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+` running `Android 12` using the following build(s):

```
Brave | 1.39.120 Chromium: 102.0.5005.99 (Official Build) (64-bit)
--- | ---
Revision | 870f7bcc58dfa811cc68c2186439721385e086d0-refs/branch-heads/5005@{#1125}
OS | Android 12; Build/SP1A.210812.016
```

**`Example`** | **`Example`**
----------------|----------------
![Screenshot_20220608-113412_Brave](https://user-images.githubusercontent.com/2602313/172658418-264e9967-fcc1-4e10-9944-f2d015e73e1d.jpg) | ![Screenshot_20220608-113445_Brave](https://user-images.githubusercontent.com/2602313/172658427-8f08b98a-6fdb-4a17-94af-37dcec5739f4.jpg)
