### ISSUE TITLE
Brave Shield script blocker needs an option "Allow 1st party scripts, block 3rd party JS" - to match UBO advanced mode "1p allow, 3p block"

### ISSUE THREAD

**Issue by gkrishnaks** [brave/brave-browser#2331]
Have you searched for similar issues: Yes

Feature request : 

## Description 
Brave Shield's Script blocker feature needs to have an option : "Allow 1st party Javascript, block all 3rd party Javascript". This feature is available in Ublock Origin Advanced mode where one can disable 3rd party JS while allowing 1p JS.  UBO seems to use eTLD+1 as "1p" rule.

## Steps to Reproduce
Feature Request:  UI brave shields dropdown menu can be updated with option "Block 3rd party scripts"  

## Expected result:
User expects to have the feature to disable 3rd party javascript but allowing 1st party Javascript (eTLD+1)
UblockOrigin provides this option via advanced user mode. 

## Brave version
Any/Latest

Raising an issue thread for what I mentioned in twitter: https://twitter.com/gkrishnaks/status/1069417407049981953

**Comment by tomlowenthal** [comment]
We already have this one planned, and it's in the first cluster of things to implement in our next development pass. #538
