### ISSUE TITLE
[De-AMP] JS navigations from canonical -> AMP cause redirect loop

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#23320]
## Description 

Some canonical pages manipulate `window.location` to direct a site back to the AMP page. We should catch when this is happening and stop De-AMPing.

## Steps to Reproduce

   1. Make sure De-AMP pref is turned on
   2. Go to https://thehustle.co/06022022-elvis-vegas-weddings 
   3. Alternatively, go to [test-js-redirect-amp.html](https://shivankaul.com/brave/de-amp/test-js-redirect-amp.html)

   
## Actual result:

Redirect loop

## Expected result:
Not a loop, we should stop either on canonical page or AMP page.

## Reproduces how often: 

Easily

The issue here is that it's not technically a redirect that we can check for throttle-side. The page load for the canonical page completed successfully, and then the page is navigated away to the AMP page.

**Comment by kjozwiak** [comment]
This will go out in the next `1.39.x` release if we need to either push a HF (hotfix) or we get a minor `C102` chromium bump. If don't end up releasing another `1.39.x`, we'll close off the `1.39.x - Release #5` milestone and move this issue into the `1.40.x` milestone.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64` using the following build(s):

````
Brave | 1.40.105 Chromium: 103.0.5060.53 (Official Build) (64-bit)
-- | --
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | Windows 11 Version 21H2 (Build 22000.739)
````

Went through all the STR/Cases (specifically the websites being listed) via https://github.com/brave/brave-core/pull/13674#issue-1263953932 and ensured that all the websites mentioned loaded without running into any looping issues.

#### `de-amp` enabled

**`Example`** | **`Example`**
---------------|-----------------
![image](https://user-images.githubusercontent.com/2602313/174713179-e97b4393-04a9-4b8e-88f7-af953e265ea1.png) | ![image](https://user-images.githubusercontent.com/2602313/174713326-b91d829e-4677-40b5-9acd-19f88c5e7272.png)

#### `de-amp` disabled

**`Example`** | **`Example`**
---------------|----------------
![image](https://user-images.githubusercontent.com/2602313/174713755-44196dfa-bb43-49cb-8183-279b0efcec4c.png) | ![image](https://user-images.githubusercontent.com/2602313/174713858-e583d3f8-e710-4f5c-a182-34ec0a171aa6.png)
