### ISSUE TITLE
Rollback ETH's symbol name from Ether to Ethereum in preloading networks

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#23322]
Might be causing UI issues, there might be some checks against token.name and network.symbolName in places.
We should rollback for now to be safe, and uplift to 1.40.x.

https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1654638804348119

**Comment by kjozwiak** [comment]
I don't think we need to add the above into the release notes for `1.40.x` as it's a simple string change.

**Comment by kjozwiak** [comment]
The above will require `1.40.94` or higher for `1.40.x` verification 👍

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.40.95 Chromium: 102.0.5005.115 (Official Build) beta (64-bit) </th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>174dbe6e33bc81994fceb71d751be201d0b4803d-refs/branch-heads/5005_109@{#3}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.708)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/13680>brave/brave-core#13680</a></li>
         <li>Verified <code>Ether</code> now reads as <code>Ethereum</code> under Swap tab</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/173370118-ea21792b-1474-4700-a20d-b47c325b5c00.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/173370139-88e172c4-4483-43e5-a391-384e6df03bc9.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/173372818-c83fb5ed-5e2c-40b7-9b78-d95e50dbd9ab.mov>
      </td>
   </tr>
</table>

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.40.101 x64 build
- Verified steps from [brave-core#13680](https://github.com/brave/brave-core/pull/13680)
- Verified `Ether` now reads as `Ethereum` under Swap tab

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/174079805-e420143e-3223-4f55-a72f-6ca3304f082e.mp4> | <video src=https://user-images.githubusercontent.com/17010094/174079566-065f71b0-88e5-4d63-b50a-1b005ba4254d.mp4>
