### ISSUE TITLE
Copy edit on Brave Wallet / crypto / accounts: web 3 to web3

### ISSUE THREAD

**Issue by lukemulks** [brave/brave-browser#23328]
## Description 

On brave://wallet/crypto/accounts, within the *Primary crypto accounts* section copy, we have a space between _web_ and _3_ in _web 3_. 

sample of section copy in current form: 

> _These accounts can be used with **_web 3_** DApps, and can be shown in your portfolio. However, note that secondary accounts cannot be restored via recovery phrase from your primary account backup._

Suggest we update from _web 3_ to _web3_, removing the extra space between web and 3.

stylized _web3_ adopted as common shortform nomenclature in blockchain space, across b2c, p2p and b2b. 

## Steps to Reproduce

   1. navigate to brave://wallet/crypto/accounts 
   2. section: *Primary crypto accounts*
   3. observe: _These accounts can be used with **_web 3_** DApps..._

## Actual result:

*_web 3_*

## Expected result:
*_web3_*

## Reproduces how often: 

100%

## Brave version (info found on brave://version)

1.41.33 Chromium: 102.0.5005.78 (Official Build) nightly (64-bit) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? y
- Can you reproduce this issue with the beta channel? y
- Can you reproduce this issue with the dev channel? unknown; tbd.
- Can you reproduce this issue with the nightly channel? y

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? no

## Miscellaneous Information:

Heya @jamesmudgett @Douglashdaniel @onyb given this is a single-character string update, grouped you all on this one in case it's able to be attached to any uplifts, etc. 

note - I have only checked on desktop so far. that said, iirc Android on core, so would suspect that this likely applies there as well; unclear on iOS, and don't have an iOS device nearby that I can check from (so someone on iOS should spot check)

**Comment by jamesmudgett** [comment]
Yup, should also be capitalized Web3

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.41.86 Chromium: 103.0.5060.66 (Official Build) beta (64-bit) </th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>20b1569438a85e631d15e83eb355e3e326e5da6f-refs/branch-heads/5060@{#1066}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.708)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/13754>brave/brave-core#13754</a></li>
         <li>Verified <code>Web 3</code> is changed to <code>Web3</code></li>
         <li>Verified primary and secondary accounts description is shown correctly</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>Welcome screen
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/176939568-ac5f4778-2bf4-4927-b2da-73a7a9145381.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/176936784-5d9f5ec3-0857-4846-82ef-07b2fe30774d.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/176941307-266e3c72-7a51-4a12-9fd6-797ed5124d2b.png>
      </td>
   </tr>
   <tr>
      <td>Import from MetaMask
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/176939596-59bb07df-fe0f-4a51-8372-e1fb0ce143ac.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/176937724-ea13aa31-a308-49a6-a638-5538d452d17d.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/176941342-a6f68b02-4ba6-4c43-99b0-dbbb91f56602.png>
      </td>
   </tr>
   <tr>
      <td>Import from CryptoWallets
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/176939678-63e34da8-d0c3-49cf-8991-5dbcee1273f2.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/176937758-2a490e03-1a14-47d5-ac9e-0ec1b72c3067.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/176941366-23a7ac16-a092-405c-bbe3-b822cf3386bf.png>
      </td>
   </tr>
   <tr>
      <td>Welcome panel
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/176939721-19608bde-c5b4-4f92-9405-0d7b06c49170.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/176937775-f3c8ed8e-ecf3-4175-b255-3b6f29f368b6.jpg>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/176941504-29ef70be-b2cf-45c9-aa1b-675526c2329c.png>
      </td>
   </tr>
   <tr>
      <td>Default Wallet warning banner
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/176939867-db21b344-e3f0-46ac-9add-ddaaac3886e0.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/176937799-0ff30221-fc18-4f92-9c9a-7c6ff7994f24.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/176941616-eadc3f45-2d95-4c5f-8357-ee34195036af.png>
      </td>
   </tr>
   <tr>
      <td>Accounts tab (Secondary Accounts description)
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/176939894-1c0810e2-a78b-47fb-bc56-19672e63c4a3.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/176937819-def13b7a-42bb-4024-bdd3-19ccef93e1e6.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/176941641-50742fa9-5dfd-4b8d-95b2-87e5e2423073.png>
      </td>
   </tr>
   <tr>
      <td>Import Account modal
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/176939924-c4cd427f-ac4c-4a1c-9945-8d9bbb2e0868.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/176937834-46855936-47bc-4d2a-a0db-6db5efe6e63c.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/176941670-eb2cc6b7-e5f8-4b8e-b020-2475e4130813.png>
      </td>
   </tr>
</table>
