### ISSUE TITLE
Brave news crashes browser process when scroll into certain position

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#23338]
## Description 

Here is the callstack
https://brave.sp.backtrace.io/p/brave/explore?fingerprint=db0c40f5ef8fd380e75b895d2a376f5c80417f284fd0e9bcd76da214c7d3b90b&

## Steps to Reproduce

https://user-images.githubusercontent.com/11330831/172697825-2b430ba8-055a-4b29-9c68-3596f752d83d.mp4

## Actual result:

no crash

## Expected result:
Browser crash

## Reproduces how often: 

always

## Brave version (brave://version info)

1.41.47 Chromium: 102.0.5005.78 (Official Build) nightly (x86_64) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by mattmcalister** [comment]
is this still an open issue?
