### ISSUE TITLE
Recognize twitter.com as a Greaselion url

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#23332]
In our extension API adapter, the `isGreaselionURL` function seems to be missing an entry for `twitter.com`. Based on inspection of the code it seems that this doesn't cause an error per se (just some unnecessary work) but we should add it in there for consistency.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.41.59 Chromium: 103.0.5060.42 (Official Build) nightly (x86_64)
-- | --
Revision | de0d840bf9439c31bd86bf74f065c31fdf9b208d-refs/branch-heads/5060@{#667}
OS | macOS Version 12.4 (Build 21F79)
```

**Comment by stephendonner** [comment]
Verification `IN-PROGRESS` using 

Brave | 1.41.86 Chromium: 103.0.5060.66 (Official Build) beta (64-bit)
--|--
Revision | 20b1569438a85e631d15e83eb355e3e326e5da6f-refs/branch-heads/5060@{#1066}
OS | Linux

Verified test plan from https://github.com/brave/brave-core/pull/13689#issue-1264936021

Using Staging env for below cases:
* Confirmed verified twitter creators still displayed as expected in the panel
   * Confirmed if verified and have a custom image, the custom image is displayed on the panel
   * Confirmed if verified and do not have a custom image, the creator's twitter image is displayed on the panel
* Confirmed unverified twitter creators still displayed as expected in the panel
* Confirmed able to tip verified twitter creators and the tip is shown as expected on the panel summary, balance decreases as expected, etc
* Confirmed able to set up a monthly tip for a verified twitter creator and the panel reflects the selected amount for the tip
* Confirmed verified twitter creators can be added to auto contribution list and the attention % displays on the panel as expected
* Confirmed unverified twitter creators can be added to auto contribution list and the attention % displays on the panel as expected

Verified Example (custom image) | Verified Example (added to AC list) | Verified Example (no custom image) | Unverified Example (uses default twitter image) | Unverified Example (added to AC list)
----- | ----- | ----- | ----- | -----
<img width="416" alt="Screen Shot 2022-06-30 at 11 36 51 AM" src="https://user-images.githubusercontent.com/387249/176754225-15960d85-75d4-4ce1-9a0b-c0a6a9578ed6.png"> | <img width="412" alt="Screen Shot 2022-06-30 at 11 38 22 AM" src="https://user-images.githubusercontent.com/387249/176754229-90c70f01-401a-4cd3-871a-594452ee1688.png"> | <img width="416" alt="Screen Shot 2022-06-30 at 11 39 11 AM" src="https://user-images.githubusercontent.com/387249/176754232-1b0bf9f2-2d58-417c-aac3-aaa28e14d3df.png"> | <img width="413" alt="Screen Shot 2022-06-30 at 11 40 23 AM" src="https://user-images.githubusercontent.com/387249/176754233-4c6b406e-5dd8-49a6-857c-707460a7711e.png"> | <img width="415" alt="Screen Shot 2022-06-30 at 11 41 10 AM" src="https://user-images.githubusercontent.com/387249/176754236-b8a52a7d-c038-401b-8315-d554866fe86f.png">

Additionally, did some navigation checks to ensure panel showed correct creator info:

Visited several twitter pages in succession and then used back/forward browser buttons to navigate through the visited pages. Confirmed the panel showed the expected twitter user info each time.

Repeated above test while logged in to twitter. Confirmed the panel showed the expected twitter user info each time.

Visited several twitter (and non-twitter) pages in various tabs/windows. Visit these twitter (and non-twitter) tabs/windows in various orders, opening the panel to confirm the expected creator info (twitter, non-twitter, verified, non-verified) is shown as expected each time.

Repeated above test while logged in to twitter. Confirmed the panel showed the expected creator info (twitter, non-twitter, verified, non-verified) is shown as expected each time.
