### ISSUE TITLE
Auto Add Native Asset for new Preloaded Networks

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#23337]
## Description 
We need to Auto Add `Native Assets` for the new `Preloaded Networks` if a user selects the network and it's native asset is not a visible asset.

https://user-images.githubusercontent.com/40611140/172691821-815b8723-08b5-49ad-a473-4d4fa69676c6.mov

**Comment by yrliou** [comment]
After https://github.com/brave/brave-core/pull/13705 is merged, it also surface the problem that we currently wrongly use ETH as native tokens for all preloading network, will be fixed here too. cc @srirambv

**Comment by kjozwiak** [comment]
The above will require `1.40.96` or higher for `1.40.x` verification 👍

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.40.99 Chromium: 102.0.5005.125 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>07573b09e385116e620ed12d5ef2402c4bfa929f-refs/branch-heads/5005@{#1159}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.708)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/13724>brave/brave-core#13724</a></li>
         <li>Verified native tokens are listed for all EVM's on a clean profile</li>
         <li>Verified custom tokens are retained along with native tokens for all EVM's upon upgrade</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/173821669-224bfe00-e190-4d6c-b5c5-10a7d9d65cea.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/173820364-c384a08d-2d4e-4de8-b041-0d25bba2ef3b.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/173821829-dbe1669d-450d-431f-896c-8366c6f9b50d.mov>
      </td>
   </tr>
</table>
