### ISSUE TITLE
Filecoin GetBalance should respect chain_id parameter

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#23335]
https://github.com/brave/brave-core/blob/16fa11045ebb75aa9c6240cc9fe8514cc5300e42/components/brave_wallet/browser/json_rpc_service.cc#L639-L641

Currently we always call this API using the selected network, we should respect the chain_id parameter and use the result from `GetNetworkURL` to support getting balances for different networks without switching to them.

**Comment by yrliou** [comment]
Test plan specified in https://github.com/brave/brave-core/pull/13696

**Comment by srirambv** [comment]
Marking as `QA/No` as we don't have Filecoin Testnet support for 1.40.x
