### ISSUE TITLE
Importing from Brave (Muon version) when it's open will prompt user to close Brave

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#2334]
## Description 
If a user is doing a manual import from Brave (the older Muon version) and they have Muon open, they'll get an importer locked message (see picture under `Actual result`)

## Test plan / Steps to Reproduce
   1. Have an older Brave (release channel) install with profile data
   2. Leave the older Brave open
   3. Launch Brave Core and use Settings => Import to import from `Brave (old)`
   4. Choose the items and pick `Import`

## Actual result:
![brave-import](https://user-images.githubusercontent.com/4733304/49359422-7c401500-f693-11e8-89ac-68b5031610ef.jpg)

## Expected result:
Instead of `Brave`, it should probably say `Brave (old)` (so that user is not confused and doesn't close the current browser (Brave Core)

## Reproduces how often: 
100%

## Brave version (brave://version info)
0.57.12

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.57.16 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

* Verified STR from description
![screen shot 2018-12-05 at 12 16 34 pm](https://user-images.githubusercontent.com/28145373/49531214-cab60500-f887-11e8-983d-37a5482c905e.png)
