### ISSUE TITLE
Implement new buy user flow

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#23349]
Implement new user flow that shows all onramp providers (currently Ramp and Wyre).

The description for both providers has been updated to: "Buy crypto with Visa or Mastercard"

![Image](https://user-images.githubusercontent.com/48117473/172786088-6e5643f4-2459-40f1-898c-96110dd2d9f5.png)

**Comment by kjozwiak** [comment]
@muliswilliam changing the milestone to `1.41.x` as this landed in `master` which is currently `1.41.x` and not `1.40.x`. Please see https://github.com/brave/brave-browser/wiki/Triage-Guidelines#uplifting 👍 Once https://github.com/brave/brave-core/pull/13731 has been uplifted into `1.40.x`, the @brave/uplift-approvers team will move the issue into the `1.40.x` milestone.

**Comment by kjozwiak** [comment]
The above will require `1.40.99` or higher for `1.40.x` verification 👍

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.40.99 Chromium: 102.0.5005.125 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>07573b09e385116e620ed12d5ef2402c4bfa929f-refs/branch-heads/5005@{#1159}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.708)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/13708>brave/brave-core#13708</a></li>
         <li>Verified a new button to <code>Select purchase method...</code> is shown on the Buy widget</li>
         <li>Verified selecting it shows available providers</li>
         <li>Verified both <code>Ramp</code> and <code>Wyre</code> is shown for available tokens/network</li>
         <li>Verified only <code>Ramp</code> is shown for tokens/network when applicable</li>
         <li>Encountered <a href=https://github.com/brave/brave-browser/issues/23425>#23425</a></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/173818376-e24071a4-94ce-447d-a067-a71095e0d359.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/173816974-39bbbeed-722f-48f0-a475-b91e3e755410.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/173819072-726bff0a-7f08-4707-9cf6-275701f7868a.mov>
      </td>
   </tr>
</table>
