### ISSUE TITLE
Page webview crash when trying to change wallet network

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23352]
## Description 

While trying to investigate a community report on wallet, had `https://www.coingecko.com/en/coins/venus-usdc` page open and tried to add the token from the page. When I went back to wallet page and changed network to BSC, Coingecko page crashed

## Steps to Reproduce

   1. Clean profile on nightly
   2. Login into wallet
   3. Open `https://www.coingecko.com/en/coins/venus-usdc` in a new tab and try to add the token
   4. Shows network error on the bottom left side of the page
   5. Go back to wallet page and change network to BSC, Coingecko tab crashes 

## Actual result:

Page webview crash when trying to change wallet network.  Crash Report: https://share.backtrace.io/api/share/WBx1aHA6fXx19NC0H40l05U2

## Expected result:
No webview crash

## Reproduces how often: 

Only Once. Tried a few times to repro but couldn't

## Brave version (brave://version info)

Brave | 1.41.47 Chromium: 102.0.5005.78 (Official Build) nightly (64-bit)
-- | --
Revision | `df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}`
OS | Windows 11 Version 22H2 (Build 22621.1)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Not sure
- Can you reproduce this issue with the beta channel? Not sure
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

Not sure of this is wallet related crash but adding it to the board. cc: @bbondy

**Comment by srirambv** [comment]
One more crash but on a different page. This time it crashed when trying to add a custom network via `https://chainlist.org`. Crashing page was `https://trustwallet.org`. Link to crash https://share.backtrace.io/api/share/8vYuZcNThlBZa3i3bNx3GO0

**Comment by jamesmudgett** [comment]
CG seems to target MM directly or reports an error message. 

![Image](https://github.com/brave/brave-browser/assets/318119/d10dfc8d-12cb-4527-a82a-9e0047d612fb)

**Comment by srirambv** [comment]
No longer crashes webview. Closing the issue as stale
