### ISSUE TITLE
Implement Solana SignAndSendTransaction, SignTransaction, and SignAllTransactions in Wallet UI

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#23369]
## Description 

Implement UI for the following Solana Dapp requests
 - SignAndSendTransaction
 - SignTransaction
 - SignAllTransactions

## Actual result:

see: https://github.com/brave/brave-core/pull/13439

## Expected result:
When signing Solana dapp transactions, the UI should display relevant information regarding the pending signature request.

**Comment by kjozwiak** [comment]
The above will require `1.41.80` or higher for `1.41.x` verification 👍

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.41.86 Chromium: 103.0.5060.66 (Official Build) beta (64-bit) </th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>20b1569438a85e631d15e83eb355e3e326e5da6f-refs/branch-heads/5060@{#1066}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.708)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/13666>brave/brave-core#13666</a></li>
         <li>Verified able to sign and send transactions (single/multiple)</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/176920408-6c33167d-3809-488c-8d28-0b490206f663.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/176925736-d4f12e37-01af-4f84-9358-8d19752b6181.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/176926843-f812881c-8294-4017-8d67-ed0db8e1465b.mov>
      </td>
   </tr>
</table>
