### ISSUE TITLE
Add custom token fails for other EVM's

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23360]
## Description 

Add custom token fails for other EVM's. 

## Steps to Reproduce

   1. Install 1.40.91
   2. Visit `https://www.coingecko.com/en/coins/railgun` and add token
   3. Reload wallet page, shows token listed and available under add tokens
   4. Switch network to Fantom Opera
   5. Visit `https://www.coingecko.com/en/coins/wrapped-turtlecoin` and try to add coin
   6. Shows added successfully but coin is not listed under visible asset
   7. Manually enter token details from `https://ftmscan.com/token/0x6a31Aca4d2f7398F04d9B6ffae2D898d9A8e7938` shows error that it can't add custom asset

## Actual result:

https://user-images.githubusercontent.com/17010094/172863009-ea618746-08fd-41f2-bc44-928b536c7853.mp4

## Expected result:
Should be able to add other network's custom token similar to how it works on release channel
![image](https://user-images.githubusercontent.com/17010094/172863993-a12cb8bb-74f4-4a99-8e8e-ecc3bec08877.png)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.40.91 Chromium: 102.0.5005.78 (Official Build) beta (64-bit) 
-- | --
Revision | `df6dbb5a9fd82af3f567198af2eb5fb4876ef99c-refs/branch-heads/5005_59@{#3}`
OS | Windows 11 Version 21H2 (Build 22000.708)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @jamesmudgett @HEagle18 @Douglashdaniel @muliswilliam

**Comment by yrliou** [comment]
Fixed by https://github.com/brave/brave-core/pull/13705.
