### ISSUE TITLE
bug accessing apeswap.finance 

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#23366]
## Description 

Metamask seems to be taking over flow even when brave wallet is selected from wallet option. See video attached. Using version Version 1.39.120

https://user-images.githubusercontent.com/12224304/172894595-c4267c27-02a5-47e5-98c9-c9f79d948cb6.mov

## Steps to Reproduce

   1. try connecting brave wallet on brave release Version 1.39.120
   2. 
   3. 

## Actual result:

Metamask just takes over.

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by HEagle18** [comment]
I've struggled reproducing this 100% of the time. It may happen when a user has extensions preferred and there is already a request from metamask. Also note that new users have setting set to 'extension preferred'

**Comment by bbondy** [comment]
This is working fine for me. It gives a Brave Wallet option and that option works.
Closing but let me know if you still experience an issue.
The video above doesn't show the same wallet selection screen so maybe they recently added support.

![Image](https://user-images.githubusercontent.com/831718/176272307-90b69c2a-0a6d-4ce0-aeaf-f3de1d3875b5.png)
