### ISSUE TITLE
Add filecoin network chooser

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#23368]
We need to add additional row with filecoin testnet in create new account option.
Also we need to add chooser for filecoin network when import hardware filecoin account.
Base branch is origin/brave_23241.
For adding account AddFilecoinAccount(string accountName, string fileCoinNetwork) => (bool success); method should be used.
Where filecoin network is filecoin chain_id which is "t" or "f";
For the chooser, when we import hardware account, HardwareWalletAccount struct now has optional "network" field with same scope("t" or "f").
Chooser when import account by private key is already working.

**Comment by srirambv** [comment]
Removing Android label since Filecoin isn't supported on Mobile yet.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.43.81 Chromium: 104.0.5112.102 (Official Build) (64-bit)
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | Linux

- Verified steps from [ brave/brave-core#13895](https://github.com/brave/brave-core/pull/13895)
- Verified Filecoin mainnet accounts have a different naming convention starting with `f`
- Verified Filecoin testnet accounts have a different naming convention starting with `t`
- Verified when no Filecoin account is created, selecting Filecoin (Mainnet/Testnet) prompts to create an account on the selected network
- Verified able to create both Mainnet and Testnet accounts and are listed one below the other irrespective of how its created
- Verified transaction works on Mainnet 
- Encountered [#24824](https://github.com/brave/brave-browser/issues/24824), [#24946](https://github.com/brave/brave-browser/issues/24946), [#24947](https://github.com/brave/brave-browser/issues/24947) & [#24949](https://github.com/brave/brave-browser/issues/24949)


------------------------
Verification passed on

Brave | 1.43.81 Chromium: 104.0.5112.102 (Official Build) (64-bit)
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | Windows 11 Version 21H2 (Build 22000.795)

- Verified steps from [ brave/brave-core#13895](https://github.com/brave/brave-core/pull/13895)
- Verified Filecoin mainnet accounts have a different naming convention starting with `f`
- Verified Filecoin testnet accounts have a different naming convention starting with `t`
- Verified when no Filecoin account is created, selecting Filecoin (Mainnet/Testnet) prompts to create an account on the selected network
- Verified able to create both Mainnet and Testnet accounts and are listed one below the other irrespective of how its created
- Verified transaction works on Mainnet
- Encountered [#24824](https://github.com/brave/brave-browser/issues/24824), [#24946](https://github.com/brave/brave-browser/issues/24946), [#24947](https://github.com/brave/brave-browser/issues/24947) & [#24949](https://github.com/brave/brave-browser/issues/24949)


------------------------
Verification passed on

Brave | 1.43.81 Chromium: 104.0.5112.102 (Official Build) (arm64)  
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [ brave/brave-core#13895](https://github.com/brave/brave-core/pull/13895)
- Verified Filecoin mainnet accounts have a different naming convention starting with `f`
- Verified Filecoin testnet accounts have a different naming convention starting with `t`
- Verified when no Filecoin account is created, selecting Filecoin (Mainnet/Testnet) prompts to create an account on the selected network
- Verified able to create both Mainnet and Testnet accounts and are listed one below the other irrespective of how its created
- Verified transaction works on Mainnet
- Encountered [#24824](https://github.com/brave/brave-browser/issues/24824), [#24946](https://github.com/brave/brave-browser/issues/24946), [#24947](https://github.com/brave/brave-browser/issues/24947) & [#24949](https://github.com/brave/brave-browser/issues/24949)
