### ISSUE TITLE
Upgrade from Chromium 102.0.5005.99 to 102.0.5005.115

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#23372]
Minor Chromium bump.

https://chromium.googlesource.com/chromium/src/+log/102.0.5005.99..102.0.5005.115?pretty=fuller&n=10000

QA tests:

Check branding items
Check for version bump

Additional checks:

No specific code changes in Brave (only line number changes in patches).

**Comment by kjozwiak** [comment]
Closing as this was merged into `1.39.x` as per https://github.com/brave/brave-core/pull/13718.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.39.122 Chromium: 102.0.5005.115 (Official Build) (64-bit)
-- | --
Revision | 174dbe6e33bc81994fceb71d751be201d0b4803d-refs/branch-heads/5005_109@{#3}
OS | Windows 11 Version 21H2 (Build 22000.708)
```

![image](https://user-images.githubusercontent.com/2602313/173020086-c179c661-0a4c-43e8-b12b-82f5475929ff.png)

**Comment by LaurenWags** [comment]
Verified using

```
Brave	1.39.122 Chromium: 102.0.5005.115 (Official Build) (arm64) 
Revision	174dbe6e33bc81994fceb71d751be201d0b4803d-refs/branch-heads/5005_109@{#3}
OS	macOS Version 12.4 (Build 21F79)
```

<img width="1192" alt="M1" src="https://user-images.githubusercontent.com/28145373/173063884-02c83700-1a79-4887-8863-54790fe0e972.png">
