### ISSUE TITLE
Global shields settings should be set to `Standard`, `Standard`, and `Cross-site` for `Trackers & ads blocking`, `Fingerprinting` and `block cookies` 

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#23370]
## Description 

Currently in the nightly build, global shield settings are incorrect for `Trackers & ads blocking`, `Block fingerprinting`, `Block cookies`

## Steps to Reproduce

   1. Install 1.41.50
   2. Launch brave
   3. Open brave://settings/shields

## Actual result:
Global shields settings show as below: 
    `Trackers & ads blocking` show `Aggressive`
    `Block fingerprinting` show `Strict, may break sites`
    `Block cookies` show `All`

`1.41.50`
----
![image](https://user-images.githubusercontent.com/98358127/172916449-21affd33-bafd-4f75-a4db-85b793384350.png)

## Expected result:
  Global shields setting should be default
    `Trackers & ads blocking` should show `Standard`
     `Block fingerprinting` show `Standard`
     `Block cookies` show `Only cross-site`

1.39.120
---
![image](https://user-images.githubusercontent.com/98358127/172918757-def81a60-a419-417c-88dd-4542c45ff4ed.png)

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Brave | 1.41.50 Chromium: 102.0.5005.99 (Official Build) nightly (64-bit)
-- | --
Revision | 870f7bcc58dfa811cc68c2186439721385e086d0-refs/branch-heads/5005@{#1125}
OS | Windows 11 Version 21H2 (Build 22000.675)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@rebron

**Comment by bridiver** [comment]
after some testing it appears that the main settings page is just displaying the wrong default. The shields panel for any given site shows the correct default and testing shows that the behavior matches the expected defaults

**Comment by rebron** [comment]
Dupe of https://github.com/brave/brave-browser/issues/23304
