### ISSUE TITLE
[De-AMP] Pages with un-quoted attributes for canonical link don't get redirected

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#23388]
## Description 

If the page has a canonical link that doesn't use quotes in the `link` tag then the regex doesn't catch that. E.g. if the tag looks like `link rel=canonical href=https://brave.com`. This doesn't technically comply with the [AMP spec](https://amp.dev/documentation/guides-and-tutorials/learn/spec/amphtml/#canon) but is valid HTML.

## Steps to Reproduce

   1. Make sure De-AMP setting is on in brave://settings/shields
   2. Go to https://shivankaul.com/brave/de-amp/test-amp-no-quotes.html

## Actual result:

End up on https://shivankaul.com/brave/de-amp/test-amp-no-quotes.html i.e. doesn't get de-amped

## Expected result:
Go to the canonical link i.e. https://brave.com

## Reproduces how often: 

Easily

**Comment by kjozwiak** [comment]
Removing the `1.42.x` milestone as this hasn't landed. The above will need to go into `master` first which is `1.43.x` right now and then will need to be uplifted into `1.42.x` if we want to get this into the `1.42.x` release. As per process, once this lands, please set the correct milestone and the release team will change the milestones once the issue has been uplifted.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.43.55 Chromium: 104.0.5112.81 (Official Build) beta (64-bit)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | Windows 11 Version 21H2 (Build 22000.795)
```

Verified using the testplan from https://github.com/brave/brave-core/pull/13729#issue-1266971183

### Confirmed https://shivankaul.com/brave/de-amp/test-amp-no-quotes.html redirects to https://brave.com/

`brave://settings/shields`|`redirect`
-----|----
<image width="850" alt="image" src="https://user-images.githubusercontent.com/98358127/182493603-fff960f7-6b20-4f22-b897-d4291e8b2046.png">|<image width="850" alt="image" src="https://user-images.githubusercontent.com/98358127/182493785-bc4b21ad-093d-4916-9afb-242fbc46bf43.png">

**Comment by stephendonner** [comment]
## Verified `PASSED` using

`Brave Beta 1.43.74, Chromium 104.0.5112.102`

Followed the steps and used the minimal testcase from https://github.com/brave/brave-browser/issues/23388#issue-1266968702.

de-AMP pref | test URL | brave.com
-------------|----------|------------
![Screenshot_20220818-091459](https://user-images.githubusercontent.com/387249/185445253-9de87e06-a60e-4976-b606-457930ce82a3.png) | ![Screenshot_20220818-091700](https://user-images.githubusercontent.com/387249/185445258-db0cbe81-50d6-4157-aa24-0f2c2c72530d.png) | ![Screenshot_20220818-091704](https://user-images.githubusercontent.com/387249/185445263-fe6e31a5-5c87-41f0-9f19-1c2f6eaf9d85.png)
