### ISSUE TITLE
Update stats can undercount when laptop is suspended

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#2338]
## Description 

The stats update ping is currently sent immediately on startup and then once an hour thereafter. T?his will undercount in the following scenario:

- A user's laptop sends a ping to the stats server
- The user closes the laptop
- The next day, the user runs Brave for less than one hour

To remedy that, we'll instead check every five minutes and only send a ping if we haven't already done it for today.

## Steps to Reproduce

   1. Start with a clean profile on a laptop
   2. Launch Brave with verbose logging set to 1 (`npm run start -- --v=1`)
   3. Verify that the startup ping is sent by checking logs (looks like `Brave stats ping, url ...`)
   4. Close the laptop lid, putting the laptop into a suspended state
   5. Wait long enough for the periodic ping to fire (the periodic ping fires once an hour, so this means waiting slightly longer than an hour).
   6. Open the laptop, resuming it
   7. Verify that the periodic ping wasn't sent, even though more than an hour has passed.

## Actual result:

The periodic ping isn't sent, even though more than an hour has elapsed.

## Expected result:

The periodic ping should be sent.

## Reproduces how often: 

Always.

**Comment by btlechowski** [comment]
Verification Passed on

Brave | 0.57.17 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Windows 7

Used testcases from https://github.com/brave/brave-core/pull/1008
TC1 - PASSED:
`Verifies that the startup ping is sent and no periodic pings are sent when a date change doesn't occur while running Brave`
1st ping `[2628:8108:1206/230824.355:VERBOSE1:brave_stats_updater.cc(157)] Brave stats ping, url: https://laptop-updates.brave.com/1/usage/brave-core?platform=winx64-bc&channel=release&version=0.57.17&daily=true&weekly=true&monthly=true&first=true&woi=2018-12-03&ref=none`
2nd ping: `none`

TC2 - PASSED
`Verifies that the startup ping is sent and one periodic ping is sent when a date change does occur while running Brave`
1st ping: `[9028:9848:1206/235355.494:VERBOSE1:brave_stats_updater.cc(157)] Brave stats ping, url: https://laptop-updates.brave.com/1/usage/brave-core?platform=winx64-bc&channel=release&version=0.57.17&daily=true&weekly=true&monthly=true&first=true&woi=2018-12-03&ref=none`
2nd ping: `[9028:9848:1207/001254.841:VERBOSE1:brave_stats_updater.cc(157)] Brave stats ping, url: https://laptop-updates.brave.com/1/usage/brave-core?platform=winx64-bc&channel=release&version=0.57.17&daily=true&weekly=false&monthly=false&first=false&woi=2018-12-03&ref=none`
