### ISSUE TITLE
Lose cookies during channel bump upgrade 

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#2339]
## Description 

Upgrade browser from `0.(X-1).*` to `0.X.*` will automatically relaunch and showing white window with extensions crashed notifications but cookies will be erased 

## Steps to Reproduce

   1.  Download older version before channel bump (ex. current version of dev is 0.58.10 download 0.57.4)
   2.  open "About Brave"
   3.  Waiting for update process prompting relaunch
   4.  Click relaunch
   5.  There will be a successful relaunch with white window

## Actual result:

![update-relaunch](https://user-images.githubusercontent.com/11330831/49399289-c22dc500-f6f5-11e8-8b7c-7895cb2fdd06.png)
And lost only cookies after force quit Brave

## Expected result:
Cookies should be preserved 

## Reproduces how often: 

Very often. Doing a system sleep at least 5 mins between step 3 and step 4 will make it easier to reproduce

## Brave version (brave://version info)

every channel bump on all channels
`0.(X-1).*` to `0.X.*` 
### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? YES

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by simonhong** [comment]
I also can't reproduce with dev release.
Cookies are not changed during the updating from 0.57.2 to 0.58.10.
(Browser was closed and reopened after clicking relaunch button)

**Comment by darkdh** [comment]
it requires multiple times trying. 
And I notice there will be a `Profile error occurred` titled dialog showing for a few seconds
It is `ShowProfileErrorDialog` and the most possible caller would be `CreatePrimaryProfile` in `chrome_browser_main.cc` after both `GetStartupProfile` and `GetFallbackStartupProfile` still gets empty profile

**Comment by darkdh** [comment]
This is what processes of it looks like when white window shows up
```
darkdh           79255 124.7  0.9  5058620 317560   ??  R    12:11PM   8:47.08 /Applications/Brave Browser Beta.app/Contents/MacOS/Brave Browser Beta --disable-chrome-google-url-tracking-client --disable-domain-reliability --disable-features=SharedArrayBuffer,DefaultEnableOopRasterization,VizDisplayCompositor,AutofillSaveCardSignInAfterLocalSave,kAutofillServerCommunication --enable-features=EnableEmojiContextMenu,DesktopPWAWindowing,fill-on-account-select,NewExtensionUpdaterService --enable-tab-audio-muting --no-pings
darkdh           79021   0.0  0.0  4334132   9584   ??  S    12:05PM   0:00.02 /Applications/Brave Browser Beta.app/Contents/Versions/70.0.56.7/Brave Browser Beta Framework.framework/Helpers/crashpad_handler --monitor-self-annotation=ptype=crashpad-handler --database=/Users/darkdh/Library/Application Support/BraveSoftware/Brave-Browser-Beta/Crashpad --metrics-dir=/Users/darkdh/Library/Application Support/BraveSoftware/Brave-Browser-Beta --url=https://laptop-updates.brave.com/1/bc-crashes --annotation=channel=beta --annotation=plat=OS X --annotation=prod=Brave_Mac --annotation=ver=70.0.56.7 --handshake-fd=9
darkdh           79257   0.0  0.0  4325940   9500   ??  S    12:11PM   0:00.01 /Applications/Brave Browser Beta.app/Contents/Versions/70.0.56.7/Brave Browser Beta Framework.framework/Helpers/crashpad_handler --monitor-self-annotation=ptype=crashpad-handler --database=/Users/darkdh/Library/Application Support/BraveSoftware/Brave-Browser-Beta/Crashpad --metrics-dir=/Users/darkdh/Library/Application Support/BraveSoftware/Brave-Browser-Beta --url=https://laptop-updates.brave.com/1/bc-crashes --annotation=channel=beta --annotation=plat=OS X --annotation=prod=Brave_Mac --annotation=ver=70.0.56.7 --handshake-fd=9
```

**Comment by darkdh** [comment]
The relaunching instance is still "before upgrade" one, I can tell from `RunningChromeVersion`, `SingletonCookie` and `SingletonLock`. My test subject happens to have chromium bump so RunningChromeVersion is 70.0.56.7 vs 71.0.57.8

**Comment by simonhong** [comment]
The main difference from my test is white window shows or not.
I'm repeating below steps.

1. install 70.0.56.7
2. set/check cookie status
3. waiting to update and click relaunch
4. Launch manually because relaunch is failed
5. check cookie status and `ps -aux` to check older version is running

Need to find how to make white window visible.

**Comment by darkdh** [comment]
yes, only white window will make you lose cookies

**Comment by simonhong** [comment]
During the termination (by restart or by quit), downloaded new version of app bundle is copied.
So, I think there is some timing issue during the restart.
Not sure but I think restart is triggered before fully copied.
This is just assumption. need to verify from sparkle source code and when copy is done.

**Comment by simonhong** [comment]
@diracdeltas Didn't you see relaunch fail?

**Comment by diracdeltas** [comment]
relaunch seemed to succeed

**Comment by simonhong** [comment]
Thanks for reporting.
Relaunching after update might not be related with this cookie lost.
Also sparkle doesn't touch user data during the update.
Need to investigate more.

**Comment by diracdeltas** [comment]
in case it helps: i checked `chrome://settings/siteData` and it showed all my cookies even though i was logged out of all sites

**Comment by simonhong** [comment]
> i was also unable to autofill passwords until restarting my computer.
Quit & restart didn't help?

**Comment by diracdeltas** [comment]
browser restart did not help, i had to restart my mac

i just updated to 0.60.3 though, and all my cookies are preserved and autofill works

**Comment by diracdeltas** [comment]
Just encountered this again when updating to 0.61.51; cookies were still lost when I restarted my computer.

maybe this has something to do with Chromium being unable to decrypt the cookies

**Comment by diracdeltas** [comment]
Also in case it helps, i updated by clicking on the green arrow button in the browser top bar, not by going to chrome://settings.

**Comment by simonhong** [comment]
I didn't see this for a long time. if anyone can see this again feel free to reopen.

**Comment by rebron** [comment]
@diracdeltas Let us know if this is still happening. We had the 67.x update last week and doing another update soon so have a chance to test another time or two.
