### ISSUE TITLE
User needs to tap twice on start new chain CTA to load next screen in sync flow

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#23398]
## Description 
On the first screen in the sync flow, user must tap twice on `Start a new sync chain` to proceed to the next screen

<img width="400" alt="0" src="https://user-images.githubusercontent.com/17885425/173111167-679a42f4-e9f9-4b90-9c1d-f0d94e493fa6.png">

## Steps to reproduce 

  1.Clean install
  2. Menu > Settings > Sync
  3. Tap once on `Start a new sync chain`
  4. Observe and wait for next screen to load (it doesn't)
  5. Tap again on `Start a new sync chain`

## Actual result 
Tapping once doesn't load next screen, user must tap again.  

## Expected result
Next screen should load when user taps once

## Issue reproduces how often 
Easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung Galaxy Devices
   - Android version: 12
   
## Brave version
1.40.91, Chromium 102.0.5005.78

**Comment by stephendonner** [comment]
## Verified `PASSED` using `Brave` `1.48.140`, `Chromium`, `109.0.5414.119` on a `Google Pixel XL` (`arm64`) running `Android 9`

### Steps:
1. installed `1.48.140`
2. launched Brave
3. tapped the 3-dots menu -> `Settings` -> `Sync`
4. tapped `Start a new sync chain`
5. (ensured it only required a single tap)
6. tapped `Add a Mobile Device`
7. (ensured it only required a single tap)
8. tapped `Add a Computer`
9. (ensured it only required a single tap)

### `Screencast`:
https://user-images.githubusercontent.com/387249/214782044-15d09e9a-3931-4073-873f-2d84fb1e7fa3.mp4
