### ISSUE TITLE
[Followup to #23111] Buttons on approval screen needs more bottom padding

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23392]
## Description 
[Followup to #23111] Buttons on approval screen needs more bottom padding. Issue happens with or without bottom toolbar enabled

## Actual result 

![image](https://user-images.githubusercontent.com/17010094/173046489-58284bef-3efa-4fab-ba3a-fcad7aaab8bb.png) | ![image](https://user-images.githubusercontent.com/17010094/173046517-c26376f4-d27f-4c76-a72a-e87187c553e5.png) | ![image](https://user-images.githubusercontent.com/17010094/173046530-53deac0e-56a2-4a05-bb92-fbca09b1bff7.png)
-- | -- | --

## Expected result
Buttons needs bottom padding.

## Issue reproduces how often 

Easy
## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 12
   
## Brave version
1.41.53

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @qamarngr @jamesmudgett

**Comment by kjozwiak** [comment]
The above will require `1.40.102` or higher for `1.40.x` verification 👍
