### ISSUE TITLE
Crash with http referrer

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#234]
Scheme mismatch error for referrer setting happens with these steps:

1. Search "flash game"
2. Click on the first result: www.y8.com/tags/Flash
3. Click on any flash game

Actual results:
Crash

Expected results:
No crash

---

Alt site which can sometimes reproduce:
FATAL error again today visiting http://www.benzworld.org/forums/w126-s-se-sec-sel-sd/

URL = http://staticxx.facebook.com/connect/xd_arbiter/r/oVjM2wVZ10b.js?version=42#channel=f385f5a644c3e9&origin=http%3A%2F%2Fwww.benzworld.org
Referrer = https://staticxx.facebook.com/```

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7
