### ISSUE TITLE
Crash when creating a new Bookmark folder

### ISSUE THREAD

**Issue by HunterMeyer** [brave/brave-browser#23406]
## Description
Brave crashes when creating a new Bookmark folder after selecting the parent folder option.

## Steps to reproduce
   1. Press the Bookmark icon to create a new bookmark
   2. Click the Edit link to edit bookmark
   3. Tap the Folder option
   4. Click New Folder
   5. Tap the Parent folder option
   6. Observe crash

## Actual result
Brave crashes

## Expected result
I should be able to select the parent folder I want the new folder to go under.

## Issue reproduces how often
Everytime

## Version/Channel Information:
- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? N/A

## Device details
   - Device type (Phone, Tablet, Phablet): phone
   - Android version: 12
   
## Brave version
1.39.120

## Screenshots

https://user-images.githubusercontent.com/4690516/173149595-a67047ba-f385-4d98-b976-d1dcbbb734f3.mp4

**Comment by 4444dogs** [comment]
I can confirm that this issue can be reproduced.

**Comment by HunterMeyer** [comment]
Looks like this has been resolved in the latest release.
