### ISSUE TITLE
Update brand logo for Ecosia

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#23405]
## Description 

Per https://bravesoftware.slack.com/archives/C015G1THCAJ/p1654884889038839

Please update the brand logo for Ecosia
![New Ecosia logo 6 22](https://user-images.githubusercontent.com/7606853/173131148-806aef34-338f-4819-974e-2a86397c660c.png)

**Comment by simonhong** [comment]
It seems desktop doesn't need to update from browser side. Brand logo is updated in backround when user loaded ecosia.com once.

**Comment by Uni-verse** [comment]
Verified on `Samsung GS 21` & `Tab S7` using

```
Brave	1.41.86 Chromium: 103.0.5060.66 (Official Build) beta (64-bit) 
Revision	20b1569438a85e631d15e83eb355e3e326e5da6f-refs/branch-heads/5060@{#1066}
OS	Android 12; Build/SP1A.210812.016
```

- Verified brand logo update in `url bar` using new tab page search
- Verified brand logo is updated in `Brave Shields` and `Brave Rewards`
- Verified brand logo is updated in `url`, `Sheilds`, `BR panel` for `upgraded profiles`

URL | Shields | Rewards
-|-|-
![screenshot-1656704160776](https://user-images.githubusercontent.com/17885425/176959296-d534bcd2-c430-476d-aa3f-479d2cf0d3ce.png) | ![screenshot-1656704364299](https://user-images.githubusercontent.com/17885425/176959298-a311b739-9b98-4980-bf6d-02f60fa7d3d9.png) | ![screenshot-1656704377817](https://user-images.githubusercontent.com/17885425/176959301-6eeefbca-b873-452c-81c2-86575324fefe.png)
![screenshot-1656702878961](https://user-images.githubusercontent.com/17885425/176959452-4cf90242-9e3c-4e04-adba-3f8b446b75b3.png) | ![screenshot-1656704641595](https://user-images.githubusercontent.com/17885425/176959750-b8972d6c-b216-43c2-b585-6256c4e9c3c4.png) | ![screenshot-1656704653767](https://user-images.githubusercontent.com/17885425/176959760-8bdc1b00-9d93-47a0-bd2b-9c10b062d29c.png)
