### ISSUE TITLE
Blank photo when posting to Instagram from Braver Browser on desktop

### ISSUE THREAD

**Issue by msdosfx** [brave/brave-browser#23409]
PLEASE USE THE TEMPLATE BELOW TO PROVIDE INFORMATION ABOUT THE ISSUE. 
INSUFFICIENT INFO WILL GET THE ISSUE CLOSED. IT WILL ONLY BE REOPENED AFTER SUFFICIENT INFO IS PROVIDED-->

## Description 
 When I try to post a photo to Instagram from Brave Browser, the image shows up in the upload window, then when I go to the next window or the post window it is blank. It is also blank if I actually post it. I can post from the Creator Studio in Brave Browser with some success, but not in the normal Instagram web page. I switched to Firefox and it worked fine. I have done a bit of tweaking to my privacy/security settings in Brave so this might be causing the issue, but my Firefox is pretty hardened and don't have any issues posting. 

## Steps to Reproduce

   1. Go into Instagram.com
   2. Hit the + 
   3. upload a photo from my computer (typically this is from a Syncthing folder but I don't know why that would matter)
   4. Photo shows up in the upload Window
   5. hit the "next" button
   6. Photo disappears
   7. hit the "next" button
   8. hit the "share" button
   9. a blank white photo is uploaded to my profile
   10. check on mobile, and it is in fact blank

## Actual result:

Photo is blank

## Expected result:
Photo shouldn't be blank

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

<html>
<body>

1.39.122 Chromium: 102.0.5005.115 (Official Build) (64-bit)
--
Revision | 174dbe6e33bc81994fceb71d751be201d0b4803d-refs/branch-heads/5005_109@{#3}
OS | Windows 10 Version 21H2 (Build 19044.1706)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Disabling Brave Shields resolves the issue
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? I won't install chrome

**Comment by rebron** [comment]
@msdosfx Do you have Shields set up to be in aggressive mode? I'm not able to reproduce uploading to instagram with Shields up. Can you try uploading an image from your desktop?

**Comment by msdosfx** [comment]
![Annotation 2022-06-26 063344](https://user-images.githubusercontent.com/85908634/175810195-8e851bbd-358a-4278-95b7-0ea59c21dd55.jpg)
![Annotation 2022-06-26 063451](https://user-images.githubusercontent.com/85908634/175810197-d178f866-4106-476f-81e2-9108663a1f96.jpg)

**Comment by ryanbr** [comment]
Allowing Facebook Logins, and standard fingerprinting would improve things for instagram.  @msdosfx

**Comment by ryanbr** [comment]
Still an issue @msdosfx ?

Just retested this  
![instagram-uploadtest](https://user-images.githubusercontent.com/1659004/212657567-ecb55d6c-a9c5-49fb-b9a1-ded8e951d608.png)
![instagram-uploadtest2](https://user-images.githubusercontent.com/1659004/212658393-39c7cc49-6653-4c18-9fb0-80e85a1076fb.png)
