### ISSUE TITLE
deleted sites from muon are not being imported to Rewards - follow up to PR 736

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#2340]
## Description 
Found while testing https://github.com/brave/brave-core/pull/736

Per test plan in https://github.com/brave/brave-core/pull/736, Deleted sites from muon should be imported as 'excluded' sites in Brave Rewards.

## Steps to Reproduce

Follow test plan in https://github.com/brave/brave-core/pull/736 or

1. Have a muon Brave profile set up with 0.25.2 where you have Payments data (wallet, etc). Have some sites in table, delete some others.
2. Close muon Brave.
3. Ensure you don’t have any Brave-Browser profile for b-c Brave.
4. Launch 0.57.12.
5. Import only Payments data from Brave (Brave > Import Bookmarks and Settings > choose Brave (old) > only have Payments checked
6. Navigate to 6 sites. 

## Actual result:
When you open the popup to view all sites, no link for restoring excluded sites. You can also try visiting a site that you know was excluded in muon. --> Watch it get added to your A-C table after specified time from settings. Alternatively, I clicked on the BAT logo and saw that the toggle for ‘Include in Auto-Contribute’ for this site was set to On.

![screen shot 2018-12-03 at 3 52 46 pm](https://user-images.githubusercontent.com/28145373/49401875-61fb4b00-f716-11e8-988e-1d469ab02435.png)

## Expected result:
Deleted sites from muon Payments should be 'excluded' in Rewards.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.57.12 Chromium: 71.0.3578.75 (Official Build) (64-bit)
-- | --
Revision | 06ef00b5279f93f8e0c1e73acedd49d7dcc09767-refs/branch-heads/3578@{#836}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information
cc @bsclifton

**Comment by bsclifton** [comment]
Closing as `wontfix` after discussion on Slack. Let's re-open if this should indeed block the release (and needs a fix)
