### ISSUE TITLE
Create providers only in secure contexts

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#23407]
Only define `window.ethereum` and `window.solana` in a secure context.
I.e. only for pages with `window.isSecureContext`

This includes `127.0.0.1`, `localhost`, and `https` sites.
But not URLs like http://a.com

**Comment by VERDIBOTZ1** [comment]
Tanks information

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.40.101 x64 build
- Verified `window.ethereum` is available only for `https` contexts 

**Oppo Reno 5 (Android 12)**

HTTPS | HTTP
-- | --
![image](https://user-images.githubusercontent.com/17010094/174076565-d2a5d86a-bec9-4ef4-8e4a-ca85c4f8a8a7.png) | ![image](https://user-images.githubusercontent.com/17010094/174076838-5577d5ad-080e-4750-97e7-d903790a6904.png)


**Samsung Tab A (Android 10)**

HTTPS | HTTP
-- | --
![image](https://user-images.githubusercontent.com/17010094/174077447-1887e3aa-2ec7-4128-b7e2-1c53d2430741.png) | ![image](https://user-images.githubusercontent.com/17010094/174077522-eefc4bd5-29b0-4751-94f7-3617e659a02d.png)
