### ISSUE TITLE
Problem on uniswap on Rinkeby network

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#23410]
Investigate does that work or not as I tried on Rospten and it worked ok:
BUG: On https://uniswap.org/#/swap?chain=rinkeby when I'm attempting to swap ETH for DAI with ETH in my account I'm able to start the transaction. Then when I go to switch the gas limit from optimal to high and hit ok, rather than take me back to the main screen it refreshes the page without allowing me to confirm the transaction with the gas fee set to the high option. This may be an issue with the way uniswap works with rinkeby network, but I haven't confirmed.

Updated steps:
Do any transaction through DApps and Edit gas on approve/reject dialog. It crashes in most cases. It doesn't matter what network or is it uniswap or anything else.

**Comment by kdenhartog** [comment]
If it helps at all for reproducing this issue I'm using a Moto G Stylus 2022 with Android 11 on Brave Nightly with the Dapp support flag enabled currently.

**Comment by SergeyZhukovsky** [comment]
@kdenhartog I managed to replicate that. The fix is under review https://github.com/brave/brave-core/pull/13756. It doesn't happen always though as it's a race condition in updating a UI while the object is getting destroyed. That's why I perhaps didn't hit it when tried once. Thanks for finding that!
