### ISSUE TITLE
Website issues: namecheap

### ISSUE THREAD

**Issue by daniesy** [brave/brave-browser#2341]
## Description 
The domain search functionality of namecheap.com isn't working

## Steps to Reproduce

   1. Go to [namecheap.com](https://namecheap.com)
   2. Search for a domain
   3. The search results don't appear

## Actual result:
<img width="1552" alt="screenshot 2018-12-03 at 23 32 11" src="https://user-images.githubusercontent.com/3399101/49402944-0b146680-f754-11e8-9a7d-1974401f38ec.png">

## Expected result:
<img width="1552" alt="screenshot 2018-12-03 at 23 35 16" src="https://user-images.githubusercontent.com/3399101/49402964-1ff0fa00-f754-11e8-9a7b-203d823eb9ff.png">

## Reproduces how often: 
Every time i search for a domain and i have the shields turned on.

## Brave version (brave://version info)
Brave | 0.58.10 Chromium: 71.0.3578.53 (Official Build) dev(64-bit)
Revision | 599fb72e740eab9d10609f1ed28a2ad669f82c1a-refs/branch-heads/3578@{#669}
OS | Mac OS X

### Reproducible on current release:
- Yep

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields?  **Yep**
- Is the issue reproducible on the latest version of Chrome? **Nope**

### Additional Information
It happens to many other websites, but this is the last one i remembered. The problem is that i get no warning that content is blocked and, at first, i thought that the website is blocked.

**Comment by srirambv** [comment]
Issue is due to CORS policy. Disable shields is the only workaround
![image](https://user-images.githubusercontent.com/17010094/49417737-ff04c500-f7a4-11e8-9eb0-ed750ae1aec7.png)

**Comment by iefremov** [comment]
Should be fixed together with #2252

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.58.20 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Windows 7

![image](https://user-images.githubusercontent.com/34715963/50929877-b48afe00-145e-11e9-94b1-d0fc297bc7bd.png)
