### ISSUE TITLE
Sidebar shows even when visibility is set to "never"

### ISSUE THREAD

**Issue by mzenz** [brave/brave-browser#23416]
## Description 

The sidebar reappears after setting its visibility to `never`.

## Steps to Reproduce

   1. Set sidebar visibility to "never"
   2. Use Brave for an undetermined period of time

## Actual result:

Sidebar is visible despite being set to `never`

## Expected result:

Don't see sidebar at all.

## Reproduces how often: 

Randomly.

## Brave version (brave://version info)
[Version 1.39.111 Chromium: 102.0.5005.61 (Official Build) (x86_64)](https://brave.com/latest/)

**Comment by rebron** [comment]
cc: @simonhong 

@mzenz This will be tougher to investigate if you're encountering this issue intermittently. If it's never, you shouldn't see it all.

**Comment by rebron** [comment]
@mzenz Are you still seeing issues with our latest 1.58.124 with sidebar set to "never"? There is a keyboard shortcut ctrl+B or cmd+B so if you inadvertently hit that keyboard shortcut, that's when you'll see it open and close.

**Comment by rebron** [comment]
Closing as stale. @mzenz Let us know if you're still seeing this issue and we'll reopen.
