### ISSUE TITLE
Tipping banner causes DCHECK crash in dev when monthly checkbox is checked

### ISSUE THREAD

**Issue by jasonrsadler** [brave/brave-browser#2342]
## Description 

When in dev environment, visiting a site and opening tip banner and clicking monthly checkbox causes DCHECK crash

## Steps to Reproduce

   1. run `npm start` in dev environment to start Brave dev
   2. Visit a site that supports monthly tipping, open panel, and send a tip
   3. On publisher banner, click checkbox to make a monthly tip

## Actual result:
Banner inlay turns white and a DCHECK crash with error occurs:
`[92550:775:1203/165444.656164:FATAL:find_properties_needing_update.h(75)] Check failed: original_local_border_box_properties_->Transform() == object_border_box.Transform() (0x30b29c6710 vs. 0x30b29c4790)"LayoutBlockFlow DIV class='sc-fQkuQJ EJAmK'"`
<img width="1915" alt="screen shot 2018-12-03 at 4 55 03 pm" src="https://user-images.githubusercontent.com/25326067/49404007-38ddb900-f71c-11e8-9463-6c40929a2a84.png">

## Expected result:
Checkbox should simply fill

## Reproduces how often: 
always

## Brave version (brave://version info)
Latest master branch (0.60.x) (actual DCHECK crash will not occur if on release build; unknown if error is still logged on release build)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by jasonrsadler** [comment]
This error does not reproduce on Linux

**Comment by NejcZdovc** [comment]
@jasonrsadler is this still a problem on the latest master?

**Comment by jasonrsadler** [comment]
This no longer seems to be an issue. 👍
