### ISSUE TITLE
`Set brave as your default browser` modal popup is displayed with incorrect background color

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#23422]
## Description 

`Set brave as your default browser` modal popup is displayed with incorrect background-color

## Steps to Reproduce

   1. NA
  

## Actual result:

![image](https://user-images.githubusercontent.com/38657976/173283356-e383e58c-503a-47da-8f9a-cc888388abaa.png)

## Expected result:

![image](https://user-images.githubusercontent.com/38657976/173283406-1f0dc01d-8fa0-4ec2-be9f-b4ad4c91278a.png)

## Reproduces how often: 

Easy
## Brave version (brave://version info)

<html>
<body>

Brave | 1.41.58 Chromium: 103.0.5060.42 (Official Build) nightly (64-bit)
-- | --
Revision | de0d840bf9439c31bd86bf74f065c31fdf9b208d-refs/branch-heads/5060@{#667}
OS | Windows 10 Version 21H2 (Build 19044.1706)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @rebron @mkarolin @emerick

**Comment by simonhong** [comment]
Looking now

**Comment by kjozwiak** [comment]
This is being uplifted as part of https://github.com/brave/brave-core/pull/13755 and can be verified using `1.40.101` or higher 👍 We should probably re-check to make sure that the above was actually fixed with `C103` now that we've merged it into `1.40.x`.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.40.101 Chromium: 103.0.5060.42 (Official Build) (x86_64)
-- | --
Revision | de0d840bf9439c31bd86bf74f065c31fdf9b208d-refs/branch-heads/5060@{#667}
OS | macOS Version 11.6.7 (Build 20G630)

`Dark` | `Light`
-------|--------
<img width="1312" alt="Screen Shot 2022-06-16 at 12 01 45 PM" src="https://user-images.githubusercontent.com/387249/174146103-60377544-6d70-457d-a2c9-18fda7c37ac8.png"> | <img width="1282" alt="Screen Shot 2022-06-16 at 12 00 10 PM" src="https://user-images.githubusercontent.com/387249/174146136-241c2906-823c-411d-ab9d-d2f25b2fe52e.png">

**Comment by kjozwiak** [comment]
Verification **PASSED** on `PopOS 22.04 x64` using the following build(s):

```
Brave | 1.40.105 Chromium: 103.0.5060.53 (Official Build) (64-bit)
--- |---
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | Linux
```

**`Example (Light Theme)`** | **`Example (Dark Theme)`**
--------------------------------|--------------------------------
![image](https://user-images.githubusercontent.com/2602313/174522348-74ba9d6b-d41f-4393-88bd-ef528260b34f.png) | ![image](https://user-images.githubusercontent.com/2602313/174522561-ab047f50-c371-4e2b-be35-1b1cc3f2f3a6.png)
