### ISSUE TITLE
New tab `+` shows the different background color when mouse is not hovered

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#23423]
## Description 

New tab `+` shows the different background color when mouse is not hovered

## Steps to Reproduce

   1. NA
  

## Actual result:

![image](https://user-images.githubusercontent.com/38657976/173303862-b30358e5-dfd3-45e4-bbe0-a1c97cf39a71.png)

## Expected result:
![image](https://user-images.githubusercontent.com/38657976/173303794-47f277fb-4ad8-4939-9c95-19246d6996e5.png)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.41.58 Chromium: 103.0.5060.42 (Official Build) nightly (64-bit)
-- | --
Revision | de0d840bf9439c31bd86bf74f065c31fdf9b208d-refs/branch-heads/5060@{#667}
OS | Windows 10 Version 21H2 (Build 19044.1706)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome?NA 

## Miscellaneous Information:

cc: @brave/qa-team @simonhong @mkarolin @emerick

**Comment by emerick** [comment]
Seems related to this upstream change: https://source.chromium.org/chromium/chromium/src/+/0740de35621ac0d7f7ca592c965a394818f32693.

**Comment by GeetaSarvadnya** [comment]
The issue needs to be fixed for the `Search Tabs` background color also. Reproduced in `Linux - 1.40.103`

![image](https://user-images.githubusercontent.com/38657976/174281198-40fdbcde-3c7f-4e70-8301-7fa3bcef61b3.png)

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
```
- Verified the STR from the description

**_Light theme_**

`1.40.105` Before the fix | `1.40.107` After the fix
------ | -------
![image](https://user-images.githubusercontent.com/38657976/175511650-cfe24365-924a-4260-af03-66919d51501c.png) | 

**_Dark theme_**

`1.40.105` Before the fix | `1.40.107` After the fix
------ | -------
![image](https://user-images.githubusercontent.com/38657976/175511759-9e4beb79-cff4-4550-96be-5d1e05224720.png)

**_PT and TOR tabs_** 

`1.40.105` Before the fix | `1.40.107` After the fix
------ | -------
![image](https://user-images.githubusercontent.com/38657976/175512229-8b3f5136-f030-49a9-b4c6-7b6d9d8714e9.png)

**Comment by GeetaSarvadnya** [comment]
Verified the comments https://github.com/brave/brave-browser/issues/23423#issuecomment-1158737334 and ensured the `Search tabs` bg color issue is also fixed in Linux `1.40.107`
 
![image](https://user-images.githubusercontent.com/38657976/175530196-f28a6031-0686-4fe3-8793-0c29438a41cb.png)
