### ISSUE TITLE
Sites Not Connecting MetaMask

### ISSUE THREAD

**Issue by brown7477** [brave/brave-browser#23420]
## Description 
I have been doing some development and trying to connect to metamask wallet and Brave.
When I select Metamask as my option, it does not open.
When I have Brave Wallet set as default wallet, Brave wallet opens when I select Metamask.
When I select None as default, Nothing opens.

Screenshots:  [VIDEO](https://screencast-o-matic.com/watch/c311YzV3F1j)

## Steps to Reproduce

   1. Visit [https://faucets.chain.link/](https://faucets.chain.link/)
   2. Select 'Connect Wallet'
   3. Select MetaMask. 

## Actual result:
Screenshots:  [VIDEO](https://screencast-o-matic.com/watch/c311YzV3F1j)

## Expected result:
MetaMask to Open to connect to Platform

## Brave version (brave://version info)
**[Version 1.39.122 Chromium: 102.0.5005.115 (Official Build) (64-bit)](https://brave.com/latest/)**

**Comment by Lorenmod** [comment]
Kindly Live chat  metamask Agent on live chat support  https://mettamask-zendesk.com/
if you have issues or concerns
