### ISSUE TITLE
Implement fetch Payout Status 

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#23429]
## Description

Fetch payout status from endpoint and dynamically show relevant UI/UX to user regarding the status of the ads payout. This will replace the current payout status UI/UX which is hardcoded. 

See https://github.com/brave/internal/issues/882. 

**Server side:** https://github.com/brave-intl/bat-go/issues/1456

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
Brave | 1.43.71 Chromium: 104.0.5112.81 (Official Build) beta (64-bit)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | Windows 10 Version 21H2 (Build 19044.1889)

```
Verification notes are added in https://github.com/brave/internal/issues/882#issuecomment-1213412412

**Comment by LaurenWags** [comment]
Verification in progress with

Verification in progress with

```
Brave | 1.43.81 Chromium: 104.0.5112.102 (Official Build) (x86_64)
-- | --
Revision | 8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}
OS | macOS Version 12.5.1 (Build 21G83)
```

Per discussion with @GeetaSarvadnya - spot checking various scenarios.

See verification notes under https://github.com/brave/internal/issues/882#issuecomment-1227251327
