### ISSUE TITLE
Implement text embedding processing for ad matching MVP

### ISSUE THREAD

**Issue by moritzhaller** [brave/brave-browser#23424]

**Comment by ptjames** [comment]
https://github.com/brave/brave-core/pull/14269

**Comment by kjozwiak** [comment]
Closing as this was uplifted into `1.43.x` ~11 days ago via https://github.com/brave/brave-core/pull/14694#event-7216266551.

**Comment by kjozwiak** [comment]
Removing from the `1.43.x` milestone as https://github.com/brave/brave-core/pull/14393 is still opened and hasn't been merged into `master` yet. We're releasing `1.43.x` this week so there's no way this is making it.  We only move issues into milestones once they've actually landed in the target milestone and https://github.com/brave/brave-core/pull/14393 is still opened.

**Comment by LaurenWags** [comment]
@ptjames Adding `QA/Blocked` label as test plan mentions building locally which QA does not do, please provide additional test plan, can work with @btlechowski on this as needed.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.45.75 Chromium: 106.0.5249.65 (Official Build) beta (64-bit)
-- | --
Revision | 3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/14393

Verified text embedding is working:
```
[5051:5051:1009/140553.354039:VERBOSE3:text_embedding_processor.cc(72)] Successfully logged text embedding HTML event
[5051:5051:1009/140553.373045:VERBOSE3:text_embedding_processor.cc(80)] Successfully purged stale text embedding HTML events
```

Verified embeddings being stored in table `text_embedding_html_event`
![image](https://user-images.githubusercontent.com/34715963/194756193-7ea240f8-691e-4807-86f3-e7f04f444bd0.png)

Verified embeddings are not duplicated for the same id:
Before page reload:
![image](https://user-images.githubusercontent.com/34715963/194756295-0792ea48-f188-4b07-9610-a5622689d023.png)
After page reload:
![image](https://user-images.githubusercontent.com/34715963/194756349-c4ef97c1-38a7-46b0-b769-5597ba7c518a.png)

Verified when embedding is not possible, proper message is shown:
```
[6876:6876:1009/144455.972530:VERBOSE1:text_embedding_processor.cc(53)] No text available for embedding

```

Logged https://github.com/brave/brave-browser/issues/25878 for failed embedding on wikipedia pages
