### ISSUE TITLE
Don't hide full asset while loading balances

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#23436]
## Description 
Currently we have a `Skeleton` loading view for `Assets` that is continuously displayed until the balance is returned.
We should at least show the asset while the balance is still being returned so it's not confusing of what asset is still loading.

![Screen Shot 2022-06-13 at 9 56 30 PM](https://user-images.githubusercontent.com/40611140/173484372-679833ae-0a0e-4af5-a7d3-9092da46c75a.png)

**Comment by Uni-verse** [comment]
Verification PASSED using

```
Brave	1.41.91 Chromium: 103.0.5060.114 (Official Build) beta (64-bit) 
Revision	a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS	Windows 11 Version 21H2 (Build 22000.318)
```
Acceptance Criteria:

`PASS` - Show the asset while the balance is still being returned so it's not confusing of what asset is still loading. 
`PASS` - `Skeleton animation` should only impact the balance in `Portfolio` and `Accounts` Pages

Accounts Page | Portfolio (Solana) | Portfolio (BSC)
-|-|-
![Screen Shot 2022-07-08 at 1 00 53 PM](https://user-images.githubusercontent.com/17885425/178063012-a19bd128-71bc-499a-9223-b875735a76b5.png) | ![Screen Shot 2022-07-08 at 12 59 28 PM](https://user-images.githubusercontent.com/17885425/178063035-59ff5f43-dc77-4d02-a6bb-52227d1b981f.png) | ![Screen Shot 2022-07-08 at 12 53 23 PM](https://user-images.githubusercontent.com/17885425/178063062-37fb6a95-5e43-480d-ab5f-5b13ef92050f.png)

**Comment by Uni-verse** [comment]
Verification PASSED using 

```
Brave	1.41.91 Chromium: 103.0.5060.114 (Official Build) beta (64-bit) 
Revision	a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS	Linux
```

Acceptance Criteria:

`PASS` - Show the asset while the balance is still being returned so it's not confusing of what asset is still loading.
`PASS` - `Skeleton animation` should only impact the balance in `Portfolio` and `Accounts` Pages
