### ISSUE TITLE
Hide Speedup Cancel and Retry for Filecoin Transactions

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#23431]
## Description 
We need to hide `Speedup`, `Cancel` and `Retry` transaction actions for `Filecoin`

![Screen Shot 2022-06-13 at 4 32 30 PM](https://user-images.githubusercontent.com/40611140/173453620-266dee32-c2b4-4f44-b539-bb82a8886b67.png)

![Screen Shot 2022-06-13 at 4 52 34 PM](https://user-images.githubusercontent.com/40611140/173453646-43bd2566-e5bd-4b06-9992-aa03fc7cf0b7.png)

**Comment by kjozwiak** [comment]
The above will require `1.40.100` or higher for `1.40.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.40.105 Chromium: 103.0.5060.53 (Official Build) (64-bit) 
-- | --
Revision | `a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}`
OS | Windows 11 Version 21H2 (Build 22000.739)

- Verified steps from PR
- Verified Hide/Speedup/Cancel/Retry is not shown for Filecoin transactions

https://user-images.githubusercontent.com/17010094/174540536-21a40cd3-b0b1-4586-a57b-c64bfc4926b7.mp4
