### ISSUE TITLE
Display sendOptions in UI if exists for pending transactions

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#23434]
In https://github.com/brave/brave-core/pull/13764, we added an optional `send_options` in `SolanaTxData`, we should display this in the details of pending transactions approval screen to users.
https://github.com/brave/brave-core/pull/13764/files#diff-9f2cf11d57c8efee5461b92cdb38fa327b70c25fd8d009f7692049e8e88944a8R1186

**Comment by kjozwiak** [comment]
The above will require `1.41.80` or higher for `1.41.x` verification 👍

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.41.86 Chromium: 103.0.5060.66 (Official Build) beta (64-bit) </th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>20b1569438a85e631d15e83eb355e3e326e5da6f-refs/branch-heads/5060@{#1066}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.708)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/13666>brave/brave-core#13666</a></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/176920374-7980d2f9-8236-4bb8-a425-8dda07e48a98.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/176925846-67c75ed4-be84-4bfa-a61d-d032a4d0e9d9.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/176927201-be50fafb-45eb-4758-8fdc-efc16c6d0bbc.mov>
      </td>
   </tr>
</table>
