### ISSUE TITLE
Fix Bad Set State Call in Buy Tab

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#23437]
## Description 
Seeing a `Bad Set State` warning in the `Buy Tab` that needs to be addressed.

https://user-images.githubusercontent.com/40611140/173484878-3a79c9dd-f22b-44d4-915d-d378e3cd9793.mov

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.42.67 Chromium: 103.0.5060.114 (Official Build) beta (64-bit) </th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.708)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/13883>brave/brave-core#13883</a></li>
         <li>Verified no errors when unlocking wallet with Solana Devnet set as active network</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/179215413-63089fc0-09b2-46e7-bc8d-943d13de47e2.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/179215775-03b83d84-ab72-4fe4-8bfe-8b68787d1a16.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/179222140-8608fb5f-2e63-4a7f-b136-af9b033136c5.mov>
      </td>
   </tr>
</table>
