### ISSUE TITLE
Errors in brave://settings console

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#23439]
After https://github.com/brave/brave-core/pull/12827/files#diff-2640d3fc96dc2bbbe439e1a9d39c43b0389123aad49b98de67b0f80e6d566c1c
brave://settings console spams with error ```method `controlEqual` not defined```
![image](https://user-images.githubusercontent.com/168356/173492074-77d41234-efc7-48f6-8d2a-170698d190a1.png)

**Comment by supermassive** [comment]
cc @nullhook

**Comment by nullhook** [comment]
Fixed here: https://github.com/brave/brave-core/pull/13761
