### ISSUE TITLE
Trezor transaction fails

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23448]
## Description 

Trezor transaction fails
## Steps to Reproduce

   1. Connect Trezor and import accounts
   2. Initiate a send ETH transaction from Trezor to another account
   3. Once session authentication is done, automatically rejects the transaction

## Actual result:

https://user-images.githubusercontent.com/17010094/173557402-1521954d-fa37-4579-b70a-97dcd61d9e4e.mp4

## Expected result:
Should show the transaction approval on the device so user can approve/reject it via the device

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.41.61 Chromium: 103.0.5060.42 (Official Build) nightly (64-bit) 
-- | --
Revision | `de0d840bf9439c31bd86bf74f065c31fdf9b208d-refs/branch-heads/5060@{#667}`
OS | Windows 11 Version 21H2 (Build 22000.708)

## Version/Channel Information:

- Can you reproduce this issue with the current release?  NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/crypto-wallets

**Comment by onyb** [comment]
Could not reproduce on Trezor Model T (firmware 2.5.1). Tested with Nightly version on Ethereum mainnet network.

@srirambv Can you please reproduce the issue again using brave://wallet-panel.top-chrome and looking at the console logs?

**Comment by srirambv** [comment]
@onyb  am just seeing `session not found` 


https://user-images.githubusercontent.com/17010094/173755790-1c1f6971-ba9c-4673-9267-6a481e28e3e9.mp4

**Comment by srirambv** [comment]
Update: Rechecked the issue on Mainnet and the transactions went through without issues.

**Comment by bbondy** [comment]
Should this be closed @srirambv ?

**Comment by srirambv** [comment]
Just rechecked the issue. Seems to work on Mainnet but its still an issue on Testnet. I am ok to close the issue but might be good to get it fixed for testnet at least

**Comment by nvonpentz** [comment]
@srirambv Confirmed the issue is just on mainnet. It seems testnets are off by default for Trezor. To enable them, you must go to https://suite.trezor.io/web/settings/device > Safety Checks > Edit, then select 'Prompt'.  After making that change, I was able to send transactions on Sepolia.

**Comment by srirambv** [comment]
Able to send on testnet after updating the Safety check permission. Closing the issue as invalid. Thanks for the steps @nvonpentz
