### ISSUE TITLE
[speedreader] Allow to reload an original distilled page 

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#23445]
Inject a link to the page that would reload the original, non-distilled page. This should not affect speedreader feature status or anything, just a one-time action. Negotiate a placement and style of the link with the design-team

**Comment by boocmp** [comment]
@rebron 
![image](https://user-images.githubusercontent.com/73575789/174090769-f01a5bba-e6c7-4bd9-80f4-06abc9273fc6.png)
Is it OK?

**Comment by stephendonner** [comment]
@boocmp @iefremov mind dropping in a testplan for QA, here, when you get a chance?  Thanks!  Adding `QA/Test-Plan-Required` and `QA/Blocked` just until we've got the above.

**Comment by boocmp** [comment]
> Member

Test plan added in https://github.com/brave/brave-core/pull/13814.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.42.62 Chromium: 103.0.5060.114 (Official Build) beta (x86_64)
-- | --
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | macOS Version 13.0 (Build 22A5295i)

### Steps:
1. installed `1.42.62`
2. launched Brave
3. loaded `https://www.aol.com/news/officer-once-beaten-colleagues-lead-150022856-204729746.html`
4. clicked on the `Turn on reader mode` icon in the URL bar
5. confirmed article rendered in Speedreader mode
6. confirmed `Show original page` link
7. clicked on the `Show original page` link
8. confirmed the page reloaded and rendered in "normal" mode
9. clicked on the `Speedreader` button in the URL bar
10. confirmed no bubble

step 3 | step 5 | step 8 
---------|----------|---------
<img width="1009" alt="Screenshot 2022-07-13 at 3 02 01 PM" src="https://user-images.githubusercontent.com/387249/178844942-27107f0f-59cb-4a5b-96c7-910c2a812891.png"> | <img width="1009" alt="Screenshot 2022-07-13 at 3 01 55 PM" src="https://user-images.githubusercontent.com/387249/178844998-168b57f2-9808-4975-9d2f-4e3ad0cc18d4.png"> | <img width="1117" alt="Screenshot 2022-07-13 at 3 08 13 PM" src="https://user-images.githubusercontent.com/387249/178845266-289401de-1f8b-40f5-99d6-0f47d8e380c3.png">
