### ISSUE TITLE
Brave is crashing when doing a hard refresh or selecting a new tor connection for this site in the TOR window

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#23442]
## Description 

The issue is reported by @MadhaviSeelam 

Brave is crashing when doing a hard refresh or selecting a new tor connection for this site in the TOR window
## Steps to Reproduce

   1. Clean profile 1.41.59
   2. Open a TOR window
   3. Open `check.torproject.org`
   4. Confirm the TOR network is connected and `check.torproject.org` is opened
   5. Do a hard refresh by clicking on Ctrl+Shift+R or select the `New Tor connection for this site` in the hamburger menu
   6. Brave crashes

## Actual result:

Brave crashes

```
Jun 14 12:43:30.000 [notice] Owning controller connection has closed -- exiting now.
```
## Expected result:
Should not crash

## Reproduces how often: 

100%
## Brave version (brave://version info)

Brave | 1.41.59 Chromium: 103.0.5060.42 (Official Build) nightly (64-bit)
-- | --
Revision | de0d840bf9439c31bd86bf74f065c31fdf9b208d-refs/branch-heads/5060@{#667}
OS | Windows 10 Version 21H2 (Build 19044.1706)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @rebron @mkarolin @simonhong @emerick

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.41.63 Chromium: 103.0.5060.42 (Official Build) nightly (x86_64)
-- | --
Revision | de0d840bf9439c31bd86bf74f065c31fdf9b208d-refs/branch-heads/5060@{#667}
OS | macOS Version 12.5 (Build 21G5037d)

Used the original steps to reproduce.

#### Confirmed no crashes when obtaining a newly requested Tor IP address

original IP | `New Tor connection for this site` | new IP | `brave://tor-internals` | `brave://tor-internals`
---|---|----|---|---
<img width="1312" alt="Screen Shot 2022-06-14 at 5 41 04 PM" src="https://user-images.githubusercontent.com/387249/173712506-a9297330-c592-4a9a-b100-0fc2747e9dd1.png"> | <img width="1312" alt="Screen Shot 2022-06-14 at 5 41 08 PM" src="https://user-images.githubusercontent.com/387249/173712509-f65f8c2b-e516-430d-a526-d86815a384fc.png"> | <img width="1312" alt="Screen Shot 2022-06-14 at 5 41 14 PM" src="https://user-images.githubusercontent.com/387249/173712512-1940859b-fc58-42bb-87ef-850a01a67910.png"> | <img width="1312" alt="Screen Shot 2022-06-14 at 5 45 03 PM" src="https://user-images.githubusercontent.com/387249/173712933-00e90930-2fa1-44a7-966a-bc409917c91f.png"> | <img width="1312" alt="Screen Shot 2022-06-14 at 5 45 07 PM" src="https://user-images.githubusercontent.com/387249/173712942-a0057304-0ff2-4eb8-91eb-aa08783e7500.png">


```
Jun 14 17:11:02.781 [notice] Tor 0.4.6.10 running on Darwin with Libevent 2.1.12-stable, OpenSSL 1.1.1n, Zlib 1.2.12, Liblzma N/A, Libzstd N/A and Unknown N/A as libc.
Jun 14 17:11:02.781 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://support.torproject.org/faq/staying-anonymous/
Jun 14 17:11:02.781 [notice] Read configuration file "/Users/sdonner/Library/Application Support/BraveSoftware/Brave-Browser-Nightly/cldoidikboihgcjfkhdeidbpclkineef/1.0.25/tor-torrc".
Jun 14 17:11:02.781 [notice] Read configuration file "/Users/sdonner/Library/Application Support/BraveSoftware/Brave-Browser-Nightly/cldoidikboihgcjfkhdeidbpclkineef/1.0.25/tor-torrc".
Jun 14 17:11:02.783 [notice] Opening Socks listener on 127.0.0.1:0
Jun 14 17:11:02.783 [notice] Socks listener listening on port 62851.
Jun 14 17:11:02.783 [notice] Opened Socks listener connection (ready) on 127.0.0.1:62851
Jun 14 17:11:02.783 [notice] Opening Control listener on 127.0.0.1:0
Jun 14 17:11:02.783 [notice] Control listener listening on port 62852.
Jun 14 17:11:02.783 [notice] Opened Control listener connection (ready) on 127.0.0.1:62852
Jun 14 17:11:02.000 [notice] Bootstrapped 0% (starting): Starting
Jun 14 17:11:02.000 [notice] Starting with guard context "default"
Jun 14 17:11:02.000 [notice] New control connection opened from 127.0.0.1.
Jun 14 17:11:02.000 [notice] Bootstrapped 5% (conn): Connecting to a relay
Jun 14 17:11:02.000 [notice] Bootstrapped 10% (conn_done): Connected to a relay
Jun 14 17:11:03.000 [notice] Bootstrapped 14% (handshake): Handshaking with a relay
Jun 14 17:11:03.000 [notice] Bootstrapped 15% (handshake_done): Handshake with a relay done
Jun 14 17:11:03.000 [notice] Bootstrapped 20% (onehop_create): Establishing an encrypted directory connection
Jun 14 17:11:03.000 [notice] Bootstrapped 25% (requesting_status): Asking for networkstatus consensus
Jun 14 17:11:03.000 [notice] Bootstrapped 30% (loading_status): Loading networkstatus consensus
Jun 14 17:11:05.000 [notice] I learned some more directory information, but not enough to build a circuit: We have no usable consensus.
Jun 14 17:11:05.000 [notice] Bootstrapped 40% (loading_keys): Loading authority key certs
Jun 14 17:11:05.000 [notice] The current consensus has no exit nodes. Tor can only build internal paths, such as paths to onion services.
Jun 14 17:11:05.000 [notice] Bootstrapped 45% (requesting_descriptors): Asking for relay descriptors
Jun 14 17:11:05.000 [notice] I learned some more directory information, but not enough to build a circuit: We need more microdescriptors: we have 0/6854, and can only build 0% of likely paths. (We have 0% of guards bw, 0% of midpoint bw, and 0% of end bw (no exits in consensus, using mid) = 0% of path bw.)
Jun 14 17:11:06.000 [notice] Bootstrapped 50% (loading_descriptors): Loading relay descriptors
Jun 14 17:11:06.000 [notice] The current consensus contains exit nodes. Tor can build exit and internal paths.
Jun 14 17:11:07.000 [notice] Bootstrapped 55% (loading_descriptors): Loading relay descriptors
Jun 14 17:11:08.000 [notice] Bootstrapped 61% (loading_descriptors): Loading relay descriptors
Jun 14 17:11:08.000 [notice] Bootstrapped 68% (loading_descriptors): Loading relay descriptors
Jun 14 17:11:08.000 [notice] Bootstrapped 75% (enough_dirinfo): Loaded enough directory info to build circuits
Jun 14 17:11:08.000 [notice] Bootstrapped 80% (ap_conn): Connecting to a relay to build circuits
Jun 14 17:11:08.000 [notice] Bootstrapped 85% (ap_conn_done): Connected to a relay to build circuits
Jun 14 17:11:09.000 [notice] Bootstrapped 89% (ap_handshake): Finishing handshake with a relay to build circuits
Jun 14 17:11:09.000 [notice] Bootstrapped 90% (ap_handshake_done): Handshake finished with a relay to build circuits
Jun 14 17:11:09.000 [notice] Bootstrapped 95% (circuit_create): Establishing a Tor circuit
Jun 14 17:11:10.000 [notice] Bootstrapped 100% (done): Done
```

**Comment by stephendonner** [comment]
Marking `QA/Test-All-Platforms` because this hard crash is 100% reproducible and is at least on macOS and Windows.

**Comment by kjozwiak** [comment]
This is being uplifted as part of https://github.com/brave/brave-core/pull/13755 and can be verified using `1.40.101` or higher 👍 We should probably re-check to make sure that the above was actually fixed with `C103` now that we've merged it into `1.40.x`.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.40.101 Chromium: 103.0.5060.42 (Official Build) (64-bit)
-- | --
Revision | de0d840bf9439c31bd86bf74f065c31fdf9b208d-refs/branch-heads/5060@{#667}
OS | Windows 11 Version 21H2 (Build 22000.739)
```
Confirmed no crashes when obtaining a newly requested Tor IP address for `Do hard refresh by clicking on Ctrl+Shift+R` or `select the New Tor connection for this site in the hamburger menu`

```
Jun 16 08:46:24.350 [notice] Tor 0.4.6.10 running on Windows 8 [or later] with Libevent 2.1.12-stable, OpenSSL 1.1.1n, Zlib 1.2.12, Liblzma N/A, Libzstd N/A and Unknown N/A as libc.
Jun 16 08:46:24.350 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://support.torproject.org/faq/staying-anonymous/
Jun 16 08:46:24.350 [notice] Read configuration file "C:\Users\mseel\AppData\Local\BraveSoftware\Brave-Browser\User Data\cpoalefficncklhjfpglfiplenlpccdb\1.0.25\tor-torrc".
Jun 16 08:46:24.350 [notice] Read configuration file "C:\Users\mseel\AppData\Local\BraveSoftware\Brave-Browser\User Data\cpoalefficncklhjfpglfiplenlpccdb\1.0.25\tor-torrc".
Jun 16 08:46:24.350 [warn] Path for GeoIPFile (<default>) is relative and will resolve to C:\Program Files\BraveSoftware\Brave-Browser\Application\103.1.40.101\<default>. Is this what you wanted?
Jun 16 08:46:24.350 [warn] Path for GeoIPv6File (<default>) is relative and will resolve to C:\Program Files\BraveSoftware\Brave-Browser\Application\103.1.40.101\<default>. Is this what you wanted?
Jun 16 08:46:24.366 [notice] Opening Socks listener on 127.0.0.1:0
Jun 16 08:46:24.366 [notice] Socks listener listening on port 52857.
Jun 16 08:46:24.366 [notice] Opened Socks listener connection (ready) on 127.0.0.1:52857
Jun 16 08:46:24.366 [notice] Opening Control listener on 127.0.0.1:0
Jun 16 08:46:24.366 [notice] Control listener listening on port 52858.
Jun 16 08:46:24.366 [notice] Opened Control listener connection (ready) on 127.0.0.1:52858
[7144:26204:0616/084624.366:INFO:tor_file_watcher.cc(183)] tor: failed to open control auth cookie
[7144:26204:0616/084624.369:INFO:tor_file_watcher.cc(183)] tor: failed to open control auth cookie
[7144:26204:0616/084624.372:INFO:tor_file_watcher.cc(183)] tor: failed to open control auth cookie
[7144:26204:0616/084624.372:INFO:tor_file_watcher.cc(183)] tor: failed to open control auth cookie
Jun 16 08:46:24.000 [notice] Bootstrapped 0% (starting): Starting
Jun 16 08:46:24.000 [notice] Starting with guard context "default"
Jun 16 08:46:24.000 [notice] New control connection opened from 127.0.0.1.
Jun 16 08:46:24.000 [warn] Path for GeoIPFile (<default>) is relative and will resolve to C:\Program Files\BraveSoftware\Brave-Browser\Application\103.1.40.101\<default>. Is this what you wanted?
Jun 16 08:46:24.000 [warn] Path for GeoIPv6File (<default>) is relative and will resolve to C:\Program Files\BraveSoftware\Brave-Browser\Application\103.1.40.101\<default>. Is this what you wanted?
Jun 16 08:46:24.000 [notice] Bootstrapped 5% (conn): Connecting to a relay
Jun 16 08:46:24.000 [notice] Bootstrapped 10% (conn_done): Connected to a relay
Jun 16 08:46:24.000 [notice] Bootstrapped 14% (handshake): Handshaking with a relay
Jun 16 08:46:25.000 [notice] Bootstrapped 15% (handshake_done): Handshake with a relay done
Jun 16 08:46:25.000 [notice] Bootstrapped 20% (onehop_create): Establishing an encrypted directory connection
Jun 16 08:46:25.000 [notice] Bootstrapped 25% (requesting_status): Asking for networkstatus consensus
Jun 16 08:46:25.000 [notice] Bootstrapped 30% (loading_status): Loading networkstatus consensus
Jun 16 08:46:29.000 [notice] I learned some more directory information, but not enough to build a circuit: We have no usable consensus.
Jun 16 08:46:29.000 [notice] Bootstrapped 40% (loading_keys): Loading authority key certs
Jun 16 08:46:30.000 [notice] The current consensus has no exit nodes. Tor can only build internal paths, such as paths to onion services.
Jun 16 08:46:30.000 [notice] Bootstrapped 45% (requesting_descriptors): Asking for relay descriptors
Jun 16 08:46:30.000 [notice] I learned some more directory information, but not enough to build a circuit: We need more microdescriptors: we have 0/6891, and can only build 0% of likely paths. (We have 0% of guards bw, 0% of midpoint bw, and 0% of end bw (no exits in consensus, using mid) = 0% of path bw.)
Jun 16 08:46:30.000 [notice] Bootstrapped 50% (loading_descriptors): Loading relay descriptors
Jun 16 08:46:31.000 [notice] The current consensus contains exit nodes. Tor can build exit and internal paths.
Jun 16 08:46:33.000 [notice] Bootstrapped 57% (loading_descriptors): Loading relay descriptors
Jun 16 08:46:33.000 [notice] Bootstrapped 64% (loading_descriptors): Loading relay descriptors
Jun 16 08:46:33.000 [notice] Bootstrapped 69% (loading_descriptors): Loading relay descriptors
Jun 16 08:46:33.000 [notice] Bootstrapped 75% (enough_dirinfo): Loaded enough directory info to build circuits
Jun 16 08:46:33.000 [notice] Bootstrapped 80% (ap_conn): Connecting to a relay to build circuits
Jun 16 08:46:33.000 [notice] Bootstrapped 85% (ap_conn_done): Connected to a relay to build circuits
Jun 16 08:46:33.000 [notice] Bootstrapped 89% (ap_handshake): Finishing handshake with a relay to build circuits
Jun 16 08:46:33.000 [notice] Bootstrapped 90% (ap_handshake_done): Handshake finished with a relay to build circuits
Jun 16 08:46:33.000 [notice] Bootstrapped 95% (circuit_create): Establishing a Tor circuit
Jun 16 08:46:34.000 [notice] Bootstrapped 100% (done): Done
```

**Comment by stephendonner** [comment]
Verified `PASSED` using 

Brave | 1.40.101 Chromium: 103.0.5060.42 (Official Build) (x86_64)
-- | --
Revision | de0d840bf9439c31bd86bf74f065c31fdf9b208d-refs/branch-heads/5060@{#667}
OS | macOS Version 11.6.7 (Build 20G630)

`
Jun 16 10:57:55.922 [notice] Tor 0.4.6.10 running on Darwin with Libevent 2.1.12-stable, OpenSSL 1.1.1n, Zlib 1.2.12, Liblzma N/A, Libzstd N/A and Unknown N/A as libc.
Jun 16 10:57:55.922 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://support.torproject.org/faq/staying-anonymous/
Jun 16 10:57:55.922 [notice] Read configuration file "/Users/stephendonner/Library/Application Support/BraveSoftware/Brave-Browser/cldoidikboihgcjfkhdeidbpclkineef/1.0.43/tor-torrc".
Jun 16 10:57:55.922 [notice] Read configuration file "/Users/stephendonner/Library/Application Support/BraveSoftware/Brave-Browser/cldoidikboihgcjfkhdeidbpclkineef/1.0.43/tor-torrc".
Jun 16 10:57:55.925 [notice] Opening Socks listener on 127.0.0.1:0
Jun 16 10:57:55.925 [notice] Socks listener listening on port 58737.
Jun 16 10:57:55.925 [notice] Opened Socks listener connection (ready) on 127.0.0.1:58737
Jun 16 10:57:55.925 [notice] Opening Control listener on 127.0.0.1:0
Jun 16 10:57:55.925 [notice] Control listener listening on port 58738.
Jun 16 10:57:55.925 [notice] Opened Control listener connection (ready) on 127.0.0.1:58738
[2288:32771:0616/105755.925842:INFO:tor_file_watcher.cc(183)] tor: failed to open control auth cookie
[2288:32771:0616/105755.926053:INFO:tor_file_watcher.cc(183)] tor: failed to open control auth cookie
[2288:32771:0616/105755.928425:INFO:tor_file_watcher.cc(183)] tor: failed to open control auth cookie
[2288:32771:0616/105755.928643:INFO:tor_file_watcher.cc(183)] tor: failed to open control auth cookie
Jun 16 10:57:55.000 [notice] Bootstrapped 0% (starting): Starting
Jun 16 10:57:55.000 [notice] Starting with guard context "default"
Jun 16 10:57:55.000 [notice] New control connection opened from 127.0.0.1.
Jun 16 10:57:55.000 [notice] Bootstrapped 5% (conn): Connecting to a relay
Jun 16 10:57:56.000 [notice] Bootstrapped 10% (conn_done): Connected to a relay
Jun 16 10:57:56.000 [notice] Bootstrapped 14% (handshake): Handshaking with a relay
Jun 16 10:57:57.000 [notice] Bootstrapped 15% (handshake_done): Handshake with a relay done
Jun 16 10:57:57.000 [notice] Bootstrapped 20% (onehop_create): Establishing an encrypted directory connection
Jun 16 10:57:57.000 [notice] Bootstrapped 25% (requesting_status): Asking for networkstatus consensus
Jun 16 10:57:57.000 [notice] Bootstrapped 30% (loading_status): Loading networkstatus consensus
Jun 16 10:57:58.000 [notice] I learned some more directory information, but not enough to build a circuit: We have no usable consensus.
Jun 16 10:57:58.000 [notice] Bootstrapped 40% (loading_keys): Loading authority key certs
Jun 16 10:57:58.000 [notice] The current consensus has no exit nodes. Tor can only build internal paths, such as paths to onion services.
Jun 16 10:57:58.000 [notice] Bootstrapped 45% (requesting_descriptors): Asking for relay descriptors
Jun 16 10:57:58.000 [notice] I learned some more directory information, but not enough to build a circuit: We need more microdescriptors: we have 0/6895, and can only build 0% of likely paths. (We have 0% of guards bw, 0% of midpoint bw, and 0% of end bw (no exits in consensus, using mid) = 0% of path bw.)
Jun 16 10:57:58.000 [notice] Bootstrapped 50% (loading_descriptors): Loading relay descriptors
Jun 16 10:57:59.000 [notice] The current consensus contains exit nodes. Tor can build exit and internal paths.
Jun 16 10:57:59.000 [notice] Bootstrapped 55% (loading_descriptors): Loading relay descriptors
Jun 16 10:57:59.000 [notice] Bootstrapped 61% (loading_descriptors): Loading relay descriptors
[2288:259:0616/105800.421844:WARNING:CONSOLE(226)] "crbug/1173575, non-JS module files deprecated.", source: chrome://resources/js/load_time_data.js (226)
[2288:259:0616/105800.455263:ERROR:CONSOLE(0)] "Unchecked runtime.lastError: Not available in Tor profile", source: chrome://newtab/ (0)
[2288:259:0616/105800.455325:ERROR:CONSOLE(0)] "Unchecked runtime.lastError: Not available in Tor/incognito/guest profile", source: chrome://newtab/ (0)
[2288:259:0616/105800.455530:ERROR:CONSOLE(0)] "Unchecked runtime.lastError: Not available in Tor/incognito/guest profile", source: chrome://newtab/ (0)
[2288:259:0616/105800.466923:ERROR:CONSOLE(0)] "Unchecked runtime.lastError: Ads service is not initialized", source: chrome://newtab/ (0)
[2288:259:0616/105800.467833:ERROR:CONSOLE(0)] "Unchecked runtime.lastError: Ads service is not initialized", source: chrome://newtab/ (0)
Jun 16 10:58:01.000 [notice] Bootstrapped 69% (loading_descriptors): Loading relay descriptors
Jun 16 10:58:01.000 [notice] Bootstrapped 75% (enough_dirinfo): Loaded enough directory info to build circuits
Jun 16 10:58:02.000 [notice] Bootstrapped 80% (ap_conn): Connecting to a relay to build circuits
Jun 16 10:58:02.000 [notice] Bootstrapped 85% (ap_conn_done): Connected to a relay to build circuits
Jun 16 10:58:02.000 [notice] Bootstrapped 89% (ap_handshake): Finishing handshake with a relay to build circuits
Jun 16 10:58:02.000 [notice] Bootstrapped 90% (ap_handshake_done): Handshake finished with a relay to build circuits
Jun 16 10:58:02.000 [notice] Bootstrapped 95% (circuit_create): Establishing a Tor circuit
Jun 16 10:58:03.000 [notice] Bootstrapped 100% (done): Done
`

**Comment by kjozwiak** [comment]
Verification **PASSED** on `PopOS 22.04 x64` using the following build(s): 

```
Brave | 1.40.105 Chromium: 103.0.5060.53 (Official Build) (64-bit)
--- | ---
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | Linux
```

Went through the STR/Cases outlined via https://github.com/brave/brave-browser/issues/23442#issue-1270362571 and ensured that `Tor` doesn't crash when creating a new `Tor` connection.

**`Example`** | **`Example`** | **`Example`**
---------------|----------------|----------------
![image](https://user-images.githubusercontent.com/2602313/174523125-94e898ff-96f6-4375-94f1-5828386183df.png) | ![image](https://user-images.githubusercontent.com/2602313/174523162-7c703b51-b1fd-42f7-aa25-5554b9cfbd55.png) | ![image](https://user-images.githubusercontent.com/2602313/174523367-23161ee4-5a07-4ede-a8ba-4f29c04f7c2c.png)

#### `Initially launching Tor`

```
Jun 19 23:59:40.401 [notice] Opening Socks listener on 127.0.0.1:0
Jun 19 23:59:40.401 [notice] Socks listener listening on port 36203.
Jun 19 23:59:40.401 [notice] Opened Socks listener connection (ready) on 127.0.0.1:36203
Jun 19 23:59:40.401 [notice] Opening Control listener on 127.0.0.1:0
Jun 19 23:59:40.401 [notice] Control listener listening on port 43357.
Jun 19 23:59:40.401 [notice] Opened Control listener connection (ready) on 127.0.0.1:43357
Jun 19 23:59:40.000 [notice] Bootstrapped 0% (starting): Starting
Jun 19 23:59:40.000 [notice] Starting with guard context "default"
Jun 19 23:59:40.000 [notice] Bootstrapped 5% (conn): Connecting to a relay
Jun 19 23:59:40.000 [notice] New control connection opened from 127.0.0.1.
Jun 19 23:59:40.000 [notice] Bootstrapped 10% (conn_done): Connected to a relay
Jun 19 23:59:40.000 [notice] Bootstrapped 14% (handshake): Handshaking with a relay
Jun 19 23:59:41.000 [notice] Bootstrapped 15% (handshake_done): Handshake with a relay done
Jun 19 23:59:41.000 [notice] Bootstrapped 45% (requesting_descriptors): Asking for relay descriptors
Jun 19 23:59:42.000 [notice] Bootstrapped 63% (loading_descriptors): Loading relay descriptors
Jun 19 23:59:44.000 [notice] Bootstrapped 68% (loading_descriptors): Loading relay descriptors
Jun 19 23:59:45.000 [notice] Bootstrapped 75% (enough_dirinfo): Loaded enough directory info to build circuits
Jun 19 23:59:46.000 [notice] Bootstrapped 90% (ap_handshake_done): Handshake finished with a relay to build circuits
Jun 19 23:59:46.000 [notice] Bootstrapped 95% (circuit_create): Establishing a Tor circuit
Jun 19 23:59:49.000 [notice] Bootstrapped 100% (done): Done
```

#### `Creating a new Tor connection`

```
Jun 20 00:01:00.792 [notice] Opening Socks listener on 127.0.0.1:0
Jun 20 00:01:00.792 [notice] Socks listener listening on port 42105.
Jun 20 00:01:00.792 [notice] Opened Socks listener connection (ready) on 127.0.0.1:42105
Jun 20 00:01:00.792 [notice] Opening Control listener on 127.0.0.1:0
Jun 20 00:01:00.792 [notice] Control listener listening on port 35261.
Jun 20 00:01:00.792 [notice] Opened Control listener connection (ready) on 127.0.0.1:35261
Jun 20 00:01:00.000 [notice] Bootstrapped 0% (starting): Starting
Jun 20 00:01:00.000 [notice] Starting with guard context "default"
Jun 20 00:01:00.000 [notice] New control connection opened from 127.0.0.1.
Jun 20 00:01:00.000 [notice] Bootstrapped 5% (conn): Connecting to a relay
Jun 20 00:01:01.000 [notice] Bootstrapped 10% (conn_done): Connected to a relay
Jun 20 00:01:01.000 [notice] Bootstrapped 14% (handshake): Handshaking with a relay
Jun 20 00:01:01.000 [notice] Bootstrapped 15% (handshake_done): Handshake with a relay done
Jun 20 00:01:01.000 [notice] Bootstrapped 75% (enough_dirinfo): Loaded enough directory info to build circuits
Jun 20 00:01:03.000 [notice] Bootstrapped 90% (ap_handshake_done): Handshake finished with a relay to build circuits
Jun 20 00:01:03.000 [notice] Bootstrapped 95% (circuit_create): Establishing a Tor circuit
Jun 20 00:01:06.000 [notice] Bootstrapped 100% (done): Done
```
