### ISSUE TITLE
Unable to perform Swap on CR 103

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23443]
## Description 

Unable to perform Swap on CR 103

## Steps to Reproduce

   1. Install CR 103 build 
   2. Initiate a swap transaction
   3. Confirm button doesn't enable

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/173531232-c862486c-722f-4995-b0c1-3a6e3bff3f61.png)

## Expected result:
Should enable Confirm button to submit a swap transaction

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.41.61 Chromium: 103.0.5060.42 (Official Build) nightly (64-bit) 
-- | --
Revision | `de0d840bf9439c31bd86bf74f065c31fdf9b208d-refs/branch-heads/5060@{#667}`
OS | Windows 11 Version 21H2 (Build 22000.708)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA 
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

Works fine on Send Transaction
![image](https://user-images.githubusercontent.com/17010094/173531779-1acdf69d-97f3-445a-a379-46d7717b6f6a.png)
cc: @brave/crypto-wallets @rebron @emerick @rebase

**Comment by srirambv** [comment]
This may not be a CR103 related issue as I can repro it on 1.40.96 build as well which is still on CR 102.

**Comment by kjozwiak** [comment]
The above will require `1.40.102` or higher for `1.40.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.40.105 Chromium: 103.0.5060.53 (Official Build) (64-bit) 
-- | --
Revision | `a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}`
OS | Windows 11 Version 21H2 (Build 22000.739)

- Verified steps from issue description
- Verified Confirm button enables to initiate swap
- Verified able to submit a Swap transaction successfully on Mainnet

https://user-images.githubusercontent.com/17010094/174541381-314ec1b5-fd81-4a77-969e-d30a1e229f31.mp4
