### ISSUE TITLE
[speedreader] Dark/Light theme support

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#23447]
Speedreader should automatically show a light or dark distilled page, according to the browser settings.
We need to negotiate the exact theme colors with the design team

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.44.75 Chromium: 105.0.5195.102 (Official Build) beta (x86_64)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | macOS Version 11.6.8 (Build 20G730)

### Steps:
1. installed `1.44.75`
2. launched Brave
3. deleted the `jicbkmdloagakknpihibphagfckhjdih` component directory
4. loaded `https://www.bbc.com/news/business-58559179`
5. clicked on the `Speedreader` icon
6. opened `Developer Tools` -> `Console` panel
7. entered `document.documentElement.setAttribute('data-theme', 'dark')` and pressed `return`
8. confirmed the `Light` theme changed to `Dark` and was applied in Speedreader mode to the article
9. entered `document.documentElement.setAttribute('data-theme', 'light')` and pressed `return`
10. confirmed the `Dark` theme changed to `Light` and was applied
11. entered `document.documentElement.setAttribute('data-theme', 'sepia')` and pressed `return`
12. confirmed the `Light` theme changed to `Sepia` and was applied
13. entered `document.documentElement.removeAttribute('data-theme')` and pressed `return`
14. confirmed the `Dark` mode returned

step 3 | step 4-5 | steps 7-8 | steps 9-10 | steps 11-12 | steps 13-14
-------|-------|--------|-----------|-----------|-------------
<img width="806" alt="Screen Shot 2022-09-06 at 9 09 41 AM" src="https://user-images.githubusercontent.com/387249/188688702-a52fc917-72c4-4326-b5fa-68c2273c67b8.png"> | <img width="1193" alt="Screen Shot 2022-09-06 at 9 34 07 AM" src="https://user-images.githubusercontent.com/387249/188688927-0b9fa00a-bc77-402e-bb9f-742a0a58219a.png"> | <img width="1193" alt="Screen Shot 2022-09-06 at 9 03 04 AM" src="https://user-images.githubusercontent.com/387249/188689009-364ac9dd-b7ac-4c43-884c-cf6f6a5df537.png"> | <img width="1193" alt="Screen Shot 2022-09-06 at 9 03 07 AM" src="https://user- images.githubusercontent.com/387249/188689109-60579d66-61d6-418f-ad94-72df17b04219.png"> | <img width="1193" alt="Screen Shot 2022-09-06 at 9 05 42 AM" src="https://user-images.githubusercontent.com/387249/188689158-7ca7f090-c810-4359-9a4a-d6dedd92a807.png"> | <img width="1193" alt="Screen Shot 2022-09-06 at 9 05 58 AM" src="https://user-images.githubusercontent.com/387249/188689293-2dba2db5-5108-4684-9671-27165fd3f48e.png">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.44.82 Chromium: 105.0.5195.102 (Official Build) beta (64-bit)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | Windows 11 Version 21H2 (Build 22000.856)
```

1. Installed 1..44.82
2. launched Brave
3. deleted the jicbkmdloagakknpihibphagfckhjdih component directory
4. confirmed brave://settings/appearance is `Dark`
5. loaded https://www.bbc.com/news/business-58559179
6. clicked on the Speedreader icon
7. opened Developer Tools -> Console panel
8. entered document.documentElement.setAttribute('data-theme', 'dark') and pressed return
9. confirmed the Light theme on the page changed to Dark and was applied in Speedreader mode to the article
10. entered document.documentElement.setAttribute('data-theme', 'light') and pressed return
11. confirmed the Dark theme changed to Light and was applied
12. entered document.documentElement.setAttribute('data-theme', 'sepia') and pressed return
13. confirmed the Light theme changed to Sepia and was applied
14. entered document.documentElement.removeAttribute('data-theme') and pressed return
15. confirmed the Dark mode returned

step 3|step 4|step5-6|step8-9|step10-11|step12-13|step 14-15
----|----|-----|-----|-----|----|----
<image width="950" alt="step3" src="https://user-images.githubusercontent.com/98358127/189721888-ac4d3e88-d51d-4dec-98fd-6df60ded30ec.png">|<image width="950" alt="step3" src="https://user-images.githubusercontent.com/98358127/189722257-7c69871f-ef41-425e-9bed-c14bab7c4436.png">|<image width="950" alt="step3" src="https://user-images.githubusercontent.com/98358127/189722479-0220a35c-aa73-4848-b202-7c888e214d42.png">|<image width="950" alt="step3" src="https://user-images.githubusercontent.com/98358127/189737988-6af6d4a7-fcc3-45d5-a6ff-db1dd8ca8a6a.png">|<image width="950" alt="step3" src="https://user-images.githubusercontent.com/98358127/189738036-90e145ab-af21-49db-a003-e6505fd029bf.png">|<image width="950" alt="step3" src="https://user-images.githubusercontent.com/98358127/189738072-bd2aaaa2-8ad1-40ad-a23d-1b2cb66ea88d.png">|<image width="950" alt="step3" src="https://user-images.githubusercontent.com/98358127/189738136-d0d361e2-b12d-4ee4-8727-c43a403a037d.png">

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.44.97 Chromium: 106.0.5249.55 (Official Build) (64-bit)
-- | --
Revision | 4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}
OS | Ubuntu 18.04 LTS

<details>

![image](https://user-images.githubusercontent.com/34715963/192325354-872ec054-25cb-4a45-810f-c572666ef482.png)
![image](https://user-images.githubusercontent.com/34715963/192325996-d99622b5-d505-4ac8-92f8-f07ae52f7560.png)
![image](https://user-images.githubusercontent.com/34715963/192329451-ab038d74-1c4c-419b-ae95-b3ed9693c71e.png)
![image](https://user-images.githubusercontent.com/34715963/192329543-a3753fbe-7840-40c7-9e1b-65539e2deb96.png)
![image](https://user-images.githubusercontent.com/34715963/192329807-ab268bee-36a1-4295-812f-b4ce5bbebec0.png)
![image](https://user-images.githubusercontent.com/34715963/192329908-65be80bf-a249-44ef-b014-1342563c5df1.png)

</details>
