### ISSUE TITLE
Able to submit multiple transactions when clicking on the confirm transaction button

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23451]
## Description 

Reported by @bbondy, while doing a FIL transaction clicked Confirm button twice and the send amount was double than what was intended to send 

## Steps to Reproduce

   1. Initiate a send transaction
   2. Double click on the confirm button
   3. Ensure twice the amount is sent to the receiving account

## Actual result:

Able to submit multiple transactions when clicking on the confirm transaction button

## Expected result:
Disable confirm button the moment first click is registered on it

## Reproduces how often: 

Somewhat Easy

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel @bbondy

**Comment by kjozwiak** [comment]
The above will require `1.40.102` or higher for `1.40.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.40.105 Chromium: 103.0.5060.53 (Official Build) (64-bit) 
-- | --
Revision | `a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}`
OS  | Windows 11 Version 21H2 (Build 22000.739)

- Verified steps from issue description
- Verified can't submit duplicate transactions by clicking on the confirm button twice in quick succession
- Verified both `Reject` and `Confirm` buttons are disabled when transaction is being submitted

https://user-images.githubusercontent.com/17010094/174544572-eebf72de-388a-4c64-b706-23600990a10c.mp4
