### ISSUE TITLE
[Android] Playlist on Android

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#23464]
**Spec:**
https://bravesoftware.slack.com/archives/C02SC5AKTAS/p1655258456342959?thread_ts=1655258381.968479&cid=C02SC5AKTAS

**Comment by timchilds** [comment]
Project currently with design team. Scheduling a review for next week.

**Comment by Uni-verse** [comment]
In progress on Samsung GS 21 5G 

```
Brave	1.52.2 Chromium: 112.0.5615.39 (Official Build) canary (64-bit) 
Revision	a0e7b9718a92bcd1cf33b7c95316caff3fc20714-refs/branch-heads/5615@{#753}
OS	Android 13; Build/TP1A.220624.014
```

**Comment by Sayum24** [comment]
hello, is it possible to save music from SoundCloud or any other streaming service except YouTube? 
Thanks for that feature btw.

**Comment by Sayum24** [comment]
> @Sayum24 we are adding other sites soon. We are updating scripts to add more options.

@deeppandya sounds good. Where should I report bugs for the playlist feature?

**Comment by deeppandya** [comment]
> 
> > @Sayum24 we are adding other sites soon. We are updating scripts to add more options.
> 
> @deeppandya sounds good. Where should I report bugs for the playlist feature?

You can use the public issues to report any bug.

**Comment by Thed13** [comment]
I hope to see this feature soon available on beta/stable builds. I used playlists a lot on iphone, so if it's on android then it would be great.

**Comment by kjozwiak** [comment]
See context via https://github.com/brave/brave-browser/issues/30071#issue-1690332016 re: why this was labelled as `QA/No` & `release-notes/exclude`.
