### ISSUE TITLE
Honey extension causing issues on web.whatsapp.com

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#23466]
## Description 
Honey extension is causing browser hangs in web.whatsapp.com, QR code fails to show (or takes much longer to show)

## Steps to Reproduce

   1.  Open a clean profile of Brave
   2. Install Honey https://chrome.google.com/webstore/detail/honey-automatic-coupons-c/bmnlcjabgnpnenekpadlanbbkooimhnj
   3. Click on extension icon to ensure its loaded
   4. Open `web.whatsapp.com` . (this should load the QR code)
   5. Now close  `web.whatsapp.com` Tab.
   6. Open a new tab for `web.whatsapp.com`, this will hang. QR code will either fail to load or take much much longer to load.

## Actual result:  (websocket timeouts/errors)
**Honey Enabled:**
![brave-nightly-honey-enab](https://user-images.githubusercontent.com/1659004/173706382-63e9884b-7c61-43b9-9213-d32e5c047d6b.png)
![brave-honey-errors](https://user-images.githubusercontent.com/1659004/173706391-e7a0c1d1-3c58-4641-a1f4-58e418e449b8.png)

## Expected result:
**Honey Disabled:**

![brave-nightly-honey-dis](https://user-images.githubusercontent.com/1659004/173706456-0ff9b7db-2c29-4e01-a22c-a462553720a1.png)

## Reproduces how often: 

Easily.

## Brave versions tested (clean profiles test between each run) 

Was reproducible in much older Brave builds, we've only had reports recently in the last few days (maybe weeks).

```
Version 1.41.59  BAD
Version 1.41.62  BAD
Nightly v1.40.4  BAD
Nightly v1.38.40 BAD
Nightly v1.37.60  BAD
Nightly v1.36.60  BAD
Nightly v1.34.38  BAD
Nightly v1.32.66  BAD
```

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  No
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:
Just installing the extension is enough to cause the hang ups, 

- "On click"  -> Still showed issues on whatsapp.
- "limiting the extension to certain domain" -> Still showed issues on whatsapp.

This is a new error given the amount of reports we're getting, I suspect its a recent update on the Honey Extension.  

user reports: https://github.com/brave/brave-browser/issues/23382

We've had an 500%+ increase in reports regarding web.whatsapp.com issues, started June the 9th.

**Comment by Gilgul46** [comment]
Well, I tried turning it off, but it didn't work. I thought maybe it was my other extensions but when I opened an incognito mode the same happens. After way too long the qr code appears but it doesn't let me connect! wtf it worked yesterday, what's different now?

**Comment by r3lai** [comment]
I saw this behaviour too. You might have to do a full cycle of:

1. Turn off the extension
2. Dump cookies
3. Close browser (and quit any processes)
4. Open browser and dump cookies again
5. Go to web.whatsapp.com

The QR should load very quickly if you do 1-5 every damn time. It's a pain, but it' worked 100% of the time for me.

**Comment by ryanbr** [comment]
I'm seeing more reliablity of the site, Unable to get QR code hang ups now. @r3lai @Gilgul46 

Did notice a recent issue on Firefox which was also report; https://old.reddit.com/r/firefox/comments/vg3886/whatsapp_web_not_working_on_firefox_developer/

Looking back on it, I don't think its the extension.  Is it working better?

**Comment by r3lai** [comment]
Just confirmed now, with honey turned off, Whatsapp web seeems to operate just fine. The opposite is true with honey turned on.

**Comment by ryanbr** [comment]
Closing, While some people had issues with Honey, I don't think its the issue. Since others see it without having the extension installed.
