### ISSUE TITLE
Add Wallet new user P3A metric

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#23463]
Add one new P3A question for wallet:

"As a first time user of Brave Wallet this week, did I return again to use it during the week?"
`Brave.Wallet.NewUserReturning`

0) I have never used Brave Wallet
1) I have used Brave Wallet, but I'm not a first time Brave Wallet user this week
2) I'm a first time Brave Wallet user this week but, no, I did not return the rest of the week
3) I'm a first time Brave Wallet user this week and, yes, I returned and used it again the following day
4) I'm a first time Brave Wallet user this week and, yes, I returned and used it again this week but not the following day

Will raise PR soon.

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```
Brave | 1.42.64 Chromium: 103.0.5060.114 (Official Build) beta (64-bit)
-- | --
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | Windows 10 Version 21H2 (Build 19044.1806)

```

**Comment by GeetaSarvadnya** [comment]
@DJAndries I am not getting the correct response for one case. Can you review the case below?

1. Clean profile 1.42.x
2. Create a wallet today (14th July)
3. Open the brave://local-state file and ensured that the metrics `Brave.Wallet.NewUserReturning` response value is `2`
4. Close the browser and set the system clock ahead by one day (15th July)
5. Relaunch the browser
6. Unlock the wallet
7. Reload the brave://local-state file 
8. The metrics response value is `4` instead of `3`

**Comment by GeetaSarvadnya** [comment]
@DJAndries I assume a week is considered from the day when wallet is created. Is my understanding correct?

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress on `Samsung Galaxy Tab A7 version 11` running `Bravemonoarm.apk_1.42.80`

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on `Samsung Galaxy version 11` running `Bravemonoarm.apk_1.42.80`

- Verified the test plan from https://github.com/brave/brave-core/pull/13787
- Encountered https://github.com/brave/brave-browser/issues/24058

<details>
<summary>Case 1: I have never used Brave Wallet = 0_PASSED</summary>

- Confirmed that `Brave.Wallet.NewUserReturning` metrics response value is `0` when brave wallet is not used



</details>

<details>
<summary>Case 2: I have used Brave Wallet, but I'm not a first-time Brave Wallet user this week = 1_PASSED</summary>

Case 1: 

1. Set the system date to 11th July (starting day of the week)
2. Clean profile 1.42.x
3. Create a wallet
4. Open the brave://local-state file and ensured that the metrics `Brave.Wallet.NewUserReturning` response value is `2`
5. Close the browser and set the system clock ahead by one week (18th July)
6. Relaunch the browser
7. Unlock the wallet
8. Reload the brave://local-state file 
9. The metrics response value is `1` as expected



Case 2:

1. Set the system date to 11th July (starting day of the week)
2. Clean profile 1.42.x
3. Create a wallet today
4. Open the brave://local-state file and ensured that the metrics `Brave.Wallet.NewUserReturning` response value is `2`
5. Close the browser and set the system clock ahead by one week (18th July)
6. Relaunch the browser
7. Unlock the wallet
8. Reload the brave://local-state file 
9. The metrics `Brave.Wallet.NewUserReturning` response value is `1` as expected
11. Close the browser and set the system clock ahead by one week (19th July/22 July/ 23 July/ 24 July / 26 July)
12. Relaunch the browser
13. Unlock the wallet
14. Reload the brave://local-state file 
15. The metrics `Brave.Wallet.NewUserReturning` response value is `1` as expected




</details>

<details>
<summary>Case 3: I'm a first-time Brave Wallet user this week but, no, I did not return the rest of the week = 2_PASSED</summary>

Case 1:

1. Clean profile 1.42.x
2. Open the brave://local-state file and ensured that the metrics `Brave.Wallet.NewUserReturning` response value is `0`
3. Create a wallet and reload the brave://local-state file and ensured that the metrics `Brave.Wallet.NewUserReturning` response value is `2` as expected



</details>

<details>
<summary>Case 4: I'm a first-time Brave Wallet user this week and, yes, I returned and used it again the following day = 3_PASSED</summary>

Case 1:

1. Clean profile 1.42.x
2. Create a wallet today (14th July)
3. Open the brave://local-state file and ensured that the metrics `Brave.Wallet.NewUserReturning` response value is `2`
4. Close the browser and set the system clock ahead by one day (15th July)
5. Relaunch the browser
6. Unlock the wallet
7. Reload the brave://local-state file 
8. The metrics response value is `3` as expected



Case 2:

1. Clean profile 1.42.x
2. Create a wallet today (11th July)
3. Open the brave://local-state file and ensured that the metrics `Brave.Wallet.NewUserReturning` response value is `2`
4. Close the browser and set the system clock ahead by one day (12th July)
5. Relaunch the browser
6. Unlock the wallet
7. Reload the brave://local-state file 
8. The metrics response value is `3` as expected



</details>

<details>
<summary>Case 5: I'm a first time Brave Wallet user this week and, yes, I returned and used it again this week but not the following day = 4_PASSED</summary>

1. Clean profile 1.42.x
2. Create a wallet today (14th July)
3. Open the brave://local-state file and ensured that the metrics `Brave.Wallet.NewUserReturning` response value is `2`
4. Close the browser and set the system clock ahead by one day (16th July)
5. Relaunch the browser
6. Unlock the wallet
7. Reload the brave://local-state file 
8. The metrics response value is `4` as expected



</details>
