### ISSUE TITLE
change string from `Show Top sites` to `Show Top Sites` under `New Tab Page` settings

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#23474]
## Description 

We added the `Show Top sites` setting via https://github.com/brave/brave-browser/issues/23118 that allows users to disable the `Top Sites` section under NTP. However, the label/string currently appears as `Show Top sites` but should be shown as `Show Top Tiles`. If you look at the other settings within `New Tab Page`, all of of the first characters are capitalized. We should keep the style consistent.

## Steps to reproduce 

1. download/install a version of Brave that has the `Show Top sites` feature (being introduced in `1.40.x`)
2. go into `Settings` -> `New Tab Page` and notice the discrepancy 

## Actual result 

![Screenshot_20220615-001858](https://user-images.githubusercontent.com/2602313/173750004-cd76dab9-a43d-44fa-bd4c-2d3d65959a27.png)

## Expected result

Should be displayed as `Show Top Sites` rather than `Show Top sites`

## Issue reproduces how often 

100% reproducible using the STR/Cases mentioned above.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `No` (will be released when `1.40.x` goes out)
- Can you reproduce this issue with the current Play Store Beta version? `Yes`
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Pixel 6`
   - Android version: `Android 13`
   
## Brave version

```
Brave | 1.41.64 Chromium: 103.0.5060.42 (Official Build) canary (32-bit)
--- | ---
Revision | de0d840bf9439c31bd86bf74f065c31fdf9b208d-refs/branch-heads/5060@{#667}
OS | Android 13; Build/TPB3.220513.017.B1
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by s0l0r1d4** [comment]
Beginner here, I wanna fix it
How do I start?

**Comment by tcchawla** [comment]
Hello, I would like to make the required changes to this issue.

**Comment by deeppandya** [comment]
Thank you @s0l0r1d4 and @tcchawla for reaching out. basically for this issue, you would need to update the string value from `Show Top sites` to `Show Top Sites` here : https://github.com/brave/brave-core/blob/50dd82b12eccb83fe46fbc748279e90e89462885/browser/ui/android/strings/android_brave_strings.grd#L3032

**Comment by daspartho** [comment]
resolved in #13908

**Comment by daspartho** [comment]
resolved in brave/brave-core#13908

**Comment by tcchawla** [comment]
Thanks, I will make the changes and make the PR.

**Comment by nawed2611** [comment]
Can I work on this issue?

**Comment by tcchawla** [comment]
I have made the changes @deeppandya. Please review the PR, and please revert if any changes are required in the PR. Thank you! 
https://github.com/brave/brave-browser/pull/23844

**Comment by kjozwiak** [comment]
Unfortunately this was never verified as the milestone was never set so QA never saw the above while running through the `1.42.x` milestone. Currently cleaning up https://github.com/orgs/brave/projects/40/views/1?filterQuery= hence finding this issue which was completely missed.
