### ISSUE TITLE
Remove GetPrivateKeyForImportedAccount

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#23477]
## Description 
Remove KeyringService::GetPrivateKeyForImportedAccount and use KeyringService::GetPrivateKeyForKeyringAccount instead for both imported and created accounts.
This call should just delegate to selected HDKeyring implementation.

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.42.65 Chromium: 103.0.5060.114 (Official Build) beta (64-bit) </th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.708)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=brave/brave-core#13804>https://github.com/brave/brave-core/pull/13804</a></li>
         <li>Verified account address and private keys match after import on a clean profile</li>
        </ul>
      </td>
   </tr>
</table>
