### ISSUE TITLE
Pinned tabs, when muted, can't always be unmuted by clicking on unmute icon

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#23476]
## Steps to Reproduce

   1. open a tab with some audio playing
   2. pin that tab
   3. mute and unmute - this would work normally
   4. open a second tab
    5. try muting the first tab
   6. the unmute icon doesn't work, until the tab is unpinned

## Brave version (brave://version info)

 V1.39.122 (June 10th, 2022) from customer
V 1.41.62 (June 15th, 2022) from Hubert (me)
## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

Issue came in from a customer that said this was an issue for 6 months or so. Use case would be for users that like to play music but that have that tab pinned. 

https://user-images.githubusercontent.com/12224304/173817012-54c8586b-2ccd-48c4-8632-787d490097c2.mov

**Comment by HEagle18** [comment]
https://community.brave.com/t/sound-icon-on-pinned-tab/405252/3  could be same issue

**Comment by wladiston** [comment]
This is so annoying

**Comment by sangwoo108** [comment]
Chromium canray seems to have the same problem. Let me see what I can do.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.42.62 Chromium: 103.0.5060.114 (Official Build) beta (x86_64)
-- | --
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | macOS Version 11.6.7 (Build 20G630)

### Steps:

1. installed `1.42.62`
2. launched Brave
3. load and play `https://www.youtube.com/watch?v=fOk8Tm815lE`
4. pin that tab
5. mute and unmute - confirmed this still works
6. open a second tab
7. tried muting the first tab

#### Confirmed I could mute/unmute both the original, pinned tab, as well as the 2nd tab.

![23476-tab-mute](https://user-images.githubusercontent.com/387249/178617133-c2059b20-cb00-43f9-bca1-83bcf2a556cd.gif)
