### ISSUE TITLE
Wrong monochrome icon used for Themed App Icon

### ISSUE THREAD

**Issue by seventhmoon** [brave/brave-browser#23478]
## Description 
Android 13 supported [Themed App Icons](https://developer.android.com/about/versions/13/features#themed-app-icons) which developers could use a monochrome `VectorDrawable` as the app icon. However, a Chrome / Chromium icon is shown for Brave.
I believe Brave didn't update this new asset and so it shows an Chrome / Chromium icon.

## Steps to reproduce 

   1. Add Brave shortcut to Desktop
   2. Turn on Themed Icons in Settings
   3. Observe the Icon

## Actual result 
Chrome / Chromium icon is shown

## Expected result
Brave icon is shown

## Issue reproduces how often 
100%

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version?  YES
- Can you reproduce this issue with the current Play Store Beta version?  N/A
- Can you reproduce this issue with the current Play Store Nightly version? N/A

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: Android 13 Beta 3
   
## Brave version
1.39.120

**Comment by seventhmoon** [comment]
The Beta `com.brave.browser_beta` and Nightly `com.brave.browser_nightly` have fixed the issue already.
Any ETA for the public version?

**Comment by samartnik** [comment]
Was fixed in the context of https://github.com/brave/brave-browser/issues/22861
