### ISSUE TITLE
[Android] Rewards panel should say `Logged out` 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#23480]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/21588
`Logged out` state is not shown in the BR panel when the custodian wallet is disconnected from brave

## Steps to reproduce 

   1. Clean profile 1.40.x
   2. Enable rewards and connect the existing KYC'd uphold/Gemini/bitFlyer wallet 
   3. Get the wallet into a logged-out state
   4. Confirm that the wallet is in the `Logged out` state on the brave://rewards settings page
   5. Click on the BR panel
   6. Wallet state is NOT in the `Logged out` state instead it's showing up the `Disconnected` state
   

## Actual result 

`Logged out` state is not shown in the BR panel when the custodian wallet is disconnected from brave
![image](https://user-images.githubusercontent.com/38657976/173861325-2a9008d4-628e-436d-b5b6-0f01e47b6fd8.png)

## Expected result

`Logged-out` state should be shown on both rewards settings and BR panel
## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Not sure
- Can you reproduce this issue with the current Play Store Beta version? Not sure
- Can you reproduce this issue with the current Play Store Nightly version?Not sure

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung Galaxy Tab A7
   - Android version: version 11
   
## Brave version

1.40.99
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @Miyayes @brave/qa-team @deeppandya @emerick

**Comment by Uni-verse** [comment]
In Progress on Samsung Galaxy S 21 & Galaxy Tab S7 using the following build(s):

Brave	1.44.97 Chromium: 106.0.5249.55 (Official Build) (64-bit) 
Revision	4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}
OS	Android 12; Build/SP1A.210812.016

**Uphold** - `Passed`

Example | Example | Example
-|-|-
![screenshot-1663856836976](https://user-images.githubusercontent.com/17885425/191784202-99e591a7-c858-4e46-9937-72d17632d25f.png) | ![screenshot-1663856849600](https://user-images.githubusercontent.com/17885425/191784208-51117206-7a8d-4bd7-82a7-df32f510921a.png) | ![screenshot-1663856929359](https://user-images.githubusercontent.com/17885425/191784211-678701df-25c8-4aa3-bad5-0162339eab49.png)
![screenshot-1663858676180](https://user-images.githubusercontent.com/17885425/191784693-2a01a671-36df-45f9-8c53-0c89fda68284.png) | ![screenshot-1663858730103](https://user-images.githubusercontent.com/17885425/191785229-e9f57019-1ccb-4fad-9de8-3f90ecfbd50c.png) | ![screenshot-1663858748607](https://user-images.githubusercontent.com/17885425/191785015-d43dd028-957a-4339-bf3f-efb1b964ae78.png)

**Gemini** - `Failed`

Example | Example | Example
-|-|-
![screenshot-1663858929034](https://user-images.githubusercontent.com/17885425/191785463-f28bb0a3-3084-4ec6-bf90-70c543c8322e.png) | ![screenshot-1663859137592](https://user-images.githubusercontent.com/17885425/191785574-bc431bde-2ee9-4d12-b6bc-6e6e64513cce.png) | ![screenshot-1663859724394](https://user-images.githubusercontent.com/17885425/191785918-a08d32e5-fe5f-428f-8032-1142be9f39b5.png)

**bitFlyer** - `Failed`
Example | Example | Example
-|-|-

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 13` using the following build(s):

```
Brave | 1.44.97 Chromium: 106.0.5249.55 (Official Build) (64-bit)
--- | ---
Revision | 4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}
OS | Android 13; Build/T1B1.220819.006
```

@Uni-verse ran through the the following last night but didn't update the issue. So adding my verification notes 👍 

**`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------
![Screenshot_20220922-020516](https://user-images.githubusercontent.com/2602313/191802369-cf0fcddd-9e05-43da-a7a3-11515332a1ad.png) | ![Screenshot_20220922-025637](https://user-images.githubusercontent.com/2602313/191802437-e137f891-e44e-429a-b2d8-3371c556fd70.png) | ![Screenshot_20220922-025645](https://user-images.githubusercontent.com/2602313/191802443-e9342e47-cd83-4c9d-bd9e-370cca3a6e02.png)
