### ISSUE TITLE
Bug when trying to edit name of a top tile

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#23483]
## Description 

https://user-images.githubusercontent.com/7606853/173875500-bf0f65a7-ed95-4c90-b223-04e1061ff1f5.mov

Version: [Version 1.41.42 Chromium: 102.0.5005.78 (Official Build) nightly (x86_64)](https://brave.com/latest/)

**Comment by sangwoo108** [comment]
Seems the click event isn't handled by the editor. When I hit the enter key, it works. z-order can be the problem.

![image](https://user-images.githubusercontent.com/5474642/176443375-02166f30-e163-4dfa-9d3a-3ce442494743.png)

**Comment by rebron** [comment]
@sangwoo108 Related to https://github.com/brave/brave-browser/issues/23685 
Can you check if already fixed with @fallaciousreasoning's PR https://github.com/brave/brave-core/pull/13975

**Comment by sangwoo108** [comment]
Yeah. I think so. It's exactly same patch!
