### ISSUE TITLE
Shields breaking fonts on Feedly

### ISSUE THREAD

**Issue by pilgrim-brave** [brave/brave-browser#23489]
spun off from https://github.com/brave/brave-browser/issues/23093#issuecomment-1156520427 because this bug has a separate root cause and was not fixed when other sites mentioned in that issue were fixed

**Comment by kjozwiak** [comment]
Removing the `OS/Android` label as it looks like `Android` wasn't affected, specifically the STR/Case @stephendonner mentioned above. Example using `1.39.120 Chromium: 102.0.5005.99` which doesn't include the fix from https://github.com/brave/brave-core/pull/13807 but has Font FP which was introduced in `1.39.x`:

**`Shields Enabled with default FP`** | **`Shields Disabled`**
-----------------------------------------|---------------------------
![Screenshot_20220616-221923_Brave](https://user-images.githubusercontent.com/2602313/174212002-defde671-c749-4734-8422-90c6a78bef29.jpg) | ![Screenshot_20220616-221930_Brave](https://user-images.githubusercontent.com/2602313/174212000-622b6a6b-309a-442c-9e1e-537bfc636169.jpg)

**Comment by kjozwiak** [comment]
@brave/qa-team `Win` case will be handled via https://github.com/brave/brave-browser/issues/23541.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.40.104 Chromium: 103.0.5060.53 (Official Build) (x86_64)
-- | --
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | macOS Version 11.6.7 (Build 20G630)

Tested several times (with and without app restarts), with both new and pre-existing profiles.

Couldn't get it to fail 👍 

`run 1` | `run 5` | `run 8` | `run 17`
------|------|-------|------
<img width="1770" alt="Screen Shot 2022-06-18 at 6 27 06 PM" src="https://user-images.githubusercontent.com/387249/174462175-ff471356-54d3-40ec-ac7c-6063faabdb58.png"> | <img width="1770" alt="Screen Shot 2022-06-18 at 6 28 06 PM" src="https://user-images.githubusercontent.com/387249/174462177-fec8fd22-638e-421b-addc-0b9b10769bb9.png"> | <img width="1770" alt="Screen Shot 2022-06-18 at 6 29 45 PM" src="https://user-images.githubusercontent.com/387249/174462224-e652ac13-ce4e-416a-965b-c2545d677e0f.png"> | <img width="1312" alt="Screen Shot 2022-06-18 at 6 30 42 PM" src="https://user-images.githubusercontent.com/387249/174462228-daba3165-fbf9-49cc-9981-c58cebaf396c.png">
