### ISSUE TITLE
[QA] 0.57.x sync issues that still need to be verified

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#2349]
Because it was decided that sync won't be going out enabled by default in `0.57.x`, QA concentrated on verifying other issues, specifically `muon` migration. Because the following PR/fixes already landed in `0.57.x`, we need to verify that the following have also been QA'd/verified for sync:

* Unable to create sync chain without entering a device name #2126
* Console logs error when sync is enabled #2132
* remove `sync this device` interface #2156
* Reset sync should show warning message to user, if sync is already established between two devices #2134
* Update sync to production server #2211
* Folder created on Android shows up without name #2144

CCing @brave/legacy_qa please let me know if there's anything that I might have missed. Either way, I'll go through the list once again once we release `0.57.x` and update this issue if anything else was forgotten.

**Comment by srirambv** [comment]
Verified all issues except #2144 as its blocked. All verification done on 

Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta(64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Linux
