### ISSUE TITLE
Update VPN support text

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#23490]
## Description 
Please update the auto-generate body text from:

> #### Please do not edit any information below ####

to

> #### Brave doesn’t track you or know how you use our app, so we don’t know how you've set up VPN. Please share info about the issue you're experiencing and we'll do our best to resolve it as soon as we can. ####

Note, the #### are being deleted here, edit to see the correct format

**Comment by kjozwiak** [comment]
The above will require `1.40.105` or newer for `1.40.x` verification 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 13` using the following build(s):

```
Brave | 1.40.105 Chromium: 103.0.5060.53 (Official Build) (64-bit)
--- | ---
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | Android 13
```

**`Before Fix`** | **`With Fix`**
-----------------|----------------
![Screenshot_20220620-004556](https://user-images.githubusercontent.com/2602313/174527356-e35082df-462f-414c-80b0-8cca57d174d3.png) | ![Screenshot_20220620-004425](https://user-images.githubusercontent.com/2602313/174527370-4449489c-e144-4688-b19c-af0d6d6e435e.png)
