### ISSUE TITLE
Leaking Chromium/Brave full version through navigator.userAgentData.getHighEntropyValues()

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#23491]
## Description 

This is what I get in dev console or by going to https://browserleaks.com/client-hints (scroll down for the JS API):
```
> await navigator.userAgentData.getHighEntropyValues(["fullVersionList", "uaFullVersion"]);
```

<img width="751" alt="image" src="https://user-images.githubusercontent.com/5284154/204843298-ecae4b33-beb5-499b-948a-b1a41f48152d.png">

We should not leak the full version in `fullVersionList` and `uaFullVersion` and instead clamp it to the major version, same as in `brands` (108 in this case).

There's a separate webcompat question of what to do about high entropy values for `"platformVersion, "architecture", 
"platform", "bitness"` but for UA versions it's clear that we should just match what we have in the UA.

**Comment by kjozwiak** [comment]
The above requires `1.46.139` or higher for `1.46.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.46.141 Chromium: 108.0.5359.99 (Official Build) (x86_64)
-- | --
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | macOS Version 13.1 (Build 22C65)

### Steps:
1. installed `1.46.141`
2. launched Brave
3. opened `Developer Tools`
4. clicked on the `Console` tab
5. entered `await navigator.userAgentData.getHighEntropyValues(["fullVersionList", "uaFullVersion"]);`
6. expanded the `fullVersionList`

#### Confirmed we only show the first digit of the version # 

<img width="1312" alt="Screenshot 2022-12-09 at 12 57 36 PM" src="https://user-images.githubusercontent.com/387249/206795266-075e1018-b8bb-485e-b1a4-36aa446956a7.png">

**Comment by btlechowski** [comment]
Verification **PASSED** on

Brave | 1.46.141 Chromium: 108.0.5359.99 (Official Build) (64-bit)
-- | --
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | Ubuntu 18.04 LTS

### Steps:
1. installed `1.46.141`
2. launched Brave
3. opened `Developer Tools`
4. clicked on the `Console` tab
5. entered `await navigator.userAgentData.getHighEntropyValues(["fullVersionList", "uaFullVersion"]);`
6. expanded the `fullVersionList`

#### Confirmed we only show the first digit of the version # 

![image](https://user-images.githubusercontent.com/34715963/206806823-408e04a2-d20f-4176-887e-411f85dff66d.png)
