### ISSUE TITLE
Manual test run on macOS (arm64) for `1.40.x - Release`

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#23498]
### Installer

- [x] Ensured that the following executables work as expected
   - [x] `Brave-Browser-arm64.dmg`
      - [x] Check executable size, should be `~290mb`
      - [x]  Check signature: If OS Run `spctl --assess --verbose` for the installed version and make sure it returns `accepted`.
   - [x] `Brave-Browser-arm64.pkg`
       - [x] Check executable size, should be `~290mb`
       - [x]  Check signature: If OS Run `spctl --assess --verbose` for the installed version and make sure it returns `accepted`.
   - [x] `Brave-Browser-x64.dmg`
       - [x] Check executable size, should be `~290mb`
       - [x]  Check signature: If OS Run `spctl --assess --verbose` for the installed version and make sure it returns `accepted`.
   - [x] `Brave-Browser-x64.pkg`
       - [x] Check executable size, should be `~290mb`
       - [x]  Check signature: If OS Run `spctl --assess --verbose` for the installed version and make sure it returns `accepted`.
   - [x] `Brave-Browser-universal.dmg`
       - [x] Check executable size, should be `~500mb`
       - [x]  Check signature: If OS Run `spctl --assess --verbose` for the installed version and make sure it returns `accepted`.
   - [x] `Brave-Browser-universal.pkg`
       - [x] Check executable size, should be `~500mb`
       - [x]  Check signature: If OS Run `spctl --assess --verbose` for the installed version and make sure it returns `accepted`.
- [x] Visited `brave://version` and ensure the following:
   - [x] `arm64` is being displayed when installing via `arm64` and `universal` binaries on `M1` mac
   - [x] `x86_64 translated` is being displayed when installing via `x64` binary on `M1` mac using `Rosetta`

### Widevine

- [x]  Using `universal` build:
   - [x]  Verify `Widevine Notification` is shown when you visit Netflix for the first time
   - [x]  Test that you can stream on Netflix on a fresh profile after installing Widevine 
- [x]  Using `arm64` build:
   - [x]  Verify `Widevine Notification` is shown when you visit Netflix for the first time
   - [x]  Test that you can stream on Netflix on a fresh profile after installing Widevine 

#### Components
- [x]   Delete Adblock folder from browser profile and restart browser. Visit `brave://components` and verify `Brave Ad Block Updater` downloads and update the component. Repeat for all Brave components

#### Upgrade - `Brave-Browser-arm64.dmg`

- [x] Make sure that data from the last version appears in the new version OK
- [x] Ensure that `brave://version` lists the expected Brave & Chromium versions
- [x] With data from the last version, verify that
  - [x] Bookmarks on the bookmark toolbar and bookmark folders can be opened
  - [x] Cookies are preserved
  - [x] Installed extensions are retained and work correctly
  - [x] Opened tabs can be reloaded
  - [x] Stored passwords are preserved
  - [x] Sync chain created in previous version is retained 
  - [x] Social media blocking buttons changes are retained
  - [x] Rewards
    - [x] BAT balance is retained
    - [x] Auto-contribute list is retained
    - [x] Both Tips and Monthly Contributions are retained
    - [x] Panel transactions list is retained
    - [x] Changes to rewards settings are retained
    - [x] Ensure that Auto Contribute is not being enabled when upgrading to a new version if AC was disabled
  - [x] Ads
    - [x] Both `Estimated pending rewards` & `Ad notifications received this month` are retained
    - [x] Changes to ads settings are retained
    - [x] Ensure that ads are not being enabled when upgrading to a new version if they were disabled
    - [x] Ensure that ads are not disabled when upgrading to a new version if they were enabled 

#### Upgrade - `Brave-Browser-x64.dmg`

- [x] Make sure that data from the last version appears in the new version OK
- [x] Ensure that `brave://version` lists the expected Brave & Chromium versions
- [x] With data from the last version, verify that
  - [x] Bookmarks on the bookmark toolbar and bookmark folders can be opened
  - [x] Cookies are preserved
  - [x] Opened tabs can be reloaded
  - [x] Stored passwords are preserved
  - [x] Sync chain created in previous version is retained 
  - [x] Social media blocking buttons changes are retained 

#### Upgrade - `Brave-Browser-universal.dmg`

Pre-requisite: Make sure that the previous version is installed using the universal build
- [x] Make sure that after upgrade, the universal build is upgraded to the appropriate architecture specific version
- [x] Confirm that the .app file size has decreased as a result of the upgrade
- [x] Make sure that data from the last version appears in the new version OK
- [x] Ensure that `brave://version` lists the expected Brave & Chromium versions
- [x] With data from the last version, verify that
  - [x] Bookmarks on the bookmark toolbar and bookmark folders can be opened
  - [x] Cookies are preserved
  - [x] Opened tabs can be reloaded
  - [x] Stored passwords are preserved
  - [x] Sync chain created in previous version is retained 
  - [x] Social media blocking buttons changes are retained

**Comment by stephendonner** [comment]
`Brave-Browser-arm64.dmg`:

Brave | 1.40.103 Chromium: 103.0.5060.53 (Official Build) (arm64)
--|--
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | macOS Version 11.6.6 (Build 20G624)`

`Brave-Browser-arm64.pkg`:

Brave | 1.40.103 Chromium: 103.0.5060.53 (Official Build) (arm64)
--|--
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | macOS Version 11.6.6 (Build 20G624)


`Brave-Browser-x64.dmg`:

Brave | 1.40.103 Chromium: 103.0.5060.53 (Official Build) (x86_64 translated)
--|--
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | macOS Version 11.6.6 (Build 20G624)

`Brave-Browser-x64.pkg`:


Brave | 1.40.103 Chromium: 103.0.5060.53 (Official Build) (x86_64 translated)
--|--
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | macOS Version 11.6.6 (Build 20G624)

`Brave-Browser-universal.dmg`:

Brave | 1.40.103 Chromium: 103.0.5060.53 (Official Build) (arm64)
--|--
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | macOS Version 11.6.6 (Build 20G624)


`Brave-Browser-universal.pkg`:

Brave | 1.40.103 Chromium: 103.0.5060.53 (Official Build) (arm64) 
--|--
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | macOS Version 11.6.6 (Build 20G624)
