### ISSUE TITLE
Launching VPN support page will crash app if set as default

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#23492]
## Description 
Loading the VPN Support page will crash app if brave was previously set as default. It will open URL initially if brave is not default browser and user is prompted with the `open with` modal and selects "Always". If user tries to open again after that, it will result in crash. Also, selecting "Just Once" from the `open with` modal with result in same crash. 

**Note: VPN menu is disabled on Beta, Nightly**

Case 1: Set brave as default, open `VPN Support` page
Case 2: Skip default, open `VPN Support` page, select "Just Once" from `open with` prompt

Reproducible on `1.39.x`, `1.40.x`, `1.41.x`

## Steps to reproduce 

Precondition: VPN setting enabled through dev/qa menu on Beta/Nightly

   1. Clean install
   2. Set brave as default browser
   3. Navigate to Menu > Settings > Brave Firewall + VPN 
   4. Tap on VPN Support
   5. Observe

## Actual result 
<table><tr><td>

https://user-images.githubusercontent.com/17885425/173943040-f7c0fe7e-4b9a-4685-bdec-bf603d3cdf62.mp4

</td><td>

https://user-images.githubusercontent.com/17885425/173943065-92cfb730-8c62-4e0f-b4a3-53ad6276022b.mp4</td>

</tr></table>

<hr>

```
--- beginning of crash
06-15 13:37:28.250 10824  2845  2845 E AndroidRuntime: FATAL EXCEPTION: main
06-15 13:37:28.250 10824  2845  2845 E AndroidRuntime: Process: com.brave.browser_beta, PID: 2845
06-15 13:37:28.250 10824  2845  2845 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources$Theme android.content.Context.getTheme()' on a null object reference
06-15 13:37:28.250 10824  2845  2845 E AndroidRuntime: 	at Q33.a(chromium-MonochromePublic6432.aab-beta-414009624:355)
06-15 13:37:28.250 10824  2845  2845 E AndroidRuntime: 	at androidx.preference.Preference.<init>(chromium-MonochromePublic6432.aab-beta-414009624:314)
06-15 13:37:28.250 10824  2845  2845 E AndroidRuntime: 	at tf3.<init>(chromium-MonochromePublic6432.aab-beta-414009624:325)
06-15 13:37:28.250 10824  2845  2845 E AndroidRuntime: 	at org.chromium.chrome.browser.settings.BraveMainPreferencesBase.c4(chromium-MonochromePublic6432.aab-beta-414009624:182)
06-15 13:37:28.250 10824  2845  2845 E AndroidRuntime: 	at oG.run(Unknown Source:2)
06-15 13:37:28.250 10824  2845  2845 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
06-15 13:37:28.250 10824  2845  2845 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-15 13:37:28.250 10824  2845  2845 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
06-15 13:37:28.250 10824  2845  2845 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
06-15 13:37:28.250 10824  2845  2845 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8582)
06-15 13:37:28.250 10824  2845  2845 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-15 13:37:28.250 10824  2845  2845 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:563)
06-15 13:37:28.250 10824  2845  2845 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
06-15 13:37:28.266  1000   737   737 D io_stats: !@   8,0 r 4993518 130680836 w 5549344 102408648 d 1049554 306078732 f 0 0 iot 5352904 0 th 0 0 0 pt 0 inp 0 0 365898.460
06-15 13:37:28.583  1000  1230  3581 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
06-15 13:37:28.585  1000  1230  1586 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
06-15 13:37:28.585  1000  1230  2449 W ActivityManager: crash : com.brave.browser_beta,10824
```

## Expected result
VPN support page should open in new tab

## Issue reproduces how often 
Easily, follow STR

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung GS 21 & Tab S7
   - Android version: 12
   
## Brave version
Release `1.39.123, Chromium 102.0.5005.125`
Beta `1.40.x`
Nightly `1.41.x`

**Comment by kjozwiak** [comment]
Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/23492#issue-1272826763, I reproduced the crash using the following devices:

* reproduced on `Pixel 6` running `Android 13` using `1.39.123 Chromium: 102.0.5005.125`
* reproduced on `Samsung S10+` running `Android 12` using `1.39.123 Chromium: 102.0.5005.125`

**`Pixel 6 Example`** | **`Samsung S10+ Example`**
-----------------------|----------------------------------
https://user-images.githubusercontent.com/2602313/173993686-ba3151fb-e8fa-4329-9ef6-1228fce06019.mp4 | https://user-images.githubusercontent.com/2602313/173994160-47476072-e629-409b-bc7d-0c96187f6bdd.mp4

**Comment by kjozwiak** [comment]
The above will require `1.40.105` or newer for `1.40.x` verification 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 13` using the following build(s):

```
Brave | 1.40.105 Chromium: 103.0.5060.53 (Official Build) (64-bit)
--- | ---
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | Android 13
```

Went through the STR/Cases outlined via https://github.com/brave/brave-browser/issues/23492#issue-1272826763 & https://github.com/brave/brave-browser/issues/23492#issuecomment-1157231322 and couldn't reproduce the original issue. Also ensured that you can enable VPN and restore a subscription without any issues.
