### ISSUE TITLE
Shields is not shown after clearing browser history

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#235]
## Description 

Shields is not shown after clearing browser history
## Steps to Reproduce

   1. Build from source 
   2. Open a new tab and visit brianbondy.com
   3. Clear browsing history 
   4. Switch back brianbondy.com and click on shields, shows blank layout
   5. Close and open shields again, shows shields menu correctly
   6. Open a new tab and visit the same site and click on shields icon, shows blank, reopen shields shows it correctly

 ## Actual result:

![clearhistory](https://user-images.githubusercontent.com/17010094/40614898-97b2095e-6252-11e8-89df-3dc940602e89.gif)

## Expected result:
Should always show the shields menu correctly 
## Reproduces how often: 

Easy

## Brave version (about:brave info)

 2e9c470

**Comment by bbondy** [comment]
Seems to be working now per 1:1 on Slack. Please re-open if you see it again though.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7
