### ISSUE TITLE
Separate out NFT's from Tokens in protfolio

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23506]
## Description 
Separate out NFT's from Tokens in protfolio

## Steps to reproduce 

   1. Install 1.40.99 build
   2. Add custom token for ERC721
   3. Gets listed but doesn't list as NFT similar to desktop

## Actual result 
<img width=300 src=https://user-images.githubusercontent.com/17010094/174029487-5e892a50-a370-4bcb-90f0-4c3d072cc5fd.png>

## Expected result
NFT should be listed as its own section when added similar to desktop

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 12
   
## Brave version
1.40.99

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @wchen342 @Pavneet-Sing @SergeyZhukovsky @jamesmudgett

**Comment by Pavneet-Sing** [comment]
Completed with https://github.com/brave/brave-core/pull/16643.
