### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by HenriqueRamos13** [brave/brave-browser#23509]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.38.119  Chromium: 101.0.4951.67
Operating System: Mac OS X 12.3.0

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Go to google meet, start a meet
2. Share your all screen
3. Click in brave icon that disable ADS. (Sometimes brave crash when u click in icon without sharing screen.)

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/aa9c0000-4c26-6008-0000-000000000000

**Comment by bsclifton** [comment]
Reported here too - https://github.com/brave/brave-browser/issues/23599

Should be fixed. No new reports (in that issue or otherwise). May have been an upstream bug that was fixed
