### ISSUE TITLE
Unable to Send ERC721 tokens

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23508]
## Description 
Unable to Send ERC721 tokens

## Steps to reproduce 

   1. Add an ERC721 token to portfolio
   2. Select send on quick action button
   3. Select the account which has the ERC721 token associated to
   4. Select token dropdown, no ERC721 token is shown to select to send

## Actual result 
Unable to Send ERC721 tokens

## Expected result
Should be able to send ERC721 tokens similar to desktop

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 12
   
## Brave version
1.40.101 RC build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @wchen342 @SergeyZhukovsky @Pavneet-Sing @jamesmudgett

**Comment by deeppandya** [comment]
@srirambv needs to verify on nightly/beta.

**Comment by srirambv** [comment]
This is currently working on Nightly (1.42.25). @wchen342 mind linking the PR/Commit that fixed this so it can be linked to a milestone?

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.41.86 x64 Beta build
- Verified able to send ERC721 tokens from account to another.
