### ISSUE TITLE
Remove previous `getBuyUrl` method in core when android and iOS implement selecting buy tab currency

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#23503]

**Comment by muliswilliam** [comment]
@nuo-xu @Pavneet-Sing Have you migrated iOS/Android to `getBuyUrlV2`. I would like to remove the older implementation. If not, you can update here when you do.

**Comment by muliswilliam** [comment]
This issue will remain open until iOS and Android no longer have a dependency on `getBuyUrl`

**Comment by Pavneet-Sing** [comment]
Android is using `BlockchainRegistry#getBuyUrl` and seems it should now be replaced with `AssetRatioService#getBuyUrlV1` (seems [`getBuyUrlV2`](https://github.com/brave/brave-browser/issues/23503#issuecomment-1401698538) is a typo).

Created an issue for android: https://github.com/brave/brave-browser/issues/27996
Seems like it should be ASAS and
Do we wanna uplift this to beta as well? @muliswilliam

**Comment by muliswilliam** [comment]
@Pavneet-Sing We may not need an uplift depending on when the work is completed.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.50.85 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from [brave/brave-core#17340](https://github.com/brave/brave-core/pull/17340)
- Verified `Buy with Ramp or Transak or Sardine` loads corresponding on-ramp widget page

https://user-images.githubusercontent.com/17010094/224976560-d50a6a6d-502a-4928-9ee7-a2cb37158813.mp4
