### ISSUE TITLE
Prepare for NetworkService migration

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#2351]
Chromium team is in the middle of a big project, called servicification [1]. One of the most significant parts of it is transition to the Network Service [2].

One of the goals of moving to NS is to avoid storing information in `ProfileIOData` (i.e. cookies), so `ProfileIOData` will eventually become deprecated. At the moment, the core code of brave shields `brave_shields_util.cc` depends on `ProfileIOData`, so it needs to be reworked in the future. `

`ChromeNetworkDelegate` itself probably will also be deprecated in favor of `NetworkServiceNetworkDelegate`

Deadlines or milestone dates of [1] and [2] are not yet clear.

[1] https://www.chromium.org/servicification
[2] https://bugs.chromium.org/p/chromium/issues/detail?id=598073

**Comment by iefremov** [comment]
@tomlowenthal FYI

**Comment by lukf** [comment]
Can confirm that Shield becomes ineffective with `chrome://flags/#network-service` enabled.

**Comment by iefremov** [comment]
`ChromeNetworkDelegate` is not functioning with NetworkService, it seems we should start with replacing it witih `NetworkServiceNetworkDelegate`. `ProfileIOData` will stay with us for a while.

**Comment by bbondy** [comment]
Please revert this as part of this work:
brave/brave-core@9257ced

**Comment by bbondy** [comment]
upgraded to p1 priority

**Comment by iefremov** [comment]
As part of migration we have to fix Tor - it doesn't work with enabled NetworkService. It seems that the reason is `TorProfileServiceImpl::SetNewTorCircuitOnIOThread`: `URLRequestContext` is not compatible with NetworkService @darkdh

**Comment by iefremov** [comment]
Filed https://github.com/brave/brave-browser/issues/4312

**Comment by simonhong** [comment]
Failed browser test with NS on MacOS.
```
20 tests failed:
    AdBlockServiceTest.AdBlockThirdPartyWorksForThirdPartyHost (../../brave/components/brave_shields/browser/ad_block_service_browsertest.cc:649)
    AdBlockServiceTest.AdsGetBlockedAfterDataFileVersionUpgrade (../../brave/components/brave_shields/browser/ad_block_service_browsertest.cc:393)
    AdBlockServiceTest.AdsGetBlockedByCustomBlocker (../../brave/components/brave_shields/browser/ad_block_service_browsertest.cc:290)
    AdBlockServiceTest.AdsGetBlockedByDefaultBlocker (../../brave/components/brave_shields/browser/ad_block_service_browsertest.cc:244)
    AdBlockServiceTest.AdsGetBlockedByRegionalBlocker (../../brave/components/brave_shields/browser/ad_block_service_browsertest.cc:335)
    AdBlockServiceTest.BlockNYP (../../brave/components/brave_shields/browser/ad_block_service_browsertest.cc:671)
    AdBlockServiceTest.CancelRequestOptionTest (../../brave/components/brave_shields/browser/ad_block_service_browsertest.cc:792)
    AdBlockServiceTest.NewTabContinuesToBlock (../../brave/components/brave_shields/browser/ad_block_service_browsertest.cc:474)
    AdBlockServiceTest.SocialButttonAdBLockTagTest (../../brave/components/brave_shields/browser/ad_block_service_browsertest.cc:693)
    AdBlockServiceTest.SubFrame (../../brave/components/brave_shields/browser/ad_block_service_browsertest.cc:509)
    AdBlockServiceTest.TagPrefsControlTags (../../brave/components/brave_shields/browser/ad_block_service_browsertest.cc:744)
    AdBlockServiceTest.TrackerReferencedFromUntrustedDomain (../../brave/components/brave_shields/browser/ad_block_service_browsertest.cc:573)
    AdBlockServiceTest.TwoDiffAdsGetCountedAsTwo (../../brave/components/brave_shields/browser/ad_block_service_browsertest.cc:450)
    AdBlockServiceTest.TwoSameAdsGetCountedAsOne (../../brave/components/brave_shields/browser/ad_block_service_browsertest.cc:426)
    BraveNetworkDelegateBaseBrowserTest.ThirdPartySTS (../../brave/browser/net/brave_network_delegate_hsts_fingerprinting_browsertest.cc:93)
    BraveNetworkDelegateBrowserTest.Iframe3PCookieBlocked (../../brave/browser/net/brave_network_delegate_browsertest.cc:70)
    BraveNetworkDelegateBrowserTest.IframeJs3PCookieBlocked (../../brave/browser/net/brave_network_delegate_browsertest.cc:87)
    HTTPSEverywhereServiceTest.RedirectsKnownSite (../../brave/components/brave_shields/browser/https_everywhere_service_browsertest.cc:101)
    HTTPSEverywhereServiceTest.RedirectsKnownSiteInIframe (../../brave/components/brave_shields/browser/https_everywhere_service_browsertest.cc:127)
    TrackingProtectionServiceTest.TrackerReferencedFromUntrustedDomainGetsBlocked (../../brave/components/brave_shields/browser/tracking_protection_service_browsertest.cc:169)
5 tests timed out:
    BraveRewardsBrowserTest.RecurringTipForUnverifiedPublisher (../../brave/components/brave_rewards/browser/rewards_service_browsertest.cc:1408)
    BraveRewardsBrowserTest.RecurringTipForVerifiedPublisher (../../brave/components/brave_rewards/browser/rewards_service_browsertest.cc:1390)
    BraveRewardsBrowserTest.TipUnverifiedPublisher (../../brave/components/brave_rewards/browser/rewards_service_browsertest.cc:1372)
    BraveRewardsBrowserTest.TipVerifiedPublisher (../../brave/components/brave_rewards/browser/rewards_service_browsertest.cc:1355)
    BraveSchemeLoadBrowserTest.SettingsPageIsNotAllowedInPrivateWindow (../../brave/browser/brave_scheme_load_browsertest.cc:253)
```

**Comment by iefremov** [comment]
The current plan is to implement our own `ProxyingURLLoaderFactory` similar to `WebRequestProxyingURLLoaderFactory`, since this is the only logical interface for our Shields machinery after enabling `NetworkService`.

There is a draft PR with this factory, cargoculted/copypasted from two existing `Proxying` factories in Chromium (https://github.com/brave/brave-core/pull/2701), not sure if it is possible to reduce the amount of boilerplate, but probably stuff connected to `TrustedHeaderClient` will not be needed.

Plumbing easiest individual shield callbacks seems working (not presented in the PR), though porting the whole loop of callbacks that occasionally redirect requests is somewhat bigger task, which I'm doing right now.  

There is one thing that could be done in parallel with the current stuff - dealing with `AdBlockInterceptor`, which is a part of our ad-blocking mechanism. In the current shields architecture, we set some special header during the ad-blocking session in `NetworkDelegate` and later craft an empty `200 OK` response in the interceptor. NetworkService doesn't work with interceptors, instead, some custom `URLLoaderFactory` should be provided, which probably should be different from the `Proxying` one described above.

**Comment by iefremov** [comment]
Fixed in
https://github.com/brave/brave-core/pull/2988
https://github.com/brave/brave-core/pull/3245
