### ISSUE TITLE
Made an option to completely disable DApps notifications

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#23518]
It has to be under Brave Wallet section in Settings and on by default.

**Comment by kjozwiak** [comment]
The above will require `1.40.105` or higher for `1.40.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.40.105 x64 build
- Verified a new setting called `Display Web3 notifications` is available under Brave Wallet setting
- Verified the new setting is enabled by default
- Verified disabling the setting stops from showing `This page wants to interact with Brave Wallet` 
- Verified disabling the setting doesn't stop from manually connecting and interacting with the Dapp

Oppo Reno 5(Android 12) | Samsung Tab A (Android 10)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/174611936-3a6d799f-2355-4757-b00e-79abb9ae9c39.mp4> | <video src=https://user-images.githubusercontent.com/17010094/174615073-072d0328-0ca9-44ec-b42e-dcd55afe8786.mp4>
