### ISSUE TITLE
Creating a new Solana/Filecoin account only switches the network but not the account

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23515]
## Description 

Creating a new Solana/Filecoin account only switches the network but not the account

## Steps to Reproduce

   1. Clean profile and create wallet
   2. Go to Accounts tab and click on Create account
   3. Select Solana/Filecoin from the modal and continue to create a new account on the network
   4. Network changes to the new one in widget but Account is still set to Ethereum
   5. Reselecting the new network switches the account created on that network

## Actual result:

https://user-images.githubusercontent.com/17010094/174095986-051da580-42e4-43bd-bc05-385708a61352.mp4

## Expected result:
If network is switched then the account should also switch to the associated network

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.41.68 Chromium: 103.0.5060.42 (Official Build) nightly (64-bit) 
-- | --
Revision | `e0d840bf9439c31bd86bf74f065c31fdf9b208d-refs/branch-heads/5060@{#667}`
OS | Windows 11 Version 21H2 (Build 22000.739)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel @jamesmudgett

**Comment by yrliou** [comment]
@Douglashdaniel Is it related to https://github.com/brave/brave-browser/issues/22114?

**Comment by Douglashdaniel** [comment]
@yrliou I have attempted to handle this on the `Front-end` in https://github.com/brave/brave-core/pull/13325
Seems like it should still be handled by the core code though? What do you think?

**Comment by Douglashdaniel** [comment]
Will revisit this after https://github.com/brave/brave-browser/issues/22114

**Comment by Douglashdaniel** [comment]
Closing as this is no longer replicable!
We now create a `Solona` account on `Wallet` creation.
`Filecoin` worked as expected though!


https://user-images.githubusercontent.com/40611140/220755669-48dbc482-6c45-4870-ba5c-8f120629969c.mov
