### ISSUE TITLE
[Android] logged-out notification is not shown on the BR panel

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#23517]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/22508
logged-out notification is not shown on the BR panel

## Steps to reproduce 

   1. Follow the steps (1 to 11) from case5 https://github.com/brave/brave-browser/issues/22508#issuecomment-1156576542
   2. In step 12, the logged-out notification is not shown on the BR panel
   

## Actual result 

logged-out notification is not shown on the BR panel

![Screenshot_20220616-221341_Brave](https://user-images.githubusercontent.com/38657976/174133572-fe4c276d-e705-40bf-b97e-be97948dc631.jpg)

## Expected result

logged-out notification should be shown on the BR panel
## Issue reproduces how often 

Easy
## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung Galaxy Tab A7
   - Android version: version 11
   
## Brave version
1.40.101

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/qa-team @Miyayes @deeppandya

**Comment by Miyayes** [comment]
https://github.com/brave/brave-browser/issues/20603 Dupe
