### ISSUE TITLE
Dapps: Wallet approval screen auto closes when trying to click on the panel button

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23511]
## Description 
Wallet approval screen flashes when trying to click on the panel button

## Possible Steps to reproduce  (may not be accurate)

   1. Clean install 1.40.101 build
   2. Create a wallet account
   3. Visit `https://chainlist.org/` and connect the wallet and try to add a network
   4. Panel **_sometimes_** takes time to show up
   5. Once added open a new tab and visit `https://app,skiff.com`
   6. Click on connect wallet, Sign message popup shows up but closes the panel
   7. Click on the wallet button in Panel, keeps flashing the panel but doesn't retain
   8. Close the browser and restart, now panel shows sign message

## Actual result 

https://user-images.githubusercontent.com/17010094/174052809-f91bbf0b-3247-46ef-bf7b-138fdae5fefa.mp4

## Expected result
Should show the panel when the wallet icon is clicked

## Issue reproduces how often 
Intermittent

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Don't know
- Can you reproduce this issue with the current Play Store Nightly version? Don't know

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): PHone
   - Android version: 12
   
## Brave version
1.40.101

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @qamarngr @Pavneet-Sing @SergeyZhukovsky

**Comment by kjozwiak** [comment]
The above will require `1.40.105` or newer for `1.40.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.40.105 x64 build
- Verified steps from issue description
- Verified panel doesn't auto-close when interacting with Dapps

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/174780226-2f59a706-7915-4721-be96-897614b7c143.mp4> | <video src=https://user-images.githubusercontent.com/17010094/174780254-75bb29a8-c57e-4934-8e3a-d0b89f519cc1.mp4>
