### ISSUE TITLE
Brave Ads failed confirmations should not backoff if payment tokens are not created or not ready

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#23516]
## Description 

Brave Ads failed confirmations should not backoff if payment tokens are not created or not ready. V2 endpoints are async and therefore fetching payment tokens fails on first attempt increasing the size of the retry queue.

## Steps to Reproduce

   1. Discuss how to reproduce with @tmancey @tackley @Sneagan 

## Actual result:

Failed confirmations retries backoff if payment tokens are not created or not ready

## Expected result:
Failed confirmations should not backoff if payment tokens are not created or not ready

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by kjozwiak** [comment]
The above will require `1.40.104` or higher for `1.40.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```
Brave | 1.40.105 Chromium: 103.0.5060.53 (Official Build) (64-bit)
-- | --
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | Windows 10 Version 21H2 (Build 19044.1766)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/13824

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.40.105 Chromium: 103.0.5060.53 (Official Build) (x86_64)
-- | --
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | macOS Version 12.4 (Build 21F79)
```
