### ISSUE TITLE
[Android] `Your Brave Rewards is verified` toast notification is not shown on the BR panel

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#23519]
## Description 
Found while testing https://github.com/brave/brave-browser/issues/22508
`Your Brave Rewards is verified` notification is not shown on the BR panel
## Steps to reproduce 

   1. Follow the steps from case 7 https://github.com/brave/brave-browser/issues/22508#issuecomment-1156576542
   2. Click on the BR panel
   3. `Your Brave Rewards is verified` notification is not shown on the BR panel

## Actual result 
`Your Brave Rewards is verified` notification is not shown on the BR panel
![Screenshot_20220616-224258_Brave](https://user-images.githubusercontent.com/38657976/174135590-9aafef52-deb3-4d21-8065-21e57edbbad1.jpg)

## Expected result

![image](https://user-images.githubusercontent.com/38657976/174135100-5fba0d4a-ae8d-4f09-b4af-6e00d4753a63.png)

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung Galaxy Tab A7
   - Android version: version 11
   
## Brave version
1.40.101

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

CC: @brave/qa-team @Miyayes @deeppandya

**Comment by Miyayes** [comment]
@GeetaSarvadnya It doesn't show the toast notification for any of our custodians right? If so, then I will close this issue as resolved, given this: https://github.com/brave/brave-browser/issues/24114. Thanks!

**Comment by GeetaSarvadnya** [comment]
Gemini custodian linkage also I am not getting` Your rewards is verified toast` notification
![Screenshot_20220722-111016_Brave](https://user-images.githubusercontent.com/38657976/180371300-2c6dba62-4954-40cb-9159-ff23d75d4043.jpg)
