### ISSUE TITLE
Change Brave Ads inline content minimum viewed time

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#23525]
Change Brave Ads inline content minimum viewed time from 100 milliseconds to 1 second. An inline content ad must be viewed for at least 1 second before the user is rewarded.

**Comment by petemill** [comment]
One thing I would note is this is a feed and the ads are huge relative to the viewport vs say a small ad in a slow-scrolling page, so 1s might be a dramatic change, but maybe we can see how it goes? I guess 1s is still a short time if we want to make sure the impression has been "read" and not just scrolled past.
