### ISSUE TITLE
Enable Solana DApps support by default on desktop

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#23520]
It will remain disabled by default on Android.
Also need to aggregate test plans for all the API

**Comment by yrliou** [comment]
Reverted by https://github.com/brave/brave-core/pull/13981 due to recent crashes in nightly.

**Comment by kjozwiak** [comment]
The above will require `1.41.89` or higher for `1.41.x` verification 👍

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.41.93 Chromium: 103.0.5060.114 (Official Build) (64-bit) </th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.708)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/13825>brave/brave-core#13825</a></li>
         <li>Verified Solana Dapp support is enabled by default</li>
         <li>Verified able to connect to Dapps using Solana account and perform Sign/Transactions</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>Transactions
      </td>
      <td colspan=3>Verified as part of <a href=https://github.com/brave/brave-browser/issues/23369#issuecomment-1172477790>#23369 (comment)</a>. Also verified on RC build and seems to work fine
      </td>
   </tr>
   <tr>
      <td>Account Connect & Disconnect
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/177547836-a0ca11c0-ced9-4b9a-8faf-8d38c78c511d.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/177551268-1a7fa15b-bfd9-4bb3-950f-267d5d2a915a.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/177553514-b68e9428-f9d0-4d2b-a063-0dccf40eb3bd.mov>
      </td>
   </tr>
   <tr>
      <td>Account Connect & Lock
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/177547891-b89a5350-560f-462c-a6d2-2f74167e5f89.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/177551295-852a7681-43f5-4dcc-8ed9-35cd4fdb06c4.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/177553578-a953f606-71ea-46f0-a52d-dca28d7eb8d4.mov>
      </td>
   </tr>
   <tr>
      <td>Sign Messages
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/177547924-bde6339f-e272-44f9-9856-86e3ec28fe05.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/177551355-1c3222dd-476f-4a18-b6b4-e2bc724808d7.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/177553613-e48c5055-d48f-4ef8-ba83-9e367a7871a8.mov>
      </td>
   </tr>
   <tr>
      <td>Account Change Event
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/177547951-8658c546-7f5c-49f0-b975-ae14f9f296a6.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/177551418-da8b8a98-8dac-417c-a89a-c4b3f79d7029.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/177553452-373eab11-981b-4a96-a25e-894ef2f16a5e.mov>
      </td>
   </tr>
</table>
