### ISSUE TITLE
Add note about filecoin import format

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#23523]
## Description 
![image](https://user-images.githubusercontent.com/106654560/174140411-955b5df4-bc4c-47cb-b0d4-d03b1426e7ab.png)
Here should be a note that says about import format(hex encoded json with private key and protocol)

**Comment by kjozwiak** [comment]
The above will require `1.41.76` or higher for `1.40.x` verification 👍

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.41.82 Chromium: 103.0.5060.66 (Official Build) beta (64-bit) </th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>20b1569438a85e631d15e83eb355e3e326e5da6f-refs/branch-heads/5060@{#1066}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.708)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/13839>brave/brave-core#13839</a></li>
         <li>Verified the hex encode message is shown when clicked on Show key</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/176174418-c095f19e-90ac-4d24-9a7f-c709edf3907d.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/176174451-47aa0a9c-6fc3-4e51-bbbd-e472aec6c0c2.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/176174732-6cfcef82-3e53-4dcf-982c-478a351b283f.mov>
      </td>
   </tr>
</table>
