### ISSUE TITLE
NEAR integration (Aurora)

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#23522]
Add Aurora EVM chain to preloaded chains.

**Comment by kjozwiak** [comment]
The above will require `1.42.66` or higher for `1.42.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.42.76 x64 Beta build
- Verified Aurora is listed as one of the pre-loaded network
- Encountered [#24210](https://github.com/brave/brave-browser/issues/24210)

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | -- 
<video src=https://user-images.githubusercontent.com/17010094/180395268-eb1ec170-7b3a-42a1-9f75-d29a5facc87e.mp4> | <video src=https://user-images.githubusercontent.com/17010094/180395311-1848b0bb-6100-45d4-9aa3-47774b1d1944.mp4>

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.42.67 Chromium: 103.0.5060.114 (Official Build) beta (64-bit) </th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.708)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/14080> brave/brave-core#14080</a></li>
         <li>Verified Aurora is listed as one of the pre-loaded network</li>
         <li>Encountered <a href=https://github.com/brave/brave-browser/issues/24248>#24248</a></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/180789541-912b254c-6017-44bc-a7f0-b11b74faffb1.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/180787290-79a3abb4-4dd6-419d-a86b-c97b1a5c5be4.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/180789913-9e09d1ba-b383-44ce-8b8f-6fd5a9ff2760.mov>
      </td>
   </tr>
</table>

**Comment by srirambv** [comment]
@jamesmudgett any reason why this issue is reopened?
