### ISSUE TITLE
Extra `()` is shown on account importer screen

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23533]
## Description 

Extra `()` is shown on account importer screen

## Steps to Reproduce

   1. Install RC Build
   2. Go to wallet accounts page and click on `Import` button
   3. Select the account type, shows `( )` below the info text 

## Actual result:

https://user-images.githubusercontent.com/17010094/174258432-31cfb92a-41e9-4af5-947d-44565d02a569.mp4

## Expected result:
No extra char's 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.40.101 Chromium: 103.0.5060.42 (Official Build) (64-bit) 
-- | --
Revision | `de0d840bf9439c31bd86bf74f065c31fdf9b208d-refs/branch-heads/5060@{#667}`
OS | Windows 11 Version 21H2 (Build 22000.739)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes when 1.40.x is released
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

Note: This is fixed on 1.40.x Beta  and 1.41.x Nightly. Logged issue for tracking purpose and if we want can fix it for maintenance release or just close it when 1.41.x gets into RC Phase

Beta | Nightly
-- | --
![BEta](https://user-images.githubusercontent.com/17010094/174259122-7bd1dc27-b094-43f8-be7b-5ae82964bc0a.png) | ![Nightly](https://user-images.githubusercontent.com/17010094/174259135-3658f562-5b74-448a-89cb-c83c3f491d60.png)

**Comment by jamesmudgett** [comment]
@srirambv please update

**Comment by srirambv** [comment]
This will be fixed in 1.41.x. Will close the issue when channel migration happens. This is still a valid issue on the current 1.40.x release

**Comment by srirambv** [comment]
Keeping the issue open till channel migrations are done that way we can close the issue when Release channel is on 1.41.x as the issue is already fixed there

**Comment by srirambv** [comment]
This is fixed on 1.41.x and is already on Release channel. So closing this issue as this is invalid now.
