### ISSUE TITLE
Solana events cannot be emitted on some websites

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#23530]
When a Solana provider event is about to be fired, there will be errors on these sites
1. https://www.orca.so/
```
Uncaught TypeError: t.off is not a function
    at Object.n (2.607a4fcc.chunk.js:2:4253985)
    at Object.emit (<anonymous>:297:7)
```
2. https://magiceden.io/
```
main.ed84d7ce.js:1 Uncaught TypeError: e.off is not a function
    at Object.r (main.ed84d7ce.js:1:8579631)
    at Object.emit (<anonymous>:292:5)
```
3. https://raydium.io/
<img width="944" alt="Screen Shot 2022-06-16 at 16 07 50" src="https://user-images.githubusercontent.com/11330831/174192656-bbc9d60e-ca1e-42b7-9ddd-456b5872383e.png">

**Comment by kjozwiak** [comment]
The above requires `1.41.76` or higher for `1.41.x` verification 👍
