### ISSUE TITLE
Make Lotus link clickable under private key info

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23531]
## Description 

Make Lotus link clickable under private key info

## Steps to Reproduce

   1. Create a Filecoin account
   2. Go to Accounts and select Filecoin account
   3. Select Edit and switch to Private Key
   4. Info text has a link to support document that is not clickable

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/174230811-a6317e7d-0595-4f6d-b6bc-15231ffc08ff.png)

## Expected result:
Support links should be clickable

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.42.1 Chromium: 103.0.5060.42 (Official Build) nightly (64-bit) 
-- | --
Revision | `de0d840bf9439c31bd86bf74f065c31fdf9b208d-refs/branch-heads/5060@{#667}`
OS | Windows 11 Version 21H2 (Build 22000.739)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @cypt4 @yrliou @jamesmudgett

**Comment by kjozwiak** [comment]
The above will require `1.41.76` or higher for `1.40.x` verification 👍
