### ISSUE TITLE
Update translate code to use a redirection shim

### ISSUE THREAD

**Issue by atuchin-m** [brave/brave-browser#23538]
During secreview/[slack discussion](https://bravesoftware.slack.com/archives/C02G7LEELQK/p1654015053632779) we decided to use current google translate scripts as is via a shim to redirect requests to brave backend.
 The code/tests should be updated to use this approach.

**Comment by atuchin-m** [comment]
For QA: we also need to check here a migration from extension based translation: https://github.com/brave/brave-browser/issues/23155

**Comment by stephendonner** [comment]
There's no test plan for this or https://github.com/brave/brave-browser/issues/23155 - mind adding one @atuchin-m ?  Marking as `QA/Blocked` and `QA/Test-Plan-Required` in the interim. /cc @LaurenWags

**Comment by atuchin-m** [comment]
@LaurenWags @stephendonner We have a test plan here for all things related to translate: https://docs.google.com/document/d/1hADNy20_UIXMe2vXFrTFfpB5NCGK6hBtNVXJBYIJLds/

Currently, I seems that currently we need to make do some sanity check (without the new flag).
After we need to do detailed checking using the plan.

@rebron can provide more details.

**Comment by LaurenWags** [comment]
thanks @atuchin-m 

chatted with @rebron - he's going to grab the issue with the test plan for Google translate extension (there were a few iirc) so we can be sure we're checking the correct one.

**Comment by LaurenWags** [comment]
Labelling `QA/Blocked` pending additional information from @rebron
