### ISSUE TITLE
missing openSUSE support?

### ISSUE THREAD

**Issue by hemna** [brave/brave-browser#2354]
The installing page doesn't include instructions on how to install brave browser on openSUSE.

**Comment by kirkins** [comment]
Related #2343

**Comment by kirkins** [comment]
Just noticed that an open PR seems to have instructions for openSUSE, try this https://github.com/brave/brave-browser/pull/2233/files

**Comment by michbona** [comment]
/Even if configured correctly as in PR, installation will work once, but next day, repo will be broken by #1967

**Comment by fmarier** [comment]
Let's close this in favour of #3635 since that one has more details.
