### ISSUE TITLE
Default wallet setting to "Brave Wallet" causes some webcompat issues

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#23546]
A regression in 1.39.x is causing the login / connect operation on https://wallet.polygon.technology/ to not work. 

The regression causes this issue's work to no longer work when the user's default wallet is "Brave Wallet":
https://github.com/brave/brave-core/commit/819279a8016264f2299085632d91d4c2b3912a2b

I think it was introduced here:
https://github.com/brave/brave-core/commit/5e085ff797b6c2b59c462ce8be7760ea8d07bb38#diff-cf0cece38d73d9bb6e7593e045b9c6020641df26897c132feb56a3f10215cfd4R115

**Comment by kjozwiak** [comment]
The above will require `1.40.105` or higher for `1.40.x` verification 👍

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.40.105 Chromium: 103.0.5060.53 (Official Build) (64-bit) </th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.708)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/13854>brave/brave-core#13854</a></li>
         <li>Verified able to connect to Dapp when either <code>Brave Wallet (Prefer Extensions)</code> or <code>Brave Wallet</code> is set as default provider</li>
         <li>Verified able to logout and reconnect to Dapp without issues</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/174554106-07d5bed3-f0b9-45f2-b2e1-4014228d589a.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/174554450-72b3e74c-feac-4eaf-b07b-c471f727e01a.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/174555430-62bfb98d-81b9-48ca-944e-883488067154.mov>
      </td>
   </tr>
</table>
