### ISSUE TITLE
[hackerone] warn about possible DNS leaks when user is using a browser proxy

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#23552]
see https://bravesoftware.slack.com/archives/C01K7EDB082/p1655669298310699 for details

we will need some kind of warning when the user enables the following settings, to tell them that DNS requests will not use their proxy settings:
- [x] IPFS with the local node setting (also covered in #23570)
- [x] ENS
- [x] Unstoppable Domains
- [x] Probably DNSlink
- [ ] Aggressive mode adblocking https://github.com/brave/brave-browser/issues/23812

Suggested text for IPFS: https://github.com/brave/brave-browser/issues/23552#issuecomment-1159804437

Suggested text for everything else: `Warning: When you enable this setting and use a custom proxy, DNS requests may not go through the proxy.`

For `Aggressive mode adblocking`, this text should only show up once the user selects aggressive mode, in both the global shield settings and shields panel.

https://hackerone.com/reports/1443500
https://hackerone.com/reports/1606202

**Comment by diracdeltas** [comment]
for IPFS i am imagining that once a user selects the Local Node option, we show some text below the "Learn more" link that says `Warning: DNS requests for IPFS
<img width="723" alt="Screen Shot 2022-06-19 at 1 16 12 PM" src="https://user-images.githubusercontent.com/549654/174498868-718c34dc-63ee-408e-b1ef-5bb541217c16.png">
 will be sent using your system DNS settings instead of browser DNS settings.`

**Comment by cypt4** [comment]
Actually there is DNS configuration in go-ipfs so we can set DNS from browser-settings. But traffic to other ipfs nodes will be still uncovered by proxy.

**Comment by rebron** [comment]
Closing since resolved in https://github.com/brave/brave-browser/issues/23570 and will be resolved with https://github.com/brave/brave-browser/issues/23812

**Comment by neeythann** [comment]
@rebron @diracdeltas may you also close this https://github.com/brave/brave-browser/issues/21034 ?
