### ISSUE TITLE
DAapps: UI fixes

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#23556]
Sign Request:
- [ ] Remove tab white underline in dark mode on sign fragment

![Screenshot from 2022-06-20 22-05-53](https://user-images.githubusercontent.com/11755381/174653898-42068f3b-977e-4397-8381-fc15a6446d68.png)

- [ ] Show a gradient separator (pink-line under message on ) instead of a plain pink one
- [ ] The negative button (Cancel) should not have a primary (blue) background and have click effect

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.42.67 x64 build
- Verified steps from [brave/brave-core#13987](https://github.com/brave/brave-core/pull/13987)
- Verified gradient shown on tabs in various screens

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/180952949-b83570f4-6f4b-44fb-aab3-e2d92fd59640.mp4> | <video src=https://user-images.githubusercontent.com/17010094/180953013-44c0b8d4-990f-4077-beb4-6280dc8f4b95.mp4>
