### ISSUE TITLE
DApps: Fix address placement in the account switcher, address partially moved to next line when selected

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#23558]
https://bravesoftware.slack.com/archives/C02SC5AKTAS/p1655379158901509?thread_ts=1653566500.573419&cid=C02SC5AKTAS

![Screenshot from 2022-06-23 17-35-19](https://user-images.githubusercontent.com/11755381/175295561-3e5a9c2f-9add-4ace-a979-897aad78970c.png)

https://user-images.githubusercontent.com/11755381/175294475-3020ebc9-eb0f-46ca-adf3-0803b7646ecd.mp4

**Comment by Pavneet-Sing** [comment]
Dropping this to prioritise Solana implementation

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.42.80 x64 build
- Verified steps from [brave/brave-core#13968](https://github.com/brave/brave-core/pull/13968)
- Verified selecting an account doesn't affect the address placement


https://user-images.githubusercontent.com/17010094/181466150-051785bc-c769-46e8-a5dd-c69fef505e98.mp4
