### ISSUE TITLE
Open image in a new tab from Reddit crashes Brave

### ISSUE THREAD

**Issue by Heclalava** [brave/brave-browser#23561]
## Description 
 When I right click an image on Reddit and want to open it in a new tab the browser crashes. 

## Steps to Reproduce

   1. Right click image
   2. Click open image in a new tab
   3. Browser crashes

## Actual result:
 Refer to uploaded screen record. 

## Reproduces how often: 
 Happens every time.

## Brave version (brave://version info)

Brave | 1.39.122 Chromium: 102.0.5005.115 (Official Build) (64-bit)
-- | --
Revision | 174dbe6e33bc81994fceb71d751be201d0b4803d-refs/branch-heads/5005_109@{#3}
OS | Linux
JavaScript | V8 10.2.154.8
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.115 Safari/537.36
Command Line | /opt/brave.com/brave/brave --enable-crashpad --disable-client-side-phishing-detection --disable-domain-reliability --enable-dom-distiller --no-pings --component-updater=url-source=https://go-updater.brave.com/extensions --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --variations-insecure-server-url=https://variations.brave.com/seed --flag-switches-begin --flag-switches-end
Executable Path | /opt/brave.com/brave/brave
Profile Path | /home/master/.config/BraveSoftware/Brave-Browser/Default
Variations | AdRewardsStudy:NextPaymentDayAdServingStudy:DefaultAdNotificationsPerHour=10/MaximumAdNotificationsPerDay=100/MaximumInlineContentAdsPerHour=12/MaximumInlineContentAdsPerDay=60BraveAds.UserActivityStudy:Triggers=EMPTY/Threshold=0.0/IdleTimeThreshold=5BraveDebounceStudy:EnabledConversionsStudy:NewDefaultPatternDefault1pBlockingStudy:DisabledEphemeralStorageStudy:EnabledExtendedVariationsSafeMode5:SignalAndWriteViaFileUtil5FirstPartyEphemeralDomainBlockStudy:EnabledForceDisableBlinkFeatures:EnabledNativeCosmeticFilteringStudy:EnabledNavigationThreadingOptimizationsCompat:DefaultPartitionBlinkMemoryCacheStudy:EnabledPartitionConnectionsByNetworkIsolationKeyStudy:EnabledPermissionLifetimeReleaseStudy:EnabledRequestAdsEnabledApiStudy:EnabledSpeedreaderReleaseStudy:Enabled

## Version/Channel Information:

https://user-images.githubusercontent.com/8341359/174691982-76312e64-e4a2-4c5d-848c-1c39236897a3.mp4

**Comment by rebron** [comment]
Hi @Heclalava. Can you update to our latest 1.40.107 and let us know if you're still experiencing the crash.

**Comment by Heclalava** [comment]
I actually ended up switching to the flatpak version in the end which seems
fine. Before that it did update once (uncertain of the version number) and
still crashed. I decided to test to see if the flatpak version worked which
it did, so I left it on that.

**Comment by Nerae** [comment]
Same thing happening to me, typing brave --version into console gives Brave Browser 105.1.43.89
I'm using the AUR package brave-bin, happens just as the OP describes at the same frequency. Flatpak version seems to work fine too, but I'd like if this version was fixed up somehow.
