### ISSUE TITLE
Maker/taker assets in Swap transactions are incorrectly read as ETH

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#23565]
Transaction parser for `ETHSwap` incorrectly reads maker/taker asset as always `ETH`. It's reproducible every time the maker/taker assets are not part of visible tokens, even though they are present in the full tokens list.

<img src="https://user-images.githubusercontent.com/3684187/174712126-33f8f7e3-bc05-4ccc-ab78-5232d0d95480.png">

To reproduce, use matcha.xyz to build a swap transaction and make sure the taker asset is not present in the visible tokens list.

**Comment by kjozwiak** [comment]
Cleaned up https://github.com/brave/brave-core/pull/18697 as it originally pointed to only https://github.com/brave/brave-browser/issues/30703 but should have also included this issue as per https://github.com/brave/brave-browser/issues/30703#issuecomment-1571342523. Removed https://github.com/brave/brave-browser/issues/30703 from labels/milestones as verification will be done with the above issue.

**Comment by kjozwiak** [comment]
The above requires `1.52.124` or higher for `1.52.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.52.125 Chromium: 114.0.5735.110 (Official Build) (64-bit)
-- | --
Revision | `1c828682b85bbc70230a48f5e345489ec447373e-refs/branch-heads/5735_90@{#13}`
OS | Windows 11 Version 22H2 (Build 22621.1778) 

- Verified steps from [brave/brave-core#18299](https://github.com/brave/brave-core/pull/18299)
- Verified unknown token show `???` in panel and in activity tab
- Verified clicking on `View on block explorer` loads the token details page on respective block explorer

https://github.com/brave/brave-browser/assets/17010094/ae94540d-093e-45bc-be07-3f3729ae9579
