### ISSUE TITLE
"Automatically redirect .onion sites" is not disabled with Tor

### ISSUE THREAD

**Issue by rillian** [brave/brave-browser#23560]
## Description 

The "Automatically redirect .onion sites" preference stays enabled and clickable even when "Private window with Tor" is disabled. This is confusing because it implies onion-alternate sites will continue to redirect when this is not the case.

Looks like a regression of https://github.com/brave/brave-browser/issues/17363 possibly because a [variable was renamed](https://github.com/brave/brave-core/commit/61e6ed1a5943d6d87c52d536ae7f6174227786be)?

## Steps to Reproduce

   1. Launch Brave
   2. Visit brave://settings/extensions
   3. Enable "Automatically redirect .onion sites"
   4. Disable "Private window with Tor"

## Actual result:
Onion pref is still set and allows interaction

![screenshot showing the still enabled pref](https://user-images.githubusercontent.com/225102/174682683-949fb154-bb37-4033-96b9-6cdf081836fe.png)

## Expected result:
I believe the original design was for it to gray out when Tor was disabled.
![original design screenshot](https://user-images.githubusercontent.com/20608253/128377459-53723efa-4f4a-40fa-bb57-641dbec753cc.png)

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave: 1.40.96 Chromium: 102.0.5005.115 (Official Build) beta (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.43.56 Chromium: 104.0.5112.81 (Official Build) dev (x86_64)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | macOS Version 11.6.8 (Build 20G730)



install 1.43.56
launch Brave
opened `brave://settings/extensions`
confirmed `Private window with Tor` is `Enabled` by default
confirmed `Automatically redirect .onion sites` was `Disabled` by default
toggled `Private window with Tor` to `Disabled`
confirmed `Private window with Tor` is now `Disabled`
confirmed `Automatically redirect .onion site` is `Disabled` and ghosted/greyed out
toggled `Private window with Tor` back to `Enabled`
toggled `Automatically redirect .onion sites` to `Enabled`
toggled `Private window with Tor` back to `Disabled`
confirmed `Automatically redirect .onion sites` is set to `Enabled` but is ghosted/greyed out




Migration

install 1.41.100
launch Brave
opened `brave://settings/extensions`
toggle `Private window with Tor` to `Disabled`

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.43.91 Chromium: 105.0.5195.102 (Official Build) (64-bit)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | Windows 11 Version 21H2 (Build 22000.856)
```
### Case one, new profile:

1. install 1.43.91
2. launch Brave
3. opened `brave://settings/extensions`
4. confirmed `Private window with Tor` is `Enabled` by default
5. confirmed `Automatically redirect .onion sites` was `Disabled` by default
6. toggled `Private window with Tor` to `Disabled`
7. confirmed `Private window with Tor` is now `Disabled`
8. confirmed `Automatically redirect .onion site` is `Disabled` and ghosted/greyed out
9. toggled `Private window with Tor` back to `Enabled`
10. toggled `Automatically redirect .onion sites` to `Enabled`
11. toggled `Private window with Tor` back to `Disabled`
12. confirmed `Automatically redirect .onion sites` is set to `Enabled` but is ghosted/greyed out
13. clicked on this greyed out state and can't be toggled 

step 4 | step 5| steps 6-7|step 8|step 9| steps 10 | step 11-12
-------|------|-----|-----|------|------|------
<image width="900" alt="step4" src="https://user-images.githubusercontent.com/98358127/189445689-f9787981-bc6e-4de1-be7a-b715af49a8a6.png">|<image width="900" alt="step 5" src="https://user-images.githubusercontent.com/98358127/189445762-0342f843-7ecb-4726-9e43-abdbfc7bddee.png">|<image width="900" alt="step6-8" src="https://user-images.githubusercontent.com/98358127/189443584-31b73919-6f05-42a9-83ed-765d80bb2d28.png">|<image width="900" alt="step4" src="https://user-images.githubusercontent.com/98358127/189444317-b60fb2d5-2c24-4ad4-abfc-b3218209eddb.png">|<image width="900" alt="step6-8" src="https://user-images.githubusercontent.com/98358127/189443748-78f03623-ed4f-4646-b098-f9df054f3b10.png">|<image width="900" alt="step4" src="https://user-images.githubusercontent.com/98358127/189445159-8b5f11b7-6bb3-40bf-b3d2-258fcf9ce9a4.png">|<image width="900" alt="step4" src="https://user-images.githubusercontent.com/98358127/189445266-accf09d5-c40b-4cd1-8a2d-b43d033bf203.png">

### Case two, migration:

1. installed `1.42.97`
2. launched Brave
3. opened `brave://settings/extensions`
4. toggle `Private window with Tor` to `Disabled`
5. installed `1.43.91`
6. launch Brave
7. confirmed both `Private window with Tor` and `Automatically redirect .onion sites` were `Disabled`
8. additionally, confirmed `Automatically redirect .onion sites` was ghosted/greyed out
9. clicked on this greyed out state and can't be toggled 

`1.42.97` | `1.43.91`
----------|---------
<image width="900" alt="step4" src="https://user-images.githubusercontent.com/98358127/189456142-9611c261-9797-4305-aa06-3e077f363514.png">|<image width="900" alt="step4" src="https://user-images.githubusercontent.com/98358127/189456457-f2fbcda9-a52e-4a7d-a36b-79eec744c683.png">
