### ISSUE TITLE
Unlimited ERC20 allowance is incorrectly displayed in transaction history

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#23562]
<img src="https://user-images.githubusercontent.com/3684187/174707762-2fc08e70-f24d-4f0b-ac7f-98cb555d7c2c.png">

Should display "Unlimited".

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.40.107 Chromium: 103.0.5060.53 (Official Build) (64-bit) </th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.708)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/13873>brave/brave-core#13873</a></li>
         <li>Verified transaction details shows <code>Unlimited</code> instead of the full value</li>
         <li>Encountered <a href=https://github.com/brave/brave-browser/issues/23666>#23666</a></li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/175501007-51b57c11-eed3-424e-b920-ab3024e5dab3.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/175498154-3a010c4e-e7e6-477d-bfa5-7b175c1d4c16.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/175502134-36f18e2c-217a-4d67-a09e-0e713480daf1.png>
      </td>
   </tr>
</table>
