### ISSUE TITLE
A way for brave wallet to work with iframe(Cross-origin)

### ISSUE THREAD

**Issue by omarsy** [brave/brave-browser#23572]
## Description 
I have seen that now brave Wallet does not work in iframe that do not have the same origin as its parent. 
Maybe we need to have a way to disable this behaviour.

Maybe we should provide a function to disable it or in the iframe have an allow-wallet attribute.

## Desktop Brave version:

after this fix (https://github.com/brave/brave-browser/issues/22686)

**Comment by diracdeltas** [comment]
we actually have a spec for this that @bbondy is working on

**Comment by omarsy** [comment]
Do you know when this feature will be available?
Sorry to ask you this question, it's to know if I'm going to develop my own workaround or not  
@diracdeltas @bbondy

**Comment by bbondy** [comment]
I'll have a PR up within the next couple days.  iframes will need an allow="ethereum" if it is cross origin for it to work.

**Comment by bbondy** [comment]
Implemented as part of this issue https://github.com/brave/brave-browser/issues/23710
