### ISSUE TITLE
[hackerone] dev tool console leak in Tor window

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#23579]
https://hackerone.com/reports/1605654

**Comment by kjozwiak** [comment]
The above will require `1.41.80` or higher for `1.41.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.41.80 Chromium: 103.0.5060.53 (Official Build) beta (x86_64)
-- | --
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | macOS Version 11.6.7 (Build 20G630)

First, confirmed issue using `1.40.105`

example | example
---------|---------
<img width="1312" alt="Screen Shot 2022-06-27 at 12 45 54 PM" src="https://user-images.githubusercontent.com/387249/176023298-8cc146ae-ad95-475c-8077-51a3ecb9e714.png"> | <img width="1312" alt="Screen Shot 2022-06-27 at 12 46 12 PM" src="https://user-images.githubusercontent.com/387249/176023318-611cea61-8fe3-4b91-8f18-b52447c530ee.png">


### Steps:

1. installed 1.41.80
2. clicked on the "hamburger" menu
3. clicked on `New Private Window with Tor`
4. opened `Developer Tools`
5. clicked on the `Console` panel
6. typed `a=123` and pressed `return`
7. clicked on the "hamburger" menu
8. clicked on "New Window"
9. clicked on the `Console` panel
10. pressed the arrow-up key ⬆️ 

### Confirmed no history of previous entry shown

example | example
---------|---------
<img width="1312" alt="Screen Shot 2022-06-27 at 12 35 07 PM" src="https://user-images.githubusercontent.com/387249/176022279-01f300d6-5161-4214-a6f2-06ce63c9bcdf.png"> | <img width="1312" alt="Screen Shot 2022-06-27 at 12 35 34 PM" src="https://user-images.githubusercontent.com/387249/176022287-6a7c0cb3-f9d7-4e64-8b83-b67eb7b3189a.png">

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.41.80 Chromium: 103.0.5060.53 (Official Build) beta (64-bit)
-- | --
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | Linux

### Steps:

1. installed 1.41.80
2. clicked on the "hamburger" menu
3. clicked on `New Private Window with Tor`
4. opened `Developer Tools`
5. clicked on the `Console` panel
6. typed `a=123` and pressed `return`
7. clicked on the "hamburger" menu
8. clicked on "New Window"
9. clicked on the `Console` panel
10. pressed the arrow-up key ⬆️ 

### Confirmed no history of previous entry shown

example | example
---------|---------

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.41.86 Chromium: 103.0.5060.66 (Official Build) beta (64-bit)
-- | --
Revision | 20b1569438a85e631d15e83eb355e3e326e5da6f-refs/branch-heads/5060@{#1066}
OS | Windows 11 Version 21H2 (Build 22000.739)
```
Reproduced the issue in `1.40.109`

TOR window|Normal window
----|---
<img width="958" alt="image" src="https://user-images.githubusercontent.com/98358127/176946886-8b0cfbad-b2c8-4864-b93d-0976b82b2db8.png">|<img width="953" alt="image" src="https://user-images.githubusercontent.com/98358127/176947460-f1e40fd6-d0b7-4783-8325-398621dbcd5b.png">

### Steps:

1. installed 1.41.86
2. clicked on the "hamburger" menu
3. clicked on `New Private Window with Tor`
4. opened `Developer Tools`
5. clicked on the `Console` panel
6. typed `a=123` and pressed `return`
7. clicked on the "hamburger" menu
8. clicked on "New Window"
9. clicked on the `Console` panel
10. pressed the arrow-up key ⬆️ 

### Confirmed no history of previous entry shown

TOR window|Normal window
----|---
<img width="954" alt="image" src="https://user-images.githubusercontent.com/98358127/176947074-8ba1833f-5391-48fe-9d7a-aeb54604fecc.png">|<img width="954" alt="image" src="https://user-images.githubusercontent.com/98358127/176947223-f7a547d3-3f22-4880-bd76-e5dba00bfae8.png">
