### ISSUE TITLE
Unable to connect to bsc.cryptoz.cards

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#23571]
## Description 
Unable to connect to bsc.cryptoz.cards

Console Log: 
```
code: -32000
message: "etherbase must be explicitly specified"
```

https://user-images.githubusercontent.com/40611140/174812916-5156e00c-8497-4faf-a26b-df9b11c51091.mov

**Comment by bbondy** [comment]
I found out why.

The website uses `eth_coinbase`

For `eth_coinbase`, we pass it on to our EVM RPC endpoint. But MetaMask returns the first connected account (or null if the wallet is locked or there is no connected account). 

We need to do the same as MetaMask here.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.45.88 Chromium: 106.0.5249.91 (Official Build) beta (64-bit) 
-- | --
Revision | `fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}`
OS | Linux

- Verified steps from issue description
- Verified able to connect to `https://bsc.crptoz.cards` on BSC network without issues
- Verified works similar to how MM works with the site

https://user-images.githubusercontent.com/17010094/194632944-303c1d76-f835-4613-af2d-e455d9c88e91.mp4

------------------------
Verification passed on

Brave | 1.45.88 Chromium: 106.0.5249.91 (Official Build) beta (64-bit) 
-- | --
Revision | `fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}`
OS | Windows 11 Version 21H2 (Build 22000.978)

- Verified steps from issue description
- Verified able to connect to `https://bsc.crptoz.cards` on BSC network without issues
- Verified works similar to how MM works with the site

https://user-images.githubusercontent.com/17010094/194632322-5a579659-8123-4b50-9ca2-b9ff01c7cdfa.mp4

------------------------
Verification passed on

Brave | 1.45.88 Chromium: 106.0.5249.91 (Official Build) beta (arm64)
-- | --
Revision | `fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from issue description
- Verified able to connect to `https://bsc.crptoz.cards` on BSC network without issues
- Verified works similar to how MM works with the site

https://user-images.githubusercontent.com/17010094/194635474-d7a0480d-0b45-4c56-902f-fa795a843b17.mov
