### ISSUE TITLE
Make a standalone .deb file available for download on website

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#2357]
Based on [a comment](https://github.com/brave/brave-browser/issues/2264#issuecomment-444212867) in #2264, there's value in making our `.deb`s available for download on the website. Though there remains an open question of how a standalone deb should set up the `apt` repo and keyring.

**Comment by fmarier** [comment]
The latest `.deb` (and `.rpm`) packages are always available from https://github.com/brave/brave-browser/releases. Maybe we just need to publicize this?

**Comment by fmarier** [comment]
Related: https://github.com/brave/brave-browser/issues/1290

**Comment by yasharya2901** [comment]
Yes, making a deb file would be much easier experience for newbies who are new to Linux and are accustomed to download in Windows way. Also, how come Edge and Chrome does it, just asking.

**Comment by fmarier** [comment]
Let's close this in favour of https://github.com/brave/brave-browser/issues/9050 which has more details as to what needs to happen.
