### ISSUE TITLE
Support eth_signTransaction

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#23582]
This issue is to add support of eth_signTransaction provider API, see eth_signTransaction at https://ethereum.github.io/execution-apis/api-documentation/.
Just for reference, https://web3js.readthedocs.io/en/v1.2.11/web3-eth.html#signtransaction for interface defined by web3.js.

Testing app provided by mistx:
https://github.com/juice0x/test-mistx-transaction-app
In this repo there's a test for signing an eth:usdc swap with signTransaction as well as a sample app to test in the browser environment. the code in the test is an example of working code however it will fail due to the mock provider not supporting signTransaction. it should succeed with a provider that supports it.

cc @bbondy

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.48.151 Chromium: 109.0.5414.119 (Official Build) beta (64-bit)
-- | --
Revision | `772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#16247](https://github.com/brave/brave-core/pull/16247)
- Verified signed transaction changes to confirmed when `eth_sendRawTransaction` goes through
- Verified one of the signed transaction drops when there are two of them and one of them gets confirmed
- Encountered [#28205](https://github.com/brave/brave-browser/issues/28205)

Normal Flow | Nonce drop
-- | --
<video src=https://user-images.githubusercontent.com/17010094/216590661-50490d3f-93f7-4412-b129-799c8799ec4d.mp4> | <video src=https://user-images.githubusercontent.com/17010094/216590645-73dbe60d-5dca-4f87-9063-bdb14e01246c.mp4>

**Comment by srirambv** [comment]
Removing `OS/Android` label as there is an Android specific issue that is logged https://github.com/brave/brave-browser/issues/28363
