### ISSUE TITLE
Need new Rewards and Shields panels

### ISSUE THREAD

**Issue by rossmoody** [brave/brave-browser#2358]
New panel designs for Rewards and Shields to account for missing states in relation to when the user sets Rewards to "Off", when a user is in a Private Window, and when a user is on a Brave System Page.

![brave action bar behavior](https://user-images.githubusercontent.com/29072694/49768104-fa9e4780-fc8f-11e8-8aab-8b584f9d0b15.png)

**Comment by LaurenWags** [comment]
@rossmoody - related to https://github.com/brave/brave-core/pull/1034 for https://github.com/brave/brave-browser/issues/2214 ?

**Comment by rossmoody** [comment]
@LaurenWags exactly right. Since there are a ton of issues and updates related to omnibox brave element behavior, I’ll put together a comprehensive spec today we can point to

**Comment by rossmoody** [comment]
Getting ducks in a row, reviewing as a larger team and will circle back with more concise direction on Brave Action item behavior/styling.
