### ISSUE TITLE
New tab changing

### ISSUE THREAD

**Issue by beebonius** [brave/brave-browser#23595]
Why can't I outright change what page I want to see when I open a new tab? I like the Brave homepage, but I'd like to set a different website to pop up when I open a new tab.

**Comment by rebron** [comment]
Hi @beebonius You can go to brave://settings/newTab and choose what you want to see there. If you want to specify a url, enable homepage button and set your url preference in brave://settings/appearance in the enter custom web address section. You can hide the home page button or keep it there.

I'm going to go ahead and close this one out. If you have any other questions about Brave or other issues community.brave.com is a great place for it.
