### ISSUE TITLE
Solana dApp compatibility bug when signing a swap transaction with Raydium

### ISSUE THREAD

**Issue by kdenhartog** [brave/brave-browser#23594]
1. go to https://raydium.io/swap/
2. add RPC [api.testnet.solana.com](http://api.testnet.solana.com/)
3. connect wallet
4. Switch wallet to testnet in wallet
5. try to do a swap and get a WalletSignTransactionError

![image](https://user-images.githubusercontent.com/23125059/174925505-3f6540c5-d1ea-4482-9428-ccdab618f059.png)

cc @jamesmudgett @bbondy this is that one webcompat one I came across when sec testing today

**Comment by yrliou** [comment]
For these swap transactions, they provide a signature in the dapp transaction, besides providing the connected account's signature, we also need to keep those signatures filled by dapp transactions.

**Comment by kjozwiak** [comment]
The above will require `1.41.89` or higher for `1.41.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.41.91 Chromium: 103.0.5060.114 (Official Build) beta (64-bit) 
-- | --
Revision | `a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}`
OS | Windows 11 Version 21H2 (Build 22000.739)

- Verified test plan from [brave/brave-core#14001](https://github.com/brave/brave-core/pull/14001)
- Verified able to Swap SOL -> USDC on both `https://radiyum.io/` and `https://orca.so/`

Raydium | Orca
-- | --
<video src=https://user-images.githubusercontent.com/17010094/177326732-3b715aa4-c471-4257-ae4b-b3837cb974ce.mp4> | <video src=https://user-images.githubusercontent.com/17010094/177326673-20bd8fcd-97b9-4d04-aab8-26465fed6937.mp4>
