### ISSUE TITLE
Buy with Wyre links for Polygon & AVAX are incorrect

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#23591]
## Description 

Links opened from Buy With Wyre button do not have the correct destination value (chain) set

## Steps to Reproduce

   1. Unlock Wallet
   2. Select Avalanche or Polygon network
   3. Select Buy tab
   4. Select USDC or AVAX
   6. Select buy with Wyre
   7. Opened URL has an incorrect destination of "ethereum" & the selected buy asset is incorrect
 

## Actual result:

https://user-images.githubusercontent.com/30185185/174915296-9553c1e8-dade-4fde-b58c-7d057f84c4c5.mov

https://user-images.githubusercontent.com/30185185/174915305-cdaca575-2fce-4e4f-a88f-cb08f0aa9831.mov

## Expected result:
Opened URL has the correct destination and token symbol values

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by HEagle18** [comment]
@muliswilliam do we close this now as Wyre is no longer supported ?

**Comment by muliswilliam** [comment]
@HEagle18 Closing it now
