### ISSUE TITLE
Learn more text is missing in the welcome onboarding screen if Brave is already default

### ISSUE THREAD

**Issue by tapanmodh** [brave/brave-browser#23598]
## Description 
1. Learn more text is missing in the welcome onboarding screen if Brave is already default.
2. Change set default logic:
Check set default for release channel with regards to only release channel. So If on Brave release channel build, check if Brave release channel is default or not. 
For beta and nightly channel, check if any of the brave channel is default or not

## Steps to reproduce 

   1. Install brave beta or nightly build
   2. Set brave as default without opening the newly installed build
   3. Open the newly installed build and go through the welcome onboarding screen. In the p3a screen, Learn more text is missing

## Actual result 

![Screenshot_20220622_143413](https://user-images.githubusercontent.com/11678818/174989909-3746b09a-d703-4afd-af4d-bc34860f1afd.png)

## Expected result

![Screenshot_20220622_143258](https://user-images.githubusercontent.com/11678818/174990090-f7292b39-467f-437c-a072-e32822cb14f5.png)

## Issue reproduces how often 
Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes 
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): Arm
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 11
   
## Brave version
Beta `1.41.74`
Nightly `1.42.12`

**Comment by Uni-verse** [comment]
Verified on Samsung GS 21 & Tab S7 using
