### ISSUE TITLE
A crash on checking for a badge

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#23604]
```
java.lang.NullPointerException: 
  at org.chromium.brave_wallet.mojom.BraveWalletService_Internal$BraveWalletServiceGetPendingSignMessageRequestsResponseParams.run (BraveWalletService_Internal.java:405)
  at android.os.Handler.handleCallback (Handler.java:883)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7386)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:492)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:980)
```

There is a crash I see in a Google Play Console. I cannot replicate it, but it looks like it's related to showing a badge on a wallet icon. It's possible that a call to mojo services are done to get any pending requests when native isn't ready yet.
So to fix it I'm going to do:
1. Call it only from a place when we are 100% that native is ready
2. Call it only when a wallet icon is visible as now it's called all the time on `onResume`.

### Test Plan

**Trigger badge on wallet icon**

Test Case 1:
* Visit `https://chainlist.org` and connect wallet
* Click on `Add network` 
* Close the wallet popup, badge is shown on wallet
* Background the browser and relaunch, ensure no browser crash

Test Case 2:
* Visit `https://app.skiff.com`
* Click on `Login with Brave Wallet`
* Continue with account permission
* Close the panel popup when the sign message is shown
* Wallet should have a badge shown
* Background the browser and relaunch, ensure no browser crash
* Quit the browser and restart, wallet should still show the badge and no crash when relaunching the browser

Test Case 3:
* Visit `https://metamask.github.io/test-dapp`
* Click on Connect and connect the wallet
* Click on `Get Encryption key`
* Close the panel popup and close the browser
* Restart the browser, wallet icon should be shown with badge and no crash when relaunching the browser

**Comment by LaurenWags** [comment]
Verification in progress on Asus Zenfone (x86) with Android 6 running 1.40.106

**Comment by LaurenWags** [comment]
Verification in progress on Samsung J7 Neo with Android 7 running 1.40.106

Test Case 1 - InProgress
* Create wallet, lock wallet
* Visit `https://chainlist.org` and connect wallet
* Scroll to something down on list (like Moonriver) and click on `Add to Brave` 
* When "Allow this site to add a network?" popup shows up, use Android "back" button to close popup
* Confirm badge is shown on wallet icon
* Background the browser and relaunch, ensure no browser crash

Test Case 2 - TBD
* Visit `https://app.skiff.com`
* Click on `Login with Brave Wallet`
* Continue with account permission
* Close the panel popup (using Android back button) when the sign message is shown
* Wallet should have a badge shown
* Background the browser and relaunch, ensure no browser crash and wallet icon still shows badge
* Quit the browser and restart, no crash when relaunching the browser (no wallet icon displayed, no badge displayed)

Test Case 3 - TBD
* Visit `https://metamask.github.io/test-dapp`
* Click on Connect and connect the wallet
* Click on `Get Encryption key`
* Close the panel popup (using Android back button) and background the browser
* Reopen the browser, wallet icon should be shown with badge and no crash when bringing the browser to foreground
* Quit the browser and restart, no crash when relaunching the browser (no wallet icon displayed, no badge displayed)

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave `1.40.106, Chromium 103.0.5060.53` on a `Google Pixel XL` (`arm64`) running `Android 9.0.`

### Test Case 1 - PASSED

1. Create wallet, lock wallet
2. Visit https://chainlist.org and connect wallet
3. Scroll to something down on list (like Moonriver) and click on Add to Brave
4. When "Allow this site to add a network?" popup shows up, use Android "back" button to close popup
5. Confirm badge is shown on wallet icon
6. Background the browser and relaunch, ensure no browser crash


https://user-images.githubusercontent.com/387249/175137176-2e9a99f6-154a-440c-9094-c300fc80312a.mp4



### Test Case 2 - PASSED

1. Visit https://app.skiff.com
2. Click on Login with Brave Wallet
3. Continue with account permission
4. Close the panel popup (using Android back button) when the sign message is shown
5. Wallet should have a badge shown
6. Background the browser and relaunch, ensure no browser crash and wallet icon still shows badge
7. Quit the browser and restart, no crash when relaunching the browser (no wallet icon displayed, no badge displayed)
8. 

https://user-images.githubusercontent.com/387249/175137448-bc2687cf-fc68-40ed-b2de-e2e79ad6ec5f.mp4



### Test Case 3 - PASSED

1. Visit https://metamask.github.io/test-dapp
2. Click on Connect and connect the wallet
3. Click on Get Encryption key
4. Close the panel popup (using Android back button) and background the browser
5. Reopen the browser, wallet icon should be shown with badge and no crash when bringing the browser to foreground
6. Quit the browser and restart, no crash when relaunching the browser (no wallet icon displayed, no badge displayed)


https://user-images.githubusercontent.com/387249/175137569-1feb4c6c-5a43-456f-8658-6beddca76aea.mp4

**Comment by Uni-verse** [comment]
Verified on Samsung GS 21 5G using 

```
Brave	1.40.106 Chromium: 103.0.5060.53 (Official Build) (32-bit) 
Revision	a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS	Android 12; Build/SP1A.210812.016
```
- Confirmed crash is not reproducible for all test cases in https://github.com/brave/brave-browser/issues/23604#issuecomment-1163576104
- Confirmed badge is being displayed when there is wallet request is active
- Confirmed wallet icon and badge is not displayed when restarting browser unless requests are not sent in UI (TC3)

<table><tr><td>

https://user-images.githubusercontent.com/17885425/175138099-3226e325-9df6-4f86-ac7d-9b9981ef0b4a.mp4

</td><td>

https://user-images.githubusercontent.com/17885425/175138269-c38084bb-39ca-4df8-ac5b-da0f8c287bb8.mp4

</td><td>

https://user-images.githubusercontent.com/17885425/175138474-ab5b213f-4b1f-46c3-9e7c-beb9425901b5.mp4

</td></tr></table>
