### ISSUE TITLE
Folder structure is not in sync and all the BM's are added outside the folders in Bravecore

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#2360]
## Description 
Found this issue while testing #2144
Folder structure is not in sync and all the BM's are added outside the folders in Bravecore

## Devices
Device 1: Desktop Rrelease (sync chain creator)
Device 2: Gionee Android (Android 5.1)

## Steps to Reproduce

   1. Enable Sync on desktop
   2. Sync Android using code word
   3. Bookmark site1 and add it to folder A.
   4. Bookmark site 2 and add it to folder B, which is created inside the folder A
   5. Bookmark site 3 and add it to folder C, which is created inside the folder B
   6. Create a folder on desktop and BM few sites into it
   7. Desktop folder never synced in Android

## Actual result:
- Folders A, B, C are displayed one after the other and folders and empty. all the BM'ed sites added outside the folders 
- Desktop folder never synced in Android
![image](https://user-images.githubusercontent.com/38657976/49477061-b818dd00-f841-11e8-92e4-3050b3ba30d9.png)

## Expected result:
- Folders should be inside the one another (A->B->C) and should have specific BM's inside the folder
- Desktop folder should sync in Android

![image](https://user-images.githubusercontent.com/38657976/49472020-674eb780-f834-11e8-9517-b6c673977a17.png)

## Reproduces how often: 
Always

## Brave version (brave://version info)

Brave | 0.57.12 Chromium: 71.0.3578.75 (Official Build) (64-bit)
-- | --
Revision | 06ef00b5279f93f8e0c1e73acedd49d7dcc09767-refs/branch-heads/3578@{#836}
OS | Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? NA

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by GeetaSarvadnya** [comment]
Console error:

![image](https://user-images.githubusercontent.com/38657976/49476841-12fe0480-f841-11e8-8e36-4ed502cfc4b1.png)

**Comment by darkdh** [comment]
fixed in https://github.com/brave/brave-core/pull/1037
