### ISSUE TITLE
Tooltip text for Brave Search omnibox promo close widget is too geeky

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#23607]
## Description 

Tooltip text for Brave Search omnibox promo close widget is too geeky

## Steps to Reproduce

1. installed `1.41.76`
2. launched Brave using `--enable-features=BraveSearchOmniboxButton` command-line switch
3. set `Search engine used in the address bar` to `DuckDuckGo`
4. typed `brunch`
5. hovered over the `X` widget
6. read the tooltip text

## Actual result:

`Dismiss brave search conversion`

<img width="1203" alt="Screen Shot 2022-06-22 at 9 32 41 AM" src="https://user-images.githubusercontent.com/387249/175090439-a2ffabbe-b08a-43d4-a189-c93c934f1d70.png">

## Expected result:

Something like `Close Brave Search promotion` (@rmcfadden3 help wordsmithing?) 

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.41.76 Chromium: 103.0.5060.53 (Official Build) beta (x86_64)
-- | --
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | macOS Version 11.6.7 (Build 20G630)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `No`
- Can you reproduce this issue with the nightly channel? `Yes`

cc @rmcfadden3 @aguscruiz @jenn-rhim

**Comment by rebron** [comment]
@rmcfadden3 Dismiss here will function more like a "Don't show this again"

**Comment by rmcfadden3** [comment]
@rebron & @stephendonner — I'm good with the "Don't show this again" text. It makes sense here, and also saves us on localization.
