### ISSUE TITLE
Follow up of PR #13566 - Incorrect response value for `Brave.Search.Promo.Button` when default SE is changed via search engine results page

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#23602]
## Description 

Found while testing https://github.com/brave/brave-core/pull/13566
Follow up of PR #13566 - Incorrect response value for `Brave.Search.Promo.Button` when default SE is changed via search engine results page
## Steps to Reproduce

   1. Clean profile 1.42.x , launch brave using brave.exe --enable-logging=stderr --enable-features="BraveSearchOmniboxButton
   2. Open brave://local-state file
   3. Search for the metric Brave.Search.Promo.Button
   4. Ensured metric is not shown in the brave://local-state file
   5. Navigate to brave://settings/search
   6. Change the search engine to something other than Brave
   7. Enter some random text in the Omnibox and ensured the button promo appears in the suggestions
   8. Click on the promo
   9. Change the default SE to brave by clicking on the prompt that appears on the search engine results page
  10. Reload the brave://local-state page
  11. Confirmed that the metric `Brave.Search.Promo.Button` response value is `3` instead of `2`
  

## Actual result:

The metric `Brave.Search.Promo.Button` response value is `3` instead of `2`

## Expected result:
the metric `Brave.Search.Promo.Button` response value should be `2`

## Brave version (brave://version info)

Brave | 1.42.16 Chromium: 103.0.5060.53 (Official Build) nightly (64-bit)
-- | --
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | Windows 10 Version 21H2 (Build 19044.1766)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @DJAndries @mattmcalister @brave/qa-team

**Comment by DJAndries** [comment]
Closing as invalid. The value 3 is the correct if you have clicked on the promo and changed your default engine to Brave. The value 2 is recorded if you saw the promo, did not click on it and changed your default engine.

**Comment by GeetaSarvadnya** [comment]
@DJAndries Thanks for your response! The test plan step 11 needs to updated `Change search engine to Brave via one of the methods in step 8.` It says both the methods should give the response status `2`
