### ISSUE TITLE
Dapps: Fix wallet string translation issue

### ISSUE THREAD

**Issue by qamarngr** [brave/brave-browser#23605]
https://github.com/brave/brave-core/pull/13398#discussion_r903889095

**Comment by kjozwiak** [comment]
The above will require `1.41.82` or higher for `1.41.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using 

```
Brave	1.41.94 Chromium: 103.0.5060.114 (Official Build) (64-bit) 
Revision	a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS	Android 12; Build/SP1A.210812.016
```
- Confirmed `wallet` is changed to `wallet's` in the request key modal
- Confirmed translations for connect modal and request key modals

English | French | Russian | German
-|-|-|-
![screenshot-1657233640789](https://user-images.githubusercontent.com/17885425/177886616-b021ebdc-92c3-4a08-a9c2-9898d7537aec.png) | ![screenshot-1657234479314](https://user-images.githubusercontent.com/17885425/177886641-67673a46-bb83-4bed-a0a2-803d7034645e.png) | ![screenshot-1657234250503](https://user-images.githubusercontent.com/17885425/177886670-9047e7e5-bc8e-48f4-ac28-acc6d17889d4.png) | 
![Uploading screenshot-1657237307239.png…]()



![screenshot-1657233595848](https://user-images.githubusercontent.com/17885425/177886827-e42bd1e9-753d-40fe-92b5-d7c0cd8af454.png) | ![screenshot-1657234828868](https://user-images.githubusercontent.com/17885425/177887084-47c29b83-62fb-402f-a488-03ee87255300.png) | ![screenshot-1657234292859](https://user-images.githubusercontent.com/17885425/177887036-7cc9d4ed-d59d-4e69-b888-4654af78d1d3.png) | ![screenshot-1657234929141](https://user-images.githubusercontent.com/17885425/177888879-1391b311-01b6-4601-b762-08d6af65c908.png)

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy Tab S7` running `Android 12` using 

```
Brave	1.41.94 Chromium: 103.0.5060.114 (Official Build) (64-bit) 
Revision	a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS	Android 12; Build/SP1A.210812.016 
```

- Confirmed wallet is changed to wallet's in the request key modal
- Confirmed translations for connect modal and request key modals in US and non-US languages

English | French | Russian
-|-|-
![screenshot-1657239012538](https://user-images.githubusercontent.com/17885425/177893253-81ab1dd8-336a-45d4-987f-0b7f7074ba2d.png) | ![screenshot-1657239229000](https://user-images.githubusercontent.com/17885425/177893278-084b5058-1176-4660-8e1b-79378ed59ad8.png) | ![screenshot-1657239679946](https://user-images.githubusercontent.com/17885425/177893315-e48cac50-9ecb-49ae-b265-a49586b6671b.png)
![screenshot-1657239091269](https://user-images.githubusercontent.com/17885425/177893412-fa93e145-d3e3-42b2-babc-4a2d7182c49a.png) | ![screenshot-1657239247105](https://user-images.githubusercontent.com/17885425/177893423-539edeab-bd64-4610-8fc3-ead0e06dc45c.png) | ![screenshot-1657239787843](https://user-images.githubusercontent.com/17885425/177893451-6dfd116a-2f4e-4c79-be57-0b0475307998.png)
