### ISSUE TITLE
Add one more pending request to show a wallet's icon badge

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#23613]
We miss one more pending request to show badge https://github.com/brave/brave-core/blob/master/android/java/org/chromium/chrome/browser/app/domain/DappsModel.java#L51
The call is `mBraveWalletService.getPendingDecryptRequests`

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.42.76 x64 Beta build
- Verified steps from [brave/brave-core#13935](https://github.com/brave/brave-core/pull/13935)
- Verified pending request is shown on Wallet icon badge


Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | -- 
<video src=https://user-images.githubusercontent.com/17010094/180426150-fc5b2421-3dc0-43f5-98f4-8e422e81db12.mp4> | <video src=https://user-images.githubusercontent.com/17010094/180426188-7442c67e-f990-4830-8f7f-b44c43abd673.mp4>
