### ISSUE TITLE
Internal URLs imported from Muon fail to resolve

### ISSUE THREAD

**Issue by garrettr** [brave/brave-browser#2361]
## Description 
Follow-up for https://github.com/brave/brave-browser/issues/998#issuecomment-443812890.

The windows/tabs importer exactly re-creates the windows and tabs that were open in Muon in b-c. If any of the open tabs were showing a Muon internal URL (e.g. `about:preferences#payments` for Brave Payments, `chrome-extension://...` for PDFs rendered by pdf.js), it probably won't resolve in b-c because most of the internal URLs have changed.

A small subset of internal URLs, for example `about:history`, resolve correctly in both Muon and b-c.

## Steps to Reproduce

1. In Muon, open one or more tabs and look up an internal URL, e.g. `about:brave`.
2. Quit Muon and start brave-core.
3. Import open windows/tabs from Muon into brave-core (follow the test plan from https://github.com/brave/brave-core/pull/981).

## Actual result:

<img width="1142" alt="screen shot 2018-12-04 at 3 10 51 pm" src="https://user-images.githubusercontent.com/407302/49479142-cf6eb080-f7d6-11e8-852c-96c8a12cdf47.png">

## Expected result:
One of the two following scenarios should be implemented:
1. Internal URLs from Muon should be filtered during import and should not be loaded in brave-core
2. Internal URLs from Muon should be rewritten to their brave-core equivalents during import so they will load the expected page. This may not be possible for all Muon internal URLs.

## Reproduces how often: 
Easily reproduced.

**Comment by LaurenWags** [comment]
Following test plan from https://github.com/brave/brave-core/pull/1021, my pinned tab with a PDF is imported (and opens fine) in b-c, but the normal tab which had a pdf is not imported into b-c. Is this expected?
This is muon prior to b-c import:
![screen shot 2018-12-05 at 1 07 18 pm](https://user-images.githubusercontent.com/28145373/49534191-f5578c00-f88e-11e8-8ef7-b67d7a05dc16.png)

This is b-c after import from muon. I was expecting that the pinned 'PDFjs' tab wouldn't be there. 
![screen shot 2018-12-05 at 1 07 18 pm](https://user-images.githubusercontent.com/28145373/49534098-b6293b00-f88e-11e8-90ef-ea4dafa3e1e2.png)

**Comment by bsclifton** [comment]
@garrettr I believe the filtering logic might not be applying to pinned tabs

**Comment by garrettr** [comment]
@bsclifton Filtering logic should be applied in `ParsePinnedTabs` [here](https://github.com/brave/brave-core/pull/1021/files#diff-c467dc7949e04db58d0d852f05199e07R796).

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.57.16 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

* Verified with test plan in https://github.com/brave/brave-core/pull/1021
* Encountered and logged https://github.com/brave/brave-browser/issues/2376 based on what I saw in https://github.com/brave/brave-browser/issues/2361#issuecomment-444585333
