### ISSUE TITLE
HDR issues

### ISSUE THREAD

**Issue by StuffOfSonny** [brave/brave-browser#23616]
Yes I looked for similar issues, no I did not find any.

## Description 
There seems to be an issue with the latest update that causes tabs to set the entire browser into an HDR mode. If I drag the browser to my HDR monitor, all the colors are correct. Some sites (Like my.nintendo.com and tweetdeck.twitter.com) trigger this issue consistently, but some sites (like duckduckgo.com or twitter.com) only trigger it on certain subpages. Additionally, the issue can sometimes be fixed by opening non-problematic tabs (though sometimes not). This issue doesn't happen on Vivaldi or Firefox when I open the same sites.

## Steps to Reproduce

   1. Open Brave
   2. Put on Sunglasses
   3. Go to https://my.nintendo.com/

## Actual result:

![DiscordCanary_2022-06-22_19-32-00](https://user-images.githubusercontent.com/61560546/175179073-1493006c-9203-4952-931e-e224ad1b017e.png)

## Expected result:
See Screenshot (Firefox displays correctly)

## Reproduces 

I can consistently reproduce the issue.

## Brave version (brave://version info)
<html>
<body>

Brave | 1.40.105 Chromium: 103.0.5060.53 (Official Build) (64-bit)
-- | --
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | Windows 11 Version 21H2 (Build 22000.739)

</body>
</html>

## Version/Channel Information:

Was able to reproduce in the Beta and Nightly Channels immediately by using my.nintendo.com as a test.

## Other Additional Information:
Issue did not resolve from disabling Shields or Rewards.
Does not occur on Microsoft Edge or UnGoogled Chromium, though both of those seem to be an update behind on the Chromium fork (or two, Edge - 102.0.1245.44, UnGoogled Chromium - 102.0.5005.115-1. Vivaldi doesn't say which Chromium Build it's using in it's "About" tab, though my install is "up to date" as of this writing - 5.3.2679.61)

## Miscellaneous Information:

This was not happening yesterday, so I'm assuming I had my browser open before the update was pushed, and today it's running said problematic update. If there is a way to roll back to the previous version, I will test that,

**Comment by rebron** [comment]
@StuffOfSonny If you have Chrome running (no worries if not), are you able to see the reproduce the same behavior?

**Comment by bsclifton** [comment]
@StuffOfSonny can you please try this?
1. Visit brave://flags/#force-color-profile
2. For the setting, pick `sRGB`
3. Restart the browser if needed

I believe this is due to software like Adobe Photoshop that alters the system's color profile (ex: gamma settings). It would be affecting you in other Chromium browsers too

**Comment by StuffOfSonny** [comment]
> 

This appears to have fixed the issue. Thank you so much!

**Comment by StuffOfSonny** [comment]
> @StuffOfSonny can you please try this?
> 
> 1. Visit brave://flags/#force-color-profile
> 2. For the setting, pick `sRGB`
> 3. Restart the browser if needed
> 
> I believe this is due to software like Adobe Photoshop that alters the system's color profile (ex: gamma settings). It would be affecting you in other Chromium browsers too

This appears to have fixed it, thank you so much!

**Comment by bsclifton** [comment]
Awesome! Super glad to hear - thanks for reporting. I'll see if we can add something to our support docs 😄
