### ISSUE TITLE
Disable "reduce language" feature by default

### ISSUE THREAD

**Issue by pilgrim-brave** [brave/brave-browser#23610]
We want to control this feature via Griffin, but on first run we now want the feature to be off by default until Griffin rules are downloaded.

**Comment by kjozwiak** [comment]
@brave/qa-team please see https://github.com/brave/brave-core/pull/13905#issuecomment-1165152535 for STR/Cases 👍

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
Brave | 1.41.77 Chromium: 103.0.5060.53 (Official Build) beta (64-bit)
-- | --
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | Windows 10 Version 21H2 (Build 19044.1766)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/13905 and ensured the following websites are loading as expected and there is no broken text/font on the websites

**https://www.ghacks.net**
![image](https://user-images.githubusercontent.com/38657976/175520029-8ad6e5dc-2b7a-45bb-9a53-9be7d52eb622.png)

**https://valhost.net/demo**
![image](https://user-images.githubusercontent.com/38657976/175520116-981e1503-51b0-4336-a724-ca117fc691f1.png)

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.40.107 Chromium: 103.0.5060.53 (Official Build) (x86_64)
-- | --
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | macOS Version 12.4 (Build 21F79)
```

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.40.107 Chromium: 103.0.5060.53 (Official Build) (64-bit)
-- | --
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | Windows 11 Version 21H2 (Build 22000.739)
```
- Verified the test plan from https://github.com/brave/brave-core/pull/13905 and ensured the following websites are loading as expected and there is no broken text/font on the websites

**https://www.ghacks.net**
<img width="948" alt="image" src="https://user-images.githubusercontent.com/98358127/175568676-b6bf5af6-7db8-4f9a-b79c-9113d48f30ec.png">

**https://valhost.net/demo**

Ex1|Ex2
---|---
<img width="955" alt="image" src="https://user-images.githubusercontent.com/98358127/175568605-8385b2dc-233e-43fe-b392-cbcf2c39fd70.png">|<img width="952" alt="image" src="https://user-images.githubusercontent.com/98358127/175568567-4cc578c2-360c-4e84-9c0d-9a20e3f7f691.png">
