### ISSUE TITLE
Resurrect playlist for desktop

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#23621]
We have to resurrect the old playlist PR. This PR is large and can be split into 4 parts according to a commit log.
But we're not going to communicate via extension API,  so it's actually 3 parts can be reused.

[old pr](https://github.com/brave/brave-core/pull/5733)

### playlist core(components/playlist)
* manage playlist. Playlist core API
* is exported via PlaylistService.
* download thumbnail and media files
* should take Android into account
* Currently, download URLs are retrived here with youtubedown.js (not working)
   * need to port script form iOS - the script seems to be run on target WebContents(active tab)
   * so maybe it'd be better to run script from chrome/ layer, not here.
   * ~~We can fadeout Youtubedown crx related codes.~~
 
### extensions api(browser/extensions/api/playlist): 
* We're not going to use extensions API: We'll use mojo just like other web UIs.
* But we can scan the APis and convert them to mojo

### test purpose playlist webui(components/playlist/resources)
* brave://playlist implementation.
* should add a button on sidebar and load `brave://playlist`

---

## Things TODO: Android & Desktop
- [x] #23622
- [x] #23850
- [x] #24027
- [x] #23895
- [x] #23693
- [x] #23967
- [x] #24094
- [x] #24240 
- [x] #24405
- [x] #24989

---

## Things todo : Desktop
- [ ]  Add a button on location bar to add video/music to playlist
- [x] #25365
- [x] #24619 
- [x] #24620

**Comment by sangwoo108** [comment]
@simonhong I just wrote up things roughly. Please feel free to modify this. I'm going to split the old PR.

**Comment by simonhong** [comment]
> @simonhong I just wrote up things roughly. Please feel free to modify this. I'm going to split the old PR.

Looks good 👍🏼 

> Persistent data for playlist (sql? How about android?)

Old branch uses preferences (not sql). I think it's fine to use it.

**Comment by sangwoo108** [comment]
@simonhong Do you think the new js script for getting download urls should be maintained as component extension like  youtubedownlod was?

**Comment by simonhong** [comment]
> @simonhong Do you think the new js script for getting download urls should be maintained as component extension like youtubedownlod was?

IMO, using component has some benefits.
* That script could be broken easily if service(ex, youtube) has changes. Then, we can fix easily to all channels.
* Not all users needs that script. Only playlist users could have that script
* Maybe license issue could be resolved easily not by default shipping

**Comment by simonhong** [comment]
> > IMO, using component has some benefits.
> 
> Yeah. I totally agree with you on those. One thing I concern about is Android. I guess Android can't use component extensions. Then, should we supply different implementation to get download URLs or just give Android a leeway to pass url list to the core?

Android uses component extension.

**Comment by sangwoo108** [comment]
Oh, that's great. Thanks.

**Comment by simonhong** [comment]
> Yey! tons of things to do but anyway there's progress
> 
> * iOS sciprt was tested on youtube: working.
> * downloading thumbnail and media file: working
> 
> ![image](https://user-images.githubusercontent.com/5474642/178003634-954b02cb-a73b-45a0-8e99-be6e631163f3.png)
> 
> ![image](https://user-images.githubusercontent.com/5474642/178004297-30e4fdb7-6367-4240-82da-6959e4961b72.png)

Awesome! 👍🏼

**Comment by simonhong** [comment]
Added https://github.com/brave/brave-browser/issues/24137 to todo list.

**Comment by sangwoo108** [comment]
Follow-ups for Android will be tracked from https://github.com/brave/brave-browser/issues/25058
