### ISSUE TITLE
Reduce language pref should default to the value of the feature flag

### ISSUE THREAD

**Issue by pilgrim-brave** [brave/brave-browser#23638]
(It's currently defaulting to true, which makes for a confusing UI if the feature flag is off.)

**Comment by kjozwiak** [comment]
@brave/qa-team please see https://github.com/brave/brave-core/pull/13925#issuecomment-1165166684 for STR/Cases 👍

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```

Brave | 1.40.107 Chromium: 103.0.5060.53 (Official Build) (64-bit)
-- | --
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | Windows 10 Version 21H2 (Build 19044.1766)

```

**Comment by LaurenWags** [comment]
Verification PASSED on

```
Brave | 1.40.107 Chromium: 103.0.5060.53 (Official Build) (x86_64)
-- | --
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | macOS Version 12.4 (Build 21F79)
```

Ensured that `Prevent sites from fingerprinting me based on my language preferences` under `brave://settings/shields` was disabled on new profiles and previously created profiles that are upgraded as per https://github.com/brave/brave-browser/issues/23638#issuecomment-1165167549. Example:

1.40.107 - Clean Install | 1.40.107 - Upgraded from 1.40.105
----- | -----
<img width="1198" alt="1 40 107 clean" src="https://user-images.githubusercontent.com/28145373/175527091-8e73a087-a437-48a9-9d1c-b6736d313a73.png"> | <img width="1196" alt="1 40 107 upgrade" src="https://user-images.githubusercontent.com/28145373/175527106-fdc9522d-df69-4e6c-9d36-d5b23e4a74a7.png">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using

```
Brave | 1.40.107 Chromium: 103.0.5060.53 (Official Build) (64-bit)
-- | --
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | Windows 11 Version 21H2 (Build 22000.739)
```

Ensured that `Prevent sites from fingerprinting me based on my language preferences` under `brave://settings/shields` was disabled on new profiles and previously created profiles that are upgraded as per https://github.com/brave/brave-core/pull/13925#issuecomment-1165166684

**`Clean Install`** | **`Upgraded from previous release where setting was enabled`**
--------------------|-------------------------------------------------------------------------
<img width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/175576065-b59d1c33-6fb3-4e0e-bcf9-0c94d22f05a8.png">|<img width="951" alt="image" src="https://user-images.githubusercontent.com/98358127/175574790-cd7d5305-89cd-4152-a9c7-39eab8cc8a5d.png">
