### ISSUE TITLE
Remove add asset button from buy flow on widget & portal

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#23637]
## Description 

You cannot add new assets to buy if we don't offer it on that dropdown & the + button also just adds an asset to the asset list
![Screenshot 2022-06-23 at 15 40 35](https://user-images.githubusercontent.com/12224304/175317684-27ec1e9a-2460-4eee-add6-5624c073c60d.png)

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by muliswilliam** [comment]
The buy widget was deprecated making this issue no longer relevant.
