### ISSUE TITLE
DApps: Wallet icon should match the lock icon in the url bar at runtime

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#23632]
On sites changes the color of lock icon in the url bar at runtime so wallet icon should match the lock icon color.

https://user-images.githubusercontent.com/11755381/175296976-38c18cc6-b793-4890-a10e-c6467f996afa.mp4

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.42.76 x64 Beta build
- Verified steps from [brave/brave-core#13945](https://github.com/brave/brave-core/pull/13945)
- Verified wallet icon now matches the lock icon in URL bar

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/180419300-cd65c882-903c-4eb0-83dd-02b254486001.mp4> | <video src=https://user-images.githubusercontent.com/17010094/180419351-b5397c9e-8dd7-4b97-8eb1-6119680c8a27.mp4>
