### ISSUE TITLE
[hackerone] IPFS crash

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#23646]
https://hackerone.com/reports/1610343

**Comment by diracdeltas** [comment]
please don't share the link publicly that causes the crash

**Comment by stephendonner** [comment]
@cypt4 @diracdeltas 👋  do you have a step-by-step testcase handy QA can follow?  If there's something to be not made public in the verification, we can create an internal issue and cross-link here.

Marking `QA/Blocked` and `QA/Test-Plan-Required` until then.  Thanks in advance!

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.42.62 Chromium: 103.0.5060.114 (Official Build) beta (x86_64)
-- | --
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | macOS Version 13.0 (Build 22A5295i)

Conversation with the original link (now defunct) and minimal testcase (which works) is in https://bravesoftware.slack.com/archives/G2KN13Z8C/p1657739382970029?thread_ts=1657733235.918989&cid=G2KN13Z8C

### Steps:
1. installed `1.42.62`
2. launched Brave
3. created a minimal testcase from the above Slack link, and saved it
4. set `Method to resolve IPFS resources` to `Disabled`, in `brave://settings/ipfs`
5. loaded the minimal testcase

#### Confirmed I don't crash, and the IPFS resource was blocked

IPFS disabled | testcase blocked
---------------|-----------------
<img width="1312" alt="Screenshot 2022-07-13 at 12 50 08 PM" src="https://user-images.githubusercontent.com/387249/178819783-72e75834-45b1-4329-afa3-147ed12d4ff4.png"> | <img width="1312" alt="Screenshot 2022-07-13 at 12 48 55 PM" src="https://user-images.githubusercontent.com/387249/178819301-7ecf15e4-cb80-4224-9eeb-aed27ea428af.png">
