### ISSUE TITLE
Ask tough of the community : Reduce Crypto feature in update.

### ISSUE THREAD

**Issue by BirdInFire** [brave/brave-browser#23642]
I open this issue to actually see if i'm the only one who think that and let the dev team know (if i'm not the only one).

The problem is in every relase note nearly 90% of the content is for the Wallet, crypto stuff, of alternate way to distribute internet (ipfs etc).
Even if i understand that sometime there is update who doesn't bring anything to me as individual, it's been month since i really seen other thing that simple "chrome bump" everything else is wallet / cryptocrap related.

Please answer with you through do you think brave muse reduce the work load on these crypto feature, or continue like this ?

Thanks.

**Comment by rebron** [comment]
Closing as not actionable. @BirdInFire Please move this discussion to https://community.brave.com/ 

If you have feature requests, you can also post in community. We've been working through several usability issues and top requested issues such as https://github.com/brave/brave-browser/issues/10430 and https://github.com/brave/brave-browser/issues/13598 and we're working on a translation feature and vertical tabs as well. 

Again, if you have feature requests, community.brave.com is the appropriate place to discuss.
