### ISSUE TITLE
Support Solana account creation / import

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#23648]
- [x] Show coin type selection UI
- [x] Implement account creation of selected coin type
- [x] Show all accounts (eth+solana)

**Comment by kjozwiak** [comment]
The above will require `1.42.69` or higher for `1.42.x` verification.

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.42.77 x64 build
- Verified create account shows bottom sheet for ETH accounts 
- Verified enabling Solana flag allows to create a Solana account
- Verified able to select Solana accounts from Panel 
- Verified able to select Solana accounts in accounts tab
- Encountered [#24104](https://github.com/brave/brave-browser/issues/24104)
------------
Verification passed on Samsung Tab A with Android 10 running 1.42.77 x64 build
- Verified create account shows bottom sheet for ETH accounts 
- Verified enabling Solana flag allows to create a Solana account
- Verified able to select Solana accounts from Panel 
- Verified able to select Solana accounts in accounts tab
- Encountered [#24104](https://github.com/brave/brave-browser/issues/24104)
