### ISSUE TITLE
Add Solana to the network selector

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#23647]
- [ ] Add Solana to network selector
- [ ] Should prompt for new Solana account creation if a user hasn't created one after selecting the Solana network.

**Comment by kjozwiak** [comment]
The above will require `1.42.76` or higher for `1.42.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.42.77 x64 build
- Verified steps from [ brave/brave-core#14240](https://github.com/brave/brave-core/pull/14240)
- Verified able to create an account when Network dropdown is selected
- Verified selecting Solana for the first time shows popup to create the account
- Verified able to see Solana in the network drop down
- Verified able to select Solana from network drop down
- Encountered [#24193](https://github.com/brave/brave-browser/issues/24193) & [#24194](https://github.com/brave/brave-browser/issues/24194)

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/181032326-a63aec5f-66e7-469e-af48-3375df3285e7.mp4> | <video src=https://user-images.githubusercontent.com/17010094/181032244-6033edc8-caeb-42a3-8926-281eff9e5110.mp4>
