### ISSUE TITLE
Webview (tab) crash on `att.com/internet/fiber` in Solana support

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#23645]
## Description 

Webview (tab) crash on `att.com/internet/fiber` in Solana support

## Steps to Reproduce

   1. new profile
   2. launch Brave
   3. load `att.com`
   4. click on `Internet` on the top nav
   5. `https://www.att.com/internet/fiber/` loads
   6. wait

## Actual result:

Crash in:

```
[ 00 ] 0x10f9a676e
[ 01 ] 0x10e437805
[ 02 ] 0x112f03ed1
[ 03 ] 0x112f06d6a
[ 04 ] 0x10e3121ca
[ 05 ] 0x10e7198ed
[ 06 ] 0x10e0494e5
[ 07 ] 0x11036d34b
[ 08 ] 0x10de181c4
[ 09 ] 0x10de65c0e
[ 10 ] 0x113648b7a
[ 11 ] 0x10de1c68a
[ 12 ] 0x11035dabf
[ 13 ] 0x7fff20a04cec
[ 14 ] 0x7fff20a04c54
[ 15 ] 0x7fff20a049d4
[ 16 ] 0x7fff20a033fc
[ 17 ] 0x7fff20a029bc
[ 18 ] 0x7fff21794617
[ 19 ] 0x10f650efe
[ 20 ] 0x10f650df4
[ 21 ] 0x10ec8b5ea
[ 22 ] 0x10ec8acce
[ 23 ] 0x10f24736c
[ 24 ] 0x10ef08749
[ 25 ] 0x10f213d7c
[ 26 ] 0x10de05f97
[ 27 ] 0x10906e426
[ 28 ] 0x7fff20927f3d
[ 29 ] 0x7fff20927f3d
```

## Expected result:

Page loads, no crash

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.42.21 Chromium: 103.0.5060.53 (Official Build) nightly (x86_64)
-- | --
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | macOS Version 11.6.7 (Build 20G630)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `No`
- Can you reproduce this issue with the nightly channel? `Yes`

cc @srirambv @GeetaSarvadnya @MadhaviSeelam

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.42.26 Chromium: 103.0.5060.53 (Official Build) nightly (x86_64)
-- | --
Revision | a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS | macOS Version 11.6.7 (Build 20G630)

Followed my original steps to reproduce.

#### Confirmed there's no longer a crash going from `att.com` -> `att.com/internet` / `att.com/internet/fiber`

<img width="1312" alt="Screen Shot 2022-06-24 at 10 57 07 AM" src="https://user-images.githubusercontent.com/387249/175616936-1871e088-db26-4c57-a7d2-404d8b1367b9.png">

**Comment by srirambv** [comment]
Removing QA Pass label as there is an uplift and needs to be rechecked

**Comment by kjozwiak** [comment]
The above will require `1.41.89` or higher for `1.41.x` verification 👍

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.41.86 Chromium: 103.0.5060.66 (Official Build) beta (64-bit) </th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>20b1569438a85e631d15e83eb355e3e326e5da6f-refs/branch-heads/5060@{#1066}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.708)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from issue description</li>
         <li>Verified no crash when visiting <code>https://att.com/</code></li>
         <li>Verified no crash when loading <code>https://att.com/</code> and navigating to Internet which redirects to <code>https://att.com/internet</code></li>
         <li>Verified no crash when visiting <code>https://att.com/internet/fiber/</code></li>
        </ul>
      </td>
   </tr>
</table>
