### ISSUE TITLE
Remove `Desktop Mode` option as it is a duplicate now

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#23652]
## Description 
In `Site Settings` `Desktop Mode` option is a duplicate of `Desktop site` and so we should remove it.
![Screenshot_20220623_160737](https://user-images.githubusercontent.com/30602739/175396971-060ab1b5-8ee6-4c64-9570-e58238a1a9c6.png)

## Steps to reproduce 

   1. Go to `Site settings`
   2. There 2 options `Desktop Mode` and `Desktop site`

## Actual result 
There 2 options `Desktop Mode` and `Desktop site`

## Expected result
Only `Desktop site` should be left.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by samartnik** [comment]
Test plan:
- Check that after upgrade to a newer version there is only 1 option left (`Desktop site`).
- Double check that `Desktop site` option works as intended (when `on`, all websites open in desktop mode by default and in mobile mode otherwise).
- Double check that `Desktop site` option in main menu able to override global option for current web site.
- Double check that when `Desktop Mode` option was on prior to upgrade, `Desktop site` global option is also on after upgrade regardless of its state before upgrade.

**Comment by kjozwiak** [comment]
The above will require `1.41.94` or higher for `1.41.x` verification 👍

**Comment by kjozwiak** [comment]
Please wait till https://github.com/brave/brave-core/pull/14053 gets uplifted into `1.41.x`

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.41.94 x64 build
- Verified steps from [#23652 (comment)](https://github.com/brave/brave-browser/issues/23652#issuecomment-1169108408)
- Verified there is only `Desktop Site` option under `Site settings`
- Verified enabling `Desktop Site` enables it globally on all new tabs and page loads using desktop mode
- Verified able to override the global settings via the menu settings 
- Verified setting `Desktop Mode` to enabled on an older version and upgrading to 1.41.94 removes `Desktop Mode` from settings and sets `Desktop Site` to enabled

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/177745951-f666d386-ea94-4ab9-b0a7-b0cf78442ea9.mp4> | <video src=https://user-images.githubusercontent.com/17010094/177722240-08407953-01c6-4b95-b2aa-fcfa1a3d96b8.mp4>
