### ISSUE TITLE
Hide sites from auto-contribute with 0% contribution.

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#2365]
Due to some of the computation and using percentages for auto-contribute, a lot of users see that their long tail auto-contribution has 0% contributions associated with them (<0.5% computations round to 0%)

To reduce visualization pain points, the auto-contribute table should hide all sites that have 0% contributions.

cc @davidtemkin @NejcZdovc

**Comment by kirkins** [comment]
I don't have any experience on this project but I'm wondering if this small change in the contributeBox component of brave-core would fix it?

https://github.com/kirkins/brave-core/commit/9be4fb6dea0f99d164b39bf0a013ca13a58a59f2

I'm doing my first build of `brave-browser` and it seems to take a long time. Do you have to run a build every-time a change is made, or is there a faster way?

**Comment by NejcZdovc** [comment]
@kirkins hi thx for trying out brave-browser. Sadly there is no faster way to build.

Regarding change we would probably prefer to do this on database level, so that we would reduce payload that we are sending to JS

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.59.26 Chromium: 72.0.3626.64 (Official Build) beta (64-bit)
-- | --
Revision | eaa9668e80ce5405e7f1902579558ea725c06ca1-refs/branch-heads/3626@{#708}
OS | Windows 7

Used test plan from https://github.com/brave/brave-core/pull/1032

![image](https://user-images.githubusercontent.com/34715963/51509512-bc04bc80-1df9-11e9-9ee9-c4d5a680a87d.png)
![image](https://user-images.githubusercontent.com/34715963/51509516-c32bca80-1df9-11e9-83d2-14a1ed799181.png)
