### ISSUE TITLE
Refactor Trezor and Ledger HW wallet bridges to align better with chrome-untrusted:// boundaries

### ISSUE THREAD

**Issue by kdenhartog** [brave/brave-browser#23655]
When I was taking a look at the Solana HW Wallet integration with @nvonpentz one of the things he noted was that we may not be hitting our process isolation guarantees quite like we thought we were. We should refactor our implementation with Trezor, and also make sure that we're properly isolating the [ETH ledger bridge keyring](https://github.com/brave/brave-core/blob/master/components/brave_wallet_ui/common/hardware/ledgerjs/eth_ledger_bridge_keyring.ts) and the [filecoin ledger bridge keyring](https://github.com/brave/brave-core/blob/master/components/brave_wallet_ui/common/hardware/ledgerjs/filecoin_ledger_keyring.ts) to make sure they're isolated properly as well.

We want to make sure these bridges are adhering with the principles outlined in the [chrome-untrusted FAQ document](https://source.chromium.org/chromium/chromium/src/+/main:docs/chrome_untrusted.md#separate-fully-trusted-WebUIs-and-untrustworthy-ones) since these bridges are processing untrusted inputs from the HW wallet and therefore should be isolated.

@nvonpentz pointed out, 

"Basically, if the point is to isolate the 'trezor-connect' library such that it is only used in the untrusted frame, then I'm not sure we're accomplishing that currently, because the 'trezor-connect' library is imported in code that runs outside that frame.
This is the js that runs in the trezor untrusted frame: https://github.com/brave/brave-core/blob/master/components/brave_wallet_ui/trezor/trezor.ts.
This [TrezorBridgeKeyring](https://github.com/brave/brave-core/blob/master/components/brave_wallet_ui/common/hardware/trezor/trezor_bridge_keyring.ts#L35) is an example of some js that imports the library, but then is run in the hardware-wallet-connect [component](https://github.com/brave/brave-core/blob/636b7fcdd2db56144088abfefa6a993a37957ac9/components/brave_wallet_ui/components/desktop/popup-modals/add-account-modal/hardware-wallet-connect/index.tsx#L64-L66) via  [onConnectHardwareWallet](https://github.com/brave/brave-core/blob/939568e4e50eb1eed2448526cbc86f85154aa35c/components/brave_wallet_ui/common/async/lib.ts#L59-L63) -> [getHardwareKeyring](https://github.com/brave/brave-core/blob/939568e4e50eb1eed2448526cbc86f85154aa35c/components/brave_wallet_ui/common/api/hardware_keyrings.ts#L45) -> [getTrezorHardwareKerying](https://github.com/brave/brave-core/blob/939568e4e50eb1eed2448526cbc86f85154aa35c/components/brave_wallet_ui/common/api/hardware_keyrings.ts#L75)
I'm assuming that importing the library is enough to be exposed to whatever bad consequences we want to avoid by sandboxing"

**Comment by kdenhartog** [comment]
cc @jamesmudgett this is the separate wallet process isolation issue I mentioned on the wallet security call today

**Comment by nvonpentz** [comment]
I tried to copy the chrome-untrusted approach used in the Trezor integration for Ledger, but ran into this permission issue when connecting attempting to connect my ledger device for the first time:
```
Failed to execute 'requestDevice' on 'HID': Must be handling a user gesture to show a permission request.
```

The 'connect your wallet' click occurs in the chrome://wallet context, which triggers a postMessage call to the untrusted iframe.  The untrusted iframe processes the API and calls the ledger library which calls `navigator.hid.requestDevices()`, which prompts the permissions dialog.  The problem is that `requestDevices()` must be called in the context of a user action like a click, however that context is not propagated with postMessage.  I suspect we do not have this issue with Trezor because that integration requires the user click a second time (after clicking 'connect'), and that happens from within the untrusted frame.

One solution is to put the 'connect your wallet' button into the untrusted frame to preserve the context.  Then instead of having the *_ledger_bridge_keyring.ts classes operate in the chrome://wallet context sending postMessages to chrome-untrusted://ledger-bridge, they would operate in the chrome-untrusted://ledger-bridge context (respond to click events) and send postMessages to the chrome://wallet or panel contexts.

**Comment by kdenhartog** [comment]
A second alternative method recommended by the chromium documents is to expose mojo APIs specifically for communications expected to occur between the untrusted and trusted frames. I've not spent the time to work through how this split is working, but it maybe useful as we're implementing this work.

Here's a sample app that shows how this can be done: https://chromium-review.googlesource.com/c/chromium/src/+/3222406/

**Comment by nvonpentz** [comment]
@kdenhartog if we went that route, what would the flow look like?

**Comment by kdenhartog** [comment]
Do you mean flow in terms of the UX?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.42.92 Chromium: 104.0.5112.81 (Official Build) (64-bit)  
-- | --
Revision | `5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}`
OS | Linux

- Verified steps from from [brave/brave-core#14096](https://github.com/brave/brave-core/pull/14096)
- Verified able to Authorize Ledger device
- Verified able to connect and add accounts from Ledger
- Verified able to perform sign transactions after authorizing the ledger device for Solana transactions
- Encountered [#24229](https://github.com/brave/brave-browser/issues/24429)

Test Case 1 | Test Case 2
-- | --
<video src=https://user-images.githubusercontent.com/17010094/184157953-1b79b3d8-9499-42c1-8c1b-a442084bb92d.mp4> | <video src=https://user-images.githubusercontent.com/17010094/184157999-c87e228a-a68a-4d4d-9a8c-d5ccfbf44de9.mp4>

------------------------
Verification passed on

Brave | 1.42.92 Chromium: 104.0.5112.81 (Official Build) (64-bit)  
-- | --
Revision | `5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}`
OS | Windows 11 Version 21H2 (Build 22000.795)

- Verified steps from from [brave/brave-core#14096](https://github.com/brave/brave-core/pull/14096)
- Verified able to Authorize Ledger device
- Verified able to connect and add accounts from Ledger
- Verified able to perform sign transactions after authorizing the ledger device for Solana transactions
- Encountered [#24229](https://github.com/brave/brave-browser/issues/24429)

Test Case 1 | Test Case 2
-- | --
<video src=https://user-images.githubusercontent.com/17010094/184160518-753b7431-f210-41b2-93aa-fd8b2a132166.mp4> | <video src=https://user-images.githubusercontent.com/17010094/184160793-4f2efcfc-cf8d-42af-83d0-e31636fa020c.mp4>

------------------------
Verification passed on

Brave | 1.42.92 Chromium: 104.0.5112.81 (Official Build) (64-bit) 
-- | --
Revision | `5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [brave/brave-core#14096](https://github.com/brave/brave-core/pull/14096)
- Verified able to Authorize Ledger device
- Verified able to connect and add accounts from Ledger
- Verified able to perform sign transactions after authorizing the ledger device for Solana transactions
- Encountered [#24229](https://github.com/brave/brave-browser/issues/24429)

Test Case 1 | Test Case 2
-- | --
<video src=https://user-images.githubusercontent.com/17010094/184164554-b63e4ee4-3d97-42b7-9a60-78d7dedcccdd.mov> | <video src=https://user-images.githubusercontent.com/17010094/184164608-fd7b3e2d-109f-41cd-a373-a69f2fb5ed96.mov>
