### ISSUE TITLE
Have a place holder text while panel is loading the transaction values

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23663]
## Description 

Have a place holder text while panel is loading the transaction values

## Steps to Reproduce

   1. Submit a Sign and Send transaction on `https://pwgoom.csb.app/`
   2. Panel loads and enables confirm button but the total value is still not populated on the panel

## Actual result:

https://user-images.githubusercontent.com/17010094/175481428-4e5d5e79-e46e-4dc0-970d-3db1dae34fac.mp4

## Expected result:
Should not enable Confirm button till the values are populated in the panel or have a `Loading values` placeholder text on panel while the values are populated

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.42.24 Chromium: 103.0.5060.53 (Official Build) nightly (64-bit) 
-- | --
Revision | `a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}`
OS | Windows 11 Version 21H2 (Build 22000.739)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel @yrliou this also happens on other EVM's tokens as well where the total value is being loaded but before loading confirm button is enabled. NOTE: This is not a problem when you view the panel in tab via `brave://wallet-panel.top-chrome`

**Comment by jamesmudgett** [comment]
@Douglashdaniel needs loading skeleton

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.50.93 Chromium: 111.0.5563.64 (Official Build) beta  (64-bit) 
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Linux

- Verified steps from [brave/brave-core#16945](https://github.com/brave/brave-core/pull/16945)
- Verified loading skeleton is shown when the values are being fetched
- Verified `Unable to fetch fee estimates` error is shown when network doesn't match

https://user-images.githubusercontent.com/17010094/225847953-b2d0de94-be61-4efd-9b95-6c35e5e1b596.mp4

---------------------

Verification passed on 

Brave | 1.50.93 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from [brave/brave-core#16945](https://github.com/brave/brave-core/pull/16945)
- Verified loading skeleton is shown when the values are being fetched
- Verified `Unable to fetch fee estimates` error is shown when network doesn't match

https://user-images.githubusercontent.com/17010094/225847993-6d87f53a-4c3c-4c9a-9ffc-c7939f51c939.mp4

---------------------

Verification passed on 

Brave | 1.50.93 Chromium: 111.0.5563.64 (Official Build) beta (arm64)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#16945](https://github.com/brave/brave-core/pull/16945)
- Verified loading skeleton is shown when the values are being fetched
- Verified `Unable to fetch fee estimates` error is shown when network doesn't match

https://user-images.githubusercontent.com/17010094/225848287-7e974299-ccf7-412c-9d69-ea4ea31b03b4.mov
