### ISSUE TITLE
Bookmark bar hover backdrop different for site or folder

### ISSUE THREAD

**Issue by rubenpoppe** [brave/brave-browser#23667]
## Description 
The hover backdrop on the bookmark bar differs between a site or a folder. Not sure if intended.

## Steps to Reproduce
   1. Add item to the bookmark bar
   2. Create folder on the bookmark bar

## Actual result:
![image](https://user-images.githubusercontent.com/6934044/175498617-45024b53-4237-4446-ac54-2a01b3935058.png)

## Expected result:
![176397339-d5cba951-026a-4459-947c-52ce14d5cb56](https://user-images.githubusercontent.com/5951041/176482133-74da8a8a-3f9f-421c-b745-80b8fa933aab.png)

## Reproduces how often: 
Every time

## Brave version (brave://version info)
Brave: 1.40.105 Chromium: 103.0.5060.53 (Official Build) (64-bit)
Revision: a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}
OS: Windows 11 Version 22H2 (Build 22621.105)

## Version/Channel Information:
Tested on current release

**Comment by rebron** [comment]
cc: @emerick Chromium 103 related issue?

**Comment by rebron** [comment]
Bookmark folder background hover should match background hover for an individual link, more squared/soft round versus the Chrome style round. 
cc: @aguscruiz

**Comment by aguscruiz** [comment]
Agreed, we should keep the original style, at least for now, so it's consistent

**Comment by kjozwiak** [comment]
The above will require `1.41.94` or higher for `1.41.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.41.94 Chromium: 103.0.5060.114 (Official Build) (x86_64)
-- | --
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | macOS Version 12.4 (Build 21F79)
```
