### ISSUE TITLE
Add network filter to Visible Asset Modal

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#23675]
## Description 
Add a `Network` filter to the `Edit Visible Assets` modal to allow sorting assets by network.

![Screen Shot 2022-06-24 at 10 10 16 AM](https://user-images.githubusercontent.com/40611140/175564691-aca6108f-48e5-4d5a-bf07-c0b8112dc9b0.png)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.47.46 Chromium: 107.0.5304.91 (Official Build) nightly (64-bit) 
-- | --
Revision | `3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}`
OS | Linux

- Verified steps from [brave/brave-core#15519](https://github.com/brave/brave-core/pull/15519)
- Verified network filter is available on Visible asset modal
- Verified able to search tokens based on network or all network
- Verified able to add tokens for specific network and lists in portfolio

https://user-images.githubusercontent.com/17010094/200582851-3873c9de-a334-420d-aa9d-749fcfb5356e.mp4


---------------------

Verification passed on 

Brave | 1.47.46 Chromium: 107.0.5304.91 (Official Build) nightly (64-bit) 
-- | --
Revision | `3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#15519](https://github.com/brave/brave-core/pull/15519)
- Verified network filter is available on Visible asset modal
- Verified able to search tokens based on network or all network
- Verified able to add tokens for specific network and lists in portfolio

https://user-images.githubusercontent.com/17010094/200583443-8e27b7ac-23cc-4e8a-b983-ce9aa06ffae9.mp4

---------------------

Verification passed on 

Brave | 1.47.46 Chromium: 107.0.5304.91 (Official Build) nightly (64-bit) 
-- | --
Revision | `3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#15519](https://github.com/brave/brave-core/pull/15519)
- Verified network filter is available on Visible asset modal
- Verified able to search tokens based on network or all network
- Verified able to add tokens for specific network and lists in portfolio

https://user-images.githubusercontent.com/17010094/200578414-c41d6626-a68c-4dd2-b9dc-2432f3c727eb.mov
