### ISSUE TITLE
Dismiss Panel UI after Rejecting Transaction

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#23673]
## Description 
After rejecting a Transactions the `Main` Panel UI should be dismissed.

https://user-images.githubusercontent.com/40611140/175551972-e8362c8c-b6ce-435b-9d7b-93e7f6bb059b.mov

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta  (64-bit) 
-- | --
Revision | `46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}`
OS | Linux

- Verified steps from [brave/brave-core#16625](https://github.com/brave/brave-core/pull/16625)
- Verified rejecting a transaction automatically dismisses the panel

https://user-images.githubusercontent.com/17010094/221797022-fea34b15-376d-4e91-8b33-24a6578fa4ee.mp4

---------------------

Verification passed on 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta  (64-bit)
-- | --
Revision | `46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#16625](https://github.com/brave/brave-core/pull/16625)
- Verified rejecting a transaction automatically dismisses the panel

https://user-images.githubusercontent.com/17010094/221797234-d72cf1dd-bd60-427a-856f-41156f1a9477.mp4

---------------------

Verification passed on 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta  (arm64)
-- | --
Revision | `46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#16625](https://github.com/brave/brave-core/pull/16625)
- Verified rejecting a transaction automatically dismisses the panel

https://user-images.githubusercontent.com/17010094/221797522-ce66a4d9-37a0-4342-bea3-ad657772d20d.mov
