### ISSUE TITLE
TypeError in Confirm Solana Transaction Panel

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#23674]
## Description 
```
[54650:259:0623/162254.210409:ERROR:CONSOLE(37212)] "Uncaught TypeError: Cannot read properties of undefined (reading 'pubkey')", source: chrome://wallet-panel.top-chrome/brave_wallet_panel.bundle.js (37212)
[54650:259:0623/162254.215544:ERROR:CONSOLE(243975)] "The above error occurred in the <ConfirmSolanaTransactionPanel> component:
    in ConfirmSolanaTransactionPanel (created by Container)
    in div (created by LongWrapper)
    in LongWrapper (created by Container)
    in div (created by PanelWrapper)
    in PanelWrapper (created by Container)
    in Container (created by App)
    in Le (created by LightDarkThemeProvider)
    in LightDarkThemeProvider (created by App)
    in Provider (created by App)
    in App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.", source: chrome://wallet-panel.top-chrome/brave_wallet_panel.bundle.js (243975)
[54650:259:0623/162254.224159:ERROR:CONSOLE(37212)] "Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'pubkey')", source: chrome://wallet-panel.top-chrome/brave_wallet_panel.bundle.js (37212)
[54650:259:0623/162256.600844:ERROR:node_channel.cc(859)] Dropping message on closed channel.
```

**Comment by kjozwiak** [comment]
The above will require `1.41.88` or higher for `1.41.x` verification 👍

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.41.93 Chromium: 103.0.5060.114 (Official Build) (64-bit) </th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.708)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/13948>brave/brave-core#13948</a></li>
         <li>Verified no error when trying to connect/initiate transactions</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/177558160-c1e23402-2d53-489f-ac58-dec1d0524ff8.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/177558224-c3576ea7-5ca8-4ccb-81aa-8fa33e965534.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/177558732-a8fb7b9c-94d8-4830-b518-7451c8ae895e.mov>
      </td>
   </tr>
</table>
