### ISSUE TITLE
Edit top site dialog displays in the background instead of the foreground

### ISSUE THREAD

**Issue by nightfury0448** [brave/brave-browser#23685]
## Description 

Edit top sites dialog displays in the background versus foreground. Can still make edits and save.

## Steps to Reproduce

   1. Go to the new tab page and make sure there's a few top sites sites showing from most visited. 
   2. Add site via the kebab menu or edit a tile to go into favorites mode.
   3. Notice Add Site/Edit dialog box. Move screen size or if many frequently visited/top sites are shown you'll see that dialog is in the background.

## Actual result:

![Screenshot (129)](https://user-images.githubusercontent.com/108186894/175779142-16f1cc80-cf20-4384-8df1-7cd1c3e561fe.png)
edit site is not working properly

## Expected result:
Edit dialog displays in the foreground

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by fallaciousreasoning** [comment]
I think this has probably been around for a while - the pagination on the NTP stuff hasn't landed yet.

**Comment by kjozwiak** [comment]
The above will require `1.41.94` or higher for `1.41.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.41.94 Chromium: 103.0.5060.114 (Official Build) (x86_64)
-- | --
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | macOS Version 12.4 (Build 21F79)
```
