### ISSUE TITLE
Tip not shown in Summary on settings page when Payments data imported from muon

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#2368]
## Description 
If you import Payments data from muon, and then tip a site (one time tip), the tip does not display in your Rewards Summary. Instead, you see the 'Sadly, no tokens' message.

## Steps to Reproduce

   1. Have Payments set up in muon (wallet with balance, etc)
   2. Import data to b-c.
   3. See data successfully import to b-c (wallet balance, pinned sites become tips, etc)
   4. Navigate to a site and do a one time tip.
   5. Wallet balance goes down, tip is recorded in Tips panel (other tips were imported) - see tip highlighted in box:
![screen shot 2018-12-05 at 10 55 32 am](https://user-images.githubusercontent.com/28145373/49526986-f1237280-f87e-11e8-8c98-23879301e1e6.png)

## Actual result:
Tip is not recorded in Rewards Summary on brave://rewards or via the BAT logo:
![screen shot 2018-12-05 at 10 55 46 am](https://user-images.githubusercontent.com/28145373/49526938-d9e48500-f87e-11e8-8540-3857979720af.png)

## Expected result:
Tip should be recorded in summary.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.57.16 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information
If you perform the steps with a fresh wallet created on 0.57.x (not imported from muon), the tip displays in the Rewards Summary:
![screen shot 2018-12-05 at 11 15 39 am](https://user-images.githubusercontent.com/28145373/49527058-1e702080-f87f-11e8-8cc4-6ccc8c4e8aa3.png)
![screen shot 2018-12-05 at 11 15 33 am](https://user-images.githubusercontent.com/28145373/49527064-216b1100-f87f-11e8-8bb7-56c8e61d2811.png)

**Comment by LaurenWags** [comment]
cc @NejcZdovc @bsclifton @rebron @kjozwiak

**Comment by LaurenWags** [comment]
@kjozwiak I don't believe there's a way to recover from this state. I agree that we should up the priority so upgraded users get an accurate picture of what's going on in Rewards - especially since this is a new feature not available in Payments. Also, it could be related to https://github.com/brave/brave-browser/issues/2379

**Comment by kjozwiak** [comment]
@rebron moved this into `0.58.x` as per our conversation with @davidtemkin. Can we get someone to take a look at this? Once someone is assigned, lets move it out of `Untriaged Backlog in Rewards` and into the `In Progress` board 👍

**Comment by NejcZdovc** [comment]
@kjozwiak I will take a look later today

**Comment by rebron** [comment]
@LaurenWags Does this happen when you manually import payments from muon (or was this from the auto update)?

**Comment by LaurenWags** [comment]
@rebron - reproduces when auto updating from muon, manually importing (thru Import Bookmarks and Settings), and launching brave with `--update-from-muon` flag.

**Comment by kjozwiak** [comment]
@LaurenWags thanks for double checking 👍 

@rebron definitely need to get this fixed as we're encouraging users to migrate their date over. @NejcZdovc mentioned that he'll be looking at this so hopefully we can get this fixed before the release.
