### ISSUE TITLE
Using Mouse Clicks when Adding or Editing Top Sites on NTP Closes the Dialogue Box

### ISSUE THREAD

**Issue by Cattae** [brave/brave-browser#23689]
## Description 
Unable to use mouse to click on entry fields & save options when adding (or editing) top sites. When use mouse to click on anything displayed, the dialogue box closes.

## Steps to Reproduce

   1. Click Add (or Edit) Top Site 
   2. Use mouse to click a field or option in the dialogue box displayed
   3. Dialogue box closes

## Actual result:
1. Can not enable data entry in a field using a mouse click because Dialogue box closes.
2. Can enter data in first field by just starting to type but need to use tab key to move to next field
3. Cannot click save button using mouse or dialogue box closes without saving.
4. To save data entered, do not use mouse click, just hit enter key on keyboard.

## Expected result:
Ability to use mouse clicks to move from field to field for data entry and save option.

## Reproduces how often: 

Easily reproduced. Reproducible in Release, Beta, & Nightly.

## Brave version (brave://version info)

Release:  1.40.107 Chromium: 103.0.5060.53; Windows 10 Version 21H1 (Build 19043.1766)
Beta:  1.41.74 Chromium: 103.0.5060.53; same OS
Nightly:  1.42.29 Chromium: 103.0.5060.53; same OS 

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Shields disabled by default on NTP
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? Unknown

## Miscellaneous Information:

Brave Community topics relating to issue report.
https://community.brave.com/t/cannot-add-new-favorite-top-site/406742
https://community.brave.com/t/i-cant-add-favorite-sites-on-my-new-tab/407069
https://community.brave.com/t/top-sites-bug-someone-knows-how-to-fix-it/407304
https://community.brave.com/t/i-cannot-manually-add-websites-to-the-the-top-sites-section-on-my-dashboard/407360
https://community.brave.com/t/unable-to-add-a-site-url-in-browsers-top-sites/407854

**Comment by rebron** [comment]
cc: @fallaciousreasoning

**Comment by kjozwiak** [comment]
The above will require `1.41.94` or higher for `1.41.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.41.94 Chromium: 103.0.5060.114 (Official Build) (x86_64)
-- | --
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | macOS Version 12.4 (Build 21F79)
```
