### ISSUE TITLE
Pending update of brave snap. Close the app to avoid disruptions

### ISSUE THREAD

**Issue by itsfrank98** [brave/brave-browser#23692]
Over the last weeks, everyday I get this notification. There is no malfunctioning, I just get the notification, which is pretty annoying since there is no further descriptions and I don't know what I should do about that. I ran the command `sudo snap refresh`, as I found [here](https://community.brave.com/t/pending-update-of-brave-snap-close-the-app-to-avoid-disruptions-8-days-left/399660/2) but nothing changed.
I'm on Ubuntu 20.04

## Steps to Reproduce
Nothing in particular. The notification displays by itself when I turn the computer on or randomly during the day.

## Actual result:
![image](https://user-images.githubusercontent.com/45521145/175896412-f9b3df28-5e52-4468-9744-be1f1675f4a2.png)

## Reproduces how often: 
Every day

## Brave version (brave://version info)
1.40.107
Chromium: 103.0.5060.53

**Comment by b1rdd0g** [comment]
I am getting the same. No idea what the Brave snap is or how to close it. I'm on Ubuntu VERSION="20.04.4 LTS (Focal Fossa)". I am hoping to get this annoying issue resolved, at last.

**Comment by AlioMcDavis** [comment]
Word has it that it works for a lot of people to:
-CLOSE the Brave browser
-Open the Terminal
-Type    sudo snap refresh

**Comment by AaronTechnic** [comment]
This is a problem on Snap's side, not Brave. Kill the Brave browser and refresh snap apps.

**Comment by rebron** [comment]
Closing per last comment. Thanks @AaronTechnic @AlioMcDavis

**Comment by itsfrank98** [comment]
I would like this to be reopened. Even if I did what you suggested (which I already done before opening the issue) I keep getting the warning

**Comment by AlioMcDavis** [comment]
I did the complete purge and re-install. 
That seemed to work for a few days but then reappeared.
I'm going to just keep dealing with the warning and hope everything doesn't suddenly go haywire someday.

**Comment by rahvee** [comment]
I wrote a script to detect this issue, detect when the app is closed, and automatically perform the snap refresh. https://gitlab.com/rahvee/snap-update
