### ISSUE TITLE
Brave browser not launching on Fedora 29 Workstation

### ISSUE THREAD

**Issue by Eznoka** [brave/brave-browser#2369]
## Description 
Brave-browser not launching on Fedora 29 (x86_64, Gnome under Wayland)

## Steps to Reproduce

   1. Install brave-brwoser following documentation for f28+, no issue
   2. From terminal; launching brave-browser (but same result using desktop icon)
   3. 

## Actual result:
Brave-browser icon appears in gnome-shell but no browser window, only option is to quit

Result from terminal:
[7550:7550:1205/172230.531569:ERROR:sandbox_linux.cc(379)] InitializeSandbox() called with multiple threads in process gpu-process.
[7508:7538:1205/172230.830092:ERROR:rewards_service_impl.cc(133)] Failed to read file: /home/francois/.config/BraveSoftware/Brave-Browser/Default/ledger_state

## Expected result:
Brave-browser is working

## Reproduces how often: 

Always reproduced.

## Brave version (brave://version info)

Brave Browser 70.0.56.15 
### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes, using brave-beta repo

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by bluesabre** [comment]
In Xubuntu 18.04, 18.10, and 19.04, Brave will open the URL, but a segmentation fault also occurs. I've only noticed this in recent weeks, so it may be a different issue entirely.

$ brave-browser google.com
[5917:5917:0413/101055.963283:ERROR:sandbox_linux.cc(364)] InitializeSandbox() called with multiple threads in process gpu-process.
Segmentation fault (core dumped)

**Comment by fmarier** [comment]
@Eznoka are you still having this problem?

@mbacchi I assume you can confirm that brave-browser launches without problems on your Fedora 29 machine, right?

**Comment by Eznoka** [comment]
Hi

Sorry, since I opened this bug report, I upgraded to F30 and with latest stable version of Brave from the repo, it's working fine.
So not on same configuration, but for me you can close this issue.
