### ISSUE TITLE
Add custom asset page not loading

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#23694]
## Description 

Page not loading for brave://wallet/crypto/portfolio/add-asset
<img width="1717" alt="Screenshot 2022-06-27 at 14 19 24" src="https://user-images.githubusercontent.com/12224304/175939589-db14d168-dcd5-4d25-adf4-06be4b4f0984.png">

## Steps to Reproduce

   1. go on portal
   2. click on view account assets
   3. click add assets
   4. click add custom asset
   5. and wait for brave://wallet/crypto/portfolio/add-asset to load

## Brave version (brave://version info)

1.42.29 Chromium

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.42.80 Chromium: 104.0.5112.57 (Official Build) (64-bit) 
-- | --
Revision | `212fd173a0da1e0a024f328295bb56a2529190bb-refs/branch-heads/5112@{#1042}`
OS | Linux

- Verified steps from [brave/brave-core#13960](https://github.com/brave/brave-core/pull/13960)
- Verified visiting `brave://wallet/crypto/portfolio/add-asset` route directly in a new tab still allows to add asset
- Verified loading the page route `brave://wallet/crypto/portfolio/add-asset` directly with wallet locked still allows to add asset after unlocking the wallet

https://user-images.githubusercontent.com/17010094/181766002-7edb8fd3-88eb-4239-b226-8197dca7caa2.mp4


------------------------
Verification passed on

Brave | 1.42.80 Chromium: 104.0.5112.57 (Official Build) (64-bit) 
-- | --
Revision | `212fd173a0da1e0a024f328295bb56a2529190bb-refs/branch-heads/5112@{#1042}`
OS | Windows 11 Version 21H2 (Build 22000.795)

- Verified steps from [brave/brave-core#13960](https://github.com/brave/brave-core/pull/13960)
- Verified visiting `brave://wallet/crypto/portfolio/add-asset` route directly in a new tab still allows to add asset
- Verified loading the page route `brave://wallet/crypto/portfolio/add-asset` directly with wallet locked still allows to add asset after unlocking the wallet

https://user-images.githubusercontent.com/17010094/181765509-d7c78695-2eab-4f39-88b9-7cb2c905c176.mp4


------------------------
Verification passed on

Brave | 1.42.80 Chromium: 104.0.5112.57 (Official Build) (arm64) 
-- | --
Revision | `212fd173a0da1e0a024f328295bb56a2529190bb-refs/branch-heads/5112@{#1042}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [brave/brave-core#13960](https://github.com/brave/brave-core/pull/13960)
- Verified visiting `brave://wallet/crypto/portfolio/add-asset` route directly in a new tab still allows to add asset
- Verified loading the page route `brave://wallet/crypto/portfolio/add-asset` directly with wallet locked still allows to add asset after unlocking the wallet

https://user-images.githubusercontent.com/17010094/181766422-03749220-0dbe-4edd-b73e-7fe6034639f8.mov
