### ISSUE TITLE
Symbols generation is broken for Mac M1 builds

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#23696]
worked here https://github.com/brave/brave-browser/releases/tag/v1.37.92

doesn't work since ~ https://github.com/brave/brave-browser/releases/tag/v1.39.39

**Comment by atuchin-m** [comment]
https://github.com/brave/brave-browser/issues/24125

**Comment by LaurenWags** [comment]
Moving this issue to `1.42.x - Release` milestone as there was not a `1.41.x - Release #4` build which included this code (do note, it was merged to 1.41.x branch, just not released with 1.41.x).
