### ISSUE TITLE
Import from Vivaldi

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#23704]
## Description 

Follow-up to https://github.com/brave/brave-browser/issues/13334
Currently not showing options to import Vivaldi. 

## Steps to Reproduce

   1. Install Vivaldi and have a valid profile with some usage.
   2. Visit brave://settings/importData
   3. Try to import profile

## Actual result:

Profile not detected / shown in drop down

## Expected result:
Profile should be detected / shown in profile
Should offer information that's available including bookmarks, history, and saved passwords

## Reproduces how often: 

Easily.

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by spylogsster** [comment]
Opera moved to https://github.com/brave/brave-browser/issues/23738

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.43.61 Chromium: 104.0.5112.81 (Official Build) beta (64-bit)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | Windows 11 Version 21H2 (Build 22000.795)

```

Prerequisite: Download Vivaldi and and create multiple profiles 
<Details>

Before Vivaldi import
-----
![image](https://user-images.githubusercontent.com/98358127/183459961-eca2f4dd-6598-483b-ad6b-54dff0ec08d5.png)

 Profile 1 - Downloaded Vivaldi and added bookmarks/extensions/history

history|bookmarks|extensions
----|----|----
<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/183472138-bcd1fb61-cd4d-4e1b-af4a-d4d15deb495f.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/183472002-3350bd90-eea6-480b-bdd0-a31accae104b.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/183472181-2e7024c6-c2d8-41cd-811c-496ffbdc7d92.png">

Profile 2 - added bookmarks and imported bookmarks/passwords/history/use default profile location from `Microsoft Edge`

history|bookmarks|passwords
---|---|----
<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/183471497-d7e30bbe-b698-4fb8-8339-7955bc2a02b4.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/183471134-93c2084e-91c4-407a-9788-b0d2354b81c3.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/183471272-855cfa36-600b-4652-ad30-87783510c8bb.png">

Profile 3 - imported history and extensions from Chrome 

history|extensions
-----|-----
<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/183512400-bbfdcbbb-ecfe-4a85-9930-be381e83fa76.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/183512279-85a11827-2997-4b02-9bda-b54a02385be1.png">

</details>

#### <summary>Case 1: `Vivaldi` Profile 1- Import from clicking  `Import bookmarks now...` link on the bookmarks bar </summary> - `PASSED` </summary>
<Details>

1. Install 1.42.88
2. launch Brave
3. click `Skip welcome tour`
4. click `Import bookmarks now...`in the bookmarks bar
5. confirmed `Vivaldi` option displayed in the `Import bookmarks and settings` modal drop down
6. Select `Vivaldi Profile 1`
7. keep default selections 
    - `Browsing history`
    - `Favorites/Bookmarks`
    - `Saved passwords`
    - `Extensions`
8. click import
9. confirmation modal `Your bookmarks and settings are ready` is displayed as it's existing functionality
10. click Done
11. confirmed `Favorites/Bookmarks` shown in the `bookmarks bar` and `sidebar` and in `brave://settings/bookmarks`
12. confirmed   `Extensions` imported and  shown in `brave://extensions` 
13. confirmed `Browsing history` is imported and shown `brave://history`
14. All `bookmarks`/`passwords`/`extensions` are imported from `Vivaldi` correctly
15. clicked on a bookmark  (`bbc.com`) and the site is loaded

Step 4|Step 5|Step 6 & 7|Step 9|Step 11|Step12|Step 13|Step 14|Step 15
------|------|------|------|------|------|-----|-------|------
<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/183483956-096a6a5e-ab16-443b-8709-1650a2fe593a.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/183483754-c9ab3a54-3917-4bab-ac8c-b0e55d2e082c.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/183484211-6d6e5296-dc2a-4a43-8db4-fc1641ff6c9f.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/183484300-07e27dcc-f75e-4250-9da8-cdd986fcbe32.png">|<image width="950" alt="Step11" src="https://user-images.githubusercontent.com/98358127/183485565-4f89d3cf-5c5b-425d-923b-fed99c84a412.png">|<image width="950" alt="Step12" src="https://user-images.githubusercontent.com/98358127/183488422-5773ed43-2021-4bc4-93cf-bd79e232004f.png">|<image width="950" alt="Step11" src="https://user-images.githubusercontent.com/98358127/183486745-488ce942-0fae-4f2f-a9f7-bdfa811deb60.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/183488811-c245ebe3-b39e-4849-b80f-2cd72922fbc2.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/183487066-b6c90593-2a91-4065-a3c0-f22b4cac84e1.png">

</details>

#### <summary>Case 2: `Vivaldi` Profile 2 -  Import from `Hamburger menu` - `PASSED`  </summary>
<Details>

1. new profile
2. launch Brave
3. click `Hamburger menu`
4. click `Bookmarks`>>`Import bookmarks and settings`
5. confirmed both profiles `Vivaldi Profile 1` and `Vivaldi Profile 2`  and `Vivaldi Profile 3` options displayed in the `Import bookmarks and settings` modal 
6. select `Vivaldi Profile 2`
8. import only `Favorites/Bookmarks` option
9. click `Import` 
10. click `Done`
11. confirmed bookmarks shown in the `bookmarks bar` and `brave://settings/bookmarks`
12. confirmed bookmarks displayed in `Hamburger menu`>>`Bookmarks` 
13. confirmed `Microsoft Edge` bookmarks folder that originally imported into `Vivaldi` are imported  into `Brave

Step 3&4|Step 5|Step 6& 7|Step 10|Step 11 & Step 12
------|------|-------|------|------
<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/183492129-dca7bd19-8c72-4f88-8e4c-149b490a735d.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/183492257-e0ea773c-5b52-4977-b404-5771e5ea12c2.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/183492676-0ef6f47e-1125-4e37-a36a-fff59e596ccc.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/183493982-65376564-774f-49b8-a475-f7b6db483367.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/183505596-f51f66be-4a6c-4261-a009-bafbb23c671b.png">

</details>



</details>

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using



Brave | 1.43.63 Chromium: 104.0.5112.81 (Official Build) beta (x86_64)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | macOS Version 11.6.8 (Build 20G730)



Prerequisite: Download `Vivaldi` and create multiple profiles 
<Details>

Before Vivaldi import
-----


 Profile 1 - Downloaded Vivaldi and added history/bookmarks/extensions

history|bookmarks|extensions
----|----|----


Profile 2 - added bookmarks and imported history/bookmarks/passwords from `Microsoft Edge`

history|bookmarks|passwords
---|---|----


Profile 3 - imported bookmarks and passwords from Chrome 

passwords|bookmarks
-----|-----



</details>

#### <summary>Case 1: `Vivaldi` Profile 1- Import from `Import bookmarks now...` link on the bookmarks bar </summary> - `PENDING` </summary>
<Details>

1. Install 1.43.61
2. launch Brave
3. click `Skip welcome tour`
4. click `Import bookmarks now...` link in the bookmarks bar
5. confirmed `Vivaldi` option displayed in the drop down list of  `Import bookmarks and settings` modal 
6. Select `Vivaldi Profile 1`
7. keep default selections 
    - `Browsing history`
    - `Favorites/Bookmarks`
    - `Saved passwords`
    - `Extensions`
8. click import
9. confirmation modal `Your bookmarks and settings are ready` is displayed as it's existing functionality
10. click Done
11. confirmed `Favorites/Bookmarks` shown in the `bookmarks bar` and `sidebar` and in `brave://settings/bookmarks`
12. confirmed   `Extensions` imported and  shown in `brave://extensions` 
13. confirmed `Browsing history` is imported and shown `brave://history`
14. confirmed all `bookmarks`/`passwords`/`extensions/history` are imported from `Vivaldi` as expected
15. clicked on a bookmark  (`bbc.com`) and the site is loaded

Step 4|Step 5|Step 6 & 7|Step 9|Step 11|Step12|Step 13|Step 14|Step 15
------|------|------|------|------|------|-----|-------|------


</details>

#### <summary>Case 2: `Vivaldi` Profile 2 -  Import from `Hamburger menu` - `PENDING`  </summary>
<Details>

1. new profile
2. launch Brave
3. click `Hamburger menu`
4. click `Bookmarks`>>`Import bookmarks and settings`
5. confirmed  `Vivaldi Profile 2`  option displayed in the `Import bookmarks and settings` modal 
6. select `Vivaldi Profile 2` and import only `Favorites/Bookmarks` option
7. click `Import` 
8. click `Done`
9. confirmed bookmarks shown in the `bookmarks bar` and `brave://settings/bookmarks`
10. confirmed bookmarks displayed in `Hamburger menu`>>`Bookmarks` 
11. confirmed `Microsoft Edge` bookmarks folder that originally imported into `Vivaldi` are imported  into `Brave

Step 3&4|Step 5|Step 6& 7|Step 8|Step 10
------|------|-------|------|------


</details>

#### <summary>Case 3:  Multiple profiles - Import `Vivaldi Profile 1 & Profile 3` profiles  - `PENDING` </summary>
<Details>

1. new profile
2. launch Brave
3. click `Skip welcome tour`
4. visit `brave://settings/importData` to open `Import bookmarks and settings` modal
5. select `Vivaldi Profile 1` and import `Browsing History` and `Extensions` from the `Import bookmarks and settings` modal
6. click `import`
7. click `Done`
8. confirmed `Browsing History` and `Extensions` are successfully imported from `Vivaldi Profile 1`
9. return to `brave://settings/importData` to open `Import bookmarks and settings` modal again
10. select `Vivaldi  Profile 3` and import `Favorite Bookmarks` and `Saved passwords` and click `import`
11. confirmed  and `Favorites/Bookmarks` and `Saved passwords` are successfully imported from `Vivaldi Profile 3`

Step 5|Step 7|Step 8|Step 10|Step 11
-----|------|------|------|------


</details>

#### <summary>Case 4: Multiple browsers -  Import from `Vivaldi`  and `Microsoft Edge` - `PENDING` </summary>
<Details>

1. new profile
2. launch Brave
3. click `Import bookmarks now...`in the bookmarks bar
4. select `Vivaldi Profile 1` from the `Import bookmarks and settings` modal
5. keep default selections `Browsing history`, `Favorites/Bookmarks`, `Saved Passwords`, `Extensions`
6. click `Import` and click `Done`
7. confirmed successful import of  `Browsing history`, `Favorites/Bookmarks`, `Saved Passwords`, `Extensions` from `Vivaldi Profile 1` 
8. go to `brave://settings/importData` and click   `Import bookmarks and settings`
9.  select `Microsoft Edge Profile 2` from the `Import bookmarks and settings` modal
10. select `Browsing history`, `Favorites/Bookmarks`
11. click `Import` and click `Done`
12. confirmed successful import of `Browsing history`, `Favorites/Bookmarks` from `Microsoft Edge Profile 2`
13. `Imported from Micr....` folder shown in the `bookmarks bar` and in the `bookmarks sidebar`

Step 7|Step 12
-----|-----


</details>

#### <summary>Case 5: Bookmarks imported from `Vivaldi`  should `Sync` between devices - `PENDING` </summary>
<Details>

**device 1** 

1. new profile
2. launch Brave
3. click `Import bookmarks now...`in the bookmarks bar
4. select `Vivaldi` from `Import bookmarks and settings modal
5. keep default selections of `Browsing history`, `Favorites/Bookmarks`, `Saved Passwords`, `Extensions` and complete import
6. confirmed successful import of  `Browsing history`, `Favorites/Bookmarks`, `Saved Passwords`, `Extensions`
7. visit `brave://sync`
8. click on Start using sync>> `Start a new Sync Chain`
9. click `Computer`
10. copy the code words
11. under `Sync Settings`, click on the `Sync everything'

Step 5|Step6|Step10|Step 11
-------|--------|------|-----


***device 2** *

1. go to device 2
2. click on the "hamburger" menu, and then `Sync`
3. click `I have a Sync Code`
4. enter/paste the code words from `device 1`
5. click `Confirm`
6. click `OK`
7. under `Sync Settings`, click on the `Sync everything` toggle
8. confirmed `Favorites/Bookmarks`, `Saved Passwords`, `Extensions` synced successfully
9. confirmed `Browsing history` not synced.  Only URLs of the sites that were visited in the session are synced

Step 5& 6 |Step 7|Step 8&9
----|----|-----

</details>

#### <summary>Case 6:  Upgrade `1.42.88`  --->`1.43.63` - `PENDING` </summary>
<Details>

1. install `1.42.88`
2. launch Brave
3. click `Import bookmarks now` in the bookmarks bar
4. select `Chrome` in the `Import bookmarks and settings`
5. keep default selections of `Browsing history`, `Favorites/Bookmarks`, `Saved Passwords`, `Extensions` and complete import 
6. confirmed successful import of `Browsing history`, `Favorites/Bookmarks`, `Saved Passwords`, `Extensions`
7. close the browser
8. install `1.43.63`
9. relaunch Brave
10. confirmed `Browsing history`, `Favorites/Bookmarks`, `Saved Passwords`, `Extensions` are retained
11. go to `Hamburger menu`>>`Bookmarks`>>`Import bookmarks and settings`
12. select `Vivaldi Profile 1` 
13. keep default selections of `Browsing history`, `Favorites/Bookmarks`, `Saved Passwords`, `Extensions` and complete import
14. confirmed successful import from `Vivaldi Profile 3`

Step 1|Step 5|Step 6|Step 11|Step 12&13|Step 14
-----|------|------|------|------|------



</details>

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using

```
Brave | 1.43.74 Chromium: 104.0.5112.102 (Official Build) beta (64-bit)
-- | --
Revision | 8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}
OS | Linux
```
