### ISSUE TITLE
Tor: Support V3 onion services

### ISSUE THREAD

**Issue by aaronovz1** [brave/brave-browser#2370]
## Description 
Add support for V3 onion addresses

## Steps to Reproduce

   1. Visit https://trac.torproject.org/projects/tor/wiki/doc/NextGenOnions#Exampleprop224services
   2. Try to browse to any of the V3 onion addresses in a Tor window
   3. Page fails to load

## Actual result:
Page cannot be reached error

## Expected result:
Page loads

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

Brave | 0.56.15 Chromium: 70.0.3538.110 (Official Build) (64-bit)
-- | --
Revision | ca97ba107095b2a88cf04f9135463301e685cbb0-refs/branch-heads/3538@{#1094}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Not sure

**Comment by tomlowenthal** [comment]
Both @riastradh-brave and I can load <vww6ybal4bd7szmgncyruucpgfkqahzddi37ktceo3ah7ngmcopnpyyd.onion> fine. Can you try again with a fresh profile or a fresh install and let us know if it's still happening.

**Comment by aaronovz1** [comment]
Appears to load now when testing on:
`Version 0.57.18 Chromium: 71.0.3578.80 (Official Build) (64-bit)`
