### ISSUE TITLE
[Wallet] - No prompt to connect wallet upon clicking "connect" on Foundation.app

### ISSUE THREAD

**Issue by lukaslevert** [brave/brave-browser#23701]
## Description 
When attempting to connect Brave wallet on desktop to Foundation.app, I received no prompt to connect to the dApp. I was able to connect by manually opening Brave Wallet -> Connect -> Selecting desired wallet.

## Steps to Reproduce
   1. Visit https://foundation.app/
   2. Click Connect Wallet
   3. Nothing happens

## Brave version (brave://version info)
1.40.107 Chromium: 103.0.5060.53 (Official Build) (arm64)

**Comment by HEagle18** [comment]
I was able to replicate this issue

**Comment by bbondy** [comment]
Looks like they're blocking us intentionally via checking for `window.ethereum.isBraveWallet`.
I tweeted at them here to see if they will reply:
https://twitter.com/brianbondy/status/1541868810961145856

**Comment by bbondy** [comment]
The repo wagmi has some anti Brave Wallet code:
https://github.com/tmm/wagmi/blob/cd450ba3ebef074bd77b59544f21f65f2fabd0c2/packages/core/src/connectors/metaMask.ts#L49

Introduced here
https://github.com/tmm/wagmi/pull/436

I added a comment here:
https://github.com/tmm/wagmi/pull/436#issuecomment-1169173563

**Comment by bbondy** [comment]
https://github.com/tmm/wagmi/pull/436#issuecomment-1169191019

**Comment by bbondy** [comment]
Looks like they should use [`InjectedConnector`](https://wagmi.sh/docs/connectors/metaMask) instead of [`MetaMaskConnector`](https://wagmi.sh/docs/connectors/injected)

**Comment by bbondy** [comment]
Added another ask here https://twitter.com/brianbondy/status/1559630954297188352

**Comment by bbondy** [comment]
Unfortunately I'm going to close this issue since I can't seem to get a response from the CTO @fuJiin 
https://twitter.com/brianbondy/status/1559630954297188352
It is intentionally excluding other wallets because of the `MetaMaskConnector` usage instead of `InjectedConnector`.
