### ISSUE TITLE
Brave crashes in development mode when all Brave News sources are disabled

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#23711]
## Description 
There's a DCHECK that Feed is not nullptr in the generated mojom because the interface expects a `(Feed feed)` result not `(Feed? feed)`. The fix is to pass an empty feed instead of a nullptr.

## Steps to Reproduce

   1. Be in development mode
   2. Enable brave news
   3. Remove all feed sources
   4. Restart brave.

## Actual result:

The browser crashes after a few seconds

## Expected result:
The browser doesn't crash.

## Reproduces how often: 
Always, in development mode.

## Brave version (brave://version info)

1.42.7 Chromium: 103.0.5060.53 (Developer Build) (64-bit) ****

**Comment by petemill** [comment]
Marking as no QA since it requires local development build to fail.
