### ISSUE TITLE
Implement search conversion promotion in NTP

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#23724]

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.43.61 Chromium: 104.0.5112.81 (Official Build) beta (x86_64)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | macOS Version 11.6.8 (Build 20G730)

### Steps:

1. launched Brave with `--enable-features=BraveSearchNTP`
2. changed search provider in `brave://settings/search` to `Qwant`
3. opened NTP and confirmed promotion banner & search box is visible
4. confirmed promotion is hidden when NTP SI is background image
5. clicked outside of promotion makes it invisible and visible again after reloading
6. when window size gets narrow and promotion popup and other widgets are overlapped much, other widget will be hidden
7. clicked close(x) button in the popup and check popup is not visible anymore after reloading or creating another NTP

steps 1-2 | step 3 | step 4 | step 5 | step 6 | step 7
----------|-------|--------|-------|--------|-------
<img width="1312" alt="Screen Shot 2022-08-08 at 1 41 24 PM" src="https://user-images.githubusercontent.com/387249/183510705-53ddccdc-d646-4ff7-94e8-9bca6eacb1cd.png"> | <img width="1312" alt="Screen Shot 2022-08-08 at 1 41 38 PM" src="https://user-images.githubusercontent.com/387249/183510935-f0aa72ef-ec61-4a65-b098-f9e75c6c9915.png"> | <img width="1710" alt="Screen Shot 2022-08-08 at 1 42 10 PM" src="https://user-images.githubusercontent.com/387249/183510995-b89b7084-9d48-45d1-a161-28e98b5bb883.png"> |  <img width="1710" alt="Screen Shot 2022-08-08 at 1 41 54 PM" src="https://user-images.githubusercontent.com/387249/183511695-f901d030-6a3b-404b-ad93-c9df76ad34b2.png"> | <img width="873" alt="Screen Shot 2022-08-08 at 1 41 45 PM" src="https://user-images.githubusercontent.com/387249/183511900-d30f6514-ae5a-409b-9c5b-02a17c0d3db2.png"> | <img width="1710" alt="Screen Shot 2022-08-08 at 1 46 08 PM" src="https://user-images.githubusercontent.com/387249/183512002-95ae68af-5059-4a07-83fb-7f3089884f53.png">

**Comment by LaurenWags** [comment]
Removed `QA Pass-macOS` as part of the test plan has not been uplifted/is not available to verify with `1.43.61`.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.43.67 Chromium: 104.0.5112.81 (Official Build) beta (64-bit)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | Windows 11 Version 21H2 (Build 22000.856)
```

1. Installed 1.43.67
2. launch Brave with --enable-features=BraveSearchNTP
3. Open `brave://settings/search` and change search provider to `DuckDuckGo`
4. opened NTP and confirmed `promotion banner & search` box is visible
5. confirmed promotion is hidden when NTP SI is background image
6. confirmed clicking outside of the promotion bubble dismisses/hides, and then makes visible again, after reloading
7. confirmed when the window/viewport size narrows and other UI (potentially) clips the Search promotion, we have a responsive-design view of primarily the Search promo/widget
8. clicked close(x) button in the popup and verified popup is not visible anymore after reloading or creating another NTP


Step 3|Step 4|Step 5|Step 6|Step 7|Step 8
-------|------|-------|-------|-----|-----
<image width="950" alt="image" src= "https://user-images.githubusercontent.com/98358127/184210240-e3f28521-4808-43c7-ba77-e37c06be6b99.png">|<image width="950" alt="image" src= "https://user-images.githubusercontent.com/98358127/184210410-0727d675-dd62-4cf5-b3eb-5b5624328c60.png">|<image width="950" alt="image" src= "https://user-images.githubusercontent.com/98358127/184210579-d60306ce-36bb-44bb-9dd7-633b824c6b0e.png">|<image width="950" alt="image" src= "https://user-images.githubusercontent.com/98358127/184210730-e184e5bf-fb46-4e5e-88e2-e5920d70a360.png">|<image width="950" alt="image" src= "https://user-images.githubusercontent.com/98358127/184211270-1f474239-7bcb-4653-833f-0191117b3684.png">|<image width="950" alt="image" src= "https://user-images.githubusercontent.com/98358127/184211374-02346bc8-ff81-4aea-999f-f5abb0f5a509.png">

**Comment by LaurenWags** [comment]
Testing can be completed with 1.43.84 and above as translations have been included in that version.

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using 

Brave | 1.43.84 Chromium: 105.0.5195.68 (Official Build) (x86_64)
-- | --
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | macOS Version 11.6.8 (Build 20G730)



### Steps:

1.  installed `1.43.84`
2. launched Brave with `--enable-features=BraveSearchNTP`
3. changed search provider in `brave://settings/search` to `Qwant`
4. opened NTP and confirmed promotion banner & search box is visible
5. confirmed promotion is hidden when NTP SI is background image
6. confirmed clicking outside of the promotion bubble dismisses/hides, and then makes visible again, after reloading
7. confirmed when the window/viewport size narrows and other UI (potentially) clips the Search promotion, we have a responsive-design view of primarily the Search promo/widget
8. clicked close `(x)` button in the popup and confirmed the popup is not visible anymore after reloading or creating another NTP


step 3 | step 4 | step 5 | step 6 | step 7 | step 8
-------|-------|--------|--------|-------|-------
<img width="1312" alt="Screen Shot 2022-08-30 at 9 42 37 AM" src="https://user-images.githubusercontent.com/387249/187494283-b9c8d609-d41c-4220-80e6-349a613a78f8.png"> | <img width="1312" alt="Screen Shot 2022-08-30 at 9 42 49 AM" src="https://user-images.githubusercontent.com/387249/187494321-eb688027-91a2-4e71-b978-59cca668a914.png"> | <img width="1154" alt="Screen Shot 2022-08-30 at 9 45 28 AM" src="https://user-images.githubusercontent.com/387249/187494376-5516242a-32b9-43c6-9306-1077df42997e.png"> | <img width="875" alt="Screen Shot 2022-08-30 at 9 53 17 AM" src="https://user-images.githubusercontent.com/387249/187495098-b4c88861-09df-4e18-acbb-9cba54bbcdac.png"> | <img width="1154" alt="Screen Shot 2022-08-30 at 9 51 56 AM" src="https://user-images.githubusercontent.com/387249/187494818-92a9a408-3e04-40dd-a49f-1b1f8f0f81d2.png"> | <img width="1154" alt="Screen Shot 2022-08-30 at 9 45 28 AM" src="https://user-images.githubusercontent.com/387249/187495355-7a492c9c-cb94-46a6-bd86-1d22cb942100.png">

`French`

`Polish`

`Hindi`

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.43.83 Chromium: 105.0.5195.68 (Official Build) (64-bit)
-- | --
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | Ubuntu 18.04 LTS

de
![image](https://user-images.githubusercontent.com/34715963/187534357-0133e1c1-95d2-48c3-82fc-4b3e3be916f9.png)

en
![image](https://user-images.githubusercontent.com/34715963/187534588-76f3c55f-6fca-4b94-b10c-4ca7a34ff2b0.png)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave |	1.43.84 Chromium: 105.0.5195.68 (Official Build) (64-bit) 
-- | --
Revision |	ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS |	Windows 11 Version 21H2 (Build 22000.856)
```
1. Installed 1.43.67
2. launch Brave with --enable-features=BraveSearchNTP
3. Open `brave://settings/search` and change search provider to `DuckDuckGo`
4. opened NTP and confirmed `promotion banner & search` box is visible
5. confirmed promotion is hidden when NTP SI is background image
6. confirmed clicking outside of the promotion bubble dismisses/hides, and then makes visible again, after reloading
7. confirmed when the window/viewport size narrows and other UI (potentially) clips the Search promotion, we have a responsive-design view of primarily the Search promo/widget
8. clicked close(x) button in the popup and verified popup is not visible anymore after reloading or creating another NTP

`Portuguese (Brasil)`
<details>

Step 3|Step 4|Step 5|Step 6|Step 7|Step 8
-------|------|-------|-------|-----|-----
<image width="950" alt="image" src= "https://user-images.githubusercontent.com/98358127/187521209-f66bfb22-a703-4cc8-8ab2-34a8efdecdc3.png">|<image width="950" alt="image" src= "https://user-images.githubusercontent.com/98358127/187521308-4d8c49a0-8807-410d-8d31-bc6e2d49377b.png">|<image width="950" alt="image" src= "https://user-images.githubusercontent.com/98358127/187521430-67baea1e-a55f-4bfb-ae36-f589a034cbb9.png">|<image width="950" alt="image" src= "https://user-images.githubusercontent.com/98358127/187521604-938d7ad9-b973-45a3-b619-9dc931e60dee.png">|<image width="950" alt="image" src= "https://user-images.githubusercontent.com/98358127/187521903-21e7dde2-8435-41bf-ba75-40470385af25.png">|<image width="950" alt="image" src= "https://user-images.githubusercontent.com/98358127/187522440-9bc24181-e497-4dad-a9a5-6595018f427c.png">|<image width="950" alt="image" src= "https://user-images.githubusercontent.com/98358127/187522262-7c09532e-6264-449d-9f5f-8a636274bcdf.png">
</details>

`Korean`
<details>

Step 3|Step 4|Step 5|Step 6|Step 7|Step 8
-------|------|-------|-------|-----|-----
<image width="950" alt="Step3" src= "https://user-images.githubusercontent.com/98358127/187525474-11e25fc7-9e75-4140-9fb9-e89f72be2241.png">|<image width="950" alt="Step4" src= "https://user-images.githubusercontent.com/98358127/187525603-758a4a60-c91f-45f2-b787-6eb6797ba9c9.png">|<image width="950" alt="Step5" src="https://user-images.githubusercontent.com/98358127/187525546-c9eafeac-83a4-42ac-bb5c-e67abdd95ead.png">|<image width="950" alt="Step6" src="https://user-images.githubusercontent.com/98358127/187525699-e0820508-ce89-4528-9cf5-6633ac4c36a5.png">|<image width="950" alt="Step7" src="https://user-images.githubusercontent.com/98358127/187525832-af56e833-9f67-4efe-8993-57e191904e60.png">|<image width="950" alt="Step8" src="https://user-images.githubusercontent.com/98358127/187525891-10d3393b-3fb3-468f-bc87-b6d03811eea5.png">
</details>


`Romanian`
<details>

Step 3|Step 4|Step 5|Step 6|Step 7|Step 8
-------|------|-------|-------|-----|-----
<image width="950" alt="image" src= "https://user-images.githubusercontent.com/98358127/187532149-2c0e23e7-9146-4d60-85d9-c2175398fee0.png">|<image width="950" alt="image" src= "https://user-images.githubusercontent.com/98358127/187532265-5189c62a-87b6-4293-b6f9-8abf502027fe.png">|<image width="950" alt="image" src= "https://user-images.githubusercontent.com/98358127/187532224-789404bb-aece-4ebc-96a1-c503a40921b9.png">|<image width="950" alt="image" src= "https://user-images.githubusercontent.com/98358127/187532397-63e447c5-a994-4c3e-b57b-d9cd10886db6.png">|<image width="950" alt="image" src= "https://user-images.githubusercontent.com/98358127/187532446-bf3934c7-c009-4620-9937-98718dda028a.png">|<image width="950" alt="image" src= "https://user-images.githubusercontent.com/98358127/187532538-2db89960-c6ef-4d9b-8b26-56efca9241c0.png">|
</details>

`Hindi`
<details>

Step 3|Step 4|Step 5|Step 6|Step 7|Step 8
-------|------|-------|-------|-----|-----
<image width="950" alt="image" src= "https://user-images.githubusercontent.com/98358127/187535398-804033fb-58cb-46e1-b582-27e4f470d9a1.png">|<image width="950" alt="image" src= "https://user-images.githubusercontent.com/98358127/187536290-fc7f68f5-8999-4ccf-bee7-7cc3aaa59972.png">|<image width="950" alt="image" src= "https://user-images.githubusercontent.com/98358127/187536222-a93d3374-2555-43ee-9308-0cb4535c3837.png">|<image width="950" alt="image" src= "https://user-images.githubusercontent.com/98358127/187536436-d4b80362-fe04-41cb-8505-ad5ad116f7d1.png">|<image width="950" alt="image" src= "https://user-images.githubusercontent.com/98358127/187536515-c66e44ed-5afb-40f3-a2a2-b575d44a1d52.png">|<image width="950" alt="image" src= "https://user-images.githubusercontent.com/98358127/187536575-d62e49ef-8150-4a7d-8a35-1d870aa91ffa.png">|
</details>
