### ISSUE TITLE
Don't receive ads behind a VPN on Linux

### ISSUE THREAD

**Issue by Zerophase** [brave/brave-browser#23727]
## Description 

Ads don't get served while behind a VPN on Linux. Ads get served if on Windows still. If you switch the VPN end point to another country and back ads get served again, until the DNS updates.

## Steps to Reproduce

   1. Use Mulvad, and set your connection behind wireguard through the router.
   2. Login to Windows, and receive ads.
   3. Login to Linux and do not receive ads.

## Actual result:
No ads on Linux.

## Expected result:
Ads on linux

## Reproduces how often: 
All the time.

## Brave version (brave://version info)
1.40.107

## Version/Channel Information:
Been happening for about a year. On current.

**Comment by tmancey** [comment]
Closing as working as expected
