### ISSUE TITLE
Display the transaction hash while awaiting a response from a HW wallet so the user can visually confirm the hashes match

### ISSUE THREAD

**Issue by kdenhartog** [brave/brave-browser#23721]
In a wallet extension (connect confirm) UI panel where a user is being asked to confirm the transaction on their device we should display the transaction hash and a warning to the user to visually confirm that the transaction being signed by the hardware wallet matches what was sent to the wallet. 

The reason for this is to make it possible for the user to confirm that the message being sent matches the message received on the hardware wallet in order to avoid a compromise in the confirmation flow where the displayed transaction doesn't match the transaction being signed by the wallet.

**Comment by nvonpentz** [comment]
Currently, we show this screen when users are signing transactions on their ledger device:
![image](https://user-images.githubusercontent.com/12549658/176495265-bd0c9735-534b-4c64-ab2d-08ada64d6767.png)

**Comment by kdenhartog** [comment]
Ok, thanks for confirming since this is what I was hoping was actually in there. I checked Figma since I don't have a HW wallet to verify the current flow with. 

I think if we add the transaction hash with a warning to the user about manually checking the hash into this screen we should be able to declare this one done.

**Comment by muliswilliam** [comment]
@kdenhartog Ledger device does not show a transaction has. It shows `amount`, `address`, `network`, `max fees` so the user will not have a transaction hash to compare to.

**Comment by onyb** [comment]
A hash is only displayed on the device if user is trying to do a "blind sign" (see https://support.ledger.com/hc/en-us/articles/4405481324433-Enable-blind-signing-in-the-Ethereum-ETH-app). I believe it's a hash of the transaction `data`, not the transaction hash itself.

**Comment by kdenhartog** [comment]
Yeah havinng the transaction data hash is what I had in mind since @orspetol and I wanted to be sure that the user wasn't encountering an issue where the transaction data is being tampered with over the bluetooth / web HID/ web USB channel. Is there a way for us to detect if blind sign is in use to be able to display this here? I'm less worried about the case where it's a non-blind sign scenario since the user can verify all the data properly on the actual ledger device.

**Comment by onyb** [comment]
> wanted to be sure that the user wasn't encountering an issue where the transaction data is being tampered with over the bluetooth / web HID/ web USB channel

Confirming the transaction data hash on the Ledger device is not enough. The tampering could be on Brave Wallet side, in which case the hashes would match but it is still a malicious transaction.

We need to be able to parse the transaction data on both the confirmation screen in Brave Wallet as well as Ledger device, to be able to consider something fully safe to sign. We could display the data hash in the confirmation screen, but it doesn't change the fact that the transaction is inherently dangerous to sign.

> Is there a way for us to detect if blind sign is in use

Maybe with [ETH Plugins](https://github.com/LedgerHQ/app-ethereum/blob/develop/doc/ethapp_plugins.asc), but I'm not sure if our current hardware wallet integration is able to use plugins.

**Comment by kdenhartog** [comment]
Spoke with @diracdeltas about this one. Seems like something that would be best handled by dApps instead. If someone else comes up with a better solution, please re-open/ping me.
