### ISSUE TITLE
Import from Opera

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#23738]
## Description 

Follow-up to https://github.com/brave/brave-browser/issues/23704
Currently not showing options to import  Opera.

## Steps to Reproduce

   1. Install Opera and have a valid profile with some usage.
   2. Visit brave://settings/importData
   3. Try to import profile

## Actual result:

Profile not detected / shown in drop down

## Expected result:
Profile should be detected / shown in profile
Should offer information that's available including bookmarks, history, and saved passwords

## Reproduces how often: 

Easily.

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.43.61 Chromium: 104.0.5112.81 (Official Build) beta (64-bit)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | Windows 11 Version 21H2 (Build 22000.795)

```

Prerequisite: Download Opera and create data to import 
<Details>

 Default - Downloaded Opera and added history/bookmarks/saved passwords

history|bookmarks|extensions|saved passwords
----|----|----|-----
<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/183524713-05f029cb-9c8b-4cc9-889f-d0e1cfbd3205.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/183524225-1cb527ea-f7e5-4337-8a3f-493c0f86757b.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/183524789-446a63c2-2ced-4e5f-879e-09c3be4430a5.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/183534487-101481e6-9f0e-4b34-9449-cc8bfb7e04c2.png">


</details>

#### <summary> Case 1: `Opera` import from clicking  `Import bookmarks now...` link on the bookmarks bar - `PASSED` </summary>
<Details>

1. Install 1.42.88
2. launch Brave
3. click `Skip welcome tour`
4. click `Import bookmarks now...`in the bookmarks bar
5. confirmed `Opera` option displayed in the `Import bookmarks and settings` modal drop down
6. Select `Opera Default`
7. keep default selections 
    - `Browsing history`
    - `Favorites/Bookmarks`
    - `Saved passwords`
8. click import
9. confirmation modal `Your bookmarks and settings are ready` is displayed as it's existing functionality
10. click Done
11. confirmed `Favorites/Bookmarks` shown in the `bookmarks bar` and `sidebar` and in `brave://bookmarks`
12. confirmed `Browsing history` is imported and shown `brave://history`
13. confirmed `Saved passwords` imported and shown `brave://settings/passwords`
14. All `bookmarks`/`passwords`/`extensions` are imported from `Opera` correctly
15. clicked on a bookmark  (`waltmart.com`) and the site is loaded

Step5|Step 6 & 7|Step 9|Step 11|Step12|Step 13|Step 14|Step 15
------|------|------|------|------|------|-----|------
<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/183525083-e1f600ad-848e-439e-a66d-fd94dccfbfa1.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/183527115-81279dc3-bf16-4b9a-8696-21839c21f769.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/183525433-effdfa1a-cbc7-4752-85d3-693761585936.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/183531124-7ec10b8e-8821-4ea5-9b0f-20dc247b130a.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/183525846-8d3d5ecc-0d72-4d3e-a6e9-dbb8e5fe1748.png">|<image width="950" alt="Step11" src="https://user-images.githubusercontent.com/98358127/183526024-da9c9356-c7d4-4e03-851d-0f428c7ab9fe.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/183531584-644d94d6-05fc-43b9-b798-af6aa64a2ccd.png">|<image width="950" alt="Step12" src="https://user-images.githubusercontent.com/98358127/183526179-59c58e4e-2740-409d-b850-189a2eb0b36b.png">

</details>

#### <summary> Case 2: `Opera`  import from `brave://settings/importData` - `PASSED` </summary>
<Details>

1. new profile
2. launch Brave
3. click `Skip welcome tour`
4. visit `brave://settings/importData`
5. select `Opera Default` from the drop down list in the `Import bookmarks and settings`
6. click `import`
7. confirmation modal `Your bookmarks and settings are ready` is displayed as it's existing functionality
8. click `Done`
9. confirmed `Favorites/Bookmarks` shown in the `bookmarks bar` and `sidebar` and in `brave://bookmarks`
10. confirmed `Browsing history` is imported and shown `brave://history`
11. clicked on a bookmark  (`nytimes.com`) and the site is loaded

Step 5|Step 6& 7 |Step 8|Step 9|Step10|Step 11
-----|------|------|------|------|-----
<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/183530118-79867032-903d-44c6-8378-8dfa86c484e4.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/183530167-8467e497-8659-4c51-a8dd-ced5fdba68d6.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/183530330-d88ebed0-4882-4f19-b5c0-1233f96ae55a.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/183530372-b0fb0bdf-414e-4fca-a2fe-ced677018008.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/183533299-b3081251-33f0-47f3-a9e6-a9a216dad4a3.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/183533230-41338a72-9a41-4371-a93e-a3674732bada.png">|

</details>

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using



Brave | 1.43.63 Chromium: 104.0.5112.81 (Official Build) beta (x86_64)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | macOS Version 11.6.8 (Build 20G730)



Prerequisite: Download Opera and create data to import
<Details>

 Default - Downloaded Opera and added history/bookmarks/saved passwords

history|bookmarks|extensions|saved passwords
----|----|----|-----


</details>

#### <summary> Case 1: `Opera` import from clicking  `Import bookmarks now...` link on the bookmarks bar - `PENDING` </summary>
<Details>

1. Install `1.43.63`
2. launch Brave
3. click `Skip welcome tour`
4. click `Import bookmarks now...` in the bookmarks bar
5. confirmed `Opera` option displayed in the `Import bookmarks and settings` modal drop down
6. Select `Opera Default`
7. keep default selections 
    - `Browsing history`
    - `Favorites/Bookmarks`
    - `Saved passwords`
8. click import
9. confirmation modal `Your bookmarks and settings are ready` is displayed as it's existing functionality
10. click Done
11. confirmed `Favorites/Bookmarks` shown in the `bookmarks bar` and `sidebar` and in `brave://bookmarks`
12. confirmed `Browsing history` is imported and shown `brave://history`
13. confirmed `Saved passwords` imported and shown `brave://settings/passwords`
14. All `Browsing history`/`Favorites/Bookmarks`/`Saved passwords` are imported from `Opera` correctly
15. clicked on a bookmark  (`ktvu.com`) and the site is loaded

Step5|Step 6 & 7|Step 9|Step 11|Step12|Step 13|Step 14|Step 15
------|------|------|------|------|------|-----|------


</details>

#### <summary> Case 2: `Opera`  import from `brave://settings/importData` - `PENDING` </summary>
<Details>

1. new profile
2. launch Brave
3. click `Skip welcome tour`
4. visit `brave://settings/importData`
5. select `Opera Default` from the drop down list in the `Import bookmarks and settings`
6. select `Favorites/Bookmarks` and `Browsing history` 
7. click `import`
8. confirmation modal `Your bookmarks and settings are ready` is displayed as it's existing functionality
9. click `Done`
10. confirmed `Favorites/Bookmarks` shown in the `bookmarks bar` and `sidebar` and in `brave://bookmarks`
11. confirmed `Browsing history` is imported and shown `brave://history`
12. clicked on a bookmark  (`nytimes.com`) and the site is loaded

Step 5& 6|Step 8 |Step 10|Step11|Step 12
-----|------|------|------|------



</details>

#### <summary>Case 3: Bookmarks imported from `Opera`  should `Sync` between devices - `PENDING` </summary>
<Details>

**device 1** 

1. new profile
2. launch Brave
3. click `Import bookmarks now...`in the bookmarks bar
4. select `Opera Default` from `Import bookmarks and settings modal
5. keep default selections of `Browsing history`, `Favorites/Bookmarks`, `Saved Passwords`, `Extensions` and complete import
6. confirmed successful import of  `Browsing history`, `Favorites/Bookmarks`, `Saved Passwords`, `Extensions`
7. visit `brave://sync`
8. click on Start using sync>> `Start a new Sync Chain`
9. click `Computer`
10. copy the code words
11. under `Sync Settings`, click on the `Sync everything'

Step 5|Step6|Step10|Step 11
-------|--------|------|-----


**device 2**

1. go to device 2
2. click on the "hamburger" menu, and then `Sync`
3. click `I have a Sync Code`
4. enter/paste the code words from `device 1`
5. click `Confirm`
6. click `OK`
7. under `Sync Settings`, click on the `Sync everything` toggle
8. confirmed `Favorites/Bookmarks`, `Saved Passwords`, `Extensions` synced successfully
9. confirmed `Browsing history` not synced.  Only URLs of the sites that were visited in the session are synced

</details>

#### <summary>Case 4:  Upgrade `1.42.88`--->`1.43.63` - `PENDING` </summary>
<Details>

1. install `1.42.88`
2. launch Brave
3. click `Import bookmarks now...` link in the `bookmarks bar`
4. select `Chrome` in the `Import bookmarks and settings` modal
5. keep default selections of `Browsing history`, `Favorites/Bookmarks`, `Saved Passwords`, `Extensions` and complete import 
6. confirmed successful import of `Browsing history`, `Favorites/Bookmarks`, `Saved Passwords`, `Extensions` into Brave
7. close the browser
8. install `1.43.63
9. relaunch Brave
10. `Browsing history`, `Favorites/Bookmarks`, `Saved Passwords`, `Extensions` are retained
11.  go to `Hamburger menu`>>`Bookmarks`>>`Import bookmarks and settings`
12. confirmed 'Opera Default` is  listed in the drop down menu of  `Import bookmarks and settings` modal
13. select `Opera Default`  and keep default selections of `Browsing history`, `Favorites/Bookmarks`, `Saved Passwords` 
14. complete import
15. confirmed successfully imported `Browsing history`, `Favorites/Bookmarks`, and `Saved Passwords` from `Opera` 


Step 1|Step 4& 5|Step5& 6|Step 6|Step 11|Step 12|Step 13|Step 14|Step 15
-----|------|------|------|------|------|------|-------|------

</details>

### Encountered:
* .

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.43.74 Chromium: 104.0.5112.102 (Official Build) beta (64-bit)
-- | --
Revision | 8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}
OS | Linux
JavaScript | V8 10.4.132.22
```
Prerequisite: Download Opera and create data to import
<Details>

 Default - Downloaded Opera and added history/bookmarks/saved passwords

history|bookmarks|extensions|saved passwords
----|----|----|-----
<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/185496973-844f2176-07c5-4055-80fa-e437c3693372.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/185497094-7e32f5ab-12eb-42b7-8c1d-dd2a8044991b.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/185497243-aabc0bbb-a7ae-46fc-8709-d4963311a8bc.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/185497193-073093c9-19fa-4b41-b136-cc402ead5c32.png">

</details>

#### <summary> Case 1: `Opera` import from clicking  `Import bookmarks now...` link on the bookmarks bar - `PASSED` </summary>
<Details>

1. Install 1.43.74
2. launch Brave
3. click `Skip welcome tour`
4. click `Import bookmarks now...`in the bookmarks bar
5. confirmed `Opera` option displayed in the `Import bookmarks and settings` modal drop down
6. Select `Opera Default`
7. keep default selections 
    - `Browsing history`
    - `Favorites/Bookmarks`
    - `Saved passwords`
8. click import
9. confirmation modal `Your bookmarks and settings are ready` is displayed as it's existing functionality
10. click Done
11. confirmed `Favorites/Bookmarks` shown in the `bookmarks bar` and `sidebar` and in `brave://bookmarks`
12. confirmed `Browsing history` is imported and shown `brave://history`
13. confirmed `Saved passwords` imported and shown `brave://settings/passwords`
14. All `Browsing history`/`Favorites/Bookmarks` are imported from `Opera` correctly
15. clicked on a bookmark  (`bbc.com`) and the site is loaded

Step 6 & 7|Step 9|Step 11|Step12
------|------|------|------
<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/185497771-10e24471-6258-4013-ab82-fbbbb270690d.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/185498124-c9a66983-80d9-4e9f-a8f8-7568c9d565a6.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/185499121-3283249d-6d81-47a7-a62e-52b1656f3caa.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/185498419-baf4146b-9a65-4339-a575-8b151ce9e992.png">
</details>

#### <summary> Case 2: `Opera`  import from `brave://settings/importData` - `PASSED` </summary>
<Details>

1. new profile
2. launch Brave
3. click `Skip welcome tour`
4. visit `brave://settings/importData`
5. select `Opera Default` from the drop down list in the `Import bookmarks and settings`
6. select `Favorites/Bookmarks` and `Browsing history` 
7. click `import`
8. confirmation modal `Your bookmarks and settings are ready` is displayed as it's existing functionality
9. click `Done`
10. confirmed `Favorites/Bookmarks` shown in the `bookmarks bar` and `sidebar` and in `brave://bookmarks`
11. confirmed `Browsing history` is imported and shown `brave://history`
12. clicked on a bookmark  (`nytimes.com`) and the site is loaded

Step 5& 6|Step 8 |Step 10|Step11|Step 12
-----|------|------|------|------
