### ISSUE TITLE
update Brave search logo on NTP Private Window/Tor

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#23732]
## Description 

Follow-up issue to https://github.com/brave/brave-browser/issues/22566.

Use Brave logo instead of Brave logo `beta` image 

## Steps to Reproduce

   1. Open NTP Private Window and Private Window with Tor
   2. Notice beta logo. Should have no beta image.

## Actual result:

<img width="1409" alt="Screen Shot 2022-06-28 at 7 40 46 AM" src="https://user-images.githubusercontent.com/5951041/176208682-9c68d0a9-88a6-4edd-b37f-ed2adc071e18.png">

## Expected result:
<img width="891" alt="Screen Shot 2022-06-28 at 9 26 31 AM" src="https://user-images.githubusercontent.com/5951041/176273356-4a15860d-644c-47ea-8b83-d03ce0dd831e.png">

## Reproduces how often: 

Easily

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the nightly channel? 1.42.33 and higher

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.42.62 Chromium: 103.0.5060.114 (Official Build) beta (x86_64)
-- | --
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | macOS Version 11.6.7 (Build 20G630)

### Steps:
1. installed `1.42.62`
2. launched Brave
3. opened a new `Private Window`
4. opened a new `Private Window with Tor`
5. opened a new `Guest Window`
6. confirmed the `Brave` logo no longer has the `beta` wordmark

#### Functionality was verified over in https://github.com/brave/brave-browser/issues/22566.

`Private Window` | `Private Window with Tor` | `Guest Window`
------------------|----------------------------|-----------------
<img width="1312" alt="Screen Shot 2022-07-12 at 2 22 40 PM" src="https://user-images.githubusercontent.com/387249/178606783-c2eaf366-2133-4157-85de-9b0da19fa583.png"> | <img width="1312" alt="Screen Shot 2022-07-12 at 3 27 07 PM" src="https://user-images.githubusercontent.com/387249/178607426-3e3e7f20-9f76-4f0a-997c-34c56ec17144.png"> | <img width="1312" alt="Screen Shot 2022-07-12 at 2 25 54 PM" src="https://user-images.githubusercontent.com/387249/178607006-bb9b40b7-c94a-4236-b042-cf57e6556775.png">

Encountered:
* https://github.com/brave/brave-browser/issues/23999
* https://github.com/brave/brave-browser/issues/23979

**Comment by MadhaviSeelam** [comment]
Verification `Complete` using
```
Brave | 1.42.68 Chromium: 103.0.5060.114 (Official Build) beta (64-bit)
-- | --
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | Windows 11 Version 21H2 (Build 22000.795)
```

### Steps:
1. installed `1.42.682`
2. launched Brave
3. opened a new `Private Window with Tor`
4. opened a new `Private Window`
6. opened a new `Guest Window`
7. confirmed the `Brave` logo no longer has the `beta` wordmark


`Private Window with Tor`|`Private Window`|`Guest Window`
----|----|----
<image width="750" alt="TOR" src="https://user-images.githubusercontent.com/98358127/179636284-91914cce-1823-4593-8acf-32d41c43fecb.png">|<image width="750" alt="TOR" src="https://user-images.githubusercontent.com/98358127/179636374-f0bc1de6-fc68-47d6-be31-c7bb87fafd16.png">|<image width="750" alt="TOR" src="https://user-images.githubusercontent.com/98358127/179636405-4f735292-ed4a-4fa6-a341-e5c4baa1eb0e.png">

Reproduced already file bugs #23999 & #23979
