### ISSUE TITLE
Get guardian vpn alerts for privacy hub

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#23736]
The "timestamp" field is optional. Send 0 to get everything and do on device sorting between duplicates that you have already downloaded or store the date/timestamp of the last alerts download and pass that as the timestamp as a UNIX timestamp in seconds (!) to the API to only get alerts that were stored after the last download.

POST /api/v1.2/device/<client-id>/alerts
{
    "api-auth-token": "<api-auth-token passed a string here",
    "timestamp": 0 <- zero is an example here. It is an optional int aka. JSON number and therefore transferred as a float64 since JS sucks
}

**Comment by bsclifton** [comment]
Closing as stale. Let's create a new issue / re-open once we have some planned work
