### ISSUE TITLE
set macOS minimum version to 10.13 for 1.42.x in Sparkle

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#23748]
## Description 

Brave 1.42.x with Chromium 104 will require macOS 10.13 High Sierra and higher. 
Those with Brave 1.41.x and 10.12 (Sierra) and 10.11 (El Capitan) or lower should not be prompted with an update to 1.42.x 

## Steps to Reproduce

   1. Run 10.12 Sierra or lower with 1.41.x installed.
   2. Should not be prompted to update when 1.42.x is made available.

## Brave version (brave://version info)

1.41.x with macOS 10.12 Sierra and lower.

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by rebron** [comment]
cc: @mihaiplesa @simonhong @mherrmann

**Comment by rebron** [comment]
Message in Chrome. https://github.com/chromium/chromium/blob/dfb0dcea77108cba550fd41941ec941ca866a7b3/chrome/app/resources/chromium_strings_en-GB.xtb#L335

**Comment by simonhong** [comment]
@mherrmann @mihaiplesa How about handling this via `brave::UpdateEnabled()` - https://github.com/brave/brave-core/blob/master/browser/update_util.cc like below? 

```
bool UpdateEnabled() {
#if defined(OFFICIAL_BUILD)
 // Check brave & macOS version and return false here?

  return !base::CommandLine::ForCurrentProcess()->HasSwitch(
      switches::kDisableBraveUpdate);
#else
  return false;
#endif
}
```

**Comment by mherrmann** [comment]
I think we already implemented this in https://github.com/brave/brave-browser/issues/22918. See `minimumSystemVersion` in https://updates.bravesoftware.com/sparkle/Brave-Browser/stable/appcast.xml. There, Sparkle versions are marked with the minimum required macOS version. If a user tries to update from a lower macOS version, then they won't be prompted. The code that sets `minimumSystemVersion` to the correct value for a release is in https://github.com/brave/devops/pull/7544/files.

**Comment by rebron** [comment]
cc: @mherrmann  @mkarolin We want to do this before CR 104 merges into nightly so we can test in nightly and beta.

**Comment by mihaiplesa** [comment]
@rebron this is in since 1.39.x.

**Comment by kjozwiak** [comment]
Quick update on the clean install cases, went through https://github.com/brave/brave-browser/issues/24199#issuecomment-1191936448 and ensured that the `C104` executable warned the user with while they were installing. Also ensured that you can't launch Brave once installed. Also ensured that you can install it without any issues via `High Sierra`.

**Comment by mihaiplesa** [comment]
Went and purged old updates that didn't have a minimum version set in Omaha, we're good to close now. Newer versions specify the minimum system version.

**Comment by kjozwiak** [comment]
## `macOS 10.11 El Captain Test Cases`

### `Nightly` channel

Verification **PASSED** on `macOS 10.12 Sierra x64` using the following build(s):

```
Brave | 1.43.42 Chromium: 103.0.5060.134 (Official Build) nightly (x86_64)
--- | ---
Revision | 8ec6fce403b3feb0869b0732eda8bd95011d333c-refs/branch-heads/5060@{#1262}
OS | macOS Version 10.12.6 (Build 16G2136)
```

* downloaded/installed `1.43.42 Chromium: 103.0.5060.134` which is on `C103`
* ensured that the warning notification appears on first launch re: needing `macOS 10.13` or higher
* loaded `brave://settings/help` and ensured that the browser wasn't installed
* ensured that there's a warning re: needing `macOS 10.13` (basically the same message as per the notification at startup)
* ensured that clicking on `Learn More` opens the following URL in a new tab
  * `https://support.brave.com/hc/en-us/articles/360025390311-How-do-I-download-and-install-Brave-`

**`Example`** | **`Example`**
---------------|-----------------
<img width="1213" alt="Screen Shot 2022-07-29 at 12 45 16 AM" src="https://user-images.githubusercontent.com/2602313/181685194-41cccaeb-f0a7-4a36-bf00-c76db2f5924d.png"> | <img width="1409" alt="Screen Shot 2022-07-29 at 12 46 28 AM" src="https://user-images.githubusercontent.com/2602313/181685204-ea29e6bb-3061-43d6-bbd8-34147ce53737.png">

## `macOS 10.12 Sierra Test Cases`

### `Nightly` channel

Verification **PASSED** on `macOS 10.12 Sierra x64` using the following build(s):

```
Brave | 1.43.42 Chromium: 103.0.5060.134 (Official Build) nightly (x86_64)
--- | ---
Revision | 8ec6fce403b3feb0869b0732eda8bd95011d333c-refs/branch-heads/5060@{#1262}
OS | macOS Version 10.12.6 (Build 16G2136)
```

* downloaded/installed `1.43.42 Chromium: 103.0.5060.134` which is on `C103`
* ensured that the warning notification appears on first launch re: needing `macOS 10.13` or higher
* loaded `brave://settings/help` and ensured that the browser wasn't installed
* ensured that there's a warning re: needing `macOS 10.13` (basically the same message as per the notification at startup)
* ensured that clicking on `Learn More` opens the following URL in a new tab
  * `https://support.brave.com/hc/en-us/articles/360025390311-How-do-I-download-and-install-Brave-`

**`Example`** | **`Example`**
---------------|-----------------
<img width="1213" alt="Screen Shot 2022-07-29 at 12 45 16 AM" src="https://user-images.githubusercontent.com/2602313/181685194-41cccaeb-f0a7-4a36-bf00-c76db2f5924d.png"> | <img width="1409" alt="Screen Shot 2022-07-29 at 12 46 28 AM" src="https://user-images.githubusercontent.com/2602313/181685204-ea29e6bb-3061-43d6-bbd8-34147ce53737.png">

### `BETA` channel

Verification **PASSED** on `macOS 10.12 Sierra x64` using the following build(s):

```
Brave | 1.42.78 Chromium: 103.0.5060.134 (Official Build) beta (x86_64)
--- | ---
Revision | 8ec6fce403b3feb0869b0732eda8bd95011d333c-refs/branch-heads/5060@{#1262}
OS | macOS Version 10.12.6 (Build 16G2136)
```

* downloaded/installed `1.42.78 Chromium: 103.0.5060.134` which is on `C103`
* ensured that the warning notification appears on first launch re: needing `macOS 10.13` or higher
* loaded `brave://settings/help` and ensured that the browser wasn't installed
* ensured that there's a warning re: needing `macOS 10.13` (basically the same message as per the notification at startup)
* ensured that clicking on `Learn More` opens the following URL in a new tab
  * `https://support.brave.com/hc/en-us/articles/360025390311-How-do-I-download-and-install-Brave-`

**`Example`** | **`Example`**
---------------|-----------------
<img width="1228" alt="Screen Shot 2022-07-29 at 12 58 03 AM" src="https://user-images.githubusercontent.com/2602313/181685971-12db7bc7-f76e-4431-8645-a6349b7820a7.png"> | <img width="1222" alt="Screen Shot 2022-07-29 at 12 58 23 AM" src="https://user-images.githubusercontent.com/2602313/181685978-682919c2-59f2-497d-a4f4-f9a77a1c6cb5.png">

### `Release` channel

Verification **PASSED** on `macOS 10.12 Sierra x64` using the following build(s):

```
Brave | 1.41.100 Chromium: 103.0.5060.134 (Official Build) (x86_64)
--- | ---
Revision | 8ec6fce403b3feb0869b0732eda8bd95011d333c-refs/branch-heads/5060@{#1262}
OS | macOS Version 10.12.6 (Build 16G2136)
```

Launched using the following before going through the STR/Cases:

```
--update-feed-url=https://updates.bravesoftware.com/sparkle/Brave-Browser/beta/appcast.xml
```

* downloaded/installed `1.41.100 Chromium: 103.0.5060.134` which is on `C103`
* ensured that the warning notification appears on first launch re: needing `macOS 10.13` or higher
* loaded `brave://settings/help` and ensured that the browser wasn't installed
* ensured that there's a warning re: needing `macOS 10.13` (basically the same message as per the notification at startup)
* ensured that clicking on `Learn More` opens the following URL in a new tab
  * `https://support.brave.com/hc/en-us/articles/360025390311-How-do-I-download-and-install-Brave-`

**`Example`** | **`Example`**
---------------|-----------------
<img width="1215" alt="Screen Shot 2022-07-29 at 1 06 46 AM" src="https://user-images.githubusercontent.com/2602313/181686883-9e346f62-2d09-4b05-a686-5271483c7737.png"> | <img width="1221" alt="Screen Shot 2022-07-29 at 1 07 03 AM" src="https://user-images.githubusercontent.com/2602313/181686888-8faf6813-824e-4fe5-8350-bb5853838e21.png">

**Comment by LaurenWags** [comment]
Using 10.13.6 High Sierra (VM), double checked able to:
* Install `1.41.100 Chromium: 103.0.5060.134` and upgrade to `1.42.84 Chromium: 104.0.5112.69`. Closed and relaunched several times.
* Install `1.42.84 Chromium: 104.0.5112.69`. Closed and relaunched several times.

```
Brave	1.42.84 Chromium: 104.0.5112.69 (Official Build) (x86_64) 
Revision	7ce2902023c722af8564068e6b26e934b83fd774-refs/branch-heads/5112@{#1213}
OS	macOS Version 10.13.6 (Build 17G66)
```
