### ISSUE TITLE
Dismiss wallet interact notification when its not related to tab in focus

### ISSUE THREAD

**Issue by qamarngr** [brave/brave-browser#23745]
This is case when the site triggers window.open

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.42.80 x64 build
- Verified steps from [brave/brave-core#14009](https://github.com/brave/brave-core/pull/14009)
- Verified wallet interaction notification is dismissed when tab focus changes

https://user-images.githubusercontent.com/17010094/181431211-a2d61592-5836-4d55-9f7b-bf98d482787e.mp4
