### ISSUE TITLE
beachball/perf hit after importing many tabs from muon

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#2374]
## Description 
Found while testing https://github.com/brave/brave-browser/issues/998

If you have a bunch of tabs on muon (I used 4 windows with 100ish tabs per window), and import those to b-c, you'll see that the import completes as expected.  However, after getting the completion box, I beachballed for a bit and then my CPU went up and my laptop fans kicked on. It looks like all tabs are attempting to load at once.

This only happens after the import. Subsequent launches of Brave do not have this problem (tabs aren't loaded until you click on them).

## Steps to Reproduce

   1. Have a muon profile with several windows and many tabs.
   2. Close muon.
   3. Launch b-c (if you don't launch with --upgrade-from-muon flag then you'll have to import your data manually.
   4. Import data manually if necessary.
   5. Wait for UI notification that import was successful.

## Actual result:
See beachball and then notice CPU go up as all tabs attempt to load at once.
<img width="1376" alt="screen shot 2018-12-05 at 3 13 28 pm" src="https://user-images.githubusercontent.com/28145373/49541411-bb8f8100-f8a0-11e8-90f4-712c63ed1064.png">

![screen shot 2018-12-05 at 3 14 57 pm](https://user-images.githubusercontent.com/28145373/49541420-c2b68f00-f8a0-11e8-9b6b-f7eb4160b85d.png)

## Expected result:
No CPU increase, would be nice if maybe tabs were lazy loaded/staggered on load.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.57.16 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information
cc @rebron @garrettr @bsclifton @kjozwiak

**Comment by kjozwiak** [comment]
We should be importing all the tabs but only load them once a user focuses on a particular tab. Basically the same thing we do when restoring sessions. This will mitigate the above issues for users who might be importing a lot of tabs/windows.

Even though the above examples are extreme cases, anyone with a moderate amount of tabs will run into these performance issues while we're loading tabs.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.57.18 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

* Verified STR from description and expected results from https://github.com/brave/brave-core/pull/1038. Not all imported tabs attempted to load at once, tabs did not load until clicked on.
