### ISSUE TITLE
Tipping banner should be non-modal, i.e. make it easily dismissable on clicking outside of the banner

### ISSUE THREAD

**Issue by jenn-rhim** [brave/brave-browser#23740]
Currently the banner can be dismissed only when the user clicks the close button.  This behavior is not originally intended nor necessary.  We'd want to make this less friction as possible.

@Miyayes @zenparsing

**Comment by Miyayes** [comment]
Was filed in this issue a long time ago https://github.com/brave/brave-browser/issues/1743. Will use this new, fresher issue instead!

**Comment by Miyayes** [comment]
Rewards client team is exploring lift weight. May require use of new Chromium abstraction, which is non-trivial.

**Comment by Miyayes** [comment]
Currently a Chromium dialog. Will try to see if we can make it a Chromium bubble.
