### ISSUE TITLE
Update 'Show Brave News' Module

### ISSUE THREAD

**Issue by Sam-Sibley** [brave/brave-browser#23755]
## Description 
The 'Show Brave News module thats displayed to prompt to turn on news, has 3 issues to fix:
1. The Graphic icon should be animated like it is on iOS
2. The learn more about your data text style should match the same text style we use in our buttons.
3. There looks to be a border on the grey border on the background container for the news. Can we remove this border?

## Steps to reproduce 

   1. Install Brave
   2. In NTP, scroll down to see 'Show Brave News' panel
   

## Actual result 

![news](https://user-images.githubusercontent.com/99699532/176369955-2a822c62-c6d7-4467-aafc-f1e4c6624f51.jpg)

## Expected result
- Graphic news Icon should animate but it doesn't.
-"Learn more about your data" text style should match the text style in button above it
-Grey Border on background container should not be there

iOS animation shown here:
https://user-images.githubusercontent.com/99699532/176377957-c43dacdf-f687-4838-a14d-cb69659d305e.MP4

## Issue reproduces how often 
Everytime

## Version/Channel Information:
Android only

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet): Samsung Galaxy A53 
   - Android version: 12
   
## Brave version
1.40.106

### Website problems only
NA 

### Additional information
Lottie animation for icon is here:
https://github.com/brave/brave-ios/blob/development/Client/Frontend/Brave%20Today/Lottie%20Assets/brave-today-welcome-graphic.json

**Comment by Sam-Sibley** [comment]
@kjozwiak  I was going through my slack and saw you mentioned to create an issue for this. Not sure if one already exists for this, i searched but couldn't find one. Hope i filled it out all correctly.

**Comment by kjozwiak** [comment]
@Sam-Sibley looks good 👍 Just adding a few missing labels/projects so the issue gets noticed and triaged 👍

**Comment by tapanmodh** [comment]
This is already been fixed in original PR: https://github.com/brave/brave-core/pull/13951

**Comment by deeppandya** [comment]
@srirambv @Sam-Sibley can you verify the change in nightly version of the application ? it should be fixed with https://github.com/brave/brave-core/pull/13951.

**Comment by kjozwiak** [comment]
@deeppandya just noticed this one, I think we can close this off 👍 This should have been closed and mentioned within https://github.com/brave/brave-core/pull/13951 if it was resolved by the PR so QA can run through the above verifications when it was originally released.

- [x] The Graphic icon should be animated like it is on iOS
- [x] The learn more about your data text style should match the same text style we use in our buttons.

However, looks like the following was resolved/addressed as I'm still seeing a border around the onboarding card. Created https://github.com/brave/brave-browser/issues/27992 as a follow up.

- [ ] There looks to be a border on the grey border on the background container for the news. Can we remove this border?

Example of `Brave News` on `Samsung S10+` running `Android 12`:

![Screenshot_20230123-172113_Brave](https://user-images.githubusercontent.com/2602313/214167331-098675c4-2a94-43e4-a379-aad71d628545.jpg)

https://user-images.githubusercontent.com/2602313/214167358-93589190-bed4-4023-8411-e31828dd45d3.mp4

Example of `Brave News` on `Pixel 6` running `Android 13`:

![Screenshot_20230123-174820](https://user-images.githubusercontent.com/2602313/214171747-dd494d69-5858-49b0-addc-392da8a596b5.png)

https://user-images.githubusercontent.com/2602313/214171756-c9a935b0-30da-4d3d-ba94-6573613a06d5.mp4

**Comment by deeppandya** [comment]
Actually @kjozwiak it was added as a part of first iteration. And I was unaware of it as we had other issues addressing the same thing. I will be careful.
