### ISSUE TITLE
Stripe credit cards using Simple Practice don't process

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#23751]
## Description 

Brave cannot let me bill Stripe credit cards for clients using Simple Practice. `https://secure.simplepractice.com/users/sign_in`
Shields down does not help.
Works in Firefox and Chrome.

## Steps to Reproduce

tbd as may require user login to `https://secure.simplepractice.com/users/sign_in`

## Actual result:

Process hangs during the process upon billing clients.

## Expected result:
Billing process via Stripe/Visa cards on simplepractice goes through properly.

## Reproduces how often: 

It worked until a few months ago. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? don't know
- Can you reproduce this issue with the nightly channel? don't know

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? no

**Comment by rebron** [comment]
cc: @ryanbr

**Comment by ryanbr** [comment]
Still an issue @rebron ?

**Comment by rebron** [comment]
Thanks @ryanbr We're all set here. Fixed on the simplepractice.com end.
