### ISSUE TITLE
CR 103-Bookmarks folder icon shape is inherited from chrome

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#23757]
## Description 

The issue is reported by @bsclifton 

Bookmarks folder icon shape is inherited from chrome in CR 103
## Steps to Reproduce

   1. NA
  

## Actual result:

![image](https://user-images.githubusercontent.com/38657976/176396299-a32a50ad-bce8-4f97-b87a-43c8f14efc04.png)

## Expected result:

![image](https://user-images.githubusercontent.com/38657976/176397339-d5cba951-026a-4459-947c-52ce14d5cb56.png)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.40.109 Chromium: 103.0.5060.66 (Official Build) (64-bit)
-- | --
Revision | 20b1569438a85e631d15e83eb355e3e326e5da6f-refs/branch-heads/5060@{#1066}
OS | Windows 10 Version 21H2 (Build 19044.1766)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @emerick @mkarolin @bsclifton @rebron

**Comment by emerick** [comment]
Same as https://github.com/brave/brave-browser/issues/23667?

**Comment by simonhong** [comment]
Closed as duplicated with #23667
