### ISSUE TITLE
Garbled texts in Shields UI with Simplified Chinese language

### ISSUE THREAD

**Issue by jdjxk** [brave/brave-browser#23753]
## Description 

Garbled texts in Shields UI with Simplified Chinese language.
Displayed like that: Shields 已为$2 $2 $1 $1 

## Steps to Reproduce

   1. 
   2. 
   3. 

## Actual result:

![screenshot](https://user-images.githubusercontent.com/46536339/176326892-fbe1e4b0-95f7-4dd8-afc2-5f799f69bae8.png)

## Expected result:
Display normally.

## Brave version (brave://version info)

1.40.109 Chromium: 103.0.5060.66 (正式版本) （64 位） 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment]
cc: @nullhook @rebron

**Comment by kjozwiak** [comment]
The above will require `1.41.96` or higher for `1.41.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification is in-progress

```
Brave | 1.41.96 Chromium: 103.0.5060.114 (Official Build) (64-bit)
-- | --
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | Windows 10 Version 21H2 (Build 19044.1806)

```
