### ISSUE TITLE
Tab webview crash when switching Solana Accounts

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23761]
## Description 

Tab webview crash when switching Solana Accounts

## Steps to Reproduce

   1. Create 2 Solana Accounts
   2. Set Solana Account 1 as active account
   3. Visit `https://pwgoom.csb.app/` and initiate wallet connect
   4. Cancel request
   5. Try to connect wallet again, successfully connects
   6. Open Wallet Panel (encounter #23760) and switch to Solana Account 2, web view crashes

## Actual result:

https://user-images.githubusercontent.com/17010094/176431196-8d223b6d-6e42-4260-93ed-7b5765a5572f.mp4

Crash Report: https://share.backtrace.io/api/share/SaPRuyFYrf5CHnpZMzx1Us3

## Expected result:
No crash 

## Reproduces how often: 

Happened only once

## Brave version (brave://version info)

Brave | 1.42.42 Chromium: 103.0.5060.66 (Official Build) nightly (64-bit) 
-- | --
Revision | `20b1569438a85e631d15e83eb355e3e326e5da6f-refs/branch-heads/5060@{#1066}`
OS | Windows 11 Version 21H2 (Build 22000.739)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @darkdh

**Comment by darkdh** [comment]
can you provider crash id? I couldn't reproduce it on the same version of Nightly

**Comment by darkdh** [comment]
Just got one now and it is symbolized
https://share.backtrace.io/api/share/iS3x3IzQvnavXA2sWqvXtY0

**Comment by kjozwiak** [comment]
The above will require `1.41.89` or higher for `1.41.x` verification 👍

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.41.89 Chromium: 103.0.5060.70 (Official Build) beta (64-bit)</th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>1543faf9f70e61c6f6e9c01ff20a2e3cf2ad55dc-refs/branch-heads/5060_53@{#4}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.708)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/14018>brave/brave-core#14018</a></li>
         <li>Verified no crash when trying to switch accounts</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/177193905-64357555-38db-4651-a464-2aab0f01e4aa.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/177193996-28bac358-1483-4da1-925e-401830fa54d5.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/177194266-6ba85849-0805-4875-b93c-e65afee1be0a.mov>
      </td>
   </tr>
</table>
