### ISSUE TITLE
[Translate] Get Brave Translate functioning on Android

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#23768]
Per meeting with @rebron @moritzhaller @atuchin-m, there is some Chromium work required to get brave translate functioning on Android. 

Find why the translation fails without loading the main script.

**Comment by anthonypkeane** [comment]
Slack Link: https://bravesoftware.slack.com/archives/C02G7LEELQK/p1634748449086800

**Comment by atuchin-m** [comment]
For QA:
1. (Important) Check that there is no any translation attempt or UI by default (when the new feature is disabled).
2. Enable the new flag `Enable internal translate engine (brave-translate-go) ` and check that pages can be translated. Note the UI fixes (removing the google icon, menu and settings items) is still in progress.

**Comment by atuchin-m** [comment]
The uplift PR wasn't merged in 1.42.x, so I've removed `1.42.x - Beta` milestone. 
https://github.com/brave/brave-core/blob/1.42.x/browser/about_flags.cc#L425

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave `1.43.74, Chromium 104.0.5112.102` on a `Google Pixel XL` running `Android 9`.

Followed the steps to reproduce/testcase in https://github.com/brave/brave-browser/issues/23768#issuecomment-1180180240

### Case One: default - no translate UI, no offer to translate

### Steps:
1. installed `1.43.74`
2. skipped onboarding
3. opened `brave://flags`
4. confirmed both `Enable internal translate engine (brave-translate-go)` and `Enable Chromium Translate feature` were set to `Default` (disabled)
5. loaded `speigel.de`, `bbc.com/mundo`, `www.jargan.com`, `www.inap.co.jp`, `www.wp.pl`, and `mail.ru`


### Confirmed:
* no UI offering to translate, near the bottom toolbar
* no `Translate` menu item

### Case Two:
