### ISSUE TITLE
Only one Solana Account is shown when initiating wallet connect

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23760]
## Description 

Only one Solana Account is shown when initiating wallet connect

## Steps to Reproduce

   1. Create 2 Solana accounts
   2. Visit  `https://pwgoom.csb.app/` and initiate wallet connect
   3. Only the current active Solana account is shown and not all available accounts

## Actual result:

Only one Solana Account is shown when initiating wallet connect

## Expected result:
Should list all available accounts

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.42.42 Chromium: 103.0.5060.66 (Official Build) nightly (64-bit) 
-- | --
Revision | `20b1569438a85e631d15e83eb355e3e326e5da6f-refs/branch-heads/5060@{#1066}`
OS | Windows 11 Version 21H2 (Build 22000.739)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @darkdh @Douglashdaniel

**Comment by darkdh** [comment]
This is intended. Solana dApp API only interact with "Selected Account"
https://wallet-docs.brave.com/solana/provider-api/methods#bravesolanaconnect
