### ISSUE TITLE
Tab search button should use rounded off square background

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#23767]
## Description 

The tab search button shape and hover background should be a rounded square. Currently button shape is a circle.

## Steps to Reproduce

   1. Launch current version of browser 1.40.107
   2. Observe upper right corner where tab search button is located. Icon shape is circle and should be rounded off square.
 

## Actual result:

<img width="71" alt="Screen Shot 2022-06-29 at 8 55 41 AM" src="https://user-images.githubusercontent.com/5951041/176482871-752b9a2a-51db-4164-99a5-154d0fbbdabe.png">

## Expected result:
Match button style as the `New Tab button`

## Reproduces how often: 

Easily observable.

## Brave version (brave://version info)

1.40.109

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

Related issue: https://github.com/brave/brave-browser/issues/23667

**Comment by aguscruiz** [comment]
For this I think we could use the same button style as for the new tab button. If we need I can mock it up, but maybe it's not necessary

**Comment by fallaciousreasoning** [comment]
This is using the same corner radius as the NewTabButton:
![image](https://user-images.githubusercontent.com/7678024/176549776-cfd68fba-581a-4e69-99ff-867411369b82.png)
![image](https://user-images.githubusercontent.com/7678024/176549856-eb8f8656-941e-4b0e-93d6-226143c644e2.png)

It looks like we were making the icon a circle on purpose though - we'd overridden the `GetCornerRadius` function to always round the icon fully.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.42.61 Chromium: 103.0.5060.114 (Official Build) beta (x86_64)
-- | --
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | macOS Version 13.0 (Build 22A5295i)

### Steps:
1. installed `1.42.61`
2. launched Brave using `Dark` mode
3. hovered over tab-search button; confirmed so-called "sqircle" shape
4. switched to `Light` mode
5. hovered over tab-search button; confirmed "sqircle" shape

`Dark` mode (hover state) | `Light` mode (hover state)
-------------|---------------
<img width="167" alt="Screenshot 2022-07-11 at 7 44 43 PM" src="https://user-images.githubusercontent.com/387249/178397560-0b11d675-525b-4c2c-b9db-97b20443994f.png"> | <img width="200" alt="Screenshot 2022-07-11 at 7 45 14 PM" src="https://user-images.githubusercontent.com/387249/178397562-2b9c3dd8-390e-41cc-91c6-def2f4123819.png">
