### ISSUE TITLE
Brave News can suggest the current site to subscribe to

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#23778]
When the Brave News is opted-in and enabled, we can do the following:

For any given Tab, if we detect a corresponding Publisher to subscribe to, we can offer the user to add the subscription.

This could look like a Location Bar button with the brave news icon. When clicked it would show a list of the available feeds (which would usually only be 1).

Sources of Publisher items for a Tab:
- sources.json via `brave_news.mojom:GetPublishers()` (see note below re: site_url)
- meta tags in the html with feed destinations

Implementation:
- Probably a TabHelper which performs the necessary Publisher look ups when the WebContents' Url is committed.
- Maybe an addition to BraveNewsController for a performant lookup of an existing Publisher.
- Addition to publisher_parsing to include the `site_url` (and possibly `feed_url`) fields in sources.json
- Uses[ `RssLinkReader`](https://source.chromium.org/chromium/chromium/src/+/main:components/feed/content/renderer/rss_link_reader.h;bpv=1;bpt=1) to get the feed url from the html.
- Uses `SetPublisherPref` to subscribe (or unsubscribe)

Design:
TBD

Rough design:
```
----------------------------------------
Subscribe to this site via Brave News

--------------
[Name of feed]    ( Subscribe )
--------------
[Name of alternate feed]    ( Subscribe )
-----------------------------------------
(Don't show this again)
```

Location bar button (older design might not be the correct icon):
**_although I don't think it should be inside the brave actions area, i.e. it can just be a regular PageActionIcon_**
<img width="103" alt="image" src="https://user-images.githubusercontent.com/741836/176540044-8ccbf9a5-f287-44e8-b963-d9bb3b5a5b6e.png">

Maybe it shows expanded on first seeing it for each browser session (ignore the tooltip):
<img width="183" alt="image" src="https://user-images.githubusercontent.com/741836/176540193-28f735fa-02ea-42f8-a398-42196c34e848.png">

Outstanding questions
- [ ] Should the button (and bubble popup) show if the user is already to subscribed to at least 1 of the feeds for the current page? It would allow users to unsubscribe.

**Comment by fallaciousreasoning** [comment]
I feel like it would be a bit weird if we let people subscribe from the dialog but not unsubscribe. Like, what if a user clicks subscribe to see what happens, but there's no obvious way to undo it?

This is what my rough mockup looks like. It's not uncommon for sites to have multiple feeds on a single page.
![Screenshot from 2022-07-14 12-46-03](https://user-images.githubusercontent.com/7678024/179639205-c102636d-5f15-4769-9d4e-b218de4c22cc.png)

That said, I don't have strong feelings about it, and I'm happy to defer to you on this :smile:

**Comment by mattmcalister** [comment]
If we're using a toggle ux then, yes, I'd agree. I thought it was just a "Add to Brave News" button or something like that in which case I would think you would want it to say "You follow [Feed Name] in Brave News. You can customize your feed selections any time in <link>Settings</link>." Maybe that doesn't work as well with multiple feeds. I don't feel strongly about it, either. It will become more obvious when we start testing, I'm sure.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.44.73 Chromium: 105.0.5195.68 (Official Build) beta (x86_64)
-- | --
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | macOS Version 13.0 (Build 22A5331f)



### Subscribe
#### via Manage Subscriptions icon
#### via Customize -> Brave News dialog

### Unsubscribe
#### via Manage Subscriptions icon
#### via Customize -> Brave News dialog
### Hide and don't show this again

### Dark + Light modes

### Tooltip

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.44.83 Chromium: 105.0.5195.102 (Official Build) beta (64-bit)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | Windows 11 Version 21H2 (Build 22000.856)
```
### Shared Steps:
1. install `1.44.73`
2. launch Brave
3. open `brave://flags/`
4. set (#brave-news-subscribe-button) `Enable Brave News Subscribe Button` to `Enabled`
5. click `Relaunch`

<details>
![image](https://user-images.githubusercontent.com/98358127/189949462-d38d10bd-e43e-43f1-be5b-9ac67cb1a0b4.png)
</details>


### <summary>Subscribe - PASSED </summary>

via Manage Subscriptions icon - PASSED
<details>

1. load `theatlantic.com`
2. click on the `Manage Subscriptions` icon in the browser URL bar
3Verification `PASSED` using
```
Brave | 1.44.83 Chromium: 105.0.5195.102 (Official Build) beta (64-bit)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | Windows 11 Version 21H2 (Build 22000.856)
```
### Shared Steps:
1. install `1.44.73`
2. launch Brave
3. open `brave://flags/`
4. set (#brave-news-subscribe-button) `Enable Brave News Subscribe Button` to `Enabled`
5. click `Relaunch`

<details>
![image](https://user-images.githubusercontent.com/98358127/189949462-d38d10bd-e43e-43f1-be5b-9ac67cb1a0b4.png)
</details>


### <summary>Subscribe - PASSED </summary>

via Manage Subscriptions icon - PASSED
<details>

1. load `theatlantic.com`
2. click on the `Manage Subscriptions` icon in the browser URL bar
3. click on `Subscribe`
4. confirm the button changes to `Unsubscribe`
5. open a new-tab page
6. click on `Customize` on the bottom right
7. click on `Brave News`
8. confirmed `The Atlantic` title and URL (as titletip) `https://www.atlantic.com/feed/all` 

`step 2` |step 3| `Loading...` | `step 4` | `step 6` | `step 7` | `step 8`
-------|-------|--------|-------|------------|---------|------
<image width="900" alt="step 2" src="https://user-images.githubusercontent.com/98358127/189952153-95b63fc3-b043-46b0-9595-cc445393d615.png">|<image width="900" alt="loading" src="https://user-images.githubusercontent.com/98358127/189958083-66d41189-64de-4acc-9ac0-2fea84369ca2.png">|<image width="400" alt="step 2" src="https://user-images.githubusercontent.com/98358127/189959436-2e099ec3-fa93-427c-b85d-76c6c1208b9f.png">|<image width="900" alt="step 2" src="https://user-images.githubusercontent.com/98358127/189952537-d7009a82-21c4-4ce7-bac1-98446b57b5ae.png">|<image width="900" alt="step 2" src="https://user-images.githubusercontent.com/98358127/189957123-8fc21143-ed46-43f3-ab40-fe95f8c78263.png">|<image width="900" alt="step 2" src="https://user-images.githubusercontent.com/98358127/189957226-99aa811d-330c-414f-804a-ee127b15c621.png">|<image width="900" alt="step 2" src="https://user-images.githubusercontent.com/98358127/189957391-d000d4a0-95ce-4398-9d04-c9c503257408.png">

</details>

#### via Customize -> Brave News dialog - PASSED
<details>

1. open a new-tab page
2. click on `Customize`
3. click on `Brave News`
4. enter `https://www.theguardian.com/us` into `Feed URL` and click `Add source`
5. confirmed publisher added to the customized dashboard in the Brave news section
6. load `theguardian.com`
7. click on the `Manage Subscriptions` icon
8. confirm it says `The Guardian`, and the button reads `Unsubscribe`
9. open a new-tab page and click on `Show Brave News`
10. scroll down and confirm a post from `The Guardian`  (`Hong Kong residents queue..`) in `Brave News` feed

`step 2-3`|`step 4` | `step 5`|`step 6 + 7` | `step 8` | `step 9`|`step 10`
-----|-------|--------|-----|-----|-------|-------
<image width="900" alt="step 2" src="https://user-images.githubusercontent.com/98358127/189964669-38b1311b-e7d5-410a-b648-16ac41410fa9.png">|<image width="900" alt="step 2" src="https://user-images.githubusercontent.com/98358127/189964984-0c47b28e-ee19-4e18-bfd4-d962e2a47c2b.png">|<image width="900" alt="step 2" src="https://user-images.githubusercontent.com/98358127/189965036-358ce76e-a0f2-4b9d-8714-95ac3ef247fc.png">|<image width="900" alt="step 2" src="https://user-images.githubusercontent.com/98358127/189965179-9d087e36-11d0-42fc-9b00-2449a97b76c9.png">|<image width="900" alt="step 2" src="https://user-images.githubusercontent.com/98358127/189965254-8fc3e926-16ec-4b11-9764-c1bb1eae13b3.png">|<image width="900" alt="step 2" src="https://user-images.githubusercontent.com/98358127/189965378-7ccad37f-d830-4494-825b-77a164292e60.png">|<image width="900" alt="step 2" src="https://user-images.githubusercontent.com/98358127/189965505-9cf76f82-d508-4735-8f57-c51d1093e805.png">
</details>

</details>

### Unsubscribe - PASSED

#### via Manage Subscriptions icon - PASSED
<details>

1. continuing from Manage Subscriptions icon - Step 8
2. load/return to `theatlantic.com` tab
3. click on the `Manage Subscriptions` icon
4. click on `Unsubscribe`
5. confirm the button changes to `Subscribe`
6. on a new-tab page, click on `Customize`
7. click `Brave News`
8. confirm the `The Atlantic` entry is removed

`step 1`|`step 4` | `step 5` | `step 8`
-----|--------|----------|--------
<image width="900" alt="step 1" src="https://user-images.githubusercontent.com/98358127/190002074-83835b88-2a53-4db8-bd37-e87ed377098e.png">|<image width="900" alt="step 4" src="https://user-images.githubusercontent.com/98358127/190001862-36bf4fa6-f95c-4493-a9e6-678b227ee9b0.png">|<image width="900" alt="step 5" src="https://user-images.githubusercontent.com/98358127/190001336-a0c8e0b7-b7a7-49d4-bb24-715582cafa9e.png">|<image width="900" alt="step 6" src="https://user-images.githubusercontent.com/98358127/190001599-f50fa959-4bf7-46ae-a04a-dde1b6fd98a5.png">

</details>

#### via Customize -> Brave News dialog - PASSED
<details>

1. continuing from `Subscribe tests - Customize -> Brave News dialog` Step 5
2. load a new-tab page
3. click on `Customize`
4. click on `Brave News`
5. click on the `...` ellipsis to the right of `The Guardian`
6. click `Remove`
7. click the `X` to dismiss the `Customize Dashboard` panel
8. load `theguardian.com`
9. click on the `Manage Subscriptions` icon
10. confirm you see `The Guardian` and then a `Subscribe` button

 `step 5`|`step 6` | `step 10`
-------|------|---------
<image width="900" alt="step 1" src="https://user-images.githubusercontent.com/98358127/190003093-6b8552e1-1759-4815-a39c-a086276726f1.png">|<image width="900" alt="step 1" src="https://user-images.githubusercontent.com/98358127/190003153-8a1585c7-eb6f-4c81-9c51-0affbf0a7352.png">|<image width="900" alt="step 1" src="https://user-images.githubusercontent.com/98358127/190003312-c16a38df-7601-48be-beb5-47c585e71139.png">

</details>

### Hide and don't show this again - PASSED
<details>

(run either of the `Subscribe` tests, first)
1. load https://theguardian.com
2. click on the `Manage Subscriptions` icon
3. click `Hide and don't show this again`
4. confirm the icon disappears
5. in a new-tab page, confirm `Show Brave News button in the toolbar` is `Disabled` / `Off`
6. restart Brave
7. re-loaded [`planet.mozilla.org`](https://theguardian.com)
8. confirm there's no `Manage Subscriptions` icon in the URL bar

`step 3` | `step 4` | `step 5` | `step 8`
---------|----------|---------|---------
<image width="900" alt="step 1" src="https://user-images.githubusercontent.com/98358127/190011874-40190084-00bb-49d6-ab48-4ba81bd4c90d.png">|<image width="900" alt="step 1" src="https://user-images.githubusercontent.com/98358127/190011936-1a9a0e58-7e57-4710-8691-a712f5daf03c.png">|<image width="900" alt="step 1" src="https://user-images.githubusercontent.com/98358127/190012118-dd57dc9c-8102-488c-97e2-6e98e4a6b7ed.png">|<image width="900" alt="step 1" src="https://user-images.githubusercontent.com/98358127/190012263-578481fd-3f2d-49d1-b20f-11441799c957.png">
</details>

### <summary>UI - PASSED </summary>
<details>

#### Show Brave News button in the toolbar - PASSED
<details>

1. new profile
1. load https://theguardian.com
2. confirm the `Manage Subscriptions` icon appears, but don't click it
3. open a new-tab page
4. click on `Customize`
5. click on `Brave News`
6. confirm that `Show Brave News button in the toolbar` is `Enabled` / `On`
7. toggle it to `Disabled` / `Off`
8. return to the [`www.theguardian.com/`](https://theguardian.com) tab
9. confirm the `Manage Subscriptions` icon disappears

`step 2` | `step 6` | `step 7` | `step 9`
---------|----------|---------|-----------
<image width="900" alt="step 1" src="https://user-images.githubusercontent.com/98358127/190009929-88edb0ec-7d73-4934-bac6-13f81bc025ef.png">|<image width="900" alt="step 1" src="https://user-images.githubusercontent.com/98358127/190009646-bc63ece0-e50e-4c32-8559-d69ffbf0c014.png">|<image width="900" alt="step 1" src="https://user-images.githubusercontent.com/98358127/190010215-3a1fa10b-ffb1-4c26-8290-f5dfbfd007b5.png">|<image width="900" alt="step 1" src="https://user-images.githubusercontent.com/98358127/190010298-2ade41b7-3383-4f51-b276-2f153effae2a.png">

</details>

Manage Subscription tooltip 
<details>

dark|light
---|----
<image width="900" alt="step 1" src="https://user-images.githubusercontent.com/98358127/190010818-76fbd177-0631-437b-925b-0cef809d6c58.png">|<image width="900" alt="step 1" src="https://user-images.githubusercontent.com/98358127/190010934-a8943d9c-de31-450c-b49a-b8a2f815206b.png">
</details>

Unsubscribe
<details>

dark|light
-----|-----
<image width="900" alt="step 1" src="https://user-images.githubusercontent.com/98358127/190020663-dcd0dd4a-be83-434f-b862-28a01af89986.png">|<image width="900" alt="step 1" src="https://user-images.githubusercontent.com/98358127/190020612-83333a88-c77e-4c5d-b0af-3f708537d02b.png">

</details>
Subscribed
<details>

dark|light 
-----|-----
<image width="900" alt="step 1" src="https://user-images.githubusercontent.com/98358127/190020432-01006086-9cc5-4a84-8075-1ec4008a1820.png">|<image width="900" alt="step 1" src="https://user-images.githubusercontent.com/98358127/190020494-c89be275-5d02-4fe7-879b-28b885715d1c.png">

</details>

</details>

### New Browser Window - PASSED
New profile
go to hamburger menu>>click New Window
visit https://theatlantic.com
confirmed Manage subscription icon displayed as expected
confirmed above subscribe and unsubscribe tests passed as expected.
confirmed rest of the functionality working as expected

Ex1|Ex2|Ex3|Ex4|Ex5
----|---|----|----|---
<image width="900" alt="step 1" src="https://user-images.githubusercontent.com/98358127/190022138-aac3a1c8-1709-4006-a899-ae5c848d10db.png">|<image width="900" alt="step 1" src="https://user-images.githubusercontent.com/98358127/190022174-5886f11c-f01f-43c4-aa5a-4abb24ac6b2a.png">|<image width="900" alt="step 1" src="(https://user-images.githubusercontent.com/98358127/190022193-d0a9ca2c-cd0c-47b1-a57b-c7b3fd55fa25.png">|<image width="900" alt="step 1" src="https://user-images.githubusercontent.com/98358127/190022242-acbf9f58-aedf-4771-bc31-7ec820fd378a.png">|<image width="900" alt="step 1" src="https://user-images.githubusercontent.com/98358127/190022255-c262fe6c-7d0b-45f3-8961-70d89fae5d8b.png">. click on `Subscribe`
4. confirm the button changes to `Unsubscribe`
5. open a new-tab page
6. click on `Customize` on the bottom right
7. click on `Brave News`
8. confirmed `The Atlantic` title and URL (as titletip) `https://www.atlantic.com/feed/all` 

`step 2` |step 3| `Loading...` | `step 4` | `step 6` | `step 7` | `step 8`
-------|-------|--------|-------|------------|---------|------
<image width="900" alt="step 2" src="https://user-images.githubusercontent.com/98358127/189952153-95b63fc3-b043-46b0-9595-cc445393d615.png">|<image width="900" alt="loading" src="https://user-images.githubusercontent.com/98358127/189958083-66d41189-64de-4acc-9ac0-2fea84369ca2.png">|<image width="400" alt="step 2" src="https://user-images.githubusercontent.com/98358127/189959436-2e099ec3-fa93-427c-b85d-76c6c1208b9f.png">|<image width="900" alt="step 2" src="https://user-images.githubusercontent.com/98358127/189952537-d7009a82-21c4-4ce7-bac1-98446b57b5ae.png">|<image width="900" alt="step 2" src="https://user-images.githubusercontent.com/98358127/189957123-8fc21143-ed46-43f3-ab40-fe95f8c78263.png">|<image width="900" alt="step 2" src="https://user-images.githubusercontent.com/98358127/189957226-99aa811d-330c-414f-804a-ee127b15c621.png">|<image width="900" alt="step 2" src="https://user-images.githubusercontent.com/98358127/189957391-d000d4a0-95ce-4398-9d04-c9c503257408.png">

</details>

#### via Customize -> Brave News dialog - PASSED
<details>

1. open a new-tab page
2. click on `Customize`
3. click on `Brave News`
4. enter `https://www.theguardian.com/us` into `Feed URL` and click `Add source`
5. confirmed publisher added to the customized dashboard in the Brave news section
6. load `theguardian.com`
7. click on the `Manage Subscriptions` icon
8. confirm it says `The Guardian`, and the button reads `Unsubscribe`
9. open a new-tab page and click on `Show Brave News`
10. scroll down and confirm a post from `The Guardian`  (`Hong Kong residents queue..`) in `Brave News` feed

`step 2-3`|`step 4` | `step 5`|`step 6 + 7` | `step 8` | `step 9`|`step 10`
-----|-------|--------|-----|-----|-------|-------
<image width="900" alt="step 2" src="https://user-images.githubusercontent.com/98358127/189964669-38b1311b-e7d5-410a-b648-16ac41410fa9.png">|<image width="900" alt="step 2" src="https://user-images.githubusercontent.com/98358127/189964984-0c47b28e-ee19-4e18-bfd4-d962e2a47c2b.png">|<image width="900" alt="step 2" src="https://user-images.githubusercontent.com/98358127/189965036-358ce76e-a0f2-4b9d-8714-95ac3ef247fc.png">|<image width="900" alt="step 2" src="https://user-images.githubusercontent.com/98358127/189965179-9d087e36-11d0-42fc-9b00-2449a97b76c9.png">|<image width="900" alt="step 2" src="https://user-images.githubusercontent.com/98358127/189965254-8fc3e926-16ec-4b11-9764-c1bb1eae13b3.png">|<image width="900" alt="step 2" src="https://user-images.githubusercontent.com/98358127/189965378-7ccad37f-d830-4494-825b-77a164292e60.png">|<image width="900" alt="step 2" src="https://user-images.githubusercontent.com/98358127/189965505-9cf76f82-d508-4735-8f57-c51d1093e805.png">
</details>

</details>

### Unsubscribe - PASSED

#### via Manage Subscriptions icon - PASSED
<details>

1. continuing from Manage Subscriptions icon - Step 8
2. load/return to `theatlantic.com` tab
3. click on the `Manage Subscriptions` icon
4. click on `Unsubscribe`
5. confirm the button changes to `Subscribe`
6. on a new-tab page, click on `Customize`
7. click `Brave News`
8. confirm the `The Atlantic` entry is removed

`step 1`|`step 4` | `step 5` | `step 8`
-----|--------|----------|--------
<image width="900" alt="step 1" src="https://user-images.githubusercontent.com/98358127/190002074-83835b88-2a53-4db8-bd37-e87ed377098e.png">|<image width="900" alt="step 4" src="https://user-images.githubusercontent.com/98358127/190001862-36bf4fa6-f95c-4493-a9e6-678b227ee9b0.png">|<image width="900" alt="step 5" src="https://user-images.githubusercontent.com/98358127/190001336-a0c8e0b7-b7a7-49d4-bb24-715582cafa9e.png">|<image width="900" alt="step 6" src="https://user-images.githubusercontent.com/98358127/190001599-f50fa959-4bf7-46ae-a04a-dde1b6fd98a5.png">

</details>

#### via Customize -> Brave News dialog - PASSED
<details>

1. continuing from `Subscribe tests - Customize -> Brave News dialog` Step 5
2. load a new-tab page
3. click on `Customize`
4. click on `Brave News`
5. click on the `...` ellipsis to the right of `The Guardian`
6. click `Remove`
7. click the `X` to dismiss the `Customize Dashboard` panel
8. load `theguardian.com`
9. click on the `Manage Subscriptions` icon
10. confirm you see `The Guardian` and then a `Subscribe` button

 `step 5`|`step 6` | `step 10`
-------|------|---------
<image width="900" alt="step 1" src="https://user-images.githubusercontent.com/98358127/190003093-6b8552e1-1759-4815-a39c-a086276726f1.png">|<image width="900" alt="step 1" src="https://user-images.githubusercontent.com/98358127/190003153-8a1585c7-eb6f-4c81-9c51-0affbf0a7352.png">|<image width="900" alt="step 1" src="https://user-images.githubusercontent.com/98358127/190003312-c16a38df-7601-48be-beb5-47c585e71139.png">

</details>

### Hide and don't show this again - PASSED
<details>

(run either of the `Subscribe` tests, first)
1. load https://theguardian.com
2. click on the `Manage Subscriptions` icon
3. click `Hide and don't show this again`
4. confirm the icon disappears
5. in a new-tab page, confirm `Show Brave News button in the toolbar` is `Disabled` / `Off`
6. restart Brave
7. re-loaded [`planet.mozilla.org`](https://theguardian.com)
8. confirm there's no `Manage Subscriptions` icon in the URL bar

`step 3` | `step 4` | `step 5` | `step 8`
---------|----------|---------|---------
<image width="900" alt="step 1" src="https://user-images.githubusercontent.com/98358127/190011874-40190084-00bb-49d6-ab48-4ba81bd4c90d.png">|<image width="900" alt="step 1" src="https://user-images.githubusercontent.com/98358127/190011936-1a9a0e58-7e57-4710-8691-a712f5daf03c.png">|<image width="900" alt="step 1" src="https://user-images.githubusercontent.com/98358127/190012118-dd57dc9c-8102-488c-97e2-6e98e4a6b7ed.png">|<image width="900" alt="step 1" src="https://user-images.githubusercontent.com/98358127/190012263-578481fd-3f2d-49d1-b20f-11441799c957.png">
</details>

### <summary>UI - PASSED </summary>
<details>

#### Show Brave News button in the toolbar - PASSED
<details>

1. new profile
1. load https://theguardian.com
2. confirm the `Manage Subscriptions` icon appears, but don't click it
3. open a new-tab page
4. click on `Customize`
5. click on `Brave News`
6. confirm that `Show Brave News button in the toolbar` is `Enabled` / `On`
7. toggle it to `Disabled` / `Off`
8. return to the [`www.theguardian.com/`](https://theguardian.com) tab
9. confirm the `Manage Subscriptions` icon disappears

`step 2` | `step 6` | `step 7` | `step 9`
---------|----------|---------|-----------
<image width="900" alt="step 1" src="https://user-images.githubusercontent.com/98358127/190009929-88edb0ec-7d73-4934-bac6-13f81bc025ef.png">|<image width="900" alt="step 1" src="https://user-images.githubusercontent.com/98358127/190009646-bc63ece0-e50e-4c32-8559-d69ffbf0c014.png">|<image width="900" alt="step 1" src="https://user-images.githubusercontent.com/98358127/190010215-3a1fa10b-ffb1-4c26-8290-f5dfbfd007b5.png">|<image width="900" alt="step 1" src="https://user-images.githubusercontent.com/98358127/190010298-2ade41b7-3383-4f51-b276-2f153effae2a.png">

</details>

Manage Subscription tooltip 
<details>

dark|light
---|----
<image width="900" alt="step 1" src="https://user-images.githubusercontent.com/98358127/190010818-76fbd177-0631-437b-925b-0cef809d6c58.png">|<image width="900" alt="step 1" src="https://user-images.githubusercontent.com/98358127/190010934-a8943d9c-de31-450c-b49a-b8a2f815206b.png">
</details>

Unsubscribe
<details>

dark|light
-----|-----
<image width="900" alt="step 1" src="https://user-images.githubusercontent.com/98358127/190020663-dcd0dd4a-be83-434f-b862-28a01af89986.png">|<image width="900" alt="step 1" src="https://user-images.githubusercontent.com/98358127/190020612-83333a88-c77e-4c5d-b0af-3f708537d02b.png">

</details>
Subscribed
<details>

dark|light 
-----|-----
<image width="900" alt="step 1" src="https://user-images.githubusercontent.com/98358127/190020432-01006086-9cc5-4a84-8075-1ec4008a1820.png">|<image width="900" alt="step 1" src="https://user-images.githubusercontent.com/98358127/190020494-c89be275-5d02-4fe7-879b-28b885715d1c.png">

</details>

</details>

### New Browser Window - PASSED
New profile
go to hamburger menu>>click New Window
visit https://theatlantic.com
confirmed Manage subscription icon displayed as expected
confirmed above subscribe and unsubscribe tests passed as expected.
confirmed rest of the functionality working as expected

Ex1|Ex2|Ex3|Ex4|Ex5
----|---|----|----|---
<image width="900" alt="step 1" src="https://user-images.githubusercontent.com/98358127/190022138-aac3a1c8-1709-4006-a899-ae5c848d10db.png">|<image width="900" alt="step 1" src="https://user-images.githubusercontent.com/98358127/190022174-5886f11c-f01f-43c4-aa5a-4abb24ac6b2a.png">|<image width="900" alt="step 1" src="(https://user-images.githubusercontent.com/98358127/190022193-d0a9ca2c-cd0c-47b1-a57b-c7b3fd55fa25.png">|<image width="900" alt="step 1" src="https://user-images.githubusercontent.com/98358127/190022242-acbf9f58-aedf-4771-bc31-7ec820fd378a.png">|<image width="900" alt="step 1" src="https://user-images.githubusercontent.com/98358127/190022255-c262fe6c-7d0b-45f3-8961-70d89fae5d8b.png">


Bugs Filed: 
* https://github.com/brave/brave-browser/issues/25385
* https://github.com/brave/brave-browser/issues/25386

**Comment by MadhaviSeelam** [comment]
Brave | 1.44.92 Chromium: 105.0.5195.136 (Official Build) beta (64-bit)
-- | --
Revision | 872774b783d0e674186a3adcd2f92e7aa22a219c-refs/branch-heads/5195_124@{#4}
OS | Linux

### Shared Steps:
1. install `1.44.92`
2. launch Brave
3. open `brave://flags/`
4. set `(#brave-news-subscribe-button)` `Enable Brave News Subscribe Button` to `Enabled`
5. click `Relaunch`

<details>
![image](https://user-images.githubusercontent.com/98358127/191113199-810e68bd-14a0-4a62-8dfe-09c2280349a8.png)

</details

### <summary>Subscribe - PASSED </summary>

via Manage Subscriptions icon - PASSED
<details>

1. load `theatlantic.com`
2. click on the `Manage Subscriptions` icon in the browser URL bar
3. click on `Subscribe`
4. confirm the button changes to `Unsubscribe`
5. open a new-tab page
6. click on `Customize` on the bottom right
7. click on `Brave News`
8. confirmed `The Atlantic` title and URL (as titletip) `https://www.atlantic.com/feed/all` 

`step 2` |step 3| `Loading...` | `step 4` | `step 6` | `step 7` | `step 8`
-------|-------|--------|-------|------------|---------|------
<image width="1060" alt="step2" src="https://user-images.githubusercontent.com/98358127/191115661-e5c5010e-68d8-4f7f-91b6-fe3c3518788c.png">|<image width="1060" alt="step2" src="https://user-images.githubusercontent.com/98358127/191113728-c6e1c20f-6bcb-497d-97eb-02f07eca8245.png">|<image width=7860" alt="step3" src="https://user-images.githubusercontent.com/98358127/191114128-ca7f49b8-a404-4214-bd56-5eec886c31a5.png">|<image width="960" alt="Loading.." src="https://user-images.githubusercontent.com/98358127/191114435-a093e977-e8af-4aa4-ad94-a5ae3d4a96ea.png">|<image width="960" alt="step4" src="https://user-images.githubusercontent.com/98358127/191114831-52fd4634-5365-415f-bd7d-6c2210539983.png">|<image width="960" alt="step6" src="https://user-images.githubusercontent.com/98358127/191114906-4ec31081-221d-4dd4-bf18-2d2c2b8333c4.png">|<image width="960" alt="step8" src="https://user-images.githubusercontent.com/98358127/191114947-b29bc33b-d0af-48cc-a271-990c9ddaaf1d.pn


</details>

#### via Customize -> Brave News dialog - PASSED
<details>

1. open a new-tab page
2. click on `Customize`
3. click on `Brave News`
4. enter `https://www.theguardian.com/us` into `Feed URL` and click `Add source`
5. confirmed publisher added to the customized dashboard in the Brave news section
6. load `theguardian.com`
7. click on the `Manage Subscriptions` icon
8. confirm it says `The Guardian`, and the button reads `Unsubscribe`
9. open a new-tab page and click on `Show Brave News`
10. scroll down and confirm a post from `The Guardian`  (`Hong Kong residents queue..`) in `Brave News` feed

`step 2-3`|`step 4` | `step 5`|`step 6 + 7` | `step 8` | `step 9`|`step 10`
-----|-------|--------|-----|-----|-------|-------

</details>

</details>

### <summary> Unsubscribe - PASSED </summary>

#### via Manage Subscriptions icon - PASSED
<details>

1. continuing from Manage Subscriptions icon - Step 8
2. load/return to `theatlantic.com` tab
3. click on the `Manage Subscriptions` icon
4. click on `Unsubscribe`
5. confirm the button changes to `Subscribe`
6. on a new-tab page, click on `Customize`
7. click `Brave News`
8. confirm the `The Atlantic` entry is removed

`step 1`|`step 4` | `step 5` | `step 8`
-----|--------|----------|--------



</details>

#### via Customize -> Brave News dialog - PASSED
<details>

1. continuing from `Subscribe tests - Customize -> Brave News dialog` Step 5
2. load a new-tab page
3. click on `Customize`
4. click on `Brave News`
5. click on the `...` ellipsis to the right of `The Guardian`
6. click `Remove`
7. click the `X` to dismiss the `Customize Dashboard` panel
8. load `theguardian.com`
9. click on the `Manage Subscriptions` icon
10. confirm you see `The Guardian` and then a `Subscribe` button

 `step 5`|`step 6` | `step 10`
-------|------|---------




</details>

### <summary>Hide and don't show this again - PASSED </summary>
<details>

(run either of the `Subscribe` tests, first)
1. load https://theguardian.com
2. click on the `Manage Subscriptions` icon
3. click `Hide and don't show this again`
4. confirm the icon disappears
5. in a new-tab page, confirm `Show Brave News button in the toolbar` is `Disabled` / `Off`
6. restart Brave
7. re-loaded [`planet.mozilla.org`](https://theguardian.com)
8. confirm there's no `Manage Subscriptions` icon in the URL bar

`step 3` | `step 4` | `step 5` | `step 8`
---------|----------|---------|---------




</details>

### <summary>UI - PASSED </summary>
<details>

#### Show Brave News button in the toolbar - PASSED
<details>

1. new profile
1. load https://theguardian.com
2. confirm the `Manage Subscriptions` icon appears, but don't click it
3. open a new-tab page
4. click on `Customize`
5. click on `Brave News`
6. confirm that `Show Brave News button in the toolbar` is `Enabled` / `On`
7. toggle it to `Disabled` / `Off`
8. return to the [`www.theguardian.com/`](https://theguardian.com) tab
9. confirm the `Manage Subscriptions` icon disappears

`step 2` | `step 6` | `step 7` | `step 9`
---------|----------|---------|-----------




</details>

Manage Subscription tooltip 
<details>

dark|light
---|----



</details>

Unsubscribe
<details>

dark|light
-----|-----



</details>
Subscribed
<details>

dark|light 
-----|-----



</details>

</details>

### <summary> New Browser Window - Subscribe/Unsubscribe functionality - PASSED </summary>
<details>

1. New profile
2. visit https://theguardian.com
3. open `brave://flags/`
4. set `(#brave-news-subscribe-button)` `Enable Brave News Subscribe Button` to `Enabled`
5. click `Relaunch`
6. go to hamburger menu>>click New Window
7. visit https://theatlantic.com
8. confirmed Manage subscription icon displayed as expected
9. confirmed above subscribe and unsubscribe tests passed as expected.

Ex1|Ex2|Ex3|Ex4|Ex5
----|---|----|----|---



</details>

### <summary> Upgrade -Subscribe/Unsubscribe functionality- PASSED </summary>
<details>

1. Installed 1.43.89
2. launch Brave
3. visit https://theguardian.com
4. close the browser
6. rename profile folder Brave Browser - Beta
7. launch with 1.44.83
8. open `brave://flags/`
9. set `(#brave-news-subscribe-button)` `Enable Brave News Subscribe Button` to `Enabled`
10. click `Relaunch`
11. return https://theguardian.com tab
12. confirmed Manage subscription icon displayed as expected
13. confirmed above subscribe and unsubscribe tests passed as expected.

Step 1-2|step 6|step7-9|step10-11|step 12
-----|-----|-----|----|----





</details>


Bugs Filed: 
* https://github.com/brave/brave-browser/issues/25385
* https://github.com/brave/brave-browser/issues/25386
* https://github.com/brave/brave-browser/issues/25387
* https://github.com/brave/brave-browser/issues/25409
