### ISSUE TITLE
DApps: [Android] Browser crashes when adding Harmony network in Wallet and language set to Hindi

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#23775]
## Description 
Attempting to add Harmony network (from https://chainlist.org/) in Brave Wallet results in browser crashing.

## Steps to reproduce 

1. Go to Chainlist.
2. Tap on “Connect Wallet”.
3. Tap on the prompt “This page wants to interact with Brave Wallet”. Notice in the video, that if I didn’t tap on the prompt right away, it doesn’t come back on tapping “Connect Wallet” again. And can be brought back only through Brave Wallet icon in the URL bar.
4. Login to Brave Wallet
5. Search Harmony network and “Add to Brave”

## Actual result 
Browser crashes

## Expected result
Harmony added to Brave Wallet

## Issue reproduces how often 
Easily 

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? N/A
- Can you reproduce this issue with the current Play Store Nightly version? No

## Device details
   - Install type (ARM, x86): x86
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: Android 11
   
## Brave version
1.40.106

### Additional information

Initial user report:
https://community.brave.com/t/android-brave-crashes-when-adding-a-network-in-brave-wallet/408504?u=mattches
Video of behavior:
https://drive.google.com/file/d/1F5blGBoG_IagUl-Kcxgzys-YELT1R3ue/view?usp=sharing

**Comment by kjozwiak** [comment]
Changing milestones as this is currently in `1.43.x` and hasn't' been uplifted yet. Once uplifted via https://github.com/brave/brave-core/pull/14062 and https://github.com/brave/brave-core/pull/14036, @brave/uplift-approvers will change the milestone as per process.

**Comment by kjozwiak** [comment]
The above will require `1.41.95` or higher for `1.41.x` verification 👍
