### ISSUE TITLE
[Android] Front end work for Brave Translate on Android

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#23770]
**Spec**
https://docs.google.com/document/d/1LBmoyUveZaMcnycpRqg91lhzZFjDx_19zM3x6ulNpHg/edit?usp=sharing

**Comment by Sam-Sibley** [comment]
@deeppandya @timchilds Attached are the translate icons, both dark and light, let me know if you need anything else<img width="24" alt="translate_light@2x" src="https://user-images.githubusercontent.com/99699532/178450055-14df00b6-0f37-44c7-84fb-76231d145ebc.png">
![translate_light](https://user-images.githubusercontent.com/99699532/178450062-6ebd8de6-7c4c-441a-9e98-0a41f10e4e49.svg)
<img width="24" alt="translate_dark@2x" src="https://user-images.githubusercontent.com/99699532/178450063-4ba64208-574d-4cee-8608-7a497a6b632d.png">
![translate_dark](https://user-images.githubusercontent.com/99699532/178450066-dc19480f-06f9-406e-8178-67febdb89fd4.svg)

**Comment by deeppandya** [comment]
@Sam-Sibley can you provide .svg file ? using vector drawables are preferable over pngs

**Comment by Sam-Sibley** [comment]
@deeppandya These are the png icons for various Android sizes as discussed
[translate icons.zip](https://github.com/brave/brave-browser/files/9130190/translate.icons.zip)
:

**Comment by deeppandya** [comment]
@timchilds i am not if we should include this issue for release note. can you check and update the issue ?

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave `1.43.74, Chromium 104.0.5112.102` on a `Google Pixel XL` running `Android 9`.

**NOTE: Over in https://github.com/brave/brave-browser/issues/23768, I covered enabling the feature, the top-level UI, and core `Translate` features, but left the remainder of the UI items for this issue.**

### Shared Steps:

1. install `1.43.74`
2. launch Brave
3. set both `Enable internal translate engine (brave-translate-go)` and `Enable Chromium Translate feature` to `Enabled` and tapped on `Relaunch`, to restart Brave


#### More languages

#### Always translate pages in (supported language)"

#### Never translate pages in (supported language)"

#### Never translate this site

#### Page is not in "(supported language)" ?
