### ISSUE TITLE
Select purchase method for Testnets doesn't list anything. Consider hiding Buy Tab for testnets

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23773]
## Description 

Select purchase method for Testnets doesn't list anything. Consider hiding Buy Tab for testnets until we have something 

## Steps to Reproduce

   1. Enable testnets
   2. Select any of the Eth Testnet
   3. Select Buy tab and click on `Select purchase method`. Doesn't show any option

## Actual result:

https://user-images.githubusercontent.com/17010094/176494166-fcd2f206-6962-44d1-b41f-36c2f21f4353.mp4

## Expected result:
Disable Buy options for testnets or show the link to support page where testnet tokens airdrop can be claimed

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.40.109 Chromium: 103.0.5060.66 (Official Build) (64-bit) 
-- | --
Revision | `20b1569438a85e631d15e83eb355e3e326e5da6f-refs/branch-heads/5060@{#1066}`
OS | Windows 11 Version 21H2 (Build 22000.739)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @jamesmudgett @Douglashdaniel  Related to #21823

**Comment by Douglashdaniel** [comment]
I think this is related to https://github.com/brave/brave-core/pull/13708
Looks like test networks works were not updated in the new flow.
cc: @muliswilliam

**Comment by muliswilliam** [comment]
@Douglashdaniel @srirambv I will fix this.

**Comment by muliswilliam** [comment]
@jamesmudgett  and I came up with this UI to fix the issue:


![Image](https://user-images.githubusercontent.com/48117473/177526877-c1c41cda-da4c-4d66-bea5-8b7cd792faad.png)
