### ISSUE TITLE
Update wallet learn more link

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#23788]
Learn more link in add new chain prompt should be updated to https://support.brave.com/hc/en-us/articles/4415497656461-Brave-Wallet-FAQ
![Screen Shot 2022-06-30 at 8 13 00 AM](https://user-images.githubusercontent.com/318119/176686839-535d8716-246b-4f0c-85aa-c5daee9a5ba2.png)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.42.80 Chromium: 104.0.5112.57 (Official Build) (64-bit) 
-- | --
Revision | `212fd173a0da1e0a024f328295bb56a2529190bb-refs/branch-heads/5112@{#1042}`
OS | Linux

- Verified steps from [brave/brave-core#14023](https://github.com/brave/brave-core/pull/14023)
- Verified `Learn more` links now points to `https://support.brave.com/hc/en-us/articles/4415497656461-Brave-Wallet-FAQ`

https://user-images.githubusercontent.com/17010094/181492250-4aa05033-4b61-4da0-9f23-b4fe6eee56a1.mp4


------------------------
Verification passed on

Brave | 1.42.80 Chromium: 104.0.5112.57 (Official Build) (64-bit) 
-- | --
Revision | `212fd173a0da1e0a024f328295bb56a2529190bb-refs/branch-heads/5112@{#1042}`
OS | Windows 11 Version 21H2 (Build 22000.795)

- Verified steps from [brave/brave-core#14023](https://github.com/brave/brave-core/pull/14023)
- Verified `Learn more` links now points to `https://support.brave.com/hc/en-us/articles/4415497656461-Brave-Wallet-FAQ`

https://user-images.githubusercontent.com/17010094/181491369-b7514a48-d3bb-42a3-965a-e03ea787cc02.mp4


------------------------
Verification passed on

Brave | 1.42.80 Chromium: 104.0.5112.57 (Official Build) (arm64) 
-- | --
Revision | `212fd173a0da1e0a024f328295bb56a2529190bb-refs/branch-heads/5112@{#1042}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [brave/brave-core#14023](https://github.com/brave/brave-core/pull/14023)
- Verified `Learn more` links now points to `https://support.brave.com/hc/en-us/articles/4415497656461-Brave-Wallet-FAQ`

https://user-images.githubusercontent.com/17010094/181491626-f7666e99-fc6f-428b-a75a-8d933dab7184.mov
