### ISSUE TITLE
"Sadly, no tokens yet" after importing wallet with non-zero balance - Follow up to 2260

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#2379]
## Description 
Follow up issue to https://github.com/brave/brave-browser/issues/2260

After importing a funded Brave Payments wallet into Brave Rewards, the Rewards Settings page shows the correct non-zero balance for the wallet, but continues to show the "Sadly, no tokens yet" sidebar. This is confusing because it contradicts the existence of the tokens from the imported wallet, which are reflected in the displayed non-zero wallet balance.

## Test plan / Steps to Reproduce

1. Import Muon/Brave Payments wallet into b-c/Brave Rewards (detailed test plan in brave/brave-core#736).
2. Click Brave Rewards icon in address bar, then Rewards Settings in the dropdown.

## Actual result:
![screen shot 2018-11-27 at 2 24 57 pm](https://user-images.githubusercontent.com/407302/49116169-a5a31000-f251-11e8-9cf1-7d1e9d18628f.png)

## Expected result:
If the wallet balance is zero, the sidebar should not say "no tokens yet."

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

Brave | 0.57.17 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds?
Yes

**Comment by LaurenWags** [comment]
cc @rebron as original issue was slated for 0.57.x

**Comment by NejcZdovc** [comment]
should be fixed with https://github.com/brave/brave-core/pull/1075

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.58.14 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Mac OS X

* Verified STR from description and test plan in https://github.com/brave/brave-core/pull/1075
![screen shot 2018-12-17 at 5 20 07 pm](https://user-images.githubusercontent.com/28145373/50119263-3ac97100-0220-11e9-84f5-81abe1687ad6.png)
