### ISSUE TITLE
Edit/add asset button should always be visible on main asset view page

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#23795]
## Description 

at the moment, it's at the bottom of the asset view and when you have more than 8 assets or so, that's an issue. We can keep the button at the bottom but we need another one at the top of the asset list.

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by HEagle18** [comment]
thoughts on this @kleantzogu ?

**Comment by Douglashdaniel** [comment]
Is no longer an issue with in `Wallet V2` closing as `Invalid`
