### ISSUE TITLE
Asset information should be accessible from individual asset view

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#23792]
## Description 

users should be able to click into information about the asset from the individual asset view page. information will include token contract address, decimals and chain name.
Screenshot shows page we need this option on. Useful to see how MM handles this and Phantom.
<img width="1272" alt="Screenshot 2022-06-30 at 16 23 48" src="https://user-images.githubusercontent.com/12224304/176721051-2e601838-8f9f-4755-9b45-74e32546becb.png">

## Steps to Reproduce

   1. click into your ethereum holdings.
   2. on this page you should have a link to token details
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by muliswilliam** [comment]
<img width="356" alt="screenshot_2022-08-04_at_15 23 28" src="https://user-images.githubusercontent.com/48117473/183045321-efc4f99a-8392-4d11-9712-4c6bb475ccc2.png">

<img width="418" alt="Screenshot 2022-08-04 at 15 58 22" src="https://user-images.githubusercontent.com/48117473/183045125-5637b8b0-b155-4863-96ef-f31488c02dc6.png">

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (64-bit)
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | Linux

- Verified steps from [brave/brave-core#14677](https://github.com/brave/brave-core/pull/14677)
- Verified tokens added to visible asset lists show `...` menu next to hide balance button
- Verified menu is not visible for native tokens
- Verified clicking the 3 dot menu shows `Token details`, `View on block explorer` & `Hide <TOKEN>` options
- Verified clicking on Token details shows token details in popup window
- Verified clicking on View on block explorer loads a new tab and opens the block explorer details of the token
- Verified clicking on Hide token shows a prompt to hide. Selecting Hide removes the token from the visible asset list
- Verified Token details popup also has a Hide token button which works similar to Hide token from menu
- Encountered [#26023](https://github.com/brave/brave-browser/issues/26023)

https://user-images.githubusercontent.com/17010094/195792736-80e794ed-5466-4378-b479-a61220f8936e.mp4


----------------
Verification passed on 

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (64-bit)
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | Windows 11 Version 21H2 (Build 22000.978)

- Verified steps from [brave/brave-core#14677](https://github.com/brave/brave-core/pull/14677)
- Verified tokens added to visible asset lists show `...` menu next to hide balance button
- Verified menu is not visible for native tokens
- Verified clicking the 3 dot menu shows `Token details`, `View on block explorer` & `Hide <TOKEN>` options
- Verified clicking on Token details shows token details in popup window
- Verified clicking on View on block explorer loads a new tab and opens the block explorer details of the token
- Verified clicking on Hide token shows a prompt to hide. Selecting Hide removes the token from the visible asset list
- Verified Token details popup also has a Hide token button which works similar to Hide token from menu
- Encountered [#26023](https://github.com/brave/brave-browser/issues/26023)

https://user-images.githubusercontent.com/17010094/195793234-2ed17323-d91f-49cd-8ea1-f77684e69aa0.mp4

----------------
Verification passed on 

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (arm64)
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | macOS Version 12.6 (Build 21G115)

- Verified steps from [brave/brave-core#14677](https://github.com/brave/brave-core/pull/14677)
- Verified tokens added to visible asset lists show `...` menu next to hide balance button
- Verified menu is not visible for native tokens
- Verified clicking the 3 dot menu shows `Token details`, `View on block explorer` & `Hide <TOKEN>` options
- Verified clicking on Token details shows token details in popup window
- Verified clicking on View on block explorer loads a new tab and opens the block explorer details of the token
- Verified clicking on Hide token shows a prompt to hide. Selecting Hide removes the token from the visible asset list
- Verified Token details popup also has a Hide token button which works similar to Hide token from menu
- Encountered [#26023](https://github.com/brave/brave-browser/issues/26023)

https://user-images.githubusercontent.com/17010094/195790924-d418b2fb-7b0e-4c01-a9a7-2329f38dc53a.mov
