### ISSUE TITLE
Refactor Brave Ads file access - Follow up to 22340

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#23794]
## Description 

See https://github.com/brave/internal/issues/877

## Steps to Reproduce

- Fresh install
- Join Rewards
- Visit some websites
- Quit the browser
- Launch the browser

## Actual result:

See https://github.com/brave/internal/issues/877

## Expected result:
See https://github.com/brave/internal/issues/877

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.42.65 Chromium: 103.0.5060.114 (Official Build) beta (64-bit)
-- | --
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | Ubuntu 18.04 LTS

Verified in https://github.com/brave/internal/issues/877#issuecomment-1191166313
