### ISSUE TITLE
window.name should be cleared on cross-origin navigation

### ISSUE THREAD

**Issue by pilgrim-brave** [brave/brave-browser#23798]

**Comment by pilgrim-brave** [comment]
c.f. https://privacytests.org/

**Comment by kjozwiak** [comment]
The above will require `1.41.94` or higher for `1.41.x` verification 👍 As mentioned via https://github.com/brave/brave-browser/issues/5910#issuecomment-1176845799, this is basically the same check re: running through https://dev-pages.bravesoftware.com/dom-properties/window-name.html.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.41.91 x64 build
- Verified `window.name` returns value `NA` on both the test pages

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/177747860-9afeff33-7714-412e-ba10-d9e37c00eb38.mp4> | <video src=https://user-images.githubusercontent.com/17010094/177747845-b4323bb9-4bb8-47f4-95b1-1daeb0a78e11.mp4>

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.41.94 Chromium: 103.0.5060.114 (Official Build) (x86_64)
-- | --
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | macOS Version 12.4 (Build 21F79)
```
