### ISSUE TITLE
Show solana Assets and Accounts

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#23809]
Solana transaction details/list should be shown in the 

- AccountDetailActivity and AssetDetailsActivity. Make it to show Solana accounts and account's assets.
- Update PortfolioFragment to show correct Solana assets, show Solana network assets on Edit Visible Assets.

**Comment by SergeyZhukovsky** [comment]
I created a separate issue for transactions list https://github.com/brave/brave-browser/issues/24292. I prepared all the code for it, it might work as expected, but needs to be re-checked.
TxFragment for the ongoing transaction after the send is going to be checked and fixed in a Send issue.

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on `Samsung Galaxy Tab A7 version 11` running `Bravemonoarm64.apk_1.42.89`

- Verified Accounts, Assets and Portfolio screens show Solana accounts and assets

Account details | Portfolio | Visible assets
-- | -- | --
![Screenshot_20220808-221804_Brave](https://user-images.githubusercontent.com/38657976/183471390-8b0778c5-71bb-41c5-84a7-1b18e5610216.jpg) | ![Screenshot_20220808-221828_Brave](https://user-images.githubusercontent.com/38657976/183471421-fe2eb39e-4870-4512-b31b-b9af416660a6.jpg) | ![Screenshot_20220808-222023_Brave](https://user-images.githubusercontent.com/38657976/183471456-4806a5d0-bd96-43c0-935c-d7ec57099634.jpg)
