### ISSUE TITLE
npm audit script misses sync deps

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#2380]
npm audit_deps should check src/brave/brave_sync/extension since there are npm packages in there

**Comment by diracdeltas** [comment]
marking this as security p3 since currently there are known vulns in brave-sync and brave-crypto

**Comment by darkdh** [comment]
@bbondy do we need to uplift the commit to the branch that contains sync?
or is it ok to wait for the channel bump?

**Comment by bbondy** [comment]
seems safer. 0.58.x will have sync.
