### ISSUE TITLE
Add translation service to Brave

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#23813]
## Description 
We have a translation service that is available in Nightly 1.42.x which can be enabled via brave://flags/#brave-translate-go

Some specific issues have been captured and labeled with [brave-translate](https://github.com/brave/brave-browser/issues?q=is%3Aopen+is%3Aissue+label%3Abrave-translate)

This issue is intended to track work required before we can release Brave Translate

## Brave version (brave://version info)

Target release 1.43.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using 
```
Brave | 1.43.67 Chromium: 104.0.5112.81 (Official Build) beta (64-bit)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | Windows 11 Version 21H2 (Build 22000.856)
```

Case 1:  `Brave translate` extension appearance - `PASSED`
<Details>

Dark1|Dark2|Light1|Light2
----|----|-----|----
<image width ="850" alt="image" src="https://user-images.githubusercontent.com/98358127/184263562-50a4ff18-603d-401a-b45b-b1611cf94c0c.png">|<image width ="850" alt="image" src="https://user-images.githubusercontent.com/98358127/184263494-aac98a96-0c5e-46ad-a52c-e0f2d7de7f53.png">|<image width ="850" alt="image" src="https://user-images.githubusercontent.com/98358127/184263525-94766042-5559-4e59-8737-e438848193ed.png">|<image width ="850" alt="image" src="https://user-images.githubusercontent.com/98358127/184263545-1500a4f3-03f3-4237-923d-60ded378a21d.png">
</details>

Case 2:  No `UseBraveTranslateGo` feature  - `PASSED`
<Details>

1. Install 1.43.67
2. launch Brave
3. leave the default value for `#brave-translate-go` in the `brave://flags`
4. visit `brave://settings/languages` and verify `French` is not listed
5. load https://www.lemonde.fr/

#### Confirmed `Google translate` extension  bubble is shown 

Step 3|Step 4|Step 5
-----|-----|------ 
<image width ="850" alt="image" src="https://user-images.githubusercontent.com/98358127/184257231-9585cf6b-ddb8-4962-9a18-c4360fcdfcf0.png">|<image width ="850" alt="image" src="https://user-images.githubusercontent.com/98358127/184257260-8daadf47-126c-40fc-8dfa-ef9bb94e5e6e.png">|<image width ="850" alt="image" src="https://user-images.githubusercontent.com/98358127/184257813-18c44bb3-3f4d-4f18-9772-85caec9b5789.png">

</details>

Case 3:  (Desktop) `UseBraveTranslateGo` + enabled Google Translate extension
<Details>

</details>

Case 4: (Desktop) Migration
<Details>


</details>

Case 5: (Desktop) Enabled `UseBraveTranslateGo` feature - Functionality
<Details>

1. clean profile
2. launch Brave
3. open `brave://flags` and enable `#brave-translate-go`
4. visit `brave://settings/languages` and verify French is not listed
5. https://www.lemonde.fr/
6. confirmed `Brave translate...` bubble is shown 
7. click (x) is dismiss the modal

Step 3|Step4|Step6
----|----|-----
<image width ="850" alt="image" src="https://user-images.githubusercontent.com/98358127/184257231-9585cf6b-ddb8-4962-9a18-c4360fcdfcf0.png">|<image width ="850" alt="image" src="https://user-images.githubusercontent.com/98358127/184257260-8daadf47-126c-40fc-8dfa-ef9bb94e5e6e.png">|<image width ="850" alt="image" src="https://user-images.githubusercontent.com/98358127/184263827-9f985b5f-a105-4970-81ea-6b64445778bf.png">

</details>

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.43.70 Chromium: 104.0.5112.81 (Official Build) beta (x86_64)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | macOS Version 11.6.8 (Build 20G730)

Testcase 1
<details>

TBD

</details>

Testcase 2
<details>

TBD

</details>

Testcase 3
<details>

TBD

</details>

Testcase 4
<details>

TBD

</details>

Testcase 5
<details>

TBD

</details>
Testcase 6
<details>

TBD

</details>

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.43.78 Chromium: 104.0.5112.102 (Official Build) beta (64-bit)
-- | --
Revision | 8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}
OS | Ubuntu 18.04 LTS

Testcase 1 - Brave Translate extension appearance - `PASSED`
<details>

- install `1.43.x`
- launch Brave
- load `brave://flags`
- flip `Enable internal translate engine` to `Enabled`
- restart Brave

![image](https://user-images.githubusercontent.com/34715963/185923449-f441a9cc-45c6-4658-a2a6-15ec3be576cb.png)

![image](https://user-images.githubusercontent.com/34715963/185923675-37115ebe-1de8-43ef-ba2d-7d82a7856153.png)
![image](https://user-images.githubusercontent.com/34715963/185923713-1f7baea5-7931-4e1f-b5b2-45bdac3ae455.png)
![image](https://user-images.githubusercontent.com/34715963/185923787-760b3b9b-123c-40e0-b49d-c56fab8b650e.png)
![image](https://user-images.githubusercontent.com/34715963/185923819-08584178-1772-4551-bbd5-8c161556d157.png)








</details>

Testcase 2 - Enabled `UseBraveTranslateGo` feature - UI validation - `PASSED`
<details>

1. clean profile
2. launch Brave
3. restart the browser to enable `Brave translate` via griffin
4. visit `brave://settings/languages` 
5. verified `German` is not listed in the `Order languages based on your preferences`
6. verified toggle `ON` as a default for `Offer to translate pages that aren't in a language you read` entry 
7.  visit `brave://translate-internals` to confirm `de (German)` is a supported language
8. load `speigel.de`
9. confirmed `Brave translate` extension bubble is shown 
10. click (x) to dismiss the modal and reload the page to view the `Brave translate` extension bubble
11. hover over the extension icon in the URL bar to show `Translate this page` text 
12. confirmed extension bubble displays the language  to be translated from the visited site - `German` along with `English`
13. click hamburger menu to confirm the following:
    - `Choose another language`
    - `Always translate German`
    - `Never translate German`
    - `Never translate this site`
    - `Page is not German`
14. confirmed the languages listed in the drop drown for `Language to translate into`  match to the supported languages in `brave://translate-internals`

![image](https://user-images.githubusercontent.com/34715963/185924538-6dae37f6-e03e-4a06-a244-cc405ae94927.png)
![image](https://user-images.githubusercontent.com/34715963/185924644-9a4cd066-27de-4669-8ce0-3e5874b5459a.png)
![image](https://user-images.githubusercontent.com/34715963/185925331-26404a54-5ab6-44b9-b096-dfadab075198.png)
![image](https://user-images.githubusercontent.com/34715963/185925465-8d44d535-6731-4903-a7c0-b130dcff584b.png)
![image](https://user-images.githubusercontent.com/34715963/185925504-53e37ef4-594c-427b-afcd-db1b3dd4a0c4.png)
![image](https://user-images.githubusercontent.com/34715963/185925629-8d67f35f-0b83-4c13-94b2-d55afe1d03c0.png)







</details>

Testcase 3 - no `UseBraveTranslateGo` feature via `brave://settings/languages` - `PASSED`
<details>

1. install `1.43.x`
2. launch Brave
3. relaunch Brave to enable the flag #brave-translate-go` via Griffin
4. visit `brave://settings/languages`
5. verified German is not listed in the `Order languages based on your preferences`
6. visit `brave://translate-internals` to confirm `de (German)` is a supported language
7. open `brave://settings/languages` and toggle `OFF` for `Offer to translate pages that aren't in a language you read` entry
8. load `www.speigel.de`
9. confirmed `Brave translate` extension is not displayed in the URL bar
10. confirmed `Google Translate` extension bubble not shown

![image](https://user-images.githubusercontent.com/34715963/185926176-be42896e-9bba-40e1-8085-85e007e2cd97.png)
![image](https://user-images.githubusercontent.com/34715963/185926238-39914c34-9a4f-41a3-9074-68355eb3250d.png)



</details>

Testcase 4 - Enabled `UseBraveTranslateGo` feature - functionality - `PASSED`
<details>

Case 1: `Choose another language` - `Dutch` - `PASSED`
<details>

1. clean profile
2. launch Brave
3. restart the browser to enable Brave translate via Griffin
4. leave toggle `ON` as a default for `Offer to translate pages that aren't in a language you read` entry
5. visit Spanish language site `laopinion.com`
6. confirmed `Brave translate` extension bubble is shown
7. click hamburger and select 'Choose another language' - `Dutch`
8. click `Translate`
9. default language English is replaced by Dutch in the extension bubble
10. home page is translated into Dutch
11. clicked few links to verify pages are translated into Dutch as well
12. activated speed reader icon and page rendered in speed reader mode

![image](https://user-images.githubusercontent.com/34715963/185926535-14fefd71-95df-41db-9513-51b9f994ec0e.png)
![image](https://user-images.githubusercontent.com/34715963/185926617-e536fd6d-26a8-4587-9064-8d5f6c0b9cc3.png)


</details>

Case 2: `Always translate <supported language>` - `PASSED`
<details>

1. clean profile
2. launch Brave
3. restart the browser to enable `Brave translate` via Griffin
4. leave toggle `ON` as a default for `Offer to translate pages that aren't in a language you read` entry
5. visit French language site `www.lemonde.fr`
6. confirmed `Brave translate` extension bubble is shown
7. click hamburger and select `Always translate French`
8. switch between French and English language and the translation worked as expected
9. functionality worked as expected compared to Chrome's `Google Translate` extension


![image](https://user-images.githubusercontent.com/34715963/185927437-969e7a71-4184-4d8a-9a80-3e780c2a1639.png)
![image](https://user-images.githubusercontent.com/34715963/185927965-52c45113-fd1a-48d1-9d86-6cae30d31194.png)




</details>

Case 3: `Never translate <supported language>` - `PASSED`
<details>

1. clean profile
2. launch Brave
3. restart the browser to enable `Brave translate` via Griffin
4. leave toggle `ON` as a default for `Offer to translate pages that aren't in a language you read` entry
5. visit French language site `www.lemonde.fr`
6. confirmed `Brave translate` extension bubble is shown
7. click hamburger and select `Never translate French`
8. click on a link
9. confirmed `Brave translate` extension no longer displayed in the URL bar

![image](https://user-images.githubusercontent.com/34715963/185928141-1200bbfe-bdcd-41cb-8adc-939d10306773.png)
![image](https://user-images.githubusercontent.com/34715963/185928224-aa925fa0-be74-4f59-b2c4-b9baf765d1b2.png)


</details>

Case 4: `Never translate this site` - `PASSED`
<details>

1. clean profile
2. launch Brave
3. restart the browser to enable `Brave translate` via Griffin
4. leave toggle `ON` as a default for `Offer to translate pages that aren't in a language you read` entry
5. visit French language site `www.lemonde.fr`
6. confirmed `Brave translate` extension bubble is shown
7. click hamburger and select `Never translate this site`
8. click a link or reload the page
9. confirmed `Brave translate` extension no longer displayed in the URL
10. loaded `www.france24.com/fr` and confirmed I still got the `Brave translate` UI

![image](https://user-images.githubusercontent.com/34715963/185928632-ffdbdb5f-b687-4b00-9e42-132559532503.png)
![image](https://user-images.githubusercontent.com/34715963/185928750-346ad358-5879-4296-bdb7-c3851d48fd27.png)
![image](https://user-images.githubusercontent.com/34715963/185928838-01d385de-6e98-4d1e-9f67-d2bc2db2a40c.png)




</details>

Case 5: `Page is not in <supported language>` - `PASSED`
<details>

1. clean profile
2. launch Brave
3. restart the browser to enable Brave translate via Griffin
4. leave toggle `ON` as a default for `Offer to translate pages that aren't in a language you read` entry
5. visit French language site `www.lemonde.fr`
6. confirmed Brave translate extension bubble is shown
7. click hamburger and select `Page is Not in French`


![image](https://user-images.githubusercontent.com/34715963/185930609-51e61057-6381-4b03-824b-a7607aad619b.png)
![image](https://user-images.githubusercontent.com/34715963/185930717-eba56a51-dd4d-492b-b2bf-b4102dff639c.png)


</details>

Case 6: Unsupported languages in `brave://translate-internals` - `PASSED`
<details>

1. clean profile
2. launch Brave
3. restart the browser to enable `Brave translate` via Griffin
4. visit `brave://translate-internals` to confirm Korean language is not listed in Supported languages
5. visit `brave://settings/languages`
6. verified toggle `ON` as a default for `Offer to translate pages that aren't in a language you read` entry
7. visit Korean language site `www.segye.com`
8. confirmed `Brave translate` extension is not loaded

![image](https://user-images.githubusercontent.com/34715963/185931303-66771730-0f31-4656-86f7-99aee6aec6d0.png)


</details>

Case 7: Language already listed in `brave://settings/languages` - `PASSED`
<details>

1. clean profile
2. launch Brave
3. restart the browser to enable `Brave translate` via Griffin
4. open `brave://settings/languages`
5. click `Add languages` to add one of the supported languages `hi (Hindi)`
6. Added language is listed
7. visit Hindi language site `www.dainiktribuneonline.com`
8. confirmed `Brave translate` extension is not displayed in the URL bar
9. open `brave://settings/languages` and click on ellipsis for Hindi entry
10. check the checkbox for `Offer to translate pages in this language`
11. Return to the website `www.dainiktribuneonline.com` and reload the page
12. `Brave translate` extension displayed in the URL bar

![image](https://user-images.githubusercontent.com/34715963/185931703-8b2d41a9-7a17-46bd-b7b9-378b6ce203c2.png)
![image](https://user-images.githubusercontent.com/34715963/185931900-fde56bfd-ce17-4919-8ec1-4f4434e07375.png)
![image](https://user-images.githubusercontent.com/34715963/185932002-83298e99-6c59-4582-9353-768e6eaa16fb.png)
![image](https://user-images.githubusercontent.com/34715963/185932126-09baba7f-3718-4d16-bee8-9402d5246ece.png)


</details>

Case 8: `Translate to <supported language>` context-menu item - `PASSED`
<details>
1. clean profile
2. launch Brave
3. restart the browser to enable `Brave translate` via Griffin
4. load `hoylosangeles.com`
5. context-click the page and select `Translate to English`
6. confirm the page is translated into English, from Spanish


![image](https://user-images.githubusercontent.com/34715963/185932750-82ed6b93-a7c3-4cbc-9336-47f485b5e5c7.png)
![image](https://user-images.githubusercontent.com/34715963/185932798-f92ab563-c78a-4174-b729-5d2ed4b9d2d9.png)


</details>




</details>

</details>

Testcase 5 - `Brave translate` overrides `Google Translate` after enabling it - `PASSED`
<details>

1. clean profile
2. launch Brave
3. do not restart the browser (this is will enable Brave translate via Griffin)
4. keep `Default` selection in `brave://flags/#brave-translate-go`
7. visit `brave://translate-internals` to confirm `es (Spanish)` is a supported language
8. visit `brave://settings/languages`
* verified Spanish is not listed
* verified toggle `ON` as a default for `Offer to translate pages that aren't in a language you read` entry
9. visit Spanish language site `www.bbc.com/mundo`
10. `Google Translate` extension displayed in the URL bar as expected
11. restart the browser to enable `Brave translate` via Griffin
12. `Brave translate` extension bubble displayed for `www.bbc.com/mundo` when page loaded

![image](https://user-images.githubusercontent.com/34715963/185940095-e2ba6301-4584-4902-bb22-165e08dbbdb6.png)

![image](https://user-images.githubusercontent.com/34715963/185940380-a9f7642f-2bbb-4330-8a9f-6ea2d190958a.png)
![image](https://user-images.githubusercontent.com/34715963/185940623-407abf34-84b5-4b60-84d6-21686d005520.png)



</details>

Testcase 6 - Upgrade- `PASSED`
<details>

1. install `1.42.x`
2. launch Brave
3. load a Russian language site `www.mail.ru`
4. `Google Translate` extension bubble is shown in the URL bar as expected
5. close the browser but do not close the tabs
6. rename the profile folder to `Brave-Browser-Beta`
7. launch Brave with `1.43.x`
8. verified toggle `ON` as a default for `Offer to translate pages that aren't in a language you read` entry
9. `mail.ru` site tab is loaded with `Brave translate` extension bubble is displayed in the URL bar

![image](https://user-images.githubusercontent.com/34715963/185941504-adb19092-46b7-472a-b19d-7731bea10405.png)
![image](https://user-images.githubusercontent.com/34715963/185941704-97995a6f-ce04-4cee-8580-776ab5ef6db3.png)


</details>


Testcase 7 - Change OS language - `PASSED`
<details>

1. change language
2. clean profile
3. launch Brave
4. restart the browser to enable `Brave translate` via Griffin
5. visit English language site `www.bbc.com`
6. confirmed `Brave translate` bubble is displayed in the URL bar
7. confirmed bubble options displayed in selected in OS language Polish

![image](https://user-images.githubusercontent.com/34715963/185961214-662cbad7-f1d0-4904-93e9-743d05de8891.png)
![image](https://user-images.githubusercontent.com/34715963/185961272-804ca0f9-3f2b-4dac-a9cb-9421d9d96a10.png)





</details>

**Comment by UjCbFwtBayFM** [comment]
Is it hosted by Brave or is it relayed elsewhere? There is no documentation about this.

**Comment by 8227846265** [comment]
Doesn't seem to work. The prompt for language translation shows to install Google Translate extension

**Comment by skariko** [comment]
> 

Same on Windows 10 and Brave 1.43.88

**Comment by emacsomancer** [comment]
Similarly does not seem to be on by default in Linux.  

Does brave://flags/#brave-translate-go still need to be manually set in this version?

**Comment by atuchin-m** [comment]
@emacsomancer  @skariko  @8227846265
[The PR](https://github.com/brave/brave-variations/issues/351) to enable the feature for 100% audience have been merged recently.

All actual browser versions should have Translate feature available now (Desktop & Android). You don't need to set `brave://flags/#brave-translate-go` manually. 
If it doesn't work for you please restart you browser and check you have the latest version.

We're still working supporting the rest languages: https://github.com/brave/brave-browser/issues/24303

**Comment by 8227846265** [comment]
It works now without setting up the flag. No more prompt to install Google Translate extension.
![image](https://user-images.githubusercontent.com/66582769/189616993-902c795b-ff1f-4184-94ae-ab9837c807e4.png)

**Comment by UjCbFwtBayFM** [comment]
> @emacsomancer @skariko @8227846265 [The PR](https://github.com/brave/brave-variations/issues/351) to enable the feature for 100% audience have been merged recently.
It would have been nice to mention the progressive roll-out of this feature in a more visible channel, like the release notes.

**Comment by atuchin-m** [comment]
@rebron have we mentioned the launch somewhere?

**Comment by atuchin-m** [comment]
> Is it done locally, hosted by Brave or is it relayed elsewhere? There is no documentation about this.
It's a brave hosted solutions from [Lingvanex](https://lingvanex.com/).
I'm updating the docs here: https://github.com/brave/go-translate/pull/19

**Comment by bsclifton** [comment]
@atuchin-m can you please update the docs here too?
https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)

Thanks 😄
