### ISSUE TITLE
Add warning about possible DNS leaks when user turns on aggressive mode in Shields

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#23812]
## Description 

Add a dismissible warning to the shields panel and in the global shields settings -> brave://settings/shields to warn users about possible DNS leaks when using a custom proxy. 

This warning should only display when users select the `Aggressively block trackers and ads` option or `Aggressive` mode in brave://settings/shields.

The warning will remain until the user dismisses the warning by clicking the `x` and will no longer show after that dismissal.

## Expected result:

See description.

<img width="599" alt="Screen Shot 2022-06-30 at 3 58 26 PM" src="https://user-images.githubusercontent.com/5951041/176793817-cddf3100-6f1c-4ea8-9c89-8e763b80ce7b.png">

Figma link for assets: https://www.figma.com/file/3A6F6VrxVahiZFxLr7j7FO/Desktop-Shields?node-id=689%3A24419

## Reproduces how often: 

n/a

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

See related issue: https://github.com/brave/brave-browser/issues/23552

**Comment by aguscruiz** [comment]
Adding Figma files for Shields Settings
https://www.figma.com/file/tLXWGCpNoiJxDZDdpfordj/Desktop-Settings?node-id=2519%3A49137

**Comment by diracdeltas** [comment]
i think this is no longer needed now that https://github.com/brave/brave-core/pull/14122 was merged

**Comment by antonok-edm** [comment]
@diracdeltas should we reopen this? (regarding https://github.com/brave/brave-browser/issues/21034)
