### ISSUE TITLE
Brave search conversion promotion in omnibox is visible for Non promo-enabled country (Japan)

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#23815]
## Steps to Reproduce

   1. Install 1.41.86
   2. set `Country or region` to Japan in windows settings
   3. launched Brave using --enable-features=BraveSearchOmniboxBanner command-line switch
   4. keep Google as search engine in `brave://settings/search`
   5. typed `brav` in the url bar
   
## Actual result:

Search promo banner appeared

<img width="454" alt="image" src="https://user-images.githubusercontent.com/98358127/176803647-a6f10c57-e4b1-4cd9-966b-6771328cbc7c.png">

## Expected result:
Promotion should not be enabled 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.41.86 Chromium: 103.0.5060.66 (Official Build) beta (64-bit)
-- | --
Revision | 20b1569438a85e631d15e83eb355e3e326e5da6f-refs/branch-heads/5060@{#1066}
OS | Windows 11 Version 21H2 (Build 22000.739)

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:
 @simonhong @rebron

**Comment by rebron** [comment]
@MadhaviSeelam This might be invalid. I think country or region is set during installation so changing region post installation won't stick.

**Comment by simonhong** [comment]
This issue is not valid anymore because we deleted hardcoded allowed country list.
Promotion will be shown with `--enable-features=BraveSearchOmniboxBanner` cmd switch always.
Instead, we'll control allowed coutry list via griffin.
