### ISSUE TITLE
Brave-ui: consistent variable types for token amounts

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#2381]
There was a mixture of `number` and `string` types in play for token amounts under `siteBanner`. This brave-ui PR correctly converts them to `string` types: https://github.com/brave/brave-ui/pull/299

brave-ui needs a bump to `36.0`

**Comment by NejcZdovc** [comment]
reverted https://github.com/brave/brave-core/pull/1051#event-2016743870 so reopening
