### ISSUE TITLE
Update search engine defaults for AT / ES / MX 

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#23814]
## Description 
Update search engine defaults for:
- Austria (AT)
- Spain (ES)
- Mexico (MX)

Brave should be at the top of drop down list at brave://settings/search 

Related: https://github.com/brave/brave-browser/issues/18331

### Region set to AT / ES / MX 
1. Fresh profile
2. Search onboarding should NOT be shown
3. Default search engine SHOULD be Brave
4. Visit brave://settings/searchEngines
5. Brave SHOULD be first in the `Default search engines` list

### Region set to anything else (excluding CA / DE / FR / GB / US)
1. Fresh profile
2. Search onboarding SHOULD be shown
3. Default will NOT be Brave Search
4. Brave Search should NOT be in the Onboarding list
5. Visit brave://settings/searchEngines
6. Brave SHOULD be first in the `Default search engines` list - unless you're in a region where Yandex is default (AM, AZ, BY, KG, KZ, MD, RU, TJ, TM, UZ). In that case it will be second.

**Comment by kjozwiak** [comment]
The above will require `1.42.80` or higher for `1.42.x` verification 👍

**Comment by kjozwiak** [comment]
@brave/qa-team as discussed with @rebron, we don't need to run through each locale like I did via https://github.com/brave/brave-core/pull/14177#issuecomment-1195042499 on Nightly before uplifted. On each platform, we can check the following:

* single check on either `AT`, `ES` or `MX`
* single check on either `CA`, `DE`, `FR`, `GB` or `US`
* single check of a locale that isn't listed above to ensure that `Brave Search` isn't default and the search screen is still visible via `brave://welcome` during onboarding.

Please coordinate so we're not doing the same locales twice when verifying via `1.42.x`.

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```
Brave | 1.42.80 Chromium: 104.0.5112.57 (Official Build) (64-bit)
-- | --
Revision | 212fd173a0da1e0a024f328295bb56a2529190bb-refs/branch-heads/5112@{#1042}
OS | Windows 10 Version 21H2 (Build 19044.1826)

```
**_AT (Austria) locale_**


----
As per https://github.com/brave/brave-browser/issues/23908, ensured that locales from CA / DE / FR / GB / US are not displaying the Set default search engine screen via brave://welcome (onboarding).

**_US (United states) locale_**

----
Checking to ensure that locales that don't have Brave Search as the default and still have the Set default search engine screen screen via brave://welcome (onboarding) are working as expected.

**_IN (India) locale_**

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.42.80 Chromium: 104.0.5112.57 (Official Build) (x86_64)
-- | --
Revision | 212fd173a0da1e0a024f328295bb56a2529190bb-refs/branch-heads/5112@{#1042}
OS | macOS Version 12.5 (Build 21G72)
```

**Comment by Uni-verse** [comment]
Verification in Progress on Android ARM using

```
Brave	1.42.80 Chromium: 104.0.5112.57 (Official Build) (64-bit) 
Revision	212fd173a0da1e0a024f328295bb56a2529190bb-refs/branch-heads/5112@{#1042}
OS	Android 12; Build/SP1A.210812.016
```
- Verified the test plan from https://github.com/brave/brave-browser/issues/23814#issue-1290770631

### MX (Mexico) locale

#### `Case #1` - https://github.com/brave/brave-browser/issues/23908

<details>
<summary>brave://welcome</summary>

Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/23908#issue-1296549984 and ensured that the `Set default search engine screen` was removed from `brave://welcome` as per the following:


</details>

#### `Case #2` - https://github.com/brave/brave-browser/issues/23814

<details>
<summary>Clean Profile</summary>

* ensured that `Brave` was selected as the default for both Normal/Private windows via `brave://settings/searchEngines`
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Private` windows


</details>

<details>
<summary>Updated Profile (Google/Google)</summary>

* installed `1.41.100 Chromium: 103.0.5060.134`
* ensured that `Google` was the default SE selected under `brave://settings/searchEngines`
* updated to `1.42.80 Chromium: 104.0.5112.57` and ensured that `Google` is still the default SE in both Normal and Private windows SE
  * ensured that it wasn't replaced by `Brave`
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Private` windows

</details>

<details>
<summary>Updated Profile (Startpage/DDG)</summary>

* installed `1.41.100 Chromium: 103.0.5060.134`
* ensured that `Startpage` was the default SE selected under `brave://settings/searchEngines` 
* updated to `1.42.80 Chromium: 104.0.5112.57` and ensured that both SE engines were selected as the default
  * ensured that it wasn't replaced by `Brave`
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Private` windows


- Install beta version `1.42.78  Chromium: 103.0.5060.134`
- Open brave://settings/search and ensure that `Google` is the default SE for both Normal and Private windows
- Change the SE to `Startpage` in Normal windows SE dropdown
- Change the SE to `DDG` in Private windows SE dropdown
- Rename the profile to Release channel and upgrade the profile to `1.42.80 Chromium: 104.0.5112.57`
- Ensured that `Startpage` was the default SE selected under `brave://settings/searchEngines` for Normal windows
- Ensured that `DDG` was the default SE selected under `brave://settings/searchEngines` for Private windows


- ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Normal` windows
- ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Private` windows


</details>

<details>
<summary>Updated Profile (Ecosia/Qwant)</summary>

* installed `1.41.100 Chromium: 103.0.5060.134`
* ensured that `Ecosia` was the default SE selected under `brave://settings/searchEngines` 
* updated to `1.42.80 Chromium: 104.0.5112.57` and ensured that both SE engines were still selected as the default
  * ensured that it wasn't replaced by `Brave`
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Private` windows


- Install beta version `1.42.78  Chromium: 103.0.5060.134`
- Open brave://settings/search and ensure that `Google` is the default SE for both Normal and Private windows
- Change the SE to `Ecosia` in Normal windows SE dropdown
- Change the SE to `Qwant` in Private windows SE dropdown
- Rename the profile to Release channel and upgrade the profile to `1.42.80 Chromium: 104.0.5112.57`
- Ensured that `Ecosia` was the default SE selected under `brave://settings/searchEngines` for Normal windows
- Ensured that `Qwant` was the default SE selected under `brave://settings/searchEngines` for Private windows



- ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Normal` windows
- ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Private` windows



</details>

----
As per https://github.com/brave/brave-browser/issues/23908, ensured that locales from CA / DE / FR / GB / US are not displaying the Set default search engine screen via brave://welcome (onboarding).

### GB (United Kingdom) locale


 `Case #1` - https://github.com/brave/brave-browser/issues/23908

<details>
<summary>brave://welcome</summary>

Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/23908#issue-1296549984 and ensured that the `Set default search engine screen` was removed from `brave://welcome` as per the following:


</details>

`Case #2` - https://github.com/brave/brave-browser/issues/23814

<details>
<summary>Clean Profile</summary>

* ensured that `Brave` was selected as the default for both Normal/Private windows via `brave://settings/searchEngines`
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Private` windows


</details>

<details>
<summary>Updated Profile (Brave/Brave)</summary>

* installed `1.41.100 Chromium: 103.0.5060.134`
* ensured that `Brave` was the default SE selected under `brave://settings/searchEngines`
* updated to `1.42.80 Chromium: 104.0.5112.57` and ensured that `Brave` is still the default SE
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Private` windows



</details>

<details>
<summary>Updated Profile (DDG/Startpage)</summary>

* installed `1.41.100 Chromium: 103.0.5060.134`
* ensured that `DDG` was the default SE selected under `brave://settings/searchEngines` for `Normal` windows and 
* updated to `1.42.80 Chromium: 104.0.5112.57` and ensured that both SE engines were still selected as the default
  * ensured that it wasn't replaced by `Brave`
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Private` windows





- Install beta version `1.42.78  Chromium: 103.0.5060.134`
- Open brave://settings/search and ensure that `Brave` is the default SE in both Normal and Private window SE
- Change the SE to `DDG` in Normal windows SE dropdown
- Change the SE to `Startpage` in Private windows SE dropdown
- Rename the profile to Release channel and upgrade the profile to `1.42.80 Chromium: 104.0.5112.57`
- Ensured that `DDG` was the default SE selected under `brave://settings/searchEngines` for Normal windows
- Ensured that `Startpage` was the default SE selected under `brave://settings/searchEngines` for Private windows





</details>

----
Checking to ensure that locales that don't have Brave Search as the default and still have the Set default search engine screen screen via brave://welcome (onboarding) are working as expected.

###  locale

`Case #1` - https://github.com/brave/brave-browser/issues/23908

<details>
<summary>brave://welcome</summary>

Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/23908#issue-1296549984 and ensured that the `Set default search engine screen` was removed from `brave://welcome` as per the following:


</details>

 `Case #2` - https://github.com/brave/brave-browser/issues/23814

<details>
<summary>Clean Profile</summary>

* ensured that `Google` was selected as the default for both Normal/Private windows via `brave://settings/searchEngines`
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Private` windows




</details>

<details>
<summary>Updated Profile (Google/Google)</summary>

* installed `1.41.100 Chromium: 103.0.5060.134`
* ensured that `Google` was the default SE selected under `brave://settings/searchEngines`
* updated to `1.42.80 Chromium: 104.0.5112.57` and ensured that `Google` is still the default SE in both Normal and Private window SE
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Private` windows




</details>

<details>
<summary>Updated Profile (Qwant/Bing)</summary>

* installed `1.41.100 Chromium: 103.0.5060.134`
* ensured that `Qwant` was the default SE selected under `brave://settings/searchEngines` 
* updated to `1.42.80 Chromium: 104.0.5112.57` and ensured that both SE engines were still selected as the default in both Normal and Private windows SE
  * ensured that it wasn't replaced by `Brave`
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Private` windows






- Install beta version `1.42.78  Chromium: 103.0.5060.134`
- Open brave://settings/search and ensure that `Google` is the default SE in both Normal and Private window SE
- Change the SE to `Qwant` in Normal windows SE dropdown
- Change the SE to `Bing` in Private windows SE dropdown
- Rename the profile to Release channel and upgrade the profile to `1.42.80 Chromium: 104.0.5112.57`
- Ensured that `Qwant` was the default SE selected under `brave://settings/searchEngines` for Normal windows
- Ensured that `Bing` was the default SE selected under `brave://settings/searchEngines` for Private windows


* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Private` windows




</details>

**Comment by Uni-verse** [comment]
Verification in progress on `Samsung Galaxy Tab S7` using

```
Brave	1.42.80 Chromium: 104.0.5112.57 (Official Build) (64-bit) 
Revision	212fd173a0da1e0a024f328295bb56a2529190bb-refs/branch-heads/5112@{#1042}
OS	Android 12; Build/SP1A.210812.016
```
- Verified the test plan from https://github.com/brave/brave-browser/issues/23814#issue-1290770631

###  AT (Austria) locale

#### `Case #1` - https://github.com/brave/brave-browser/issues/23908

<details>
<summary>Onboarding Flow</summary>

Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/23908#issue-1296549984 and ensured that the `Set default search engine screen` was removed from onboarding modals.




</details>

#### `Case #2` - https://github.com/brave/brave-browser/issues/23814

<details>
<summary>Clean Profile</summary>

* ensured that `Brave` was selected as the default for both Normal/Private windows
* ensured that `Brave` was the first engine via the drop down list for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list for `Private` windows

</details>

<details>
<summary>Updated Profile (Google/Google)</summary>

* installed `1.41.100 Chromium: 103.0.5060.134`
* ensured that `Google` was the default SE selected
* updated to `1.42.80 Chromium: 104.0.5112.57` and ensured that `Google` is still the default SE in both Normal and Private windows
 * ensured that it wasn't replaced by `Brave`
* ensured that `Brave` was the first engine via the drop down list for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list for `Private` windows

</details>

<details>
<summary>Updated Profile (Startpage/DDG)</summary>

* installed `1.41.100 Chromium: 103.0.5060.134`
* ensured that `Startpage` was the default SE selected for normal windows and 'DuckDuckGo' for Private windows.  
* updated to `1.42.80 Chromium: 104.0.5112.57` and ensured that both SE engines were selected as the default.
  * ensured that it wasn't replaced by `Brave`
* ensured that `Brave` was the first engine via the drop down list for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list for `Private` windows

</details>

<details>
<summary>Updated Profile (Bing/Qwant)</summary>

* installed `1.41.100 Chromium: 103.0.5060.134`
* ensured that `Bing` was the default SE selected for normal windows and `Qwant` for private
* updated to `1.42.80 Chromium: 104.0.5112.57` and ensured that both SE engines were still selected as the default
* ensured that it wasn't replaced by `Brave`
* ensured that `Brave` was the first engine via the drop down list for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list for `Private` windows

</details>

----
As per https://github.com/brave/brave-browser/issues/23908, ensured that locales from CA / DE / FR / GB / US are not displaying the Set default search engine screen via brave://welcome (onboarding).

### DE (Germany) locale


 `Case #1` - https://github.com/brave/brave-browser/issues/23908

<details>
<summary>Onboarding Flow</summary>

Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/23908#issue-1296549984 and ensured that the `Set default search engine screen` was removed from onboarding.



</details>

`Case #2` - https://github.com/brave/brave-browser/issues/23814

<details>
<summary>Clean Profile</summary>

* ensured that `Brave` was selected as the default for both Normal/Private windows 
* ensured that `Brave` was the first engine via the drop down list for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list for `Private` windows

</details>

<details>
<summary>Updated Profile (Brave/Brave)</summary>

* installed `1.41.100 Chromium: 103.0.5060.134`
* ensured that `Brave` was the default SE selected
* updated to `1.42.80 Chromium: 104.0.5112.57` and ensured that `Brave` is still the default SE
* ensured that `Brave` was the first engine via the drop down list for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list for `Private` windows

</details>

<details>
<summary>Updated Profile (DDG/Startpage)</summary>

* installed `1.41.100 Chromium: 103.0.5060.134`
* ensured that `DDG` was the default SE selected for `Normal` windows and `Startpage` for private windows.
* updated to `1.42.80 Chromium: 104.0.5112.57` and ensured that both SE engines were still selected as the default
  * ensured that it wasn't replaced by `Brave`
* ensured that `Brave` was the first engine via the drop down list for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list for `Private` windows

</details>

----
Checking to ensure that locales that don't have Brave Search as the default and still have the Set default search engine screen screen via brave://welcome (onboarding) are working as expected.

###  locale

`Case #1` - https://github.com/brave/brave-browser/issues/23908

<details>
<summary>Onboarding Flow</summary>

Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/23908#issue-1296549984 and ensured that the `Set default search engine screen` was not removed from onboarding.



</details>

 `Case #2` - https://github.com/brave/brave-browser/issues/23814

<details>
<summary>Clean Profile</summary>

* ensured that `Google` was selected as the default for both Normal/Private windows via `brave://settings/searchEngines`
* ensured that `Brave` was the first engine via the drop down list for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list for `Private` windows

</details>

<details>
<summary>Updated Profile (Google/Google)</summary>

* installed `1.41.100 Chromium: 103.0.5060.134`
* ensured that `Google` was the default SE selected 
* updated to `1.42.80 Chromium: 104.0.5112.57` and ensured that `Google` is still the default SE in both Normal and Private window SE
* ensured that `Brave` was the first engine via the drop down list for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list for `Private` windows

</details>

<details>
<summary>Updated Profile (Qwant/Bing)</summary>

* installed `1.41.100 Chromium: 103.0.5060.134`
* ensured that `Qwant` was the default SE selected under 
* updated to `1.42.80 Chromium: 104.0.5112.57` and ensured that both SE engines were still selected as the default in both Normal and Private windows SE
  * ensured that it wasn't replaced by `Brave`
* ensured that `Brave` was the first engine via the drop down list for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list for `Private` windows

</details>

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.42.81 Chromium: 104.0.5112.69 (Official Build) (64-bit)
-- | --
Revision | 7ce2902023c722af8564068e6b26e934b83fd774-refs/branch-heads/5112@{#1213}
OS | Ubuntu 18.04 LTS


- Verified the test plan from https://github.com/brave/brave-browser/issues/23814#issue-1290770631

### ES (Spain) locale

#### `Case #1` - https://github.com/brave/brave-browser/issues/23908

<details>
<summary>brave://welcome</summary>

Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/23908#issue-1296549984 and ensured that the `Set default search engine screen` was removed from `brave://welcome` as per the following:

![image](https://user-images.githubusercontent.com/34715963/181752456-60f5b8b1-6c7f-4b49-bd7a-41e2e198031e.png)
![image](https://user-images.githubusercontent.com/34715963/181752479-d23519f0-632d-43b7-8cf8-4694601e1b63.png)
![image](https://user-images.githubusercontent.com/34715963/181752501-09430339-2b29-4373-9288-4b1d16ea2d2a.png)


</details>

#### `Case #2` - https://github.com/brave/brave-browser/issues/23814

<details>
<summary>Clean Profile</summary>

* ensured that `Brave` was selected as the default for both Normal/Private windows via `brave://settings/search`
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Private` windows
* ensured that `Brave` was selected as the default via `brave://settings/searchEngines`

![image](https://user-images.githubusercontent.com/34715963/181752580-5fbff004-e6e0-4c38-bf90-503956a8ced5.png)
![image](https://user-images.githubusercontent.com/34715963/181752612-bb6c20d7-1012-4a55-a962-c8f26b42c793.png)
![image](https://user-images.githubusercontent.com/34715963/181752632-913a68d3-02ed-4f96-892f-63c272864d87.png)
![image](https://user-images.githubusercontent.com/34715963/181752692-c8eace5d-5fde-4dfb-a328-d27286d6417f.png)


</details>

<details>
<summary>Updated Profile (Google/Google)</summary>

* installed `1.41.x`
* ensured that `Google` was the default SE selected under `brave://settings/search`
* updated to `1.42.x` and ensured that `Google` is still the default SE in both Normal and Private windows SE
  * ensured that it wasn't replaced by `Brave`
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Private` windows

1.41.x
![image](https://user-images.githubusercontent.com/34715963/181753216-e690d219-86fe-40a0-b5f5-69428273dccd.png)
![image](https://user-images.githubusercontent.com/34715963/181753308-a7fdbadc-16dc-48bd-9c8e-93f28f281a58.png)


1.42.x
![image](https://user-images.githubusercontent.com/34715963/181753594-6f122633-1e1e-4a05-b54f-aa3ff464e15f.png)
![image](https://user-images.githubusercontent.com/34715963/181753612-c391e5da-6e04-4296-b039-2354b4bd99ff.png)
![image](https://user-images.githubusercontent.com/34715963/181753626-15313d60-a8f8-400a-be70-ab8c70b3558a.png)



</details>

<details>
<summary>Updated Profile (Startpage/DDG)</summary>

* installed `1.41.x`
* ensured that `Startpage` was the default SE selected under `brave://settings/search` 
* updated to `1.42.x` and ensured that previously selected SE is still the default for both Normal and Private windows
  * ensured that it wasn't replaced by `Brave`
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Private` windows


![image](https://user-images.githubusercontent.com/34715963/181754898-7719c650-7d4b-4fe9-a96c-ece1a0ac341f.png)
![image](https://user-images.githubusercontent.com/34715963/181755233-d76824d2-c6a8-466b-8087-ffbf59fec814.png)
![image](https://user-images.githubusercontent.com/34715963/181755271-84402b52-24e0-4676-950e-c292fa82ee98.png)
![image](https://user-images.githubusercontent.com/34715963/181755285-51bbc988-afff-43cc-9891-dfdd1d2b164c.png)


</details>

<details>
<summary>Updated Profile (Ecosia/Qwant)</summary>

* installed `1.41.x`
* ensured that `Ecosia` was the default SE selected under `brave://settings/search` 
* updated to `1.42.x` and ensured that previously selected SE is still the default for both Normal and Private windows
  * ensured that it wasn't replaced by `Brave`
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Private` windows

![image](https://user-images.githubusercontent.com/34715963/181755485-293bd0b7-82ac-4967-be78-f168e576be55.png)
![image](https://user-images.githubusercontent.com/34715963/181755496-6b647a3d-ee24-472b-9ced-73c8843f37b8.png)
![image](https://user-images.githubusercontent.com/34715963/181755514-ff24d5da-a92a-484d-8ed2-5e98aaf24af9.png)


</details>

------------------

As per https://github.com/brave/brave-browser/issues/23908, ensured that locales from CA / DE / FR / GB / US are not displaying the Set default search engine screen via brave://welcome (onboarding).

### de locale

 `Case #1` - https://github.com/brave/brave-browser/issues/23908

<details>
<summary>brave://welcome</summary>

Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/23908#issue-1296549984 and ensured that the `Set default search engine screen` was removed from `brave://welcome` as per the following:

![image](https://user-images.githubusercontent.com/34715963/181756357-d92a0df9-3bec-4710-ba7c-a6bfa10e100b.png)
![image](https://user-images.githubusercontent.com/34715963/181756375-117a6a69-f0a5-47e8-9ace-a12d2b020c45.png)
![image](https://user-images.githubusercontent.com/34715963/181756396-41eaf3b3-f5b5-4aa4-b760-17b218e18c1d.png)


</details>

`Case #2` - https://github.com/brave/brave-browser/issues/23814

<details>
<summary>Clean Profile</summary>

* ensured that `Brave` was selected as the default for both Normal/Private windows via `brave://settings/search`
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Private` windows
* ensured that `Brave` was selected as the default via `brave://settings/searchEngines`

![image](https://user-images.githubusercontent.com/34715963/181756473-02bfca13-1a12-4c28-b2d2-19079d876ad6.png)
![image](https://user-images.githubusercontent.com/34715963/181756497-3d495043-fdc7-4262-aefb-6635658819a4.png)
![image](https://user-images.githubusercontent.com/34715963/181756513-d066f6ca-b87e-41f0-ab01-c677329a71dd.png)


</details>

<details>
<summary>Updated Profile (Brave/Brave)</summary>

* installed `1.41.x`
* ensured that `Brave` was the default SE selected under `brave://settings/search`
* updated to `1.42.x` and ensured that `Brave` is still the default SE
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Private` windows

![image](https://user-images.githubusercontent.com/34715963/181756655-8cdc33c0-fefe-45e8-a654-7e9ecd9e26ba.png)
![image](https://user-images.githubusercontent.com/34715963/181756685-bb671a75-4086-4183-8389-d97484af2acf.png)
![image](https://user-images.githubusercontent.com/34715963/181756701-4558b39e-275b-4b95-b6b1-45341aa012c6.png)



</details>

<details>
<summary>Updated Profile (DDG/Startpage)</summary>

* installed `1.41.x`
* ensured that `DDG` was the default SE selected under `brave://settings/searchEngines` for `Normal` windows and 
* updated to `1.42.x` and ensured that previously selected SE is still the default for both Normal and Private windows
  * ensured that it wasn't replaced by `Brave`
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Private` windows

1.41.x
![image](https://user-images.githubusercontent.com/34715963/181758331-299cc118-333b-4eaf-9735-c77aa4119a48.png)

1.42.x
![image](https://user-images.githubusercontent.com/34715963/181760082-a3fa9d59-6cf7-41e8-b9c9-73870e890f09.png)
![image](https://user-images.githubusercontent.com/34715963/181760129-4603eba7-255b-4a4a-8c4c-449baad9ba21.png)
![image](https://user-images.githubusercontent.com/34715963/181760180-9ebb9055-ecbb-41e8-b0ca-976525435e94.png)


</details>

----

Checking to ensure that locales that don't have Brave Search as the default and still have the Set default search engine screen screen via brave://welcome (onboarding) are working as expected.

### PL locale

`Case #1` - https://github.com/brave/brave-browser/issues/23908

<details>
<summary>brave://welcome</summary>

Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/23908#issue-1296549984 and ensured that the `Set default search engine screen` was not removed from `brave://welcome` as per the following:

![image](https://user-images.githubusercontent.com/34715963/181761220-eac682bf-fd99-4f20-bb53-10bf36023025.png)



</details>

 `Case #2` - https://github.com/brave/brave-browser/issues/23814

<details>
<summary>Clean Profile</summary>

* ensured that `Google` was selected as the default for both Normal/Private windows via `brave://settings/search`
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Private` windows
* ensured that `Google` was selected as the default via `brave://settings/searchEngines`

![image](https://user-images.githubusercontent.com/34715963/181761337-b6f3821a-ef94-4269-b340-72d64cd38449.png)
![image](https://user-images.githubusercontent.com/34715963/181761384-76f9d950-8f43-4c30-a619-dbb56e729f7a.png)
![image](https://user-images.githubusercontent.com/34715963/181761439-fd2a39dd-0e8a-42cb-bd35-7c93e8303fe6.png)

</details>

<details>
<summary>Updated Profile (Google/Google)</summary>

* installed `1.41.x`
* ensured that `Google` was the default SE selected under `brave://settings/search`
* updated to `1.42.x` and ensured that `Google` is still the default SE in both Normal and Private window SE
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Private` windows

![image](https://user-images.githubusercontent.com/34715963/181764663-7a478c41-8c0e-4200-b8fe-9b3f69cc2682.png)
![image](https://user-images.githubusercontent.com/34715963/181764684-a66ea83d-6fb0-440c-8794-4f089ff2bcde.png)
![image](https://user-images.githubusercontent.com/34715963/181764714-8fd97aa8-2c90-435a-964f-a434dca0a049.png)


</details>

<details>
<summary>Updated Profile (Qwant/Bing)</summary>

* installed `1.41.x`
* ensured that `Qwant` was the default SE selected under `brave://settings/search` 
* updated to `1.42.x` and ensured that previously selected SE is still the default for both Normal and Private windows
  * ensured that it wasn't replaced by `Brave`
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Private` windows

1.41.x
![image](https://user-images.githubusercontent.com/34715963/181765383-d56659ca-6b6b-47ca-b103-3848d6f55a88.png)

1.42.x
![image](https://user-images.githubusercontent.com/34715963/181765708-4bc70442-2852-4027-97e7-e633da404a9c.png)
![image](https://user-images.githubusercontent.com/34715963/181765751-db68bf0d-92ba-4728-8419-716880b0e3dd.png)
![image](https://user-images.githubusercontent.com/34715963/181765785-704ea180-83b8-4d93-8c7d-ebe76b1849ee.png)


</details>
