### ISSUE TITLE
Copy function not working on full wallet view

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#23810]
## Description 

See video attached

https://user-images.githubusercontent.com/12224304/176771774-163edf0a-9eb9-415f-8c41-1d9399d66c88.mov

## Steps to Reproduce

   1. 
   2. 
   3. 

## Brave version (brave://version info)

[Version 1.42.43 Chromium: 103.0.5060.66 (Official Build) nightly 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by muliswilliam** [comment]
@HEagle18 This is fixed in this PR: https://github.com/brave/brave-core/pull/13986
