### ISSUE TITLE
Leave network selector state as undefined on 'add custom asset' popup

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#23820]
## Description 

Right now the 'add custom asset' page shows up solana first. We want to make the user select a network and only then will the 'add' button be enabled. 

## Steps to Reproduce

   1. 
   2. 
   3. 

## Actual result:

<img width="660" alt="Screenshot 2022-06-30 at 22 33 22" src="https://user-images.githubusercontent.com/12224304/176887374-8591fe33-a0e3-4656-9f4b-b265e8c7df1d.png">

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.44.95 Chromium: 106.0.5249.40 (Official Build) (64-bit) 
-- | --
Revision | `fab1d91915d2722d6339aaa7f4e9ce44f1e9b103-refs/branch-heads/5249@{#442}`
OS | Linux

- Verified steps from [brave/brave-core#14471](https://github.com/brave/brave-core/pull/14471)
- Verified Solana network is not selected by default on Add custom asset view
- Verified Add button is only enabled when all the required fields are added

https://user-images.githubusercontent.com/17010094/191587478-50584498-f33e-4984-aaed-1d6adc3295fa.mp4


------------------------
Verification passed on

Brave | 1.44.95 Chromium: 106.0.5249.40 (Official Build) (64-bit) 
-- | --
Revision | `fab1d91915d2722d6339aaa7f4e9ce44f1e9b103-refs/branch-heads/5249@{#442}`
OS | Windows 11 Version 21H2 (Build 22000.978)

- Verified steps from [brave/brave-core#14471](https://github.com/brave/brave-core/pull/14471)
- Verified Solana network is not selected by default on Add custom asset view
- Verified Add button is only enabled when all the required fields are added

https://user-images.githubusercontent.com/17010094/191586864-1632d52e-49b4-4942-b70a-3c2f95d663b1.mp4


------------------------
Verification passed on

Brave | 1.44.95 Chromium: 106.0.5249.40 (Official Build) (arm64)
-- | --
Revision | `fab1d91915d2722d6339aaa7f4e9ce44f1e9b103-refs/branch-heads/5249@{#442}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [brave/brave-core#14471](https://github.com/brave/brave-core/pull/14471)
- Verified Solana network is not selected by default on Add custom asset view
- Verified Add button is only enabled when all the required fields are added

https://user-images.githubusercontent.com/17010094/191584529-079778d5-220d-4edd-8e20-57e821524465.mov
