### ISSUE TITLE
Incorrect block explorer is used until transaction is confirmed

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23825]
## Description 

Incorrect block explorer is used until transaction is confirmed

## Steps to Reproduce

   1. Clean install 1.41.86 build
   2. Create a transaction on localhost
   3. Switch network to Mainnet/Ropsten
   4. Initiate a transaction on that network 
   5. Go to transaction details and click on `...` button and select `View on block explorer`
   6. Loads `localhost;//` URL rather than the actual network selected
   7. Wait for transaction confirmation, then select `View on block explorer`, loads the correct URL

## Actual result:

https://user-images.githubusercontent.com/17010094/176910728-b7ed7927-3bfb-492e-bc1f-4bf63fd267f1.mp4

## Expected result:
Load correct block explorer from UI

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.41.86 Chromium: 103.0.5060.66 (Official Build) beta (64-bit) 
-- | --
Revision | `20b1569438a85e631d15e83eb355e3e326e5da6f-refs/branch-heads/5060@{#1066}`
OS | Windows 11 Version 21H2 (Build 22000.739)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Not checked

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel

**Comment by josheleonard** [comment]
Closing as not-reproducible on latest master branch
