### ISSUE TITLE
Add BAT as a preloaded asset on Solana network 

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#23823]
## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by onyb** [comment]
Published `Wallet-Data-Files-Updater@1.0.16` via https://ci.brave.com/job/brave-core-ext-wallet-data-files-update-publish/25 job.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.43.79 Chromium: 104.0.5112.102 (Official Build) beta (64-bit)  
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | Linux

- Verified `Basic Attention Token (Portal)` token is listed as a visible asset when searched
- Verified `Basic Attention Token (Portal)` token is available under send/swap for Solana Mainnet Beta 

https://user-images.githubusercontent.com/17010094/186165634-8a4b7e97-c2e3-4b7b-b730-318666d5e514.mp4



------------------------
Verification passed on

Brave | 1.43.79 Chromium: 104.0.5112.102 (Official Build) beta (64-bit)  
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | Windows 11 Version 21H2 (Build 22000.795)

- Verified `Basic Attention Token (Portal)` token is listed as a visible asset when searched
- Verified `Basic Attention Token (Portal)` token is available under send/swap for Solana Mainnet Beta 

https://user-images.githubusercontent.com/17010094/186165655-1184e105-8c8b-44c2-be1c-0a28e875dec1.mp4


------------------------
Verification passed on

Brave | 1.43.79 Chromium: 104.0.5112.102 (Official Build) beta (64-bit) 
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | macOS Version 12.4 (Build 21F79)

- Verified `Basic Attention Token (Portal)` token is listed as a visible asset when searched
- Verified `Basic Attention Token (Portal)` token is available under send/swap for Solana Mainnet Beta 

https://user-images.githubusercontent.com/17010094/186165978-447718ea-5307-406e-8cdf-fc77235c37c0.mov
