### ISSUE TITLE
`OnNotificationAdDismissed` in `ads_impl.cc` is not triggered on notification swipe

### ISSUE THREAD

**Issue by LorenzoMinto** [brave/brave-browser#23826]
## Description 

`OnNotificationAdDismissed` in `ads_impl.cc` is not triggered on notification dismissal

## Steps to Reproduce

   1. Recent master
   2. Fresh profile and opt in rewards
   3. Trigger notification on browser
   4. Dismiss notification
   5. No logs from `OnNotificationAdDismissed`

Same procedure but clicking on notification shows `OnNotificationAdDismissed` is triggered

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by tmancey** [comment]
Closing issue as when you swipe a notification it moves to the Notification Center where you can dismiss or wait for a timeout. Ads is working as expected when you click the X or wait 2 minutes for the ad to timeout
