### ISSUE TITLE
Update Optimism mainnet RPC URL to our proxy

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#23833]
Update our preloading optimism mainnet to use our proxy created in https://github.com/brave/devops/issues/7562.

**Comment by onyb** [comment]
For QA, it's enough to verify that balances under Optimism and Aurora networks are being displayed correctly.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.44.97 Chromium: 106.0.5249.40 (Official Build) (64-bit) 
-- | --
Revision | `4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}`
OS | Windows 11 Version 21H2 (Build 22000.978)


- Verified steps from [#23833 (comment)](https://github.com/brave/brave-browser/issues/23833#issuecomment-1206736890)
- Verified balance on Optimism shows correctly
- Verified network calls are proxied

![image](https://user-images.githubusercontent.com/17010094/191822245-4b18eabe-f587-440f-b2be-023fed8b2369.png)![image](https://user-images.githubusercontent.com/17010094/191826214-9c0ad500-36ed-41ca-9585-90bdef5278e8.png)

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.44.97 x64 build

- Verified steps from [#23833 (comment)](https://github.com/brave/brave-browser/issues/23833#issuecomment-1206736890)
- Verified balance on Optimism shows correctly
- Verified network calls are proxied
<img width=300 src=https://user-images.githubusercontent.com/17010094/191828324-dbb8844a-4698-4c03-9700-e0b4dfb8afc1.png>
