### ISSUE TITLE
IPFS should not work in incognito

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#23831]
At the moment IPFS sometimes can open ipfs pages in incognito.
For example when ipfs local node is started in normal profile, ipfs urls can be loaded in incognito window.
We need fix this and create descriptive error page when navigation fails.

**Comment by diracdeltas** [comment]
marking this as p2 because it seems very bad if IPFS can also open in Tor windows

**Comment by cypt4** [comment]
> What are the risks of IPFS in incognito? The IPFS daemon will still have a record of the viewed content after the incognito session is closed?

Here is disscussion:
https://github.com/brave/brave-browser/issues/13613#issuecomment-927175872

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.43.58 Chromium: 104.0.5112.81 (Official Build) beta (x86_64)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | macOS Version 11.6.8 (Build 20G730)

ipfs://bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi/

|   | local node | gateway  |
|---|---|---|
|  Private  | <img width="1312" alt="Screen Shot 2022-08-05 at 4 11 21 PM" src="https://user-images.githubusercontent.com/387249/183222549-0ba4847f-790f-4e20-8143-e76aca0be77a.png"> |  <img width="1312" alt="Screen Shot 2022-08-05 at 4 18 21 PM" src="https://user-images.githubusercontent.com/387249/183222768-a4ee8132-85fa-4766-87e3-a026ca9080d0.png"> |
|  Private w/Tor | <img width="1312" alt="Screen Shot 2022-08-05 at 4 11 54 PM" src="https://user-images.githubusercontent.com/387249/183222439-fac5ddd8-48bb-42f7-b2e8-f54100832558.png"> |  <img width="1312" alt="Screen Shot 2022-08-05 at 4 18 48 PM" src="https://user-images.githubusercontent.com/387249/183222779-7da37827-a3bf-4b90-a1bc-2c79e6d364a0.png"> |
|  Guest | <img width="1312" alt="Screen Shot 2022-08-05 at 4 12 13 PM" src="https://user-images.githubusercontent.com/387249/183222406-ead1700d-b769-4d2b-8fa4-d5dc660b4078.png"> |  <img width="1312" alt="Screen Shot 2022-08-05 at 4 18 58 PM" src="https://user-images.githubusercontent.com/387249/183222795-2ced03aa-a8ec-4fde-a500-6ac3a181817c.png"> |
|  regular |  <img width="1312" alt="Screen Shot 2022-08-05 at 4 01 00 PM" src="https://user-images.githubusercontent.com/387249/183222157-7f7e665a-3e44-4367-a2a8-2299cdfa862d.png"> |  <img width="1312" alt="Screen Shot 2022-08-05 at 4 10 09 PM" src="https://user-images.githubusercontent.com/387249/183222260-13ea26df-23e9-4a4c-bd8b-5447cff1da1c.png">
