### ISSUE TITLE
Android test failures due to playlist core

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#23848]
https://github.com/brave/brave-core/pull/13922 seems to have caused Android test failure.

Need to revert or disable the components for our CI .

cc. @samartnik @wknapik

**Comment by simonhong** [comment]
Oh, looks like https://github.com/brave/brave-core/pull/14034 fixed android failure.
Let's merge when CI gets all green!

**Comment by sangwoo108** [comment]
Thanks simon. You were faster than me. Linux somehow failed so I reran the bot.
