### ISSUE TITLE
Support using ledger hardware for Solana signTransaction, signAllTransactions provider APIs

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#23842]

**Comment by yrliou** [comment]
Split SignMessage to https://github.com/brave/brave-browser/issues/23959 as we are blocked by ledger hardware support.

**Comment by kjozwiak** [comment]
The above will require `1.42.65` or higher for `1.42.x` verification 👍

**Comment by Ayern12** [comment]
###All signs are passed by Me ... Understand.

Pada Kha, 14 Jul 2022, 11:53 Kamil Jozwiak ***@***.***>
menulis:

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.42.81 Chromium: 104.0.5112.69 (Official Build) (64-bit) 
-- | --
Revision | `7ce2902023c722af8564068e6b26e934b83fd774-refs/branch-heads/5112@{#1213}`
OS | Windows 11 Version 21H2 (Build 22000.795)

- Verified steps from [brave/brave-core#14099](https://github.com/brave/brave-core/pull/14099)
- Verified able to sign and submit transactions via Ledger
- Verified able to submit a Swap transaction via Ledger

Ledger Swap | Ledger Sign
-- | --
<video src=https://user-images.githubusercontent.com/17010094/182088961-23d9c108-75da-45a9-bba4-f9dc53e23edf.mp4></video> | <video src=https://user-images.githubusercontent.com/17010094/182132171-9dd09c3c-6a3c-41ac-938c-8852f9076332.mp4></video>
