### ISSUE TITLE
(Feature Request) An option in Brave Shields to prevent Tracking via Query string parameters

### ISSUE THREAD

**Issue by raynell5** [brave/brave-browser#23852]
## Description 
I feel like Brave Shields needs an option to prevent websites from tracking the user using [Query string parameters](https://en.wikipedia.org/wiki/Query_string).
Today a lot of websites make use of query string parameters to track their users, instead of HTTP cookies.
Recently Firefox has also introduced this feature, see: https://thenextweb.com/news/firefox-continues-fight-for-privacy-by-automatically-stripping-url-trackers
I think it would make users feel more safe while browsing online, knowing that the website is unable to use query string parameters to track them and their online friends with who they share their URLs with.

It would really be nice to see Brave introduce this feature as well, since Privacy is one thing that the Web Browser is focusing on, besides Speed, Better Ads and Beyond.

I have got two popular websites in mind that make use of query string parameters to track you, those are Google and Amazon.

For example, if I want to share my search query on Google with someone, I don't want to send them that nasty long URL full of query parameters that do who knows what... Since https://www.google.com/search?q=XXX is enough.

The same goes for Amazon, maybe a product I find on there could interest someone I know. It wouldn't be nice sending them an URL full of query string parameters that do who knows what, once again...

That's about it! I hope that the Brave Developers can look into this and realize it as soon as possible.

**Comment by diracdeltas** [comment]
we already do this to some extent; cc @fmarier

**Comment by fmarier** [comment]
Yes, we released our query string filter in Brave 1.1 (December 2019): https://github.com/brave/brave-browser/issues/4239

See the [documentation for this feature](https://github.com/brave/brave-browser/wiki/Query-String-Filter) or the [announcement blog post](https://brave.com/privacy-updates/5-grab-bag/).

**Comment by fmarier** [comment]
A related feature, though not one that is privacy-related, is to provide the ability to copy clean URLs when sharing them with others: https://github.com/brave/brave-browser/issues/23315
