### ISSUE TITLE
Cannot Click on 'Add Site' Component

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#23855]
## Steps to Reproduce

   1. Select _Add Site_ from the favorites area of the New Tab Page
   2. Reduce size of browser window
 
## Actual result:

User cannot use their mouse to interact with the "Add Site" component. On a sufficiently small window, the component is rendered behind other elements on the new tab page.

## Expected result:

Component should act more like a modal, displayed above all other elements, and able to be clicked.

## Reproduces how often: 

Always

## Brave version (brave://version info)

1.40.109

**Comment by simonhong** [comment]
I think this is fixed on nightly and uplift PR is ready for beta - https://github.com/brave/brave-core/pull/14002

**Comment by AishickChowdhuryTurja** [comment]
Text cursor is not showing while adding sites in "Add Site". Please tell us what to do.

**Comment by Munir-Hassan** [comment]
Also you cannot click on the fields or the close or save buttons. Anywhere you click the modal gets closed. But you do can write on the input fields and press tab to hit enter on close and save buttons.

**Comment by jonathansampson** [comment]
@AishickChowdhuryTurja and @Munir-Hassan, this is confirmed to have been resolved in preview builds, and will soon land in the release/stable builds. Thank you for helping us keep an eye on quality :)
