### ISSUE TITLE
Low resolution background on New tab page

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#23859]
## Description 

When opening a new tab page, there is a small resolution background, we should remove it from our rotation

## Steps to Reproduce

   1. Open new tab
   2. See this particular image attached
  

## Actual result:

![image 12](https://user-images.githubusercontent.com/15734630/177182113-187a0791-9ead-4771-805b-444b8d98c035.jpg)

## Expected result:
Removal of this image

## Test

1. Lanuch Brave and load brave://components
2. Check ntp background component is latest  `NTP Background Images - Version: 1.0.6`
3. Check NTP doesn't display above image

**Comment by simonhong** [comment]
Updated dev-goupdater first for testing and waiting till it's deployed.
After testing with `--use-dev-goupdater-url`, I'll ntp-background-component from update prod-goupdater.

**Comment by simonhong** [comment]
Set `OS/Android` also as ntp background component is shared on desktop and android.

**Comment by simonhong** [comment]
Pushed ntp-background-components to prod goupdater.
and Set `1.41.x - Release` as all channels gets this component update.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.41.94 x64 build
- Verified steps from issue description
- Verified `NTP Background Images - Version: 1.0.6` via `brave://components`
- Verified the low resolution image doesn't show up loading new tab pages

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/177751684-1f9a9167-f628-42bf-9255-654fc0dbae2b.mp4> | <video src=https://user-images.githubusercontent.com/17010094/177753700-28108065-6d09-436e-86be-f7f17b2344b0.mp4>
