### ISSUE TITLE
Enable playlist core for Android

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#23850]
This is sub task of https://github.com/brave/brave-browser/issues/23621

---

For now, the core is disabled on Android (from https://github.com/brave/brave-core/pull/14034) because it caused unexpected test failures. During the fix, we found that `deps` to playlist/buildflag was missing but It's not likely to be the cause of test failures.

---

For now, `./src/build/install-build-deps-android.sh` works only for x86 arch

**Comment by chris122380** [comment]
Still not available on Brave stable 😢
