### ISSUE TITLE
[Follow up #23652] Desktop site is not enabled during upgrade if Desktop Mode was set to enable

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23871]
## Description 
As per test plan in https://github.com/brave/brave-browser/issues/23652#issuecomment-1169108408, Desktop Site should be enabled regardless of its state post upgrade as long as Desktop Mode was set to ON before upgrade. This is currently not working as intended

## Steps to reproduce 

   1. Install 1.41.65 nightly build which has duplicate desktop entries under site settings
   2. Set Desktop Mode to ON and leave Desktop Site to OFF (default)
   3. Upgrade to 1.42.52
   4. Desktop Mode is removed as expected, but Desktop Site remains OFF when it should have been set to ON

## Actual result 

https://user-images.githubusercontent.com/17010094/177272509-f634ad9f-c426-4bce-b7d6-de8b4f7b18f8.mp4

## Expected result
Should set Desktop Site to enabled as per test plan

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 12
   
## Brave version
1.42.52

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @samartnik

**Comment by kjozwiak** [comment]
The above will require `1.41.94` or higher for `1.41.x` verification 👍

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/23652#issuecomment-1177335998
