### ISSUE TITLE
Android wallet code clearup and transaction parser

### ISSUE THREAD

**Issue by wchen342** [brave/brave-browser#23875]
Add a transaction parser similar to the one used for desktop (`components/brave_wallet_ui/common/hooks/transaction-parser.ts`). Also clean up some of the backend functions.

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12.1 running 1.42.96 x64 build
- Verified able to send/swap ETH/ERC20 tokens
- Verified able to send/swap token on other networks
- Verified able to connect to Dapps
- Verified able to view transactions details under accounts (confirmed/rejected)
- Verified able to add custom tokens and list them in portfolio
- Verified able to add tokens via Add token screen
- Verified `Show web3` notifications works as expected
- Encountered [#24721](https://github.com/brave/brave-browser/issues/24721)
--------------
Verification passed on Samsung Tab A with Android 10 running 1.42.96 x64 build
- Verified able to send/swap ETH/ERC20 tokens
- Verified able to send/swap token on other networks
- Verified able to connect to Dapps
- Verified able to view transactions details under accounts (confirmed/rejected)
- Verified able to add custom tokens and list them in portfolio
- Verified able to add tokens via Add token screen
- Verified `Show web3` notifications works as expected
- Encountered [#24721](https://github.com/brave/brave-browser/issues/24721)
