### ISSUE TITLE
Browser process keeps running even after browser close, when 'Hangouts` extension is enabled.

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#2387]
## Description 
Browser process keeps running even after browser close, when 'Hangouts` extension is enabled.

## Steps to Reproduce

   1. Install `Hangouts` extension alone
   2. Restart the browser
 

## Actual result:
Unable to restart the browser due to extension crash. 

## Expected result:
Once browser is closed, process should get exit and allow user to restart the browser

## Reproduces how often: 
Always

## Brave version (brave://version info)

Brave | 0.57.17 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional Information
@bbondy @kjozwiak

**Comment by GeetaSarvadnya** [comment]
#1380

**Comment by srirambv** [comment]
There was no extension crash or ghost browser process running when i checked this on master. Test was done on Linux

**Comment by srirambv** [comment]
Even though the background app option is disabled in settings, the process continues to run in background. If i uncheck that then it automatically exits
![image](https://user-images.githubusercontent.com/17010094/49602550-bcaed400-f9ae-11e8-9d51-d49425950be1.png)
This is the same behaviour on Chrome as well
![image](https://user-images.githubusercontent.com/17010094/49602555-bf112e00-f9ae-11e8-8eca-ec64028d401a.png)

**Comment by GeetaSarvadnya** [comment]
I was trying to launch and Relaunch browser through Gitbash. When I was closing the browser, I was not terminating the processes which were initiated by Gitbash. Hence Relaunch was not happening through Gitbash. Gitbash has lock over the browser process and Hnagouts. Re-launch brave through shortcut doesn't have any issues. Hence i am going to close the issue.
