### ISSUE TITLE
Add opton to hide Brave VPN from the hamburger menu

### ISSUE THREAD

**Issue by UjCbFwtBayFM** [brave/brave-browser#23880]
## Description 
There is no option to hide "Brave VPN" or "Brave Rewards" or "Brave News" from the browser menu.

## Steps to reproduce 

   1. Open menu
   2. 
   3. 

## Issue reproduces how often 
always

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? unknown
- Can you reproduce this issue with the current Play Store Nightly version? unknown

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Tablet
   - Android version: 11
   
## Brave version
Brave 1.40.106

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by bsclifton** [comment]
cc: @anthonypkeane @timchilds

**Comment by anthonypkeane** [comment]
Fair point, we are actually going to work on cleaning up the menu shortly.

**Comment by UjCbFwtBayFM** [comment]
Any update about this clean-up?

**Comment by Codel1417** [comment]
Still waiting on this

**Comment by Agoutii** [comment]
> Fair point, we are actually going to work on cleaning up the menu shortly.

Mmm, very shortly. Still an issue, still no sign of being addressed.

Hard to see this without just assuming it's a deliberate scummy tactic to push people towards the badly overpriced partner VPN. The whole reason people started switching fr Chrome/Edge to Brave was a belief that it was a browser that put users ahead of profits rather than being predatory.

**Comment by Codel1417** [comment]
>The whole reason people started switching fr Chrome/Edge to Brave was a belief that it was a browser that put users ahead of profits rather than being predatory.

Sadly that ship sailed years ago.

**Comment by Agoutii** [comment]
Yup, time to switch to Firefox. We all really should of known better.

**Comment by LemonDoo** [comment]
So wtf happened with this? Can we get an update on if this can be shipped? The hamburger menu now has like 4 spammy ad features on top of everything else. What happened to the "cleanup"?

**Comment by bsclifton** [comment]
Hi folks

This is a great issue - thanks for the comments

We have captured https://github.com/brave/brave-browser/issues/41801 which allows for showing/hiding all of the menu items. Please subscribe to that issue for updates. I'll ask for an update there
