### ISSUE TITLE
Users getting errors on Opensea

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#23889]
## Description 

See https://bravesoftware.slack.com/archives/C02S9LFEXU4/p1655731623724999
https://community.brave.com/t/brave-wallet-on-opensea-not-allowing-sales/406373

Users are getting the error `Invalid Order Signature `. Happening on 1.40.107 and 1.42.43. 2 users and an employee mentioned it.

## Steps to Reproduce

   1. 
   2. 
   3. 

## Brave version (brave://version info)

1.40 and 1.42

## Version/Channel Information:

- Can you reproduce this issue with the current release? y
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? y

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

Screenshots in the community ticket

**Comment by mtakacs** [comment]
Confirming I'm also seeing this trying to interact with (create a SELL listing) on OpenSeas, getting the `Invalid Order Signature`

Version: ```1.41.96 Chromium: 103.0.5060.114 (Official Build) (arm64)```

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.42.81 Chromium: 104.0.5112.69 (Official Build) (64-bit) 
-- | --
Revision | `7ce2902023c722af8564068e6b26e934b83fd774-refs/branch-heads/5112@{#1213}`
OS | Windows 11 Version 21H2 (Build 22000.795)

- Verified steps from [brave/brave-core#14239](https://github.com/brave/brave-core/pull/14239)
- Verified able to submit listings without errors

https://user-images.githubusercontent.com/17010094/182139936-c4b74153-1e8a-49b8-a953-75f3ffadf555.mp4
