### ISSUE TITLE
Portfolio Price History Continuously Loads

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#23883]
## Description 
The Portfolio Price History continuously loads for a new wallet without a balance, it should flatline.
Possibly regressed in https://github.com/brave/brave-browser/issues/22815

https://user-images.githubusercontent.com/40611140/177377631-f12be324-ddad-4cf9-ae65-13e6a5d27ad5.mov

**Comment by kjozwiak** [comment]
The above will require `1.42.63` or higher for `1.41.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.42.80 Chromium: 104.0.5112.57 (Official Build) (64-bit) 
-- | --
Revision | `212fd173a0da1e0a024f328295bb56a2529190bb-refs/branch-heads/5112@{#1042}`
OS | Linux

- Verified steps from issue description
- Verified price history is loaded on a clean profile
- Verified price history shows on a restored wallet with balance


Clean Profile | Restore Profile
-- | --
<video src=https://user-images.githubusercontent.com/110182089/181546043-1b772c3c-c2c6-4ca1-8bda-6bf8f780e515.mp4> | <video src=https://user-images.githubusercontent.com/110182089/181546069-bf83d109-f122-427f-bfdd-fadea918174e.mp4> 
------------------------
Verification passed on

Brave | 1.42.80 Chromium: 104.0.5112.57 (Official Build) (64-bit) 
-- | --
Revision | `212fd173a0da1e0a024f328295bb56a2529190bb-refs/branch-heads/5112@{#1042}`
OS | Windows 11 Version 21H2 (Build 22000.795)

- Verified steps from issue description
- Verified price history is loaded on a clean profile
- Verified price history shows on a restored wallet with balance


Clean Profile | Restore Profile
-- | --
<video src=https://user-images.githubusercontent.com/17010094/181533600-1ea7b618-1b9d-4961-89f7-b622eda50f09.mp4 />  | <video src=https://user-images.githubusercontent.com/17010094/181533796-aa792384-844f-4884-96dc-af85059e36a5.mp4 /> 
------------------------
Verification passed on

Brave | 1.42.80 Chromium: 104.0.5112.57 (Official Build) (arm64) 
-- | --
Revision | `212fd173a0da1e0a024f328295bb56a2529190bb-refs/branch-heads/5112@{#1042}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from issue description
- Verified price history is loaded on a clean profile
- Verified price history shows on a restored wallet with balance


Clean Profile | Restore Profile
-- | --
<video src=https://user-images.githubusercontent.com/17010094/181524858-4de8ce77-5a81-49ba-86c2-11b93b3e2157.mov /> | <video src=https://user-images.githubusercontent.com/17010094/181524882-749c43d8-d0a1-4b53-8262-2ffa4eaaa370.mov />
