### ISSUE TITLE
ads not blocked on megaup

### ISSUE THREAD

**Issue by dylantrevor87** [brave/brave-browser#23896]
## Description 

some ads are not blocked on this site (or sometimes ad blocker is detected):
https://megaup.net/3878h/sc21950-FON2GKv110.rar

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
cc: @ryanbr

**Comment by ryanbr** [comment]
Give it 24/48hrs @dylantrevor87
