### ISSUE TITLE
Add VPN P3A usage questions

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#23892]
## Description 

Adding three P3A questions for VPN.

As a Brave VPN user, when was the last time I enabled the Brave VPN?
`Brave.VPN.LastUsageTime`

1) 0 - 6 days ago
2) 7 - 13 days ago
3) 14 - 20 days ago
4) 21 - 27 days ago
5) 28 - 59 days ago
6) 60 days ago or more

As Brave VPN user, how many different days did I enable the Brave VPN in the last 30 days?	
`Brave.VPN.DaysInMonthUsed`

0) 0 days
1) 1 day
2) 2 days
3) 3 to 5 days
4) 5 to 10 days
5) 10 to 15 days
6) 15 to 20 days
7) More than 20 days

As a first time user of the Brave VPN this week, did I enable it again the following day?
`Brave.VPN.NewUserReturning`

0) I have never enabled the Brave VPN
1) I have enabled the Brave VPN, but I'm not a first time Brave VPN user this week
2) I'm a first time Brave VPN user this week but, no, I did not enable the Brave VPN the rest of the week
3) I'm a first time Brave VPN user this week and, yes, I did enable it again the following day
4) I'm a first time Brave VPN user this week and, yes, I enabled it again this week but not the following day

## Miscellaneous Information:
Will raise PR soon.

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```
Brave | 1.44.70 Chromium: 105.0.5195.68 (Official Build) beta (64-bit)
-- | --
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | Windows 10 Version 21H2 (Build 19044.1889)

```

**Comment by GeetaSarvadnya** [comment]
@DJAndries Few questions related to the test plan https://github.com/brave/brave-core/pull/14168. Could you please review them?

1. The test plan says `turn on VPN` in steps 2,6 and 10. Once the VPN is enabled user can access the VPN even if they advance the system clock and VPN doesn't gets disconnected once the browser is closed and system clock is set ahead, I am not sure why we need to turn on the VPN in steps 2,6 and 10. The browser state (Open/close) doesn't determine the VPN connection.

2. The metris `Brave.VPN.LastUsageTime` response value are not working as expected. Steps which I followed are as below:

1. Clean profile 1.44.x
2. Enable Brave VPN
3. Open brave://local-state file and ensured `Brave.VPN.LastUsageTime` metrics response value is `1` as expected
4. Set the system clock ahead by one week or more than one week, the metrics reponse value is `1` instead of `2`

**Comment by DJAndries** [comment]
@GeetaSarvadnya These are good points. I updated the Windows test plan, P3A wiki and original issue to address your concerns. Thanks

**Comment by GeetaSarvadnya** [comment]
@DJAndries Thanks for the updated test plan. Still the test plan needs to be updated as when user reconnects the VPN on the future date the server throws the error and unbale to connect the VPN (Logged https://github.com/brave/brave-browser/issues/25244#issuecomment-1241029752) In this case we won't get the expected result which you mentioned in 10

**Comment by Uni-verse** [comment]
In progress for Android ARM using the following build(s):

Brave	1.44.97 Chromium: 106.0.5249.55 (Official Build) (64-bit) 
Revision	4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}
OS	Android 12; Build/SP1A.210812.016

Test Scenarios based on https://github.com/brave/brave-browser/issues/23892#issuecomment-1235298332

`Brave.VPN.LastUsageTime`

1 = 0 - 6 days ago
2 = 7 - 13 days ago
3 = 14 - 20 days ago
4 = 21 - 27 days ago
5 = 28 - 59 days ago
6 = 60 days ago or more

0 - 6 days ago | 7 - 13 days ago | 14 - 20 days ago | 21 - 27 days ago | 28 - 59 days ago | 60 days ago or more
-|-|-|-|-|-
![screenshot-1663881538490](https://user-images.githubusercontent.com/17885425/191854795-c343a30f-3147-49a0-ba65-6b4ea2520f46.png) | ![screenshot-1663881702465](https://user-images.githubusercontent.com/17885425/191854798-1c4b7caa-b3f5-410d-b92e-001b9272f909.png) | ![screenshot-1663881799188](https://user-images.githubusercontent.com/17885425/191854800-c2dd5fcc-4e17-4e5b-b9c5-72e19ccddad9.png) | ![screenshot-1663881895628](https://user-images.githubusercontent.com/17885425/191854803-84399ca8-2a66-4f77-9ec9-a6006c2b2f26.png) | ![screenshot-1663881965096](https://user-images.githubusercontent.com/17885425/191854804-7fc8053a-d29e-4ea6-9ed2-57df234eb71c.png) | ![screenshot-1663882049972](https://user-images.githubusercontent.com/17885425/191854806-5263696c-2bdd-4066-8a2b-07d606017aa7.png)
