### ISSUE TITLE
Interacting with Solana Dapp without Solana Account should probably initiate account creation on the panel

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23898]
## Description 

Interacting with Solana Dapp with Solana Account should probably initiate account creation on the panel

## Steps to Reproduce

   1. Clean profile and create Wallet 
   2. Visit a Solana Dapp and try to connect
   3. No error shown on UI, but console throws error about `WalletConnectionError: An internal error has occurred`
 

## Actual result:

Solana Dapp detects provider but doesn't do anything since there is no solana account created

## Expected result:
Probably initiate Create Solana Account in Panel and continue to connect to Dapp

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.41.93 Chromium: 103.0.5060.114 (Official Build) (64-bit) 
-- | --
Revision | `a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes after 1.41.x is released
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @jamesmudgett @Douglashdaniel

**Comment by jamesmudgett** [comment]
Yes, for existing accounts. Though we may need to find a better solution as discussed in Slack to generate Solana account numbers on new wallet creation. Show/hide when needed.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.43.81 Chromium: 104.0.5112.102 (Official Build) (64-bit)
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | Linux

- Verified steps from issue description
- Verified interacting with Solana Dapp opens `brave://wallet/crypto/accounts/add-account/create/solana` in a new tab to create a Solana Account
- Verified able to go back to Solana Dapp and connect wallet without having to refresh the page
- Verified the above works when only Phantom wallet is detected on Dapp

https://user-images.githubusercontent.com/17010094/186487177-f8f1d7a6-67be-4f18-bedd-7e7b5e3f05ac.mp4


------------------------
Verification passed on

Brave | 1.43.81 Chromium: 104.0.5112.102 (Official Build) (64-bit)
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | Windows 11 Version 21H2 (Build 22000.795)

- Verified steps from issue description
- Verified interacting with Solana Dapp opens `brave://wallet/crypto/accounts/add-account/create/solana` in a new tab to create a Solana Account
- Verified able to go back to Solana Dapp and connect wallet without having to refresh the page
- Verified the above works when only Phantom wallet is detected on Dapp

https://user-images.githubusercontent.com/17010094/186486229-9ceba34a-0014-4001-ac58-67e32df553a7.mp4


------------------------
Verification passed on

Brave | 1.43.81 Chromium: 104.0.5112.102 (Official Build) (arm64)  
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from issue description
- Verified interacting with Solana Dapp opens `brave://wallet/crypto/accounts/add-account/create/solana` in a new tab to create a Solana Account
- Verified able to go back to Solana Dapp and connect wallet without having to refresh the page
- Verified the above works when only Phantom wallet is detected on Dapp

https://user-images.githubusercontent.com/17010094/186487499-d41c1117-e591-4463-9d06-932a0e474717.mov
