### ISSUE TITLE
Add updated assets on Ramp (06/06/22)

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#23897]
## Description 

Add these 5 assets to ramp.network options

BNB on BSC
MANA on ETH
MANA on MATIC
USDC on Solana
ETH on Optimism

**Comment by kjozwiak** [comment]
The above will require `1.41.97` or higher for `1.41.x` verification 👍

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.41.99 Chromium: 103.0.5060.134 (Official Build) (64-bit) </th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>8ec6fce403b3feb0869b0732eda8bd95011d333c-refs/branch-heads/5060@{#1262}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.708)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-core/pull/14065>brave/brave-core#14065</a></li>
         <li>Verified 5 new assets are added to purchase via Ramp.Network option</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/179973797-0c98e196-6a40-45a9-b3dd-776cc37ff35d.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/179973855-d55976e6-48f1-4e19-8c0b-5068204c3811.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/179974891-0b245a79-5b5f-41fa-babe-a4a89baaad7c.mov>
      </td>
   </tr>
</table>
