### ISSUE TITLE
Remove P3A protobuf reporting

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#23902]
## Description 

Reverting P3A protobuf submission is done via the PR https://github.com/brave/brave-core/pull/14015/ and which resolves the issue https://github.com/brave/brave-browser/issues/23754 and the same is verified in 1.41.x https://github.com/brave/brave-browser/issues/23754#issuecomment-1176443588 and ensured P3A and P2A work as it works in 1.40.x 

The actual fix for `Remove P3A protobuf reporting` is merged in 1.42.x and 1.43.x  via the PR https://github.com/brave/brave-core/pull/14017 hence created this issue to address `Remove P3A protobuf reporting` in 1.42.x

 ## Test Plan:

Run browser under a network proxy for traffic inspection
- With a fresh profile, wait 10-15 minutes for P3A reports to be sent.
- Confirm messages all go the p3a-json.brave.com and are formatted as readable json. There should be no traffic to p3a.brave.com.
- P2A messages are unaffected and may go to p2a.brave.com, p2a-json.brave.com or both, depending on the version. This change is only about `Brave.P3A.*` reports.

## Miscellaneous Information:

Discussed with @kjozwiak and created the issue.

cc: @brave/legacy_qa @rillian @mattmcalister @rebron

**Comment by rillian** [comment]
> I need clarification on p2a metrics. p2a metrics are recorded only when rewards is enabled and view an ad. It's behaving the same in both 1.41 and 1.42. But earlier it was not like that, we used to get the p2a metrics after 15 or 20 mins of browser load (p2a metrics records verified in 1.36 #15967) Is this a recent change?

@GeetaSarvadnya are you saying in 1.36 you see P2A metrics in the first ~10 minutes without having to enable rewards and browse long enough to trigger an ad?

I'm not aware of anything changing the in P2A scheduling, but the ad code which reports opportunities and impressions has changed, particularly with Brave News, so maybe that's the origin of the change?

@tmancey you refactored the p2a reporting recently. Is this an expected change between 1.36 and 1.41?

**Comment by tmancey** [comment]
@rillian p2a metrics have not changed, just moved in the code. However, users can join Brave News ads without joining rewards and P2A are sent for ad impressions for those ads. So it could be that Brave News has changed and the ads are viewed much sooner.

**Comment by rillian** [comment]
At least it sounds like an improvement instead of a regression.

**Comment by GeetaSarvadnya** [comment]
@tmancey Pretty sure when we verified the P2A records in https://github.com/brave/brave-browser/issues/15967, we haven't enabled rewards.

**Comment by tmancey** [comment]
@GeetaSarvadnya nothing has changed with regards to p2a in ads lib for quite a while. More than happy to jump on screen-share to go over your results. Thanks

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.42.85 x64 build
- Verified traffic is not sent to old endpoint `p3a.brave.com`
- Verified that all the P3A metrics are sent in JSON format to `p3a-json.brave.com`
- Verified around 17 metric that are sent for P3A is available in `brave://local-state` 
- Verified no P2A metrics are sent (known issue)

![image](https://user-images.githubusercontent.com/17010094/182338503-465c8f48-6584-43a4-acbe-774971839f6d.png) | ![image](https://user-images.githubusercontent.com/17010094/182338023-e941bd3e-7a8d-4528-9c27-e096fec540ca.png)
-- | --
