### ISSUE TITLE
Unable to find the cast media option on brave browser in flags

### ISSUE THREAD

**Issue by Dashiznitzn** [brave/brave-browser#23900]
## Description
cant  locate- media control option on flags

## Steps to reproduce 

   1. Searched for keyword media
   2. Does not exist
![Screenshot_20220706-180030](https://user-images.githubusercontent.com/108825109/177603163-11f50214-b48b-40e7-b7c1-d761d96a9ea4.png)

   3. I want to be able to cast any video to Chromecast but its not showing on flags

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by ShalokShalom** [comment]
I dont think, there are any flags around this. Maybe its simply not supported yet?

**Comment by bsclifton** [comment]
I'm looking at this and I don't think this is possible on Android (in Brave or any Chromium browser) to stream individual tans

Of course, you can Chromecast your phone under Settings > Connected devices > Connection preferences

**Comment by bsclifton** [comment]
Closing as `wontfix` as issue has been open for ~2 years with no movement. Android does not have an in-browser Chromecast. Desktop does - you can find that at brave://settings/extensions under the setting `Media Router`
