### ISSUE TITLE
HTTPS upgrades prevent wifi captive portals from working

### ISSUE THREAD

**Issue by Plasma** [brave/brave-browser#2390]
## Description 

In the middle of travel, and using Brave at a few hotels and airports.

Normally when connecting to these wifi networks, they need you to open a web browser and try and navigate to a website so they can intercept and redirect to the captive portal that asks you to provide a use code or login to use the wifi.

In general this is already pretty broken with Chrome, because if you visit any https site, you either get internet working, or certificate errors, because its trying to redirect via DNS hijacking.

My normal workaround was to type http://yahoo.com (the only http site I am aware of lately) to get to the captive portal page, but brave seems to detect it supports https:// and will upgrade it, then I can't access the captive portal.

## Steps to Reproduce

   1. Connect to a public wifi with a captive portal (eg hotel, airport, starbucks?)
   2. Try and visit say http://yahoo.com to try and get the captive portal to show

## Actual result:

You will get DNS hijacked and get a certificate error and unable to continue

## Expected result:

Ideally the captive portal was visible (or Brave figured out one was there and showed it when first opening the browser -- but chrome doesn't do this either).

## Brave version (brave://version info)

0.56.15 Chromium: 70.0.3538.110 (Official Build) (64-bit)

**Comment by Liunkae** [comment]
You should try http://neverssl.com/, which is designed exactly for this purpose.

**Comment by tomlowenthal** [comment]
This isn't a bug. The purpose of HTTPS-Everywhere (and HSTS, and pinning, and…) is to prevent your connection from being hijacked. As @Liunkae says: use an HTTP page to open captive portals.
