### ISSUE TITLE
[Android] New Onboarding: move search engine election modal to after onboarding has been completed

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#23907]
**Summary**
We have a gap in the new onboarding. Except for CA, DE, FR, GB and US we show the search onboarding when a user clicks on the search bar. This is interfering with the new onboarding steps for all countries outside of CA, DE, FR, GB and US.

https://user-images.githubusercontent.com/28269287/177650605-9ee478d0-2396-472b-b7cc-fabe2801edd9.mp4

**Comment by anthonypkeane** [comment]
**Solution**

-> Please add the Search Engine selection screen after onboarding.

During onboarding, the user can either: 

a) enter a URL (i.e. www.cat.com) or 
b) search for a URL (i.e. Cat). 

For a) after onboarding, on the next URL tap, present the screen where the user can select their search engine.  
For b) use the country default search engine during onboarding but after onboarding, on the next URL tap, present the screen where the user can select their search engine.

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.41.96 x64 build
- Verified steps from [brave/brave-core#14107](https://github.com/brave/brave-core/pull/14107)
- Verified after initial onboarding (default/opt-in), omnibox/URL bar is set to focus
- Verified when omnibox/URL bar is set to focus, `Type a website name or URL` onboarding modal is shown 
- Verified the modal can be dismissed either via tapping inside the URL bar or outside anywhere on the NTP
- Verified performing a search after dismissing the modal doesn't bring up the Search onboarding modal
- Verified on a clean install selecting the empty URL after clearing the `Type a website name or URL` onboarding message doesn't show the Search engine onboarding
- Verified selecting URL bar a second time (without having to search the first time) triggers the Search onboarding modal 


<video src=https://user-images.githubusercontent.com/17010094/178512511-30094c92-5fe0-4dfe-8a50-933b3c585007.mp4> | <video src=https://user-images.githubusercontent.com/17010094/178512454-979b3e8b-1450-4501-937c-2d3771e0b9ff.mp4>
-- | --
