### ISSUE TITLE
brave://settings/braveHelpTips is blank 

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#23910]
## Description 

brave://settings/braveHelpTips is blank on first load. On refresh, brave://settings/braveHelpTips content displays.

## Steps to Reproduce

   1. Go to brave://settings/braveHelpTips
   2. Notice that brave://settings/braveHelpTips is blank and doesn't. Refreshing or selecting other setting section and back shows the proper page.

## Actual result:

![Screenshot 2022-07-06 at 4 29 04 PM](https://user-images.githubusercontent.com/5951041/177659728-eca74cf5-88dc-4d76-9315-326232e2a119.png)

## Expected result:
![Screenshot 2022-07-06 at 4 32 31 PM](https://user-images.githubusercontent.com/5951041/177659790-936f50b6-d57f-493a-a3e8-9dd5ac3e2c39.png)

## Reproduces how often: 

Easily.

## Brave version (brave://version info)

Brave | 1.40.113 Chromium: 103.0.5060.114 (Official Build) (arm64)
-- | --
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | macOS Version 13.0 (Build 22A5286j)
JavaScript | V8 10.3.174.18
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36

## Version/Channel Information:

- Can you reproduce this issue with the current release? 1.40.113
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by simonhong** [comment]
We already have several filed issue for this :) https://github.com/brave/brave-browser/issues/23090 https://github.com/brave/brave-browser/issues/22736

**Comment by rebron** [comment]
close as dupe of https://github.com/brave/brave-browser/issues/22736
