### ISSUE TITLE
Add support for $removeparam filter syntax

### ISSUE THREAD

**Issue by UjCbFwtBayFM** [brave/brave-browser#23927]
## Description 
Several adblockers added the ability to remove URL parameters over the last few years, like uBlock Origin through the `$removeparam` filter. Allows to remove tracking/unnecessary URL parameters.
Brave support is currently [hardcoded to very select few parameters](https://github.com/brave/brave-core/blob/master/browser/net/brave_site_hacks_network_delegate_helper.cc#L29), thus making it impossible to use any list using this filter.

## Steps to Reproduce

   1. None

## Brave version (brave://version info)
<html>
<body>

Brave | 1.40.113 Chromium: 103.0.5060.114 (Official Build) (64-bit)
-- | --
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | Windows 10 Version 21H1 (Build 19043.1766)

</body>
</html>

**Comment by ryanbr** [comment]
We can close this, we already have a ticket for this.  https://github.com/brave/adblock-rust/issues/166  No eta, but we are aware of it. cc: @antonok-edm

**Comment by antonok-edm** [comment]
Reopening this, since support is incoming in `adblock-rust`. We'll use this issue to track the `brave-core` integration.

**Comment by kjozwiak** [comment]
The above requires `1.47.122` or higher for `1.47.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.47.123 Chromium: 108.0.5359.99 (Official Build) beta (x86_64)
-- | --
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | macOS Version 13.1 (Build 22C65)

### Steps:
1. saved HTML testcase as `index.html`
2. started server via `python3 -m http.server`
3. added filter rule of `localhost:8000^$document,removeparam=test` to `brave://settings/shields/filters`
4. clicked `Saved changes`
5. loaded `localhost:8000/index.html`
6. clicked on each of the 3 links

`index.html` | `brave://settings/shields/filters` | `?test2=false` | `(empty)` | `?test2=false`
---------|----------|---------|----------|---------
<img width="1173" alt="Screenshot 2022-12-11 at 11 38 14 AM" src="https://user-images.githubusercontent.com/387249/206925183-56689a53-4e81-4f10-a89e-385d3a000c32.png"> | <img width="1312" alt="Screenshot 2022-12-11 at 11 38 22 AM" src="https://user-images.githubusercontent.com/387249/206925186-40c1a239-08db-4abd-b8fb-00bbb2c239a3.png"> | <img width="1312" alt="Screenshot 2022-12-11 at 11 38 43 AM" src="https://user-images.githubusercontent.com/387249/206925187-e6db7323-2f46-4022-a145-4eab659c549a.png"> | <img width="1312" alt="Screenshot 2022-12-11 at 11 38 47 AM" src="https://user-images.githubusercontent.com/387249/206925190-3d286413-0141-46cb-b983-c2a14a927cd6.png"> | <img width="1312" alt="Screenshot 2022-12-11 at 11 38 52 AM" src="https://user-images.githubusercontent.com/387249/206925191-0559269c-b853-47e7-b6d7-e5945e73ad83.png">

**Comment by Uni-verse** [comment]
In progress on Samsung Galaxy S21 using version:

Brave	1.47.167 Chromium: 109.0.5414.80 (Official Build) (64-bit) 
Revision	0f69b168d36a06cace4365e9f029fa987afa5633-refs/branch-heads/5414@{#1178}
OS	Android 12; Build/SP1A.210812.016

**Comment by adripo** [comment]
> ||uni-verse.github.io^$removeparam=test

Hi @Uni-verse,

I came across the test you performed on `removeparam` in this PR. I recently tried using this feature on both desktop and mobile, but it didn’t work for me in either case.

Before opening a new issue, I wanted to check if you could re-test the feature and confirm whether it’s still working as expected on your end? Thank you for your time!
