### ISSUE TITLE
National Review won't load content unless ads are allowed

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#2392]
## Description 

Article/image content on nationalreview.com won't load unless ads are allowed. No workarounds found other than allowing ads/tracking.
Console:
![image](https://user-images.githubusercontent.com/3299098/49609371-221fa800-f950-11e8-9235-e3eafff314ba.png)

## Steps to Reproduce

   1. Visit nationalreview.com (I used this page to test https://www.nationalreview.com/photos/cartoons-of-the-day-december-6-2018/#slide-1)
   2. When article/image content doesn't load drop Shields or allow Ads/tracking
## Actual result:

"Cartoon of the day" page with default protections on:
![image](https://user-images.githubusercontent.com/3299098/49609386-36fc3b80-f950-11e8-966f-f63babadd195.png)

## Expected result:
Same page with ads/trackers allowed:
![image](https://user-images.githubusercontent.com/3299098/49609410-4e3b2900-f950-11e8-995b-ece29540b172.png)

## Reproduces how often: 

Easily/always

## Brave version (brave://version info)

Developer v0.59.2
Beta v0.57.8
Release v0.56.15 

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? Yes
- Is the issue reproducible on the latest version of Chrome? No

### Additional Information

Original report from Community:
https://community.brave.com/t/cartoons-of-the-day-december-6-2018-national-review/39021

**Comment by ryanbr** [comment]
`@@||nationalreview.com/wp-content/themes/national-review/client/build/js/ads.$script`

Should help

**Comment by ryanbr** [comment]
Fixed.
https://github.com/easylist/easylist/commit/29435bf6af394e72c7f2dee079710ffa72c07129
