### ISSUE TITLE
Show multichain (solana) accounts in account tab and account selector screen

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#23920]
## Description 
Show multi-chain (Solana) accounts in account tab and account selector screen

**Comment by Pavneet-Sing** [comment]
This has been implemented in https://github.com/brave/brave-core/pull/14090 PR.

**Comment by kjozwiak** [comment]
The above will require `1.42.69` or higher for `1.42.x` verification.

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/23648#issuecomment-1195568467
