### ISSUE TITLE
P2A metrics are not broadcasted [Android]

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#23922]
## Description 
P2A metrics are not being broadcasted on Android platform after enabling rewards and viewing ads.

version 1.41.94 (RC)

## Steps to reproduce 

   1. Clean install
   2. Connect to `Charles Proxy` and launch app
   3. Enable `rewards`
   4. Wait for `ads`
   5. Monitor Charles for P2A metrics (may have to monitor for 15-20mins to be sure)
   6. Check `brave://local-state`

## Actual result 
No metrics broadcasted

## Expected result
metrics should be broadcasted to `https://p2a.brave.com` & `https://p2a-json.brave.com`

## Issue reproduces how often 
Easily, follow STR

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? N/A
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone, Tablet - Samsung Galaxy Devices
   - Android version: 12
   
## Brave version
1.41.93/1.41.94

**Comment by Uni-verse** [comment]
@rillian

**Comment by GeetaSarvadnya** [comment]
@SergeyZhukovsky Please check the play store version. It looks like it's reproducible in GPS as well. 

>Can you reproduce this issue with the current Play Store version? N/A

Edit the above if issue is reproducible in GPS

**Comment by rillian** [comment]
@moritzhaller are P2A reports supposed to be sent from Android? I don't see anything in the code turning it off, but my personal instance with Brave Private Ads enabled doesn't show any P2A keys in brave://local-state either.

**Comment by rillian** [comment]
Aha. We don't [register the P2A metric names](https://github.com/brave/brave-core/blob/v1.43.13/browser/brave_profile_prefs.cc#L440-L442) on Android, and indeed https://github.com/brave/brave-core/pull/5949 is marked OS/Desktop only. So I think this was never supposed to work on Android. Sorry for the confusion.

**Comment by rillian** [comment]
I've removed the Android label from #22079. Moritz, please reopen if this isn't correct!
