### ISSUE TITLE
Wallet onboarding conversion P3A question

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#23928]
## Description 
Adding P3A question to query Wallet onboarding conversion.

If you accessed the Wallet page at least once, did you create/import a wallet?
`Brave.Wallet.OnboardingConversion`

1) I accessed the wallet page, but did not set up the wallet
2) Yes, I have set up the wallet

## Miscellaneous Information:

Will raise PR soon.

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/24844#issuecomment-1228393839
