### ISSUE TITLE
Enable reduce-user-agent-minor-version by default

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#23938]
@pes10k asked to enable `#reduce-user-agent-minor-version` by default. The description for this feature is:

>Reduce the minor version in the User-Agent string
Reduce the minor, build, and patch versions in the User-Agent string. The Chrome version in the User-Agent string will be reported as Chrome/<major_version>.0.0.0.

**Comment by Johann999** [comment]
Since Version 103.0 the minor part of the user agent is 0.0 only at Chrome, but not Chromium, Edge and Opera.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.43.17 Chromium: 103.0.5060.114 (Official Build) nightly (x86_64)
-- | --
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | macOS Version 11.6.7 (Build 20G630)

### Steps:
1. installed `1.43.17`
2. launched Brave
3. opened `Developer Tools`
4. clicked on the `Console` panel
5. typed in and hit `return` for `navigator.userAgent`
6. confirmed and compared the value & format to `1.41.96`

#### Confirmed from the minor version onward that the values are `0` for each.

**1.43.17:** `'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36'`

**1.41.96:** `'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36'`

`1.43.17` | `1.41.96`
---------|----------
<img width="1327" alt="Screen Shot 2022-07-12 at 4 02 08 PM" src="https://user-images.githubusercontent.com/387249/178613246-8d521046-1a40-4b72-a83c-024518200c0e.png"> | <img width="1312" alt="Screen Shot 2022-07-12 at 4 02 11 PM" src="https://user-images.githubusercontent.com/387249/178613255-43466dd6-a5ba-420f-835e-7ec7c993fc76.png">
