### ISSUE TITLE
Display full RPC URL in add network panel screen

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#23935]
From Slack: https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1657280053728779

|Brave Wallet| Metamask|
-|-
|<img src="https://user-images.githubusercontent.com/3684187/177991619-5ddc284e-044c-429c-91eb-a9a0b748e6c5.png">|<img src="https://user-images.githubusercontent.com/3684187/177991647-056e1e74-d5d0-4516-b63c-494367db83be.png">|

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.43.79 Chromium: 104.0.5112.102 (Official Build) beta (64-bit)  
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | Linux

- Verified steps from [brave/brave-core#14097](https://github.com/brave/brave-core/pull/14097)
- Verified full RPC URL is shown in add network panel screen
![image](https://user-images.githubusercontent.com/17010094/186170149-8b96d340-f4d6-40ff-8934-959ced35a8ae.png)

------------------------
Verification passed on

Brave | 1.43.79 Chromium: 104.0.5112.102 (Official Build) beta (64-bit)  
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | Windows 11 Version 21H2 (Build 22000.795)

- Verified steps from [brave/brave-core#14097](https://github.com/brave/brave-core/pull/14097)
- Verified full RPC URL is shown in add network panel screen
![image](https://user-images.githubusercontent.com/17010094/186169897-d0cdeaa5-4101-4ef8-be33-880f4aa3663c.png)

------------------------
Verification passed on

Brave | 1.43.79 Chromium: 104.0.5112.102 (Official Build) beta (64-bit) 
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [brave/brave-core#14097](https://github.com/brave/brave-core/pull/14097)
- Verified full RPC URL is shown in add network panel screen
![image](https://user-images.githubusercontent.com/17010094/186170533-5da2a2c0-b2fb-44e5-948c-b61536b91826.png)
