### ISSUE TITLE
Investigate why Rabby.io in your browser extensions messes up BW dapp connections

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#23947]
## Description 

Having Rabby.io in your browser extensions messes with brave wallets connections to dApps. Tried it out on matcha.xyz, app.gamee.com and quickswap.exchange on 1.43

https://user-images.githubusercontent.com/12224304/178025318-2bf3885c-a7b1-4dae-a262-4d71e00b77aa.mov

## Steps to Reproduce

   1. download rabby.io as an extension
   2. try use a dapp like matcha.xyz
   3. 

## Actual result:

<img width="675" alt="Screenshot 2022-07-08 at 16 41 44" src="https://user-images.githubusercontent.com/12224304/178025257-d076a04c-ec02-4edd-8b68-57add6e650be.png">

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by bbondy** [comment]
This should all be working now, please let me know if you still encounter an issue.
