### ISSUE TITLE
Brave browser on Mac crashes

### ISSUE THREAD

**Issue by bhaskarnn9** [brave/brave-browser#23949]
## Description 

I am still unable to sync to iPhone, related issue that's marked as fixed is here: [brave-ios/issues/5304](https://github.com/brave/brave-ios/issues/5304)

I have following devices synced
1. Browser on personal Mac - Intel chip
- Mac version 12.2.1 (21D62)
- Browser version: [Version 1.40.113 Chromium: 103.0.5060.114 (Official Build) (x86_64)](https://brave.com/latest/)

2. Browser on work mac - M1 Max
- Mac version 12.4 (21F79)
- Browser version: [Version 1.40.107 Chromium: 103.0.5060.53 (Official Build) (arm64)](https://brave.com/latest/)

## Steps to Reproduce

   1. try to open browser --> settings --> sync in either of the browsers with above specs/versions
   2. observe that browser on mac crashes (on both Intel and Apple chips)
   3. tried to sync on iPhone using sync-phrase - says not enough words

## Actual result:

1. Browser crash on mac
2. not enough words when tried using sync-phrase

## Expected result:
sync successful

## Reproduces how often: 

easy, 5/5

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
@bhaskarnn9 When you get a chance can you go to brave://crashes/ , send the report and paste the id in this issue.

**Comment by bhaskarnn9** [comment]
https://github.com/brave/brave-browser/issues/23952

**Comment by bhaskarnn9** [comment]
@rebron Hey this is still an issue. Also, unable to sync via syncphrase. Any update?
