### ISSUE TITLE
Error message is different for QR Code and Code words

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23948]
## Description 
Error message is different for QR Code and Code words

## Steps to reproduce 

   1. Follow `V. Case for too far in the future error` test case from https://github.com/brave/brave-core/pull/12300 using two Android devices

## Actual result 
Error message for QR Code
```
This code is invalid. Please check that the time and timezone are set correctly on your device.
```

Error message for Code words
```
Sync could be setup [This code is invalid. Please check that the time and timezone are set correctly on your device.]
```

## Expected result
Should be the same 

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone/Tablet
   - Android version: 10/12
   
## Brave version
1.41.94

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @AlexeyBarabash @brave/legacy_qa

**Comment by srirambv** [comment]
Also need to fix this screen to say `Wrong sync code`
![image](https://user-images.githubusercontent.com/17010094/178037853-e99eddc4-49ca-40fa-bdb9-0525507065b1.png)

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave `1.43.74`, `Chromium 104.0.5112.102` on a `Google Pixel XL`, running `Android 9`.

### Steps:

1. Created sync chain on new desktop version, 25 words.
2. Adjusted time on Android device 2 days backwards;
3. Connected Android to chain via words

#### Confirmed I got "Sync could not be setup [This code is invalid. Please check that the time and timezone are set correctly on your device.]" error message

2 days ago | Sync chain | error message
------------|-----------|----------------
![Screenshot_20220629-175307](https://user-images.githubusercontent.com/387249/185451553-d1db2c1f-b7fb-47bc-9ed1-3f5f0fbf7149.png) | <img width="1165" alt="Screen Shot 2022-08-18 at 9 43 05 AM" src="https://user-images.githubusercontent.com/387249/185451595-2dfa3e9c-c011-4514-b836-cd20bb173cec.png"> | ![Screenshot_20220627-175407](https://user-images.githubusercontent.com/387249/185451656-f637d7ab-6ff6-4c7c-8708-ff4f256c1da4.png)
