### ISSUE TITLE
grant notification displays on import from muon even if grant was already accepted with muon version

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#2394]
## Description 
If you have Brave Payments enabled and you've already accepted the most recent UGP grant, when you import to b-c, you will see a notification that you have a grant waiting for you, but you actually don't (since you already accepted it on muon).

## Steps to Reproduce

   1. Fresh profile on 0.25.2 muon.
   2. Enable payments, accept UGP grant.
   3. Close muon.
   4. Launch b-c from terminal with `--upgrade-from-muon` flag.
   5. Look at BAT logo.

## Actual result:
When you click on the BAT logo you will see:
![screen shot 2018-12-06 at 5 36 06 pm](https://user-images.githubusercontent.com/28145373/49616266-41352e80-f97e-11e8-9970-68eaac695453.png)

But you already accepted the grant in muon. If you navigate to brave://rewards there's no way to claim the grant you were notified about since it's not really available to you.

## Expected result:
No notification if grant was already accepted on muon.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.57.18 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? probably

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information
cc @rebron @NejcZdovc @bsclifton - found while testing muon migration

**Comment by LaurenWags** [comment]
Additional details after discussing with @ryanml - when you go to brave://rewards page, the claim banner (seen below) is not on this page as expected. So the only indication of a grant is from the BAT logo.

![screen shot 2018-12-18 at 10 06 43 am](https://user-images.githubusercontent.com/28145373/50162633-d3a5ce00-02ac-11e9-973d-7519fc2f6b90.png)

**Comment by NejcZdovc** [comment]
closing as import from muon is not active anymore
