### ISSUE TITLE
odysee.com not working properly

### ISSUE THREAD

**Issue by memesmith0** [brave/brave-browser#23955]
## Description 

odysee.com is designed to be able to play videos in the background on android. this works on firefox but not on brave

## Steps to reproduce 

   open brave mobile
    go to odysee.com
   open a video
    switch to another app
    video stops playing

## Actual result 
video stops playing

## Expected result
video should continue to play in the background that is the design of the site

## Issue reproduces how often 
easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
stable

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by ryanbr** [comment]
Can you test in Chrome @memesmith0

**Comment by m77e4t** [comment]
Odysee video play normally in the background, I just tried it.
Enable 'Background Video Playback' from brave browser settings.
If it is Off, it will not play in background.

**Comment by memesmith0** [comment]
My problem is solved thank you.
