### ISSUE TITLE
remove search engine onboarding for AT / ES / MX

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#23950]
## Description 

Remove Set default search engine onboarding for the following locales: AT / ES / MX 
Austria, Spain, Mexico

## Expected Result

   1. Install Brave from the following locales AT / ES / MX  
   2. User should not see the search engine onboarding on first tap on 

### Region set to AT / ES / MX 
1. Fresh profile
2. Search onboarding should NOT be shown

**Comment by kjozwiak** [comment]
The above requires `1.42.81` or higher for `1.42.x` verification 👍

**Comment by Uni-verse** [comment]
Verification `PASSED` on `Android ARM` using 

Brave	1.42.81 Chromium: 104.0.5112.69 (Official Build) (64-bit) 
Revision	7ce2902023c722af8564068e6b26e934b83fd774-refs/branch-heads/5112@{#1213}
OS	Android 12; Build/SP1A.210812.016

- Ensured the `default search engine screen` is removed from onboarding when tapping on `URL bar` with `clean profile`.
- Ensured the `default search engine onboarding screen` does not show up when `upgrading` to version `1.42.81` when tapping on the URL bar.

<table><tr><td>AT (Austria) </td><td>MX (Mexico) </td><td> ES (Spain) </td></tr><tr><td>

https://user-images.githubusercontent.com/17885425/181594336-610261de-9cc7-4700-83f1-eae57dc0102a.mp4 

</td><td>

https://user-images.githubusercontent.com/17885425/181593062-665cdaf4-7b0e-4d8a-ad39-468b49c47ce3.mp4

</td><td>

https://user-images.githubusercontent.com/17885425/181598014-f4224921-7b81-4b9b-87d4-9ab3429363be.mp4

</td></tr></table>
