### ISSUE TITLE
The editing panel for `Top Sites` icons is bugged and non-functional

### ISSUE THREAD

**Issue by d-e-v-esh** [brave/brave-browser#23954]
## Description 

I cannot make changes to the top sites that show up on the home screen. After clicking the edit button, the editing window that shows up is bugged. The editing window shows up behind the icons and disappears when I click on it so it is not even functional.

Edit Button
![image](https://user-images.githubusercontent.com/59534570/178096677-09c84adf-8c12-4882-bcd8-f252d78fdb2e.png)

## Steps to Reproduce

   1. Have `Top Sites` enabled in the customize section.
   2. Hover the mouse over the icon that appeared on the home page.
   3. An edit button will appear. Click on it.
   4. You will see the buggy editing window.

## Actual result:

![brave_ZVVibIzLY0](https://user-images.githubusercontent.com/59534570/178096997-0626331d-d248-4eea-a1e2-622269cda23f.gif)

## Expected result:
The window should be functioning like normal. But it appears behind the icons and goes away when I click on it.

## Reproduces how often: 

It is happening every time.

## Brave version (brave://version info)

[Version 1.40.113 Chromium: 103.0.5060.114 (Official Build) (64-bit)]

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
Yes. The browser is up to date.

**Comment by simonhong** [comment]
@d-e-v-esh Thanks for reporting. This issue is already fixed and will be available in the next update.
Closed as duplicated with https://github.com/brave/brave-browser/issues/23685
