### ISSUE TITLE
Able to view ads after 426 Upgrade Required

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#23957]
Follow up to: https://github.com/brave/brave-browser/issues/21388

User can view ads and be paid for them after 426.
After 426 from any end point we should stop serving ads

## Steps to Reproduce

1. Override `https://mywallet.ads.brave.com/v2/confirmation/payment/*` response code to 426
1. Enable rewards and ads
1. View an ad
1. redeem the payment tokens -> will give 426
1. View an ad

## Actual result:

User can view and be paid for ads
The UI indicates that this is not possible:
![image](https://user-images.githubusercontent.com/34715963/178099080-8d2194d7-8e97-44e1-b48b-88e443acecd2.png)

## Expected result:
User is not served nor paid for ads till browser is upgraded

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.41.94 Chromium: 103.0.5060.114 (Official Build) (64-bit)
-- | --
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | Ubuntu 18.04 LTS

cc @brave/qa-team @tmancey @codomii @rebron @Miyayes @aseren

**Comment by tmancey** [comment]
Closing as resolved by https://github.com/brave/brave-browser/issues/23958
