### ISSUE TITLE
Update list of acceptable TLDs to include .coin and .token non-ICANN TLDs.

### ISSUE THREAD

**Issue by lukemulks** [brave/brave-browser#23953]
## Description 

We have just updated our Brave Crypto DNS Strategy to remove the `.coin` and `.token` non-ICANN TLDs from the list of reserved non-ICANN TLDs. 

This update has been reflected in our documentation here, for reference: https://github.com/brave/brave-browser/wiki/Reserved-non-ICANN-top-level-domains-(TLDs)-and-subdomains

*The Ask*

With this issue, we're requesting a minor update to our acceptable TLDs to include `.coin` and `.token`, to reflect the updated policy change. 

Unstoppable Domains made the `.coin` TLDs available for sale last year, causing a conflict when Brave users purchase .coin TLDs through Unstoppable Domains and attempt to resolve those TLDs in Brave. 

Thanks in advance!

## Steps to Reproduce

   1. 
   2. 
   3. 

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by bbondy** [comment]
Per a discussion on Slack: `.coin` is already on the list of supported TLDs and `.token` is not supported by UD. So there's nothing to do here. Closing for now.
Please re-open if there's a particular bug though. Thanks!
