### ISSUE TITLE
VPN restore fails if the app gets updated via a different account where the purchase isn't made

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23969]
## Description 
VPN restore fails if the app gets updated via a different account where the purchase isn't made

## Steps to reproduce 

   1. Have 2 Google Accounts created, One for US and one for India
   2. Purchase/Redeem code for VPN on one account (INR)
   3. Switch to US account in playstore and update Brave
   4. VPN is disconnected during update
   5. Loading VPN shows purchase value in USD instead of INR
   6. Try to restore subscription fails and shows subscription expired
   7. Only way to restore is to uninstall and reinstall with the account in which it was purchased

## Actual result 
VPN restore fails if the app gets updated via a different account where the purchase isn't made

## Expected result
Irrespective of which account the app is updated, should be able to restore subscription as long as the valid account is linked to PlayStore

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? NA as its not available
- Can you reproduce this issue with the current Play Store Nightly version? NA as there is no prod subscription

## Device details
   - Install type (ARM, x86):ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 12
   
## Brave version
Playstore verson

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @deeppandya @timchilds @brave/legacy_qa

**Comment by deeppandya** [comment]
@srirambv this issue should be fixed with https://github.com/brave/brave-core/pull/19576. would it be possible to verify and close the issue ?

**Comment by srirambv** [comment]
Closing as I've not encountered this in a while.
