### ISSUE TITLE
Brave Search pages opened by promotion banner at NTP should always be able to show "set default" UI

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#23968]
## Steps to Reproduce

   1. Set a default search provider that is not Brave Search
   2. Visit search.brave.com and perform a search
   3. Repeat searches on search.brave.com more than 3 times
   4. Run with the flag to show search promotion for Brave Search at NTP
   5. Begin to type a search query in to the promotion's search box and enter

## Actual result:

The results page will not be able to create the button for the user to make Brave Search their default search provider, since we only currently allow 3 calls to that API in a 24-hour period.

## Expected result:
Any search results page opened as a result of the search promotion at NTP should not be restricted to the 24-hour limit. The user has decided to engage with the promotion and we wish to provide the option to set as default.

**Comment by Ayern12** [comment]
##so What should I do?

Pada Isn, 11 Jul 2022, 13:53 Simon Hong ***@***.***> menulis:

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.43.58 Chromium: 104.0.5112.81 (Official Build) beta (64-bit)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | Windows 11 Version 21H2 (Build 22000.795)
```

Case 1: Non NTP SI page - Do not select  `Set Brave search as default` in the search results page

1. install 1.43.58
2. launch Brave using  `--enable-features=BraveSearchNTP` command line switch
3. open `brave://settings/search`
4. set search engine to `DuckDuckGo` for `Normal Window` as a default provider
5. open NTP and check search promotion is visible `Want even better privacy?....`
6. type keyword `crypto` from search box in promotion UI
7. check `Set Brave Search as a default` is visible from search results page
8. reload current search result page 4 times and check Set Brave Search as a default is visible
9. open another NTP and check search promotion is still visible

step4|step5|step6|step7|Step8|Step 9
-----|-----|-----|-----|-----|------
<image width="850" alt="settings" src="https://user-images.githubusercontent.com/98358127/182946613-655217c9-645d-4a4c-912e-3d520e6491c0.png">|<image width="850" alt="settings" src="https://user-images.githubusercontent.com/98358127/182946580-75a5dbe7-b2bf-4b73-8051-1e557724bff0.png">|<image width="850" alt="settings" src="https://user-images.githubusercontent.com/98358127/182947092-b923279d-a6b7-4506-8049-0d2017840511.png">|<image width="850" alt="settings" src="https://user-images.githubusercontent.com/98358127/182947302-82fff092-9ac9-4525-b830-d337c81bb9d7.png">|<image width="850" alt="settings" src="https://user-images.githubusercontent.com/98358127/182947713-1173c15e-e1e8-452f-8bb3-e49fc29bf539.png">|<image width="850" alt="settings" src="https://user-images.githubusercontent.com/98358127/182948253-9fcbe418-736c-4d8b-9d2d-1c6750938495.png">

Case 1: Non NTP SI page - Select  `Set Brave search as default` in the search results page

1. clean profile 
2. launch Brave using  `--enable-features=BraveSearchNTP` command line switch
3. open `brave://settings/search`
4. set search engine to `Qwant` for `Normal Window` as a default provider
5. open `NTP and check search promotion is visible `Want even better privacy?....`
6. type keyword `NFT` from `search box` in promotion UI
7. Enter keyboard return or search icon in the box
8. check `Set Brave Search as a default` is visible from search result page
9. reload current search result page 4 times and check Set Brave Search as a default is visible
10. open another NTP and check search promotion is still visible

Step 4|Step 5|Step6
<image width="850" alt="settings" src="https://user-images.githubusercontent.com/98358127/182951328-f1169fe3-2e04-47f3-ab4a-4c61e078bdfc.png">|<image width="850" alt="settings" src="https://user-images.githubusercontent.com/98358127/182951464-154d08c8-f0b4-4c3e-85aa-86a2147a7519.png">|<image width="850" alt="settings" src="https://user-images.githubusercontent.com/98358127/182951706-4c179621-4c04-414c-a015-922d79ec2e0a.png">|<
