### ISSUE TITLE
Cannot automate installation of extensions on Linux

### ISSUE THREAD

**Issue by staticdev** [brave/brave-browser#23966]
## Description 
I am a developer who wants to automate configuration of Brave through Ansible (https://github.com/staticdev/ansible-role-brave).

In Chrome/Chromium it is possible to create `EXTENSION_ID.json` on /usr/share/google-chrome/extensions as described in https://developer.chrome.com/docs/extensions/mv3/external_extensions/#preferences.

On Brave, I saw extensions are stored in a folder on `~/.config/BraveSoftware/Brave-Browser/Default/Extensions`, but it does not suffice to create the folder with the id. Are there any instructions on how to do it to install new extensions manually?

## Brave version (brave://version info)
1.40.113 Chromium: 103.0.5060.114 (Official Build) (64-bit)

**Comment by dagadbm** [comment]
is this something that will be looked at? 
https://developer.chrome.com/docs/extensions/mv3/external_extensions/#preferences
it should be working out of the box no? or was this removed from brave?

**Comment by staticdev** [comment]
> is this something that will be looked at? https://developer.chrome.com/docs/extensions/mv3/external_extensions/#preferences it should be working out of the box no? or was this removed from brave?

Last time I tried (July 2022), it did not work on Brave. It is the only part in my machine configuration I need to do manually today.

**Comment by dagadbm** [comment]
Jesus... Hopefully someone will try to fix this eventually. I understand it can be because of security reasons as well but there should be a way to have this since this is a default feature of chromium based browsers.

**Comment by bsclifton** [comment]
Hi there folks - sorry for the long turn-around time on a response to this; I lost track of this ☹️ Kudos @dagadbm and @staticdev for the bump

I think the misunderstanding is the location for the JSON. This is different on Chromium than it is for Chrome. And then we change it for Brave also.

Here's how you can do it:

1. Create a file
    ```
    vim /etc/brave/policies/managed/extension_install_policy.json
    ```
2. Paste in this (just an example; edit to put your real ones)
    ```
    {
       "ExtensionInstallForcelist": [
            "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa;https://clients2.google.com/service/update2/crx",
            "abcdefghijklmnopabcdefghijklmnop"
        ]
    }
    ```
3. Save the file and exit (escape; `:wq`, enter)
4. Load Brave; verify it shows under brave://policy/

More information here:
https://chromeenterprise.google/policies/#ExtensionInstallForcelist

**Comment by staticdev** [comment]
Thanks @bsclifton I will try that out.

**Comment by bsclifton** [comment]
I closed issue since this should resolve - but please let me know. Thanks @staticdev! 😄

**Comment by dagadbm** [comment]
Is there a blog post or something where this is explained ?
Seems the files change depending on the OS you are using? Does the file
location also change?

**Comment by bsclifton** [comment]
@dagadbm no - there isn't a blog post unfortunately. But I'll work with @Brave-Matt to get the help center article updated 🙂

**Comment by dagadbm** [comment]
Can you ping this issue when thats done?

Also just from the link you gave I am not sure I fully understand where to
put things since I am using mac and not linux.

**Comment by bsclifton** [comment]
@dagadbm sure, will follow up with you. Each OS is a bit different; macOS uses plist files I believe. I'll get information about that and get the article updated too (which currently only documents Windows)
