### ISSUE TITLE
Hello, I need to use adobe Flash Player！What is the last support version?

### ISSUE THREAD

**Issue by cc19264997** [brave/brave-browser#23964]
Hello, I need to use adobe Flash Player！

What is the last support version?

**Comment by kakamorsch** [comment]
Hello!
HTML5 replaced Adobe Flash Player in the browsers. I don't know if there is any browser supporting Flash Player at the moment but I can assure you that Brave isn't one, because Flash Player itself has lots of vulnerabilities.

**Comment by rebron** [comment]
Hi @cc19264997. We ended support for Flash on December 31, 2020. Please see https://support.brave.com/hc/en-us/articles/360035598412-Sunsetting-Flash and https://www.adobe.com/products/flashplayer/end-of-life.html

**Comment by Brave-Matt** [comment]
@cc19264997 @rebron is correct here. Closing this issue out.
