### ISSUE TITLE
Text cut off in onboarding screen

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23972]
## Description 
Text cut off in onboarding screen

## Steps to reproduce 

   1. Clean install
   2. Text in onboarding is cut off

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/178262993-88e5eccd-2a6e-4879-89ef-0d8cc293e844.png)
![image](https://user-images.githubusercontent.com/17010094/178266023-6c373666-b9a3-48cc-98b4-030b218bed23.png)

## Expected result
No text should be cut off on any screen

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes in 1.41.x
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone 
   - Android version: 12
   
## Brave version
1.41.95

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @tapanmodh @timchilds @anthonypkeane @Uni-verse @kjozwiak

**Comment by kjozwiak** [comment]
The above will require `1.41.96` or higher for `1.41.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.41.96 x64 build
- Verified steps from issue description
- Verified onboarding text is shown fully 
- Verified increasing the device display text doesn't affect the onboarding screen text

Default font size | Bigger Display font
-- | --
![image](https://user-images.githubusercontent.com/17010094/178448149-675f88fd-c179-4fa2-8709-5c81f601594a.png) | ![image](https://user-images.githubusercontent.com/17010094/178448173-d447f22c-1494-4b10-8c04-3c8a90a33fbe.png)
