### ISSUE TITLE
Incorrect publisher / creator / website favicon in Rewards panel 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23970]
## Description 

Incorrect Publisher icon in panel 

## Steps to Reproduce

Not sure

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/178238766-a7084635-596b-4cb4-8194-b588e87ae704.png)

## Expected result:
Should show correct publisher icon

## Reproduces how often: 

Happened once

## Brave version (brave://version info)

<html>
<body>

Brave | 1.43.3 Chromium: 103.0.5060.114 (Official Build) nightly (64-bit)
-- | --
Revision | `a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}`
OS | Windows 11 Version 21H2 (Build 22000.778)

</body>
</html>
## Version/Channel Information:

- Can you reproduce this issue with the current release? Not sure
- Can you reproduce this issue with the beta channel? Not sure
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/rewards-client @brave/legacy_qa

**Comment by Miyayes** [comment]
Most important is to watch whether this happens in the new WebUI Rewards panel itself. If it doesn't, then we'll consider it resolved once WebUI Rewards panel lands. @srirambv

**Comment by srirambv** [comment]
This still happens on WebUI Rewards panel. Checked with Flag enabled manually and with flag disabled.

**Comment by zenparsing** [comment]
@srirambv Were you able to get any more info on repro steps, or maybe the URL for the incorrect icon?

**Comment by zenparsing** [comment]
@srirambv If you're using the extension version of panel and you see it again, try right clicking the icon and doing "Copy Image Address" - we might be able to see if we're generating the wrong icon URL.

**Comment by srirambv** [comment]
@zenparsing am on nightly so don' think it will be possible to go back to extension version. the WebUI panel is set to 100% now via griffin

**Comment by Miyayes** [comment]
Now issue is that no favicon is showing for Brave Talk, instead of showing an incorrect favicon 🤔

**Comment by Miyayes** [comment]
QA says they haven't seen this in recent times, and neither has Chris. We will relog if we see it again.
