### ISSUE TITLE
Incorrect values for ad grant on panel

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#23971]
## Description 

Incorrect values for ad grant on panel

## Steps to Reproduce

No idea

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/178239098-ad5632eb-ec08-4816-ba89-9d5f18b5c603.png)

## Expected result:
Should show correct values in the ad grant notification message and rewards arrived message

## Reproduces how often: 

Happened once 

## Brave version (brave://version info)

<html>
<body>

Brave | 1.43.3 Chromium: 103.0.5060.114 (Official Build) nightly (64-bit)
-- | --
Revision | `a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}`
OS | Windows 11 Version 21H2 (Build 22000.778)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? No idea
- Can you reproduce this issue with the beta channel? No idea
- Can you reproduce this issue with the nightly channel? Yes happened on Nightly 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/rewards-client @brave/legacy_qa

**Comment by tmancey** [comment]
@srirambv can you please let me know why you think this value is wrong? Thanks

**Comment by tmancey** [comment]
@srirambv reminder to backup your profile please :-) Thanks

**Comment by tmancey** [comment]
Closing as works for me
