### ISSUE TITLE
Brave Ads notification timeout event is not triggered

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#23978]
## Description 

Brave Ads notification timeout event is not triggered.

## Steps to Reproduce

   1. View a notification ad
   2. Wait for the notification ad to timeout

## Actual result:

`Timed out notification ad with placement id` is not displayed in the console log

## Expected result:
`Timed out notification ad with placement id` should be displayed in the console log

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.43.58 Chromium: 104.0.5112.81 (Official Build) beta (64-bit)
-- | --
Revision | 174dbe6e33bc81994fceb71d751be201d0b4803d-refs/branch-heads/5005_109@{#3}
OS | Ubuntu 18.04 LTS

Verified `Timed out` is triggered and notification ad is not longer shown
```
[3712:3712:0808/131422.638684:VERBOSE3:notification_ad_event_timed_out.cc(21)] Timed out notification ad with placement id 6550d7b0-afd4-4842-9443-4d99b2a45e04 and creative instance id 04064736-ea43-463a-bd6e-6c2be4408b4d
```

**Comment by stephendonner** [comment]
## Verification `PASSED` using 

Brave | 1.43.63 Chromium: 104.0.5112.81 (Official Build) beta (x86_64)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | macOS Version 11.6.8 (Build 20G730)

### Steps:
1. installed `1.43.63`
2. launched Brave using Rewards & Ads staging
3. enabled Rewards
4. waited a few minutes
5. triggered an ad
6. waited two minute for the ad to time out

<img width="1116" alt="Screen Shot 2022-08-09 at 9 24 41 AM" src="https://user-images.githubusercontent.com/387249/183706670-6873c487-f0ac-488d-b1a0-3ee4900fd9c8.png">

#### Confirmed the ad timed out and auto-dismissed:
`[8615:259:0809/092241.223166:VERBOSE3:notification_ad_event_timed_out.cc(21)] Timed out notification ad with placement id 278bb9e8-0ccc-44b7-a4ae-061b41079885 and creative instance id 7a49c681-76ee-48ee-a627-1bd80de82854`

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.43.67 Chromium: 104.0.5112.81 (Official Build) beta (64-bit)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | Windows 11 Version 21H2 (Build 22000.856)
```

### Steps:
1. installed `1.43.67`
2. launched Brave using Rewards & Ads staging
3. enabled Rewards
4. waited a few minutes
5. triggered an ad
6. waited two minutes for the ad to time out

Verified `Timed out` is triggered and notification ad is not longer shown

![image](https://user-images.githubusercontent.com/98358127/184224265-9783adf3-0c94-4157-9691-1ac379c8a993.png)

```
[10228:1892:0811/114742.012:VERBOSE3:notification_ad_event_timed_out.cc(21)] Timed out notification ad with placement id bdfc958a-6662-4c1a-95bb-922bc121c2a5 and creative instance id 40f9f892-2eee-4b8f-8bde-45915ae2fd88

```

**Comment by Uni-verse** [comment]
Verified using `Samsung GS 21` & `Samsung Galaxy Tab S7` using the following build(s):

```
Brave	1.43.74 Chromium: 104.0.5112.102 (Official Build) beta (64-bit) 
Revision	8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}
OS	Android 12; Build/SP1A.210812.016
```
Using test plan in https://github.com/brave/brave-core/pull/14315#issue-1316454852 for the Android requirements:

- Ensured ad notification logs are shown on Android after enabling rewards and viewing an ad.

<table><tr><td>Example</td><td>

![Screen Shot 2022-08-19 at 1 23 28 PM](https://user-images.githubusercontent.com/17885425/185674702-1683319f-47b3-4e5d-bcdd-863b5d836571.png) 

</td></tr><tr><td>Example</td><td>

![Screen Shot 2022-08-19 at 12 49 51 PM](https://user-images.githubusercontent.com/17885425/185674738-210443fd-6215-43a6-927e-c4364a1a447a.png)

</td></tr></table>
