### ISSUE TITLE
anonymous diagnostic collection should be opt-out rather than opt-in

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#23989]
## Description 

With the latest `1.41.x` RC, it looks like the first selection via onboarding re: anonymous diagnostic collection is set as opt-in rather than opt-out. From the various discussions on Slack, I believe it should also be opt-out like it's on the `BETA` & `Nightly` channels. Security review completed via https://github.com/brave/security/issues/791.

## Steps to reproduce / Test plan

   1. install the latest `1.41.x` and launch the browser
   2. you'll notice that the `anonymous diagnostic collection` option has been set to opt-in rather than opt-out

Examples mentioned below via screenshots under the `Actual result` & `Expected result` sections.

## Actual result 

![Screenshot_20220711-152832_Brave](https://user-images.githubusercontent.com/2602313/178352985-1d245b7b-9f37-4e16-b94d-a28c4d332ee8.jpg)

## Expected result

![Screenshot_20220711-163848](https://user-images.githubusercontent.com/2602313/178354139-ac58ecd9-d4db-407b-ba90-66240ef3c064.png)

## Issue reproduces how often 

100% reproducible using the STR/Cases outlined above.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `N/A` (new changes being released via `1.41.x`)
- Can you reproduce this issue with the current Play Store Beta version? `No`
- Can you reproduce this issue with the current Play Store Nightly version? `No`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Pixel 6` & `Samsung S10+`
   - Android version: `Android 13` & `Android 12`
   
## Brave version

```
Brave | 1.41.95 Chromium: 103.0.5060.114 (Official Build) (64-bit)
--- | ---
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | Android 13; Build/TPB3.220617.002
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by anthonypkeane** [comment]
https://github.com/brave/security/issues/791

**Comment by kjozwiak** [comment]
The above requires `1.41.96` or higher for `1.41.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.41.96 x64 build
- Verified steps from issue description
- Verified Anonymous diagnostic collection is selected by default and user needs to `opt-out` of it manually
- Also verified the colour of checkbox is now blue instead of red

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/178449943-08757370-94ad-4d7a-b8f1-1aa245d39fd1.mp4> | <video src=https://user-images.githubusercontent.com/17010094/178450047-28dbcadb-ce61-4f82-a03c-99dc9e46bb64.mp4>
