### ISSUE TITLE
Sync: Pressing return key after inputting device name does not submit form

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#2398]
In the 'I am new to Sync' dialog, after inputting the device name, pressing return does not submit the dialog.

![image](https://user-images.githubusercontent.com/741836/49621968-7d678f80-f97c-11e8-8f23-16dbe2530cad.png)

**Comment by srirambv** [comment]
+1 to have this fixed. This was an annoying problem on muon as well

**Comment by cezaraugusto** [comment]
closing as sync v2 adds the device name automatically.
