### ISSUE TITLE
Disable peeking card when new tab page sponsored images are shown

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#23981]
## Description 

The Brave News peeking card should not be displayed when a new tab page sponsored image is shown. Brave News peeking card should continue to "peek" on non sponsored new tab images.
brave://flags/#brave-news-peek

## Steps to Reproduce

   1. Use 1.40.x and higher. Have Brave News enabled.
   2. Open new tab page and notice Brave News peeks from the bottom. Refresh page and notice Brave News peeks from all new tab page opens.

## Actual result:

<img width="1365" alt="Screenshot 2022-07-11 at 8 18 44 AM" src="https://user-images.githubusercontent.com/5951041/178299165-91f7a191-299e-4a77-bd1b-4c87e112eff2.png">

## Expected result:
Disabled on sponsored images
<img width="1681" alt="Screenshot 2022-07-11 at 8 42 27 AM" src="https://user-images.githubusercontent.com/5951041/178303232-ea3dae25-6fc7-4d4f-a858-067ea31586c0.png">

Enabled for non-sponsored images
<img width="1363" alt="Screenshot 2022-07-11 at 8 45 10 AM" src="https://user-images.githubusercontent.com/5951041/178303715-f62d297b-b373-438d-8c3a-be482010c19c.png">

## Reproduces how often: 

Easily.

## Brave version (brave://version info)

1.40.x and higher

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by LorenzoMinto** [comment]
Duplicate https://github.com/brave/brave-browser/issues/34968

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/34968
