### ISSUE TITLE
default shield-on option lost

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#23988]
## Description 

Shields default option `Enabled` fix worked in `1.42.x` and `1.43.x` via https://github.com/brave/brave-core/pull/14031 but this fix didn't work with `1.41.x.`  This is a follow up issue to https://github.com/brave/brave-browser/issues/23214

## Steps to Reproduce

- Installed `1.41.95`
- Visit buzzfeed.com
- Toggle `OFF` Shields in the Shields panel
- close the browser
- open  `AppData\Local\BraveSoftware\Brave-Browser-Nightly\User Data\Default\Preferences`
- changed  "buzzfeed.com,*" -> ` *,*`  via the braveShields section 
- relaunched the browser

## Actual result:

Shields was disabled
`*,*` entry was still shown

## Expected result:
Shields should be `enabled` for `buzzfeed.com`
*,* entry should be removed in preference file

## Reproduces how often: 

Easily 

## Brave version (brave://version info)

Brave | 1.41.95 Chromium: 103.0.5060.114 (Official Build) (64-bit)
-- | --
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | Windows 11 Version 21H2 (Build 22000.739)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
Closing as https://github.com/brave/brave-core/pull/14121 was uplifted directly into `1.41.x`. The above will require `1.41.96` or higher for `1.41.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Reproduced the issue in `1.41.95`. Good catch @MadhaviSeelam!

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```

Brave | 1.41.96 Chroium: 103.0.5060.114 (Official Build) (64-bit)
-- | --
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | Windows 10 Version 21H2 (Build 19044.1806)

```
- Verified the STR from the description and ensured shield for the site is enabled and *,* is removed from the preference file

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.41.96 Chromium: 103.0.5060.114 (Official Build) (x86_64)
-- | --
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | macOS Version 12.4 (Build 21F79)
```
