### ISSUE TITLE
After enabling, VPN stayed in connecting mode and had to click VPN again to show alert modal

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#23991]
## Steps to Reproduce

- Install 1.41.91
- Disable DnsOverHttpsMode in the registry
-   - go to Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Policies\BraveSoftware\Brave
-   - create new string value>>DnsOverHttpsMode
-   - set to off
- Launch Brave
- Verify policy is disabled via brave://policy/
- Purchase and Setup Brave VPN
- Click VPN button and enable

## Actual result:

VPN showed stayed in connecting mode
Clicked VPN button again to show the alert modal

![2022-07-11_14h23_36](https://user-images.githubusercontent.com/98358127/178366257-c4949967-b1a5-4470-873b-f406cec3b94d.gif)

## Expected result:
`Secure DNS is disabled...' alert modal should be displayed immediately? 

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
Found this issue while testing https://github.com/brave/brave-browser/issues/23123

@spylogsster @rebron

**Comment by spylogsster** [comment]
We reverted this PR https://github.com/brave/brave-browser/issues/23123 so I close this as wont fix
