### ISSUE TITLE
[Android] Brave Rewards panel site info not loading when logged in [Twitter]

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#23994]
## Description 
Brave Rewards panel site info not loading when logged in [Twitter]

Found while testing https://github.com/brave/brave-browser/issues/20980

## Steps to reproduce 

   1. Clean install
   2. Navigate to `mobile.twitter.com`
   3. Login with google credentials or twitter handle
   4. Open profile page - `mobile.twitter.com/{username}`
   5. Open BR Panel, observe site info

## Actual result 
Tab | Mobile
-|-
![screenshot-1657580215942](https://user-images.githubusercontent.com/17885425/178378445-af931b15-121b-43ba-b85c-8ea21add666d.png) | ![screenshot-1657581034274](https://user-images.githubusercontent.com/17885425/178378448-7f5c6fae-349b-44ad-b8bd-1e06f1ebb614.png)

## Expected result
![screenshot-1657582857101](https://user-images.githubusercontent.com/17885425/178378457-d34d8abc-87d9-44ca-a5bc-eac52f5150ca.png)

## Issue reproduces how often 
Easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? N/A
- Can you reproduce this issue with the current Play Store Nightly version? N/A

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Tablet, mobile
   - Android version: 12
   
## Brave version
1.41.95

**Comment by kjozwiak** [comment]
CCing @Miyayes

**Comment by Uni-verse** [comment]
Looks like this behavior is expected per https://github.com/brave/brave-browser/issues/20712

Closing as invalid/expected. 

CC: @kjozwiak @LaurenWags
