### ISSUE TITLE
Import from Brave

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#24]
- [ ] Ledger wallet
- [ ] Bookmarks
- [ ] Cookies
- [ ] History

More?

**Comment by bbondy** [comment]
QA notes:
When testing please look for missed parts, like in this one ledger wallet. If no issue exists for that yet, please create one.

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Linux

* Verified cookies were imported from Brave and loading site remained logged in
* Verified Password was auto added in `chrome://settings/passwords`
* Verified stats were updated on new tab
* Verified bookmarks and history was imported and listed in the same order
* Verified re importing data again didn't lose any thing that was already imported
