### ISSUE TITLE
openstreet map fails to load on https://glutt.se/

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#24009]
## Description 
Unable to load the openstreet map on https://glutt.se/filter/Karta-60.94077-16.65340-39811/alla/

## Steps to Reproduce

   1. Open https://glutt.se/filter/Karta-60.94077-16.65340-39811/alla/
   2. Click on the "Eye" below the date, which will load the openstreet 
   3. openstreet embedded loads some elements, but not the actual map.

## Actual result:

![glutt-brave](https://user-images.githubusercontent.com/1659004/178475968-63255d78-3da7-49b1-a221-cff1750e5a17.png)

## Expected result:
![glutt-chrome](https://user-images.githubusercontent.com/1659004/178476444-8ec57abf-62bb-42b7-ad53-f21d728cbfd9.png)

## Reproduces how often: 

Easily, 

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `No`
- Is the issue reproducible on the latest version of Chrome? `No`
- Is the issue reproducible on the latest version of Safari? `No`

## Miscellaneous Information:
Console is showing `GET https://c.tile.openstreetmap.org/8/139/73.png 403`  errors. Same errors not shown in plain Chrome.

Shields has no affect, disabling completely.  Tested in ungoogled-chromium_102.0.5005.61-1.1, works here.

Was reported from a user in the webcompat report site.

**Comment by mkarolin** [comment]
Test plan: see STR.

**Comment by kjozwiak** [comment]
Adding `QA/Blocked` as we'll need to push https://github.com/brave/brave-variations/pull/332 into Griffin via Nightly first and then enabling it on `BETA`.

**Comment by kjozwiak** [comment]
Removing `QA/Blocked` after speaking with @mkarolin. We're going to decouple the checks mentioned via https://github.com/brave/brave-browser/issues/24009#issuecomment-1183622774 that requires the `AllowCertainClientHintsStudy` study. As mentioned above, the website has been fixed so we'll basically just need to make sure it's loading without any problems.

I added and improved the STR/Cases outlined via https://github.com/brave/brave-browser/issues/24009#issuecomment-1183622774 and added them into https://github.com/brave/brave-variations/pull/332#issue-1344849858 and went through the STR/Cases as per https://github.com/brave/brave-variations/pull/332#issuecomment-1244832192.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.44.85 Chromium: 105.0.5195.127 (Official Build) beta (x86_64)
-- | --
Revision | 912488396852bf658ab32465980c0b93a3c27a83-refs/branch-heads/5195@{#1109}
OS | macOS Version 11.7 (Build 20G817)

### Steps:
1. installed `1.44.85`
2. launched Brave
3. shut down
4. relaunched Brave
5. opened `brave://version` and confirmed no `AllowCertainClientHintsStudy`
6. loaded `https://glutt.se`
7. ensured the initial map loaded
8. loaded various in-page links with different map positions

### Confirmed I could load and display correct-appearing map content - no noticeable errors via `Console`, either

example | example | example
---------|---------|----------
<img width="1787" alt="Screen Shot 2022-09-14 at 11 31 29 AM" src="https://user-images.githubusercontent.com/387249/190234924-c8a07914-14e0-4aac-8224-8b9c6ada43b5.png"> | <img width="1787" alt="Screen Shot 2022-09-14 at 11 28 50 AM" src="https://user-images.githubusercontent.com/387249/190234969-0193c5c9-7e1c-495e-a128-1e35153d9878.png"> | <img width="1787" alt="Screen Shot 2022-09-14 at 11 29 10 AM" src="https://user-images.githubusercontent.com/387249/190234970-0ec67c11-75cc-4bb6-b1f5-58199766895c.png">



Brave | 1.44.85 Chromium: 105.0.5195.127 (Official Build) beta (x86_64)
-- | --
Revision | 912488396852bf658ab32465980c0b93a3c27a83-refs/branch-heads/5195@{#1109}
OS | macOS Version 11.7 (Build 20G817)
