### ISSUE TITLE
Text is not properly justified with checkbox on onboarding screen

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#24003]
## Description 
Text is not properly justified with checkbox on onboarding screen

## Steps to reproduce 

   1. Install 1.41.96 build
   2. `Send anonymous diagnostic reports ...` text is not justified with the checkbox

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/178451886-36f19b66-c391-451c-a7d6-318f6db335a3.png)

## Expected result
Align text properly with the checkbox

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Tablet
   - Android version: 10
   
## Brave version
1.41.96

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @tapanmodh @deeppandya

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy Tab S7` using

```
Brave	1.43.74 Chromium: 104.0.5112.102 (Official Build) beta (64-bit) 
Revision	8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}
OS	Android 12; Build/SP1A.210812.016
```

- Verified that text is properly justified with checkbox on P3A onboarding screen

<img width="400" alt="0" src="https://user-images.githubusercontent.com/17885425/185499253-f42cdabe-8359-498d-bba0-9ee57428dcbe.png">
