### ISSUE TITLE
[Android] Follow up to #20998 - Replace "Wallet" text in Rewards contexts to say "Brave Rewards"

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#24001]
## Description 
Replace "Wallet" text in Rewards contexts to say "Brave Rewards." The following pages/modals still contain some `wallet` strings that may need to be replaced with `Brave Rewards`. Follow up to #20998, see for details.

- [ ] Brave rewards wallet dropdown contains `Wallet Verified`/`Verifed` - There is copy mismatch when viewing on panel/rewards.
- [ ] Brave Reset Rewards modal/prompt string - `This will delete your brave wallet` may need to reviewed by product.

brave://rewards/Panel | Reset Rewards | rewards-internals
-|-|-
![screenshot-1657596141793](https://user-images.githubusercontent.com/17885425/178430354-4794be26-e946-489a-86b9-1caac9c69b71.png) | ![screenshot-1657595670808](https://user-images.githubusercontent.com/17885425/178430163-2b083860-0231-4995-a3c8-83ce7d4c0170.png) | ![screenshot-1657596291709](https://user-images.githubusercontent.com/17885425/178430095-5bc35b69-8e24-47f0-b3e7-365e609d42fb.png)

## Steps to reproduce 

   1. Clean install
   2. Enable Staging Rewards/Prod Rewards
   3. Log in to Custodial accounts, Uphold/Gemini
   4. Check mentioned pages/modals in description 

## Actual result 
See description

## Expected result
Strings containing `Wallet` need to be replaced with `Brave Rewards` in context of rewards

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Tablet, Mobile - Galaxy Devices
   - Android version: 12
   
## Brave version
1.41.95

**Comment by Uni-verse** [comment]
@timchilds Product to investigate whether we should updated the sections mentioned.

**Comment by Miyayes** [comment]
>Brave://rewards-internals - Section with heading Wallet info possibly will need to be reviewed so its not confused with anything brave wallet related.

Will be resolved for free with https://github.com/brave/brave-browser/issues/24017.

**Comment by Uni-verse** [comment]
In progress using 

Brave	1.45.64 Chromium: 106.0.5249.40 (Official Build) canary (64-bit) 
Revision	fab1d91915d2722d6339aaa7f4e9ce44f1e9b103-refs/branch-heads/5249@{#442}
OS	Android 12; Build/SP1A.210812.016
