### ISSUE TITLE
`Try Brave Search` translated text isn't confined within the button in search promo banner message

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#24005]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/23914
`Try Brave Search` translated text isn't confined within the button in the search promo banner message
## Steps to Reproduce

   1. Set OS locale to Germany/Kannada/Hindi/France
   2. Launch brave using `brave.exe --enable-features=BraveSearchOmniboxBanner`
   3. Change the search engine to other apart from brave
   4. Enter any text in the URL bar
   5. Search promo banner message is shown
   6. `Try Brave Search` translated text isn't confined within the button in search promo banner message

## Actual result:

`Try Brave Search` translated text isn't confined within the button in search promo banner message
![image](https://user-images.githubusercontent.com/38657976/178466500-6c651cce-c7bf-4d1c-8dd8-3482079e6d51.png)

## Expected result:
`Try Brave Search` translated text should be shown entirely within the button

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.41.96 Chromium: 103.0.5060.114 (Offizieller Build) (64-Bit)
-- | --
Überarbeitung | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
Betriebssystem | Windows 10 Version 21H2 (Build 19044.1806)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? NA

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @mkarolin @rebron @brave/qa-team

**Comment by kjozwiak** [comment]
The above will require `1.42.67` or higher for `1.42.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.42.67 Chromium: 103.0.5060.114 (Official Build) beta (x86_64)
-- | --
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | macOS Version 13.0 (Build 22A5295i)


### Steps:
1. set OS locale to Germany, France (couldn't reproduce the search banner in Hindi and Kannada)
2. launched Brave using `--enable-features=BraveSearchOmniboxBanner`
3. changed the search engine to `DuckDuckGo`
4. entered `basic attention token` in the URL bar
5. search promo banner message is shown

Confirmed the translated `Try Brave Search...` text fits the button in the following locales:

`German` | `French`
----------|---------
<img width="1257" alt="Bildschirm­foto 2022-07-15 um 12 39 16" src="https://user-images.githubusercontent.com/387249/179301998-ead8d925-8692-4396-84ec-005ceca4ef13.png"> | <img width="1257" alt="Capture d’écran 2022-07-15 à 12 44 16" src="https://user-images.githubusercontent.com/387249/179302012-fbda1846-8bbb-40fe-8c82-31534d10cc0a.png">
