### ISSUE TITLE
Few strings are not translated in content filtering screen

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#24004]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/23914

Few strings are not translated in content filtering screens

## Steps to Reproduce

   1. Set OS locales to Kannada/Germany/Hindi/France
   2. Open brave://settings/shields/filters
   3. Few strings `Filter lists`, `Content filters`, and  `Show full list` are not translated in other locales

## Actual result:

**_Germany_**

![image](https://user-images.githubusercontent.com/38657976/178463879-ed32c82c-c4c6-4e83-8a63-d7ea0312f161.png)

## Expected result:

Strings should be translated

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.41.96 Chromium: 103.0.5060.114 (Offizieller Build) (64-Bit)
-- | --
Überarbeitung | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
Betriebssystem | Windows 10 Version 21H2 (Build 19044.1806)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? NA

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @mkarolin @rebron @brave/qa-team

**Comment by mkarolin** [comment]
cc: @nullhook

**Comment by kjozwiak** [comment]
The above requires `1.45.104` or higher for `1.45.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.45.104 Chromium: 106.0.5249.126 (Official Build) beta (x86_64)
-- | --
Revision | fb2e06d2dee20fe0c804528502b5ad72c613abd9-refs/branch-heads/5249_118@{#3}
OS | macOS Version 12.6 (Build 21G115)
```
