### ISSUE TITLE
Show Solana network name on Portfolio fragment and remove the hardcoded network utility method/usage

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#24011]
## Description 

- [ ] Show solana network on Portfolio screen 
- [ ] Show "Ethereum" for "Ethereum Mainnet" instead of "Mainnet" on network selector 
- [ ] Refactor code to get the short network name dynamically and remove hard-coded implementation

## Actual result 
Solana network is not being shown when selected

## Expected result
Should show solana when selected 

![Screenshot from 2022-07-12 17-08-46](https://user-images.githubusercontent.com/11755381/178481556-68e2b7db-8260-44f8-a948-24d724e9038f.png)

## Issue reproduces how often 
Easy

**Comment by kjozwiak** [comment]
The above will require `1.42.76` or higher for `1.42.x` verification 👍

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/23647#issuecomment-1195558468
