### ISSUE TITLE
Rename `Wallet Payment ID` to `Rewards Payment ID` 

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#24017]
## Description

Replace all instances of "Wallet Payment ID" with "Rewards Payment ID" in visible contexts, such as brave://rewards-internals.  

cc: @brave/user-support-team

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.43.56 Chromium: 104.0.5112.81 (Official Build) dev (x86_64)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | macOS Version 11.6.8 (Build 20G730)

### Steps:
1. installed `1.43.56`
2. launched Brave
3. enabled Rewards
4. opened `brave://rewards-internals`

Confirmed the following string changes:
* `Wallet info` -> `Rewards info`
* `Wallet payment ID` -> `Rewards payment ID`
* `Wallet created at` -> `Rewards profile created at`

1.43.56 | 1.42.86
--------|--------
<img width="1213" alt="Screen Shot 2022-08-03 at 11 09 16 AM" src="https://user-images.githubusercontent.com/387249/182679112-c1d00156-98cd-4fec-b5ca-5e70af92d316.png"> | <img width="1312" alt="Screen Shot 2022-08-03 at 11 09 40 AM" src="https://user-images.githubusercontent.com/387249/182679067-2f2c1f1e-0866-4b8a-9080-20394040629b.png">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.43.58 Chromium: 104.0.5112.81 (Official Build) beta (64-bit)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | Windows 11 Version 21H2 (Build 22000.795)
```

1. installed `1.43.58`
2. launched Brave
3. enabled Rewards
4. opened `brave://rewards-internals`

#### Confirmed the following string changes:
* `Wallet info` -> `Rewards info`
* `Wallet payment ID` -> `Rewards payment ID`
* `Wallet created at` -> `Rewards profile created at`
* `Wallet status` -> `Rewards state`

1.42.86|1.43.58
-----|-----
<image width = "850" alt="image" src="https://user-images.githubusercontent.com/98358127/182921170-8f4d55e0-5835-4675-b16f-8948de384898.png">|<image width = "850" alt="image" src="https://user-images.githubusercontent.com/98358127/182921220-a95bdfee-e987-4c07-9ced-12d840a34b18.png">

**Comment by Uni-verse** [comment]
Verified on `Samsung GS 21` & `Samsung Galaxy Tab S7` using

```
Brave	1.43.74 Chromium: 104.0.5112.102 (Official Build) beta (64-bit) 
Revision	8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}
OS	Android 12; Build/SP1A.210812.016
```
- Confirmed the following string changes in the brave://rewards-internals under General info (Replacing "Wallet" with "Rewards")

- [x] Wallet info -> Rewards info
- [x] Wallet payment ID -> Rewards payment ID
- [x] Wallet created at -> Rewards profile created at
- [x] Wallet status -> Rewards state

Mobile | Tablet 
-|-
![screenshot-1660862361410](https://user-images.githubusercontent.com/17885425/185507725-9c00dcb0-2f1e-49ab-b3ec-7bc197089a4e.png) | ![screenshot-1660862577405](https://user-images.githubusercontent.com/17885425/185507879-b4ae8d1a-8d41-403c-83c6-ec3508084e78.png)
1.42.x (Mobile) | 1.42.x (Tablet)
![screenshot-1660862882096](https://user-images.githubusercontent.com/17885425/185508428-a3526182-81d8-4898-803b-7ad0a79aa0bf.png) | ![screenshot-1660862865221](https://user-images.githubusercontent.com/17885425/185508426-253622be-21c9-47a7-bf03-9b929ae078cf.png)
