### ISSUE TITLE
Audit (and fix) rewards code for casting of int64_t to int.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#24015]
In `Chromium 104` the `base::DictionaryValue::SetXXX` APIs have been deprecated and we transitioned to using `base::Value::Dict` instead that has an overloaded `Set` method.

In rewards code, there are multiple places where `int64_t` data types were stored in various `base::DictionaryValue`s using the `SetInteger` method, which would implicitly cast `int64_t` to `int`. With the new `base::Value::Dict` we had to explicitly specify static_cast<int> because the overloaded `Set` methods couldn't match the `int64_t` type. Obviously, all these casts can lead to data loss, so rewards code needs to be audited for such occurrences and fixed up either by using double as suggested by @zenparsing or by using string types for things like date/time as suggested by @cdesouza-chromium. 

Specific locations for casts:
`browser/extensions/api/brave_rewards_api.cc`
`browser/ui/webui/brave_rewards_internals_ui.cc`
`browser/ui/webui/brave_rewards_page_ui.cc`
`components/brave_rewards/browser/rewards_notification_service_impl.cc`

cc: @zenparsing @cdesouza-chromium

**Comment by cdesouza-chromium** [comment]
It seems to me that most of these conversions are used to store a timestamp. I have recently come across code that seems to need such reviewing.

Take for instance the following code

```
double ChromeImporter::chromeTimeToDouble(int64_t time) {
  return ((time * 10 - 0x19DB1DED53E8000) / 10000) / 1000;
}
```

Which gets used like this:

```
base::Time::FromDoubleT(chromeTimeToDouble(std::stoll(date_added)));
```

This doesn't seems to be the correct way of approaching how to store these time stamps. For the case above, we possibly should be doing something like the following:

```  SaveToDatabase(last_updated.ToDeltaSinceWindowsEpoch().InMicroseconds());

  // Deserialization:
  base::Time last_updated = base::Time::FromDeltaSinceWindowsEpoch(
    base::Microseconds(LoadFromDatabase()));
```
