### ISSUE TITLE
Aurora Mainnet uses Ethereum Asset icon

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#24024]
## Description 

Aurora Mainnet uses Ethereum Asset icon

## Steps to Reproduce

   1. Install latest nightly
   2. Create wallet
   3. Aurora mainnet is using Ethereum icon rather than the native network icon

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/178653476-85215b06-b66b-45ca-b695-f04ceaf61fbb.png)

## Expected result:
Similar to the one in `https://aurora.dev`
![image](https://user-images.githubusercontent.com/17010094/178653877-3215d68d-6485-4d09-b6f2-7bade30402e4.png)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html><head></head>
<body>

Brave | 1.43.17 Chromium: 103.0.5060.114 (Official Build) nightly (64-bit)
-- | --
Revision | `a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}`
OS | Windows 11 Version 22H2 (Build 22622.290)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @onyb @jamesmudgett @yrliou @supermassive

**Comment by yrliou** [comment]
Looks like UI code here https://github.com/brave/brave-core/blob/master/components/brave_wallet_ui/options/asset-options.ts#L20 might need some update? cc @onyb @Douglashdaniel

**Comment by Douglashdaniel** [comment]
If this is actually supposed to represent `Aurora` the token https://www.coingecko.com/en/coins/aurora-near then this should be adjusted in our network list to not be returned as `ETH`. Why is it being returned as `ETH` for this network? The price is not going to be correct either.

**Comment by onyb** [comment]
The native asset of Aurora is `ETH`, but the asset icon will be different. We need to add a case for Aurora here https://github.com/brave/brave-core/blob/master/components/brave_wallet_ui/options/asset-options.ts#L20 right after Optimism.

Logo is here: https://aurorascan.dev/images/svg/brands/mainbrand-1.svg

**Comment by kjozwiak** [comment]
The above will require `1.42.66` or higher for `1.42.x` verification 👍

**Comment by srirambv** [comment]
<table>
   <tr>
      <th>Brave</th>
      <th colspan="3">1.42.80 Chromium: 104.0.5112.57 (Official Build) (64-bit) </th>
   </tr>
   <tr>
      <th>Revision</th>
      <th colspan="3"><code>212fd173a0da1e0a024f328295bb56a2529190bb-refs/branch-heads/5112@{#1042}</code></th>
   </tr>
   <tr>
      <th>OS
      </th>
      <th>:ballot_box_with_check: Linux</th>
      <th>:ballot_box_with_check: Windows 11 Version 21H2
         <br/> (Build 22000.708)
      </th>
      <th>:ballot_box_with_check: macOS Version 12.0.1
         <br/> (Build 21C52)
      </th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td colspan=4>
         <ul>
         <li>Verified asset icon is updated</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>
      </td>
      <td><img width=1200 src=https://user-images.githubusercontent.com/17010094/181492897-acad6242-4113-4368-bfea-d0af66adb995.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/181493039-056f3226-d0b4-48d8-ac55-4712fdab714f.png>
      </td>
      <td><img width=1000 src=https://user-images.githubusercontent.com/17010094/181493177-d81ed4eb-50ab-4565-ab9c-e194c326caa3.png>
      </td>
   </tr>
</table>
