### ISSUE TITLE
Add user pref for debouncing feature (Desktop)

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#24020]
Add a new pref to control debouncing to brave://settings/shields. Currently we only have a flag in brave://flags for debouncing.

Setting label: `Auto-redirect tracking URLs`
Sublabel: `Enable support for bypassing top-level redirect tracking URLs. Learn More`. Learn more points to https://brave.com/privacy-updates/11-debouncing/ 

Note that De-AMP related debouncing (e.g. debounce AMP cache URLs) would depend on both this new Debounce setting (to debounce at all) and the De-AMP setting prescribed by the `pref` key in `debounce.json`, support for which was added in https://github.com/brave/brave-browser/issues/23121.

**Comment by LaurenWags** [comment]
@ShivanKaul is using https://dev-pages.brave.software/navigation-tracking/debouncing.html sufficient for testing the pref on/off setting?

cc @brave/qa-team

**Comment by ShivanKaul** [comment]
Yeah that makes sense. Also apologies, this should be Desktop and Android, I updated the PR but forgot to update the issue.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.48.129 Chromium: 109.0.5414.87 (Official Build) beta (64-bit)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | Windows 11 Version 21H2 (Build 22000.1455)
```

1. Install 1.48.129 
2. launch Brave
3. navigate to `brave://settings/shields`
4. confirmed `Auto-redirect AMP pages` setting is enabled as a default
5. confirmed `Enable support for bypassing top-level redirect tracking URLs. Learn more` sub label text is displayed
6. clicked on `Learn more`, navigated to  https://brave.com/privacy-updates/11-debouncing/
7. visit https://dev-pages.brave.software/navigation-tracking/debouncing.html
8. click Run for all the condition

step 4-5|step 6|step 8
-----|------|-------
<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/212978749-c39bc9a9-eeb2-4917-a86b-ad0c19b6264f.png">|<img width="462" alt="image" src="https://user-images.githubusercontent.com/98358127/212979468-5b4cfa90-ae89-4038-a9a0-3e298192ad90.png">|<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/212980194-50df96f9-dcb4-47e9-ae12-1f9fa7b05345.png">

**Comment by stephendonner** [comment]
Verification `IN-PROGRESS` using



Brave | 1.48.129 Chromium: 109.0.5414.87 (Official Build) beta (x86_64)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | macOS Version 11.7.2 (Build 20G1020)



Case 1:  Enable `Auto-redirect tracking URLs`  - `PASSED`
<details>

1. Install 1.48.129 
2. launch Brave
3. navigate to `brave://settings/shields`
4. confirmed `Auto-redirect tracking URLs` setting is toggled `On/Enabled` as a default
5. confirmed `Enable support for bypassing top-level redirect tracking URLs.' sub label text with  Learn more` more link displayed
6. clicked on `Learn more`, navigated to  https://brave.com/privacy-updates/11-debouncing/
7. visit https://dev-pages.brave.software/navigation-tracking/debouncing.html
8. click Run for all the conditions (Default, Base 64, Regex & Regex (multi)
9. click other site and Run the same conditions

Confirmed redirecting worked as expected with `Auto-redirect tracking URLs` default setting 

steps 4-5 | step 6 | step 8 | step 9
-----|------|-------|--------
<img width="1138" alt="Screen Shot 2023-01-17 at 5 50 25 PM" src="https://user-images.githubusercontent.com/387249/213062334-a239128d-07d9-45a9-a69c-203cd8f81f50.png"> | <img width="1138" alt="Screen Shot 2023-01-17 at 5 50 17 PM" src="https://user-images.githubusercontent.com/387249/213062376-f368b26f-448b-4c19-b1ae-6b2012d59495.png"> | <img width="1138" alt="Screen Shot 2023-01-17 at 5 53 30 PM" src="https://user-images.githubusercontent.com/387249/213062408-0413f7c2-3149-48da-a306-884d93d5557f.png"> | <img width="1138" alt="Screen Shot 2023-01-17 at 5 56 21 PM" src="https://user-images.githubusercontent.com/387249/213062411-fb940e87-0b5e-480b-86da-a604d0b9054e.png">




</details>

Case 2: Disable `Auto-redirect tracking URLs` 
<details>

1. Continue from Case 1:
    - `Auto-redirect tracking URLs` setting in `brave://settings/shields` enabled
2. disable  `Auto-redirect tracking URLs` setting
3. Toggled `Auto-redirect tracking URLs` to `Off/Disabled` via `brave://settings/shields`
4. visit https://dev-pages.brave.software/navigation-tracking/debouncing.html
5. click Run for `Default` condition

Confirmed redirecting didn't work with disabling `Auto-redirect tracking URLs` pref

step 2 | step 3 | step 4 | ex| ex
-----|----|-----|---|----

</details>

**Comment by stephendonner** [comment]
## Verified `PASSED` using `1.48.134` on a `Google Pixel XL` (`arm64`) running `Android 9`

#### Shared steps:

1. installed `1.48.134`
2. launched Brave
3. tapped to set/unset the respective value for `Auto-redirect tracking URLs` in `Brave Shields & privacy`
4. loaded `https://dev-pages.brave.software/navigation-tracking/debouncing.html`
5. clicked on each of the `Run` buttons
6. (continue with each case)

### Case 1: Enable `Auto-redirect tracking URLs` (default) - `PASSED`


`observed referrer` | `Auto-redirect...` ENABLED
--------------------|---------------------------
![Screenshot_20230122-023106](https://user-images.githubusercontent.com/387249/213911675-0c78bff6-5b70-495a-9455-08a800b1db3e.png) | ![Screenshot_20230122-023130](https://user-images.githubusercontent.com/387249/213911676-11127598-9043-4830-ac27-6f679ad784c2.png) | ![Screenshot_20230122-023310](https://user-images.githubusercontent.com/387249/213911700-35899642-810a-49f7-b015-2f6d85687f3b.png) | ![Screenshot_20230122-023506](https://user-images.githubusercontent.com/387249/213911702-7d4205af-7e75-4dca-8b14-abba8f5da023.png) 



### Case 2: Disable `Auto-redirect tracking URLs` - `PASSED`

`observed referrer` | `Auto-redirect...` DISABLED
--------------------|---------------------------
![Screenshot_20230122-023310](https://user-images.githubusercontent.com/387249/213912201-12abc948-708e-47a1-82a9-0868e75fa4ee.png) | ![Screenshot_20230122-023506 (1)](https://user-images.githubusercontent.com/387249/213912210-a8d312dc-049c-4159-bd08-1f8c3ab58069.png)

Results for each `Run`-button press

`default` | `base64` | `regex` | `regex (multi)`
-----------|-----------|------------|-----------
| ![Screenshot_20230122-023200](https://user-images.githubusercontent.com/387249/213911747-b3b86ed6-0a04-48b4-a027-2e4eb1c5c7ad.png) | ![Screenshot_20230122-023208](https://user-images.githubusercontent.com/387249/213911749-664e7134-ec87-4210-a16a-39b32f2fcadb.png) | ![Screenshot_20230122-023218](https://user-images.githubusercontent.com/387249/213911750-c5bcfed4-fea1-4bfb-8d96-23152d79fc15.png) | ![Screenshot_20230122-023226](https://user-images.githubusercontent.com/387249/213911751-f9703134-5b0a-4527-aaed-c738d99c9f35.png)

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using 
```
Brave | 1.48.140 Chromium: 109.0.5414.119 (Official Build) beta (64-bit)
-- | --
Revision | 772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}
OS | Linux
```

#### Case 1:  Enable `Auto-redirect tracking URLs`  - `PASSED`
<details>

1. Install 1.48.129 
2. launch Brave
3. navigate to `brave://settings/shields`
4. confirmed `Auto-redirect tracking URLs` setting is toggled `On/Enabled` as a default
5. confirmed `Enable support for bypassing top-level redirect tracking URLs.' sub label text with  Learn more` more link displayed
6. clicked on `Learn more`, navigated to  https://brave.com/privacy-updates/11-debouncing/
7. visit https://dev-pages.brave.software/navigation-tracking/debouncing.html
8. click Run for all the conditions (Default, Base 64, Regex & Regex (multi)
9. click other site and Run the same conditions

#### Confirmed redirecting worked as expected with `Auto-redirect tracking URLs` default setting 

step 4-5|step 6|step 8|step 9
-----|------|-------|--------




</details>

#### Case 2: Disable `Auto-redirect tracking URLs` -  `PASSED`
<details>

1. Continue from Case 1:
    - `Auto-redirect tracking URLs` setting in `brave://settings/shields` enabled
2. disable  `Auto-redirect tracking URLs` setting
3. Toggled `Auto-redirect tracking URLs` to `Off/Disabled` via `brave://settings/shields`
4. visit https://dev-pages.brave.software/navigation-tracking/debouncing.html
5. click Run for `Default` condition

#### Confirmed redirecting didn't work with disabling `Auto-redirect tracking URLs` pref

step 2|step 3|step 4|ex|ex
-----|----|-----|---|----




</details>
