### ISSUE TITLE
VPN logged-in environment should be cached between browser restarts

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#24033]
## Description 

VPN logged-in environment should be cached between browser restarts

## Steps to Reproduce

   1. Launch Brave Nightly 
   2. Log into VPN Dev environment
   3. Click on Refresh Brave VPN if already have loaded credentials else perform purchase flow
   4. VPN shows connect state
   5. Quit Brave
   6. Relaunch Brave, click VPN goes back to opt-in state

## Actual result:

Browser relaunch causes VPN to go to opt-in state 

## Expected result:
Should cache the environment details so when browser is launched shouldn't go back to opt-in state

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.43.17 Chromium: 103.0.5060.114 (Official Build) nightly (x86_64 translated)
-- | --
Revision | `a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}`
OS | macOS Version 12.4 (Build 21F79)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

More discussion here https://bravesoftware.slack.com/archives/CC5SA8CCB/p1657696282138699
cc: @simonhong @spylogsster @bsclifton @brave/legacy_qa

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.43.73 Chromium: 104.0.5112.81 (Official Build) beta (x86_64)
--|--
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | macOS Version 11.6.8 (Build 20G730)

### Steps:
1. installed `1.43.65`
2. launched Brave
3. opened `brave://flags/`
4. toggled `Enable experimental Brave VPN` to `Enabled`
5. toggled `Enable experimental SKU SDK` to `Enabled`
6. restarted Brave
7. loaded `account.bravesoftware.com`
8. entered basic auth
9. entered `issue24033@mailinator.com` and clicked `Get login link`
10. clicked on the link in the email
11. clicked on `Browse plans`
12. scrolled down and clicked on `Buy now` for Brave VPN
13. completed the Stripe checkout
14. connected to VPN
15. closed all browser windows
16. relaunched Brave
17. checked for updates
18. let Brave update itself to `1.43.73`
19. confirmed I was (still) connected to VPN
20. relaunched Brave
21. checked VPN-connection status


#### Confirmed I was still connected to VPN


![issue24033](https://user-images.githubusercontent.com/387249/185244729-cbee0c18-e95e-44c5-a59f-54e56088aeee.gif)

**Comment by MadhaviSeelam** [comment]
Brave | 1.43.73 Chromium: 104.0.5112.81 (Official Build) beta (64-bit)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | Windows 11 Version 21H2 (Build 22000.856)


Reproduced the issue in `1.43.17`
 ![image](https://user-images.githubusercontent.com/98358127/185248613-5e65a6bf-be34-4599-a3d8-cef53082f1da.png)


1. installed `1.43.73`
2. launched Brave
3. opened `brave://flags/`
4. toggled `Enable experimental Brave VPN` to `Enabled`
5. toggled `Enable experimental SKU SDK` to `Enabled`
6. restarted Brave
7. loaded `account.bravesoftware.com` (staging)
8. enter credentials from 1Password
9. enter a unique test email address (e.g. vpn-test-0823@mailinator.com) and click Get login link
10. clicked on the link in the email
11. clicked on `Browse plans`
12. scrolled down and clicked on `Buy now` for Brave VPN
13. completed the Stripe checkout
14. connected to VPN
15. closed all browser windows
16. confirmed I was (still) connected to VPN
17. relaunched Brave
18. checked VPN-connection status

####Confirmed still connected to VPN after relaunching Brave

Ex1|Ex2
---|---
<image width="900" alt="image" src="https://user-images.githubusercontent.com/98358127/185248216-e2d690b7-941e-431c-bad7-58c2d2de5c65.png">|<image width="900" alt="image" src="https://user-images.githubusercontent.com/98358127/185248062-335e6922-377b-4675-954b-b474b743821b.png">

**Comment by srirambv** [comment]
Just adding a note that its working fine on the same profile that was used to report the issue. VPN isn't returned back to opt-in screen and stays connected.
