### ISSUE TITLE
Create ledger APIs to handle mobile adaptive captcha attestation

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-browser#24044]
## Description 

For Android & iOS it would be helpful to have functions that handle adaptive captcha network requests and setup similar to claiming & attesting promotions seen here: [ClaimPromotion](https://github.com/brave/brave-core/blob/master/vendor/bat-native-ledger/include/bat/ledger/ledger.h#L203) and [AttestPromotion](https://github.com/brave/brave-core/blob/e6bd2be10bdf7582cb54639d8bbb208b8230f3d5/vendor/bat-native-ledger/include/bat/ledger/ledger.h#L225)

You can find how iOS sets up this flow calling these APIs here: https://github.com/brave/brave-ios/blob/9b269a0b4512412b8140aa5d6b4a3338954b36b3/Client/Extensions/Rewards/BraveLedgerExtensions.swift#L160

The steps are essentially:
- Ensure the device is enrolled
- Generate public key hash from the private key
- Call `ClaimPromotion` with it and get back a nonce
- Create a solution based on the nonce, signature and blob
- Attest the promotion using that solution by calling `AttestPromotion`

The APIs around adaptive captcha solving would likely be similar

**Comment by emerick** [comment]
For the time being, the iOS team will implement these calls directly in the iOS client as that's the path of least resistance. We'll chat with the iOS team to see what we can do to make using the BraveAdaptiveCaptchaService via iOS simpler in the future.
