### ISSUE TITLE
`Manage Subscription` link in about VPN dialog shouldn't open multiple tabs

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#24048]
## Description 

`Manage Subscription` link in about VPN dialog shouldn't open multiple tabs

This is essentially just https://github.com/brave/brave-browser/issues/23100; it wasn't fixed fully there, but is better, now.  New windows still suffer from the same issue, but the original window looks to be working (doesn't open new tabs)

## Steps to Reproduce

   1. install `1.43.20`
   2. launch Brave
   3. set up VPN via `account.brave.software`
   4. once logged in, click on the `VPN` button in the toolbar
   5. click on the "gear" / `Settings` icon
   6. now click on `Manage subscription`
   7. note it opens a new tab
   8. click again on `Manage subscription`
   9. if the above doesn't reproduce the issue, open a new window (not tab), and then click on `Manage subscription` from that flow
  
## Actual result:

Keeps opening new tabs for the `Manage subscription` link; not that the `About Brave Firewall & VPN` link in the same dialog is fine (only opens one tab).  Looks like the single-tab logic only works for the original tab

![vpn-issue](https://user-images.githubusercontent.com/387249/178789813-8959b19e-3827-458d-88cb-1d12c83ff5c2.gif)

## Expected result:
Only opens one tab

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.43.20 Chromium: 103.0.5060.114 (Official Build) nightly (x86_64)
-- | --
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | macOS Version 11.6.7 (Build 20G630)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

cc @srirambv @spylogsster

**Comment by GeetaSarvadnya** [comment]
The issue is partially fixed, it's still reproducible in certain cases like close the subscription tab (if it already opned) click on `Manage Subscription` will open in a new tab, multipl clickson it will open multiple tabs with manage subsciption page


```
Brave | 1.43.51 Chromium: 104.0.5112.57 (Official Build) beta (64-bit)
-- | --
Revision | 212fd173a0da1e0a024f328295bb56a2529190bb-refs/branch-heads/5112@{#1042}
OS | Windows 10 Version 21H2 (Build 19044.1826)
```

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using

Brave | 1.44.70 Chromium: 105.0.5195.68 (Official Build) beta (64-bit)
-- | --
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | Windows 11 Version 21H2 (Build 22000.856)

Verified using original STR https://github.com/brave/brave-browser/issues/24048#issue-1303709135

Steps: 

   1. install `1.44.70
   2. launched Brave
   3. set up VPN via `account.bravesoftware.com`
   4. once logged in, clicked on the `VPN` button in the toolbar
   5. clicked on the "gear" / `Settings` icon
   6. clicked on `Manage subscription` link

#### Confirmed:
- if subscription page is already loaded, clicking `Manage Subscription` will not open to duplicate tabs
- if subscription page is not open, clicking `Manage Subscription` link will open to single tab as expected.

![2022-09-01_15h54_52](https://user-images.githubusercontent.com/98358127/188026135-ad920361-fdae-4516-9252-6917b1b080af.gif)

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.44.85 Chromium: 105.0.5195.127 (Official Build) beta (x86_64)
-- | --
Revision | 912488396852bf658ab32465980c0b93a3c27a83-refs/branch-heads/5195@{#1109}
OS | macOS Version 11.7 (Build 20G817)

![manage-subscription](https://user-images.githubusercontent.com/387249/190250171-98a5ca2e-8b9f-4ac6-8ac6-54be858ef743.gif)
