### ISSUE TITLE
Browser crashes in SolanaProviderImpl::SelectedAccountChanged when trying to remove selected Ledger Solana account 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#24046]
## Description 

Browser crashes when trying to Remove Ledger Solana account 

## Steps to Reproduce

   1. Clean install 1.43.20
   2. Create wallet account and connect Ledger
   3. Import Solana Account from Ledger
   4. Exit Solana App on Ledger or Disconnect Ledger device
   5. Delete Ledger entry under Secondary Accounts
   6. Browser crash

## Actual result:

https://user-images.githubusercontent.com/17010094/178779963-f24c06a8-fcaa-47d6-bb94-8a6ac47849e1.mp4

Crash report https://share.backtrace.io/api/share/BXms9JrVFuLr2tgRx3N3OG2

## Expected result:
No Crash 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.43.20 Chromium: 103.0.5060.114 (Official Build) nightly (64-bit) 
-- | --
Revision | `a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}`
OS | Windows 11 Version 21H2 (Build 22000.795)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @yrliou @supermassive @cypt4

**Comment by kjozwiak** [comment]
The above will require `1.42.67` or higher for `1.42.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.42.81 Chromium: 104.0.5112.69 (Official Build) (64-bit) 
-- | --
Revision | `7ce2902023c722af8564068e6b26e934b83fd774-refs/branch-heads/5112@{#1213}`
OS | Windows 11 Version 21H2 (Build 22000.795)

- Verified steps from [brave/brave-core#14164](https://github.com/brave/brave-core/pull/14164)
- Verified  no crash when removing the connected Ledger account


https://user-images.githubusercontent.com/17010094/182135179-ce5a4183-308e-45cb-bcd1-28cc059efb06.mp4
