### ISSUE TITLE
Ubuntu/Debian repository broken

### ISSUE THREAD

**Issue by scmart** [brave/brave-browser#2405]
Getting the following when attempting to update.

Err:8 https://brave-browser-apt-release.s3.brave.com xenial InRelease          
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0B31DBA06A8A26F9

**Comment by BallisticBuddha** [comment]
I've started to see this today, too (on Ubuntu bionic). I even tried re-running the key import with:
`curl https://s3-us-west-2.amazonaws.com/brave-apt/keys.asc | sudo apt-key add -`
but I'm still unable to update the package list due to a missing public key.

**Comment by 2bithacker** [comment]
I was having the same problem, the command in https://github.com/brave/brave-browser/issues/2405#issuecomment-445494542 fixed it for me. Thanks!

**Comment by tomlowenthal** [comment]
Looks like you're seeing this issue: https://github.com/brave/brave-browser/issues/1826#issuecomment-445948353 .
