### ISSUE TITLE
Add `Keep in dock` option to first run dialog and settings

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#24055]
## Description 
When user sets Brave as a default browser, "Keep Brave in dock" also.

## Steps to Reproduce

1.  Launch Brave with clean profile
2. Click `Set Brave as default` button after checking `Keep in dock`
3. Check Brave is added to dock
4. Load brave://settings/getStarted and check settings shows as `Brave is already in dock`
5. Unpin from taskbar and reload brave://settings/getStarted and click `Dock` button
6. Check Brave is added to dock

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

See related: https://github.com/brave/brave-browser/issues/24054

**Comment by sangwoo108** [comment]
I guess `chrome/browser/mac/dock.h` can be used for this

**Comment by bridiver** [comment]
after speaking to @rebron we should add a checkbox if you want to keep it in the dock (unchecked by default)

**Comment by bridiver** [comment]
same dialog ^^

**Comment by aguscruiz** [comment]
Design here
https://www.figma.com/file/tLXWGCpNoiJxDZDdpfordj/Desktop-Settings?node-id=2952%3A45315

![image](https://user-images.githubusercontent.com/15734630/191510699-8dcac08b-d741-4742-88ba-09f56e81e456.png)

**Comment by stephendonner** [comment]
> Design here https://www.figma.com/file/tLXWGCpNoiJxDZDdpfordj/Desktop-Settings?node-id=2952%3A45315
> 
> ![image](https://user-images.githubusercontent.com/15734630/191510699-8dcac08b-d741-4742-88ba-09f56e81e456.png)

The Figma assets are pretty clearly -- though labeled for `macOS` -- a `Windows` screenshot with a bit of `macOS` treatment.

@aguscruiz can you please confirm that https://github.com/brave/brave-core/pull/14714#issue-1344018951 is what's intended to be implemented, for macOS?  I'm 99% sure but want to be 110%; thanks.

cc: @LaurenWags

**Comment by kjozwiak** [comment]
The above requires `1.46.94` or higher for `1.46.x` verification 👍

**Comment by stephendonner** [comment]
## Verification `PASSED` using 



#### Prerequisite: make a non-Brave browser the system default via `Apple menu` -> `System Preferences...` -> `General` -> `Default web browser`
<details>

<img width="780" alt="Screen Shot 2022-11-03 at 1 52 02 PM" src="https://user-images.githubusercontent.com/387249/199831617-fcfa6ab0-3e0d-4edc-8554-5f5fa0ea710d.png">

</details>

#### Case 1: Pin Brave to dock via the `Pin to Dock` checkbox in the first-run dialog - `.`

<details>

1. installed `.`
2. launched Brave
3. checked the `Keep in Dock` checkbox
4. clicked on the `Set Brave as default` button
5. confirmed I got the `Do you want to change your default web browser to "Brave" or keep using "Firefox"?` dialog
6. clicked on `Use "Brave"`
7. confirmed Brave is kept in the dock
8. closed Brave
9. relaunched by clicking on the Brave icon in the dock
10. opened `brave://settings/getStarted`
11. confirmed `Brave is your default browser` text
12. confirmed `Brave is already in Dock` text

#### Confirmed Brave is successfully kept in the dock

step 3 | step 5 | step 7 | steps 11-12
-------|-------|-------|------------


</details>

#### Case 2: Unpin Brave from the dock and `Pin to Dock` it from `brave://settings/getStarted` - `.`
<details>

1. continued from `Case 1`, with Brave kept in the dock
2. context-clicked on Brave and chose `Options` -> `Keep in Dock`
3. reloaded `brave://settings/getStarted`
4. confirmed the `Dock` button beside `Keep in Dock` is clickable
5. clicked `Dock`
6. confirmed I now saw `Brave is already in Dock`
7. context-click on Brave

#### Confirmed Brave is docked and shows `Options` -> `Keep in Dock` enabled

step 4 | step 6 | step 7
-------|--------|------





</details>

#### Case 3: With `Pin to Dock` unchecked (default), click `Set Brave as default` on the first-run dialog - `.`
<details>

1. installed `.`
2. launched Brave
3. left `Keep in Dock` unchecked (default)
4. click `Set Brave as default` button
5. clicked `Use "Brave"` on the next dialog
6. clicked `Skip welcome tour`
7. opened `brave://settings/getStarted`
9. confirmed Brave is your default browser text is shown 
10. confirmed `Dock` button is shown in next to `Keep in Dock`
11. clicked on the `Dock` button
12. confirmed the `Dock` button on `brave://settings/getStarted` disappears
13. context-click on Brave 

#### Confirmed Brave is docked and shows `Options` -> `Keep in Dock` enabled

step 4 | step 5 | step 8-9 | step 11 | step 12
-------|-------|----------|--------|--------





</details>

#### Case 4: `Pin to Dock` Brave via `brave://settings/getStarted` when a non-Brave browser is set as default via `Apple menu`' -> `System Preferences` -> `General` `Default web browser` - `.`
<details>

1. installed `.`
2. launched Brave
3. clicked `Maybe later`
4. clicked `Skip welcome tour`
5. closed Brave
6. relaunched Brave
7. clicked on `Set as default` in the infobar
8. clicked on `Use "Brave"`
9. opened `brave://settings/getStarted`
10. confirmed it read `Brave is your default browser`
11. confirmed the `Dock` button is enabled
12. clicked on the `Dock` button
14. confirmed the `Dock` button disappeared
15. confirmed it read `Brave is already in Dock`
16. context-clicked Brave

#### Confirmed Brave is docked and shows `Options` -> `Keep in Dock` enabled

step 3 | step 7 | step 8 | steps 10-11 | steps 13-14 | step 15
-------|-------|--------|-------------|------------|--------









</details>

#### Case 5: Upgrade from `1.46.x (nightly)` -> `1.47.x (nightly)` - `.`
<details>

1. installed `1.46.46`
2. launched Brave
3. clicked `Set Brave as default` on the first-run dialog
4. clicked `Use "Brave"`
5. opened `brave://settings/getStarted` and confirmed it shows `Brave is your default browser text`
6. upgraded to ``
7. opened `brave://settings/getStarted`
8. clicked the `Dock` button
9. confirmed the `Dock` button disappeared, and the text now reads "Brave is already in Dock`
10. context-clicked Brave

#### Confirmed Brave is docked and shows `Options` -> `Keep in Dock` enabled

step 3 | step 4 | step 5 | step 8 | step 9 | step 10
-------|--------|-------|-------|-------|--------




</details>
