### ISSUE TITLE
Incorrect response value for new user returning wallet usage pings 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#24058]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/23463
Incorrect response value for new user returning wallet usage pings 

"As a first time user of Brave Wallet this week, did I return again to use it during the week?"
`Brave.Wallet.NewUserReturning`

0) I have never used Brave Wallet
1) I have used Brave Wallet, but I'm not a first time Brave Wallet user this week
2) I'm a first time Brave Wallet user this week but, no, I did not return the rest of the week
3) I'm a first time Brave Wallet user this week and, yes, I returned and used it again the following day
4) I'm a first time Brave Wallet user this week and, yes, I returned and used it again this week but not the following day

## Steps to Reproduce

1.  Clean profile 1.42.x
2. Create a wallet today (14th July)
3. Open the brave://local-state file and ensured that the metrics `Brave.Wallet.NewUserReturning` response value is `2`
4. Close the browser and set the system clock ahead by one day (15th July)
5. Relaunch the browser
6. Unlock the wallet
7. Reload the brave://local-state file 
8. The metrics response value is `3` as expected
9. Close the browser and set the system clock to 18th July (the first day of the next week)
10. Repeat steps 5 and 6
11. Reload the brave://local-state file 
12. if a week is from  the day wallet is created then it's `4` if a week is from Monday to Sunday then it should be `1` but the response is `3`
 

## Actual result:

Incorrect response value for new user returning wallet usage pings 

## Expected result:
if a week is from  the day wallet is created then it's `4` if a week is from Monday to Sunday then it should be `1`

## Reproduces how often: 

100%
## Brave version (brave://version info)

Brave | 1.42.65 Chromium: 103.0.5060.114 (Official Build) beta (64-bit)
-- | --
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | Windows 10 Version 21H2 (Build 19044.1826)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @DJAndries @mattmcalister

**Comment by GeetaSarvadnya** [comment]
The issue is reproducible on `Samsung Galaxy Tab A7 version 11` running `Bravemonoarm.apk_1.42.80`

**Comment by DJAndries** [comment]
Renamed the question to "As a first time user of Brave Wallet this week, did I return again to use it during the first 7 day period?". Should work as expected with this definition.

**Comment by GeetaSarvadnya** [comment]
Verified the STR again and ensured that the reposnse value is `1` ( `I have used Brave Wallet, but I'm not a first time Brave Wallet user this week`) in step 12 as expected. Thanks @DJAndries
