### ISSUE TITLE
Pin to taskbar when user sets Brave as a default browser

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#24054]
## Description

When user set Brave as a default browser, pin Brave to taskbar also.

## Steps to reproduce

1. With clean profile scenario 1:
    1. Launch with clean profile
    2. Agree to set as a default browser
    3. Check brave is also pinned to taskbar - [ ]  https://github.com/brave/brave-browser/issues/24241

    4. Set another browser as a default browser via system preferences
    5. Unpin Brave from taskbar
    6. Set Brave as a default from settings
    7. Check brave is pinned again to taskbar - [ ] https://github.com/brave/brave-browser/issues/24509

2. With clean profile scenario 2:
   1. Launch with clean profile
   2. Don't agree to set as a default browser
   3. Relaunch several times to make `Set Brave as your default browser` dialog
   4. Click `Set as default`  and check shortcut is pinned to taskbar - [ ] https://github.com/brave/brave-browser/issues/24696

~~5. With existing users and brave is already set as a default
    1. Launch Brave with existing profile and check it's pinned after this launching
    2. Terminate and unpin Brave from taskbar
    6. Launch Brave again and check it's not pinned - respect user's choice - [ ] https://github.com/brave/brave-browser/issues/24697~~

Above feature is disabled till we have checkbox  - [ ] https://github.com/brave/brave-browser/issues/24870

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

See related: https://github.com/brave/brave-browser/issues/24055

FF - https://github.com/mozilla/gecko-dev/blob/master/browser/components/shell/nsWindowsShellService.cpp

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.46.80 Chromium: 107.0.5304.68 (Official Build) beta (64-bit)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | Windows 11 Version 21H2 (Build 22000.1098)
```

Case 1:  Check `Pin to taskbar` check box and  click `Set  Brave as default` button on `first run dialog`
<details>

1. Install 1.46.80
2. launch Brave
3. check the check box for `Pin to taskbar` on `the first run dialog`
4. click `Set Brave as default` button
5. confirmed Brave browser is pinned to taskbar
6. closed the browser
7. relaunched by clicking the `Brave `icon pinned to taskbar
8. open `brave://settings/getStarted`
9. `Brave is your default browser` text is shown `brave://settings/getStarted`

#### Confirmed Brave is successfully pinned to taskbar

step 3-4|step 5|step 7|step 8-10
-----|-----|-----|----
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/98358127/198076387-964dfc94-dfa2-49fc-b9bb-68f5b6e83960.png">|<img width="900" alt="image" src="https://user-images.githubusercontent.com/98358127/198077941-2ee70e5d-0f98-4a95-baa1-83c86a771721.png">|<img width="900" alt="image" src="https://user-images.githubusercontent.com/98358127/198077992-4f41fec1-4562-49bf-8e25-6a5a280e6985.png">|<img width="1500" alt="image" src="https://user-images.githubusercontent.com/98358127/198078118-042fb1ce-60ec-495c-8b13-e7027d9cbd19.png">
</details>

Case 2:  Unpin the Brave from the taskbar and `Pin` it from `brave://settings/getStarted`
<details>

1. continue from Case 1
     - launch Brave 
     - Brave icon pinned to taskbar
2. unpin from taskbar and reload `brave://settings/getStarted`
3. `Pin` button is displayed 
4. click `Pin` button again
5. Brave is pinned to taskbar 

#### Confirmed `brave://settings/getStarted` page shows `Brave is already pinned` text

step 1|step 1|step 3|step 5
---|----|----|---
<img width="900" alt="image" src="https://user-images.githubusercontent.com/98358127/198153650-33a32dfa-723e-4809-a3fd-6d29ccfcc623.png">|<img width="700" alt="image" src="https://user-images.githubusercontent.com/98358127/198153686-393d156a-4b7f-4498-b2de-674fa1c06d07.png">|<img width="900" alt="image" src="https://user-images.githubusercontent.com/98358127/198154019-37fc3912-f290-4580-9573-71e1d54eea45.png">|<img width="684" alt="image" src="https://user-images.githubusercontent.com/98358127/198154062-ce3cc516-cbb6-45d6-a2ae-d398ee56729c.png">
</details>

Case 3:  Do not check `Pin to taskbar` check box but click `Set  Brave as default` button on `first run dialog`
<details>

1. new profile
2. unpin Brave if it's pinned to taskbar
3. launch Brave
4. do not check the check box for `Pin to taskbar` on `the first run dialog`
5. click `Set  Brave as default` button
8. click `Skip welcome tour`
9. Brave is not pinned to the taskbar
10. open `brave://settings/getStarted`
12. `Brave is your default browser` text is shown `brave://settings/getStarted`

#### Confirmed `Pin` button is shown  in `brave://settings/getStarted`

step 4-5|step 7|result
----|----|-----
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/98358127/198144265-318f49fa-0ff2-4da3-a89f-b506ce669073.png">|<img width="700" alt="image" src="https://user-images.githubusercontent.com/98358127/198147111-8f0510d8-69aa-4f54-a6db-cbb755716098.png">|<img width="1100" alt="image" src="https://user-images.githubusercontent.com/98358127/198147014-ad398add-ddf9-419d-b5da-f96d4d895fc6.png">
</details>

Case 4: Click `Pin` button in `brave://settings/getStarted`  when  non-Brave browser set as a default  
<details>

1. new profile
2. unpin Brave from taskbar if pinned to it
3. set `Firefox` a default browser
4. launch Brave
6. click (x) to close `the first run dialog`
8. click on `Skip welcome tour`
9. close the browser and relaunch browser
10.  tab page shows `Infobar` with `Set as default` button
11. close the browser relaunch the browser again
13. page shows `Infobar` with `Set as default` again
14. click `Set as default` button on the `Infobar`
15. `Infobar` gets dismissed
16. open `brave://settings/getStarted`
17. `Brave is your default browser` text is shown `brave://settings/getStarted`
18. `Pin` button is shown in `brave://settings/getStarted`
19. click on `Pin` button 

#### Confirmed Brave icon is pinned to taskbar

step 3|step 5|step 8|step 12|step 13-15|result
-----|------|-----|-----|------|---
<img width="900" alt="image" src="https://user-images.githubusercontent.com/98358127/198124594-ab5ffc8a-8351-4934-8463-ac9a35f8ff8e.png">|<img width="700" alt="image" src="https://user-images.githubusercontent.com/98358127/198125529-4dfdbfab-777e-464c-bf7e-a40b2231267b.png">|<img width="800" alt="image" src="https://user-images.githubusercontent.com/98358127/198126271-9e0e2e91-6745-47bd-922b-cb6d1d1901c2.png">|<img width="900" alt="image" src="https://user-images.githubusercontent.com/98358127/198129289-7c91b9a0-95fc-45e4-aa9e-6ac2cdfddcba.png">|<img width="900" alt="image" src="https://user-images.githubusercontent.com/98358127/198129485-2945d1fc-3731-4457-a36f-d46ef0dd8b18.png">|<img width="673" alt="image" src="https://user-images.githubusercontent.com/98358127/198153139-153bd39c-f410-4e45-8159-929e04e72fbf.png">
</details>

Case 5: click `x` on  `Infobar` to dismiss the `Infobar`  when  non-Brave browser set as a default 
<details>

1. new profile
2. unpin Brave if it's pinned to taskbar
3. launch Brave
4. click `x` to close first run dialog
5. click `Skip welcome tour`
6. close Brave and relaunch browser
8. click `x` on the `Infobar`
9. `Infobar` is dismissed
10. go to `brave://settings/getStarted`
11. click on `Pin` button 

#### Confirmed Brave icon is pinned to taskbar

step 4|step 7|step 8|step 9|result
----|-----|----|----|----
<img width="900" alt="image" src="https://user-images.githubusercontent.com/98358127/198157060-efbd9aa8-1c30-4f57-b273-b7177271b373.png">|<img width="460" alt="image" src="https://user-images.githubusercontent.com/98358127/198157628-68e8e7e6-8343-45ee-9737-ab5b5d7e4110.png">|<img width="464" alt="image" src="https://user-images.githubusercontent.com/98358127/198157655-43c6e714-1194-493d-8e48-802a10c9e07e.png">|<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/198157994-782b7cdd-b840-4c05-926f-0d88f1a35973.png">|<img width="687" alt="image" src="https://user-images.githubusercontent.com/98358127/198158076-ea998bc0-e662-464c-92f0-9ac4b9af5460.png">

</details>

Bugs filed:
* https://github.com/brave/brave-browser/issues/26301

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.46.91 Chromium: 107.0.5304.91 (Official Build) dev (x86_64)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | macOS Version 11.7.1 (Build 20G918)

Case 1: Pin Brave to dock via `Pin to taskbar` checkbox in the first-run dialog
Case 2: Unpin Brave from the dock and `Pin to taskbar` it from `brave://settings/getStarted`
Case 3: Leave `Pin to taskbar` unchecked, but click `Set Brave as default` on the first-run dialog
Case 4: Pin Brave via `brave://settings/getStarted` when non-Brave browser is set as default in macOS settings
Case 5: Upgrade from 1.45.x (beta) ---> 1.46.x (beta)

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```
Brave | 1.46.90 Chromium: 107.0.5304.91 (Official Build) beta (64-bit)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | Windows 10 Version 21H2 (Build 19044.2130)

```
