### ISSUE TITLE
Add NTP search promo P3A question

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#24065]
## Description 

Adding P3A question for the new tab page search promo (promo added in #23724):

Did the participant in Group C click on the promo and did they switch their default engine to Brave Search?
`Brave.Search.Promo.NewTabPage`

0) No, No
1) Yes, No
2) No, Yes
3) Yes, Yes

Will raise PR soon.

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```
Brave | 1.44.73 Chromium: 105.0.5195.68 (Official Build) beta (64-bit)
-- | --
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | Windows 10 Version 21H2 (Build 19044.1889)

```

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress on `Samsung Galaxy Tab A7 version 11` running `Bravemonoarmx64.apk_1.44.95`

**Comment by kjozwiak** [comment]
Going to remove the above as we've never implemented the Brave search promo via NTP on `Android`. Currently we only have search promo implemented in the omnibox as per https://github.com/brave/brave-browser/issues/24902. CCing @timchilds @anthonypkeane @bsclifton please correct me if I'm wrong.

Thanks for looking at this @GeetaSarvadnya, I should have read it closer before pinging you to take a look.
