### ISSUE TITLE
Adjust translate initialization timeouts

### ISSUE THREAD

**Issue by atuchin-m** [brave/brave-browser#24075]
With a slow network + our backend we have a change on getting timeout when initializing the translate engine at the first time. 
## Steps to Reproduce
   1.  Get a clean profile.
   2.  Enabled `brave-translate-go` flag
   3.  Open a foreign page
   4.  Open devtools, go to `Network` tab and enable `3G slow` throttling.
   5. Try to translate the page.
Note: the same profile can be reused if the http cache is cleaned.
 
## Actual result:
Translation error

## Expected result:
Translation succeed.

## Desktop Brave version:
Nightly 1.43.x

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.43.58 Chromium: 104.0.5112.81 (Official Build) beta (x86_64)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | macOS Version 11.6.8 (Build 20G730)

Followed the steps to reproduce using the inline testplan.

Confirmed I see the issue with `1.42.86` but not with `1.43.58`.

`aol.de:`

1.43.58 | 1.42.86
--------|--------
<img width="1312" alt="Screen Shot 2022-08-05 at 12 19 44 PM" src="https://user-images.githubusercontent.com/387249/183146405-22fcfbef-fd14-44ba-978c-32c4e5dfea9e.png"> | <img width="1312" alt="Screen Shot 2022-08-05 at 12 17 04 PM" src="https://user-images.githubusercontent.com/387249/183146457-c22f30b0-2b5f-4c99-b961-cc83acf629be.png">

**Comment by MadhaviSeelam** [comment]
@atuchin-m 

Validation is still  failing in `Win 11 x64`.  Still see translation error after enabling `3G slow` throttling.  It fails for the first time but works when I clicked `Try again` or reload the page.  @stephendonner  verified in `Windows` and confirmed the issue as well.

https://user-images.githubusercontent.com/98358127/185234243-a428f2a0-4622-4059-9929-68596ea97a46.mp4

**Comment by MadhaviSeelam** [comment]
QA Passing this issue as https://github.com/brave/brave-browser/issues/24777 is filed as a follow up.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.43.78 Chromium: 104.0.5112.102 (Official Build) beta (64-bit)
-- | --
Revision | 8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}
OS | Ubuntu 18.04 LTS

still reproducible, encountered https://github.com/brave/brave-browser/issues/24777

![image](https://user-images.githubusercontent.com/34715963/185972687-18b91150-d940-42b6-b042-2a590968a4ff.png)

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S 21` & `Samsung Galaxy Tab S7` using the following build:

```
Brave	1.43.74 Chromium: 104.0.5112.102 (Official Build) beta (64-bit) 
Revision	8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}
OS	Android 12; Build/SP1A.210812.016
```
- Able to still reproduce this using the following throttle settings, encountered https://github.com/brave/brave-browser/issues/24777
![Screen Shot 2022-08-23 at 10 41 30 AM](https://user-images.githubusercontent.com/17885425/186191495-164de1be-360b-4f66-8202-a601e3c217ac.png)


https://user-images.githubusercontent.com/17885425/186191195-3918d3e4-2239-4eab-a041-fbdb5e81106e.mp4
