### ISSUE TITLE
Can I connect built-in brave wallet of brave browser into Solana project? 

### ISSUE THREAD

**Issue by haodev007** [brave/brave-browser#24074]
https://github.com/solana-labs/wallet-adapter/issues/469

**Comment by darkdh** [comment]
Hi @haodev007,
Can you make sure you have solana account created and open the panel and click a solana account to make it selected?
 
For the selected part we have PR in progress to make it more frictionless 
https://github.com/brave/brave-core/pull/14135

**Comment by haodev007** [comment]
Hi @darkdh  Thanks for your reply!
But not sure what should I do correctly...
And also it means we cant connect brave wallet using wallet adapter?
Is there any Solana Dapp connected brave wallet and is working good?

**Comment by haodev007** [comment]
Is it in progress, now?

**Comment by darkdh** [comment]
You can use wallet adapter, you just need to setup Solana account properly before using it.
Navigate to brave://wallet/crypto/accounts/add-account/create/ and create a Solana account. 
After creation, open the panel and select Solana network
<img width="316" alt="Screen Shot 2022-07-16 at 17 22 05" src="https://user-images.githubusercontent.com/11330831/179375933-cbc5e1e6-847d-45dd-8d1f-95e25f19273d.png">
And select the account you just created like this
<img width="312" alt="Screen Shot 2022-07-16 at 17 23 28" src="https://user-images.githubusercontent.com/11330831/179375955-b7264499-3042-48a5-91f8-7af4a0475c41.png">

The auto selection after creation part is in progress, that is why you have to manually select it now.

**Comment by haodev007** [comment]
Ah, yes. it is. thank you very much @darkdh
