### ISSUE TITLE
Split out default wallet prefs for Ethereum and Solana

### ISSUE THREAD

**Issue by mirkoschubert** [brave/brave-browser#24079]
## Description 
If you set the Brave wallet as the default cryptocurrency wallet in v1.41.96 and have another Solana wallet extension such as the Phantom wallet installed, you can't connect to dApps with the 3rd party wallet, even if you didn't create any Solana account in the Brave wallet.

## Steps to Reproduce

   1. Install the latest Brave browser (v1.41.96) on macOS (not tested on Windows or Linux, but I suspect it would be the same result)
   2. Set up the Brave wallet **without** creating a Solana wallet
   3. Set the `Default Cryptocurrency Wallet` to `Brave Wallet` at brave://settings/wallet
   4. Install a 3rd party Solana wallet extension (tested with the Phantom wallet)
   5. Import or set up a Solana wallet in the Phantom wallet
   6. Try to connect to any dApp (tested with magiceden.io, solsea.io and others) with your Phantom wallet

## Actual result:
After trying to connect to a dApp with a 3rd party Solana Wallet (e.g. Phantom Wallet) nothing happens and the connection failed. In the console of the Dev Tools there is an error message:

```
Uncaught TypeError: Cannot redefine property: solana
```
<img width="1440" alt="screenshot 2022-07-15 at 12 54 45" src="https://user-images.githubusercontent.com/6443573/179230232-38dec21c-1dba-4508-a00c-a6f47e66a61a.png">

## Expected result:
The dApp should easily connect to the 3rd party Solana wallet extension even with the Brave Wallet as default wallet, if no Solana wallet was created in the Brave wallet.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
**Brave:** 1.41.96 Chromium: 103.0.5060.114 (Official Build) (x86_64)
**Revision:** a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
**OS:** macOS Version 12.4 (Build 21F79)

## Version/Channel Information:

- Can you reproduce this issue with the current release? **YES**
- Can you reproduce this issue with the beta channel? **UNTESTED**
- Can you reproduce this issue with the nightly channel? **UNTESTED**

**I didn't have any problems before the 1.41.96 release.**

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? **NO**
- Does the issue resolve itself when disabling Brave Rewards? **UNTESTED**
- Is the issue reproducible on the latest version of Chrome? **NO**

**The issue is only applicable if a Brave wallet is present.** I couldn't reproduce the issue with the Phantom extension in a private window, where the Brave wallet isn't enabled. On other browsers such as Chrome the issue doesn't appear.

## Explanation:
It seems that the Solana part of the Brave wallet interferes with 3rd party Solana wallet extensions. Even if no Solana wallet has been created within the Brave wallet the `window.solana` object will be written before any other Solana wallets.

**There is a temporary solution:** The user can always set the `Default cryptocurrency wallet` to `Brave Wallet (Prefer extensions)` at brave://settings/wallet. This fixes it for now.

But many users would update the Brave browser without knowing that something has changed and would get this issue instantly. They wouldn't think of changing this setting.

## Possible Solution:
With the default wallet set to `Brave Wallet`, but no Solana wallet created, the `window.solana` object shouldn't be written as well. So 3rd party Solana wallets would work as expected until the user creates or imports a Solana wallet within the Brave wallet.

Maybe you should also warn the user if changes like that wouldn't work with current setting after an update.

**Comment by srirambv** [comment]
cc: @darkdh

**Comment by srirambv** [comment]
Probable solution would be this #23898

**Comment by jamesmudgett** [comment]
@mirkoschubert could you share what you have set for "Default cryptocurrency wallet" in brave://settings/wallet?

**Comment by mirkoschubert** [comment]
@jamesmudgett Already did. 😄 I had `Brave Wallet` and fixed it with `Brave Wallet (Prefer extensions)` for the moment.

But that's the issue: If you have set it to `Brave Wallet`, but don't have a Solana account in the Brave wallet, it shouldn't interfere with extensions as well. Setting up the `window.solana` object without any need is the problem here. 😉

**Comment by jamesmudgett** [comment]
That's not the way defaults work ;) unless you mean we should break into more granular defaults like:

- Default Ethereum/EVM wallet 
- Default Solana wallet

**Comment by mirkoschubert** [comment]
@jamesmudgett Btw, it did work with Solana support and `Brave Wallet` as default before 😉 The issue just appeared in the last version when (Solana) dApp support was introduced to Brave.

But more granular defaults would fix the issue as well. 😊

**Comment by jamesmudgett** [comment]
![Screen Shot 2022-07-20 at 9 55 38 AM](https://user-images.githubusercontent.com/318119/180014228-7c1f80a0-703f-4449-95b1-fcf92ae5bc6a.png)

1. Create a new row with identical default wallet options.
2. Rename the two options @rmcfadden3 to confirm the text or offer up alternatives.

"Default Ethereum/EVM wallet"
"Default Solana wallet"

**Comment by rmcfadden3** [comment]
@jamesmudgett — no edits from me. your copy makes sense.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.43.81 Chromium: 104.0.5112.102 (Official Build) (64-bit)
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | Linux

- Verified steps from [brave/brave-core#14288](https://github.com/brave/brave-core/pull/14288)
- Verified there is an individual setting to set default wallet provider for Solana and Ethereum 
- Verified setting either/both of them to `Brave Wallet` or `None` triggers the default wallet notification in `brave://wallet`
- Encountered [#24932](https://github.com/brave/brave-browser/issues/24932)

Ethereum | Solana 
-- | --
![image](https://user-images.githubusercontent.com/17010094/186428991-4b0db10f-8e0e-4a70-ad2e-de6fd8e77cb7.png) | ![image](https://user-images.githubusercontent.com/17010094/186428764-d3212cdc-6fb1-4b33-93a7-f3ad770ab732.png) 

------------------------
Verification passed on

Brave | 1.43.81 Chromium: 104.0.5112.102 (Official Build) (64-bit)
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | Windows 11 Version 21H2 (Build 22000.795)

- Verified steps from [brave/brave-core#14288](https://github.com/brave/brave-core/pull/14288)
- Verified there is an individual setting to set default wallet provider for Solana and Ethereum 
- Verified setting either/both of them to `Brave Wallet` or `None` triggers the default wallet notification in `brave://wallet`
- Encountered [#24932](https://github.com/brave/brave-browser/issues/24932)

Ethereum | Solana 
-- | --
![image](https://user-images.githubusercontent.com/17010094/186430187-61fcd4ab-a290-41ca-8e35-46699f588de1.png) | ![image](https://user-images.githubusercontent.com/17010094/186430170-7f6c7389-fb08-4d37-a135-f5ca12cd656b.png)

------------------------
Verification passed on

Brave | 1.43.81 Chromium: 104.0.5112.102 (Official Build) (arm64)  
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [brave/brave-core#14288](https://github.com/brave/brave-core/pull/14288)
- Verified there is an individual setting to set default wallet provider for Solana and Ethereum 
- Verified setting either/both of them to `Brave Wallet` or `None` triggers the default wallet notification in `brave://wallet`
- Encountered [#24932](https://github.com/brave/brave-browser/issues/24932)

Ethereum | Solana 
-- | --
![image](https://user-images.githubusercontent.com/17010094/186426775-06457022-a0b9-4295-88bb-d2e70ca54101.png) | ![image](https://user-images.githubusercontent.com/17010094/186426908-3ab0793d-2b30-46bd-85e1-dd2755575b9b.png)
