### ISSUE TITLE
Update to native token when network is changed on Dapps Panel

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#24078]
## Description 
The same fix https://github.com/brave/brave-core/pull/14085 also needs to be applied on the panel as well as reported earlier and now.

- https://github.com/brave/brave-browser/issues/22572#issuecomment-1171468980
- https://community.brave.com/t/mobile-browser-wallet-reporting-eth-pricing-for-all-networks/415294

![panel-eth-issue](https://user-images.githubusercontent.com/11755381/179190394-69dbaa3c-d025-4887-8887-ff67512a8ef3.jpeg)

cc: @wchen342

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.43.74 x64 Beta build
- Verified steps from [brave/brave-core#14201](https://github.com/brave/brave-core/pull/14201)
- Verified when network is changed in panel corresponding network's native token is shown and balance is updated

Oppo Reno 5(Android 12) | Samsung Tab A (Android 10)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/185576334-b2ce5479-faef-4f36-8b8a-fdc024aff6cd.mp4> | <video src=https://user-images.githubusercontent.com/17010094/185576766-0657216c-7ba3-4581-857d-a16807d58f44.mp4>
