### ISSUE TITLE
Seemingly impossible to complete captcha and claim rewards on Linux

### ISSUE THREAD

**Issue by rdgh8** [brave/brave-browser#24073]
## Description 

I cannot seem to claim my monthly rewards on Linux. 

## Steps to Reproduce

   1. Click "Claim Rewards"
   2. Attempt to complete captcha by dragging the icon into the correct shape. Brave will repeatedly claim it is being done incorrectly. 

## Actual result:

After giving up and closing the captcha, the "Claim Rewards" button remains on the homescreen. Clicking it results in the Brave Rewards menu opening but nothing happening (captcha does not reappear and you do not receive your BAT)

https://user-images.githubusercontent.com/66289396/179118983-daebc8dc-6029-40cd-8ac2-4fdc42f13057.mp4

## Expected result:

BAT is claimed

## Reproduces how often: 

Both June and July for me

## Brave version (brave://version info)

1.39.79 Chromium: 101.0.4951.41 (Official Build) beta (64-bit) 

## Version/Channel Information:

Not practically reproduced (would have to wait a month for rewards after downloading Brave from a different channel)

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
Yes
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
No
- Does the issue resolve itself when disabling Brave Rewards? 
N/A
- Is the issue reproducible on the latest version of Chrome? 
N/A

## Miscellaneous Information:

Device is a laptop with an i7 8750h and GTX 1060 mobile, running Pop!_OS 22.04 on Wayland

**Comment by cwmke** [comment]
I have the same issue with Fedora 36 on two different laptops and a desktop. I haven't been able to claim rewards in 2-3 months.

**Comment by rdgh8** [comment]
I find that if you try enough times, it will work. Like 20-30 times.

**Comment by cwmke** [comment]
After a recent update this is resolved for me on all devices. Works on the first time every time and also allowed me to receive past months contributions.

**Comment by bsclifton** [comment]
cc: @brave/rewards-support

**Comment by Miyayes** [comment]
Sounds like it's resolved. Great1
