### ISSUE TITLE
UX follow-ups to top sites customization #6619

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#24071]
## Description 

As a follow-up to top sites pagination https://github.com/brave/brave-browser/issues/6619 :

1. Remove the 1 "dot"/page enumeration until user creates a second page (or more than 6 top sites). Looks like a floating dot with only six tiles.
2. With Brave News on, selecting the second "page" or second set of top sites makes Brave News peek up even more. 
3. When selecting a page 1, 2, 3, or 4 in top sites, opening a new tab page should keep you on the page you selected. For example, select page 3 on the existing new tab page. Open a new tab page, and top sites should remain on page 3. If a user has multiple new tab pages open, a change in one should not reflect in the others. Only a new tab should reflect the last selected pagination state. 

## Steps to Reproduce
See above. Using 1.43.20 and higher. To reproduce 1, need only 6 top sites. To reproduce 2 and 3 requires 12 to 36 top sites. Can pick sites from here `https://www.visualcapitalist.com/the-50-most-visited-websites-in-the-world/` or choice websites.

## Actual result:
<img width="573" alt="Screenshot 2022-07-14 at 4 08 11 PM" src="https://user-images.githubusercontent.com/5951041/179116333-d03b735c-67ff-4e0c-8357-28fd701acde1.png">

<img width="1198" alt="screenshot_2022-07-14_at_10 28 17_am" src="https://user-images.githubusercontent.com/5951041/179116128-53770058-7ee2-4433-bc45-2cfdc9de1d58.png">

1. Dot shown on one page.
2. Brave News peeks higher with selection of page 2.
3. Opening a new tab page always shows the first set of tiles or first page versus last viewed.

## Expected result:
1. No dot with first page/first set of six sites.
2. No movement with Brave News with selection of pagination with top sites.
3. Show last viewed page on opening of a new tab page.

## Reproduces how often: 

Easily.

## Brave version (brave://version info)

1.43.20 and higer

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.43.70 Chromium: 104.0.5112.81 (Official Build) beta (x86_64)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | macOS Version 11.6.8 (Build 20G730)

Confirmed no pagination dots (`o`) until 12+ tiles:

No pagination (11 tiles) | Pagination (12+ tiles)
-----------------------|----------------------
<img width="1269" alt="Screen Shot 2022-08-15 at 4 25 06 PM" src="https://user-images.githubusercontent.com/387249/184741955-d9119ed6-0afd-4ea0-8d1e-9ce04c47d41c.png"> | <img width="1269" alt="Screen Shot 2022-08-15 at 4 29 55 PM" src="https://user-images.githubusercontent.com/387249/184743530-dd029ed0-6bbf-41b2-aeeb-ceda79169f98.png">

Confirmed no Brave News "peeking" movement when switching between pages:

example | example | example
---------|----------|---------
<img width="1269" alt="Screen Shot 2022-08-15 at 4 36 18 PM" src="https://user-images.githubusercontent.com/387249/184748568-b711efe6-4470-4f49-b4fa-fb1b16efef22.png"> | <img width="1312" alt="Screen Shot 2022-08-15 at 4 39 33 PM" src="https://user-images.githubusercontent.com/387249/184748579-0ae0e4ea-9e1a-4dd0-8112-873e5d97c154.png"> | <img width="1312" alt="Screen Shot 2022-08-15 at 4 40 09 PM" src="https://user-images.githubusercontent.com/387249/184748736-41546c7a-cfe1-40b2-9dff-07976f8d6650.png">
