### ISSUE TITLE
First run dialog is unskippable on windows

### ISSUE THREAD

**Issue by ubergeek42** [brave/brave-browser#24082]
## Description 

There is no way to skip/hide the first run dialog on windows. The dialog only offers to set brave as the default browser, but if it is already the default browser the window is shown anyway.

![image](https://user-images.githubusercontent.com/672279/179289235-d3c67f71-26b6-46b9-9f2b-2c215e419a4d.png)

## Steps to Reproduce

   1. Install brave, open it, set it as the default browser
   2. Delete the brave profile settings (`%LOCALAPPDATA%/BraveSoftware`)
   3. Launch brave, observe the first run dialog

## Actual result:

The dialog is always shown, even if brave is already the default browser

## Expected result:
The first run dialog to be skipped if brave is the default browser (or a preference/policy to skip this first run dialog. For chrome on linux/mac, that's the `MetricsReportingEnabled` policy, but there's no equivalent in brave for windows).

## Reproduces how often: 

Every time.

## Brave version (brave://version info)

![image](https://user-images.githubusercontent.com/672279/179289590-886f30ab-6470-4dd4-8e09-6b6d9aad03dd.png)

## Version/Channel Information:

Didn't try, but looking at the source code on master it seems likely to still be an issue in all channels.

## Other Additional Information:
N/A

## Miscellaneous Information:

I use brave in a virtual machine for testing, and wipe the profile/reprovision the machine frequently. I have scripts to set Brave as the default browser after installing it, but it still nags me which interrupts my testing workflow.

The `--no-first-run` flag is not sufficient, as while it suppresses the first run dialog, it also skips processing the `initial_preferences`/`master_preferences` file, which I use to configure a few things.

This PR seems to be where this was added: https://github.com/brave/brave-core/pull/12482
Probably a check if brave is already the default browser could be added here: https://github.com/brave/brave-core/blob/6103fb3d7a7ee200a1b4b9f4bdf399db117e030d/chromium_src/chrome/browser/first_run/first_run_internal_win.cc#L11-L17

That'd be similar to how chrome does it when checking for the `MetricsReportingEnabled` policy on other platforms (see: https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/first_run/first_run_internal_posix.cc;l=56-62;bpv=0;bpt=1)

**Comment by bsclifton** [comment]
@ubergeek42 thanks for the report - I can definitely see how this could break you if you're using Selenium or something like that

Do you have more information about your setup?

**Comment by ubergeek42** [comment]
Exactly, my test harness doesn't expect the dialog to be there, so it causes some issues I have to annoyingly work around. My current workaround is to launch Brave, the nag appears, so I sleep for a bit to make sure the profile is fully initialized, then kill brave and launch it again. The second run skips the nag because the profile directory was created by the first run. I frequently wipe the profile directory to clear everything out and this extra step feels very unclean/slows things down.

**Comment by shvchk** [comment]
Here's what I found:

You can use [`PromotionalTabsEnabled`](https://chromeenterprise.google/policies/?policy=PromotionalTabsEnabled) policy set to `false` to skip welcome screen.

If you want to disable telemetry, you can use [`MetricsReportingEnabled`](https://chromeenterprise.google/policies/?policy=MetricsReportingEnabled) (controls sending diagnostic reports) and [`UrlKeyedAnonymizedDataCollectionEnabled`](https://chromeenterprise.google/policies/?policy=UrlKeyedAnonymizedDataCollectionEnabled) (not sure if does anything in Brave) policies, and pre-create `Local  State` file (I think it's in `%LOCALAPPDATA%/BraveSoftware/Brave-Browser` on Windows) with the following contents:

```json
{ "brave": { "p3a": { "enabled": false }, "stats": { "reporting_enabled": false } } }
```

— this will disable P3A and usage pings. No other content in `BraveSoftware/Brave-Browser` dir needed.

**Comment by bsclifton** [comment]
cc: @simonhong - do you know if there's a way to skip this?

I believe we do have logic about if Brave is already default (even if another channel), don't offer it. But I can't remember

**Comment by simonhong** [comment]
We don't use first run dialog anymore as we have it in welcome flow. https://github.com/brave/brave-core/pull/16282

**Comment by bsclifton** [comment]
Oh yeah, that's right! Thanks @simonhong 😄 
Closing as fixed
