### ISSUE TITLE
"Join" extension won't function in Brave

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#2408]
## Description 

Several users have brought to my attention that apps like "Join" won't work in Brave with #1380.
Devices cannot communicate and device the extension is installed on remains "unrecognized". Diagnostics in the extension show the following errors:
![image](https://user-images.githubusercontent.com/3299098/49670890-f74e5600-fa1a-11e8-95a5-78ca79329e8a.png)

## Steps to Reproduce

   1. Install Join extension
   2. Try to use the extension
   3. When it doesn't work, run diagnostics

## Actual result:

Extension doesn't function

## Expected result:
Extension should work and device should be recognized. 

## Reproduces how often: 

Easily/always

## Brave version (brave://version info)

All current builds
Release Build v0.57.18
Beta build v0.57.8
Developer build v0.59.2

### Reproducible on current release: 
Yes
- Does it reproduce on brave-browser dev/beta builds? 
Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields?
No 
- Is the issue reproducible on the latest version of Chrome? 
No

### Additional Information

No Shields settings, in domain-specific or global, have any effect.

**Comment by darthShadow** [comment]
This is still an issue with the latest version of the browser (0.60.47 Chromium: 72.0.3626.119 (Official Build) (64-bit)). Anything I can do to help get this resolved faster? Basically, the only thing preventing me from switching fully to Brave.

**Comment by anthonyrebel** [comment]
> This is still an issue with the latest version of the browser (0.60.47 Chromium: 72.0.3626.119 (Official Build) (64-bit)). Anything I can do to help get this resolved faster? Basically, the only thing preventing me from switching fully to Brave.

FWIW - When I started collecting errors on the extension it failed on line 1963 with the following error:  Error: File doesn't exist on your google drive: storedpushes=:=undefined.  

In addition, when you run through the GCM Internals the connection state comes up as false.  

I haven't spent a lot of time on this issue, but in my case it acts like it's not integrated with Google Drive even though I went through the setup.  I've only been able to reproduce this issue in Brave.  Going through setup in Chrome and Canary still works.

**Comment by Brave-Matt** [comment]
+1 from Reddit:
https://www.reddit.com/r/brave_browser/comments/b90wmq/join_extension_does_not_work/

**Comment by jDally987** [comment]
Hey, if it helps:
If you go to Join's chrome extension store page, in the "Support" tab, the user Sean Blonien posted 2 days ago (so Apr. 27 2019):
![image](https://user-images.githubusercontent.com/24235975/56856674-6cb8b580-692d-11e9-84a9-8bc463f6afdb.png)
So it looks like the problem is related to `regId`?

**Comment by FappyMcFap** [comment]
+1 I rely on this extension quite a bit.

**Comment by ReeSilva** [comment]
+1

**Comment by LesterCovax** [comment]
It's working perfectly now in `Brave Dev Version 0.72.110 Chromium: 78.0.3904.70` after enabling `Use Google Services for Push Messaging` (Added in v0.72.73 - https://github.com/brave/brave-browser/issues/2301 / https://github.com/brave/brave-core/pull/3390 / https://github.com/brave/brave-core/commit/cd3df93236f9677a70493e4cc1a82ba6d5bfb973) .  This finally enables Brave to work with [Firebase Cloud Messaging](https://developers.google.com/web/fundamentals/push-notifications/), after GCM having been deprecated earlier this year (more info: [GCM/FCM FAQ](https://developers.google.com/cloud-messaging/faq)).  
_**Note:** This feature isn't available yet in Release/Beta channels._

There appears to be a bug though, where clicking the `Relaunch` button after toggling it on, untoggles the setting before relaunching.  I got around this by toggling it on, and then running `chrome://restart` in a new tab.  I've created https://github.com/brave/brave-browser/issues/6633 for the bug.

<img src="https://user-images.githubusercontent.com/34850610/67652762-c588fb00-f91c-11e9-9692-e4d8d7405b4a.png" height="150px">

- [x] **Step 1:** Use Google Services for Push Messaging :feelsgood:
- [ ] **Step 2:** ‽‽‽‽‽
- [x] **Step 3:** Profit!!! :money_mouth_face::money_with_wings:

**Comment by mickdekkers** [comment]
Can confirm, Join works great in Brave now. You just need to enable Google Services for Push Messaging as @LesterCovax showed. I'm on the Release channel, so it looks like this feature has made its way there.

Join has a self-test function under the diagnostics tab. All the tests pass in Brave 🎉  

![A screenshot of Join's diagnostics tab, taken after running the tests in Brave. All the tests have passed.](https://user-images.githubusercontent.com/5085260/71467791-44d36780-27c4-11ea-9115-e2e5ccd40c63.png)

Tested on `Version 1.1.23 Chromium: 79.0.3945.88 (Official Build) (64-bit)`.

**Comment by bsclifton** [comment]
Thanks for confirming, folks! 😄
