### ISSUE TITLE
[hackerone] IPFS crash

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#24093]
see https://hackerone.com/reports/1636430 for details

credit: [neeythann](https://hackerone.com/neeythann)

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.43.56 Chromium: 104.0.5112.81 (Official Build) dev (x86_64)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | macOS Version 13.0 (Build 22A5311f)

## Test Setup
<details>

Created webserver instance via `python3 -m http.server`

For the "incorrect {`ipfs`, `ipns`} tests", I ensured the following HTML snippets (from HackerOne and @cypt4) don't crash:
* `ipfs-crash-test-1.html` (dotted-quad IP address)
* `ipfs-crash-test-2.html` (empty `ipfs://` scheme)
* `ipfs-crash-test-3.html` (full IPFS URL)
* `ipfs-crash-test-4.html` (redirect testcase)

### IPFS URLs
<details>

#### Correct
`ipfs://bafybeicgmdpvw4duutrmdxl4a7gc52sxyuk7nz5gby77afwdteh3jc5bqa/wiki/Mars.html`
#### Incorrect
`ipfs://`

</details>

### IPNS URLs
<details>

#### Correct
`ipns://docs.ipfs.io`
#### Incorrect
`ipns://`

</details>

</details>

## Shared Steps:
<details>

1. install `1.43.56`
2. launch Brave
3. open the appropriate tab (window) type
4. load the respective URL

</details>

### IPFS disabled:
<details>

1) Check iframe with correct ipfs url in normal tab
2) Check iframe with correct ipfs url in private tab
3) Check iframe with incorrect ipfs url in normal tab
4) Check iframe with incorrect ipfs url in private tab
5) Check iframe with correct ipns url in normal tab
6) Check iframe with correct ipns url in private tab
7) Check iframe with incorrect ipns url in normal tab
8) Check iframe with incorrect ipns url in private tab

</details>

### IPFS enabled, local node:
<details>

1) Check iframe with correct ipfs url un normal tab
2) Check iframe with correct ipfs url in private tab
3) Check iframe with incorrect ipfs url in normal tab
4) Check iframe with incorrect ipfs url in private tab
5) Check iframe with correct ipns url in normal tab
6) Check iframe with correct ipns url in private tab
7) Check iframe with incorrect ipns url in normal tab
8) Check iframe with incorrect ipns url in private tab

</details>

### IPFS enabled, gateway:
<details>

1) Check iframe with correct ipfs url normal tab
2) Check iframe with correct ipfs url private tab
3) Check iframe with incorrect ipfs url in normal tab
4) Check iframe with incorrect ipfs url in private tab
5) Check iframe with correct ipns url in normal tab
6) Check iframe with correct ipns url in private tab
7) Check iframe with incorrect ipns url in normal tab
8) Check iframe with incorrect ipns url in private tab

</details>

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.43.56 Chromium: 104.0.5112.81 (Official Build) dev (x86_64)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | macOS Version 13.0 (Build 22A5311f)

## Test Setup
<details>

Created webserver instance via `python3 -m http.server`

For the "incorrect {`ipfs`, `ipns`} tests", I ensured the following HTML snippets (from HackerOne and @cypt4) don't crash:
* `ipfs-crash-test-1.html` (dotted-quad IP address)
* `ipfs-crash-test-2.html` (empty `ipfs://` scheme)
* `ipfs-crash-test-3.html` (full IPFS URL)
* `ipfs-crash-test-4.html` (redirect testcase)

</details>

### IPFS disabled:
<details>

1) Check iframe with correct ipfs url in normal tab
2) Check iframe with correct ipfs url in private tab
3) Check iframe with incorrect ipfs url in normal tab
4) Check iframe with incorrect ipfs url in private tab
5) Check iframe with correct ipns url in normal tab
6) Check iframe with correct ipns url in private tab
7) Check iframe with incorrect ipns url in normal tab
8) Check iframe with incorrect ipns url in private tab

1 | 2 | 3 | 4 | 5 | 6 | 7 | 8
-|-|-|-|-|-|-|-|
. | . | . | . | . | . | . | . |

</details>

### IPFS enabled, local node:
<details>

1) Check iframe with correct ipfs url un normal tab
2) Check iframe with correct ipfs url in private tab
3) Check iframe with incorrect ipfs url in normal tab
4) Check iframe with incorrect ipfs url in private tab
5) Check iframe with correct ipns url in normal tab
6) Check iframe with correct ipns url in private tab
7) Check iframe with incorrect ipns url in normal tab
8) Check iframe with incorrect ipns url in private tab

1 | 2 | 3 | 4 | 5 | 6 | 7 | 8
-|-|-|-|-|-|-|-|
. | . | . | . | . | . | . | . |

</details>

### IPFS enabled, gateway:
<details>

#### Steps:
1. install `1.43.56`
2. launch Brave
3. load `ipns://brantly.eth`
4. click on `Use a public gateway`
5. opened `brave://settings/ipfs` and set `IPFS public gateway address` to `https://cf-ipfs.com` (it's faster, IMHO)
6. [open a new Private window, if specified]
7. open the appropriate local HTML testcase

1) Check iframe with correct ipfs url normal tab
2) Check iframe with correct ipfs url private tab
3) Check iframe with incorrect ipfs url in normal tab
4) Check iframe with incorrect ipfs url in private tab
5) Check iframe with correct ipns url in normal tab
6) Check iframe with correct ipns url in private tab
7) Check iframe with incorrect ipns url in normal tab
8) Check iframe with incorrect ipns url in private tab

1 | 2 | 3 | 4 | 5 | 6 | 7 | 8
-|-|-|-|-|-|-|-|
. | . | . | . | . | . | . | . |

</details>

**Comment by stephendonner** [comment]
I passed this, but we need to uplift https://github.com/brave/brave-browser/issues/24211; left a comment in  https://github.com/brave/brave-core/pull/14313#issuecomment-1205842589 to that effect.
