### ISSUE TITLE
Fingerprinting preventing signin on raceroster.com

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#24096]
## Description 
Unable to login into `https://raceroster.com/events/2022/57424/purekids-triathlon-series-2022-presented-by-pure-flavor-and-wfcu-credit-union` due to fingerprinting

## Steps to reproduce 

   1. (on Android) Open `https://raceroster.com/events/2022/57424/purekids-triathlon-series-2022-presented-by-pure-flavor-and-wfcu-credit-union`
   2. Create a sign in, attempt to sign in with user/pass. 
   3. Button shows "Sign in"

## Actual result 
"Sign Out" Box should show, indicating user/password worked

## Expected result
Allow sign in to work

## Issue reproduces how often 
Easily, Sample user login `yhtmuhhdkxnczqqjgl@nthrw.com`  password: `XVC$&u#lw3ejsS*Ir`

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): Arm
   - Device type (Phone, Tablet, Phablet): Galaxy Fold 3
   - Android version: 12
   
## Brave version
Testing in Brave Nightly

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? Yes (Allow Fingerprinting works.)
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information
From my testing there is a regression, between `1.39.22` and `1.39.23`

```
1.38.109 (release) Good
1.39.22 (Nightly) Good
1.39.23 (Nightly) Bad
1.39.24 (Nightly) Bad
1.39.27 (Nightly) Bad
1.39.33 (Nightly) Bad
1.39.43 (Nightly) Bad
1.39.76 (Beta) Bad
```

**Comment by mikealmond** [comment]
I just wanted to share that this has been fixed on the Race Roster side. The `accept-language` header was changing between requests and the system saw this as a possible session hijack. The logic has been changed to only look at the preferred language as opposed to the entire list to avoid false positives.

**Comment by ryanbr** [comment]
Closed, checked and working.
