### ISSUE TITLE
Tab group outline is not rendered properly with light theme

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#24095]
## Description 

Inactive tab also should have thicker bottom line when it's included in any tab group

## Steps to Reproduce

   1. Launch Brave
   2. Create tab group via tab's context menu (`Add Tab to Group`)
   3. Check inactive tab's bottom bottom line in the tab group

## Actual result:

<img width="632" alt="image" src="https://user-images.githubusercontent.com/6786187/179430462-17c13a66-9f1e-4153-9c94-0ef276c39358.png">
<img width="455" alt="image" src="https://user-images.githubusercontent.com/6786187/179430560-00961483-4acd-43ea-8c71-6f17bcd41adc.png">

## Expected result:
Works properly with dark theme like below.
<img width="552" alt="image" src="https://user-images.githubusercontent.com/6786187/179430521-78279a60-811f-4742-800d-92a93db0b39b.png">
<img width="478" alt="image" src="https://user-images.githubusercontent.com/6786187/179430547-0f6c0f8e-cbaa-4f4f-9c90-ed0a8612528b.png">

## Reproduces how often: 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.43.54 Chromium: 104.0.5112.69 (Official Build) beta (64-bit)
-- | --
Revision | 7ce2902023c722af8564068e6b26e934b83fd774-refs/branch-heads/5112@{#1213}
OS | Windows 11 Version 21H2 (Build 22000.795)
```

Reproduced in `1.41.100` using STR from https://github.com/brave/brave-browser/issues/24095#issue-1307250343
![image](https://user-images.githubusercontent.com/98358127/182263590-64f3c3ca-593b-4add-9337-60979f6f21a8.png)

### Confirmed tab group border thickness in light theme rendered as expected and compared with dark mode
### Confirmed tab group border thickness rendered as expected for Guest window, Private and TOR windows

dark|light
----|-----
<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/182263411-4d2b63f8-4eb9-4c3f-a081-3b8bfc079162.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/182263436-457ff22a-5556-4f01-9f88-02b1a7f9a1a8.png">


GW|PW|TOR
----|----|-----
<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/182264085-b1f51fd3-6d9c-451b-9917-55a4641e5172.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/182264169-c6ebac45-8021-48e6-8c62-3e45c1e26603.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/182264343-cac956b0-2f57-47ed-ae7b-a2d20d001471.png">

**Comment by urbenlegend** [comment]
The tab outline looks great now, but can we also fix the padding and corner radius of the group labels? It's like the last thing that will make tab groups finally look polished in Brave.

For example, look at the label `Test` below:
![image](https://user-images.githubusercontent.com/241316/193435492-4e19de23-21f1-46b5-8d3c-788d5865a3de.png)
The purple box surrounding the label barely has any padding against the tab outline, making it look like its merging with it. Rounding out the corners of the box will also make it more appealing and more in line with the unnamed group circles.
