### ISSUE TITLE
Expire Flash settings if it doesn't come for free in C68

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#241]
This should come for free in C68 here:
https://www.chromium.org/flash-roadmap#TOC-Non-Persisted-HTML5-by-Default-Target:-Chrome-68---July-2018-

But if not we should implement it.

**Comment by bbondy** [comment]
This came for free from the Chromium 70 upgrade.

**Comment by LaurenWags** [comment]
Verified passed on

Brave | 0.55.12 Chromium: 70.0.3538.45 (Official Build) beta(64-bit)
-- | --
Revision | cbdc32e4334458954e9def214d7e5fa1ca1960eb-refs/branch-heads/3538@{#830}
OS | Mac OS X

* Navigated to homestarrunner.com -> received notice in URL bar
![screen shot 2018-10-10 at 5 37 11 pm](https://user-images.githubusercontent.com/28145373/46767499-24001e80-ccb3-11e8-90e1-42e9d13a7df9.png)
* Clicked 'Run Flash this time'. Clicked 'Click to enable Adobe Flash Player'. Was prompted in URL bar to Allow or Block:
![screen shot 2018-10-10 at 5 38 37 pm](https://user-images.githubusercontent.com/28145373/46767564-5578ea00-ccb3-11e8-9a41-04c933d64af8.png)
* Verified both Block and Allow function as expected.
* Navigated to chrome://settings/content/flash --> Verified setting toggle to 'Ask first' and navigating to flash site did not show Plugin blocked URL bar notice (had to click 'Click to enable Adobe Flash Player' and select block or allow from prompt)
* Verified flash settings were expired on restart per notice on chrome://settings/content/flash

**Comment by srirambv** [comment]
Linux is blocked on https://github.com/brave/brave-browser/issues/1562
