### ISSUE TITLE
mobile.twitter.com right click hang

### ISSUE THREAD

**Issue by kxlt** [brave/brave-browser#2410]
## Description 

Right clicking on mobile.twitter.com hangs the entire tab for a few seconds.

## Steps to Reproduce

1. Log into twitter.com and go to mobile.twitter.com
2. Right click on any part of the page, preferably an external link.

## Actual result:

Devtools Performance panel screenshot, see the long “Event (context menu)”. Right click menu doesn’t appear until it ends executing all that Javascript, so 11 seconds.

[Devtools performance panel screenshot](https://discourse-cdn-sjc1.com/business4/uploads/brave/original/2X/5/572e5018d50bd591cc2644b858289c9f48b562f3.png)

## Expected result:
Right click menu pops up very quickly.

## Reproduces how often: 

Always.

## Brave version (brave://version info)

Brave | 0.57.18 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X
JavaScript | V8 7.1.302.28
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36
Command Line | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --enable-features=EnableEmojiContextMenu,DesktopPWAWindowing,fill-on-account-select,NewExtensionUpdaterService --disable-features=SharedArrayBuffer,DefaultEnableOopRasterization,VizDisplayCompositor,AutofillSaveCardSignInAfterLocalSave,AutofillServerCommunication,UnifiedConsent --flag-switches-begin --flag-switches-end

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds?  YES

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NO
- Is the issue reproducible on the latest version of Chrome? NO

**Comment by ostoh** [comment]
I just experienced this too. The lag took 14.4s.


Brave | 0.59.20 Chromium: 72.0.3626.28 (Official Build) beta(64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Linux
JavaScript | V8 7.2.502.13
Flash | (Disabled)
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.28 Safari/537.36

**Comment by Brave-Matt** [comment]
Several +1's from Community:
https://community.brave.com/t/twitter-twitter-beta-issue-delay-on-right-click/43692/9

**Comment by reaktivo** [comment]
I've dug a bit on this issue and found that the cause of the few seconds hang is the `unique-selector` running while trying to find a unique css selector to block an ad with.

I've opened a pull request for the fix here https://github.com/brave/brave-extension

**Comment by kaepora** [comment]
This also happens on Windows 10.

`Brave Version 0.61.51 Chromium: 73.0.3683.75 (Official Build) (64-bit)`

**Comment by bsclifton** [comment]
Quick update - the problem is with our cosmetic filtering code. A unique selector is calculated on right click, in the event that you go into the Brave menu and choose `Block element via selector`

Looking into a fix now...

**Comment by kjozwiak** [comment]
@brave/legacy_qa once we get a nightly that includes https://github.com/brave/brave-core/pull/2043 & https://github.com/brave/brave-core/pull/2063, we'll need to go through the test plans to ensure that it's working as expected and didn't cause any other obvious performance issues or regressions. We would like to get this uplifted into `0.63.x` as well but need to make sure it's working on nightly.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.63.40 Chromium: 74.0.3729.61 (Official Build) beta (64-bit)
-- | --
Revision | 5df2c8936783bd7575987e45d72a92fcf528496b-refs/branch-heads/3729@{#645}
OS | Windows 10 OS Build 17134.523

Verified the test plan from https://github.com/brave/brave-core/pull/2043
