### ISSUE TITLE
ETH & BAT tokens are listed for Solana Account

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#24104]
## Description 
ETH & BAT tokens are listed for Solana Account (Portfolio, asset details and account details screen)

## Steps to reproduce 

   1. Enable Solana flag and create a Solana Account
   2. Go to Accounts tab and open the created Solana Account
   3. ETH & BAT tokens from Ethereum Account 1 are listed by default

## Actual result 
![image](https://user-images.githubusercontent.com/17010094/179531579-ef542386-7199-4bbc-bf7e-2bb5743538b7.png)

## Expected result
Should show SOL for Solana Account

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Na
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 12
   
## Brave version
1.43.26

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @Pavneet-Sing

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on `Samsung Galaxy Tab A7 version 11` running `Bravemonoarm64.apk_1.42.89`

- Verified Accounts, Assets and Portfolio screens show Solana accounts and assets

Account details | Portfolio | Visible assets
-- | -- | --
![Screenshot_20220808-221804_Brave](https://user-images.githubusercontent.com/38657976/183471390-8b0778c5-71bb-41c5-84a7-1b18e5610216.jpg) | ![Screenshot_20220808-221828_Brave](https://user-images.githubusercontent.com/38657976/183471421-fe2eb39e-4870-4512-b31b-b9af416660a6.jpg) | ![Screenshot_20220808-222023_Brave](https://user-images.githubusercontent.com/38657976/183471456-4806a5d0-bd96-43c0-935c-d7ec57099634.jpg)

----
Verification PASSED on `Samsung Galaxy A52s version 11` running `Bravemonoarm64.apk_1.42.89`

Account details | Portfolio | Visible assets
-- | -- | --
![IMG-20220808-WA0001](https://user-images.githubusercontent.com/38657976/183473147-ae4b9077-7fea-4079-85aa-429fde086f4f.jpg) | ![IMG-20220808-WA0002](https://user-images.githubusercontent.com/38657976/183473178-9370a577-7fb5-4c93-9ecd-c497f92ae698.jpg) | ![IMG-20220808-WA0004](https://user-images.githubusercontent.com/38657976/183473201-54ba076c-d8af-4e5a-955c-25d9238213f8.jpg)
