### ISSUE TITLE
Shield not actually disabled

### ISSUE THREAD

**Issue by JakobJingleheimer** [brave/brave-browser#24101]
## Description 

I think the fix for https://github.com/brave/brave-browser/issues/23988 did not actually work.

Brave Shields causes _heaps_ of problems for localhost (and thus local web development), so I have it disabled.

Brave Shields reports itself disabled yet is actually running.

## Steps to Reproduce

1. Open a fresh regular window and go to `app.localhost` (presumably with a server running)
1. Disable shields
1. Close the window
1. Open a new window (incognito—not sure if it matters) and go to the same url from step 1

## Actual result:

The Shields icon is greyed out and the Shields popover claims "**Shields are DOWN** for app.localhost". That's a lie: it's still blocking certain requests and silently switching http → https.

Manually toggling the on/off switch first to "on" and then back to "off" truly disables it for the current session (but then the bug recurs for the next new window/tab).

## Expected result:

Shields to actually be disabled when it says it is.

## Reproduces how often: 

100%

## Brave version

1.41.96

## Version/Channel Information:

Unknown

## Other Additional Information:

N/A 

## Miscellaneous Information:

N/A

**Comment by ryanbr** [comment]
Changing shields options, it won't apply to all subdomains.  So disabling shields for localhost won't apply to app.localhost. Shields would be needed to be adjusted on a per domain/subdomain basis. If its needed for development, per-site or just disable https globally in brave://settings

@JakobJingleheimer

**Comment by JakobJingleheimer** [comment]
Thanks for getting back to me.

I specifically disabled it on `http://app.localhost:3000` in step 1 and went back to it in step 4. Note that in my reproduction steps I specifically said to return to the same URL as step 1 (I just happen to be using a subdomain, but it was consistent). Also, Shields _claims_ that it is disabled.

I don't want to globally disable http → https, only for [.*]localhost—localhost is already considered a secure context, so https just adds overhead and wastes processing power.

**Comment by JakobJingleheimer** [comment]
This seems to be resolved in Brave v1.42.88 (possibly earlier).
