### ISSUE TITLE
`For quick access....` text is invisible with white background in the bookmarks bar for a newly created profile 

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#24110]
## Description 

   1. Install 1.41.96
   2. Launch Brave
   3. open `brave://settings/appearance` and select `Dark`
   4. Do not import any bookmarks for original profile and verify the text is available `For quick access, place your bookmarks here on the bookmarks bar. Import bookmarks now...`
   5. Click hamburger menu>>Create a new profie
   6. Name the profile (Profile B) and select `Green and white` theme
   
   

## Actual result:

Text for `For quick access place your bookmarks here on the bookmarks bar` is not visible on the white background in the bookmarks bar. This issue is reproduced for all themes with white color and with Dark appearance

Ex1|Ex2
---|---
<image width="870" alt="image1" src="https://user-images.githubusercontent.com/98358127/179560942-dfbc8e2a-e642-4335-bb9e-c17a1b219b98.png">|<image width="870" alt="image1" src="https://user-images.githubusercontent.com/98358127/179560976-227dadc5-8174-4e3f-8056-67bb09898341.png">

## Expected result:
Different color for the text?

## Reproduces how often: 

Easily 

## Brave version (brave://version info)

Brave | 1.41.96 Chromium: 103.0.5060.114 (Official Build) (64-bit)
-- | --
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | Windows 11 Version 21H2 (Build 22000.795)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
@rebron

**Comment by rebron** [comment]
cc: @simonhong Can you take a look when you get a chance?

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.43.54 Chromium: 104.0.5112.69 (Official Build) beta (64-bit)
-- | --
Revision | 7ce2902023c722af8564068e6b26e934b83fd774-refs/branch-heads/5112@{#1213}
OS | Windows 11 Version 21H2 (Build 22000.795)
```
Verified using original steps from https://github.com/brave/brave-browser/issues/24110#issue-1308228164

### Confirmed text is visible in the bookmarks bar for profiles that has custom theme with white background in dark mode
Switched to light mode and verified text is visible as expected for the custom theme profiles

g&w -1|g&w-2|b&w|y&w|light blue
----|----|----|-----|-----
<image width = "850" alt="1" src="https://user-images.githubusercontent.com/98358127/182259202-40778ce5-b71e-4995-953a-4add08d26fdb.png">|<image width = "850" alt="2" src="https://user-images.githubusercontent.com/98358127/182258295-c4d59fa5-d743-4275-acb2-d2d5b6686e24.png">|<image width = "850" alt="2" src="https://user-images.githubusercontent.com/98358127/182258536-4b074b44-3540-4da3-955d-e7ea09586fd6.png">|<image width = "850" alt="2" src="https://user-images.githubusercontent.com/98358127/182259425-64edb874-24ba-4be7-9f84-1fdc512ec4f7.png">|<image width = "850" alt="2" src="https://user-images.githubusercontent.com/98358127/182258640-4352deba-9b1c-4cdd-a338-8b0038902db5.png">
