### ISSUE TITLE
Bug in brave cookies migration.

### ISSUE THREAD

**Issue by boocmp** [brave/brave-browser#24119]
## Steps to Reproduce

Seeing an issue with cookies configuration changed  from original setting Block all cookies to Allow all cookies in the Shields panel upon subsequent browser launches after an upgrade and https://firstparty/ entry shown  Sites that can never use cookies
1. install 1.41.96
2. visit [www.youtube.com](http://www.youtube.com/) and configure Block all cookies in the Shields panel
3. open brave://settings/cookies 
4. Following entries are displayed in the Sites that can never use cookies
      - [*.][youtube.com](http://youtube.com/)
      -[www.youtube.com](http://www.youtube.com/)
5. install 1.42.62
6. renamed Brave-Browser profile to Brave-Browser-Beta
7. relaunched the browser
8. confirmed [www.youtube.com](http://www.youtube.com/) entry is shown as expected in brave://settings/cookies
9.  Block all cookies setting retained
10. close the browser and relaunch

## Actual result:

1.  Cookie setting changed to Allow all cookies
2.  brave://settings/cookies page shows following entry in Sites that can never use cookies in addition to earlier entry [www.youtube.com](http://www.youtube.com/)
       [www.youtube.com](http://www.youtube.com/)
        `embedded on https://firstparty/

![image](https://user-images.githubusercontent.com/98358127/179783583-cb437503-56cc-4784-ba9c-30d9a3b7f8dd.png)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
`QA/Blocked` pending uplift

**Comment by kjozwiak** [comment]
The above will require `1.42.78` or higher for `1..42.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.42.78 Chromium: 103.0.5060.134 (Official Build) beta (x86_64)
-- | --
Revision | 8ec6fce403b3feb0869b0732eda8bd95011d333c-refs/branch-heads/5060@{#1262}
OS | macOS Version 12.5 (Build 21G72)
```
