### ISSUE TITLE
Add Rewards verification state changes to Event Logs tab of `brave://rewards-internals` for Gemini and bitFlyer 

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#24112]
## Description 

While testing https://github.com/brave/brave-browser/issues/23682 noticed that rewards verification state changes are only logged on the "Event logs" tab of brave://rewards-internals for Uphold, not for Gemini or bitFlyer.

Per discussion with @Miyayes @szilardszaloki this is something we want to consider adding.

## Steps to Reproduce

   1. Clean profile, staging env
   2. Enable Rewards
   3. Link KYC'd Uphold account
   4. Look at brave://rewards-internals Event Logs tab, see line for `NOT_CONNECTED` --> `PENDING` and then `PENDING` --> `VERIFIED` rewards verification state change
   5. Repeat for Gemini or bitFlyer

## Actual result:

Gemini and bitFlyer don't list the rewards verification state changes on Event Logs tab

## Expected result:

Like the below which exists for Uphold

<img width="1189" alt="uphold example" src="https://user-images.githubusercontent.com/28145373/179563497-3b116c81-955e-431f-ae10-b9c6d038c598.png">

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.42.68 Chromium: 103.0.5060.114 (Official Build) beta (x86_64)
-- | --
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | macOS Version 12.4 (Build 21F79)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.44.73 Chromium: 105.0.5195.68 (Official Build) beta (x86_64)
-- | --
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | macOS Version 12.5.1 (Build 21G83)
```

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21 5G` & `Samsung Galaxy Tab S7` using 

```
Brave	1.44.95 Chromium: 106.0.5249.40 (Official Build) (64-bit) 
Revision	fab1d91915d2722d6339aaa7f4e9ce44f1e9b103-refs/branch-heads/5249@{#442}
OS	Android 12; Build/SP1A.210812.016
```
Test Plan: https://github.com/brave/brave-browser/issues/24112#issue-1308242028

- Verified verification state changes are logged in `brave://rewards-internals` for `Uphold`, `Gemini` and `bitFlyer`

Uphold | Gemini | bitFlyer
-|-|-
![screenshot-1663791689991](https://user-images.githubusercontent.com/17885425/191605591-e0d1a4a4-6886-46ca-b081-da85145fc45b.png) | ![screenshot-1663791868700](https://user-images.githubusercontent.com/17885425/191605593-46b41c65-5a66-4b26-a983-aa1448b9034f.png) | ![screenshot-1663792152025](https://user-images.githubusercontent.com/17885425/191605596-3b609b01-7ab5-4295-9723-1835170a3732.png)
<img width="581" alt="Screen Shot 2022-09-21 at 3 52 08 PM" src="https://user-images.githubusercontent.com/17885425/191605788-77e59155-b992-43b9-b1f4-c8f5632e51de.png"> | <img width="576" alt="Screen Shot 2022-09-21 at 3 58 46 PM" src="https://user-images.githubusercontent.com/17885425/191605767-a7d675f9-91d7-4d0f-b839-d26763ccee69.png"> | <img width="579" alt="Screen Shot 2022-09-21 at 4 16 47 PM" src="https://user-images.githubusercontent.com/17885425/191605771-eec82c66-e290-4189-a18a-5f7c1ee25f2e.png">
