### ISSUE TITLE
Add to Bookmarks shortcut randomly doesn't work

### ISSUE THREAD

**Issue by Gersonzao** [brave/brave-browser#24116]
## Description
The shortcut to add a website to bookmarks randomly doesn't work. The button always works
## Steps to Reproduce
   1. Open random websites
   2. Try adding them to bookmarks **only by using the shortcut** (Ctrl+D)
## Actual result:
The popup doesn't open, neither the website is added to the bookmarks
## Expected result:
Popup appeared and bookmark added
## Reproduces how often: 
Intermittent issue
## Brave version (brave://version info)
Brave | 1.42.65 Chromium: 103.0.5060.114 (Official Build) beta (64-bit)
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | Windows 7 Service Pack 1 (Build 7601.24241)
## Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No

**Comment by Gersonzao** [comment]
Isn't happening anymore, should've been fixed.

**Comment by rebron** [comment]
@Gersonzao Thanks for the note.
