### ISSUE TITLE
[Android] India retention - update onboarding copy

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#24111]
**Summary**
Update the onboarding copy for the India locale to be softer and explain the feature benefits focused on: 

(1) Ad-blocking
(2) Ad-free video streaming

_Existing onboarding:
https://user-images.githubusercontent.com/28269287/179563128-d5faf1e9-36d4-4c85-a71b-1dfe613a602a.mp4_

**Why**
@anthonypkeane @timchilds @srirambv @tapanmodh @deeppandya @Pavneet-Sing met recently to discuss what we can do to improve our user retention rates in India. One of the changes agreed was to focus the onboarding on ad-blocking and ad-free video streaming. Since these are the features Indian users are likely interested in vs. the current onboarding privacy focus, which Indian users don't really care about.

**Comment by rmcfadden3** [comment]
Thanks, @timchilds. Brainstorming with @bradleyrichter in DM. Will reply here once we settle on final final.

**Comment by bradleyrichter** [comment]
preview
<img width="366" alt="image" src="https://user-images.githubusercontent.com/13509546/180115990-3a7706d2-ed55-4b7b-bc55-a52050b88e29.png">

I am satisfied.

**Comment by rmcfadden3** [comment]
@timchilds — yeah, I'd be in favor of aligning these 2 messages. So tool-tip could be:

- **Header —** Type a website name or URL
- **Body —** See the Brave difference: Block ads. Save data. Stream faster.

With some body variations like:
- See Brave in action: Block ads. Save data. Stream faster. On every page, every video.
- See Brave in action: Block ads. Save data. Stream faster. On every page & video.
- Brave in action: Block ads. Save data. Load faster. On every page, video, or stream.
- See Brave in action: Block ads. Save data. Stream faster.

CC @bradleyrichter to vet these ideas as well.

**Comment by bradleyrichter** [comment]
I like this. Let's proceed.

**Comment by kjozwiak** [comment]
@Uni-verse @srirambv just a heads up that the correct strings/text are mentioned via https://github.com/brave/brave-browser/issues/24111#issuecomment-1190962959 & https://github.com/brave/brave-browser/issues/24111#issuecomment-1192120758. Some more context via https://github.com/brave/brave-core/pull/14327#issuecomment-1215675457.

The body of the `default browser` page via onboarding will be checked via https://github.com/brave/brave-browser/issues/24677.

**Comment by kjozwiak** [comment]
The above will require `1.43.72` or higher for `1.43.x` verification. We'll also need to check if these new strings were translated once we get translations merged into `1.43.x.`. Believe we should be ordering the new translations sometime early next week.

**Comment by Uni-verse** [comment]
Verified on `Samsung GS 21` & `Samsung Galaxy Tab S7` using

```
Brave	1.43.74 Chromium: 104.0.5112.102 (Official Build) beta (64-bit) 
Revision	8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}
OS	Android 12; Build/SP1A.210812.016
```
- Verified default browser updated copy matches https://github.com/brave/brave-browser/issues/24111#issuecomment-1190962959 with India locale
- Verified URL modal copy header and body matches final design spec https://github.com/brave/brave-browser/issues/24111#issuecomment-1192120758 with India locale

Default Browser (Mobile) | URL modal (Mobile)
-|-
![screenshot-1660859843284](https://user-images.githubusercontent.com/17885425/185502710-cffbf7f1-d152-4b0e-ad79-e73e38c20006.png) | ![screenshot-1660859856967](https://user-images.githubusercontent.com/17885425/185502717-e71ee4cd-1511-4f3c-bd36-8ea74c5caa11.png)
Default Browser (Tablet) | URL modal (Tablet)
![screenshot-1660859314615](https://user-images.githubusercontent.com/17885425/185502963-bbaabbfe-2d24-4b55-b45d-5d6876b33b03.png) | ![screenshot-1660859344574](https://user-images.githubusercontent.com/17885425/185502968-c798c4d1-c3cf-4fe0-9dab-0fb164b4a1d4.png)

**Comment by kjozwiak** [comment]
Labelled as `QA/Test-All-Device-Types` as UI tends to behave/look differently on mobile vs tablet devices. Definitely worth checking the tablet to make sure things are looking correct 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+` running `Android 12` using the following build(s):

```
Brave | 1.45.12 Chromium: 105.0.5195.68 (Official Build) canary (32-bit)
--- | ---
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | Android 12; Build/SP1A.210812.016
```

**`Example`** | **`Example`**
----------------|----------------
![Screenshot_20220831-000837_Brave - Nightly](https://user-images.githubusercontent.com/2602313/187591400-ccb3f391-fadf-4a33-a423-2dd04047ee74.jpg) | ![Screenshot_20220831-001115_Google](https://user-images.githubusercontent.com/2602313/187591409-36edd8f0-4895-4c38-9de0-03736badd9af.jpg)
![Screenshot_20220831-001011_Brave - Nightly](https://user-images.githubusercontent.com/2602313/187591433-8c7374ab-3b88-4eca-afd8-e36c8a561e5d.jpg) | ![Screenshot_20220831-001213_Google](https://user-images.githubusercontent.com/2602313/187591439-633aceab-67b1-40c1-a910-aa0efa8031d9.jpg)
