### ISSUE TITLE
Disable "Save" button when adding a new site in NTP list of websites when no text is entered 

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#24128]
## Steps to Reproduce

   1. Open a new tab page
   2. Click on "Add a website"
   3. See modal

## Actual result:

<img width="480" alt="image" src="https://user-images.githubusercontent.com/15734630/179809589-1d0d52fe-6f49-4477-b354-c227321730ad.png">

## Expected result:
The "Save" button should be disabled until the user enters at least the URL of the site.

## Brave version (brave://version info)

Version 1.43.29 Chromium: 103.0.5060.114 (Official Build) nightly (arm64)

**Comment by rebron** [comment]
cc: @fallaciousreasoning

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.43.54 Chromium: 104.0.5112.69 (Official Build) beta (64-bit)
-- | --
Revision | 7ce2902023c722af8564068e6b26e934b83fd774-refs/branch-heads/5112@{#1213}
OS | Windows 11 Version 21H2 (Build 22000.795)
```

#### Case 1: Click `...`

1. Install 1.43.54
2. launch Brave
3. visit a websites (`bbc.com`)
4. open a new tab page
5. `bbc.com` is added to NTP
6. click `...` in the same view box/row as the websites    
7. click `Add site`
8. do not enter website information in the modal
9. confirmed `Save` button is disabled 
10. add website information in the modal (`abcnews.com`)
11. confirmed `Save` is enabled after entering URL


Step 8|Step 11
----|----
<image width="950" alt = "step 8" src="https://user-images.githubusercontent.com/98358127/182244288-ee6774bf-9427-4e82-84b9-49466a70c9fa.png">|<image width="950" alt = "step 8" src="https://user-images.githubusercontent.com/98358127/182247495-87b01686-e1d9-486a-89d4-fa79233229e9.png">


#### Case 2: Click Show Favorites

1. Continue from case 1
2. click `...` in the same view box/row as the websites 
3. click  `Show favorites`
4. click `Add site` (+) 
5. add website information in the modal (`usatoday.com`)
6. confirmed `Save` is enabled after entering URL
7. website added to NTP

Step 3|Step 6|Step 7
-----|-----|-----
<image width="950" alt = "step 3" src="https://user-images.githubusercontent.com/98358127/182247600-b37031aa-8d34-4140-94c1-d225726fa6dc.png">|<image width="950" alt = "step 6" src="https://user-images.githubusercontent.com/98358127/182247939-777a77f6-a9e2-4c66-a377-3a8ee2800299.png">|<image width="950" alt = "step 8" src="https://user-images.githubusercontent.com/98358127/182247996-0313d0e9-43b3-4e96-b9bb-f9b7c34ca80c.png">
