### ISSUE TITLE
Add Filecoin to list of buy options on Ramp

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#24123]
It's now become available. see #ramp-shared slack channel.
## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.43.79 Chromium: 104.0.5112.102 (Official Build) beta (64-bit)  
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | Linux

- Verified steps from [brave/brave-core#14236](https://github.com/brave/brave-core/pull/14236)
- Verified Filecoin is available to buy via Ramp

https://user-images.githubusercontent.com/17010094/186168806-15388c7d-df81-4ccd-97d0-a98d846d08a6.mp4



------------------------
Verification passed on

Brave | 1.43.79 Chromium: 104.0.5112.102 (Official Build) beta (64-bit)  
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | Windows 11 Version 21H2 (Build 22000.795)

- Verified steps from [brave/brave-core#14236](https://github.com/brave/brave-core/pull/14236)
- Verified Filecoin is available to buy via Ramp

https://user-images.githubusercontent.com/17010094/186169087-cace65f0-735c-4805-8c9a-e48f26585bed.mp4


------------------------
Verification passed on

Brave | 1.43.79 Chromium: 104.0.5112.102 (Official Build) beta (64-bit) 
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [brave/brave-core#14236](https://github.com/brave/brave-core/pull/14236)
- Verified Filecoin is available to buy via Ramp

https://user-images.githubusercontent.com/17010094/186169291-f0821fe7-46cc-4bdd-85de-7baf9a847fb1.mov
