### ISSUE TITLE
[Sync] Warn if OS Keychain is locked or impossible to decrypt sync code words

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#24121]
If OS Keychain is locked and/or impossible to decrypt sync code words, then sync doesn't work.
Also there is a crash when trying to display QR code.

Steps to reproduce:
1. Setup sync chain
2. Exit browser
3. Lock the keychain
4. Launch browser and deny keychain access
5. Show sync code words.
 Actual - there is one word.
 Expected not to have any words.
6. Show QR code
 Actual - crash happens
 Expected not to crash at least.

Required:
- display no words in such case;
- do not have a crash;
- provide additional info about Keychain state and code words decryption result in sync-internals.

Reproduced on Ubuntu and macOS.

**Comment by kjozwiak** [comment]
The above will require `1.43.83` or higher for `1.43.x` verification 👍

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.43.84 Chromium: 105.0.5195.68 (Official Build) (x86_64)
-- | --
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | macOS Version 11.6.8 (Build 20G730)
