### ISSUE TITLE
Support online/offline play

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#24137]
Even if user don't cache playlist item, it should be playable.
And item cache can be toggled.

- [ ] Make it playable when it's not cached

---

- If there's a locally cached media file, we play it. <video src="chrome-data://...">
- If there's no cache media file, we try to play video from video url we detected, but not cache. So, <video src="https://foo.com/detected_video.mp4" will be used.

**Comment by Brandon-T** [comment]
> https://github.com/brave/brave-ios/blob/65f165a370cdaf56ec8d383272f8f7b8dca17feb/Client/Frontend/Browser/Playlist/Controllers/PlaylistCarplayController.swift#L662

https://github.com/brave/brave-ios/blob/96d39c67aa630d7004121db35e493a95d07c0adc/Client/Frontend/Browser/Playlist/Utilities/PlaylistMediaStreamer.swift#L95

When an item is not cached locally, iOS uses an invisible web-view to load the PageURL, then retrieve the video from the page again. If it cannot, it considers the item `expired`.

**Comment by bridiver** [comment]
This ticket is a bit vague about exactly what should happen when a media file has been deleted locally so here is my understanding:
1. Thumbnail is never deleted because the size is trivial
2. If the media file is deleted, we attempt to reload it into the local cache
3. If it cannot be reloaded then the item is expired

Is that correct? What exactly should be displayed to the user if the item is expired?

**Comment by bridiver** [comment]
also what should happen if the user is offline, but tries to play a file that isn't cached?

**Comment by sangwoo108** [comment]
> This ticket is a bit vague about exactly what should happen when a media file has been deleted locally so here is my understanding:
> 
> 1. Thumbnail is never deleted because the size is trivial
> 2. If the media file is deleted, we attempt to reload it into the local cache
> 3. If it cannot be reloaded then the item is expired
> 
> Is that correct? What exactly should be displayed to the user if the item is expired?

Sorry for poor explanation here. The current state is

1. If there's locally cached media file, we play it. `<video src="chrome-data://...">`
2. If there's no cache media file, we try to play video from video url we detected, but not cache. So, `<video src="https://foo.com/detected_video.mp4"` will be used.

Recaching or Redetecting is not discussed or implemented yet.

**Comment by sangwoo108** [comment]
> 
also what should happen if the user is offline, but tries to play a file that isn't cached?

This case is also not discussed yet. Now @rebron is on the specification. https://docs.google.com/document/d/1A7Bv1IAD8RiMBnexV1NpNHDHCPBUJ7_uZ3_W6ntn4yg/edit#heading=h.ozg8nwll8ni5
