### ISSUE TITLE
Enable solana support by default

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#24133]

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.42.96 x64 build
- Verified Solana support is enabled by default on a clean install
- Verified Solana support is enabled for a wallet on a upgrade install
----------
Verification passed on Samsung Tab A with Android 10 running 1.42.96 x64 build
- Verified Solana support is enabled by default on a clean install
- Verified Solana support is enabled for a wallet on a upgrade install
