### ISSUE TITLE
Import Opera passwords for OSX doesn't work

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#24130]
Encryption failed for osx

**Comment by bsclifton** [comment]
Related https://github.com/brave/brave-browser/issues/24343

**Comment by kjozwiak** [comment]
The above will require `1.43.77` or higher for `1.43.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.43.78 Chromium: 104.0.5112.102 (Official Build) beta (x86_64)
-- | --
Revision | 8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}
OS | macOS Version 11.6.8 (Build 20G730)

Followed my steps to reproduce from https://github.com/brave/brave-core/pull/14663#issuecomment-1220983347.

#### Confirmed I was able to import and use all saved passwords from Opera

example | example | example | example | example | example
---------|----------|---------|----------|---------|----------
<img width="1214" alt="Screen Shot 2022-08-22 at 10 05 41 AM" src="https://user-images.githubusercontent.com/387249/185979440-e1594aa7-7e90-4a8e-80f4-7148fa41980f.png"> | <img width="1312" alt="Screen Shot 2022-08-22 at 10 05 46 AM" src="https://user-images.githubusercontent.com/387249/185979454-9820c9f8-b0ff-433f-a132-eacc7279df72.png"> | <img width="1197" alt="Screen Shot 2022-08-22 at 10 05 57 AM" src="https://user-images.githubusercontent.com/387249/185979463-b58a78e4-a029-40e9-af79-c351b0287f9e.png"> | <img width="1312" alt="Screen Shot 2022-08-22 at 10 06 06 AM" src="https://user-images.githubusercontent.com/387249/185979466-a00c0777-ad59-4d5d-bcc1-1a2beed0b6a0.png"> | <img width="1199" alt="Screen Shot 2022-08-22 at 10 06 27 AM" src="https://user-images.githubusercontent.com/387249/185979469-02bac218-a84d-4500-a8a1-662e94f7fe60.png"> | <img width="1312" alt="Screen Shot 2022-08-22 at 10 06 34 AM" src="https://user-images.githubusercontent.com/387249/185979476-6ca4bbb0-d0af-4d1a-8ee1-392e37c9965a.png">

**Comment by LaurenWags** [comment]
Updated to `release-notes/exclude` as this is a follow up to the original implementation of Vivaldi import which will be included in the release notes via https://github.com/brave/brave-browser/issues/23704)).
