### ISSUE TITLE
Inline Tip button on Twitter is misaligned (July 2022)

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#24134]
## Description

![image](https://user-images.githubusercontent.com/11497541/179855564-7a96a0ea-c4bd-46c7-8547-71be9ee57354.png)

@LaurenWags and @pes10k reproduced.

**Comment by emerick** [comment]
@LaurenWags Could you give me a sample URL where this is happening? I've never seen that "Retweets, Quote Tweet, Likes" message before. I have icons in that area (assuming I'm looking at the right area...):

![image](https://user-images.githubusercontent.com/5033691/180808797-5e137cf1-4e2a-49a6-97c5-4b311b874e03.png)

**Comment by LaurenWags** [comment]
@emerick try this link: https://twitter.com/realhamed/status/1549429088913428480?s=20&t=gJEop-TdhIzsayUtRUGykg

**Comment by emerick** [comment]
@LaurenWags That repro'ed, thanks!

**Comment by LaurenWags** [comment]
@emerick yep - that makes perfect sense 👍🏻

**Comment by LaurenWags** [comment]
Verified using dev component for:

```
Brave Local Data Updater - Version: 1.0.601
```

Confirmed Tip button is aligned as expected using link from https://github.com/brave/brave-browser/issues/24134#issuecomment-1194171479

<img width="1199" alt="Screen Shot 2022-08-04 at 10 28 48 AM" src="https://user-images.githubusercontent.com/28145373/182875042-9ac090c4-1b66-436f-8803-a9d6a1915627.png">
