### ISSUE TITLE
open.spotify.com Problem.

### ISSUE THREAD

**Issue by thanuj10** [brave/brave-browser#2413]
Have you searched for similar issues?
Yes.

## Description 
Spotify Web player does not go to my homescreen and says that i need to activate web player
(Check Screenshot below)

## Steps to Reproduce

   1. Open open.spotify.com 
   2. Log into Spotify
   3. Spotify asks to Enable webplayer.

## Actual result:
Site asks to enable web player. Support link says to enable the option "Allow website to play protected content" option by visiting "chrome://settings/content". Brave already has that enabled but Spotify does not recognize that it is turned on.

## Expected result:
Spotify must allow webplayer to load on the website.

## Reproduces how often: 
Easily Reproducible.

## Brave version (brave://version info)
Brave | 0.59.2 Chromium: 71.0.3578.80 (Official Build) dev (64-bit)

### Reproducible on current release:
Yes. Reproducible on latest Dev release (0.59.2)

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
No.
- Is the issue reproducible on the latest version of Chrome?
No. 
Not reproducible on latest Chrome Canary too. 

### Additional Information
N/A

https://i.ibb.co/s64n4p7/Screenshot-2.png

**Comment by eljuno** [comment]
Duplicate of #1391

You also may want to try https://github.com/brave/brave-browser/issues/1391#issuecomment-435530032
