### ISSUE TITLE
Enable features rolled out to 100% via Griffin by default in code and cleanup Griffin seed

### ISSUE THREAD

**Issue by goodov** [brave/brave-browser#24148]
```
EphemeralStorageStudy
PermissionLifetimeStudy
PermissionLifetimeReleaseStudy
FirstPartyEphemeralDomainBlockStudy
DisableBlobPartitioning
PartitionConnectionsByNetworkIsolationKeyStudy
PartitionBlinkMemoryCacheStudy
ForceDisableBlinkFeatures
```

https://bravesoftware.slack.com/archives/C01LKMP6X36/p1658272711054049?thread_ts=1658182146.056129&cid=C01LKMP6X36

**Comment by pes10k** [comment]
@goodov just checking, is this complete? Can we close this out?

**Comment by goodov** [comment]
https://github.com/brave/brave-variations/pull/515 is not merged for some reason. I updated it to target the current beta version so we can merge it again.

cc @kjozwiak let's merge this already. Such change shouldn't require any tests from you.

Here's the previous discussion about this PR 
https://bravesoftware.slack.com/archives/C01LKMP6X36/p1678984039029489?thread_ts=1670621494.836799&cid=C01LKMP6X36

**Comment by kjozwiak** [comment]
Labelling this as `QA/Yes` but also `QA/Blocked` as we'll be removing the studies mentioned via https://github.com/brave/brave-browser/issues/24148#issue-1310455503 from the `seed` file once `1.63.x` goes live. We'll ping @goodov once `1.63.x` goes out so we can remove them from both `main` & `production`. We'll use this issue as a reminder so it doesn't slip through the cracks once `1.63.x` goes out.

**Comment by kjozwiak** [comment]
Removing the `QA/Blocked` & `QA/Yes` as https://github.com/brave/brave-variations/pull/936 was merged into `production`.
