### ISSUE TITLE
Enable debounce by default

### ISSUE THREAD

**Issue by pilgrim-brave** [brave/brave-browser#24159]
As per recent team discussion, debouncing should graduate to be enabled by default (but still technically "behind" a feature flag so we can shut it off via variations server if something goes horribly wrong).

**Comment by pilgrim-brave** [comment]
QA test plan: https://dev-pages.brave.software/navigation-tracking/debouncing.html

**Comment by kjozwiak** [comment]
The above requires `1.42.81` or higher for `1.42.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.42.81 Chromium: 104.0.5112.69 (Official Build) (x86_64)
-- | --
Revision | 7ce2902023c722af8564068e6b26e934b83fd774-refs/branch-heads/5112@{#1213}
OS | macOS Version 12.5 (Build 21G72)
```

**Comment by Uni-verse** [comment]
Verification in progress on Android ARM using 
```

Brave	1.42.81 Chromium: 104.0.5112.69 (Official Build) (64-bit) 
Revision	7ce2902023c722af8564068e6b26e934b83fd774-refs/branch-heads/5112@{#1213}
OS	Android 12; Build/SP1A.210812.016
```

**Comment by Uni-verse** [comment]
Verification in progress on `Samsung Tab S7` using 
```

Brave	1.42.81 Chromium: 104.0.5112.69 (Official Build) (64-bit) 
Revision	7ce2902023c722af8564068e6b26e934b83fd774-refs/branch-heads/5112@{#1213}
OS	Android 12; Build/SP1A.210812.016
```

Version 1.41.100

- Confirmed debouncing is disabled by default on 1.41.x without re-launching browser using test page - https://dev-pages.brave.software/navigation-tracking/debouncing.html
- Confirmed for debouncing to work requires re-starting brave app.

Default | Base64 | Regex | version
-|-|-|-


Version 1.42.81

- Confirmed debouncing is working on 1.42.81 without re-starting browser.

Default | Base64 | Regex
-|-|-
