### ISSUE TITLE
Update Brave translate icon on URL bar to replace Chromium default

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#24150]
## Description 

Currently, Brave translate shows an icon in the URL bar to offer translations. Desktop browser has chromium's default, and Android has a custom one that doesn't scale too well to be used in Desktop. So we're going to provide a new one that works for both versions.

Related Android ticket: https://github.com/brave/brave-browser/issues/23770

## Steps to Reproduce

Desktop browser 
   1. On nightly, open https://www.heise.de/
   2. See icon for translation

## Actual result:

![image](https://user-images.githubusercontent.com/15734630/179995543-a824fbce-2b8f-44fa-ac52-d898ca50dca8.png)

## Expected result:
New icon will be provided when it's defined

## Desktop Brave version:

Nightly

**Comment by aguscruiz** [comment]
@rebron Updated icon available here:
Light mode: https://www.figma.com/file/tLXWGCpNoiJxDZDdpfordj/Desktop-Settings?node-id=2625%3A70968
Dark mode: https://www.figma.com/file/tLXWGCpNoiJxDZDdpfordj/Desktop-Settings?node-id=2625%3A71522

![image](https://user-images.githubusercontent.com/15734630/180215438-b353ae4d-9f23-445e-b5ad-db6ad4cf30f5.png)

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.43.70 Chromium: 104.0.5112.81 (Official Build) beta (x86_64)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | macOS Version 11.6.8 (Build 20G730)

#### Used the reference icons from https://github.com/brave/brave-browser/issues/24150#issuecomment-1191435166

### Steps:
1. installed `1.43.70`
2. launched Brave
3. loaded `https://www.spiegel.de/`
4. confirmed new icon asset in both `Light` and `Dark` modes

`Light` | `Dark`
--------|--------
<img width="1312" alt="Screen Shot 2022-08-15 at 11 48 10 AM" src="https://user-images.githubusercontent.com/387249/184698075-a458b2ce-7ca9-4f72-b89a-46dec286bb84.png"> | <img width="1312" alt="Screen Shot 2022-08-15 at 11 48 24 AM" src="https://user-images.githubusercontent.com/387249/184698093-03f6d3d2-f36a-450e-a023-6e1dcb26ce95.png">

**Comment by Uni-verse** [comment]
Verification in progress on `Samsung GS 21` running `Android 12` using 

```
Brave	1.43.71 Chromium: 104.0.5112.81 (Official Build) beta (64-bit) 
Revision	5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS	Android 12; Build/SP1A.210812.016
```
Specs: https://docs.google.com/document/d/1LBmoyUveZaMcnycpRqg91lhzZFjDx_19zM3x6ulNpHg/edit?usp=sharing

- Verified `translation icon` is updated to spec and is displayed in the translate bar 
- Verified new translate asset in the menu in `light` and `dark` mode. 
- Verified translate icon placement under `find in page` 

Dark Mode | Light Mode
-|-
![screenshot-1660773572831](https://user-images.githubusercontent.com/17885425/185251148-6b0bee65-0905-4958-b026-0259c327a052.png) | ![screenshot-1660773609548](https://user-images.githubusercontent.com/17885425/185251154-b689daee-bf73-44ff-83d6-f5c80f111d4f.png)
![screenshot-1660773849296](https://user-images.githubusercontent.com/17885425/185251545-899e4ec1-9dfe-4c8e-9e6d-064fd1278990.png) | ![screenshot-1660773835504](https://user-images.githubusercontent.com/17885425/185251541-741e77a4-14f0-4257-bb6d-e96a61bff3e7.png)

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy Tab S7` running `Android 12` using 

```
Brave	1.43.71 Chromium: 104.0.5112.81 (Official Build) beta (64-bit) 
Revision	5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS	Android 12; Build/SP1A.210812.016
```
Specs: https://docs.google.com/document/d/1LBmoyUveZaMcnycpRqg91lhzZFjDx_19zM3x6ulNpHg/edit?usp=sharing

Preconditions: 
1. Enable Brave Translate-go flag
2. Enable Chromium translate flag
3. Relaunch browser

- Verified `translation icon` is updated to spec and is displayed in the translate bar 
- Verified new translate asset in the menu in `light` and `dark` mode. 
- Verified translate icon placement under `find in page` 

Dark Mode | Light Mode
-|-
![screenshot-1660774424220](https://user-images.githubusercontent.com/17885425/185253072-aa7a9067-dd0c-4fa6-82b9-d52dd53c1700.png) | ![screenshot-1660774404468](https://user-images.githubusercontent.com/17885425/185253067-885405c1-40fb-4b7e-b5d8-41e0bfe7c348.png)
