### ISSUE TITLE
Solana: Implement Solana send request

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#24156]

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.42.96 x64 build
- Verified able to send SOL token from one address to other
- Verified able to send SPL token from one address to other


Oppo Reno 5 (Android 12.1) | Samsung Tab A (Android 10)
-- | -- 
<video src=https://user-images.githubusercontent.com/17010094/184883584-75f9bd29-6dc7-46cf-b93c-cffa2863056d.mp4> | <video src=https://user-images.githubusercontent.com/17010094/184885494-905deea0-2b5f-4c8c-88bb-8f4f6e77876a.mp4>
