### ISSUE TITLE
Fix Brave Ads layering violations

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#24163]
Set `check_includes` to `true` in `components/brave_ads/browser/BUILD.gn` and `npm run gn_check` to see a list of layering violations

**Comment by tmancey** [comment]
Closing as stale because we are raising issues for individual layering violations

**Comment by LaurenWags** [comment]
@tmancey can this one be marked `QA/No`?

**Comment by tmancey** [comment]
@LaurenWags changed to QA/No, thanks.
