### ISSUE TITLE
Browser Closes Randomly

### ISSUE THREAD

**Issue by Cloverwave** [brave/brave-browser#24165]
Nothing complicated.

I recently watched the 2018 Tetris Effect playstation trailer, i was instantly hooked.
So, i went to github to see if I could pirate it, (couldn't). Broadening my search,
I searched Tetris on Github and it instantly closed. Did this many times, same result.

halp?
(no idea what is wrong with this).

**Comment by Ryan-Goldstein** [comment]
Also reported here: https://github.com/brave/brave-browser/issues/24164

**Comment by rebron** [comment]
Closing as dupe of #24164
