### ISSUE TITLE
Change brave://bravesync to brave://sync

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#2416]
brave://bravesync is harder to type, remember, doesn't look as good, and is repetitive.

**Comment by GeetaSarvadnya** [comment]
Verification passed on 


Brave | 0.59.6 Chromium: 71.0.3578.80 (Official Build) beta (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Windows

- Verified `brave://sync` which redirects to Brave Sync page
  
![image](https://user-images.githubusercontent.com/38657976/49932880-3afc0080-fef0-11e8-81e2-340dce4aaaa7.png)
- Verified `brave://bravesync` doesn't redirects to Brave Sync page anymore.
