### ISSUE TITLE
Brave crashes when using GitHub's focus search bar

### ISSUE THREAD

**Issue by df327** [brave/brave-browser#24164]
## Description 
After updating to [Release v1.41.99 (Chromium 103.0.5060.134)](https://github.com/brave/brave-browser/releases/tag/v1.41.99) (current latest stable version), Brave browser started to crash when using the GitHub focus search bar.

## Steps to Reproduce
   1. Go to https://github.com/
   2. Press the `s` or `/` key on your keyboard to focus on the search bar
   3. Type in anything and press the `Enter` key on your keyboard, Brave will crash every time you do this

## Actual result:
The Brave browser crashes.

## Expected result:
The focus search bar should just work, I do not understand why this causes Brave to crash.

## Reproduces how often: 
All the time.

## Brave version (brave://version info)
1.41.99 Chromium: 103.0.5060.134 (Official Build) (64-bit) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes.
- Can you reproduce this issue with the beta channel? No.
- Can you reproduce this issue with the nightly channel? No.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No.
- Does the issue resolve itself when disabling Brave Rewards? No.
- Is the issue reproducible on the latest version of Chrome? Not sure.

## Miscellaneous Information:
None.

**Comment by DemonWolfFang** [comment]
Can reproduce on Linux Mint 20.3, also crashes when attempting to sign into multiple websites.

**Comment by Ryan-Goldstein** [comment]
Can reproduce easily on Windows 11 as well.

**Comment by rebron** [comment]
crashid: dbb10000-0d65-8e08-0000-000000000000

**Comment by yrliou** [comment]
Crash ID with symbols: 1ab60000-0d65-8e08-0000-000000000000

**Comment by GeetaSarvadnya** [comment]
Verifiation PASSED on

```
Brave | 1.41.100 Chromium: 103.0.5060.134 (Official Build) (64-bit)
-- | --
Revision | 8ec6fce403b3feb0869b0732eda8bd95011d333c-refs/branch-heads/5060@{#1262}
OS | Windows 10 Version 21H2 (Build 19044.1826)

```
- Reproduced the crash issue in `1.41.99` 
- Issue is fixed and working fine in `1.41.100`
![Crash issue](https://user-images.githubusercontent.com/38657976/180135151-ca8e8dc6-2eea-4b1c-a3b2-1e3198b31df4.gif)

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.41.100 x64 build
- Verified steps from issue description
- Verified no crash when searching on Github focus bar
- Verified no crash when viewing both desktop page or mobile page

**Comment by jiripospisil** [comment]
@srirambv Most likely the same issue but would be nice to make sure https://community.brave.com/t/brave-is-crashing-after-clicking-in-duckduckgo-links/416611

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.41.100 Chromium: 103.0.5060.134 (Official Build) (arm64) 
Revision	8ec6fce403b3feb0869b0732eda8bd95011d333c-refs/branch-heads/5060@{#1262}
OS	macOS Version 12.4 (Build 21F79)
```

* Reproduced the issue using `1.41.99` (had to restart to pull griffin seed)
* Confirmed using `1.41.100` there was no crash observed when using GitHub's focus search bar

**Comment by lunixxx817** [comment]
Tahoe76011#

**Comment by lunixxx817** [comment]
Tahoe76011#
