### ISSUE TITLE
ENS & Unstoppable Domains: Prompt the user to enable IPFS, if IPFS is disabled. 

### ISSUE THREAD

**Issue by lukemulks** [brave/brave-browser#24166]
## Description 

 - We received a report from the field regarding issues with ENS resolution in Brave, which is also likely applicable to Unstoppable Domains. 

 - In the process of reproducing the issue, we encountered a step in the user journey that isn't very intuitive for users that are not well versed in IPFS/IPNS or URI resolution. 

 - When a user attempts to navigate to an ENS domain, for example, vitalik.eth, they are greeted with a screen notifying them that they need to enable Infura to resolve the domain. 

 - When the user enables Infura, the domain navigates to the associated IPFS/IPNS URI. 

 - If the user has IPFS enabled, the ENS resolves to the associated site as expected, without issue. 

 - However, if the user does not have IPFS enabled via brave://settings/ipfs, when the IPFS URI attempts to resolve, the user receives a "This site can't be reached" error. 
 
The problem: We do not tell a user that does not have IPFS enabled in Brave that they need to enable IPFS to load the site as expected. 

 Suggest we either: 
  - Include a string on the "This site can't be reached" error page when the user does not have IPFS enabled, to notify them that they need to enable IPFS. (we could include a button to enable, similar to what we do for Infura - or potentially associate both items together in one step - "Click to enable Infura and IPFS in Brave" 
  
  - Include a string to notify the user ^ and provide a hyperlink to brave://settings/ipfs for the user to change from the Settings UI. 
  
  I don't recall if we have IPFS enabled by default, but I suspect we don't. Since the crypto domains are paired with IPFS, we may encounter users assuming that we don't support a feature that we support because they're unaware that both Infura and IPFS have to be enabled. 

## Steps to Reproduce

   1. Go to vitalik.eth
   2. Click to enable infura
   3. Observe the "This site can't be reached" error page. 

## Actual result:

"This site can't be reached" error page

## Expected result:
ENS + IPFS site should resolve and display in Brave. 

## Reproduces how often: 

100% without setting enabled. 

## Brave version (brave://version info)

`1.43.29 Chromium: 103.0.5060.114 (Official Build) nightly (64-bit) `

## Version/Channel Information:

- Can you reproduce this issue with the current release? tbd
- Can you reproduce this issue with the beta channel? tbd
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by cypt4** [comment]
I see 2 problems at the moment : 
1) If IPFS is disabled and we navigate to vitalik.eth then error page without meaningful description is shown.
2) If we choose "Ask" ask IPFS resolve method then vitalik.eth navigation ends with remote gateway.

**Comment by cypt4** [comment]
I've created separate issue, https://github.com/brave/brave-browser/issues/24188 for the second one

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.44.73 Chromium: 105.0.5195.68 (Official Build) beta (x86_64)
-- | --
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | macOS Version 13.0 (Build 22A5331f)

### Steps:
1. installed `1.44.73`
2. launched Brave
3. loaded `vitalik.eth`
4. clicked on `Proceed using Infura server`
5. clicked on `Use a Brave local IPFS node`
6. confirmed it loaded `ipfs://bafybeibc7nsbhktzjvplpi4qmzk7kd22yqol3v4thpbhp5yzfspcc56hsi/`
7. new profile
8. loaded `vitalik.eth`
9. clicked on `Proceed using Infura server`
10. clicked on `Use a public gateway`
11. confirmed it loaded `https://bafybeibc7nsbhktzjvplpi4qmzk7kd22yqol3v4thpbhp5yzfspcc56hsi.ipfs.dweb.link/`

step 4 | step 5 | step 6 | step 10
----------|--------|-------|-------
<img width="1312" alt="Screenshot 2022-09-06 at 1 36 41 PM" src="https://user-images.githubusercontent.com/387249/188734712-e381aa13-54e7-494d-9d0c-032e7d16e384.png"> | <img width="1312" alt="Screenshot 2022-09-06 at 1 36 46 PM" src="https://user-images.githubusercontent.com/387249/188734798-a6a8e856-431d-4dc6-8cfc-d6a2e89e8fe8.png"> | <img width="1312" alt="Screenshot 2022-09-06 at 1 36 57 PM" src="https://user-images.githubusercontent.com/387249/188736170-86a2122a-923b-4d48-a721-338fc070a72c.png"> | <img width="1312" alt="Screenshot 2022-09-06 at 1 37 29 PM" src="https://user-images.githubusercontent.com/387249/188736294-e3c4ba75-163e-44fb-bd72-d272fb6cdebc.png">
