### ISSUE TITLE
Fix transaction handling for all custodians

### ISSUE THREAD

**Issue by szilardszaloki** [brave/brave-browser#24189]
We should persist transaction IDs and make use of them when retrying transactions. In the pathological case, a custodian's server has executed the transaction, but the response doesn't reach our client, hence when retrying, we actually create a second transfer.

In most of the places, `transaction_id` is just an unused variable:
- bitFlyer: [ContributionCompleted()](https://github.com/brave/brave-core/blob/2439d8100fa380ef2b5054b3a29ce97e62e5f9bd/vendor/bat-native-ledger/src/bat/ledger/internal/bitflyer/bitflyer.cc#L83-L100), [OnTransferFeeCompleted()](https://github.com/brave/brave-core/blob/2439d8100fa380ef2b5054b3a29ce97e62e5f9bd/vendor/bat-native-ledger/src/bat/ledger/internal/bitflyer/bitflyer.cc#L220-L235)
- Gemini: [ContributionCompleted()](https://github.com/brave/brave-core/blob/2439d8100fa380ef2b5054b3a29ce97e62e5f9bd/vendor/bat-native-ledger/src/bat/ledger/internal/gemini/gemini.cc#L84-L101), [OnTransferFeeCompleted()](https://github.com/brave/brave-core/blob/2439d8100fa380ef2b5054b3a29ce97e62e5f9bd/vendor/bat-native-ledger/src/bat/ledger/internal/gemini/gemini.cc#L221-L236)
- Uphold: [ContributionCompleted()](https://github.com/brave/brave-core/blob/2439d8100fa380ef2b5054b3a29ce97e62e5f9bd/vendor/bat-native-ledger/src/bat/ledger/internal/uphold/uphold.cc#L87-L104), [OnTransferFeeCompleted()](https://github.com/brave/brave-core/blob/2439d8100fa380ef2b5054b3a29ce97e62e5f9bd/vendor/bat-native-ledger/src/bat/ledger/internal/uphold/uphold.cc#L271-L286)

Currently, only Uphold has a 2PC-style transaction API, so we might need development on bitFlyer's and Gemini's end, too.

**Comment by szilardszaloki** [comment]
We can easily fix it for Uphold, since it has a 2PC-style transaction API, so:
1. we can create the transaction via `POST https://api.uphold.com/v0/me/cards/:card-id/transactions`, which returns a transaction ID,
2. save it in DB before committing the transaction,
3. commit the transaction via `POST https://api.uphold.com/v0/me/cards/:card-id/transactions/:transaction-id/commit`,
4. then if we don't hear back from Uphold regarding the outcome (because of a network error, browser not running, etc.), we can recommit it (which doesn't create a second transfer)

bitFlyer and Gemini don't have a 2PC transaction API, but since we are the ones who provide the `transfer_id`/`tx_ref` field in both cases, we can save them in DB before we'd hit the transaction endpoints (`POST https://bitflyer.com/api/link/v1/coin/withdraw-to-deposit-id/request`/`POST https://api.gemini.com//v1/payments/pay`). These endpoints are idempotent, so recommitting a transaction won't trigger the transfer again.

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave | 1.50.91 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | Windows 10 Version 21H2 (Build 19044.2604)

```

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Samsung Galaxy version 12` running `Bravemonoarm64.apk_1.50.101`
