### ISSUE TITLE
IPFS interstitial is not shown when redirect from .eth domains

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#24188]
## Steps to Reproduce
   1. Set IPFS resolve option to "Ask"
   2. Navigate to vitalik.eth
   3. Check omnibox url. Remote gateway is loaded

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.44.29 Chromium: 104.0.5112.81 (Official Build) nightly (x86_64)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | macOS Version 11.6.8 (Build 20G730)

### Steps:

1. installed 1.44.29
2. launched Brave
3. loaded `vitalik.eth`
4. clicked on `Proceed using Infrura server`
5. confirmed I got the interstitial page
6. set `Method to resolve IPFS resources` to `Disabled` on `brave://settings/ipfs`


step 3-4 | step 5 | step 6
---------|--------|-------
 <img width="1312" alt="Screen Shot 2022-08-08 at 4 01 52 PM" src="https://user-images.githubusercontent.com/387249/183528897-a467a113-52ff-4505-b00b-57274d06ab9f.png"> | <img width="1312" alt="Screen Shot 2022-08-08 at 3 56 58 PM" src="https://user-images.githubusercontent.com/387249/183528816-cebbac45-2b9f-475c-8887-e05a53511f7b.png"> | <img width="1250" alt="Screen Shot 2022-08-08 at 3 57 22 PM" src="https://user-images.githubusercontent.com/387249/183529265-1af11a1e-42c3-4b38-b6cd-2b3cad68a43b.png">


7. loaded `vitalik.eth`


Confirmed I got the the following error message:

<img width="1250" alt="Screen Shot 2022-08-08 at 3 57 30 PM" src="https://user-images.githubusercontent.com/387249/183528675-fbc3f104-81ab-40ae-994a-a1089c4e3d25.png">
