### ISSUE TITLE
Ads are not blocked for `--variations-server-url` and `--variations-insecure-server-url`

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#24180]
Follow up to: https://github.com/brave/brave-browser/issues/23336

## Steps to Reproduce

1. Clean profile
1. Run Brave with:
```
'--variations-server-url=https://www.google.com'
`--variations-server-url=https://variations.brave.com/seed`
--variations-insecure-server-url=http://localhost
```
1. Enable rewards and ads
1.. Trigger an ad

## Actual result:

Ads are shown

## Expected result:
Ads are blocked

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.42.74 Chromium: 103.0.5060.134 (Official Build) beta (64-bit)
-- | --
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | Ubuntu 18.04 LTS

cc @jsecretan @tmancey @brave/qa-team

**Comment by tmancey** [comment]
Closing as invalid. I have now updated the test case for https://github.com/brave/brave-core/pull/13695
