### ISSUE TITLE
Linux dist build fails.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#24191]
https://github.com/brave/brave-core/pull/14227 may have broken Linux dist builds:
https://ci.brave.com/view/linux/job/test-brave-browser-build-linux-x64/648/execution/node/237/log/

<pre>
 FAILED: dist/brave.breakpad.syms 
 python3 ../../brave/tools/posix/generate_breakpad_symbols.py --symbols-dir=/home/ubuntu/workspace/test-brave-browser-build-linux-x64-nightly/src/out/Release/dist/brave.breakpad.syms --jobs=16 --build-dir=/home/ubuntu/workspace/test-brave-browser-build-linux-x64-nightly/src/out/Release --binary=\[\"brave\"\] --libchromiumcontent-dir=/home/ubuntu/workspace/test-brave-browser-build-linux-x64-nightly/src/ --clear
 usage: generate_breakpad_symbols.py [-h] --build-dir BUILD_DIR --symbols-dir
                                     SYMBOLS_DIR --libchromiumcontent-dir
                                     LIBCHROMIUMCONTENT_DIR --binary BINARY
                                     --dump-syms-bin DUMP_SYMS_BIN [--clear]
                                     [-j JOBS] [-v]
 generate_breakpad_symbols.py: error: the following arguments are required: --dump-syms-bin
</pre>

**Comment by LaurenWags** [comment]
Moving this issue to `1.42.x - Release` milestone as there was not a `1.41.x - Release #4` build which included this code (do note, it was merged to 1.41.x branch, just not released with 1.41.x).
