### ISSUE TITLE
Selecting Solana on Wallet doesn't show any details on Panel

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#24194]
## Description 
Selecting Solana on Wallet doesn't show any details on Panel

## Steps to reproduce 

   1. Create Solana Account
   2. Select Solana from network dropdown in Wallet portfolio screen
   3. Go back to Dapp and click on Wallet Panel in URL bar, everything is empty 

## Actual result 
<img width=300 src=https://user-images.githubusercontent.com/17010094/180280817-42c8fa83-1486-4cca-8d14-c913b5a2b4eb.jpg>

## Expected result
Show proper details

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 12
   
## Brave version
1.43.39

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @Pavneet-Sing

**Comment by Pavneet-Sing** [comment]
Panels are not part of the Solana MVP so wan't covered by the https://github.com/brave/brave-core/pull/14240 PR,issues and test plans.
Panel should be fixed with https://github.com/brave/brave-browser/issues/23916 issue for Solana support.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.45.88 x64 build
- Verified steps from issue description
- Verified Solana account details on shown on panel

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<img width=290 src=https://user-images.githubusercontent.com/17010094/194922478-a1bf38a3-6475-4c3d-a286-08a9ff6ae1da.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/194922455-702d418e-037f-4708-9ed2-d20b81a73f13.png>
