### ISSUE TITLE
Unable rename Solana Account

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#24193]
## Description 
Unable rename Solana Account

## Steps to reproduce 

   1. Create Solana account
   2. Click edit to rename account
   3. Update account name and save, shows error

## Actual result 

https://user-images.githubusercontent.com/17010094/180281355-81d7e78f-768b-4724-a90a-2ebe897edc04.mp4

## Expected result
Should be able to rename account

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 12
   
## Brave version
1.43.39

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @Pavneet-Sing

**Comment by Pavneet-Sing** [comment]
This is yet to be implemented. Just a note, there is no support for Solana other than the parts we are covering with Solana implementation.

**Comment by srirambv** [comment]
Closing as #24299 has the fix
