### ISSUE TITLE
Phantom uses new provider object

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#24192]
They use `window.phantom.solana` and keep `window.solana` for legacy integration
https://docs.phantom.app/integrating/extension-and-in-app-browser-web-apps/detecting-the-provider
Also updated in wallet-adapter
https://github.com/solana-labs/wallet-adapter/commit/05df19038f6ff131236566bc1c31b45a5f908bf5

We need to support that because no every websites using wallet-adapter would list us so users have to way to interact with brave wallet for those dapps sites. (Ex. https://opensea.io/)

**Comment by kjozwiak** [comment]
The above requires `1.42.81` or higher for `1.42.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.42.81 Chromium: 104.0.5112.69 (Official Build) (64-bit) 
-- | --
Revision | `7ce2902023c722af8564068e6b26e934b83fd774-refs/branch-heads/5112@{#1213}`
OS | Linux

- Verified steps from  [brave/brave-core#14282](https://github.com/brave/brave-core/pull/14282)
- Verified able to prompt for granting permission when selecting Phantom as wallet provider on Dapps

Adapter | Dapps
-- | --
<video src=https://user-images.githubusercontent.com/17010094/182072044-42d03a89-5705-45f0-95f5-0ac6f4ead7db.mp4 /> | <video src=https://user-images.githubusercontent.com/17010094/182072095-d22e4565-9aa8-4784-8aa0-17e39ece7e55.mp4 />

------------------------
Verification passed on

Brave | 1.42.81 Chromium: 104.0.5112.69 (Official Build) (64-bit) 
-- | --
Revision | `7ce2902023c722af8564068e6b26e934b83fd774-refs/branch-heads/5112@{#1213}`
OS | Windows 11 Version 21H2 (Build 22000.795)

- Verified steps from  [brave/brave-core#14282](https://github.com/brave/brave-core/pull/14282)
- Verified able to prompt for granting permission when selecting Phantom as wallet provider on Dapps

Adapter | Dapps
-- | --
<video src=https://user-images.githubusercontent.com/17010094/182068975-62554867-c429-43ac-8620-1a02016ef99f.mp4 /> | <video src=https://user-images.githubusercontent.com/17010094/182068993-ccc43d6a-70aa-4b2a-9239-2d244ceed92e.mp4 />

------------------------
Verification passed on

Brave | 1.42.81 Chromium: 104.0.5112.69 (Official Build) (arm64) 
-- | --
Revision | `7ce2902023c722af8564068e6b26e934b83fd774-refs/branch-heads/5112@{#1213}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [brave/brave-core#14282](https://github.com/brave/brave-core/pull/14282)
- Verified able to prompt for granting permission when selecting Phantom as wallet provider on Dapps

Adapter | Dapps
-- | --
<video src=https://user-images.githubusercontent.com/17010094/182071859-8d53e140-eb7a-4d2c-b2ac-1c3e5565c58b.mov /> | <video src=https://user-images.githubusercontent.com/17010094/182071873-06f97317-8428-449a-b473-ebdff8b360a9.mov />

**Comment by bbondy** [comment]
I think we should change this one to exclude now since we're going to not include window.phantom because of the webcompat issues.

**Comment by darkdh** [comment]
reverted through
1.44.x https://github.com/brave/brave-core/pull/14430
1.43.x https://github.com/brave/brave-core/pull/14432
1.42.x https://github.com/brave/brave-core/pull/14433

and waiting for Phantom to update new provider object other than `window.phantom` so we can follow.

**Comment by darkdh** [comment]
we don't need this anymore because now wallet adapter has [fallback](https://github.com/solana-labs/wallet-adapter/commit/5a274e0a32c55d4376d63a802f0d512947b087af)
