### ISSUE TITLE
YouTube ad's are not blocked sometimes

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#242]
## Description 
YouTube ad's are not blocked sometimes

## Steps to Reproduce

   1. Build from source
   2. Watch YouTube videos
   3. Some ads leak through either as pre-roll or in between stream

 ## Actual result:

![image](https://user-images.githubusercontent.com/17010094/40656734-561ee842-6313-11e8-9fd9-1bab7d16a94f.png)

## Expected result:
All YouTube ads should be blocked
## Reproduces how often: 

Easy(just need to keep watching YT)

## Brave version (about:brave info)

2e9c470

**Comment by bbondy** [comment]
Does it work differently from browser-laptop?

**Comment by srirambv** [comment]
Yes. No pre-roll ad or instream ads are seen on browser-laptop. Once it starts doesn't stop. Have to clear browsing history and start over for it to start blocking ads

**Comment by emerick** [comment]
@srirambv Could you give this another try please? I believe an erroneous file was on our S3 server. If by chance you continue to see the problem, it would be helpful to capture the chrome_debug.log and a screenshot of chrome://components as well if possible. Thanks!

**Comment by srirambv** [comment]
@emerick Not seeing on a clean profile built from 332140d. Closing the issue for now. If it reproduces will capture the details and reopen the issue.

**Comment by bbondy** [comment]
🎉

**Comment by emerick** [comment]
Thanks @srirambv!

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | -- 
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Linux

* No pre-roll ads seen on YT before playback
* No in video ads seen on YT while playback
