### ISSUE TITLE
Move 'Show Brave Rewards icon in...' toggle to BR pane so all BR related controls are in one place

### ISSUE THREAD

**Issue by jenn-rhim** [brave/brave-browser#24204]
![image](https://user-images.githubusercontent.com/4369856/180330943-70f874d7-3c3b-446f-bb1d-ad582398ab3c.png)

**Comment by Miyayes** [comment]
One funny edge case is this:

If user has not yet enabled Brave Rewards, then this is what the Brave Rewards section of brave://settings looks like: 

![image](https://user-images.githubusercontent.com/11497541/180831056-3f3ba25f-f8d8-4049-8008-7db42a5996ce.png)

So, they wouldn't be able to access it without first enabling Brave Rewards (which they might not want to do).

That said, maybe that's acceptable now that we introduced a right-click hide on the BAT icon itself? 

<img src="https://user-images.githubusercontent.com/11497541/180831247-688d68cd-2dcf-4ee3-969c-0dd276a90193.jpg" width=300px>

@jenn-rhim ^^

**Comment by rebron** [comment]
@Miyayes The show/hide Brave Rewards icon setting could still live separately in the Brave Rewards section when Brave Rewards are disabled. Could have the setting sit on top or below what's shown there.

**Comment by Miyayes** [comment]
> @Miyayes The show/hide Brave Rewards icon setting could still live separately in the Brave Rewards section when Brave Rewards are disabled. Could have the setting sit on top or below what's shown there.

That's a good point. We will plop it in as an item under the "Brave Rewards are disabled" section, then. Thanks!

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.44.73 Chromium: 105.0.5195.68 (Official Build) beta (64-bit)
-- | --
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | Windows 11 Version 21H2 (Build 22000.856)
```

#### Case 1: Rewards Disabled

1. Install 1.44.73
2. launch Brave
3. Do not enable rewards
4. open brave://settings/rewards

#### Confirmed `Show Brave Rewards icon in address bar` setting shown in `brave://settings/rewards` and the functionality works as expected (toggle ON/OFF)

toggle `ON`|toggle `OFF`
---|---
<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/188194276-1d780591-7049-4fb5-ad95-56199baee24d.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/188194296-e11f6a09-a4b3-42b0-b898-e7413aba4a26.png">

#### Case 2: Rewards enabled

1. Continue from Case 1
2. Enable Rewards from browser bar
3. open brave://settings/rewards

#### Confirmed `Show Brave Rewards icon in address bar` setting shown in `brave://settings/rewards` and the functionality works as expected (toggle ON/OFF)

toggle `ON`|toggle `OFF`
---|---
<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/188194444-d8e99bd4-d965-425d-ad6b-4fe16eead497.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/188194475-cedbbe43-b333-4808-83a4-65f2e7727f5f.png">

Case 3: Upgrade 1.43.88-->1.44.73

1. Install 1.43.88
2. Enable Rewards
3. `Show Brave Rewards icon in address bar is available and enabled in brave://settings/appearance
4. close the browser 
5. rename profile 
6. install 1.44.73
7. launch Brave
8. open brave://settings/rewards

#### Confirmed `Show Brave Rewards icon in address bar` setting moved from `brave://settings/appearance` to `brave://settings/rewards`

1.43.88(Appearance)|1.43.88(Rewards)|1.44.73(Rewards)
---|---|---
<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/188193659-e34a886c-d245-4ea7-90ea-5cacc69d2fa8.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/188193834-5e489954-353b-4428-ba2a-d4ade3debdb1.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/188190792-e342d3cf-fe6b-4430-939e-7f080ce3a514.png">
