### ISSUE TITLE
Tab Sync - Open Tabs & Send Tab API on iOS

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-browser#24202]
## Description 

**Add support for iOS Chromium Synced Session implementation for Open Tabs and SendTabSyncService implementation for Sending Tabs to different devices so we can sync open tabs with Desktop and send/receive tabs on demand.**

1. Open Tabs API: Create Query functionality for fetching Synced Sessions and List of Distant Tabs information related wrappers for iOS

- Implement GetSyncedSessions functionality which will include identifier/type/name of the sessions and fetch list of DistantTabs which includes url and title of the tab information, and write wrappers for iOS so the information can be presented and used.

2. Open Tabs API observers: Create Observer methods related with OpenTabs API functionality which will allow iOs side to refresh the information when there is update happened in Synced Sessions

3. Send Tab API: Create Fetch functionality for list of synced device which can receive a Tab. In Addition create the functionality of 
sending Tab information to a selected device.

4. Send Tab API observers: Create Observer methods related with Send Tab API functionality which will allow iOS side to fetch Tab information and present them with a Toast or different alert UI.

5. Sync Tab Generator API and Brave Sync Tab: Create a Tab interface which allows setting URL and title and which will sync automatically with Synced Session using WebState. And API which includes creation of this Synced Tab for iOS bridge.

6. Sync Profile : Add OpenTabs to Sync Profile so we can choose open tabs type to sync from iOS side

Corresponding iOS Ticket: https://github.com/brave/brave-ios/issues/3229

**Comment by bsclifton** [comment]
Removing milestone as PR is still open; we can set to Nightly when we merge 😄 (and then uplift if needed)
