### ISSUE TITLE
Remove `std::function<>` from further `Ledger` flows

### ISSUE THREAD

**Issue by szilardszaloki** [brave/brave-browser#24200]
Part3 of https://github.com/brave/brave-browser/issues/18560.

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```
Brave | 1.43.74 Chromium: 104.0.5112.102 (Official Build) beta (64-bit)
-- | --
Revision | 8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}
OS | Windows 10 Version 21H2 (Build 19044.1889)
```

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using 
```
Brave | 1.43.74 Chromium: 104.0.5112.102 (Official Build) beta (64-bit)
-- | --
Revision | 8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}
OS | Linux
```
- Verified the test plan from https://github.com/brave/brave-core/pull/14286

<details>
<summary>Create a wallet flow_PASSED</summary>

- Confirmed that `rewards wallet` can be created via `rewards setting page(hamburger menu)`, `BR panel` and `NTP`
- Confirmed `AC`, `monthly tips`, `one-time tips` are processed
- Confirmed `custom tips` can be sent to verified pubs and tips are processed successfully
- Confirmed tips sent to unverified pubs are listed in pending contribution table
- Confirmed `monthly tips` are processed even when the `AC` switch is OFF
- Confirmed that `one time` tips and `monthly tips` can be sent when AC switch is OFF 
- Confirmed monthly tips are processed when AC switch is turned OFF
- Confirmed re-enable AC switch doesn't lose the rewards data

Example | Example | Example | Example
-- | -- | -- | --
<image width="950" alt="recent" src="https://user-images.githubusercontent.com/98358127/186004230-13a0f8d2-dd87-40e0-9dc0-737725967097.png">|<image width="950" alt="Pending contribution" src="https://user-images.githubusercontent.com/98358127/186004311-f2298533-7f77-44e7-9d90-a921543a2f01.png">|<image width="950" alt="Statement" src="https://user-images.githubusercontent.com/98358127/186004446-853cd3d4-bc20-42b4-bb34-83783c4ea983.png">|<image width="950" alt="pending contributions stmt" src="https://user-images.githubusercontent.com/98358127/186005151-dedeb4ec-2896-44c7-b6f3-db67512c737b.png">

**_Notifications:_**

Example | Example
-- | --
<image width="950" alt="Monthlytips" src="https://user-images.githubusercontent.com/98358127/186006050-d3deac8f-376c-435c-babe-23ecf3c8ef75.png">|<image width="950" alt="autocontribute" src="https://user-images.githubusercontent.com/98358127/186006291-0730a768-e7cf-4b81-a697-d15ec00ace7a.png">

</details>

<details>
<summary>BAT to USD exchange rate_tipping banner_PASSED</summary>

- Confirmed BAT to USD exchange rate is shown correctly on one-time tipping banner
- Confirmed BAT to USD exchange rate is shown correctly on monthly tipping banner

**_USD conversion on tipping banner:_**

one-time|monthly|custom
----|-----|----
<image width="950" alt="one-time" src="https://user-images.githubusercontent.com/98358127/186007067-9152eb87-70c0-41df-8a6d-d217f17d44cd.png">|<image width="950" alt="monthly" src="https://user-images.githubusercontent.com/98358127/186007046-0def4660-3d06-4b67-ad08-68ad8b68b67d.png">|<image width="950" alt="custom" src="https://user-images.githubusercontent.com/98358127/186007035-45de2f1d-ce08-4269-9102-c049296280c2.png">

**_USD conversion_** 
Example | Example | Example|Example|Example|Example
-- | -- | -- | -- | -- | --
<image width="950" alt="1" src="https://user-images.githubusercontent.com/98358127/186009489-9ac06cc0-2467-45e8-8ebc-3066c3546646.png">|<image width="950" alt="2" src="https://user-images.githubusercontent.com/98358127/186009497-3523e316-b0f1-4802-bb92-d8c81fef772e.png">|<image width="950" alt="3" src="https://user-images.githubusercontent.com/98358127/186009535-f2532c25-eb38-4f66-9c0b-7bdc3f8b062f.png">|<image width="950" alt="AC" src="https://user-images.githubusercontent.com/98358127/186011755-b33acded-54bc-4ca9-bd98-f4c1b79def37.png">|<image width="950" alt="OT" src="https://user-images.githubusercontent.com/98358127/186011766-331b2727-6b2e-4204-8e16-3fb097d8cdaa.png">|<image width="950" alt="MT" src="https://user-images.githubusercontent.com/98358127/186011779-fe4d0f25-7d14-4870-abe7-0e24dc12443a.png">

**_USD converstion on all panels_**

Example | Example | Example | Example
-- | -- | -- | --
<image width="950" alt="USD Conversion -Ads" src="https://user-images.githubusercontent.com/98358127/186013094-bf06ad14-800c-4cfe-8df6-3d6bfccf48a8.png">|<image width="950" alt="USD conversion AC" src="https://user-images.githubusercontent.com/98358127/186013093-7de3a26e-f565-403c-83d0-33e5f90153ee.png">|<image width="950" alt="USD Conversion Tops" src="https://user-images.githubusercontent.com/98358127/186013092-39fe95f6-ceaf-4bff-acd7-dafdb872c4f7.png">|<image width="950" alt="Monthly tips" src="https://user-images.githubusercontent.com/98358127/186013095-17d38b0b-86ad-42d9-a645-dcc9012ab93b.png">

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.43.81 Chromium: 104.0.5112.102 (Official Build) (x86_64)
-- | --
Revision | 8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}
OS | macOS Version 12.5.1 (Build 21G83)
```

**Comment by Uni-verse** [comment]
Verification in Progress on Android ARM using the following build: 

Brave	1.43.82 Chromium: 105.0.5195.58 (Official Build) (64-bit) 
Revision	1907e1693887af4463221a10247360b7a056db49-refs/branch-heads/5195_47@{#3}
OS	Android 12; Build/SP1A.210812.016
