### ISSUE TITLE
[hackerone] another IPFS crash bypass

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#24211]
https://hackerone.com/reports/1646204

**Comment by LaurenWags** [comment]
Added `QA/Blocked` label as this is waiting on an uplift before it can be tested in 1.43.x.

**Comment by LaurenWags** [comment]
PR has been uplifted, this requires `1.43.62` or above to test

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.43.62 Chromium: 104.0.5112.81 (Official Build) beta (x86_64)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | macOS Version 11.6.8 (Build 20G730)

Pre-requisite:
* created a minimal testcase based on the HackerOne report
* started a Python HTTP server via: `python3 -m http.server 8080`


### Steps:
1. installed `1.43.62`
2. launched Brave
3. opened a new `Private window`
4. opened a new `Private window w/Tor`
5. opened a new `Guest window`
6. loaded the minimal testcase via localhost:8080 in the above window types

`Private window` | `Private window w/Tor` | `Guest window`
----------------|----------------------|----------------
<img width="1074" alt="Screen Shot 2022-08-08 at 6 18 07 PM" src="https://user-images.githubusercontent.com/387249/183541791-3ee6c7fc-6748-4cb0-b50c-82ce9189e5ba.png"> | <img width="960" alt="Screen Shot 2022-08-08 at 6 10 13 PM" src="https://user-images.githubusercontent.com/387249/183541820-feffec2f-0130-478f-b33f-3672c4e22689.png"> | <img width="960" alt="Screen Shot 2022-08-08 at 6 09 58 PM" src="https://user-images.githubusercontent.com/387249/183541863-316e232d-0d39-4762-a24f-a7921a8f7083.png">
