### ISSUE TITLE
Update ETH icon to use Aurora ETH icon

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#24210]
## Description 
Aurora uses ETH symbol for native Token. 

## Steps to reproduce 

   1. Upgrade to a build that has Aurora network
   2. Native token uses Eth icon rather than native icon

## Actual result 
<img width=300 src=https://user-images.githubusercontent.com/17010094/180397469-7a0adeb9-c03a-48fe-bc53-76021a6b53b6.png>

## Expected result
Use native icons

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 12
   
## Brave version
1.42.76

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

Related desktop issue #24024

**Comment by Pavneet-Sing** [comment]
This has a dependency on https://github.com/brave/brave-browser/issues/28561

**Comment by Pavneet-Sing** [comment]
Note: This outcome will be changed with https://github.com/brave/brave-browser/issues/29227

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.51.87 x64 Beta build
- Verified steps from issue description and [brave/brave-core#17692](https://github.com/brave/brave-core/pull/17692)
- Verified native asset icon for Aurora is updated to show Aurora Icon. 

Oppo Reno 5 (Android 13) | Lenovo Tab (Android 12)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/232076903-fe84e31c-72cb-45cd-a39d-3463babbc992.mp4> | <video src=https://user-images.githubusercontent.com/17010094/232076840-46622892-339c-444d-8299-f5ca9e5e90e5.mp4>
