### ISSUE TITLE
Bookmarks dont appear in android Brave app

### ISSUE THREAD

**Issue by emanueol** [brave/brave-browser#24215]
## Description 
Bookmarks not appearing on my android devices.

## Steps to Reproduce
   1. I added pc + 2 android devices to sync chain.
   2. Android > opening brave app > option bookmarks shows empty screen

## Actual result:
![Screenshot_20220722_121214_com brave browser](https://user-images.githubusercontent.com/8422412/180427693-99a158bd-b0de-464e-bbde-4807305274d0.jpg)

## Expected result:
List of all my bookmarks present in my Google Chrome desktop windows application to appear on synced android devices.

## Reproduces how often: 
Easily reproduced

## Brave version (info found on brave://version)
![Screenshot_20220722_123816_com brave browser](https://user-images.githubusercontent.com/8422412/180431680-7a8f2692-4547-4863-a01a-f2f1a4829dc9.jpg)

## Version/Channel Information:
Latest android app

## Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields?
As im unsure what this is, as i didn't found 1 single toggle named "Brave Shields", so heres screenshots of all options inside Brave android app > Settings > Brave Shields & Privacy

![Screenshot_20220722_122455_com brave browser](https://user-images.githubusercontent.com/8422412/180430356-9ff03fe0-60a0-492c-bdbb-bba2f31cbf62.jpg)

![Screenshot_20220722_122502_com brave browser](https://user-images.githubusercontent.com/8422412/180430407-8d261f47-96d1-49a8-94cd-627edd6bf7a6.jpg)

![Screenshot_20220722_122519_com brave browser](https://user-images.githubusercontent.com/8422412/180430448-e34eb9c4-32cc-4a88-8829-46c4b0aa2b3a.jpg)

![Screenshot_20220722_122530_com brave browser](https://user-images.githubusercontent.com/8422412/180430494-7844c219-e954-4b9b-a9dc-e3354f3a1010.jpg)

![Screenshot_20220722_122556_com brave browser](https://user-images.githubusercontent.com/8422412/180430538-df3a7155-38a9-4016-8030-21bf20ff6d0e.jpg)

![Screenshot_20220722_122722_com brave browser](https://user-images.githubusercontent.com/8422412/180430573-8576e6ba-6fc5-460a-9634-e1b3d40bc884.jpg)

- Does the issue resolve itself when disabling Brave Rewards? I hadn't touched/enabled that option.
- Is the issue reproducible on the latest version of Chrome? 
Problem is not with chrome. Problem is with android app Brave which doesn't show any bookmarks despite its in a sync chain with my main windows pc where i have both Google chrome which then got all information imported Brave website upon first use.

## Miscellaneous Information:

Any solution or workaround? I really enjoy the speed of Brave browser, but while i got bookmarks in brave window application, i dont see the bookmarks in both my android apps with android Brave app.

**Comment by 424344** [comment]
> List of all my bookmarks present in my Google Chrome desktop windows application to appear on synced android devices.

I don't understand: do you want to see your chrome desktop bookmarks on brave android?

**Comment by emanueol** [comment]
Thats the english I wrote you indeed.


Thanks and Kind regards,
Emanuel Oliveira

**Comment by 424344** [comment]
from what I understand you cannot see on brave the bookmarks from a different browser, like chrome.
you can import in brave desktop the bookmarks from chrome, and then sync those bookmarks to brave on android.

**Comment by emanueol** [comment]
You misunderstood what i wrote.. so heres a rephrasing:

all pc chrome bookmarks+passwords+etc got imported in pc brave

now the problem:
pc brave > sync > create chain > show qr
android brave > settings > sync > scan or enter sync code > point phone camera tobthe qd code on mybpc screen

android brave & pc brace sync shows 2 devices in chain

android brave bookmarks list is empty!!!!
I'm assuming this is a bug, as both brave browsers are in sync chain and given chsin created from windows brave on pc which have all bookmarks.

hope this clear your doubt.

**Comment by 424344** [comment]
ok, thank for the clarification. 
on my brave on android device the desktop bookmarks and the mobile bookmarks are separated.
If you only have bookmarks created on desktop then mobile bookmarks folder will be empty.
did you verifiy that the desktop bookmarks folder is really empty?
In your first screenshot you're showing the mobile folder, not the desktop one.

**Comment by emanueol** [comment]
When i click android brave > [3 dots] > bookmarks > i only see > Mobile
bookmarks empty

Where do i see your suggestion of a 2nd place with desktop bookmarks ?

Thanks & Kind Regards,

*Emanuel de Oliveira*

**Comment by 424344** [comment]
on the left of "Mobile bookmarks" there is a little arrow pointing left. 
Tap on the arrow and you should see both the desktop folder and mobile folder.
Now tap on the desktop bookmark folder (I don't remember the exact name)

**Comment by emanueol** [comment]
Oh there they are

> on the left of "Mobile bookmarks" there is a little arrow pointing left. Tap on the arrow and you should see both the desktop folder and mobile folder. Now tap on the desktop bookmark folder (I don't remember the exact name)

Oh there they are ! thanks so much.
