### ISSUE TITLE
Update Settings sidebar icons and colors for consistency

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#24216]
## Description 

We need to update our Settings pages icons for better consistency. Right now we have a mix of filled vs. outline icons that look weird.

What changed is: 
- All the icons in sidebar (even if it looks the same, it has a new bounding box so it should be replaced)
- Size of the icons (from 20px to 24px for better use of margins)
- Size of buttons
- Colors for hover and active states in text / button / left line hint.

## Steps to Reproduce

   1. Open Brave settings
   2. See sidebar icons

## Actual result:

<img width="260" alt="image" src="https://user-images.githubusercontent.com/15734630/180435936-db6fda47-e8ce-49a2-acf2-7a360a2df668.png">

## Expected result:
<img width="612" alt="image" src="https://user-images.githubusercontent.com/15734630/180435789-c13d58e8-d4cb-4499-9857-e7fb18ae8ea0.png">

Design file with icon and color definition
https://www.figma.com/file/tLXWGCpNoiJxDZDdpfordj/Desktop-Settings?node-id=1807%3A31917

**Comment by LaurenWags** [comment]
labelling as `QA/Blocked` until https://github.com/brave/brave-browser/issues/24872 is uplifted to 1.44.x.

**Comment by kjozwiak** [comment]
Removing the `QA/Blocked` as https://github.com/brave/brave-browser/issues/24872 as been uplifted into `1.44.x` via https://github.com/brave/brave-core/pull/15002#pullrequestreview-1098543252.

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using 

Brave | 1.44.86 Chromium: 105.0.5195.127 (Official Build) beta (x86_64)
-- | --
Revision | 912488396852bf658ab32465980c0b93a3c27a83-refs/branch-heads/5195@{#1109}
OS | macOS Version 11.7 (Build 20G817)

### Steps:
1. install `1.44.86`
2. launch Brave
3. open `brave://settings`
4. carefully examine and compare to `1.43.x`


#### Confirmed:
* most icons are replaced; all have a new "bounding box"
* icons are sized slightly larger
* size of buttons (?)
* hover, active, and active w/hover (text, buttons, left-line hint - vertical `|`)

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.44.86 Chromium: 105.0.5195.127 (Official Build) beta (64-bit)
-- | --
Revision | 912488396852bf658ab32465980c0b93a3c27a83-refs/branch-heads/5195@{#1109}
OS | Windows 11 Version 21H2 (Build 22000.978)
```
Steps:

- Install 1.44.86
- launch Brave
- opened `brave://settings`
- compared side bar icons in old icons with new updated Settings sidebar icons
- verified sidebar icons in the page match to Figma designs
- confirmed size of the icons to be 24 px
- confirmed the icon margin 14px
- confirmed most icons are updated
- confirmed colors for normal, hover and active states in text / button / left line hint.


1.43.93 (old)|1.44.86(updated) - PASSED
---|---
<image width="950" alt="14393" src="https://user-images.githubusercontent.com/98358127/190458478-4c08cfdc-10b2-4195-847e-64d5da36ba7b.png">|<image width="850" alt="14486" src="https://user-images.githubusercontent.com/98358127/190458928-205eecca-23d0-48c8-acb6-6da409fd9972.png">

#### Appearance  - PASSED

Dark|Light
----|----
<image width="850" alt="dark" src="https://user-images.githubusercontent.com/98358127/190507077-cbe9a977-cd3d-493e-8a6a-bb94a4f5f851.png">|<image width="850" alt="dark" src="https://user-images.githubusercontent.com/98358127/190507076-dd5855e2-4593-49f4-af0b-61ab93a99305.png">


#### Colors for hover, active states, normal

- open brave://settings
- hover over `Get started` in the sidebar and notice the text color
- click `Get started` and notice the text color

hover|active|normal|light_theme (all 3)
----|----|----|----
<image width="950" alt="hover" src="https://user-images.githubusercontent.com/98358127/190469820-2555a800-ac34-42c8-aee4-43147d022daa.png">|<image width="950" alt="active" src="https://user-images.githubusercontent.com/98358127/190469346-02b6e925-0c08-45f6-a650-78c93d840b5e.png">|<image width="950" alt="inactive" src="https://user-images.githubusercontent.com/98358127/190468891-8da19a44-1737-4acc-bf87-3017b1aead32.png">|<image width="950" alt="hover" src="https://user-images.githubusercontent.com/98358127/190486846-479541f0-c614-43ec-ae26-57f9b6e92e87.png">

### Additionally verified following pages for any missing/updated icons

### Privacy and Security
`brave://settings/privacy`
 
<image width="850" alt="hover" src="https://user-images.githubusercontent.com/98358127/190477411-bbacb62f-bf94-4e47-a848-c31ad265b1fd.png">

`brave://settings/cookies`

<image width="850" alt="hover" src="https://user-images.githubusercontent.com/98358127/190477026-9c4ef814-ecbd-41ac-a98c-906330d67f0a.png">

`brave://settings/security`

Ex1|Ex2|Ex3
----|----|-----
<image width="850" alt="hover" src="https://user-images.githubusercontent.com/98358127/190472713-98c82748-72e6-43a6-a020-140675db4108.png">|<image width="850" alt="hover" src="https://user-images.githubusercontent.com/98358127/190475530-48a31718-1fad-4732-a35b-39d87f11eca9.png">|<image width="850" alt="hover" src="https://user-images.githubusercontent.com/98358127/190475701-d546ad1a-fc75-4091-97e5-93ff28a81182.png">

#### `brave://settings/content`

<image width="850" alt="hover" src="https://user-images.githubusercontent.com/98358127/190472920-d5285175-a478-4da5-9c23-9e5fa05579a1.png">

#### `brave://settings/autofill`

<image width="850" alt="hover" src="https://user-images.githubusercontent.com/98358127/190472567-8da1978e-c929-4a37-aac1-de575d75cdae.png">

#### `brave://settings/importData`

<image width="850" alt="hover" src="https://user-images.githubusercontent.com/98358127/190475951-fad8cdb3-8bf3-41c0-8bfe-813abc9491fb.png">


* https://github.com/brave/brave-browser/issues/25434
