### ISSUE TITLE
Disable Signed Exchange (SXG) support

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#24227]
re @mkarolin 

>   I think disabling kSignedHTTPExchange feature fixes it

**Comment by mkarolin** [comment]
QA STR:

1. Navigate to brave.com with DevTools open on the Network tab
2. Click on the "brave.com" entry in the DevTools resources list
3. Check `Request Headers` section and locate `accept:` header

Current actual result:
`accept:` header contains `application/signed-exchange;v=b3;q=0.9`

Expected result:
`accept:` header **DOES NOT** contain `application/signed-exchange;v=b3;q=0.9`

**Comment by kjozwiak** [comment]
The above requires `1.42.81` or higher for `1.42.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.42.81 Chromium: 104.0.5112.69 (Official Build) (x86_64)
-- | --
Revision | 7ce2902023c722af8564068e6b26e934b83fd774-refs/branch-heads/5112@{#1213}
OS | macOS Version 12.5 (Build 21G72)
```

**Comment by Uni-verse** [comment]
Verification in progress on Android ARM using

```
Brave	1.42.81 Chromium: 104.0.5112.69 (Official Build) (64-bit) 
Revision	7ce2902023c722af8564068e6b26e934b83fd774-refs/branch-heads/5112@{#1213}
OS	Android 12; Build/SP1A.210812.016
```

Reproduced the issue using `1.41.100 Chromium: 103.0.5060.134` and steps from https://github.com/brave/brave-browser/issues/24227#issuecomment-1192877052.

Confirmed issue does not reproduce using `1.42.81 Chromium: 104.0.5112.69` and steps from https://github.com/brave/brave-browser/issues/24227#issuecomment-1192877052.

1.41.100 (Tablet) | 1.42.82 (Tablet)
-|-
![Screen Shot 2022-07-28 at 11 59 10 AM](https://user-images.githubusercontent.com/17885425/181620976-05ee7e56-ebbe-4be0-81c7-8f2a2773b3d7.png) | ![Screen Shot 2022-07-28 at 12 29 53 PM](https://user-images.githubusercontent.com/17885425/181621728-dfb359ba-3896-442e-98ff-8c794f8a3a2d.png)

**Comment by pes10k** [comment]
For future reference, I've added a column for this on https://dev-pages.brave.software/fingerprinting/headers.html too

**Comment by pes10k** [comment]
as context, this post has some of the reasons we should disable SXG

https://brave.com/web-standards-at-brave/6-privacy-sandbox-concerns/
