### ISSUE TITLE
Add ability to inc Bookmarks vs Top Tiles on the NTP

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#24225]
## Description 

Somewhat like iOS but like Desktop, this person is asking if we can have Bookmarks on the NTP vs Top Tiles. 

https://twitter.com/hatsforpelicans/status/1550533013947269122?s=20

**Comment by bsclifton** [comment]
Closing as a duplicate of https://github.com/brave/brave-browser/issues/33845
