### ISSUE TITLE
per site cookie setting isn't retained on browser relaunch, falls back to default global shield setting

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#24221]
## Description 

Per site shield setting does not appear to be retained between relaunches of 1.42.x.

Found while testing https://github.com/brave/brave-browser/issues/8604

## Steps to Reproduce

   1. Clean profile 1.42.x
   2. Navigate to any site
   3. Open shields, change the per site cookie setting to something other than the default
   4. Close site, close browser
   5. Relaunch 1.42.x
   6. Navigate to site again
   7. Open shields

## Actual result:

Your selection is not retained, it shows the default selection of "Block cross-site cookies"

<img width="1191" alt="7-step" src="https://user-images.githubusercontent.com/28145373/180491032-b0e27716-4c28-4b18-8298-ad0302256adc.png">

## Expected result:

Your selection for the site from step 3 should be retained

<img width="1190" alt="3-step" src="https://user-images.githubusercontent.com/28145373/180491055-b118160b-7967-4a43-9812-038d743a695d.png">

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.42.74 Chromium: 103.0.5060.134 (Official Build) beta (x86_64)
-- | --
Revision | 8ec6fce403b3feb0869b0732eda8bd95011d333c-refs/branch-heads/5060@{#1262}
OS | macOS Version 12.4 (Build 21F79)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no, 1.41.100
- Can you reproduce this issue with the beta channel? yes 1.42.74
- Can you reproduce this issue with the nightly channel? no 1.43.42

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron @brave/qa-team 

reproduced by @GeetaSarvadnya @btlechowski

**Comment by rebron** [comment]
cc: @nullhook @petemill @bridiver

**Comment by LaurenWags** [comment]
Could be resolved by https://github.com/brave/brave-browser/issues/24119 which was included in 1.43.34.

Since there was no 1.43.33 build, confirmed https://github.com/brave/brave-browser/issues/24221#issue-1315249443 reproduces with 1.43.32.

Then, using 1.43.34, confirmed https://github.com/brave/brave-browser/issues/24221#issue-1315249443 does not reproduce.

**Comment by LaurenWags** [comment]
Verified this is resolved with the below build. No longer reproduces now that https://github.com/brave/brave-core/pull/14226 was uplifted to 1.42.x.

```
Brave | 1.42.78 Chromium: 103.0.5060.134 (Official Build) beta (x86_64)
-- | --
Revision | 8ec6fce403b3feb0869b0732eda8bd95011d333c-refs/branch-heads/5060@{#1262}
OS | macOS Version 12.5 (Build 21G72)
```

Verified STR from description no longer reproduce with `1.42.78`.

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
Brave | 1.42.78 Chromium: 103.0.5060.134 (Official Build) beta (64-bit)
-- | --
Revision | 8ec6fce403b3feb0869b0732eda8bd95011d333c-refs/branch-heads/5060@{#1262}
OS | Windows 10 Version 21H2 (Build 19044.1826)

```
- Verified the STR from the description and ensured per site cookies settings are retained after browser relaunch
