### ISSUE TITLE
Why only eth is supported for custom networks, and NOTREACHED() causing a crash for SOL

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#24230]
## Description 

Getting a crash (at-least in debug mode) when SOL is used for custom network because of NOTREACHED

https://github.com/brave/brave-core/blob/fc5661c6c1b2383528f5e946e567639f937a0cca/components/brave_wallet/browser/json_rpc_service.cc#L502

```
void JsonRpcService::GetCustomNetworks(mojom::CoinType coin,
                                       GetCustomNetworksCallback callback) {
  if (coin != mojom::CoinType::ETH) {
    NOTREACHED(); // crashing the app
    std::move(callback).Run({});
    return;
  }
```

## Actual result 
Crashing for SOL

## Expected result
Should not crash (and it doesn't if I comment the NOTREACHED)

cc: @supermassive

**Comment by supermassive** [comment]
We had custom network support only for ETH and NOTREACHED guard explicitly states that for SOL api clients should not call GetCustomNetworks as they would get 'incorrect' outcome.
Are we adding custom neither network for SOL now? Could you please link the issue here then?

**Comment by darkdh** [comment]
There is no custom network need for Solana
