### ISSUE TITLE
Chromium icon is displayed in search suggestions

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#24247]
## Description 

Chromium icon is displayed in search suggestions
## Steps to Reproduce

Case 1:
   1. Open 1.41/1.42/1.43
   2. Enter a string `hello` in address bar
   3. Hello search result page is displayed
   4. Bookmark the result page
   5. Open a new tab and enter a string `hello` suggested result has the chromium icon
   
Case 2:
  1. Import bookmarks from other browser
  2. Search a string `test`
  3. Suggested result has the chromium icon
  

## Actual result:

![image](https://user-images.githubusercontent.com/38657976/180774190-daa20dfc-9aa3-4cd6-9a8d-d5071b35b843.png)
![image (1)](https://user-images.githubusercontent.com/38657976/180774271-695f971b-6096-4b42-85dd-93096bbbe9de.png)

## Expected result:
Chromium icon should not be displayed in search suggestions

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.43.43 Chromium: 104.0.5112.57 (Official Build) nightly (64-bit)
-- | --
Revision | 212fd173a0da1e0a024f328295bb56a2529190bb-refs/branch-heads/5112@{#1042}
OS | Windows 10 Version 21H2 (Build 19044.1826)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @mkarolin @rebron

**Comment by LaurenWags** [comment]
Reproduced on macOS 

```
Brave | 1.42.74 Chromium: 103.0.5060.134 (Official Build) beta (x86_64)
-- | --
Revision | 8ec6fce403b3feb0869b0732eda8bd95011d333c-refs/branch-heads/5060@{#1262}
OS | macOS Version 12.5 (Build 21G72)
```

<img width="254" alt="Screen Shot 2022-07-25 at 8 13 25 AM" src="https://user-images.githubusercontent.com/28145373/180775204-9c59e495-5cb8-47b4-83aa-e2f5f95185dc.png">

**Comment by rebron** [comment]
cc: @simonhong When you get a chance, can you take a look.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.44.70 Chromium: 105.0.5195.68 (Official Build) beta (64-bit)
-- | --
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | Windows 11 Version 21H2 (Build 22000.856)
```
Verified using original STR https://github.com/brave/brave-browser/issues/24247#issue-1316745380

Case 1:

1. installed 1.44.70
2. launched Brave
3. entered string `hello` in address bar
4. hello search result page is displayed
5. bookmarked the result page
6. opened a new tab and entered string `hello` 

###Confirmed  a bookmark icon displayed in the omnibox autocomplete entry

step 3|step 4-5
----|----
<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/187801750-297ff588-e764-42b4-b84e-a22a94d9133d.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/187802178-f3488848-edbb-411c-9ae6-3c45b30eb3c0.png">

###Case 2: 

1. imported bookmarks from MS edge browser
2. searched  with a string 'news` 

###Confirmed no Chromium icons displayed in the omnibox autocomplete entry

   
![image](https://user-images.githubusercontent.com/98358127/187806737-55844169-0080-45d1-8fb2-c02c8d00bf12.png)
