### ISSUE TITLE
gclient sync failure because of duplicate deps

### ISSUE THREAD

**Issue by timschumi** [brave/brave-browser#2424]
## Description 
When following the build instructions, `npm run init` will fail with the following error message (after downloading the largest part of the Chromium source finished):
`The same name "src/third_party/android_sdk/public" appears multiple times in the deps section`

## Steps to Reproduce
   1. `git clone https://github.com/brave/brave-browser`
   1b. (Apply patches, see bottom of issue report)
   2. `cd brave-browser`
   3. `npm run init`

## Actual result:
Fails with the following error message:
`The same name "src/third_party/android_sdk/public" appears multiple times in the deps section`

## Expected result:
The sync should finish (afaik) without errors.

## Reproduces how often: 
Every time

## Brave version (brave://version info)
(Doesn't apply, building issue. The cloned brave-browser repository is at commit e1e3dc0)

### Reproducible on current release:
See above

### Additional Information
My host OS is Arch Linux, so python3 is the default. Therefore, I wrote two different patches to make the build system use python2. The issue exists with both of those patches, unfortunately I don't have a OS nearby that uses python2 by default and bash aliases don't work because of subshells. However, I doubt that there is any difference between using those patches and running it on a python2-default OS.

[depot-tools-python2_v1.diff.txt](https://github.com/brave/brave-browser/files/2660938/depot-tools-python2_v1.diff.txt)
[depot-tools-python2_v2.diff.txt](https://github.com/brave/brave-browser/files/2660939/depot-tools-python2_v2.diff.txt)

**Comment by fmarier** [comment]
Are you running `npm run init` as **root** by any chance?

I ran into that problem while trying to checkout brave-browser in an Ubuntu 14.04 LXC container as `root`. Switching to the `ubuntu` user (a non-root user) solved my problem.

**Comment by timschumi** [comment]
No, I don't run `npm run init` as root. This issue both happens in a makepkg context (which is never running as root due to security reasons) and my default user.

If anyone is using Arch Linux or an Arch-based system, the following makepkg configuration should replicate this issue every time: https://github.com/timschumi/aur-packages/tree/brave-git-next-gen
As far as I can tell, the steps in the PKGBUILD should exactly follow the build instructions written here: https://github.com/brave/brave-browser/wiki

**Comment by timschumi** [comment]
Definitely stale by now. and either already fixed or wasn't ever a widespread issue.
