### ISSUE TITLE
Browser crashes when clicking on Wikipedia link on DuckDuckGo smart-suggestion box

### ISSUE THREAD

**Issue by huylv** [brave/brave-browser#24245]
## Description 

Clicking on the Wikipedia link on the smart-suggestion box on the right side crashes the browser.

## Steps to Reproduce

   1. Go to https://duckduckgo.com/?q=Rishi+Sunak&t=braveed&ia=web
   2. Click on the link to Wikipedia on the right-side box
<img width="1275" alt="Screenshot 2022-07-25 at 12 40 56" src="https://user-images.githubusercontent.com/2832672/180758932-e7528cce-a472-4f5d-bd38-a8613dd5600f.png">

## Actual result:

Browser crashes

## Expected result:
Get redirected to Wikipedia page

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

1.41.99 Chromium: 103.0.5060.134 (Official Build) (x86_64) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
@huylv Can you update to 1.41.100? Can go to brave://settings/help and check for updates. We fixed an issue that addressed the crash issue you're seeing.

**Comment by huylv** [comment]
@rebron It no longer crashes on 1.41.100. Thank you.
