### ISSUE TITLE
Pin to taskbar from first run dialog

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#24241]
This is subtask of https://github.com/brave/brave-browser/issues/24054

## Description 

Pin Brave to task bar when user sets Brave as a default browser from first run dialog

## Steps to Reproduce

  1. Launch with clean profile
  2. Agree to set as a default browser
  3. Check brave is also pinned to taskbar

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
Brave | 1.44.9 Chromium: 104.0.5112.69 (Official Build) nightly (64-bit)
-- | --
Revision | 7ce2902023c722af8564068e6b26e934b83fd774-refs/branch-heads/5112@{#1213}
OS | Windows 11 Version 21H2 (Build 22000.795)

Verified using STR from https://github.com/brave/brave-browser/issues/24241#issue-1316251741

#### Confirmed Brave is pinned to taskbar

Ex1|Ex 2
---|---
<image width="800" alt="image" src="https://user-images.githubusercontent.com/98358127/181862048-30c79fc7-cbaa-459c-ba4f-a10bfba2a150.png">|<image width="800" alt="image" src="https://user-images.githubusercontent.com/98358127/181862055-492af73c-7584-4577-8459-5b5a54c7f9a6.png">

**Comment by simonhong** [comment]
Set `QA/No` as this feature will be disabled via https://github.com/brave/brave-browser/issues/24870
Instead, we can verify this when https://github.com/brave/brave-browser/issues/24054 is closed.
