### ISSUE TITLE
`WalletStatus` cleanup

### ISSUE THREAD

**Issue by szilardszaloki** [brave/brave-browser#24251]
Currently we have 6 wallet states:
- `NOT_CONNECTED`
- `CONNECTED`
- `VERIFIED`
- `DISCONNECTED_NOT_VERIFIED`
- `DISCONNECTED_VERIFIED`
- `PENDING`

Our Uphold integration uses only a subset of the above (`NOT_CONNECTED`, `VERIFIED`, `DISCONNECTED_VERIFIED`, `PENDING`), which is explicitly checked in code.

Although not explicitly checked, but that's also true for bitFlyer and Gemini, as they only use `NOT_CONNECTED`, `VERIFIED`, and `DISCONNECTED_VERIFIED` (they do expect their wallets to be in `CONNECTED`, `DISCONNECTED_NOT_VERIFIED`, and `PENDING`, but they never actually set their wallets to any of these states).

The idea would be to reduce the possible wallet states to these 3:
- `NOT_CONNECTED`
- `CONNECTED` (formerly `VERIFIED`)
- `LOGGED_OUT` (formerly `DISCONNECTED_VERIFIED`)

This requires the removal of the `PENDING` state from our Uphold integration and state migrations for all custodians.

cc: @Miyayes @brave/rewards-client

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.47.125 Chromium: 108.0.5359.99 (Official Build) beta (x86_64)
-- | --
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | macOS Version 12.6.1 (Build 21G217)
```

Verified test plan from https://github.com/brave/brave-core/pull/15722#issue-1430205229.

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Vivo X70 Pro version 12` running `Bravemonoarmx64.apk_1.47.45`
