### ISSUE TITLE
Importing from Chromium browsers will import (and enable) disabled extensions

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#24250]
## Description 
Importing extensions from Chromium browsers will import and enable disabled extensions

## Steps to Reproduce

   1. Have an install of Chrome, Chromium, Microsoft Edge, etc
   2. Install an extension from [Chrome Web Store](https://chrome.google.com/webstore/category/extensions?hl=en-US)
   3. Visit chrome://extensions and disable that extension
   4. Close the browser
   5. Open Brave (new profile)
   6. Import from the browser you used in Step 1

## Actual result:
The disabled extension will be imported and enabled

## Expected result:
The disabled extension should NOT be imported

## Reproduces how often: 
100%

**Comment by kjozwiak** [comment]
The above requires `1.43.71` for higher for `1.43.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `Passed` using
```
Brave | 1.43.73 Chromium: 104.0.5112.81 (Official Build) beta (64-bit)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | Windows 11 Version 21H2 (Build 22000.856)
```

Verified STR from https://github.com/brave/brave-browser/issues/24250#issue-1317104395

1. installed Chrome
2. install `LassPass:Free Password Manager` extension from [Chrome Web Store](https://chrome.google.com/webstore/category/extensions?hl=en-US)
3.visit `chrome://extensions` and disable that extension
4. close chrome browser
5. install 1.43.73
6. launch Brave
7. click on `Import bookmarks now...` in the bookmarks bar

Confirmed  `Extensions` option is not available if it's disabled in `Import bookmarks and settings` modal

Step 2|Step 3|Step6
-----|-----|-----
<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/185448107-8cb7eca4-8ca6-41ea-aa92-8514d9197e1f.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/185448153-88de7c17-c4d0-4a54-9015-ca40514c8f8a.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/185448692-eef5361e-ec18-402b-a7b9-50170d684d41.png">
