### ISSUE TITLE
Incorrect option selection for shields fingerprinting

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#24258]
## Description 
Shields fingerprinting option doesn't show the correct selected option.  

## Steps to reproduce 

   1. Open any website
   2. Open brave shields panel
   3. Go to fingerprinting option
   4. select `Allow all fingerprinting` option 
   5. close the panel by pressing `Done`
   6. Open fingerprinting option again
   7. select `Fingerprinting blocked(standard)` option
   8. close the panel by pressing `Done`
   9. Open fingerprinting option again
   10. observe the selected option 

## Actual result 
Even after selecting `Fingerprinting blocked(standard)`, on next shields open, it shows `Fingerprinting blocked (strict, may break sites)` option

## Expected result
should show the correct selected option for fingerprinting

## Issue reproduces how often 
Easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? yes
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on  `vivo x70 Pro version 12` running Bravemonoarm64.apk_1.45.106`
- Verified the STR from the description and ensured selcted `fingerprinting` option is shown when shield is opened and closed
