### ISSUE TITLE
Simulation support for Solana transactions

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#24269]
### Background

Since Solana programs have complete control over the user lamports, we've seen a huge rise in rugpulls by smart contracts draining user's funds. To prevent this, Phantom, Solflare, etc., have added support for simulations and show a state diff if the transaction were to be submitted.

Simulations are native to Solana, so adding support for it doesn't require any sort of third-party integration.

![image](https://user-images.githubusercontent.com/3684187/181024270-b58b86e8-b4d9-424e-8e91-8d3b60b4f3a2.png)

|RPC| https://docs.solana.com/developing/clients/jsonrpc-api#simulatetransaction|
-|-

### Security

Some researchers have found ways for Solana programs to detect if it's being run under simulation, and can trick users into approving the transaction by doing some false state updates, hence a social engineering attack. Phantom and Solflare address this by mentioning that the balance changes are "estimated" (see screenshot). Could be addressed in a separated issue.

**Full report w/ suggested remediation:** https://opcodes.fr/en/publications/2022-01/detecting-transaction-simulation

**Comment by Xavier59** [comment]
Solana recently merged a remediation for this so that the simulation cannot be tricked the way described in the article anymore :
https://github.com/solana-labs/solana/pull/24543

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.70.107 Chromium: 128.0.6613.120 (Official Build) beta (64-bit)
-- | --
Revision | ab3f504ca4a15c330f60a93d5e3773d780498980
OS | Windows 11 Version 23H2 (Build 22631.4112)

- Verified steps from [brave/brave-core#21796](https://github.com/brave/brave-core/pull/21796)
- Verified `brave://flags/#brave-wallet-enable-transaction-simulations` is set to disabled by default
- Verified enabling the flag enables the `See the results of transactions before you sign.` setting and sets to `Ask` as default
- Verified when submitting a native ETH transaction safe sign is shown and no simulation is shown
- Verified when submitting an ERC20 send simulation transaction optin message is shown when set to `Ask`
- Verified selecting `Enable` sets the setting to `Yes`
- Verified selecting `No thanks` sets the setting to `No`
- Verified when there are multiple transaction in queue, cycle through the transactions loads the correct simulation

Scenario 1 (Enable) | Secanrio 1 (Disable) | Scenario 2
-- | -- | --
<video src=https://github.com/user-attachments/assets/6dfd3fb0-f06b-4504-ab59-8e66d896fb8d> | <video src=https://github.com/user-attachments/assets/b867bb76-83d9-456a-bafd-d0383345f0f4> | <video src=https://github.com/user-attachments/assets/c579b912-a61e-44d4-94f9-d41d3f125e86>
