### ISSUE TITLE
`Search the web privately` is not translated on NTP Private Window/Tor

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#24267]
Follow up to https://github.com/brave/brave-browser/issues/23732

## Steps to Reproduce

1. launch Brave in PL (Polish) locale
1. click hamburger menu
1. opened a new `Private Window with Tor`
OR opened a new `Private Window`
OR opened a new `Guest Window`

## Actual result:

`Search with web privately` is not translated

![image](https://user-images.githubusercontent.com/34715963/180988497-ec4cdc7a-dd89-4bd3-864d-0ad091dcddb3.png)|![image](https://user-images.githubusercontent.com/34715963/180988606-04c96304-41d7-494f-86a1-2dc1a4c9bcf6.png)|![image](https://user-images.githubusercontent.com/34715963/180988673-5ad02321-cfc2-44f1-861b-991a8385d9a9.png)
--|--|--

## Expected result:
`Search the web privately` is translated

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.42.74 Chromium: 103.0.5060.134 (Official Build) beta (64-bit)
-- | --
Revision | a1c2360c5b02a6d4d6ab33796ad8a268a6128226-refs/branch-heads/5060@{#1124}
OS | Ubuntu 18.04 LTS

cc @rebron @mkarolin @brave/qa-team @nullhook

**Comment by mkarolin** [comment]
I don't see this string in any of the GRD(P) files. It seems to be hardcoded at the moment in components/brave_private_new_tab_ui/resources/page/components/search-box/index.tsx:166 (maybe?) cc: @nullhook

**Comment by simonhong** [comment]
@nullhook Please handling here(https://github.com/brave/brave-core/blob/master/components/brave_new_tab_ui/components/default/searchPromotion/searchBox.tsx#L130) together.
I referenced your search box for ntp promotion.

**Comment by kjozwiak** [comment]
We'll need translations to be able to verify the above. Once we get the translations uplifted into `1.43.x`, the above can be checked. I did run through a quick sanity check and made sure string is still being displayed and nothing obvious regressed as per https://github.com/brave/brave-core/pull/14463#issuecomment-1219959950.

**Comment by LaurenWags** [comment]
Testing can be completed with 1.43.84 and above as translations have been included in that version.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.43.84 Chromium: 105.0.5195.68 (Oficjalna wersja) (x86_64)
-- | --
Wersja | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
System operacyjny | macOS Wersja 11.6.8 (kompilacja 20G730)

### Followed original steps to reproduce; confirmed the `Search the web privately` string has been translated.

`Polish`

Private window | Private window w/Tor | Guest window
----------------|----------------------|---------------
<img width="1312" alt="Zrzut ekranu 2022-08-30 o 08 47 26" src="https://user-images.githubusercontent.com/387249/187482775-5378364d-544f-4b5b-87b8-726d71db0379.png"> | <img width="1312" alt="Zrzut ekranu 2022-08-30 o 08 47 36" src="https://user-images.githubusercontent.com/387249/187482781-417e3ab7-64c8-4fb1-a508-5d88a910b8e1.png"> | <img width="1312" alt="Zrzut ekranu 2022-08-30 o 08 47 45" src="https://user-images.githubusercontent.com/387249/187482783-22ec1534-1ac5-4146-adc5-fd711245aff4.png">
