### ISSUE TITLE
Brave Rewards Creators | Wallet connection issues!

### ISSUE THREAD

**Issue by betheodo** [brave/brave-browser#24277]
I’m trying to connect my “creator wallet” to uphold, and despite receiving an email from Uphold that it was connected, I’m receiving information that “Could not configure BAT deposits for Uphold”.
This has been going on for almost two months.

![Screenshot_15](https://user-images.githubusercontent.com/105853904/181062007-9e381792-cf1e-407f-a062-5e6c823a19c8.png)

**Comment by Miyayes** [comment]
This is the repo for creators: https://github.com/brave-intl/publishers/issues
