### ISSUE TITLE
Move Ethereum Ledger Integration to untrusted iframe

### ISSUE THREAD

**Issue by nvonpentz** [brave/brave-browser#24275]
We need to isolate the Ethereum Ledger JS libraries similar to how we did for [Solana](https://github.com/brave/brave-core/pull/14096).

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.44.99 Chromium: 106.0.5249.55 (Official Build) (64-bit) 
-- | --
Revision | `4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}`
OS | Linux

- Verified steps from [brave/brave-core#14373](https://github.com/brave/brave-core/pull/14373)
- Verified `Authoize` message is shown when Ledger is connected for the first time to import wallet
- Verified authorizing Ledger allows to connect Ledger and import wallet
- Verified once authorized doesn't ask again when connected
- Verified able to load more accounts on the import account screen
- Verified able to select multiple accounts to be imported at once
- Verified `Authorize` transaction is shown for the first transaction done via Ledger wallet
- Verified able to sign transactions via Ledger wallet
- Verified able to ETH Sign transactions via Ledger wallet
- Verified able to sign + verify Sign Type Data V3 & Sign Type Data V4 transactions
- Encountered [#25616](https://github.com/brave/brave-browser/issues/25616), [#25617](https://github.com/brave/brave-browser/issues/25617), [#25619](https://github.com/brave/brave-browser/issues/25619) & [#25623](https://github.com/brave/brave-browser/issues/25623)

------------------------
Verification passed on

Brave | 1.44.99 Chromium: 106.0.5249.55 (Official Build) (64-bit) 
-- | --
Revision | `4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}`
OS | Windows 11 Version 21H2 (Build 22000.978)

- Verified steps from [brave/brave-core#14373](https://github.com/brave/brave-core/pull/14373)
- Verified `Authoize` message is shown when Ledger is connected for the first time to import wallet
- Verified authorizing Ledger allows to connect Ledger and import wallet
- Verified once authorized doesn't ask again when connected
- Verified able to load more accounts on the import account screen
- Verified able to select multiple accounts to be imported at once
- Verified `Authorize` transaction is shown for the first transaction done via Ledger wallet
- Verified able to sign transactions via Ledger wallet
- Verified able to ETH Sign transactions via Ledger wallet
- Verified able to sign + verify Sign Type Data V3 & Sign Type Data V4 transactions
- Encountered [#25616](https://github.com/brave/brave-browser/issues/25616), [#25617](https://github.com/brave/brave-browser/issues/25617), [#25619](https://github.com/brave/brave-browser/issues/25619) & [#25623](https://github.com/brave/brave-browser/issues/25623)

------------------------
Verification passed on

Brave | 1.44.99 Chromium: 106.0.5249.55 (Official Build) (arm64)
-- | --
Revision | `4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [brave/brave-core#14373](https://github.com/brave/brave-core/pull/14373)
- Verified `Authoize` message is shown when Ledger is connected for the first time to import wallet
- Verified authorizing Ledger allows to connect Ledger and import wallet
- Verified once authorized doesn't ask again when connected
- Verified able to load more accounts on the import account screen
- Verified able to select multiple accounts to be imported at once
- Verified `Authorize` transaction is shown for the first transaction done via Ledger wallet
- Verified able to sign transactions via Ledger wallet
- Verified able to ETH Sign transactions via Ledger wallet
- Verified able to sign + verify Sign Type Data V3 & Sign Type Data V4 transactions
- Encountered [#25616](https://github.com/brave/brave-browser/issues/25616), [#25617](https://github.com/brave/brave-browser/issues/25617), [#25619](https://github.com/brave/brave-browser/issues/25619) & [#25623](https://github.com/brave/brave-browser/issues/25623)
