### ISSUE TITLE
Balance is not being updated for the corresponding network

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#24272]
## Description 
Balance is not being updated for the corresponding network when changed

## Steps to reproduce 

   1.  Login, go to buy-send-swap
   2.  change networks and observe the balance is not updated

## Actual result 
Show balance of previously selected network 

https://user-images.githubusercontent.com/11755381/181030601-a01f8488-e02e-478e-ae14-f9645e2bcf17.mp4

## Issue reproduces how often 
easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version?  Yes
- Can you reproduce this issue with the current Play Store Beta version? didn't test
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Expected result
Balance should be updated as per network

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5(Android 12.1) & Samsung Tab A (Android 10) running 1.42.96 x64 build
- Verified balance is automatically updated once the transaction is confirmed
