### ISSUE TITLE
`window.phantom` being defined breaks several websites

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#24289]
## Description 
Trying to login with valid (or invalid) credentials triggers a fatal error on some websites, preventing login.

Works fine in Brave version `1.42` (before 1.42.81), `1.41` and in Chrome. Also works fine in a private window

## Steps to Reproduce

   1. Visit https://accountaccess.edwardjones.com/ca-logon/logon.action
   2. Put in username `braveuser`
   3. Put in password `AbbbAAbbcdD11`
   4. Click Log In button

## Actual result:
Error is shown `Due to a system problem, we are unable to log you in at this time. Please try again later. If the problem continues, contact Online Client Support at 800-441-5203.`

## Expected result:
Should show an error `The system did not recognize the user ID and password you entered.`

## Reproduces how often: 
100%

## Brave version (brave://version info)
1.43.42 or newer (Nightly)
1.42.81 or newer (Beta)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no 
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? no

## Miscellaneous Information:
Problem did not exist in `1.43.41`. Problem started occurring with `1.43.42`.
https://github.com/brave/brave-core/commits/19d8fe92f1887055072d62f1e7e6546053964515

I was able to reproduce from source code (`git checkout -b bsc-troubleshooting v1.43.42`) and commenting out this line fixed the issue for me (I don't know why):
https://github.com/brave/brave-core/blob/f54f6be60d18d8e9496c72c3a3afc974cbc784d4/components/brave_wallet/renderer/js_solana_provider.cc#L159-L161

**Comment by darkdh** [comment]
This can also happen if you install and setup Phantom extension using Chrome. The website will give the exactly same error because it sees `window.phantom` disregarding who inserted it.

**Comment by snowbound** [comment]
Just posted that this wallet issue fixed the bank website issue. I am wondering how many other Brave Beta users are having this problem. Thanks @bsclifton for the heads up

**Comment by bsclifton** [comment]
`window.phantom` introduced in https://github.com/brave/brave-core/pull/14282 for 1.43 and uplifted to 1.42 with https://github.com/brave/brave-core/pull/14295

Thanks @snowbound for reporting https://online.acu.ca/ breakage; there are likely others having the same problem

If I had to guess, I think that some websites are having a special code path for automated tests (ex: using Selenium). If `window.phantom` is set, the developers may be assuming the site is running under phantomjs. They likely have a workaround for faking or skipping login for the purpose of the automated test. Here's an example of someone recommending that strategy on stackoverflow.com:
https://stackoverflow.com/questions/26186101/how-to-skip-the-code-execution-from-phantomjs-or-grover

**Comment by MadhaviSeelam** [comment]
Brave | 1.42.86 Chromium: 104.0.5112.81 (Official Build) (64-bit)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | Windows 11 Version 21H2 (Build 22000.795)

Verified using STR  https://github.com/brave/brave-browser/issues/24289#issue-1319105735

###Confirmed correct error message displayed `The system did not recognize the user ID and password you entered.`

before fix in 1.42.85|fix verified 1.42.86
------|-----
<image width ="850" alt="before" src="https://user-images.githubusercontent.com/98358127/182496863-72500563-aee6-440b-ae0e-3f9ac10ef860.png">|<image width ="850" alt="before" src="https://user-images.githubusercontent.com/98358127/182496719-4e5a65bf-6d2f-4bb9-9230-7eb0017d9c84.png">

Verified this site as well as per  https://github.com/brave/brave-browser/issues/24347
### Confirmed `Enter your password` displayed
<image width ="850" alt="before" src="https://user-images.githubusercontent.com/98358127/182497302-c0e3d0ec-6d5c-4cb5-9e55-c2680c9b6868.png">

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.42.86 Chromium: 104.0.5112.81 (Official Build) (x86_64)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | macOS Version 11.6.8 (Build 20G730)

Edward Jones, before | Edward Jones, fixed
----------------------|---------------------
. | <img width="1672" alt="Screen Shot 2022-08-02 at 5 41 31 PM" src="https://user-images.githubusercontent.com/387249/182500598-8f421890-057e-4924-8c0e-f91dc9be3f40.png">


https://online.acu.ca/, before | https://online.acu.ca/, fixed
-----------------------------|----------------------------
. | <img width="1672" alt="Screen Shot 2022-08-02 at 5 27 51 PM" src="https://user-images.githubusercontent.com/387249/182499024-f3882c24-78e3-40cc-858d-ea9269409bea.png">
