### ISSUE TITLE
Default search provider should be Brave in Private Window after upgrade if DuckDuckGo was not selected in previous versions

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#24284]
## Steps to Reproduce

1. Install `1.30.89`
2. launch Brave
3. open a `New Private Window`
4. Leave toggle `Search with DuckDuckGo` to `OFF`
5. shut down Brave
6. install/upgrade to `1.32.103`
7. launch Brave
8. DDG toggle was not available in the `Private window`
9. Rename `Brave-Browser` to `Brave-Browser-Beta`
10. install/upgrade to `1.42.73`
11. launch Brave
12. open `brave://settings/search`

## Actual result:

 Normal Window and Private Window both show Google as a default selection

![image (7)](https://user-images.githubusercontent.com/98358127/181129699-edf7f858-47a9-4a1e-b658-46a590f362f5.png)

## Expected result:
Since the toggle for `Search with DuckDuckGo` is `OFF` before upgrade, Brave should be a default provider for Private Window after upgrade.

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Brave | 1.42.73 Chromium: 103.0.5060.134 (Official Build) beta (64-bit)
-- | --
Revision | 8ec6fce403b3feb0869b0732eda8bd95011d333c-refs/branch-heads/5060@{#1262}
OS | Windows 11 Version 21H2 (Build 22000.795)

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@simonhong @rebron

**Comment by kjozwiak** [comment]
The above requires `1.42.82` or higher for `1.42.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```

Brave | 1.42.82 Chromium: 104.0.5112.69 (Official Build) (64-bit)
-- | --
Revision | 7ce2902023c722af8564068e6b26e934b83fd774-refs/branch-heads/5112@{#1213}
OS | Windows 10 Version 21H2 (Build 19044.1826)

```
- Encured that `brave` default SE in Private window when DDG SE is toggled OFF in `1.32.103`

**`1.30.89`** | **`1.32.103`** | **`1.42.82`**
--------------|----------------|--------------
![image](https://user-images.githubusercontent.com/38657976/181735079-5f7d7082-80bb-414e-bbca-e1ef7e52fd09.png) | ![image (1)](https://user-images.githubusercontent.com/38657976/181735101-c0a2910a-04ac-49ae-aea2-a8a8edc1a8de.png) | ![image](https://user-images.githubusercontent.com/38657976/181734951-fea1be32-b8c5-4095-969a-2f54a4b9dd01.png)
