### ISSUE TITLE
Reduce Language not farbling HTTP headers of subresources

### ISSUE THREAD

**Issue by pilgrim-brave** [brave/brave-browser#24282]
Easily reproducible on the QA page, open devtools and network tab and refresh the page. The primary resource's Accept-Language request header is farbled, but subresources like `site.css` are not.

<img width="473" alt="Screen Shot 2022-07-26 at 4 42 12 PM" src="https://user-images.githubusercontent.com/43750833/181108244-58562485-0989-4384-9337-ba2cd8c15829.png">

<img width="514" alt="Screen Shot 2022-07-26 at 4 42 26 PM" src="https://user-images.githubusercontent.com/43750833/181108251-fe143da9-4a49-439a-a70b-f9c203fcc56a.png">

**Comment by kjozwiak** [comment]
@brave/qa-team STR/Cases can be found via https://github.com/brave/brave-core/pull/14338#issuecomment-1216142387. Used the screenshot example that @pilgrim-brave provided via https://github.com/brave/brave-browser/issues/24282#issue-1318732527 as guidance and received confirmation that the pass looks good 👍 

@pilgrim-brave also recommended running through https://dev-pages.brave.software/fingerprinting/headers.html as well.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.42.97 Chromium: 104.0.5112.102 (Official Build) (x86_64)
-- | --
Revision | 8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}
OS | macOS Version 12.5 (Build 21G72)
```

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```
```

Reproduced the original issue mentioned via https://github.com/brave/brave-browser/issues/24282#issue-1318732527 using the following STR/Cases:

* installed `1.42.95 Chromium: 104.0.5112.81`
* restarted the browser and ensured that `DisableReduceLanguage:Enabled`
* double checked and ensured that `Prevent sites from fingerprinting me based on my language preferences` was enabled via `brave://settings/shields`
* added several languages via `brave://settings/languages`
* visited `https://dev-pages.brave.software/index.html` and opened the DevTools
* under the `Network` tab, clicked on `Disable cache`
* refreshed `https://dev-pages.brave.software/index.html` once again

**`Farbled`** | **`Not farbled`** | **`Not farbled`**
----------------|----------------|----------------
![image](https://user-images.githubusercontent.com/38657976/185160110-a8a990e6-8445-46ae-b2a4-971a9bb2f7f3.png) | ![image](https://user-images.githubusercontent.com/38657976/185160197-3f91115a-b63a-4510-8ac5-8f102a00f74d.png) | ![image](https://user-images.githubusercontent.com/38657976/185160583-ac9f67c9-a9e3-4e66-a7ad-01eb6985b58c.png)

Verified steps above using `1.42.97 Chromium: 104.0.5112.102`:

**`Languages selected`** | **`Farbled`** | **`Farbled`** | **`Farbled`**
----------------|----------------|----------------|----------------

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung Tablet S8 Ultra` running `Android 12` using the following build(s):

```
Brave | 1.42.97 Chromium: 104.0.5112.102 (Official Build) (64-bit)
-- | --
Revision | 8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}
OS | Android 12; Build/SP1A.210812.016
```

**`Languages`** | **`Block Fingerprinting (Default)`** | **`Aggressively Block Fingerprinting`** | **`Allow Fingerprinting`**
-- | -- | -- | --
![Screenshot_20220817-124749_Settings](https://user-images.githubusercontent.com/2602313/185197633-3b918424-e8f3-4775-89a1-c9717f6873a6.jpg) | ![Screenshot_20220817-124808_Brave](https://user-images.githubusercontent.com/2602313/185197701-2d9bee06-95f5-4a08-a04c-af3b330fc306.jpg) | ![Screenshot_20220817-124837_Brave](https://user-images.githubusercontent.com/2602313/185197759-42bea807-206f-423a-ab1f-2b5ae8267c2b.jpg) | ![Screenshot_20220817-124824_Brave](https://user-images.githubusercontent.com/2602313/185197795-0b4dc25c-7b01-43ea-823e-e642c113f04c.jpg)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+` running `Android 12` using the following build(s):

```
Brave | 1.42.97 Chromium: 104.0.5112.102 (Official Build) (64-bit)
-- | --
Revision | 8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}
OS | Android 12; Build/SP1A.210812.016
```

**`Languages`** | **`Block Fingerprinting (Default)`** | **`Aggressively Block Fingerprinting`** | **`Allow Fingerprinting`**
-- | -- | -- | --
![Screenshot_20220817-130446_Settings](https://user-images.githubusercontent.com/2602313/185200411-ad731e08-2721-4eb1-98ba-2476acd88092.jpg) | ![Screenshot_20220817-130511_Brave](https://user-images.githubusercontent.com/2602313/185200452-9fec7e1a-23c1-4b14-a3c9-f73daabf32ee.jpg) | ![Screenshot_20220817-130534_Brave](https://user-images.githubusercontent.com/2602313/185200472-d89a3edd-5456-4651-8726-a704d98c53cf.jpg) | ![Screenshot_20220817-130522_Brave](https://user-images.githubusercontent.com/2602313/185200502-6c38f25d-65fc-449e-a42e-66ccb8fd10ab.jpg)
