### ISSUE TITLE
handle error code http 409 conflict on grant claim

### ISSUE THREAD

**Issue by evq** [brave/brave-browser#2428]
For cases where a grant for this promotion has already been claimed we will now return HTTP 409 from the server, see - https://github.com/brave-intl/bat-ledger/pull/463

**Comment by NejcZdovc** [comment]
we need to add it here https://github.com/brave-intl/bat-native-ledger/blob/7bd43e1b5e3d16f7a0374796110d42783a7ef7bd/src/bat_client.cc#L485
