### ISSUE TITLE
NTP Backgrounds Same Strange Images

### ISSUE THREAD

**Issue by reb0und** [brave/brave-browser#24288]
## Description 
Brave keeps using the same image(s) for the NTP and they are becoming very strange, such as this one I have been seeing for the past few days. Especially this billing period background which is very annoying. 

## Steps to Reproduce

   1. Open New Tab or Window

## Actual result:
<img width="1139" alt="image" src="https://user-images.githubusercontent.com/67512765/181173370-eed80044-0478-48c8-8c1e-2c6a77f114ac.png">

## Expected result:
A normal background rotation not this. 

## Brave version (brave://version info)
[Version 1.41.100 Chromium: 103.0.5060.134 (Official Build) (arm64)](https://brave.com/latest/)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- > Yes
- Can you reproduce this issue with the beta channel? 
- > Have not tested
- Can you reproduce this issue with the nightly channel? 
- > Have not tested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- > No
- Does the issue resolve itself when disabling Brave Rewards? 
- > No
- Is the issue reproducible on the latest version of Chrome? 
- > No, as Chrome backgrounds are set by user. 

## Miscellaneous Information:
A theme/background customization feature similar to Chrome would be ideal for this situation.

**Comment by simonhong** [comment]
@reb0und Can you check which component is used for this background images?
You can load brave://components and find `NTP Sponsored Images (xx)`

**Comment by reb0und** [comment]
1.0.6

<img width="286" alt="image" src="https://user-images.githubusercontent.com/67512765/181183511-166ec109-0b1d-4516-a477-93f9d959399d.png">

**Comment by simonhong** [comment]
@reb0und Can you share NTP `Sponsored` Images comopnent info also?
and are you seeing above image from every NTP?

**Comment by reb0und** [comment]
I am seeing the above image on almost every if not every NTP. <img width="772" alt="image" src="https://user-images.githubusercontent.com/67512765/181185982-7e80328f-16cc-49a9-8cf5-b509dcbf91da.png">

**Comment by simonhong** [comment]
@reb0und Thanks for reply. clicking `Brave backgrounds` in the above dashboard doesn't make any difference?

**Comment by simonhong** [comment]
and it would be helpful if you can share below components version from brave://components.
<img width="311" alt="image" src="https://user-images.githubusercontent.com/6786187/181186829-a91411d0-1f36-4169-8302-12c9507556c6.png">

**Comment by reb0und** [comment]
> Reference in

https://github.com/brave/brave-browser/issues/24288#issuecomment-1196343891 1.0.6

**Comment by reb0und** [comment]
Okay, clicking Brave Backgrounds worked

**Comment by reb0und** [comment]
Thank you @simonhong

**Comment by simonhong** [comment]
> Thank you @simonhong

My pleasure :)
