### ISSUE TITLE
Solana transactions

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#24292]
Make sure we show present and past Solana transactions correct everywhere.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.42.96 x64 build
- Verified able to view transaction details in the transaction list for Solana Account
- Verified clicking on a confirmed transaction loads the correct block explorer
- Verified for both SOL and SPL tokens, correct block explorer is loaded 

Oppo Reno 5 (Android 12.1) | Samsung Tab A (Android 10)
-- | -- 
<video src=https://user-images.githubusercontent.com/17010094/184888448-c05fd77a-7ad2-4b4c-8608-3a268d0eebba.mp4> | <video src=https://user-images.githubusercontent.com/17010094/184888431-ede52cf7-adac-455a-80f8-e5614b225842.mp4>
