### ISSUE TITLE
Solana account name edit doesn't work

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#24299]
## Steps to reproduce 

   1. Open Accounts tab
   2. Click on Solana account
   3. Click rename and change name, hit update

## Actual result 
![Screenshot_20220727-140818_Brave - Debug](https://user-images.githubusercontent.com/12011303/181348096-a2652e7a-89ad-4e67-bbc1-02fe940ef148.jpg)

## Expected result
Rename works

## Issue reproduces how often 
Always

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Dupe of #24193

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on `Samsung Galaxy Tab A7 version 11` running `Bravemonoarm64.apk_1.42.89`

- Verified steps from issue description
- Verified able to update already created account name
- Verified able to change account name at the time of creation

----

Verification PASSED on `Samsung Galaxy A52s version 11` running `Bravemonoarm64.apk_1.42.89`

- Verified steps from issue description
- Verified able to update already created account name
- Verified able to change account name at the time of creation
