### ISSUE TITLE
Chromium 104 messed up macOS initial launch modal

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#24297]
## Description 

Initial launch modal on macOS is messed up with Chromium 104, the text goes out of view.

## Steps to Reproduce

   1. Clean install 1.41.100 (Chromium 103) or 1.42.78 (Chromium 103) --> initial launch modal looks fine
   2. Clean install 1.42.80 (Chromium 104) --> initial launch modal text is displayed incorrectly

## Actual result:

<img width="439" alt="1 42 80 C104" src="https://user-images.githubusercontent.com/28145373/181313615-297dfe78-8f83-419e-a05b-391244e01893.png">

## Expected result:

<img width="446" alt="1 42 78 C103" src="https://user-images.githubusercontent.com/28145373/181313646-f9a1bb6b-426b-4a86-bf69-442f796a924f.png">

## Reproduces how often: 

easily

## Version/Channel Information:

- Can you reproduce this issue with the current release? 1.41.x no, 1.42.x Chromium 104 versions yes
- Can you reproduce this issue with the beta channel? 1.43.x Chromium 104 versions yes
- Can you reproduce this issue with the nightly channel? 1.44.x Chromium 104 versions yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron @brave/qa-team @mkarolin

**Comment by kjozwiak** [comment]
The above requires `1.42.82` or higher for `1.42.x` verification 👍

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.42.82 Chromium: 104.0.5112.69 (Official Build) (x86_64)
-- | --
Revision | 7ce2902023c722af8564068e6b26e934b83fd774-refs/branch-heads/5112@{#1213}
OS | macOS Version 12.5 (Build 21G72)
```

Verified STR from description.

<img width="423" alt="1 42 82 Intel" src="https://user-images.githubusercontent.com/28145373/181741999-14bff45d-e0d8-40a8-aafc-c4216c358646.png">
