### ISSUE TITLE
Solana account doesn't show private key

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#24300]
## Steps to reproduce 

   1. Open Accounts tab
   2. Click on any Solana account
   3. Click Details and Private Key there

## Actual result 
Private key field is empty

## Expected result
Shouldn't be empty

## Issue reproduces how often 
Always

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on `Samsung Galaxy Tab A7 version 11` running `Bravemonoarm64.apk_1.42.89`

- Verified Private Key field is not empty for Solana Accounts
- Verified `Show private key` shows the accounts private key
- Verified Private Key field is not empty for Ethereum Accounts
- Verified `Show private key` shows the accounts private key
