### ISSUE TITLE
Add rotating hash to payload - followup to 23055

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#24304]
## Steps to Reproduce

   1. Launch browser
   2. Join rewards
   3. Navigate to brave://rewards-internals

## Actual result:

`Device Id: Unknown` is shown on Ad Diagnostics

## Expected result:
`Device Id: ...` should be shown on Ad Diagnostics, where ... is the device id (which never leaves the local machine)

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by kjozwiak** [comment]
The above requires `1.43.53` or higher for `1.43.x` verification 👍

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.43.63 Chromium: 104.0.5112.81 (Official Build) beta (64-bit)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | Ubuntu 18.04 LTS

Verified test plan from the description
Verified device id does not change between browser versions

![image](https://user-images.githubusercontent.com/34715963/183908241-154d9b3c-7492-4e4f-add0-bc96bf16fcd4.png)
DeviceID
```
910719246a9627bd084e9746711379856a23864aa8fa5b6f069ec99e1c251f11
```

![image](https://user-images.githubusercontent.com/34715963/183909147-cad665b1-dbfc-4560-9fa6-9ee21f4a007b.png)
DeviceID
```
910719246a9627bd084e9746711379856a23864aa8fa5b6f069ec99e1c251f11
```

#### --rewards=staging=true,debug=true
Device id not changed:
```
910719246a9627bd084e9746711379856a23864aa8fa5b6f069ec99e1c251f11
```

#### --rewards=staging=false,debug=true
Device id not changed:
```
910719246a9627bd084e9746711379856a23864aa8fa5b6f069ec99e1c251f11
```

#### --rewards=staging=true,debug=false
Device id not changed:
```
910719246a9627bd084e9746711379856a23864aa8fa5b6f069ec99e1c251f11
```

---------------------------------
Verification passed on

Brave | 1.43.63 Chromium: 104.0.5112.81 (Official Build) beta (64-bit)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | Windows 10 Version 21H2 (Build 19044.1826)

Verified test plan from the description
Verified device id does not change between browser versions

![image](https://user-images.githubusercontent.com/34715963/183908668-628019cb-0a38-4b01-a686-bf312b88b953.png)
Device id
```
c5a1e1bcf6b9b52ede9a5281de63a304b89154420b2b9b26620526019c3c277f
```

![image](https://user-images.githubusercontent.com/34715963/183909668-89e87fae-4c52-49cc-acd7-5e03b38a272b.png)
Device id
```
c5a1e1bcf6b9b52ede9a5281de63a304b89154420b2b9b26620526019c3c277f
```

---------------------

Verification passed on

Brave | 1.43.63 Chromium: 104.0.5112.81 (Official Build) beta (64-bit)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Device id
```
8450908ac7c99985b45bebf073a7e24c6f6baf3d24dcc2b18185ebb7ad903c64
```


---------------------

Verification passed on

Brave | 1.43.63 Chromium: 104.0.5112.81 (Official Build) beta (64-bit)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | Windows 8.1 (Build 9600)

Device id
```
ab55ff9b2c38ee10a601d7bddb449e7c8ce55a743578ead5cc84bb23b238dc25
```

Device id after restart:
```
ab55ff9b2c38ee10a601d7bddb449e7c8ce55a743578ead5cc84bb23b238dc25
```

----------------------

**Comment by LaurenWags** [comment]
@brave/qa-team please use these steps to verify on your machines/OSes: https://bravesoftware.slack.com/archives/GAA4017R7/p1660671903953109?thread_ts=1660148977.287319&cid=GAA4017R7

**Comment by stephendonner** [comment]
Verification `PASSED` using 

Brave | 1.43.73 Chromium: 104.0.5112.81 (Official Build) beta (x86_64)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | macOS Version 11.6.8 (Build 20G730)



Followed https://github.com/brave/brave-browser/issues/24304#issuecomment-1217052424.

### Steps:
1. new install
2. launch Brave
3. enabled Rewards (via `brave://rewards`)
4. opened `brave://rewards-internals`
5. noted the `Device Id ` (sic)
6. restarted my machine
7. relaunched Brave
8. noted the Device Id from `brave://rewards-internals`

### Confirmed they are identical.

Device ID: `b879e65e8169e0127f33810e45043c9e8de8e4b28e3fc0bedb3170aaa8caa224`

before | after machine restart
-------|----------------------
<img width="1312" alt="Screen Shot 2022-08-17 at 11 13 39 AM" src="https://user-images.githubusercontent.com/387249/185213316-a86ab4b1-f6f9-438d-a445-fdf88a36973f.png"> | <img width="1312" alt="Screen Shot 2022-08-17 at 11 16 09 AM" src="https://user-images.githubusercontent.com/387249/185213326-2f86c8aa-7a5a-496f-957b-4c2c4ddb72f3.png">

**Comment by MadhaviSeelam** [comment]
Verification `Passed` using
```
Brave | 1.43.73 Chromium: 104.0.5112.81 (Official Build) beta (64-bit)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | Windows 11 Version 21H2 (Build 22000.856)
```

Followed https://github.com/brave/brave-browser/issues/24304#issuecomment-1217052424.

### Steps:
1. new install
2. launch Brave
3. enabled Rewards (via `brave://rewards`)
4. opened `brave://rewards-internals`
5. noted the `Device Id ` (sic)
6. restarted my machine
7. relaunched Brave
8. noted the Device Id from `brave://rewards-internals`

### Confirmed they are identical.

Device Id: 93be11f96f3f5bbb2d5a4e1451abe492f77de78536f3f10b08d4ae35ae04d573

Before|After machine restart
----|----
<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/185213527-142a0c7d-4cd2-4ac1-8e31-b383fadf0ac8.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/185214485-6ebf97fe-b855-4e26-a4ff-9755e19b3830.png">

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```

Brave | 1.43.78 Chromium: 104.0.5112.102 (Official Build) beta (64-bit)
-- | --
Revision | 8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}
OS | Windows 10 Version 21H2 (Build 19044.1889)

```

**Comment by kjozwiak** [comment]
Went through the verification's using the following build(s):

```
Brave | 1.43.79 Chromium: 104.0.5112.102 (Official Build) beta (64-bit)
-- | --
Revision | 8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}
```

Verified steps from https://bravesoftware.slack.com/archives/GAA4017R7/p1660671903953109?thread_ts=1660148977.287319&cid=GAA4017R7.

<details>
<summary>Win 11 x64 (Physical machine) - PASSED</summary>

Before restart: `Device Id: 9babaa3c0d282cf5a6e3594c7065d27b682568e52e849602bcd76ee128a71c83`

After restart: `Device Id: 9babaa3c0d282cf5a6e3594c7065d27b682568e52e849602bcd76ee128a71c83`

</details>

<details>
<summary>Win 10 x64 VM (Hyper-V) - PASSED</summary>

Before restart: `Device Id: 0e611d0e210479ca9ae3812ed5df920fe62c6e3e611c96aec9fc9686da5a185a`

After restart: `Device Id: 0e611d0e210479ca9ae3812ed5df920fe62c6e3e611c96aec9fc9686da5a185a`

</details>

<details>
<summary>Win 10 x86 VM (Hyper-V) - FAILED</summary>

Before restart: `Device Id: Unknown`

After restart: `Device Id: Unknown`

**`Example`** | **`Example`**
----------------|----------------
![image](https://user-images.githubusercontent.com/2602313/186327763-d995e6be-52fb-46dc-bc77-a25a09004a70.png) | ![image](https://user-images.githubusercontent.com/2602313/186328040-d882e9a0-4e9a-42e6-a07e-33b6e2b5b5d1.png)

</details>

<details>
<summary>PopOS 22.04 x64 VM (VM Workstation Pro) - PASSED</summary>

Before restart: `Device Id: 733c959a43224e3ded00952caa391a71c9e31c5f70328a69c01ce3d4e7a5368e`

After restart: `Device Id: 733c959a43224e3ded00952caa391a71c9e31c5f70328a69c01ce3d4e7a5368e`

</details>

<details>
<summary>macOS x64 Monterey 12.5.1 (Physical machine) - PASSED</summary>

Before restart: `Device Id: 7d6152ede1e4ea03d82cbe33fd5687f9c60391dec83d9ba62df529b8041acd76`

After restart: `Device Id: 7d6152ede1e4ea03d82cbe33fd5687f9c60391dec83d9ba62df529b8041acd76`

</details>

<details>
<summary>macOS x64 10.13.6 High Sierra VM (Parallels Desktop 18) - PASSED</summary>

Before restart: `Device Id: 1304864c7cc3af5c5f78f52a4b21ce9e58b7475a1a29b99f59fad8ddbbbd6726`

After restart: `Device Id: 1304864c7cc3af5c5f78f52a4b21ce9e58b7475a1a29b99f59fad8ddbbbd6726`

</details>

<details>
<summary>Win 8.1 x64 VM (Parallels Desktop 18) - PASSED</summary>

Before restart: `Device Id: a58a537264e304f3d67658c20b7bb36d2d53b001896f70e217077ca896ebbbbb`

After restart: `Device Id: a58a537264e304f3d67658c20b7bb36d2d53b001896f70e217077ca896ebbbbb`

</details>

<details>
<summary>Win 8.1 x86 VM (Parallels Desktop 18) - PASSED</summary>

Before restart: `Device Id: 1aa883222a315585cc33325b56c5c7db808e44fa6550b369a4df13b8fd4e1b95`

After restart: `Device Id: 1aa883222a315585cc33325b56c5c7db808e44fa6550b369a4df13b8fd4e1b95`

</details>

<details>
<summary>Win 10 x64 VM (Parallels Desktop 18) - PASSED</summary>

Before restart: `Device Id: 1aa883222a315585cc33325b56c5c7db808e44fa6550b369a4df13b8fd4e1b95`

After restart: `Device Id: 1aa883222a315585cc33325b56c5c7db808e44fa6550b369a4df13b8fd4e1b95`

</details>
