### ISSUE TITLE
State-level ad targeting setting is not shown

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#24313]
Regression introduced in 1.42.x, probably due to https://github.com/brave/brave-browser/issues/21038

## Steps to Reproduce

1. On Windows: Set `Regional format` Windows setting to `English (United States)`
1. Use US connection (or use charles to override `https://geo.ads.brave.com/v1/getstate` with `{"country":"US","region":"CA"}`)
1. Run Brave with logging enabled
1. Enable rewards and ads
1. Make sure that response from `https://geo.ads.brave.com/v1/getstate` has proper country(US) and region
1. Open `Brave Private Ads settings` in `brave://rewards/`
1. Check if `Regional ad relevance` is shown

## Actual result:

`Regional ad relevance` is not shown
![image](https://user-images.githubusercontent.com/34715963/181502304-1ab95aa4-fd97-4cb6-9e93-21409840e33d.png)

## Expected result:
`Regional ad relevance` is shown
![image](https://user-images.githubusercontent.com/34715963/181502269-5296fc80-ea19-49d2-a72c-ae461751e11d.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.42.78 Chromium: 103.0.5060.134 (Official Build) beta (64-bit)
-- | --
Revision | 8ec6fce403b3feb0869b0732eda8bd95011d333c-refs/branch-heads/5060@{#1262}
OS | Linux

Brave | 1.43.51 Chromium: 104.0.5112.57 (Official Build) beta (64-bit)
-- | --
Revision | 212fd173a0da1e0a024f328295bb56a2529190bb-refs/branch-heads/5112@{#1042}
OS | Windows 10 Version 21H2 (Build 19044.1826)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

cc @rebron @jsecretan @aseren @brave/qa-team

**Comment by LaurenWags** [comment]
Requires `1.42.83` or higher to test 👍🏻

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.42.83 Chromium: 104.0.5112.69 (Official Build) (64-bit)
-- | --
Revision | 7ce2902023c722af8564068e6b26e934b83fd774-refs/branch-heads/5112@{#1213}
OS | Ubuntu 18.04 LTS

Verified test plan from the description

#### locale: `US`, geo: `US-CA` 
![image](https://user-images.githubusercontent.com/34715963/181822080-454f871d-585d-46a3-b49d-5027275d5e24.png)

**Comment by btlechowski** [comment]
Verification passed on Brave v1.42.85 on Samsung s7 (Android 8.0).

Verified test plan from the description

![Screenshot_20220803-004507_Brave](https://user-images.githubusercontent.com/34715963/182486425-bf76f457-aa0f-41b7-8127-775b6d778d68.jpg)
