### ISSUE TITLE
Typo in credit page: brave://credits/

### ISSUE THREAD

**Issue by kerHbal** [brave/brave-browser#2431]
## Description 
Homepage for Blink is wrong:
![](https://i.imgur.com/3aFpuL0.png)

## Actual result:
Showed above.

## Expected result:
Should be:
https://www.chromium.org

## Brave version (brave://version info)
Brave | 0.57.18 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Windows
JavaScript | V8 7.1.302.28

**Comment by kirkins** [comment]
Nice find, this is actually an issue in chromium automatically pulled in by Brave.

**Comment by kerHbal** [comment]
@kirkins Oh I see. I'll close this issue.
