### ISSUE TITLE
Wallet send address validation not checked after switching accounts

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#24325]
## Description 

During a send transaction, we validate to make sure the to address does not match the from address. After switching selected accounts, this validation is not re-checked which can allow the user to create a send transaction with a matching to/from address.

## Steps to Reproduce
   1. Open Send transaction panel
   2. Copy address for Account 1
   3. Enter a value to send, valid given current balance of token being sent in Account 1
   4. Use account selector to select Account 2
   5. Paste address for Account 1 in the 'to' field
   6. Use account selector to select Account 1
   7. Click 'send'
   8. Observe from address and to address are the same in the Transaction Confirmation panel

## Actual result:

https://user-images.githubusercontent.com/5314553/181632400-5792ed66-efa7-487a-b39e-c751b6ac2dca.mov

## Expected result:

Validation for send to address is checked again when the selected account is changed

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

Version 1.44.5 Chromium: 104.0.5112.69 (Official Build) nightly (arm64)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.46.70 Chromium: 107.0.5304.36 (Official Build) beta (64-bit) 
-- | --
Revision | `2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}`
OS | Linux

- Verified steps from issue description and [brave/brave-core#15253](https://github.com/brave/brave-core/pull/15253)
- Verified wallet address is verified when switching accounts

https://user-images.githubusercontent.com/17010094/197781999-0824088c-8b92-4da2-8cf5-99feadad7687.mp4


------------------------
Verification passed on

Brave | 1.46.70 Chromium: 107.0.5304.36 (Official Build) beta (64-bit) 
-- | --
Revision | `2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}`
OS | Windows 11 Version 22H2 (Build 22621.674)

- Verified steps from issue description and [brave/brave-core#15253](https://github.com/brave/brave-core/pull/15253)
- Verified wallet address is verified when switching accounts

https://user-images.githubusercontent.com/17010094/197783720-a177c044-4331-4c3f-985d-47ded892e59c.mp4

------------------------
Verification passed on

Brave | 1.46.70 Chromium: 107.0.5304.36 (Official Build) beta (arm64)
-- | --
Revision | `2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from issue description and [brave/brave-core#15253](https://github.com/brave/brave-core/pull/15253)
- Verified wallet address is verified when switching accounts

https://user-images.githubusercontent.com/17010094/197780240-edbc7485-12be-4943-ba72-69eb668de51c.mov
