### ISSUE TITLE
Add additional Password-protection to private key reveal from Account screen

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#24322]
## Description 

To increase the overall security, revealing a private key from the account screen should require re-entering the wallet password

## Steps to Reproduce

1. Unlock the Brave wallet
2. Navigate to Accounts -> Select Account1 -> Account details -> Private Key -> Show key

## Actual result:

Key is revealed without additional credential check

## Expected result:
User is prompted to enter their password before they can click the "Show key" button

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.44.83 Chromium: 105.0.5195.102 (Official Build) beta (64-bit)
-- | --
Revision | `4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}`
OS | Linux

- Verified steps from [brave/brave-core#14390](https://github.com/brave/brave-core/pull/14390)
- Verified password is requested before showing private key
- Verified `Show Key` buttons is disabled when no input is given
- Verified `Show Key` button is disabled when wrong password is entered
- Verified `Show Key` changes to `Hide Key` when correct password is entered to reveal the private key

Enter Password | Show Key enabled for password | Invalid Password | Hide Key
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/189906924-2002a4cb-44d3-4ad8-8822-66ff897de020.png) | ![image](https://user-images.githubusercontent.com/17010094/189907060-87201c2f-8d3a-4a47-adfa-0a50c520e7fd.png) | ![image](https://user-images.githubusercontent.com/17010094/189907101-2fcbfdfb-a036-42d5-8725-9a6e5e6bbece.png) | ![image](https://user-images.githubusercontent.com/17010094/189908382-8447c92c-85ae-4757-9464-00b58832484d.png)



------------------------
Verification passed on

Brave | 1.44.83 Chromium: 105.0.5195.102 (Official Build) beta (64-bit)
-- | --
Revision | `4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}`
OS | Windows 11 Version 21H2 (Build 22000.795)

- Verified steps from [brave/brave-core#14390](https://github.com/brave/brave-core/pull/14390)
- Verified password is requested before showing private key
- Verified `Show Key` buttons is disabled when no input is given
- Verified `Show Key` button is disabled when wrong password is entered
- Verified `Show Key` changes to `Hide Key` when correct password is entered to reveal the private key

Enter Password | Show Key enabled for password | Invalid Password | Hide Key
-- | -- | -- | --
<img  src="https://user-images.githubusercontent.com/17010094/189908513-964c1a10-df81-4766-881a-285eb1349913.png"> | <img  src="https://user-images.githubusercontent.com/17010094/189908495-69363ed2-b68b-4c9d-958a-a2501a361910.png"> | <img  src="https://user-images.githubusercontent.com/17010094/189908483-417ae803-5107-48cc-b9f7-94d68cc4a57b.png"> | <img  src="https://user-images.githubusercontent.com/17010094/189908476-a8c912ed-5d4a-47b6-95c8-bb22c37e4e61.png">


------------------------
Verification passed on

Brave | 1.44.79 Chromium: 105.0.5195.102 (Official Build) beta (arm64)
-- | --
Revision | `4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [brave/brave-core#14390](https://github.com/brave/brave-core/pull/14390)
- Verified password is requested before showing private key
- Verified `Show Key` buttons is disabled when no input is given
- Verified `Show Key` button is disabled when wrong password is entered
- Verified `Show Key` changes to `Hide Key` when correct password is entered to reveal the private key

Enter Password | Show Key enabled for password | Invalid Password | Hide Key
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/189906557-3409cfd0-aa88-4aae-be7c-0e0e985e9122.png) | ![image](https://user-images.githubusercontent.com/17010094/189906567-b934eb49-1eb8-4c4f-916d-98db5b1fe80e.png) | ![image](https://user-images.githubusercontent.com/17010094/189906589-97dc2ebb-1575-49b6-bb0b-c22a77f17112.png) | ![image](https://user-images.githubusercontent.com/17010094/189908081-e853a4ca-5cd3-4d10-9ff4-062cecd59331.png)

**Comment by aranyakax** [comment]
Under "Enter Password", it _should_ say, "Enter wallet password" instead of "Enter new password".
