### ISSUE TITLE
Wrong cookies state in Brave shields after adding URL in `brave://settings/cookies`

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#24321]
Follow up to https://github.com/brave/brave-browser/issues/8604

After adding URL in `brave://settings/cookies`, the state in Brave Shields does not reflect actual state

## Steps to Reproduce

1. Clean profile
1. Open `brave://settings/cookies`
1. add `www.whatismybrowser.com` in `Sites than can always use cookies` (do not check `Including third-party cookies on this site`)
1. Open Return to [www.whatismybrowser.com](http://www.whatismybrowser.com/) site and check cookie Shield settings

## Actual result:

Brave Shields shows: `Allow all cookies`
But behaves differently (blocks 3rd party cookies)
![image](https://user-images.githubusercontent.com/34715963/181626384-5bb5eb55-5280-4f8c-a9e3-d7dabe1050d7.png)

## Expected result:
Brave Shields shows: ??
Definitely not `Allow all cookies` as the definitions are different

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.42.78 Chromium: 103.0.5060.134 (Official Build) beta (64-bit)
-- | --
Revision | 8ec6fce403b3feb0869b0732eda8bd95011d333c-refs/branch-heads/5060@{#1262}
OS | Ubuntu 18.04 LTS

cc @rebron @boocmp @MadhaviSeelam @LaurenWags

**Comment by boocmp** [comment]
Yep, there is a bug in brave_shields_util.cc, should show 'block 3p' as it actually acts.

**Comment by boocmp** [comment]
@rebron 
Another case: we can "Allow all cookies" by default and then disable only first-party cookies for the site. The actual state will be "Allow only third party" (we haven't state for it in the bubble), in this case "Allow all cookies" will be displayed. What should we do?

**Comment by bridiver** [comment]
The bug here is actually that shields reflects settings adding in `brave://settings/cookies` at all. Shields is a simplified UI by design and is not intended to cover the full range of all possible cookie settings. The shields UI should always show the value of the shields cookie settings which in this case would presumably be the default of block 3p. The setting in `brave://settings/cookies` will override that, but that does not change the value of the current shields cookie setting just like changing the shields cookie settings should not delete or change any settings manually added to `brave://settings/cookies`. For instance there is no equivalent shield setting to allow site.com including third-party cookies on this site because that translates into cookies for site.com being allowed whether they are first-party or third-party. The combination of shields settings and `brave://settings/cookies` will be applied correctly and non-default shields settings show up in `brave://settings/cookies`, but trying to create a drop-down option for every possible setting you can do in `brave://settings/cookies` is impractical and defeats the purpose.

**Comment by bridiver** [comment]
@petemill re ^^ we could potentially show some kind of "warning" icon next to the shield settings if there are other settings that apply to the site in `brave://settings/cookies`

**Comment by iefremov** [comment]
we probably can @rebron about potential UX updates

**Comment by bridiver** [comment]
@btlechowski just to be clear this reverts an earlier incorrect change that showed the effective cookie setting instead of the brave shields cookie setting. The dropdown is now back to what it has always been before that and we should address what we want to do about the combination of chromium and brave cookie settings (either the warning icon or disable the ability to add chromium cookie settings) cc @pes10k

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.48.131 Chromium: 109.0.5414.87 (Official Build) beta (64-bit)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | Windows 11 Version 21H2 (Build 22000.1455)
```

Case 1:  Select cookies setting in `brave://settings/cookies` - `Allow all cookies`
<details>

1. Install 1.48.131
2. launch Brave
3. visit  www.whatismybrowser.com in  a new-tab  
4. confirmed default settings for cookies `Block cross-site cookies` displayed as expected
5. open `brave://settings/cookies` in a new-tab
6. Select `Allow all cookies` 
7. return to  www.whatismybrowser.com site
8. confirmed `Allow all cookies` displayed in the Shields panel
9. open `brave://settings/shields`
10. confirmed `Disabled` selection displayed for `Block cookies` option as expected

step 4|step 6|step 8|step 10
------|-------|-------|------
<img width="954" alt="image" src="https://user-images.githubusercontent.com/98358127/213254512-3e2d97ff-4255-4756-9f8b-fe80cab531f8.png">|<img width="940" alt="image" src="https://user-images.githubusercontent.com/98358127/213237745-7159e444-e1b0-4e5b-8782-f9dea73c2ac0.png">|<img width="954" alt="image" src="https://user-images.githubusercontent.com/98358127/213254879-0753fb6d-c088-473e-a9dd-50e2fffb4b40.png">|<img width="958" alt="image" src="https://user-images.githubusercontent.com/98358127/213255323-7d4ebba8-ac10-4c97-8e0e-1eb4ce902f84.png">
</details>

Case 2:  Select shields cookie setting in the Shields panel - `Block all cookies` 
<details>

1. continue from Case 1: 
      - `brave://settings/cookies` shows `Allow all cookies`
      - `brave://settings/shields` shows `Disabled`
      - Shields panel on `whatismybrowser.com` shows  `Allow all cookies`
2. return to `whatismybrowser.com` site 
3. select `Block all cookies` in the Shields panel
4. refresh the page 
5. confirmed `Block all cookies` selection is retained
6. visit brave://settings/cookies
7. verified previous selection (Case 1) `Allow all cookies` is retained
8. open `brave://settings/shields`
9. verified previous selection (Case 1)  `Disabled` is retained
10. verified  `www.whatismybrowser.com` is shown in `Sites that can never use cookies` 

step 1|step 5|step 7|step 9|step 10
-----|-----|------|------|-------
<img width="954" alt="image" src="https://user-images.githubusercontent.com/98358127/213254879-0753fb6d-c088-473e-a9dd-50e2fffb4b40.png">|<img width="951" alt="image" src="https://user-images.githubusercontent.com/98358127/213256654-4dc5df6c-701a-4dd4-9346-ab59dcb0fb4f.png">|<img width="952" alt="image" src="https://user-images.githubusercontent.com/98358127/213248604-1e9f4c3e-cec7-420c-98b4-509e2773116d.png">|<img width="956" alt="image" src="https://user-images.githubusercontent.com/98358127/213248817-de6e2b48-7169-456e-9d5b-dc775ddac0f8.png">|<img width="949" alt="image" src="https://user-images.githubusercontent.com/98358127/213256789-519dfd96-befe-4a05-8466-6506c039aadb.png">

</details>

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.48.129 Chromium: 109.0.5414.87 (Official Build) beta (x86_64)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | macOS Version 11.7.2 (Build 20G1020)

### Case 1: Select cookies setting in `brave://settings/cookies` - `Allow all cookies`
<details>

1. installed `1.48.131`
2. launched Brave
3. visited [www.whatismybrowser.com](http://www.whatismybrowser.com/) in a new-tab
4. confirmed default settings for cookies `Block cross-site cookies` displayed as expected
5. opened `brave://settings/cookies` in a new tab
6. selected `Allow all cookies`
7. returned to [www.whatismybrowser.com](http://www.whatismybrowser.com/) site
8. confirmed `Allow all cookies` displayed in the Shields panel
9. opened `brave://settings/shields`
10. confirmed `Disabled` selection displayed for `Block cookies` option as expected

step 4 | step 6 | step 8 | step 10
-------|-------|--------|--------
<img width="1173" alt="Screen Shot 2023-01-18 at 3 11 23 PM" src="https://user-images.githubusercontent.com/387249/213315712-8bad3416-3913-4073-8693-b106e03761bd.png"> | <img width="1173" alt="Screen Shot 2023-01-18 at 3 11 45 PM" src="https://user-images.githubusercontent.com/387249/213315718-7b804d48-c8e4-4ccc-8115-163428734afc.png"> | <img width="1173" alt="Screen Shot 2023-01-18 at 3 12 01 PM" src="https://user-images.githubusercontent.com/387249/213315721-36a8a57e-eace-4655-a5bc-518b6e1de69f.png"> | <img width="1173" alt="Screen Shot 2023-01-18 at 3 12 55 PM" src="https://user-images.githubusercontent.com/387249/213315725-d94dcc0f-18ed-4ab1-b416-f48189a6c96f.png">

</details>

### Case 2: Select Shields cookie setting in the Shields panel - `Block all cookies`

<details>


</details>

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.48.140 Chromium: 109.0.5414.119 (Official Build) beta (64-bit)
-- | --
Revision | 772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}
OS | Linux
```

#### Case 1:  Select cookies setting in `brave://settings/cookies` - `Allow all cookies` - `PASSED`
<details>

1. Install 1.48.131
2. launch Brave
3. visit  www.whatismybrowser.com in  a new-tab  
4. confirmed default settings for cookies `Block cross-site cookies` displayed as expected
5. open `brave://settings/cookies` in a new-tab
6. Select `Allow all cookies` 
7. return to  www.whatismybrowser.com site
8. confirmed `Allow all cookies` displayed in the Shields panel
9. open `brave://settings/shields`
10. confirmed `Disabled` selection displayed for `Block cookies` option as expected

step 4|step 6|step 8|step 10
------|-------|-------|------











#### Case 2:  Select shields cookie setting in the Shields panel - `Block all cookies`  - `PASSED`
<details>

1. continue from Case 1: 
      - `brave://settings/cookies` shows `Allow all cookies`
      - `brave://settings/shields` shows `Disabled`
      - Shields panel on `whatismybrowser.com` shows  `Allow all cookies`
2. return to `whatismybrowser.com` site 
3. select `Block all cookies` in the Shields panel
4. refresh the page 
5. confirmed `Block all cookies` selection is retained
6. visit brave://settings/cookies
7. verified previous selection (Case 1) `Allow all cookies` is retained
8. open `brave://settings/shields`
9. verified previous selection (Case 1)  `Disabled` is retained
10. verified  `www.whatismybrowser.com` is shown in `Sites that can never use cookies` 

step 1|step 5|step 7|step 9|step 10
-----|-----|------|------|-------
