### ISSUE TITLE
Fix account approval/reject transaction parser to show the Solana tx details

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#24332]
## Description 
Fix the parser to show the solana tx details in the approval/reject dialog

## Steps to reproduce 

   1. Create a solana transaciton
   2. The approval dialog does not show the solana tx details correctly

## Actual result 
Not showing solana tx details
![Screenshot from 2022-07-29 15-46-07](https://user-images.githubusercontent.com/11755381/181738264-00a0dc70-0557-4ff5-9df6-e41561339074.png)

## Expected result
Should show solana tx details

### Additional information

Links: https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1659034844787799?thread_ts=1659004027.656119&cid=C023VS4HJ6Q

cc: @wchen342

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.42.96 x64 build
- Verified From and To address are shown in transaction approval screen
- Encountered [#24519](https://github.com/brave/brave-browser/issues/24519)

Oppo Reno 5 (Android 12.1) | Samsung Tab A (Android 10)
-- | -- 
<img width=290 src=https://user-images.githubusercontent.com/17010094/184891059-1ea02451-f92f-43de-afd2-50499fc6ba24.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/184891094-701b0f98-905a-4ddb-8197-260bbbb118cf.png>
