### ISSUE TITLE
Hide transaction advance setting and edit option on solana approve-reject 

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#24334]
## Description 
Hide transaction advance setting and edit option on solana approve-reject dialog like desktop.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.42.96 x64 build
- Verified edit/advance option is not shown for Solana transactions
- Verified SPL spend token message is shown for the first SPL transaction. Not shown on subsequent transactions


Oppo Reno 5 (Android 12.1) | Samsung Tab A (Android 10)
-- | -- 
<Img width=290 src=https://user-images.githubusercontent.com/17010094/184886753-47ba6a95-2a65-48a0-b24c-03976128557c.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/184886923-40d3a4ec-1d7e-418a-ac98-dffb94f12aa0.png>
