### ISSUE TITLE
Follow up of # 23081 - VPN can't be reconnected in the same session when internet/wifi is disconnected and reconnected

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#24331]
## Description 

Follow up of # 23081 - VPN can't be reconnected in the same session when internet/wifi is disconnected and reconnected

## Steps to Reproduce

   1. Follow the steps from https://github.com/brave/brave-browser/issues/23081

## Actual result:

VPN can't be reconnected in the same session when internet/wifi is disconnected and reconnected
![Reconnect issue](https://user-images.githubusercontent.com/38657976/181680221-c76c40ad-6ca5-4f67-b92f-2e77bcd35c5f.gif)

## Expected result:

Should be able to reconnect the VPN in the same browser session when wifi is reconnected
## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.43.51 Chromium: 104.0.5112.57 (Official Build) beta (64-bit)
-- | --
Revision | 212fd173a0da1e0a024f328295bb56a2529190bb-refs/branch-heads/5112@{#1042}
OS | Windows 10 Version 21H2 (Build 19044.1826)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@spylogsster @rebron @brave/qa-team 

Looks like the issue works fine on macOS ( as per the @stephendonner comments  https://github.com/brave/brave-browser/issues/23081#issuecomment-1186041553 ) but still as issue with Windows 10 and windows 11

The issue is reproduced by @MadhaviSeelam  on windows 11

**Comment by GeetaSarvadnya** [comment]
The issue is stil reproducible in latest beta build `Windows 10 x64 - 1.45.95 Chromium: 106.0.5249.103`

**Comment by MadhaviSeelam** [comment]
Reproduced in `1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (64-bit) ` for Win 11 x64 as well.  VPN state seem to stuck in `Connecting' status` after enabling network.  Restarting browser fixed the issue

![image](https://user-images.githubusercontent.com/98358127/195132601-f01c2dfb-29a8-4544-87e3-19d23ab5e377.png)

**Comment by GeetaSarvadnya** [comment]
The issue is still reproducible on `Windows 10 x64  - 1.47.24` and `1.46.81`

**Comment by GeetaSarvadnya** [comment]
cc: @stephendonner @srirambv @MadhaviSeelam - Could you try this issue in beta and nightly? for me issue is still reproducible.

**Comment by stephendonner** [comment]
> cc: @stephendonner @srirambv @MadhaviSeelam - Could you try this issue in beta and nightly? for me issue is still reproducible.

@GeetaSarvadnya it just worked for me on the 1st try, using 

Brave | 1.47.27 Chromium: 107.0.5304.91 (Official Build) nightly (x86_64)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | macOS Version 11.7.1 (Build 20G918)


![issue24331](https://user-images.githubusercontent.com/387249/198687131-06755039-cd6d-4a7e-9e8c-f6d401c01559.gif)

**Comment by GeetaSarvadnya** [comment]
@stephendonner Thanks for checking! For me reconnct VPN is not working when I click on `Try again` after connecting WIFI. I think this could be WIFI related issue but I am not sure. @MadhaviSeelam Could you try this on your window 11? Thanks!

![wifi disconncect and reconnect](https://user-images.githubusercontent.com/38657976/198693792-cb17355b-8f78-43fd-b9ee-9506bdfd73da.gif)

**Comment by MadhaviSeelam** [comment]
> @stephendonner Thanks for checking! For me reconnct VPN is not working when I click on `Try again` after connecting WIFI. I think this could be WIFI related issue but I am not sure. @MadhaviSeelam Could you try this on your window 11? Thanks!
> 

@GeetaSarvadnya  I am able to reproduce the issue in Win 11 x64 for a new or existing account in Beta. However having connecting issues while WiFi is still connected in Nightly.
```
Brave | 1.46.83 Chromium: 107.0.5304.68 (Official Build) beta (64-bit)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | Windows 11 Version 21H2 (Build 22000.1098)
```

https://user-images.githubusercontent.com/98358127/198704349-e0605b25-9477-4fa4-9e4b-b4a5c5327c5c.mp4

**Comment by LaurenWags** [comment]
@GeetaSarvadnya @MadhaviSeelam if this is still reproducible on Windows 1.46.x and 1.47.x with latest builds of both, please open a new issue and link here.

cc @bsclifton

**Comment by GeetaSarvadnya** [comment]
@LaurenWags @bsclifton : Logged the issue https://github.com/brave/brave-browser/issues/26579
