### ISSUE TITLE
Add Constellation/STAR encryption for P3A

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#24338]
## Description 

The nested STAR/Constellation protocol will be used to increase anonymity protections for users who opt-in to P3A. The client/browser will encrypt user metrics using the protocol before upload. The server/aggregator will collect the protected/encrypted measurements and attempt to recover their decrypted values. This new P3A method will be deployed on all platforms.

Initially, JSON reporting will still be used alongside STAR reporting, until STAR server-side collection has stabilized.

## Miscellaneous Information:

Will raise PR soon.

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.52.107 Chromium: 114.0.5735.26 (Official Build) beta (64-bit)
-- | --
Revision | 7075cbb66f0542ac3e01ddfde6b813e7d61118a5-refs/branch-heads/5735@{#454}
OS | Windows 10 Version 22H2 (Build 19045.2965)
```
- Verified the test plan from https://github.com/brave/brave-core/pull/14399

**Comment by GeetaSarvadnya** [comment]
@DJAndries I would need few clarification on the case 1 above, when I checked the `brave.p3a.next_epoch_time` time stamp `13329702685000000` in the https://www.epochconverter.com/ then time shown is in the past. Is that correct?

![image](https://github.com/brave/brave-browser/assets/38657976/f27e44aa-5920-4baf-937c-a89e130e87c6)

**Comment by DJAndries** [comment]
> 1. In Step 1 under `Test without a MITM proxy` above, when I checked the `brave.p3a.next_epoch_time` time stamp `13329702685000000` in the https://www.epochconverter.com/ then time stamp value shown is in the past (53 years ago). Is that correct? I think the next epoch time should always be in future, but I see the time stamp as `53 years ago`

please note that Chromium timestamps are saved as Windows/LDAP timestamps. if you'd like to convert the date, you can use https://www.epochconverter.com/ldap and add 0 to the value.

> 2. Under `Test with a MITM proxy` above, step 6 is not working as expected for me

updated the last step to include "Randomness requests should fail since the current fake epoch is not valid". please validate the info request, and requests made to the upload url

**Comment by GeetaSarvadnya** [comment]
@DJAndries When I run the step 5 from the test plan https://github.com/brave/brave-core/pull/14399. 

```
An /info request should be sent. Encrypted metrics should be uploaded to the upload URL after a few minutes. Randomness requests should fail since the current fake epoch is not valid.
```

I don't see `Encrypted metrics  uploaded to the upload URL`. Could you let me know where can I see `requests made to the upload url` in proxy?, when I looked at the `info` I don't see requests made to uplod url. 

Example | Example | Example
-- | -- | --
![image](https://github.com/brave/brave-browser/assets/38657976/7f38cb64-66fd-478a-96e9-0d8d3deddd6e) | ![image](https://github.com/brave/brave-browser/assets/38657976/07621a89-23bd-4c7a-87bf-c3fbaaa2e26a) | ![image](https://github.com/brave/brave-browser/assets/38657976/4b18d5fe-5834-4749-a7cd-d0cb2da195b2)

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.52.112`
