### ISSUE TITLE
Link to Rewards verification not available re: country restrictions in Rewards UI

### ISSUE THREAD

**Issue by UjCbFwtBayFM** [brave/brave-browser#24336]
Many users recently discovered they were unable to link their Rewards wallet to an exchange. The only way for them to know about it is to go to the community forum to read the announcement (that was posted the same day it went into effect). Forums being the mess they are, many users can't find it and open numerous threads about it. That trend is likely to continue as users already linked will be automatically disconnected from their exchange over time.

Adding a direct link to status updates in the Rewards UI and in the Verification info window would greatly improve user experience on that matter.

**Comment by Miyayes** [comment]
https://github.com/brave/brave-browser/issues/22905

**Comment by Miyayes** [comment]
#22905 Has this UI:

![image](https://user-images.githubusercontent.com/11497541/195621481-8c5f2243-3d5f-4ba2-83ac-954187c91ad8.png)

And also links out to https://support.brave.com/hc/en-us/articles/6539887971469.
