### ISSUE TITLE
Fill out transaction screen on modal when there is no transactions

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#24335]
## Description 

When you don't have any transactions (that Brave Wallet recognises), the transaction view within the portal looks very bare. See Screenshots of what I'm referring to. Maybe we could have some icons or CTAs. Needs design help

## Steps to Reproduce

   1. 
   2. 
   3. 

## Actual result:

<img width="326" alt="Screenshot 2022-07-29 at 15 00 10" src="https://user-images.githubusercontent.com/12224304/181766502-ce359e3e-0df8-4653-8012-0422f498c69a.png">
<img width="330" alt="Screenshot 2022-07-29 at 15 00 14" src="https://user-images.githubusercontent.com/12224304/181766524-b4dec9be-1792-4a8a-b54a-f2636b70764c.png">

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kleantzogu** [comment]
![Recent Transactions](https://user-images.githubusercontent.com/2451237/182600033-98a1a89c-64e2-4526-9a54-aa522af42061.png)

Figma Link: https://www.figma.com/file/jZrVG7dsi5npXFTDC6LDGn/Crypto?node-id=7184%3A250487

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.47.161 Chromium: 109.0.5414.61 (Official Build) beta (64-bit) 
-- | --
Revision | `846c6eff1c374cde417a9cdc44193545cc07f354-refs/branch-heads/5414@{#1030}`
OS | Linux

- Verified steps from [brave/brave-core#15489](https://github.com/brave/brave-core/pull/15489)
- Verified the copy is same as figma which doesn't include the colour palette 

Light Theme | Dark Theme
-- | --
![image](https://user-images.githubusercontent.com/17010094/210765499-cd0bb9a7-13c2-4647-8a6e-79f90fe099d6.png) | ![image](https://user-images.githubusercontent.com/17010094/210765454-99ab96bb-fffc-4f5b-aae6-8ca01c0158ea.png)

---------------------

Verification passed on 

Brave | 1.47.161 Chromium: 109.0.5414.61 (Official Build) beta (64-bit) 
-- | --
Revision | `846c6eff1c374cde417a9cdc44193545cc07f354-refs/branch-heads/5414@{#1030}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#15489](https://github.com/brave/brave-core/pull/15489)
- Verified the copy is same as figma which doesn't include the colour palette 

Light Theme | Dark Theme
-- | --
![image](https://user-images.githubusercontent.com/17010094/210767180-90e506b3-160c-40e5-949a-fcc09846a018.png) | ![image](https://user-images.githubusercontent.com/17010094/210767251-675f13e3-b0e9-46ae-8dcd-20b099b2ba3c.png)


---------------------

Verification passed on 

Brave | 1.47.161 Chromium: 109.0.5414.61 (Official Build) beta (arm64)
-- | --
Revision | `846c6eff1c374cde417a9cdc44193545cc07f354-refs/branch-heads/5414@{#1030}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#15489](https://github.com/brave/brave-core/pull/15489)
- Verified the copy is same as figma which doesn't include the colour palette 

Light Theme | Dark Theme
-- | --
![image](https://user-images.githubusercontent.com/17010094/210766029-f3fabdbb-7b82-45eb-9821-9b77eae4935e.png) | ![image](https://user-images.githubusercontent.com/17010094/210766107-bfff0903-51e5-43c0-a246-b60278ea0b3b.png)
