### ISSUE TITLE
`Regional ad relevance` is not shown in `brave://rewards` after changing locale

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#24342]
Follow up to https://github.com/brave/brave-browser/issues/21038. The issue is still reproducible.

## Steps to Reproduce

1. Set locale to English (United States). On Windows: Set `Regional format` Windows setting to `English (United States)`
1. Use US connection (or use charles to override `https://geo.ads.brave.com/v1/getstate` with `{"country":"US","region":"CA"}`)
1. Run Brave with logging enabled
1. Enable rewards and ads
1. Make sure that response from `https://geo.ads.brave.com/v1/getstate` has proper country(US) and region
1. Open `Brave Private Ads settings` in `brave://rewards/`
1. Check if `Regional ad relevance` is shown
1. Change `Regional ad relevance` to `Alabama`
1. Close Brave
1. Set locale to Poland Polish
1. Run Brave
1. Open `Brave Private Ads settings` in `brave://rewards/`
1. Close Brave
1. Set locale to English (United States)
1. Run Brave
1. Open `Brave Private Ads settings` in `brave://rewards/`

## Actual result:

`Regional ad relevance` is not shown
![image](https://user-images.githubusercontent.com/34715963/181824675-a4f47ae4-599d-4829-ae08-1d10062898f4.png)

## Expected result:
`Regional ad relevance` is shown
![image](https://user-images.githubusercontent.com/34715963/181824387-31b1f87b-876e-4240-b03a-21ac8f4fe771.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.42.83 Chromium: 104.0.5112.69 (Official Build) (64-bit)
-- | --
Revision | 7ce2902023c722af8564068e6b26e934b83fd774-refs/branch-heads/5112@{#1213}
OS | Ubuntu 18.04 LTS

cc @rebron @tmancey @aseren @brave/qa-team

**Comment by tmancey** [comment]
@aseren if you could close and add a QA/Yes label and set the milestone when merging https://github.com/brave/brave-browser/issues/16682 that would be great :-)

**Comment by aseren** [comment]
The issue was fixed here: https://github.com/brave/brave-browser/issues/16682

**Comment by aseren** [comment]
The issue was fixed here: https://github.com/brave/brave-browser/issues/16682

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Samsung galaxy Tab A7` version 12 running `Bravemonoarm64.apk_1.45.106`

- Confirmed that when country and region is overriden to `{"country":"US","region":"CA"})` the `Regional ad relevance` is shown in the brave://rewards Ads settings section
- Confirmed that when the locale is set to `Poland Polish` the `Regional ad relevance` is NOT shown in the brave://rewards Ads settings section (`Regional ad relevance` is supported for only "US")

Example | Example | Example | Example | Example |Example
-- | -- | -- | -- | -- | --
![image (8)](https://user-images.githubusercontent.com/38657976/196762903-9051843c-0d25-4bb2-873c-26f348dbb7a4.png) | ![Screenshot_20221019-224358_Brave](https://user-images.githubusercontent.com/38657976/196763340-0a6283d3-70ba-41ab-96c3-047aff7d5f38.jpg) | ![Screenshot_20221019-224505_Brave](https://user-images.githubusercontent.com/38657976/196763502-30e5b628-f7ff-45ea-a9fd-defe7edc21a5.jpg) | ![Screenshot_20221019-224638_Settings](https://user-images.githubusercontent.com/38657976/196763816-3026ab30-dbee-43f2-bfd6-e546ee3566e2.jpg) | ![Screenshot_20221019-224707_Brave](https://user-images.githubusercontent.com/38657976/196763933-f6f53fc2-7851-4290-abcd-6c48616fd127.jpg) | ![Screenshot_20221019-224819_Brave](https://user-images.githubusercontent.com/38657976/196764106-254d30e1-3bb4-47aa-a86f-60d03916fc3b.jpg)
