### ISSUE TITLE
Show solana icon in the BuySendSwap or anywhere if it is missing

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#24340]
## Description 
Show Solana icon in the BuySendSwap (asset selector, etc.)or anywhere if it is missing

**Comment by noobyogi0010** [comment]
@Pavneet-Sing I would like to work on this issue if no one else has already taken it up.

**Comment by Pavneet-Sing** [comment]
@noobyogi0010 thanks for your interest though this suppose to be fixed soon as it has P2 priority so likely to be picked up and finished soon. May I suggest some issues to work on
https://github.com/brave/brave-browser/issues/23514
https://github.com/brave/brave-browser/issues/23362
https://github.com/brave/brave-browser/issues/20886
Most likely the above issue won't have any activity anytime soon, though feel to go though others issue to work on, preferably the one that does not have any dependency like UI mocks or info-needed and has priority p3 or preferably p4. Happy coding!

**Comment by noobyogi0010** [comment]
Thank you @Pavneet-Sing 
I'll look into these issues.

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 Android 12.1 running 1.42.96 x64 build
- Verified steps from issue description 
- Verified correct SOL token is displayed when selected on Send screen 
----------
Verification passed on Samsung Tab A Android 10 running 1.42.96 x64 build
- Verified steps from issue description 
- Verified correct SOL token is displayed when selected on Send screen
