### ISSUE TITLE
Unable to import saved passwords from Edge (Chromium, macOS, Linux)

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#24343]
## Description 

Unable to import saved passwords from Edge (Chromium, macOS)

## Steps to Reproduce

1. seed a Microsoft Edge profile with saved password(s)
2. double-check that `edge://settings/passwords` has entries
3. install `1.44.8`
4. launch Brave
5. click on `Skip welcome screen`
6. click on `Import bookmarks now...`
7. choose `Microsoft Edge Profile 1`
8. note that `Saved passwords` is listed and checked, by default
9. click on `Import`

## Actual result:

No saved passwords are imported

<img width="1312" alt="Screenshot 2022-07-29 at 1 45 29 PM" src="https://user-images.githubusercontent.com/387249/181840797-19f7a5ba-1eb2-41a4-b37e-96411494c4b2.png">

## Expected result:

Should import saved passwords; they should show up in `brave://settings/passwords`

<img width="1792" alt="Screenshot 2022-07-29 at 1 48 00 PM" src="https://user-images.githubusercontent.com/387249/181840880-116317be-31f6-4001-b1e2-924484c2725e.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.44.8 Chromium: 104.0.5112.69 (Official Build) nightly (x86_64)
-- | --
Revision | 7ce2902023c722af8564068e6b26e934b83fd774-refs/branch-heads/5112@{#1213}
OS | macOS Version 13.0 (Build 22A5311f)

cc @rebron @spylogsster @simonhong @LaurenWags

**Comment by LaurenWags** [comment]
Reproduces with Linux as well (Ubuntu 20.04)

```
Brave	1.42.84 Chromium: 104.0.5112.69 (Official Build) (64-bit) 
Revision	7ce2902023c722af8564068e6b26e934b83fd774-refs/branch-heads/5112@{#1213}
OS	Linux
```

**Comment by bsclifton** [comment]
Related https://github.com/brave/brave-browser/issues/24130

**Comment by kjozwiak** [comment]
The above will require `1.43.77` or higher for `1.43.x` verification 👍

**Comment by kjozwiak** [comment]
The above will require `1.43.80` or higher for `1.43.x` verification. Looks like we missed the Edge portion of the fix from https://github.com/brave/brave-core/pull/14559 when uplifting https://github.com/brave/brave-core/pull/14663. @spylogsster created https://github.com/brave/brave-core/pull/14741 which adds the `Edge` cases 👍

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.43.81 Chromium: 104.0.5112.102 (Official Build) (64-bit)
-- | --
Revision | 8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}
OS | Ubuntu 18.04 LTS

Issue is still reproducible. Per our process created a follow up https://github.com/brave/brave-browser/issues/25001

![image](https://user-images.githubusercontent.com/34715963/186912601-55463de6-cc6b-41b9-a8de-0caa3c007529.png)
