### ISSUE TITLE
Brave Settings Sidebar Disappears on Narrow Screens

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#24352]
## Description 
When shrinking the Brave window the settings menu disappears. It looks like it should be moved to a hamburger menu, but no menu becomes visible.

Settings page (981px wide):
![image](https://user-images.githubusercontent.com/7678024/182055612-ea223678-d464-4374-8fd6-108c7f1d38cd.png)
^ At this size, the side bar is still visible.

Settings page (980px wide):
![image](https://user-images.githubusercontent.com/7678024/182057831-718dc90b-f045-462e-88a6-a1b5bc29fd0f.png)
^ However, shrinking the window slightly smaller, the menu disappears. In similar UIs, it would be possible to summon the menu back with a `Hamburger` button. However, we seem to be missing one.

## Steps to Reproduce

   1. Open the settings page.
   2. Shrink the window until the menu disappears

## Actual result:
It should still be possible to access other areas of settings.

## Expected result:
You are stuck on the currently open settings section. There is no way to access others (beyond resizing the window or searching)

## Reproduces how often: 

Always

## Brave version (info found on brave://version)

1.41.96 Chromium: 103.0.5060.114 (Official Build) (64-bit) 

I think this has been around for longer though. Present on at least Windows & Linux. Probably not a problem on Android 😆 

@rebron

**Comment by TitouanLeDilavrec** [comment]
Same issues 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.54.85 Chromium: 115.0.5790.56 (Official Build) beta (64-bit)
-- | --
Revision | ebcfb87c1393f36955cfa2f6451a1767e3dc3ee5-refs/branch-heads/5790@{#1193}
OS | Windows 10 Version 22H2 (Build 19045.3155)
```

Followed the steps to reproduce from https://github.com/brave/brave-browser/issues/24352#issue-1323690490

### Confirmed that, at all window sizes, I get the nav menu icon appearing, which opens the navigation menu, when clicked

example | example | example | example
----------|-----------|-----------|---------
![image (2)](https://github.com/brave/brave-browser/assets/387249/61cafc36-24ce-4305-a54c-357de7ce7935) | ![image (3)](https://github.com/brave/brave-browser/assets/387249/b13a598a-15e1-4544-800c-a1842e525c72) | ![image (4)](https://github.com/brave/brave-browser/assets/387249/847b9ca1-b3d3-40aa-87d5-a2f4eb8b7a3c) | ![image](https://github.com/brave/brave-browser/assets/387249/dcd11fa5-4e2a-4d0b-b09e-4a7e6c3f4d4e)
