### ISSUE TITLE
Currency selector not working in wallet panel

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#24357]
https://user-images.githubusercontent.com/48117473/182137580-a0369dd2-306c-464d-9291-a1846da550cc.mov

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.44.97 Chromium: 106.0.5249.40 (Official Build) (64-bit) 
-- | --
Revision | `4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}`
OS | Linux

- Verified steps from [brave/brave-core#14423](https://github.com/brave/brave-core/pull/14423)
- Verified selecting a currency from the list updates the current currency symbol
- Verified able to search for currency and select

https://user-images.githubusercontent.com/17010094/191812320-9d7b507d-4539-4980-bd89-ed9e6f4e1160.mp4


------------------------
Verification passed on

Brave | 1.44.97 Chromium: 106.0.5249.40 (Official Build) (64-bit) 
-- | --
Revision | `4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}`
OS | Windows 11 Version 21H2 (Build 22000.978)

- Verified steps from [brave/brave-core#14423](https://github.com/brave/brave-core/pull/14423)
- Verified selecting a currency from the list updates the current currency symbol
- Verified able to search for currency and select

https://user-images.githubusercontent.com/17010094/191811466-37628986-f68d-4395-aa02-3efa3cdf9526.mp4


------------------------
Verification passed on

Brave | 1.44.97 Chromium: 106.0.5249.40 (Official Build) (arm64)
-- | --
Revision | `4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [brave/brave-core#14423](https://github.com/brave/brave-core/pull/14423)
- Verified selecting a currency from the list updates the current currency symbol
- Verified able to search for currency and select

https://user-images.githubusercontent.com/17010094/191812528-0791eff2-eca8-48da-bce3-8df09486b0f8.mov
