### ISSUE TITLE
Sardine Integration - Frontend

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#24356]
- Add sardine token list
- Add sardine as an onramp provider in the buy tab

**Comment by muliswilliam** [comment]
- Add sardine token list
- Add sardine as an onramp provider in the buy tab

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.44.97 Chromium: 106.0.5249.40 (Official Build) (64-bit) 
-- | --
Revision | `4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}`
OS | Linux

- Verified steps from [brave/brave-core#14353](https://github.com/brave/brave-core/pull/14353)
- Verified Sardine is available as on-ramp provider for buy
- Verified able to submit a buy via Sardine on both Buy widget and via panel

https://user-images.githubusercontent.com/17010094/191817269-64ea2796-187e-4791-913b-1ea4dfa2987d.mp4


------------------------
Verification passed on

Brave | 1.44.97 Chromium: 106.0.5249.40 (Official Build) (64-bit) 
-- | --
Revision | `4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}`
OS | Windows 11 Version 21H2 (Build 22000.978)

- Verified steps from [brave/brave-core#14353](https://github.com/brave/brave-core/pull/14353)
- Verified Sardine is available as on-ramp provider for buy
- Verified able to submit a buy via Sardine on both Buy widget and via panel

https://user-images.githubusercontent.com/17010094/191818848-a500a37f-357d-4641-bbb0-8e90c7389fc5.mp4


------------------------
Verification passed on

Brave | 1.44.97 Chromium: 106.0.5249.40 (Official Build) (arm64)
-- | --
Revision | `4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [brave/brave-core#14353](https://github.com/brave/brave-core/pull/14353)
- Verified Sardine is available as on-ramp provider for buy
- Verified able to submit a buy via Sardine on both Buy widget and via panel

https://user-images.githubusercontent.com/17010094/191819551-06e83eab-a779-4c1c-9f7c-0acdf8b445ec.mov
