### ISSUE TITLE
Follow up of  #24241 - Pin to taskbar from first run dialog 

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#24363]
## Description 

Follow up of #24241 - Pin to taskbar from first run dialog 

## Steps to Reproduce

   1. Follow steps from https://github.com/brave/brave-browser/issues/24241#issue-1316251741

## Actual result:
Brave is not pinned to task bar after selecting to be a default browser
![image](https://user-images.githubusercontent.com/98358127/182199039-84bdaa0d-7079-4f0c-aedb-a5a3910aba58.png)

## Expected result:
 Brave should be pinned to taskbar 
Ex1|Ex2
----|----
<image width="800" alt="image" src="https://user-images.githubusercontent.com/98358127/181862048-30c79fc7-cbaa-459c-ba4f-a10bfba2a150.png">|<image width="800" alt="image" src="https://user-images.githubusercontent.com/98358127/181862055-492af73c-7584-4577-8459-5b5a54c7f9a6.png">
## Reproduces how often: 

Easily

## Brave version (brave://version info)

Brave | 1.44.12 Chromium: 104.0.5112.69 (Official Build) nightly (64-bit)
-- | --
Revision | 7ce2902023c722af8564068e6b26e934b83fd774-refs/branch-heads/5112@{#1213}
OS | Windows 11 Version 21H2 (Build 22000.795)

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@simonhong @rebron

**Comment by simonhong** [comment]
Set QA/No because this can be verified from https://github.com/brave/brave-browser/issues/24241

**Comment by simonhong** [comment]
@MadhaviSeelam Please check again when nightly build has fix for this!
