### ISSUE TITLE
Tab switcher redesign is unusable

### ISSUE THREAD

**Issue by adrianinsaval** [brave/brave-browser#24366]
## Description 
After updating brave browser on android the tab switcher interface has changed from a grid with previews where I could group tabs and with drag and drop support, to a useless list without groups or drag and drop support. I cannot organize or group my tabs anymore, it's become unusable.

## Steps to reproduce 

   1. update brave on android
   2. open tab switcher
   3. suffer

## Actual result 
tabs are shown in a list with no functionality

## Expected result
previous grid interface or at least feature parity in new list interface

## Issue reproduces how often 
always

## Version/Channel Information:
tested only Play Store version

## Device details
   - Install type (ARM, x86): arm
   - Device type (Phone, Tablet, Phablet): phone
   - Android version: 11
   
## Brave version
1.41.100, chromium 103.0.5060.134

**Comment by adrianinsaval** [comment]
I have no clue what happened but this appear to have been some sort of bug, tabs are back to normal now and it doesn't seem like brave got any update... very weird stuff.

**Comment by bsclifton** [comment]
@adrianinsaval thanks for following back up - I read your original report and was confused also. 

The old version of Brave used to be that list you're talking about (called "stack view"). You can see what it looks like here:
https://github.com/brave/brave-browser/issues/22028

The feature request we have tracking it would be to make it an option for folks that want to enable it. The grid view is the default and should be what you're seeing 😄

**Comment by adrianinsaval** [comment]
Actually it wasn't like the "stacked" view, there where no previews of the tabs, just a list with close buttons on the right, not even the correct icons where shown, strangely Google Chrome had the same issue at the same time and now has a grid again too.

**Comment by jtwil** [comment]
@bsclifton
I've currently got the same problem described in this issue. I'm using Brave 1.41.100 on Android 12.

Here's a screenshot of the tab switcher
![Screenshot_20220805-230758](https://user-images.githubusercontent.com/44239453/183218166-4fe84366-0cf0-4230-b21b-fdfa8eda827c.png)

**Comment by adrianinsaval** [comment]
yeap that's the useless switcher I got! i'll reopen the issue since it's not only me. I don't have the problem anymore and have no clue how it got solved. Do you have google chrome installed? When you open it does it have the same tab switcher?

**Comment by bsclifton** [comment]
cc: @deeppandya @SergeyZhukovsky

**Comment by jtwil** [comment]
I'm still experiencing this problem after updating to Brave 1.42.94

**Comment by jtwil** [comment]
Hmm... Just found [this article](https://www.askvg.com/fix-google-chrome-tab-switcher-ui-changed-to-basic-horizontal-list-on-android/) about the same thing in Chrome. Turns out it's an Accessibility setting in Chrome (and Brave). According to that article when accessibility settings are enabled on Android, Chrome enables the simplified tab view. I've never had them enabled on my phone, though.

Must be a bug somewhere in Chrome/Brave when it decides to silently enable this feature.

**Comment by adrianinsaval** [comment]
Oh lord what bullshit, yes I was playing around and had enabled the kde connect app accessibility permissions (it's for remote control actually). Somehow it got disabled later and that fixed the problem, now I enabled it again to test and sure enough that useless switcher was activated. Disabling "Simplified view for open tabs" on accessibility settings (or disabling the accessibility permissions for kde connect) does the trick.

Check if really don't have any app using accessibility for other functions.

**Comment by adrianinsaval** [comment]
Seems to be a feature and if anything it would be an upstream issue -> closing again.
