### ISSUE TITLE
Implement Bridge to Aurora button

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#24377]
From supported assets detail screen (on Aurora... NEAR) we will want to add a quick link to bridge. See supported assets (note all in the image below should include the bridge button)

![Image](https://user-images.githubusercontent.com/318119/182416307-5dc3a0e3-6167-49b2-a7aa-3b4a7f699338.png)

## Example button placement

![Image](https://user-images.githubusercontent.com/318119/182416661-94981113-7331-497d-89af-85411940c29e.png)

## Example modal for first click... subsequent clicks on bridge will not show the modal.

![Image](https://user-images.githubusercontent.com/318119/182416650-5688448f-ae03-417f-aa26-6f9ac56d8f23.png)

(clicking Open... should launch a new tab to rainbowbridge.app)

**Comment by jamesmudgett** [comment]
@rmcfadden3 please review and provide new copy for the modal.

**Comment by jamesmudgett** [comment]
Learn more link https://ethereum.org/en/bridges/#bridge-risk

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.43.81 Chromium: 104.0.5112.102 (Official Build) (64-bit)
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | Linux

- Verified steps from and as part of [#24695 (comment)](https://github.com/brave/brave-browser/issues/24695#issuecomment-1225766651)
- Verified for supported asset, there is a button Bridge to Aurora on the asset details screen
- Verified clicking on the button shows a modal about bridging details
- Verified `Learn more` opens a new tab page and loads `https://ethereum.org/en/bridges/#bridge-risk`
- Verified the modal is shown only once for the first time. Subsequent attempts doesn't show the modal
- Encountered [#24248](https://github.com/brave/brave-browser/issues/24248)

------------------------
Verification passed on

Brave | 1.43.81 Chromium: 104.0.5112.102 (Official Build) (64-bit)
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | Windows 11 Version 21H2 (Build 22000.795)

- Verified steps from and as part of [#24695 (comment)](https://github.com/brave/brave-browser/issues/24695#issuecomment-1225766651)
- Verified for supported asset, there is a button Bridge to Aurora on the asset details screen
- Verified clicking on the button shows a modal about bridging details
- Verified `Learn more` opens a new tab page and loads `https://ethereum.org/en/bridges/#bridge-risk`
- Verified the modal is shown only once for the first time. Subsequent attempts doesn't show the modal
- Encountered [#24248](https://github.com/brave/brave-browser/issues/24248)

------------------------
Verification passed on

Brave | 1.43.81 Chromium: 104.0.5112.102 (Official Build) (arm64)  
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from and as part of [#24695 (comment)](https://github.com/brave/brave-browser/issues/24695#issuecomment-1225766651)
- Verified for supported asset, there is a button Bridge to Aurora on the asset details screen
- Verified clicking on the button shows a modal about bridging details
- Verified `Learn more` opens a new tab page and loads `https://ethereum.org/en/bridges/#bridge-risk`
- Verified the modal is shown only once for the first time. Subsequent attempts doesn't show the modal
- Encountered [#24248](https://github.com/brave/brave-browser/issues/24248)
