### ISSUE TITLE
Brave does not block publicity

### ISSUE THREAD

**Issue by angelog0** [brave/brave-browser#24372]
This morning, Brave does not block the publicity on this site (see attachment) . Up to yesterday it worked just fine. Same Brave version 1.41.100 on Windows, GNU/Linux etc.

![bravethismorning](https://user-images.githubusercontent.com/35931460/182327498-cbdf24e2-8bc0-4d40-a694-bbd71a805e4f.png)

**Comment by krystian3w** [comment]
Left and right banners gone form page?

In middle possible test:

`orizzontescuola.it##.ads`

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/14230

**Comment by ryanbr** [comment]
@angelog0  Just enable Easylist Italy in `brave://adblock`  Should be fixed within the next 24hrs.
