### ISSUE TITLE
Rewards Summary does not display transactions when accessed from BAT logo in URL bar

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#2437]
## Description 
Found while testing https://github.com/brave/brave-browser/issues/2261

After updating to 0.58.11, my monthly contribution and tips were processed. I noticed that the Rewards Summary, visible on both brave://rewards and on the panel, accessed via the BAT logo were displaying differently. Rewards Summary when accessed via the BAT logo is not displaying the 'Transactions' (monthly tips, auto -contribute), but the Rewards Summary on brave://rewards is displaying this info.

## Steps to Reproduce

   1. Have a profile with rewards set up on previous beta (0.57.8 for me)
   2. Have Rewards enabled.
   3. Update to 0.57.11
   4. Claim a grant, tip, auto contribute, etc.

## Actual result:
Rewards Summary does not display transactions when accessed from BAT logo:
![screen shot 2018-12-10 at 6 05 45 pm](https://user-images.githubusercontent.com/28145373/49767468-891dc380-fca6-11e8-8a3a-d5922d4ad752.png)

## Expected result:
Rewards Summary should match brave://rewards page:
![screen shot 2018-12-10 at 6 05 29 pm](https://user-images.githubusercontent.com/28145373/49767482-963ab280-fca6-11e8-90d5-fd3d5c8d6b6d.png)

## Reproduces how often: 
 unsure

## Brave version (brave://version info)

Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta(64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? yes, found on Beta

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
Seems to be an issue with updating the profile. If I launch a clean profile on 0.58.11 and claim a grant, both Rewards Summaries match:
![screen shot 2018-12-10 at 6 10 58 pm](https://user-images.githubusercontent.com/28145373/49767571-f9c4e000-fca6-11e8-80d7-50222f9157b2.png)

![screen shot 2018-12-10 at 6 11 05 pm](https://user-images.githubusercontent.com/28145373/49767573-fcbfd080-fca6-11e8-9e04-8ded1c0bfc5e.png)

**Comment by NejcZdovc** [comment]
closing this one as it has the same problem as https://github.com/brave/brave-browser/issues/2273, so let's track it there
