### ISSUE TITLE
Adding accounts from Accounts selection screen from panel doesn't update until user navigates from account list screen 1.42.x

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#24374]
The same as https://github.com/brave/brave-browser/issues/24337 but for 1.42.x only as the original fix worked for 1.43.x and higher.

**Comment by srirambv** [comment]
This is fixed and merged as part of https://github.com/brave/brave-core/pull/14427/commits/104d0cd3197aa53f0b7ea9fe9bc57b0597de1a30

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.42.86 x64 build
- Verified steps from [#24337 ](https://github.com/brave/brave-browser/issues/24337)
- Verified newly added accounts are show up immediately 

https://user-images.githubusercontent.com/17010094/182532960-e7403e0a-853c-4e13-9ea4-31910f43b36b.mp4
