### ISSUE TITLE
Show only the short network name on approve/reject

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#24373]
## Description 
Show only the short network name on approve/reject dialog.

---

## Steps to reproduce 

Update: Currently Android shows the pending transaction of the selected network which needs to change to show pending tx of all networks then the below issue will arise

   1. Create a transaction on Solana test network
   2. Change network to Solana mainnet
   3. Open approve/reject dialog for the pending Tx and should see only "Solana" as network name instead of "Solana Mainnet Beta"

## Actual result 
Shows full network name

## Expected result
Show short name

## Issue reproduces how often 
easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): all
   - Device type (Phone, Tablet, Phablet): all
   - Android version: all
   
## Brave version
all

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? N
- Does the issue resolve itself when disabling Brave Rewards? N
- Is the issue reproducible on the latest version of Chrome? N

### Additional information

https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1659004027656119

**Comment by jamesmudgett** [comment]
We should show full network name always on transaction confirmation prompts

**Comment by Pavneet-Sing** [comment]
> We should show full network name always on transaction confirmation prompts

Created https://github.com/brave/brave-browser/issues/24382 to address the above and likely this issue(24373) will be closed.

**Comment by Pavneet-Sing** [comment]
No longer required, android is also showing [pending requests of default networks](https://github.com/brave/brave-core/pull/14497) now.

**Comment by Pavneet-Sing** [comment]
No longer required, android is also showing [pending requests of default networks](https://github.com/brave/brave-core/pull/14497) now.
