### ISSUE TITLE
Website added via Add site modal is not added to NTP

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#24370]
## Steps to Reproduce

1. Install 1.43.54
2. launch Brave
3. visit a websites (bbc.com)
4. open a new tab page
5. bbc.com is added to NTP
6. click `...` in the same view box/row as the websites
7. click `Add site`
8. add website information in the modal (usatoday.com) and save

## Actual result:

Website (`usatoday`) is not shown on NTP

https://user-images.githubusercontent.com/98358127/182249761-9d09df45-2f46-407e-b0a6-84f1d19182ee.mp4

## Expected result:
Website should be shown along with correct favicon

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Brave | 1.43.54 Chromium: 104.0.5112.69 (Official Build) beta (64-bit)
-- | --
Revision | 7ce2902023c722af8564068e6b26e934b83fd774-refs/branch-heads/5112@{#1213}
OS | Windows 11 Version 21H2 (Build 22000.795)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@fallaciousreasoning @rebron

**Comment by fallaciousreasoning** [comment]
Sounds quite similar to https://github.com/brave/brave-core/pull/14293. Would you mind checking in the latest Nightly to see if it reproduces?

**Comment by MadhaviSeelam** [comment]
@fallaciousreasoning  yes, it is reproducible in 1.44.12.  
 So the behavior in both 1.44.x and 1.43.x is 
1. click `...` --->`Add site` ---> site is not aded
2. click  `show favorites`-->`Add site`-->sites gets added to NTP
3. now click `...`-->`Add site`-->site gets added to NTP

**Comment by fallaciousreasoning** [comment]
:+1: I'll take a look

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.44.73 Chromium: 105.0.5195.68 (Official Build) beta (x86_64)
-- | --
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | macOS Version 13.0 (Build 22A5331f)

### Steps:

1. installed `1.44.73`
2. launched Brave
3. loaded `bbc.com`
4. open a new tab page
5. confirmed `bbc.com` is added to the NTP
6. clicked `...` in the same view box/row as the websites
7. clicked `Add site`
8. added website information in the modal (`usatoday.com`) and clicked `Save`

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.44.93 Chromium: 105.0.5195.136 (Official Build) beta (64-bit)
-- | --
Revision | 872774b783d0e674186a3adcd2f92e7aa22a219c-refs/branch-heads/5195_124@{#4}
OS | Windows 11 Version 21H2 (Build 22000.978)
```


Followed my original steps from the description

1. Installed 1.44.93
2. launched Brave
3. visited a websites (bbc.com)
4. opened a new tab page
5. `BBC` is added to NTP
6. click `...` in the same view box/row as the websites
7. clicked `Add site`
8. added website information in the modal (usatoday.com) and save
9. confirmed `usatoday` added to NTP favorites
10. click on the favorite (`usatoday`) to verify page is loaded
11. return to NTP to confirm the `usatoday` favicon displayed

step 3|step 5|step 7|step 8|step9|step10|step11
----|-----|-----|----|----|-----|----
<image width="1200" alt="1" src="https://user-images.githubusercontent.com/98358127/191341033-aabfc28b-212d-467b-b0e7-9b355229af90.png">|<image width="1200" alt="2" src="https://user-images.githubusercontent.com/98358127/191341206-aa72793e-369c-45cf-90e3-f8ab60f9f33b.png">|<image width="1200" alt="3" src="https://user-images.githubusercontent.com/98358127/191341346-71d82cdb-69a7-4a6c-9b0e-7f422ac098bb.png">|<image width="1200" alt="4" src="https://user-images.githubusercontent.com/98358127/191341495-381c339d-9b8f-41c9-82d4-2f64f1984fdb.png">|<image width="1200" alt="5" src="https://user-images.githubusercontent.com/98358127/191341622-1755e61e-84ff-4614-9630-d56fbd7fcc62.png">|<image width="1200" alt="6" src="https://user-images.githubusercontent.com/98358127/191341953-59572ed4-b0ab-4bc3-b440-c95a16749dda.png">|<image width="1200" alt="7" src="https://user-images.githubusercontent.com/98358127/191341885-5879dd88-7797-4bd9-9ca6-aa8feda894aa.png">
