### ISSUE TITLE
Incorrect Solana balance on Portfolio

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#24389]
Portfolio shows incorrect Solana account balance:
![Screenshot_20220802-143004_Brave - Debug](https://user-images.githubusercontent.com/12011303/182451494-2c459485-ba16-44f3-94b4-aefd4a40fa55.jpg)

The above Portfolio has only 2 SOL ^

**Comment by srirambv** [comment]
#24458 logged for SPL tokens not shown correctly

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12.1 running 1.42.96 x64 build
- Verified correct SOL balance is shown on Send screen irrespective how its selected
-----------
Verification passed on Samsung Tab A with Android 10 running 1.42.96 x64 build
- Verified correct SOL balance is shown on Send screen irrespective how its selected
