### ISSUE TITLE
[Android] Remove unused rewards code

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#24385]
This issue is to refactor previous rewards related changes. We should remove all unused references to previous rewards implementation.

**Comment by Uni-verse** [comment]
Will be tested as part of the C106 regression checks as well as checking while running through the full manual pass when C106 gets uplifted.

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress on `Samsung Galaxy Tab A7 version 11` running `Bravemonoarmx64.apk_1.44.95`
- Verified the test plan from https://github.com/brave/brave-core/pull/14434
