### ISSUE TITLE
Bind wallet transactions to a specific network rather than using current selected network afterwards

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#24384]
## Description 

Currently we are always using selected networks when sending out transactions, and lack of support for pending transactions with different networks.
We need to bind transactions to a network it is supposed to be sending out, and expose them via TransactionInfo.

Related issues:
- [Show pending tx of all networks](https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1659030105261199?thread_ts=1659004027.656119&cid=C023VS4HJ6Q) and [thread 2](https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1659461000764589)

## Miscellaneous Information:

[Front-end issue](https://github.com/brave/brave-browser/issues/24382)

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/30277#issuecomment-1592935435
