### ISSUE TITLE
Whitespace is not collapsed at the top of the page when nytimes.com site is loaded 

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#24398]
## Steps to Reproduce

   1. Install 1.42.85
   2. visit nytimes.com in  NTP
   
   
## Actual result:

White space is displayed at the top of the page in both default & aggressive shields settings

default|aggressive
----|----
<image width="850" alt="image" src="https://user-images.githubusercontent.com/98358127/182481338-e44c03aa-7677-4604-a1a5-4aeba24b10d0.png">|<image width="850" alt="image" src="https://user-images.githubusercontent.com/98358127/182481361-401dd87f-5ecb-4bb9-b0b5-f8338faa7b3e.png">

## Expected result:
White space should collapse

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Brave | 1.42.85 Chromium: 104.0.5112.81 (Official Build) (64-bit)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | Windows 11 Version 21H2 (Build 22000.795)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc: @rebron

**Comment by rebron** [comment]
cc: @ryanbr @antonok-edm

**Comment by ryanbr** [comment]
Lets see how this goes: https://github.com/easylist/easylist/commit/874f1fc2e69923e8f613fe9fb4cb9db2eff41027

Give it 24hrs and retest. If that fails, set sheilds = Aggressive @MadhaviSeelam

**Comment by ryanbr** [comment]
@MadhaviSeelam how is it looking? Just tested, the top ad header briefly shows before collapsing from what I'm seeing

**Comment by MadhaviSeelam** [comment]
@ryanbr  White space collapsed with Aggressive shields setting.  Didn't collapse in default setting.

**Comment by rebron** [comment]
@MadhaviSeelam Should we close this one out as fixed or should we consider removing white space for the default setting?

**Comment by rebron** [comment]
@ryanbr Any chance we can get hide as part of default shields setting?

**Comment by ryanbr** [comment]
Looks okay currently @rebron  . Is this working for you @MadhaviSeelam ?

![nytimes-test](https://user-images.githubusercontent.com/1659004/187884400-76104177-cd70-4034-9918-00a8dc4db1fd.gif)

**Comment by RacerDuke** [comment]
I commented on another related issue but this is the most generalized one I could find. Brave is not collapsing blocked ad space leaving big gaps in the page. Would integration of a different ad blocking engine (uBlock Origin specifically) be possible since the OG blocking engine isn't doing it?
