### ISSUE TITLE
NTP clock day period component (AM / PM) is huge

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#2439]
Chromium71 changed the type for DayPeriod from 'dayperiod' to 'dayPeriod' which means our matching fails and we end up showing the 'AM' / 'PM' / local-specific-whatever in the same font-size as the time itself.

**Comment by SilverPuppy** [comment]
How is this different from #247, where the fix is taking place? Was this created by mistake?

**Comment by petemill** [comment]
@SilverPuppy this is the reported issue, #247 is the code to fix in a dependency

**Comment by petemill** [comment]
@kjozwiak yes, same as previous release

**Comment by GeetaSarvadnya** [comment]
Verification passed on 


Brave | 0.59.6 Chromium: 71.0.3578.80 (Official Build) beta (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Windows

- Verified the time display as per the description mentioned in https://github.com/brave/brave-ui/pull/247
![image](https://user-images.githubusercontent.com/38657976/49933726-739cd980-fef2-11e8-8b59-e73b9aaadf11.png)

**Comment by srirambv** [comment]
This fails on Linux. Here's the recording https://drive.google.com/open?id=1GMl-4xRTovTsy_SMxix0dTRZ5TLAWuGf Follow up issue logged https://github.com/brave/brave-browser/issues/2530

**Comment by petemill** [comment]
It doesn’t seem like that’s a fail for this issue, which is just about the font size when the component is being displayed. The time in that video is using 24hr time format, so we wouldn’t show AM / PM in the previous font size or the corrected font size. I assume that the bug you’ve found - using 24hr time format or 12hr time format - is present on previous version too.

**Comment by srirambv** [comment]
Whats the expected clock format for NTP? I assumed it should be 12hrs format irrespective of device clock settings/format.

**Comment by srirambv** [comment]
Updated the issue title there in #2530. Its definitely not following the system format. @brave/legacy_qa can anyone try on their VM and check if they see 12/24 hr format based on system settings

**Comment by LaurenWags** [comment]
@srirambv 12hr format worked for me on Linux VM using 
![screen shot 2018-12-13 at 4 15 04 pm](https://user-images.githubusercontent.com/28145373/49967938-46502b80-fef2-11e8-81e4-1ac617ad5f5e.png)

![screen shot 2018-12-13 at 4 13 03 pm](https://user-images.githubusercontent.com/28145373/49967955-4d773980-fef2-11e8-8100-780bc5a2d4df.png)
