### ISSUE TITLE
Reload button is a little chopped off on the curve

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#244]
## Description 
Reload button is a little chopped off on the curve

 ## Actual result:

![image](https://user-images.githubusercontent.com/17010094/40692114-d9c3bf00-637d-11e8-9afb-a001f6784454.png)

## Expected result:
Should not be chopped off. Should look like as mentioned in https://github.com/brave/browser-laptop/issues/13981
![image](https://user-images.githubusercontent.com/17010094/40692315-0991ff8e-637f-11e8-882e-4996a67f354d.png)

## Reproduces how often: 

Easy. Visually easily noticeable 

## Brave version (about:brave info)

 5212284

**Comment by srirambv** [comment]
Closing the issue for now. Looks correct on Windows. Will have to check once Brave UI is implemented.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7
