### ISSUE TITLE
Fix eth request handling

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#24403]
See https://github.com/brave/internal/issues/888 and https://github.com/brave/internal/issues/892 for test plans.

**Comment by srirambv** [comment]
Verification notes can be found here https://github.com/brave/internal/issues/888#issuecomment-1208170860 & https://github.com/brave/internal/issues/892#issuecomment-1208365671

**Comment by srirambv** [comment]
Verification notes for Android can be found here https://github.com/brave/internal/issues/892#issuecomment-1216899275 & https://github.com/brave/internal/issues/888#issuecomment-1216903668
