### ISSUE TITLE
b-c installer crash during migration when b-l is installed without elevated permissions

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#2441]
## Steps to Reproduce

1. Create a new admin user (also worth checking for normal user)
2. Login to the created user account
3. Install BraveBetaSetup-x64 0.23.204.exe, when asked for permissions click `No`
4. Check for update
5. When update ready click `Update`, when asked for permissions click `No`

## Actual result:

b-c installer crash
![upgrade_fail_1](https://user-images.githubusercontent.com/34715963/49782563-0c76fd80-fd17-11e8-9e0f-7ce6d8a2bf2a.png)
b-l is launched after b-c installer crash
![upgrade_fail_2](https://user-images.githubusercontent.com/34715963/49782565-11d44800-fd17-11e8-82e9-d0584242759f.png)

Log
```
2018-12-11T04:51:12.959Z - Creating "Brave (old)" shortcut on desktop
2018-12-11T04:51:13.701Z - Attempting silent install using "C:\Users\Test\AppData\Local\BraveBeta\app-0.25.217\resources\BraveBrowserSetup64.exe"
2018-12-11T04:53:05.619Z - Error thrown when installing brave-core: Error: Command failed: C:\Users\Test\AppData\Local\BraveBeta\app-0.25.217\resources\BraveBrowserSetup64.exe /silent /install
```

## Expected result:
No crash

## Reproduces how often: 

always
Reproduced 4 times in a row.

## Brave version (brave://version info)

Windows 7 x64
b-l 0.25.217
b-c 0.57.18

cc @bsclifton @kjozwiak @LaurenWags @srirambv @GeetaSarvadnya

**Comment by btlechowski** [comment]
Found when investigating https://community.brave.com/t/error-on-yesterdays-update/39287/ The issues could be related.

**Comment by bsclifton** [comment]
Recapping: 
- Install Muon; when Muon brings up UAC prompt, user clicks no
- Update happens
- Update doesn't work

Talking with @rebron @Brave-Matt @kjozwiak:
- users shouldn't be installing Muon Brave anymore
- we can address upgrade not working with article for how to install / import (already in progress)
    - Download Brave from https://brave.com/download
    - Run; go to chrome://settings/importData
    - Run importer
