### ISSUE TITLE
Wallet prototype pollution attack

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#24415]
placeholder for https://github.com/brave/security/issues/940

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.45.88 Chromium: 106.0.5249.91 (Official Build) beta (64-bit) 
-- | --
Revision | `fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}`
OS | Linux

- Verified steps from [brave/brave-core#14460](https://github.com/brave/brave-core/pull/14460)
- Verified results are as expected

https://user-images.githubusercontent.com/17010094/194576425-5c9994d2-c51c-4932-9f65-be7b8602a238.mp4

------------------------
Verification passed on

Brave | 1.45.88 Chromium: 106.0.5249.91 (Official Build) beta (64-bit) 
-- | --
Revision | `fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}`
OS | Windows 11 Version 21H2 (Build 22000.978)

- Verified steps from [brave/brave-core#14460](https://github.com/brave/brave-core/pull/14460)
- Verified results are as expected

https://user-images.githubusercontent.com/17010094/194579820-041726a3-1858-4677-9f8d-0c36aca2c0e4.mp4


------------------------
Verification passed on

Brave | 1.45.88 Chromium: 106.0.5249.91 (Official Build) beta (arm64)
-- | --
Revision | `fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [brave/brave-core#14460](https://github.com/brave/brave-core/pull/14460)
- Verified results are as expected

https://user-images.githubusercontent.com/17010094/194580277-0f5815f7-135a-4533-9c7a-d4d2ee47bc15.mov
