### ISSUE TITLE
Solana: Pending request for Devnet is not shown and show pending requests for default networks

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#24410]
## Description 

- [x] Show Solana pending request first time
- [x] Show pending requests for default networks in dapps panel until 24384 issue is done to fetch the corresponding network

https://user-images.githubusercontent.com/11755381/182600972-9895b3a9-83b2-4b1e-9131-4f4a2ad5ec8e.mp4

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.44.79 x64 Beta build
- Verified steps from [brave/brave-core#14497](https://github.com/brave/brave-core/pull/14497)
- Verified pending request is show for Solana account transactions via the bell icon in portfolio
- Verified able to submit the transaction from pending requests
