### ISSUE TITLE
Add Brave Ads transaction ID when redeeming tokens

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#24416]

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.44.75 Chromium: 105.0.5195.102 (Official Build) beta (64-bit)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/14461

Verified `transactionId` is included in `POST /v2/confirmation/{confirmation_id}/{credential}`
![image](https://user-images.githubusercontent.com/34715963/189177947-ceaafde4-34b2-498f-ad37-b0b8ec7fdd96.png)

Verified `transactionId` is unique for each confirmation
![image](https://user-images.githubusercontent.com/34715963/189178397-7c81dcbf-2186-4acd-9d50-27256f2f656b.png)
