### ISSUE TITLE
Manual test run on Windows x64 & x86 for Tor 1.0.27

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#24433]
### Tor Client Updater

- [x] For development go-update-server. Run brave-browser with `--user-data-dir=component-dev --use-dev-goupdater-url` (These flags are only available in v1.7.x). Once the crx is pushed to production run without these flags.
- [x] Open `New Private Window with Tor` and confirm that it starts without any errors.
	- [x] Navigate to `http://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/` to check if the site loads successfully.
- [x] Navigate to `brave://components` and verify `Tor Client Updater (OS)` is updated successfully to dev component version `1.0.50`

### Windows
- [x] Setup Windows SDK by downloading - https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk/
- [x] Run `"C:\Program Files (x86)\Windows Kits\10\bin\x86\signtool.exe" verify /pa "C:\Users\<user>\AppData\Local\BraveSoftware\Brave-Browser-<channel>\User Data\cpoalefficncklhjfpglfiplenlpccdb\<version>\tor-<version-tor>-win-brave-<version-brave>.exe"` to verify if the signature of the binary is correct.

### Tor Client Updater

- [x] For development go-update-server. Run brave-browser with `--user-data-dir=component-dev --use-dev-goupdater-url` (These flags are only available in v1.7.x). Once the crx is pushed to production run without these flags.
- [x] Open `New Private Window with Tor` and confirm that it starts without any errors.
	- [x] Navigate to `http://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/` to check if the site loads successfully.
- [x] Navigate to `brave://components` and verify `Tor Client Updater (OS)` is updated successfully to dev component version `1.0.50`

### Windows
- [x] Setup Windows SDK by downloading - https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk/
- [x] Run `"C:\Program Files (x86)\Windows Kits\10\bin\x86\signtool.exe" verify /pa "C:\Users\<user>\AppData\Local\BraveSoftware\Brave-Browser-<channel>\User Data\cpoalefficncklhjfpglfiplenlpccdb\<version>\tor-<version-tor>-win-brave-<version-brave>.exe"` to verify if the signature of the binary is correct.

### Tor Client Updater

- [x] For development go-update-server. Run brave-browser with `--user-data-dir=component-dev --use-dev-goupdater-url` (These flags are only available in v1.7.x). Once the crx is pushed to production run without these flags.
- [x] Open `New Private Window with Tor` and confirm that it starts without any errors.
	- [ ] Navigate to `http://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/` to check if the site loads successfully.
- [ ] Navigate to `brave://components` and verify `Tor Client Updater (OS)` is updated successfully to dev component version `1.0.50`

### Windows
- [ ] Setup Windows SDK by downloading - https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk/
- [ ] Run `"C:\Program Files (x86)\Windows Kits\10\bin\x86\signtool.exe" verify /pa "C:\Users\<user>\AppData\Local\BraveSoftware\Brave-Browser-<channel>\User Data\cpoalefficncklhjfpglfiplenlpccdb\<version>\tor-<version-tor>-win-brave-<version-brave>.exe"` to verify if the signature of the binary is correct.

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```
Brave | 1.42.86 Chromium: 104.0.5112.81 (Official Build) (64-bit)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | Windows 10 Version 21H2 (Build 19044.1826)

```
Launched `1.42.86 Chromium: 104.0.5112.81` using `--use-dev-goupdater-url` and confirmed the following versions:

* `tor` binary `0.4.7.8`
* `OpenSSL` `1.1.1q`
* `Brave Tor Client Updater (Windows)` `1.0.50`

![image](https://user-images.githubusercontent.com/38657976/182865442-3a583e89-7a9c-4584-9998-7f942f706282.png)


Ensured that you can open the following domains in a Tor window without issues:

* brave.com
* duckduckgo.com
* https://duckduckgogg42xjoc72x3sjasowoarfbgcmvfimaftt6twagswzczad.onion
* check.torproject.org (ensured that hard refreshing gets a new circut/IP)

Confirmed the following sites opened via "Open in Tor" button and navigated to .onion URL:

* brave.com --> https://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion
* mail.protonmail.com --> https://protonmailrmez3lotccipshtkleegetolb73fuirgj7r4o4vfu7ozyd.onion

Ensured that the tor binary was correctly signed using `signtool.exe`:

```
```

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 

Brave | 1.42.86 Chromium: 104.0.5112.81 (Official Build) (64-bit)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | Windows 11 Version 21H2 (Build 22000.795)

Launched `1.42.86 Chromium: 104.0.5112.81` using  `--use-dev-goupdater-url` and confirmed the following versions:

`tor` binary `0.4.7.8`
`OpenSSL` `1.1.1q`
`Brave Tor Client Updater (Windows) 1.0.50`

![image](https://user-images.githubusercontent.com/98358127/182890261-f7356d15-73e5-4c4c-a8c3-12e86f5d1e65.png)

```
Aug 04 08:44:38.087 [notice] Tor 0.4.7.8 running on Windows 8 [or later] with Libevent 2.1.12-stable, OpenSSL 1.1.1q, Zlib 1.2.12, Liblzma N/A, Libzstd N/A and Unknown N/A as libc.
Aug 04 08:44:38.087 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://support.torproject.org/faq/staying-anonymous/
Aug 04 08:44:38.095 [notice] Read configuration file "C:\Users\mseel\AppData\Local\BraveSoftware\Brave-Browser\User Data\cpoalefficncklhjfpglfiplenlpccdb\1.0.50\tor-torrc".
Aug 04 08:44:38.095 [notice] Read configuration file "C:\Users\mseel\AppData\Local\BraveSoftware\Brave-Browser\User Data\cpoalefficncklhjfpglfiplenlpccdb\1.0.50\tor-torrc".
Aug 04 08:44:38.096 [warn] Path for GeoIPFile (<default>) is relative and will resolve to C:\Program Files\BraveSoftware\Brave-Browser\Application\104.1.42.86\<default>. Is this what you wanted?
Aug 04 08:44:38.096 [warn] Path for GeoIPv6File (<default>) is relative and will resolve to C:\Program Files\BraveSoftware\Brave-Browser\Application\104.1.42.86\<default>. Is this what you wanted?
Aug 04 08:44:38.098 [notice] Opening Socks listener on 127.0.0.1:0
Aug 04 08:44:38.098 [notice] Socks listener listening on port 56784.
Aug 04 08:44:38.098 [notice] Opened Socks listener connection (ready) on 127.0.0.1:56784
Aug 04 08:44:38.099 [notice] Opening Control listener on 127.0.0.1:0
Aug 04 08:44:38.099 [notice] Control listener listening on port 56785.
Aug 04 08:44:38.099 [notice] Opened Control listener connection (ready) on 127.0.0.1:56785
[8980:9984:0804/084438.100:INFO:tor_file_watcher.cc(183)] tor: failed to open control auth cookie
[8980:9984:0804/084438.100:INFO:tor_file_watcher.cc(183)] tor: failed to open control auth cookie
[8980:9984:0804/084438.101:INFO:tor_file_watcher.cc(183)] tor: failed to open control auth cookie
[8980:9984:0804/084438.102:INFO:tor_file_watcher.cc(183)] tor: failed to open control auth cookie
Aug 04 08:44:38.000 [notice] Bootstrapped 0% (starting): Starting
Aug 04 08:44:38.000 [notice] Starting with guard context "default"
Aug 04 08:44:38.000 [notice] New control connection opened from 127.0.0.1.
Aug 04 08:44:38.000 [warn] Path for GeoIPFile (<default>) is relative and will resolve to C:\Program Files\BraveSoftware\Brave-Browser\Application\104.1.42.86\<default>. Is this what you wanted?
Aug 04 08:44:38.000 [warn] Path for GeoIPv6File (<default>) is relative and will resolve to C:\Program Files\BraveSoftware\Brave-Browser\Application\104.1.42.86\<default>. Is this what you wanted?
Aug 04 08:44:38.000 [notice] Bootstrapped 5% (conn): Connecting to a relay
Aug 04 08:44:38.000 [notice] Bootstrapped 10% (conn_done): Connected to a relay
Aug 04 08:44:38.000 [notice] Bootstrapped 14% (handshake): Handshaking with a relay
Aug 04 08:44:38.000 [notice] Bootstrapped 15% (handshake_done): Handshake with a relay done
Aug 04 08:44:38.000 [notice] Bootstrapped 20% (onehop_create): Establishing an encrypted directory connection
Aug 04 08:44:39.000 [notice] Bootstrapped 25% (requesting_status): Asking for networkstatus consensus
Aug 04 08:44:39.000 [notice] Bootstrapped 30% (loading_status): Loading networkstatus consensus
Aug 04 08:44:40.000 [notice] I learned some more directory information, but not enough to build a circuit: We have no usable consensus.
Aug 04 08:44:40.000 [notice] Bootstrapped 40% (loading_keys): Loading authority key certs
Aug 04 08:44:40.000 [notice] The current consensus has no exit nodes. Tor can only build internal paths, such as paths to onion services.
Aug 04 08:44:40.000 [notice] Bootstrapped 45% (requesting_descriptors): Asking for relay descriptors
Aug 04 08:44:40.000 [notice] I learned some more directory information, but not enough to build a circuit: We need more microdescriptors: we have 0/6740, and can only build 0% of likely paths. (We have 0% of guards bw, 0% of midpoint bw, and 0% of end bw (no exits in consensus, using mid) = 0% of path bw.)
Aug 04 08:44:41.000 [notice] Bootstrapped 50% (loading_descriptors): Loading relay descriptors
Aug 04 08:44:41.000 [notice] The current consensus contains exit nodes. Tor can build exit and internal paths.
Aug 04 08:44:43.000 [notice] Bootstrapped 56% (loading_descriptors): Loading relay descriptors
Aug 04 08:45:09.000 [notice] Bootstrapped 63% (loading_descriptors): Loading relay descriptors
Aug 04 08:45:09.000 [notice] Bootstrapped 68% (loading_descriptors): Loading relay descriptors
Aug 04 08:45:09.000 [notice] Bootstrapped 75% (enough_dirinfo): Loaded enough directory info to build circuits
Aug 04 08:45:10.000 [notice] Bootstrapped 80% (ap_conn): Connecting to a relay to build circuits
Aug 04 08:45:10.000 [notice] Bootstrapped 85% (ap_conn_done): Connected to a relay to build circuits
Aug 04 08:45:10.000 [notice] Bootstrapped 89% (ap_handshake): Finishing handshake with a relay to build circuits
Aug 04 08:45:10.000 [notice] Bootstrapped 90% (ap_handshake_done): Handshake finished with a relay to build circuits
Aug 04 08:45:10.000 [notice] Bootstrapped 95% (circuit_create): Establishing a Tor circuit
Aug 04 08:45:11.000 [notice] Bootstrapped 100% (done): Done
```

Ensured that you can open the following domains in a Tor window without issues:

* brave.com
* duckduckgo.com
* https://duckduckgogg42xjoc72x3sjasowoarfbgcmvfimaftt6twagswzczad.onion
* check.torproject.org (ensured that hard refreshing gets a new circut/IP)

Confirmed the following sites opened via "Open in Tor" button and navigated to .onion URL:

* brave.com --> https://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion
* mail.protonmail.com --> https://protonmailrmez3lotccipshtkleegetolb73fuirgj7r4o4vfu7ozyd.onion

Ensured that the tor binary was correctly signed using `signtool.exe`:

```
C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64>BraveSign.exe verify /pa "C:\Users\mseel\AppData\Local\BraveSoftware\Brave-Browser\User Data\cpoalefficncklhjfpglfiplenlpccdb\1.0.50\tor-0.4.7.8-win32-brave-1"
File: C:\Users\mseel\AppData\Local\BraveSoftware\Brave-Browser\User Data\cpoalefficncklhjfpglfiplenlpccdb\1.0.50\tor-0.4.7.8-win32-brave-1
Index  Algorithm  Timestamp
========================================
0      sha256     Authenticode

Successfully verified: C:\Users\mseel\AppData\Local\BraveSoftware\Brave-Browser\User Data\cpoalefficncklhjfpglfiplenlpccdb\1.0.50\tor-0.4.7.8-win32-brave-1

C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64>
````

**Comment by LaurenWags** [comment]
Verified using

```
Brave	1.42.86 Chromium: 104.0.5112.81 (Official Build) (32-bit) 
Revision	5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS	Windows 10 Version 21H2 (Build 19044.1826)
```

Confirmed that the correct Tor component was being downloaded via --use-dev-goupdater-url:

<img width="313" alt="win" src="https://user-images.githubusercontent.com/28145373/182916168-3d78a8d7-677a-498e-b9ca-8b9905d63101.png">

Confirmed that the Tor component was started when launching Tor and ensured Tor 0.4.7.8 was being used.

```
Aug 04 13:41:12.747 [notice] Tor 0.4.7.8 running on Windows 8 [or later] with Libevent 2.1.12-stable, OpenSSL 1.1.1q, Zlib 1.2.12, Liblzma N/A, Libzstd N/A and Unknown N/A as libc.
```

Confirmed that you can open the following domains in a Tor window without issues:

* http://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/

Ensured that the tor binary was correctly signed using BraveSign.exe

```
C:\Program Files\Windows Kits\10\bin\10.0.18362.0\x86>BraveSign.exe verify /pa "C:\Users\Lauren Wagner\AppData\Local\BraveSoftware\Brave-Browser\User Data\cpoalefficncklhjfpglfiplenlpccdb\1.0.50\tor-0.4.7.8-win32-brave-1"
File: C:\Users\Lauren Wagner\AppData\Local\BraveSoftware\Brave-Browser\User Data\cpoalefficncklhjfpglfiplenlpccdb\1.0.50\tor-0.4.7.8-win32-brave-1
Index  Algorithm  Timestamp
========================================
0      sha256     Authenticode

Successfully verified: C:\Users\Lauren Wagner\AppData\Local\BraveSoftware\Brave-Browser\User Data\cpoalefficncklhjfpglfiplenlpccdb\1.0.50\tor-0.4.7.8-win32-brave-1
```
