### ISSUE TITLE
Manual test run on Linux for Tor 1.0.27

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#24434]
## Tor Client Updater

- [x] For development go-update-server. Run brave-browser with `--user-data-dir=component-dev --use-dev-goupdater-url` (These flags are only available in v1.7.x). Once the crx is pushed to production run without these flags.
- [x] Open `New Private Window with Tor` and confirm that it starts without any errors.
	- [x] Navigate to `http://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/` to check if the site loads successfully.
- [x] Navigate to `brave://components` and verify `Tor Client Updater (OS)` is updated successfully to dev component version `1.0.50`

### Linux
- [x] Navigate to `<user-data-dir>/biahpgbdmdkfgndcmfiipgcebobojjkp`
- [x] Run `ldd tor-<version-tor>-linux-brave-<version-brave>` to confirm tor client is a static binary

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.42.86 Chromium: 104.0.5112.81 (Official Build) (64-bit)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | Ubuntu 18.04 LTS

Tor works
```
Aug 04 17:41:15.296 [notice] Tor 0.4.7.8 running on Linux with Libevent 2.1.12-stable, OpenSSL 1.1.1q, Zlib 1.2.12, Liblzma N/A, Libzstd N/A and Glibc 2.35 as libc.

```

Onion page opened:
![image](https://user-images.githubusercontent.com/34715963/182889757-86a17d7f-9990-4052-ae0f-aa5d8ed4d256.png)

brave://components
![image](https://user-images.githubusercontent.com/34715963/182892519-54283eba-a686-4125-bc7d-62d706c697f9.png)

Not dynamic library:
![image](https://user-images.githubusercontent.com/34715963/182893775-c69f264b-4e39-470e-97ce-7dfaf5e67b70.png)
