### ISSUE TITLE
Manual test run on macOS (Intel) for Tor 1.0.27

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#24435]
### Tor Client Updater

- [x] For development go-update-server. Run brave-browser with `--user-data-dir=component-dev --use-dev-goupdater-url` (These flags are only available in v1.7.x). Once the crx is pushed to production run without these flags.
- [x] Open `New Private Window with Tor` and confirm that it starts without any errors.
	- [x] Navigate to `http://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/` to check if the site loads successfully.
- [x] Navigate to `brave://components` and verify `Tor Client Updater (OS)` is updated successfully to dev component version `1.0.50`

### macOS
- [x] Navigate to `/Users/<user>/Library/Application Support/BraveSoftware/Brave-Browser-<channel>/cldoidikboihgcjfkhdeidbpclkineef/<version>`
- [x] Run `codesign -vvvv tor-<version-tor>-darwin-brave-<version-brave>` to confirm codesign is valid
- [x] For MacOS Catalina (10.15+) - Run `spctl -a -vv -t install tor-<version-tor>-darwin-brave-<version-brave>` to verify that the binary is notarized.

### Tor Client Updater

- [x] For development go-update-server. Run brave-browser with `--user-data-dir=component-dev --use-dev-goupdater-url` (These flags are only available in v1.7.x). Once the crx is pushed to production run without these flags.
- [x] Open `New Private Window with Tor` and confirm that it starts without any errors.
	- [x] Navigate to `http://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/` to check if the site loads successfully.
- [x] Navigate to `brave://components` and verify `Tor Client Updater (OS)` is updated successfully to dev component version `1.0.50`

### macOS
- [x] Navigate to `/Users/<user>/Library/Application Support/BraveSoftware/Brave-Browser-<channel>/cldoidikboihgcjfkhdeidbpclkineef/<version>`
- [x] Run `codesign -vvvv tor-<version-tor>-darwin-brave-<version-brave>` to confirm codesign is valid
- [x] For MacOS Catalina (10.15+) - Run `spctl -a -vv -t install tor-<version-tor>-darwin-brave-<version-brave>` to verify that the binary is notarized.

### Tor Client Updater

- [x] For development go-update-server. Run brave-browser with `--user-data-dir=component-dev --use-dev-goupdater-url` (These flags are only available in v1.7.x). Once the crx is pushed to production run without these flags.
- [x] Open `New Private Window with Tor` and confirm that it starts without any errors.
	- [x] Navigate to `http://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/` to check if the site loads successfully.
- [x] Navigate to `brave://components` and verify `Tor Client Updater (OS)` is updated successfully to dev component version `1.0.50`

### macOS
- [x] Navigate to `/Users/<user>/Library/Application Support/BraveSoftware/Brave-Browser-<channel>/cldoidikboihgcjfkhdeidbpclkineef/<version>`
- [x] Run `codesign -vvvv tor-<version-tor>-darwin-brave-<version-brave>` to confirm codesign is valid
- [x] For MacOS Catalina (10.15+) - Run `spctl -a -vv -t install tor-<version-tor>-darwin-brave-<version-brave>` to verify that the binary is notarized.

### Tor Client Updater

- [x] For development go-update-server. Run brave-browser with `--user-data-dir=component-dev --use-dev-goupdater-url` (These flags are only available in v1.7.x). Once the crx is pushed to production run without these flags.
- [x] Open `New Private Window with Tor` and confirm that it starts without any errors.
	- [x] Navigate to `http://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/` to check if the site loads successfully.
- [x] Navigate to `brave://components` and verify `Tor Client Updater (OS)` is updated successfully to dev component version `1.0.50`

### macOS
- [x] Navigate to `/Users/<user>/Library/Application Support/BraveSoftware/Brave-Browser-<channel>/cldoidikboihgcjfkhdeidbpclkineef/<version>`
- [x] Run `codesign -vvvv tor-<version-tor>-darwin-brave-<version-brave>` to confirm codesign is valid

### Tor Client Updater

- [x] For development go-update-server. Run brave-browser with `--user-data-dir=component-dev --use-dev-goupdater-url` (These flags are only available in v1.7.x). Once the crx is pushed to production run without these flags.
- [x] Open `New Private Window with Tor` and confirm that it starts without any errors.
	- [x] Navigate to `http://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/` to check if the site loads successfully.
- [x] Navigate to `brave://components` and verify `Tor Client Updater (OS)` is updated successfully to dev component version `1.0.50`

### macOS
- [x] Navigate to `/Users/<user>/Library/Application Support/BraveSoftware/Brave-Browser-<channel>/cldoidikboihgcjfkhdeidbpclkineef/<version>`
- [x] Run `codesign -vvvv tor-<version-tor>-darwin-brave-<version-brave>` to confirm codesign is valid

**Comment by LaurenWags** [comment]
Verification in progress for the following:

<details>
<summary>macOS 10.13.x High Sierra x64</summary>

```

```

Confirmed that the correct Tor component was being downloaded via --use-dev-goupdater-url:



Confirmed that the Tor component was started when launching Tor and ensured Tor 0.4.7.8 was being used.

```

```

Confirmed that you can open the following domains in a Tor window without issues:

* http://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/

Confirmed that codesign is valid:

```

```

</details>

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` for the following:

(arm64/M1) macOS 11.6.8 Big Sur - PENDING
(x86) macOS 13.0 Ventura - PENDING
(x86) macOS 11.6.8 Big Sur - PENDING
