### ISSUE TITLE
Support ENS wildcard resolution

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#24430]
To complete support of ENS L2 https://github.com/brave/brave-browser/issues/22930 we also need support of wildcard resolution for ENS https://docs.ens.domains/ens-improvement-proposals/ensip-10-wildcard-resolution

**Comment by srirambv** [comment]
Discussed with @supermassive [here](https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1666268670700859) and removing `OS/Android` label from this as the implementation needs to be done Android.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (64-bit)
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | Linux

- Verified as Send To address resolution as part of [#24990 (comment)](https://github.com/brave/brave-browser/issues/24990#issuecomment-1296701139)
- Verified entering `offchainexample.eth` in omnibox shows IPFS interstitial page
- Verified able to load the page either via local address resolution or via public dns resolution

https://user-images.githubusercontent.com/17010094/198957612-b7e8a9ef-4857-4c21-a3f6-f06818024256.mp4


----------------
Verification passed on 

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (64-bit)
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | Windows 11 Version 22H2 (Build 22621.674)

- Verified as Send To address resolution as part of [#24990 (comment)](https://github.com/brave/brave-browser/issues/24990#issuecomment-1296701139)
- Verified entering `offchainexample.eth` in omnibox shows IPFS interstitial page
- Verified able to load the page either via local address resolution or via public dns resolution

https://user-images.githubusercontent.com/17010094/198956616-43d09db0-0855-4580-b427-05560c79ad30.mp4


----------------
Verification passed on 

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (arm64)
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | macOS Version 12.6 (Build 21G115)

- Verified as Send To address resolution as part of [#24990 (comment)](https://github.com/brave/brave-browser/issues/24990#issuecomment-1296701139)
- Verified entering `offchainexample.eth` in omnibox shows IPFS interstitial page
- Verified able to load the page either via local address resolution or via public dns resolution

https://user-images.githubusercontent.com/17010094/198955614-94b25dc3-8295-42a4-8574-ef920a511933.mov
