### ISSUE TITLE
Manual test run on macOS (arm64) for Tor 1.0.27

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#24436]
### Tor Client Updater

- [x] For development go-update-server. Run brave-browser with `--user-data-dir=component-dev --use-dev-goupdater-url` (These flags are only available in v1.7.x). Once the crx is pushed to production run without these flags.
- [x] Open `New Private Window with Tor` and confirm that it starts without any errors.
	- [x] Navigate to `http://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/` to check if the site loads successfully.
- [x] Navigate to `brave://components` and verify `Tor Client Updater (OS)` is updated successfully to dev component version `1.0.50`

### macOS
- [x] Navigate to `/Users/<user>/Library/Application Support/BraveSoftware/Brave-Browser-<channel>/cldoidikboihgcjfkhdeidbpclkineef/<version>`
- [x] Run `codesign -vvvv tor-<version-tor>-darwin-brave-<version-brave>` to confirm codesign is valid
- [x] For MacOS Catalina (10.15+) - Run `spctl -a -vv -t install tor-<version-tor>-darwin-brave-<version-brave>` to verify that the binary is notarized.

### Tor Client Updater

- [x] For development go-update-server. Run brave-browser with `--user-data-dir=component-dev --use-dev-goupdater-url` (These flags are only available in v1.7.x). Once the crx is pushed to production run without these flags.
- [x] Open `New Private Window with Tor` and confirm that it starts without any errors.
	- [x] Navigate to `http://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/` to check if the site loads successfully.
- [x] Navigate to `brave://components` and verify `Tor Client Updater (OS)` is updated successfully to dev component version `1.0.50`

### macOS
- [x] Navigate to `/Users/<user>/Library/Application Support/BraveSoftware/Brave-Browser-<channel>/cldoidikboihgcjfkhdeidbpclkineef/<version>`
- [x] Run `codesign -vvvv tor-<version-tor>-darwin-brave-<version-brave>` to confirm codesign is valid
- [x] For MacOS Catalina (10.15+) - Run `spctl -a -vv -t install tor-<version-tor>-darwin-brave-<version-brave>` to verify that the binary is notarized.

**Comment by LaurenWags** [comment]
Verified on macOS 12.5 arm64 using the following build:

```
Brave	1.42.86 Chromium: 104.0.5112.81 (Official Build) (arm64) 
Revision	5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS	macOS Version 12.5 (Build 21G72)
```

Confirmed that the correct Tor component was being downloaded via --use-dev-goupdater-url:

<img width="331" alt="M1" src="https://user-images.githubusercontent.com/28145373/182863010-325b99b3-8174-4aa6-ba27-02758e2ce954.png">

Confirmed that the Tor component was started when launching Tor and ensured Tor 0.4.7.8 was being used.

```
Aug 04 09:34:59.574 [notice] Tor 0.4.7.8 running on Darwin with Libevent 2.1.12-stable, OpenSSL 1.1.1q, Zlib 1.2.12, Liblzma N/A, Libzstd N/A and Unknown N/A as libc.
```

Confirmed that you can open the following domains in a Tor window without issues:

* http://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/

Confirmed that codesign is valid:

```
laurenwags@Laurens-M1 1.0.50 % codesign -vvvv tor-0.4.7.8-darwin-brave-1 
tor-0.4.7.8-darwin-brave-1: valid on disk
tor-0.4.7.8-darwin-brave-1: satisfies its Designated Requirement
```

Confirmed that the binary is notarized:

```
laurenwags@Laurens-M1 1.0.50 % spctl -a -vv -t install tor-0.4.7.8-darwin-brave-1 
tor-0.4.7.8-darwin-brave-1: accepted
source=Notarized Developer ID
origin=Developer ID Application: Brave Software, Inc. (KL8N8XSYF4)
```

**Comment by stephendonner** [comment]
(arm64/M1) macOS 11.6.8 Big Sur - `PASSED`
<details>

```


Brave | 1.42.86 Chromium: 104.0.5112.81 (Official Build) (arm64)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | macOS Version 11.6.8 (Build 20G730)


```

Confirmed that the correct Tor component was being downloaded via --use-dev-goupdater-url:

<img width="303" alt="Screenshot 2022-08-04 at 12 10 05 PM" src="https://user-images.githubusercontent.com/387249/182933791-c7bddf88-c550-4d60-9017-05d4d51ed5b2.png">


Confirmed that the Tor component was started when launching Tor and ensured Tor `0.4.7.8` was being used.

```
Aug 04 11:45:41.060 [notice] Tor 0.4.7.8 running on Darwin with Libevent 2.1.12-stable, OpenSSL 1.1.1q, Zlib 1.2.12, Liblzma N/A, Libzstd N/A and Unknown N/A as libc.
```

Confirmed that you can open the following domains in a Tor window without issues:

* http://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/
* https://account.protonmailrmez3lotccipshtkleegetolb73fuirgj7r4o4vfu7ozyd.onion/

Confirmed that codesign is valid:

```
stephendonner@Stephens-MBP-3 1.0.50 % codesign -vvvv tor-0.4.7.8-darwin-brave-1
tor-0.4.7.8-darwin-brave-1: valid on disk
tor-0.4.7.8-darwin-brave-1: satisfies its Designated Requirement
```


</details>
