### ISSUE TITLE
Wyre not provided chain identifier in GetBuyUrl

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#24444]
## Description 

In the Blockchain Registry service, we don't seem to be providing Wyre with the chain identifier for the network the user wishes to purchase from. `USDC` is available as a buy asset for Ethereum Mainnet, Polygon and Avalanche networks and it's unclear which network the tokens would be purchased from on Wyre.

## Steps to Reproduce

   1. Open buy panel and select Ethereum Mainnet
   2. Select `USDC` as the buy token
   3. Tap 'Select purchase method' and select Wyre
   4. Keep the tab open, and open the buy panel again but switch to Polygon or Avalanche network
   5. Select `USDC` as the buy token
   6. Tap 'Select purchase method' and select Wyre
   7. Observe no chain id provided as a query parameter in either URL on `https://pay.sendwyre.com/`

## Actual result:

Unclear which network the tokens would be purchased from.

## Expected result:

Tokens are purchased on the network selected in the buy panel

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

The `GetBuyUrl` function does not add the `chain_id` (or any other way to identify the network) to the Wyre url:
https://github.com/brave/brave-core/blob/master/components/brave_wallet/browser/blockchain_registry.cc#L150

**Comment by HEagle18** [comment]
closing because we no longer use Wyre
