### ISSUE TITLE
Add Bridge to Aurora button on asset detail screen

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#24446]
Android version of https://github.com/brave/brave-browser/issues/24377

Add "Bridge to Aurora" button on all supported assets (this screen shows all supported assets including both highlighted and not highlighted)

![Image](https://user-images.githubusercontent.com/318119/182908142-5d532fb6-c791-4673-a594-9fb2b8c19901.png)

## Example placement

![Image](https://user-images.githubusercontent.com/318119/182908671-28f727b0-00cc-46f4-a939-c3717fe1949e.png)

## First time tapping on bridge button

![Image](https://user-images.githubusercontent.com/318119/182950994-4686f461-3ec9-4399-982d-3f4a8b667669.png)

(Lets show a system dialog that informs the user of the risks, the learn more button should be a system button and not a link in the message body. Three buttons [Continue, Cancel, Learn more], learn more link https://ethereum.org/en/bridges/#bridge-risk)

**Comment by kjozwiak** [comment]
The above will require `1.44.72` or higher for `1.42.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.44.75 x64 build
- Verified `Bridge to Aurora` button is shown for supported tokens on Ethereum Mainnet
- Verified `Bridge to Aurora` button is not shown for other EVM networks/Testnet
- Verified popup modal is shown for all tokens every time it is clicked
- Verified the popup modal doesn't show again when `Do not show this again` message is checked
- Verified the links open correct info page
- Verified `Bridge to Aurora` button opens a new tab and loads the Rainbow app
- Encountered 
   * https://github.com/brave/brave-browser/issues/25131
   * https://github.com/brave/brave-browser/issues/25132

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/188583992-436477c5-fa4e-4a79-b77a-fbb8770d1f79.mp4> | <video src=https://user-images.githubusercontent.com/17010094/188584093-284a3759-511c-49fc-8d08-826de219d0a9.mp4>

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.43.92 x64 build
- Verified `Bridge to Aurora` button is shown for supported tokens on Ethereum Mainnet
- Verified `Bridge to Aurora` button is not shown for other EVM networks/Testnet
- Verified popup modal is shown for all tokens every time it is clicked
- Verified the popup modal doesn't show again when `Do not show this again` message is checked
- Verified the links open correct info page
- Verified `Bridge to Aurora` button opens a new tab and loads the Rainbow app
- Encountered 
   * https://github.com/brave/brave-browser/issues/25131
   * https://github.com/brave/brave-browser/issues/25132
   * https://github.com/brave/brave-browser/issues/25224

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/189675018-675b87fd-dfdb-4b28-982d-6d328247b966.mp4> | <video src=https://user-images.githubusercontent.com/17010094/189674949-018dcb1d-bc8d-4271-a13b-2f4e36ff4370.mp4>
