### ISSUE TITLE
Incorrect Formatting on Trackers & Ads Blocked

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#24450]
## Description 

The number shown for *Trackers & Ads Blocked* on the New Tab Page lacks commas.

## Steps to Reproduce

1. Use Brave a lot 🙂
2. Visit the New Tab Page

## Actual result:

A number like 6011204 is displayed without commas.

## Expected result:

A number like 6011204 is displayed according to the user's locale. For example, en-US users should see 6,011,204.

## Reproduces how often: 

Always.

## Brave version (brave://version info)

1.42.86

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

**Comment by jonathansampson** [comment]
Looks like the difference between numbers and strings; perhaps we recently switched types:

![image](https://user-images.githubusercontent.com/815158/182942241-c287208d-f60d-45cc-9c6e-83f9fd73f5ef.png)

**Comment by jonathansampson** [comment]
Looks like this is where the behavior changed: https://github.com/brave/brave-core/commit/531526b64ce60a611a9ecea9dc07a644c104bedb.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.44.73 Chromium: 105.0.5195.68 (Official Build) beta (x86_64)
-- | --
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | macOS Version 13.0 (Build 22A5331f)

### Steps:
1. installed `1.44.73`
2. launched Brave
3. visited some sites, to get a profile and populate data
4. shut down Brave
5. found a way to set `ads_blocked` to `1000000000`
6. opened a new-tab page

#### Confirmed I saw `1,000,000,976 Trackers & ads blocked`

<img width="1312" alt="Screenshot 2022-09-06 at 6 05 54 PM" src="https://user-images.githubusercontent.com/387249/188768190-84a6c618-4d48-459c-a0c5-93b62c2f19a7.png">
