### ISSUE TITLE
Chrome's TLS pinned are enforced in Brave

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#24454]
Chrome's list of pinned certs ends up being used in Brave, probably because of the copy of it that's shipped via the *PKI Metadata component* (`kp_pinslist.pb`).

Need to figure out whether or not we should disable this.

Test URL (in Chrome's list): https://pinning-test.badssl.com/

**Comment by diracdeltas** [comment]
i think the only risk here is that if a site needs to get off the pinning list suddenly, they may know to contact chromium but not brave; but if we are getting these pinlist updates at the same time as chromium, this doesn't seem like a problem.

**Comment by fmarier** [comment]
That was my thinking exactly. Since it's from a component update, Google might be okay with that since they effectively control the list in Brave too.

**Comment by fmarier** [comment]
The Chrome team has requested that embedders not enforce these pins: https://groups.google.com/a/chromium.org/g/embedder-dev/c/XsNTwEiN1lI/m/TMXh-ZvOAAAJ

**Comment by fmarier** [comment]
It turns out that Chrome's pins are not yet enforced in Brave because we haven't merged yet the version of Chromium which enabled pins from the PKI Metadata component: https://source.chromium.org/chromium/chromium/src/+/c33500d8b97d2b0756af4acedf9f7f630c9b5218

However, we are pinning the static test entries from them, which makes testing more difficult.

**Comment by fmarier** [comment]
Suggested addition to the smoketests to cover this issue too: https://github.com/brave/qa-resources/pull/455

**Comment by kjozwiak** [comment]
The above requires `1.43.80` or higher for `1.43.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.43.80 Chromium: 104.0.5112.102 (Official Build) dev (x86_64)
-- | --
Revision | 8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}
OS | macOS Version 11.6.8 (Build 20G730)

### Steps:
1. installed `1.43.80`
2. launched Brave
3. loaded `https://ssl-pinning.someblog.org/`
4. confirmed I received a warning about the site not being pinned
5. loaded `https://pinning-test.badssl.com/`
6. confirmed I got the red error page

`ssl-pinning.someblog.org` | `pinning-test.badssl.com`
----------------------------|---------------------------
<img width="1312" alt="Screen Shot 2022-08-23 at 12 48 01 PM" src="https://user-images.githubusercontent.com/387249/186253257-ccd0b99c-03ae-4186-893d-fb28c6f5ff87.png"> | <img width="1312" alt="Screen Shot 2022-08-23 at 12 48 16 PM" src="https://user-images.githubusercontent.com/387249/186253264-01df470f-417a-4df7-84d8-8e16aba6e91e.png">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.43.81 Chromium: 104.0.5112.102 (Official Build) (64-bit)
-- | --
Revision | 8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}
OS | Windows 11 Version 21H2 (Build 22000.856)
```
### Steps:
1. installed `1.43.81`
2. launched Brave
3. loaded `https://ssl-pinning.someblog.org/`
4. confirmed I received a warning about the site not being pinned
5. loaded `https://pinning-test.badssl.com/`
6. confirmed I got the red error page

Ex1|Ex2
---|---
<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/186783934-c48f4545-1749-4fad-ac51-2b28cfd4bfc4.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/186785968-17fcb67c-0658-442c-a1a2-6428269b8008.png">

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.43.81 Chromium: 104.0.5112.102 (Official Build) (64-bit)
-- | --
Revision | 8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}
OS | Ubuntu 18.04 LTS

#### https://ssl-pinning.someblog.org/
confirmed I received a warning about the site not being pinned
![image](https://user-images.githubusercontent.com/34715963/186917189-d96c1142-3b37-4047-904a-0968d81fc9af.png)

#### https://pinning-test.badssl.com/
confirmed I got the red error page

![image](https://user-images.githubusercontent.com/34715963/186917211-89154202-7b12-441d-adb0-aa28db810405.png)
