### ISSUE TITLE
[Security][Android] SSL Pinning doesn't work 

### ISSUE THREAD

**Issue by stoletheminerals** [brave/brave-browser#24453]
## Description 
SSL Pinning doesn't work for the domains listed in https://github.com/brave/brave-core/blob/master/chromium_src/net/tools/transport_security_state_generator/input_file_parsers.cc

## Steps to reproduce 

   1. Navigate to https://ssl-pinning.someblog.org/

## Actual result 
Webpage loads without an SSL error
<img width="463" alt="image" src="https://user-images.githubusercontent.com/10810135/182974774-73798312-7407-4b9b-a57e-ae6682ab6f37.png">

## Expected result
Webpage fails to load with an SSL error

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by fmarier** [comment]
Upstream appears to be preparing to roll this out to Android: https://chromium.googlesource.com/chromium/src/+/f12eac9342eb88971851d46e31c97af8c2c27%5E%21/

**Comment by fmarier** [comment]
This is now working in Brave for Android and so we should enable too.

This was done on desktop in https://github.com/brave/brave-core/pull/8750.

**Comment by fmarier** [comment]
It's probably just a matter of removing the check for Android here: https://github.com/brave/brave-core/blob/44a98b1a20d935db5eab9899361871740695d29b/chromium_src/net/http/transport_security_state.cc#L17-L25

and then testing it like this:
1. Going through the test plan at https://github.com/brave/brave-core/pull/22540
2. Opening https://pinning-test.badssl.com/ and confirming that there's no TLS error and that the red page loads fine:
![Screenshot from 2024-05-06 10-58-24](https://github.com/brave/brave-browser/assets/167821/fe41c9a9-fd92-4a47-bc93-94ef83025c14)

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 15 AP31.240517.031 release-keys
Brave build: 1.68.115
Chromium: 127.0.6533.26 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/24453#issue-1329290991 and https://github.com/brave/brave-browser/issues/24453#issuecomment-2096607206
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the page fails to load with an `SSL` error when navigating to https://ssl-pinning.someblog.org/
- Verified that there's no `TLS` error and that the `red page` loads fine when navigating to https://pinning-test.badssl.com/

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/2d5d2dce-4368-4aa2-9ebc-0f890217ba14) | ![2](https://github.com/brave/brave-browser/assets/128532965/a46827e7-2310-44c1-9b56-b0413c48ef27) |
