### ISSUE TITLE
Cert pinning is not enforced on Desktop

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#24451]
Upstream recently [changed how pinning is gated](https://chromium.googlesource.com/chromium/src/+/f12eac9342eb88971851d46e31c97af8c2c27%5E%21/) and when we merged that change, we [added a fixed timestamp of *Wed 13 Apr 2022 05:00:00 PM PDT*](https://github.com/brave/brave-core/commit/c3f7f99f569fd8e69de2848a340f83194e81cfa1). That stopped working a few weeks later because at that point the list is [considered stale after 10 weeks](https://source.chromium.org/chromium/chromium/src/+/main:net/http/transport_security_state.cc;l=1124-1128;drc=6dc688ca4a5fdd6a52a216b5db83a78c36c89e8d).

Test URL (in Brave's pinning list): https://ssl-pinning.someblog.org/

**Comment by fmarier** [comment]
I created a [PR to do this manually](https://github.com/brave/brave-core/pull/14478), but the real fix is to [automate updating this timestamp](https://github.com/brave/devops/issues/8082).

**Comment by fmarier** [comment]
To prevent future regressions:
- https://github.com/brave/qa-resources/issues/450
- https://github.com/brave/brave-browser/issues/24455

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.43.62 Chromium: 104.0.5112.81 (Official Build) beta (x86_64)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | macOS Version 11.6.8 (Build 20G730)

### Steps:
1. installed `1.43.62`
2. launched Brave
3. loaded `https://ssl-pinning.someblog.org/`
4. clicked on `Advanced`


#### Confirmed I got the certificate-pinning error message

`Light` | `Dark`
-------|--------
<img width="960" alt="Screen Shot 2022-08-08 at 6 11 05 PM" src="https://user-images.githubusercontent.com/387249/183541321-319f384d-59d3-4bda-86ac-d606c92a4bcd.png"> | <img width="1439" alt="Screen Shot 2022-08-08 at 6 11 18 PM" src="https://user-images.githubusercontent.com/387249/183541328-c682281d-93bf-41c1-92f2-2b2386531db7.png">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.43.63 Chromium: 104.0.5112.81 (Official Build) beta (64-bit)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | Windows 11 Version 21H2 (Build 22000.795)
```

- install 1.43.63
- launch Brave
- visit `https://ssl-pinning.someblog.org/`

### Verified pinning error message shown as expected

dark|light
---|----
<image width = "800" alt="image" src="https://user-images.githubusercontent.com/98358127/183781610-a8a92960-f8c0-417d-9e10-06f1b69aa3a2.png">|<image width = "800" alt="image" src="https://user-images.githubusercontent.com/98358127/183781640-2a19c825-4b4a-401f-8b77-cf0104cbb783.png">
