### ISSUE TITLE
MetaMask with prefer extension setting brings down Google doc/sheet

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#24456]
Regressed by https://github.com/brave/brave-core/pull/14193
With default wallet setting set to prefer extension, we shouldn't redefine `window.ethereum` properties as read only

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.42.88 Chromium: 104.0.5112.81 (Official Build) (64-bit)
-- | --
Revision | `5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}`
OS | Windows 11 Version 22H2 (Build 22622.450)

- Verified steps from [brave/brave-core#14483](https://github.com/brave/brave-core/pull/14483)
- Verified setting up MM & BW and setting prefer extensions as default doesn't cause any crash
- Verified able to load GDocs without any issue
- Verified loading web2/web3 pages doesn't throw any console errors
- Verified no errors when trying to connect to a Dapp via MM extension when prefer extension is set as default with both MM and Brave Wallet enabled

**Comment by 01235110219565** [comment]
c20422208@gmail.com
中國銀行有限公司HK BoC
WONG LAP FAI/王立輝
