### ISSUE TITLE
Pending transaction badge is not cleared when wallet is reset

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#24462]
## Description 
Pending transaction badge is not cleared when wallet is reset

## Steps to reproduce 

   1. Create some pending tx
   2. Reset the wallet, the pending tx dot is not cleared until app is restarted

## Actual result

https://user-images.githubusercontent.com/11755381/183064994-3f277ff1-fc48-4d0c-96f2-c1ebd59b4ac4.mp4

## Expected result
Notification badge should be cleared when wallet is reset

**Comment by simoarpe** [comment]
The pending transaction red badge is now cleared correctly when the wallet is reset. 
Closing this issue as it's not reproducible anymore.
