### ISSUE TITLE
Shields breaking text/fonts on some websites (followup)

### ISSUE THREAD

**Issue by pilgrim-brave** [brave/brave-browser#24468]
https://github.com/brave/brave-browser/issues/23093#issuecomment-1205922022

"""
I experienced this issue and arrived here after some basic troubleshooting and finding that turning down shields allowed our font stack to work as expected. At the time, I was running macOS 12.4 and a slightly outdated version of Brave.

The font stack is Inter, -apple-system, BlinkMacSystemFont, avenir next, avenir, helvetica neue, helvetica, Ubuntu, roboto, noto, segoe ui, arial, sans-serif, and the font that I was seeing was avenir. So the browser was skipping Inter (despite Inter being installed correctly and having worked as expected with this font stack previously) and also skipping the two apple system font declarations. Again, turning down shields allowed the stack to perform as expected.

Next, I updated Brave to 1.42.86, which was after the fix announced above, and that did not improve the issue. Only after updating macOS to 12.5 was the issue resolved.

Hope this helps!
"""

**Comment by LaurenWags** [comment]
from @pes10k:

QA test: https://dev-pages.brave.software/fingerprinting/fonts.html
(the “Pseudo Fonts” section)

**Comment by LaurenWags** [comment]
Requires `1.42.90` or higher to test

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.42.91 Chromium: 104.0.5112.81 (Official Build) (x86_64)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | macOS Version 13.0 (Build 22A5321d)

### Steps:
1. installed `1.42.91`
2. installed the `Fredoka One` font
3. launched Brave
4. loaded `https://dev-pages.brave.software/fingerprinting/fonts.html` and `https://dev-pages.bravesoftware.com/fingerprinting/fonts.html`
5. clicked on `Start tests`
6. checked the `Pseudo Fonts` section's output

#### Confirmed the `Control` and `Test` font were rendered the same and with the same width: `343` pixels

`dev-pages.brave.software` | `dev-pages.bravesoftware.com/`
-----------------------------|----------------------------------
<img width="1312" alt="Screenshot 2022-08-10 at 11 44 48 AM" src="https://user-images.githubusercontent.com/387249/183992913-26fa7c53-07f7-4843-8855-b118f4005a42.png"> | <img width="1312" alt="Screenshot 2022-08-10 at 11 44 57 AM" src="https://user-images.githubusercontent.com/387249/183992978-3ad2913e-3ee2-4b5a-9954-f8d4b4e2a632.png">

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.42.91 Chromium: 104.0.5112.81 (Official Build) (64-bit)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | Windows 11 Version 21H2 (Build 22000.856)
```
Reproduced using 1.42.88 Chromium: 104.0.5112.81 (Official Build)
confirmed "Pseudo Fonts" test did not show expected results:
![image](https://user-images.githubusercontent.com/98358127/183989688-2881e869-959d-40d7-b6c9-c6fed3d88b0c.png)


1. Install 1.42.91
2. launch Brave
3. restarted the browser 
4. open `brave://settings/shields` and confirmed "Prevent sites from fingerprinting me based on my language preferences" was enabled 
5. visited https://dev-pages.brave.software/fingerprinting/fonts.html
6. download and install the `fredoka one` font as per the setup instructions on the page 
7. click Start tests

 

Step 3|Step 4|Results|Results
----|----|----|----
<image width ="850" alt="image 1" src="https://user-images.githubusercontent.com/98358127/183988600-6343ea82-1268-48cd-9fc7-0536f1a88ed9.png">|<image width ="850" alt="image 1" src="https://user-images.githubusercontent.com/98358127/183988701-1ff40c18-c802-4ab3-8322-d80ee213c292.png">|<image width ="850" alt="image 1" src="https://user-images.githubusercontent.com/98358127/183991006-f900a3a8-bd90-48bd-9485-47cbe9d0f572.png">|<image width ="850" alt="image 1" src="https://user-images.githubusercontent.com/98358127/183991020-f1e3c369-ada5-4d55-bdca-b1f1a1471424.png">
