### ISSUE TITLE
Implement create solana account option in buysendswap

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#24463]
## Description 
Show auto solana account create dialog in buysendswap for send when there is no solana account

## Steps to reproduce 

   1. Create wallet
   2. click send
   3. select solana account, should ask to create solana account

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.44.79 x64 Beta build
- Verified steps from [brave/brave-core#14497](https://github.com/brave/brave-core/pull/14497)
- Verified able to create Solana account from Send screen
- Verified able to submit a send transaction as soon as the account is created from Send screen
- Encountered [#25373](https://github.com/brave/brave-browser/issues/25373)

https://user-images.githubusercontent.com/17010094/189926747-10f768fe-5b63-439d-b596-795f780972be.mp4
