### ISSUE TITLE
"You can switch between Brave profiles here" message has a Chrome blue background

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#24466]
## Description 

Message which says "You can switch between Brave profiles here" is in Chrome blue color. Should be a Brave color/design instead.

## Steps to Reproduce

   1. Create a second profile.
   2. Note message on the new window of second profile is in Chrome blue color, should be Brave-ified.

## Actual result:

<img width="423" alt="blue profile msg" src="https://user-images.githubusercontent.com/28145373/183087044-8bc7d636-6799-4b6a-9be2-17a425fe2e6c.png">

## Expected result:

The blue color should be more Brave-ified

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.44.23 Chromium: 104.0.5112.81 (Official Build) nightly (x86_64)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | macOS Version 12.5 (Build 21G72)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes, not new with C104 though
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron

**Comment by Rixant** [comment]
Could you please assign me this issue?

**Comment by rebron** [comment]
cc: @aguscruiz Can you provide a color for this one.

**Comment by aguscruiz** [comment]
Added designs here:

https://www.figma.com/file/sS3l8tqUFxt54MEiBTalUI/Desktop-toolbar-and-menu?node-id=1792%3A6053

![image](https://user-images.githubusercontent.com/15734630/183902867-9bf63d4c-3ce7-4c79-9f57-b3fa8c6e750e.png)

![image](https://user-images.githubusercontent.com/15734630/183902906-9abcd183-3572-416e-b683-013208827a73.png)

**Comment by sangwoo108** [comment]
I believe this bubble is one of what's called In-product help bubble(IPH bubble). So, the new color could be applied to all other IPHs. Is it okay or do you want to change color only for IPH on profile button?

**Comment by aguscruiz** [comment]
I think we'll be ok changing it everywhere. If you find a scenario where this wouldn't work, let me know and we can talk about it :)

**Comment by sangwoo108** [comment]
Thank you for confirmation! Let me try this one quickly.

**Comment by sangwoo108** [comment]
### on dark theme
<img width="439" alt="image" src="https://user-images.githubusercontent.com/5474642/191951706-fc7b4eb2-9cea-4c80-b1a6-2500d333db47.png">

### on light theme
<img width="382" alt="image" src="https://user-images.githubusercontent.com/5474642/191951906-80031cab-505d-498e-8471-3600faaf3bb1.png">

**Comment by sangwoo108** [comment]
@aguscruiz , I was looking color configs from the upstream and found there's more colors

```
kColorFeaturePromoBubbleButtonBorder <-- #DADCE0
kColorFeaturePromoBubbleDefaultButtonBackground <-- uses bubble foreground
kColorFeaturePromoBubbleDefaultButtonForeground <-- uses bubble background
```
Some IPH seems to have a button on it. I could find the real example yet. I made an ad-hoc update on these too. Let's see what happens.

**Comment by aguscruiz** [comment]
That color seems to be the same as the browser toolbar background, that's probably it.

Just a head's up, there's something junky happening there with the border radius and also the background. Seems to be 2 different ones acting together 
<img width="79" alt="image" src="https://user-images.githubusercontent.com/15734630/191956986-7fdebe90-ec1c-43bb-95cd-3bc4a16960d2.png">

**Comment by sangwoo108** [comment]
> That color seems to be the same as the browser toolbar background, that's probably it.
> 
> Just a head's up, there's something junky happening there with the border radius and also the background. Seems to be 2 different ones acting together <img alt="image" width="79" src="https://user-images.githubusercontent.com/15734630/191956986-7fdebe90-ec1c-43bb-95cd-3bc4a16960d2.png">

Yeah, nice catch. It seems Ink drop's radius and border radius don't match. Let me create an issue for it.

**Comment by stephendonner** [comment]
Verifying as `PASSED`, since I logged a follow-up issue: https://github.com/brave/brave-browser/issues/26290, which we can milestone-triage further, once we have a fix.
