### ISSUE TITLE
DOH Ipfs override may cause high cpu usage

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#24461]
There is a report from @aseren where he got high cpu usage on macos when closed the browser.
Sampling pointed to the doh override network service listener. Seems network service was down and didn't wake up.
So throttling needed when try to reconnect to network manager.

**Comment by kjozwiak** [comment]
The above will require `1.43.81` or higher for `1.43.x` verification.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.43.81 Chromium: 104.0.5112.102 (Official Build) (x86_64)
-- | --
Revision | 8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}
OS | macOS Version 13.0 (Build 22A5321d)

### Steps:
1. installed `1.43.81`
2. launched Brave
3. loaded `brave://ipfs-internals`
4. clicked on `Install and start`
5. opened `Window` -> `Task Manager`
6. selected `Utility: Network Service`
7. clicked on `End Process`
8. opened `brave://settings/security` and made sure `With Cloudflare (1.1.1.1)` was selected
9. loaded `ipns://en.wikipedia-on-ipfs.org`

#### Confirmed it loaded `ipns://en.wikipedia-on-ipfs.org/wiki/` with a new `Utility: Network Service` process (Old: `4163`, New: `4314`)

example | example | example | example
---------|----------|---------|---------
<img width="592" alt="Screenshot 2022-08-24 at 3 32 45 PM" src="https://user-images.githubusercontent.com/387249/186535570-7b85363c-56a0-4f57-a04a-3ff232699b0f.png"> | <img width="1028" alt="Screenshot 2022-08-24 at 3 33 15 PM" src="https://user-images.githubusercontent.com/387249/186535653-e7221121-8fa9-4f95-9aba-ff3acb1b224b.png"> | <img width="1028" alt="Screenshot 2022-08-24 at 3 33 41 PM" src="https://user-images.githubusercontent.com/387249/186535658-71380e66-b6e0-4395-9940-4f5d81907d58.png"> | <img width="592" alt="Screenshot 2022-08-24 at 3 34 12 PM" src="https://user-images.githubusercontent.com/387249/186535660-9e3c1dad-90d8-41fb-9160-9c7e7436cca3.png">

**Comment by stephendonner** [comment]
Ran through the following URLs:
* `ipfs://bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq/wiki/Vincent_van_Gogh.html`
* `ipfs://bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi/`
* `ipns://brad.crypto`
* `ipns://ipfs.io`



`ipfs://bafy...van_Gogh.html` | `ipfs://bafy...55fbzdi/`| `ipns://brad.crypto` | `ipns://ipfs.io`
------|--------|--------|---------
![Screenshot_20220831-092213](https://user-images.githubusercontent.com/387249/187731859-e8cd2e13-81fb-43ac-8470-a2f25536f1f9.png) | ![Screenshot_20220831-092019](https://user-images.githubusercontent.com/387249/187731894-9e363227-eed9-4826-9300-d0c48d0ff625.png) | ![Screenshot_20220831-091730](https://user-images.githubusercontent.com/387249/187731932-cef98d0a-2922-49fa-a250-972d3c78783b.png) | ![Screenshot_20220831-092355](https://user-images.githubusercontent.com/387249/187731967-5f2ce757-0a96-4028-aa24-a8d278eec6cb.png)






Ran through `https://github.com/brave/qa-resources/blob/82e6e8dd508f87595b20c4bbde093cd80d124dbe/wikitemplate-IPFS.md#ipfs-on-android`, additionally 👍
