### ISSUE TITLE
Asset list needed for Aurora chain

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#24473]
At least assets available on rainbowbridge should be in the assets list for aurora/NEAR.

![Image](https://user-images.githubusercontent.com/318119/183121224-6a2503f2-8fad-421c-8d53-8ffd63caa897.png)

**Comment by onyb** [comment]
Updated Wallet Data files on production via https://ci.brave.com/job/brave-core-ext-wallet-data-files-update-publish/26. Current version of Wallet-Data-Files-Updater is 1.0.17. Tested OK on current Release, Beta, and Nightly.
