### ISSUE TITLE
Crash due to dismissed tx dialog before the Solana tx data is completely fetched and shown

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#24472]
## Description 
Transaction dialog takes time to parse and show the details and dismissing it while the data is being fetches causes a crash in dialog during an attempt to update dialog which has been dismissed

https://user-images.githubusercontent.com/11755381/183112175-4cb4b45d-f877-4051-a334-633ed461c8a3.mp4

### Additional information

Works fine with ETH tx as they are quick to show.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.42.96 x64 build
- Verified steps from issue description and no crash when initiating a Solana Transaction
- Verified transaction confirmation screen loads correctly without crashing for pre-set values
- Verified transaction confirmation screen loads correctly without crashing when a very low decimal value is set
- Verified for both Solana accounts and Ethereum/EVM accounts

Oppo Reno 5 (Android 12.1) | Samsung Tab A (Android 10)
-- | -- 
<video src=https://user-images.githubusercontent.com/17010094/184892687-6b8a299a-f86e-4b49-b4ac-53a4c5f95dc8.mp4> | <video src=https://user-images.githubusercontent.com/17010094/184893748-fdb740b7-5345-40af-a73d-3876cf56cdea.mp4>
