### ISSUE TITLE
Brave Browser is detecting as Chrome

### ISSUE THREAD

**Issue by cjsio** [brave/brave-browser#24478]
This issue was originally documented inside the [browscap project issue tracker](https://github.com/browscap/browscap/issues/2676), but upon closer examination appears to require an edit inside the Brave codebase.

## Description 
I'm using Brave Browser Version 1.40.109 w/ Chromium Version 103.0.5060.66 (Official Build) (64-bit) on Windows 11, but after updating to the latest [php_browscap.ini](http://browscap.org/stream?q=PHP_BrowsCapINI), Brave Browser is being detected as:

> Chrome version 103 on Windows 10

**08/05/22 Update:** I've just updated to Brave Browser Version 1.42.86 w/ Chromium: 104.0.5112.81 (Official Build) (64-bit) and Brave Browser is still being detected as Chrome, but now as version 104:

> Chrome version 104 on Windows 10

According to [developers.whatismybrowser.com](https://developers.whatismybrowser.com/useragents/explore/software_name/brave/), most Brave user agents contains the keyword "Brave" in them, but my current user agent in a standard Brave installation on Win11 is:

>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.66 Safari/537.36

## Reproduces how often: 
Always on my Windows 11 machine

## Brave version
Version 1.40.109 w/ Chromium Version 103.0.5060.66 (Official Build) (64-bit) through Version 1.42.86 w/ Chromium: 104.0.5112.81 (Official Build) (64-bit)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? **A:** Disabling shields does not impact this issue as it doesn't alter the useragent.
- Does the issue resolve itself when disabling Brave Rewards? **A:** I have never enabled Brave Rewards but presumably this also will not alter the useragent.
- Is the issue reproducible on the latest version of Chrome? **A:** N/A as this is a Brave-specific useragent issue. The useragent would be correct if this were Chrome.

**Comment by UjCbFwtBayFM** [comment]
This behavior is intended. One (the only?) way to reliably detect if a user is running Brave would be through this method:
`(navigator.brave && await navigator.brave.isBrave() || false)`

**Comment by rebron** [comment]
Closing. Works as expected and thanks for the comment @UjCbFwtBayFM, that's correct.
