### ISSUE TITLE
Unable to update to/install go-ipfs 0.14.0 on Windows

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#24475]
## Description 

Unable to update to/install go-ipfs 0.14.0 on Windows

## Steps to Reproduce

1. install `1.42.86`
2. launch Brave using `--use-dev-goupdater-url`
3. load `brave://ipfs`
4. click on `Install and restart`
5. check the `go-ipfs` version

## Actual result:

Remains at `go-ipfs` `0.13.0`, even after restarting Brave

![image](https://user-images.githubusercontent.com/387249/183128986-ae2911ed-f06c-4ed2-b615-f7cee27a408c.png)

## Expected results:

Case 1: Should upgrade from `0.13.0` -> `0.14.0`
Case 2: Should fresh-install `go-ipfs` `0.14.0`

## Reproduces how often: 

100%

## Brave version (brave://version info)

I swear I tested this before; sorry, not sure how I missed this (it works on macOS).

cc @lidel @cypt4 @spylogsster

**Comment by stephendonner** [comment]
cc @mihaiplesa just FYI, as it might relate to the recent binary-signing changes.

**Comment by stephendonner** [comment]
![image](https://user-images.githubusercontent.com/387249/183134511-3c67d292-2c43-47f6-a896-0a118033ea9e.png)

**Comment by mherrmann** [comment]
Doesn't reproduce for me on Windows. I'm able to install 0.14.

**Comment by stephendonner** [comment]
This was due to a couple things:
* we had to republish the Windows-signed binaries, as the original job failed (other installation errors not pictured in screenshot)
* I had the correct commandline flag, but a previous parameter for something else was unterminated/unbalanced, making `--use-dev-goupdater-url` get dropped at runtime.
