### ISSUE TITLE
Manual test run on macOS (arm64) for 1.42.x - Release #2

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#24486]
### Installer

- [ ] Ensured that the following executables work as expected
   - [x] `Brave-Browser-arm64.dmg`
      - [x] Check executable size, should be `~290mb`
      - [ ] Check signature: If OS Run `"spctl --assess --verbose /Applications/Brave Browser.app"` and make sure it returns `accepted`.
   - [ ] `Brave-Browser-x64.dmg`
       - [ ] Check executable size, should be `~290mb`
       - [ ] Check signature: If OS Run `"spctl --assess --verbose /Applications/Brave Browser.app"` and make sure it returns `accepted`.
   - [x] `Brave-Browser-universal.dmg`
       - [x] Check executable size, should be `~500mb`
       - [ ] Check signature: If OS Run `"spctl --assess --verbose /Applications/Brave Browser.app"` and make sure it returns `accepted`.
- [ ] Visited `brave://version` and ensure the following:
   - [x] `arm64` is being displayed when installing via `arm64` and `universal` binaries on `M1` mac
   - [ ] `x86_64 translated` is being displayed when installing via `x64` binary on `M1` mac using `Rosetta`

### Widevine

- [x]  Using `universal` build:
   - [x]  Verify `Widevine Notification` is shown when you visit Netflix for the first time
   - [x]  Test that you can stream on Netflix on a fresh profile after installing Widevine 
- [x]  Using `arm64` build:
   - [x]  Verify `Widevine Notification` is shown when you visit Netflix for the first time
   - [x]  Test that you can stream on Netflix on a fresh profile after installing Widevine 

#### Components
- [x]   Delete Adblock folder from browser profile and restart browser. Visit `brave://components` and verify `Brave Ad Block Updater` downloads and update the component. Repeat for all Brave components

#### Upgrade - `Brave-Browser-arm64.dmg`

- [x] Make sure that data from the last version appears in the new version OK
- [x] Ensure that `brave://version` lists the expected Brave & Chromium versions
- [x] With data from the last version, verify that
  - [x] Bookmarks on the bookmark toolbar and bookmark folders can be opened
  - [x] Cookies are preserved
  - [x] Installed extensions are retained and work correctly
  - [x] Opened tabs can be reloaded
  - [x] Stored passwords are preserved
  - [x] Sync chain created in previous version is retained 
  - [x] Social media blocking buttons changes are retained
  - [x] Rewards
    - [x] BAT balance is retained
    - [x] Auto-contribute list is retained
    - [x] Both Tips and Monthly Contributions are retained
    - [x] Panel transactions list is retained
    - [x] Changes to rewards settings are retained
    - [x] Ensure that Auto Contribute is not being enabled when upgrading to a new version if AC was disabled
  - [x] Ads
    - [x] Both `Estimated pending rewards` & `Ad notifications received this month` are retained
    - [x] Changes to ads settings are retained
    - [x] Ensure that ads are not being enabled when upgrading to a new version if they were disabled
    - [x] Ensure that ads are not disabled when upgrading to a new version if they were enabled

**Comment by rebron** [comment]
Verified passed on universal build:

Brave | 1.42.88 Chromium: 104.0.5112.81 (Official Build) (arm64)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | macOS Version 13.0 (Build 22A5295h)
JavaScript | V8 10.4.132.20
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.42.88 Chromium: 104.0.5112.81 (Official Build) (arm64)
-- | --
Revision | `5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}`
OS | macOS Version 12.4 (Build 21F79)
