### ISSUE TITLE
Please restore clear history on exit functionality

### ISSUE THREAD

**Issue by sam-wheat** [brave/brave-browser#24482]
Steps to reproduce:

Enable clear history on exit
Login to youtube
Close the browser
Open the browser, navigate to youtube
Note login persists.

I am aware this functionality is by design.  Please restore it to work the way it used to and the way the UI leads the user to believe it should.  

Thank you.

**Comment by rebron** [comment]
@sam-wheat Selecting the history checkbox will only clear history and the entires from brave://history/. To clear logins, you'll need to select `cookies and other site data` in the clear on exit screen.

**Comment by sam-wheat** [comment]
> To clear logins, you'll need to select cookies and other site data in the clear on exit screen.


That option is selected.  Did you follow the steps to reproduce the issue?  I can reproduce this issue 100% of the time with youtube, github, and outlook.  

Please be honest with users about the way the browser is designed to work.  If you intend on not clearing cookies on exit, please do not include an option that leads the user to believe you will.

Thanks.

**Comment by sam-wheat** [comment]
Says cookies exist for 38 sites.  I've visited one site since opening the browser.

![Capture](https://user-images.githubusercontent.com/16885210/185708857-c61e8f90-186a-4d64-a580-698f5f198b2a.PNG)
