### ISSUE TITLE
Unable to use extensions menu on Wayland

### ISSUE THREAD

**Issue by ket0x4** [brave/brave-browser#24491]
## Description 
Extension menus looks broken with wayland (not xwayland)

## Steps to Reproduce

   1. Enable Wayland (`--enable-features=UseOzonePlatform --ozone-platform=wayland` or go to brave://flags/#ozone-platform-hint and choose wayland)
   2. Relaunch Browser
   3. Try with any extension 

## Actual result:

![image](https://user-images.githubusercontent.com/25691875/183264049-6e3020d2-9025-4f98-a3cb-d7bdf470d36c.png)

## Expected result:
![image](https://i.ibb.co/QPH7wyQ/Ekran-G-r-nt-s-2022-08-06-22-51-04.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

1.42.86 Chromium: 104.0.5112.81 (Resmi Derleme) unknown (64 bit) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
Nope
- Does the issue resolve itself when disabling Brave Rewards? 
Nope
- Is the issue reproducible on the latest version of Chrome?
Nope

## Miscellaneous Information:

OS: Fedora 36 Silverblue. Brave installed via flatpak

**Comment by muradbuyukasik** [comment]
Facing the same issue.

1.42.86 Chromium: 104.0.5112.81 (Official Build) (64-bit) 

OS: Arch Linux, kernel `linux 5.18.15.arch1-2`

**Comment by acheong08** [comment]
Flatpak issue. Works with snap and deb right now

**Comment by EmptyVisual** [comment]
@Caticer seems to be an upstream issue -https://bugs.chromium.org/p/chromium/issues/detail?id=1282790

I've had this issue for ages and it seems to be a few things that cause it. But having multiple monitors is definitely a common variable between reports.

Hoping this gets fixed at some point

**Comment by binarious** [comment]
Do you have a workaround for this issue?

**Comment by acheong08** [comment]
> Do you have a workaround for this issue?

Set `Preferred Ozone platform` to `X11` in `brave://flags/`

**Comment by imadethisfor1page** [comment]
Did not work.

**Comment by binarious** [comment]
Does only happen in multi monitor setups for me when the secondary monitor is off. A workaround via a totally different issue (https://github.com/swaywm/sway/issues/4857):
Make sure the primary monitor starts at 0. I'm doing this like so in sway:
```
output eDP-1 pos -1920 0 res 1920x1080
output HDMI-A-1 pos 0 0 res 3840x2160
```

**Comment by jeroni** [comment]
It seems an issue regarding the size of the browser window. The extension popups become more and more visible as the window size grow.

**Comment by cmsolomon** [comment]
I'm also seeing the issue.
Version 1.56.20 Chromium: 115.0.5790.171 
Ubuntu 22.04.3 LTS, 5.15.0-60-generic, using Wayland
Triple monitor (built-in laptop screen + 2 monitors)

I have found that the menus work on only one of my monitors - in my case monitor 3, which is not my primary monitor.
It might be relevant that monitor 3 is the only one that's portrait?

**Comment by codesalatdev** [comment]
> @binarious this workaround (move to position 0 the primary display) fixed my issues.
> 
> Before:
> 
> ```
>  hyprctl monitors                                                                                                       ✘ INT  11:30:27
> Monitor DP-2 (ID 1):
> 	2560x1080@59.978001 at 3840x0
> 	description: LG Electronics LG HDR WFHD 0x00049A0C (DP-2 via HDMI)
> 	make: LG Electronics
> 	model: LG HDR WFHD
> 	serial: 0x00049A0C
> 	active workspace: 2 (2)
> 	reserved: 0 30 0 0
> 	scale: 1.00
> 	transform: 0
> 	focused: yes
> 	dpmsStatus: 1
> 	vrr: 0
> ```
> 
> After changing the position:
> 
> ```
> hyprctl monitors                                                                                                              11:31:02
> Monitor DP-2 (ID 1):
> 	2560x1080@59.978001 at 0x0
> 	description: LG Electronics LG HDR WFHD 0x00049A0C (DP-2 via HDMI)
> 	make: LG Electronics
> 	model: LG HDR WFHD
> 	serial: 0x00049A0C
> 	active workspace: 2 (2)
> 	reserved: 0 30 0 0
> 	scale: 1.00
> 	transform: 0
> 	focused: yes
> 	dpmsStatus: 1
> 	vrr: 0
> ```

I can't believe that actually works :smile: 

Sadly, this isn't really an option for me with my current setup  (2 is primary):
![image](https://github.com/brave/brave-browser/assets/10341765/1ba69a4a-88b6-494f-9c69-a1827f7f7712)

**Comment by lana-kk** [comment]
You can also change it temporarily with:
`hyprctl keyword monitor DP-2,preferred, 0x0, auto`

**Comment by m3tam3re** [comment]
You can also change it for the moment with:
`hyprctl keyword monitor DP-2,preferred, 0x0, auto`

**Comment by martisj** [comment]
Setting position of output to 0 fixed my issue as well! Thank you @binarious https://github.com/brave/brave-browser/issues/24491#issuecomment-1407630986

:pray:

**Comment by iynaix** [comment]
This appears to have been fixed for me today for hyprland! (NixOS unstable)

`Version 1.62.153 Chromium: 121.0.6167.85 (Official Build) (64-bit)`
