### ISSUE TITLE
Sync: deleted node becomes folder in `Other bookmarks`

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#2449]
## Description 

Deleted node becomes folder in `Other bookmarks`

## Steps to Reproduce

1. Create sync chain, device BC-A;
2. Connect to sync chain with device BC-B with code words;
3. On device BC-A create in Bookmarks bar bookmarks A.com, B.com, C.com
4. Delete bookmark B.com on device BC-A fast after pt.3
5. On device BC-A create in Bookmarks bar folders F1, F2, F3
6. Delete folder F2 on device BC-A fast after pt.5

## Actual result:

7. See folders B.com and F2 in Other bookmarks on device BC-B

## Expected result:
7. folders B.com and F2 in Other bookmarks on device BC-B are not created.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.60.1 Chromium: 71.0.3578.80 (Developer Build) (64-bit)
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
yes

**Comment by GeetaSarvadnya** [comment]
Verification passed on 


Brave | 0.59.12 Chromium: 72.0.3626.17 (Official Build) beta (64-bit)
-- | --
Revision | 08d2140079f8db14c9eb885a803d231b1a30e817-refs/branch-heads/3626@{#315}
OS | Windows

- Verified the STR mentioned in the issue.
![image](https://user-images.githubusercontent.com/38657976/50480902-c4d5be80-0a04-11e9-8df9-1763f88ae0a4.png)
