### ISSUE TITLE
Crash Report - when opening URL with Speedreader

### ISSUE THREAD

**Issue by JeanSebastienV** [brave/brave-browser#24494]
Brave Version: 1.42.86  Chromium: 104.0.5112.81
Operating System: Linux 5.15.57-2-MANJARO

URL where crash occurred: http://transportparis.canalblog.com/archives/2022/06/28/39449394.html
(In fact every URL loaded with Speedreader crashes.)

What steps will reproduce this crash:
1. Go to a Speedreader compatible website
2. Enable Speedreader in the address bar
3. After 1 sec. the browser crashes. Note that it is able to open the link normally

[Relative discussion on _Brave Community_](https://community.brave.com/t/reporting-a-bug/419686)

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/5ba20300-efc0-a008-0000-000000000000

**Comment by Maxime-J** [comment]
Fixed with the just released v1.42.95 (https://github.com/brave/brave-browser/issues/24513)
