### ISSUE TITLE
WebTorrent should adapt to dark/light mode settings

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#24498]
## Description 

WebTorrent should adapt to dark/light mode settings

## Steps to Reproduce

1. install `1.44.26`
2. launch Brave
3. set `Brave colors` to `Dark`
4. load `https://webtorrent.io/free-torrents`
5. click on any torrent or magnet link

## Actual result:

<img width="1312" alt="Screenshot 2022-08-07 at 1 44 21 PM" src="https://user-images.githubusercontent.com/387249/183310356-11958941-730a-4b6f-bd24-9b6206cb21b6.png">

## Expected result:

The WebTorrent content should be Brave-colors aware, and adapt to `Dark` or `Light` modes

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.44.26 Chromium: 104.0.5112.81 (Official Build) nightly (x86_64)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | macOS Version 13.0 (Build 22A5311f)

cc @fallaciousreasoning @aguscruiz

**Comment by fallaciousreasoning** [comment]
I'm happy to work on this if we can get a UX mock together :smile:

**Comment by aguscruiz** [comment]
Added a mockup here @stephendonner @fallaciousreasoning 
https://www.figma.com/file/wWRDxRJFw04gLPahfAjUrO/Desktop-WebTorrent?node-id=103%3A17994

There are some minor updates too, nothing in terms of actual user experience, but visual updates to make the design be in line with the Design system.

![image](https://user-images.githubusercontent.com/15734630/183415648-2d356003-c68c-4eb8-882d-d7672d6210a8.png)

![image](https://user-images.githubusercontent.com/15734630/183415702-d775cea8-c090-45c0-b573-41f511a609bc.png)

**Comment by fallaciousreasoning** [comment]
Woohoo! All right, I'll try and jump on this later this week :smile:

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.44.70 Chromium: 105.0.5195.68 (Official Build) beta (64-bit)
-- | --
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | Windows 11 Version 21H2 (Build 22000.856)
```
Verified using original STR https://github.com/brave/brave-browser/issues/24498#issue-1331119698

#### Confirmed WebTorrent pages adapted to dark/light mode settings and pages matched to new Figma designs.

Dark
Before Download|Downloading
----|----
<image width="900" alt="image" src="https://user-images.githubusercontent.com/98358127/188015145-f00d3960-2705-4936-a4a6-b2a702f37881.png">|<image width="900" alt="image" src="https://user-images.githubusercontent.com/98358127/188015023-88acc37e-fae5-4a6b-850b-9b81c9ccf028.png">


Light
Before download|Downloading
----|-----
<image width="900" alt="image" src="https://user-images.githubusercontent.com/98358127/188015065-e9f48f2e-9077-4f75-974e-a994b93c935b.png">|<image width="900" alt="image" src="https://user-images.githubusercontent.com/98358127/188014931-2469e510-8e9f-49c8-9cfd-aa6431d9b132.png">
