### ISSUE TITLE
Include mobile app annoyances by default

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#24506]
## Description 
Include mobile app annoyances/popups by default (Android and possibly IOS)

![download-mobi](https://user-images.githubusercontent.com/1659004/183314428-61d9e322-98fe-490b-98ec-da999d68b2b6.jpg)

With https://www.macrumors.com/2022/08/05/ios-app-blocks-annoying-pop-ups-in-safari/ being offered we can do something similar also in Brave

## List currently being offered:

https://github.com/easylist/easylist/blob/master/fanboy-addon/fanboy_notifications_specific_hide.txt#L66
https://github.com/easylist/easylist/blob/master/fanboy-addon/fanboy_annoyance_specific_uBO.txt#L6

## Convert some Adguard specific filters

Needing to investigate (and convert, remove any procedural filters) additions from Adguard: 

https://github.com/AdguardTeam/AdguardFilters/blob/master/AnnoyancesFilter/MobileApp/sections/mobile-app_specific.txt
https://github.com/AdguardTeam/AdguardFilters/tree/master/AnnoyancesFilter/MobileApp/sections

## Possible issues that need to be avoided

- Removing legit content
- Scroll blocked
- Missed lightbox overlays
- Multiple scrolls

## IOS support?

Various Cosmetic filtering, `:style` and `removeclass` would be needed to be supported on IOS

## Miscellaneous Information:

No ETA, Needs reviewing and testing and avoid website breakages (overlays or scroll blocks, multiple scrolls)

**Comment by ryanbr** [comment]
Separating off mobile app notifications from other notifications is another goal here

**Comment by LaurenWags** [comment]
Per discussion with @rebron not going to include in desktop release notes but it should be included in Android/iOS notes. Also, leaving `OS/Desktop` as code is technically in desktop per discussion with @antonok-edm.
