### ISSUE TITLE
Brave sync extension is not available in brave extensions list

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#2450]
## Description 
Brave sync extension is not available in brave extensions list

## Steps to Reproduce

   1. Launch bravebeta `0.58.11` with clean profile from CLI ` BraveSoftware/Brave-Browser-Beta/Application/brave.exe --show-component-extension-options`
   2. Open `brave://extensions`
   

## Actual result:
Brave sync extension is not available in brave extensions list

![brave sync extension not visible in brave extensions_0 58 11](https://user-images.githubusercontent.com/38657976/49803025-ade06c80-fd74-11e8-9061-709c3b521f72.gif)

## Expected result:
Brave sync extension should be available in brave extensions list

## Reproduces how often: 
Always

## Brave version (brave://version info)

Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? NA

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by srirambv** [comment]
Could be windows specific as I can see the extension option on Linux

**Comment by LaurenWags** [comment]
Reproduces on macOS using

Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta(64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

When launching from terminal with `/Applications/Brave\ Browser\ Beta.app/Contents/MacOS/Brave\ Browser\ Beta --show-component-extension-options` Sync is not displayed:
![screen shot 2018-12-11 at 12 03 16 pm](https://user-images.githubusercontent.com/28145373/49816965-0dbb2100-fd3d-11e8-820c-c05754f10480.png)

**Comment by darkdh** [comment]
you have to setup sync chain first. sync extension can be loaded only when you connect to a sync chain
