### ISSUE TITLE
Password List Will Not Display

### ISSUE THREAD

**Issue by danallendotcom** [brave/brave-browser#24510]
## Description 
Cannot view list of domains with the  saved usernames and passwords.  When I click on settings->autofill->passwords, the page scrolls up a bit, but other than that, does nothing.  Brave continues to operate without a problem, including passwords.

## Steps to Reproduce
1. Open brave browser nightly on macOS, current build as of now.
2. Click the three buttons for the menu
3. Click Settings
4. Click Autofill
5. Click Passwords

![image](https://user-images.githubusercontent.com/6373767/183334816-f832deff-73ad-49f1-9920-247045371b87.png)

![image](https://user-images.githubusercontent.com/6373767/183334848-0715c18b-5af6-4464-a37e-8712a24471ed.png)

## Expected result:
Should see list of domains for which I have saved passwords.  Should be able to click on items in the list to see usernames and a passwords obscured. None of that appears.

## Reproduces how often: 
All the time

## Brave version (brave://version info)
![image](https://user-images.githubusercontent.com/6373767/183332652-8b070984-a799-4f73-b5ca-96080344d85f.png)

Operating System
![image](https://user-images.githubusercontent.com/6373767/183332701-a0c03c62-b73f-41be-b65f-8fb7b6ede8cf.png)

## Version/Channel Information:
It is happening with Brave Nightl.
Problem does not occur with regular release of Brave, this one works perfectly:
![image](https://user-images.githubusercontent.com/6373767/183333211-ab7439ae-ba7b-4b26-add9-4b15eba0efd5.png)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
Shields on or off has no effect

- Does the issue resolve itself when disabling Brave Rewards? 
Rewards on or off has no effect

- Is the issue reproducible on the latest version of Chrome? 
No, latest version of Chrome does not have this problem

## Miscellaneous Information:
I am sorry for whatever I have done to cause this problem to occur.

**Comment by sangwoo108** [comment]
Thanks @danallendotcom ! I can reproduce it on my dev env. Let me check this out.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.44.75 Chromium: 105.0.5195.102 (Official Build) beta (x86_64)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | macOS Version 11.6.8 (Build 20G730)

### Steps:
1. installed `1.44.26`
2. reproduced the issue
3. installed `1.44.75`
4. launched Brave
5. loaded `facebook.com`
6. entered my username/password
7. clicked on `Save` when prompted
8. opened `brave://settings/passwords?search=pass`
9. confirmed my `Facebook` login was saved

steps 1-2 | step 7 | step 9
----------|--------|------
<img width="1312" alt="Screen Shot 2022-09-06 at 10 13 32 AM" src="https://user-images.githubusercontent.com/387249/188699782-a116985c-7edb-46c3-86e5-8263325b11d7.png"> | <img width="1312" alt="Screen Shot 2022-09-06 at 10 19 51 AM" src="https://user-images.githubusercontent.com/387249/188699820-bf51d8bb-713e-481f-8f23-1d6d500cabd6.png"> | <img width="1312" alt="Screen Shot 2022-09-06 at 10 15 06 AM" src="https://user-images.githubusercontent.com/387249/188699890-7d73502b-0fe9-44a0-8ed0-39999f5077b5.png">

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.44.88 Chromium: 105.0.5195.136 (Official Build) beta (64-bit)
--|--
Revision | 872774b783d0e674186a3adcd2f92e7aa22a219c-refs/branch-heads/5195_124@{#4}
OS | Linux

### Steps:
1. installed `1.44.88`
2. launched Brave
3. loaded `facebook.com`
4. entered my username/password
5. clicked on `Save` when prompted
6. opened `brave://settings/passwords?search=pass`
7. confirmed my `Facebook` login was saved

`step 5` | `step 7`
---------|--------
<img width="1027" alt="Screen Shot 2022-09-16 at 12 50 53 AM" src="https://user-images.githubusercontent.com/387249/190586348-184a1bd9-8b60-4994-8bb1-c5b48e96b82f.png"> | <img width="1752" alt="Screen Shot 2022-09-16 at 12 51 48 AM" src="https://user-images.githubusercontent.com/387249/190586286-8a61373f-860e-49db-a42c-b722187e0e04.png">
