### ISSUE TITLE
Brave Browser crashes when clicking on duckduckgo info card wikipedia link

### ISSUE THREAD

**Issue by kwsp** [brave/brave-browser#24525]
## Steps to Reproduce

   1. Go to any duckduckgo page with a Wikipedia card on the right (e.g. https://duckduckgo.com/?q=duck&t=h_&ia=definition)
   2. Click on "Wikipedia" at the bottom of the card.
   3. Brave Browser crashes.
 
<img width="1417" alt="image" src="https://user-images.githubusercontent.com/30088608/183467224-38a41d39-78e4-4dff-a21a-1d288249d8a0.png">

## Actual result:

Crashes

## Expected result:
Doesn't crash and navigates to Wikipedia

## Reproduces how often: 

Always reproducible on M1 mac. Not reproducible on x64 Windows.

## Brave version (brave://version info)

Brave | 1.41.99 Chromium: 103.0.5060.134 (Official Build) (arm64)
-- | --
Revision | 8ec6fce403b3feb0869b0732eda8bd95011d333c-refs/branch-heads/5060@{#1262}
OS | macOS Version 12.4 (Build 21F79)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Haven't tried
- Can you reproduce this issue with the nightly channel? Haven't tried

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome?

**Comment by Johann999** [comment]
For me, the Wikipedia entry is quite normal displayed; no crash.
Brave 1.42.86 on Windows.

**Comment by kwsp** [comment]
Seems to be fixed in a new brave release (1.42.88)
