### ISSUE TITLE
IPFS perform garbage collection sweep should also purge localhost/ipns cache

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#24524]
brave://ipfs-internals/ if a user clicks that button, also clear the cache for localhost ipns

**Comment by lidel** [comment]
:+1:  I think it should purge browser cache for websites loaded via:
- `ipfs://` - `http://*.ipfs.localhost:{port}`
- `ipns://` - `http://*.ipns.localhost:{port}`

This way users can fixup various stale-cache situations without dealing with two separate caches.
