### ISSUE TITLE
Add additional Password-protection for Wallet Backup Seed reveal

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#24534]
## Description 

To increase the overall security, revealing the Brave Wallet backup seed phrase from should require re-entering the wallet password

## Steps to Reproduce

1. Unlock the Brave wallet
2. Navigate to Portfolio Screen -> Click the "..." icon -> Select "Back up Now" -> Agree to Terms -> Continue

## Actual result:

Seed is revealed without additional credential check

## Expected result:
User is prompted to enter their password before they can click the "continue" button

**Comment by diracdeltas** [comment]
@josheleonard is this from the doyensec audit?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.45.88 Chromium: 106.0.5249.91 (Official Build) beta (64-bit) 
-- | --
Revision | `fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}`
OS | Linux

- Verified steps from [brave/brave-core#14541](https://github.com/brave/brave-core/pull/14541)
- Verified additional password-protection is shown before revealing Backup Seed words

https://user-images.githubusercontent.com/17010094/194638626-a5471619-2843-4fa1-aebb-3c62ea003034.mp4


------------------------
Verification passed on

Brave | 1.45.88 Chromium: 106.0.5249.91 (Official Build) beta (64-bit) 
-- | --
Revision | `fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}`
OS | Windows 11 Version 21H2 (Build 22000.978)

- Verified steps from [brave/brave-core#14541](https://github.com/brave/brave-core/pull/14541)
- Verified additional password-protection is shown before revealing Backup Seed words

https://user-images.githubusercontent.com/17010094/194639001-2c3b2f80-92b1-4e5b-a7ca-0aaaec049474.mp4

------------------------
Verification passed on

Brave | 1.45.88 Chromium: 106.0.5249.91 (Official Build) beta (arm64)
-- | --
Revision | `fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [brave/brave-core#14541](https://github.com/brave/brave-core/pull/14541)
- Verified additional password-protection is shown before revealing Backup Seed words

https://user-images.githubusercontent.com/17010094/194639174-fc37271e-82c4-4bd9-86d3-1d4883f92f2d.mov
