### ISSUE TITLE
improve error flow for Tipping

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#2453]
## Description 
Currently if your tip cannot be completed for whatever reason, we don't show anything to the user because we have retry logic and we will just retry the tip later. However, the user has no indication that the tip can't go thru and may try multiple times, which when the retry logic kicks in and the tip can be completed, will result in multiple tips being deducted from their wallet. 

## Steps to Reproduce

   1. Have a wallet funded with UGP. 
   2. Attempt to tip during a time when server has some issue (intentional or otherwise).
   3. 

## Actual result:
Tip doesn't go thru. There is no notification to the user that we couldn't complete the tip and will try again later, so the user tries multiple times.

## Expected result:
When tip cannot be completed, show notification to user indicating that tip could not go thru at this time and we will try again later.

## Reproduces how often: 
Easily when UGP server has problem (intentional or otherwise)

## Brave version (brave://version info)

Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta(64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Yes, reproduced on Release version and Beta versions.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
cc @davidtemkin @kjozwiak @NejcZdovc

**Comment by LaurenWags** [comment]
A different idea that @NejcZdovc had was to possibly show the tip as pending in Tips panel (not Rewards Summary) with a Retry button instead of the notification.

**Comment by kiwina** [comment]
LOL you open the issue now it works!! But yes the returned error if any should be displayed in the tipping list with a retry button or some thing

**Comment by NejcZdovc** [comment]
closing as we will fix it here https://github.com/brave/brave-browser/issues/3052
