### ISSUE TITLE
Android Tab Switcher Just Shows Text Instead of Card for Tab

### ISSUE THREAD

**Issue by eygraber** [brave/brave-browser#24535]
## Description

When opening the tab switcher, instead of seeing tab cards, I just see text.

This just randomly started in middle of the day today. I didn't update or change any settings. 

## Steps to reproduce

   1. Open the tab switcher

## Actual result 

![Screenshot_20220808-204502](https://user-images.githubusercontent.com/1100381/183538733-96c2cb1a-9df7-4883-abeb-e142f2cf7c2e.png)

## Expected result

I can't see it to get a screenshot

## Issue reproduces how often

Always

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Didn't try
- Can you reproduce this issue with the current Play Store Nightly version? Didn't try

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Pixel 5
   - Android version: 12
   
## Brave version

1.41.100 Chromium: 103.0.5060.134 (Official Build) (64-bit)

**Comment by deeppandya** [comment]
@eygraber can you check if this still an issue with new update for the Brave app ?

**Comment by eygraber** [comment]
I haven't seen this happen again
