### ISSUE TITLE
Importing private key from Cosmos wallet and Guarda does not work

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#24547]
Community report here: https://community.brave.com/t/can-not-import-another-account-failed-to-import-account/393309/8
<img width="527" alt="Screen Shot 2022-08-09 at 2 55 18 PM" src="https://user-images.githubusercontent.com/831718/183739035-d91cc811-914d-4d6b-a1f1-50bc69031ce9.png">

It seems to be because these wallets export a private key with a 0x prefix.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.44.83 Chromium: 105.0.5195.102 (Official Build) beta (64-bit)
-- | --
Revision | `4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}`
OS | Linux

- Verified steps from [brave/brave-core#14563](https://github.com/brave/brave-core/pull/14563)
- Verified able to import wallets via private key's starting with `0x`

https://user-images.githubusercontent.com/17010094/189894527-3324de69-0bd0-4fa1-a4b6-d82e3d4f1bf0.mp4



------------------------
Verification passed on

Brave | 1.44.83 Chromium: 105.0.5195.102 (Official Build) beta (64-bit)
-- | --
Revision | `4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}`
OS | Windows 11 Version 21H2 (Build 22000.795)

- Verified steps from [brave/brave-core#14563](https://github.com/brave/brave-core/pull/14563)
- Verified able to import wallets via private key's starting with `0x`

https://user-images.githubusercontent.com/17010094/189881326-7eac2c73-9443-4ea6-a5fd-cdce50759d0a.mp4

------------------------
Verification passed on

Brave | 1.44.79 Chromium: 105.0.5195.102 (Official Build) beta (arm64)  
-- | --
Revision | `4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [brave/brave-core#14563](https://github.com/brave/brave-core/pull/14563)
- Verified able to import wallets via private key's starting with `0x`

https://user-images.githubusercontent.com/17010094/189880181-85f42ac4-ab1b-4f40-81fc-ada680cf7077.mov

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.44.79 x64 build
- Verified steps from [brave/brave-core#14563](https://github.com/brave/brave-core/pull/14563)
- Verified able to import wallets via private key's starting with 0x

https://user-images.githubusercontent.com/17010094/189930675-6dd5b55f-9f62-43c8-bb8b-d8139d46776c.mp4
