### ISSUE TITLE
Set WebUI-based Rewards panel flag to Enabled by default (1.43.x) Beta

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#24546]
## Description

Same as https://github.com/brave/brave-browser/issues/24062, except specify Beta, now that 1.43 is Beta. 

Example PR: See here for the previous PR for 1.43.x Nightly: https://github.com/brave/brave-variations/pull/316/files

**Comment by diracdeltas** [comment]
does this warrant a sec review? i don't think we've looked at this at any point, but maybe there's no risks here. my main concern would be rule of 2 violations like the ones that used to exist in wallet webui: https://chromium.googlesource.com/chromium/src/+/master/docs/security/rule-of-2.md

**Comment by kjozwiak** [comment]
> does this warrant a sec review? i don't think we've looked at this at any point, but maybe there's no risks here. my main concern would be rule of 2 violations like the ones that used to exist in wallet webui: https://chromium.googlesource.com/chromium/src/+/master/docs/security/rule-of-2.md

@diracdeltas this was already enabled on `master` using Griffen via https://github.com/brave/brave-variations/pull/317 and QA'd via https://github.com/brave/brave-variations/pull/316#issuecomment-1190743487. The above is scheduled to be released via `1.43.x`. We're planning on enabling the `WebUI rewards panel` on BETA using Griffin (same method as we did on `master`) so it can get some bake time on `BETA` before it's released via `1.43.x`.

Should we wait till the above gets a security review? Or can we enable it on `BETA` so it can bake and only push to `Production` once the security team has done a review. Let me know if that works or if we should just wait before enabling on `BETA`.

**Comment by kjozwiak** [comment]
Quick update: As per the conversation via Slack, we'll be pushing the above into BETA via Girffin either today/tomorrow.

**Comment by bsclifton** [comment]
Unintentionally resolved with https://github.com/brave/brave-variations/pull/326 (production)

I merged the change to staging with https://github.com/brave/brave-variations/pull/328
