### ISSUE TITLE
Implement declare geo UI/UX (Phase 1)

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#24542]
https://github.com/brave/internal/issues/894 
- [ ] UI/UX 

**Prerequisites:**
- https://github.com/brave/brave-browser/issues/24538 
- https://github.com/brave/brave-browser/issues/19361
- [x] Endpoints https://github.com/brave/brave-browser/issues/25484

**Comment by Miyayes** [comment]
Likely split into UI issue/PR and backend. @zenparsing @szilardszaloki

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.46.80 Chromium: 107.0.5304.68 (Official Build) beta (x86_64)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | macOS Version 12.6.1 (Build 21G217)
```

Issues encountered:
- https://github.com/brave/brave-browser/issues/26280

Verified test plan from https://github.com/brave/brave-core/pull/15199#issue-1384160311

<details>
<summary>New Profiles - InProgress</summary>

<details>
<summary>Success Case (non Japan region) - InProgress</summary>

1. Clean profile 1.46.x, relaunch to pull griffin seed.
2. Open the Rewards panel.
3. Verify that initial onboarding modal is displayed.
4. Click "Start Using Rewards".
5. Verify that a country selection modal is displayed.
6. Select a country from the drop-down.
7. Click the "Continue" button.
8. Verify that the Rewards tour is displayed.
9. Open the Preferences file for the profile and verify that the "declared_geo" property has been set.

</details>

</details>

**Comment by LaurenWags** [comment]
@brave/qa-team see this post for more information: https://bravesoftware.slack.com/archives/GAA4017R7/p1667492572270059

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```
Brave | 1.46.99 Chromium: 107.0.5304.91 (Official Build) beta (64-bit)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | Windows 10 Version 21H2 (Build 19044.2130)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/15199

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.46.121 Chromium: 108.0.5359.48 (Official Build) beta (64-bit)
-- | --
Revision | 18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}
OS | Ubuntu 18.04 LTS

- Verified the test plan from https://github.com/brave/brave-core/pull/15199

**`Clean profile`**

<details>
<summary>Success Case: Country Already Declared - PASSED</summary>

With a fresh profile:

1. Enable Rewards and close the browser.
2. Open the `Preferences` file and clear the `declared_geo` field.
3. Start the browser and open the Rewards panel.
4. Select a country and click "Continue".
5. Verify that the "Thank You" modal is displayed.
6. Click "Close".
7. Verify that Rewards panel content is displayed.
8. Open the `Preferences` file for the profile and verify that the "declared_geo" property has been set.

![image](https://user-images.githubusercontent.com/34715963/203630830-c11693a0-8bb2-43f6-9760-e7da5532d9c9.png)
![image](https://user-images.githubusercontent.com/34715963/203630961-dec6a29b-a8d6-4e2b-b9e0-46c2797bb789.png)
![image](https://user-images.githubusercontent.com/34715963/203631030-efb00434-3a2b-4a3f-b9de-187ff700dfa8.png)
![image](https://user-images.githubusercontent.com/34715963/203631087-9db060e5-4325-4d93-a29b-f96f967c6842.png)
![image](https://user-images.githubusercontent.com/34715963/203631187-57cd16d8-6f6d-4bc8-a7d4-081894f3fc05.png)


<details>
<summary>Logs from Step 4</summary>

```
[12392:12392:1123/204625.763850:VERBOSE5:ledger_impl.cc(117)] 
[ REQUEST ]
> URL: https://grant.rewards.brave.com/v4/wallets/b8f6e33e-4ae2-59d5-8b47-2db91cb37997
> Method: PATCH
> Content: {"geoCountry":"US"}
> Content Type: application/json; charset=utf-8
> Header digest: SHA-256=3qb2VxsOc3ttZ2t4p2mnCmhKFFOCcXpkoqc/iirXnIA=
> Header signature: keyId="b8f6e33e-4ae2-59d5-8b47-2db91cb37997",algorithm="ed25519",headers="digest (request-target)",signature="/jDC8lAkVe2Z2f//v8dyzHGptpbxz3OJfndHNmblRH2VLES0pfLBIM4vb8O3QihmsZnbo+nB+XIhbrEeoXwcCA=="
> Header accept: application/json
[12392:12392:1123/204626.416915:VERBOSE6:logging_util.cc(134)] 
[ RESPONSE - OnResponse ]
> Url: https://grant.rewards.brave.com/v4/wallets/b8f6e33e-4ae2-59d5-8b47-2db91cb37997
> Result: Failure
> HTTP Code: 409
> Body: {"code":409,"message":"error updating rewards wallet: error geo country has already been set for rewards wallet"}


```
</details>
</details>

<details>
<summary>New Profiles - PASSED</summary>

<details>
<summary>Success Case (non Japan region) - PASSED</summary>

1. Clean profile 1.46.x, relaunch to pull griffin seed.
2. Open the Rewards panel.
3. Verify that initial onboarding modal is displayed.
4. Click "Start Using Rewards".
5. Verify that a country selection modal is displayed.
6. Select a country from the drop-down.
7. Click the "Continue" button.
8. Verify that the Rewards tour is displayed.
9. Open the Preferences file for the profile and verify that the "declared_geo" property has been set.

![image](https://user-images.githubusercontent.com/34715963/203647460-ac643c22-410a-4d65-9e55-540559d5931e.png)


<details>
<summary>Logs</summary>

```
[12658:12658:1123/204835.176630:VERBOSE5:ledger_impl.cc(117)] 
[ REQUEST ]
> URL: https://grant.rewards.brave.com/v4/wallets
> Method: POST
> Content: {"geoCountry":"US"}
> Content Type: application/json; charset=utf-8
> Header digest: SHA-256=3qb2VxsOc3ttZ2t4p2mnCmhKFFOCcXpkoqc/iirXnIA=
> Header signature: keyId="f0a8c411d021c4b9644b859638683129f3de054fa8329776f10924a1044b55ab",algorithm="ed25519",headers="digest (request-target)",signature="ekVv3s2HpkUqWJ15ngRL8YcTmfNQHFRxfQSKLBvon0X0u8JxcYto3gCHbq7jy4tToJNa4oLmTjUhQRLga0n5Ag=="
> Header accept: application/json
[12658:12658:1123/204836.526255:VERBOSE6:logging_util.cc(134)] 
[ RESPONSE - OnResponse ]
> Url: https://grant.rewards.brave.com/v4/wallets
> Result: Success
> HTTP Code: 201
> Body: {"paymentId":"1f4e4500-e0a2-5071-9a3a-464c291e0830"}



```

</details>

</details>

<details>
<summary>Success Case (Japan region) - PASSED</summary>

1. Clean profile 1.46.x, relaunch to pull griffin seed.
2. Open the Rewards panel and click "Start Using Rewards".
3. Select "Japan" from the list and click "Continue".
4. In the Rewards tour, verify that the AC panel is not displayed.
5. In the Rewards tour, verify that the bitFlyer promo is displayed.
6. Navigate to the Rewards page.
7. Verify that the AC settings section is not displayed.

![image](https://user-images.githubusercontent.com/34715963/203649452-e3677fd3-198b-4d3b-a498-5e6581d88500.png)
![image](https://user-images.githubusercontent.com/34715963/203649493-3789f1d2-1456-4028-9f95-9db268692ace.png)



</details>

<details>
<summary>Error Case 1: Unexpected Error - PASSED</summary>

1. Clean profile 1.46.x, relaunch to pull griffin seed.
2. Open the Rewards panel and click "Start Using Rewards".
3. Turn off Wifi.
4. Select a country from the list and click "Continue".
5. Verify that "Something went wrong" error is displayed.

<details>
<summary>Logs</summary>

```
[14999:14999:1123/213443.692322:VERBOSE5:ledger_impl.cc(117)] 
[ REQUEST ]
> URL: https://grant.rewards.brave.com/v4/wallets
> Method: POST
> Content: {"geoCountry":"US"}
> Content Type: application/json; charset=utf-8
> Header digest: SHA-256=3qb2VxsOc3ttZ2t4p2mnCmhKFFOCcXpkoqc/iirXnIA=
> Header signature: keyId="7aa3cf7bf7f792c16f5a74c88bef9a31233a0d67c3a398fe79a31c52cf61cec1",algorithm="ed25519",headers="digest (request-target)",signature="3XUyq3BSFRsAKiknIPhiSjDKGlmpK5Wy6txQw6xtvtU/uoNJMZmWpoWC96JYGxtqXbL35QO8RIFkkGq4GhpOAg=="
> Header accept: application/json
[ RESPONSE - OnResponse ]
> Url: https://grant.rewards.brave.com/v4/wallets
> Result: Error
> HTTP Code: -1
> Body:
```
![image](https://user-images.githubusercontent.com/34715963/203649930-facaf9fa-709b-497d-baa2-f89971108bb4.png)


</details>


</details>

<details>
<summary>Error Case 2: 403 Forbidden - PASSED</summary>

1. Clean profile 1.46.x, relaunch to pull griffin seed.
2. Open the Rewards panel and click "Start Using Rewards".
3. Select unsupported country (like Iran) from the list and click "Continue".
4. Verify that "Brave Rewards not available" error is displayed.

Error message is shown as expected though:

![image](https://user-images.githubusercontent.com/34715963/203650996-08f9310d-8681-4a73-8252-9807d9369e5c.png)


<details>
<summary>Logs</summary>

```
[15607:15607:1123/214305.976794:VERBOSE6:logging_util.cc(134)] 
[ RESPONSE - OnResponse ]
> Url: https://grant.rewards.brave.com/v4/wallets
> Result: Failure
> HTTP Code: 403
> Body: {"code":403,"message":"error creating rewards wallet: geo country is disabled"}
[15607:15607:1123/214305.984858:INFO:post_wallets.cc(54)] Wallet generation disabled!
[15607:15607:1123/214305.993171:INFO:wallet_create.cc(103)] Failed to create Rewards wallet!

```

</details>

</details>

</details>

**`Existing profile`** 

<details>
<summary>Existing Profile Screenshots - PASSED</summary>

Using screenshots from https://github.com/brave/brave-core/pull/15199#issue-1384160311 compared to the below screens:


![image](https://user-images.githubusercontent.com/34715963/203651487-0f35879b-4f52-453d-8306-48b4cd05ee3e.png)
![image](https://user-images.githubusercontent.com/34715963/203651524-27981c95-00cd-4a1f-a22b-ccf38f9d650c.png)




</details>


<details>
<summary>Existing Profiles - PASSED</summary>

<details>
<summary>New Tab Page - PASSED</summary>

1. Install 1.45.x (Release channel), relaunch to pull griffin seed.
9. Enable Rewards.
10. Close and "upgrade" to 1.46.x (rename profile to Beta).
11. Open a new tab.
12. Verify that the "Select your country" card is displayed.
13. Click the "Continue" button.
14. Verify that the Rewards panel is opened and the country selection modal is displayed.

![image](https://user-images.githubusercontent.com/34715963/203653108-b193a23b-3205-4ab8-a2f6-c273922add93.png)
![image](https://user-images.githubusercontent.com/34715963/203653147-a7c269c5-247c-4935-96ef-6065519d48be.png)
![image](https://user-images.githubusercontent.com/34715963/203653201-3bfbd73f-310a-4e2a-80bb-7cb6de4e1add.png)
![image](https://user-images.githubusercontent.com/34715963/203653224-a6f32ec6-52b2-4ac1-8c55-7f0766091dc0.png)



<details>
<summary>Logs</summary>

```
[17791:17791:1123/220018.437145:VERBOSE5:ledger_impl.cc(117)] 
[ REQUEST ]
> URL: https://grant.rewards.brave.com/v4/wallets/3a18705f-0e4f-4956-ab49-418f35b5b077
> Method: PATCH
> Content: {"geoCountry":"PL"}
> Content Type: application/json; charset=utf-8
> Header digest: SHA-256=BeW/FSPnGAMv94rXcHDM3nTkJLSiAPy4Z1dZOSiieBk=
> Header signature: keyId="3a18705f-0e4f-4956-ab49-418f35b5b077",algorithm="ed25519",headers="digest (request-target)",signature="691dIf649PboBioBIGV2PWBVE7Ue/gRHfsSBmtf+iI2wtVp8Me8/sK0l4iCo72gtae0xzituUCSrSTMpvBNEDg=="
> Header accept: application/json
[17791:17791:1123/220019.054921:VERBOSE6:logging_util.cc(134)] 
[ RESPONSE - OnResponse ]
> Url: https://grant.rewards.brave.com/v4/wallets/3a18705f-0e4f-4956-ab49-418f35b5b077
> Result: Success
> HTTP Code: 200
> Body: 

```

</details>

</details>

<details>
<summary>Rewards Icon - PASSED</summary>

1. Install 1.45.x (Release channel), relaunch to pull griffin seed.
2. Enable Rewards, claim UGP grant and ensure no notification badges shown on rewards icon.
3. Close and "upgrade" to 1.46.x (rename profile to Beta).
4. Ensure that brave://flags/#brave-rewards-webui-panel is enabled (currently this is done via griffin study).
5. Verify that a notification badge is displayed on the Rewards icon.

![image](https://user-images.githubusercontent.com/34715963/203655123-5f049e7a-f2ff-4897-be2c-2628128af860.png)



</details>

<details>
<summary>Success Case - PASSED</summary>

Follow above "Rewards Icon" case, then:
1. Open the Rewards panel. 
2. Verify the "select country" modal is displayed.
3. Select a country and click the "Continue" button.
4. Verify that the "Thank you" modal is displayed.
5. Click "Close".
6. Verify that Rewards panel content is displayed.
7. Open the `Preferences` file for the profile and verify that the "declared_geo" property has been set.

![image](https://user-images.githubusercontent.com/34715963/203654161-e0ca6ad2-945a-4805-b9ad-56c6461dcca8.png)
![image](https://user-images.githubusercontent.com/34715963/203654203-14732bec-d52a-4901-8ab0-96713cb4bd19.png)
![image](https://user-images.githubusercontent.com/34715963/203654213-517e853d-0134-4c52-a49a-003b63bb45fd.png)
![image](https://user-images.githubusercontent.com/34715963/203654313-b55934bb-b4c9-473a-b1d8-c219ad059446.png)



<details>
<summary>Logs</summary>

```
[ REQUEST ]
> URL: https://grant.rewards.bravesoftware.com/v4/wallets/0245521f-cede-4ce1-966c-a8b5b83ce7e7
> Method: PATCH
> Content: {"geoCountry":"US"}
> Content Type: application/json; charset=utf-8
> Header digest: SHA-256=3qb2VxsOc3ttZ2t4p2mnCmhKFFOCcXpkoqc/iirXnIA=
> Header signature: keyId="0245521f-cede-4ce1-966c-a8b5b83ce7e7",algorithm="ed25519",headers="digest (request-target)",signature="G5gm4oWQAaMtzLSfbl7gSQdesFEpF90a2z79Dmmem5kyahW/I9b9QO/CkKx9+RvaPVEgABY+DYaWOlRLUJy2AQ=="
> Header accept: application/json
[19254:19254:1123/220839.057983:INFO:rewards_service_impl.cc(1166)] Response sanitization error: Invalid top-level type
[19254:19254:1123/220839.059879:VERBOSE6:logging_util.cc(134)] 
[ RESPONSE - OnResponse ]
> Url: https://grant.rewards.bravesoftware.com/v4/wallets/0245521f-cede-4ce1-966c-a8b5b83ce7e7
> Result: Success
> HTTP Code: 200

```

</details>

</details>

<details>
<summary>Unexpected Error - PASSED</summary>

Follow above "Rewards Icon" case, then:
1. Open the Rewards panel. 
2. Verify the "select country" modal is displayed.
3. Turn off Wifi.
4. Select a country and click the "Continue" button.
5. Verify that "Something went wrong" error is displayed.

![image](https://user-images.githubusercontent.com/34715963/203655176-413d07b4-6bf4-42e6-81cc-0fc07ba594f2.png)
![image](https://user-images.githubusercontent.com/34715963/203655207-ce49f875-9258-4e2e-b98d-062286b42f4e.png)
![image](https://user-images.githubusercontent.com/34715963/203655250-d9996443-4431-4544-9dbb-7d61c03b890a.png)



<details>
<summary>Logs</summary>

```
[ REQUEST ]
> URL: https://grant.rewards.bravesoftware.com/v4/wallets/08b987c9-c2c2-43a1-b436-b54fa623c992
> Method: PATCH
> Content: {"geoCountry":"US"}
> Content Type: application/json; charset=utf-8
> Header digest: SHA-256=3qb2VxsOc3ttZ2t4p2mnCmhKFFOCcXpkoqc/iirXnIA=
> Header signature: keyId="08b987c9-c2c2-43a1-b436-b54fa623c992",algorithm="ed25519",headers="digest (request-target)",signature="nuPuGQXdjctMZadIr5RDMuNrINrRrlWOYZwmZEval6IHRr0Bpzp/9150l+cg3dd2jQ2PHLm2eR4rwPBDZ2ooCg=="
> Header accept: application/json
[20100:20100:1123/221710.475065:INFO:logging_util.cc(102)] Network error (net::ERR_INTERNET_DISCONNECTED)
[20100:20100:1123/221710.491291:VERBOSE6:logging_util.cc(134)] 
[ RESPONSE - OnResponse ]
> Url: https://grant.rewards.bravesoftware.com/v4/wallets/08b987c9-c2c2-43a1-b436-b54fa623c992
> Result: Error
> HTTP Code: -1
> Body: 

```

</details>

</details>

<details>
<summary>Linked Wallet Case: bitFlyer - PASSED</summary>

Pre-req: be set to Japan for OS or use countryid flag.
1. Install 1.45.x (Release channel), relaunch to pull griffin seed.
2. Enable Rewards, claim UGP grant and ensure no notification badges shown on rewards icon.
3. Link KYC'd bitFlyer account
4. Close and "upgrade" to 1.46.x (rename profile to Beta).
5. Ensure that brave://flags/#brave-rewards-webui-panel is enabled (currently this is done via griffin study).
6. Verify that a notification badge is displayed on the Rewards icon. 
7. Open the Rewards panel.
8. Verify that the only country available is Japan.
9. Select Japan and click Continue.
10. Confirm "Thank you" message is displayed.
11. Close message and confirm panel information is shown.

![image](https://user-images.githubusercontent.com/34715963/203656976-66862e57-ce19-4e56-bb17-724d29943d5e.png)
![image](https://user-images.githubusercontent.com/34715963/203657125-fd31a906-8e2a-49c2-bc85-e54d13e8589f.png)
![image](https://user-images.githubusercontent.com/34715963/203657144-d9369f64-48b7-49e1-b0d6-87744acf536d.png)
![image](https://user-images.githubusercontent.com/34715963/203657168-1bd37488-af2e-4583-82d9-9e7fd3061216.png)
![image](https://user-images.githubusercontent.com/34715963/203657186-2175c778-e474-46d0-a5f0-cca5e0b66664.png)


<details>
<summary>Logs from step 9</summary>

```
[22096:22096:1123/223320.037904:VERBOSE5:ledger_impl.cc(117)] 
[ REQUEST ]
> URL: https://grant.rewards.bravesoftware.com/v4/wallets/19396c0f-759d-47f2-980d-289b8d86fc49
> Method: PATCH
> Content: {"geoCountry":"JP"}
> Content Type: application/json; charset=utf-8
> Header digest: SHA-256=Me3rye9M1qvq7hjPKSFwYENAess0B71534D9pQlDJU4=
> Header signature: keyId="19396c0f-759d-47f2-980d-289b8d86fc49",algorithm="ed25519",headers="digest (request-target)",signature="8C96ZtY44K8x+e4/AAAWJYUMUxjAuqqS3UplzI2bO5cGpqlgO5ktS2cJm3NBQaL2MPBprPIQzoQuEX9TQME3Aw=="
> Header accept: application/json
[22096:22096:1123/223320.641008:VERBOSE6:logging_util.cc(134)] 
[ RESPONSE - OnResponse ]
> Url: https://grant.rewards.bravesoftware.com/v4/wallets/19396c0f-759d-47f2-980d-289b8d86fc49
> Result: Failure
> HTTP Code: 409
> Body: {"code":409,"message":"error updating rewards wallet: error geo country has already been set for rewards wallet"}
[22096:22096:1123/223320.667605:INFO:patch_wallets.cc(71)] geo_country already declared!
[22096:22096:1123/223320.677828:INFO:wallet_create.cc(105)] Failed to update Rewards wallet!

```

</details>

</details>

<details>
<summary>Linked Wallet Case: Gemini - PASSED</summary>

1. Install 1.45.x (Release channel), relaunch to pull griffin seed.
2. Enable Rewards, claim UGP grant and ensure no notification badges shown on rewards icon.
3. Link KYC'd Gemini account
4. Close and "upgrade" to 1.46.x (rename profile to Beta).
5. Ensure that brave://flags/#brave-rewards-webui-panel is enabled (currently this is done via griffin study).
6. Verify that a notification badge is displayed on the Rewards icon. 
7. Open the Rewards panel.
8. Verify Japan is not available in the list.
9. Select the country your account is KYC'd for and click Continue.
10. Confirm "Thank you" message is displayed.
11. Close message and confirm panel information is shown.



<details>
<summary>Logs for step 9</summary>

```

```

Note, in above logs the 409 response and UI shown is expected per doc linked in https://github.com/brave/internal/issues/894.

</details>

</details>

<details>
<summary>Linked Wallet Case: Uphold - PASSED</summary>

1. Install 1.45.x (Release channel), relaunch to pull griffin seed.
2. Enable Rewards, claim UGP grant and ensure no notification badges shown on rewards icon.
3. Link KYC'd Uphold account
4. Close and "upgrade" to 1.46.x (rename profile to Beta).
5. Ensure that brave://flags/#brave-rewards-webui-panel is enabled (currently this is done via griffin study).
6. Verify that a notification badge is displayed on the Rewards icon. 
7. Open the Rewards panel.
8. Verify Japan is not available in the list.
9. Select the country your account is KYC'd for and click Continue.
10. Confirm "Thank you" message is displayed.
11. Close message and confirm panel information is shown.




<details>
<summary>Logs for step 9</summary>

```
```

Note, in above logs the 409 response and UI shown is expected per doc linked in https://github.com/brave/internal/issues/894.

</details>

</details>
