### ISSUE TITLE
Remove creator-set default tipping values logic

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#24548]
## Description

Currently, the browser will overwrite default tipping options from /parameters if the creator set their own set of default tipping values in the Creators app. With the custom tipping feature, however, these creator-set values no longer provide any real value.

We will be removing this option from the Creators app https://github.com/brave-intl/publishers/issues/3137, so we should remove related logic on the browser side that overwrites the Brave-suggested default tipping amounts to simplify logic.

**Comment by LaurenWags** [comment]
Verified with

```
Brave | 1.45.78 Chromium: 106.0.5249.65 (Official Build) beta (x86_64)
-- | --
Revision | 3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}
OS | macOS Version 12.6 (Build 21G115)
```

Verified test plan from https://github.com/brave/brave-core/pull/14605#issue-1337413642.

Compared 1.44.x which uses the creator set tip defaults to 1.45.x which removed them.
Confirmed in 1.45.x even if a creator has tip defaults set, the standard values are used in the tip banner.

1.44.x | 1.45.x
--- | ---
<img width="1192" alt="1 44 x" src="https://user-images.githubusercontent.com/28145373/193057123-78977fe2-da64-43d4-b97c-e13609fe5b36.png"> | <img width="1175" alt="1 45 x" src="https://user-images.githubusercontent.com/28145373/193056680-9cf090ba-2dc2-451b-82f4-fe40cd657d04.png">

Spot checked various creator types, confirmed they also use the default values:

Example | Example
---- | ----
<img width="1170" alt="GH" src="https://user-images.githubusercontent.com/28145373/193056540-17bee3e1-65c5-46b5-877a-13279e6da8de.png"> | <img width="1168" alt="Vimeo" src="https://user-images.githubusercontent.com/28145373/193056551-5f48f83f-3e9f-46c9-8a92-e01450e063d4.png">
