### ISSUE TITLE
Brave Rewards Ads UI should be disabled if BRAVE_ADS_ENABLED buildflag is not set

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#2455]
When BRAVE_ADS_ENABLED buildflag is not set, the toggle option on the ads box in settings should be unavailable as it was before the initial UI integration, so ads service cannot be interacted with.

**Comment by NejcZdovc** [comment]
closing as we don't need it

**Comment by ryanml** [comment]
closed via: https://github.com/brave/brave-core/pull/1057
