### ISSUE TITLE
Brave News Sources Migration

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#24550]
One of the issues we have with the Brave News V2 work is that we need to ensure that the user doesn't lose access to any of their subscriptions when we switch over to the new list of feeds (which doesn't contain all of the sources in the old feed list).

Our proposed solution here is to add the feeds which have disappeared, that the user was subscribed to to the user's direct feeds. This means, that for a while at least, we'll need to keep the old `sources.json` files available.

**Comment by fallaciousreasoning** [comment]
@petemill @aurangzaib048 for your thoughts

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (x86_64)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | macOS Version 11.7.1 (Build 20G918)

### Steps:
1. installed `1.46.81`
2. launched Brave
3. opened a new-tab page
4. scrolled down
6. clicked on `Show Brave News`
7. clicked on `Customize`
8. clicked on `Brave News`
9. clicked on `All Sources`
10. toggled `Hollywood Life` to `Enabled`
11. opened `brave://flags/`
12. set `brave://flags/#brave-news-v2` to `Enabled`
13. clicked on `Relaunch`
14. confirmed I was `Following` the `Hollywood Life` feed source

(But could *not* confirm it via Brave News feed.  Will continue investigating and file, if needed.)

example | example | example
---------|----------|---------
<img width="1312" alt="Screen Shot 2022-10-27 at 4 14 01 PM" src="https://user-images.githubusercontent.com/387249/198415969-4aa88a8d-b13e-4198-829b-97b79e212381.png"> | <img width="1312" alt="Screen Shot 2022-10-27 at 4 14 04 PM" src="https://user-images.githubusercontent.com/387249/198415974-0d326788-8d89-4c2e-a9a9-22cba9361dd6.png"> | <img width="1312" alt="Screen Shot 2022-10-27 at 4 16 01 PM" src="https://user-images.githubusercontent.com/387249/198415976-43c1c07f-5f4d-49f8-be5a-fde83fd5b73d.png">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.46.83 Chromium: 107.0.5304.68 (Official Build) beta (64-bit)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | Windows 11 Version 21H2 (Build 22000.1098)
```

Steps:

1. Install 1.46.83
2. opened a new-tab page
3. scrolled down
4. clicked on `Show Brave News`
5. clicked on `Customize`
6. clicked on `Brave News`
7. clicked on `All Sources`
8. toggled `Hollywood Life` to Enabled
9. opened `brave://flags/`
10. set `brave://flags/#brave-news-v2` to Enabled
11. clicked on Relaunch
12. click to open NTP
13. confirmed `Brave News` is still enabled
14. click `Customize`
15. click `Brave News`
16. new `Brave News UI` displayed

Confirmed `Hollywood Life` feed source displayed on the left panel of the Following section

step 4|step 8|step10|result
----|----|----|------
<img width="465" alt="image" src="https://user-images.githubusercontent.com/98358127/198746493-b0cbdfc6-717d-4735-b62c-7b9bbfad439d.png">|<img width="461" alt="image" src="https://user-images.githubusercontent.com/98358127/198746551-38879f14-d950-45c6-b294-8bfcf7f59045.png">|<img width="464" alt="image" src="https://user-images.githubusercontent.com/98358127/198746613-1afee924-b5af-47aa-844c-0095ea09d708.png">|<img width="462" alt="image" src="https://user-images.githubusercontent.com/98358127/198747017-f0dad68d-3f0e-4f82-ab38-aeef968ed2a9.png">

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.46.87 x64 beta build
- Verified steps from [ brave/brave-core#14565](https://github.com/brave/brave-core/pull/14565)
- Verified manually enabled source is listed under `Your sources` post migration


https://user-images.githubusercontent.com/17010094/199657735-6ac9c1c9-4c6e-46a2-bd71-19a185194c11.mp4

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.46.117 Chromium: 107.0.5304.110 (Official Build) beta (64-bit)
-- | --
Revision | 2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}
OS | Ubuntu 18.04 LTS

<details>

Steps:

1. Install 1.45.x
2. opened a new-tab page
3. scrolled down
4. clicked on `Show Brave News`
5. clicked on `Customize`
6. clicked on `Brave News`
7. clicked on `All Sources`
8. toggled `Hollywood Life` to Enabled
9. install 1.46.x
11. clicked on Relaunch
12. click to open NTP
13. confirmed `Brave News` is still enabled
14. click `Customize`
15. click `Brave News`
16. new `Brave News UI` displayed

Confirmed `Hollywood Life` feed source displayed on the left panel of the Following section

1.45.x
![image](https://user-images.githubusercontent.com/34715963/202966633-25090579-3221-49f4-8d59-e4258c86bfc5.png)

1.46.x
![image](https://user-images.githubusercontent.com/34715963/202966998-117b6f24-97a9-4cf1-95a0-e456ae37bdba.png)



</details>
