### ISSUE TITLE
Occasionally WebTorrent fails to load the first time you click on a link (refreshing fixes the issue).

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#24552]
## Steps to Reproduce

   1. Load a torrent (ie.https://webtorrent.io/torrents/big-buck-bunny.torrent)

## Actual result:
![image](https://user-images.githubusercontent.com/7678024/183797645-75eaaad4-bb6e-4d9c-9dc8-247039bd9ffb.png)

## Expected result:
![image](https://user-images.githubusercontent.com/7678024/183797677-fe1d74d1-c961-4f8c-aea6-aa2e30c6e706.png)

## Reproduces how often: 
Reproduces every time for the first page load on linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.44.44 Chromium: 104.0.5112.81 (Official Build) nightly (x86_64)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | macOS Version 11.6.8 (Build 20G730)

### Steps:
1. installed `1.44.44`
2. launched Brave
3. loaded `webtorrent.io/free-torrents`
4. clicked on both `magnet:?` and `Torrent` links

#### Confirmed correct layout and functionality

`magnet:?` | `.torrent`
------------|----------
<img width="1625" alt="Screen Shot 2022-08-15 at 3 43 27 PM" src="https://user-images.githubusercontent.com/387249/184733407-2385c0a9-d136-49e1-815f-f6adceece41b.png"> | <img width="1625" alt="Screen Shot 2022-08-15 at 3 43 19 PM" src="https://user-images.githubusercontent.com/387249/184733422-4ec62789-dc3b-48b7-a7c5-0b5618af45aa.png">

**Comment by MadhaviSeelam** [comment]
Verified `In progress` using
```
Brave | 1.44.70 Chromium: 105.0.5195.68 (Official Build) beta (64-bit)
-- | --
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | Windows 11 Version 21H2 (Build 22000.856)
```

Working as expected first time loading torrent (https://webtorrent.io/torrents/big-buck-bunny.torrent)  in `1.43.88` in `Win 11 x64`

Steps:

- installed 1.44.70
- launched Brave
- loaded `webtorrent.io/free-torrents`
- clicked on both `magnet:?` and `Torrent` links

 `(magnet:?)`|torrent
----|----
<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/187967593-1b9145c9-19f9-4789-884c-dcd604035961.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/187967624-2fbf765b-231a-4d95-9b73-d526b193fd8f.png">
