### ISSUE TITLE
Web site throwing "Culture is not supported" error and stops working

### ISSUE THREAD

**Issue by aseedig** [brave/brave-browser#24564]
## Description 
When working on an analytics dashboard website and try to export data to excel, the server responds with the following error:
"There was an error while processing your request.
The error was: Culture is not supported. Parameter name: name en-GB;q=0.8 is an invalid culture identifier."

It seems that the Language settings is adding the following parameters to the Request Header: "name en-GB;q=0.8"
This was working in previous Brave versions and I discovered this issue since Brave Version v1.42.86

## Steps to Reproduce
You would need access to the application to reproduce the issue. However, the Request Header contains the above mentioned parameter and this needs to be addressed. I might be able to grant access to an export function for trouble shooting purposes, but cannot give access here to the restricted internal application. This export function is working with:
- Chrome Version 104.0.5112.79 (Official Build) (x86_64)
- MS Edge: Version 104.0.1293.47 (Official build) (x86_64)

## Actual result:
![image](https://user-images.githubusercontent.com/13466676/183901220-92a7675d-a4f2-4fc7-a633-bdd5174c5974.png)

## Expected result:
<img width="1865" alt="image" src="https://user-images.githubusercontent.com/13466676/183901748-76675679-84bb-4828-acb9-ce0d388ed4a0.png">

## Reproduces how often: 
Easily reproducible... Just need access to the export function.

## Brave version (brave://version info)
Brave	1.42.88 Chromium: 104.0.5112.81 (Official Build) (x86_64) 
Revision	5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS	macOS Version 12.5 (Build 21G72)
JavaScript	V8 10.4.132.20
User agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36
Command Line	/Applications/Brave Browser.app/Contents/MacOS/Brave Browser --disable-domain-reliability --enable-dom-distiller --component-updater=url-source=https://go-updater.brave.com/extensions --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --variations-insecure-server-url=https://variations.brave.com/seed --enable-features --disable-features --flag-switches-begin --flag-switches-end
Executable Path	/Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path	/Users/aseedig/Library/Application Support/BraveSoftware/Brave-Browser/Default
Linker	lld
Active variations	AdRewardsStudy:NextPaymentDay
BraveAds.AdServingStudy:DefaultAdNotificationsPerHour=10/MaximumAdNotificationsPerDay=100/MaximumInlineContentAdsPerHour=12/MaximumInlineContentAdsPerDay=60/AdServingVersion=1
BraveAds.EpsilonGreedyBanditStudy:Default
BraveAds.FrequencyCappingStudy:ExcludeAdIfWithinTimeWindow=0h
BraveAds.UserActivityStudy:Triggers=NTPSI/TimeWindow=15m/Threshold=0.0/IdleTimeThreshold=5s
BraveDebounceStudy:Enabled
ConversionsStudy:NewDefaultPattern
Default1pBlockingStudy:Disabled
DisableReduceLanguage:Enabled
EphemeralStorageStudy:Enabled
ExtendedVariationsSafeMode5:SignalAndWriteViaFileUtil5
FirstPartyEphemeralDomainBlockStudy:Enabled
ForceDisableBlinkFeatures:Enabled
MacCoreLocationBackendStudy:Enabled
PartitionBlinkMemoryCacheStudy:Enabled
PartitionConnectionsByNetworkIsolationKeyStudy:Enabled
PermissionLifetimeReleaseStudy:Enabled
RequestAdsEnabledApiStudy:Enabled
SpeedreaderReleaseStudy:Enabled

## Version/Channel Information:

I only tested it with the current Official Build.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes.
- Does the issue resolve itself when disabling Brave Rewards? No.
- Is the issue reproducible on the latest version of Chrome? No.

**Comment by rebron** [comment]
@aseedig Do you have a pointer to the website/app where you're seeing this error?

**Comment by aseedig** [comment]
Not yet, but can produce something shortly. As mentioned, this is an internal analytics dashboard of an insurance company and I cannot share the data in the public. I can however make a test page accessible for testing and reproduction. Just wanted to know that someone is picking it up.

**Comment by pilgrim-brave** [comment]
Please and thank you.

**Comment by aseedig** [comment]
Hey guys,

please us the following URL for testing:
https://manager.hampshire4x4response.net/Application/rdPage.aspx?rdReport=ExportTest

Please let me know if you need anything else. 

I have set the debug mode to on, so you will see a lot of details in the data. but nothing points to the error apart the message that the Culture is not supported:
[Culture is not supported. Parameter name: name en-GB;q=0.9 is an invalid culture identifier.]

Disable Shields Up and the export works.

Thanks

Axel

**Comment by pilgrim-brave** [comment]
Thank you. I confirmed the bug and also confirmed that it is fixed already in nightly builds by <https://github.com/brave/brave-core/pull/14338>.

**Comment by pilgrim-brave** [comment]
Thanks very much for the bug report.  As I mentioned, it's fixed in nightly and so will be made available on all platforms shortly, in version 1.44. In the meantime, you can work around it by going into the shields panel, under Advanced Controls, change "Block fingerprinting" to "Allow fingerprinting" for this site. (You don't need to disable "Shields Up" entirely.)

Thank you very much for taking the time to report the bug and helping us get this sorted; it's greatly appreciated. I am checking if there is anything i can do to get to fix shipped faster, but worst case know it'll be in version 1.44.

**Comment by aseedig** [comment]
Great news. Thank you for taking this on and resolve it so quickly.
Great work.

Axel

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.45.49 Chromium: 105.0.5195.127 (Official Build) nightly (x86_64)
-- | --
Revision | 912488396852bf658ab32465980c0b93a3c27a83-refs/branch-heads/5195@{#1109}
OS | macOS Version 13.0 (Build 22A5342f)

**NOTE**: could **not** reproduce the issue as filed using `1.43.89 Chromium: 105.0.5195.102`

### Steps:
1. installed `1.45.49`
2. launched Brave
3. ensured `Prevent sites from fingerprinting me in `brave://settings/shields`
4. loaded `https://manager.hampshire4x4response.net/Application/rdPage.aspx?rdReport=ExportTest`

#### Confirmed I was able to load and export the data without issue/exceptions in the JavaScript `Console` panel

example | example | example | example
---------|----------|---------|---------
<img width="1312" alt="Screenshot 2022-09-14 at 5 28 37 PM" src="https://user-images.githubusercontent.com/387249/190286274-5bc03768-9159-4b3a-aa01-3fdf7dd698d3.png"> | <img width="1312" alt="Screenshot 2022-09-14 at 5 28 41 PM" src="https://user-images.githubusercontent.com/387249/190286279-f3174143-8459-4e12-9887-31708969a4c1.png"> | <img width="1312" alt="Screenshot 2022-09-14 at 5 28 51 PM" src="https://user-images.githubusercontent.com/387249/190286282-0d24313a-ee88-4d15-941d-7d1b565a70d2.png"> | <img width="1312" alt="Screenshot 2022-09-14 at 5 30 58 PM" src="https://user-images.githubusercontent.com/387249/190286284-f73d99f4-918d-40be-8749-db4eb25b5433.png">

**Comment by aseedig** [comment]
Hi Stephen,

 

Thank you for the info. The exception is because the test page doesn’t log in to the system and the Logo is based on the customer ID. Hence the Link to the JPG file is incomplete and triggers the exception.

Nothing to do with the actual report, just a cosmetic issue not showing the customer logo.

 

Thanks again for your help.

 

Best


Axel

 

From: Stephen Donner ***@***.***>
Reply to: brave/brave-browser ***@***.***>
Date: Thursday, 15 September 2022 at 01:34
To: brave/brave-browser ***@***.***>
Cc: Axel Seedig ***@***.***>, Mention ***@***.***>
Subject: Re: [brave/brave-browser] Web site throwing "Culture is not supported" error and stops working (Issue #24564)

 
Verified PASSED using
Brave1.45.49 Chromium: 105.0.5195.127 (Official Build) nightly (x86_64)
Revision912488396852bf658ab32465980c0b93a3c27a83-refs/branch-heads/5195@{#1109}
OSmacOS Version 13.0 (Build 22A5342f)

NOTE: could not reproduce the issue as filed using 1.43.89 Chromium: 105.0.5195.102
Steps:
installed 1.45.49
launched Brave
ensured Prevent sites from fingerprinting me in brave://settings/shields`
loaded https://manager.hampshire4x4response.net/Application/rdPage.aspx?rdReport=ExportTest
Confirmed I was able to load and export the data without issue/exceptions in the JavaScript Console panel
exampleexampleexampleexample
