### ISSUE TITLE
Gemini wallet integration fails: Invalid region?

### ISSUE THREAD

**Issue by gergo-szabo** [brave/brave-browser#24563]
## Description 
I tried to integrate a "newly" installed browser to my Gemini account for Brave Rewards.

## Steps to Reproduce
1, brave://rewards/
2, reward stat area has a Not authenticated (or similar, translated) button
3, Selecting Gemini account
4, Gemini asks: Brave Browser is requesting access to your Primary account -> Allow
5, After brief processing an error message appears

## Actual result:
Rough translation from my native language:

Error: region not supported
Unfortunately, we were unable to verify your Brave Rewards as your region is currently not supported for Brave Rewards authentication.

## Expected result:
Gemini wallet integrated

## Reproduces how often: 
All the time for this new installlation

## Brave version (brave://version info)
1.38.111 Chromium: 101.0.4951.54 (Hivatalos verzió) (64 bites)
67da1aeb32cedd27634ca6634fb79cbd85d3f0ab-refs/branch-heads/4951@{#1126}
Linux

## Other Additional Information:
The Gemini wallet has been integrated before. BAT was transfered to it.

**Comment by zeeshan1212** [comment]
Getting the same issue for me as well, my region is not there in the unsupported regions list from the braves site, still getting the error.

**Comment by Miyayes** [comment]
Hello, kindly check this list for support regions: https://support.brave.com/hc/en-us/articles/6539887971469
