### ISSUE TITLE
Support editing network details for Solana and Filecoin

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#24569]
Mainly for users to be able to customize their block explorer url, and probably JSON RPC URL too. cc @jamesmudgett 
We should probably consider have separate sections for EVM, Solana, Filecoin networks in the settings UI with section titles, and only allow user to edit a subset of network fields (such as block_explorer_url, JSON RPC URL) only, things like changing chain_id doesn't make sense in Solana and Filecoin.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (64-bit)
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | Linux

- Verified steps from [ brave/brave-core#14879](https://github.com/brave/brave-core/pull/14879)
- Verified Filecoin and Solana networks are listed in their own section
- Verified able to edit existing default networks
- Verified able to reset edit to defaults
- Verified Ethereum defaults works as expected
- Verified Chain ID field is ready only so can't be edited

https://user-images.githubusercontent.com/17010094/195783749-75d5fbfd-f738-4064-a52b-ead5352a5a94.mp4


----------------
Verification passed on 

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (64-bit)
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | Windows 11 Version 21H2 (Build 22000.978)

- Verified steps from [ brave/brave-core#14879](https://github.com/brave/brave-core/pull/14879)
- Verified Filecoin and Solana networks are listed in their own section
- Verified able to edit existing default networks
- Verified able to reset edit to defaults
- Verified Ethereum defaults works as expected
- Verified Chain ID field is ready only so can't be edited

https://user-images.githubusercontent.com/17010094/195778435-a13776aa-da1e-4f69-8e98-48232b57a2d7.mp4


----------------
Verification passed on 

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (arm64)
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | macOS Version 12.6 (Build 21G115)

- Verified steps from [ brave/brave-core#14879](https://github.com/brave/brave-core/pull/14879)
- Verified Filecoin and Solana networks are listed in their own section
- Verified able to edit existing default networks
- Verified able to reset edit to defaults
- Verified Ethereum defaults works as expected
- Verified Chain ID field is ready only so can't be edited

https://user-images.githubusercontent.com/17010094/195779737-52d9d805-87cd-4029-9c4f-d1a5b22da7c7.mov
