### ISSUE TITLE
Connect VPN tunnel automatically after split tunnel

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#24576]
This issue is the follow up issue to https://github.com/brave/brave-browser/issues/22938. With this issue we start the tunnel right away after split tunnel change without user interaction.

**Comment by Uni-verse** [comment]
Verification in progress on `Samsung Galaxy S21` running `Android 12` using the following build(s): 

```
Brave	1.43.83 Chromium: 105.0.5195.68 (Official Build) (64-bit) 
Revision	ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS	Android 12; Build/SP1A.210812.016
```
Testing based on Test Plan in https://github.com/brave/brave-core/pull/14581#issue-1335192616

**Default State:** 
- Verified split tunneling is not enabled if there is no `VPN profile` installed.
- Verified split tunneling is not enabled if user resets configuration via `Settings` > `Brave Firewall + VPN` > `Reset Configuration`
<img width="200" alt="0" src="https://user-images.githubusercontent.com/17885425/187262910-afa1d891-861e-448c-a410-809b1cf88063.png">

**Split Tunneling when VPN Enabled:** 
- Confirmed when user excludes apps from the VPN under `Split Tunneling` option, profile is automatically updated without user interaction, connection is not interrupted.
- Confirmed user is abled to `remove` apps from the `Excluded Apps` list. It will only take effect if user saves. 
- Confirmed apps that user adds to `Excluded Apps` on Split tunneling page will bypass the VPN.
- Confirmed that apps will not be `saved` if user selects apps into `Excluded Apps` list but closes page without saving.
- Confirmed that toggling the VPN off/on via the settings menu, notification tray or the brave hamburger menu will not change state of the `Excluding Apps` list.
- Confirmed when user hits show system apps CTA, system apps list will populate.
- Confirmed user is able to add `25 items` into Exclude Apps list under Split Tunneling.

**Selected Host location** | **Excluded App** | **Included App**
-|-|-
![screenshot-1661790374174](https://user-images.githubusercontent.com/17885425/187265157-e8e4b251-926d-4578-910a-fc7c911641e0.png) | ![screenshot-1661790169134](https://user-images.githubusercontent.com/17885425/187265597-bba5beec-637a-49fe-8767-cd391ab69651.png) | ![screenshot-1661790362022](https://user-images.githubusercontent.com/17885425/187265601-da526664-8549-43cd-848e-67e956869da5.png)

Split Tunneling when VPN Disabled: 
- Confirmed user is able to app/remove apps to the `Excluded Apps` list when VPN is disabled. Enabling VPN will automatically launch new profile, establish connection. 
- Confirmed user is able to add/remove system apps from `Exluded Apps` list. 
- Confirmed user is able to remove all apps previous saved from the Excluded list successfully.

Example | Example | Example
-|-|-
![screenshot-1661789922095](https://user-images.githubusercontent.com/17885425/187267165-9b4926fc-ea72-4a95-a271-062224164beb.png) | ![screenshot-1661789931063](https://user-images.githubusercontent.com/17885425/187267167-be6c7a75-7935-4a52-978c-cbb579bcadb8.png) | ![screenshot-1661789943419](https://user-images.githubusercontent.com/17885425/187267168-e23c5006-c57f-4cfe-9c1e-b27b83bcd8c5.png)

**Comment by Uni-verse** [comment]
Verification in progress on `Samsung Galaxy Tab S7` running `Android 12` using the following build(s):

Brave	1.43.83 Chromium: 105.0.5195.68 (Official Build) (64-bit) 
Revision	ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS	Android 12; Build/SP1A.210812.016
