### ISSUE TITLE
Unable to import saved passwords from Vivaldi

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#24578]
## Description 

Unable to import saved passwords from Vivaldi

## Steps to Reproduce

1. install latest `stable`-channel Vivaldi
2. log in to a few sites, saving passwords for each (I did `github.com`, `gmail.com`, `facebook.com, and `fill.dev``
3. shut down Vivaldi
4. install Brave `1.44.34`
5. launch Brave
6. click on `Skip welcome tour`
7. click on `Import bookmarks now...`
8. select `Vivaldi Person 1`
9. note that the list includes `Saved passwords`
10. click `Import`
11. click `Done`
12. load `brave://settings/passwords`
13. look for passwords

## Actual result:

No imported passwords

<img width="1312" alt="Screen Shot 2022-08-10 at 3 55 31 PM" src="https://user-images.githubusercontent.com/387249/184042376-a6e4b04f-e3d9-4732-92d6-780e3a6fea07.png">

## Expected result:

Should import all 4 Vivaldi-saved passwords

<img width="1552" alt="Screenshot 2022-08-10 at 4 55 10 PM" src="https://user-images.githubusercontent.com/387249/184042600-e637433c-04ea-47d5-b0fc-16d26095f488.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.44.34 Chromium: 104.0.5112.81 (Official Build) nightly (x86_64)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | macOS Version 13.0 (Build 22A5321d)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@bsclifton @spylogsster @rebron @MadhaviSeelam

**Comment by stephendonner** [comment]
Cross-reference this for Opera; maybe the same reason (likely, given Chromium-based?)

https://github.com/brave/brave-browser/issues/24130

**Comment by rebron** [comment]
@spylogsster We may need to add additional UX specific to importing passwords for macOS.
cc: @aguscruiz see examples below from Edge.

<img width="420" alt="Screenshot 2022-08-12 at 10 32 22 AM" src="https://user-images.githubusercontent.com/5951041/184412771-b5eda56c-b748-4b75-b530-a0813f9d3db9.png">
<img width="862" alt="Screenshot 2022-08-12 at 10 32 55 AM" src="https://user-images.githubusercontent.com/5951041/184412777-ca909811-e8f9-4a71-b984-f03c541c07bb.png">

**Comment by spylogsster** [comment]
> to add additional UX specific to importing passwords for macOS.

Moved to separate issue https://github.com/brave/brave-browser/issues/24666 as discussed in Slack with @rebron

**Comment by kjozwiak** [comment]
The above will require `1.43.77` or higher for `1.43.x` verification 👍

**Comment by LaurenWags** [comment]
Updated to `release-notes/exclude` as this is a follow up to the original implementation of Vivaldi import which will be included in the release notes via https://github.com/brave/brave-browser/issues/23704)).

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.43.91 Chromium: 105.0.5195.102 (Official Build) (64-bit)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | Windows 11 Version 21H2 (Build 22000.856)
```
Working as expected and can not reproduce the issue using original STR  https://github.com/brave/brave-browser/issues/24578#issue-1335323389 in Win 11 x64 in `1.44.34`

Confirmed this issue still works as expected as  passwords are successfully imported from Vivaldi 

![image](https://user-images.githubusercontent.com/98358127/189417800-f537164a-d838-45d4-995d-0b86a250d934.png)

**Comment by aguscruiz** [comment]
> @spylogsster We may need to add additional UX specific to importing passwords for macOS. cc: @aguscruiz see examples below from Edge.
> 
> <img alt="Screenshot 2022-08-12 at 10 32 22 AM" width="420" src="https://user-images.githubusercontent.com/5951041/184412771-b5eda56c-b748-4b75-b530-a0813f9d3db9.png">
> 
> <img alt="Screenshot 2022-08-12 at 10 32 55 AM" width="862" src="https://user-images.githubusercontent.com/5951041/184412777-ca909811-e8f9-4a71-b984-f03c541c07bb.png">

We should be able to use our current dialogs for this issue, right? I think there's no need to mock it up unless there's something I'm missing
