### ISSUE TITLE
[Android] Unify responsive Rewards settings page with Android

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#24570]
## Description

Use unified responsive Rewards settings page on Android.

Related to https://github.com/brave/brave-browser/issues/16619.

cc: @deeppandya

**Comment by LaurenWags** [comment]
@srirambv @Uni-verse please be sure to see the test plan in https://github.com/brave/brave-core/pull/14604#issue-1337318897 and ensure the brave://rewards page is tested thoroughly on Android devices (ARM and Tablet).

As for desktop testing, a single platform is sufficient to do the testing of desktop specific areas listed in https://github.com/brave/brave-core/pull/14604#issue-1337318897 cc @GeetaSarvadnya

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```

Brave | 1.45.78 Chromium: 106.0.5249.65 (Official Build) beta (64-bit)
-- | --
Revision | 3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}
OS | Windows 10 Version 21H2 (Build 19044.2006)

```

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress on `Vivo X70 Pro version 12` running `Bravemonoarm.aok_1.45.106` 
 
- Verified the test plan from https://github.com/brave/brave-core/pull/14604#issue-1337318897

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress on `Android Tab A7` version 12 running `Bravemonoarm64.apk_1..45.106`
