### ISSUE TITLE
Page CSP can block Reader Mode stylesheet

### ISSUE THREAD

**Issue by Seirdy** [brave/brave-browser#24577]
## Description 

A site's content-security-policy can block the Reader Mode's inline CSS from loading if the CSP uses a hash.

## Steps to Reproduce

   1. Navigate to any page on https://seirdy.one/
   2.  Open the Console in DevTools
   3.  Activate Reader Mode

## Actual result:

The CSS for Reader Mode is not applied; the page is completely unstyled. The console reports the following error:

<pre><samp>Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'sha256-yeoa9pw7t4Un85jGWHQcNLZ8XpPN6AiUnk6+8tiGT44='". Either the 'unsafe-inline' keyword, a hash ('sha256-/zANq2Ot1HS0JMxZ4NpGDtN5wIJOxobb5Rqjx9AKsCU='), or a nonce ('nonce-...') is required to enable inline execution.</samp></pre>

## Expected result:

Expected Reader Mode to function normally and render styled, as it does in other desktop browsers (Firefox, Safari, Edge, Vivaldi, Chromium with DOM Distiller, etc).

## Reproduces how often: 

Easily + consistently reproducible.

## Brave version (info found on brave://version)

1.44.31 Chromium: 104.0.5112.81 (Official Build) nightly (64-bit)

## Version/Channel Information:

I have only attempted to reproduce this issue on the Nightly channel. I first noticed the issue a month ago and reproduced it just now, so it should have tricked down to other channels by now.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? **No.**
- Does the issue resolve itself when disabling Brave Rewards? **No.**
- Is the issue reproducible on the latest version of Chrome?  **No.**

## Miscellaneous Information:

The full CSP that triggers this issue:

<pre><samp>content-security-policy: default-src 'none';img-src 'self';style-src 'sha256-yeoa9pw7t4Un85jGWHQcNLZ8XpPN6AiUnk6+8tiGT44=';frame-ancestors 'none';base-uri 'none';form-action https://seirdy.one/webmentions/receive https://seirdy.one/search/;manifest-src 'self';webrtc 'block';upgrade-insecure-requests;sandbox allow-same-origin allow-forms</samp></pre>

The exact hash is subject to change if/when I update my site's stylesheet.

**Comment by Seirdy** [comment]
Other functionality broken by page CSPs: https://github.com/brave/brave-browser/issues/24577

This issue can also be reproduced on <https://grapheneos.org/articles/grapheneos-servers>. This isolates the offending CSP directive to a `style-src` which does *not* allow `unsafe-inline`.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.64.81 Chromium: 122.0.6261.43 (Official Build) beta (x86_64)
-- | --
Revision | 19b9ce86d7aed2a1fdb7734d6a27f2fe6abd0153
OS | macOS Version 14.4 (Build 23E5205c)
```

### Steps:
1. installed `1.64.81`
2. launched Brave
3. loaded `https://seirdy.one/` and clicked on an `archive` entry
4. clicked on `Turn on Speedreader`
5. did the same for `https://grapheneos.org/articles/grapheneos-servers`

### Confirmed Speedreader ("Reader mode") activated and rendered fine

example | example
---------|---------
<img width="1556" alt="Screenshot 2024-02-21 at 11 54 24 AM" src="https://github.com/brave/brave-browser/assets/387249/c86966f4-0087-4ed3-be37-4342008cb2e9"> | <img width="1669" alt="Screenshot 2024-02-21 at 11 54 39 AM" src="https://github.com/brave/brave-browser/assets/387249/047c6ad5-547a-4e5c-8216-09600984d322">

example | example
---------|---------
<img width="1669" alt="Screenshot 2024-02-21 at 11 57 49 AM" src="https://github.com/brave/brave-browser/assets/387249/8a53bc4a-800f-4246-855a-82e778e3343f"> | <img width="1669" alt="Screenshot 2024-02-21 at 11 57 53 AM" src="https://github.com/brave/brave-browser/assets/387249/14a6ddef-8603-4c07-b75e-73dd9e885181">
