### ISSUE TITLE
Payout pending and payout processing messages are shown in two different places at the same time

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#24584]
## Description 
Found while testing https://github.com/brave/brave-browser/issues/23429
Payout pending and payout processing messages are shown in two different places at the same time

## Steps to reproduce 

   1. Clean profile 1.43.67
   2. Enable rewards
   3. View couple of ads and reconcile ads with server
   4. Close the browser
   5. Set the system date one day prior to payout date (I have set the date to 7th Sep as payout date is 8th Sep)
   6. Relaunch the browser
   7. Open brave://rewards setting page
   8. Payout processing message is shown in rewards settings page
   9. Open ads panel
   10. Payout pending message is shown

**Note:** looks like the processing message which is shown in rewards settings page is hardcoded. This is shown in case 1. when payout pending condition is triggered case 2. when payout processing condition is triggered. It make sense it case 2, but in case 1 it doesn't.

## Actual result 
Payout pending and payout processing messages are shown in two different places at the same time

Settings page | Ads panel
-- | --
![Screenshot_20220907-171812_Brave - Beta](https://user-images.githubusercontent.com/38657976/184120470-9a7c0b0c-2331-43c1-b782-f05610f2f54c.jpg) | ![Screenshot_20220907-171819_Brave - Beta](https://user-images.githubusercontent.com/38657976/184120517-a7bd8fab-85bf-4265-bb3d-f0d207627179.jpg)

## Expected result
Payout processing message should not be shown in rewards settings page when pending payout condition is triggered

## Issue reproduces how often 

Easy
## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes 
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: Version 11
   
## Brave version
1.43.67

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @Miyayes @brave/qa-team @deeppandya

**Comment by emerick** [comment]
@GeetaSarvadnya Could you check if this is an existing bug in 1.42 as well? I suspect it may be.

**Comment by GeetaSarvadnya** [comment]
The issue exists in Desktop also hence updating title and OS label in the issue. 

![image](https://user-images.githubusercontent.com/38657976/184382316-b6eef881-d343-42be-afe0-ed37957431f5.png)

**Comment by GeetaSarvadnya** [comment]
@emerick The issue is **NOT** reproducible in `1.42.88`, verified with both nonverified and uphld custodian connected

**nonverified:**
![image](https://user-images.githubusercontent.com/38657976/184394640-08f6efbf-9370-4eef-90cc-e076a970afe4.png)

**uphold custodian connected**
![image](https://user-images.githubusercontent.com/38657976/184394792-b46546dc-7230-40ce-a8d4-3aefa30c1fc6.png)

**Comment by kjozwiak** [comment]
The above will require `1.43.76` or higher for `1.43.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress 

```
Brave | 1.43.78 Chromium: 104.0.5112.102 (Official Build) beta (64-bit)
-- | --
Revision | 8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}
OS | Windows 10 Version 21H2 (Build 19044.1889)

```

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on `Samsung Galaxy Tab A7 version 11` running `Bravemonoarnx64.apk_1.43.78` 


- Confirmed `payment status` banner is not shown on the rewards summary on setting page
- Confirmed `payout pending` and `payout processing` messages are NOT shown in two different places at the same time
- Confirmed `payout pending` banner message is shown in the `rewards settings page`, `BR panel`, `NTP` and `BR panel on the website` 

**_unverified (non custodian connected)_**
![Screenshot_20220907-205911_Brave_-_Beta 1](https://user-images.githubusercontent.com/38657976/185946708-6995af8a-aecf-4a7c-9522-bb571d553715.jpg)



**_Uphold custodian connected_**

Example | Example | Example | Example
-- | -- | -- | --
