### ISSUE TITLE
scripts/upload.py: fix env var reference in instructions

### ISSUE THREAD

**Issue by bkero** [brave/brave-browser#246]
## Description 

The upload.py script has a reference to a BRAVE_GITHUB_TOKEN environment variable that is not used (anywhere AFAICT). Right above that, the GITHUB_TOKEN environment variable is used. This reconciles those two lines.

## Steps to Reproduce

   1. Clone the repository
   2. Build a dist
   3. Try to upload

 ## Actual result:
GITHUB_TOKEN not defined

## Expected result:
Dist is uploaded as release

## Reproduces how often: 

Consistently

## Brave version (about:brave info)

Latest

### Reproducible on current release:

Yes

**Comment by bbondy** [comment]
Fixed by @bkero here:
https://github.com/brave/brave-core/commit/f75096c130877b7332aeb81c6f69b6c04fc28e15#diff-a1d80e606253fa3360d6b276ea70bef2
