### ISSUE TITLE
[ads] Transition ad history and reactions from `client.json` to a more efficient data approach

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#24604]

**Comment by btlechowski** [comment]
Verified with

Brave | 1.70.109 Chromium: 128.0.6613.138 (Official Build) beta (64-bit)
-- | --
Revision | fec4422ae56f4d9680c71a3c1de60b9a8e5ef32f
OS | Linux


#### Like

<details>



Verified is highlighted
![image](https://github.com/user-attachments/assets/462a5ba5-12d6-42d9-948b-8f8ab380ebf4)

Verified reaction is saved:
```
            "reactions": {
                "ads": {
                    "93130af3-2def-4ecb-b836-b3772e73b3c9": 1
                }
            },
```

</details>

#### Dislike

<details>



Verified is highlighted
![image](https://github.com/user-attachments/assets/39527628-d17b-4dd2-b043-d7552c7b2a6e)

Verified advertiser is blocked
```
            "reactions": {
                "ads": {
                    "93130af3-2def-4ecb-b836-b3772e73b3c9": 2
                }
            },
```
```
[20218:20218:0917/091935.351888:VERBOSE1:eligible_inline_content_ads_v2.cc(40)] Get eligible inline content ads
[20218:20218:0917/091935.355612:VERBOSE2:exclusion_rules_base.cc(100)] advertiserId 93130af3-2def-4ecb-b836-b3772e73b3c9 excluded due to being disliked

```

</details>

#### Mark as inappropriate


<details>



Verified is highlighted
![image](https://github.com/user-attachments/assets/6bd94ec7-0b67-4ffb-9e2a-2638250b9c68)

Verified is blocked
```
            "reactions": {
                "ads": {},
                "marked_as_inappropriate": ["8b848823-c47f-43de-a753-2efa8dea6863"]
            },
```
```
[20218:20218:0917/092141.983411:VERBOSE1:eligible_inline_content_ads_v2.cc(40)] Get eligible inline content ads
[20218:20218:0917/092141.984111:VERBOSE2:exclusion_rules_base.cc(100)] creativeSetId 8b848823-c47f-43de-a753-2efa8dea6863 excluded due to being marked as inappropriate

```


</details>

#### Save

<details>


Verified highlighted
![image](https://github.com/user-attachments/assets/cefb1997-e443-42e7-8bae-40cbe68476c2)

```
            "reactions": {
                "ads": {},
                "marked_as_inappropriate": [],
                "saved_ads": ["22110568-4125-4b84-b97a-27ef45c5c07c"]
            },
```


</details>

#### Heart segment


<details>



![image](https://github.com/user-attachments/assets/a4331f87-2089-45b7-9003-8e28c1ac6b0c)

```
            "reactions": {
                "ads": {},
                "marked_as_inappropriate": [],
                "saved_ads": [],
                "segments": {
                    "untargeted": 1
                }
            },
```


</details>


#### Block segment


<details>



![image](https://github.com/user-attachments/assets/77ff8be1-7e14-462b-ac35-c0d276726a61)

```
            "reactions": {
                "ads": {},
                "marked_as_inappropriate": [],
                "saved_ads": [],
                "segments": {
                    "untargeted": 2
                }
            },
```

Verified segment is blocked:
```
[20218:20218:0917/092143.235191:VERBOSE1:eligible_inline_content_ads_v2.cc(40)] Get eligible inline content ads
[20218:20218:0917/092143.236522:VERBOSE2:exclusion_rules_base.cc(100)] creativeSetId 8b848823-c47f-43de-a753-2efa8dea6863 excluded due to untargeted segment being marked to no longer receive ads

```

</details>

#### Ads history

<details>

Verified ads history is retained after browser restart

</details>

#### Upgrade from 1.69.x

<details>

Verified ads history is retained

1.69.x | 1.70.x
--|--
![image](https://github.com/user-attachments/assets/98f16600-3bf3-45a7-b78d-3318778457dc)|![image](https://github.com/user-attachments/assets/6ada8603-f3fd-48f0-a9aa-ae8658b28582)


Verified reactions are wiped. 

</details>
