### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by rafael-atias** [brave/brave-browser#24615]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.42.88  Chromium: 104.0.5112.81
Operating System: Windows NT 10.0.19044

**URL (if applicable) where crash occurred: **
It has ocurred with these URLs
- https://support.brave.com/hc/en-us/articles/360059254971-What-do-the-connection-error-codes-mean-
- https://keskonmangemaman.blogspot.fr/2017/09/bolognese-au-tofu-aux-olives-et-au.html

**Can you reproduce this crash?** Yes, I think so

**What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)**
1. Open a new tab in Brave browser
2. Paste the link https://support.brave.com/hc/en-us/articles/360059254971-What-do-the-connection-error-codes-mean-
3. Press Enter

As context, Brave has been crashing lately and is almost unusable. That's why I was searching on Brave Search the term: `brave error e6152ae7-b87a-46c7-8f38-9301ecd6c7ab` (e6152ae7-b87a-46c7-8f38-9301ecd6c7ab was the code `brave://crashes/` gave to the error). 

Brave shut down even when trying to open the link that caused the crash in a new tab, a new window and even a private window.

I uninstalled all the extensions, but the crashes still happen.

I don't know if it makes a difference, but I could open on Brave Beta the [second link](https://keskonmangemaman.blogspot.fr/2017/09/bolognese-au-tofu-aux-olives-et-au.html) that crashed the regular Brave...

However, when trying to open the [first link](https://support.brave.com/hc/en-us/articles/360059254971-What-do-the-connection-error-codes-mean-) on Brave Beta, I got this error:

> This webpage has a redirect loop / ERR_TOO_MANY_REDIRECTS
>
> You'll see this error when the page has tried to redirect you too many times. Sometimes, pages don't open because cookies aren't working correctly. To fix the error, try [clearing cookies](https://support.brave.com/hc/en-us/articles/360048833872).
> 
> This site can't provide a secure connection; network-error sent an invalid response / ERR_SSL_FALLBACK_BEYOND_MINIMUM_VERSION
> 
> You'll see this error if the page had an error that Brave couldn't understand. To fix the error, contact the website owner.
> 
> You'll see this error if the page had an error that Brave couldn't understand. To fix the error, contact the website owner. If you own this website, learn how to fix the [ERR_SSL_FALLBACK_BEYOND_MINIMUM_VERSION error](https://developers.google.com/web/updates/2016/03/chrome-50-deprecations#remove-insecure-tls-version-fallback).
> 
> ERR_CERT_SYMANTEC_LEGACY
> 
> If the error mentions Symantec, ask the site owner to update the site's certificate.
> 
> "Your connection is not private," "NET::ERR_CERT_AUTHORITY_INVALID," "ERR_CERT_COMMON_NAME_INVALID," "NET::ERR_CERT_WEAK_SIGNATURE_ALGORITHM," “ERR_CERTIFICATE_TRANSPARENCY_REQUIRED," or "SSL certificate error"
> 
> If the error mentions HSTS, privacy certificates, or invalid names,try the following steps:
> 
> Step 1: Sign in to the portal
> Wi-Fi networks at places like cafes or airports need you to sign in. To see the sign-in page, visit a page that uses http://.
> 
> Go to any website starting withhttp://, likehttp://example.com/.
> On the sign-in page that opens, sign in to use the internet.
> Step 2: Open the page in Incognito mode (computer only)
> Open the page you were visiting in a[Private window](https://support.brave.com/hc/en-us/articles/360017840332-What-is-a-Private-Window-).
> 
> If the page opens, an extension isn't working right. To fix the error, disable the extension.
> 
> Step 3: Update your operating system
> Make sure your device is up-to-date on [Windows](https://support.microsoft.com/help/14162/windows-service-pack-and-update-center),[Mac](https://support.apple.com/HT201541), or another operating system.
> 
> Step 4: Temporarily turn off your antivirus
> You'll see this error if you have antivirus software that provides "HTTPS protection" or "HTTPS scanning." The antivirus is preventing Brave from providing security.
> 
> To fix the problem, turn off your antivirus software. If the page works after turning off the software, turn off this software when you use secure sites.
> 
> Remember to turn your antivirus program back on when you're done.
> 
> Connect to network
> 
> You'll see this error if you're using a Wi-Fi portal where you have to sign in before you can get online. To fix the error, click Connect on the page you try to open.
> 
> Your clock is behind / Your clock is ahead / NET::ERR_CERT_DATE_INVALID
> 
> You'll see this error if your computer or mobile device's date and time are inaccurate. To fix the error, open your device's clock. Make sure the time and date are correct.
> 
> Server has a weak ephemeral Diffie-Hellman public key / ERR_SSL_WEAK_EPHEMERAL_DH_KEY
> 
> You'll see this error if you try to go to a website with an outdated security code. Brave protects your privacy by not letting you connect to these sites. If you own this website, try to update your server to support ECDHE and turn off DHE. If ECDHE is unavailable, you can turn off all DHE cipher suites and use plain RSA.
> 
> This webpage is not available / ERR_SSL_VERSION_OR_CIPHER_MISMATCH
> 
> You'll see this error if you try to go to a website with an outdated security code. Brave protects your privacy by not letting you connect to these sites. If you own this website, try to set your server to use TLS 1.2 and TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, instead of RC4. RC4 is no longer considered secure. If you can't turn off RC4, make sure that other non-RC4 ciphers are turned on.
> 
> Software on your computer is stopping Brave from safely connecting to the web (Windows computers only)
> 
> You'll see this error if you have Superfish software on your Windows computer. To remove this software from your computer:
> 
> On your Windows computer, open Brave.
> Go to [Lenovo's support page for this problem](https://support.lenovo.com/product_security/ps500066).
> Click Download SuperFish Removal Tool. At the bottom, click the filename (Lenovo.SuperFishRemovalTool.exe).
> Follow the onscreen instructions.
> Delete Expired DigiCert Certificate (Mac computers only)
> 
> You'll see this error if the page uses a certificate that isn't set up right on your computer. To fix the error, try these tips:
> 
> On your Mac computer, at the top right, click Spotlight search Search.
> Enter "Keychain Access."
> In the results, click Keychain Access.
> At the top of your computer screen, click View and then Show Expired Certificates.
> At the top right, click Search Search.
> Enter "DigiCert High" and press Enter on your keyboard.
> Find "DigiCert High Assurance EV Root CA" that's marked as Expired Expired. Click the certificate.
> Press Delete on your keyboard.
> Did you mean [site name]?
> 
> You’ll see this message if the link you opened goes to a site with a slightly different name from one you usually visit. Brave will ask if you want to go to the site you usually visit.
> 
> Click the name of the site or Continue to go to the site Brave suggests.
> Click Ignore to continue to the link you opened.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/13330100-f3fb-a908-0000-000000000000

**Comment by rebron** [comment]
@rafael-atias Do you have Speedreader enabled? brave://settings/appearance

**Comment by rafael-atias** [comment]
@rebron  Yes, it was enabled

With SpeedReader disabled, I can confirm that **Brave can open the web pages that caused the crash**.

After navigating to the [support Brave page](https://support.brave.com/hc/en-us/articles/360059254971-What-do-the-connection-error-codes-mean-), if I enable SpeedReader the browser crashes.

**Comment by iefremov** [comment]
This was fixed at some point
