### ISSUE TITLE
Update UD toggle wording in brave://settings/extensions

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#24622]
We don't use DoH anymore
brave://settings/extensions
![image](https://user-images.githubusercontent.com/168356/184292012-e4538fe2-928d-4aa0-8170-352d9fe4ee1f.png)

**Comment by supermassive** [comment]
@jamesmudgett @yrliou 
Can you help with proper wording here, please?

**Comment by yrliou** [comment]
@supermassive just `Learn More about Ethereum privacy considerations.` seems fine to me.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.45.74 Chromium: 106.0.5249.55 (Official Build) beta (x86_64)
-- | --
Revision | 4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}
OS | macOS Version 11.7 (Build 20G817)

#### Confirmed the wording has been updated to `Learn More about Ethereum privacy considerations.`

<img width="1429" alt="Screen Shot 2022-09-26 at 6 26 13 PM" src="https://user-images.githubusercontent.com/387249/192391693-5fbef933-a55d-40a2-9d8d-f3f727f0ea18.png">
