### ISSUE TITLE
Allow picking the Authenticode code signing certificate by hash

### ISSUE THREAD

**Issue by mherrmann** [brave/brave-browser#24623]
At the moment, our build process selects the Windows code signing certificate by its subject name "Brave". This is ambiguous, for example when we are about to renew our certificate and then have two certificates with the same subject name. The goal of this issue is to change the build process so it can select the certificate by its hash. It is also a prerequisite for improvements to our code signing infrastructure, in https://github.com/brave/devops/pull/8103.

**Comment by kjozwiak** [comment]
See https://github.com/brave/brave-browser/issues/24763#issuecomment-1232419318 for context re: moving this into `1.43.x`.
