### ISSUE TITLE
Support .zil tld for UD

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#24621]
UD resolvers did not support this initially

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.44.75 x64 build
- Verified steps from [brave/brave-core#14599](https://github.com/brave/brave-core/pull/14599)
- Verified visiting `jim-unstoppable.zil` and accepting to use `Infura Server` redirects to `ipfs://QmSEj9K6mAj52CFqCzd5Pbt4DgAFocWovwnn2GJpyFjm3p`

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/188624517-94b7819b-16a2-4bc1-abac-c33d66384717.mp4> | <video src=https://user-images.githubusercontent.com/17010094/188624865-5fa8ec4f-efa6-4263-b14d-69c686e3c2a8.mp4>

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.44.97 Chromium: 106.0.5249.40 (Official Build) (64-bit) 
-- | --
Revision | `4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}`
OS | Linux

- Verified steps from https://github.com/brave/brave-core/pull/14599
- Verified visiting `jim-unstoppable.zil` and accepting to use Infura Server redirects to `ipfs://QmSEj9K6mAj52CFqCzd5Pbt4DgAFocWovwnn2GJpyFjm3p`
- Verified able to load the page via public DNS. 
- Encountered [#25230](https://github.com/brave/brave-browser/issues/25230) when trying to load via local node

https://user-images.githubusercontent.com/17010094/191808705-801c9de4-0bfc-4170-95d3-0f9dfe94f9d3.mp4


------------------------
Verification passed on

Brave | 1.44.97 Chromium: 106.0.5249.40 (Official Build) (64-bit) 
-- | --
Revision | `4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}`
OS | Windows 11 Version 21H2 (Build 22000.978)

- Verified steps from https://github.com/brave/brave-core/pull/14599
- Verified visiting `jim-unstoppable.zil` and accepting to use Infura Server redirects to `ipfs://QmSEj9K6mAj52CFqCzd5Pbt4DgAFocWovwnn2GJpyFjm3p`
- Verified able to load the page via public DNS. 
- Encountered [#25230](https://github.com/brave/brave-browser/issues/25230) when trying to load via local node

https://user-images.githubusercontent.com/17010094/191808933-dfb9e4e0-025d-4050-9fdd-1ae6c5906895.mp4


------------------------
Verification passed on

Brave | 1.44.97 Chromium: 106.0.5249.40 (Official Build) (arm64)
-- | --
Revision | `4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from https://github.com/brave/brave-core/pull/14599
- Verified visiting `jim-unstoppable.zil` and accepting to use Infura Server redirects to `ipfs://QmSEj9K6mAj52CFqCzd5Pbt4DgAFocWovwnn2GJpyFjm3p`
- Verified able to load the page via public DNS. 
- Encountered [#25230](https://github.com/brave/brave-browser/issues/25230) when trying to load via local node

https://user-images.githubusercontent.com/17010094/191809090-c1e320f3-c180-433a-968c-f4ba62005e72.mov
