### ISSUE TITLE
brave://rewards-internals "Ad diagnostics" tab should show timestamps in local time with timezone

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#24626]

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.44.75 Chromium: 105.0.5195.102 (Official Build) beta (64-bit)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/14624

Confirmed date/time are shown in local time at brave://rewards-internals > Ads Diagnostics
![image](https://user-images.githubusercontent.com/34715963/189109501-c4d9289e-8af3-4d1c-bcfb-ba39331fb21d.png)
