### ISSUE TITLE
Allow contributions to videos checkbox controls if you are able to tip a YouTube video

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#2463]
## Description 
Found by @GeetaSarvadnya 

When `Allow contributions to videos` is unchecked, you cannot tip a YouTube video. If you check this checkbox and then visit a YouTube video, you can tip. If you uncheck this option again, you will still be able to tip for this video, but not any newly opened YouTube videos. This is unexpected since the Allow contributions to videos checkbox is an Auto-Contribute setting, not a Tips setting.

## Steps to Reproduce

1.    Launch brave with clean profile
2.    Enable Rewards
3.    Disable/Uncheck the checkbox `Allow contribution to videos`
4.    Open youtube.com and play any video
5.    Click on BAT icon and observe that there is NO tip option for the video
6.    Enable/check the checkbox `Allow contribution to videos`
7.    Refresh the video which is already opened and you can SEE tip option
8.    Disable the `Allow contribution to videos` option
9.    Go back to the same video and refresh, still you can see tip option
10.    Open any YT video in another tab and click on BAT icon you WON’T see tip option

## Actual result:
Unable to tip YT if Allow contributions to videos setting in AutoContribute is unchecked.

## Expected result:
Should be able to tip YouTube channel/video regardless of 'Allow contributions to videos' setting.

## Reproduces how often: 
Easily

## Brave version (brave://version info)

Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta(64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
Reproduced by @kjozwiak and @LaurenWags on macOS

**Comment by GeetaSarvadnya** [comment]
Verification passed on 


Brave | 0.60.25 Chromium: 72.0.3626.96 (Official Build) beta (64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Windows
