### ISSUE TITLE
Set default search engine bug

### ISSUE THREAD

**Issue by ghost** [brave/brave-browser#24635]
Issue was when I go to create a new profile in brave it shows me the welcome window (brave://welcome/) as usual after continuing to the fifth step of **Set default search engine** for suppose I choose google as default search engine and then I click **Set default** NOT **Done**.  _My screen goes blank for no reason._ 

![Brave bug 2](https://user-images.githubusercontent.com/111140272/184399283-b2683fd8-69d7-4097-8bce-74ca9d03a358.jpeg)

![brave bug](https://user-images.githubusercontent.com/111140272/184397565-b9ae2d0d-d92f-42d6-bd43-f57cefc182ea.jpeg)

I discovered this bug on my Mac running MacOS Monterey and running this in the latest update.[Version 1.42.88 Chromium: 104.0.5112.81].

Thanks :)

**Comment by GeetaSarvadnya** [comment]
Looks like it's UI bug, click on `Set Default` is setting the default SE via Onboarding flow, only problem is it's showing up the empty page after setting default SE. The issue is reproducible from `1.36.x to 1.42.x` versions. The issue got introduced starting from the version when `Rewards slide` is removed from the onboarding flow in the version 1.35.x. 

In 1.42.x, when the user select the SE from the drop down and click on `Set Default` button, the empty page appears with the `Next->` button, which is incorrect instead of `Next->` button it should show `Done` button as SE is the last slide in the onboarding flow. 

The version 1.35.x has 5 slides in onboarding flow (`lets go`, `import bookmarks`, `p3a`, `default search engine` and `rewards`) In 1.36.x the rewards slide is been removed from the onboarding flow. Looks like issue got introduced after that.

**_1.35.x - Working as expected_**

![SEt default SE via onboarding](https://user-images.githubusercontent.com/38657976/184856493-6842582d-3f63-4850-bf16-9873f3743c39.gif)

**_1.42.x - Not working_**

![SEt default SE](https://user-images.githubusercontent.com/38657976/184860650-76f45720-e924-478a-ae0f-bf013c2e5035.gif)

**Comment by rebron** [comment]
cc: @zenparsing

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.44.71 Chromium: 105.0.5195.68 (Oficjalna wersja) dev (x86_64)
-- | --
Wersja | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
System operacyjny | macOS Wersja 13.0 (kompilacja 22A5331f)

Prerequisite: set my OS language and region to Polish/Poland (to trigger the offering of the search-engine choice)

### Steps:
1. installed `1.44.71`
2. launched Brave
3. clicked through the onboarding-carousel dots
4. chose `Google` from the list, and clicked on the button

#### Confirmed it replaced the `brave://welcome` tab with a new-tab page, with background image, etc.

`1.44.71`

example | example
---------|----------
<img width="1312" alt="Zrzut ekranu 2022-09-1 o 16 07 57" src="https://user-images.githubusercontent.com/387249/188027889-bf7746d7-5eab-49a2-bce1-c1c091b7342e.png"> | <img width="1312" alt="Zrzut ekranu 2022-09-1 o 16 08 01" src="https://user-images.githubusercontent.com/387249/188027893-040590df-29d6-44cd-a5b8-d46c93e9031f.png">


`1.42.88`

example | example
---------|----------
<img width="1312" alt="Zrzut ekranu 2022-09-1 o 16 01 31" src="https://user-images.githubusercontent.com/387249/188027731-b97e4e92-9738-4aed-96a7-e118bafd7a43.png"> | <img width="1312" alt="Zrzut ekranu 2022-09-1 o 16 01 36" src="https://user-images.githubusercontent.com/387249/188027744-832132d9-b2e5-4638-9acf-c8341cdf2d7b.png">

**Comment by LaurenWags** [comment]
Labelling as `QA/Blocked` until this is uplifted to 1.43.x for the maintenance release

**Comment by kjozwiak** [comment]
The above requires `1.43.91` for `1.43.x` verification 👍 Removing `QA/Blocked`.

**Comment by kjozwiak** [comment]
Removing the `QA Pass-macOS` label as the above will need to be rechecked once we get a new `1.43.x` build. Used https://github.com/brave/brave-browser/issues/24635#issuecomment-1234887560 as the verification to get https://github.com/brave/brave-core/pull/15005 uplifted into `1.43.x`.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.43.91 Chromium: 105.0.5195.102 (Official Build) (x86_64)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | macOS Version 12.5.1 (Build 21G83)
```

**Comment by MadhaviSeelam** [comment]
```
Brave | 1.43.91 Chromium: 105.0.5195.102 (Official Build) (64-bit)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | Windows 11 Version 21H2 (Build 22000.856)
```
Pre-req: Set to a country/region which contains the SE panel in onboarding, I used India .

Reproduced using `1.43.89`
Ex1|Ex2
----|----
<image width ="950" alt="step4" src="https://user-images.githubusercontent.com/98358127/189218864-908d2020-0d16-4e20-ba51-afd8f1b90a5b.png">|<image width ="950" alt="step4" src="https://user-images.githubusercontent.com/98358127/189218910-a67d2134-15dd-4d6b-a0a9-c41cfcbf45a8.png">

Verification Steps:

1. installed `1.43.91`
2. launched Brave
3. clicked through the onboarding-carousel dots
4. chose `Bing`  from the list, and clicked on the button
5. confirmed search-engine choice in `brave://settings/search`

### Confirmed after clicking "Set default" on SE selection panel, the NTP was displayed. 

step 4|ex1|step 5
---|----|---
<image width ="950" alt="step4" src="https://user-images.githubusercontent.com/98358127/189216170-d271e539-a2c8-40ff-b432-83f0ec6b3af5.png">|<image width ="950" alt="step4" src="https://user-images.githubusercontent.com/98358127/189216545-52706fc8-9bf1-4ac5-8cfe-84fa5f9805dd.png">|<image width ="950" alt="step4" src="https://user-images.githubusercontent.com/98358127/189216237-82d7062d-0cd7-4b0c-b7b7-f6117ba0c9d2.png">

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.43.92 Chromium: 105.0.5195.102 (Official Build) (64-bit)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | Ubuntu 18.04 LTS

Pre-req: Set to a country/region which contains the SE panel in onboarding, I used PL.

Reproduced using `1.43.88`
Ex1|Ex2
----|----
![image](https://user-images.githubusercontent.com/34715963/189677969-e059e36d-bb04-4c91-aeed-f2f53fbc4a61.png)|![image](https://user-images.githubusercontent.com/34715963/189678013-78dfc7c5-0f37-4213-9a31-541265b66356.png)


Verification Steps:

1. installed `1.43.92`
2. launched Brave
3. clicked through the onboarding-carousel dots
4. chose `Bing`  from the list, and clicked on the button
5. confirmed search-engine choice in `brave://settings/search`

### Confirmed after clicking "Set default" on SE selection panel, the NTP was displayed. 

step 4|NTP|step 5
---|----|---
![image](https://user-images.githubusercontent.com/34715963/189678994-0dce89ca-9bb4-429a-a371-f310ef3fa5d6.png)|![image](https://user-images.githubusercontent.com/34715963/189679051-18d03304-1634-40c7-a6d7-5638ac75238c.png)|![image](https://user-images.githubusercontent.com/34715963/189679162-ca480b45-20e6-4a5c-b767-27d4cfc895cc.png)
