### ISSUE TITLE
`Arrived` message is shown starting from the payout date to till the end of the month 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#24637]
## Description 

`Arrived` message is shown starting from the payout date to till the end of the month 

## Steps to Reproduce

   1. Clean profile 1.43.67
   2. Enable rewards and view couple of ads
   3. Reconcile the ads with server
   4. Close the browser
   5. Set the system date to one day prior to payout date (7th Sep in my case)
   6. Relauch the browser
   7. Ensured that the payout pending message is shown as expected
   8. Send a ad grant to the payment id
   9. Claim the ad grants and close the browser
   10. Set the system date to payout date (8th Sep in my case)
   11. Relaunch the browser
   12. Payout arrived message is shown as expected
   13. Set the system date to one day after the payout date (9th Sep in my case)
   14. Relaunch the browser
   15. Payout arrived message is shown as expected, close the browser
   16. Repeat the steps 13 to 14 for the dates Sep10 and ensured payout message is shown as expected
   17. Repeat the steps 13 to 14 for rest of the dates in Sep (from Sep 11 to Sep 30)
   18. Arrived message is shown for all the date from Sep 11 to Sep 30 which is incorrcet
   
## Actual result:

`Arrived` message is shown starting from the payout date to till the end of the month 

## Expected result:
`Arrived` message should be shown for 8th, 9th and 10th Sep, 11th Sep onwards the arrived message should not be shown

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.43.67 Chromium: 104.0.5112.81 (Official Build) beta (64-bit)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | Windows 10 Version 21H2 (Build 19044.1889)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Miyayes @emerick @brave/qa-team

**Comment by emerick** [comment]
I think that we'll continue to show the "Arrived" message until the endpoint returns `off` cc: @Miyayes.

**Comment by GeetaSarvadnya** [comment]
As per the slack thread conversion this is expected  `With the current server payout configurations the `Payment Arrived` message is shown from the payout (8th Sep) to till end of the month (30th Sep) which is expected, in order to see arrived message in particular date range, the server side team needs to update the dates at the endpoint (confirmed with @emerick and @Miyayes )

Hence closing the issue as expected
