### ISSUE TITLE
Payout pending and payout arrived messages are shown in two different places at the same time

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#24642]
## Description 

Payout pending and payout arrived messages are shown in two different places at the same time

## Steps to Reproduce

   1. Clean profile 1.43.67
   2. Enable rewards and view couple of ads
   3. Reconcile the ads with server
   4. Close the browser
   5. Set the system date to one day prior to payout date (7th Sep in my case)
   6. Relauch the browser
   7. Ensured that the payout pending message is shown as expected
   8. Send a ad grant to the payment id
   9. Claim the ad grants and close the browser
   10. Set the system date to payout date (8th Sep in my case)
   11. Relaunch the browser
   12. Payout arrived message is shown as expected
   13. Set the system date to one day prior the payout date (7th Sep in my case)
   14. Relaunch the browser
   15. Payout arrived message is shown in the panel and payout pending message is shown in the settings pages
## Actual result:

Payout pending and payout arrived messages are shown in two different places at the same time

![image](https://user-images.githubusercontent.com/38657976/184434022-c8ed27bb-0e85-41cd-b5b6-4414ee9da84e.png)

## Expected result:
Arrived message should not be shown in the panel

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.43.67 Chromium: 104.0.5112.81 (Official Build) beta (64-bit)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | Windows 10 Version 21H2 (Build 19044.1889)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?NA 
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Miyayes @emerick @brave/qa-team

**Comment by kjozwiak** [comment]
The above will require `1.43.76` or higher for `1.43.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
Brave | 1.43.78 Chromium: 104.0.5112.102 (Official Build) beta (64-bit)
-- | --
Revision | 8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}
OS | Windows 10 Version 21H2 (Build 19044.1889)

```

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on `Samsung Galaxy Tab A7 version 11` running `Bravemonoarmx64.apk_1.43.78`

- Confirmed `payment status` banner is NOT shown on the rewards summary on setting page
- Confirmed `payout pending` and `payout arrived` messages are NOT shown in two different places at the same time
- Confirmed `payout pending` , `payment processing` and `payment arrived` banner messages are shown in the `rewards settings page`, `BR panel`, `NTP` and `BR panel on the website` 

### When the payout API enpoint is set to "Complete"
**_Step 15 Verification_** 
<details>
<summary>Payment pending banner message_</summary>

Example | Example | Example | Example
-- | -- | -- | --


</details>

**_Step 12 Verification_** 

<details>
<summary>Payment arrived banner message_</summary>

Example | Example | Example | Example
-- | -- | -- | --



</details>
