### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by mbaus24** [brave/brave-browser#24656]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.42.88  Chromium: 104.0.5112.81
Operating System: Windows NT 10.0.19044

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Enable speedreader
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/12fd0200-f3fb-a908-0000-000000000000

**Comment by rebron** [comment]
@mbaus24 Can you update to 1.42.95 and let us know if this fixes the crash for you
