### ISSUE TITLE
Brave crashed when clicked to turn on Speedreader after enabling `Brave translate` service

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#24650]
## Steps to Reproduce

   1. Install 1.43.54
   2. open brave://flags/#brave-translate-go and select Enabled
   3. relaunch the browser
   4. `Brave translate` bubble in the URL bar is displayed
   5. view a site in one of the supported languages `French` - https://www.faz.net/
   6. click to open links to view any of the articles
   7. click `Speedreader` icon and click on `Turn on Speedreader`

## Actual result:

Brave crashed. (Unfortunately didn't grab crash id)
![image](https://user-images.githubusercontent.com/98358127/184449311-f5614080-309d-4cb9-8038-eee580c91da4.png)

## Expected result:
No crashes

## Reproduces how often: 

Intermittently

## Brave version (brave://version info)

Brave | 1.43.54 Chromium: 104.0.5112.69 (Official Build) beta (64-bit)
-- | --
Revision | 7ce2902023c722af8564068e6b26e934b83fd774-refs/branch-heads/5112@{#1213}
OS | Windows 11 Version 21H2 (Build 22000.856)

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc: @rebron  @brave/qa-team

**Comment by rebron** [comment]
Possibly fixed with https://github.com/brave/brave-browser/issues/24588
cc: @boocmp

**Comment by kjozwiak** [comment]
> Possibly fixed with #24588 cc: @boocmp

@MadhaviSeelam mind seeing if you can still reproduce the issue with either `1.44.49` (or higher) or `1.43.75` (or higher).

**Comment by MadhaviSeelam** [comment]
@kjozwiak  @rebron  Verified with 1.43.76.  Not seeing any crashes and Speedreader is working as expected.  Closing this bug.
