### ISSUE TITLE
There is just one Private Window possible

### ISSUE THREAD

**Issue by kremik** [brave/brave-browser#24663]
## Description 

If I open regular and private window I can log into the same service with different credentials because every window have their own cookies/session. I would expect (as it is eg in Safari) that the second Private window will have the independent cookies/session and be able to log in the same service with another credentials. But all other private windows share the same cookies so you can have one context for non-private windows and all private windows act as one. 

## Steps to Reproduce

   1. Open private window and log in any cookie relevant service
   2. Open another private window and go to the same service
   3. Olalala, you don't have to log-in, because it uses the same cookies are the previous private window

## Expected result:
Every Private window to have independent cookies 

## Reproduces how often: 

Every time

## Brave version (brave://version info)

[Version 1.42.88](https://brave.com/latest/)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by ShivanKaul** [comment]
We match with Chromium here - it depends on your mental model here whether you would expect every new Private Window to have its own storage. Folks can use different profiles for that.

**Comment by kremik** [comment]
Well, at least from the user perspective I feel that it cannot be recognized (especially by non-tech users) that if I ask for a New Private Window that I have to check if there is not any other Private Window open, otherwise it's not a Private Window. From the elementary design of the feature - I'm opening the private window to browse privately.
