### ISSUE TITLE
Refactor AdsImpl methods from std::function to base::OnceCallback

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#24661]

**Comment by aseren** [comment]
QA could be done together with this issue: https://github.com/brave/brave-browser/issues/24761

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.47.101 Chromium: 108.0.5359.48 (Official Build) beta (64-bit)
-- | --
Revision | 18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/15748

<details>

Checked that brave rewards page shows correct statement information:

previous month earnings, this month earnings, next payment date, number of ads received this month

![image](https://user-images.githubusercontent.com/34715963/204854641-d5509595-01ec-4d1e-88ff-0e35ecf85ce4.png)


</details>
