### ISSUE TITLE
It's possible to resize text area with sync words

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#24671]
## Description 

It's possible to resize text area with sync words with an weird looking effect.

Reported by @boocmp 

## Steps to Reproduce

   1. Open sync settings
   2. Show code words
   3. Drag the right-bottom corner 

## Actual result:

![Screenshot from 2022-08-15 19-04-22](https://user-images.githubusercontent.com/24739341/184671826-f9bc787d-d7e1-4b5a-911b-f262aeb2109c.png)

![Screenshot from 2022-08-15 19-03-48](https://user-images.githubusercontent.com/24739341/184671831-c27bd2ec-6dec-4715-b269-dce8c4b3e2a7.png)

## Expected result:
There is no so much text in that area, we can make the dialog to be re-sizable only vertically.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.44.70 Chromium: 105.0.5195.68 (Official Build) beta (x86_64)
-- | --
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | macOS Version 13.0 (Build 22A5331f)

#### Followed the original steps to reproduce, and confirmed I can only resize vertically

`1.43.83` / `release` | `1.44.70` | `vertical resizing`
---------------------|-----------|------------------
<img width="712" alt="Screenshot 2022-08-31 at 13 50 13" src="https://user-images.githubusercontent.com/387249/187780244-0f39590b-67b4-4f5c-864e-596fc5bcab54.png"> | <img width="709" alt="Screenshot 2022-08-31 at 13 50 27" src="https://user-images.githubusercontent.com/387249/187780247-a3e48b38-699e-4861-875c-1c1ffed9741a.png"> | <img width="709" alt="Screenshot 2022-08-31 at 13 50 42" src="https://user-images.githubusercontent.com/387249/187780251-db973799-0e4e-4cd1-93f9-c02389a5874a.png">
