### ISSUE TITLE
Torrent downloading bug

### ISSUE THREAD

**Issue by dayfuaim** [brave/brave-browser#2467]
## Description 
If I click on torrent link I see empty page titled "Webtorrent", and that's it.
Even 'Right click - "Save As..."' dance doesn't work – Brave tries to save "HTML Text".
So for magnet-links.
All shields _and_ uBlock __are OFF__.

## Steps to Reproduce

   1. Open any website with torrent links.
   2. Click on torrent link.

## Actual result:
Blank "Webtorrent" page opens and nothing happens.

## Expected result:
_At least_: correct "Webtorrent" page with "Start torrent" and "Save torrent" buttons.
_At best_: "Save as..." dialog.

## Reproduces how often: 
Every time.

## Brave version (brave://version info)

Brave | 0.58.11 Chromium: 71.0.3578.80 (Official build) beta (64 бbit)
Version | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
ОС | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Beta – yes
Dev (0.59.2 Chromium: 71.0.3578.80 (Official build), dev (64 bit)) – no

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? Shields are already Off.
- Is the issue reproducible on the latest version of Chrome? It is the latest version.

**Comment by yrliou** [comment]
Duplicate to https://github.com/brave/brave-browser/issues/2479, closing this one.

**Comment by bbondy** [comment]
Please move to dupe / invalid milestone when no fix exists. Thanks!
