### ISSUE TITLE
Remove DNS.Resolvers IPNS config property if user disables DOH

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#24678]
Dns override doesn't falls back when DOH removed.
Config still contains DNS.Resolvers property after user switches to system DNS.

**Comment by kjozwiak** [comment]
The above will require `1.43.81` or higher for `1.43.x` verification. @StephenBass believe this wasn't working so you created a follow up via https://github.com/brave/brave-browser/issues/24900 when running through the verification before we uplift into `1.43.x` via https://github.com/brave/brave-core/pull/14631#issuecomment-1224411932. Should this be labelled as `QA/No` in that case?

**Comment by kjozwiak** [comment]
@cypt4 mind taking a look? Is this something we should fix? Seems like it's a `P2` so assuming we want to get https://github.com/brave/brave-browser/issues/24900 fixed.

**Comment by stephendonner** [comment]
> The above will require `1.43.81` or higher for `1.43.x` verification. @StephenBass believe this wasn't working so you created a follow up via #24900 when running through the verification's via [brave/brave-core#14631 (comment)](https://github.com/brave/brave-core/pull/14631#issuecomment-1224411932) before we uplift into `1.43.x`. Should this be labelled as `QA/No` in that case?

We can `QA/No` this one, as -- at any rate -- I wasn't able to get it working, with my steps.  Pending the outcome/fix of https://github.com/brave/brave-browser/issues/24900, we can change the label back, if need-be.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.43.89 Chromium: 105.0.5195.102 (Official Build) (64-bit)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | Windows 11 Version 21H2 (Build 22000.856)
```

### Steps:

1. installed `1.43.89`
2. launched Brave
3. loaded `brave://ipfs-internals/`
4. clicked on `Install and start`
5. chose `NextDNS` as a DoH provider in `brave://settings/security`
6. shut down Brave
7. opened `{profile_folder}/brave_ipfs/config` in a text editor
8. confirmed there's a DNS entry with `Resolvers:` and `NextDNS` is listed
9. relaunch Brave
10. set DNS back to `With your current service provider`
11. loaded `ipns://ipfs.io`
12. clicked on `Use a local Brave IPFS node`
13. waited for `ipns://ipfs.tech/` to finish loading
14. shut down Brave
15. opened `{profile_folder}/brave_ipfs/config` in a text editor
16. searched for `DNS` / `Resolver`

#### Confirmed the `DNS Resolver` section was removed

step 4|step5|step 7-8|step10|step 11|step12|step 13|step15-16
----|-----|-----|-----|-----|-----|-----|-----
<image width="900" alt="step4" src="https://user-images.githubusercontent.com/98358127/189395853-f8dcb612-dbe7-4c63-8874-ab208427f513.png">|<image width="900" alt="step5" src="https://user-images.githubusercontent.com/98358127/189395990-34a90dca-8da5-4703-b5dd-da856a1e9221.png">|<image width="1900" alt="step8" src="https://user-images.githubusercontent.com/98358127/189397617-1b4a48bb-8847-40ba-bb9d-a1977cf830b3.png">|<image width="900" alt="step4" src="https://user-images.githubusercontent.com/98358127/189398056-1079bf48-1fcd-42fd-898b-92c50dc3789e.png">|<image width="900" alt="step4" src="https://user-images.githubusercontent.com/98358127/189398348-e22fe374-b424-4b30-85f4-2d8fab55da4e.png">|<image width="900" alt="step4" src="https://user-images.githubusercontent.com/98358127/189398519-3fb481b2-d814-4761-be20-c43ecb48d4cf.png">|<image width="900" alt="step13" src="https://user-images.githubusercontent.com/98358127/189398687-93315318-7920-490b-ac11-cc1f5a9f7dd4.png">|<image width="900" alt="step4" src="https://user-images.githubusercontent.com/98358127/189399526-8caf81b5-a155-4890-9722-a1ea5d144122.png">
