### ISSUE TITLE
Top Site "on-touch" white background on the New Tab Page is misaligned

### ISSUE THREAD

**Issue by nastavoi** [brave/brave-browser#24676]
## Description 
Top Site "on-touch" white background on the New Tab Page is misaligned (or cut off?)

## Steps to reproduce 

   1. Open Brave 
   2. Open/touch any of the Top Sites on the New Tab Page
   3. Notice that the white/grey background that is appearing when touching the icon is misaligned. I've attached a short video which shows the problem very clearly.
   
   I've also attached a video from Chrome to show how it is supposed to look.

## Actual result 
https://user-images.githubusercontent.com/61883414/184692313-27984eed-f4fb-4701-bd47-dd4dae70664c.mp4

## Expected result
https://user-images.githubusercontent.com/61883414/184692328-97ab54fb-ed70-4b74-bda1-1cbaac0a6400.mp4

## Issue reproduces how often 
Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): arm64
   - Device type (Phone, Tablet, Phablet): Samsung S10+
   - Android version: 12
   
## Brave version
Brave Nightly 1.44.40

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No, it's fine on the latest Chrome.

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` & `Samsung Galaxy Tab S7` using the following build(s):

```
Brave	1.45.106 Chromium: 107.0.5304.36 (Official Build) (64-bit) 
Revision	2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}
OS	Android 12; Build/SP1A.210812.016
```

- Verified top sites on-touch white background is aligned
- Verified webpage is launched upon tapping the top site icon.

https://user-images.githubusercontent.com/17885425/196811811-cbea6745-8a50-48d3-bc03-0aba34c26d48.mp4
