### ISSUE TITLE
Recovery phrase verification should use randomized word indices

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#24683]
## Description 

https://github.com/brave/brave-core/pull/13146#discussion_r934111501
When creating a new wallet during onboarding, the user is always asked to verify the first, third, and last words of their recovery phase. 
We should randomize these words to deter users from not properly backing-up their recovery phrase

## Steps to Reproduce

   1. Reset Wallet
   2. Create New Wallet
   3. Continue to the Verify recovery phrase onboarding step

## Actual result:

The user is only ever asked to verify the first, third and last words of their recovery phrase

## Expected result:
The user is asked to verify 3 randomly selected words from their recovery phrase

cc @kdenhartog

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.44.95 Chromium: 106.0.5249.40 (Official Build) (64-bit) 
-- | --
Revision | `fab1d91915d2722d6339aaa7f4e9ce44f1e9b103-refs/branch-heads/5249@{#442}`
OS | Linux

- Verified steps from [brave/brave-core#14633](https://github.com/brave/brave-core/pull/14633)
- Verified recovery phrase verification has randomized word indices for each wallet creation

https://user-images.githubusercontent.com/17010094/191576609-41ad2bbe-00e8-4214-92fc-cfd4f81ff504.mp4



------------------------
Verification passed on

Brave | 1.44.95 Chromium: 106.0.5249.40 (Official Build) (64-bit) 
-- | --
Revision | `fab1d91915d2722d6339aaa7f4e9ce44f1e9b103-refs/branch-heads/5249@{#442}`
OS | Windows 11 Version 21H2 (Build 22000.978)

- Verified steps from [brave/brave-core#14633](https://github.com/brave/brave-core/pull/14633)
- Verified recovery phrase verification has randomized word indices for each wallet creation

https://user-images.githubusercontent.com/17010094/191577186-c0b5b938-51ae-4696-a822-460279142a72.mp4


------------------------
Verification passed on

Brave | 1.44.95 Chromium: 106.0.5249.40 (Official Build) (arm64)
-- | --
Revision | `fab1d91915d2722d6339aaa7f4e9ce44f1e9b103-refs/branch-heads/5249@{#442}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [brave/brave-core#14633](https://github.com/brave/brave-core/pull/14633)
- Verified recovery phrase verification has randomized word indices for each wallet creation

https://user-images.githubusercontent.com/17010094/191574751-eb408a09-2511-4688-ae12-e779a35aae14.mov
