### ISSUE TITLE
Switching between top tile types w/pagination gets stuck

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#24688]
## Description 

Switching between top tile types w/pagination gets stuck

## Steps to Reproduce

1. install `1.44.44`
2. launch Brave
3. load and bookmark 12+ sites
4. open a new-tab page
5. toggle to `Show favorites`
6. click to switch to the 2nd page
7. toggle to `Show frequently visited`
8. toggle back to `Show favorites`
9. try to click to change pages

## Actual result:

Pagination is stuck, and you're unable to return to the 1st page

![favorites-broken](https://user-images.githubusercontent.com/387249/184757608-8c2d6c8a-59f6-489f-8025-e858dc74331f.gif)

## Expected result:

Pagination should still work, after switching between Favorites/Frequently-Visited Sites

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.44.44 Chromium: 104.0.5112.81 (Official Build) nightly (x86_64)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | macOS Version 11.6.8 (Build 20G730)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @fallaciousreasoning @rebron

**Comment by fallaciousreasoning** [comment]
Interesting, I can't actually reproduce this in `1.44.32`, `1.44.37`, `1.44.43` (Latest Nightly) but I could in `1.43.67` (Beta). I'm wondering if this is maybe already fixed?

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.45.48 Chromium: 105.0.5195.127 (Official Build) nightly (x86_64)
-- | --
Revision | 912488396852bf658ab32465980c0b93a3c27a83-refs/branch-heads/5195@{#1109}
OS | macOS Version 11.7 (Build 20G817)

#### Followed my original steps to reproduce, and confirmed it's fixed

example | example | example | example | example | example | example
---------|----------|---------|----------|---------|----------|---------
<img width="1309" alt="Screen Shot 2022-09-14 at 11 30 07 PM" src="https://user-images.githubusercontent.com/387249/190331279-3c70b4d0-c132-4bdf-9d95-70f1172fb417.png"> | <img width="1309" alt="Screen Shot 2022-09-14 at 11 30 25 PM" src="https://user-images.githubusercontent.com/387249/190331305-355fa7e6-f73e-48ae-af4b-71d42bfd1f23.png"> | <img width="1418" alt="Screen Shot 2022-09-14 at 11 31 13 PM" src="https://user-images.githubusercontent.com/387249/190331314-97a526ca-4a61-4e22-89e1-5d1c572e7908.png"> | <img width="1389" alt="Screen Shot 2022-09-14 at 11 31 25 PM" src="https://user-images.githubusercontent.com/387249/190331324-08bdb237-090e-4a37-b9fd-2ecbcffe8295.png"> | <img width="1389" alt="Screen Shot 2022-09-14 at 11 31 30 PM" src="https://user-images.githubusercontent.com/387249/190331330-f17648b1-4835-4891-9aee-2a026f8a328b.png"> | <img width="1389" alt="Screen Shot 2022-09-14 at 11 34 45 PM" src="https://user-images.githubusercontent.com/387249/190331660-c13afb3d-f1d3-4408-8e52-33b6416a87b5.png"> | <img width="1389" alt="Screen Shot 2022-09-14 at 11 31 36 PM" src="https://user-images.githubusercontent.com/387249/190331338-e5f9cf40-11e5-46bb-ad77-2f46bb884389.png">
