### ISSUE TITLE
Fix conditions for showing "Bridge to Aurora" button

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#24695]
Conditions outlined in [this](https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1660578385735489?thread_ts=1660067286.646109&cid=C023VS4HJ6Q) conversation on Slack.

**Comment by kjozwiak** [comment]
The above will require `1.43.79` or higher for `1.43.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.43.81 Chromium: 104.0.5112.102 (Official Build) (64-bit)
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | Linux

- Verified steps from [brave/brave-core#14643](https://github.com/brave/brave-core/pull/14643)
- Verified Bridge to Aurora is only shown for tokens on mainnet
- Verified Bridge to Aurora is not shown for tokens on other networks
- Encountered [#24248](https://github.com/brave/brave-browser/issues/24248)

https://user-images.githubusercontent.com/17010094/186436599-2bf53a97-ec4b-4b7f-b956-5bf145fec609.mp4


------------------------
Verification passed on

Brave | 1.43.81 Chromium: 104.0.5112.102 (Official Build) (64-bit)
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | Windows 11 Version 21H2 (Build 22000.795)

- Verified steps from [brave/brave-core#14643](https://github.com/brave/brave-core/pull/14643)
- Verified Bridge to Aurora is only shown for tokens on mainnet
- Verified Bridge to Aurora is not shown for tokens on other networks
- Encountered [#24248](https://github.com/brave/brave-browser/issues/24248)

https://user-images.githubusercontent.com/17010094/186436993-5ed98f42-33f6-4aae-aabe-2de0531f112f.mp4


------------------------
Verification passed on

Brave | 1.43.81 Chromium: 104.0.5112.102 (Official Build) (arm64)  
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [brave/brave-core#14643](https://github.com/brave/brave-core/pull/14643)
- Verified Bridge to Aurora is only shown for tokens on mainnet
- Verified Bridge to Aurora is not shown for tokens on other networks
- Encountered [#24248](https://github.com/brave/brave-browser/issues/24248)

https://user-images.githubusercontent.com/17010094/186435987-8ba47ed8-e93a-4d74-b1b9-b67247da37b2.mov

**Comment by LaurenWags** [comment]
Changing to `release-notes/exclude` per consultation with @bbondy as this issue is a follow up to the implementation of the "Bridge to Aurora" button via https://github.com/brave/brave-browser/issues/24377. Main issue will be included in release notes.
