### ISSUE TITLE
download from Chrome sometimes get "file maybe dangerous" warning

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#2470]
![chrome](https://user-images.githubusercontent.com/5951041/49834828-36014a80-fd52-11e8-8be6-143cb741e50e.jpg)

## Description 
Downloading Brave using Chrome shows the "This file maybe dangerous, Chrome has blocked it." notification with "Remove from list" or "Keep dangerous file" as options (neither of which make sense as a user option).

## Steps to Reproduce
1. Use the latest Chrome Browser.
2. Go to https://brave.com and download Brave normally.
3. Download Brave and notice downloads in in Download manager with notification.

## Expected result:
Brave should be downloaded in the normal flow without this warning prompt from Google.
User should not even be taken to chrome://downloads.

## Reproduces how often: 
Can't reproduce consistently. Looks like a Google Safebrowsing feature rolled out to only some subset of users.

**Comment by tomlowenthal** [comment]
Pretty sure this was a problem with the Safe Browsing lists Google was publishing rather than any client-side issue. I think it's done now, but happy to re-open if it's still happening.

**Comment by bbondy** [comment]
Please set dupe / invalid milestone when closing issues that have no fixes. Thanks @tomlowenthal
