### ISSUE TITLE
Sort on ramp providers alphabetically

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#24700]
Update design to:

<img width="313" alt="Screenshot 2022-08-17 at 17 07 18" src="https://user-images.githubusercontent.com/48117473/185155156-e36ee027-aa63-41e6-a50d-127f6d1e8930.png">

figma.com/file/G3CV8kIdipr5xTVben9blr/Wallet?node-id=170%3A21772

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.44.95 Chromium: 106.0.5249.40 (Official Build) (64-bit) 
-- | --
Revision | `fab1d91915d2722d6339aaa7f4e9ce44f1e9b103-refs/branch-heads/5249@{#442}`
OS | Linux

- Verified steps from [brave/brave-core#14644](https://github.com/brave/brave-core/pull/14644)
- Verified Ramp providers are sorted alphabetically

Widget | Panel
-- | --
![image](https://user-images.githubusercontent.com/17010094/191593814-d1a15b36-96fc-47b1-be51-9d84dc5aeb77.png) | ![image](https://user-images.githubusercontent.com/17010094/191593773-33a9bf71-ca0a-4aa4-bf9a-07bda45c3191.png)


------------------------
Verification passed on

Brave | 1.44.95 Chromium: 106.0.5249.40 (Official Build) (64-bit) 
-- | --
Revision | `fab1d91915d2722d6339aaa7f4e9ce44f1e9b103-refs/branch-heads/5249@{#442}`
OS | Windows 11 Version 21H2 (Build 22000.978)

- Verified steps from [brave/brave-core#14644](https://github.com/brave/brave-core/pull/14644)
- Verified Ramp providers are sorted alphabetically

Widget | Panel
-- | --
![image](https://user-images.githubusercontent.com/17010094/191594038-e90d861e-2d57-4485-81be-503d58bf5408.png) | ![image](https://user-images.githubusercontent.com/17010094/191594025-0ac149e5-3bf4-4c5f-a237-813210118c92.png) 

------------------------
Verification passed on

Brave | 1.44.95 Chromium: 106.0.5249.40 (Official Build) (arm64)
-- | --
Revision | `fab1d91915d2722d6339aaa7f4e9ce44f1e9b103-refs/branch-heads/5249@{#442}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [brave/brave-core#14644](https://github.com/brave/brave-core/pull/14644)
- Verified Ramp providers are sorted alphabetically

Widget | Panel
-- | --
![image](https://user-images.githubusercontent.com/17010094/191594470-5753b071-3d42-411b-9e6e-0116f54d723b.png) | ![image](https://user-images.githubusercontent.com/17010094/191594495-da2d4344-7dc6-42fb-94fb-40f9cab7eed2.png)
