### ISSUE TITLE
Do not pass raw RFC-8484 urls when make DOH override in IPFS

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#24706]
Kubo(go-ipfs) only supports POST DOH requests.
https://github.com/libp2p/go-doh-resolver/blob/master/request.go#L28
If DOH is overriden by url with {?dns} template then DNS resolution errors happens.
So we should clear the provided DOH url from {?dns} templates or not override DOH if such url is selected.

**Comment by ShivanKaul** [comment]
@cypt4 we discussed this in privacy confab today but we didn't understand what the issue was, would you mind explaining?

**Comment by cypt4** [comment]
> ~@cypt4 we discussed this in privacy confab today but we didn't understand what the issue was~ Taking a look at the PR, seems like it's simply replacing the {?dns} substring from the DoH server URL if it exists. It's confusing that the PR fixes two separate issues under one title.

Yep, sorry for merging 2 issues in one pr, this is made to push this changes to 1.43

**Comment by kjozwiak** [comment]
The above will require `1.43.81` or higher for `1.43.x` verification.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.43.81 Chromium: 104.0.5112.102 (Official Build) (x86_64)
-- | --
Revision | 8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}
OS | macOS Version 11.6.8 (Build 20G730)

**Followed the steps to reproduce from https://github.com/brave/brave-core/pull/14631#issue-1339413042.**

### Confirmed I was able to load `ipns://ipfs.io`

example | example | example | example
---------|----------|---------|---------
<img width="1312" alt="Screen Shot 2022-08-24 at 2 14 38 PM" src="https://user-images.githubusercontent.com/387249/186525677-725caf3c-4e23-4140-854e-7cd94038cbed.png"> | <img width="1218" alt="Screen Shot 2022-08-24 at 2 18 42 PM" src="https://user-images.githubusercontent.com/387249/186525707-d31aef17-6a52-4cd9-ac09-2a7530a608af.png"> | <img width="1312" alt="Screen Shot 2022-08-24 at 2 17 11 PM" src="https://user-images.githubusercontent.com/387249/186525755-5b1ac82f-ae03-41fc-b8a1-f887f87a9dbb.png"> | <img width="1312" alt="Screen Shot 2022-08-24 at 2 17 24 PM" src="https://user-images.githubusercontent.com/387249/186525759-8c9702b2-d357-4d98-be91-e6a024d9ffcf.png">
