### ISSUE TITLE
Tipping banner doesn't reflect failed vBAT tip - follow up to 19071

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#24707]
## Description 

Found while testing #19071 

Case 1 (vBAT tip) from above issue does not show messaging for failed tip on the tip banner, instead banner shows success message and vBAT tip goes into endless retry loop.

## Steps to Reproduce

Anon wallet (pre-req: have Charles Proxy set up to return 500 error for `https://grant.rewards.bravesoftware.com/v1/suggestions`)
   1. Clean profile, staging env
   2. Enable Rewards, claim UGP grant
   3. Go to tip a verified publisher
   4. Watch logs
   5. You will see the 500 error, but you get the success/confetti on tip banner

## Actual result:

<img width="1196" alt="vBAT" src="https://user-images.githubusercontent.com/28145373/184916745-1c0a558e-6193-4a84-b8f9-ce4534f3b088.png">

## Expected result:

Failed message or messaging indicating the tip will be retried to accurately reflect what is happening.

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.43.71 Chromium: 104.0.5112.81 (Official Build) beta (x86_64)
-- | --
Revision | 5b7b76419d50f583022568b6764b630f6ddc9208-refs/branch-heads/5112@{#1309}
OS | macOS Version 12.5 (Build 21G72)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @Miyayes @zenparsing

**Comment by Miyayes** [comment]
"it went into a perpetual retry state" — @LaurenWags

"in the vBAT case, if you get a 500 back from the endpoint, it just retries. So, the tipping banner thinks that it will succeed later, hence why it shows success." — @zenparsing

**Comment by zenparsing** [comment]
The non-trivial aspect here will be ensuring that the tokens are "unreserved" before failing the contribution. (The tokens are "reserved" before attempting to send them to the server).

**Comment by Miyayes** [comment]
Once vBAT is sunsetted completely, this will no longer be relevant. Will close as will not fix.
