### ISSUE TITLE
Add additional Password-protection for Wallet Account removal

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#24711]
## Description 

To increase the overall security, revealing the Brave Wallet backup seed phrase from should require re-entering the wallet password

## Steps to Reproduce

1. Unlock the Brave wallet
2. Navigate to Portfolio Screen -> Click the "Accounts" tab
3. Create a non-primary account (if none exist)
4. Click the "Trash" icon in the account's list item

## Actual result:

Account is removed without additional credential check

## Expected result:
User is prompted to enter their password before they can confirm the account removal

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.45.85 Chromium: 106.0.5249.91 (Official Build) beta (64-bit) 
-- | --
Revision | `fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}`
OS | Linux

- Verified steps from issue description & [brave/brave-core#14669](https://github.com/brave/brave-core/pull/14669)
- Verified additional password-protection is shown when trying to remove Imported Wallet accounts
- Verified password prompt is shown for both Imported accounts and hardware wallets

https://user-images.githubusercontent.com/17010094/194246580-b5101780-070b-49dd-b6fd-0a7515e1571d.mp4


------------------------
Verification passed on

Brave | 1.45.85 Chromium: 106.0.5249.91 (Official Build) beta (64-bit) 
-- | --
Revision | `fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}`
OS | Windows 11 Version 21H2 (Build 22000.978)

- Verified steps from issue description & [brave/brave-core#14669](https://github.com/brave/brave-core/pull/14669)
- Verified additional password-protection is shown when trying to remove Imported Wallet accounts
- Verified password prompt is shown for both Imported accounts and hardware wallets

https://user-images.githubusercontent.com/17010094/194246176-92c89329-bbfb-4c04-a894-4d0b8018932b.mp4


------------------------
Verification passed on

Brave | 1.45.85 Chromium: 106.0.5249.91 (Official Build) beta (arm64)
-- | --
Revision | `fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from issue description & [brave/brave-core#14669](https://github.com/brave/brave-core/pull/14669)
- Verified additional password-protection is shown when trying to remove Imported Wallet accounts
- Verified password prompt is shown for both Imported accounts and hardware wallets

https://user-images.githubusercontent.com/17010094/194245057-674450e0-cf6b-4b42-b166-2c9fa3070ce8.mov
