### ISSUE TITLE
Tip button placement on Twitter incorrect again

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#24710]
## Description 

Tip button placement was adjusted in last GL update via https://github.com/brave/brave-browser/issues/24134

It is now showing incorrectly again. Example link: 

https://twitter.com/brendaneich/status/1559579029144887296

Reported by @szilardszaloki via https://bravesoftware.slack.com/archives/C01F09348SV/p1660668967984699

## Steps to Reproduce

   1. Navigate to link
   2. See incorrect Tip button placement

## Actual result:

<img width="635" alt="Screen Shot 2022-08-16 at 1 22 04 PM" src="https://user-images.githubusercontent.com/28145373/184940695-e5cc2254-d6c7-4897-bfc3-577966497459.png">

## Expected result:

Should be like other tip buttons in above screenshot

## Reproduces how often: 

easily

## Brave version (brave://version info)

1.43.x, Brave Local Data Updater version 1.0.180

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @emerick @Miyayes

**Comment by LaurenWags** [comment]
+1 from @lukaslevert via https://bravesoftware.slack.com/archives/C0KHGGEUW/p1661279459479289

**Comment by GeetaSarvadnya** [comment]
Verified using dev component for:

```
Brave Local Data Updater - Version: 1.0.649
```


- Reproduced the issue with the component `1.0.199`  
![image](https://user-images.githubusercontent.com/38657976/191680451-5e55d21a-cc09-4e06-9370-189b83b77637.png)

- Launched `1.44.95` using `--use-dev-goupdater-url` and ensured issue is fixed with the component `1.0.649` and ensured tip button is aligned with action button on twitter posts
![image](https://user-images.githubusercontent.com/38657976/191681176-c7e52f18-254a-466c-85b6-6a49986a0fca.png)

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.43.93 Chromium: 105.0.5195.127 (Official Build) (x86_64)
-- | --
Revision | 912488396852bf658ab32465980c0b93a3c27a83-refs/branch-heads/5195@{#1109}
OS | macOS Version 11.7 (Build 20G817)

#### Confirmed new working component version `1.0.649`:

<img width="414" alt="Screen Shot 2022-09-22 at 8 53 24 AM" src="https://user-images.githubusercontent.com/387249/191800168-d9ae8a16-3da5-4c59-befe-20e00a7d836a.png">

#### Confirmed `Tip` button placement and functionality

`https://twitter.com/brendaneich/status/1559579029144887296`:

example | example
---------|---------
<img width="1312" alt="Screen Shot 2022-09-22 at 9 16 55 AM" src="https://user-images.githubusercontent.com/387249/191800073-e72341a5-0c44-4264-bcea-5af7c5ea4e0b.png"> | <img width="1312" alt="Screen Shot 2022-09-22 at 9 17 00 AM" src="https://user-images.githubusercontent.com/387249/191800078-d34ff860-e018-4364-9229-e4c38f9a52ba.png">



`https://www.reddit.com/r/brave_browser/comments/vxelra/new_today_in_brave_v141_solana_dapp_support_for/`:

example | example
---------|---------
<img width="1312" alt="Screen Shot 2022-09-22 at 9 17 47 AM" src="https://user-images.githubusercontent.com/387249/191799763-3bd7663e-dda2-48e3-a0e5-6bb011836b5d.png"> | <img width="1312" alt="Screen Shot 2022-09-22 at 9 17 55 AM" src="https://user-images.githubusercontent.com/387249/191799770-1ab77777-255b-4450-9a5e-6f2405bfec46.png">

**Comment by mkarolin** [comment]
Fixed via https://github.com/brave/brave-site-specific-scripts/pull/84 (https://github.com/brave/brave-core-crx-packager/pull/489)
