### ISSUE TITLE
Don't inherit permissions in private windows

### ISSUE THREAD

**Issue by goodov** [brave/brave-browser#24720]
Change `INHERIT_IF_LESS_PERMISSIVE` to some `NEVER_INHERIT` equivalent in private windows.

**Comment by goodov** [comment]
#### Test case 1
Don't inherit in incognito less than permissive settings.
1. Visit https://permission.site/, request and **Block** Geolocation permission.
2. Open https://permission.site/ in incognito, request Geolocation permission.
3. Expect permission **dialog is shown** with Allow and Block buttons.
4. Expect `brave://settings/content/location` shows two records for a normal and incognito profiles.

#### Test case 2
Notifications should always block in incognito.
1. Visit https://permission.site/, request and **Allow** Notifications permission.
2. Open https://permission.site/ in incognito, request Notifications permission.
3. Expect **permission is blocked**.
4. Expect `brave://settings/content/notifications` shows two records for a normal and incognito profiles.

#### Test case 3
Always-inheritable settings should work as usual.
1. Select "Don't allow sites to show images" mode on `brave://settings/content/images`
2. Visit https://brave.com/, make sure images are not loaded.
3. Visit https://brave.com/ in incognito, **make sure images are not loaded**.
4. Enable images via permissions dialog in incognito, reload:
![image](https://user-images.githubusercontent.com/5928869/187638282-bcd68bac-87b8-462f-8e02-b2ce1447a3ce.png)
5. Expect images are loaded and `brave://settings/content/images` contains an item for incognito profile.

**Comment by MadhaviSeelam** [comment]
Verification In progress using
```
Brave | 1.45.80 Chromium: 106.0.5249.65 (Official Build) beta (64-bit)
-- | --
Revision | 3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}
OS | Windows 11 Version 21H2 (Build 22000.978)
```
Test 1: don't inherit less-permissive permissions - `PASSED`
<details>

Case 1:  request and `Block` Geolocation permission 
<details>

Steps:
1. loaded `https://permission.site`, 
2. request and `Block `Geolocation permission for normal window
3. loaded `https://permission.site` in a Private tab, request Geolocation permission 
4. confirmed permission dialog is shown with `Allow` and `Block` buttons
5. clicked on `Block`
6. `brave://settings/content/location` shows two records for a normal and Private profiles for `Not allowed`

step 1| step 2| step3| step5|step 6
----------|----------|---------|-----------|----------
<img width="963" alt="image" src="https://user-images.githubusercontent.com/98358127/193635763-536360f8-d156-4168-a834-df426277cce1.png">|<img width="963" alt="image" src="https://user-images.githubusercontent.com/98358127/193647703-1012f82e-8fd0-4edb-888b-3ef5a0617883.png">|<img width="963" alt="image" src="https://user-images.githubusercontent.com/98358127/193636000-14b0aca2-dc33-4b1f-aa36-fe0003df9700.png">|<img width="963" alt="image" src="https://user-images.githubusercontent.com/98358127/193647861-91fca2a3-3fd4-40e3-a2ce-d32b7dedbac4.png">|<img width="962" alt="image" src="https://user-images.githubusercontent.com/98358127/193648374-052895f8-0186-4756-9740-d33148185b67.png">

</details>

Case 2:  request and `Allow` Geolocation permission
<details>

Steps:
1. loaded `https://permission.site`, 
2. request and `Allow `Geolocation permission for normal window
3. loaded `https://permission.site` in a Private tab, request Geolocation permission 
4. confirmed permission dialog is shown with `Allow` and `Block` buttons
4. clicked on `Allow`
6. `brave://settings/content/location` shows two records for a normal and Private profiles for Allowed

step 1| step 2| step3| step 6
--------|-------|-------|--------
<img width="465" alt="image" src="https://user-images.githubusercontent.com/98358127/193642940-b8cefb60-51ee-4871-9dbd-0fa0faed044f.png">|<img width="462" alt="image" src="https://user-images.githubusercontent.com/98358127/193643378-072c6b15-a9a0-479a-bd52-ed25b919e040.png">|<img width="459" alt="image" src="https://user-images.githubusercontent.com/98358127/193643125-b0a9902b-621c-49ee-aa4d-4aee21c0af8c.png">|<img width="461" alt="image" src="https://user-images.githubusercontent.com/98358127/193643529-8b95209a-0478-4576-89d4-d2ab0f53b52d.png">
</details>

</details>

Test 2: always block notifications in Private windows - `PASSED`
<details>

Steps:
1. loaded `https://permission.site`, request and `Allow` for the `notifications` permission for normal window
2. confirmed permission is allowed
3. opened `https://permission.site` in a Private tab, request `notifications` permission
4. confirmed permission is blocked
5. confirmed `brave://settings/content/notifications` shows two records for a normal and Private profiles

step 1|step 2|step 3|step 5
--------|-------|-------|--------
<img width="961" alt="image" src="https://user-images.githubusercontent.com/98358127/193639712-a5df31f9-5720-49ba-90df-63ae88f4e8fa.png">|<img width="963" alt="image" src="https://user-images.githubusercontent.com/98358127/193639755-ce14f5bc-0466-422c-a82b-8f7eae1413b0.png">|<img width="962" alt="image" src="https://user-images.githubusercontent.com/98358127/193639793-d6a5347d-7adb-4eb2-831f-839129d7cc38.png">|<img width="961" alt="image" src="https://user-images.githubusercontent.com/98358127/193639939-2dc8751d-5764-4ada-acb5-332e9b8e6af4.png">

</details>

Test 3: always-inheritable settings - `PASSED`
<details>

Steps:
1. clicked on "Don't allow sites to show images" radio button on `brave://settings/content/images`
2. loaded `https://brave.com`in normal window
3. confirmed images weren't loaded
4. visited `https://brave.com` in a Private tab
5. confirmed images weren't loaded
6. clicked to enable `Sites can show images` in a Private tab
7. reloaded
8. confirmed images are loaded and `brave://settings/content/images` contains an item for the Private-tab profile.

step 1 | step 2-3| step 4-5 | step 6 | step 8
---------|-----------|------------|-----------|----------
<img width="467" alt="image" src="https://user-images.githubusercontent.com/98358127/193644453-7bfbfde3-89f2-48bb-8406-ce92ff71ace3.png">|<img width="465" alt="image" src="https://user-images.githubusercontent.com/98358127/193646835-da17ccbf-babe-4dbf-b637-f8d003724857.png">|<img width="465" alt="image" src="https://user-images.githubusercontent.com/98358127/193646771-84799b56-4d1d-417d-887e-03e264a491f0.png">|<img width="465" alt="image" src="https://user-images.githubusercontent.com/98358127/193646915-113fc6ff-234d-426e-9718-197e6836f4cc.png">|<img width="465" alt="image" src="https://user-images.githubusercontent.com/98358127/193646963-26fb2123-6b9b-4fd9-a2cf-b326b681032d.png">
