### ISSUE TITLE
Doesn't translate into chosen language after selecting "This page is not in <supported language>"

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#24747]
## Description 

Doesn't translate into chosen language after selecting "This page is not in <supported language>"

(Found while testing https://github.com/brave/brave-browser/issues/23813 - not sure this is valid.)

## Steps to Reproduce

1. change your OS language to Spanish
2. install 1.43.x
3. launch Brave
4. restart Brave (to pick up Brave Translate via Griffin)
5. load `bbc.com`
6. click on the "hamburger" menu
7. click on the last option, `La pagina no esta en ingles`
8. in the resulting `Idioma para translatar la pagina`, choose `frances`
9. click `Traducir` (Translate)

## Actual result:

Page gets translated into Spanish

![translate](https://user-images.githubusercontent.com/387249/185195967-686d2473-56e0-4ad5-b5a4-996444d58206.gif)

## Expected result:

Should the page be translated into French?  Or am I misunderstanding how this feature works?

## Reproduces how often: 

100%

## Brave version (brave://version info)

cc @MadhaviSeelam @rebron

**Comment by stephendonner** [comment]
@rebron @atuchin-m is this invalid?

Looks like I confused the source vs. intended language, here?

`Page language to translate` | `Language to Translate into`
----------------------------|---------------------------------
<img width="1312" alt="Screen Shot 2022-08-17 at 10 13 50 AM" src="https://user-images.githubusercontent.com/387249/185201501-a9c9a320-6513-44a7-af94-409a54766787.png"> | <img width="1312" alt="Screen Shot 2022-08-17 at 10 13 59 AM" src="https://user-images.githubusercontent.com/387249/185201523-4f8a7956-9485-49c5-9274-4ac73ade9dfa.png">

**Comment by stephendonner** [comment]
i.e. in my original example, my selection of `French` is actually the **translate-from-language** rather than the source **translate-to-language**.

**Comment by atuchin-m** [comment]
@stephendonner yep, `Page is not <lang>` changes the source language not the target one.
To change the target language there is an option named `Choose another language`.

The correct expected result:
If the page is actually in French (was incorrect detected as English page), then the option will trigger `fr => es` translation.

BTW that code is originated from Chromium and wasn't changed.
IMHO should be closed as invalid.

**Comment by stephendonner** [comment]
Thanks; happily closing this out!
