### ISSUE TITLE
fix typo in add-funds dialog text

### ISSUE THREAD

**Issue by bradleyrichter** [brave/brave-browser#2474]
![image](https://user-images.githubusercontent.com/13509546/49819760-10ad1600-fd2b-11e8-97f2-7bc8c3e6e671.png)

"cryto" should be changed to "crypto"

![image](https://user-images.githubusercontent.com/13509546/49837656-12db9880-fd5c-11e8-826e-878f81023add.png)

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.58.12 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

![screen shot 2018-12-13 at 11 08 51 am](https://user-images.githubusercontent.com/28145373/49951308-9e256d00-fec7-11e8-91bd-4d6c0d523347.png)
