### ISSUE TITLE
Remove 2 BAT minimum threshold for connecting/verifying with Uphold

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#24759]
## Description

Remove 2 BAT minimum threshold for connecting/verifying with Uphold.

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```

Brave | 1.44.83 Chromium: 105.0.5195.102 (Official Build) beta (64-bit)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | Windows 10 Version 21H2 (Build 19044.1889)

```

**Comment by stephendonner** [comment]
## Verified `PASSED` using `1.44.86, Chromium 105.0.5195.127` on a `Google Pixel XL` running `Android 9.0`.

#### First, reproduced the issue in current `1.43.89`:

example | example
---------|---------
![Screenshot_20220915-155049](https://user-images.githubusercontent.com/387249/190524717-cd634a0f-28fe-47f7-a8fd-bef5963b8196.png) | ![Screenshot_20220915-155746](https://user-images.githubusercontent.com/387249/190524333-bb4239c4-42fc-4806-9001-045e73fb4d02.png) | 

### Steps:
1. install `1.44.86`
2. launch Brave
3. enable Rewards
4. on `brave://rewards`, tap on `Unverified`
5. tap `Continue`
6. note no message about the 2-BAT-minimum requirement
7. also completed logging in/verifying my Uphold account, on staging, as a regression test


example | example | example
---------|----------|---------
![Screenshot_20220915-155049](https://user-images.githubusercontent.com/387249/190524414-8a2a10ea-522d-4125-a5c6-3bff5afc848d.png) | ![Screenshot_20220915-155055 (1)](https://user-images.githubusercontent.com/387249/190524416-c6be4176-f54a-4770-b36a-1f66dc1330b0.png) | ![Screenshot_20220915-162228](https://user-images.githubusercontent.com/387249/190525561-6fec1259-38ac-4749-af76-eb8b3f877e95.png)
