### ISSUE TITLE
Remove unused binance widget code

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#24755]
This is a follow issue of https://github.com/brave/brave-browser/issues/21653 to remove binance widget code .

**Comment by stoletheminerals** [comment]
At least we need to make the activity not exported or add proper sanitization.

**Comment by Uni-verse** [comment]
In progress on Samsung Galaxy S21 & Samsung Galaxy Tab S7 using the following build(s):

Brave	1.45.106 Chromium: 107.0.5304.36 (Official Build) (64-bit) 
Revision	2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}
OS	Android 12; Build/SP1A.210812.016

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` & `Samsung Galaxy Tab S7` using the following build(s):

```
Brave	1.45.106 Chromium: 107.0.5304.36 (Official Build) (64-bit) 
Revision	2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}
OS	Android 12; Build/SP1A.210812.016
```

- Verified widget stack is removed from the New Tab Page settings menu
- Verified NTP does not contain binance widget

Example | Example 
-|-
![screenshot-1666288707781](https://user-images.githubusercontent.com/17885425/197028128-7bde27f0-41fc-4896-8447-1551aad7a89b.png) | ![screenshot-1666288717132](https://user-images.githubusercontent.com/17885425/197028131-944a1553-19db-46e2-91a6-d5021d62ecea.png)
![screenshot-1666289990955](https://user-images.githubusercontent.com/17885425/197028217-d44a5a40-0d3d-456c-98c5-8a5a5d9ad894.png) | ![screenshot-1666290020481](https://user-images.githubusercontent.com/17885425/197028219-988e627e-1aff-43be-ac74-089d8ec5452b.png)
