### ISSUE TITLE
Allow capturing of multiple capture groups for debounce action regex-path

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#24750]
To debounce URLs like https://topnews--ru-ru.turbopages.org/topnews-ru.ru/s/2022/08/15/djoan-royling-prigrozili-smertu-za-podderjky-ryshdi-ty-sledyushaia/, we need to remove the `/s/`. We can do this by allowing for multiple capture groups for the action `regex-path` and then concatenating the matches. 

Currently the action validates that there is only one capture group.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.44.73 Chromium: 105.0.5195.68 (Official Build) beta (64-bit)
-- | --
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | Windows 11 Version 21H2 (Build 22000.856)
```
Verified with the testplan https://github.com/brave/brave-core/pull/14687#issue-1342114212

Install 1.44.73
launch Brave

URL 1: 
visit https://topnews--ru-ru.turbopages.org/topnews-ru.ru/s/2022/08/15/djoan-royling-prigrozili-smertu-za-podderjky-ryshdi-ty-sledyushaia/ should go to https://topnews-ru.ru/2022/08/15/djoan-royling-prigrozili-smertu-za-podderjky-ryshdi-ty-sledyushaia/

initial url|redirect url
----|----
<image width="859" alt="image" src="https://user-images.githubusercontent.com/98358127/188210176-a8a0ea9e-5448-49ab-acf6-a3b02d60204d.png">|<image width="859" alt="image" src="https://user-images.githubusercontent.com/98358127/188210289-eb8f1bbe-1d1c-4ac6-b22c-3dbe57e44068.png">


URL 2: 
visit https://08-mchs-gov-ru.turbopages.org/08.mchs.gov.ru/s/deyatelnost/press-centr/novosti/4726459 should go to https://08.mchs.gov.ru/deyatelnost/press-centr/novosti/4726459

initial url|redirect url
----|----
<image width="859" alt="image" src="https://user-images.githubusercontent.com/98358127/188211113-89483d4f-1e1f-4eab-a5fa-403b5edafcab.png">|<image width="859" alt="image" src="https://user-images.githubusercontent.com/98358127/188211316-67de24ef-f8d5-4ad0-aa4e-b9c18b74ba30.png">

URL 3:

https://dev-pages.brave.software/navigation-tracking/debouncing.html

Ex1|Ex2
---|---
<image width="859" alt="image" src="https://user-images.githubusercontent.com/98358127/188215616-449b5b27-fa58-4a58-bee5-0e258ebff998.png">|<image width="859" alt="image" src="https://user-images.githubusercontent.com/98358127/188215656-4f3e4600-ccf6-4d42-a188-5e20d8abe2d6.png">

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.44.79 Chromium: 105.0.5195.102 (Official Build) beta (x86_64)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | macOS Version 13.0 (Build 22A5331f)

### Steps:
1. installed `1.44.79`
2. launched Brave
3. loaded `https://topnews--ru-ru.turbopages.org/topnews-ru.ru/s/2022/08/15/djoan-royling-prigrozili-smertu-za-podderjky-ryshdi-ty-sledyushaia/`
4. confirmed it redirected to `https://topnews-ru.ru/2022/08/15/djoan-royling-prigrozili-smertu-za-podderjky-ryshdi-ty-sledyushaia/`
5. loaded `https://08-mchs-gov-ru.turbopages.org/08.mchs.gov.ru/s/deyatelnost/press-centr/novosti/4726459`
6. confirmed it redirected to `https://08.mchs.gov.ru/deyatelnost/press-centr/novosti/4726459`

step 3 | step 4 | step 5 | step 6
-------|-------|--------|-------
<img width="1312" alt="Screenshot 2022-09-08 at 1 40 38 PM" src="https://user-images.githubusercontent.com/387249/189221707-1365aafb-c751-4a15-a20f-579f4623bb79.png"> | <img width="1312" alt="Screenshot 2022-09-08 at 1 40 45 PM" src="https://user-images.githubusercontent.com/387249/189221710-bc180079-d702-446e-b9c9-aa519895c0c5.png"> | <img width="1312" alt="Screenshot 2022-09-08 at 1 41 36 PM" src="https://user-images.githubusercontent.com/387249/189221877-d653c119-6700-41d0-94a4-f6608aae1b8e.png"> | <img width="1312" alt="Screenshot 2022-09-08 at 1 41 43 PM" src="https://user-images.githubusercontent.com/387249/189221879-216864c2-2559-4347-a83a-610b3a548222.png">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.44.86 Chromium: 105.0.5195.127 (Official Build) beta (64-bit)
-- | --
Revision | 912488396852bf658ab32465980c0b93a3c27a83-refs/branch-heads/5195@{#1109}
OS | Linux
```
- Install 1.44.86
- launch Brave

#### URL 1 - PASSED

<details>

- visited https://topnews--ru-ru.turbopages.org/topnews-ru.ru/s/2022/08/15/djoan-royling-prigrozili-smertu-za-podderjky-ryshdi-ty-sledyushaia/ 
- verified it's redirected to https://topnews-ru.ru/2022/08/15/djoan-royling-prigrozili-smertu-za-podderjky-ryshdi-ty-sledyushaia/

initial url|redirect url
----|----
<image width="900" alt="url" src="https://user-images.githubusercontent.com/98358127/190535047-caf6cadd-1ef8-43a6-8680-eaa8376872f8.png">|<image width="900" alt="url" src="https://user-images.githubusercontent.com/98358127/190535183-de4b80fc-7dec-496d-8f3e-a15cd7388bad.png">

</details>

### URL 2 - PASSED

<details>

- visit https://08-mchs-gov-ru.turbopages.org/08.mchs.gov.ru/s/deyatelnost/press-centr/novosti/4726459 
- verified it's redirected to https://08.mchs.gov.ru/deyatelnost/press-centr/novosti/4726459

initial url|redirect url
----|----
<image width="900" alt="url" src="https://user-images.githubusercontent.com/98358127/190535454-e068fad2-d477-4687-8bf4-2a21ff84dbee.png">|<image width="900" alt="url" src="https://user-images.githubusercontent.com/98358127/190535591-44468c0f-920a-4189-bbd3-ab5135126925.png">
</details>

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 13` using the following build(s):

```
Brave | 1.44.95 Chromium: 106.0.5249.40 (Official Build) (32-bit)
--- | ---
Revision | fab1d91915d2722d6339aaa7f4e9ce44f1e9b103-refs/branch-heads/5249@{#442}
OS | Android 13; Build/T1B1.220819.006
```

Went through the STR/Cases outlined via https://github.com/brave/brave-core/pull/14687#issue-1342114212 and ensured the following:

**`Test Case #1 (URL #1)`**

* launch `1.44.95 Chromium: 106.0.5249.40` and restarted Brave
* ensured that `BraveDebounceStudy:Enabled` via `brave://version`

Ensured that visiting https://topnews--ru-ru.turbopages.org/topnews-ru.ru/s/2022/08/15/djoan-royling-prigrozili-smertu-za-podderjky-ryshdi-ty-sledyushaia redirected to https://topnews-ru.ru/2022/08/15/djoan-royling-prigrozili-smertu-za-podderjky-ryshdi-ty-sledyushaia without any issues.

**`Test Case #2 (URL #2)`**

* launch `1.44.95 Chromium: 106.0.5249.40` and restarted Brave
* ensured that `BraveDebounceStudy:Enabled` via `brave://version`

Ensured that visiting https://08-mchs-gov-ru.turbopages.org/08.mchs.gov.ru/s/deyatelnost/press-centr/novosti/4726459 redirected to https://08.mchs.gov.ru/deyatelnost/press-centr/novosti/4726459 without any issues.

**`Test Case #3 - Regex (multi)`**

**`Example (Disabled)`** | **`Example (Enabled)`**
---------------------------|--------------------------
![Screenshot_20220921-204246](https://user-images.githubusercontent.com/2602313/191634212-e87e06e6-3964-46cc-8578-103baaa1aed3.png) | ![Screenshot_20220921-203712](https://user-images.githubusercontent.com/2602313/191634215-08760008-5400-46a4-b843-2bab6d2cf253.png)
