### ISSUE TITLE
Improve Brave Ads rotating hash

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#24751]

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.44.93 Chromium: 105.0.5195.136 (Official Build) beta (64-bit)
-- | --
Revision | 872774b783d0e674186a3adcd2f92e7aa22a219c-refs/branch-heads/5195_124@{#4}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/14688

Verified hash is included in the confirmation

Verified hash was improved:
1.43.x:
![image](https://user-images.githubusercontent.com/34715963/191372907-bbd91a63-a3ad-4327-9f7a-d1f268109368.png)

1.44.x
![image](https://user-images.githubusercontent.com/34715963/191372743-85f4dfd5-4d39-4548-8455-d202a19ac869.png)
