### ISSUE TITLE
Uplift #24623 to 1.42.x - picking the Windows code signing certificate by hash

### ISSUE THREAD

**Issue by mherrmann** [brave/brave-browser#24763]
This change purely affects the build system. Uplifting will allow us to make some necessary changes to our CI infrastructure.

**Comment by kjozwiak** [comment]
Closing as this was uplifted into `1.42.x` via https://github.com/brave/brave-core/pull/14695#event-7216355866. **`Quick Note:`** this was merged into `1.42.x` but we never ended up doing a `1.42.x - Release #6` so I'll move this into `1.43.x` and delete the `1.42.x - Release #6` milestone.
