### ISSUE TITLE
Make update recommend dialog use sparkle's relaunch api

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#2477]
If relaunch is done from update recommend dialog on mac, relaunch will be failed because it uses chromium's relaunch api.

**Comment by kjozwiak** [comment]
@LaurenWags have you seen the prompt mentioned in https://github.com/brave/brave-core/pull/1046?

**Comment by LaurenWags** [comment]
@kjozwiak no I haven't - I'm not sure how to get it to display.
