### ISSUE TITLE
text alignment is off on VPN sell screen

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#24780]
## Description 

Alignment for second bullet in Brave VPN sell screen is off. Should be aligned with the rest of the text.

## Steps to Reproduce

   1. Click on VPN button in the toolbar.
   2. Notice Brave VPN sell screen.

## Actual result:

<img width="301" alt="screen_shot_2022-08-18_at_2 54 52_pm" src="https://user-images.githubusercontent.com/5951041/185477210-31131648-7d58-446f-8034-97f8166dcc0b.png">

## Expected result:
Second bullet item should be aligned with text

## Reproduces how often: 

Easily.

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes w/ flag enabled
- Can you reproduce this issue with the beta channel? yes w/ flag enabled
- Can you reproduce this issue with the nightly channel? yes w/ flag enabled

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by bsclifton** [comment]
This has been fixed 👍 
![image](https://github.com/brave/brave-browser/assets/4733304/fce6491a-c1a0-4bae-bde6-21324c9a693b)
