### ISSUE TITLE
Crash when changing the server for VPN

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#24797]
## Description 
We have crash because of p3a related changes. This issue is to resolve the issue.

## Steps to reproduce 

   1. Turn on the vpn
   2. Changing server from canada to germany should crash the app. 

## Actual result 
Crash happens on server change.

## Expected result
User should be able to change the server without any crash.

## Issue reproduces how often 
Easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.44.68` or higher for `1.44.x` verification 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 13` using the following build(s):

```
Brave | 1.44.95 Chromium: 106.0.5249.40 (Official Build) (32-bit)
--- | ---
Revision | fab1d91915d2722d6339aaa7f4e9ce44f1e9b103-refs/branch-heads/5249@{#442}
OS | Android 13; Build/T1B1.220819.006
```

Went through the STR/Cases outlined via https://github.com/brave/brave-browser/issues/24797#issue-1343924066 and ensured that you can switch between different VPN servers without Brave crashing.

Example of switching between a few servers:

**`Singapore`** | **`London, UK`** | **`France`**
------------------|-------------------|--------------
![Screenshot_20220921-144136](https://user-images.githubusercontent.com/2602313/191586829-4bb897c3-8067-4744-b941-9117e2ce3f80.png) | ![Screenshot_20220921-144156](https://user-images.githubusercontent.com/2602313/191586846-3c912921-32b3-417f-9500-c328547a77e6.png) | ![Screenshot_20220921-144122](https://user-images.githubusercontent.com/2602313/191586870-3cbe257a-b1db-4c94-9a63-855b12f5af16.png)
