### ISSUE TITLE
Integrate ethwallet

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#248]
https://github.com/brave/browser-laptop/pull/13177

**Comment by bbondy** [comment]
I'd be interested in following this more closely, could you perhaps to checkbox list items summary in the first comment as things progress? Thank you!

**Comment by diracdeltas** [comment]
should we close this?

**Comment by bsclifton** [comment]
@diracdeltas yup- good call 😄 

Closing as a dupe of https://github.com/brave/brave-browser/issues/4494
