### ISSUE TITLE
After wallet restoration the getSelectedAccount(CoinType.ETH) returns null (Brave-Core)

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#24800]
## Description 
After creating a new wallet or restoring wallet getSelectedAccount(CoinType.ETH,.... is returning null, causes unexpected behaviour while showing pending transaction for default accounts per coin.

## Steps to reproduce 

   1. Create or restore wallet
   2. Check return value of getSelectedAccount for ETH

## Actual result 
getSelectedAccount for ETH returns null 

## Expected result
the first auto created Ethereum account should be the selected account for ETH coin type

## Issue reproduces how often 
easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? y
- Can you reproduce this issue with the current Play Store Beta version? y
- Can you reproduce this issue with the current Play Store Nightly version? y

**Comment by darkdh** [comment]
This should be already fixed by https://github.com/brave/brave-core/pull/14135
cc @cypt4

**Comment by Pavneet-Sing** [comment]
@darkdh I have been debugging and testing this from the past week, getting `null` after restoring wallet or creating a new wallet.

**Comment by Pavneet-Sing** [comment]
FYI: I have created a separate issue to handle this manually on android : https://github.com/brave/brave-browser/issues/24929

**Comment by kjozwiak** [comment]
The above requires `1.44.95` or higher for `1.44.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.44.97 x64 build
- Verified steps from [brave/brave-core#14940](https://github.com/brave/brave-core/pull/14940)
- Verified no crash when creating account or restoring account
- Verified when creating a new account Solana account is created and selected as default
- Verified when restoring wallet via seed, first Solana account generate via the seed is restored and set as active network
----------
Verification passed on Samsung Tab A with Android 10 running 1.44.97 x64 build
- Verified steps from [brave/brave-core#14940](https://github.com/brave/brave-core/pull/14940)
- Verified no crash when creating account or restoring account
- Verified when creating a new account Solana account is created and selected as default
- Verified when restoring wallet via seed, first Solana account generate via the seed is restored and set as active network
