### ISSUE TITLE
Google Translate Extension proxied endpoint bug or not?

### ISSUE THREAD

**Issue by HGhostRevisionist88** [brave/brave-browser#24801]
Hello,

In the wiki page https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)#services-we-proxy-through-brave-servers

It mentions:
https://translate.googleapis.com/translate_a/element.js*
https://translate.googleapis.com/element/*/js/element/element_main.js
https://translate.googleapis.com/translate_static/js/element/main.js
https://translate.googleapis.com/translate_static/css/translateelement.css
https://www.gstatic.com/images/branding/product/*x/translate_24dp.png

When I use the extension (I was just testing it, I use Brave new translate feature) I see all the connections in DevTools and my Firewall connecting to google translate API IPs, I even blocked the two IPs with my firewall 173.194.68.94   and 173.194.68.95 which are google IPs and the translations didn't work.

So, the question is: wouldn't that mean they should go through Brave servers? 

I don't know to what extend the connections can go through Brave browser, so, are Google Translate supposed to do that or not? or it is like not exactly the translation itself but something else? like to avoid Brave servers getting blocked from the APIs? I tried to find information about this but nothing, and everything seems to be "it should go through Brave servers" like Safe Browsing or Component updates, but I better ask or report.

I use Nightly 1.44.53 but I don't think the proxied endpoints stuff only works on Stable or something.

For now I just want to understand if it is meant to be that way or not. but it not, then it is a bug and that's why I am opening this issue.

Thank you.

**Comment by fmarier** [comment]
Thanks for pointing that out. I have now revised the documentation to remove any references to the Google Translate endpoints.

These proxies were running for a short period of time back when we were considering enabling Google Translate in Brave. We eventually abandoned that approach and settled on a different service (see `brave://flags/#brave-translate-go`).

You are of course welcome to install third-party extensions for this, but it was never our intention to proxy those extensions.

**Comment by HGhostRevisionist88** [comment]
@fmarier 
Thank you very much!
I don't use Google Translate Extension, I use Brave Translate since very long time (even before added as a flag).
So I was confused when someone mentioned it, made some tests and reported it to make sure it was expected behavior or a bug.

So, thanks for fixing documentation! it's very important to avoid giving wrong information and then people think you are not doing what you are saying and you can't be trusted or something.

Have a nice day!

**Comment by fmarier** [comment]
Thanks for taking the time to report it!
