### ISSUE TITLE
Solana specific connection/permission changes in dapps 

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#24810]
Implement Solana specific dapps changes: https://github.com/brave/brave-browser/issues/22184

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.45.88 x64 build
- Verified steps from [brave/brave-core#15094](https://github.com/brave/brave-core/pull/15094)
- Verified `Connected` & `Disconnected` state is shown on panel when connected to a Solana Dapp or trust is revoked
- Encountered 
  -  https://github.com/brave/brave-browser/issues/25258
  - https://github.com/brave/brave-browser/issues/25897

Connected | Disconnected
-- | --
![image](https://user-images.githubusercontent.com/17010094/195050978-fbc18c8b-8efc-40e3-aca4-8e6ce6c477a3.png) | ![image](https://user-images.githubusercontent.com/17010094/195051003-8a90ffdf-c4c4-43fd-ab8f-61cce01ade0f.png)

-----------
Verification passed on Samsung Tab A with Android 10 running 1.45.88 x64 build
- Verified steps from [brave/brave-core#15094](https://github.com/brave/brave-core/pull/15094)
- Verified `Connected` & `Disconnected` state is shown on panel when connected to a Solana Dapp or trust is revoked
- Encountered 
  -  https://github.com/brave/brave-browser/issues/25258
  - https://github.com/brave/brave-browser/issues/25897

Connected | Disconnected
-- | --
![image](https://user-images.githubusercontent.com/17010094/195051106-5237b427-ce13-42c7-af30-af273824af48.png) | ![image](https://user-images.githubusercontent.com/17010094/195051071-7030a8bc-91a9-41bb-9768-0739e97417e2.png)
