### ISSUE TITLE
Add {?dns} to IPFS DOH overide

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#24813]
At the moment(0.14.0 kubo) libp2p does not support RFC8484 DOH url template, so it sends only POST requests.
So we remove {?dns} suffix from DOH template url before passing it to the IPFS config.
This suffix should be returned when libp2p will support RFC8484.
Related ticket in libp2p: https://github.com/libp2p/go-doh-resolver/issues/19

**Comment by vadimstruts** [comment]
The IPFS local node and scheme has been [deprecated](https://github.com/brave/brave-browser/issues/37735)
