### ISSUE TITLE
Include Solana in onboarding seed import/restore description text

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#24812]
## Description 

Only Ethereum was listed as a supported import. Solana should also be listed

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.44.86 Chromium: 105.0.5195.127 (Official Build) beta (64-bit) 
-- | --
Revision | `912488396852bf658ab32465980c0b93a3c27a83-refs/branch-heads/5195@{#1109}`
OS | Linux

- Verified onboarding message incudes importing Solana account via seed restore
![image](https://user-images.githubusercontent.com/17010094/190396957-72c13399-a6d5-4037-aa47-412a139fc54a.png)

------------------------
Verification passed on

Brave | 1.44.86 Chromium: 105.0.5195.127 (Official Build) beta (64-bit) 
-- | --
Revision | `912488396852bf658ab32465980c0b93a3c27a83-refs/branch-heads/5195@{#1109}`
OS | Windows 11 Version 21H2 (Build 22000.795)

- Verified onboarding message incudes importing Solana account via seed restore
![image](https://user-images.githubusercontent.com/17010094/190397101-06b7c9de-1c18-49b0-aa04-a0441a09890e.png)

------------------------
Verification passed on

Brave | 1.44.86 Chromium: 105.0.5195.127 (Official Build) beta (arm64)
-- | --
Revision | `912488396852bf658ab32465980c0b93a3c27a83-refs/branch-heads/5195@{#1109}`
OS | macOS Version 12.4 (Build 21F79)

- Verified onboarding message incudes importing Solana account via seed restore
![image](https://user-images.githubusercontent.com/17010094/190397257-f8a61475-955b-4240-b3c8-7db2fdaaeca7.png)
