### ISSUE TITLE
add notification badge to desktop

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#24818]
After user submits send transaction in the wallet there is no indication that it is in progress, so user may think that it has failed. 

Update: badge for pending transactions instead of submitted transactions.

**Comment by HEagle18** [comment]
Maybe addressed in new UI

**Comment by jamesmudgett** [comment]
https://github.com/brave/brave-browser/issues/22970

**Comment by jamesmudgett** [comment]
![Screen Shot 2022-10-28 at 8 44 31 AM](https://user-images.githubusercontent.com/318119/198620846-b2ce2d0e-f359-47fc-a047-8317c7da42cf.png)
![Screen Shot 2022-10-28 at 8 45 04 AM](https://user-images.githubusercontent.com/318119/198620858-d03164a3-ab42-42c7-9aab-8fc8db22c1ae.png)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta  (64-bit) 
-- | --
Revision | `46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}`
OS | Linux

- Verified steps from [brave/brave-core#16256](https://github.com/brave/brave-core/pull/16256)
- Verified wallet notification badge shows pending number of transactions for that network
- Encountered [#28804](https://github.com/brave/brave-browser/issues/28804)

https://user-images.githubusercontent.com/17010094/221932210-abfd7409-1f1f-449c-aa62-1a177c247174.mp4
