### ISSUE TITLE
Sending from HW filecoin acc doesn't work

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#24824]
When send filecoins from HW filecoin acc, wallet asks to open ETH application even Filecoin app is opened,
![image](https://user-images.githubusercontent.com/106654560/185696523-2e3fc5e7-f8b6-4ae5-a660-9e7027ae3ea0.png)
On ETH app nothing happens.

## Reproduces how often: 
100%

## Version/Channel Information:
1.41+ is affected

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.43.85 Chromium: 105.0.5195.68 (Official Build) (64-bit)
-- | --
Revision | `ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}`
OS | Windows 11 Version 21H2 (Build 22000.856)

- Verified able to submit transactions via Ledger for Filecoin
- Encountered [#25012](https://github.com/brave/brave-browser/issues/25012)

https://user-images.githubusercontent.com/17010094/187676401-9968d253-7800-49f6-a75f-1cce9dfee80c.mp4
