### ISSUE TITLE
"Don't ask me again" setting in "Close all tabs?" prompt has no affect from private window

### ISSUE THREAD

**Issue by oldhen** [brave/brave-browser#24829]
## Description 
When closing a private window with multiple tabs open, the **Don't ask me again** setting in the **Close all tabs?** prompt has no affect.

## Steps to Reproduce
1. Ensure **Warn me before closing window with multiple tabs** setting is **on**
2. Open a private window
3. Open multiple tabs
4. Close private window
5. Select **Don't ask me again** setting when prompted with **Close all tabs?**
6. Open a private window
7. Open multiple tabs
8. Close private window

## Actual result:
* **Close all tabs?** prompt appears
* **Warn me before closing window with multiple tabs** setting is still **on**

## Expected result:
* Private window should close without prompt
* **Warn me before closing window with multiple tabs** setting should be **off**

## Reproduces how often: 
Always

## Brave version (brave://version info)
* 1.42.97 Chromium: 104.0.5112.102 (Official Build) (64-bit) 
* Windows 10 Version 21H2 (Build 19044.1889)

**Comment by bsclifton** [comment]
cc: @spylogsster

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.44.70 Chromium: 105.0.5195.68 (Official Build) beta (64-bit)
-- | --
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | Windows 11 Version 21H2 (Build 22000.856)
```
Verified and reproduced the issue using STR from https://github.com/brave/brave-browser/issues/24829#issue-1344940575

 `1.42.83 Chromium: 104.0.5112.69`

Ex1|Ex2|Ex3|Ex4
----|----|----|----
<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/187775219-2439b40c-f193-422a-9810-3381207e85e1.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/187775239-ac059847-c717-4007-a4e7-0e404bb4829a.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/187775670-8e8f9d36-7d37-472a-bc93-2007645ce2e0.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/187775694-4d9bbc84-7192-4f4c-ac82-ec97ead281aa.png">

####Steps:

1. Install 1.44.70
2. launch Brave
3. ensure `Warn me before closing window with multiple tabs` setting is on` in `brave://settings/braveHelpTips`
4. click `Hamburger` menu to open `New Private Window`
5. open multiple tabs in the private window
6. click `x` to close the private window
7. check the check box for  `Don't ask me again` setting  in Close all tabs? modal
8. confirmed `Warn me before closing window with multiple tabs` toggle is  `OFF`
9. run above steps 4-6 again

####Confirmed private window closed without `Close all tabs?` modal  

step 3|step 4|step5-7|step8|step9
----|----|----|----|----
<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/187776264-08f56b43-b323-4b33-aae6-347801c3c414.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/187779029-cefcba2b-1d8b-4774-9801-dfcc012b8500.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/187776292-eced8a8b-703e-4e9c-a597-c7b73f5c8b3f.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/187776354-eb53acc5-c221-4374-ba6d-b26df86f5625.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/187779993-913ad8f5-d37c-40e0-972e-877e59b00272.png">
