### ISSUE TITLE
Icon for Extensions in brave browser for desktop

### ISSUE THREAD

**Issue by Faizan711** [brave/brave-browser#24835]
There should be an icon for extensions as it is difficult to use extensions in brave.
It would be very helpful.

**Comment by rebron** [comment]
@Faizan711 There is an icon for extensions in Brave. Are you not seeing one? You have to have an extension installed first from https://chrome.google.com/webstore/category/extensions. Once an extension is installed an icon will appear.

**Comment by rebron** [comment]
<img width="358" alt="Screenshot 2022-08-23 at 1 29 52 PM" src="https://user-images.githubusercontent.com/5951041/186259651-1a6a9aa5-6f79-4bad-b07f-6297c372a9ff.png">
