### ISSUE TITLE
New blank tab isn't blank but gray

### ISSUE THREAD

**Issue by cogabe** [brave/brave-browser#24834]
## Description 
Since the last update v1.42.97, when "new tab" is set to blank, it used to be white, now it is gray.

## Steps to Reproduce

   1. Set new tab page to "blank" like this:

![Screen Shot 2022-08-21 at 10 51 16 AM](https://user-images.githubusercontent.com/19887885/185783647-5068efcf-83d9-4bb1-983b-12ae40f6d6b1.png)

   2. Open a new tab

## Actual result:

![Screen Shot 2022-08-21 at 10 50 24 AM](https://user-images.githubusercontent.com/19887885/185783511-7a1ada0d-48df-47f4-b05e-52b25a682091.png)

## Expected result:
Page should be blank like this:

![Screen Shot 2022-08-21 at 10 50 17 AM](https://user-images.githubusercontent.com/19887885/185783519-7ccfa93e-b984-47f2-9921-3f19c1ce1d01.png)

## Reproduces how often: 

Every time we open a new tab

## Brave version (brave://version info)

1.42.97 Chromium: 104.0.5112.102 (Official Build) (x86_64) - macOS Version 10.14.6 (Build 18G103)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

None

**Comment by rebron** [comment]
<img width="1422" alt="Screenshot 2022-12-06 at 10 42 56 AM" src="https://user-images.githubusercontent.com/5951041/205995266-12b051a3-cc51-49f0-8bb7-9b9c14ad02b1.png">
Hi @cogabe This looks like it's new tab page is blank here and not gray with version 1.46.134. 
Going to close this one off. Please reopen if you're still seeing this issue.
