### ISSUE TITLE
Add password protection to private key reveal

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#24830]
We first implemented the protection only in desktop UI side in https://github.com/brave/brave-core/pull/14390.
We still need to
- Protect `GetPrivateKeyForKeyringAccount` API with password argument which will be validated in the backend.
- Update the frontend code in desktop with the API change.
- Update Android frontend code for UI side password inputs similar to https://github.com/brave/brave-core/pull/14390 and also update the call of `GetPrivateKeyForKeyringAccount` to pass password to backend.
These three items need to be consolidated in one PR.

**Comment by yrliou** [comment]
cc @kdenhartog

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.45.88 x64 build
- Verified steps from [brave/brave-core#14731](https://github.com/brave/brave-core/pull/14731)
- Verified there is a new password prompt when Private Key is selected from Account details view
- Verified Fingerprint prompt is shown if set
- Verified private key is only shown when correct password is typed in
----------
Verification passed on Samsung Tab A with Android 10 running 1.45.88 x64 build
- Verified steps from [brave/brave-core#14731](https://github.com/brave/brave-core/pull/14731)
- Verified there is a new password prompt when Private Key is selected from Account details view
- Verified Fingerprint prompt is shown if set
- Verified private key is only shown when correct password is typed in

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (64-bit)
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | Linux

- Verified steps from [brave/brave-core#14731](https://github.com/brave/brave-core/pull/14731)
- Verified there is a new password prompt when Private Key is selected from Account details view
- Verified private key is only shown when correct password is typed in

![image](https://user-images.githubusercontent.com/17010094/195871711-1e9985e4-e201-41dd-9401-0929510bc188.png) | ![image](https://user-images.githubusercontent.com/17010094/195871842-3aa0ba69-29d1-407e-9180-31a03eebf6ab.png) | ![image](https://user-images.githubusercontent.com/17010094/195871906-8c8661a9-0411-43e3-ae98-11a9d5e1f156.png) | ![image](https://user-images.githubusercontent.com/17010094/195872041-66076a5d-e973-4a20-bb3f-3c6477c4ed2f.png) 
-- | -- | -- | --

----------------
Verification passed on 

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (64-bit)
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | Windows 11 Version 21H2 (Build 22000.978)

- Verified steps from [brave/brave-core#14731](https://github.com/brave/brave-core/pull/14731)
- Verified there is a new password prompt when Private Key is selected from Account details view
- Verified private key is only shown when correct password is typed in

![image](https://user-images.githubusercontent.com/17010094/195871120-014b8d54-04bc-40f2-a8e8-cd44c4d05d57.png) | ![image](https://user-images.githubusercontent.com/17010094/195871179-29490236-71e1-4bf3-b050-409fb53a0a0a.png) | ![image](https://user-images.githubusercontent.com/17010094/195871211-71027fb9-3ec5-4db9-8f5d-cff9a29f26c9.png) | ![image](https://user-images.githubusercontent.com/17010094/195871326-574ddcea-d849-4d43-bb55-3adc10729014.png)
-- | -- | -- | --
----------------
Verification passed on 

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (arm64)
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | macOS Version 12.6 (Build 21G115)

- Verified steps from [brave/brave-core#14731](https://github.com/brave/brave-core/pull/14731)
- Verified there is a new password prompt when Private Key is selected from Account details view
- Verified private key is only shown when correct password is typed in

![image](https://user-images.githubusercontent.com/17010094/195872903-c5aaad81-6632-47d1-8a6d-2db389dca751.png) | ![image](https://user-images.githubusercontent.com/17010094/195872931-cc683513-9d71-4e43-aee9-b7869f7b96c2.png) | ![image](https://user-images.githubusercontent.com/17010094/195872941-daceafaa-8ce2-45a4-adc1-302931854092.png) | ![image](https://user-images.githubusercontent.com/17010094/195872951-656b0bdd-99ea-47b0-a100-0bcbbedb35ba.png)
-- | -- | -- | --
