### ISSUE TITLE
Unable to setup sync with multiple profiles

### ISSUE THREAD

**Issue by danhab99** [brave/brave-browser#24839]
## Description 

I want to add my work profile to my personal computer. I created a new profile and tried to setup a new sync chain with it but nothing happens. In the "Manage your synced devices" page, there is no device in the list, not even the computer I'm using (i.e "This Device"). On my work machine, brave lists my laptop as on the sync chain but not my personal computer. 

## Steps to Reproduce

   1. Have and use Brave for personal use, use your default profile for awhile.
   2. Create a new Brave profile
   3. Go to sync settings and click "start using sync"
   4. Choose "I have a sync code"
   5. Enter sync code form existing profile
   6. Observe fault

## Actual result:

No devices listed, nothing sync

![Screenshot_2022-08-21-35_1021x810](https://user-images.githubusercontent.com/13894263/185811515-6d30c722-ef91-413b-b861-ae9d87f5b21f.png)

## Expected result:

Brave sync works

## Reproduces how often: 

Chronic

## Brave version (brave://version info)

<details>
<summary>My personal computer</summary>

Brave | 1.38.111 Chromium: 101.0.4951.54 (Official Build) (64-bit)
-- | --
Revision | 67da1aeb32cedd27634ca6634fb79cbd85d3f0ab-refs/branch-heads/4951@{#1126}
OS | Linux
JavaScript | V8 10.1.124.11
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36
Command Line | /usr/lib/brave-bin/brave --enable-crashpad --disable-client-side-phishing-detection --disable-domain-reliability --enable-dom-distiller --no-pings --component-updater=url-source=https://go-updater.brave.com/extensions --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --variations-insecure-server-url=https://variations.brave.com/seed --flag-switches-begin --disable-features=SystemNotifications --flag-switches-end
Executable Path | /usr/lib/brave-bin/brave
Profile Path | /home/dan/.config/BraveSoftware/Brave-Browser/Default
Variations | AdRewardsStudy:NextPaymentDayAdvertiserSplitTestStudy:GroupBBraveAds.AdServingStudy:DefaultAdNotificationsPerHour=10/MaximumAdNotificationsPerDay=100/MaximumInlineContentAdsPerHour=12/MaximumInlineContentAdsPerDay=60/AdServingVersion=1BraveAds.FrequencyCappingStudy:ExcludeAdIfWithinTimeWindow=0hBraveAds.UserActivityStudy:Triggers=NTPSI/TimeWindow=15m/Threshold=0.0/IdleTimeThreshold=5sBraveDebounceStudy:EnabledConversionsStudy:NewDefaultPatternDefault1pBlockingStudy:DisabledDisableBlobPartitioning:DefaultDisableReduceLanguage:EnabledEphemeralStorageStudy:EnabledExtendedVariationsSafeMode5:Default5FirstPartyEphemeralDomainBlockStudy:EnabledForceDisableBlinkFeatures:EnabledNavigationThreadingOptimizationsCompatOldVersions:DisabledPartitionBlinkMemoryCacheStudy:EnabledPartitionConnectionsByNetworkIsolationKeyStudy:EnabledPermissionLifetimeReleaseStudy:EnabledRequestAdsEnabledApiStudy:EnabledSpeedreaderReleaseStudy:Enabled
</details>

<details>
<summary>My work laptop</summary
<html>
<body>

Brave | 1.42.97 Chromium: 104.0.5112.102 (Official Build) (64-bit)
-- | --
Revision | 8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}
OS | Windows 10 Version 21H2 (Build 19044.1889)
JavaScript | V8 10.4.132.22
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36
Command Line | "C:\Users\DHabot\AppData\Local\BraveSoftware\Brave-Browser\Application\brave.exe" --disable-domain-reliability --enable-dom-distiller --component-updater=url-source=https://go-updater.brave.com/extensions --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --variations-insecure-server-url=https://variations.brave.com/seed --enable-features --disable-features --flag-switches-begin --flag-switches-end
Executable Path | C:\Users\DHabot\AppData\Local\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path | C:\Users\DHabot\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Active Variations | AdRewardsStudy:NextPaymentDayAdvertiserSplitTestStudy:GroupABraveAds.AdServingStudy:DefaultAdNotificationsPerHour=10/MaximumAdNotificationsPerDay=100/MaximumInlineContentAdsPerHour=12/MaximumInlineContentAdsPerDay=60/AdServingVersion=1BraveAds.FrequencyCappingStudy:ExcludeAdIfWithinTimeWindow=0hBraveAds.UserActivityStudy:Triggers=NTPSI/TimeWindow=15m/Threshold=0.0/IdleTimeThreshold=5sBraveDebounceStudy:EnabledConversionsStudy:NewDefaultPatternDefault1pBlockingStudy:DisabledDisableReduceLanguage:EnabledEphemeralStorageStudy:EnabledExtendedVariationsSafeMode5:SignalAndWriteViaFileUtil5FirstPartyEphemeralDomainBlockStudy:EnabledForceDisableBlinkFeatures:EnabledPartitionBlinkMemoryCacheStudy:EnabledPartitionConnectionsByNetworkIsolationKeyStudy:EnabledPermissionLifetimeReleaseStudy:EnabledRequestAdsEnabledApiStudy:EnabledSpeedreaderReleaseStudy:Enabled

</body>
</html>
</details>

## Version/Channel Information:

- Can you reproduce this issue with the current release?  yes
- Can you reproduce this issue with the beta channel? cant try
- Can you reproduce this issue with the nightly channel? cant try

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? no

## Miscellaneous Information:

Found this page while trying to set this up. This is the error that's in the red rows in that sidebar:

```
Error: GenerateCryptoErrorsForTypes@components/sync/driver/data_type_manager_impl.cc:35, cryptographer error was encountered: 
```

![Screenshot_2022-08-21-28_1920x1080](https://user-images.githubusercontent.com/13894263/185811746-f5551cb7-6426-4e5d-a338-53aef3e1bf8a.png)

**Comment by AlexeyBarabash** [comment]
Just tried - I can setup two profiles of the same browser to be at the same sync chain:

![image](https://user-images.githubusercontent.com/24739341/211586448-fceaf135-b7e0-4122-a6a0-8b66c3b5a724.png)


![image](https://user-images.githubusercontent.com/24739341/211586596-09853ec2-4818-4390-b5b2-18f22fd06a90.png)

@danhab99 is the issue still present for you?

**Comment by danhab99** [comment]
It's been months since so I guess this got fixed some time in the past. I have managed to have two profiles with different sync chains as of today so I guess this is closed.

**Comment by AlexeyBarabash** [comment]
thanks @danhab99 !
