### ISSUE TITLE
[Follow up to #23928] Wallet onboarding conversion P3A question

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#24844]
## Description 
[Follow up to #23928] Wallet onboarding conversion P3A question

## Steps to reproduce 

   1. Clean profile
   2. Visit `brave://local-state/` check for `Brave.Wallet.OnboardingConversion`, doesn't show
   3. Open Wallet from menu, do not create wallet, quit and reluanch
   4. Check metric on local-state, doesn't list
   5. Create Wallet, quit and reluanch
   6. Check metric on local-state, shows value `1`

## Actual result 
`Brave.Wallet.OnboardingConversion` is not shown when wallet onboarding is launched but no wallet is created

## Expected result
Should show the metric similar to desktop

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version:12
   
## Brave version
1.43.74

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @DJAndries @GeetaSarvadnya

**Comment by kjozwiak** [comment]
The above will require `1.43.82` or higher for `1.43.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.43.82 x64 build
- Verified steps from [brave/brave-core#14081](https://github.com/brave/brave-core/pull/14081)
- Verified metric is only shown on a clean profile
- Verified metric is not available on upgrade profile with wallet created before upgrade
- Verified metric is available on upgrade profile when wallet is not created before upgrade

<details>
<summary><b><code>Brave.Wallet.OnboardingConversion = 0</code> - PASSED</b></summary>

- Clean profile 
- Verify `Brave.Wallet.OnboardingConversion` is not available in `brave://local-state` 
- Click on Wallet from menu 
- Close the onboarding without creating a wallet 
- Verified `Brave.Wallet.OnboardingConversion` metric is shown in `brave://local-state` and value is set to `0`

No Metric | Metric set to 0 
-- | --
![image](https://user-images.githubusercontent.com/17010094/186896551-20a882b6-2ebf-4080-a5c9-d238b05bb928.png) | ![image](https://user-images.githubusercontent.com/17010094/186896536-751fd2eb-735c-4b08-8147-603878fe07c4.png)

</details>

<details>
<summary><b><code>Brave.Wallet.OnboardingConversion = 1</code> - PASSED</b></summary>

- Clean profile 
- Verify `Brave.Wallet.OnboardingConversion` is not available in `brave://local-state` 
- Click on Wallet from menu 
- Close the onboarding without creating a wallet 
- Verified `Brave.Wallet.OnboardingConversion` metric is shown in `brave://local-state` and value is set to `0`
- Open Wallet again and create a wallet this time 
- Verified `Brave.Wallet.OnboardingConversion` metric is shown in `brave://local-state` and value is set to `1`

No Metric | Metric set to 1 
-- | --
![image](https://user-images.githubusercontent.com/17010094/186896551-20a882b6-2ebf-4080-a5c9-d238b05bb928.png) | ![image](https://user-images.githubusercontent.com/17010094/186896623-b72e5dc1-ffa3-41a5-be6b-8cd05412ac3f.png)

</details>
