### ISSUE TITLE
Error message isn't dismissed when browser is closed

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#2484]
## Description 

Error message isn't dismissed when browser is closed

## Steps to Reproduce

   1. Disconnect device from network
   2. Open brave://bravesync and click on `I am new to Sync`
   3. Enter device name and click `Setup Sync`, shows error message
   4. Close browser without dismissing the popup notification
   5. Restart browser and open sync page and click on `I am new to Sync`, error popup message is retained 

## Actual result:

https://drive.google.com/open?id=1iCn5ZbFxvc9tVw3vivKiSPi0j7mm2LPF

## Expected result:
Popup error message should be dismissed when browser is closed

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta(64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by btlechowski** [comment]
Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Windows 7 x64

**Comment by GeetaSarvadnya** [comment]
Verification passed on 


Brave | 0.59.12 Chromium: 72.0.3626.17 (Official Build) beta (64-bit)
-- | --
Revision | 08d2140079f8db14c9eb885a803d231b1a30e817-refs/branch-heads/3626@{#315}
OS | Windows

- Verified the STR mentioned in description

Verification passed on 

Brave	0.59.12 Chromium: 72.0.3626.17 (Official Build) beta (64-bit)
Revision	08d2140079f8db14c9eb885a803d231b1a30e817-refs/branch-heads/3626@{#315}
OS	Linux

- Verified the STR mentioned in description
