### ISSUE TITLE
"Contact Support" from adaptive captcha doesn't work with WebUI rewards panel

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#24846]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/22423

When Rewards WebUI panel is enabled, the "Contact support" button doesn't open the Brave Help Center in a new tab. This works as expected when Rewards WebUI panel is not enabled.

## Steps to Reproduce

   1. Clean profile 1.43.x, staging env
   2. Relaunch browser so that griffin seed is pulled and `BraveRewardsWebUiPanelStudy:Enabled` is shown on brave://version
   3. Enable Rewards
   4. View an ad
   5. Schedule an adaptive captcha
   6. Trigger adaptive captcha
   7. Fail solving captcha w/ max attempts
   8. Click on "Contact support" button

## Actual result:

Brave Help Center does not open in a new tab after clicking "Contact support" below.

<img width="431" alt="Screen Shot 2022-08-22 at 9 10 01 AM" src="https://user-images.githubusercontent.com/28145373/185929145-ca739f5c-d4ba-4486-ac63-a8895d0f504a.png">

## Expected result:

Brave Help Center should open in a new tab

## Reproduces how often: 

easily

## Brave version (brave://version info)

```
Brave | 1.43.74 Chromium: 104.0.5112.102 (Official Build) beta (x86_64)
-- | --
Revision | 8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}
OS | macOS Version 12.5.1 (Build 21G83)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a (works fine without webUI panel enabled)
- Can you reproduce this issue with the beta channel? yes 1.43.x
- Can you reproduce this issue with the nightly channel? yes 1.44.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @Miyayes @zenparsing @rebron

**Comment by LaurenWags** [comment]
Adding `QA/Blocked` until this is uplifted to 1.43.x

**Comment by GeetaSarvadnya** [comment]
Reproduced the issue in Windows 10 x64

Brave | 1.43.78 Chromium: 104.0.5112.102 (Official Build) beta (64-bit)
-- | --
Revision | 8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}
OS | Windows 10 Version 21H2 (Build 19044.1889)

**Comment by kjozwiak** [comment]
The above will require `1.43.81` or higher for `1.43.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
Brave | 1.43.82 Chromium: 105.0.5195.58 (Official Build) (64-bit)
-- | --
Revision | 1907e1693887af4463221a10247360b7a056db49-refs/branch-heads/5195_47@{#3}
OS | Windows 10 Version 21H2 (Build 19044.1889)

```
The griffin study `BraveRewardsWebUiPanelStudy:Enabled` is not been added in RC hence I was not able to see this study in brave://version. Verified the issue by enabling/disabling the flag `#brave-rewards-webui-panel` via brave://flags

### `#brave-rewards-webui-panel` - Enabled

Ensured that click on `Contact support` opens up the `Brave Help Center` in a new tab

Example | Example | Example
-- | -- | --
![image](https://user-images.githubusercontent.com/38657976/186901941-1ea6b461-091d-452a-8893-af9d77be3088.png) | ![image](https://user-images.githubusercontent.com/38657976/186901982-3bb7ee04-9f56-428a-ac12-adb18b9b71fa.png) | ![image](https://user-images.githubusercontent.com/38657976/186902094-51347b8a-d7f6-4643-94a8-25961c3e971f.png)


### `#brave-rewards-webui-panel` - Disabled

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.43.81 Chromium: 104.0.5112.102 (Official Build) (x86_64)
-- | --
Revision | 8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}
OS | macOS Version 12.5.1 (Build 21G83)
```

Verified STR from description with `brave://flags/#brave-rewards-webui-panel` manually enabled since Griffin study is not in Release channel yet.
Confirmed clicking on "Contact support" opens Brave Help Center in a new tab.

Example | Example
-- | --
<img width="1196" alt="Screen Shot 2022-08-26 at 11 38 16 AM" src="https://user-images.githubusercontent.com/28145373/186942216-62ab6ec2-05f6-4b50-b3c1-8cbca2055cc0.png"> | <img width="1197" alt="Screen Shot 2022-08-26 at 11 38 25 AM" src="https://user-images.githubusercontent.com/28145373/186942220-ad953518-bfc1-4cfc-b1e4-7c006e90787a.png">
