### ISSUE TITLE
Add dedicated transaction review screen for ETHSwap

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#24860]
We're now able to parse 0x Swap transactions into an `ETHSwap` type. Implement a dedicated swap review screen to display this information.

|Figma| https://www.figma.com/file/jZrVG7dsi5npXFTDC6LDGn/Crypto?node-id=4520%3A138295|
-|-

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.45.104 Chromium: 106.0.5249.126 (Official Build) beta (64-bit) 
-- | --
Revision | `fb2e06d2dee20fe0c804528502b5ad72c613abd9-refs/branch-heads/5249_118@{#3}`
OS | Linux

- Verified test plan from [brave/brave-core#14745](https://github.com/brave/brave-core/pull/14745)
- Verified transaction review screen is as per spec and shows the correct network/token icons 

https://user-images.githubusercontent.com/17010094/196640519-c20cdafa-2f1a-4819-bf66-2c3373a9108b.mp4


------------------------
Verification passed on

Brave | 1.45.104 Chromium: 106.0.5249.126 (Official Build) beta (64-bit) 
-- | --
Revision | `fb2e06d2dee20fe0c804528502b5ad72c613abd9-refs/branch-heads/5249_118@{#3}`
OS | Windows 11 Version 22H2 (Build 22621.674)

- Verified test plan from [brave/brave-core#14745](https://github.com/brave/brave-core/pull/14745)
- Verified transaction review screen is as per spec and shows the correct network/token icons 

https://user-images.githubusercontent.com/17010094/196640436-7c1602de-7292-4532-91ef-fb9935618704.mp4


------------------------
Verification passed on

Brave | 1.45.104 Chromium: 106.0.5249.126 (Official Build) beta (arm64)
-- | --
Revision | `fb2e06d2dee20fe0c804528502b5ad72c613abd9-refs/branch-heads/5249_118@{#3}`
OS | macOS Version 12.4 (Build 21F79)

- Verified test plan from [brave/brave-core#14745](https://github.com/brave/brave-core/pull/14745)
- Verified transaction review screen is as per spec and shows the correct network/token icons 

https://user-images.githubusercontent.com/17010094/196641530-878eeb34-6286-4e8b-bf49-8d052d05fe36.mov
