### ISSUE TITLE
Select account list item UI - clickable zone is too small

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#24861]
## Description 

Only the account name is clickable.
Account name, icon & address should all be clickable.

https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1660937690832889

## Steps to Reproduce

   1. Unlock wallet
   2. Create a second wallet account from the accounts screen (if needed)
   3. Navigate to the Send Tab of the buy/send/swap widget
   4. Click the wallet account
   5. The account selection list should appear
   6. Attempt to click the account icon or address

## Actual result:

Selection event is not triggered unless the account name is clicked

## Expected result:
Selection event is triggered when either the account's name, icon or address is clicked

## Reproduces how often: 

Easy

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (64-bit) 
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | Linux

- Verified steps from [brave/brave-core#14744](https://github.com/brave/brave-core/pull/14744)
- Verified click area is bigger than before 

https://user-images.githubusercontent.com/17010094/196217108-9b67a468-3548-4dbe-a159-4f929f5bcca8.mp4


------------------------
Verification passed on

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (64-bit) 
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | Windows 11 Version 21H2 (Build 22000.978)

- Verified steps from [brave/brave-core#14744](https://github.com/brave/brave-core/pull/14744)
- Verified click area is bigger than before 

https://user-images.githubusercontent.com/17010094/196217200-774f848a-6105-481f-858f-68880429aa46.mp4


------------------------
Verification passed on

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (arm64)
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [brave/brave-core#14744](https://github.com/brave/brave-core/pull/14744)
- Verified click area is bigger than before 

https://user-images.githubusercontent.com/17010094/196210591-4d229a50-e820-487e-9946-fdacc60933b2.mov
