### ISSUE TITLE
Missing icons in brave://settings and advanced settings pages

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#24872]
## Description 

Missing icons in Privacy & Security sections in Settings

## Steps to Reproduce

   1. install `1.44.60`
   2. launch Brave
   3. open `brave://settings/privacy`
   4. look at the (missing) icons below `Automatically send diagnostic reports`

## Actual result:

<img width="1223" alt="Screen Shot 2022-08-22 at 6 40 42 PM" src="https://user-images.githubusercontent.com/387249/186049991-0d9710a0-fedd-42eb-8328-4b2d5d3837ca.png">

## Expected result:

<img width="1237" alt="Screen Shot 2022-08-22 at 6 42 38 PM" src="https://user-images.githubusercontent.com/387249/186050033-b23646b6-ef01-43b2-9c73-964005371cc6.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.44.60 Chromium: 105.0.5195.37 (Official Build) nightly (x86_64)
-- | --
Revision | 5f67e9f258cc28ab970e57572290edf1863ee3c5-refs/branch-heads/5195@{#621}
OS | macOS Version 11.6.8 (Build 20G730)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `No`
- Can you reproduce this issue with the nightly channel? `Yes`

cc @brave/qa-team @mkarolin @rebron @emerick

**Comment by mkarolin** [comment]
This is not specific to cr105, seems to be present in `Brave is up to date
[Version 1.44.60 Chromium: 104.0.5112.102 (Official Build) nightly (64-bit)](https://brave.com/latest/)` as well.
cc: @fallaciousreasoning looks to be related to https://github.com/brave/brave-core/pull/14347

**Comment by GeetaSarvadnya** [comment]
Missing icons in brave://settings/autofill
![image](https://user-images.githubusercontent.com/38657976/186074152-218a3db8-96c2-44ea-9f52-1c8711135e85.png)

**Comment by fallaciousreasoning** [comment]
I'll take a look

**Comment by GeetaSarvadnya** [comment]
@fallaciousreasoning The icons are missing in the pages below:

**brave://settings/content**
![image](https://user-images.githubusercontent.com/38657976/186326897-dff17b0b-e9c5-4573-81f7-78dc3988ca8b.png)

**Comment by rebron** [comment]
@fallaciousreasoning I think we need an uplift for this for 1.44.x

**Comment by kjozwiak** [comment]
1.44.78

**Comment by kjozwiak** [comment]
The above requires `1.44.78` or higher for `1.44.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.44.78 Chromium: 105.0.5195.102 (Official Build) beta (x86_64)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | macOS Version 13.0 (Build 22A5331f)

#### Confirmed icons were restored again.

`settings/privacy` | `settings/security` | `settings/autofill` | `settings/cookies` | `settings/content` | `settings`
---------|----------|---------|----------|---------|---------
<img width="1405" alt="Screenshot 2022-09-07 at 2 16 04 PM" src="https://user-images.githubusercontent.com/387249/188983406-c42016fa-d05a-47f8-8833-7bc49cbcea4e.png"> | <img width="1300" alt="Screenshot 2022-09-07 at 2 16 45 PM" src="https://user-images.githubusercontent.com/387249/188983414-5a5ec93a-27b3-4428-92c8-004d042e2d89.png"> | <img width="1300" alt="Screenshot 2022-09-07 at 2 17 01 PM" src="https://user-images.githubusercontent.com/387249/188983422-25f1d257-4571-4eb2-b2b6-be9a3714334c.png"> | <img width="1300" alt="Screenshot 2022-09-07 at 2 17 30 PM" src="https://user-images.githubusercontent.com/387249/188983427-5b0d4e47-8bfe-4731-b43b-2c96bc5c4346.png"> | <img width="1300" alt="Screenshot 2022-09-07 at 2 17 58 PM" src="https://user-images.githubusercontent.com/387249/188983433-2fe18768-7708-46b0-b8b8-29bd6e093f7c.png"> | <img width="1300" alt="Screenshot 2022-09-07 at 2 18 36 PM" src="https://user-images.githubusercontent.com/387249/188983440-8233a711-29d6-4a55-9340-f8ee58d2dfcd.png">
