### ISSUE TITLE
Gradient background option for NTP

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#24889]
subtask of #15252. Overall design also can be found there.

Spec:
  * Users can choose a gradient background for NTP
  * This will be applied only to the current local machine.
  * When Users choose another option like `custom background` and `brave background`, the background should be changes to it.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED`
```
Brave | 1.45.80 Chromium: 106.0.5249.65 (Official Build) beta (64-bit)
-- | --
Revision | 3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}
OS | Windows 11 Version 21H2 (Build 22000.978)
```

Case 1: Toggle `ON` `Refresh on every new tab` 
<details>

1. installed `1.45.80`
2. launched Brave
3. opened a new-tab page
4. clicked on `Customize`
5. clicked on `Gradients` card
6. toggle `ON` `Refresh on every new tab`
7. open NTP

####  Confirmed when `Refresh on every new tab` toggle is on, Gradient background is picked on every new tab

step 5-6|step 7
----|----
<img width="454" alt="image" src="https://user-images.githubusercontent.com/98358127/193355626-81b85f03-274b-4fd4-88ae-2ba75eaed190.png">|<img width="453" alt="image" src="https://user-images.githubusercontent.com/98358127/193355597-7cf14419-4fe4-4b08-9c48-845d87775cba.png">

</details>

Case 2: Toggle `OFF` `Refresh on every new tab` 
<details>

1. click customize on the last tab from Case 1
2. click on selected gradients card to return to `Refresh on every new tab`
3. toggle `OFF` `Refresh on every new tab` 
4. open NTP

### Confirmed same Gradient background is picked from the last tab in Case 1 for each new tab

Ex1|Ex2
----|----
|<img width="454" alt="image" src="https://user-images.githubusercontent.com/98358127/193355874-8ff8abd0-7e95-496e-8554-fe8b60f41a81.png">|<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/193355790-ed8b0726-2ddc-4d2e-b59a-8fd53577700f.png">
</details>

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.45.84 Chromium: 106.0.5249.91 (Official Build) beta (x86_64)
-- | --
Revision | fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}
OS | macOS Version 11.7 (Build 20G817)




Case 1: Toggle `ON` `Refresh on every new tab` 
<details>

1. installed `1.45.84`
2. launched Brave
3. opened a new-tab page
4. clicked on `Customize`
5. clicked on `Gradients` card
6. toggle `ON` `Refresh on every new tab`
7. open NTP

####  Confirmed when `Refresh on every new tab` toggle is on, a new Gradient background is picked on each new (non-Sponsored-Image) tab

`step 5-6`|`step 7`, *1* | *2* | *3* | *4*
----|----|----|----|-----
<img width="1312" alt="Screen Shot 2022-10-03 at 6 53 41 PM" src="https://user-images.githubusercontent.com/387249/193700036-66351961-2a10-4620-94b2-c6afecb485d5.png"> | <img width="1312" alt="Screen Shot 2022-10-03 at 6 53 49 PM" src="https://user-images.githubusercontent.com/387249/193700044-b1887678-aec2-4718-a175-13b74961b6a2.png"> | <img width="1312" alt="Screen Shot 2022-10-03 at 6 53 55 PM" src="https://user-images.githubusercontent.com/387249/193700046-fd506d80-a35f-4b74-8184-84686647997e.png"> | <img width="1312" alt="Screen Shot 2022-10-03 at 6 54 09 PM" src="https://user-images.githubusercontent.com/387249/193700053-f94e93dc-a787-41dc-a70a-95dd79c2aba8.png"> | <img width="1312" alt="Screen Shot 2022-10-03 at 6 56 58 PM" src="https://user-images.githubusercontent.com/387249/193700612-6908db13-3311-466b-b164-e799281a7b40.png">



</details>

Case 2: Toggle `OFF` `Refresh on every new tab` 
<details>

1. click customize on the last tab from Case 1
2. click on selected `Gradients` card to return to `Refresh on every new tab`
3. toggle `OFF` `Refresh on every new tab` 
4. open NTP

#### Confirmed same Gradient background is picked from the last tab in Case 1 for each new tab

Ex1|Ex2
----|----

</details>
