### ISSUE TITLE
Click on `All scripts allowed` shield setting, displays blank drop down for few seconds before loading drop down options

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#2488]
## Description 
Click on `All scripts allowed` shield setting, displays blank drop down for few seconds before loading drop down options

## Steps to Reproduce

   1.  Launch brave with clean profile
   2.  Open few sites ( I have opened espn.com, orimi.com, fortune.com, YT.com, twitter.com) 
   3.  Click on shiled setting `All scripts allowed` 
   

## Actual result:
Click on `All scripts allowed` displays blank drop down for few seconds before loading drop down options.
![scripts block-drop down blank issue-0 58 11](https://user-images.githubusercontent.com/38657976/49878627-09caf400-fe4e-11e8-837c-6f1ca8a76f75.gif)

## Expected result:
Should not show blank drop down

## Reproduces how often: 
Always

## Brave version (brave://version info)

Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Windows

### Reproducible on current release: Yes
- Does it reproduce on brave-browser dev/beta builds? Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional Information
@brave/legacy_qa

**Comment by LaurenWags** [comment]
Have not been able to reproduce this on macOS so far

Brave | 0.58.12 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

**Comment by srirambv** [comment]
I was able to reproduce this on beta once. But not on a new profile in beta or on release channel

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.64.60 Chromium: 74.0.3729.91 (Official Build) beta (64-bit)
-- | --
Revision | 03844ed83e02b8add3f4b9cb859a7108d55b2e4d-refs/branch-heads/3729@{#860}
OS | Windows 10 OS Build 17134.523

Still reproducible, logged new issue https://github.com/brave/brave-browser/issues/4213
