### ISSUE TITLE
Add updated logo for Sardine 

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#24899]
## Description 

See https://bravesoftware.slack.com/archives/C03FP409W2X/p1660571165447769 for details

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Fixed by https://github.com/brave/brave-core/pull/14881

**Comment by kjozwiak** [comment]
The above requires `1.44.78` or higher for `1.44.x` verification 👍

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/25029#issuecomment-1247993762
