### ISSUE TITLE
Remove BAT from showing up as default listed token 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#24892]
## Description 

Remove BAT from showing up as default listed token 

## Steps to Reproduce

   1. Create a new wallet
   2. BAT is listed as one of the default token
   
## Actual result:

BAT is listed as one of the default token when wallet is created

## Expected result:
Should only list native tokens as default enabled/listed tokens

## Reproduces how often: 

Easy

## Desktop Brave version:

All

## Android Device details:
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @onyb

**Comment by lukemulks** [comment]
Why are we removing BAT from default listed tokens in browser wallet where BAT is the unit of account for attention? 

This provides awareness for the token and utility. 

I do not see why we would intentionally make people less aware of BAT, than create awareness for BAT where supported.  

There should be more discussion about this before removing imo.
