### ISSUE TITLE
Cannot login to bank site

### ISSUE THREAD

**Issue by groovinfingers** [brave/brave-browser#2489]
## Description 

When I navigate to my bank site, I am able to authenticate.  I am then presented with a page where I need to select which account to view.  When I select an account, I am taken back to the login page.  If I perform the same workflow in Chrome, no problems occur.

## Steps to Reproduce

Block all cookies in Brave in the settings page (i.e. not in the shields balloon).
Create a white-list and add an entry for my bank.
Go to bank site.
Open shields balloon - turn off shields for this site.
Enter creds, hit enter.
I am take to account selection page.
Select account.
I am taken to login page.
Aside: this same workflow works in Chrome.

## Actual result:

I am taken to login page.

## Expected result:
Should be taken to account details page.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Version 0.57.18 Chromium: 71.0.3578.80 (Official Build) (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Installed beta for MacOS.  When I try to launch it, immediate crash occurs.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
No
- Is the issue reproducible on the latest version of Chrome? 
No

### Additional Information

I ran the use case through Chrome and Brave side-to-side with the dev tools open in Network section while recording http log.  Chrome successfully navigates from bank.org to memberidentify.bank.org to my.bank.org.  Brave does: bank.org to memberidentify.bank.org to bank.org.  Cookie entry in white list is: [*.]bank.org which works in Chrome.

**Comment by bsclifton** [comment]
Not enough information here to take action - and no follow ups. Closing as stale
