### ISSUE TITLE
Update Brave Ads brave://rewards Copy

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#24903]
Update Brave Ads brave://rewards Copy:

<img width="487" alt="Screen Shot 2022-08-19 at 16 21 45" src="https://user-images.githubusercontent.com/1188719/186238901-70ce3aa9-b5f1-485a-9a83-f4de977b0aca.png">

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.45.75 Chromium: 106.0.5249.65 (Official Build) beta (64-bit)
-- | --
Revision | 3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}
OS | Ubuntu 18.04 LTS

### English locale

Verified notification ads per hour in `brave://rewards`
![image](https://user-images.githubusercontent.com/34715963/192633460-438391d5-0f04-4c89-8d98-ff571ea71276.png)

Verified ads per hour dropdown
![image](https://user-images.githubusercontent.com/34715963/192633596-572b9786-dfcd-471c-b1dc-f4bf526b2da5.png)

### Polish locale
![image](https://user-images.githubusercontent.com/34715963/192635000-0810c9aa-659f-4256-8793-ee95bda47706.png)

![image](https://user-images.githubusercontent.com/34715963/192634627-a2c46042-2c04-40a2-8061-dcbd3e69f011.png)
