### ISSUE TITLE
Sending Ether on Optimism L2 fails without displaying an error message

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#24909]
## Description 
Sending Ether via Optimism fails to execute a transaction and fails to provide an error message

## Steps to reproduce 

   1. 
![03318cc30813d2d0710f4195dd8eaf6281e56d95_2_225x500](https://user-images.githubusercontent.com/30185185/186283828-1e5ec6b9-5745-4209-876e-51fbaa8f9954.jpeg)

   2. 
![763088d2d7e6cbb2aa574b26f9112bae18346e15_2_225x500](https://user-images.githubusercontent.com/30185185/186283837-e9bac269-1c41-4af6-ab08-1fdd0ec6e5d4.jpeg)

## Actual result 
White screen, then redirect to last opened window

## Expected result
Sending Ether via Optimism should generate & broadcast a transaction

## Issue reproduces how often 
Not yet reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version: Android 11
   
## Brave version
1.42.97

### Additional information

Reported here: https://community.brave.com/t/cant-send-me-eth-outside-of-brave-wallet/426444/3?u=jleonard

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.46.87 x64 Beta build
- Verified test plan from [brave/brave-core#15192](https://github.com/brave/brave-core/pull/15192)
- Verified able to send transaction on Optimism

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<img width=270 src=https://user-images.githubusercontent.com/17010094/199406928-58ab175e-9ec3-4698-8665-3efeed7aefc4.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/199406950-65cc665a-2ae1-4a9a-aa1c-a3fe3ab37d21.png>
