### ISSUE TITLE
[Android] Brave Search Promo - copy / design change

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#24902]
The design team have requested a design / copy change to the omnibar brave search promo banner.

**Figma:** https://www.figma.com/file/8wncTFNBvKN7CS6LTXAMYs?node-id=45:14911#250446537

![Image](https://user-images.githubusercontent.com/28269287/186213452-9266b9cd-f234-4aae-be4e-b8dc3314168c.png)

**Comment by kjozwiak** [comment]
STR/Cases for @brave/qa-team can be found via https://github.com/brave/brave-core/pull/14778#issuecomment-1230750226. Example of the screenshots/design can be found via https://github.com/brave/brave-browser/issues/24902#issue-1348224400.

Quick note that the above can be QA'd/verified alongside https://github.com/brave/brave-browser/issues/23062.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+` running `Android 12` using the following build(s):

```
Brave | 1.43.87 Chromium: 105.0.5195.68 (Official Build) (32-bit)
--- | ---
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | Android 12; Build/SP1A.210812.016
```

**`Example`** | **`Example`**
---------------|-----------------
![Screenshot_20220831-180717_Brave](https://user-images.githubusercontent.com/2602313/187794635-ae9aeba0-8dc2-4e45-b0b1-d62e505b32f1.jpg) | ![Screenshot_20220831-180736_Brave](https://user-images.githubusercontent.com/2602313/187794654-49421775-2ac6-4d77-b08b-8c4b8511e7bc.jpg)
![Screenshot_20220831-180805_Brave](https://user-images.githubusercontent.com/2602313/187794677-5c80e855-2a05-49b4-8e5c-d5eeadd2a527.jpg) | ![Screenshot_20220831-180750_Brave](https://user-images.githubusercontent.com/2602313/187794681-d3530248-1f68-4276-b939-e8932f230b8e.jpg)

----------

Verification **PASSED** on `Samsung S10+` running `Android 12` using the following build(s):

```
Brave | 1.43.87 Chromium: 105.0.5195.68 (Official Build) (32-bit)
--- | ---
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | Android 12; Build/SP2A.220305.013
```

**`Example`** | **`Example`**
---------------|-----------------
![Screenshot_20220831_182248_Brave](https://user-images.githubusercontent.com/2602313/187796256-e7ed8e04-1a03-49d0-ad5d-db72bc208f01.jpg) | ![Screenshot_20220831_182310_Brave](https://user-images.githubusercontent.com/2602313/187796270-f730643a-e8e7-4e4f-8705-3fc821da1800.jpg)
![Screenshot_20220831_182444_Brave](https://user-images.githubusercontent.com/2602313/187796302-ba16ed63-0ac3-4ca0-a9e2-a9fa37c848cb.jpg) | ![Screenshot_20220831_182339_Brave](https://user-images.githubusercontent.com/2602313/187796304-ebd29e01-03e7-447e-8264-d6390352baf6.jpg)
