### ISSUE TITLE
DNS resolver doesn't get reset after enabling, then disabling, DoH for IPNS

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#24900]
## Description 

DNS resolver doesn't get reset after enabling, then disabling, DoH for IPNS

Found while testing https://github.com/brave/brave-browser/issues/24678.

## Steps to Reproduce

1. install `1.44.62`
2. launch Brave
3. load `brave://ipfs-internals/`
4. click on `Install and start`
5. chose `NextDNS` as a DoH provider in `brave://settings/security`
6. shut down Brave
7. opened `{profile_folder}/brave_ipfs/config` in a text editor
8. confirmed there's a `DNS` entry with `Resolvers:` and `NextDNS` is listed
9. relaunch Brave
10. set DNS back to `With your current service provider`
11. shut down Brave
12. opened `{profile_folder}/brave_ipfs/config` in a text editor
13. searched for `DNS` / `Resolver`

## Actual result:

<img width="1418" alt="Screen Shot 2022-08-23 at 9 24 14 AM" src="https://user-images.githubusercontent.com/387249/186211099-169ed485-c752-41cb-a400-3ceadcdfd9ad.png">

## Expected result:

No `DNS` / `Resolvers` entry

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.44.62 Chromium: 104.0.5112.102 (Official Build) nightly (x86_64)
-- | --
Revision | 8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}
OS | macOS Version 11.6.8 (Build 20G730)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @cypt4

**Comment by cypt4** [comment]
@stephendonner , I think config will be updated after local node relaunch. Could you recheck the testcase but after 10 open some ipfs:// or ipns:// site?

**Comment by stephendonner** [comment]
> @stephendonner , I think config will be updated after local node relaunch. Could you recheck the testcase but after 10 open some ipfs:// or ipns:// site?

Confirmed working; if I add the step of loading `ipns://ipfs.io` after changing back to regular DNS from DoH, the `NextDNS` entry is removed 👍 

11. load ipns://ipfs.io
12. click on Brave local IPNS node  13. let it load
14. shut down Brave
15. open {profile_dir}/ipfs_folder/config, I no longer see the DNS/ NextDNS  entry

**Comment by stephendonner** [comment]
With the above added step, this fix works for me, so closing this issue off as WORKSFORME.  Will verify over in https://github.com/brave/brave-browser/issues/24678 👍
