### ISSUE TITLE
Solana: Show multi-chain pending requests of selected networks via wallet icon

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#24928]
## Description 
Solana: Show multi-chain pending requests of selected default networks per coin when wallet icon is clicked

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.45.95 x64 build
- Verified steps from [brave/brave-core#14795](https://github.com/brave/brave-core/pull/14795)
- Verified multiple transactions from different network is stacked 
- Encountered
  - https://github.com/brave/brave-browser/issues/25962
  - https://github.com/brave/brave-browser/issues/25963

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/195591235-9c330d25-2721-485d-9732-11248791fbae.mp4> | <video src=https://user-images.githubusercontent.com/17010094/195592701-4c37123d-180a-4bc3-86dd-6a8774e9d1f1.mp4>
