### ISSUE TITLE
Reading list graphics is inherited from chrome

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#24927]
## Description 

Reading list graphics is inherited from chrome 

## Actual result:

![image](https://user-images.githubusercontent.com/38657976/186400869-7ff04077-68ee-487d-aecf-726a4be727eb.png)

## Expected result:
See: https://github.com/brave/brave-browser/issues/24927#issuecomment-1225944491

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.44.64 Chromium: 105.0.5195.37 (Official Build) nightly (64-bit)
-- | --
Revision | 5f67e9f258cc28ab970e57572290edf1863ee3c5-refs/branch-heads/5195@{#621}
OS | Windows 10 Version 21H2 (Build 19044.1889)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @rebron @bradleyrichter

**Comment by aguscruiz** [comment]
Already have a design for this, link here: https://www.figma.com/file/xOdKFSr3P5AXSAbP2r8ung/Sidebar-Desktop?node-id=3862%3A70675

![image](https://user-images.githubusercontent.com/15734630/186470077-4e6f6a1b-31fc-4d9d-a420-7a32b7ed6387.png)

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.51.76 Chromium: 112.0.5615.49 (Official Build) beta (x86_64)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | macOS Version 13.4 (Build 22F5027f)

### Post-fix

`Figma spec` | `Light` | `Dark`
--------------|---------|-------
<img width="1496" alt="Screenshot 2023-04-03 at 2 10 20 PM" src="https://user-images.githubusercontent.com/387249/229629302-9169ab74-301b-4003-9d41-5db12d99c8c8.png"> | <img width="1496" alt="Screenshot 2023-04-03 at 2 02 36 PM" src="https://user-images.githubusercontent.com/387249/229629090-1971a657-cba3-4bbc-93ee-24d62b275900.png"> | <img width="1496" alt="Screenshot 2023-04-03 at 2 04 33 PM" src="https://user-images.githubusercontent.com/387249/229629107-74d30831-1acb-43bb-8027-d21e84f2bb33.png">


### Previous

`Light` | `Dark`
--------|------
<img width="1389" alt="Screenshot 2023-04-03 at 2 12 14 PM" src="https://user-images.githubusercontent.com/387249/229628820-f5ec809b-5a7e-4703-b0a7-8b3725ab6870.png"> | <img width="1389" alt="Screenshot 2023-04-03 at 2 11 39 PM" src="https://user-images.githubusercontent.com/387249/229628862-1901c398-8c55-4dec-bf45-23730d39da26.png">

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.51.87 Chromium: 112.0.5615.49 (Official Build) beta (64-bit)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Windows 10 Version 22H2 (Build 19045.2846)


`Dark` | `Light`
-------|---------
![image](https://user-images.githubusercontent.com/387249/231722453-299e63c3-26fc-4979-8ce3-9770c128841d.png) | ![image](https://user-images.githubusercontent.com/387249/231722635-50d3fe74-34e0-4f95-9e8e-33f03b09ab6b.png)
