### ISSUE TITLE
Search option provided within brave://settings/cookies doesn't function

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#24924]
## Description 

Search option provided within brave://settings/cookies doesn't function

## Steps to Reproduce

   1. Clean profile 1.42.x or 1.44.x
   2. Open brave://settings/cookies
   3. Enter a string in search bar under brave://settings/cookies
   4. Search doesn't work

## Actual result:

![image](https://user-images.githubusercontent.com/38657976/186370737-ef0cdc90-dcc0-4977-8ec1-aa5909af8842.png)

## Expected result:
It's behaving same in Chrome as well, either we can make it work or remove it from brave

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.44.64 Chromium: 105.0.5195.37 (Official Build) nightly (64-bit)
-- | --
Revision | 5f67e9f258cc28ab970e57572290edf1863ee3c5-refs/branch-heads/5195@{#621}
OS | Windows 10 Version 21H2 (Build 19044.1889)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? Yes

## Miscellaneous Information:

The issue exists in chrome as well, I will defer to @rebron on this

cc: @brave/qa-team @mkarolin @rebron

**Comment by LaurenWags** [comment]
@GeetaSarvadnya I couldn't reproduce using 

```
Brave | 1.43.84 Chromium: 105.0.5195.68 (Official Build) (x86_64)
-- | --
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | macOS Version 12.5.1 (Build 21G83)
```

Just to be sure, you're attempting to search your cookies, correct? This search box won't highlight the word "site" on the page. We can look at this one together to be sure 👍🏻

**Comment by GeetaSarvadnya** [comment]
@LaurenWags Thanks for checking. There was some misunderstanding in seach settings, it works as expected hence closing the issue.
