### ISSUE TITLE
Rename NTPCustomBackgroundImageService => BraveNTPCustomBackgroundService

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#24926]
It's dealing with not only images but also colors.

**Comment by akshat-rawat** [comment]
Hey, can I work on this one? I got everything setup just have a couple of questions before starting.

**Comment by sangwoo108** [comment]
Hi @akshat-rawat ! I really appreciate your interest. It's still valid but unfortunately, there's already a class named `NTPCustomBackgroundService` from upstream. So we need to come up with a better name. 

cc. @simonhong

**Comment by debanjana-a11y** [comment]
> It's still valid but unfortunately, there's already a class named NTPCustomBackgroundService from upstream. So we need to come up with a better name.

has the new name been finalized ?

**Comment by sangwoo108** [comment]
Not yet, but I think `BraveNTPCustomBackgroundService` might be good. @simonhong What do you think about this?

**Comment by simonhong** [comment]
`BraveNTPCustomBackgroundService` looks good 👍🏼

**Comment by debanjana-a11y** [comment]
I was trying to build brave following the guideline mentioned [here](https://github.com/brave/brave-browser/blob/master/CONTRIBUTING.md), this is what I am facing right now. Any idea what wrong I am doing ?
![image](https://user-images.githubusercontent.com/89571066/189537129-6f1a217f-a435-4935-ab33-703fbf2660d6.png)

**Comment by sangwoo108** [comment]
Hi, @debanjana-a11y . Could you confirm that you ran `npm install` and `npm init` before running `npm run build`? Also, on Linux there are more prerequisites. https://github.com/brave/brave-browser/wiki/Linux-Development-Environment

**Comment by debanjana-a11y** [comment]
> Hi, @debanjana-a11y . Could you confirm that you ran npm install and npm run init before running npm run build? Also, on Linux there are more prerequisites. https://github.com/brave/brave-browser/wiki/Linux-Development-Environment

Thanks @sangwoo108 for pointing out. Turned out that I did not properly follow the prerequisites. Now I'm able to build but it is taking too much time. Is it normal ? I also tried running ` npm run test -- brave_browser_tests` this also looks very slow in compiling stuffs.
Did I miss something which makes them faster ?

**Comment by XZ6H** [comment]
What all should be renamed - class, filename, preprocessor directives and delegates? or just the class?

**Comment by sangwoo108** [comment]
> I would like to give this a shot. What all should be renamed - class, filename, preprocessor directives and delegates? or just the class?

Hi @XZ6H ! All of them should be changed

**Comment by SIDDHANT80NY** [comment]
Hi can I work on this ?

**Comment by XavierJDN** [comment]
Hey, Can I have more details where the service is?

**Comment by XavierJDN** [comment]
Hi, I think I resolved the issue.
Can someone assign to me the issue?
I also release that a factory and delegate service is connected to NTPCustomBackgroundImageService, so I also rename the factory and delegate service.

**Comment by bsclifton** [comment]
@XavierJDN sure - please submit your PR when ready and let us know 😄

**Comment by XavierJDN** [comment]
> @XavierJDN I'm really sorry that I missed this. I cherry-picked your commits and created an PR so that our CI bots can go through tests. [brave/brave-core#17908](https://github.com/brave/brave-core/pull/17908)
> 
> And I can't thank you enough for your time and effort for this pray

You're welcome. That was a pleasure.
