### ISSUE TITLE
`Block all cookies` global shield settings isn't functioning in Guest window

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#24921]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/23800#issue-1290451177

`Bock all cookies` global shield settings isn't functioning in Guest window
## Steps to Reproduce

Case 1
   1. Clean profile 1.42.x or 1.44.x
   2. Open a guest window
   3. Navigate to brave://settings/shields
   4. Change the global shield settings for cookies to "All"
   5. Reload the brave://settings/shields page
   6. Cookies shield settings reset back to default "Only cross sites"

Case 2:

   1. Clean profile 1.42.x or 1.44.x
   2. Open a guest window
   3. Navigate to brave://settings/shields
   4. Change the global cookies shield settings to "Disable"
   5. Open a site A and verify that the global shield settings are applied 
   6. Change the global shield cookies settings to "All"
   7. Reload the site A and observe changed cookies settings are NOT applied
   

## Actual result:

`Bock all cookies` global shield settings isn't functioning in Guest window

## Expected result:
`Bock all cookies` global shield settings should function in Guest window

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.44.64 Chromium: 105.0.5195.37 (Official Build) nightly (64-bit)
-- | --
Revision | 5f67e9f258cc28ab970e57572290edf1863ee3c5-refs/branch-heads/5195@{#621}
OS | Windows 10 Version 21H2 (Build 19044.1889)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @rebron @mkarolin @brave/qa-team

**Comment by kjozwiak** [comment]
Closing the above as it's labelled as `closed/wontfix` so there's no need for the above to stay opened.
