### ISSUE TITLE
Update Aurora modal text

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#24923]
Update Aurora Modal tex as outlined in this [comment](https://github.com/brave/security/issues/974#issuecomment-1222794584).

**Comment by kjozwiak** [comment]
The above requires `1.44.78` or higher for `1.44.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.44.86 Chromium: 105.0.5195.127 (Official Build) beta (64-bit) 
-- | --
Revision | `912488396852bf658ab32465980c0b93a3c27a83-refs/branch-heads/5195@{#1109}`
OS | Linux

- Verified steps from PR
- Verified `Bridge to Aurora` modal is shown every time user clicks on it
- Verified `Learn more about using Rainbow Bridge` opens `https://doc.aurora.dev/bridge/bridge-overview/` 
- Verified `Learn more about mitigating risk on Rainbow Bridge` opens `https://rainbowbridge.app/approvals`
- Verified when user checks `Do not show this again` it doesn't show the prompt after that

https://user-images.githubusercontent.com/17010094/190390206-d2904995-8f24-4cdf-be0a-c81664c97ced.mp4


------------------------
Verification passed on

Brave | 1.44.86 Chromium: 105.0.5195.127 (Official Build) beta (64-bit) 
-- | --
Revision | `912488396852bf658ab32465980c0b93a3c27a83-refs/branch-heads/5195@{#1109}`
OS | Windows 11 Version 21H2 (Build 22000.795)

- Verified steps from PR
- Verified `Bridge to Aurora` modal is shown every time user clicks on it
- Verified `Learn more about using Rainbow Bridge` opens `https://doc.aurora.dev/bridge/bridge-overview/` 
- Verified `Learn more about mitigating risk on Rainbow Bridge` opens `https://rainbowbridge.app/approvals`
- Verified when user checks `Do not show this again` it doesn't show the prompt after that

https://user-images.githubusercontent.com/17010094/190387120-e85dc180-716e-4ab9-86cc-c89df9782bf9.mp4


------------------------
Verification passed on

Brave | 1.44.86 Chromium: 105.0.5195.127 (Official Build) beta (arm64)
-- | --
Revision | `912488396852bf658ab32465980c0b93a3c27a83-refs/branch-heads/5195@{#1109}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from PR
- Verified `Bridge to Aurora` modal is shown every time user clicks on it
- Verified `Learn more about using Rainbow Bridge` opens `https://doc.aurora.dev/bridge/bridge-overview/` 
- Verified `Learn more about mitigating risk on Rainbow Bridge` opens `https://rainbowbridge.app/approvals`
- Verified when user checks `Do not show this again` it doesn't show the prompt after that

https://user-images.githubusercontent.com/17010094/190386671-7f984f3e-7093-4b29-bdba-6c477cdfff3c.mov
