### ISSUE TITLE
Captcha on Signal website working incorrectly

### ISSUE THREAD

**Issue by groovinfingers** [brave/brave-browser#2493]
## Description 

When attempting to enter new ticket at Signal website using Brave, captcha error occurs.

## Steps to Reproduce

1. Go here: https://support.signal.org/hc/en-us/requests/new
2. Disable shields for site
3. Attempt to fill out a ticket.  
4. Hit submit
5. At bottom of page, validation related to captcha fails.

## Actual result:

At bottom of page, validation related to captcha fails.

## Expected result:
Form should be allowed to be submitted.

## Reproduces how often: 

Easily reproduced.

## Brave version (brave://version info)

Version 0.57.18 Chromium: 71.0.3578.80 (Official Build) (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Beta build won't run on my Mac.  When I launch it, immediately blows up.  Crash report was sent to Apple.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
No.

- Is the issue reproducible on the latest version of Chrome? 
No.

**Comment by GeetaSarvadnya** [comment]
1+ https://community.brave.com/t/incorrect-captcha-code/63014

**Comment by ryanbr** [comment]
Just submitted 2 ticket's (with shields enabled and disabled) can you confirm everything is working @groovinfingers  ?

**Comment by groovinfingers** [comment]
I don't use Brave anymore.  Nonetheless, thanks for addressing @ryanbr

**Comment by ryanbr** [comment]
Closing, thanks for the report and responding. Issue seems to be resolved :)
