### ISSUE TITLE
Brave crashes upon clicking on `Exit private window with Tor` when reading list is enabled in PT, TOR and Normal window

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#24931]
## Description 

Brave crashes upon clicking on `Exit private window with Tor` when reading list is enabled in PT, TOR and Normal window

## Steps to Reproduce

   1. Clean profile 1.44.x
   2. Open a Tor private window
   3. Click on side panel and ensure reading list sidebar menu opens up
   4. Wait until tor network connects to 100%
   5. Open a couple of sites and add to the reading list
   6. Open a Private window and enable reading list by clicking on the side panel 
   7. Navigate to normal window and enable reading list by clicking on the side panel 
   8. Navigate to `Tor` window and click on `Exit private window with Tor` 
   9. Brave crashes

## Actual result:

Brave crashes
## Expected result:
Should not be any crash

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.44.64 Chromium: 105.0.5195.37 (Official Build) nightly (64-bit)
-- | --
Revision | 5f67e9f258cc28ab970e57572290edf1863ee3c5-refs/branch-heads/5195@{#621}
OS | Windows 10 Version 21H2 (Build 19044.1889)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @rebron @pes10k @simonhong @mkarolin @brave/qa-team

**Comment by mkarolin** [comment]
I believe it's the same as https://github.com/brave/brave-browser/issues/24953

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
Brave | 1.43.82 Chromium: 105.0.5195.58 (Official Build) (64-bit)
-- | --
Revision | 1907e1693887af4463221a10247360b7a056db49-refs/branch-heads/5195_47@{#3}
OS | Windows 10 Version 21H2 (Build 19044.1889)

```
Ensured that there is no crash when the TOR window is closed via `Exit private window with Tor`
