### ISSUE TITLE
Filecoin balance is not shown on account details view or in widget

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#24946]
## Description 

Filecoin balance is not shown on account details view or in widget

## Steps to Reproduce

   1. Create Wallet
   2. Enable Testnet to show up 
   3. Create mainnet account and testnet accounts for Filecoin
   4. Balance isn't shown for both networks
   5. Refresh portfolio starts showing balance

## Actual result:

https://user-images.githubusercontent.com/17010094/186470525-5c0830e4-404d-4419-b27d-73fde44b93be.mp4

## Expected result:
Should show the balance without needing to reload the page 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.43.81 Chromium: 104.0.5112.102 (Official Build) (64-bit) 
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | Windows 11 Version 21H2 (Build 22000.856)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @cypt4 @yrliou

**Comment by yrliou** [comment]
@srirambv is this still reproducible?

**Comment by josheleonard** [comment]
Closing - FIL balances are now shown after import without refreshing
