### ISSUE TITLE
Blue check mark icon is missing in Import bookmarks and settings page

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#24944]
## Description 

Blue check mark icon is missing in Import bookmarks and settings page

## Steps to Reproduce

   1. Clean profile 1.44.x
   2. Open brave://settings/importData
   3. Import bookmarks
   4. After bookmarks import, Green check mark icon is not shown

## Actual result:

![image](https://user-images.githubusercontent.com/38657976/186460697-86afdc09-1c3b-4379-9bd5-00239766f4a1.png)

## Expected result:

![image](https://user-images.githubusercontent.com/38657976/186460786-767a8658-e2b9-4ac4-a268-10e55741353c.png)

## Reproduces how often: 

100%
## Brave version (brave://version info)

Brave | 1.44.64 Chromium: 105.0.5195.37 (Official Build) nightly (64-bit)
-- | --
Revision | 5f67e9f258cc28ab970e57572290edf1863ee3c5-refs/branch-heads/5195@{#621}
OS | Windows 10 Version 21H2 (Build 19044.1889)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @rebron @mkarolin

**Comment by rebron** [comment]
cc: @fallaciousreasoning

**Comment by stephendonner** [comment]
s/green/blue?

**Comment by kjozwiak** [comment]
The above requires `1.44.78` or higher for `1.44.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.44.78 Chromium: 105.0.5195.102 (Official Build) beta (x86_64)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | macOS Version 13.0 (Build 22A5331f)

#### Followed Geeta's steps and confirmed the blue checkmark icon is back

<img width="1312" alt="Screenshot 2022-09-07 at 2 48 15 PM" src="https://user-images.githubusercontent.com/387249/188992788-2452b23b-787f-4bb4-8c99-0b91f8d3e2d0.png">
