### ISSUE TITLE
update wording on bookmark manager and favicon to remove reference to star icon

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#2494]
## Description 
When you navigate to the bookmarks manager and you don't have any bookmarks yet (or you navigate to a folder within bookmark manager that does not have any bookmarks) you're shown instructional text that says 'To bookmark pages, click the star in the address bar' - however, there's no star for you to click as we changed icons. This wording should be updated to reflect changed icon.

## Steps to Reproduce

   1. Navigate to bookmarks manager.
   2. If you don't have any bookmarks, you'll see the text in the image below.
   3. If you have bookmarks, create a new folder and open it in the bookmark manager.

## Actual result:
![screen shot 2018-12-12 at 12 48 53 pm](https://user-images.githubusercontent.com/28145373/49888553-4c201100-fe0d-11e8-8db4-3e04b075e910.png)

## Expected result:
Text should be updated to reflect changed icon.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta(64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by rebron** [comment]
Text should be: 

To bookmark pages, click the bookmarks button next to the address bar.

**Comment by rebron** [comment]
cc: @petemill can you take at look if you're in brave://bookmarks already.

**Comment by eltonbaroncello** [comment]
@LaurenWags this bookmark button on the left side of the location bar, it's turning the transition experience a bit annoying. There's any chance to change it. 😒

**Comment by LaurenWags** [comment]
@eltonbaroncello I'm not aware of any plans to move the location of the bookmark button.

**Comment by rebron** [comment]
Let's also address the favicon in the Bookmarks tab at the top by using our bookmarks icon.

**Comment by rossmoody** [comment]
DM'd Raf: copy finalized to : `To add a bookmark, click the bookmark button next to the address bar`

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.5.102 Chromium: 80.0.3987.122 (Official Build) beta (64-bit)
-- | --
Revision | cf72c4c4f7db75bc3da689cd76513962d31c7b52-refs/branch-heads/3987@{#943}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the STR from the description
![image](https://user-images.githubusercontent.com/38657976/75689579-6f133b00-5cc7-11ea-9f0d-2d740ae568cb.png)
