### ISSUE TITLE
Unable to perform Filecoin Testnet transactions

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#24949]
## Description 

Unable to perform Filecoin Testnet transactions

## Steps to Reproduce

   1. Create Wallet and enable testnets
   2. Create Filecoin testenet account
   3. Can't create a Filecoin testnet transaction as there balance doesn't show up 

## Actual result:

Unable to perform Filecoin Testnet transactions

## Expected result:
Able to submit Filecoin transactions on testnet

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.43.81 Chromium: 104.0.5112.102 (Official Build) (64-bit) 
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | Windows 11 Version 21H2 (Build 22000.856)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @cypt4 @yrliou

**Comment by yrliou** [comment]
@srirambv is this issue still reproducible?

**Comment by josheleonard** [comment]
I was able to send testnet transactions yesterday. Although sometimes the TX would end up in the state of "Approved" without confirmation

**Comment by josheleonard** [comment]
Currently not able to confirm testnet filecoin transactions on a Ledger (The panel closes after the approve via connect hardware screen appears)

**Comment by josheleonard** [comment]
Seeing pending txs getting refetched once "confirm" is pressed when sending testnet FIL from a Ledger. The list is empty after this refresh, causing the connect-hardware UI to close (ledger device still shows confirm/reject options)

**Comment by josheleonard** [comment]
Seeing the `onTransactionStatusChanged` called after pressing "confirm" on a pending FIL testnet hardware transaction with a status of "Error". This triggers a refresh of the pending txs list in where the newly "errored" transaction is not present

**Comment by josheleonard** [comment]
Once "confirm" is pressed when sending testnet FIL from a Ledger, seeing the `onTransactionStatusChanged` getting called (the tx now has a status of "Approved", which is incorrect since it is still pending approval/rejection via the Ledger)

**Comment by josheleonard** [comment]
cc: @vadimstruts

**Comment by srirambv** [comment]
This is not an issue anymore. Able to send FIL transactions on Testnet. Closing as stale
![image](https://github.com/brave/brave-browser/assets/17010094/ada2f008-1a3f-4aaa-a7ce-0dada01c8dee)
