### ISSUE TITLE
Virtualize Tokens List

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#24959]
## Description 

The current Tokens list  implementation renders the entire list, even if the majority of the list is not visible within the viewport

## Steps to Reproduce

   Scenario 1
   1. Visit brave://wallet/crypto/deposit-funds
   2. Scroll down the list of assets

   Scenario 2
   1. Add many assets to the visible tokens list (including multiple NFTs)
   2. Scroll down the list of assets on the portfolio page
   3. Sort, search and filter the list

## Actual result:

List takes a long time to render 

## Expected result:
List renders/scrolls smoothly

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (64-bit)
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | Linux

- Verified steps from issue description and [brave/brave-core#14817](https://github.com/brave/brave-core/pull/14817)
- Verified there is smooth scroll on deposit screen
- Verified smooth scroll on portfolio with tokens and NFT's

----------------
Verification passed on 

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (64-bit)
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | Windows 11 Version 21H2 (Build 22000.978)

- Verified steps from issue description and [brave/brave-core#14817](https://github.com/brave/brave-core/pull/14817)
- Verified there is smooth scroll on deposit screen
- Verified smooth scroll on portfolio with tokens and NFT's

----------------
Verification passed on 

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (arm64)
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | macOS Version 12.6 (Build 21G115)

- Verified steps from issue description and [brave/brave-core#14817](https://github.com/brave/brave-core/pull/14817)
- Verified there is smooth scroll on deposit screen
- Verified smooth scroll on portfolio with tokens and NFT's
