### ISSUE TITLE
`Save all files` button should be disabled until `Start`

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#24958]
## Description 

`Save all files` button should be disabled until `Start`

## Steps to Reproduce

   1.  install `1.44.60`
   2. launch Brave
   3. load `https://webtorrent.io/free-torrents`
   4. click on the `magnet link` for any of the files
   5. in the resulting WebTorrent view, look at the `Save all files` button

## Actual result:

`Save all files` button is enabled, but doesn't do anything (until after you start the torrent)

<img width="990" alt="Screenshot 2022-08-24 at 3 02 08 PM" src="https://user-images.githubusercontent.com/387249/186531637-f0cffe9a-a9e0-4ab2-819e-a11d1b53d87f.png">

## Expected result:

`Save all files` button should be disabled until after you've started the torrent

## Brave version (brave://version info)

Brave | 1.44.60 Chromium: 105.0.5195.37 (Official Build) nightly (x86_64)
-- | --
Revision | 5f67e9f258cc28ab970e57572290edf1863ee3c5-refs/branch-heads/5195@{#621}
OS | macOS Version 13.0 (Build 22A5321d)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @fallaciousreasoning

**Comment by fallaciousreasoning** [comment]
I think it should actually be disabled until the torrent has finished downloading - it zips the files up and does nothing until then anyway.

**Comment by ben-marrett** [comment]
I'm keen to work on this issue.

**Comment by fallaciousreasoning** [comment]
Awesome, go for it! A good starting place is probably in `brave/components/brave_webtorrent/extension/components/torrentFileList.tsx`. When you have something, add me as a reviewer on the PR!

**Comment by panoplied** [comment]
@fallaciousreasoning unable to add you as a reviewer, but check the PR #https://github.com/brave/brave-core/pull/14977

**Comment by fallaciousreasoning** [comment]
Wohoo! Thanks for the contribution @panoplied. I'm just kicking off CI, when it finishes we should be good to merge

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using 

Brave | 1.47.110 Chromium: 108.0.5359.71 (Official Build) beta (x86_64)
-- | --
Revision | 1e0e3868ee06e91ad636a874420e3ca3ae3756ac-refs/branch-heads/5359@{#1016}
OS | macOS Version 13.1 (Build 22C5059b)

`Torrent file`:

`default` | `in-progress` | `complete`
----------|---------------|-----------


`Magnet link`:

`default` | `in-progress` | `complete`
----------|---------------|-----------
