### ISSUE TITLE
Enable translate in Nightly using Griffin

### ISSUE THREAD

**Issue by atuchin-m** [brave/brave-browser#24957]
Desktop issue: https://github.com/brave/brave-variations/issues/308
Slack thread: https://bravesoftware.slack.com/archives/C01LKMP6X36/p1661365425546619

**Comment by kjozwiak** [comment]
Closing as https://github.com/brave/brave-variations/pull/337 was merged into `production`. Labelled as `QA/No` and `release-notes/exclude` as this will also be checked on `BETA` and then `RELEASE` as per the discussion via https://bravesoftware.slack.com/archives/C01LKMP6X36/p1661365425546619.
