### ISSUE TITLE
Correct site favicons are not displayed in the Shields panel

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#24954]
## Steps to Reproduce

   1. Install `1.45.1`
   2. Launch Brave
   3. visit https://cnn.com
   4. click `Shields` icon
   5. click `learn more` link in the Shields panel

## Actual result:

Incorrect icons rendered 

Ex1|Ex2
----|---
<image width="950" alt="cnnsite" src="https://user-images.githubusercontent.com/98358127/186494571-070513b2-c7ad-424f-9dfa-e644b1d06588.png">|<image width="950" alt="privacy" src="https://user-images.githubusercontent.com/98358127/186496068-63d9d1a3-433d-4bf2-959b-4359d26b66f3.png">

## Expected result:
`CNN` favicon should render for `CNN.com`
When clicked on `Learn more` link `Brave` favicon should render in the Shields panel for https://brave.com/privacy-features/ page

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Brave | 1.45.1 Chromium: 105.0.5195.37 (Official Build) nightly (64-bit)
-- | --
Revision | 5f67e9f258cc28ab970e57572290edf1863ee3c5-refs/branch-heads/5195@{#621}
OS | Windows 11 Version 21H2 (Build 22000.856)

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
Issue is NOT reproducible in RC - 1.42.x hence adding the regression label

**Comment by GeetaSarvadnya** [comment]
Verification PASSE on

```
Brave | 1.43.82 Chromium: 105.0.5195.58 (Official Build) (64-bit)
-- | --
Revision | 1907e1693887af4463221a10247360b7a056db49-refs/branch-heads/5195_47@{#3}
OS | Windows 10 Version 21H2 (Build 19044.1889)

```

Ensured that correct site favicon is shown in the shield panel
**_Staging:_**

Example | Example | Example | Example | Example | Example
-- | -- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/38657976/186896377-152137d2-84d1-4405-b669-6d010b62a4d0.png) | ![image](https://user-images.githubusercontent.com/38657976/186896412-c307fca1-09c0-4dde-a9d9-8b568ee507dc.png) | ![image](https://user-images.githubusercontent.com/38657976/186896451-6e97b280-0f21-4e0e-b74b-776f4065ad76.png) | ![image](https://user-images.githubusercontent.com/38657976/186896492-5e1db6fd-dfd2-4d29-a1dd-055815bd03b0.png) | ![image](https://user-images.githubusercontent.com/38657976/186896529-b1c7fc16-c9fe-4370-bd26-9a09fb3b35d7.png) | ![image](https://user-images.githubusercontent.com/38657976/186896572-950f990a-8b5c-4356-a232-f5a0a91e18d2.png)

**_Production_**

Example | Example | Example | Example | Example | Example
-- | -- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/38657976/186896879-97be1904-841e-4b10-87bf-f8db724e9984.png) | ![image](https://user-images.githubusercontent.com/38657976/186896924-ae8bb0b2-9f42-4a1e-a77e-b5ec8c8f1e2e.png) | ![image](https://user-images.githubusercontent.com/38657976/186896989-38edb660-fd72-415e-943d-043a140f51aa.png) | ![image](https://user-images.githubusercontent.com/38657976/186897047-3c5de6ab-b201-4710-9b84-09b4660f1b3e.png) | ![image](https://user-images.githubusercontent.com/38657976/186897099-ffd0d6d5-e7bd-4513-b41b-463b0dbac81b.png) | ![image](https://user-images.githubusercontent.com/38657976/186897163-a15c9dba-9807-4f74-b656-30420a2b371a.png)
