### ISSUE TITLE
NTP dashboard crashes Nightly Linux

### ISSUE THREAD

**Issue by intrnl** [brave/brave-browser#24963]
## Description 

with Brave Nightly on Linux, opening NTP dashboard crashes the entire browser.

## Steps to Reproduce

   1. Open the browser
   2. Make sure that the new tab page is set to open the dashboard
   3. Open a new tab

## Actual result:

The browser crashes

## Expected result:
It shouldn't crash

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

1.45.2 Chromium: 105.0.5195.37 (Official Build) nightly (64-bit) 

Started crashing since 1.44.64, that's when the first Cr105 builds arrived.

## Version/Channel Information:

- Can you reproduce this issue with the current release? Not tested.
- Can you reproduce this issue with the beta channel? Not tested.
- Can you reproduce this issue with the nightly channel? Yes.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No.
- Does the issue resolve itself when disabling Brave Rewards? No.
- Is the issue reproducible on the latest version of Chrome? No.

## Miscellaneous Information:

Setting new tab to open a blank page or another page instead of the dashboard fixes the crashing.

Running Arch Linux with Liquorix Kernel 5.19.3-lqx1-1-lqx

**Comment by intrnl** [comment]
This does not seem to affect new installs, I'm baffled as to what's going on.

**Comment by intrnl** [comment]
```
$ brave-nightly 
[5291:5291:0825/194657.911339:ERROR:json_rpc_service.cc(120)] Could not set network from JsonRpcService() for FIL
[5291:5291:0825/194657.970914:ERROR:profile_attributes_storage.cc(849)] Failed to PNG encode the image.
[5291:5291:0825/194657.971078:ERROR:profile_attributes_storage.cc(849)] Failed to PNG encode the image.
[0825/194659.323789:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0825/194659.323886:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0825/194659.323916:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0825/194659.324022:ERROR:elf_dynamic_array_reader.h(64)] tag not found
/opt/brave.com/brave-nightly/brave-browser: line 48:  5291 Segmentation fault      (core dumped) "$HERE/brave" "$@"
```

**Comment by rebron** [comment]
@intrnl can you send the crash report from brave://crashes/ and post the crash id in this issue.

**Comment by intrnl** [comment]
```
c77c0200-e66e-bc08-0000-000000000000
277d0200-e66e-bc08-0000-000000000000
```

**Comment by intrnl** [comment]
It's been a while, I've made new profiles and deleted my old ones, so I'm not sure if there's anything that can be done here and I don't think I see anyone else reporting on it.

Closing for now.
