### ISSUE TITLE
Make sidebar item editable

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#24964]
For now, user can't touch each item's properties such as title or url.
User may want to edit them after adding.

For example, we can launch item edit dialog via context menu like topsite tile's one
<img width="338" alt="Screen Shot 2022-08-25 at 9 18 40 AM" src="https://user-images.githubusercontent.com/6786187/186565960-6a6d0d11-536b-4f12-9838-e2e10419ddb7.png">
<img width="522" alt="Screen Shot 2022-08-25 at 9 18 50 AM" src="https://user-images.githubusercontent.com/6786187/186565971-ff255993-bad9-42ff-ad5c-d02f137e2b66.png">

**Comment by simonhong** [comment]
@aguscruiz I think edit dialog also needs visual feedback when user tries to enter invalid url or alread used url from another sidebar items. Sidebar can't have two different items that uses same url.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.45.87 Chromium: 106.0.5249.91 (Official Build) beta (x86_64)
-- | --
Revision | fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}
OS | macOS Version 11.7 (Build 20G817)

### Steps:
1. installed `1.45.87`
2. launched Brave
3. loaded `bravest.com`
4. loaded `brave.com`
5. added both of the above sites to the Sidebar via the `+` `(Add to Sidebar)` button
6. context-clicked on the `bravest.com` icon and chose `Edit`
7. changed the URL to `brave.com` from `bravest.com`
8. clicked on `OK`
9. context-clicked on the `bravest.com` icon again and chose `Edit`
10. confirmed the URL remains the original `bravest.com`

step 5 | step 6 | step 7a | step 7b | step 9 | step 10
---------|-------|--------|-------|--------|-----------
<img width="1312" alt="Screen Shot 2022-10-05 at 8 11 49 PM" src="https://user-images.githubusercontent.com/387249/194186194-95a6fc1e-a294-4894-862e-63c870336975.png"> | <img width="1201" alt="Screen Shot 2022-10-05 at 8 19 10 PM" src="https://user-images.githubusercontent.com/387249/194186656-b1ee3fd9-8f3e-4b1f-b4e9-e3e5a29101e3.png"> | <img width="1312" alt="Screen Shot 2022-10-05 at 8 14 45 PM" src="https://user-images.githubusercontent.com/387249/194186203-0494d3f4-d127-45fa-baa1-5f8fb93e49bf.png"> | <img width="1312" alt="Screen Shot 2022-10-05 at 8 14 34 PM" src="https://user-images.githubusercontent.com/387249/194186200-826db2bb-ce5f-46ee-8840-04400bb630ca.png"> | <img width="1196" alt="Screen Shot 2022-10-05 at 8 24 06 PM" src="https://user-images.githubusercontent.com/387249/194187035-9fac11e1-9558-4556-bcd4-98b4523ef777.png"> | <img width="1312" alt="Screen Shot 2022-10-05 at 8 14 45 PM" src="https://user-images.githubusercontent.com/387249/194186944-04ee0cd2-b27b-4d39-8ad2-fdf2e7309cb2.png">
