### ISSUE TITLE
same device gets listed multiple times

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#2496]
## Description 
Found when https://github.com/brave/browser-android-tabs/issues/924 was encountered

It seems like if there's a problem syncing one device on the chain, it gets listed multiple times on another device. 

## Steps to Reproduce

   1. Clean profile on macOS
   2. Import some bookmarks (about 45 from a bookmark file and 7 from safari)
   3. Create Sync chain.
   4. Clean install of 1.0.71 (sync 2) on Android.
   5. Add some bookmarks (I had 5 bookmarks across 3 folders)
   6. Join sync chain. (used QR code scanner)
   7. Get stuck in Loading screen on Android device (https://github.com/brave/browser-android-tabs/issues/924)
   8. After trying to get Brave install to work on Android, I looked back at the macOS device and saw that the same Android device was listed multiple times

## Actual result:
![samedevicelistedmultipletimes](https://user-images.githubusercontent.com/28145373/49891646-0404ec80-fe15-11e8-8857-7fc2a5e952b2.png)

## Expected result:
Device should only be listed once

## Reproduces how often: 
Unsure, only ran into it in this case.

## Brave version (brave://version info)

Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta(64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by AlexeyBarabash** [comment]
Fixed with https://github.com/brave/browser-android-tabs/pull/934

**Comment by GeetaSarvadnya** [comment]
Verification passed on 


Brave | 0.59.12 Chromium: 72.0.3626.17 (Official Build) beta (64-bit)
-- | --
Revision | 08d2140079f8db14c9eb885a803d231b1a30e817-refs/branch-heads/3626@{#315}
OS | Windows

- Verified the STR from description
