### ISSUE TITLE
VPN state is different on different profile window

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#24967]
## Description 

VPN state is different on different profile window

## Steps to Reproduce

   1. Create a new browser profile and enable VPN on it
   2. Create a new user profile for the same browser profile
   3. Check VPN button on the second profile, shows opt-in state 

## Actual result:

VPN state is different on different profile window

## Expected result:
TBD

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.45.1 Chromium: 105.0.5195.37 (Official Build) nightly (64-bit)
-- | --
Revision | `5f67e9f258cc28ab970e57572290edf1863ee3c5-refs/branch-heads/5195@{#621}`
OS | Windows 11 Version 21H2 (Build 22000.856)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @bsclifton @spylogsster @brave/legacy_qa @rebron

**Comment by kjozwiak** [comment]
The above requires `1.45.68` or higher for `1.45.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.45.84 Chromium: 106.0.5249.91 (Official Build) beta (x86_64)
-- | --
Revision | fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}
OS | macOS Version 11.7 (Build 20G817)

### Steps:
1. installed `1.45.84`
2. launched Brave
3. opened `brave://flags`
4. set the `SDK` and `VPN` flags to `Enabled`
5. clicked on `Relaunch`
6. purchased `Brave VPN Subscription` from `account.bravesoftware.com`
7. confirmed connected to `Brave VPN`
8. clicked on the `"hamburger"` menu -> `Create New Profile`
9. entered `Green Profile 2` and created the profile
10. examined the `Brave VPN` connected state

#### Confirmed the 2nd profile was also in the same state as the 1st: **actively connected**.

`brave://flags` | `Brave VPN` (*1st profile*) | `Brave VPN` (*2nd profile*)
-------|---------|---------
<img width="1312" alt="Screen Shot 2022-10-03 at 7 52 16 PM" src="https://user-images.githubusercontent.com/387249/193706857-d5ccbf83-ed2b-4adf-b255-e554cea4cc69.png"> | <img width="1312" alt="Screen Shot 2022-10-03 at 7 54 48 PM" src="https://user-images.githubusercontent.com/387249/193706860-0d796581-3569-4206-9245-27df36f23dfd.png"> | <img width="1312" alt="Screen Shot 2022-10-03 at 7 55 38 PM" src="https://user-images.githubusercontent.com/387249/193706871-4b7b4538-4876-4702-a0b3-a45fb24e9252.png">
