### ISSUE TITLE
Add random button for color background

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#24968]
subtask of https://github.com/brave/brave-browser/issues/15252. 

Overall design also can be found there.

---

When user toggles on a 'random button' for solid colors or gradient colors, we should set random background every time users open up NTP.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.45.74 Chromium: 106.0.5249.55 (Official Build) beta (x86_64)
-- | --
Revision | 4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}
OS | macOS Version 11.7 (Build 20G817)

#### Followed the testplan in https://github.com/brave/brave-core/pull/14828, and confirmed that when `Refresh on every new tab` is checked, each new tab is in a different color. 

example | example
---------|---------
<img width="1429" alt="Screen Shot 2022-09-26 at 6 34 51 PM" src="https://user-images.githubusercontent.com/387249/192392798-9a0fc58d-e586-4a0d-8db1-48fa6e237ae7.png"> | <img width="1332" alt="Screen Shot 2022-09-26 at 6 35 14 PM" src="https://user-images.githubusercontent.com/387249/192392799-e9ec3b8d-5cdf-48b1-b41b-30c04e732793.png">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED`
```
Brave | 1.45.80 Chromium: 106.0.5249.65 (Official Build) beta (64-bit)
-- | --
Revision | 3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}
OS | Windows 11 Version 21H2 (Build 22000.978)
```

### Solid Colors

Case 1: Toggle `ON` `Refresh on every new tab` selected
<details>

1. installed `1.45.80`
2. launched Brave
3. opened a new-tab page
4. clicked on `Customize`
5. clicked on `Solid colors` card
6. toggle `ON` `Refresh on every new tab`
7. open NTP

####  Confirmed when `Refresh on every new tab` toggle is on, background color is picked on every new tab

step 5-6|step 7
----|----
<img width="460" alt="image" src="https://user-images.githubusercontent.com/98358127/193354129-fd3db85e-9186-4dd0-b7e6-1cb8295acdba.png">|<img width="465" alt="image" src="https://user-images.githubusercontent.com/98358127/193354011-c80502ac-538f-4f7d-aa2c-0f51086bb933.png">
<img width="449" alt="image" src="https://user-images.githubusercontent.com/98358127/193354316-03299457-3d11-485e-aad3-471711ff487d.png">

</details>

Case 2: Toggle `OFF` `Refresh on every new tab` 
<details>

1. click customize on the last tab from Case 1
2. click on selected solid color card to return to `Refresh on every new tab`
3. click toggle `OFF` `Refresh on every new tab` 
4. open NTPs

### Confirmed same background color will be picked from the last color in Case 1

<img width="453" alt="image" src="https://user-images.githubusercontent.com/98358127/193354742-c7064f4d-4681-475a-9406-f4eb6be74c2d.png">|<img width="462" alt="image" src="https://user-images.githubusercontent.com/98358127/193355006-266a7528-a3ed-4c00-ae15-20a4d52fd17a.png">

</details>

### Gradients
<details>

Tested above testcases, Case 1 and 2,  for Gradients 

### Confirmed functionality worked as expected for Gradients as well

Ex1|Ex2|Ex3|Ex4
----|----|----|----
<img width="454" alt="image" src="https://user-images.githubusercontent.com/98358127/193355626-81b85f03-274b-4fd4-88ae-2ba75eaed190.png">|<img width="453" alt="image" src="https://user-images.githubusercontent.com/98358127/193355597-7cf14419-4fe4-4b08-9c48-845d87775cba.png">|<img width="454" alt="image" src="https://user-images.githubusercontent.com/98358127/193355874-8ff8abd0-7e95-496e-8554-fe8b60f41a81.png">|<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/193355790-ed8b0726-2ddc-4d2e-b59a-8fd53577700f.png">
</details>
