### ISSUE TITLE
Tor connection timeout is too short

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#24978]
When opening a Tor window, the tor daemon needs to start up and connect to the Tor network. While it's doing that, we should a notification:
![tor-connecting](https://user-images.githubusercontent.com/167821/186740614-c3debdba-d8fb-4f53-8501-34509d5d5929.png)

Once it's done, we change to a successful notification:
![Screenshot from 2022-08-25 11-24-34](https://user-images.githubusercontent.com/167821/186740750-0f7f63b3-5655-4460-a768-96572a2a68f5.png)

In cases of failure, we show an error:
![tor-error](https://user-images.githubusercontent.com/167821/186740830-9bd51aa5-876e-4140-a38f-f14ac0ac0435.png)

The problem is that the error notification is shown unconditionally after a **30-sec timeout**. Sometimes it takes longer than 30s for a connection to be established and in that case, we show the error notification and then a few seconds later, it gets replaced with a success notification, which is pretty confusing.

**Comment by fmarier** [comment]
The proposed solution (thanks to @rmcfadden3 and @aguscruiz) is to add a second timer:

1. "Tor is connecting…" (no change)
2. [30 seconds pass]
3. "Still connecting (there's some slowness in the Tor network)"
4. [30 seconds pass]
5. "Tor connection failed" / "Tor connected successful" (no change)

**Comment by fmarier** [comment]
cc @boocmp

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.47.126 Chromium: 108.0.5359.99 (Official Build) beta (64-bit)
-- | --
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | Windows 11 Version 21H2 (Build 22000.1335)
```



1. Install 1.47.126
2. launch Brave
3. open `brave://settings/privacy` in a new-tab
4. enable `Use Bridges` in Tor windows section
5. select `meek-azure`  in `Select a built-in-bridge` drop-down menu
6. click `Apply changes`
7. click hamburger menu >> `New private window with Tor`


step 4|step 5|initial tor connection|still connecting|Tor failed
----|------|--------|--------|--------
<img width="451" alt="image" src="https://user-images.githubusercontent.com/98358127/207659140-7c6041ff-83cb-43e4-8169-5df51472dac6.png">|<img width="457" alt="image" src="https://user-images.githubusercontent.com/98358127/207659679-f734750a-ed91-466b-8b92-f8f5361cb540.png">|<img width="472" alt="image" src="https://user-images.githubusercontent.com/98358127/207665781-cf9308a3-e9dd-48bb-8bbc-cd883e727024.png">|<img width="949" alt="image" src="https://user-images.githubusercontent.com/98358127/207661939-6be6d0c5-a2c8-43b3-b9ec-9658b7f3dfde.png">|<img width="952" alt="image" src="https://user-images.githubusercontent.com/98358127/207662056-44b50a2c-dd01-4fad-89cd-61edb2b4b97f.png">

**Comment by MadhaviSeelam** [comment]
@boocmp any update on above issue as error message shown for each status takes > 2 minutes 
cc: @fmarier

https://bravesoftware.slack.com/archives/C85NV6NSG/p1671045026328789

**Comment by LaurenWags** [comment]
cc @rebron on https://github.com/brave/brave-browser/issues/24978#issuecomment-1369902290

**Comment by LaurenWags** [comment]
Removing `QA/Blocked` per today's desktop planning meeting. cc-ing @GeetaSarvadnya @btlechowski @kjozwiak to check this issue.

We decided to confirm that the expected messages display and @MadhaviSeelam will log a follow up issue for the timing if it is still problematic.

cc @rebron

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.47.169 Chromium: 109.0.5414.87 (Official Build) (64-bit)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | Ubuntu 18.04 LTS

Verified Tor connection indicator works properly when connection is successful

<details>

Connecting:
![image](https://user-images.githubusercontent.com/34715963/211833805-67c3f0d1-0a87-4ba9-874c-ffc1da7763d4.png)

Connected:
![image](https://user-images.githubusercontent.com/34715963/211833880-f66a3596-6665-4f4b-b7cc-5a5e45496c36.png)



</details>

Verified Tor connection indicator works properly when connection has problems
<details>

Note used STR from https://github.com/brave/brave-browser/issues/24978#issuecomment-1352011898

Connecting:
![image](https://user-images.githubusercontent.com/34715963/211834923-ab6edbdf-9d5f-4a85-96b3-e282317eb688.png)

Connection takes longer than expected
![image](https://user-images.githubusercontent.com/34715963/211837638-35e6b629-8992-494f-9d06-ef1b688cd445.png)

Connection failed
![image](https://user-images.githubusercontent.com/34715963/211837881-957c5e0e-1ade-4f27-bbfd-38e7f9c698ba.png)


</details>


Logged `Tor connection indicator flashes red just before successfully connecting to Tor` https://github.com/brave/brave-browser/issues/27746
Logged `Some string are not translated in Tor connection indicator` https://github.com/brave/brave-browser/issues/27747

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```

Brave | 1.47.169 Chromium: 109.0.5414.87 (Official Build) (64-bit)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | Windows 10 Version 21H2 (Build 19044.2364)

```

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.47.169 Chromium: 109.0.5414.87 (Official Build) (64-bit)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | Windows 11 Version 21H2 (Build 22000.1455)
```
Retested this on 1.47.169

Confirmed `Tor is connecting...`, `Still connecting...` and Tor connection failed` message are shown as expected
Tor connection message are taking longer to show than expected timeout of 45 seconds.  Filed tttps://github.com/brave/brave-browser/issues/27766 

**`Tor is connecting...`**|**`Still connecting...`**|**`Tor connection failed`** 
---------|---------|--------------
<img width="955" alt="image" src="https://user-images.githubusercontent.com/98358127/211948326-0466222f-9512-43a2-bada-08a56d25040f.png">|<img width="945" alt="image" src="https://user-images.githubusercontent.com/98358127/211948497-0cf4a7af-0313-4ee5-9e7a-2d09dc4eeda0.png">|<img width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/211944565-104220d2-f219-4fc2-bc7e-73fa4d197ef6.png">

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

**Comment by boocmp** [comment]
The Meek-Azure bridge has begun to show signs of life, it is trying to create a connection and periodically sends a progress message (14% or 15% of Handshake with a relay done). We're resetting the connection timer at every progress message so this causes the messages "still connecting" and "Tor is connecting" to swap each other until the bridge stops trying to connect.  We need to check 'count' field of the progress message to determine that is the same as we received early and ignore it.
