### ISSUE TITLE
brave-nightly v1.45.2  crashes X 

### ISSUE THREAD

**Issue by fungilife** [brave/brave-browser#24973]
## Description 

brave-nightly v1.45.2 crashes X
arch-linux x86-64 glibc 2.36 xorg 21.1.4 linux lts 5.15 wm openbox

## Steps to Reproduce

1  Youtube video on max-screen instantly crashed X-session all other tabs were working before.
When repeated with only Brave open same thing happened.  When reverting to v1.44.63 the problem was eliminated.

## Actual result:

Error output went to console and wasn't captured.

## Reproduces how often: 

3 times before reverting to older version to isolate the cause.

## Brave version (info found on brave://version)

Nightly v1.45.2

**Comment by fungilife** [comment]
I still revert to 1.44.64 to avoid crashing X when some videos are maximized (youtube, twitch) 

Even when started from terminal to catch some error messages since X crashes, it takes the terminal output out with it.  Maybe I should try forwarding terminal output to a text file?  I'd like to hear your advise for debugging this.

**Comment by fungilife** [comment]
when chrome-base was upped in 1.46 the issue went away.
From further investigation it appeared as an incompatibility of some instruction with openbox, other wm's didn't have the problem (jwm, vtwm, twm, i3) while on openbox it was 100% reliable crash of X server.

**Comment by fungilife** [comment]
The problem persists, I am now at brave-nightly-bin 1.46.38 and still, the only fix is to revert to 1.44.64

I believe it is related to some openbox instruction conflict, Xorg.log doesn't reveal anything when going down.  It is a fast crash with little feedback.

**Comment by bsclifton** [comment]
@fungilife does this still happen?

**Comment by iefremov** [comment]
stale
