### ISSUE TITLE
Solana connected status should changed when permission is revoked

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#24974]
## Description 

Blocked connection shows Green dot instead of red

## Steps to Reproduce

   1. Connect to a Solana Dapp
   2. Check Panel shows `🟢 Connected`
   3. Turn of Solana Dapp permission from `brave://settings/content/solana`
   4. Go back to Panel and check shows `🟢 Blocked` instead of `🔴 Blocked`

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/186722733-0ce61b7e-934b-4fc6-8514-f1b0333932d7.png)

## Expected result:
![image](https://user-images.githubusercontent.com/17010094/186722717-625f2fc3-bb45-4911-bf3b-ca2fdcd22c1f.png)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.43.81 Chromium: 104.0.5112.102 (Official Build) (arm64)
-- | --
Revision | `8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}`
OS | macOS Version 12.5.1 (Build 21G83)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @darkdh @Douglashdaniel

**Comment by darkdh** [comment]
The green status came from "connected" status because it is still connected after we set Solana permission to blocked.
We should consider doing automatically disconnect when Solana permission changed to blocked per site or globally.

**Comment by darkdh** [comment]
Resurface this issue since @mrose17 brought this up when integrating wallet with Brave Talk.

Beside clearing the connected status when permission is removed we should also emit "disconnect" event to let dapps know this happens.

**Comment by mrose17** [comment]
@mrose17 - would like to be in the loop on this!

**Comment by Douglashdaniel** [comment]
Tested with `Phantom` and it looks like they do emit a `disconnect` event when revoking.

https://github.com/brave/brave-browser/assets/40611140/47319bb2-d5a4-4a5a-8b77-d865645215a5

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.58.108 Chromium: 116.0.5845.114 (Official Build) beta (64-bit)
-- | --
Revision | f08ffbe3ce0069ad8207b9d2d7dee38afcccc1b9
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from issue description and [brave/brave-core#19123](https://github.com/brave/brave-core/pull/19123)
- Verified connection status is properly shown on panel when connected to Dapps

https://github.com/brave/brave-browser/assets/17010094/105b58ca-0df0-488c-882a-be3807f5062d
