### ISSUE TITLE
change Find extensions and Themes text

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#2497]
<img width="1308" alt="cws" src="https://user-images.githubusercontent.com/5951041/49892202-360a5480-fdfd-11e8-9985-2da06c97ac88.png">

Text shouldn't say "Brave Web Store" until ours launches.

**Comment by rebron** [comment]
cc: @bradleyrichter @tomlowenthal 

Suggested text as provided by toml:
"You don't have any extensions yet. Would you like to [install some](cws link)?"

**Comment by rebron** [comment]
We should also have text when Extensions are installed and this page isn't empty to point to CWS store for now.

**Comment by mkarolin** [comment]
@srirambv, I'll pull that into the fix.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.59.25 Chromium: 72.0.3626.53 (Official Build) beta (64-bit)
-- | --
Revision | 98434e6cd182d68ce396daa92e9c6310422e6763-refs/branch-heads/3626@{#620}
OS | Windows 7

![image](https://user-images.githubusercontent.com/34715963/51358004-b0478c00-1ac1-11e9-9792-a29f78788c77.png)
