### ISSUE TITLE
Remove Squarespace newsletter tracker

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#24988]
Here's a an example of a link from a Squarespace newsletter:

https://kristenyarker.com/kristen-yarker-dietitian-blog/2022/6/15/chocolate-banana-ice-pops?ss_source=sscampaigns&ss_campaign_id=6305392a3d8976566686c28f&ss_email_id=6307bc4b0140600a14744bc1&ss_campaign_name=Meal+prep+hacks%2C+is+hiding+veggies+OK%2C+new+healthy+homemade+popsicles&ss_campaign_sent_date=2022-08-25T18%3A16%3A00Z

Based on the name, `ss_email_id`, it seems very likely that this tracks clicks from a specific email subscriber.

The unsubscribe link doesn't use that parameter either: https://campaign-preferences.com/unsubscribe/kGuWLaa4X9G8tzigwnD...7kG-mR..Nmd_eVNJW-TUdrVUrwvY-...men5TGkFszr6FEeI8-...LskvlwyqqthfOXA-S3V...8M

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.45.21 Chromium: 105.0.5195.68 (Official Build) nightly (x86_64)
-- | --
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | macOS Version 13.0 (Build 22A5331f)

### Steps:
1. installed `1.45.21`
2. launched Brave
3. opened `Developer Tools` -> `Network` panel from the main menu
4. loaded `https://brave.com/?ss_email_id=1234`
5. confirmed that the query-string parameters were dropped from the final (actually loaded) URL: `https://brave.com`

<img width="1312" alt="Screenshot 2022-09-01 at 4 40 50 PM" src="https://user-images.githubusercontent.com/387249/188030376-49834bca-cfbe-4e81-8f08-acd5bff6fb5f.png">
