### ISSUE TITLE
"Complete" payout status is not showing green "Arrived" message banner

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#24980]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/23429

When `parameters` endpoint returns `complete` (and the date is on or after the payment date), there is no green "Arrived" banner for ad grant. Green "Arrived" banner does not display until you successfully complete the captcha. This seems to indicate that the API isn't being utilized.

## Steps to Reproduce

Pre-req: server should be set to return "complete" for payout status
   1. Clean profile staging env
   2. Enable Rewards
   3. View an ad and redeem it with the server (cash in your payment token)
   4. Close browser
   5. Advance date to the 6th (day before my payout day)
   6. I see the countdown banner as expected.
   7. Close browser
   8. Advance date to the 7th (or 8th, 9th, etc)

Repeat above for unverified rewards as well as verified user w/ a custodial wallet provider (Uphold, Gemini, bF)

## Actual result:

No green "Arrived" banner on ads panel of brave://rewards, rewards panel, NTP widget

## Expected result:

Green "Arrived" banner to show since the API is returning "complete"

Note - possibly the green "Arrived" banner should be removed from view if you complete a captcha? Mentioned by @Miyayes. Need to confirm - makes sense for it to do so in unverified case, but what happens if you have a custodian? does the banner just always display until "off" is returned from API?

## Reproduces how often: 

easily

## Brave version (brave://version info)

```
Brave | 1.43.81 Chromium: 104.0.5112.102 (Official Build) (x86_64)
-- | --
Revision | 8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}
OS | macOS Version 12.5.1 (Build 21G83)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 1.42.x n/a, 1.43.x yes
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @Miyayes @emerick @GeetaSarvadnya

**Comment by LaurenWags** [comment]
Added `QA/Blocked` label until uplifted to 1.43.x

**Comment by LaurenWags** [comment]
Can be tested with 1.43.84 and above.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.43.84 Chromium: 105.0.5195.68 (Official Build) (x86_64)
-- | --
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | macOS Version 12.5.1 (Build 21G83)
```

**Comment by Uni-verse** [comment]
Verification in progress on Android ARM
