### ISSUE TITLE
NTP Stats Toggle is Broken

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#24985]
## Description 
The stats toggle in the customise NTP doesn't update. You can still use it to reshow the stats, and hide them via the 3 dot menu but the toggle isn't working properly.

<img width="742" alt="Screenshot 2022-08-26 at 12 43 48 PM" src="https://user-images.githubusercontent.com/5951041/186979947-de618b27-37fd-4f99-aafd-b6cf6297a06e.png">

**Comment by stephendonner** [comment]
### Confirmed using 

Brave | 1.44.60 Chromium: 105.0.5195.37 (Official Build) nightly (x86_64)
-- | --
Revision | 5f67e9f258cc28ab970e57572290edf1863ee3c5-refs/branch-heads/5195@{#621}
OS | macOS Version 13.0 (Build 22A5321d)



<img width="1321" alt="Screenshot 2022-08-25 at 5 22 55 PM" src="https://user-images.githubusercontent.com/387249/186791280-26924e22-4bc2-48ac-9848-9b207570bef2.png">

### Steps:
1. install `1.44.60`
2. launch Brave
3. open a new tab/window
4. click on `Customize` on the lower right
5. click on `Brave Stats`
6. look at the `Show Brave Stats` button

Actual:

It's disabled

Expected:

It should be on/off toggleable (sp!)

**Comment by stephendonner** [comment]
Also broken in 

Brave | 1.45.1 Chromium: 105.0.5195.37 (Official Build) nightly (x86_64)
-- | --
Revision | 5f67e9f258cc28ab970e57572290edf1863ee3c5-refs/branch-heads/5195@{#621}
OS | macOS Version 13.0 (Build 22A5321d)

**Comment by stephendonner** [comment]
## Verified `PASSED` using 


### Steps:

1. launch Brave
2. open a new tab/window
3. click on Customize on the lower right
4. click on Brave Stats
5. look at the Show Brave Stats button
6. toggle it `Off`
7. toggle it `On`

#### Confirmed `Off` / `On` state correlated with stats dashboard

toggled `Off` | toggled `On`
--------------|--------------
<img width="1312" alt="Screenshot 2022-09-01 at 10 46 21 PM" src="https://user-images.githubusercontent.com/387249/188067258-09a8609e-0331-4051-abe8-ffb83fac2c6e.png"> | <img width="1312" alt="Screenshot 2022-09-01 at 10 46 26 PM" src="https://user-images.githubusercontent.com/387249/188067260-5417652b-ee76-4970-b9d0-509ea0c2ddaa.png">

**Comment by kjozwiak** [comment]
Removed the `QA Pass-macOS` as this will need to be rechecked on `1.44.x` once we get RC builds. I also added `release-notes/include` as this ended up making it into `1.44.x`. Hence, adding it into the `1.44.x` maintenance release.

**Comment by kjozwiak** [comment]
The above requires `1.44.108` or higher for `1.44.x` verification. Just a note that DevOps kicked off a `1.44.107` for `noplatforms` so there was never any platforms builds for that version.

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```
```
- Reproduced the issue in `1.44.101`
