### ISSUE TITLE
odd display (scroll bar related) on pending contributions modal

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#24982]
## Description 

Follow up for https://github.com/brave/brave-browser/issues/16619

Weird UI display on the pending contributions panel when there's no scrollbar

## Steps to Reproduce

   1. Create a pending contribution (ex. tip an unverified creator)
   2. Go to brave://rewards
   3. Open pending contributions list

## Actual result:

<img width="1192" alt="Screen Shot 2022-08-25 at 8 03 02 AM" src="https://user-images.githubusercontent.com/28145373/186749691-4d7c5a29-e891-4fd2-8a35-b88b1d36ac29.png">

## Expected result:

no space/line for scrollbar when it's not needed

## Reproduces how often: 

easily

## Brave version (brave://version info)

1.45.x / 1.44.63

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes 1.44.x
- Can you reproduce this issue with the nightly channel? yes 1.45.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @Miyayes @zenparsing @GeetaSarvadnya

**Comment by kjozwiak** [comment]
The above requires `1.44.73` or higher for `1.43.x` verification 👍

**Comment by LaurenWags** [comment]
Verified using

```
Brave | 1.44.73 Chromium: 105.0.5195.68 (Official Build) beta (x86_64)
-- | --
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | macOS Version 12.5.1 (Build 21G83)
```
