### ISSUE TITLE
change text on Tips panel

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#2499]
## Design/Screenshot 

<img width="569" alt="tips-panel-text" src="https://user-images.githubusercontent.com/5951041/49893893-6522c500-fe01-11e8-81a0-79dad8db8663.png">

## Description
1. Go to brave://rewards and scroll to bottom.

Currently reads: 
“Tip content creators directly as you browse or give tips to videos and tweets that you ‘like’. You can also set up recurring monthly tips so you can support sites continuously.”

Change text so it reads: 
“Tip content creators directly as you browse. You can also set up recurring monthly tips so you can support sites continuously.”

**Comment by GeetaSarvadnya** [comment]
Verification passed on 

Brave | 0.59.12 Chromium: 72.0.3626.17 (Official Build) beta (64-bit)
-- | --
Revision | 08d2140079f8db14c9eb885a803d231b1a30e817-refs/branch-heads/3626@{#315}
OS | Windows

- Verified changed text on tips panel
![image](https://user-images.githubusercontent.com/38657976/50352695-06311e80-056c-11e9-872a-e7effb3b0b81.png)
