### ISSUE TITLE
ENS L2 offchain contenthash resolution

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#24991]
ENS L2 for wallet address was implemented here https://github.com/brave/brave-browser/issues/22930
In scope of this issues content hash record also should be supported for omnibox scenario.

<details><summary>UI will be covered in separate issue</summary>

Also there should be some ui for that per https://github.com/brave/security/issues/966#issuecomment-1225138567
_Make it clear in the UI that an offchain resolution took place ("resolved offchain by XYZ URL") with a place to learn more about what exactly this means._
Maybe like these
![image](https://user-images.githubusercontent.com/168356/186893422-097bf058-d2ff-4ce3-9fa7-9ae4803e06ad.png)
![image](https://user-images.githubusercontent.com/168356/186893433-de2f7bf0-57e0-456f-80d7-619ae2a1f1a6.png)

</details>

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (64-bit)
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | Linux

- Verified steps from [brave/brave-core#14945](https://github.com/brave/brave-core/pull/14945)
- Verified `offchainexample.eth` resolve to ETH address

https://user-images.githubusercontent.com/17010094/195846125-f1a19a33-ebf6-45b1-8d16-abaf523f0e48.mp4

----------------
Verification passed on 

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (64-bit)
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | Windows 11 Version 21H2 (Build 22000.978)

- Verified steps from [brave/brave-core#14945](https://github.com/brave/brave-core/pull/14945)
- Verified `offchainexample.eth` resolve to ETH address

https://user-images.githubusercontent.com/17010094/195845465-0ada32f5-d997-458c-bb5b-e6559e8c2cdc.mp4


----------------
Verification passed on 

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (arm64)
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | macOS Version 12.6 (Build 21G115)

- Verified steps from [brave/brave-core#14945](https://github.com/brave/brave-core/pull/14945)
- Verified `offchainexample.eth` resolve to ETH address

https://user-images.githubusercontent.com/17010094/195855547-342fdd5d-5713-4e05-95a6-6888685f8716.mov
