### ISSUE TITLE
UI for ENS L2 offchain wallet address resolution

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#24990]
ENS L2 was implemented here https://github.com/brave/brave-browser/issues/22930
per https://github.com/brave/security/issues/966#issuecomment-1225138567
_Make it clear in the UI that an offchain resolution took place ("resolved offchain by XYZ URL") with a place to learn more about what exactly this means._
We need some ui for wallet 'send to' scenario.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (64-bit)
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | Linux

- Verified steps from [brave/brave-core#15010](https://github.com/brave/brave-core/pull/15010)
- Verified a new setting `Allow ENS offchain lookup.` is available under `brave://settings/extensions`
- Verified default setting for `Allow ENS offchain lookup.` is `Ask`
- Verified entering `offchainexample.eth` in Send field shows address resolution confirmation
- Verified selecting `Do not ask again` and either `Yes` or `No` sets the setting as default
- Verified able to modify the setting via `brave://settings/extensions`, automatically updates behaviour after page refresh on brave://wallet

https://user-images.githubusercontent.com/17010094/198954788-4864fd9c-b3ba-4498-9ffe-c66bbcd8a9f8.mp4


----------------
Verification passed on 

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (64-bit)
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | Windows 11 Version 22H2 (Build 22621.674)

- Verified steps from [brave/brave-core#15010](https://github.com/brave/brave-core/pull/15010)
- Verified a new setting `Allow ENS offchain lookup.` is available under `brave://settings/extensions`
- Verified default setting for `Allow ENS offchain lookup.` is `Ask`
- Verified entering `offchainexample.eth` in Send field shows address resolution confirmation
- Verified selecting `Do not ask again` and either `Yes` or `No` sets the setting as default
- Verified able to modify the setting via `brave://settings/extensions`, automatically updates behaviour after page refresh on brave://wallet

https://user-images.githubusercontent.com/17010094/198953510-1ad5dc70-0d7b-4114-97c6-d9a9ad7226ef.mp4


----------------
Verification passed on 

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (arm64)
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | macOS Version 12.6 (Build 21G115)

- Verified steps from [brave/brave-core#15010](https://github.com/brave/brave-core/pull/15010)
- Verified a new setting `Allow ENS offchain lookup.` is available under `brave://settings/extensions`
- Verified default setting for `Allow ENS offchain lookup.` is `Ask`
- Verified entering `offchainexample.eth` in Send field shows address resolution confirmation
- Verified selecting `Do not ask again` and either `Yes` or `No` sets the setting as default
- Verified able to modify the setting via `brave://settings/extensions`, automatically updates behaviour after page refresh on brave://wallet

https://user-images.githubusercontent.com/17010094/198954019-201e6b42-68a6-4a99-b6dd-675733be896b.mov
