### ISSUE TITLE
VPN state is not updated correctly 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#25006]
## Description 

VPN state is not updated correctly 

## Steps to Reproduce

   1. Connect VPN 
   2. Continues to show `Connecting`
   3. Panel doesn't show green dot to indicate its connected
   4. Close Panel and reopen shows connected

## Actual result:

https://user-images.githubusercontent.com/17010094/186959417-1edc734e-e5ad-4350-9c7b-e9ae6f2964c0.mp4

## Expected result:
Should show state correctly 

## Reproduces how often: 

Easy 

## Brave version (brave://version info)

<html>
<body>

Brave | 1.45.5 Chromium: 105.0.5195.52 (Official Build) nightly (64-bit)
-- | --
Revision | `412c95e518836d8a7d97250d62b29c2ae6a26a85-refs/branch-heads/5195@{#853}`
OS | Windows 11 Version 21H2 (Build 22000.856)

</body>
</html>
## Version/Channel Information:

- Can you reproduce this issue with the current release? Not checked
- Can you reproduce this issue with the beta channel? Not checked
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @bsclifton @spylogsster @brave/legacy_qa

**Comment by bsclifton** [comment]
Looks like it's getting stuck in connected state; definitely something we want to fix

**Comment by simonhong** [comment]
@srirambv Can you check this issue is still happening?
I tried to reproduce this with latest nightly (`Version 1.45.64 Chromium: 106.0.5249.40`) and local dev build.
but both works well.

**Comment by srirambv** [comment]
Seems to be fixed on nightly for me as well. Checked on `1.45.64 Chromium: 106.0.5249.40 (Official Build) nightly (64-bit)` and seems to work fine. Closing the issue for now. Can reopen the issue if it happens again
