### ISSUE TITLE
Sync v2 usability issues

### ISSUE THREAD

**Issue by cezaraugusto** [brave/brave-browser#2500]
## ~~Users are unable to differentiate between devices with the same name~~ fixed by https://github.com/brave/brave-core/pull/1136

**First report:** https://bravesoftware.slack.com/archives/C2HJYB45N/p1544587433023800

**Possible solutions:** 

1. Re-enable the option to add a device name
2. Re-enable the `device id` table row

## ~~Children of device type modal should use the same modal~~ carried over to https://github.com/brave/brave-browser/issues/2677

**First report:** https://github.com/brave/brave-core/pull/1019/files/cdbd7580077798806d6d160e72a64f7e8ece0193#diff-43b07d9c901bb298f50280da4bcf368d
**Second report:** https://github.com/brave/brave-core/pull/1019#pullrequestreview-184340284

**Possible solutions:**

1. Close previous modals when user hit `tablet/phone` or `desktop` options
2. Change content in the modals so they all use the same one

## ~~Table column spacing (and button column could collapse to above / below table)~~ fixed by https://github.com/brave/brave-core/pull/1155

<img src="https://user-images.githubusercontent.com/741836/49892678-68688180-fdfe-11e8-8262-b8f49d0593b5.png">

**First report:** https://github.com/brave/brave-core/pull/1019#pullrequestreview-184340284

**Possible solutions:**

## ~~Text in the first screen (disabled content) feels extremely cramped and uneven~~ carried over to https://github.com/brave/brave-browser/issues/2675

<img src="https://user-images.githubusercontent.com/741836/49891673-ebd4a380-fdfb-11e8-8297-c2ccbd843456.png">

**First report:** https://github.com/brave/brave-core/pull/1019#pullrequestreview-184340284

**Possible solutions**

1. Tweak the line height

## ~~Data Toggle has extra couple of blank rows from disabled sync types.~~ carried over to https://github.com/brave/brave-browser/issues/2676

<img src="https://user-images.githubusercontent.com/741836/49892620-440ca500-fdfe-11e8-875b-fd2e2a31db06.png">

**First report:** https://github.com/brave/brave-core/pull/1019#pullrequestreview-184340284

**Possible solutions**

1. In brave-ui we should remote the previous 3-row grid for bookmarks/site settings/history. Since we only added `bookmarks` in v2, it should host only 1 row.

**Comment by bradleyrichter** [comment]
@cezaraugusto can you trim the date/time string to only show date? The column is really to help you notice a problem or an intruder.

**Comment by cezaraugusto** [comment]
@bradleyrichter created https://github.com/brave/brave-browser/issues/2501. put it in backlog as it is the usual but please ping if it should be in 0.58.x and we can discuss with the uplifting team

**Comment by rebron** [comment]
We want to pull in device name from the system/device and not have to specify our own. 
cc: @darkdh

**Comment by darkdh** [comment]
>We want to pull in device name from the system/device and not have to specify our own.
>cc: @darkdh


@rebron the issue is tracked here https://github.com/brave/brave-browser/issues/2573

**Comment by cezaraugusto** [comment]
all content described here was either fixed or moved to their own issues so we can make it easier to review/test. based on this I'm going to close and remove the "release/blocking" label. you can see the fixes and issues in this issue initial comment.
