### ISSUE TITLE
update default behavior permission settings for Autoplay, Ethereum, and Solana 

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#25016]
## Description 

Permission settings for Autoplay, Ethereum, and Solana use a primary toggle for settings. The new design for content and permission settings includes a description and "Default behavior" title and description with radio buttons to choose between options.

## Steps to Reproduce

   1. Go to brave://settings/content/autoplay; brave://settings/content/ethereum; and brave://settings/content/solana
   2. Notice primary toggle.
   3. Should be new style and match designs from Figma designs.

## Actual result:

<img width="705" alt="Screenshot 2022-08-26 at 2 05 57 PM" src="https://user-images.githubusercontent.com/5951041/186990706-4b84c9e4-8b70-4f7a-8383-a075080ab91b.png">
<img width="692" alt="Screenshot 2022-08-26 at 2 06 12 PM" src="https://user-images.githubusercontent.com/5951041/186990708-374fb77d-fd52-4c4a-aa90-eaf24b9c5154.png">
<img width="686" alt="Screenshot 2022-08-26 at 2 06 22 PM" src="https://user-images.githubusercontent.com/5951041/186990710-baa2193c-5a8b-4842-b28e-16a3f2f50dc7.png">

## Expected result:
https://www.figma.com/file/tLXWGCpNoiJxDZDdpfordj/Desktop-Settings?node-id=2967%3A64568

See comment for screenshots https://github.com/brave/brave-browser/issues/25016#issuecomment-1253653746

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by aguscruiz** [comment]
Design ready here:
https://www.figma.com/file/tLXWGCpNoiJxDZDdpfordj/Desktop-Settings?node-id=2967%3A64568

![image](https://user-images.githubusercontent.com/15734630/191506217-e4f9ebd6-db08-4f89-869c-8cbb7bf4b9ec.png)

![image](https://user-images.githubusercontent.com/15734630/191506248-6f83d570-89c3-420b-a47f-9a1181fbe939.png)

![image](https://user-images.githubusercontent.com/15734630/191506301-5f6e7c88-bc00-4417-9a72-424151cb54f6.png)

**Comment by rebron** [comment]
cc: @yrliou @darkdh We still need text for these settings.

**Comment by rebron** [comment]
Closing as dupe of https://github.com/brave/brave-browser/issues/31710 and fixed in 1.56.x
