### ISSUE TITLE
Sites can write to the clipboard without any confirmation from user

### ISSUE THREAD

**Issue by pashynskykh** [brave/brave-browser#25019]
## Description 
Brave (Chrome) allows websites to write to the clipboard without the user’s permission.

## Steps to Reproduce

   1. Visit https://webplatform.news/
   2. Check clipboard

## Actual result:
Clipboard isn't modified.

## Expected result:
Site changed content of clipboard.

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

1.42.97 Chromium: 104.0.5112.102 (Offisiell delversjon) (arm64) 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes.
- Does the issue resolve itself when disabling Brave Rewards? Yes.
- Is the issue reproducible on the latest version of Chrome? Yes.

## Miscellaneous Information:
Relevant commit in Chromium's source code: https://chromium.googlesource.com/chromium/src/+/4d7b74b051abfe5945f418601fdc2ffc8ce3072c

**Comment by UjCbFwtBayFM** [comment]
Already known: https://github.com/brave/brave-browser/issues/16890

**Comment by rebron** [comment]
Closing as dupe of #16980 and fixed in 1.43.93 release.
Thanks @UjCbFwtBayFM
