### ISSUE TITLE
Sync `Added On` column should show only date

### ISSUE THREAD

**Issue by cezaraugusto** [brave/brave-browser#2501]
Per @bradleyrichter [suggestion](https://github.com/brave/brave-browser/issues/2500#issuecomment-446718444), we should trim the date/time string to only show date. The column is really to help you notice a problem or an intruder.

cc @AlexeyBarabash @darkdh

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.60.19 Chromium: 72.0.3626.81 (Official Build) beta(64-bit)
-- | --
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS | Mac OS X

![screen shot 2019-02-05 at 3 54 09 pm](https://user-images.githubusercontent.com/28145373/52303886-3e938d00-295f-11e9-9ae2-66db2119b610.png)

Also encountered and logged https://github.com/brave/brave-browser/issues/3234
