### ISSUE TITLE
Feature Request: The ability to support accounts on odysee.com, minds.com, bitchute.com, and nexusmods.com

### ISSUE THREAD

**Issue by wavesurf432** [brave/brave-browser#25023]
Feature Request:

The ability to support individual accounts (similar to YouTube, GitHub, e.t.c.), via tips and/or auto-contribute, on odysee.com, minds.com, bitchute.com, and nexusmods.com.

**Comment by UjCbFwtBayFM** [comment]
FYI they removed Github support some time ago. It's unclear if they plan to support them again.

**Comment by wavesurf432** [comment]
> FYI they removed Github support some time ago. It's unclear if they plan to support them again.

Tipping a GitHub user no longer works now? Do you know if this was done in favour of supporting/using GitLab? 

Thanks for the information.

**Comment by Miyayes** [comment]
> > FYI they removed Github support some time ago. It's unclear if they plan to support them again.
> 
> Tipping a GitHub user no longer works now? Do you know if this was done in favour of supporting/using GitLab?
> 
> Thanks for the information.

Those who already verified their GitHub accounts still work, but GitHub has been disabled for any new verifications with Brave Creators.

**Comment by Miyayes** [comment]
Thanks for the suggestions. We have a big list of platforms we want to support, including some of the ones you mentioned, so I'll close this issue out. Will open GH issues for these once it's time to implement them!
