### ISSUE TITLE
Brave rewards banner creator doesn't parse usernames

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#2502]
Log into the publishers dashboard and attempt to add a Twitter, Twitch, or YouTube link to your profile. If you just enter a username, it should be parsed into the profile URI for that service.

**Comment by mandar-brave** [comment]
Opened: https://github.com/brave-intl/publishers/issues/1444
cc @tomlowenthal 

Issue created in incorrect repo!
