### ISSUE TITLE
Add missing tokens, enable fantom

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#25029]
Add the the following tokens:

1. 0x
2. Axie Infinity
3. MATIC (on ethereum chain)
4. TUSD

**Comment by kjozwiak** [comment]
The above requires `1.44.78` or higher for `1.44.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.44.86 Chromium: 105.0.5195.127 (Official Build) beta (64-bit) 
-- | --
Revision | `912488396852bf658ab32465980c0b93a3c27a83-refs/branch-heads/5195@{#1109}`
OS | Linux

- Verified steps from [brave/brave-core#14881](https://github.com/brave/brave-core/pull/14881)
- Verified missing tokens are now listed
- Verified Buy via Sardine option is shown for supported tokens
- Verified on both light and dark theme
- Verified Sardine is only shown for US locale
- Encountered [#25422](https://github.com/brave/brave-browser/issues/25422)

https://user-images.githubusercontent.com/17010094/190394482-a053783b-d096-467d-a45b-2071383fb5b9.mp4


------------------------
Verification passed on

Brave | 1.44.86 Chromium: 105.0.5195.127 (Official Build) beta (64-bit) 
-- | --
Revision | `912488396852bf658ab32465980c0b93a3c27a83-refs/branch-heads/5195@{#1109}`
OS | Windows 11 Version 21H2 (Build 22000.795)

- Verified steps from [brave/brave-core#14881](https://github.com/brave/brave-core/pull/14881)
- Verified missing tokens are now listed
- Verified Buy via Sardine option is shown for supported tokens
- Verified on both light and dark theme
- Verified Sardine is only shown for US locale
- Encountered [#25422](https://github.com/brave/brave-browser/issues/25422)

https://user-images.githubusercontent.com/17010094/190392446-64e60582-e34f-469b-bf08-87cb7d5636ec.mp4


------------------------
Verification passed on

Brave | 1.44.86 Chromium: 105.0.5195.127 (Official Build) beta (arm64)
-- | --
Revision | `912488396852bf658ab32465980c0b93a3c27a83-refs/branch-heads/5195@{#1109}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [brave/brave-core#14881](https://github.com/brave/brave-core/pull/14881)
- Verified missing tokens are now listed
- Verified Buy via Sardine option is shown for supported tokens
- Verified on both light and dark theme
- Verified Sardine is only shown for US locale
- Encountered [#25422](https://github.com/brave/brave-browser/issues/25422)

https://user-images.githubusercontent.com/17010094/190395270-9afd3e26-17aa-4d42-8600-1ecbfa9650a6.mov
