### ISSUE TITLE
Users cannot connect their brave wallet to adobe accounts

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#25039]
## Description 

After user signs the transaction they get an error with 'Something went wrong. Please try again later.' (https://connected-accounts.adobe.com/?)
https://bravesoftware.slack.com/archives/C02S9LFEXU4/p1661783493953629

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by bbondy** [comment]
This turns out to be because the accounts we return `EIP-55` checksumed addresses to dapps instead of what MetaMask does (lowercase accounts). 

The connected account is sent up in a JSON structure to Adobe with a POST HTTPS request to `https://connected-accounts.adobe.com/api/connection/metamask`. If that address is not lowercase, the server responds with an HTTP status code of 400. 

it looks like we're going to have to modify to return lowercase addresses for better MM compat.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (64-bit) 
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | Linux

- Verified able to connect to Adobe accounts 

https://user-images.githubusercontent.com/17010094/196124418-7b8de219-a704-4156-83d2-0f7378ac24fb.mp4


------------------------
Verification passed on

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (64-bit) 
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | Windows 11 Version 21H2 (Build 22000.978)

- Verified able to connect to Adobe accounts 

https://user-images.githubusercontent.com/17010094/196124446-edf3d643-4ca8-4cdc-bd63-56c3fe09ed72.mp4


------------------------
Verification passed on

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (arm64)
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | macOS Version 12.4 (Build 21F79)

- Verified able to connect to Adobe accounts 

https://user-images.githubusercontent.com/17010094/196123960-97e06207-9672-40ea-a357-e85c5d1eee64.mov
