### ISSUE TITLE
Allow users to select a specific "Brave background"

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#25030]
Subtask of https://github.com/brave/brave-browser/issues/15252

---

* When user select a specific brave background, that background should be applied for all NTPs
* Sponsored image should be visible as is.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.45.75 Chromium: 106.0.5249.65 (Official Build) beta (x86_64)
-- | --
Revision | 3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}
OS | macOS Version 11.7 (Build 20G817)

### Steps:
1. installed `1.45.75`
2. launched Brave
3. opened a new-tab page
4. clicked on `Customize`
5. clicked on Brave Backgrounds
6. clicked on a background
7. confirmed `Refresh on every new tab` was deselected automatically

#### Confirmed my chosen image was used for each new tab, excepting the Sponsored Images backgrounds.

example | example | example
---------|----------|---------
<img width="1312" alt="Screen Shot 2022-09-27 at 10 38 12 AM" src="https://user-images.githubusercontent.com/387249/192557426-dbb5d875-2815-4437-826d-ad3efbac5ba3.png"> | <img width="1312" alt="Screen Shot 2022-09-27 at 10 38 20 AM" src="https://user-images.githubusercontent.com/387249/192557454-ecce38c0-73bc-4faf-ab7e-a2e438659231.png"> | <img width="1201" alt="Screen Shot 2022-09-27 at 10 40 15 AM" src="https://user-images.githubusercontent.com/387249/192557471-d2998c39-25ab-42fc-aafc-09a5081d8030.png">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.45.80 Chromium: 106.0.5249.65 (Official Build) beta (64-bit)
-- | --
Revision | 3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}
OS | Windows 11 Version 21H2 (Build 22000.978)
```

### Steps:

Case 1: `Refresh on every new tab` auto-deselected
<details>

1. installed `1.45.80`
2. launched Brave
3. opened a new-tab page
4. clicked on `Customize`
5. clicked on Brave Backgrounds
6. clicked on a background
7. confirmed `Refresh on every new tab` was deselected automatically

#### Confirmed chosen image was used for each new tab, excepting the Sponsored Images backgrounds.

step5|step6-7|result|SI
-----|----|------|-----
<img width="455" alt="image" src="https://user-images.githubusercontent.com/98358127/193329473-de4e151f-bfc8-45c0-86b6-2a4a4e762123.png">|<img width="450" alt="image" src="https://user-images.githubusercontent.com/98358127/193331804-d0335435-866b-4396-adbe-cfa74d32b251.png">|<img width="456" alt="image" src="https://user-images.githubusercontent.com/98358127/193332176-dd01ddc4-b361-4876-aae3-a94572103eff.png">|<img width="456" alt="image" src="https://user-images.githubusercontent.com/98358127/193331871-180b42f9-ccbc-4b68-8e6a-0dbc0fbb8226.png">
</details>

Case 2: `Refresh on every new tab` toggle `ON`
<details>

1. continue from Case 1
2. toggle `ON` `Refresh on every new tab`
3. load new tabs 
4. Brave background images are rotated as expected

step 2|step3|step4
----|----|-----
<img width="453" alt="image" src="https://user-images.githubusercontent.com/98358127/193338720-b20b8c97-2c40-43f2-9599-24266e3eb771.png">|<img width="457" alt="image" src="https://user-images.githubusercontent.com/98358127/193338485-213e31cd-cb51-48b3-af82-eee125da759a.png">|<img width="452" alt="image" src="https://user-images.githubusercontent.com/98358127/193338447-a1eae589-7426-4268-98e4-22ca318c9241.png">
</details>
