### ISSUE TITLE
[Android 13] Notifications - user manually disable notifications

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#25042]
### Problem
Android 13 has introduced a notifications permission request modal similar to iOS. Currently this modal appears randomly during the onboarding flow. We are solving for this by triggering a permissions prompt during rewards / privacy report opt-in (further details in #25041). However users will still able to disable notifications manually which would result in:

1. Private ads no longer functioning.
2. Brave unable to send the weekly privacy report notification.

### Solution
We should inform users **BEFORE AND AFTER** they attempt to disable notifications that this action will impact the private ads and privacy report features.

### Requirements
_IMPORTANT NOTE: All of the following requirements are conditional to private ads and/or privacy report being ON._

**Brave Settings Menu**
1. When a user **attempts** to disable notifications from the Brave settings menu we should:
- Show a message asking “are you sure you want to do that because…” informing the user that this action will disable private ads and/or the privacy weekly report (_depending on which feature is currently enabled_).
- Show the option to ignore the message or cancel action.
- On tap of cancel option: keep notifications enabled.
- On tap of ignore: disable notifications.

2. After a user disables notifications from the Brave settings menu we should:
- Switch off private ads and add a notice near the private ads toggle informing the user that they need to re-enable notifications for the private ads to function.
- Add a notice in the privacy report informing the user that they need to re-enable notifications to be able to receive the weekly privacy report.
- On tap of notices: show notifications permission modal.

**Android System Settings**
1. When a user disables notifications from the Android system settings. On next launch of Brave we should:
- Show a message informing the user that private ads and/or the weekly privacy report (_depending on which feature is currently enabled_) will no longer function without notifications enabled.
- Show the option to ignore or enable notifications.
- On tap of enable notifications option: show notifications permission modal.
- On tap of ignore: keep notifications disabled. Do not show the launch message again.

| Brave Settings: Notifications | Android System Settings: Notifications |
| ------------- | ------------- |
| _Main Menu -> Settings -> Notifications_  | _Settings App -> Notifications -> Included Apps_ |
| ![Image](https://user-images.githubusercontent.com/28269287/187260549-3a7455af-c51b-4607-b5e4-8227b3d3c51c.png) | ![Image](https://user-images.githubusercontent.com/28269287/187260390-fcc3e9ff-34c3-485c-bae0-459314c6f859.png) |

### Designs

Figma: https://www.figma.com/file/sdVBBufbl2A11hAgPNfyqG/Android-13-Notifications

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung Galaxy S10+` running `Android 13` using the following build(s):

```
Brave | 1.46.133 Chromium: 108.0.5359.71 (Official Build) (32-bit)
--- | ---
Revision | 1e0e3868ee06e91ad636a874420e3ca3ae3756ac-refs/branch-heads/5359@{#1016}
OS | Android 13; Build/T1B3.221003.008
```

### `Reward Cases`

* ensure that the user can opt-in into rewards without any issues if they enabled OS notifications during onboarding
* ensured that the `Allow Brave to send you notification` modal appears if `Not now` was selected while onboarding
* ensured that the user receives a `Enable notifications from Brave to earn Brave Rewards` if OS notifications have been disabled 
* ensured that the user receives a `You're not earning Rewards` warning if you've disabled OS notifications but have rewards enabled with `Settings` -> `Brave Rewards` -> `Show Ads when Brave is not in use` enabled
* also ensured that the modals only appear once via https://github.com/brave/brave-browser/issues/26930#issuecomment-1334291301

Example video of the feature working --> https://youtu.be/SqNVWJfbXJA

Also created https://github.com/brave/brave-browser/issues/27002 as a follow up.

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------|----------------|-----------------
![Screenshot_20221201-164606](https://user-images.githubusercontent.com/2602313/205165917-35037164-b7f9-4cfc-ab85-7b92bc6e6625.png) | ![Screenshot_20221201-164609](https://user-images.githubusercontent.com/2602313/205166167-ee5a5eaf-e057-43b2-ad62-e6cf527c3cba.png) | ![Screenshot_20221201-163919](https://user-images.githubusercontent.com/2602313/205164681-1a9bcf9b-c2ee-4174-8a10-98f2dd43b4ac.png) | ![Screenshot_20221201-162948](https://user-images.githubusercontent.com/2602313/205164734-7debf61b-4d2e-4684-bbe9-a02480390f43.png) | ![Screenshot_20221201-164655](https://user-images.githubusercontent.com/2602313/205166045-3fd792da-42cc-4bc3-870f-f55dcf0c13c0.png)

### `Privacy Report Cases`



**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------|----------------|----------------|----------------
![Screenshot_20221201-164606](https://user-images.githubusercontent.com/2602313/205165917-35037164-b7f9-4cfc-ab85-7b92bc6e6625.png) | ![Screenshot_20221201-164609](https://user-images.githubusercontent.com/2602313/205166167-ee5a5eaf-e057-43b2-ad62-e6cf527c3cba.png) | ![Screenshot_20221201-165614](https://user-images.githubusercontent.com/2602313/205167913-a4e4401c-ed77-43e3-a3db-df067bd03ef2.png) | ![Screenshot_20221201-165620](https://user-images.githubusercontent.com/2602313/205167925-adb71274-9769-436b-a1c1-5f2378c5398d.png) | ![Screenshot_20221201-165625](https://user-images.githubusercontent.com/2602313/205167943-2feee8fb-d8f9-499a-9a80-5540de683676.png) | ![Screenshot_20221201-165651](https://user-images.githubusercontent.com/2602313/205167949-c7d08688-df8e-4c41-bee5-2b97e16d4dcf.png)

Example video of the feature working --> https://youtube.com/shorts/niVE7t-iVrw

**Comment by kjozwiak** [comment]
Ran into https://github.com/brave/brave-browser/issues/27107 & https://github.com/brave/brave-browser/issues/27108 while running through the above verification on `Android 12`.
