### ISSUE TITLE
Update Onboarding text to state supported recovery phrase lengths 

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#25043]
## Description 

The new onboarding text does not consistently mention that a wallet recovery phrase can be 12-24 words long

## Steps to Reproduce

   1. Reset Brave Wallet or create a new profile
   2. Open `brave://wallet/crypto`
   3. Click import
   4. Click import from from seed phrase

## Actual result:

Page description only mentions 12-word recovery phrases

## Expected result:
Page description only mentions 12-24 word recovery phrases

## Reproduces how often: 

Easy

## Brave version (brave://version info)

1.45.5 Chromium: 105.0.5195.52 (Official Build) nightly (arm64) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

**Comment by bradleyrichter** [comment]
It should probably be "12/24 words" rather than 12-24 words.

**Comment by kjozwiak** [comment]
The above requires `1.44.77` or higher for `1.44.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.44.86 Chromium: 105.0.5195.127 (Official Build) beta (64-bit) 
-- | --
Revision | `912488396852bf658ab32465980c0b93a3c27a83-refs/branch-heads/5195@{#1109}`
OS | Linux

- Verified steps from issue description
- Verified onboarding text shows supported recovery phrase length to be `12-24 words`
![image](https://user-images.githubusercontent.com/17010094/190648764-e009ab81-d624-45e5-8c66-c18dc3262219.png)


------------------------
Verification passed on

Brave | 1.44.86 Chromium: 105.0.5195.127 (Official Build) beta (64-bit) 
-- | --
Revision | `912488396852bf658ab32465980c0b93a3c27a83-refs/branch-heads/5195@{#1109}`
OS | Windows 11 Version 21H2 (Build 22000.795)

- Verified steps from issue description
- Verified onboarding text shows supported recovery phrase length to be `12-24 words`
![image](https://user-images.githubusercontent.com/17010094/190648923-a9c06a77-ddbb-45a1-a2d2-5e1a63ff7919.png)

------------------------
Verification passed on

Brave | 1.44.86 Chromium: 105.0.5195.127 (Official Build) beta (arm64)
-- | --
Revision | `912488396852bf658ab32465980c0b93a3c27a83-refs/branch-heads/5195@{#1109}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from issue description
- Verified onboarding text shows supported recovery phrase length to be `12-24 words`
![image](https://user-images.githubusercontent.com/17010094/190649009-420bd9d4-8b15-4804-bfe4-ce3f46c2e96f.png)
