### ISSUE TITLE
Hide non-working Safe Browsing setting on Android

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#25047]
A [community thread](https://community.brave.com/t/need-a-way-more-detailed-explanation-of-how-safe-browsing-works/427253) has brought to my attention that we currently have a Safe Browsing setting on Android, which claims that Safe Browsing is ON, even though it's not (it's never worked in brave-core: https://github.com/brave/brave-browser/issues/8705).

We should hide this setting until we fix Safe Browsing support.

![Screenshot_20220829-103855](https://user-images.githubusercontent.com/167821/187264244-37b5f8c3-0e46-4f46-baf1-d266ba18b8ed.png) ![Screenshot_20220829-103917](https://user-images.githubusercontent.com/167821/187264246-18f5faad-cace-46e2-b7ca-1a358a8eccdd.png)

**Comment by Uni-verse** [comment]
In Progress on Samsung Galaxy S21 & Samsung Galaxy Tab S7 using the following build(s):

Brave	1.45.106 Chromium: 107.0.5304.36 (Official Build) (64-bit) 
Revision	2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}
OS	Android 12; Build/SP1A.210812.016

**Comment by PrivacyMatters** [comment]
It is also showing on my Google Pixel Pro 7.  It is deeply problematic:

- it may be viewed as providing a privacy promise lacking substance
- users may access 'dangerous' sites without appropriate warnings in contradiction of what we have advised them

Version 1.44.114 Chromium 106.0.5249.126

Android 13



![Screenshot_20221024-160152](https://user-images.githubusercontent.com/41578351/197724437-dfaf88f9-2f8a-45ff-945e-febb7a299050.png)
![Screenshot_20221024-160200](https://user-images.githubusercontent.com/41578351/197724451-e057c873-c43c-4530-9783-c4bb7db1ba02.png)
