### ISSUE TITLE
Update New Tab Page Images and refine design

### ISSUE THREAD

**Issue by rossmoody** [brave/brave-browser#2504]
Need to update the background images from Muon since we are now on Core. New tab page also needs some light polish surrounding icon style parity, typography standards and responsive formatting.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.60.29 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Linux

* Verified all points from https://github.com/brave/brave-core/pull/1091
* Encountered #3380 while verifying the issue
