### ISSUE TITLE
Onboarding: show import from legacy checkbox when 24 words are pasted

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#25045]
## Description 

A checkbox should be shown on the "Import from seed phrase" Brave Wallet onboarding page. This will match the current iOS implementation. This will also ensure that the wallet is imported correctly.

## Steps to Reproduce

   1. Start Wallet onboarding
   2. Select import
   3. Select import from seed phrase
   4. Enter a 24 recovery phrase

## Actual result:

A "Import from legacy Brave crypto wallets" checkbox should be shown

## Expected result:
No checkbox is shown, causing import errors

## Reproduces how often: 

Easy

## Brave version (brave://version info)

1.45.5 Chromium: 105.0.5195.52 (Official Build) nightly (arm64)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.44.86 Chromium: 105.0.5195.127 (Official Build) beta (64-bit) 
-- | --
Revision | `912488396852bf658ab32465980c0b93a3c27a83-refs/branch-heads/5195@{#1109}`
OS | Linux

- Verified steps from [brave/brave-core#14897](https://github.com/brave/brave-core/pull/14897)
- Verified when 24-word seed is used, shows message to import from legacy wallet 
- Verified when an extra word is added to 24-word seed phrase shows the error message
- Verified able to import wallet from 24 word seed 
![image](https://user-images.githubusercontent.com/17010094/190649884-7bc636e3-aad2-4f04-84aa-fcdc1e05fb4d.png)


------------------------
Verification passed on

Brave | 1.44.86 Chromium: 105.0.5195.127 (Official Build) beta (64-bit) 
-- | --
Revision | `912488396852bf658ab32465980c0b93a3c27a83-refs/branch-heads/5195@{#1109}`
OS | Windows 11 Version 21H2 (Build 22000.795)

- Verified steps from [brave/brave-core#14897](https://github.com/brave/brave-core/pull/14897)
- Verified when 24-word seed is used, shows message to import from legacy wallet 
- Verified when an extra word is added to 24-word seed phrase shows the error message
- Verified able to import wallet from 24 word seed 
![image](https://user-images.githubusercontent.com/17010094/190650077-81e6a7ad-0cbc-470a-b7f7-3a64101383ea.png)


------------------------
Verification passed on

Brave | 1.44.86 Chromium: 105.0.5195.127 (Official Build) beta (arm64)
-- | --
Revision | `912488396852bf658ab32465980c0b93a3c27a83-refs/branch-heads/5195@{#1109}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [brave/brave-core#14897](https://github.com/brave/brave-core/pull/14897)
- Verified when 24-word seed is used, shows message to import from legacy wallet 
- Verified when an extra word is added to 24-word seed phrase shows the error message
- Verified able to import wallet from 24 word seed 
![image](https://user-images.githubusercontent.com/17010094/190650204-56d38b84-b2a7-41db-8dfb-7037e1239d31.png)
