### ISSUE TITLE
Onboarding v2 create password continue button is enabled for invalid seed words length

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#25044]
## Description 

Continue button doesn’t work when an invalid number of words are set. It also allows you to continue with weird amount of seed words that are non standard or maybe because of non-real words specified to restore.

## Steps to Reproduce

   1. Start Wallet onboarding
   2. Select import
   3. Select import from seed phrase
   4. Enter an invalid amount of words (not 12 or 24)
   5. Continue to password creation
   6. Create a valid password

## Actual result:

Continue button is enabled

## Expected result:
User should not have been able to navigate to the create password screen if an invalid recovery phrase length was entered.

## Reproduces how often: 

Easy

## Brave version (brave://version info)

1.45.5 Chromium: 105.0.5195.52 (Official Build) nightly (arm64) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

**Comment by kjozwiak** [comment]
The above requires `1.44.77` or higher for `1.44.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.44.86 Chromium: 105.0.5195.127 (Official Build) beta (64-bit) 
-- | --
Revision | `912488396852bf658ab32465980c0b93a3c27a83-refs/branch-heads/5195@{#1109}`
OS | Linux

- Verified steps from [brave/brave-core#14897](https://github.com/brave/brave-core/pull/14897)
- Verified import seed phrase works for valid amount of words only
- Verified importer shows error about invalid seed words if the seed word count is incorrect
- Verified error message is automatically removed when the correct amount of words are entered (valid/invalid)
- Verified when 24-word seed is used, shows message to import from legacy wallet 
- Verified when an extra word is added to 24-word seed phrase shows the error message
- Verified able to import wallet from 24 word seed 

------------------------
Verification passed on

Brave | 1.44.86 Chromium: 105.0.5195.127 (Official Build) beta (64-bit) 
-- | --
Revision | `912488396852bf658ab32465980c0b93a3c27a83-refs/branch-heads/5195@{#1109}`
OS | Windows 11 Version 21H2 (Build 22000.795)

- Verified steps from [brave/brave-core#14897](https://github.com/brave/brave-core/pull/14897)
- Verified import seed phrase works for valid amount of words only
- Verified importer shows error about invalid seed words if the seed word count is incorrect
- Verified error message is automatically removed when the correct amount of words are entered (valid/invalid)
- Verified when 24-word seed is used, shows message to import from legacy wallet 
- Verified when an extra word is added to 24-word seed phrase shows the error message
- Verified able to import wallet from 24 word seed 

------------------------
Verification passed on

Brave | 1.44.86 Chromium: 105.0.5195.127 (Official Build) beta (arm64)
-- | --
Revision | `912488396852bf658ab32465980c0b93a3c27a83-refs/branch-heads/5195@{#1109}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [brave/brave-core#14897](https://github.com/brave/brave-core/pull/14897)
- Verified import seed phrase works for valid amount of words only
- Verified importer shows error about invalid seed words if the seed word count is incorrect
- Verified error message is automatically removed when the correct amount of words are entered (valid/invalid)
- Verified when 24-word seed is used, shows message to import from legacy wallet 
- Verified when an extra word is added to 24-word seed phrase shows the error message
- Verified able to import wallet from 24 word seed
