### ISSUE TITLE
[Android 13] Notifications - permission request during opt-in of rewards or privacy report

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#25041]
### Problem
Android 13 has introduced a notifications permission request modal similar to iOS. Currently this modal appears randomly during the onboarding flow. Example video:

https://user-images.githubusercontent.com/28269287/187249033-f8f5f20f-560c-40d4-81e5-57df8f49b5e5.mov

We are worried this will:

1. Interfere with the user onboarding.
2. Result in low conversion. Because there is no context re: why the user should enable notifications.

### Solution
Android 13 has introduced the option to trigger a permissions prompt from a user action. We should do this for the notifications permission when a user opts in to rewards or the privacy report.

https://developer.android.com/develop/ui/views/notifications/notification-permission#wait-to-show-prompt

### Requirements

1. For Android 6-12 keep the notification permission on by default (existing behavior).

2. For Android 13 we should request the permission when a user opts into rewards or privacy reports. At this point we need to convey to the user **WHY** we are about to show them the notification permission modal. 

e.g. we will be unable to show private ads / you will not get rewarded without the notification permission. 
e.g. we will be unable to send the weekly privacy report without the notification permission.

| Rewards Opt In | Privacy Report Opt In |
| ------------- | ------------- |
| ![Image](https://user-images.githubusercontent.com/28269287/187250575-145472a9-56ad-42d4-b59d-889806976eee.png) | ![Image](https://user-images.githubusercontent.com/28269287/187250666-bcb6ba93-be2a-4efa-b633-0fd2a230ea10.png) |

### Designs

Figma: https://www.figma.com/file/sdVBBufbl2A11hAgPNfyqG/Android-13-Notifications

**Comment by kjozwiak** [comment]
The above will be verified via https://github.com/brave/brave-browser/issues/25042 👍
