### ISSUE TITLE
Ethereum site settings permission replaces Ask with Block

### ISSUE THREAD

**Issue by kdenhartog** [brave/brave-browser#25057]
When accessing the site settings of a particular site to take a look at the permissions (accessed via lock in omnibox ->  site settings) the permissions has the incorrect permissions. Rather than setting default to Block the text default should be Ask.

This is what the ethereum permissions drop down looks like:
![Screen Shot 2022-08-30 at 11 10 13 AM](https://user-images.githubusercontent.com/23125059/187314412-aaba5f2f-a050-4e88-975c-ad8d1bfaf654.png)

---
However this is what the Solana permissions dropdown looks like:
![Screen Shot 2022-08-30 at 11 11 38 AM](https://user-images.githubusercontent.com/23125059/187314467-75954805-616b-47f7-a788-8f5c3de299b1.png)

**Comment by darkdh** [comment]
Please check your global ethereum setting (brave://settings/content/ethereum) and if it is blocked, then per site setting would be blocked by default.
This is how content setting works not a bug.

**Comment by kdenhartog** [comment]
Thanks that was the issue. I had defaulted that to off globally when I was playing around with what this is guarding and didn't realized it would change this text here. I assumed this was statically set text.
