### ISSUE TITLE
Feature request: Please, make a short to focus on web-page (the opposite of Control-l: focus on address)

### ISSUE THREAD

**Issue by pdelfino** [brave/brave-browser#25052]
Please, see this question on [Super User](https://superuser.com/questions/1739506/on-brave-browser-running-macos-what-is-the-shortcut-to-focus-on-web-page-the-o) (from Stack Exchange). Also, see the reply.

I believe this should be a feature on Brave browser!

**Comment by fallaciousreasoning** [comment]
FWIW, there's already a shortcut for doing this, but it's not super intuitive: <kbd>Ctrl</kbd>+<kbd>F6</kbd> should do what you want.

I'm working on some stuff to make this more discoverable/configurable but for now, that's probably your best bet. If you're interested in progress on this issue, it's probably worth subscribing to #354 (for configuring shortcuts) or #28329 (for viewing available commands)
