### ISSUE TITLE
Download playlist media from background web contents

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#25062]
When background web contents is used for downloading media, ads video is downloaded instead of actual contents.
cc @sangwoo108

**Comment by simonhong** [comment]
Tried to check whether shields rule is used or not when youtube url is loaded in background web contents at `BraveRequestInfo::MakeCTX()` and it seems same rule is applied. Curious why background web contents still gives ads video?..

**Comment by simonhong** [comment]
@Brandon-T 
On desktop, sometimes ads video is downloaded instead of actual contents.
I'm not sure but I assume adblock enabled state could cause this.
AFAIK, desktop uses same script for getting media file list.
Curious iOS experienced similar issue?

**Comment by Brandon-T** [comment]
> @Brandon-T 
> 
> On desktop, sometimes ads video is downloaded instead of actual contents.
> 
> I'm not sure but I assume adblock enabled state could cause this.
> 
> AFAIK, desktop uses same script for getting media file list.
> 
> Curious iOS experienced similar issue?

iOS had the same issue. So we use the adblock shields in the invisible web view. It doesn't happen to use on sites where the user is actively viewing the page.
The ads issue only ever happened on the invisible web view so we inject our Adblock shields in there.

**Comment by simonhong** [comment]
> > @Brandon-T
> > On desktop, sometimes ads video is downloaded instead of actual contents.
> > I'm not sure but I assume adblock enabled state could cause this.
> > AFAIK, desktop uses same script for getting media file list.
> > Curious iOS experienced similar issue?
> 
> iOS had the same issue. So we use the adblock shields in the invisible web view. It doesn't happen to use on sites where the user is actively viewing the page. The ads issue only ever happened on the invisible web view so we inject our Adblock shields in there.

If user disabled shields for youtube and current tab is youtube for example, iOS could download ads also?

**Comment by Brandon-T** [comment]
> > > @Brandon-T
> 
> > > On desktop, sometimes ads video is downloaded instead of actual contents.
> 
> > > I'm not sure but I assume adblock enabled state could cause this.
> 
> > > AFAIK, desktop uses same script for getting media file list.
> 
> > > Curious iOS experienced similar issue?
> 
> > 
> 
> > iOS had the same issue. So we use the adblock shields in the invisible web view. It doesn't happen to use on sites where the user is actively viewing the page. The ads issue only ever happened on the invisible web view so we inject our Adblock shields in there.
> 
> 
> 
> If user disabled shields for youtube and current tab is youtube for example, iOS could download ads also?

In the invisible web view we always load the adblock when downloading.
For the videos on the page where there the user disabled Adblock, it will download an ad yeah.

In this case it's up to the user to only add to playlist the actual video.

**Comment by simonhong** [comment]
> > > > @Brandon-T
> > 
> > 
> > > > On desktop, sometimes ads video is downloaded instead of actual contents.
> > 
> > 
> > > > I'm not sure but I assume adblock enabled state could cause this.
> > 
> > 
> > > > AFAIK, desktop uses same script for getting media file list.
> > 
> > 
> > > > Curious iOS experienced similar issue?
> > 
> > 
> > > 
> > 
> > 
> > > iOS had the same issue. So we use the adblock shields in the invisible web view. It doesn't happen to use on sites where the user is actively viewing the page. The ads issue only ever happened on the invisible web view so we inject our Adblock shields in there.
> > 
> > 
> > If user disabled shields for youtube and current tab is youtube for example, iOS could download ads also?
> 
> In the invisible web view we always load the adblock when downloading. For the videos on the page where there the user disabled Adblock, it will download an ad yeah.
> 
> In this case it's up to the user to only add to playlist the actual video.

Got it, thanks for the answer! 👍🏼

**Comment by sangwoo108** [comment]
https://github.com/brave/brave-browser/issues/25130

Reportedly, Hiding Media source API on desktop seems to make Youtube streaming unplayable. We may need to download media files on background every time.

**Comment by simonhong** [comment]
Closed as https://github.com/brave/brave-browser/issues/25366 fixed also.
