### ISSUE TITLE
[Android] Suppress Mobile “Switch to App” Annoyances

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#25079]
### Spec
https://bravesoftware.slack.com/archives/C03MMJ4CHEZ/p1661878378715489?thread_ts=1661878373.627779&cid=C03MMJ4CHEZ

1. Apply and enable the "Fanboy's Mobile Notification List" suppression filter lists by default.

2. Add a toggle to enable/disable. Under settings -> brave shields & privacy -> other privacy settings.

Copy: _Block 'Switch to App' Notices_

**Comment by iccub** [comment]
It's this list only

<img width="335" alt="Zrzut ekranu 2022-10-7 o 21 16 10" src="https://user-images.githubusercontent.com/6950387/194637580-64672012-a3c1-4c22-94f5-499fddc3838c.png">

**Comment by deeppandya** [comment]
Thank you @iccub @timchilds . I will triage ut

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Vivo X70 Pro version 12` running `Bravemonoarmx64.apk_1.50.113'
