### ISSUE TITLE
window.ethereum.send should be writable

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#25078]
https://www.mycryptoheroes.net/ and  https://wallet.polygon.technology/
would do `window.ethereum.send = window.ethereum.sendAsync`.
We should make that function to be an exception of the property protection

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.43.85 Chromium: 105.0.5195.68 (Official Build) (64-bit)
-- | --
Revision | `ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}`
OS | Linux

- Verified test plan from [brave/brave-core#14895](https://github.com/brave/brave-core/pull/14895)
- Verified no error when loading the site or when connecting wallet to the dapps

https://user-images.githubusercontent.com/17010094/187672904-e77f629c-68fb-42ac-a288-d7d7093ca9d2.mp4


--------------

Verification passed on
Brave | 1.43.85 Chromium: 105.0.5195.68 (Official Build) (64-bit)
-- | --
Revision | `ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}`
OS | Windows 11 Version 21H2 (Build 22000.795)

- Verified test plan from [brave/brave-core#14895](https://github.com/brave/brave-core/pull/14895)
- Verified no error when loading the site or when connecting wallet to the dapps

https://user-images.githubusercontent.com/17010094/187672645-ac6c6de1-8125-4695-b672-fc444417c1d4.mp4


-------------------------
Verification passed on
Brave | 1.43.85 Chromium: 105.0.5195.68 (Official Build) (arm64)
-- | --
Revision | `ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}`
OS | macOS Version 12.5.1 (Build 21G83)

- Verified test plan from [brave/brave-core#14895](https://github.com/brave/brave-core/pull/14895)
- Verified no error when loading the site or when connecting wallet to the dapps

https://user-images.githubusercontent.com/17010094/187673269-501a070b-3a9a-47a3-a16d-05521f27253c.mov
