### ISSUE TITLE
Tab title for `brave://welcome` reads `Chromium`  instead of  `Brave` in Hindi

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#25082]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/25050
Tab title for `Welcome to Brave` reads as `chromium` instead of `Brave` in Hindi

## Steps to Reproduce

   1. Install 1.43.84
   2. Set OS locales to Hindi
   3. Launch Brave
   4. Notice the tab title for brave://welcome

## Actual result:

Tab title for brave://welcome reads `Chromium` in Hindi
![image](https://user-images.githubusercontent.com/98358127/187513573-f2496bb5-d578-43a2-b767-769d35b4eb3e.png)

## Expected result:
Should read `Brave`

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.43.84 Chromium: 105.0.5195.68 (Official Build) (64-bit)
-- | --
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | Windows 11 Version 21H2 (Build 22000.856)
```
## Version/Channel Information:

- Can you reproduce this issue with the current release?  Yes
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@rebron @brave/qa-team

**Comment by kjozwiak** [comment]
The above requires `1.43.91` or higher for `1.43.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `in progress` 
```
Brave | 1.43.91 Chromium: 105.0.5195.102 (आधिकारिक बिल्ड) (64-बिट)
-- | --
पुनरीक्षण | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | Windows 11 Version 21H2 (Build 22000.856)
```

![image](https://user-images.githubusercontent.com/98358127/189189594-f536246e-525d-4a48-9f91-c10e7e49d792.png)
![image](https://user-images.githubusercontent.com/98358127/189189619-0c457d93-8060-4c80-a8ab-08fd332616bc.png)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED using
```
Brave | 1.43.91 Chromium: 105.0.5195.102 (Official Build) (64-bit)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | Windows 11 Version 21H2 (Build 22000.856)
```
Verified using original STR from https://github.com/brave/brave-browser/issues/25082#issue-1356141674

### Confirmed correct tab title (Brave) shown in Hindi

Ex1|Ex2
---|---
<image width ="950" alt="image" src="https://user-images.githubusercontent.com/98358127/189189594-f536246e-525d-4a48-9f91-c10e7e49d792.png">|<image width ="950" alt="image" src="https://user-images.githubusercontent.com/98358127/189190798-8d8e5768-699d-44cb-95f2-555fbbda4707.png">
