### ISSUE TITLE
Spain and Mexico aren't getting the new-tab page Brave Search promos

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#25087]
## Description 

Spain and Mexico aren't getting the new-tab page Brave Search promos

## Steps to Reproduce

Prerequisite: set your OS language/locale to Spanish/Spain, or Spanish/Mexico

1. install `1.43.84`
2. launch Brave using `--enable-features=BraveSearchNTP`
3. open `brave://settings/search`
4. change `Brave` in `Ventana normal` section to be `Qwant` or anything other than `Brave`
5. open a new-tab page (ensure it doesn't have a Sponsored-Image ad)
6. look at the page

## Actual result:

No Spanish Brave Search promo appears

`search settings` | `new-tab page`
------------------|----------------
<img width="1312" alt="Captura de pantalla 2022-08-30 a las 12 36 09" src="https://user-images.githubusercontent.com/387249/187527735-0d7c2d69-b4ee-4a14-944e-30342f535d9a.png"> | <img width="1287" alt="Captura de Pantalla 2022-08-30 a la(s) 12 10 05" src="https://user-images.githubusercontent.com/387249/187523968-7a53058b-833f-4de8-987e-8b576cbfdc32.png">

## Expected result:

Spanish new-tab page promo for Brave Search should appear (like this one, for Germany/German).

<img width="1312" alt="Bildschirmfoto 2022-08-30 um 12 24 39" src="https://user-images.githubusercontent.com/387249/187525636-39cece67-e499-46b6-a53d-3c7b1b2ddca8.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.43.84 Chromium: 105.0.5195.68 (Build oficial) (x86_64)
-- | --
Revisión | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
SO | macOS Versión 11.6.8 (Fase 20G730)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `No`
- Can you reproduce this issue with the nightly channel? `Yes`

cc @simonhong @bsclifton @rebron @brave/qa-team

**Comment by MadhaviSeelam** [comment]
Able to reproduce above issue for `Spanish/Mexico` only in Win 11 x64. 
Works as expected for Spanish/Spain locale. 

<img width="919" alt="Screenshot 2022-08-30 144348, spain" src="https://user-images.githubusercontent.com/98358127/187551999-a369c5a6-8f36-4e2c-88b8-e5d8bb403762.png">

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.45.16 Chromium: 105.0.5195.68 (Build oficial) nightly (x86_64)
-- | --
Revisión | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
SO | macOS Versión 13.0 (Fase 22A5331f)

### Followed my original steps to reproduce, and confirmed I got Spanish-translated search promotions in both `es-MX` (Mexico) and `es-ES` (Spain) locales.

### `Mexico`

`macOS language + region` | `NTP promo`
-----------------------------|------------
<img width="947" alt="Captura de pantalla 2022-08-31 a la(s) 16 26 24" src="https://user-images.githubusercontent.com/387249/187803146-584d676b-2ac8-4d66-b8ba-78f98403f62d.png"> | <img width="1312" alt="Captura de pantalla 2022-08-31 a las 16 21 57" src="https://user-images.githubusercontent.com/387249/187803216-a9294a71-bf55-417a-8f2b-c8659564c398.png">



### `Spain`

`macOS language + region` | `NTP promo`
-----------------------------|------------
<img width="958" alt="Captura de pantalla 2022-08-31 a las 16 22 10" src="https://user-images.githubusercontent.com/387249/187802940-692db633-c31d-4366-abd6-18c26cc637c2.png"> | <img width="1503" alt="Captura de pantalla 2022-08-31 a la(s) 16 28 29" src="https://user-images.githubusercontent.com/387249/187802989-77d503fd-2a16-4cff-aeb3-f7797909dba1.png">

**Comment by kjozwiak** [comment]
Removing `QA Pass-macOS` so we can recheck the above via `1.43.x`. Used the https://github.com/brave/brave-browser/issues/25087#issuecomment-1233556198 verification to get both https://github.com/brave/brave-core/pull/14934 & https://github.com/brave/brave-core/pull/14935 uplifted.

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```
Brave	1.43.88 Chromium: 105.0.5195.68 (Build oficial) (64 bits) 
Revisión	ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
SO	Windows 10 Version 21H2 (Build 19044.1826)
```
