### ISSUE TITLE
[Android] Update verified creator criteria

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#25086]
## Description

https://github.com/brave/internal/issues/898

**Comment by deeppandya** [comment]
I have verified below steps with latest nightly version of the application (1.46.12), 

1. Enable Rewards
2. Visit a publisher that is "connected, but not verified" (e.g. duckduckgo.com on staging)
3. Verify that publisher appears "not verified":

-   There is no blue checkmark on the Rewards icon
-   In the Rewards panel, the status is displayed as "Unverified Creator"
-   In the tipping banner, the "creator is not signed up yet" message is displayed

4. Send a tip using vBAT.
5. Verify that a pending tip has been created.

**Comment by deeppandya** [comment]
Closing this issue as https://github.com/brave/brave-core/pull/15167 would be for both desktop and android
