### ISSUE TITLE
Update verified creator criteria

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#25085]
## Description

https://github.com/brave/internal/issues/898

**Comment by Miyayes** [comment]
Split it into small issue and then medium sized issue (where we remove dead branches)

**Comment by deeppandya** [comment]
Added android label as per the discussion

**Comment by kjozwiak** [comment]
The above requires `1.45.87` or higher for `1.45.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```

Brave | 1.45.87 Chromium: 106.0.5249.91 (Official Build) beta (64-bit)
-- | --
Revision | fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}
OS | Windows 10 Version 21H2 (Build 19044.2006)

```

**Comment by LaurenWags** [comment]
Verification in progress on Google Pixel 3 XL with Android 12 running 1.45.100
