### ISSUE TITLE
crash when selecting Guest window

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#25084]
## Description 

Crash with:

Brave | 1.45.5 Chromium: 105.0.5195.52 (Official Build) nightly (arm64)
-- | --
Revision | 412c95e518836d8a7d97250d62b29c2ae6a26a85-refs/branch-heads/5195@{#853}
OS | macOS Version 13.0 (Build 22A5331f)
JavaScript | V8 10.5.218.7
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36

when selecting Guest window from the app menu.

Crash ID: 8f420800-e66e-bc08-0000-000000000000

## Reproduces how often: 

Easily

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the nightly channel? no

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by mkarolin** [comment]
Doesn't repro on Windows.

**Comment by btlechowski** [comment]
Does not reproduce on Linux

Brave | 1.45.9 Chromium: 105.0.5195.68 (Official Build) nightly (64-bit)
-- | --
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | Linux

![image](https://user-images.githubusercontent.com/34715963/187527773-a884c21e-92a6-4f6c-bf28-e9dfee8e6245.png)

**Comment by stephendonner** [comment]
Wasn't able to reproduce either, using 

Brave | 1.45.5 Chromium: 105.0.5195.52 (Official Build) nightly (arm64)
-- | --
Revision | 412c95e518836d8a7d97250d62b29c2ae6a26a85-refs/branch-heads/5195@{#853}
OS | macOS Version 11.6.8 (Build 20G730)

<img width="1312" alt="Captura de pantalla 2022-08-30 a las 12 41 33" src="https://user-images.githubusercontent.com/387249/187529446-df2e4a37-2ebc-4516-b19f-3c6767c24e68.png">

Perhaps something profile-specific?  Though I can't imagine what...

**Comment by kjozwiak** [comment]
@rebron was thinking it might be related to https://github.com/brave/brave-browser/issues/24953 but that should have been fixed in `1.45.5`. Can you reproduce if you update to https://github.com/brave/brave-browser/releases/tag/v1.45.11? The version you're using is ~5-6 days old so a lot could have been fixed between `1.45.5` and `1.45.11` 👍 

BTW, I can't reproduce it either via `Win 11 x64` running `1.45.9 Chromium: 105.0.5195.68`.

Doesn't seem like `8f420800-e66e-bc08-0000-000000000000` is symbolized via BackTrace either :(

**Comment by rebron** [comment]
Closing as stale and dupe of https://github.com/brave/brave-browser/issues/24953
