### ISSUE TITLE
Fix/update "select accounts(s)" title for Solana connection request

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#25098]
Currently desktop is showing only the selected account to connect so there will always be only one choice of account to connect to.

## Description 

Fix/update "select accounts(s)" title for Solana connection request. Update the typo in "select accounts(s)" to either "select account(s)" or "Verify the current account" etc.

## Actual result:

[Screencast from 31-08-22 04:58:37 PM IST.webm](https://user-images.githubusercontent.com/11755381/187669307-43d0992c-d7a9-4fc2-b289-b1c6e65752c9.webm)

**Comment by Douglashdaniel** [comment]
Closing as duplicate of https://github.com/brave/brave-browser/issues/23993
