### ISSUE TITLE
Update "region not supported" error modal text (Sept 2022)

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#25092]
## Change to:

**Error: Region currently not supported**

Your {custodianName} account can't be connected to your Brave Rewards profile at this time. Your {custodianName} account is registered in a country that's not currently supported for connecting to Brave Rewards. 

See the [current list of supported regions and learn more](https://support.brave.com/hc/en-us/articles/6539887971469) about connecting a custodial account to Brave Rewards.

**Comment by kjozwiak** [comment]
The above requires `1.44.85` or higher for `1.44.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```
Brave | 1.44.86 Chromium: 105.0.5195.127 (Official Build) beta (64-bit)
-- | --
Revision | 912488396852bf658ab32465980c0b93a3c27a83-refs/branch-heads/5195@{#1109}
OS | Windows 10 Version 21H2 (Build 19044.2006)

```

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on `Samsung Galaxy Tab A7 version 11` running `Bravemonoarmx64.apk_1.44.95`

- Verified the description from https://github.com/brave/brave-browser/issues/25092#issue-1356645372 
- Ensured that the new text message for unsupported regions is displayed for **Uphold** and **Gemini** custodians
- Confirmed that click on link `current list of supported regions and learn more` opens up the the brave support page https://support.brave.com/hc/en-us/articles/6539887971469  in a new tab
- Confirmed that click on `Close` button on the region not supported error modal popup dismiss/remove the modal from the rewards page


**Error message:**
```
Your {custodianName} account can't be connected to your Brave Rewards profile at this time. Your {custodianName} account is registered in a country that's not currently supported for connecting to Brave Rewards.
See the [current list of supported regions and learn more](https://support.brave.com/hc/en-us/articles/6539887971469) about connecting a custodial account to Brave Rewards
```

**_wide view_**

**_Uphold_** 
![Screenshot_20220922-091511_Brave](https://user-images.githubusercontent.com/38657976/191654419-c2d372c4-364a-478c-b53d-215d762b90b7.jpg)
