### ISSUE TITLE
Support new layout for bridges.torproject.org/bridges

### ISSUE THREAD

**Issue by boocmp** [brave/brave-browser#25095]
## Steps to Reproduce

   1.  Open Privacy&Security settings
   2.  Click Request a bridge

## Actual result:

Can't request captcha.

## Expected result:
Captcha should be shown.

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.44.78` or higher for `1.44.x` verification 👍

**Comment by stephendonner** [comment]
@brave/qa-team this is blocked on macOS, with a fix in-hand; I recommend we wait on Windows and Linux until https://github.com/brave/brave-browser/issues/25293 lands and is verified, before circling back to this (to save retesting across multiple platforms).

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.44.94 Chromium: 105.0.5195.136 (Official Build) dev (x86_64)
-- | --
Revision | 872774b783d0e674186a3adcd2f92e7aa22a219c-refs/branch-heads/5195_124@{#4}
OS | macOS Version 11.7 (Build 20G817)

### Steps:
1. installed `1.44.94`
2. launched Brave
3. opened `brave://settings/privacy`
4. clicked to set `Use Bridges` to `Enabled`
5. clicked on the `Request a new bridge from torproject.org` radio button
6. clicked on `Request a New Bridge...`
7. entered the CAPTCHA text
8. clicked `Submit`
9. confirmed the dialog dismissed
10. confirmed the bridges' `obfs4 xxx.xxx.xxx.xxx` configs appeared in the text area
11. clicked on `Apply changes`
12. clicked on the `"hamburger menu"` -> `New Private Window with Tor`
13. loaded `check.torproject.org`
14. additionally, invoked `New Tor connection for this site` and confirmed it reloaded with a new Tor IP address

#### Confirmed I was able to request and use a bridge from torproject.org

`brave://settings/privacy` | `check.torproject.org` | `check.torproject.org - new IP`
--------------------------|------------------------|-------------------------------
<img width="1312" alt="Screen Shot 2022-09-20 at 9 23 20 AM" src="https://user-images.githubusercontent.com/387249/191314476-c9707399-e74f-4aa8-bc7d-71ad277f0f4a.png"> | <img width="1233" alt="Screen Shot 2022-09-20 at 9 25 24 AM" src="https://user-images.githubusercontent.com/387249/191314481-d5411cbf-eaaa-48e0-9e01-09f7367bcc54.png"> | <img width="1233" alt="Screen Shot 2022-09-20 at 9 34 26 AM" src="https://user-images.githubusercontent.com/387249/191314783-3f003b3c-2f41-41b9-baca-daf37c3a61cf.png">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.44.93 Chromium: 105.0.5195.136 (Official Build) beta (64-bit)
-- | --
Revision | 872774b783d0e674186a3adcd2f92e7aa22a219c-refs/branch-heads/5195_124@{#4}
OS | Windows 11 Version 21H2 (Build 22000.978)
```

### Steps:
1. installed `1.44.94`
2. launched Brave
3. opened `brave://settings/privacy`
4. clicked to set `Use Bridges` to `Enabled`
5. clicked on the `Request a new bridge from torproject.org` radio button
6. clicked on `Request a New Bridge...`
7. entered the CAPTCHA text
8. clicked `Submit`
9. confirmed the dialog dismissed
10. confirmed the bridges' `obfs4 xxx.xxx.xxx.xxx` configs appeared in the text area
11. clicked on `Apply changes`
12. clicked on the `"hamburger menu"` -> `New Private Window with Tor`
13. loaded `check.torproject.org`
14. additionally, invoked `New Tor connection for this site` and confirmed it reloaded with a new Tor IP address
15. do a hard refresh (Ctrl+shift+R) and confirmed it reloaded with a new Tor IP address

#### Confirmed  able to request and use a bridge from torproject.org

step 3-4|step 5|step7|step 10|step 12|step 13|step 14|step15
----|----|----|----|----|----|-----|----
<image width="1800" alt="step3" src="https://user-images.githubusercontent.com/98358127/191364366-ff9778c8-1f2d-496b-b4fc-915aa701f2cc.png">|<image width="1800" alt="step3" src="https://user-images.githubusercontent.com/98358127/191356305-6491c425-be90-42a7-b8d6-1785455d7e7a.png">|<image width="1600" alt="step3" src="https://user-images.githubusercontent.com/98358127/191356411-f9ddbb3a-2b0b-4cb3-a166-54c5151fed6a.png">|<image width="1600" alt="step3" src="https://user-images.githubusercontent.com/98358127/191356546-210ab8bf-d0b9-448b-bae4-f18c5ffa4a4d.png">|<image width="1600" alt="step3" src="https://user-images.githubusercontent.com/98358127/191356738-484f9930-397c-44b3-97e4-78352db0bd36.png">|<image width="1600" alt="step3" src="https://user-images.githubusercontent.com/98358127/191356998-be850038-3998-4a60-ba09-65aee5277021.png">|<image width="1600" alt="step3" src="https://user-images.githubusercontent.com/98358127/191357072-5ea60c5d-03b6-4db2-bc8a-3588c9b63c7f.png">|<image width="1400" alt="step3" src="https://user-images.githubusercontent.com/98358127/191357153-590b275e-48df-4348-b02d-48789b0b70f0.png">

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.44.95 Chromium: 106.0.5249.40 (Official Build) (64-bit) 
--|--
Revision | fab1d91915d2722d6339aaa7f4e9ce44f1e9b103-refs/branch-heads/5249@{#442}
OS | Linux

### Steps:

1. installed `1.44.95`
2. launched Brave
3. opened `brave://settings/privacy`
4. clicked to set `Use Bridges to Enabled`
5. clicked on the `Request a new bridge from torproject.org` radio button
6. clicked on `Request a New Bridge...`
7. entered the CAPTCHA text
8. clicked `Submit`
9. confirmed the dialog dismissed
10. confirmed the bridges' `obfs4 xxx.xxx.xxx.xxx` configs appeared in the text area
11. clicked on `Apply changes`
12. clicked on the "hamburger menu" -> New Private Window with Tor
13. loaded `check.torproject.org`
14. additionally, invoked `New Tor connection for this site` and confirmed it reloaded with a new Tor IP address

example | example | example | example | example | example | example | example
---------|----------|---------|----------|---------|----------|---------|---------
<img width="1618" alt="Screen Shot 2022-09-21 at 9 40 54 AM" src="https://user-images.githubusercontent.com/387249/191562608-21b38ef4-3ddd-408a-9125-f262043b2cb2.png"> | <img width="1618" alt="Screen Shot 2022-09-21 at 9 40 57 AM" src="https://user-images.githubusercontent.com/387249/191562612-249cc739-3d5f-4094-b0b7-86b3fc91b2c9.png"> | <img width="1618" alt="Screen Shot 2022-09-21 at 9 40 59 AM" src="https://user-images.githubusercontent.com/387249/191562619-5c732cd7-ea77-4c81-8f29-4e831fc635c7.png"> | <img width="1618" alt="Screen Shot 2022-09-21 at 9 30 50 AM" src="https://user-images.githubusercontent.com/387249/191561152-1b75d7e4-5e76-4c47-8433-1c8a7cf96629.png"> | <img width="1618" alt="Screen Shot 2022-09-21 at 9 31 02 AM" src="https://user-images.githubusercontent.com/387249/191561177-0fd86d0a-1235-43bd-bf43-df571790f8e1.png"> | <img width="1618" alt="Screen Shot 2022-09-21 at 9 31 07 AM" src="https://user-images.githubusercontent.com/387249/191561188-e0b9bf10-6f19-4928-bf7e-38415bac00b4.png"> | <img width="1618" alt="Screen Shot 2022-09-21 at 9 32 41 AM" src="https://user-images.githubusercontent.com/387249/191561200-93cde299-0ec2-4725-bfd4-64e8faf07665.png"> | <img width="1618" alt="Screen Shot 2022-09-21 at 9 33 32 AM" src="https://user-images.githubusercontent.com/387249/191561208-f1d24fc9-7a21-490d-8acd-beb6ead579b0.png">
