### ISSUE TITLE
Deselecting account is automatically gets selected again

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#25101]
## Description 

Deselecting account is automatically gets selected again

## Actual result:

[Screencast from 31-08-22 07:20:56 PM IST.webm](https://user-images.githubusercontent.com/11755381/187695544-a71bdfdf-1f29-4ff7-a656-83272346b7cf.webm)

## Expected result:
Deselected account should remain deselected

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.45.104 Chromium: 106.0.5249.126 (Official Build) beta (64-bit) 
-- | --
Revision | `fb2e06d2dee20fe0c804528502b5ad72c613abd9-refs/branch-heads/5249_118@{#3}`
OS | Linux

- Verified steps from [brave/brave-core#14971](https://github.com/brave/brave-core/pull/14971)
- Verified deselecting an account doesn't automatically adds it back

https://user-images.githubusercontent.com/17010094/196436576-e8740462-22c0-497a-a28d-ee913d5b285d.mp4


------------------------
Verification passed on

Brave | 1.45.104 Chromium: 106.0.5249.126 (Official Build) beta (64-bit) 
-- | --
Revision | `fb2e06d2dee20fe0c804528502b5ad72c613abd9-refs/branch-heads/5249_118@{#3}`
OS | Windows 11 Version 22H2 (Build 22621.674)

- Verified steps from [brave/brave-core#14971](https://github.com/brave/brave-core/pull/14971)
- Verified deselecting an account doesn't automatically adds it back

https://user-images.githubusercontent.com/17010094/196436236-e3e24880-c671-4726-959f-9c0ba01e9c78.mp4


------------------------
Verification passed on

Brave | 1.45.104 Chromium: 106.0.5249.126 (Official Build) beta (arm64)
-- | --
Revision | `fb2e06d2dee20fe0c804528502b5ad72c613abd9-refs/branch-heads/5249_118@{#3}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [brave/brave-core#14971](https://github.com/brave/brave-core/pull/14971)
- Verified deselecting an account doesn't automatically adds it back

https://user-images.githubusercontent.com/17010094/196436760-aa997c42-7dec-4580-9d39-089a07b1e140.mov
