### ISSUE TITLE
Show full network name in Buy-Send-Swap widget tab button tooltips (BRA-Q322-3. Misleading Blockchain Names)

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#25107]
## Description 

BRA-Q322-3. Misleading Blockchain Names

Before rendering a blockchain name, Brave Wallet uses the reduceNetworkDisplayName function to reduce the network name.
Such a design decision leads to ambiguity for users and possible unintended transactions. For example, executing transaction on the main network instead of using test network. Users must hover over the blockchain name to be sure on which network they will be executing transactions.

## Steps to Reproduce

   1. Enable displaying test networks from Wallet setting
   2. Unlock the desktop version of the Brave Wallet
   3. Select Solana Testnet
   4. Hover the mouse over the "Buy" or "Swap" tab of the Buy/Send/Swap widget
   5. A Tooltip should appear explaining that the network is not supported for that feature
   6. Notice that the selected network name is not fully displayed

## Actual result:

Network name reads "Solana"

## Expected result:
Network name reads "Solana Testnet"

## Reproduces how often: 

Easy

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (64-bit) 
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | Linux

- Verified steps from [brave/brave-core#14927](https://github.com/brave/brave-core/pull/14927)
- Verified full network name is shown on Buy/Send/Swap widget and on panel 
- Added follow up issue [#26066](https://github.com/brave/brave-browser/issues/26066)

https://user-images.githubusercontent.com/17010094/196145151-86d0d9ef-3e16-4ef0-957d-f977c04e1f5d.mp4


------------------------
Verification passed on

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (64-bit) 
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | Windows 11 Version 21H2 (Build 22000.978)

- Verified steps from [brave/brave-core#14927](https://github.com/brave/brave-core/pull/14927)
- Verified full network name is shown on Buy/Send/Swap widget and on panel 
- Added follow up issue [#26066](https://github.com/brave/brave-browser/issues/26066)

https://user-images.githubusercontent.com/17010094/196144713-013592a9-a143-4493-bb84-937f4b228e62.mp4


------------------------
Verification passed on

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (arm64)
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [brave/brave-core#14927](https://github.com/brave/brave-core/pull/14927)
- Verified full network name is shown on Buy/Send/Swap widget and on panel 
- Added follow up issue [#26066](https://github.com/brave/brave-browser/issues/26066)

https://user-images.githubusercontent.com/17010094/196145408-55390627-d9cd-47ed-a05c-57485e5effc1.mov
