### ISSUE TITLE
Brave Ads crashes on Linux when viewing a notification

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#2510]
## Description 
Brave Ads crashes on Linux when viewing a notification

## Steps to Reproduce

   1. Enable Brave Ads
   2. Visit a website
   3. Do not use the computer for 15 seconds so it becomes idle (best to wait 30 seconds to be sure)
   4. Use the computer so it becomes unidle
   5. Wait for a notification to appear
   6. View the notification

## Actual result:
Brave Ads crashes

## Expected result:
Brave Ads should not crash

## Reproduces how often: 
Everytime

## Brave version (brave://version info)
Linux 0.59.6

### Reproducible on current release:
beta build

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by bridiver** [comment]
If the notification appears but I don't view it, does it still crash? ;)

**Comment by bridiver** [comment]
@tmancey do you mean a debug build or ads debug mode? Can you specify what flags you are running with?

**Comment by tmancey** [comment]
> @tmancey do you mean a debug build or ads debug mode? Can you specify what flags you are running with?

Updated ticket title to reflect actual crash

**Comment by tmancey** [comment]
Won't fix as no longer an issue now that ads is fully integrated
