### ISSUE TITLE
Show full network name in transaction confirmation panel (BRA-Q322-3. Misleading Blockchain Names)

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#25105]
## Description 

BRA-Q322-3. Misleading Blockchain Names

Before rendering a blockchain name, Brave Wallet uses the reduceNetworkDisplayName function to reduce the network name.
Such a design decision leads to ambiguity for users and possible unintended transactions. For example, executing transaction on the main network instead of using test network. Users must hover over the blockchain name to be sure on which network they will be executing transactions.

## Steps to Reproduce

   1. Enable displaying test networks from Wallet setting
   2. Unlock the desktop version of the Brave Wallet
   3. Select Ropsten Testnet
   4. Send ETH from one account to another
   5. Notice that the network name is not fully displayed

## Actual result:

<img width="317" alt="Screen Shot 2022-08-31 at 11 30 42 AM" src="https://user-images.githubusercontent.com/30185185/187742338-67506dbf-9c62-4130-8b09-75422338e2e4.png">

## Expected result:
<img width="315" alt="Screen Shot 2022-08-31 at 11 33 25 AM" src="https://user-images.githubusercontent.com/30185185/187742735-713d5f9a-da13-4133-a209-f7d75ca4ec37.png">

## Reproduces how often: 

Easy

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/25114#issuecomment-1278887474
