### ISSUE TITLE
`Install and start` button shouldn't be available on `brave://ipfs-internals` for Android

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#25103]
## Description 

`Install and start` button shouldn't be available on `brave://ipfs-internals` for Android

## Steps to Reproduce

   1. install `1.43.86`
   2. launch Brave
   3. load `brave://ipfs-internals`
   4. click on `Install and start`
   5. wait

## Actual result:

Literally nothing happens (confirmed via `adb logcat`)

initial | `Installing IPFS...`
------|-------------------
![Screenshot_20220831-083217](https://user-images.githubusercontent.com/387249/187722611-8eeff670-364e-4907-9511-1dce342096e7.png) | ![Screenshot_20220831-083225](https://user-images.githubusercontent.com/387249/187722621-5acd9eba-3e96-4a9e-b499-682088881d6f.png)

## Expected result:

Since IPFS local-node support isn't on Android, we should remove this button.

(And whatever else is only appropriate for `public gateway` support.)

## Reproduces how often: 

100%

## Brave version (brave://version info)

`Brave 1.43.86, Chromium 105.0.5195.68` running on `Android 9` using a `Google Pixel XL`

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

cc @spylogsster @cypt4 @srirambv @kjozwiak @Uni-verse

**Comment by kjozwiak** [comment]
Moving this into the `1.52.x Nightly` which is currently `master` as it was fixed by https://github.com/brave/brave-core/pull/17999. It wasn't moved automatically due incorrectly formatting being used via https://github.com/brave/brave-core/pull/17999#issue-1663088076.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave	1.52.87 Chromium: 113.0.5672.77 (Official Build) beta (32-bit)
Revision	c4236862955e005c2187105415ac4a2ecf86dff1-refs/branch-heads/5672_62@{#3}
OS	Android 9; Build/PQ2A.190305.002; 28; REL
```

running on a `Google Pixel XL` (`arm64`), running `Android 9`.

### Confirmed `brave://ipfs-internals` and/or `chrome://ipfs-internals` no longer load(s)

example | example | example
---------|---------|---------
![Screenshot_20230505-140220](https://user-images.githubusercontent.com/387249/236568966-62bc9bea-4595-493c-947a-2f72ba3c99cc.png) | ![Screenshot_20230505-140213](https://user-images.githubusercontent.com/387249/236568984-3b95f309-7fea-4bac-b095-ff252bc7f696.png) | ![Screenshot_20230505-140227](https://user-images.githubusercontent.com/387249/236569012-c5e26530-ece8-45c8-ac06-d49181742ed1.png)
