### ISSUE TITLE
Support different derivation paths for Solana

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#25111]
Right now we only support `44'/501'/${index}/0'`, we need to support other options that Ledger Live and Phantom are using, so users can import their accounts from ledger live or phantom using these paths.
See https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1658160838560809 for more details.

Options on Phantom when importing hardware accounts from Ledger:
<img width="363" alt="Screen Shot 2022-08-31 at 12 15 29 PM" src="https://user-images.githubusercontent.com/4730197/187764102-b68a75a7-3454-4ec4-a889-644c5ca104c2.png">

Ledger Live: `44'/501'/{index}'`

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.46.87 Chromium: 107.0.5304.91 (Official Build) beta (64-bit)
-- | --
Revision | `3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}`
OS | Linux

- Verified steps from [brave/brave-core#15406](https://github.com/brave/brave-core/pull/15406)
- Verified able to import Solana accounts from both `Default` and `Ledger Live`

https://user-images.githubusercontent.com/17010094/199215750-b53904db-60d0-4f8f-aaa9-f1a8736287d4.mp4

------------------------
Verification passed on

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (64-bit) 
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | Windows 11 Version 22H2 (Build 22621.674)

- Verified steps from [brave/brave-core#15406](https://github.com/brave/brave-core/pull/15406)
- Verified able to import Solana accounts from both `Default` and `Ledger Live`

https://user-images.githubusercontent.com/17010094/199215680-1e17ba52-c651-443e-b44d-a2f4917f5346.mp4

------------------------
Verification passed on

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (arm64)
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#15406](https://github.com/brave/brave-core/pull/15406)
- Verified able to import Solana accounts from both `Default` and `Ledger Live`

https://user-images.githubusercontent.com/17010094/199216204-650ef886-fc74-4f62-9177-b9867440c5bf.mov
