### ISSUE TITLE
Disable `Add to Home screen` IPH

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#25118]
## Description 
Chromium's implementation is intrusive. We want to disable it for now and implement it the way we want it going forward.

## Steps to reproduce 

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung S10+` running `Android 12` using the following build(s):

```
Brave | 1.43.88 Chromium: 105.0.5195.68 (Official Build) (32-bit)
--- | ---
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | Android 12; Build/SP1A.210812.016
```

* verified the STR/Cases outlined via https://github.com/brave/brave-browser/issues/25118#issue-1358032544
* verified that you can still add websites to the home screen via `Add to Home screen`
* ensured that opening websites that were added via `Add to Home screen` work as expected
