### ISSUE TITLE
Show full network name in Network selector (BRA-Q322-3. Misleading Blockchain Names)

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#25114]
## Description 

BRA-Q322-3. Misleading Blockchain Names

Before rendering a blockchain name, Brave Wallet uses the reduceNetworkDisplayName function to reduce the network name.
Such a design decision leads to ambiguity for users and possible unintended transactions. For example, executing transaction on the main network instead of using test network. Users must hover over the blockchain name to be sure on which network they will be executing transactions.

## Steps to Reproduce

   1. Enable displaying test networks from Wallet setting
   2. Unlock the desktop version of the Brave Wallet
   3. Select Solana Testnet
   4. Notice that the selected network name is not fully displayed

## Actual result:

Network name reads "Solana"

## Expected result:
Network name reads "Solana Testnet"

## Reproduces how often: 

Easy

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (64-bit)
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | Linux

- Verified steps from [brave/brave-core#14979](https://github.com/brave/brave-core/pull/14979)
- Verified full network name is shown on both panel and widget
- Verified after connecting to Dapp network full name is shown
- Verified full network name is shown on the network dropdown list 

https://user-images.githubusercontent.com/17010094/195837118-7d2349ed-8fcd-4e47-be82-f63bad71a7dd.mp4

----------------
Verification passed on 

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (64-bit)
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | Windows 11 Version 21H2 (Build 22000.978)

- Verified steps from [brave/brave-core#14979](https://github.com/brave/brave-core/pull/14979)
- Verified full network name is shown on both panel and widget
- Verified after connecting to Dapp network full name is shown
- Verified full network name is shown on the network dropdown list 

https://user-images.githubusercontent.com/17010094/195836784-7313fcaf-4a5c-47a2-95bd-7b91d8e36660.mp4


----------------
Verification passed on 

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (arm64)
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | macOS Version 12.6 (Build 21G115)

- Verified steps from [brave/brave-core#14979](https://github.com/brave/brave-core/pull/14979)
- Verified full network name is shown on both panel and widget
- Verified after connecting to Dapp network full name is shown
- Verified full network name is shown on the network dropdown list 

https://user-images.githubusercontent.com/17010094/195837501-f812392b-fb7a-432b-ba14-8c2c8fa53f2c.mov
