### ISSUE TITLE
Remove speedreader updater component (enabling theme support)

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#25116]
The `Brave Speedreader Updater` component (`jicbkmdloagakknpihibphagfckhjdih`) only ships two data files in its CRX - `content-stylesheet.css` and `speedreader-updater.dat`.

The `.dat` file is completely unused, since Speedreader has been updated to no longer use the adblock list-based backend.

`content-stylesheet.css` is still used to override the style in `brave-core`, but it does so unconditionally even though there is already a speedreader stylesheet bundled inside `brave-core`. The stylesheet is now stable enough to not need to be updated dynamically, so it should be safe to remove this as well.

The stylesheet currently shipped by the component updater is fairly old and there is a PR (https://github.com/brave-experiments/SpeedReader/pull/36) to update it to match the current version in `brave-core`, enabling theme support. Merging this will make themes work without requiring the component at all.

Once this has enough roll-out, we should remove the speedreader component from `brave-core-crx-packager` as well.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.45.78 Chromium: 106.0.5249.65 (Official Build) beta (64-bit)
-- | --
Revision | 3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}
OS | Windows 11 Version 21H2 (Build 22000.978)
```

1. Install 1.45.78
2. launch Brave
3. verified `jicbkmdloagakknpihibphagfckhjdih` is no longer available in the component directory
4. opened `brave://settings/appearance` and selected `Light`
5. visited https://www.bbc.com/travel/article/20220928-mexicos-ancient-unknown-pyramids
6. clicked on the `Speedreader` icon
7. verified the `Light` theme was applied in Speedreader mode to the article
8. switch to `Dark` theme in  `brave://settings/appearance`
9. return to the article tab
10. verified the `Dark` theme was applied in Speedreader mode to the article
11. open `brave://components`

#### Confirmed `Brave SpeedReader Updater` component is no longer available

step 3|step 4|step7|step8|step10|step 11
----|----|-----|------|-----|------
<img width="220" alt="image" src="https://user-images.githubusercontent.com/98358127/193093222-8ad4a7b8-d5db-4b19-90a8-7a6279db8bc3.png">|<img width="465" alt="image" src="https://user-images.githubusercontent.com/98358127/193091257-ef63a16c-a1eb-4777-adcd-a2b00909ebdb.png">|<img width="462" alt="image" src="https://user-images.githubusercontent.com/98358127/193092312-a8e472fb-20de-4293-a3e8-9e7fb5b81adb.png">|<img width="465" alt="image" src="https://user-images.githubusercontent.com/98358127/193092477-14e80c00-7f15-4d39-9b66-300a9918a5e8.png">|<img width="452" alt="image" src="https://user-images.githubusercontent.com/98358127/193093903-66a5a42a-e588-4790-8b96-461c0bc2c812.png">|<img width="462" alt="image" src="https://user-images.githubusercontent.com/98358127/193092841-659e9760-f357-4716-adf8-d4f34e7a61ee.png">

**Comment by stephendonner** [comment]
## Verification `PASSED` using 


Brave | 1.46.29 Chromium: 106.0.5249.91 (Official Build) nightly (x86_64)
-- | --
Revision | fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}
OS | macOS Version 11.7 (Build 20G817)

### Steps:
1. installed `1.45.84`
2. launched Brave
3. verified `jicbkmdloagakknpihibphagfckhjdih` is no longer available in the component directory
4. opened `brave://settings/appearance` and selected `Light`
5. visited `https://www.bbc.com/travel/article/20220928-mexicos-ancient-unknown-pyramids`
6. clicked on the `Speedreader` icon
7. verified the `Light` theme was applied in Speedreader mode to the article
8. switch to `Dark` theme in  `brave://settings/appearance`
9. returned to the article tab
10. verified the `Dark` theme was applied in Speedreader mode to the article
11. opened `brave://components`

#### Confirmed `Brave SpeedReader Updater` component is no longer available

step 3|step 4|step 7|step 8|step 10|step 11
----|----|-----|------|-----|------
<img width="742" alt="Screen Shot 2022-10-03 at 11 30 34 PM" src="https://user-images.githubusercontent.com/387249/193728409-e0c8787d-2efe-4a22-ad82-9d7ef66cc8f7.png"> | <img width="1312" alt="Screen Shot 2022-10-03 at 11 31 27 PM" src="https://user-images.githubusercontent.com/387249/193728597-59d91ba8-9ca0-4eaf-9b7f-1c2d2bc96173.png"> | <img width="1312" alt="Screen Shot 2022-10-03 at 11 32 02 PM" src="https://user-images.githubusercontent.com/387249/193728600-6f9c2b5c-745e-4d30-8e06-5f1443a0488b.png"> | <img width="1312" alt="Screen Shot 2022-10-03 at 11 34 24 PM" src="https://user-images.githubusercontent.com/387249/193728789-7b4684ca-c72c-4552-bf75-f596a38115b7.png"> | <img width="1312" alt="Screen Shot 2022-10-03 at 11 32 30 PM" src="https://user-images.githubusercontent.com/387249/193728603-2cb1fead-7e69-45a8-aad2-fba76643e598.png"> | <img width="1312" alt="Screen Shot 2022-10-03 at 11 32 43 PM" src="https://user-images.githubusercontent.com/387249/193728606-89b74952-8af5-4cf2-abe3-ae7ab1e4ef78.png">

**Comment by LaurenWags** [comment]
Verified on Google Pixel 3 XL with Android 12 running 1.45.100.

Speedreader is not available on Android yet (https://github.com/brave/brave-browser/issues/22968) however, confirmed that chrome://components does not show Speedreader component:

![Screenshot_20221014-101623](https://user-images.githubusercontent.com/28145373/195869306-1c04e88e-5de3-4caa-8847-70ad34c3ea3b.png)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.45.90 Chromium: 106.0.5249.103 (Official Build) beta (64-bit)
-- | --
Revision | 182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}
OS | Ubuntu 18.04 LTS

### Steps:
1. installed `1.45.x`
2. launched Brave
3. verified `jicbkmdloagakknpihibphagfckhjdih` is no longer available in the component directory
4. opened `brave://settings/appearance` and selected `Light`
5. visited `https://www.bbc.com/travel/article/20220928-mexicos-ancient-unknown-pyramids`
6. clicked on the `Speedreader` icon
7. verified the `Light` theme was applied in Speedreader mode to the article
8. switch to `Dark` theme in  `brave://settings/appearance`
9. returned to the article tab
10. verified the `Dark` theme was applied in Speedreader mode to the article
11. opened `brave://components`

#### Confirmed `Brave SpeedReader Updater` component is no longer available

step 3|step 4|step 7|step 8|step 10|step 11
----|----|-----|------|-----|------
![image](https://user-images.githubusercontent.com/34715963/196279357-9ede62cc-7d39-44ec-9988-b6f95e9c318b.png)|![image](https://user-images.githubusercontent.com/34715963/196279529-4e5a1a89-755b-4e86-85aa-8588fbb92d5e.png)|![image](https://user-images.githubusercontent.com/34715963/196279743-3c4fca2c-5c45-4020-bfd5-3f2546a2c0e4.png)|![image](https://user-images.githubusercontent.com/34715963/196279679-d34568b0-4624-41cf-9560-af1e5f723b53.png)|![image](https://user-images.githubusercontent.com/34715963/196279818-85a75687-9dec-4a28-ad04-4125fbb1d120.png)|![image](https://user-images.githubusercontent.com/34715963/196280050-bc0b9c63-37fe-4df3-b726-6a66931cec38.png)
