### ISSUE TITLE
Foreground/Background notifications aren't implemented on Linux for Brave Ads

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#2511]
Foreground/Background notifications aren't implemented on Linux for Brave Ads

**Comment by bridiver** [comment]
@tmancey this needs steps for QA

**Comment by tmancey** [comment]
@bridiver This is just a reminder for us to implement background/foreground notifications for Ads in Linux. Once completed would this not be tested as part of overall Ads implementation?

**Comment by tmancey** [comment]
@bridiver This was already resolved in the brave core implementation. Ok with you if we close as tests are covered by spec?
