### ISSUE TITLE
issue rendering/displaying tabs which causes artifacts and other issues due to `VulkanStudy:Disabled`

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#25124]
## Description 

I'm noticing that my `Samsung S8 Ultra Tablet` is having issues loading tabs at the top. I'm seeing the following occurring:

* graphic artifacts
* blank tabs with no text
* entire row of tabs missing
* entire row of tabs appear is a dark/black line

They're usually corrected after the page loads or you tap on the tab but it's not a good experience. Switching between tabs is also causing tons of artifacts and strange behaviour. This isn't happening with `1.42.97 Chromium: 104.0.5112.102`.

However, I think this is due to `Vulkan`. Maybe something was changed on `C105` that's causing this particular tablet to run into rendering issues when `VulkanStudy:Disabled`.

Using `BETA` which has `C105` and also has ``VulkanStudy:Enabled` works fine without any issues and everything is rendering correctly.

## Steps to reproduce 

   1. install/launch and version of Brave that has `C105` (used https://github.com/brave/brave-browser/releases/tag/v1.43.87)
   2. open ~3-4 different tabs and re-launch the browser
   3. you'll notice there's issues loading the tabs
   4. once the browser is re-launched, attempt switching to other tabs
   5. tapping on the omnibox also causes the issue to happen

## Actual result 

![image](https://user-images.githubusercontent.com/2602313/187820099-e5909567-dcb5-4ba1-9c72-6afa12da17fc.png)
![image](https://user-images.githubusercontent.com/2602313/187820127-b4235623-231a-48c9-9fcc-5d9a703460f9.png)
![image](https://user-images.githubusercontent.com/2602313/187821205-8b0181bc-e194-4617-af15-c1e6f2240c1c.png)
![image](https://user-images.githubusercontent.com/2602313/187821226-f3052496-b8be-4835-b8ad-aed4d6c19319.png)

## Expected result

Tabs should be loading without any issues/rendering artifacts.

## Issue reproduces how often 

100% reproducible using the STR/Cases outlined above.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `Yes` (with the `1.43.x` RC where `Vulkan` is disabled)
- Can you reproduce this issue with the current Play Store Beta version? `No` 
- Can you reproduce this issue with the current Play Store Nightly version? `No`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Samsung Tab S8 Ultra`
   - Android version: `Android 12`
   
## Brave version

```
Brave | 1.43.87 Chromium: 105.0.5195.68 (Official Build) (32-bit)
--- | ---
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | Android 12; Build/SPSA.220305.013
```

### Website problems only

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `No`

**Comment by kjozwiak** [comment]
Enabling `Vulkan` via `brave://flags#enable-vulkan` fixes the issue 👍 The above will be resolved once we enable `Vulkan` via Griffin.

**Comment by cristianrgreco** [comment]
@kjozwiak I have the same issue and tried enabling Vulkan via the flags as you suggest. It fixes the strange artifacting but I've found the tabs still pulsate, with the text disappearing and reappearing rapidly, as if they're being re rendered every few ms.

**Comment by kjozwiak** [comment]
> @kjozwiak I have the same issue and tried enabling Vulkan via the flags as you suggest. It fixes the strange artifacting but I've found the tabs still pulsate, with the text disappearing and reappearing rapidly, as if they're being re rendered every few ms.

@cristianrgreco just curious, what tablet/device are you using? We're looking into the above and trying to figure out which devices are being affected. I'll create a follow up issue regarding the tabs still not loading correctly even though Vulkan has been enabled.

**Comment by cristianrgreco** [comment]
Thanks @kjozwiak, I'm using a Samsung galaxy fold 4

**Comment by dfontana92** [comment]
Same issue on Samsung Galaxy Tab S8 Plus.

**Comment by juguerin3** [comment]
Same issue with my Galaxy S8 Plus for about 2 weeks.

The issue look like solved by enabling Vulkan..

@kjozwiak Really thanks for this tip !

**Comment by Siriu5J** [comment]
Same issue with Samsung Galaxy S22. It might have to do with recent Samsung software upgrades.

**Comment by rathashit** [comment]
I'm also having the same issue.
Device - Samsung ZFlip 4
![image](https://user-images.githubusercontent.com/14171903/190839400-0ca155f2-415b-4e84-9091-844c03715aed.png)

**Comment by kjozwiak** [comment]
@Siriu5J @rathashit did enabling `brave://flags#enable-vulkan` help?

**Comment by rathashit** [comment]
@Siriu5J Yes, I don’t see the glitches anymore. For a moment I thought my new phone has panel issues 😅

**Comment by Siriu5J** [comment]
> @Siriu5J @rathashit did enabling `brave://flags#enable-vulkan` help?

Yes.

**Comment by psychic69** [comment]
This issue appeared on my Samsung s8+ tab ans S22 the second the oneui 4.1.1 patch was applied about two weeks ago.

**Comment by kjozwiak** [comment]
Just a heads up that we'll be enabling `Vulkan` on `50%` of our `release` population starting tomorrow via https://github.com/brave/brave-variations/pull/370. As per https://community.brave.com/t/z-fold-4-graphical-issues/429856/7?u=kamil, we had it enabled on `10%` to gauge if it caused any issues on older devices that might not support Vulkan.

**Comment by SergeyZhukovsky** [comment]
That is solved by that PR https://github.com/brave/brave-variations/pull/375
