### ISSUE TITLE
Implement "custodial connection unavailable" error modal 

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#25125]
## Description 

> **Error: Connecting to selected custodian temporarily unavailable**
> 
> It looks like connecting Brave Rewards to {custodianName} is temporarily unavailable. Please try again later.
> 
> You can view [service status here](https://status.brave.com/). 

**Server-side PR:** https://github.com/brave-intl/bat-go/pull/1574
**Documentation:** https://github.com/brave-intl/bat-go/pull/1576/files

**Comment by emerick** [comment]
@Miyayes Is it important that the custodian name appears in the modal title? We'd have to add new code to handle that, as we only expect to do substitutions in the body of the modal not the title. Not the end of the world if we have to add that, just figured I'd check!

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.47.129 Chromium: 108.0.5359.128 (Official Build) beta (x86_64)
-- | --
Revision | 1cd27afdb8e5d057070c0961e04c490d2aca1aa0-refs/branch-heads/5359@{#1185}
OS | macOS Version 12.6.2 (Build 21G320)
```

Verified test plan from https://github.com/brave/brave-core/pull/15627 for:

<details>
<summary>Uphold - PASSED</summary>

Logs:

```
[ REQUEST ]
> URL: https://grant.rewards.bravesoftware.com/v3/wallet/uphold/68490aec-31fe-51d8-b4ab-1d23bc140999/claim
> Method: POST
> Content: {"signedLinkingRequest":"eyJib........
[ RESPONSE - OnResponse ]
> Url: https://grant.rewards.bravesoftware.com/v3/wallet/uphold/68490aec-31fe-51d8-b4ab-1d23bc140999/claim
> Result: Failure
> HTTP Code: 400
> Body: {"code":400,"data":{"validationErrors":null},"message":"Error validating Connecting Brave Rewards to Uphold is temporarily unavailable.  Please try again later"}
```

Confirmed error message displayed as expected.
Confirmed link navigates to status page as expected.

Example | Example | Example
----- | ----- | -----
<img width="1004" alt="Screen Shot 2022-12-19 at 3 03 48 PM" src="https://user-images.githubusercontent.com/28145373/208510781-2ab5889f-4352-448a-9398-b64c3735d83a.png"> | <img width="1196" alt="Screen Shot 2022-12-19 at 3 06 23 PM" src="https://user-images.githubusercontent.com/28145373/208511053-6e2026ee-0b1f-4366-a55f-eeed4a9ac854.png"> | <img width="1191" alt="Screen Shot 2022-12-19 at 3 07 49 PM" src="https://user-images.githubusercontent.com/28145373/208511198-b57aa538-cec2-4d0b-b527-d6a7c4115208.png">


</details>

<details>
<summary>bitFlyer - InProgress</summary>

</details>

<details>
<summary>Gemini - TBD</summary>

</details>

**Comment by Uni-verse** [comment]
Verified on `Samsung GS 21` using version: 

Brave	1.47.161 Chromium: 109.0.5414.61 (Official Build) beta (64-bit) 
Revision	846c6eff1c374cde417a9cdc44193545cc07f354-refs/branch-heads/5414@{#1030}
OS	Android 12; Build/SP1A.210812.016

Uphold | BitFlyer
-|-
![screenshot-1672870360504](https://user-images.githubusercontent.com/17885425/210667335-53ddd347-a578-4715-a085-f0785e7f3a90.png) | ![screenshot-1672872554281](https://user-images.githubusercontent.com/17885425/210667370-26834d0c-d4a2-4038-91e2-c5b56e519f1e.png)
