### ISSUE TITLE
discuss enabling `TabbedPaintPreview` only on lower end devices

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#25123]
## Description 

With `C105`, you'll notice `Preview` being displayed within the omnibox before the page finishes loading and then displays a modal/notification that says `Viewing live page`. What happens is that it loads an image in the view while the libraries are being loaded before letting the user know that they're viewing a live page.

@samartnik mentioned that this feature has been around for a while but is probably now appearing as it takes a bit longer for libraries to load on startup on `C105`, hence the `Preview` before loading the page. This feature is mostly tailored for lower end devices.

So we'll need to decide if we want to keep it as is for now or just enable it for lower end devices. However, if we do disable this for higher end devices and only enable it for lower device, someone with a higher end device could see a blank page while the libraries are loading rather than an `Preview` image.

## Steps to reproduce 

   1. open/launch any version of Brave that has `C105`
   2. open any website and leave it as the active tab
   3. close/re-launch Brave a few times until you see the `Preview` via the omnibox
   4. after a few `ms`, you'll notice a `Viewing life page` modal/notification in the middle of the viewport indicating the website loaded

## Actual result 

* Example of the `Preview` feature happening on `mobile`: -> https://youtube.com/shorts/zdoT8G0IteQ
* Example of the `Preview` feature happening on `tablet`: -> https://youtube.com/shorts/gBS_scxnJuk

![Screenshot_20220831-122755_Brave](https://user-images.githubusercontent.com/2602313/187813093-10ac7621-5988-42ea-b331-bc2fd9c80273.jpg)

## Expected result

TBD and needs to be discussed/decided by product re: what we're going to do.

## Issue reproduces how often 

100% reproducible using the STR/Cases outlined above.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `Yes`
- Can you reproduce this issue with the current Play Store Beta version? `Yes` 
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Samsung S10+` (Phone)
   - Android version: `Android 12`
   
## Brave version

```
Brave | 1.43.87 Chromium: 105.0.5195.68 (Official Build) (32-bit)
--- | ---
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | Android 12; Build/SP1A.210812.016
```

### Website problems only

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `Yes`

### Additional information

CCing @timchilds @anthonypkeane @srirambv @samartnik @Uni-verse

**Comment by deeppandya** [comment]
@timchilds we need to create security review for this.

**Comment by axaxs** [comment]
Just commenting to say, I have a higher end device(8gb ram, sd888) and see the same behavior as in the YouTube videos.  It's highly jarring and annoying, and would vote to remove this behavior.

**Comment by shellscape** [comment]
A year later and this is still a problem
