### ISSUE TITLE
Sync: move bookmark into folder not reflected

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#2512]
From slack messages from @darkdh and @petemill 

## Description 

Move bookmark into folder on device A is not reflected on synced device B

## Steps to Reproduce

   1. Create sync chain with device A
   2. Connect device B to sync chain
   3. On device A create bookmark a.com in a root of `Bookmarks bar`
   4. On device A create folder F1 in a root of `Bookmarks bar`
   5. Wait on device B for entities get synced
   6. On device A move a.com into F1

## Actual result:

    7. On device B a.com is not inside of F1

## Expected result:
    7. On device B a.com is inside of F1

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.61.0 Chromium: 71.0.3578.80 (Developer Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Linux

**Comment by bbondy** [comment]
Please remember to update issue milestones to match where the associated PR landed. Thanks!

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.58.14 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Mac OS X

* Verified STR in description
