### ISSUE TITLE
`Private New Tab` text is not translated in other locales like Germany/France 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#25138]
## Description 

`Private New Tab` text is not translated in other locales like Germany/France 
## Steps to Reproduce

   1. Set OS locale to Germany/France/Kannada/Hindi
   2. Open a PT or TOR or Guest window
   3. `Private New Tab` text is not translated in other locales 

## Actual result:

`Private New Tab` text is not translated in other locales like Germany/France/Kannada/Hindi

**_Germany_**
![image](https://user-images.githubusercontent.com/38657976/187933538-f9dd5c05-46ae-4e1b-9f61-461c2f717b6e.png)

## Expected result:

`Private New Tab` text should be translated in other locales
## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.43.88 Chromium: 105.0.5195.68 (Offizieller Build) (64-Bit)
-- | --
Überarbeitung | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
Betriebssystem | Windows 10 Version 21H2 (Build 19044.1889)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @mkarolin @rebron

**Comment by kjozwiak** [comment]
The above requires `1.43.92` or higher for `1.43.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
Brave | 1.43.92 Chromium: 105.0.5195.102 (Offizieller Build) (64-Bit)
-- | --
Überarbeitung | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
Betriebssystem | Windows 10 Version 21H2 (Build 19044.1889)

```
