### ISSUE TITLE
Support bitint256 flag for clangd

### ISSUE THREAD

**Issue by goodov** [brave/brave-browser#25134]
clangd errors on bitint256 values after https://github.com/brave/brave-core/pull/14787

```
Unsigned _BitInt of bit sizes greater than 128 not supported clang(bit_int_max_size)
```

**Comment by bridiver** [comment]
> clangd errors on bitint256 values after [brave/brave-core#14787](https://github.com/brave/brave-core/pull/14787)
> 
> ```
> Unsigned _BitInt of bit sizes greater than 128 not supported clang(bit_int_max_size)
> ```

Can you provide some more details as to where you are seeing this? I have never seen that error

**Comment by goodov** [comment]
> > clangd errors on bitint256 values after [brave/brave-core#14787](https://github.com/brave/brave-core/pull/14787)
> > ```
> > Unsigned _BitInt of bit sizes greater than 128 not supported clang(bit_int_max_size)
> > ```
> 
> Can you provide some more details as to where you are seeing this? I have never seen that error

![image](https://user-images.githubusercontent.com/5928869/200492957-994a96a5-3cd1-460b-8811-bae0db034e1e.png)
