### ISSUE TITLE
Browser crash when switching/selecting networks and quickly viewing asset details

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#25131]
## Description 
Found while testing https://github.com/brave/brave-core/pull/14556, Browser crash when selecting Testnet ETH

## Steps to reproduce 

   1. Create wallet 
   2. Select Ethereum Mainnet and select ETH
   3. Go back to wallet and quickly select Testnet and select ETH, browser crashes and reloads

## Actual result 

https://user-images.githubusercontent.com/17010094/187856835-fec6deab-b3db-4b37-84d5-e8e724cc10f8.mp4

Crash Log: 
1. https://share.backtrace.io/api/share/N3CorV5CwE7Wx2dMN0dwYs2
2. https://share.backtrace.io/api/share/Fa17mFIgzfWwatomvWHB73
3. https://share.backtrace.io/api/share/fR9zx26zTSdg3Ayw0GC3ll2

## Expected result
No crash

## Issue reproduces how often 
Only once on first attempt. Subsequent doesn't cause crash

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 12
   
## Brave version
1.45.18

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @Pavneet-Sing @SergeyZhukovsky

**Comment by Pavneet-Sing** [comment]
Updated the details, it's linked with clicking on an old asset which is yet to be updated for the changed network. (asset list takes some time to update)

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.45.88 x64 build
- Verified steps from issue description & [brave/brave-core#14944](https://github.com/brave/brave-core/pull/14944)
- Verified no crash when switching network and selecting an asset
- Verified when network is changed there is small delay in loading the asset 
-----------
Verification passed on Samsung Tab A with Android 10 running 1.45.88 x64 build
- Verified steps from issue description & [brave/brave-core#14944](https://github.com/brave/brave-core/pull/14944)
- Verified no crash when switching network and selecting an asset
- Verified when network is changed there is small delay in loading the asset
