### ISSUE TITLE
Brave freezes for 5 seconds on CIBC and Simplii login pages

### ISSUE THREAD

**Issue by et304383** [brave/brave-browser#25135]
## Description 
Not entirely sure what it's hanging on, but loading either of the login pages causes Brave to freeze for about 5 seconds.

## Steps to Reproduce
Go to either of these URLs:
https://www.cibconline.cibc.com/ebm-resources/public/banking/cibc/client/web/index.html#/signon
https://online.simplii.com/ebm-resources/public/client/web/index.html#/signon

## Actual result:
The page freezes for about 5 seconds with no ability to interact with the login fields or click the login button.

## Expected result:
Page loads as it does in other browsers (Chrome, Firefox, Edge) and does not freeze, allowing me to login immediately.

## Reproduces how often: 
Every time.

## Brave version (brave://version info)
1.42.97 Chromium: 104.0.5112.102 (Official Build) (64-bit) 

## Version/Channel Information:
All versions.  Has been happening for months.

## Other Additional Information:
Happens even with brave shields and rewards disabled.  Does not happen in any version of Chrome.

## Miscellaneous Information:
Looking at console and network debugger shows it may be hanging on the web socket instantiation.  Not 100% sure.

**Comment by cowwoc** [comment]
I believe this is a duplicate of https://github.com/brave/brave-browser/issues/22178

**Comment by et304383** [comment]
> I believe this is a duplicate of #22178

That is related to keyboard.  I am talking about the login button just not even working.  The entire page is non-responsive.

**Comment by cowwoc** [comment]
> That is related to keyboard. I am talking about the login button just not even working. The entire page is non-responsive.

Nope. It affects the mouse, login buttons, etc. See https://github.com/brave/brave-browser/issues/22178#issuecomment-1094036027 which is longer down the same issue.

**Comment by et304383** [comment]
> > That is related to keyboard. I am talking about the login button just not even working. The entire page is non-responsive.
> 
> Nope. It affects the mouse, login buttons, etc. See [#22178 (comment)](https://github.com/brave/brave-browser/issues/22178#issuecomment-1094036027) which is longer down the same issue.

Gotcha. Send this isn't high priority for the Brave team at the moment.

**Comment by cowwoc** [comment]
@et304383 No one has even bothered reviewing the tickets yet :( I'm not sure how to get their attention...

**Comment by cowwoc** [comment]
This issue seems to be fixed for me on `Version 1.48.167 Chromium: 110.0.5481.104 (Official Build) (64-bit)`

Can everyone else please re-test? Is this problem fixed for you as well?

**Comment by et304383** [comment]
Seems to finally be fixed!  Yay!
