### ISSUE TITLE
Refactor Brave Ads confirmation token verification

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#25140]

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.45.75 Chromium: 106.0.5249.65 (Official Build) beta (64-bit)
-- | --
Revision | 3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/14950
