### ISSUE TITLE
Rewards page blank after data reset

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#25141]
## Description 

The Rewards page appears blank after resetting Rewards data from the "Manage Wallet" modal. The Rewards page appears as normal after reload.

## Steps to Reproduce

   1. Navigate to the Rewards page
   2. Enable Rewards
   3. Click the "Manage Wallet" button
   4. On the "Reset" tab, press the "Reset" button.

## Actual result:

The Rewards page is blank. 

## Expected result:

The Rewards onboarding UI should be displayed.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

1.44.x

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
Brave | 1.46.17 Chromium: 106.0.5249.65 (Official Build) nightly (64-bit)
-- | --
Revision | 3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}
OS | Windows 10 Version 21H2 (Build 19044.2006)

```
- Verified the STR from the description and ensured that the rewards page is not blank after resetting the rewards 
![reset rewards](https://user-images.githubusercontent.com/38657976/192705456-e6b888f5-f9f8-45a9-8519-396bd88fd7fc.gif)
