### ISSUE TITLE
Brave translator problem

### ISSUE THREAD

**Issue by Bundy01** [brave/brave-browser#25143]
## Description 

The translator does not work if javascript is blocked

## Steps to Reproduce

   1. Disable scripts via Brave-Shield
   2. Trying to translate an English page into another language
   3. The page does not translate

## Expected result:
It would be nice to be able to translate these pages without having to activate the scripts, if it is possible

## Reproduces how often: 

Easily reproduced

## Desktop Brave version:

1.43.88 Chromium: 105.0.5195.68 (Build officiel) (64 bits) 

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release?   Y
- Can you reproduce this issue with the beta channel?       ?
- Can you reproduce this issue with the nightly channel?   ?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?     Y
- Does the issue resolve itself when disabling Brave Rewards?  N
- Is the issue reproducible on the latest version of Chrome?       ?

**Comment by diracdeltas** [comment]
cc @atuchin-m, not sure if this is possible given the way translate works

**Comment by atuchin-m** [comment]
@Bundy01 Thanks for the reporting.
The current design of the feature doesn't support running without JavaScript.

It's extremely hard to replace text fragment to the translated version to preserve formatting, spacing, etc using only native code. Moreover, all other browsers that support translation use JS for the same purpose.
