### ISSUE TITLE
iPhone not syncing History with Desktop. 

### ISSUE THREAD

**Issue by Saoiray** [brave/brave-browser#25146]
## Description 
Desktop History will appear on iPhone but any sites visited on iPhone are not showing up on Desktop. It seems to be one-sided. This appears both between iPhone and Windows 10 Pro, as well as iPhone and Mac. 

Bookmarks and Passwords seem to sync with no issues. This problem only exists with history, regardless of whether it's typed.

## Steps to Reproduce

   1. Type in URL in address bar
   2. Visit site
   3. This will appear in History on iPhone but not on Desktop. 

## Actual result:

History does not sync to Desktop

## Expected result:

Typed history would appear on all devices in the sync chain. 

## Reproduces how often: 
Seems to happen 100% of the time I test this. 

## Desktop Brave version:
v1.43.88

## iOS Device details:
- Device type (Phone, Tablet, Phablet):  Phone (iPhone 13 Pro Max)
- iOS version: 15.6.1

## Version/Channel Information:

- Can you reproduce this issue with the current release?  Yes
- Can you reproduce this issue with the beta channel? Haven't installed (but this issue has existed for many versions now)
- Can you reproduce this issue with the nightly channel?  Haven't installed (but this issue has existed for many versions now) 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  No
- Does the issue resolve itself when disabling Brave Rewards?  No
- Is the issue reproducible on the latest version of Chrome?  N/A

## Miscellaneous Information:

Recent Brave Community posts:

* https://community.brave.com/t/issue-with-history-sync-between-desktop-and-iphone/427014/
* https://community.brave.com/t/history-sync-is-broken-and-one-sided/427939

I'm sure there's others, including people who posted within https://community.brave.com/t/brave-sync-on-ios-is-completely-broken-and-has-been-for-many-months-plus-other-bugs-with-sync-on-ios-too-ios-if-you-have-ios-please-read/306368/

**Comment by Areckleh** [comment]
+1 https://community.brave.com/t/history-sync-is-broken-and-one-sided/427939
v1.42
iPad Air 5

**Comment by Saoiray** [comment]
Just want to say this still persists even after update to v1.43.89 on Desktop. Obviously still no new update on iPhone, so it's running on 1.42 still. Can send in sync-internals to someone if it might help.

**Comment by soner-yuksel** [comment]
@Saoiray I am checking this problem right now. For now it seems like it is a problem related with how Visit Type is recorded on iOS side. I will figure out the problem and there will be a fix for iOS `1.44`

I will also close this this ticket and open a new issue on iOS repo when I fix the problem properly.

**Comment by Saoiray** [comment]
@soner-yuksel Good to know. I would have put it over there but it's AWOL on options when submitting an issue. Only choices provided are:

- Desktop and Android Issue
- Android Issue
- Desktop Issue
- Report a security vulnerability

Definitely would have submitted there if was an option. In any case, appreciated if you can link to the new issue when made, if it's something I'll be able to see and track. (won't bother anyone, just nice to see status)

**Comment by soner-yuksel** [comment]
@Saoiray iOS has an entirely separate repository. So since the problem is iOs only I moved the ticket to https://github.com/brave/brave-ios/issues/5979. 

Thanks for reporting it, we will try try to add this fix in `1.43` which is next release.
