### ISSUE TITLE
No sync of a new device after browser launched when offline

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#2514]
## Steps to Reproduce

Device A: Windows 7 x64
Device B: Windows 10 x64

1. On Device A: Open `brave://sync/`
2. On Device A: Click `Start a new sync chain`
3. On Device A: Click `Computer`
4. Set Device A to offline (no internet access)
5. On Device B: Open `brave://sync/`
6. On Device B: Click `I have a sync code`
7. On Device B: Paste the sync code and click `Confirm sync code`
8. Set Device A to online 

## Actual result:

Devices are not synced. Waited 30 minutes for sync
Device A stuck at: 
![image](https://user-images.githubusercontent.com/34715963/51217828-f964d800-1929-11e9-9c27-9ecdef88464d.png)

Device B stuck at: 
![image](https://user-images.githubusercontent.com/34715963/51217836-05e93080-192a-11e9-8c83-3e1ef6a2944c.png)

## Expected result:
Device A synced Device B 

## Reproduces how often: 

always

## Brave version (brave://version info)

Brave | 0.59.21 Chromium: 72.0.3626.28 (Official Build) beta (64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Windows

cc @darkdh @kjozwiak @LaurenWags @GeetaSarvadnya @srirambv

**Comment by cezaraugusto** [comment]
cc @AlexeyBarabas related to https://github.com/brave/brave-browser/issues/7854

**Comment by cezaraugusto** [comment]
cc @AlexeyBarabash related to https://github.com/brave/brave-browser/issues/7854
