### ISSUE TITLE
Allow a Dapp to open onboarding at most once

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#25152]
## Description 

Unable to close Brave Wallet onboarding tab

## Steps to Reproduce

1. install `1.45.21`
2. launch Brave
3. load `supermario.store` (Warning: I think this site tries to steal all your NFTs)
4. click on the `Mint` button on the page
5. now, try closing the onboarding tab
6. clicking on the backgrounded `Super Mario` tab will spawn new onboarding tabs

## Actual result:

![wallet-accordian](https://user-images.githubusercontent.com/387249/188031322-230e8284-250a-4926-8edd-d77f0453cf69.gif)

## Expected result:

Able to close the Brave Wallet onboarding tab/window

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.45.21 Chromium: 105.0.5195.68 (Official Build) nightly (x86_64)
-- | --
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | macOS Version 13.0 (Build 22A5331f)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

cc @srirambv @rebron

**Comment by HEagle18** [comment]
Fairly weird behavior. 

I was able to replicate this on 1.45.19. I had to set up a new browser profile with no extensions or brave wallet set up. Ethereum wallet was set to `Brave Wallet (prefer extensions)`

Is this something to do with our default wallet settings, I wonder ? thoughts @bbondy

**Comment by bbondy** [comment]
We can fix this by ensuring that a tab helper opens at most 1 tab to setup the wallet

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.45.87 Chromium: 106.0.5249.91 (Official Build) beta (x86_64)
-- | --
Revision | fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}
OS | macOS Version 11.7 (Build 20G817)

### Steps:
1. installed `1.45.87`
2. launched Brave
3. loaded `supermario.store`
4. clicked on the `Mint (1)` link
5. confirmed it opened the Brave Wallet onboarding tab
6. closed the above tab
7. confirmed it closed, without opening a new tab
8. reloaded `supermario.store` again
9. clicked on `Mint (1)` again

#### Confirmed we only ever open one (1) Brave Wallet onboarding tab

example | example | example | example | example
---------|----------|---------|---------|----------
<img width="1312" alt="Screen Shot 2022-10-05 at 12 10 44 PM" src="https://user-images.githubusercontent.com/387249/194110123-50ab0d21-67d1-4987-ab7a-768d187a3220.png"> | <img width="1312" alt="Screen Shot 2022-10-05 at 12 10 50 PM" src="https://user-images.githubusercontent.com/387249/194110132-4ad914d5-ddd5-4a73-b601-48dc1d863077.png"> | <img width="1312" alt="Screen Shot 2022-10-05 at 12 10 57 PM" src="https://user-images.githubusercontent.com/387249/194110138-7a05b12a-b210-4fd4-8c2e-321730fe63c6.png"> | <img width="1312" alt="Screen Shot 2022-10-05 at 12 16 06 PM" src="https://user-images.githubusercontent.com/387249/194110366-af506a02-5a43-4257-8aa1-f21393dc53dd.png"> |  <img width="1312" alt="Screen Shot 2022-10-05 at 12 11 14 PM" src="https://user-images.githubusercontent.com/387249/194110145-2497276d-ed3f-4c5d-8493-788c0ebc80e8.png">
