### ISSUE TITLE
Pluralize `place` in the `Use Bridges` section of `brave://settings/privacy`

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#25155]
## Description 

Pluralize `place` in the `Use Bridges` section of `brave://settings/privacy`

## Steps to Reproduce

   1. install latest `nightly`
   2. load `brave://settings/privacy`
   3. scroll down to the `Use Bridges` section
   4. read the text

## Actual result:

`Bridges help you access the Tor Network in place where Tor is blocked.`

<img width="1312" alt="Screenshot 2022-09-01 at 9 54 56 PM" src="https://user-images.githubusercontent.com/387249/188062227-15c12fed-460b-4a3c-b574-50a2f42c3a64.png">

## Expected result:

`Bridges help you access the Tor Network in places where Tor is blocked.`

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.45.21 Chromium: 105.0.5195.68 (Official Build) nightly (x86_64)
-- | --
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | macOS Version 13.0 (Build 22A5331f)

cc @boocmp @rebron

**Comment by sreenath-tm** [comment]
I'm interested in contributing to this issue, so before I start working it, would you mind sparing your time explaining me to some resources to get started.

**Comment by kjozwiak** [comment]
The above requires `1.44.89` or higher for `1.44.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.44.92 Chromium: 105.0.5195.136 (Official Build) beta (x86_64)
-- | --
Revision | 872774b783d0e674186a3adcd2f92e7aa22a219c-refs/branch-heads/5195_124@{#4}
OS | macOS Version 11.7 (Build 20G817)

1. installed `1.44.92`
2. loaded `brave://settings/privacy`
3. scrolled down to the `Use Bridges` section
4. read the text

#### Confirmed the descriptive texts now has the plural `places`


<img width="1283" alt="Screen Shot 2022-09-19 at 11 40 48 AM" src="https://user-images.githubusercontent.com/387249/191091944-a4d7223e-948b-497a-aa0c-cc7c94f6907c.png">
