### ISSUE TITLE
Regression in 'Top Sites' keyboard navigation on Windows

### ISSUE THREAD

**Issue by JimBreton** [brave/brave-browser#25150]
## Description 

Since adding the ability to have more Top Sites on the NTP, one regression seems to have been introduced, at least on Windows.  If you Tab thru the 'Top Sites' and press `Enter` on one of them, the previous behavior was to follow that link; now, it just de-selects that site and does nothing.

Reproducible on multiple Windows machines, although it does not seem to occur on Linux.

## Steps to Reproduce

   1. Open the New Tab Page
   2. Press Tab a bunch of times to select one of the Top Sites
   3. Press Enter

## Actual result:

The selected Top Site icon is de-selected and its associated site is not opened.

## Expected result:
Top Site link is followed and opened.

## Reproduces how often: 

Easily/consistently

## Desktop Brave version:

1.43.88

**Comment by JimBreton** [comment]
Created with wrong template.  Copied into #25154.

**Comment by 0ljas** [comment]
same bug in macOS Ventura
