### ISSUE TITLE
Brave crashes when visiting brave://settings when Sync disabled via brave://flags

### ISSUE THREAD

**Issue by specter78** [brave/brave-browser#25156]
## Test plan
See https://github.com/brave/brave-core/pull/15031

## Description
Brave v1.43.88 crashes when Brave Sync V2 flag is disabled.

On windows - it crashes on launch 

On macOS- it crashes on opening preferences

**Comment by rebron** [comment]
@specter78 Can you go into brave://crashes send the report and post the crash id in the thread if you get a chance.

**Comment by MadhaviSeelam** [comment]
Reproduced this issue in `1.43.85 Chromium: 105.0.5195.68`  in Win 11 x64
Crash Report ID: | a72d0300-74c0-c508-0000-000000000000

- install 1.43.88
- open brave://flags and disable sync v2 and relaunch the browser
- open brave://settings/ in a new tab

**Comment by bsclifton** [comment]
Also crashes on NTP when turning off brave://flags/#brave-news

**Comment by kjozwiak** [comment]
The above requires `1.43.92` or higher for `1.43.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```
Brave | 1.43.92 Chromium: 105.0.5195.102 (Official Build) (64-bit)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | Windows 10 Version 21H2 (Build 19044.1889)
```
