### ISSUE TITLE
Add a policy option to disable Brave Rewards

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#25151]
This is a sub-task for https://github.com/brave/brave-browser/issues/22029

**Test Plan:**

1. Set the policy to disable Brave Rewards:

- [Linux]
(sudo is needed in this step) Go to /etc/brave/policies/managed (create folders if not exists already), create test_policy.json with content:
<pre>
{
  "BraveRewardsDisabled": true
}
</pre>
- [Windows]
  Open regedit and create the following keys: `BraveSoftware\Brave` under the existing key
    * For 64 bit, `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Policies`
    * For 32 bit, `HKEY_LOCAL_MACHINE\SOFTWARE\Policies` 

  Create a DWORD value at this path called `BraveRewardsDisabled` and set the value as `1`

2. Open Brave and navigate to brave://policy. Observe:
   
![Policy](https://user-images.githubusercontent.com/41635752/188021956-93fdba2e-9aa1-436c-840a-b78daa549d27.png)

3. Observe Brave Rewards icon is not shown in the location bar
4. Navigate to brave://rewards. Observe `This site can’t be reached` error page.
5. Navigate to brave://rewards-internals. Observe `This site can’t be reached` error page.
6. Open application menu (☰). Observe `Brave Rewards` menu item is not present
7. Navigate to brave://settings. Observe:
    - `Brave Rewards` item is not present in the top Settings toolbar
    - `Brave Rewards` item is not present in the left navigation menu
    - In the Shields section the sentence `This will block most ads on websites, not Brave Private Ads — those are controlled in the Brave Rewards settings.` is replaced with `This will block most ads on websites.`
8. Open application menu -> More Tools -> Task Manager. Observe `Extension: Brave Rewards` is not present (note that you would need to disable #brave-rewards-webui-panel flag to have the extension loaded normally).

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```
```

**Comment by GeetaSarvadnya** [comment]
@mkarolin I have added the key in the REGEDIT as mentioned in the step 2 in the above test plan, after that when I open the brave://rewards I am not seeing the `This site can’t be reached` error page. Could you look into this and let me know If I missing anything here?
![image](https://user-images.githubusercontent.com/38657976/193014231-9510014d-0744-4e3c-be06-d7c44b833670.png)

**Comment by mkarolin** [comment]
> @mkarolin I have added the key in the REGEDIT as mentioned in the step 2 in the above test plan, after that when I open the brave://rewards I am not seeing the `This site can’t be reached` error page. Could you look into this and let me know If I'm missing anything here? ![image](https://user-images.githubusercontent.com/38657976/193014231-9510014d-0744-4e3c-be06-d7c44b833670.png)

@GeetaSarvadnya, instead of creating `QWORD (64-bit)` value in the registry, please, create a `DWORD (32-bit)` value.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.45.85 Chromium: 106.0.5249.91 (Official Build) beta (x86_64)
-- | --
Revision | fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}
OS | macOS Version 12.6 (Build 21G115)
```

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.45.90 Chromium: 106.0.5249.103 (Official Build) beta (64-bit)
-- | --
Revision | 182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}
OS | Ubuntu 18.04 LTS


- Verified the test plan from https://github.com/brave/brave-browser/issues/25151#issue-1359473235

<details>

Ensured that (step 3) the `Brave rewards` icon is NOT shown in the URL bar
![image](https://user-images.githubusercontent.com/34715963/196623599-1db814e4-0a4e-4551-8e97-833c4392b036.png)


Ensured that (step 4) the `This site can’t be reached error page` is shown when brave://rewards page is opened
![image](https://user-images.githubusercontent.com/34715963/196623692-58f8a2d7-8a46-4e33-be72-aab20c87390f.png)


Ensured that (step 5) the `This site can’t be reached error page` is shown when brave://rewards-internals page is opened
![image](https://user-images.githubusercontent.com/38657976/193064125-21eb5f13-9006-4e58-ad5e-ccd8c50444b5.png)

Ensured that (step 6) the `Brave Rewards` menu option is NOT present in the hamburger menu
![image](https://user-images.githubusercontent.com/34715963/196623909-4d41dc23-15cb-42ab-90d4-5812ea5b2fad.png)


Ensured that (step 7a) the  `Brave Rewards` header menu is NOT shown in the top header navigation bar in brave://settings
![image](https://user-images.githubusercontent.com/34715963/196624165-a9a20f7a-f64e-4522-a342-8576a17c457b.png)


Ensured that (step 7b) the `Brave Rewards` left navigation menu is NOT shown in the left navigation settings bar in brave://settings page
![image](https://user-images.githubusercontent.com/34715963/196624302-24f9e422-3d37-4ad6-ae1c-5545c7399ef9.png)


Ensured that (step 7c) the Shields section the sentence `This will block most ads on websites, not Brave Private Ads — those are controlled in the Brave Rewards settings`. is replaced with `This will block most ads on websites`.
![image](https://user-images.githubusercontent.com/34715963/196624479-64d95217-8d7f-4e44-9a45-7b0cf679ebe2.png)



Ensured that (step 8) the `Extension: Brave Rewards` is not present in `application menu -> More Tools -> Task Manager`
![image](https://user-images.githubusercontent.com/34715963/196624647-125f1a8b-39aa-4853-b33a-83da5846f192.png)


</details>

**Comment by cra3yk** [comment]
It's stopped working after 1.45.121 Chromium: 107.0.5304.91
Now this switch (`--disable-brave-rewards-extension`) is non-existed here:
https://github.com/brave/brave-core/blob/master/components/constants/brave_switches.h
