### ISSUE TITLE
TradingView Chart Not Rendered Properly

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#2516]
## Description 
The popular TradingView chart doesn't show price/value numbers. Instead, they are clipped by the chart boundary, and thus not rendered.

## Steps to Reproduce
1. Navigate to https://www.bitmex.com/app/trade/XBTUSD
2. Expand price chart by clicking _expand_ icon at the top-right of the chart

## Actual result:
Price labels are cut off (normally visible at the right-side of the chart)

![tradingviewmodule](https://user-images.githubusercontent.com/815158/49917380-8cf74480-fe64-11e8-88cb-d9fab51f922e.PNG)

## Expected result:
Price labels should be entirely visible.

## Reproduces how often: 
Always (when loaded as a third-party component?)

## Brave version (brave://version info)
0.57.18

### Reproducible on current release:
Yes

### Website problems only:  
Enabling _device recognition_ resolves the issue.

### Additional Information
Problem may impact all sites loading the TradingView chart.

**Comment by mrzealot** [comment]
When looking into potential ways to whitelist the subresource that is "caught" fingerprinting, I noticed that the blocked origin is `https://static.bitmex.com/`, which should be TLD+1 equivalent with the site it was encountered on (`https://www.bitmex.com/app/trade/XBTUSD`). So, while it wouldn't be semantically correct for a 1st-party fingerprinting match either, it should be explicitly disqualified as a candidate for the 3rd-party version, shouldn't it?

**Comment by Nuc1eoN** [comment]
Duplicate #3412

**Comment by ryanbr** [comment]
Closing this ticket, we more details on the other ticket. https://github.com/brave/brave-browser/issues/3412
