### ISSUE TITLE
Show Solana connected sites permissions settings

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#25169]
## Description 
Show Solana connected site permission list under site setting like Ethereum

**Comment by kjozwiak** [comment]
The above requires `1.46.94` or higher for `1.46.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.46.96 x64 Beta build
- Verified test plan from [brave/brave-core#15733](https://github.com/brave/brave-core/pull/15733)
- Verified a new setting for Solana is shown under Settings -> Site Settings -> Solana
- Verified all connected Solana accounts are listed
- Verified able to remove an account
- Verified able to remove and readd a Solana account

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/200307467-ef124c0a-c585-4984-b506-7502441eb084.mp4> | <video src=https://user-images.githubusercontent.com/17010094/200308471-bcb9e797-33bb-4c84-89f3-63ca7d69704f.mp4>
