### ISSUE TITLE
Brave Translate not working without flag

### ISSUE THREAD

**Issue by UjCbFwtBayFM** [brave/brave-browser#25170]
## Description 
Brave Translate does not operate by default, flag #brave-translate-go needs to be set to "Enabled" in order for it to work.

## Steps to Reproduce
   1.  Enable Brave Translate
   2.  Visit any website not in language set up in brave://settings/languages
   3.  Notice Brave suggesting to install Google Translate extension.
   4. Go to chrome://flags
   5. set #brave-translate-go to "Enabled"
   6. Restart browser
   7. visit any website not in language set up in brave://settings/languages
   8. Notice Brave is using Brave Translate

## Reproduces how often: 
Always

## Brave version (brave://version info)
<html>
<body>

Brave | 1.43.88 Chromium: 105.0.5195.68 (Official Build) (64-bit)
-- | --
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | Windows 10 Version 21H1 (Build 19043.1889)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Unknown
- Can you reproduce this issue with the nightly channel? Unknown

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? N:A

**Comment by diracdeltas** [comment]
cc @atuchin-m

**Comment by bsclifton** [comment]
Thanks for the report @UjCbFwtBayFM! this is something we're still rolling out... it's at 25% now, soon to be 50%

You can watch over some of this in the `brave-variations` repo. For example, here's the pull request to bump it to 50%:
https://github.com/brave/brave-variations/pull/350

**Comment by rebron** [comment]
@UjCbFwtBayFM Should be live for you now. Please re-open if on restart and visiting a page you don't see Brave Translate

**Comment by cc19264997** [comment]
Hello, but he still can't translate Chinese!

**Comment by bsclifton** [comment]
@cc19264997 Chinese translation tracked here: https://github.com/brave/brave-browser/issues/25327
