### ISSUE TITLE
Implement Solana connection request and update Dapps panel for Solana

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#25175]
## Description 
For Solana support:
1. [Implement Solana native request for dapps](https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1661941523671849)
2. [Implement Solana specific permissions and accounts update](https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1661946575005259)
3. Update Dapps connection panel

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.45.95 x64 build
- Verified steps from [brave/brave-core#14973](https://github.com/brave/brave-core/pull/14973)
- Verified Solana connection request is shown 
- Verified Ethereum connection still works when Solana account is set as active
- Verified current active Solana account is requested when trying to connect to Solana Dapp 

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/195583415-f74e9fa0-ecb1-4cf1-9350-1b4cd83dab89.mp4> | <video src=https://user-images.githubusercontent.com/17010094/195589286-1a945c15-61b8-40f1-869b-39ea4a6f79ed.mp4>
