### ISSUE TITLE
Asset Filter Selector no longer sorting

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#25179]
## Description 
The `Asset Filter` selector is not sorting for `Low/High`, `High/Low` options.

https://user-images.githubusercontent.com/40611140/188216717-6d6eec58-4baf-4fad-8254-47d9512a2922.mov

**Comment by AlexNguyen1612** [comment]
Hi @Douglashdaniel , this sounds like an interesting problem, would you mind if I look into it? 
If it's okay, I'd like to know how I can "mock" all of these coins data on my local dev environment for reproducing/testing
Thank you 🙏

**Comment by Douglashdaniel** [comment]
Closing this as `Invalid`, was fixed by this revert https://github.com/brave/brave-core/pull/15181
