### ISSUE TITLE
Bridge to Aurora button needs a locale string

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#25181]
## Description 
Bridge to Aurora button needs a locale string

https://github.com/brave/brave-core/blob/master/components/brave_wallet_ui/components/desktop/views/portfolio/portfolio-asset.tsx#L613

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.45.104 Chromium: 106.0.5249.126 (Official Build) beta (64-bit) 
-- | --
Revision | `fb2e06d2dee20fe0c804528502b5ad72c613abd9-refs/branch-heads/5249_118@{#3}`
OS | Linux

- Verified `Bridge to Aurora` button is still shown and text is visible
- ![image](https://user-images.githubusercontent.com/17010094/196752179-2150e46b-1f5a-4415-84b7-31f12f552a10.png)

------------------------
Verification passed on

Brave | 1.45.104 Chromium: 106.0.5249.126 (Official Build) beta (64-bit) 
-- | --
Revision | `fb2e06d2dee20fe0c804528502b5ad72c613abd9-refs/branch-heads/5249_118@{#3}`
OS | Windows 11 Version 22H2 (Build 22621.674)

- Verified `Bridge to Aurora` button is still shown and text is visible
![image](https://user-images.githubusercontent.com/17010094/196752650-2afb2380-08cc-4a57-9469-16c5c27bca31.png)

------------------------
Verification passed on

Brave | 1.45.104 Chromium: 106.0.5249.126 (Official Build) beta (arm64)
-- | --
Revision | `fb2e06d2dee20fe0c804528502b5ad72c613abd9-refs/branch-heads/5249_118@{#3}`
OS | macOS Version 12.4 (Build 21F79)

- Verified `Bridge to Aurora` button is still shown and text is visible
![image](https://user-images.githubusercontent.com/17010094/196751839-551040a7-4dfc-4e65-acc2-f6d533a96d68.png)
