### ISSUE TITLE
Saving pdfs by printing is broken

### ISSUE THREAD

**Issue by GreenYellowLight** [brave/brave-browser#25186]
Normally when you have a pdf you can select the button in the top right and then 'print' to pdf to a folder on your computer. This is helpful as unlike the download button it allows for custom page selection.

However as of the last update this functionality has become broken.

## Steps to Reproduce

   1. Put brave in fullscreen mode
   2. Open a pdf in brave. eg http://filmeducation.org/pdf/
<img width="1440" alt="Screen Shot 2022-09-03 at 7 26 34 am" src="https://user-images.githubusercontent.com/103926103/188237596-b4c3491b-d993-4d2a-bb64-0b3f5bd4c5a4.png">
resources/primary/Brave.pdf
   3. Press the print button in the top right
<img width="197" alt="Screen Shot 2022-09-03 at 7 26 46 am" src="https://user-images.githubusercontent.com/103926103/188237687-d03a9cd5-b4c8-412a-9fbe-14cd0661c733.png">

   4. Press the save button
<img width="1440" alt="Screen Shot 2022-09-03 at 7 26 54 am" src="https://user-images.githubusercontent.com/103926103/188237812-ef8e2fa0-7590-4852-9265-1347bf7d9265.png">

   5. Screen becomes greyed out. Expected behaviour is that you will be given the mac option thing of where to save the file to
   
<img width="1440" alt="Screen Shot 2022-09-03 at 7 27 03 am" src="https://user-images.githubusercontent.com/103926103/188237841-627b735c-705b-4b8e-922f-f579d4827ae3.png">

## Actual result:
Screen becomes greyed out
   
<img width="1440" alt="Screen Shot 2022-09-03 at 7 27 03 am" src="https://user-images.githubusercontent.com/103926103/188237841-627b735c-705b-4b8e-922f-f579d4827ae3.png">

## Expected result:
There is an option of where to save the file to and you can save the pdf (or part of it) somewhere

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.42.97 Chromium: 104.0.5112.102 (Official Build) (x86_64)
-- | --
Revision | 8e5396254975ef939f2ef7d0bd334e48a052b536-refs/branch-heads/5112@{#1478}
OS | macOS Version 12.5.1 (Build 21G83)

## Version/Channel Information:

I don't know

## Other Additional Information:
Issue only happens in fullscreen mode

**Comment by rebron** [comment]
@GreenYellowLight We just released 1.44.101. Can you update to the latest version and let us know if you're still having issues with saving the pdf via print dialog.

**Comment by rebron** [comment]
@GreenYellowLight Are you seeing this same issue with Chrome if you still have that browser installed?

**Comment by GreenYellowLight** [comment]
> @GreenYellowLight Are you seeing this same issue with Chrome if you still have that browser installed?

On chrome the issue does not exist
<img width="1440" alt="Screen Shot 2022-10-05 at 1 14 34 pm" src="https://user-images.githubusercontent.com/103926103/193964865-696f4b0c-398a-4e5f-94a5-c6f52d6fbdce.png">

**Comment by GreenYellowLight** [comment]
A recent update fixed this issue

**Comment by rebron** [comment]
@GreenYellowLight Thanks for the update.
