### ISSUE TITLE
Initial hot reloading / preview for webui within brave-core

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#2518]
Overall tracked with https://github.com/brave/brave-browser/issues/2335

Create a storybook in brave-core to contain src/features from brave-ui

This is not an issue to request hot-reloading in the browser webui's itself, that will require a bit of change to get files served from localhost instead of internal build-produced pak files!

**Comment by LaurenWags** [comment]
@petemill is manual QA needed for this one? Looks like maybe the first test plan in https://github.com/brave/brave-core/pull/2857 can be executed on a packaged build, but not the others. is that sufficient?

**Comment by petemill** [comment]
@laurenwags yes just checking NTP works should be enough, thanks

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.69.119 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Mac OS X

* Verified first test plan listed in https://github.com/brave/brave-core/pull/2857
