### ISSUE TITLE
Toggling `Use Bridges` makes scrolled viewport positions reset

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#25183]
## Description 

Toggling `Use Bridges` makes scrolled viewport positions reset

## Steps to Reproduce

1. install 1.45.22
2. launch Brave
3. open `brave://settings/privacy`
4. scroll to the bottom `Use Bridges` section
5. toggle `Use Bridges` to `Enabled` / `ON`
6. scroll down again
7. now toggle `Use Bridges` off

## Actual result:

The viewport/scroll position changes, which is a bit jarring

![jumping-bean](https://user-images.githubusercontent.com/387249/188232255-5b774dfc-de6c-4f4e-92a4-14940c396fa0.gif)

## Expected result:

Collapse/expand in-place?

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.45.22 Chromium: 105.0.5195.68 (Official Build) nightly (x86_64)
-- | --
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | macOS Version 13.0 (Build 22A5331f)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.44.89` or higher for `1.44.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.44.92 Chromium: 105.0.5195.136 (Official Build) beta (x86_64)
-- | --
Revision | 872774b783d0e674186a3adcd2f92e7aa22a219c-refs/branch-heads/5195_124@{#4}
OS | macOS Version 11.7 (Build 20G817)


### Steps:
1. install `1.44.92`
2. launch Brave
3. open `brave://settings/privacy`
4. scroll to the bottom `Use Bridges` section
5. toggle `Use Bridges` to `Enabled` / `ON`
6. confirmed I'm no longer able to scroll down, with it expanded
7. now toggle `Use Bridges off`
8. confirmed it snaps back to its original state and position (collapsed)

![use-bridges](https://user-images.githubusercontent.com/387249/191090749-e791e0c2-9877-4e8d-9ced-56f1babb7345.gif)
