### ISSUE TITLE
Update "Sponsored Images" toggle UI

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#25197]
Subtask of https://github.com/brave/brave-browser/issues/15252

---

Checklist
- [x] The toggle UI should be below background image options
- [x] The new toggle UI should contain descriptions about Sponsored Images
- [x] When Brave Rewards or Brave Ad are not enabled, a button should be visible
- [x] When a user opts in the option and Reward & Ads are enabled, the description should notify the user that they're earning from it.
- [x] When clicking the "Rewards" button, "Reward tour" UI appears or "Brave Ads" option is enabled.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using 
```
Brave | 1.45.78 Chromium: 106.0.5249.65 (Official Build) beta (64-bit)
-- | --
Revision | 3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}
OS | Windows 11 Version 21H2 (Build 22000.978)
```

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using 
```
Brave | 1.45.78 Chromium: 106.0.5249.65 (Official Build) beta (64-bit)
-- | --
Revision | 3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}
OS | Windows 11 Version 21H2 (Build 22000.978)
```
Bugs filed:
* https://github.com/brave/brave-browser/issues/25719

Case 1:  Leave `Show Sponsored Images` toggle `ON` and enable Rewards 

1. Install 1.45.78
2. launch Brave
3. click Skip welcome tour
4. click `Start using Rewards` button on the NTP 
5. complete onboarding to enable Rewards 
6. click `Customize` button
7. confirmed `Show Sponsored Images` UI is available below background Images section
8. confirmed `Show Sponsored Images` toggle is `ON` by default
9. confirmed the text about sponsored images is displayed and the description notifies the user that they're earning from it. `You're earning for seeing sponsored images.`
10.  NTP sponsored images loaded?

step 4|step5|step 7-9
----|-----|-----
<img width="456" alt="image" src="https://user-images.githubusercontent.com/98358127/193143033-32ac4119-ba78-4202-b7bb-0126bf508a61.png">|<img width="461" alt="image" src="https://user-images.githubusercontent.com/98358127/193104823-14fa6a5f-64ff-48cb-8059-38f733e78ada.png">|<img width="455" alt="image" src="https://user-images.githubusercontent.com/98358127/193142804-7e90a10a-c716-4107-bbe1-68b497e8b273.png">|<img width="458" alt="image" src="https://user-images.githubusercontent.com/98358127/193106295-bcf0d28a-dc35-40eb-a026-78d35362025b.png">

Case 2: Leave `Show Sponsored Images` toggle `ON` but do not enable Rewards

1. new profile 
2. launch Brave
3. click Skip welcome tour
4. do not enable Rewards 
5. click `Customize` button
6. Confirmed `Show Sponsored Images` UI is available below background Images section
7. Confirmed `Show Sponsored Images` toggle is `ON` by default
8. Confirmed the text about sponsored images is displayed and the description notifies the user that they're earning from it. `You're earning for seeing sponsored images.`
9. confirmed `Start using Rewards` button available
10. open NTP and 3rd tab shows NTPSI
11. clicked `Start using Rewards`  button 
12. rewards onboarding tour modal should be displayed as expected



step 4|step 6-8|step 9|step11
---|---|---|----
<img width="465" alt="image" src="https://user-images.githubusercontent.com/98358127/193113122-492fb9d1-c69c-4de7-9bda-b5570f9bcc67.png">|<img width="456" alt="image" src="https://user-images.githubusercontent.com/98358127/193113206-874bbfe4-e675-4bd6-8666-43d8b708a330.png">|<img width="455" alt="image" src="https://user-images.githubusercontent.com/98358127/193146000-b745fb9b-7f73-422a-ad50-568960645443.png">|<img width="456" alt="image" src="https://user-images.githubusercontent.com/98358127/193147787-c9eb52e9-a53f-4e20-bcb0-365f0aeddbb9.png">

Case 3: Do not enable Rewards and Disable `Show Sponsored Images` 

1. new profile 
2. launch Brave
3. click Skip welcome tour
4. do not enable Rewards 
5. click `Customize` button
6. verified `Show Sponsored Images` UI is available below background Images section
7. toggle `OFF` `Show Sponsored Images` entry
8. `Start using Rewards` button is  dismissed
9. confirmed no NTP sponsored images loaded after opening new tabs

step 6|step7|step 9
----|----|----
<img width="453" alt="image" src="https://user-images.githubusercontent.com/98358127/193149475-ccc43ec6-e37a-4377-81e3-220e9cdaa393.png">|<img width="455" alt="image" src="https://user-images.githubusercontent.com/98358127/193149492-e7afdb8a-c9e9-46f1-a3d3-8a2b21151a9e.png">|<img width="453" alt="image" src="https://user-images.githubusercontent.com/98358127/193149828-1fc0d5b0-bebb-41c8-be3e-f7773f81e708.png">

Case 4: Enable Rewards and Disable `Show Sponsored Images` 

1. new profile 
2. launch Brave
3. click Skip welcome tour
4. enable Rewards
5. open NTP and click `Customize` button
6. verified `Show Sponsored Images` UI is available below background Images section
7. toggle `OFF` `Show Sponsored Images` entry
8. `Start using Rewards` button is  dismissed
9. no NTP sponsored images loaded after opening new tabs?

step 6|step7
----|----
<img width="453" alt="image" src="https://user-images.githubusercontent.com/98358127/193151166-8dd9f373-1b2b-42dc-80fb-ae944e84edac.png">|<img width="453" alt="image" src="https://user-images.githubusercontent.com/98358127/193151384-12beee49-6793-4e70-b67f-a89112cbc4c7.png">

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.45.84 Chromium: 106.0.5249.91 (Official Build) beta (x86_64)
-- | --
Revision | fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}
OS | macOS Version 11.7 (Build 20G817)

Case 1: Keep default `Show Sponsored Images` toggle `ON` and enable `Rewards`
<details>

1. install `1.45.84`
2. launch Brave using `--enable-logging=stderr --vmodule="*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*/bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6 --rewards=debug=true --rewards=staging=false`
3. click `Skip welcome tour`
4. click `Start using Rewards` button on the NTP
5. complete onboarding to enable Rewards
6. click `Customize` button
7. confirmed `Show Sponsored Images` UI is available below background Images section
8. confirmed `Show Sponsored Images` toggle is `ON` by default
9. confirmed the text about sponsored images is displayed and the description notifies the user that they're earning from it. You're earning for seeing sponsored images.
10. open NTP and load NTPSI
11. NTP sponsored images loaded as expected

step 4 | step 5 | step 7-9 | step 11
------|-------|--------|---------
<img width="1312" alt="Screen Shot 2022-10-03 at 12 12 52 PM" src="https://user-images.githubusercontent.com/387249/193629141-550514d4-932b-4612-b6cb-cc2d0896ec94.png"> | <img width="1312" alt="Screen Shot 2022-10-03 at 12 14 03 PM" src="https://user-images.githubusercontent.com/387249/193629163-d51ccb2d-163f-4c51-b8f9-68e97256f16c.png"> | <img width="1312" alt="Screen Shot 2022-10-03 at 12 14 33 PM" src="https://user-images.githubusercontent.com/387249/193629172-2d1800d2-41ce-4a3f-92b3-18385e17ef91.png"> | <img width="1312" alt="Screen Shot 2022-10-03 at 12 22 32 PM" src="https://user-images.githubusercontent.com/387249/193629184-396ffb08-9675-4263-892d-c7f0242e6de8.png">


</details>

Case 2: Enable `Show Sponsored Images` with `Rewards` `OFF`
Case 3: Do not enable `Rewards` and disable `Show Sponsored Images`
Case 4: Enable `Rewards` and disable `Show Sponsored Images`
Case 5: Enable `Rewards` but turn `OFF` `Ads` with `Show Sponsored Images` enabled
