### ISSUE TITLE
 Learn more about Brave Wallet should look like a hyperlink rather than a greyed out text

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#25201]
## Description 

 Learn more about Brave Wallet should look like a hyperlink rather than a greyed out text

## Steps to Reproduce

   1. Clean profile 
   2. Open `brave://wallet`
   3. Learn more message looks like a greyed out text and doesn't look like a hyperlink

## Actual result:

Dark | Light
-- | --
![image](https://user-images.githubusercontent.com/17010094/188309743-66518d14-75f1-4fdf-8926-522a29292001.png) | ![image](https://user-images.githubusercontent.com/17010094/188309754-2bca9fc6-ce55-4cb4-8241-8098bb63e2a1.png)

## Expected result:
Should differentiate between normal text vs hyperlink

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.45.22 Chromium: 105.0.5195.68 (Official Build) nightly (64-bit) 
-- | --
Revision | `ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @jamesmudgett @josheleonard

**Comment by wolbek** [comment]
I would like to contribute to this issue.

**Comment by wolbek** [comment]
@srirambv I have made a pull request regarding the issue 👍

**Comment by wolbek** [comment]
@srirambv I have made a pull request regarding the issue, will you please review it? If any more changes are needed, mention them and I will work on them ASAP.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.64.97 Chromium: 122.0.6261.111 (Official Build) beta (64-bit)
-- | --
Revision | f7c8f13563bfe1063db456650cb43207e1c960c0
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from [brave/brave-core#21916](https://github.com/brave/brave-core/pull/21916)
- Verified `Learn more about Brave Wallet` now has a better hyperlink feel than before
- Verified on both light and dark theme link is properly visible

https://github.com/brave/brave-browser/assets/17010094/c2bd139f-a098-481b-8c0f-9e47c9cf379f
