### ISSUE TITLE
Update kubo (go-ipfs) to 0.15.0

### ISSUE THREAD

**Issue by lidel** [brave/brave-browser#25219]
Release Notes: https://github.com/ipfs/kubo/releases/tag/v0.15.0

Changes relevant to Brave:

-  Support for Blake3 (Brave won't be able to access content hashed with Blake3 unless it updates)

cc @cypt4

**Comment by stephendonner** [comment]
Shipped and verified around 3:30am PDT on Thursday, September 15, 2022.
