### ISSUE TITLE
Fix broken layout in 

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#25210]
Broken by https://github.com/brave/brave-core/pull/14879

![image](https://user-images.githubusercontent.com/168356/188385153-74b847c9-0dbb-4f01-aad0-fff41184a5dd.png)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (64-bit) 
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | Linux

- Verified steps from [brave/brave-core#14989](https://github.com/brave/brave-core/pull/14989)
- Verified settings layout is shown properly for all networks
![image](https://user-images.githubusercontent.com/17010094/195658559-33e383d3-8a6f-4173-8b59-ac60ff4f4736.png)

------------------------
Verification passed on

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (64-bit) 
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | Windows 11 Version 21H2 (Build 22000.978)

- Verified steps from [brave/brave-core#14989](https://github.com/brave/brave-core/pull/14989)
- Verified settings layout is shown properly for all networks
![image](https://user-images.githubusercontent.com/17010094/195658690-45916f2f-9860-49d7-ab4f-0c3377326278.png)


------------------------
Verification passed on

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (arm64)
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [brave/brave-core#14989](https://github.com/brave/brave-core/pull/14989)
- Verified settings layout is shown properly for all networks
![image](https://user-images.githubusercontent.com/17010094/195658853-1c523ab1-763b-4345-9572-8c9f6cb58d66.png)
