### ISSUE TITLE
Empty item in sidebar add button

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#25212]
## Description 

<img width="303" alt="image" src="https://user-images.githubusercontent.com/6786187/188396877-4d689ce9-6a3c-49c2-ae0a-b48b4ccf5241.png">

## Steps to Reproduce

   1. Launch Brave
   2. Load any pages
   3. Select `View Page Source` from page's context menu
   4. Try to add page source page to sidebar

## Actual result:

Empty item label

## Expected result:
<img width="325" alt="image" src="https://user-images.githubusercontent.com/6786187/188397220-470810a0-f64c-4691-8cab-ce2f12a375d2.png">

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.45.35 Chromium: 105.0.5195.102 (Official Build) nightly (x86_64)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | macOS Version 13.0 (Build 22A5331f)

Followed the original steps to reproduce.

#### Confirmed I could add the full view-source:// link, and clicking on it worked.

example | example | example
---------|---------|----------
<img width="1134" alt="Screenshot 2022-09-08 at 3 07 30 PM" src="https://user-images.githubusercontent.com/387249/189234772-7daf0823-105b-4c49-bb64-a7334dccc4b3.png"> | <img width="1248" alt="Screenshot 2022-09-08 at 3 10 23 PM" src="https://user-images.githubusercontent.com/387249/189234934-bb11f083-7a34-4fdf-a78f-c37b4630f588.png"> |<img width="1137" alt="Screenshot 2022-09-08 at 3 07 57 PM" src="https://user-images.githubusercontent.com/387249/189234775-eb17ea7b-3c79-4334-9f1e-5d235ddd17b8.png">
