### ISSUE TITLE
Auto-play blocked on rainway and cheddar.com

### ISSUE THREAD

**Issue by Codeusa** [brave/brave-browser#2522]
## Description 
When starting a real-time interactive video stream from [Rainway](https://play.rainway.io/), the video and audio is blocked from playing by default even though it utilizes [MSE](https://developer.mozilla.org/en-US/docs/Web/API/Media_Source_Extensions_API) and the creation was triggered by a user action. 

## Steps to Reproduce

   1. Start a game stream.
   2. The video is blocked from playing.

## Actual result:
![](https://i.imgur.com/vdvbgXJ.png)

## Expected result:

Immediate playback of the audio/video content so the user can interact with the remote content.

## Reproduces how often: 
Until setting it to allow auto-play.

## Brave version (brave://version info)
Brave	0.57.18 Chromium: 71.0.3578.80 (Official Build) (64-bit) 
Revision	2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS	Windows

### Reproducible on current release:
Yes

### Website problems only:  
Chrome, Firefox, and Safari all play the video/audio content without issue. 

### Additional Information
N/A

**Comment by srirambv** [comment]
Autoplay is blocked by default. That the expected behaviour. Unless the domain is whitelisted it will always block on clean load. Here's a list of sites that are whitelisted (#1089)

Closing as this is the expected behaviour.

**Comment by Codeusa** [comment]
Just for reference blocking by default isn’t spec compliant as all other browsers trigger it based on site usage and user interaction, not whitelisting. There is also zero clear notification on the UI so this will break any video based screen sharing applications.

**Comment by Codeusa** [comment]
Bumping this again as we've had 6 user reports in the last week as to way manual action is required to start real-time playback. User interaction is an intent to trigger playback and there is no reason that should be blocked.

**Comment by srirambv** [comment]
cc: @bbondy  to comment on adding the said site on whitelist.

**Comment by bbondy** [comment]
0.59.x is already out the door but I put this to be uplifted to Beta channel for you @Codeusa.
Cheers!

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.60.28 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Mac OS X

* Verified navigating to cheddar.com and selecting a stream to play did not show autoplay icon in URL bar as it did on 0.59.35. Verified videos autoplayed on cheddar articles.
* Verified navigating to rainway.com and playing the video on home page did not show autoplay icon in URL bar as it did on 0.59.35.
