### ISSUE TITLE
Button text is not visible in dark mode

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#25225]
## Description 
Button text is not visible. Seems like a regression in CR105

## Steps to reproduce 

   1. Install 1.44.75 x64 beta build
   2. Open Menu -> Settings -> Brave Shields & privacy -> Clear browsing data
   3. Button text is not visible 

## Actual result 

https://user-images.githubusercontent.com/17010094/188620671-afd422e8-468c-4deb-b1e7-d9a5ec59997f.mp4

Impacted buttons

Clear data | Add Address | Add Card | Install App shortucut
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/188622299-c50e7e55-5718-420e-bbc7-3718062f514d.png) | ![image](https://user-images.githubusercontent.com/17010094/188622317-ec78f6a7-96f4-44bf-9924-72a703ecc650.png) | Can't take screenshot but has the same issue | ![image](https://user-images.githubusercontent.com/17010094/188624814-1e6b044f-668c-4d5c-a2ff-f4a9fc176e45.png)

## Expected result
Button text should be visible

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 12
   
## Brave version
1.44.75

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @mkarolin @samartnik @Uni-verse @kjozwiak

**Comment by GeetaSarvadnya** [comment]
Reproduced the issue in `Galaxy A5 ARM device version 11 - Bravemonarm.apk_1.44.75`

**Comment by kjozwiak** [comment]
Probably a good idea to get this one fixed in the `1.43.x` maintenance release.

**Comment by kjozwiak** [comment]
The above will require `1.43.91` or higher for `1.43.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.43.92 x64 build
- Verified steps from issue description
- Verified button text is visible on dark mode 
- Verified button text is still visible on light mode

Clear data | Add address | Install App | Reset Permission
-- | -- | -- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/189649531-39040fa8-3839-4a67-87b7-0d428f95c84a.png> | <img width=300 src=https://user-images.githubusercontent.com/17010094/189649553-6ba8205f-1932-4507-8026-bc8fadf5afa7.png> | <img width=300 src=https://user-images.githubusercontent.com/17010094/189649566-748df16c-516d-4688-8775-0e64d798b94b.png> | <img width=300 src=https://user-images.githubusercontent.com/17010094/189649581-571449a8-e290-4932-b055-100cfcb5666e.png>

**Comment by srirambv** [comment]
Verification passed on Samsung Tab A with Android 10 running 1.43.92 x64 build
- Verified steps from issue description
- Verified button text is visible on dark mode 
- Verified button text is still visible on light mode

Clear data | Add address | Install App | Reset Permission
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/189940241-9ed57b32-438d-427d-b347-f5868c7d7456.png) | ![image](https://user-images.githubusercontent.com/17010094/189940257-11da7fb5-6cb1-48fd-9ae2-0caeae7a4fc4.png) | ![image](https://user-images.githubusercontent.com/17010094/189940282-b26ff573-540f-447e-acc8-d735fb5432b4.png) | ![image](https://user-images.githubusercontent.com/17010094/189940325-a8f06d61-fa26-482c-87e7-c76cbec5bd0f.png)
