### ISSUE TITLE
Search Engine settings are broken

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#25221]
## Description 
This PR https://github.com/brave/brave-core/pull/14402 introduced regression. When private tab SE is changed, the normal tab SE is also changed. Reported by @samartnik 

## Steps to reproduce 

   1. Open Settings => Search Engines => Private tab
   2. Change the search engine

## Actual result 
   3. Search engine for normal tab is also changed

## Expected result
   3. Search engine for normal tab remains untouched

## Issue reproduces how often 
Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No (1.43.90)
- Can you reproduce this issue with the current Play Store Beta version?  No (1.43.79), but soon it will be
- Can you reproduce this issue with the current Play Store Nightly version? Yes (1.45.23)

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using `1.44.86, Chromium 105.0.5195.127`

### Steps:
1. installed `1.44.86`
2. launched Brave
3. tapped on the 3-dots menu (bottom right)
4. tapped on `Settings`
5. tapped on `Search engines`
6. noted default of `Brave` for both `Standard Tab` and `Private Tab`
7. tapped on `Private Tab`
8. chose `Startpage`
9. tapped the `X` to close
10. tapped the 3-dots menu
11. tapped `New Private tab`
12. tapped `blah`
13. confirmed it loaded `https://www.startpage.com/do/search?q=blah&segment=startpage.brave`
14. in a regular tab, tapped `foobar`
15. confirmed it loaded `https://search.brave.com/search?q=foobar&source=android`

example | example | example | example
---------|----------|---------|---------
![Screenshot_20220915-150746](https://user-images.githubusercontent.com/387249/190518186-7d69c097-356c-4f9a-a294-aec46da19d86.png) | ![Screenshot_20220915-150751](https://user-images.githubusercontent.com/387249/190518190-5ae4c093-2f0c-4548-a1a0-be2e4f8c551a.png) | ![Screenshot_20220915-150923](https://user-images.githubusercontent.com/387249/190518191-fe445e5a-2cac-4158-9ba2-29b2c0f594d6.png)
