### ISSUE TITLE
Learn more links are in red instead of blue in dark mode

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#25224]
## Description 
Learn more links are in red instead of blue in dark mode

## Steps to reproduce 

   1. Create wallet, change theme to dark
   2. Select ETH
   3. Click on Bridge to Aurora button

## Actual result 
<img width=300 src=https://user-images.githubusercontent.com/17010094/188583285-8388c2f6-a234-4329-831d-640ddd57eb76.png>

## Expected result
Similar to tablet 
<img width=400 src=https://user-images.githubusercontent.com/17010094/188583145-3ae325b8-96b3-4fb0-b460-f8c167ad3a50.png>

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86):ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 12
   
## Brave version
1.44.75 x64 Beta build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @Pavneet-Sing

**Comment by Pavneet-Sing** [comment]
@srirambv this is an intended behaviour as the blue colour makes it hard to read due to poor contrast with dark theme, for e.g.
![ZCbDJ (1)](https://user-images.githubusercontent.com/11755381/188845725-86bf342c-acb1-4e15-9932-e649d480f739.png)

Brave theme colour works well for dark theme contrast, though let me know if we want to use a different colour.

cc: @jamesmudgett

**Comment by jamesmudgett** [comment]
#A0A5EB

![Image](https://user-images.githubusercontent.com/318119/189395837-95b8d59e-773b-47c8-b081-b8d8695fc2a2.png)

**Comment by srirambv** [comment]
@Pavneet-Sing @jamesmudgett can you confirm if the button text should be blue for both dark & light or just for light theme?

**Comment by Pavneet-Sing** [comment]
|light| dark|
|------|--------|
| ![image](https://user-images.githubusercontent.com/11755381/189650033-cd3c2351-9db2-4eda-9d19-94b5151a9ad1.png) |![Screenshot from 2022-09-12 17-43-12](https://user-images.githubusercontent.com/11755381/189650387-7abaf1e6-cf84-464b-a42b-59af680249bf.png) |


@srirambv yes.

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.46.70 x64 Beta build
- Verified steps from issue description
- Verified Learn more links are in blue in dark/light mode

https://user-images.githubusercontent.com/17010094/196881339-9eec28e5-4f25-4f8d-8267-5c8177bad28f.mp4
