### ISSUE TITLE
use last opened panel when selecting sidepanel button in toolbar

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#25229]
## Description 

When selecting the side panel button, it will always open the reading list unless the user has removed the reading list from the sidebar, in which case the button will open the bookmarks panel.

Selecting the side panel button should use the last opened panel and toggle the last opened panel on open and close of that button.

## Steps to Reproduce

   1. Use 1.44.x and select the side panel button. (notice it opens reading list panel)
   2. Select the bookmarks panel. And close side panel button
   3. Open side panel button and notice it opens reading list panel. Expected to open bookmarks panel again.

## Actual and Expected result:
see STR above.

## Reproduces how often: 

Easily.

## Brave version (brave://version info)

1.44.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.49.89 Chromium: 110.0.5481.77 (Official Build) beta (x86_64)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | macOS Version 11.7.3 (Build 20G1116)

### Steps:
1. installed `1.49.89`
2. launched Brave
3. opened a new-tab page
4. clicked on the `Show Sidebar` button
5. confirmed it opened the `Reading List` in the left Sidebar panel
6. selected the `Bookmarks` icon in the Sidebar panel
7. clicked to close the `Sidebar` button
8. clicked again on the `Show Sidebar` button

#### Confirmed it opened with the `Bookmarks` panel

`Step 5` | `Step 6` | `Step 7` | `result`
---------|----------|---------|----------
<img width="1327" alt="Screen Shot 2023-02-07 at 10 15 51 PM" src="https://user-images.githubusercontent.com/387249/217450366-c2b9e5b4-a4bd-460b-9729-d25dc6ced1f5.png"> | <img width="1327" alt="Screen Shot 2023-02-07 at 10 16 11 PM" src="https://user-images.githubusercontent.com/387249/217450373-a6d17601-219f-42d3-8c21-32d39384ad2b.png"> | <img width="1327" alt="Screen Shot 2023-02-07 at 10 16 26 PM" src="https://user-images.githubusercontent.com/387249/217450377-ef68b52e-a490-4399-92fd-c4b03a98540d.png"> | <img width="1327" alt="Screen Shot 2023-02-07 at 10 16 34 PM" src="https://user-images.githubusercontent.com/387249/217450380-8beb16d5-6f14-426e-a9a5-b1f43e445e7f.png">
