### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by legelf36** [brave/brave-browser#25233]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.43.89  Chromium: 105.0.5195.102
Operating System: Linux 5.19.1-3-MANJARO

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1.Watching Youtube Videos
2.or Leaving browser open for more than 10  minutes
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/31340700-74c0-c508-0000-000000000000

**Comment by iefremov** [comment]
unfortunately the dump is expired
