### ISSUE TITLE
Remove Blueshift email trackers

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#25238]
Example link which includes lots of Blueshift trackers: `https://www.bmc.com/it-solutions/release-lifecycle-management.html?agency_tier=gold&utm_campaign=daily_20170912&bsft_clkid=c58b29b1-5cad-4713-b605-c04a064151b3&bsft_mid=af5baca2-3018-4a87-8ce9-c983ff946744&utm_medium=email&yt_video=sIcA21Igr5U&region=united-states&bsft_eid=32a71fc5-36ee-4710-8e6a-a35065ec7107&bsft_uid=c401f142-ebf0-48fd-928a-3f068aac3a73&utm_source=blueshift&utm_content=daily_20170912&app=LeadgenDownload&shortpath=docs%2FROI_from_HubSpot.pdf&_ga=2.38267619.1148770831.1562332271-933118289.1529345498&hubs_signup-url=blog.hubspot.com/service&hubs_signup-cta=null`

The parameters are described in this [helpful Cloudflare forum thread](https://community.cloudflare.com/t/cloudflare-apo-add-query-strings-for-blueshift-marketing-product/389140) as well as in the official [campaign report documentation](https://help.blueshift.com/hc/en-us/articles/360006193053-Campaign-Activity-Reports). The ones that are user-identifying are:
- `bsft_uid`: user UUID
- `bsft_clkid`: unique click ID

Examples of unsubscribe pages can be found in the [unsubscription documentation](https://help.blueshift.com/hc/en-us/articles/115002745253-Managing-Unsubscribes#h_01EXSP8A3GXSENCQMXCFGEEC1D) and in this [sample JSON response](https://help.blueshift.com/hc/en-us/articles/115002708213-Personalization-using-Liquid#h_01FVM15T243WW0JZK8MEHNZK9R):
- `https://universallinks.blueshiftreads.com/customer/unsubscribe?uid=e6afc3fc-f3e9-4142-836b-50cbb05c5e55&mid=cdf1727f-bdec-462b-9969-23f18d859a18&txnid=99af1bf5-969e-416f-b331-917eff4617b7&eid=433b295e-cdfe-0f5a-5cca-cfa46f6809fc&bsft_ek=2021-04-26T19%3A15%3A46Z&bsft_aaid=48400530-21e4-4403-826c-d50cc97d18b7&bsft_mime_type=html&bsft_link_id=4&bsft_tv=5&bsft_lx=4`
- `https://universallinks.blueshiftreads.com/customer/email_preferences?uid=...`

Therefore we should be able to block `bsft_uid` without affecting unsubscribe pages since `uid` without the `bsft_` prefix is used on on Blueshift-hosted pages:
- `https://click.britbox.com/z/kqup9fl7s?uid=02368e01-13c3-4b27-94b9-0cde6bfe90e8&txnid=4d081fa5-6961-485e-b5c5-c1dec0eb9fdb&mid=eb90197e-f0bb-40b4-a328-7397d42f9824&bsft_ek=2022-02-08T19%3A10%3A32Z&bsft_mime_type=html&bsft_tv=26&bsft_lx=9`
- `https://links.e.animoto.com/z/myvpwnbky?uid=8a00172a-00ee-4b1c-9642-8fac748b9fa3&txnid=adc264a9-14ba-4f81-9dee-4ca1bc5c4fb9&mid=c5abc9d6-4fcd-47f2-85f3-adba5e5c84b5&bsft_ek=2022-07-18T05%3A25%3A39Z&bsft_mime_type=html&bsft_tv=21&bsft_lx=15`
- `https://bl.houzz.com/z/j2rr7c3ty?uid=4d7c699c-6519-4505-ab70-98b47a71e28f&txnid=ffd10d64-7931-4cce-b5fa-15092efa5837&mid=a97bd283-1353-424c-bcb0-309fb5461e00&bsft_pp=4&bsft_ek=2022-02-23T13%3A00%3A38Z&bsft_mime_type=html&bsft_link_id=8458&bsft_tv=16&bsft_lx=36`

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.45.74 Chromium: 106.0.5249.55 (Official Build) beta (x86_64)
-- | --
Revision | 4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}
OS | macOS Version 11.7 (Build 20G817)

#### Followed the testplan in https://github.com/brave/brave-core/pull/15008#issue-1363927626, and confirmed the two `bsft_*` parameters were dropped

<img width="1769" alt="Screen Shot 2022-09-26 at 6 12 23 PM" src="https://user-images.githubusercontent.com/387249/192390087-8484a362-edb2-4152-8fdb-23aaf6259dea.png">

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 13` using the following build(s):

```
Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (32-bit)
--- | ---
Revision | 182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}
OS | Android 13; Build/T1B2.220916.004
```

Went through the STR/Cases outlined via https://github.com/brave/brave-core/pull/15008#issue-1363927626 and confirmed that both `bsft_*` parameters are removed from the URL as per the following:

![image](https://user-images.githubusercontent.com/2602313/195240175-2614c4f4-a587-40de-a3e6-db6aaf5a2770.png)
