### ISSUE TITLE
Unable to load `jim-unstoppable.zil` using a local-node IPFS install

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#25230]
## Description 

Unable to load `jim-unstoppable.zil` using a local-node IPFS install

(Found while testing https://github.com/brave/brave-browser/issues/24621.)

## Steps to Reproduce

1. install `1.45.19`
2. launch Brave
3. load `jim-unstoppable.zil`
4. click on `Proceed using Infura server`
5. on the interstitial page, click on `Use a Brave local IPFS node`

## Actual result:

Stuck at `Looking for peers...`

<img width="1312" alt="Screen Shot 2022-09-06 at 12 42 31 PM" src="https://user-images.githubusercontent.com/387249/188725428-c7f96d8f-ddf3-4c89-ba55-bb6a02349528.png">

## Expected result:

Should resolve and load over `ipfs://QmSEj9K6mAj52CFqCzd5Pbt4DgAFocWovwnn2GJpyFjm3p`

NOTE: `brad.crypto` works

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.45.19 Chromium: 105.0.5195.68 (Official Build) nightly (x86_64)
-- | --
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | macOS Version 11.6.8 (Build 20G730)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @srirambv @supermassive

**Comment by stephendonner** [comment]
cc @spylogsster @cypt4

**Comment by stephendonner** [comment]
@supermassive mind taking a look at this, when you get a chance?  Thanks!

**Comment by supermassive** [comment]
UD resolving worked correctly here. Not sure about what's going on with IPFS stuff. Maybe @spylogsster or @cypt4 have some ideas.

**Comment by cypt4** [comment]
@stephendonner , could you recheck this issue, please?

**Comment by stephendonner** [comment]
Works for me now using 

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (x86_64)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | macOS Version 11.7.1 (Build 20G918)

🤷 

`Use a Brave local node IPFS` | `Use a public gateway`
-------------------------------|------------------------
<img width="1312" alt="Screen Shot 2022-10-28 at 9 00 15 AM" src="https://user-images.githubusercontent.com/387249/198682456-dc0e5092-5df5-4235-a440-1838d034095e.png"> | <img width="1312" alt="Screen Shot 2022-10-28 at 9 01 48 AM" src="https://user-images.githubusercontent.com/387249/198682501-5822250d-739c-41f1-b1bd-62a97a593cf7.png">

**Comment by vadimstruts** [comment]
The IPFS local node and scheme has been [deprecated](https://github.com/brave/brave-browser/issues/37735)
