### ISSUE TITLE
Images missing on Create new sync chain

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#2523]
## Description 

Images missing on Create new sync chain on Linux

## Steps to Reproduce

   1. Install `0.58.12`
   2. Create a new sync chain
   3. On device selection screen, images are misssing

## Actual result:

![screenshot from 2018-12-13 17-30-02](https://user-images.githubusercontent.com/17010094/49937490-de531280-fefc-11e8-8335-cbaf0c777c87.png)

## Expected result:
Should show images as per spec

## Brave version (brave://version info)

Brave | 0.58.12 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
No Beta/Dev is still not on sync V2 UI
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
NA
- Is the issue reproducible on the latest version of Chrome? 
NA

### Additional Information

cc: @brave/legacy_qa to verify on other platforms

**Comment by LaurenWags** [comment]
Reproduces on macOS

Brave | 0.58.12 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

![screen shot 2018-12-13 at 8 51 21 am](https://user-images.githubusercontent.com/28145373/49942798-577a4780-feb4-11e8-88ba-59da1c684532.png)

**Comment by GeetaSarvadnya** [comment]
Reproduce on Windows '0.58.12`


Brave | 0.58.12 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Windows




![image](https://user-images.githubusercontent.com/38657976/49943293-8375e700-ff0d-11e8-882b-7c9d9f1b32b3.png)

**Comment by cezaraugusto** [comment]
fixed by the uplift of https://github.com/brave/brave-core/commit/a35a3e30d6ed555b20960c402f7344342ca0c96f. doesn't happen in v0.58.14.
