### ISSUE TITLE
Add NFT tab

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#25245]
Add a new tab with NFT assets in a grid with a search and network filter

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (64-bit) 
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | Linux

- Verified steps from [brave/brave-core#15013](https://github.com/brave/brave-core/pull/15013)
- Verified a new NFT tab is available
- Verified all NFT's added to wallet is listed 
- Verified able to filter NFT's by network
- Verified clicking on the NFT loads the NFT details page
- Verified clicking on the magnifier icon on the NFT shows a bigger version of NFT image
- Encountered [#26064](https://github.com/brave/brave-browser/issues/26064)

https://user-images.githubusercontent.com/17010094/196120063-4d73cb46-c14e-4927-815d-5332cdbf97bb.mp4


------------------------
Verification passed on

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (64-bit) 
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | Windows 11 Version 21H2 (Build 22000.978)

- Verified steps from [brave/brave-core#15013](https://github.com/brave/brave-core/pull/15013)
- Verified a new NFT tab is available
- Verified all NFT's added to wallet is listed 
- Verified able to filter NFT's by network
- Verified clicking on the NFT loads the NFT details page
- Verified clicking on the magnifier icon on the NFT shows a bigger version of NFT image
- Encountered [#26064](https://github.com/brave/brave-browser/issues/26064)

https://user-images.githubusercontent.com/17010094/196120595-f1298570-d8b1-429b-8270-61e6ede98e3e.mp4

------------------------
Verification passed on

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (arm64)
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [brave/brave-core#15013](https://github.com/brave/brave-core/pull/15013)
- Verified a new NFT tab is available
- Verified all NFT's added to wallet is listed 
- Verified able to filter NFT's by network
- Verified clicking on the NFT loads the NFT details page
- Verified clicking on the magnifier icon on the NFT shows a bigger version of NFT image
- Encountered [#26064](https://github.com/brave/brave-browser/issues/26064)

https://user-images.githubusercontent.com/17010094/196114926-ee80615f-7859-4012-b5ac-24695f053c0d.mov
