### ISSUE TITLE
Once the VPN is disconnected unable to reconnect the VPN on the future date

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#25244]
## Description 

Once the VPN is disconnected unable to reconnect the VPN on the future date

## Steps to Reproduce

   1. Clean profile enable Brave VPN (today)
   2. Disconnect the VPN and close the browser, set the sys clock ahead by one day
   3. Relaunch the browser and reconnect the vpn
   4. Unable to connect the VPN
  
## Actual result:

Once the VPN is disconnected unable to reconnect the VPN on the future date

## Expected result:
Should be able to connect the vpn 

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.44.75 Chromium: 105.0.5195.102 (Official Build) beta (64-bit)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | Windows 10 Version 21H2 (Build 19044.1889)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @bsclifton @spylogsster @brave/qa-team

**Comment by spylogsster** [comment]
Slack thread for history https://bravesoftware.slack.com/archives/CC5SA8CCB/p1662454317658309

**Comment by bsclifton** [comment]
Closing as `wontfix`. Client is correctly choosing the token for the next day (since clock changed) but backend is not showing that as valid (because server side has a different time, basically the correct time)
