### ISSUE TITLE
ERC20 Approve is using wrong network for fees

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#25255]
## Description 
Set your selected network `Solana Mainnet` and then create an `ERC20 Approve` transaction.
The transactions fees will be parsed for `Solana` and not `Ethereum`

![image](https://user-images.githubusercontent.com/40611140/188919429-765ede70-560f-4448-ae20-e421cf6b77ed.png)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.45.104 Chromium: 106.0.5249.126 (Official Build) beta (64-bit) 
-- | --
Revision | `fb2e06d2dee20fe0c804528502b5ad72c613abd9-refs/branch-heads/5249_118@{#3}`
OS | Linux

- Verified steps from [brave/brave-core#15020](https://github.com/brave/brave-core/pull/15020)
- Verified correct network is used for fee calculation irrespective of which network is set as active

https://user-images.githubusercontent.com/17010094/196635896-83375e84-6cb1-4f63-8f47-c3c090f66b44.mp4


------------------------
Verification passed on

Brave | 1.45.104 Chromium: 106.0.5249.126 (Official Build) beta (64-bit) 
-- | --
Revision | `fb2e06d2dee20fe0c804528502b5ad72c613abd9-refs/branch-heads/5249_118@{#3}`
OS | Windows 11 Version 22H2 (Build 22621.674)

- Verified steps from [brave/brave-core#15020](https://github.com/brave/brave-core/pull/15020)
- Verified correct network is used for fee calculation irrespective of which network is set as active

https://user-images.githubusercontent.com/17010094/196635233-3ad01ab5-0cb5-4744-83df-b6c44d53a628.mp4


------------------------
Verification passed on

Brave | 1.45.104 Chromium: 106.0.5249.126 (Official Build) beta (arm64)
-- | --
Revision | `fb2e06d2dee20fe0c804528502b5ad72c613abd9-refs/branch-heads/5249_118@{#3}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [brave/brave-core#15020](https://github.com/brave/brave-core/pull/15020)
- Verified correct network is used for fee calculation irrespective of which network is set as active

https://user-images.githubusercontent.com/17010094/196633820-bc7aa3bc-219f-4ef3-829a-36721249271f.mov
