### ISSUE TITLE
Make `Manage Subscriptions` tooltip for Brave News more descriptive?

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#25252]
## Description 

Make `Manage Subscriptions` tooltip for Brave News more descriptive?

Found while testing https://github.com/brave/brave-browser/issues/23778

## Steps to Reproduce

   1. install `1.45.19`
   2. launch Brave
   3. open `brave://flags`
   4. enable `brave://flags/#brave-news-subscribe-button`
   5. click `Relaunch`
   6. load `planet.mozilla.org`
   7. hover over the `Brave News` icon in the URL bar
   8. look at its tooltip

## Actual result:

`Manage Subscriptions`

<img width="925" alt="Screen Shot 2022-09-07 at 7 36 53 AM" src="https://user-images.githubusercontent.com/387249/188905974-bab2d326-370b-4c5e-ba77-c6cf75651715.png">

## Expected result:

Something more descriptive?  Especially since Brave News isn't part of Premium, and `Subscriptions` might be confusing without the Brave News context (even though the icon is a newspaper...)

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.45.19 Chromium: 105.0.5195.68 (Official Build) nightly (x86_64)
-- | --
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | macOS Version 11.6.8 (Build 20G730)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @fallaciousreasoning @rebron

**Comment by stephendonner** [comment]
cc @aguscruiz

**Comment by mattmcalister** [comment]
This is ok. Closing.
