### ISSUE TITLE
Wallet icon in toolbar is not shown when Solana dapps is connected

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#25258]
## Description 
Wallet icon in toolbar is not shown when Solana dapps connection is established. The icon should be visible to interact with panel and dapps.

## Steps to reproduce 

   1. Create, unlock wallet and Go to solana dapps
   2. Connect with dapps
   3. The wallet icon is not visible but the Solana account is connected

[solana-brave-wallet-icon.webm](https://user-images.githubusercontent.com/11755381/188938754-6934e9c0-9591-4da6-88cc-e4980c356763.webm)

### Additional information

Seems like [delegate_->ShowPanel();](https://github.com/brave/brave-core/blob/0db2967b9bc3aa6d1742c4fa40be6f31672d2e40/components/brave_wallet/browser/solana_provider_impl.cc#L105) is not being reached.

For Ethereum, [walletInteractionDetected](https://github.com/brave/brave-core/blob/92f6e5e6041f65cb952c70a5aab432df2ebd195c/android/java/org/chromium/chrome/browser/crypto_wallet/BraveWalletProviderDelegateImplHelper.java#L33) is triggered to show the icon

BTW, the icon shows up if the wallet is locked and connection request is triggered. 

cc: @darkdh @SergeyZhukovsky

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.46.96 x64 Beta build
- Verified the wallet icon is shown in toolbar when Solana Dapp is connected
- Verified able to click the wallet icon once connected
- Encountered [#26583](https://github.com/brave/brave-browser/issues/26583)

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/200300193-fe01a41f-0520-40d8-82b3-d2f75c682e9d.mp4> | <video src=https://user-images.githubusercontent.com/17010094/200300247-a4e26e01-f14c-452e-b2a0-3bcb4d2bea3c.mp4>
