### ISSUE TITLE
Follow up to  #24750 - Got DNS error for the URL (Regex multi) under test

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#25259]
## Steps to Reproduce

- Install 1.44.73
- launch Brave
- visit https://dev-pages.brave.software/navigation-tracking/debouncing.html
- click Run for `Regex (multi)`

## Actual result:

Ex1|Ex2
---|---
<image width="970" alt="image" src="https://user-images.githubusercontent.com/98358127/188940896-d5d69ecb-b432-44fe-a105-c1181c7bff75.png">|<image width="970" alt="image" src="https://user-images.githubusercontent.com/98358127/188940908-1c4a0c1a-f1fd-4dc5-9dd5-87b56d15cd6b.png">

## Expected result:
https://dev-pages.brave.software should be displayed in the Observed Referrer section

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Brave | 1.44.73 Chromium: 105.0.5195.68 (Official Build) beta (64-bit)
-- | --
Revision | ad13e82529051bac6a0e65f455e6d7a1e5fd7938-refs/branch-heads/5195@{#903}
OS | Windows 11 Version 21H2 (Build 22000.856)

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@ShivanKaul

**Comment by ShivanKaul** [comment]
The next component update should fix this.
