### ISSUE TITLE
Payment status link does not work in Rewards WebUI panel

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#25253]
## Description 

When the Rewards panel is rendered using WebUI, the "Check status" link that appears in the payment status banner does not work.

## Steps to Reproduce

   1. Click the Rewards icon when payments are processing.
   2. Click the "Check status" link.

## Actual result:

Nothing happens.

## Expected result:

A new tab should be opened displaying Rewards payment processing status. 

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

1.43.88 Chromium: 105.0.5195.68 (Official Build) (x86_64)

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```

Brave | 1.43.92 Chromium: 105.0.5195.102 (Official Build) (64-bit)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | Windows 10 Version 21H2 (Build 19044.1889)

```
