### ISSUE TITLE
Investigate referral code being added from the playstore install

### ISSUE THREAD

**Issue by porteron** [brave/brave-browser#25265]
## Description 
Historically we've accepted that referral codes do not get captured from our google paid digital advertising into our internal analytics system.  More specifically we are missing out on referral data from the Google Playstore install, we'd like to investigate the reason for this because it looks like we have the proper code in place `getInstallReferrer()` to extract this data. 

#### A couple places to leading thoughts: 
- Is the referral code captured and added to the usage ping before the user sends their first usage ping?
- Is there any other information in the `getInstallReferrer` response that we can use? (campaign name, id, ref url)?
- We are calling `getInstallReferrer()`[docs](https://developer.android.com/google/play/installreferrer/igetinstallreferrerservice). Is this being called at the correct time and added to the users local-state so that it is included in the usage ping? And does it persist for 90 days?
- Is referral link being passed through to install and do we have a valid refcodes in campaign setups, format XXX123? ?

cc @anthonypkeane @laurentiugruia 

## Issue reproduces how often 
- Seems to be almost all the time

## Version/Channel Information:
- Can you reproduce this issue with the current Play Store version?  Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - All android core it seems

**Comment by samartnik** [comment]
Test plan:
Case 1:
1. Install brave browser from the GPS ad (contact @porteron on how to do it).
2. Goto `brave://local-state`.
3. Make sure that ref code there is `UAC001`.

Case 2:
1. Install brave browser from the GPS (justr regular install).
2. Goto `brave://local-state`.
3. Make sure that ref code there is `BRV001`.

Case 3:
1. Install brave browser from the referral link.
2. Goto `brave://local-state`.
3. Make sure there is appropriate ref code.

**Comment by porteron** [comment]
Details on Case 1: 
So the first one requires setting up a google ads search campaign so that the app shows up in the Google Playstore for the beta app. Typically it will be discoverable in the US and maybe CA. Based on the keywords, description, headline that was setup in the google ads campaign then those are the words that should be searched in the playstore to find our ad.

Once the campaign is approved and is live then you should be able to find the app.

If you search Brave Browser Beta in the Playstore and look at the results, then scroll down until you see the Ads section and scroll through until you see the Beta app. Click on that and download from there.

It's all a bit of a pain to setup so hopefully we do not need to do this again, but if needed just ping me.

**Comment by kjozwiak** [comment]
The above requires `1.44.107` or higher for `1.44.x` verification 👍

**Comment by kjozwiak** [comment]
As per https://github.com/brave/brave-browser/issues/25265#issuecomment-1267633910 and https://github.com/brave/brave-core/pull/15307#issuecomment-1267899346, `Test Case #1` can only be verified on `BETA` which has been completed below. @Uni-verse @srirambv re: `1.44.x` verifications, we'll just need to run through `Test Case #2` & `Test Case #3`.


Verification **PASSED** on `Samsung S10+` running `Android 12` using the following build(s):

```
Brave | 1.45.87 Chromium: 106.0.5249.91 (Official Build) beta (64-bit)
--- | ---
Revision | fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}
OS | Android 12; Build/SP1A.210812.016
```

* searched for `brave browser` via GPS and tapped on the `Brave Beta` ad that appeared with the `ads` section of GPS
* installed and launched `1.45.87 Chromium: 106.0.5249.91`
* checked `brave://local-state` and ensured that `"promo_code": "UAC001"` as per https://github.com/brave/brave-browser/issues/25265#issuecomment-1265674315

```
},
      "referral": {
         "promo_code": "UAC001"
      },
```

**`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------
![Screenshot_20221005-144330_Google Play Store](https://user-images.githubusercontent.com/2602313/194175258-c6b3f0ac-a887-44d2-86cf-f56dc8216a09.jpg) | ![Screenshot_20221005-163700_Google Play Store](https://user-images.githubusercontent.com/2602313/194175266-000d3f0f-068e-462a-af57-9d679c0c3fb1.jpg) | ![Screenshot_20221005-163803_Brave - Beta](https://user-images.githubusercontent.com/2602313/194175272-f8785bb7-de0b-4803-936e-c165d09edaf4.jpg)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 13` using the following build(s):

```
Brave | 1.44.110 Chromium: 106.0.5249.103 (Official Build) (64-bit)
--- | ---
Revision | 182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}
OS | Android 13; Build/T1B2.220916.004
```

**`Test Case #1`**

As per https://github.com/brave/brave-browser/issues/25265#issuecomment-1267633910, this was verified on `BETA` as per https://github.com/brave/brave-browser/issues/25265#issuecomment-1269051612.

**`Test Case #2`**

* downloaded/installed `Brave Browser` from GPS via the internal test channel
* launched Brave and ensured that `"promo_code": "BRV001"` via `brave://local-state`

```
"referral": {
         "initialization": true,
         "promo_code": "BRV001"
```

![Screenshot_20221011-233058](https://user-images.githubusercontent.com/2602313/195243551-7037bb78-7c7c-4419-bab5-9486ac25db28.png)

**`Test Case #3`**

* opened https://kjozwiak.github.io via `Chrome` and clicked on `Production GPS WWK708`
* downloaded/installed `Brave Browser` from GPS
* launched Brave and ensured that `"promo_code": "WWK708"` via `brave://local-state`

```
"referral": {
         "download_id": "59b8c2a2-f697-4ea0-b5ce-cac0badfb7ce",
         "initialization": true,
         "promo_code": "WWK708"
      },
```

![Screenshot_20221011-233624](https://user-images.githubusercontent.com/2602313/195244139-89b2da6b-4a1d-4650-aa49-d385b06773b6.png)
