### ISSUE TITLE
Brave Ads issuers fail to update on iOS

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#25266]
## Description 

Brave Ads issuers fail to update on iOS, meaning ads will never be shown.

## Steps to Reproduce

   1. Fresh install
   2. Launch browser

## Actual result:

`Issuers already up to date` appears in the Rewards diagnostic log

## Expected result:
`Updated issuers` should appear in the Rewards diagnostic log

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by kjozwiak** [comment]
The above will be verified by QA via https://github.com/brave/brave-ios/issues/6001 once we start getting `1.44` TF builds.
