### ISSUE TITLE
Users are not rewarded for inline content Brave Ads

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#25260]
## Steps to Reproduce

   1. TBD
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by aseren** [comment]
The issue was already fixed in nightly here: https://github.com/brave/brave-core/pull/15069/commits/d610ee7f944152a7a260620ccac05032671adefb

**Comment by aseren** [comment]
fix was already provided in this issue https://github.com/brave/brave-core/pull/15069 and was uplifted to 1.43x and 1.44x:
https://github.com/brave/brave-core/pull/15081
https://github.com/brave/brave-core/pull/15082

**Comment by aseren** [comment]
### Test plan:

Check that user is rewarded for viewing an inline ad on Android.

**Comment by Santhoshkumarmamidala** [comment]
Still it is not working. I am facing the issue right now.
Can anyone help me?

**Comment by Santhoshkumarmamidala** [comment]
> ### Test plan:
> Check that user is rewarded for viewing an inline ad on Android.

It is not working

**Comment by tmancey** [comment]
@Santhoshkumarmamidala can you please send a screenshot of the browser version, thanks

**Comment by Santhoshkumarmamidala** [comment]
Hi,

Please find the attached screenshot.

Thanks & Regards,
Santhosh Kumar.

**Comment by tmancey** [comment]
@Santhoshkumarmamidala I cannot see the screenshot? Thanks

**Comment by Santhoshkumarmamidala** [comment]
Hi,

Please find the attached and pasted the same below.

Note:  It is working fine now in latest version.

I think it was one off issue in below release.

About Brave

Application version Brave 1.43.94, Chromium 105.0.5195.136

Operating system Android 11; Build/RKQ1.201022.002

Legal information

Copyright 2022 The Brave Authors. All rights reserved.
