### ISSUE TITLE
Add rotating hash to payload

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#25263]

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` & `Samsung Galaxy Tab S7` using the following build:

```
Brave	1.46.130 Chromium: 108.0.5359.62 (Official Build) (64-bit) 
Revision	041930a89a990cfab0315a2d9f20d6429a4a67cf-refs/branch-heads/5359@{#938}
OS	Android 12; Build/SP1A.210812.016

```

Using acceptance criteria in https://github.com/brave/brave-core/pull/15042#issue-1366484429

- Verified `Device Id` is not empty in Ad diagnostic tab in brave://rewards-internals/
- Verified that `Device Id` differs on different devices

Example | Example
-|-
![screenshot-1669741159472](https://user-images.githubusercontent.com/17885425/204595725-50516a72-03e3-4d57-aa0d-7baa2dfc8ad7.png) | ![screenshot-1669741305123](https://user-images.githubusercontent.com/17885425/204595730-69f548b1-f21f-4ef7-9e26-c22a38b36d92.png)
