### ISSUE TITLE
Need more spacing between `Submit` and `Cancel` dialogs for Tor bridges

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#25268]
## Description 

Need more spacing between `Submit` and `Cancel` dialogs for Tor bridges

## Steps to Reproduce

   1. install `1.44.78`
   2. launch Brave
   3. open `brave://settings/privacy`
   4. scroll to `Use Bridges`
   5. click on the `Request a New Bridge...` button
   6. look at the spacing between the `Submit` and `Cancel` dialogs

## Actual result:

example | example
---------|---------
<img width="1300" alt="Screenshot 2022-09-07 at 2 31 20 PM" src="https://user-images.githubusercontent.com/387249/188987869-b3f94484-e4fd-4d4d-8c61-6b5f32a91baf.png"> | <img width="191" alt="Screenshot 2022-09-07 at 2 31 37 PM" src="https://user-images.githubusercontent.com/387249/188987876-00d54829-805e-4c87-b175-758d2259ef4e.png">

## Expected result:

Compare spacing with `brave://settings/clearBrowserData`

example | example
---------|---------
<img width="1300" alt="Screenshot 2022-09-07 at 2 34 33 PM" src="https://user-images.githubusercontent.com/387249/188988138-d749c30f-c61f-4b85-b03c-1c1173c39f48.png"> | <img width="246" alt="Screenshot 2022-09-07 at 2 35 11 PM" src="https://user-images.githubusercontent.com/387249/188988139-6e76cf39-1cb4-4059-b1b3-21210556a084.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.44.78 Chromium: 105.0.5195.102 (Official Build) beta (x86_64)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | macOS Version 13.0 (Build 22A5331f)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @boocmp

**Comment by kjozwiak** [comment]
The above requires `1.44.89` or higher for `1.44.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.44.92 Chromium: 105.0.5195.136 (Official Build) beta (x86_64)
-- | --
Revision | 872774b783d0e674186a3adcd2f92e7aa22a219c-refs/branch-heads/5195_124@{#4}
OS | macOS Version 11.7 (Build 20G817)

### Steps:
1. installed `1.44.92`
2. launched Brave
3. opened `brave://settings/privacy`
4. scrolled to `Use Bridges`
5. clicked on the `Request a New Bridge...` button
6. looked at the spacing between the `Submit` and `Cancel` dialogs

#### Confirmed the spacing and button ordering are correct

<img width="1312" alt="Screen Shot 2022-09-19 at 11 12 59 AM" src="https://user-images.githubusercontent.com/387249/191085737-8611c4ff-c449-406c-b258-d5d14d9d6a5c.png">
