### ISSUE TITLE
Paused video's are unpaused when apps are switched if "Enable background audio" is enabled on IOS devices

### ISSUE THREAD

**Issue by JQDigital** [brave/brave-browser#25264]
## Description 

On IOS (iPhone) if you watch a YouTube video in the Brave browser, pause the video, and then switch to another app. The video will be unpaused and the audio will play in the background. This also happens on other video websites.
This behavior ends when "Enable background audio" is disabled.
Background audio should only play when the video is playing, it should not unpause paused videos.

## Steps to Reproduce

   1.  make sure you have an IOS device (iPhone)
   2. make sure that the volume is audible
   3. make sure that "enable background audio" is enabled in Brave browser
   4. go to youtube.com in the Brave browser
   5. play any random video
   6. pause the video
   7. Switch to another app, for instance by double clicking the home button on iPhone SE

## Actual result:

The video will unpause and start playing, the audio will be heard.

## Expected result:
The video will remain paused, the audio will not be heard.
The audio should only be heard if the video is manually unpaused by the user.

## Reproduces how often: 

every time]

## Brave version (info found on brave://version)

version 1.42 (22.8.15.22)

## Version/Channel Information:

- Can you reproduce this issue with the current release? unknown
- Can you reproduce this issue with the beta channel? unknown
- Can you reproduce this issue with the dev channel? unknown
- Can you reproduce this issue with the nightly channel? unknown

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome?  no

**Comment by iccub** [comment]
Seems to work for me
