### ISSUE TITLE
Remove device modal text needs to be aligned correctly

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#2526]
## Description 

Remove device modal text needs to be aligned correctly

## Steps to Reproduce

   1. Install 0.58.12
   2. Enable sync and add a device
   3. Remove the device added in step 2, modal popup shows up with incorrect text alignment 

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/49938030-99c87680-fefe-11e8-8fe7-4690067a357b.png)

## Expected result:
All text should be left aligned

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.58.12 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
No, Beta/Dev doesnt have V2 UI
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
NA
- Is the issue reproducible on the latest version of Chrome? 
NA
### Additional Information

cc: @brave/legacy_qa to verify on other platforms

**Comment by cezaraugusto** [comment]
@srirambv per your video you seem to be using sync v1. could you please check with the new version?

**Comment by srirambv** [comment]
@cezaraugusto  not sure which video you are referring to ?

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Ubuntu 18.04.1 x64` using the following build:

Brave | 0.58.14 Chromium: 71.0.3578.98 (Official Build) (64-bit)
--- | ---
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Linux

<img width="761" alt="screen shot 2018-12-18 at 2 17 13 am" src="https://user-images.githubusercontent.com/2602313/50138039-29f21d00-026b-11e9-903f-51492e554a5b.png">
