### ISSUE TITLE
Gradient backgrounds are not shown

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#25271]
On Nightly and Development version, Gradient backgrounds are not revealed. 

![image](https://user-images.githubusercontent.com/5474642/188996880-79da040e-f5f4-43d0-b047-7c5911110a30.png)

https://github.com/brave/brave-core/pull/14867 seems to break this

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.45.75 Chromium: 106.0.5249.65 (Official Build) beta (x86_64)
-- | --
Revision | 3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}
OS | macOS Version 11.7 (Build 20G817)

### Steps:
1. installed `1.45.75`
2. launched Brave
3. opened a new-tab page
4. clicked on `Customize`
5. clicked on `Gradients`
6. confirmed `Refresh on every new tab` was unchecked
7. clicked on various colors
8. opened a new tab for each color
9. opened multiple new tabs for each color

#### Confirmed gradients are properly rendered for each new-tab page (excepting Sponsored Images)

example | example | example
---------|---------|----------
<img width="1081" alt="Screen Shot 2022-09-27 at 1 46 21 PM" src="https://user-images.githubusercontent.com/387249/192600097-3f6d717e-a124-453e-86cd-9a77846e63d6.png"> | <img width="1125" alt="Screen Shot 2022-09-27 at 1 46 28 PM" src="https://user-images.githubusercontent.com/387249/192600100-47a05256-1111-4081-a19e-f232b2606199.png"> | <img width="1024" alt="Screen Shot 2022-09-27 at 1 54 45 PM" src="https://user-images.githubusercontent.com/387249/192601147-f4e55e46-5d38-43f1-9963-1e655f9888ee.png">
