### ISSUE TITLE
`Request a New Bridge...` button should be disabled until its radio button is selected

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#25270]
## Description 

`Request a New Bridge...` button should be disabled until its radio button is selected

## Steps to Reproduce

   1. install `1.44.78`
   2. launch Brave
   3. load `brave://settings/privacy`
   4. scroll down to the `Request a New Bridge...` button
   5. click on it

## Actual result:

The `Request Bridge` dialog CAPTCHA dialog appears

example | example
---------|---------
<img width="1174" alt="Screenshot 2022-09-07 at 3 19 41 PM" src="https://user-images.githubusercontent.com/387249/188993776-8c41e4bb-b6f0-4dd8-b196-532075ade1bb.png"> | <img width="1300" alt="Screenshot 2022-09-07 at 2 31 20 PM" src="https://user-images.githubusercontent.com/387249/188993818-1ed6ab13-577b-4d7a-8037-a902cf9c3e91.png">

## Expected result:

Nothing.  The button shouldn't be clickable until the radio button `Request a bridge from torproject.org` is selected.

<img width="1782" alt="Screenshot 2022-09-07 at 3 11 07 PM" src="https://user-images.githubusercontent.com/387249/188993364-fde2c024-37f4-4279-b352-1a68cba2188c.png">

## Reproduces how often: 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @boocmp @aguscruiz

**Comment by stephendonner** [comment]
Figma here: https://www.figma.com/file/tLXWGCpNoiJxDZDdpfordj/Desktop-Settings?node-id=2732%3A97824

**Comment by boocmp** [comment]
fixed in https://github.com/brave/brave-core/pull/14996
