### ISSUE TITLE
Add setting to show/hide sidepanel button

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#25272]
## Description 

Add a setting in brave://settings/appearance to give users the ability to show/hide side panel button regardless of usage of reading list/bookmarks panel. Some set of users will opt to keep the main toolbar clean to leave room for Extensions and continue to use the sidebar via hover or always on and select bookmarks panel or reading list from the sidebar.

Should be able to right click on the side panel button to hide button similar to other icons such as Rewards, Wallet, VPN.

## Actual result:

Currently can only hide side panel button by "removing" reading list and bookmarks from the sidebar.

## Expected result:
Ability to show/hide Side panel button in the navigation toolbar.

## Brave version (brave://version info)

1.44.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? no

**Comment by aguscruiz** [comment]
This looks pretty straightforward in terms of UX/UI. Do we need a mockup or just implement?

**Comment by fallaciousreasoning** [comment]
I think we can just implement :smile:

**Comment by sangwoo108** [comment]
@rebron @aguscruiz I wonder what is default visibility of the button. Is the button visible by default?

**Comment by rebron** [comment]
Should be visible by default cc: @petemill

**Comment by kjozwiak** [comment]
The above requires `1.44.95` or higher for `1.44.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.44.95 Chromium: 106.0.5249.40 (Official Build) (x86_64)
-- | --
Revision | fab1d91915d2722d6339aaa7f4e9ce44f1e9b103-refs/branch-heads/5249@{#442}
OS | macOS Version 11.7 (Build 20G817)

### Case 1: toolbar button

Confirmed:
* `Show side panel` icon is shown by default, to the left of the `Wallet` icon
* context-clicking the `Show side panel` icon and clicking `Hide Side Panel Icon` hides the icon from the toolbar

### Case 2: `brave://settings/appearance`

Confirmed:
* `Show side panel button` is toggled to `Enabled`
* toggling `Show side panel button` to `Disabled` removes it from the toolbar
* toggling it back to `Enabled` restores the button on the toolbar

`enabled` | `disabled`
-----------|-----------
<img width="1312" alt="Screen Shot 2022-09-21 at 11 47 40 AM" src="https://user-images.githubusercontent.com/387249/191586512-8427e429-d2de-40d0-8045-50ad126e17ba.png"> | <img width="1312" alt="Screen Shot 2022-09-21 at 11 47 46 AM" src="https://user-images.githubusercontent.com/387249/191586516-1b8e1199-37c4-4d4b-8ddc-f709e8e5b6bb.png">


### Case 3: menu-item text

<img width="344" alt="Screen Shot 2022-09-21 at 11 48 05 AM" src="https://user-images.githubusercontent.com/387249/191586405-cb491334-d8f3-487b-b114-6085268daa51.png">


Logged:
* https://github.com/brave/brave-browser/issues/25532



### Case 4: migration from 1.43.x
