### ISSUE TITLE
[Android] Disallow Rewards from being enabled and show clearer unavailable messaging for users in unavailable list countries

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#25276]
## Description

Android equivalent of https://github.com/brave/brave-browser/issues/25275. 

**Designs: https://www.figma.com/file/ag8i1OV5vpvn4SiOhW2c0f/Github-fixes?node-id=1853%3A34996**

- [ ] Hide BAT icon for Rewards panel if device region is in unavailable list
- [x] Show messaging on Rewards settings page (inherited from desktop) 

Learn more link goes to: https://support.brave.com/hc/en-us/articles/9053832354957

**Comment by kjozwiak** [comment]
@LaurenWags any thoughts on the above? @Uni-verse and myself are in the triage call and debating if this needs to be labelled as `QA/Test-All-Device-Types`. Looks like `Desktop` was only done on `Win x64` so we're assuming one device is fine but let is know if you feel differently.

**Comment by LaurenWags** [comment]
Agree, I think just one is fine 👍🏻
