### ISSUE TITLE
Apply JSON sanitizer to WaybackMachineURLFetcher

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#25283]
Follow up from https://github.com/brave/brave-browser/issues/21764

Let's use the sanitizer for https://github.com/brave/brave-core/blob/master/components/brave_wayback_machine/wayback_machine_url_fetcher.cc#L83

```
// Sanitizes and normalizes JSON by parsing it in a safe environment and
// re-serializing it. Parsing the sanitized JSON should result in a value
// identical to parsing the original JSON.
//
// This allows parsing the sanitized JSON with the regular JSONParser while
// reducing the risk versus parsing completely untrusted JSON. It also minifies
// the resulting JSON, which might save some space.
https://source.chromium.org/chromium/chromium/src/+/main:services/data_decoder/public/cpp/json_sanitizer_non_android.cc
https://source.chromium.org/chromium/chromium/src/+/main:services/data_decoder/public/cpp/json_sanitizer.h
[https://source.chromium.org/chromium/chromium/src/+/main:services/data_decoder/public/[…]coder.cc;l=208;drc=88989bcd7983c93c8d294e1472160d0718299f62](https://source.chromium.org/chromium/chromium/src/+/main:services/data_decoder/public/cpp/data_decoder.cc;l=208;drc=88989bcd7983c93c8d294e1472160d0718299f62)
```

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.45.87 Chromium: 106.0.5249.91 (Official Build) beta (x86_64)
-- | --
Revision | fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}
OS | macOS Version 11.7 (Build 20G817)



### Case 1: page archive found - `PASSED`
<details>

### Steps:

1. installed `1.45.87`
2. launched Brave
3. loaded `my.aol.com`
4. confirmed I got the `Sorry, that page is missing...` doorhanger
5. clicked on `Check for saved version`

#### Confirmed it loaded `https://web.archive.org/web/20221005110522/https://www.aol.com/`

`Wayback Machine doorhanger` | `web.archive.org/....www.aol.com/`
----------------------------------|-----------------
<img width="1312" alt="Screen Shot 2022-10-05 at 5 52 20 PM" src="https://user-images.githubusercontent.com/387249/194171076-7bed291f-e44d-44d2-805c-20db2e0955f9.png"> | <img width="1312" alt="Screen Shot 2022-10-05 at 5 55 03 PM" src="https://user-images.githubusercontent.com/387249/194171231-561a4568-eade-4d6f-a8dd-a78f1d2dfe05.png">

</details>

### Case 2: no page archive, valid URL - `PASSED`
<details>

### Steps:

1. installed `1.45.87`
2. launched Brave
3. loaded `www.aol.com`

#### Confirmed I didn't receive the `Wayback Machine's` doorhanger

<img width="1312" alt="Screen Shot 2022-10-05 at 5 56 52 PM" src="https://user-images.githubusercontent.com/387249/194171646-67872adf-89a3-4c83-bdc8-53a79c8f7e19.png">
</details>

### Case 3: no page archive, broken URL - `PASSED`
<details>

### Steps:

1. installed `1.45.87`
2. launched Brave
3. loaded `https://brave.com/broken_link`
4. clicked on `Check for saved version`

#### Confirmed I got the `Wayback Machine`, and after clicking `Check for saved version` it disappeared

`Wayback Machine` | `No saved version`
---------------------|--------------------
<img width="1312" alt="Screen Shot 2022-10-05 at 6 04 26 PM" src="https://user-images.githubusercontent.com/387249/194172626-a23b06f9-d2ee-4f5b-b989-e10dbad54b25.png"> | <img width="1312" alt="Screen Shot 2022-10-05 at 6 04 30 PM" src="https://user-images.githubusercontent.com/387249/194172631-3594d808-cd55-4174-ad58-cb53a7c71517.png">


</details>

### Case 4: `Don't ask me again` - `PASSED`
<details>

### Steps:

1. installed `1.45.87`
2. launched Brave
3. loaded `https://brave.com/broken_link`
6. clicked on `Don't ask me again`
7. reloaded the page

#### Confirmed there was no `Wayback Machine` triggered on the 2nd page load

`Wayback Machine doorhanger` | `reloaded`
---------------------------------|---------
<img width="1312" alt="Screen Shot 2022-10-05 at 5 58 41 PM" src="https://user-images.githubusercontent.com/387249/194172140-3120c8d8-8e2e-4fec-86a0-34e66d6064e2.png"> |<img width="1312" alt="Screen Shot 2022-10-05 at 6 00 57 PM" src="https://user-images.githubusercontent.com/387249/194172143-44f4bb05-873d-4d5c-b16a-0f3175c410bd.png">
