### ISSUE TITLE
Fingerprint upgrade broke youtube.com (forces aggressive fingerprint blocking). Migration impacted by sync

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#25280]
## Description 
It seems the browser's color preference is not respected by YouTube (and likely other sites).

## Steps to Reproduce
   1. Be on an older Brave (less than 1.45.26 or older)
   2. Be on a sync chain with a a few devices and run Brave
   3. Upgrade to latest Nightly (ex: 1.45.28 or higher)
   4. Have OS appearance mode set to Light mode
   5. Visit brave://settings/appearance
   6. Set `Brave colors` to `Dark`
   7. Visit youtube.com

## Actual result:
It's showing with a white background

## Expected result:
It should show with a dark colored background

## Reproduces how often: 
100%

## Brave version (brave://version info)
- Issue is not present in 1.45.26
- Issue is present in 1.45.28 https://github.com/brave/brave-core/commits/b721953065326b08054ad97c12323dc9bb43475a

## Version/Channel Information:
Nightly

- Can you reproduce this issue with the current release? NO
- Can you reproduce this issue with the beta channel? NO
- Can you reproduce this issue with the nightly channel? YES

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? YES
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? NO

**Comment by bsclifton** [comment]
Based on regression range and commit log, it may have been unintentionally caused by https://github.com/brave/brave-core/pull/14389

**Comment by bsclifton** [comment]
OK seems I had a bad upgrade experience; fresh profile with above steps works great 😄 Looking into this more

**Comment by bsclifton** [comment]
Seems I have a few entries which have `balanced` in them under `profile` > `content_settings` > `exceptions` > `fingerprintingV2`

Example bad entry looks like this:
```
                    "www.youtube.com,https://balanced":
                    {
                        "expiration": "0",
                        "last_modified": "13306484393598196",
                        "model": 0,
                        "setting": 2
                    }
```

**Comment by bsclifton** [comment]
WIP pull request to address https://github.com/brave/brave-core/pull/15050

**Comment by bridiver** [comment]
It looks like sync is re-adding the deleted entries which we've seen in other cases as well

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.45.88 Chromium: 106.0.5249.91 (Official Build) beta (x86_64)
-- | --
Revision | fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}
OS | macOS Version 12.6 (Build 21G115)
```

**Comment by LaurenWags** [comment]
`QA/Blocked` pending additional information from https://bravesoftware.slack.com/archives/C7VLGSR55/p1665149264236009

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.45.65 Chromium: 106.0.5249.40 (Official Build) nightly (x86_64)
-- | --
Revision | fab1d91915d2722d6339aaa7f4e9ce44f1e9b103-refs/branch-heads/5249@{#442}
OS | macOS Version 12.6 (Build 21G115)
```

<details>
<summary>Case 1 - STR from description - InProgress</summary>

STR from: https://github.com/brave/brave-browser/issues/25280#issue-1365860297


</details>
