### ISSUE TITLE
Apply JSON sanitizer to Ipfs

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#25284]
Follow up from https://github.com/brave/brave-browser/issues/21764

Let's use the sanitizer for https://github.com/brave/brave-core/blob/master/components/ipfs/ipfs_service.cc

```
// Sanitizes and normalizes JSON by parsing it in a safe environment and
// re-serializing it. Parsing the sanitized JSON should result in a value
// identical to parsing the original JSON.
//
// This allows parsing the sanitized JSON with the regular JSONParser while
// reducing the risk versus parsing completely untrusted JSON. It also minifies
// the resulting JSON, which might save some space.
https://source.chromium.org/chromium/chromium/src/+/main:services/data_decoder/public/cpp/json_sanitizer_non_android.cc
https://source.chromium.org/chromium/chromium/src/+/main:services/data_decoder/public/cpp/json_sanitizer.h
[https://source.chromium.org/chromium/chromium/src/+/main:services/data_decoder/public/[…]coder.cc;l=208;drc=88989bcd7983c93c8d294e1472160d0718299f62](https://source.chromium.org/chromium/chromium/src/+/main:services/data_decoder/public/cpp/data_decoder.cc;l=208;drc=88989bcd7983c93c8d294e1472160d0718299f62)
```

**Comment by stephendonner** [comment]
## Verification `PASSED` using 

Brave | 1.45.84 Chromium: 106.0.5249.91 (Official Build) beta (x86_64)
-- | --
Revision | fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}
OS | macOS Version 11.7 (Build 20G817)

<details>
<summary>Installation and initial public gateway/Brave Local IPFS node page load</summary>

`interstitial IPFS page` | `Brave local IPFS node` | `gateway`
---------|----------|---------
<img width="1312" alt="Screen Shot 2022-10-03 at 8 19 31 PM" src="https://user-images.githubusercontent.com/387249/193710369-51019e70-48f4-428d-93ea-37c5d7030a4e.png"> | <img width="1312" alt="Screen Shot 2022-10-03 at 8 20 35 PM" src="https://user-images.githubusercontent.com/387249/193710372-c20c2221-4c6b-4754-87f7-34c19dc2c30b.png"> | <img width="1312" alt="Screen Shot 2022-10-03 at 8 22 53 PM" src="https://user-images.githubusercontent.com/387249/193710373-8f6c9024-341e-438c-96b6-a95f537eee5a.png">

</details>

<details><summary>Import Page</summary>

`Import this Page` | `imported Wikipedia page`
-------------------|---------------------------------
<img width="1197" alt="Screen Shot 2022-10-03 at 8 39 48 PM" src="https://user-images.githubusercontent.com/387249/193710404-279ac214-ea4b-41c9-a480-70a3d9236033.png"> | <img width="1312" alt="Screen Shot 2022-10-03 at 8 40 01 PM" src="https://user-images.githubusercontent.com/387249/193710407-1ba3b3ed-e49b-4893-90b6-d0c2a56e09ff.png">

</details>

<details><summary>Import JSON</summary>

`sample-json.json` | imported JSON
---------------|----------------
<img width="1312" alt="Screen Shot 2022-10-03 at 10 49 54 PM" src="https://user-images.githubusercontent.com/387249/193724024-df506e7d-dfba-4e8b-a64b-32de1a5ad69d.png"> | <img width="1312" alt="Screen Shot 2022-10-03 at 10 49 58 PM" src="https://user-images.githubusercontent.com/387249/193724033-f9f9afe3-3c96-4c2a-a921-c049fa4d471e.png">

</details>

<details><summary>Import selected text to IPFS</summary>

`lipsum.com` | imported text
--------------|--------------
<img width="1312" alt="Screen Shot 2022-10-03 at 8 24 25 PM" src="https://user-images.githubusercontent.com/387249/193710376-6be9fd20-4c85-4cd1-b5c4-8e1c41239016.png"> | <img width="1312" alt="Screen Shot 2022-10-03 at 8 33 59 PM" src="https://user-images.githubusercontent.com/387249/193710380-7e02f848-76e9-4341-9e49-e584d36ccd25.png">

</details>

#### IPFS & IPNS URLs

<details><summary>ipfs://</summary>

`IPFS`: Ensured each of the following URLs load over `Brave local IPFS node` modes:
 * ipfs://bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq/wiki/Vincent_van_Gogh.html#Life
 * ipfs://bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi/
 * ipfs://QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco/wiki/Tokyo_National_Museum.html
 * ipfs:QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG/readme

`ipfs://bafybeim...` | `ipfs://bafybeigdr...` | `ipfs://QmXoypizjW...` | `ipfs:QmYwAPJz...`
-------------------|----------------------|-----------------------|---------------------
<img width="1312" alt="Screen Shot 2022-10-03 at 9 06 08 PM" src="https://user-images.githubusercontent.com/387249/193712768-c7091425-17f8-45c0-ad09-ae0ebbba4f9e.png"> | <img width="1312" alt="Screen Shot 2022-10-03 at 9 06 47 PM" src="https://user-images.githubusercontent.com/387249/193712834-f117a0f7-e744-4d63-a3f0-815b3454760b.png"> | <img width="1312" alt="Screen Shot 2022-10-03 at 9 08 11 PM" src="https://user-images.githubusercontent.com/387249/193712957-4529827a-7760-459b-abd0-39e851b63c7c.png"> | <img width="1312" alt="Screen Shot 2022-10-03 at 9 08 49 PM" src="https://user-images.githubusercontent.com/387249/193713013-efb765f6-a82d-4d89-b766-ad7d9eb655cd.png">
</details>

<details><summary>ipns://</summary>

`IPNS`: Ensured each of the following IPNS URLs load over `Brave local IPFS node` modes:
 * ipns://en.wikipedia-on-ipfs.org
 * ipns://en.wikipedia-on-ipfs.org/wiki/Tokyo#Islands
 * ipns://docs.ipfs.io
 * ipns://brantly.eth (ENS)
 * ipns://vitalik.eth (ENS)
 * ipns://brad.crypto (Unstoppable Domains)

`ipns://en.wikipedia...org` | `ipns://en.wikipedia...#Islands` | `ipns://docs.ipfs.io` 
--------------------------|--------------------------------|--------------------
<img width="1312" alt="Screen Shot 2022-10-03 at 9 31 13 PM" src="https://user-images.githubusercontent.com/387249/193715359-0421b8a3-300d-4980-8aae-4a02a06adf25.png"> | <img width="1312" alt="Screen Shot 2022-10-03 at 9 32 22 PM" src="https://user-images.githubusercontent.com/387249/193715436-d20c7ffe-14aa-49f2-87cd-8da70ba24618.png"> | <img width="1312" alt="Screen Shot 2022-10-03 at 9 34 02 PM" src="https://user-images.githubusercontent.com/387249/193715610-93d12b58-92ce-4360-b261-69d2a99f64da.png">


`ipns://brantly.eth` (ENS) | `ipns://vitalik.eth` (ENS) | `ipns://brad.crypto` (Unstoppable Domains)
------------|-----------|----------
<img width="1312" alt="Screen Shot 2022-10-03 at 9 29 02 PM" src="https://user-images.githubusercontent.com/387249/193715102-1fe91e88-f2b6-44cf-8038-cca6523d693e.png"> | <img width="1312" alt="Screen Shot 2022-10-03 at 9 29 37 PM" src="https://user-images.githubusercontent.com/387249/193715175-5e3ade31-6c61-4038-9997-bdf1f337c436.png"> | <img width="1312" alt="Screen Shot 2022-10-03 at 9 30 19 PM" src="https://user-images.githubusercontent.com/387249/193715242-2994f715-5205-43c5-83da-3ef70b04a54d.png">

</details>
