### ISSUE TITLE
Apply JSON sanitizer to SkusUrlLoaderImpl

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#25285]
## Test plan
See https://github.com/brave/brave-core/pull/15043

## Description
Follow up from https://github.com/brave/brave-browser/issues/21764

Let's use the sanitizer for https://github.com/brave/brave-core/blob/master/components/skus/browser/skus_url_loader_impl.cc

```
// Sanitizes and normalizes JSON by parsing it in a safe environment and
// re-serializing it. Parsing the sanitized JSON should result in a value
// identical to parsing the original JSON.
//
// This allows parsing the sanitized JSON with the regular JSONParser while
// reducing the risk versus parsing completely untrusted JSON. It also minifies
// the resulting JSON, which might save some space.
https://source.chromium.org/chromium/chromium/src/+/main:services/data_decoder/public/cpp/json_sanitizer_non_android.cc
https://source.chromium.org/chromium/chromium/src/+/main:services/data_decoder/public/cpp/json_sanitizer.h
[https://source.chromium.org/chromium/chromium/src/+/main:services/data_decoder/public/[…]coder.cc;l=208;drc=88989bcd7983c93c8d294e1472160d0718299f62](https://source.chromium.org/chromium/chromium/src/+/main:services/data_decoder/public/cpp/data_decoder.cc;l=208;drc=88989bcd7983c93c8d294e1472160d0718299f62)
```

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.45.84 Chromium: 106.0.5249.91 (Official Build) beta (x86_64)
-- | --
Revision | fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}
OS | macOS Version 11.7 (Build 20G817)

### Steps:
<details>

1. installed `1.45.84`
2. launched Brave
3. opened `brave://flags`
4. set the `SDK` and `VPN` flags to `Enabled`
5. clicked `Relaunch`
6. loaded `account.bravesoftware.com`
7. entered `issue25285@mailinator.com` and clicked `Get login link`
8. clicked the button in the email
9. clicked `Browse plans`
10. scrolled down to `Brave VPN Subscription`
11. clicked `Buy now`
12. filled out and submitted the Stripe checkout page
13. clicked `Refresh Brave VPN` button
14. clicked the `VPN` button on the toolbar
15. accepted the macOS `Brave VPN` config when prompted
16. toggled `Brave VPN` `Off` and `On` using context menu, app menu, and via the macOS VPN menu

#### Confirmed I was connected to `Brave VPN`, and could disconnect/reconnect via various methods in the UI
</details>

<details><summary>Screenshots</summary>

example | example | example | example | example
---------|----------|---------|----------|---------
<img width="1312" alt="Screen Shot 2022-10-04 at 12 51 29 AM" src="https://user-images.githubusercontent.com/387249/193739489-f880fb84-5535-456b-a91b-d1b93cc06816.png"> | <img width="1298" alt="Screen Shot 2022-10-04 at 12 52 49 AM" src="https://user-images.githubusercontent.com/387249/193739495-d3b7654b-14c3-4e69-af93-55a36f1d37b2.png"> | <img width="1298" alt="Screen Shot 2022-10-04 at 12 52 54 AM" src="https://user-images.githubusercontent.com/387249/193739505-7eda3ce6-637c-4c22-859a-5a8d727e51b9.png"> | <img width="1298" alt="Screen Shot 2022-10-04 at 12 53 25 AM" src="https://user-images.githubusercontent.com/387249/193739512-4b571328-7d9f-452f-8249-8bd735886cf7.png"> | <img width="1298" alt="Screen Shot 2022-10-04 at 12 53 30 AM" src="https://user-images.githubusercontent.com/387249/193739518-ec8d8446-9d64-4c29-91d6-3176e37ef664.png">

example | example | example | example | example
---------|---------|----------|----------|---------
<img width="1298" alt="Screen Shot 2022-10-04 at 12 53 36 AM" src="https://user-images.githubusercontent.com/387249/193739523-709012e3-5244-4957-ad08-2f65d3c5b928.png"> | <img width="1188" alt="Screen Shot 2022-10-04 at 12 53 54 AM" src="https://user-images.githubusercontent.com/387249/193739529-d44e68d6-8527-4c9b-b76c-fe4168372873.png"> | <img width="1298" alt="Screen Shot 2022-10-04 at 12 54 24 AM" src="https://user-images.githubusercontent.com/387249/193739536-897f8d98-86e9-4397-a3fc-45a5ac0b8aff.png"> | <img width="1184" alt="Screen Shot 2022-10-04 at 12 54 37 AM" src="https://user-images.githubusercontent.com/387249/193739546-dafd91f1-88b9-4646-ae67-fcfd1975af1c.png"> | <img width="1298" alt="Screen Shot 2022-10-04 at 12 54 46 AM" src="https://user-images.githubusercontent.com/387249/193739550-97862c3c-5de4-4ca4-a6b3-f8dc76760ce6.png">
