### ISSUE TITLE
Enable Translate feature by default

### ISSUE THREAD

**Issue by atuchin-m** [brave/brave-browser#25289]
The feature is nearly to be rolled to 100% of users.
https://github.com/brave/brave-variations/pull/355

The feature should be enabled by default in the code and the griffin experiment should be finished.

**Comment by LaurenWags** [comment]
@atuchin-m could you provide a test plan for QA to use if manual QA is required here? if not, we should have this labeled as `QA/No`. Thanks!

**Comment by atuchin-m** [comment]
@LaurenWags IMHO we need only sanity check that the feature is enabled despite the Griffin config.
https://github.com/brave/brave-core/pull/15068#issuecomment-1248207592

**Comment by LaurenWags** [comment]
@atuchin-m is the following sufficient?

**Comment by atuchin-m** [comment]
Yes, that's enough.

**Comment by LaurenWags** [comment]
perfect, thanks for confirming @atuchin-m!

**Comment by LaurenWags** [comment]
Verified with

```
Brave | 1.45.90 Chromium: 106.0.5249.103 (Official Build) beta (x86_64)
-- | --
Revision | 182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}
OS | macOS Version 12.6 (Build 21G115)
```

Verified steps from https://github.com/brave/brave-browser/issues/25289#issuecomment-1271518616.

Confirmed on a clean profile (without restart, so no griffin seed pulled), that Brave's translate service was offered, not the Google extension:

Example | Example | Example
---- | ---- | ----
<img width="962" alt="Screen Shot 2022-10-07 at 9 44 38 AM" src="https://user-images.githubusercontent.com/28145373/194568467-1c253a81-d946-4e18-8fa6-a0a1d15a1258.png"> | <img width="960" alt="Screen Shot 2022-10-07 at 9 45 02 AM" src="https://user-images.githubusercontent.com/28145373/194568468-8a0341b6-b1fc-4785-9287-1e3acf32770a.png"> | <img width="1113" alt="Screen Shot 2022-10-07 at 9 45 37 AM" src="https://user-images.githubusercontent.com/28145373/194568469-ec54a66d-5e76-40f7-bc9a-f0ec9520d2a5.png">

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` & `Samsung Galaxy Tab S7` using the following build(s):

```
Brave	1.45.106 Chromium: 107.0.5304.36 (Official Build) (64-bit) 
Revision	2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}
OS	Android 12; Build/SP1A.210812.016
```

- Confirmed brave translate is enabled on clean install

Wikipedia.fr | Wikipedia.fr (Translated) | Menu
-|-|-
![screenshot-1666214290939](https://user-images.githubusercontent.com/17885425/196808815-2c8a0357-6818-4310-8b51-cb4121f50000.png) | ![screenshot-1666214324379](https://user-images.githubusercontent.com/17885425/196808820-fe389ec8-ec87-49f8-9e17-c2b96d91ee86.png) | ![screenshot-1666214339236](https://user-images.githubusercontent.com/17885425/196808824-b95945cb-5540-47e3-bb8d-de73182bc02a.png)
![screenshot-1666215224268](https://user-images.githubusercontent.com/17885425/196809052-1c88176a-06a2-4073-9b83-3ffdea73cbf7.png) | ![screenshot-1666215235562](https://user-images.githubusercontent.com/17885425/196809055-b6379e30-32c9-4fab-81c8-762dc9eb533f.png) | ![screenshot-1666215241683](https://user-images.githubusercontent.com/17885425/196809057-5357abc6-f101-4fef-9efc-260661cd1fed.png)
