### ISSUE TITLE
Improve copy of the "Automatically redirect .onion sites" setting

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#25298]
The long description of the "Automatically redirect .onion sites" setting is phrased in an odd way:
![Screenshot from 2022-09-08 12-29-31](https://user-images.githubusercontent.com/167821/189209720-c497168d-64d8-4245-ab22-7198d33cbc7f.png)

Suggested rewrite (reviewed by @rmcfadden3 ):

> Brave will switch to the .onion version of a website when available, and automatically open all .onion domains in a Tor window.

**Comment by rmcfadden3** [comment]
@fmarier — you're too modest. That copy is all you. All I did was write "ship it!" :)

**Comment by rmcfadden3** [comment]
Yeah, ship it!

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.45.38 Chromium: 105.0.5195.102 (Official Build) nightly (x86_64)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | macOS Version 11.6.8 (Build 20G730)

### Steps:
1. installed `1.45.38`
2. launch Brave
3. open `brave://settings/privacy`
4. looked at the copy for `Automatically redirect .onion sites`

#### Confirmed the copy has been updated

<img width="1213" alt="Screen Shot 2022-09-09 at 11 23 51 AM" src="https://user-images.githubusercontent.com/387249/189418988-b082b51a-c5db-497a-8ac8-24933cc5fcbb.png">
