### ISSUE TITLE
Typo in Tor Use Bridges setting description

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#25297]
![tor-windows-settings](https://user-images.githubusercontent.com/167821/189207890-533ed614-3d1f-43d4-b4a4-6fb75ff3ef6d.png)

> [...] access the Tor Network in place where [...]

should be:

> [...] access the Tor Network in place**s** where [...]

**Comment by stephendonner** [comment]
Was already filed in https://github.com/brave/brave-browser/issues/25155 - thanks for finding and fixing!
