### ISSUE TITLE
Adding (This device) text to the device name removes both devices from sync chain

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#2529]
## Description 

Adding (This device) text to the device name removes both devices from sync chain

## Steps to Reproduce

   1. Install 0.58.12
   2. Enable sync on it and copy the code words
   3. Install 0.59.6
   4. **Show you are smart** and enter the placeholder device name along with `(This device)`
   5. Remove second device added with the lowercase `device` in 0.58.12 and get a cup of coffee and watch the magic on release build

## Actual result:

You proved you are smart and beat the system (https://drive.google.com/open?id=1Cc2w3h2cG7yT7NJmtOGeKmisxfVjUqJr)

## Expected result:
Sync back-end needs to get smarter than users

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.58.12 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Linux

Brave | 0.59.6 Chromium: 71.0.3578.80 (Official Build) beta(64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @bbondy @rebron @brave/legacy_qa to verify on other platforms

**Comment by srirambv** [comment]
@darkdh this is reproduced when you delete the second device from the list on the new beta(0.59.8). Here's the recording https://drive.google.com/open?id=1_T9CuqYoYGtEIz4TFSkz1VzMh3uzlXRc

**Comment by rebron** [comment]
cc: @bradleyrichter

**Comment by darkdh** [comment]
I thought this is expected from v2 spec.
You have to have two devices to setup sync chain and when you have only one device in the sync chain, it will be reset.

**Comment by darkdh** [comment]
Although it is spec, considering this:
If there are device a and device b in the sync chain now, users want to replace b with c, they have to add c in sync chain first and then remove b. 
If they remove b first, they have to create a new sync chain between a and c

**Comment by cezaraugusto** [comment]
we currently don't check for the main device using words but the main device id instead.
also per sync v2 spec having two devices and removing one would reset sync as it is required to have two devices to keep sync.

closing per the above. please re-open if I'm mistaken
