### ISSUE TITLE
`snowflake` bridge should read `Snowflake`

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#25294]
## Description 

`snowflake` bridge should read `Snowflake`

## Steps to Reproduce

   1. install `1.44.79`
   2. launch Brave
   3. open `brave://settings/privacy`
   4. toggle `Use Bridges` to `Enabled` / `On`
   5. look at the values for `Select a built-in bridge`

## Actual result:

`snowflake`

<img width="1196" alt="Screenshot 2022-09-08 at 9 42 18 AM" src="https://user-images.githubusercontent.com/387249/189181891-b6f8fd6d-3ea2-4c62-905a-15b212165b8b.png">

## Expected result:

`Snowflake` - looks like it's a proper noun:

<img width="1312" alt="Screenshot 2022-09-08 at 9 49 37 AM" src="https://user-images.githubusercontent.com/387249/189181541-8e0272e9-c5fe-4de7-be70-57223ac96213.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.44.79 Chromium: 105.0.5195.102 (Official Build) beta (x86_64)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | macOS Version 13.0 (Build 22A5331f)

cc @rebron @boocmp

**Comment by kjozwiak** [comment]
The above requires `1.44.89` or higher for `1.44.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.44.92 Chromium: 105.0.5195.136 (Official Build) beta (x86_64)
-- | --
Revision | 872774b783d0e674186a3adcd2f92e7aa22a219c-refs/branch-heads/5195_124@{#4}
OS | macOS Version 11.7 (Build 20G817)

#### Confirmed it now reads `Snowflake`

<img width="1312" alt="Screen Shot 2022-09-19 at 10 46 29 AM" src="https://user-images.githubusercontent.com/387249/191081271-3933339a-9dab-4d0f-82ae-57eface46483.png">
