### ISSUE TITLE
Fix nft network selector styling

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#25307]
- Network selector dropdown button text is wrapping
- When network selector dropdown is opened, some elements from buy-send-swap are shown above the selector.

#### Network selector button text wrapping

<img width="1266" alt="Network selector text wrapping" src="https://user-images.githubusercontent.com/48117473/189311169-ffcfd841-a72d-4c10-802c-4d6c9b746633.png">

#### Network selector dropdown stacked below buy-send-swap

<img width="300" alt="Network selector stacked below other elements" src="https://user-images.githubusercontent.com/48117473/189309855-da4945ae-2813-4bcd-b3ad-f57df34600f4.png">

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (64-bit) 
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | Linux

- Verified steps from issue description
- Verified networks selector is shown correctly
- Verified none of the elements form Buy/Send/Swap widget shows up on the network dropdown 
![image](https://user-images.githubusercontent.com/17010094/195661809-d26a88a9-6f23-40f0-885a-570abb39e6b7.png)


------------------------
Verification passed on

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (64-bit) 
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | Windows 11 Version 21H2 (Build 22000.978)

- Verified steps from issue description
- Verified networks selector is shown correctly
- Verified none of the elements form Buy/Send/Swap widget shows up on the network dropdown 
![image](https://user-images.githubusercontent.com/17010094/195660043-4db053c7-8489-411f-82c7-87bb0d17f61b.png)


------------------------
Verification passed on

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (arm64)
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from issue description
- Verified networks selector is shown correctly
- Verified none of the elements form Buy/Send/Swap widget shows up on the network dropdown 
![image](https://user-images.githubusercontent.com/17010094/195661441-6cb07650-bef6-4473-83c8-4ecc08e3c41c.png)
