### ISSUE TITLE
www.ulta.com checkout doesn't work due to fingerprinting.

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#25309]
## Description 
Unable to go through checkout  on https://www.ulta.com

## Steps to Reproduce

   1. Open `https://www.ulta.com/featured/50off_jaclyn_cosmetics_highlighters?N=7vzezd&Ns=product.bestseller%7C1`
   2. Add an item to Bag
   3. Click on top right to view cart
   4. Click on `Secure Checkout`

## Actual result:
Doesn't forward to checkout, when clicking on the red `Secure Checkout` button.
![checkout-console](https://user-images.githubusercontent.com/1659004/189350883-65b0c0e5-6034-429c-b4bd-bb98a0473f63.png)
## Expected result:
Let user go through checkout process

## Reproduces how often: 

With default shields,

## Brave version (brave://version info)
`[Version 1.45.35 Chromium: 105.0.5195.102 (Official Build) nightly (64-bit)`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes 
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel?  Tes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes  (Fingerprinting specifically)
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of (Safari)?  No.

## Miscellaneous Information:
Disabling Fingerprinting fixes this. Also Safari works without issue.

**Comment by pes10k** [comment]
The issue is with Ulta not accepting Brave's randomized weight on accept-language (disabing language based fingerprinting protections fixes the issue), despite Brave's randomized weight being valid by the spec

Short term, @ryanbr will reach out to Ulta and see if (fingers crossed) they'll fix their busted stuff.  If not, @pilgrim-brave will add an exception to not apply randomization for ulta.

Medium term, we might create a new component to allow us to ship exceptions to users faster

**Comment by LaurenWags** [comment]
@pilgrim-brave @pes10k can this please be marked `QA/Yes` or `QA/No` as appropriate? If `QA/Yes`, let's make sure there's a test plan as well if the STR aren't sufficient. Thanks!

cc @rebron @kjozwiak

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.46.76 Chromium: 107.0.5304.62 (Official Build) beta (x86_64)
-- | --
Revision | 1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942}
OS | macOS Version 11.7 (Build 20G817)

### Steps:
1. installed `1.46.76`
2. launched Brave
3. loaded `ulta.com`
4. searched for `jacelyn cosmetics highlighters` (`https://www.ulta.com/ulta/a/_/Ntt-jaceyln%20cosmetics%20highlighters/Nty-1?Dy=1&ciSelector=searchResults`)
5. clicked on `https://www.ulta.com/p/accent-light-highlighter-pimprod2022958` and added to to my cart/bag
6. clicked on `Secure checkout`

#### Confirmed I was taken to the secure-checkout page, to fill out payment & shipping details, successfully (did not complete purchase, of course).

example | example | example | example
---------|----------|---------|---------
<img width="1408" alt="Screen Shot 2022-10-24 at 2 42 40 PM" src="https://user-images.githubusercontent.com/387249/197636440-3acf0d35-1bb8-4064-9111-1fce4e7cbe7f.png"> | <img width="1408" alt="Screen Shot 2022-10-24 at 2 42 49 PM" src="https://user-images.githubusercontent.com/387249/197636536-985b71a9-5aa7-4924-a345-0aa7619dfb48.png"> | <img width="1408" alt="Screen Shot 2022-10-24 at 2 45 12 PM" src="https://user-images.githubusercontent.com/387249/197636537-02811006-f0ac-4a16-b1eb-d0c0a8991e4a.png"> | <img width="1565" alt="Screen Shot 2022-10-24 at 2 46 04 PM" src="https://user-images.githubusercontent.com/387249/197636538-c8a7bfdb-ac9c-4597-bdd8-102efea2021d.png">
