### ISSUE TITLE
Youtube Player not Loading on Watch2gether w2g.tv

### ISSUE THREAD

**Issue by Nex-Carter** [brave/brave-browser#25300]
## Description 
If i join a room with another person on the website Watch 2 gether i end up beeing unable to play the YT Videos since the last update.
The Scriptblockler blocks the YT scripts for no reason. And there is no way to actually allow the script by hand.

I would love to have like a "no script" option to allow scripts one by one and not only ALL OR NOTHING :(

## Steps to Reproduce

   1.  Create a Link for a WatchTogether session with a friend. ( https://w2g.tv/ )
   2.  Join the session.
   3.  "Allow" The other scripts via Brave Shield
   4. Look at the "javascript wasnt loaded" error and Brave still blocking the YT scripts

## Actual result:

https://abload.de/image.php?img=2022-09-0822_26_57-wa0yi9i.png

## Expected result:
Working YT player

## Reproduces how often: 
always

## Brave version (brave://version info)

1.43.89

**Comment by rebron** [comment]
cc: @ryanbr Can you take a look?

**Comment by ryanbr** [comment]
@Nex-Carter  still an issue? Modify scripts in shields will cause issues here, disabling script blocking in shields is best here.
