### ISSUE TITLE
Unable to claim UGP grants as source BAT logo is missing on brave://rewards page

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#2531]
## Description 
Unable to claim UGP grants as source BAT logo is missing on brave://rewards page

## Steps to Reproduce

   1. Open brave
   2. Enable Rewards
   3. Click on UGP grants button `CLAIM`

## Actual result:
Source BAT logo is missing. Unable to claim the grants.
![image](https://user-images.githubusercontent.com/38657976/49940845-ced8c700-ff06-11e8-8e51-975355e6835e.png)

## Expected result:
![image](https://user-images.githubusercontent.com/38657976/49940969-34c54e80-ff07-11e8-8301-d7fda592b437.png)

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 0.58.12 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Windows

### Reproducible on current release: No
- Does it reproduce on brave-browser dev/beta builds? No

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional Information
@brave/legacy_qa @evq

**Comment by NejcZdovc** [comment]
cc @petemill could be this related to webpack changes?

**Comment by LaurenWags** [comment]
Reproduces on macOS

Brave | 0.58.12 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

![screen shot 2018-12-13 at 8 49 55 am](https://user-images.githubusercontent.com/28145373/49942728-27cb3f80-feb4-11e8-9b9b-604af5b3762c.png)

**Comment by NejcZdovc** [comment]
not sure what is happening, but this one I think is related https://github.com/brave/brave-browser/issues/2523

**Comment by rebron** [comment]
@petemill assuming brave/brave-core#1011 will fix this issue?

**Comment by NejcZdovc** [comment]
should be fixed with https://github.com/brave/brave-core/pull/1011

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.58.14 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Mac OS X

* Verified STR from description (using staging environment)
