### ISSUE TITLE
Promoting the Snowflake extension in Brave

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#25315]
Now that Brave has [support for Tor bridges](https://github.com/brave/brave-browser/issues/1138), we should try to help build bridge network capacity by making it easy for users to run the [Snowflake extension](https://snowflake.torproject.org/).

There is a [detailed spec](https://docs.google.com/document/d/1eNUt6-dzs1DlUcCK6oWJTI51pjzIG8E3NOJ_Q_uhx88/edit#) for this, but the basic idea is a new toggle in the _Tor windows* section of `brave://settings/privacy`:

> **Volunteer to help others connect to the Tor network [ OFF / on ]**
> Enable the Snowflake extension to allow users in censored countries to connect to the Tor network via your network connection. [Learn more](https://support.brave.com/hc/en-us/articles/9059440641421).

**Comment by LaurenWags** [comment]
@fmarier @boocmp looked at the document in https://github.com/brave/brave-core/pull/15907#issue-1445565110 but wasn't entirely clear on the test plan - some items are mentioned as optional, where they implemented? Document is still in draft status as well. 

Any clarifications/additional information on what needs to be verified would be appreciated, thanks!

**Comment by fmarier** [comment]
@LaurenWags I've updated the status of the doc (I completely forgot to change that, sorry!) and marked the optional section around the NTP notice as "not for MVP".

I've looked through the doc again and it should be a good reflection of what got implemented now.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using 

Brave | 1.47.121 Chromium: 108.0.5359.99 (Official Build) beta (64-bit)
-- | --
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | Windows 11 Version 21H2 (Build 22000.1219)

- Install 1.47.121
- launch Brave

#### Case 1: Enable Brave toggle and enable `Snowflake` in the extension
<details>

1. open `brave://settings/privacy` in a new-tab
2. `Volunteer to help others connect to the Tor network` toggle is available with `OFF` as a default
3. enable the toggle `Volunteer to help....` 
4. confirmed `Snowflake` extension has been added to Brave with a popup  `Snowflake has been added to Brave` text in the toolbar
5. click on Extensions puzzle 
6. Extensions popup displayed with the `Snowflake` extension shown
7. click `Snowflake` to enable Snowflake
8. `Your Snowflake is ready to help users circumvent censorship` text with user count popup is displayed
9. open `brave://extensions` in a new-tab
10. `Snowflake` extension is shown

step 2|step 3|step 4|step 7|step 8|step 9-10
-----|-----|------|-----|-----|-----
<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/206758318-151075e3-301a-44f4-bcd9-2303eecd934a.png">|<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/206758830-1beaf5a5-fd46-447b-a574-1fdccd39bbdb.png">|<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/206759848-9a6b71b6-a690-4ab7-b8cd-a1d4d3802840.png">|<img width="459" alt="image" src="https://user-images.githubusercontent.com/98358127/206761204-c1600203-45bf-4809-b805-a56fb5a7ff0a.png">|<img width="468" alt="image" src="https://user-images.githubusercontent.com/98358127/206790870-9185a06e-a23d-4c79-8adc-14cad07f21f9.png">|<img width="460" alt="image" src="https://user-images.githubusercontent.com/98358127/206760929-11d18698-a521-4e35-898f-7ecc926d1aef.png">

Snowflake extension UI
<details>

Light-1|Light-2|Dark-1|Dark-2
----|-----|----|-----
<img width="468" alt="image" src="https://user-images.githubusercontent.com/98358127/206798127-ce71a4ff-0180-4e67-bf97-3babd97daa11.png">|<img width="469" alt="image" src="https://user-images.githubusercontent.com/98358127/206798153-cf303c57-620e-4b58-85ac-afb9b594ff46.png">|<img width="469" alt="image" src="https://user-images.githubusercontent.com/98358127/206798182-af9fdac6-8b51-4e97-9068-cbb47b83e624.png">|<img width="468" alt="image" src="https://user-images.githubusercontent.com/98358127/206798248-8519039d-e450-4329-9e9c-124569335889.png">

</details>
</details>

#### Case 2: Enable Brave toggle and disable `Snowflake`  in the extension
<details>

1. click on `Snowflake`  in the  Extensions popup which is in enabled state
2. disable the `Enabled` toggle
3. observe no connections to the host snowflake host `https://snowflake-broker.freehaven.net` 
4. visually `Snowflake` icon shown gray
5. the text reads `Snowflake is off`

###Confirmed `Snowflake` extension state shows disabled

step 1|step 3|result
-----|------|-------
<img width="453" alt="image" src="https://user-images.githubusercontent.com/98358127/206763924-72c5ce8b-2f3f-43b4-a051-3bbc7e6c65b0.png">|<img width="589" alt="image" src="https://user-images.githubusercontent.com/98358127/206798616-49dc5575-e9a5-426a-83d9-4bd1b3d88bb6.png">|<img width="453" alt="image" src="https://user-images.githubusercontent.com/98358127/206763885-9e891393-e5fd-46c4-add4-4e4216eacb1e.png">
</details>

#### Case 3: Remove `Snowflake` extension
<details>

1. open `brave://extensions`
2. click `Remove`
3. click `Remove`
6. open `brave://settings/privacy`
7. `Volunteer to help...` toggle is disabled

#### Confirmed `Snowflake` extension is removed

step 1-2|step 3|step 5|result
-----|-------|--------|-------
<img width="461" alt="image" src="https://user-images.githubusercontent.com/98358127/206765267-2992b9d5-72ae-4757-96e3-b3242eed5cb9.png">|<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/206765307-a6c9fdeb-624c-4beb-966c-3050167aea8f.png">|<img width="457" alt="image" src="https://user-images.githubusercontent.com/98358127/206765377-26a8345f-5894-4dc6-bab9-3ee08cd972bb.png">|<img width="462" alt="image" src="https://user-images.githubusercontent.com/98358127/206765353-402e70eb-7489-46e8-9076-909058d09883.png">
</details>


#### Case 4 : Disconnect/reconnect  WiFI during Snowflake extension installation
<details>

1. New profile
2. launch Brave
3. open `brave://settings/privacy` in a new-tab
4. enable `Volunteer to help others connect to the Tor network` 
5. disable WiFi
6. close the popup `Snowflake has been added to Brave` 
7. click `Snowflake` in the extension
8. It shows `Snowflake is off` along with the icon shows gray
9. enable WiFI
10. click Retry button

#### Confirmed `Snowflake` bridge is successfully connected

step 3|step 5|step 7|step 10
-----|--------|-------|---------
<img width="464" alt="image" src="https://user-images.githubusercontent.com/98358127/206810336-f0bb4a1d-aace-4da4-8fd2-638ef2f7a25e.png">|<img width="374" alt="image" src="https://user-images.githubusercontent.com/98358127/206810103-6586d542-72c0-46a7-b569-e3fde22e54ba.png">|<img width="674" alt="image" src="https://user-images.githubusercontent.com/98358127/206809956-5f943388-7116-41cf-ae56-85b28ad18628.png">|<img width="462" alt="image" src="https://user-images.githubusercontent.com/98358127/206812480-1ba61788-b566-40a3-9385-c445dced2d8e.png">|<img width="464" alt="image" src="https://user-images.githubusercontent.com/98358127/206811524-cf68ff51-eb5d-40d3-89aa-1cd90ba0bea7.png">|<img width="464" alt="image" src="https://user-images.githubusercontent.com/98358127/206812390-10165901-a2a5-4fab-9e0a-5f642446a808.png">
</details>

#### Case 5: HTTPS Connection
<details>

Pre-req:  Disable Snowflake connection in the Brave extensions

1. Open Charles
2. enable Snowflake extension
3. observe the network connections to snowflake host `https://snowflake-broker.freehaven.net` 

pre-req|step 2|step 3
-----|-----|------
<img width="461" alt="image" src="https://user-images.githubusercontent.com/98358127/206795855-a5861b6d-5667-4b83-bfb0-b6b2186947c8.png">|<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/206794864-dce0ff1b-3283-44e4-9bd1-b862613171aa.png">|<img width="551" alt="image" src="https://user-images.githubusercontent.com/98358127/206794664-73820ae5-4780-4ec3-9ae1-49128c8d2898.png">

</details>

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.47.121 Chromium: 108.0.5359.99 (Official Build) beta (x86_64)
-- | --
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | macOS Version 13.1 (Build 22C65)

Case 1
<details>

</details>
Case 2
<details>

</details>
Case 3
<details>

</details>
Case 4
<details>

</details>
Case 5
<details>

</details>
Case 6
<details>

</details>
Case 7
<details>

</details>
Case 8
<details>

</details>
