### ISSUE TITLE
Crash report - Brave News

### ISSUE THREAD

**Issue by ilpinguinoimmortale** [brave/brave-browser#25312]
## Steps to reproduce 

   1.  Open the browser (note that this happens if you have Brave News activated)
   2.  Scroll down
   3.  Crash!

## Issue reproduces how often -> Everytime 

- Can you reproduce this issue with the current Play Store version? Yes.
- Can you reproduce this issue with the current Play Store Beta version? Idk
- Can you reproduce this issue with the current Play Store Nightly version? Idk

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 11 (MIUI 12.5.5)
   
### Additional information
Another Brave News bug: News settings' banner covers the Privacy Report.![IMG_20220909_153724.jpg](https://user-images.githubusercontent.com/108210645/189362970-09aace67-0ac8-43d1-bc50-0320529def4c.jpg)

**Comment by kjozwiak** [comment]
The above will require `1.43.93` or higher for `1.43.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.43.93 x64 build
- Verified steps from issue description
- Verified scrolling down to the last feed item doesn't crash the browser


https://user-images.githubusercontent.com/17010094/190161661-fedc5a4d-bff4-4ba2-b58c-c9f03bd172d8.mp4
