### ISSUE TITLE
Remove last sentence in default tipping banner creator description text  (Sept 2022)

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#25313]
![image](https://user-images.githubusercontent.com/11497541/189379516-603bd2bd-32ed-42c3-bd2d-2b60c7d48359.png)

Remove final sentence that says "Verified creators get paid for their tips during the first week of each calendar month." 

Non-vBAT tips are instant and not paid out/settled monthly, for example, so this sentence is inaccurate.

**Comment by Miyayes** [comment]
cc: @sujitacharya2005 on Android.

**Comment by mkarolin** [comment]
**Test Plan**:
1. Navigate to a website (e.g. cnn.com)
2. Click on the Rewards icon and then click on `Send tip`
3. Observe the tipping banner doesn't have the text "Verified creators get paid for their tips during the first week of each calendar month." any more.

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
Brave | 1.45.75 Chromium: 106.0.5249.65 (Official Build) beta (64-bit)
-- | --
Revision | 3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}
OS | Windows 10 Version 21H2 (Build 19044.2006)
```
- Ensured that the last sentense **"Verified creators get paid for their tips during the first week of each calendar month."** is removed from the tipping banner

1.44.5 | 1.45.x
-- | --
![image](https://user-images.githubusercontent.com/38657976/192711630-9eb99141-854d-4e8b-9e35-de0dba53e9e8.png) | ![image](https://user-images.githubusercontent.com/38657976/192711877-4495bd60-36b6-40af-b4b0-a18ab972432f.png)
