### ISSUE TITLE
brave-translate does not handle Chinese

### ISSUE THREAD

**Issue by cc19264997** [brave/brave-browser#25327]
Hello, why did the browser's translation function not respond? I am a Chinese user, and I couldn't translate when I opened VPN! what should I do?

I downloaded the Crx translated by Google, but I still can't translate the webpage content!

I hope you can answer it for me and thank you again!

**Comment by diracdeltas** [comment]
you may need to restart, see https://github.com/brave/brave-browser/issues/25170#issuecomment-1242154933

**Comment by atuchin-m** [comment]
@cc19264997 to use the build-in translation engine please remove or disable Google Translate extension.
If you have the extension it still be used instead of the build-in implementation.

**Comment by cc19264997** [comment]
> you may need to restart, see [#25170 (comment)](https://github.com/brave/brave-browser/issues/25170#issuecomment-1242154933)


Hello, but he still can't translate Chinese!

**Comment by atuchin-m** [comment]
Chinese will be supported in here: https://github.com/brave/brave-browser/issues/24303

**Comment by bsclifton** [comment]
Closing as a duplicate of https://github.com/brave/brave-browser/issues/24303 - @cc19264997 you can subscribe to that issue for updates 😄 Thanks!
