### ISSUE TITLE
Tipping icons are present on tipping sites without opting into Rewards

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#25320]
## Description 

With a fresh Brave browser navigating to one of the tipping site before opting into Rewards results in tipping icons showing on the site.

## Steps to Reproduce

   1. Start with a fresh Brave profile
   2. Navigate to a tipping website (e.g. https://twitter.com/brave/status/1557414715600551936)
   
## Actual result:

Observe Tip icons shown (if they are not reload the page once and they will show up)

## Expected result:
Tip icons aren't shown because the user has not opted into the rewards yet

## Reproduces how often: 

Easy

## Brave version (brave://version info)

1.45.35 Chromium: 105.0.5195.102 (Official Build) nightly (64-bit) 

cc: @emerick

**Comment by emerick** [comment]
Based on a quick look, it seems like `RewardsServiceImpl::EnableGreaseLion()` enables Greaselion's `REWARDS` precondition whether or not Rewards is currently enabled (this is probably a holdover from Rewards Everywhere). I think we should fix that, but it also looks like that code has been that way for a long time. I think what changed here is that the Rewards service is running at all when we visit Twitter; that doesn't seem like it should be the case.

**Comment by diracdeltas** [comment]
>  I think what changed here is that the Rewards service is running at all when we visit Twitter; that doesn't seem like it should be the case.

i am a bit concerned about the privacy/etc. implications of this. could be p1 or p2 depending on what exactly it means for rewards service to be running. if users are not opted into rewards, they haven't consented to rewards-related network requests, for instance.

cc @rebron

**Comment by emerick** [comment]
I looked at this a little bit closer and the Ledger service is not actually running; sorry for the false alarm on that front. At the moment, it appears to be a problem with the Greaselion service or perhaps fallout from some of our recent refactoring. But I just confirmed that visiting Twitter does not start ledger up.

**Comment by Miyayes** [comment]
I think this is expected, and was a core part of Brave Rewards Everywhere (BRE). Tip icons are intentionally shown on sites like Twitter, even prior to Brave Rewards opt-in, to increase visibility and knowledge of Brave Rewards. When users press on the Tip icon, it opens the tipping banner, and allows users to opt-in to Brave Rewards, where "opt-in" means to generate a Brave Rewards wallet.

Also, see this issue and conversation, the last time this sort of issue arose: https://github.com/brave/brave-browser/issues/14277
