### ISSUE TITLE
Send the tab to mobile device doesn't work from macOS to iOS

### ISSUE THREAD

**Issue by chakrademorue** [brave/brave-browser#25324]
## Description 
The “send to your devices” option appears in my address bar. But when I click on it, “Sending in progress” is displayed in the address bar but nothing happens on the mobile device.
However, I did the test with 2 Brave profiles, each synchronized with a different mobile device: an iPhone and an iPad.
Each time, I leave the mobile browser on iPad or iPhone open, but nothing happen.

## Steps to Reproduce
   1. Open Brave on my mobile device, connected and synced to same profile as desktop
   2. Click on "Send to your devices" on desktop browser
  

## Actual result:
Nothing happens except the message "Sending in progress" in the address bar

## Expected result:
Opening the current desktop's page on mobile browser

## Reproduces how often: 
Every time

## Version/Channel Information:
Version 1.43.89
Profile 1 : MacBook Pro (Intel - OS 12.5.1) + iPhone XS (OS 15.6.1)
Profile 2 : MacBook Pro (Intel - OS 12.5.1) + iPad Air 4 (OS 15.6)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No > it works perfectly on chrome, with same extensions.

## Miscellaneous Information:
The “handoff” icon of Brave appears in my dock for the iPhone (that uses the same iCloud account as my MacBook). When I click on the icon, the current webpage displayed on my iPhone is opening in my desktop browser.

**Comment by AlexeyBarabash** [comment]
Related Brave iOS PRs
https://github.com/brave/brave-ios/pull/5809 and the follow-up https://github.com/brave/brave-ios/pulls?q=is%3Apr+sync+tab+is%3Aclosed

@Floooowk are you still facing the issue?
