### ISSUE TITLE
Linux installation instructions don't work if you set your UMASK to 027

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#25322]
After running the `curl` command in https://brave.com/linux/#debian-ubuntu-mint, I ended up with a `/usr/share/keyrings/brave-browser-archive-keyring.gpg` with 640 permissions and that caused this error:

```
W: GPG error: https://brave-browser-apt-release.s3.brave.com stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A8580BDC82D3DC6C
E: The repository 'https://brave-browser-apt-release.s3.brave.com stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://ppa.launchpadcontent.net/fmarier/ppa/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```
So I guess we should add a `chmod a+r /usr/share/keyrings/brave-browser-archive-keyring.gpg` step after the `curl` command to make sure users don't run into this problem.

**Comment by fmarier** [comment]
cc @wknapik

**Comment by wknapik** [comment]
Should we complicate our already complicated installation instructions for the sake of a very small group of people who decided to customize their umask?

This is not a change that a newbie would (have to) make, so I think it's safe to expect that the user understands the consequences.

I also don't recall seeing `chmod a+r` in instructions like this in other projects.

**Comment by suhasabhishek** [comment]
@wknapik Can I work on this?

**Comment by wknapik** [comment]
If it was commonplace to cover the custom umask scenario in installation instructions for Linux, I'd be happy to change our documentation, but given that it's not, my thinking is that we should stick to what we have. That's my 2 cents, perhaps others will see it differently.
