### ISSUE TITLE
Add ability to import From Google Chrome for developers

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#25335]
## Description 
Brave importer should look for Dev profiles for Google Chrome installs

## Steps to Reproduce

   1. Download/install Chrome for developers https://www.google.com/chrome/dev/
   2. Have a profile with history, bookmarks, etc
   3. Try to import this profile in Brave

## Actual result:
Profile won't show in import drop down

## Expected result:
Profile should show in drop down

## Reproduces how often: 
100%

**Comment by LaurenWags** [comment]
@stephendonner @MadhaviSeelam let's be sure to check this one on Windows and macOS 👍🏻

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 




Brave | 1.45.79 Chromium: 106.0.5249.65 (Official Build) dev (x86_64)
-- | --
Revision | 3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}
OS | macOS Version 11.7 (Build 20G817)


### Prerequisite Steps:
<details>

`Google Chrome Dev` installed, seeded the following two profiles:
* `Unique User 1`
* `Unique User 2`

Both of which have 2 (or more):
* bookmarks
* extensions
* browsing history
* saved passwords

</details>

Case 1: `brave://welcome` import - `.`
<details>

### Steps:
1. installed `1.45.77`
2. launched Brave
3. clicked `Let's go ->`
4. selected `Chrome Dev Unique User 1`
5. clicked on `Import`
6. clicked `Done` 

#### Confirmed the following were successfully imported:
* bookmarks/favorites
* extensions
* browsing history
* saved passwords

#### `Unique User 1`

`brave://welcome` | `bookmarks` | `extensions` | `history` | `passwords`
-------------|---------------|----------|-------------|--------


#### `Unique User 2`

`brave://welcome` | `bookmarks` | `extensions` | `history` | `passwords`
-------------|---------------|----------|-------------|-----------


</details>

Case 2: `Brave` -> `Import Bookmarks and Settings...` - `.`
<details>

### Steps:

1. installed `1.45.77`
2. launched Brave
3. clicked OS/app-level `Brave` menu item -> `Import Bookmarks and Settings`
4. selected `Chrome Dev Unique User 1`
5. clicked on `Import`
6. clicked `Done`

Confirmed the following were successfully imported:

- bookmarks/favorites
- extensions
- browsing history
- saved passwords 

`brave://settings/importData`, 1 | `brave://settings/importData`, 2
------------------------------|--------------


`bookmarks` | `extensions` | `history` | `passwords`
--------------|---------------|-----------|------------





</details>

Case 3: Main menu -> `Bookmarks` -> `Import Bookmarks and Settings...` - `.`
<details>

This entrypoint (which redirects to `brave://settings/importData`)  is invoked by (and tested in) the `Case 2: Brave -> Import Bookmarks and Settings` test

</details>

Case 4: `brave://settings/importData` - `.`
<details>

This entrypoint is invoked by (and tested in) the `Case 2: Brave -> Import Bookmarks and Settings...` test

</details>

Case 5: Deselection of two (2) import types - `.`
<details>

### Steps:

1. installed `1.45.77`
2. launched Brave
3. clicked OS/app-level `Brave` menu item -> `Import Bookmarks and Settings`
4. selected `Chrome Dev Unique User 1`
5. clicked on `Import`
6. de-selected `Browsing history`
7. de-selected `Saved passwords`
8. clicked `Import`
9. clicked `Done`


#### Confirmed the following were successfully imported:

- bookmarks
- extensions

#### Confirmed the following were *NOT* imported:

- browsing history (entries in screenshot are from imported extensions opening their "welcome" tabs)
- saved passwords 




`brave://settings/importData` | `bookmarks` | `extensions` | `history` | `passwords`
--------------|---------------|-----------|------------|---------


</details>

Case 6: Import a single category type - `.`
<details>

### Steps:

1. installed `1.45.77`
2. launched Brave
3. clicked OS/app-level `Brave` menu item -> `Import Bookmarks and Settings`
4. selected `Chrome Dev Unique User 1`
5. clicked on `Import`
6. de-selected `Browsing history`
7. de-selected `Favorites/Bookmarks`
8. de-selected `Extensions`
9. clicked `Import`
10. clicked `Done`

#### Confirmed the following was imported:
* saved passwords

#### Confirmed the following were *not* imported:
* browsing history
* favorites/bookmarks
* extensions

`brave://settings/importData` | `bookmarks` | `extensions` | `history` | `passwords`
--------------|---------------|-----------|------------|---------


</details>

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.45.84 Chromium: 106.0.5249.91 (Official Build) beta (64-bit)
-- | --
Revision | fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}
OS | Windows 11 Version 21H2 (Build 22000.978)
```

### Prerequisite Steps:
<details>

`Google Chrome Dev` installed, seeded the following two profiles:
* `Person 1`  - 
    - bookmarks/favorites
    - extensions
    - browsing history
    - saved passwords
* `Person 2`
    - bookmarks/favorites
    - extensions
    - browsing history

</details>

Case 1: `brave://welcome` import - `PASSED`
<details>

### Steps:
1. installed `1.45.84`
2. launched Brave
3. clicked `Let's go ->`
4. selected `Chrome Dev Person 1`
5. clicked on `Import`
6. clicked `Done` 

#### Confirmed the following were successfully imported:
* bookmarks/favorites
* extensions
* browsing history
* saved passwords

#### `Person 1`

`brave://welcome-1` |`brave://welcome-2`|`bookmarks` | `extensions` | `browsing history` | `saved passwords`
-------------|---------------|----------|-------------|--------|---------
<img width="461" alt="image" src="https://user-images.githubusercontent.com/98358127/193705533-e0aa9d95-fc23-4fc7-ba42-9650730e750e.png">|<img width="460" alt="image" src="https://user-images.githubusercontent.com/98358127/193705584-06516eb6-7a12-41fe-9d14-f899879ede97.png">|<img width="461" alt="image" src="https://user-images.githubusercontent.com/98358127/193705648-458e3060-e8e1-481d-a284-1febb51291af.png">|<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/193705681-53de9dad-8e60-45e7-b1a8-db51023d5195.png">|<img width="457" alt="image" src="https://user-images.githubusercontent.com/98358127/193705769-4da2470c-c9db-4578-ba56-e1bd934e783f.png">|<img width="460" alt="image" src="https://user-images.githubusercontent.com/98358127/193705823-7905fad6-50f3-414f-8195-b59c194c2bce.png">
