### ISSUE TITLE
sometimes QR codes and words not displayed for sync

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#2533]
## Description 
First, second, and third attempts to create a sync chain were unsuccessful because QR code and words were not displayed in the UI. I was using a clean profile each time. The fourth time/profile, I was able to see QR code and words.

Similar to https://github.com/brave/brave-browser/issues/2537 

## Steps to Reproduce

   1. Clean install of 0.58.12
   2. Go to hamburger menu and choose Brave Sync
   3. Click on Start a new sync chain
   4. Choose Phone/Tablet button or Computer button

## Actual result:
No QR code or words. Unsure if something went wrong - there's no error message to user. 

![screen shot 2018-12-13 at 8 55 37 am](https://user-images.githubusercontent.com/28145373/49944496-85fa2180-feb8-11e8-9b24-60adadc300e2.png)

![screen shot 2018-12-13 at 9 01 10 am](https://user-images.githubusercontent.com/28145373/49944523-93afa700-feb8-11e8-8372-63c3bb04eb83.png)

## Expected result:
QR code/words to be displayed as appropriate. OR an error message indicating something is wrong/to try again later/whatever as appropriate.

## Reproduces how often: 
Unsure

## Brave version (brave://version info)

Brave | 0.58.12 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? unsure

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by LaurenWags** [comment]
Seen by @AlexeyBarabash as reported here https://github.com/brave/brave-core/pull/1019#issuecomment-446953927
And I just experienced it again.

**Comment by btlechowski** [comment]
Reproduced on Windows 7 

Brave | 0.58.12 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Windows 7

**Comment by kjozwiak** [comment]
Seems like the issue is intermittent but does happen often enough. I reproduced it on my second clean install. The first once worked correctly but the second install was missing the QR code/chain code.

<img width="758" alt="screen shot 2018-12-13 at 11 03 37 am" src="https://user-images.githubusercontent.com/2602313/49951030-01fb6600-fec7-11e8-9f8c-0db57f631b8c.png">

<img width="754" alt="screen shot 2018-12-13 at 11 03 47 am" src="https://user-images.githubusercontent.com/2602313/49951040-07f14700-fec7-11e8-8895-fb97384739f7.png">

Reproduced using the following:

Brave | 0.58.12 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

**Comment by GeetaSarvadnya** [comment]
Not seeing both QR code and secrete code word on Bravebeta `0.59.8`
![image](https://user-images.githubusercontent.com/38657976/49996385-e078a800-ffb4-11e8-93f9-27355f17cac7.png)
![image](https://user-images.githubusercontent.com/38657976/49996410-ed959700-ffb4-11e8-820a-29a6f6e1f6f1.png)


Please note, it was working in the morning. I have tested one defect also, all of sudden server stops responding.

**Comment by GeetaSarvadnya** [comment]
Issue is still reproducible on Brave beta `0.59.12 ` Hence reopening the issue.

QR code missing:
![image](https://user-images.githubusercontent.com/38657976/50405874-2ae1fc00-07e1-11e9-841f-f7deae3f6d3c.png)

Code word missing:
![image](https://user-images.githubusercontent.com/38657976/50405878-3b927200-07e1-11e9-9443-ff955d984d24.png)

**Comment by GeetaSarvadnya** [comment]
Issue is reproducible on Linux as well - `0.59.12`

QR code missing:

![image](https://user-images.githubusercontent.com/38657976/50446592-bf607180-093b-11e9-9b0a-7ae065d3d39d.png)

Code word  missing:

![image](https://user-images.githubusercontent.com/38657976/50446608-d2734180-093b-11e9-92d2-32bc93a546ec.png)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.2 x64` using the following build:

Brave | 0.59.20 Chromium: 72.0.3626.28 (Official Build) beta(64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Mac OS X
