### ISSUE TITLE
Remove code to suggest installing Google Translate Extension

### ISSUE THREAD

**Issue by atuchin-m** [brave/brave-browser#25347]
After [enabling the new Translate feature by default](https://github.com/brave/brave-browser/issues/25289) we can remove the code to install Goggle Translate extension (including the bubble).

The behaviour for the existing Google Translate extension users is discussed in https://github.com/brave/brave-browser/issues/24715

**Comment by atuchin-m** [comment]
Test plan:
1. Sanity check that build-in translation works (any desktop platform + android);
2. Check that translation bubble and the icon in the omnibox is unchanged (any desktop platform); 
3. Check that `Enable internal translate engine (brave-translate-go)` flag is removed from brave://flags (desktop + android)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.45.77 Chromium: 106.0.5249.65 (Official Build) beta (64-bit)
-- | --
Revision | 3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}
OS | Windows 11 Version 21H2 (Build 22000.978)
```
Case 1: Verified Built-in translation works as expected and additionally not prompted to install `Google Translate` extension

Ex1|Ex2
---|---
<img width="462" alt="image" src="https://user-images.githubusercontent.com/98358127/192904730-99773b95-45e8-47fb-ad9c-c5577cdd9f23.png">|<img width="466" alt="image" src="https://user-images.githubusercontent.com/98358127/192904752-cfd71ff9-9eae-46a8-a71b-7272369cce28.png">

Case 2: Verified `translation bubble` and the icon in the omnibox displayed as expected

<img width="462" alt="image" src="https://user-images.githubusercontent.com/98358127/192904812-c531b18e-0976-4271-9101-7156b7cd9e7d.png">

Case 3: Verified `#brave-translate-go` flag is removed from `brave://flags`

<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/192904933-c003ebd8-3353-4a07-b639-ab840726fe5a.png">

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.45.90 Chromium: 106.0.5249.103 (Official Build) beta (64-bit)
-- | --
Revision | 182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}
OS | Ubuntu 18.04 LTS

#### Case 1: in-build translation
<details>

![image](https://user-images.githubusercontent.com/34715963/196370743-2d78ff18-08f5-41ec-a580-28e3b2afc772.png)
![image](https://user-images.githubusercontent.com/34715963/196370961-bc1a7d5b-f23b-42b7-89c1-a4b36d5d6f75.png)


</details>

#### Case 2: translation "bubble" and icon
<details>

![image](https://user-images.githubusercontent.com/34715963/196371222-5590057c-4b9f-4c2b-a8ac-91367beb9e0f.png)


</details>

#### Case 3: confirmed that the `brave-translate-go` flag is removed from `brave://flags`

<details>

![image](https://user-images.githubusercontent.com/34715963/196371994-7cb78f7e-d46c-4951-9142-5334257a0380.png)


</details>

Confirmed I was not prompted to install `Google Translate`, and Brave Translate worked without any additional setup

**Comment by GeetaSarvadnya** [comment]
Verification **In progress** on `Samsung Galaxy Tab A7` version 12 running `Bravemonoarm64.apk_1.45.108`

#### Case 1: in-build translation
<details>


</details>

#### Case 2: translation "bubble" and icon
<details>




</details>

#### Case 3: confirmed that the `brave-translate-go` flag is removed from `brave://flags`

<details>




</details>

Confirmed I was not prompted to install `Google Translate`, and Brave Translate worked without any additional setup
