### ISSUE TITLE
New tab title jumps

### ISSUE THREAD

**Issue by VMBindraban** [brave/brave-browser#2534]
## Description 

When opening a new tab the title of the tab changes to `chrome://newtab` and then back to `New tab`.

## Steps to Reproduce

   1. Open a new normal or private tab/window

## Actual result:

![kapture 2018-12-13 at 15 19 52](https://user-images.githubusercontent.com/2269400/49944395-9b883f00-feea-11e8-8a5c-21a624330c6e.gif)

## Expected result:
Title shouldn't change.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.57.18 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No.
- Is the issue reproducible on the latest version of Chrome? No.

**Comment by srirambv** [comment]
This is expected. If you type in `brave://newtab` or `chrome://newtab` it will still change the tab title to `NewTab`

**Comment by VMBindraban** [comment]
If i type `brave://newtab` it transforms `brave://newtab` to `New Tab`.
When i open a new tab it goes from `New Tab` to `chrome://newTab` to `new Tab` again.

**Comment by srirambv** [comment]
cc: @bbondy  for comment.

**Comment by bbondy** [comment]
seems like a valid issue to investigate to me

**Comment by srirambv** [comment]
Sorry for closing it prematurely. Added appropriate labels and milestone

**Comment by bsclifton** [comment]
I haven't seen this for a while and there haven't been any +1s. Closing as stale
