### ISSUE TITLE
Process "NO REGION" geo target endpoint response

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#25342]

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.46.83 Chromium: 107.0.5304.68 (Official Build) beta (64-bit)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/15267

<details>


</details>

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` & `Samsung Galaxy Tab S7` using the following build(s):

```
Brave	1.46.130 Chromium: 108.0.5359.62 (Official Build) (64-bit) 
Revision	041930a89a990cfab0315a2d9f20d6429a4a67cf-refs/branch-heads/5359@{#938}
OS	Android 12; Build/SP2A.220305.013
```

Test Plan: https://github.com/brave/brave-core/pull/15267#issue-1389953376

Case 1: `PASS`

<details>

1. Change locale to United States
2. Override geo-target endpoint response with {"country":"US", "region":"NO REGION"}
3. Start browser with ads enabled
4. Check that Regional ad relevance value is set to Disable

Example | Example
-|-
![screenshot-1669736846317](https://user-images.githubusercontent.com/17885425/204581306-419768a5-9507-4ad8-b7b4-9b32754a4a4e.png)|  ![screenshot-1669738577478](https://user-images.githubusercontent.com/17885425/204585775-375ea561-be58-4df0-9fa7-e5a0864f1c4c.png)


getState:
```
{
	"country": "US",
	"region": "NO REGION"
} 

```

</details>

Case 2: `PASS`

<details>

1. Change locale to United States
2. Override geo-target endpoint response with {"country":"CA", "region":"NB"}
3. Start browser with ads enabled
4. Check that Regional ad relevance is hidden
5. Close the browser
6. Change locale to Canada
7. Start browser
8. Check that Regional ad relevance is set to Auto detect

Example | Example
-|-
![screenshot-1669737412555](https://user-images.githubusercontent.com/17885425/204581637-e24a19cb-e0fb-450f-a314-ec10412b3f58.png) | ![screenshot-1669737919714](https://user-images.githubusercontent.com/17885425/204581639-238eb3eb-090e-4ad2-96c2-a90319e6bf82.png)
![screenshot-1669738881294](https://user-images.githubusercontent.com/17885425/204585812-ab2e8af5-c3ef-473d-85c0-9d8a7560d350.png) | ![screenshot-1669739062060](https://user-images.githubusercontent.com/17885425/204585816-93819f26-3c75-4c62-9f2b-0ad646971749.png)


getState:
```
{
	"country": "CA",
	"region": "NB"
}
```
</details>
