### ISSUE TITLE
IPFS context menu should be disabled in Private windows 

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#25362]
## Steps to Reproduce

   1. install `1.45.41`
   2. launch Brave
   3. load `ipns://docs.ipfs.io`
   4. click on `Use a Brave local IPFS node`
   5. click on the `"hamburger menu"` -> `New Private Window` or `New Private Window with Tor`
   6. load `search.brave.com`
   7. context-click the page or the `brave` logo
   8. look at the context menus

## Actual result:

IPFS context menu 1 | IPFS context menu 2
---------------------|---------------------
<img width="886" alt="Screenshot 2022-09-12 at 5 54 57 PM" src="https://user-images.githubusercontent.com/387249/189784128-4e6e1804-bb18-43fa-8f0c-3663748fe7b5.png"> | <img width="889" alt="Screenshot 2022-09-12 at 5 55 10 PM" src="https://user-images.githubusercontent.com/387249/189784133-9cfcf58a-5cec-4aab-ba69-0359b5f3681b.png">

## Expected result:

These don't work.  We should remove them, I think, because we remove them in the top-level/`"hamburger"` menu, for these window types.

Of course, if they're supposed to stay, we should fix them.

## Reproduces how often: 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @lidel @cypt4 @diracdeltas

**Comment by rebron** [comment]
cc: @spylogsster
