### ISSUE TITLE
Missing signing key hash on IPNS-shared content

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#25367]
## Description 

Missing signing key hash on IPNS-shared content

## Steps to Reproduce

1. install `1.45.41`
2. launch Brave
3. load `ipns://ipfs.io`
4. click `Use a Brave local IPFS node`
5. open `brave://settings/ipfs`
6. click on `Set up your IPNS keys`
7. click `Add`
8. type `newKey` (note its unique values)
9. click `Generate`
10. click on `"hamburger menu"` -> `IPFS` -> `Update IPNS` -> `With a file`
11. share/pin any file using `newKey`

## Actual result:

IPFS settings | `dweb.link` link
---------------|-----------------
![ipfs-1](https://user-images.githubusercontent.com/387249/189821352-00e4e9a7-3290-4755-9e9c-76e9f25f7acd.png) | ![ipfs-2](https://user-images.githubusercontent.com/387249/189821364-84cc7901-82f4-48dc-a1fc-2a97002deb9d.png)

look at the link; it's missing the `newKey` hash

e.g. `https://dweb.link/ipfs/QmPwTDdLrziVkgUrjJ72kz8Gj2cV35GWkdnXHbu5PUyEtE?filename=sample3.txt`

Also turns into `https://bafybeiaxyyc3lrod5ocnxrwfkwz4htnrcehzck4ewsirc3r3spyspmvit4.ipfs.dweb.link/?filename=sample3.txt`

Still missing the `newKey` hash.

## Expected result:

Should have its `newKey` hash just before the `?filename=` portion, according to my testcases.

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.45.41 Chromium: 105.0.5195.102 (Official Build) nightly (64-bit)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | Windows 10 Version 21H2 (Build 19044.1949)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @cypt4 @lidel @MadhaviSeelam

**Comment by srirambv** [comment]
This is not just with new keys but also happens with existing `self` key as well

**Comment by vadimstruts** [comment]
The IPFS local node and scheme has been [deprecated](https://github.com/brave/brave-browser/issues/37735)
