### ISSUE TITLE
Ads needs text

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#2536]
What should we show instead of coming soon?

![image](https://user-images.githubusercontent.com/9574457/49946121-4fbea100-febc-11e8-9925-caf216a7b95e.png)

cc @davidtemkin @jenn-rhim

**Comment by mrose17** [comment]
what we should do is to have the text say that adds are in beta and available only to special beta testers. And leave it at that!

**Comment by mandar-brave** [comment]
@NejcZdovc https://docs.google.com/document/d/1sjW_XPjUctoLRQN0VMqNbhukKJFg92YHNeYWd81ySYs/edit#

See details

**Comment by NejcZdovc** [comment]
fixed with https://github.com/brave/brave-core/pull/1283
