### ISSUE TITLE
Remove Rinkeby as a preloaded chain

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#25360]
## Description 

Related to conversation here https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1663013305197379?thread_ts=1662575028.202199&cid=C023VS4HJ6Q and ethereum merge coming up

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by SergeyZhukovsky** [comment]
Closing it as it's done in the context of other issues.
