### ISSUE TITLE
Remove Ropsten as a preloaded chain after merge

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#25361]
## Description 

Related to conversations around ethereum merge and in slack conv here . @onyb mentioned we do this in Q4 https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1662575028202199

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by SergeyZhukovsky** [comment]
Closing that as it's done in the context of other issues.
