### ISSUE TITLE
re-enabling wifi does not show sync QR code or words

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#2537]
## Description 
Similar to https://github.com/brave/brave-browser/issues/2533 but this case has consistently reproducible steps.

If you have wifi off when you first visit brave://sync page and attempt to create a sync chain, when you re-enable wifi the QR code and words will not be displayed. However, a refresh of the page resolves this.

## Steps to Reproduce

   1. Clean install 0.58.12
   2. Disable wifi
   3. Hamburger menu > Brave Sync
   4. Click on Start a new sync chain
   5. Get message about internet connection.
   6. Close message.
   7. Reenable wifi.
   8. Click on Start a new sync chain again.
   9. Click on Phone/Tablet or Computer.

## Actual result:
No QR code or words are displayed

![screen shot 2018-12-13 at 9 01 02 am](https://user-images.githubusercontent.com/28145373/49946823-c60fd300-febd-11e8-9959-bb8ac7d207df.png)

![screen shot 2018-12-13 at 9 01 10 am](https://user-images.githubusercontent.com/28145373/49946827-c8722d00-febd-11e8-86fd-59ec0ffe177d.png)

## Expected result:
QR code or words should be displayed.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.58.12 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
Similar to https://github.com/brave/brave-browser/issues/2533

cc @brave/legacy_qa for verification on other platforms

**Comment by GeetaSarvadnya** [comment]
Verification passed on 


Brave | 0.59.12 Chromium: 72.0.3626.17 (Official Build) beta (64-bit)
-- | --
Revision | 08d2140079f8db14c9eb885a803d231b1a30e817-refs/branch-heads/3626@{#315}
OS | Windows

- Verified the STR mentioned in the issue
