### ISSUE TITLE
`Manage subscriptions` icon still shown and able to subscribe when `Show Brave News` toggled OFF without explicitly turning OFF `Show Brave News button in the toolbar`

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#25385]
## Description 

I am not sure of the expected behavior for this scenario. If Show Brave News button is turned OFF, without explicitly turning OFF `Show Brave News button in the toolbar` `Manage Subscriptions` icon still shown. And when subscribe button clicked, `Loading` status shown as long as the modal is active and once it's dismissed,  `Subscribe` button is shown.

## Steps to Reproduce

   1. Install 1.44.83
   2. launch Brave
   3. open `brave://flags`
   4. set `Enable Brave News Subscribe Button` to Enabled
   5. click Relaunch
   6. load https://theguardian.com
   7. click `subscribe` on the `Manage Subscriptions` icon in the browser URL bar
   8. subscribe button changed to `Unsubscribe`
   9. open NTP
   10. click customize>>Brave News
   11. Toggle `OFF` `Show Brave News button` (without explicitly turning `OFF`  `Show Brave News button in the toolbar`)
   12. return to the site and click on `Manage Subscriptions` icon
   13. `Unsubscribe` button changes `Subscribe`
   14. click `Subscribe` button again
 
## Actual result:

Button shows `Loading` as long as the modal is active. Once it's dismissed, the button shows `Subscribe`

step 7|step 8|step9-10|step11-12|step13
----|----|----|----|----
<image width ="950" alt="image 1" src="https://user-images.githubusercontent.com/98358127/190023762-e6492351-2bec-48a9-a58a-0ecccd4a67af.png">|<image width ="950" alt="image 1" src="https://user-images.githubusercontent.com/98358127/190028844-a0f56e73-18b0-4ca1-b0e0-9f5f143f71ce.png">|<image width ="950" alt="image 1" src="https://user-images.githubusercontent.com/98358127/190023834-49a573fb-c847-44ff-8191-30cb4d81e62e.png">|<image width ="950" alt="image 1" src="https://user-images.githubusercontent.com/98358127/190023785-b2afa550-8eee-44f7-a411-49e6c635333b.png">|<image width ="950" alt="image 1" src="https://user-images.githubusercontent.com/98358127/190023815-6cb24fe9-5e11-41f8-bc1d-fabb9be999a4.png">

## Expected result:
`Manage subscriptions` icon should not be shown? 

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Brave | 1.44.83 Chromium: 105.0.5195.102 (Official Build) beta (64-bit)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | Windows 11 Version 21H2 (Build 22000.856)

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@rebron @fallaciousreasoning @stephendonner

**Comment by stephendonner** [comment]
Nice catch; I'm not sure what's supposed to happen, myself, so thanks for logging!

**Comment by MadhaviSeelam** [comment]
```
Brave | 1.45.75 Chromium: 106.0.5249.65 (Official Build) beta (64-bit)
-- | --
Revision | 3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}
OS | Windows 11 Version 21H2 (Build 22000.978)
```

Steps: 

Case 1: Disable `Show Brave News` 

1. Install 1.45.75
2. launch Brave
3. open brave://flags
4. set `Enable Brave News Subscribe Button` to Enabled
5. click Relaunch
6. load https://theguardian.com/
7. click  Manage Subscriptions icon in the browser URL bar
9. open NTP
10. click customize>>Brave News
11. Toggle OFF Show Brave News button (without explicitly turning OFF Show Brave News button in the toolbar)
12. return to the site 

#### Confirmed `Manage Subscription` button is not  available

Also verified  when `Show Brave News button in the toolbar` toggle is OFF, `Manage Subscription` button is not  available as expected.

step3-5|step6-7|step8-10|result
---|----|----|-----
<img width="478" alt="image" src="https://user-images.githubusercontent.com/98358127/192873508-77358ddb-d85d-4ff3-9402-9e2e7bc13eed.png">|<img width="478" alt="image" src="https://user-images.githubusercontent.com/98358127/192872501-b31d2cc7-1e0b-4b88-a8ad-837a05984b12.png">|<img width="477" alt="image" src="https://user-images.githubusercontent.com/98358127/192872963-601b8462-46a6-4fbf-8172-7eff7029792c.png">|<img width="478" alt="image" src="https://user-images.githubusercontent.com/98358127/192872810-3f9170d6-1184-4e47-8bea-93977b6c11cd.png">
