### ISSUE TITLE
Typo in `brave://flags` for `Enable Brave New Subscribe Button`

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#25386]
## Steps to Reproduce

   1. Install 1.44.83
   2. launch Brave
   3. open brave://flags
   4. search for `Enable Brave News Subscribe Button` 

## Actual result:

Reads `Enable Brave New Subscribe Button`

![image](https://user-images.githubusercontent.com/98358127/190030058-eefe6193-fde1-423d-8369-22e7ec67da70.png)

## Expected result:
Should read `Enable Brave News Subscribe Button`

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Brave | 1.44.83 Chromium: 105.0.5195.102 (Official Build) beta (64-bit)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | Windows 11 Version 21H2 (Build 22000.856)

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@rebron @fallaciousreasoning @stephendonner

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.45.74 Chromium: 106.0.5249.55 (Official Build) beta (x86_64)
-- | --
Revision | 4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}
OS | macOS Version 11.7 (Build 20G817)

#### Confirmed the flag now correctly reads `Enable Brave News Subscribe Button`

<img width="1312" alt="Screen Shot 2022-09-26 at 7 11 24 PM" src="https://user-images.githubusercontent.com/387249/192396769-d229d38b-4407-4955-8267-1353dc4bb8ef.png">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.45.75 Chromium: 106.0.5249.65 (Official Build) beta (64-bit)
-- | --
Revision | 3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}
OS | Windows 11 Version 21H2 (Build 22000.978)
```
Verified using original STR from https://github.com/brave/brave-browser/issues/25386#issue-1372143016

Confirmed correct text for the  flag  `Enable Brave News Subscribe Button` 

<img width="476" alt="image" src="https://user-images.githubusercontent.com/98358127/192871132-30f12d32-3e33-4059-8504-09642ca0434e.png">
