### ISSUE TITLE
Add a policy option to disable Brave Wallet

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#25383]
This is a sub-task for https://github.com/brave/brave-browser/issues/22029

**Test Plan:**

1. Set the policy to disable Brave Wallet:

- [Linux]
(sudo is needed in this step) Go to /etc/brave/policies/managed (create folders if not exists already), create test_policy.json with content:
<pre>
{
  "BraveWalletDisabled": true
}
</pre>
- [Windows]
  Open regedit and create the following keys: `BraveSoftware\Brave` under the existing key
    * For 64 bit, `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Policies`
    * For 32 bit, `HKEY_LOCAL_MACHINE\SOFTWARE\Policies` 

  Create a DWORD value at this path called `BraveWalletDisabled` and set the value as `1`

- [MacOS]
   * Create folder `/Library/Managed Preferences/<username>/`, if one doesn't exist (you will need to use `sudo`)
   * In the above folder create (or open; you will need to use sudo) the file named `com.brave.Browser.<CHANNEL>.plist` (where &lt;CHANNEL&gt; will be `nightly`, `beta`, or nothing for the release channel: e.g `com.brave.Browser.nightly.plist`) with the content:
     <pre>
     &lt;?xml version="1.0" encoding="UTF-8"?&gt;
     &lt;!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"&gt;
     &lt;plist version="1.0"&gt;
      &lt;dict&gt;
        &lt;key&gt;BraveWalletDisabled&lt;/key&gt;
        &lt;true/&gt;
      &lt;/dict&gt;
     &lt;/plist&gt;
     </pre>
  **Note:** MacOS caches these preferences, so if you delete or rename this file and restart the browser it will still retain this policy. In order to reset the policy quit the browser fully, delete or rename the file and issue to following command:
  <pre>
  defaults read /Library/Managed\ Preferences/&lt;username&gt;/com.brave.Browser.&lt;CHANNEL&gt;.plist
  </pre>
  You should see output similar to:
  <pre>
  2022-09-28 18:46:43.413 defaults[10710:143731] 
  Domain /Library/Managed Preferences/&lt;username&gt;/com.brave.Browser.nightly.plist does not exist
  </pre>
  Start the browser and you should be able to see the Rewards feature again.

2. Open Brave and navigate to brave://policy. Observe:
   
![image](https://user-images.githubusercontent.com/41635752/192934936-88bdbd89-fafd-4942-a661-e2af266e4406.png)

3. Navigate to brave://policy. Observe `This site can’t be reached` error page.
4. Open application menu (☰). Observe `Wallet` menu item is not present.
5. Navigate to brave://settings. Observe:
    - `Wallet` item is not present in the top Settings toolbar
    - `Wallet` item is not present in the left navigation menu
6. Observe in the sidebar the Wallet button is not present.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (64-bit) 
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | Linux

- Verified steps from issue description
- Verified with policy enabled, `brave://wallet` doesn't load and shows error page
- Verified Wallet is removed from Settings and Side panel when policy is enabled
- Verified Wallet is not show in settings toolbar
![image](https://user-images.githubusercontent.com/17010094/199198425-eb71ad9a-ac4b-4e07-861f-ace29ad6b086.png)

------------------------
Verification passed on

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (64-bit) 
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | Windows 11 Version 22H2 (Build 22621.674)

- Verified steps from issue description
- Verified with policy enabled, `brave://wallet` doesn't load and shows error page
- Verified Wallet is removed from Settings and Side panel when policy is enabled
- Verified Wallet is not show in settings toolbar
![image](https://user-images.githubusercontent.com/17010094/199208975-267a37f6-162d-4d96-bee0-7b7402327c8c.png)

------------------------
Verification passed on

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (arm64)
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from issue description
- Verified with policy enabled, `brave://wallet` doesn't load and shows error page
- Verified Wallet is removed from Settings and Side panel when policy is enabled
- Verified Wallet is not show in settings toolbar
![image](https://user-images.githubusercontent.com/17010094/199195737-b53193d0-6bf4-4d40-893d-bc785a087d4e.png)
