### ISSUE TITLE
[Android] Address `DiscouragedApi` warning in `BraveDappPermissionPromptDialog`

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#25388]
## Description 
Address `DiscouragedApi` warning in `BraveDappPermissionPromptDialog` or `show` method. It is much more efficient to retrieve resources by identifier (e.g. R.foo.bar) than by name (e.g. getIdentifier("bar", "foo", null)).

## Steps to reproduce 

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by samartnik** [comment]
@Pavneet-Sing could you please replace this comment
```
// TODO: It is much more efficient to retrieve resources by identifier (e.g. R.foo.bar) than by
// name (e.g. getIdentifier("bar", "foo", null)).
```
with the above explanation why we use  `@SuppressWarnings("DiscouragedApi")`

**Comment by Pavneet-Sing** [comment]
@samartnik sure, will do in my next PR.
