### ISSUE TITLE
Block findguide ads (fake search results)?

### ISSUE THREAD

**Issue by jtheletter** [brave/brave-browser#25381]
## Description 
Recently I’ve been seeing ads from findguide appear at the top of Google search results. They look just like actual Google results, except they use light mode and I use dark mode. They load as iframe elements sourced to `findguide.com/search.php?` followed by a query string.

I can set Brave browser to block cookies from that domain (brave://settings/cookies?search=block). I can create a CSS Stylus to block its display.

Is there a better way to block them entirely?

Couldn’t Brave browser block them by default? They’re nefarious; many users likely click them without realizing.

## Brave version (brave://version info)
Brave is up to date
Version 1.43.89 Chromium: 105.0.5195.102 (Official Build) (x86_64)

## Screenshots
I seem to get one of these in about ten searches.

<img width="957" alt="Screen Shot 2022-09-13 at 13 08 59" src="https://user-images.githubusercontent.com/49571924/189999646-6a61149c-3414-4a5b-9013-7d51f4bb1a53.png">

![Screen Shot 2022-09-13 at 13 17 16](https://user-images.githubusercontent.com/49571924/190000963-7ebbe3a4-5f39-438a-abf2-46040c2159e1.png)

**Comment by rebron** [comment]
cc: @ryanbr @antonok-edm

**Comment by ryanbr** [comment]
Does the ad show in private window mode, with no extensions? @jtheletter

**Comment by jtheletter** [comment]
If I disable the URL block I added, disable the Stylus style I added, disable browser extensions, and repeat the search twenty times in a private browser window, I do not see the fake-results advertisement (and I trigger Google’s “are you a robot” check three times).

**Comment by ryanbr** [comment]
I suspect that one of the extensions is inserting ads onto the page @jtheletter

**Comment by jtheletter** [comment]
I tried toggling on/off a few browser extensions, but it was difficult to determine if/which made a difference. Now a month has passed, and I’ve not seen the fake search results reappear. So I would guess someone solved this problem somehow somewhere.
