### ISSUE TITLE
Fix Brave Ads rewards migration path

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#25384]
## Description 

Brave Ads rewards migration path fails if `ads_rewards`, `transaction_history` or `unblinded_payment_tokens` nodes are missing from `Default/confirmations.json`

## Steps to Reproduce

   1. If `ads_rewards`, `transaction_history` or `unblinded_payment_tokens` nodes are missing from `Default/confirmations.json`

## Actual result:

`Failed to initialize ads` is shown in the verbose rewards logs.

## Expected result:
`Successfully initialized ads` should be shown in the verbose rewards logs.

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.45.75 Chromium: 106.0.5249.65 (Official Build) beta (64-bit)
-- | --
Revision | 3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}
OS | Ubuntu 18.04 LTS

Verified test plan from the description
