### ISSUE TITLE
UGP grant notification message from BAT logo is missing image

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#2538]
## Description 
Image is missing from above the 'Token Grant' message on Brave Rewards panel (accessible from BAT logo).

## Steps to Reproduce

   1. Clean install 0.58.12
   2. Click on BAT logo and enable rewards.
   3. Panel displays

## Actual result:
No image above Token Grant message
![screen shot 2018-12-13 at 10 09 32 am](https://user-images.githubusercontent.com/28145373/49947719-ea6caf00-febf-11e8-8e9a-ca30011c2dc6.png)

## Expected result:
![screen shot 2018-12-13 at 10 21 20 am](https://user-images.githubusercontent.com/28145373/49948150-dd9c8b00-fec0-11e8-9149-5e10e2dfd1ba.png)

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.58.12 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? no, did not reproduce on 0.59.6 beta

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
Probably related to https://github.com/brave/brave-browser/issues/2531

**Comment by rebron** [comment]
@petemill assuming https://github.com/brave/brave-core/pull/1011 will fix this issue?

**Comment by NejcZdovc** [comment]
should be fixed with https://github.com/brave/brave-core/pull/1011

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.58.14 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Mac OS X

* Verified STR from description (used staging environment)
![screen shot 2018-12-17 at 9 45 22 am](https://user-images.githubusercontent.com/28145373/50094202-9bd15480-01e0-11e9-8e97-962b4cd2dc64.png)
