### ISSUE TITLE
NTP background 2nd-level options should not be selected if their parent is not selected

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#25380]
## Description 

When I choose a gradient, then choose a solid color, the solid colors top-level item is correctly selected, but the gradient item is still selected when I click the top-level item. We should either clear this pref or hide the selection in the UI. It is confusing to know how to re-select this item since it is already selected.

## Steps to Reproduce

   1. Choose a gradient background
   2. Choose a solid background
   3. View gradient backgrounds

## Actual result:

A gradient appears selected

## Expected result:
No gradient appears selected

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
cc: @GeetaSarvadnya Can you see if you can reproduce. I couldn't reproduce in 1.45.68 and can't reproduce in 1.49.132

**Comment by GeetaSarvadnya** [comment]
@petemill Issue is **NOT** reproducible on `Windows 10 x64 - 1.50.108`. 

```
Brave | 1.50.108 Chromium: 112.0.5615.39 (Official Build) (64-bit)
-- | --
Revision | a0e7b9718a92bcd1cf33b7c95316caff3fc20714-refs/branch-heads/5615@{#753}
OS | Windows 10 Version 21H2 (Build 19044.2728)

```

**Comment by sangwoo108** [comment]
Let's close this issue, as it's been stale for a while.
