### ISSUE TITLE
Bandwidth stats is not shown clearly when blue Gradients/Solid background color is selected

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#25392]
## Description 

Follow up of the PR https://github.com/brave/brave-core/pull/14783
Bandwidth stats is not shown clearly when blue Gradients background color is selected
## Steps to Reproduce

   1. NA

## Actual result:

![image](https://user-images.githubusercontent.com/38657976/190060198-8fe1b783-f2d6-4d1d-9bd0-1939145848b2.png)

## Expected result:

Bandwidth stats should be shown clearly when blue Gradients background color is selected
## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.45.44 Chromium: 105.0.5195.102 (Official Build) nightly (64-bit)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | Windows 10 Version 21H2 (Build 19044.1889)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @simonhong @petemill @sangwoo108

**Comment by GeetaSarvadnya** [comment]
The issue is applicable for solid color selction also
![image](https://user-images.githubusercontent.com/38657976/190063623-0bc5ba3b-8e8e-4d40-9dda-027ba185e908.png)

**Comment by aguscruiz** [comment]
Design ready here
https://www.figma.com/file/FMuS3IZbzqzQTyRHz42Oix/Desktop-NTP?node-id=2586%3A108235

Already discussed having the text color changing from white to black depending on the background color contrast.
![image](https://user-images.githubusercontent.com/15734630/191509070-2745d60c-1215-4ad1-9408-207a4ebcc473.png)

**Comment by sangwoo108** [comment]
### Prototype plan
#### Colors to be inverted when contrast ratio with light background is too low
* stats
* clock
* right-bottom buttons
* News peek label
<img width="990" alt="스크린샷 2022-09-24 오후 6 21 47" src="https://user-images.githubusercontent.com/5474642/192090612-775b8264-de64-4496-9a61-7c84983856ac.png">

### How to define luminance of color
#### references
https://www.w3.org/TR/WCAG20/#contrast-ratiodef%20
https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_Colors_and_Luminance
https://www.myndex.com/WEB/LuminanceContrast

#### contrast ratio
```
contrast ratio
(L1 + 0.05) / (L2 + 0.05), where

L1 is the [relative luminance](https://www.w3.org/TR/WCAG20/#relativeluminancedef) of the lighter of the colors, and

L2 is the [relative luminance](https://www.w3.org/TR/WCAG20/#relativeluminancedef) of the darker of the colors.
```

#### Threashhold
> : The visual presentation of [text](https://www.w3.org/TR/WCAG20/#textdef) and [images of text](https://www.w3.org/TR/WCAG20/#images-of-textdef) has a [contrast ratio](https://www.w3.org/TR/WCAG20/#contrast-ratiodef) of at least 4.5:1,
> : Large Text: [Large-scale](https://www.w3.org/TR/WCAG20/#larger-scaledef) text and images of large-scale text have a contrast ratio of at least 3:1;

In our use case, 4.5:1 would be better cause there are small interactive texts and buttons.


#### how to define liminance of gradient?
For now, we should calculate some average color of gradient. 
The calculation for linear gradient and radial gradient would be different.

**Comment by aguscruiz** [comment]
Great! Yeah agreed 4.5:1 contrast would be ideal

**Comment by sangwoo108** [comment]
This is what I got now. Let me try deploying a storybook for you to play with.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5474642/192314577-d9b17e5e-e231-4914-8d8e-2fe1b10623b2.png">
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/5474642/192314637-84cc75a3-20b7-41d9-940e-4197052f3365.png">
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/5474642/192314685-9528f800-e140-4762-9330-a1eec6aaf6b1.png">

**Comment by sangwoo108** [comment]
0.45 seems to be too tight threshhold. Even gray and violet background can't pass it. Let me try 3:1.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (x86_64)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | macOS Version 11.7.1 (Build 20G918)

### Steps:
1. installed `1.46.81`
2. launched Brave
3. opened a new-tab page
4. clicked on `Customize`
5. clicked on `Solid colors`
6. selected various shades of colors
7. clicked on `Gradients`
8. selected various shades of gradients

#### Confirmed I was able to see `Bandwidth saved` text and its count, with high contrast

solid 1 | solid 2 | solid 3 | solid 4 | gradient 1 | gradient 2 | gradient 3 | gradient 4
-------|------|-----|------|-------|-------|-------|---------
<img width="1610" alt="Screen Shot 2022-10-27 at 5 58 50 PM" src="https://user-images.githubusercontent.com/387249/198427457-9fe24a58-0a6e-4efd-9459-3295809bdefc.png"> | <img width="1610" alt="Screen Shot 2022-10-27 at 5 58 53 PM" src="https://user-images.githubusercontent.com/387249/198427465-3e40e5ae-edac-4abb-89ed-7995303d4b45.png"> | <img width="1610" alt="Screen Shot 2022-10-27 at 5 59 05 PM" src="https://user-images.githubusercontent.com/387249/198427467-5d852e05-fd8a-4e71-ab66-b9871d5c3743.png"> | <img width="1610" alt="Screen Shot 2022-10-27 at 6 03 57 PM" src="https://user-images.githubusercontent.com/387249/198428543-a8d7913b-2924-4d11-9ed0-81b3f3609095.png"> | <img width="1610" alt="Screen Shot 2022-10-27 at 6 00 20 PM" src="https://user-images.githubusercontent.com/387249/198427473-eee3f096-5132-4614-bbae-51a4869cf1e0.png"> | <img width="1610" alt="Screen Shot 2022-10-27 at 6 00 23 PM" src="https://user-images.githubusercontent.com/387249/198427486-0a24e79d-ae7f-4b3e-99f4-0e684d393579.png"> | <img width="1610" alt="Screen Shot 2022-10-27 at 6 00 28 PM" src="https://user-images.githubusercontent.com/387249/198427493-728b4d7e-5e30-42b2-a061-18b5585b4de0.png"> | <img width="1610" alt="Screen Shot 2022-10-27 at 6 00 31 PM" src="https://user-images.githubusercontent.com/387249/198427500-6b7b91da-7a6e-404e-a298-f7a10fe73e6d.png">
