### ISSUE TITLE
Can Android add translation function?

### ISSUE THREAD

**Issue by biange200** [brave/brave-browser#25391]
安卓版本的brave可以增加翻译功能和脚本插件功能？

**Comment by bsclifton** [comment]
@biange200 thanks for the request - yes; we are planning to roll out Chinese

Can you please subscribe to https://github.com/brave/brave-browser/issues/24303 for updates? I'm going to close this issue as a duplicate. Thanks
------------------------

@biange200 感谢您的请求 - 是的； 我们计划推出中文

您能否订阅 https://github.com/brave/brave-browser/issues/24303 以获取更新？ 我将把这个问题作为一个副本关闭。 谢谢
