### ISSUE TITLE
Trackers & ads blocked stats is not shown clearly in NTP when a Gradient/Solid color is selected

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#25393]
## Description 

Follow up of PR #https://github.com/brave/brave-core/pull/14783
Trackers & ads blocked stats is not shown clearly in NTP when a Gradient color is selected
## Steps to Reproduce

   1. NA
  
## Actual result:

![image](https://user-images.githubusercontent.com/38657976/190062125-3d5ce501-fc6e-4015-8701-ba9af16f52ec.png)

## Expected result:
`Trackers & ads blocked` stats should be shown clearly in NTP when a Gradient color is selected

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.45.44 Chromium: 105.0.5195.102 (Official Build) nightly (64-bit)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}
OS | Windows 10 Version 21H2 (Build 19044.1889)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @simonhong @pes10k @sangwoo108

**Comment by GeetaSarvadnya** [comment]
The issue is applicable for solid color selction also
![image](https://user-images.githubusercontent.com/38657976/190064313-e960fdf6-91fc-4fb6-a57a-6d0a8369bf57.png)

**Comment by sangwoo108** [comment]
Hi, @aguscruiz ! Could you give me some guideline for the state UI? I think we might want to have shadow underneath the UI.

**Comment by aguscruiz** [comment]
Linking this issue here with the design solution:
https://github.com/brave/brave-browser/issues/25392#issuecomment-1253670681

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (x86_64)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | macOS Version 11.7.1 (Build 20G918)

### Steps:
1. installed `1.46.81`
2. launched Brave
3. opened a new-tab page
4. clicked on `Customize`
5. selected `Background Image`
6. selected `Solid colors`
7. chose a few different colors
8. chose a few different gradients
9. confirmed I could easily see the `Trackers & ads blocked` text and count

gradient 1 | gradient 2 | solid 1 | solid 2
----------|------------|--------|-------
<img width="1312" alt="Screen Shot 2022-10-27 at 5 39 00 PM" src="https://user-images.githubusercontent.com/387249/198422980-6498ac8f-2e1d-43cf-b3dc-5f0aa807320a.png"> | <img width="1312" alt="Screen Shot 2022-10-27 at 5 39 03 PM" src="https://user-images.githubusercontent.com/387249/198422982-0ab20669-8d7a-444a-8830-2f4beb0c1eaa.png"> | <img width="1312" alt="Screen Shot 2022-10-27 at 5 39 24 PM" src="https://user-images.githubusercontent.com/387249/198422985-b96375b2-85fb-461d-816a-98d5c828a8bd.png"> | <img width="1312" alt="Screen Shot 2022-10-27 at 5 39 33 PM" src="https://user-images.githubusercontent.com/387249/198422987-2bf3b68a-c61e-4783-85e2-c5113ebd70ab.png">
