### ISSUE TITLE
Create policy options for upgrading http to https

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#25395]
Add options to be able to configure it via local policies
- `HTTPSEverywhereDefault` (for global HTTPS upgrade)
- `HTTPSEverywhereAllowedForUrls` (for individual https upgrades)
- `HTTPSEverywhereBlockedForUrls` (for individual https upgrades)

**Comment by rebron** [comment]
cc: @diracdeltas

**Comment by spylogsster** [comment]
created security review  https://github.com/brave/security/issues/1061

**Comment by spylogsster** [comment]
Closed as requested in https://github.com/brave/security/issues/1061#issuecomment-1272868332
