### ISSUE TITLE
Create group policy options for Shields

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#25394]
## Description
Add group policy support for Shields (up/down). This will support individual URLs and patterns
- Added `BraveShieldsDisabledForUrls` to disable shields urls
- Added `BraveShieldsEnabledForUrls` to enable shields urls

For the design, see Figma:
https://www.figma.com/file/3A6F6VrxVahiZFxLr7j7FO/Desktop-Shields?node-id=2695%3A49651

### Behavior notes
This is an overview of what the user should expect when the policy is set.

#### Behavior when DISABLED
When the site being visited matches the URL or the pattern:
- shields should be DISABLED
- when clicking shields (to open advanced panel), person should see shields disabled
- shields itself should NOT be toggleable
- the other settings will never show up because shields are down

#### Behavior when ENABLED
When the site being visited matches the URL or the pattern:
- shields should be ENABLED
- when clicking shields (to open advanced panel), person should see shields enabled
- shields itself should NOT be toggleable (should be grayed out)
- none of the sub-values (block ads, https upgrade, block script, block fingerprint, block cookie) should be toggleable. It should be grayed out.

### Example of how to add the group policy (Windows)
1. Open `regedit.exe`
2. Navigate to `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\`
3. Create the key (folders) `BraveSoftware\Brave\` if they don't already exist

#### How to add the shields DISABLE policy
1. Create a new key (folder) `BraveShieldsDisabledForUrls` inside the root (`HKEY_LOCAL_MACHINE\SOFTWARE\Policies\BraveSoftware\Brave\`)
2. You can now add `REG_SZ` (string value) for any sites you wish to mark as disabled. 
 
The entries need to created in a numbered fashion. Let's say you want to add two values. You would create:
- `REG_SZ` value `1` set to `https://www.example.com`
- `REG_SZ` value `2` set to `[*.]brave.com`

This would DISABLE shields on brave.com and all subdomains. It would also DISABLE shields on https://www.example.com - but NOT on other subdomains (or if you leave `www.` out for example).

#### How to add the shields ENABLE policy
1. Create a new key (folder) `BraveShieldsEnabledForUrls` inside the root (`HKEY_LOCAL_MACHINE\SOFTWARE\Policies\BraveSoftware\Brave\`)
2. You can now add `REG_SZ` (string value) for any sites you wish to mark as enabled. 
 
The entries need to created in a numbered fashion. Let's say you want to add two values. You would create:
- `REG_SZ` value `1` set to `[*.]twitter.com`
- `REG_SZ` value `2` set to `https://www.example.com`

This would ENABLE shields on brave.com and all subdomains. It would also ENABLE shields on https://www.example.com - but NOT on other subdomains (or if you leave `www.` out for example).

### Adding using a `.reg` file (also on Windows)
1. Create a new empty file called `shields-policy.reg` 
2. Open it in Notepad and put this for the content:
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\BraveSoftware\Brave]

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\BraveSoftware\Brave\BraveShieldsEnabledForUrls]
"1"="[*.]twitter.com"
"2"="https://www.example.com"

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\BraveSoftware\Brave\BraveShieldsDisabledForUrls]
"1"="https://www.example.com"
"2"="[*.]brave.com"
```
3. Save the file and close it
4. Double click the `shields-policy.reg` file
5. You can use `regedit.exe` to confirm it was added

**Comment by bridiver** [comment]
what should actually display in the shields popup when shields is enabled/disabled by policy? How are we displaying to the user that shields is managed and cannot be changed there? This ticket needs more detail for review and QA

**Comment by spylogsster** [comment]
@bridiver there is follow up (with picture) to add a tooltip for this case https://github.com/brave/brave-browser/issues/26187

**Comment by LaurenWags** [comment]
@spylogsster @bsclifton 

Is this only for Windows, or is this applicable to macOS and Linux as well? Only Windows is mentioned in https://github.com/brave/brave-browser/issues/25394#issue-1372370679. 

If this is only for Windows, please add `OS/Windows` label.

If this is applicable for macOS and Linux as well, please add instructions on how to enable on those OSes also.

Labelling as `QA/Blocked` until the above is sorted out.

cc @kjozwiak @rebron

**Comment by bsclifton** [comment]
This is available on macOS and Linux - but I'm not sure offhand how to test actually. Let me dig in on that and then I'll share an update

**Comment by bsclifton** [comment]
## Example of how to add the group policy (Linux)
You can set the options via `/etc/opt/chrome/policies/managed` **(NOTE: is this path also for Brave?)**

Basically, you will make a file with the name of the key you'd like to set with contents being the value in JSON

### Example of how to enable shields for a list of origins
1. create a file 
    ```bash
    vim /etc/opt/chrome/policies/managed/BraveShieldsEnabledForUrls
    ```
2. paste in:
```
{
  "[*.]twitter.com",
  "https://www.example.com"
}
```

3. Save the file and exit (escape; `:wq`, enter)
4. Load Brave; verify it shows under brave://policy/

### Example of how to disable shields for a list of origins
1. create a file 
    ```bash
    vim /etc/opt/chrome/policies/managed/BraveShieldsDisabledForUrls
    ```
2. paste in:
```
{
  "https://www.example.com",
  "[*.]brave.com"
}
```

3. Save the file and exit (escape; `:wq`, enter)
4. Load Brave; verify it shows under brave://policy/

**Comment by LaurenWags** [comment]
thanks @bsclifton!

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.47.115 Chromium: 108.0.5359.94 (Official Build) beta (64-bit)
-- | --
Revision | 713576b895246504ccc6b92c2fb8ce2d60194074-refs/branch-heads/5359_71@{#3}
OS | Windows 10 Version 21H2 (Build 19044.2251)

Verified test plan from the description

#### DISABLE policy

<details>

Verified Brave is shown as managed in hamburger menu
![image](https://user-images.githubusercontent.com/34715963/205920452-0c4073c9-16a4-4f00-bdb7-6da43f4cbd00.png)

Verified Brave Shields are disabled by default for the disabled page
![image](https://user-images.githubusercontent.com/34715963/205920710-72052cad-f20e-43ef-ba1b-d3255af06b55.png)

Verified unable to enable Brave Shields for disabled page
![image](https://user-images.githubusercontent.com/34715963/205920902-8ccdf3aa-dc8f-4c1e-93a3-1dc419d6a464.png)


</details>

#### ENABLE policy

<details>

Verified Brave is shown as managed in hamburger menu
![image](https://user-images.githubusercontent.com/34715963/205921358-8f57c459-c75e-4346-bdd6-998bc89fc101.png)


Verified Brave Shields are enabled by default for the enabled page
![image](https://user-images.githubusercontent.com/34715963/205921444-4ebc2a0f-b8b9-4204-b0ff-cd4e3998704f.png)


Verified unable to disable Brave Shields for enabled page
![image](https://user-images.githubusercontent.com/34715963/205921499-cf20d669-1508-448d-8293-c713302d061a.png)


</details>

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.47.115 Chromium: 108.0.5359.94 (Official Build) beta (64-bit)
-- | --
Revision | 713576b895246504ccc6b92c2fb8ce2d60194074-refs/branch-heads/5359_71@{#3}
OS | Ubuntu 18.04 LTS

Verified test plan from the description

#### DISABLE policy

<details>

Verified Brave is shown as managed in hamburger menu
![image](https://user-images.githubusercontent.com/34715963/206572321-3ea50fe1-fb58-4bf3-95be-63167d038abd.png)


Verified Brave Shields are disabled by default for the disabled page
![image](https://user-images.githubusercontent.com/34715963/206572432-3298d920-c27a-47dc-807b-85c171dd55cc.png)


Verified unable to enable Brave Shields for disabled page
![image](https://user-images.githubusercontent.com/34715963/206572470-83201ebd-e547-41c8-84f4-75a3bc08b508.png)


</details>

#### ENABLE policy

<details>

Verified Brave is shown as managed in hamburger menu
![image](https://user-images.githubusercontent.com/34715963/206578440-826b5b4b-7752-4853-abe7-1fd180f42128.png)


Verified Brave Shields are enabled by default for the enabled page
![image](https://user-images.githubusercontent.com/34715963/206578467-b8608bf3-a00b-4100-9f48-0010ac0d4db3.png)


Verified unable to disable Brave Shields for enabled page
![image](https://user-images.githubusercontent.com/34715963/206578496-95659cfb-189e-4db8-a3d8-14506ebd2486.png)


</details>

#### ENABLE & DISABLE policy for the same domain

<details>

Verified the policies have 'OK' status
![image](https://user-images.githubusercontent.com/34715963/206578781-0a044c47-3e0f-4004-ad32-6ef451688869.png)


Verified Brave Shields enabled policy takes precedent over disabled policy
![image](https://user-images.githubusercontent.com/34715963/206578830-2e2d6a63-ea30-47cc-9226-5978c89d43ae.png)


</details>

#### Wildcard policy

<details>

Policy used:
![image](https://user-images.githubusercontent.com/34715963/206579783-c213d12f-d5c0-4a96-a6fb-f3f344c817d5.png)


Verified policy was applied to `https://www.example.com`
![image](https://user-images.githubusercontent.com/34715963/206579669-51fe52f2-e097-4105-afc5-07902c540a65.png)


Verified policy was applied to `https://example.com`
![image](https://user-images.githubusercontent.com/34715963/206579506-91d15e42-573c-4c4b-a474-d4d7def6d450.png)


</details>

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.47.136 Chromium: 108.0.5359.128 (Official Build) beta (x86_64)
-- | --
Revision | 1cd27afdb8e5d057070c0961e04c490d2aca1aa0-refs/branch-heads/5359@{#1185}
OS | macOS Version 11.7.2 (Build 20G1020)

### Case 1: Disable policy
<details>

</details>


### Case 2: Enable policy
### Case 3: Enable & disable policy for the same domain
### Case 4: Wildcard policy
