### ISSUE TITLE
Possible to sync the device with itself

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#2539]
## Steps to Reproduce

1 Clean install. 
2. Go to `chrome://sync/`
3. Click `Start a new sync chain` -> `Computer`
4. Copy `Sync code`
5. Close all the modals and click `Enter a sync chain code`
6. Paste the code from 4.

## Actual result:
The device is synced with itself

![image](https://user-images.githubusercontent.com/34715963/49948953-c7a8bd80-fef4-11e8-881a-fcfcf916f699.png)

![sync2](https://user-images.githubusercontent.com/34715963/49949502-0ee37e00-fef6-11e8-91e0-ab4f41dcb8ca.gif)

## Expected result:
the device is not synced with itself

## Reproduces how often: 

always

## Brave version (brave://version info)

Brave | 0.58.12 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Windows 7

@brave/legacy_qa

**Comment by cezaraugusto** [comment]
after https://github.com/brave/brave-core/pull/1094 we are resetting Sync when the devices modal is closed meaning that once you type your sync words the code word copied is not from the current device but from an abandoned chain, so I'm going to close this. Please re-open if you disagree

**Comment by cezaraugusto** [comment]
code ref https://github.com/brave/brave-core/pull/1094/files#diff-43b07d9c901bb298f50280da4bcf368dR87

**Comment by GeetaSarvadnya** [comment]
Verification passed on 


Brave | 0.59.12 Chromium: 72.0.3626.17 (Official Build) beta (64-bit)
-- | --
Revision | 08d2140079f8db14c9eb885a803d231b1a30e817-refs/branch-heads/3626@{#315}
OS | Windows

- Verified the STR mentioned in the issue.

Verification passed on 

Brave	0.59.12 Chromium: 72.0.3626.17 (Official Build) beta (64-bit)
Revision	08d2140079f8db14c9eb885a803d231b1a30e817-refs/branch-heads/3626@{#315}
OS	Linux

- Verified the STR mentioned in the issue.

**Comment by cezaraugusto** [comment]
I've bring up this issue in https://bravesoftware.slack.com/archives/C2HJYB45N/p1546637100018400 and we're considering that it's ok to have it as-is so I'm marking this as invalid
