### ISSUE TITLE
Background Selection state is wrong when SI background is shown

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#25398]
## Steps to Reproduce

   1. Choose solid/graident background
   2. Open new tabs until a new tab has SI background
   3. Open background picker on the new tab with SI.

## Actual result:

![image](https://user-images.githubusercontent.com/5474642/190114328-1a5b360a-c770-420a-8779-b6a1b23206ff.png)

## Expected result:
The actual background categroy should be checked.

## Reproduces how often: 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @GeetaSarvadnya @kjozwiak

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.45.74 Chromium: 106.0.5249.55 (Official Build) beta (x86_64)
-- | --
Revision | 4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}
OS | macOS Version 11.7 (Build 20G817)

#### Followed the steps to reproduce, and confirmed `Gradients` was shown as selected


example | example
---------|---------
<img width="1312" alt="Screen Shot 2022-09-26 at 6 07 11 PM" src="https://user-images.githubusercontent.com/387249/192389249-32e9bf61-4020-4066-8029-1a992058d8e2.png"> | <img width="1312" alt="Screen Shot 2022-09-26 at 6 04 25 PM" src="https://user-images.githubusercontent.com/387249/192389169-e5184227-da5f-4beb-8537-53c267226998.png">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.45.75 Chromium: 106.0.5249.65 (Official Build) beta (64-bit)
-- | --
Revision | 3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}
OS | Windows 11 Version 21H2 (Build 22000.978)
```

Reproduced in 1.44.101 using original STR in the description https://github.com/brave/brave-browser/issues/25398#issue-1372644090

<img width="470" alt="image" src="https://user-images.githubusercontent.com/98358127/192892715-55837249-a938-4726-9e45-f5a5cc7de8c0.png">

Steps:

1. Installed 1.45.75
2. launch Brave
3. click `Customize`
4. selected solid color background 
5. opened NTP until a NTPSI background shown
6.  click `Customize` to open  Background image setting page

Confirmed `Solid colors` category that was selected in step 4 remained selected 

Also verified for `Gradients` color category and the selection remained as selected

Solid colors
NTP|NTPSI
---|---
<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/192892874-7a467d07-f853-4a2d-9a1b-ba98d4968751.png">|<img width="462" alt="image" src="https://user-images.githubusercontent.com/98358127/192892918-80be87c1-0b8a-41fd-a105-ea7346fc690f.png">

Gradients 
NTP|NTP SI
---|----
<img width="456" alt="image" src="https://user-images.githubusercontent.com/98358127/192893357-c0b69d2e-1533-4401-9ff9-6c272c7c1151.png">|<img width="455" alt="image" src="https://user-images.githubusercontent.com/98358127/192893451-d6798c7b-0241-4fe7-b253-c00a9de6dc6f.png">
