### ISSUE TITLE
Soundcloud ads hang

### ISSUE THREAD

**Issue by DTV96Calibre** [brave/brave-browser#254]
## Description 
Playback freezes up when ads play (the ad isn't heard or seen) and continues (presumably) after the ad has finished.

## Steps to Reproduce
   1. Log into Soundcloud
   2. Find a track to play under Likes and click on it to start it.
   3. Soundcloud will eventually attempt to play an ad. Music playback will hang for a bit and may begin again, presumably when the ad is expected to end.

 ## Actual result:
Soundcloud playback freezes, including the ability to select different songs when an ad attempts to play.

## Expected result:
Song playback plays immediately when selecting for playback.

## Reproduces how often: 

Easily reproduced. You may have to play a few songs before Soundcloud attempts to play an ad.

## Brave version (about:brave info)
 
Brave: 0.22.721 
V8: 6.6.346.32 
rev: bfe7cdd026c68013236ebe206a33448db9370fca 
Muon: 6.0.12 
OS Release: 6.1.7601 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.170

### Reproducible on current release:
Yes

### Website problems only:  
- Does the issue gets fixed with Brave Shields disabled? Yes
- Does the issue reproduces on Chrome? No

**Comment by srirambv** [comment]
Cross posted issue on browser-laptop repo (https://github.com/brave/browser-laptop/issues/14428)
