### ISSUE TITLE
In app updates for android app

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#25407]
this issue is to add in app update dialog which can help users to have the latest version of the app. 

More details : https://developer.android.com/guide/playcore/in-app-updates

**Comment by hffvld** [comment]
According to @deeppandya we need to verify that the `app update` bottom-sheet modal is not shown on devices with Android 14 and newer as of today.

---------------------------

Verified on `Pixel 6` and `Pixel 7` using version(s):
```
Device/OS: 
- Pixel 6 / oriole-user 14 AP1A.240405.002 release-keys
- Pixel 7 / panther_beta-user 14 AP31.240426.023.B4 release-keys
Brave build: 1.67.112
Chromium: 126.0.6478.40 (Official Build) (64-bit) 
```
---------------------------

**STEPS:**
1. Install and launch Brave `1.67.112`
2. Finish the onboarding flow > Close Brave
3. Go to device settings > Date & time > Change the date to 1 week from today
4. Launch Brave > *Verify*
5. Repeat Steps 3 and 4 but set the date to `2 weeks`, `3 weeks`, and then `4 weeks` from today
6. Now change the date to `one month` from today
7. Launch Brave > *Verify*

**ACTUAL RESULTS:**
- Verified that there's no GPS bottom-sheet modal `re: requiring an update` when Brave `1.67.112` is installed and `1.67.115` is available for the upgrade if the system time is set to: `today's date`/`one week from today`/`two weeks from today `/`three weeks from today`/`four weeks from today`.
- Verified that GPS bottom-sheet modal `re: requiring an update` is NOT shown when the system time is set to `one month from today's date`.

---------------------------

`Pixel 6 / Android 14`

https://github.com/brave/brave-browser/assets/128532965/bf4fa3cb-c136-4b8b-b208-60268b97d789

`Pixel 7 / Android 15`

https://github.com/brave/brave-browser/assets/128532965/9660ca90-efa6-4314-a703-d8beb471dc1a
