### ISSUE TITLE
Brave Translate doesn't work (brave翻译功能没用)

### ISSUE THREAD

**Issue by biange200** [brave/brave-browser#25401]
试过多个网站 都是翻译不了
> I've tried multiple websites but can't translate it

![Screenshot_20220914_185343.jpg](https://user-images.githubusercontent.com/37582806/190136227-bc704287-34b9-4da1-b261-8dd6f247d302.jpg)
![Screenshot_20220914_185246.jpg](https://user-images.githubusercontent.com/37582806/190136297-e9a73a99-601b-430b-bce3-cdf7ee30b6b6.jpg)

**Comment by bsclifton** [comment]
@biange200 we don't support Chinese (yet)

You can subscribe to https://github.com/brave/brave-browser/issues/25327 for updates - I'm going to close this issue as a duplicate

cc: @rebron (in case we knew when Chinese may be available)
