### ISSUE TITLE
Show IPFS button and do DNSLink redirects when IPFS Resolution method is setted up as ASK

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#25406]
![image](https://user-images.githubusercontent.com/106654560/190204016-e6a2ba09-a90b-4531-9593-3b2214a32825.png)

Currently this features are available only if IPFS resolution method is selected as GATEWAY or LOCAL.

**Steps:**
1) Set IPFS resolution method to ASK 
![image](https://user-images.githubusercontent.com/106654560/190368323-c9b60f4e-bdde-415e-80a2-187a078d243d.png)
2) Set DNSLink autoredirect
![image](https://user-images.githubusercontent.com/106654560/190368415-6e8c381b-32ec-4e19-8261-be9957299f17.png)
3) Load https://en.wikipedia-on-ipfs.org

**Actual result:**
https version of the site is loaded

**Expected result:**
redirect to ipns://en.wikipedia-on-ipfs.org

**Comment by stephendonner** [comment]
Mind breaking this down into discrete steps, with expected and actual results, @cypt4 ?  Thanks!

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.46.68 Chromium: 107.0.5304.36 (Official Build) nightly (x86_64)
-- | --
Revision | 2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}
OS | macOS Version 13.0 (Build 22A379)

### Steps:
1. installed `1.46.68`
2. launched Brave
3. opened `brave://settings/ipfs`
4. ensured `Method to resolve IPFS resources` is defaulted to `Ask`
5. toggled `Automatically redirect to IPFS pages via DNSLink when possible`
6. loaded `https://en.wikipedia-on-ipfs.org/`
7. examined the resulting URL
8a. clicked on `Use a Brave local IPFS node`
8b. clicked on ` Use a public gateway`
9. ensured the content loaded over both types

#### Confirmed I could load `ipns://en.wikipedia-on-ipfs.org` over both `local-node` and `public-gateway` IPFS-delivery methods

example | example | example | example | example | example
---------|----------|---------|----------|---------|----------
<img width="1215" alt="Screenshot 2022-10-18 at 10 40 53 PM" src="https://user-images.githubusercontent.com/387249/196608022-91870ed7-f3cf-4d01-baab-90bf93c56385.png"> | <img width="1215" alt="Screenshot 2022-10-18 at 10 41 56 PM" src="https://user-images.githubusercontent.com/387249/196608026-82a21404-ba5f-4a92-9807-a370d44edbb7.png"> | <img width="1215" alt="Screenshot 2022-10-18 at 10 42 12 PM" src="https://user-images.githubusercontent.com/387249/196608036-89e2daaf-6cf6-40ce-9079-5b08f04a2f40.png"> | <img width="1215" alt="Screenshot 2022-10-18 at 10 42 19 PM" src="https://user-images.githubusercontent.com/387249/196608044-175a036a-5baf-485c-a975-364d50ef160f.png"> | <img width="1312" alt="Screenshot 2022-10-18 at 10 46 31 PM" src="https://user-images.githubusercontent.com/387249/196608047-2b3bb7d3-dacb-4083-b27c-0a649fff1769.png"> | <img width="1312" alt="Screenshot 2022-10-18 at 10 46 34 PM" src="https://user-images.githubusercontent.com/387249/196608052-8671ee51-82b6-4dca-b3f1-e552e360f6fa.png">
