### ISSUE TITLE
Clicking ok on info modal navigates back to sync home page

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#2541]
## Description 

Clicking ok on info modal navigates back to sync home page

## Steps to Reproduce

   1. Clean install 0.58.12
   2. Click `Enter a sync chain code` to join a sync chain
   3. Do not enter any code words and click on `Confirm sync code`
   4. Click `Ok` on the info modal, navigates back to home screen

## Actual result:

https://drive.google.com/open?id=1npiWvwxabuI2IIQezU3axdXqwolwflxU

## Expected result:
Should only dismiss the info modal and not navigate back to home screen

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.58.12 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
N/A
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @brave/legacy_qa

**Comment by GeetaSarvadnya** [comment]
Issue is reproducible on 0.59.12. Is the issue merged after the build 0.59.12 deployment?
![2541](https://user-images.githubusercontent.com/38657976/50448768-07d25c00-0949-11e9-9393-83b316854304.gif)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.59.14 Chromium: 72.0.3626.28 (Official Build) beta(64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Windows 7

![2541](https://user-images.githubusercontent.com/34715963/50616783-396b9a00-0eea-11e9-9d23-d5e154f65209.gif)
