### ISSUE TITLE
Sign and Send Transaction (Request) on pwgoom app crashing the browser

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#25415]
## Description 

Sign and Send Transaction (Request) on pwgoom app crashing the browser

## Steps to Reproduce

   1. Create and connect wallet on https://pwgoom.csb.app/
   2. click "Sign and Send Transaction (Request) "

## Expected result:
Should show transaction dialog

## Reproduces how often: 

easy

## Brave version (brave://version info)

release: Version 1.43.89 Chromium: 105.0.5195.102 (Official Build) (64-bit)
nightly: Version 1.45.32 Chromium: 105.0.5195.102 (Official Build) nightly (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel?  yes

[Screencast from 15-09-22 02:49:47 PM IST.webm](https://user-images.githubusercontent.com/11755381/190367878-7864d6d5-e6bc-4928-841f-37f929b72486.webm)

OS: Ubuntu 22.04.1 LTS

**Comment by srirambv** [comment]
This just got fixed and release as part of HF#4 via #25374
