### ISSUE TITLE
Add Sardine to Onboarding on-ramp providers

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#25414]
Sardine is missing in the on-ramp list as shown below.

<img width="674" alt="Screenshot 2022-09-14 at 14 54 11" src="https://user-images.githubusercontent.com/48117473/190331237-3466d6fd-137b-4ef3-afe1-6197615dc83c.png">

**Comment by kjozwiak** [comment]
The above requires `1.44.95` or higher for `1.44.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.44.99 Chromium: 106.0.5249.55 (Official Build) (arm64)
-- | --
Revision | `4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}`
OS | macOS Version 12.6 (Build 21G115)

- Verified steps from [brave/brave-core#15104](https://github.com/brave/brave-core/pull/15104)
- Verified Sardine is added as an on-ramp provider during onboarding
<img width="1840" alt="image" src="https://user-images.githubusercontent.com/17010094/192501315-fc118365-12b9-4759-894b-4fa7ab11f52f.png">

-------
Verification passed on 

Brave | 1.44.99 Chromium: 106.0.5249.55 (Official Build) (64-bit)
-- | --
Revision | `4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}`
OS | Windows 11 Version 22H2 (Build 22622.601)

- Verified steps from [brave/brave-core#15104](https://github.com/brave/brave-core/pull/15104)
- Verified Sardine is added as an on-ramp provider during onboarding
![image](https://user-images.githubusercontent.com/17010094/192503281-be92693d-d127-404f-9b1d-96e01290c07c.png)


-------
Verification passed on 

Brave | 1.44.99 Chromium: 106.0.5249.55 (Official Build) (64-bit)
-- | --
Revision | `4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}`
OS | Linux

- Verified steps from [brave/brave-core#15104](https://github.com/brave/brave-core/pull/15104)
- Verified Sardine is added as an on-ramp provider during onboarding
<img width="1290" alt="image" src="https://user-images.githubusercontent.com/17010094/192511187-7b37bbff-a851-4ab2-8531-4ab9d24b8bc1.png">
