### ISSUE TITLE
Support Solana Dapp transactions in Transaction Parser

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#25419]
Description:
Need to support two Solana dapp transaction types in our TransactionParser: SolanaDappSignAndSendTransaction & SolanaDappSignTransaction

Dependency:
Unlike desktop, Mobile doesn't have solana/web3 lib sdk to parse solana transaction so need:

- https://github.com/brave/brave-browser/issues/23960
- https://github.com/brave/brave-browser/issues/23961

**Comment by kjozwiak** [comment]
The above requires `1.46.94` or higher for `1.46.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.46.96 x64 beta build
- Verified steps from [brave/brave-core#15593](https://github.com/brave/brave-core/pull/15593)
- Verified able preform send and sign transactoin on Solana Dapp

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/200302509-394130e3-88e8-4881-8468-6906dae7194f.mp4> | <video src=https://user-images.githubusercontent.com/17010094/200302578-47cb4616-9b4f-4bf0-a0c0-b44010e13322.mp4>
