### ISSUE TITLE
Add Solana Sign Transaction / Sign All Transactions panel

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#25420]
Android version of https://github.com/brave/brave-ios/issues/6005

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.46.70 x64 Beta build
- Verified test plan from [brave/brave-core#15389](https://github.com/brave/brave-core/pull/15389)
- Verified able to Sign Transactions successfully

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/196919930-6c44baec-a546-4189-8d93-154dabadc74a.mp4> | <video src=https://user-images.githubusercontent.com/17010094/196920917-758f3d0c-10d4-4139-99d9-b1327ae73734.mp4>
