### ISSUE TITLE
sync command line logging

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#2542]
## Description 
Currently to view sync logs QA needs to use `--enable-logging --v=1` (which encompasses a lot of messaging). Would be very helpful to separate out sync logs similar to how rewards are (ex. `--enable-logging --vmodule=*rewards*=6`). Maybe something like `--vmodule=*sync*=<somenumber>`?

## Steps to Reproduce

   1. Launch from terminal with `--enable-logging --v=1`

## Actual result:
Sync logs are not separated from other log messages.

## Expected result:
Would like a way to separate sync logs from other logging messages.

## Brave version (brave://version info)

Brave | 0.58.12 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
@kjozwiak discussed feasibility with @darkdh

**Comment by darkdh** [comment]
please use `--enable-logging --vmodule=sync=1`
https://www.chromium.org/for-testers/enable-logging
