### ISSUE TITLE
Clicking on "first" isn't working when multiple transactions are being viewed

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#25421]
## Description 

[next-issue.webm](https://user-images.githubusercontent.com/11755381/190379957-384d70a1-77c1-4009-8fc8-8b82a7531150.webm)

- Can you reproduce this issue with the current release? Y
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? Y

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.46.70 Chromium: 107.0.5304.36 (Official Build) beta (64-bit) 
-- | --
Revision | `2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}`
OS | Linux

- Verified steps from issue description and [brave/brave-core#15243](https://github.com/brave/brave-core/pull/15243)
- Verified able to cycle through the list of pending transactions

https://user-images.githubusercontent.com/17010094/197795465-f8f5ff8f-14a5-4ba7-afbc-5de0e358cc85.mp4


------------------------
Verification passed on

Brave | 1.46.70 Chromium: 107.0.5304.36 (Official Build) beta (64-bit) 
-- | --
Revision | `2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}`
OS | Windows 11 Version 22H2 (Build 22621.674)

- Verified steps from issue description and [brave/brave-core#15243](https://github.com/brave/brave-core/pull/15243)
- Verified able to cycle through the list of pending transactions

https://user-images.githubusercontent.com/17010094/197794867-bdfe8610-8384-42e3-b690-da8bc1dba4c4.mp4

------------------------
Verification passed on

Brave | 1.46.70 Chromium: 107.0.5304.36 (Official Build) beta (arm64)
-- | --
Revision | `2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from issue description and [brave/brave-core#15243](https://github.com/brave/brave-core/pull/15243)
- Verified able to cycle through the list of pending transactions

https://user-images.githubusercontent.com/17010094/197789302-2a992abf-dfc0-4eba-9f2b-50253dce1480.mov
