### ISSUE TITLE
Matic on Ethereum Mainnet is not shown Buy list for Ethereum Mainnet

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#25422]
## Description 

Matic on Ethereum Mainnet is not shown Buy list for Ethereum Mainnet

## Steps to Reproduce

   1. Clean profile and create wallet
   2. Select Ethereum Mainnet and select token list under Buy
   3. `MATIC` token is not available
   4. Asset can be added to visible assets and shows under Send tab but not visible under Buy tab

## Actual result:

Matic on Ethereum Mainnet is not shown Buy list for Ethereum Mainnet

## Expected result:
Should show MATIC as per https://github.com/brave/brave-core/pull/14881

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.44.86 Chromium: 105.0.5195.127 (Official Build) beta (64-bit) 
-- | --
Revision | `912488396852bf658ab32465980c0b93a3c27a83-refs/branch-heads/5195@{#1109}`
OS | Windows 11 Version 21H2 (Build 22000.978)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @muliswilliam

**Comment by muliswilliam** [comment]
@srirambv 

https://user-images.githubusercontent.com/48117473/195107933-fd9c180a-d2f1-4de2-8c02-2f707b95fae1.mov

**Comment by srirambv** [comment]
This seems to be working fine. User misundertanding. The token shown is `MATIC - Polygon` on `Ethereum Mainnet`. With new changes to Sardine its more clear about the correct token being shown. Closing this as an invalid issue
