### ISSUE TITLE
Create Solana account and make Solana the default network for new wallet installs 

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#25432]
For new wallet installs:
- Have Solana account created
- Have the globally default selected network be Solana

cc @bbondy

**Comment by kjozwiak** [comment]
The above requires `1.44.95` or higher for `1.44.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.44.97 x64 build 
- Verified steps from [ brave/brave-core#15125](https://github.com/brave/brave-core/pull/15125)
- Verified Solana network is set as active network for new wallet or restored wallet
- Verified first Solana account generated for the seed is set as the active account for new wallet or restored wallet
- Verified on upgrade from previous build, Solana isn't set as active network
- Verified on upgrade from previous build with Solana account created doesn't make it the active account unless it was set as active before upgrade
- Verified no crash when creating new wallet
- Verified Solana account is selected after account creation

Create Account | Restore Wallet
-- | --
<video src=https://user-images.githubusercontent.com/17010094/191679992-d9af4eb9-b630-4830-b6ab-27244eabb62f.mp4> | <video src=https://user-images.githubusercontent.com/17010094/191680010-cf781a01-220c-4bae-acbd-9a73c92672fb.mp4>

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.44.97 Chromium: 106.0.5249.40 (Official Build) (64-bit) 
-- | --
Revision | `fab1d91915d2722d6339aaa7f4e9ce44f1e9b103-refs/branch-heads/5249@{#442}`
OS | Linux

- Verified steps from [brave/brave-core#15125](https://github.com/brave/brave-core/pull/15125)
- Verified Solana network is set as active network for new wallet or restored wallet
- Verified first Solana account generated for the seed is set as the active account for new wallet or restored wallet
- Verified on upgrade from previous build, Solana isn't set as active network
- Verified on upgrade from previous build with Solana account created doesn't make it the active account unless it was set as active before upgrade

https://user-images.githubusercontent.com/17010094/191685395-78375508-9f7c-439d-b32b-586fdcc2f35e.mp4

------------------------
Verification passed on

Brave | 1.44.97 Chromium: 106.0.5249.40 (Official Build) (64-bit) 
-- | --
Revision | `fab1d91915d2722d6339aaa7f4e9ce44f1e9b103-refs/branch-heads/5249@{#442}`
OS | Windows 11 Version 21H2 (Build 22000.978)

- Verified steps from [brave/brave-core#15125](https://github.com/brave/brave-core/pull/15125)
- Verified Solana network is set as active network for new wallet or restored wallet
- Verified first Solana account generated for the seed is set as the active account for new wallet or restored wallet
- Verified on upgrade from previous build, Solana isn't set as active network
- Verified on upgrade from previous build with Solana account created doesn't make it the active account unless it was set as active before upgrade


https://user-images.githubusercontent.com/17010094/191687205-ff2ed175-47d4-4a98-b4e6-c90a3c225149.mp4

------------------------
Verification passed on

Brave | 1.44.97 Chromium: 106.0.5249.40 (Official Build) (arm64)
-- | --
Revision | `fab1d91915d2722d6339aaa7f4e9ce44f1e9b103-refs/branch-heads/5249@{#442}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [brave/brave-core#15125](https://github.com/brave/brave-core/pull/15125)
- Verified Solana network is set as active network for new wallet or restored wallet
- Verified first Solana account generated for the seed is set as the active account for new wallet or restored wallet
- Verified on upgrade from previous build, Solana isn't set as active network
- Verified on upgrade from previous build with Solana account created doesn't make it the active account unless it was set as active before upgrade

https://user-images.githubusercontent.com/17010094/191682201-02d5f279-8f14-437d-9f42-77bfab37c32a.mov

**Comment by urbenlegend** [comment]
Is there anyway I can delete this newly created Solana account? I don't plan on using it and it's just an eyesore when I view my accounts list.

Honestly, I think users should be given a choice of which account to create during wallet creation so that they aren't stuck with accounts that they didn't want in the first place.
