### ISSUE TITLE
Left line hint is not displayed next to the icon in active state in brave://settings sidebar

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#25434]
## Steps to Reproduce

   1. Install `1.44.86`
   2. launch Brave
   3. open `brave://settings`
   4. click on  `Appearance` in the sidebar

## Actual result:

Left line hint is not displayed next to the icon in the active state
![image](https://user-images.githubusercontent.com/98358127/190482091-c4c6b9e2-98c0-4979-b69c-f686552a2a7d.png)

## Expected result:
Left line should be displayed for the `Appearance` icon in the active state

<img width="1312" alt="Screenshot 2022-09-15 at 12 44 09 PM" src="https://user-images.githubusercontent.com/387249/190494818-54e50ebe-4743-4136-bbec-315b5dc8166d.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.44.86 Chromium: 105.0.5195.127 (Official Build) beta (64-bit)
-- | --
Revision | 912488396852bf658ab32465980c0b93a3c27a83-refs/branch-heads/5195@{#1109}
OS | Windows 11 Version 21H2 (Build 22000.978)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@fallaciousreasoning @aguscruiz @rebron cc: @stephendonner

**Comment by Medmly20208** [comment]
Can I work on this issue?

**Comment by wolbek** [comment]
I would like to contribute to this issue.

**Comment by fallaciousreasoning** [comment]
Go for it @wolbek! This file `brave/browser/resources/settings/brave_overrides/settings_menu.js` is probably a good starting point :smile:

**Comment by prasoonmhwr** [comment]
If this issue is still open , may I work on this I am new to open source and this will be my good first issue

**Comment by prasoonmhwr** [comment]
> Go for it @wolbek! This file `brave/browser/resources/settings/brave_overrides/settings_menu.js` is probably a good starting point 😄

@fallaciousreasoning Is this the correct path? not able to find it

**Comment by sonithch** [comment]
@prasoonmhwr check it here

`https://github.com/brave/brave-core/blob/master/browser/resources/settings/brave_overrides/settings_menu.js`

**Comment by fallaciousreasoning** [comment]
Yeah go for it! 

The spec for the line from our designers is:

```css
width: 4px;
height: 32px;

background: linear-gradient(96.98deg, #E51D00 0%, #E5007B 78.13%);
border-radius: 0px 2px 2px 0px;
```

**Comment by prasoonmhwr** [comment]
> Yeah go for it!
> 
> The spec for the line from our designers is:
> 
> ```css
> width: 4px;
> height: 32px;
> 
> background: linear-gradient(96.98deg, #E51D00 0%, #E5007B 78.13%);
> border-radius: 0px 2px 2px 0px;
> ```

@fallaciousreasoning @sonithch  i think this issue is already fixed , as i just now downloaded the latest version of brave and i can see the line, I have attached the screenshot below. I think this issue can be closed.

<img width="1198" alt="Screenshot 2022-09-23 at 12 20 32 PM" src="https://user-images.githubusercontent.com/52622674/191906226-4ad637bb-103a-4d05-bc20-20a439d0a61f.png">
<img width="731" alt="Screenshot 2022-09-23 at 12 21 50 PM" src="https://user-images.githubusercontent.com/52622674/191906284-44088ebf-0ac7-4d2a-bf7b-41598635c4bf.png">

**Comment by prasoonmhwr** [comment]
@fallaciousreasoning I have created the pull request , whom should i assign for review?

**Comment by wolbek** [comment]
> Go for it @wolbek! This file `brave/browser/resources/settings/brave_overrides/settings_menu.js` is probably a good starting point 😄

@fallaciousreasoning Thank you. I have made a pull request.

**Comment by fallaciousreasoning** [comment]
I'm really sorry guys, I just realised there are two of you looking at this. @prasoonmhwr I'm going to look at @wolbek's PR, just because he asked if he could work on the issue first.

Really sorry about that everyone.

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
Brave | 1.46.80 Chromium: 107.0.5304.68 (Official Build) beta (64-bit)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | Windows 10 Version 21H2 (Build 19044.2130)

```
