### ISSUE TITLE
Add Brave Ads status header to search.brave.com calls

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-browser#25430]
## Description 
In preparation for Brave Ads on Brave Search, it is helpful for the Brave Search backend to understand whether the requesting browser has Brave Ads enabled.  As such we should add the header `X-Brave-Ads-Enabled: 1` to any call to Brave Search (and it's associated dev/staging environments) whether originating from the main search box or the Omnibox.

This can hopefully use some of the same mechanisms that have been used in the past on this, e.g. https://github.com/brave/brave-browser/wiki/Custom-Headers.  When the work is complete, please add an appropriate description to this page: https://github.com/brave/brave-browser/wiki/Custom-Headers.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.46.83 Chromium: 107.0.5304.68 (Official Build) beta (64-bit)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | Ubuntu 18.04 LTS

#### https://search.brave.com/

Clean profile

<details>

`X-Brave-Ads-Enabled: 1` is not included in the request
![image](https://user-images.githubusercontent.com/34715963/201784671-c551ffa5-3956-465e-b1ff-4b8b385addc2.png)

</details>

Ads enabled

<details>

`X-Brave-Ads-Enabled: 1` is included in the request

![image](https://user-images.githubusercontent.com/34715963/201785269-a69a7ebd-46aa-4d05-b2dd-bbbb41fb3377.png)


</details>

Ads disabled

<details>

`X-Brave-Ads-Enabled: 1` is not included in the request

![image](https://user-images.githubusercontent.com/34715963/201785415-911c8bc7-7930-450c-9dd6-111f2add9faf.png)


</details>

**Comment by LaurenWags** [comment]
Removing `QA Pass-Linux` as this is being uplifted to 1.45.x where it will need to be retested. In the event that there is not another 1.45.x build, the label can be re-added.

**Comment by LaurenWags** [comment]
Requires `1.45.129` or higher to test.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.45.129 Chromium: 107.0.5304.110 (Official Build) (64-bit)
-- | --
Revision | 2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/15147

#### https://search.brave.com/

Clean profile

<details>

`X-Brave-Ads-Enabled: 1` is not included in the request
![image](https://user-images.githubusercontent.com/34715963/202472247-1b164595-e5f1-46eb-aa21-03958569d7f9.png)


</details>

Ads enabled

<details>

`X-Brave-Ads-Enabled: 1` is included in the request

![image](https://user-images.githubusercontent.com/34715963/202472530-100ae72a-f455-4ea3-a63b-07f05bb01412.png)

</details>

Ads disabled

<details>

`X-Brave-Ads-Enabled: 1` is not included in the request

![image](https://user-images.githubusercontent.com/34715963/202472751-1c29cf45-8a92-4c03-825e-6479b89969a9.png)


</details>

**Comment by btlechowski** [comment]
Verification passed on Brave v1.45.129  on Samsung Galaxy Tab S5e (Android 11.0)

Verified test plan from https://github.com/brave/brave-core/pull/15147

#### https://search.brave.com/

Clean profile

<details>

`X-Brave-Ads-Enabled: 1` is not included in the request
![image](https://user-images.githubusercontent.com/34715963/202492636-d53e7e9c-5eec-4fba-9dbe-97a555470a10.png)


</details>

Ads enabled

<details>

`X-Brave-Ads-Enabled: 1` is included in the request

![image](https://user-images.githubusercontent.com/34715963/202492725-60b02d80-1032-4176-8f33-843f4466e371.png)


</details>

Ads disabled

<details>

`X-Brave-Ads-Enabled: 1` is not included in the request

![image](https://user-images.githubusercontent.com/34715963/202493212-bbed71d8-979c-42ea-b3c9-289c5f3e7e65.png)


</details>
