### ISSUE TITLE
Orca signature verification failure

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#25443]
## Description 

We were able to set-up the integration here: https://pr-963.d2sgcp2ktplkej.amplifyapp.com/ 

We can connect the Brave wallet and open a new Whirlpool position as expected. However, when withdrawing/closing a Whirlpool position (and burning the NFT for the associated position), we encounter an error with "signature verification failed" in the console. 

This seems to be a Brave-specific issue that does not affect other wallets. 

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by bbondy** [comment]
From orca:
yep, we are using 0.18.8
    "@solana/spl-token": "^0.1.8",
    "@solana/wallet-adapter-base": "^0.9.16",
    "@solana/wallet-adapter-wallets": "^0.18.8",
    "@solana/web3.js": "^1.43.1",

**Comment by yrliou** [comment]
The difference I see between opening a new Whirlpool position and withdrawing/closing a Whirlpool position is that the new position does pass signatures required by the transactions excluding the fee payer (user's) signature, which we sign and create the transaction with passed in signatures along with fee payer's signature, and it's sent out successfully by Orca. While when withdrawing/closing, I don't see signatures being passed in to us, we currently return the transaction with only fee payer's signature inside and Orca should do maybe addSignature to supply the missing signature before sending it out. I also tried filling the missing signature with 0 bytes to see if that's what dApp is expecting us to return in this case, but the result is still the same.

We need more help on Orca side to check how they currently provide the missing signature before sending out the transaction, and logging of transactions before signTransaction and after signTransaction, and before sendTransaction is always helpful.

**Comment by yrliou** [comment]
This was resolved from Orca side, closing.
