### ISSUE TITLE
Fix typo "brave background"

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#25441]
![image](https://user-images.githubusercontent.com/5474642/190589010-12ae4906-b98a-45a5-9707-c3a277438a00.png)

![image](https://user-images.githubusercontent.com/5474642/190589026-bdc7c50f-7dd4-4601-b8b4-f7eb47b4f88b.png)

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.45.74 Chromium: 106.0.5249.55 (Official Build) beta (x86_64)
-- | --
Revision | 4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}
OS | macOS Version 11.7 (Build 20G817)

But the background are empty; will file and circle back.

<img width="1102" alt="Screen Shot 2022-09-26 at 5 33 42 PM" src="https://user-images.githubusercontent.com/387249/192384837-bc916cd7-da57-4397-8e36-93e988943297.png">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.45.75 Chromium: 106.0.5249.65 (Official Build) beta (64-bit)
-- | --
Revision | 3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}
OS | Windows 11 Version 21H2 (Build 22000.978)
```

- Install 1.45.75
- launch Brave
- click `Customize`
- click `Brave backgrounds` tile
- verified the text reads correctly reads for `Brave backgrounds` 

![image](https://user-images.githubusercontent.com/98358127/192834170-82503087-a167-4779-8e98-7f692b3ea3ac.png)
