### ISSUE TITLE
"Upgrade connections to HTTPS" does not work anymore

### ISSUE THREAD

**Issue by pitsi** [brave/brave-browser#25449]
## Description 
Brave's "Upgrade connections to HTTPS" does not work anymore. Visiting a site that is on http but can do https, stays in http.

## Steps to Reproduce

   1. Make sure "Upgrade connections to HTTPS" is turned on under brave://settings/shields
   2. Visit a page that can do https, although it is in http. The one that I first noticed it is this mirror for the armbian repository: `http://armbian.systemonachip.net/apt/`

## Actual result:
The page's connection is not switched to https, so the "not secure" message on the right side of the address bar appears. 

## Expected result:
The page's connection is switched to https and the padlock appears on the right side of the address bar.

## Reproduces how often: 
Easily

## Brave version (brave://version info)
```
Brave	1.43.93 Chromium: 105.0.5195.127 (Official Build) (64-bit) ￼
Revision	912488396852bf658ab32465980c0b93a3c27a83-refs/branch-heads/5195@{#1109}
OS	Linux
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? No idea
- Can you reproduce this issue with the nightly channel? No idea

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:
Chrome upgrades its connection to https, provided that its relevant option (named "Always use secure connections", under chrome://settings/security) is enabled. For that reason, I also switched on the same setting on brave (under brave://settings/security) and then the issue was resolved in brave as well.
I also tested it on guest windows (profiles) for both browsers. On brave, the setting mentioned in the title is available on guest windows and it is enabled by default. The other one does not exist on either chrome's or brave's guest window settings.

**Comment by diracdeltas** [comment]
this is confusing because "upgrade connections" only upgrades it if it's in EFF's HTTPS Everywhere list, which is not really maintained anymore. the "Always use secure connections" setting is distinct from this feature. we are planning on deprecating HTTPS Everywhere in Brave in favor of "Always use secure connections" anyway.

**Comment by pitsi** [comment]
I see. Please close the issue when you finally remove the option from brave.

**Comment by pitsi** [comment]
As it seems, brave's option "upgrade connections to https" is now gone, leaving only the chromium one available, so I am closing this one.
![Uploading 2023-01-17-070725_1280x1024_scrot.png…]()
