### ISSUE TITLE
Open all in Private window - text is not translated

### ISSUE THREAD

**Issue by mbiesiad** [brave/brave-browser#25454]
## Description 
<code>Open all in Private window</code> text is not translated in other locales like Polish for instance.

## Steps to Reproduce

   1. Open Brave browser (with set Polish lang. for instance)
   2. Add few sites as bookmarks
   3. Add these websites to the Bookmark folder (ie.: create new one)
   4. RMC – right mouse click on the Bookmark folder
   5. See the result

## Actual result:
<code>Open all (...) in Private window</code> text is not translated other locales like Polish.

## Expected result:
<code>Open all (...) in Private window</code> text should be translated in other locales.

## Reproduces how often: 
Easily reproduced.

## Brave version (brave://version info)
1.43.93 Chromium: 105.0.5195.127

## Miscellaneous Information:
Screenshots:
✔ RMC - single bookmarked website (fine): 
![image](https://user-images.githubusercontent.com/18367606/190730266-9cc9ff25-030e-4f23-9c63-0cddc506cd15.png)

❌ RMC - bookmark folder (incorrect):
![image](https://user-images.githubusercontent.com/18367606/190730405-6ffc863f-9307-4ba6-915b-6f351f0ddd10.png)

Similar issues (fixed):
https://github.com/brave/brave-browser/issues/24296
https://github.com/brave/brave-browser/issues/25138

Best wishes,

**Comment by mbiesiad** [comment]
The same happens with repro steps:
1. Go to: brave://bookmarks/ - with set other lang. than English of course
2. Click on the Kebab Menu
3. See result

Screenshot - result:
![image](https://user-images.githubusercontent.com/18367606/190753353-0314fc72-7743-484f-8d58-50c4681f45a3.png)

Best wishes,

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.44.99 Chromium: 106.0.5249.55 (Oficjalna wersja) (x86_64)
-- | --
Wersja | 4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}
System operacyjny | macOS Wersja 11.7 (kompilacja 20G817)



example | example
---------|---------
<img width="1504" alt="Zrzut ekranu 2022-09-26 o 10 36 22 AM" src="https://user-images.githubusercontent.com/387249/192307220-4561dcac-b149-45da-872b-387521fe6f2a.png"> | <img width="1504" alt="Zrzut ekranu 2022-09-26 o 11 01 45 AM" src="https://user-images.githubusercontent.com/387249/192311774-77aeb196-0b64-4506-8154-716b0ea248bc.png">
