### ISSUE TITLE
`sec-ch-ua` client hint should use the same product name regardless of the channel.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#25459]
This is a follow up to https://github.com/brave/brave-browser/issues/24009 (https://github.com/brave/brave-core/pull/14155). 

The code to generate the hint calls `version_info::GetProductName()` which on MacOS returns different values based on the channel (Beta, Nightly). 

@pes10k suggested to the value should be invariable for all channels.

Test plan:

See https://github.com/brave/brave-variations/pull/332

**Comment by kjozwiak** [comment]
The above requires `1.45.87` or higher for `1.45.x` verification 👍 @brave/qa-team note that this is behind Griffin and at the time of verification, might only be enabled on the Nightly channel. Please use `brave://flags` to enable `brave://flags/#allow-certain-client-hints`.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.45.87 Chromium: 106.0.5249.91 (Official Build) beta (x86_64)
-- | --
Revision | fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}
OS | macOS Version 11.7 (Build 20G817)

### Steps:
1. installed `1.45.87`
2. launched Brave
3. opened `brave://flags`
4. set `Allow certain request client hints` to `Enabled`
5. clicked on the `Relaunch` button
6. loaded `brave.com` with the `Developer Tools` open to the `Network` panel
7. clicked on `brave.com`
8. examined the `Request` headers and confirmed the following was present:

```
sec-ch-ua: "Chromium";v="106", "Brave";v="106", "Not;A=Brand";v="99"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
```

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.45.87 Chromium: 106.0.5249.91 (Official Build) beta (64-bit)
-- | --
Revision | fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}
OS | Windows 11 Version 21H2 (Build 22000.978)
```
### Steps:
1. installed `1.45.87`
2. launched Brave
3. opened `brave://flags`
4. set `Allow certain request client hints` to `Enabled`
5. clicked on the `Relaunch` button
6. loaded `brave.com` with the `Developer Tools` open to the `Network` panel
7. clicked on `brave.com`
8. examined the `Request` headers and confirmed the following was present:
```
sec-ch-ua: "Chromium";v="106", "Brave";v="106", "Not;A=Brand";v="99"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
```

step 3-5|step 8
----|-----
<img width="452" alt="image" src="https://user-images.githubusercontent.com/98358127/194178875-b7e75b8e-306e-423c-9593-153f31a2bfac.png">|<img width="949" alt="image" src="https://user-images.githubusercontent.com/98358127/194179517-f8e077f6-8ef3-4bf0-970f-811d905187ec.png">

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.45.90 Chromium: 106.0.5249.103 (Official Build) beta (64-bit)
-- | --
Revision | 182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}
OS | Ubuntu 18.04 LTS

### Steps:
1. installed `1.45.x`
2. launched Brave
3. opened `brave://flags`
4. set `Allow certain request client hints` to `Enabled`
5. clicked on the `Relaunch` button
6. loaded `brave.com` with the `Developer Tools` open to the `Network` panel
7. clicked on `brave.com`
8. examined the `Request` headers and confirmed the following was present:

```
sec-ch-ua: "Chromium";v="106", "Brave";v="106", "Not;A=Brand";v="99"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Linux"
```

`brave://flags` | `brave.com` headers
---------------|----------------------
![image](https://user-images.githubusercontent.com/34715963/196392872-5d0e073e-ed90-45c5-842e-7e3972ac47b5.png)|![image](https://user-images.githubusercontent.com/34715963/196393344-a5d96b83-a648-4840-bdf8-ff53ab722665.png)
