### ISSUE TITLE
`Content filters` - translation mix

### ISSUE THREAD

**Issue by mbiesiad** [brave/brave-browser#25458]
## Description 
Inside the part of `brave://settings/shields/filters` languages are mixed.

## Steps to Reproduce
   1. Go to (with set language other than English, ie.: Polish): brave://settings/shields/filters
   2. Scroll down and read

## Actual result:
Parts like: `Content filters`, `Filter lists`, `Show full list` are not translated from English.

## Expected result:
Consistency is maintained - mentioned part is also translated.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
1.43.93 Chromium: 105.0.5195.127
 

## Miscellaneous Information:
Screenshots:
![image](https://user-images.githubusercontent.com/18367606/190826488-c98950d5-1fee-4f85-8f81-ed968d4ce10b.png)

![image](https://user-images.githubusercontent.com/18367606/190826651-ec2da931-7c72-4603-b2d2-07566bd2747f.png)

![image](https://user-images.githubusercontent.com/18367606/190826535-fac6ae2a-6c3e-4a35-a44c-c8c0341a956c.png)

Best wishes,

**Comment by rebron** [comment]
cc: @mkarolin and @btlechowski

**Comment by kjozwiak** [comment]
The above requires `1.45.104` or higher for `1.45.x` verification 👍
