### ISSUE TITLE
`brave://settings/shields` - AMP translation issue

### ISSUE THREAD

**Issue by mbiesiad** [brave/brave-browser#25457]
## Description 
AMP part in `brave://settings/shields` is not translated.

## Steps to Reproduce

   1. Set lang. other than English (ie.: Polish)
   2. Go to: brave://settings/?search=amp or: brave://settings/shields
   3. Take a look at part contains 'AMP'

## Actual result:
`div.label` there is translated, but `span#sub-label-text` is not.

`Always visit original (non-AMP) page URLs, instead of Google's Accelerated Mobile Page versions` text is still displayed in English.

## Expected result:
Consistency is maintained - mentioned part is also translated.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
1.43.93 Chromium: 105.0.5195.127 

## Miscellaneous Information:
Screenshot:
![image](https://user-images.githubusercontent.com/18367606/190813753-4ed897b4-29e6-43d1-a763-18221221901f.png)

Best wishes,

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.44.99 Chromium: 106.0.5249.55 (Oficjalna wersja) (x86_64)
-- | --
Wersja | 4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}
System operacyjny | macOS Wersja 11.7 (kompilacja 20G817)

`brave://settings/shields` | `support.brave.com`
--------------------------|----------------------
<img width="1144" alt="Zrzut ekranu 2022-09-26 o 5 09 21 PM" src="https://user-images.githubusercontent.com/387249/192381610-01d0bdb5-4796-42d4-84c1-c895e70fe363.png"> | <img width="1144" alt="Zrzut ekranu 2022-09-26 o 5 14 03 PM" src="https://user-images.githubusercontent.com/387249/192381759-6b2789dc-3e20-41ea-bacb-edca436e067d.png">


#### Confirmed translated text, as well as clicked on `Dowiedz się więcej` which went to `https://support.brave.com/hc/en-us/articles/8611298579981`
