### ISSUE TITLE
Misaligned UI elements on `view sync code` modal

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#2546]
## Steps to Reproduce

1. Sync two devices
2. In Desktop Browser click `view sync code`

## Actual result:

Misaligned UI elements

![image](https://user-images.githubusercontent.com/34715963/49956318-30983180-ff05-11e8-981e-32a38114b708.png)

## Expected result:
The UI elements are properly aligned

## Brave version (brave://version info)

Brave | 0.58.12 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Windows 7

cc @brave/legacy_qa

**Comment by kjozwiak** [comment]
Lets try getting this fixed in `0.58.x` if possible as it looks pretty bad... Doesn't look professional and users will question if we even noticed something that obvious as the above.

**Comment by rebron** [comment]
@petemill @cezaraugusto can you guys take a look at this one?

**Comment by bradleyrichter** [comment]
We can't ship this as is. Must fix please.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.58.14 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Windows 7

Looks better
![image](https://user-images.githubusercontent.com/34715963/50061318-4c1e6900-019f-11e9-8f5d-aa54c50ff1ed.png)

Padding between `Word Code` and `QR Code` could be improved.  Reported https://github.com/brave/brave-browser/issues/2591
