### ISSUE TITLE
Feature Request: Disable-all button for Brave News sources

### ISSUE THREAD

**Issue by toddlj** [brave/brave-browser#25462]
## Description 
This is a feature request for a "disable all" button when configuring Brave News sources. By default many news sources are enabled. I'd like the option to disable all so I can actively opt in to the news sources I want to consume.

## Steps to Reproduce
1. Open new tab of desktop.
2. Click customise.
3. Navigate to Brave News. (Enable Brave News if not enabled)
![image](https://user-images.githubusercontent.com/16966076/190834610-77741951-1e99-48ca-b0dc-9d4c66532bb8.png)
4. (Optional) Click onto one of the sections.
![image](https://user-images.githubusercontent.com/16966076/190834620-0c4a9b07-754c-49df-b506-e50deb680e02.png)

## Brave version 
Version 1.43.93 Chromium: 105.0.5195.127 (Official Build) (64-bit)
Linux

**Comment by bsclifton** [comment]
cc: @mattmcalister @fallaciousreasoning

**Comment by fallaciousreasoning** [comment]
+1, I'm pretty keen for this feature myself. Might be a little while because I'm working on landing a UI update first but I really want to get onto this at some point

**Comment by mattmcalister** [comment]
+1. 

the UI update should essentially solve this problem.
