### ISSUE TITLE
Non-referral downloads should use generic refcode 

### ISSUE THREAD

**Issue by davidtemkin** [brave/brave-browser#2547]
Currently, only versions of Brave that have been downloaded with a refcode (as encoded in the installer's filename) will (a) call referral server endpoints immediately and at 30 days, and (b) will include the refcode in update pings for the first 90 days of usage.

This change will add an implicit, default refcode for all downloads, even those not downloaded via referral links.

Here's the change: All Brave browsers should add a universal "default" Brave refcode into the user profile at first run time (if not already present from a referral download/installation process) and act from that moment forward exactly as any referred download would act.

This will give us apples-to-apples data that will allow us to diagnose potential problems with both "organic" and referred installs. 

Stay tuned for the actual default refcode to use.

This change needs to be released in .58.x

**Comment by mandar-brave** [comment]
@anthonypkeane to follow up for Mobile as well - not a high priority immediately.

**Comment by anthonypkeane** [comment]
@jhreis @SergeyZhukovsky Pls add this to the list of to-dos

**Comment by diracdeltas** [comment]
In case it wasn't clear, we should not do IP anti-fraud logging for general referrals. (Basically any download not from a referral promo)

**Comment by aekeus** [comment]
@diracdeltas are you ok with keeping the current behaviour of storing the geo-coded country for downloads and installations using the new default refcode?

**Comment by diracdeltas** [comment]
@aekeus do you mean the current behavior for referral promo builds is to log geo-coded country for each referral download?

**Comment by aekeus** [comment]
@diracdeltas ip is not stored, it is geo-coded and the ip address discarded.

**Comment by diracdeltas** [comment]
if the effect is just "Brave sees country code of all downloads/installs (unlinked to any other data except the user's referral code)" i think that is not necessary to remove, but if it's not needed, it should probably be removed.

my general concern is we may want to add more anti-fraud checks in the future for referral promo users that we don't want for regular users, so it might make sense to distinguish between the two from the start.

**Comment by aekeus** [comment]
@diracdeltas ok that makes sense. Would you be more comfortable if we removed all info from the iptags JSON blob except country for the default refcode case?

**Comment by davidtemkin** [comment]
country is needed for reasons other than anti-fraud.

good point on being careful wrt on any future anti-fraud measures related to referrals.

**Comment by aekeus** [comment]
@diracdeltas yes, country is the only identifier required. We should remove the rest on all downloads. Will update the linked issue.

**Comment by rebron** [comment]
cc: @anthonypkeane

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.65.107 Chromium: 75.0.3770.38 (Official Build) beta (64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Windows 10 OS Version 1803 (Build 17134.523)

Used test plan from https://github.com/brave/brave-core/pull/1982
Verified BRV001 is the generic ref code.
Logged https://github.com/brave/brave-browser/issues/4619

![image](https://user-images.githubusercontent.com/34715963/58441269-ef759180-80e0-11e9-8043-2eed831eff9e.png)
![image](https://user-images.githubusercontent.com/34715963/58441305-4aa78400-80e1-11e9-8a03-021dcfd8d3ca.png)

**Comment by srirambv** [comment]
Marking as Windows and macOS only as referrals are not available on Linux

**Comment by davidtemkin** [comment]
I think we do want the generic referral code reporting on Linux -- the intent here is to measure our organic download usage, and that does not involve the download/install refcode mechanism. It only requires that the generic "organic" refocode be put into the update pings. (In effect, this will mean all Linux builds will use this one refcode). @srirambv

**Comment by btlechowski** [comment]
Removed OS/Windows and OS/macOS labels based on above comment

**Comment by srirambv** [comment]
Verified on new profile and it shows the default ref code. Existing profiles doesn't show it. Marking it as passed on 

Brave | 0.65.112 Chromium: 75.0.3770.38 (Official Build) beta (64-bit)
-- | --
Revision | 3860105745f2b12537da9e9f048f14c3f52ba970-refs/branch-heads/3770@{#618}
OS | Linux

![image](https://user-images.githubusercontent.com/17010094/58559985-37d0a480-81f2-11e9-8065-127f3f022aca.png)
