### ISSUE TITLE
Unable to translate

### ISSUE THREAD

**Issue by biange200** [brave/brave-browser#25471]
![Screenshot_20220919_130714.jpg](https://user-images.githubusercontent.com/37582806/190953016-4a1bc498-b1cf-4ffa-9c53-9d251a4684d0.jpg)
![Screenshot_20220919_130707.jpg](https://user-images.githubusercontent.com/37582806/190953044-39e95546-7ede-4cee-8e54-6e626ea1520d.jpg)
 安卓版本的brave在中国经常无法翻译
![Screenshot_20220919_131119.jpg](https://user-images.githubusercontent.com/37582806/190953282-3a7e9ff5-f4d1-41c5-b462-3943fbe779c2.jpg)

**Comment by bsclifton** [comment]
@biange200 thanks for reporting this - yes; we are planning to roll out Chinese at some point.

Can you please subscribe to https://github.com/brave/brave-browser/issues/24303 for updates? When you see that issue become closed, it means it's fixed. I'm going to close this issue as a duplicate. Thanks

------------------------

@biange200 感谢您报告此问题 - 是的； 我们计划在某个时候推出中文。

您能否订阅 https://github.com/brave/brave-browser/issues/24303 以获取更新？ 当您看到该问题已关闭时，这意味着它已修复。 我将把这个问题作为一个副本关闭。 谢谢
