### ISSUE TITLE
make it so Tor warning text is visible without scrolling

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#25479]
with the Tor design update, the important warning at the end of the Tor window description text is hidden behind a scroll:

<img width="297" alt="Screenshot 2022-09-19 at 14 59 35" src="https://user-images.githubusercontent.com/549654/191023164-d61039f9-d2ef-433a-a252-ce14ba31f610.png">

we should either make this text area bigger or make the text shorter, for instance change it to:

> Brave doesn't store browsing activity from Private Windows. With Tor connectivity, it is more difficult for sites to see your true IP address and for network observers to see what sites you visit. However, if your personal safety depends on remaining anonymous, use the [Tor Browser](https://torproject.org) instead.

**Comment by rmcfadden3** [comment]
@diracdeltas — your text looks good. Only comment I'll make is the phrase "Brave never remembers…" to me might imply some server call on our side that we disable in a Private Window, which is obviously not true.

I think what we're rather saying here is a comment on the client-side, no? Like "The Brave browser never caches your activity in a Private Window." or similar?

**Comment by diracdeltas** [comment]
i changed that sentence to `Brave doesn't store browsing activity from Private Windows.` since it's more accurate

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.46.68 Chromium: 107.0.5304.36 (Official Build) nightly (x86_64)
-- | --
Revision | 2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}
OS | macOS Version 13.0 (Build 22A379)

### Steps:
1. installed `1.46.68`
2. launched Brave
3. clicked on the `"hamburger"` menu
4. clicked on `New Private Window with Tor`
5. examined the info text on the bottom left

#### Confirmed the text updates match https://github.com/brave/brave-browser/issues/25479#issue-1377925871 and https://github.com/brave/brave-browser/issues/25479#issuecomment-1275302910

<img width="1186" alt="Screenshot 2022-10-18 at 5 07 08 PM" src="https://user-images.githubusercontent.com/387249/196567790-23c2b66e-dccd-449b-b006-d9b25c4152f2.png">
