### ISSUE TITLE
Bug - Buys on wallet are hardcoded in the url to USD

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#25477]
> BuyUrl for all ramp providers currently hard code fiat currency to USD, as a result, a user's preferred currency is not used used in on ramp provider's UI. This creates a confusing UX for users.

Android version of https://github.com/brave/brave-browser/issues/23295

cc: @HEagle18, @Pavneet-Sing @SergeyZhukovsky @wchen342

**Comment by HEagle18** [comment]
On desktop, we settled on providing 3 currencies USD, EUR and GBP. Message me or @muliswilliam for questions.

**Comment by Pavneet-Sing** [comment]
This is a dupe of [Add currency selector on Buy asset screen](https://github.com/brave/brave-browser/issues/27679) so closing it
