### ISSUE TITLE
Crash on opening browser after 8 hours of inactivity

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#25481]
## Description 
There is a crash on opening browser after 8 hours of inactivity.

## Steps to reproduce 

   1. Open any website.
   2. Close browser via `Exit` menu.
   3. Change system time to the next day (it has to be more than 8 hours).
   4. Open browser again and it crashes.

## Actual result 
Browser crashes.

## Expected result
No crash.

## Issue reproduces how often 
Easy.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version?  No
- Can you reproduce this issue with the current Play Store Beta version?  No
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
1.45.54

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 13` using the following build(s):

```
Brave | 1.44.95 Chromium: 106.0.5249.40 (Official Build) (32-bit)
--- | ---
Revision | fab1d91915d2722d6339aaa7f4e9ce44f1e9b103-refs/branch-heads/5249@{#442}
OS | Android 13; Build/T1B1.220819.006
```

Reproduced the issue using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/25481#issue-1378063609 using `1.45.56 Chromium: 106.0.5249.40`.

Verified that the crash doesn't occur with `1.44.95 Chromium: 106.0.5249.40` when running through the STR/Cases outlined via https://github.com/brave/brave-browser/issues/25481#issue-1378063609.

-----

Verification **PASSED** on `Samsung Tab S8 Ultra` running `Android 12` using the following build(s):

```
Brave | 1.44.95 Chromium: 106.0.5249.40 (Official Build) (32-bit)
--- | ---
Revision | fab1d91915d2722d6339aaa7f4e9ce44f1e9b103-refs/branch-heads/5249@{#442}
OS | Android 12; Build/SP2A.220305.013
```

Reproduced the issue using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/25481#issue-1378063609 using `1.45.56 Chromium: 106.0.5249.40`.

Verified that the crash doesn't occur with `1.44.95 Chromium: 106.0.5249.40` when running through the STR/Cases outlined via https://github.com/brave/brave-browser/issues/25481#issue-1378063609.
