### ISSUE TITLE
Manually revert the Windows only DNS over HTTP work-around (for Brave VPN)

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#25488]
## Description 
We should manually revert the logic introduced in https://github.com/brave/brave-core/pull/13434

Basically, Windows can leak your ISP due to `Smart Multi-Homed Name Resolution` (even when you're on VPN). This is a feature of Windows and is expected behavior. See https://github.com/brave/brave-browser/issues/22163 for full details.  During security review, we came up with a plan that attempted to solve this. If users aren't already using DNS over HTTP, it would enable this (on Windows only). When disconnecting from VPN, it would revert that config change.

This approach has a few problems
- In edge cases, it's been raised that the config may be lost (need concrete steps; nothing reported yet)
- VPN provider has some filtering logic which uses DNS
- This work-around would only ever work inside Brave and not on the entire system

## Steps to Reproduce

   1. Be on Windows
   2. Enable brave://flags/#brave-vpn
   3. Purchase VPN from staging (https://account.bravesoftware.com)
   4. Connect to VPN

## Actual result:
DNS over HTTP defaults to `1.1.1.1` and becomes enabled

## Expected result:
DNS over HTTP should not be affected

## Reproduces how often: 
100%

**Comment by kjozwiak** [comment]
The above requires `1.45.69` or higher for `1.45.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using 
```
Brave | 1.45.75 Chromium: 106.0.5249.65 (Official Build) beta (64-bit)
-- | --
Revision | 3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}
OS | Windows 11 Version 21H2 (Build 22000.978)
```

Reproduced using STR from the description https://github.com/brave/brave-browser/issues/25488#issue-1378505633 using `1.45.67`

Ex1|Ex2|Ex3
---|---|---
<image width="1500" alt="step2" src="https://user-images.githubusercontent.com/98358127/192660523-4f49ee8f-19de-420a-859f-de454041f5f9.png">|<image width="1500" alt="step2" src="https://user-images.githubusercontent.com/98358127/192660631-ab53bb52-aba3-4b6b-87d5-cb929507bd52.png">|<image width="1500" alt="step2" src="https://user-images.githubusercontent.com/98358127/192661611-7ee9ecab-d70c-4de4-8d1f-98bd3a6ab810.png">

Steps: 

1. Install 1.45.75
2. launch Brave
3. Purchase and setup Brave VPN 
4. Connect to a region - (`Netherlands`)
5. open `brave://settings/security`
6. confirmed  DNS over HTTP defaults to default selection `With your current service provider` in the `Use secure DNS` section
7. load `browserleaks.com/dns` 
8. confirmed no "local" (ISP, i.e. non-VPN-region) DNS-server addresses shown as all DNS queries are resolved by the VPN

step 3-4|step 5-6|step 7-8
----|----|------
<image width="1500" alt="step2" src="https://user-images.githubusercontent.com/98358127/192662064-b245c586-5f1c-432e-9cbd-3c380415ee97.png">|<image width="1500" alt="step2" src="https://user-images.githubusercontent.com/98358127/192659138-3cd61492-90ca-49d9-86c3-83f1926dfce6.png">|<image width="1500" alt="step2" src="https://user-images.githubusercontent.com/98358127/192661313-bc344cf2-70d9-41dc-9a6d-7c1852f533ba.png">

**Comment by stephendonner** [comment]
## Verification `PASSED` using 

Brave | 1.45.84 Chromium: 106.0.5249.91 (Official Build) beta (x86_64)
-- | --
Revision | fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}
OS | macOS Version 11.7 (Build 20G817)

### Steps:

1. installed `1.45.84`
2. launched Brave
3. purchased and set up Brave VPN
4. connected to the `USA (Central)` region
5. opened `brave://settings/security`
6. confirmed `Use secure DNS` defaults to `ON`
7. confirmed `With your current service provider` radio button is selected 
8. loaded `browserleaks.com/dns`


steps 1-4 | steps 5-7 | step 8
----------|-----------|-------
<img width="1316" alt="Screen Shot 2022-10-03 at 2 00 36 PM" src="https://user-images.githubusercontent.com/387249/193650258-0bea2deb-5457-4145-9e0f-3c694ec01565.png"> | <img width="1194" alt="Screen Shot 2022-10-03 at 2 04 18 PM" src="https://user-images.githubusercontent.com/387249/193650263-3c647712-a5c8-44e9-9410-bfde067c9dd7.png"> | <img width="1194" alt="Screen Shot 2022-10-03 at 2 05 13 PM" src="https://user-images.githubusercontent.com/387249/193650265-eacdad01-74fb-47d5-b816-8d3e71dae6d1.png">



#### Confirmed no "local" (ISP, i.e. non-VPN-region) DNS-server addresses shown as all DNS queries are resolved by the VPN as expected

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

Brave | 1.45.84 Chromium: 106.0.5249.91 (Official Build) beta (64-bit) 
--|--
Revision | fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}
OS | Linux

`1.44.103`

settings | browserleaks.com/dns
---------|-----------------------

`1.45.84`

settings | browserleaks.com/dns
---------|-----------------------
