### ISSUE TITLE
Contribution to translate user interface in Dutch for iPad

### ISSUE THREAD

**Issue by josgrp** [brave/brave-browser#25487]
## Description 

I use the Brave browser on Windows, Android and on the iPad.
For the first two systems the user interface can be displayed in Dutch.
For the last one this is not possible.
I can see from the description on the App Store that there's not yet a Dutch version.
I would like to help translating.

## Steps to Reproduce

   1. 
   2. 
   3. 

## Brave version (info found on brave://version)

Version 1.42 (22.8.15.22)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by iccub** [comment]
Hi we are handling it in this ticket https://github.com/brave/brave-browser/issues/36939
