### ISSUE TITLE
`Monthly auto contribution limit` dropdown is empty in brave://settings/rewards page

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#25494]
## Description 

`Monthly auto contribution limit` dropdown is empty in brave://settings/rewards page

## Steps to Reproduce

   1. Clean profile 
   2. Enable rewards
   3. Open brave://settings/rewards page
   4. `Monthly auto contribution limit` dropdown is empty in brave://settings/rewards page

## Actual result:

`Monthly auto contribution limit` dropdown is empty in brave://settings/rewards page
![image](https://user-images.githubusercontent.com/38657976/191183886-597b5bbd-edd9-488d-af8f-adc259b07784.png)

## Expected result:

`Monthly auto contribution limit` dropdown should not be empty in brave://settings/rewards page
## Reproduces how often: 

Intermittent 
## Brave version (brave://version info)

Brave | 1.45.59 Chromium: 106.0.5249.40 (Official Build) nightly (64-bit)
-- | --
Revision | fab1d91915d2722d6339aaa7f4e9ce44f1e9b103-refs/branch-heads/5249@{#442}
OS | Windows 10 Version 21H2 (Build 19044.2006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @Miyayes @emerick

**Comment by Miyayes** [comment]
When you refresh it does resolve it, so it could just be an async call thing.

**Comment by Miyayes** [comment]
no longer relevant since we now use brave://rewards
