### ISSUE TITLE
Unable to add ETH POW as Custom Network

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#25493]
## Description 
Unable to add ETH POW as Custom Network in `[Version 1.45.59 Chromium: 106.0.5249.40 (Official Build) nightly (x86_64)](https://brave.com/latest/)`

![Screen Shot 2022-09-20 at 12 04 03 AM](https://user-images.githubusercontent.com/40611140/191171806-5ef8f729-6f95-4b43-82c1-72ae1d29031d.png)

**Comment by kjozwiak** [comment]
The above requires `1.45.78` or higher for `1.45.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (64-bit) 
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | Linux

- Verified steps from [brave/brave-core#15168](https://github.com/brave/brave-core/pull/15168)
- Verified able to add ETH POW network

https://user-images.githubusercontent.com/17010094/195395002-c41e07d8-71dd-4d26-b383-a65aec8262d7.mp4


------------------------
Verification passed on

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (64-bit) 
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | Windows 11 Version 21H2 (Build 22000.978)

- Verified steps from [brave/brave-core#15168](https://github.com/brave/brave-core/pull/15168)
- Verified able to add ETH POW network

https://user-images.githubusercontent.com/17010094/195396222-71bf9e58-3a0a-443c-ae80-7eca1141faec.mp4


------------------------
Verification passed on

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (arm64)
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [brave/brave-core#15168](https://github.com/brave/brave-core/pull/15168)
- Verified able to add ETH POW network

https://user-images.githubusercontent.com/17010094/195394087-f4913ae4-95b7-4f33-a794-f978bda4637a.mov
