### ISSUE TITLE
Browser crashes when switching system language while in wallet

### ISSUE THREAD

**Issue by wchen342** [brave/brave-browser#25497]
## Description 
While the browser is on BuySendSwap screen, changing the system language will cause it to crash.

## Steps to reproduce 

   1. Open wallet, go to e.g. Send screen.
   2. Go to Android's system settings -> Language, and change the first language from, e.g. English to French.
   3. Go back to the browser with app switcher, see crash.

## Actual result 
![Screenshot_20220920-135201](https://user-images.githubusercontent.com/6406743/191240916-9ccff1ff-8e31-4f8f-a22f-c1779f69a400.png)
![Screenshot_20220920-135234](https://user-images.githubusercontent.com/6406743/191241048-ab846ea6-0343-4539-9c87-78e68cfe2cc6.png)
![Screenshot_20220920-135225](https://user-images.githubusercontent.com/6406743/191241073-a5c46baf-7736-4ade-a854-022c88507f6d.png)

## Expected result
No crash.

## Issue reproduces how often 
Always

## Version/Channel Information:

nightly/master

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): arm64
   - Device type (Phone, Tablet, Phablet): phone
   - Android version: 12
   
## Brave version
Master

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Couldn't repro the crash with above steps on 1.45.63 Playstore build.

**Comment by HEagle18** [comment]
I couldn't replicate either.
