### ISSUE TITLE
Sync `add device` and `view sync code` duplicate functionality

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#2549]
## Steps to Reproduce

   1. Sync two device on Desktop

## Actual result:

Buttons `add device` and `view sync code` are next to each other yet their functionality is the same: to show `QR code` and `Word code`
![image](https://user-images.githubusercontent.com/34715963/49958091-12810000-ff0a-11e8-8bce-3494e886429d.png)

`add device` button:
![sync3](https://user-images.githubusercontent.com/34715963/49958260-891dfd80-ff0a-11e8-8d8f-540fe6c089f7.gif)

`view sync code` button
![image](https://user-images.githubusercontent.com/34715963/49956318-30983180-ff05-11e8-981e-32a38114b708.png)

## Brave version (brave://version info)

Brave | 0.58.12 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Windows 7

cc @brave/legacy_qa

**Comment by bradleyrichter** [comment]
@btlechowski 

"Add Device" takes the user through 90% of the wizard again to help them add a new device. It is working correctly.

"View Sync Code" is an advanced use button that requires a DIY approach. I don't think it will become a usability problem but we can monitor for it.

**Comment by rebron** [comment]
Won't fix. As designed. Let's consider changing "view sync code" text to "view QR code and word code"
File separately cc: @srirambv
