### ISSUE TITLE
Developer mode in Extension Collect Errors 

### ISSUE THREAD

**Issue by SWxEng** [brave/brave-browser#25490]
Hi

What is it ? What is his job ? Collect Errors 

![d5acb138034b260323296ae17db16dafbe64035a](https://user-images.githubusercontent.com/55116927/191117296-498a796a-fc2e-45b6-a2f9-b1fda4480140.png)

**Comment by rebron** [comment]
Hi @SWxEng Here's some more information on Developer mode and the Collect errors option.
https://developer.chrome.com/docs/extensions/mv3/tut_debugging/

**Comment by SWxEng** [comment]
Done ..... Thank You
