### ISSUE TITLE
Use and install PDFJS by default 

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#255]

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | -- 
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Linux

* Verified clean install has PDFJS installed and enabled
* Verified http://pdf99.com/samples/pdf.pdf loads the PDF file correctly
