### ISSUE TITLE
Add promo card for Brave Creators (`creators.brave.com`) on Brave Rewards settings page

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#25503]
## Description

- [ ] Add promo card for https://creators.brave.com on brave://rewards page (all geos)

* This will be a traditional promo card (`117 x 157px`) image on the left with text on the right.
* This should be enabled in all geos. 
* Put it at the top (1st position) 

**Designs:** https://www.figma.com/file/JDpW9ykhiWysTLvs35JtsF/BR20-proposal?node-id=0%3A10424

cc: @bradleyrichter

**Comment by Miyayes** [comment]
**Pre-cropped asset:**

![Illustration](https://user-images.githubusercontent.com/11497541/193352833-f71805f9-a5d1-4203-82f6-fcc94b7a2795.svg)

**Uncropped asset:** ![bat-website-hero](https://user-images.githubusercontent.com/11497541/193352890-c86d9e9c-5a80-4449-863d-f041b7295cbc.svg)

**Comment by emerick** [comment]
@Miyayes I'm assuming that URL was accidentally transposed in the description and should be https://creators.brave.com/ but let me know?

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.47.119 Chromium: 108.0.5359.99 (Official Build) beta (x86_64)
-- | --
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | macOS Version 12.6.1 (Build 21G217)
```
