### ISSUE TITLE
Remove "Switch to Brave Search" prompt

### ISSUE THREAD

**Issue by UjCbFwtBayFM** [brave/brave-browser#25505]
## Description 
Brave inserts a huge "Switch to Brave Search" overlay prompt every single time I open a new blank tab. Engine is already set to Brave search, which means it does not even check the current engine. 

This lack of check aside, **this is completely unacceptable behavior on your end to tell users they should use your search engine. Pushing your own products down people's throat is something I could expect from entities like Google or Microsoft, not Brave. REMOVE THAT.** You even have the hubris to claim you don't bias or censor results.

## Steps to Reproduce

   1. Open a new tab

## Actual result:
Prompt appears
![ReCutvVrRq](https://user-images.githubusercontent.com/22710992/191341848-1fe11ef4-cded-4a4a-a50a-aedc36197caf.png)

## Expected result:
Brave should not suggest I switch my search engine.

## Reproduces how often: 
Every time I open a new tab.

## Brave version (brave://version info)
<html>
<body>

Brave | 1.45.64 Chromium: 106.0.5249.40 (Official Build) nightly (64-bit)
-- | --
Revision | fab1d91915d2722d6339aaa7f4e9ce44f1e9b103-refs/branch-heads/5249@{#442}
OS | Windows 10 Version 21H1 (Build 19043.1889)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by kjozwiak** [comment]
@UjCbFwtBayFM just curious, what's your default search engine for `Normal` windows via `brave://settings/search`? For example, mine appears as the following via Nightly:

![image](https://user-images.githubusercontent.com/2602313/191351476-91086109-32ca-46f5-9e95-044a1b4ee4ec.png)

> Brave inserts a huge "Switch to Brave Search" overlay prompt every single time I open a new blank tab. Engine is already set to Brave search, which means it does not even check the current engine.

If it's set as `Brave`, you should definitely not be seeing the above. You can also click on the `X` button which should dismiss the promo/panel. Once dismissed, you shouldn't see it appearing again.

![panel](https://user-images.githubusercontent.com/2602313/191351823-7b3ce80d-bcd3-41b4-a7c9-849db858b00e.png)

**Comment by UjCbFwtBayFM** [comment]
> You can also click on the `X` button which should dismiss the promo/panel. Once dismissed, you shouldn't see it appearing again.

It looks like you have trouble understanding the issue here, so I will rephrase my initial statement in simple terms: this screen should NOT appear _at all_. There is no justification for this kind of despicable way of promoting it.  The people who greenlight it are idiots that do not care about UX.

**Revert this.**

**Comment by Brave-Matt** [comment]
@UjCbFwtBayFM,
We're all on the same team here — or at least we're supposed to be. Insults and ultimatums are not going to get your issue resolved any faster or your point across any clearer. Please keep your comments and reports civil and we'll be more than happy to listen and assist you. 

Thank you.

**Comment by UjCbFwtBayFM** [comment]
@Brave-Matt Remove this feature, or loose supporters and users.

**Comment by bsclifton** [comment]
Closing as this experiment (Nightly only) should have concluded a while back and this has been disabled for a while, AFAIK

cc: @rebron

**Comment by johnnymatthews** [comment]
It's back, albeit in a smaller form-factor.

<img width="431" height="108" alt="Image" src="https://github.com/user-attachments/assets/56985ad4-7cc3-42b8-8275-68eaf1af79b6" />

For folks finding this issue after searching for a solution, just click that little `x` next to *Switch to Brave Search*. It seems that the browser gets the hint and stops that little prompt from showing up.
