### ISSUE TITLE
Double Scrollbar when onboarding and unnecessary scrollbar on `brave://wallet` page

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#25502]
## Description 

Double Scrollbar when onboarding and unnecessary scrollbar on `brave://wallet` page

## Steps to Reproduce

   1. Clean profile 
   2. Open `brave://wallet`, shows scrollbar
   3. Continue with onboarding, shows second scrollbar
   4. Finish onboarding second scrollbar is removed only one is shown 

## Actual result:

https://user-images.githubusercontent.com/17010094/191303720-5eddf62f-cf9c-4d8a-aad2-fd2da6c1a1c3.mp4

## Expected result:
Do not show scroll bar if its not required 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.44.93 Chromium: 105.0.5195.136 (Official Build) beta (64-bit) 
-- | --
Revision | `872774b783d0e674186a3adcd2f92e7aa22a219c-refs/branch-heads/5195_124@{#4}`
OS | Windows 11 Version 21H2 (Build 22000.978)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel @josheleonard

**Comment by kjozwiak** [comment]
The above requires `1.45.68` or higher for `1.45.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.45.85 Chromium: 106.0.5249.91 (Official Build) beta (64-bit) 
-- | --
Revision | `fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}`
OS | Linux

- Verified steps from issue description & [brave/brave-core#15143](https://github.com/brave/brave-core/pull/15143)
- Verified no additional scrollbars are shown during onboarding

https://user-images.githubusercontent.com/17010094/194115624-dfc4cea1-ff6c-4314-bef3-b032a7fd4931.mp4


------------------------
Verification passed on

Brave | 1.45.85 Chromium: 106.0.5249.91 (Official Build) beta (64-bit) 
-- | --
Revision | `fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}`
OS | Windows 11 Version 21H2 (Build 22000.978)

- Verified steps from issue description & [brave/brave-core#15143](https://github.com/brave/brave-core/pull/15143)
- Verified no additional scrollbars are shown during onboarding

https://user-images.githubusercontent.com/17010094/194114434-cd58ed47-4e8b-4249-8d97-3554c6360a03.mp4

------------------------
Verification passed on

Brave | 1.45.85 Chromium: 106.0.5249.91 (Official Build) beta (arm64)
-- | --
Revision | `fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from issue description & [brave/brave-core#15143](https://github.com/brave/brave-core/pull/15143)
- Verified no additional scrollbars are shown during onboarding

https://user-images.githubusercontent.com/17010094/194113449-4a2ce3b6-cc4f-4eed-a8dc-45df57e83d53.mov
