### ISSUE TITLE
Brave news feed doesn't show when enabled through settings

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#25500]
## Description 
Enabling brave news using the switch in the menu and then navigating back to NTP will still show news modal.

## Steps to reproduce 

   1. Clean profile
   2. Navigate to menu > Brave News > Enable Show Brave News
   3. Return to NTP

## Actual result 
Brave News Card is still shown. news feed not shown

https://user-images.githubusercontent.com/17885425/191292471-682d16ed-cd6d-440c-9229-531ec62f9e38.mp4

## Expected result
News feed should be shown

## Issue reproduces how often 
Always

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? N/A
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung GS 21
   - Android version: 12
   
## Brave version
1.45.x, 1.43.x

**Comment by kjozwiak** [comment]
The above requires `1.44.97` or higher for `1.44.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S 21` & `Galaxy Tab S7` using the following build(s): 

```
Brave	1.44.97 Chromium: 106.0.5249.55 (Official Build) (64-bit) 
Revision	4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}
OS	Android 12; Build/SP1A.210812.016
```

- Ensured news feed is shown immediately after enabling `Show Brave News` in the Brave News menu.
- Ensured news feed is not shown if disabled via the settings menu.
- Ensured that the news feed can be re-enabled after disabling.

https://user-images.githubusercontent.com/17885425/191766541-88993e64-8d54-41fa-b490-08245453bdfe.mp4
