### ISSUE TITLE
`Previous` and `OK` yield the same action in `add device`

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#2550]
## Steps to Reproduce

1. Sync two device on Desktop
2. Click `add device`

## Actual result:

`Previous` and `OK` yield the same action in `add device`

For `Phone/Tablet`
![sync4](https://user-images.githubusercontent.com/34715963/49958553-78ba5280-ff0b-11e8-86ea-d181a5989abe.gif)

For `Computer`
![sync4b](https://user-images.githubusercontent.com/34715963/49958554-7952e900-ff0b-11e8-81e3-e49957cdb7fa.gif)

## Brave version (brave://version info)

Brave | 0.58.12 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Windows 7

cc @brave/legacy_qa

**Comment by bradleyrichter** [comment]
This is a bug. It should be showing the "looking for device" button status:

![image](https://user-images.githubusercontent.com/13509546/49973528-56fca380-feea-11e8-96f4-5a36013d2fdb.png)

**Comment by cezaraugusto** [comment]
moving to 0.59 per last sync meeting
