### ISSUE TITLE
Brave News Subscribe Button UX

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#25510]
Now we have a lovely UX mockup for how the dialog should look the UI should be updated:

[Figma Design](https://figma.com/file/w13WS9lovJubjbSjtK1fVo/Brave-Desktop---Add-to-Brave-News?node-id=129%3A12747)

Dark Mode
![image](https://user-images.githubusercontent.com/7678024/191413838-60691293-6b1e-457a-81ff-9c6162d27723.png)

Light Mode
![image](https://user-images.githubusercontent.com/7678024/191413883-5f3d4d3e-78a2-452b-96e6-b27e37690fbb.png)

**Comment by LaurenWags** [comment]
@fallaciousreasoning could we get a test plan for this one please? Marking as `QA/Blocked` until we have that 👍🏻 

cc @rebron @kjozwiak

**Comment by fallaciousreasoning** [comment]
Added!
