### ISSUE TITLE
Occasionally crashing after installing Brave VPN profile

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#25513]
## Description 

Occasionally crashing after installing Brave VPN profile

## Steps to Reproduce

1. install `1.45.66`
2. go through onboarding
3. tap the 3-dots menu
4. tap `Settings`
5. tap `Developer Options`
6. tap `QA Preferences`
7. enter the QA code (from 1PW)
8. tap to enable `Brave VPN` to `On`
9. tap `Relaunch Now`
10. tap on the 3-dots menu
11. tap on `Brave VPN`
12. tap on `Monthly subscription`
13. tap on `Subscribe`
14. confirm the VPN-profile installation

## Actual result:

Sometimes, crash (`https://share.backtrace.io/api/share/JPPEriex3tJjpx36vT3FQRk1`):

```
[ 00 ] 0xc59254c8
[ 01 ] 0xc5928d87
[ 02 ] 0xc7c05de6
[ 03 ] 0xc58cfb11
[ 04 ] 0xc7c05de6
[ 05 ] 0xc5928ebb
[ 06 ] 0xc58d84ff
[ 07 ] 0xc58d851f
[ 08 ] 0xc38b4c6b
[ 09 ] 0xc3952859
[ 10 ] 0xc58d84c3
[ 11 ] 0xc60be6e7
[ 12 ] 0xc376e9b5
[ 13 ] 0xc60c21cf
[ 14 ] 0xc38b189d
[ 15 ] 0xc781165d
[ 16 ] 0xc7ad4f3a
[ 17 ] 0xc781178b
[ 18 ] 0xc40d7d58
[ 19 ] 0xc7822e6b
[ 20 ] 0xc40d7d58
[ 21 ] 0xc40d7d58
[ 22 ] 0xc40d7cff
[ 23 ] 0xc40d7d7b
[ 24 ] 0xc7822ee5
[ 25 ] 0xc40d7d7b
[ 26 ] 0xc40d7cff
[ 27 ] 0xc787e5c5
[ 28 ] 0xc40d7d7b
[ 29 ] 0xca04b07f
[ 30 ] 0xe7c8c575
[ 31 ] 0xe7c65c95
[ 32 ] 0xe7c650f3
[ 33 ] 0xca6ad676
[ 34 ] 0xca6ad67a
[ 35 ] 0xe7c8bece
[ 36 ] 0xe7a78caf
[ 37 ] 0xe7a43d55
[ 38 ] 0xca89a4cf
[ 39 ] 0xe7920029
[ 40 ] 0xca89a4cf
[ 41 ] 0xca09ebde
[ 42 ] 0xe7a64aeb
[ 43 ] 0xca89a4cf
[ 44 ] 0xe7a5f5d9
[ 45 ] 0xca286974
[ 46 ] 0xe7c617c9
[ 47 ] 0xca286952
[ 48 ] 0xca286974
[ 49 ] 0xe7c7bbfe
[ 50 ] 0xe7c7f496
[ 51 ] 0xe7a78caf
[ 52 ] 0xe7a43d55
[ 53 ] 0xe7a48381
[ 54 ] 0xe7c542d3
[ 55 ] 0xca286974
[ 56 ] 0xca286942
[ 57 ] 0xca899c47
[ 58 ] 0xca286942
[ 59 ] 0xe7cee4c6
[ 60 ] 0xca899c47
[ 61 ] 0xe7c90b01
[ 62 ] 0xe9b2ee8d
[ 63 ] 0xe9b29373
[ 64 ] 0xe9b709ee
[ 65 ] 0xe9b7137e
[ 66 ] 0xe9b70a1e
[ 67 ] 0xe9b709f2
[ 68 ] 0xe9b684ff
[ 69 ] 0xe7c8c575
[ 70 ] 0xe7c65b93
[ 71 ] 0xe9b29373
[ 72 ] 0xe9b709ee
[ 73 ] 0xe9b7137e
[ 74 ] 0xe9b70a1e
[ 75 ] 0xe9b709f2
[ 76 ] 0xe9b684ff
[ 77 ] 0xca899c47
[ 78 ] 0xe7920017
[ 79 ] 0xca899c47
[ 80 ] 0xca899c47
[ 81 ] 0xca899c47
[ 82 ] 0xe7bc6ac7
[ 83 ] 0xca899c47
[ 84 ] 0xe7c01f17
[ 85 ] 0xe7cf42e6
[ 86 ] 0xe7ca27b8
[ 87 ] 0xe7cf236a
[ 88 ] 0xe7ab28cd
[ 89 ] 0xe7bf2263
[ 90 ] 0xeb9b04ea
[ 91 ] 0xca899c47
[ 92 ] 0xe7bc781f
[ 93 ] 0xca899c47
[ 94 ] 0xca899c47
[ 95 ] 0xe7cf3e92
[ 96 ] 0xe7ca3056
[ 97 ] 0xe79730bf
[ 98 ] 0xe7cf3e92
[ 99 ] 0xe7ca3056
[ 100 ] 0xe7be87b1
[ 101 ] 0x7268540e
[ 102 ] 0xeb9b04ea
[ 103 ] 0xe9b254d9
[ 104 ] 0xe9b254c1
[ 105 ] 0xe9adff29
[ 106 ] 0xe9b254c1
[ 107 ] 0xe7be844b
```

## Expected result:

Relaunch without crashing

## Reproduces how often: 

1/3rd of the time?

## Brave version (brave://version info)

1.45.66, Chromium 106.0.5249.40, Android 9, Google Pixel XL

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A`
- Can you reproduce this issue with the beta channel? `haven't tried`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @deeppandya @bsclifton @srirambv

**Comment by bsclifton** [comment]
@deeppandya can you check this out?

**Comment by stephendonner** [comment]
https://user-images.githubusercontent.com/387249/191428228-90f88307-9564-49ea-8564-65a62469cb29.mp4

**Comment by deeppandya** [comment]
@stephendonner can you verify this issue again with latest master ? we encountered a bug with P3A and resolved it. so it should be good

**Comment by stephendonner** [comment]
Dupe of https://github.com/brave/brave-browser/issues/25704
