### ISSUE TITLE
Vertical Tabs Sidebar Not Hiding in Full Screen Mode

### ISSUE THREAD

**Issue by friedITguy** [brave/brave-browser#25511]
## Description 
The vertical tabs sidebar is not 'hiding' when entering full screen mode. With the vertical tabs experiment flag disabled, the tabs bar disappears as expected.

## Steps to Reproduce
   1. Enable the vertical tabs experiment and relaunch the browser
   2. Press F11 on any webpage, or navigate to a video and press the 'full screen' button in the video controls
   3. The browser will enter full screen mode, prompting you to press Esc to exit the mode

## Actual result:
The tabs sidebar is still visible when in full screen mode

## Expected result:
The tabs sidebar should 'hide' (not be visible) until after exiting full screen mode

## Reproduces how often: 
Easily reproduced on the nightly build for Windows and MacOS.

### Nightly Build - Windows
**Brave:** 1.45.59 Chromium: 106.0.5249.40 (Official Build) nightly (64-bit)
**Revision:** fab1d91915d2722d6339aaa7f4e9ce44f1e9b103-refs/branch-heads/5249@{#442}
**OS:** Windows 11 Version 21H2 (Build 22000.978)
### Nightly Build - MacOS
**Brave:** 1.45.64 Chromium: 106.0.5249.40 (Official Build) nightly (x86_64)
**Revision:** fab1d91915d2722d6339aaa7f4e9ce44f1e9b103-refs/branch-heads/5249@{#442}
**OS:** macOS Version 12.5.1 (Build 21G83)
### Source Build
**Brave:** 1.45.50 Chromium: 105.0.5195.127 (Developer Build) (64-bit)
**Branch:** [sko/vertical-tabs](https://github.com/brave/brave-core/pull/13816)
**Commit:** [05f70cb](https://github.com/brave/brave-core/commit/05f70cb3193717ad292f87a21bb449085fb49ebf)

## Version/Channel Information:
The vertical tabs experiment is only available on nightly, so the issue only impacts that channel. I can reproduce it on the nightly channel.

I can also reproduce the issue in the last commit from the vertical tabs experiment. See the **Source Build** version info above for links to the commit and experiment pull.

## Other Additional Information:
None

## Miscellaneous Information:
None

**Comment by friedITguy** [comment]
This issue was originally [reported](https://github.com/brave/brave-browser/issues/464#issuecomment-1252833406) on #464

**Comment by sangwoo108** [comment]
@friedITguy Thank you for reporting! Let me take a look!

**Comment by friedITguy** [comment]
@sangwoo108, I see the issue is resolved when entering full screen mode using video controls, thanks for fixing that. The tabs bar is hidden, as expected. However, I still see the tabs bar when entering full screen mode by pressing F11. Is this expected behavior?

**Comment by sangwoo108** [comment]
Hi, @friedITguy ! Thanks for checking out. I think it's what I expected. Doesn't the sidebar work the same?

**Comment by friedITguy** [comment]
> Hi, @friedITguy ! Thanks for checking out. I think it's what I expected. Doesn't the sidebar work the same?

Ahh, yes it does. The normal tabs bar hides when pressing F11, but the vertical tabs and the sidebar are both visible when pressing it.

**Comment by sangwoo108** [comment]
Yeah, if so, it's what's implemented. If you feel it's too annoying, please let us know. We'll see what can be done for this and sidebar altogether in fullscreen mode. One more thing we can rely on is that "auto hiding / hover to show up" feature is being considered. That might help you.

**Comment by friedITguy** [comment]
> Yeah, if so, it's what's implemented. If you feel it's too annoying, please let us know. We'll see what can be done for this and sidebar altogether in fullscreen mode. One more thing we can rely on is that "auto hiding / hover to show up" feature is being considered. That might help you.
> 
> cc. @rebron : we might need to give a second thought to sidebar and vertical tabs' visibility on fullscreen mode.

Personally, I very rarely use my browser in fullscreen, outside of watching videos. The only situations in which I've used F11 were for kiosks (where you want the site to appear like an app). However, in that scenario, I wouldn't need vertical tabs. 

So, it's not an issue that will impact me at all. I just wanted to make sure you're aware of it in case it was unintentional.

"Auto hiding / hover to show up" on the other hand is a feature I would love to see. If there's an open issue or PR for that please let me know so I can follow it. Thanks!

**Comment by sangwoo108** [comment]
Here it is https://github.com/brave/brave-browser/issues/25474 :)

**Comment by Coffeeling** [comment]
> Yeah, if so, it's what's implemented. If you feel it's too annoying, please let us know. We'll see what can be done for this and sidebar altogether in fullscreen mode. One more thing we can rely on is that "auto hiding / hover to show up" feature is being considered. That might help you.
> 
> cc. @rebron : we might need to give a second thought to sidebar and vertical tabs' visibility on fullscreen mode.

Hover to show up seems like the best of both worlds - you can get a clutter-free full screen experience but show nav tools if needed.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (x86_64)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | macOS Version 11.7.1 (Build 20G918)



### Steps:
1. installed `1.46.81`
2. launched Brave
3. set `brave://flags/#brave-vertical-tabs` to `Enabled`
4. clicked `Relaunch`
5. loaded `https://www.youtube.com/watch?v=b3ootXSAaqE`
6. clicked on the `Full Screen (f)` control within YouTube
7. exited `Full Screen` mode

#### Confirmed the vertical-tab strip was visible, then hidden in `Full Screen` mode, then visible again after exiting `Full Screen`

`step 5` | `step 6` | `step 7`
-------|--------|------
<img width="1312" alt="Screen Shot 2022-10-27 at 3 46 46 PM" src="https://user-images.githubusercontent.com/387249/198412137-bd6370d9-32ce-4cfa-97b5-b9674599b503.png"> | ![Screen Shot 2022-10-27 at 3 46 59 PM](https://user-images.githubusercontent.com/387249/198412141-02c98066-8471-43ac-833e-cfd5651ce908.png) | <img width="1312" alt="Screen Shot 2022-10-27 at 3 47 06 PM" src="https://user-images.githubusercontent.com/387249/198412147-7cd4434b-88c6-49b7-aa50-2b6548b7abb4.png">

**Comment by hash4q** [comment]
I see black screen in place of vertical tabs in full screen

**Comment by xoldyckk** [comment]
Same issue for me. But it started only when I updated to this newer version today. It was working fine till last day :- 
**1.47.171 Chromium: 109.0.5414.87 (Official Build) (64-bit)**

![full_screen](https://user-images.githubusercontent.com/82873939/212335256-895035a1-b622-4b09-8806-53c78c1f1459.png)

**Comment by sangwoo108** [comment]
Hi, @xoldyckk . Sorry for the inconvinience. I believe it's fixed on nightly and will take some time for it to applied to official version.

**Comment by Arcadio-Buendia** [comment]
I am using Brave Browser 114.1.52.130 on Debian Linux and facing the same problem. The vertical tab strip doesn't disappear on full-screen, only the addressbar does. If the tabs are horizontal, they do disappear.


![image](https://github.com/brave/brave-browser/assets/67139441/613b030c-5884-458e-aefe-5211093d6a9b)

**Comment by sangwoo108** [comment]
Hi, @Arcadio-Buendia 

I think that's what we expected. We don't hide vertical tabs when you enter fullscreen via Window menu. We only hide it when full screen is triggered from media contents,like youtube.
