### ISSUE TITLE
Interstitial UI for ENS L2 offchain contenthash resolution

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#25515]
ENS L2 was implemented here https://github.com/brave/brave-browser/issues/22930
Wallet UI here https://github.com/brave/brave-browser/issues/24990

This issue covers work for asking user consent to use offchain lookup in case of omnibox scenario

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (64-bit)
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | Linux

- Verified steps from [brave/brave-core#15151](https://github.com/brave/brave-core/pull/15151)
- Verified as part of [#24430 (comment)](https://github.com/brave/brave-browser/issues/24430#issuecomment-1296716895)
- Verified when setting is disabled, IPFS address resolution fails
![image](https://user-images.githubusercontent.com/17010094/198959697-0d269bf3-e532-416f-a6a3-8ff3edc8d55b.png)

----------------
Verification passed on 

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (64-bit)
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | Windows 11 Version 22H2 (Build 22621.674)

- Verified steps from [brave/brave-core#15151](https://github.com/brave/brave-core/pull/15151)
- Verified as part of [#24430 (comment)](https://github.com/brave/brave-browser/issues/24430#issuecomment-1296716895)
- Verified when setting is disabled, IPFS address resolution fails
![image](https://user-images.githubusercontent.com/17010094/198958592-a9116fa2-570f-4497-88f1-af4b65e4e1fd.png)

----------------
Verification passed on 

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (arm64)
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | macOS Version 12.6 (Build 21G115)

- Verified steps from [brave/brave-core#15151](https://github.com/brave/brave-core/pull/15151)
- Verified as part of [#24430 (comment)](https://github.com/brave/brave-browser/issues/24430#issuecomment-1296716895)
- Verified when setting is disabled, IPFS address resolution fails
![image](https://user-images.githubusercontent.com/17010094/198959874-c37d6cee-0d7e-4519-bdad-860bda0ca39f.png)
