### ISSUE TITLE
Integrate Chromium PRESUBMIT.py into build pipeline

### ISSUE THREAD

**Issue by goodov** [brave/brave-browser#25517]
Presubmits support initially implemented in https://github.com/brave/brave-browser/issues/16196 requires some additional work to properly cover brave-core codebase and make it usable during CI runs.

This task aims to make all required changes and add `npm run presubmit` to the build pipeline with ability to quickly disable or ignore some errors during CI rollout.

**Comment by goodov** [comment]
related https://github.com/brave/brave-browser/issues/25805

**Comment by kjozwiak** [comment]
@goodov should this issue be closed? Looks like all the associated PRs that are being listed above have been merged but this issue is still opened. If it needs to stay open, lets remove it from the `1.47.x` milestone.

**Comment by goodov** [comment]
Yes, this is now integrated and can be closed. All follow-ups (if any) will be done in separate issues.
