### ISSUE TITLE
Replace the Muli font with Poppins

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#25527]
We have decided to stop using Muli, which we mainly used for body content. Uses should be replaced with Poppins. When replacing, we generally have to dial down the font-weight a little (e.g. from `600` to `500`).

This requires changes in brave-core and brave-ui (where there are theme variables and shared styles from components).

Places:
- Welcome
- Rewards (page, not panel)
- NTP widgets

## Test Plan
- Open brave://welcome
- Verify that the font being used is Poppins not Muli, via referencing the below screenshots
- Turn on and open brave://rewards. Verify the font (for the "left" column) is correct as per the below screenshots
- Open NTP and switch to Brave Talk widget. Verify screenshots...

### Screenshots (old on right, new on left)
<img width="1613" alt="image" src="https://user-images.githubusercontent.com/741836/191567338-71f6eba2-69fb-40bd-9a89-2ad53a4e5d63.png">
<img width="1601" alt="image" src="https://user-images.githubusercontent.com/741836/191567439-d2b5a5a1-bca1-4ad7-9082-c7397fed9c18.png">
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/741836/191567549-aa8b4e6e-cd7d-4603-a7b8-1faac964fb69.png">

### Notes
If you really want to verify which font is being used, you can inspect the element, switch to the "computed" tab and scroll right to the bottom. DevTools will report which font is being used to actually render.
<img width="612" alt="image" src="https://user-images.githubusercontent.com/741836/191567706-f3ba5685-881f-4003-b039-d3862813839e.png">

**Comment by LaurenWags** [comment]
@brave/qa-team spot check sections listed in https://github.com/brave/brave-browser/issues/25527#issue-1381244003.

@rebron could someone from design team give this a more thorough check with a trained eye?

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.46.56 Chromium: 106.0.5249.119 (Official Build) nightly (64-bit)
-- | --
Revision | 9f2101830b56fd2ea1408287f6c74e253ebcb7c6-refs/branch-heads/5249@{#797}
OS | Windows 11 Version 21H2 (Build 22000.1098)
```

1. Install 1.46.56
2. Launch Brave

`Welcome page`
-------------------
- right click on any element in the page 
- select Inspect
- click  `Computed` tab in `Developer tools`
- scroll down to view the rendered fonts for the page.

### Confirmed `Poppins` font rendered

Muli|Poppins
----|----
![image](https://user-images.githubusercontent.com/98358127/195717563-df0c8134-0e41-4573-baed-cdf9dd78827d.png)|![image](https://user-images.githubusercontent.com/98358127/195716988-0a309498-ca4c-46e7-bfcb-b92d17f15c1b.png)

`Brave Talk` 
------
- open NTP 
- click on  `Brave Talk` to switch to the widget
- right click on any element in the page 
- select Inspect
- click  `Computed` tab in the `Developer tools``
- scroll down to view the rendered fonts for the page.

#### Confirmed `Poppins` font rendered
Muli|Poppins
----|----
![image](https://user-images.githubusercontent.com/98358127/195718090-f609be83-9008-4c93-b8f1-1b6ba30e5244.png)|![image](https://user-images.githubusercontent.com/98358127/195719859-dc61a4a6-77c1-490b-ad47-94c07b76a9ef.png)

Rewards settings page
------
- enable rewards
- open `brave://rewards`
- right click on any element in the page 
- select Inspect
- click  Computed tab in `Developer tools`
- scroll down to view the rendered fonts for the page.

### Confirmed `Poppins` font rendered
Muli|Poppins
----|----
![image](https://user-images.githubusercontent.com/98358127/195719508-5c7c27a6-9ff9-417a-ad7d-c91c2e858b0c.png)|![image](https://user-images.githubusercontent.com/98358127/195720176-5be784fb-9219-468e-bc99-68db7e8e3541.png)

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.46.76 Chromium: 107.0.5304.62 (Official Build) beta (x86_64)
-- | --
Revision | 1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942}
OS | macOS Version 11.7 (Build 20G817)



### Welcome page

1. right click on any element in the page
2. select `Inspect`
3. click `Computed` tab in `Developer` tools
4. scroll down to view the rendered fonts for the page

<img width="1277" alt="Screen Shot 2022-10-24 at 4 32 14 PM" src="https://user-images.githubusercontent.com/387249/197649386-ee7b101c-ab0e-4361-8d18-2135d89043cd.png">

### Confirmed `Poppins` font rendered


### Brave Talk

1. open NTP
2. click on `Brave Talk` to switch to the widget
3. right click on any element in the page
4. select `Inspect`
5. click `Computed` tab in `Developer tools`
6. scroll down to view the rendered fonts for the page


<img width="1626" alt="Screen Shot 2022-10-24 at 4 33 32 PM" src="https://user-images.githubusercontent.com/387249/197649620-3b6c618c-be35-4639-8fd3-ad0d30ad83d0.png">

### Confirmed `Poppins` font rendered


### Rewards Settings page

1. enable Rewards
2. open `brave://rewards`
3. right-click on any element in the page
4. select `Inspect`
5. click `Computed` tab in `Developer tools`
6. scroll down to view the rendered fonts for the page

<img width="1626" alt="Screen Shot 2022-10-24 at 4 34 29 PM" src="https://user-images.githubusercontent.com/387249/197649592-815cfc96-4fbf-4871-baa3-d25f25bcd221.png">

### Confirmed `Poppins` font rendered

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.46.106 Chromium: 107.0.5304.110 (Official Build) beta (64-bit) 
Revision	2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}
OS	Linux
```

**Comment by aguscruiz** [comment]
Adding a few places where Poppins is not loading and it should, so far everything I found is on the NTP

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/15734630/204915439-ede359ca-5bbf-4c2b-923e-179781da9710.png">

<img width="586" alt="image" src="https://user-images.githubusercontent.com/15734630/204915461-c46f3be3-39c9-49d5-ae4f-c5479ac6a2b1.png">


<img width="398" alt="image" src="https://user-images.githubusercontent.com/15734630/204915488-a31800c1-1f8c-4486-9732-8addc54c869a.png">

Brave news:
<img width="275" alt="image" src="https://user-images.githubusercontent.com/15734630/204915534-5b8b0f7e-9237-4bb3-bfbb-4f59e4f836bf.png">

**Comment by LaurenWags** [comment]
@aguscruiz if the places mentioned in https://github.com/brave/brave-browser/issues/25527#issuecomment-1332776558 need to be addressed, please open a new issue for it, thanks!

**Comment by stephendonner** [comment]
> @aguscruiz if the places mentioned in [#25527 (comment)](https://github.com/brave/brave-browser/issues/25527#issuecomment-1332776558) need to be addressed, please open a new issue for it, thanks!

Yes, please; helps us keep scope down considerably <3

**Comment by aguscruiz** [comment]
No problem! Will do, here is the new issue https://github.com/brave/brave-browser/issues/27081
