### ISSUE TITLE
Sync chain should be reset when deleting another device with v2 spec

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#2552]
## Description 

Sync chain didn't get reset when there is only one device left on sync chain

## Steps to Reproduce

   1. Setup sync chain on device a and device b
   2. Delete device b from device a
   3. Setup new chain on device a and connect device b to it
   4. It connect to the previous sync chain. (sync code is still same as step 1)
    

## Actual result:

 It connect to the previous sync chain. (sync code is still same as step 1)

## Expected result:
Sync chain should be reset when there is only one device on sync chain

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
Verified the STR mentioned in https://github.com/brave/brave-core/pull/1109. Issue still persists hence reopening the issue.
![2552](https://user-images.githubusercontent.com/38657976/50421103-e0ed2a80-0861-11e9-979c-731ec381ab13.gif)

**Comment by darkdh** [comment]
@GeetaSarvadnya can we close this issue because you open https://github.com/brave/brave-browser/issues/2737 for tracking it?

**Comment by GeetaSarvadnya** [comment]
Verification passed on 


Brave | 0.59.18 Chromium: 72.0.3626.28 (Official Build) beta (64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Windows

- Verified the STR from https://github.com/brave/brave-core/pull/1109.
