### ISSUE TITLE
`Hide Side Panel Icon`menu-item text should read `Hide Side Panel icon`

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#25532]
## Description 

`Hide Side Panel Icon` menu-item text should read `Hide Side Panel icon`

## Steps to Reproduce

   1. install `1.44.95`
   2. launch Brave
   3. context-click on the side-panel icon, next to the wallet icon, on the main toolbar
   4. look at its menu-item text text

## Actual result:

`Hide Side Panel Icon`

<img width="1112" alt="Screen Shot 2022-09-21 at 11 07 37 AM" src="https://user-images.githubusercontent.com/387249/191579003-ca99d1c2-ad07-4cf8-b9e9-1d844245d14a.png">

## Expected result:

`Hide Side Panel icon`

example | example
---------|---------
<img width="334" alt="Screen Shot 2022-09-21 at 11 07 56 AM" src="https://user-images.githubusercontent.com/387249/191578917-36aa4555-7f2b-4475-b218-88540b1aa7a8.png"> | <img width="336" alt="Screen Shot 2022-09-21 at 11 08 05 AM" src="https://user-images.githubusercontent.com/387249/191578922-d8dbd95d-0a23-4c04-a41d-146b275fbf0b.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.44.95 Chromium: 106.0.5249.40 (Official Build) (x86_64)
-- | --
Revision | fab1d91915d2722d6339aaa7f4e9ce44f1e9b103-refs/branch-heads/5249@{#442}
OS | macOS Version 11.7 (Build 20G817)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@boocmp

**Comment by fallaciousreasoning** [comment]
Should the expected text here be `Hide Side Panel icon`? I thought on Mac we generally used Title Case for menu entries?

**Comment by stephendonner** [comment]
cc @aguscruiz

**Comment by fallaciousreasoning** [comment]
(I could be wrong, I don't own a mac)

**Comment by aguscruiz** [comment]
I'm seeing almost every menu entry on my mac with Title Case, yeah.

**Comment by fallaciousreasoning** [comment]
@aguscruiz & @stephendonner what's our conclusion here - what do we think is the best casing?

**Comment by stephendonner** [comment]
> @aguscruiz & @stephendonner what's our conclusion here - what do we think is the best casing?

Sorry, meant to come back to this earlier; I think, given the precedence here and knowing the Apple HIG re: casing, we can close this as `INVALID` and I/we should spin up new bugs to bring the other, incorrectly changed instances inline, on macOS:

`Brave Rewards` | `Brave Wallet`
-----------------|----------------
<img width="323" alt="Screen Shot 2022-10-20 at 6 35 43 PM" src="https://user-images.githubusercontent.com/387249/197090800-625ca2a7-06f3-406d-92e7-1bfa979bc650.png"> | <img width="340" alt="Screen Shot 2022-10-20 at 6 35 54 PM" src="https://user-images.githubusercontent.com/387249/197090803-effc8358-5048-442f-a87a-12d18f5a47e6.png">

**Comment by fallaciousreasoning** [comment]
Cool, that was @sangwoo108's suggestion!

**Comment by fallaciousreasoning** [comment]
Closing as invalid
