### ISSUE TITLE
Videos on site `Soap2Day.to` will NOT play on Brave Browser for Linux Devices

### ISSUE THREAD

**Issue by npn225** [brave/brave-browser#25542]
## Description 

- Videos for the site `soap2day.to` will not play on Brave Browser for Linux devices!  
- Have used both the guest profile and default factory settings for the Brave Browser but even for those, the videos on `soap2day.to` will not play!  
- When the console log is inspected, a bunch of "GET ... 404" Errors and a bunch of "JW Player Warning 324003." Warnings are found to be reported.  
- When the play button is hit, the console presents a new error of "JW Player Error 224003."

## Steps to Reproduce

   1. Get a Linux OS Machine 
   2. Install the Brave Browser on that machine
   3. Enter `soap2day.to` into the URL 
   4. Hit the "Home" button until you have entered the site 
   5. Click on any random video 
   6. Open the console log to see the errors and warnings mentioned above 
   7. Hit the play button on the video and you will see it is not playing 

## Actual result:
Errors & Warnings are retrieved and the video does not play: 

Before hitting the play button: https://postimg.cc/561KXLHz
After hitting the play button: https://postimg.cc/dkVrMQDL

## Expected result:
The video should play without error or trouble after the button is clicked: 

(On Firefox) Before hitting the play button: https://postimg.cc/T5PzWb1f
(On Firefox) After hitting the play button: https://postimg.cc/grfshRns

## Reproduces how often: 
Easily reproduced on a linux machine

## Brave version (brave://version info)
1.43.93 Chromium: 105.0.5195.127 (Official Build) (64-bit)  

## Version/Channel Information:
It is not specific to any one channel and this problem has been occurring for the last couple versions of Brave!

- Can you reproduce this issue with the current release?  - Yes
- Can you reproduce this issue with the beta channel?  - Yes 
- Can you reproduce this issue with the nightly channel?  - Yes 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  - No
- Does the issue resolve itself when disabling Brave Rewards? - No
- Is the issue reproducible on the latest version of Chrome? - Yes 

## Miscellaneous Information:
This may be a Chromium issue rather than a Brave Browser specific one since I was also able to reproduce this issue on the Chromium browser!  

NOTE: This issue does not occur for Chromium based browsers on Windows, just on Linux!  Have not tested for MacOS!

**Comment by ryanbr** [comment]
@npn225 Site seems fine, still an issue? (with the latest ver of Brave)

**Comment by npn225** [comment]
Hey @ryanbr, 

The problem does seem to have resolved itself with that mirror.

But could you check out this one - s2dfree.nl

For that mirror, I still have the same video playing problems on Chromium-based browsers on Linux! 

Just wanted to see if you do as well!

**Comment by ryanbr** [comment]
Seems fine, no difference between the 2 sites. `https://s2dfree.nl/MczozNDoiMTE2NTR8fDEwMi4xMjkuMjUyLjEzOHx8MTY4Mzc4MDA0MCI7.html`  Loaded the the movie. (2-3 second delay). But seems good @npn225

**Comment by npn225** [comment]
Then I guess it might just be me!  
It's weird because even with all my extensions turned off and with Brave Shields down, I still get this problem on s2dfree.nl!

I also get on other Chromium-based browsers as well! 
Here's what the error looks like on Brave: [Link](https://postimg.cc/Snj3yfC4) to Image

Quick question though: What version of Brave are you running?

I'm running version 113.1.51.110!

**Comment by ryanbr** [comment]
```
Hello guys:
We have decided to close soap2day forever.
We are very sorry :)
Bye
```

Closing ticket, site now dead. Pity not probably resolved
