### ISSUE TITLE
Bitcoin lists Ethereum account when opened from Market tab

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#25547]
## Description 

Bitcoin lists Ethereum account when opened from Market tab

## Steps to Reproduce

   1. Install/Upgrade to 1.44.97
   2. Create Wallet and open Market tab
   3. Click on Bitcoin to view Market details of Bitcoin
   4. Accounts lists Ethereum account which is wrong

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/191693268-ec998026-ac97-4ea4-9f01-b722fe9cad0e.png)

## Expected result:
Do not show account info where its not applicable

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.44.97 Chromium: 106.0.5249.55 (Official Build) (64-bit) 
-- | --
Revision | `4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}`
OS | Windows 11 Version 21H2 (Build 22000.978)
## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @muliswilliam @Douglashdaniel

**Comment by Douglashdaniel** [comment]
Accounts are no longer listed for `Market` details. Closing as `Invalid`

![Screenshot 69](https://github.com/brave/brave-browser/assets/40611140/1b1ef5b0-f078-4fc0-9bd2-19351baf9fb3)
