### ISSUE TITLE
[Android] 0.300 BAT appears/persists after resetting Brave Rewards

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#25541]
## Description 

0.300 BAT appears/persists after resetting Brave Rewards

## Steps to Reproduce

1. install `1.44.95`
2. launch Brave
3. tap on the 3-dots menu
4. tap on `Settings`
5. tap on `About Brave`
6. tap 10x on `Application version`
7. tap on `Developer options`
8. tap on `QA Preferences`
9. enter the code
10. tap to set `Use Rewards staging server` to `Enabled`
11. tap `Later`
12. tap to set `Verbose Logs for Ad-Rewards`
13. tap `Relaunch now`
14. tap on the BAT icon
15. tap `Start using Brave Rewards`
16. tap on `Unverified`
17. tap `Continue`
18. tap `Uphold`
19. tap on `Authorize`
20. log in to staging/sandbox
21. tap `Next`
22. wait
23. you'll see `0.300 BAT` added to `Estimated Earnings`
24. tap on the 3-dots menu
25. tap `Settings`
26. tap `Brave Rewards`
27. tap `Reset Brave Rewards`
28. tap `Confirm`
29. tap `Relaunch Now`
30. look at your `brave://rewards` window

## Actual result:

Screencast:

https://user-images.githubusercontent.com/387249/191624932-c3b72467-48cc-4973-bc73-cbc56a922c2c.mp4

Shows `0.300 BAT`

## Expected result:

Shows `0.000 BAT`, as this Rewards profile was just reset?

NOTE: tapping on the `BAT` icon shows the correct `0.000 BAT`

`brave://rewards` page | from `BAT` icon
------------------------|-----------------
![Screenshot_20220922-000650](https://user-images.githubusercontent.com/387249/191624876-d24b1d35-a810-4e03-891b-14426255b265.png) | ![Screenshot_20220921-155727](https://user-images.githubusercontent.com/387249/191624872-6c266440-5b80-4074-af12-bde7d82a2988.png)

## Reproduces how often: 

100%

## Brave version (brave://version info)

`1.44.95, Chromium 106.0.5249.40` on a `Google Pixel XL` running `Android 9`.

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@deeppandya @Miyayes

**Comment by Miyayes** [comment]
>the underlying code works, just need to trigger it to flush state for Expected Earnings on the brave://rewards/ page

**Comment by deeppandya** [comment]
@stephendonner can you verify this issue on nightly version of the application ? it should have been fixed in nightly

**Comment by stephendonner** [comment]
@deeppandya can still easily reproduce using `1.46.7, Chromium 106.0.5249.55`:


https://user-images.githubusercontent.com/387249/192065516-e7f2a56d-60cf-4654-8a27-23577b30640f.mp4

**Comment by stephendonner** [comment]
## Verified `PASSED` using `1.48.134, Chromium 109.0.5414.87` on a `Google Pixel XL` running `Android 9`

Followed the original steps to reproduce from https://github.com/brave/brave-browser/issues/25541#issue-1381611931, with a slightly modified experience (but correct) after resetting Rewards.

#### Confirmed after resetting Rewards all of my BAT and ad-earning data was cleared, and Rewards `Brave Private Ads` was disabled

screencast | end screenshot
------------|----------------
<video src="https://user-images.githubusercontent.com/387249/213821596-489dcce4-7447-40c5-9257-7fa75ffe392a.mp4"> | ![Screenshot_20230120-151614](https://user-images.githubusercontent.com/387249/213821945-992c8dc6-4123-4bdc-a5fc-3cb7a936f6a8.png)
