### ISSUE TITLE
Warn users to enabled Cloudflare DNS to avoid DNS leaks 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#25544]
## Description 

With #25488 being done, Windows doesn't default to using `Use secure DNS * With Cloudflare (1.1.1.1)` which leads to DNS leaks when using Brave VPN. Users should be warned to enable it when connecting to Brave VPN on Windows

## Steps to Reproduce

   1. Clean profile on 1.46.2
   2. Enable VPN on staging
   3. Ensure `Use secure DNS with your current service provider` is set (also default setting)
   4. Visit `https://browserleaks.com/dns`, local ISP DNS is leaked 
   5. Visit `https://ipleak.net`, local ISP DNS is leaked
   6. Enable `Use secure DNS with Cloudflare (1.1.1.1)` 
   7. Visit `https://browserleaks.com/dns`, no local ISP DNS is leaked
   8. Visit `https://ipleak.net`, no local ISP DNS is leaked

## Actual result:

DNS Leak  | No DNS Leak
-- | --
![image](https://user-images.githubusercontent.com/17010094/191669691-b3ab50b9-f0ae-47fb-bd06-1a38471bc978.png) | ![image](https://user-images.githubusercontent.com/17010094/191669721-672e770c-86d9-4a15-86ac-f7ced0aee304.png)

## Expected result:
Warn user to enable DNS over Cloudflare to avoid DNS leaks

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.46.2 Chromium: 106.0.5249.40 (Official Build) nightly (64-bit)
-- | --
Revision | `fab1d91915d2722d6339aaa7f4e9ce44f1e9b103-refs/branch-heads/5249@{#442}`
OS | Windows 11 Version 21H2 (Build 22000.1042)

<br class="Apple-interchange-newline">

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @bsclifton @spylogsster

**Comment by bsclifton** [comment]
Closing for now - will reopen an issue with guidance from security/privacy review (currently open here https://github.com/brave/security/issues/1029)
