### ISSUE TITLE
Update `GetPurchaseToken` method to set proper subscription ID

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#25545]
## Description
When testing the receipt linking, we noticed that we're getting a 400 error from the backend.

Currently, we're sending over `brave-firewall-vpn-premium` as the `subscription_id` but this doesn't match when doing validation.
https://github.com/brave/brave-core/blob/330f5f729ace85a765b6d22d06676ad446b91222/components/brave_vpn/brave_vpn_service.cc#L902-L906

We need to update this to provide the appropriate value here for `subscription_id`:
https://github.com/brave/brave-core/blob/b71f6c656fdf1ed4958ccfc6505dd5d7f20d13e6/android/java/org/chromium/chrome/browser/vpn/utils/InAppPurchaseWrapper.java#L42-L46

**Comment by bsclifton** [comment]
First rev attempt here: https://github.com/brave/brave-core/commit/4d7e7e6eab80a351c55857b8e9daf6600b0733b0

**Comment by kjozwiak** [comment]
The above requires `1.45.87` or higher for `1.45.x` verification 👍
