### ISSUE TITLE
[Android] Alignment issue in Auto-contribute panel for `Sites viewed` and `Sites excluded` screen

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#25556]
## Description 
Alignment issue in Auto-contribute page for `Sites viewed` and `Sites excluded` screen

## Steps to reproduce 

   1. Clean profile 1.44.95
   2. Enable rewrads 
   3. Add few publishers into AC table
   4. Open `Auto-contribute` panel

## Actual result 
Alignment issue in Auto-contribute panel for `Sites viewed` and `Sites excluded` screen
![Screenshot_20220922_200832](https://user-images.githubusercontent.com/38657976/191782445-2dea4dc8-06c1-4e17-8b7b-41893a1d4c5f.jpg)

## Expected result
Should not be any alignment issue

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? not sure
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Vivo x70 pro with android version 12
   - Android version: 12
   
## Brave version

1.44.95
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: https://github.com/orgs/brave/teams/qa-team @Miyayes @deeppandya

**Comment by Miyayes** [comment]
Does this repro in the latest Nightly that contains https://github.com/brave/brave-browser/issues/24570?

**Comment by Miyayes** [comment]
Does this repro in 1.45.x or the latest Nightly that contains https://github.com/brave/brave-browser/issues/24570? @GeetaSarvadnya

**Comment by GeetaSarvadnya** [comment]
The issue is fixed and working fine on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.52.x`

![Screenshot_20230513_222822](https://github.com/brave/brave-browser/assets/38657976/84b95c44-d2dd-42d9-a64d-e5146ea13487)
