### ISSUE TITLE
[Desktop] Private wallet data preferences should be encrypted 

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#2555]
## Description
Carried over from https://github.com/brave/browser-laptop/issues/10705

> The wallet private key and passphrase are as sensitive as most passwords, so we should use the Brave password manager encryption key to encrypt them before saving to disk.

**Comment by bridiver** [comment]
I think the best way to handle this is to add something like LedgerClient::LoadSecure/LedgerClient::SaveSecure which internally uses os_crypt

**Comment by diracdeltas** [comment]
what does os_crypt use to store the encryption key if a keychain-like mechanism isn't available?

**Comment by bridiver** [comment]
@diracdeltas os_crypt just encrypts the data using the OS encryption key and then we would just store the output in a file

**Comment by diracdeltas** [comment]
@bridiver i think we're on the same page here; in the original issue i mean store the encryption key in keyring (or whatever is available on the OS*), not store the private key itself in the keyring. the encrypted output can be stored in regular storage.

* appears this would be keyring on macos / Gnome Keyring or KDE Wallet Manager on linux

**Comment by bridiver** [comment]
the only concern I have here is that 3rd-party clients may not properly encrypt the data and could make bat-native-ledger/ads look insecure through a poor implementation of the encrypt/decrypt methods. The alternative would be to embed os_crypt into the lib which should be ok because it has code for all platforms including IOS

**Comment by diracdeltas** [comment]
Does this not encrypt on windows due to lack of an underlying OS keychain-like mechanism?

**Comment by diracdeltas** [comment]
we should also encrypt the Authorization token (stored in the Preferences file)

**Comment by mrose17** [comment]
@mrose17 - tracking

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.16.50 Chromium: 86.0.4240.55 (Official Build) dev (x86_64)
Revision	a6d625ef6f7fe8ea0675f1cf759155a05ee1be40-refs/branch-heads/4240@{#953}
OS	macOS Version 10.14.6 (Build 18G3020)
```

Verified plan 1 from https://github.com/brave/brave-core/pull/6213. Confirmed able to connect to Uphold on clean profile and view balance. Confirmed able to 1 time tip. Confirmed able to perform AC and recurring tip.

Verified plan 2 from https://github.com/brave/brave-core/pull/6213. Confirmed brave://rewards was displayed correctly after upgrade from 1.15.x to 1.16.x and Uphold wallet was still connected as expected. After upgrade, confirmed able to 1 time tip. Confirmed able to perform AC and recurring tip.

---------

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T with Android 10 running 1.16.62 x64 build
- Verified scenario 1 from https://github.com/brave/brave-core/pull/6213
- Verified able to connect to uphold on a clean profile and able to perform tips/recurring tips/ac
- Verified scenario 2 from https://github.com/brave/brave-core/pull/6213
- Verified able balance shows as expected after upgrading from 1.15.66
- Verified able to still send one-time tip/recurring tip/ac after upgrading
-------------
Verification passed on Samsung Tab A with Android 10 running 1.16.62 x64 build
- Verified scenario 1 from https://github.com/brave/brave-core/pull/6213
- Verified able to connect to uphold on a clean profile and able to perform tips/recurring tips/ac
- Verified scenario 2 from https://github.com/brave/brave-core/pull/6213
- Verified able balance shows as expected after upgrading from 1.15.66
- Verified able to still send one-time tip/recurring tip/ac after upgrading
