### ISSUE TITLE
Add ability to hide balances with $0 value

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#25552]
## Description 

https://community.brave.com/t/add-possibility-to-hide-token-with-0-value/433323

brought up on ticket here and in other design mockups. 

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by bbondy** [comment]
Duping to https://github.com/brave/brave-browser/issues/19758
