### ISSUE TITLE
`Send a tip` hover text is far away from the tip button in few GH pages

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#25557]
## Description 

`Send a tip` hover text is far away from the tip button in few GH pages

## Steps to Reproduce

 Open GH pages below
https://gist.github.com/darkdh/85fed2542190510aaee0f3ad91091818
https://github.com/brave/brave-browser/commits/master?after=05749476419ca759df8d5f7873bec79f58d2f624+69&branch=master&qualified_name=refs%2Fheads%2Fmaster 

## Actual result:

`Send a tip` hover text is far away from the tip button in few GH pages
![image (1)](https://user-images.githubusercontent.com/38657976/191786069-6ac4258b-e4f6-457d-aba4-5d4ad762a2fb.png)

## Expected result:
`Send a tip` hover text should not be too far away from the tip button in few GH pages

![image](https://user-images.githubusercontent.com/38657976/191785474-38fa0119-f924-4843-814e-15b398526ae9.png)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.44.95 Chromium: 106.0.5249.40 (Official Build) (64-bit)
-- | --
Revision | fab1d91915d2722d6339aaa7f4e9ce44f1e9b103-refs/branch-heads/5249@{#442}
OS | Windows 10 Version 21H2 (Build 19044.2006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @Miyayes

**Comment by emerick** [comment]
@GeetaSarvadnya Could I ask you to retry this one with nightly? I can no longer repro. We made some Github-related fixes to Greaselion recently and I suspect those may have addressed this. Thank you!

**Comment by Miyayes** [comment]
We should just remove all these tooltips.

**Comment by emerick** [comment]
No longer relevant in light of https://github.com/brave/brave-browser/issues/28699.
