### ISSUE TITLE
Save custom background image in a directory

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#25553]
subtask for https://github.com/brave/brave-browser/issues/15252

---

In order to allow users to upload multiple images, we should save images into a directory.
Currently, we overwrite the image. (delete and save it with same name)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (64-bit)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | Windows 11 Version 21H2 (Build 22000.1098)
```

Before Upgrade
------------------
1. Install 1.45.113
2. launch Brave
3. open NTP
4. click `Customize`
5. click `Upload from device 
6. upload a custom image 
7. uploaded image is displayed as the background image
8. close the browser

step 5|step 6|step 7a|step 7b
------|----|-----|------
<img width="464" alt="image" src="https://user-images.githubusercontent.com/98358127/198413434-4f09fb25-a54b-4c7a-b3be-d1215eceaf4a.png">|<img width="484" alt="image" src="https://user-images.githubusercontent.com/98358127/198413523-048328f5-2b92-4f2c-a970-19c5cdf6ba99.png">|<img width="464" alt="image" src="https://user-images.githubusercontent.com/98358127/198413550-2a17fbaf-7987-45e3-a034-7bccc807f63b.png">|<img width="466" alt="image" src="https://user-images.githubusercontent.com/98358127/198413578-6803edbb-fb17-4c8e-be65-5fe4b167d28d.png">

After Upgrade
------------------
9. rename the profile 
10. Install 1.46.81
11. launch brave profile 
12. confirmed image is retained from previous version
13. click `Customize`
14. click `Upload from device` and image is displayed as the thumbnail
15. click `Upload from device` to upload couple of more images

#### Confirmed image is retained from previous version and able to upload multiple custom images

step 12|step 14|Ex1|Ex2|Ex3
----|----|-----|-----|-----
<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/198414162-257e65f2-0b02-4a5a-8fac-5bb9f9de7163.png">|<img width="464" alt="image" src="https://user-images.githubusercontent.com/98358127/198414665-19fcba56-7775-4914-ae5c-de4775f7c276.png">|<img width="487" alt="image" src="https://user-images.githubusercontent.com/98358127/198414824-caf72f60-ab52-48ec-a9f4-b70a3675441a.png">|<img width="465" alt="image" src="https://user-images.githubusercontent.com/98358127/198414875-856f427a-d563-45ed-bccc-87b05981b8ec.png">|<img width="465" alt="image" src="https://user-images.githubusercontent.com/98358127/198414891-dd7bf15f-9266-4fec-8060-45ea86e74dd0.png">

**Comment by stephendonner** [comment]
## Verified `PASSED` using 


### Before upgrade


1. installed `1.45.113`
2. launched Brave
3. opened NTP
4. clicked `Customize`
5. clicked `Upload from device
6. uploaded a custom image
7. uploaded image is displayed as the background image
8. closed the browser

<img width="1312" alt="Screen Shot 2022-10-27 at 4 48 37 PM" src="https://user-images.githubusercontent.com/387249/198418730-aac2d791-08b2-4932-8b90-70f4c9988986.png">


### After upgrade

9. renamed the profile from `Brave Browser` -> `Brave Browser Beta`
10. installed `1.46.81`
11. launched brave profile
12. confirmed image is retained from previous version
13. clicked `Customize`
14. clicked `Upload from device` and image is displayed as the thumbnail
15. clicked `Upload from device` to upload a couple more images

#### Confirmed the original image upload was retained, as well as subsequent image uploads

example | example | example | example
---------|----------|---------|---------
<img width="1312" alt="Screen Shot 2022-10-27 at 4 49 57 PM" src="https://user-images.githubusercontent.com/387249/198418817-6c23fe01-e3c6-4301-b73a-e8a882aaa9d7.png"> | <img width="1312" alt="Screen Shot 2022-10-27 at 4 50 26 PM" src="https://user-images.githubusercontent.com/387249/198418818-3437affe-f837-4cde-b682-d4ad6df3fcbf.png"> | <img width="1312" alt="Screen Shot 2022-10-27 at 4 50 40 PM" src="https://user-images.githubusercontent.com/387249/198418822-c1f7b4e0-34a0-457a-a225-938ed2c75bf0.png"> | <img width="1312" alt="Screen Shot 2022-10-27 at 4 50 55 PM" src="https://user-images.githubusercontent.com/387249/198418823-740abc8b-e532-4103-a417-8a2982b629ca.png">
