### ISSUE TITLE
[Android] Rewards logged out state is not shown for some custodians

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#25561]
## Description 
The disconnected but verified state is not reflected in the UI or in the brave-internals pages for `bitFlyer` accounts. `Logged out` should be displayed in brave://rewards and BR panel for the account. This is currently working as expected for Uphold and Gemini.

## Steps to reproduce 

Preconditions: Clean install. Also, for bitFlyer, Japan region and language must be selected before app first launch. 

1. Enable staging on rewards
2. Enable rewards
3. Login in KYC'd custodial account
4. Check brave://rewards and BR panel for verified state
5. Check brave://rewards-internals to confirm verified state is displayed in the general tab
6. Get account into logged-out state by ending the session (Different STR depending on custodian)
7. Confirm logged out is displayed in brave://rewards and the rewards panel
8. Check the connection status in rewards-internals

## Actual result 

`Verified` state is displayed instead of `Logged out` in rewards page and panel
Disconnected status missing/not reflected in brave://rewards-internals pages

bF Example | bF Example | bF Example
-|-|-
![screenshot-1663862047981](https://user-images.githubusercontent.com/17885425/191801426-358fa524-183e-4a3e-98f7-00c2e5f03844.png) | ![screenshot-1663862547207](https://user-images.githubusercontent.com/17885425/191801438-952d64c0-1f40-4c16-988c-a86da185ccc3.png) | ![screenshot-1663862575630](https://user-images.githubusercontent.com/17885425/191801440-cd64f5ee-5b84-48f3-bb84-973e37836a2d.png)

## Expected result
1. `Logged out` state is displayed in both brave://rewards and rewards panel
2. `Disconnected(verified)` is displayed for the account status under general section in `brave://rewards-internals`
3. `Disconnected_Verified => Pending` or similar log should be reflected for logged out state under `Event Logs` in `brave://rewards-internals`

## Issue reproduces how often 
Always

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung Galaxy S21, Galaxy Tablet
   - Android version: 12
   
## Brave version
`1.44.97 Chromium 106.0.5249.55`

**Comment by LaurenWags** [comment]
cc @Miyayes
