### ISSUE TITLE
Useless IPFS notifications on resume from sleep

### ISSUE THREAD

**Issue by MikeBishop** [brave/brave-browser#25566]
## Description 
After enabling IPFS to run a local node, Brave sends desktop notifications that the node is down when the system resumes from sleep, followed a few seconds later by a notification that the IPFS node is back up.  These notifications are useless in the course of normal sleep/resume; unless there's an IPFS navigation happening at that moment, the user likely doesn't care.  The user _might_ care if the node stays down for an extended period of time.

## Steps to Reproduce

   1. Enable local IPFS node in Brave
   2. Put PC to sleep
   3. Resume PC from sleep 

## Actual result:

![image](https://user-images.githubusercontent.com/4273797/191843557-1de39288-63c1-4223-b6d8-885cc115aadc.png)

## Expected result:
Just be quiet.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

1.43.93 Chromium: 105.0.5195.127 (Official Build) (64-bit) 

## Version/Channel Information:

Only tried current.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by rebron** [comment]
cc: @spylogsster

**Comment by spylogsster** [comment]
cc @cypt4

**Comment by vadimstruts** [comment]
The IPFS local node and scheme has been [deprecated](https://github.com/brave/brave-browser/issues/37735)
