### ISSUE TITLE
Support fetching the selected token's address from Unstoppable Domains

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#25562]
Currently we always get ETH address for whichever token user selected in the send UI, we should revise to get the selected token's address too (using symbol as the key) and use it if exists, otherwise fallback to ETH address.
For testing, jim-unstoppable.crypto should resolve to different addresses depending on the token selected.
And we would like to revise the API to take in coin type as well, and query SOL or FIL address based on it.

**Comment by yrliou** [comment]
cc @supermassive

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (64-bit) 
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | Linux

- Verified steps from [brave/brave-core#15388](https://github.com/brave/brave-core/pull/15388)
- Verified UD address updates based on tokens 
- Encountered [#26411](https://github.com/brave/brave-browser/issues/26411)

https://user-images.githubusercontent.com/17010094/199189096-0515e5d4-1bc7-4064-9dc3-37b2590e42b6.mp4

------------------------
Verification passed on

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (64-bit) 
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | Windows 11 Version 22H2 (Build 22621.674)

- Verified steps from [brave/brave-core#15388](https://github.com/brave/brave-core/pull/15388)
- Verified UD address updates based on tokens 
- Encountered [#26411](https://github.com/brave/brave-browser/issues/26411)

https://user-images.githubusercontent.com/17010094/199189472-d1ce4c4d-680d-4b38-b3b2-e1de69055791.mp4

------------------------
Verification passed on

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (arm64)
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#15388](https://github.com/brave/brave-core/pull/15388)
- Verified UD address updates based on tokens 
- Encountered [#26411](https://github.com/brave/brave-browser/issues/26411)

https://user-images.githubusercontent.com/17010094/199186263-6769204d-12db-4201-ac64-0f0fae083900.mov
