### ISSUE TITLE
[Android] Failed Auto-Contribute toast notification appearance needs updated design

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#25573]
## Description

See (similar to this issue for Monthly Tips): https://github.com/brave/brave-browser/issues/22374#issuecomment-1255791025

## Actual result 

Not correct:
<img src="https://user-images.githubusercontent.com/11497541/191908660-34d5235b-a032-4b16-a4f4-4e4b64971a7b.png" width=300px>

## Solution

Fix toast notification appearance.

cc: @GeetaSarvadnya

**Comment by Miyayes** [comment]
@deeppandya 

But you can make the text: Auto-Contribute failed
![image](https://user-images.githubusercontent.com/11497541/202813461-b054f2b2-eb0b-4fef-b420-eaeea28f8d97.png)

**Comment by stephendonner** [comment]
## Verified `PASSED` using `Brave` `1.48.152`, `Chromium` `109.0.5414.119` on a `Google Pixel XL` running `Android 9`

### Steps:
1. on desktop, transferred all but `0.15` `BAT` from the `Brave Browser` card in `Uphold` to a temp one
2. installed `1.48.152`
3. launched Brave
4. set Rewards environment to staging via `QA Preferences`
5. tapped on the `BAT` icon
6. tapped on `Start using Brave Rewards`
7. tapped `Connect`
8. tapped `Uphold`
9. logged in to `Uphold`
10. confirmed my balance is `0.15`
11. loaded `laurenwags.github.io`
12. waited for auto-complete
13. tapped on the notification icon in the URL bar/on the `BAT` icon

#### Confirmed I got `Monthly tip failed.  There was a problem processing your contribution`

NOTE: https://github.com/brave/brave-browser/issues/28116 covers both the missing and incorrect button-acknowledgement texts

`0.15 BAT` | `Light` | `Dark`
-----------|---------|------
![Screenshot_20230307-133800](https://user-images.githubusercontent.com/387249/216173302-174f9d93-af6c-463f-ad4c-82bea26b5a05.png) | ![Screenshot_20230407-134304](https://user-images.githubusercontent.com/387249/216173457-e0ffb2ef-9229-4625-8271-d0683f680ae3.png) | ![Screenshot_20230407-134331](https://user-images.githubusercontent.com/387249/216173460-11f9bf59-76c8-473a-948d-5dd72cd704a1.png)
