### ISSUE TITLE
Inkdrop and border radius don't match on avatar button.

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#25579]
<img width="79" alt="image" src="https://user-images.githubusercontent.com/15734630/191956986-7fdebe90-ec1c-43bb-95cd-3bc4a16960d2.png">

### Steps to reproduce
* Create a new profile from app menu
* When a new window opens, wait for the avatar button to exapnd so that we can see the user name.
* When promo bubble closes, try moving mouse over to the button.
* The fill effect should fill the entire area of the button.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.49.92 Chromium: 110.0.5481.77 (Official Build) beta (x86_64)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | macOS Version 12.6.3 (Build 21G419)
```
