### ISSUE TITLE
BSC network name overflows beyond the dropdown 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#25572]
## Description 

BSC network name overflows beyond the dropdown 

## Steps to Reproduce

   1. Upgrade to 1.46.4
   2. Open Wallet and click Network dropdown in portfolio, BSC name is outside the dropdown
   3. Check the network dropdown in NFT tab, same issue

## Actual result:

Light | Dark
-- | --
<img width="283" alt="image" src="https://user-images.githubusercontent.com/17010094/191905169-2f3a9f41-1de5-4d0c-8fb0-474f257afdb7.png">| <img width="288" alt="image" src="https://user-images.githubusercontent.com/17010094/191905262-fdaf4012-7b59-45b9-914f-9d1af9e20796.png">

## Expected result:
<img width="267" alt="image" src="https://user-images.githubusercontent.com/17010094/191905685-5b47e30a-0e53-4e8c-8f91-2a5d08267f6a.png">

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.46.4 Chromium: 106.0.5249.55 (Official Build) nightly (arm64)
-- | --
Revision | `4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel @josheleonard @muliswilliam

**Comment by kjozwiak** [comment]
The above requires `1.45.78` or higher for `1.45.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.45.85 Chromium: 106.0.5249.91 (Official Build) beta (64-bit) 
-- | --
Revision | `fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}`
OS | Linux

- Verified steps from issue description
- Verified BSC network name doesn't overflow beyond the dropdown 
![image](https://user-images.githubusercontent.com/17010094/194111227-1e821b19-9b4d-4586-9792-dc4db74b9724.png)

------------------------
Verification passed on

Brave | 1.45.85 Chromium: 106.0.5249.91 (Official Build) beta (64-bit) 
-- | --
Revision | `fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}`
OS | Windows 11 Version 21H2 (Build 22000.978)

- Verified steps from issue description
- Verified BSC network name doesn't overflow beyond the dropdown 
![image](https://user-images.githubusercontent.com/17010094/194111744-5e04dfdc-1b9f-4ea8-adac-9a7be005f276.png)


------------------------
Verification passed on

Brave | 1.45.85 Chromium: 106.0.5249.91 (Official Build) beta (arm64)
-- | --
Revision | `fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from issue description
- Verified BSC network name doesn't overflow beyond the dropdown 
![image](https://user-images.githubusercontent.com/17010094/194111966-74d1efdc-85bf-4dc0-a5f2-05ed94b58072.png)
