### ISSUE TITLE
Add a proper message when there is no associated wallet address & delay showing invalid eth address

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#25574]
## Description 

Add a proper message when there is no associated wallet address & delay showing invalid eth address

## Steps to Reproduce

   1. Start typing a domain name in Send tab
   2. Starts to show invalid eth address
   3. Enter `haimoura.eth`, shows `Domain haimoura.eth is not registered` when it is a registered domain but doesn't have a valid wallet address linked to it

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/191910489-ada7d37e-b0c3-4d9b-8663-6d85f9761af4.png) | ![image](https://user-images.githubusercontent.com/17010094/191911026-790a0199-7461-4f75-b2a9-35e37b497ecc.png)
-- | --

## Expected result:
Better wording on the error message

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.46.4 Chromium: 106.0.5249.55 (Official Build) nightly (64-bit)
-- | --
Revision |` 4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @supermassive @rmcfadden3 @jamesmudgett

**Comment by rmcfadden3** [comment]
@srirambv — what would your expected text here be? Would it be something like:

"The domain [domain_name] doesn't have a valid wallet address."

If yes, would there be any additional action the user could take? Could they then register it with a valid address? What's their recourse?

**Comment by srirambv** [comment]
> "The domain [domain_name] doesn't have a valid wallet address."

probably could be simplified to 
> "The domain [domain_name] doesn't have an associated ETH address."

I don't think there is any action item there if there isn't an associated ETH address. Its just to warn user that what is entered is invalid. Maybe @supermassive can elaborate more on it

cc: @yrliou

**Comment by Douglashdaniel** [comment]
Is an old issue from `V1` designs, has since been address. Closing as `Invalid`

![Screenshot 68](https://github.com/brave/brave-browser/assets/40611140/f4f40f51-9c2b-459e-b8ff-86245e430f1a)
