### ISSUE TITLE
Install Brave Browser For All Windows Users (Ansible + Chocolatey)

### ISSUE THREAD

**Issue by Techy444** [brave/brave-browser#25571]
## Description 
**I am using Ansible + Chocolatey to deploy Brave browser to Windows 10 domain joined computers.**

**I am using the credentials of a Windows domain admin to deploy the software to computers but instead of installing the software on ALL users on the computer, it only installs Brave browser on the domain admin's account. Normal users do not have install privileges.**

## Steps to Reproduce

   **1. Deploy Brave browser to domain joined windows 10 computer using Ansible + Chocolatey**
   **2. Use Windows domain admin credentials to deploy the software in Ansible setting**
   3. 

## Actual result:
**Only installs Brave browser on the domain admin account you used to deploy the software on Ansible**

## Expected result:
**Installs Brave browser on all users of the windows domain joined computer**

## Reproduces how often: 
**Every time**

## Brave version (brave://version info)
**Brave | 1.43.93 Chromium: 105.0.5195.127 (Official Build) (64-bit)**
**Revision | 912488396852bf658ab32465980c0b93a3c27a83-refs/branch-heads/5195@{#1109}**
**OS | Windows 10 Version 21H2 (Build 19044.2006)**

## Other Additional Information:

**- Does the issue resolve itself when disabling Brave Shields?  No**
**- Does the issue resolve itself when disabling Brave Rewards?  No**
**- Is the issue reproducible on the latest version of Chrome? No**

**Comment by mherrmann** [comment]
Hi @Techy444, the Chocolatey package is not maintained by Brave. So the first point of contact should be whoever maintains the Brave Chocolatey package.

But having said that, I believe the reason why the Chocolatey package doesn't work in the way you expect actually is an issue in Brave: #18711. This says that Brave's silent standalone installer (which I strongly suspect is what Chocolatey uses) fails to perform system-wide installations even when run as admin.

I'll see whether we can do something about it. Because this issue is about Chocolatey, which is not maintained by Brave, I'll close it. But we can continue the discussion in #18711.

**Comment by Techy444** [comment]
> Hi @Techy444, the Chocolatey package is not maintained by Brave. So the first point of contact should be whoever maintains the Brave Chocolatey package.
> 
> But having said that, I believe the reason why the Chocolatey package doesn't work in the way you expect actually is an issue in Brave: #18711. This says that Brave's silent standalone installer (which I strongly suspect is what Chocolatey uses) fails to perform system-wide installations even when run as admin.
> 
> I'll see whether we can do something about it. Because this issue is about Chocolatey, which is not maintained by Brave, I'll close it. But we can continue the discussion in #18711.

Thank you for taking the time to explain! And thank you for also continuing to look into it. I will also try to contact chocolatey package maintainers

**Comment by Neustradamus** [comment]
There is a problem with user profile which is not in the good folder!

Linked to:
- https://github.com/brave/brave-browser/issues/1473
- https://github.com/brave/brave-browser/issues/4609
