### ISSUE TITLE
Multiple transactions in Jupiter swaps results in stuck funds

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#25570]
Jupiter quotes may have 1 to 3 separate transactions for performing a swap. These transactions must be settled sequentially, and in the event of an error in one of the transactions, the funds may be stuck.

For simpler UX, we want to avoid having multiple transactions. The current tradeoff we'll make is by choosing direct routes only.

**Current behaviour:** Solana swaps have multiple transactions, all of which must be successful in sequence, for the swap to complete.
**Expected behaviour:** Solana swaps can be done with only one transaction.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.44.99 Chromium: 106.0.5249.55 (Official Build) (64-bit) 
-- | --
Revision | `4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}`
OS | Windows 11 Version 21H2 (Build 22000.978)

- Verified steps from issue description & [brave/brave-core#15189](https://github.com/brave/brave-core/pull/15189)
- Verified there is only a single step in submitting a Swap transaction
- Verified there is no UI hang when submitting the Swap transaction on Solana

https://user-images.githubusercontent.com/17010094/192275574-6fb73c0a-a16a-4380-b1df-7af0c0d1a08a.mp4
