### ISSUE TITLE
Adding an NFT doesn't show it in the portfolio until refresh

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#25578]
## Description 

Adding an NFT doesn't show it in the portfolio until refresh

## Steps to Reproduce

   1. Add an NFT via `Add custom asset` under `Visible assets`
   2. Doesn't list the NFT under portfolio
   3. Reload the page, NFT gets listed 

## Actual result:

https://user-images.githubusercontent.com/17010094/191956442-32c6c00f-428b-4daf-a9ec-36f7db8a894a.mp4

## Expected result:
Should get listed automatically without having to refresh the portfolio page

## Reproduces how often: 

Easy

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Not checked
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @muliswilliam @nvonpentz

**Comment by kjozwiak** [comment]
The above requires `1.45.105` or higher for `1.45.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.45.106 Chromium: 107.0.5304.36 (Official Build) (64-bit) 
-- | --
Revision | `2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}`
OS | Linux

- Verified steps from issue description and [brave/brave-core#15241](https://github.com/brave/brave-core/pull/15241)
- Verified added NFT is shown automatically under portfolio without having to refresh the portfolio page
- Verified adding NFT successfully closes the add token details form

https://user-images.githubusercontent.com/17010094/196864500-f3009195-b740-4ff5-b9de-96ac4e5ae6f1.mp4


------------------------
Verification passed on

Brave | 1.45.106 Chromium: 107.0.5304.36 (Official Build) (64-bit) 
-- | --
Revision | `2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}`
OS | Windows 11 Version 22H2 (Build 22621.674)

- Verified steps from issue description and [brave/brave-core#15241](https://github.com/brave/brave-core/pull/15241)
- Verified added NFT is shown automatically under portfolio without having to refresh the portfolio page
- Verified adding NFT successfully closes the add token details form

https://user-images.githubusercontent.com/17010094/196862924-c8a26b22-18d7-4209-89d1-fb3e9520f9eb.mp4

------------------------
Verification passed on

Brave | 1.45.106 Chromium: 107.0.5304.36 (Official Build) (arm64)
-- | --
Revision | `2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from issue description and [brave/brave-core#15241](https://github.com/brave/brave-core/pull/15241)
- Verified added NFT is shown automatically under portfolio without having to refresh the portfolio page
- Verified adding NFT successfully closes the add token details form

https://user-images.githubusercontent.com/17010094/196862316-da753018-5ff2-4c69-a01e-dabc27991e57.mov
