### ISSUE TITLE
[Android] `You've earned an Ads Rewards!` toast notification doesn't look like Desktop notification

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#25582]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/24294

`You've earned an Ads Rewards!` toast notification doesn't look like Desktop notification

## Steps to reproduce 

   1. Clean profile 1.44.95 staging env
   2. Enable rewards
   3. Send ad grants to the profile (ask me or @LaurenWags or @Miyayes )
   4. Cliam ad grants via brave://rewards settings page
   5. `You've earned an Ads Rewards!` toast notification doesn't look like Desktop notification
   
   
## Actual result 
![Screenshot_20220923_184600](https://user-images.githubusercontent.com/38657976/191970656-f0de063d-a2ce-4256-ace1-969e7910f172.jpg)

## Expected result
notification should look more like desktop
![image](https://user-images.githubusercontent.com/38657976/191970925-8b96983c-1048-4720-9575-20971ce9d510.png)

## Issue reproduces how often 

Easy
## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86): ARM 
   - Device type (Phone, Tablet, Phablet): Vivo x70 pro with android version 12
   - Android version: 12
   
## Brave version
1.44.95

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

CC: @brave/qa-team @Miyayes @deeppandya

**Comment by stephendonner** [comment]
## Verified `PASSED` using `Brave` `1.48.148`, `Chromium` `109.0.5414.119` on a `Google Pixel XL` (`arm64`) running `Android 9`

### Steps:
1. installed `1.48.148`
2. launched Brave
3. opened `QA Preferences` menu and set rewards to staging
4. relaunched
5. asked Chris for an ad grant on staging
6. tapped the `BAT` icon
7. tapped `Start using Brave Rewards`
8. connected to `Uphold` on staging
9. tapped on the notification

#### `brave://rewards`

example | example | example
---------|----------|---------
![Screenshot_20230131-092235](https://user-images.githubusercontent.com/387249/215632009-2d95e57e-1a87-4fc3-9c05-8c2918fda366.png) | ![Screenshot_20230131-092245 (1)](https://user-images.githubusercontent.com/387249/215632014-732f73df-7522-475e-bf91-9f3d39463d85.png) | ![Screenshot_20230131-092332 (1)](https://user-images.githubusercontent.com/387249/215632016-ebdc1326-3c6f-4d57-b500-7a360eeeca9b.png)


#### panel

example | example | example | example | example
---------|----------|---------|----------|---------
![Screenshot_20230131-092332](https://user-images.githubusercontent.com/387249/215631944-917996ff-cba6-4792-b232-d9a82f644e52.png) | ![Screenshot_20230131-094517](https://user-images.githubusercontent.com/387249/215631945-d1b38869-439f-4d94-907c-73ddda81c013.png) | ![Screenshot_20230131-094527](https://user-images.githubusercontent.com/387249/215631947-1ce8e67a-1692-41a3-8bfe-19ce676429bf.png) | ![Screenshot_20230131-094533](https://user-images.githubusercontent.com/387249/215631949-0db2fc60-91eb-43fd-8337-4b6cd48a8083.png) | ![Screenshot_20230131-094640](https://user-images.githubusercontent.com/387249/215631950-f0365643-48c3-4601-b6c1-78b2be99425b.png)
