### ISSUE TITLE
Cannot recover from corrupted wallet

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#2558]
Follow up from https://github.com/brave/brave-browser/issues/2183

## Steps to Reproduce

   1. enable rewards
   2. close browser
   3. modify `ledger_state` by deleting `walletInfo` content
`"walletInfo":{}`
   4. Restart

## Actual result:

- The expected UI error message is not shown. 
- The wallet remains in corrupted state. 
- Cannot claim grant.

## Expected result:
-show error message
<img width="383" alt="screen shot 2018-11-19 at 11 12 11 am" src="https://user-images.githubusercontent.com/25326067/48719655-072d0400-ebec-11e8-9361-c0582bbd0b60.png">
-able recover the wallet
-able to claim grant

## Reproduces how often: 

always

## Brave version (brave://version info)

Brave | 0.58.12 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Windows 7

cc @NejcZdovc @brave/legacy_qa

**Comment by LaurenWags** [comment]
Reproduces on macOS

Brave | 0.58.12 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

**Comment by NejcZdovc** [comment]
not sure why but it should be like this

![image](https://user-images.githubusercontent.com/9574457/48720872-fc409680-ec20-11e8-88d8-39894ac33cbd.png)

**Comment by NejcZdovc** [comment]
this will be fixed with https://github.com/brave/brave-core/pull/1086. So the next 0.58 build should fix it

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.58.14 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Windows 7

Used STR from OP.
