### ISSUE TITLE
[Android] After claiming ad grants not getting `You've earned an Ads Rewards!` toast notification on Android

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#25581]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/24294
After claiming ad grants not getting `You've earned an Ads Rewards!` toast notification on Android

## Steps to reproduce 

   1. Clean profile 1.44.95 staging env
   2. Enable rewards
   3. Send ad grants to the profile (ask me or @LaurenWags or @Miyayes )
   4. Cliam ad grants via BR panel
   5. After claiming ad grants not getting `You've earned an Ads Rewards!` toast notification on Android
 

## Actual result 
After claiming ad grants not getting `You've earned an Ads Rewards!` toast notification on Android

## Expected result

![image](https://user-images.githubusercontent.com/38657976/191965534-ec8deae7-2132-45cc-b254-c0d853516462.png)

## Issue reproduces how often 

Easy
## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Vivo x70 pro with android version 12
   - Android version: 12
   
## Brave version
Bravemonoarmx64.apk_1.44.95

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

CC: @brave/qa-team @Miyayes @deeppandya

**Comment by stephendonner** [comment]
Note: still reproduces, re-filed as https://github.com/brave/brave-browser/issues/28189.

Setting to `QA/No` as we'll QA the above, once ready.
