### ISSUE TITLE
Adding NFT doesn't work the first time

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#25588]
## Description 

Adding NFT doesn't work the first time

## Steps to Reproduce

   1. Try adding a NFT 
   2. Sometimes doesn't work the first time
   

## Actual result:

Adding NFT doesn't work the first time. Couple of retry or giving it a few mins and trying again works 

## Expected result:
Should be able to add NFT's instantly  (whether you own it or not)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.44.97 Chromium: 106.0.5249.55 (Official Build) (64-bit)
-- | --
Revision | `4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @muliswilliam @nvonpentz

**Comment by muliswilliam** [comment]
@srirambv I separated the NFT form from the general add custom asset form. I have tested the new implementation in latest master and it is okay.
