### ISSUE TITLE
Allow users to load custom adblock scriptlets

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#25586]
Sometimes, websites have features that cannot be blocked by network request blocking or through CSS. Some of these are dealt with by using scriptlets. We currently use uBlock Origin's resource library for scriptlets, as well as a few custom ones in the https://github.com/brave/adblock-resources repository.

One of Brave's core principles is to put the user back in control of their browsing experience, so we should also allow users to upload their own custom scriptlets, probably from brave://settings/shields/filters. It would be a feature specifically for advanced users, so it's ok to have it hidden at first. The UI would allow users to view a list of scriptlets they've added, to edit or remove entries, and to add a new one. A scriptlet consists of arbitrary JavaScript code and can be given a name for reference in custom filter rules, e.g. `brave-fix`.

Note that this is a security sensitive feature. If users paste untrusted code into a scriptlet, attackers may be able to inject arbitrary code on certain websites that they browse, leading to significant privacy/security risks - UI should be adjusted accordingly.

**Comment by TEMP-ACCOUNT-m4C5gRm32s3Z** [comment]
This is really needed. 
For example, Brave depending on a 3p for the scriptlets is just not good, because if uBlock doesn't want to add a scriptlet they don't find 'user cases to implement it', that means, we as Brave users are just restricted to what uBlock wants to do or not, we depend on them, and there is nothing we can do to make Brave browser better. 
Since uBlock doesn't want to support trusted-set-attr, that means, we Brave users can't have it, it is so easy to implement, just remove the restricted values and done, but since we can't load them on our own, that means we only depend on uBlock, especially on mobile where there is no extensions support.
If tomorrow uBlock decided to remove their remove attribute, remove class scriptlets because they are already marked as _Deprecated by_ the action operators :remove-attr() and :remove-class() then Brave will be at loss.

Also, we have examples of TwitchAdSolutions scriptlets being a great example for this, [video-swap-new](https://github.com/pixeltris/TwitchAdSolutions/raw/master/video-swap-new/video-swap-new-ublock-origin.js) and [vaft](https://github.com/pixeltris/TwitchAdSolutions/raw/master/vaft/vaft-ublock-origin.js) exist, and can reduce quality of a Twitch stream while an ad is playing to avoid it, but we can't use them in Brave, because they are hit and miss, they might work one day and not the next, but at least testing and loading them on our own, would truly extend the capabilities of Brave as a whole.
Or something like a Twitter/X to Nitter redirector can be achieved easily through JS without the use of extensions, or anything else.

Brave needs to invest and work more in the Adblocker, put more money to it, Brave already chose the path to follow uBlock development and their features and even use their lists, and these are the consequences of that, they add the alias "from" and then they make those rules incompatible with Brave, they created the `include` in lists, and `if`s and all that in their lists, and a lot of stuff gets messy for Brave users.
At least Brave can break some dependency by allowing the users to use our own scriptlets, and then being able to feel a little more free, because right now we can't even turn Default lists off, even if they break X or Y.

**Comment by ShivanKaul** [comment]
We should have this under a feature flag, default disabled.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.75.121 Chromium: 132.0.6834.57 (Official Build) nightly (64-bit)
-- | --
Revision | 8d18f88a9b413c52f5168def57222545785b76c8
OS | Windows 11 Version 24H2 (Build 26100.2314)
```

<details>
<summary>Case 1: Default behavior - `#brave-adblock-custom-scriptlets` flag not enabled</summary>

1. Installed 1.75.121
2. launched Brave
3. opened brave://flags in a new tab
4. confirmed `#brave-adblock-custom-scriptlets` flag is disabled by default
5. opened brave://settings/shields/filters in a new tab
6. confirmed `Custom scriptlets` section is not shown 
7. confirmed `Developer mode` toggle is turned off by default
8. confirmed `Create custom filters text area (CFT) is in read only mode/disabled state
9. opened https://example.com in a new tab
10. opened context menu >> Block element >> selected text >>Block Element1. returned brave://settings/shields/filters page and refreshed the page
12. confirmed blocked rule is shown in the custom filters box
13. confirmed this box is read only as I tried to delete the content and unable to do. 
14. returned to https://example.com tab
15. confirmed blocked element is hidden on the page as expected

step 6 | step 7 | step 9 | step 12 | step15
------- | ------- | ------- | ------- | -------
![Image](https://github.com/user-attachments/assets/e427e112-e580-41c5-b642-45ec81340292)|![Image](https://github.com/user-attachments/assets/242913eb-3538-4aac-9f06-a4dd40bb109e)|![Image](https://github.com/user-attachments/assets/445f58cd-cc5b-45e1-8d1f-828c452b9cfb)|![Image](https://github.com/user-attachments/assets/31dbfe41-d57d-4c64-86cd-2238090ce589)|![Image](https://github.com/user-attachments/assets/6a70ea25-158f-4005-8605-98560a13a849)
</details>

<details>
<summary>Case 2: `#brave-adblock-custom-scriptlets` flag not enabled but Developer mode toggle is enabled</summary>

1.New profile
2. launched Brave
3. opened `brave://flags` in a new tab
4. confirmed `#brave-adblock-custom-scriptlets` flag is disabled by default
5. opened `brave://settings/shields/filters` in a new tab
6. toggled `ON `Developer mode` toggle 
7. added "example.com##[href*="https://www.iana.org/domains/example"]" in the custom filters text box
8. clicked `Save Changes` button
9. visited https://example.com in a new tab
10. confirmed `More Information...` link is not shown
11. returned to `brave://settings/shields/filters` 
12. deleted the rule from step 7 from the text box and clicked `Save changes`
13. returned to https://example.com tab and refreshed the page
14. confirmed `More information...` link is shown

step 4 | step 6 | step 7 | step 12 | step 14
------ | ------ | ------ | ------ | ------
![Image](https://github.com/user-attachments/assets/060af1ef-a47d-49d9-86be-c8e86760ec87)|![Image](https://github.com/user-attachments/assets/f8109214-df1a-444f-a042-645551e44ce8)|![Image](https://github.com/user-attachments/assets/3a82dadf-bef1-4f56-80fb-43851aba0317)|![Image](https://github.com/user-attachments/assets/6b773a57-258e-462e-9161-6f92a00f130b)|![Image](https://github.com/user-attachments/assets/f6740ec5-661f-4235-a189-229116d14f32)

</details>

Case 3: `#brave-adblock-custom-scriptlets` flag enabled but Developer mode toggle is enabled</summary>


1. New profile
2. launched Brave
3. opened `brave://flags` in a new tab
4. enabled `#brave-adblock-custom-scriptlets` flag 
5. clicked Relaunch button
6. opened `brave://settings/shields/filters` in a new tab
7. confirmed `Custom scriptlets` section is shown in disabled state 
8. toggled `ON `Developer mode` toggle Open brave://settings/shields/filters
9. confirmed both `Save Changes` button in CFT and `Add new scriptlet` button in `Custom scriptlets` area are enabled
10. clicked `Add new scriptlet` 
11. confirmed a dialog shown
12. confirmed a placeholder text is shown `Don't paste code here...)
13. added `my-script` to Name text field
14. added `console.log('my-script')` in the content text box 
15. clicked 'Save`
16. confirmed the `user-my-script.js` is shown in the custom scriptlet list
17. added "example.com##+js(user-my-script.js)" rule in CFT and save changes
18. visited https://example.com in a new tab 
19. opened DevTools console
20. confirmed "my-script" message shown
21. returned to `brave://settings/shields/filters`
22. opened `user-my-script.js` in the `Custom sriptlets` section 
23. edited from `my-script` to test25586' in the console.log and clicked `Save`
24. returned to example.com tab and reload the page
25. confirmed console shows `test25586` 
26. closed Browser and reopened 
27. navigated to `example.com` page and confirmed message is still shown

step 4 | step 7 | step 9 | step 11 | step 13-15 | step 16 | step 17 | step 20 | step 23 | step 27
-------- | ------- | ------- | -------- | ---------- | --------- | ---------- | --------- | ------ | ---------
![Image](https://github.com/user-attachments/assets/082e2712-4474-4972-880c-da93aa300faf)|![Image](https://github.com/user-attachments/assets/a42e8850-806f-49a7-9e00-b90b03858889)|![Image](https://github.com/user-attachments/assets/7801f4a7-7fa7-402e-9548-d7be5ae52bd2)|![Image](https://github.com/user-attachments/assets/e0fa7bdd-db28-403e-a1b1-2fdd3b44f4e8)|![Image](https://github.com/user-attachments/assets/b5b5f919-2867-49a8-988b-ac375303a326)|![Image](https://github.com/user-attachments/assets/e20146ab-640c-49d1-b1d5-c57ad012a8a1)|![Image](https://github.com/user-attachments/assets/c6c0cab9-2866-421e-974f-2d971bb0ecea)|![Image](https://github.com/user-attachments/assets/365af3aa-9cb6-4f63-8b2a-36a99e93c553)|![Image](https://github.com/user-attachments/assets/43f2b9b8-3755-48c6-8044-9cb47bb81ab5)|![Image](https://github.com/user-attachments/assets/f1b9c7ef-88d0-46a3-89a4-88f656696533)

</details>





Go to the settings and turn off Developer mode
Custom scriptlets should disappear
Reload example.com, check there is no messages from scriptlets in the devtools console.
Go to the settings enable Developer mode and delete user-my-script.js by clicking the trash icon
Reload example.com check there is no messages from scriptlets in the devtools console.

**Comment by kjozwiak** [comment]
Removed `OS/Android` after checking with @boocmp. The above is currently for `Desktop` only and hasn't been implemented on `Android`.

**Comment by alexpontess** [comment]
> Removed `OS/Android` after checking with [@boocmp](https://github.com/boocmp). The above is currently for `Desktop` only and hasn't been implemented on `Android`.

Dear, please put this functionality on both Android and iOS versions. This will help a lot, allowing for greater control on the user's side.

An example would be that we can put a script to run Spotify on Android as if it were on Desktop. The script code example:

WebSpotify

Make spotify web player working on mobile device.

https://greasyfork.org/pt-BR/scripts/394873-webspotify

// ==UserScript==
// @name WebSpotify
// @namespace http://tampermonkey.net/
// @Version 0.2
// @description Make spotify web player working on mobile device.
// https://github.com/run-at document-start
// https://github.com/author gvvad
// @include http*://open.spotify.com/*
// @license MIT; https://opensource.org/licenses/MIT
// @copyright 2020, gvvad
// @grant none
// @namespace https://greasyfork.org/users/100160
// ==/UserScript==

(function () {
'use strict';
let _scr = {};
for (const key in window.screen) {
_scr[key] = window.screen[key];
}
Object.setPrototypeOf(_scr, Object.getPrototypeOf(window.screen));

_scr.width = 1080;
_scr.height = 1920;

window.screen = _scr;
})();

I have already tested this script in another browser on Android and it worked perfectly. I suggest you even incorporate this script as a Brave feature into the Android and iOS mobile versions.

Thank you for your attention!

**Comment by grant** [comment]
Hey please don't @ me
