### ISSUE TITLE
Add Account Filter to Portfolio Overview

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#25587]
## Description 
Add an `Account Filter` to `Portfolio Overview` screen

https://user-images.githubusercontent.com/40611140/192011235-1f2e60de-6c53-49c8-9425-e604331371db.mov

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.46.70 Chromium: 107.0.5304.36 (Official Build) beta (64-bit) 
-- | --
Revision | `2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}`
OS | Linux

- Verified steps from [brave/brave-core#15218](https://github.com/brave/brave-core/pull/15218)
- Verified able to filter accounts by network on Portfolio page

https://user-images.githubusercontent.com/17010094/197803953-6e464943-018c-42f4-9088-10ce43b8b783.mp4


------------------------
Verification passed on

Brave | 1.46.70 Chromium: 107.0.5304.36 (Official Build) beta (64-bit) 
-- | --
Revision | `2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}`
OS | Windows 11 Version 22H2 (Build 22621.674)

- Verified steps from [brave/brave-core#15218](https://github.com/brave/brave-core/pull/15218)
- Verified able to filter accounts by network on Portfolio page

https://user-images.githubusercontent.com/17010094/197804223-90074ff7-af01-483b-9181-9248f84a7bb4.mp4

------------------------
Verification passed on

Brave | 1.46.70 Chromium: 107.0.5304.36 (Official Build) beta (arm64)
-- | --
Revision | `2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#15218](https://github.com/brave/brave-core/pull/15218)
- Verified able to filter accounts by network on Portfolio page

https://user-images.githubusercontent.com/17010094/197804619-1366c08c-f55b-4680-9a57-e13c87a32d3e.mov
