### ISSUE TITLE
Invalid or malformed RSS feed can cause a crash when added to Brave News

### ISSUE THREAD

**Issue by mattmcalister** [brave/brave-browser#25584]
1. On desktop go to Brave News settings 
2. Paste an invalid RSS Feed Url such as `https://nymag.com/rss/The_Power_Grid.xml` and hit enter

reproduced on both Nightly and Release

**Comment by rebron** [comment]
Can you go to brave://crashes and post the crash id

**Comment by stephendonner** [comment]
Not much useful here on macOS stack-wise, but I can reproduce 100% using 

Brave | 1.43.93 Chromium: 105.0.5195.127 (Official Build) (x86_64)
-- | --
Revision | 912488396852bf658ab32465980c0b93a3c27a83-refs/branch-heads/5195@{#1109}
OS | macOS Version 13.0 (Build 22A5352e)

https://share.backtrace.io/api/share/inWZ1sQFrHUYqwrcFPpNv1

```
[ 00 ] __pthread_kill
[ 01 ] 0x7ff80bd39f7b
[ 02 ] abort
[ 03 ] 0x11fb5a656
[ 04 ] 0x11fb5a620
[ 05 ] 0x122e281be
[ 06 ] 0x122e27cd3
[ 07 ] 0x11b181cb6
[ 08 ] 0x11c729c38
[ 09 ] 0x119fcabfd
[ 10 ] 0x11a14d5a7
[ 11 ] 0x11a2494d4
[ 12 ] 0x11a7b92d4
[ 13 ] 0x11feb2a2d
[ 14 ] 0x11ad783d7
[ 15 ] 0x11a9a9713
[ 16 ] 0x7ff80bd3a259
[ 17 ] 0x7ff80bd35c7b
[ 18 ] 0x11a9a9660
```

**Comment by neeythann** [comment]
possibly fixed by https://github.com/brave/brave-browser/issues/26604 (?)

**Comment by rillian** [comment]
Should be. I can't reproduce with the url above. Please reopen if the issue re-occurs on 1.47.121 or later.
