### ISSUE TITLE
BATs are not increasing after ad view. 

### ISSUE THREAD

**Issue by Santhoshkumarmamidala** [brave/brave-browser#25594]
## Description 
After ad view, still it is showing Zero bats. It is not a all increasing. It is showing zero dispite of viewing the multiple ads

## Steps to reproduce 

   1. Watch the add
   2. Check the bat count
   3. 

## Actual result 

![Screenshot_20220924-022743](https://user-images.githubusercontent.com/114261883/192055429-78bf3ab8-cf97-4183-bdb1-529e184f5257.jpg)

## Expected result

BAT should increase as per add
## Issue reproduces how often 
Everytime

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version?  Yes
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

![Screenshot_20220924-022743](https://user-images.githubusercontent.com/114261883/192055436-b330c641-ed42-4ebb-9c44-2ebe0c8e0d2c.jpg)

**Comment by Santhoshkumarmamidala** [comment]
![Uploading Screenshot_20220924-022749.jpg…]()

**Comment by Santhoshkumarmamidala** [comment]
![Screenshot_20220924-023326](https://user-images.githubusercontent.com/114261883/192056377-ea5b83b3-d38a-4f0c-a2c5-251ab0baee80.jpg)

**Comment by Miyayes** [comment]
Can you send your brave://rewards-internals (general info), copy-paste the text, to christopher@brave.com with a link to this issue? Thanks.
