### ISSUE TITLE
[Android 13] Restyle Chromium enable notifications dialog

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#25593]
**Summary**
CR106 introduced a new dialog to encourage users to enable notifications. This dialog was appearing during and interfering with our onboarding. As a quick fix we moved the dialog outside of the onboarding experience.

We now need to restyle the dialog to be more inline with our styling and call out Brave features that require notifications to function. e.g. rewards and privacy report.

![image](https://user-images.githubusercontent.com/28269287/192041634-b12cb940-cffc-4422-bd19-dca646a18ac7.png)

**Comment by deeppandya** [comment]
@Sam-Sibley can you attach figma spec here ?

**Comment by Sam-Sibley** [comment]
@deeppandya , Ryan has done the copy. This is good to go.
<img width="364" alt="Screenshot 2022-10-13 at 11 18 45 am" src="https://user-images.githubusercontent.com/99699532/195476793-8253745e-56e6-4e9d-9f1f-51fd289bdf34.png">

Here is the link:
https://www.figma.com/file/sdVBBufbl2A11hAgPNfyqG/Android-13-Notifications?node-id=363%3A30672

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 13` using the following build(s):

```
Brave | 1.46.130 Chromium: 108.0.5359.62 (Official Build) (32-bit)
--- | ---
Revision | 041930a89a990cfab0315a2d9f20d6429a4a67cf-refs/branch-heads/5359@{#938}
OS | Android 13; Build/T1B3.221003.008
```

Went through the STR/Cases outlined via https://github.com/brave/brave-browser/issues/25593#issuecomment-1276907394 and ensured that the new UI is working as per the following:

* ensured that the `Android 13` permission modal appears once the URL bar onboarding has completed
* ensured that tapping on `Continue` displays the `system` permission screen without any issues
* ensured that tapping on `Not now` closes the modal without loading the `system` permission modal
* ensured that the screen/modal only appears once after the URL onboarding (ensuring it's not seen a second time)

**`Example`** | **`Example`**
---------------|----------------
![Screenshot_20221130-002943](https://user-images.githubusercontent.com/2602313/204715820-82fecdf4-dcaf-4056-8375-b531bac670da.png) | ![Screenshot_20221130-002949](https://user-images.githubusercontent.com/2602313/204715828-7394f07e-d8ed-4141-8165-482ae1bcba71.png)
