### ISSUE TITLE
Brave Toolbar button color is inverted (and partially invisible) when using "Dark Colors" with a Theme using a light color toolbar

### ISSUE THREAD

**Issue by Sekt0rX** [brave/brave-browser#25597]
## Description 

Toolbar colors are inverted (and the "clickable" buttons are unreadable) when "Brave colors" is set to Dark and a Theme with a light toolbar is applied. This only started after updating Brave to v1.43.93 (although it had been about 2months since I last updated). Using Windows 10.

## Steps to Reproduce

   1. Set "Brave colors" to "Dark" in Brave Settings.
   2. Apply a Theme from the Chrome Web Store which uses a light toolbar e.g. https://chrome.google.com/webstore/detail/modern-flat/pdcjjgefkpoemmlcjfcfkeminneboaob

## Actual result:

![Inverted](https://user-images.githubusercontent.com/101000511/192093837-4ba2a440-56bb-434f-9b4f-68add64a554d.JPG)

Circled in red are the areas with almost invisible buttons, I'm also hovering over the Refresh button.

## Expected result:

The "clickable/active" buttons should be a darker color (and readable) and the "unclickable/inactive" buttons (see the "Forward" button in the screenshot) should be a lighter color to the Clickable/Active buttons.

## Reproduces how often: 

Always.

## Brave version (brave://version info)

Brave | 1.43.93 Chromium: 105.0.5195.127 (Official Build) (64-bit)
Revision | 912488396852bf658ab32465980c0b93a3c27a83-refs/branch-heads/5195@{#1109}
OS | Windows 10 Version 21H1 (Build 19043.1826)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes.
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
Changing the "Brave colors" to "Light" in the Brave settings does fix the inverted and invisible issue but also causes the "Active" buttons to be come darker than usual (the color is very saturated).

**Comment by simonhong** [comment]
@Sekt0rX Fix for this is merged to master. Thanks for reporting! 👍🏼

**Comment by simonhong** [comment]
@rebron @kjozwiak Do you think we need to uplift this?

**Comment by kjozwiak** [comment]
> @rebron @kjozwiak Do you think we need to uplift this?

@simonhong apologies, totally missed this one for some reason. I didn't notice it listed under `@mentions` via GH. I think at this point we can just leave this in `1.46.x` and let it ride the trains. Seems like a minor issue that's not affecting that many users. If we stat getting more `++` from other users, we could try squeezing this into a `1.45.x` maintenance release.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.46.90 Chromium: 107.0.5304.91 (Official Build) beta (x86_64)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | macOS Version 12.6.1 (Build 21G217)
```
