### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Ravendwyr** [brave/brave-browser#25592]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.43.94  Chromium: 105.0.5195.136
Operating System: Android 11

URL (if applicable) where crash occurred: N/A

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Enable Brave News
2. Open new tab
3. Scroll down a bit to read the articles
4. Close new tab

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/93410100-0868-e108-0000-000000000000

**Comment by iefremov** [comment]
must be a duplicate https://github.com/brave/brave-browser/issues/23338
