### ISSUE TITLE
Next payment date is blank; estimated earnings, ads viewed are zeroed out

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#25595]
## Description

Reported by @Brave-Matt. 

![image](https://user-images.githubusercontent.com/11497541/192056709-750c0fd1-e01a-4c2c-82dd-cd0446e157fd.png)

`v1.46.7 (Nightly)` 

brave://rewards-internals looks normal. Rewards profile is not flagged. 

**@zenparsing noted this in the logs:**
```
[Sep 23, 2022, 3:54:01.2 PM:INFO:database_manager.cc(107)] Migrating database from schema version 8 to schema version 25
[Sep 23, 2022, 3:54:01.2 PM:INFO:database_manager.cc(123)] Failed to migrate database from schema version 8 to schema version 25
[Sep 23, 2022, 3:54:01.2 PM:ERROR:ads_impl.cc(443)] Failed to create or open database
[Sep 23, 2022, 3:54:01.2 PM:INFO:ads_impl.cc(529)] Failed to initialize ads
```

@brave/ads-dev @tmancey @aseren

**Comment by tmancey** [comment]
cc @ptjames

**Comment by Miyayes** [comment]
@tmancey Has this been resolved, or is there any more information needed here?

**Comment by tmancey** [comment]
This issue has not been reported in a while, I would close and open a new issue if it reoccurs. Thanks
