### ISSUE TITLE
Broken clipboard icon for Wallet address

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#25607]
## Steps to Reproduce

   1. Install 1.45.68
   2. Create wallet and open account details page 
   3. Click on QR code to view address/QR Code
   4. Clipboard icon is shown properly

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/192265732-e73c179f-28ec-40c4-ac7d-3060e374166a.png)

## Expected result:
![image](https://user-images.githubusercontent.com/17010094/192265910-e3db75b2-f5bb-4378-922d-16e53d98341f.png)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.45.68 Chromium: 106.0.5249.55 (Official Build) beta (64-bit) 
-- | --
Revision | 4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}
OS | Windows 11 Version 21H2 (Build 22000.978)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel @muliswilliam

**Comment by Douglashdaniel** [comment]
This issue is no longer present on our current supported release version 1.46.x
Closing as `invalid`.

https://user-images.githubusercontent.com/40611140/212139734-e990e627-d7fc-45bf-8153-b3d8050b07bd.mov
