### ISSUE TITLE
Enable swaps for Ropsten test networks

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#25606]
## Description 
Enable swaps for Ropsten test networks, mimic changes for solana if required

## Steps to reproduce 

   1. Create wallet and select ropston
   2. No swap option is visible

## Actual result 
No swap option is visible on Ropsten

## Expected result
Show swap option for Ropsten

**Comment by wchen342** [comment]
Checked on Desktop Nightly. Swap is not enabled on Solana Devnet or Testnet.
