### ISSUE TITLE
Export/Backup all opened tabs as text file

### ISSUE THREAD

**Issue by tathastu871** [brave/brave-browser#25603]
## Description 
Please, i have 1000s of tab open in my brave browser.
Now i am switching phone and want all that tabs to be opened on new phone in brave browser.

My phones usb is broken so i cannot use Android debug bridge to backup tabs using remote chrome feature.

**Please add option to export list of all opened tabs on brave, so atleast we can use that list and bulk open them on another browser**h

## Expected result

MENU --> Export opened tabs to text file
## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): PHONE
   - Android version: 10
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by tathastu871** [comment]
PLEASE MAKE IT IMMEDIATE ISSUE

**Comment by tathastu871** [comment]
Such happened with me thrice my phone got broken and i lost all opened yabs

**Comment by tathastu871** [comment]
Pleading to add this feature. I have a habit of opening all interested links in new tabs and then viewing them later on when i have time.

This way brave accumulated 1000s of opened tabs.
I want to backup those tabs as text file so that i can import them to bookmarks. 
Manually bookmarking all opened tabs is not feasinle and brave sync already has several issues, hence data lost is inevitable.


Please add this fast

**Comment by tathastu871** [comment]
why the hell no one taking it important,
like me several people when switching their phones wanted their old phone brave opened tabs to be opned in new phone

**Comment by tathastu871** [comment]
please begging to ass this feature it wont take much time for developers to add meny entey to export tabs list from brve internal files to sdcard

**Comment by tathastu871** [comment]
Pleas add it i want to change phone but unable to as i have 10000s tab opened on brave on old phone and want all them to be opened on new phone. 
My old phone usb cirxuit is broken so i cannot backup tabs using adb

**Comment by tathastu871** [comment]
@mihaiplesa

**Comment by mihaiplesa** [comment]
Have you tried Brave Sync or Wireless ADB?

**Comment by tathastu871** [comment]
> Have you tried Brave Sync or Wireless ADB?

wireless adb work only in android 11.
android 10 or below require one time usb connection to start adb in tcpip mode. and my phone usb is completely broken

brave syncs dont even sync bookmarks. and aboyt tabs it does'nt. i have 10000 tabs opned. i juts want to export list of them

**Comment by tathastu871** [comment]
> Have you tried Brave Sync or Wireless ADB?

many people have habit of opening tabs and virwing them later. 
it occuref to me 5 times i had to reset phone or change phone and i lost my tabs

**Comment by tathastu871** [comment]
brave must be having list of opened tabs in its internal data just add option to export them.
i dont root otherwise i would have backed up brave

**Comment by tathastu871** [comment]
> Have you tried Brave Sync or Wireless ADB?

brave sync dont work for tabs. if i reset my phone and  install on other brave sync wont open all those open apps

**Comment by tathastu871** [comment]
@brave-dev 
I am a tab hoardet like many out there  
Please implement this feature  
i have lost 1000s of valuable  tabs
