### ISSUE TITLE
Change behaviour for notification permission rationale 

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#25610]
This issue is to change the timing of showing the chromium notification permission dialog. 
For more reference : https://bravesoftware.slack.com/archives/C03MMJ4CHEZ/p1663909683137019

**Comment by kjozwiak** [comment]
The above requires `1.44.101` or higher for `1.44.x` verification 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 13` using the following build(s):

```
Brave | 1.44.101 Chromium: 106.0.5249.65 (Official Build) (32-bit)
--- | ---
Revision | 3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}
OS	Android 13; Build/T1B1.220819.006
```

Went through the STR/Cases outlined via https://github.com/brave/brave-core/pull/15214#issuecomment-1258841930 as per the following:

**Selecting `Continue` Test Cases**

<table>
<tr><td>

https://user-images.githubusercontent.com/2602313/192446645-e41f6b8f-49a0-401e-aa04-500c7849c409.mp4

</td><td>

https://user-images.githubusercontent.com/2602313/192446732-08ee4666-4419-4eeb-9428-7c5156b8d3f0.mp4

</td></tr>
</table>

**Selecting `No thanks` Test Cases**

<table>
<tr><td>

https://user-images.githubusercontent.com/2602313/192446842-a4652205-d29a-41cb-8309-6f859435d84f.mp4

</td><td>

https://user-images.githubusercontent.com/2602313/192446888-d1d7cf34-0374-4e0e-8bbb-0e6a8a1a0f23.mp4

</td></tr>
</table>
