### ISSUE TITLE
[Android] Add option to enable/disable download bubbles

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#25611]
### Summary
A large number of users have complained about the download bubbles Chromium introduced earlier this year. 

**Bubble Examples:**

| Downloading File  | File Downloaded |
| ------------- | ------------- |
| ![Image](https://user-images.githubusercontent.com/28269287/192338540-6feac6c0-8c87-4219-984a-b161bc7eae58.png) | ![Image](https://user-images.githubusercontent.com/28269287/192338604-b9e31b84-55c6-41d7-a5f6-d91ccded848f.png) |

**Complaints:**

- https://community.brave.com/t/remove-download-bubbles/434423
- https://community.brave.com/t/give-option-to-disable-download-bubble-notifications/343837
- https://community.brave.com/t/annoying-download-bubbles/406793
- https://community.brave.com/t/download-notification-bubble-cannot-be-turned-off/343735
- https://community.brave.com/t/is-there-anyway-to-disable-the-download-finished-pop-up-bubble/404857
- https://appfigures.com/reviews/266342430751LF2UH_DfH03PI1J29AvpwBg?lang=en
- https://appfigures.com/reviews/266342430751L4Km_f4hHiFH7a8DuyFg6fg?lang=en
- https://appfigures.com/reviews/266342430751LYr0fbjNywezTwMtw_6DGow?lang=en
- https://appfigures.com/reviews/266342430751L6kzQl2dj33HMct20zAIbYw?lang=en

### Requirements
We should disable the bubbles by default and add an option in download settings to allow users to switch the bubbles on/off.

![Image](https://user-images.githubusercontent.com/28269287/192337823-cb7f77e9-e1ea-483a-b0e1-2a59a73299aa.png)

### Copy
Show download progress notifications
On/Off

@deeppandya as discussed on triage call - let's also update the "ask where to save files" copy to:

"Ask where to save files (if SD card is detected)"

**Comment by rmcfadden3** [comment]
@timchilds — could we do a parenthetical here? So like"

"Ask where to save files (if SD card is detected)"

**Comment by Uni-verse** [comment]
Verified on `1.49.118, Chromium 111.0.5563.50` using the following devices:

Samsung GS 21, Android 13
Samsung Tab S7, Android 12
Pixel 5, Android 8

- Ensured copy update in downloads settings
- Ensured that enabling `download progress notification` will enable download bubbles

GS 21 | GS 21 | GS 21
-|-|-
![screenshot-1678203170354](https://user-images.githubusercontent.com/17885425/223473876-1315a187-8131-4edb-84d3-e4215a6bf0d5.png) | ![screenshot-1678203243038](https://user-images.githubusercontent.com/17885425/223473884-dccc6270-98ec-4760-85c5-c6e6f3e05cfa.png) | ![screenshot-1678203313298](https://user-images.githubusercontent.com/17885425/223473893-7f84040f-d815-4f89-a24f-7da858a5a5a1.png)

Tab S7 | Tab S7
-|-
![screenshot-1678203813716](https://user-images.githubusercontent.com/17885425/223474063-6ada5837-1c88-4fa3-aaa8-b8d78334a312.png) | ![screenshot-1678203828776](https://user-images.githubusercontent.com/17885425/223474069-050f452d-a175-4600-b431-9a7bac7179b7.png)

Pixel | Pixel
-|-
![Screen Shot 2023-03-07 at 10 36 17 AM](https://user-images.githubusercontent.com/17885425/223474276-8ce93e93-22fa-4033-93c9-114bae3b36c8.png) | ![Screen Shot 2023-03-07 at 10 36 44 AM](https://user-images.githubusercontent.com/17885425/223474297-f3de5692-542a-4307-b998-b1bb060d5924.png)
