### ISSUE TITLE
Unable to import/migrate with new onboarding when legacy wallet is used

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#25612]
## Description 

Unable to import/migrate with new onboarding when legacy wallet is used

## Steps to Reproduce

   1. Import 24 word seed into Crypto Wallet extension
   2. Use new Brave Wallet onboarding to migrate
   3. Fails to import with error. Goes into a infinite loop

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/192337974-6ea14c11-5bcd-457f-8f64-a7610df4ec51.png)

## Expected result:
Should be able to import legacy wallet without error

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.44.99 Chromium: 106.0.5249.55 (Official Build) (64-bit)
-- | --
Revision | `4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}`
OS | All

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @josheleonard @darkdh @bbondy

**Comment by srirambv** [comment]
Issue happens on current release as well. Removed P1/Release blocking labels
![image](https://user-images.githubusercontent.com/17010094/192350464-12f49b9a-4967-4175-b1d9-695f3d8eaff2.png)

**Comment by kjozwiak** [comment]
The above requires `1.44.102` or higher for `1.44.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.44.103 Chromium: 106.0.5249.65 (Official Build) (64-bit) 
-- | --
Revision | `3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}`
OS | Windows 11 Version 21H2 (Build 22000.978)

- Verified steps from issue and [brave/brave-core#15221](https://github.com/brave/brave-core/pull/15221)
- Verified able to migrate from 24-word seed Legacy wallet to new wallet
- Verified able to migrate from 12-word deprecate Crypto Wallet to new wallet
- Verified able to migrate from 12-word MetaMask wallet to new wallet

24-Word Import | 12-Word Import | MM Import
-- | -- | --
<video src=https://user-images.githubusercontent.com/17010094/193087496-eae5d71a-0b76-476e-89af-b8e8a766cd61.mp4> | <video src=https://user-images.githubusercontent.com/17010094/193087465-9f39ae79-a950-44dc-8519-eff3163cabb8.mp4> | <video src=https://user-images.githubusercontent.com/17010094/193087444-1e058c04-440c-424f-b488-e6d416b76da2.mp4>

-------------
Verification passed on 

Brave | 1.44.103 Chromium: 106.0.5249.65 (Official Build) (x86_64 translated)
-- | --
Revision | 3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}
OS | macOS Version 12.6 (Build 21G115)

- Verified steps from issue and [brave/brave-core#15221](https://github.com/brave/brave-core/pull/15221)
- Verified able to migrate from 24-word seed Legacy wallet to new wallet
- Verified able to migrate from 12-word deprecate Crypto Wallet to new wallet
- Verified able to migrate from 12-word MetaMask wallet to new wallet

24-Word Import | 12-Word Import | MM Import
-- | -- | --
<video src=https://user-images.githubusercontent.com/17010094/193090316-6ed6ce53-ec9d-4b6b-9d6b-8695cefb3357.mov>  | <video src=https://user-images.githubusercontent.com/17010094/193090197-29a91192-f48d-46d7-95ab-b896627116c2.mov>  | <video src=https://user-images.githubusercontent.com/17010094/193091171-156465a3-2aa7-4467-a548-c0d97c8dcda2.mov>  
---------------
Verification passed on 

Brave | 1.44.103 Chromium: 106.0.5249.65 (Official Build) (64-bit) 
-- | --
Revision | `3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}`
OS | Linux

- Verified steps from issue and [brave/brave-core#15221](https://github.com/brave/brave-core/pull/15221)
- Verified able to migrate from 24-word seed Legacy wallet to new wallet
- Verified able to migrate from 12-word deprecate Crypto Wallet to new wallet
- Verified able to migrate from 12-word MetaMask wallet to new wallet

24-Word Import | 12-Word Import | MM Import
-- | -- | --
<video src=https://user-images.githubusercontent.com/17010094/193093714-bc91ffb4-0a7a-473a-9f56-586c1da044b2.mp4>  | <video src=https://user-images.githubusercontent.com/17010094/193093737-7d05c10c-5409-45e7-8a9d-06786ab88b74.mp4>  | <video src=https://user-images.githubusercontent.com/17010094/193093698-d1468d5f-a2f2-4de0-a998-9f6b40e16c41.mp4>
