### ISSUE TITLE
Capitalize Ledger in authorize window

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#25616]
## Description 

Capitalize Ledger in authorize window

## Steps to Reproduce

   1. Connect Ledger wallet 
   2. Initiate Import from  Ledger wallet
   3. Message reads `ledger`, should be `Ledger`

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/192343821-affcae5e-9c4c-4372-8a17-59f3096b196b.png)

## Expected result:
![image](https://user-images.githubusercontent.com/17010094/192344230-9bb3651b-27c1-4066-9754-d649819638a0.png)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.44.99 Chromium: 106.0.5249.55 (Official Build) (64-bit)
-- | --
Revision | `4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}`
OS | All

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @nvonpentz @Douglashdaniel @onyb @jamesmudgett

**Comment by kjozwiak** [comment]
The above requires `1.45.79` or higher for `1.45.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (64-bit) 
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | Linux

- Verified steps from issue description
- Verified Ledger is correctly capitalized
![image](https://user-images.githubusercontent.com/17010094/195618283-2036eb09-1b5e-4e65-8bbc-776167eb4c4e.png)

------------------------
Verification passed on

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (64-bit) 
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | Windows 11 Version 21H2 (Build 22000.978)

- Verified steps from issue description
- Verified Ledger is correctly capitalized
![image](https://user-images.githubusercontent.com/17010094/195618756-c048f928-75dc-4ff9-9e59-88fee5c46bb0.png)

------------------------
Verification passed on

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (arm64)
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from issue description
- Verified Ledger is correctly capitalized

![image](https://user-images.githubusercontent.com/17010094/195618886-743cabaf-ac32-4e1b-b055-9c2ebda9384d.png)
