### ISSUE TITLE
Make bg playback as a feature flag

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#25613]
Make it as a flag and disabled by default. We are going to enable it via griffin after that.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.46.87 x64 Beta build
- Verified steps from [brave/brave-core#15357](https://github.com/brave/brave-core/pull/15357)
- Verified a new flag `brave://flags#brave-background-video-playback` is available 
- Verified background video playback setting is disabled by default
- Verified on a upgrade profile, if setting is enabled the state is retained post upgrade

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/199439949-44f80bc9-d428-48af-804d-d5ec35a05f25.mp4> | <video src=https://user-images.githubusercontent.com/17010094/199452288-a5a969f7-51ff-43ab-be90-6420c9406ca3.mp4>
