### ISSUE TITLE
Unable to Authorize and sign transactions for Ledger accounts

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#25623]
## Description 

Unable to Authorize and sign transactions for Ledger accounts

## Steps to Reproduce

   1. Clean profile 
   2. Connect Ledger wallet and import an account
   3. Initiate a send transaction from Ledger to another account
   4. Approve/Reject the transaction on Ledger
   5. Open `brave://inspect/#other` 
   6. Click on Wallet panel 
   7. Shows 2 entries for `chrome://wallet-panel.top-chrome/` , (logged [#25619](https://github.com/brave/brave-browser/issues/25619))
   8. Run `(await navigator.hid.getDevices()).forEach((d) => d.forget())` on both entries
   9. Visit `https://metamask.github.io/test-dapp` and connect Ledger account
   10. Initiate Eth Sign, wallet panel shows `Authorize` message (as expected because of step 8)
   11. Doesn't show Sign message on Ledger device
   12. Initiate a Send transaction, wallet panel shows `Authorize` again, Ledger shows Sign transaction
   13. Cancel Sign message via Ledger
   14. Wallet Panel still shows Send transaction as pending approval/submit
   15. Resubmit send transaction, Ledger shows approval for send transaction
   16. Resubmit Eth sign message, Ledger now shows sign approval message

## Actual result:

Unable to Authorize and sign transactions for Ledger accounts

## Expected result:
Should be able to Sign message without having to do a Sign transaction approval

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.44.99 Chromium: 106.0.5249.55 (Official Build) (64-bit)
-- | --
Revision | `4d5f098fca6ab7f4b6b7c240be3d9593c2357709-refs/branch-heads/5249@{#531}`
OS | All

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Not checked
- Can you reproduce this issue with the nightly channel? Not checked

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @nvonpentz @josheleonard @kdenhartog

**Comment by kjozwiak** [comment]
The above requires `1.44.102` or higher for `1.44.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.44.103 Chromium: 106.0.5249.65 (Official Build) (64-bit) 
-- | --
Revision | `3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}`
OS | Windows 11 Version 21H2 (Build 22000.978)

- Verified steps from issue description
- Verified after running `(await navigator.hid.getDevices()).forEach((d) => d.forget())` and resubmitting a sign transaction, prompts to `Authorize` before signing the message

-------------
Verification passed on 

Brave | 1.44.103 Chromium: 106.0.5249.65 (Official Build) (x86_64 translated)
-- | --
Revision | 3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}
OS | macOS Version 12.6 (Build 21G115)

- Verified steps from issue description
- Verified after running `(await navigator.hid.getDevices()).forEach((d) => d.forget())` and resubmitting a sign transaction, prompts to `Authorize` before signing the message
---------------
Verification passed on 

Brave | 1.44.103 Chromium: 106.0.5249.65 (Official Build) (64-bit) 
-- | --
Revision | `3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}`
OS | Linux

- Verified steps from issue description
- Verified after running `(await navigator.hid.getDevices()).forEach((d) => d.forget())` and resubmitting a sign transaction, prompts to `Authorize` before signing the message
