### ISSUE TITLE
Add Portfolio Account Filter Pref APIs

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#25620]
## Description 
We need a `getPortfolioAccountFilter` and `setPortfolioAccountFilter` Pref API to persist user selection.

![Screen Shot 2022-09-26 at 1 12 43 PM](https://user-images.githubusercontent.com/40611140/192349968-094f22c0-232b-40b2-bbe8-a1899275b6d7.png)

**Comment by HEagle18** [comment]
https://github.com/brave/brave-browser/issues/27364 has been chosen instead to handle this issue.
