### ISSUE TITLE
Portfolio Fiat Balances not Loading

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#25626]
## Description 
The `Fiat Balances` are not rendering in the `Portfolio Overview` page until you change views.

https://user-images.githubusercontent.com/40611140/192369221-075b78fb-9e26-47fe-8106-afd27765b227.mov

**Comment by kjozwiak** [comment]
The above requires `1.45.77` or higher for `1.45.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (64-bit) 
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | Linux

- Verified steps from [brave/brave-core#15223](https://github.com/brave/brave-core/pull/15223)
- Verified reloading the portfolio page loads the Fiat balances

https://user-images.githubusercontent.com/17010094/195607180-3068e99c-0a5e-4045-8569-88c3ecb91ac4.mp4

------------------------
Verification passed on

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (64-bit) 
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | Windows 11 Version 21H2 (Build 22000.978)

- Verified steps from [brave/brave-core#15223](https://github.com/brave/brave-core/pull/15223)
- Verified reloading the portfolio page loads the Fiat balances

https://user-images.githubusercontent.com/17010094/195599524-1e1468df-ebd5-4727-a315-6dd834f2629c.mp4

------------------------
Verification passed on

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (arm64)
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [brave/brave-core#15223](https://github.com/brave/brave-core/pull/15223)
- Verified reloading the portfolio page loads the Fiat balances

https://user-images.githubusercontent.com/17010094/195597398-8a0e89ee-7e52-4b80-b891-77114fcae0a7.mov
