### ISSUE TITLE
Crashes with "Command failed" popup when Enable Brave Sync v2 set to Disabled

### ISSUE THREAD

**Issue by ForkedLightning** [brave/brave-browser#25624]
## Description 
Brave crashes with "Command failed" error when "Enable Brave Sync v2" is set to Disabled.

## Steps to Reproduce

   1. Go to brave://flags/
   2. Set "Enable Brave Sync v2" to "Disabled"
   3. Crashes when Settings is opened.

## Actual result:
Crashes with popup "Command failed".

## Expected result:
No crash.

## Reproduces how often: 
Easily reproduced

## Brave version (info found on brave://version)
<html>
<body>

Brave | 1.43.89 Chromium: 105.0.5195.102 (Official Build) (64-bit)
-- | --
Revision | 4c16f5ffcc2da70ee2600d5db77bed423ac03a5a-refs/branch-heads/5195_55@{#4}

</body>
</html>

**Comment by iefremov** [comment]
stale
