### ISSUE TITLE
Sanitize response bodies in `RewardsServiceImpl`

### ISSUE THREAD

**Issue by szilardszaloki** [brave/brave-browser#25628]
Use `data_decoder::JsonSanitizer` [here](https://github.com/brave/brave-core/blob/master/components/brave_rewards/browser/rewards_service_impl.cc#L1032) to sanitize and normalize response bodies coming back from server side.

cc: @brave/rewards-client

**Comment by kdenhartog** [comment]
@szilardszaloki is that the common entry point for all responses coming back from the server? It looks like there's quite a few calls being made within `brave-core/vendor/bat-native-ledger`

**Comment by kdenhartog** [comment]
I looked into this and confirmed that's the common entry point for RewardsService.
