### ISSUE TITLE
Better wording for `Copy Clean URL` context menu item

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#25621]
## Description 
When solving the feature https://github.com/brave/brave-browser/issues/23315 with https://github.com/brave/brave-core/pull/14763 we have (on the context menu), `Copy clean link (only main URL)`
![image](https://user-images.githubusercontent.com/4733304/192352221-7f762177-0517-4cd9-82bb-1a774d42f64e.png)

It might be better as `Copy clean link (remove tracking elements)` or `Copy clean link (strip query suffix)` (something like this)

When fixed, would need uplift to 1.45

cc: @rmcfadden3 @rebron can you help with wording on this?

**Comment by BrendanEich** [comment]
@pes10k @ShivanKaul thoughts welcome too.

**Comment by rmcfadden3** [comment]
@fmarier and I discussed this a couple weeks back, and arrived at the "Copy clean link (only main URL)" string after much back-and-forth. I'm good with it.

**Comment by pes10k** [comment]
as a novice user, im not sure i'd know what "only main URL" means (im not sure i know what it means a non-novice user!).  Why not just "Copy link address (clean)" or similar, so its clearly related to but distinct option from the existing "Copy link address" option?

**Comment by rmcfadden3** [comment]
@pes10k — @fmarier and I chose not to go that route, because the word "clean" is likely not universally understood by novice users. So we chose to "brand" the term as "clean", but then give a very short parenthetical definition of what "clean" means, too.

**Comment by pes10k** [comment]
that seems extremely confusing to me (and the wrong piece of UI) to define a term in a dropdown menu

I'm also surprised that i didn't see this option when i right click on a link. Is that intended?

**Comment by bsclifton** [comment]
@pes10k yes - that wasn't in scope for the MVP in original spec by @fmarier. I've captured that here https://github.com/brave/brave-browser/issues/25625

**Comment by rmcfadden3** [comment]
@pes10k — I'm definitely open to shifting. Some options off top of my head:

- Copy clean link (URL only)
- Copy clean link address (URL only)
- Copy link address (URL only)

Any other ideas?

**Comment by pes10k** [comment]
I dont think URL only works for any of these.  Query parameters are part of the URL.  I'm happy to hold my peace if folks feel otherwise, but I still don't understand the concern around "clean".  It captures the feature (both technically and literally), and a "clean" URL seems at least as understandable as what a "main" URL is.

Strong vote against "link" though too.  Its definitely not a link :)

Anyway, i'll sit on my hands for a bit, but thats my 2c

**Comment by ShivanKaul** [comment]
Agree that 'clean' without qualification seems fine - I think we should have documentation/support article/wiki/blog post explaining what exactly we mean by 'clean', but we don't need to make this confusing for users.

**Comment by rmcfadden3** [comment]
Per sidebar w/ @rebron , our latest idea for this string is:

`Copy clean URL (address only)`

**Comment by pes10k** [comment]
what is meant by (address only)?  The whole thing is the address
(regardless of weather there or some, a lot, or no query parameters), and
there are many query parameters we won't remove

**Comment by bridiver** [comment]
So seeing this for the first time I had absolutely no idea what "Copy clean URL" meant and adding "only main URL" made it even more confusing. I had to go back to the original issue to see what this feature does.

**Comment by rebron** [comment]
Some additional suggestions:

1. `Copy clean URL`  No further description
<img width="355" alt="Screenshot 2022-10-17 at 6 31 34 PM" src="https://user-images.githubusercontent.com/5951041/196314354-5073aee0-f636-49db-a8ae-b59cef0df85a.png">

2. `Copy clean link`   No further description. Relying on `clean` to differentiate from `Copy link` 
<img width="432" alt="Screenshot 2022-10-17 at 6 30 13 PM" src="https://user-images.githubusercontent.com/5951041/196314358-629cf960-914f-43cb-a769-fb469f2c2268.png">

3. `Copy clean link for sharing` 
<img width="405" alt="Screenshot 2022-10-17 at 6 30 59 PM" src="https://user-images.githubusercontent.com/5951041/196314360-81a0b887-132c-441c-9249-2e71d59061f9.png">

**Comment by rebron** [comment]
Right click context menu from the url bar.

1. Copy clean URL No further description
<img width="447" alt="Screenshot 2022-10-17 at 7 21 07 PM" src="https://user-images.githubusercontent.com/5951041/196323021-5f08e3b7-038c-442a-8cea-0f15b5d52863.png">

2. Copy clean link No further description. Relying on clean to differentiate from Copy link
<img width="476" alt="Screenshot 2022-10-17 at 7 21 20 PM" src="https://user-images.githubusercontent.com/5951041/196323051-1f17a492-9b76-42a3-bd71-973e08251a9d.png">

3. Copy clean link for sharing
<img width="423" alt="Screenshot 2022-10-17 at 7 21 56 PM" src="https://user-images.githubusercontent.com/5951041/196323112-fba0fe2f-a1e3-4a89-8c94-cafb009988b7.png">

**Comment by kjozwiak** [comment]
Labelling as `QA/No` in favour of https://github.com/brave/brave-browser/issues/26106 which we'll be used to verify https://github.com/brave/brave-core/pull/15518. CCing @rebron @bsclifton
