### ISSUE TITLE
`Copy Clean URL` on links in page

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#25625]
## Description 
Follow up to https://github.com/brave/brave-browser/issues/23315

For employees wanting to see the spec (by @fmarier), go on GDrive and search for `Copy clean URL`

For the MVP of the original feature, it only shows in two places. 
1. Share widget
    ![image](https://user-images.githubusercontent.com/4733304/192366614-a48b7894-edfd-4974-aa58-d46658510cf1.png)
2. Right clicking omnibox (url bar)
    ![image](https://user-images.githubusercontent.com/4733304/192366687-a78ee6ea-9a9c-48c3-a65b-6d4850802619.png)

**This functionality should also be on in-page links (when you right click)**. For example, here:
![image](https://user-images.githubusercontent.com/4733304/192366788-2cd488db-bce2-4b7f-9990-a77a79c10ba4.png)

From the spec:
> We could have a **Copy clean link address** option there too, but it requires more work since in that case we’ll have to first apply our normal URL modification rules (e.g. debouncing, query filter, de-AMP, HTTPS Everywhere) before applying the clean URL filter.
> 
> In order to ship the feature faster, this context menu will **not be part of the MVP** and will be addressed in a follow-up later.

**Comment by snowbound** [comment]
Just a FYI had an issue with this feature in Brave Beta as outline in my post on Brave [subreddit ](https://www.reddit.com/r/brave_browser/comments/xwkgcg/clean_url_not_working/)

**Comment by rebron** [comment]
<img width="341" alt="Screenshot 2023-09-15 at 11 56 02 AM" src="https://github.com/brave/brave-browser/assets/5951041/1a77947b-8f1e-4a35-b62c-7cb163391e02">
Closing, not sure when we added it to content menu though. 

cc: @spylogsster
