### ISSUE TITLE
Translate not working on several sites

### ISSUE THREAD

**Issue by tathastu871** [brave/brave-browser#25638]
## Description 
![20220927_150647](https://user-images.githubusercontent.com/65007212/192491490-50a75d44-a5b8-4ab6-bd5c-8c799929592e.jpg)

## Steps to reproduce 

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): Arm
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version:10
   
## Brave version 
Latest

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by tathastu871** [comment]
i can translate those pages with google translate bookmarklet

**Comment by SuRGeoNix** [comment]
it seems that brave messes up also with google translate extension

**Comment by samartnik** [comment]
closing as duplicate to this issue https://github.com/brave/brave-browser/issues/30388
