### ISSUE TITLE
Brave Ads database migration failing from schema 8 to 25

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#25630]
## Description 

Brave Ads database migration failing from schema 8 to 25

## Steps to Reproduce

   1. Launch the browser (fresh profile)
   2. Quit the browser
   3. Copy ads_service (reach out for this file via DM) to Defaults
   4. Launch the browser

## Actual result:

`Failed to initialize ads` appears in the console log

## Expected result:
`Successfully initialized ads` appears in the console log

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by tmancey** [comment]
Cause of issue is that the database tables and migration prefs have migrated but the database version and compatible version did not update. I have a fix however, I am Investigating the root cause.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.46.83 Chromium: 107.0.5304.68 (Official Build) beta (64-bit)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | Ubuntu 18.04 LTS

Due to profile used in STR not being available, regression test was done.

<details>

</details>
