### ISSUE TITLE
Remove window._brave_solana

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#25645]
Lazily loaded `//components/brave_wallet/resources/solana_provider_internal.js` suffers from various attacks other than prototype pollution. The best way to deal with it is making it invisible to global namespace. 
We will load the `solanaWeb3.js` module in v8 and then evaluate  the result from `PublicKey` and `Transaction` modules. 
Browser tests also needs an update because it is currently using `window._brave_solana` to generate test input for transactions.

**Comment by kjozwiak** [comment]
The above requires `1.45.91` or higher for `1.45.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (64-bit)
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | Linux

- Verified steps from [brave/brave-core#15247](https://github.com/brave/brave-core/pull/15247)
- Verified able to connect to Dapp
- Verified able to submit 1Sign Transaction1 & `Sign All Transaction`

https://user-images.githubusercontent.com/17010094/195857420-3472b891-ffb5-47ae-92a8-2b2e4c8a2e67.mp4

----------------
Verification passed on 

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (64-bit)
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | Windows 11 Version 21H2 (Build 22000.978)

- Verified steps from [brave/brave-core#15247](https://github.com/brave/brave-core/pull/15247)
- Verified able to connect to Dapp
- Verified able to submit 1Sign Transaction1 & `Sign All Transaction`

https://user-images.githubusercontent.com/17010094/195856657-291abb11-62f2-4174-b4ef-b53183efa8aa.mp4

----------------
Verification passed on 

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (arm64)
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | macOS Version 12.6 (Build 21G115)

- Verified steps from [brave/brave-core#15247](https://github.com/brave/brave-core/pull/15247)
- Verified able to connect to Dapp
- Verified able to submit 1Sign Transaction1 & `Sign All Transaction`

https://user-images.githubusercontent.com/17010094/195857896-25539da2-c053-498d-95e9-1660ed360584.mov
