### ISSUE TITLE
Adaptive captcha UI is broken ("refused to connect" error)

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#25640]
## Description 

Claim adaptive captcha UI is broken on staging env
## Steps to Reproduce

   1. Clean profile 1.46.14 staging env
   2. Enable rewards and view an ad
   3. Schedule a adaptive captcha
   4. Click on adaptive captcha notification to solve the captcha
   5. Captcha claim UI is broken

## Actual result:

![image](https://user-images.githubusercontent.com/38657976/192516421-e22f4389-95b9-4697-b7e8-0d5d7c8af6be.png)

## Expected result:
Should be abl eto clear the captcha

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.46.14 Chromium: 106.0.5249.61 (Official Build) nightly (64-bit)
-- | --
Revision | 511755355844955cd3e264779baf0dd38212a4d0-refs/branch-heads/5249@{#569}
OS | Windows 10 Version 21H2 (Build 19044.2006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Miyayes @gpestana @brave/qa-team @zenparsing 

Refer the thread for more details https://bravesoftware.slack.com/archives/CNH9Q6REV/p1664276596984569?thread_ts=1664208395.163569&cid=CNH9Q6REV

**Comment by gpestana** [comment]
I can reproduce this error when running nightly against staging backend. I'm seeing the current error:

```
[33026:259:0927/163139.333767:ERROR:CONSOLE(1)] "Refused to display 'https://grant.rewards.bravesoftware.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.", source: chrome-error://chromewebdata/ (1)
```

The backend is setting the following headers in the response that returns the payload to be rendered in the iframe ([here](https://github.com/brave-intl/bat-reputation/blame/master/controllers/v3/captchas.go#L72), this code hasn't changed for the past 2y and it has provably been working).

```
X-Frame-Options: SAMEORIGIN
Access-Control-Allow-Origin: *
```

**Comment by Miyayes** [comment]
@tmancey Repro'd this in production on release?

**Comment by tmancey** [comment]
I have a backup of the profile if this helps. Thanks

**Comment by emerick** [comment]
The server-side fix was confirmed in staging last week and has now been migrated to the reputation production server, so closing this issue out.
