### ISSUE TITLE
Issue in ZIP build: Remove firebaseapp and accounts.google from websites that can always use cookies by default

### ISSUE THREAD

**Issue by rany2** [brave/brave-browser#25647]
## Description 

Brave's zip build (i.e. https://github.com/brave/brave-browser/releases/download/v1.46.15/brave-browser-nightly-1.46.15-linux-amd64.zip) has firebaseapp and accounts.google.com from websites that can always use cookies by default. This doesn't happen in the .deb build of Brave.

![image](https://user-images.githubusercontent.com/71077389/192597232-37a57f6a-fcde-4c48-9434-c2ac6c21925a.png)

## Brave version (brave://version info)

Brave | 1.43.93 Chromium: 105.0.5195.127 (Official Build) unknown (64-bit)
-- | --
Revision | 912488396852bf658ab32465980c0b93a3c27a83-refs/branch-heads/5195@{#1109}
OS | Linux
JavaScript | V8 10.5.218.8
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Command Line | /app/brave/brave --disable-features=WebAssemblyTrapHandler,DesktopPWAsRunOnOsLogin --enable-crashpad --disable-domain-reliability --enable-dom-distiller --component-updater=url-source=https://go-updater.brave.com/extensions --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --variations-insecure-server-url=https://variations.brave.com/seed --disable-features=DesktopPWAsRunOnOsLogin,WebAssemblyTrapHandler --flag-switches-begin --flag-switches-end
Executable Path | /app/brave/brave
Profile Path | /home/user/.var/app/com.brave.Browser/config/BraveSoftware/Brave-Browser/Default

## Miscellaneous Information:

Original issue reported in https://github.com/flathub/com.brave.Browser/issues/193

**Comment by mherrmann** [comment]
I believe this is actually not related to ZIP/DEB but to setting "Allow Google log in buttons on third party sites". Please see https://github.com/brave/brave-browser/issues/11679#issuecomment-691249319.

**Comment by rany2** [comment]
Yes, and it appears that .deb actually has the same defaults. I took the original reporter for their word but apparently this isn't the case. Closing
