### ISSUE TITLE
Need to update Android VPN to fix local state usage

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#25648]
## Test plan
Basic functional test. This fixes a bug where the purchase token was not readable.

1. Fresh Android profile
2. Purchase VPN
3. Confirm you can connect to VPN and it works as expected (change server, etc)

## Description 
This is a regression caused by https://github.com/brave/brave-core/pull/15129

Basically, when desktop was moving over to local state, we didn't move the parts where Android is checking user prefs. We need to also check local state instead of `UserPrefs`. We'll get DCHECK errors / unexpected behavior as there are no longer profile values with these settings

When fixed, this would need an uplift to 1.45.x

**Comment by kjozwiak** [comment]
The above requires `1.45.87` or higher for `1.45.x` verification 👍
