### ISSUE TITLE
add a new setting on brave://settings for IPFS gateway address for NFTs

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#25646]
## Description 

We currently have one IPFS setting for one public gateway address. We have been advised to add one for nft's specifically. See post here about how we should support https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1664291898140589

also note comment about trying a few times before failing.
## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (64-bit) 
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | Linux

- Verified steps from [brave/brave-core#15434](https://github.com/brave/brave-core/pull/15434)
- Verified a new setting `IPFS public gateway address for NFT` is available under `brave://ipfs` and has `https://nftstorage.link` is added by default
- Verified able to update the NFT Gateway setting
- Verified the gateway field can't be set to be blank
- Verified tracing network with just wallet created, there is no entry for NFT gateway
- Verified adding an NFT and viewing it starts showing NFT gateway in network trace
- Verified able to still load IPFS pages via localnode or public gateway
- Verified able to still load IPFS page resolved via ENS (L1/L2)
- Verified able to still load an IPNS URI resolves using the public gateway/localnode

https://user-images.githubusercontent.com/17010094/199738488-36b5bd42-5bd4-4fcd-93b6-bfce6b18e5c8.mp4


------------------------
Verification passed on

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (64-bit) 
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | Windows 11 Version 22H2 (Build 22621.674)

- Verified steps from [brave/brave-core#15434](https://github.com/brave/brave-core/pull/15434)
- Verified a new setting `IPFS public gateway address for NFT` is available under `brave://ipfs` and has `https://nftstorage.link` is added by default
- Verified able to update the NFT Gateway setting
- Verified the gateway field can't be set to be blank
- Verified tracing network with just wallet created, there is no entry for NFT gateway
- Verified adding an NFT and viewing it starts showing NFT gateway in network trace
- Verified able to still load IPFS pages via localnode or public gateway
- Verified able to still load IPFS page resolved via ENS (L1/L2)
- Verified able to still load an IPNS URI resolves using the public gateway/localnode

https://user-images.githubusercontent.com/17010094/199734808-57957f18-6bee-45e4-96d2-010e43670358.mp4

------------------------
Verification passed on

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (arm64)
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#15434](https://github.com/brave/brave-core/pull/15434)
- Verified a new setting `IPFS public gateway address for NFT` is available under `brave://ipfs` and has `https://nftstorage.link` is added by default
- Verified able to update the NFT Gateway setting
- Verified the gateway field can't be set to be blank
- Verified tracing network with just wallet created, there is no entry for NFT gateway
- Verified adding an NFT and viewing it starts showing NFT gateway in network trace
- Verified able to still load IPFS pages via localnode or public gateway
- Verified able to still load IPFS page resolved via ENS (L1/L2)
- Verified able to still load an IPNS URI resolves using the public gateway/localnode

https://user-images.githubusercontent.com/17010094/199745043-da0403f3-75cb-4ab2-8da2-d0aaabd4b2bd.mp4
