### ISSUE TITLE
Allow users to send an optional diagnostic id in payloads to help debug features

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#25649]

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.49.110 Chromium: 110.0.5481.177 (Official Build) beta (64-bit) 
-- | --
Revision | f34f7ab2d4ca4ad498ef42aeba4f4eb2c1392d63-refs/branch-heads/5481@{#1239}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/16334

<details>



</details>

**Comment by btlechowski** [comment]
Verification passed on Brave v1.49.108 on Lenovo TB-8506FS (Android 11.0)

Verified test plan from https://github.com/brave/brave-core/pull/16334

#### Valid v4 GUID
<details>

Verified GUID is persisted after page reload
![image](https://user-images.githubusercontent.com/34715963/222214086-5008fe28-d788-4f7d-adc4-c23b2962db66.png)

Verified the GUID is passed when redeeming unblinded token
![image](https://user-images.githubusercontent.com/34715963/222215315-f2623101-8a7d-45f3-8ed7-71c3637db4b9.png)


Verified diangnosticid is persisted after browser restart
![image](https://user-images.githubusercontent.com/34715963/222213505-3e581035-48a4-4c8f-b6b5-99944ff837df.png)


</details>

#### Invalid v4 GUID
<details>

Verified the invalid GUID is saved:
![image](https://user-images.githubusercontent.com/34715963/222216417-10421d3a-b716-4313-bfdc-3ce16ebac975.png)


Verified the invalid GUID is not sent when redeeming unblinded token
![image](https://user-images.githubusercontent.com/34715963/222218447-9055654f-c224-44c1-8e80-85aa9996abcc.png)


</details>
