### ISSUE TITLE
Add P3A metric for Ethereum wallet provider

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#25659]
## Description 

Add P3A metric for the preferred Ethereum provider. The metric value will be determined when a page load has been completed, by evaluating the `window.ethereum` object.

What is the preferred Ethereum provider?
`Brave.Wallet.EthProvider`

0) None
1) Third-party wallet extension
2) Native Brave Wallet

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```
Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (64-bit)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | Windows 10 Version 21H2 (Build 19044.2130)

```

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.46.99`
