### ISSUE TITLE
Update Shields UI colors and labels

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#2565]
## Description
- Update Shields UI colors so UI has sufficient contrast for accessibility
- Fix grammar issues in the total blocked heading
- Fix focus indicators
- Change "Ads and trackers blocked" to "3rd-party trackers blocked"
- Change "Connections encrypted" to "Connections upgraded to HTTPS"
- Change scripts dropdown to a toggle and move it underneath "Connections upgraded to HTTPS"

## Designs 
These are the various states of the Shields panel:

![shields states](https://user-images.githubusercontent.com/2388823/52825381-5a8ae300-3071-11e9-9054-3db1d318bada.png)

The Shields panel shows the number of blocked items as a heading, which should change to accurately describe what is blocked:

![total blocked heading](https://user-images.githubusercontent.com/2388823/52825387-5eb70080-3071-11e9-8817-cb0c168b9f41.png)

When there are blocked items, users can click on the row to get a detail view of blocked items. 3rd-party trackers, Connections upgraded to HTTPS, and device recognition have a read-only detail view. 

3rd-party trackers detail view:

![3rd-party trackers breakdown](https://user-images.githubusercontent.com/2388823/52825392-62e31e00-3071-11e9-9d76-81210f4e8c1a.png)

Connections upgraded to HTTPS detail view:

![https upgrades breakdown](https://user-images.githubusercontent.com/2388823/52825397-670f3b80-3071-11e9-8eb5-627a34e687f8.png)

Device recognition detail view:

![shields device recognition breakdown](https://user-images.githubusercontent.com/2388823/52825400-6e364980-3071-11e9-910b-5ceeb97be690.png)

The scripts detail view includes functionality from the NoScript extension in Muon and extends it. Users can allow/block all sources of Javascript or select individual sources to allow/block:

![shields scripts breakdown](https://user-images.githubusercontent.com/2388823/52825407-75f5ee00-3071-11e9-95e7-d6635e6a0494.png)

Grab the SVG assets from this ZIP folder:
[icons.zip](https://github.com/brave/brave-browser/files/2789709/icons.zip)

For more CSS and plain text, check Abstract link: https://share.goabstract.com/68d70c4d-8c77-4588-9ee5-ce6418505c79

**Comment by karenkliu** [comment]
@cezaraugusto Thanks for updating shields in brave-ui; I took a look and here is my design feedback:

![color update design qa](https://user-images.githubusercontent.com/2388823/52158174-8efea800-264a-11e9-960a-c65e061756f0.png)

**Comment by karenkliu** [comment]
Hi @cezaraugusto, I took a look at your latest updates at https://brave-ui-959w0ii2u.now.sh

There are some issues with the total blocked heading, small spacing issues, an old interaction issue that resurfaced, and 1 small typography issue:

![color update design qa 3](https://user-images.githubusercontent.com/2388823/53122825-7af0ec80-350c-11e9-8740-ac94e752fa0e.png)

**Comment by karenkliu** [comment]
Hi @cezaraugusto, your latest updates at https://brave-ui-qzk8nw4np.now.sh looks good to go from the design side. 👍

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.64.60 Chromium: 74.0.3729.91 (Official Build) beta (64-bit)
-- | --
Revision | 03844ed83e02b8add3f4b9cb859a7108d55b2e4d-refs/branch-heads/3729@{#860}
OS | Windows 10 OS Build 17134.523

Used test plan from https://github.com/brave/brave-core/pull/1797
