### ISSUE TITLE
Add declared geo to `brave://rewards-internals`

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#25656]
## Description

In brave://rewards-internals add a row to display:

>Rewards country: `{{code}}`

If empty, show "not set".

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.46.80 Chromium: 107.0.5304.68 (Official Build) beta (x86_64)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | macOS Version 12.6.1 (Build 21G217)
```

<details>
<summary>Clean Profile - PASSED</summary>

Verified test plan from https://github.com/brave/brave-core/pull/15439.

1. Clean profile
2. Enable Rewards and declare geo
3. Visit brave://rewards-internals
4. Verify that declared geo matches what's shown on the internals page

Step 2 | Step 4
---- | ----
<img width="436" alt="2" src="https://user-images.githubusercontent.com/28145373/198071883-6fc31869-7e99-4b90-8807-ff958af56c48.png"> | <img width="1187" alt="4" src="https://user-images.githubusercontent.com/28145373/198071888-dd385cdb-2079-4efb-a42f-2697163f137f.png">

</details>

<details>
<summary>Upgrade Profile - InProgress</summary>

1. Clean profile 1.45.x, relaunch and pull griffin seed
2. Enable Rewards 
3. Close and "upgrade" to 1.46.x (rename profile to Beta)
4. Launch and do not open the panel to set your country
5. Visit brave://rewards-internals
6. Verify that declared geo says "not set" per description

</details>

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Samsung Galaxy  version 12` running `Bravemonoarm64.apk_1.46.114`

<details>
<summary>Clean Profile - PASSED</summary>

Verified test plan from https://github.com/brave/brave-core/pull/15439.

1. Clean profile
2. Enable Rewards and declare geo
3. Visit brave://rewards-internals
4. Verify that declared geo matches what's shown on the internals page

Step 2 | Step 4
---- | ----
![Screenshot_20221117-150256_Brave - Beta](https://user-images.githubusercontent.com/38657976/202412112-513405a3-2d06-4526-bf05-81c23c66ccb5.jpg) | ![Screenshot_20221117-150732_Brave - Beta](https://user-images.githubusercontent.com/38657976/202412158-8285c32b-f01d-4b95-90f2-dfd262b13e7e.jpg)



</details>

<details>
<summary>Upgrade Profile - PASSED</summary>

1. Clean profile 1.45.x, relaunch and pull griffin seed
2. Enable Rewards 
3. Close and "upgrade" to 1.46.x (rename profile to Beta)
4. Launch and do not open the panel to set your country
5. Visit brave://rewards-internals
6. Verify that declared geo says "not set" per description

Step 3 | Step 6
---- | ----


</details>
