### ISSUE TITLE
Some URLs are not syncing properly with all the devices in sync chain

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-browser#25650]
## Description 
Not all the **TYPED** History is being synced between every device in sync chain. 

The TYPED history is working with intermittent problems and which url syncs when is not consistent at all. It almost feels like there is window like period it syncs and it stops after.

More than one occasion we witnessed a typed url from a device might appear in one device but not in another. And in addition when a typed url is sent from a device, there is an increase in number `Typed Urls` sometimes this url being synced from other device is not shown inside `Sync Node Browser` and does not appear in History at all. 

## Steps to Reproduce

   1. Add multiple devices to Sync Chain including Desktop / Android / iOS
   2. Enable History Sync from settings for all devices
   3. Add typed urls from different devices one by one and observe which urls are being synced with which device

## Actual result:

Not every url is synced, sometimes url is not synced with any device, sometimes it synced partially with some of the devices.

For instance `brave.com` is typed on Android device and it is received on iOS device however it is not synced on Desktop.

Or `reddit.com` is typed on desktop, received by android but not iOS or `reddit.com/r/news` is typed on iOS which is received by Android but not on desktop. And some urls typed are not received by either of devices.

![Screen Shot 2022-09-27 at 12 06 45 PM](https://user-images.githubusercontent.com/6643505/192613287-08e77dd5-a555-41d7-b3e6-453610fc55b4.png)

Also on similar note  as mentioned above what is observed on desktop side inside` Sync Internals` is sometimes  when a typed url is entered from a device, the increase in number `Typed Urls` can be observed but this url being synced from other device is not shown inside `Sync Node Browser` and does not appear in History at all.

![internal1](https://user-images.githubusercontent.com/6643505/192614021-70c70cd3-a744-418b-b45a-057f65fe56d3.png)

## Expected result:

The typed urls should sync across all the devices properly.

## Reproduces how often: 

The issue is 100 percent reproducible as long as more urls are being typed eventually this will be observed. Which means it is not depending on what urls is typed on which device.

## Desktop Brave version:

Latest Nightly on MacOS / Windows

## Android Device details:
   - Install type (ARM, x86): Any
   - Device type (Phone, Tablet, Phablet): Any
   - Android version: Latest Google Play Store version

## Version/Channel Information:

N/A

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? **NO**. It is working properly on Chrome (tested using Chrome on desktop and mobile.

## Miscellaneous Information:

The behaviour is tested on Chrome and it is working as expected. cc @Brandon-T @AlexeyBarabash

**Comment by AlexeyBarabash** [comment]
I have prepared the PR https://github.com/brave/brave-core/pull/16478 to help understand what is happening with synced history entries. For now I don't see inconsistency. TYPED_URL page transition is synced everywhere.

**Comment by AlexeyBarabash** [comment]
Also the PR https://github.com/brave/brave-core/pull/16705 was merged. Since [v1.50.6](https://github.com/brave/brave-core/releases/tag/v1.50.6) this option is available under the brave://flags `Send All History to Brave Sync`. With this option enabled all the history visits except RELOAD are sent to sync.
