### ISSUE TITLE
Remove unneeded tooltips from network selectors

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#25655]
## Description 

Recent UI changes have allowed for the full chain name to be displayed in the wallet UI. These networks names used to have tooltips to show the full name. Removing the tooltips since the full name now is always displayed.

## Steps to Reproduce

   1. Open wallet panel
   2. Switch to a network with a large name, such as "Solana Mainnet Beta"

## Actual result:

The tooltip is still shown when hovering the network selector.

## Expected result:
The tooltip is not shown when hovering the network selector.

## Reproduces how often: 

Easy

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (64-bit) 
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | Linux

- Verified steps from [brave/brave-core#15246](https://github.com/brave/brave-core/pull/15246)
- Verified unnecessary tooltips are removed from network selector dropdown on both Widget and panel

https://user-images.githubusercontent.com/17010094/199180652-a3c29156-27f2-45ea-94a6-fe1af2f16ba9.mp4

------------------------
Verification passed on

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (64-bit) 
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | Windows 11 Version 22H2 (Build 22621.674)

- Verified steps from [brave/brave-core#15246](https://github.com/brave/brave-core/pull/15246)
- Verified unnecessary tooltips are removed from network selector dropdown on both Widget and panel

https://user-images.githubusercontent.com/17010094/199180855-e19a17b9-8c73-470b-9431-8b2178f6dbd8.mp4

------------------------
Verification passed on

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (arm64)
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#15246](https://github.com/brave/brave-core/pull/15246)
- Verified unnecessary tooltips are removed from network selector dropdown on both Widget and panel

https://user-images.githubusercontent.com/17010094/199180458-8ffabe5d-aecd-4e85-b230-7c979def1cc4.mov
