### ISSUE TITLE
Remove desktop support for Ropsten, Rinkeby, and Kovan test networks and add Sepolia

### ISSUE THREAD

**Issue by nvonpentz** [brave/brave-browser#25654]
as they are being deprecated by our RPC provider October 5th.

**Comment by nvonpentz** [comment]
I will also add Sepolia in this change because some tests depend there being two different Ethereum testnets.  This way I can swap those with Sepolia and Goerli without having to modify the core test logic.

**Comment by kjozwiak** [comment]
The above will require `1.44.109` or higher for `1.44.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.44.109 Chromium: 106.0.5249.103 (Official Build) (64-bit) 
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | Linux

- Verified steps from [brave/brave-core#15266](https://github.com/brave/brave-core/pull/15266)
- Verified deprecated networks are removed after update
- Verified `Sepolia` & `Goreli` are the only two ETH test networks available after upgrade
- Verified `Sepolia` is added as default for new wallets and fetches balance

https://user-images.githubusercontent.com/17010094/194558471-62226748-20af-426c-a590-89453007306a.mp4

------------------------
Verification passed on

Brave | 1.44.109 Chromium: 106.0.5249.103 (Official Build) (64-bit) 
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | Windows 11 Version 21H2 (Build 22000.978)

- Verified steps from [brave/brave-core#15266](https://github.com/brave/brave-core/pull/15266)
- Verified deprecated networks are removed after update
- Verified `Sepolia` & `Goreli` are the only two ETH test networks available after upgrade
- Verified `Sepolia` is added as default for new wallets and fetches balance

https://user-images.githubusercontent.com/17010094/194555854-2766c87b-6007-4ffe-9c03-2032dac8f272.mp4

------------------------
Verification passed on

Brave | 1.44.109 Chromium: 106.0.5249.103 (Official Build) (arm64)
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [brave/brave-core#15266](https://github.com/brave/brave-core/pull/15266)
- Verified deprecated networks are removed after update
- Verified `Sepolia` & `Goreli` are the only two ETH test networks available after upgrade
- Verified `Sepolia` is added as default for new wallets and fetches balance

https://user-images.githubusercontent.com/17010094/194562801-019f5e2d-102a-49c6-94a9-abca6620115c.mov

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.44.109 x64 build

- Verified steps from [brave/brave-core#15266](https://github.com/brave/brave-core/pull/15266)
- Verified deprecated networks are removed after update
- Verified `Sepolia` & `Goreli` are the only two ETH test networks available after upgrade
- Verified `Sepolia` is added as default for new wallets and fetches balance

https://user-images.githubusercontent.com/17010094/194563399-1ff6c28b-7968-4fb3-93c5-7fe147e96b59.mp4
