### ISSUE TITLE
Add Jupiter fees only for selected output mints

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#25657]
In order for Brave to receive fees on Solana swaps, we need to have associated token accounts for all possible taker assets, created in advance. This is impractical to maintain, so we should charge fees only for popularly traded pairs for which we create ATA accounts in advance.

Phantom is doing the same thing, but the reason was not clear to us until now. This is also what the Jupiter team has recommended.

Here's the list of tokens we want to charge fees for initially:
- Wrapped SOL
- USDC
- USDT
- Wrapped Ether (Wormhole)
- Wrapped Ether (Sollet)
- Wrapped Bitcoin (Wormhole)
- Wrapped Bitcoin (Sollet)
- Lido Staked SOL
- Marinade Staked SOL
- DAI (Wormhole)

The above list can always be changed in future to include or exclude tokens.

cc: @HEagle18 

### Test plan

As part of the QA, please perform the following swaps on Solana. All the transactions should be successful. The table below indicates whether or not to expect collection of fees by Brave. You can verify this information after the swap [here](https://explorer.solana.com/address/3NUW8hWoCnLgJwWCVnwdFo2Dsz8bKwLac9A3VgS2jLUQ/tokens) under "Token history".

|Swap|Fees|
:-:|:-:
|**`SOL -> USDT`**| ✅ |
|**`USDT -> SOL`**| ✅ |
|**`SHDW -> SOL`**|✅ |
|**`SHDW -> USDT`**| ✅ |
|**`SOL -> SHDW`**| ❌|
|**`USDT -> SHDW`**| ❌|

**Comment by kjozwiak** [comment]
The above requires `1.44.108` or higher for `1.44.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.44.108 Chromium: 106.0.5249.103 (Official Build) (64-bit)
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | Windows 11 Version 22H2 (Build 22623.730)

- Verified Swap fee is only collected for selected tokens

Swap | Transaction | Fees
-- | -- | --
`SOL -> USDT` | [Tx Hash](https://explorer.solana.com/tx/5GpSoSFSUiCR8hCZ4CPYCvTcXs72Wx3sgcEJSmY26Qyg99aMFxG3TFcYhFP9xAJBVJJjis3rYsD9Mztta989LKUB)| ![image](https://user-images.githubusercontent.com/17010094/194341872-f3e9fca8-5103-4e68-8b7b-b208ffb79c1e.png)
`USDT -> SOL` | [Tx Hash](https://explorer.solana.com/tx/2GHodnVzni1sThq1M1ypMhTPVX5JEyT5KdfUv9NZR3W2ko39gVWxysGuZAZbXsn1hxvfCckYqZx47dqPWSG5azA)| ![image](https://user-images.githubusercontent.com/17010094/194342537-152b5379-f0a5-42e4-81a6-80f87b21bc1d.png)
`SHDW -> SOL` | [Tx Hash](https://explorer.solana.com/tx/4mzocWyCdf31KiyQFuEFmahYTrtzynRC1NRCn1aMEG3UyxThvbzAveHsgyQnKftb9HTFB6qdDtAsnkMPXqhHozDY)| ![image](https://user-images.githubusercontent.com/17010094/194344017-eec9fb37-939f-467a-9c01-ae55e4a86297.png)
`SHDW -> USDC` | [Tx Hash](https://explorer.solana.com/tx/3sv2hTtryTCmcZ4Ro1RT65ignwt3hL9j9PgFikFDKhAVtT53LW8sVmVhk1KYkgYCvUrshDNBK3nKaWsXH8FMxBZG)| ![image](https://user-images.githubusercontent.com/17010094/194344800-38f1fc58-9c3a-43b8-a96f-271d80747bda.png)
`SOL -> SHDW` | [Tx Hash]() | ![image](https://user-images.githubusercontent.com/17010094/194345686-65df804c-20d0-41f8-9a87-a92861786050.png)
`USDC -> SHDW` | [Tx Hash](https://explorer.solana.com/tx/DEjxaXM5Xr61ntXQW3i17URquBbmpbV2qqu5KXN155d2F3JdXkpMT4p3FnAzMpmDtTZVQ6zJbtPFJBGFbWDfGos)| ![image](https://user-images.githubusercontent.com/17010094/194345301-43a5a52b-9d39-4580-90c5-5beb9347b2d7.png)
