### ISSUE TITLE
New Tab Page uses 'chrome' links for History, Bookmarks, and Preferences

### ISSUE THREAD

**Issue by bradleyrichter** [brave/brave-browser#2566]
![image](https://user-images.githubusercontent.com/13509546/49978042-81a42780-fefd-11e8-8f5a-b84faac906ed.png)

**Comment by srirambv** [comment]
probably #1616 will fix this as well

**Comment by fmarier** [comment]
Sadly, my fix for #1616 (https://github.com/brave/brave-core/pull/1354) won't help with this issue.

**Comment by bsclifton** [comment]
Reverted with https://github.com/brave/brave-core/pull/2188 because there have been unit test issues. When brought up on Slack, @bridiver noticed some issues too. @simonhong can you re-open the original PR and/or hit up @bridiver? Thanks 😄 

Removing milestone as code has been reverted

**Comment by rebron** [comment]
+1 for @pes10k for this one via #13467

**Comment by bsclifton** [comment]
+1 from @JimB-Dev via https://github.com/brave/brave-browser/issues/17156

**Comment by rebron** [comment]
+1 from @uraashif https://github.com/brave/brave-browser/issues/25467

**Comment by pes10k** [comment]
@bridiver , can we copy what Edge does here then?  I believe edge completely replaces chrome:// -> edge:// IIRC

**Comment by bridiver** [comment]
> @bridiver , can we copy what Edge does here then? I believe edge completely replaces chrome:// -> edge:// IIRC

I have no idea what they do to accomplish that. They might do a search/replace on the entire codebase which isn't practical for us atm

**Comment by pes10k** [comment]
not being totally serious but, couldn't we just `#define chrome: brave:` 😅

**Comment by bridiver** [comment]
> not being totally serious but, couldn't we just `#define chrome: brave:` 😅

Haha, well unfortunately that would not fix any of them because the pre-processor doesn't modify strings and you can't have a colon in a define

**Comment by stephendonner** [comment]
## Verified `PASSED` using 





Brave | 1.47.108 Chromium: 108.0.5359.71 (Official Build) beta (x86_64)
-- | --
Revision | 1e0e3868ee06e91ad636a874420e3ca3ae3756ac-refs/branch-heads/5359@{#1016}
OS | macOS Version 13.1 (Build 22C5059b)

### Steps:
1. installed `1.47.108`
2. launched Brave
3. loaded each of the following pages
4. hovered over an internal link

#### Confirmed former `chrome://` links now point to `brave://` internally

`brave://about` | `release`
----------------|---------
<img width="1312" alt="Screenshot 2022-12-02 at 11 04 01 AM" src="https://user-images.githubusercontent.com/387249/205367327-48a11112-0ee0-4816-82e0-409ab921e683.png"> | <img width="1566" alt="Screenshot 2022-12-02 at 11 07 18 AM" src="https://user-images.githubusercontent.com/387249/205367496-9c582025-b5d0-4afc-a53e-45677450fbd2.png">

`new-tab page` | `release`
-----------------|---------
<img width="1312" alt="Screenshot 2022-12-02 at 10 58 17 AM" src="https://user-images.githubusercontent.com/387249/205367662-f20af3a0-4aa6-4958-a12a-7d11fd2940fc.png"> | <img width="1566" alt="Screenshot 2022-12-02 at 11 08 40 AM" src="https://user-images.githubusercontent.com/387249/205367664-a442c11a-a80d-4246-aa96-526e18c40c39.png">

`brave://settings/ipfs` | `release`
----------------------|----------
<img width="1566" alt="Screenshot 2022-12-02 at 11 09 54 AM" src="https://user-images.githubusercontent.com/387249/205368049-a38c1c43-56b7-4ef0-9960-ee91aa7608e1.png"> | <img width="1312" alt="Screenshot 2022-12-02 at 11 11 20 AM" src="https://user-images.githubusercontent.com/387249/205368052-74506d55-278e-48c3-9374-2989ba930555.png">
