### ISSUE TITLE
Market tab in Wallet is showing the wrong base currency

### ISSUE THREAD

**Issue by urbenlegend** [brave/brave-browser#25668]
## Description 

The Market tab in Wallet always shows USD. It does not follow the default base currency set in `brave://settings/wallet`.

## Steps to Reproduce

   1. Go to `brave://settings/wallet` and change the default base currency to something other than USD
   2. Go to `brave://wallet/crypto/market`
   3. Notice that the prices are still listed in USD

## Actual result:

Market tab shows prices in USD even when you set the default base currency setting to something other than USD

## Expected result:
Market tab should show prices in the base currency that the user has set

## Reproduces how often: 

Every time

## Brave version (brave://version info)

1.44.101 Chromium: 106.0.5249.65 (Official Build) (64-bit) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by jamesmudgett** [comment]
@muliswilliam

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (64-bit) 
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | Linux

- Verified steps from issue description & [brave/brave-core#15402](https://github.com/brave/brave-core/pull/15402)
- Verified Market tab uses the selected based currency 
- Verified token details page from Market tab still shows the currently set default currency 

https://user-images.githubusercontent.com/17010094/199003790-adc86cd9-c0f0-4ced-8357-22873c51d68b.mp4


------------------------
Verification passed on

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (64-bit) 
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | Windows 11 Version 22H2 (Build 22621.674)

- Verified steps from issue description & [brave/brave-core#15402](https://github.com/brave/brave-core/pull/15402)
- Verified Market tab uses the selected based currency 
- Verified token details page from Market tab still shows the currently set default currency 

https://user-images.githubusercontent.com/17010094/199003570-94d19239-3fe5-4049-a475-3e2564ba6cd9.mp4

------------------------
Verification passed on

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (arm64)
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from issue description & [brave/brave-core#15402](https://github.com/brave/brave-core/pull/15402)
- Verified Market tab uses the selected based currency 
- Verified token details page from Market tab still shows the currently set default currency 

https://user-images.githubusercontent.com/17010094/199003970-a42ac2e5-f6e0-4ba0-ba93-cfa608e74c5b.mov
