### ISSUE TITLE
Disable tab cycling on linux when "vertical tabs" feature is enabled.

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#25667]
There's a feature called "tab cycling" on linux, which switches active tab on wheel event. This doesn't go well with vertical tabs as vertical tabs are in scroll view. We should disable this.

Note that upstream folks also disable the feature when scrollable tabstrip is enabled.

**Comment by sangwoo108** [comment]
cc @antonok-edm

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.46.117 Chromium: 107.0.5304.110 (Official Build) beta (64-bit)
-- | --
Revision | 2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}
OS | Ubuntu 18.04 LTS


Verified unable to scroll vertical tabs 

Steps:
1. Enabled vertical tabs
2. Verified unable to scroll vertical tabs (hover over tabs and use mouse wheel)


![image](https://user-images.githubusercontent.com/34715963/203077795-a7657ec4-d4d4-483b-a0fb-4ca9ae55742e.png)
![image](https://user-images.githubusercontent.com/34715963/203078695-399c12fe-0f65-4b21-a06b-6f8ef826e168.png)

Verified able to scroll horizontal tabs 
![25667](https://user-images.githubusercontent.com/34715963/203080825-f47af6bc-8e56-4576-81b0-de4057dcbefc.gif)
