### ISSUE TITLE
Sync needs a 'waiter' message when reset/confirm/remove

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#2567]
## Description 

Sync needs a 'waiter' message when reset/confirm/remove

## Steps to Reproduce

   1. Add a device to sync chain
   2. Try removing it by clicking on the `X` button in the devices list
   3. Click on `Remove` in the popup modal, there is no UI indication that a request is sent. This could lead to user clicking the button unnecessarily 

## Actual result:

https://youtu.be/itrU8cV_ce4

## Expected result:
Should have a waiter message similar to the one implemented in rewards(#1099)

## Reproduces how often: 

Easy

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

May be duplicate of #2227  @AlexeyBarabash to confirm and close this if its a dupe

**Comment by LaurenWags** [comment]
Reproduced on 

Brave | 0.59.14 Chromium: 72.0.3626.28 (Official Build) beta(64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Mac OS X

**Comment by btlechowski** [comment]
Reproduced on

Brave | 0.59.14 Chromium: 72.0.3626.28 (Official Build) beta(64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Windows 7
