### ISSUE TITLE
Remove `Ask when to save files` option

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#25687]
## Description 
Code that handles this option was removed in the upstream in `cr105` https://github.com/chromium/chromium/commit/2435d853521676edd919e3e2f4b8cb6d50cbe7ca
So it is redundant at the moment.

## Steps to reproduce 

   1. Goto `Downloads` settings
   2. You see `Ask when to save files` option

## Actual result 
Option is there

## Expected result
No option

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Blocked on https://github.com/brave/brave-browser/issues/26475

**Comment by kjozwiak** [comment]
Removing `QA/Blocked` as https://github.com/brave/brave-browser/issues/26475 was uplifted into `1.46.x` via https://github.com/brave/brave-core/pull/16141 and should be ready to verify using `1.46.131` or higher as per https://github.com/brave/brave-browser/issues/26475#issuecomment-1331398244.

**Comment by Uni-verse** [comment]
Verified per https://github.com/brave/brave-browser/issues/26475#issuecomment-1333073321 on `Samsung Galaxy S21` & `Samsung Galaxy Tab S7` using version(s):

```
Brave	1.46.131 Chromium: 108.0.5359.71 (Official Build) (64-bit) 
Revision	1e0e3868ee06e91ad636a874420e3ca3ae3756ac-refs/branch-heads/5359@{#1016}
OS	Android 12; Build/SP1A.210812.016
```
