### ISSUE TITLE
Add support for `channels` from the new Brave News API. These replace `categoryName`.

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#25688]
For now, this should be behind the `BraveNewsV2` flag. It is a requirement to release the new UI.

**Comment by stephendonner** [comment]
@brave/qa-team hold off on testing this (and other feed/channel-related issues) until after the fixes for issues in https://bravesoftware.slack.com/archives/CU56GUJ1H/p1666975874847419 have been pushed to production.

**Comment by stephendonner** [comment]
Removing `QA/Blocked`; I believe everything needed for testing has landed in the client and/or pushed to prod 👍

**Comment by stephendonner** [comment]
> Removing `QA/Blocked`; I believe everything needed for testing has landed in the client and/or pushed to prod 👍

Though it would be good to hold off until https://github.com/brave/brave-core/pull/15808 is merged, I now realize (not technically blocked, but we'd have to re-do testing, since there are channel-related tweaks -- including the ability to be translatable -- in there).

**Comment by stephendonner** [comment]
## Verification `PASSED` using 

Brave | 1.46.100 Chromium: 107.0.5304.91 (Official Build) dev (x86_64)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | macOS Version 11.7.1 (Build 20G918)

### Steps:

1. installed `1.46.100`
2. launched Brave
3. clicked `Skip welcome tour`
4. scrolled down on the new-tab page
5. clicked on `Show Brave News`
6. confirmed the usual mix of news, sports, entertainment, health, etc. categories/feeds
7. loaded `brave://flags`
8. enabled the `brave://flags/#brave-news-v2` flag
9. closed Brave
10. relaunched Brave
11. with the default `Top Sources` category followed, scrolled Brave News
12. confirmed `Gamespot` articles
13. unfollowed `Top Sources`
14. followed `Entertainment`, reloaded
15. scrolled Brave News
16. confirmed `Gamespot` articles, reloaded
17. unfollowed `Entertainment`
18. followed `Gaming`, reloaded
19. scrolled Brave News

#### Confirmed the `Gamespot` feed was present in the `Entertainment`, `Gaming`, and `Top Sources` categories, with articles, without directly following it.

#### Entertainment
`Customize` dialog | `Gamespot` in feed
--------------------|--------------------
<img width="1312" alt="Screen Shot 2022-11-08 at 12 26 03 PM" src="https://user-images.githubusercontent.com/387249/200669897-28ee4ef9-b459-412f-beec-d3b149ee4f67.png"> | <img width="1312" alt="Screen Shot 2022-11-08 at 12 28 12 PM" src="https://user-images.githubusercontent.com/387249/200669936-8f8cd8cb-5fa7-4aac-925d-19591f4d01c0.png">

#### Gaming

`Customize` dialog | `Gamespot` in feed
--------------------|--------------------
<img width="1312" alt="Screen Shot 2022-11-08 at 12 37 43 PM" src="https://user-images.githubusercontent.com/387249/200670228-b4ad1b7a-1f55-49eb-b12b-6b81656daed8.png"> | <img width="1312" alt="Screen Shot 2022-11-08 at 12 39 19 PM" src="https://user-images.githubusercontent.com/387249/200670532-b0200074-b844-405a-8d67-1f44a7ce7c3f.png">



#### Top Sources

`Customize` dialog | `Gamespot` in feed
--------------------|--------------------
<img width="1312" alt="Screen Shot 2022-11-08 at 12 25 42 PM" src="https://user-images.githubusercontent.com/387249/200669404-14c66331-bbda-4463-9b58-b6786b88c248.png"> | <img width="1312" alt="Screen Shot 2022-11-08 at 12 27 15 PM" src="https://user-images.githubusercontent.com/387249/200669416-0057092d-288a-4ebf-b717-b6976c235626.png">
