### ISSUE TITLE
Fiat currency selection not working on Fund Wallet screen

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#25686]
## Description 

The fiat currency selector that is shown on the fund wallet screen does not show fiat options when clicked

## Steps to Reproduce

   1. Create a wallet
   2. navigate to brave://wallet/crypto/fund-wallet
   3. click the fiat symbol "$"

## Actual result:

Nothing happens after clicking the fiat symbol

## Expected result:
A searchable list of fiat currencies should appear

## Reproduces how often: 

Easy

## Brave version (brave://version info)

1.44.101 Chromium: 106.0.5249.65 (Official Build) (arm64) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (64-bit) 
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | Linux

- Verified steps from [brave/brave-core#15265](https://github.com/brave/brave-core/pull/15265)
- Verified currency selection dropdown is clickable
- Verified able to search for availbale Fiat options
- Verified changing Fiat currency automatically updates the token value as well

https://user-images.githubusercontent.com/17010094/199179304-f8bfc235-9fa1-41dc-953a-702ab8413cd3.mp4

------------------------
Verification passed on

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (64-bit) 
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | Windows 11 Version 22H2 (Build 22621.674)

- Verified steps from [brave/brave-core#15265](https://github.com/brave/brave-core/pull/15265)
- Verified currency selection dropdown is clickable
- Verified able to search for availbale Fiat options
- Verified changing Fiat currency automatically updates the token value as well

https://user-images.githubusercontent.com/17010094/199179616-481d4a11-ba62-46b6-92f5-afec96df2c4f.mp4

------------------------
Verification passed on

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (arm64)
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#15265](https://github.com/brave/brave-core/pull/15265)
- Verified currency selection dropdown is clickable
- Verified able to search for availbale Fiat options
- Verified changing Fiat currency automatically updates the token value as well

https://user-images.githubusercontent.com/17010094/199179831-8230acd4-e1da-4741-a9bc-982201720ae4.mov
