### ISSUE TITLE
Enable ENS L2 by default on desktop

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#25684]
ETH address resolution in wallet UI: https://github.com/brave/brave-core/pull/14447, https://github.com/brave/brave-core/pull/15010
URL bar resolution: https://github.com/brave/brave-core/pull/14945, https://github.com/brave/brave-core/pull/15151
Security & privacy review done in https://github.com/brave/security/issues/966.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (64-bit)
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | Linux

- Verified ENS L2 resolution is enabled by default
- Verified setting is only shown when ENS resolution setting is set to `Ethereum`

----------------
Verification passed on 

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (64-bit)
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | Windows 11 Version 22H2 (Build 22621.674)

- Verified ENS L2 resolution is enabled by default
- Verified setting is only shown when ENS resolution setting is set to `Ethereum`

----------------
Verification passed on 

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (arm64)
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | macOS Version 12.6 (Build 21G115)

- Verified ENS L2 resolution is enabled by default
- Verified setting is only shown when ENS resolution setting is set to `Ethereum`
