### ISSUE TITLE
Use backend instruction data decoder rather than solana-web3 lib in desktop frontend

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#25681]
https://github.com/brave/brave-core/pull/15142/ implement a backend decoder with support of System and Token program.
We should revise our frontend to use this instead of having deps of solana-web3 in brave_wallet_ui component.
Note that currently our frontend uses solana-web3 and supports System, Staking, and Vote program, by switching to the backend decoder result, we will not have Staking and Vote program support for now but will have Token program support added.
cc @Douglashdaniel

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.50.93 Chromium: 111.0.5563.64 (Official Build) beta  (64-bit) 
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Linux

- Verified steps from [brave/brave-core#17128](https://github.com/brave/brave-core/pull/17128)
- Verified `Transaction parameters` (addresses and amount) are shown for `Sign and Send Transaction` System Program
- Verified `Transaction parameters` (addresses and amount) are shown for `Sign and Send SPL Transaction` Token Program
- Verified `Raw Transaction` info is shown for `non-decodable instructions` (program id and data)

https://user-images.githubusercontent.com/17010094/225851072-6aaf1280-fb97-4a31-b0e7-44b51277fd43.mp4

---------------------

Verification passed on 

Brave | 1.50.93 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from [brave/brave-core#17128](https://github.com/brave/brave-core/pull/17128)
- Verified `Transaction parameters` (addresses and amount) are shown for `Sign and Send Transaction` System Program
- Verified `Transaction parameters` (addresses and amount) are shown for `Sign and Send SPL Transaction` Token Program
- Verified `Raw Transaction` info is shown for `non-decodable instructions` (program id and data)

https://user-images.githubusercontent.com/17010094/225851496-f0870f8e-32ed-4d40-b3bf-f00acc11cbb6.mp4

---------------------

Verification passed on 

Brave | 1.50.93 Chromium: 111.0.5563.64 (Official Build) beta (arm64)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#17128](https://github.com/brave/brave-core/pull/17128)
- Verified `Transaction parameters` (addresses and amount) are shown for `Sign and Send Transaction` System Program
- Verified `Transaction parameters` (addresses and amount) are shown for `Sign and Send SPL Transaction` Token Program
- Verified `Raw Transaction` info is shown for `non-decodable instructions` (program id and data)

https://user-images.githubusercontent.com/17010094/225852000-ddcbaef2-d7ce-43ab-8503-e7f2ad8b59fb.mov
