### ISSUE TITLE
Hide side panel option from settings appearance page

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#25689]
## Steps to Reproduce

   1. Load brave://settings/appearance
   2. 
   3. 

## Actual result:

![image](https://user-images.githubusercontent.com/6786187/192914209-f8b133f3-5d0d-4667-b821-ebc6d822138d.png)

## Expected result:
Not shown as we can't show sidebar on left side

## Reproduces how often: 

Easy

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.44.104` or higher for `1.44.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.44.105 Chromium: 106.0.5249.91 (Official Build) (x86_64)
-- | --
Revision | fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}
OS | macOS Version 12.6 (Build 21G115)
```
