### ISSUE TITLE
"connected" creators still show as verified after upgrade - follow up to 25085

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#25699]
## Description 

Found while testing #25085

In the clean profile case for #25085, all works as expected.

For upgrades, "connected" creators still show as verified on brave://rewards page (AC list, tips list, monthly tips, statement, etc) after upgrade. As such, if an auto contribution and/or monthly tip contribution occurs post upgrade and the "connected" creator still has the verified checkmark, the contributions (AC and monthly tip) go through.

## Steps to Reproduce

1. Install release version (1.44.x) w/ staging env and reconcile interval
2. Close and relaunch (pull griffin seed)
3. Enable Rewards, claim UGP grant
4. Populate AC list with a mix of creators, including at least one "connected" creator
5. Do a one time tip for a "connected" creator
6. Set up a monthly tip for "connected" creator
7. Close Brave
8. Rename profile for Nightly
9. Launch with Nightly version which contains this fix
10. Look at brave://rewards page --> "connected" creator still displays the verified checkmark in all places (AC, tips, monthly tips, statement, etc)
11. Wait for reconcile interval to occur so AC & monthly tips are contributed
12. AC and monthly tips are completed --> however "connected" creator still gets the AC and monthly tip set up prior to upgrade

## Actual result:

after upgrade, "connected" creators still have verified checkmark, so contributions go through 

Step 4 | Step 5 | Step 6 | Step 10 | Step 12 | Step 12 | Step 12
---- | ---- | ---- | ---- | ---- | ---- | ----
<img width="658" alt="4" src="https://user-images.githubusercontent.com/28145373/193037804-7811a9b9-7dbb-4c77-8577-c0f5c7af6297.png"> | <img width="657" alt="5" src="https://user-images.githubusercontent.com/28145373/193037805-ca78411d-2367-45b5-bd41-41fde9303e7f.png"> | <img width="653" alt="6" src="https://user-images.githubusercontent.com/28145373/193037806-17761da1-ec7f-4fc0-ac03-56fc00d9507f.png"> | <img width="520" alt="10" src="https://user-images.githubusercontent.com/28145373/193039092-7aa402c6-ecf1-4899-8757-c6ed089e3251.png"> | <img width="1187" alt="12a" src="https://user-images.githubusercontent.com/28145373/193042517-8af34fe3-7ad7-489c-8046-0702978fcac4.png"> | <img width="963" alt="12b" src="https://user-images.githubusercontent.com/28145373/193042518-dc1a8e10-0d54-4ab6-ba16-0dc1070e3ed9.png"> | <img width="946" alt="12c" src="https://user-images.githubusercontent.com/28145373/193042519-4528c233-d9f2-4223-91bc-7f3a923993af.png">

## Expected result:

post upgrade "connected" creators do not have verified checkmark, so previously set up contributions should not go through

## Reproduces how often: 

easily

## Desktop Brave version:

```
Brave | 1.46.18 Chromium: 106.0.5249.65 (Official Build) nightly (x86_64)
-- | --
Revision | 3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}
OS | macOS Version 12.6 (Build 21G115)
```

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? 1.46.x yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @zenparsing @Miyayes 

additional discussion: https://bravesoftware.slack.com/archives/CHGKGMHDJ/p1663856354685349

**Comment by kjozwiak** [comment]
The above requires `1.45.87` or higher for `1.45.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
Brave | 1.45.87 Chromium: 106.0.5249.91 (Official Build) beta (64-bit)
-- | --
Revision | fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}
OS | Windows 10 Version 21H2 (Build 19044.2006)

```
- Verifcation is covered in the "Upgrade Profile Checks" case https://github.com/brave/brave-browser/issues/25085#issuecomment-1269286361

**Comment by LaurenWags** [comment]
Verification in progress on Google Pixel 3 XL with Android 12 running 1.45.100
