### ISSUE TITLE
Crash when enabling the vpn due to p3a

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#25704]
## Description 
Turning on the vpn from main menu `Brave VPN` resulting in crash because of https://github.com/brave/brave-core/blob/e07ab61c650017a88f6dc6bef984a70b636cdc84/android/java/org/chromium/chrome/browser/app/BraveActivity.java#L629

## Steps to reproduce 

   1. Buy vpn subscription
   2. create profile with `Install profile` button
   3. Turn off the vpn from main menu `Brave VPN` item
   4. turn on vpn from the same menu

## Actual result 
Crashing the application

## Expected result
Shouldn't crash the app when trying to enable the vpn

## Issue reproduces how often 
Easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version? yes

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.45.87` or higher for `1.45.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on` Vivo version Android version 12` running `Bravemonoarm64.apk_1.46.67`

- Ensured that there is no crash when VPN is turn off/on 

Example | Example | Example | Example
-- | -- | -- | --
![Screenshot_20221019_104947](https://user-images.githubusercontent.com/38657976/196604380-49cbc2e0-d986-4036-bb5b-d39fe24efd3f.jpg) | ![Screenshot_20221019_105007](https://user-images.githubusercontent.com/38657976/196604647-bd21d567-0806-469f-87a0-3cb6b716ad32.jpg) | ![Screenshot_20221019_105817](https://user-images.githubusercontent.com/38657976/196604901-45cd8af0-b819-4e16-94ca-a0cd5869d668.jpg) | ![Screenshot_20221019_105022](https://user-images.githubusercontent.com/38657976/196604961-be8cf5f4-920c-43ec-a2d7-4267124bba19.jpg)
