### ISSUE TITLE
Switching chains with uppercase chain ID hex does not work

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#25707]
## Description 
Try to switch to Avalanche network via wallet_switchEthereumChain API fails when chain_id param is 0xA86A, and only works if it is passed as 0xa86a.

## Steps to Reproduce

Problem 1:

   1. Open devtool and run `window.ethereum.request({method:'wallet_switchEthereumChain', params: [{chainId: '0xA86A'}]})`

Problem 2:

   1. Go to brave://settings/wallet/networks and edit the chain ID to be `0xa86A` instead of `0xa86a`.  Save.

## Actual result:

Problem 1:

![image](https://user-images.githubusercontent.com/4730197/193083717-d1d5bd49-1f50-460a-9eea-7844eb76a939.png)
And only `window.ethereum.request({method:'wallet_switchEthereumChain', params: [{chainId: '0xa86a'}]})` works.

Problem 2:

Gives an error like this: "Request for method 'eth_chainId' on https://api.avax.network/ext/bc/C/rpc failed"

## Expected result:

Problem 1:

Wallet panel should prompt user the request for switching to Avalanche network.

Problem 2:

It should save with no errors.

## Reproduces how often: 
Always

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.46.70 x64 beta build
- Verified steps from issue description
- Verified running `window.ethereum.request({method:'wallet_switchEthereumChain', params: [{chainId: '0xA86A'}]})` prompts to switch network
- Verified able to approve or cancel the network switch request

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
![image](https://user-images.githubusercontent.com/17010094/197127090-86788253-1ab9-426c-8b23-a1b185facc46.png) | ![image](https://user-images.githubusercontent.com/17010094/197127642-e59cf41b-0897-4be6-941d-e0142eea6d2b.png)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (64-bit) 
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | Linux

- Verified steps from issue description
- Verified running `window.ethereum.request({method:'wallet_switchEthereumChain', params: [{chainId: '0xA86A'}]})` prompts to switch network
- Verified able to approve or cancel the network switch request
- Verified able to save changes to network without any errors 

https://user-images.githubusercontent.com/17010094/199001312-3b60c783-3d23-48c0-9192-5bd2925c5fdb.mp4

------------------------
Verification passed on

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (64-bit) 
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | Windows 11 Version 22H2 (Build 22621.674)

- Verified steps from issue description
- Verified running `window.ethereum.request({method:'wallet_switchEthereumChain', params: [{chainId: '0xA86A'}]})` prompts to switch network
- Verified able to approve or cancel the network switch request
- Verified able to save changes to network without any errors 

https://user-images.githubusercontent.com/17010094/199002833-46de97fe-505b-4aef-ae89-b2d4be7c0522.mp4

------------------------
Verification passed on

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (arm64)
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from issue description
- Verified running `window.ethereum.request({method:'wallet_switchEthereumChain', params: [{chainId: '0xA86A'}]})` prompts to switch network
- Verified able to approve or cancel the network switch request
- Verified able to save changes to network without any errors 

https://user-images.githubusercontent.com/17010094/199000993-ed40c60e-92a4-4a0a-a75c-1c28f1ff01c2.mov
