### ISSUE TITLE
Duplicate name entries in Desktop, when re-sync Android with Desktop.

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#2570]
## Description 
Duplicate name entries in Desktop, when re-sync Android with Desktop.

## Devices
Device1: Desktop (Windows 10) BraveBeta - `0.59.8`
Device2: Android (Samsumg Galaxy J3 version 5.1) - Brave `1.0.71 (sync2)`
Device3: Android (Gionee version 5.1)-Brave `1.0.71 (sync2)`

## Steps to Reproduce

   1. Clean profile
   2. Sync desktop and two android devices using QR code
   3. After sync, remove one of the Android device from sync
   5. Re-sync the Android (which is removed from sync in step 3)
   

## Actual result:
Re-sync is causing duplicate name entries in Desktop
![image](https://user-images.githubusercontent.com/38657976/49987024-ef049680-ff97-11e8-96d8-39eec997b568.png)

## Expected result:
Should not be any duplicate name entries after re-sync

## Reproduces how often: 
Always

## Brave version (brave://version info)

Brave | 0.59.8 Chromium: 71.0.3578.98 (Official Build) beta (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? NA

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional Information
@brave/legacy_qa

**Comment by AlexeyBarabash** [comment]
Could not reproduce with 

Brave | 0.61.0 Chromium: 71.0.3578.98 (Developer Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Linux



Android 1.0.71(sync3)

**Comment by srirambv** [comment]
@GeetaSarvadnya could you recheck this with the new beta and Android sync build

**Comment by AlexeyBarabash** [comment]
@srirambv 
I am not 100% sure, but this one https://github.com/brave/browser-android-tabs/pull/934 may fix, as I saw such duplicating only when Brave Browser Android got ANR and had been restarted, though STR do not mention ANR on Android.

Or may be this PR https://github.com/brave/brave-core/pull/1135 from @darkdh .

**Comment by srirambv** [comment]
Based on https://github.com/brave/brave-core/pull/1135 moving the issue to `0.59.x` @brave/legacy_qa can quickly check on all platforms on the latest RC build and mark it.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.59.31 Chromium: 72.0.3626.71 (Official Build) (64-bit)
-- | --
Revision | f52ccad2a6a3c65fc9e0c591a517ceab1198dac0-refs/branch-heads/3626@{#763}
OS | Linux

* Verified removing device from desktop and re-adding it didn't show duplicate entry
* Verified removing device from sync chain via Android device and re-adding doesn't show duplicate entry
