### ISSUE TITLE
WebUI Rewards panel can be slow to display cached content

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#25705]
## Description 

The WebUI version of the Rewards panel will reused cached `WebContents` if the Rewards panel was opened very recently. If the Reward panel is using cached content, and the `RewardsService` is slow to respond, this can cause a delay in displaying the panel.

## Steps to Reproduce

   1. Open the Rewards panel.
   2. Close the Rewards panel.
   3. Turn off Wifi.
   4. Open the Rewards panel.

## Actual result:

The Rewards panel is not displayed immediately.

## Expected result:

The Rewards panel should be displayed immediately.

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel?  Yes
- Can you reproduce this issue with the nightly channel? Yes

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.46.64 Chromium: 107.0.5304.36 (Official Build) nightly (x86_64)
-- | --
Revision | 2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}
OS | macOS Version 12.6 (Build 21G115)
```
