### ISSUE TITLE
NTP Sponsored images are not loading if Rewards enabled

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#25719]
## Steps to Reproduce

1.  Install 1.45.78
2. launch Brave
3. enable Rewards 
4. leave the default option `ON` for `Show Sponsored Images` toggle
5. open NTP and load SI

## Actual result:

No sponsored images are loaded.  However, if Rewards not enabled, NTPSI are loading as expected
Rewards enabled|Rewards disabled
----|-----
<img width="453" alt="image" src="https://user-images.githubusercontent.com/98358127/193154210-6949626f-78f9-4c4e-99de-96e412e8e7cb.png">|<img width="451" alt="image" src="https://user-images.githubusercontent.com/98358127/193154150-8a7c57b9-a013-4369-8e05-8d77ed42b725.png">

## Expected result:
NTPSI should be loaded 

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Brave | 1.45.78 Chromium: 106.0.5249.65 (Official Build) beta (64-bit)
-- | --
Revision | 3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}
OS | Windows 11 Version 21H2 (Build 22000.978)
## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@rebron @sangwoo108 
cc: @stephendonner

**Comment by kjozwiak** [comment]
hmmm seems to be working on my end on my existing and new profiles that has `Rewards` enabled. Example:

**`Existing with rewards enabled`** | **`New profile with rewards enabled`**
---------------------------------------|--------------------------------------------
![image](https://user-images.githubusercontent.com/2602313/193158467-aa1ae143-5396-4f2b-be69-0ae6844cd21b.png) | ![image (1)](https://user-images.githubusercontent.com/2602313/193158473-1bceec99-e67a-4177-aab4-96ea2e95a968.png)
