### ISSUE TITLE
Group sidebar settings and update labels in brave://settings/appearance

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#25717]
## Description 

As it is right now, the side bar has several options in `Settings --> Appearance` that are not grouped together and are not (imo) labeled properly. 
- There is the "Sidebar" which is the actual "vertical strip" where all the clickable sites/pages/options are
- There is the "side panel" which is the resulting panel that "pops out" of the sidebar when there are additional options to be shown
- There is the "Show side bar panel" button, which automatically opens the "reading list", but which subsequently opens the "sidebar" anyway
- There is the "Side panel" option, that controls whether or not the panel — that is to say, the _bar and the panel_, show on the right or left side of the browser window

All of the above is confusing and looks messy in the UI. I would highly recommend tidying these options up to help clarify what the user is actually controlling. For example, I've created a [rather crude] mock up below:

![image](https://user-images.githubusercontent.com/3299098/193150518-3dba4430-56cd-4c7e-926d-97adda97874f.png)

Here I have:
- Changed _everything_ to read "Side bar" as there is no need to differentiate what the "panel is" in this context. If someone wants to jump straight to the "reading list" then the option should instead say "Show reading list button" as it is specific to that feature. Otherwise, the user is just, effectively, opening the Sidebar
- Grouped the options together in the UI so anyone can see that all of these features are related at a glance

The changes suggested above are a straightfoward way of keeping all the different options available to the user without causing any unnecessary confusion.

**Comment by simonhong** [comment]
As side panel option is enabled again by https://github.com/brave/brave-core/pull/15315, I also think scattered sidebar(panel) related options should be grouped.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.48.129 Chromium: 109.0.5414.87 (Official Build) beta (x86_64)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | macOS Version 11.7.2 (Build 20G1020)

### Steps:
1. installed `1.48.129`
2. launched Brave
3. loaded `brave://settings/appearance`

#### Confirmed `Sidebar` options are grouped together, beneath `Show autocomplete suggestions in address bar`

#### Confirmed `Always show full URLs` is located under `Use wide address bar`

#### Confirmed the `Show Sidebar` button's tooltip reads `Show Sidebar`

`Sidebar` option grouping | `Always show full URLs` | `Show Sidebar` tooltip
---------------------------|-------------------------|---------------
<img width="1312" alt="Screen Shot 2023-01-17 at 5 30 09 PM" src="https://user-images.githubusercontent.com/387249/213059464-94096e41-3543-4a29-bb4e-824d2263867b.png"> | <img width="1312" alt="Screen Shot 2023-01-17 at 5 30 34 PM" src="https://user-images.githubusercontent.com/387249/213059470-b7d78bb6-7552-4704-aaf8-2ebcd87ab311.png"> | <img width="1204" alt="Screen Shot 2023-01-17 at 5 32 02 PM" src="https://user-images.githubusercontent.com/387249/213059475-f1f4f13d-ccba-4934-91d6-3864cc4f044d.png">
