### ISSUE TITLE
PDF.js enabling selectively when there is content to be rendered

### ISSUE THREAD

**Issue by AndriusA** [brave/brave-browser#2571]
## Description 

Having PDF.js extension always enabled is currently necessary for it to pick up PDF content that needs rendering, however it has a significant memory overhead of 20-25% (40-50 MB, compared to Chrome's overall baseline of 200-250MB) even when not actively used.
 
## Steps to Reproduce

Simple memory tracing with `chrome://tracing` and `memory-infra` enabled shows a blank Brave instance using more memory than a blank Google Chrome.

Relaunching Brave with `--disable-pdfjs-extension` and rerunning tracing cuts memory use by approx. 40MB.

## Expected result:

From performance perspective, PDFium-like behaviour is preferred, not affecting resource footprint without a PDF document being rendered. It may be possible to move some PDF document detection into native and only enable PDF.js extension then.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

0.59.2 Chromium: 71.0.3578.80 (Official Build) dev (64-bit)

### Reproducible on current release:

Reproducible on current dev, beta and stable releases.

**Comment by srirambv** [comment]
@fmarier ok to close this in favour of #3846?

**Comment by fmarier** [comment]
Yes, this is no longer be necessary since we'll be removing pdf.js entirely.
