### ISSUE TITLE
Account selection button is cutoff with large account names

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#25720]
## Description 

The select account dropdown icon is not fully displayed when the currently selected account has a long name

## Steps to Reproduce

   1. Create a Filecoin account
   2. Navigate to brave://wallet/crypto/deposit-funds
   3. Select Filecoin
   4. Click continue

## Actual result:

![Screen Shot 2022-09-27 at 4 37 15 PM](https://user-images.githubusercontent.com/30185185/193164105-09689de1-ee74-43d1-927f-be55199de7d0.png)

## Expected result:
<img width="534" alt="Screen Shot 2022-09-29 at 6 04 21 PM" src="https://user-images.githubusercontent.com/30185185/193163873-cd74e0cd-3a2b-44f7-b895-f4dbe0e823f8.png">

## Reproduces how often: 

Easy

## Brave version (brave://version info)

1.44.101 Chromium: 106.0.5249.65 (Official Build) (arm64) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (64-bit) 
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | Linux

- Verified steps from [brave/brave-core#15299](https://github.com/brave/brave-core/pull/15299)
- Verified account selection button is shown properly with long account names
- Encountered [#26408](https://github.com/brave/brave-browser/issues/26408) on Linux
![image](https://user-images.githubusercontent.com/17010094/199177606-93cebdf6-388c-496d-b797-b7d0769cbf7b.png)

------------------------
Verification passed on

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (64-bit) 
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | Windows 11 Version 22H2 (Build 22621.674)

- Verified steps from [brave/brave-core#15299](https://github.com/brave/brave-core/pull/15299)
- Verified account selection button is shown properly with long account names
![image](https://user-images.githubusercontent.com/17010094/199178348-24eddb2a-fc40-4c9c-ae73-557dcb4cefbb.png)

------------------------
Verification passed on

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (arm64)
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#15299](https://github.com/brave/brave-core/pull/15299)
- Verified account selection button is shown properly with long account names
![image](https://user-images.githubusercontent.com/17010094/199175430-bc4448a5-dc12-4aef-80f7-d97e26c0f5fa.png)
