### ISSUE TITLE
This Device is put on the wrong row

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#2572]
## Description 

"This Device" is always be put on the row which id ==0  

## Steps to Reproduce

   1. Setup sync chain between device a and device b (click create sync chain on a and connect it on b)
   2. On the device table of both device a and b, this device always points to a

## Actual result:

<img width="1850" alt="screen shot 2018-12-05 at 09 07 10" src="https://user-images.githubusercontent.com/11330831/50017923-75ae7900-ff82-11e8-80e9-b3f4a9ebfea6.png">

## Expected result:
<img width="1668" alt="screen shot 2018-12-13 at 13 59 36" src="https://user-images.githubusercontent.com/11330831/50017950-91198400-ff82-11e8-9a89-383f8330fd40.png">

## Reproduces how often: 

100%
### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
Noticed this issue this morning on 0.58.12 on both my mac laptop and Linux VM. Both devices show the Mac as 'This Device':
![screen shot 2018-12-14 at 9 43 41 am](https://user-images.githubusercontent.com/28145373/50021454-2b8bbe80-ffa7-11e8-8055-6397b35bb76c.png)

**Comment by GeetaSarvadnya** [comment]
Verification passed on 


Brave | 0.59.12 Chromium: 72.0.3626.17 (Official Build) beta (64-bit)
-- | --
Revision | 08d2140079f8db14c9eb885a803d231b1a30e817-refs/branch-heads/3626@{#315}
OS | Windows



![image](https://user-images.githubusercontent.com/38657976/50419564-67503f00-0857-11e9-9ee9-2edf0cb61a5a.png)
