### ISSUE TITLE
Question: What is included in Brave's ad blocking?

### ISSUE THREAD

**Issue by BlohoJo** [brave/brave-browser#25724]
This is a question I'm unable to find the answer to by searching on Github or Google. I may not be using the best terms.

I'm just wanting to know what blocklists are actually included in Brave's ad blocking.

There are two settings, "Aggressive" and "Standard".

Is this a custom list for each setting that it's pulling from some server somewhere? If so, is it possible to take a look at the list, or download it?

Otherwise, what lists is it using? (I.e., Easylist, Easy Privacy, etc.)

I realize this is meant to be "easy" for the average user looking for better privacy, but some users (like me) want to know more.

Personally, I use uBlock Origin, and that is going to be no longer working on Chromium browsers in a few months, in browser versions released after 1/1/23 (6/1/23 for enterprise builds). So, many users I think will be switching to Brave since the ad blocking is not being done via extension/manifest v2. And, they will be looking for *some* of the same functionality, such as the ability view blocklists.

For example, I just had a website break due to an issue with one filter list, and I would not have been able to find which filter was causing the problem without uBlock's logging tool, which showed me what it was blocking, and which filter list each block was coming from, then I could enter custom filter rules to override suspected items until I narrowed down the one filter that was causing the issue, and report it to the people who maintained the filter list.

Moving forward, without manifest v2 and extensions like uBlock, I think some additional functionality needs implemented to make Brave useful as a workaround for advanced/power users.

**Comment by Miyayes** [comment]
You can find this information here: https://github.com/brave/brave-browser/wiki/Blocking-goals-and-policy

**Comment by antonok-edm** [comment]
@BlohoJo great questions; I've just updated that page with slightly more information to cover some points that weren't there before.

> Moving forward, without manifest v2 and extensions like uBlock, I think some additional functionality needs implemented to make Brave useful as a workaround for advanced/power users.

We actually use uBlock Origin too sometimes when debugging filter list issues to get a quick impression of which filters are applying to a page. The logging there is extremely well-designed :smiley:

We will continue to support Manifest V2 going forwards, so you should be able to continue using it in Brave if you're interested. Meanwhile we do have longer-term plans to improve our in-browser logging abilities (most likely with [DevTools integrations](https://github.com/brave/brave-browser/issues/6458)).

**Comment by BlohoJo** [comment]
> You can find a bunch of this information here: https://github.com/brave/brave-browser/wiki/Blocking-goals-and-policy
> 
> I will also cc: @antonok-edm @pes10k who may be able to share more about Shields.

Thanks!! That's very useful.

But, it only shows lists used for "Aggressive" mode. Can anyone specify what filter lists are omitted for "Standard" mode?

**Comment by antonok-edm** [comment]
It's the same set of lists! Just some heuristics added to avoid blocking 1st party content from those lists in Standard mode.

**Comment by PaperCutBad** [comment]
In uBlock Origin's Logger, I really like how easy it is to create personal filters. Is it possible to include similar functionality for Brave Shields?
![image](https://user-images.githubusercontent.com/87314923/200170433-a2d1baee-427b-450f-9fb2-ac29a87f2874.png)

**Comment by pes10k** [comment]
@PaperCutBad you can add new personal filters in brave://settings/shields/filters.  We don't have the "guide you through" it wizard that uBO has, but you can add new rules there (or subscribe to additional filterlists on the same page)
