### ISSUE TITLE
Include `Timezone` field in `Contact Technical Support` form

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#25722]
## Description 

Include `Timezone` field in `Contact Technical Support` form

## Steps to Reproduce

1. install `1.45.77`
2. launch Brave using --vmodule="*/skus/*"=1 --enable-logging=stderr
3. via brave://flags, set Enable experimental SKU SDK to Enabled
4. also set Experimental SKU Environment to Development
5. click to Relaunch
6. load account.brave.software
7. enter basic auth creds for site
8. enter an email and click Get login link
9. check your email inbox
10. click Log in to Brave or the link in the email
11. click on Browse plans
12. scroll down and click on Buy now for Brave VPN Subscription
13. enter payment details on https://checkout.stripe.com/pay/cs_test…
14. click Subscribe
15. you should get a Complete your purchase... screen
16. click on Complete payment
17. click on the VPN icon
18. click on the Settings gear icon
19. click on Contact technical support
20. look for a `Timezone` field

## Actual result:

No `Timezone` / `timezone` field exists.

<img width="361" alt="Screen Shot 2022-09-29 at 11 51 55 PM" src="https://user-images.githubusercontent.com/387249/193186520-a575d61e-0e0f-4562-918c-bcf2050a927c.png">

## Expected result:

To match parity with mobile and help troubleshoot further, we should include the user's `timezone` in the form

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.45.77 Chromium: 106.0.5249.65 (Official Build) beta (x86_64)
-- | --
Revision | 3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}
OS | macOS Version 11.7 (Build 20G817)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

cc @rebron @bsclifton @spylogsster @MadhaviSeelam @GeetaSarvadnya @srirambv @Uni-verse

**Comment by kjozwiak** [comment]
The above requires `1.47.138` or higher for `1.47.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.47.141 Chromium: 109.0.5414.46 (Official Build) beta (32-bit)
-- | --
Revision | 6e36b77363ef3febbe792af680fa1367993ddcf0-refs/branch-heads/5414@{#709}
OS | Windows 10 Version 22H2 (Build 19045.2364)

Followed my original steps to reproduce.

#### Confirmed `Timezone` values were appropriate for my OS-selected timezones/regions

`Los Angeles, CA` | `America/Los_Angeles` | `St. Petersburg, Russia` | `Moscow, Russia`
--|--|--|--
![25722-0](https://user-images.githubusercontent.com/387249/209225383-eece1d0b-b616-4fc2-84ca-e96cbab35bee.png) | ![25722-1](https://user-images.githubusercontent.com/387249/209225414-28b3ed0e-7384-430a-9294-180797015358.png) | ![25722-2](https://user-images.githubusercontent.com/387249/209225462-bd9a108f-dd34-4893-bbed-46cd6abd3132.png) | ![25722-3](https://user-images.githubusercontent.com/387249/209225474-d4a320ee-9d4e-437c-afe2-51c908ad1f6d.png)

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.47.143 Chromium: 109.0.5414.46 (Official Build) beta (x86_64)
-- | --
Revision | 6e36b77363ef3febbe792af680fa1367993ddcf0-refs/branch-heads/5414@{#709}
OS | macOS Version 11.7.2 (Build 20G1020)

`Cupertino, CA` | `America/Los_Angeles` | `South Africa` | `Johannesburg, South Africa`
---|-------------------------|----------------|------------------------------
<img width="780" alt="Screen Shot 2022-12-23 at 1 15 26 PM" src="https://user-images.githubusercontent.com/387249/209406346-b22986c8-7d57-4e75-9681-497113c60b8e.png"> | <img width="1312" alt="Screen Shot 2022-12-23 at 1 15 02 PM" src="https://user-images.githubusercontent.com/387249/209406367-92dee7a0-17f9-4edd-9958-68f8836e6166.png"> | <img width="780" alt="Screen Shot 2022-12-23 at 11 15 58 PM" src="https://user-images.githubusercontent.com/387249/209406371-cbe0397c-e51c-4b87-b22a-fc89dce97a1a.png"> | <img width="1312" alt="Screen Shot 2022-12-23 at 11 16 34 PM" src="https://user-images.githubusercontent.com/387249/209406374-470e0353-3123-4c2d-9d15-eb1937bdf3c3.png">
