### ISSUE TITLE
Add NFT Multimedia Support

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#25725]
Add multimedia support for NFTs. The following formats should be supported:

1. Audio
2. Video
3. HTML
4. Models e.g GLB files

**Comment by srirambv** [comment]
Marking as QA/Blocked until https://github.com/brave/brave-core/pull/15620, https://github.com/brave/brave-core/pull/15621 & 
https://github.com/brave/brave-core/pull/15622 are merged in with backend changes
