### ISSUE TITLE
Sending to another address using QR code is not working

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#25731]
## Description 
Tried this on metamask and gamestop wallet. When I tried to send to to the QR code, it returned with text 'ethereum' before the address 

## Steps to reproduce 

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by jamesmudgett** [comment]
Remove "Ethereum:" from the address data in qr code

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.46.70 x64 Beta build
- Verified scanning QR code works fine
- Verified for both Ethereum and Solana accounts

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/196889047-fba20af6-7f74-4742-bb4f-37338ab92d5f.mp4> | <video src=https://user-images.githubusercontent.com/17010094/196889719-eb32fbf7-7ccf-4d6e-8fea-ad94ba9a519e.mp4>
