### ISSUE TITLE
Use host name for default sync device name

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#2573]
Instead of displaying Mac/Linux/Windows Desktop, we should use these API to get hostname info

http://man7.org/linux/man-pages/man2/gethostname.2.html
https://docs.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-gethostname

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.59.20 Chromium: 72.0.3626.28 (Official Build) beta(64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Linux

* New sync chain adds device name automatically
