### ISSUE TITLE
Slow down on Google Sheets

### ISSUE THREAD

**Issue by Areckleh** [brave/brave-browser#25735]
## Description 

When opening Google sheets it takes a while to open on start. 
Clicking and interacting with the cells or UI is delayed.

## Steps to Reproduce

   1. Open Google Sheets
   2. Wait for Sheets to open
   3. Click or select multiple cells 

## Actual result:

A slight delay when selecting multiple cells or interacting in Google Sheets

## Expected result:
No delay or hang up

## Reproduces how often: 

Everytime when using Google sheets

## Brave version (brave://version info)

Present in v1.44x macOS and Windows

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by Areckleh** [comment]
+1 Community https://community.brave.com/t/google-sheets-unusably-slow-in-brave-browser/435060

**Comment by Areckleh** [comment]
Gsheets when connected to an external monitor

https://user-images.githubusercontent.com/43886134/193313252-6f0f1b41-375d-4a7b-9458-77dc1ada3cfb.mov

Gsheets disconnect from an external monitor

https://user-images.githubusercontent.com/43886134/193313684-1fca5255-08ec-4d05-88cc-4d456fe1f3c9.mov

**Comment by kjozwiak** [comment]
Closing 👍 Most likely fixed by https://chromium.googlesource.com/chromium/src/+/65af93c719fcb74a2adeafe2d8454c2515dbc22b. Thanks for moving this into the milestone @rebron 👍 

@Areckleh once we push the new release with `106.0.5249.91`, it should address the above issues you're seeing.
