### ISSUE TITLE
Incorrect text for password input field placeholders

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#25745]
## Description 

Under "Enter Password", it should say, "Enter your Brave Wallet password" instead of, "Enter new password".

![189906557-3409cfd0-aa88-4aae-be7c-0e0e985e9122](https://user-images.githubusercontent.com/30185185/193344294-d3061cb9-e014-4f10-98ac-aaefddb5c19f.png)

## Steps to Reproduce

   1. Create a wallet
   2. Open the accounts screen
   3. select an account
   4. click either the pencil or QR code icon
   5. click the Private key tab

## Actual result:

"Enter new password" is displayed in the password input field

## Expected result:
"Enter your Brave Wallet password" is displayed in the password input field

## Reproduces how often: 

Easy

## Brave version (brave://version info)

1.44.101 Chromium: 106.0.5249.65 (Official Build) (arm64) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

**Comment by Eddayavuz** [comment]
Hello,

I'd like to take on this task. However, could you please label this under hacktober, it will be my first contribution? :)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (64-bit) 
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | Linux

- Verified steps from [brave/brave-core#15320](https://github.com/brave/brave-core/pull/15320)
- Verified placeholder text is shown correctly 

Scenario 1 | Scenario 2 | Scenario 3 | Scenario 4
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/199172213-1a69c141-2b97-483e-a428-7a17f1432acc.png) | ![image](https://user-images.githubusercontent.com/17010094/199172175-f1d46488-b0bd-4f9c-b287-e4c0df3b81b5.png) | ![image](https://user-images.githubusercontent.com/17010094/199171941-aa08a5e4-4f04-4852-981c-3e33aca942c7.png) | ![image](https://user-images.githubusercontent.com/17010094/199172416-e46d1b6f-cb6d-4906-ad32-7e0a5ee1b824.png)

------------------------
Verification passed on

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (64-bit) 
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | Windows 11 Version 22H2 (Build 22621.674)

- Verified steps from [brave/brave-core#15320](https://github.com/brave/brave-core/pull/15320)
- Verified placeholder text is shown correctly 

Scenario 1 | Scenario 2 | Scenario 3 | Scenario 4
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/199172691-6300dac3-1b89-4d4c-b4d6-fd4713e18269.png) | ![image](https://user-images.githubusercontent.com/17010094/199172707-d6c6a4b9-1ced-420f-af71-939c866b99e1.png) | ![image](https://user-images.githubusercontent.com/17010094/199172732-bbeacc44-ecfd-426b-987f-0a5109b757d9.png) | ![image](https://user-images.githubusercontent.com/17010094/199172776-451835b3-ea40-458c-b0b5-d48a2b28e832.png)

------------------------
Verification passed on

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (arm64)
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#15320](https://github.com/brave/brave-core/pull/15320)
- Verified placeholder text is shown correctly 

Scenario 1 | Scenario 2 | Scenario 3 | Scenario 4
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/199171884-669158c3-9e88-465f-9cf3-1f2ed3917786.png) | ![image](https://user-images.githubusercontent.com/17010094/199171896-f3db196c-6863-48c3-8b09-c71137bb3033.png) | ![image](https://user-images.githubusercontent.com/17010094/199171874-19ec0a38-a24e-48b2-abd8-ca2b83839f8f.png) | ![image](https://user-images.githubusercontent.com/17010094/199171889-7f2006bb-e013-46cf-86e9-1885f98f5ee8.png)
