### ISSUE TITLE
Add Buy/Deposit buttons to Market Tab Tokens

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#25744]
## Description 
Add `Buy` and `Deposit` buttons to the `Market` tab tokens list.

![Screen Shot 2022-09-30 at 2 09 13 PM](https://user-images.githubusercontent.com/40611140/193340296-0e81e8f8-7122-4576-992a-0719023e0138.png)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.46.70 Chromium: 107.0.5304.36 (Official Build) beta (64-bit) 
-- | --
Revision | `2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}`
OS | Linux

- Verified steps from [brave/brave-core#15365](https://github.com/brave/brave-core/pull/15365)
- Verified `Buy` & `Deposit` buttons are shown next to tokens where supported
- Verified for a few tokens only `Deposit` button is shown 
- Encountered [#26246](https://github.com/brave/brave-browser/issues/26246)

https://user-images.githubusercontent.com/17010094/197798608-f47d81af-fe26-469a-83be-7c2778046e26.mp4

------------------------
Verification passed on

Brave | 1.46.70 Chromium: 107.0.5304.36 (Official Build) beta (64-bit) 
-- | --
Revision | `2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}`
OS | Windows 11 Version 22H2 (Build 22621.674)

- Verified steps from [brave/brave-core#15365](https://github.com/brave/brave-core/pull/15365)
- Verified `Buy` & `Deposit` buttons are shown next to tokens where supported
- Verified for a few tokens only `Deposit` button is shown 
- Encountered [#26246](https://github.com/brave/brave-browser/issues/26246)

https://user-images.githubusercontent.com/17010094/197799731-04803108-6bc5-448c-a5ad-d45bde0fe45f.mp4


------------------------
Verification passed on

Brave | 1.46.70 Chromium: 107.0.5304.36 (Official Build) beta (arm64)
-- | --
Revision | `2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#15365](https://github.com/brave/brave-core/pull/15365)
- Verified `Buy` & `Deposit` buttons are shown next to tokens where supported
- Verified for a few tokens only `Deposit` button is shown 
- Encountered [#26246](https://github.com/brave/brave-browser/issues/26246)

https://user-images.githubusercontent.com/17010094/197796596-44f530c0-0c2b-4ed6-9a01-2520d824171c.mov
