### ISSUE TITLE
clicking anywhere on the same line as 'Bookmarks' toggles Bookmark Sync on/off

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#2574]
## Description 
If you click anywhere on the same line as 'Bookmarks', Bookmark sync is toggled on/off.

## Steps to Reproduce

   1. Sync two devices
   2. On brave://sync page, click somewhere to the right of the word 'Bookmarks' on the same line. 
   3. 

## Actual result:
![entirelineclickable](https://user-images.githubusercontent.com/28145373/50022327-bec5f380-ffa9-11e8-836f-ba9ab761042c.gif)

## Expected result:
Just toggle itself should be clickable

## Reproduces how often: 
Easily

## Brave version (brave://version info)

Brave | 0.58.12 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.59.20 Chromium: 72.0.3626.28 (Official Build) beta(64-bit)
--
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Linux

![2574](https://user-images.githubusercontent.com/17010094/50816719-6df6b000-1347-11e9-804b-f95934609256.gif)
