### ISSUE TITLE
Add right-side display support for Sidebar

### ISSUE THREAD

**Issue by UjCbFwtBayFM** [brave/brave-browser#25756]
Currently there is a setting in brave://settings/appearance that should allow for moving the Sidebar on the right side of the window, but it seems it is not linked to the backend.
It would be great to have this setting implemented so it actually works.
<html>
<body>

Brave | 1.44.101 Chromium: 106.0.5249.65 (Official Build) (64-bit)
-- | --

</body>
</html>

**Comment by mlntr** [comment]
It's already confirmed to be coming, it's in nightly

**Comment by UjCbFwtBayFM** [comment]
From Nightly:
![2022-10-01-155027-brave](https://user-images.githubusercontent.com/22710992/193412872-294e1146-05e7-40e4-a73d-987dc6fd3fb7.png)
It looks like they preferred to remove the setting than have it work.

**Comment by mlntr** [comment]
Not everything is necessarily meant to be working yet in nightly

**Comment by rebron** [comment]
@UjCbFwtBayFM This one is in progress. We removed the setting in the UI since it wasn't doing anything yet.
<img width="1417" alt="Screenshot 2022-10-03 at 12 47 52 PM" src="https://user-images.githubusercontent.com/5951041/193665739-9d45719b-e7ee-48c4-a533-c64c40d76e16.png">

**Comment by mlntr** [comment]
> @UjCbFwtBayFM This one is in progress. We removed the setting in the UI since it wasn't doing anything yet. <img alt="Screenshot 2022-10-03 at 12 47 52 PM" width="1417" src="https://user-images.githubusercontent.com/5951041/193665739-9d45719b-e7ee-48c4-a533-c64c40d76e16.png">

The icon should be horizontally flipped (i.e. have the sidebar on the right of the image) when the panel is set to be on the right

**Comment by MadhaviSeelam** [comment]
Verification `In progress`  using 
```
Brave | 1.46.73 Chromium: 107.0.5304.62 (Official Build) beta (64-bit)
-- | --
Revision | 1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942}
OS | Windows 11 Version 21H2 (Build 22000.1098)
```

Case 1: `brave://settings/appearance` - Select  `Show on right` radio button 

1. Install 1.46.73
2. launch Brave
3. load `brave://settings/appearance`
4. confirmed default option for Side panel is `Show on left`'
5. clicked `Show on right` radio button in the Side panel section
6. side bar is visible on the right with all four widgets displayed
7. `Show side panel` button on the toolbar is selected and rotated to right
8. click on reading list icon on the sidebar to open and close the side panel 
9. click on bookmarks icon on the sidebar to open and close the side panel

step 4|step 5|step 8|step 9
-----|-----|---|----
<image width ="900" alt="image" src= "https://user-images.githubusercontent.com/98358127/197306179-3d0fe1af-f881-47ed-b458-fac1c303e870.png">|<image width ="900" alt="image" src= "https://user-images.githubusercontent.com/98358127/197296899-6e260e4c-e152-40c6-92e0-1bb80a560be8.png">|<image width ="900" alt="image" src="https://user-images.githubusercontent.com/98358127/197296529-ed5708c8-4c2b-483b-833b-0ca37688a47c.png">|<image width ="900" alt="image" src="https://user-images.githubusercontent.com/98358127/197297067-7d799835-8112-4a73-a8f9-5d3a13cbf8e7.png">

Case 2: `brave://settings/appearance`  - `Show on left` radio button as a default  

1. clean profile
2. load `brave://settings/appearance`
3. confirmed default option for Side panel is `Show on left`'
4. side bar is visible on the left with all four widgets displayed
5. show side panel button on the toolbar is highlighted and rotated to left 
6. click on reading list icon on the sidebar to open and close the side panel 
7. click on bookmarks icon on the sidebar to open and close the side panel


step 3|step 6| step 7
---|----|----
<image width ="900" alt="image" src="https://user-images.githubusercontent.com/98358127/197296807-5067dd77-0e09-49e3-a426-e40a64501f0d.png">|<image width ="900" alt="image" src="https://user-images.githubusercontent.com/98358127/197296423-9e1fb469-eb62-46f7-a0b3-e7a10dba2029.png">|<image width ="900" alt="image" src="https://user-images.githubusercontent.com/98358127/197306344-293b21ee-de24-4c0f-b25d-11103b242a6e.png">

Case 3: `Show side panel` toolbar button will  open the panel on the right

1. continue from case 2
2. load `brave://settings/appearance`
3. clicked `Show on right` radio button 
4. side bar is visible on the right with all four widgets displayed 
5. `Show side panel` button on the toolbar is rotated to right
6. click on the `Show side panel`  toolbar button
8. confirmed `Show side panel`  toolbar button is selected
9. confirmed side panel on the right opened with `Reading list` icon enabled by default
11. clicked the `Show side panel` toolbar button again
12. confirmed no sidebar buttons were shown as selected
13. confirmed the `Show side panel` toolbar button was not shown as selected

step 4-5|step 7-8|step 10-11
-----|----|----
<image width ="900" alt="image" src="https://user-images.githubusercontent.com/98358127/197305670-eb95095d-705b-48f1-ba4d-4d3eff70518e.png">|<image width ="900" alt="image" src="https://user-images.githubusercontent.com/98358127/197305686-159d2189-17b6-4cb6-9bcb-e909650b9296.png">|<image width ="900" alt="image" src="https://user-images.githubusercontent.com/98358127/197305871-f8845f6a-b8a5-457a-833a-0813010df235.png">

Case 4: Enable `#brave-veritcal-tabs` in `brave://flags`

1. clean profile
2. open brave://flags
3. select `Enabled` for vertical tabs `#brave-vertical-tabs`
4. click `Relaunch` button
5. vertical tab is displayed on the left to the right of the side bar
6. click on the Reading list icon
7. confirmed the reading list opened
8. vertical tab moved right when side panel opened 

Ex1|Ex2|Ex3
---|---|---
![image](https://user-images.githubusercontent.com/98358127/197306598-591aa78f-b272-41ee-a760-eb5bd1665f06.png)|![image](https://user-images.githubusercontent.com/98358127/197306944-19e99c7a-60ad-44e2-9fef-82f60e601bc2.png)|![image](https://user-images.githubusercontent.com/98358127/197307210-3d1ddbea-6a58-41f3-a7c6-68cfcb8fbb66.png)
