### ISSUE TITLE
Drag-drop indicator is not removed on side-panel

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#25752]
## Description 

Drag-drop indicator is not removed on side-panel

## Steps to Reproduce

   1. Drag an item on side-panel and try to drop it at the top or bottom
   2. Drag-drop indicator is shown always
   3. Close and relaunch browser, indicator is removed

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/193380061-b2ccce07-cb50-4f52-90ab-e7e1516272f2.png)
![image](https://user-images.githubusercontent.com/17010094/193380012-92a66faa-2ce3-4970-a094-42878271d8ff.png)
![image](https://user-images.githubusercontent.com/17010094/193380017-5f84fa40-4c05-4224-9947-147671d5491e.png)

## Expected result:
Do not retain the drag-drop indicator 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.46.24 Chromium: 106.0.5249.65 (Official Build) nightly (64-bit)
-- | --
Revision | `3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}`
OS | Windows 11 Version 22H2 (Build 22623.730)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Partial Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @simonhong @petemill @brave/qa-team

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.47.7 Chromium: 107.0.5304.36 (Official Build) nightly (64-bit)
-- | --
Revision | 2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}
OS | Windows 11 Version 21H2 (Build 22000.1098)
```

- Install 1.47.7
- launch Brave
- drag an item (`Brave talk`) on side-panel and try to drop it at the top or bottom
- confirmed drag-drop indicator is not shown
- confirmed close and relaunch browser, indicator is not shown

Before fix|After fix
-----|-----
<image width="500" at="image" src="https://user-images.githubusercontent.com/98358127/197080010-2530db5a-0217-4fc6-8120-d571fd07038c.png">|<image width="500" at="image" src="https://user-images.githubusercontent.com/98358127/197079976-25b665e3-b37b-47ef-95e8-427a2e00df72.png">
