### ISSUE TITLE
Draggable chrome

### ISSUE THREAD

**Issue by mlntr** [brave/brave-browser#25757]
#### Feature request

- Brave has has this narrow address bar, so there is space on both sides:

![image](https://user-images.githubusercontent.com/17552475/193411932-18bd53a4-7910-4e78-b78d-91b19109a605.png)

- This space could be made useful by letting users move the window position by dragging it

- When the tab row is full, users have to be more careful to drag the window. This would help alleviate this while making use of unused space

- Firefox and Safari have this same convenient feature

**Comment by rebron** [comment]
cc: @simonhong what do you think?

**Comment by simonhong** [comment]
> cc: @simonhong what do you think?

I think this is good suggestion. empty toolbar area would be good place for dragging!

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.47.120 Chromium: 108.0.5359.99 (Official Build) dev (x86_64)
-- | --
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | macOS Version 13.1 (Build 22C65)

### Steps:
1. installed `1.47.120`
2. launched Brave
3. left side: confirmed I could click + hold the empty toolbar area between the `Reload this page` and `Bookmark this tab` icons, to drag and reposition the browser
4. right side: confirmed I could click + hold the empty toolbar area between the `BAT`/Rewards icon and the `Show side panel` button

#### Newly-draggable regions

`left side` | `right side` | `full toolbar`
--------|---------------|------------
<img width="138" alt="Screenshot 2022-12-08 at 11 04 43 PM" src="https://user-images.githubusercontent.com/387249/206644809-60cdf144-c3de-4a0a-a57c-509487b8a5f0.png"> | <img width="162" alt="Screenshot 2022-12-08 at 11 04 51 PM" src="https://user-images.githubusercontent.com/387249/206644811-95f913dd-51cb-4b3d-858e-12e444d12b0f.png"> | <img width="1194" alt="Screenshot 2022-12-08 at 11 06 19 PM" src="https://user-images.githubusercontent.com/387249/206645036-36a54f7c-ea94-4df0-a256-5242751f05f7.png">
