### ISSUE TITLE
Sync chain not being reset when Main device is removed

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#2575]
## Description 
Found while testing https://github.com/brave/brave-core/pull/1019

If you have a sync chain with two devices, when you remove the main device (Device A), the sync chain is not being reset on second device.

Device A - macOS Laptop
Device B - Linux VM

## Steps to Reproduce

   1. Setup sync between Device A and B
   2. On Device A, remove itself
   3. Sync is reset on Device A
   4. Go over to Device B

## Actual result:
Sync is not reset on Device B

https://drive.google.com/file/d/1Qmuu0UqatUjKVcfVrYidtfp1lx5OTtOX/view?usp=sharing

## Expected result:
Sync to be reset on both devices since you need two devices for a sync chain.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.58.12 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

and 0.58.12 on Linux VM as well.

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
cc @brave/legacy_qa for verification on other platforms

**Comment by kjozwiak** [comment]
Waiting on new build as the PR landed ~11hrs ago. Still reproducible under `0.58.14 Chromium: 71.0.3578.98` which was built ~3 days ago on Friday.
