### ISSUE TITLE
Can not see VPN Pop-up

### ISSUE THREAD

**Issue by 5WhiteTiger5** [brave/brave-browser#25766]
## Description 
I cant see the VPN Pop-up in the brave browser settings

## Actual result 
![Screenshot_2022-10-02-12-45-43_1](https://user-images.githubusercontent.com/114278266/193450265-d83e1809-69ac-4352-a40e-2843da2308ac.png)

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- yes
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 8.1 Oreo
   
## Brave version
![Screenshot_2022-10-02-12-45-38_1](https://user-images.githubusercontent.com/114278266/193450255-42900dbd-1cc5-4bb0-9f92-ca73cdc8f023.png)

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment]
I think this version of Android is not supporting VPN- this is expected
