### ISSUE TITLE
Support to multiple custom images for NTP background

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#25761]
This is a subtask of https://github.com/brave/brave-browser/issues/15252

---

Users should be able to upload multiple images for their NTP background.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using 
```
Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (64-bit)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | Windows 11 Version 21H2 (Build 22000.1098)
```
Pre-requisites: Have few images available in a directory

Case 1: Upload a single image in the very first tab
<details>

1. Install 1.46.81
2. launch Brave
3. click `Skip welcome tour` 
4. click `Customize`
5. Click `Upload from device` in `Use your own` tile
6. select an image from the directory (eg. Downloads)-->open
7. Uploaded image is shown as the background 
8. click the `Upload from device` again to show the image 

#### Confirmed image is uploaded successfully and shown for NTP background 

step 5|step 6|step 7|step8
----|----|-----|-----
<img width="464" alt="image" src="https://user-images.githubusercontent.com/98358127/198384792-676e3bcb-3e8e-49f0-975d-a59c3318d7fb.png">|<img width="473" alt="image" src="https://user-images.githubusercontent.com/98358127/198376069-3a55f9a5-2da2-4b98-bc02-b432d04eb30a.png">|<img width="451" alt="image" src="https://user-images.githubusercontent.com/98358127/198385100-1d81b451-8ed4-4c55-ad9d-b42356728f8d.png">|<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/198385228-6afb1e77-ea19-4ff0-8c4c-189837e4bcd8.png">
</details>

Case 2: Users should be able to upload multiple images in NTP
<details>

1. new profile
2. launch Brave
3. open NTP 
4. click `Customize`
5. Click `Upload from device` in `Use your own` tile
6. select an image from the directory (eg. Downloads)-->open
7. Uploaded image is shown as the background 
8. click the `Upload from device` again to show the image 
9. continue to upload images 
10. Able to upload only 24 images as blank `Upload from device` tile was not available
11. click on each of the uploaded images

#### Confirmed all of the images are uploaded successfully and are shown for NTP background 
 
step 5|step 6|step7|step 8|step 9|step10|step 10
---|----|-----|----|---|----|----
<img width="464" alt="image" src="https://user-images.githubusercontent.com/98358127/198386500-e679d99a-b57d-44bb-9cec-26c3d7568e39.png">|<img width="366" alt="image" src="https://user-images.githubusercontent.com/98358127/198387315-f3bbee4c-c21b-452a-999b-7e549c14739a.png">|<img width="454" alt="image" src="https://user-images.githubusercontent.com/98358127/198387568-5e5b2a38-9a0b-4c86-bd37-ba0929a1d24d.png">|<img width="460" alt="image" src="https://user-images.githubusercontent.com/98358127/198387392-76ce8768-04e2-44d5-9cb4-64dbbc66dad5.png">|<img width="464" alt="image" src="https://user-images.githubusercontent.com/98358127/198389017-9e696f2f-e2e2-4a6c-a2a5-145e2a361f01.png">|<img width="464" alt="image" src="https://user-images.githubusercontent.com/98358127/198389483-e78977c0-2e2e-47f1-bc7c-532f3b2f2b1d.png">|<img width="464" alt="image" src="https://user-images.githubusercontent.com/98358127/198389137-2a4875bd-1286-4bde-8773-b0bcbbf861f9.png">
</details>

Case 3: When user toggle on random button, one of these images should appear on NTP randomly.
<details>

1. Continue from Case 2
     - custom images are uploaded
2. toggle `ON` `Refresh on ever new tab`
3. Refresh the tab (Ctrl+R)

#### Confirmed custom images randomly loaded

step 1|step 2|step 3|results
---|----|-----|----
<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/198391160-15e546b1-776e-4fa1-ba84-49a6dfbb7cfe.png">|<img width="466" alt="image" src="https://user-images.githubusercontent.com/98358127/198391216-1cbf24bf-2044-4083-bea7-c6f4bec47114.png">|<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/198392552-7a31f985-41d0-4295-81a8-fd7a374cfade.png">|<img width="466" alt="image" src="https://user-images.githubusercontent.com/98358127/198392508-0087cf45-5a23-44a9-b61c-95cd87817678.png">
</details>

Case 4: Users should be able to remove these images
<details>

1. continue from Case 3
     - custom images are uploaded
2.  click `Customize`
3.  click `Upload from device`
4. click `x` on an image

#### Confirmed image is removed
 step 4|result 1|result 2
----|---|----
<img width="468" alt="image" src="https://user-images.githubusercontent.com/98358127/198397964-f0d719a0-da86-48fa-85b6-c3753387c4d0.png">|<img width="465" alt="image" src="https://user-images.githubusercontent.com/98358127/198398010-24503884-1864-457c-8f3d-aacf7019c39e.png">|<img width="458" alt="image" src="https://user-images.githubusercontent.com/98358127/198398084-44af4538-259c-4da9-96c8-20fc4d66404c.png">

</details>

Case 5: a file name has other characters than alphabet, it should be uploaded.
<details>

1.new profile
2. launch Brave
3. open NTP 
4. click `Customize`
5. Click `Upload from device` in `Use your own` tile
6. select an image (`custom139#@$#$$###2323image`) from the directory (eg. Downloads)-->open
7. click `Upload from device` again

#### Confirmed image loaded successfully 

step 6|step 7|result
---|----|----
<img width="483" alt="image" src="https://user-images.githubusercontent.com/98358127/198396851-01f012a1-a457-4ff5-941b-69fe08ebab83.png">|<img width="462" alt="image" src="https://user-images.githubusercontent.com/98358127/198396894-b5af55b8-d088-419a-9d5c-1891b734e7eb.png">|<img width="461" alt="image" src="https://user-images.githubusercontent.com/98358127/198397067-4673aabd-8dcf-494e-bcce-3f1e13c135c8.png">

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.46.86 Chromium: 107.0.5304.91 (Official Build) beta (x86_64)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | macOS Version 11.7.1 (Build 20G918)

### Prerequisite: have 15+ images handy

### Case 1: Upload a single image in the 1st tab
<details>

</details>

### Case 2: Users should be able to upload multiple images in new-tab page 
<details>

</details>


### Case 3: Toggling `Refresh on every new tab` should cycle through images
<details>

</details>


### Case 4: Users should be able to remove custom-background images
<details>

</details>


### Case 5: filename with non-alphanumeric characters
<details>

</details>
