### ISSUE TITLE
[Android] Improve Rating Prompts

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#25777]
### Spec
https://bravesoftware.slack.com/archives/C03MMJ4CHEZ/p1664813123345989?thread_ts=1664813117.013499&cid=C03MMJ4CHEZ

**Comment by kjozwiak** [comment]
When running through the above, please keep in mind https://github.com/brave/brave-browser/issues/27750 and ensure that there's no crashes with the new improved rating modals/prompts.

**Comment by Uni-verse** [comment]
Verified on `Samsung GS 21 ` using version:

```
Brave	1.48.157 Chromium: 110.0.5481.77 (Official Build) (64-bit) 
Revision	65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS	Android 13; Build/TP1A.220624.014
```
Scenario 1 (Condition: Default Browser set):

1. Launch App
2. Set browser to default
3. Background brave app, change system date/time to 30 days ahead
4. Open app
5. Close app
6. Change date 1 day ahead
7. Repeat steps 4-7 four times
8. Close app 
9. Change system time 3 days ahead
10. Relaunch app

Example | Example | Example | Example
-|-|-|-
![screenshot-1675463873726](https://user-images.githubusercontent.com/17885425/217023379-37cb7bee-9951-47d2-81ae-c4f3279cbb6a.png) | ![screenshot-1675463889777](https://user-images.githubusercontent.com/17885425/217023386-73b72371-a1e8-40c1-90cb-98f22aa77b04.png) | ![screenshot-1675463900202](https://user-images.githubusercontent.com/17885425/217023389-ce756e6f-b857-4025-ad13-6001b86fb1bd.png) | ![screenshot-1675463942940](https://user-images.githubusercontent.com/17885425/217023394-83642591-6a50-4392-aff1-ea0950dd2578.png)


Scenario 2: (Condition: 5 Bookmarks created):

1. Launch app
2. Enabled brave news
3. Bookmark 5 webpages
4. Background app, change system date/time 30 days ahead
5. Open app

Example | Example | Example | Selecting Sad Emoji
-|-|-|-
![screenshot-1675697653425](https://user-images.githubusercontent.com/17885425/217023675-3310cee8-3f21-415a-a673-1e0aa6e98d54.png) | ![screenshot-1675697670296](https://user-images.githubusercontent.com/17885425/217023682-6b4356a5-d255-4ad8-ae9e-389fc97aee42.png) | ![screenshot-1675697684750](https://user-images.githubusercontent.com/17885425/217023691-4eda41c0-b876-426e-b4d7-36b576769c72.png) | ![screenshot-1675698115786](https://user-images.githubusercontent.com/17885425/217023734-e4f15fd0-4a5e-46cb-9ac0-bcc30226cac6.png)


Encountered: https://github.com/brave/brave-browser/issues/28315
