### ISSUE TITLE
Restore Wallet moves line position to end when editing

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#25774]
## Description 
When restoring a `Wallet` during onboarding, if you try to edit any of the phrase it will move your line position to the end of the phrase.

https://user-images.githubusercontent.com/40611140/193607383-5da693fe-1bc6-4854-85a1-463c1584358b.mov

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.46.70 Chromium: 107.0.5304.36 (Official Build) beta (64-bit) 
-- | --
Revision | `2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}`
OS | Linux

- Verified steps from issue description 
- Verified editing seed words doesn't move cursors position

https://user-images.githubusercontent.com/17010094/197250290-5688a9ad-5b15-49e5-8e7e-0d90d9d156b9.mp4


------------------------
Verification passed on

Brave | 1.46.70 Chromium: 107.0.5304.36 (Official Build) beta (64-bit) 
-- | --
Revision | `2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}`
OS | Windows 11 Version 22H2 (Build 22621.674)

- Verified steps from issue description 
- Verified editing seed words doesn't move cursors position

https://user-images.githubusercontent.com/17010094/197250439-b08e2f38-0916-46c7-9644-def56037b55c.mp4


------------------------
Verification passed on

Brave | 1.46.70 Chromium: 107.0.5304.36 (Official Build) beta (arm64)
-- | --
Revision | `2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from issue description 
- Verified editing seed words doesn't move cursors position

https://user-images.githubusercontent.com/17010094/197249075-4eb3cfac-6d79-4119-a1af-3da7d44fb11d.mov
