### ISSUE TITLE
No user feedback while (slow) gateway loads

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#25788]
## Description 

No user feedback when (slow) gateway loads

## Steps to Reproduce

1. install `1.46.2
2. launch Brave
3. load `ipfs://QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco/wiki/Tokyo_National_Museum.html`
4. click on `Use a public gateway`
5. wait...

## Actual result:

No UI feedback on the progress (that it's even happening)

## Expected result:

`Loading...` or `Opening...` or an icon, or something

<img width="1312" alt="Screen Shot 2022-10-03 at 11 12 03 PM" src="https://user-images.githubusercontent.com/387249/193726618-4c7eafd4-5a55-45e9-814f-4e92ce8d16ad.png">

## Reproduces how often: 

often (with the right slow network conditions)

## Brave version (brave://version info)

Brave | 1.46.29 Chromium: 106.0.5249.91 (Official Build) nightly (x86_64)
-- | --
Revision | fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}
OS | macOS Version 11.7 (Build 20G817)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

cc @aguscruiz @cypt4

**Comment by vadimstruts** [comment]
The IPFS local node and scheme has been [deprecated](https://github.com/brave/brave-browser/issues/37735)
