### ISSUE TITLE
Choose new server throws `Can't connect to server` error in both profile 1 and profile 2

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#25789]
## Description 

Choose other server in Profile 2 throws `Can't connect to server` error 
## Steps to Reproduce

**Pre-requisites:** Enable sku and vpn flags via brave://flags and purchase a vpn
   1. Clean profile 1.45.x
   2. Follow the prerequisites
   3. Enable VPN on profile 1 (Confirmed VPN is cconnected to default/nearest server `Singapore`)
   4. Create a profile 2 via hamburger menu
   5. Ensure that VPN is connected in profile 2  (Confirmed VPN is connected to `Singapore`
   6. In profile 2, click on VPN and choose another server 
   7. `Can't connect to server` error is shown
   8. Click on retry connects the server successfully
   9. Go to profile 1 and select the new server 
   10. `Can't connect to server` error is shown
   11. Click on retry connects the server successfully

## Actual result:

Choose other server in Profile 2 throws `Can't connect to server` error 
## Expected result:

Should not throw any error
## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.45.78 Chromium: 106.0.5249.65 (Official Build) beta (64-bit)
-- | --
Revision | 3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}
OS | Windows 10 Version 21H2 (Build 19044.2006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @bsclifton @spylogsster @mattmcalister

**Comment by GeetaSarvadnya** [comment]
Verified the issue again the happens on the Profile1 also when user tries to connect the new server.

**Comment by kjozwiak** [comment]
The above requires `1.46.87` or higher for `1.46.x` verification 👍 Believe we might need to wait to verify the above until we can QA the VPN feature with the new SKU SDK. @stephendonner @LaurenWags please correct me if I'm wrong.

**Comment by LaurenWags** [comment]
@kjozwiak correct afaik, have added `QA/Blocked` label until all server side/back end/website work is complete.

**Comment by GeetaSarvadnya** [comment]
The issue is still reproducible in the fillowing build hence opened a new follow up issue https://github.com/brave/brave-browser/issues/26857. Hence marked this issue as QA/No

```
Brave | 1.46.117 Chromium: 107.0.5304.110 (Official Build) beta (64-bit)
-- | --
Revision | 2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}
OS | Windows 10 Version 21H2 (Build 19044.2251)

```
