### ISSUE TITLE
Two different servers can be set on two different profiles

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#25790]
## Description 

Two different servers can be set on two different profiles
## Steps to Reproduce

  **Pre-requisites:** Enable `sku` and `vpn` flags via brave://flags and purchase a vpn
   1. Clean profile 1.45.x
   2. Follow the prerequisites
   3. Enable VPN on profile 1 
   4. Create a profile 2 via hamburger menu
   5. Ensure that VPN is connected in profile 2  
   6. Ensure that the same server is connected in profile 1 and profile 2
   7. In profile 2, click on VPN and choose another server 
   8. `Can't connect to server` error is shown
   9. Click on `Try again` button connects to selected server
   
## Actual result:

Two different servers can be set on two different profiles

![connect two different servers in two different profiles](https://user-images.githubusercontent.com/38657976/193771003-187d2db4-bcb4-4f51-a51d-af90bd77ea64.gif)

## Expected result:
No sure, but I assume shouldn't be able to connet two different states

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.45.78 Chromium: 106.0.5249.65 (Official Build) beta (64-bit)
-- | --
Revision | 3269dc3633cdd2ab94546fdbe54962e45b17a6e0-refs/branch-heads/5249@{#580}
OS | Windows 10 Version 21H2 (Build 19044.2006)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @spylogsster @bsclifton

**Comment by GeetaSarvadnya** [comment]
While doing futher investigation on the issue found that IP points to the 2nd server on both the profiles although the different servers connected in the UI. Looks like UI bug?

**Comment by simonhong** [comment]
@GeetaSarvadnya Yes, it's UI issue. It's not updated properly when different server is used from another profile.

**Comment by kjozwiak** [comment]
The above requires `1.46.87` or higher for `1.46.x` verification 👍 Believe we might need to wait to verify the above until we can QA the VPN feature with the new SKU SDK. @stephendonner @LaurenWags please correct me if I'm wrong.

**Comment by LaurenWags** [comment]
@kjozwiak correct afaik, have added `QA/Blocked` label until all server side/back end/website work is complete.

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.46.117 Chromium: 107.0.5304.110 (Official Build) beta (64-bit)
-- | --
Revision | 2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}
OS | Windows 10 Version 21H2 (Build 19044.2251)
```
- Verified the STR from the description and ensured below:
   - If we try to set the 2 two diffrent servers on two profiles (Profile 1 and Profile 2) the latest server will be set on both the profiles e.g: If we select `CA` profile 1 and before it gets connect to the server, if we try to select `UK` for profile 2, then server `UK` will be set on both the profiles
   - Confirmed ipleak.net points to same IP on both the profiles
   - Confirmed that same server name is shown for both the profiles

![VPN profiles](https://user-images.githubusercontent.com/38657976/202725956-caa9d783-94b7-4034-8fd7-d45635da64b5.gif)

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.46.122 Chromium: 108.0.5359.48 (Official Build) beta (x86_64)
-- | --
Revision | 18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}
OS | macOS Version 11.7.1 (Build 20G918)

### Steps:
1. installed `1.46.122`
2. launched Brave
3. set up VPN with the default profile
4. created `Profile 2` and switched to it
5. confirmed I was connected to the same default `USA (West)` server
6. switched to `Japan`
7. confirmed I was connected to a Japanese node
8. switched back to default profile/profile 1
9. confirmed I was connected to the same custom-selected `Japan` region's node

USA - West (profile 1) | USA - West (profile 2)
-----------------------|----------------------
<img width="1312" alt="Screen Shot 2022-11-22 at 9 09 58 AM" src="https://user-images.githubusercontent.com/387249/203379659-83f41458-a66f-4b81-a50b-c71e64280097.png"> | <img width="1312" alt="Screen Shot 2022-11-22 at 9 10 19 AM" src="https://user-images.githubusercontent.com/387249/203379689-7369d473-4656-499f-a7fa-edb81245feb2.png">


ipleak.net (profile 2) | ipleak.net (profile 1)
--------------------|---------------------
<img width="1312" alt="Screen Shot 2022-11-22 at 9 13 49 AM" src="https://user-images.githubusercontent.com/387249/203379410-fba34fcd-acd9-48a7-8f57-5a57660e7d8f.png"> | <img width="1312" alt="Screen Shot 2022-11-22 at 9 12 37 AM" src="https://user-images.githubusercontent.com/387249/203379488-c36bc1b8-4ae4-40f6-870f-026dc230fc21.png">
