### ISSUE TITLE
Remove Rewards extension 

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#25792]
## Description

Given https://github.com/brave/brave-browser/issues/22423, remove remaining code and flags for using the Rewards extension and depend entirely on the new WebUI Rewards panel.

**Comment by LaurenWags** [comment]
@Miyayes @zenparsing since this one is labelled `QA/Yes`, a test plan is needed.

Labelling as `QA/Blocked` until there is one.

cc @kjozwiak @rebron

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.47.119 Chromium: 108.0.5359.99 (Official Build) beta (x86_64)
-- | --
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | macOS Version 12.6.1 (Build 21G217)
```

Verified test plan from https://github.com/brave/brave-browser/issues/25792#issue-1396389414.

Compared `1.46.140` and `1.47.119`. Confirmed 1.47.x version does not contain the webUI flag.
Confirmed able to pinch zoom in webUI panel on 1.47.x, but not 1.46.x.

`1.46.140` | `1.47.119`
---- | ----
<img width="1188" alt="Screen Shot 2022-12-08 at 5 02 40 PM" src="https://user-images.githubusercontent.com/28145373/206577957-023fd4c4-ef41-46e0-90eb-06ba38945785.png"> | <img width="1191" alt="Screen Shot 2022-12-08 at 4 57 48 PM" src="https://user-images.githubusercontent.com/28145373/206576428-6645a006-6297-4b3b-8229-9a7f0c97eafb.png">
<img width="1192" alt="Screen Shot 2022-12-08 at 5 03 21 PM" src="https://user-images.githubusercontent.com/28145373/206577857-022a334f-f2fe-4779-a702-caba61457d65.png"> | <img width="1199" alt="Screen Shot 2022-12-08 at 5 01 47 PM" src="https://user-images.githubusercontent.com/28145373/206577856-4352c745-6818-4641-9aa7-a82026ce9b81.png">
