### ISSUE TITLE
Cannot login to vpn

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#25793]
## Description 

Seeing infinite payment requests

https://user-images.githubusercontent.com/2965009/193847498-5cf1a395-2108-4aeb-82a2-31778967cf32.mp4

## Steps to Reproduce

   1. Try to login to vpn on dev env

## Actual result:

- login failed

## Expected result:

- login success

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by spylogsster** [comment]
Reverting this change fixes it, https://github.com/brave/brave-core/pull/15292/files#diff-7150adfa3b679ee58d52bb8ff9b958c1dfaf8259dd560b2c28b5b2390c5ed51eR37,
cc @antonok-edm

**Comment by spylogsster** [comment]
cc @bsclifton @rebron

**Comment by antonok-edm** [comment]
cc @evq who added the dependency originally

**Comment by bsclifton** [comment]
@spylogsster I'm on Windows also and I ran fresh `npm run sync` against master (using Nightly seems fine too). And it appears to be working as-is

Were there any updates @antonok-edm @evq?

**Comment by antonok-edm** [comment]
@bsclifton looks like it was unrelated after all and https://github.com/brave/brave-core/pull/15435 will solve it

**Comment by bsclifton** [comment]
@srirambv I wonder if this is what you ran into with https://github.com/brave/brave-browser/issues/25887?

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
Brave | 1.46.126 Chromium: 108.0.5359.48 (Official Build) beta (64-bit)
-- | --
Revision | 18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}
OS | Windows 10 Version 21H2 (Build 19044.2251)

```
Verified the issue in staging env as discussed in the slack thread https://bravesoftware.slack.com/archives/CC5SA8CCB/p1669641355738889?thread_ts=1669362761.508539&cid=CC5SA8CCB 

- Confirmed click on `Buy Now` opens up the purchase vpn page
- Confirmed user can purchase VPN in staging environmnet
- Confirmed user can connect the Brave VPN 

![image](https://user-images.githubusercontent.com/38657976/204294935-5ee6d56a-ca1a-4eb4-b229-0e320206ee5c.png)

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
Brave | 1.46.126 Chromium: 108.0.5359.48 (Official Build) beta (64-bit)
-- | --
Revision | 18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}
OS | Windows 10 Version 21H2 (Build 19044.2251)

```
Verified the issue in staging env as discussed in the slack thread https://bravesoftware.slack.com/archives/CC5SA8CCB/p1669641355738889?thread_ts=1669362761.508539&cid=CC5SA8CCB 

- Confirmed click on `Buy Now` opens up the purchase vpn page
- Confirmed user can purchase VPN in staging environmnet
- Confirmed user can connect the Brave VPN 

![image](https://user-images.githubusercontent.com/38657976/204294935-5ee6d56a-ca1a-4eb4-b229-0e320206ee5c.png)

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.46.129 Chromium: 108.0.5359.48 (Official Build) (x86_64)
-- | --
Revision | 18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}
OS | macOS Version 11.7.1 (Build 20G918)

### Steps:

1. deleted prior `BraveVPN` OS-config, first
2. installed `1.46.129`
3. launched Brave using `--vmodule="*/skus/*"=2 --enable-logging=stdrr --v=1`
4. clicked `Maybe later`
5. clicked `Skip welcome tour`
6. opened `brave://flags`
7. set `brave://flags/#brave-vpn to Enabled`
8. clicked `Relaunch`
9. clicked `No thanks` on the `Tired of cookie consent notices?` dialog
10. loaded `account.bravesoftware.com`
11. entered staging credentials from `1Password`
12. entered a unique email address: `issue25793@mailinator.com`
13. clicked `Get login` link
14. opened the `Log in to your Brave Pre...` email (`https://www.mailinator.com/v4/public/inboxes.jsp?to=issue25793` in the above case)
15. clicked on the `Log in to Brave` button
16. clicked `Browse plans` on `https://account.bravesoftware.com/account/`
17. scrolled down
18. clicked on `Buy now` beneath `Brave VPN Subscription`
19. completed the Stripe checkout using `https://stripe.com/docs/testing#testing-interactively`
20. clicked on the `VPN` button in the browser toolbar, and attempt to add and connect to the `BraveVPN` config

example | example | example | example | example
---------|----------|---------|----------|---------
<img width="1150" alt="Screen Shot 2022-11-28 at 4 04 44 PM" src="https://user-images.githubusercontent.com/387249/204407018-24fd7085-babb-410b-b250-efcedde1c376.png"> | <img width="1399" alt="Screen Shot 2022-11-28 at 4 05 24 PM" src="https://user-images.githubusercontent.com/387249/204407025-795247e3-b0de-4043-8d3b-46f3f0af17e5.png"> | <img width="1399" alt="Screen Shot 2022-11-28 at 4 05 29 PM" src="https://user-images.githubusercontent.com/387249/204407035-af2e1da5-cf79-4962-974b-2c4780cd3817.png"> | <img width="1288" alt="Screen Shot 2022-11-28 at 4 06 21 PM" src="https://user-images.githubusercontent.com/387249/204407036-e5839675-c5ae-46c6-ad17-46477c16ae09.png"> | <img width="1282" alt="Screen Shot 2022-11-28 at 4 07 01 PM" src="https://user-images.githubusercontent.com/387249/204407041-d257d1a1-d175-4920-a7a9-91ed243e1e2c.png">
