### ISSUE TITLE
Content on WSHH is Unreachable

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#25809]
WARNING: The domain listed below may contain sensitive/mature material. The example link provided, however, is just a clip of comedian/actor Kevin Hart reacting to his own high school basketball games.

## Description 

Videos on worldstarhiphop.com may not display properly, if at all. Instead, the following is displayed:

```
Application error: a client-side exception has occurred (see the browser console for more information).
```

Corresponding console entries are as follows (original, full, expanded screenshot at the bottom of this issue):

```
08:23:21.996 _app-b851d3e8e8a70eb8.js:1 👉👉👉 ANAInstance is:  Object
08:23:22.220 467.1d4f2c71f581c184.js:1 [👁 VideoV2 👁] window.videojs Object
08:23:22.288 109.1d8662b947d4d31c.js:1 [ANAInstantiatorDesktop] ANA.createdGoogleSlots:  Array(6)
08:23:22.288 _app-b851d3e8e8a70eb8.js:1 👉👉👉 ANAInstance is:  Object
08:23:22.302 369.7614c9fd2b97f556.js:1 [👉canAutoplay👉] MUTED autoplay supported: FALSE for device with specs:  Object
08:23:22.306 467.1d4f2c71f581c184.js:1 [👁 VideoV2 👁] player is ready:  Object
08:23:22.318 369.7614c9fd2b97f556.js:1 [👉canAutoplay👉] MUTED autoplay supported: FALSE for device with specs:  Object
08:23:22.321 369.7614c9fd2b97f556.js:1 [👉canAutoplay👉] MUTED autoplay supported: FALSE for device with specs:  Object
08:23:22.326 _app-b851d3e8e8a70eb8.js:1 👉👉👉 ANAInstance is:  Object
```

## Steps to Reproduce
1.  Go to https://worldstar.com/video/wshh82aKM5QfLcO3M1IE/kevin-heart-reacts-to-his-high-school-basketball-highlights

## Actual result:
User is shown an error message.

## Expected result:
User is shown the video they requested.

## Reproduces how often: 
Easily.

## Brave version (brave://version info)
1.44.105 Chromium: 106.0.5249.91 (Official Build) (64-bit) 

## Version/Channel Information:
- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

![image](https://user-images.githubusercontent.com/815158/194072913-f170f6b2-47bc-4f2f-8cd5-9abc93b748cd.png)

**Comment by rebron** [comment]
cc: @ryanbr

**Comment by ryanbr** [comment]
@jonathansampson  I was able to play the Kevin Heart video here, is that the issue specifically?
![kevinhart](https://user-images.githubusercontent.com/1659004/194697472-9214b03a-783f-427f-84a1-2e062e6b5386.png)

**Comment by jonathansampson** [comment]
@ryanbr When I was attempting to repro, I would get the working page *sometimes*, but the error message *most of the time*. It could be that WSHH is doing a bit of A/B testing on their end.

**Comment by SheldonPatnett** [comment]
This is occurring on all bowers across many different platforms for this site.
