### ISSUE TITLE
Brave backgrounds are empty at the very first time

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#25808]
## Steps to Reproduce

   1. Clean your profile
   2. Launch brave
   3. Skip welcom tour
   4. Click customize -> Brvae background

## Actual result:
![image](https://user-images.githubusercontent.com/5474642/194074831-9bdf5b56-22d7-4ed4-9b50-f7993f45e044.png)

## Expected result:
At least the default one should be visible.

## Reproduces how often: 
Everytime.

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by sangwoo108** [comment]
hi @tony83033 . Do you happen to wannna give it a try?

The fix will would be check if new backgrounds list is empty in updateImages() from brave/components/brave_new_tab_ui/data/backgrounds.ts

**Comment by kjozwiak** [comment]
The above requires `1.45.106` or higher for `1.45.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.45.106 Chromium: 107.0.5304.36 (Official Build) (64-bit)
-- | --
Revision | 2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}
OS | Windows 11 Version 21H2 (Build 22000.1098)
```

- Install 1.45.106
- launch Brave
- click `Skip welcome tour`
- click `Brave backgrounds` tile 

### Confirmed  images are loaded on rotation.

https://user-images.githubusercontent.com/98358127/196753299-be18b3b9-ac08-471c-ac6b-2ebe3f6e6e9c.mp4


Note: this issue is related to https://github.com/brave/brave-browser/issues/25824
