### ISSUE TITLE
Unable to SignTransaction on MagicEden

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#25802]
## Description 

When trying to purchase an NFT on MagicEden, the `signTransaction` call fails due to `solana.disconnect`

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

https://user-images.githubusercontent.com/40611140/193969794-00896f93-95f0-4854-9e05-e712627dd35f.mov

![Screen Shot 2022-10-04 at 9 43 27 PM](https://user-images.githubusercontent.com/40611140/193969806-cac22062-c3a3-4404-8bf3-70b26b7cb53d.png)

**Comment by kjozwiak** [comment]
The above requires `1.44.110` or higher for `1.44.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.45.88 Chromium: 106.0.5249.91 (Official Build) beta (64-bit) 
-- | --
Revision | `fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}`
OS | Linux

- Verified steps from [brave/brave-core#15376](https://github.com/brave/brave-core/pull/15376)
- Verified sign message is shown when trying to buy an NFT on `https://magiceden.io`

![image](https://user-images.githubusercontent.com/17010094/194803885-dd387f14-6e97-452c-b397-594d0cf2057c.png) | ![image](https://user-images.githubusercontent.com/17010094/194803908-9e60585c-1696-453a-8989-03142ab93b47.png)
-- | --

------------------------
Verification passed on

Brave | 1.45.88 Chromium: 106.0.5249.91 (Official Build) beta (64-bit) 
-- | --
Revision | `fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}`
OS | Windows 11 Version 21H2 (Build 22000.978)

- Verified steps from [brave/brave-core#15376](https://github.com/brave/brave-core/pull/15376)
- Verified sign message is shown when trying to buy an NFT on `https://magiceden.io`

![image](https://user-images.githubusercontent.com/17010094/194804049-8d917906-6250-4edf-b2f3-f0571c777d6d.png) | ![image](https://user-images.githubusercontent.com/17010094/194804082-abd6944b-6ba3-4016-8801-3205486460fd.png)
-- | --

------------------------
Verification passed on

Brave | 1.45.88 Chromium: 106.0.5249.91 (Official Build) beta (arm64)
-- | --
Revision | `fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [brave/brave-core#15376](https://github.com/brave/brave-core/pull/15376)
- Verified sign message is shown when trying to buy an NFT on `https://magiceden.io`

![image](https://user-images.githubusercontent.com/17010094/194803534-c7f65b8d-4939-4f83-9765-bf8184f42604.png) | ![image](https://user-images.githubusercontent.com/17010094/194803545-87a5de6c-8119-4cb8-a060-3e25c75461ec.png)
-- | --
