### ISSUE TITLE
Default filter lists are missing

### ISSUE THREAD

**Issue by takomine** [brave/brave-browser#25803]
## Description 

Adblock is not working because the default filter lists are missing in `brave://adblock`
![image](https://user-images.githubusercontent.com/108466107/193981708-8f503671-69b8-4f9d-b2f0-ae1dc99116fd.png)

## Steps to Reproduce

   1.  enter in url bar `brave://adblock`

## Actual result:

![image](https://user-images.githubusercontent.com/108466107/193972504-98c55409-bdc2-4352-af51-36e43c59526d.png)

## Expected result:
There should be lists of checkbox to select filter lists

## Brave version (brave://version info)

1.44.105 Chromium: 106.0.5249.91 (Official Build) (64-bit) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by antonok-edm** [comment]
@takomine:

- is this a fresh install?
- can you check `brave://components` for any entries with `Brave Ad Block` in the name, and list the versions here? Also try pressing `Check for update` on them and see if that helps.

**Comment by takomine** [comment]
>is this a fresh install?

No but I did try to open the installer again (without uninstalling) thinking that it might fix it

>can you check brave://components for any entries with Brave Ad Block in the name, and list the versions here? Also try pressing Check for update on them and see if that helps.

There is no `Brave Ad Block`. Only the updater

![image](https://user-images.githubusercontent.com/108466107/193998982-640f935a-032e-4a26-8c2f-d022e69670ce.png)

**Comment by takomine** [comment]
For some unknown reason, the filter lists came back. I will close this issue now. Tell me if you need logs or something for this issue

![image](https://user-images.githubusercontent.com/108466107/194182438-50e01ffa-bec4-47c6-b5a6-d4c2ea2ec57d.png)
