### ISSUE TITLE
need to put shields down to watch video on Hulu or Amazon Prime

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#2580]
## Description 
With 0.57.18 you need to put shields down to watch a video on Hulu. Allowing Ads and Trackers is not enough.

Note, In 0.56.15 you did not need to put shields down to watch a video on Hulu - I was able to view a video with standard shield configuration.

## Steps to Reproduce

   1. Install 0.57.18
   2. Navigate to Hulu
   3. Install Widevine
   4. Login and try to play a video.

## Actual result:
Unable to play video. Get message below until you put shields down.
![screen shot 2018-12-14 at 7 06 33 pm](https://user-images.githubusercontent.com/28145373/50036098-1b3e0880-ffd4-11e8-8344-da717c8e1de4.png)

## Expected result:
No error message, able to view video. 

## Reproduces how often: 
Easily

## Brave version (brave://version info)

Brave | 0.57.18 Chromium: 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? yes
- Is the issue reproducible on the latest version of Chrome? Using Chrome 71.0.3578.98 and UBlock Origin extension, issue does not reproduce.

### Additional Information
Issue does not reproduce on previous version, 0.56.15

Additionally, with Amazon Prime the issue does not occur on 0.56.15. Note, there is no error message displayed on 0.57.x when trying to view an Amazon Prime video, there is just an endless spinner for me.

**Comment by iefremov** [comment]
@LaurenWags this one is probably fixed together with #2252

**Comment by iefremov** [comment]
@btlechowski Hey, could you please recheck this ticket? I think it should be fixed as well as other CORS-related problems.

**Comment by LaurenWags** [comment]
@iefremov verified I was able to view Netflix, Hulu, and Amazon Prime videos with default shields on using this build:

Brave | 0.58.21 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Mac OS X

**Comment by iefremov** [comment]
Thanks!

**Comment by srirambv** [comment]
This issue should have been part of `0.58.x` based on fix for #2252 and being verified by @LaurenWags.

**Comment by jdgamble555** [comment]
Hulu still does not work.
