### ISSUE TITLE
Brave News Customize 2.0 UI

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#25801]
Now we have a UI & implementation spec for the Brave News API we should implement it behind a flag.

https://www.figma.com/file/SDcE22eeUsV2uc4dy3NwaC/Onboarding?node-id=195%3A66414

@petemill 

## Test Plan:
- Enable the "Enable Brave News v2" flag, if it's not already default enabled
- Open a NTP
- Scroll down and Enable Brave News if it isn't already enabled
- Click Customize
- The new brave news customize experience should show

### Can enable a source
- Click follow on a source
- Verify that the source is now in the left column

### Can unfollow a source
- Click unfollow on a source in the left column
- Verify that the source is no longer in the left column

### Can enable a channel
- Click follow on a channel (e.g. "Cars")
- Verify that the channel is displayed in the left column

### Search
- Search via a site's url
- The expected source is displayed

- Search via a site's name
- The expected source is displayed

**Comment by petemill** [comment]
Added a test plan

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.46.80 Chromium: 107.0.5304.68 (Official Build) beta (x86_64)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | macOS Version 11.7.1 (Build 20G918)

### Enable Brave News v2
<details>

</details>

### Follow sources
<details>

</details>

### Unfollow sources
<details>

</details>

### Follow channel
<details>

</details>


### Unfollow channel
<details>

</details>


### Search
<details>

</details>

**Comment by stephendonner** [comment]
@brave/qa-team some of the issues I've already seen and filed on are likely due to https://bravesoftware.slack.com/archives/CU56GUJ1H/p1666975874847419.  I've covered some good ground, though definitely need to test channels + subscriptions more.

I'm waiting until the push of the backend-server changes from above are live in production, before finishing/retesting.  There's also a pending new locale format change, in https://github.com/brave/brave-core/pull/15681.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.46.102 Chromium: 107.0.5304.110 (Official Build) beta (64-bit)
-- | --
Revision | 2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}
OS | Windows 11 Version 21H2 (Build 22000.1219)
```
Test Case 1:  Click `Show Brave News` and click `Customize`

### Case 1:  Enable Brave News v2 - `PASSED`
<details>

1. installed `1.46.102`
2. launched Brave
3. opened `brave://flags`
4. set `brave://flags/#brave-news-v2` to `Enabled`
5. clicked on `Relaunch`
6. opened a new-tab page
7. scroll down
8. click on `Show Brave News`
9. clicked on `Customize`
10. confirmed I got the v2 UI
11. Brave News button is enabled by default

step 4|step 8|step 10-11
-------|---------|----------
<img width="462" alt="image" src="https://user-images.githubusercontent.com/98358127/200899742-11d383cb-b9c0-4086-a7e5-9dda4c06d733.png">|<img width="466" alt="image" src="https://user-images.githubusercontent.com/98358127/200899926-e5efcbf5-555f-44d1-9150-e82ab5580554.png">|<img width="948" alt="image" src="https://user-images.githubusercontent.com/98358127/200901582-7c43ea62-ee41-4c8f-b93c-c9e2857394bb.png">

**Comment by stephendonner** [comment]
Unsetting `QA/Blocked`, as all required client changes have been uplifted, and backend changed push to production 👍 

@brave/qa-team testing can and should resume; thanks! re: https://github.com/brave/brave-browser/issues/25801#issuecomment-1295368832

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.46.117 Chromium: 107.0.5304.110 (Official Build) beta (64-bit)
-- | --
Revision | 2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}
OS | Ubuntu 18.04 LTS

### Enable Brave News (v2)

#### Enable Brave News v2 in Polish locale- `PASSED`
<details>

Verified `Show Brave News` button is not shown
![image](https://user-images.githubusercontent.com/34715963/202859419-5ab1db7f-24ef-4092-a868-0cd1b45ca586.png)

</details>

#### Enable Brave News v2 through 'Customize' in Polish locale- `FAILED`
<details>

Possible to enable `Brave News` through 'Customize'
![image](https://user-images.githubusercontent.com/34715963/202860085-ef911428-8943-46cc-b4d7-fa465368b969.png)


</details>


#### Enable Brave News (v2) via Brave news opt-in in the new-tab page- `PASSED`
<details>

1. installed `1.46.x`
2. launched Brave
3. opened `brave://flags`
4. set `#brave-news-v2` to `Enabled`
5. clicked on `Relaunch`
6. opened a new-tab page
7. scroll down
8. click on `Show Brave News`
9. clicked on `Customize`
10. confirmed new Brave News (v2)  UI displayed
11. `Brave News button` is enabled by default

![image](https://user-images.githubusercontent.com/34715963/202859856-5c240d5a-0f08-4bd2-867a-9e0d691a83d8.png)
![image](https://user-images.githubusercontent.com/34715963/202859845-97117ec5-0b37-4ff5-97d2-75a7faa0b513.png)



</details>

#### Case 2:  Enable Brave News (v2) via clicking Customize button in the new-tab page- `PASSED`
<details>

1. new profile
2. launched Brave
3. opened `brave://flags`
4. set `brave://flags/#brave-news-v2` to `Enabled`
5. clicked on `Relaunch`
6. opened a new-tab page
7. click `Customize`
8. click `Brave News` in the `Customize Dashboard`
9. click `Turn on `Brave News`
10. confirmed new Brave News (v2)  UI displayed
11. `Brave News` button is enabled

![image](https://user-images.githubusercontent.com/34715963/202859926-5be543e4-ca10-4cf3-ac92-81f96fe9daaa.png)
![image](https://user-images.githubusercontent.com/34715963/202859930-8feeee25-5152-4475-b4e8-61e4b1011e1f.png)


</details>

#### Case 3: Back to Dashboard link via clicking Customize button - `PASSED`
<details>

1. Continue from Case 2: 
   - open a new-tab page
   - clicked on `Customize`
   - click `Brave News` in the `Customize Dashboard`
   - click `Turn on `Brave News`
2. click on `< Back to Dashboard` 
3. returned to `Customize Dashboard` screen

![image](https://user-images.githubusercontent.com/34715963/202859972-0ab0c215-375e-4ad1-a411-88c7010ab5f7.png)
![image](https://user-images.githubusercontent.com/34715963/202859996-d8c1548c-24e5-4f43-9f0f-0ff96541f4bc.png)


</details>

#### Case 4:  Customize Brave News dialog UI - Appearance & UI elements- `PASSED`
<details>

1. new profile
2. launched Brave
3. opened `brave://flags`
4. set `brave://flags/#brave-news-v2` to `Enabled`
5. clicked on `Relaunch`
6. opened a new-tab page
7. click `Customize`
8. click `Brave News` in the `Customize Dashboard`
9. click `Turn on `Brave News`
10. confirmed new Brave News (v2)  UI displayed
11. `Brave News` button is enabled by default
12. click `Follow` on `Fox News` in the `Popular` category
13. click `X` to close the modal
14. click `Brave News`  in the `Customize Dashboard`
15. `Suggestions` category displayed based on earlier selections 
16. Click `View all` for `Popular` and `Suggestions` categories to view all sources
17. Click `Back` to view  Brave news  (v2) UI modal including `Channels`
18. toggle `OFF` `Brave News` to turn off the news feed

![image](https://user-images.githubusercontent.com/34715963/202860491-713706a8-4e68-405a-abbf-8f6825f50ca4.png)
![image](https://user-images.githubusercontent.com/34715963/202860512-7a908f88-2934-4d43-b2c7-c7af080d1bd2.png)
![image](https://user-images.githubusercontent.com/34715963/202860797-f9df9032-18d4-4925-aec9-25aa417f4e46.png)
![image](https://user-images.githubusercontent.com/34715963/202962014-f03870fc-3f6a-45e0-a6ee-b86056135bf7.png)
![image](https://user-images.githubusercontent.com/34715963/202962052-96f3e4c3-d412-4d89-9fc6-b3212098d274.png)
![image](https://user-images.githubusercontent.com/34715963/202962084-ba80eb1a-f58e-4606-a052-bb72c793fe5d.png)
![image](https://user-images.githubusercontent.com/34715963/202962110-8bae7d05-8976-4b33-98fb-592d3c2acae6.png)
![image](https://user-images.githubusercontent.com/34715963/202962135-585af1b8-047d-49d7-a48b-ff6b07bae832.png)


Dark  mode
![image](https://user-images.githubusercontent.com/34715963/202962188-5ec553f7-09c5-4f1b-9b2d-096f8c3b9f8f.png)
![image](https://user-images.githubusercontent.com/34715963/202962223-174a1f47-7ee8-4032-8e61-892ee310984a.png)
![image](https://user-images.githubusercontent.com/34715963/202962241-33878718-1126-4be9-a1bc-ad76ef1ad84c.png)



### Follow/Unfollow Sources

</details>

#### Case 5:  Follow sources - Single Source  `PASSED`
<details>

#### Discover sources
1. new profile
2. enabled brave  news v2 via `brave://flags/#brave-news-v2` 
3. opened a new-tab page
4. clicked on `Show Brave News`
5. confirmed `Newsweek` article is not available
6. clicked `Customize` 
7. searched for `Newsweek` and click `Follow` button  
8. confirmed it appears under the `Following` heading
9. opened a new-tab page
10. confirmed  `Newsweek` articles displayed

![image](https://user-images.githubusercontent.com/34715963/202962436-665ed2c7-f5af-4b0c-a3d1-2a07999b2b5c.png)
![image](https://user-images.githubusercontent.com/34715963/202962461-3e6cf6f6-4820-4314-9d61-2610d892056a.png)
![image](https://user-images.githubusercontent.com/34715963/202962494-fa1245e4-25c2-419c-9b28-c92948171a3d.png)
![image](https://user-images.githubusercontent.com/34715963/202962539-4ab67fd1-b266-49ef-8ff5-2d658fd9ccb4.png)


</details>

####  Case 6:  Follow sources - Multiple Sources  `PASSED`
<details>

#### Discover sources
1. new profile
2. enabled brave  news v2 via `brave://flags/#brave-news-v2` 
3. opened a new-tab page
4. clicked `Customize` 
5. clicked `Brave News`
6. clicked `Turn on Brave News` button
7. searched for `Time`, NPR, `Conde Nast Traveler`, `Delish` and clicked `Follow` button  
8. confirmed it appears under the `Following` heading in the left column
9. opened a new-tab page
10. confirmed articles for   `Time`, NPR, `Conde Nast Traveler `Delish` shown in the Brave news feed

![image](https://user-images.githubusercontent.com/34715963/202962730-8fdf8121-f4db-47b1-bff2-7ab7ffa890d9.png)
![image](https://user-images.githubusercontent.com/34715963/202962799-b9dd967d-20ba-4c5a-a16a-d53c283d46a4.png)
![image](https://user-images.githubusercontent.com/34715963/202962832-d72d998b-2807-4e9e-83a7-f20acaa2088b.png)


</details>

#### Case 7:  Unfollow sources - `PASSED`
<details>

1.  continue from Case 6
    - opened a new-tab page
    - clicked `Customize`
    - multiple sources shown in the `Following` pane in the left column (`NPR`, `Time`, `Conde Nast`, `Delish`
    - articles for `NPR`, `Time`, `Conde Nast` & `Delish `shown in the Brave news feed
2. hovered to the right of your source(s),(`NPR` & `Delish`) in the `Following` column
3. clicked  `Unfollow`
4. clicked the `X` to close the dialog
5. clicked `Load new content` (or  reload your Brave News feed,  or open a new-tab page)
6. scrolled  through and confirm the source(s) have been removed - `NPR` & `Delish`

#### Confirmed `NPR` & `Delish` resources have been removed from `Following` pane and Brave news feed.

![image](https://user-images.githubusercontent.com/34715963/202962908-7f35a949-659f-496b-b80a-db79f77124b5.png)
![image](https://user-images.githubusercontent.com/34715963/202962925-a7a0897c-4a3f-4c6a-b35f-5f89af531a09.png)
![image](https://user-images.githubusercontent.com/34715963/202962956-30e19ccc-5904-408c-96d6-8a7af29ed06e.png)
![image](https://user-images.githubusercontent.com/34715963/202962997-74e9ad09-9863-4d71-9ca6-b13ecca75316.png)


### Follow/Unfollow Channels
![image](https://user-images.githubusercontent.com/34715963/202963535-af844d18-bec0-4586-91f3-a10150e62721.png)
![image](https://user-images.githubusercontent.com/34715963/202963560-8692d02c-a4a8-4105-a800-de325908bb0c.png)


</details>

#### Case 8: Follow Channel - `PASSED`
<details>

1. new profile
2. enabled brave  news v2 via `brave://flags/#brave-news-v2` 
3. opened a new-tab page
4. clicked `Show Brave News` 
5. clicked `Customize`
7. under `Channels`, clicked on `Follow` in `Food`
8. Unfollowed `Top Sources` 
9. clicked the `X` to close the dialog
10. clicked on `Load new content`
11. scrolledl thru the feed
17. confirmed the following articles appeared:
      - Delish
      - Serious Eats

![image](https://user-images.githubusercontent.com/34715963/202963598-da28e5b8-83f6-4e04-b181-f5489669dab6.png)
![image](https://user-images.githubusercontent.com/34715963/202963625-c3c8d344-a3de-455a-a8d2-a16f1ca91b6d.png)
![image](https://user-images.githubusercontent.com/34715963/202963671-926e4d36-bad8-4786-b6d5-a15abc723afe.png)
![image](https://user-images.githubusercontent.com/34715963/202963702-49ce7486-4a00-4616-ba5d-2368e96cef3c.png)



</details>

#### Case 9: Unfollow channel - `PASSED`

<details>

1.  continue from Case 8
    - open a new-tab page
    - clicked `Customize`
    - `Food` channel is available in the `Following` pane
2. clicked `Follow` to follow couple of more channels - `Culture` &  `Travel`
3. hovered to the right of `Food`, & `Travel` and click `Unfollow`
4. confirmed `Food` & `Travel` were no longer subscribed under `Following`
5. clicked on the `X` to dismiss the dialog
6. clicked `Load new content` indicator to reload the content for `Culture` channel (wait for couple of secs for the indicator)
7. verified the Brave News feed for articles from `Culture` 

![image](https://user-images.githubusercontent.com/34715963/202963792-eef592c7-1013-4990-80c1-b3864aab15a7.png)
![image](https://user-images.githubusercontent.com/34715963/202963936-ee1adcf8-3463-4bf1-8f2f-5c8b928b4782.png)
![image](https://user-images.githubusercontent.com/34715963/202963996-8f4ff59a-2885-4536-8c4e-fd50899fe1d7.png)


</details> 

### Search 

#### Case 10:  Search bar - Sub-string searches - `PASSED`
<details>

1. new profile
2. opened a new-tab page
3. clicked `Customize`
4. clicked `Brave News`
5. click `Turn on Brave News`
6. searched for the following:

`Blo` | `com` | `NBC` |  `日本版` | `El Español`
------|-----------|-------|-------|----------
![image](https://user-images.githubusercontent.com/34715963/202964484-2e464ffa-3a9b-4e58-8f6f-031b3899af9d.png)|![image](https://user-images.githubusercontent.com/34715963/202964513-52a426f6-6516-4a09-b848-d8680aa1d38d.png)|![image](https://user-images.githubusercontent.com/34715963/202964531-6226f77a-882a-4da9-943f-378a9d79de70.png)|![image](https://user-images.githubusercontent.com/34715963/202964549-92a2c9d1-564a-4a6d-a219-7d354f01af41.png)|![image](https://user-images.githubusercontent.com/34715963/202964580-9070b8b1-2a90-44c4-a7fc-41a7b2fcdb77.png)


</details>

####  Case 11:  Search via a site's url - `PASSED`
<details>

1. new profile
2. enable brave  news v2 via `brave://flags/#brave-news-v2` 
3. clicked `Customize`
4. clicked `Brave News`
5. clicked `Turn on Brave News`
6. beneath Discover, entered https://blog.mozilla.org/feed/ in the search bar
7. clicked on Get feeds from https://blog.mozilla.org/feed/
8. clicked  `Follow` on `The Mozilla Blog` source to appear on `Following` pane

![image](https://user-images.githubusercontent.com/34715963/202964739-7e13ba91-60ec-423e-b51a-dbb90783beb2.png)
![image](https://user-images.githubusercontent.com/34715963/202964763-8e6e9eed-e06b-407e-ad2f-ef040e0ab39d.png)


</details>

#### Case 12: Search via a site's name - `PASSED`
<details>

1. new profile
2. enable Brave news v2 via `brave://flags/#brave-news-v2` 
3. clicked `Customize`
4. clicked `Brave News`
5. clicked `Turn on Brave News`
6. beneath Discover, enter `wired` in the search bar
7 confirmed all 3 sources returned 
8. clicked `Follow` on all three sources and both shown on the `Following` pane
9. open  new-tab page

![image](https://user-images.githubusercontent.com/34715963/202964851-d6bf19a7-abf8-437b-9eeb-4a00ce2237ca.png)
![image](https://user-images.githubusercontent.com/34715963/202964878-f573bb8b-94a1-4b62-9334-39b268939d82.png)
![image](https://user-images.githubusercontent.com/34715963/202964916-25ad606b-17ca-4be4-9496-e62688476b4d.png)


</details>

#### Case 13: Brave News (v2) for Multiple profiles - `PASSED`
<details>

Profile 1: 
1. new profile
2. enabled Brave news v2 via `brave://flags/#brave-news-v2` 
3. clicked `Customize`
4. clicked `Brave News`
5. clicked `Turn on Brave News`
6. Brave news V2 modal and feed displayed as expected

![image](https://user-images.githubusercontent.com/34715963/202964981-f5c50607-2fdf-40a2-87d5-7f3a87be3ddb.png)


Profile 2:

1. click Hamburger menu>>create a new profile>>profile 2
2. scroll thru new-tab page
3. clicked `Show Brave News`
4. clicked `Customize`
5. Brave News (v2) modal displayed as expected
6. click `Follow` for `Fox news`
7. clicked `X` to close the dialog
8. article links displayed on the Brave News feed as expected

![image](https://user-images.githubusercontent.com/34715963/202965055-3ae5b08f-7416-43f3-8e23-7781cfa8c35b.png)
![image](https://user-images.githubusercontent.com/34715963/202965131-0a035098-822f-4df5-b5a4-dd86a263d897.png)
![image](https://user-images.githubusercontent.com/34715963/202965206-d6b5c62b-809c-48a8-948d-e8b7e5ce7528.png)


</details>

#### Case 14: Upgrade - Brave News (v2) - `PASSED`
<details>

Before Upgrade :

1. Install 1.45.x
2. launched Brave
3. created multiple profiles (i.e. Profile 1 & Profile 2)
4. enabled Brave News on Profile 1
5. do not enable Brave News on Profile  2
6. closed the browser
10. renamed to Beta

Profile 1|Profile 2
----|----
![image](https://user-images.githubusercontent.com/34715963/202965583-1a3de0e8-000b-4100-9e43-738ab5fc76ba.png)


After Upgrade: Profile 1: 

1. open brave://flags
2. enabled`#brave-news-v2` flag
3. clicked `Customize`
4. clicked `Brave News` in the `Customize Dashboard`
5. Brave News (v2) modal displayed as expected
6. followed `TechCrunch` source
7. clicked `X` on both modals and clicked new-tab page
11. Brave news feed displayed as expected including articles for `TechCrunch`

![image](https://user-images.githubusercontent.com/34715963/202965945-637db039-eba1-41f7-a64e-36c7bfb04577.png)
![image](https://user-images.githubusercontent.com/34715963/202965968-a1bfaefd-0f0d-46bb-8f5f-02466a5fd102.png)
![image](https://user-images.githubusercontent.com/34715963/202966020-73717dfa-a8a9-4dfe-b4ed-678e05efb5d0.png)


After Upgrade: Profile 2: 

1. clicked `Show Brave News`
2. clicked `Customize`
3. Brave News (v2) modal displayed as expected
4. click Follow on `Le Monde` 
5. clicked `X` to close the dialog
6. clicked `Load new content` indicator
7. Brave news feed displayed as expected including articles for `LeMonde`

![image](https://user-images.githubusercontent.com/34715963/202965716-a6343379-288e-47fb-b3ac-08291a8823d8.png)
![image](https://user-images.githubusercontent.com/34715963/202965821-670465b3-a223-4f72-8588-b3dbceb2a328.png)
![image](https://user-images.githubusercontent.com/34715963/202965882-cc069d9f-c3c6-4954-9fd8-dd88e61dab9b.png)


</details>
