### ISSUE TITLE
PHI Network Smart Chain Support

### ISSUE THREAD

**Issue by Phinetwork** [brave/brave-browser#25813]
Hello would like to integrate phi smart chain. 

Chain details 

RPC url: connect.phi.network 
Explorer: phiscan.com 
Chain id: 144 

Chainlist.org/chain/144 

Phi network is a high performance evm compatible blockchain built for social entertainment & high performance gaming. A decentralized social entertainment economy. Thank you

**Comment by Phinetwork** [comment]
@rebron is this being integrated

**Comment by jamesmudgett** [comment]
Hi @Phinetwork, this can be done through visiting brave://settings/wallet/networks then adding a new network. The Phi details should auto-populate the form if you begin typing in the "Chain id or name"

**Comment by Phinetwork** [comment]
> Hi @Phinetwork, this can be done through visiting brave://settings/wallet/networks then adding a new network. The Phi details should auto-populate the form if you begin typing in the "Chain id or name"

The price API is wrong gives price of the wrong PHI and it doesn't allow to add custom tokens gives error, ![image](https://user-images.githubusercontent.com/85964511/197375577-42634eba-2e5b-48e2-b1d9-2a4f648d3c3c.png)
