### ISSUE TITLE
Brave Logo not on tab titles

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#25818]
## Description 

At the moment, we don't show the brave logo when you are accessing
<img width="1551" alt="Screenshot 2022-10-05 at 19 15 25" src="https://user-images.githubusercontent.com/12224304/194126816-162afcb5-74ef-47be-a5f2-302eac4515f6.png">
 brave wallet. 
We should add the brave logo but also do it like

[logo] wallet 
[logo] send
[logo] swap
[logo] Brave Wallet (on onboarding)

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.47.39 Chromium: 107.0.5304.91 (Official Build) nightly (64-bit) 
-- | --
Revision | `3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}`
OS | Linux

- Verified steps from [brave/brave-core#15634](https://github.com/brave/brave-core/pull/15634)
- Verified Brave logo is shown on all Wallet routes
- Verified `Buy Crypto` is shown as page title for `brave://wallet/crypto/fund-wallet` 
- Verified `Deposit Crypto` is shown as page title for `brave://wallet/crypto/deposit-funds`
- Encountered [#26406](https://github.com/brave/brave-browser/issues/26406) in light theme

https://user-images.githubusercontent.com/17010094/199719033-8f550835-9974-4804-9c2b-c6bb81547fef.mp4


------------------------
Verification passed on

Brave | 1.47.39 Chromium: 107.0.5304.91 (Official Build) nightly (64-bit)  
-- | --
Revision | `3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}`
OS | Windows 11 Version 22H2 (Build 22621.674)

- Verified steps from [brave/brave-core#15634](https://github.com/brave/brave-core/pull/15634)
- Verified Brave logo is shown on all Wallet routes
- Verified `Buy Crypto` is shown as page title for `brave://wallet/crypto/fund-wallet` 
- Verified `Deposit Crypto` is shown as page title for `brave://wallet/crypto/deposit-funds`
- Encountered [#26406](https://github.com/brave/brave-browser/issues/26406) in light theme

https://user-images.githubusercontent.com/17010094/199714890-61ceb303-0378-4108-8524-0beb4f2ff4db.mp4


------------------------
Verification passed on

Brave | 1.47.39 Chromium: 107.0.5304.91 (Official Build) nightly (arm64)
-- | --
Revision | `3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#15634](https://github.com/brave/brave-core/pull/15634)
- Verified Brave logo is shown on all Wallet routes
- Verified `Buy Crypto` is shown as page title for `brave://wallet/crypto/fund-wallet` 
- Verified `Deposit Crypto` is shown as page title for `brave://wallet/crypto/deposit-funds`
- Encountered [#26406](https://github.com/brave/brave-browser/issues/26406) in light theme

https://user-images.githubusercontent.com/17010094/199720088-17c9635b-aac8-479f-a3c6-92b4610fd636.mov
