### ISSUE TITLE
Remove NTPSI section in Customize Dashboard when policy is in place - Follow up to 25151

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#25812]
## Description 

Found while testing #25151 

When policy is in place to disable Brave Rewards, we need to decide what to do with NTP SI. Particularly the "Start using Rewards" button but potentially the whole UI around this on the "Customize Dashboard" settings area.

See https://bravesoftware.slack.com/archives/CB0KCRCQN/p1664977942843319 for items/further discussion.

## Solution 

- [ ] Hide whole SI section in the NTP customization modal when policy is active (given that NTPSIs won't show at all when policy is active)
- [ ] ~Remove the little popup/CTA in bottom left corner when user first sees NTPSI when policy is active~ (no longer relevant given that NTPSIs won't show at all when policy is active)
- [ ] ~Make sure NTPSIs are still visible when policy is active~ (per @rebron and @jsecretan) 

## Steps to Reproduce

1. Follow steps from #25151 to set up policy to disable Brave Rewards
2. Visit Customize Dashboard on NTP

## Actual result:

<img width="747" alt="Screen Shot 2022-10-05 at 10 02 35 AM" src="https://user-images.githubusercontent.com/28145373/194081330-02c56c38-b563-4b45-8af8-e28928c99b0f.png">

## Expected result:

TBD based on discussion in above thread - @Miyayes to provide specifics

## Reproduces how often: 

easily

## Brave version (brave://version info)

```
Brave | 1.45.85 Chromium: 106.0.5249.91 (Official Build) beta (x86_64)
-- | --
Revision | fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}
OS | macOS Version 12.6 (Build 21G115)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? 1.45.x yes
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
cc: @sangwoo108

**Comment by kjozwiak** [comment]
The above requires `1.45.91` or higher for `1.45.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (64-bit)
-- | --
Revision | 182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}
OS | Windows 10 Version 21H2 (Build 19044.2006)

```
- Verified the STR from the https://github.com/brave/brave-browser/issues/25812#issue-1397859933
