### ISSUE TITLE
Backend support for running DiscoverAssets on page refresh

### ISSUE THREAD

**Issue by nvonpentz** [brave/brave-browser#25820]
Currently the asset discovery logic is run when new accounts are added.  With this approach we will not discover tokens sent to the user after they have added their account.  Instead we should run asset discovery when the user refreshes the page, and have a message on pending response for auto-discovery cycle. Then throttle it to only call once every X minutes.

That way we will discover new assets, as well as discover assets for accounts added prior to the asset discovery feature.

**Comment by yrliou** [comment]
Resolved by https://github.com/brave/brave-core/pull/15707

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.47.167 x64 build
- Verified test plan from [brave/brave-core#13295](https://github.com/brave/brave-core/pull/13295)
- Verified restoring a wallet via seed shows all tokens that have balance across all accounts
- Verified restoring an account via private key also restores/shows all tokens from that account in addition to already visible tokens
- Verified on a clean wallet only Ethereum and BAT are listed as expected and no other tokens are listed

---------
Verification passed on Lenovo Tab with Android 12 running 1.47.167 x64 build
- Verified test plan from [brave/brave-core#13295](https://github.com/brave/brave-core/pull/13295)
- Verified restoring a wallet via seed shows all tokens that have balance across all accounts
- Verified restoring an account via private key also restores/shows all tokens from that account in addition to already visible tokens
- Verified on a clean wallet only Ethereum and BAT are listed as expected and no other tokens are listed
