### ISSUE TITLE
Brave background images are not loading for the very first tab some times

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#25823]
## Steps to Reproduce

1. installed 1.45.87
2. launched Brave
3. clicked `Skip welcome tour` link
4. clicked on Customize
5. clicked on Brave Backgrounds

## Actual result:

Images are not loading after clicking on Brave background tile.  Had to refresh the page to view images
ex1|ex2
---|---
<img width="948" alt="image" src="https://user-images.githubusercontent.com/98358127/194180971-9e7b93ce-e7d1-4ddf-a1b9-12eaadf13dd5.png">|<img width="948" alt="image" src="https://user-images.githubusercontent.com/98358127/194181112-bb9bd327-4773-44a6-8d21-205d84f50935.png">

## Expected result:
Brave background images should load as expected as other NTP

## Reproduces how often: 

intermittent

## Brave version (brave://version info)

```
Brave | 1.45.87 Chromium: 106.0.5249.91 (Official Build) beta (64-bit)
-- | --
Revision | fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}
OS | Windows 11 Version 21H2 (Build 22000.978)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel?  Yes
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@sangwoo108 @rebron

**Comment by sangwoo108** [comment]
We'll hide this UI : https://github.com/brave/brave-browser/issues/25824#issuecomment-1271754138

**Comment by kjozwiak** [comment]
Labelling as `QA/No` as this will be verified/checked via https://github.com/brave/brave-browser/issues/25808 which was created first 👍
