### ISSUE TITLE
Unable to toggle `OFF`  for `Refresh on every new tab` in the Dashboard 

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#25824]
## Steps to Reproduce

 1. installed 1.45.87
2. launched Brave
3. open a NTP
4. clicked on `Customize`
5. clicked on Brave Backgrounds
6. click on a image
7. toggle `ON` for `Refresh on every new tab`
8. Do not select an image 
9. toggle `OFF` `Refresh on every new tab`

## Actual result:

Unable to toggle `OFF` 

https://user-images.githubusercontent.com/98358127/194183318-5537d73a-7168-4953-a535-90ec67cc2851.mp4

## Expected result:
toggle  ON/OFF should work as expected

## Brave version (brave://version info)

```
Brave | 1.45.87 Chromium: 106.0.5249.91 (Official Build) beta (64-bit)
-- | --
Revision | fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}
OS | Windows 11 Version 21H2 (Build 22000.978)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@sangwoo108 @rebron

**Comment by rebron** [comment]
@sangwoo108 Reminder for this one that with Brave backgrounds, we'll only want users to be able to select Brave backgrounds and not anything else in terms of a sing e Brave background, rotation or not.

It doesn't look like refresh is an issue with custom uploaded images, colors or gradients.

**Comment by sangwoo108** [comment]
@rebron Yep, just as we talked from Slack. I'm on it. 

@MadhaviSeelam , we're going to remove ability to select a specific brave background and toggle on rotation. So clicking "Brave backgrounds" has no any deeper UI, it'll be checked and that's all.

![image](https://user-images.githubusercontent.com/5474642/194683284-829ad8e1-572a-4467-994f-c564e9bcf2e0.png)

**Comment by kjozwiak** [comment]
The above requires `1.45.106` or higher for `1.45.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.45.106 Chromium: 107.0.5304.36 (Official Build) (64-bit)
-- | --
Revision | 2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}
OS | Windows 11 Version 21H2 (Build 22000.1098)
```

- installed 1.45.106
- launched Brave
- clicked to open NTP
- clicked on Customize

Case 1: `Show Background Images` toggle `ON` as a default

- Brave background tile was checked as a default
- clicked on `Brave Backgrounds` tile

### Confirmed images are loaded on rotation when clicked after an image loaded

bg image 1|bg image 2|bg image 3
-----|----|-----
<image width="900" alt="image1" src="https://user-images.githubusercontent.com/98358127/196739649-9104033b-d5f6-440a-873a-acdda558e3c1.png">|<image width="900" alt="image1" src="https://user-images.githubusercontent.com/98358127/196739658-86a352fb-aa51-468f-8ffb-1e1c2fca78cf.png">|<image width="900" alt="image1" src="https://user-images.githubusercontent.com/98358127/196740463-9d820c99-3509-44b9-8368-5dcca0500c99.png">


Case 2: `Show Background Images` toggle `OFF` 

- toggle `OFF` `Show Background Images`

### Confirmed No `Brave background` images are shown

![image](https://user-images.githubusercontent.com/98358127/196740546-078bd733-266d-4aa3-a7f8-432eb7f9ed7b.png)
