### ISSUE TITLE
[Android] Default search engine for private tabs does not update without closing all private tabs

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#25821]
## Description 
When a user changes the default search engine for private tabs. The default search engine does not change until the user closes out all private tabs.

Review mentioning issue: https://appfigures.com/reviews/266342430751LVjJf0SHmdOIHzSlmlHw4YQ?lang=en

## Steps to Reproduce

   1. Open a private tab.
   2. Search for something.
   3. Change the default search engine for private tabs (Settings -> Search engines -> Private Tab).
   4. Navigate back to existing private tab OR open a new private tab.
   5. Search for something.

## Actual result:
Search opens in old default search engine.

## Expected result:
Search opens in new default search engine - the search engine selected in step 3 above.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
1.44.105

## Version/Channel Information:
Current release

### Video
https://user-images.githubusercontent.com/28269287/194148980-8c2ad97f-88e9-4918-9557-96d5be345dd0.MOV

**Comment by Uni-verse** [comment]
In progress on Samsung Galaxy S21 & Samsung Galaxy Tab S7 on version:

Brave	1.47.165 Chromium: 109.0.5414.80 (Official Build) (64-bit) 
Revision	0f69b168d36a06cace4365e9f029fa987afa5633-refs/branch-heads/5414@{#1178}
OS	Android 12; Build/SP1A.210812.016
