### ISSUE TITLE
Tab close buttons are sometimes incorrectly shaped (not round) in Windows 11 when video is playing

### ISSUE THREAD

**Issue by urbenlegend** [brave/brave-browser#25825]
## Description 

When playing video content inside a Brave tab, the tab close buttons take on an incorrect shape when hovered over. The upper-left corner looks rectangular, making the entire button not perfectly round. So far I've been able to reproduce the issue with any Youtube, Vimeo, or Google Drive video. The window has to be **non-maximized**. Also, I believe it is a Windows 11 specific bug as I do not see it on my Linux machine. I have not tested Mac or Windows 10 however.

## Steps to Reproduce

   1. Open a new Brave window in Windows 11. Do not maximize the window. The bug will not occur when the window is maximized.
   2. Create two tabs.
   3. Open up a Youtube video in one tab and start playback.
   4. Hover over the tab close buttons of both tabs.
   5. Notice that the close button isn't perfectly round.
   6. Close the video
   7. Hover over the close button of the remaining tab.
   8. Notice that the close button is perfectly round, as it should be.

## Actual result:

![image](https://user-images.githubusercontent.com/241316/194183056-7e7920c7-1565-4f45-b635-76ed54ce4a9b.png)

## Expected result:
![image](https://user-images.githubusercontent.com/241316/194183614-f1314aa4-c8a6-4245-9ea7-f0c17d95d20e.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

1.44.105 Chromium: 106.0.5249.91 (Official Build) (64-bit) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Not tested
- Can you reproduce this issue with the nightly channel? Not tested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by rebron** [comment]
@urbenlegend Nice catch.

**Comment by urbenlegend** [comment]
With the new theme changes, this no longer happens. Great work!
