### ISSUE TITLE
Amazon-cleaned URLs aren't actually cleaned of query params/strings

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#25822]
## Description 

Amazon-cleaned URLs aren't actually cleaned of query params/strings

Spun off from https://github.com/brave/brave-browser/issues/23315.

## Steps to Reproduce

   1. install `1.45.87`
   2. launch Brave
   3. load `https://www.amazon.com/Echo-Dot/dp/B07FZ8S74R/ref=sr_1_1?crid=1JM4ODN4MKLZO&keywords=alexa+echo&qid=1654644603&sprefix=alexa%2Caps%2C136&sr=8-1`
   4. either context-click in the URL bar or click on the `Share this page` icon in the URL bar
   5. choose `Copy clean link (only main URL)`
   6. paste and look at the link

## Actual result:

"Cleaned" URL still is: `https://www.amazon.com/Echo-Dot/dp/B07FZ8S74R/ref=sr_1_1?crid=1JM4ODN4MKLZO&keywords=alexa+echo&qid=1654644603&sprefix=alexa%2Caps%2C136&sr=8-1`

<img width="1312" alt="Screen Shot 2022-10-05 at 5 24 59 PM" src="https://user-images.githubusercontent.com/387249/194166854-8f916f04-7182-4d89-b2d2-12c22767c5cb.png">

## Expected result:

Cleaned URL should be: `https://www.amazon.com/dp/B07FZ8S74R/`

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.45.87 Chromium: 106.0.5249.91 (Official Build) beta (x86_64)
-- | --
Revision | fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}
OS | macOS Version 11.7 (Build 20G817)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Miscellaneous Information:

cc @fmarier @spylogsster

**Comment by spylogsster** [comment]
There are no rules for amazon or any other appropriate for this url, @fmarier mind to update it?

**Comment by stephendonner** [comment]
> There are no rules for amazon or any other appropriate for this url, @fmarier mind to update [server json](https://github.com/brave/adblock-lists/blob/master/brave-lists/clean-urls.json)?

Shouldn't that have been caught in review?  It was one of the first examples listed.

**Comment by spylogsster** [comment]
@stephendonner we agreed to keep list empty for some time, @fmarier wanted to fill it later

**Comment by fmarier** [comment]
Apologies @stephendonner for not updating the original issue to make the current coverage clear. In the initial list, we added the Google `utm_*` parameters and then two Twitter-specific ones. Those should work fine. At the moment, there are no rules for cleaning Amazon URLs and so the expected "clean" URL is the original URL.

We should add rules to clean the Amazon params that we can, but it's not a bug in this feature, rather it's an example of something that's missing in our list.
