### ISSUE TITLE
Too many decimals added when a pre-set value is selected

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#25833]
## Description 

Too many decimals added when a pre-set value is selected

## Steps to Reproduce

   1. Select a token in Send/Swap
   2. Click on a preset value 
   3. If the value is too low it adds more decimals than what the token contract specifies

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/194220418-7098db53-862a-4de9-8643-8fbf0fab7151.png)

## Expected result:
Only add max decimal values allowed for the token

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html><head></head>
<body>

Brave | 1.46.35 Chromium: 106.0.5249.91 (Official Build) nightly (64-bit)
-- | --
Revision | `fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}`
OS | Windows 11 Version 22H2 (Build 22623.730)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @onyb @jamesmudgett @Douglashdaniel

**Comment by Douglashdaniel** [comment]
Was an issue in Wallet `V1` closing as `Invalid`
