### ISSUE TITLE
Set  fixed_asset_type and fixed_network for Sardine

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#25839]
A user is able to change the token from the Sardine UI which means that the wallet address becomes incompatible
Sardine team recommends adding `fixed_asset_type` and `fixed_network` so the user is unable to pick a different token than the one they chose within your picker.

**Comment by kjozwiak** [comment]
The above will require `1.44.110` or higher for `1.44.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.44.110 Chromium: 106.0.5249.103 (Official Build) (64-bit)
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | Windows 11 Version 22H2 (Build 22623.741)

- Verified steps from PR
- Verified `/?fixed_network=<network_name>` is passed as a query parameter to the landing page causing it not to change token
- Verified for both Ethereum & Solana 


https://user-images.githubusercontent.com/17010094/195282191-c2dbb6a6-7cf3-4b9c-8104-068f2a5e6cd0.mov
