### ISSUE TITLE
keyboard shortcut ctrl + L doesn't work

### ISSUE THREAD

**Issue by alanjacobmathew** [brave/brave-browser#25836]
## Description 

Keyboard shortcut to jump to address bar `ctrl + L` doesn't work. The other shortcuts for the same `Alt + d or F6` does work as expected.

## Steps to Reproduce

   1.  use shortcut keys ctrl + L
   2. 
   3. 

## Actual result:

Browser stays as the same. Nothing happens
## Expected result:
Jump to address bar

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

```
1.44.105 Chromium: 106.0.5249.91 (Official Build) (64-bit) 
fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}
Windows 10 Version 21H1 (Build 19043.2006)
```
It's not a new issue related just with this version.

## Version/Channel Information:

- Can you reproduce this issue with the current release?  Yes
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  No
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
 https://support.brave.com/hc/en-us/articles/360032272171-What-keyboard-shortcuts-can-I-use-in-Brave

**Comment by chbroecker** [comment]
I am on: 

Brave | 1.44.105 Chromium: 106.0.5249.91 (Official Build) (64-bit)
-- | --
Revision | fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}

(same version as you) but on Ubuntu 22.04 and I do not have this issue. `Ctrl` + `L` works for me.

**Comment by alanjacobmathew** [comment]
Closing the issue as it was a conflict with Bitwarden extension. BW by default uses `Ctrl` + `L` key to lock the extension.
Removing the extension, or changing the key at `brave://extensions/shortcuts` solves the issue.

**Comment by iddm** [comment]
It doesn't work when in fullscreen mode. Should I open a new issue?
