### ISSUE TITLE
Add Copy clean links to links in pages

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#25845]
When solving the feature https://github.com/brave/brave-browser/issues/23315 with https://github.com/brave/brave-core/pull/14763 we have (on the context menu), `Copy clean link (only main URL)` for url bar, need to add same for any hyperlink in the renderers

**Comment by kjozwiak** [comment]
Removing from `1.46.x` as https://github.com/brave/brave-core/pull/15384 hasn't landed yet and the above isn't labelled as `release/blocking`. Once https://github.com/brave/brave-core/pull/15384 has been fixed, this issue should be moved into the `Nightly` milestone which will most likely be `1.47.x` and then an uplifted created for `1.46.x`. Once uplifted, the release team will change the milestones from` 1.47.x` -> `1.46.x` 👍

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS

```

Brave | 1.47.126 Chromium: 108.0.5359.99 (Official Build) beta (64-bit)
-- | --
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | Windows 10 Version 21H2 (Build 19044.2251)

```
