### ISSUE TITLE
Portfolio: Add hover feedback on the asset list

### ISSUE THREAD

**Issue by kleantzogu** [brave/brave-browser#25848]

**Comment by kleantzogu** [comment]
Figma: https://www.figma.com/file/CPUOGNxaQXHheUMoucwQFN/Portfolio?node-id=982%3A35156

![Image](https://user-images.githubusercontent.com/2451237/194881571-3e1bdf32-9d7a-41ed-b68a-fba942d667fe.png)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (64-bit) 
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | Linux

- Verified steps from [brave/brave-core#15466](https://github.com/brave/brave-core/pull/15466)
- Verified hover state is shown on asset list
- Verified on both dark and light theme

https://user-images.githubusercontent.com/17010094/198261381-5ec3b56a-8580-4452-a9d7-ac37c5d61c18.mp4

------------------------
Verification passed on

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (64-bit) 
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | Windows 11 Version 22H2 (Build 22621.674)

- Verified steps from [brave/brave-core#15466](https://github.com/brave/brave-core/pull/15466)
- Verified hover state is shown on asset list
- Verified on both dark and light theme

https://user-images.githubusercontent.com/17010094/198261147-e34db53a-e138-4138-9d34-de8cb72fc5a9.mp4


------------------------
Verification passed on

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (arm64)
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#15466](https://github.com/brave/brave-core/pull/15466)
- Verified hover state is shown on asset list
- Verified on both dark and light theme

https://user-images.githubusercontent.com/17010094/198261745-efa8f03a-42b9-4b02-80cb-faeda8edc7f7.mov
