### ISSUE TITLE
Same-site debouncing restriction should be based on eTLD+1

### ISSUE THREAD

**Issue by pilgrim-brave** [brave/brave-browser#25859]
Currently we don't debounce a link if two hops in the chain have the same origin.  This should be expanded to be eTLD+1 matches, not just origin.

For example, currently this chain is _not_ debounced in Brave:

> from.example -> a.click.example/bounce -> a.click.example/dest

bc /bounce and /dest share the origin.

However, this chain _would_ be debounced:

> from.example -> a.click.example/bounce -> b.click.example/dest

The correct behavior is for neither of the above redirect chains to be debounced

**Comment by kjozwiak** [comment]
Labelled as `QA/No` after discussing the above with @pes10k and @pilgrim-brave via the Slack thread that @LaurenWags started.
