### ISSUE TITLE
[hackerone] Disable block element picker in private sessions

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#25858]
https://hackerone.com/reports/1726268

credit: [xiaoyinl](https://hackerone.com/xiaoyinl)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.46.56 Chromium: 106.0.5249.119 (Official Build) nightly (64-bit)
-- | --
Revision | 9f2101830b56fd2ea1408287f6c74e253ebcb7c6-refs/branch-heads/5249@{#797}
OS | Windows 11 Version 21H2 (Build 22000.1098)
```

- Install 1.46.56
- launch Brave

Normal Window
------------------
- open Normal window 
- visit a website (https://cnn.com)
- right click to open context menu
- click `Brave`-->`Block element` 

#### Confirmed `Block element` is enabled and able to block page element 

![image](https://user-images.githubusercontent.com/98358127/195731808-d98ef916-1a50-4b6a-a4c0-a98c2227ea8d.png)

Private Window
------------------
- open Private window 
- visit a website (https://cnn.com)
- right click to open context menu
- scroll down to `Brave`-->`Block element`

#### Confirmed `Block element` is disabled 

![image](https://user-images.githubusercontent.com/98358127/195732105-c813f7da-62cb-4aa9-9854-170acebca915.png)

Private window with TOR
-----------------
- open private window with TOR 
 - visit a website (https://cnn.com)
- right click to open context menu
- scroll down to `Brave`-->`Block element` 

#### Confirmed `Block element` is disabled 

![image](https://user-images.githubusercontent.com/98358127/195732535-728b2a51-4d4b-459d-9b8a-1129f155d902.png)

Guest window 
----------
- open Guest window
- visit a website (https://cnn.com)
- right click to open context menu
- scroll down to `Brave`-->`Block element` 

#### Confirmed `Block element` is disabled 

![image](https://user-images.githubusercontent.com/98358127/195733009-05650135-ef58-4d0f-8656-9093b4dc32fb.png)

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.46.76 Chromium: 107.0.5304.62 (Official Build) beta (x86_64)
-- | --
Revision | 1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942}
OS | macOS Version 11.7 (Build 20G817)

### Steps:
1. installed `1.46.76`
2. launched Brave
3. loaded `cnn.com` in each of the following window types: Normal, Private, Private w/Tor, and Guest
4. context-clicked on the largest image

### Confirmed `Brave` -> `Block element` is disabled in all window types except for `Normal`:

`Normal window` | `Private window` | Private w/Tor | Guest window
----------------|----------------|---------------|-------------
<img width="807" alt="Screen Shot 2022-10-24 at 12 25 25 PM" src="https://user-images.githubusercontent.com/387249/197609664-a9375a37-9d47-4513-9507-c07c348147bc.png"> | <img width="805" alt="Screen Shot 2022-10-24 at 12 26 34 PM" src="https://user-images.githubusercontent.com/387249/197609668-714b4ad8-4dc6-484b-98d1-51205d1ff472.png"> | <img width="807" alt="Screen Shot 2022-10-24 at 12 27 48 PM" src="https://user-images.githubusercontent.com/387249/197609670-99dfd6fe-c466-4258-af25-f5124db784a6.png"> | <img width="805" alt="Screen Shot 2022-10-24 at 12 28 21 PM" src="https://user-images.githubusercontent.com/387249/197609673-d4083f71-bab6-4e26-9871-537b8bb00585.png">

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.46.106 Chromium: 107.0.5304.110 (Official Build) beta (64-bit) 
Revision	2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}
OS	Linux
```

**Comment by askbox** [comment]
This is just stupid. How do I roll this back ? I want to block elements while being in private, never mind why.
