### ISSUE TITLE
Dark Mode detection not always blocked by Fingerprinting Protection on Android

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#25851]
Under certain conditions, the user's system light-mode/dark-mode preference is leaked to websites even if fingerprint blocking is set to strict. This happens when closing and reopening Brave for Android.

**Steps To Reproduce:**
1. On an Android device, set the system color scheme to dark mode.
2. In Brave, set Settings -> Brave Shields & privacy -> Block Fingerprinting to "Fingerprinting blocked (strict, may break sites)"
3. Open https://septatrix.github.io/prefers-color-scheme-test/ (or another prefers-color-scheme demo page). Observe that the site does not detect Dark Mode, as expected.
4. Press the system Home button (or, if using gesture navigation, swipe the bar up) to close Brave. Then, reopen Brave.
5. Observe that the demo page now detects Dark Mode.

Expected Outcome:
Demo page should not detect dark mode even if Brave is closed and then re-opened.

Additional Regression Testing:
https://github.com/brave/brave-browser/issues/15265#issuecomment-861071038

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.46.87 x64 build 
- Verified steps from issue description
- Verified the test page auto-detects and updates the value based on device theme preference/browser theme preference

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/199427653-779dbccd-9364-43aa-a99e-e2cd10e0d9bd.mp4> | <video src=https://user-images.githubusercontent.com/17010094/199427766-21c05147-3937-4ac8-9431-9668d5d32739.mp4>
