### ISSUE TITLE
Add pages and domains loaded P3A metrics

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#25867]
## Description 

Add P3A metrics for amount of pages loaded and domains loaded.

How many pages did you load in the past week?
`Brave.Core.PagesLoaded`
```
0. 0 pages
1. 1-10
2. 11-50
3. 51-100
4. 101-500
5. 501-1000
6. Greater than 1000 pages
```

How many unique domains did you load in the past week?
`Brave.Core.DomainsLoaded`
```
0. 0 domains
1. 1-4
2. 5-10
3. 11-30
4. 31-50
5. 51-100
6. Greater than 100 domains
```

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```
Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (64-bit)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | Windows 10 Version 21H2 (Build 19044.2130)

```

**Comment by GeetaSarvadnya** [comment]
@DJAndries I need a clarification on the respone status value `2` for the metrics `Brave.Core.PagesLoaded`. I have opened 10 sites (as shown in the image below) which falls under the bucket 1 to 10, I was expecting the response  value as `1` instead of `2`, I am suspecting brave://local-state is also considered as a domain hence the status response value is `2` ?

![image](https://user-images.githubusercontent.com/38657976/198530179-d707e0ab-e96e-4164-90bb-27b550edcf08.png)

**Comment by GeetaSarvadnya** [comment]
@DJAndries I am not getting the expected result for the step 4 in the test plan https://github.com/brave/brave-core/pull/15395
I am getting the metrics `Brave.Core.DomainsLoaded` response value as `1` instead `0`. Could you look into this? Thanks!

**Comment by GeetaSarvadnya** [comment]
@DJAndries `How many unique domains did you load in the past week?` - a past week is considered from the day when sites are loaded or a calendar week (Monday to Sunday)? 

I have executed few cases where in I am seeing response value for `Brave.Core.DomainsLoaded` even when a week is not completed (I am considering the past week from the day when I loaded the unique domains). Example the cases 1 and 2. Is this bug? what is the criteria to show `Brave.Core.DomainsLoaded` response value? even if I load the sites today and set the sys date ahead by one day I could see the response value for metrics. But the description says unique sites loaded is past week this is bit confusing. Also I would need clarification on the cases below.

Scenarios:

**Case 1**: 31st oct->domains loaded 4--> set the sys date to 5th Nov-->`Brave.Core.DomainsLoaded`response value 1-Need clarification 
**Case 2**: 31st oct->domains loaded 4--> set the sys date to 6th Nov-->`Brave.Core.DomainsLoaded` response value  2-Need clarification 
**Case 3**: 31st oct->domains loaded 4--> set the sys date to 7th Nov-->`Brave.Core.DomainsLoaded` response value  1- Expected as a week is considered from 31st Oct to 6th Nov
**Case 4**: 31st oct->domains loaded 4--> set the sys date to 8th Nov-->`Brave.Core.DomainsLoaded` response value  0 -Expected as a week is already passed
**Case 5**: 31st oct->domains loaded 4--> set the sys date to 9th Nov-->`Brave.Core.DomainsLoaded` response value 0 -Expected as a week is already passed

**Comment by GeetaSarvadnya** [comment]
As per the discussion with @DJAndries via DM, To report the metrics `Brave.Core.DomainsLoaded` one week need not to be passed. The domain will be counted the day after the domain has been visited. If domain is visited today (31st Oct), the domains will be reported from 1st, 2nd, 3rd, 4th, 5th, 6th, 7th Novemenber (i.e from 2 to 8). The below cases are working as expected.

Case 1: 31st oct->domains loaded 4--> set the sys date to 5th Nov-->`Brave.Core.DomainsLoaded`response value 1
Case 2: 31st oct->domains loaded 4--> set the sys date to 6th Nov-->`Brave.Core.DomainsLoaded` response value 1
Case 3: 31st oct->domains loaded 4--> set the sys date to 7th Nov-->`Brave.Core.DomainsLoaded` response value  1
Case 4: 31st oct->domains loaded 4--> set the sys date to 8th Nov-->`Brave.Core.DomainsLoaded` response value  0
Case 5: 31st oct->domains loaded 4--> set the sys date to 9th Nov-->`Brave.Core.DomainsLoaded` response value 0
Case 6: 31st oct->domains loaded 4--> set the sys date to 2nd Nov-->`Brave.Core.DomainsLoaded`response value 1
Case 7: 31st oct->domains loaded 4--> set the sys date to 3rd Nov-->`Brave.Core.DomainsLoaded`response value 1
Case 8: 31st oct->domains loaded 4--> set the sys date to 4th Nov-->`Brave.Core.DomainsLoaded`response value 1

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.46.87 x64 Beta build
- Verified steps from issue description and [brave/brave-core#15395](https://github.com/brave/brave-core/pull/15395)

**`Brave.Core.PagesLoaded`**

<i>Note: There was no need to move the date ahead to check the metric to be updated or not. Just quit and relaunch of browser and waiting upto 30 sec was sufficient.</i>

<details>
<summary>Case 1: <code>Brave.Core.PagesLoaded = 0</code> - <b>PASSED</b></summary>
<br>

- Clean install 1.46.87 x64 Beta build
- Do not load any webpages
- Open `chrome://local-state`
- Verified `Brave.Core.PagesLoaded` has a response value of `0`
   <img width=300 src=https://user-images.githubusercontent.com/17010094/199503924-90e2922d-0cbd-4ebf-8d75-a391d0fe001d.png>

</details>
<details>
<summary>Case 2: <code>Brave.Core.PagesLoaded = 1</code> - <b>PASSED</b></summary>
<br>

- Clean install 1.46.87 x64 Beta build
- Do not load any webpages
- Open `chrome://local-state`
- Verified `Brave.Core.PagesLoaded` has a response value of `0`
- Visit < 10 sites 
- Quit browser and restart 
- Wait for 30sec and reload `chrome://local-state`
- Verified `Brave.Core.PagesLoaded` has a response value of `1`
   <img width=300 src=https://user-images.githubusercontent.com/17010094/199511269-d5ce7966-9e2a-463c-ab2c-e6f3c44ff3d5.png>

</details>
<details>
<summary>Case 3: <code>Brave.Core.PagesLoaded = 2</code>  - <b>PASSED</b></summary>
<br>

- Clean install 1.46.87 x64 Beta build
- Do not load any webpages
- Open `chrome://local-state`
- Verified `Brave.Core.PagesLoaded` has a response value of `0`
- Visit > 10 sites  
- Quit browser and restart 
- Wait for 30sec and reload `chrome://local-state`
- Verified `Brave.Core.PagesLoaded` has a response value of `2`
   <img width=300 src=https://user-images.githubusercontent.com/17010094/199511317-19ea253a-6fec-4e93-ab27-1237b40444be.png>

</details>

**`Brave.Core.DomainsLoaded`**

<details>
<summary>Case 1: <code>Brave.Core.DomainsLoaded = 0</code> - <b>PASSED</b></summary>
<br>

- Clean install 1.46.87 x64 Beta build
- Do not load any webpages
- Open `chrome://local-state`
- Verified `Brave.Core.DomainsLoaded` has a response value of `0`
   <img width=300 src=https://user-images.githubusercontent.com/17010094/199511494-f2f1321d-4049-4bca-9a19-4aebf43144f8.png>

</details>
<details>
<summary>Case 2: <code>Brave.Core.DomainsLoaded = 1</code> - <b>PASSED</b></summary>
<br>

- Clean install 1.46.87 x64 Beta build
- Do not load any webpages
- Open `chrome://local-state`
- Visit two domains in an individual tab
- Quit browser and move date ahead by 2 days
- Relaunch browser and wait for 30 sec
- Verified `Brave.Core.DomainsLoaded` has a response value of `1`
   <img width=300 src=https://user-images.githubusercontent.com/17010094/199511458-9b595902-16d6-456b-a191-05b25923fb63.png>

</details>
<details>
<summary>Case 3: <code>Brave.Core.DomainsLoaded = 2</code>  - <b>PASSED</b></summary>
<br>

- Clean install 1.46.87 x64 Beta build
- Do not load any webpages
- Open `chrome://local-state`
- Visit 5 0r 6 domains in an individual tab
- Quit browser and move date ahead by 2 days
- Relaunch browser and wait for 30 sec
- Verified `Brave.Core.DomainsLoaded` has a response value of `2`
   <img width=300 src=https://user-images.githubusercontent.com/17010094/199511611-4ed68d61-6b9d-49b8-b158-edc5ae6ba5ee.png>

</details>

<details>
<summary>Case 4: <code>Brave.Core.DomainsLoaded = 3</code>  - <b>PASSED</b></summary>
<br>

- Clean install 1.46.87 x64 Beta build
- Do not load any webpages
- Open `chrome://local-state`
- Visit 11 domains in an individual tab
- Quit browser and move date ahead by 2 days
- Relaunch browser and wait for 30 sec
- Verified `Brave.Core.DomainsLoaded` has a response value of `3`
   <img width=300 src=https://user-images.githubusercontent.com/17010094/199511674-d6c63842-f13b-4313-90a6-dcf33dada77c.png>

</details>
