### ISSUE TITLE
Feature request: Show token prices within Fund-Wallet screen

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#25861]
## Description 

Show the current price of the assets available for purchase within the fund-wallet screen.

## Actual result:

Prices are not shown

## Expected result:
Show the price of the asset/token based on the selected fiat currency.

## Reproduces how often: 

Easy

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (64-bit) 
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | Linux

- Verified steps from issue description and [brave/brave-core#15393](https://github.com/brave/brave-core/pull/15393)
- Verified as part of [#25660](https://github.com/brave/brave-browser/issues/25660#issuecomment-1298067045)

------------------------
Verification passed on

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (64-bit) 
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | Windows 11 Version 22H2 (Build 22621.674)

- Verified steps from issue description and [brave/brave-core#15393](https://github.com/brave/brave-core/pull/15393)
- Verified as part of [#25660](https://github.com/brave/brave-browser/issues/25660#issuecomment-1298067045)

------------------------
Verification passed on

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (arm64)
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from issue description and [brave/brave-core#15393](https://github.com/brave/brave-core/pull/15393)
- Verified as part of [#25660](https://github.com/brave/brave-browser/issues/25660#issuecomment-1298067045)
