### ISSUE TITLE
Fund Account Asset Keeps Scrolling into View

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#25865]
## Description 

When selecting a multi-chain asset for purchase (such as Ether) from the market page, the fund-wallet page displays the multi-chain asset as selected on multiple networks

## Steps to Reproduce

   1. Open market data page
   2. select "Buy" for any asset
   3. The fund-wallet page is shown and the Asset should scroll into view
   4. Scroll away from the asset, it will keep scrolling back into view.

## Actual result:

https://user-images.githubusercontent.com/40611140/194648508-d83f80fb-be07-468c-8723-25b6b4ce91d2.mov

## Expected result:
The asset should only scroll into view once

## Reproduces how often: 

Easy

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (64-bit) 
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | Linux

- Verified steps from [brave/brave-core#15394](https://github.com/brave/brave-core/pull/15394)
- Verified account asset doesn't scroll back to selected token rather stays in the same place as it is scrolled into view


------------------------
Verification passed on

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (64-bit) 
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | Windows 11 Version 22H2 (Build 22621.674)

- Verified steps from [brave/brave-core#15394](https://github.com/brave/brave-core/pull/15394)
- Verified account asset doesn't scroll back to selected token rather stays in the same place as it is scrolled into view

------------------------
Verification passed on

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (arm64)
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#15394](https://github.com/brave/brave-core/pull/15394)
- Verified account asset doesn't scroll back to selected token rather stays in the same place as it is scrolled into view
