### ISSUE TITLE
Solana NFT token quantity and decimal handling in Brave Wallet

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#25864]
I purchased these 2 NFTs:
https://solscan.io/token/7xRLmfvknKtsQwJB3JuTSAdEQz5k2zeBWCkzBSGNiRXp
https://solscan.io/token/CnPSj9ABGJXSBrRPjahYN8wMzhpz9CFFwPoZV6y1caeq
From Magic Eden with Phantom
I added them manually to the Brave Wallet by importing my Phantom seed into Brave Wallet.
Then I added the custom assets for each of those NFTs.

But when you add you need to enter decimals. So I entered 1. 0 is not accepted.  When I saved it shows the quantity as 0.1. If I put for example 10 it would be 0.000…1

Could we detect that it's an NFT token address and not have a decimal field? Or else allow 0 at least?
Info via Jocelyn: We can use `getTokenSupply` JSON RPC, something like checking that supply = 1 means NFT.

<img width="1078" alt="Screen Shot 2022-10-07 at 4 33 57 PM" src="https://user-images.githubusercontent.com/831718/194648306-bb929e0b-3b49-4b7d-ab52-fb51d7e6aaa5.png">

We should check to see if extra fixes are needed for Android and iOS for this.

**Comment by yrliou** [comment]
Another thought, we currently ask users to select if it's ERC721 for EVMs and show a slightly different input screen if so, we could probably make it a general "Is it a NFT?" switch and apply that to both EVM and Solana. Advantage of this is that we could give users a more reasonable input screen. This property can be used for NFT displaying too in the wallet.

**Comment by jamesmudgett** [comment]
We have a new NFT input form in review which only has required fields for NFTs

**Comment by yrliou** [comment]
To have basic support of Solana NFT, on desktop UI, we need
1. Enable the ability to add Solana NFT via add-nft-form similar to below. Currently we can't add Solana NFT this way because there is no tokenID.
```
+++ b/components/brave_wallet_ui/components/shared/add-custom-token-form/add-nft-form.tsx
@@ -177,9 +177,9 @@ export const AddNftForm = (props: Props) => {
   const buttonDisabled = React.useMemo((): boolean => {
     return tokenName === '' ||
       tokenSymbol === '' ||
-      tokenID === '' ||
       tokenContractAddress === '' ||
       !customAssetsNetwork ||
+      (customAssetsNetwork?.coin === BraveWallet.CoinType.ETH && tokenID === '') ||
```
2. Fix the balance display for Solana NFT similar to below. Currently we use amount without returned decimals in this RPC response and use amount with token.decimals, which is wrong.
```
+++ b/components/brave_wallet_ui/common/async/lib.ts
@@ -462,7 +462,7 @@ export function refreshBalances () {
           if (networks.some(n => n.chainId === token.chainId)) {
             const getSolTokenBalance = await jsonRpcService.getSPLTokenAccountBalance(account.address, token.contractAddress, token.chainId)
             return {
-              balance: getSolTokenBalance.amount,
+              balance: getSolTokenBalance.uiAmountString,
               error: getSolTokenBalance.error,
               errorMessage: getSolTokenBalance.errorMessage
             }
```
3. Display Solana NFTs (which will have token.isNft = true) under NFT section in portfolio page.

We need corresponding changes on Android and iOS too.

**Comment by kjozwiak** [comment]
The above will require `1.45.124` or higher for `1.45.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.45.127 Chromium: 107.0.5304.110 (Official Build) (64-bit)
-- | --
Revision | `2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}`
OS | Linux

- Verified NFT token quantity is shown correctly and no decimal value is shown for the total
- Verified SPL Token value is also shown correctly 
- Additional verification notes here [#26667 (comment)](https://github.com/brave/brave-browser/issues/26667#issuecomment-1315130435)
![image](https://user-images.githubusercontent.com/17010094/201937839-64bd5010-d7d3-4123-ad61-5e37f2315522.png)

---------------------

Verification passed on 

Brave | 1.45.127 Chromium: 107.0.5304.110 (Official Build) (64-bit) 
-- | --
Revision | `2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified NFT token quantity is shown correctly and no decimal value is shown for the total
- Verified SPL Token value is also shown correctly 
- Additional verification notes here [#26667 (comment)](https://github.com/brave/brave-browser/issues/26667#issuecomment-1315130435)
![image](https://user-images.githubusercontent.com/17010094/201937736-69d7abff-a27e-4d38-b244-80bf0b440053.png)

---------------------

Verification passed on 

Brave | 1.45.127 Chromium: 107.0.5304.110 (Official Build) (64-bit) 
-- | --
Revision | `2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}`
OS | macOS Version 13.0 (Build 22A380)

- Verified NFT token quantity is shown correctly and no decimal value is shown for the total
- Verified SPL Token value is also shown correctly 
- Additional verification notes here [#26667 (comment)](https://github.com/brave/brave-browser/issues/26667#issuecomment-1315130435)
![image](https://user-images.githubusercontent.com/17010094/201894764-90ea34a8-c68c-4413-9585-b57c2ee87ff0.png)
