### ISSUE TITLE
[Android] Add setting for blocking Android app links

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#25863]
### Summary
iOS already has a setting to allow/block "universal links" from opening in external apps.
![image](https://user-images.githubusercontent.com/28269287/194646040-72c1aa7a-287d-49b7-be3f-9b92f9795018.png)

We should bring over this feature to Android. "universal links" are called "app links" on Android. The setting copy should reflect this. Android app link details: https://developer.android.com/training/app-links

### Requirements
- Add a toggle setting to allow/block Android "app links" under settings -> brave shields & privacy -> other privacy settings. 
Copy: "Allow app links to open in apps outside of Brave"
Default state: disabled.

- Enabled (Allow) state: app links open in external app.
- Disabled state: app links open in Brave.

**Comment by rmcfadden3** [comment]
@timchilds — so this is like if you click a FB link and you have FB app installed on your phone, this setting would allow it to open there instead?

If yes, your copy looks pretty good. Only thing I might comment on is use of the word "external" here. It makes sense to us, but maybe not to users? Could we say like "Allow app links to open in apps outside of Brave" instead?

**Comment by deeppandya** [comment]
> @deeppandya adding this one to next triage. @Sam-Sibley @rmcfadden3 does the toggle setting copy sound ok to you:
> 
> "Allow app links to open in external apps"

Yeah toggle for the setting, would be perfect here.

**Comment by Sam-Sibley** [comment]
@deeppandya wording is good, and agree this can go in the 'Other' section. I would put it at the top of that section, but @timchilds may have suggestion on this.

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` & `Samsung Galaxy Tab S7` using the following build:

```
Brave	1.57.35 Chromium: 115.0.5790.171 (Official Build) beta (64-bit) 
Revision	776897328898241b35b83878040730e73e749c06
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
Acceptance Criteria: https://github.com/brave/brave-browser/issues/25863#issue-1401631915

- Verified toggle is located in settings -> brave shields & privacy -> other privacy
- Verified default toggle state is disabled
- Verified copy `Allow app links to open in apps outside of Brave` for toggle
- Verified external app will load when opening universal links in Brave if toggle is enabled
- Verified `Allow app links to open in apps outside of Brave` default state is disabled on existing profile and enabling will load installed app when opening universal links.
- Verified app links do not load in external app in private tabs - https://github.com/brave/brave-browser/issues/32086

<table><tr><td>Mobile</td><td>Tablet</td></tr>
<tr><td>

https://github.com/brave/brave-browser/assets/17885425/079ef233-5adc-4dee-926f-7785461c7cbb

</td><td>

https://github.com/brave/brave-browser/assets/17885425/dbbf2dfb-0626-4bc3-968f-ac7ab5e25c7c

</td></tr></table>

**Comment by Uni-verse** [comment]
In Progress on Pixel 2 using the following build version:

```
Brave	1.57.44 Chromium: 116.0.5845.82 (Official Build) (32-bit) 
Revision	109e984111c5152478bf49d266f4e19861c0b63e
OS	Android 8.1.0; Build/OPM2.171026.006.H1; 27; REL
```
