### ISSUE TITLE
`Your email address` textfield needs validation

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#25860]
## Description 

`Your email address` textfield needs validation

Kudos to @MadhaviSeelam for the find!

## Steps to Reproduce

   1. install `1.45.90`
   2. launch Brave
   3. set up a `Brave VPN` connection
   4. click on the `VPN` button in the toolbar
   5. click the `Gears` icon
   6. click on `Contact technical support`
   7. enter `aaaa` into the `Your email address` field
   8. click `Submit`

## Actual result:

<img width="1085" alt="Screen Shot 2022-10-07 at 3 00 21 PM" src="https://user-images.githubusercontent.com/387249/194635458-e7b6d5ff-872b-4f31-a94a-604baa5346d2.png">

`Failed to create support ticket, check your connection.`

## Expected result:

Should balk at the non-email-address text `aaaa` and throw an error saying so, with the `Your email address` textfield highlighted in red

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.45.90 Chromium: 106.0.5249.103 (Official Build) beta (x86_64)
-- | --
Revision | 182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}
OS | macOS Version 11.7 (Build 20G817)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @MadhaviSeelam @aguscruiz @bsclifton @spylogsster @rmcfadden3

**Comment by rmcfadden3** [comment]
@stephendonner — are you thinking an error message something like "Failed to create support ticket. Check your email address." or similar?

**Comment by stephendonner** [comment]
> @stephendonner — are you thinking an error message something like "Failed to create support ticket. Check your email address." or similar?

@rmcfadden3 was thinking we should validate the email address first, and throw an error message specific to its validation, before even trying to submit, actually.

**Comment by rmcfadden3** [comment]
> > @stephendonner — are you thinking an error message something like "Failed to create support ticket. Check your email address." or similar?
> 
> @rmcfadden3 was thinking we should validate the email address first, and throw an error message specific to its validation, before even trying to submit, actually.

@stephendonner — so maybe something more like "Could not validate your email address. Please try again." or "Could not verify your email address. Please try again." instead?

**Comment by stephendonner** [comment]
> > > @stephendonner — are you thinking an error message something like "Failed to create support ticket. Check your email address." or similar?
> > 
> > 
> > @rmcfadden3 was thinking we should validate the email address first, and throw an error message specific to its validation, before even trying to submit, actually.
> 
> @stephendonner — so maybe something more like "Could not validate your email address. Please try again." or "Could not verify your email address. Please try again." instead?

Sorry for the delay in responding; what @petemill implemented with the red error text (inline) LGMT 👍

**Comment by kjozwiak** [comment]
The above requires `1.46.87` or higher for `1.46.x` verification. However, I believe we can verify the above without the need for the SKU SDK v2 to land on the server side.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.46.96 Chromium: 107.0.5304.91 (Official Build) beta (64-bit)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | Windows 11 Version 21H2 (Build 22000.1098)
```

Verified using original STR from the description


- Install 1.46.96
- launched Brave
- set up a Brave VPN connection
- clicked on the `VPN` button in the toolbar
- clicked the `Gears `icon
- clicked on `Contact technical support`

#### Confirmed `Your email address` text field shows correct validation message  `Please enter a valid email address` for invalid email address
#### Confirmed validation message  `Please choose a reason`  returned for not choosing a `Subject `
#### Confirmed validation message  `This field is required` returned for `empty body`

Invalid email address|Not choosing a subject `|Empty body
-------|----------|-------------------
<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/200414803-d0f125fd-b34a-4eda-b0e9-cd7f2fbd1b6d.png">|<img width="466" alt="image" src="https://user-images.githubusercontent.com/98358127/200421499-55f8d5b8-b305-4227-9a6b-08e9e80f1800.png">|<img width="461" alt="image" src="https://user-images.githubusercontent.com/98358127/200416557-38375d8c-9178-414c-8324-7ae0c875ea71.png">

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.46.133 Chromium: 108.0.5359.71 (Official Build) (x86_64)
-- | --
Revision | 1e0e3868ee06e91ad636a874420e3ca3ae3756ac-refs/branch-heads/5359@{#1016}
OS | macOS Version 13.1 (Build 22C5050e)

### Steps:
1. Installed `1.46.133`
2. launched Brave
3. set up a `Brave VPN` connection via `account.bravesoftware.com`
4. clicked on the `VPN` button in the toolbar
5. clicked the `Gears` icon
6. clicked on `Contact technical support`
7. Confirmed `Your email address` text field shows correct validation message `Please enter a valid email address for invalid email address`
8. Confirmed validation message `Please choose a reason` returned for not choosing a `Subject`
9. Confirmed validation message `This field is required` returned for empty body

example | example | example | example
---------|----------|----------|---------
<img width="1432" alt="Screenshot 2022-12-01 at 9 07 22 AM" src="https://user-images.githubusercontent.com/387249/205117802-74257b6e-424b-4877-8cd7-4b001b7c2269.png"> | <img width="1432" alt="Screenshot 2022-12-01 at 9 07 33 AM" src="https://user-images.githubusercontent.com/387249/205117805-233de9c0-00e8-49bf-802a-bb8d966a9a08.png"> | <img width="1432" alt="Screenshot 2022-12-01 at 9 08 17 AM" src="https://user-images.githubusercontent.com/387249/205117806-99fb8a1e-f60f-46f8-851a-ca3bce9ff723.png"> | <img width="1432" alt="Screenshot 2022-12-01 at 9 08 40 AM" src="https://user-images.githubusercontent.com/387249/205117808-439812b4-d926-4baa-b383-f4d0703e8730.png">
