### ISSUE TITLE
[Android] Message vpn users about desktop vpn

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#25866]
### Summary
The desktop vpn and subscription linking will launch soon (date tbd). The marketing team would like to message existing mobile users who have already purchased a vpn subscription. Informing those users that they can now use their existing subscription to access the desktop vpn.

Design: https://www.figma.com/file/PqLTp3DnANLQMM1XzaChqZ/Mobile-VPN?node-id=2407%3A21605

**Comment by deeppandya** [comment]
@Sam-Sibley @timchilds there are two way we perform cross platform sync : 
1. desktop -> Android credentials linking (https://github.com/brave/qa-resources/wiki/Premium-VPN-Tests#desktop---android-credentials-linking) 
2. Android -> desktop credentials linking (https://github.com/brave/qa-resources/wiki/Premium-VPN-Tests#android---desktop-credentials-linking)

we would need CTA for `Android -> desktop credentials linking`

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.46.130 x64 build.
- Verified steps from [brave/brave-core#15602](https://github.com/brave/brave-core/pull/15602)
- Verified VPN settings has a new item for linking subscription
- Verified clicking the setting opens a new tab and loads `https://account.brave.com`
- Verified link subscription modal is shown on second restart
- Verified `Link purchase to your Brave account` is only enabled when there is an active subscription on Android IAP
- Verified when the setting is disabled, the modal is also not shown irrespective how many times the browser is restarted

https://user-images.githubusercontent.com/17010094/204548035-94f434c0-a07b-4337-9186-4ed73670ccfd.mp4
