### ISSUE TITLE
Youtube Video Tearing on Windows

### ISSUE THREAD

**Issue by icy-comet** [brave/brave-browser#25879]
## Description 
Launching YouTube without changing any setting after a clean installation of Brave and setting the video resolution to 1080p causes video-tearing.

I tried all 3 releases of Brave — Stable, Beta, Nightly but had similar results in all 3 of them.

Disabling 'Hardware Acceleration' or changing the `ANGLE graphics backend` to `OpenGL` with `brave://flags` seems to resolve the issue.

## Steps to Reproduce
   1. Clean Install Brave
   2. Open YouTube
   3. Play Video at 1080p resolution

## Reproduces how often: 
Every time.

## Brave version (brave://version info)
```
Brave           1.44.108 Chromium: 106.0.5249.103 (Official Build) (64-bit) 
Revision	182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}
OS	        Windows 11 Version 22H2 (Build 22621.608)
```
```
Brave           1.45.88 Chromium: 106.0.5249.91 (Official Build) beta (64-bit) 
Revision	fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}
OS	        Windows 11 Version 22H2 (Build 22621.608)
```
```
Brave           1.46.41 Chromium: 106.0.5249.103 (Official Build) nightly (64-bit) 
Revision	182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}
OS	        Windows 11 Version 22H2 (Build 22621.608)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by deiberts86** [comment]
I second this, having the same issue with the latest NVIDIA drivers on a 3080ti.  Edge, Chrome, or Mozilla Firefox doesn't have this problem whatsoever.

OS Info:
 Windows 11 22H2 (Build 22621.675)

Brave Browser Info:
Version 1.45.113 Chromium: 107.0.5304.62 (Official Build) (64-bit)

Nvidia Drivers:
522.25 Release date (10/12/2022)

**Comment by icy-comet** [comment]
I forgot to mention that I have a laptop with Intel and Nvidia 3050 graphics.

Nvidia: `v522.25` (released 12th Oct'22)
Intel: `v30.0.101.1692` (latest OEM driver)
