### ISSUE TITLE
[In Latest Version] An error occurred while loading the PDF

### ISSUE THREAD

**Issue by avndp** [brave/brave-browser#2587]
## Description 
I've been waiting since long for opening PDF files through Brave browser. Now with the latest release i.e., 0.57.18, the PDF problems were solved to a great extent. However, still, some PDFs are not opening.

## Steps to Reproduce

   1. Open this link: https://webservices.ignou.ac.in/Pre-Question/Question%20Paper%20December%202015/SOSS/MA(SOCIOLOGY)/MSO-004.PDF
   2. Error occurs.

## Actual result:
An error occurred while loading the PDF.  More Information

## Expected result:
PDF should open. 

## Reproduces how often: 
Easily reproduced, everytime.

## Brave version (brave://version info)
Version 0.57.18 Chromium: 71.0.3578.80 (Official Build) (64-bit)

### Reproducible on current release:
Not checked with Beta/Dev.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? - NO. 
- Is the issue reproducible on the latest version of Chrome?  - NO, It's working fine in Chrome.

### Additional Information
I wanted to install Brave in all my office which consists of more than 500 computer users. All of them regularly uses PDF in the office procedures. I've been waiting for these problems to be solved before I introduce Brave to my colleagues.

**Comment by sillibird** [comment]
Working fine for me.

**Comment by bbondy** [comment]
works for me with 0.58.x.  Please re-open if you still experience with a 0.58.x build.
