### ISSUE TITLE
scroll position resets to the very first tab when removing tabs

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#25883]
~~> When closing the active tab (through any method: Ctrl+W, X button, context menu), the vertical tab list scrolling will be reset to the top. You need enough tabs open to spill off the bottom of the screen for it to become a problem, but it's quite inconvenient when attempting to close multiple tabs in a row out of a large set.~~ - Not reproducible at this moment.

**Comment by sangwoo108** [comment]
cc. @antonok-edm

**Comment by sangwoo108** [comment]
Removing case is not reproducible on Mac and Windows.

**Comment by sangwoo108** [comment]
Reportedly, a user faced this on Windows 10

**Comment by sangwoo108** [comment]
Hi, @antonok-edm . I'd like to ask you something. When you said "srolling will be reset to the top", does it mean that the very first tab will be visible? or more like a video herehttps://github.com/brave/brave-browser/issues/26304 ?

**Comment by antonok-edm** [comment]
The very first tab became visible - although I'm not able to reproduce that anymore, so this is probably safe to close now! I'll try to get a recording if I see it again at all.
