### ISSUE TITLE
Connection error message is shown even when device is successfully connected

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#25887]
## Description 

Connection error message is shown even when device is successfully connected

## Steps to Reproduce

First way to repro
   1. Complete VPN purchase flow
   2. Close the browser, ensure VPN is disconnected
   3. Relaunch the browser and open VPN button and connect
   4. Open VPN button again, shows error message but its successfully connected (check IP for double confirmation)

Second way to repro (Windows Only)
   1. Complete VPN purchase flow
   2. Close the browser, ensure VPN is disconnected
   3. Connect to VPN via Windows VPN connection
   4. Launch browser, VPN shows connected
   5. Open VPN button, shows connection error message but VPN is connected via System settings

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/194902303-1ff878bb-9bdc-4ad9-8d64-d83988c59c42.png)

Console throws error 

```
    in skus::storage::kv::get_time_limited_creds with self=NativeClient item_id="ef8f35fb-b418-43f5-a45b-9fa4f3d569bd"
    in skus::sdk::credentials::matching_time_limited_credential with self=SDK item_id="ef8f35fb-b418-43f5-a45b-9fa4f3d569bd"
    in skus::sdk::credentials::present::prepare_order_credentials_presentation with self=SDK order_id="aa7eae18-ee79-4c20-b08a-894c4fcd6976" domain="vpn.bravesoftware.com" path="*"
    in skus::sdk::credentials::present::prepare_credentials_presentation with self=SDK domain="vpn.bravesoftware.com" path="*"
[9656:11452:1010/013932.694:ERROR:utils_win.cc(55)] The parameter is incorrect.
```

## Expected result:
No errors on console or error connecting message

## Reproduces how often: 

Easy but intermittent

## Brave version (brave://version info)

Brave | 1.46.41 Chromium: 106.0.5249.103 (Official Build) nightly (64-bit)
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | Windows 11 Version 21H2 (Build 22000.1042(

## Version/Channel Information:

- Can you reproduce this issue with the current release? Not tested
- Can you reproduce this issue with the beta channel? Not tested
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @simonhong @bsclifton @spylogsster

**Comment by GeetaSarvadnya** [comment]
I can't reproduce the issue from both ways (STR's) from https://github.com/brave/brave-browser/issues/25887#issue-1403364186

But issue is reproduced intermittently once when I open the VPN panel, I get `Can't connect to server` error in the panel eventhough VPN is connected successfully.

**Comment by spylogsster** [comment]
looks like yes, cannot reproduce anymore @srirambv mind to recheck this please?

**Comment by srirambv** [comment]
Can't reproduce the issue anymore as well. Closing the issue for now. We can reopen if me or anyone runs into this again.

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on 

```
Brave | 1.46.117 Chromium: 107.0.5304.110 (Official Build) beta (64-bit)
-- | --
Revision | 2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}
OS | Windows 10 Version 21H2 (Build 19044.2251)

```
- Verified the both STR's from the issue and ensured connection error message is not shown when device is connected

Also verified the below:
1. Make sure VPN is connected->Disconnect the VPN via windows vpn settings->make sure VPN is disconnected in browser->close the browser->reconnect the VPN via windows vpn settings->relaunch the browser and ensured VPN is in conneted state, click on VPN there is no error message
