### ISSUE TITLE
Brave's translatation does not work in China

### ISSUE THREAD

**Issue by biange200** [brave/brave-browser#25881]
## English translation by Brave staff member
> May I ask which Google Translate function Brave uses? Google Translate doesn't work in China
> Brave's built-in translation function cannot be translated at all in China

## Original issue description
请问一下 brave用的是谷歌翻译功能？ 谷歌翻译在中国用不了
brave内置翻译功能在中国完全无法翻译![Screenshot_20221008_112329.jpg](https://user-images.githubusercontent.com/37582806/194789433-b2f9848c-3a5b-4266-9cb7-6aa9a6bb68a1.jpg)
可以添加其他翻译？比如deepl youdao baidu Translation

**Comment by git10135405** [comment]
me too

**Comment by biange200** [comment]
没有解决方法？



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年12月03日 20:52 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [brave/brave-browser] brave的翻译在中国用不了 (Issue #25881) |

me too

**Comment by zhaojiannet** [comment]
继谷歌翻译挂了之后，Brave的翻译也挂了，实在是想不明白，为什么要针对这种翻译服务。

临时解决办法，在hosts文件中，添加以下IP地址后，可以使用整页翻译。

172.65.248.248 translate.brave.com

2024-3-14

**Comment by biange200** [comment]
> 继谷歌翻译挂了之后，Brave的翻译也挂了，实在是想不明白，为什么要针对这种翻译服务。
> 
> 临时解决办法，在hosts文件中，添加以下IP地址后，可以使用整页翻译。
> 
> 172.65.248.248 translate.brave.com
> 
> 2024-3-14

手机没root

**Comment by T-789t** [comment]
> 继谷歌翻译挂了之后，Brave的翻译也挂了，实在是想不明白，为什么要针对这种翻译服务。
> 
> 临时解决办法，在hosts文件中，添加以下IP地址后，可以使用整页翻译。
> 
> 172.65.248.248 translate.brave.com
> 
> 2024-3-14
我添加了,还是用不了

**Comment by biange200** [comment]
> > 继谷歌翻译挂了之后，Brave的翻译也挂了，实在是想不明白，为什么要针对这种翻译服务。
> > 
> > 临时解决办法，在hosts文件中，添加以下IP地址后，可以使用整页翻译。
> > 
> > 172.65.248.248 translate.brave.com
> > 
> > 2024-3-14
> 我添加了,还是用不了
> 

手机没root

**Comment by bsclifton** [comment]
cc: @atuchin-m

**Comment by git10135405** [comment]
> Hi folks - this should be working great now. Please reply here if the translation is not working OK
> 
> We had some fixes back in August and did not find/close this issue after fixing.

Mobile 1.71.114 still doesn't work without a proxy
