### ISSUE TITLE
Sidebar toolbar button should use image based on alignment

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#25899]
## Steps to Reproduce

   1. Launch Brave with clean profile
   2. Check sidebar toolbar button uses left aligned image
   3. Change to sidebar on right via brave://settings/appearance

## Actual result:

<img width="40" alt="image" src="https://user-images.githubusercontent.com/6786187/195093004-c65c2e00-1ed5-4460-979f-fff8a52fe992.png">

## Expected result:
<img width="58" alt="image" src="https://user-images.githubusercontent.com/6786187/195093069-83f8c313-c038-4bff-889d-8828ee8b2ab4.png">

## Reproduces how often: 

Easy

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.46.68 Chromium: 107.0.5304.36 (Official Build) nightly (x86_64)
-- | --
Revision | 2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}
OS | macOS Version 13.0 (Build 22A379)

### Steps:
1. installed `1.46.68`
2. launched Brave
3. examined orientation of side panel's icon
4. changed `Side panel` to `Show on right` via `brave://settings/appearance`
5. examined orientation of side panel's icon

#### Confirmed the side-panel icon's orientation is appropriate for its `right`/`left` setting


### `Light`:

`Show on left` | `Show on right`
---------|---------
<img width="1176" alt="Screenshot 2022-10-18 at 5 46 22 PM" src="https://user-images.githubusercontent.com/387249/196571481-af06db9f-e547-4ce8-8a37-5a7864453583.png"> | <img width="1176" alt="Screenshot 2022-10-18 at 5 42 44 PM" src="https://user-images.githubusercontent.com/387249/196571372-38f6d1a7-ce67-4758-b7e1-408dcfb4b172.png">

### `Dark`:

`Show on left` | `Show on right`
---------------|----------------
<img width="1176" alt="Screenshot 2022-10-18 at 5 47 29 PM" src="https://user-images.githubusercontent.com/387249/196571608-84559ee7-8fa4-47c4-88c5-aa36900c53ac.png"> | <img width="1176" alt="Screenshot 2022-10-18 at 5 47 36 PM" src="https://user-images.githubusercontent.com/387249/196571609-bd708211-f7c2-4e2c-b8b7-dbab5cd4a725.png">
