### ISSUE TITLE
Latest version has broken too many sites to be useful

### ISSUE THREAD

**Issue by BrianMinister** [brave/brave-browser#2589]
## Description 
I am using Version 0.57.18 Chromium: 71.0.3578.80 (Official Build) (64-bit)

Github fails to allow updates but only when using brave.
Bing & Google fail to allow me to open common sites using brave.
DTube doesn't play video, just gives me a blank gray box where the video should be.
After so many fails, I decided to switch back to firefox for a while.

## Steps to Reproduce
I believe that the details in the description may be enough.
However, here is a sample of the failure: https://d.tube/#!/v/abolitionistjay/pwev5owf

## Actual result:
DTube doesn't play video, just gives me a blank gray box where the video should be.

## Expected result:
Video player in box for dtube.
Github, allowing me to upload files.

## Reproduces how often: 
I am seeing this 100% of the time for github and dtube.

## Brave version (brave://version info)
Version 0.57.18 Chromium: 71.0.3578.80 (Official Build) (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds?  only tested on the version above.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? nope.
- Is the issue reproducible on the latest version of Chrome? nope.

**Comment by tomlowenthal** [comment]
Thanks for the report, but a consolidated issue like this is very hard to act on. If you file specific issues for the sites where you're seeing the problems, that'll be much more helpful.
