### ISSUE TITLE
Can't recover after deleting vpn entry from os settings

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#25895]
## Description 

`Try again` doesn't work at all before relaunching the browser or choosing another server.

## Steps to Reproduce / Test plan

   1. Connect vpn
   2. Disconnect vpn
   3. Delete vpn entry from OS settings
   4. Connect vpn
   5. VPN Bubble shows `Can't connect to server bubble` 
   6. Click `Try again`

## Actual result:

Bubble shows `Can't connect to server` again

## Expected result:
Should go to connecting state

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.45.98` or higher for `1.45.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```

Brave | 1.45.98 Chromium: 106.0.5249.119 (Official Build) beta (64-bit)
-- | --
Revision | 9f2101830b56fd2ea1408287f6c74e253ebcb7c6-refs/branch-heads/5249@{#797}
OS | Windows 10 Version 21H2 (Build 19044.2130)

```

**Comment by stephendonner** [comment]
## Verified `PASSED` using 



Brave | 1.45.104 Chromium: 106.0.5249.126 (Official Build) beta (x86_64)
-- | --
Revision | fb2e06d2dee20fe0c804528502b5ad72c613abd9-refs/branch-heads/5249_118@{#3}
OS | macOS Version 11.7 (Build 20G817)

example | example | example | example | example | example | example
---------|----------|---------|-----------|---------|---------|---------
<img width="1312" alt="Screen Shot 2022-10-18 at 1 53 23 PM" src="https://user-images.githubusercontent.com/387249/196543073-781e004a-20f1-46b6-bffb-902b16a47561.png"> | <img width="1217" alt="Screen Shot 2022-10-18 at 1 50 30 PM" src="https://user-images.githubusercontent.com/387249/196543133-6e7b842d-22c3-4547-8e0c-21df41d75dbb.png"> |  <img width="780" alt="Screen Shot 2022-10-18 at 1 57 26 PM" src="https://user-images.githubusercontent.com/387249/196543578-cd2ec1f4-ab31-4277-8128-0218dfb046f9.png"> | <img width="780" alt="Screen Shot 2022-10-18 at 1 57 31 PM" src="https://user-images.githubusercontent.com/387249/196543583-a7a5b2f3-6965-422c-a399-4822871e7bd6.png"> | <img width="1312" alt="Screen Shot 2022-10-18 at 1 50 12 PM" src="https://user-images.githubusercontent.com/387249/196543362-4e6be7fe-3db4-4373-a4b6-193512713d27.png"> | <img width="1312" alt="Screen Shot 2022-10-18 at 1 50 16 PM" src="https://user-images.githubusercontent.com/387249/196543694-135d503d-97b0-4111-9f17-ffceeab12d70.png"> | <img width="1214" alt="Screen Shot 2022-10-18 at 2 00 30 PM" src="https://user-images.githubusercontent.com/387249/196543923-d8038b95-11bd-4ab7-8525-2d6f722e2d7a.png">
