### ISSUE TITLE
Revoking the connection doesn't update until the page is reloaded

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#25897]
## Description 
Revoking the connection doesn't update until the page is reloaded

## Steps to reproduce 

   1. Create 2 Solana Accounts
   2. Open `https://raydium.io` and connect to the site
   3. Connect with the current active account
   4. Click on `Connected` button to see list of accounts
   5. Select `Trust` on the other account and `Revoke` for the connected account in step 2
   6. Open Panel, first connected account continues to shows as `Connected` even though its revoked, second account still continues to shows `Disconnected` even though it has been trusted 
   7. Reload page fixes the connection status of both the accounts

## Actual result 
Revoking the connection doesn't update until the page is reloaded

## Expected result
Should update the state immediately

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes
 
## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.45.88 x64 Beta build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @Pavneet-Sing @SergeyZhukovsky @jamesmudgett

**Comment by Pavneet-Sing** [comment]
Discussed [here](https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1666342708670209), The behaviour on android is same as desktop so closing this as invalid.
