### ISSUE TITLE
Extensive padding in rewards panel

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#2590]
Follow up from https://github.com/brave/brave-browser/issues/2486

## Steps to Reproduce

1. Enable rewards
2. Visit any site 
3. Open the rewards panel

## Actual result:

![image](https://user-images.githubusercontent.com/34715963/50061168-6eaf8280-019d-11e9-9482-6469b1eb0894.png)

## Reproduces how often: 

always

## Brave version (brave://version info)

Brave | 0.58.14 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Windows 7

cc @brave/legacy_qa @NejcZdovc @petemill

**Comment by ryanml** [comment]
Curious, as this fix definitely worked at the time it was merged...

I'm going to come up with a more hardened solution at the brave-ui level later this evening. I'll keep it simple for the sake of uplift.

cc: @NejcZdovc @petemill

**Comment by kjozwiak** [comment]
Definitely an improvement compared to #2486 but I can still see a "small" whitespace padding as @btlechowski mentioned above on `macOS 10.14 x64` using the following build:

Brave | 0.58.14 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Mac OS X

Example of the issue under `macOS 10.14 x64`:

<img width="416" alt="screen shot 2018-12-17 at 2 50 30 pm" src="https://user-images.githubusercontent.com/2602313/50111772-86bdeb00-020b-11e9-80de-34a07b05ed1b.png">

**Comment by ryanml** [comment]
@kjozwiak thanks for checking this out.

A hardened fix has been introduced here: https://github.com/brave/brave-core/issues/1111

Just needs to be reapproved for uplift

**Comment by btlechowski** [comment]
Reproduced on Ubuntu 17..10

Brave | 0.58.14 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Linux

![image](https://user-images.githubusercontent.com/34715963/50128997-8e1ade00-0277-11e9-876f-5008cccdd4a4.png)
