### ISSUE TITLE
Integrate SNS into Brave wallet to allow users send tokens via .sol domains directly

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#25907]
Integrate SNS into Brave wallet to allow users send tokens via .sol domains directly
github doc: https://bonfida.github.io/solana-name-service-guide/wallet-guide.html

Complete the native resolution of SNS records inside Brave’s browser
github doc: https://github.com/Bonfida/name-resolver

cc @yrliou

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.47.164 Chromium: 109.0.5414.74 (Official Build) (64-bit)
-- | --
Revision | `e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}`
OS | Linux

- Verified steps from [brave/brave-core#15617](https://github.com/brave/brave-core/pull/15617)
- Verified with RPC endpoint set to `https://mainnet-beta-solana.brave.com/rpc`
- Verified `onybose.sol` resolves to `5wytVPbjLb2VCXbynhUQabEZZD2B6Wxrkvwm6v6Cuy5X `  (SOL record on domain)
- Verified `brave.onybose.sol` resolves to `3nCNLXJw9FEXgByDLffv2mC9233EdFHnoJx2MySRrhuR `  (SOL record on domain)
- Verified `bonfida.sol` resolves to `HKKp49qGWXd639QsuH7JiLijfVW5UtCVY4s1n2HANwEA ` (NFT domain)

https://user-images.githubusercontent.com/17010094/211299682-61abb5cd-7c5d-4319-aece-ad34d6664a6d.mp4


---------------------

Verification passed on 

Brave | 1.47.164 Chromium: 109.0.5414.74 (Official Build) (64-bit)
-- | --
Revision | `e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#15617](https://github.com/brave/brave-core/pull/15617)
- Verified with RPC endpoint set to `https://mainnet-beta-solana.brave.com/rpc`
- Verified `onybose.sol` resolves to `5wytVPbjLb2VCXbynhUQabEZZD2B6Wxrkvwm6v6Cuy5X `  (SOL record on domain)
- Verified `brave.onybose.sol` resolves to `3nCNLXJw9FEXgByDLffv2mC9233EdFHnoJx2MySRrhuR `  (SOL record on domain)
- Verified `bonfida.sol` resolves to `HKKp49qGWXd639QsuH7JiLijfVW5UtCVY4s1n2HANwEA ` (NFT domain)

https://user-images.githubusercontent.com/17010094/211299717-d761377f-497a-435e-83b6-4755ee4b7f19.mp4


---------------------

Verification passed on 

Brave | 1.47.164 Chromium: 109.0.5414.74 (Official Build) (arm64)
-- | --
Revision | `e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#15617](https://github.com/brave/brave-core/pull/15617)
- Verified with RPC endpoint set to `https://mainnet-beta-solana.brave.com/rpc`
- Verified `onybose.sol` resolves to `5wytVPbjLb2VCXbynhUQabEZZD2B6Wxrkvwm6v6Cuy5X `  (SOL record on domain)
- Verified `brave.onybose.sol` resolves to `3nCNLXJw9FEXgByDLffv2mC9233EdFHnoJx2MySRrhuR `  (SOL record on domain)
- Verified `bonfida.sol` resolves to `HKKp49qGWXd639QsuH7JiLijfVW5UtCVY4s1n2HANwEA ` (NFT domain)

https://user-images.githubusercontent.com/17010094/211299941-4c396901-47b6-46f8-8e22-211497ffb07a.mov
