### ISSUE TITLE
site comments not working when shields enabled

### ISSUE THREAD

**Issue by tenapps2** [brave/brave-browser#25900]
## Description 

when shields are enabled (standard) the comments on this site are not working:
https://www.tomshw.it/hardware/intel-arc-a770-limited-edition-avvistata-in-germania-a-431-euro/

after the article there is a button for vieweing comments. if I click the button the page scrolls to the top and shows no comments.
if I disable the shields then the button shows correctly the comments section (disqus).

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/8171b3a509146e062f831c88a3fbbd827865a728  Give it 24/48hrs, update will go out. @tenapps2
