### ISSUE TITLE
Vertical tabs reorder themselves when selected, occasionally pop out into a new window

### ISSUE THREAD

**Issue by Coffeeling** [brave/brave-browser#25910]
## Description 
When using Brave Nightly, clicking on a tab causes it to jump to a different place in the tab list, and occasionally into a new window.

## Steps to Reproduce

   1. Click on a vertical tab.

## Actual result:

Tab changes position in tab order, or is instantly dragged into a new window.

## Expected result:

Clicking on a tab just focuses it.

## Reproduces how often: 

[Easily reproduced]

Occurs every time.

## Brave version (brave://version info)

Brave	1.46.49 Chromium: 106.0.5249.103 (Official Build) nightly (64-bit) 
Revision	182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}
OS	Windows 10 Version 21H2 (Build 19044.2006)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
    - Not tested 
- Can you reproduce this issue with the beta channel? 
    - Not tested
- Can you reproduce this issue with the nightly channel? 
    - Yes

## Other Additional Information:

Normal tab strip works fine. Given how the tabs feel, I think it's something like even normal clicks getting registered as hold-clicks. If I hold-click tabs, they never jump out into a new window, for example, because I'm intentionally managing them. A simple click could get registered as a drag event and letting go, so the tab gets dragged into a new window.

**Comment by Coffeeling** [comment]
Update: This seems to have something to do with the top banner on the new tab page that tells me to import bookmarks. When I made all tabs into actual websites, things seem to work as expected @sangwoo108

**Comment by sangwoo108** [comment]
Hi, @Coffeeling ! Thank you for reporting this. We're aware of this problem. As you alreay found, when there's an info bar or bookmarks bar in a newly activated tab, dragging is kicked off due to y coordination change.

cc @petemill

**Comment by Coffeeling** [comment]
The Edge solution seems to be to extend vert tablist up to the address bar and just start the bookmarks bar from the list's right edge:

![image](https://user-images.githubusercontent.com/54371213/195228647-8407d468-537b-4488-8f89-62f176e393f4.png)

If set to collapse and expand on hover:

![image](https://user-images.githubusercontent.com/54371213/195228684-e0f0d6f1-0e93-4b8e-8f13-6548e98fccff.png)

![image](https://user-images.githubusercontent.com/54371213/195228738-aeb40c95-ba4f-4461-8a98-1a4e3f0291e8.png)

**Comment by sangwoo108** [comment]
Thanks @Coffeeling for the idea. Seeing your comment, I was wondering what happens if vertical tab strip is pinned. And I found out that they customized the bookmark bar's position so that it doesn't interfere with vertical tabs coordinate. This will be applied only when you're using the "Show bookmarks bar only on New tab" option. Looks quite smart. cc @petemill 

### When bookmarks bar appears only on ntp
<img width="798" alt="image" src="https://user-images.githubusercontent.com/5474642/195324860-b3a6d08a-fa03-4f99-bf22-30315558ba2b.png">

### When bookmarks bar is always visible
<img width="543" alt="image" src="https://user-images.githubusercontent.com/5474642/195325030-872f9fcf-1996-4b63-b1c0-4379e2a98b04.png">

**Comment by sangwoo108** [comment]
Possibly https://github.com/brave/brave-browser/issues/26688 could solve this.

**Comment by anonghuser** [comment]
Or you can compare screen or window coordinates of mouse down and up and not count as a drag if they match, regardless of "element" coordinates changing. Or if the time between mousedown and mouseup is unreasonably small (I guess below 100-150ms) not count it too,
