### ISSUE TITLE
VPN sometimes doesn't auto-connect right after purchase

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#25912]
## Description 

VPN sometimes doesn't auto-connect right after purchase

## Steps to Reproduce

   1. install `1.46.69`
   2. launch Brave
   3. set `VPN` and `SDK` flags in `brave://flags` to `Enabled`
   4. click on `Relaunch`
   5. purchase VPN from `account.brave.software`
   6. click on the `Refresh VPN` button on the webpage
   7. click on the `VPN` button on the browser toolbar
   8. click to toggle it to `Connected`
   9. click `Allow` to add VPN config to macOS when prompted
   10. wait (nothing happens) 
   11. click again on the `VPN` button on the browser toolbar
   12. click to try to toggle it to `Connected`
   13. eventually you're able to connect

## Actual result:

VPN doesn't always auto-connect after its initial purchase

![vpn-auto-connect](https://user-images.githubusercontent.com/387249/195153469-2a6a01a8-2b63-45f5-8e45-ddaab7e4825a.gif)

## Expected result:

VPN should auto-connect after the config gets loaded into macOS

## Reproduces how often: 

It varies - sometimes it works, sometimes (most), it doesn't

## Brave version (brave://version info)

Brave | 1.46.49 Chromium: 106.0.5249.103 (Official Build) nightly (x86_64)
-- | --
Revision | 182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}
OS | macOS Version 11.7 (Build 20G817)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

cc @LaurenWags @spylogsster @simonhong @bsclifton @mattmcalister

**Comment by LaurenWags** [comment]
++ I run into this often

**Comment by stephendonner** [comment]
Closing as a duplicate of https://github.com/brave/brave-browser/issues/25895, which @simonhong filed and fixed 👍
