### ISSUE TITLE
Update "Error: Different account region" error modal text

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#25918]
## Description

Change to:

> **Error: Country mismatch**
> 
> Hmm, it looks like your Brave Rewards country does not match the country of the {{custodian}} account you’re trying to connect. Learn more.

Learn more goes to: https://support.brave.com/hc/en-us/articles/9809690466061

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```
Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (64-bit)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | Windows 10 Version 21H2 (Build 19044.2130)
```
- Verified the `Country mismatch` error message for the custodians `Uphold` and `Gemini`

**Comment by GeetaSarvadnya** [comment]
@Miyayes @szilardszaloki I can verify the updated `Country mismatch` error message only for the Uphold custodian. How do we verify this for other custodians any idea? Gemini custodian is disabled for `IN` region in the brave://rewards UI.
cc: @LaurenWags 
![image](https://user-images.githubusercontent.com/38657976/198690621-07ed468b-d3ad-4c8d-9d73-7d955f1c8854.png)

**Comment by szilardszaloki** [comment]
Hi @GeetaSarvadnya,
Going to Slack DM.

**Comment by szilardszaloki** [comment]
This error modal is shown on two scenarios now:
- if regions don't match when changing wallet providers (e.g. verifying with a US Uphold account, then trying to verify with a CA Gemini account)
- if declared geo doesn't match the one the wallet provider account is set to (e.g. declaring geo as CA, then trying to verify with a US Uphold account) `<<<` _this is going to be the primary use case from now on_

If you want to test Gemini, just pick a region (where Gemini is enabled) from the dropdown list, then try to verify with a Gemini account outside this region.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.46.90 Chromium: 107.0.5304.91 (Official Build) beta (x86_64)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | macOS Version 12.6.1 (Build 21G217)
```

**Comment by Uni-verse** [comment]
In progress on Android ARM

Clean
- new wallet gemini (mismatch geo)
- gemini -> uphold (mismatch geo)
- gemini -> gemini (mismatch geo)

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy Tab S7` using the following build(s):

```
Brave	1.46.129 Chromium: 108.0.5359.48 (Official Build) (64-bit) 
Revision	18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}
OS	Android 12; Build/SP1A.210812.016
```

Verified some scenarios based on https://github.com/brave/brave-browser/issues/25918#issuecomment-1329476435 on Samsung Tablet to spot check country mismatch error for clean and upgraded profile.

Example | Example | Example | Example
-|-|-|-
![screenshot-1669662616066](https://user-images.githubusercontent.com/17885425/204365956-68300c25-a773-4f4f-992f-922a71945b79.png) | ![screenshot-1669662616066](https://user-images.githubusercontent.com/17885425/204365969-a36d704e-31d7-475c-83f1-74d2187b4ef0.png) | ![screenshot-1669662509982](https://user-images.githubusercontent.com/17885425/204366007-26985a83-5b61-45b5-ab22-820d5b45703f.png) | ![screenshot-1669662836268](https://user-images.githubusercontent.com/17885425/204366021-2f258f59-a0b3-452d-811e-7a0df509db88.png)
