### ISSUE TITLE
Padding is too small between `Word Code` and `QR Code` in `view sync code` modal

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#2591]
## Steps to Reproduce

1. Sync two devices
2. In Desktop Browser click `view sync code`

## Actual result:

Padding is too small between `Word Code` and `QR Code`
![image](https://user-images.githubusercontent.com/34715963/50061318-4c1e6900-019f-11e9-8f5d-aa54c50ff1ed.png)

## Expected result:
Example:
![image](https://user-images.githubusercontent.com/34715963/50061380-1a59d200-01a0-11e9-9ed3-03e39e18d69c.png)

## Brave version (brave://version info)

Brave | 0.58.14 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Windows 7

@cezaraugusto @bradleyrichter @brave/legacy_qa

**Comment by kjozwiak** [comment]
Reproducible on `macOS 10.14 x64` using the following build:

Brave | 0.58.14 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Mac OS X

<img width="713" alt="screen shot 2018-12-17 at 11 50 54 am" src="https://user-images.githubusercontent.com/2602313/50102067-28d0d980-01f2-11e9-8fc1-eb17d4e44cd0.png">

Would be nice to fix before this before `0.58.x` goes out the door with sync enabled, but definitely not a blocker/critical.

**Comment by cezaraugusto** [comment]
cc @rossmoody

**Comment by cezaraugusto** [comment]
moving to 0.59 per last sync meeting

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.59.20 Chromium: 72.0.3626.28 (Official Build) beta(64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Linux

* View Sync code only shows either Code words/QR code as per new UI
