### ISSUE TITLE
PNG file optimization [Android]

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#25911]
## Description 
Thread: https://bravesoftware.slack.com/archives/C0816QH3R/p1665501581524649
Chromium Thread: https://chromium.googlesource.com/chromium/src/+/HEAD/docs/speed/binary_size/optimization_advice.md#optimizing-images

Testing Objectives: 
1. Perform sanity check for all png files to ensure image quality has not degraded 
2. Perform regression checks for flows involving handling images for the app (rendering, downloading, sharing)
3. Reduction in APK size. 

## Brave version
1.45.x

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.46.87 x64 Beta build
- Verified all icons on the app looks fine
- Verified all icons are rendered correctly
------------
Verification passed on Samsung Tab A with Android 10 running 1.46.87 x64 Beta build
- Verified all icons on the app looks fine
- Verified all icons are rendered correctly
