### ISSUE TITLE
Brave News Top Sources Migration fix

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#25924]
The |GetLocales| function was changed to return the V1 locale. Unfortunately this broke the top sources migration, as the V1 locale for most regions is "" (the empty string). This meant when we ran the migration users would be subscribed to the `Top Sources` channel but only in the "" region. When switching to V2 they would get a proper locale, but they wouldn't be subscribed to sources in that region.

The fix is to only subscribe to `Top Sources` when the V2 flag is enabled.

**Comment by LaurenWags** [comment]
@fallaciousreasoning can you please add `OS/Desktop` or `OS/Android` - or both, depending on where this fix needs to be QA'ed? Thanks!

cc @rebron @kjozwiak

**Comment by fallaciousreasoning** [comment]
Done, sorry about that.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.46.73 Chromium: 107.0.5304.62 (Official Build) beta (x86_64)
-- | --
Revision | 1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942}
OS | macOS Version 11.7 (Build 20G817)



### default, only enabled Brave News (no source changes)
<details>

1. launched Brave
2. opened a new-tab page
3. scrolled down and clicked on `Show Brave News`
4. restarted Brave
5. set `brave://flags/#brave-news-v2` to `Enabled`
6. opened a new-tab page
7. scrolled and ensured I still saw articles
8. clicked on `Customize`
9. confirmed I was subscribed to the `Top Sources` feed

`News, v1` | `brave://flags`| `News, v2` | `News, v2`
---------|---------|---------|----------
<img width="1312" alt="Screen Shot 2022-10-21 at 3 28 54 PM" src="https://user-images.githubusercontent.com/387249/197297894-e7274b41-257f-4a2c-825d-e22bbfe6943d.png"> | <img width="1312" alt="Screen Shot 2022-10-21 at 3 24 00 PM" src="https://user-images.githubusercontent.com/387249/197297561-d65a122a-68e0-4bbf-a833-285b7b28468a.png"> | <img width="1312" alt="Screen Shot 2022-10-21 at 3 32 59 PM" src="https://user-images.githubusercontent.com/387249/197298151-2a30b67f-496d-47d2-806b-78e9639b7507.png"> | <img width="1312" alt="Screen Shot 2022-10-21 at 3 33 13 PM" src="https://user-images.githubusercontent.com/387249/197298155-7445d3d6-93d8-4060-91b3-3b3feee0ea76.png">




</details>

### customized Brave News feed
<details>
launch Brave

</details>
