### ISSUE TITLE
Takes multiple reconnection attempts to re-add missing VPN config

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#25925]
## Description 

Takes multiple reconnection attempts to re-add missing VPN config

## Steps to Reproduce

   1.  install `1.46.49`
   2. launch Brave
   3. set up Brave VPN
   4. disconnect from Brave VPN
   5. open `System Preferences...` -> `Network`
   6. select `BraveVPN`
   7. click on the `-` button below
   8. click `Apply`
   9. now, click on the `VPN` button on the browser toolbar
   10. toggle from `Disconnected` to `Connecting...`
   11. wait for it to fail
   12. click `Try again` a bunch of times
   13. switch servers, click `Connect`
   14. when prompted, restore the `BraveVPN` config by clicking `Allow`
   15. try to connect to `BraveVPN`

## Actual result:

It takes a few tries to get prompted to re-add the `BraveVPN` config (or maybe it's just time-delayed, and I wasn't patient enough)

![VPN](https://user-images.githubusercontent.com/387249/195215454-d8d0c5e4-1235-4d74-8a41-722e89a1d649.gif)

## Expected result:

Should prompt to re-add the `BraveVPN` config during the 1st reconnection attempt

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.46.49 Chromium: 106.0.5249.103 (Official Build) nightly (x86_64)
-- | --
Revision | 182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}
OS | macOS Version 11.7 (Build 20G817)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

cc @brave/qa-team @rebron @bsclifton @spylogsster @simonhong

**Comment by simonhong** [comment]
https://github.com/brave/brave-core/pull/15404 will resolve some parts of this issue.

**Comment by stephendonner** [comment]
> [brave/brave-core#15404](https://github.com/brave/brave-core/pull/15404) will resolve some parts of this issue.

Oh nice, I didn't even look for/see that issue 👍 Will re-test after that lands.

**Comment by bsclifton** [comment]
@stephendonner let us know if this fixes the issue for you 🙂 When I had tested the original PR it worked for me

**Comment by bsclifton** [comment]
Closing this for now - let's re-open if it's still an issue (should be fixed)

**Comment by stephendonner** [comment]
So sorry for the epic delay in circling back, @bsclifton and @simonhong.  At least I have good news ;-)

This works for me using 

Brave | 1.47.33 Chromium: 107.0.5304.91 (Official Build) nightly (x86_64)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | macOS Version 11.7.1 (Build 20G918)

![vpn](https://user-images.githubusercontent.com/387249/199128831-69bb3ee9-a158-4994-bff7-a4fec9da9f24.gif)
