### ISSUE TITLE
Rename `Brave Sync` to `Sync` in settings

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#2592]
Follow up from https://github.com/brave/brave-browser/issues/1183

## Steps to Reproduce

   1. Go to `brave://settings`
   2. Scroll down to `Brave Sync`

## Actual result:

The section is named `Brave Sync`
![image](https://user-images.githubusercontent.com/34715963/50061970-82121c00-01a4-11e9-8412-d1f3806d08f0.png)

## Expected result:
The section is named `Sync`

## Brave version (brave://version info)

Brave | 0.58.14 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Windows 7

@rebron @cezaraugusto @brave/legacy_qa

**Comment by LaurenWags** [comment]
Reproduces on macOS. Additionally, do we want to change the wording in the box from 'Access Brave Sync...' to 'Access Sync...'?


Brave | 0.58.14 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Mac OS X

**Comment by cezaraugusto** [comment]
moving to 0.59 per last sync meeting

**Comment by darkdh** [comment]
If we rename this, we also need to rename the menu item
<img width="373" alt="screen shot 2018-12-17 at 11 31 36" src="https://user-images.githubusercontent.com/11330831/50110603-89aae280-01ef-11e9-82c6-6a5cf354775b.png">

**Comment by btlechowski** [comment]
Reproduces on Ubuntu 17.10

Brave | 0.58.14 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Linux

**Comment by GeetaSarvadnya** [comment]
Verification passed on 


Brave | 0.59.13 Chromium: 72.0.3626.28 (Official Build) beta (64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Windows



![image](https://user-images.githubusercontent.com/38657976/50537023-e8257880-0b80-11e9-94e2-15a5539bb912.png)
