### ISSUE TITLE
Re-enable infobar for default browser ask

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#25929]
Use upstream's infobar for default browser asking

1. Set non brave as a default default browser
2. Launch brave with clean profile
3. Create NTP and relaunch
4. Check default browser infobar is visible
5. Click set default button and relaunch
6. Check infobar is not visible anymore
7. Set non brave as a default browser and relaunch Brave
8. Check infobar is visible
9. Dismiss infobar by clicking `x` and relaunch
10. Check infobar is not visible

Note: after dismiss, infobar is not shown again. To make visible, we should provide refresh period via griffin.
Or, this dismiss flag is cleared when user set Brave as a default.

From the `bool ShouldShowDefaultBrowserPrompt(Profile* profile)`, it checks refresh days after dismissed.
As we don't provide this value yet, it's not shown again. This will be handled by https://github.com/brave/brave-browser/issues/25930
```
    base::StringToInt(variations::GetVariationParamValue(
                          "DefaultBrowserInfobar", "RefreshPeriodDays"),
```

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.46.64 Chromium: 107.0.5304.36 (Official Build) nightly (64-bit)
-- | --
Revision | 2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}
OS | Windows 11 Version 21H2 (Build 22000.1098)
```

Pre requisites:

- open windows settings>Apps>Default Apps
- search for Firefox in `Set defaults for applications`
- click on Firefox for .html type
- click Firefox 
- click OK


Ex1|Ex2|Ex3
---|---|---
<img width="601" alt="image" src="https://user-images.githubusercontent.com/98358127/196305957-5811b3d8-56b5-4eea-8936-5c56d072c6b6.png">|<img width="605" alt="image" src="https://user-images.githubusercontent.com/98358127/196305980-af34a442-fef3-4855-890e-71ad8dda3a28.png">|<img width="605" alt="image" src="https://user-images.githubusercontent.com/98358127/196306397-e4f68495-26d5-42d9-8d64-0f2f77cf5e8a.png">


1. Install 1.46.64
2. launch Brave
3. click to open NTP
4. close the browser
5. return to windows settings>>Apps>default apps>Firefox
6. click Set default
7. restart browser
8. confirmed the infobar is displayed `Brave isn't your default browser with `Set as default``
10. do not click `Set as default ` button 
11. close and restart the browser
12. infobar still displayed
13. open brave://settings 
14. `Make default` button is displayed
16. click `x` button to dismiss `infobar`


Ex1|Ex2|Ex3
----|----|-----
<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/196305108-83ebcd7c-8c8d-414c-a441-7e3199efd5df.png">|<img width="465" alt="image" src="https://user-images.githubusercontent.com/98358127/196305146-00325fc3-af1f-4e9d-9a06-146fcdb5ae1d.png">|<img width="455" alt="image" src="https://user-images.githubusercontent.com/98358127/196307134-c42226d1-5ead-480c-b0da-f39eb5fb1e3d.png">|<img width="464" alt="image" src="https://user-images.githubusercontent.com/98358127/196307284-02b6ad53-c57d-4ae2-ad1a-e480f0bd6b7c.png">

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.46.86 Chromium: 107.0.5304.91 (Official Build) beta (x86_64)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | macOS Version 11.7.1 (Build 20G918)

### Pre-requisites:
<details>

1. opened `Apple` -> `System Preferences` -> `General`
2. under `Default web browser`, choose `Firefox.app`

<img width="780" alt="Screen Shot 2022-10-31 at 10 10 44 AM" src="https://user-images.githubusercontent.com/387249/199068009-e8606649-a4b3-473a-98b1-5c0514957f37.png">

</details>

### Case 1: `infobar` is visible - `PASSED`
<details>

1. followed pre-requisite steps
2. launched Brave
3. clicked `Maybe later` on the first-run dialog `Ready for the best privacy online?`
5. opened a new-tab page
6. closed Brave
7. relaunched Brave


#### Confirmed the infobar `Brave isn't your default browser`, with `Set as default` was shown

<img width="1312" alt="Screen Shot 2022-10-31 at 10 20 12 AM" src="https://user-images.githubusercontent.com/387249/199070371-72cc9256-7f20-4dda-ba74-6103ded80a9f.png">

</details>

### Case 2: dismiss the `infobar` -  `PASSED`
<details>

1. continue from Case 1
2. click `x` on the infobar
3. close and relaunch Brave
4. infobar is no longer available
5. `brave://settings` still shows `Make default` button

step 2 | step 5
-------|-------
<img width="1312" alt="Screen Shot 2022-10-31 at 10 20 12 AM" src="https://user-images.githubusercontent.com/387249/199073337-564addba-09f0-495a-a687-3d9477779efe.png"> | <img width="1181" alt="Screen Shot 2022-10-31 at 10 27 17 AM" src="https://user-images.githubusercontent.com/387249/199071018-c54aebbf-ac75-40d9-8d6f-ad24b727b8ee.png">

</details>

### Case 3: `brave://settings` - `PASSED`
<details>

1. new profile
2. follow pre-requisites
3. launch Brave
4. click `Maybe Later` on the first run dialog `Ready for the best privacy online?`
5. click to open NTP
6. close Brave
7. relaunch Brave
8. do not click `Set as default` button in the infobar
9. open `brave://settings`
10. `Make default` button is displayed
11. click `Make default` button
12. `Brave is your default browser` tab is displayed
13. go to Slack and click on any link

step 8 | step 10 | step 11 | step 12 | result
-------|--------|---------|-------|-------
<img width="1312" alt="Screen Shot 2022-10-31 at 10 33 29 AM" src="https://user-images.githubusercontent.com/387249/199072720-8793d1ac-c875-4f76-bb21-41ba62b20917.png"> | <img width="1312" alt="Screen Shot 2022-10-31 at 10 34 24 AM" src="https://user-images.githubusercontent.com/387249/199072744-71ce2b10-ebdf-4639-8dfd-3e04b5bd31c9.png"> | <img width="1201" alt="Screen Shot 2022-10-31 at 10 35 00 AM" src="https://user-images.githubusercontent.com/387249/199072748-345e3d5c-8cee-421b-bfb0-756be723da2c.png"> | <img width="1268" alt="Screen Shot 2022-10-31 at 10 35 07 AM" src="https://user-images.githubusercontent.com/387249/199072752-00e6544c-6f9d-4a15-b5af-e35c64393b6a.png"> | <img width="1312" alt="Screen Shot 2022-10-31 at 10 35 51 AM" src="https://user-images.githubusercontent.com/387249/199072754-3f6d42ee-cead-43b0-be77-003de8a2ec96.png">


</details>

### Case 4: `Set Brave as default` from `infobar` - `PASSED`
<details>

1. followed pre-requisites
2. new profile
3. launched Brave
4. clicked `Maybe Later` on the first-run dialog `Ready for the best privacy online?`
5. clicked to open NTP
6. closed Brave
7. relaunched Brave
8. clicked `Set as default` button on the infobar
9. infobar is no longer visible
10. opened `brave://settings`
11. `Brave is your default browser` tab is displayed
12. went to Slack and clicked on a link

step 4 | step 8 | step 10-11 | result
-------|-------|------------|--------
<img width="512" alt="Screen Shot 2022-10-31 at 10 49 03 AM" src="https://user-images.githubusercontent.com/387249/199075942-4f687700-c846-4714-8b83-d8fac5d74f1e.png"> | <img width="1202" alt="Screen Shot 2022-10-31 at 10 50 51 AM" src="https://user-images.githubusercontent.com/387249/199076142-694370d2-1806-4ced-9fab-fa52447b8df5.png"> | <img width="1312" alt="Screen Shot 2022-10-31 at 10 51 56 AM" src="https://user-images.githubusercontent.com/387249/199076146-466212cb-f27b-43d7-ae31-117b33c261a8.png"> | <img width="1312" alt="Screen Shot 2022-10-31 at 10 54 57 AM" src="https://user-images.githubusercontent.com/387249/199076232-bf692a3a-5bce-4f88-b260-03aa6faabd0a.png">



#### Confirmed Brave Beta is default browser as the link opened in Brave Beta as expected

</details>

### Case 5: `Set Brave as a default` from first run dialog - No `infobar` is available - `PASSED`
<details>

1. follow pre-requisite steps
2. new profile
3. clicked `Set Brave as default` button on the first-run dialog
4. clicked `Skip welcome tour` to open NTP
5. closed and relaunched the browser

#### Confirmed no `infobar` is visible

step 1 | step 3 | step 3b | result
------|--------|---------|------
<img width="780" alt="Screen Shot 2022-10-31 at 11 09 03 AM" src="https://user-images.githubusercontent.com/387249/199080705-e1f087a8-4e47-42a3-8a3a-f7ca651c8cc8.png"> | <img width="512" alt="Screen Shot 2022-10-31 at 11 05 38 AM" src="https://user-images.githubusercontent.com/387249/199078910-9c7b7a0f-a1a9-4dd2-bb3d-b4f75d09fee0.png"> | <img width="1196" alt="Screen Shot 2022-10-31 at 11 11 53 AM" src="https://user-images.githubusercontent.com/387249/199079787-1be78d93-fecb-4f7f-94ef-90a1e94c805a.png"> | <img width="1312" alt="Screen Shot 2022-10-31 at 11 13 29 AM" src="https://user-images.githubusercontent.com/387249/199079792-0fd56c72-1e2d-4597-a8ca-9c7895efc0fd.png">

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.46.106 Chromium: 107.0.5304.110 (Official Build) beta (64-bit) 
Revision	2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}
OS	Linux
```
