### ISSUE TITLE
Upgrade from Chromium 106.0.5249.103 to Chromioum 106.0.5249.119

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#25926]
Minor Chromium bump.

https://chromium.googlesource.com/chromium/src/+log/106.0.5249.103..106.0.5249.119?pretty=fuller&n=10000

QA tests:

Check branding items
Check for version bump

Additional checks:

No specific code changes in Brave (only line number changes in patches).

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 13` using the following build(s):

```
Brave | 1.44.112 Chromium: 106.0.5249.119 (Official Build) (32-bit)
--- | ---
Revision | 9f2101830b56fd2ea1408287f6c74e253ebcb7c6-refs/branch-heads/5249@{#797}
OS | Android 13; Build/T1B2.220916.004
```

**`Example`** | **`Example`**
---------------|------------------
![Screenshot_20221012-004811](https://user-images.githubusercontent.com/2602313/195253100-39742b0c-5c18-4fc8-9351-6917c56db2d0.png) | ![Screenshot_20221012-004804](https://user-images.githubusercontent.com/2602313/195253104-3784c725-7df9-4798-ba92-a90d4da038a8.png)

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```

Brave | 1.44.112 Chromium: 106.0.5249.119 (Official Build) (64-bit)
-- | --
Revision | 9f2101830b56fd2ea1408287f6c74e253ebcb7c6-refs/branch-heads/5249@{#797}
OS | Windows 10 Version 21H2 (Build 19044.2006)

```
![image](https://user-images.githubusercontent.com/38657976/195315689-e1439c4a-e7b6-42d6-82f6-43aebbd85652.png)

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.44.112 Chromium: 106.0.5249.119 (Official Build) (arm64) 
Revision	9f2101830b56fd2ea1408287f6c74e253ebcb7c6-refs/branch-heads/5249@{#797}
OS	macOS Version 12.6 (Build 21G115)
```

<img width="1199" alt="Screen Shot 2022-10-12 at 8 57 13 AM" src="https://user-images.githubusercontent.com/28145373/195349482-0c081271-ec10-4a8e-ae16-76ca7690a155.png">

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.44.112 Chromium: 106.0.5249.119 (Official Build) nightly (64-bit)
-- | --
Revision | 9f2101830b56fd2ea1408287f6c74e253ebcb7c6-refs/branch-heads/5249@{#797}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/195395446-8cb75ac4-3c82-4d0b-99be-bae19dae430d.png)
