### ISSUE TITLE
Selected Country or region in the Windows OS settings is not shown in the Brave VPN

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#25923]
## Steps to Reproduce

   1.  Install 1.45.x
   2.  Select `Country or region` in settings to `Australia` in Windows OS settings
   3.  Launch Brave
   4.  Enabled SKU/SDK and VPN in the `brave://flags`
   5.  Login to `account.bravesoftware.com` with an existing VPN account
   6.   click VPN button

## Actual result:

It's defaulting to default region (`USA(west)`) instead of  `Australia`
step 2|step 6
----|-----
<image width="900" alt="step2" src="https://user-images.githubusercontent.com/98358127/195204787-70e82fba-47c8-4c40-b57c-e85ca5e92987.png">|<image width="900" alt="step2" src="https://user-images.githubusercontent.com/98358127/195204812-f4bf279c-b0a0-44bb-ae76-089eb645cb25.png">

## Expected result:
It should auto-detect the region to `Australia` based on OS Region settings

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (64-bit)
-- | --
Revision | 182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}
OS | Windows 11 Version 21H2 (Build 22000.978)

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel?  Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
@rebron @bsclifton 
cc: @brave/qa-team

**Comment by stephendonner** [comment]
@MadhaviSeelam if this is one of my testcases, it's likely wrong - it actually goes by timezone.  Did Windows/you also change the timezone?

**Comment by MadhaviSeelam** [comment]
User error @stephendonner.  Thanks for catching.  Retested.  Didn't set to the time zone earlier (thought I did).  Closing the bug.  Working as expected.  Selected country or region shown in the VPN modal
