### ISSUE TITLE
Adblock warning being shown with shields up in brave browsers for this site

### ISSUE THREAD

**Issue by Jarvis991** [brave/brave-browser#25937]
Site >> https://www.rockmods.net/
![image](https://user-images.githubusercontent.com/97823396/195342218-b19a6cfc-0317-48d7-b16e-ce13cc6cea6e.png)

Kindly fix this site with adblocking. Thanks

**Comment by kyoyacchi** [comment]
![Screenshot_20221028-201016](https://user-images.githubusercontent.com/63583961/198694031-1188a62e-f992-4a25-b42a-be8f9a993b48.jpg)
No problem for me.
You may try using Anti Adblock Killer list like i do.
