### ISSUE TITLE
[hackerone] block mixed content on .onion sites

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#25939]
fixed by https://github.com/brave/brave-core/pull/15436

https://hackerone.com/bugs?subject=brave&report_id=1727949&view=open&substates%5B%5D=new&substates%5B%5D=triaged&substates%5B%5D=needs-more-info&reported_to_team=&text_query=&program_states%5B%5D=2&program_states%5B%5D=3&program_states%5B%5D=4&program_states%5B%5D=5&sort_type=latest_activity&sort_direction=descending&limit=25&page=1

credit: [xiaoyinl](https://hackerone.com/xiaoyinl)

**Comment by kjozwiak** [comment]
@LaurenWags looks like we have a few cases that QA can use outlined via https://github.com/brave/brave-core/pull/15436#issuecomment-1276391954 & https://github.com/brave/brave-core/pull/15436#issuecomment-1278406754.

@diracdeltas would the above be sufficient enough re: QA verification? If so, we can remove the `QA/Blocked` label.

**Comment by kjozwiak** [comment]
Removing `QA/Blocked` after speaking with @diracdeltas. As per https://github.com/brave/brave-browser/issues/25939#issuecomment-1338848684, the above should be sufficient enough for verification.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.47.126 Chromium: 108.0.5359.99 (Official Build) beta (64-bit)
-- | --
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | Windows 11 Version 21H2 (Build 22000.1219)
```

1. Install 1.47.126
2. launch Brave
3. click hamburger menu >>New Private window with Tor
4. Wait until Tor connected successfully message
5. visit  http://xao2lxsmia2edq2n5zxg6uahx6xox2t7bfjw6b5vdzsxi7ezmqob6qid.onion/
6. open devtools and enter `fetch("https://www.example.com")` in the console
7. click on Network 
8. confirmed `https://www.example.com/` is not blocked.
9. repeat step 6-7with  `fetch("http://www.example.com")`
10. confirmed https://www.example.com` is blocked with a message `blocked:mixed-content` in the Network

step 3|step 5|step 8|step 9|step 10
-----|-----|-----|----|-----
<img width="952" alt="image" src="https://user-images.githubusercontent.com/98358127/207389543-9194fb60-96a5-4742-85b0-78bc47d37c18.png">|<img width="959" alt="image" src="https://user-images.githubusercontent.com/98358127/207392769-742a1288-ecd6-483f-aa12-ae7fc5445685.png">|<img width="954" alt="image" src="https://user-images.githubusercontent.com/98358127/207419322-3fd0b4ba-7915-4c39-a233-dff0f3aaa356.png">|<img width="956" alt="image" src="https://user-images.githubusercontent.com/98358127/207419500-a9fd890c-9ffa-4424-b36a-a003b1ce9275.png">|<img width="957" alt="image" src="https://user-images.githubusercontent.com/98358127/207419646-71101d02-7fac-4e8b-8fc9-8922b11be85e.png">

Case 2: 
1. visit https://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/index.html in a new tab
12. repeat steps 6-7 


Case 3:

  - visit  https://mixed.badssl.com/ in  a new-tab in Tor window
      - confirmed it shows warning messages in the console about an insecure resource being requested (but was upgraded) 
          - `Mixed Content: The page at 'https://mixed.badssl.com/' was loaded over HTTPS, but requested an insecure element 'http://mixed.badssl.com/image.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html`

<img width="953" alt="image" src="https://user-images.githubusercontent.com/98358127/207427344-8b7e5f2e-0436-4b1f-be62-12212d91808c.png">

-  visited 'http://mixed.badssl.com/image.jpg' in new-tab
    - confirmed this request was automatically upgraded to HTTPS`
   
<img width="947" alt="image" src="https://user-images.githubusercontent.com/98358127/207422742-9f067949-36a9-4a7d-bdc8-ffdcfd8e3f97.png">

- visit https://mixed-favicon.badssl.com/ in a new-tab
    - confirmed it shows error message in the console about favicon being blocked 
        - `Mixed Content: The page at 'https://mixed-favicon.badssl.com/' was loaded over HTTPS, but requested an insecure favicon. 'http://mixed-favicon.badssl.com/favicon.ico'. This request has been blocked; the content must be served over HTTPS.`

<img width="951" alt="image" src="https://user-images.githubusercontent.com/98358127/207422927-b19980c0-e041-42a4-854e-02e2b1e7f9fb.png">

  - visit https://mixed-form.badssl.com/ in a new-tab 
      - confirmed console shown warning
          - Mixed Content: The page at 'https://mixed-form.badssl.com/' was loaded over a secure connection, but contains a form that targets an insecure endpoint 'http://http.badssl.com/resources/form-submitted.html'. This endpoint should be made available over a secure connection.

<img width="953" alt="image" src="https://user-images.githubusercontent.com/98358127/207427025-135acd5f-4c7f-4315-b127-e11b351d541e.png">

  - visit https://mixed-script.badssl.com/ in a new-tab
      - confirmed shown with a grey background and has an error message in the console

<img width="959" alt="image" src="https://user-images.githubusercontent.com/98358127/207423441-f54956f5-8797-400d-ba13-99e4db7a3531.png">

  - visit https://very.badssl.com/ in a new-tab
      - confirmed the page is shown both warnings and errors in the console

<img width="956" alt="image" src="https://user-images.githubusercontent.com/98358127/207423628-2405c68a-94ce-40f8-baa8-21281fdac65b.png">

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.47.135 Chromium: 108.0.5359.128 (Official Build) beta (x86_64)
-- | --
Revision | 1cd27afdb8e5d057070c0961e04c490d2aca1aa0-refs/branch-heads/5359@{#1185}
OS | macOS Version 11.7.2 (Build 20G1020)

### Case 1: `PENDING`
<details>

</details>

### Case 2: `PENDING`
<details>

</details>

### Case 3: `PENDING`
<details>

</details>
