### ISSUE TITLE
No `Sync` label in settings' sidebar

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#2593]
Follow up from https://github.com/brave/brave-browser/issues/1183

## Steps to Reproduce

   1. Go to `brave://settings`
   2. Show `sidebar`

## Actual result:

The is no `Sync` label in `sidebar`

![image](https://user-images.githubusercontent.com/34715963/50062115-8559d780-01a5-11e9-8525-4d3dc2cd5e51.png)

<img width="264" alt="screen shot 2018-12-18 at 1 44 31 am" src="https://user-images.githubusercontent.com/2602313/50136669-7f77fb00-0266-11e9-83d9-86cb26107243.png">

## Expected result:
`Sync` label is in `sidebar`

## Brave version (brave://version info)

Brave | 0.58.14 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Windows 7

@rebron @cezaraugusto @brave/legacy_qa

**Comment by LaurenWags** [comment]
Reproduces on macOS

Brave | 0.58.14 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Mac OS X

**Comment by darkdh** [comment]
@bradleyrichter do we need this? we haven't added any of our stuff like "Brave Shield" and "Brave Sync" into the sidebar

**Comment by cezaraugusto** [comment]
moving to 0.59 per last sync meeting

**Comment by btlechowski** [comment]
Reproduces on Ubuntu 17.10

Brave | 0.58.14 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Linux

**Comment by GeetaSarvadnya** [comment]
Verification passed on 


Brave | 0.59.13 Chromium: 72.0.3626.28 (Official Build) beta (64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Windows



- Verified the STR mentioned in the issue.
![image](https://user-images.githubusercontent.com/38657976/50536670-cf1ac880-0b7c-11e9-80c8-e8ddb2476fc8.png)
