### ISSUE TITLE
`Sync` section is in the wrong place in settings

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#2594]
Follow up from https://github.com/brave/brave-browser/issues/1183

## Steps to Reproduce

   1. Go to `brave://settings`
   2. Scroll down to `Brave Sync`

## Actual result:

The section is between `Brave shields defaults` and `On startup`

![image](https://user-images.githubusercontent.com/34715963/50062269-8f300a80-01a6-11e9-8004-2a3f4678dbd0.png)

## Expected result:
Per comment https://github.com/brave/brave-browser/issues/1183#issue-361490280 `Create new Extensions section in Settings beneath Extensions and before Shield Settings section`

## Brave version (brave://version info)

Brave | 0.58.14 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Windows 7

@rebron @cezaraugusto @brave/legacy_qa

**Comment by LaurenWags** [comment]
Reproduces on macOS

Brave | 0.58.14 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Mac OS X

**Comment by btlechowski** [comment]
Reproduces on Ubuntu 17.10

Brave | 0.58.14 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Linux

**Comment by srirambv** [comment]
Verification passed on Linux however the name is still not changed to Sync. Reopened the issue(#2758) as its being reproduced on several machines and needs to be investigated

Brave | 0.59.14 Chromium: 72.0.3626.28 (Official Build) beta(64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Linux

![image](https://user-images.githubusercontent.com/17010094/50628005-2beef800-0f5c-11e9-994d-d8f2dab942ad.png)
