### ISSUE TITLE
Infinite page reload

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#25946]
## Description 

Unable to use brave vpn 

https://user-images.githubusercontent.com/2965009/195415010-e19e0947-0dea-4325-acb3-d5ea83942f43.mp4

In sniffer I see requests to m.stripe.com/6

![image](https://user-images.githubusercontent.com/2965009/195416064-0507b14d-89e2-4622-aebe-04a8223c1b22.png)

## Steps to Reproduce

   1. Clean profile
   2. Enable brave vpn/skus in flags
   3. Click already purchased in popup
   4. type email
   5. go to link from email
   6. infinite page reloading

## Actual result:

infinite page reloading

## Expected result:

VPN page with plans

## Reproduces how often: 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by spylogsster** [comment]
Fixed by @AlanBreck

**Comment by stephendonner** [comment]
> Fixed by @AlanBreck on server side

Great; mind pointing to the fix, @AlanBreck @spylogsster ?

**Comment by AlanBreck** [comment]
Here's the relevant fix: https://github.com/brave/account-brave-com/commit/01349e6e8de06b8acd0ebad97004d3e285c3b457#diff-c3a76f211b02106e458d330c6c4dfb09844e51487170b2300cf76913360eda47R81
