### ISSUE TITLE
Fix link colour in dark mode

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#25941]
## Description 

Change colour of links in dark mode

## Actual result:

an e.g. 

![Screenshot from 2022-10-12 21-20-50](https://user-images.githubusercontent.com/11755381/195391544-4ac4642f-86b5-4828-a8d0-17243bff9b39.png)

## Expected result:
use `#A0A5EB` for [links in dark mode](https://github.com/brave/brave-browser/issues/25224#issuecomment-1242182458)

**Comment by ArturAronov** [comment]
Can I contribute and help to fix this issue?

**Comment by Pavneet-Sing** [comment]
@ArturAronov Yes, Happy coding!

**Comment by HEagle18** [comment]
Removing desktop tag from this because there is a new send/swap UI

**Comment by Pavneet-Sing** [comment]
This issue is desktop specific and it can be reproduced on latest nightly `1.48.5`, so adding back the desktop label. Here's a video to reproduce: 

[color-issue.webm](https://user-images.githubusercontent.com/11755381/210523199-a9b7be0a-b537-4f55-b245-16c80318099f.webm)

Note: There could be more links like this, haven't checked all.

cc: @HEagle18

**Comment by Pavneet-Sing** [comment]
BTW, not sure if the new designs are yet to be landed on nightly. In that case, feel free to close this one out if links have the right colour.

**Comment by Pavneet-Sing** [comment]
Closing as no longer valid per new UI: https://github.com/brave/brave-browser/issues/25941#issuecomment-1370004407
