### ISSUE TITLE
Vertical Tabs do not pop out on Mouse over 

### ISSUE THREAD

**Issue by rleyvasal** [brave/brave-browser#25948]
## Description 

It would be great to have an option to make the vertical tabs open on Mouse Over (similar to Edge) instead of the current click on "<" button to look over vertical tabs . Vertical Tabs work very well without issue. Thanks for implementing the new feature. 

## Steps to Reproduce

   1.  Enable flag for vertical tabs
   2.  click on "<" button to show and hide the vertical tabs

## Brave version (brave://version info)

Nightly version: [Version 1.46.49](https://brave.com/latest/)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the nightly channel?  yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? no

## Miscellaneous Information:

Screenshot of the "<" button that has to be pressed to make vertical tabs pop out.
![vertical tabs mouse over](https://user-images.githubusercontent.com/61335136/195447078-1c9ff81f-7b5b-4059-a2c0-bb1ab05a3cfe.png)

**Comment by Coffeeling** [comment]
Have this now in Nightly, but it's very fiddly - they collapse even though my mouse is still over the now-expanded tab list. Feels like the expansion just lets me see what's what but actual operations have to be carried out in the small icon-only state.

**Comment by rebron** [comment]
Hi @rleyvasal We have the vertical tabs panel open on mouseover when collapsed in Beta and Nightly. Can you take a look? @Coffeeling Are you seeing the mouseover/hover as more reliable in the current builds?

**Comment by rebron** [comment]
cc: @sangwoo108 We can probably close this one.

**Comment by sangwoo108** [comment]
Thanks! @rebron . Let me close this.

**Comment by Coffeeling** [comment]
> Hi @rleyvasal We have the vertical tabs panel open on mouseover when collapsed in Beta and Nightly. Can you take a look? @Coffeeling Are you seeing the mouseover/hover as more reliable in the current builds?

Yeah, this is definitely fixed and the tabs are behaving pleasantly.

**Comment by rleyvasal** [comment]
Vertical tabs are working as expected. Thanks!
