### ISSUE TITLE
Rename "view sync code" to "view QR code and Code words" followup to #2549

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#2595]
## Description 

"view sync code" might not be descriptive enough and might confuse with "add device" functionality. Renaming it to "view QR code and Code words" should make it more easy to differentiate the functionalities of both buttons.

## Actual result:

![img](https://user-images.githubusercontent.com/34715963/49958091-12810000-ff0a-11e8-8bce-3494e886429d.png)

**Comment by cezaraugusto** [comment]
moving to 0.59 per last sync meeting

**Comment by GeetaSarvadnya** [comment]
@cezaraugusto Issue still persists on 0.59.12, Is this not yet merged in 0.59.12?

![image](https://user-images.githubusercontent.com/38657976/50406380-400f5880-07ea-11e9-889d-cf8ded878c52.png)

**Comment by GeetaSarvadnya** [comment]
Verification passed on 


Brave | 0.59.13 Chromium: 72.0.3626.28 (Official Build) beta (64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Windows

- Verified the description

![image](https://user-images.githubusercontent.com/38657976/50536466-efe21e80-0b7a-11e9-966d-01bc5e27b541.png)
