### ISSUE TITLE
Hello, I'm a Chinese user. Can "Baidu. com" search be added to the default search of the search engine. Because I need it very much, thank you!

### ISSUE THREAD

**Issue by cc19264997** [brave/brave-browser#25957]
Hello, I'm a Chinese user. Can "Baidu. com" search be added to the default search of the search engine. Because I need it very much, thank you!

**Comment by simonhong** [comment]
@cc19264997 Hello, you can add baidu in search engines list.

1. Load brave://settings/searchEngines
2. Click `Add` button at the bottom of `Search engines` section
3. Fill proper search provider name like `baidu` and shortcut such as `:bd` or whatever you want
4. Fill this `https://www.baidu.com/#ie={inputEncoding}&wd=%s` as a query url
5. Save and make it default

I got query url from https://source.chromium.org/chromium/chromium/src/+/main:components/search_engines/prepopulated_engines.json;l=51?q=prepopulated%20json

**Comment by cc19264997** [comment]
> 
thank you very much!

**Comment by rebron** [comment]
Closing as worksforme.
