### ISSUE TITLE
Cannot connect to iOS sync chain code

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#25952]
## Description 
Cannot connect to sync chain when trying to scan code from iOS device. Able to scan sync code from desktop client.

## Steps to reproduce 

   1. Install 1.44 on Android device
   2. Install 1.44 on iOS device
   3. Start a sync chain on iOS device
   4. Select `add a device` on the IOS device
   5. Begin sync flow on Android device, attempt to scan a sync code on the iOS device with the camera

## Actual result 
Sync code not recognized 

## Expected result
After scanning QR code, user should be prompted to proceed to connect to sync chain

## Issue reproduces how often 
Always

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 12
   
## Brave version
1.44.112

**Comment by deeppandya** [comment]
@Uni-verse would be providing sync chain codes.

**Comment by soner-yuksel** [comment]
As per discussion, made the QR code iOS side way bigger than it is, hopefully this will help the problem.

**Comment by AlexeyBarabash** [comment]
This is fixed with https://github.com/brave/brave-ios/pull/6708
