### ISSUE TITLE
Show exact derivation path when importing from hardware wallet

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#25954]
Follow up to https://github.com/brave/brave-core/pull/15406/files#r993859775

We have these select controls for Ethereum and Solana
![image](https://user-images.githubusercontent.com/168356/195488829-b9aa248a-24aa-45a5-9b70-3fd333c54f28.png)
![image](https://user-images.githubusercontent.com/168356/195488894-46161919-9244-4026-8b52-1641c41c8ea5.png)

We should show somehow give user more information on exact derivation path(`44'/501'/${index}'/0'`) each option means(Tooltip, inline, second row, etc)

For reference, Phantom shows paths as options
![image](https://user-images.githubusercontent.com/4730197/187764102-b68a75a7-3454-4ec4-a889-644c5ca104c2.png)

**Comment by josheleonard** [comment]
@supermassive is there a mojo method that returns this info?

**Comment by supermassive** [comment]
> @supermassive is there a mojo method that returns this info?

Actually these paths are generated in frontend code. 
https://github.com/brave/brave-core/blob/d2a8043b1be036c4412a365079e446fc940f9a34/components/brave_wallet_ui/common/hardware/ledgerjs/sol_ledger_bridge_keyring.ts#L144-L153
https://github.com/brave/brave-core/blob/d2a8043b1be036c4412a365079e446fc940f9a34/components/brave_wallet_ui/common/hardware/ledgerjs/fil_ledger_bridge_keyring.ts#L104-L108
https://github.com/brave/brave-core/blob/d2a8043b1be036c4412a365079e446fc940f9a34/components/brave_wallet_ui/common/hardware/ledgerjs/eth_ledger_bridge_keyring.ts#L210-L220

**Comment by josheleonard** [comment]
@jamesmudgett How's this design-wise?

<img width="582" alt="Screenshot 2023-11-02 at 5 55 04 PM" src="https://github.com/brave/brave-browser/assets/30185185/72279f11-725e-4856-b9a2-c65ccabfac85">
<img width="582" alt="Screenshot 2023-11-02 at 5 54 30 PM" src="https://github.com/brave/brave-browser/assets/30185185/61a9e3dd-e6f5-4fc2-908a-a1e26bbcca0c">

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.62.146 Chromium: 120.0.6099.234 (Official Build) beta (64-bit)
-- | --
Revision | 85d26e25365bbea90074b7bc40ab0c89bbbf26e8
OS | Windows 11 Version 23H2 (Build 22631.3007)

- Verified steps from [rave/brave-core#20818](https://github.com/brave/brave-core/pull/20818)
- Verified derivation path is shown for hardware wallets

Ethereum (Ledger) | Ethereum (Trezor) | Solana (Ledger) 
-- | -- | --
![Screenshot 2024-01-18 030537](https://github.com/brave/brave-browser/assets/17010094/4ccc9a0e-5119-4e96-b184-786d9531b0e0) | ![Screenshot 2024-01-18 030949](https://github.com/brave/brave-browser/assets/17010094/962e8a31-f620-4fed-a61a-82530c27f13f) | ![Screenshot 2024-01-18 030628](https://github.com/brave/brave-browser/assets/17010094/4393c180-1423-4d09-a85a-15a34c02d754)
