### ISSUE TITLE
Delay or Remove inaccurate errors popping up on sends

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#25964]
## Description 

When a user goes to send, the product gives a little error saying 'amount must be greater than zero' before it really has had time to  know whats happening. We should delay this error showing up or remove it.

## Steps to Reproduce

   1. try sends some eth

https://user-images.githubusercontent.com/12224304/195598618-5690602e-d1c1-41bf-956d-21fac66098db.mov

   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by Douglashdaniel** [comment]
The `Buy/Send/Swap` tab will be depreciated in 1.48.x
The new `Send` flow does not have this issue, closing as `not-actionable`.
