### ISSUE TITLE
Tooltips are not contained within tooltip container

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#25975]
## Description 

Tooltips are not contained within tooltip container. Issue seems to be limited to Beta channel alone. Not on Release/Nightly 

## Steps to Reproduce

   1. Hover over tooltips
   
## Actual result:

Password | Address | Button tooltips
-- | -- | --
![Screen Shot 2022-10-13 at 9 21 36 AM](https://user-images.githubusercontent.com/17010094/195611310-ea664b29-fb80-4ccd-a015-35eb3eb0d109.png) | ![Screen Shot 2022-10-13 at 9 22 12 AM](https://user-images.githubusercontent.com/17010094/195611339-206ae4ee-1f30-42f4-abb5-ee5d030f9812.png) | ![Screen Shot 2022-10-13 at 9 22 18 AM](https://user-images.githubusercontent.com/17010094/195611356-797a0d58-8501-4922-9ba6-836f3409daf0.png)
![Screen Shot 2022-10-13 at 9 26 29 AM](https://user-images.githubusercontent.com/17010094/195611370-20c8ba1c-967c-48a6-a319-6f2453bb8a41.png) | ![Screen Shot 2022-10-13 at 9 22 39 AM](https://user-images.githubusercontent.com/17010094/195611368-8560044c-4687-46da-89b1-509209dc3a3a.png) | ![Screen Shot 2022-10-13 at 9 22 31 AM](https://user-images.githubusercontent.com/17010094/195611362-e65caff0-d82b-447f-8c6f-08a2ee04b18d.png) 

## Expected result:

![Screen Shot 2022-10-13 at 9 37 16 AM](https://user-images.githubusercontent.com/17010094/195612169-ff3a18e1-62aa-4c95-b7f4-cc4efe8ebbb5.png) | ![Screen Shot 2022-10-13 at 9 37 27 AM](https://user-images.githubusercontent.com/17010094/195612200-b46b50e1-07f5-4f9e-a9c6-7456ee487b7f.png) | ![Screen Shot 2022-10-13 at 9 37 30 AM](https://user-images.githubusercontent.com/17010094/195612210-ca1acec5-8caa-4c99-9fa3-d209f363c46a.png)
-- | -- | --

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (arm64)
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | macOS Version 12.6 (Build 21G115)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel @josheleonard

**Comment by kjozwiak** [comment]
The above requires `1.45.102` or higher for `1.45.x` verification 👍

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/25495#issuecomment-1282288687
