### ISSUE TITLE
Restyle chrome: pages

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#26]
- [x] Restyle bookmarks
- [x] Restyle history
- [x] Restyle preferences
- [x] Downloads page

**Comment by cezaraugusto** [comment]
task tracked in asana as well ref https://app.asana.com/0/464256022274986/495961382725336/f

**Comment by rebron** [comment]
Closing out. Major restyling work completed in 64.x and 65.x. Will work out remaining polish items in separate issues.
