### ISSUE TITLE
Verbose logging not showing LOG_INFO or LOG_WARNING logs for Brave Ads

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#2600]
## Description 
Verbose logging not showing LOG_INFO or LOG_WARNING for Brave Ads when passing --v=3 as a command-line argument

## Steps to Reproduce

   1. Install Brave Browser Beta 0.59.8
   2. Open `Terminal`
   3. `cd` to the directory of where you have unzipped `Brave Browser Beta.app`
   4. run `./Brave Browser Beta.app/Contents/MacOS/Brave\ Browser\ Beta --brave-ads-staging --v=3` from `Terminal`

## Actual result:
Only LOG_ERROR logs are shown

## Expected result:
LOG_INFO, LOG_WARNING and LOG_ERROR logs should be shown

## Reproduces how often: 
Everytime

## Brave version (brave://version info)
macOS Version 0.59.8 (64-bit)

**Comment by bridiver** [comment]
verbose logging should use VLOG (needs lib/brave-core support similar to LOG)

**Comment by bridiver** [comment]
`--v=3` won't do anything here because we don't have VLOG in ads, but you do need `--enable-logging`

**Comment by tmancey** [comment]
Closing issue as opened https://github.com/brave-intl/bat-native-ads/issues/56 for native lib work, in the mean time we can use `--enable-logging` and `--log-level=0` as above

**Comment by tmancey** [comment]
👍 confirmed working as expected
