### ISSUE TITLE
Replace wallet onboarding conversion P3A question

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#26011]
## Description 

Replace wallet onboarding conversion question with a new one that includes an extra answer for importing accounts.

If you accessed the Wallet page at least once, did you create/import a wallet?
`Brave.Wallet.OnboardingConversion.2`

0) I accessed the wallet onboarding page, but did not set up the wallet
1) Yes, I created a new wallet
2) Yes, I imported/restored an existing wallet

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on `Vivo X70 Pro version 12` running `Bravemonoarmx64.apk`


<details>
<summary>Brave.Wallet.OnboardingConversion.2 = 0_PASSED</summary>

1. Clean profile visit brave://wallet or click on the wallet icon 
2. Ensured that the wallet onboarding page is displayed
3. Open brave://locals-state file
4. Ensured that the metrics `Brave.Wallet.OnboardingConversion.2` response value is `0` as expected



</details>

<details>
<summary>Brave.Wallet.OnboardingConversion.2 = 1_PASSED</summary>

1. Clean profile visit brave://wallet or click on the wallet icon 
2. Ensured that the wallet onboarding page is displayed
3. Create an wallet 
4. Open brave://locals-state file
5. Ensured that the metrics `Brave.Wallet.OnboardingConversion.2` response value is `1` as expected



</details>

<details>
<summary>Brave.Wallet.OnboardingConversion.2 =2_ PASSED</summary>

<details>
<summary>Case 1: Import CW</summary>

1. Clean profile visit brave://wallet or click on the wallet icon 
2. Ensured that the wallet onboarding page is displayed
3. Import an existing CW 
4. Open brave://locals-state file
5. Ensured that the metrics `Brave.Wallet.OnboardingConversion.2` response value is `2` as expected



</details>

<details>
<summary>Case 2: Import MM wallet</summary>

1. Clean profile visit brave://wallet or click on the wallet icon 
2. Ensured that the wallet onboarding page is displayed
3. Import an existing MM wallet 
4. Open brave://locals-state file
5. Ensured that the metrics `Brave.Wallet.OnboardingConversion.2` response value is `2` as expected



</details>

</details>
