### ISSUE TITLE
Update VPN Payment dialog according to Figma

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#26024]
## Actual result:

![image](https://user-images.githubusercontent.com/2965009/195813365-18701600-7ce0-4651-932b-1eccd9fc687c.png)

## Expected result:

<img width="306" alt="image" src="https://user-images.githubusercontent.com/2965009/195813468-183e9fbc-fb2b-4187-8e9d-99cb4e2cac6f.png">

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment]
Updated Figma to match what we have in the product. I'll try to do this for other areas also and then we can review Figma to see if any copy changes needed
