### ISSUE TITLE
Brave Search show links to porno-pages

### ISSUE THREAD

**Issue by Johann999** [brave/brave-browser#26027]
For a few days now, I've been getting under discussions links with the url 'pornfalcon.com'.
Please suppress that. Thank you.

![Porno](https://user-images.githubusercontent.com/53431361/195845542-d0425d4c-4c8e-451d-ab9d-f7665c4b71f7.png)

**Comment by rebron** [comment]
@Johann999 Closing. A fix was pushed to production. Please re-open if you're still seeing issues.
