### ISSUE TITLE
Selecting Filecoin Testnet/Localhost creates a mainnet account and doesn't create account on selected network

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#26026]
## Description 

Selecting Filecoin Testnet/Localhost creates a mainnet account and doesn't create account on selected network

## Steps to Reproduce

   1. Clean profile and create wallet
   2. Create Filecoin account, ensure account starts with `f`
   3. Enable show test networks
   4. Select Filecoin Testnet from network selector
   5. Prompts to create testnet account,
   6. Selecting Yes adds a second Filecoin account on mainnet
   7. Select testnet again, prompt to create a new testnet account is shown again
   8. Selecting yes creates a third mainnet account
   9. Repeat the same steps for localhost, same result ends up creating more mainnet accounts

## Actual result:

https://user-images.githubusercontent.com/17010094/195843218-e733bdc7-f0c8-488e-b6e3-db84b4e2b0d4.mp4

## Expected result:
Network specific accounts should be created

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (64-bit)
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | Windows 11 Version 22H2 (Build 22621.674)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Not checked

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @cypt4 @yrliou

**Comment by kjozwiak** [comment]
The above requires `1.45.106` or higher for `1.45.x` verification 👍

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/24947#issuecomment-1284938319
