### ISSUE TITLE
Sync `I have code words` modal doesn't show words

### ISSUE THREAD

**Issue by cezaraugusto** [brave/brave-browser#2602]
<img width="710" alt="screen shot 2018-12-17 at 4 50 53 pm" src="https://user-images.githubusercontent.com/4672033/50108293-02c02f00-021c-11e9-9f4c-e36147722b01.png">

Sync loads the words and word count shows the right number, you are able to copy words properly but textarea field remains empty

STR:

1. Start a new chain
2. Go to "desktop" option

**Comment by GeetaSarvadnya** [comment]
Verification passed on 


Brave | 0.59.12 Chromium: 72.0.3626.17 (Official Build) beta (64-bit)
-- | --
Revision | 08d2140079f8db14c9eb885a803d231b1a30e817-refs/branch-heads/3626@{#315}
OS | Windows



- Verified the STR mentioned in https://github.com/brave/brave-core/pull/1115
