### ISSUE TITLE
Add unstoppable domains  and ENS support to send UI on mobile

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#26032]
## Description 
https://github.com/brave/brave-core/pull/10529 PR for how its done on desktop

From @Douglashdaniel on desktop

Wired up UnstoppableDomains and ENS Resolution to UI

Refactored/Moved Send methods into a reusable hook useSend, will also clear toAddress and sendAmount after creating transaction.
If a url ends with .eth it will call the ensGetEthAddr method, if the url is registered it will return an address that we will use to send, if the url is not registered will return a Domain <name> is not registered error.
If a url ends with .crypto it will call the unstoppableDomainsGetEthAddr method, if the url is registered it will return an address that we will use to send, if the url is not registered will return a Domain <name> is not registered error.
If the address starts with 0x, it will check if its a valid address, if not it will return a Not a valid ETH address error
If the input value is not recognized it will return a Not a valid address error
## Steps to reproduce 

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by yrliou** [comment]
@simoarpe Is this now supported due to WebUI migration?

**Comment by simoarpe** [comment]
Android fully relies on WebUI, so most likely it's a feature that is now supported. @srirambv can you please give it a quick check just to be extra sure?

**Comment by srirambv** [comment]
This now works on Android. 

![image](https://github.com/brave/brave-browser/assets/17010094/e7c262bc-c3d5-48b4-9980-9801d98ea3a1) | ![image](https://github.com/brave/brave-browser/assets/17010094/9722353b-de3e-41c7-9ed9-b7939616bc75) | ![image](https://github.com/brave/brave-browser/assets/17010094/66d9a028-e62f-4dfd-b593-5b736a1fc83f)
-- | -- | --
![image](https://github.com/brave/brave-browser/assets/17010094/4c6d4636-8da4-4b7d-9366-7a0bc411007e) | ![image](https://github.com/brave/brave-browser/assets/17010094/8bfb2921-116a-4faf-bd23-6a79639b3389) | ![image](https://github.com/brave/brave-browser/assets/17010094/2e6e8076-59f1-48da-8efc-63f72a2027ca)


closing the issue
