### ISSUE TITLE
typing chrome://sync autocompletes to chrome://sync-internals

### ISSUE THREAD

**Issue by cezaraugusto** [brave/brave-browser#2603]
Test Plan:

1. Type chrome://sync
2. Autocompletes to chrome://sync-internals

chrome://sync is much more mainstream than chrome://sync-internals and should not autocomplete

cc @darkdh

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.61.37 Chromium: 73.0.3683.39 (Official Build) beta (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

Used test plan from the description

![2603](https://user-images.githubusercontent.com/34715963/53379953-efdc8000-396b-11e9-9e88-5565c4f61d8d.gif)
