### ISSUE TITLE
Ads on YouTube Search

### ISSUE THREAD

**Issue by Nihal-Raj** [brave/brave-browser#26037]
## Description 
Noticing ads while searching for videos in YouTube

## Steps to Reproduce

   1. Visit www.youtube.com
   2. Search for Brave
   3. See an ad for Brave

## Actual result:
![image](https://user-images.githubusercontent.com/83210067/195885894-9ab94ee7-a830-4360-8bf2-7134f85415ac.png)

## Expected result:
No Ad should be shown

## Brave version (brave://version info)
<html>
<body>

Brave | 1.44.112 Chromium: 106.0.5249.119 (Official Build) (64-bit)
-- | --
Revision | 9f2101830b56fd2ea1408287f6c74e253ebcb7c6-refs/branch-heads/5249@{#797}
OS | Windows 10 Version 21H2 (Build 19044.2130)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release?  Yes
- Can you reproduce this issue with the beta channel? N.A.
- Can you reproduce this issue with the nightly channel? N.A.

**Comment by rebron** [comment]
cc: @ryanbr

**Comment by antonok-edm** [comment]
Should be fixed by procedural filters, which are tracked in https://github.com/brave/brave-browser/issues/16935
