### ISSUE TITLE
Google logo appears on Android NTP

### ISSUE THREAD

**Issue by intrnl** [brave/brave-browser#26035]
## Description 
Google logo is now shown on Brave Android NTP

## Steps to reproduce 

   1. Create a new tab

## Actual result 
![Screenshot_2022-10-14-22-21-57-38_82cebf612ef3f9a8762672c971adaed4](https://user-images.githubusercontent.com/20620901/195883349-7ac94b06-00ba-45ea-ba26-9bd9cebedcbf.jpg)

## Expected result
There should not be a Google logo.

## Issue reproduces how often 
Easily reproduced.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No. 
- Can you reproduce this issue with the current Play Store Beta version? No.
- Can you reproduce this issue with the current Play Store Nightly version? Yes, 1.46.59.

## Device details
   - Install type (ARM, x86): ARMv64
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 12
   
## Brave version
Nightly 1.46.59

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  No.
- Does the issue resolve itself when disabling Brave Rewards? No.
- Is the issue reproducible on the latest version of Chrome? This is specific to Brave, so no.

**Comment by GeetaSarvadnya** [comment]
Reproduced on `Android Tab A7 version 12` running `Bravemonoarm64.apk_1.45.106`

I am getting Google text on all the bg images in NTP. Default SE is `Google` for me If I change it to `brave` then Google text is removed from bg images from NTP

![Uploading Screenshot_20221019-204747_Brave.jpg…]()

cc: @brave/qa-team @anthonypkeane @SergeyZhukovsky

**Comment by Uni-verse** [comment]
Likely related to CR107. 

Doesn't reproduce on Nightly version 1.46.56 CR106. Upgrading to 1.46.67 CR107 will show the google logo on NTP

<img width="400" alt="0" src="https://user-images.githubusercontent.com/17885425/196738288-dceed92c-e92b-4ef6-a28b-156b1c278541.png">

**Comment by kjozwiak** [comment]
Going to move this into the `1.45.x` milestone and label it as `release/blocking` as we should fix this ASAP. We shouldn't be displaying `Google` under `NTP` even if a user selects `Google` as their default SE.

**Comment by GeetaSarvadnya** [comment]
Only for `Google` SE, `Google` text is shown in NTP
. If we switch to other search engine the Google text will not be shown in NTP

**Comment by Brave-Matt** [comment]
+1 from Community:
https://community.brave.com/t/google-written-by-default-on-ntp-images/439590/5
Looks like this user is on Android 11 using 1.46.49

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Samsung Galaxy Tab A7` version 12 running `Bravemonoarm64.apk_1.45.108`

- Confirmed that `Google` logo isn't shown in the NTP when the default search engine is `Google`
- Confirmed that `Google` logo isn't shown in the NTP when the default search engine is changed to `Brave`
- Confirmed that `Google` logo isn't shown in the NTP when the default search engine is changed to `Duckduckgo`
- Confirmed that `Google` logo isn't shown in the NTP when the default search engine is changed to `Bing`
- Confirmed that `Google` logo isn't shown in the NTP when the default search engine is changed to `Qwant`
- Confirmed that `Google` logo isn't shown in the NTP when the default search engine is changed to `Startpage`

Example | Example
--  | --
![Screenshot_20221020-170106_Brave](https://user-images.githubusercontent.com/38657976/196937298-ce778573-9dc9-4cff-aa22-dd608924243c.jpg) | ![Screenshot_20221020-170122_Brave](https://user-images.githubusercontent.com/38657976/196937323-54c8530a-7e80-431f-b1fd-61499e7f81b2.jpg)

----

Verification **PASSED** on `Samsung Galaxy Tab A7` version 12 running `Bravemonoarm64.apk_1.45.108`
