### ISSUE TITLE
[Android] Update Start using Brave Rewards modal design

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#26041]
## Description

**Existing:**

![image](https://user-images.githubusercontent.com/11497541/195894594-94a002dc-3d6b-4363-8f38-e6fb55120b14.png)

**Design:**

https://www.figma.com/file/ag8i1OV5vpvn4SiOhW2c0f/Github-fixes?node-id=1750%3A49149

![image](https://user-images.githubusercontent.com/11497541/195894431-1fce5540-8d2b-4439-8097-4995dc9c9e63.png)

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Vivo X70 Pro version 12` running `Bravemonoarn64.apk_1.46.114`

- Confirmed updated `Start using rewards modal` is shown
- Confirmed Rewards modal text is updated as per the design mentioned in https://github.com/brave/brave-browser/issues/26041#issue-1409582752

**`1.45.12`** | **`1.46.114`**
--------------|---------------
![Screenshot_20221117_123500](https://user-images.githubusercontent.com/38657976/202381776-61231e0d-ade2-417b-95a1-225e47d76062.jpg) | ![Screenshot_20221117_124055](https://user-images.githubusercontent.com/38657976/202381801-120d8e74-63be-4c16-8990-0c4a9d092e07.jpg)
