### ISSUE TITLE
Version number in "About Brave" should be orange to indicate that it is a link

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#26040]
## Description 

The version number on the `About Brave` page in the browser doubles as link out to the brave.com/latet page so that users can easily access the latest release notes from the update page. I believe this used to be orange colored like the rest of the links on the page (or perhaps it was orange on mouseover) but it no longer is. 

The version number needs to be colored like the rest of the links on the page so users can easily tell that this it is in fact a link. I believe we could also include a separate link on this page that links out to the release notes page but it seems silly to add more text when we can leverage what is already there.

![image](https://user-images.githubusercontent.com/3299098/195892170-fe9336d8-a9e2-4144-b7f9-bf5dfb2abecf.png)

cc @rebron

**Comment by nikolaps17** [comment]
Hello, Can you assign this issue to me?

**Comment by Stormkiller-01** [comment]
Hello developers, may I be assigned this issue as well if more help is allowed and/or needed? I am looking for experience in Open Source software and would like a chance to help out.

**Comment by NaaeemMalik** [comment]
I would also like it to be assigned it to me

**Comment by kavyadeepdev** [comment]
Hey, can this issue be assigned to me if it is still open?

**Comment by Ashutosh2407** [comment]
Hi, can I take this issue? Thanks

**Comment by ben-marrett** [comment]
Any tips on finding this in the codebase?
I've used the search bar and had a good look around browser, ui, toolbar and more to no avail.
How would you go about finding this?

**Comment by protocolog** [comment]
I am student of BITS Pilani, India and would love to contribute brave. Please assign me this issue.
@Brave-Matt

**Comment by XavierJDN** [comment]
> <img alt="image" width="435" src="https://user-images.githubusercontent.com/73435031/208945947-4bbeadd3-e914-4fe2-9471-795f7f8c15f2.png"> This is the code that is to be worked with, but now I am having trouble understanding it. Can someone help? Here is the file link is someone what to have a look point_down https://github.com/brave/brave-core/blob/8f562a725fbb272841b6de7c5b6ba2a3912573ad/browser/resources/settings/brave_overrides/about_page.ts#L23
Hi @TechBoyy6,
This file defines the template attributes. It also provide a exception error if the version of the browser is not found.

**Comment by XavierJDN** [comment]
I resolve the problem by adding the style attribute to the html:
...
      const parent = version.parentNode
      const wrapper = document.createElement('a')
      **version.setAttribute('style', 'color: var(--cr-link-color)')**
      wrapper.setAttribute('id', 'release-notes')
      wrapper.setAttribute('target', '_blank')
      wrapper.setAttribute('rel', 'noopener noreferrer')
      wrapper.setAttribute('href', 'https://brave.com/latest/')
...

**Comment by TechBoyy6** [comment]
@XavierJDN how do u test it?
what I mean is, I also tried stuff but since the codebase is so big setting it up locally to see the changes is not possible. So how do I test it? How did you test your changes?

**Comment by NaaeemMalik** [comment]
@TechBoyy6  my videos can help you out go.sixer.co/ytch .
you might also connect to me on skype go.sixer.co/skype

**Comment by XavierJDN** [comment]
> @XavierJDN how do u test it? what I mean is, I also tried stuff but since the codebase is so big setting it up locally to see the changes is not possible. So how do I test it? How did you test your changes?

Hi @TechBoyy6, the only way to see the changes is to build the code and check on the about page. The first time you build the project, it can take a long time. After that if you like to rebuild the project, it won't take long

**Comment by Oshanik22** [comment]
Is this issue still open? If yes, then I would like to work on this.

**Comment by CharlesQuinto** [comment]
I will be working on this as my first issue. First experience in contribution

**Comment by SujalHansda** [comment]
I would like to work on it. If any one's not working

**Comment by fallaciousreasoning** [comment]
@XavierJDN has a PR up for this already sorry.

**Comment by harshita-ramchandani** [comment]
Hi, I am new to the opensource community and want to learn can you pls assign this issue to me.
