### ISSUE TITLE
Unable to access Brave Rewards settings

### ISSUE THREAD

**Issue by lukemulks** [brave/brave-browser#2605]
## Description 

- Unable to access Brave Rewards settings in Brave. 
- Happens regardless of whether I'm on the dev, beta or alpha release channel. 
- Have uninstalled and reinstalled all versions, and am still unable to access to opt-in, claim grants, etc. 

## Steps to Reproduce

   1.  Enter: brave://rewards
   2. See white screen
   3. 

## Actual result:

![brave-rewards-12172018-white-screen](https://user-images.githubusercontent.com/8979240/50115303-d09ed500-01fb-11e9-816a-2cefb7278e9d.JPG)
![brave-rewards-12172018-sources-error](https://user-images.githubusercontent.com/8979240/50115309-d3012f00-01fb-11e9-9a81-1f6cb902b3f2.JPG)
![brave-rewards-12172018-console](https://user-images.githubusercontent.com/8979240/50115311-d5638900-01fb-11e9-98de-530b897fa651.JPG)

## Expected result:
Should be able to access Brave Rewards

## Reproduces how often: 

100% for me. 

## Brave version (brave://version info)

Version 0.57.18 Chromium: 71.0.3578.80 (Official Build) (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by NejcZdovc** [comment]
@lukemulks is this still a problem?
