### ISSUE TITLE
`WebRTC IP handling policy` entry is not shown in `brave://settings/security` in Nightly w/ Chromium 107

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#26050]
## Steps to Reproduce

   1. Install 1.46.58
   2. Launch Brave
   3. open brave://settings/security

## Actual result:

`WebRTC IP handling policy` entry with dropdown is not shown.  

Nightly|current release
----|-----
<img width="452" alt="image" src="https://user-images.githubusercontent.com/98358127/195937668-3957e53b-02d3-4dc7-8c77-a05da5dfd12b.png">|<img width="464" alt="image" src="https://user-images.githubusercontent.com/98358127/195937770-a0b7fe6f-961e-4981-9fd7-224db37b9697.png">

## Expected result:
`WebRTC IP handling policy` entry with dropdown should be available 

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Brave | 1.46.58 Chromium: 107.0.5304.36 (Official Build) nightly (64-bit)
-- | --
Revision | 2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}
OS | Windows 11 Version 21H2 (Build 22000.1098)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel?  Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@emerick @rebron 
cc: @brave/qa-team

**Comment by emerick** [comment]
@petemill Any idea what might be going on there? It does seem like the Polymer override is called, FWIW.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.46.64 Chromium: 107.0.5304.36 (Official Build) nightly (64-bit)
-- | --
Revision | 2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}
OS | Windows 11 Version 21H2 (Build 22000.1098)
```

Confirmed that the `WebRTC IP handling policy` entry is shown as expected.

<img width="456" alt="image" src="https://user-images.githubusercontent.com/98358127/196472019-ac061c4b-52d0-489c-8459-3fd77013b16e.png">

**Comment by kjozwiak** [comment]
The above requires `1.45.106` for `1.45.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.45.106 Chromium: 107.0.5304.36 (Official Build) (64-bit)
-- | --
Revision | 2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}
OS | Windows 11 Version 21H2 (Build 22000.1098)
```

- Verified with the original STR from the description. 
- Confirmed that the `WebRTC IP handling policy` setting is shown and working as expected.

![image](https://user-images.githubusercontent.com/98358127/196735399-e022a3fb-3add-4bf1-a58f-0788696db82a.png)
