### ISSUE TITLE
`Block All cookies` option is selected by default in `Block cookies` settings dropdown in brave://settings/shields

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#26067]
## Description 

`Block All cookies` option selected by default in `Block cookies` settings dropdown in brave://settings/shields

## Steps to Reproduce

   1.  Clean profile `1.46.63`
   2. Open brave://settings/shields
   3. Look for `Block cookies` setting
   4. `All`  option is selected by default which is NOT as expected
   5. Open any site and open shield settings
   6. Ensured `Block cross-site` option is selected as expected 

## Actual result:

![image](https://user-images.githubusercontent.com/38657976/196146344-f32f51bd-be05-4aa3-b9b2-b2061a132305.png)

## Expected result:

`Block cross-site` cookies should be selected by default
## Reproduces how often: 

Easy
## Brave version (brave://version info)

<html>
<body>

Brave | 1.46.63 Chromium: 107.0.5304.36 (Official Build) nightly (64-bit)
-- | --
Revision | 2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}
OS | Windows 10 Version 21H2 (Build 19044.2130)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @rebron @emerick

**Comment by emerick** [comment]
I think this is possibly due to https://github.com/brave/brave-core/pull/14893. At least, I don't see where `refreshState` is called nor any definition for `getHTTPSEverywhereEnabled`.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.46.68 Chromium: 107.0.5304.36 (Official Build) nightly (x86_64)
-- | --
Revision | 2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}
OS | macOS Version 13.0 (Build 22A379)

### Steps:
1. installed `1.46.68`
2. launched Brave
3. opened `brave://settings/shields`
4. examined the default pref value for `Block cookies`

#### Confirmed the default pref value for `Block cookies` is now correctly `Only cross-site`

<img width="1312" alt="Screenshot 2022-10-18 at 5 27 03 PM" src="https://user-images.githubusercontent.com/387249/196569654-d3191f64-fd90-4c49-b107-911404e92260.png">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.46.69 Chromium: 107.0.5304.36 (Official Build) beta (64-bit)
-- | --
Revision | 2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}
OS | Windows 11 Version 22H2 (Build 22621.674)
```

### Steps:
1. installed `1.46.69`
2. launched Brave
3. opened `brave://settings/shields`
4. examined the default pref value for `Block cookies`

#### Confirmed the default pref value for `Block cookies` is now correctly `Only cross-site`


<img width="466" alt="image" src="https://user-images.githubusercontent.com/98358127/198677701-5be400d1-71c1-4338-937a-a17654ce93eb.png">

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.46.106 Chromium: 107.0.5304.110 (Official Build) beta (64-bit) 
Revision	2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}
OS	Linux
```

### Steps:
1. installed `1.46.106`
2. launched Brave
3. opened `brave://settings/shields`
4. examined the default pref value for `Block cookies`

#### Confirmed the default pref value for `Block cookies` is now correctly `Only cross-site`

<img width="1124" alt="Screen Shot 2022-11-11 at 9 50 25 AM" src="https://user-images.githubusercontent.com/28145373/201365389-4e833e68-cc7e-4a15-a06c-2a14676d377f.png">
