### ISSUE TITLE
Multiple issues while adding NFT's to porfolio

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#26064]
## Description 

Ran into multiple issues while adding an NFT to portfolio

## Steps to Reproduce

**`Issue #1` - Unable to add NFT's on the first try**
   1. Clean profile & create wallet
   2. Add a custom token for NFT
   3. Click on Add doesn't add the NFT to portfolio
   4. Refresh the portfolio page, NFT gets listed

**`Issue #2` - Adding NFT doesn't close the Add custom token dialog**
   1. Clean profile & create wallet
   2. Add a custom token for NFT from a collection
   3. Click on Add doesn't add the NFT to portfolio
   4. Ensure the NFT is added 
   5. Try adding a second NFT from the same collection
   6. Clicking on Add doesn't automatically close the add token dialog
   7. Manually closing the dialog and refresh portfolio loads the NFT 

## Actual result:

https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1665992515919749

## Expected result:
Should add NFT on the first try and list it. Should not keep the add token modal open if NFT is already added to portfolio

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.45.95 Chromium: 106.0.5249.103 (Official Build) beta (64-bit) 
-- | --
Revision | `182570408a1f25ab2731ef5f283b918df9b9f956-refs/branch-heads/5249_91@{#6}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Most likely but not checked

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @muliswilliam

**Comment by kjozwiak** [comment]
The above requires `1.45.108` or higher for `1.45.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.45.108 Chromium: 107.0.5304.36 (Official Build) (64-bit) 
-- | --
Revision | `2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}`
OS | Linux

- Verified steps from issue description
- Verified able to add NFT successfully
- Verified able to view NFT immediately after adding NFT
- Verified able to add multiple NFT in one go and list all of them
- Verified modal is closed immediately after NFT is added successfully

https://user-images.githubusercontent.com/17010094/196943210-4e1f04e4-0c07-4a48-9871-f01495106394.mp4


------------------------
Verification passed on

Brave | 1.45.108 Chromium: 107.0.5304.36 (Official Build) (64-bit) 
-- | --
Revision | `2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}`
OS | Windows 11 Version 22H2 (Build 22621.674)

- Verified steps from issue description
- Verified able to add NFT successfully
- Verified able to view NFT immediately after adding NFT
- Verified able to add multiple NFT in one go and list all of them
- Verified modal is closed immediately after NFT is added successfully

https://user-images.githubusercontent.com/17010094/196941894-8e24a32b-d822-4bff-83c9-db91ff21041e.mp4


------------------------
Verification passed on

Brave | 1.45.108 Chromium: 107.0.5304.36 (Official Build)  (arm64)
-- | --
Revision | `2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from issue description
- Verified able to add NFT successfully
- Verified able to view NFT immediately after adding NFT
- Verified able to add multiple NFT in one go and list all of them
- Verified modal is closed immediately after NFT is added successfully

https://user-images.githubusercontent.com/17010094/196939884-7226b456-c2f4-4384-b1ee-44fa28e3c531.mov
