### ISSUE TITLE
Follow up of the PR #15242 - `Content Filters` string isn't translated in brave://settings/shields/filters page

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#26062]
## Description 

Follow up of the PR #https://github.com/brave/brave-core/pull/15242
`Content Filters` string isn't translated in brave://settings/shields/filters page
## Steps to Reproduce

   1. Set OS locale to Germany/France/Polish
   2. Clean profile 1.46.63 
   3. Follow the steps from the issue #24004
   4. `Content Filters` string isn't translated in brave://settings/shields/filters page

## Actual result:

`Content Filters` string isn't translated in brave://settings/shields/filters page

**Germany**
![image](https://user-images.githubusercontent.com/38657976/196096713-ed35d09a-5203-431a-9547-e1ee26ffce26.png)

## Expected result:
`Content Filters` string should be translated in other locales

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.46.63 Chromium: 107.0.5304.36 (Offizieller Build) nightly (64-Bit)
-- | --
Überarbeitung | 2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}
Betriebssystem | Windows 10 Version 21H2 (Build 19044.2130)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @rebron @nullhook

**Comment by rebron** [comment]
@GeetaSarvadnya Needs a re-check after translations land for 1.45.x

**Comment by GeetaSarvadnya** [comment]
Verified the issue against the build `1.45.113` on the OS `Windows 10 x64` and ensured `Content Filters` text in `brave://settings/shields/filters` page is translated in other locales like `Germany`, `France` and `Polish`. Hence closing the issue. Thanks @rebron !

Germany | France | Polish
-----------|--------|--------
![image](https://user-images.githubusercontent.com/38657976/198080657-ef725ca9-2327-48a3-bada-45ed50afc35d.png) | ![image](https://user-images.githubusercontent.com/38657976/198080833-5fe4b514-9500-4f6e-80ba-02713f51a3f8.png) | ![image](https://user-images.githubusercontent.com/38657976/198081004-570c4fd2-7149-438a-973f-f5539e7a24f0.png)
