### ISSUE TITLE
`Strict, may break sites` option is selected by default in `Block fingerprinting` settings dropdown in brave://settings/shields

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#26068]
## Description 

`Strict, may break sites` option selected by default in `Block fingerprinting` settings dropdown in brave://settings/shields

## Steps to Reproduce

   1. Clean profile 1.46.63
   2. Open brave://settings/shields
   3. Look for `Block fingerprinting` setting
   4. `Strict, may break sites` selected by default 
   

## Actual result:

`Strict, may break sites` selected by default in `Block fingerprinting` setting in brave://settings/shields
![image](https://user-images.githubusercontent.com/38657976/196145404-1a9ec118-fe15-4995-87c7-3aeda93cffaa.png)

## Expected result:
`Standard` should be selected by default

## Reproduces how often: 

Easy
## Brave version (brave://version info)

<html>
<body>

Brave | 1.46.63 Chromium: 107.0.5304.36 (Official Build) nightly (64-bit)
-- | --
Revision | 2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}
OS | Windows 10 Version 21H2 (Build 19044.2130)

</body>
</html>
## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @emerick @rebron @brave/qa-team

**Comment by emerick** [comment]
I think this is possibly due to https://github.com/brave/brave-core/pull/14893. At least, I don't see where `refreshState` is called nor any definition for `getHTTPSEverywhereEnabled`.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.46.68 Chromium: 107.0.5304.36 (Official Build) nightly (x86_64)
-- | --
Revision | 2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}
OS | macOS Version 13.0 (Build 22A379)

### Steps:
1. installed `1.46.68`
2. launched Brave
3. opened `brave://settings/shields`
4. examined the default setting for `Block fingerprinting`

#### Confirmed the default is now properly `Standard`

<img width="1312" alt="Screenshot 2022-10-18 at 5 15 51 PM" src="https://user-images.githubusercontent.com/387249/196568542-902c2f40-31c9-4a1e-8a9f-dd726a3f7777.png">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.46.69 Chromium: 107.0.5304.36 (Official Build) beta (64-bit)
-- | --
Revision | 2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}
OS | Windows 11 Version 22H2 (Build 22621.674)
```
### Steps:
1. installed `1.46.69`
2. launched Brave
3. opened `brave://settings/shields`
4. examined the default setting for `Block fingerprinting`

#### Confirmed the default is now properly `Standard`


<img width="467" alt="image" src="https://user-images.githubusercontent.com/98358127/198676704-14b7dc97-652e-4d9b-82b2-c6748397e88e.png">

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave	1.46.106 Chromium: 107.0.5304.110 (Official Build) beta (64-bit) 
Revision	2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}
OS	Linux
```

### Steps:
1. installed `1.46.106`
2. launched Brave
3. opened `brave://settings/shields`
4. examined the default setting for `Block fingerprinting`

#### Confirmed the default is now properly `Standard`

<img width="1124" alt="Screen Shot 2022-11-11 at 9 50 25 AM" src="https://user-images.githubusercontent.com/28145373/201364995-707c7e23-2793-4171-89e3-25c77c9a1575.png">
