### ISSUE TITLE
Fee payer signature might be dropped by solana-web3 `Transaction._compile()`

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#26061]
Currently if non-fee payer signatures is not passed by dApp, we will create a transaction with only fee payer signature inside and do nothing for those missing signatures. However, this could cause our fee payer signature later be dropped when solana-web3 `Transaction._compile()` is called because the length of our Transaction.signatures array is only 1 (the fee payer) instead of length of required signatures. (https://github.com/solana-labs/solana-web3.js/blob/8b3cab18fc7977be34f02ec4f1121da7b8b89162/src/transaction/legacy.ts#L526-L537) We should fill those signatures with empty signatures (all 0), so our Transaction.signatures array will have the size equal to the num of required signatures look like below.
<img width="1679" alt="Screen Shot 2022-10-15 at 9 56 22 PM" src="https://user-images.githubusercontent.com/4730197/196089942-097c12af-e4d2-487c-b1d4-9f87f6ea85a9.png">

**Comment by kjozwiak** [comment]
The above requires `1.45.104` for higher for `1.45.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.45.104 Chromium: 106.0.5249.126 (Official Build) beta (64-bit) 
-- | --
Revision | `fb2e06d2dee20fe0c804528502b5ad72c613abd9-refs/branch-heads/5249_118@{#3}`
OS | Linux

- Verified steps from [brave/brave-core#15480](https://github.com/brave/brave-core/pull/15480)
- Verified signatures are shown as expected

https://user-images.githubusercontent.com/17010094/196433520-f62fef4d-9ec8-4f1a-b097-4ae587ddf6c6.mp4


------------------------
Verification passed on

Brave | 1.45.104 Chromium: 106.0.5249.126 (Official Build) beta (64-bit) 
-- | --
Revision | `fb2e06d2dee20fe0c804528502b5ad72c613abd9-refs/branch-heads/5249_118@{#3}`
OS | Windows 11 Version 21H2 (Build 22000.978)

- Verified steps from [brave/brave-core#15480](https://github.com/brave/brave-core/pull/15480)
- Verified signatures are shown as expected

https://user-images.githubusercontent.com/17010094/196434102-48f618be-1e99-468f-932c-58e10e9a1928.mp4

------------------------
Verification passed on

Brave | 1.45.104 Chromium: 106.0.5249.126 (Official Build) beta (arm64)
-- | --
Revision | `fb2e06d2dee20fe0c804528502b5ad72c613abd9-refs/branch-heads/5249_118@{#3}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from [brave/brave-core#15480](https://github.com/brave/brave-core/pull/15480)
- Verified signatures are shown as expected

https://user-images.githubusercontent.com/17010094/196434593-58488ccd-f1de-4e05-b694-c54cd3ca4765.mov
