### ISSUE TITLE
cookie consent modal/notification should close when switching/losing or opening NTP

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#26078]
## Description 

As per the desktop implementation of the `Cookie Consent` feature, we should ensure that it dismisses/closes in the following cases:

```
* The user switches tabs
* The user closes the active tab
* The user opens a new tab
```

Once https://github.com/brave/brave-browser/issues/25811 was fixed, it made it so the user couldn't dismiss the notification/modal without making a decision but didn't take the above cases into consideration. As per @pes10k, we should get this into `1.45.x` so when we enable the ` BraveAdblockCookieListOptInStudy`, it will work as expected on `1.45.x`.

## Steps to reproduce 

   1. download/install Brave Nightly
   2. open any random website
   3. refresh the same website ~5 times (the `cookie consent` should appear after the 5th refresh)
   4. once it's visible, don't make a decision and start creating new tabs/switching tabs

You'll notice that the `cookie consent` notification/modal isn't being dismissed.

## Actual result 

**`Example`** | **`Example`**
----------------|----------------
![Screenshot_20221015-230339_Brave - Nightly](https://user-images.githubusercontent.com/2602313/196237365-34f4e336-1616-4446-8f67-dc04baa298c0.jpg) | ![Screenshot_20221015-230352_Brave - Nightly](https://user-images.githubusercontent.com/2602313/196237374-70198515-301f-4314-a3c7-dc6dc811fb29.jpg)

## Expected result

The `cookie consent` notification/modal should be dismissed in the following cases:

```
* The user switches tabs
* The user closes the active tab
* The user opens a new tab
```

## Issue reproduces how often 

100% reproducible when using the STR/Cases outlined above.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `N/A`
- Can you reproduce this issue with the current Play Store Beta version? `N/A` (until https://github.com/brave/brave-core/pull/15356 is uplifted into `1.45.x`)
- Can you reproduce this issue with the current Play Store Nightly version? `N/A`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Samsung S10+` (Phone)
   - Android version: `Android 13`
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

### Additional information

CCing @pes10k @deeppandya @timchilds

**Comment by kjozwiak** [comment]
The above requires `1.45.109` or higher for `1.45.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `vivo x70 Pro` version 12 running `Bravemonoarm64.1pk_1.45.108`

- Verified the STR from the description https://github.com/brave/brave-browser/issues/26078#issue-1411905767,  ensured the following:
* ensured that the cookie consent panel/notification is dismissed when a user switches tabs
* ensured that the cookie consent panel/notification is dismissed when a user user closes the active tab
* ensured that the cookie consent panel/notification is dismissed when a user user opens a new tab

Example | Example
-- | --
![Screenshot_20221021_170550](https://user-images.githubusercontent.com/38657976/197187712-49104408-1a3c-42b9-860a-2a2deab5ab43.jpg) | ![Screenshot_20221021_170624](https://user-images.githubusercontent.com/38657976/197187737-3268cb6d-f7f4-4406-9c35-1e1726808d9c.jpg)
