### ISSUE TITLE
Browser crash on https://d3ward.github.io/toolz/adblock with enabled `Ru Adlist`

### ISSUE THREAD

**Issue by atuchin-m** [brave/brave-browser#26075]
## Description 
Browser process crashes when open certain sites with enabled adblock list `Ru Adlist`.
Disabling `Ru Adlist` fixes the problem. Could be the same issue with some other additional adblock lists.

## Steps to Reproduce
   1.  Enable `Ru Adlist` on brave://adblock
   2. Open new tab and navigate to https://d3ward.github.io/toolz/adblock

## Actual result:
Main process crashed.

## Reproduces how often: 
Always

## Desktop Brave version:
1.46.56 Chromium: 106.0.5249.119 (Official Build) nightly (arm64) 

## Android Device details:
Doesn't check Android, but it uses the same code.

## Version/Channel Information:
- Can you reproduce this issue with the current release? 
Yes
- Can you reproduce this issue with the beta channel? 
Yes
- Can you reproduce this issue with the nightly channel? 
Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
Yes
- Does the issue resolve itself when disabling Brave Rewards? 
No
- Is the issue reproducible on the latest version of Chrome? 
No

**Comment by kjozwiak** [comment]
@atuchin-m should try getting the above uplifted into `1.45.x` if we fix it in time 👍 CCing @rebron

**Comment by kjozwiak** [comment]
The above requires `1.46.80` or higher for `1.46.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.46.80 Chromium: 107.0.5304.68 (Official Build) beta (x86_64)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | macOS Version 11.7.1 (Build 20G918)

First, confirmed the clean exit/crash using `1.46.56`.

### Steps:
1. installed `1.46.80`
2. launched Brave
3. opened `brave://adblock`
4. checked `RU Adlist`
5. loaded `https://d3ward.github.io/toolz/adblock`

#### Confirmed I was able to load `https://d3ward.github.io/toolz/adblock` with `RU Adlist` enabled, without crashing

`brave://adblock` | `https://d3ward.github.io/toolz/adblock`
------------------|----------------------------------------
<img width="1312" alt="Screen Shot 2022-10-26 at 10 54 12 AM" src="https://user-images.githubusercontent.com/387249/198100971-6940eec8-b7fc-4cf1-b93b-e17cca8ae4e4.png"> | <img width="1312" alt="Screen Shot 2022-10-26 at 10 54 20 AM" src="https://user-images.githubusercontent.com/387249/198100981-ac01e1a7-e377-4f57-87ef-37a99da0cb7f.png">

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.46.87 x64 Beta build
- Verified steps from issue description
- Verified enabling `Ru Adlist` and loading `https://d3ward.github.io/toolz/adblock` doesn't cause any crash (browser/webview)

`chrome://adblock` | `https://d3ward.github.io/toolz/adblock`
-- | --
![image](https://user-images.githubusercontent.com/17010094/199485613-d787b6c9-2043-4163-b14f-0d1fd5c3c08c.png) | ![image](https://user-images.githubusercontent.com/17010094/199485629-c18b573b-58af-4b42-a9dc-4786e600dbea.png)
