### ISSUE TITLE
Printing on Google Slides doesn't work with Shields up

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#26079]
## Description 

We had an old issue for Google services where Brave would force the user to save the [content] as a `.pdf` rather than initiating the print screen dialog:
https://github.com/brave/brave-browser/issues/3694

This issue seems to have reappeared specifically for Google Slides. Attempting to print anything on Slides with Shields up forces the user to save the content as a `.pdf`. Attempting to print w/ Shields down displays the print screen dialog as intended:

https://user-images.githubusercontent.com/3299098/196257835-00d72f00-6b7a-4675-a379-e30cb52230ae.mov

## Steps to Reproduce

   1. Visit slides.google.com and open a presentation
   2. Attempt to print a slide w/Shields up
   3. Observe browser forces saving content as `.pdf`

## Reproduces how often: 

Always

## Brave version (brave://version info)

v1.44.112

## Version/Channel Information:

- Can you reproduce this issue with the current release? Y
- Can you reproduce this issue with the beta channel? Y
- Can you reproduce this issue with the nightly channel? Y

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

User report:
https://community.brave.com/t/bug-missing-print-dialogue-in-google-slides-only-save-as-pdf/429045/14

**Comment by rebron** [comment]
cc: @ryanbr Looks like the print dialog show up ok with Shields down. Only an issue on Google Slides. Works fine (print dialog shows up) with Sheets and Docs with Shields down.

**Comment by twMat** [comment]
@rebron - regarding the label "workaround/shields-down"; does this label mean it will not be properly fixed, i.e as there is a workaround?
Thx

**Comment by rebron** [comment]
@twMat Only means that there is a workaround. We want a proper fix for it.

**Comment by ryanbr** [comment]
Looks like a fingerprinting issue, Allowing fingerprinting on `slides.google.com` cc: @pilgrim-brave

**Comment by soliviantar** [comment]
Sorry, but I am having this problem now and shields down is not helping. I can confirm printing works normally on Sheets, but not on Slides.

**Comment by ryanbr** [comment]
Print preview now working

**Comment by twMat** [comment]
@ryanbr 

>Print preview now working

Well, still not for me. Turning shields off makes it work.
Latest official brave
Win 11
