### ISSUE TITLE
Click on the `Brave Rewards` link opens up the rewards page in the same tab instead of opening in an NTP

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#26070]
## Description 

Click on the `Brave Rewards` link opens up the rewards page in the same tab instead of opening in an NTP

## Steps to Reproduce

   1. Clean profile 1.46.63
   2. Open brave://settings/shields
   3. Click on `Brave Rewards` link
   4. Click on the `Brave Rewards` link opens up the rewards page in the same tab instead of opening in an NTP

## Actual result:

Click on the `Brave Rewards` link opens up the rewards page in the same tab instead of opening in an NTP
![image](https://user-images.githubusercontent.com/38657976/196174740-f89e3a7d-20ce-4707-ab86-181e46a32bd0.png)

## Expected result:

Brave rewards page should be opened in an new NTP
## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.46.63 Chromium: 107.0.5304.36 (Official Build) nightly (64-bit)
-- | --
Revision | 2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}
OS | Windows 10 Version 21H2 (Build 19044.2130)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @rebron @emerick 

@emerick This happens with CR 106 nightly build also, but not with Rc 1.44 (cr 106), Please close the issue if it's the expected change.

**Comment by emerick** [comment]
I think that this may be related to https://github.com/brave/brave-core/pull/14928 and not a cr107-related regression? cc: @mkarolin

**Comment by kjozwiak** [comment]
The above requires `1.45.106` or higher for `1.45.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.45.106 Chromium: 107.0.5304.36 (Official Build) (x86_64)
-- | --
Revision | 2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}
OS | macOS Version 12.6 (Build 21G115)
```
