### ISSUE TITLE
`Default avatar` icon is inherited from Chrome 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#26073]
## Description 

Default avatar icon is inherited from Chrome 
## Steps to Reproduce

   1. Clean profile 1.46.63
   2. Open brave://settings/manageProfile
   3. `Default avatar` icon is inherited from Chrome 

## Actual result:

Default avatar icon is inherited from Chrome 

**1.46.63**
![image (2)](https://user-images.githubusercontent.com/38657976/196213751-84cbf677-6ac3-4245-afc4-386eddf0f11e.png)

**1.44.112**
![image](https://user-images.githubusercontent.com/38657976/196214137-4cd2ff6e-7d52-41a7-892f-e424ca349dbc.png)

## Expected result:

Discussed with @aguscruiz and @rebron - Use brave branded default avatara icon

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.46.63 Chromium: 107.0.5304.36 (Official Build) nightly (64-bit)
-- | --
Revision | 2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}
OS | Windows 10 Version 21H2 (Build 19044.2130)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @rebron @aguscruiz

**Comment by kjozwiak** [comment]
The above requires `1.45.111` or higher for `1.45.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.45.111 Chromium: 107.0.5304.62 (Official Build) (x86_64)
-- | --
Revision | 1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942}
OS | macOS Version 12.6 (Build 21G115)
```
