### ISSUE TITLE
 Closing the PT/TOR tab windows causes the brave crash

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#26074]
## Description 

Closing the PT/TOR tab windows causes the brave crash

## Steps to Reproduce

   1. Clean profile `1.46.63`
   2. Open a PT or TOR tab window via Hamburger menu
   3. Close the PT or TOR tab window
   4. Brave crashes

## Actual result:

 Closing the PT/TOR tab windows causes the brave crash

## Expected result:

Should not be any crash
## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.46.63 Chromium: 107.0.5304.36 (Official Build) nightly (64-bit)
-- | --
Revision | 2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}
OS | Windows 10 Version 21H2 (Build 19044.2130)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes
## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @rebron @emerick

**Comment by emerick** [comment]
Not able to repro this one in master.

**Comment by rebron** [comment]
@GeetaSarvadnya Can you add your crash id for this one?

**Comment by GeetaSarvadnya** [comment]
Sorry. It's working as expected. Closing the issue as expected.
