### ISSUE TITLE
Brave Ads notifications disappear without user input

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#2608]
## Description 
Brave Ads notifications disappear without user input

## Steps to Reproduce

   1.  Visit a website, e.g. www.foodnetwork.com
   2. Remain idle for 15 seconds
   3. Move the mouse to become unidle
   4. Ad is shown

## Actual result:
Ad disappears without user input

## Expected result:
Ad should not disappear without user input

## Reproduces how often: 
Intermittent

## Brave version (brave://version info)
macOS Version 0.59.8 (64-bit)

**Comment by bridiver** [comment]
We have no control over this on macos

**Comment by tmancey** [comment]
<img width="780" alt="screenshot 2018-12-18 at 01 53 33" src="https://user-images.githubusercontent.com/1188719/50127157-d7633180-0267-11e9-8810-367f51671bff.png">

<img width="736" alt="screenshot 2018-12-18 at 01 53 23" src="https://user-images.githubusercontent.com/1188719/50127158-d7633180-0267-11e9-9339-75f41fd33b2f.png">

Notifications should be forced to use the alert style, as then they will not automatically be removed

**Comment by bridiver** [comment]
@tmancey I'm not sure if we can force that or not because we currently do use the alert style (has buttons). I'll take a look

**Comment by tmancey** [comment]
@mrose17 Can you please check in macOS Preferences the above settings, ideally please attach a screenshot

**Comment by tmancey** [comment]
Agreed reason Ad vanished was that macOS Preferences/Notifications for Brave Browser were set to Banner and not Alert as Banners do vanish after a period of time

**Comment by mrose17** [comment]
and how do we set it programmatically when the browser starts?

**Comment by tmancey** [comment]
I need to add `  # Explicitly force user notification alerts
  plist['NSUserNotificationAlertStyle'] = "alert"
` to tweak_info_plist.py however this will force alerts app wide, is this ok?

**Comment by tmancey** [comment]
Resolved by https://github.com/brave/brave-core/pull/1137

**Comment by bbondy** [comment]
Milestone should be adjusted please to match where this landed.

**Comment by bbondy** [comment]
@tmancey milestone still needs to be adjusted pls. Thanks.

**Comment by tmancey** [comment]
This issue has been reverted as the functionality is no longer required
