### ISSUE TITLE
Add a toggle to hide the price graph in Brave Wallet Portfolio Overview page 

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#26080]
## Description 

Add a toggle button to show/hide the graph in the portfolio overview page

Figma prototype: https://www.figma.com/proto/CPUOGNxaQXHheUMoucwQFN/Portfolio?page-id=966%3A29147&node-id=1076%3A52452&viewport=5490%2C301%2C0.45&scaling=min-zoom&starting-point-node-id=1076%3A51546&show-proto-sidebar=1

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.47.126 Chromium: 108.0.5359.99 (Official Build) beta (64-bit)
-- | --
Revision | `410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}`
OS | Linux

- Verified steps from [brave/brave-core#15494](https://github.com/brave/brave-core/pull/15494)
- Verified toggle next to portfolio balance shows/hide portfolio balance and tokens balance
- Verified toggle on token details screen shows/hides balance 

https://user-images.githubusercontent.com/17010094/207395605-cc1f688f-c92f-4f5e-9a61-157649e63029.mp4

---------------------

Verification passed on 

Brave | 1.47.126 Chromium: 108.0.5359.99 (Official Build) beta (64-bit)
-- | --
Revision | `410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#15494](https://github.com/brave/brave-core/pull/15494)
- Verified toggle next to portfolio balance shows/hide portfolio balance and tokens balance
- Verified toggle on token details screen shows/hides balance 

https://user-images.githubusercontent.com/17010094/207396308-2a826690-7816-441f-8a3f-943491afd561.mp4

---------------------

Verification passed on 

Brave | 1.47.126 Chromium: 108.0.5359.99 (Official Build) beta (arm64)
-- | --
Revision | `410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#15494](https://github.com/brave/brave-core/pull/15494)
- Verified toggle next to portfolio balance shows/hide portfolio balance and tokens balance
- Verified toggle on token details screen shows/hides balance 

https://user-images.githubusercontent.com/17010094/207397063-c1b2e058-7089-45d0-805d-ecf6e8945042.mov
