### ISSUE TITLE
CR 107 - Remove chrome icon in autofill suggest

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#26089]
## Description 

Autofill for passwords shows Chrome icon. This is coming from Chromium 107 update. There should be no icon here.

<img width="431" alt="Screenshot 2022-10-17 at 6 18 08 PM" src="https://user-images.githubusercontent.com/5951041/196312861-be12340d-23d1-43c5-a83d-b9e9c6dda6d3.png">

## Steps to Reproduce

   1. Go to a site that has a password that will autofill and invoke autofill dropdown.
   2. Notice Chrome icon.

## Actual result:

See description.

## Expected result:
No icon.

## Version/Channel Information:

Brave | 1.46.64 Chromium: 107.0.5304.36 (Official Build) nightly (arm64)
-- | --
Revision | 2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}
OS | macOS Version 13.0 (Build 22A5342f)
JavaScript | V8 10.7.193.13
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by GeetaSarvadnya** [comment]
Reproduce the issue in `Windows 10 x64 - 1.46.64` - @rebron Good catch
![image](https://user-images.githubusercontent.com/38657976/196342384-206d317c-6b69-4cd0-9a7a-804f68776f9e.png)

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.45.108 Chromium: 107.0.5304.36 (Official Build) (x86_64)
-- | --
Revision | 2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}
OS | macOS Version 11.7 (Build 20G817)

### Steps:
1. installed `1.45.108`
2. launched Brave
3. loaded `facebook.com`
4. entered username and password information
5. clicked on `Save`
6. relaunched Brave
7. loaded `facebook.com`

#### Confirmed the "gears" icon has replaced the `Chrome`/`Chromium` icon

<img width="452" alt="Screen Shot 2022-10-20 at 9 24 21 AM" src="https://user-images.githubusercontent.com/387249/197005415-bf5d9460-9e67-41cf-9be9-0b10ff549604.png">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.45.108 Chromium: 107.0.5304.36 (Official Build) (64-bit)
-- | --
Revision | 2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}
OS | Windows 11 Version 21H2 (Build 22000.1098)
```
Verified using original STR from description

### Confirmed chrome longer displayed

![image](https://user-images.githubusercontent.com/98358127/197019844-ba04db28-405b-4fd3-9030-a52fd50f5637.png)
