### ISSUE TITLE
News: Unfollow button should remove follow and not block content

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#26090]
## Test Plan
- Open NTP
- Scroll down and opt in to brave news
- Remember the first content's publisher name
- Click Customize
- Find the Publisher Name
- Click Follow
- -> Publisher should be in the left column
- Click Unfollow
- -> Publisher should not be in the left column
- Close customize
- Refresh NTP
- Scroll down to Brave News
- First content should be the same, i.e. content from the publisher should still be visible

**Comment by MadhaviSeelam** [comment]
@petemill  - `Follow/Unfollow` buttons are behind a flag? and new design too? 
 I am not seeing those buttons in `1.46.70 Chromium: 107.0.5304.36 beta`


currently seeing this
![image](https://user-images.githubusercontent.com/98358127/197072609-d32cdb34-77cb-4254-a1ab-dacd07006343.png)

**Comment by stephendonner** [comment]
> @petemill - `Follow/Unfollow` buttons are behind a flag? and is there a new design? I am not seeing those buttons in `1.46.70 Chromium: 107.0.5304.36 beta`
> 
> currently seeing this ![image](https://user-images.githubusercontent.com/98358127/197072609-d32cdb34-77cb-4254-a1ab-dacd07006343.png)

@MadhaviSeelam yup, you'll want to set `brave://flags/#brave-news-v2` to `Enabled`.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.46.78 Chromium: 107.0.5304.62 (Official Build) beta (x86_64)
-- | --
Revision | 1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942}
OS | macOS Version 11.7.1 (Build 20G918)

### Steps:

1. installed `1.46.78`
2. launched Brave
3. opened `brave://flags`
4. set `brave://flags/#brave-news-v2` to `Enabled`
5. clicked `Relaunch`
6. opened a new-tab page
7. scrolled down
8. clicked on `Show Brave News`
9. 1st publisher was `Daily Mail`
10. clicked `Customize`
11. typed `daily mail` into the `Discover` search textfield and hit `return`
12. clicked on the `Follow` button/link within the `Daily Mail` icon
13. confirmed `Daily Mail` appeared in the left column, under `Following`
14. clicked `Unfollow`
15. confirmed `Daily Mail` was removed from the left column
16. closed the `Customize` dialog
17. clicked on the browser's `Reload this page` button
18. scrolled down to Brave News


#### Confirmed I saw the `Daily Mail` article in the feed

step 4 | step 8 | step 9 | step 10 | step 11 | step 13 | step 15 | step 18
-------|-------|--------|---------|-------|---------|--------|--------
<img width="1072" alt="Screen Shot 2022-10-25 at 1 32 52 PM" src="https://user-images.githubusercontent.com/387249/197876186-b01abe62-0ded-44cc-97ae-a9315c013aee.png"> | <img width="1312" alt="Screen Shot 2022-10-25 at 1 34 25 PM" src="https://user-images.githubusercontent.com/387249/197876502-47cebad9-f69a-492b-afc5-c5a1780d796c.png"> | <img width="1312" alt="Screen Shot 2022-10-25 at 1 34 30 PM" src="https://user-images.githubusercontent.com/387249/197876584-1244cbd7-c942-434c-8d87-7b99342739aa.png"> | <img width="1312" alt="Screen Shot 2022-10-25 at 1 36 44 PM" src="https://user-images.githubusercontent.com/387249/197876867-64e1deac-47a6-4ba0-80ad-4639dba1d579.png"> | <img width="1312" alt="Screen Shot 2022-10-25 at 1 36 39 PM" src="https://user-images.githubusercontent.com/387249/197876912-256a5a08-cc5e-4c3f-9327-64bb15b279e8.png"> | <img width="1312" alt="Screen Shot 2022-10-25 at 1 37 37 PM" src="https://user-images.githubusercontent.com/387249/197877248-2b1e433b-6001-4ab0-8827-95f355cd94db.png"> | <img width="1312" alt="Screen Shot 2022-10-25 at 1 37 43 PM" src="https://user-images.githubusercontent.com/387249/197877253-68c5e154-0b80-45eb-bb9b-81936e9b42e5.png"> | <img width="1312" alt="Screen Shot 2022-10-25 at 1 38 26 PM" src="https://user-images.githubusercontent.com/387249/197877368-cefaa38a-c7cc-4362-9fe7-1938d7d49365.png">
