### ISSUE TITLE
CR 107 - Links in brave://settings have been underlined and which is inherited from chrome

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#26091]
## Description 

Links in brave://settings should not be underlined

## Steps to Reproduce

   1. Clean profile 1.46.64
   2. Open brave://settings
   3. Links in brave://settings have been underlined and which is inherited from Chromium CR 107

## Actual result:

Links in brave://settings have been underlined

`Brave Rewards` and `Learn more` links are underlined
![image](https://user-images.githubusercontent.com/38657976/196334554-2f50794a-e2e1-45e0-8b3b-506ffe50c5b5.png)

## Expected result:

Discussed with @rebron and @aguscruiz - Links in brave://settings should not be underlined

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.46.64 Chromium: 107.0.5304.36 (Official Build) nightly (64-bit)
-- | --
Revision | 2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}
OS | Windows 10 Version 21H2 (Build 19044.2130)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @rebron @aguscruiz @emerick

**Comment by kjozwiak** [comment]
The above requires `1.45.112` or higher for `1.45.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```

Brave | 1.45.113 Chromium: 107.0.5304.62 (Official Build) (64-bit)
-- | --
Revision | 1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942}
OS | Windows 10 Version 21H2 (Build 19044.2130)

```
