### ISSUE TITLE
Disable sync by default in 0.58.x

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#2609]
In order to use sync, use `--enable-brave-sync` switch

**Comment by darkdh** [comment]
closed by https://github.com/brave/brave-core/pull/1116

**Comment by LaurenWags** [comment]
@darkdh with the below version Sync is still available on Settings page, is this expected? fwiw, navigating to brave://sync results in an error.

Brave | 0.58.15 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Mac OS X

![screen shot 2018-12-19 at 10 46 59 am](https://user-images.githubusercontent.com/28145373/50230925-9eb47c80-037b-11e9-9256-923cb566cecb.png)

![screen shot 2018-12-19 at 10 46 43 am](https://user-images.githubusercontent.com/28145373/50230928-a116d680-037b-11e9-9c10-fe1452b7ffa7.png)

cc @kjozwiak @rebron

**Comment by btlechowski** [comment]
@LaurenWags Also reproduced on Windows 7.

**Comment by kjozwiak** [comment]
Seeing the same thing with `macOS 10.14.2 x64` and `Windows 10 x64` using the following build:

Brave | 0.58.15 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.58.15 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Mac OS X

* Verified Sync is not available from hamburger menu
* Verified navigating to brave://sync results in an error
* Sync is still available in Settings, logged follow up issue https://github.com/brave/brave-browser/issues/2642

**Comment by darkdh** [comment]
fixed in https://github.com/brave/brave-core/pull/1146
