### ISSUE TITLE
Overlapping text in NTP customization for sponsored images on some locales (Polish)

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#26099]
Follow up to https://github.com/brave/brave-browser/issues/25197

## Steps to Reproduce

1. Run Brave in Polish (PL) locale
2. Open NTP 
3. Click `Dopasowanie`
4. Click `Obraz tła`
5. Scroll down

## Actual result:

overlapping text
![image](https://user-images.githubusercontent.com/34715963/196467195-e75eecda-5a61-4a27-9368-b6c1bce8f929.png)

## Expected result:
No overlapping text

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.45.103 Chromium: 106.0.5249.126 (Official Build) beta (64-bit)
-- | --
Revision | fb2e06d2dee20fe0c804528502b5ad72c613abd9-refs/branch-heads/5249_118@{#3}
OS | Ubuntu 18.04 LTS

cc @rebron @sangwoo108

**Comment by kjozwiak** [comment]
The above requires `1.45.109` or higher for `1.45.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.45.109 Chromium: 107.0.5304.62 (Official Build) (x86_64)
-- | --
Revision | 1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942}
OS | macOS Version 12.6 (Build 21G115)
```
