### ISSUE TITLE
News Suggestions backend should remove www. prefix hack

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#26092]
When https://github.com/brave/news-aggregator/issues/58 is solved, we should remove the www. prefix hack at https://github.com/brave/brave-core/blob/faf05930c46dd6b3fbe7f14e6e25f28bd88768a7/components/brave_today/browser/suggestions_controller.cc#L91

**Comment by fallaciousreasoning** [comment]
Issue is fixed in the aggregator - closing and removing.
