### ISSUE TITLE
Settings header is not shown when loading `brave://wallet` or navigating to Wallet from Settings page

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#26093]
## Description 

Settings header is not shown when loading `brave://wallet` or navigating to Wallet from Settings page

## Steps to Reproduce

   1. Install 1.46.66 
   2. Open a new tab and load `brave://wallet`
   3. No settings header bar is shown
   4. Open a new tab and load settings page, settings bar is shown with Wallet
   5. Click on wallet in header bar from settings page
   6. Brave wallet page loads but settings header is removed

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/196349074-059d2df0-d78a-4d1d-9c7b-606ede75c703.png)

## Expected result:
Not sure

## Reproduces how often: 

East

## Brave version (brave://version info)

<html><head></head>
<body>

Brave | 1.46.66 Chromium: 107.0.5304.36 (Official Build) nightly (64-bit)
-- | --
Revision | `2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}`
OS | Windows 11 Version 22H2 (Build 22623.746)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @emerick @rebron

**Comment by kjozwiak** [comment]
The above requires `1.45.106` for `1.45.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.45.106 Chromium: 107.0.5304.36 (Official Build) (64-bit) 
-- | --
Revision | `2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}`
OS | Linux

- Verified steps from issue description
- Verified navigation bar is shown for `brave://wallet` as well

https://user-images.githubusercontent.com/17010094/196865562-2336576a-919f-4d3b-8af1-ee06d8bd53ea.mp4

------------------------
Verification passed on

Brave | 1.45.106 Chromium: 107.0.5304.36 (Official Build) (64-bit) 
-- | --
Revision | `2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}`
OS | Windows 11 Version 22H2 (Build 22621.674)

- Verified steps from issue description
- Verified navigation bar is shown for `brave://wallet` as well

https://user-images.githubusercontent.com/17010094/196865573-7e5baa55-3e8f-4274-a4a6-f27c89c1b9f4.mp4

------------------------
Verification passed on

Brave | 1.45.106 Chromium: 107.0.5304.36 (Official Build) (arm64)
-- | --
Revision | `2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}`
OS | macOS Version 12.4 (Build 21F79)

- Verified steps from issue description
- Verified navigation bar is shown for `brave://wallet` as well

https://user-images.githubusercontent.com/17010094/196865666-627e324a-0614-4834-ba56-780d4adf2595.mov
