### ISSUE TITLE
`Brave Wallet (Prefer extensions)` text cuts off in dropdown 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#26095]
## Description 

Brave Wallet (Prefer extensions) text cuts off in dropdown 

## Steps to Reproduce

   1. Clean profile `1.46.64`
   2. Open brave://settings/wallet
   3. `Brave Wallet (Prefer extensions)` text cuts off in dropdown 

## Actual result:

`Brave Wallet (Prefer extensions)` text cuts off in dropdown 
![image (4)](https://user-images.githubusercontent.com/38657976/196378880-a71f9e2b-2fc4-4814-b291-e91386a295e8.png)

## Expected result:

![image (5)](https://user-images.githubusercontent.com/38657976/196378985-0c4c635d-c4ad-4597-84d1-6c04301b6906.png)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.46.64 Chromium: 107.0.5304.36 (Official Build) nightly (64-bit)
-- | --
Revision | 2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}
OS | Windows 10 Version 21H2 (Build 19044.2130)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @rebron @emerick

**Comment by jamesmudgett** [comment]
We should rename this to "Extensions"

**Comment by adithyaakrishna** [comment]
@jamesmudgett @GeetaSarvadnya Can I take this up?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.49.118 Chromium: 111.0.5563.50 (Official Build) (64-bit)
-- | --
Revision | `39f3dfc5023fe60997adc4f6cf5439cfa3e6968a-refs/branch-heads/5563@{#903}`
OS | Linux

- Verified steps from issue descripton
- Verified `Brave Wallet (Prefer extensions)` not show as `Extensions`

Default Ethereum wallet | Default Solana wallet
-- | --
![image](https://user-images.githubusercontent.com/17010094/222656092-fdb76b20-b702-490b-b9b0-fda2f050e1dc.png) | ![image](https://user-images.githubusercontent.com/17010094/222656061-c2d73c46-a146-4e49-946a-a1a538cbdff5.png)
