### ISSUE TITLE
[Android] BR panel showing blank values on first state after enabling rewards

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#26108]
## Description 
BR panel blank on first state after enabling rewards

*Reproduces on Tablet as well 

https://user-images.githubusercontent.com/17885425/196539592-0bc0d006-2828-413d-9238-e552c18985e8.mp4

## Steps to reproduce 

   1. Clean install nightly (C106)
   2. Complete onboarding
   3. Enable rewards
   4. Notice the BR panel upon enabling rewards
   5. Close the panel and reopen
   6. Notice nothing is missing now

## Actual result 
Numeric values are missing in the panel

## Expected result
Nothing should be missing

## Issue reproduces how often 
Always

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung Galaxy
   - Android version: 12
   
## Brave version
1.46.56 CR106

**Comment by kjozwiak** [comment]
hmm not sure how this stayed opened after https://github.com/brave/brave-core/pull/15531 was closed and the above issue was mentioned as the `Resolved` GH issue. Closing 👍

**Comment by kjozwiak** [comment]
The above requires `1.46.78` or higher for `1.46.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Vivo X70 Pro version 12` running `Bravemonoarm.apk_1.46.99'

- Ensured that BP panel values are not blank after enabling the rewards
