### ISSUE TITLE
update text to Copy clean link

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#26106]
## Description 

For the Copy clean URL feature, update the text and simplify to `Copy clean link` in the Share menu and in the right click context menus from the URL bar and on a link on a page.

## Steps to Reproduce

1. Right click on a link on page.
2. Go to URL bar and right click on the URL.
3. Go to Share menu icon in the URL bar.

## Actual result:

Text label below Copy reads as `Copy clean link (only main URL)

Share menu
<img width="374" alt="Screenshot 2022-10-18 at 12 53 53 PM" src="https://user-images.githubusercontent.com/5951041/196532719-5b9210d6-27a3-4421-b7bf-44dbb068dbb3.png">
Context menu URL bar
<img width="356" alt="Screenshot 2022-10-18 at 12 54 03 PM" src="https://user-images.githubusercontent.com/5951041/196532726-3aeedc67-a26a-45f8-a402-585a241cab97.png">

## Expected result:
Label should read as `Copy clean link`

Share menu
<img width="432" alt="196314358-629cf960-914f-43cb-a769-fb469f2c2268" src="https://user-images.githubusercontent.com/5951041/196532808-8a82cd37-48a2-421a-a6a7-72b744f2f2e3.png">

Context menu URL bar
<img width="476" alt="196323051-1f17a492-9b76-42a3-bd71-973e08251a9d" src="https://user-images.githubusercontent.com/5951041/196532815-88cefa50-8033-4ac6-a3e3-b4a78ddb57f8.png">

## Reproduces how often: 

Easily.

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:
Related issues:
https://github.com/brave/brave-browser/issues/23315 initial issue
https://github.com/brave/brave-browser/issues/25845 context menu follow-up
https://github.com/brave/brave-browser/issues/25621 discussion of text

cc: @fmarier, @mkarolin @spylogsster @rmcfadden3

**Comment by kjozwiak** [comment]
The above requires `1.45.111` or higher for `1.45.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.45.111 Chromium: 107.0.5304.62 (Official Build) (64-bit)
-- | --
Revision | 1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942}
OS | Windows 11 Version 21H2 (Build 22000.1098)
```

Install 1.45.111
launch Brave
visit a website (github.com)
Go to URL bar and right click on the URL.

Confirmed the label in the context menu URL bar reads as `Copy clean link` 

![image](https://user-images.githubusercontent.com/98358127/197583999-5f0dbe7f-2e2f-4b52-b3bb-4edb2221e5af.png)
