### ISSUE TITLE
Improve behavior when Brave can't auto-update on Mac

### ISSUE THREAD

**Issue by mherrmann** [brave/brave-browser#26103]
Chromium has a nice feature where installations that haven't been updated in a while show increasingly pressing warnings in the top right corner:

![image](https://user-images.githubusercontent.com/1076393/196523248-eb9ced4d-0e61-47be-b4d1-69d6ad8852d5.png)

In contrast, our current implementation shows the following [obtrusive](https://twitter.com/patrick99e99/status/1581458270295756800/photo/1) popup whenever an update becomes available but Brave cannot auto-update:

![image](https://user-images.githubusercontent.com/1076393/196522658-9493a84b-7847-4a3a-817b-e60103349806.png)

(Brave on Mac cannot auto-update when it doesn't have write access to the installation directory. This includes when Brave was installed via its `.pkg` installer.)

The goal of this issue (if @rebron et al. agree) is to remove the auto-update popup on macOS in favor of the above implementation. It would supersede #9562.

**Comment by britalmeida** [comment]
This would be really nice!
It used to be like this? But in the last half year it regressed to being a popup for me :(
Could it be because something changed on my end regarding mac permissions? I thought it was because Brave changed it.

**Comment by mherrmann** [comment]
@britalmeida did you install Brave with the `.pkg` installer? Because if yes, then that's a known bug.

**Comment by britalmeida** [comment]
@mherrmann I no longer remember :|
How can I check my setup and correct if needed?

**Comment by mherrmann** [comment]
@britalmeida you could reinstall Brave with a .dmg file from https://github.com/brave/brave-browser/releases/tag/v1.52.129 and see if the problem persists :)

**Comment by mherrmann** [comment]
The two pieces of UI in the description above are actually separate things.

The warning in the top right corner gets shown by upstream logic when the build is more than (I think) 5 weeks old. In this case, upstream believes it is unable to update, and shows the warning to ask the user to re-install.

The popup is shown by Sparkle when it discovers an update but cannot write to Brave's installation directory. This is for example the case when Brave was installed via the PKG installer, because of #39567.

So the warning gets shown when the build is outdated, independently of whether a new version is available. And the popup gets shown when there is a new update, but Sparkle can't write to the installation directory.

We are currently working on migrating from Sparkle to Omaha 4, which will make any plans described here obsolete. So I'm closing this issue as unplanned.
