### ISSUE TITLE
Popup doesn't close after gateway url change

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#26104]
## Description 
After clicking the "Submit" button popup doesn't close
![image](https://user-images.githubusercontent.com/106654560/196524578-a4dd4ed5-f39c-4967-aba5-ae7262dfb5c4.png)

**Comment by stephendonner** [comment]
This was/is a duplicate of https://github.com/brave/brave-browser/issues/21479 - thanks for fixing!

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.47.126 Chromium: 108.0.5359.99 (Official Build) beta (64-bit)
-- | --
Revision | `410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}`
OS | Linux

- Verified steps from issue description
- Verified able to close the popup for both public gateway and NFT gateway settings

https://user-images.githubusercontent.com/17010094/207512205-4fdaacc7-1fb3-4441-973c-ff0e9810e34f.mp4


---------------------

Verification passed on 

Brave | 1.47.126 Chromium: 108.0.5359.99 (Official Build) beta (64-bit)
-- | --
Revision | `410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from issue description
- Verified able to close the popup for both public gateway and NFT gateway settings

https://user-images.githubusercontent.com/17010094/207511771-27025d4b-829c-4b72-869b-7c1f37b0c457.mp4


---------------------

Verification passed on 

Brave | 1.47.126 Chromium: 108.0.5359.99 (Official Build) beta (arm64)
-- | --
Revision | `410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from issue description
- Verified able to close the popup for both public gateway and NFT gateway settings

https://user-images.githubusercontent.com/17010094/207511372-0ad9f286-380b-4884-82ab-483d9afdec06.mov
