### ISSUE TITLE
clicking on an in-line tip icon does not open the panel to show rewards onboarding

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#26109]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/14277

Prior to opting into Brave Rewards, if you click on an in-line tip icon (on twitter, reddit, gh), the panel should open and show onboarding. This is not occurring with 1.46.x. When you click on the in-line tip button nothing happens in the UI, so the button appears broken.

Not sure if this is related to the changes from #14277. 

Note, confirmed that the panel opens as expected to offer onboarding with 1.45.x via https://github.com/brave/brave-browser/issues/24538#issuecomment-1268726176.

## Steps to Reproduce

1. Fresh profile, relaunch to pull griffin seed
2. Go to twitter.com/emerick (or reddit.com/u/cryptojennie or open this GH issue)
3. Click on an in-line tip button

Note to @brave/qa-team - when retesting this issue after it's fixed, Case 4 from https://github.com/brave/brave-browser/issues/14277#issuecomment-1282400589 needs to be checked.

## Actual result:

Nothing happens

## Expected result:

Rewards panel opens to show onboarding

<img width="1197" alt="Screen Shot 2022-10-18 at 4 40 44 PM" src="https://user-images.githubusercontent.com/28145373/196542996-22c5f017-66e4-4c9d-b1f4-7d39b8b3996c.png">

## Reproduces how often: 

easily

## Brave version (brave://version info)

```
Brave | 1.46.66 Chromium: 107.0.5304.36 (Official Build) nightly (x86_64)
-- | --
Revision | 2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}
OS | macOS Version 12.6 (Build 21G115)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 1.44.x n/a
- Can you reproduce this issue with the beta channel? 1.45.x no
- Can you reproduce this issue with the nightly channel? 1.46.x yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @Miyayes @mkarolin

**Comment by LaurenWags** [comment]
Added `release/blocking` per discussion with @Miyayes

**Comment by LaurenWags** [comment]
Uplift required, adding `QA/Blocked` for now.

**Comment by kjozwiak** [comment]
Removing `QA/Blocked`. The above requires `1.46.80` or higher for `1.46.x` verification 👍
