### ISSUE TITLE
Fade out page content when opening the tip panel [Tablet]

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#26112]
## Description 
BR Panel is shown when open tip panel [Tablet]

The page content is not shown on mobile because of the screen size, its just the top blue welcome section and bottom part with the tipping information.

https://user-images.githubusercontent.com/17885425/196543970-f0efeef7-6707-4349-a9ca-0840ad8fb81f.mp4

## Steps to reproduce 

   1. Clean install
   2. Enabled Rewards
   3. load a webpage
   4. Open the BR panel
   5. Tap `Send Tip`
   6. Observe UI

## Actual result 
Page content is shown, BR panel is partly shown.

## Expected result
The content part should be blurred out or faded so it doesnt' look so messy with the BR panel in the background overlapping

## Issue reproduces how often 
Always

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung Galaxy S21
   - Android version: 12
   
## Brave version
1.46.56, 1.46.x

**Comment by LaurenWags** [comment]
cc @Miyayes for thoughts on this one

**Comment by Miyayes** [comment]
This looks pretty bad. Let's make sure the tipping portion and the top banner portion stick together, and then blur (or darken) the underlying page. @sujitacharya2005

**Comment by Miyayes** [comment]
Resolved by https://github.com/brave/brave-core/pull/15687

**Comment by kjozwiak** [comment]
The above requires `1.46.109` or higher for `1.46.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on the `Samsung Galaxy Tab A7 version 12` running `Bravemonoarm64.apk_1.46.109`
 - Ensured that Rewards panel is NOT shown on the tipping banner
