### ISSUE TITLE
App halts when entering decimal point in custom tip field

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#26110]
## Description 
Entering decimal in custom tip field will halt app

Reproducible on Tablet as well

https://user-images.githubusercontent.com/17885425/196542171-1abd8d87-1ef9-476a-a0e6-7396f1d4acae.mp4

## Steps to reproduce 

   1. Clean install 1.46.x
   2. Switch to staging rewards env in QA preferences
   3. Enable rewards
   4. Navigate to webpage
   5. Open BR panel
   6. Tap `Send Tip`
   7.  Select `Custom tip amount`
   8. Clear the 1.25 BAT shown by default
   9. Start by entering a period/decimal point

## Actual result 
App halts/closes

## Expected result
We should be validating this use case

## Issue reproduces how often 
Always, will halts the app repeatedly.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NO
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung Galaxy Devices
   - Android version: 12 
   
## Brave version

1.46.56, 1.46.64

**Comment by kjozwiak** [comment]
Closing as this was fixed by https://github.com/brave/brave-core/pull/15521#issue-1413929400.

**Comment by kjozwiak** [comment]
The above requires `1.46.78` or higher for `1.46.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.46.96 x64 Beta build
- Verified steps from issue description
- Verified able to set a decimal value for one time tips without browser crash
- Verified able to submit a decimal value tip to both verified and non-verified publisher
- Encountered [#26661](https://github.com/brave/brave-browser/issues/26661)

https://user-images.githubusercontent.com/17010094/201063851-17e38df0-4dc6-4fc9-8b72-6d400ee1e5ce.mp4
