### ISSUE TITLE
Channels in Brave News are not translated

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#26116]
We should add translations for channels in Brave News. The V1 UI doesn't support this at all.

**Comment by kjozwiak** [comment]
The above will require `1.46.100` or higher for `1.46.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.46.100 Chromium: 107.0.5304.91 (Official Build) dev (x86_64)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | macOS Version 11.7.1 (Build 20G918)

### Steps:

1. set my macOS system language to Russian, and German (separately, of course)
2. installed `1.46.100`
3. launched Brave
4. opened `brave://flags`
5. set `brave://flags/#brave-news-v2` to `Enabled`
6. clicked `Relaunch`
7. opened a new-tab page
8. clicked on `Customize`
9. clicked on `Brave News`
10. examined the `Customize Brave News` dialog

#### Confirmed `Crypto` became `криптовалюта` in Russian, and `Krypto` in German

`Russian` | `German`
--------|---------
<img width="1075" alt="Снимок экрана 2022-11-08 в 11 12 48 AM" src="https://user-images.githubusercontent.com/387249/200657011-e7c8181c-ee73-486f-ab47-d05d912ba83c.png"> | <img width="1075" alt="Bildschirmfoto 2022-11-08 um 11 19 33 AM" src="https://user-images.githubusercontent.com/387249/200657081-4d1235e5-c6e9-4f71-b500-8463bf2b4b4a.png">

**Comment by srirambv** [comment]
Removing Android label as this doesn't work on Android. There is no V2 UI and translation is not done for existing sources. Added follow up/Android specific issue #26660 

<img width=300 src=https://user-images.githubusercontent.com/17010094/201059769-83618215-4954-4df0-a7ba-a308f5b0b4e3.png>
