### ISSUE TITLE
Link to Transifex Page in README.md broken

### ISSUE THREAD

**Issue by chnuessli** [brave/brave-browser#26111]

**Comment by NaaeemMalik** [comment]
@bsclifton sorry about opening another pull request just after you closed first but I noticed the link you mentioned in your previous comment had a broken link in it so I fixed it, just like @chnuessli  did in README.md

**Comment by chnuessli** [comment]
Thabks for the merge @bsclifton

**Comment by NaaeemMalik** [comment]
@bsclifton commit of @chnuessli  only fixed the issue in README.md not in Contributing.md, so that's why I sent pull request with fix in that file as well but you closed that pull requested without approving. just FYI

**Comment by bsclifton** [comment]
oh whoops, sorry @NaaeemMalik

**Comment by rebron** [comment]
@bsclifton 1.47.x milestone correct?

**Comment by bsclifton** [comment]
@rebron yeah - but it's just the GitHub README.md. Nothing in the binary being shipped
