### ISSUE TITLE
Update the Brave News V2 Channels UI to use the new icons from Figma

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#26115]
Now we have icons we should update Brave News to use them!

https://www.figma.com/file/SDcE22eeUsV2uc4dy3NwaC/Onboarding?node-id=740%3A67478

![image](https://user-images.githubusercontent.com/7678024/196570662-894ea759-a462-4b41-ad5f-fab511fd74f7.png)

**Comment by kjozwiak** [comment]
The above will require `1.46.100` or higher for `1.46.x` verification 👍
