### ISSUE TITLE
Lost the Welcome Page favicon

### ISSUE THREAD

**Issue by rossmoody** [brave/brave-browser#2611]
Lost the favicon with the new welcome page update. 

![image](https://user-images.githubusercontent.com/29072694/50118956-2f694c00-0206-11e9-8017-bcfc9202efc9.png)

**Comment by kjozwiak** [comment]
@bbondy @rebron should we uplift this into `0.59.x` as it's a regression? Granted, it's really not that noticeable but seems like a simple thing to uplift so we don't regress under `0.59.x` when released. Example:

<img width="614" alt="screen shot 2019-01-04 at 1 35 29 am" src="https://user-images.githubusercontent.com/2602313/50676225-3d1e2000-0fc1-11e9-9877-4b2f575dbf98.png">

Top one belongs to `0.58.18 Chromium: 71.0.3578.98 (Official Build)` which is the current release.

**Comment by bbondy** [comment]
sgtm

**Comment by GeetaSarvadnya** [comment]
Verification passed on 


Brave | 0.59.20 Chromium: 72.0.3626.28 (Official Build) beta (64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Windows
