### ISSUE TITLE
Typo in the Brave Wallet Show Private Key UI

### ISSUE THREAD

**Issue by deepansh96** [brave/brave-browser#26120]
## Description 

When I try to view my wallet account's private key in the Brave Browser Wallet, it asks me for my wallet password.
But the placeholder text inside the textbox is incorrect. It says "Enter new password" whereas it should say "Enter your brave wallet password".
Ideally the placeholder text should not even be there as the text telling the user to put in their password already comes up above the textbox, so no need to tell the same information twice.

## Steps to Reproduce

   1. Create/configure a brave wallet. 
   2. Navigate to the following link in the browser `brave://wallet/crypto/accounts`
   3. Click on your account and then click the small QR scanner icon to show up more details of your account.
   4. In the menu that opens, switch from the `Details` tab to `Private Key` tab. There you can see a textbox with a title saying `Enter your Brave Wallet password` and a placeholder text saying `Enter new password`

## Actual result:

<img width="537" alt="image" src="https://user-images.githubusercontent.com/20169829/196612339-60a94e02-14bd-4336-8cd4-a986f72760b0.png">

## Expected result:
<img width="557" alt="Screenshot 2022-10-19 at 11 51 52 AM" src="https://user-images.githubusercontent.com/20169829/196612407-cd6ed23f-957a-493c-ae1e-faad7f84dce1.png">

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

```
Brave | 1.44.105 Chromium: 106.0.5249.91 (Official Build) (arm64)
-- | --
Revision | fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}
OS | macOS Version 12.6 (Build 21G115)
JavaScript | V8 10.6.194.17
User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Not sure
- Can you reproduce this issue with the nightly channel? Not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? - Chrome doesn't have brave wallet

**Comment by srirambv** [comment]
This is fixed in beta as part of #25745. Thanks for reporting.
