### ISSUE TITLE
Token details bug - Figures leaving screen

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#26122]
## Description 

See screenshot
<img width="862" alt="Screenshot 2022-10-19 at 14 49 32" src="https://user-images.githubusercontent.com/12224304/196701557-b282a798-7640-463c-ba17-d6f1b79dc868.png">

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.47.126 Chromium: 108.0.5359.99 (Official Build) beta (64-bit)
-- | --
Revision | `410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}`
OS | Linux

- Verified steps from [brave/brave-core#15562](https://github.com/brave/brave-core/pull/15562)
- Verified ERC20 tokens balance is shown with in the token details screen
![image](https://user-images.githubusercontent.com/17010094/207540463-aaa1a1af-4106-4edf-ab54-b5c7cff73882.png)

---------------------

Verification passed on 

Brave | 1.47.126 Chromium: 108.0.5359.99 (Official Build) beta (64-bit)
-- | --
Revision | `410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#15562](https://github.com/brave/brave-core/pull/15562)
- Verified ERC20 tokens balance is shown with in the token details screen
![image](https://user-images.githubusercontent.com/17010094/207540105-ab002651-0c32-480d-8bdf-2154da662afe.png)

---------------------

Verification passed on 

Brave | 1.47.126 Chromium: 108.0.5359.99 (Official Build) beta (arm64)
-- | --
Revision | `410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#15562](https://github.com/brave/brave-core/pull/15562)
- Verified ERC20 tokens balance is shown with in the token details screen
![image](https://user-images.githubusercontent.com/17010094/207540780-8e24fa16-93e0-4948-aaef-e955fbd53faa.png)
