### ISSUE TITLE
Updating from 1.44.112 64bit to Release v1.45.106 Pre-release not working

### ISSUE THREAD

**Issue by gh0sti** [brave/brave-browser#26123]
## Description 

I ran the bravebrowsersetup.exe that was provided on the pre-release of 1.45.106 and it did not upgrade my existing brave browser. 

## Steps to Reproduce

   1. Download BraveBrowserSetup.exe
   2. close existing brave browser instance
   3. run the .exe
   4. open brave, build does not change to newest one.

## Actual result:

This is the details of the .exe build grab from github
![image](https://user-images.githubusercontent.com/4202657/196703082-a1609e0e-7a9c-43ca-903e-05eb7ce02e63.png)
![image](https://user-images.githubusercontent.com/4202657/196703174-0e7486a3-2af5-432d-b20f-ef50599023eb.png)
![image](https://user-images.githubusercontent.com/4202657/196703254-32d92874-4de3-4439-91af-f33bcabdcbd1.png)
![image](https://user-images.githubusercontent.com/4202657/196703317-8d2e4fb3-4d9b-42a3-9a52-a77d9f5a65aa.png)
![image](https://user-images.githubusercontent.com/4202657/196703360-fb87b05a-636f-4795-9029-eb3b18175dff.png)

the Bravebrowser should have been upgraded to 1.45.106 but it did not.

## Expected result:
BraveBuild should have changed to a newer version.

## Reproduces how often: 

everytime I run the new package installer it should have changed the build.

## Brave version (brave://version info)

![image](https://user-images.githubusercontent.com/4202657/196703667-abaab66f-1164-4b70-a122-dfefc4fcee94.png)

## Version/Channel Information:

trying to upgrade to pre-release from release channel

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? haven't tried
- Can you reproduce this issue with the nightly channel? haven't tried

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? haven't tried

## Miscellaneous Information:
 I was able to on my 2019 macbook pro intel upgrade to pre-release build without issue when downloading the .dmg. The .exe 64build for Windows should have upgraded my build. I am running Win 11 64bit 22H2 22621.674

**Comment by rebron** [comment]
@gh0sti. This is the latest pre-release version. https://github.com/brave/brave-browser/releases/tag/v1.45.109
You need to install BraveBrowserStandAloneSetup.exe. 

If you install BraveBrowserSetup.exe that will pull the current release version.

**Comment by gh0sti** [comment]
Well stand alone update and keep my pref on windows?
