### ISSUE TITLE
Brave News Button should be to the left of the Tor Button

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#26138]
Currently, it shows to the right, which looks a bit odd. 
![image](https://user-images.githubusercontent.com/7678024/196786117-d2ca15dd-31e6-42c0-bbd3-b0da057ad74e.png)

Should also be to the left of the share icon

**Comment by Sathvik902** [comment]
Hello!
I am pretty confident from my experience that I can work on this issue.
Please assign me to this..

**Comment by fallaciousreasoning** [comment]
Sorry @Sathvik902, the issue has already been fixed

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.47.110 Chromium: 108.0.5359.71 (Official Build) beta (x86_64)
-- | --
Revision | 1e0e3868ee06e91ad636a874420e3ca3ae3756ac-refs/branch-heads/5359@{#1016}
OS | macOS Version 13.1 (Build 22C5059b)

### Steps:
1. installed `1.47.110`
2. launched Brave
3. opened a new-tab page
4. loaded `theguardian.com`
5. examined and clicked on the `Manage Subscriptions` RSS-feed icon in the URL bar

#### Confirmed the `Manage Subscriptions` button was to the left of the `Tor` button, in the URL bar

### `Light` mode:

`default` | `clicked`
----------|---------
<img width="1101" alt="Screenshot 2022-12-03 at 4 42 57 PM" src="https://user-images.githubusercontent.com/387249/205468478-260f16b5-d215-4920-9068-ec8db03d5b6e.png"> | <img width="1101" alt="Screenshot 2022-12-03 at 4 43 06 PM" src="https://user-images.githubusercontent.com/387249/205468479-d5fbc21d-1adc-48e8-a76b-03c329094c79.png">

### `Dark` mode:

`default` | `clicked`
----------|---------
<img width="1128" alt="Screenshot 2022-12-03 at 4 43 30 PM" src="https://user-images.githubusercontent.com/387249/205468481-91dec54c-9060-4ec5-a2e5-f8a541ffa86b.png"> | <img width="1128" alt="Screenshot 2022-12-03 at 4 43 34 PM" src="https://user-images.githubusercontent.com/387249/205468482-66dda7fa-49a6-4280-ba18-4ef8aa47baa0.png">
