### ISSUE TITLE
Add localisation for gas titles

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#26136]
## Description 

Add localisation for gas titles
- [Gas Premium](https://github.com/brave/brave-core/blob/a8565ea7f9838a3732706d746df2a1ea072157d6/components/brave_wallet_ui/components/extension/confirm-transaction-panel/transaction-info.tsx#L95)
- [Gas Limit](https://github.com/brave/brave-core/blob/a8565ea7f9838a3732706d746df2a1ea072157d6/components/brave_wallet_ui/components/extension/confirm-transaction-panel/transaction-info.tsx#L106)

## Expected result:
Fetch titles via `getLocale`

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.50.93 Chromium: 111.0.5563.64 (Official Build) beta  (64-bit) 
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Linux

- Verified steps from [brave/brave-core#16888](https://github.com/brave/brave-core/pull/16888)
- Verified on transaction confirmation screen, transaction info labels are shown same as before.
- Encountered [#28886](https://github.com/brave/brave-browser/issues/28886)
![image](https://user-images.githubusercontent.com/17010094/225869264-f3ba7162-3877-4cfd-b8b4-0cc41f4d943c.png)

---------------------

Verification passed on 

Brave | 1.50.93 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from [brave/brave-core#16888](https://github.com/brave/brave-core/pull/16888)
- Verified on transaction confirmation screen, transaction info labels are shown same as before.
- Encountered [#28886](https://github.com/brave/brave-browser/issues/28886)
![gQfCMJrA1N](https://user-images.githubusercontent.com/17010094/225869500-2be0ad9e-a837-42db-92de-de7085caedb9.png)

---------------------

Verification passed on 

Brave | 1.50.93 Chromium: 111.0.5563.64 (Official Build) beta (arm64)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#16888](https://github.com/brave/brave-core/pull/16888)
- Verified on transaction confirmation screen, transaction info labels are shown same as before.
- Encountered [#28886](https://github.com/brave/brave-browser/issues/28886)
![image](https://user-images.githubusercontent.com/17010094/225869800-4321ed3f-751b-4a94-9be6-ac21207c72cb.png)
