### ISSUE TITLE
Brave background images are not loaded sometimes, instead a Gradient color is loaded.

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#26135]
## Steps to Reproduce

   1. Install 1.45.106
   2. Launch Brave
   3. Click `Skip welcome tour`
   4. Click `Customize`
   5. Click `Brave backgrounds` tile
   

## Actual result:

Sometimes Brave background images are not loaded for the very first tab and instead Gradient color is loaded. 

https://user-images.githubusercontent.com/98358127/196756680-5181c8d9-1e41-48da-86f9-61d2f9db9a9a.mp4

## Expected result:
Brave background images should be loaded

## Reproduces how often: 

intermittent

## Brave version (brave://version info)

```
Brave | 1.45.106 Chromium: 107.0.5304.36 (Official Build) (64-bit)
-- | --
Revision | 2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}
OS | Windows 11 Version 21H2 (Build 22000.1098)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release?  N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@sangwoo108 @rebron

**Comment by sangwoo108** [comment]
Thanks @MadhaviSeelam , I thought I fixed this but it seems I made a mistake. This occurs when the profile is fresh one and background images are not fetched yet. So in few secs, newly created tabs won't have this problem and the very first tab has this problem. I'll make a fix for this again.

**Comment by kjozwiak** [comment]
The above requires `1.45.111` or higher for `1.45.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.45.111 Chromium: 107.0.5304.62 (Official Build) (64-bit)
-- | --
Revision | 1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942}
OS | Windows 11 Version 21H2 (Build 22000.1098)
```
Verified using original STR from the description https://github.com/brave/brave-browser/issues/26135#issue-1415325749

Confirmed `Brave backgrounds` images are loaded as expected on the very first tab.

https://user-images.githubusercontent.com/98358127/197560266-03915628-1a8a-4fa6-bfc6-f74e7d77954a.mp4
