### ISSUE TITLE
Search engine for Private Window with Tor is not imported from Muon

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#2613]
Follow up to https://github.com/brave/brave-browser/issues/2415

## Steps to Reproduce

1. In Muon  in `about:preferences#search`, set `Use DuckDuckGo by default for search in Private Tabs with Tor` to false
2. Close Muon
3. In b-c, Import data(doesn't matter which items you pick) from Brave (old) in `chrome://settings/importData`

## Actual result:

DuckDuckGo remains the default search engine in b-c.
DuckDuckGo logo and text is show on new tab

![image](https://user-images.githubusercontent.com/34715963/50124230-ffe92c80-0263-11e9-9257-b7a4526e2271.png)

## Expected result:
DuckDuckGo is not the default search engine in b-c
DuckDuckGo logo and text is not show on new tab

## Reproduces how often: 

always

## Brave version (brave://version info)

Brave | 0.58.14 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Windows 7

cc @brave/legacy_qa

**Comment by LaurenWags** [comment]
Reproduces on macOS

Brave | 0.58.14 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Mac OS X

**Comment by btlechowski** [comment]
Reproduced on Ubuntu 17.10

Brave | 0.58.15 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Linux

**Comment by bsclifton** [comment]
Closing as I don't think we'll be fixing this
