### ISSUE TITLE
Make the Site banner icon visible

### ISSUE THREAD

**Issue by rossmoody** [brave/brave-browser#2614]
Update the color and shadow treatment for the icon in site banners to be more visible on light and dark backgrounds.

<img width="565" alt="49309646-be4d3900-f490-11e8-94ba-5c6c54113871" src="https://user-images.githubusercontent.com/29072694/50132047-ecc16700-0239-11e9-9b54-0d1839618e31.png">

**Comment by petemill** [comment]
Closed via https://github.com/brave/brave-ui/pull/300

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Ubuntu 18.04.1 x64` using the following build:

Brave | 0.58.15 Chromium: 71.0.3578.98 (Official Build) (64-bit)
--- | ---
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Linux

**Before the fix (0.58.14):**

<img width="636" alt="screen shot 2018-12-18 at 11 18 24 pm" src="https://user-images.githubusercontent.com/2602313/50198849-8d3b8800-031b-11e9-9065-74fe3f5e2fa5.png">

**After the fix (0.58.15):**

<img width="564" alt="screen shot 2018-12-18 at 11 13 04 pm" src="https://user-images.githubusercontent.com/2602313/50198863-9e849480-031b-11e9-8b04-80a79c85afb0.png">
