### ISSUE TITLE
Make eTLD+1 always visible in the URL bar

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#26155]
Currently Brave and Chrome ways to show long URLs are different:
<img width="464" alt="Screenshot 2022-10-14 at 14 41 00" src="https://user-images.githubusercontent.com/12011303/197031534-0d73b982-784e-4a4f-983c-5c3bf9b260be.png">
We need to use the same approach as Chrome for now. Ideally we want to implement like it's described here https://github.com/brave/brave-browser/issues/26052. But for now we are ok with a Chrome's approach.
A link to test with is https://long-extended-subdomain-name-containing-many-letters-and-dashes.badssl.com/ysigsgksgkskgslgsogslgslgslgslgslgsogsogsogslgsogsyosoys

**Comment by kjozwiak** [comment]
Reproduced the original issue on `Pixel 6` running `Android 13` using the following build(s):

```
Brave | 1.46.146 Chromium: 108.0.5359.128 (Official Build) (64-bit)
--- | ---
Revision | 1cd27afdb8e5d057070c0961e04c490d2aca1aa0-refs/branch-heads/5359@{#1185}
OS | Android 13; Build/TQ1A.221205.011
```

Using the STR/Cases outlined via https://github.com/brave/brave-core/pull/15574#issue-1417110259, reproduced the issue as per the following:

![image](https://user-images.githubusercontent.com/2602313/208512693-f8e12e63-e4dd-4310-a32d-559c391a1810.png)

Verification **PASSED** on `Pixel 6` running `Android 13` using the following build(s):

```
Brave | 1.47.135 Chromium: 108.0.5359.128 (Official Build) beta (32-bit)
--- | ---
Revision | 1cd27afdb8e5d057070c0961e04c490d2aca1aa0-refs/branch-heads/5359@{#1185}
OS | Android 13; Build/TQ1A.221205.011
```

Went through the STR/Cases outlined via https://github.com/brave/brave-core/pull/15574#issue-1417110259 and ensured that the URL was correctly being displayed as per the following:

![image](https://user-images.githubusercontent.com/2602313/208515746-338f68c6-9988-4750-b0ac-707882c66605.png)
