### ISSUE TITLE
Add option to disable Brave Translate for Android devices

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#26154]
## Description 
At the time of writing this, there is no way for users to disable the Brave Translate feature on Android devices. There does appear to be a way to do this via brave://flags, but I do not think this is ideal — there should be a clear/easy to find way for users to achieve this in the UI.

### Additional information

A thread with some users requesting this:
https://community.brave.com/t/cant-disable-brave-translate/439789/5

**Comment by atuchin-m** [comment]
cc @rebron @timchilds

**Comment by atuchin-m** [comment]
Here I mentioned adding it in brave://settings
https://bravesoftware.slack.com/archives/C02G7LEELQK/p1656517545218259?thread_ts=1634748449.086800&cid=C02G7LEELQK 

It seems that it was missed.

**Comment by Sam-Sibley** [comment]
@timchilds No objections, this seems like the most logical place for it to go.

**Comment by kjozwiak** [comment]
The above will need to be checked with a build that was created after `107.0.5304.110` went out via `1.45.x - Release #6`

**Comment by Uni-verse** [comment]
In progress using the following build(s):

```
Brave	1.45.125 Chromium: 107.0.5304.110 (Official Build) (64-bit) 
Revision	2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}
OS	Android 12; Build/SP1A.210812.016
```

**Brave Translate Enabled**

- Verified Brave Translate is enabled by default under settings > languages on fresh profile
- Verified Brave Translate switch can be disabled
- Verified Brave Translate tool bar is displayed on clean profile

Example | Example | Example
-|-|-
![screenshot-1668464802642](https://user-images.githubusercontent.com/17885425/201783737-d25f4da0-7b39-4f9b-ab20-1ae3f422e258.png) | ![screenshot-1668465294207](https://user-images.githubusercontent.com/17885425/201783773-f283cee2-81a6-40e8-b1cf-c82bcb8369b3.png) | ![screenshot-1668464870604](https://user-images.githubusercontent.com/17885425/201783937-baf2dc77-5e7b-47e9-91c2-17d13e4c22bc.png)


**Brave Translate Disabled**

- Verified disabling Brave Translate via the settings switch will prompt user to relaunch browser
- Verified Brave translate tool is not shown when Brave Translate is turned off
- Verified re-enabling Brave translate via the brave menu or the switch in the language settings will show the translate bar and will successfully translate the page

Example | Example | Example
-|-|-
![screenshot-1668465302739](https://user-images.githubusercontent.com/17885425/201784462-54a22c4d-2ca5-436e-8cbb-20baa5b8bb1e.png) | ![screenshot-1668465334536](https://user-images.githubusercontent.com/17885425/201784466-b9868a4f-cce6-455e-a435-13a7493ea27a.png) | ![screenshot-1668465377118](https://user-images.githubusercontent.com/17885425/201784469-4e043025-7e61-4aec-bab9-71edc08e8998.png)
