### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by mucahitkarson** [brave/brave-browser#26169]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.44.112  Chromium: 106.0.5249.119
Operating System: Linux 5.15.0-52-generic

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1.
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/3e100200-8f59-0609-0000-000000000000

**Comment by iefremov** [comment]
@mucahitkarson unfortunately this is not actionable without steps to reproduce, we've got a broken stacktrace
