### ISSUE TITLE
Clock shown on Brave start page is off by 1 hour

### ISSUE THREAD

**Issue by Plasma** [brave/brave-browser#2616]
## Description 

On the Brave start page, where you see your trackers blocked stats, there is a clock in the top right corner. My local time is currently 9.37pm AEDT (GMT+11), but shows as 8.37pm -- off by 1 hour.

We are in Daylight Savings Time at the moment which may be the cause, https://time.is/Melbourne

## Steps to Reproduce

   1. Have your local timezone set to Melbourne
   2. Load Brave start page
   3. Notice the clock is 1 hour behind

## Actual result:

Time shows as 8.37pm, 1 hour behind

## Expected result:

Should be 9.37pm

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

0.57.18 Chromium: 71.0.3578.80 (Official Build) (64-bit)
--
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}

**Comment by Liunkae** [comment]
What operating system are you using (Windows, macOS, Linux)?

**Comment by Plasma** [comment]
Windows in this example.

**Comment by Plasma** [comment]
This was an old laptop, so Windows 7 actually!

**Comment by kirkins** [comment]
Can't replicate on virtual machine running Windows 7 or Ubuntu version of Brave.

Changed my timezone to Melbourne and view start page. Timezone matches that of https://time.is/Melbourne

@Plasma the time wasn't off on your operating system?

**Comment by rebron** [comment]
Closing as stale issue.
