### ISSUE TITLE
Make Chromium storage partitioning compatible with Brave ephemeral storage implementation

### ISSUE THREAD

**Issue by goodov** [brave/brave-browser#26165]
Chromium has been working on its own storage partitioning for a while, they've come up with `StorageKey` that is spread across many storage APIs. The structure is similar to `NetworkIsolationKey/NetworkAnonymizationKey`, but is used mostly for eTLD+1 partitioning of cross sites (relative to the top origin).

We should adopt `StorageKey` as much as possible, befriend it with our ephemeral storage implementation and enable upstream partitioning where possible. Some of our partitioning tasks (for ex. https://github.com/brave/brave-browser/issues/24712) can use `StorageKey` for simpler implementation.

Here's Chromium invite to test their partitioning in the wild: https://developer.chrome.com/en/blog/storage-partitioning-dev-trial/

**Comment by goodov** [comment]
QA:
Run https://dev-pages.brave.software/storage/ephemeral-storage.html

**Comment by kjozwiak** [comment]
> QA: Run https://dev-pages.brave.software/storage/ephemeral-storage.html

Thanks @goodov 👍 Work to support `Chromium Storage` on the QA test pages was done via https://github.com/brave-experiments/qa-test-pages/pull/16. Just adding some context.

**Comment by LaurenWags** [comment]
@goodov should this be checked on Android as well - or is there a separate issue for implementation on Android?

**Comment by goodov** [comment]
This issue also covers Android and it should be tested there as well.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.64.95 Chromium: 122.0.6261.94 (Official Build) beta (x86_64)
-- | --
Revision | 6f4193fbcee7c358ae3684f777faa9f12e52206e
OS | macOS Version 13.6.4 (Build 22G513)
```

**Comment by goodov** [comment]
> 1. I'm seeing a problem with Step 6 from the test page with `All cookies allowed` and Ephemeral Storage enabled (by default). The tables don't match. Could you take a look? Unsure if this is a problem with the test page or the browser.

That doesn't look right. Did you enable cookies globally on `brave://settings/shields` or via the Brave Shields popup? Please create a separate issue for this, I'll look into it.

> 2. Do we need to run the tests on this page with Ephemeral Storage disabled?

No, please stop doing that. I'll update the test page to remove this text. We should not test the disabled stage at this point as it's an always-on feature.

**Comment by hffvld** [comment]
### IN PROGRESS...

Verified on `Galaxy Tab S8` and `Pixel 7` using version(s):
```
Device/OS: 
- Galaxy Tab S8 / gts8wifixx-user 14 UP1A.231005.007 release-keys
- Pixel 7 / panther_beta-user 14 AP21.240119.009 release-keys
Brave build: 1.64.95 
Chromium: 122.0.6261.94 (Official Build) beta (64-bit) 
```
---------------------------


**STEPS:**
1. Follow the steps from https://github.com/brave/brave-browser/issues/26165#issuecomment-1923279518
2. *Verify*

**ACTUAL RESULTS:**
- Verified that `Cross-site cookies blocked` testing `PASS`
- Verified that `Cookies Blocked` testing `PASS`
- 

---------------------------

<details>
<summary> Block cross-site cookies / Cross-site cookies blocked </summary>

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/0e7d04bb-ccd9-494c-a8dc-5045ead576f2) | ![2](https://github.com/brave/brave-browser/assets/128532965/1d2cf4a4-e6b5-4423-b64d-d3c1c6fe07de) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/90726d71-8c25-47d0-9b9e-b4258e8838ee) | ![2](https://github.com/brave/brave-browser/assets/128532965/d577ee3e-3a53-4191-8047-fbfb5212b6b6) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/d28e8332-8485-4205-acef-7ec8de679bd0) | ![2](https://github.com/brave/brave-browser/assets/128532965/ed0843f6-b858-4ee0-9f54-aa4e43a548cc) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/22df6f36-ee50-4fbe-9ba5-9158a2a06448) | ![2](https://github.com/brave/brave-browser/assets/128532965/924e8d48-382f-41a6-b9f5-4b28a4988f5a) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/f64f8d4c-08c5-49d2-9ff2-50ec21fa5d51) | ![2](https://github.com/brave/brave-browser/assets/128532965/a2db1d62-ad7e-433b-bf0d-f18fc1c16989) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/490eec62-beb1-411b-a6b3-d7dc3d46b182) | ![2](https://github.com/brave/brave-browser/assets/128532965/5d942b8e-d0d0-4167-b700-ff0dccc16558) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/83061a20-5d31-4e75-96b1-5ffa3b313263) | ![2](https://github.com/brave/brave-browser/assets/128532965/d2f4d151-2797-47db-8e57-d50024ea3156) |
</details>

<details>
<summary> Block all cookies / Cookies blocked </summary>

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/ecc8174f-4c1b-41a6-a806-33a6907b373c) | ![2](https://github.com/brave/brave-browser/assets/128532965/0e567c74-2fb6-4ce8-a6e8-3e952cebb7fc) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/bd485f0e-a0a3-4c8e-be29-d0a7645c8bbb) | ![2](https://github.com/brave/brave-browser/assets/128532965/6d7c270e-ae83-4859-ae8d-6d5f46a3ca65) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/cba773ef-d6b3-460a-9d6d-8c6de3a163ac) | ![2](https://github.com/brave/brave-browser/assets/128532965/453be0ad-7c4e-4bca-9a62-f7d870ba2bd9) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/c9a758fc-c3b9-474d-8548-9b4fde03a00d) | ![2](https://github.com/brave/brave-browser/assets/128532965/afac7beb-3ef1-419a-a236-7a1d9b7e5e1d) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/535364f9-a758-4abf-bbca-a2aaebfe4331) | ![2](https://github.com/brave/brave-browser/assets/128532965/e6189625-f7d3-444b-a1db-fa439451091d) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/4e6c78dd-c420-4e68-8037-5a689a7a0aef) | ![2](https://github.com/brave/brave-browser/assets/128532965/d31ec76a-4f78-4787-9729-71e7d116a309) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/467e4ea5-e8e7-4d36-8d74-067bd5f4a38d) | ![2](https://github.com/brave/brave-browser/assets/128532965/20d1b484-68c1-4739-8dc6-db5456a4d8a5) |
</details>

<details>
<summary> Allow all cookies / All cookies allowed </summary>

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/d83332f8-134d-4cf2-bb26-501063993b80) | ![2](https://github.com/brave/brave-browser/assets/128532965/5581e3c3-8162-43fe-8715-6196d91afc00) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/7b08c3e6-fbd5-42d5-a2f0-fc23a99077a1) | ![2](https://github.com/brave/brave-browser/assets/128532965/d8b9ff83-70a7-41f8-bca2-2c0d72021b46) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/14e0448d-0832-49f4-bde8-f4c211c61c0c) | ![2](https://github.com/brave/brave-browser/assets/128532965/b9b0b997-2b94-4a39-aae4-5a7bf7731177) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/7fa9f176-b37d-41d4-b5f3-1bcc152ceb6e) | ![2](https://github.com/brave/brave-browser/assets/128532965/55e655ce-4a3f-4895-b674-2b7a2c4c660a) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/102cdd55-f9c1-49a1-9562-3a67d134314c) | ![2](https://github.com/brave/brave-browser/assets/128532965/e080af00-a329-4cc2-8a14-a050743ec2ae) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/665ee638-6cdd-4c66-b949-73a9544a0c2e) | ![2](https://github.com/brave/brave-browser/assets/128532965/cfa48c3b-650d-49eb-b6e3-3a4d3bd6a4b2) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/a232f903-54c4-4a9d-a6cd-50464e6b642a) | ![2](https://github.com/brave/brave-browser/assets/128532965/3f50ceca-cde8-424f-8012-eaaa41236675) |
</details>

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.64.103 Chromium: 122.0.6261.128 (Official Build) beta (64-bit)
-- | --
Revision | 41534736ca142c5829699b512024398eaa2bbfc0
OS | Windows 10 Version 22H2 (Build 19045.4170)
```

## Cross-site cookies blocked
## Block all cookies
## Allow all cookies

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave	1.64.104 Chromium: 123.0.6312.46 (Official Build) (64-bit) 
Revision	0ca3d372cf8aab96fafdd75f5c5c8d2012bc0cc6
OS	Linux
```

### Steps:
1. installed `1.64.104`
2. launched Brave
3. loaded `https://dev-pages.brave.software/storage/ephemeral-storage.html`
4. followed directions

## Cross-site cookies blocked - `PENDING`

## Block all cookies - `PENDING`

## Allow all cookies - `PENDING`
