### ISSUE TITLE
Changing audio output on the fly

### ISSUE THREAD

**Issue by yochem** [brave/brave-browser#2617]
## Description 

When I attach an external monitor to my Macbook and there's playing sound in Brave, brave keeps the output of the sound to the internal speakers, not the monitor.

## Steps to Reproduce

   1. Play audio in Brave (e.g. on [youtube](https://youtube.com).
   2. Attach an external monitor with audio jack to macbook air's minidisplayport port. 

## Actual result:

Audio keeps playing on internal speakers

## Expected result:
Expected audio playing on external speakers, not internal.

## Reproduces how often: 

100%

## Brave version (brave://version info)

Version 0.57.18 Chromium: 71.0.3578.80 (Official Build) (64-bit)
MacOS 10.14.2 (18C54)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Not tested yet.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields?
Nope 
- Is the issue reproducible on the latest version of Chrome? 
Not tested yet.

### Additional Information

None.

**Comment by srirambv** [comment]
Do you mind checking the behaviour on Chrome? Would be helpful to analyse if its a Brave level issue or its a Chromium issue
