### ISSUE TITLE
Integrate a "I don't care about cookie option"

### ISSUE THREAD

**Issue by DavidBabel** [brave/brave-browser#2618]
The title is explicit, i talk about the chrome extension which allows that.

It will be great if finally, a browser embed this option, especially on a phone.

**Comment by tomlowenthal** [comment]
If there's already an extension to do what you want, you should certainly use that extension!

**Comment by DavidBabel** [comment]
As far as i know, extensions cannot be installed on a phone, am i wrong ?

**Comment by DavidBabel** [comment]
> Perhaps being in the US you don't see just how the EU copyright directive and GDPR have rendered the internet a crippling banner-spam filled place, as citizens within the EU have to put up with on a daily basis.

Exactly. Now cookie bannerx are far worst than ads.

**Comment by bsclifton** [comment]
@DavidBabel @aidanjt for the mobile apps, you'll want to create an issue here:
- (Android) https://github.com/brave/browser-android-tabs/issues
- (iOS) https://github.com/brave/brave-ios/issues
