### ISSUE TITLE
Update search engine defaults for BR / AR

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#26181]
## Description 
Update search engine defaults for:

- Brazil (BR)
- Argentina (AR)

Brave should be at the top of drop down list at brave://settings/search

Related: https://github.com/brave/brave-browser/issues/18331 and https://github.com/brave/brave-browser/issues/23814

### Region set to BR / AR
1. Fresh profile
2. Search onboarding should NOT be shown
3. Default search engine SHOULD be Brave
4. Visit brave://settings/searchEngines
5. Brave SHOULD be first in the `Default search engines` list

### Region set to anything else (excluding CA / DE / FR / GB / US / AT / ES / MX)
1. Fresh profile
2. Search onboarding SHOULD be shown
3. Default will NOT be Brave Search
4. Visit brave://settings/searchEngines
5. Brave SHOULD be first in the `Default search engines` list - unless you're in a region where Yandex is default (AM, AZ, BY, KG, KZ, MD, RU, TJ, TM, UZ). In that case it will be second.

### Notes for test plan
https://github.com/brave/brave-browser/issues/23814#issuecomment-1195841652

**Comment by simonhong** [comment]
Maybe we also want NTP search promotion to these new regions
https://github.com/brave/brave-variations/blob/main/seed/seed.json#L1185

**Comment by anthonypkeane** [comment]
We probably need to re-open this for Android as I'm not sure if the work is done yet. 
cc @timchilds & @deeppandya

**Comment by deeppandya** [comment]
@anthonypkeane setting brave as default should be good but we need to change the onboarding behaviour for android.

**Comment by srirambv** [comment]
@anthonypkeane the issue has an associated PR so it should not be reopened. If we need we can add an Android specific issue and mark this one as Desktop only

**Comment by kjozwiak** [comment]
The above requires `1.45.121` or higher for `1.45.x` verification 👍

**Comment by kjozwiak** [comment]
> This issue was closed incorrectly as the work on Android was not completed.
> 
> Reopening, adding the correct Android project and assigning to @deeppandya & @timchilds

This particular PR can be verified on `Android` as well but the onboarding portion will be done via https://github.com/brave/brave-browser/issues/26318 as per https://github.com/brave/brave-browser/issues/26318#issuecomment-1299587680.

@brave/qa-team when verifying the above, you can use the STR/Cases outlined via https://github.com/brave/brave-core/pull/15669#issuecomment-1299023358 & https://github.com/brave/brave-core/pull/15669#issuecomment-1299634053. However, rather than going through all the cases I did, each platform should:

* pick either `BR` or `AR` (the new ones added)
* pick one of the previous locales that have `Brave` as default (`CA` / `DE` / `FR` / `GB` / `US` / `AT` / `ES` / `MX`)
* pick a locale that doesn't have `Brave` as the default SE (example: `Japan` or `Poland`)
* pick a locale that has `Yandex` set as the default SE

**Comment by stephendonner** [comment]
Verification `IN-PROGRESS` using 



### `AR (Argentina) locale` (new addition)

#### `Case #1` - https://github.com/brave/brave-browser/issues/26182

<details>
<summary>brave://welcome</summary>

Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/26182#issue-1418874390 and ensured that the `Set default search engine screen` was removed from `brave://welcome` as per the following:

**`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------


</details>

#### `Case #2` - https://github.com/brave/brave-browser/issues/26181

<details>
<summary>Clean Profile</summary>

* ensured that `Brave` was selected as the default for both Normal/Private windows via `brave://settings/searchEngines`
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Private` windows

**`Example`** | **`Example`** | **`Example`**
---------------|-----------------|---------------


</details>

<details>
<summary>Updated Profile (Google/Brave)</summary>

* installed `1.47.20 Chromium: 107.0.5304.68`
* ensured that `Google` was the default SE selected under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Brave` was the default SE selected under `brave://settings/searchEngines` for `Private` windows
* updated to `1.47.36 Chromium: 107.0.5304.91` and ensured that `Google` is still the default SE for `Normal Windows`
  * ensured that `Google` wasn't replaced by `Brave` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Normal` windows

**`1.47.20 Chromium: 107.0.5304.68`** | **`1.47.36 Chromium: 107.0.5304.91`**
--------------------------------------------|----------------------------------------------


**`Example (Brave at top of list)`** | **`Example (Brave at top of list)`**
--------------------------------------|-----------------------------------------


</details>

<details>
<summary>Updated Profile (DDG/Startpage)</summary>

* installed `1.47.20 Chromium: 107.0.5304.68`
* ensured that `DDG` was the default SE selected under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Startpage` was the default SE selected under `brave://settings/searchEngines` for `Private` windows
* updated to `1.47.36 Chromium: 107.0.5304.91` and ensured that both SE engines were still selected as the default
  * ensured that it wasn't replaced by `Brave`
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Private` windows

**`1.47.20 Chromium: 107.0.5304.68`** | **`1.47.36 Chromium: 107.0.5304.91`**
--------------------------------------------|----------------------------------------------


**`Example (Brave at top of list)`** | **`Example (Brave at top of list)`**
--------------------------------------|-----------------------------------------


</details>

<details>
<summary>Updated Profile (Qwant/Bing)</summary>

* installed `1.47.20 Chromium: 107.0.5304.68`
* ensured that `Qwant` was the default SE selected under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Bing` was the default SE selected under `brave://settings/searchEngines` for `Private` windows
* updated to `1.47.36 Chromium: 107.0.5304.91` and ensured that both SE engines were still selected as the default
  * ensured that it wasn't replaced by `Brave`
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Private` windows

**`1.47.20 Chromium: 107.0.5304.68`** | **`1.47.36 Chromium: 107.0.5304.91`**
--------------------------------------------|----------------------------------------------


**`Example (Brave at top of list)`** | **`Example (Brave at top of list)`**
--------------------------------------|-----------------------------------------


</details>

### `DE (German) locale` (existing locale with Brave Search as default)

#### `Case #1` - https://github.com/brave/brave-browser/issues/26182

<details>
<summary>brave://welcome</summary>

Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/26182#issue-1418874390 and ensured that the `Set default search engine screen` was removed from `brave://welcome` as per the following:

**`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------


</details>

#### `Case #2` - https://github.com/brave/brave-browser/issues/26181

<details>
<summary>Clean Profile</summary>

* ensured that `Brave` was selected as the default for both Normal/Private windows via `brave://settings/searchEngines`
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Private` windows

**`Example`** | **`Example`** | **`Example`**
---------------|-----------------|---------------


</details>

<details>
<summary>Updated Profile (Brave/Brave)</summary>

* installed `1.47.20 Chromium: 107.0.5304.68`
* ensured that `Brave` was the default SE selected under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Brave` was the default SE selected under `brave://settings/searchEngines` for `Private` windows
* updated to `1.47.36 Chromium: 107.0.5304.91` and ensured that `Brave` is still the default SE for `Normal` & `PB` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Normal` windows

**`1.47.20 Chromium: 107.0.5304.68`** | **`1.47.36 Chromium: 107.0.5304.91`**
--------------------------------------------|----------------------------------------------


**`Example (Brave at top of list)`** | **`Example (Brave at top of list)`**
--------------------------------------|-----------------------------------------


</details>

<details>
<summary>Updated Profile (DDG/Startpage)</summary>

* installed `1.47.20 Chromium: 107.0.5304.68`
* ensured that `DDG` was the default SE selected under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Startpage` was the default SE selected under `brave://settings/searchEngines` for `Private` windows
* updated to `1.47.36 Chromium: 107.0.5304.91` and ensured that both SE engines were still selected as the default
  * ensured that it wasn't replaced by `Brave`
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Private` windows

**`1.47.20 Chromium: 107.0.5304.68`** | **`1.47.36 Chromium: 107.0.5304.91`**
--------------------------------------------|----------------------------------------------

**`Example (Brave at top of list)`** | **`Example (Brave at top of list)`**
--------------------------------------|-----------------------------------------


</details>

### `JP (Japan) locale` (doesn't have Brave Search as default)

#### `Case #1` - https://github.com/brave/brave-browser/issues/26182

<details>
<summary>brave://welcome</summary>

Ensured that the `Set default search engine screen` was was still present via `brave://welcome` as per the following:

**`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|-----------------|---------------|------------------


</details>

#### `Case #2` - https://github.com/brave/brave-browser/issues/26181

<details>
<summary>Clean Profile</summary>

* ensured that `Google` was selected as the default for both Normal/Private windows via `brave://settings/searchEngines`
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Private` windows

**`Example`** | **`Example`** | **`Example`**
---------------|-----------------|---------------


</details>

<details>
<summary>Updated Profile (Google/Brave)</summary>

* installed `1.47.20 Chromium: 107.0.5304.68`
* ensured that `Google` was the default SE selected under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Brave` was the default SE selected under `brave://settings/searchEngines` for `Private` windows
* updated to `1.47.36 Chromium: 107.0.5304.91` and ensured that `Google` is still the default SE for `Normal` windows
* ensured that `Brave` is still the default SE for `Private` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Normal` windows

**`1.47.20 Chromium: 107.0.5304.68`** | **`1.47.36 Chromium: 107.0.5304.91`**
--------------------------------------------|----------------------------------------------


**`Example (Brave at top of list)`** | **`Example (Brave at top of list)`**
--------------------------------------|-----------------------------------------

</details>

<details>
<summary>Updated Profile (Startpage/Bing)</summary>

* installed `1.47.20 Chromium: 107.0.5304.68`
* ensured that `Startpage` was the default SE selected under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Bing` was the default SE selected under `brave://settings/searchEngines` for `Private` windows
* updated to `1.47.36 Chromium: 107.0.5304.91` and ensured that both SE engines were still selected as the default
  * ensured that it wasn't replaced by `Brave`
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Private` windows

**`1.47.20 Chromium: 107.0.5304.68`** | **`1.47.36 Chromium: 107.0.5304.91`**
--------------------------------------------|----------------------------------------------

**`Example (Brave at top of list)`** | **`Example (Brave at top of list)`**
--------------------------------------|-----------------------------------------


</details>

### `RU (Russia) locale` (Yandex as the default SE)

#### `Case #1` - https://github.com/brave/brave-browser/issues/26182

<details>
<summary>brave://welcome</summary>

Ensured that the `Set default search engine screen` was was still present via `brave://welcome` as per the following:

**`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|-----------------|---------------|------------------


</details>

#### `Case #2` - https://github.com/brave/brave-browser/issues/26181

<details>
<summary>Clean Profile</summary>

* ensured that `Yandex` was selected as the default for both Normal/Private windows via `brave://settings/searchEngines`

**`Example`** | **`Example`** | **`Example`**
---------------|-----------------|---------------



</details>

<details>
<summary>Updated Profile (Yandex/Brave)</summary>

* installed `1.47.20 Chromium: 107.0.5304.68`
* ensured that `Yandex` was the default SE selected under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Brave` was the default SE selected under `brave://settings/searchEngines` for `Private` windows
* updated to `1.47.36 Chromium: 107.0.5304.91` and ensured that `Yandex` is still the default SE for `Normal` windows
* ensured that `Brave` is still the default SE for `Private` windows

**`1.47.20 Chromium: 107.0.5304.68`** | **`1.47.36 Chromium: 107.0.5304.91`**
--------------------------------------------|----------------------------------------------


**`Example`** | **`Example`**
---------------|---------------


</details>

<details>
<summary>Updated Profile (Google/DDG)</summary>

* installed `1.47.20 Chromium: 107.0.5304.68`
* ensured that `Google` was the default SE selected under `brave://settings/searchEngines` for `Normal` windows
* ensured that `DDG` was the default SE selected under `brave://settings/searchEngines` for `Private` windows
* updated to `1.47.36 Chromium: 107.0.5304.91` and ensured that both SE engines were still selected as the default
  * ensured that it wasn't replaced by `Brave`

**`1.47.20 Chromium: 107.0.5304.68`** | **`1.47.36 Chromium: 107.0.5304.91`**
--------------------------------------------|----------------------------------------------


**`Example`** | **`Example`**
---------------|---------------


</details>

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```
Brave | 1.45.121 Chromium: 107.0.5304.91 (Official Build) (64-bit)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | Windows 10 Version 21H2 (Build 19044.2130)

```

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.45.121 Chromium: 107.0.5304.91 (Official Build) (64-bit)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | Ubuntu 18.04 LTS




### `BR (Brazilian) locale` (new addition)

#### `Case #1` - https://github.com/brave/brave-browser/issues/26182

<details>
<summary>brave://welcome</summary>

Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/26182#issue-1418874390 and ensured that the `Set default search engine screen` was removed from `brave://welcome` as per the following:

![image](https://user-images.githubusercontent.com/34715963/201302904-d87503fa-0368-4380-8893-fafd02f590df.png)
![image](https://user-images.githubusercontent.com/34715963/201303088-01f7d8ec-354f-4818-9eb9-66d5d5909be2.png)
![image](https://user-images.githubusercontent.com/34715963/201303142-9bcea8f6-6c4f-413c-9855-c7c85a783c20.png)



</details>

#### `Case #2` - https://github.com/brave/brave-browser/issues/26181

<details>
<summary>Clean Profile</summary>

* ensured that `Brave` was selected as the default for both Normal/Private windows via `brave://settings/searchEngines`
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Private` windows

![image](https://user-images.githubusercontent.com/34715963/201303990-598f2605-83f4-45ab-ba5d-e0499e71edc0.png)
![image](https://user-images.githubusercontent.com/34715963/201304067-0f3beb06-e7b5-4cb5-b735-431e7518e60a.png)
![image](https://user-images.githubusercontent.com/34715963/201304154-b1be636b-40f2-4ca4-b39b-86fd7ee059d5.png)


</details>

<details>
<summary>Updated Profile (Google/Brave)</summary>

* installed `1.45.118`
* ensured that `Google` was the default SE selected under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Brave` was the default SE selected under `brave://settings/searchEngines` for `Private` windows
* updated to `1.45.121` and ensured that `Google` is still the default SE for `Normal Windows`
  * ensured that `Google` wasn't replaced by `Brave` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Normal` windows

![image](https://user-images.githubusercontent.com/34715963/201304293-72984265-4b98-43d2-9475-ca7492408c62.png)
![image](https://user-images.githubusercontent.com/34715963/201304414-99e031dd-b6be-4c3b-b005-36b9af258802.png)


</details>

<details>
<summary>Updated Profile (DDG/Startpage)</summary>

* installed `1.45.118`
* ensured that `DDG` was the default SE selected under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Startpage` was the default SE selected under `brave://settings/searchEngines` for `Private` windows
* updated to `1.45.121` and ensured that both SE engines were still selected as the default
  * ensured that it wasn't replaced by `Brave`
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Private` windows

![image](https://user-images.githubusercontent.com/34715963/201304556-bfa0ded3-d463-4d20-9450-7666592ea26e.png)
![image](https://user-images.githubusercontent.com/34715963/201304641-39903ba1-9b75-4487-99ed-af1dbebbaf71.png)
![image](https://user-images.githubusercontent.com/34715963/201304727-cbc38514-0746-4a56-ba4a-57b81c5d270d.png)




</details>

<details>
<summary>Updated Profile (Qwant/Bing)</summary>

* installed `1.45.118`
* ensured that `Qwant` was the default SE selected under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Bing` was the default SE selected under `brave://settings/searchEngines` for `Private` windows
* updated to `1.45.121` and ensured that both SE engines were still selected as the default
  * ensured that it wasn't replaced by `Brave`
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Private` windows


![image](https://user-images.githubusercontent.com/34715963/201304877-187c0391-545a-4997-a88d-62776ec0cc35.png)
![image](https://user-images.githubusercontent.com/34715963/201304933-e6b37421-a491-460d-a1b0-d7a07404dcb2.png)
![image](https://user-images.githubusercontent.com/34715963/201305010-7cfc9929-1389-4d5d-a297-98398dc2fefe.png)



</details>

### `en_GB locale` (existing locale with Brave Search as default)

#### `Case #1` - https://github.com/brave/brave-browser/issues/26182

<details>
<summary>brave://welcome</summary>

Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/26182#issue-1418874390 and ensured that the `Set default search engine screen` was removed from `brave://welcome` as per the following:

![image](https://user-images.githubusercontent.com/34715963/201305451-c13d7cdf-3ec6-4cae-a691-ffee76f26de1.png)
![image](https://user-images.githubusercontent.com/34715963/201305506-622539b8-fadf-4cb8-9b85-d55d31388d9e.png)
![image](https://user-images.githubusercontent.com/34715963/201305562-c29d1d37-661a-4ba7-8f6e-56534a1cc27c.png)



</details>



#### `Case #2` - https://github.com/brave/brave-browser/issues/26181

<details>
<summary>Clean Profile</summary>

* ensured that `Brave` was selected as the default for both Normal/Private windows via `brave://settings/searchEngines`
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Private` windows

![image](https://user-images.githubusercontent.com/34715963/201305660-771cbdb1-e914-4b02-9293-5a07dd38a765.png)
![image](https://user-images.githubusercontent.com/34715963/201305711-93a3741d-2a7e-4070-bce6-8f8b12cf8d1f.png)
![image](https://user-images.githubusercontent.com/34715963/201305770-f770166e-6b3c-44db-beb9-219948dc77ea.png)



</details>

<details>
<summary>Updated Profile (Brave/Brave)</summary>

* installed `1.45.118`
* ensured that `Brave` was the default SE selected under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Brave` was the default SE selected under `brave://settings/searchEngines` for `Private` windows
* updated to `1.45.121` and ensured that `Brave` is still the default SE for `Normal` & `PB` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Normal` windows

![image](https://user-images.githubusercontent.com/34715963/201306269-fe4983da-6569-4066-a7d7-151fbe2bcd9f.png)
![image](https://user-images.githubusercontent.com/34715963/201306412-bbcae9db-28d5-4eb6-9d17-f5aa46f4d3d6.png)
![image](https://user-images.githubusercontent.com/34715963/201306468-0c608941-7241-4464-bcc8-87ad64323805.png)


</details>

<details>
<summary>Updated Profile (DDG/Startpage)</summary>

* installed `1.45.118`
* ensured that `DDG` was the default SE selected under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Startpage` was the default SE selected under `brave://settings/searchEngines` for `Private` windows
* updated to `1.45.121` and ensured that both SE engines were still selected as the default
  * ensured that it wasn't replaced by `Brave`
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Private` windows

![image](https://user-images.githubusercontent.com/34715963/201306842-236b893c-0818-4bff-9f21-08334f69fd24.png)
![image](https://user-images.githubusercontent.com/34715963/201306903-a396bc62-5194-49a8-86e5-bd7f557381f1.png)
![image](https://user-images.githubusercontent.com/34715963/201306967-4e47e025-226c-4539-93dd-447b5fe44920.png)


</details>

### `PL (Poland) locale` (doesn't have Brave Search as default)

#### `Case #1` - https://github.com/brave/brave-browser/issues/26182

<details>
<summary>brave://welcome</summary>

Ensured that the `Set default search engine screen` was was still present via `brave://welcome` as per the following:

![image](https://user-images.githubusercontent.com/34715963/201307986-1fc4923d-78a1-438b-9afa-ce41ce9e35cc.png)


</details>

#### `Case #2` - https://github.com/brave/brave-browser/issues/26181

<details>
<summary>Clean Profile</summary>

* ensured that `Google` was selected as the default for both Normal/Private windows via `brave://settings/searchEngines`
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Private` windows

![image](https://user-images.githubusercontent.com/34715963/201307847-1ce6d807-7a2d-4f5b-903c-dd6d78404b36.png)
![image](https://user-images.githubusercontent.com/34715963/201308125-4619613b-1fb4-45a4-b71d-0d9b1ac85a5d.png)
![image](https://user-images.githubusercontent.com/34715963/201308196-ae1084f9-9cc1-4080-96da-4b9d8079934e.png)



</details>

<details>
<summary>Updated Profile (Google/Brave)</summary>

* installed `1.45.118`
* ensured that `Google` was the default SE selected under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Brave` was the default SE selected under `brave://settings/searchEngines` for `Private` windows
* updated to `1.45.121` and ensured that `Google` is still the default SE for `Normal` windows
* ensured that `Brave` is still the default SE for `Private` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Normal` windows

![image](https://user-images.githubusercontent.com/34715963/201308472-93f660f7-155c-4708-a5fc-00e414330c18.png)
![image](https://user-images.githubusercontent.com/34715963/201308692-d0a23695-cf79-440d-8d41-d0edd2d4762c.png)
![image](https://user-images.githubusercontent.com/34715963/201308730-bb04f11f-1541-47d3-b5a9-f08f98f8466d.png)


</details>

<details>
<summary>Updated Profile (Startpage/Bing)</summary>

* installed `1.45.118`
* ensured that `Startpage` was the default SE selected under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Bing` was the default SE selected under `brave://settings/searchEngines` for `Private` windows
* updated to `1.45.121` and ensured that both SE engines were still selected as the default
  * ensured that it wasn't replaced by `Brave`
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/searchEngines` for `Private` windows

![image](https://user-images.githubusercontent.com/34715963/201308842-aa3d546a-6b8a-4b4d-a5f3-aff969817fb3.png)
![image](https://user-images.githubusercontent.com/34715963/201308892-04915140-5ccb-4c72-b39b-a29e3d1f3c39.png)
![image](https://user-images.githubusercontent.com/34715963/201308948-53cb95b1-e3bc-43b2-a296-0b4b8667a487.png)



</details>

### `RU (Russia) locale` (Yandex as the default SE)

#### `Case #1` - https://github.com/brave/brave-browser/issues/26182

<details>
<summary>brave://welcome</summary>

Ensured that the `Set default search engine screen` was was still present via `brave://welcome` as per the following:

![image](https://user-images.githubusercontent.com/34715963/201310084-9c1ad114-dd2f-4749-9bca-7e149551507f.png)


</details>

#### `Case #2` - https://github.com/brave/brave-browser/issues/26181

<details>
<summary>Clean Profile</summary>

* ensured that `Yandex` was selected as the default for Normal windows via `brave://settings/searchEngines`
* ensured that `Brave` was selected as the default for Private windows via `brave://settings/searchEngines`

![image](https://user-images.githubusercontent.com/34715963/201310193-e9a8f3db-7a7f-43b2-825a-3976a606e26c.png)
![image](https://user-images.githubusercontent.com/34715963/201310233-c14191bf-7f2c-4539-a318-fc443217d686.png)
![image](https://user-images.githubusercontent.com/34715963/201310254-b7d098e3-f1be-4639-a820-c4eb8d4c69d1.png)



</details>

<details>
<summary>Updated Profile (Yandex/Brave)</summary>

* installed `1.45.118`
* ensured that `Yandex` was the default SE selected under `brave://settings/searchEngines` for `Normal` windows
* ensured that `Brave` was the default SE selected under `brave://settings/searchEngines` for `Private` windows
* updated to `1.45.121` and ensured that `Yandex` is still the default SE for `Normal` windows
* ensured that `Brave` is still the default SE for `Private` windows

![image](https://user-images.githubusercontent.com/34715963/201310519-73f32ebc-ee04-43cb-b35c-a821d3ff5e46.png)
![image](https://user-images.githubusercontent.com/34715963/201310546-d371c5f2-85a9-4875-bb55-4558320e9d4f.png)
![image](https://user-images.githubusercontent.com/34715963/201310568-4e5e8944-4c52-467b-be81-c12449c99f76.png)



</details>

<details>
<summary>Updated Profile (Google/DDG)</summary>

* installed `1.45.118`
* ensured that `Google` was the default SE selected under `brave://settings/searchEngines` for `Normal` windows
* ensured that `DDG` was the default SE selected under `brave://settings/searchEngines` for `Private` windows
* updated to `1.45.121` and ensured that both SE engines were still selected as the default
  * ensured that it wasn't replaced by `Brave`

![image](https://user-images.githubusercontent.com/34715963/201310672-48621a47-0d1b-47e1-a88a-fc09f0b21eb1.png)
![image](https://user-images.githubusercontent.com/34715963/201310698-08708592-269e-4d2c-90ee-2ff18ca4ce15.png)
![image](https://user-images.githubusercontent.com/34715963/201310730-ecaabc45-312b-41fe-b279-d255980bcefe.png)


</details>

**Comment by Uni-verse** [comment]
In progress on Android ARM using:

```
Brave	1.45.125 Chromium: 107.0.5304.110 (Official Build) (64-bit) 
Revision	2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}
OS	Android 12;
```
