### ISSUE TITLE
Download protection service (SafeBrowsing) is blocking a file from google.com

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#26183]
## Description 
Trying to download the Chrome enterprise templates and Brave gives an error and won't allow you (no matter what you try) to access the file. Only option is to `Discard`. Turning off Safe Browsing resolves the issue

## Steps to Reproduce

   1. Be in Brave
   2. Have Safe Browsing enabled (under brave://settings/security)
   3. Try to download https://dl.google.com/dl/edgedl/chrome/policy/policy_templates.zip
   4. Download finishes

## Actual result:
Download bar shows as dangerous and you can only click `Discard`. Clicking down chevron sends you to a help link
![image](https://user-images.githubusercontent.com/4733304/197296029-fdaa7751-c606-4bf1-8382-6545a75dd0b7.png)

## Expected result:
It should download and be accessible. Works in Chrome
![image](https://user-images.githubusercontent.com/4733304/197296229-fefd1346-4abc-4e18-9e4f-f58cc76dfa4a.png)

## Reproduces how often: 
100%

## Version/Channel Information:
- Can you reproduce this issue with the current release? YES
- Can you reproduce this issue with the beta channel?  YES
- Can you reproduce this issue with the nightly channel? YES

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NO
- Does the issue resolve itself when disabling Brave Rewards? NO
- Is the issue reproducible on the latest version of Chrome? NO

**Comment by bsclifton** [comment]
Per convo with @fmarier - call to Safe Browsing may be missing metadata

**Comment by fmarier** [comment]
After investigating this, I found that this file was blocked with the following indicators:

- UI = "Blocked - Dangerous"
- `DownloadCheckResults = POTENTIALLY_UNWANTED (5)`
- `DownloadCheckResultReason = REASON_DOWNLOAD_POTENTIALLY_UNWANTED (21)`
- `DownloadDangerType = DOWNLOAD_DANGER_TYPE_POTENTIALLY_UNWANTED (8)`

and I did notice that providing the URL of the download (i.e. by commenting out [this
line](https://github.com/brave/brave-core/blob/b528d946869409e4736f79a71895301732fb6a18/chromium_src/chrome/browser/safe_browsing/download_protection/check_client_download_request_base.cc#L14)), changed the server verdict from `POTENTIALLY_UNWANTED` to `SAFE`.

However, while the file is still the same, I can't reproduce the `POTENTIALLY_UNWANTED` verdict anymore and  so it looks there's been a server-side change. Perhaps Google has realized that this was a false positive.

**Comment by fmarier** [comment]
Seems to be happening again.

**Comment by fmarier** [comment]
The fix is now upstream: https://chromium.googlesource.com/chromium/src/+/4c22713700868309e30a6611702a83413dba428b

**Comment by stephendonner** [comment]
> The fix is now upstream: https://chromium.googlesource.com/chromium/src/+/4c22713700868309e30a6611702a83413dba428b

Do we need to file any followup issues to remove the temporary patch on our side?

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.58.80 Chromium: 116.0.5845.51 (Official Build) nightly (64-bit)
-- | --
Revision | 4408cc9795df260c5d5f033660ce757782b53b32
OS | Windows 10 Version 22H2 (Build 19045.3271)
```

**Comment by fmarier** [comment]
> Do we need to file any followup issues to remove the temporary patch on our side?

It should happen as part of a Chromium rebase since our patch won't apply anymore (already applied upstream).
