### ISSUE TITLE
remove Set default search engine screen for BR / AR

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#26182]
## Test plan
See https://github.com/brave/brave-browser/issues/23814

## Description 

in brave://welcome remove Set default search engine screen for the following locales: BR / AR

<img width="775" alt="135164087-0e746789-834d-49b8-86ca-4b19d33786db" src="https://user-images.githubusercontent.com/5951041/177653298-7ab7b542-70b3-4b6b-acb8-e71ac9d9be68.png">

## Expected Result

   1. Install Brave from the following locales BR / AR 
   2. `Set default search engine screen` should be removed from BR / AR (and previously CA / DE / FR / GB / US / AT / ES / MX). Screen should remain for all other locales.
   3. Onboarding should be four steps now instead of five.

## Brave version (brave://version info)

Target version is 1.45.x maintenance release

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

Dependency on https://github.com/brave/brave-browser/issues/26181
Previous work for removing screen in CA/DE/FR/GB/US here: https://github.com/brave/brave-browser/issues/18415
Previous work for removing screen in AT / ES / MX here: https://github.com/brave/brave-browser/issues/23908

**Comment by kjozwiak** [comment]
Believe the above is `Desktop` related and not `OS/Android`. The one for `Android` re: onboarding will be addressed via https://github.com/brave/brave-browser/issues/26318.

**Comment by kjozwiak** [comment]
The above requires `1.45.121` or higher for `1.45.x` verification 👍

**Comment by kjozwiak** [comment]
@brave/qa-team please take a look at https://github.com/brave/brave-core/pull/15669#issuecomment-1299023358 for `Test Case #1` and basically run through the same thing mentioned via https://github.com/brave/brave-browser/issues/26181#issuecomment-1304257416. Don't run through both `BR` & `AR` on one platform. Between the three platforms, both of the new locales will be covered. They've also been checked on `Nightly` as well before uplifting.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.45.121 Chromium: 107.0.5304.91 (Official build) (x86_64)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
ОS | macOS Version 11.7.1 (Build 20G918)

Verification notes can be found in https://github.com/brave/brave-browser/issues/26181#issuecomment-1306306949.
