### ISSUE TITLE
Tab unresponsive when closing it on Mac M1

### ISSUE THREAD

**Issue by felladrin** [brave/brave-browser#26185]
## Description 

When closing a tab with https://www.jetbrains.com/intellij-repository/snapshots loaded, Brave browser gets unresponsive for several seconds before finally closing it.

I suspect it's due to the number of HTML elements on that page. And I think it's happening only on arm64 build.

## Steps to Reproduce

   1. Open Brave Browser
   2. Access https://www.jetbrains.com/intellij-repository/snapshots
   3. Close the tab and notice the browser getting unresponsive

## Actual result:

The browser gets unresponsive for several seconds before finally closing the tab.
Meanwhile, the Activity Manager shows the browser using a full CPU core:
<img width="366" alt="image" src="https://user-images.githubusercontent.com/418083/197354219-60e95d22-963e-4595-b0d1-8f5e03ef1d7b.png">

## Expected result:
The tab should close instantaneously, as other tabs.

## Reproduces how often: 

Every time I access that page and try to close its tab.

## Brave version (brave://version info)

Brave | 1.44.112 Chromium: 106.0.5249.119 (Official Build) (arm64)
Revision | 9f2101830b56fd2ea1408287f6c74e253ebcb7c6-refs/branch-heads/5249@{#797}
OS | macOS Version 12.6 (Build 21G115)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes.
- Can you reproduce this issue with the beta channel? Didn't test.
- Can you reproduce this issue with the nightly channel? Didn't test.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes.
- Does the issue resolve itself when disabling Brave Rewards? Yes
- Is the issue reproducible on the latest version of Chrome? In Chrome it takes about 10 seconds to close that page, but it in Brave it can take up to one minute to close it. Other browsers don't suffer from this issue.

## Miscellaneous Information:

This issue didn't happen on Brave running on Macbook with Intel Processor.
I've also disabled all browser extensions and confirmed it's not related to any of them.

**Comment by sadikyalcin** [comment]
I just tried on an M1 and the tab closes instantly without any issues. Same brave version but I'm on macOS `12.5.1`.

**Comment by felladrin** [comment]
I've updated the OS today and rechecked it.
It's not reproduced anymore on _Brave v1.46.144_ running on _macOS Version 13.1 (Build 22C65)_.

**Comment by bsclifton** [comment]
@felladrin thanks for the follow up 😄
