### ISSUE TITLE
Brave News v2 migration follows sources disabled in v1

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#26184]
## Description 

Brave News v2 migration follows sources disabled in v1.

Found while testing https://github.com/brave/brave-browser/issues/25924.

## Steps to Reproduce

1. installed `1.46.73`
2. launched Brave
3. opened a new-tab page
4. scrolled down
5. clicked on `Show Brave News`
6. clicked on `Customize`
7. removed the following:
- all `Crypto` sources
- all `Fashion` sources
- all `Sports` sources
11. opened `brave://flags`
12. set `brave://flags/#brave-news-v2` to `Enabled`
13. clicked on `Relaunch`
14. opened a new-tab page
15. clicked on `Customize`

## Actual result:

Following all the sources I unfollowed (toggled off from defaults) in `v1`

`v1` example | example | example |  `v2`
-----|-----|-----|-----
<img width="1312" alt="Screen Shot 2022-10-21 at 3 41 42 PM" src="https://user-images.githubusercontent.com/387249/197303848-27fd60e3-24b6-44be-87d7-a07492ce868f.png"> | <img width="1312" alt="Screen Shot 2022-10-21 at 3 42 56 PM" src="https://user-images.githubusercontent.com/387249/197303849-a6c68caf-68c2-45d2-b884-48d08ff5356f.png"> | <img width="1312" alt="Screen Shot 2022-10-21 at 3 43 10 PM" src="https://user-images.githubusercontent.com/387249/197303850-a69c7beb-3efd-408f-8ba5-4b66868bb14e.png"> | <img width="1278" alt="Screen Shot 2022-10-21 at 3 58 09 PM" src="https://user-images.githubusercontent.com/387249/197302835-e785b501-4e78-47c6-86db-8b6dd0f3e317.png">

![sometimes-they-come-back-again](https://user-images.githubusercontent.com/387249/197302978-e8cad820-d95c-47b8-9ab2-7373dda3e69d.gif)

## Expected result:

No additional sources, especially not of those I've explictly disabled/unfollowed

## Reproduces how often: 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @fallaciousreasoning @rebron @mattmcalister @brave/qa-team

**Comment by kjozwiak** [comment]
The above requires `1.46.80` or higher for `1.46.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using the original steps to reproduce, with 

Brave | 1.46.80 Chromium: 107.0.5304.68 (Official Build) beta (x86_64)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | macOS Version 11.7.1 (Build 20G918)

#### Confirmed I wasn't subscribed to any of the `Crypto`, `Fashion`, or `Sports` feed sources

<img width="1077" alt="Screen Shot 2022-10-26 at 5 45 45 PM" src="https://user-images.githubusercontent.com/387249/198165181-3874f023-4218-4c9f-9f86-f1ad80fd9a5d.png">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.46.83 Chromium: 107.0.5304.68 (Official Build) beta (64-bit)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | Windows 11 Version 21H2 (Build 22000.1098)
```
Verified the issue with original STR https://github.com/brave/brave-browser/issues/26184#issue-1418941344

Steps: 

1. installed `1.46.83`
2. launched Brave
3. opened a new-tab page
4. scrolled down
5. clicked on `Show Brave News`
6. clicked on `Customize`
7. click `Brave News` 
8. disabled the following:
    - all `Food` sources
    - all `Fun` sources
9. opened `brave://flags`
10. set `brave://flags/#brave-news-v2` to `Enabled`
11. clicked on `Relaunch`
12. opened a new-tab page
13. clicked on `Customize`

#### Confirmed `Food`, `Fun` sources weren't subscribed/followed.

step 8-food|step 8-fund|step 11|result
-----|-----|----|----
<img width="462" alt="image" src="https://user-images.githubusercontent.com/98358127/198737638-75eaf82e-d463-4075-9a7f-6aca4418e1ad.png">|<img width="465" alt="image" src="https://user-images.githubusercontent.com/98358127/198737712-c5fff210-3fa3-4201-802f-d4550f2048a9.png">|<img width="464" alt="image" src="https://user-images.githubusercontent.com/98358127/198736839-588665a4-ad2e-4f04-8a79-d9e5d1d76901.png">|<img width="465" alt="image" src="https://user-images.githubusercontent.com/98358127/198739013-f43d4707-5eb7-48f8-8d93-c7e5231a05e4.png">

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.46.117 Chromium: 107.0.5304.110 (Official Build) beta (64-bit)
-- | --
Revision | 2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}
OS | Ubuntu 18.04 LTS


Verified test plan from the description

<details>

1.45.x
crypto
![image](https://user-images.githubusercontent.com/34715963/202967881-c32e8880-268d-4de4-9390-878c48d0213f.png)

Fashion 
![image](https://user-images.githubusercontent.com/34715963/202967962-2dc1d4ce-a55c-4af9-acb5-2fcb3559648a.png)

Sports 
![image](https://user-images.githubusercontent.com/34715963/202968053-d8106f2c-ad5c-4d04-b9ca-5478b385537b.png)

1.46.x
![image](https://user-images.githubusercontent.com/34715963/202968605-f89b53f8-c114-4b78-8513-2b2f9cab5cb2.png)





</details>
