### ISSUE TITLE
ARM64 Linux Drop GLIBC 2.29+ requirement

### ISSUE THREAD

**Issue by theofficialgman** [brave/brave-browser#26189]
## Description 
The new beta version of brave browser (https://github.com/brave/brave-core/pull/15349 by @mherrmann) requires much higher library versions than the amd64 versions

amd64:
```
Depends: ca-certificates, fonts-liberation, libasound2 (>= 1.0.17), libatk-bridge2.0-0 (>= 2.5.3), libatk1.0-0 (>= 2.2.0), libatspi2.0-0 (>= 2.9.90), libc6 (>= 2.17), libcairo2 (>= 1.6.0), libcups2 (>= 1.6.0), libcurl3-gnutls | libcurl3-nss | libcurl4 | libcurl3, libdbus-1-3 (>= 1.5.12), libdrm2 (>= 2.4.60), libexpat1 (>= 2.0.1), libgbm1 (>= 8.1~0), libglib2.0-0 (>= 2.39.4), libgtk-3-0 (>= 3.9.10) | libgtk-4-1, libnspr4 (>= 2:4.9-2~), libnss3 (>= 2:3.26), libpango-1.0-0 (>= 1.14.0), libwayland-client0 (>= 1.0.2), libx11-6 (>= 2:1.4.99.1), libxcb1 (>= 1.9.2), libxcomposite1 (>= 1:0.4.4-1), libxdamage1 (>= 1:1.1), libxext6, libxfixes3, libxkbcommon0 (>= 0.4.1), libxrandr2, wget, xdg-utils (>= 1.0.2)
Recommends: libu2f-udev, libvulkan1
```
in particular `libc6 (>= 2.17)`

arm64:
```
Pre-Depends: dpkg (>= 1.14.0)
Depends: ca-certificates, fonts-liberation, libasound2 (>= 1.0.17), libatk-bridge2.0-0 (>= 2.5.3), libatk1.0-0 (>= 2.2.0), libatspi2.0-0 (>= 2.9.90), libc6 (>= 2.29), libcairo2 (>= 1.6.0), libcups2 (>= 1.6.0), libcurl3-gnutls | libcurl3-nss | libcurl4 | libcurl3, libdbus-1-3 (>= 1.0.2), libdrm2 (>= 2.4.60), libexpat1 (>= 2.0.1), libgbm1 (>= 8.1~0), libglib2.0-0 (>= 2.39.4), libgtk-3-0 (>= 3.9.10) | libgtk-4-1, libnspr4 (>= 2:4.9-2~), libnss3 (>= 2:3.26), libpango-1.0-0 (>= 1.14.0), libwayland-client0 (>= 1.0.2), libx11-6 (>= 2:1.4.99.1), libxcb1 (>= 1.9.2), libxcomposite1 (>= 1:0.4.4-1), libxdamage1 (>= 1:1.1), libxext6, libxfixes3, libxkbcommon0 (>= 0.4.1), libxrandr2, wget, xdg-utils (>= 1.0.2)
Recommends: libu2f-udev, libvulkan1
```
in particular `libc6 (>= 2.29)`

I have not researched in detail your build process but I assume you are probably using the chromium sysroots to build this on and utilizing their re-version glibc scripts to drop the minimum requirements on x86_64. You may need to make a minor edit to the re-version script as it was previously (and might still be) disabled on ARM64 linux due to an issue that google was having with re-versioning for ARM64 chromeOS.

I suggest starting with reading my issue at electron for a more detailed dive: https://github.com/electron/electron/issues/34399

the problematic chromium commit that I referenced: https://chromium.googlesource.com/chromium/src/+/f6901be733e76832721ad7fb8d4d51715df77095

https://bugs.chromium.org/p/chromium/issues/detail?id=1309965#c5

**Comment by theofficialgman** [comment]
tagging @mherrmann

**Comment by theofficialgman** [comment]
update on this. looks like chromium has bumped the glibc reversion script to max 2.26 glibc https://chromium-review.googlesource.com/c/chromium/src/+/3938615

so no more more debian 9 for all platforms going forward @mherrmann @martinbutt

**Comment by theofficialgman** [comment]
unfortunatly, arm64 symbol re-versioning is still disabled for some reason

https://source.chromium.org/chromium/chromium/src/+/main:build/linux/sysroot_scripts/sysroot-creator.sh;l=395-402

**Comment by theofficialgman** [comment]
After almost a year of the reversion script being disabled on arm6r Linux, it has finally been re-enabled https://chromium-review.googlesource.com/c/chromium/src/+/4021416

This is in chromium main and will make it's way to release builds in the future.

**Comment by theofficialgman** [comment]
the patch has landed in chromium 111

**Comment by mihaiplesa** [comment]
Thanks for all the follow-ups @theofficialgman!

We'll be on 111 soon- https://github.com/brave/brave-browser/wiki/Brave-Release-Schedule

**Comment by theofficialgman** [comment]
> We'll be on 111 soon- https://github.com/brave/brave-browser/wiki/Brave-Release-Schedule

I appreciate the ping, but all that tells me is that you were supposed to be on 111 a week and a half ago

https://github.com/brave/brave-browser/wiki/Brave-Release-Schedule#nightly-channel-migration-dates
```
Nightly channel migration dates:
Version | Target Chromium | Migration Date
1.49.x | 111 | January 4, 2023
```

**Comment by mihaiplesa** [comment]
@theofficialgman that was for nightly channel, next week we'll be on 111 on all channels which is what matters here.

**Comment by mihaiplesa** [comment]
This is now done.

**Comment by theofficialgman** [comment]
1.49.X is still not marked as released yet (still pre-release)

is the relase date (supposed to be today) getting pushed back again?

**Comment by mihaiplesa** [comment]
@theofficialgman done https://github.com/brave/brave-browser/releases/tag/v1.49.120
