### ISSUE TITLE
Poor performance on M1 with CSS blur

### ISSUE THREAD

**Issue by sadikyalcin** [brave/brave-browser#26186]
## Description 

CSS blur causes very poor performance on M1 chips - completely lagging the browser. Pretty much unusable. I've tested the same brave version on an M1 chip and an intel chip. Intel is perfectly fine. Safari is perfectly fine too on both chips so it isn't a chip issue but most likely to be chromium.

## Steps to Reproduce

   1. Add `backdrop-filter: blur(10px);` or `filter: blur(10px);` on any <html> element

## Actual result:
Browser becoming very laggy and unresponsive. Below is a demo of brave.com

https://user-images.githubusercontent.com/8109619/197367970-056e51a0-0525-48d2-a627-d8c4790ce16a.mp4

## Expected result:
Browser should perform normally.

## Reproduces how often: 
Constantly if blur is on a visible element.

## Brave version (brave://version info)
Brave: 1.44.112 Chromium: 106.0.5249.119 (Official Build) (arm64)
Revision: 9f2101830b56fd2ea1408287f6c74e253ebcb7c6-refs/branch-heads/5249@{#797}
OS: macOS Version 12.5.1 (Build 21G83)

## Version/Channel Information:
N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
No

- Does the issue resolve itself when disabling Brave Rewards?
No

- Is the issue reproducible on the latest version of Chrome? 
N/A

## Miscellaneous Information:
N/A

**Comment by mjherich** [comment]
@sadikyalcin I was experiencing the same issue. What fixed it for me was enabling Hardware Acceleration, not sure why I had disabled it in the first place.

<img width="738" alt="image" src="https://user-images.githubusercontent.com/8888824/215874710-d9c7e9c5-a4b9-459a-8eae-0f80e170ffb3.png">

**Comment by sadikyalcin** [comment]
> Hardware Acceleration

You are absolutely correct. No idea why I had that turned off.

**Comment by sadikyalcin** [comment]
> @sadikyalcin I was experiencing the same issue. What fixed it for me was enabling Hardware Acceleration, not sure why I had disabled it in the first place.
> 
> <img alt="image" width="738" src="https://user-images.githubusercontent.com/8888824/215874710-d9c7e9c5-a4b9-459a-8eae-0f80e170ffb3.png">
