### ISSUE TITLE
Sidebar's `On mouseover` option doesn't work with right side sidebar

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#26198]
## Steps to Reproduce

   1. Set sidebar on right
   2. Set On mousever as a sidebar show option
   3. Move mouse to the right side of brower window

## Actual result:

Sidebar is not shown

## Expected result:
it should be shown

## Reproduces how often: 

Easy

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.46.81` or higher for `1.46.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (x86_64)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | macOS Version 11.7.1 (Build 20G918)

### Steps:
1. installed `1.46.81`
2. launched Brave
3. opened `brave://settings/appearance`
4. set `Show Sidebar` to `On mouseover`
5. set `Side panel` to `Show on right`
6. hovered over the right side of the browser window
7. move the pointer away from the right side

#### Confirmed the sidebar appeared only on mouseover on the right, and disappeared on mouse-away

`brave://settings/appearance` | `On mouseover`
-------------------------------|----------------
<img width="1312" alt="Screen Shot 2022-10-27 at 2 53 09 PM" src="https://user-images.githubusercontent.com/387249/198405728-7af33755-b1dd-4f45-a1db-e48a8eb09168.png"> | <img width="1312" alt="Screen Shot 2022-10-27 at 2 53 22 PM" src="https://user-images.githubusercontent.com/387249/198405737-96f8c89d-3950-4ffc-8756-302887d9cf2d.png">
