### ISSUE TITLE
In the Brave News V2 UI you can't unfollow direct sources.

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#26196]
1. Enable Brave News V2
2. Follow a direct source (I like https://reactjs.org/)
3. Try and unfollow the source

Expected
The source is unfollow

Actual
Nothing happens

### Detail
I think this is being caused because we treat DIRECT sources differently to COMBINED sources, so setting a DIRECT source to NOT_MODIFIED is like leaving it as enabled. To fix, we should set the direct source to be DISABLED

**Comment by kjozwiak** [comment]
The above requires `1.46.81` or higher for `1.46.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (x86_64)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | macOS Version 11.7.1 (Build 20G918)

### Steps:
1. installed `1.46.81`
2. launched Brave
3. opened a new-tab page
4. scrolled down
5. clicked on `Show Brave News`
6. clicked on `Customize`
7. entered `https://planet.mozilla.org/atom.xml` and clicked `Add source`
8. opened `brave://flags`
9. set `brave://flags/#brave-news-v2` to `Enabled`
10. clicked `Relaunch`
11. clicked `Customize` on a new-tab page
12. confirmed `Planet Mozilla` was shown under `Following`
13. clicked on `Unfollow` to the right
14. confirmed I was no longer subscribed to `Planet Mozilla`

Subscribed (`Following`) | Unsubscribed (`Unfollowed`)
--------------------------|-----------------------------
<img width="1312" alt="Screen Shot 2022-10-27 at 3 03 32 PM" src="https://user-images.githubusercontent.com/387249/198406907-ecad630d-18f3-4ffa-82be-b4d8e611a844.png"> | <img width="1312" alt="Screen Shot 2022-10-27 at 3 03 41 PM" src="https://user-images.githubusercontent.com/387249/198406911-8c0aa274-6004-461c-a51c-bf678651944a.png">
