### ISSUE TITLE
adddevtoolsextensions method is not available after app Ready

### ISSUE THREAD

**Issue by akshay24495** [brave/brave-browser#2619]
electron.BrowserWindow.addDevToolsExtensions method is not available after app.on('ready')

**Comment by akshay24495** [comment]
@bsclifton

**Comment by srirambv** [comment]
@akshay24495  Please add more info to your issue. Use the template to fill out details so that there is as much information as possible. Template clearly states one liners will be closed for lack of information. Please add sufficient infor and reopen the issue

**Comment by bsclifton** [comment]
@akshay24495 this version of Brave is not based on Electron. You may be having a question about https://github.com/brave/browser-laptop which is basically deprecated at this point
