### ISSUE TITLE
Disable Manifest V2 deprecation warning message

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#26207]
The following warning appears when loading an unpacked extension. Brave will _not_ be removing Manifest V2 support in 2023, so this warning should be removed.

![image](https://user-images.githubusercontent.com/22821309/197570708-9e224433-b284-4024-a29c-a86fe8c9dd6c.png)

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.47.120 Chromium: 108.0.5359.99 (Official Build) dev (x86_64)
-- | --
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | macOS Version 13.1 (Build 22C65)

### Steps:
1. installed `1.47.120`
2. launched Brave
3. downloaded a `chromium.zip` file from `https://github.com/gorhill/uBlock/releases`
4. unzipped the directory
5. opened `brave://extensions`
6. toggled `Developer` mode to `On`
7. clicked on `Load unpacked`
8. browsed to the top-level of the unzipped folder, and clicked `Select` / `OK`
9. confirmed `brave://extensions/?id=annlddlhmngolbgkifidmdhblaglfnec` loaded without errors, warnings, or issues

example | example | example | example | example
---------|----------|---------|----------|---------
<img width="1107" alt="Screenshot 2022-12-08 at 9 57 35 PM" src="https://user-images.githubusercontent.com/387249/206636620-b28d0580-dad6-4c0e-b354-f3dcf70ad2e5.png"> | <img width="1107" alt="Screenshot 2022-12-08 at 9 57 39 PM" src="https://user-images.githubusercontent.com/387249/206636624-a3c57140-f14a-4968-8112-9435ff93c6fb.png"> | <img width="1107" alt="Screenshot 2022-12-08 at 9 57 48 PM" src="https://user-images.githubusercontent.com/387249/206636626-58b8c024-1411-4b24-bf90-bc131833274c.png">. | <img width="1107" alt="Screenshot 2022-12-08 at 10 02 09 PM" src="https://user-images.githubusercontent.com/387249/206636629-1670efa9-faea-456e-8e89-b4ebc961fccc.png"> | <img width="1366" alt="Screenshot 2022-12-08 at 10 02 43 PM" src="https://user-images.githubusercontent.com/387249/206636631-db26ed10-219b-490e-ae12-ba15155830ba.png">

**Comment by kjozwiak** [comment]
The above requires `1.46.142` or higher for `1.46.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.46.143 Chromium: 108.0.5359.99 (Official Build) (x86_64)
-- | --
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | macOS Version 11.7.1 (Build 20G918)

### Steps:

1. installed `1.46.143`
2. launched Brave
3. downloaded `https://github.com/gorhill/uBlock/releases/download/1.45.2/uBlock0_1.45.2.chromium.zip` from `https://github.com/gorhill/uBlock/releases`
4. unzipped the directory
5. opened `brave://extensions`
6. toggled `Developer mode` to `On`
7. clicked on `Load unpacked`
8. browsed to the top-level of the unzipped folder, and clicked `Select`
9. confirmed `brave://extensions/?id=annlddlhmngolbgkifidmdhblaglfnec` loaded without errors, warnings, or issues

example | example | example | example | example
---------|----------|---------|----------|---------
<img width="1312" alt="Screen Shot 2022-12-13 at 9 47 41 AM" src="https://user-images.githubusercontent.com/387249/207407880-15e3839d-5a2f-46d8-96a4-aa63ce7b5908.png"> | <img width="1312" alt="Screen Shot 2022-12-13 at 9 47 45 AM" src="https://user-images.githubusercontent.com/387249/207407893-13a236e1-173f-49fa-90dd-b1a1a7f573ab.png"> | <img width="1312" alt="Screen Shot 2022-12-13 at 9 48 00 AM" src="https://user-images.githubusercontent.com/387249/207407898-f6b5ffee-0316-4a4c-a34f-03e3f5887516.png"> | <img width="1312" alt="Screen Shot 2022-12-13 at 9 48 05 AM" src="https://user-images.githubusercontent.com/387249/207407901-771df58c-46ee-47cc-8c5f-22c5540e07de.png"> | <img width="1312" alt="Screen Shot 2022-12-13 at 9 49 40 AM" src="https://user-images.githubusercontent.com/387249/207407907-cfffd88a-3fb8-49c1-bf74-a5656948fe00.png">
