### ISSUE TITLE
Thumbs down should dislike a Brave ad

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#26202]
## Description 

Thumbs down should dislike a Brave ad

## Steps to Reproduce

   1. View ad
   2. Navigate to brave://rewards
   3. Navigate to 30-day ads history
   4. Click thumbs down

## Actual result:

Thumbs down likes an ad

## Expected result:
Thumbs down should dislike a Brave ad

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by kjozwiak** [comment]
The above requires `1.45.113` or higher for `1.45.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```
Brave | 1.45.113 Chromium: 107.0.5304.62 (Official Build) (64-bit)
-- | --
Revision | 1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942}
OS | Windows 10 Version 21H2 (Build 19044.2130)

```
