### ISSUE TITLE
Feature Request: Arm64 build for linux mobile devices

### ISSUE THREAD

**Issue by tathastu871** [brave/brave-browser#26201]
## Description 

An arm64 linux build so we can use brave from within proot distro or on linux phones
## Steps to Reproduce

   1. 
   2. 
   3. 

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by mihaiplesa** [comment]
@tathastu871 we already have Linux arm64 in nightly, please see the files in https://github.com/brave/brave-browser/releases/tag/v1.47.20

**Comment by mihaiplesa** [comment]
Resolved by https://github.com/brave/brave-browser/issues/11836

**Comment by tathastu871** [comment]
Does it work on ubuntu proot arm64 on termux. even if its not functional, just wanting a way to export bookmarks
