### ISSUE TITLE
`Sidebar` not visible on `On mouseoever` show mode

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#26208]
## Steps to Reproduce

   1. Install  1.46.73
   2. Launch Brave
   3. click `hamburger menu`-->`Show Sidebar`-->`On mouseover`
   4. open `brave://settings/appearance`
   5. select `Show on right` radio button on the `Side panel`
   6. hover on the right side to display `Sidebar`

## Actual result:

`Sidebar` is not shown when hovered over on the right. However, it displayed when hovered on the left.

https://user-images.githubusercontent.com/98358127/197592569-18053d93-99bf-4668-a48a-92342b6258b8.mp4

## Expected result:
`Sidebar` should be displayed on the right when hovered over

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.46.73 Chromium: 107.0.5304.62 (Official Build) beta (64-bit)
-- | --
Revision | 1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942}
OS | Windows 11 Version 21H2 (Build 22000.1098)
```
## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@rebron @simonhong

**Comment by simonhong** [comment]
This is already fixed via https://github.com/brave/brave-browser/issues/26198.
Closed as duplicated.
