### ISSUE TITLE
Add missing stats pings to desktop arm64 platforms

### ISSUE THREAD

**Issue by mihaiplesa** [brave/brave-browser#26200]
For https://github.com/brave/brave-browser/issues/6319
For https://github.com/brave/brave-browser/issues/11836

**Comment by LaurenWags** [comment]
@mihaiplesa since this one is labelled `QA/Yes` please provide a manual test plan, thanks!

cc @kjozwiak @rebron

**Comment by mihaiplesa** [comment]
@LaurenWags have just changed to `QA/No` since I re-tested now and it works.
