### ISSUE TITLE
Show dialog for blocking cookie consent banners

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#26203]
## Description 

Show dialog for blocking cookie consent banners. 
Follow-up to https://github.com/brave/brave-browser/issues/10433
Managed by BraveAdblockCookieListOptInStudy:Enabled, griffin variation study.

## Expected result:
Use 1.45.111 and higher. For new users, users will see the dialog on second launch of Brave. For existing users, they will see the dialog upon upgrade to 1.45.x

## Brave version (brave://version info)

1.45.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by LaurenWags** [comment]
Changing to `QA/No` as this was verified by @kjozwiak extensively when checking griffin study.

**Comment by LaurenWags** [comment]
closed per discussion with @kjozwiak @rebron

**Comment by StrangePeanut** [comment]
Just upgraded `Version 1.45.113 Chromium: 107.0.5304.62 (Official Build) (64-bit)` and not seeing any dialogue. There also doesn't seem to be any option for it in the settings. How to enable this feature?

**Comment by StrangePeanut** [comment]
Found **Easylist-Cookie List - Filter Obtrusive Cookie Notices** on `brave://settings/shields/filters` but unsure if this is the same thing?

**Comment by LaurenWags** [comment]
Hi @StrangePeanut,

This dialog has a phased release, so it's being rolled out to all users over the next week or so via our variations service, [Griffin](https://github.com/brave/brave-browser/wiki/Brave-Variations-(Griffin)). 

If you're keen to try it right away, yes, you can enable "Easylist-Cookie List - Filter Obtrusive Cookie Notices" under `brave://settings/shields/filters` now. The dialog just enables this filter list for you if you opt-in. I believe if you enable this filter manually you won't get the dialog asking to enable when it is rolled out - so you should be good right away. 

If you'd rather wait, it should only be about a week or so until this feature is rolled out 100%, but you could get it sooner. See the Griffin link above for more information.

Thanks for asking about this!

cc @rebron @kjozwiak for any information I might have missed/additional clarifications
