### ISSUE TITLE
Decouple Brave rewards p3a from ads

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#26211]

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.47.101 Chromium: 108.0.5359.48 (Official Build) beta (64-bit)
-- | --
Revision | 18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}
OS | Ubuntu 18.04 LTS

### ads enabled
<details>


</details>


### ntp si
<details>


</details>

### notification ad

<details>


</details>


### brave news inline ad

<details>


</details>
