### ISSUE TITLE
`Shields` button text isn't translated in German

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#26216]
## Description 

`Shields` button text isn't translated in German

Found while testing https://github.com/brave/brave-browser/issues/22550

## Steps to Reproduce

   1. install `1.47.14`
   2. launched Brave (in English)
   3. loaded `cnn.com`
   4. set `German` as the primary language, via `Apple` -> `System Preferences` -> `Language & Region
   6. clicked on the `Shields` icon in the URL bar
   7. expanded the dialog
   8. clicked on the `Blocked-cookies` count
   9. looked at the translated string for Shields

## Actual result:

<img width="1680" alt="Bildschirmfoto 2022-10-24 um 2 15 19 PM" src="https://user-images.githubusercontent.com/387249/197631990-058d9834-5569-4220-a9a4-c642a38a2d9c.png">

## Expected result:

`Shields` should be translated into German

## Reproduces how often: 

Brave | 1.47.14 Chromium: 107.0.5304.62 (Official Build) nightly (x86_64)
-- | --
Revision | 1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942}
OS | macOS Version 11.7 (Build 20G817)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @GeetaSarvadnya @rebron @mkarolin

**Comment by rebron** [comment]
To double check that this will get fixed in next Transifex request.

**Comment by mkarolin** [comment]
Fixed via https://github.com/brave/brave-core/pull/16100

**Comment by kjozwiak** [comment]
The above requires `1.46.130` or higher for `1.46.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```

Brave | 1.46.130 Chromium: 108.0.5359.62 (Offizieller Build) (64-Bit)
-- | --
Überarbeitung | 041930a89a990cfab0315a2d9f20d6429a4a67cf-refs/branch-heads/5359@{#938}
Betriebssystem | Windows 10 Version 21H2 (Build 19044.2251)

```
Ensured that `Shields` text in the shield panel is translated to German locale
![image](https://user-images.githubusercontent.com/38657976/204594034-de016095-aeea-43a3-b2bd-658cd21c9364.png)
