### ISSUE TITLE
Clicking done doesn't route back to Market Tab

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#26210]
## Description 

When click on `Buy` or `Deposit` from the `Market` tab, after clicking done on the `Fund Wallet`/`Deposit Funds` pages, it routes to the `Portfolio` tab, it should route back to the `Market` tab

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.47.126 Chromium: 108.0.5359.99 (Official Build) beta (64-bit)
-- | --
Revision | `410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}`
OS | Linux

- Verified steps from [brave/brave-core#15632](https://github.com/brave/brave-core/pull/15632)
- Verified clicking on Done routes back to Market tab for both Buy and Deposit options from market tab
- Encountered [https://github.com/brave/brave-browser/issues/26408](https://github.com/brave/brave-browser/issues/26408)

---------------------

Verification passed on 

Brave | 1.47.126 Chromium: 108.0.5359.99 (Official Build) beta (64-bit)
-- | --
Revision | `410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#15632](https://github.com/brave/brave-core/pull/15632)
- Verified clicking on Done routes back to Market tab for both Buy and Deposit options from market tab

https://user-images.githubusercontent.com/17010094/207533344-0ceb4879-f60b-4baa-9708-e99322dbccde.mp4


---------------------

Verification passed on 

Brave | 1.47.126 Chromium: 108.0.5359.99 (Official Build) beta (arm64)
-- | --
Revision | `410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#15632](https://github.com/brave/brave-core/pull/15632)
- Verified clicking on Done routes back to Market tab for both Buy and Deposit options from market tab

https://user-images.githubusercontent.com/17010094/207533508-755b3bff-da95-4c09-9428-e8b2c7e69549.mov
