### ISSUE TITLE
Add Buy and Deposit buttons to the asset details screen

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#26213]
## Description 

We need to add `Buy` and `Deposit` buttons to the `Asset Details` screen.
Only show the buttons if they are supported for the asset.

![Screen Shot 2022-10-24 at 2 15 37 PM](https://user-images.githubusercontent.com/40611140/197607301-ab711689-039e-4049-bc46-8257072d72ac.png)

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.46.129 Chromium: 108.0.5359.48 (Official Build) (64-bit)
-- | --
Revision | `18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}`
OS | Linux

- Verified steps from [brave/brave-core#15641](https://github.com/brave/brave-core/pull/15641)
- Verified Buy/Deposit buttons on asset details screen is shown
- Verified clicking Buy from asset details screen loads `Fund Wallet` page
- Verified clicking Deposit from asset details screen loads `Deposit Funds` page

https://user-images.githubusercontent.com/17010094/204324153-9822973b-b5ae-4cb1-b789-c1cd4d56cf72.mp4


---------------------

Verification passed on 

Brave | 1.46.129 Chromium: 108.0.5359.48 (Official Build) (64-bit)
-- | --
Revision | `18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#15641](https://github.com/brave/brave-core/pull/15641)
- Verified Buy/Deposit buttons on asset details screen is shown
- Verified clicking Buy from asset details screen loads `Fund Wallet` page
- Verified clicking Deposit from asset details screen loads `Deposit Funds` page

https://user-images.githubusercontent.com/17010094/204324416-75019e65-f9e7-4c49-801a-233930c33f43.mp4


---------------------

Verification passed on 

Brave | 1.46.129 Chromium: 108.0.5359.48 (Official Build) (arm64)
-- | --
Revision | `18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#15641](https://github.com/brave/brave-core/pull/15641)
- Verified Buy/Deposit buttons on asset details screen is shown
- Verified clicking Buy from asset details screen loads `Fund Wallet` page
- Verified clicking Deposit from asset details screen loads `Deposit Funds` page

https://user-images.githubusercontent.com/17010094/204324723-6cc5b9ce-c4be-4a2e-bf46-74a228c7ba8e.mov
