### ISSUE TITLE
`Crypto` should be lowercase on Gemini and Binance widget previews

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#26223]
## Description 

`Crypto` should be lowercase on Gemini and Binance widget previews

## Steps to Reproduce

   1. install `1.47.14`
   2. launch Brave
   3. open a new-tab page
   4. click on `Edit Cards`
   5. look at the capitalization of `Crypto` for `Gemini` and `Binance` widget previews/summaries

## Actual result:

`Trade Crypto on...` (upper-cased)

<img width="1038" alt="Screen Shot 2022-10-24 at 3 58 57 PM" src="https://user-images.githubusercontent.com/387249/197645729-f346691a-64de-4a97-a59d-0b1dc3db2fc5.png">

## Expected result:

`Gemini`
`Trade crypto on Gemini directly in your browser.`

`Binance`
`Trade crypto on Binance directly in your browser.`

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.47.14 Chromium: 107.0.5304.62 (Official Build) nightly (x86_64)
-- | --
Revision | 1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942}
OS | macOS Version 11.7 (Build 20G817)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

/cc @jamesmudgett @srirambv @rebron @rmcfadden3

**Comment by NaaeemMalik** [comment]
Can I be assigned to it?

**Comment by yeshwantthota** [comment]
@NaaeemMalik are u working on the issue?

**Comment by NaaeemMalik** [comment]
It's not been assigned to me so not yet

**Comment by NaaeemMalik** [comment]
@yeshwantthota should I be working on it?

**Comment by yeshwantthota** [comment]
@NaaeemMalik if u want, then work on it and submit your PR

**Comment by NaaeemMalik** [comment]
@yeshwantthota  alright, I will work on it, thou I also waanna tell you that its gonna be my first open source coding bug although I have 8 years software development experience

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.47.39 Chromium: 107.0.5304.91 (Official Build) nightly (x86_64)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | macOS Version 11.7.1 (Build 20G918)

<img width="1312" alt="Screen Shot 2022-11-02 at 3 46 56 PM" src="https://user-images.githubusercontent.com/387249/199616758-f7cd5681-22fa-42c9-b3ef-bcc614318e51.png">
