### ISSUE TITLE
Add utils for transaction parsing outside of react hooks

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#26222]
## Description 

Currently, the format of transactions that are returned from core (`BraveWallet.TransactionInfo`) require additional parsing on the frontend to properly render the pertinent data Brave Wallet UI.

Also, the available frontend transaction parsing utilities are only accessible through react hooks, preventing their use within other contexts.

Moving logic from the monolithic `useTransactionParser` hook to smaller utility functions would allow partial transaction parsing within any context, and should make porting these utilities over to core for use within multiple environments easier.

The reimplementation also will offer opportunities for sorting and filtering lists of transactions by additional data points that are currently not available, such as token, or network.

**Comment by yrliou** [comment]
reverted by https://github.com/brave/brave-core/pull/15882

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.47.164 Chromium: 109.0.5414.74 (Official Build) (64-bit)
-- | --
Revision | `e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}`
OS | Linux

- Verified steps from [brave/brave-core#15891](https://github.com/brave/brave-core/pull/15891)
- Verified transactions are shown as expected

---------------------

Verification passed on 

Brave | 1.47.164 Chromium: 109.0.5414.74 (Official Build) (64-bit)
-- | --
Revision | `e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#15891](https://github.com/brave/brave-core/pull/15891)
- Verified transactions are shown as expected

---------------------

Verification passed on 

Brave | 1.47.164 Chromium: 109.0.5414.74 (Official Build) (arm64)
-- | --
Revision | `e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#15891](https://github.com/brave/brave-core/pull/15891)
- Verified transactions are shown as expected
