### ISSUE TITLE
icloud.com never loads with default shield settings

### ISSUE THREAD

**Issue by cndouglas** [brave/brave-browser#2622]
## Description 
https://www.icloud.com/ never finishes loading with the default shield settings, as shown below:
![image](https://user-images.githubusercontent.com/19424103/50173287-95b0a600-02bc-11e9-81b9-ab9d10aacc17.png)

The site loads correctly with the cookie setting changed to `All cookies allowed`.

## Steps to Reproduce
   1. Start with a fresh profile or reset all content settings.
   2. Go to https://www.icloud.com/

## Actual result:
The login page never loads. The following error message appears after a while:
![](https://user-images.githubusercontent.com/19424103/50173464-356e3400-02bd-11e9-9f39-19f068cb41df.png)

Here is the developer console output (with a few errors):
![image](https://user-images.githubusercontent.com/19424103/50173439-1c658300-02bd-11e9-9e57-d13944c17c78.png)

## Expected result:
The site should load the login page, like this:
![](https://user-images.githubusercontent.com/19424103/50173396-ef18d500-02bc-11e9-8de2-40f45ae27577.png)

## Reproduces how often: 
Always

## Brave version (brave://version info)
Brave | 0.60.3 Chromium: 71.0.3578.98 (Official Build) dev(64-bit)
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Yes, 0.60.3 dev.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? Yes.
- Is the issue reproducible on the latest version of Chrome? Not sure.

### Additional Information
#1025 mentions a problem with icloud.com with fingerprinting protection. This issue pertains to the cookie setting.

**Comment by diracdeltas** [comment]
just ran into this today

**Comment by srirambv** [comment]
Same issue with https://itunesconnect.apple.com/login. Adblock has 1 item but disable adblock also doesn;t load the login page. Shields down doesn't load the page either

**Comment by Maleick** [comment]
I wanted to give Brave a try and this was my only issue.

`All cookies allowed` does allow me to use the site.

**Comment by jonathansampson** [comment]
The website attempts to load an iframe from idmsa.apple.com. This page doesn't get the cookie it expects, and therefore responds with an `X-FRAME-OPTIONS: DENY` header.

**Comment by diracdeltas** [comment]
https://github.com/brave/referrer-whitelist/pull/2 should fix this. it doesn't require a new build, just an update to the referrer whitelist JSON file.

**Comment by diracdeltas** [comment]
Since this is not part of the regular release cycle (it's a file which is updated independently), any thoughts what milestone this should be marked as, @rebron ?

**Comment by rebron** [comment]
@diracdeltas Adding to what was current release at the time which was 65.x hotfix 2.
