### ISSUE TITLE
Add P3A metrics for weekly sent transactions per chain

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#26224]
Add P3A metrics for weekly sent transactions on Ethereum, Solana and Filecoin mainnets.

If you have ever sent a transaction, have you sent one in the past 7 days?
`Brave.Wallet.EthTransactionSent`, `Brave.Wallet.SolTransactionSent` and `Brave.Wallet.FilTransactionSent`

0. No
1. Yes

**Comment by GeetaSarvadnya** [comment]
Depending on the https://github.com/brave/brave-browser/issues/25504#issuecomment-1347912310

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.47.161 Chromium: 109.0.5414.61 (Official Build) beta (64-bit)
-- | --
Revision | 846c6eff1c374cde417a9cdc44193545cc07f354-refs/branch-heads/5414@{#1030}
OS | Windows 10 Version 21H2 (Build 19044.2364)

```

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on `Vivo X70 Pro version 12` runing `Bravemonoarmx64.apk_1.4.161`
