### ISSUE TITLE
`Mark as inappropriate` behaves as `Save` in 30-day ads history

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#26220]
Similar issue to https://github.com/brave/brave-browser/issues/26202

## Steps to Reproduce

1. Clean profile
1. Enable rewards and ads
1. View an ad
1. Navigate to brave://rewards
1. Navigate to 30-day ads history
1. Click 3 vertical dots
1. Click `Mark as inappropriate`

## Actual result:

Ad is marked as `Saved`
![image](https://user-images.githubusercontent.com/34715963/197635798-2b285e03-66ca-46b0-bf50-9ad698e4c523.png)

## Expected result:
Ad is marked as `inappropriate`
![image](https://user-images.githubusercontent.com/34715963/197635535-70d8cf90-dbb8-42a2-a415-132364432aa0.png)
`flag` confirmation is sent
```
[10333:10333:1024/234443.795098:VERBOSE1:redeem_unblinded_token.cc(353)] Successfully redeemed unblinded token flag confirmation for ad_notification with transaction id a97215cb-e75c-4a1d-837c-bd8b1f5b417c and creative instance id 0210de7e-2a7a-4ba7-af73-960acaac63fe
```

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.47.15 Chromium: 107.0.5304.62 (Official Build) nightly (64-bit)
-- | --
Revision | 1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942}
OS | Ubuntu 18.04 LTS

cc @jsecretan @tmancey

**Comment by tmancey** [comment]
@btlechowski this is working as expected, as "flag" is correct when marking as inappropriate. We send "bookmark" for saved ads. Thanks

**Comment by btlechowski** [comment]
This issue is valid. Reopening.

**Comment by kjozwiak** [comment]
The above requires `1.45.116` or higher for `1.45,x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```
Brave | 1.45.116 Chromium: 107.0.5304.91 (Official Build) (64-bit)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | Windows 10 Version 21H2 (Build 19044.2130)
```
