### ISSUE TITLE
Global fingerprinting setting defaults to standard on upgraded profile

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#26221]
## Description 
Global fingerprinting setting defaults to standard on upgraded profile

Does not occur when upgrading from 1.43 -> 1.44, also setting to allow FP will be retained. Its only when setting to `aggressive` that you will see it return to `standard` when upgrading

<img width="400" alt="0" src="https://user-images.githubusercontent.com/17885425/197638755-e7feccfd-7b15-4a98-919f-73b647298cfe.png">

## Steps to reproduce 

   1. Install 1.44
   2. Navigate to settings > Brave Shields & Privacy > Block Fingerprinting
   3. Set Block Fingerprinting to Strict
   4. Update to version 1.45
   5. Check global FP settings

## Actual result 
Set back to standard 

## Expected result
Should retain the setting when upgrading

## Issue reproduces how often 
Always 

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? Not tested
- Can you reproduce this issue with the current Play Store Nightly version? Not tested

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung Tablet
   - Android version: 12
   
## Brave version
1.45.x

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
@Uni-verse thanks for filing and nice catch. But as per the discussion on Slack, the above is expected due to https://github.com/brave/brave-core/pull/14389.
