### ISSUE TITLE
Enable Solana dapps support by default(Android)

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#26239]

**Comment by kjozwiak** [comment]
The above requires `1.46.102` or higher for `1.46.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.46.102 x64 Beta build
- Verified able to connect to Solana Dapps without having to enable any flags
- Verified able to connect/disconnect with Ethereum set as default
- Verified able to remove/re-add Solana Dapp connection from Site settings

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/200812779-7cbe28b9-7677-43a6-8747-d28aa3339036.mp4> | <video src=https://user-images.githubusercontent.com/17010094/200813386-8f81f9c7-7fcc-40e9-a38d-398db30b64c3.mp4>
