### ISSUE TITLE
Fingerprinted by fingerprint.com- privacy concern

### ISSUE THREAD

**Issue by U-Gautam** [brave/brave-browser#26235]
## Description 
 If you visit fingerprint.com, you will get an unique id. This id is persistent even if you clear all data from settings, not only that even if your clear storage and cache from within Android setting, the unique id still persists. I think this is a major privacy concern. Bromite and Firefox don't have this issue after clearing "all data" from within their settings.

## Steps to reproduce 

   1. visit fingerprint.com
   2. the website assigns you with unique and persistent tracking id
   3. clear all data from within settings to get rid of cookies, history etc.
   4. The id is still persistent even if you clear "storage and cache" from within aandroid settings

## Actual result 
The tracking id should be cleared and non persistent after clearing all the data from brave settings or android settings

## Expected result
The tracking id should be cleared and the website shouldn't be able to track brave users on Android devices

## Issue reproduces how often 
Easily reproduced

## Version/Channel Information:

All the channels

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 13
   
## Brave version
1.44.112 

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Not sure

**Comment by m77e4t** [comment]
It has already been discussed in depth https://github.com/brave/brave-browser/issues/20268

The company seems to have changed their name from fingerprintjs to just fingerprint.

**Comment by wooque** [comment]
I learned about this from https://www.bitestring.com/posts/2023-03-19-web-fingerprinting-is-worse-than-I-thought.html.
Firefox can be resistant to fingerprinting by setting `privacy.resistFingerprinting = true`, Brave is fingerprinted easily. 
I hope Brave team will try to tackle this privacy issue, otherwise privacy that boasts about is just charade.

**Comment by aocorporation** [comment]
bump.

**Comment by bsclifton** [comment]
cc: @pes10k

**Comment by ShivanKaul** [comment]
Please see https://github.com/brave/brave-browser/issues/20268#issuecomment-1003189602.
