### ISSUE TITLE
Fix animation for Brave toolbar buttons

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#26245]
## Description 
This is a follow up for https://github.com/brave/brave-browser/issues/26155

https://user-images.githubusercontent.com/30602739/197795984-d1791075-5160-4c7d-9d5f-c96b792c34ab.mp4

## Steps to reproduce 

   1. Goto any scrollable website.
   2. Start scrolling so toolbar starts to disappear (see video above).
   3. Brave icons disappear with part of url bar.

## Actual result 
Brave icons disappear with part of url bar.

## Expected result
Brave icons remain in url bar.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
1.47.x

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy GS 21` & `Samsung Galaxy Tab S7` on the following version(s):

```
Brave	1.47.161 Chromium: 109.0.5414.61 (Official Build) beta (64-bit) 
Revision	846c6eff1c374cde417a9cdc44193545cc07f354-refs/branch-heads/5414@{#1030}
OS	Android 12; Build/SP1A.210812.016
```
- Verified icons in the tool bar do not disappear when scrolling

https://user-images.githubusercontent.com/17885425/210618966-17dd715b-9d23-4e44-b17c-88a6c3119845.mp4
