### ISSUE TITLE
Smooth scrolling doesn't work

### ISSUE THREAD

**Issue by armaccloud** [brave/brave-browser#26249]
## Description 
Setting the option in brave://flags for smooth scrolling to enabled, doesn't enable smooth scrolling.

## Steps to Reproduce
   1. Ensure to have Brave Browser installed as a flatpak on Linux (in my case, Pop!_OS)
   2. Set the flag smooth scrolling to enabled
   3. Verify that smooth scrolling doesn't work

## Actual result:
Smooth scrolling doesn't work

## Expected result:
Smooth scrolling is working.

## Brave version
1.44.112 Chromium: 106.0.5249.119

**Comment by bsclifton** [comment]
Closing as stale. Let's re-open if this is still an issue. Thanks!
