### ISSUE TITLE
Vertical tabs conflict with Tab Scrolling flag

### ISSUE THREAD

**Issue by Coffeeling** [brave/brave-browser#26241]
Post from #464 below:

---

There's something off about Vertical Tabs in Beta, but they seem to be fine on Nightly:

Blue is Beta, gray is Nightly.
![image](https://user-images.githubusercontent.com/54371213/194583586-6037af24-bfce-4447-a4b6-32d1970f1080.png)

![image](https://user-images.githubusercontent.com/54371213/194583816-2fb077be-b59c-40f8-b1cb-424fa2341613.png)

Seems that vertical tabs are a browser-wide thing atm, I switched vert tabs on on one profile in Beta and it rebooted Beta entirely with vert tabs.

_Originally posted by @Coffeeling in https://github.com/brave/brave-browser/issues/464#issuecomment-1271707668_

---

The cause seems to be that I had Tab Scrolling enabled in my beta install. Vertical Tabs work fine after I disabled it.

**Comment by illtellyoulater** [comment]
I confirm this issue. I'm seeing this in stable. Disabling tabs scrolling fixes it.
