### ISSUE TITLE
`Customize Dashboard` dialog disappears when clicking `Back to Dashboard`

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#26252]
## Description 

`Customize Dashboard` dialog disappears when clicking `Back to Dashboard`

Found while testing https://github.com/brave/brave-browser/issues/25563

## Steps to Reproduce

   1. install `1.47.14`
   2. launch Brave
   3. set `brave://flags/#brave-news-v2` to `Enabled`
   4. click on `Relaunch`
   5. open a new-tab page
   6. scroll down
   7. click on `Show Brave News`
   8. click on `Customize`
   9. click on `<-- Back to Dashboard`

   
## Actual result:

`Customize` dialog disappears

`Back to Dashboard` | missing `Customize Dashboard` dialog
----------|-------
<img width="1312" alt="Screen Shot 2022-10-25 at 3 30 50 PM" src="https://user-images.githubusercontent.com/387249/197894451-46d546d5-5d3b-4666-aec9-aa2ed26b0779.png"> | <img width="1312" alt="Screen Shot 2022-10-25 at 3 29 12 PM" src="https://user-images.githubusercontent.com/387249/197894159-e403c3d8-7cc3-4597-b484-114a29d57991.png">

## Expected result:

Should return to the `Customize Dashboard` dialog

<img width="1312" alt="Screen Shot 2022-10-25 at 3 26 09 PM" src="https://user-images.githubusercontent.com/387249/197893884-50cad0bb-3970-432f-aa77-e4ade1e3919b.png">

## Reproduces how often: 

100%
## Brave version (brave://version info)

Brave | 1.47.14 Chromium: 107.0.5304.62 (Official Build) nightly (x86_64)
-- | --
Revision | 1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942}
OS | macOS Version 11.7.1 (Build 20G918)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @brave/qa-team @rebron @petemill @fallaciousreasoning

**Comment by fallaciousreasoning** [comment]
Fixed by https://github.com/brave/brave-core/pull/15755

**Comment by fallaciousreasoning** [comment]
One thing I wasn't sure about was whether the 'X' button should close both dialogs. For now it only closes the first one.
