### ISSUE TITLE
Preview for a hovered over tab is not shown when `Card with preview` is selected in `brave://settings/appearance`

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#26251]
Currently when hovered over a tab for a visited site (not the currently active tab) either vertical or horizontal tab, thumbnail of the tab is not displayed. This functionality  was tested in 1.44.x -https://github.com/brave/brave-browser/issues/9906.  It appears to be broken in 1.45.x. 

## Steps to Reproduce

   1. Install 1.46.73
   2. launch Brave
   3. visit cnbc.com
   4. open brave://settings/appearance
   5. switch the setting to `Card with preview`
   6. hovered over a tab (not the currently active tab)

   
## Actual result:

thumbnail is not shown (either vertical tab or horizontal tab)
Note: this issue is reproducible for `horizontal tab` as well in `1.45.x`
horizontal tab|vertical tab
---|---
![image](https://user-images.githubusercontent.com/98358127/197864988-5e60f907-c18a-4589-a6d8-455581534bb0.png)|![image](https://user-images.githubusercontent.com/98358127/197864896-a9aca907-d082-49a7-9f5a-e0f0f1df4f36.png)

## Expected result:
 a thumbnail and preview of the tab should be shown 
 (1.44.x)
![image](https://user-images.githubusercontent.com/98358127/198068696-8c13a54a-9022-4992-8111-f482a20907d4.png)

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.46.73 Chromium: 107.0.5304.62 (Official Build) beta (64-bit)
-- | --
Revision | 1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942}
OS | Windows 11 Version 21H2 (Build 22000.1098)
```
## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@sangwoo108 @rebron

**Comment by kjozwiak** [comment]
We should try getting this into the `1.45.x` maintenance release 👍 CCing @rebron

**Comment by GeetaSarvadnya** [comment]
>Can you reproduce this issue with the current release? 

Yes in 1.45.x but not in 1.44.x


**1.44.x** - works fine

![image](https://user-images.githubusercontent.com/38657976/197954322-15e23e6a-9ff3-42fc-a0ac-0473565fed3d.png)

**Comment by rebron** [comment]
cc: @fallaciousreasoning @simonhong

**Comment by sangwoo108** [comment]
Sorry, it seems I made a mistake during rebase :(

**Comment by kjozwiak** [comment]
The above requires `1.45.116` or higher for `1.45.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
Brave | 1.45.116 Chromium: 107.0.5304.91 (Official Build) (64-bit)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | Windows 10 Version 21H2 (Build 19044.2130)

```

- Confirmed that thumbnail and preview of the tab is shown when `Card with preview` is selected in `Tab hover mode` settings under `brave://settings/appearance`
- Confirmed that the thumbnail and preview of the tab is shown bor the both `horizontal tab` and `vertical tab` patterns
- Confirmed that the thumbnail and preview of the tab works fine in both the clean and upgraded profiles

**_Clean profile_**

**`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|-----------
![image](https://user-images.githubusercontent.com/38657976/198546541-8a9f23bb-28fe-48c4-bc2a-fee74e6e1bd9.png) | ![image](https://user-images.githubusercontent.com/38657976/198546489-eb129d4b-bc64-42b7-9ce9-2be991cc60a9.png) | ![image](https://user-images.githubusercontent.com/38657976/198548243-9f9eeecb-ec38-4374-8c0c-7d79f5b3097f.png) | ![image](https://user-images.githubusercontent.com/38657976/198548331-3e6a848f-c983-4dcf-8ab5-44ba789025b5.png)


**_Upgrade profile_**

Install `1.45.113` and  select `Card with preview` in `Tab hover mode` settings under `brave://settings/appearance`, open bunch of sites and hover over the tabs, observed that the tab preview is NOT shown, upgrade the profile to `1.45.116`

**`1.45.113`** | **`1.45.116`**
---------------|-------------
![image](https://user-images.githubusercontent.com/38657976/198549825-cd5b63db-4139-4cbc-9868-a7a08669f444.png) | ![image](https://user-images.githubusercontent.com/38657976/198550429-038ff70a-3158-4c3d-babc-b642f2401cf1.png)
