### ISSUE TITLE
Replace Brave Web Store with Web Store in 0.58.x release.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#2625]
Since brave/brave-browser#2497 fix won't make it to 0.58.x we still want to patch the string without needing to redo the localization. For 0.58.x we will just replace "Brave Web Store" with "Web Store" globally which won't require localization changes.

cc: @rebron

**Comment by rushilsrivastava** [comment]
Can the support URLs also be updated accordingly, reported in #2457

**Comment by rebron** [comment]
@mkarolin per discussion in triage, marking uplift-approved, let's get this merged to 58.x.

**Comment by mkarolin** [comment]
Merged to 0.58.x.
@rebron @bbondy based on the number of strings replaced, it might make sense to apply this change to 0.59.x and above as well, since brave/brave-core#1080 won't affect all of these strings.

**Comment by mkarolin** [comment]
Fixed

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.58.16 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/1133
![screen shot 2018-12-19 at 6 06 41 pm](https://user-images.githubusercontent.com/28145373/50253688-05a45680-03b9-11e9-8235-71697bd5a3c2.png)
![screen shot 2018-12-19 at 6 07 06 pm](https://user-images.githubusercontent.com/28145373/50253691-06d58380-03b9-11e9-83aa-f6a9f3034748.png)
