### ISSUE TITLE
There are three otherwise identical CNN feed sources

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#26259]
## Description 

There are three otherwise identical CNN feed sources

## Steps to Reproduce

   1. install `1.47.14`
   2. launch Brave
   3. open `brave://flags`
   4. set `brave://flags/#brave-news-v2` to `Enabled`
   5. click on `Relaunch`
   6. open a new-tab page
   7. click on `Customize`
   8. click on `Turn on Brave News`
   9. type `cnn`
  10. look at the results 

## Actual result:

There are 3 non-descript, otherwise-identical CNN feed sources (in addition to CNN Brasil and CNN.co.jp, which are clearly marked)

unfollowed | followed
------------|--------
<img width="919" alt="Screen Shot 2022-10-25 at 4 51 47 PM" src="https://user-images.githubusercontent.com/387249/197903021-4c499776-4916-459c-bd39-56a4d8c8de43.png"> | <img width="919" alt="Screen Shot 2022-10-25 at 4 54 42 PM" src="https://user-images.githubusercontent.com/387249/197903304-0c9738a0-8468-4648-b0ac-f721543376d6.png">

## Expected result:

Either there should only be 1, or it should be possible to differentiate between them (tooltip or something?)

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.47.14 Chromium: 107.0.5304.62 (Official Build) nightly (x86_64)
-- | --
Revision | 1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942}
OS | macOS Version 11.7.1 (Build 20G918)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron @mattmcalister @fallaciousreasoning @petemill

**Comment by fallaciousreasoning** [comment]
@petemill, maybe this has something to do with locales? I had a look at `sources.global.json` and there are three `CNN`s. One in `en_US`, one in `en_CA` and one in `es_ES`. The two sources in `en_US` and `en_CA` are identical except for channels.

**Comment by petemill** [comment]
I believe this is fixed in dev environment and maybe just not pushed to production yet

**Comment by kjozwiak** [comment]
The above requires `1.46.94` or higher for `1.46.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.46.96 Chromium: 107.0.5304.91 (Official Build) beta (x86_64)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | macOS Version 11.7.1 (Build 20G918)

### Steps:

1. install `1.46.96`
2. launch Brave
3. open `brave://flags`
4. set `brave://flags/#brave-news-v2` to `Enabled`
5. clicked on `Relaunch`
6. opened a new-tab page
7. clicked on `Customize`
8. clicked on `Turn on Brave News`
9. typed `cnn`
10. looked at the results

#### Confirmed there was one fewer `CNN.com` feeds - we're left with the two valid ones: `en_US` and `en_CA`

### `1.46.96` - original issue

`unfollowed` | `followed`
--------------|----------
<img width="919" alt="197903021-4c499776-4916-459c-bd39-56a4d8c8de43" src="https://user-images.githubusercontent.com/387249/200422401-8d002900-68e7-45f9-96a7-dba84dc8a3b8.png"> | <img width="919" alt="197903304-0c9738a0-8468-4648-b0ac-f721543376d6" src="https://user-images.githubusercontent.com/387249/200422404-4f3c4531-ebf8-446c-98b3-b9647952651d.png">


### `1.47.14` - fixed

`unfollowed` | `followed`
-------------|-----------
<img width="1312" alt="Screen Shot 2022-11-07 at 1 30 07 PM" src="https://user-images.githubusercontent.com/387249/200422193-eb7199cd-1463-49ef-8074-407e44743f3b.png"> | <img width="1358" alt="Screen Shot 2022-11-07 at 1 48 59 PM" src="https://user-images.githubusercontent.com/387249/200422584-af78d243-1382-453a-817a-ae1a60f8b26a.png">
