### ISSUE TITLE
[Brave News] Brave News should check the favicon cache if a publisher doesn't have an icon

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#26266]
Currently, direct sources don't have any favicons. As most of the time, a user will have visited the publisher, looking up the icon in the favicon cache is a quick win.

**Comment by kjozwiak** [comment]
The above requires `1.46.102` or higher for `1.46.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.46.102 Chromium: 107.0.5304.110 (Official Build) beta (64-bit)
-- | --
Revision | 2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}
OS | Windows 11 Version 21H2 (Build 22000.1219)
```

Verified using testplan from https://github.com/brave/brave-core/pull/15820#issuecomment-1307972156

Example|Example|Example|Example|Example
-----|-----|-----|-----|-----
<img width="455" alt="image" src="https://user-images.githubusercontent.com/98358127/201398703-1dd182dd-3a1d-4852-9a59-74215b7b1fe3.png">|<img width="461" alt="image" src="https://user-images.githubusercontent.com/98358127/201398942-1ca9f215-1837-4653-80a3-a1681ce9d30c.png">|<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/201398967-c39f82e4-6f01-4cdc-b979-6dc9641159ea.png">|<img width="464" alt="image" src="https://user-images.githubusercontent.com/98358127/201399060-03ebc3cb-d24c-46ea-9355-0777f8b83762.png">|<img width="452" alt="image" src="https://user-images.githubusercontent.com/98358127/201399771-17e2ec98-8508-425f-9f0b-3fb95c92bef9.png">
