### ISSUE TITLE
`Follow` button text is invisible until hovered over

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#26262]
## Description 

`Follow` button text is invisible until hovered over

## Steps to Reproduce

1. install `1.47.14`
2. launch Brave
3. open `brave://flags`
4. set `brave://flags/#brave-news-subscribe-button` to `Enabled`
5. click `Relaunch`
6. open a new-tab page
7. load `planet.mozilla.org`
8. click on the `Manage Subscriptions` News icon in the URL bar
9. look at the resulting UI

## Actual result:

<img width="954" alt="Screen Shot 2022-10-25 at 5 01 08 PM" src="https://user-images.githubusercontent.com/387249/197903907-e6b5cc6b-2bb6-4341-aeb2-9242f414daec.png">

## Expected result:

<img width="954" alt="Screen Shot 2022-10-25 at 5 01 59 PM" src="https://user-images.githubusercontent.com/387249/197903936-a88e83a6-fae1-4462-ba10-916577c7b5f1.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.47.14 Chromium: 107.0.5304.62 (Official Build) nightly (x86_64)
-- | --
Revision | 1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942}
OS | macOS Version 11.7.1 (Build 20G918)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron @mattmcalister @fallaciousreasoning @petemill

**Comment by fallaciousreasoning** [comment]
Wow, that's weird - it doesn't do it on Linux at all. I think it might be `macOS` specific. I'll have a look

**Comment by fallaciousreasoning** [comment]
Does this still repro now https://github.com/brave/brave-core/pull/15856 has landed?

**Comment by mattmcalister** [comment]
Am still seeing the blank follow on MacOS using 1.47.82
![image](https://user-images.githubusercontent.com/71029/202653646-615b39e7-a030-4f17-bf90-36e0bc04f4be.png)

**Comment by stephendonner** [comment]
@fallaciousreasoning Still seeing the issue using 

Brave | 1.47.91 Chromium: 108.0.5359.48 (Official Build) nightly (x86_64)
-- | --
Revision | 18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}
OS | macOS Version 11.7.1 (Build 20G918)

<img width="1312" alt="Screen Shot 2022-11-21 at 10 40 11 AM" src="https://user-images.githubusercontent.com/387249/203134278-bc4c7e5a-cfd1-41c6-829d-24f27e7b1a7b.png">

**Comment by mattmcalister** [comment]
Same. Also, the icon was updated. Can we get that changed over? cc @martin-c0des

**Comment by stephendonner** [comment]
> Same. Also, the icon was updated. Can we get that changed over? cc @martin-c0des

For cross-reference, that's taken care of now in https://github.com/brave/brave-browser/issues/26997.

**Comment by kjozwiak** [comment]
We'll be uplifted the above into the `1.46.x` maintenance release via https://github.com/brave/brave-core/pull/16143 once the initial `1.46.x` build goes out. Verification will be completed on `1.46.x`.

**Comment by kjozwiak** [comment]
The above requires `1.46.139` or higher for `1.46.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.46.141 Chromium: 108.0.5359.99 (Official Build) (64-bit)
-- | --
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | Windows 10 Version 21H2 (Build 19044.2251)

```
#### Confirmed initial/default, hover, and click/followed states are rendered correctly

#### `Dark` mode:

default | hover | click/followed
--------|----------|---------
![image](https://user-images.githubusercontent.com/38657976/206729008-fef3b709-5b04-4fa7-a773-e703dfa0623e.png) | ![image](https://user-images.githubusercontent.com/38657976/206729090-f69bc02d-c752-4b2e-97e5-ab6af06052fd.png) | ![image](https://user-images.githubusercontent.com/38657976/206729200-59e79df8-4bcf-4918-8e6c-f3974b16a685.png)


#### `Light` mode:

default | hover | click/followed
--------|------|------
![image](https://user-images.githubusercontent.com/38657976/206728491-afe54aa7-0145-48aa-a615-bad2b929fb19.png) | ![image](https://user-images.githubusercontent.com/38657976/206728574-5e138914-cfb9-4ca6-a790-6dbdca3c8d04.png) | ![image](https://user-images.githubusercontent.com/38657976/206728837-162a6952-a14a-4433-b8eb-5b05ed89b952.png)

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.46.141 Chromium: 108.0.5359.99 (Official Build) (x86_64)
-- | --
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | macOS Version 13.1 (Build 22C65)

`Dark` mode:

default | hover | followed
--------|------|----------
<img width="1312" alt="Screenshot 2022-12-09 at 11 40 34 AM" src="https://user-images.githubusercontent.com/387249/206784722-728e6560-f5b1-4774-ac9a-326184406c58.png"> | <img width="1312" alt="Screenshot 2022-12-09 at 11 40 39 AM" src="https://user-images.githubusercontent.com/387249/206784727-34a0d503-eb97-4207-9f02-35dce03463f1.png"> | <img width="1312" alt="Screenshot 2022-12-09 at 11 41 21 AM" src="https://user-images.githubusercontent.com/387249/206784730-da173c3c-5dd1-4fda-8dc6-9bcdf0079555.png">


`Light` mode:

default | hover | followed
-------|-------|----------
<img width="1312" alt="Screenshot 2022-12-09 at 11 40 58 AM" src="https://user-images.githubusercontent.com/387249/206784439-414d3dd7-57be-40ab-a88c-42b5944f42b0.png"> | <img width="1312" alt="Screenshot 2022-12-09 at 11 40 58 AM" src="https://user-images.githubusercontent.com/387249/206784538-f27f2977-6b11-4070-b1bc-4fe53917f448.png"> | <img width="1312" alt="Screenshot 2022-12-09 at 11 41 07 AM" src="https://user-images.githubusercontent.com/387249/206784588-4e57057f-174f-4262-96a0-4f86b3a246a4.png">

**Comment by btlechowski** [comment]
Verification **PASSED** on

Brave | 1.46.141 Chromium: 108.0.5359.99 (Official Build) (64-bit)
-- | --
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | Ubuntu 18.04 LTS

`Dark` mode:

default | hover | followed
--------|------|----------
![image](https://user-images.githubusercontent.com/34715963/206806419-d1f5eaac-a157-4731-a016-ec19b60b2636.png)|![image](https://user-images.githubusercontent.com/34715963/206806439-110333d6-65bb-44fa-b07a-b991acb9e5a9.png)|![image](https://user-images.githubusercontent.com/34715963/206806483-fd4c05a1-5523-4c0b-b0fb-84ec601bd889.png)



`Light` mode:

default | hover | followed
-------|-------|----------
![image](https://user-images.githubusercontent.com/34715963/206806271-2a03b405-d69e-4317-ad14-91a023c24b06.png)|![image](https://user-images.githubusercontent.com/34715963/206806352-27abf245-d518-4955-bfb6-cf4fca8f82aa.png)|![image](https://user-images.githubusercontent.com/34715963/206806517-5b90c465-6b55-44c0-bcf2-63c96a4593d1.png)
