### ISSUE TITLE
Need to unescape special characters in feed titles

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#26264]
## Description 

Need to unescape special characters in feed titles

## Steps to Reproduce

   1. install `1.47.14`
   2. launch Brave
   3. load `brave://flags`
   4. set `brave://flags/#brave-news-v2` to `Enabled`
   5. click on `Relaunch`
   6. open a new-tab page
   7. click on `Customize`
   8. click on `Brave News`
   9. click on `Turn on Brave News`
   10. type `food` in the `Discover` search textfield
   11. look at the `Food &amp; Wine Magazine` entry

## Actual result:

<img width="940" alt="Screen Shot 2022-10-25 at 6 04 23 PM" src="https://user-images.githubusercontent.com/387249/197910580-6b8e2c87-111c-4678-94a0-4dd24b1ffe8c.png">

## Expected result:

`Food & Wine Magazine`

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.47.14 Chromium: 107.0.5304.62 (Official Build) nightly (x86_64)
-- | --
Revision | 1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942}
OS | macOS Version 11.7.1 (Build 20G918)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @mattmcalister @rebron @fallaciousreasoning @petemill @brave/qa-team

**Comment by diracdeltas** [comment]
I suspect the original point of escaping was to avoid XSS/HTML injection in feed titles so please make sure the fix for this has sec review

**Comment by fallaciousreasoning** [comment]
I think this is related to https://github.com/brave/news-aggregator/issues/44

**Note:** I don't think we need to worry about XSS/HTML injection because the places this is used are either:
1. On Android, and not HTML
2. Via React, where HTML is escaped automatically

**Comment by fallaciousreasoning** [comment]
This seems to have been fixed a while ago!
