### ISSUE TITLE
Should not scroll Brave News feed in background when `Customize Dashboard` dialog is focused

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#26271]
## Description 

Should not scroll Brave News feed in background when `Customize Dashboard` dialog is focused (credit to @srirambv for the find 👍 )

## Steps to Reproduce

   1. install `1.47.19`
   2. launch Brave
   3. open a new-tab page
   4. set `brave://flags/#brave-news-v2` to `Enabled`
   5. click on `Relaunch`
   6. click on `Customize`
   7. click on `Turn on Brave News`
   8. via `Follow`, add a bunch of sources and/or channels (so there's a need to scroll the list in the `Following` pane)
   9. hover the mouse/pointer over the `Following` pane
   10. scroll using scroll wheel on mouse/trackpad, etc.
   11. when you reach the end of the list, keep scrolling
   

## Actual result:

After scrolling the `Following` pane's list, you'll start scrolling the Brave News feed in the background

## Expected result:

Should probably *not* scroll the background, too, when a parented-to-current-window dialog is focused?

## Reproduces how often: 

100%
## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

cc @srirambv @mattmcalister @rebron @fallaciousreasoning @petemill

**Comment by kjozwiak** [comment]
The above requires `1.46.102` or higher for `1.46.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.46.102 Chromium: 107.0.5304.110 (Official Build) beta (64-bit)
-- | --
Revision | 2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}
OS | Windows 11 Version 21H2 (Build 22000.1219)
```
Reproduced in 1.46.99 using original STR for Win 11 x64

1. Install 1.46.102
2. launch Brave
3. opened `brave://flags` in NTP
4. enabled `#brave-news-v2` 
5. clicked on `Relaunch`
6. clicked on `Customize`
7. click on `Turn on Brave News`
8. clicked `Follow` button to  add a bunch of sources and/or channels to scroll the list in the `Following` pane 
9. hovered the mouse/pointer over the `Following` pane
10. scrolled using scroll wheel on mouse till end of the list and keep scrolling 


#### Confirmed scrolling with the mouse cursor on the customize Brave News dialog or Following pane on the left did not  scroll the page behind/background

https://user-images.githubusercontent.com/98358127/201170035-20690819-fe1b-4744-bfe7-3e1b2869a102.mp4
