### ISSUE TITLE
No audio output from Brave if I plug in a new audio device.

### ISSUE THREAD

**Issue by jnki** [brave/brave-browser#2627]
## Description 

If I add a new audio device, brave will stop outputting audio until I restart computer.
Every other application and browser still outputs audio, only Brave refuses to output.

## Steps to Reproduce

   1. Have Brave open, with a page playing audio (youtube or something)
   2. Notice audio is playing fine.
   3. Plug in a headset, or some other new audio device.
   4. Close and relaunch Brave.

## Actual result:

Brave no longer outputting audio. Have to restart computer for it to work again.

## Expected result:
Brave should output audio to whatever is the default device.

## Reproduces how often: 

Easily reproduced.

## Brave version (brave://version info)

Brave | 0.57.18 Chromium: 71.0.3578.80 (Official Build) (64-bit)
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Windows 10 64bit 1809

**Comment by jnki** [comment]
might be related to this, although their issue is on mac #2617

**Comment by jnki** [comment]
i'm no longer experiencing this in the latest update. so i will close it :)

**Comment by bsclifton** [comment]
@jnki perfect- thanks for the update 😄
