### ISSUE TITLE
Inline ads are shown first on feed (Desktop Brave News)

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#26277]
## Description 

Inline ads are shown first on feed

## Steps to Reproduce

   1. Enable V2 News flag
   2. Enable Brave news and scroll down
   3. First card on the feed is an inline ad

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/198021937-39552f29-4956-4061-8d97-ae9a31d82508.png)

## Expected result:
Should show a content feed card first

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.47.17 Chromium: 107.0.5304.62 (Official Build) nightly (arm64)
-- | --
Revision | `1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942}`
OS | macOS Version 13.0 (Build 22A380)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Not checked
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @tmancey @mattmcalister @brave/legacy_qa

**Comment by kjozwiak** [comment]
The above requires `1.46.107` or higher for `1.46.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.46.121 Chromium: 108.0.5359.48 (Official Build) beta (64-bit)
-- | --
Revision | 18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}
OS | Windows 11 Version 21H2 (Build 22000.1219)
```
Details

1. installed 1.46.121
2. clicked `Skip welcome tour`
3. clicked on `Customize`
4. confirmed Brave news V2 UI  with `Turn on Brave News` button displayed
5. clicked on the `Turn on Brave News` button
6. Brave news sources displayed as expected
7. closed the dialog
8. scrolled initial Brave News content

Confirmed the 1st feed content was a CBS news article, followed by our `inline-content ad`

step 4|step 5|results
-----|-----|----
<img width="464" alt="image" src="https://user-images.githubusercontent.com/98358127/203157940-995f97c1-0aad-4d7b-adc3-5b5422a7ab0b.png">|<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/203157993-14d761e9-1da5-43fb-81ce-a5bd0799cfd5.png">|<img width="462" alt="image" src="https://user-images.githubusercontent.com/98358127/203158579-9deb342e-99a4-4239-8aba-a3a7012ca567.png">
