### ISSUE TITLE
"Learn more" link missing from error message in Rewards panel when 403 is returned from server - follow up to 24542

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#26280]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/24542

If you select a country which will return `403` from the server, the corresponding error message on the panel looks like it should have a link to "Learn more", but it doesn't.

## Steps to Reproduce

   1. Clean profile 1.46.x, relaunch to pull griffin seed
   2. Click on rewards icon
   3. Click to start using rewards
   4. Select "Iran" as the country

Logs:
```
[ REQUEST ]
> URL: https://grant.rewards.bravesoftware.com/v4/wallets
> Method: POST
> Content: {"geoCountry":"IR"}
........
> Url: https://grant.rewards.bravesoftware.com/v4/wallets
> Result: Failure
> HTTP Code: 403
> Body: {"code":403,"message":"error creating rewards wallet: geo country is disabled"}
[7657:259:1026/103122.265798:VERBOSE9:logging_util.cc(135)] 
[ RESPONSE HEADERS ]
> Url: https://grant.rewards.bravesoftware.com/v4/wallets
```

## Actual result:

See the `$2Learn more$2` in the text below. 

<img width="440" alt="Screen Shot 2022-10-26 at 10 31 30 AM" src="https://user-images.githubusercontent.com/28145373/198055393-2f9bf7f9-5a87-4b3c-884f-0d3c7bbd0577.png">

## Expected result:

Per spec from https://github.com/brave/internal/issues/894, the "Learn more" link should point to https://support.brave.com/hc/en-us/articles/9312922941069.

## Reproduces how often: 

easily

## Brave version (brave://version info)

```
Brave | 1.46.80 Chromium: 107.0.5304.68 (Official Build) beta (x86_64)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | macOS Version 12.6.1 (Build 21G217)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 1.45.x n/a
- Can you reproduce this issue with the beta channel? 1.46.x yes
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @Miyayes @zenparsing

**Comment by kjozwiak** [comment]
The above requires `1.46.84` or higher for `1.46.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.46.86 Chromium: 107.0.5304.91 (Official Build) beta (x86_64)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | macOS Version 12.6.1 (Build 21G217)
```
