### ISSUE TITLE
Open in a new tab from brave news

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#26289]
![brave_news1](https://user-images.githubusercontent.com/12011303/198103911-2a30272e-3cbe-49f5-9494-48d70f3c8cc0.jpg)
If i choose open in new tab,it takes me to that tab instead of opening in background like any hyperlink from any webpage in same browser.
We should be consistent with that.

**Comment by mattmcalister** [comment]
seems sensible but not urgent. am adding it to our list.

**Comment by Uni-verse** [comment]
Verified on `Samsung GS 21` & `Samsung Galaxy Tab S7` using version(s):

```
Brave	1.49.117 Chromium: 111.0.5563.50 (Official Build) (64-bit) 
Revision	39f3dfc5023fe60997adc4f6cf5439cfa3e6968a-refs/branch-heads/5563@{#903}
OS	Android 13; Build/TP1A.220624.014
```
```
Brave	1.49.117 Chromium: 111.0.5563.50 (Official Build) (64-bit) 
Revision	39f3dfc5023fe60997adc4f6cf5439cfa3e6968a-refs/branch-heads/5563@{#903}
OS	Android 12; Build/SP2A.220305.013
```

- Ensured opening news articles in new tab will open tabs in background. 

Example | Example | Example
-|-|-
![screenshot-1677790234039](https://user-images.githubusercontent.com/17885425/222567706-145db8e6-fced-4c66-9fe3-ad17208c8297.png) | ![screenshot-1677794360218](https://user-images.githubusercontent.com/17885425/222568322-365925d4-b004-4b27-a87a-de1315eaa79c.png) | ![screenshot-1677794386218](https://user-images.githubusercontent.com/17885425/222568623-3039cda9-869a-4092-9bfa-fc6df5bce262.png)
