### ISSUE TITLE
[Android] Geo declaration causes app to crash (1.46.x) 

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#26286]
## Description

From user report:

![image](https://user-images.githubusercontent.com/11497541/198086494-87e2b541-6e77-4685-853f-0aa029576c2f.png)

cc: @anthonypkeane

**Comment by kjozwiak** [comment]
The above requires `1.46.143` or higher for `1.46.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress on Samsung J7 Neo with Android 7 running 1.46.143.

* Verified the test plan from https://github.com/brave/brave-core/pull/16341#issue-1493033805.
* Reproduced the issue using device above and version `1.46.138`.
