### ISSUE TITLE
`PopularMechanics` should be `Popular Mechanics` in Brave News v2 feed

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#26299]
## Description 

`PopularMechanics` should be `Popular Mechanics` in Brave News v2 feed

## Steps to Reproduce

   1. install `1.47.20`
   2. launch Brave
   3. enable Brave News v2 via `brave://flags`
   4. open a new-tab page
   5. scroll down
   6. click on `Show Brave News`
   7. click on `Customize`
   8. type `popular` or `popularmechanics` or `mechanics`
   9. look at the search result

## Actual result:

<img width="1312" alt="Screen Shot 2022-10-26 at 1 01 13 PM" src="https://user-images.githubusercontent.com/387249/198125883-ca4e0b9e-883d-4d18-be9e-54dfa8053c40.png">

## Expected result:

`Popular Mechanics`

## Reproduces how often: 

100%
## Brave version (brave://version info)

Brave | 1.47.20 Chromium: 107.0.5304.68 (Official Build) nightly (x86_64)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | macOS Version 11.7.1 (Build 20G918)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @fallaciousreasoning @mattmcalister

**Comment by fallaciousreasoning** [comment]
I think this should be filed against the https://github.com/brave/news-aggregator

I've created https://github.com/brave/news-aggregator/issues/149 and I'm going to close this one.
