### ISSUE TITLE
Remove ActiveCampaign tracker from the query string

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#26295]
I found this tracking parameter in a spam email:
https://webappick.com/plugin/woocommerce-product-feed-pro/?utm_source=hw&utm_medium=email&utm_campaign=hw-cm-22&utm_source=ActiveCampaign&utm_medium=email&utm_content=Halloween+Coupon+Arrived+%F0%9F%8E%83+Get+CTX+Feed+PRO+with+30++Off+%F0%9F%94%A5&utm_campaign=HWC_5th_251122_Without_Automation&vgo_ee=XxqkePXGUrvI2IoN4Bf%2B5Yvy7T5YEJ8ohjC9vauJg30%3D

The `vgo_ee` parameter comes from ActiveCampaign and [contains the encrypted email address of the user who clicked the link](https://help.activecampaign.com/hc/en-us/articles/221542267-An-overview-of-Site-Tracking#how-contacts-are-identified-0-5)

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.47.39 Chromium: 107.0.5304.91 (Official Build) nightly (x86_64)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | macOS Version 11.7.1 (Build 20G918)

### Steps:
1. installed `1.47.39`
2. launched Brave
3. loaded `https://brave.com/?vgo_ee=1234`
4. looked at the URL bar

#### Confirmed that trying to load `https://brave.com/?vgo_ee=1234` ends up doing a `200 OK` `Internal Redirect`, and only `https://brave.com/` was loaded, ultimately.


<img width="1312" alt="Screen Shot 2022-11-02 at 3 30 21 PM" src="https://user-images.githubusercontent.com/387249/199615022-3e32c94a-1834-4532-84e4-4a8b996e80e1.png">

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version:

```
Brave 1.47.167 Chromium: 109.0.5414.80 (Official Build) (64-bit)
Revision 0f69b168d36a06cace4365e9f029fa987afa5633-refs/branch-heads/5414@{https://github.com/brave/brave-browser/issues/1178}
OS Android 12; Build/SP1A.210812.016
```

1. installed 1.47.x 
2. launched Brave
3. loaded `https://brave.com/?vgo_ee=1234`
4. looked at the URL bar

- Ensured that `vgo_ee` is removed from query string 
- Ensured that `brave.com` loads successfully

https://user-images.githubusercontent.com/17885425/211424638-f1f20a9c-ca3b-4d49-817e-715874971e09.mp4
