### ISSUE TITLE
"You can switch between Brave profiles here" message has Chrome-blue background

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#26290]
## Description 

"You can switch between Brave profiles here" message has Chrome-blue background

(This is essentially just https://github.com/brave/brave-browser/issues/24466 again.)

## Steps to Reproduce

   1. install `1.47.19`
   2. launch Brave
   3. click on the `"hamburger"` menu
   4. click `Create Profile`
   5. type `Profile 2` and click `Done`
   6. wait
   7. notice the background color of the profile button's messaging

## Actual result:

<img width="1312" alt="Screen Shot 2022-10-26 at 11 14 59 AM" src="https://user-images.githubusercontent.com/387249/198104378-9f90dde7-b36d-4d99-8736-fb9a1b84e4a4.png">

## Expected result:

Should be white (`Light` theme) or black/dark gray (`Dark` theme)

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.47.19 Chromium: 107.0.5304.68 (Official Build) nightly (x86_64)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | macOS Version 11.7.1 (Build 20G918)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron @LaurenWags @sangwoo108

**Comment by sangwoo108** [comment]
It seems regression selecting theme color during profile creation lead to creating custom theme. So the value isn't overriden for it. I'll move values so that it can be overridden regardless of theme.

ref. https://github.com/brave/brave-core/pull/15208#discussion_r979851404

cc. @simonhong

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.47.123 Chromium: 108.0.5359.99 (Official Build) beta (x86_64)
-- | --
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | macOS Version 13.1 (Build 22C65)

`Dark` | `Light`
-------|--------
<img width="1312" alt="Screenshot 2022-12-11 at 10 56 11 AM" src="https://user-images.githubusercontent.com/387249/206923183-36b3c3ae-7518-4efa-82cf-bcb79e060180.png"> | <img width="1312" alt="Screenshot 2022-12-11 at 10 55 07 AM" src="https://user-images.githubusercontent.com/387249/206923195-d4e5eb91-978b-490c-8229-53c692e9daff.png">
