### ISSUE TITLE
prevent the user from firing device removal multiple times

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#2629]
https://github.com/brave/brave-browser/issues/2527#issuecomment-447965917
https://github.com/brave/brave-browser/issues/2527#issuecomment-448089790

we need to prevent user from clicking remove multiple times(sending duplicated delete record) while delete record is sending under the hood. we also need to dismiss the remove modal when user click "Remove"

Test Plan:

1. have 3 devices in a sync chain
2. once devices are loaded, remove one device by clicking the X button
3. confirm removal
4. all buttons should be disabled
5. a loading spinner should show while the operation is running
6. modal should self-close once operation is completed

**Comment by cezaraugusto** [comment]
cc @rossmoody

**Comment by rossmoody** [comment]
The most up to date design spec for Sync [can be found right here.](https://docs.google.com/document/d/1gvOwHRORwg3xDQEUsWRp_WgYC0_TYc87By8v8r0isYM/edit?usp=sharing)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.59.20 Chromium: 72.0.3626.28 (Official Build) beta(64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Linux

![screenshot from 2019-01-08 13-00-28](https://user-images.githubusercontent.com/17010094/50816096-836ada80-1345-11e9-8615-2f051f42f844.png)
