### ISSUE TITLE
Two `Planet Mozilla` sources discovered, one of which can't be followed

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#26306]
## Description 

Two `Planet Mozilla` sources, one of which can't be followed

## Steps to Reproduce

   1. install `1.47.20`
   2. launch Brave
   3. open `brave://flags`
   4. toggle `brave://flags/#brave-news-v2` to `Enabled`
   5. click on `Relaunch`
   6. open a new-tab page
   7. click `Customize`
   8. click `Turn on Brave News`
   10. beneath `Discover`, enter `https://planet.mozilla.org/atom.xml`
   11. click on `Get feeds from https://planet.mozilla.org/atom.xml`
   12. confirm one `Planet Mozilla` results under `Sources`
   13. hover over and click on the `Follow` button within
   14. wait
   15. you're subscribed to `Planet Mozilla`, but with an additional non-followable source

## Actual result:

click `Follow` | result
--------------|-------
<img width="1335" alt="Screen Shot 2022-10-26 at 3 42 06 PM" src="https://user-images.githubusercontent.com/387249/198152413-0a68543b-c9a8-4cb2-b9a5-bee380c6537d.png"> | <img width="1335" alt="Screen Shot 2022-10-26 at 3 43 07 PM" src="https://user-images.githubusercontent.com/387249/198152489-8514bd98-7776-4fed-ba59-6733ed36e949.png">

## Expected result:

Should either be able to follow whatever the 2nd feed is, or it shouldn't be showing up, since we can't follow it.

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.47.20 Chromium: 107.0.5304.68 (Official Build) nightly (x86_64)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | macOS Version 11.7.1 (Build 20G918)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @fallaciousreasoning @petemill @mattmcalister

**Comment by fallaciousreasoning** [comment]
Ah, I think this is actually a UX bug. Second one is the direct feed we discovered, first one is the direct feed we subscribed to :facepalm: 

We had this working at one point but I guess it regressed. I'll take a look.

**Comment by kjozwiak** [comment]
The above requires `1.46.102` or higher for `1.46.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.46.102 Chromium: 107.0.5304.110 (Official Build) beta (64-bit)
-- | --
Revision | 2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}
OS | Windows 11 Version 21H2 (Build 22000.1219)
```

Verified using STR from https://github.com/brave/brave-core/pull/15820#issuecomment-1307972156

Confirmed I was subscribed to the Planet Mozilla feed, without duplicate sources/cards, via direct-feed search.

example|example|example|example|example
-------|--------|--------|---------|------
<img width="455" alt="image" src="https://user-images.githubusercontent.com/98358127/201395022-fc3f3839-7252-4459-a55a-f52fcac693f6.png">|<img width="454" alt="image" src="https://user-images.githubusercontent.com/98358127/201395084-9d5325a1-e297-40f7-88d3-bbda27d0e779.png">|<img width="455" alt="image" src="https://user-images.githubusercontent.com/98358127/201395130-49f89a83-4b83-439a-b19f-a5aa15d56610.png">|<img width="457" alt="image" src="https://user-images.githubusercontent.com/98358127/201395289-6d71f60e-0688-4545-b862-83f00ce33d73.png">|<img width="450" alt="image" src="https://user-images.githubusercontent.com/98358127/201395778-c480b65b-6b86-4d64-814d-8f2e05ee351d.png">
