### ISSUE TITLE
Backspacing after searching for non-existent feed source seems to "hang" search

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#26308]
## Description 

Backspacing after searching for non-existent feed source seems to "hang" search

## Steps to Reproduce

   1. install `1.47.20`
   2. launch Brave
   3. open `brave://flags`
   4. set `brave://flags/#brave-news-v2` to `Enabled`
   5. open a new-tab page
   6. click on `Customize`
   7. click on `Brave News`
   8. click on `Turn on Brave News`
   9. type `https://brave.com`
   10. click on the `Get feeds from https://brave.com`
   11. now, backspace/delete the `m`
   12. wait...

## Actual result:

step 9 | step 10 | step 11
-----|-----|-----
<img width="1312" alt="Screen Shot 2022-10-26 at 4 10 31 PM" src="https://user-images.githubusercontent.com/387249/198155623-4a2ebf49-20a8-4d1d-9720-dc0dec923b4b.png"> | <img width="1312" alt="Screen Shot 2022-10-26 at 4 10 35 PM" src="https://user-images.githubusercontent.com/387249/198155624-5af54b36-dd09-4dff-8ff9-51d1933b3d23.png"> | <img width="1312" alt="Screen Shot 2022-10-26 at 4 10 38 PM" src="https://user-images.githubusercontent.com/387249/198155629-af0f5930-b7a5-438f-a68c-9b138fd7285b.png">

## Expected result:

<img width="1312" alt="Screen Shot 2022-10-26 at 4 12 05 PM" src="https://user-images.githubusercontent.com/387249/198155775-ce99c408-23bf-4f25-b132-3d9096c0e7ad.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.47.20 Chromium: 107.0.5304.68 (Official Build) nightly (x86_64)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | macOS Version 11.7.1 (Build 20G918)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @fallaciousreasoning @mattmcalister

**Comment by fallaciousreasoning** [comment]
Was this fixed by https://github.com/brave/brave-core/pull/15611 or is it still happening? Just having a play around to try and repro and I'm not having too much success

**Comment by stephendonner** [comment]
> Was this fixed by [brave/brave-core#15611](https://github.com/brave/brave-core/pull/15611) or is it still happening? Just having a play around to try and repro and I'm not having too much success

Can still easily reproduce this 100% using 

Brave | 1.47.33 Chromium: 107.0.5304.91 (Official Build) nightly (x86_64)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | macOS Version 11.7.1 (Build 20G918)

**Comment by fallaciousreasoning** [comment]
Okay cool, I'll dig into it a bit more

**Comment by mattmcalister** [comment]
Reducing priority on this. Yes, it's odd behavior, but it's very minor. Not closing it yet but not prioritizing it atm.

**Comment by fallaciousreasoning** [comment]
Does this still repro in latest Nightly? I had a quick go in 1.55.5 Chromium: 115.0.5790.32 (Official Build) nightly (64-bit) (Linux) and it seemed to be fine.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.58.78 Chromium: 116.0.5845.51 (Official Build) nightly (x86_64)
-- | --
Revision | ca260d83d1ffda3cb35bff4bdc3251f30f9c8ccd
OS | macOS Version 11.7.9 (Build 20G1426)

Used my steps to reproduce from https://github.com/brave/brave-browser/issues/26308#issue-1424802948.

### Confirmed pressing `delete` / `backspace` doesn't "hang" the search UI, and it updates dynamically

![news-fixed](https://github.com/brave/brave-browser/assets/387249/2334bfa6-dc39-4349-ac6f-6cfde4b3b845)
