### ISSUE TITLE
`Top Sources'` feeds appear to be followed, still, after unfollowing them

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#26303]
## Description 

Top Sources' feeds appear to be followed, still, after unfollowing them

## Steps to Reproduce

   1. install `1.47.20`
   2. launch Brave
   3. set `brave://flags/#brave-news-v2` to `Enabled`
   4. click on `Relaunch`
   5. open a new-tab page
   6. click on `Customize`
   7. click on `Brave News`
   8. click on `Turn on Brave News`
   9. click `Follow` on `Cars`, under `Channels`
   10. close the `X`
   11. scroll down
   12. click on `Load new content`
   13. confirm articles from `The Drive` and `Car and Driver` loaded
   14. click `Customize`
   15. click `Unfollow` next to `Cars`
   16. click `Unfollow` next to `Top Sources`
   17. reload the Brave News feed

## Actual result:

Looks like `The Drive` and `Car and Driver` were removed, but I still see a bunch of articles, likely from `Top Sources`, which is supposed to be unfollowed

0 sources | Brave News content
-----------|--------------------
<img width="1312" alt="Screen Shot 2022-10-26 at 2 39 42 PM" src="https://user-images.githubusercontent.com/387249/198143919-a835c618-8172-43ed-9c5d-8d73e826ac52.png"> | <img width="1312" alt="Screen Shot 2022-10-26 at 2 39 38 PM" src="https://user-images.githubusercontent.com/387249/198143940-145c4257-138f-4dd5-a181-54b1a17eced4.png">

## Expected result:

As I'm following 0 sources, I don't expect content other than ads

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.47.20 Chromium: 107.0.5304.68 (Official Build) nightly (x86_64)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | macOS Version 11.7.1 (Build 20G918)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @fallaciousreasoning @petemill @mattmcalister @rebron

**Comment by kjozwiak** [comment]
The above requires `1.46.107` or higher for `1.46.x` verification 👍
