### ISSUE TITLE
Issues with adblocker

### ISSUE THREAD

**Issue by TheVampireInLoveWithTheCorpsesBlood** [brave/brave-browser#26309]
@pes10k Can you check these issues? I was the original creator, but I forgot to close them before I closed my account few days ago.

I don't want to be the creature bothering the Devs but if they are issues need to be resolved and apparently I am the only one noticing them, then I hope they get resolved, even if they seem obvious problems to me that someone else should have reported long time ago.
Since I opened this new account, I want to make sure the issues can get some attention, all I want is issues to be fixed for others, because I already fixed most with custom lists.

**They are not feature requests**, if they are meant to be that way, so be it and please close the issues. Maybe I shouldn't have posted them in the adblock-rust repo, but I can't change that, can't even close them myself.
But I want you to see what you can do about them.

[$redirect rules from brave-unbreak list not working as they should #229](https://github.com/brave/adblock-rust/issues/229) a bad but or conflict somewhere in the adblocker, and it is serious especially since it affects important rules brave-unbreak that could fix many problems.

[$redirect-rules used with $Important act as $redirect #231](https://github.com/brave/adblock-rust/issues/231) This is clearly a bug, not big and it is only available on Nightly, so it is not serious or something many people will use but it is clearly doing something it shouldn't!

[Generic cosmetics exceptions are being ignored. #230](https://github.com/brave/adblock-rust/issues/230) I don't know if this is a bug or meant to be this way, but I noticed it years ago and never knew how important it was until last days when I started to resolve adblocker detection issues myself and why there were no issues in uBlock. (if it is done this way by design please close)

Don't hate me please!

Thanks and have a good day!

**Comment by pes10k** [comment]
thanks @TheVampireInLoveWithTheCorpsesBlood, going to tag @antonok-edm and @ryanbr in, since they're the adblock-rs and filter list gurus ;)

**Comment by antonok-edm** [comment]
@TheVampireInLoveWithTheCorpsesBlood I have these on my radar, it's just been a busy few days :sweat:

For the sake of organization I'm going to close this issue and follow up on those individual issues. Thanks for the reports though, these are issues we hadn't seen in the past and reports are always extremely helpful!
