### ISSUE TITLE
NFT Gallery will not display items in portfolio

### ISSUE THREAD

**Issue by UjCbFwtBayFM** [brave/brave-browser#26317]
## Description 

NFT display gallery fails to load assets, not displaying any info.

## Steps to Reproduce

   1. Add NFT asset.
   2. Switch to NFT Gallery page
   3. 

## Actual result:

Assets do not load.
![ZSwxpmnHdn](https://user-images.githubusercontent.com/22710992/198336027-828fb7b5-8fda-4476-a257-3cf8fc32f8a7.png)
![V2V6IeE9hq](https://user-images.githubusercontent.com/22710992/198336040-6729761b-d3cd-4201-abc4-84ca13e02c17.png)
![d9S32SWrTo](https://user-images.githubusercontent.com/22710992/198336055-911e1ca9-8f8e-4eb8-b11d-f261c54eaeb2.png)

## Expected result:
Assets should load.

## Reproduces how often: 

Every time I load the NFT Gallery.

## Brave version (brave://version info)

<html>
<body>
<br class="Apple-interchange-newline">

Brave | 1.45.113 Chromium: 107.0.5304.62 (Official Build) (64-bit)
-- | --
Revision | 1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942}
OS | Windows 10 Version 21H1 (Build 19043.2006)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by UjCbFwtBayFM** [comment]
Update, Brave Nightly Version 1.48.75: no change. 
Tried re-adding them, tried re-generating wallet, still not working.

**Comment by bsclifton** [comment]
cc: @jamesmudgett

**Comment by Douglashdaniel** [comment]
cc: @muliswilliam @nvonpentz

**Comment by muliswilliam** [comment]
@UjCbFwtBayFM Which NFT are you adding?

**Comment by josheleonard** [comment]
Closing as stale. This is related to an older wallet UI
