### ISSUE TITLE
[Android] Update search engine defaults for BR / AR

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#26318]
### Description
Update search engine defaults for:

- Brazil (BR)
- Argentina (AR)

Brave should be at the top of drop down list at settings -> search engines.

Related: https://github.com/brave/brave-browser/issues/18331, https://github.com/brave/brave-browser/issues/23814 and https://github.com/brave/brave-browser/issues/26181

### Test plan
**Region set to BR / AR**

1. Fresh profile
2. Search onboarding should NOT be shown
3. Default search engine SHOULD be Brave
4. Visit settings -> search engines
5. Brave SHOULD be first in the Default search engines list

**Region set to anything else (excluding CA / DE / FR / GB / US / AT / ES / MX)**

1. Fresh profile
2. Search onboarding SHOULD be shown
3. Default will NOT be Brave Search
4. Visit settings -> search engines
5. Brave SHOULD be first in the Default search engines list - unless you're in a region where Yandex is default (AM, AZ, BY, KG, KZ, MD, RU, TJ, TM, UZ). In that case it will be second.

### Notes for test plan
https://github.com/brave/brave-browser/issues/23814#issuecomment-1195841652

**Comment by kjozwiak** [comment]
As per https://github.com/brave/brave-browser/issues/26181#issuecomment-1293746731, we basically need to change the onboarding behaviour for `BR` & `AR`. Believe we remove the `onboarding` when the user taps on the URL. We're currently displaying it.

**Comment by kjozwiak** [comment]
The above requires `1.45.121` or higher for `1.45.x` verification 👍

**Comment by Uni-verse** [comment]
In progress using the following build(s):

```
Brave	1.45.125 Chromium: 107.0.5304.110 (Official Build) (64-bit) 
Revision	2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}
OS	Android 12; Build/SP1A.210812.016
```

AR (Argentina) locale (New addition)

BR (Brazil) locale (New addition)

DE (Germany) Existing brave first SE

CO (Columbia) Existing Non-brave first SE

Yandex first SE case
