### ISSUE TITLE
[hackerone] brave:// issues

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#2631]
https://hackerone.com/bugs?report_id=464458&subject=brave

**Comment by diracdeltas** [comment]
related issue: `brave://` is loadable in incognito whereas `chrome://` is not

**Comment by fmarier** [comment]
This might get fixed by https://github.com/brave/brave-core/pull/1385.

**Comment by tomlowenthal** [comment]
@bridiver Is this now fixed to your satisfaction, or are more mitigations needed?

**Comment by bsclifton** [comment]
@bridiver @tomlowenthal @fmarier is there anything else to do on this issue?

**Comment by bridiver** [comment]
I don't know, I can't access the hackerone issue for some reason so not even sure what it is

**Comment by bridiver** [comment]
This is fixed as far as I can tell

**Comment by tomlowenthal** [comment]
Well, if you think it's fixed, that sounds good to me.
