### ISSUE TITLE
webview crashing when visiting certain websites when `Block trackers & ads` enabled

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#26311]
## Description 

Webview crashing consistently when visiting https://www.motorsport.com/f1/news/horner-mateschitz-ensured-that-red-bulls-f1-future-is-secure/10390559. Reproduced the issue on both `Win 11 x64` and `macOS 13`. Crash reports mentioned below but it doesn't look like the crashes have been symbolized:

**`Win 11 x64`**

* `Uploaded crash report ID: | 5e9b0000-c482-0f09-0000-000000000000`
* `Uploaded crash report ID: | 5b9b0000-c482-0f09-0000-000000000000`
* `Uploaded crash report ID: | 589b0000-c482-0f09-0000-000000000000`

**`macOS 13 x64`**

* `Uploaded crash report ID: | c1920000-c482-0f09-0000-000000000000`
* `Uploaded crash report ID: | c09e0000-c482-0f09-0000-000000000000`

## Steps to Reproduce

   1. download/install `1.47.22 Chromium: 107.0.5304.68`
   2. ensure that the shield is enabled and `Block trackers & ads` is selected (default value)
   3. visit https://www.motorsport.com/f1/news/horner-mateschitz-ensured-that-red-bulls-f1-future-is-secure/10390559
   4. if it doesn't crash the webview the first time around, refresh the page several times

The above is also reproducible when loading https://www.youtube.com.

## Actual result:

https://user-images.githubusercontent.com/2602313/198231481-6942ef41-07fa-4914-afb2-74dbbadb5df6.mp4

## Expected result:

Brave shouldn't be crashing the webview

## Reproduces how often: 

100% reproducible using the STR/Cases mentioned above.

## Brave version (brave://version info)

```
Brave | 1.47.22 Chromium: 107.0.5304.68 (Official Build) nightly (64-bit)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | Windows 11 Version 22H2 (Build 22621.675)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Couldn't reproduce with 1.45.113 Chromium: 107.0.5304.62`
- Can you reproduce this issue with the beta channel? `Couldn't reproduce with 1.46.80 Chromium: 107.0.5304.68`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `Yes, the issue is fixed when disabling shields`
- Does the issue resolve itself when disabling Brave Rewards? `Not related to rewards, related to shields being enabled`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.47.108 Chromium: 108.0.5359.71 (Official Build) beta (64-bit)
-- | --
Revision | 1e0e3868ee06e91ad636a874420e3ca3ae3756ac-refs/branch-heads/5359@{#1016}
OS | Windows 10 Version 21H2 (Build 19044.2251)

```
Verified the STR from the description and ensured webview doesn't crash when loading the following sites several times
https://www.motorsport.com/f1/news/horner-mateschitz-ensured-that-red-bulls-f1-future-is-secure/10390559
https://www.youtube.com/
