### ISSUE TITLE
aeroplan.rewardops.com gives 404 until you allow all fingerprinting

### ISSUE THREAD

**Issue by pilgrim-brave** [brave/brave-browser#26325]
Reported by @ryanbr 

Appears to be related to our HTTP header farbling.

**Comment by LaurenWags** [comment]
@pes10k @pilgrim-brave since this has `QA/Yes`, a test plan is needed. 

Marking as `QA/Blocked` until there is one.

cc @kjozwiak @rebron

**Comment by pes10k** [comment]
@LaurenWags i think the test is to just go to aeroplan.rewardops.com with shields up and see if the page loads correctly.  If so, then test passes

**Comment by LaurenWags** [comment]
Thanks @pes10k - not being familiar with this one, didn't want to make any assumptions.

**Comment by pes10k** [comment]
No stress at all :)

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.47.121 Chromium: 108.0.5359.99 (Official Build) beta (x86_64)
-- | --
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | macOS Version 13.1 (Build 22C65)

### Steps:
1. installed `1.47.121`
2. launched Brave
3. opened `https://aeroplan.rewardops.com/`

#### Confirmed I could load `aeroplan.rewardops.com` with default `Block fingerprinting` Shields enabled

`1.46.141` | `1.47.121`
-----------|---------
<img width="1312" alt="Screenshot 2022-12-10 at 1 29 46 PM" src="https://user-images.githubusercontent.com/387249/206876027-6be96b60-4cbc-4645-9198-dfd10a268d64.png"> | <img width="1312" alt="Screenshot 2022-12-10 at 1 29 54 PM" src="https://user-images.githubusercontent.com/387249/206876031-a5b65196-c854-4bbc-a588-c775a7a66b6f.png">
