### ISSUE TITLE
Icon is missing from Brave notification ads after macOS upgrade

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#26323]
## Steps to Reproduce

   1. Install Brave
   2. Join Rewards
   3. Upgrade macOS

## Actual result:

Notification ads do not have the Brave icon

## Expected result:
Notification ads should have the Brave icon

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
Could be this upstream issue per @tmancey 

https://bugs.chromium.org/p/chromium/issues/detail?id=1379743&q=mac%20icon%20notification&can=2

**Comment by tmancey** [comment]
Closing as an upstream issue
