### ISSUE TITLE
Do not assume selectedNetwork to be ETH mainnet

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#26320]
When initialising the Redux state, we populate `selectedNetwork` with ETH mainnet information. See code: https://github.com/brave/brave-core/blob/c06dc72392ae38276a7282b040fa820d460f933f/components/brave_wallet_ui/common/reducers/wallet_reducer.ts#L57-L69

This is a bad assumption for various reasons, but it also causes the wallet to fetch balances, prices, tokens, for ETH mainnet while the real selectedNetwork is refreshed from the backend.

This issue is about changing its type to `BraveWallet.NetworkInfo | undefined` and refactoring the whole codebase to work with this new type.

**Comment by yrliou** [comment]
@onyb Is it related to https://github.com/brave/brave-browser/issues/26226?
