### ISSUE TITLE
Pre-followed sources should reflect `Follow`ed status in the `Customize` dialog

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#26324]
## Description 

Pre-followed sources should reflect `Follow`ed status in the `Customize` dialog

## Steps to Reproduce

   1. install `1.47.21`
   2. launch Brave
   3. set `brave://flags/#brave-news-v2` to `Enabled`
   4. set `brave://flags/#brave-news-subscribe-button` to `Enabled`
   5. click `Relaunch`
   6. load `theatlantic.com`
   7. click on the `Manage Subscriptions` icon in the URL bar
   8. notice that `The Atlantic` feed is followed
   9. click `Manage Feeds >`
   10. look for `The Atlantic`

## Actual result:

URL bar | `Customize` dialog
--------|---------------------
<img width="1312" alt="Screen Shot 2022-10-27 at 12 52 16 PM" src="https://user-images.githubusercontent.com/387249/198386999-cc2714d3-0595-4ed1-bd7f-35472ca9f311.png"> | <img width="1312" alt="Screen Shot 2022-10-27 at 12 52 32 PM" src="https://user-images.githubusercontent.com/387249/198387014-64c931be-ceb2-43f0-9327-6906a3b9b903.png">

## Expected result:

`The Atlantic` should should as already being followed

<img width="1088" alt="Screen Shot 2022-10-27 at 1 04 26 PM" src="https://user-images.githubusercontent.com/387249/198387447-1236b643-335a-4c17-a5b4-9e00a95153f2.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.47.21 Chromium: 107.0.5304.68 (Official Build) nightly (x86_64)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | macOS Version 11.7.1 (Build 20G918)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @aguscruiz @mattmcalister @fallaciousreasoning @petemill

**Comment by petemill** [comment]
This is related to https://github.com/brave/brave-browser/issues/26631 and adds an extra layer about follows being added from completely outside the current NTP instance and further underlining the need to have an event get fired.

**Comment by fallaciousreasoning** [comment]
So I think this is actually separate to #26631 - this is an issue with the migration from V1 to V2, `The Atlantic` was default enabled in V1 and the subscribe dialog reflects that default enabled status.

**Comment by LaurenWags** [comment]
Requires `1.46.122` or higher to test.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.46.122 Chromium: 108.0.5359.48 (Official Build) beta (x86_64)
-- | --
Revision | 18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}
OS | macOS Version 11.7.1 (Build 20G918)


### Steps:
1. installed `1.46.122`
2. launched Brave
3. opened `brave://flags`
4. set `brave://flags/#brave-news-subscribe-button` to `Enabled`
5. clicked `Relaunch`
6. opened a new-tab page
7. clicked on `Customize`
8. clicked on `Brave News`
9. clicked on `Turn on Brave News`
10. confirmed I was default following `Top Sources`, in the `Following` column
11. loaded `theatlantic.com`
12. clicked on the `Manage Subscriptions` button
13. examined the `The Atlantic` and `Best of the Atlantic feeds` statuses

#### Confirmed neither `The Atlantic` nor `Best of the Atlantic` were `Followed`/shown as `Followed`

example | example | example
----|----|----
<img width="1176" alt="Screen Shot 2022-11-21 at 10 56 57 PM" src="https://user-images.githubusercontent.com/387249/203246127-83345cf5-20a6-4b75-8d77-301e0cf9d0e7.png"> | <img width="1176" alt="Screen Shot 2022-11-21 at 10 55 49 PM" src="https://user-images.githubusercontent.com/387249/203246111-be680ec2-b9ab-4ea9-957e-63c52d123943.png"> | <img width="1176" alt="Screen Shot 2022-11-21 at 10 55 58 PM" src="https://user-images.githubusercontent.com/387249/203246121-489ade05-8667-4bbb-b870-aacfd24fbf5f.png">
