### ISSUE TITLE
Brave News crashes when loading https://www.pravda.com.ua/eng/news/ with v2 enabled

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#26321]
## Description 

Brave News crashes when loading https://www.pravda.com.ua/eng/news/ with v2 enabled

## Steps to Reproduce

   1. install `1.47.21`
   2. launch Brave
   3. set `brave://flags/#brave-news-v2` to `Enabled`
   4. set `brave://flags/#brave-news-subscribe-button` to `Enabled`
   5. click `Relaunch`
   6. load `https://www.pravda.com.ua/eng/news/`

## Actual result:

Crashes 100%, here:

```
[ 00 ] 0x7fff203fe91e
[ 01 ] 0x7fff20382406
[ 02 ] std::__terminate(void (*)()) ( cxa_handlers.cpp:59 )
[ 03 ] std::terminate() ( cxa_handlers.cpp:92 )
[ 04 ] base::internal::Invoker<base::internal::BindState<brave_news::(anonymous namespace)::ParseFeedDataOffMainThread(GURL const&, std::Cr::basic_string<char, std::Cr::char_traits<char>, std::Cr::allocator<char>> const&, base::OnceCallback<void (absl::optional<brave_news::FeedData>)>)::$_0, GURL, std::Cr::basic_string<char, std::Cr::char_traits<char>, std::Cr::allocator<char>>>, absl::optional<brave_news::FeedData> ()>::RunOnce(base::internal::BindStateBase*) ( cxx.cc:131 )
[ 05 ] void base::internal::ReturnAsParamAdapter<absl::optional<brave_news::FeedData>>(base::OnceCallback<absl::optional<brave_news::FeedData> ()>, std::Cr::unique_ptr<absl::optional<brave_news::FeedData>, std::Cr::default_delete<absl::optional<brave_news::FeedData>>>*) ( callback.h:145 )
[ 06 ] base::internal::Invoker<base::internal::BindState<void (*)(base::OnceCallback<bool ()>, std::Cr::unique_ptr<bool, std::Cr::default_delete<bool>>*), base::OnceCallback<bool ()>, base::internal::UnretainedWrapper<std::Cr::unique_ptr<bool, std::Cr::default_delete<bool>>>>, void ()>::RunOnce(base::internal::BindStateBase*) ( bind_internal.h:514 )
[ 07 ] base::(anonymous namespace)::PostTaskAndReplyRelay::RunTaskAndPostReply(base::(anonymous namespace)::PostTaskAndReplyRelay) ( callback.h:0 )
[ 08 ] base::internal::Invoker<base::internal::BindState<void (*)(base::(anonymous namespace)::PostTaskAndReplyRelay), base::(anonymous namespace)::PostTaskAndReplyRelay>, void ()>::RunOnce(base::internal::BindStateBase*) ( bind_internal.h:514 )
[ 09 ] base::internal::TaskTracker::RunSkipOnShutdown(base::internal::Task&, base::TaskTraits const&, base::internal::TaskSource*, base::SequenceToken const&) ( callback.h:145 )
[ 10 ] base::internal::TaskTracker::RunAndPopNextTask(base::internal::RegisteredTaskSource) ( task_tracker.cc:638 )
[ 11 ] base::internal::WorkerThread::RunWorker() ( worker_thread.cc:448 )
[ 12 ] base::internal::WorkerThread::RunPooledWorker() ( worker_thread.cc:335 )
[ 13 ] base::internal::WorkerThread::ThreadMain() ( worker_thread.cc:315 )
[ 14 ] base::(anonymous namespace)::ThreadFunc(void*) ( platform_thread_posix.cc:102 )
[ 15 ] 0x7fff2042d8fc
[ 16 ] 0x7fff20429443
```

## Expected result:

No crash, and the website loads

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.47.21 Chromium: 107.0.5304.68 (Official Build) nightly (x86_64)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | macOS Version 11.7.1 (Build 20G918)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @fallaciousreasoning @mattmcalister @rebron

**Comment by fallaciousreasoning** [comment]
Wow - that is not good :fearful:

**Comment by fallaciousreasoning** [comment]
This was being caused by a non-UTF-8 RSS feed getting passed to the Rust string constructor, which was causing a panic. This bug would be triggered in Brave News V1 too (but it's much more visible now).

**Comment by kjozwiak** [comment]
The above requires `1.46.91` or higher for `1.46.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.46.91 Chromium: 107.0.5304.91 (Official Build) dev (x86_64)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | macOS Version 11.7.1 (Build 20G918)

### Steps:

1. launch Brave
2. set `brave://flags/#brave-news-v2` to `Enabled`
3. set `brave://flags/#brave-news-subscribe-button` to `Enabled`
4. click `Relaunch`
5. load `https://www.pravda.com.ua/eng/news/`
6. clicked on the `Manage Subscriptions` icon in the URL bar
7. subscribed to all (8) of the feeds
8. scrolled Brave News

#### Confirmed I saw articles from Pravda

example | example | example | example | example
---------|----------|---------|----------|---------
<img width="1312" alt="Screen Shot 2022-11-03 at 8 58 01 AM" src="https://user-images.githubusercontent.com/387249/199772112-5d0a934f-20f7-4ad4-b0a6-1df07d890414.png"> | <img width="1312" alt="Screen Shot 2022-11-03 at 8 58 15 AM" src="https://user-images.githubusercontent.com/387249/199772115-c9dea8e3-0ce5-46b0-900b-1f7613a6d9bd.png"> | <img width="1312" alt="Screen Shot 2022-11-03 at 8 59 12 AM" src="https://user-images.githubusercontent.com/387249/199772117-0d160749-1d41-4b64-956a-0faa4ab51b60.png"> | <img width="1312" alt="Screen Shot 2022-11-03 at 8 59 22 AM" src="https://user-images.githubusercontent.com/387249/199772123-64699e0c-768a-47c4-99c0-043a5f86a2ee.png"> | <img width="1312" alt="Screen Shot 2022-11-03 at 9 00 40 AM" src="https://user-images.githubusercontent.com/387249/199772126-050fc97e-f95b-4097-b590-d80e238e0411.png">
