### ISSUE TITLE
`Upload device` tile do not show  same image as the background when Dashboard closed re-opened

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#26335]
## Description 

Not sure if this is expected but I am expecting `Upload from device` tile image should match to the image on the background when Dashboard opened

## Steps to Reproduce

   1. Install 1.46.81
   2. launch Brave
   3. click `Customize`
   4. click `Upload from device`
   5. upload few custom images
   6. close and reopen Dashboard

## Actual result:

`Upload from device` tile shows grey

step 5|result
---|----
<img width="456" alt="image" src="https://user-images.githubusercontent.com/98358127/198419871-c48e6a28-484c-445f-85ed-ab3cfc85399f.png">|<img width="461" alt="image" src="https://user-images.githubusercontent.com/98358127/198419926-466aea06-abeb-458d-8f9f-f7291cf3522c.png">

## Expected result:
Expected the `Upload from device` tile image match to the background image

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (64-bit)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | Windows 11 Version 21H2 (Build 22000.1098)
```
## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel?  yes
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@sangwoo108 @rebron

**Comment by sangwoo108** [comment]
@rebron @aguscruiz I'd like to hear about this. I thought it'd be more recognizable with the upload icon than the acutal image that was chosen. What do you think?

**Comment by aguscruiz** [comment]
Design added here: https://www.figma.com/file/FMuS3IZbzqzQTyRHz42Oix/Desktop-NTP?node-id=2661%3A69546

![image](https://user-images.githubusercontent.com/15734630/198591737-f35aa042-d3a1-444c-959f-77c9ab96eb7c.png)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.47.126 Chromium: 108.0.5359.99 (Official Build) beta (64-bit)
-- | --
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | Windows 11 Version 21H2 (Build 22000.1219)
```

- Install 1.46.81
- launch Brave

Case 1: No custom images are available
<details>

- click `Customize` in a new-tab
- do not upload any images

#### Confirmed `Upload from device` icon is available in the `Customize Dashboard` when no custom images are available

<img width="453" alt="image" src="https://user-images.githubusercontent.com/98358127/207464015-bf73c5b4-bd74-4218-821b-d9ef6ef4563c.png">
</details>

Case 2: Single custom image
<details>

1. continue from Case 1:
      - No custom images are available in the `Customize Dashboard`
2. click `Upload from device` tile
3. Upload a single custom image
4. click on the image in the `Use your own` tile
5. uploaded image thumbnail along with `Upload from device` tile are displayed
6. click `Use your own`
7. close the dashboard and reopen

#### Confirmed a single custom image is displayed in the `Use your own` tile

step 1|step5|result
---|----|----
<img width="453" alt="image" src="https://user-images.githubusercontent.com/98358127/207464015-bf73c5b4-bd74-4218-821b-d9ef6ef4563c.png">|<img width="457" alt="image" src="https://user-images.githubusercontent.com/98358127/207464439-58256cf1-c4f0-422e-a81a-efb77855306e.png">|<img width="453" alt="image" src="https://user-images.githubusercontent.com/98358127/207468586-7d0b9c88-190e-49d3-9ec0-bc7299ba299b.png">

</details>

Case 3: Two custom images 
<details>

1. Continue from Case 2:
    - a single image already uploaded
    - `Upload from device` tile is available
2. click `Upload from device` tile
3. upload an image
4. click on the image in the `Use your own` tile
5. uploaded image thumbnail along with `Upload from device` tile are displayed
6. click `Use your own`
7. close the dashboard and reopen

#### Confirmed both images are shown in the `Use your own` tile

step 1|step 5|result
---|----|---
<img width="451" alt="image" src="https://user-images.githubusercontent.com/98358127/207468689-c1a4cbec-e18d-4798-9caa-4a59dd525ee2.png">|<img width="452" alt="image" src="https://user-images.githubusercontent.com/98358127/207464694-7dd12802-919d-4ea9-a6df-fb79caf513c0.png">|<img width="451" alt="image" src="https://user-images.githubusercontent.com/98358127/207464755-dd832a15-9098-4c4f-a520-95d805a8f820.png">

</details>

Case 4: Three  custom images 
<details>

1. Continue from Case 3:
    - two images already uploaded
    - `Upload from device` tile is available
2. click `Upload from device` tile 
3. upload an image
4. click on the image in the `Use your own` tile
5. uploaded image thumbnail along with `Upload from device` tile are displayed
6. click `Use your own`
7. close the dashboard and reopen

#### Confirmed all three images are shown in the `Use your own` tile

step 1|step 5|result
---|----|----
<img width="453" alt="image" src="https://user-images.githubusercontent.com/98358127/207465105-f85ca898-f20a-4594-ae49-2c44a08798b8.png">|<img width="452" alt="image" src="https://user-images.githubusercontent.com/98358127/207465143-3f369bc1-efe9-44b2-bdf0-bac480df13d0.png">|<img width="454" alt="image" src="https://user-images.githubusercontent.com/98358127/207465175-1d592154-8748-428d-bc74-375254bf416e.png">
</details>

Case 5: Four  images 
<details>

1. Continue from Case 4:
      - three images already uploaded
      - `Upload from device` tile is available
2. click `Upload from device` tile
3. upload an image
4.  click on the image in the `Use your own` tile
5. uploaded image thumbnail along with `Upload from device` tile are displayed
6. click `Use your own` 
7. close the dashboard and reopen

#### Confirmed all four images are shown in the `Use your own` tile

step 1|step 5|result
---|----|----
<img width="449" alt="image" src="https://user-images.githubusercontent.com/98358127/207465410-04817378-abd4-489d-9fb1-ee6096740a55.png">|<img width="455" alt="image" src="https://user-images.githubusercontent.com/98358127/207465437-f292a9b7-ac73-409f-98ce-f4ece7bb9731.png">|<img width="456" alt="image" src="https://user-images.githubusercontent.com/98358127/207465491-2159c315-0b7b-4dba-98a6-beec64376b99.png">
</details>

Case 6: Five custom images 
<details>

1. Continue from Case 5:
    - four images already uploaded
    - `Upload from device` tile is available
2. click `Upload from device` tile
3. upload an image
4. uploaded image thumbnail along with `Upload from device` tile are displayed
5. click `Use your own`
6. close the dashboard and reopen

#### Confirmed only at most four images are shown in the `Use your own` tile
#### Confirmed all five images are shown after closing and reopening dashboard

step 1|step 5|result|result
---|----|----|------
<img width="450" alt="image" src="https://user-images.githubusercontent.com/98358127/207465995-320121b7-f660-4fb3-86a6-0c81671be5b1.png">|<img width="453" alt="image" src="https://user-images.githubusercontent.com/98358127/207466019-f2a0a6cf-1740-4509-a42a-0e88c3ed04f0.png">|<img width="452" alt="image" src="https://user-images.githubusercontent.com/98358127/207466049-b8ba9a93-4987-42ce-a379-af877cecd928.png">|<img width="455" alt="image" src="https://user-images.githubusercontent.com/98358127/207473162-b1b80ab8-ae9e-4a62-af7e-214e19980c02.png">
</details>
