### ISSUE TITLE
Remove "Restore" tab from Manage Brave Rewards section

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#26338]
## Description

Remove "Restore" tab from Manage Brave Rewards section. 

![image](https://user-images.githubusercontent.com/11497541/198431112-b7dc37fe-7d70-4aa1-917e-28d69ecac343.png)

cc: @szilardszaloki

**Comment by emerick** [comment]
@Miyayes Just confirming that the `View QR Code` feature (bottom of the Restore tab) goes away too?

**Comment by Miyayes** [comment]
@emerick Yes, that also goes away.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.47.114 Chromium: 108.0.5359.94 (Official Build) beta (x86_64)
-- | --
Revision | 713576b895246504ccc6b92c2fb8ce2d60194074-refs/branch-heads/5359_71@{#3}
OS | macOS Version 12.6.1 (Build 21G217)
```

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy GS 21` & `Samsung Galaxy Tab S7` on the following version(s):

```
Brave	1.47.161 Chromium: 109.0.5414.61 (Official Build) beta (64-bit) 
Revision	846c6eff1c374cde417a9cdc44193545cc07f354-refs/branch-heads/5414@{#1030}
OS	Android 12; Build/SP1A.210812.016
```
- Verified user is able to join brave rewards
- Verified brave://rewards page has not regressed

Example | Example
-|-
![screenshot-1672855552647](https://user-images.githubusercontent.com/17885425/210621201-bc01ada2-a6ee-44c9-b897-3c4dcec9810f.png) | ![screenshot-1672855667255](https://user-images.githubusercontent.com/17885425/210621204-fa5a112e-ea41-44d5-8562-1046cd11b8cc.png)
