### ISSUE TITLE
Migrated `Followed` feed source doesn't display in v2

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#26339]
## Description 

Migrated `Followed` feed source doesn't display in v2

## Steps to Reproduce

   1. install `1.47.25`
   2. launch Brave
   3. open a new-tab page
   4. click on `Customize`
   5. click on `Brave News`
   6. type `https://www.rt.com/rss-feed/` into `Feed URL`
   7. click `Add source`
   8. close the dialog
   9. scroll down
   10. click on `Show Brave News`
   11. scroll more
   12. confirmed I saw an `RT.com - Daily news` article
   13. opened `brave://flags`
   14. set `brave://flags/#brave-news-v2` to `Enabled`
   15. clicked on `Relaunch`
   16. scrolled a lot
   17. looked for `RT.com - Daily news`

## Actual result:

Couldn't find any `RT.com - Daily news` articles any longer, post-migration

## Expected result:

Should be at least a couple `RT.com - Daily news` articles appearing in the feed

example | example
---------|---------
<img width="1312" alt="Screen Shot 2022-10-27 at 6 41 31 PM" src="https://user-images.githubusercontent.com/387249/198447344-ec9b02ed-b19e-4058-a313-f0c3df34c1b3.png"> | <img width="1312" alt="Screen Shot 2022-10-27 at 6 44 28 PM" src="https://user-images.githubusercontent.com/387249/198447347-5f00c5ef-921b-4cb4-8d26-c9e8647a806a.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.47.25 Chromium: 107.0.5304.68 (Official Build) nightly (x86_64)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | macOS Version 11.7.1 (Build 20G918)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @fallaciousreasoning @mattmcalister @petemill

**Comment by fallaciousreasoning** [comment]
Nice find!

**Comment by kjozwiak** [comment]
The above requires `1.46.90` or higher for `1.46.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.46.91 Chromium: 107.0.5304.91 (Official Build) dev (x86_64)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | macOS Version 11.7.1 (Build 20G918)

### Steps:

1. install `1.46.91`
2. launch Brave
3. open a new-tab page
4. click on `Customize`
5. click on `Brave News`
6. type `https://www.rt.com/rss-feed/` into `Feed URL`
7. click `Add source`
8. close the dialog
9. scroll down
10. click on `Show Brave News`
11. scroll more
12. confirmed I saw an `RT.com - Daily news article`
13. opened `brave://flags`
14. set `brave://flags/#brave-news-v2` to `Enabled`
15. clicked on `Relaunch`
16. scrolled
17. looked for `RT.com - Daily news`

#### Confirmed I successfully migrated the `RT.com - Daily news` feed from `v1` to `v2`

`v1` | `v2`a | `v2`b
----|------|------
<img width="1312" alt="Screen Shot 2022-11-03 at 8 49 33 AM" src="https://user-images.githubusercontent.com/387249/199769548-06935144-c318-4a22-9d13-65988be80294.png"> | <img width="1312" alt="Screen Shot 2022-11-03 at 8 50 14 AM" src="https://user-images.githubusercontent.com/387249/199769561-3cb81cac-d8f5-4aef-8349-b86b2d28d842.png"> | <img width="1312" alt="Screen Shot 2022-11-03 at 8 50 21 AM" src="https://user-images.githubusercontent.com/387249/199769569-d036af61-60f3-44cf-b534-7561246cc1da.png">
