### ISSUE TITLE
Refresh on every new tab should be toggled OFF when all custom images are deleted

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#26337]
## Description 

Not sure if it is expected functionality but I think `Refresh on every new tab` should be toggled `OFF` when all custom images are deleted to prevent grey page loading

## Steps to Reproduce

1. Install 1.46.81
2. launch Brave
3. click `Customize`
4. click `Upload from device`
5. upload few custom images
6. toggle `ON ` `Refresh on every new tab`
7. delete  all of the images
8. refresh the page

## Actual result:

Grey color NTP loaded

https://user-images.githubusercontent.com/98358127/198423166-2de8f33f-d985-4a32-9d40-9a38f2c53d02.mp4

## Expected result:
`Refresh on every new tab` should be toggled `OFF` when all custom images are deleted to prevent grey page loading

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (64-bit)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | Windows 11 Version 21H2 (Build 22000.1098)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release?  N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@rebron @sangwoo108

**Comment by sangwoo108** [comment]
The expected behavior would be reset background to "Random brave background" which is the default background. There's a bug for this behavior and it wasn't reset to it and remained to use "Custom background image" even when there's no custom image.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.47.126 Chromium: 108.0.5359.99 (Official Build) beta (64-bit)
-- | --
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | Windows 11 Version 21H2 (Build 22000.1219)
```

Steps: 

- Install 1.47.126
- launch Brave
- click Customize
- click Upload from device
- upload few custom images
- toggle ON Refresh on every new tab
- delete all of the images
- click `Use your own` 

#### Confirmed `Refresh on every new tab` is toggled `Off` when all custom images are deleted 
#### Confirmed "Brave backgrounds" is selected.


https://user-images.githubusercontent.com/98358127/207454572-e26e12e2-1683-4d15-a709-7e4b17d3c00d.mp4
