### ISSUE TITLE
NFTs added before image support do not show icons on portfolio list and NFT tab

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#26343]
### Portfolio - Icons not loading
![Image](https://user-images.githubusercontent.com/48117473/198510892-911f6720-13f0-48f9-a2ec-55f468f6ed10.png)

### NFT Tab - Showing placeholder image
![Image](https://user-images.githubusercontent.com/48117473/198510891-985ba99a-6c8c-4779-8c1f-a76ff4715a7c.png)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.47.164 Chromium: 109.0.5414.74 (Official Build) (64-bit)
-- | --
Revision | `e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}`
OS | Linux

- Verified steps from [brave/brave-core#15730](https://github.com/brave/brave-core/pull/15730)
- Verified NFT image is shown on details screen and in portfolio screen

---------------------

Verification passed on 

Brave | 1.47.164 Chromium: 109.0.5414.74 (Official Build) (64-bit)
-- | --
Revision | `e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#15730](https://github.com/brave/brave-core/pull/15730)
- Verified NFT image is shown on details screen and in portfolio screen

---------------------

Verification passed on 

Brave | 1.47.164 Chromium: 109.0.5414.74 (Official Build) (arm64)
-- | --
Revision | `e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#15730](https://github.com/brave/brave-core/pull/15730)
- Verified NFT image is shown on details screen and in portfolio screen
