### ISSUE TITLE
Monthly case show the text as "Tip Amount"

### ISSUE THREAD

**Issue by sujitacharya2005** [brave/brave-browser#26348]
## Description 

1. Set monthly tip
2. In Confirmation screen show "Tip Amount"
3. Instead of One-time tip Amount.

## Steps to Reproduce

1. Set monthly tip
2. In Confirmation screen show "Tip Amount"
3. Instead of One-time tip Amount.

## Actual result:

![Screenshot_20221028_153527](https://user-images.githubusercontent.com/32419898/198573007-32d3e7f7-e0c6-404d-ab45-28862dca33c7.png)

## Expected result:
![Screenshot_20221028_163007](https://user-images.githubusercontent.com/32419898/198572519-a779d4bc-add6-4fee-a159-e3c60c12ce44.png)

## Reproduces how often: 

Easily reproduced

## Brave version (info found on brave://version)

1.47.25

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
Closing as this was addressed and fixed by https://github.com/brave/brave-core/pull/15687.

**Comment by kjozwiak** [comment]
The above requires `1.46.109` or higher for `1.46.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Galaxy Tab A7 version 12` running `Bravemonoarm64.apk_1.46.109`

- Ensured that `Tip amount`  text is shown in the monthly tip confirmation screen

One time tip | Monthly tip
---------------|------------
![Screenshot_20221114-231633_Brave - Beta](https://user-images.githubusercontent.com/38657976/201731031-450b6c3f-0988-4dba-8190-d7f08af358ba.jpg) | ![Screenshot_20221114-231706_Brave - Beta](https://user-images.githubusercontent.com/38657976/201731082-385b6b17-e848-4298-9ab3-ce853757556d.jpg)
