### ISSUE TITLE
Blocks AWS console when creating lambdas

### ISSUE THREAD

**Issue by Northshoot** [brave/brave-browser#2634]
## Description 

AWS console create lambda is broken.

## Steps to Reproduce

   1. Go to AWS
   2. Select and follow steps to create lambda
   3. Fill in all details
   4. Press create function

## Actual result:

Getting notificartion Network error

## Expected result:
Created lambda function

## Reproduces how often: 

Every time

## Brave version (brave://version info)

Brave | 0.60.2 Chromium: 71.0.3578.98 (Official Build) dev (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Mac OS X
JavaScript | V8 7.1.302.31
Flash | (Disabled)
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
Yes
- Is the issue reproducible on the latest version of Chrome? 
No

**Comment by Northshoot** [comment]
Any updated on this? Now AWS is releasing new UI version and that gives continues errors making the site unusable with Brave :/

**Comment by ryanbr** [comment]
Sorry for the lack of updates @Northshoot  Is this still causing an issue?
