### ISSUE TITLE
RSS Autodiscovery popup bugs

### ISSUE THREAD

**Issue by mattmcalister** [brave/brave-browser#26352]
## Description 

1. Incorrect icon showing in address bar when visiting a site that is _not_ in the sources list
2. Empty follow button when not following a feed until you mouseover the button
3. Sometimes the icon doesn't appear at all

## Steps to Reproduce
   1. Visit theregister.com
   4. Click the old RSS autodiscovery icon
   5. Mouseover the follow buttons
   6. Visit infoworld.com or towardsdatascience.com
   7. No RSS autodiscovery icon
   8. View page source to find the RSS feed

## Example
![image](https://user-images.githubusercontent.com/71029/198614294-5f331835-5112-4a08-833b-95b0e1bba897.png)

**Comment by stephendonner** [comment]
@fallaciousreasoning @petemill can we please get this uplifted to 1.46.x?

**Comment by kjozwiak** [comment]
The above requires `1.46.97` or higher for `1.46.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.46.97 Chromium: 107.0.5304.91 (Official Build) beta (x86_64)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | macOS Version 13.1 (Build 22C5033e)

### Steps:

1. installed `1.46.97`
2. launched Brave
3. opened `brave://flags`
4. set both `Brave News v2` and `Brave News Subscribe` button to `Enabled`
5. clicked on `Relaunch`
6. loaded `infoworld.com` and `towardsdatascience.com`
7. for each, clicked on the `Manage Subscriptions` icon in the URL bar
8. ensured I could `Follow` each
9. opened the `Customize News` dialog
10. ensured they were listed
11. opened the Brave News feed on a new-tab page

### `infoworld.com`

1 | 2 | 3 | 4
--|--|--|--
<img width="1312" alt="Screenshot 2022-11-07 at 9 13 30 PM" src="https://user-images.githubusercontent.com/387249/200481039-82e5ee9d-b651-4424-a7cc-b689cb7b4061.png"> | <img width="1312" alt="Screenshot 2022-11-07 at 9 14 00 PM" src="https://user-images.githubusercontent.com/387249/200481044-38dd15d9-7965-4de8-9df6-e13816b961f8.png"> | <img width="1312" alt="Screenshot 2022-11-07 at 9 14 15 PM" src="https://user-images.githubusercontent.com/387249/200481046-14bbc9c2-0126-4af7-9d32-b16af9ae3b33.png"> | <img width="1312" alt="Screenshot 2022-11-07 at 9 14 54 PM" src="https://user-images.githubusercontent.com/387249/200481049-d859c211-68bb-4af6-92d3-5f84dada4187.png">



### `towardsdatascience.com`

1 | 2 | 3 | 4
--|--|--|--
<img width="1312" alt="Screenshot 2022-11-07 at 9 15 15 PM" src="https://user-images.githubusercontent.com/387249/200481102-458ae4fb-6bcd-4ac4-a9b3-55fee8516aa5.png"> | <img width="1312" alt="Screenshot 2022-11-07 at 9 15 20 PM" src="https://user-images.githubusercontent.com/387249/200481106-b5e35ff6-cd06-4c04-b54a-d3c6b66f3be8.png"> | <img width="1312" alt="Screenshot 2022-11-07 at 9 15 32 PM" src="https://user-images.githubusercontent.com/387249/200481108-9a2d8cd6-b7de-492f-b71a-c820a0f1d173.png"> | <img width="1312" alt="Screenshot 2022-11-07 at 9 15 45 PM" src="https://user-images.githubusercontent.com/387249/200481110-46d1bea9-d8ec-4738-983f-3cf8981cf9d7.png">
