### ISSUE TITLE
Hook up Griffin for VPN elements

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#26355]
## Description 

Hook up Griffin for: 

- [ ] The Notice to existing users to notify them that they can use their VPN on Desktop https://github.com/brave/brave-browser/issues/25866
- [ ] The UI for linking accounts to [account.brave.com](http://account.brave.com/)

##

**Comment by bsclifton** [comment]
This should be replacing https://github.com/brave/brave-browser/issues/25680 - I'll capture desktop details and add a testing plan (others welcome to update!)

**Comment by srirambv** [comment]
Verification passed as part of https://github.com/brave/brave-browser/issues/25866#issuecomment-1330689781
