### ISSUE TITLE
VPN doesn't auto connects after purchasing the VPN

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#26350]
## Description 

VPN doesn't auto connect after purchasing the VPN
## Steps to Reproduce

   1. Clean profile 1.47.24
   2. Enable SKU and VPN flags via brave://flags
   3. Purchase the VPN 
   4. Click on `Refresh Brave VPN` 
   5. VPN is not auto connected to the nearest region

## Actual result:

VPN doesn't auto connects after purchasing the VPN

![auto connnect_vpn](https://user-images.githubusercontent.com/38657976/198581080-f4df7204-991b-494e-920c-b3c4db233dc1.gif)

## Expected result:

VPN should be auto connected after purchasing the VPN

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.47.24 Chromium: 107.0.5304.68 (Official Build) nightly (64-bit)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | Windows 10 Version 21H2 (Build 19044.2130)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Not sure about 1.46, but it was fixed in 1.45.x
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @simonhong @bsclifton @spylogsster

**Comment by spylogsster** [comment]
cc @AlanBreck

**Comment by AlanBreck** [comment]
I don't think this is a result of anything on the website itself.

**Comment by simonhong** [comment]
This is expected behavior with current implementation. Should we connect after purchasing?

**Comment by bsclifton** [comment]
@simonhong @GeetaSarvadnya it's definitely NOT expected to connect after purchasing... but it is expected to show the regions when you click the VPN menu (ex: it's authenticated). Looks like that's taken care of per the video in original post 👍
