### ISSUE TITLE
muon becoming unresponsive when launching via the "Launch the new Brave" button

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#2636]
## Description 

When launching `b-c` within `muon` using the "Launch the new Brave" button under `about:newtab`, once `b-c` launches, `muon` becomes unresponsive. You have two choices:

* force quit `muon` which it considers a crash (possibly risking profile corruption)
* close `b-c` which also instantly closes `muon` even though it's unresponsive/hanging

## Steps to Reproduce

  1. ensure that neither `b-c` nor `muon` is installed
  2. install `0.57.18` and close it once it auto launched after installation
  3. install `0.25.303` (skipping the `0.25.2` -> `0.25.303` for quicker STR)
  4. once  `0.25.303` launches, click on the `Launch the new Brave` via `about:newtab`
  5. you'll notice that `0.57.18` will launch but `0.25.303` will instantly become unresponsive
  6. wait ~5min and you'll notice that `0.25.303` is still unresponsive and never recovers
  7.  close `0.57.18` and `0.25.303` will also close instantly even though it's not responsive

## Actual result:

![migrationunresponsive](https://user-images.githubusercontent.com/2602313/50200694-02f82180-0325-11e9-8312-8ed1048344ea.gif)

![issuemigration 1](https://user-images.githubusercontent.com/2602313/50200762-5bc7ba00-0325-11e9-8ce8-7e7a1e131be0.png)

<img width="1135" alt="screen shot 2018-12-18 at 10 09 40 pm" src="https://user-images.githubusercontent.com/2602313/50200765-61bd9b00-0325-11e9-983e-654771eb94e8.png">

## Expected result:

`muon` shouldn't become unresponsive when launching via the `Launch the new Brave` under `about:newtab`

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

```
Brave: 0.25.303
V8: 6.9.427.23
rev: 8decf8c35b9e9400650d79207902e739d5e62598
Muon: 8.1.8
OS Release: 10.0.17763
Update Channel: Release
OS Architecture: x64
OS Platform: Microsoft Windows
Node.js: 7.9.0
Brave Sync: v1.4.2
libchromiumcontent: 69.0.3497.100
```

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

Reproducible under `0.26.0` as well

### Website problems only: 

- Does the issue resolve itself when disabling Brave Shields?

N/A

- Is the issue reproducible on the latest version of Chrome? 

N/A

### Additional Information

@GeetaSarvadnya @btlechowski please see if you can reproduce using your Win machines.

**Comment by GeetaSarvadnya** [comment]
Issue is reproducible on Windows x10. 

1. Click on the `Launch the new Brave` via `about:newtab` lauches `0.57.18` but `0.25.303` becomes unresponsive and it never recovers. close `0.57.18` closes the muon `0.25.303` also.

![image](https://user-images.githubusercontent.com/38657976/50206656-142b4780-0392-11e9-8eb1-50daeadbb260.png)

**Comment by LaurenWags** [comment]
When I follow the STR in description, this is what I see on macOS:
- muon does not hang or become unresponsive
- b-c opens and muon closes smoothly
- however, if I reopen muon now, my entire session was lost. @btlechowski suggested silent crash - I checked chrome://crashes and there's nothing listed there.

**Comment by btlechowski** [comment]
Verification passed on Windows 7 x64


Brave | 0.58.16 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Windows

Brave | 0.25.304
-- | --
V8 | 6.9.427.23
rev | 3ecf323

Used STR from OP
