### ISSUE TITLE
Common Sense Media's favicon is stretched, aspect-ratio wise

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#26368]
## Description 

Common Sense Media's favicon is stretched, aspect-ratio wise
## Steps to Reproduce

   1. install `1.46.81`
   2. launch Brave
   3. set `brave://flags/#brave-news-v2` to `Enabled`
   4. set `brave://flags/#brave-news-subscribe-button` to `Enabled`
   5. click `Relaunch`
   6. open a new-tab page
   7. scroll down
   8. click on `Show Brave News`
   9. click on `Customize`
   10. type `common` under `Discover`
   11. click on `Follow`
   12. compare the favicon to the larger one in `Sources`

## Actual result:

<img width="1324" alt="Screen Shot 2022-10-28 at 10 58 17 AM" src="https://user-images.githubusercontent.com/387249/198702111-91940116-f33b-4774-bd57-4090f24b1275.png">

## Expected result:

Should be normal proportions/aspect ratios.

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (x86_64)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | macOS Version 11.7.1 (Build 20G918)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

/cc @fallaciousreasoning @rebron

**Comment by kjozwiak** [comment]
The above requires `1.46.90` or higher for `1.46.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.46.91 Chromium: 107.0.5304.91 (Official Build) dev (x86_64)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | macOS Version 11.7.1 (Build 20G918)

### Steps:
1. install `1.46.91`
2. launch Brave
3. set `brave://flags/#brave-news-v2` to `Enabled`
4. set `brave://flags/#brave-news-subscribe-button` to `Enabled`
5. click `Relaunch`
6. open a new-tab page
7. scroll down
8. click on `Show Brave News`
9. click on `Customize`
10. type `common` under `Discover`
11. click on `Follow`
12. compare the favicon to the larger one in `Sources`

#### Confirmed both the `Common Sense` and `American Psychological Association` favicons/icons are correctly-sized 👍 

`Common Sense` | `APA`
------------------|-------
<img width="1312" alt="Screen Shot 2022-11-03 at 8 36 38 AM" src="https://user-images.githubusercontent.com/387249/199766431-111a74f9-54f3-4260-bc54-b0d1b117c827.png"> | <img width="1312" alt="Screen Shot 2022-11-03 at 8 36 47 AM" src="https://user-images.githubusercontent.com/387249/199766447-dc2afc9b-8b48-43ac-93c9-9604b33cc110.png">
