### ISSUE TITLE
Account blockie is hidden when browser window size becomes very small in width

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#26367]
## Description 

Account blockie is hidden when browser window size becomes very small in width

## Steps to Reproduce

   1. Submit a transaction and open account details page
   2. Reduce the browser window size
   3. once it becomes small enough the account blockie is hidden 

## Actual result:

https://user-images.githubusercontent.com/17010094/198699272-7adaff4a-f6f2-4538-8fa5-ff6338664dc3.mp4

## Expected result:
Should not hide account blockie no matter the browser window size

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (64-bit)
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NAN
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @josheleonard

**Comment by josheleonard** [comment]
@srirambv, is this still valid. I'm not seeing the account details screen in the video

**Comment by srirambv** [comment]
Issue is not valid anymore. Closing as invalid
