### ISSUE TITLE
Brave News's `Unfollow` and `Manage Feeds` texts are illegible on Windows 11

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#26366]
## Description 

Brave News's `Unfollow` and `Manage Feeds` texts are illegible on Windows 11

## Steps to Reproduce

   1. install `1.47.27`
   2. launch Brave
   3. open `brave://flags`
   4. set `brave://flags/#brave-news-subscribe-button` to `Enabled`
   5. click `Relaunch`
   6. load `wired.com`
   7. click on the `Manage Subscriptions` icon
   8. click `Follow`
   9. look at the resulting UI

## Actual result:

`Unfollow` and `Manage Feeds ->` are almost completely illegible

![illegible](https://user-images.githubusercontent.com/387249/198698938-bb8ffec1-62c5-40ce-b129-4259df416de8.png)

## Expected result:

Should be able to read the UI labels

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.47.27 Chromium: 107.0.5304.91 (Official Build) nightly (64-bit)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | Windows 11 Version 21H2 (Build 22000.1165)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @aguscruiz @fallaciousreasoning @rebron

**Comment by stephendonner** [comment]
Other UI pieces are fine, font-wise.  @MadhaviSeelam do you see this also, on Windows 11?

![image](https://user-images.githubusercontent.com/387249/198699559-4f2ed7bc-16dc-4410-a800-dbcb9e7a285a.png)

**Comment by fallaciousreasoning** [comment]
I'm seeing it in Nightly on Linux too. I think this has something to do with drawing a transparent background. I'm working on a fix.

**Comment by LaurenWags** [comment]
Requires `1.46.122` or higher to test.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.46.122 Chromium: 108.0.5359.48 (Official Build) beta (x86_64)
-- | --
Revision | 18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}
OS | macOS Version 11.7.1 (Build 20G918)

### Steps:

1. installed `1.46.122`
2. launched Brave
3. opened `brave://flags`
4. set `brave://flags/#brave-news-subscribe-button` to `Enabled`
5. clicked `Relaunch`
6. loaded `wired.com`
7. clicked on the `Manage Subscriptions` icon
8. clicked `Follow`
9. looked at the resulting UI

#### Confirmed `Follow`,`Unfollow`, and `Manage Feeds` were all legible, using both `Dark` and `Light` modes

`Dark`

`Follow` | `Unfollow`
---------|-----------
<img width="990" alt="Screen Shot 2022-11-21 at 8 21 27 PM" src="https://user-images.githubusercontent.com/387249/203220835-428f7620-51b1-4c24-aa8a-3cff0883491e.png"> | <img width="990" alt="Screen Shot 2022-11-21 at 8 21 33 PM" src="https://user-images.githubusercontent.com/387249/203220836-de36b701-b100-4cf4-a14b-d27c2db26364.png">

`Light`

`Follow` | `Unfollow`
---------|------------
<img width="1028" alt="Screen Shot 2022-11-21 at 8 22 02 PM" src="https://user-images.githubusercontent.com/387249/203220840-b8c5dc91-abf3-4a5d-a421-3c851bc630bb.png"> | <img width="1028" alt="Screen Shot 2022-11-21 at 8 21 54 PM" src="https://user-images.githubusercontent.com/387249/203220839-11ac4228-de31-4acf-b187-576c29a0b2f2.png">

**Comment by stephendonner** [comment]
Note also: https://github.com/brave/brave-browser/issues/26262 is still open, and isn't reflected in the screenshots above.
