### ISSUE TITLE
Change default auto lock setting from 5 minutes to 10 minutes

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#26362]
Many people have complained that we re-lock the wallet too quickly. Let's update from a default of 5 minutes auto-lock to a default of 10 minutes.  Thread here: https://bravesoftware.slack.com/archives/C8MP8ME4C/p1666893856182529

**Comment by vadimstruts** [comment]
Hi @bbondy 
Should we change default value only for new users or for new and all existing, who have the default value used (i.e. apply special preferences migration)?

**Comment by bbondy** [comment]
I think let's do the change, but please include someone from the security team on the review of the pull request. 

It should just be a default value change, no migration.
