### ISSUE TITLE
Implement the new onboarding UI

### ISSUE THREAD

**Issue by nullhook** [brave/brave-browser#26378]
Implement the new onboarding UI

**Comment by LaurenWags** [comment]
`QA/Blocked` - per @rebron test plan still needed

**Comment by rebron** [comment]
Testing requires 1.48.41 and higher.

**Comment by rebron** [comment]
@nullhook @LaurenWags Note for multiple profile import to ensure that the profiles are imported separately and the default profile for the one imported remains the default profile in Brave.

Check for other case for multiple profile import, if default profile for the imported browser is not selected but other profiles are, which profile becomes default in Brave. Unclear on what the ordering/selection should be.

**Comment by LaurenWags** [comment]
as discussed during today's QA walkthrough, this will be tested in 1.47.x, but requires uplifts before beginning (see "Related issues" in https://github.com/brave/brave-browser/issues/26378#issue-1427981070) so this issue remains blocked until the 2 "Related issues" PRs are uplifted. 

There will be another uplift, but it's macOS specific and wouldn't hold up testing of this issue on Win/Linux.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.47.129 Chromium: 108.0.5359.128 (Official Build) beta (64-bit)
-- | --
Revision | 1cd27afdb8e5d057070c0961e04c490d2aca1aa0-refs/branch-heads/5359@{#1185}
OS | Windows 11 Version 21H2 (Build 22000.1335)
```
Case 1: `brave://welcome` page upon Brave launch
<details>

1. Install 1.47.129
2. launch Brave
3. verified First run dialog no longer displayed

#### Confirmed newly designed `brave://welcome` page `Set Brave as a default browser` and `Skip` buttons displayed

<img width="464" alt="image" src="https://user-images.githubusercontent.com/98358127/207958733-9330423b-f471-4862-bc6f-709a3137d103.png">

</details>

Case 2: Set Brave as default browser
continue from Case 1
      - `brave://welcome` page  
click `Set Brave as default browser` button
verified the second show all the browsers 




Case 3:  Select Browser
Pre-requisites: 
Have import supported browsers installed 
`Chrome`, `Chrome Beta`, `Chrome Canary`, `Edge`, `Internet Explorer`, `Firefox`, `Opera`, and `Vivaldi`

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.47.151 Chromium: 109.0.5414.46 (Official Build) beta (x86_64)
-- | --
Revision | 6e36b77363ef3febbe792af680fa1367993ddcf0-refs/branch-heads/5414@{#709}
OS | macOS Version 11.7.2 (Build 20G1020)

Section 1
Section 2
Section 3
Section 4
Section 5
