### ISSUE TITLE
Refactor "Redirect IPFS resources to the configured gateway" to use reload instead of redirect

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#26373]
Refactor OnHeadersReceived_IPFSRedirectWork
1) We don't need to check x-ipfs-path header in the case when the url already has CID in path or subdomain.
2) Use re-request or url rewrite instead of fake redirect.
3) Show ipfs button for gateway-like urls when auto redirect is disabled

According sec review https://github.com/brave/security/issues/1063

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.47.126 Chromium: 108.0.5359.99 (Official Build) beta (64-bit)
-- | --
Revision | `410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#15772](https://github.com/brave/brave-core/pull/15772)
- Verified `Redirect IPFS resources to the configured IPFS gateway` setting works as expected
- Verified with the setting disabled visiting gateway URL such as `ipfs.io/ipfs/bafybeibz5jdo2r7244gdzvrynyo2di3m3kics5nmkd6dby5mikvffqi4qm/` shows `IPFS` button in URL bar and clicking on it loads URL via public gateway


https://user-images.githubusercontent.com/17010094/207549500-0c17681e-c326-4d51-80d3-71a8bc0f655e.mp4
