### ISSUE TITLE
Move Send to its own Tab

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#26371]
## Description 

We need to move `Send` into it's own tab

See figma designs here https://www.figma.com/file/SeRk6BLWnaqK8PQbayXWnx/Send?node-id=114%3A50437

![Screen Shot 2022-10-28 at 2 09 32 PM](https://user-images.githubusercontent.com/40611140/198713899-5a058501-7d3c-4002-a411-dca8bb4ace5b.png)

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.47.126 Chromium: 108.0.5359.99 (Official Build) beta (64-bit)
-- | --
Revision | `410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}`
OS | Linux

- Verified steps from [brave/brave-core#15913](https://github.com/brave/brave-core/pull/15913)
- Verified able to send `Native` tokens
- Verified able to send `ERC20` tokens
- Verified able to send `ERC721` NFT tokens
- Verified able to send `SPL` NFT tokens

https://user-images.githubusercontent.com/17010094/207596951-c73b30f2-11f0-4310-9a7b-817fe218ef55.mp4

---------------------

Verification passed on 

Brave | 1.47.126 Chromium: 108.0.5359.99 (Official Build) beta (64-bit)
-- | --
Revision | `410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#15913](https://github.com/brave/brave-core/pull/15913)
- Verified able to send `Native` tokens
- Verified able to send `ERC20` tokens
- Verified able to send `ERC721` NFT tokens
- Verified able to send `SPL` NFT tokens

https://user-images.githubusercontent.com/17010094/207597595-a99d7073-7417-4b58-869e-c2b21dbe289e.mp4

---------------------

Verification passed on 

Brave | 1.47.126 Chromium: 108.0.5359.99 (Official Build) beta (arm64)
-- | --
Revision | `410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#15913](https://github.com/brave/brave-core/pull/15913)
- Verified able to send `Native` tokens
- Verified able to send `ERC20` tokens
- Verified able to send `ERC721` NFT tokens
- Verified able to send `SPL` NFT tokens

https://user-images.githubusercontent.com/17010094/207597423-cfb8ede7-20c8-4b31-80d8-82e8f0dd4ea6.mov
