### ISSUE TITLE
Change description for "Redirect IPFS resources to configured gateway" feature

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#26374]
According https://github.com/brave/security/issues/1063

**Comment by stephendonner** [comment]
@cypt4 can you please provide a step-by-step testplan for this?  Although it says "Change description..." it looks like there are quite a few changes here I should help regression-test?

**Comment by LaurenWags** [comment]
@cypt4 pinging on https://github.com/brave/brave-browser/issues/26374#issuecomment-1302830117.

cc @kjozwiak @rebron @srirambv

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.47.161 Chromium: 109.0.5414.61 (Official Build) beta (64-bit)
-- | --
Revision | 846c6eff1c374cde417a9cdc44193545cc07f354-refs/branch-heads/5414@{#1030}
OS | Linux

- Verified test plan from [brave/brave-core#15721](https://github.com/brave/brave-core/pull/15721)
- Verified text copy is same as mentioned in [security#1063 (comment)](https://github.com/brave/security/issues/1063#issuecomment-1294065874)
- Verified with setting enabled loading `gateway.io/ipfs/bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfy` redirects to `ipfs://bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfy`
- Verified with settings enabled loading `bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfy.ipfs.gateway.io` redirects to `ipfs://bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfy`

https://user-images.githubusercontent.com/17010094/210527646-71504a6e-5ae2-415b-a2d8-9d66f0bd4e55.mp4
