### ISSUE TITLE
Misleading Signing Request Message (BRA-Q322-7)

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#26372]
Basically implement of what we have on desktop https://github.com/brave/brave-browser/issues/24816

**Comment by kjozwiak** [comment]
The above requires `1.46.97` or higher for `1.46.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.45.125 x64 build
- Verified steps from [#24816](https://github.com/brave/brave-browser/issues/24816)
- Verified when non-ASCII code is passed in Sign transaction, a warning message is show
- Verified clicking on View message in ASCII encoding shows the ASCII code in message
- Verified clicking on View original message shows the encoded message
- Logged followup issue [#26692](https://github.com/brave/brave-browser/issues/26692)

Samsung Tab  A(Android 10) | Oppo Reno 5 (Android 12) 
-- | --
<video src=https://user-images.githubusercontent.com/17010094/201317147-3b98e26c-e434-4364-8793-ea0df679329c.mp4> | <video src=https://user-images.githubusercontent.com/17010094/201317166-e064abaa-af02-4a96-bf46-bfcdeaaf1386.mp4>
