### ISSUE TITLE
Exempt non-GET requests from the query filter

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#26377]
Bounce trackers and email newsletter trackers use `GET` requests (typically redirect chains of them). We can therefore exempt `POST` requests, which are typically the result of form submissions and a user action. This should help mitigate any webcompat issues arising from filtering parameters that a form might need in order to work properly.

This is also in line with the [Mozilla policy on URL decorations](https://wiki.mozilla.org/Security/Anti_tracking_policy#2._Navigational_cross-site_tracking).

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.47.39 Chromium: 107.0.5304.91 (Official Build) nightly (x86_64)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | macOS Version 11.7.1 (Build 20G918)


### Steps:
1. installed `1.47.39`
2. launched Brave
3. loaded `https://fmarier.github.io/brave-testing/query-filter.html`
4. scrolled down to the `POSTS tests` section
5. clicked on the button
6. examined the URL bar

#### Confirmed the URL I ended up on included the `?fbclid=1234` query-string parameter: `https://fmarier.org/query-filter/?fbclid=1234`


`test page` | `result`
------------|--------
<img width="1312" alt="Screen Shot 2022-11-02 at 4 27 53 PM" src="https://user-images.githubusercontent.com/387249/199621533-077222e2-5995-42ff-9b26-293313719a51.png"> | <img width="1312" alt="Screen Shot 2022-11-02 at 4 28 01 PM" src="https://user-images.githubusercontent.com/387249/199621541-5669a4d2-cf37-4b48-a79c-3aa06d481200.png">

**Comment by antonok-edm** [comment]
AdGuard's `removeparam` option applies to `GET`, `HEAD`, and `OPTIONS`. I haven't checked the behavior, but uBO's wiki links to the same document for reference. We should do the same.

https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#removeparam
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#removeparam

**Comment by fmarier** [comment]
@antonok-edm `HEAD` and `OPTIONS` to be added in https://github.com/brave/brave-browser/issues/26827.

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version:

```
Brave 1.47.167 Chromium: 109.0.5414.80 (Official Build) (64-bit)
Revision 0f69b168d36a06cace4365e9f029fa987afa5633-refs/branch-heads/5414@{https://github.com/brave/brave-browser/issues/1178}
OS Android 12; Build/SP1A.210812.016
```

1. installed 1.47.x
2. launched Brave
3. loaded https://fmarier.github.io/brave-testing/query-filter.html
4. scrolled down to the POSTS tests section
5. clicked on the button
6. examined the URL bar

Confirmed the URL I ended up on included the `?fbclid=1234` query-string parameter: `https://fmarier.org/query-filter/?fbclid=1234`

Example | Example
-|-
![screenshot-1673305157249](https://user-images.githubusercontent.com/17885425/211425476-1b555a65-b99f-407d-9879-0b930717dd61.png) | ![screenshot-1673305215410](https://user-images.githubusercontent.com/17885425/211425482-44173e7b-1be3-4d72-b6c7-d2885c790ef2.png)
