### ISSUE TITLE
NFT images don't load on portfolio/panel when added without network 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#26388]
## Description 

NFT images don't load on portfolio/panel when added without network 

## Steps to Reproduce

   1. Disable network
   2. Add a bunch of NFT's to portfolio
   3. Doesn't show any image for NFT's 
   4. Connect back to network 
   5. Open the NFT, shows the NFT image
   6. Reload portfolio, doesn't load the image yet
   7. Open panel, doesn't show the NFT image

## Actual result:

https://user-images.githubusercontent.com/17010094/198982914-6b17c951-7d1b-4bdc-a68c-cd5bb92a65fb.mp4

## Expected result:
Should show the image when image metadata is loaded in NFT view details

## Brave version (brave://version info)

<html>
<body>

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (64-bit)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | Linux

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Not checked

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @muliswilliam @nvonpentz

**Comment by josheleonard** [comment]
Closing - NFTs can no longer be added without first selecting a network from the dropdown

![Image](https://github.com/brave/brave-browser/assets/30185185/9a0e2479-7951-4234-99eb-1d98cbc6e49c)
