### ISSUE TITLE
Main profile can't be deleted.

### ISSUE THREAD

**Issue by OverBrave** [brave/brave-browser#26389]
## Description 
Main profile can't be deleted.
So, I opened new profile and changed so many settings in this profile. After, I try delete old/main profile. By the way I can delete oldest/main profile but after restart browser/pc its coming again to profiles.  I want to use just one profile and don't want delete new created profile.

## Steps to Reproduce

   1. Open new profile.
   2. Try delete main/oldest profile.

## Actual result:
![image](https://user-images.githubusercontent.com/47111280/198996572-c97577c1-e60a-452d-a185-689c5c906041.png)

## Expected result:
![image](https://user-images.githubusercontent.com/47111280/198996644-c3c71953-273f-4a8e-8aa6-06eced9ba9d7.png)

## Reproduces how often: 
Always

## Brave version (brave://version info)
1.45.116 Chromium: 107.0.5304.91 

## Version/Channel Information:

- Can you reproduce this issue with the current release?  Yes
- Can you reproduce this issue with the beta channel? I haven't tried it but probably not because this problem has been around for about 1 year.
- Can you reproduce this issue with the nightly channel? I haven't tried it but probably not because this problem has been around for about 1 year.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? I don't know.

**Comment by rebron** [comment]
Closing as duplicated of https://github.com/brave/brave-browser/issues/4599
