### ISSUE TITLE
[hackerone] crash

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#26384]
see https://github.com/brave/internal/issues/943

credit: [rebane2001](https://hackerone.com/rebane2001)

**Comment by kjozwiak** [comment]
@brave/qa-team please use https://github.com/brave/internal/issues/943 for verification notes as per https://github.com/brave/internal/issues/943#issuecomment-1297986124.

**Comment by kjozwiak** [comment]
The above requires `1.45.118` or higher for `1.45.x` verification 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.45.118 Chromium: 107.0.5304.91 (Official Build) (64-bit)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | Windows 11 Version 22H2 (Build 22621.755)
```

Verification notes can be found via https://github.com/brave/internal/issues/943#issuecomment-1299505474.

**Comment by stephendonner** [comment]
## Verification `PASSED` using 

Brave | 1.45.118 Chromium: 107.0.5304.91 (Official Build) (x86_64)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | macOS Version 11.7.1 (Build 20G918)


Verification notes can be found via https://github.com/brave/internal/issues/943#issuecomment-1299579856

**Comment by kjozwiak** [comment]
Verification **PASSED** on `PopOS 22.04 x64` using the following build(s):

```
Brave | 1.45.118 Chromium: 107.0.5304.91 (Official Build) (64-bit)
--- | ---
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | Linux
```

Verification notes can be found via https://github.com/brave/internal/issues/943#issuecomment-1299671244.
