### ISSUE TITLE
signature created from brave wallet can not verify

### ISSUE THREAD

**Issue by nguyenhoaidanh** [brave/brave-browser#26380]
## Description 
Hi team, 
I am working on a dapp that needs to verify users' signatures. When testing with Metamask, Coinbase everything is okay.
But can not verify the signature created from Brave wallet.
My code js code using ethers.js.
```
const hash = `0xd3aea288db79124342317a8e950dfc59d3f8d93b7a7b743a25c3453f2e53e309`
const myAccount = `0xF14DE383fE1f5ECA59dbC33A7d7aB527AD7c8c94`
const signature = await myprovider.send('eth_sign', [myAccount, hash])
// signature is "0xf20b11505f101df739e899dec45f09791526f4b06ad77b987699517a08db36c04c224e262b5757ecba9e648e61c12cd2668c9327f22e46e85d9e5e18cc6260bf1c"

```
I verify signature by golang backend with go-ethereum.
I tried another method like `personal_sign` but it still got same problem.
I am sure that problem with Brave because that signature create from Metamask, Coinbase wallet can be verify successfully.
## Actual result:
Invalid signature

## Expected result:
Signature create from Brave wallet can be verify 

## Reproduces how often: 
100%

## Desktop Brave version:
- Brave wallet on Brave browser
- Brave browser version: 1.45.113
- MacOS

**Comment by diracdeltas** [comment]
cc @kdenhartog

**Comment by kdenhartog** [comment]
@nguyenhoaidanh do you have a test dApp or a piece of sample code that you can provide me with to try and reproduce this issue on my end? More specifically, how are you instantiating your provider object and what error code are you seeing?

**Comment by nguyenhoaidanh** [comment]
@kdenhartog @diracdeltas Thanks all, I found my solution. 
My FE code, sign with ethers.js, It work well with all wallet now.
```
const hash = `0xd3aea288db79124342317a8e950dfc59d3f8d93b7a7b743a25c3453f2e53e309`
const signature = await myprovider.getSigner().signMessage(ethers.utils.arrayify(hash))
```
and update my BE code verify using  [EIP 191 standar](https://eips.ethereum.org/EIPS/eip-191#specification)

**Comment by kdenhartog** [comment]
I can see that this library works for eth_chainId and I'm getting a 4200 error showing in the wallet which is usually an [indication that the method](https://github.com/brave/brave-core/blob/be6363986637fbfa563b0cf6217dea1798ebd479/components/brave_wallet/common/brave_wallet.mojom#L48) is not supported.

I'm not sure why `eth_sign` isn't usable, but I will note that the usage of the send API is deprecate in both [Brave ](https://wallet-docs.brave.com/ethereum/provider-api/methods#ethereumsend-deprecated) and [Metamask](https://docs.metamask.io/guide/ethereum-provider.html#legacy-methods).

You should be using the [request API](https://github.com/ethers-io/ethers.js/blob/01aea705ce60b1c42d2f465b162cb339a0e94392/packages/providers/src.ts/web3-provider.ts#L20) these days with the [ExternalProvider class](https://docs.ethers.io/v5/api/providers/other/#Web3Provider--ExternalProvider).

**Comment by kdenhartog** [comment]
Good to hear @nguyenhoaidanh I'm going to close this one out then.
