### ISSUE TITLE
When a link is opened on Google, the "Open with" dialog always appears

### ISSUE THREAD

**Issue by cbwee** [brave/brave-browser#26381]
## Description 
While browsing in Brave, the "Open with" dialog appears when any link on a Google search results page is opened, if no default browser is set.

## Steps to reproduce 

   1. Open Brave
   2. Search anything on Google
   3. Open a link of any of the results
   4. The "Open with" dialog appears
   5. Select Brave to open the link
   6. Set any of the browsers (not Brave) to be the default browser
   7. Brave opens links on Google normally, without having that dialog every time a link is opened in Brave

## Actual result 
As shown in the screen recording, the dialog appears, but as soon as a browser is set as default, it will not appear.
https://user-images.githubusercontent.com/34395942/198836150-07dbfc29-03dd-4097-aabc-fb6c8ace85ad.mp4

## Expected result
Even if none of the browser is set as the default browser, Brave should open links normally.

## Issue reproduces how often 
Easily reproduced

## Version/Channel Information:

It happens on all channels.

## Device details
   - Install type (ARM, x86): ARM64
   - Device type (Phone, Tablet, Phablet): Phone (Xiaomi Redmi 9T)
   - Android version: Android 12, MIUI 13
   
## Brave version
Nightly 1.47.28

### Additional information

This also happens on older versions of Brave, it happens even after I factory reset my phone, but it only happens in Brave, no any other browser has this issue.
I noticed that this only happens recently after Google changes the design of the mobile search results page.

**Comment by Saga-sanga** [comment]
Hi, does this issue still exist?

**Comment by cbwee** [comment]
Recently after I re-installed the OS on my phone, I do not have this issue on the phone anymore, I will close this issue for now.
