### ISSUE TITLE
Wallet shows wrong address and network when signing DApps messages/transaction 

### ISSUE THREAD

**Issue by stoletheminerals** [brave/brave-browser#26397]
## Description 

On Android, if I connect to Ethereum dapps and have a Solana account active/chosen in the wallet, it shows my Solana address instead of the Ethereum address when signing messages . This works vice versa as well, shows my Ethereum address when signing Solana dapps messages. When signing transaction it also shows the network incorrectly on both Android and Desktop.

## Steps to Reproduce

   1. Have both Ethereum and Solana accounts in the Wallet
   2. Visit `https://pwgoom.csb.app/`
   3. Connect the wallet
   4. Open the wallet and change the account to Ethereum
   5. Press `Sign Transaction` (also `Sign Message` on Android)
   

## Actual result:
Desktop shows current active network (Ethereum), instead of the network where transaction actually happens (Solana)
Android shows both the network and address incorrectly

![image](https://user-images.githubusercontent.com/10810135/199105661-396f2e72-9f00-4329-92a6-95cde0f82638.png)

https://user-images.githubusercontent.com/10810135/199106044-02ae786d-40bc-416f-a79b-359d3b7d428b.mp4

https://user-images.githubusercontent.com/10810135/199106048-6ad54f33-0599-4a65-ae05-0f0b3799e32b.mp4

## Expected result:
Wallet should show the network and the account address where transaction/signing happens

## Reproduces how often: 

Easily reproduced

## Desktop Brave version:

<img width="565" alt="image" src="https://user-images.githubusercontent.com/10810135/199110237-2c70932f-1e9e-4480-80a1-77591c834491.png">

## Android Device details:
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Galaxy S10 Plus
   - Android version: 12

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by SergeyZhukovsky** [comment]
desktop version of the problem will be covered in that issue https://github.com/brave/brave-browser/issues/26476

**Comment by kjozwiak** [comment]
The above requires `1.46.94` or higher for `1.46.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.46.96 x64 Beta build
- Verified steps from [brave/brave-core#15763](https://github.com/brave/brave-core/pull/15763)
- Verified with Ethereum Account set as active account, submitting a Solana Dapp transaction shows correct address and network

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/200518983-3221ab24-006c-40af-a8a4-a3dda43e1461.mp4> | <video src=https://user-images.githubusercontent.com/17010094/200552955-c4cfeb34-6822-4c01-96d6-710580668a3b.mp4>
