### ISSUE TITLE
Revisit issue 22028

### ISSUE THREAD

**Issue by notvenom** [brave/brave-browser#26393]
Hi, I know this isnt the proper way, but on 
https://github.com/brave/brave-browser/issues/22028 , it was said in May that it would be worked on in the next few weeks. However, it has been 5 months now with no update, the issue is locked and community threads are ignored.
Will this be implemented eventually or are we just forced to use the old version forever?

**Comment by UjCbFwtBayFM** [comment]
They made it quite clear it would require too much work for little gains.

**Comment by bsclifton** [comment]
This is still on our backlog; I'll see if we can share an update in the original issue

It was locked because there things were getting a bit heated
