### ISSUE TITLE
updated region not supported message is NOT shown for Gemini custodian

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#26391]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/25918
updated region not supported message is NOT shown for Gemini custodian

## Steps to Reproduce

   1. Clean profile 1.46.x
   2. Click on the BR panel and declare the geo as `US` in the rewards onborading flow
   3. Enable rewards
   4. Login to Gemini custodian using the Gemini account which is verified with `IN` region

## Actual result:

updated region not supported message is NOT shown for Gemini custodian
![image](https://user-images.githubusercontent.com/38657976/199001742-17484e1a-4841-4f91-8d71-7fd469d6f46a.png)

## Expected result:

Updated message should be shown as mentioned in the description https://github.com/brave/brave-browser/issues/25918#issue-1405111563
## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (64-bit)
-- | --
Revision | a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}
OS | Windows 10 Version 21H2 (Build 19044.2130)

</body>
</html>
## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @szilardszaloki @Miyayes @brave/qa-team

**Comment by Miyayes** [comment]
@GeetaSarvadnya I think you're just running into a different error in this case? Or: "region not supported" logic comes _before_ "country mismatch" check?

**Comment by GeetaSarvadnya** [comment]
@Miyayes Looks like issue is invalid. In this case, the `region not supported` message which I am getting is expected as `India` is in not supported country list for Gemini.

**Comment by GeetaSarvadnya** [comment]
cc: @szilardszaloki

**Comment by szilardszaloki** [comment]
@GeetaSarvadnya @Miyayes We have "early region not supported" errors implemented only for Uphold, so that's not coming from Gemini, but from our linking endpoint. @husobee might know what the actual order of these checks is.

**Comment by Miyayes** [comment]
It's indeed on the server, but in general, "region not supported" seems to be very early/come first. In testing some other error messages, too, I also noted that "region not supported" takes precedence, so it's probably early up in logic. 

If the logic is working w/ other custodian cases, I feel safe closing this out as invalid for now. Thanks for reporting.
