### ISSUE TITLE
New tab button is not visible when vertical tab is enabled

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#26403]
## Description 

New tab button is not visible when vertical tab is enabled

## Steps to Reproduce

   1. Launch with clean profile
   2. Turn on vertical tab feature and relaunch
   3. 

## Actual result:

New tab button is not visible in tab strip

## Expected result:
New tab button should be visible

## Reproduces how often: 

Easy

## Brave version (brave://version info)

[Version 1.47.33 Chromium: 107.0.5304.91 (Official Build) nightly (x86_64)](https://brave.com/latest/)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

New tab buttons is visible again when turn on vertical tab via tab's context menu.
But, happen again after relaunching.

cc @sangwoo108

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.47.120 Chromium: 108.0.5359.99 (Official Build) dev (x86_64)
-- | --
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | macOS Version 13.1 (Build 22C65)

### Steps:
1. installed `1.47.120`
2. launched Brave
3. opened `brave://flags`
4. set `brave://flags/#brave-vertical-tabs` to `Enabled`
5. clicked on `Relaunch`
6. confirmed I saw a new-tab page button
7. confirmed clicking on the new-tab button opened a new page

`after relaunch` | `new-tab page`
---------|---------
<img width="1730" alt="Screenshot 2022-12-08 at 10 46 25 PM" src="https://user-images.githubusercontent.com/387249/206642252-34b1624e-874f-48ff-b730-c2605b275e94.png"> | <img width="1366" alt="Screenshot 2022-12-08 at 10 46 31 PM" src="https://user-images.githubusercontent.com/387249/206642254-77a43e53-35d7-4241-9d95-7b18a5300791.png">
