### ISSUE TITLE
Wallet page icon needs to be updated for light theme

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#26406]
## Description 

Wallet page icon needs to be updated

## Steps to Reproduce

   1. Open `brave://wallet`
   2. Tab icon shows black brave logo

## Actual result:

<img width="978" alt="image" src="https://user-images.githubusercontent.com/17010094/199162821-b623fe14-d4e3-441d-b59e-61cbc43028c8.png">

## Expected result:
Similar to About Brave page

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.47.33 Chromium: 107.0.5304.91 (Official Build) nightly (arm64)
-- | --
Revision | `3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}`
OS | macOS Version 13.0 (Build 22A380)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel 
Looks like regression of https://github.com/brave/brave-browser/issues/25818

**Comment by Douglashdaniel** [comment]
@srirambv should be fixed when @petemill lands https://github.com/brave/brave-core/pull/15700

**Comment by Douglashdaniel** [comment]
Was fixed via https://github.com/brave/brave-core/pull/15700, closing as invalid.
