### ISSUE TITLE
Port `wallet` reducer to utilize Redux Tool Kit

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#26401]
## Description 

Utilize the newly added Redux Tool Kit dependency to simplify reducer logic for the `wallet` portion of the redux store

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.47.164 Chromium: 109.0.5414.74 (Official Build) (64-bit)
-- | --
Revision | `e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}`
OS | Linux

- Verified steps from [brave/brave-core#15728](https://github.com/brave/brave-core/pull/15728)
- Verified wallet functionality works as expected

---------------------

Verification passed on 

Brave | 1.47.164 Chromium: 109.0.5414.74 (Official Build) (64-bit)
-- | --
Revision | `e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#15728](https://github.com/brave/brave-core/pull/15728)
- Verified wallet functionality works as expected

---------------------

Verification passed on 

Brave | 1.47.164 Chromium: 109.0.5414.74 (Official Build) (arm64)
-- | --
Revision | `e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#15728](https://github.com/brave/brave-core/pull/15728)
- Verified wallet functionality works as expected
