### ISSUE TITLE
UD address resolution sometimes fails until you clear the address and retype/paste it

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#26411]
## Description 

UD address resolution sometimes fails until you clear the address and retype/paste it

## Steps to Reproduce

   1. Set network to Solana
   2. Type/paste `uns-devtest-brave.x` in the Send to field
   3. Resolve to SOL address
   4. Change network BSC/Ethereum, doesn't automatically update to ETH address
   5. Change token on BSC/ETH, then automatically updates

## Actual result:

UD address resolution sometimes fails until you clear the address and retype/paste it

## Expected result:
Automatically resolve address when network is changed

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.46.81 Chromium: 107.0.5304.68 (Official Build) beta (64-bit)
-- | --
Revision | `a4e93e89d3b3df1be22214603fba846ad0183ca5-refs/branch-heads/5304@{#991}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @supermassive @yrliou

**Comment by Douglashdaniel** [comment]
Closing this as `not-actionable` since we now clear the address field after switch networks/token. https://github.com/brave/brave-browser/issues/28151
