### ISSUE TITLE
Chromium icons: in url bar; bookmark this page.  

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#2641]
The fresh master branch based  on Chromium 72 has the icon of Chromium in url bar instead of Brave's icon; star for 'Bookmark this page' instead of  ![image](https://user-images.githubusercontent.com/24739341/50219065-ab929980-0396-11e9-9ef7-eb29f4fae3d6.png)

## Steps to Reproduce

   1. Open chrome://bookmarks/

## Actual result:

   2. See the icon of Chromium
 
![image](https://user-images.githubusercontent.com/24739341/50218751-ab45ce80-0395-11e9-911c-97487535b508.png)

## Expected result:
2. Icon looks like before in Chromium 71 based builds
![image](https://user-images.githubusercontent.com/24739341/50218784-cca6ba80-0395-11e9-87dc-71e684ba66d2.png)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.61.0 Chromium: 72.0.3626.17 (Developer Build) (64-bit)
-- | --
Revision | 08d2140079f8db14c9eb885a803d231b1a30e817-refs/branch-heads/3626@{#315}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
hadn't tried

**Comment by bbondy** [comment]
thanks for posting, nice find.

**Comment by LaurenWags** [comment]
Reproduced with Beta channel 0.59.12
![screen shot 2018-12-21 at 1 33 40 pm](https://user-images.githubusercontent.com/28145373/50357772-1d005280-0525-11e9-9dc6-79593499d964.png)

**Comment by rebron** [comment]
Approving for uplift to 59.x. cc: @kjozwiak and @srirambv

**Comment by GeetaSarvadnya** [comment]
Verification passed on 

Brave | 0.59.13 Chromium: 72.0.3626.28 (Official Build) beta (64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Windows

Verification passed on

Brave	0.59.13 Chromium: 72.0.3626.28 (Official Build) beta (64-bit)
Revision	997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS	Linux
