### ISSUE TITLE
Sync available in Settings - follow up to 2609

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#2642]
## Description 
Follow up to https://github.com/brave/brave-browser/issues/2609

Build 0.58.15 should have Sync disabled by default. However, when navigating to brave://settings, Sync is still available in Settings.

## Steps to Reproduce

   1. Install 0.58.15
   2. Navigate to brave://settings
   3. Search for Sync

## Actual result:
Sync is displayed in settings:
![screen shot 2018-12-19 at 10 46 59 am](https://user-images.githubusercontent.com/28145373/50232005-0b307b00-037e-11e9-8dd4-cdb7905efe4c.png)

## Expected result:
Since sync is disabled by default due to https://github.com/brave/brave-browser/issues/2609, it should not be displayed in settings.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.58.15 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? n/a

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
As expected, sync is not available from hamburger menu and navigating to brave://sync results in an error.

**Comment by darkdh** [comment]
For channels other than 0.58.x, we need to check if `--disable-brave-sync` hides sync in settings

**Comment by darkdh** [comment]
>For channels other than 0.58.x, we need to check if --disable-brave-sync hides sync in settings

will be addressed in https://github.com/brave/brave-browser/issues/2650

closed by https://github.com/brave/brave-core/pull/1146

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.58.16 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Mac OS X

* Verified test plan in https://github.com/brave/brave-core/pull/1146
