### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by CasperTMP** [brave/brave-browser#26426]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.45.116  Chromium: 107.0.5304.91
Operating System: Windows NT 10.0.22621

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. The browser randomly crashes and I have no idea why, I can start/open the browser and let it run and it still crashes
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/58f40600-c482-0f09-0000-000000000000

**Comment by rebron** [comment]
Hi @CasperTMP Can you update to 1.45.118 and see if that fixes the crash for you.

**Comment by iefremov** [comment]
crashdump is expired, @CasperTMP pls upload more crashes if the issue persists and reopen the ticket
