### ISSUE TITLE
Fix icon layout for `Grid tab switcher for tablets` feature

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#26424]
## Description 
We currently have an issue with this feature (see picture)

![Screenshot_2022-11-01-09-11-36-382](https://user-images.githubusercontent.com/30602739/199243206-5c708ee9-e28a-4666-8458-87ce14f07e35.jpeg)

## Steps to reproduce 

   1. Enable `Grid tab switcher for tablets` in `brave://flags`.
   2. Relaunch.
   3. Icons not grouped properly.

## Actual result 
Icons not grouped properly.

## Expected result
Icons grouped properly.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.46.128` or higher for `1.46.x` verification 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung Galaxy Tab S8 Ultra` running `Android 12` using the following build(s):

```
Brave | 1.46.129 Chromium: 108.0.5359.48 (Official Build) (32-bit)
--- | ---
Revision | 18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}
OS | Android 12; Build/SP2A.220305.013
```

Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/26424#issue-1431427109 & https://github.com/brave/brave-browser/issues/26954#issue-1462270802, ensured the following:

* ensured that the tab switcher icon appears in the correct area on first launch
* ensured that the tab switcher icon appears in the correct area one you open a NTP
* ensured that tapping on the tab switcher works as expected and there's no issues with animation/performance
* ensured that all the currently opened tabs are being listed under the tab overview screen
* ensured that you can open `normal` & `private` windows via the hamburger menu under the tab overview screen
* ensured that you can `Close all tabs` without any issues
   * ensured there's a warning before closing all the tabs
* ensured that you can switch between tabs without any issues
* ensured that you can close individual tabs via the overview screen without any issues

**`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|-----------------
![Screenshot_20221129_013811_Brave](https://user-images.githubusercontent.com/2602313/204459796-aebed6e4-2526-48f5-b269-19166dbcae4c.jpg) | ![Screenshot_20221129_014010_Brave](https://user-images.githubusercontent.com/2602313/204459818-99bd1daf-5157-4f0f-889b-0cb852396f8c.jpg) | ![Screenshot_20221129_013845_Brave](https://user-images.githubusercontent.com/2602313/204459830-07b3b3c1-e20e-481e-8dfb-c81b13e8b157.jpg) | ![Screenshot_20221129_014032_Brave](https://user-images.githubusercontent.com/2602313/204459834-deb58ce6-a115-4f20-bc03-8917d17adc39.jpg)
