### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by goldenchunky101** [brave/brave-browser#26427]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.45.116  Chromium: 107.0.5304.91
Operating System: Windows NT 10.0.19044

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1.open the browser
2. clicked restore windows
3.waited around 5 seconds
4. then it crashed

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/cb1e0700-c482-0f09-0000-000000000000

**Comment by rebron** [comment]
Hi @goldenchunky101 Can you update to 1.45.118 and see if that fixes the crash for you.

**Comment by iefremov** [comment]
Unfortunately, the dump is expired
