### ISSUE TITLE
Crash Report [Update: the cause found, it's Dashboard card "Crypto.com", see comments]

### ISSUE THREAD

**Issue by AlexeyBobkov** [brave/brave-browser#26438]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.45.116  Chromium: 107.0.5304.91
Operating System: Windows NT 10.0.19043

URL (if applicable) where crash occurred:
N/A, new tab page

Can you reproduce this crash?
Yes

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1.Open the Brave browser
2.Minimize it
3.Wait exactly 30 sec.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/024d0700-c482-0f09-0000-000000000000

**Comment by AlexeyBobkov** [comment]
Minimizing is even not necessary. Just the following:
1) Open the Brave browser.
2) Wait 30 sec, don't do anything.
3) It silently crashed.

If I browse any pages and do not leave it idle, it usually works, but sometimes still crashes.

**Comment by AlexeyBobkov** [comment]
I tried the following:
1) Browser full reset
2) Disable hardware acceleration
3) Disable sync

All this doesn't help.

**Comment by AlexeyBobkov** [comment]
After some experiments, I found the cause.

The browser crashes only if the Dashboard card **"Crypto.com"** is enabled.
When I disable the Dashboard card "Crypto.com", the browser is stable.
As soon as I enable this card and open a New Tab page with this card, the browser crashes after 30 sec, no matter what I do on other tabs.

**Comment by rebron** [comment]
hi @AlexeyBobkov Can you update to 1.45.118 and see if that fixes the crash for you.

**Comment by AlexeyBobkov** [comment]
Thanks, it's seems to be fixed in 1.45.118. The browser doesn't crash anymore with the Dashboard card "Crypto.com" enabled.
