### ISSUE TITLE
www.costcophotocentre.ca can't upload photos unless shields are down

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#2644]
## Description 

Going to https://www.costcophotocentre.ca/Home and uploading photos does not work unless shields are down.

## Actual result:

They don't upload.

## Expected result:

It should upload the photos.

## Reproduces how often: 

Always.

## Brave version (brave://version info)

all, button 0.59.x currently

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

Yes.
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields?   Yes.
- Is the issue reproducible on the latest version of Chrome?  No.

**Comment by ryanbr** [comment]
I've re-checked this, created a fake account. I was able to upload from my PC and via Instagram. No issues I could see. If its okay, I'll close this @bbondy

**Comment by ryanbr** [comment]
Closing ticket.
