### ISSUE TITLE
[Android] P3A work to gather average usage data for dormant user engagement

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#26446]
## Description
We are planning to send a number of notifications to re-engage dormant Android users. Full details here:
https://bravesoftware.slack.com/archives/C03MMJ4CHEZ/p1667330665673899?thread_ts=1667330661.351209&cid=C03MMJ4CHEZ

The hook for these notifications will display potential time / battery / mobile data saved per week / month / year. This data will be based on the average users historic usage. We need some P3A work done to handle and calculate the historic data.

## Implementation Details
@iefremov to add.

**Comment by bridiver** [comment]
Please include all relevant details/information in the ticket. Linking to slack is not very transparent for public access and slack discussions are often messy which can make the implementation details ambiguous at best.
