### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by rudeboy1one** [brave/brave-browser#26449]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.45.116  Chromium: 107.0.5304.91
Operating System: Windows NT 10.0.19044

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. when i open the brave browser it shut down atomatically
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/f67a0700-c482-0f09-0000-000000000000

**Comment by rudeboy1one** [comment]
also, i don't know what can happend if i delete and reinstal the browser, i mean, i don't know if i'll have the same brave account, and if is what i said what can i do to keep my brave and fix this issue

**Comment by cbcb00** [comment]
> also, i don't know what can happend if i delete and reinstal the browser, i mean, i don't know if i'll have the same brave account, and if is what i said what can i do to keep my brave and fix this issue

If you have brave on more than one device you can use brave sync to sync your account.

**Comment by rebron** [comment]
Hi @rudeboy1one Can you update to 1.45.118 and see if that fixes the crash for you.
