### ISSUE TITLE
Cookie Consent lost dialog, cannot find

### ISSUE THREAD

**Issue by jtheletter** [brave/brave-browser#26459]
Brave browser for MacOS Version 1.45.116 suddenly flashed a request to disable cookie notices, but it gave no context or info link. I opened a new tab to Google it, and it disappeared. I searched Brave settings for “consent” and “cookie” and found nothing.

Where is this, how do I restore the dialog? Thank you.

**Comment by m77e4t** [comment]
Go to `brave://settings/shields/filters` and just tick mark 'Easylist Cookie'.

The pop-up does not nothing extra-ordinary but just enables the Easylist Cookie. This feature has been in brave for about a year. Now, they are just advertising it (which is a good thing).
