### ISSUE TITLE
Crash Report: Brave crashes randomly

### ISSUE THREAD

**Issue by mrKampie** [brave/brave-browser#26450]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.45.116  Chromium: 107.0.5304.91
Operating System: Windows NT 10.0.22621

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Open Brave
2. Go browsing for 30 seconds or 3 minutes (really random time)
3. Braves crashes at a random moment
4. (I tried all the standard solutions as disabling hardware accelaration and extensions. Nothing works)

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/357f0700-c482-0f09-0000-000000000000

**Comment by rebron** [comment]
Hi @mrKampie and @KevinArce Can you update to 1.45.118 and see if that fixes the crash for you.

**Comment by KevinArce** [comment]
@rebron It worked, thank you!
