### ISSUE TITLE
Submit button doesn't work (loading spinner doesn't show when submitting a ticket) for VPN trouble ticket

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#26454]
## Description 
The code definitely exists - but for some reason it's not showing. Here's a quick demo. It does submit ticket - but takes quite a while. No spinner shown while it's waiting and submit button is not disabled (so you could accidentally click more than once)
![form-submit](https://user-images.githubusercontent.com/4733304/199338768-1891fa58-78e9-4fae-9801-b59559db59d4.gif)

## Steps to Reproduce / test plan

   1. Enable brave://flags/#brave-vpn
   2. Login to account.bravesoftware.com and purchase VPN
   3. Click "VPN" button (next to hamburger menu) and panel comes up
   4. open the tech support section
   5. Fill out the form and hit `Submit`

## Expected result
- Form should lock
- Spinner should show
- Ticket should submit

## Actual result
- nothing happens

**Comment by kjozwiak** [comment]
The above requires `1.46.97` or higher for `1.46.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.46.122 Chromium: 108.0.5359.48 (Official Build) beta (x86_64)
-- | --
Revision | 18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}
OS | macOS Version 11.7.1 (Build 20G918)

### Steps:
   0. deleted previous `BraveVPN` OS-configs, first
   1. installed `1.46.122`
   2. launched Brave using `--vmodule="*/skus/*"=2 --enable-logging=stdrr --v=1`
   3. clicked `Maybe later`
   4. clicked `Skip welcome tour`
   5. opened `brave://flags`
   6. set `brave://flags/#brave-vpn` to `Enabled`
   7. clicked `Relaunch` (if you want to retain logging, `CTRL+C` and relaunch from `Terminal`/console
   8. clicked `No thanks` on the `Tired of cookie consent notices?` dialog
   9. loaded `account.bravesoftware.com`
   10. entered staging credentials from 1Password
   11. entered `issue26523@mailinator.com` from that issue's previous testrun
   12. clicked `Get login link`
   13. opened the `Log in to your Brave Pre...` email (`https://www.mailinator.com/v4/public/inboxes.jsp?to=issue26523` in the above case)
   14. clicked on either the `Log in to Brave` button -or- the link below it
   15. clicked `Browse plans` on `https://account.bravesoftware.com/account/`
   16. scrolled down
   17. clicked on `Buy now` beneath `Brave VPN Subscription`
   18. complete the Stripe checkout using `https://stripe.com/docs/testing#testing-interactively`
   19. clicked on the `VPN` button in the browser toolbar, added the config, and connected to `BraveVPN`
   20. clicked on the `Settings` gear icon
   21. clicked on `Contact technical support`
   22. tested a few validation cases
   23. submitted a valid request
   24. confirmed request received with Shannon from Guardian

`step 19` | `step 22` | `step 22` | `step 23` | `step 24`
---------|---------|-----------|---------|---------
<img width="1312" alt="Screen Shot 2022-11-22 at 1 31 58 PM" src="https://user-images.githubusercontent.com/387249/203429790-a3406cff-1474-44b1-ad42-527634dc4d1a.png"> | <img width="1312" alt="Screen Shot 2022-11-22 at 1 41 06 PM" src="https://user-images.githubusercontent.com/387249/203429794-109056d7-7b89-4a74-8e45-652081a24e59.png"> | <img width="1312" alt="Screen Shot 2022-11-22 at 1 41 18 PM" src="https://user-images.githubusercontent.com/387249/203429795-0bc2b328-f1e1-4743-87fd-58348d374c5e.png"> | <img width="1312" alt="Screen Shot 2022-11-22 at 1 42 26 PM" src="https://user-images.githubusercontent.com/387249/203429800-1572c518-09d6-4ebd-97a8-b23635af86de.png"> | <img width="1215" alt="Screen Shot 2022-11-22 at 2 45 35 PM" src="https://user-images.githubusercontent.com/387249/203430016-1c80ce84-4666-4902-8d1a-31c4eed3a0a5.png">
