### ISSUE TITLE
Add support for custom tip amount for publishers

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#2645]
We are getting tip amount for publisher custom banner. We need to add support for it. This needs to be reflected in site banner and panel where user can chose this amounts.

**Comment by kjozwiak** [comment]
As @NejcZdovc mentioned above, changing the tip amounts on the Publishers website isn't being reflected under the Brave client. Quick example for more context:

Here's a preview of my banner under the Publishers website (notice the custom tips):

<img width="1407" alt="screen shot 2018-12-18 at 11 15 34 pm" src="https://user-images.githubusercontent.com/2602313/50246718-14344300-03a4-11e9-8ba2-3fbc4e5c3295.png">

Here's my actual website that's serving the new banner that I've created via Publishers (notice that the custom tips haven't been used):

<img width="1404" alt="screen shot 2018-12-18 at 11 13 24 pm" src="https://user-images.githubusercontent.com/2602313/50246759-3928b600-03a4-11e9-8b5c-02c16cbe02ed.png">

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.59.14 Chromium: 72.0.3626.28 (Official Build) beta(64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Mac OS X

* Verified tipping banner shows custom amounts set on publisher website:
![screen shot 2019-01-03 at 9 14 44 am](https://user-images.githubusercontent.com/28145373/50642065-0d770580-0f38-11e9-9032-0b0ea2ce0300.png)

**Comment by kjozwiak** [comment]
Attempted to tip `500` BAT to `kjozwiakstaging.github.io` via staging and ran into the following error:

```
[ RESPONSE - ReconcilePayloadCallback ]
> time: 1546891257
> result: Failure
> response: {"statusCode":503,"error":"Service Unavailable","message":"surveyor 6KTixOtZEpwfT4prbgyTG0MlPSwri6OsKsl1bSR+BuJ has 435 control surveyors, but needed 1454"}> headers cache-control: no-cache
> headers connection: keep-alive
> headers content-encoding: gzip
> headers content-type: application/json; charset=utf-8
> headers date: Mon, 07 Jan 2019 20:00:57 GMT
> headers retry-after: 5
> headers server: Cowboy
> headers transfer-encoding: chunked
> headers vary: accept-encoding
> headers via: 1.1 vegur
> headers x-rate-limit-limit: 60
> headers x-rate-limit-remaining: 59
> headers x-rate-limit-reset: 1546891317
[ END RESPONSE ]
```

It appears that the back-end doesn't support 500 BAT tips. Publishers team will change/remove the 500 BAT choice from the Publishers website.

**Comment by ChildishGiant** [comment]
I'd love if there was a way for a user to type in how many BAT they want to send, that way the user can give as much or as little as they want. I guess some publishers wouldn't want this so maybe they could set a min & max or just disable the custom amount option. Here's a terrible 30 second mockup 
![image](https://user-images.githubusercontent.com/13716824/57456623-cc845a00-7265-11e9-92b9-b20e1ea52161.png)

**Comment by leshacat** [comment]
I second this feature

**Comment by SYK-08** [comment]
I am not able to add a custom tip amount on Brave Mobile, please help.

**Comment by LaurenWags** [comment]
@SYK-08 custom tip amount will be implemented on Android with https://github.com/brave/brave-browser/issues/16021
