### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by KevinArce** [brave/brave-browser#26452]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.45.116  Chromium: 107.0.5304.91
Operating System: Windows NT 10.0.25231

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Open Brave 
2. Go to any website (Youtube, Reddit, etc) 
3. Wait a couple of minutes, sometimes it takes around 15 minutes and other times around 1 minute

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/70840700-c482-0f09-0000-000000000000

**Comment by rebron** [comment]
Hi @KevinArce Can you update to 1.45.118 and see if that fixes the crash for you.

**Comment by KevinArce** [comment]
It worked, thank you
