### ISSUE TITLE
Wrong fonts on https://brendaneich.github.io/sieve/

### ISSUE THREAD

**Issue by pilgrim-brave** [brave/brave-browser#26458]
Text should be monospaced but is displayed in a proportional font. As per discussion in Slack, this is likely caused by font whitelisting. CSS uses `font-family: "Courier"` and relies on font engine to substitute a modern monospaced font like Courier New.

**Comment by pilgrim-brave** [comment]
Affects Mac and Windows only. Linux desktop build currently has no font whitelist, and Android already has "Courier" on the whitelist for unrelated reasons.

**Comment by LaurenWags** [comment]
@pes10k @pilgrim-brave since this has `QA/Yes`, a test plan is needed. 

Marking as `QA/Blocked` until there is one.

cc @kjozwiak @rebron

**Comment by pes10k** [comment]
@pilgrim-brave do we have a browser test for this?  If so, i think we can `QA/No` it, wdyt?

**Comment by pilgrim-brave** [comment]
We do not have automated testing for this. Visit the link in the title, right-click any number in the grid, go to Computed tab in devtools, scroll down to Rendered Fonts section to see what font it's actually using for rendering. Correct answer on Mac is "Courier", as per this screenshot:
![image](https://user-images.githubusercontent.com/43750833/205396348-328d858c-e4f6-47ee-a692-466730c297e7.png)

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.47.110 Chromium: 108.0.5359.71 (Official Build) beta (x86_64)
-- | --
Revision | 1e0e3868ee06e91ad636a874420e3ca3ae3756ac-refs/branch-heads/5359@{#1016}
OS | macOS Version 13.1 (Build 22C5059b)




### Steps:
1. installed `1.47.110`
2. launched Brave
3. loaded `https://brendaneich.github.io/sieve/`
4. opened `Developer Tools` and inspected an element
5. looked at its `font-family`

#### Confirmed the `font-family` used is `Courier`

<img width="1312" alt="Screenshot 2022-12-03 at 6 41 54 PM" src="https://user-images.githubusercontent.com/387249/205471564-ae2de690-9297-483b-9484-7c5c81dfe2c8.png">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED`
```
Brave | 1.47.125 Chromium: 108.0.5359.99 (Official Build) beta (64-bit)
-- | --
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | Windows 11 Version 21H2 (Build 22000.1219)
```

### Steps:
1. installed `1.47.110`
2. launched Brave
3. loaded `https://brendaneich.github.io/sieve/`
4. opened `Developer Tools` and inspected an element
5. looked at its `font-family`

#### Confirmed the `font-family` used is `Courier`



![image](https://user-images.githubusercontent.com/98358127/207199127-02fa222f-c240-4c8d-b62d-60481da1a301.png)
