### ISSUE TITLE
Copy Clean Link should remove IDs if they're used like URL parameters

### ISSUE THREAD

**Issue by RobotoSkunk** [brave/brave-browser#26467]
## Description 
An Argentinian website called [Mercado Libre](https://www.mercadolibre.com.mx/) uses IDs instead of URL parameters to track their users, and maybe there are others websites that does the same. I think IDs should be removed too if they're being used like URL parameters

## Steps to Reproduce
   1. Go to [Mercado Libre](https://mercadolibre.com.mx/).
   2. Click on a recommended article.
   3. Go to URL bar and copy the URL using "Copy Clean Link"

## Actual result:
https://www.mercadolibre.com.mx/microfono-sf-666-condensador-omnidireccional-negro/p/MLM15161567#reco_item_pos=2&reco_backend=machinalis-homes-pdp-boos&reco_backend_type=function&reco_client=home_navigation-recommendations&reco_id=25e5f982-4a90-4c44-854e-58dfca856fee&c_id=/home/navigation-recommendations/element&c_element_order=3&c_uid=3b680aeb-99b0-4c14-9882-5863aedb5d51

## Expected result:
https://www.mercadolibre.com.mx/microfono-sf-666-condensador-omnidireccional-negro/p/MLM15161567

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
```
Brave | 1.45.116 Chromium: 107.0.5304.91 (Official Build) (64-bit)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | Windows 10 Version 21H1 (Build 19043.2130)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes (1.45.x)
- Can you reproduce this issue with the beta channel? Not yet tested
- Can you reproduce this issue with the nightly channel? Not yet tested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
N/A

**Comment by fmarier** [comment]
Merging with https://github.com/brave/brave-browser/issues/28997 since they are the same suggestion.
