### ISSUE TITLE
[Brave News] The Brave News V2 page should be updated to match new design specs

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#26462]
After some discussion with the designers, we've worked out a more consistent design for the home page:
1. Popular sources should appear first
2. Suggestions should appear second
3. Channels should appear third
4. All channels should be visible
5. Popular/Suggestions should appear in a Carousel, with a view all link taking you to a full page view
6. We should remove the `All Sources` section

**Comment by kjozwiak** [comment]
The above will require `1.46.100` or higher for `1.46.x` verification 👍

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.46.100 Chromium: 107.0.5304.91 (Official build) dev (x86_64)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | macOS Version 11.7.1 (Build 20G918)

### Steps:
1. launched Brave
2. clicked on Skip welcome tour
3. opened brave://flags
4. set brave://flags/#brave-news-v2 to Enabled
5. clicked Relaunch
6. opened a new-tab page
7. clicked on Customize
8. clicked on Brave News
9. clicked on Turn on Brave News
10. checked the Customize Brave News dialog

Confirmed the following changes:
* Popular sources appeared first
* Suggestions appeared second (after following a few sources, then returning to this dialog)
* Channels appeared third
* All channels were visible (no `Show more` button)
* Popular & Suggestions appeared in a carousel, with a View All link taking me to a full page view
* removed previous Sources section

`order of appearance` | `all channels visible` | `carousel`
-----------------------|----------------------|-----------
