### ISSUE TITLE
Align layout constants of vertical tabs to sidebar

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#26463]
- [x] Min width should be the same with sidebar
  <img width="335" alt="image" src="https://user-images.githubusercontent.com/5474642/199421738-ab549405-30e0-49ff-b735-796801fb64bc.png">

- [x] Tab heights should be the same with sidebar item.
  <img width="321" alt="image" src="https://user-images.githubusercontent.com/5474642/199409338-4a31c8bc-5fbc-4d64-9d6e-bcda43082a40.png">

**Comment by Coffeeling** [comment]
Not a fan of the new chonky spacing. Compact spacing back please? I the aligned spacing looks nice in screenshots, but I don't think it has too much extra value - I'd much rather have a better overview of my tabs, and the compact layout serves that need much better. (I moved the sidebar to the right anyway, so different item sizes aren't really jarring that way either.)

**Comment by sangwoo108** [comment]
cc. @rebron @aguscruiz Please check out the feedback ^

**Comment by sangwoo108** [comment]
Another feedback: https://github.com/brave/brave-browser/issues/24717#issuecomment-1305021262

**Comment by Coffeeling** [comment]
Another user preferring the compact tab list: https://github.com/brave/brave-browser/issues/464#issuecomment-1309183076
