### ISSUE TITLE
brave intermittently crashes when selecting certain SE from the onboarding modal

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#26464]
## Description 

Looks like there's an intermediate crash when selecting specific search engines from the SE onboarding screen. Basically ran into this crash while running through https://github.com/brave/brave-core/pull/15669. For my particular case, it's crashing when selecting `Qwant`.

## Steps to reproduce 

   1. change the device local to `Brazil` and install `1.47.20 Chromium: 107.0.5304.68`
   2. launch brave and skip through the initial onboarding
   3. tap on the URL bar (shouldn't get the SE onboarding modal)
   4. tap on the URL bar for the second time and you should see the SE onboarding modal
   5. select `Qwant` from the modal

You'll notice that Brave crashes intermediately. 

## Actual result 

https://user-images.githubusercontent.com/2602313/199414878-06f854d7-cbfc-44df-9d8a-32ebe7de4828.mp4

## Expected result

Brave shouldn't be crashing when selecting a default SE via the SE onboarding modal.

## Issue reproduces how often 

It's pretty easy to reproduce using the STR/Cases mentioned above. I would say ~80% reproduction rate.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `Yes`
- Can you reproduce this issue with the current Play Store Beta version? `Yes` 
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details

   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Samsung Galaxy S10+`
   - Android version: `Android 12`
   
## Brave version

```
Brave | 1.45.116 Chromium: 107.0.5304.91 (Official build) 32 bits
--- | ---
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | Android 12; Build/SP1A.210812.016
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

### Additional information

CCing @bsclifton @Uni-verse @timchilds @anthonypkeane @deeppandya

**Comment by deeppandya** [comment]
@kjozwiak would you be able to verify it ? i think it should be resolved.

**Comment by kjozwiak** [comment]
> @kjozwiak would you be able to verify it ? i think it should be resolved.

@deeppandya yup, lets close this off. Using `1.46.154 Chromium: 108.0.5359.128`, I went through the same STR/Cases mentioned above via the following locales:

* `Brazil` - now has `Brave` as the default SE but tried a few time either way and ensured that tapping on the omnibox several times doesn't initiate the SE onboarding nor crash Brave
* `Poland` - went through the STR several times re: selecting `Qwant` as the default (went through all other choices as well)
* `Japan` - went through the STR several times re: selecting `Qwant` as the default (went through all other choices as well)
* `Portugal` - went through the STR several times re: selecting `Qwant` as the default (went through all other choices as well)

While running through the above, never experience a crash. It used to be pretty reproducible using `Brazil` which isn't a valid case anymore as mentioned above.
