### ISSUE TITLE
`Ask when to save files` still shown in Download settings

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#26475]
## Description 
`Ask when to save files` still shown in Download settings

## Steps to reproduce 

   1. Clean install
   2. Open Menu -> Downloads -> Settings
   3. `Ask when to save files` is still shown

## Actual result 

https://user-images.githubusercontent.com/17010094/199478082-b63203ee-1cfe-4908-b3d7-03d151d5ac69.mp4

## Expected result
Should not show as per https://github.com/brave/brave-browser/issues/25687 & brave/brave-core#15269

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Not checked

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 12
   
## Brave version
1.46.87 x64 Beta build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @samartnik

**Comment by kjozwiak** [comment]
The above requires `1.46.131` or higher for `1.46.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` & `Samsung Galaxy Tab S7` using version(s):

```
Brave	1.46.131 Chromium: 108.0.5359.71 (Official Build) (64-bit) 
Revision	1e0e3868ee06e91ad636a874420e3ca3ae3756ac-refs/branch-heads/5359@{#1016}
OS	Android 12; Build/SP1A.210812.016
```

STR: https://github.com/brave/brave-browser/issues/26475#issue-1432979988

- Verified `Ask when to save files` is not shown in Download settings page
- Ensured switches are operable 
- Ensured switch state is saved

Example | Example
-|-
![screenshot-1669861563227](https://user-images.githubusercontent.com/17885425/204951287-d1704644-b3e1-41ba-abcc-5367d26a0da2.png) | ![screenshot-1669861852160](https://user-images.githubusercontent.com/17885425/204951781-109d79f0-55c7-4ce6-a0dc-6afa5da10bf0.png)
