### ISSUE TITLE
Wallet shows wrong network when signing DApps messages/transaction 

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#26476]
## Description 

When signing Solana transaction with the selected Ethereum network then the network (Ethereum) is incorrectly shown on Desktop panel.
Origin issue with more details and media: https://github.com/brave/brave-browser/issues/26397

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.47.164 Chromium: 109.0.5414.74 (Official Build) (64-bit)
-- | --
Revision | `e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}`
OS | Linux

- Verified steps from [brave/brave-core#15873](https://github.com/brave/brave-core/pull/15873)
- Verified correct network name is shown when Signing Dapps messages/transactions

https://user-images.githubusercontent.com/17010094/211366247-1e8e6d84-eea5-45df-a262-d0aac58e5f17.mp4


---------------------

Verification passed on 

Brave | 1.47.164 Chromium: 109.0.5414.74 (Official Build) (64-bit)
-- | --
Revision | `e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#15873](https://github.com/brave/brave-core/pull/15873)
- Verified correct network name is shown when Signing Dapps messages/transactions

https://user-images.githubusercontent.com/17010094/211365958-e1337fbe-b4ad-49ad-b3d5-874890363fcb.mp4

---------------------

Verification passed on 

Brave | 1.47.164 Chromium: 109.0.5414.74 (Official Build) (arm64)
-- | --
Revision | `e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#15873](https://github.com/brave/brave-core/pull/15873)
- Verified correct network name is shown when Signing Dapps messages/transactions

https://user-images.githubusercontent.com/17010094/211365517-8f5c31d0-4340-4c0d-b4ed-beffea3fdc0c.mov
