### ISSUE TITLE
Brave Rewards stuck disabled.

### ISSUE THREAD

**Issue by a-triant** [brave/brave-browser#26484]
## Description 
The Brave Rewards in settings shows as disabled, at same it's looks like enabled and i getting reward for views. Had it enabled for long time, before it was even linked to Gemini.

![Screenshot 2022-11-02 195439](https://user-images.githubusercontent.com/22340405/199571485-40365391-80d1-4cf8-9eda-7466189bb9b5.png)

If i switch to Brave Rewards tab, then i have what i show in the screenshot below, a screen with the "Start using Brave Reward" button, if i click it then opens the Brave reward icon, which you see in the same screenshot on the right side, if there i click on settings or Unverified then it again opens the screen with the "Start using Brave Reward" button.

![Screenshot 2022-11-02 194313](https://user-images.githubusercontent.com/22340405/199573510-6bd85eb0-e52c-47fd-b378-7e1161cd4dee.png)

Any way to resolve this? I don't want to reset the browser since this will lead to lose of rewards...

## Reproduces how often: 
Always.

## Brave version (brave://version info)
1.45.118 Chromium: 107.0.5304.91 (Official Build) (64-bit)

**Comment by Miyayes** [comment]
Thanks for reporting this. We think this will be solved by 1.46.x, but we're working to see if we can get a hotfix out in about a week from now.

**Comment by LaurenWags** [comment]
Closing issue as it is resolved by https://github.com/brave/brave-core/pull/15832.

Requires `1.45.124` or higher to test.

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```
Brave | 1.45.125 Chromium: 107.0.5304.110 (Official Build) (64-bit)
-- | --
Revision | 2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}
OS | Windows 10 Version 21H2 (Build 19044.2251)

```
Reproduced the issue using `1.45.123` and steps from below.

<details>
<summary>Steps</summary>

Verified test plan from https://github.com/brave/brave-core/pull/15832#issue-1438934848

1. Start browser with a clean profile.
2. Relaunch to pull griffin. 
3. Enable Rewards.
4. Close browser.
5. Open the `Preferences` file in a text editor.
6. Find the "enabled" property (under "brave" and "rewards"), and delete it.
7. Start the browser and visit the Rewards page.
8. Verify that the Rewards page is displayed correctly.

</details>

"Upgraded" the 1.45.x profile to 1.45.125 and confirmed issue is resolved. 

1.45.123 | 1.45.125 
---------|-----------
![image](https://user-images.githubusercontent.com/38657976/201351174-57969bca-ecc0-489b-ae4c-80264cb4527a.png) | ![image](https://user-images.githubusercontent.com/38657976/201351998-6151350a-005b-4314-8b02-b9ab34f9be33.png)
