### ISSUE TITLE
Add fallback button when ipfs page can't be loaded

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#26486]
![image](https://github.com/brave/brave-browser/assets/106654560/296cc5ef-76c5-4052-a44f-17aa0b5a6a65)
We have a feature which auto-redirects to ipfs:// resources when dnslink or gateway-like url is loaded.
We should give an opportunity to the user to load original url in case ipfs url can't be loaded.

There are several cases we should handle:
1) Cannot resolve remote gateway or cannot start local node, so chromium error page is shown
2) Remote gateway is resolved but resource is not loaded since it is not available. Like https://ipfs.io/ipfs/123
3) Local gateway is started but we block request because CID or IPNS is invalid : ipfs://123 or ipns://abc.com
4) Local gateway is started but it cannot resolve CID or IPNS since it has network problems or resource is unavailable.

Probably the easiest way would be to show fallback Infobar witch suggest to load original url neither to show error page in all cases.

Redirect logic is mostly covered in ipfs_tab_helper

Follow up: Same functionality but when redirect is fired by <ipfs> addressbar button or ipfs promo infobar

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.62.97 Chromium: 120.0.6099.56 (Official Build) beta (64-bit)
-- | --
Revision | 9561bb49dc23c407275af722586f045356609329
OS | Linux

- Verified steps from [ brave/brave-core#20403](https://github.com/brave/brave-core/pull/20403)
- Verified with network blocked and `Automatically redirect requests for IPFS network resources to the configured gateway.` set to on and `Method to resolve IPFS resource` set to `Brave local IPFS node`, a new info bar is shown with `Redirect` and `No thanks`
- Verified clicking on `Redirect` button on the infobar redirects to the public gateway link
- Verified clicking on `No thanks` button on the infobar tries to load via localhost

https://github.com/brave/brave-browser/assets/17010094/fb8de9f0-0685-4ffe-9411-d5185f87ab30
