### ISSUE TITLE
Setting the Search Engine Preference should set that preference for both normal and private windows

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#26483]
## Description 
Some context: https://bravesoftware.slack.com/archives/C01NNFM9XMM/p1667370541619929

On Android we ask users to select a search engine during onbaording. That selection should set the search engine preference for both normal and private tabs. 

In some countries, for new users we set Brave as the default search engine. This default should be set for both normal and private tabs also (same logic) 

More recently we asked existing users if they would like to set Brave Search as default, if they say Yes, again we should follow the same logic and set the search engine selection for both Private & Normal tabs

**Comment by Uni-verse** [comment]
In progress on Samsung Galaxy S21 using version:

Brave	1.47.165 Chromium: 109.0.5414.80 (Official Build) (64-bit) 
Revision	0f69b168d36a06cace4365e9f029fa987afa5633-refs/branch-heads/5414@{#1178}
OS	Android 12; Build/SP1A.210812.016
