### ISSUE TITLE
Cmd-Comma ungroups all tabs from all groups in a brave window

### ISSUE THREAD

**Issue by m-ammar** [brave/brave-browser#26487]
## Description 
When I have multiple tab groups in a Brave window, and I press Cmd+, to open browser settings, all the browser tabs get ungrouped with each group having only one browser tab.

## Steps to Reproduce

   1. Open a brave browser window on a Macbook computer
   2. Add multiple tab groups
   3. Add more than one browser tab to each tab group
   4. Then press "Cmd + ," to open browser settings

## Actual result:
All browser tabs that are in a tab group will get ungrouped and become normal browser tabs.

## Expected result:
Browser should open Browser settings window

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.45.116 Chromium: 107.0.5304.91 (Official Build) (x86_64)
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | macOS Version 12.6.1 (Build 21G217)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Haven't tried
- Can you reproduce this issue with the nightly channel? Haven't tried

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Not a website issue
- Does the issue resolve itself when disabling Brave Rewards? Rewards is already disabled
- Is the issue reproducible on the latest version of Chrome? Yes

**Comment by rebron** [comment]
@m-ammar I'm not able to reproduce your steps. Looks like doing "Cmd + ," just adds brave://settings as a normal tab to the end of the list and not effecting opening or closing any tab groups. Do you have an extension installed that maybe conflicting or some brave://flags you turned on?

**Comment by m-ammar** [comment]
Maybe you are right @rebron . I just disabled and check and I couldn't reproduce it either. Thanks. I'll close this issue.
