### ISSUE TITLE
Add ipns support for redirect gateway-like urls feature

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#26485]
According specs /ipns/ gateway-like urls should also be parsed.
https://github.com/ipfs/ipfs-docs/blob/feat/how-to-implement-support-in-a-web-browser.md/docs/how-to/detect-ipfs-on-web.md

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.48.155 Chromium: 110.0.5481.77 (Official Build) (64-bit) 
-- | --
Revision | `65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}`
OS | Linux

- Verified steps from [ brave/brave-core#15850](https://github.com/brave/brave-core/pull/15850)
- Verified IPNS redirect  urls work as expected

https://user-images.githubusercontent.com/17010094/216670770-dd89ffc5-2833-483d-9aef-8ef1b0294609.mp4
