### ISSUE TITLE
Class/id cosmetic selectors intermittently missed

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#26492]
Cosmetic filtering uses a [hidden_class_id_selectors](https://github.com/brave/adblock-rust/blob/master/src/cosmetic_filter_cache.rs#L209-L227) routine to query for CSS to inject based on the classes of elements newly added to the page or modified, using an in-page MutationObserver. That applies to generic cosmetic rules that can be queried by a particular class or id selector that must appear in the page; i.e. rules of the form `##.class-selector` or `###id-selector`.

We've noticed a handful of instances where rules of this form fail to be applied to pages. @ryanbr has been manually adding workarounds for these rules, of the form e.g. `##div.class-selector`, which tricks Brave's adblock engine into injecting these rules into _all_ pages rather than finding them during MutationObserver queries. But this is not ideal, and we should discover and fix the root cause.

**Comment by antonok-edm** [comment]
One example: https://websummit.com has a cookie banner which is intermittently affected by this. Workaround: https://github.com/easylist/easylist/commit/d9b99af1

**Comment by antonok-edm** [comment]
Another example: https://yourcountdown.to/. I'm not able to see the cookie banner personally but it was supposedly fixed with `##.gdprcookie` -> `##div.gdprcookie`

**Comment by ryanbr** [comment]
https://www.shoop.de/  -> ##.cookies-bottom-banner

**Comment by antonok-edm** [comment]
https://charac.co.uk/ -> `###gdprbanner`

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.46.129 Chromium: 108.0.5359.48 (Official Build) (64-bit)
-- | --
Revision | 18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}
OS | Windows 10 Version 21H2 (Build 19044.2251)

```
Used a clean profile on 1.46.x and STR from https://github.com/brave/brave-core/pull/15930#issue-1447010515 and confirmed there was no cookie consent banner on initial load of `https://websummit.com/`. Refreshed (normal and hard refresh) several times, confirmed no cookie consent banner. 


![image](https://user-images.githubusercontent.com/38657976/204506401-55817083-1814-44ce-a6ee-44f17c401a60.png)

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using the following build(s):

```
Brave	1.46.133 Chromium: 108.0.5359.71 (Official Build) (64-bit) 
Revision	1e0e3868ee06e91ad636a874420e3ca3ae3756ac-refs/branch-heads/5359@{#1016}
OS	Android 12; Build/SP1A.210812.016
```

Created a follow up issue regarding the cookie consent banner: https://github.com/brave/brave-browser/issues/27098

Example | Example | Example
-|-|-
![screenshot-1669917418929](https://user-images.githubusercontent.com/17885425/205135314-d3b1117c-30f8-4b26-a9b3-dec523b27fe5.png) | ![screenshot-1669917436102](https://user-images.githubusercontent.com/17885425/205135319-726fff26-5c0e-4366-911a-ddeab350b4ea.png) | ![screenshot-1669917454131](https://user-images.githubusercontent.com/17885425/205135320-367f3292-33e4-44c0-a764-94d4fb8addad.png)
