### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by grobarko** [brave/brave-browser#26490]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.45.116  Chromium: 107.0.5304.91
Operating System: Mac OS X 12.6.0

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Brave crashes every time I open it. Sometimes after a couple of seconds. Sometime after a couple of minutes.
2. I'm not doing anything special, reading articles, scrolling through some web pages... and all of a sudden, it crashes
3. The issue started on November 1st.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/daa40000-f0bb-1809-0000-000000000000

-----------------------------------------------------------------
Hi everyone. Brave is crashing almost non-stop for me since yesterday. 
Here are some screenshots from brave://crashes/

![Screenshot 2022-11-02 at 23 45 03](https://user-images.githubusercontent.com/12982562/199616548-cc0f65dd-e278-4d91-ac43-398070c059a0.png)

![Screenshot 2022-11-02 at 23 45 42](https://user-images.githubusercontent.com/12982562/199616629-77e4df88-bcb0-4a9a-b14b-f349f807aafd.png)

So, these are all related:
Uploaded crash report ID: | daa40000-f0bb-1809-0000-000000000000
Uploaded crash report ID: | bdb70800-c482-0f09-0000-000000000000
Uploaded crash report ID: | e2d50600-c482-0f09-0000-000000000000
Uploaded crash report ID: | 64730800-c482-0f09-0000-000000000000
Uploaded crash report ID: | 8aa20700-c482-0f09-0000-000000000000
Uploaded crash report ID: | 7e210700-c482-0f09-0000-000000000000

Please look into it. I don't want to have to go back to Chrome 😱

**Comment by rebron** [comment]
Hi @grobarko Can you update to 1.45.118 and let us know if you're still experiencing the crash. Go to brave://settings/help to grab it.

**Comment by grobarko** [comment]
Tnx @rebron. I just updated and I'll let you know how's the behaviour after I use it for a while
![Screenshot 2022-11-03 at 08 43 48](https://user-images.githubusercontent.com/12982562/199669345-45c462f8-879d-4842-866b-d3799f9de97f.png)
