### ISSUE TITLE
Desktop Brave News should be enabled by default

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#26494]
## Test Plan
- Fresh user profile directory, no flags changed
- Open NTP
- Opt in to Brave News
- Open Brave News customize
Expected: The new Brave News customize experience is shown

<img width="1208" alt="image" src="https://user-images.githubusercontent.com/741836/199647407-b05870af-72f7-45ba-8d5b-8daf5e634645.png">

**Comment by kjozwiak** [comment]
The above requires `1.46.107` or higher for `1.46.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.46.121 Chromium: 108.0.5359.48 (Official Build) beta (64-bit)
-- | --
Revision | 18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}
OS | Windows 11 Version 21H2 (Build 22000.1219)
```
Steps: 

1. installed 1.46.121
2. clicked `Skip welcome tour`
3. clicked on Customize
4. confirmed `Turn on Brave News` screen displayed
5. clicked on the `Turn on Brave News` button 
6. confirmed  the Brave News v2 UI displayed
7. visited `brave://flags`

#### Confirmed `Enable Brave News V2` was set to Default

step 4|step 5|brave://flags
----|-----|-------
<img width="944" alt="image" src="https://user-images.githubusercontent.com/98358127/203140965-bbc75a7b-242b-4f23-a89e-09a2c1fe405e.png">|<img width="947" alt="image" src="https://user-images.githubusercontent.com/98358127/203141040-8187523f-7310-42da-9071-45f7a5364507.png">|<img width="947" alt="image" src="https://user-images.githubusercontent.com/98358127/203141149-d8411991-5633-4bd1-8ec3-c61ee54db0a6.png">
