### ISSUE TITLE
brave://rewards fails to create wallet in certain browser profile state

### ISSUE THREAD

**Issue by Liunkae** [brave/brave-browser#2649]
## Description 
My browser profile is stuck in a state in which brave://rewards does not work properly. If I restart with a fresh profile, brave://rewards works correctly. I have used this profile for a few weeks over a few versions of Brave. If it would help with debugging, I can send my profile to someone at Brave.

## Steps to Reproduce
   1. Start with an existing profile with Brave Rewards not enabled.
   2. Go to brave://rewards
   3. Click the "Yes, I'm In!" button.

## Actual result:
Clicking "Yes, I'm In!" or "Try again" repeatedly shows the following error (even when my Internet connection is fine):
![image](https://user-images.githubusercontent.com/19424103/50239475-e0e3bb00-0387-11e9-800a-fc778b623c3c.png)

## Expected result:
Brave Rewards should turn on properly. It works fine with a fresh profile:
![](https://user-images.githubusercontent.com/19424103/50239964-2d7bc600-0389-11e9-8ed8-3fea4ef28f5b.png)

## Reproduces how often: 
Always reproduces in my current profile, but does not reproduce with a fresh profile.

## Brave version (brave://version info)
Brave | 0.60.3 Chromium: 71.0.3578.98 (Official Build) dev(64-bit)
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Yes, 0.60.3 dev.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? Not applicable.
- Is the issue reproducible on the latest version of Chrome? Not applicable.

### Additional Information
In #2605, brave://rewards does not even load. With this issue, the page does load, but the wallet does not load.

**Comment by unggulzmalqp** [comment]
I also run into this issue, what can I provide to help resolve this?

**Comment by Liunkae** [comment]
Duplicate of #2997

**Comment by NejcZdovc** [comment]
closing as dupe

**Comment by netowww** [comment]
Same problem here! What can I do to help and solve the problem?

**Comment by NejcZdovc** [comment]
this problem was fixed with https://github.com/brave/brave-core/pull/1839

**Comment by Kinzowa** [comment]
I have this problem since I restared my browser (or maybe my Ubuntu). `chrome://rewards/ `show correct information about my wallet but when i click the small icon to tips website I have the `Wallet creation failed `error.

**Comment by thadfollowill** [comment]
I'm facing this problem as well too, wondering if anyone has found a solution for this?

**Comment by jackowski626** [comment]
same

**Comment by archae0pteryx** [comment]
v1.0.0 is doing this as well.
