### ISSUE TITLE
Strict fingerprint blocking generates strange WebGL Vendor & Renderer value 

### ISSUE THREAD

**Issue by ghost** [brave/brave-browser#26508]
## Description 
Strict fingerprint blocking generates strange WebGL Vendor & Renderer value. According to EFF generated value is `fvXrVKFi~ePHDBAgw` which mean one in 223253 browsers have this value which is very unique.

## Steps to Reproduce
   1. Launch Brave
   2. Set Shields > Block fingerprinting option to 'Strict, may break sites'
   3. Proceed to [EFF CoverYourTracks](https://coveryourtracks.eff.org) and test browser's fingerprint

## Actual result:
![image](https://user-images.githubusercontent.com/114309523/199746207-b4398572-f982-414a-9366-751519bd1ccd.png)

## Expected result:
![image](https://user-images.githubusercontent.com/114309523/199746293-4a89aaa2-c71f-485a-aa39-2fd34b2b6fcc.png)

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
1.45.118 Chromium: 107.0.5304.91 (Official Build) (arm64)

## Version/Channel Information:
- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Unable to test

**Comment by DesignerOff** [comment]
This appears as to be fixed in: `[Version 1.48.171 Chromium: 110.0.5481.177 (Official Build) (arm64)](https://brave.com/latest/)`

**Comment by ShivanKaul** [comment]
This is expected behaviour. With strict fingerprinting, those strings are randomized per-registrable-domain, per-browsing-session, per-user. We've reached out to EFF to see if they can account for this in their tests (they do it for other APIs).
Also, we're planning on deprecating the strict fingerprinting mode altogether: https://github.com/brave/brave-browser/issues/31229
