### ISSUE TITLE
Incorrect response value for the wallet selection "None"

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#26500]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/25659
Incorrect response value for the wallet selection "None"
## Steps to Reproduce

Case 1:

1. Clean profile 1.46.x
2. Open brave://local-state file
3. Install MM
4. Change the `Default Ethereum wallet` to "None" 
5. Open any https site 
6. Reload brave://local-state file
7. The metrics `Brave.Wallet.EthProvider` response value is `1` `Third-party wallet extension` instead of `0` `None`

**Note**: Reverse steps 3 and 4 yields the same result
 
Case 2:

1. Clean install 1.46.x
2. Open chrome://settings/wallet/
3. Change the `Default Ethereum wallet` to "None"
4. Open chrome://local-state/ and reload
5. The metrics `Brave.Wallet.EthProvider` is NOT shown as expected
6. Open chainlist.org in a new tab
7. Reload chrome://local-state/ and check value
8. The metrics `Brave.Wallet.EthProvider` response value is `0` as expected
9. Install MM and create MM account
10. Reload chainlist.org or close and reopen the same tab
11. Reload chrome://local-state/, when `chainlist.org` is reloaded the value is `0`, when chainlist.org tab is closed and open the chainlist.org in a new tab and reload brave://local-state gives the response value as `1` which is incorrect

## Actual result:

Incorrect response value for the wallet selection "None"

## Expected result:
Correct response value should be shown for the wallet selection "None"

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.46.87 Chromium: 107.0.5304.91 (Official Build) beta (64-bit)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | Windows 10 Version 21H2 (Build 19044.2130)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @DJAndries @mattmcalister @rebron

**Comment by DJAndries** [comment]
@GeetaSarvadnya The "Default Ethereum Wallet" setting does not block a third-party wallet extension from being used, if it is set to "None". It will only control how the native Brave Wallet provider is loaded. When the setting is set to "None", you can try connecting the wallet to a dapp (i.e. OpenSea); the competing wallet's connect dialog should still pop up. Closing as invalid.
