### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by swanwise** [brave/brave-browser#26505]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.45.116  Chromium: 107.0.5304.91
Operating System: Mac OS X 12.6.0

URL (if applicable) where crash occurred:

Can you reproduce this crash?
yes
What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. multiple youtube tabs open
2.make this stop
3.i want to eep using brave...

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/fcb70100-f0bb-1809-0000-000000000000

**Comment by OmarJAhmad** [comment]
i also have similar issue, brave crashes multiple time,
windows 10 
Brave is up to date
[Version 1.45.118 Chromium: 107.0.5304.91 (Official Build) (64-bit)]
