### ISSUE TITLE
Sync availability in settings (non 0.58.x) 

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#2650]
follow up of https://github.com/brave/brave-browser/issues/2642#issuecomment-448695141

**Comment by darkdh** [comment]
0.59.12 doesn't contain the fix, please retest with 0.59.13 when it is available

**Comment by GeetaSarvadnya** [comment]
Verification passed on 


Brave | 0.59.13 Chromium: 72.0.3626.28 (Official Build) beta (64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Windows

- Verified there is no sync section in chrome settings and Hamburger menu when we launch brave with `--disable-brave-sync` flag
![image](https://user-images.githubusercontent.com/38657976/50535241-13eb3300-0b6e-11e9-940f-d95ebdfc951c.png)
- Verified there is sync section in both chrome://settings and Hamburger menu when we lauch brave without `--disable-brave-sync` flag
![image](https://user-images.githubusercontent.com/38657976/50535265-5b71bf00-0b6e-11e9-8907-0d005b0570eb.png)
- Logged new issue (#2757)
