### ISSUE TITLE
Provide Windows Group Policy templates for Brave

### ISSUE THREAD

**Issue by mherrmann** [brave/brave-browser#26501]
In the [documentation for Group Policies](https://support.brave.com/hc/en-us/articles/360039248271-Group-Policy), we advise administrators to download Chrome's templates and modify them by hand for Brave's registry paths. The goal of this issue is to provide our own set of templates so the modification by hand is not necessary.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.47.121 Chromium: 108.0.5359.99 (Official Build) beta (64-bit)
-- | --
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | Windows 11 Version 21H2 (Build 22000.1219)
```

#### Case 1: Add Group policy templates via `policy_templates.zip`
<details>

1. Install 1.47.121
2. launch Brave
3. open https://github.com/brave/brave-browser/releases/tag/v1.47.125
4. click  to download `policy_templates.zip file
5. extract `policy_templates.zip` 
6. open `Local Group Policy editor`  (Windows>>Run>>enter `gpedit.msc`>>OK)
7. right click `Administrative Templates` under `Computer Configuration`
8. clicked `Add/Remove templates`
9. clicked `Add`
10. go to `Downloads` > `policy_templates` > `windows` > `adm` > `en-US` >` braveadm` > open
11. click close on `Administrative Templates` dialog
12. click Local Group Policy Editor >> `Administrative Templates`
13. expand   `Classic Administrative Templates (ADM) >>Brave >> Brave
14. `Content Settings`>>`Block cookies on these sites` shows ` Not Configured` 

#### Confirmed `Group policy templates` are added

step 3|step 5|step 7-8|step 9|step10|step 11|step 14
-----|-----|-----|-----|-----|-----|------
<img width="475" alt="image" src="https://user-images.githubusercontent.com/98358127/207100623-44330c99-5882-4893-bd56-f7f430370045.png">|<img width="1004" alt="image" src="https://user-images.githubusercontent.com/98358127/207102534-88ad89e9-4c6b-470b-a7c8-c59caa7dae4c.png">|<img width="1200" alt="image" src="https://user-images.githubusercontent.com/98358127/207103170-269c378a-bbb9-4e26-bc64-8e2bc094c97b.png">|<img width="977" alt="image" src="https://user-images.githubusercontent.com/98358127/207128576-64674f19-ca80-4b7c-b69d-841678c26edf.png">|<img width="575" alt="image" src="https://user-images.githubusercontent.com/98358127/207123065-8df64e2d-a3f4-4a9d-b65c-16604c2c4b7e.png">|<img width="978" alt="image" src="https://user-images.githubusercontent.com/98358127/207128984-3aa4ea4f-86ea-4e8c-b768-9cc6d2bc3d1f.png">|<img width="1254" alt="image" src="https://user-images.githubusercontent.com/98358127/207134225-9a6349bc-c57e-4031-a7bc-086045686012.png">

</details>

#### Case 2:  Modify a setting in Brave content settings
<details>

1. continue from case 1
2. click `Content Settings`>>`Block cookies on these sites`
3. select `Enabled`
4. click `Show`
5. add a value (eg. cnn.com)
6. click `OK`
7. click `Apply` >> `OK`
8. Block cookies on these sites show `Enabled`
9. open `brave://policy`
10. confirmed policy name shows `CookiesBlockedForURLs` and policy value shows `cnn.com`
11. open `brave://settings/cookies` in a new-tab
12. confirmed `cnn.com` entry shows in `Sites that can never use cookies`

step 1|step 2-7|step 8|step 10|step 11-12
-------|-------|-------|-----|----
<img width="945" alt="image" src="https://user-images.githubusercontent.com/98358127/207129266-e17aaec8-6460-4b39-b90c-a568c122d40a.png">|<img width="347" alt="image" src="https://user-images.githubusercontent.com/98358127/207129373-dec51773-f9cc-497b-af7f-82ffc8a231cf.png">|<img width="677" alt="image" src="https://user-images.githubusercontent.com/98358127/207124609-c71d5fc2-5655-4233-a408-5b25874cc5cb.png">|<img width="956" alt="image" src="https://user-images.githubusercontent.com/98358127/207130499-f928a8c3-dc06-4df7-aa73-ade58368ee2d.png">|<img width="458" alt="image" src="https://user-images.githubusercontent.com/98358127/207130036-4839f435-15b7-4f38-9162-e4ffcb72154f.png">

</details>


#### Case 3:  Remove the setting in Brave content settings
<details>

1. continue from Case 1
      - `brave://policy` shows `Policy name`  `cnn.com
      - `brave://settings/cookies`  `cnn.com` shows in `Sites that can never use cookies` entry
2. go to open `Local Group Policy editor`  (Windows>>Run>>enter `gpedit.msc`>>OK)
3. go to `Administrative Templates`>>`Classic Administrative Templates (ADM)` >>`Brave` >> `Brave` 
4. click `Block cookies on these sites`  
5. click `Disabled`
6. click `Apply` >> `OK`
7. `Block cookies on these sites` shows disabled
8. go to `brave://policy`
9. Policy name `cnn.com` was removed
10. go to `brave://settings/cookies`
11. refresh the page
12. confirmed `cnn.com` entry shows in `Sites that can never use cookies`

step 1a|step 1b|step 3-6|step 7|step 8-9|step10-11
-------|-------|-------|------|---------|---------
<img width="661" alt="image" src="https://user-images.githubusercontent.com/98358127/207143911-4c332848-271b-43ab-9662-cc0be487a063.png">|<img width="654" alt="image" src="https://user-images.githubusercontent.com/98358127/207142612-a3dcb224-a525-412f-85e7-3ee58924958b.png">|<img width="842" alt="image" src="https://user-images.githubusercontent.com/98358127/207142567-034194f4-61a3-4f48-af36-c141dc6eca95.png">|<img width="1051" alt="image" src="https://user-images.githubusercontent.com/98358127/207142721-5c5853db-caea-4e0d-89fb-fd0a915fcd30.png">|<img width="665" alt="image" src="https://user-images.githubusercontent.com/98358127/207144884-56a58068-98f2-48b6-b55e-19ae81840823.png">|<img width="466" alt="image" src="https://user-images.githubusercontent.com/98358127/207143210-ea437054-07cc-4948-b764-02b799ab563a.png">

</details>
