### ISSUE TITLE
Can't access thingiverse.com with Brave on macOS 12.6 (Apple M1)

### ISSUE THREAD

**Issue by bogdanm** [brave/brave-browser#26504]
## Description 

https://thingiverse.com (and possibly other sites too) just displays a "Something went wrong" error when I try to open it with Brave (with or without shields, rewards off). The site works when opened from Safari or Google Chrome. 

The developer console shows this error:

```
vendors.bundle.js?1667337615:2 TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at j (app.bundle.js?1667337615:1:301523)
    at app.bundle.js?1667337615:1:422319
    at vu (vendors.bundle.js?1667337615:2:862651)
    at Hs (vendors.bundle.js?1667337615:2:887512)
    at t.unstable_runWithPriority (vendors.bundle.js?1667337615:2:905265)
    at Qo (vendors.bundle.js?1667337615:2:830303)
    at As (vendors.bundle.js?1667337615:2:887268)
    at vendors.bundle.js?1667337615:2:887179
    at R (vendors.bundle.js?1667337615:2:904647)
```

## Steps to Reproduce

Open https://thingiverse.com

## Reproduces how often: 

Every time.

## Brave version (brave://version info)

```
Brave: 1.45.116 Chromium: 107.0.5304.91 (Official Build) (arm64)
Revision: 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS: macOS Version 12.6 (Build 21G115)
```

## Miscellaneous Information:

This is not a new issue, older versions of Brave and macOS had the same problem.

**Comment by rebron** [comment]
<img width="1522" alt="Screenshot 2022-11-04 at 10 12 36 AM" src="https://user-images.githubusercontent.com/5951041/200035648-3c8ba619-94ce-4ce6-bd78-3bb8a5e31a6a.png">
I'm not able to reproduce. 

cc: @ryanbr

**Comment by rebron** [comment]
@bogdanm Can you try opening the page in a private window, also wondering if the page is conflicting with an extension. We had a few other in QA try to load the page and it looks like it was loading properly.

**Comment by bogdanm** [comment]
@rebron I did and find out that an extensions was indeed the problem, namely Windscribe (https://chrome.google.com/webstore/detail/windscribe-free-proxy-and/hnmpcagpplmpfojmgmnngilcnanddlhb). Even though I wasn't connected to a VPN using Windscribe, it's still doing something weird. Thank you and sorry for the noise.

**Comment by ryanbr** [comment]
Great to see it working @bogdanm  Also rolled out a fix for the Advert space; https://github.com/easylist/easylist/commit/59bd920  (give it 24/48hrs)
