### ISSUE TITLE
Update "background video playback" setting copy

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#26516]
## Description
We are in the process of enabling the "background video playback" feature by default. Because it is no longer considered "experimental" and most users want to play video/audio in the background.

![image](https://user-images.githubusercontent.com/28269287/199801264-dfc9d0af-466c-4548-bc13-04dce6ef596b.png)

https://github.com/brave/brave-variations/pull/420
https://github.com/brave/brave-variations/pull/421

The setting copy should be updated as follows:

**Header:** Background media playback
**Body:** Allows audio to continue playing when you switch to another tab in Brave, switch to another app, or your device screen is off.

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` & `Samsung Galaxy Tab S7` using the following build(s):

```
Brave	1.47.149 Chromium: 109.0.5414.46 (Official Build) beta (64-bit) 
Revision	6e36b77363ef3febbe792af680fa1367993ddcf0-refs/branch-heads/5414@{#709}
OS	Android 12; Build/SP1A.210812.016
```

- Verified setting copy is updated.

Example | Example
-|-
![screenshot-1672347305488](https://user-images.githubusercontent.com/17885425/210012789-e408d299-f374-42da-b17d-d46d4339ecab.png) | ![screenshot-1672349405183](https://user-images.githubusercontent.com/17885425/210012872-8260895d-85b0-46bc-ab72-e3f496d8ab03.png)
