### ISSUE TITLE
Brave News onboarding region selection

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#26517]
On Brave News onboarding (i.e. the opt-in card), when a user is not in a region/language that we have a Brave News feed for, then we should show a drop-down with all our language/region options. The selection would affect which region they are subscribed to the "Top Sources" channel in. In other words which region they want to start with content from.

The options would be, e.g.:
```
"United States (English)"
"Canada (English)"
"Spain (Spanish)"
"United States (Spanish)"
"Japan (Japanese)"
```

![image](https://user-images.githubusercontent.com/741836/199801117-7eba19a8-2652-4f8a-8f89-679d80ac97f3.png)

## Technical implementation
- We should store "brave news user region" in a pref. That pref should only affect:
  - The initial channel subscription on first opt-in
  - The region that sources and channels are filtered to in the Customize modal. https://github.com/brave/brave-browser/issues/26518
 - We should provide the translated name of all regions to all platforms via a new API method.

**Comment by martin-c0des** [comment]
@petemill I assume multiple selection is going to be possible?

**Comment by martin-c0des** [comment]
@petemill [Here's a link to the screens](https://www.figma.com/file/wpjvatVQQvOtC96WaPCw86/Desktop-Brave-News?node-id=1151%3A23106&t=c6PPLClpXdgd4Soz-1) showcasing the designs for the required UI. This way of presenting the dropdown won't require any additional changes in copy.

- dropdown marked as required
- "Show Brave News" button disabled until a selection is made

Let me know what you think.

**Comment by fallaciousreasoning** [comment]
I like this, it's quite an elegant solution! One thing - at the moment I don't think we show that card to enable Brave News unless you're in a supported region.

**Comment by LorenzoMinto** [comment]
Closing this as stale, and we are planning an upgrade to both onboarding and settings, including the localisation aspect.
