### ISSUE TITLE
Brave News Customize toggle should hide Brave News, not opt-out

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#26519]
Users should be able to hide Brave News from the NTP.
User should be able to show Brave News on the NTP after initially opting-out.

## Implementation details
Whilst it would be good to have a separate toggle that's purely for whether Brave News shows on the NTP, especially when we surface the feed in other places such as a sidebar, right now we only show Brave News in one place. Therefore the Toggle on the Customize dialog can be changed so that it toggles the preference for Brave News on NTP.

## Can hide Brave News from the NTP
- Opt in to Brave News
- Open Customize
- Turn off Brave News
- Expected: Brave News does not show on the NTP
- Actual: Brave News shows on NTP in opted-out mode

## Can show Brave News on NTP after opting-out
- Fresh profile
- Click "no thanks" on Brave News opt-in card
- Open Customize and click Brave News section
- Enable the main Brave News Toggle
- Expected: Brave News should be displayed on NTP
- Actual: Brave News does not show on NTP

**Comment by kjozwiak** [comment]
The above requires `1.46.107` or higher for `1.46.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.46.121 Chromium: 108.0.5359.48 (Official Build) beta (64-bit)
-- | --
Revision | 18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}
OS | Windows 11 Version 21H2 (Build 22000.1219)
```

Case 1: Hide Brave News from the new-tab page - PASSED
<details>

1. install 1.46.121
2. clicked Skip welcome tour
3. scrolled down
4. confirmed the `Turn on Brave News / No thanks` opt-in card displayed
5. clicked on `Turn on  Brave News` 
6. Brave news feed displayed
7. clicked on `Customize`
8. Brave news V2 UI is displayed 
9. toggled `Brave News` at the top to `OFF/Disabled` in the customize news dialog
10. closed the dialog
11. refreshed the page

Confirmed Brave News (peeking card/opt-in/feed content, etc.) on the new-tab page is not displayed

step 5|step 6|step 8|step 8|results
-----|-----|------|------|------
<img width="464" alt="image" src="https://user-images.githubusercontent.com/98358127/203148537-31e9f1e8-11d0-4f22-b82a-330f907d0d71.png">|<img width="462" alt="image" src="https://user-images.githubusercontent.com/98358127/203148569-b7080328-a32a-4690-a2b4-984e45cff29b.png">|<img width="464" alt="image" src="https://user-images.githubusercontent.com/98358127/203148592-299fcbfa-d18f-44ce-a9cc-bebc8e918d39.png">|<img width="466" alt="image" src="https://user-images.githubusercontent.com/98358127/203148633-91100914-25d3-479d-8277-ed7bddaa7655.png">|<img width="466" alt="image" src="https://user-images.githubusercontent.com/98358127/203148662-3d9a669b-3604-4728-b5c0-66d3d7f2cf99.png">
</details>

Case 2: Show Brave News from the new-tab page, after opting-out - PASSED
<details>

1. install 1.46.121
2. clicked Skip welcome tour
3. scrolled down
4. confirmed the `Turn on Brave News / No thanks` opt-in card displayed
5. clicked on `No thanks`
6. clicked on `Customize`
7. clicked on `Brave News`
8. clicked on `Turn on Brave News`
9. confirmed Brave News UI shows sources as expected

Confirmed Brave News is enabled and feed is displayed 
Confirmed Brave News feed shows on the new-tab page as well

step 6|step 6|step 8|step 9|news feed|NTP
----|------|------|-------|--------|------
<img width="465" alt="image" src="https://user-images.githubusercontent.com/98358127/203153961-f3276c5d-6d2a-411f-8310-ecbe9348ef10.png">|<img width="459" alt="image" src="https://user-images.githubusercontent.com/98358127/203154128-160aaea8-7a33-4e40-a449-0e9e17950fb4.png">|<img width="458" alt="image" src="https://user-images.githubusercontent.com/98358127/203154344-7aff906f-2295-4417-8ed1-482c757b9b9e.png">|<img width="457" alt="image" src="https://user-images.githubusercontent.com/98358127/203154394-4ea9c2b3-db38-4476-a49d-5d12900ba342.png">|<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/203154443-10d1dd73-3332-4109-8561-c0026697657a.png">|<img width="462" alt="image" src="https://user-images.githubusercontent.com/98358127/203155008-75e5946d-4e87-4e41-8518-419bdf1f94aa.png">





</details>
