### ISSUE TITLE
Description text for `Redirect IPFS resources to the configured IPFS gateway` could be a little clearer

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#26528]
## Description 

Description text for `Redirect IPFS resources to the configured IPFS gateway` could be a little clearer

## Steps to Reproduce

1. install `1.47.42`
2. launch Brave
3. load `brave://settings/ipfs`
4. read the wall of text under `Redirect IPFS resources to the configured IPFS gateway`

## Actual result:

`Requests to IPFS resources, hosted on third-party IPFS gateways will be loaded via selected local or remote gateway. Note: If local node is selected, resource will be requested directly from your computer and cached data may be provided to the IPFS network for some time.`

I understand this came from a security review, so I'm not knocking it, we could just make it a little clearer?

<img width="1312" alt="Screen Shot 2022-11-03 at 6 07 34 PM" src="https://user-images.githubusercontent.com/387249/199863465-0fca7e95-8d05-4629-9b55-57c9c6ffa390.png">

## Expected result:

It could be slightly better: maybe an article `the` here or there (e.g. `the resource will be requested`, and `will be loaded via the selected`, and maybe a comma for the clause on the end of `hosted on third-party gateways," 

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.47.42 Chromium: 107.0.5304.91 (Official Build) nightly (x86_64)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | macOS Version 11.7.1 (Build 20G918)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `No`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rmcfadden3 @cypt4

**Comment by stephendonner** [comment]
Cross-reference https://github.com/brave/brave-browser/issues/26374 and https://github.com/brave/security/issues/1063

**Comment by rmcfadden3** [comment]
@stephendonner — something like this?

`Requests to IPFS resources (hosted on third-party IPFS gateways) will be loaded via a selected local or remote gateway. If a local node is selected, the resource will be requested directly from your computer and cached data may be provided to the IPFS network for some time.`

Oh, and do you know if we can give any more specificity around what "…for some time." means in this case?

**Comment by stephendonner** [comment]
> @stephendonner — something like this?
> 
> `Requests to IPFS resources (hosted on third-party IPFS gateways) will be loaded via a selected local or remote gateway. If a local node is selected, the resource will be requested directly from your computer and cached data may be provided to the IPFS network for some time.`
> 
> Oh, and do you know if we can give any more specificity around what "…for some time." means in this case?

I do not, but am betting @cypt4 @yrliou @lidel will be able to help suss that out 👍

**Comment by lidel** [comment]
Cached IPFS blocks are reprovided to the network until they are garbage-collected.
GC can be manually triggered by the user on the `brave://ipfs-internals` screen, or happen automatically after `brave.ipfs.storage_max` is reached.


So maybe "for some time" → "until it is garbage-collected"?

**Comment by vadimstruts** [comment]
The IPFS local node and scheme has been [deprecated](https://github.com/brave/brave-browser/issues/37735)
