### ISSUE TITLE
Brave News untoggled state needs opt-in text if user hasn't opted-in previously

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#26520]
There are 2 prefs that consider Brave News as not "active" - opted-in and show-on-ntp. If opted-in has not been toggled before, we should show the opt-in text that is shown on the feed's opt-in text. Perhaps we should show even when the user has disabled Brave News after previously opting in?

Current opt-in text in feed card:
```
Brave News is ad-supported with completely private and anonymized ads matched on your device. Your personal information always stays private, per our [privacy policy](https://brave.com/privacy/browser/).
```

Current text displayed in Customize dialog when user has not yet opted-in OR user has turned off Brave News
```
Customized news feeds, from leading sources, delivered right to your browser. All 100% private.
```

**Comment by mattmcalister** [comment]
```
Follow your favorite sources, in a single feed. Just open a tab in Brave, scroll down, and…voila!
Brave News is ad-supported with private, anonymized ads. [Learn more](https://brave.com/privacy/browser/#brave-news).
```

![image](https://user-images.githubusercontent.com/71029/199814908-a5a9f0cc-cf2b-4653-89a3-0a88390409f9.png)

**Comment by petemill** [comment]
@mattmcalister Should that be new text for both the regular opt-in card in the feed and the Customize dialog, or just the Customize dialog?

**Comment by mattmcalister** [comment]
it should be the new text for both.

**Comment by kjozwiak** [comment]
The above requires `1.46.107` or higher for `1.46.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.46.121 Chromium: 108.0.5359.48 (Official Build) beta (64-bit)
-- | --
Revision | 18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}
OS | Windows 11 Version 21H2 (Build 22000.1219)
```
Install 1.46.121
launch Brave
clicked `Skip welcome tour`
scroll down 

#### Confirmed opt-in text changes were the same on both the opt-in card and untoggled state in the Customize Brave news dialog

opt-in card|customize news dialog
--------|-------
<img width="937" alt="image" src="https://user-images.githubusercontent.com/98358127/203169546-f4fd5f9f-3d77-4f1c-b9dc-2cdbe7976a97.png">|<img width="942" alt="image" src="https://user-images.githubusercontent.com/98358127/203169612-9cc41122-6e92-4c59-81fa-b7f41c36b6ce.png">
