### ISSUE TITLE
Fix broken redirect URI escaping

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#26536]
We found that `com.brave.ftx://authorization` was not escaped at `FTXService::AuthenticateFromAuthToken()`

Internal issue: https://github.com/brave/internal/issues/944

**Comment by LaurenWags** [comment]
@simonhong @fmarier 

Given https://github.com/brave/internal/issues/944#issuecomment-1316107304, can this be changed to `QA/No`?

**Comment by fmarier** [comment]
Yes, I think that's not relevant anymore since we're removed that widget.
