### ISSUE TITLE
Show etld on sign panel

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#26539]
## Description 
Show etld on sign panel

## Expected result

![Screenshot from 2022-11-04 15-47-02](https://user-images.githubusercontent.com/11755381/199949147-7aa27276-9f23-4ccf-a1a9-162ecde45b55.png)

**Comment by kjozwiak** [comment]
The above requires `1.46.94` or higher for `1.46.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.46.96 x64 Beta build
- Verified etld is shown on send and sign transactions

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/200303273-511c8c47-9369-41b3-9f6f-eaae5f0eb661.mp4> | <video src=https://user-images.githubusercontent.com/17010094/200303300-823b1d1a-bb10-44d0-91ab-5e4e9da73a51.mp4>
