### ISSUE TITLE
Non-verified publishers are not displayed

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#2653]
## Steps to Reproduce

   1. enable rewards
   2.  uncheck allow to non-verified
   3. visit non verified site
   4. open a panel

## Actual result:

You will be presented with a rewards summary

## Expected result:
Publisher should be displayed

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

broken with https://github.com/brave/brave-browser/issues/2111

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.59.25 Chromium: 72.0.3626.53 (Official Build) beta(64-bit)
-- | --
Revision | 98434e6cd182d68ce396daa92e9c6310422e6763-refs/branch-heads/3626@{#620}
OS | Linux

* Verified non-verified sites are not added to ac list when settings is off
* Verified non-verified sites are added to ac list when setting is on
