### ISSUE TITLE
Brave is pinned to the taskbar when brave is NOT pinned explicitly via the first run dialog

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#26542]
## Description 

Brave is pinned to the taskbar when brave is NOT pinned explicitly via the first run dialog

This issue is not reproducible 100% but I have seen the issue 3 to 4 times in 3 days while dog fooding the beta build (1.46.x)
## Steps to Reproduce

STR 1:
   1. Clean profile 1.46.x
   2. Click on `May be later` in first run dialog
   3. Browser was launched and I was working on Rewards for 10 to 15 mins
   4. When I right click on the brave icon in the taskbar it was already pinned

STR2:
   1. Clean profile 1.46.x
   2. Click on `x` in first run dialog
   3. Brave://welcome page is displayed, click on `Skip welcome tour` link 
   4. Right click on the brave icon in the taskbar it was already pinned

## Actual result:

Brave is pinned to the taskbar when brave is NOT pinned explicitly via the first run dialog

## Expected result:
Brave should not be pinned to the taskbar when brave is NOT pinned explicitly via the first run dialog

## Reproduces how often: 

Intermittent
## Brave version (brave://version info)

Brave | 1.46.90 Chromium: 107.0.5304.91 (Official Build) beta (64-bit)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | Windows 10 Version 21H2 (Build 19044.2130)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @simonhong @rebron

**Comment by simonhong** [comment]
@GeetaSarvadnya I found why you're experiencing this on beta.
With this https://chromium-review.googlesource.com/c/chromium/src/+/3858031,
upstream started to pin to taskbar by installer - `constexpr int kBetaRolloutPercentage = 10;`
Maybe 10% of `Win10+` users will get pinned with this change.
```
bool ShouldPinChromeToTaskbar() {
  if (base::win::GetVersion() < base::win::Version::WIN10)
    return true;
  switch (install_static::GetChromeChannel()) {
    case version_info::Channel::BETA: {
      // Increase kBetaRolloutPercentage to roll out to beta channel.
      constexpr int kBetaRolloutPercentage = 10;
      return base::RandInt(0, 99) < kBetaRolloutPercentage;
    }
    case version_info::Channel::STABLE: {
      constexpr int kStableRolloutPercentage = 0;
      return base::RandInt(0, 99) < kStableRolloutPercentage;
    }
    default:
      return false;
  }
}
```

And it seems upstream already changed it to 100% by https://chromium-review.googlesource.com/c/chromium/src/+/3858031
But it's not yet arrived to our master.
Then maybe we don't need `Pin to taskbar` checkbox in first run dialog on Windows.
cc @rebron

**Comment by simonhong** [comment]
Ok, I'll remove checkbox when upstream set 100% asstable rollout percentage.

**Comment by MadhaviSeelam** [comment]
@GeetaSarvadnya - Closing this issue since first run dialog is disabled via https://github.com/brave/brave-browser/issues/27225.  And I filed a follow up for the same issue https://github.com/brave/brave-browser/issues/27499
cc: @rebron @simonhong
