### ISSUE TITLE
Frontend desktop support for running DiscoverAssets on page refresh

### ISSUE THREAD

**Issue by nvonpentz** [brave/brave-browser#26547]
### Background
Backend support issue - https://github.com/brave/brave-browser/issues/25820.

The backend will provide a DiscoverAssetsOnAllSupportedChains API to the frontend that it can call to run the discover assets logic when the user reloads the wallet UI.  The API will look like this with with no callback:
```
interface BraveWalletService {
  DiscoverAssetsOnAllSupportedChains();
}
```
Upon completion/failure, the backend will emit an event for each chain.
```
interface BraveWalletServiceObserver {
  // Fired when a discovered asset query completes
  OnDiscoverAssetsCompleted(array<BlockchainToken> discovered_assets);
};
```
If it's useful for the frontend, the backend can also emit an event when discovery logic completes for all supported chains.

### Spec
More input needed to determine the the specifics, but the frontend implementation should be something like this --
1. Call this API when appropriate (on-refresh)
2. Display some UI to the user indicating that the asset discovery has running
3. Indicate to the user when that has completed

**Comment by jamesmudgett** [comment]
We should use one single row "loading skeleton" at the bottom of any list on load and until the final completion/failure call has been executed.

**Comment by nvonpentz** [comment]
@jamesmudgett should the OnDiscoverAssetsCompleted event the frontend receives contain data on whether the calls succeeded or failed, or just that they are complete?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.48.141 Chromium: 109.0.5414.119 (Official Build) beta (64-bit) 
-- | --
Revision | `772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}`
OS | Linux

- Verified steps from [brave/brave-core#16329](https://github.com/brave/brave-core/pull/16329)
- Verified loading skeleton is shown at the bottom of the asset list on both portfolio page and account page

https://user-images.githubusercontent.com/17010094/215510581-c7128cde-c176-401a-8fe9-4e229fc596c0.mp4


---------------------

Verification passed on 

Brave | 1.48.141 Chromium: 109.0.5414.119 (Official Build) beta (64-bit)
-- | --
Revision | `772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#16329](https://github.com/brave/brave-core/pull/16329)
- Verified loading skeleton is shown at the bottom of the asset list on both portfolio page and account page

https://user-images.githubusercontent.com/17010094/215509757-1f21b37a-9f4f-4334-a0b6-b07b46cd9a96.mp4

---------------------

Verification passed on 

Brave | 1.48.141 Chromium: 109.0.5414.119 (Official Build) beta (arm64)
-- | --
Revision | `772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#16329](https://github.com/brave/brave-core/pull/16329)
- Verified loading skeleton is shown at the bottom of the asset list on both portfolio page and account page

https://user-images.githubusercontent.com/17010094/215510089-a6cf4df1-f0d8-439d-a16d-dab1fb8cb8c3.mov
