### ISSUE TITLE
Check if the user has a `recipient_id` before creating one.

### ISSUE THREAD

**Issue by szilardszaloki** [brave/brave-browser#26545]
https://github.com/brave/internal/issues/948

**Comment by LaurenWags** [comment]
@szilardszaloki @Miyayes 

Since this is labelled `QA/Yes` a manual test plan is needed. Labelling as `QA/Blocked` until this is sorted.

cc @kjozwiak @rebron

**Comment by szilardszaloki** [comment]
Hey @LaurenWags,
Added test plan to the internal issue (also removed `QA/Blocked`).

**Comment by LaurenWags** [comment]
Verified with

```
Brave	1.47.129 Chromium: 108.0.5359.128 (Official Build) beta (x86_64) 
Revision	1cd27afdb8e5d057070c0961e04c490d2aca1aa0-refs/branch-heads/5359@{#1185}
OS	macOS Version 12.6.2 (Build 21G320)
```

Verification notes can be found under https://github.com/brave/internal/issues/948#issuecomment-1354957138
