### ISSUE TITLE
Manual test run on macOS (arm64) for Tor 0.4.7.10 - Release #2

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#26554]
### Tor Client Updater

- [ ] For development go-update-server. Run brave-browser with `--user-data-dir=component-dev --use-dev-goupdater-url` (These flags are only available in v1.7.x). Once the crx is pushed to production run without these flags.
- [ ] Navigate to `brave://components` and verify `Tor Client Updater (OS)` is updated successfully.
- [ ] Open `New Private Window with Tor` and confirm that it starts without any errors.
	- [ ] Navigate to `check.torproject.org` and verify that tor is working successfully.
	- [ ] Navigate to `brave.com` and `http://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/` to check if the sites work correctly.
- [ ] Load `brave.com` and `mail.protonmail.com` in a regular Window/Tab and ensure that clicking the `Tor` button in the URL bar correctly launches a Tor window and opens the appropriate `.onion` website.

### MacOS
- [ ] Navigate to `/Users/<user>/Library/Application Support/BraveSoftware/Brave-Browser-<channel>/cldoidikboihgcjfkhdeidbpclkineef/<version>`
- [ ] Run `codesign -vvvv tor-<version-tor>-darwin-brave-<version-brave>` to confirm codesign is valid
- [ ] For MacOS Catalina (10.15+) - Run `spctl -a -vv -t install tor-<version-tor>-darwin-brave-<version-brave>` to verify that the binary is notarized.

### Tor Client Updater

- [x] For development go-update-server. Run brave-browser with `--user-data-dir=component-dev --use-dev-goupdater-url` (These flags are only available in v1.7.x). Once the crx is pushed to production run without these flags.
- [x] Navigate to `brave://components` and verify `Tor Client Updater (OS)` is updated successfully.
- [x] Open `New Private Window with Tor` and confirm that it starts without any errors.
	- [x] Navigate to `check.torproject.org` and verify that tor is working successfully.
	- [x] Navigate to `brave.com` and `http://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/` to check if the sites work correctly.
- [x] Load `brave.com` and `mail.protonmail.com` in a regular Window/Tab and ensure that clicking the `Tor` button in the URL bar correctly launches a Tor window and opens the appropriate `.onion` website.

### MacOS
- [x] Navigate to `/Users/<user>/Library/Application Support/BraveSoftware/Brave-Browser-<channel>/cldoidikboihgcjfkhdeidbpclkineef/<version>`
- [x] Run `codesign -vvvv tor-<version-tor>-darwin-brave-<version-brave>` to confirm codesign is valid
- [x] For MacOS Catalina (10.15+) - Run `spctl -a -vv -t install tor-<version-tor>-darwin-brave-<version-brave>` to verify that the binary is notarized.

**Comment by kjozwiak** [comment]
Quick note: The Tor daemon itself was not updated and is still on `0.4.7.10`. However, the following did get upgraded:

* `OpenSSL` - `1.1.1q` -> `1.1.1s`
* `Zlib` - `1.2.12` -> `1.2.13`

**Comment by stephendonner** [comment]
#### Big Sur - `PASSED`
<details>

Verified `PASSED` using 



Brave | 1.45.118 Chromium: 107.0.5304.91 (Official Build) (arm64)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | macOS Version 11.7.1 (Build 20G918)




Confirmed that the correct Tor component was being downloaded via --use-dev-goupdater-url:

--use-dev-goupdater-url

<img width="294" alt="Screen Shot 2022-11-04 at 4 15 14 PM" src="https://user-images.githubusercontent.com/387249/200087937-f7ecbce1-971c-49e0-9903-276c40238692.png">


Confirmed that the Tor component was started when launching Tor and ensured Tor `0.4.7.10` was being used:

`Nov 04 16:18:42.218 [notice] Tor 0.4.7.10 running on Darwin with Libevent 2.1.12-stable, OpenSSL 1.1.1q, Zlib 1.2.12, Liblzma N/A, Libzstd N/A and Unknown N/A as libc.`

`stephendonner@Stephens-MacBook-Pro-3 1.0.52 % codesign -vvvv tor-0.4.7.10-darwin-brave-1
tor-0.4.7.10-darwin-brave-1: valid on disk
tor-0.4.7.10-darwin-brave-1: satisfies its Designated Requirement
stephendonner@Stephens-MacBook-Pro-3 1.0.52 % spctl -a -vv -t install tor-0.4.7.10-darwin-brave-1
tor-0.4.7.10-darwin-brave-1: accepted
source=Notarized Developer ID
origin=Developer ID Application: Brave Software, Inc. (KL8N8XSYF4)`

Confirmed that you can open the following domains in a Tor window without issues:

`brave.com`
`duckduckgo.com`
`https://duckduckgogg42xjoc72x3sjasowoarfbgcmvfimaftt6twagswzczad.onion/`
`check.torproject.org` (ensured that hard-refreshing gets a new circuit/IP)

Confirmed the following sites opened via “Open in Tor” button from normal window and navigated to their .onion URL in a Tor window:

`brave.com` --> `https://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/`
`https://account.proton.me/login` --> `https://account.protonmailrmez3lotccipshtkleegetolb73fuirgj7r4o4vfu7ozyd.onion/`
`nytimes.com` --> `https://www.nytimesn7cgmftshazwhfgzm37qxb44r64ytbb2dj3x62d2lljsciiyd.onion/`

</details>

**Comment by stephendonner** [comment]
@kjozwiak @LaurenWags leaving open still, since I think we want to also do `Monterey`?

**Comment by LaurenWags** [comment]
yeah, we usually do. I'll add a section for it.

**Comment by LaurenWags** [comment]
Verification in progress for the below:

<details>
<summary>macOS 12.6.1 Monterey arm64 - InProgress</summary>

Verified on macOS 12.6.1 arm64 using the following build:

```

```

Confirmed that the correct Tor component was being downloaded via --use-dev-goupdater-url:


Confirmed that the Tor component was started when launching Tor and ensured Tor 0.4.7.10 was being used.
Confirmed that OpenSSL version is 1.1.1s per https://github.com/brave/brave-browser/issues/26553#issuecomment-1304016983.
Confirmed the Zlib version is 1.2.13 per https://github.com/brave/brave-browser/issues/26553#issuecomment-1304016983.

```

```

Confirmed that you can open the following domains in a Tor window without issues:

* brave.com
* duckduckgo.com
* https://duckduckgogg42xjoc72x3sjasowoarfbgcmvfimaftt6twagswzczad.onion/
* check.torproject.org (ensured that hard refreshing gets a new circuit/IP)

Confirmed the following sites opened via “Open in Tor” button from normal window and navigated to .onion URL in a Tor window:

* brave.com --> https://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/
* https://account.proton.me/login --> https://account.protonmailrmez3lotccipshtkleegetolb73fuirgj7r4o4vfu7ozyd.onion/
* nytimes.com --> https://www.nytimesn7cgmftshazwhfgzm37qxb44r64ytbb2dj3x62d2lljsciiyd.onion/

Confirmed that codesign is valid:

```
laurenwags@Laurens-MBP 1.0.55 % codesign -vvvv tor-0.4.7.10-darwin-brave-2 
```

Confirmed that the binary is notarized: 

```
laurenwags@Laurens-MBP 1.0.55 % spctl -a -vv -t install tor-0.4.7.10-darwin-brave-2 
```

</details>
