### ISSUE TITLE
Brave News feed auto-discovery within search appears broken

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#26550]
## Description 

Brave News feed auto-discovery within search appears broken

## Steps to Reproduce

1. install `1.47.42`
2. launch Brave
3. set `brave://flags/#brave-news-v2` and `brave://flags/#brave-news-subscribe-button` to `Enabled`
4. click `Relaunch`
5. open a new-tab page
6. click on `Customize`
7. click on `Brave News`
8. click on `Turn on Brave News`
9. under `Discover`, enter `https://www.pravda.com.ua/eng/`
10. when `Sources` pops up with `Get feeds from...` click it
11. wait

## Actual result:

`No feeds found at https://www.pravda.com.ua/eng/`

<img width="1312" alt="Screen Shot 2022-11-04 at 11 25 32 AM" src="https://user-images.githubusercontent.com/387249/200049284-c89f1683-cb54-40d6-9802-4d4ba77b6b73.png">

## Expected result:

I'd think it should show the 8 feeds which show up in the URL bar, when you loaded `https://www.pravda.com.ua/eng/`

example | example
---------|---------
<img width="1312" alt="Screen Shot 2022-11-04 at 11 30 16 AM" src="https://user-images.githubusercontent.com/387249/200049474-8656583b-bb76-487e-b94e-2f86c1b6a2ac.png"> | <img width="1312" alt="Screen Shot 2022-11-04 at 11 31 13 AM" src="https://user-images.githubusercontent.com/387249/200049583-dd402411-f4b8-4f2c-9476-5e112a590253.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.47.42 Chromium: 107.0.5304.91 (Official Build) nightly (x86_64)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | macOS Version 11.7.1 (Build 20G918)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

/cc @mattmcalister @fallaciousreasoning @petemill

**Comment by kjozwiak** [comment]
The above requires `1.46.102` or higher for `1.46.x` verification 👍

**Comment by stephendonner** [comment]
NOTE: I spun the original issue here off into https://github.com/brave/brave-browser/issues/26676, as search auto-discovery was broken even for `planet.mozilla.org`, with which it now works 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.46.103 Chromium: 107.0.5304.110 (Official Build) beta (x86_64)
-- | --
Revision | 2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}
OS | macOS Version 13.1 (Build 22C5044e)

### Steps:

1. install `1.46.103`
2. launch Brave
3. set `brave://flags/#brave-news-v2` and `brave://flags/#brave-news-subscribe-button` to `Enabled`
4. click `Relaunch`
5. open a new-tab page
6. click on `Customize`
7. click on `Brave News`
8. click on `Turn on Brave News`
9. under `Discover`, enter `planet.mozilla.org`
10. when `Sources` pops up with `Get feeds from...` click it

#### Confirmed I can search for, find, follow, and see articles from the `Planet Mozilla` feed

example | example | example | example | example
---------|----------|---------|----------|---------
<img width="1312" alt="Screenshot 2022-11-10 at 15 42 23" src="https://user-images.githubusercontent.com/387249/201229337-f52bbbf3-d74d-4336-b37b-fcf03cba131c.png"> | <img width="1312" alt="Screenshot 2022-11-10 at 15 42 30" src="https://user-images.githubusercontent.com/387249/201229339-06f170a6-33d7-4a89-92b9-2a37cda63332.png"> | <img width="1312" alt="Screenshot 2022-11-10 at 15 42 44" src="https://user-images.githubusercontent.com/387249/201229341-a234dd07-670a-4097-b25f-44459da574a5.png"> | <img width="1312" alt="Screenshot 2022-11-10 at 15 42 52" src="https://user-images.githubusercontent.com/387249/201229343-83eb7e07-e037-42ff-9c9b-fcd58078030a.png"> | <img width="1312" alt="Screenshot 2022-11-10 at 15 43 47" src="https://user-images.githubusercontent.com/387249/201229344-b30aa86b-32df-4db3-ac0f-9cf6f0de04ef.png">

cc @MadhaviSeelam

**Comment by fallaciousreasoning** [comment]
Okay, this is broken for a different reason to https://github.com/brave/brave-browser/issues/26676 - here the HTML was being returned with a non-UTF8 encoding, and we were completely failing to parse it. Fortunately the fix is simple enough: Parse the HTML doc with the appropriate encoding.
