### ISSUE TITLE
Manual test run on macOS (Intel) for Tor 0.4.7.10 - Release #2

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#26553]
### Tor Client Updater

- [ ] For development go-update-server. Run brave-browser with `--user-data-dir=component-dev --use-dev-goupdater-url` (These flags are only available in v1.7.x). Once the crx is pushed to production run without these flags.
- [ ] Navigate to `brave://components` and verify `Tor Client Updater (OS)` is updated successfully.
- [ ] Open `New Private Window with Tor` and confirm that it starts without any errors.
	- [ ] Navigate to `check.torproject.org` and verify that tor is working successfully.
	- [ ] Navigate to `brave.com` and `http://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/` to check if the sites work correctly.
- [ ] Load `brave.com` and `mail.protonmail.com` in a regular Window/Tab and ensure that clicking the `Tor` button in the URL bar correctly launches a Tor window and opens the appropriate `.onion` website.

### MacOS
- [ ] Navigate to `/Users/<user>/Library/Application Support/BraveSoftware/Brave-Browser-<channel>/cldoidikboihgcjfkhdeidbpclkineef/<version>`
- [ ] Run `codesign -vvvv tor-<version-tor>-darwin-brave-<version-brave>` to confirm codesign is valid
- [ ] For MacOS Catalina (10.15+) - Run `spctl -a -vv -t install tor-<version-tor>-darwin-brave-<version-brave>` to verify that the binary is notarized.

### Tor Client Updater

- [x] For development go-update-server. Run brave-browser with `--user-data-dir=component-dev --use-dev-goupdater-url` (These flags are only available in v1.7.x). Once the crx is pushed to production run without these flags.
- [x] Navigate to `brave://components` and verify `Tor Client Updater (OS)` is updated successfully.
- [x] Open `New Private Window with Tor` and confirm that it starts without any errors.
	- [x] Navigate to `check.torproject.org` and verify that tor is working successfully.
	- [x] Navigate to `brave.com` and `http://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/` to check if the sites work correctly.
- [x] Load `brave.com` and `mail.protonmail.com` in a regular Window/Tab and ensure that clicking the `Tor` button in the URL bar correctly launches a Tor window and opens the appropriate `.onion` website.

### MacOS
- [x] Navigate to `/Users/<user>/Library/Application Support/BraveSoftware/Brave-Browser-<channel>/cldoidikboihgcjfkhdeidbpclkineef/<version>`
- [x] Run `codesign -vvvv tor-<version-tor>-darwin-brave-<version-brave>` to confirm codesign is valid
- [x] For MacOS Catalina (10.15+) - Run `spctl -a -vv -t install tor-<version-tor>-darwin-brave-<version-brave>` to verify that the binary is notarized.

### Tor Client Updater

- [x] For development go-update-server. Run brave-browser with `--user-data-dir=component-dev --use-dev-goupdater-url` (These flags are only available in v1.7.x). Once the crx is pushed to production run without these flags.
- [x] Navigate to `brave://components` and verify `Tor Client Updater (OS)` is updated successfully.
- [x] Open `New Private Window with Tor` and confirm that it starts without any errors.
	- [x] Navigate to `check.torproject.org` and verify that tor is working successfully.
	- [x] Navigate to `brave.com` and `http://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/` to check if the sites work correctly.
- [x] Load `brave.com` and `mail.protonmail.com` in a regular Window/Tab and ensure that clicking the `Tor` button in the URL bar correctly launches a Tor window and opens the appropriate `.onion` website.

### MacOS
- [x] Navigate to `/Users/<user>/Library/Application Support/BraveSoftware/Brave-Browser-<channel>/cldoidikboihgcjfkhdeidbpclkineef/<version>`
- [x] Run `codesign -vvvv tor-<version-tor>-darwin-brave-<version-brave>` to confirm codesign is valid
- [x] For MacOS Catalina (10.15+) - Run `spctl -a -vv -t install tor-<version-tor>-darwin-brave-<version-brave>` to verify that the binary is notarized.

### Tor Client Updater

- [x] For development go-update-server. Run brave-browser with `--user-data-dir=component-dev --use-dev-goupdater-url` (These flags are only available in v1.7.x). Once the crx is pushed to production run without these flags.
- [x] Navigate to `brave://components` and verify `Tor Client Updater (OS)` is updated successfully.
- [x] Open `New Private Window with Tor` and confirm that it starts without any errors.
	- [x] Navigate to `check.torproject.org` and verify that tor is working successfully.
	- [x] Navigate to `brave.com` and `http://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/` to check if the sites work correctly.
- [x] Load `brave.com` and `mail.protonmail.com` in a regular Window/Tab and ensure that clicking the `Tor` button in the URL bar correctly launches a Tor window and opens the appropriate `.onion` website.

### MacOS
- [x] Navigate to `/Users/<user>/Library/Application Support/BraveSoftware/Brave-Browser-<channel>/cldoidikboihgcjfkhdeidbpclkineef/<version>`
- [x] Run `codesign -vvvv tor-<version-tor>-darwin-brave-<version-brave>` to confirm codesign is valid
- [x] For MacOS Catalina (10.15+) - Run `spctl -a -vv -t install tor-<version-tor>-darwin-brave-<version-brave>` to verify that the binary is notarized.

### Tor Client Updater

- [x] For development go-update-server. Run brave-browser with `--user-data-dir=component-dev --use-dev-goupdater-url` (These flags are only available in v1.7.x). Once the crx is pushed to production run without these flags.
- [x] Navigate to `brave://components` and verify `Tor Client Updater (OS)` is updated successfully.
- [x] Open `New Private Window with Tor` and confirm that it starts without any errors.
	- [x] Navigate to `check.torproject.org` and verify that tor is working successfully.
	- [x] Navigate to `brave.com` and `http://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/` to check if the sites work correctly.
- [x] Load `brave.com` and `mail.protonmail.com` in a regular Window/Tab and ensure that clicking the `Tor` button in the URL bar correctly launches a Tor window and opens the appropriate `.onion` website.

### MacOS
- [x] Navigate to `/Users/<user>/Library/Application Support/BraveSoftware/Brave-Browser-<channel>/cldoidikboihgcjfkhdeidbpclkineef/<version>`
- [x] Run `codesign -vvvv tor-<version-tor>-darwin-brave-<version-brave>` to confirm codesign is valid
- [ ] For MacOS Catalina (10.15+) - Run `spctl -a -vv -t install tor-<version-tor>-darwin-brave-<version-brave>` to verify that the binary is notarized.

### Tor Client Updater

- [x] For development go-update-server. Run brave-browser with `--user-data-dir=component-dev --use-dev-goupdater-url` (These flags are only available in v1.7.x). Once the crx is pushed to production run without these flags.
- [x] Navigate to `brave://components` and verify `Tor Client Updater (OS)` is updated successfully.
- [x] Open `New Private Window with Tor` and confirm that it starts without any errors.
	- [x] Navigate to `check.torproject.org` and verify that tor is working successfully.
	- [x] Navigate to `brave.com` and `http://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/` to check if the sites work correctly.
- [x] Load `brave.com` and `mail.protonmail.com` in a regular Window/Tab and ensure that clicking the `Tor` button in the URL bar correctly launches a Tor window and opens the appropriate `.onion` website.

### MacOS
- [x] Navigate to `/Users/<user>/Library/Application Support/BraveSoftware/Brave-Browser-<channel>/cldoidikboihgcjfkhdeidbpclkineef/<version>`
- [x] Run `codesign -vvvv tor-<version-tor>-darwin-brave-<version-brave>` to confirm codesign is valid
- [x] For MacOS Catalina (10.15+) - Run `spctl -a -vv -t install tor-<version-tor>-darwin-brave-<version-brave>` to verify that the binary is notarized.

**Comment by kjozwiak** [comment]
Quick note: The Tor daemon itself was not updated and is still on `0.4.7.10`. However, the following did get upgraded:

* `OpenSSL` - `1.1.1q` -> `1.1.1s`
* `Zlib` - `1.2.12` -> `1.2.13`

**Comment by stephendonner** [comment]
#### Big Sur
<details>


Confirmed that the correct Tor component was being downloaded via --use-dev-goupdater-url:

--use-dev-goupdater-url

<img width="295" alt="Screen Shot 2022-11-04 at 3 32 22 PM" src="https://user-images.githubusercontent.com/387249/200084466-d9669e80-6d32-4665-b7d0-eaf6bec26dfa.png">


Confirmed that the Tor component was started when launching Tor and ensured Tor `0.4.7.10` was being used:

`Nov 04 15:14:18.333 [notice] Tor 0.4.7.10 running on Darwin with Libevent 2.1.12-stable, OpenSSL 1.1.1s, Zlib 1.2.13, Liblzma N/A, Libzstd N/A and Unknown N/A as libc.`

`stephendonner@Stephens-MacBook-Pro ~ % cd /Users/stephendonner/Library/Application\ Support/BraveSoftware/Brave-Browser/cldoidikboihgcjfkhdeidbpclkineef/1.0.55
stephendonner@Stephens-MacBook-Pro 1.0.55 % codesign -vvvv tor-0.4.7.10-darwin-brave-2
tor-0.4.7.10-darwin-brave-2: valid on disk
tor-0.4.7.10-darwin-brave-2: satisfies its Designated Requirement`


`stephendonner@Stephens-MacBook-Pro 1.0.55 % spctl -a -vv -t install tor-0.4.7.10-darwin-brave-2
tor-0.4.7.10-darwin-brave-2: accepted
source=Notarized Developer ID
origin=Developer ID Application: Brave Software, Inc. (KL8N8XSYF4)`

Confirmed that you can open the following domains in a Tor window without issues:

`brave.com`
`duckduckgo.com`
`https://duckduckgogg42xjoc72x3sjasowoarfbgcmvfimaftt6twagswzczad.onion/`
`check.torproject.org` (ensured that hard-refreshing gets a new circuit/IP)

Confirmed the following sites opened via “Open in Tor” button from normal window and navigated to their .onion URL in a Tor window:

`brave.com` --> `https://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/`
`https://account.proton.me/login` --> `https://account.protonmailrmez3lotccipshtkleegetolb73fuirgj7r4o4vfu7ozyd.onion/`
`nytimes.com` --> `https://www.nytimesn7cgmftshazwhfgzm37qxb44r64ytbb2dj3x62d2lljsciiyd.onion/`

</details>

**Comment by LaurenWags** [comment]
Verification in progress for the below:

<details>
<summary>macOS 12.6.1 Monterey x64 - InProgress</summary>

Verified on macOS 12.6.1 x64 using the following build:

```
Brave | 1.45.118 Chromium: 107.0.5304.91 (Official Build) (x86_64)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | macOS Version 12.6.1 (Build 21G217)
```

Confirmed that the correct Tor component was being downloaded via --use-dev-goupdater-url:



Confirmed that the Tor component was started when launching Tor and ensured Tor 0.4.7.10 was being used.

```

```

Confirmed that you can open the following domains in a Tor window without issues:

* brave.com
* duckduckgo.com
* https://duckduckgogg42xjoc72x3sjasowoarfbgcmvfimaftt6twagswzczad.onion/
* check.torproject.org (ensured that hard refreshing gets a new circuit/IP)

Confirmed the following sites opened via “Open in Tor” button from normal window and navigated to .onion URL in a Tor window:

* brave.com --> https://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/
* https://account.proton.me/login --> https://account.protonmailrmez3lotccipshtkleegetolb73fuirgj7r4o4vfu7ozyd.onion/
* nytimes.com --> https://www.nytimesn7cgmftshazwhfgzm37qxb44r64ytbb2dj3x62d2lljsciiyd.onion/

Confirmed that codesign is valid:

```
laurenwags@Laurens-MBP 1.0.52 % codesign -vvvv tor-0.4.7.10-darwin-brave-1 

```

Confirmed that the binary is notarized: 

```
laurenwags@Laurens-MBP 1.0.52 % spctl -a -vv -t install tor-0.4.7.10-darwin-brave-1

```

</details>

**Comment by kjozwiak** [comment]
#### **`macOS 10.13.6 High Sierra x64`** - **PASSED**

Verification **PASSED** on `macOS 10.13.6 High Sierra x64` using the following build:

<details>

```
Brave | 1.45.118 Chromium: 107.0.5304.91 (Official Build) (x86_64) 
--- | ---
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | macOS Version 10.13.6 (Build 17G14042)
```

Launched `1.45.118 Chromium: 107.0.5304.91` using `--use-dev-goupdater-url` and confirmed the following versions:

* `tor` binary ` 0.4.7.10`
* `Brave Tor Client Updater (Mac) - Version: 1.0.55`
* `OpenSSL` - `1.1.1s`
* `Zlib` - `1.2.13`

<img width="351" alt="Screenshot 2022-11-07 at 3 31 26 PM" src="https://user-images.githubusercontent.com/2602313/200409341-c97186d3-73c3-461f-8c1d-52e2ae4597ee.png">

```
[571:29699:1107/152509.452360:INFO:tor_file_watcher.cc(183)] tor: failed to open control auth cookie
Nov 07 15:25:09.463 [notice] Tor 0.4.7.10 running on Darwin with Libevent 2.1.12-stable, OpenSSL 1.1.1s, Zlib 1.2.13, Liblzma N/A, Libzstd N/A and Unknown N/A as libc.
Nov 07 15:25:09.463 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://support.torproject.org/faq/staying-anonymous/
Nov 07 15:25:09.464 [notice] Read configuration file "/Users/kjozwiak/Library/Application Support/BraveSoftware/Brave-Browser/cldoidikboihgcjfkhdeidbpclkineef/1.0.55/tor-torrc".
Nov 07 15:25:09.464 [notice] Read configuration file "/Users/kjozwiak/Library/Application Support/BraveSoftware/Brave-Browser/cldoidikboihgcjfkhdeidbpclkineef/1.0.55/tor-torrc".
Nov 07 15:25:09.466 [notice] Opening Socks listener on 127.0.0.1:0
Nov 07 15:25:09.467 [notice] Socks listener listening on port 49225.
Nov 07 15:25:09.467 [notice] Opened Socks listener connection (ready) on 127.0.0.1:49225
Nov 07 15:25:09.467 [notice] Opening Control listener on 127.0.0.1:0
Nov 07 15:25:09.467 [notice] Control listener listening on port 49226.
Nov 07 15:25:09.467 [notice] Opened Control listener connection (ready) on 127.0.0.1:49226
[571:29699:1107/152509.467718:INFO:tor_file_watcher.cc(183)] tor: failed to open control auth cookie
[571:29699:1107/152509.467871:INFO:tor_file_watcher.cc(183)] tor: failed to open control auth cookie
[571:29699:1107/152509.470206:INFO:tor_file_watcher.cc(183)] tor: failed to open control auth cookie
[571:29699:1107/152509.470636:INFO:tor_file_watcher.cc(183)] tor: failed to open control auth cookie
Nov 07 15:25:09.000 [notice] Bootstrapped 0% (starting): Starting
Nov 07 15:25:09.000 [notice] Starting with guard context "default"
Nov 07 15:25:09.000 [notice] New control connection opened from 127.0.0.1.
Nov 07 15:25:09.000 [notice] Bootstrapped 5% (conn): Connecting to a relay
Nov 07 15:25:11.000 [notice] Bootstrapped 10% (conn_done): Connected to a relay
Nov 07 15:25:11.000 [notice] Bootstrapped 14% (handshake): Handshaking with a relay
Nov 07 15:25:12.000 [notice] Bootstrapped 15% (handshake_done): Handshake with a relay done
Nov 07 15:25:12.000 [notice] Bootstrapped 20% (onehop_create): Establishing an encrypted directory connection
Nov 07 15:25:12.000 [notice] Bootstrapped 25% (requesting_status): Asking for networkstatus consensus
Nov 07 15:25:12.000 [notice] Bootstrapped 30% (loading_status): Loading networkstatus consensus
Nov 07 15:25:13.000 [notice] I learned some more directory information, but not enough to build a circuit: We have no usable consensus.
Nov 07 15:25:13.000 [notice] Bootstrapped 40% (loading_keys): Loading authority key certs
Nov 07 15:25:13.000 [notice] The current consensus has no exit nodes. Tor can only build internal paths, such as paths to onion services.
Nov 07 15:25:13.000 [notice] Bootstrapped 45% (requesting_descriptors): Asking for relay descriptors
Nov 07 15:25:13.000 [notice] I learned some more directory information, but not enough to build a circuit: We need more microdescriptors: we have 0/6125, and can only build 0% of likely paths. (We have 0% of guards bw, 0% of midpoint bw, and 0% of end bw (no exits in consensus, using mid) = 0% of path bw.)
Nov 07 15:25:14.000 [notice] Bootstrapped 50% (loading_descriptors): Loading relay descriptors
Nov 07 15:25:14.000 [notice] The current consensus contains exit nodes. Tor can build exit and internal paths.
Nov 07 15:25:15.000 [notice] Bootstrapped 55% (loading_descriptors): Loading relay descriptors
Nov 07 15:25:15.000 [notice] Bootstrapped 62% (loading_descriptors): Loading relay descriptors
Nov 07 15:25:15.000 [notice] Bootstrapped 73% (loading_descriptors): Loading relay descriptors
Nov 07 15:25:15.000 [notice] Bootstrapped 75% (enough_dirinfo): Loaded enough directory info to build circuits
Nov 07 15:25:16.000 [notice] Bootstrapped 80% (ap_conn): Connecting to a relay to build circuits
Nov 07 15:25:16.000 [notice] Bootstrapped 85% (ap_conn_done): Connected to a relay to build circuits
Nov 07 15:25:16.000 [notice] Bootstrapped 89% (ap_handshake): Finishing handshake with a relay to build circuits
Nov 07 15:25:16.000 [notice] Bootstrapped 90% (ap_handshake_done): Handshake finished with a relay to build circuits
Nov 07 15:25:16.000 [notice] Bootstrapped 95% (circuit_create): Establishing a Tor circuit
Nov 07 15:25:17.000 [notice] Bootstrapped 100% (done): Done
```

Ensured that you can open the following domains in a Tor window without issues:

* brave.com
* duckduckgo.com
* https://duckduckgogg42xjoc72x3sjasowoarfbgcmvfimaftt6twagswzczad.onion
* check.torproject.org (ensured that hard refreshing gets a new circuit/IP)

Confirmed the following sites opened via "Open in Tor" button and navigated to .onion URL:

* brave.com --> https://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion
* mail.protonmail.com --> https://protonmailrmez3lotccipshtkleegetolb73fuirgj7r4o4vfu7ozyd.onion

Confirmed that `codesign` is valid as per the following:

```
macos-10:~ kjozwiak$ codesign -vvvv ~/Library/Application\ Support/BraveSoftware/Brave-Browser/cldoidikboihgcjfkhdeidbpclkineef/1.0.55/tor-0.4.7.10-darwin-brave-2
/Users/kjozwiak/Library/Application Support/BraveSoftware/Brave-Browser/cldoidikboihgcjfkhdeidbpclkineef/1.0.55/tor-0.4.7.10-darwin-brave-2: valid on disk
/Users/kjozwiak/Library/Application Support/BraveSoftware/Brave-Browser/cldoidikboihgcjfkhdeidbpclkineef/1.0.55/tor-0.4.7.10-darwin-brave-2: satisfies its Designated Requirement
```

</details>
