### ISSUE TITLE
Brave sigkill and hi memory consumption

### ISSUE THREAD

**Issue by Deviner75** [brave/brave-browser#26558]
## Description 
Crashes on memory heavy websites like youtube. Using a lot of memory overall. About 13gb! with 1-2 youtube tabs open.

## Steps to Reproduce
Potential steps:
Packages:
Arch linux 6.0.6-arch1-1
nvidia-open
opencl-nvidia

Potentially conflicting:
blender
houdini sidefx
clinfo

## Actual result:
Tabs go offline with sigkill one by one after ~10 min of usage.

## Brave version

Brave | 1.47.47 Chromium: 107.0.5304.91 (Official Build) nightly (64-bit)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | Linux
JavaScript | V8 10.7.193.18
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Command Line | /opt/brave.com/brave-nightly/brave --enable-crashpad --disable-domain-reliability --enable-dom-distiller --component-updater=url-source=https://go-updater.brave.com/extensions --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --variations-insecure-server-url=https://variations.brave.com/seed --flag-switches-begin --flag-switches-end
Executable Path | /opt/brave.com/brave-nightly/brave
Profile Path | /home/deviner/.config/BraveSoftware/Brave-Browser-Nightly/Default
Active Variations | AdRewardsStudy:NextPaymentDayAllowCertainClientHintsStudy:DisabledBraveAdblockCookieListOptInStudy:EnabledBraveAds.AdNotificationsStudy:AdNotificationTimeout=15BraveAds.AdServingStudy:DefaultAdNotificationsPerHour=10/MaximumAdNotificationsPerDay=100/MaximumInlineContentAdsPerHour=12/MaximumInlineContentAdsPerDay=60/AdServingVersion=2/AdPredictorWeights=16.0,8.0,16.0,8.0,0.0,0.0,0.0BraveAds.FrequencyCappingStudy:ExcludeAdIfWithinTimeWindow=0hBraveAds.UserActivityStudy:Triggers=NTPSI/TimeWindow=15m/Threshold=0.0/IdleTimeThreshold=5sBraveDebounceStudy:EnabledBraveRewardsWebUiPanelStudy:EnabledBraveScreenFingerprintingBlockerStudy:EnabledBraveSearchPromotionDesktopNTPStudy:EnabledConversionsStudy:NewDefaultPatternCookieListDefaultStudy:DisabledDeAMPStudy:EnabledDefault1pBlockingStudy:DisabledDisableReduceLanguage:EnabledEphemeralStorageStudy:EnabledFirstPartyEphemeralDomainBlockStudy:EnabledForceDisableBlinkFeatures:EnabledHangWatcher:HangWatcherEnableDumpsPartitionBlinkMemoryCacheStudy:EnabledPartitionConnectionsByNetworkIsolationKeyStudy:EnabledPermissionLifetimeStudy:Enabled

- Can you reproduce this issue with the nightly channel? 
Yes: [Version 1.47.47 Chromium: 107.0.5304.91 (Official Build) nightly (64-bit)](https://brave.com/latest/)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
not really
- Does the issue resolve itself when disabling Brave Rewards?
no
- Is the issue reproducible on the latest version of Chrome?
don't have an access to chrome

**Comment by deivastra** [comment]
Please add information from `brave://version` page to your issue.
Also need test with Chromium Browser instead of Chrome.
Thanks.

**Comment by Deviner75** [comment]
Works stable on chromium too!


Chromium | 107.0.5304.87 (Official Build) Arch Linux (64-bit)
-- | --
Revision | f59ffb32abf8c01e9aa298400314bfdf0221b02f-refs/branch-heads/5304@{#1093}
OS | Linux
JavaScript | V8 10.7.193.18
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Command Line | /usr/lib/chromium/chromium --enable-crashpad --flag-switches-begin --flag-switches-end
Executable Path | /usr/lib/chromium/chromium
Profile Path | /home/deviner/.config/chromium/Default

**Comment by Deviner75** [comment]
it's fine after I reinstalled the whole system
