### ISSUE TITLE
Manual test run on Linux for Tor 0.4.7.10 - Release #2

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#26556]
## Tor Client Updater

- [x] For development go-update-server. Run brave-browser with `--user-data-dir=component-dev --use-dev-goupdater-url` (These flags are only available in v1.7.x). Once the crx is pushed to production run without these flags.
- [x] Navigate to `brave://components` and verify `Tor Client Updater (OS)` is updated successfully.
- [x] Open `New Private Window with Tor` and confirm that it starts without any errors.
	- [x] Navigate to `check.torproject.org` and verify that tor is working successfully.
	- [x] Navigate to `brave.com` and `http://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/` to check if the sites work correctly.
- [x] Load `brave.com` and `mail.protonmail.com` in a regular Window/Tab and ensure that clicking the `Tor` button in the URL bar correctly launches a Tor window and opens the appropriate `.onion` website.

### Linux
- [x] Navigate to `<user-data-dir>/biahpgbdmdkfgndcmfiipgcebobojjkp`
- [x] Run `ldd tor-<version-tor>-linux-brave-<version-brave>` to confirm tor client is a static binary

**Comment by kjozwiak** [comment]
Quick note: The Tor daemon itself was not updated and is still on `0.4.7.10`. However, the following did get upgraded:

* `OpenSSL` - `1.1.1q` -> `1.1.1s`
* `Zlib` - `1.2.12` -> `1.2.13`

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.45.118 Chromium: 107.0.5304.91 (Official Build) (64-bit)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | Ubuntu 18.04 LTS

Verified tor initialized successfully
```
Nov 04 19:39:43.831 [notice] Tor 0.4.7.10 running on Linux with Libevent 2.1.12-stable, OpenSSL 1.1.1s, Zlib 1.2.13, Liblzma N/A, Libzstd N/A and Glibc 2.35 as libc.
Nov 04 19:39:49.000 [notice] Bootstrapped 95% (circuit_create): Establishing a Tor circuit
Nov 04 19:39:49.000 [notice] Bootstrapped 100% (done): Done
```

Verified static library
![image](https://user-images.githubusercontent.com/34715963/200062746-718869de-5eee-4e9c-99ee-6450434827ae.png)
