### ISSUE TITLE
Persist show/hide wallet portfolio chart user pref

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#26557]
## Description 

The chart on the Brave Wallet portfolio overview screen should remain displayed/hidden based on subsequent page loads when the user shows or hide the chart.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.47.126 Chromium: 108.0.5359.99 (Official Build) beta (64-bit)
-- | --
Revision | `410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}`
OS | Linux

- Verified steps from [brave/brave-core#15807](https://github.com/brave/brave-core/pull/15807)
- Verified page refresh retains show/hide chart button state

https://user-images.githubusercontent.com/17010094/207542341-88076758-a947-4493-8a5d-a5528edea409.mp4

---------------------

Verification passed on 

Brave | 1.47.126 Chromium: 108.0.5359.99 (Official Build) beta (64-bit)
-- | --
Revision | `410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#15807](https://github.com/brave/brave-core/pull/15807)
- Verified page refresh retains show/hide chart button state

https://user-images.githubusercontent.com/17010094/207542823-59a92e85-e6aa-464e-9c6f-68b1313c2f5e.mp4

---------------------



Verification passed on 

Brave | 1.47.126 Chromium: 108.0.5359.99 (Official Build) beta (arm64)
-- | --
Revision | `410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#15807](https://github.com/brave/brave-core/pull/15807)
- Verified page refresh retains show/hide chart button state

https://user-images.githubusercontent.com/17010094/207542773-8debf218-daad-4b23-b2d7-ff0dd8fdb82b.mov
