### ISSUE TITLE
bastyon.com: Aw, Snap! A Tab crashes while start upload video. (linux/snap)

### ISSUE THREAD

**Issue by DeivAstra** [brave/brave-browser#26565]
## Description 

Snapped Brave always crashes while start upload video file.

## Steps to Reproduce
   1. Login to Bastyon and open url: https://bastyon.com/userpage?id=videoCabinet
   2. Press upload video and select one
   3. Press open/upload

## Actual result:
Got crached  Tab with message: `Error code: RESULT_CODE_KILLED_BAD_MESSAGE`

## Expected result:
Starting upload video with progress bar

## Reproduces how often: 
Always

## Brave version (brave://version info)
**Brave**	| 1.45.118 Chromium: 107.0.5304.91 (Official Build) (64-bit) 
**Revision** | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
**OS** | Linux
**JavaScript**	| V8 10.7.193.18
**User Agent**	| Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
**Command Line** | /snap/brave/185/opt/brave.com/brave/brave --user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36 --enable-crashpad --disable-domain-reliability --enable-dom-distiller --component-updater=url-source=https://go-updater.brave.com/extensions --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --variations-insecure-server-url=https://variations.brave.com/seed --flag-switches-begin --flag-switches-end --desktop-startup-id=xfce4-panel/env/1196-11-crypto_TIME258515014
**Executable Path** | /snap/brave/185/opt/brave.com/brave/brave
**Profile Path** | /home/user/snap/brave/185/.config/BraveSoftware/Brave-Browser/Default
**Active Variations**  | 
AdRewardsStudy:NextPaymentDay
BraveAdblockCookieListOptInReleaseStudy:Enabled
BraveAds.AdServingStudy:DefaultAdNotificationsPerHour=10/MaximumAdNotificationsPerDay=100/MaximumInlineContentAdsPerHour=12/MaximumInlineContentAdsPerDay=60/AdServingVersion=1
BraveAds.FrequencyCappingStudy:ExcludeAdIfWithinTimeWindow=0h
BraveAds.UserActivityStudy:Triggers=NTPSI/TimeWindow=15m/Threshold=0.0/IdleTimeThreshold=5s
BraveDebounceStudy:Enabled
BraveRewardsWebUiPanelStudy:Enabled
BraveScreenFingerprintingBlockerStudy:Default
ConversionsStudy:NewDefaultPattern
Default1pBlockingStudy:Disabled
DisableReduceLanguage:Enabled
EphemeralStorageStudy:Enabled
FirstPartyEphemeralDomainBlockStudy:Enabled
ForceDisableBlinkFeatures:Enabled
PartitionBlinkMemoryCacheStudy:Enabled
PartitionConnectionsByNetworkIsolationKeyStudy:Enabled
PermissionLifetimeReleaseStudy:Enabled
SpeedreaderReleaseStudy:Enabled

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
Yes
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 
Not tested.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
Private mode, shields disabled.
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?
No.

## Miscellaneous Information:

```# lsb_release -a```
Description:	Ubuntu 20.04.4 LTS
Codename:	focal

```# snap --version```
snap    2.57.4
snapd   2.57.4
series  16
ubuntu  20.04
kernel  5.13.0-35-generic

**Comment by iefremov** [comment]
stale
