### ISSUE TITLE
Brave crashing during update

### ISSUE THREAD

**Issue by vmartinv** [brave/brave-browser#26566]
Brave started crashing after 2 minutes of being open, independently of the tabs. I saw that it was trying to install an update, so I downloaded and installed the latest version manually. This solved it, but there was certainly a problem while updating.

Brave Version: 1.45.118  Chromium: 107.0.5304.91
Operating System: Mac OS X 12.6.0

URL (if applicable) where crash occurred: -

Can you reproduce this crash? Not exactly

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Have a version older than 1.45.118 (not sure exactly which one I had)
2. Wait to get update to 1.45.118

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/61620600-f0bb-1809-0000-000000000000

**Comment by simonhong** [comment]
Hello @vmartinv , we had crash issue (https://github.com/brave/brave-browser/issues/26412) and it's fixed at `1.45.118`.
Maybe you've enabled crypto.com widget on NTP?

**Comment by rebron** [comment]
@vmartinv You're not encountering crashes anymore with 1.45.118 are you?

**Comment by vmartinv** [comment]
> Hello @vmartinv , we had crash issue (#26412) and it's fixed at `1.45.118`.
> Maybe you've enabled crypto.com widget on NTP?

No, I didn’t.

**Comment by vmartinv** [comment]
> @vmartinv You're not encountering crashes anymore with 1.45.118 are you?

Yes, as I mentioned initially manually updating to 1.45.118 fixed the issue.
