### ISSUE TITLE
Brave News Customize sidebar has some style issues

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#26560]
- Channels don't have icons
- Grid spacing is too much
- Font family is incorrect in some places
- Sources list title is too bold
- Long source names are not wrapping correctly

<img width="811" alt="image" src="https://user-images.githubusercontent.com/741836/200088369-cb711f96-6bcf-4c20-ad5a-20fb3757c31b.png">

**Comment by stephendonner** [comment]
@petemill can you also include https://github.com/brave/brave-browser/issues/26293, if not already?

**Comment by kjozwiak** [comment]
The above requires `1.46.107` or higher for `1.46.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.46.122 Chromium: 108.0.5359.48 (Official Build) beta (x86_64)
-- | --
Revision | 18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}
OS | macOS Version 11.7.1 (Build 20G918)

### Ensured:

- channels have icons
- CSS-grid spacing flexes better
- improved font-family usage
- reduced Sources title boldness
- better wrapping of long source names

#### UI

`Light` | `Dark`
--------|-------
<img width="1228" alt="Screen Shot 2022-11-21 at 8 46 35 PM" src="https://user-images.githubusercontent.com/387249/203224201-5c035fa3-d506-4af3-827f-0f03e46acb97.png"> | <img width="1228" alt="Screen Shot 2022-11-21 at 8 47 33 PM" src="https://user-images.githubusercontent.com/387249/203224203-3e484627-d937-458c-8253-309b90cb07bd.png">

#### Channels

`Light` | `Dark`
--------|-------
<img width="1228" alt="Screen Shot 2022-11-21 at 8 48 49 PM" src="https://user-images.githubusercontent.com/387249/203224389-02d66eaa-a826-4799-a9cc-5ec1f6e15c37.png"> | <img width="1228" alt="Screen Shot 2022-11-21 at 8 48 30 PM" src="https://user-images.githubusercontent.com/387249/203224417-c0d63706-80c1-4553-bdbd-3150c951e006.png">
