### ISSUE TITLE
Use infobar for WDP promotion instead of dialog

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#26576]
Replace WDP promotion dialog with infobar
- Show Infobar on Brave Search result page
- User can see 5 times maximum and only once per day if not dismissed
- If dismissed, it'll not be shown for current CTA
- Infobar state is tied with specific CTA
  - This means infobar can be visible again with new CTA
~~- Design and sentences are not finalized yet~~

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.47.115 Chromium: 108.0.5359.94 (Official Build) beta (64-bit)
-- | --
Revision | 713576b895246504ccc6b92c2fb8ce2d60194074-refs/branch-heads/5359_71@{#3}
OS | Windows 11 Version 21H2 (Build 22000.1219)
```

**Comment by stephendonner** [comment]
> Testing is complete however, as per @rebron this may be `QA/No` to let Brave Search team take a look. cc: @kjozwiak @LaurenWags

Got the OK to keep going from @rebron 👌

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.47.125 Chromium: 108.0.5359.99 (Official Build) beta (x86_64)
-- | --
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | macOS Version 11.7.1 (Build 20G918)

Case 1
Case 2
Case 3
Case 4
Case 5
Case 6
Case 7
Case 8
