### ISSUE TITLE
Tab counts changed from number of groups to number of tabs

### ISSUE THREAD

**Issue by ehaynes99** [brave/brave-browser#26578]
## Description 
Previously, the number in the bar at the bottom was the number of tab groups, but now it's the total number of tabs across all groups.

## Steps to reproduce 
Open multiple tab groups such as:
```
- 3 tabs
- 6 tabs
- 2 tabs
```

## Actual result 
The counter at the bottom of the screen shows "11"

## Expected result
The counter would show "3".

## Issue reproduces how often 
Always

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
  - yes
- Can you reproduce this issue with the current Play Store Beta version?
  - yes
- Can you reproduce this issue with the current Play Store Nightly version?
  - yes

## Device details
   - Install type: ARM
   - Device type: Phone
   - Android version: 11
   
## Brave version
1.45.120, C\hromium 107.0.5304.91

### Additional information
I didn't see any issues here on GitHub. I'm not sure if the change was intentional or not, but it largely defeats the purpose of tab groups, IMO. I use them as "a bunch of tabs about the same general thing". The whole reason I use it is to escape the "97 tabs of random crap" issue that inevitably arises when using just one window. On a desktop, these work relatively consistently across Windows, Mac, and most Linux DEs. Tiling through with
```
alt+`
```
(where applicable) shows the "tab groups" individually. If the OS has a taskbar, hovering also shows the groups individually.

Not the end of the world, but hopefully this is configurable somehow that I'm just overlooking. Ideally at this point, any change to tabs should just be an option. It's been 30 years of yanking the rug out from under people. It's really not a subject that can be innovated any further. It's essentially a file tree: tabs are files, tab groups are directories.

**Comment by srirambv** [comment]
I don' think this has changed. count is always for the number of tabs opened and not the number of groups.

cc: @samartnik

**Comment by ehaynes99** [comment]
No, it was definitely the number of groups until recently. Looks like it was a Chromium change though. :(

https://source.chromium.org/chromium/chromium/src/+/50c51cb7d57f12ae44a76982e777dd75b03606ce
