### ISSUE TITLE
Follow up of #24331- VPN can't be reconnected in the same session when internet/wifi is disconnected and reconnected

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#26579]
## Description 

Follow up of #24331- VPN can't be reconnected in the same session when internet/wifi is disconnected and reconnected
## Steps to Reproduce

   1. Follow the steps from https://github.com/brave/brave-browser/issues/23081
 
Please note that issue is reproducible for myself and @MadhaviSeelam on Windows 10 x64 and Windows 11 x64 as per https://github.com/brave/brave-browser/issues/24331#issuecomment-1295247448 and https://github.com/brave/brave-browser/issues/24331#issuecomment-1295312400

Works fine on macOS, https://github.com/brave/brave-browser/issues/24331#issuecomment-1295204070 

## Actual result:

https://github.com/brave/brave-browser/issues/24331#issuecomment-1295247448

## Expected result:

Should be able to reconnect the VPN in the same browser session when wifi is reconnected
## Reproduces how often: 

Easy
## Brave version (brave://version info)

Windows 10 x64 - `1.47.24 and 1.46.81`

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @spylogsster @bsclifton @simonhong

**Comment by stephendonner** [comment]
Steps on macOS which reproduce 100%:

1. install `1.47.87`
2. launch Brave
3. open `brave://flags`
4. set `brave://flags/#brave-vpn` to `Enabled`
5. purchase VPN from `account.bravesoftware.com`
6. click on the VPN button in the browser toolbar
7. ensure you're connected
8. disconnect via any method (browser toolbar, flyout menu-items, Network panel -> BraveVPN in macOS's System Preferences...)
9. ensure correct status is reflected in the remainder of the UI and in the Network panel
10. disable Wi-Fi
11. try to reconnect to BraveVPN
12. confirm you get the `Can't connect to server` dialog
13. re-enable Wi-Fi
14. confirm VPN is not connected
15. click on the `VPN` button
16. click on `Choose another server`
17. select any network region
18. click `Connect`
19. confirm you are connected to `BraveVPN` now
20. look at the dialog on the `VPN` button

Actual Results:

Still show `Can't connect to server` dialog

**Comment by simonhong** [comment]
note - at the step 16, error panel is gone if we connect via retry instead of `Choose another server`

**Comment by GeetaSarvadnya** [comment]
Marking this as QA/No as the follow up issue is been logged https://github.com/brave/brave-browser/issues/26938 and the issues verification will be taken care in that issue
