### ISSUE TITLE
New version of Brave breaks password manager

### ISSUE THREAD

**Issue by geoidesic** [brave/brave-browser#26571]
## Description 

Happens on one device but works fine on a different device. I've checked the settings and it claims to be saving the password and I can see the password in the password manager but it doesn't offer the password in a drop-down when it should on one of my devices. It used to, incidentally, on this same device.. and then one day recently it just stopped working.

## Steps to Reproduce

   1. Upgrade Brave version (see below).

## Actual result:

![Screenshot 2022-11-06 at 13 11 26](https://user-images.githubusercontent.com/4637995/200172645-a27e2f7a-9cca-4442-9eb7-c325612e3e2e.png)

You can see that the password is saved in the password manager but when I click in the field it does not provide the drop-down with the password option.

## Expected result:
<img width="1552" alt="Screenshot 2022-11-06 at 13 12 36" src="https://user-images.githubusercontent.com/4637995/200172688-e89dc5d3-430c-40fc-9ca5-d4fecaccdd8b.png">

This screenshot was taken from another device and as you can see here it does provide the drop-down.

## Reproduces how often: 

Always happens on one device but never on the other device.

## Brave version (brave://version info)

The device on which it is not working is using this version:
[Version 1.45.118 Chromium: 107.0.5304.91 (Official Build) (arm64)](https://brave.com/latest/)
The device on which it is working is still using this version:
[Version 1.44.108 Chromium: 106.0.5249.103 (Official Build) (arm64)](https://brave.com/latest/)

Both devices are apple M1 chip devices running MacOS 12.6

Update – I updated Brave on the device on which it was working and now it is no longer working on that device. So it looks like a bug introduced in the new version

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

Sorry I did not understand this question

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome?  No

**Comment by EGA-SUPREMO** [comment]
Not sure if this is related, but each time I open brave and I dont put my password I lose all logged accounts, it started to happen after being updated, should I post a new issue?

**Comment by rebron** [comment]
Need to check if this is site specific and also if this reproduces in Chrome.

**Comment by geoidesic** [comment]
Agreed, it seems to have been fixed now. (I also upgraded to MacOS Ventura)
