### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by burzno** [brave/brave-browser#26580]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.43.93  Chromium: 105.0.5195.127
Operating System: Linux 5.4.0-126-generic

URL (if applicable) where crash occurred:

Can you reproduce this crash?
Au simple lancement de l'application

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1.Ouvrir Brave
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/82150a00-f0bb-1809-0000-000000000000

**Comment by rebron** [comment]
hi @burzno Can you update to 1.45.118 by visiting brave://settings/help and let us know if you're still seeing a crash.

**Comment by burzno** [comment]
Hi,
I already have this version.
But today Brave seems stable, there is no crash.
I continue to use it.

Le lun. 7 nov. 2022 à 23:45, Rafael Ebron ***@***.***> a
écrit :
