### ISSUE TITLE
Switching Tabs automatically hides the wallet icon on Solana Dapp

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#26583]
## Description 
Switching Tabs automatically hides the wallet icon on Solana Dapp

## Steps to reproduce 

   1. Connect to a Solana Dapp
   2. Ensure wallet icon is shown in the URL bar
   3. Switch tab 
   4. Go back to Solana Dapp tab, Wallet icons is not shown
   5. Reload Solana Dapp tab, shows wallet icon again

## Actual result 
Switching Tabs automatically hides the wallet icon on Solana Dapp

## Expected result
Should continue to show the wallet irrespective of tab is in focus or not

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.46.96 x64 Beta build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @Pavneet-Sing

**Comment by Pavneet-Sing** [comment]
@srirambv I tested this on various sites (magic edan, pwgoom) but unable to reproduce, can you share the site name you used  to reproduce this or maybe try this on latest nightly if you haven't?

[wallet-icon.webm](https://user-images.githubusercontent.com/11755381/200312143-56489540-088f-4378-a0dc-6502681c418d.webm)

**Comment by srirambv** [comment]
@Pavneet-Sing  here's a recording of the issue.

https://user-images.githubusercontent.com/17010094/200313847-41ca2ecc-7d39-44d2-8aca-9cbaf68c8909.mp4

**Comment by srirambv** [comment]
Verification passed on the following devices running 
- Verified steps from [brave/brave-core#15904](https://github.com/brave/brave-core/pull/15904)
- Verified switching tabs doesn't hide the wallet button on Solana Dapp page

Oppo Reno 5 (Android 12) | Lenovo Tab (Android 12)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/207089042-d186bb48-1c6b-4d09-a083-9c1c794469e0.mp4> | <video src=https://user-images.githubusercontent.com/17010094/207089088-cc669c52-9ec8-44b4-aa7d-d2a2f16463c4.mp4>
