### ISSUE TITLE
[Android] Content filtering via settings

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#26587]
## Description
Currently users can enable/disable content filtering lists via settings on iOS and Desktop. This ticket is to bring over the same feature to Android.

| Desktop Feature  | iOS Feature |
| ------------- | ------------- |
| <img width="972" alt="image" src="https://user-images.githubusercontent.com/28269287/200372217-c135a2e0-bc48-4c8e-a3c4-1953b5f93b58.png">  | ![image](https://user-images.githubusercontent.com/28269287/200372384-d55754f0-afb2-4a5f-aa29-22b494e4a3a3.png)

## Requirements

- Android users are able to enable/disable individual content filtering lists via settings.
- The setting should live under Brave Shields & privacy, after the "prevent fingerprinting via language settings" toggle.

### Design
We should do the same as iOS, a screen with a list of toggles. @Sam-Sibley @deeppandya  I don't think we need any designs here. We can just re-use the screen we have for Brave News -> All Sources. Let me know if you think otherwise?

![image](https://user-images.githubusercontent.com/28269287/200372966-5b08c3aa-330b-4d6c-aa05-a0c6dd72f684.png)

**Comment by kjozwiak** [comment]
The above requires `1.59.100` or higher for `1.59.x` verification 👍 Adding `QA/Test-All-Platforms` as we'll want to double check on the `Tablet` and ensure that everything is being displayed correctly.

**Comment by hffvld** [comment]
Verified on `Pixel 2 XL`, `Galaxy Tab S8` and `Pixel 7` using version(s):
```
Device/OS: 
- Pixel 2 XL [taimen-user  8.1.0 OPM2.171026.006.H1 release-keys]
- Galaxy Tab S8 [gts8wifixx-user 13 TP1A.220624.014 release-keys]
- Pixel 7 [panther_beta-user 14 U1B1.230908.003 release-keys]
Brave build: 1.59.109
Chromium: 118.0.5993.21 (Official Build) beta (64-bit) 
Revision: aacb6a6f8bd916bd49f064b2137b007fa6c47b51
```
---------------------------

**STEPS:**
1. Followed the steps from https://github.com/brave/brave-core/pull/19670#issue-1850212175

**ACTUAL RESULTS:**
- Verified that the default `filter list` is visible via `Settings` > `Brave Shields & privacy` > `Content Filtering`
  - Checked using both `Dark` and `Light` Mode
- Verified that disabling/enabling `Fanboy's Mobile Notifications` via `Settings` > `Brave Shields & privacy` > `Content Filtering` is working
  - Verified that the `Open with` modal appears within `reddit.com` once the filter is disabled (proving that filters are working)
  - Verified that the `Open with` modal is NOT appearing once `Fanboy's Mobile Notifications` is re-enabled
- Compared the default `filter list` between `1.58.135` via `brave://adblock` and `1.59.102` via `Content Filtering` settings
  - Verified that we're not missing any entries when we moved into the native implementation
- Verified that the settings persist after restarting (stay enabled/stay disabled etc.)
- Verified that enabling/disabling the default `filter list` via the toggles doesn't crash Brave

---------------------------

*Pixel 2 XL / Android 8*

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/77feaccd-0781-4a82-9668-b1658391672c) | ![2](https://github.com/brave/brave-browser/assets/128532965/6cd08321-6707-4198-8a69-74c78dd6e4da) | ![3](https://github.com/brave/brave-browser/assets/128532965/d3274f59-8b78-4687-98fd-ea781dce1be7) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/e76d493e-69a3-473d-9626-46f9031fb5c7) | ![2](https://github.com/brave/brave-browser/assets/128532965/2b6fde4a-0221-4e19-99ad-91a1c7e4481a) | ![3](https://github.com/brave/brave-browser/assets/128532965/4e8c7536-dfc9-47fb-b733-f6a698af6eec) |

*Galaxy Tab S8 / Android 13*

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/fb4d09a9-2b3b-4050-9858-4c36991ad4ed) | ![2](https://github.com/brave/brave-browser/assets/128532965/eac6cbf6-3702-46a5-be6f-cc0ff3e6ccc0) | ![3](https://github.com/brave/brave-browser/assets/128532965/400ba9d9-a5eb-4a46-bebc-780374824f90) | ![4](https://github.com/brave/brave-browser/assets/128532965/026cc711-23f9-423b-9653-bed480d61d3e) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/c0a44bde-be85-4c9f-8153-2745f6a49167) | ![2](https://github.com/brave/brave-browser/assets/128532965/eed1bc1d-6976-40f7-8b2a-4a113f13dcee) | ![3](https://github.com/brave/brave-browser/assets/128532965/2de43e99-e138-4558-9996-b6140624d1f0) | ![4](https://github.com/brave/brave-browser/assets/128532965/976a98e5-e634-4328-b285-f475f2f4f897) |

*Pixel 7 / Android 14*

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/5e93338d-53ba-4718-b5ab-e40302476e65) | ![2](https://github.com/brave/brave-browser/assets/128532965/21c1a045-8937-41aa-bca5-e78613d09fbb) | ![3](https://github.com/brave/brave-browser/assets/128532965/7816fa68-1379-4352-8f25-5ae3e700c641) | ![4](https://github.com/brave/brave-browser/assets/128532965/674567c1-d789-49bf-a522-0ed8a629d029) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/a149b8d9-4f96-415a-b8c7-0644320c1aed) | ![2](https://github.com/brave/brave-browser/assets/128532965/74ae0e0d-744f-4243-95c7-5bd364fdec80) | ![3](https://github.com/brave/brave-browser/assets/128532965/b915303c-5c43-492d-80b5-50178c58eadd) | ![4](https://github.com/brave/brave-browser/assets/128532965/a0b50f35-ddfd-4201-8c82-1eeb782921e9) |
