### ISSUE TITLE
Brave News: do not show null ranked sources in Popular list

### ISSUE THREAD

**Issue by mattmcalister** [brave/brave-browser#26597]
Brave Blog's rank is `null`, but it appears at the top of the Popular list in the new Discover panel in the Settings UX
https://github.com/brave/news-aggregator/blob/master/sources.en_US.csv

![image](https://user-images.githubusercontent.com/71029/200409505-2114845a-ba99-45f8-9d38-e4e93cc4ff20.png)

**Comment by fallaciousreasoning** [comment]
I'm closing this, it seems to be fine in the latest nightly (Brave Blog doesn't show at the top of Popular).
