### ISSUE TITLE
Duplicate content appearing in feed

### ISSUE THREAD

**Issue by mattmcalister** [brave/brave-browser#26596]
Sometimes the feed will show me two identical articles. In this example using Version 1.47.52 Chromium: 107.0.5304.91 (Official Build) nightly (arm64), I am not subscribed to any channels, only individual sources:
![image](https://user-images.githubusercontent.com/71029/200402463-b403c60c-4002-4daf-9b3d-6eb945ad079c.png)

The duplicates do not appear as duplicates in the raw feed.

**Comment by petemill** [comment]
@mattmcalister Can you add a screenshot of your customize section and also more info about where in the feed the duplication is happening, relative to either the top of the feed if close, or another landmark like a list

**Comment by mattmcalister** [comment]
The first duplicate to appear is the 3rd item in my feed
![image](https://user-images.githubusercontent.com/71029/200404527-9a3be05d-0cb7-48ba-89ef-9b5be0f9622c.png)

And my Following list includes:

- Ars Technica
- Bleacher Report
- Brave Blog
- Breaking the News
- Formula One | The Guardian
- Gardening Know How
- Hacker News
- Space.com
- Techmeme
- The Atlantic
- The Isle Of Thanet News
- The Verge
- Timeout
- Toms Hardware
- Tottenham Hotspur | The Guardian
- Wikihow
- Wired
- XKCD

![image](https://user-images.githubusercontent.com/71029/200404917-479414fc-20d2-4f89-bd32-f7d9a75aa6aa.png)

**Comment by mattmcalister** [comment]
STR
1. Open Brave News Discover panel.
2. Start with a clean slate. Unfollow all feeds.
3. Search for one feed and follow it. For example, `The Atlantic` or `Wired`. 
4. Close Settings
5. Refresh NTP
6. Scroll down

**Comment by fallaciousreasoning** [comment]
I wonder if this is a bug in the fetching the feed in all locales code? What's in your `Preferences` file under `today.sources` and `news.channels`?

**Comment by mattmcalister** [comment]
`"news":{"channels":{"":{"Top Sources":true},"en_US":{"Crypto":true,"Politics":true,"Top News":true,"Top Sources":true,"Weather":true,"World News":true}}}`

**Comment by mattmcalister** [comment]
`"sources":{"851807a03afb6804b83dd50a72a21afb0c90ce9be1035452d40601e47e4b02a0":false,"9267d9058a847bcb7d53de0e9ca1aa5946c6ca89c1f0ae2689ddf77cac3f0de9":false,"f3373c57bd23f617d991ef066a2645351eaf54859c37d8877c06f72749a0f573":false}`

**Comment by fallaciousreasoning** [comment]
Ah, so I'm pretty sure that first one is the cause - I actually though we fixed that a while back. Does it still happen with a new profile? If not, remove the `"": { "Top Sources": true }` from `channels`.

**Comment by mattmcalister** [comment]
fixed!

**Comment by mattmcalister** [comment]
latest update appears to have cleared it up. will keep an eye on it, but I'm going to close this issue now.

**Comment by petemill** [comment]
I added a test plan with the STR @fallaciousreasoning fixed with https://github.com/brave/brave-core/pull/15984

**Comment by LaurenWags** [comment]
Requires `1.46.122` or higher to test.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.46.121 Chromium: 108.0.5359.48 (Official Build) beta (64-bit)
-- | --
Revision | 18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}
OS | Windows 11 Version 21H2 (Build 22000.1219)
```

Reproduced the issue in 1.46.117

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.46.122 Chromium: 108.0.5359.48 (Official Build) beta (x86_64)
-- | --
Revision | 18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}
OS | macOS Version 11.7.1 (Build 20G918)



### Steps:
1. installed `1.46.122`
2. launched Brave
3. opened a new-tab page
4. scrolled down
5. clicked on `Customize`
6. followed `CNN`, `Techcrunch`, and `CNN - World News` feeds
7. scrolled through my Brave News feed


#### Confirmed no feed/article duplicates


example | example | example
---------|---------|---------
<img width="1312" alt="Screen Shot 2022-11-21 at 10 14 31 PM" src="https://user-images.githubusercontent.com/387249/203238986-0b52b5bc-4477-4279-a20e-4123d1d122f7.png"> | <img width="1312" alt="Screen Shot 2022-11-21 at 10 15 13 PM" src="https://user-images.githubusercontent.com/387249/203239000-9b7d04d2-36c2-442c-9b67-a66991ea3aed.png"> | <img width="1312" alt="Screen Shot 2022-11-21 at 10 18 17 PM" src="https://user-images.githubusercontent.com/387249/203239420-9174222e-67c7-4107-9392-dd2d865e64f3.png">
