### ISSUE TITLE
Brave News: show 15 sources in Suggestions list

### ISSUE THREAD

**Issue by mattmcalister** [brave/brave-browser#26598]
As noted by @LorenzoMinto the precision of the suggestions declines the further you scroll down. So, let's reduce the number presented to the user to 15 sources in total.

**Comment by kjozwiak** [comment]
@mattmcalister assuming this is referring to `Brave News v2`? If that's the case, then this is blocked on `Android` until we enable the feature via `1.50.x` and then make a decision re: uplifting into `1.49.x`. We're still waiting on @deeppandya to enable `Brave News v2` on `1.50.x`. If we decide to let it ride the trains via `1.50.x`, this will be a `QA/No` for `Android` and the feature will get verified as a whole via `1.50.x`.

**Comment by fallaciousreasoning** [comment]
This one was particularly for desktop I think - we were showing all the suggestions & now we limit it to 15. If we do the same on Android once the feature is enabled I think that should be fine.

**Comment by mattmcalister** [comment]
not a problem. it's a UX enhancement, happy for it to land whenever makes sense.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.49.97 Chromium: 110.0.5481.77 (Official Build) beta (x86_64)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | macOS Version 11.7.3 (Build 20G1116)

### Steps:
1. installed `1.49.97`
2. launched Brave
3. opened a new-tab page
4. scrolled down
5. clicked on `Show Brave News`
6. followed a few sources
7. clicked on `View All` beside `Suggestions`

#### Confirmed we now cap the `Suggestions` list at `15` items, where we have over 3 pages worth, in `1.49.15`

`1.49.97`  | `1.49.15` |  `1.49.15, page 2` | `1.49.15, page 3`        
-----------|---------|-----------|----------
<img width="1312" alt="Screen Shot 2023-02-14 at 10 02 47 PM" src="https://user-images.githubusercontent.com/387249/218947763-66953ca6-696f-42d1-8094-52e02eca6fb1.png"> | <img width="1240" alt="Screen Shot 2023-02-14 at 10 21 05 PM" src="https://user-images.githubusercontent.com/387249/218948955-62a88bbe-824b-4829-a661-1a006796d151.png"> | <img width="1240" alt="Screen Shot 2023-02-14 at 10 21 12 PM" src="https://user-images.githubusercontent.com/387249/218948960-c96833aa-3cc5-4eec-9522-33182d393eed.png"> | <img width="1240" alt="Screen Shot 2023-02-14 at 10 22 03 PM" src="https://user-images.githubusercontent.com/387249/218948964-f2982804-d16d-4aa3-972a-506942f95597.png">

**Comment by Uni-verse** [comment]
Verified on `Samsung GS 21` using version:

```
Brave	1.49.117 Chromium: 111.0.5563.50 (Official Build) (64-bit) 
Revision	39f3dfc5023fe60997adc4f6cf5439cfa3e6968a-refs/branch-heads/5563@{#903}
OS	Android 13; Build/TP1A.220624.014
```

Using Test Plan in https://github.com/brave/brave-core/pull/16790#issue-1552408963

Precondition: Brave News V2 enabled

- Ensured following some sources will create a suggestions list
- Ensured that the number of items in the suggestions is capped at 15

Example | Example
-|-
![screenshot-1677787301464](https://user-images.githubusercontent.com/17885425/222548284-2cef5cf5-b02f-4601-afd2-ea809c710c08.png) | ![screenshot-1677789749826](https://user-images.githubusercontent.com/17885425/222548291-e2668cfe-c1dd-4373-ab00-d3c8f8052914.png)
