### ISSUE TITLE
Cache requests for isTestNetworksEnabled

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#26599]
## Description 

Utilize a cache for the `isTestNetworksEnabled` variable to remove the need to constantly request this variable from core api.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.47.164 Chromium: 109.0.5414.74 (Official Build) (64-bit)
-- | --
Revision | `e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}`
OS | Linux

- Verified steps from [brave/brave-core#15835](https://github.com/brave/brave-core/pull/15835)
- Verified changing Test network settings work as expected

https://user-images.githubusercontent.com/17010094/211294634-617a1079-da42-4ee6-b73b-7d7a85e9a2ac.mp4


---------------------

Verification passed on 

Brave | 1.47.164 Chromium: 109.0.5414.74 (Official Build) (64-bit)
-- | --
Revision | `e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#15835](https://github.com/brave/brave-core/pull/15835)
- Verified changing Test network settings work as expected


https://user-images.githubusercontent.com/17010094/211294853-7a9b09ca-c61a-44bd-addb-24ac944c9dd2.mp4

---------------------

Verification passed on 

Brave | 1.47.164 Chromium: 109.0.5414.74 (Official Build) (arm64)
-- | --
Revision | `e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#15835](https://github.com/brave/brave-core/pull/15835)
- Verified changing Test network settings work as expected

https://user-images.githubusercontent.com/17010094/211295151-a9cb6bd0-1835-4272-a79c-ab3a8959924d.mov
