### ISSUE TITLE
vertical tabs wont enable

### ISSUE THREAD

**Issue by ghostlyentity** [brave/brave-browser#26595]
## Description 
The vertical tabs flag is enable but the tabs stay on top

## Steps to Reproduce
   1. enable flag "vertical tabs"
   2. restart
   3. tabs dont change

## Actual result:
vertical tabs wont enable

## Expected result:
vertical tabs should enable

## Reproduces how often: 
it happens every time

## Desktop Brave version:
brave nightly v1.45.118

![Screenshot from 2022-11-07 20-34-29](https://user-images.githubusercontent.com/86599520/200399257-e2a905ed-3dc3-4ca7-b50b-2bc92d9ad1a0.png)

**Comment by antonok-edm** [comment]
@ghostlyentity anything in `brave://flags` should be considered in an experimental state or under rapid development. In this case @simonhong has recently added an option to enable vertical tabs to be enabled _without_ a browser restart, in preparation for when the flag will eventually be removed.

For now you can re-enable vertical tabs by right-clicking on the tab bar and selecting `Use vertical tabs` after the flag has been enabled.

**Comment by ghostlyentity** [comment]
ah i see, i was clicking right between the bar and the drpdown menu before making this issue, which seems to not count, thank you for the swift reply

**Comment by simonhong** [comment]
> @ghostlyentity anything in `brave://flags` should be considered in an experimental state or under rapid development. In this case @simonhong has recently added an option to enable vertical tabs to be enabled _without_ a browser restart, in preparation for when the flag will eventually be removed.

Not me. @sangwoo108 is father of vertical tab 😄

**Comment by antonok-edm** [comment]
oops yeah, wrong tab complete 😅
