### ISSUE TITLE
User should be able to submit `Contact technical support` form with a valid email address that includes digits  

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#26600]
## Steps to Reproduce

   1. install `1.46.96`
   2. launch Brave
   3. set up a `Brave VPN` connection
   4. click on the `VPN` button in the toolbar
   5. click the `Gears` icon
   6. click on `Contact technical support`
   7. enter a valid email address with digits (for example. `test123@brave.com`) into the `Your email address` field
   8. click `Submit`

## Actual result:

Nothing happens

https://user-images.githubusercontent.com/98358127/200427419-05590c78-7963-4120-8d00-eace0ee4db83.mp4

## Expected result:
User should be able to submit the form

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.46.96 Chromium: 107.0.5304.91 (Official Build) beta (64-bit)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | Windows 11 Version 21H2 (Build 22000.1098)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@rebron @bsclifton @brave/qa-team

**Comment by bsclifton** [comment]
This should be resolved 😄 Issue was originally reported here:
https://github.com/brave/brave-browser/issues/26454

Fixed with https://github.com/brave/brave-core/pull/15747 and uplifted to 1.46 with https://github.com/brave/brave-core/pull/15760

See comment here https://github.com/brave/brave-browser/issues/26454#issuecomment-1305568280 - `1.46.97` or greater is needed to see
