### ISSUE TITLE
Sidebar's border is not rendered when it's on right-sided

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#26605]
## Steps to Reproduce

   1. Launch Brave and set sidebar visible and set on right
   2. Re-launch and load https://yaronschoen.com/ for getting white background
   3. Check sidebar's border is not rendered

## Actual result:

<img width="68" alt="image" src="https://user-images.githubusercontent.com/6786187/200448320-0207eeee-e706-47c5-ba2b-684158a6efea.png">

## Expected result:
<img width="60" alt="image" src="https://user-images.githubusercontent.com/6786187/200448510-26acdefd-348a-477d-ba91-4e9961536f26.png">

## Reproduces how often: 

Easy

## Brave version (brave://version info)

`1.47.52`

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

This issue is gone when toggled sidebar left/right option. but happens again after relaunch

**Comment by kjozwiak** [comment]
The above requires `1.46.102` or higher for `1.46.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.46.104 Chromium: 107.0.5304.110 (Official Build) beta (x86_64)
-- | --
Revision | 2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}
OS | macOS Version 12.6.1 (Build 21G217)
```
