### ISSUE TITLE
Cache requests for `selectedCoin` in panel

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#26603]
## Description 

Utilize a cache for the `selectedCoin` variable to remove the need to constantly request this variable from core api while using the wallet panel UI.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.47.164 Chromium: 109.0.5414.74 (Official Build) (64-bit)
-- | --
Revision | `e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}`
OS | Linux

- Verified steps from [brave/brave-core#15836](https://github.com/brave/brave-core/pull/15836)
- Verified `Connected / Disconnected` and `Site Permissions` in panel work as expected

---------------------

Verification passed on 

Brave | 1.47.164 Chromium: 109.0.5414.74 (Official Build) (64-bit)
-- | --
Revision | `e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#15836](https://github.com/brave/brave-core/pull/15836)
- Verified `Connected / Disconnected` and `Site Permissions` in panel work as expected

---------------------

Verification passed on 

Brave | 1.47.164 Chromium: 109.0.5414.74 (Official Build) (arm64)
-- | --
Revision | `e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#15836](https://github.com/brave/brave-core/pull/15836)
- Verified `Connected / Disconnected` and `Site Permissions` in panel work as expected
