### ISSUE TITLE
VPN subscriber credential is not refreshed on startup till panel is opened

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#26607]
## Description 

Subscriber credential is refreshed during the runtime when when it's expired.
If it's expired while browser isn't used, it's not refreshed on startup till panel is opened

## Steps to Reproduce

   1.  Make purchased state and shutdown
   2. Wait till cached credential is expired and relaunch
   3. Open vpn panel after some minutes passed

## Actual result:

User can see vpn panel has spinning

## Expected result:
User could see vpn panel spinning if panel is opened right after startup.
But, could see main panel w/o spinning if opened after some times passed

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.46.103` or higher for `1.46.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.46.129 Chromium: 108.0.5359.48 (Official Build) (64-bit)
-- | --
Revision | 18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}
OS | Windows 11 Version 21H2 (Build 22000.1219)
```

1. installed 1.46.129
2. launched Brave
3. opened `brave://flags`
4. set `brave://flags#brave-vpn` to Enabled
5. relaunched Brave
6. loaded `account.bravesoftware.com`
7. entered username/password from 1PW
8. entered `test28-nov28@mailinator.com`, clicked Get login link
9. clicked the link in the email
10. clicked `Browse plans`
11. scrolled down
12. clicked on` Buy now` for Brave VPN Subscription
13. completed the Stripe purchase flow
14. confirmed I could connect to the VPN
15. closed Brave browser
16. disconnected from the BraveVPN connection in `VPN` settings in the `Windows settings`>>`Network&internet`
17. opened `Local State` from my user profile
18. edited the value for `brave.brave_vpn.subscriber_credential.expiration`, from `13312583928000000` to `133125839280000` by deleting the last 2 `0` numbers
19. relaunched Brave
20. confirmed able to connect to VPN 


step 4|step 10|step 14|step 16|step 17|step 18|step 20
------|------|--------|------|---------|-------|-------
<image width="750" alt="image" src="https://user-images.githubusercontent.com/98358127/204400019-3b2fb0ec-fd27-4f06-b8be-7ae5291ee4ca.png">|<image width="750" alt="image" src="https://user-images.githubusercontent.com/98358127/204400280-214faddf-95d1-442f-abc4-070d05260980.png">|<image width="750" alt="image" src="https://user-images.githubusercontent.com/98358127/204400456-d80e319e-2caf-4bf4-bfe4-79bb49c4fb0f.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/204400785-c60bdb4d-6b55-43e1-af36-6093923ba994.png">|<image width="1250" alt="image" src="https://user-images.githubusercontent.com/98358127/204400905-c5036db0-ccfd-4972-974f-fee492682cb9.png">|<image width="1250" alt="image" src="https://user-images.githubusercontent.com/98358127/204400953-67614ad1-b7e3-4f3f-a1b5-2399046c67d4.png">|<image width="1250" alt="image" src="https://user-images.githubusercontent.com/98358127/204401268-7fdd81b8-1d6e-4b4f-9106-d7d87018ad91.png">

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.46.129 Chromium: 108.0.5359.48 (Official Build) (x86_64)
-- | --
Revision | 18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}
OS | macOS Version 11.7.1 (Build 20G918)

### Steps:

1. installed 1.46.129
2. launched Brave
3. opened brave://flags
4. set brave://flags#brave-vpn to Enabled
5. relaunched Brave
6. loaded account.bravesoftware.com
7. entered username/password from 1PW
8. entered test28-nov28@mailinator.com, clicked Get login link
9. clicked the link in the email
10. clicked Browse plans
11. scrolled down
12. clicked on Buy now for Brave VPN Subscription
13. completed the Stripe purchase flow
14. confirmed I could connect to the VPN
15. closed Brave browser
16. disconnected from the BraveVPN connection in VPN settings in the Windows settings>>Network&internet
17. opened Local State from my user profile
18. edited the value for brave.brave_vpn.subscriber_credential.expiration, from `1331420629200000000` to `13314206292000000` by deleting the last 2 `0` digits
19. relaunched Brave
20. confirmed able to connect to VPN

example | example | example | example | example | example
---------|---------|----------|---------|----------|----------
<img width="1356" alt="Screen Shot 2022-11-29 at 12 22 57 AM" src="https://user-images.githubusercontent.com/387249/204478657-1ad7f82f-3bcf-4aba-8853-20defddac608.png"> | <img width="780" alt="Screen Shot 2022-11-29 at 12 23 27 AM" src="https://user-images.githubusercontent.com/387249/204478673-11587e03-39aa-44f8-b915-b0bc509b5f1c.png"> | <img width="780" alt="Screen Shot 2022-11-29 at 12 23 35 AM" src="https://user-images.githubusercontent.com/387249/204478675-3ee8c518-84d5-43f2-a06e-9032412bfb20.png"> | <img width="1481" alt="Screen Shot 2022-11-29 at 12 26 51 AM" src="https://user-images.githubusercontent.com/387249/204478682-c438a86f-d1f3-4ebf-a1c8-54e0280e6ff4.png"> | <img width="1419" alt="Screen Shot 2022-11-29 at 12 28 39 AM" src="https://user-images.githubusercontent.com/387249/204478698-280e3f66-2ea4-4291-956e-a31e9cdcd9d4.png"> | <img width="1419" alt="Screen Shot 2022-11-29 at 12 28 44 AM" src="https://user-images.githubusercontent.com/387249/204478701-f819dc9d-fafe-4297-b94c-ad4b071e7f7b.png">
