### ISSUE TITLE
Add P3A metric for desktop browser menu usage

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#26602]
Add P3A metric to query browser menu usage.

What menu functionality group do you use the most?
`Brave.Toolbar.FrequentMenuGroup`

0. Tab & window actions (new tab/new window)
1. Brave features (Wallet, Rewards, Sync)
2. Browser views (History, Bookmarks, Extensions, Settings)

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.49.90 Chromium: 110.0.5481.77 (Official Build) beta (64-bit)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | Windows 10 Version 21H2 (Build 19044.2486)
```

**Comment by GeetaSarvadnya** [comment]
@DJAndries: when I mix all the 3 groups or two groups together I am getting the response of lastely used group even though the amount of accesses NOT exceeds the amount in 1st group.

Could you review the scenarios and let me know your thoughts?

Reg the group 1 Brave features (Wallet, Rewards, Sync))

- If I access the Brave rewards or wallet, I get the metrics response as `0` ?
- If I access the sync then I get the metrics response as `1` 
Q - When we say access, does it mean create rewards or wallet or sync chain? If so, the response should be same when we access each feature, if I just access sync I get response as `1` but if I access rewards/wallet I get the response as `0` why is this difference?

when I mix all the 3 groups or two groups together I am getting the response of lastely used group even though the amount of accesses NOT exceeds the amount in 1st group.

**Scenario 1:** 

1. Clean profile 1.49.x
2. Open few a Tab, a new windows, a TOR window, a PT window and a Guest windows via 3 dot menu option
3. Open brave://local-state file
4. The metrics `Brave.Toolbar.FrequentMenuGroup` response value is `0` as expected
5. Open Bookmarks, History and Extension from 3 dot menu option
6. The metrics `Brave.Toolbar.FrequentMenuGroup` response value is `2` 

**Scenario 2:**
1. Clean profile 1.49.x
2. Open a new Tab and a new windows via 3 dot menu option
3. Open brave://local-state file
4. The metrics `Brave.Toolbar.FrequentMenuGroup` response value is `0` as expected
5. Open Bookmarks from 3 dot menu option
6. The metrics `Brave.Toolbar.FrequentMenuGroup` response value is `2`

**Comment by DJAndries** [comment]
> If I access the sync then I get the metrics response as 1
Q - When we say access, does it mean create rewards or wallet or sync chain? If so, the response should be same when we access each feature, if I just access sync I get response as 1 but if I access rewards/wallet I get the response as 0 why is this difference?

How are you accessing Rewards + Wallet? Is it via the "three dot" menu? I'm not able to reproduce this when using the menu. Sync, Rewards and Wallet get counted as Brave features.

> when I mix all the 3 groups or two groups together I am getting the response of lastely used group even though the amount of accesses NOT exceeds the amount in 1st group.

If the max count between two or more groups is equal, consider the expected selected group (between the groups with the equal max count) to be undefined. It is correct if the value is any one of the groups with the max count.

**Comment by GeetaSarvadnya** [comment]
@DJAndries Please find the steps for the case 2 under `Two groups menus are accessed together` section. In this case I have opened the `Browser views` 1. History, 2. Bookmarks, 3. Extensions, 4. Settings one by one via 3 dot toolbar menu after that I have opened 1. Tab, 2. window, 3. PT window, 4. PT TOR window and 5. Guest window via 3 dot toolbar menu, after this I am getting the response as `2` instead of `0`

**Comment by DJAndries** [comment]
@GeetaSarvadnya Looks like a problem, raised #28525. Thanks!

**Comment by GeetaSarvadnya** [comment]
Thanks @DJAndries !
