### ISSUE TITLE
Confirmation Improvements to be supported on Uniswap and associated products

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#26613]
## Description 

Brave Wallet should support the new UX we have for confirmations on Dapps, like Matcha, on Uniswap. @onyb to fill in what other dapps this work will also cover. 

## Steps to Reproduce

   1. 
   2. 
   3. 

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by HEagle18** [comment]
This work may not be needed if we get simulations in soon.. cc @onyb

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.70.107 Chromium: 128.0.6613.120 (Official Build) beta (64-bit)
-- | --
Revision | ab3f504ca4a15c330f60a93d5e3773d780498980
OS | Windows 11 Version 23H2 (Build 22631.4112)

- Verified steps from [brave/brave-core#21796](https://github.com/brave/brave-core/pull/21796)
- Verified `brave://flags/#brave-wallet-enable-transaction-simulations` is set to disabled by default
- Verified enabling the flag enables the `See the results of transactions before you sign.` setting and sets to `Ask` as default
- Verified when submitting a native ETH transaction safe sign is shown and no simulation is shown
- Verified when submitting an ERC20 send simulation transaction optin message is shown when set to `Ask`
- Verified selecting `Enable` sets the setting to `Yes`
- Verified selecting `No thanks` sets the setting to `No`
- Verified when there are multiple transaction in queue, cycle through the transactions loads the correct simulation

Scenario 1 (Enable) | Secanrio 1 (Disable) | Scenario 2
-- | -- | --
<video src=https://github.com/user-attachments/assets/6dfd3fb0-f06b-4504-ab59-8e66d896fb8d> | <video src=https://github.com/user-attachments/assets/b867bb76-83d9-456a-bafd-d0383345f0f4> | <video src=https://github.com/user-attachments/assets/c579b912-a61e-44d4-94f9-d41d3f125e86>
