### ISSUE TITLE
`On mouseover` option doesn't work when it's on right-sided in some condition

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#26612]
## Steps to Reproduce

1. Launch Brave and set sidebar visible and set on right
2. Re-launch and change sidebar option to `On mouseover`
3. Move around right side to make sidebar visible

## Actual result:

Sidebar is not shown

## Expected result:
Sidebar should be shown

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

This issue is gone when toggled sidebar left/right option. but happens again after relaunch

**Comment by kjozwiak** [comment]
The above requires `1.46.102` or higher for `1.46.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.46.104 Chromium: 107.0.5304.110 (Official Build) beta (x86_64)
-- | --
Revision | 2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}
OS | macOS Version 12.6.1 (Build 21G217)
```
