### ISSUE TITLE
Windows Group Policy Template zip is too large

### ISSUE THREAD

**Issue by mherrmann** [brave/brave-browser#26611]
Brave's `policy_templates.zip` file, which was introduced in #26501, is unnecessarily large. It is 40 MB when it could be 4 MB. The goal of this issue is to fix this. This was noticed by @goodov [here](https://github.com/brave/brave-core/pull/15440#pullrequestreview-1171606454).

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.47.123 Chromium: 108.0.5359.99 (Official Build) beta (64-bit)
-- | --
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | Windows 11 Version 21H2 (Build 22000.1219)
```

1. Install 1.47.121
2. launch Brave
3. open https://github.com/brave/brave-browser/releases/tag/v1.47.125
4. click to download `policy_templates.zip file
5. go to downloads

#### Confirmed the file is < 5MB (4,142 KB)

<img width="608" alt="image" src="https://user-images.githubusercontent.com/98358127/207148038-43532a83-fb52-4d12-bfcf-9f885d130e7f.png">
