### ISSUE TITLE
Basic Solana NFT support on Android

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#26617]
A full description is here https://github.com/brave/brave-browser/issues/25864#issuecomment-1297575252

**Comment by kjozwiak** [comment]
The above will require `1.45.124` or higher for `1.45.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.45.125 x64 build
- Verified steps from [brave/brave-core#15849](https://github.com/brave/brave-core/pull/15849)
- Verified able to add Solana NFT via add custom token 
- Verified selecting `NFT` checkbox automatically hides the decimal value input and adds NFT
- Verified NFT is listed in portofolio automatically
- Verified correct NFT value is shown when account is switched 
- Send NFT will be checked as part of [#26694](https://github.com/brave/brave-browser/issues/26694)

Oppo Reno 5 (Android 12) | Samsung Tab A (Android 10)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/201736524-edc607d9-4278-4d78-be31-c2c3f79d6a7a.mp4> | <video src=https://user-images.githubusercontent.com/17010094/201737507-77a64829-ee45-429b-87d1-df61f75d4399.mp4>
