### ISSUE TITLE
Brave News Desktop: Following or unfollowing sources and channels should trigger an update banner

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#26631]
When channels or sources follows are changed in Customize, we should call the redux action `checkForUpdate` similar to how this happens in the redux `setPublisherPref` action. 

_note: That happens in a less than ideal manner since it waits for 3 seconds after making changes, hoping that the backend has re-fetches and re-built the feed in that time. Ideally we should have an event mechanism through a new mojom interface. We don't neccessarily need to improve that for this issue fix._

## Steps
- Open Customize
- Follow a new channel
- Close Customize
- Actual: No "reload content" button pill is available
- Expected: A "reload content" button pill is shown

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.48.118 Chromium: 109.0.5414.80 (Official Build) beta (x86_64)
-- | --
Revision | 0f69b168d36a06cace4365e9f029fa987afa5633-refs/branch-heads/5414@{#1178}
OS | macOS Version 11.7.2 (Build 20G1020)

### Steps:
1. installed 1.48.118
2. launched Brave
3. opened a new-tab page
4. opted in to Brave News
5. clicked on `Customize`
6. unfollowed `Top News`
7. followed `Cars`
8. waited
9. confirmed I saw `Load new content`
10. clicked on the button
11. confirmed I saw content from `The Drive` subbed in

example | example | example
---------|----------|---------
<img width="1312" alt="Screen Shot 2023-01-09 at 4 22 11 PM" src="https://user-images.githubusercontent.com/387249/211434909-1842bb67-52cd-4331-9ab1-ddc3e2480b17.png"> | <img width="1312" alt="Screen Shot 2023-01-09 at 4 22 16 PM" src="https://user-images.githubusercontent.com/387249/211434937-c5015df2-68ce-48b4-8ca6-cf1971007405.png"> | <img width="1312" alt="Screen Shot 2023-01-09 at 4 22 22 PM" src="https://user-images.githubusercontent.com/387249/211434956-bb9fc2c6-3a1e-48ea-8d1b-168831d44473.png">
