### ISSUE TITLE
Integrate Swap V2 in brave-core

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#26632]
Issue to track integration of https://github.com/brave/swap into brave-core.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.48.141 Chromium: 109.0.5414.119 (Official Build) beta (64-bit)
-- | --
Revision | `772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified test plan from [brave/brave-core#15762](https://github.com/brave/brave-core/pull/15762)
- Verified selecting network updates the background gradient colour to match the network icon colour
- Verified able to select from and to tokens and quote is updated automatically when a value is entered
- Verified able to switch from and to tokens 
- Verified selecting a token updates the quotes regularly
- Verified once quote is updated a comparison message with CoinGecko is shown similar to `1.06% more expensive than CoinGecko` or  `Within 0.94% CoinGecko`
- Verified Liquidity provider is shown for each token
- Verified Liquidity provider is updated based on the Swap To token selection
- Verified for SOL/SPL tokens different provider is shown which user can select
- Verified for SOL/SPL tokens Brave fee is set to `Free`
- Verified Brave fee is only applicable for ETH/ERC20 tokens
- Verified clicking on Privacy Policy brings up modal which give info about both 0x and Jupiter
- Verified clicking on 0x in Privacy Policy modal  loads `https://www.0x.org/` 
- Verified clicking on 0x Privacy Policy modal loads `https://www.0x.org/privacy`
- Verified clicking on Jupiter on Privacy Policy modal loads `https://jup.ag/`
- Verified clicking on Jupiter Privacy Policy on Privacy Policy modal loads `https://docs.jup.ag/legal/privacy-policy`
- Verified able to successfully submit a swap transaction
- Verified clicking on the swap button in panel opens `brave://wallet/swap` in a new tab
- Encountered [#28140](https://github.com/brave/brave-browser/issues/28140),[#28137](https://github.com/brave/brave-browser/issues/28137), [#28063](https://github.com/brave/brave-browser/issues/28063)

https://user-images.githubusercontent.com/17010094/215550703-92fbe6ea-e515-4ac8-a2b3-e06023666d83.mp4
