### ISSUE TITLE
Confusing UX on Brave Wallet Onboarding

### ISSUE THREAD

**Issue by ianrandmckenzie** [brave/brave-browser#26638]
## Description 
On the page prompting the user to connect their wallet, there is a link that says, "Learn more about Brave Wallet"
brave://wallet/crypto/onboarding/welcome

When clicking the link, it takes you here:
https://brave.com/web3/what-is-crypto-wallet/

This article describes crypto wallets, but says nothing about Brave Wallet itself. For people that are already familiar with what crypto wallets are, it creates a frustrating disconnect in that they are likely wanting to know about the Brave Wallet, not crypto wallets, as the link text would suggest.

## Steps to Reproduce

   1. Go to any website that has MetaMask integration and click a login with MetaMask link
   2. A new tab opens brave://wallet/crypto/onboarding/welcome
   3. Click the "Learn more about Brave Wallet" link at the bottom with the assumption that you are learning about Brave Wallet, not crypto wallets.

## Actual result:
An article about crypto wallets.

## Expected result:
An article about Brave Wallet.

## Reproduces how often: 
100%

## Brave version (brave://version info)
1.45.118 Chromium: 107.0.5304.91 (Official Build) (arm64) 

## Version/Channel Information:
I'm sorry, I don't know what channels are.

## Other Additional Information:
At the end of an article, there is a link that says "Get started with Brave Wallet" that does in fact give more information about Brave Wallet. However, I don't want to get started until I know what it is and as a result never clicked that link until this issue prompted me to address the issue like a QA tester/debugger rather than a consumer.

## Miscellaneous Information:
n/a

**Comment by diracdeltas** [comment]
cc @jamesmudgett

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta  (64-bit) 
-- | --
Revision | `46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}`
OS | Linux

- Verified steps from [brave/brave-core#16644](https://github.com/brave/brave-core/pull/16644)
- Verified clicking on `Learn more about Brave Wallet` opens help centre link (`https://support.brave.com/hc/en-us/categories/360001059151-Brave-Wallet`)  in a new tab

https://user-images.githubusercontent.com/17010094/221795734-2bf212a7-1986-4203-a8e7-c99a19b032ca.mp4


---------------------

Verification passed on 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta  (64-bit)
-- | --
Revision | `46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#16644](https://github.com/brave/brave-core/pull/16644)
- Verified clicking on `Learn more about Brave Wallet` opens help centre link (`https://support.brave.com/hc/en-us/categories/360001059151-Brave-Wallet`)  in a new tab

https://user-images.githubusercontent.com/17010094/221795537-b65cc1ba-dac9-4f39-8aaf-8f4e5adcb90d.mp4

---------------------

Verification passed on 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta  (arm64)
-- | --
Revision | `46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#16644](https://github.com/brave/brave-core/pull/16644)
- Verified clicking on `Learn more about Brave Wallet` opens help centre link (`https://support.brave.com/hc/en-us/categories/360001059151-Brave-Wallet`)  in a new tab

https://user-images.githubusercontent.com/17010094/221795919-ba057a71-3096-4acb-b3d3-1d7185341043.mov
