### ISSUE TITLE
Unable reset Brave's wallet when language is not in English

### ISSUE THREAD

**Issue by rardcode** [brave/brave-browser#26640]
## Description 
Unable reset Brave's wallet when Brave is in ITALIAN language

## Steps to Reproduce

   1. go to three bar in top right, settings, wallet
   2. click on "Reset Brave's wallet"
   3. Insert "Yes"

## Actual result:
Nothing

## Expected result:
Reset Brave's wallet

## Reproduces how often: 
Every

## Brave version (brave://version info)
v1.45.118

**Comment by srirambv** [comment]
What platform are you seeing behaviour ?

**Comment by rardcode** [comment]
Linux Manjaro, desktop  KDE, kernel 6.0.7

**Comment by srirambv** [comment]
Does console throw any errors? I can't repro it on Windows/Debian

**Comment by rardcode** [comment]
In console this error:
https://i.imgur.com/xueF1dB.png
UPDATE: i've tested in other pc Windows 10 and even in that pc same problem!
INFO: i've Brave sync enable between two pc, i've tryed to disable it thinking sync caused the problem but no.

**Comment by GeetaSarvadnya** [comment]
The issue is not reproducible in `1.45.118`, `1.45.121` and `1.46.99`

**Comment by rardcode** [comment]
i've find problem: the language!

i've set English language, restarted Brave.. step 1,2,3 and wallet successfully resetted!!!

i've update ISSUE Description adding ITALIAN LANGUAGE

**Comment by vadimstruts** [comment]
Hello @rardcode 

I just tried to figure out the problem and want to mention that in case of Italian language, Brave expects the confirmation phrase `Sì`.  As you can see the letter `ì` (diacritics) is not equal `i`.
Could you please use it, and verify yet one time?
