### ISSUE TITLE
[Android] Top tile icons cut off in quick action widget 

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#26645]
## Description 
The top tile icons get cut off when the quick actions widget size is reduce.

## Steps to reproduce 

   1. Make sure you have the top tiles populated with browsing history. e.g. visit a few sites.
   2. Add the quick actions widget to the home screen (settings -> general -> home screen widget)
   3. Restart Brave Nightly.
   4. Expand then reduce the size of the widget to it's smallest state.

## Actual result 
Half of the top tile icons are cut off.

## Expected result
Top tile icons are not cut off.

## Issue reproduces how often
Easily reproduced

## Version/Channel Information:
Nightly 

## Device details
   - Install type: ARM
   - Device type: Phone
   - Android version: 12
   
## Brave version
Brave 1.47.55 / Chromium 107.0.5304.91 

### Additional information

https://user-images.githubusercontent.com/28269287/200889071-abc12709-7351-457b-b5b8-a6861b29f614.mp4

**Comment by kjozwiak** [comment]
The above requires `1.47.179` or higher for `1.47.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version: 

```
Brave	1.47.181 Chromium: 109.0.5414.87 (Official Build) (64-bit) 
Revision	2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS	Android 13; Build/TP1A.220624.014
```
Using STR in https://github.com/brave/brave-browser/issues/26645#issue-1442414539

- Verified that reducing size of the widget to 1 row will not cut off the top tiles.
- Verified top tiles on quick action widget are working properly

https://user-images.githubusercontent.com/17885425/214092394-006cc768-08ab-4d61-a05d-54c3184f87e9.mp4
