### ISSUE TITLE
Allow `selectedAccount` to be `undefined`

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#26647]
## Description 

Currently, when initializing the Redux state, we populate `selectedAccount` an empty object that is casted to the `WalletAccountType` type. See code: https://github.com/brave/brave-core/blob/d16bacac881246605459178e13f82b90c6471def/components/brave_wallet_ui/common/slices/wallet.slice.ts#L80

To avoid program errors, allow the type to accept `undefined` as a value, so that app logic can correctly identify the need to check for the existence of a proper account object before accessing properties from the object.

This issue is about changing its type to `WalletAccountType | undefined` and refactoring the whole codebase to work with this new type.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.47.164 Chromium: 109.0.5414.74 (Official Build) (64-bit)
-- | --
Revision | `e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}`
OS | Linux

- Verified steps from [brave/brave-core#15868](https://github.com/brave/brave-core/pull/15868)
- Verified wallet functionality works as expected

---------------------

Verification passed on 

Brave | 1.47.164 Chromium: 109.0.5414.74 (Official Build) (64-bit)
-- | --
Revision | `e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#15868](https://github.com/brave/brave-core/pull/15868)
- Verified wallet functionality works as expected

---------------------

Verification passed on 

Brave | 1.47.164 Chromium: 109.0.5414.74 (Official Build) (arm64)
-- | --
Revision | `e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#15868](https://github.com/brave/brave-core/pull/15868)
- Verified wallet functionality works as expected
