### ISSUE TITLE
Added NFT doesn't show the corresponding NFT number

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#26657]
## Description 
Added NFT doesn't show the corresponding NFT number

## Steps to reproduce 

   1. Add a Solana NFT via add custom asset
   2. Search for the NFT, shows in the list but has value `#0`
   3. Wait for the token to be shown in portfolio, shows value as 1 but the NFT number is still shown as `#0`

## Actual result 

![image](https://user-images.githubusercontent.com/17010094/201018604-28e579fd-5999-4271-9bb0-078823826c55.png) | ![image](https://user-images.githubusercontent.com/17010094/201018639-bb201f59-97f3-4273-90f2-981f953e5486.png) | ![image](https://user-images.githubusercontent.com/17010094/201018651-eb30da96-a8bc-4d87-a5a6-9a199a94cf62.png)
-- | -- | --

## Expected result
Should show the correct NFT number 

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 12
   
## Brave version
1.47.60

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @SergeyZhukovsky @Pavneet-Sing @yrliou

**Comment by yrliou** [comment]
There is no "number" (token ID) for Solana NFT. We probably shouldn't show it on UI. cc @SergeyZhukovsky

**Comment by kjozwiak** [comment]
The above requires `1.45.124` or higher for `1.45.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 145.125 x64 build
- Verified NFT shows proper NFT number 

![image](https://user-images.githubusercontent.com/17010094/201735516-673c34fa-9d56-4ae0-995d-a45400aa34d0.png) | ![image](https://user-images.githubusercontent.com/17010094/201735508-5f95196c-2a17-4fb4-8197-cc92fd52dd9c.png) | ![image](https://user-images.githubusercontent.com/17010094/201735563-289a582f-9298-4663-865f-5dc8c33879e4.png)
-- | -- | --


--------------
Verification passed on Samsung Tab  A with Android 10 running 145.125 x64 build
- Verified NFT shows proper NFT number 

![image](https://user-images.githubusercontent.com/17010094/201735615-d398c076-5e5d-4a01-b646-95eadf6958e9.png) | ![image](https://user-images.githubusercontent.com/17010094/201735603-0acda609-4c01-472c-b65e-8f2f9038f01c.png) | ![image](https://user-images.githubusercontent.com/17010094/201735642-230d7d61-9d6d-48ed-a2cc-0c6e2384a180.png)
-- | -- | --
