### ISSUE TITLE
ENS, SNS, UD should use hardcoded endpoints for resolution.

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#26654]
We provide such resolution as a service and should not depend on custom RPC endpoints

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.48.151 Chromium: 109.0.5414.119 (Official Build) beta (arm64)
-- | --
Revision | `772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}`
OS | macOS Version 13.0 (Build 22A380)

- Verified Wallet and omnibox resolution for SNS, ENS and UD are using Brave RPC endpoints where applicable
