### ISSUE TITLE
NFT send should not list preset percentage values

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#26658]
## Description 
NFT send should not list preset percentage values

## Steps to reproduce 

   1. Add a Solana NFT
   2. Select NFT and click Send
   3. Send options are still shown with default preset values

## Actual result 
<img width=300 src=https://user-images.githubusercontent.com/17010094/201019980-fb0cf6d3-3088-4b04-bb07-95e5bd1fa48a.png>

## Expected result
<img width=300 srchttps://user-images.githubusercontent.com/17010094/201020029-3499aac3-4dd0-4ad9-87ee-a4e0a775c4d1.png>

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version:12
   
## Brave version

1.47.60 x64 Nightly build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @SergeyZhukovsky @wchen342 @Pavneet-Sing

**Comment by kjozwiak** [comment]
The above requires `1.45.124` or higher for `1.45.x` verification 👍
