### ISSUE TITLE
Integrate SNS into Brave wallet to allow users navigate to .sol domains

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#26652]
Complete the native resolution of SNS records inside Brave’s browser
github doc: https://github.com/Bonfida/name-resolver

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.47.164 Chromium: 109.0.5414.74 (Official Build) (64-bit)
-- | --
Revision | `e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}`
OS | Linux

- Verified steps from [brave/brave-core#15863](https://github.com/brave/brave-core/pull/15863)
- Verified navigating to a `.sol` domain shows interstitial page the first time
- Verified clicking on `Proceed using Coinbase Cloud server` auto redirects the page to the correct resolving domain

https://user-images.githubusercontent.com/17010094/210785922-c9051b00-26b6-463c-8c9d-8819c956ba38.mp4

---------------------

Verification passed on 

Brave | 1.47.164 Chromium: 109.0.5414.74 (Official Build) (64-bit)
-- | --
Revision | `e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#15863](https://github.com/brave/brave-core/pull/15863)
- Verified navigating to a `.sol` domain shows interstitial page the first time
- Verified clicking on `Proceed using Coinbase Cloud server` auto redirects the page to the correct resolving domain

https://user-images.githubusercontent.com/17010094/210785988-93c81287-6b15-4831-afef-30f7628ab764.mp4

---------------------

Verification passed on 

Brave | 1.47.164 Chromium: 109.0.5414.74 (Official Build) (arm64)
-- | --
Revision | `e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#15863](https://github.com/brave/brave-core/pull/15863)
- Verified navigating to a `.sol` domain shows interstitial page the first time
- Verified clicking on `Proceed using Coinbase Cloud server` auto redirects the page to the correct resolving domain

https://user-images.githubusercontent.com/17010094/210786381-a6cb5dda-d3b7-4505-be4b-cddd189e2af2.mov
