### ISSUE TITLE
All Solana transactions showing token contract address error

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#26656]
## Description 

All Solana transactions are showing `token contract address` errors

https://user-images.githubusercontent.com/40611140/201017997-25910306-8894-4988-a95d-ec3d7e1d8676.mov

## Steps to Reproduce

   1. Create any transaction on the `Solana` network
   2. It will show a `token contract address` error every time.

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.47.126 Chromium: 108.0.5359.99 (Official Build) beta (64-bit)
-- | --
Revision | `410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}`
OS | Linux

- Verified steps from [brave/brave-core#15882](https://github.com/brave/brave-core/pull/15882)
- Verified no error when trying to send Solana transactions
- Verified error is only shown when an actual contract address is entered

https://user-images.githubusercontent.com/17010094/207544941-50282946-945e-4790-9bcc-2cdd28b0894f.mp4

---------------------

Verification passed on 

Brave | 1.47.126 Chromium: 108.0.5359.99 (Official Build) beta (64-bit)
-- | --
Revision | `410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#15882](https://github.com/brave/brave-core/pull/15882)
- Verified no error when trying to send Solana transactions
- Verified error is only shown when an actual contract address is entered

https://user-images.githubusercontent.com/17010094/207545001-ad3e7c04-b397-40b2-88b8-b0f3b10b1b0e.mp4

---------------------

Verification passed on 

Brave | 1.47.126 Chromium: 108.0.5359.99 (Official Build) beta (arm64)
-- | --
Revision | `410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#15882](https://github.com/brave/brave-core/pull/15882)
- Verified no error when trying to send Solana transactions
- Verified error is only shown when an actual contract address is entered

https://user-images.githubusercontent.com/17010094/207545317-c58950d5-45cc-43e0-8a15-548a31f4beee.mov
