### ISSUE TITLE
Solana NFT shows preset values on Send screen

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#26666]
## Description 

Solana NFT shows preset values on Send screen

## Steps to Reproduce

   1. Add Solana NFT to wallet
   2. Select NFT from token list in Send tab
   3. Preset values are shown instead of just listing the NFT similar to Ethereum NFT's

## Actual result:

https://user-images.githubusercontent.com/17010094/201117396-b096311e-dbc2-463f-8e47-325b5f46b56e.mp4

## Expected result:
Should be similar to how Ethereum NFT's are shown in send tab

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.47.61 Chromium: 107.0.5304.110 (Official Build) nightly (64-bit)
-- | --
Revision | `2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @muliswilliam @yrliou

**Comment by yrliou** [comment]
Fixed by https://github.com/brave/brave-core/pull/15883.

**Comment by kjozwiak** [comment]
The above requires `1.45.125` or higher for `1.45.x` verification 👍

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/26667#issuecomment-1315130435
