### ISSUE TITLE
Websites ask to disable adblocker

### ISSUE THREAD

**Issue by johnconner122** [brave/brave-browser#26668]
## Steps to reproduce 

   1. open brave android
   2. go to settings->Brave Shields & Privacy->Use Secure DNS
   3. Change secure dns to `https://dns.adguard.com/dns-query`
   4. open https://www.rockmods.net/
   5. Website will ask to disable adblocker

## Actual result 
Website Detects adblocker

## Expected result
Website should'nt Detect adblocker

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by ryanbr** [comment]
Fix will go out in the next 24hrs, Seperately this will be resolved when `redirect` rule is supported.
