### ISSUE TITLE
[Android] Unknown error when selecting geo region during rewards onboarding

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#26662]
## Description 
Unknown error when selecting geo region during rewards onboarding

## Steps to reproduce 

   1. Enable rewards staging flag (happened in prod as well)
   2. Click Rewards panel to start onboarding
   3. Select your geo when prompted
   4. Click continue, throws error
   5. Close and reopen panel, error is dismissed and grant prompt is shown

## Actual result 
<img width=300 src=https://user-images.githubusercontent.com/17010094/201065464-47d2cc3e-d458-4535-bd77-79c63481a760.png>

## Expected result
Should not throw any error

## Issue reproduces how often 
Happened once on upgrade profile wasn't able to reproduce it on a clean install

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes 
- Can you reproduce this issue with the current Play Store Nightly version? Not checked

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 12
   
## Brave version
1.46.96

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @deeppandya @brave/rewards-client @brave/legacy_qa

**Comment by GeetaSarvadnya** [comment]
Issue is NOT reproducible in `Vivo X70 Pro version 12` running `Bravemonoarm.apk_1.45.99`

**Comment by GeetaSarvadnya** [comment]
The issue is reproduced once while testing the https://github.com/brave/brave-browser/issues/24543. Steps which I followed are as below:

1. Clean profile 1.46.99
2. Enable rewards
3. Selec the geo as `Germany` from the select country dropdown
4. I am getting the error which @srirambv mentioned above

**Comment by LaurenWags** [comment]
@GeetaSarvadnya  do you have any logs? Would be good to know what we're getting back from the server.

**Comment by deeppandya** [comment]
@LaurenWags @GeetaSarvadnya i think it's worth verifying the same issue on desktop as well. We use the similar validation on both platform.

**Comment by GeetaSarvadnya** [comment]
@deeppandya Tried the issue couple of times on Desktop. Issue is not reproducible in `Windows 10 x64  - 1.46.99`

**Comment by GeetaSarvadnya** [comment]
@deeppandya Logs are sent via DM

**Comment by Miyayes** [comment]
Intermittency: 40% per Geeta

**Comment by Miyayes** [comment]
>2022-11-30 14:17:01.625 26107-26107/? V/chromium: [VERBOSE6:logging_util.cc(134)] 
    [ RESPONSE - OnResponse ]
    > Url: **************************************************
    > Result: Failure
    > HTTP Code: 409
    > Body: {"message":"error creating rewards wallet: rewards wallet already exists","code":409}
2022-11-30 14:17:01.628 26107-26107/? I/chromium: [INFO😛ost_wallets.cc(57)] Wallet already exists!
2022-11-30 14:17:01.629 26107-26107/? I/chromium: [INFO:wallet_create.cc(103)] Failed to create Rewards wallet!
