### ISSUE TITLE
Supply wallet password with command line for dev builds

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#26663]
For example running browser with `--dev-wallet-password="my_dummy_password"` unlocks wallet on startup

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.47.164 Chromium: 109.0.5414.74 (Official Build) (64-bit)
-- | --
Revision | `e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}`
OS | Linux

- Verified steps from [brave/brave-core#15879](https://github.com/brave/brave-core/pull/15879)
- Verified passing `--dev-wallet-password="my_dummy_password"` for release build doesn't unlock the wallet on start-up

---------------------

Verification passed on 

Brave | 1.47.164 Chromium: 109.0.5414.74 (Official Build) (64-bit)
-- | --
Revision | `e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#15879](https://github.com/brave/brave-core/pull/15879)
- Verified passing `--dev-wallet-password="my_dummy_password"` for release build doesn't unlock the wallet on start-up

---------------------

Verification passed on 

Brave | 1.47.164 Chromium: 109.0.5414.74 (Official Build) (arm64)
-- | --
Revision | `e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#15879](https://github.com/brave/brave-core/pull/15879)
- Verified passing `--dev-wallet-password="my_dummy_password"` for release build doesn't unlock the wallet on start-up
