### ISSUE TITLE
Serialize Solana Transactions before use in within Redux

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#26677]
## Description 

Redux currently recommends that all data used in actions and reducers should be serializable. Serializing the store data allows us to save or send the store state using JSON.

This PR also will prevent warnings regarding non-serializable data in Solana-related transaction actions

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.47.164 Chromium: 109.0.5414.74 (Official Build) (64-bit)
-- | --
Revision | `e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}`
OS | Linux

- Verified steps from [brave/brave-core#15896](https://github.com/brave/brave-core/pull/15896)
- Verified Solana transactions work as expected. 
- Verified all tests on `https://pwgoom.csb.app` works as expected
- Verified all transactions are listed under Solana account details page
- Verified all transactions are shown in the panel under recent transactions

---------------------

Verification passed on 

Brave | 1.47.164 Chromium: 109.0.5414.74 (Official Build) (64-bit)
-- | --
Revision | `e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#15896](https://github.com/brave/brave-core/pull/15896)
- Verified Solana transactions work as expected. 
- Verified all tests on `https://pwgoom.csb.app` works as expected
- Verified all transactions are listed under Solana account details page
- Verified all transactions are shown in the panel under recent transactions

---------------------

Verification passed on 

Brave | 1.47.164 Chromium: 109.0.5414.74 (Official Build) (arm64)
-- | --
Revision | `e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#15896](https://github.com/brave/brave-core/pull/15896)
- Verified Solana transactions work as expected. 
- Verified all tests on `https://pwgoom.csb.app` works as expected
- Verified all transactions are listed under Solana account details page
- Verified all transactions are shown in the panel under recent transactions
