### ISSUE TITLE
[Android] YT Improvements: Picture-in-Picture Floating Player

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#26670]
## Description
See `Picture-in-Picture Floating Player` and `Requirements `sections here:
https://bravesoftware.slack.com/archives/CELA35G5S/p1694106384308469?thread_ts=1671572756.471319&cid=CELA35G5S

-----------------------------------------------

## Additional Info
Currently in Brave, picture-in-picture (PiP) mode only displays when tapping home from the **fullscreen YT player**. We should also display PiP mode when tapping home from the **minimized YT player**.

![image](https://user-images.githubusercontent.com/28269287/201159511-03af21f1-0d70-4eb7-9b9b-2e87b6d82255.png)

## Why
Currently users need to make 3 interactions to display YT videos in PiP mode:

1. While a video is playing, tap fullscreen icon on video player.
2. Swipe to reveal home button (easier said than done with YT overlays in the way - see current behavior video below).
3. Tap the home button.

The UX would be a lot cleaner if users could just tap the home button while the video is playing in the minimized video player to reveal PiP mode. It would be 1 interaction vs. 3 interactions. The YT app already has this behavior, we should try to keep parity to improve the YT experience in Brave. Also no other Android browser has this behavior so it would be a USP for the Brave YT experience.

## Current vs Desired Behavior

**Brave PiP (Current Behavior)**

https://user-images.githubusercontent.com/28269287/201163260-ee39d563-7ebb-48ed-ac2e-a3eccff1461b.mp4

**YT App PiP (Desired Behavior)**

https://user-images.githubusercontent.com/28269287/201163342-b2e7956e-6c1c-4547-ab6d-0eb1c6cc3ca1.mp4

**Comment by deeppandya** [comment]
@deeppandya will add more details with playlist work
