### ISSUE TITLE
`pravda.com.ua` feeds not found by search auto-discovery

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#26676]
## Description 

`pravda.com.ua` feeds not found by search auto-discovery

NOTE: This is essentially https://github.com/brave/brave-browser/issues/26550, which we missed when verifying for uplifts.  Instead, it looks like I verified feed auto-discovery within search only worked with `planet.mozilla.org`, rather than this, which was originally filed.  Apologies.

## Steps to Reproduce

1. install `1.47.55`
2. launch Brave
3. set `brave://flags/#brave-news-v2` and `brave://flags/#brave-news-subscribe-button to `Enabled`
4. click `Relaunch`
5. open a new-tab page
6. click on `Customize`
7. click on `Brave News`
8. click on `Turn on Brave News`
9. under `Discover`, enter `https://www.pravda.com.ua/eng/`
10. when `Sources` pops up with `Get feeds from...` click it
11. wait

## Actual result:

<img width="1153" alt="Screenshot 2022-11-10 at 15 16 37" src="https://user-images.githubusercontent.com/387249/201225990-279b6ac2-dfb7-4e7f-a5cf-7a5e9fd7f3b5.png">

## Expected result:

I believe it should find these feeds:

```<link rel="alternate" type="application/rss+xml" title="УП - Загальна стрічка всіх матеріалів" href="https://www.pravda.com.ua/rss/"/>
<link rel="alternate" type="application/rss+xml" title="УП - Новини" href="https://www.pravda.com.ua/rss/view_news/"/>
<link rel="alternate" type="application/rss+xml" title="УП - Тільки найважливіші новини" href="https://www.pravda.com.ua/rss/view_mainnews/"/>
<link rel="alternate" type="application/rss+xml" title="УП - Публікації" href="https://www.pravda.com.ua/rss/view_pubs/"/>
<link rel="alternate" type="application/rss+xml" title="УП - Загальна стрічка всіх матеріалів (рос)" href="https://www.pravda.com.ua/rus/rss/"/>
<link rel="alternate" type="application/rss+xml" title="УП - Новини (рос)" href="https://www.pravda.com.ua/rus/rss/view_news/"/>
<link rel="alternate" type="application/rss+xml" title="УП - Тільки найважливіші новини (рос)" href="https://www.pravda.com.ua/rus/rss/view_mainnews/"/>
<link rel="alternate" type="application/rss+xml" title="УП - Публікації (рос)" href="https://www.pravda.com.ua/rus/rss/view_pubs/"/>
```

They show up in the URL bar, under `Manage Subscriptions`

`view-source` | `URL bar`
---------------|----------------------- 
<img width="1446" alt="Screenshot 2022-11-10 at 15 17 44" src="https://user-images.githubusercontent.com/387249/201226306-d6fb76d6-361e-4e95-9595-05e45f3577d2.png"> | <img width="1312" alt="Screenshot 2022-11-10 at 15 06 12" src="https://user-images.githubusercontent.com/387249/201226782-c4fd636e-c0a1-4f9c-a416-218ea297367e.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.47.55 Chromium: 107.0.5304.91 (Official Build) nightly (x86_64)
-- | --
Revision | 3d5948960d62418160796d5831a4d2d7d6c90fa8-refs/branch-heads/5304@{#1097}
OS | macOS Version 13.1 (Build 22C5044e)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@fallaciousreasoning @petemill @MadhaviSeelam @mattmcalister

**Comment by fallaciousreasoning** [comment]
Okay, this is broken for a different reason to https://github.com/brave/brave-browser/issues/26550 - here the HTML was being returned with a non-UTF8 encoding, and we were completely failing to parse it. Fortunately the fix is simple enough: Parse the HTML doc with the appropriate encoding.

**Comment by LaurenWags** [comment]
Requires `1.46.122` or higher to test.
