### ISSUE TITLE
Wrong balance being shown for some Solana NFTs

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#26673]
I have created Solana NFTs on devnet, these tokens are showing wrong balance 1,000,000,000 NFT instead of 1 NFT with https://github.com/brave/brave-core/pull/15883.
This is because we use amount only in the getSPLTokenBalance result and not uiAmountString or amount + decimals within desktop UI code for Solana NFTs.
We should at least use uiAmountString for Solana NFTs.

Note: @muliswilliam did see correct balance in his own NFT on mainnet beta, because the amount returned in the RPC response is 1 already for his token, I'm not sure under what conditions tokens will get amount = 1 & decimals = 0 in the RPC response directly, and when we will get get amount = 1,000,000,000 and decimals = 9. Seems like they're both possible, so we should make sure both case works.

To test this:
- Check your existing Solana NFT or can ask what kind of NFT @muliswilliam owns on mainnet beta, you will see the balance is 1 on a Brave version without https://github.com/brave/brave-core/pull/15883 in it, and should continue to show the balance as 1 correctly on a version with https://github.com/brave/brave-core/pull/15883.
- Have a Solana NFT created on devnet (can ask @yrliou to send it), and check balance should correctly be shown as 1.

**Comment by yrliou** [comment]
Fixed by https://github.com/brave/brave-core/pull/15883.

**Comment by kjozwiak** [comment]
The above requires `1.45.125` or higher for `1.45.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.45.127 Chromium: 107.0.5304.110 (Official Build) (64-bit)
-- | --
Revision | `2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}`
OS | Linux

- Verified steps from issue description
- Verified NFT and SPL Tokens show correct balance
![image](https://user-images.githubusercontent.com/17010094/201895368-c38dfde5-4ba4-461b-b8e2-bdc3a71350ce.png)
---------------------

Verification passed on 

Brave | 1.45.127 Chromium: 107.0.5304.110 (Official Build) (64-bit) 
-- | --
Revision | `2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from issue description
- Verified NFT and SPL Tokens show correct balance
![image](https://user-images.githubusercontent.com/17010094/201898815-eb4f5a90-0337-47c2-b1e6-0dd1af000ea7.png)

---------------------

Verification passed on 

Brave | 1.45.127 Chromium: 107.0.5304.110 (Official Build) (64-bit) 
-- | --
Revision | `2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from issue description
- Verified NFT and SPL Tokens show correct balance
![image](https://user-images.githubusercontent.com/17010094/201894764-90ea34a8-c68c-4413-9585-b57c2ee87ff0.png)
