### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by ericxnelson** [brave/brave-browser#26679]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.45.116  Chromium: 107.0.5304.91
Operating System: Mac OS X 10.14.6

URL (if applicable) where crash occurred:

Can you reproduce this crash?
every day - seems like every time I come back onto my computer after a break/sleep the browser crashes out 5-10 times before stabilizing.
This started happening maybe a week ago?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1.
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/1f610200-b002-2209-0000-000000000000

**Comment by rebron** [comment]
Hi @ericxnelson Can you update to 1.45.123 and let us know if you're still experiencing the crash?
