### ISSUE TITLE
Brave News: Add additional locales to "Default Enabled" list

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#26678]
If the user has the following OS language and region set, then Brave News should start to show by default (new and existing users, unless the user has enabled and disabled Brave News from NTP).

`es_ES`
`es_MX`
`pt_BR`

The user should see content from that region.

**Comment by stephendonner** [comment]
@petemill not `ja-JP`, as well?

**Comment by petemill** [comment]
All ja and en users are already default-enabled.

**Comment by stephendonner** [comment]
> All ja and en users are already default-enabled.

Yep, sorry - read the patch and saw that it's already in, as you say 👍

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.46.109 Chromium: 107.0.5304.110 (Official Build) beta (64-bit)
-- | --
Revision | 2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}
OS | Windows 11 Version 21H2 (Build 22000.1219)
```
