### ISSUE TITLE
Move wallet "last used" preference from profile to local state

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#26675]
Moving the wallet "last used" preference from the profile preferences to the local state preferences. This will allow wallet usage stats to cover multiple profiles, instead of just the primary profile.

**Comment by GeetaSarvadnya** [comment]
@DJAndries Do I need to retest the issue #20956 on the 1.49.x build? The test description says last used preference is moved from  preference to local state, does it mean the metrics "wallet2" is moved to brave://local-state file?
![image](https://user-images.githubusercontent.com/38657976/212831278-f024153f-88d8-435a-acac-47d272a65b60.png)

**Comment by DJAndries** [comment]
> @DJAndries Do I need to retest the issue #20956 on the 1.49.x build? The test description says last used preference is moved from preference to local state, does it mean the metrics "wallet2" is moved to brave://local-state file? ![image](https://user-images.githubusercontent.com/38657976/212831278-f024153f-88d8-435a-acac-47d272a65b60.png)

Yes, please retest #20956. It would also be good to test migrating from 1.47.x to 1.49.x, and ensuring that the `wallet2` parameter works as expected during the upgrade. One test that could be done is as follows:

1) Open 1.47.x browser, let usage ping to be sent. Create & unlock wallet for the first time.
2) Close browser, advance system time by one day, upgrade to 1.49.x.
3) Open browser, and ensure `wallet2` is set to 7 in the usage ping.

fyi, the last unlock time is now stored in `brave.wallet.p3a_last_unlock_time` in local state.

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.48.129 Chromium: 109.0.5414.87 (Official Build) beta (64-bit)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | Windows 10 Version 21H2 (Build 19044.2486)

```

<details>
<summary>Case 1: WalletActive_0 (No usage pings)</summary>

Steps:

- Set the system data to 8th Feb 2022
- Clean profile, launch 1.38.1 nightly build
- Create a wallet
- Daily/weekly/monthly usage pings are `True` (which is correct as the usage pings are sent as soon as the browser is launched and these pings are NOT related to the wallet metrics)
- Verified wallet state is `0` which is correct as the wallet is just created and wallet pings are not yet sent


</details>

**Comment by DJAndries** [comment]
> @DJAndries Are you referring to the metric below? I don't see `brave.wallet.p3a_last_unlock_time` in brave://local-state file, Also how will convert this time `13318608648142675` into readable format?
> 
> ![image](https://user-images.githubusercontent.com/38657976/213187349-00e8e90f-0780-4728-a00a-0df8219bf1df.png)

Yes, I was referring to the preference above. I wouldn't worry about converting/validating the value. As long as the test cases work, I think that's all we need.
