### ISSUE TITLE
Support Uint8Array private key import for Solana

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#26672]
https://solflare.com/ export private key in Uint8Array instead of base58 encoding.
<img width="615" alt="Screen Shot 2022-11-10 at 09 45 41" src="https://user-images.githubusercontent.com/11330831/201169306-2cc098d7-d5d0-498c-8535-9532d3b4851b.png">

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.47.164 Chromium: 109.0.5414.74 (Official Build) (64-bit)
-- | --
Revision | `e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}`
OS | Linux

- Verified steps from [brave/brave-core#15959](https://github.com/brave/brave-core/pull/15959)
- Verified able to import Uint8Array private key for Solana Account

https://user-images.githubusercontent.com/17010094/211358833-c0131ed0-ce8d-46c5-8a1c-000cc3670187.mp4


---------------------

Verification passed on 

Brave | 1.47.164 Chromium: 109.0.5414.74 (Official Build) (64-bit)
-- | --
Revision | `e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#15959](https://github.com/brave/brave-core/pull/15959)
- Verified able to import Uint8Array private key for Solana Account

https://user-images.githubusercontent.com/17010094/211358081-8a87a408-5546-44f4-bcf8-dacf0fee7054.mp4


---------------------

Verification passed on 

Brave | 1.47.164 Chromium: 109.0.5414.74 (Official Build) (arm64)
-- | --
Revision | `e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#15959](https://github.com/brave/brave-core/pull/15959)
- Verified able to import Uint8Array private key for Solana Account

https://user-images.githubusercontent.com/17010094/211359257-38883550-04d6-4441-9830-ec1f724477f9.mov
