### ISSUE TITLE
Flag BraveNewsSubscribeButton results in core dump on certain sites

### ISSUE THREAD

**Issue by lurkynerd** [brave/brave-browser#26681]
## Description 
Instant crash when browsing certain sites such as thehackernews.com due to the new subscribe button flag.  This happens on Wayland session have not tested on X. 

## Steps to Reproduce

   1. enable the new BraveNewsSubscribeButton flag
   2. open site thehackernews.com
   3. brave crashes

## Actual result:
core dump

## Expected result:
no core dump

## Reproduces how often: 
every time 

## Brave version (brave://version info)
 1.46.99 Chromium: 107.0.5304.91 (Official Build) beta (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel?  yes
- Can you reproduce this issue with the nightly channel? don't know

## Other Additional Information:
Tried a variation of options/flags/vanilla boot and the one thing that caused core dump was  the BraveNewsSubscribeButton feature on certain sites.
- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? no

**Comment by rebron** [comment]
cc: @fallaciousreasoning

**Comment by fallaciousreasoning** [comment]
Interesting - I was trying to reproduce this at tip of tree and it doesn't seem to happen - maybe it's been fixed by one of the other PRs?

**Comment by fallaciousreasoning** [comment]
@lurkynerd is this still happening? I'm going to close the issue but feel free to comment/reopen
