### ISSUE TITLE
remove FTX widget from NTP and widget gallery

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#26683]
## Description 

Remove FTX widget from NTP and widget gallery for new and existing users.

## Brave version (brave://version info)

Target for 1.45.x maintenance release or sooner.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

Related issue: https://github.com/brave/internal/issues/954

**Comment by kjozwiak** [comment]
The above requires `1.45.125` or higher for `1.45.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.45.125 Chromium: 107.0.5304.110 (Official Build) (64-bit)
-- | --
Revision | `2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}`
OS | Linux

- Verified steps from [brave/brave-core#15898](https://github.com/brave/brave-core/pull/15898)
- Verified FTX widget is removed on both update profile and on clean profile
- Verified FTX widget is not available via customise settings

https://user-images.githubusercontent.com/17010094/201713453-b4771a8d-e35b-4578-b5c2-6c9483d7e857.mp4

---------------------

Verification passed on 

Brave | 1.45.125 Chromium: 107.0.5304.110 (Official Build) (64-bit) 
-- | --
Revision | `2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}`
OS | Windows 11 Version 22H2 (Build 22623.891)

- Verified steps from [brave/brave-core#15898](https://github.com/brave/brave-core/pull/15898)
- Verified FTX widget is removed on both update profile and on clean profile
- Verified FTX widget is not available via customise settings

https://user-images.githubusercontent.com/17010094/201716301-eaa59394-8269-4d43-bc97-b0fcfb54347a.mp4

---------------------

Verification passed on 

Brave | 1.45.125 Chromium: 107.0.5304.110 (Official Build) (64-bit) 
-- | --
Revision | `2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#15898](https://github.com/brave/brave-core/pull/15898)
- Verified FTX widget is removed on both update profile and on clean profile
- Verified FTX widget is not available via customise settings

https://user-images.githubusercontent.com/17010094/201712722-0a02e72c-4e87-4da3-9265-66306608a900.mp4
