### ISSUE TITLE
Solana NFT is not listed under NFT heading in account details page

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#26685]
## Description 

Solana NFT is not listed under NFT heading in account details page

## Steps to Reproduce

   1. Add Solana NFT to portfolio
   2. Click on Accounts tab and click on the account that holds the NFT
   3. NFT is listed under tokens and not under its own section similar to Ethereum NFT's

## Actual result:

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/17010094/201261990-e5068092-1563-4cc7-8c2e-85330eebb492.png">

## Expected result:
Similar to Ethereum NFT's
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/17010094/201262038-6979d05d-3b96-422e-8579-88c3919c9ba5.png">

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.47.63 Chromium: 107.0.5304.110 (Official Build) nightly (64-bit)
-- | --
Revision | `2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}`
OS | Windows 11 Version 22H2 (Build 22623.891)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @yrliou @muliswilliam

**Comment by Ashutosh2407** [comment]
Hii , I am new here. Can I take this issue?thanks

**Comment by srirambv** [comment]
Fixed by https://github.com/brave/brave-core/commit/e7f0be6e2c4530474d19899c31ebff43ce9f540e
