### ISSUE TITLE
Failed to purchase vpn subscription

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#26690]
## Description 

Brave VPN service says credentionals are not valid right after purchasing([here](https://github.com/brave/brave-core/blob/master/components/brave_vpn/brave_vpn_service.cc#L599)) 

```
                "unblinded_creds":
                [
                    {
                        "issuer_id": "927752e2-e189-4eed-a0ca-ee1606594a74",
                        "unblinded_creds":
                        [
                            {
                                "spent": true,
                                "unblinded_cred": "yBMACZQvpGU75hFBFj67QOJvJBDT45Hz6xd9up3qc7q3RXwjEhbPuJj3OjXj5TyQrHZ5fkSmwgFM8TA/3e/hwB5i/69Nvw5Famxh6ndnPMiMjO7Lf5JOv/WYSexTxOIo"
                            },
                            {
                                "spent": true,
                                "unblinded_cred": "y7SH3VEtt10QTaEvpeslelJRQxbDS8UdOYUaDC9+7RtStamS/GELgnPSWgCqSRvRydDMOGrcAz/kbJbxjiB55NqH03iCXJeLl2yJvOnyikIfjj/M9mvQZTkSbq9l7NF0"
                            }
                        ],
                        "valid_from": "2022-11-10T16:54:23",
                        "valid_to": "2022-11-11T16:54:23"
                    },
                    {
                        "issuer_id": "927752e2-e189-4eed-a0ca-ee1606594a74",
                        "unblinded_creds":
                        [
                            {
                                "spent": false,
                                "unblinded_cred": "yBMACZQvpGU75hFBFj67QOJvJBDT45Hz6xd9up3qc7q3RXwjEhbPuJj3OjXj5TyQrHZ5fkSmwgFM8TA/3e/hwKTwdrG+JvlwtiSR0hgwoh0ujFUvX55Lc/D42GPg4R5t"
                            },
                            {
                                "spent": false,
                                "unblinded_cred": "y7SH3VEtt10QTaEvpeslelJRQxbDS8UdOYUaDC9+7RtStamS/GELgnPSWgCqSRvRydDMOGrcAz/kbJbxjiB55EKo+pSXxhWDYHmZ0GIr5bTAMaFkpKIf9eGmxyx4X7MN"
                            }
                        ],
                        "valid_from": "2022-11-11T16:54:23",
                        "valid_to": "2022-11-12T16:54:23"
                    },
```

## Steps to Reproduce

   1. Buy vpn for a new account or try to recover old one
   2. see green messages about success on the vpn page
   3. Check popup, it doesnt show purchased state

## Actual result:

Brave vpn popup doesnt show purchased state

## Expected result:

Vpn purchased

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by husobee** [comment]
https://github.com/brave/brave-core/pull/15926 - fixes the next interval issue where credentials from yesterday will not work for today.
https://github.com/brave/brave-core/pull/15918 - fixes one of the issues that could have lead to this problem.

I believe that these two PRs correct this particular issue for the moment.

**Comment by bsclifton** [comment]
Closing as stale - let's re-open if you still are experiencing this @spylogsster 😄
