### ISSUE TITLE
Create an about:adblock page

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#267]
The first version would be very simple, you can follow along how about:payments is done for a simple example, or about:newtab is done in WebUI for a more complicated example.

It should be the same redux format as the newtab page.

The first version would just say the blocked count.
It would also indicate if a regional list is in use and if so which one it is.

Later we'll add more features to this page like custom filters.

**Comment by bsclifton** [comment]
cc: @Snuupy

**Comment by bbondy** [comment]
I was doing a task close to this code today so I just took this one too.

**Comment by bbondy** [comment]
As described above, this task is just to get the page working, redux things setup, and display the block count, if region lists are enabled, and if so which one is being used. It's mainly for support for now until we add things like custom lists.

<img width="342" alt="screen shot 2018-07-04 at 9 45 06 pm" src="https://user-images.githubusercontent.com/831718/42298373-8fba1036-7fd3-11e8-844b-7f6e5611fcb2.png">

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7

![image](https://user-images.githubusercontent.com/34715963/45865992-9bf7ba80-bd7f-11e8-9aa3-b6b12e9cd91f.png)
