### ISSUE TITLE
Brave news feed is not shown when opted out initially on the NTP and Turning on news in the Brave news dialog later

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#26703]
## Description 

Opted out of Brave news initially on the NTP and as expected, no Brave news feed displayed.  Clicked `Customize` and  clicked `Turn on Brave News` in the new Customize Brave news dialog.  However  Brave news feed is not shown in the NTP

## Steps to Reproduce

   1. Install 1.46.102
   2.  launch Brave
   3.  open `brave://flags`
   4.  click `Enabled` for #brave-news-v2` flag
   5.  open NTP
   6.  scroll down
   7. click `No Thanks` button
   8. click `Customize`
   9. click `Brave News` in the `Customize Dashboard`
   10. click `Turn on Brave News`
   11. click `X` to close dialog
   12. open NTP
   13. scroll down for Brave News feeds

## Actual result:

No feed displayed

https://user-images.githubusercontent.com/98358127/201422334-3f7c3bfc-f757-4a2c-89a1-76a3e4be87ae.mp4

## Expected result:
Brave News feed should be displayed

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Brave | 1.46.102 Chromium: 107.0.5304.110 (Official Build) beta (64-bit)
-- | --
Revision | 2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}
OS | Windows 11 Version 21H2 (Build 22000.1219)

## Version/Channel Information:

- Can you reproduce this issue with the current release?  N/A
- Can you reproduce this issue with the beta channel?  Yes
- Can you reproduce this issue with the nightly channel?  

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@mattmcalister @fallaciousreasoning 
cc: @stephendonner

**Comment by fallaciousreasoning** [comment]
@petemill is this fixed by https://github.com/brave/brave-core/pull/15877

**Comment by stephendonner** [comment]
Thanks for logging this, @MadhaviSeelam.  I've seen this too, when testing the `Manage Subscriptions` button <-> `Customize News` dialog behavior, but chalked it up to being specific to that flow.  Now I realize it was, like this one, because of opt-in.

**Comment by MadhaviSeelam** [comment]
Verified in 1.61.104.  Closing as it's no longer an issue. 

<img width="940" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/40d01461-0ba3-4a60-ae10-18e7957baa37">
