### ISSUE TITLE
Shouldn't show `Manage Subscriptions` button in URL bar until after opt-in

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#26705]
## Description 

Shouldn't show `Manage Subscriptions` button in URL bar until after opt-in

## Steps to Reproduce

   1. install `1.47.65`
   2. launch Brave
   3. open `brave://flags`
   4. set `brave://flags/#brave-news-subscribe-button` to `Enabled`
   5. click `Relaunch`
   6. dismiss the cookie-consent dialog
   7. open a new-tab page
   8. scroll
   9. confirm you are not opted-in to `Brave News`
   10. load `planet.mozilla.org`
   11. wait
   12. click on the `Manage Subscriptions` icon in the URL bar
   13. click `Follow`
   14. click `Manage Feeds`
   15. click `Turn on Brave News`
   16. examine the dialog, under `Following`

## Actual result:

`Planet Mozilla` shows as `Followed`, after opting in

example | example | example | example | example
-----|-----|------|-----|-----
<img width="1006" alt="Screen Shot 2022-11-11 at 12 21 08 PM" src="https://user-images.githubusercontent.com/387249/201430135-061c531b-b427-4df8-8c65-65ddb6ed2556.png"> | <img width="1006" alt="Screen Shot 2022-11-11 at 12 21 17 PM" src="https://user-images.githubusercontent.com/387249/201430137-5e0661e5-7c05-4f17-b859-3cdd158d7a44.png"> | <img width="1006" alt="Screen Shot 2022-11-11 at 12 21 24 PM" src="https://user-images.githubusercontent.com/387249/201430138-5b2f13d3-5741-4db2-809b-27ece29d82e9.png"> | <img width="1006" alt="Screen Shot 2022-11-11 at 12 24 37 PM" src="https://user-images.githubusercontent.com/387249/201430139-5d640492-284f-4711-af1d-7c70f8d1db1b.png"> | <img width="1205" alt="Screen Shot 2022-11-11 at 12 30 34 PM" src="https://user-images.githubusercontent.com/387249/201426517-5f60ea67-01b5-4f24-a177-54910ccb029a.png">

## Expected result:

In step 12, since we haven't-yet opted-in to Brave News, we should probably take the user to the `Customize` dialog, first, to opt-in?

Or maybe just not show the button until opted-in?

## Reproduces how often: 

100%
## Brave version (brave://version info)

Brave | 1.47.65 Chromium: 107.0.5304.110 (Official Build) nightly (x86_64)
-- | --
Revision | 2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}
OS | macOS Version 11.7.1 (Build 20G918)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @petemill @fallaciousreasoning @mattmcalister @LaurenWags @MadhaviSeelam

**Comment by fallaciousreasoning** [comment]
I can't repro this in 1.47.186 Chromium: 109.0.5414.119 (Official Build) (64-bit)  (which is the latest stable).
