### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by rushabhvg** [brave/brave-browser#26717]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.45.123  Chromium: 107.0.5304.110
Operating System: Windows NT 10.0.22621

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1.
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/dfde0400-b002-2209-0000-000000000000

**Comment by rushabhvg** [comment]
After disabling the brave news, I was abled to use it normally. I guess issue is around news section. Kindly check.

**Comment by iefremov** [comment]
most probably it was https://github.com/brave/brave-browser/issues/26604
