### ISSUE TITLE
SKUs SDK Time Limited V2 Creds Presentation Wrong for today + 1

### ISSUE THREAD

**Issue by husobee** [brave/brave-browser#26716]
## Description 
Credential presentation for time limited v2 credentials is incorrect due to how the token preimage is stored upon receiving the signed credentials from the server.  This causes the same token preimage to be submitted for all time intervals.

## Steps to Reproduce
Purchase VPN on staging.
Wait one Day.
Attempt to turn on the VPN

## Actual result:
VPN will not work.

## Expected result:
VPN should work

## Reproduces how often: 
Easily

## Brave version (brave://version info)
1.47.66

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
Confirmed using 

Brave | 1.47.61 Chromium: 107.0.5304.110 (Official Build) nightly (x86_64)
-- | --
Revision | 2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}
OS | macOS Version 13.1 (Build 22C5044e)



### Steps to Reproduce:
1. delete any BraveVPN OS-configs, first
2. install 1.47.
3. launch Brave using `--vmodule="*/skus/*"=2 --enable-logging=stdrr --v=0`
4. click `Maybe later`
5. click `Skip welcome tour`
6. open `brave://flags`
7. set `brave://flags/#brave-vpn` to `Enabled`
8. click `Relaunch` (if you want to retain logging, CTRL+C and relaunch from Terminal/console
9. click `No thanks` on the `Tired of cookie consent notices?` dialog
10. load `account.bravesoftware.com`
11. enter staging credentials from 1Password
12. enter a unique email address such as "unique99@mailinator.com" or similar
13. click `Get login link`
14. open the `Log in to your Brave Pre...` email (`https://www.mailinator.com/v4/public/inboxes.jsp?to=unique99` in the above case)
15. click on either the `Log in to Brave` button -or- the link below it
16. click `Browse plans` on `https://account.bravesoftware.com/account/`
17. scroll down
18. click on `Buy now` beneath `Brave VPN Subscription`
19. complete the Stripe checkout using `https://stripe.com/docs/testing#testing-interactively`
20. if you're able to, click on the `VPN` button in the browser toolbar, and attempt to add and connect to the `BraveVPN` config
21. confirm you can connect
22. now, set the system clock ahead a day.
23. re-run Brave from. your commandline, and click on the `VPN` button in the browser toolbar

Actual Results:

<img width="1312" alt="Screenshot 2022-11-13 at 11 15 00 AM" src="https://user-images.githubusercontent.com/387249/201490986-fe2771b4-f19a-4bdd-8bb9-048a437b60ce.png">

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.46.122 Chromium: 108.0.5359.48 (Official Build) beta (x86_64)
-- | --
Revision | 18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}
OS | macOS Version 11.7.1 (Build 20G918)



### Steps:

1. deleted my previous BraveVPN OS-configs
2. installed `1.46.122` 
3. launched Brave using `--vmodule="*/skus/*"=2 --enable-logging=stdrr --v=0`
4. clicked `Maybe later`
5. clicked `Skip welcome tour`
6. opened `brave://flags`
7. set `brave://flags/#brave-vpn to Enabled`
8. clicked `Relaunch` (if you want to retain logging, CTRL+C and relaunch from Terminal/console
9. clicked `No thanks` on the `Tired of cookie consent notices?` dialog
10. loaded `account.bravesoftware.com`
11. entered staging credentials from `1Password`
12. entered a unique email address, `issue26716@mailinator.com`
13. clicked `Get login link`
14. opened the `Log in to your Brave Pre...` email in the above case)
15. clicked on either the Log in to Brave button -or- the link below it
16. clicked Browse plans on `https://account.bravesoftware.com/account/`
17. scrolled down
18. clicked on `Buy now` beneath `Brave VPN Subscription`
19. completed the Stripe checkout using `https://stripe.com/docs/testing#testing-interactively`
20. clicked on the `VPN` button in the browser toolbar, add and connect to the `BraveVPN` config
21. confirm you can connect
22. shut down Brave
23. set the system clock ahead a day
24. re-ran Brave from my commandline, and click on the VPN button in the browser toolbar

#### Confirmed I could use VPN on the subscription day + the day after

example | example | example | example
---------|----------|---------|---------
<img width="1285" alt="Screen Shot 2022-11-21 at 11 28 21 PM" src="https://user-images.githubusercontent.com/387249/203252699-96658f96-9405-441e-a9e2-c75153e44690.png"> | <img width="780" alt="Screen Shot 2022-11-21 at 11 29 56 PM" src="https://user-images.githubusercontent.com/387249/203252715-754ea2d7-53e1-492b-b966-14d5a0c42ecd.png"> | <img width="780" alt="Screen Shot 2022-11-22 at 11 30 08 PM" src="https://user-images.githubusercontent.com/387249/203252723-59312beb-17fd-47d8-bd4c-42ee2d52cd86.png"> | <img width="1175" alt="Screen Shot 2022-11-22 at 11 36 22 PM" src="https://user-images.githubusercontent.com/387249/203253351-db845861-5521-4acd-9eb8-1bd009ea81db.png">

**Comment by GeetaSarvadnya** [comment]
Verification inprogress

```
Brave | 1.46.123 Chromium: 108.0.5359.48 (Official Build) beta (64-bit)
-- | --
Revision | 18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}
OS | Windows 10 Version 21H2 (Build 19044.2251)

```
