### ISSUE TITLE
Screen fingerprinting protection is applied to extensions pages

### ISSUE THREAD

**Issue by arthuredelstein** [brave/brave-browser#26715]
First reported here:
https://twitter.com/AaronToponce/status/1590038533963538432

I was able to confirm that the extension pop-up for Bitwarden is half size when screen fingerprinting protection is enabled. It appears this is because the browser is lying about the size of the screen to the popup page, which has a `chrome-extension://` address. We should not apply this protection to such extension pages.

**Comment by arthuredelstein** [comment]
@pes10k Do you have an opinion on the best approach here? The two options are:
1. Exempt extension pages entirely from fingerprinting protections (my PR's approach)
2. Exempt extension pages from screen fingerprinting protections only (an alternative approach I could implement)
I think the decision depends mainly on Brave's threat model for extensions.

**Comment by pes10k** [comment]
Yep! I agree, option 1 seems A+ to me

**Comment by arthuredelstein** [comment]
Reopening while we uplift

**Comment by arthuredelstein** [comment]
''QA testing ideas''

The fix for this bug modifies our fingerprinting protections so they aren't applied to extensions pages. To test, we can check that (**A**) known broken extensions are no longer broken, while (**B**) fingerprinting protection still applies to http(s) pages.

**Part A**

1. Enable the flag brave://flags#brave-block-screen-fingerprinting

2. Install the LINE extension: https://chrome.google.com/webstore/detail/line/ophjlpahpchlmihnnnihgmmeilfjmjjc?hl=en
Once it is installed, confirm that clicking on the extension button (<img width="34" alt="image" src="https://user-images.githubusercontent.com/355566/203122982-306e5439-4f9a-4454-8a62-ecd93b046c44.png">) opens a LINE login window:
<img width="847" alt="image" src="https://user-images.githubusercontent.com/355566/203123659-b344f9d8-47fe-461b-ba33-5730140f0a57.png">

(Without this fix, the Login window does not open.)

3. Install the Bitwarden extension: https://chrome.google.com/webstore/detail/bitwarden-free-password-m/nngceckbapebfimnlniiiahkandclblb?hl=en
Create a login account. Once logged in, confirm that clicking on the Bitwarden extension button opens a full-length popup:
<img width="392" alt="image" src="https://user-images.githubusercontent.com/355566/203123615-046daa8d-58f6-46e3-9029-997233aba161.png">

(Without this fix, the popup appears but is much shorter.)

<img width="494" alt="image" src="https://user-images.githubusercontent.com/355566/203123833-193038ba-3b61-480f-8e2a-41c0a385bb2c.png">

**Part B**

Confirm that screen fingerprinting is still working in http(s) pages by reproducing the tests done in https://github.com/brave/brave-browser/issues/23170#issuecomment-1269026947

**Comment by LaurenWags** [comment]
Requires `1.45.131` or higher to test

**Comment by GeetaSarvadnya** [comment]
Verification is inprogress

```
Brave | 1.45.131 Chromium: 107.0.5304.110 (Official Build) (64-bit)
-- | --
Revision | 2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}
OS | Windows 10 Version 21H2 (Build 19044.2251)

```
