### ISSUE TITLE
Browser crashes when Solana support flag is disabled/enabled

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#26728]
## Description 
Browser crash with Solana flag is enabled/disabled. Found while testing https://github.com/brave/brave-core/pull/15869

## Steps to reproduce 

   1. Clean install 1.47.70 build
   2. Disable Solana support flag 
   3. Create new wallet, browser crashes during inital creation
   4. Try again, starts from onboarding again and creates wallet
   5. Enable Solana support flag and relaunch
   6. Connect to a Solana Dapp after relaunch, browser crashes again the first time it interacts
   7. Try a second time to interact with the Dapp works fine.

## Actual result 
Browser crashes when Solana support flag is disabled/enabled. Recording in https://github.com/brave/brave-core/pull/15869 shows the crash while interacting with Dapp

## Expected result
No Crash

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 12
   
## Brave version
1.47.70

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @Pavneet-Sing

**Comment by Pavneet-Sing** [comment]
It seems like an edge case as i am able to create wallet and later solana account with debug, nightly and on arm device using nightly. Maybe crash logs might help to get some info.

[solana-account-creation.webm](https://user-images.githubusercontent.com/11755381/201647053-6b222519-a18e-4692-99c5-b37b0a6b6446.webm)

**Comment by Pavneet-Sing** [comment]
Unable to reproduce on android 13 as well, need more info to reproduce.

**Comment by HEagle18** [comment]
@srirambv can you recreate this ?

**Comment by iefremov** [comment]
stale
