### ISSUE TITLE
Uplift cpplint rules update to beta/release branches

### ISSUE THREAD

**Issue by goodov** [brave/brave-browser#26722]
https://github.com/brave/brave-core/commit/ac1f3d4a12ebcda0aef413aef4b144fd40f1fbb5#diff-5164aa971a23edcf3fcc947e48e31550b0cce076b7cf1a772429672bdeee0f46R100

we need to uplift this to release branches, otherwise uplift PRs may fail on code blocks with disabled clang-format.

**Comment by kjozwiak** [comment]
Closing as both https://github.com/brave/brave-core/pull/15928 & https://github.com/brave/brave-core/pull/15929 have been uplifted.
