### ISSUE TITLE
[QA] 0.58.x sync issues that still need to be verified (Windows only)

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#2672]
Because it was decided that sync won't be going out enabled by default in `0.58.x`, QA concentrated on verifying other issues. Because the following PR/fixes already landed in `0.58.x`, we need to verify that the following have also been QA'd/verified for sync on Windows:

* Sync chain not being reset when Main device is removed #2575 
* This Device is put on the wrong row #2572 
* Sync chain should be reset when deleting another device with v2 spec #2552 
* QR code/words don't display if you try to join a sync chain before starting a new one #2540 
* Possible to sync the device with itself #2539 
* re-enabling wifi does not show sync QR code or words #2537 
* sometimes QR codes and words not displayed for sync #2533 
* Removed folders are not re-synced properly, when two devices are still in sync #2458 
* Sync should handle library/client errors #2316 
* Implement Sync UI #356 

This issue is specific to Windows, however CCing @brave/legacy_qa please let me know if there's anything that I might have missed.

**Comment by btlechowski** [comment]
Verified all except https://github.com/brave/brave-browser/issues/2552 and https://github.com/brave/brave-browser/issues/2533 which were moved to 0.60.x

**Comment by kjozwiak** [comment]
@btlechowski looks like https://github.com/brave/brave-core/pull/1191 landed in `0.59.x` about a day ago but the milestones for #2533, #2552, #2728, #2737 weren't updated and the issues were still in `0.60.x`. I moved #2533, #2552, #2728, #273 into `0.59.x` 👍 

We should be able to QA #2552 & #2533 as https://github.com/brave/brave-core/pull/1191 landed in `0.59.18`. Clearing the flag until #2552 & #2533 are checked.

**Comment by btlechowski** [comment]
@kjozwiak I think this issue is only for issues that were closed in 0.58.x milestone. We couldn't move them to 0.59.x milestone, hence this issue was created.

This issue is not for sync issues that have 0.59.x milestone.

**Comment by kjozwiak** [comment]
@btlechowski yup, you're right 👍 Lets just remove #2552 & #2533 form the above list and those can be addressed separately.
