### ISSUE TITLE
[Android] `wallet-generation-disabled` error message is not correct

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#26726]
## Description 
Found while testing https://github.com/brave/internal/issues/894
Brave rewards not available message is NOT shown when rewards unsupported region "Iran" is selected from the onborading

## Steps to reproduce 

   1. Clean profile 1.46.99
   2. Relaunch the browser to to pull the griffin seed
   3. Open the Rewards panel and click "Start Using Rewards"
   4. Select unsupported country (like Iran) from the list and click "Continue"
   5. `Something went wrong` message is displayed instead of "Brave Rewards not available" error message

## Actual result 
`Something went wrong` message is displayed instead of "Brave Rewards not available" error message

![image](https://user-images.githubusercontent.com/38657976/201591390-f5083814-37a9-45a9-95c6-c86fc1dbed4d.png)

## Expected result

Error mesage should be same as Desktop

Desktop 
![image](https://user-images.githubusercontent.com/38657976/201590721-0e0cece1-16b1-46d2-9152-804e392d96ca.png)

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung Galaxy
   - Android version: 12
   
## Brave version
1.46.99

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

More info: https://bravesoftware.slack.com/archives/CNH9Q6REV/p1668431862993669?thread_ts=1668402651.779199&cid=CNH9Q6REV

CC: @brave/qa-team @deeppandya @Miyayes @szilardszaloki @zenparsing

**Comment by deeppandya** [comment]
@Miyayes i was not aware of different error messages here as we don't have it in figma. would it be possible for you to mention different error messages here ?

**Comment by Miyayes** [comment]
@deeppandya For "wallet-generation-disabled" error case, this is the error message:

**Brave Rewards not available**
New signups for Brave Rewards are currently disabled in your region. However, you can always try again later. [Learn more](https://support.brave.com/hc/en-us/articles/9312922941069)

**Comment by deeppandya** [comment]
This issue should be fixed with https://github.com/brave/brave-core/pull/16232
