### ISSUE TITLE
Lots of space in the tipping banner

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#26739]
## Description 
Lots of space in the tipping banner

## Steps to reproduce 

   1. Clean profile 1.46.109
   2. Enable rewards
   3. Open a site and tap on `Send Tip`
   4. Tipping banner is shown with lot of empty space

## Actual result 
Lots of space in the tipping the banner
![image](https://user-images.githubusercontent.com/38657976/201717369-fd882faa-1806-4706-bfea-0d90057133d2.png)

## Expected result

should not be any empty space
## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86): ARM 
   - Device type (Phone, Tablet, Phablet): Galaxy Tab A7
   - Android version: version 12
   
## Brave version
1.46.109

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/qa-team @deeppandya @Miyayes

**Comment by deeppandya** [comment]
@sujitacharya2005 can you look into this issue as it's related to tipping banner ?

**Comment by sujitacharya2005** [comment]
@Miyayes 
This seems issue in Tablet.
Where lot of empty space is coming.

**Comment by Miyayes** [comment]
Seems like tablet-specific issue, so added a label. That said, ideally @sujitacharya2005, you could reduce the overall size of the tipping banner (the blue part, bring it down so that it's roughly 50% height of screen), and then blur/darken the webpage behind the tipping banner.

**Comment by kjozwiak** [comment]
Closing as the above has been fixed via https://github.com/brave/brave-core/pull/16081#issue-1463576067.

**Comment by kjozwiak** [comment]
The above will require `1.46.141` or higher for `1.46.x` verification 👍

**Comment by Uni-verse** [comment]
In progress on Android ARM using the following build version(s):

```
Brave	1.46.141 Chromium: 108.0.5359.99 (Official Build) (64-bit) 
Revision	410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS	Android 12; Build/SP2A.220305.013
```

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung Galaxy Tab S8 Ultra` running `Android 13` using the following build(s):

```
Brave | 1.46.141 Chromium: 108.0.5359.99 (Official Build) (32-bit)
--- | ---
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | Android 13; Build/TP1A.220624.014
```

**`Example`** | **`Example`**
----------------|----------------
![Screenshot_20221212_142725_Brave](https://user-images.githubusercontent.com/2602313/207136719-2f6c45c9-56f2-4706-abdb-12dc7233e6df.jpg) | ![Screenshot_20221212_142735_Brave](https://user-images.githubusercontent.com/2602313/207136735-af8fd88b-d1ea-4a79-976a-6e4ebb89724b.jpg)

Created https://github.com/brave/brave-browser/issues/27251 as a follow up re: blurring/darkening inactive areas while the tipping banner is visible.
