### ISSUE TITLE
[Android] Incorrect error text in new user case (trigger error case by disabling WIFI)

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#26732]
## Description 
Found while testing https://github.com/brave/internal/issues/894
Incorrect error message when new user tries to select country when network or WIFI is off 
## Steps to reproduce 

   1. Clean profile 1.46.x, relaunch to pull griffin seed
   2. Open the Rewards panel and click "Start Using Rewards"
   3. Turn off Wifi
   4. Select a country from the list and click "Continue"
   5. Verify that "Something went wrong" error is displayed
   6. `Trying to set your country` text is shown in the error message instead of `Trying to set up Brave Rewards` text 
   
   

## Actual result 
Trying to set your country` text is shown in the error message instead of `Trying to set up Brave Rewards` text 
![image](https://user-images.githubusercontent.com/38657976/201675338-73900814-b94b-4bdd-85d0-7824a6908cb9.png)

## Expected result

For new user on a clean profile, if user tries to select country when wifi is OFF the message should be disaplyed as below:

Desktop 
![image](https://user-images.githubusercontent.com/38657976/201674906-090a757e-d130-4d38-ab0f-a584d3d110ff.png)

## Issue reproduces how often 

Easy
## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung galaxy
   - Android version: 12
   
## Brave version
1.46.99

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/qa-team @deeppandya @Miyayes

**Comment by Miyayes** [comment]
Since this is fresh profile case, it should be "set up Brave Rewards" language, instead of "set your country" language. 

In short:

1. "set up Brave Rewards" language is for new profile case;
2. "set your country" language is for existing users case

**Comment by stephendonner** [comment]
## Verified `PASSED` using `Brave` `1.48.148`, `Chromium`, `109.0.5414.119` on a `Google Pixel XL` running `Android 9`

### Steps:

1. installed `1.48.148`
2. launched Brave
3. skipped onboarding
4. tapped on the `BAT` icon
5. tapped `Start using Brave Rewards`
6. disabled Wi-Fi on my `Google Pixel XL`
7. selected `United States` from the country list and tapped `Continue`

#### Confirmed the error message was `Unfortunately, there was an error while trying to set up Brave Rewards.  Please try again.`

example | example
---------|---------
![Screenshot_20230130-195055](https://user-images.githubusercontent.com/387249/215659482-928dacf9-9bb1-4dc3-ab50-f91c0d0c3a1b.png) | ![Screenshot_20230130-195106](https://user-images.githubusercontent.com/387249/215659487-307bceda-d7f5-4eba-b7cb-a19c06cee2ed.png)
