### ISSUE TITLE
Opening a new tab causes the bookmarks bar to be displayed regardless of the "Show bookmarks" option

### ISSUE THREAD

**Issue by tocic** [brave/brave-browser#26730]
## Description 
After opening a new tab the Brave browser shows the bookmarks bar for a moment, then hides it.

## Steps to Reproduce
   1. Uncheck the "Show bookmarks" option (or <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>B</kbd>)
   2. Open a new tab via the "Plus" button (or <kbd>Ctrl</kbd>+<kbd>T</kbd>).

## Actual result:
In a split second you'll see the same output as if the "Show bookmarks" check was checked, then the bookmarks will disappear as expected.

![bug](https://user-images.githubusercontent.com/22129543/201636462-a9cd273c-be3e-4c94-b092-4e745d6dc47e.gif)

## Expected result:
Just a new tab page without the bookmarks bar.

## Reproduces how often: 
Easily reproduced.

## Brave version (brave://version info)
<html>
<body>

Brave | 1.45.123 Chromium: 107.0.5304.110 (Official Build) (64-bit)
-- | --
Revision | 2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}
OS | Windows 10 Version 21H2 (Build 19044.2130)

</body>
</html>

**Comment by tocic** [comment]
Also reproducible on Linux with Brave 1.45.127.

**Comment by manikandancode** [comment]
https://github.com/brave/brave-browser/issues/25834

**Comment by tocic** [comment]
@manikandancode Thanks. Indeed, it's a duplicate of https://github.com/brave/brave-browser/issues/25834.
