### ISSUE TITLE
Credentials purchase doesn't complete, leading to so-called "stuck triangle"

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#26746]
## Description 

Credentials purchase doesn't complete, leading to so-called "stuck triangle"

Note: this is a follow-on from https://github.com/brave/brave-browser/issues/26671, but has a separate cause, and thus, fix 👍 

## Steps to Reproduce

   0. delete any `BraveVPN` OS-configs, first
   1. install `1.47.71`
   2. launch Brave using `--vmodule="*/skus/*"=2 --enable-logging=stdrr --v=1`
   3. click `Maybe later`
   4. click `Skip welcome tour`
   5. open `brave://flags`
   6. set `brave://flags/#brave-vpn` to `Enabled`
   7. click `Relaunch` (if you want to retain logging, `CTRL+C` and relaunch from `Terminal`/console
   8. click `No thanks` on the `Tired of cookie consent notices?` dialog
   9. load `account.bravesoftware.com`
   10. enter staging credentials from 1Password
   11. enter a unique email address such as "`unique99@mailinator.com`" or similar
   12. click `Get login link`
   13. open the `Log in to your Brave Pre...` email (`https://www.mailinator.com/v4/public/inboxes.jsp?to=unique99` in the above case)
   14. click on either the `Log in to Brave` button -or- the link below it
   15. click `Browse plans` on `https://account.bravesoftware.com/account/`
   16. scroll down
   17. click on `Buy now` beneath `Brave VPN Subscription`
   18. complete the Stripe checkout using `https://stripe.com/docs/testing#testing-interactively`
   19. if you're able to, click on the `VPN` button in the browser toolbar, and attempt to add and connect to the `BraveVPN` config

## Actual result:

Many times, we get the so-called "stuck triangle" shown here, with or without the included JSON exception, also shown:

<img width="1587" alt="Screen Shot 2022-11-14 at 9 08 14 AM" src="https://user-images.githubusercontent.com/387249/201741912-a327e797-40bb-4655-8818-f37c86cb00d3.png">

## Expected result:

<img width="1312" alt="Screen Shot 2022-11-12 at 1 30 33 AM" src="https://user-images.githubusercontent.com/387249/201741576-64d992bf-62d4-4771-9ddd-ead6b3581436.png">

## Reproduces how often: 

Often:
run 1 - “stuck triangle”
run 2 - “stuck triangle”
run 3 - got it working on the 2nd reload, after the 1st reload propagated the JSON-request body error
run 4 - 1st normal reload made it work
run 5 - “stuck triangle” 

## Brave version (brave://version info)

Brave | 1.47.71 Chromium: 107.0.5304.110 (Official Build) nightly (x86_64)
-- | --
Revision | 2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}
OS | macOS Version 11.7.1 (Build 20G918)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

/cc @mattmcalister @rebron @husobee @evq @AlanBreck @brave/qa-team

**Comment by GeetaSarvadnya** [comment]
The follow-up issue #26780 is been logged and issue is fixed and working fine in #26780. Hence adding QA/No label for this issue.

**Comment by stephendonner** [comment]
> The follow-up issue #26780 is been logged as per the above comments, the issue is fixed and working fine in #26780. Hence adding QA/No label for this issue.
> 
> @stephendonner @LaurenWags Feel free to change the label if you think differently.

That works for me, @GeetaSarvadnya, thanks.  No need to verify the same *symptoms* fixed for three separate causes, here.  We've got that other issue and more, as you note.

I'm just adding the following verification for my own sanity/satisfaction:



Brave | 1.46.122 Chromium: 108.0.5359.48 (Official Build) beta (x86_64)
-- | --
Revision | 18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}
OS | macOS Version 11.7.1 (Build 20G918)

<img width="1176" alt="Screen Shot 2022-11-21 at 10 33 41 PM" src="https://user-images.githubusercontent.com/387249/203242307-056f63f5-f5ca-4791-8fbd-7c3b325d7121.png">
