### ISSUE TITLE
`Support this creator` header is not shown in the tipping banner

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#26740]
## Description 

`Support this creator` header is not shown in the tipping banner
## Steps to reproduce 

   1. Clean profile 1.46.109
   2. Enable rewards
   3. Open a website
   4. Click on the Br panel and tap on `Send Tip`
   5. `Support this creator` header is not shown in the tipping banner

## Actual result 
`Support this creator` header is not shown in the tipping banner

![Screenshot_20221114-212020_Brave - Beta](https://user-images.githubusercontent.com/38657976/201715525-716a0bc5-a132-4bd5-97bd-b2bc9a53867c.jpg)

## Expected result
Should be same as Desktop
![image](https://user-images.githubusercontent.com/38657976/201715207-4e9ef3b9-bde4-4508-a0b3-b58af1f248ad.png)

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung Tab A
   - Android version: version 12
   
## Brave version
1.46.109

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

CC: @brave/qa-team @deeppandya @Miyayes

**Comment by deeppandya** [comment]
@sujitacharya2005 can you look into this issue as it's related to tipping banner ?

**Comment by sujitacharya2005** [comment]
@Miyayes 

In android design "Support this creator" is missing.
Do you want to this in Android?

cc: @deeppandya , @GeetaSarvadnya

**Comment by kjozwiak** [comment]
https://github.com/brave/brave-core/pull/16081#issue-1463576067

**Comment by kjozwiak** [comment]
The above will require `1.46.141` or higher for `1.46.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` & `Samsung Galaxy Tab S7` using the following build version(s):

```
Brave	1.46.141 Chromium: 108.0.5359.99 (Official Build) (64-bit) 
Revision	410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS	Android 12; Build/SP1A.210812.016
```
- Verified `Support this creator` is shown in the tipping banner

Example | Example
-|-
![screenshot-1670873189626](https://user-images.githubusercontent.com/17885425/207142348-de3be3f8-5087-4167-ab05-f27e3060c22f.png) | ![screenshot-1670875024268](https://user-images.githubusercontent.com/17885425/207142350-1b519f11-a154-40a3-b54a-018002a4e062.png)
