### ISSUE TITLE
Close (x) button should be present in the tipping banner

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#26744]
## Description 
Close (x) button should be present in tipping banner

## Steps to reproduce 

   1. NA
   2. 
   3. 

## Actual result 
Currently there is no close (x) button in the tipping banner to come out of the tipping banner, only way is to come out off the banner is tap on the device back botton 

![image](https://user-images.githubusercontent.com/38657976/201732522-4b4390bb-2b68-418d-bfa7-227caa589ce0.png)

## Expected result
Close (x) button should be present in tipping banner 

Desktop
![image](https://user-images.githubusercontent.com/38657976/201731655-3ce578b0-bbf0-4c82-9286-1c54d91ef9de.png)

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Galaxy Tab A7
   - Android version: version 12
   
## Brave version

1.46.109

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @deeppandya @Miyayes @brave/qa-team

**Comment by deeppandya** [comment]
@sujitacharya2005 can you look into this issue as it's related to tipping banner ?

**Comment by kjozwiak** [comment]
The above will require `1.46.141` or higher for `1.46.x` verification 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 13` using the following build(s):

```
Brave | 1.46.141 Chromium: 108.0.5359.99 (Official Build) (32-bit)

Revision	410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS	Android 13; Build/TQ1A.221205.011
```

* ensured that pressing the `X` button closes the tipping banner without any issues on both one-time & monthly tipping
* ensured that you can still close/dismiss the tipping banner by swiping to the left and returning to the rewards panel

**`Example`** | **`Example`**
----------------|----------------
![Screenshot_20221212-134833](https://user-images.githubusercontent.com/2602313/207133890-81dfd4a3-df4f-4674-aa51-583f40f04396.png) | ![Screenshot_20221212-134837](https://user-images.githubusercontent.com/2602313/207133892-caba5c26-24e1-4305-9b5e-cc32822d01b2.png)

--------------------------

Verification **PASSED** on `Samsung Galaxy Tab S8 Ultra` running `Android 13` using the following build(s):

```
Brave | 1.46.141 Chromium: 108.0.5359.99 (Official Build) (32-bit)
--- | ---
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | Android 13; Build/TP1A.220624.014
```

* ensured that pressing the `X` button closes the tipping banner without any issues on both one-time & monthly tipping
* ensured that you can still close/dismiss the tipping banner by tapping on the `<` (Back) button at the bottom of the device

**`Example`** | **`Example`**
----------------|----------------
![Screenshot_20221212_142725_Brave](https://user-images.githubusercontent.com/2602313/207136719-2f6c45c9-56f2-4706-abdb-12dc7233e6df.jpg) | ![Screenshot_20221212_142735_Brave](https://user-images.githubusercontent.com/2602313/207136735-af8fd88b-d1ea-4a79-976a-6e4ebb89724b.jpg)
