### ISSUE TITLE
Send Tab Build out NFT Info Tooltip

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#26753]
## Description 

Build out the `NFT Info` tooltip for the new `Send` tab

![Screen Shot 2022-11-14 at 1 27 17 PM](https://user-images.githubusercontent.com/40611140/201749097-de7bf24d-67b1-4b6d-a4fb-8115664d9b5e.png)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.47.126 Chromium: 108.0.5359.99 (Official Build) beta (64-bit)
-- | --
Revision | `410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}`
OS | Linux

- Verified steps from [brave/brave-core#15954](https://github.com/brave/brave-core/pull/15954)
- Verified hover over info button on NFT shows NFT details in Tooltip
- Verified clicking on the links opens correct block explorer links for the selected NFT
- Encountered [#27369](https://github.com/brave/brave-browser/issues/27369) & [#27370](https://github.com/brave/brave-browser/issues/27370)

https://user-images.githubusercontent.com/17010094/207584810-a7ede0bf-97a1-44e8-bd2d-183a006bb27d.mp4

---------------------

Verification passed on 

Brave | 1.47.126 Chromium: 108.0.5359.99 (Official Build) beta (64-bit)
-- | --
Revision | `410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#15954](https://github.com/brave/brave-core/pull/15954)
- Verified hover over info button on NFT shows NFT details in Tooltip
- Verified clicking on the links opens correct block explorer links for the selected NFT
- Encountered [#27369](https://github.com/brave/brave-browser/issues/27369) & [#27370](https://github.com/brave/brave-browser/issues/27370)

https://user-images.githubusercontent.com/17010094/207578151-6e7a0794-1abf-4efa-8248-5172e96a12bc.mp4

---------------------

Verification passed on 

Brave | 1.47.126 Chromium: 108.0.5359.99 (Official Build) beta (arm64)
-- | --
Revision | `410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#15954](https://github.com/brave/brave-core/pull/15954)
- Verified hover over info button on NFT shows NFT details in Tooltip
- Verified clicking on the links opens correct block explorer links for the selected NFT
- Encountered [#27369](https://github.com/brave/brave-browser/issues/27369) & [#27370](https://github.com/brave/brave-browser/issues/27370)

https://user-images.githubusercontent.com/17010094/207587883-88e4a5df-c81f-4a33-8e2b-ff804dc97c9b.mov
