### ISSUE TITLE
Text in the first screen (disabled content) feels extremely cramped and uneven

### ISSUE THREAD

**Issue by cezaraugusto** [brave/brave-browser#2675]
carried over from https://github.com/brave/brave-browser/issues/2500

<img src="https://user-images.githubusercontent.com/741836/49891673-ebd4a380-fdfb-11e8-8297-c2ccbd843456.png">

Since this is a design tweak I'm labeling this as `QA/no`

**Comment by rossmoody** [comment]
Updated polish: 
![image](https://user-images.githubusercontent.com/29072694/50314553-16f66d00-0464-11e9-903b-76238ea54164.png)

**Comment by btlechowski** [comment]
Changed the label to QA/Yes after talking to @kjozwiak.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.59.20 Chromium: 72.0.3626.28 (Official Build) beta (64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Windows 7

![image](https://user-images.githubusercontent.com/34715963/50852780-d31ac780-1380-11e9-83a4-979fba0a882a.png)
