### ISSUE TITLE
Fix adding NFT on 1.45.x

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#26755]

**Comment by LaurenWags** [comment]
Closing as this was fixed by https://github.com/brave/brave-core/pull/15942.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.45.127 Chromium: 107.0.5304.110 (Official Build) (64-bit)
-- | --
Revision | `2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}`
OS | Windows 11 Version 22H2 (Build 22621.819)

- Verified able to add Solana NFT similar to Android
- Verified selecting NFT checkbox automatically hides the decimal value input
- Verified still able to add Ethereum NFT and Solana NFT's
- Encountered [#26769](https://github.com/brave/brave-browser/issues/26769)

https://user-images.githubusercontent.com/17010094/201887938-18e8c699-9f25-4b74-80c4-7dba172c4f2f.mp4
