### ISSUE TITLE
Full manual QA pass for snap package to verify major changes

### ISSUE THREAD

**Issue by wknapik** [brave/brave-browser#26754]
Before merging https://github.com/brave/brave-browser-snap/pull/18, we should verify that there is no degradation compared to the currently released snap package.

Please contact @wknapik to rebuild the snap package from the latest stable release before testing, so we can test with the latest stable browser version.

Instructions:
* Connect to VPN
* Download: `https://build-artifacts.brave.com/test-snap-brave-browser/core22/brave_1.47.171_amd64.snap`
* Remove: `sudo snap remove brave`
* Install: `sudo snap install ./brave_1.47.171_amd64.snap --dangerous`
* Connect the `browser-sandbox` plug, which is not autoconnected when installing manually: `sudo snap connect brave:browser-sandbox`
* Run: `snap run brave`

The currently released snap package can be installed via `snap install brave`. It's recommended to do remove+install, instead of just install, when switching between packages.

[Slack thread](https://bravesoftware.slack.com/archives/CG7GV6M7Z/p1667824334275479)

**Comment by wknapik** [comment]
@kjozwiak https://github.com/brave/brave-browser-snap/pull/18 has been waiting for 1.5 months now for merging and is blocked on this. Can we please assign someone?

**Comment by kjozwiak** [comment]
> @kjozwiak [brave/brave-browser-snap#18](https://github.com/brave/brave-browser-snap/pull/18) has been waiting for 1.5 months now for merging and is blocked on this. Can we please assign someone?

We'll have free cycles after `1.47.x` goes out so should be able to tackle this once it's releaed. We basically lost a good amount of the team for ~2-3 weeks in December which means we're a bit behind with `1.47.x` which takes priority over the above. Once we get `1.47.x` out the door, we'll have someone jump on this. VPN has has also taken a lot of recourse, hence that being a higher priority as well.

**Comment by wknapik** [comment]
The package is rebuilt with the latest release channel binary (1.47.171) and the instructions in the issue description are updated to use the updated package. Ready for testing.

**Comment by kjozwiak** [comment]
Completed as per https://github.com/brave/qa-resources/issues/498 👍
