### ISSUE TITLE
Remove Twitter's `t` tracking parameter

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#26756]
Twitter adds a `t` parameter to the query string which appears to be [linked to the Twitter account](https://twitter.com/luca/status/1432782095651385354). Since these could be found in links that people share outside of Twitter, they have the potential for cross-site tracking of users. We should remove them on `*.twitter.com`.

This will require adding support for scoping our existing rules to a specific origin/hostname (or just a URL pattern).

Once we have this support in place, we should scope [the Instagram share ID](https://github.com/brave/brave-core/blob/f30a5171c8aeaab9f402149a5dd11de4e70710d2/browser/net/brave_query_filter.cc#L61) to `*.instagram.com` as well.

**Comment by fmarier** [comment]
Note that there is also an `s` parameter, but that's not a unique ID, it appears for tracking the [source of the share action (i.e. mobile app, desktop, etc.)](https://twitter.com/luca/status/1044150369927012352).

Both `s` and `t` are [removed when using the "copy clean link" feature](https://github.com/brave/adblock-lists/blob/6c11b6664470ca5b2edd59c0a5827d97bb1cb1ad/brave-lists/clean-urls.json#L13-L24).

**Comment by fmarier** [comment]
While the parameter is now filtered out, https://github.com/brave/brave-browser/issues/23742 remains and so a complete fix for Twitter depends on that issue getting fixed.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.47.110 Chromium: 108.0.5359.71 (Official Build) beta (x86_64)
-- | --
Revision | 1e0e3868ee06e91ad636a874420e3ca3ae3756ac-refs/branch-heads/5359@{#1016}
OS | macOS Version 13.1 (Build 22C5059b)

### Steps:
1. opened `https://www.instagram.com/desusbloodyshoes/?igshid=abcdef and confirm that the `igshid` parameter is missing from the query string.
2. opened `https://brave.com/?igshid=abcdef` and confirmed that the `igshid` parameter is present in the query string.
3. opened `https://twitter.com/fmarier/status/1574869891978784769?s=21&t=lkfjeslkfjes&fbclid=1234` and confirmed that neither the `t` nor the `fbclid` parameters were in the URL (but `s=21` was still there).

step 1 | step 2 | step 3
------|--------|-------
<img width="1312" alt="Screenshot 2022-12-03 at 5 35 20 PM" src="https://user-images.githubusercontent.com/387249/205469805-25e4ebf9-d670-410d-b234-5718304293a2.png"> | <img width="1312" alt="Screenshot 2022-12-03 at 5 38 28 PM" src="https://user-images.githubusercontent.com/387249/205469841-c6ddc5c7-bd43-48f0-88a5-90d7fa34b8b8.png"> | <img width="1312" alt="Screenshot 2022-12-03 at 5 40 09 PM" src="https://user-images.githubusercontent.com/387249/205469878-e632b7e5-862e-4a9d-8856-71ee8e6d2873.png">

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Vivo X70 Pro version 12` running `Bravemonoarmx64.apk_1.47.165`

### Steps:
1. opened `https://www.instagram.com/desusbloodyshoes/?igshid=abcdef and confirm that the `igshid` parameter is missing from the query string.
2. opened `https://brave.com/?igshid=abcdef` and confirmed that the `igshid` parameter is present in the query string.
3. opened `https://twitter.com/fmarier/status/1574869891978784769?s=21&t=lkfjeslkfjes&fbclid=1234` and confirmed that neither the `t` nor the `fbclid` parameters were in the URL (but `s=21` was still there).

step 1 | step 2 | step 3
------|--------|-------
![image](https://user-images.githubusercontent.com/38657976/211309378-17413363-ef7f-43fc-95a9-7f997a2b66c3.png) | ![image](https://user-images.githubusercontent.com/38657976/211309860-62f9b8d6-7ce8-46fe-9a5d-b4b7e0937cf4.png) | ![image](https://user-images.githubusercontent.com/38657976/211310377-8f395e52-cb3c-45ff-b415-c07126cc1d90.png)

**Comment by bsclifton** [comment]
@issuant no, this should not be reversed. The actual list of params is configurable and is downloaded as part of `Brave Local Data Updater` in component updater, if I remember correctly. You can view the component registration and version in brave://components/

On desktop, you can go into your profile directory and find this component and open/inspect the `clean-urls.json` file. The section for Twitter/X looks like this:

```
{
        "include": [
            "*://*.twitter.com/*",
            "*://*.x.com/*"
        ],
        "exclude": [
            "*://*.twitter.com/i/redirect?*",
            "*://*.x.com/i/redirect?*"
        ],
        "params": [
            "cxt",
            "ref_src",
            "ref_url",
            "s",
            "t"
        ]
    },
```

**Comment by fmarier** [comment]
We had to remove it from the query filter list (https://github.com/brave/brave-core/pull/16968) due to webcompat problems. But like @bsclifton said, it's still removed if you use the copy-clean-link feature.

**Comment by fmarier** [comment]
It's the same on mobile and desktop: the `t` parameter is cleaned during copy clean link. Automatically removing it would break some pages on Twitter, which is why we stopped doing that.
