### ISSUE TITLE
NFT checkbox should only be shown when Solana Network is selected

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#26769]
## Description 

NFT checkbox should only be shown when Solana Network is selected

## Steps to Reproduce

   1. Install 1.45.127 
   2. Go to `brave://wallet/crypto/portfolio/add-asset` 
   3. NFT checkbox is shown always

## Actual result:

NFT checkbox should only be shown when Solana Network is selected

## Expected result:
Should only show NFT checkbox when Solana network is selected in network dropdown

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.45.127 Chromium: 107.0.5304.110 (Official Build) (64-bit)
-- | --
Revision | `2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}`
OS | Windows 11 Version 22H2 (Build 22621.819)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Not implemented UI is different
- Can you reproduce this issue with the nightly channel? Not implemented UI is different

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @muliswilliam @yrliou @jamesmudgett

**Comment by muliswilliam** [comment]
From the discussion on [Slack](https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1668506436687849), we are not going to work on this since we are close to releasing `1.46.x` which does not have the NFT checkbox.
