### ISSUE TITLE
Assign Copy keyboard shortcut to "copy clean link"

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#26761]
Users have been asking for "copy clean URLs" to be the default so that they don't have to remember to use it when copying from the URL bar.

We should change the keyboard shortcut:
![copy-shortcut](https://user-images.githubusercontent.com/167821/201786309-5f74a75e-9ff1-4536-a339-2e47cfe4e9c0.png)

**Comment by spylogsster** [comment]
For Mac App menu part created another issue https://github.com/brave/brave-browser/issues/27902

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.49.96 Chromium: 110.0.5481.77 (Official Build) beta (x86_64)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | macOS Version 11.7.3 (Build 20G1116)

### Case 1: Copy URL

### Case 2: Copy text

### Case 3: No selection

**Comment by MadhaviSeelam** [comment]
Verification `In progess` using
```
Brave | 1.49.106 Chromium: 110.0.5481.104 (Official Build) beta (64-bit)
-- | --
Revision | 46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}
OS | Windows 11 Version 21H2 (Build 22000.1574)
```
### Case 1: Copy Clean Link - `PASSED`

1. installed `1.49.106`
2. launched Brave
3. loaded `https://twitter.com/fmarier/status/1574869891978784769?s=21&t=lkfjeslkfjes&fbclid=1234`
4. selected the URL
5. pressed `command` +`C` to copy
6. pressed `command` + `V` to paste

#### Confirmed `Copy Clean Link` was used, as the pasted URL is `https://twitter.com/fmarier/status/1574869891978784769?fbclid=1234` (removed `s=21`, and `t=lkf...` params)

`Copy Clean Link` shortcut `command` + `C` used | `command` + `v`
---------|---------
<img width="946" alt="image" src="https://user-images.githubusercontent.com/98358127/220454679-376d1a6a-6da3-4fe7-bdf3-d81292ff6dfc.png">|<img width="945" alt="image" src="https://user-images.githubusercontent.com/98358127/220454894-33cede84-f20d-45fd-b7f0-5cc91ea7a459.png">

### Case 2: Copy item from context menu should copy selected url without changes.  - `PASSED`

1. installed `1.49.106`
2. launched Brave
3. loaded `https://twitter.com/fmarier/status/1574869891978784769?s=21&t=lkfjeslkfjes&fbclid=1234`
4. selected the URL
5. select `Copy` from context menu
6. pressed `command` + `V` to paste

Confirmed selected url is pasted without any changes or strip any parameters in the URL `https://twitter.com/fmarier/status/1574869891978784769?s=21&t=lkfjeslkfjes' 

`Copy` from context menu | `Paste` from context menu
-----|------
<img width="956" alt="image" src="https://user-images.githubusercontent.com/98358127/220456382-6092daef-c81a-4cd1-96c9-b0aea80c740f.png">|<img width="939" alt="image" src="https://user-images.githubusercontent.com/98358127/220461357-2e54f37b-5fab-4d46-87e4-8c0d412cb4a0.png">

### Case 3: Copy text - `PASSED`

1. new profile
2. launched Brave
3. loaded `https://twitter.com/fmarier/status/1574869891978784769?s=21&t=lkfjeslkfjes&fbclid=1234`
4. selected a random substring of text from the URL `/157486989197878476`
5. pressed `command` + `C` to copy
6. pressed `command` + `V` to paste

#### Confirmed regular `copy` and `paste` operations for non-URL text pasted `/157486989197878476`

Copy shortcut `command` + `C` used | `command` + `V`
---------------------------------------|-------------------
<img width="945" alt="image" src="https://user-images.githubusercontent.com/98358127/220457275-8e9bcc64-11dc-4a48-8960-c69a8c5b60e4.png">|<img width="946" alt="image" src="https://user-images.githubusercontent.com/98358127/220457242-cb6856a6-c707-4e5d-a282-e8e5c66317f7.png">

### Case 4: Copy clean link should not be visible for selected text- `PASSED`

1. new profile
2. launched Brave
3. loaded `https://twitter.com/fmarier/status/1574869891978784769?s=21&t=lkfjeslkfjes&fbclid=1234`
4. selected a random substring of text from the URL `/157486989197878476`
5. right click to open context menu

#### Confirmed context menu shows default hotkey Ctrl+c for Copy item and no `Copy clean link` is available for non-URL text pasted `/157486989197878476`

<img width="947" alt="image" src="https://user-images.githubusercontent.com/98358127/220460132-2890ead9-2750-435e-8d1a-3ce5701c5ccb.png">

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.49.118 Chromium: 111.0.5563.50 (Official Build) (64-bit) 
-- | --
Revision | 39f3dfc5023fe60997adc4f6cf5439cfa3e6968a-refs/branch-heads/5563@{#903}
OS | Ubuntu 18.04 LTS

Does not work on Linux. Logged https://github.com/brave/brave-browser/issues/28891

**Comment by rbk-sense** [comment]
is there an easy way to map cmd + c back to copy?
this change is the opposite of helpful for me

**Comment by dinhanhthi** [comment]
In the version 1.56.14, I cannot use `cmd+C` to copy the URL / selection on the address bar. Every time I use `cmd+C`, it opens the Inspect Element panel. It's annoying!!! The older version doesn't have this issue!
