### ISSUE TITLE
Children of Sync device type modal should use the same modal

### ISSUE THREAD

**Issue by cezaraugusto** [brave/brave-browser#2677]
carried over from https://github.com/brave/brave-browser/issues/2500

Device type modal opens a new modal every time user choose either desktop or mobile versions. This is bad UI and should be fixed using only 1 modal with dynamic content.

Test Plan:

1. Open brave://sync
2. Click "Start a new sync chain"
3. Click "Phone/Tablet"
4. Click "Enter code words instead..."
5. Click "Use my camera instead..."
6. Click "ok"

**What happens:** You have to click "ok" several times before modal is closed
**What should happen:** Clicking "ok" should close all dialogs

**Comment by cezaraugusto** [comment]
setting this as QA/no since this is expected behavior and didn't add new features

**Comment by btlechowski** [comment]
Changed the label to QA/Yes after talking to @kjozwiak.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.59.20 Chromium: 72.0.3626.28 (Official Build) beta (64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Windows 7

Used test plan from https://github.com/brave/brave-core/pull/1193. For convenience I included the test plan below:
```
Fix Children of Sync device type modal should use the same modal

Test plan
1. Clear profile
2. Click "Start a New Sync Chain"
3. Click "Tablet or Phone"
4. Keep toggling between "View Sync Code" and "View QR Code"
5. Trying to close it closes them all at once

Repeat the same process with a sync chain set up by clicking "Add New Device" in the devices table screen.
```
