### ISSUE TITLE
Invalid Sync code error behavior

### ISSUE THREAD

**Issue by rossmoody** [brave/brave-browser#2678]
If I enter the wrong sync code on my target computer I get a notification which is awesome, but when i click the button it drops me completely back to the main screen. This should probably just put me back in the code word form as losing 24 typed words is pretty frustrating to users.

<img width="801" alt="screen shot 2018-12-20 at 3 00 24 pm" src="https://user-images.githubusercontent.com/29072694/50315551-16f86c00-0468-11e9-9821-c58c9ab514ee.png">

**Comment by cezaraugusto** [comment]
thanks Ross, this was addressed in https://github.com/brave/brave-browser/issues/2541. closing as dupe

**Comment by rossmoody** [comment]
doh! ty
