### ISSUE TITLE
Client code sometimes fails to retry VPN credentials fetching

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#26780]
## Description 

Client code sometimes fails to retry VPN credentials fetching

NOTE: This is a follow-on issue to https://github.com/brave/brave-browser/issues/26746

## Steps to Reproduce

 0. delete any `BraveVPN` OS-configs, first
   1. install `1.47.74`
   2. launch Brave using `--vmodule="*/skus/*"=2 --enable-logging=stdrr --v=1`
   3. click `Maybe later`
   4. click `Skip welcome tour`
   5. open `brave://flags`
   6. set `brave://flags/#brave-vpn` to `Enabled`
   7. click `Relaunch` (if you want to retain logging, `CTRL+C` and relaunch from `Terminal`/console
   8. click `No thanks` on the `Tired of cookie consent notices?` dialog
   9. load `account.bravesoftware.com`
   10. enter staging credentials from 1Password
   11. enter a unique email address such as "`unique99@mailinator.com`" or similar
   12. click `Get login link`
   13. open the `Log in to your Brave Pre...` email (`https://www.mailinator.com/v4/public/inboxes.jsp?to=unique99` in the above case)
   14. click on either the `Log in to Brave` button -or- the link below it
   15. click `Browse plans` on `https://account.bravesoftware.com/account/`
   16. scroll down
   17. click on `Buy now` beneath `Brave VPN Subscription`
   18. complete the Stripe checkout using `https://stripe.com/docs/testing#testing-interactively`
   19. if you're able to, click on the `VPN` button in the browser toolbar, and attempt to add and connect to the `BraveVPN` config

## Actual result:

<img width="1312" alt="Screen Shot 2022-11-15 at 8 28 06 AM" src="https://user-images.githubusercontent.com/387249/201974067-3cbd375e-0e88-45ce-b9c8-136f86f0fcce.png">

## Expected result:

<img width="1312" alt="Screen Shot 2022-11-15 at 7 24 53 AM" src="https://user-images.githubusercontent.com/387249/201974146-68273f0a-abf7-4029-bb39-eeaf649f1f6e.png">

## Reproduces how often: 

~30% of the time (# of runs)

## Brave version (brave://version info)

Brave | 1.47.74 Chromium: 108.0.5359.40 (Official Build) nightly (x86_64)
-- | --
Revision | 280b5fcaab3e877562b06cfaf2eb51121e13c3b9-refs/branch-heads/5359@{#689}
OS | macOS Version 11.7.1 (Build 20G918)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

/cc @mattmcalister @rebron @bsclifton @husobee @evq @AlanBreck https://github.com/orgs/brave/teams/qa-team

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
Brave | 1.46.117 Chromium: 107.0.5304.110 (Official Build) beta (64-bit)
-- | --
Revision | 2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}
OS | Windows 10 Version 21H2 (Build 19044.2251)

```

Example | Example
---------|-----------
![image](https://user-images.githubusercontent.com/38657976/202663086-c341d3b0-d3d6-443d-9c35-a69e26f8ee1e.png) | ![image](https://user-images.githubusercontent.com/38657976/202663387-ab78fd03-5340-4dd9-8616-f84612ae5dbd.png)

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.46.122 Chromium: 108.0.5359.48 (Official Build) beta (x86_64)
-- | --
Revision | 18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}
OS | macOS Version 11.7.1 (Build 20G918)

### Steps:
1. deleted the prior `BraveVPN` OS-config
2. installed `1.46.122`
3. launched Brave using `--vmodule="*/skus/*"=2 --enable-logging=stdrr --v=1`
4. click `Maybe later`
5. click `Skip welcome tour`
6. open `brave://flags`
7. set `brave://flags/#brave-vpn` to `Enabled`
8. click `Relaunch`
9. click `No thanks` on the `Tired of cookie consent notices?` dialog
10. load `account.bravesoftware.com`
11. enter staging credentials from `1Password`
12. enter `issue26780@mailinator.com`
13. click `Get login link`
14. open the `Log in to your Brave Pre...` email (`https://www.mailinator.com/v4/public/inboxes.jsp?to=issue26780` in the above case)
15. clicked on the `Log in to Brave` button
16. clicked `Browse plans` on `https://account.bravesoftware.com/account/`
17. scrolled down
18. clicked on `Buy now` beneath `Brave VPN Subscription`
19. completed the Stripe checkout using `https://stripe.com/docs/testing#testing-interactively`
20. clicked on the `VPN` button in the browser toolbar, and attempt to add and connected to the `BraveVPN` config

#### Confirmed I could purchase, configure, and connect to `BraveVPN`

example | example | example
---------|---------|---------
<img width="1373" alt="Screen Shot 2022-11-22 at 1 19 16 PM" src="https://user-images.githubusercontent.com/387249/203423335-5cdc8b00-6162-4902-8975-465e6e5ac40d.png"> | <img width="1261" alt="Screen Shot 2022-11-22 at 1 19 28 PM" src="https://user-images.githubusercontent.com/387249/203423343-d7a0db2d-08ef-4f81-9a6d-fae8440e138d.png"> | <img width="1373" alt="Screen Shot 2022-11-22 at 1 19 43 PM" src="https://user-images.githubusercontent.com/387249/203423346-5335af13-3bc9-4c06-90ed-3216f3a1fe41.png">
