### ISSUE TITLE
Windows 10 leaks DNS when using VPN by sending DNS to all network interfaces

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#26787]
## Test plan
**NOTE:** To experience the leak, you'll need to relay DNS through your local network. On the adapter you're testing with (ex: WiFi or the physical ethernet) you'll want to have DNS set by DHCP. This is the default when you're on a local area network (ex: your default gateway is set as your DNS server). But if you explicitly set DNS to a public IP (ex: 1.1.1.1, 8.8.4.4), you won't reproduce the leak

### Happy path test plan

0. DoH is not enabled in the browser
1. Fresh profile
2. Enable VPN / purchase VPN
3. Connect to a VPN server
4. You should get a modal warning that DoH was enabled
5. Visit https://browserleaks.com/dns and ensure your ISP is not in the results

### Test that `Do not warn me about this anymore` works
0. DoH is not enabled in the browser
1. Happy path test plan
2. When modal is presented, check the box for `Do not warn me about this anymore`
3. Disconnect VPN
4. Connect to VPN again
5. Modal should not show

### User enables DoH and connects to VPN
1. Fresh profile
2. Visit brave://settings/security and under `Use secure DNS` pick `With Cloudflare (1.1.1.1)`
    ![image](https://user-images.githubusercontent.com/4733304/203657922-266eb7d5-c963-4d3b-bbbe-c13ebef7a759.png)
3. Enable VPN / purchase VPN
4. Connect to a VPN server
5. You should not get a modal - because you already had DoH enabled
6. Reload brave://settings/security
7. Verify your settings are not overwritten; you should be able to change to Google (Public DNS)
8. Change setting for `Use secure DNS` to `With your current service provider`
9. You should get a warning modal

### When group policy can override the values
1. Open `regedit.exe`
2. Navigate to `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\`
3. Create the key (folders) `BraveSoftware\Brave\` if they don't already exist

#### When `DnsOverHttpsMode` is overridden
Documentation at https://chromeenterprise.google/policies/#DnsOverHttpsMode for reference
1. Create a `REG_SZ` (string value) key `DnsOverHttpsMode` in the root and set the value to `off`
2. Visit brave://settings/security and the `Use secure DNS` setting should NOT be editable (you'll see a house icon)
3. Try the happy path test plan
4. It should fail and show a modal explaining how group policy is blocking change to secure DNS
5. There is a `Do not warn me about this again.` setting. We can verify this works

#### When `DnsOverHttpsMode` and `DnsOverHttpsTemplates` are overridden
Documentation at https://chromeenterprise.google/policies/#DnsOverHttpsTemplates for reference
1. Create a `REG_SZ` (string value) key `DnsOverHttpsMode` in the root and set the value to `secure`
2. Create a `REG_SZ` (string value) key `DnsOverHttpsTemplates` in the root and set the value to `https://chrome.cloudflare-dns.com/dns-query`
3. Visit brave://settings/security and the `Use secure DNS` setting should NOT be editable (you'll see a house icon)
4. Try the happy path test plan
6. No warning should be shown - you're already using DNS over HTTPS

More information at https://github.com/brave/brave-core/pull/15989

## Description 
Re-opened issue for https://github.com/brave/brave-browser/issues/22163

We should re-introduce the solution presented in https://github.com/brave/brave-core/pull/13434. This will stop the leak inside the Brave Browser. Long term, we'll have a different solution - see https://github.com/brave/brave-browser/issues/25489

**Comment by LaurenWags** [comment]
labelled as `QA/Blocked` as an uplift to 1.47.x is required

**Comment by kjozwiak** [comment]
The above requires `1.47.130` or higher for `1.47.x` 👍

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using 
```
Brave | 1.47.131 Chromium: 108.0.5359.128 (Official Build) beta (64-bit)
-- | --
Revision | 1cd27afdb8e5d057070c0961e04c490d2aca1aa0-refs/branch-heads/5359@{#1185}
OS | Windows 11 Version 21H2 (Build 22000.1335)
```
### "Happiest of paths" - `PASSED`
<details>

1. installed `1.47.131
2. launched Brave
3. opened `brave://flags`
4. set `brave://flags/#brave-vpn` to `Enabled`
5. clicked `Relaunch`
6. loaded `account.bravesoftware.com`
7. entered basic-auth credentials
8. entered `test1dvpn1215@mailinator.com` and clicked `Get login link`
9. clicked `Log in to Brave` from the resulting email
10. clicked on `Browse plans`
11. scrolled down to `Brave VPN Subscription` and clicked `Buy now`
12. filled out Stripe and clicked `Subscribe`
13. connected to `BraveVPN`
14. confirmed I got the `DoH` warning modal
15. clicked `OK`
16. loaded `https://browserleaks.com/dns`

#### Confirmed only `Cloudflare` DNS resolvers were shown, and my local ISP DNS resolvers are not shown.

step 4|step 14 | result
--------|--------|------
<img width="454" alt="image" src="https://user-images.githubusercontent.com/98358127/207987227-8de749f8-6712-452e-90f8-efb558e5898b.png">|<img width="455" alt="image" src="https://user-images.githubusercontent.com/98358127/207987564-0ce9204a-d0bd-48de-b5ab-1928d5022d44.png">|<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/207987659-956a730d-5338-4a71-953d-b56b76a62c23.png">
</details>

### Ensure `Do not warn me about this anymore` works - `PASSED`
<details>

Pre-requisite ran `Happiest of paths` test

1. continued from `Happiest of paths` test
2. clicked on `Do not warn me about this anymore`
3. disconnected from `BraveVPN` via the Windows settings>>Network&Internet panel
4. reconnected to `BraveVPN` via the browser's `VPN` button toggle
5. confirm the modal doesn't show again

#### Confirmed no more DoH warning modal(s)

step 2|step 3|step5
---|----|---
<img width="954" alt="image" src="https://user-images.githubusercontent.com/98358127/207991769-1c1d0735-869c-44a6-a7ca-8580b3805137.png">
<img width="178" alt="image" src="https://user-images.githubusercontent.com/98358127/207991815-fb6dea45-b71a-4211-9445-1eca7b29c421.png">
<img width="955" alt="image" src="https://user-images.githubusercontent.com/98358127/207991853-3cbac533-c542-49c5-82ee-9f4ac004fb18.png">

**Comment by LaurenWags** [comment]
Removed `QA Pass-Win64` as this was only verified on Win 11 but needs Win 10 verification also.

cc @GeetaSarvadnya @stephendonner

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS  on

```

Brave | 1.47.164 Chromium: 109.0.5414.74 (Official Build) (64-bit)
-- | --
Revision | e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}
OS | Windows 10 Version 21H2 (Build 19044.2364)

```
#### Test Case 1:  "Happiest of paths" - `PASSED`
<details>

1. installed `1.47.131
2. launched Brave
3. opened `brave://flags`
4. set `brave://flags/#brave-vpn` to `Enabled`
5. leave `brave://flags/#brave-vpn-dns` to `Default`
6. clicked `Relaunch`
7. loaded `account.bravesoftware.com`
8. entered basic-auth credentials
9. entered `test1dvpn1215@mailinator.com` and clicked `Get login link`
10. clicked `Log in to Brave` from the resulting email
11. clicked on `Browse plans`
12. scrolled down to `Brave VPN Subscription` and clicked `Buy now`
13. filled out Stripe and clicked `Subscribe`
14. connected to `BraveVPN`
15. confirmed I got the `DoH` warning modal
16. clicked `OK`
17. loaded `https://browserleaks.com/dns`

#### Confirmed only `Cloudflare` DNS resolvers were shown, and my local ISP DNS resolvers are not shown.

step 4-5|step 14 | result
--------|--------|------

</details>

#### Test Case 2:  Ensure `Do not warn me about this anymore` works - `PASSED`
<details>

Pre-requisite ran `Happiest of paths` test

1. continued from `Happiest of paths` test
      - set `brave://flags/#brave-vpn` to `Enabled`
      - leave brave://flags/#brave-vpn-dns to `Default`
      - confirmed I got the DoH warning modal
2. clicked on `Do not warn me about this anymore`
3. disconnected from `BraveVPN` via the Windows settings>>Network&Internet panel
4. reconnected to `BraveVPN` via the browser's `VPN` button toggle

#### Confirmed no more DoH warning modal(s)

step 1|step 2|step 3|result
---|----|---|----

</details>

#### Test Case 3:  User enables DoH and connects to VPN - `PASSED`
<details>

1. new profile
2.  set `brave://flags/#brave-vpn` to `Enabled`
3. open `brave://settings/security` 
4. navigate to `Use secure DNS` and select `With Cloudflare (1.1.1.1)`
5. purchased, enabled, and connected to `BraveVPN` (see steps above)
6. confirmed no `DoH` warning modal
7. reloaded `brave://settings/security`
8. confirmed `DoH` settings were not overwritten and the toggle is enabled and collapsed 
9. disconnect VPN
10. open `brave://settings/security` 
11. navigate to `Use secure DNS` and change to `Google (Public DNS)`  and connect to VPN
12. confirmed my `DoH` settings were not overwritten and the toggle is collapsed and enabled
13. changed settings for `Use secure DNS` to `With your current service provider`
14. connected to `BraveVPN`
15. confirmed I got the `DoH` warning modal

#### Confirmed whenever I connected to `BraveVPN`, `Use secure DNS` was automatically collapsed and enabled, the DoH DNS-leak warning dialog is shown

step 2|step 4|step 5-6|step 8|step 10-11|step 12|step 13|step 15
-----|-----|-----|----|----|----|------|-----

</details>

#### Test Case 4: Group policy - `PASSED`
<details>

#### Case 1:  `DnsOverHttpsMode` is off by policy - `PASSED`
<details>

1. new profile
2. launch Brave
3. open `brave://settings/security` in a new-tab
4. navigate to `Use secure DNS` and `With your current service provider` option is selected as default
5. close Brave
6. opened `regedit.exe`
7. elevated user permissions
8. navigated to `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\`
9. created the key (folders) BraveSoftware\Brave\
10. context-clicked the `Brave` branch in the registry tree, and chose `New` -> `String Value`
11. entered `DnsOverHttpsMode`
12. set its value to `off`
13. close the `Registry Editor`
14. relaunch Brave and open `brave://settings/security`
15. confirmed the `Use secure DNS` setting should not be editable (shows a "house" icon - managed via policy)
16. create a new account (login to existing vpn account follow `Case 1:  "Happiest of paths"`)
17.  enabled VPN and confirmed the `Secure DNS is disabled by your...` warning dialog text
18. clicked on `OK` to dismiss

#### Confirmed while connected to `BraveVPN` with the above policy, both the DoH warning dialog and the tooltip + home icon, in the `brave://settings/security` page

step 4|step 6-12|steps 15|step 17
----|----|--------|------


</details>

#### Case 2: `DnsOverHttpsMode` and `DnsOverHttpsTemplates` are overriden  in the policy- `PASSED`
<details>

1. continue from above case `When `DnsOverHttpsMode` is overriden`
      - set the value of `DnsOverHttpsMode` to `secure` (from `off`)
      - disconnect VPN and close the Brave 
2. open `Registry editor` 
3. navigate to `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\BraveSoftware\Brave\`
4. create a `string` key of `DnsOverHttpsTemplates` and set its value to `https://chrome.cloudflare-dns.com/dns-query`
5. close the Registry editor
6. relaunch Brave
7. open `brave://settings/security` and confirmed the `Use secure DNS` setting is disabled (with the house icon)
8. confirm no `DoH` warning dialogs when successfully reconnecting to `BraveVPN`

step 4 | step 7 | step 8
--------|-------|--------


</details>
</details>

#### Test Case 5: Security and Privacy - `PASSED`
<details>

#### Case 1:  DNS-over-HTTPs (DOH) - `PASSED`
<details>

1. continued from Case 1: `Happiest of paths` test
2. connect to `BraveVPN`
2. click `Ok` on the DoH DNS leak warning dialog
4. load `browserleaks.com/dns`
5. confirm you see only `Cloudflare` DNS-server IPs

VPN not enabled|DoH warning dialog | browserleaks.com/dns
-----------------------|------------|-------------


</details>

#### Case 2: DNS leak (ISP) - `PASSED`
<details>

1. continue from Case 1: 
    - Brave VPN is connected to
    - load `https://browserleaks.com/dns`
    - confirm local ISP DNS resolvers aren't shown (they should be from the connected region, Cloudflare)
2. disconnect from `BraveVPN`
3. reload `https://browserleaks.com/dns`
4. confirm local ISP DNS resolvers *are* shown

step 1 | step 4 
-------|--------

</details>

#### Tor - `PASSED`
<details>

1. continue from Case 1: 
    - Brave VPN is connected to
    - load `https://browserleaks.com/dns`
    - confirm local ISP DNS resolvers aren't shown (they should be from the connected region, Cloudflare)
2. click Ok on DoH warning dialog
1. connect to `BraveVPN`
2. open a `New Private window with Tor`
3. load `check.torproject.org`
4. click to `Continue to site`
5. ensure you see `Congratulations.  This browser is configured to use Tor.`

ex1|ex2
---|----


</details>

#### Torrent (via `WebTorrents` support) - `PASSED`
<details>

1. disconnect from a working `BraveVPN` setup
2. load `https://ipleak.net`
3. click on `Activate` under `Torrent Address detection`
4. click on `this Magnet Link` (it'll open in a new window)
5. reload the URL
6. click on `Start Torrent`
7. return to the `https://ipleak.net` tab
8. confirm that you see your public (local ISP) IP address
9. connect to `BraveVPN`
10. click `OK` on the DoH leak warning dialog
11. `shift` + `reload` the page (to clear cache)
12. repeat steps 3-7
13. confirm you now see the appropriate VPN IP address (for the connected region)
14. switch to another region (for bonus points!)

step 2|step|step 6|step 8|step 10|step 13|step 14
-----|------|-----|-----|-----|-----|-----


</details>
