### ISSUE TITLE
Send Tab Build out Account Selector 

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#26784]
## Description 

Build out the `Account Selector` component for the new `Send` tab

![Screen Shot 2022-11-14 at 1 28 03 PM](https://user-images.githubusercontent.com/40611140/202012606-1b33524c-769d-4e9d-93d9-bdeddd31d76a.png)

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/26918#issuecomment-1350449077
