### ISSUE TITLE
Wallet slowness

### ISSUE THREAD

**Issue by krijnsent** [brave/brave-browser#26782]
## Description 
Opening the Brave wallet takes ages & sucks all resources into it. I have 4 eth addresses and 3 imported eth addresses in my brave wallet. I also added about 10 custom ERC-20 tokens to the list. I just opened my wallet (as a page, not by clicking the wallet icon, that's even slower) and immediately my CPU spiked to 20%, my fan started blowing and only after 5 minutes (no other processes running) all info had loaded - prices, amounts, the whole thing. Still, when I want to open a new tab in my Brave browser that hardly loads (tried with some Github issues).

## Steps to Reproduce
   1. Set up multiple wallets with assets in them
   2. Also set up multiple ERC-20 tokens
   3. Start brave 
   4. start the wallet and log in - the wallet page takes ages to load and starting another tab is virtually impossible, even after it has loaded properly

## Actual result:
A lot of spinners, the last time it took me 5 minutes to simply load my wallets. Haven't even gotten to adding some NFTs.

## Expected result:
My main goal for the brave wallet is a) to get an overview of my tokens & coins and b) transfer something every now and then. I have no idea what API calls are made in the background, but it's taking a) too many resources and b) taking way too long. Automatically giving me a year of historical prices is not needed.

## Reproduces how often: 
Always, almost switched back to Metamask for Edge...

## Brave version (brave://version info)
1.45.123 Chromium: 107.0.5304.110 (Officiële build) (64-bits)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.68.85 Chromium: 126.0.6478.40 (Official Build) beta (64-bit)
-- | --
Revision | 8e76a669cf78bdfa933c8d569460092a01166588
OS | Windows 11 Version 23H2 (Build 22631.3672)

- Verified steps from issue description
- Verified loading assets doesn't take time and work fine
- Verified loading NFTs doesn't take a long time and works fine
