### ISSUE TITLE
`Brave Wallet will not insert window.ethereum because it already exists!` console warning is shown for all pages

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#26790]
![Screenshot from 2022-11-15 11-40-38](https://user-images.githubusercontent.com/4730197/202036238-657b7fd6-9d98-4973-b880-596db2c04aa4.png)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.47.164 Chromium: 109.0.5414.74 (Official Build) (64-bit)
-- | --
Revision | `e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}`
OS | Linux

- Verified steps from [brave/brave-core#15958](https://github.com/brave/brave-core/pull/15958)
- Verified no console warnings are shown when default provider is set to `Brave Wallet`
- Verified no console warnings are shown when default provider is set to `Brave Wallet (Prefer extensions)`

---------------------

Verification passed on 

Brave | 1.47.164 Chromium: 109.0.5414.74 (Official Build) (64-bit)
-- | --
Revision | `e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#15958](https://github.com/brave/brave-core/pull/15958)
- Verified no console warnings are shown when default provider is set to `Brave Wallet`
- Verified no console warnings are shown when default provider is set to `Brave Wallet (Prefer extensions)`

---------------------

Verification passed on 

Brave | 1.47.164 Chromium: 109.0.5414.74 (Official Build) (arm64)
-- | --
Revision | `e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#15958](https://github.com/brave/brave-core/pull/15958)
- Verified no console warnings are shown when default provider is set to `Brave Wallet`
- Verified no console warnings are shown when default provider is set to `Brave Wallet (Prefer extensions)`
