### ISSUE TITLE
[Android] Update vpn cta

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#26791]
## Description
We recently received some feedback for improving subscription rates. One of the ideas was the VPN CTA. The suggestion was to emphasize "FREE" more as this usually helps increase conversion.

<img width="300" alt="Screen Shot 2022-11-15 at 2 30 44 PM" src="https://user-images.githubusercontent.com/7606853/202038832-6611508d-322e-4a93-a118-70bd5ceb8897.png">

## Requirements
1. Change the VPN purchase flow to a two step:

```
1. Tap monthly or yearly (yearly selected by default)
2. Tap "TRY 7 DAYS FREE" button (this is a new button - it does not currently exist)
```

2. Bold and underline the "Try free for 7 days" text in the small print copy.

3. Make the one year option the first option (put it above the monthly option).

### Design
https://www.figma.com/file/PqLTp3DnANLQMM1XzaChqZ/Mobile-VPN?type=design&node-id=3758%3A46424&mode=design&t=5MSv01bJ3yKu1SlR-1

**Comment by anthonypkeane** [comment]
@timchilds can you pls make an iOS issue for this too, same logic. Thanks

**Comment by deeppandya** [comment]
@timchilds is this issue ready to work on ?

**Comment by hffvld** [comment]
### Inprogress...

Verified on `Pixel 2 XL`, `Galaxy Tab S8` and `Pixel 7` using version(s):
```
Device/OS: 
- Pixel 2 XL / taimen-user  8.1.0 OPM2.171026.006.H1 release-keys
- Galaxy Tab S8 / gts8wifixx-user 13 TP1A.220624.014 release-keys
- Pixel 7 / panther_beta-user 14 AP11.231215.009 release-keys
Brave build: 1.63.146
Chromium: 121.0.6167.139 (Official Build) beta (64-bit) 
```

OR

Filed follow-up issue #
---------------------------

**STEPS:**
1. Fresh install and launch Brave
2. Tree-dot menu > Brave VPN > *Verify*
3. Select `One Year` subscription > Try for Free for 7 Days
4. Purchase a subscription and Enable a VPN > *Verify*
5. Cancel subscription and repeat Steps 2 - 4, but use `Monthly subscription` this time > *Verify*

**ACTUAL RESULTS:**
- Verified that the yearly VPN subscription is selected by default
- Verified that the early VPN subscription is on top
- Verified that the user can purchase both subscriptions and enable VPN
- Verified that tapping on `Try for Free for 7 Days` CTA will advance the user in the flow
- Verify that `free 7-day trial` text must be underlined, but observe that it's not underlined right now

---------------------------

*Pixel 2 XL*

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/08881c2d-d187-4367-842c-0fd457184e6b) | ![2](https://github.com/brave/brave-browser/assets/128532965/6970c9bd-5760-48a5-87f8-91b4dedfce02) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/31150e9b-e8e1-461e-bcdb-1c8a2ca93944) | ![2](https://github.com/brave/brave-browser/assets/128532965/39220bfd-df0f-4c76-9c2c-ce943572e40a) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/6d0b64f1-4d35-4417-baca-6c45b1d7f1c9) | ![2](https://github.com/brave/brave-browser/assets/128532965/628a22de-1c39-4774-ae1f-4f55a6656926) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/54dc2db9-5f6d-4770-87d7-4986ccda4491) | ![2](https://github.com/brave/brave-browser/assets/128532965/e6eedbb0-0a3e-4db4-8de6-e2a59887d7a4) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/e1caecf0-5ec3-4bbb-aa2b-85a1d2409022) | ![2](https://github.com/brave/brave-browser/assets/128532965/897d28ad-2930-4b73-8779-4558198897bb) |

*Galaxy Tab S8*

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1]() | ![2]() | ![3]() | ![4]() |
| ![1]() | ![2]() | ![3]() | ![4]() |
| ![1]() | ![2]() | ![3]() | ![4]() |
| ![1]() | ![2]() | ![3]() | ![4]() |
| ![1]() | ![2]() | ![3]() | ![4]() |
| ![1]() | ![2]() | ![3]() | ![4]() |

*Pixel 7*
