### ISSUE TITLE
Move swap error parsing to backend

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#26796]
Need for https://github.com/brave/brave-browser/issues/24582 and also to reduce copy-paste between android ui and wallet ui

**Comment by srirambv** [comment]
Verification passed on Lenovo Tab with Android 12 running 1.48.157 x64 build
- Verified steps from [brave/brave-core#16010](https://github.com/brave/brave-core/pull/16010)
- Verified Swaps on Ethereum work fine
- Encountered [#28307](https://github.com/brave/brave-browser/issues/28307)
