### ISSUE TITLE
Enable solana dapps conditionally

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#26804]
## Description 
Enable solana dapps conditionally to address https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1668552358419659

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.46.127 x64 build
- Verified Solana Dapp support is not available by default 
- Verified enabling Solana Provider support still doesn't enable Dapp support

https://user-images.githubusercontent.com/17010094/204013667-1b1436ad-e90e-4e5d-aa9f-80fed03a406c.mp4
