### ISSUE TITLE
Add Brave Ads status header to search.brave.com fetch/xhr requests

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#26812]
Also need to consider adding header to all requests to search.brave.com

The `X-Brave-Ads-Enabled` header description: https://github.com/brave/brave-browser/wiki/Custom-Headers#x-brave-ads-enabled

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.49.110 Chromium: 110.0.5481.177 (Official Build) beta (64-bit) 
-- | --
Revision | f34f7ab2d4ca4ad498ef42aeba4f4eb2c1392d63-refs/branch-heads/5481@{#1239}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/16023

<details>



</details>

**Comment by btlechowski** [comment]
Verification passed on Brave v1.49.108 on Lenovo TB-8506FS (Android 11.0)

Verified test plan from https://github.com/brave/brave-core/pull/16023

#### Run Brave browser with fresh profile

<details>

#### Open https://search.brave.com/


#### type query in the search box on https://search.brave.com/


#### search query from Omnibox



</details>

#### Enable Brave Private Ads

<details>

#### Open https://search.brave.com/


#### type query in the search box on https://search.brave.com/


#### search query from Omnibox


</details>

#### Disable Brave Private Ads

<details>

#### Open https://search.brave.com/


#### type query in the search box on https://search.brave.com/


#### search query from Omnibox


</details>

#### Run browser in Private mode

<details>

#### Open https://search.brave.com/


#### type query in the search box on https://search.brave.com/


#### search query from Omnibox


</details>

**Comment by Uni-verse** [comment]
In progress on `Samsung GS 21` using version:

```
Brave	1.49.117 Chromium: 111.0.5563.50 (Official Build) (64-bit) 
Revision	39f3dfc5023fe60997adc4f6cf5439cfa3e6968a-refs/branch-heads/5563@{#903}
OS	Android 13; Build/TP1A.220624.014
```
