### ISSUE TITLE
Issue with Ephemeral Storage tests 

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#26817]
## Description 

Initial case for the ephemeral storage tests is returning unexpected readings.

## Steps to Reproduce

   1. Clean install
   2. Navigate to https://dev-pages.brave.software/storage/ephemeral-storage.html
   3. Click on Start Test with default test presets
   4. Compare result with expected reading in the test

## Actual result:
<img width="400" alt="0" src="https://user-images.githubusercontent.com/17885425/202270379-cc739210-048a-4138-83e5-631d6b4c45d1.png">

## Expected result:
<img width="400" alt="0" src="https://user-images.githubusercontent.com/17885425/202270764-c9e41d54-8353-4708-9eb1-5266076be519.png">

## Reproduces how often: 
Easily

## Desktop Brave version:
 1.47.x, Any channel

## Android Device details:
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone, Tablet
   - Android version: 12

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
Expected for now as page has been adjusted to test upcoming work. See https://bravesoftware.slack.com/archives/C7VLGSR55/p1668669987094749?thread_ts=1668620091.590189&cid=C7VLGSR55 for more information.
