### ISSUE TITLE
"On exit" tab's "clear data" option is grayed out (unelectable)

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#26819]
## Description 

Follow up to https://github.com/brave/brave-browser/issues/26097
There are two problems when going to `brave://settings/clearBrowserData` --> `On exit`:

1. The option to save whatever data types are selected is grayed out and cannot be selected:
![image](https://user-images.githubusercontent.com/3299098/202271699-29c5ef6a-d5ba-4051-9282-29eaf9d0f067.png)
2. The option displays `Save` rather than `Clear data ` as it did previously. I'm not clear on whether or not this was intentional (but I do think it makes more sense this way, since you're not actually clearing data on that click).

## Steps to Reproduce

   1. Visit `brave://settings/clearBrowserData` --> [On exit]`
   2. Select a data type to be cleared on exit
   3. Observe `Save` button

## Reproduces how often: 

Always

## Brave version (brave://version info)

v1.45.127

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Miscellaneous Information:

Internal discussion: 
https://bravesoftware.slack.com/archives/C02DT9F5EP5/p1666647065097729
Community report:
https://community.brave.com/t/brave-not-deleting-history-and-no-option-to-save-on-exit-settings/441397/7

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.48.122 Chromium: 109.0.5414.87 (Official Build) beta (64-bit)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | Windows 11 Version 21H2 (Build 22000.1455)
```

Reproduced the issue in 1.46.153 where `Save` button is grayed out when selected options

Pre-requisite:
-  Manually add data & Import data from other browsers for following: 
    - Browsing history, Download history, Cookies and other site data, Cached images and files, Passwords and other sign-in data, Autofill form data, Site and Shields Settings,


1. Install 1.48.122
2. launch Brave
3. Skip onboarding 
4. go to `brave://settings/clearBrowserData`
5. click `On exit`
6. select all of the below options:
   ` Browsing history`, `Download history`, `Cookies and other site data`, `Cached images and files`, `Passwords and other sign-in 
     data`, `Autofill form data`, `Site and Shields Settings`
7. confirmed `Save` button is enabled
8. click `Save`
9. close all the tabs 
10. close and relaunch Brave

Confirmed browsing data is deleted

step 5|step 7|result
----|-----|----
<img width="774" alt="image" src="https://user-images.githubusercontent.com/98358127/212157198-8c5d5b6c-44d1-4a70-b5a0-ae74c392a5af.png">|<img width="770" alt="image" src="https://user-images.githubusercontent.com/98358127/212157388-f1d936f8-76ac-494b-812c-500d6c6313a2.png">|<img width="775" alt="image" src="https://user-images.githubusercontent.com/98358127/212158628-f0538dac-ff1f-48e8-b77e-22c2faf686c9.png">

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using 

Brave | 1.48.129 Chromium: 109.0.5414.87 (Official Build) beta (x86_64)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | macOS Version 11.7.2 (Build 20G1020)

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using 
```
Brave | 1.48.140 Chromium: 109.0.5414.119 (Official Build) beta (64-bit)
-- | --
Revision | 772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}
OS | Linux
```
Pre-requisite: Have data for following: 
    - `Browsing history`, `Download history`, `Cookies and other site data`, `Passwords and other sign-in data`, `Autofill form data`, `Site and Shields Settings`
    
    
1. Install 1.48.140
2. launch Brave
3. open a new-tap
4. open  `brave://settings/clearBrowserData`
5. click `On exit`
6. select all of the options except for `Hosted app data`: 
    - `Browsing history`, `Download history`, `Cookies and other site data`, `Cached images and files`, `Passwords and other sign-in data`, `Autofill form data`, `Site and Shields Settings`
7. confirmed `Save` button is enabled
8. click `Save`
9. close all the tabs (to confirm Browsing history is cleared)
10. close and relaunch Brave
11. open  `brave://settings/clearBrowserData`

#### Confirmed `Save` button is enabled after selecting options
#### Confirmed browsing history is deleted

step 5|step 7|result
----|-----|----
