### ISSUE TITLE
[Android] Failed Uphold tip still shows success screen in tipping banner

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#26815]
## Description

STR:

1. Staging
2. Verify with Uphold
3. Try to tip brave.com
4. This tip will fail according to logs
5. Success error message in tipping banner is still shown, which is incorrect

**Comment by kjozwiak** [comment]
The above requires `1.46.130` or higher for `1.46.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification inprogress on `Vivo X70 Pro verion 12` running `Bravemonoarm64.apk_1.46.130`
