### ISSUE TITLE
Aurora is shown under Ethereum Submenu Filter

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#26813]
## Description 

`Aurora` is being listed under `Ethereum` Submenu Filter.

## Steps to Reproduce

   1. Go to the Portfolio page
   2. Click on the `Network` filter and hover over `Ethereum`
   3. `Aurora` is being listed in the `Submenu`

## Actual result:

https://user-images.githubusercontent.com/40611140/202240786-78880670-5f49-4e3f-b65d-fb97c05e4867.mov

## Expected result:

`Aurora` should not be listed under `Ethereum` submenu.

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on <html>
<body>


Brave | 1.47.84 Chromium: 108.0.5359.48 (Official Build) nightly (64-bit)
-- | --
Revision | `18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}`
OS | Linux


</body>
</html>

- Verified steps from PR
- Verified Ethereum submenu only shows Ethereum testnets and doesn't list Aurora network
![image](https://user-images.githubusercontent.com/17010094/202732494-6ec30ace-7993-4a13-bb0e-0841bfcf0d33.png)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.46.129 Chromium: 108.0.5359.48 (Official Build) (64-bit)
-- | --
Revision | `18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}`
OS | Linux

- Verified steps from [brave/brave-core#15973](https://github.com/brave/brave-core/pull/15973)
- Verified Ethereum submenu only shows Ethereum testnets and doesn't list Aurora network

https://user-images.githubusercontent.com/17010094/204300007-780a1c3d-5bed-4b98-a15f-8b452e701014.mp4



---------------------

Verification passed on 

Brave | 1.46.129 Chromium: 108.0.5359.48 (Official Build) (64-bit)
-- | --
Revision | `18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#15973](https://github.com/brave/brave-core/pull/15973)
- Verified Ethereum submenu only shows Ethereum testnets and doesn't list Aurora network

https://user-images.githubusercontent.com/17010094/204300687-c83349b3-5414-433c-af1e-fdd79d5c3c60.mp4


---------------------

Verification passed on 

Brave | 1.46.129 Chromium: 108.0.5359.48 (Official Build) (arm64)
-- | --
Revision | `18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#15973](https://github.com/brave/brave-core/pull/15973)
- Verified Ethereum submenu only shows Ethereum testnets and doesn't list Aurora network

https://user-images.githubusercontent.com/17010094/204301840-59aec6c1-cffd-4013-8d79-a163bd570ca8.mov
