### ISSUE TITLE
Log served ad events before viewed ad events

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#26816]
Log "served" ad events before "view" ad events for the new tab page and promoted content ads in the ad_events database table. This is not a bug, but while investigating an issue for a user, this caused confusion when analyzing the database.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.47.101 Chromium: 108.0.5359.48 (Official Build) beta (64-bit)
-- | --
Revision | 18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-browser/issues/26816

<details>

</details>
