### ISSUE TITLE
ad notifications should timeout

### ISSUE THREAD

**Issue by bridiver** [brave/brave-browser#2681]
ad notification should timeout after 2 min in banner and alert style

1. Trigger an ad notification - need link to instructions...
2. Wait for at least 2 min
3. notification should close without user input

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.59.25 Chromium: 72.0.3626.53 (Official Build) beta (64-bit)
-- | --
Revision | 98434e6cd182d68ce396daa92e9c6310422e6763-refs/branch-heads/3626@{#620}
OS | Windows 7

Notification was shown and "notificationType":"timeout" was logged after 2minutes of showing the notification

```
[7772:2056:0118/164558.750:INFO:ads_service_impl.cc(938)] AdsService Event Log: {"data":{"type":"notify","stamp":"2019-01-18T16:45:58Z","notificationType":"timeout",
```
