### ISSUE TITLE
[Cr108 Follow up] IPNS Keys page dots menu doesn't work

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#26818]
STR:

1. Start Brave and navigate to ipfs://bafybeicgmdpvw4duutrmdxl4a7gc52sxyuk7nz5gby77afwdteh3jc5bqa/wiki/Mars.html
2. Pick to use local node and wait for installation
3. In a new tab navigate to brave://ipfs/
4. Click on Setup your IPNS keys on the bottom of the page
5. On the IPNS keys page click Add, enter any name and click Generate
6. Click on the triple dot menu button of the newly added key

Expected result:
Menu appears

Actual result:
Nothing happens

The console shows an error:
<pre>
settings.js:213 Uncaught TypeError: Cannot read properties of undefined (reading 'get')
    at SettingsBraveP2pKeysSubpageElement.onKeyMenuTapped_ (settings.js:213:3502)
    at polymer_bundled.min.js:1:23231
    at CrIconButtonElement.<anonymous> (polymer_bundled.min.js:1:49364)
</pre>

**Comment by GeetaSarvadnya** [comment]
The issue doesn't reproduce in Windows 10x64 - `1.47.72 Chromium: 107.0.5304.110` version  but it's reproducible in `1.47.75 Chromium: 108.0.5359.40` Looks like CR 108 Chromium bump issue.

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
Brave | 1.46.129 Chromium: 108.0.5359.48 (Official Build) (64-bit)
-- | --
Revision | 18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}
OS | Windows 10 Version 21H2 (Build 19044.2251)

```

Verified STR from https://github.com/brave/brave-browser/issues/26818#issue-1452133517:

1. Start Brave and navigate to ipfs://bafybeicgmdpvw4duutrmdxl4a7gc52sxyuk7nz5gby77afwdteh3jc5bqa/wiki/Mars.html
2. Pick to use local node and wait for installation
3. In a new tab navigate to brave://ipfs/
4. Click on "Manage Peer ID and IPNS keys" on the bottom of the page
5. On the IPNS keys page click Add, enter any name and click Generate
6. Click on the triple dot menu button of the newly added key
7. Confirmed menu displayed as expected

Example | Example | Example | Example
----------|-----------|----------|----------
![image](https://user-images.githubusercontent.com/38657976/204314693-02987f82-db5a-4a78-93a6-2c2ee4cde576.png) | ![image (1)](https://user-images.githubusercontent.com/38657976/204314715-7adfac05-e39d-4f28-b018-ff77972165ac.png) | ![image (2)](https://user-images.githubusercontent.com/38657976/204314755-e592db03-5913-4277-aed3-aa95f2986aa9.png) | ![image (3)](https://user-images.githubusercontent.com/38657976/204314782-7026766e-0a79-4892-be76-e6e879bb1df4.png)
