### ISSUE TITLE
Add copy clean link to the macOS application menu bar

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#26825]
The new "copy clean link" option is available in the contextual menu on macOS:
<img width="555" alt="copy-clean-url1" src="https://user-images.githubusercontent.com/167821/202331715-bd906923-cc28-4ef8-a63e-77be754ef424.png">

but it should also be available in the application menu bar where the keyboard shortcut can be seen:
<img width="442" alt="copy-clean-url2" src="https://user-images.githubusercontent.com/167821/202331871-b4264f92-2a58-46da-ad11-4782c397ab74.png">

(The keyboard shortcut is being changed to clean URLs by default in https://github.com/brave/brave-browser/issues/26761.)

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.49.96 Chromium: 110.0.5481.77 (Official Build) beta (x86_64)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | macOS Version 11.7.3 (Build 20G1116)

### Case 1: URL selection
<details>

### Steps:
1. installed `1.49.96`
2. launched Brave
3. loaded `https://twitter.com/fmarier/status/1574869891978784769?s=21&t=lkfjeslkfjes&fbclid=1234`
4. selected the URL
5. clicked on the top-level macOS `Edit` application-menu item
6. examined the shortcut options

#### Confirmed I got `Copy Clean Link ⌘C`

<img width="1680" alt="Screen Shot 2023-02-13 at 4 18 44 PM" src="https://user-images.githubusercontent.com/387249/218605569-8acce905-317c-47ca-8683-0372c7692eae.png">


</details>

### Case 2: substring selection
<details>

(continued from `Case 1`)

- selected substring `fmarier/status/1574869891978784769`
- clicked on the top-level macOS `Edit` application-menu item
- examined the shortcut options

#### Confirmed regular `Copy ⌘C` menu item


<img width="1680" alt="Screen Shot 2023-02-13 at 4 28 49 PM" src="https://user-images.githubusercontent.com/387249/218606773-e5ee8ade-1056-4c58-b663-3098a6c5dfd6.png">


</details>

### Case 3: no selection
<details>

- with no selection, clicked on the top-level macOS `Edit` application-menu item
- examined the shortcut options

#### Confirmed regular `Copy ⌘C` menu item

<img width="1680" alt="Screen Shot 2023-02-13 at 4 30 11 PM" src="https://user-images.githubusercontent.com/387249/218606910-5717f355-ab58-4beb-9a25-f0f340561e4f.png">


</details>

**Comment by smehrjerdian** [comment]
I don't understand why this feature was added to the latest version? Why would we want to copy the clean link when using the basic CMD + C shortcut for copying text off a page?

You can see here the community considers it a bug? Is there a way for us to revert this behavior back to the default behavior we are all used to of CMD+C copying text?

https://community.brave.com/t/keyboard-shortcuts-cmd-c-copy-clean-link-issue/477306
