### ISSUE TITLE
Flag configuration page's tab title reads `chrome://flags` instead of `brave://flags`

### ISSUE THREAD

**Issue by liamaharon** [brave/brave-browser#2682]
## Description 
Flags configuration page's tab title reads `chrome://flags`.

## Steps to Reproduce
Navigate to `brave://flags`

## Actual result:
https://i.imgur.com/BS6jqxt.png
(Github didn't let me embed the image in the issues for some reason..)

## Expected result:
I would expect `chrome` to be replaced by `brave`

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Brave | 0.58.16 Chromium: 71.0.3578.98 (Official Build) (64-bit)
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Linux

### Reproducible on current release:
Reproduces in the beta build

**Comment by Liunkae** [comment]
Also happens with Brave 0.60.4 dev:
![](https://user-images.githubusercontent.com/19424103/50355344-fd146300-0513-11e9-8c16-1b1e60a4d340.png)

@liamaharon
> (Github didn't let me embed the image in the issues for some reason..)

This is a known bug: #2034
As a workaround, please change the cookie setting to "All cookies allowed" for github.com.
