### ISSUE TITLE
Add wallet last usage time P3A metric

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#26823]
Add metric for last usage time for Brave Wallet:

As a Brave Wallet user, when was the last time I unlocked the Brave Wallet?
`Brave.Wallet.LastUsageTime`

1. 0 - 6 days ago
2. 7 - 13 days ago
3. 14 - 20 days ago
4. 21 - 27 days ago
5. 28 - 59 days ago
6. 60 days ago or more

**Comment by GeetaSarvadnya** [comment]
Verification INOROGRESS on

```
Brave | 1.48.151 Chromium: 109.0.5414.119 (Official Build) beta (64-bit)
-- | --
Revision | 772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}
OS | Windows 10 Version 21H2 (Build 19044.2486)
```
- Verified the test plan from https://github.com/brave/brave-core/pull/15983

**Comment by GeetaSarvadnya** [comment]
@DJAndries After creating a wallet in `iPhone 8 iOS version 16.11` -  `Brave Dev 1.48 (23.2.2.18)` I don't see the wallet metrics `Brave.Wallet.LastUsageTime`. Could you double check and let me know whether this question is implemented for iOS or not. Thanks!

**Comment by GeetaSarvadnya** [comment]
Opened a separte issue https://github.com/brave/brave-ios/issues/6894 in iOS repo as we don't have QA PASS label for iOS in Desktop repo
