### ISSUE TITLE
[Cr108 Follow up] Setting console error "Could not find manageLink in passwords_section"

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#26821]
The section we were hiding (since Chromium 87) is no longer on the passwords settings page (removed in Chromium 107). 
We can now remove the code trying to hide it.

QA Testing:
* Please verify that Settings -> Autofill -> Passwords Manager page doesn't show any unexpected UI elements and there's no error in the DevTools console.

**Comment by mkarolin** [comment]
Resolved via https://github.com/brave/brave-core/pull/15980

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.46.123 Chromium: 108.0.5359.48 (Official Build) beta (64-bit)
-- | --
Revision | 18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}
OS | Windows 11 Version 21H2 (Build 22000.1219)
```

1. Install 1.46.123
2. launch brave
3. opened `brave://settings/passwords`

#### Confirmed `Passwords Manger` page do not show any unexpected UI elements and the UI matches with `1.45.131` (current release)
#### Confirmed no errors shown in DevTools console


1.46.123|1.45.131
-----|-----
![image](https://user-images.githubusercontent.com/98358127/203426346-06339f17-0a09-45e0-8c75-09ba273a14f7.png)|![image](https://user-images.githubusercontent.com/98358127/203427265-274ba17a-ef7b-4e2c-8da1-d7d8eabf24c1.png)
