### ISSUE TITLE
`Can't connect to server` error trying to enable and connect to VPN, after successfully fetching credentials

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#26829]
## Description 

`Can't connect to server` error trying to enable and connect to VPN, after successfully fetching credentials

## Steps to Reproduce

1. delete any BraveVPN OS-configs, first
2. install `1.47.81`
3. launch Brave using `--vmodule="*/skus/*"=2 --enable-logging=stdrr --v=1`
4. click `Maybe later`
5. click `Skip welcome tour`
6. open `brave://flags`
7. set `brave://flags/#brave-vpn` to `Enabled`
8. click `Relaunc`h (if you want to retain logging, CTRL+C and relaunch from Terminal/console
9. click `No thanks` on the `Tired of cookie consent notices?` dialog
10. load `account.bravesoftware.com`
11. enter staging credentials from 1Password
12. enter a unique email address such as `"unique99@mailinator.com"` or similar
13. click Get login link
14. open the `Log in to your Brave Pre...` email (`https://www.mailinator.com/v4/public/inboxes.jsp?to=unique99` in the above case)
15. click on either the `Log in to Brave` button -or- the link below it
16. click `Browse plans` on `https://account.bravesoftware.com/account/`
17. scroll down
18. click on `Buy now` beneath `Brave VPN Subscription`
19. complete the Stripe checkout using `https://stripe.com/docs/testing#testing-interactively`
20. click on the `VPN` button in the browser toolbar, and attempt to add and connect to the BraveVPN config

## Actual result:

![image](https://user-images.githubusercontent.com/387249/202425894-9d9fdb15-248b-4b92-8b83-ea0587050243.png)

[chrome_debug.log](https://github.com/brave/brave-browser/files/10030545/chrome_debug.log)

## Expected result:

Able to connect to Brave VPN after purchase + successful credentials loading

## Reproduces how often: 

100% for me

## Brave version (brave://version info)

Brave | 1.47.81 Chromium: 108.0.5359.40 (Official Build) nightly (64-bit)
-- | --
Revision | 280b5fcaab3e877562b06cfaf2eb51121e13c3b9-refs/branch-heads/5359@{#689}
OS | Windows 10 Version 22H2 (Build 19045.2311)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `n/a`
- Can you reproduce this issue with the beta channel? `yes`
- Can you reproduce this issue with the nightly channel? `yes`

/cc @mattmcalister @bsclifton @spylogsster @LaurenWags @MadhaviSeelam @GeetaSarvadnya @rebron @srirambv

**Comment by stephendonner** [comment]
We'll want to document this and investigate/mitigate further, I believe.

But some good-ish news: got my Windows 10 setup working again, and verified with the following build: 

Brave | 1.46.114 Chromium: 107.0.5304.110 (Official Build) beta (64-bit)
--|--
Revision | 2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}
OS | Windows 10 Version 22H2 (Build 19045.2311)

`error` | `BraveVPN config` | `BraveVPN removal` | `success`
---------|----------|---------|----------
![image (1)](https://user-images.githubusercontent.com/387249/202559168-eb7bc6be-aee5-4eab-8adf-4d86fec08f7c.png) | ![image (2)](https://user-images.githubusercontent.com/387249/202559170-b39b4e4e-409f-4279-a966-477788f0180b.png) | ![image](https://user-images.githubusercontent.com/387249/202559174-4db32b92-6b1e-467b-8ee4-f96f28f58c7a.png) | ![image (3)](https://user-images.githubusercontent.com/387249/202559172-c4cc6e14-008f-4fd1-a9fe-35471db74c54.png)


In the end, I "fixed" this and achieved the above expected result by following the steps on https://github.com/trailofbits/algo/issues/1051:
* clearing networking caches
* resetting Device-Manager adaptors

Full steps in the issue.

**Comment by stephendonner** [comment]
Full thread here: https://bravesoftware.slack.com/archives/C0141L60REG/p1668708855325319

**Comment by GeetaSarvadnya** [comment]
@stephendonner I have followed the steps from the STR. I am not getting this issue in my ` Windows 10 x64 - 1.47.82 Chromium: 108.0.5359.40`. I can connect the VPN successfully after VPN  purchase + successful credentials loading

![image](https://user-images.githubusercontent.com/38657976/202635764-b59aeedf-a8aa-4c17-88b0-578cab31c564.png)

**Comment by bsclifton** [comment]
NOTE: we have added details about this to our FAQ. 

@mattmcalister should we can consider that adequate? or should we look at a programmatic solution?

**Comment by bsclifton** [comment]
Closing - we have a help article for this now https://support.brave.com/hc/en-us/articles/13653403930637-Cannot-connect-to-BraveVPN-the-parameter-is-incorrect-Error-87-
