### ISSUE TITLE
[Desktop] Implement NFT Pinning

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#26828]
[Figma File](https://www.figma.com/file/4e7rsWzBUKv3dCdxCqB6CR/NFT-IPFS?node-id=1042%3A92163&t=bmDTH4OSlDI4VjuG-0)

[Figma Clickable link](https://www.figma.com/proto/4e7rsWzBUKv3dCdxCqB6CR/NFT-IPFS?page-id=2%3A15&node-id=1044%3A100312&viewport=-52775%2C5716%2C1.27&scaling=min-zoom&starting-point-node-id=1044%3A100312&show-proto-sidebar=1)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.50.106 Chromium: 112.0.5615.39 (Official Build) beta (64-bit)
-- | --
Revision | `a0e7b9718a92bcd1cf33b7c95316caff3fc20714-refs/branch-heads/5615@{#753}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from [brave/brave-core#16998](https://github.com/brave/brave-core/pull/16998)
- Verified able to pin an NFT locally
- Verified with flag enabled, shows a banner message about NFT pinning
- Verified clicking on `Learn more` loads interstitial page `brave://wallet/crypto/local-ipfs-node`
- Verified selecting `Check which NFTs of mine can be pinned` on `brave://wallet/crypto/local-ipfs-node` shows how many of the added NFT's can be pinned
- Verified `Keep my NFTs always online` on both `brave://wallet/crypto/local-ipfs-node` and `brave://wallet/crypto/inspect-nfts` enables the `Automatically pin NFTs` settings under `brave://settings/web3/`
- Verified once an NFT is pinned shows how many NFT's are locally pinned in the same banner message
- Verified clicking on a locally pinned NFT shows the CID and `Image location or address` link
- Verified based on the setting for `Method to resolve IPFS resources`, `Image location or address` loads the image either via localhost or via gateway or brings up the interstitial page 
- Verified when IPFS is turned off NFT details page shows `Local IPFS node is not running` 
- Verified when IPFS is turned off and clicking the `Image location or address` automatically starts IPFS 
- Encountered [#29354](https://github.com/brave/brave-browser/issues/29354) [#29200](https://github.com/brave/brave-browser/issues/29200), [#29199](https://github.com/brave/brave-browser/issues/29199), [#29009](https://github.com/brave/brave-browser/issues/290090)

https://user-images.githubusercontent.com/17010094/228142286-889b3320-78fc-42ac-8b32-4ca0cc8cd676.mp4


---------------------

Verification passed on 

Brave | 1.50.106 Chromium: 112.0.5615.39 (Official Build) beta (64-bit) 
-- | --
Revision | `a0e7b9718a92bcd1cf33b7c95316caff3fc20714-refs/branch-heads/5615@{#753}`
OS | Linux

- Verified steps from [brave/brave-core#16998](https://github.com/brave/brave-core/pull/16998)
- Verified able to pin an NFT locally
- Verified with flag enabled, shows a banner message about NFT pinning
- Verified clicking on `Learn more` loads interstitial page `brave://wallet/crypto/local-ipfs-node`
- Verified selecting `Check which NFTs of mine can be pinned` on `brave://wallet/crypto/local-ipfs-node` shows how many of the added NFT's can be pinned
- Verified `Keep my NFTs always online` on both `brave://wallet/crypto/local-ipfs-node` and `brave://wallet/crypto/inspect-nfts` enables the `Automatically pin NFTs` settings under `brave://settings/web3/`
- Verified once an NFT is pinned shows how many NFT's are locally pinned in the same banner message
- Verified clicking on a locally pinned NFT shows the CID and `Image location or address` link
- Verified based on the setting for `Method to resolve IPFS resources`, `Image location or address` loads the image either via localhost or via gateway or brings up the interstitial page 
- Verified when IPFS is turned off NFT details page shows `Local IPFS node is not running` 
- Verified when IPFS is turned off and clicking the `Image location or address` automatically starts IPFS 
- Encountered [#29354](https://github.com/brave/brave-browser/issues/29354) [#29200](https://github.com/brave/brave-browser/issues/29200), [#29199](https://github.com/brave/brave-browser/issues/29199), [#29009](https://github.com/brave/brave-browser/issues/290090)

https://user-images.githubusercontent.com/17010094/228147096-0d7b97fc-1aa5-49a1-bf66-66c1f3aa3f37.mp4


---------------------



Verification passed on 

Brave | 1.50.106 Chromium: 112.0.5615.39 (Official Build) beta (arm64)
-- | --
Revision | `a0e7b9718a92bcd1cf33b7c95316caff3fc20714-refs/branch-heads/5615@{#753}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#16998](https://github.com/brave/brave-core/pull/16998)
- Verified able to pin an NFT locally
- Verified with flag enabled, shows a banner message about NFT pinning
- Verified clicking on `Learn more` loads interstitial page `brave://wallet/crypto/local-ipfs-node`
- Verified selecting `Check which NFTs of mine can be pinned` on `brave://wallet/crypto/local-ipfs-node` shows how many of the added NFT's can be pinned
- Verified `Keep my NFTs always online` on both `brave://wallet/crypto/local-ipfs-node` and `brave://wallet/crypto/inspect-nfts` enables the `Automatically pin NFTs` settings under `brave://settings/web3/`
- Verified once an NFT is pinned shows how many NFT's are locally pinned in the same banner message
- Verified clicking on a locally pinned NFT shows the CID and `Image location or address` link
- Verified based on the setting for `Method to resolve IPFS resources`, `Image location or address` loads the image either via localhost or via gateway or brings up the interstitial page 
- Verified when IPFS is turned off NFT details page shows `Local IPFS node is not running` 
- Verified when IPFS is turned off and clicking the `Image location or address` automatically starts IPFS 
- Encountered [#29354](https://github.com/brave/brave-browser/issues/29354) [#29200](https://github.com/brave/brave-browser/issues/29200), [#29199](https://github.com/brave/brave-browser/issues/29199), [#29009](https://github.com/brave/brave-browser/issues/290090)

https://user-images.githubusercontent.com/17010094/228148907-d0754e5e-6e63-4821-bcb4-fb59caeeba02.mp4
