### ISSUE TITLE
Decimal value is not shown in the `Monthly Tip` dropdown in the BR panel 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#26833]
## Description 
Found while testing https://github.com/brave/brave-browser/issues/17070
Decimal value is not shown in the `Monthly Tip` dropdown in the BR panel 
## Steps to reproduce 

   1. Clena profile 1.46.x
   2. Enable rewards
   3. Claim UGP grants
   4. Open laurenwags.github.io
   5. Click on the BR panel and click on the `Send Tip` button
   6. Send a decimal recurring/monthly tip, e.g `10.5` (from default tip sections) or any decimal value (e.g 2.5) via custom tip selection
   7. Confirm tip is send successfully
   8. Open the BR panel for laurenwags.github.io
   9. Observe that whole number is showing up in the `Monthly tip` dropdown 

## Actual result 
Decimal value is not shown in the `Monthly Tip` dropdown in the BR panel 

Tipping banner | Monthly tip dropdown
------------------|------------------------
![image](https://user-images.githubusercontent.com/38657976/202463945-c5fbd05f-6bf6-4199-b275-7da632d6d3c4.png) | ![image](https://user-images.githubusercontent.com/38657976/202464362-eb5cbeff-adb5-43f1-912c-4cfe0541b0b7.png)

## Expected result

Monthly tip dropdown should show both whole number and the fraction value

Desktop:
![image](https://user-images.githubusercontent.com/38657976/202463116-3ce2c591-e800-4d95-99ad-0d98893f2e01.png)

## Issue reproduces how often 

Easy
## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): All
   - Device type (Phone, Tablet, Phablet): All
   - Android version: 12
   
## Brave version
1.46.114

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @Miyayes @brave/qa-team @deeppandya

**Comment by kjozwiak** [comment]
The above requires `1.46.127` or higher for `1.46.x` verification 👍
