### ISSUE TITLE
Send Tab add Fiat Balance to Account Sections

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#26838]
## Description 

Add a `Fiat` balance for each `Account` section in the `Select Token` modal.

![Screen Shot 2022-11-14 at 1 27 38 PM](https://user-images.githubusercontent.com/40611140/202486722-be98ce0d-34e0-437e-a1cc-b4d1628ec780.png)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.47.126 Chromium: 108.0.5359.99 (Official Build) beta (64-bit)
-- | --
Revision | `410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}`
OS | Linux

- Verified steps from [brave/brave-core#15996](https://github.com/brave/brave-core/pull/15996)
- Verified clicking on the select token shows all the accounts with token balance
- Verified able to filter based on network
- Verified able to filter based on search token 

https://user-images.githubusercontent.com/17010094/207593578-22314808-610e-45ee-9b6e-f2a4d51b67f2.mp4

---------------------

Verification passed on 

Brave | 1.47.126 Chromium: 108.0.5359.99 (Official Build) beta (64-bit)
-- | --
Revision | `410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#15996](https://github.com/brave/brave-core/pull/15996)
- Verified clicking on the select token shows all the accounts with token balance
- Verified able to filter based on network
- Verified able to filter based on search token 

https://user-images.githubusercontent.com/17010094/207592793-3c904d25-3914-49cc-8d2a-301597f6e3ee.mp4

---------------------

Verification passed on 

Brave | 1.47.126 Chromium: 108.0.5359.99 (Official Build) beta (arm64)
-- | --
Revision | `410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#15996](https://github.com/brave/brave-core/pull/15996)
- Verified clicking on the select token shows all the accounts with token balance
- Verified able to filter based on network
- Verified able to filter based on search token 

https://user-images.githubusercontent.com/17010094/207593881-88e5a7ad-94ac-4d55-83bc-ffc43b40e34c.mov
