### ISSUE TITLE
Is it possible to build brave for Linux distributions?

### ISSUE THREAD

**Issue by s-kk** [brave/brave-browser#26832]
### THIS IS NOT A BUG REPORT. 

Dear developers at Brave,
Hi! I am recently writing a PKGBUILD file for Arch Linux users, and preferably, bring the package to the Arch community repo. 
However, there are a couple of factors blocking me.
It seems impossible to pass `is_official_build=false` to the build system. If I add `--official_build=false` to `npm run build Release`, the build system would still complain the `brave_services_key` is not provided and thus fail. 
Other factors could be patches that allow Brave to compile against system toolchains and related stuff. 

I would like ask that, is there any documented way to compile Brave with proper arguments for `npm run build Release`, and if Brave compiled successfully without `brave_services_key`, would services like Brave Sync and Rewards function normally?

The preliminary PKGBUILD file that I tested (contains a lot of quirks): https://gist.github.com/s-kk/4e4263f45e92851444def57f33e516ca
Related Issues: https://github.com/brave/brave-browser/issues/22524

Thanks a lot for answering!

**Comment by Vulncatic** [comment]
fuck microsoft!

**Comment by wknapik** [comment]
Hi @s-kk. There are already [source and binary packages of Brave for Arch Linux](https://aur.archlinux.org/packages?O=0&SeB=nd&K=brave-&outdated=&SB=p&SO=d&PP=50&submit=Go) (there used to be a few more source packages, but it seems they're gone now). They are community-maintained and are covered in the [installation instructions for Linux](https://brave.com/linux/#arch). If you'd still like to build Brave from source, you can take a look at the existing PKGBUILDS, the main [README](https://github.com/brave/brave-browser/blob/master/README.md) and the wiki (e.g. [Linux development environment](https://github.com/brave/brave-browser/wiki/Linux-Development-Environment), [Linux packages](https://github.com/brave/brave-browser/wiki/Linux-packages)). I'd have to see about the `brave_services_key` issue.

**Comment by s-kk** [comment]
> There are already [source and binary packages of Brave for Arch Linux](https://aur.archlinux.org/packages?O=0&SeB=nd&K=brave-&outdated=&SB=p&SO=d&PP=50&submit=Go) (there used to be a few more source packages, but it seems they're gone now).

These AUR packages are outdated, which means they don't work for newer version of Chromium and Brave. What I am doing here is to create a PKGBUILD that is maintainable for the Arch community, with upstream patches for building against system libraries in Arch Linux. 

After some more investigation, there's more potential problem other than the `brave_services_key` issue. For example, `npm run build` does not seem to accept `--gn=...` argument, which make it impossible to specify `use_custom_libcxx=false`, thus impossible to build against system library like the Chromium package in Arch Linux repo does.

**Comment by s-kk** [comment]
> For example, `npm run build` does not seem to accept `--gn=...` argument

For this issue, it could be reproduced by the following:
The line added to `npm run build`: https://gist.github.com/s-kk/4e4263f45e92851444def57f33e516ca#file-pkgbuild-L269
The argument will be transformed into the form of `--gn=use_custom_libcxx:false` by this: https://gist.github.com/s-kk/4e4263f45e92851444def57f33e516ca#file-pkgbuild-L316-L318
However, when running this PKGBUILD, the following output is produced:
```
/data/brave/src/brave-browser/src
> gn gen /data/brave/src/brave-browser/src/out/redirect_cc --args="import(\"//brave/tools/redirect_cc/args.gni\") use_goma=false goma_dir=\"/data/brave/src/brave-browser/src/brave/vendor/depot_tools/.cipd_bin\" real_gomacc=\"/data/brave/src/brave-browser/src/brave/vendor/depot_tools/.cipd_bin/gomacc\" "
ERROR at //third_party/re2/BUILD.gn:8:1: Assertion failed.
assert(!use_custom_libcxx,
^-----
Usage of the system libre2.so is not supported with use_custom_libcxx=true because the library's interface relies on libstdc++'s std::string and std::vector.
See //third_party/leveldatabase/BUILD.gn:132:5: which caused the file to be included.
    "//third_party/re2",
    ^------------------
null
null
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by wknapik** [comment]
> the build system would still complain the brave_services_key is not provided and thus fail

You'll have to set all mandatory parameters, like brave_services_key, to build. You can use dummy values to get past the assertions (e.g. `npm config --userconfig=.npmrc set brave_services_key "foo"`).

**Comment by bsclifton** [comment]
Closing as this is primarily a discussion - and we're having the same one on our community site here: 😄 
https://community.brave.com/t/does-brave-allow-the-distribution-of-self-compiled-or-distro-compiled-binaries/457833
