### ISSUE TITLE
Update Verifiable Ad Conversion Logic

### ISSUE THREAD

**Issue by iambrianfung** [brave/brave-browser#26834]
Verifiable Ad Conversions should follow the following logic when extracting the `Order ID`:

1. If ads resources components & URL regex 
    -> attempt URL regex
3. If ads resources components & URL regex & failed URL regex & DOM regex
    -> attempt DOM regex
4. If ads resources components & no URL regex & DOM regex
    -> attempt DOM regex
5. If ads resources components & no URL regex & DOM regex & failed DOM regex
    -> attempt <meta> tag
6. If ads resources components & URL regex & failed URL regex & DOM regex & failed DOM regex
    -> attempt <meta> tag
7. If no ads resources components
    -> attempt <meta> tag
8. If all 3 fail
    -> fire `conversion event` but no `conversionEnvelope`

In all cases, we should be checking for valid `OrderI ID` pattern. 
If it fails, attempt another method if applicable. 
Else, 8.

There is typically never a case where a conversion URL has both a URL regex and DOM regex.
If this is the case, attempt the URL first, then the DOM
If URL regex and DOM regex both fail to extract a valid `order ID` then finally fall back to <meta> tag.

**Comment by iambrianfung** [comment]
```
  IF Catalog.CreativeAdConversion.UrlPattern MATCHES RedirectChain
    IF Catalog.CreativeAdConversion.extractExternalId is FALSE
      OR Catalog.CreativeAdConversion.VerifiableConversionPublicKey DOES NOT EXIST
        We have converted, Yippee!
    ELSE  // extractExternalId EQUALS TRUE (Implies VerifiableConversionPublicKey exists)
      IF Components.Resource EXISTS
        IF Components.Resource.UrlPattern MATCHES RedirectChain
          IF Components.Resource.SearchIn EQUALS "URL"
            IF ExtractVerifiableConversionIdFromUrl IS SUCCESSFUL
              We have verifiably converted (with sealed envelope), Yippee!
            ELSE
              We have converted, Yippee!
            END
          ELSE IF Components.Resource.SearchIn EQUALS "HTML"
            IF ExtractVerifiableConversionIdFromHtml IS SUCCESSFUL
              We have verifiably converted (with sealed envelope), Yippee!
            ELSE
              We have converted, Yippee!
            END
          ELSE  // Empty or unknown
            IF ExtractVerifiableConversionIdFromMetaTag IS SUCCESSFUL
              We have verifiably converted (with sealed envelope), Yippee!
            ELSE
              We have converted, Yippee!
            END
          END
        ELSE
          We have converted, Yippee!
        END
      ELSE
        We have converted, Yippee!
      END
    END
  ELSE
    // Do nothing!
  END
```

**Comment by tmancey** [comment]
Resolving as part of https://github.com/brave/brave-browser/issues/23308
