### ISSUE TITLE
[Speedreader] Crash in Speedreader Panel V2

### ISSUE THREAD

**Issue by boocmp** [brave/brave-browser#26831]
## Steps to Reproduce

 Run browser with --enable-features=SpeedreaderPanelV2

 1. Open 2 sites with speedreaded pages
 2. Open panel in first tab
 3. Close first tab
 4. Open panel in second tab and change something

## Actual result:

  Crash

## Expected result:
 No crash, changes applied

## Reproduces how often: 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.47.114 Chromium: 108.0.5359.94 (Official Build) beta (64-bit)
-- | --
Revision | 713576b895246504ccc6b92c2fb8ce2d60194074-refs/branch-heads/5359_71@{#3}
OS | Windows 11 Version 21H2 (Build 22000.1219)
```

1. Install 1.47.114
2. launch Brave with  --enable-features=SpeedreaderPanelV2
3. visit https://www.bbc.com/news/world-europe-63863138 in a new-tab
4. visit https://www.cnn.com/2022/12/05/football/brazil-south-korea-qatar-world-cup-spt-intl/index.html in a new-tab
5. Open panel in first tab
6. Close first tab
7. Open panel in second tab and change something

#### Confirmed no crash occurred (when enabled speedreader toggle in the panel for second tab)

step 3|step 4|step 5|step 7
------|----|-----|-----
![image](https://user-images.githubusercontent.com/98358127/205760015-e8411ef9-690b-4145-be98-cbcb344b8776.png)|![image](https://user-images.githubusercontent.com/98358127/205760379-18a75e29-43dc-4498-acf6-ea8e227f5bce.png)|![image](https://user-images.githubusercontent.com/98358127/205760859-78c205dd-97ba-4749-a25d-a97f5f8916c0.png)|![image](https://user-images.githubusercontent.com/98358127/205760995-a854e96c-cff2-488d-93d7-d0383acb4b0c.png)

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.47.120 Chromium: 108.0.5359.99 (Official Build) dev (x86_64)
-- | --
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | macOS Version 13.1 (Build 22C65)

### Steps:
1. installed `1.47.120`
2. launched Brave using `--enable-features=SpeedreaderPanelV2`
3. visited `https://www.bbc.com/news/world-europe-63863138` in a new tab
4. visited `https://www.cnn.com/2022/12/05/football/brazil-south-korea-qatar-world-cup-spt-intl/index.html` in a new tab
5. opened panel in first tab
6. closed first tab
7. opened panel in second tab
8. toggled the toggle

step 3 | step 4 | step 5 | step 7 | step 8
-------|-------|--------|-------|---------
<img width="1312" alt="Screenshot 2022-12-08 at 9 26 31 PM" src="https://user-images.githubusercontent.com/387249/206631701-eb2ec40b-37a7-4cbe-bb78-fddb9120ac44.png"> | <img width="1312" alt="Screenshot 2022-12-08 at 9 26 45 PM" src="https://user-images.githubusercontent.com/387249/206631714-97a16993-11c0-4f7c-b043-ba64e518a2e7.png"> | <img width="1312" alt="Screenshot 2022-12-08 at 9 27 13 PM" src="https://user-images.githubusercontent.com/387249/206631718-170dc80a-fafa-4f83-aae5-5c0f7b01c4f4.png"> | <img width="1312" alt="Screenshot 2022-12-08 at 9 27 55 PM" src="https://user-images.githubusercontent.com/387249/206631721-b2548357-4e61-4e10-9941-38a54f3d46e1.png"> | <img width="1312" alt="Screenshot 2022-12-08 at 9 31 02 PM" src="https://user-images.githubusercontent.com/387249/206631722-3f039b2d-0802-4d7f-a620-a5833dd3ed1a.png">
