### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by sdavis-AWP** [brave/brave-browser#26841]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.44.112  Chromium: 106.0.5249.119
Operating System: Mac OS X 13.0.0

URL (if applicable) where crash occurred:
No URL - On brave settings and home pages (but happens on any page and anytime since upgrading to Ventura.

Can you reproduce this crash?
Yes, all I have to do is use Brave browser for a few minutes.
What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. This truly feels random. I'm experiencing crashes at completely random intervals and on many different pages.
2. Fingers crossed I get to post this before another occurs.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/157b0100-483e-2b09-0000-000000000000

**Comment by sdavis-AWP** [comment]
I should note that I just updated to 1.45.127

Will update if it continues.

**Comment by rebron** [comment]
Thanks @sdavis-AWP Let us know if you're still experiencing the same crash.
