### ISSUE TITLE
Extend detection for ad ref code

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#26845]
## Description 
This a follow up for https://github.com/brave/brave-browser/issues/25265
We need to extend detection for ad ref code.

**Comment by samartnik** [comment]
Test plan:
1. Install brave browser from the Google Search ad (contact @porteron on how to do it).
2. Goto `brave://local-state`.
3. Make sure that ref code there is `UAC002`.

**Comment by porteron** [comment]
RE:
> should this be done via Google browser or can be done via Brave browser on stable release. need to check for nightly for uplift

@srirambv What you'll need to do here is the following:
#### Prerequisites:
  -  On Android device you cannot be logged into a brave account
  - Must be in US or CA for the ad to show, VPN will work too.
  - Android phone with google chrome and Brave Beta not installed.

#### Steps 
1. On an android device open up Google Chrome and search "Brave 247 beta", you scroll through the results until you see a Brave Beta Sponsored Ad. Download from there. You may need to search "Brave 247 beta" a few times for the ad to show up.
2. Open the Beta App after the download completes and go to `chrome://local-state` 
3. Near the top section there should be an entry about promo information and you will see a refcode. That refcode should be `UAC002` or `UAC001`.

Complete.

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` & `Samsung Galaxy Tab S7` using the following build version(s):

```
Brave	1.46.130 Chromium: 108.0.5359.62 (Official Build) (64-bit) 
Revision	041930a89a990cfab0315a2d9f20d6429a4a67cf-refs/branch-heads/5359@{#938}
OS	Android 12; Build/SP1A.210812.016
```
- Verified refcode is `UAC001` in brave://local-state for release app (1.46.x) ad campaign

Example | Example | Example
-|-|-
![screenshot-1669742726877](https://user-images.githubusercontent.com/17885425/204601578-6c748981-9b18-4c42-9d4f-8a323310901f.png) | ![screenshot-1669742971301](https://user-images.githubusercontent.com/17885425/204601581-8dd21268-b602-4249-bfa4-e4a8e57ddd52.png) | ![screenshot-1669742983566](https://user-images.githubusercontent.com/17885425/204601583-cfb2fc5c-29b9-4995-b771-77d0ff403de4.png)
