### ISSUE TITLE
[Brave News] The Brave News subscribe button should be enabled by default

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#26847]
Currently, the feature is behind a flag. We should add a pref for showing and hiding it, configurable through settings and use that instead.

**Comment by stephendonner** [comment]
We should fix https://github.com/brave/brave-browser/issues/26262 before enabling this by default (obvious, but just wanted to make it explicit so we don't forget).

**Comment by stephendonner** [comment]
### Steps:
1. install `1.48.x`
2. launch Brave
3. open `brave://flags`
4. look for `brave://flags/#brave-news-subscribe-button` and ensure it's set to `Default`
5. load `planet.mozilla.org`
6. click on the `RSS`-feed icon in the URL bar

**Comment by fallaciousreasoning** [comment]
**Note:** This actually removes the flag, it's only behind a pref now.

**Comment by stephendonner** [comment]
> **Note:** This actually removes the flag, it's only behind a pref now.

Thanks; I updated the steps in https://github.com/brave/brave-browser/issues/26847#issuecomment-1330234186

**Comment by kjozwiak** [comment]
The above requires `1.47.108` or higher for `1.47.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave| 1.47.110 Chromium: 108.0.5359.71 (Official Build) beta (x86_64) 
--|--
Revision | 1e0e3868ee06e91ad636a874420e3ca3ae3756ac-refs/branch-heads/5359@{#1016}
OS | macOS Version 13.1 (Build 22C5059b)

### Steps:
1. installed `1.47.110`
2. launched Brave
3. opened `brave://flags`
4. searched for `button` and confirmed the button flag has been removed
5. loaded `theatlantic.com`
6. clicked on the `Manage Subscriptions` RSS-feed icon

#### Confirmed the `Manage Subscriptions` RSS feed icon was updated and worked

`example` | `example` | `example` | `example`
-----------|------------|-----------|-----------
<img width="1312" alt="Screenshot 2022-12-03 at 4 59 46 PM" src="https://user-images.githubusercontent.com/387249/205469023-22ab7002-3e2b-4740-8c4e-745d9bcaf2d3.png"> | <img width="1312" alt="Screenshot 2022-12-03 at 4 58 18 PM" src="https://user-images.githubusercontent.com/387249/205469029-c5be9c19-2c4e-42c1-bf9e-81ddf1baf364.png"> | <img width="1312" alt="Screenshot 2022-12-03 at 4 59 26 PM" src="https://user-images.githubusercontent.com/387249/205469030-3c49bd1e-0e31-4154-809e-f895121289d0.png"> | <img width="1312" alt="Screenshot 2022-12-03 at 4 59 31 PM" src="https://user-images.githubusercontent.com/387249/205469032-e7219dfc-1dbb-4304-b55b-c0d1fe1ea33e.png">

**Comment by kjozwiak** [comment]
Unfortunately it sounds like this needed to go into the `1.46.x` maintenance release but was missed. I'll get this uplifted into `1.46.x` and reset the `QA Pass` labels. Shouldn't be hard to re-verify. If we don't end up getting another chromium bump for `C108`, we'll just move this back into `1.47.x` and re-add the `QA Pass` labels as we already checked `1.47.x`.

**Comment by kjozwiak** [comment]
The above requires `1.46.148` or higher for `1.46.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.46.153 Chromium: 108.0.5359.128 (Official Build) (64-bit)
-- | --
Revision | 1cd27afdb8e5d057070c0961e04c490d2aca1aa0-refs/branch-heads/5359@{#1185}
OS | Windows 11 Version 21H2 (Build 22000.1335)
```
### Steps:
1. installed `1.46.153`
2. launched Brave
3. scroll down and click `Turn on Brave News` 
4. opened `brave://flags`
5. searched for `button` and confirmed the button flag has been removed
6. loaded `theatlantic.com`
7. clicked on the `Manage Subscriptions` RSS-feed icon

#### Confirmed the `Manage Subscriptions` RSS feed icon was updated and worked

step 3|step 4-5|step6-7|result|result
-----|-----|------|-----|------
<img width="453" alt="image" src="https://user-images.githubusercontent.com/98358127/211075766-dfa4dfd8-a334-47dd-aff6-6175286b7a09.png">|<img width="448" alt="image" src="https://user-images.githubusercontent.com/98358127/211075910-8c2eb2e8-7e00-448e-a6cb-7cb463a1c6d1.png">|<img width="450" alt="image" src="https://user-images.githubusercontent.com/98358127/211076025-a9fafa41-3c21-4f88-ae0f-ee99fc10a11a.png">|<img width="452" alt="image" src="https://user-images.githubusercontent.com/98358127/211076154-428100cb-ac01-4e18-b329-2a909fa71ff9.png">|<img width="449" alt="image" src="https://user-images.githubusercontent.com/98358127/211076113-54540092-fb6c-451a-99f1-371dce085bd6.png">

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.46.153 Chromium: 108.0.5359.128 (Official Build) (64-bit) 
Revision	1cd27afdb8e5d057070c0961e04c490d2aca1aa0-refs/branch-heads/5359@{#1185}
OS	Linux
```

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.46.153 Chromium: 108.0.5359.128 (Official Build) (x86_64)
-- | --
Revision | 1cd27afdb8e5d057070c0961e04c490d2aca1aa0-refs/branch-heads/5359@{#1185}
OS | macOS Version 11.7.2 (Build 20G1020)

### Steps:

1. installed 1.47.x
2. launched Brave
3. scroll down and click Turn on Brave News
4. opened brave://flags
5. searched for button and confirmed the button flag has been removed
6. loaded theatlantic.com
7. clicked on the Manage Subscriptions RSS-feed icon

#### Confirmed the Manage Subscriptions RSS feed icon was displayed and I was able to follow one of the feeds

example | example | example | example
---------|----------|---------|---------
<img width="1708" alt="Screen Shot 2023-01-06 at 12 03 41 PM" src="https://user-images.githubusercontent.com/387249/211090645-1494f1d0-d16c-4652-b5ab-84cdb98ae02b.png"> | <img width="1708" alt="Screen Shot 2023-01-06 at 12 05 18 PM" src="https://user-images.githubusercontent.com/387249/211090887-eb22d4d2-77a6-4eb7-ac52-fb102731d96b.png"> | <img width="1708" alt="Screen Shot 2023-01-06 at 12 05 27 PM" src="https://user-images.githubusercontent.com/387249/211090896-83a9ee0d-d80e-44ca-bbaf-0beb1bcab276.png"> | <img width="1708" alt="Screen Shot 2023-01-06 at 12 05 37 PM" src="https://user-images.githubusercontent.com/387249/211090904-7429ca2c-dfba-4e0c-b506-efb1253c229c.png">
