### ISSUE TITLE
Brave News: Request to add thechainsaw.com to Brave News sources

### ISSUE THREAD

**Issue by lukemulks** [brave/brave-browser#26850]
## Description 

We received a request from a long time user that runs thechainsaw.com, requesting that we add their site to the Brave News sources list. 

Original request  https://twitter.com/thecryptojourno/status/1593467378276651009?t=mHLHLUntO5jKoA1MIPrf7w&s=19

Site: 
https://thechainsaw.com 

## Steps to Reproduce

   1. 
   2. 
   3. 

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by mattmcalister** [comment]
All users can add thechainsaw.com RSS feed to Brave News. The new 1-click Follow button in the address bar will make that super easy. However the content that we aggregate and make available for browsers to fetch via the CDN has to stay limited in size, so we use a ranked list of top sites provided by Brave Search. We'll update the lists regularly to make sure the top publishers are finding their way into Brave News, so we'll keep an eye out for thechainsaw.com as it grows.
