### ISSUE TITLE
Follow up of #25789 - Choose new server throws Can't connect to server error in both profile 1 and profile 2

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#26857]
## Description 

Follow up of #25789 - Choose new server throws Can't connect to server error in both profile 1 and profile 2
## Steps to Reproduce

   1. Please refer the STR from the issue https://github.com/brave/brave-browser/issues/25789#issue-1395810177
   

## Actual result:

Follow up of #25789 - Choose new server throws Can't connect to server error in both profile 1 and profile 2
![cannot connect error message](https://user-images.githubusercontent.com/38657976/202728136-3d811cab-3c3d-4d43-aa89-2cb08b8c9d59.gif)

## Expected result:

Should not throw any error

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.46.117 Chromium: 107.0.5304.110 (Official Build) beta (64-bit)
-- | --
Revision | 2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}
OS | Windows 10 Version 21H2 (Build 19044.2251)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @simonhong @bsclifton

**Comment by LaurenWags** [comment]
cc @mattmcalister for visibility

**Comment by simonhong** [comment]
Checking

**Comment by simonhong** [comment]
https://github.com/brave/brave-core/pull/16065 will mitigate this issue but not sure will fix this issue 100%.
@GeetaSarvadnya  If you see this again, feel free to open again.

**Comment by kjozwiak** [comment]
The above requires `1.46.128` or higher for `1.46.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.46.129 Chromium: 108.0.5359.48 (Official Build) (x86_64)
-- | --
Revision | 18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}
OS | macOS Version 11.7.1 (Build 20G918)

### Steps:
1. installed `1.46.129`
2. purchased and configured VPN using `issue26857@mailinator.com` from `account.bravesoftware.com` (staging)
3. connected to `BraveVPN`, and confirmed VPN is connected to default/nearest server `USA (West)`
4. created `VPN Profile 2` via the `"hamburger"` menu
5. ensured that VPN is connected in profile 2; confirmed VPN is connected to `USA (West)`
6. in profile 2, clicked on VPN and chose `Japan`
7. confirmed Profile 2 connected to `Japan` without issue
9. switched to profile 1 and selected `USA (North-West)`
10. switched to `VPN Profile 2` and confirmed I was connected to `USA (North-West)`

example | example | example | example | example | example
---------|---------|-----------|---------|---------|---------
<img width="1287" alt="Screen Shot 2022-11-28 at 5 00 36 PM" src="https://user-images.githubusercontent.com/387249/204413163-232cc99e-7454-414d-bd6b-80d9cfd7c591.png"> | <img width="1287" alt="Screen Shot 2022-11-28 at 5 01 02 PM" src="https://user-images.githubusercontent.com/387249/204413171-de99d299-5b45-471c-9470-6482989a7589.png"> | <img width="1182" alt="Screen Shot 2022-11-28 at 5 01 32 PM" src="https://user-images.githubusercontent.com/387249/204413192-fe0c171d-c738-486c-89ff-0390526f7a9d.png"> | <img width="1287" alt="Screen Shot 2022-11-28 at 5 01 38 PM" src="https://user-images.githubusercontent.com/387249/204413198-bb2b8566-bc61-48c9-8d30-b96fdbaea9f0.png"> | <img width="1287" alt="Screen Shot 2022-11-28 at 5 01 51 PM" src="https://user-images.githubusercontent.com/387249/204413199-a1038ea7-41b2-477d-b4ca-a8d920e6e069.png"> | <img width="1182" alt="Screen Shot 2022-11-28 at 5 02 06 PM" src="https://user-images.githubusercontent.com/387249/204413202-15bcdc52-f692-4a37-9eb2-ce30187d2f62.png">

**Comment by GeetaSarvadnya** [comment]
Verification inprogress

```
Brave | 1.46.130 Chromium: 108.0.5359.62 (Official Build) (64-bit)
-- | --
Revision | 041930a89a990cfab0315a2d9f20d6429a4a67cf-refs/branch-heads/5359@{#938}
OS | Windows 10 Version 21H2 (Build 19044.2251)

```

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.46.130 Chromium: 108.0.5359.62 (Official Build) (64-bit)
-- | --
Revision | 041930a89a990cfab0315a2d9f20d6429a4a67cf-refs/branch-heads/5359@{#938}
OS | Windows 11 Version 21H2 (Build 22000.1219)
```

### Steps:
1. installed `1.46.130`
2. purchased and configured VPN using `test4vpn@mailinator.com` from `account.bravesoftware.com` (staging)
3. connected to `BraveVPN`, and confirmed VPN is connected to default/nearest server `USA (West)`
4. created `VPN Profile 2` via the `"hamburger"` menu
5. ensured that VPN is connected in profile 2; confirmed VPN is connected to `USA (West)`
6. in profile 2, clicked on the `VPN` button and chose `Netherlands`
7. confirmed Profile 2 connected to `Netherlands` without issue
9. switched to profile 1 and selected `USA (NorthWest)`
10. switched to `VPN Profile 2` and confirmed I was connected to `USA (NorthWest)`

#### Confirmed `Can't connect to server error` is not rendered when switching/connecting to new server/regions
step 3|step 5|step 6|step 7|step 9|step 10
-----|-----|-----|-------|------|------
<image width="780" alt="image" src="https://user-images.githubusercontent.com/98358127/204845409-d2a7cf8e-f847-4ecb-b87f-73d0f35cc4e5.png">|<image width="780" alt="image" src="https://user-images.githubusercontent.com/98358127/204845336-dddfdae6-e025-4164-98ff-a93eb06a72b3.png">|<image width="780" alt="image" src="https://user-images.githubusercontent.com/98358127/204845894-061dca5a-8c58-49ac-842a-c11159d32dc0.png">|<image width="780" alt="image" src="https://user-images.githubusercontent.com/98358127/204845939-8f099a0f-1816-4ac9-90e4-9904cba558a5.png">|<image width="780" alt="image" src="https://user-images.githubusercontent.com/98358127/204859559-967588ac-0e0f-4bda-80f3-9f9a32e0ecad.png">|<image width="780" alt="image" src="https://user-images.githubusercontent.com/98358127/204859596-1e5e5fc2-01c0-4e39-ac1f-e460d08dde4d.png">
