### ISSUE TITLE
Optimize Welcome JS webpack bundle

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#26851]
```
❯ ROOT_GEN_DIR=$PWD/../out/Component_arm64/gen DEPFILE_PATH=$TMPDIR\d TARGET_GEN_DIR=$TMPDIR DEPFILE_SOURCE_NAME=wtf webpack --config components/webpack/webpack.config.js --progress --colors --json --mode=production welcome_test=$(pwd)/components/brave_welcome_ui/brave_welcome.tsx > $TMPDIR/stats.json
```

```
❯ npx webpack-bundle-analyzer $TMPDIR/stats.json
```

**Comment by nullhook** [comment]
`ROOT_GEN_DIR=$PWD/../out/Component_arm64/gen DEPFILE_PATH=$TMPDIR\d TARGET_GEN_DIR=$TMPDIR DEPFILE_SOURCE_NAME=wtf node_modules/.bin/webpack --config components/webpack/webpack.config.js --progress --colors --json --mode=production welcome_test=$(pwd)/components/brave_welcome_ui/brave_welcome.tsx > ~/tmp/stats.json`
