### ISSUE TITLE
Change "Log into" to "Log in to" in Logged out dropdown menu in Rewards panel

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#26858]
## Description

![image](https://user-images.githubusercontent.com/11497541/202762284-1f800639-157b-4f0e-ab17-9aaa430d1112.png)

- [ ] "Log into your {custodian} account" --> "Log in to your {custodian} account"

**Comment by stephendonner** [comment]
You are the wind beneath my wings, @Miyayes

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.47.114 Chromium: 108.0.5359.94 (Official Build) beta (x86_64)
-- | --
Revision | 713576b895246504ccc6b92c2fb8ce2d60194074-refs/branch-heads/5359_71@{#3}
OS | macOS Version 12.6.1 (Build 21G217)
```
