### ISSUE TITLE
Show Windows specific error message when creating VPN config fails

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#26852]
## Description
When we get failure during the os' vpn entry, we are at `ConnectionState::CONNECT_NOT_ALLOWED` state.
And we have been using macOS's error message on Windows also.
We should have window specific error message in this situation.
```
void BraveVPNOSConnectionAPI::OnCreateFailed() {
  VLOG(2) << __func__;

  // Clear connecting cancel request.
  if (cancel_connecting_)
    cancel_connecting_ = false;

  UpdateAndNotifyConnectionStateChange(ConnectionState::CONNECT_NOT_ALLOWED);
}
```

## Proposal
We already show an error for macOS. If the config fails to write:
<img src="https://user-images.githubusercontent.com/4733304/202636855-87a4ce88-1e05-4d10-a992-829c77d7aeb1.png" width="250px">

We should catch any error during the config writing process on Windows and show a Windows specific message
<img src="https://user-images.githubusercontent.com/4733304/202637303-76136e6d-9c9e-45c6-b18f-44534c13fd52.png" width="250px">

This was found today when @bridiver had an older build of Windows which had a problem with the RAS service. That was resolved by updating Windows with Windows update. The macOS message was showing for Windows which doesn't make any sense

**Comment by bsclifton** [comment]
Proposed text (from screenshot above):
> Failed to write the VPN config. This may happen if you don't have permission or if you haven't ran Windows Update recently

**Comment by LaurenWags** [comment]
Requires `1.46.122` or higher to test

**Comment by GeetaSarvadnya** [comment]
Verification inprogress

```
Brave | 1.46.123 Chromium: 108.0.5359.48 (Official Build) beta (64-bit)
-- | --
Revision | 18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}
OS | Windows 10 Version 21H2 (Build 19044.2251)

```
