### ISSUE TITLE
`Back to dashboard` should be `Back to Dashboard` in News customize window

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#26856]
## Description 

`Back to dashboard` should be `Back to Dashboard` in News customize window

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/202668861-3c4203f4-7db4-4bd9-be5e-a0ec03bc0ff0.png)

## Expected result:
![image](https://user-images.githubusercontent.com/17010094/202668975-3cb28c92-497e-4fc8-a9ca-b3b4ff577e22.png)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.47.82 Chromium: 108.0.5359.40 (Official Build) nightly (64-bit)
-- | --
Revision | `280b5fcaab3e877562b06cfaf2eb51121e13c3b9-refs/branch-heads/5359@{#689}`
OS | Windows 11 Version 22H2 (Build 22621.819)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @petemill @rmcfadden3 @brave/qa-team

**Comment by rebron** [comment]
@srirambv I'm not seeing this on macOS or Windows 1.47.85. Can you take a look again. I'm seeing it as "Back to Dashboard"

<img width="1053" alt="Screenshot 2022-11-18 at 9 12 02 AM" src="https://user-images.githubusercontent.com/5951041/202763257-c4184083-8c59-4422-a8ea-7a90b15866bf.png">

**Comment by mattmcalister** [comment]
Looks like that fix needs to happen here, yes? https://github.com/brave/brave-core/blob/48e5662831ef6c34c56189694fcb93eeca898591/components/resources/strings/brave_components_resources_en-GB.xtb#L1544

cc @fallaciousreasoning

**Comment by fallaciousreasoning** [comment]
Interesting, that looks like it's in a translation. Do we need to contact our vendor to do this?

**Comment by MadhaviSeelam** [comment]
Text reads `Back to Dashboard` as expected in Win 11.  Can be closed @srirambv?
```
Brave | 1.65.114 Chromium: 124.0.6367.60 (Official Build) (64-bit)
-- | --
Revision | f1e2cbb65e11340d9040d5ef0b0115c7a5206207
OS | Windows 11 Version 23H2 (Build 22631.3447)
```
 
![image](https://github.com/brave/brave-browser/assets/98358127/ffafdaed-fbd1-4d06-91d7-a33af179ee68)

**Comment by fallaciousreasoning** [comment]
I think I'm going to close.
