### ISSUE TITLE
Allow for VPN on Release channel

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#26867]
## Test plan
1. Wait until 1.46 is on Beta
2. Try to run steps from VPN test plan

## Description 
Changes needed so that VPN can move from Beta to Release with 1.46 😄 

VPN functionality is tied to the Beta/Dev/Nightly channel at the moment. We should expose this feature on brave://flags/#brave-vpn for Release also. It will still have the default value of false

**Comment by LaurenWags** [comment]
Labelling as `QA/Blocked` until we have a release channel build with 1.46.x.

**Comment by LaurenWags** [comment]
Removing `QA/Blocked` as we now have at least one 1.46.x RC

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.46.130 Chromium: 108.0.5359.62 (Official Build) (64-bit)
-- | --
Revision | 041930a89a990cfab0315a2d9f20d6429a4a67cf-refs/branch-heads/5359@{#938}
OS | Windows 10 Version 21H2 (Build 19044.2251)

```
- Verified the STR from the description and ensured below:
    - Ensured VPN flag can be enabled via brave://flags in RC
    - Ensured VPN can be purchased via account.bravesoftware.com in RC
    - Ensured creadentials are loaded successfully message is shown after purchasing the VPN
    - Ensured VPN can be enabled via VPN panel in the browser
    - Ensured VPN in the panel is disabled when VPN is disabled via windows VPN settings
    - Ensured VPN can be enabled via Hamburger menu->Brave VPN menu option
    - Ensured VPN can be disabled via Hamburger menu->Brave VPN menu option
    - Ensured VPN can be reconnected via windows VPN settings
    - Ensured VPN status is shown correctly in windows settings when VPN is connected/disconnected

Example | Example
---------|----------
![image (4)](https://user-images.githubusercontent.com/38657976/204586499-103c871b-69a9-4516-ab0a-2db174923988.png) | ![image (5)](https://user-images.githubusercontent.com/38657976/204586555-5765d4ef-22b1-4061-ba9c-7fc5ba932b36.png)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.46.130 Chromium: 108.0.5359.62 (Official Build) (64-bit)
-- | --
Revision | 041930a89a990cfab0315a2d9f20d6429a4a67cf-refs/branch-heads/5359@{#938}
OS | Windows 11 Version 21H2 (Build 22000.1219)
```

- Installed `1.46.130`
- launched Brave
      1. Ensured VPN flag can be enabled via brave://flags in RC
      2. Ensured VPN can be purchased via account.bravesoftware.com in RC
      3. Ensured creadentials are loaded successfully message is shown after purchasing the VPN
      4. Ensured VPN can be enabled via VPN panel in the browser
      5. Ensured VPN gets connected to nearest region by default (US - West)
      6. Ensured that VPN is status remained enabled upon browser restart
      7. Ensured that the default VPN region can be updated to other regions
      8. If user has multiple profiles (Profile 1 and Profile 2), enable VPN in profile 1 enables the VPN in Profile 2 as well
      9. Change the region in Profile 1 propagate the changes in Profile 2 and vice versa,both profile points to same IP via IPleak.net
      10. Ensured VPN in the panel is disabled when VPN is disabled via windows VPN settings
      11. Ensured VPN can be enabled via Hamburger menu->Brave VPN menu option
      12. Ensured VPN can be disabled via Hamburger menu->Brave VPN menu option
      13. Ensured VPN can be reconnected via windows VPN settings 
      14. Ensured VPN status is shown correctly in windows settings when VPN is connected/disconnected
      15. Installed `1.46.129` and enabled Brave VPN and then upgraded the profile to `1.46.130` and ensured VPN status remained enabled 
      
step 1|step2|step 3-5|step 8-9|step 10|step 11|step 12|step 15
--------|--------|-------|---------|--------|---------|------|-------
<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/204622349-b31077a7-b50b-4aa6-b36e-ddd5f6b32c1c.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/204622281-575266d7-ca7c-4368-b323-58fb1955cbd0.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/204622509-08562955-915a-42b3-a2aa-edece92c8dbc.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/204645208-e6e0de5d-a001-4157-ad05-fbb937d47407.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/204645478-115d5830-e25e-417c-9709-61541bcdee4f.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/204646319-ec151523-0526-4682-80c5-0f421c83e22c.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/204646385-f53bcb1a-70e8-4585-9595-07931dadafc0.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/204650604-a3dac56c-26e4-4326-ace2-62165c42da50.png">|<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/204650763-13aa6e0e-d76d-4c0d-841e-e46b104638bb.png">

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.46.131 Chromium: 108.0.5359.71 (Official Build) (64-bit)
-- | --
Revision | 1e0e3868ee06e91ad636a874420e3ca3ae3756ac-refs/branch-heads/5359@{#1016}
OS | Ubuntu 18.04 LTS

Verified vpn flag is not available brave://flags/#brave-vpn

![image](https://user-images.githubusercontent.com/34715963/204844281-7b4b0836-5d1b-44e7-ab2b-93ab85681f64.png)

Verified no VPN UI present
![image](https://user-images.githubusercontent.com/34715963/204844722-f3e7fd78-96be-454e-ac83-aac8bde6e69d.png)

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.46.131 Chromium: 108.0.5359.71 (Official Build) (x86_64)
-- | --
Revision | 1e0e3868ee06e91ad636a874420e3ca3ae3756ac-refs/branch-heads/5359@{#1016}
OS | macOS Version 13.1 (Build 22C5050e)



- Verified the STR from the description and ensured below:
    - Ensured VPN flag can be enabled via brave://flags in RC
    - Ensured VPN can be purchased via account.bravesoftware.com in RC
    - Ensured creadentials are loaded successfully message is shown after purchasing the VPN
    - Ensured VPN can be enabled via VPN panel in the browser
    - Ensured VPN gets connected to nearest region by default
    - Ensured that VPN status remained enabled upon browser restart
    - Ensured that the default VPN region can be changed to other regions
    - If user has multiple profiles (Profile 1 and Profile 2), enable VPN in profile 1 enables the VPN in Profile 2 as well
    - Change the region in Profile 1 propagate the changes in Profile 2 and vice versa,both profile points to same IP via IPleak.net
    - Ensured VPN in the panel is disabled when VPN is disabled via windows VPN settings
    - Ensured VPN can be enabled via Hamburger menu->Brave VPN menu option
    - Ensured VPN can be disabled via Hamburger menu->Brave VPN menu option
    - Ensured VPN can be reconnected via windows VPN settings
    - Ensured VPN status is shown correctly in windows settings when VPN is connected/disconnected
    - Installed `1.46.129` and enabled Brave VPN and then upgraded the profile to `1.46.130` and ensured VPN status remained enabled after the upgrade

_**Clean profile**_

Example | Example
---------|----------


- Ensured VPN UI is not shown when brave vpn flag is in "Default" state


_**Upgrade profile**_

- Installed `1.45.133` and upgraded the profile to `1.46.130` and ensured VPN is not enabled by default
- Ensured that VPN flag is available under brave://flags in an upgraded profile `1.46.130`
- Ensured VPN flag can be enabled  and VPN can be purchased in an upgraded profile
- Ensured VPN can be enabled in an upgraded profile

Example | Example | Example
---------|------------|--------
