### ISSUE TITLE
Remove widgets and supporting code

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#26865]
- Remove FTX widget (already disabled for the whole user base but removing the rest of the code)
- Remove Binance widget
- Remove crypto.com widget
- Remove Gemini widget
- Remove suggested sites (disabled by default and not used)

**Comment by bbondy** [comment]
FYI @rebron

**Comment by Uni-verse** [comment]
Verified on `Samsung GS 21` using version: 

```
Brave	1.48.157 Chromium: 110.0.5481.77 (Official Build) (64-bit) 
Revision	65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS	Android 13; Build/TP1A.220624.014
```

- Ensured the setting `show suggested sites in autocomplete` is removed on `fresh profile`
- Ensured the setting `suggested sites` setting is removed on `upgraded profile`
- Ensured suggested sites are not shown in the search content area on `1.48.157` if setting was enabled in previous version

1.47.x | 1.48.157
-|-
![screenshot-1675714634783](https://user-images.githubusercontent.com/17885425/217077207-24eee9c2-c3f3-42bd-b97d-ef295c4976f2.png) | ![screenshot-1675714691906](https://user-images.githubusercontent.com/17885425/217077211-9acb26dc-3231-4d81-9d50-2891bad7596b.png)
