### ISSUE TITLE
Add "ads enabled" pref in local state replicating setting of last loaded profile

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#26864]
Add an "ads enabled" pref in local state which replicates the enabled setting of the last loaded profile, so that the stats updater can retrieve the setting without having to depend on the profile.

Remove the profile observer and any calls to the ProfileManager from the stats updater (should fix #4599).

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.49.91 Chromium: 110.0.5481.77 (Official Build) beta (64-bit) 
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/16026

<details>



</details>

**Comment by btlechowski** [comment]
Verification passed on Brave v1.49.108 on Lenovo TB-8506FS (Android 11.0)

Verified test plan from https://github.com/brave/brave-core/pull/16026

There are no profile on Android so the test was limited to one profile

<details>

#### single profile - ads enabled
![image](https://user-images.githubusercontent.com/34715963/222520947-9cb5bd38-07bc-4f7a-8cb5-8dbae45113b8.png)


Usage ping:
```
https://laptop-updates.brave.com/1/usage/brave-core?platform=android-bc&channel=beta&version=1.49.108&daily=true&weekly=false&monthly=false&first=false&woi=2023-02-27&dtoi=2023-03-02&ref=BRV001&adsEnabled=true&arch=aarch64&wallet2=0
```

#### single profile - ads disabled
![image](https://user-images.githubusercontent.com/34715963/222521663-c2a90949-99af-479c-9fab-24675d256a82.png)

Usage ping:
```
https://laptop-updates.brave.com/1/usage/brave-core?platform=android-bc&channel=beta&version=1.49.108&daily=true&weekly=false&monthly=false&first=false&woi=2023-02-27&dtoi=2023-03-02&ref=BRV001&adsEnabled=false&arch=aarch64&wallet2=0
```
