### ISSUE TITLE
Widevine not prompted for install Google Play Movies

### ISSUE THREAD

**Issue by IOI-655321** [brave/brave-browser#2686]
## Description 
When trying to view video on Google Play Movies it doesnt prompt to install widevine

## Steps to Reproduce

   1. Go to https://play.google.com/movies and signin 
   2. Click to play a movie
   3. Error appears saying widevine not installed

## Expected result:
Video plays

## Reproduces how often: 
Every time

## Brave version (brave://version info)
0.58.16 Chromium: 71.0.3578.98 (Official Build) (64-bit)
Windows 10

### Website problems only:  
- No shields doesnt affect it.

### Additional Information
If I visit www.netflix.com it prompts me so i can work around this issue but it should prompt on google movies too.

**Comment by bbondy** [comment]
@iefremov thoughts?

**Comment by iefremov** [comment]
Not sure, what happened, maybe something changed in the upstream.
If this works in beta/dev, maybe we should resolve?

**Comment by IOI-655321** [comment]
Happy to close if this has been resolved in dev/beta builds.

**Comment by kjozwiak** [comment]
@IOI-655321 if you have time, would you mind checking quickly to see if your case was resolved? You can grab `dev` and `beta` from the following:

* https://brave.com/download-dev
* https://brave.com/download-beta

They'll use different profiles so it shouldn't affect your release profile.

**Comment by IOI-655321** [comment]
Yep can confirm on beta version that the widevine prompt appeared in the address bar.  It was initially a bit lost as it appeared alongside a pop up alert but when that went the widevine one remained and worked to install.

**Comment by kjozwiak** [comment]
Awesome, thanks for taking a look @IOI-655321, really appreciate it 👍 

> It was initially a bit lost as it appeared alongside a pop up alert but when that went the widevine one remained and worked to install.

Regarding difficulty seeing/noticing the Widevine notification, we're looking into ways to improve this. You can follow some of the discussion/progress in https://github.com/brave/brave-browser/issues/1940.

Going to close this off as the next release (`0.59.x`) will include the above fixes so this issue won't happen anymore. @IOI-655321, if you run into the issue again once `0.59.x` goes out the door, please don't hesitate to re-open or create a new issue.
