### ISSUE TITLE
Enable CosmeticFilteringJsPerformance by default

### ISSUE THREAD

**Issue by atuchin-m** [brave/brave-browser#26861]
The feature was implemented in https://github.com/brave/brave-browser/issues/25614
Cosmetic in child frames now is enabled by griffin in https://github.com/brave/brave-variations/pull/466
Now the feature should be enabled with the recommended parameters.
Slack thread: https://bravesoftware.slack.com/archives/C01LKMP6X36/p1668103608663869

Steps to verify:
1.  Cosmetic filtering should works as before, nothing should be changed. For sites with a lot of DOM changes another algorithm is used, but the results should be the same.
2. Child frames + Speedometer2 score: Enabling/disabling flag `BraveAdblockCosmeticFilteringChildFrames` shouldn't affect the score on https://browserbench.org/Speedometer2.0/. Pplease take into account that local results will have some deviations.

**Comment by LaurenWags** [comment]
@atuchin-m 

Can you please clarify 

> 1. Cosmetic filtering should works as before, nothing should be changed. For sites with a lot of DOM changes another algorithm is used, but the results should be the same.

from https://github.com/brave/brave-browser/issues/26861#issue-1455667296? Are there certain tests we should re-run, perhaps from a previous issue? Labelling as `QA/Blocked` until this is sorted.

cc @kjozwiak @rebron

**Comment by atuchin-m** [comment]
@LaurenWags
Just to clarify: this PR only enable the fix from https://github.com/brave/brave-browser/issues/26861.
The original fix changes the algorithm of detection of new elements that should be hidden by cosmetic filters.

As far as I concern we don't have a special test sites set. @pes10k @antonok-edm may be you know?

**Comment by atuchin-m** [comment]
Also I suggest the following test:
1. add this to brave://adblock custom filters: 
```
##.blocked-class-1
##.blocked-class-2
##.blocked-class-3
```
2. go to example.com and open dev tools console
3. run this script that creates a bunch of blocked elemets:
```
function addElements(cls, num) {
  for (let i = 0; i < num; i++) {
    const newDiv = document.createElement("div");
    const newContent = document.createTextNode("Bad ad, should be blocked;" + cls);
    newDiv.appendChild(newContent);
    newDiv.classList.add(cls);
    document.body.appendChild(newDiv);
  }
  console.log('Added ', num, 'elements with class', cls);
}

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

async function test() {
  addElements("blocked-class-1", 2000);

  await sleep(2000);
  addElements("blocked-class-2", 2000);

  await sleep(11000);
  addElements("blocked-class-3", 10);
  
  console.log('Done! Scroll to the end to check if there is any visible new element');
}
test()
```
4. Check if you see added element at the end of the document.
5. Remove added custom rules and repeat steps 2-4.

**Comment by LaurenWags** [comment]
@atuchin-m so should the result from whether you have the custom rules in above case be the same? Not quite clear on what the expected result is for step 5 when we re-run the case from https://github.com/brave/brave-browser/issues/26861#issuecomment-1335605869 without the added rules.

**Comment by atuchin-m** [comment]
The added elements simulate some unwanted ads and the custom rules simulate adblock files rules.

So if you have those custom rules them all the added element should be hidden.
If you don't have the rules: they should be visible.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.47.115 Chromium: 108.0.5359.94 (Official Build) beta (64-bit)
-- | --
Revision | 713576b895246504ccc6b92c2fb8ce2d60194074-refs/branch-heads/5359_71@{#3}
OS | Ubuntu 18.04 LTS

#### Cosmetic filtering not enabled - PASS

<details>

1. open `example.com`
1. Open dev tools
1. run the script from https://github.com/brave/brave-browser/issues/26861#issuecomment-1335605869
1. Wait till `Done! Scroll to the end to check if there is any visible new element` is shown in the console

Verified the dynamically added blocks are not blocked
![image](https://user-images.githubusercontent.com/34715963/205990767-ba4198df-4d8d-4c77-a7a9-7b0f4fb62826.png)
![image](https://user-images.githubusercontent.com/34715963/205990889-e1fdc188-46f6-424f-b45b-d7db80c3b266.png)
![image](https://user-images.githubusercontent.com/34715963/205990913-b911c3dd-3582-4881-809e-ef79f767ae18.png)


</details>


#### Cosmetic filtering enabled - PASS

<details>

1. add this to brave://adblock custom filters: 
```
##.blocked-class-1
##.blocked-class-2
##.blocked-class-3
```
1. open `example.com`
1. Open dev tools
1. run the script from https://github.com/brave/brave-browser/issues/26861#issuecomment-1335605869
1. Wait till `Done! Scroll to the end to check if there is any visible new element` is shown in the console

Verified the dynamically added blocks are blocked
![image](https://user-images.githubusercontent.com/34715963/205991078-e0c8bd6e-cf07-43ca-872a-4de087935814.png)
![image](https://user-images.githubusercontent.com/34715963/205991409-f8002517-2a72-4e5b-a407-081f03a1fba0.png)


</details>

**Comment by MadhaviSeelam** [comment]
Verification `PASSED`
```
Brave | 1.47.115 Chromium: 108.0.5359.94 (Official Build) beta (64-bit)
-- | --
Revision | 713576b895246504ccc6b92c2fb8ce2d60194074-refs/branch-heads/5359_71@{#3}
OS | Windows 11 Version 21H2 (Build 22000.1219)
```
### Cosmetic filtering not enabled - `PASSED`
1. install 1.47.115
2. launch Brave
3. open `example.com`
4. Open dev tools console
3. run the script in step 3 from https://github.com/brave/brave-browser/issues/26861#issuecomment-1335605869
5. Wait till `Done! Scroll to the end to check if there is any visible new element` is shown in the console

Confirmed the dynamically added blocks are not blocked

ex1|ex2|ex3
------|----|-----
<img width="469" alt="image" src="https://user-images.githubusercontent.com/98358127/206321104-4b9febc9-ff7c-4a7d-91ef-52e4d58b833c.png">|<img width="956" alt="image" src="https://user-images.githubusercontent.com/98358127/206321556-e682f47f-1764-493e-94d4-aa1dbe3ddaa0.png">|<img width="958" alt="image" src="https://user-images.githubusercontent.com/98358127/206325192-8dafc483-399e-4698-a670-75129a6dc891.png">


### Cosmetic filtering enabled - `PASSED`

1. continue from Case 1
2. open brave://adblock and add following:
     ```
     ##.blocked-class-1
     ##.blocked-class-2
     ##.blocked-class-3
     ```
3. refresh example.com site 
4. Open dev tools
3. run the script in step 3 from https://github.com/brave/brave-browser/issues/26861#issuecomment-1335605869
5. Wait till `Done! Scroll to the end to check if there is any visible new element` is shown in the console

Confirmed dynamically added blocks are blocked

ex1|ex2
----|-----
<img width="465" alt="image" src="https://user-images.githubusercontent.com/98358127/206320363-21892356-055f-4fa3-aeb3-78051ad9f5fc.png">|<img width="958" alt="image" src="https://user-images.githubusercontent.com/98358127/206325673-3348f869-bc91-4629-b0d8-4fa3b1f94e5a.png">

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using 

Brave | 1.47.123 Chromium: 108.0.5359.99 (Official Build) beta (x86_64)
-- | --
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | macOS Version 13.1 (Build 22C65)

## Cosmetic filtering not enabled - `PENDING`
<details>

</details>

## Cosmetic filtering enabled - `PENDING`

<details>

</details>

## Child frames + Speedometer2 score - `PENDING`

<details>

</details>

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Vivo X70 Pro version 12` running `Bravemonoarmx64.apk_1.47.165`

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy Tab S7` using the following build(s):

```
Brave	1.47.168 Chromium: 109.0.5414.87 (Official Build) (64-bit) 
Revision	2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS	Android 12; Build/SP2A.220305.013
```

<details><summary>Cosmetic filtering enabled</summary>

1. open example.com
2. Open dev tools
3. run the script from https://github.com/brave/brave-browser/issues/26861#issuecomment-1335605869
4. Wait till Done! Scroll to the end to check if there is any visible new element is shown in the console

- Verified that dynamically generated elements are blocked

Example | Example
-|-
![screenshot-1673369814069](https://user-images.githubusercontent.com/17885425/211615915-437c5961-ec10-4d8b-a745-d6e78e4ed3fd.png) | ![Screen Shot 2023-01-10 at 11 57 53 AM](https://user-images.githubusercontent.com/17885425/211615415-04dba6d2-71bd-4f32-aba5-75e40b7741a0.png)

</details>


<details><summary>Cosmetic filtering NOT enabled</summary>

1. open example.com
2. Open dev tools
3. run the script from https://github.com/brave/brave-browser/issues/26861#issuecomment-1335605869
4. Wait till Done! Scroll to the end to check if there is any visible new element is shown in the console

- Verified that dynamically generated elements are NOT blocked 

![Screen Shot 2023-01-10 at 11 50 39 AM](https://user-images.githubusercontent.com/17885425/211616325-45837699-d5ab-4f0c-ad83-541143bd5396.png)
![Screen Shot 2023-01-10 at 11 50 57 AM](https://user-images.githubusercontent.com/17885425/211616327-0ab059bc-ae30-41f1-b88b-f540bb915a78.png)
![Screen Shot 2023-01-10 at 11 51 16 AM](https://user-images.githubusercontent.com/17885425/211616330-afa8aae5-7cd5-4cad-81dd-94a44d985b91.png)

</details>

<details><summary>Speedometer Tests</summary>

#brave-adblock-cosmetic-filtering-child-frames Enabled | #brave-adblock-cosmetic-filtering-child-frames Disabled
-|-
![screenshot-1673370825899](https://user-images.githubusercontent.com/17885425/211618254-0f83052c-227a-494a-bf17-8f576baa3c02.png) | ![screenshot-1673371077235](https://user-images.githubusercontent.com/17885425/211618672-c96a453f-0a38-4357-ad4d-33d5aab6b8f2.png)


</details>
