### ISSUE TITLE
Update client-side copy from 100 Mbps to 500 Mbps with caveat/disclaimer

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#26860]
## Description 

Update client-side copy from 100mbps to 500mbps with caveat/disclaimer

## Steps to Reproduce

   1. install `1.46.113`
   2. launch Brave
   3. open `brave://flags`
   4. enable `VPN`
   5. click `Relaunch`
   6. load `https://account.bravesoftware.com/?intent=checkout&product=vpn`
   7. click on the `VPN` button in the browser toolbar
   8. note the `Mbps` bitrate in the copy for both website and client

## Actual result:

`account.bravesoftware.com` - `500 Mbps` | `Brave client` - `100 Mbps`
-------------|--------------
<img width="1132" alt="Screen Shot 2022-11-18 at 9 24 08 AM" src="https://user-images.githubusercontent.com/387249/202766013-b4d0febb-f913-4d67-84ed-c84a0ae2611b.png"> | <img width="1132" alt="Screen Shot 2022-11-18 at 9 24 49 AM" src="https://user-images.githubusercontent.com/387249/202766018-b74bed6d-e6ce-48a3-80d6-c343f332cd7e.png">

## Expected result:

Consistency.

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.46.113 Chromium: 107.0.5304.110 (Official Build) beta (x86_64)
-- | --
Revision | 2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}
OS | macOS Version 11.7.1 (Build 20G918)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

/cc @bsclifton @mattmcalister @AlanBreck @rmcfadden3 @brave/qa-team

**Comment by LaurenWags** [comment]
Requires `1.46.122` or higher to test

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.46.122 Chromium: 108.0.5359.48 (Official Build) beta (x86_64)
-- | --
Revision | 18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}
OS | macOS Version 11.7.1 (Build 20G918)

### Steps:
1. installed `1.46.122`
2. launched Brave
3. opened `brave://flags`
4. enabled VPN
5. clicked `Relaunch`
6. loaded `https://account.bravesoftware.com/?intent=checkout&product=vpn
7. clicked on the `VPN` button in the browser toolbar
8. noted the `Mbps` bitrate in the copy for both website and client

#### Confirmed the client now reads `500 Mbps`, which matches the website copy

<img width="1135" alt="Screen Shot 2022-11-21 at 7 50 43 PM" src="https://user-images.githubusercontent.com/387249/203217026-e1f1127e-012a-4454-b8ef-22d793d4993b.png">

**Comment by GeetaSarvadnya** [comment]
Verification inprogress


```
Brave | 1.46.131 Chromium: 108.0.5359.71 (Official Build) (64-bit)
-- | --
Revision | 1e0e3868ee06e91ad636a874420e3ca3ae3756ac-refs/branch-heads/5359@{#1016}
OS | Windows 10 Version 21H2 (Build 19044.2251)

```
