### ISSUE TITLE
slight difference in behavior of macOS Intel and M1 after VPN config is installed the first time

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#26863]
## Description 

macOS Intel and M1 behave slightly differently the first time VPN is installed/enabled on a machine.

## Steps to Reproduce

   1. Confirm any previous Brave VPN configs are removed from the machine
   2. Confirm any previous 1.46.x Beta browser profiles are deleted/moved
   3. Install `1.46.114` (currently the only `arm64` build available for M1 with all VPN fixes to date, so I used this version for both Intel and M1 checks) and launch
   4. Enable VPN flag, relaunch
   5. Navigate to account.bravesoftware.com
   6. Enter a fresh email address (not one used previously)
   7. Get email link, login, purchase VPN
   8. Once you get the success message on account.bravesoftware.com, click on the VPN button 
   9. Attempt to connect to VPN
   10. Get message that a VPN configuration needs to be installed
   11. Allow this config install
   12. Here's where things differ:
   - on Intel the config is installed and the VPN doesn't enable after config install. User needs to click on the VPN button again, toggle VPN on again, and then it connects (VPN button shows green dot).
   - on M1 the config is installed and the VPN connects. User doesn't need to do anything further. VPN button shows green dot.

Note, @stephendonner confirmed that Windows setup is similar to the way M1 works in that user doesn't need to toggle on a second time.

## Actual result:

Intel and M1 behave differently at step 12 above

## Expected result:

Intel and M1 behave the same at step 12

## Reproduces how often: 

100%

## Brave version (brave://version info)

1.46.114

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? unsure, probably yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @bsclifton @mattmcalister @stephendonner

**Comment by mattmcalister** [comment]
closing, although we will come back to these kinds of things to work on first-time use optimizations
