### ISSUE TITLE
Sync sends bookmarks even when chain is not fully created

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#2687]
## Description 

With Sync UI v2 sync chain is considered created when it has two or more devices.
Now we can see that bookmarks are sent even if there is only one device in chain, and the secon is not connected yet.

## Steps to Reproduce

   1. Launch brave browser in terminal 
   2. Open `brave://sync/` page
   3. Press `Start a new sync chain` button, don't add the second device to chain
   4. Look on terminal and wait

## Actual result:

  5. You will see messages saying bookmark records are sent to sync, like `sending record: {"action":0,"bookmark":{ ... `

## Expected result:
  5. No send to sync of bookmarks in this case, therefore no messages saying, bookmark records are sent to sync.

## Reproduces how often: 

Easyly

## Brave version (brave://version info)

Brave | 0.61.0 Chromium: 72.0.3626.17 (Developer Build) (64-bit)
-- | --
Revision | 08d2140079f8db14c9eb885a803d231b1a30e817-refs/branch-heads/3626@{#315}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Reproduced on nightly for sure.

**Comment by srirambv** [comment]
@AlexeyBarabash is this similar to #2148. In #2148 bookmark sync was disabled but still ended up showing on the other device. This issue mentioned about the logs in console about sending records even though sync chain isnt created.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.63.31 Chromium: 73.0.3683.75 (Official Build) beta(64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Mac OS X

- Verified STR from description. Reproduced issue on 0.62.x and verified did not see issue on 0.63.31.
