### ISSUE TITLE
Add a button to access "Keyboard shortcuts" for extension page

### ISSUE THREAD

**Issue by Cleveho** [brave/brave-browser#26872]
## Description 

Brave already have page "brave://extensions/shortcuts" for Keybaord shortcuts but no way to access it for normal users. 
There should be a button to access "Keyboard shortcuts" for extension on brave://extensions/ page.

## Steps to Reproduce

   1. Open brave://extensions/
   2. No button to access Keyboard shortcuts

## Actual result:

![Screenshot (434)](https://user-images.githubusercontent.com/48880976/202842163-7e51be79-c196-4f4e-bc4b-416e333805d6.png)

## Expected result:
![Screenshot (433)](https://user-images.githubusercontent.com/48880976/202842142-1d61f4de-37b1-4f0d-a463-d7a66cc6ede6.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.45.127 Chromium: 107.0.5304.110 (Official Build) (64-bit)
Revision | 2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{https://github.com/brave/brave-browser/issues/1202%7D
OS | Windows 11 Version 22H2 (Build 22621.819)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? no

**Comment by Cleveho** [comment]
Similar issue found - https://github.com/brave/brave-browser/issues/13061

**Comment by bsclifton** [comment]
@Cleveho I'm not sure if you're still using Brave - but we do have customizable keyboard shortcuts

You can visit brave://settings/system/shortcuts and now you can make a shortcut for **Manage extensions**
![image](https://github.com/brave/brave-browser/assets/4733304/e50ea2c1-ed49-426e-b7c0-a9746706a3c0)

**Comment by bsclifton** [comment]
And I need to learn to read 😂 

The original complaint you had is solved now actually. On the left, there's the Keyboard Shortcuts
![image](https://github.com/brave/brave-browser/assets/4733304/7cd6db1a-c7e7-435d-8df6-8520eeb95f8e)
