### ISSUE TITLE
`Can't connect to server` dialog remains after renabling Wi-Fi and reconnecting to `BraveVPN`

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#26879]
## Description 

`Can't connect to server` dialog remains after renabling Wi-Fi and reconnecting to `BraveVPN`

## Steps to Reproduce

1. install `1.47.87`
2. launch Brave
3. open `brave://flags`
4. set `brave://flags/#brave-vpn` to `Enabled`
5. purchase VPN from `account.bravesoftware.com`
6. click on the `VPN` button in the browser toolbar
7. ensure you're connected
8. disconnect via any method (browser toolbar, flyout menu-items, `Network` panel -> `BraveVPN` in macOS's `System Preferences...`)
9. ensure correct status is reflected in the remainder of the UI and in the `Network` panel
10. disable Wi-Fi
11. try to reconnect to `BraveVPN`
12. confirm you get the `Can't connect to server` dialog
13. re-enable Wi-Fi
14. confirm VPN is not connected
15. click on the `VPN` button
16. click on `Choose another server`
17. select any network region
18. click `Connect`
19. confirm you are connected to `BraveVPN` now
20. look at the dialog on the `VPN` button

## Actual result:

The dialog still says `Can't connect to server`, 

example | example
-----|----------
<img width="989" alt="Screen Shot 2022-11-19 at 9 40 58 AM" src="https://user-images.githubusercontent.com/387249/202864642-f508ce8c-b3fe-4db3-ba30-974b6e00d56f.png"> | ![vpn-retry](https://user-images.githubusercontent.com/387249/202866255-bb15334b-15f9-414c-be88-512c21d72132.gif)

## Expected result:

<img width="991" alt="Screen Shot 2022-11-19 at 9 52 16 AM" src="https://user-images.githubusercontent.com/387249/202864662-4b5d0ea2-2c54-4dcd-bf3c-7d459ad52bd0.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.47.87 Chromium: 108.0.5359.48 (Official Build) nightly (arm64)
--|--
Revision | 18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}
OS | macOS Version 11.7.1 (Build 20G918)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

/cc @mattmcalister @bsclifton @simonhong @spylogsster @brave/qa-team @rebron

**Comment by GeetaSarvadnya** [comment]
dup of https://github.com/brave/brave-browser/issues/26579

**Comment by stephendonner** [comment]
As @GeetaSarvadnya said, duplicate of https://github.com/brave/brave-browser/issues/26579.
