### ISSUE TITLE
[Brave News]: If Brave News is open in multiple tabs, they should remain in sync

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#26884]
Expected:
Changes to Brave News in one tab are reflected in others

Actual:
No changes are propagated until the tab is reloaded.

This change is a stepping stone to https://github.com/brave/brave-browser/issues/26631

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.47.110 Chromium: 108.0.5359.71 (Official Build) beta (x86_64)
-- | --
Revision | 1e0e3868ee06e91ad636a874420e3ca3ae3756ac-refs/branch-heads/5359@{#1016}
OS | macOS Version 13.1 (Build 22C5059b)

### Steps:
1. installed `1.47.110`
2. launched Brave
3. opened a new-tab page
4. opted in to `Brave News`
5. subscribed to `CNN` and `Fox News`
6. confirmed both sources, in two side-by-side tabs
7. unfollowed `CNN` from `tab 1`
8. confirmed `CNN` was gone and `Fox News` remained, when clicking on `Load new content` in `tab 2`
9. unfollowed `Fox News` from `tab 2`
10. followed `Dailywire`
11. confirmed `Fox News` was gone when clicking on `Load new content` in `tab 1`
12. confirmed `Dailywire` articles (solely) in both `tab 1` and `tab 2`

example | example | example | example | example | example | example | example | example
---------|----------|---------|----------|---------|----------|----------|---------|---------
<img width="1680" alt="Screenshot 2022-12-03 at 7 35 55 PM" src="https://user-images.githubusercontent.com/387249/205473149-5ba1fc79-65ce-421a-9673-2b5156a4b9cb.png"> | <img width="909" alt="Screenshot 2022-12-03 at 7 36 32 PM" src="https://user-images.githubusercontent.com/387249/205473153-55b45de2-51e2-47d3-851b-af4afbe332e1.png"> | <img width="909" alt="Screenshot 2022-12-03 at 7 36 38 PM" src="https://user-images.githubusercontent.com/387249/205473154-4055078e-1436-4193-baf1-035d0d84e836.png"> | <img width="985" alt="Screenshot 2022-12-03 at 7 37 41 PM" src="https://user-images.githubusercontent.com/387249/205473156-6cbb0bca-8731-448b-9d5d-35ba30a9ed3f.png"> | <img width="985" alt="Screenshot 2022-12-03 at 7 38 07 PM" src="https://user-images.githubusercontent.com/387249/205473158-37d1423e-b6f8-4725-bb19-2d5a208e35b3.png"> | <img width="1680" alt="Screenshot 2022-12-03 at 7 38 36 PM" src="https://user-images.githubusercontent.com/387249/205473159-da1b6a11-94e0-449b-af6c-221c9c0c9048.png"> | <img width="909" alt="Screenshot 2022-12-03 at 7 38 44 PM" src="https://user-images.githubusercontent.com/387249/205473160-2db79c8b-8856-4939-8cc5-3d29d1d78a74.png"> | <img width="909" alt="Screenshot 2022-12-03 at 7 38 48 PM" src="https://user-images.githubusercontent.com/387249/205473161-2601125f-6d89-4907-8b08-46a93c55c8d1.png"> | <img width="1680" alt="Screenshot 2022-12-03 at 7 50 07 PM" src="https://user-images.githubusercontent.com/387249/205473397-d85d4c5a-a41a-4012-9df3-0e930e01ee15.png">
