### ISSUE TITLE
[Brave News]: The Popular/Suggestions Carousels have a tiny bit of vertical scroll

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#26909]
If you hover the mouse over the gap between the cards in the Popular or Suggestions Carousels and scroll the mouse wheel the cards shift up/down a tiny amount. This shouldn't happen.

**Comment by LaurenWags** [comment]
@fallaciousreasoning please provide a test plan/steps since this is marked as `QA/Yes`. Maybe an example of the issue occurring for reference would also be helpful.

Marking as `QA/Blocked` until this is sorted.

cc @kjozwiak @rebron @petemill

**Comment by petemill** [comment]
@LaurenWags the steps would just be what was described in the description above. It was a very minor issue but it's on 1.46.x if you want to compare. I'll update the description with bullet-point steps.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.47.120 Chromium: 108.0.5359.99 (Official Build) dev (x86_64)
-- | --
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | macOS Version 13.1 (Build 22C65)

Followed the steps in https://github.com/brave/brave-browser/issues/26909#issue-1458562072 and could reproduce both the issue and the fix.

`before fix` "wiggle" | `after fix` "no wiggle"
----------|---------
![news-scroll](https://user-images.githubusercontent.com/387249/206639747-c8d0330f-4369-4472-9437-38d8b9f67ece.gif) | ![news-scroll-fixed](https://user-images.githubusercontent.com/387249/206640546-72a36d91-c985-46d0-9255-70586b8d2a58.gif)
