### ISSUE TITLE
[Android] Redirect to `brave://rewards` settings page when user presses "Brave Rewards" button in native browser settings menu , and make sure brave://rewards page is fully reset after Rewards profile reset

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#26902]
## Description

Redirect to brave://rewards/ when users press on “Rewards” section in native browser settings. 

The brave://rewards/ is now at parity thanks to https://github.com/brave/brave-browser/issues/24570. 

- [ ] Move the "Show Ads when Brave is not in use" toggle into the general notifications section of browser settings
- [ ] Make sure Manage > Reset Rewards section on brave://rewards is visible and works on Android (which will replace the "Reset Brave Rewards" button)
- [ ] Ensure that after reset, brave://rewards page is in fresh state that shows user the "Start using Brave Rewards" screen. This button should pop open the Rewards panel when pressed.

<img src="https://user-images.githubusercontent.com/11497541/203100393-b952c83e-6eef-4440-8dba-67f1163a1d5f.png" height=300px>

___________

Related: https://github.com/brave/brave-browser/issues/20894

@anthonypkeane @timchilds

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Vivo x70 Pro version 12` running `Bravemonoarmx64.apk_1.57.19`

**Comment by GeetaSarvadnya** [comment]
>Move the "Show Ads when Brave is not in use" toggle into the general notifications section of browser settings

@deeppandya I don't see "Show Ads when Brave is not in use" toggle in `notifications` section of browser settings, could you please let me know where this setting is been moved to. Thanks!

cc: @Miyayes

**Comment by deeppandya** [comment]
> >Move the "Show Ads when Brave is not in use" toggle into the general notifications section of browser settings
> 
> @deeppandya I don't see "Show Ads when Brave is not in use" toggle in `notifications` section of browser settings, could you please let me know where this setting is been moved to. Thanks!
> 
> cc: @Miyayes 

Sorry @GeetaSarvadnya need to update the issue. That setting option is part of appearance now with title `Brave rewards icon`
