### ISSUE TITLE
Brave search widget callout button text is cut off [Galaxy S21]

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#26903]
## Description 
Brave search widget button text `Not now` is cut off

## Steps to reproduce 

   1. Install 1.47
   2. Tap on the URL bar
   3. Observe Brave Search Widget callout

## Actual result 
`Not now` slightly cut off on the right

English | German
-|-
![screenshot-1669044507864](https://user-images.githubusercontent.com/17885425/203094079-704ab259-5fde-46e0-afac-2156c1f9a7bd.png) | ![screenshot-1673380084532](https://user-images.githubusercontent.com/17885425/211655641-5463d03d-915c-4528-ab88-599eba50b29e.png)

## Expected result
button should not be cut off, provide a bit of margin/padding on right

## Issue reproduces how often 
Always

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? N/A
- Can you reproduce this issue with the current Play Store Beta version? N/A
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM 
   - Device type (Phone, Tablet, Phablet): Samsung Galaxy S21 5G
   - Android version: 12
   
## Brave version
1.47.85

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.47.171` or higher for `1.47.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version:

```
Brave	1.47.171 Chromium: 109.0.5414.87 (Official Build) (64-bit) 
Revision	2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS	Android 12; Build/SP1A.210812.016
```

Test Steps: 

1. Install 1.47
2. Complete onboarding
3. Tap on URL box
4. Confirm widget intro modal shows
5. Select `Add Widget`
6. Confirm Home screen widget modal shows
7. Select `Add`
8. Confirm Brave quick action widget has been added to home screen

- Confirmed widget intro is displayed when tapping on the url box
- Confirmed widget intro content is not cut off or blocked
- Confirmed user is able to select`Add widget` or `Now now`
- Confirmed brave quick action widget matches specs
- Confirmed user is able to open private tab, search and voice search using the widget features

Widget intro | Widget Modal | Widget added | Using widget search | Using voice search
-|-|-|-|-
![screenshot-1673533798489](https://user-images.githubusercontent.com/17885425/212095815-0977352b-0935-44fa-aeae-4309b91e0149.png) | ![screenshot-1673533805980](https://user-images.githubusercontent.com/17885425/212095824-2210a558-107f-431b-824f-07ebcae7b298.png) | ![screenshot-1673533819993](https://user-images.githubusercontent.com/17885425/212095831-7b6b1093-8d96-462d-a980-cb27e1d1ecbb.png) | ![screenshot-1673533827037](https://user-images.githubusercontent.com/17885425/212095848-508a255c-b8c8-43b3-bc82-ca8362afea02.png) | ![screenshot-1673533836709](https://user-images.githubusercontent.com/17885425/212095850-b4001588-c1f8-409b-86ca-4f625fbd9b52.png)
