### ISSUE TITLE
Remove link subscription option

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#26906]
This issue is the follow up issue of https://github.com/brave/brave-browser/issues/21972 to remove link subscription option if user doesn't have active subscription.

**Comment by kjozwiak** [comment]
We'll need to wait for a `1.47.x` RC on the `release` channel before we can QA the above due to the limitation of not being able to run through VPN on `beta`.

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` & `Samsung Galaxy Tab S7` using the following version(s):

```
Brave	1.47.164 Chromium: 109.0.5414.74 (Official Build) (64-bit) 
Revision	e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}
OS	Android 12; Build/SP1A.210812.016
```

- Ensured that `BraveVPNLinkSubscriptionAndroidUIStudy` is `Enabled` under brave://version
- Ensured that Link Subscription option is not shown when user is not subscribed to VPN
- Ensured `Link Purchase to your Brave Account` is shown when user has an active subscription
- Ensured `Link Purchase to your Brave Account` is removed after subscription expiration date elapses and user attempts to enable VPN again.

Example | Example | Example | Example | Example | Example
-|-|-|-|-|-
![screenshot-1672959749424](https://user-images.githubusercontent.com/17885425/210897975-4e6a8905-d2aa-41c1-b6d2-83154681d577.png) | ![screenshot-1672960084916](https://user-images.githubusercontent.com/17885425/210897977-fdaee33a-6b0a-4984-b4c3-f6d5ed29a39a.png) | ![screenshot-1672960094053](https://user-images.githubusercontent.com/17885425/210897978-1ac8047f-e817-42f2-992b-ddf54799e19b.png) | ![screenshot-1672960223118](https://user-images.githubusercontent.com/17885425/210897979-b7172b8e-39af-4f3e-935e-a26bdfa377b1.png) | ![screenshot-1672954472292](https://user-images.githubusercontent.com/17885425/210898064-b6d25524-08cb-4af4-b172-034c250caba0.png) | ![screenshot-1672960525923](https://user-images.githubusercontent.com/17885425/210898164-e3175949-896b-4f27-9091-d34188f1a3bb.png)
