### ISSUE TITLE
Update ads status header hosts list

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#26904]
Add following hosts: safesearch.brave.com, safesearch.brave.software, safesearch.bravesoftware.com

The `X-Brave-Ads-Enabled` header description: https://github.com/brave/brave-browser/wiki/Custom-Headers#x-brave-ads-enabled

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.47.177 Chromium: 109.0.5414.87 (Official Build) (64-bit) 
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | Ubuntu 18.04 LTS


Verified test plan from https://github.com/brave/brave-core/pull/16043

#### Test case 1 - `https://safesearch.brave.com/` - clean profile
<details>

Verified `X-Brave-Ads-Enabled` header is not set in the request after opening https://safesearch.brave.com/

![image](https://user-images.githubusercontent.com/34715963/213519870-af9944fc-193d-4f43-9040-5a86f7a0f04b.png)

Verified `X-Brave-Ads-Enabled` header is not set in the request after using the search box on https://safesearch.brave.com/
![image](https://user-images.githubusercontent.com/34715963/213520297-b92eecce-a9a0-4430-8290-a3d66c6cb039.png)


</details>

#### Test case 2 - `https://safesearch.brave.com/` - ads enabled
<details>

Verified `X-Brave-Ads-Enabled` header is set in the request after opening https://safesearch.brave.com/
![image](https://user-images.githubusercontent.com/34715963/213520884-c433aa84-5c6e-455f-8e89-c26383baba68.png)


Verified `X-Brave-Ads-Enabled` header is set in the request after using the search box on https://safesearch.brave.com/
![image](https://user-images.githubusercontent.com/34715963/213521000-1563f4e9-da3f-46da-8ecc-0f0a8e986ffc.png)


</details>

#### Test case 3 - `window.brave.getCanSetDefaultSearchProvider` on `https://github.com/`
<details>

`window.brave.getCanSetDefaultSearchProvider`
![image](https://user-images.githubusercontent.com/34715963/213522444-75f85d59-abec-4217-abf9-1abc6fadc75f.png)


`window.brave.setIsDefaultSearchProvider`
![image](https://user-images.githubusercontent.com/34715963/213522529-c9a1c703-83d8-47ef-9e55-52946216b61f.png)


</details>

#### Test case 4 - `window.brave.getCanSetDefaultSearchProvider` on `https://safesearch.brave.com/`
<details>

`window.brave.getCanSetDefaultSearchProvider`
![image](https://user-images.githubusercontent.com/34715963/213522802-fd74b99e-81eb-458e-ab77-8aa7d41ac826.png)


`window.brave.setIsDefaultSearchProvider`
![image](https://user-images.githubusercontent.com/34715963/213522923-23f02938-0118-4734-b885-961a6ca648a0.png)


</details>

#### Test case 5 - `https://github.com/` when ads enabled
<details>

Verified `X-Brave-Ads-Enabled` header is not set in the request 
![image](https://user-images.githubusercontent.com/34715963/213523729-c7ecc825-3cf6-43b0-8fa5-329a10e5dcad.png)


</details>

#### Test case 6 - `https://safesearch.brave.com/` when ads disabled
<details>

ads disabled
![image](https://user-images.githubusercontent.com/34715963/213524311-c193ab1e-65f6-4fd2-81ee-ed75f867b9b3.png)

Verified `X-Brave-Ads-Enabled` header is not set in the request after opening https://safesearch.brave.com/
![image](https://user-images.githubusercontent.com/34715963/213524640-5ae8aa9a-770c-4945-9d1b-952b6e57cc1c.png)



Verified `X-Brave-Ads-Enabled` header is not set in the request after using the search box on https://safesearch.brave.com/
![image](https://user-images.githubusercontent.com/34715963/213524757-8924331b-4f72-402f-ba0c-2b7005d86cce.png)


</details>

**Comment by btlechowski** [comment]
Verification passed on Brave v1.48.151 on Lenovo TB-8506FS (Android 11.0)

Verified test plan from https://github.com/brave/brave-core/pull/16043

#### Test case 1 - `https://safesearch.brave.com/` - clean profile
<details>

Verified `X-Brave-Ads-Enabled` header is not set in the request after opening https://safesearch.brave.com/
![image](https://user-images.githubusercontent.com/34715963/216679906-c4dfd6ea-ebe0-43ad-8c60-ac05c5fdb416.png)


Verified `X-Brave-Ads-Enabled` header is not set in the request after using the search box on https://safesearch.brave.com/
![image](https://user-images.githubusercontent.com/34715963/216679727-fbcadcfd-06cf-4c44-a195-b67b9f08a531.png)



</details>

#### Test case 2 - `https://safesearch.brave.com/` - ads enabled
<details>

Verified `X-Brave-Ads-Enabled` header is set in the request after opening https://safesearch.brave.com/
![image](https://user-images.githubusercontent.com/34715963/216679836-4a444e17-dec0-47e2-8f99-9d97e341ca6b.png)

Verified `X-Brave-Ads-Enabled` header is set in the request after using the search box on https://safesearch.brave.com/
![image](https://user-images.githubusercontent.com/34715963/216680149-a27571f6-660b-4b18-bc3c-27c0b414a8bc.png)


</details>

#### Test case 3 - `window.brave.getCanSetDefaultSearchProvider` on `https://github.com/`
<details>

`window.brave.getCanSetDefaultSearchProvider`
![image](https://user-images.githubusercontent.com/34715963/216680247-e0204657-36ce-4ab0-a079-e681f3547d91.png)



`window.brave.setIsDefaultSearchProvider`
![image](https://user-images.githubusercontent.com/34715963/216680279-b4610004-e237-4195-943a-2028eedaf5f0.png)



</details>

#### Test case 4 - `window.brave.getCanSetDefaultSearchProvider` on `https://safesearch.brave.com/`
<details>

`window.brave.getCanSetDefaultSearchProvider`
![image](https://user-images.githubusercontent.com/34715963/216680345-16dfa8ae-95fe-444d-b5a0-33afae5df3ea.png)



`window.brave.setIsDefaultSearchProvider`
![image](https://user-images.githubusercontent.com/34715963/216680385-2d7c96d9-eb76-46d1-877f-80848077e4b6.png)



</details>

#### Test case 5 - `https://github.com/` when ads enabled
<details>

Verified `X-Brave-Ads-Enabled` header is not set in the request 
![image](https://user-images.githubusercontent.com/34715963/216680482-ecbecf22-6683-4261-9c05-ff68ba142c79.png)


</details>

#### Test case 6 - `https://safesearch.brave.com/` when ads disabled
<details>

Verified `X-Brave-Ads-Enabled` header is not set in the request after opening https://safesearch.brave.com/
![image](https://user-images.githubusercontent.com/34715963/216680673-6b91776b-d1c6-45c0-b951-c648922bb86e.png)

Verified `X-Brave-Ads-Enabled` header is not set in the request after using the search box on https://safesearch.brave.com/
![image](https://user-images.githubusercontent.com/34715963/216680858-0ad0a342-371b-4ba5-8324-7d1f52d4c37e.png)

</details>
