### ISSUE TITLE
Revert transak or put it behind a feature flag

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#26912]
Revert https://github.com/brave/brave-browser/issues/26737 or put it behind an off-by-default flag until some issues are resolved

Internal discussion: https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1669064270926839?thread_ts=1668964482.399289&cid=C023VS4HJ6Q

**Comment by diracdeltas** [comment]
seems this can be closed? @rebron

**Comment by kjozwiak** [comment]
> seems this can be closed? @rebron

Quickly chatted with @srirambv, this was already reverted by @srirambv from `1.46.x` via https://github.com/brave/brave-core/pull/16053 and it was also reverted from `master` via https://github.com/brave/brave-core/pull/16054.
