### ISSUE TITLE
Add desktop menu dismiss rate P3A metric

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#26913]
Add P3A metric for the main app menu dismiss rate on desktop.

How often is the menu triggered and dismissed without an action taken in the past week?
`Brave.Toolbar.MenuDismissRate`

0. Menu was not opened in the past week
1. Less than 25% (exclusive) of opens
2. Between 25% (inclusive) and 50% (exclusive) of opens
3. Between 50% (inclusive) and 75% (exclusive) of opens
4. More than 75% of opens

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.49.90 Chromium: 110.0.5481.77 (Official Build) beta (64-bit)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | Windows 10 Version 21H2 (Build 19044.2486)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/16049

**Comment by DJAndries** [comment]
> Open a menu and dismiss it 1 time yields the response as `3`

In this case, 3 sounds correct. You opened the menu twice and only dismissed it once. The dismiss rate is 50%.

**Comment by GeetaSarvadnya** [comment]
@DJAndries I could see the metrics `Brave.Toolbar.MenuDismissRate` in Android  also `Bravemonoarmx64.apk_1.49.100`. Looks like the metrics is implemented only for Desktop as per the test plan https://github.com/brave/brave-core/pull/16049.

**Comment by DJAndries** [comment]
@GeetaSarvadnya Good catch, raised #28660
