### ISSUE TITLE
Profile Icon Should be Removed when not enabled

### ISSUE THREAD

**Issue by razorsyntax** [brave/brave-browser#2692]
## Description 
Remove and Disable Profile Button

## Steps to Reproduce

   1. Open Brave
   2. See Profile Icon/Button when not logged in

## Actual result:
Profile Icon/Button sits beside settings when it's not being used.

## Expected result:
Profile Icon/Button should have the option of being removed when not used.

**Comment by razorsyntax** [comment]
From a high level, a profile represents a specific user and the associated features.  If I want to use the browser without any "profile-related" features (like those in your screenshot dropdown, excluding `Open Tor Window` and `Close all your windows`), then why should I need to see it?  We can hide the home button and even extensions from view but it doesn't make sense that we can't do the same for the Profile Button.

In that dropdown list there's Passwords, Payment Methods, Addresses and more.  Those are (arguably) profile associated features.  I don't care about any of that and won't be using them as a user.  So why can't those features associated with profile be disabled or ***at the very least hidden from view to simulate the idea of "disabling" a profile***?

Fundamentally, the ability to hide the icon altogether from the menu without necessarily affecting functionality is the simplest way to simulate this idea.

**Comment by rebron** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/5091.
