### ISSUE TITLE
Follow up of PR #16052 - VPN can't be reconnected in the same session when internet/wifi is disconnected and reconnected

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#26938]
## Description 

Follow up of PR #16052 - VPN can't be reconnected in the same session when internet/wifi is disconnected and reconnected

Verified the issue on `Windows 10 x64` for 4 times. All the 4 times unable to reconnect the VPN in the same browser session, `Can't connect to server` error message remained forever even after click on try again

## Steps to Reproduce

   1. Clean profile `1.47.94`
   2. Follow the steps from the issue https://github.com/brave/brave-browser/issues/23081#issue-1249556377
   

## Actual result:

VPN can't be reconnected in the same session when internet/wifi is disconnected and reconnected

![VPN disconnect and reconnect in the same session](https://user-images.githubusercontent.com/38657976/203387380-f73bfbe7-7fe6-4420-a5a4-2e1f19357425.gif)

## Expected result:
Should be able to reconnect the VPN in the same browser session when wifi is reconnected
## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.47.94 Chromium: 108.0.5359.48 (Official Build) nightly (64-bit)
-- | --
Revision | 18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}
OS | Windows 10 Version 21H2 (Build 19044.2251)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @bsclifton @simonhong @mattmcalister @brave/qa-team

**Comment by GeetaSarvadnya** [comment]
@stephendonner @MadhaviSeelam Could you both post your observations on this issue? Thanks

**Comment by stephendonner** [comment]
### Steps (which don't work for me in either Windows or macOS):

1. install `1.47.94`
2. launch Brave
3. open `brave://flags`
4. set `brave://flags/#brave-vpn` to `Enabled`
5. purchase VPN from `account.bravesoftware.com`
6. click on the VPN button in the browser toolbar
7. ensure you're connected
8. disconnect via any method (browser toolbar, flyout menu-items, Network panel -> BraveVPN in macOS's System Preferences...)
9. ensure correct status is reflected in the remainder of the UI and in the Network panel
10. disable Wi-Fi
11. try to reconnect to `BraveVPN`
12. confirm you get the Can't connect to server dialog
13. re-enable Wi-Fi
14. confirm VPN is not connected
15. click on the VPN button
16. click on `Choose another server`
17. select any network region
18. click `Connect`
19. confirm you are connected to `BraveVPN` now
20. look at the dialog on the `VPN` button

macOS | Win10
--------|------
![vpn-macos](https://user-images.githubusercontent.com/387249/203389178-6e15c339-81b2-49cd-9c73-33d8aad87f41.gif) | ![vpn-win](https://user-images.githubusercontent.com/387249/203389344-7ad64d6b-7316-4248-b397-1a7f858ee20c.gif)

**Comment by MadhaviSeelam** [comment]
For ` Win 11 x64`,  followed same steps from the issue:  https://github.com/brave/brave-browser/issues/23081#issue-1249556377

1. new install `1.47.94`
2. purchased new VPN account

Actual Results: 
1. successfully connected after disconnecting WiFi and reconnecting it in the same browser session. 
2. However, I see `Connecting....` spins in the VPN modal but Windows-->settings-->Network&internet-->VPN-->Brave VPN shows connected status in following scenarios: 
    - Keep the system idle for few minutes and disconnect WiFi and reconnect
    - Select different region (eg. US-West-->Japan), after successful connection



https://user-images.githubusercontent.com/98358127/203394226-cfc519d5-2c11-4ecb-9b44-7f4315ccdc06.mp4

**Comment by stephendonner** [comment]
Can confirm my issue is fixed using 

Brave | 1.48.2 Chromium: 108.0.5359.48 (Official Build) nightly (x86_64)
-- | --
Revision | 18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}
OS | macOS Version 11.7.1 (Build 20G918)

![vpn-retry](https://user-images.githubusercontent.com/387249/203840348-0fb707ad-fcfd-4567-b47f-2e266407213f.gif)

**Comment by GeetaSarvadnya** [comment]
Verified the issue against the build `1.48.10` issue is fixed and working fine:  

```
Brave | 1.48.10 Chromium: 108.0.5359.48 (Official Build) nightly (64-bit)
-- | --
Revision | 18ceeca0d99318e70c00d2e04d88aa55488b5c63-refs/branch-heads/5359@{#854}
OS | Windows 10 Version 21H2 (Build 19044.2251)

```

![Panel connected status not updated when wifi turned off_1](https://user-images.githubusercontent.com/38657976/204520071-d496b6e4-cbee-4666-a6f0-d7e003b24343.gif)

 Encountered 2 new issues while testing the issue

1. Click on `Try again` in VPN panel connects the VPN immediately in single attempt but VPN status is still shown as "Connecting" in the windows settings  - This will be addressed by the PR https://github.com/brave/brave-browser/issues/27026
2. VPN panel status not updated correctly when wifi is disconnected and connected multiple times (2nd, 3rd and so on), no issues with panel status in the 1st time wifi disconnect and reconnect. Looks like cache issue

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.46.130 Chromium: 108.0.5359.62 (Official Build) (64-bit)
-- | --
Revision | 041930a89a990cfab0315a2d9f20d6429a4a67cf-refs/branch-heads/5359@{#938}
OS | Windows 11 Version 21H2 (Build 22000.1219)
```
#### Confirmed VPN is connected in the same session when WiFi was disconnected and reconnected

https://user-images.githubusercontent.com/98358127/204922498-e1b6f449-a07d-4565-99ac-c8340f4e15ec.mp4

Encountered same as above issues in Win 11 x64
https://github.com/brave/brave-browser/issues/27026
https://github.com/brave/brave-core/pull/16126
