### ISSUE TITLE
Shields cookie settings - wildcard created during toggle from block => allow => block

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#26939]
## Description 
If you visit a website `www.example.com`

And you toggle the cookie settings to `Allow all cookies` and then back to `Block cross-site cookies` again, it creates an entry with a wildcard
`[*.]example.com`

Which will effectively allow all cookies on other subdomains of `example.com`
But the block (Block 3rd party cookies) only applies to the `www.example.com` specifically

## Steps to Reproduce

   1. Visit https://www.cnn.com/
   2. Use shields panel to toggle cookie settings to `Allow all cookies`
   3. Let page reload
   4. Use shields panel to toggle cookie settings to `Block cross-site cookies`
   5. Let the page reload

## Actual result:
Wildcard is created after step 4
![image](https://user-images.githubusercontent.com/4733304/203388040-ffbc569d-9381-47d7-8051-ca5e730d8f0b.png)

But the block rule is in place for the www.cnn.com
![image](https://user-images.githubusercontent.com/4733304/203388122-5f2f1daa-f53d-434c-81ca-2ee1187a8759.png)

## Expected result:
Wildcard should never be created

## Reproduces how often: 
100%

## Desktop Brave version:
Nightly

Likely on Beta and Release also

## Version/Channel Information:

- Can you reproduce this issue with the current release? **YES**
- Can you reproduce this issue with the beta channel? UNKNOWN
- Can you reproduce this issue with the nightly channel? UNKNOWN
>

**Comment by GeetaSarvadnya** [comment]
@bsclifton looks like this issue also related to the issue https://github.com/brave/brave-browser/issues/26288 on which @spylogsster is currently working on.

**Comment by bsclifton** [comment]
Reproduced on 1.45.127
![image](https://user-images.githubusercontent.com/4733304/203399859-9e5eb01e-7080-4c6c-a0be-f884da36533d.png)

**Comment by bsclifton** [comment]
Reprioritized as P2 during Desktop triage; we won't stop the current release we have planned... but we will get this into a hotfix as soon as we have diagnosed, found root cause, and have a fix

**Comment by bridiver** [comment]
This actually looks correct after all. The secondary (site) pattern is www.cnn.com so this just treats `*.cnn.com` as first party on www.cnn.com
