### ISSUE TITLE
Enable notifications message on Android 13 should only be shown once 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#26930]
## Description 
Enable notifications message on Android 13 should only be shown once 

## Steps to reproduce 

Same as https://github.com/brave/brave-core/pull/15407

## Actual result 
Notification is shown every time the app is restarted

## Expected result
Should only show once 

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: 13
   
## Brave version
1.47.91

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

Discussed [here ](https://bravesoftware.slack.com/archives/C03MMJ4CHEZ/p1669046019389189)
cc: @timchilds @sujitacharya2005

**Comment by kjozwiak** [comment]
The above requires `1.46.130` or higher for `1.46.x` verification 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung Galaxy Tab S8 Ultra` running `Android 13` using the following build(s):

```
Brave | 1.46.133 Chromium: 108.0.5359.71 (Official Build) (32-bit)
--- | ---
Revision | 1e0e3868ee06e91ad636a874420e3ca3ae3756ac-refs/branch-heads/5359@{#1016}
OS | Android 13; Build/TP1A.220624.014
```

Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/26930#issue-1460129700, ensured the following:

* ensured that the `You're not receiving Privacy Reports` modal only appears once when dismissing via
  * using `X`, clicking on `Not now` or clicking on `Turn on Brave notifications` (but not enabling)
  * ensured that the modal never re-appears again (visiting settings/restarted the browser etc..)

https://user-images.githubusercontent.com/2602313/205129978-26679b73-0d57-4dd9-92a2-9b860d4373e8.mp4

* ensured that the `You're not earning Rewards` modal only appears once when dismissing via
  * using `X`, clicking on `Not now` or clicking on `Turn on Brave notifications` (but not enabling)
  * ensured that the modal never re-appears again (visiting settings/restarted the browser etc..)

https://user-images.githubusercontent.com/2602313/205130144-43894cc5-4c7c-48c3-82fc-fa1ec2fb7457.mp4

* ensured that the `You're not earning Rewards or receiving Privacy Reports` modal only appears once when dismissing via
  * using `X`, clicking on `Not now` or clicking on `Turn on Brave notifications` (but not enabling)
  * ensured that the modal never re-appears again (visiting settings/restarted the browser etc..)

https://user-images.githubusercontent.com/2602313/205130345-6033fc4b-df79-48d0-9a5e-e480611d438f.mp4

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung Galaxy S10+` running `Android 13` using the following build(s):

```
Brave | 1.46.133 Chromium: 108.0.5359.71 (Official Build) (32-bit)
--- | ---
Revision | 1e0e3868ee06e91ad636a874420e3ca3ae3756ac-refs/branch-heads/5359@{#1016}
OS | Android 13; Build/T1B3.221003.008
```

Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/26930#issue-1460129700, ensured the following:

* ensured that the `You're not receiving Privacy Reports` modal only appears once when dismissing via
  * using `X`, clicking on `Not now` or clicking on `Turn on Brave notifications` (but not enabling)
  * ensured that the modal never re-appears again (visiting settings/restarted the browser etc..)

https://user-images.githubusercontent.com/2602313/205144185-bc61f8ac-c373-4f62-8bd2-74679111038c.mp4

* ensured that the `You're not earning Rewards` modal only appears once when dismissing via
  * using `X`, clicking on `Not now` or clicking on `Turn on Brave notifications` (but not enabling)
  * ensured that the modal never re-appears again (visiting settings/restarted the browser etc..)

https://youtube.com/shorts/hDsoFPFA-Uc

* ensured that the `You're not earning Rewards or receiving Privacy Reports` modal only appears once when dismissing via
  * using `X`, clicking on `Not now` or clicking on `Turn on Brave notifications` (but not enabling)
  * ensured that the modal never re-appears again (visiting settings/restarted the browser etc..)

https://youtu.be/oBa-qJXLJQ0
