### ISSUE TITLE
small typo in Manage Your Wallet copy

### ISSUE THREAD

**Issue by josephjguerra** [brave/brave-browser#2693]
## Description 

Small copy typo on Manage Your Wallet screen.  Currently says: "It\'s probably safest..." with a backslash. Remove the \  so it reads: "It's probably safest..."

## Steps to Reproduce

   1. chrome://rewards/#
   2. Click the gear cog at top right near Your wallet
   3. See the error in the copy at the bottom

## Actual result:

It\'s probably safest

## Expected result:

It's probably safest...

## Reproduces how often: 

Every time

## Brave version (brave://version info)

Version 0.58.16 Chromium: 71.0.3578.98 (Official Build) (64-bit)

Brave | 0.58.16 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Mac OS X
JavaScript | V8 7.1.302.3

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

not sure

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.60.17 Chromium: 72.0.3626.64 (Official Build) dev (64-bit)
-- | --
Revision | eaa9668e80ce5405e7f1902579558ea725c06ca1-refs/branch-heads/3626@{#708}
OS | Windows 7

![image](https://user-images.githubusercontent.com/34715963/51909058-e17e6100-23cb-11e9-9225-2c4de5037d53.png)
