### ISSUE TITLE
Secure WebSocket connection to the loopback adapter fails to connect 

### ISSUE THREAD

**Issue by kross-italk** [brave/brave-browser#26940]
## Description 
In Brave, a webpage at https://example.com cannot connect to a WebSocket hosted locally at wss://127.0.0.1:8999. 
In Chrome, it is possible to make this connection. 

## Steps to Reproduce

   1. Host a WebSocket Secure service on the loopback interface, with self signed certs. See: https://github.com/websockets/ws#external-https-server
   2. In Brave, connect to wss://127.0.0.1:8999. Connection fails
   3. In Google Chrome, connect to the same. Connection succeeds. 

## Actual result:

In Brave, connection to wss://127.0.0.1:8999 fails

## Expected result:
Parity with Google Chrome. 

## Reproduces how often: 

Always

## Desktop Brave version:

[Version 1.45.127 Chromium: 107.0.5304.110 (Official Build) (64-bit)](https://brave.com/latest/)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

I have not tried. As this is for work, I'm not interested in using an unstable channel. 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
Yes, it does!
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 
Yes, this feature works as expected on Chrome. 

## Miscellaneous Information:

Is there a flag in brave settings for this? It makes sense that a security focused browser would disable this.

**Comment by ShivanKaul** [comment]
Fixed by https://github.com/brave/brave-core/pull/17321
