### ISSUE TITLE
Wallet P3A sends a large amount of queries at the same time

### ISSUE THREAD

**Issue by wchen342** [brave/brave-browser#26949]
## Description 
The current implementation of P3A in Android wallet uses a query function that was not desinged for its purpose. This causes two problems:

1. It sends a large amount API requests at the same time when the wallet is opened, some of them unnecessary (prices, etc.).
2. Because portfolio also queries for balances and the information is not shared, some of the balances are queried twice.

**Comment by diracdeltas** [comment]
what query is this? i'm not seeing it on https://github.com/brave/brave-browser/wiki/P3A.

**Comment by wchen342** [comment]
@diracdeltas I think it is [Q74](https://github.com/brave/brave-browser/wiki/P3A#q74-as-an-active-ethsolfil-user-that-currently-has-an-active-account-or-previously-has-had-one-how-many-accounts-do-you-have-with-a-non-zero-balance). The problem comes from [this part](https://github.com/brave/brave-core/pull/15145/files#diff-30eae7637d039986bb60e7d56d19a411894f2bce4725def3d4dd0945ea5edc72R1586) because that function call sends multiple requests each time it is called, and was put in a loop.
