### ISSUE TITLE
[Android] Enable `Show scrollable MVT on NTP` feature by default

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#26942]
## Description 
This feature makes top sites section scrollable

https://user-images.githubusercontent.com/30602739/203410669-4f1ebdfe-6f2d-483c-84e7-fa6712b50d04.mp4

## Steps to reproduce 

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above will require `1.47.140` or higher for `1.47.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Vivo X70 Pro version 12` running `Bravemonoarmx64.apk_1.47.16`

**_Clean profile_**

- Ensured that the `top sites` in a NTP are scrollable
- Ensured that user can tap on the top sites and open the sites

https://user-images.githubusercontent.com/38657976/211314759-b2a0a701-19be-4e63-9de7-b86a5ea73cae.mp4


**_Upgrade profile_**

- Ensured that the `top sites` in a NTP are scrollable
- Ensured that user can tap on the top sites and open the sites

https://user-images.githubusercontent.com/38657976/211314814-0fed5cc5-cfc9-4b9c-9030-9f005fbcf6d8.mp4
