### ISSUE TITLE
Offer Route Around Twitter's Modal

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#26945]
## Description 

When an unauthenticated user visits Twitter.com, and begins scrolling through recent posts on a channel, they will soon encounter a modal inviting them to sign-up/in to continue. This modal obscures the content on the page, and cannot be dismissed.

![image](https://user-images.githubusercontent.com/815158/203424872-ecc4f172-b82d-4d90-b455-a53ff043b5e1.png)

Brave should consider/explore a method for clearing the modal, and enabling users to continue viewing the obscured content. If a user wishes to sign-up/in, they can do so from the sidebar.

## Steps to Reproduce
1. In a private window, navigate to https://twitter.com/brave/
2. Scroll down the page until a modal is presented

## Expected result:
User should not be interrupted by the non-dismissible modal.

## Reproduces how often: 
Easily.

## Desktop Brave version:
1.45.127

## Other Additional Information:

Discussed on Twitter: https://twitter.com/BrendanEich/status/1594925703807606786

## Miscellaneous Information:
Extensions exist currently which aim to achieve similar results: https://chrome.google.com/webstore/detail/breakthrough-twitter-logi/ohhifopcgokjpbnppnmjbdnjnfcfnlep

**Comment by jonathansampson** [comment]
It may be enough to simply block a particular _onboarding_ request to prevent this issue entirely: https://twitter.com/konarkmodi/status/1595176344266035201

**Comment by ryanbr** [comment]
Can't be worked around without breaking login. Safer to leave alone to avoid possible breakages.  @jonathansampson
