### ISSUE TITLE
Seeing empty area behind the app menu button in toolbar when vertical tab flag is enabled but not used

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#26948]
## Steps to Reproduce

   1. Enable vertical tab flag but not enabled vertical tab
   2. 
   3. 

## Actual result:

![image](https://user-images.githubusercontent.com/6786187/203466355-3cfc230f-c165-4f95-8dc1-a0e5ab32b307.png)

## Expected result:
No empty area behind the app menu button

## Reproduces how often: 

Eash

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @sangwoo108 

Tested on macOS and Windows and macOS is ok. Not sure on linux.

**Comment by Chaitanya7666** [comment]
@simonhong Could you please elaborate more about the issue? Please highlight the part of the image where the problem exists. Thanks!

**Comment by simonhong** [comment]
> @simonhong Could you please elaborate more about the issue? Please highlight the part of the image where the problem exists. Thanks!

Hamburger button should be attached to right side of browser window like below. but there are some space between button and right border of window in the above screenshot.
![image](https://user-images.githubusercontent.com/6786187/203727074-5486924e-85b5-4496-b0d3-d20cfb5b0971.png)
