### ISSUE TITLE
update text on Tips panel  - follow up to 2499

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#2695]
## Description 
Follow up to issue 2499

Issue 2499 addressed removing text about tipping on like from Tips panel, however, if Rewards are turned off the Tips panel still mentions tipping on 'Like' and Twitter. This other text can also be seen when Tips panel is viewed immediately after Rewards are enabled, before any sites are visited.

## Steps to Reproduce

   1. Clean profile
   2. Enable Rewards
   3. Before visiting any sites, view Tips panel on brave://rewards
   4. If Rewards are already enabled, turn them off.

## Actual result:
Text in bullet points mentions Twitter and tipping on Like.
![screen shot 2018-12-21 at 4 29 59 pm](https://user-images.githubusercontent.com/28145373/50364699-2dbdc200-053f-11e9-9cb0-2d68517e41b6.png)

## Expected result:
Text would be adjusted since tipping Tweets and on 'Like' is not yet implemented.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.59.12 Chromium: 72.0.3626.17 (Official Build) beta(64-bit)
-- | --
Revision | 08d2140079f8db14c9eb885a803d231b1a30e817-refs/branch-heads/3626@{#315}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
cc @mandar-brave @rebron

**Comment by NejcZdovc** [comment]
@davidtemkin what should be a text here?

**Comment by davidtemkin** [comment]
The bullet point text should be: 

"Tip on the spot as you find gems."
"Support your favorite sites with recurring monthly tips."

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.60.23 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Mac OS X

* Verified bullet point text in Tips panel immediately after enabling Rewards
* Verified bullet point text in Tips panel when Rewards are turned off
* Verified bullet point text matches https://github.com/brave/brave-browser/issues/2695#issuecomment-455802934
![screen shot 2019-02-08 at 11 45 39 am](https://user-images.githubusercontent.com/28145373/52492499-55242900-2b97-11e9-8748-66047b1b3553.png)
