### ISSUE TITLE
Fix long account name wrapping on new send tab

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#26958]
## Description 
Fix word wrapping for long account names on the new send tab.

<img width="399" alt="Screen Shot 2022-11-23 at 3 00 07 PM" src="https://user-images.githubusercontent.com/40611140/203645233-c35b9759-3428-4073-b238-38de04d04cb9.png">

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.48.141 Chromium: 109.0.5414.119 (Official Build) beta (64-bit) 
-- | --
Revision | `772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}`
OS | Linux

- Verified steps from [brave/brave-core#16075](https://github.com/brave/brave-core/pull/16075)
- Verified long names are wrapped to show properly

![image](https://user-images.githubusercontent.com/17010094/215458304-b9090cd2-6abf-4e5e-989f-7331f80bdb57.png) | ![image](https://user-images.githubusercontent.com/17010094/215458463-50960926-ad5c-4086-bebd-f33e99d5678b.png)
-- | --
---------------------

Verification passed on 

Brave | 1.48.141 Chromium: 109.0.5414.119 (Official Build) beta (64-bit)
-- | --
Revision | `772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#16075](https://github.com/brave/brave-core/pull/16075)
- Verified long names are wrapped to show properly

![image](https://user-images.githubusercontent.com/17010094/215457707-2bc46182-80d0-44de-b717-9008b0ec9533.png) | ![image](https://user-images.githubusercontent.com/17010094/215457778-da867aca-5cc2-49ec-bfef-032c6fa33746.png)
-- | --

---------------------

Verification passed on 

Brave | 1.48.141 Chromium: 109.0.5414.119 (Official Build) beta (arm64)
-- | --
Revision | `772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#16075](https://github.com/brave/brave-core/pull/16075)
- Verified long names are wrapped to show properly

![image](https://user-images.githubusercontent.com/17010094/215458723-6289f959-6121-4623-a8c8-fed30e8606ae.png) | ![image](https://user-images.githubusercontent.com/17010094/215458826-d5e5b15a-98a3-424f-b139-eb802a2c0ccc.png)
-- | --
