### ISSUE TITLE
Show smaller message for invalid checksum error

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#26957]
## Description 
We need to show a small message for the `Invalid Checksum` error, maybe show more info in a tooltip.

![Screen Shot 2022-11-23 at 2 56 23 PM](https://user-images.githubusercontent.com/40611140/203644890-2be40812-3690-46a1-90b2-b9bb888b50d0.png)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.50.93 Chromium: 111.0.5563.64 (Official Build) beta  (64-bit) 
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Linux

- Verified steps from [brave/brave-core#17026](https://github.com/brave/brave-core/pull/17026)
- Verified pasting an address all in lowercase (`0x7d66c9ddaed3115d93bd1790332f3cd06cf52b14`) shows checksum warning message with yellow border and still allows to review order 
- Verified clicking on `How can I solve it?` loads a new modal with info
- Verified pasting and searching for the address in `https://etherscan.io` and copying the formatted address into send field clears the message
- Verified pasting an address with one character in lowercase (`0x7d66c9ddAED3115d93Bd1790332f3Cd06Cf52b14`) shows the checksum error message in red
- Verified `Review Order` button is disabled when the checksum error warning is shown in red

https://user-images.githubusercontent.com/17010094/225878478-3a82d9fb-fbf9-4c06-9d95-faedc10c92f3.mp4


---------------------

Verification passed on 

Brave | 1.50.93 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from [brave/brave-core#17026](https://github.com/brave/brave-core/pull/17026)
- Verified pasting an address all in lowercase (`0x7d66c9ddaed3115d93bd1790332f3cd06cf52b14`) shows checksum warning message with yellow border and still allows to review order 
- Verified clicking on `How can I solve it?` loads a new modal with info
- Verified pasting and searching for the address in `https://etherscan.io` and copying the formatted address into send field clears the message
- Verified pasting an address with one character in lowercase (`0x7d66c9ddAED3115d93Bd1790332f3Cd06Cf52b14`) shows the checksum error message in red
- Verified `Review Order` button is disabled when the checksum error warning is shown in red

https://user-images.githubusercontent.com/17010094/225877465-5cea38b2-731b-4d97-866e-3d189f90b327.mp4


---------------------

Verification passed on 

Brave | 1.50.93 Chromium: 111.0.5563.64 (Official Build) beta (arm64)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#17026](https://github.com/brave/brave-core/pull/17026)
- Verified pasting an address all in lowercase (`0x7d66c9ddaed3115d93bd1790332f3cd06cf52b14`) shows checksum warning message with yellow border and still allows to review order 
- Verified clicking on `How can I solve it?` loads a new modal with info
- Verified pasting and searching for the address in `https://etherscan.io` and copying the formatted address into send field clears the message
- Verified pasting an address with one character in lowercase (`0x7d66c9ddAED3115d93Bd1790332f3Cd06Cf52b14`) shows the checksum error message in red
- Verified `Review Order` button is disabled when the checksum error warning is shown in red

https://user-images.githubusercontent.com/17010094/225878776-b090fdb2-3419-4694-88e1-aa8f493591e7.mov
