### ISSUE TITLE
Add a loading state while API resolves domains

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#26956]
## Description 
We should add some loading state while domains are being resolved by our api's.

https://user-images.githubusercontent.com/40611140/203644260-4e20417f-d4e2-488c-9d7d-d3e0a587267e.mov

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.48.141 Chromium: 109.0.5414.119 (Official Build) beta (64-bit) 
-- | --
Revision | `772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}`
OS | Linux

- Verified steps from [brave/brave-core#16127](https://github.com/brave/brave-core/pull/16127)
- Verified loading state is shown when domain is being resolved

https://user-images.githubusercontent.com/17010094/214895004-1ee02eb2-2c28-4ddd-8f72-7b9b69db8451.mp4

---------------------

Verification passed on 

Brave | 1.48.141 Chromium: 109.0.5414.119 (Official Build) beta (64-bit)
-- | --
Revision | `772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#16127](https://github.com/brave/brave-core/pull/16127)
- Verified loading state is shown when domain is being resolved

https://user-images.githubusercontent.com/17010094/214895471-4e2f3d69-3f1a-42e9-b2dc-61db8be58895.mp4

---------------------

Verification passed on 

Brave | 1.48.141 Chromium: 109.0.5414.119 (Official Build) beta (arm64)
-- | --
Revision | `772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#16127](https://github.com/brave/brave-core/pull/16127)
- Verified loading state is shown when domain is being resolved

https://user-images.githubusercontent.com/17010094/214896091-1c714e1c-edc8-4b9d-981f-051a85e4e282.mov
