### ISSUE TITLE
Upgrade from Chromium 107.0.5304.110 to Chromium 107.0.5304.141.

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#26965]
# Minor Chromium bump

https://chromium.googlesource.com/chromium/src/+log/107.0.5304.110..107.0.5304.141?pretty=fuller&n=10000

# QA tests:

* Check branding items
* Check for version bump

# Additional checks:
* No specific code changes in Brave (only line number changes in patches)

**Comment by kjozwiak** [comment]
Closing as https://github.com/brave/brave-core/pull/16082 has been uplifted into `1.45.x`.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung Galaxy S10+` running `Android 12` using the following build(s):

```
Brave | 1.45.133 Chromium: 107.0.5304.141 (Official Build) (32-bit)
--- | ---
Revision | cddb1ab381a982f400a57e15e14080e1aaaca4b8-refs/branch-heads/5304_105@{#3}
OS | Android 12; Build/SP1A.210812.016
```

**`Example`** | **`Example`**
---------------|------------------
![Screenshot_20221124-231632_Brave](https://user-images.githubusercontent.com/2602313/203900412-21d4869c-518b-4092-ad29-a492183a89e5.jpg) | ![Screenshot_20221124-231621_Brave](https://user-images.githubusercontent.com/2602313/203900415-eba6f8d5-e94f-4f81-b11d-e5d507568e8a.jpg)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 13.0 Ventura x64` using the following build(s):

```
Brave | 1.45.133 Chromium: 107.0.5304.141 (Official Build) (x86_64)
--- | ---
Revision | cddb1ab381a982f400a57e15e14080e1aaaca4b8-refs/branch-heads/5304_105@{#3}
OS | macOS Version 13.0 (Build 22A380)
```

<img width="1206" alt="Screenshot 2022-11-25 at 12 02 38 AM" src="https://user-images.githubusercontent.com/2602313/203904991-448297aa-0b29-4247-ad52-dc4d5f6bebbb.png">
