### ISSUE TITLE
Remove all images for unverified publishers on Brave Rewards 

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#2696]
For the Tip-Panel, Tip-Banner, Thank you pages, remove the images for unverified publishers. Leave verified flow intact.

cc @NejcZdovc @diracdeltas @davidtemkin

**Comment by kjozwiak** [comment]
Went through verifications on the following platforms:

* macOS 10.14.2 x64 - Verification **PASSED**
* Ubuntu 18.04.1 x64 VM - Verification **PASSED**

Used the following build:

Brave | 0.58.17 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}

<img width="471" alt="screen shot 2018-12-23 at 8 27 20 am" src="https://user-images.githubusercontent.com/2602313/50384040-b26a2680-068c-11e9-882e-6ca1fd423099.png">

<img width="1239" alt="screen shot 2018-12-23 at 8 27 36 am" src="https://user-images.githubusercontent.com/2602313/50384041-b5fdad80-068c-11e9-9907-6bcd51023364.png">

<img width="1214" alt="screen shot 2018-12-23 at 8 29 46 am" src="https://user-images.githubusercontent.com/2602313/50384056-efceb400-068c-11e9-9b5e-9975b70bc1df.png">

<img width="481" alt="screen shot 2018-12-23 at 8 27 50 am" src="https://user-images.githubusercontent.com/2602313/50384043-c01fac00-068c-11e9-9d3f-cbc78aff32a3.png">

<img width="1236" alt="screen shot 2018-12-23 at 8 27 57 am" src="https://user-images.githubusercontent.com/2602313/50384046-c6ae2380-068c-11e9-9668-9e9c9168b70f.png">

**Comment by kjozwiak** [comment]
## Possible Issues

It appears that we're still displaying favicons under the `Rewards` panel for websites, example:

<img width="430" alt="screen shot 2018-12-23 at 8 31 44 am" src="https://user-images.githubusercontent.com/2602313/50384073-3ae8c700-068d-11e9-8e36-687bd988f878.png">

<img width="450" alt="screen shot 2018-12-23 at 8 31 53 am" src="https://user-images.githubusercontent.com/2602313/50384074-3c19f400-068d-11e9-8d6b-8d1e29c4df37.png">
