### ISSUE TITLE
Playlist media dector script bugs on android youtube.

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#26976]
### Why does this happen?

```
YouTube pages have task scheduler, which is based on requestAnimationFrame().
And <title> is updated as the scheduler ticks and their app state transitions
to “rendering” state. So my theory is that as we load the page on background,
requestAnimationFrame() isn’t fired and it remains at the very initial state.
```

### How can we avoid this?
iOS folks make an invisible webview below all the UI and load the contents on it.

### checklist

- [ ] title is always "Youtube"
  - also no title attribute on video tag
  - `"no title attribute on the node: <video tabindex=\"-1\" class=\"video-stream html5-main-video\" style=\"width: 815px; height: 458px; left: 0px; top: 0px;\" controlslist=\"nodownload\" src=\"blob:https://m.youtube.com/89b0a8ac-a65e-4f4e-9d29-686629efccfb\"></video>"`
  - In this case, we use document title as video title, but it seems title isn't updated at all ~~yet at the time of executing.~~ 
- [ ] No thumbnail
  - There's no og tag for the page. Instead, there's a div container which shows thumbnail
  - `<div class="ytp-cued-thumbnail-overlay-image" style="background-image: url(&quot;https://i.ytimg.com/vi/XJ0dI2SYHIE/sddefault.jpg&quot;);"></div>`

* ~~We could use ~~`JSON.parse(document.querySelector("script[type='application/ld+json']").innerHTML)` to get title and thumbnail for the pages - this is also updated dynamically.

```
{"@context":"https://schema.org","@type":"VideoObject","description":"최근 실시간 강의 내용 요약입니다.\n전체 실시간 강의 링크 : https://youtu.be/OjSOF8f9vdw\n\n🤝 채널을 후원하고 추가영상도 보세요!\nhttps://www.youtube.com/channel/UCKpcxgzrqu7dcolZf5Dpx_Q/join\n\n🔥 정리/복습 채널 :\nhttps://www.youtube.com/channel/UC2RrA_-QBjnu800xevk4N_Q\n\n☕️라이브아카데미 네이버 카페 :\nhttps://cafe.naver.com/liveacademy/\n\n#영어회화 #영어표현 #실시간요약","duration":"PT1581S","interactionCount":"39373","name":"자주 쓰는 영어 패턴 6개💡","thumbnailUrl":["https://i.ytimg.com/vi/1rogmWk8uI4/maxresdefault.jpg"],"uploadDate":"2022-11-03","embedUrl":"https://www.youtube.com/embed/1rogmWk8uI4?start=13","genre":"Education","author":"라이브 아카데미 토들러"}
```

**Comment by sangwoo108** [comment]
FYI @szilardszaloki

**Comment by bsclifton** [comment]
Closing as the new approach we can use (injection-less) can detect the videos via Global Media Controls.
