### ISSUE TITLE
Link subscription follow up issue

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#26977]
This issue is follow up to https://github.com/brave/brave-core/pull/16044
Please follow the test plan from : https://github.com/brave/brave-core/pull/16044

**Comment by kjozwiak** [comment]
The above requires `1.46.133` or higher for `1.46.x` verification 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 13` using the following build(s):

```
Brave | 1.46.133 Chromium: 108.0.5359.71 (Official Build) (32-bit)
--- | ---
Revision | 1e0e3868ee06e91ad636a874420e3ca3ae3756ac-refs/branch-heads/5359@{#1016}
OS | Android 13; Build/T1B3.221003.008
```

Using the instructions via https://github.com/brave/brave-core/pull/10408#issuecomment-939396800, launched Brave using the Griffin staging sever as per the following:

![image](https://user-images.githubusercontent.com/2602313/204950366-c2f28957-9deb-44a8-a80f-2eb90d26ca96.png)

Went through the following STR/Cases:

* ensured that `BraveVPNLinkSubscriptionAndroidUIStudy:Enabled` via `brave://version` after restarting the browser
* ensured that `Link purchase to your Brave account` isn't visible when there's no active subscription after enabling VPN
* ensured that `Link purchase to your Brave account` appears/is visible once a subscription is active (used monthly test card)
* ensured that `Link purchase to your Brave account` is removed once the subscription expires after ~35mins
  * note: as per @deeppandya, there needs to be an interaction with VPN before the `Link` UI is removed
* ensured that `Link purchase to your Brave account` is removed once the subscription has been manually cancelled
  * note: as per @deeppandya, there needs to be an interaction with VPN before the `Link` UI is removed
* ensured that the `Link purchase to your Brave account` was removed once a subscription expired and the following was done:
  * attempted to restore a expired subscription, attempted to switch regions when subscription expired
* ensured that tapping on the `Link purchase to your Brave account` UI opens `account.brave.com`

**`Launching Brave without a subscription and then subscribing and ensuring "Link" UI appears`**

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|---------------|---------------|---------------|---------------|---------------|---------------|--------------
![Screenshot_20221201-122321](https://user-images.githubusercontent.com/2602313/205138816-0df9f76a-8a5e-4c34-b42b-49d76f29cbab.png) | ![Screenshot_20221201-122334](https://user-images.githubusercontent.com/2602313/205138825-bbcea999-54bd-44a2-8799-cf8d1946f446.png) | ![Screenshot_20221201-122405](https://user-images.githubusercontent.com/2602313/205138831-8a2ec366-3425-46b0-91d1-c39fbece981a.png) | ![Screenshot_20221201-130606](https://user-images.githubusercontent.com/2602313/205139266-06a80edd-6bd4-492e-966a-366a8cedebbe.png) | ![Screenshot_20221201-122410](https://user-images.githubusercontent.com/2602313/205138836-1ced4ac2-3ce2-4935-85bc-23c289988d24.png) | ![Screenshot_20221201-122417](https://user-images.githubusercontent.com/2602313/205138845-f97f6951-77c4-4a53-ace4-39b142d35d0d.png) | ![Screenshot_20221201-122420](https://user-images.githubusercontent.com/2602313/205138853-94bde9d0-06fd-4e3c-b24f-a90321136d5a.png) | ![Screenshot_20221201-122425](https://user-images.githubusercontent.com/2602313/205138861-1ecfd9f9-d3c2-436e-b1db-e379ce5955ca.png)

**`Ensuring that the "Link" UI is removed once the subscription has expired`**

**`Example`** | **`Example`** | **`Example`** 
---------------|---------------|---------------
![Screenshot_20221201-130337](https://user-images.githubusercontent.com/2602313/205139873-44ee6306-7253-47b3-ad3b-ae4fbdd49ff8.png) | ![Screenshot_20221201-130357](https://user-images.githubusercontent.com/2602313/205139842-afacb21d-b6e7-4e86-87e9-af7230d72727.png) | ![Screenshot_20221201-134704](https://user-images.githubusercontent.com/2602313/205139865-e9d30784-61fd-4e78-9a79-2fd330348924.png)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung Galaxy S10+` running `Android 13` using the following build(s):

```
Brave | 1.46.133 Chromium: 108.0.5359.71 (Official Build) (32-bit)
--- | ---
Revision | 1e0e3868ee06e91ad636a874420e3ca3ae3756ac-refs/branch-heads/5359@{#1016}
OS | Android 13; Build/T1B3.221003.008
```

Using the instructions via https://github.com/brave/brave-core/pull/10408#issuecomment-939396800, launched Brave using the Griffin staging sever as per the following:

![image](https://user-images.githubusercontent.com/2602313/204950366-c2f28957-9deb-44a8-a80f-2eb90d26ca96.png)

Went through the following STR/Cases:

* ensured that `BraveVPNLinkSubscriptionAndroidUIStudy:Enabled` via `brave://version` after restarting the browser
* ensured that `Link purchase to your Brave account` isn't visible when there's no active subscription after enabling VPN
* ensured that `Link purchase to your Brave account` appears/is visible once a subscription is active (used monthly test card)
* ensured that `Link purchase to your Brave account` is removed once the subscription expires after ~35mins
  * note: as per @deeppandya, there needs to be an interaction with VPN before the `Link` UI is removed
* ensured that `Link purchase to your Brave account` is removed once the subscription has been manually cancelled
  * note: as per @deeppandya, there needs to be an interaction with VPN before the `Link` UI is removed
* ensured that the `Link purchase to your Brave account` was removed once a subscription expired and the following was done:
  * attempted to restore a expired subscription, attempted to switch regions when subscription expired
* ensured that tapping on the `Link purchase to your Brave account` UI opens `account.brave.com`

**`Launching Brave without a subscription and then subscribing and ensuring "Link" UI appears`**

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|---------------|---------------|---------------|---------------|---------------
![Screenshot_20221201_135610_Brave](https://user-images.githubusercontent.com/2602313/205146482-63cef073-4f7d-470d-8534-9cb31f59ab2a.jpg) | ![Screenshot_20221201_135624_Google Play Store](https://user-images.githubusercontent.com/2602313/205146503-78281ca4-76b5-4ca6-b247-a7edaccf6042.jpg) | ![Screenshot_20221201_135635_Brave](https://user-images.githubusercontent.com/2602313/205146514-b57f9611-562f-4f40-ab2a-10493162f129.jpg) | ![Screenshot_20221201_135654_Brave](https://user-images.githubusercontent.com/2602313/205146525-0d8b4f3f-f6c9-451a-a8c1-b5612f1f0994.jpg) | ![Screenshot_20221201_143744_Google Play Store](https://user-images.githubusercontent.com/2602313/205146541-769b47b2-17e4-47ff-bda2-c9ba0d88f2b7.jpg) | ![Screenshot_20221201_135659_Brave](https://user-images.githubusercontent.com/2602313/205146533-e562527f-bf80-4e3e-8b7f-6fd490ccd1e2.jpg)

**`Ensuring that the "Link" UI is removed once the subscription has expired`**

**`Example`** | **`Example`** | **`Example`** |  **`Example`** | **`Example`** 
---------------|---------------|---------------|---------------|---------------
![Screenshot_20221201_143552_Gmail](https://user-images.githubusercontent.com/2602313/205146777-6462d86a-c929-4f25-9635-dc9db355874d.jpg) | ![Screenshot_20221201_143624_Brave](https://user-images.githubusercontent.com/2602313/205146783-6ae885f1-496f-4a3a-b639-9ee752c891b8.jpg) | ![Screenshot_20221201_151328_Brave](https://user-images.githubusercontent.com/2602313/205151398-73214573-dafa-4186-a3a4-0f23b40c0254.jpg) | ![Screenshot_20221201_151343_Brave](https://user-images.githubusercontent.com/2602313/205151506-53fd437c-c296-4b96-8db9-9826b3b96f68.jpg) | ![Screenshot_20221201_151308_Google Play Store](https://user-images.githubusercontent.com/2602313/205151513-16dc7376-5906-4918-8b18-47b094a3e3a3.jpg)
