### ISSUE TITLE
Nightly version does not update to the latest version.

### ISSUE THREAD

**Issue by duytrung** [brave/brave-browser#26981]
## Description 

Always update to the latest nightly version

## Steps to Reproduce

   1. Installed the latest nightly version from github release page
   2. Use the browser as usual
   3. Update the browser, either automatically or via manually

## Actual result:

Not update to the latest version.
Screenshots as shown below. I have manually have the browser updated itself but still the latest "stable" version according to the Brave github releases page.
## Expected result:

Browser will update itself to the latest github version.

![image](https://user-images.githubusercontent.com/2046672/203907147-c153f6f0-e3bf-43ff-9fbd-5f730d63be03.png)

## Brave version (brave://version info)

![image](https://user-images.githubusercontent.com/2046672/203906858-c745a456-c622-4838-9ebe-1433b5216a67.png)
## Version/Channel Information:

- Can you reproduce this issue with the nightly channel? 
It's a nightly version, as the icon of the browser saying "nightly".
## Other Additional Information:

Windows 11.

## Miscellaneous Information:

None known.

**Comment by rebron** [comment]
@duytrung Can you try now?

**Comment by duytrung** [comment]
Yes, I think it works now
