### ISSUE TITLE
Blank screens on https://www.realestate.com.au/ & https://www.hyatt.com/

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#26993]
## Description 
Blank screens on https://www.realestate.com.au/ & https://www.hyatt.com/

## Steps to Reproduce

   1.  Open `https://www.realestate.com.au/buy/in-melbourne,+vic+3000/list-1`  see blank screen
   2.  Open `https://www.hyatt.com/` also see blank screen
   3.  note, (realestate.com.au will open fine, searching on it fails)

## Actual result:

![blankscreens](https://user-images.githubusercontent.com/1659004/204110104-86b3ea02-8217-4dc9-8d40-bb97105863c6.png)

## Expected result: Show website. (Nightly v1.45.53 ) 

- **https://www.realestate.com.au/buy/in-melbourne,+vic+3000/list-1**

![realestate](https://user-images.githubusercontent.com/1659004/204110886-a60da1b2-fbc5-4dab-8dfd-08a0a0fa97a8.png)

- **https://www.hyatt.com/**

![hyatt](https://user-images.githubusercontent.com/1659004/204110881-dfc35d1f-3c94-42cf-b121-62cf72533dbe.png)

## Reproduces how often: 
Easily.

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  No
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:
Regression range:

```
Nightly v1.45.62 (Chromium 106.0.5249.40)  BAD
Nightly v1.45.58 (Chromium 106.0.5249.40)  BAD
Nightly v1.45.54 (Chromium 106.0.5249.40)  BAD
Nightly v1.45.53 (Chromium 105.0.5195.136) GOOD
Nightly v1.45.52 (Chromium 105.0.5195.127)  GOOD
```

Both sites are using similar anti-bot/anti-fraud scripts:  possibly the cause of the issue. 

`https://www.realestate.com.au/149e9513-01fa-4fb0-aad4-566afd725d1b/2d206a39-8ed7-437e-a3be-862e0f06eea3/ips.js?KP2_UIDz=0bYrT138QEB61jgp6I7CSE7raxvHe2LNtEwngyXrkXfzgkHUzLQKb49zA8Gp3Dh1ZjX2cw1pubyGVkQszTwhXEMcM7Y7m9r6elILENrqGJbJovBM042qUfpWFIJcHChXLhY2Or65x9Ba1YdehIvVxzyiFPmi`

`https://www.hyatt.com/149e9513-01fa-4fb0-aad4-566afd725d1b/2d206a39-8ed7-437e-a3be-862e0f06eea3/ips.js?tkrm_alpekz_s1.3=09cQUa8g1VKM6TLai7DnSXuqvdRPZcSc9JJlp6pb5QSvbyXZot7oIKyYAHioUB9lhOmcLTot86SGvzRBzu1phKL2GLayOdmH28XO1ubOmvp2A0uzjiiOd87w9gVKBqNe9fyApm3J1Up7RulM7Xp4Br66iJET`

User reports:
https://community.brave.com/t/unable-to-search-property-on-realestate-com-au/448265
https://community.brave.com/t/website-not-loading/448792
https://community.brave.com/t/realestate-com-au-wont-load-in-brave/448808

**Comment by Condobloke** [comment]
I am experiencing the same problem.....and have been for the past few months

**  **https://www.realestate.com.au/buy/in-rockhamptom/list-1**   **

All shields down
Using: [Version 1.45.133 Chromium: 107.0.5304.141 (Official Build) (64-bit)](https://brave.com/latest/)

All other real estate sites load instantly without drama

I note that **www.hyatt.com**   ...also will not load.

Tried "open guest window".....with no success.

**Comment by ryanbr** [comment]
Supercedded by https://github.com/brave/brave-browser/issues/27021
