### ISSUE TITLE
Typo in startup tutorial

### ISSUE THREAD

**Issue by kirkins** [brave/brave-browser#2699]
## Description 

Images that show on first use have accompanying text with a typo.

![](https://i.imgur.com/k3GpVu5.jpg)

## Steps to Reproduce

   1. Start a new instance of brave
   2. Read text

## Actual result:

Single letter smelling mistake

## Expected result:
No mistake.

## Reproduces how often: 

Always

## Brave version (brave://version info)

Version 0.60.3 Chromium: 71.0.3578.98 (Official Build) dev (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 
No

### Additional Information

https://github.com/brave/brave-core/pull/1181

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.59.14 Chromium: 72.0.3626.28 (Official Build) beta (64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Windows
