### ISSUE TITLE
Add keyboard Shortcut for muting a tab

### ISSUE THREAD

**Issue by GregJArnold** [brave/brave-browser#26994]
## Description 
Firefox allows you to mute a tab with CTRL+M.  This is a nice feature, because, as far as I can tell, the only way to do so in Brave is to click the speaker icon in a tab.

## Brave version
1.45.127 Chromium: 107.0.5304.110 (Official Build) (64-bit)

**Comment by simonhong** [comment]
Nice request! @rebron I would happily take this issue if want :)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.48.118 Chromium: 109.0.5414.80 (Official Build) beta (64-bit)
-- | --
Revision | 0f69b168d36a06cace4365e9f029fa987afa5633-refs/branch-heads/5414@{#1178}
OS | Windows 11 Version 21H2 (Build 22000.1335)
```

Confirmed: Able to toggle active tab audio with keyboard shortcut CTRL+M 


https://user-images.githubusercontent.com/98358127/211431875-82aa49b1-0dfc-4dcc-87f4-bfc86f100cd9.mp4

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using 

Brave | 1.48.129 Chromium: 109.0.5414.87 (Official Build) beta (x86_64)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | macOS Version 11.7.2 (Build 20G1020)

### Steps:
1. installed `1.48.129`
2. launched Brave
3. loaded `https://www.youtube.com/watch?v=3VZFpwlXKpg`
4. clicked the `Play` button on the video
5. noted sound
6. pressed `control` + `m`
7. confirmed the tab muted
8. pressed `control` + `m` once more
9. confirmed the tab unmuted

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.48.137 Chromium: 109.0.5414.87 (Official Build) beta (64-bit)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | Linux
```
Install 1.48.137
launch Brave
open a new-tab
visit a site https://www.youtube.com/watch?v=DXZer9k27C8
