### ISSUE TITLE
grant.rewards.brave.com refused to connect on linux 

### ISSUE THREAD

**Issue by fugohan** [brave/brave-browser#26995]
## Description 
 ![](https://preview.redd.it/3plp44gg9q1a1.png?width=443&format=png&auto=webp&s=5a0afef00dcb94a01e2f8a2df92156a490613659)
I got this pop up and then i tried to solve a captcha but got this error msg in Brave Rewards. 
grant.rewards.brave.com refused to connect

![image](https://user-images.githubusercontent.com/46691165/204136257-56239065-370b-4537-acd9-360d4866a6f5.png)

## Brave version (brave://version info)
1.45.118 Chromium: 107.0.5304.91 (Official Build) unknown (64-bit)

**Comment by designoneweb** [comment]
Same problem.

System info:

Operating System: KDE neon 5.26
KDE Plasma Version: 5.26.3
KDE Frameworks Version: 5.100.0
Qt Version: 5.15.7
Kernel Version: 5.15.0-53-generic (64-bit)

Brave info:

[Version 1.45.133 Chromium: 107.0.5304.141 (Official Build) unknown (64-bit)](https://brave.com/latest/)

**Comment by jeroenev** [comment]
same here

**Comment by tauroamp** [comment]
Same error! :(

**Comment by SscoootzZ** [comment]
Word...put me down for the same error. If there is useful sysinfo to post please just lmk. Thumbnail: Pop!_OS 22.04, 64-bit.

**Comment by Miyayes** [comment]
@SscoootzZ Do you still see this CAPTCHA and if you try again, are you still getting this error?

Would you be able to try and clear your cache completely and see if that helps? Wondering if this is a caching issue or so...

If you're still facing this problem, we can schedule a quick 1:1 call with one of our engineers (@emerick)

**Comment by fugohan** [comment]
@Miyayes After clearing my cache I still get this error. 
![image](https://user-images.githubusercontent.com/46691165/205726098-f002bb79-50f2-4fac-9a4e-35f9a791a841.png)

I also updated my Brave Browser to [Version 1.46.134 Chromium: 108.0.5359.94 (Official Build) unknown (64-bit)](https://brave.com/latest/) (Flatpak)

**Comment by jeroenev** [comment]
I'm also on the flatpak version, maybe it's only on flatpak?

**Comment by Miyayes** [comment]
According to @fmarier, "Flatpaks and Snaps have extra sandboxing that sometimes breaks features", which would make sense. This extra sandboxing seems to corresponding with the kind of error message you're seeing.

**Comment by jeroenev** [comment]
@tauroamp @SscoootzZ @designoneweb Are you also using the flatpak version?

**Comment by designoneweb** [comment]
@tauroamp I'm using the flatpak version. As of this past weekend, Rewards are working properly. No Brave update but have updated Neon to the most recent build.

**Comment by jeroenev** [comment]
Found a hacky workaround:
1. open panel
2. right click -> inspect
3. go to network tab
4. refresh page
5. check the line that says (blocked:other)
6. double-click on that line in the name column
7. a new tab should open with the captcha
8. do the captcha in the new tab
9. restart brave browser

**Comment by Djenchik** [comment]
> Found a hacky workaround:
> 
> 1. open panel
> 2. right click -> inspect
> 3. go to network tab
> 4. refresh page with control-R,
> 5. make sure the developer tools are highlighted when pressing ctrl-R, otherwise the page might be reloaded instead of the panel
> 6. check the line that says (blocked:other)
> 7. double-click on that line in the name column
> 8. a new tab should open with the captcha
> 9. do the captcha in the new tab
> 10. restart brave browser

worked perfectly, kudos

**Comment by emerick** [comment]
If you visit brave://flags/#brave-rewards-webui-panel and set `Use WebUI Rewards Panel` to enabled and restart, does it help?

**Comment by dzmien** [comment]
If anyone is having trouble still, I enabled the `Use WebUI Rewards Panel` option in brave://flags per @emerick 's advice, and that solved the problem. Thanks, @emerick !

**Comment by Miyayes** [comment]
This should now be resolved. Main workaround is to enable WebUI Rewards Panel in the brave://flags. This will also be fixed for sure in 1.47.x since it only uses WebUI Rewards Panel. And, we've also made a fix on the server side.
