### ISSUE TITLE
[Brave News]: Update Subscribe Button Icon

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#26997]
We have a new subscribe button icon we should use thanks to @martin-c0des.

![image](https://user-images.githubusercontent.com/7678024/204156285-9a9b711a-2d2e-4d65-96a3-0a8b16bfa2d5.png)
https://www.figma.com/file/w13WS9lovJubjbSjtK1fVo/Brave-Desktop---Add-to-Brave-News?node-id=129%3A13678&t=R4BQ7wBZ9LhXjZnj-0#313822908

**Comment by fallaciousreasoning** [comment]
Hey @martin-c0des, I've just been updating the icon and there isn't heaps to distinguish between the subscribed & unsubscribed states:

Unsubscribed
![image](https://user-images.githubusercontent.com/7678024/204158363-124f0404-ee36-450f-bd70-bcd90378bc0d.png)


Subscribed
![image](https://user-images.githubusercontent.com/7678024/204158341-7ad37e81-5667-4280-9950-13047c4785a7.png)

**Comment by fallaciousreasoning** [comment]
I had a dig into the code, and it looks like we were doing something to reduce the contrast, to make the colors the same as the other icons. Even with that disabled it's kinda hard to tell the icon has changed:

No contrast reduction:
![image](https://user-images.githubusercontent.com/7678024/204158547-a2d06914-1e6d-43eb-b9b4-fe9faf9fc19f.png)

**Comment by kjozwiak** [comment]
We'll be uplifted the above into the `1.46.x` maintenance release via https://github.com/brave/brave-core/pull/16143 once the initial `1.46.x` build goes out. Verification will be completed on `1.46.x`.

**Comment by kjozwiak** [comment]
The above requires `1.46.139` or higher for `1.46.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.46.141 Chromium: 108.0.5359.99 (Official Build) (64-bit)
-- | --
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | Windows 10 Version 21H2 (Build 19044.2251)

```
### Steps:
1. installed `1.48.13`
2. launched Brave
3. set `brave://flags/#brave-news-subscribe-button` to `Enabled`
4. clicked `Relaunch`
5. loaded `planet.mozilla.org`
6. changed modes and theme
7. hovered over the buttons

#### Confirmed new `RSS` icon across the following:

`Dark` mode | `Dark` mode, hover | `Light` mode | `Light` mode, hover | `purple theme` | `purple theme`, hover
--------------|---------------------|--------------|----------------------|----------------|----------------
![image](https://user-images.githubusercontent.com/38657976/206730821-d0f219d4-1124-49d7-a96f-c8c91c34e9ec.png) | ![image](https://user-images.githubusercontent.com/38657976/206730927-e3519dde-9d1b-42fb-af58-a80d3eaed18e.png) | ![image](https://user-images.githubusercontent.com/38657976/206731074-29a9ecc9-eb8f-4d3a-8732-ecf4530f724d.png) | ![image](https://user-images.githubusercontent.com/38657976/206731158-1dc28a6c-df7b-4d8a-9edc-edbe9f6eec9d.png) | ![image](https://user-images.githubusercontent.com/38657976/206731684-7204c823-ea37-4b99-8cad-0b613b5553ac.png) | ![image](https://user-images.githubusercontent.com/38657976/206731764-7246d7bd-3f4d-4322-91d9-ba78aee3f8fd.png)

**Comment by btlechowski** [comment]
Verification **PASSED** on

```
Brave | 1.46.141 Chromium: 108.0.5359.99 (Official Build) (64-bit)
-- | --
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | Ubuntu 18.04 LTS

```
### Steps:
1. installed `1.46.x`
2. launched Brave
3. set `brave://flags/#brave-news-subscribe-button` to `Enabled`
4. clicked `Relaunch`
5. loaded `planet.mozilla.org`
6. changed modes and theme
7. verified subscribed/unsubscribed/hover states


#### Dark mode

<details>

unsubscribed
![image](https://user-images.githubusercontent.com/34715963/206738703-81b6d8a1-b582-4912-9876-a55973f13395.png)


unsubscribed - hover 
![image](https://user-images.githubusercontent.com/34715963/206738799-5fecf246-3b8a-4cb2-9b78-adfe95e98035.png)


subscribed
![image](https://user-images.githubusercontent.com/34715963/206739143-0985027f-02c5-43d0-968b-38ebd5c5853a.png)


subscribed - hover
![image](https://user-images.githubusercontent.com/34715963/206739172-4e9e951c-38ab-4076-a8d5-dc4ed70d28f8.png)


</details>

#### Light mode

<details>

unsubscribed
![image](https://user-images.githubusercontent.com/34715963/206739635-5877424f-48de-48e0-a0ec-ee3790b929ec.png)


unsubscribed - hover 
![image](https://user-images.githubusercontent.com/34715963/206739684-14962c53-80c4-48de-8a15-790c6ed07512.png)


subscribed
![image](https://user-images.githubusercontent.com/34715963/206739922-39ee9d87-48c3-405c-8c3b-742fe6b0ddef.png)


subscribed - hover
![image](https://user-images.githubusercontent.com/34715963/206739954-d2965d58-d95b-445c-b1bb-b56948fb13db.png)


</details>

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.46.141 Chromium: 108.0.5359.99 (Official Build) (x86_64)
-- | --
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | macOS Version 13.1 (Build 22C65)

### Steps:
1. installed `1.46.141`
2. launched Brave
3. opened `brave://flags`
4. set `brave://flags/#brave-news-subscribe-button` to `Enabled`
5. clicked `Relaunch`
6. loaded `planet.mozilla.org`
7. verified subscribed/unsubscribed/hover states

`Light` mode

unsubscribed | unsubscribed, hover | subscribed | subscribed, hover
--------------|----------------------|------------|-------------------
<img width="1186" alt="Screenshot 2022-12-09 at 10 34 02 AM" src="https://user-images.githubusercontent.com/387249/206770986-a82ab26d-559d-4302-8428-1c56d0754cc9.png"> | <img width="1186" alt="Screenshot 2022-12-09 at 10 34 07 AM" src="https://user-images.githubusercontent.com/387249/206770998-17665ad2-6ae0-4162-8d35-488d2e06b937.png"> | <img width="1312" alt="Screenshot 2022-12-09 at 10 48 24 AM" src="https://user-images.githubusercontent.com/387249/206772313-fee6be47-8f4d-41ce-af2e-d1fc28dc817c.png"> | <img width="1312" alt="Screenshot 2022-12-09 at 10 55 35 AM" src="https://user-images.githubusercontent.com/387249/206774766-a700213b-4b94-48fd-8e31-04fc0b7b1967.png">


 `Dark` mode

unsubscribed | unsubscribed, hover | subscribed | subscribed, hover
--------------|----------------------|------------|-------------------
<img width="1186" alt="Screenshot 2022-12-09 at 10 34 32 AM" src="https://user-images.githubusercontent.com/387249/206773921-925a9185-ee14-419b-8f7f-721458c2f3d5.png"> | <img width="1186" alt="Screenshot 2022-12-09 at 10 34 36 AM" src="https://user-images.githubusercontent.com/387249/206773933-1c5c76bb-e4de-45bb-8c38-d713791a776d.png"> | <img width="1312" alt="Screenshot 2022-12-09 at 10 56 57 AM" src="https://user-images.githubusercontent.com/387249/206775237-552d3e08-a57c-4a0b-994f-d581ba956b6f.png"> | <img width="1312" alt="Screenshot 2022-12-09 at 10 56 51 AM" src="https://user-images.githubusercontent.com/387249/206775330-8cce1296-8f00-43f5-bfb9-e4f31924937f.png">
