### ISSUE TITLE
only ever displaying OS notifications warnings once in total rather than one per warning/feature

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#27002]
## Description 

Once https://github.com/brave/brave-core/pull/16079 was implemented, we're only ever displaying one warning modal. So for example, if a user sees a warning modal regarding the `privacy report`, they won't see a warning modal about not being rewarded due to not receiving ad notifications once the OS notifications have been disabled. 

## Steps to reproduce 

   1. download/install brave (`1.48.9 Chromium: 108.0.5359.48` used in this case)
   2. run through the onboarding and enable OS notifications via the `Android 13` onboarding
   3. enable the `Privacy Report`
   4. disable notifications for `Brave` via `Settings` -> `Notifications`
   5. you'll receive a warning modal that was implemented via https://github.com/brave/brave-core/pull/15407
   6. enable OS notifications via `Settings` -> `Notifications`
   7. enable rewards via the rewards panel and enable `Show Ads when Brave is not in use`
   8. disable the OS notifications via `Settings` -> `Notifications`

## Actual result 

You'll notice you won't receive a warning about not being rewards as you've already received a warning modal re: the `privacy report`.

## Expected result

I'm not 100% sure what the expected behaviour should be but I think we should at least show each warning once.

## Issue reproduces how often 

100% reproducible when running through the STR/Cases outlined above.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `No` (will be once `1.46.x` gets pushed to `production`)
- Can you reproduce this issue with the current Play Store Beta version? `Yes`
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Samsung Galaxy S10+`
   - Android version: `Android 13`
   
## Brave version

```
1.48.9 Chromium: 108.0.5359.48
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by sujitacharya2005** [comment]
@kjozwiak 
Updated this condition as per this
- For 3rd launch case just re-check the conditions and show the proper dialog.
- From Brave Setting case once click on notification and come back show the corresponding dialog.
 
PR : https://github.com/brave/brave-core/pull/16128

1. Application re-launch 3rd time
2. From Brave setting -> notification click each time

If main notification is off, Rewards feature is off, privacy feature is off -> Show Generic Dialog
if main notification is off, Rewards feature is on, privacy feature is off -> Show rewards message dialog
if main notification if off, Rewards feature is off, privacy feature is on -> show Privacy message dialog
if main notification is off, Rewards feature is on, Privacy feature is on -> Show both rewards & privacy message dialog

**Comment by deeppandya** [comment]
CC @kjozwiak

**Comment by deeppandya** [comment]
This issue is irrelevant once we have feature related banners for notifications
