### ISSUE TITLE
Fix brave notification description and textual button color in dark mode

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#27004]
## Description 
Notification dialog description color is hard to read in dark mode.
- For description in dark mode: can use `#84889C` [color like wallet](https://github.com/brave/brave-core/pull/15118/files#diff-ef5c630efd1e9fe243b8e265410a08c4a7b420469e92ee07a86c1dbac113d68d)
- For textual button, can use `#A0A5EB` for dark and `#4C54D2` for light like [wallet](https://github.com/brave/brave-browser/issues/25771)

Note: Make sure to confirm the exact colors with figma if specs are available for dark mode/feature.

## Actual result 
![Screenshot from 2022-11-28 15-08-35](https://user-images.githubusercontent.com/11755381/204255846-f558bd84-5359-4189-a6d4-d79346876069.png)

## Expected result
Update colors as per theme/figma.

cc: @sujitacharya2005 @deeppandya

**Comment by deeppandya** [comment]
Thank you @Pavneet-Sing. it seems we are missing dark mode spec here : https://www.figma.com/file/sdVBBufbl2A11hAgPNfyqG/Android-13-Notifications?node-id=366%3A30681&t=kj66ZSk8TrqEpCmt-0
@sujitacharya2005 can you update the issue based on the suggestions ?

**Comment by anatolydsgn** [comment]
@deeppandya @timchilds  I've just updated the design for this notification screen.

https://www.figma.com/file/sdVBBufbl2A11hAgPNfyqG/Android-13-Notifications?node-id=1243%3A31639&t=7Pd5NQyY0I0HjTn0-1

**Comment by deeppandya** [comment]
we will be updating night mode colors for this issue.

**Comment by anatolydsgn** [comment]
@deeppandya just in case, here's a quick fix without changing the layout. you could just use updated colors and illustration. https://www.figma.com/file/sdVBBufbl2A11hAgPNfyqG/Android-13-Notifications?node-id=363%3A30672&t=JBalKKlQzJNGa6zV-1

**Comment by kjozwiak** [comment]
The above requires `1.47.168` or higher for `1.47.x` verification. @Uni-verse leave this one for me 👍 I think we'll need a follow up as it still looks like it's not using the correct colours. Looks the same as before. I wouldn't consider this a blocker but we'll need a follow up which I'll create tomorrow AM. Example:

![Screenshot_20230111-031302](https://user-images.githubusercontent.com/2602313/211753327-8ff8385a-70a3-47e5-bd95-a6124362d8ef.png)

CCing @deeppandya @sujitacharya2005 @timchilds

**Comment by kjozwiak** [comment]
Labelling this as `QA/No` and `release-notes/exclude` as this actually never made it into `1.47.x` or Brave in general. Looks like the fix was never merged as per https://github.com/brave/brave-core/pull/16128/files (don't see any colour/theme fixes). Created https://github.com/brave/brave-browser/issues/27767 as a follow up.
