### ISSUE TITLE
Switch over to Updated Nav

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#27008]
## Description 

Once `Swap V2` is merged, we need to switch over to the new `Buy/Send/Swap/Deposit` nav.

![Screen Shot 2022-11-28 at 10 04 00 AM](https://user-images.githubusercontent.com/40611140/204324865-048cbbd2-d8b3-4a3d-a515-dc76d278ae76.png)

![Screen Shot 2022-11-28 at 10 03 49 AM](https://user-images.githubusercontent.com/40611140/204324868-13fcca91-e6d4-4176-b22d-40f9f2b37bc3.png)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.48.139 Chromium: 109.0.5414.87 (Official Build) beta (64-bit) 
-- | --
Revision | `2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}`
OS | Linux

- Verified steps from [brave/brave-core#16104](https://github.com/brave/brave-core/pull/16104)
- Verified clicking on `Send` on portfolio page loads `brave://wallet/send`
- Verified clicking on `Swap` on portfolio page loads `brave://wallet/swap`
- Verified on `brave://wallet/send` page, clicking on `Swap` on the left navigation loads `brave://wallet/swap`
- Verified other navigation buttons on the left work as expected
- Verified new layout on panel is shown
- Verified `Buy` button on panel loads `brave://wallet/crypto/fund-wallet` in a new tab
- Verified `Send` button on panel loads `brave://wallet/send` in a new tab
- Verified `Swap` button on panel loads `brave://wallet/swap` in a new tab
- Verified `Deposit` button on panel loads `brave://wallet/crypto/deposit-funds` in a new tab

https://user-images.githubusercontent.com/17010094/214574714-d7425e38-54a6-49ee-8227-ae8079dfe112.mp4

---------------------

Verification passed on 

Brave | 1.48.139 Chromium: 109.0.5414.87 (Official Build) beta (64-bit)
-- | --
Revision | `2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#16104](https://github.com/brave/brave-core/pull/16104)
- Verified clicking on `Send` on portfolio page loads `brave://wallet/send`
- Verified clicking on `Swap` on portfolio page loads `brave://wallet/swap`
- Verified on `brave://wallet/send` page, clicking on `Swap` on the left navigation loads `brave://wallet/swap`
- Verified other navigation buttons on the left work as expected
- Verified new layout on panel is shown
- Verified `Buy` button on panel loads `brave://wallet/crypto/fund-wallet` in a new tab
- Verified `Send` button on panel loads `brave://wallet/send` in a new tab
- Verified `Swap` button on panel loads `brave://wallet/swap` in a new tab
- Verified `Deposit` button on panel loads `brave://wallet/crypto/deposit-funds` in a new tab

https://user-images.githubusercontent.com/17010094/214574969-1fc99a51-8252-41c7-942f-34b0a7fe90ef.mp4

---------------------

Verification passed on 

Brave | 1.48.139 Chromium: 109.0.5414.87 (Official Build) beta (arm64)
-- | --
Revision | `2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#16104](https://github.com/brave/brave-core/pull/16104)
- Verified clicking on `Send` on portfolio page loads `brave://wallet/send`
- Verified clicking on `Swap` on portfolio page loads `brave://wallet/swap`
- Verified on `brave://wallet/send` page, clicking on `Swap` on the left navigation loads `brave://wallet/swap`
- Verified other navigation buttons on the left work as expected
- Verified new layout on panel is shown
- Verified `Buy` button on panel loads `brave://wallet/crypto/fund-wallet` in a new tab
- Verified `Send` button on panel loads `brave://wallet/send` in a new tab
- Verified `Swap` button on panel loads `brave://wallet/swap` in a new tab
- Verified `Deposit` button on panel loads `brave://wallet/crypto/deposit-funds` in a new tab

https://user-images.githubusercontent.com/17010094/214569642-8783a2dc-c930-4f13-ad9f-ac855a0a3809.mov
