### ISSUE TITLE
Improve VPN set-up to make it easier for users to select a country

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#27014]
## Description Related to: https://github.com/brave/brave-ios/issues/6499

Having the ability to select an exit point in a different country is a real plus for a VPN. Given some recent feedback (see Slack thread) we should rethink how we make this feature more easy to find.

**Existing Country Selection Setting UI**
![Screenshot_20221128-100125](https://user-images.githubusercontent.com/7606853/204348567-e72f5c9c-be99-4f50-8946-4ebf2a70794a.jpg)

**Comment by hffvld** [comment]
### IN PROGRESS...

Verified on `Pixel 2 XL`, `Galaxy Tab S8` and `Pixel 7` using version(s):
```
Device/OS: 
- Pixel 2 XL / taimen-user  8.1.0 OPM2.171026.006.H1 release-keys
- Galaxy Tab S8 / gts8wifixx-user 13 TP1A.220624.014 release-keys
- Pixel 7 / panther_beta-user 14 AP21.240119.009 release-keys
Brave build: 1.63.149
Chromium: 121.0.6167.164 (Official Build) beta (64-bit) 
```
Filed follow-up issue #35939
---------------------------

**STEPS:**
   1. Launch Brave
   2. Purchase a VPN subscription
   3. Enable VPN
   4. Tree-dot menu > Country flag icon
   5. Change to any other country > *Verify*

**ACTUAL RESULTS:**
- Verified 
- Verified 

---------------------------

<details>
<summary> Pixel 2 XL </summary>

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/52883115-39f4-46a3-b370-b35759b4b772) | ![2](https://github.com/brave/brave-browser/assets/128532965/0ce29312-a501-47ed-9892-aef74139174c) | ![3](https://github.com/brave/brave-browser/assets/128532965/f3a7d2c0-e7e2-46ea-9e80-cadf75a92986) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/80bad39a-3ef6-4fe9-9083-69984920e33d) | ![2](https://github.com/brave/brave-browser/assets/128532965/89a2f702-9887-406b-9b92-d63691d6a6b2) | ![3](https://github.com/brave/brave-browser/assets/128532965/c860f11a-34ca-4c5d-b89e-450ce6369dcd) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/7d402ff3-675c-4a74-bfd9-1b1bfc7902b2) | ![2](https://github.com/brave/brave-browser/assets/128532965/ea913c35-2d08-40fb-90bc-82bd8e5df1cb) | ![3](https://github.com/brave/brave-browser/assets/128532965/142cabb5-4b87-4dbb-8bcd-5aea9301ddbf) |
</details>

<details>
<summary> Galaxy Tab S8 </summary>

</details>

<details>
<summary> Pixel 7 </summary>

</details>
