### ISSUE TITLE
Visual QA bugs for Speedreader V2 icon and panel

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#27013]
## Version 
Based on Nightly 
Version 1.48.5 

## URL bar
<img width="49" alt="image" src="https://user-images.githubusercontent.com/15734630/204337022-143b35a1-268b-4344-9b61-23331272ebc3.png">
The icon is old. The new one is here in Figma https://www.figma.com/file/YHMNRL2XpZDOUe6n1Dw6K1/Desktop-Speedreader?node-id=1277%3A36115&t=zHjd1d67ZK9Hx01K-1
<img width="816" alt="image" src="https://user-images.githubusercontent.com/15734630/204338029-67cd6362-ab27-4159-84b6-7881303223f2.png">

----------------------
## Panel
**Design vs. implementation**
![image](https://user-images.githubusercontent.com/15734630/205991565-8b4b2eec-9adc-4a2f-9af0-272f2394e5cc.png)

- Divider line shouldn't be there (use background color to divide blocks)
- Header is missing background color
- Toggle style is old and doesn't align to design
- "Always load Speedreader mode for url.comr" is missing the checkbox.
- Also in that text, the url should be semibold
- Theme previews should have an outline.
- Themes are missing the "System" theme.
- Font styles: The style name should always use Poppins (sans / serif / etc.) The Aa preview is correct previewing the font.
- Font size stepper is missing the icon. Also the font size and style doesn't match the design.
- Missing reading mode and Advanced settings, guessing it's being worked on.
- Missing hover states for buttons on the panel.
- Button group items should have a bit more padding, check the Figma spec to see correct heights and paddings

**Comment by rebron** [comment]
@aguscruiz When you get a chance can you add the off version for this panel.

**Comment by aguscruiz** [comment]
Added

**Comment by rebron** [comment]
Closing as stale
