### ISSUE TITLE
Remove Chromium's "acceptable ads" content setting

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#27010]
## Description 
Remove the Chromium `Ads` content setting as it's confusing; it could easily be mistaken for Brave shields Adblocking. Per @pes10k:
> This setting controls Chromium’s built in “acceptable ads” policy; we block all that stuff so its 99% of the time a NOOP for us.  Disabling the preference would probably make things less confusing to Brave users.

## Steps to Reproduce
   1. Visit slack.com and browse a bit
   2. Open brave://settings/content/siteDetails?site=https%3A%2F%2Fslack.com
   3. Scroll down until you see `Ads` and `Block if site shows intrusive or misleading ads`

## Actual result:
![image](https://user-images.githubusercontent.com/4733304/204330582-cba4aa11-edeb-4533-971c-3050bbc0cece.png)

## Expected result:
There should not be a setting called `Ads`

**Comment by rebron** [comment]
Let's keep this in 1.47.x

**Comment by kjozwiak** [comment]
The above requires `1.47.121` or higher for `1.47.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.47.126 Chromium: 108.0.5359.99 (Official Build) beta (64-bit)
-- | --
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | Windows 11 Version 21H2 (Build 22000.1219)
```

Case 1: New install/new profile
<details>

1. Install 1.47.126
2. launch Brave
3. visit slack.com and browse a bit
4. open `brave://settings/content/siteDetails?site=https%3A%2F%2Fslack.com`
5. scroll down the page

#### Confirmed the `Ads and Block if site shows intrusive or misleading ads` setting is no longer available

Ex1|Ex2
---|----
<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/207443247-d48ba633-a528-4b88-b860-f376e49cf9c6.png">|<img width="460" alt="image" src="https://user-images.githubusercontent.com/98358127/207443304-945aa372-4f67-4ab2-9efe-00be02982fa9.png">
</details>

Case 2: Upgrade
<details>

1. install 1.46.140
2. launch Brave
3. visit slack.com and browse a bit
4. visit `brave://settings/content/siteDetails?site=https%3A%2F%2Fslack.com`
5. scroll down the page
6. confirmed `Ads and Block if site shows intrusive or misleading ads` settings is available 
7. close the browser
8. rename the profile Brave Browser Beta
9. launch Brave 
10. visit `brave://settings/content/siteDetails?site=https%3A%2F%2Fslack.com`

#### Confirmed the `Ads and Block if site shows intrusive or misleading ads` setting is no longer available
step 1|step 6|results|results
-----|---------|-----|--------
<img width="458" alt="image" src="https://user-images.githubusercontent.com/98358127/207444666-5521e15b-21f9-43e9-a7b1-c330542647f5.png">|<img width="456" alt="image" src="https://user-images.githubusercontent.com/98358127/207444726-5034b4c7-aa6b-4496-becd-cce8c44dd15a.png">|<img width="454" alt="image" src="https://user-images.githubusercontent.com/98358127/207444990-988e7497-5060-478e-8160-c575a260c458.png">|<img width="455" alt="image" src="https://user-images.githubusercontent.com/98358127/207445043-ab513bba-0cf8-4aad-82c3-2c10b7aeaf4d.png">
</details>
