### ISSUE TITLE
Crash Report with tearing off tabs in vertical tabs mode

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#27028]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.48.5  Chromium: 108.0.5359.48
Operating System: Mac OS X 13.1.0

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1.
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/aa120700-1c77-3409-0000-000000000000

**Comment by rebron** [comment]
Reproduces in beta and nightly. 
1. Select a vertical tab.
2. Attempt to "tear off" tab or drag tab to create a new window or into an existing other window.
3. Notice crash.

**Comment by rebron** [comment]
cc: @sangwoo108

**Comment by stephendonner** [comment]
Pretty sure we can close this, @rebron - I'd have run into it, myself, while testing the feature 👍
