### ISSUE TITLE
[Brave News]: Add translations & icons for new Channels.

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#27024]
The Brave News backend has added some new channels (Music, Tech News, Tech Reviews & more). We should add translations for these new channels and also some new icons.

Thanks @aurangzaib048 for raising this!

@aguscruiz do you know if we have icons for these new channels?

**Comment by aguscruiz** [comment]
I added the new channel icons here: https://www.figma.com/file/SDcE22eeUsV2uc4dy3NwaC/Desktop-News---Onboarding?node-id=740%3A67478&t=vhDSgWnpqXnw0PbI-1 

Let me know if we're missing any

**Comment by fallaciousreasoning** [comment]
New channels as best I can tell are:
- Entertainment News
- Film and TV
- Music
- Regional News
- Tech News
- Tech Reviews
- US News

I think we missed Entertainment News, but I'm just going to reuse the entertainment icon.

**Comment by mattmcalister** [comment]
The complete list (at the moment):

- Brave
- Business
- Cars
- Crypto
- Culture
- Entertainment News
- Fashion
- Film and TV
- Food
- Fun
- Gaming
- Health
- Home
- Music
- Politics
- Science
- Sports
- Tech News
- Tech Reviews
- Travel
- US News
- Weather
- World News

**Comment by kjozwiak** [comment]
The above requires `1.47.120` or higher for `1.47.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.47.120 Chromium: 108.0.5359.99 (Official Build) dev (x86_64)
-- | --
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | macOS Version 13.1 (Build 22C65)

### Steps:
1. installed `1.47.120`
2. changed my OS language to [Spanish, Greek, German]
3. launched Brave
4. opened a new-tab page
5. scrolled down
6. clicked on `Show Brave News`
7. clicked `Customize`
8. scrolled down and examined the (translated) channel names and icons

#### Confirmed the beginnings of the newly translated strings were there, across Spanish, Greek, and German locales

Spanish | Greek | German
---------|---------|---------
<img width="1312" alt="Captura de pantalla 2022-12-08 a la(s) 8 06 32 p m" src="https://user-images.githubusercontent.com/387249/206626898-43550cfd-17f7-46a0-8208-a7a071c232d4.png"> | <img width="1522" alt="Στιγμιότυπο οθόνης 2022-12-08, 8 17 27 μμ" src="https://user-images.githubusercontent.com/387249/206626905-7280718a-c8d9-4de8-9178-6eb1935aa234.png"> | german
