### ISSUE TITLE
Consolidate tabs from all windows into one window

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#27022]
## Description 
Brave should offer a way to consolidate the tabs from ALL windows into ONE window
Maybe a right click on the tabs area and picking "Bring all tabs to this window" or similar (hamburger?)

See https://twitter.com/rohan10/status/1597252017876967430

cc: @rebron

**Comment by rebron** [comment]
cc: @aguscruiz

**Comment by aguscruiz** [comment]
Seems like a good option to have on right click on the tab area, like @bsclifton suggested.

**Comment by PedroHorace** [comment]
PLEASE ADD THIS

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.64.94 Chromium: 122.0.6261.94 (Official Build) beta (x86_64)
-- | --
Revision | 866e3a4bd76c9cc1762928df0cf9a53b8685ab71
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.64.94`
2. launched Brave
3. opened seven (7) windows, with various tabs
4. opened a main window
5. context-clicked on the main window
6. chose `Bring other tabs to main window`

### Confirmed all the tabs/windows were collected into a single, main window

![collect-windows](https://github.com/brave/brave-browser/assets/387249/630aa23d-e0f8-4d44-beca-ee4173ad9a67)

**Comment by PedroHorace** [comment]
How do I update to 1.64.94? I'm currently at 1.63.165 and the update
section isn't prompting for a new update. Do I just have to wait for it to
release?
_________________________________________
*  Peter Hollis*

**Comment by stephendonner** [comment]
> How do I update to 1.64.94? I'm currently at 1.63.165 and the update section isn't prompting for a new update. Do I just have to wait for it to release?

@PedroHorace you may grab Brave installers for `nightly`, `beta`, `release` at https://github.com/brave/brave-browser/releases.

**Comment by PedroHorace** [comment]
Ah got it thank you! When would you say that this feature will come out of
beta and onto the main brave versions?
_________________________________________
*  Peter Hollis* - La Salle '24

**Comment by stephendonner** [comment]
> Ah got it thank you! When would you say that this feature will come out of beta and onto the main brave versions?

Hi again; our release dates are always published on https://github.com/brave/brave-browser/wiki/Brave-Release-Schedule#release-channel-dates.

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using 

```
Brave | 1.64.98 Chromium: 122.0.6261.111 (Official Build) beta (64-bit)
-- | --
Revision | a262f3c44a8960fee49fbf0bd6f5740634f32be7
OS | Windows 10 Version 22H2 (Build 19045.4123)
```

## Default - horizontal tabs - `PASSED`

### Steps:
1. installed `1.64.98`
2. launched Brave
3. opened many tabs/new windows - most with content, some blank tabs and some blank windows
4. loaded `brave.com` in a single new window
5. context-clicked on the tab
6. chose `Bring all tabs to this window`

### Confirmed all tabs/windows were collected into a single window


https://github.com/brave/brave-browser/assets/387249/3e0666d2-ec9b-48a6-a8ab-8335474658f4

## Vertical tabs - `PASSED`

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave	1.64.104 Chromium: 123.0.6312.46 (Official Build) (64-bit) 
Revision	0ca3d372cf8aab96fafdd75f5c5c8d2012bc0cc6
OS	Linux
```
