### ISSUE TITLE
Vertical Tab strip's new tab button is grouped with tabs, leaves a black space or nonfunctional + button behind

### ISSUE THREAD

**Issue by Coffeeling** [brave/brave-browser#27038]
## Description 
On Nightly and Beta, the New Tab button will follow the vertical tabset, leaving a black space at the bottom. Once the tabset has expanded enough to fill the window's height, the new tab button will stay at the bottom. If the tabset decreases in size to be smaller than the window's height, the new tab button's graphic will persist but the bottom button will be nonfunctional:

Black space on Nightly:
![image](https://user-images.githubusercontent.com/54371213/204555304-b1b93826-3f36-4e5d-91b3-285bd091e9eb.png)

Nonfunctional New Tab button on Beta:
![image](https://user-images.githubusercontent.com/54371213/204558173-0cd882ed-3f21-4942-8ca6-d9b4e70ae426.png)

* Turns black immediately on window resize.

## Steps to Reproduce
Make a new window

## Actual result:
New tab button at bottom left corner or following tablist, with the rest of the tablist blank.

## Expected result:

As seen in pictures.

## Reproduces how often: 
Always.

## Brave version (brave://version info)
Beta: 1.47.99 Chromium: 108.0.5359.48 (Official Build) beta (64-bit) 
Nightly: 1.48.10 Chromium: 108.0.5359.48 (Official Build) nightly (64-bit) 

## Version/Channel Information:

- Can you reproduce this issue with the beta channel? 
    - Yes 
- Can you reproduce this issue with the nightly channel? 
    - Yes

#24717

**Comment by rebron** [comment]
cc: @sangwoo108

**Comment by sangwoo108** [comment]
I think this will be fixed by https://github.com/brave/brave-core/pull/16501
