### ISSUE TITLE
Show account creation panel for dapp's account creation request #26637

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#27031]
## Description
Show account creation panel for dapp's account creation request. It is triggered when user has no corresponding account for the dapps request type. (Solana account for Solana dapps)

## Note
This is a follow up issue for #26637/https://github.com/brave/brave-core/pull/15869, which is marked as QA/No for 1.46.x. This needs to be verified again when Solana Dapp support is enabled by default. @Pavneet-Sing please link this issue to the PR which enables Solana support on Android by default

cc: @Pavneet-Sing @SergeyZhukovsky @jamesmudgett @brave/sec-team

**Comment by Pavneet-Sing** [comment]
Solana DApp has been enabled via https://github.com/brave/brave-core/pull/16469 PR so closing this.
