### ISSUE TITLE
Unable to add NFT via edit visible asset

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#27039]
## Description 

[nft-click.webm](https://user-images.githubusercontent.com/11755381/204568761-cd300aac-c18a-4dcf-aa8f-e84700a2eab4.webm)

**Comment by kjozwiak** [comment]
The above requires `1.47.116` or higher for `1.47.x` verification 👍

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/27114#issuecomment-1346526302
