### ISSUE TITLE
Unable to add custom token on desktop

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#27043]
## Description 

When attempting to add a custom token, clicking the `Add` button does nothing and throws an error in the console.

![Screen Shot 2022-11-29 at 1 25 35 PM](https://user-images.githubusercontent.com/40611140/204629372-aeac95c6-8b65-40d4-86ad-6139b6ce5602.png)

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards? Yes
- Is the issue reproducible on the latest version of Chrome? Yes

**Comment by kjozwiak** [comment]
The above requires `1.46.133` or higher for `1.46.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.46.133 Chromium: 108.0.5359.71 (Official Build) (64-bit)
-- | --
Revision | `1e0e3868ee06e91ad636a874420e3ca3ae3756ac-refs/branch-heads/5359@{#1016}`
OS | Linux

- Verified steps from [brave/brave-core#16142](https://github.com/brave/brave-core/pull/16142)
- Verified able to add custom token 
- Verified no console errors when adding a custom token

https://user-images.githubusercontent.com/17010094/205085034-83fe0f3d-9d04-4be5-aca7-bbbf0de11cfe.mp4

---------------------

Verification passed on 

Brave | 1.46.133 Chromium: 108.0.5359.71 (Official Build) (64-bit)
-- | --
Revision | `1e0e3868ee06e91ad636a874420e3ca3ae3756ac-refs/branch-heads/5359@{#1016}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#16142](https://github.com/brave/brave-core/pull/16142)
- Verified able to add custom token 
- Verified no console errors when adding a custom token

https://user-images.githubusercontent.com/17010094/205082907-0a5207e7-39d4-4317-812f-696d7828f31b.mp4

---------------------

Verification passed on 

Brave | 1.46.133 Chromium: 108.0.5359.71 (Official Build) (arm64)
-- | --
Revision | `1e0e3868ee06e91ad636a874420e3ca3ae3756ac-refs/branch-heads/5359@{#1016}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#16142](https://github.com/brave/brave-core/pull/16142)
- Verified able to add custom token 
- Verified no console errors when adding a custom token

https://user-images.githubusercontent.com/17010094/205087770-de392600-ad4d-45dd-81fa-de8fd1d1df22.mov
