### ISSUE TITLE
Add desktop P3A metric for weekly menu opens

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#27048]
Add P3A metric for a weekly menu open count.

How many times was the menu opened in the past 7 days?
`Brave.Toolbar.MenuOpens`

0. 0
1. 1-5
2. 6-15
3. 16-29
4. 30-49
5. 50+

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave | 1.49.91 Chromium: 110.0.5481.77 (Official Build) beta (64-bit)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | Windows 10 Version 21H2 (Build 19044.2486)

```

**Comment by DJAndries** [comment]
@GeetaSarvadnya Good catch, raised #28660
