### ISSUE TITLE
disable auto translate in Brave Translate

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#27040]
## Description 

Temporarily disable auto translate in Brave Translate by hiding the ui checkbox and menu option as well as disabling the setting for those who have previously checked the setting to on.

Place auto translate feature behind a flag that where rollout of the feature can be controlled via griffin.

## Expected result:

   1. Visit a page that invokes a Brave Translate
   2. Ensure the checkbox and options to translate are not available.
 
## Current result:

<img width="346" alt="Screenshot 2022-11-23 at 3 22 41 PM" src="https://user-images.githubusercontent.com/5951041/204581733-e8dbf1e9-87e4-41de-912b-7143067e2eb1.png">
<img width="504" alt="screenshot_2022-11-23_at_1 39 33_pm" src="https://user-images.githubusercontent.com/5951041/204581736-e71c940e-980b-47c3-8574-bcb622e4736b.png">

## Desktop Brave version:

Targeted for 1.46.x

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.46.138 Chromium: 108.0.5359.94 (Official Build) (x86_64)
-- | --
Revision | 713576b895246504ccc6b92c2fb8ce2d60194074-refs/branch-heads/5359_71@{#3}
OS | macOS Version 12.6.1 (Build 21G217)
```

**Comment by kjozwiak** [comment]
Probably should exclude this from the notes as this will be enabled a bit after the release. @LaurenWags @rebron please re-add if you feel differently.

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.46.138 x64 build

**Test Case 1: Auto Translate Disabled via flag**
- Clean install 1.46.138
- Visit `https://fr.wikipedia.org`
- Ensured Translate bar is shown
- Ensured Always Translate setting is shown
- Click on English to translate
- Ensured page gets translated to English
- Added command line args `--disable-features:BraveEnableAutoTranslate`
- Restarted the browser
- Visited `https://fr.wikipedia.org`
- Ensured Translate bar is shown again
- Click on menu, `Always Translate pages in French` option is removed
- Verified still able to click on English to translate the page manually
- Verified still able to translate the page when selecting Translate setting from menu

**Test Case 2:  Page Auto-Translate checked and then disabled via flag**
- Clean install 1.46.138
- Visit `https://fr.wikipedia.org`
- Ensured Translate bar is shown
- Ensured Always Translate setting is shown
- Click on English to translate
- Ensured page gets translated to English
- Repeat the above steps until you see notification about pages will be auto translated 
- Added command line args `--disable-features:BraveEnableAutoTranslate`
- Restarted the browser
- Visited `https://fr.wikipedia.org`
- Ensured Translate bar is shown again
- Click on menu, `Always Translate pages in French` option is removed
- Verified still able to click on English to translate the page manually
- Verified still able to translate the page when selecting Translate setting from menu
- Verified manually translating the pages multiple times doesn't enable Auto-Translate again

Test Case 1 | Test Case 2
-- | --
<video src=https://user-images.githubusercontent.com/17010094/206240038-f38f2faa-ffab-42b1-abf4-c3487f3b0e1d.mp4> | <video src=https://user-images.githubusercontent.com/17010094/206239937-72a54446-113b-4c7a-b05c-28a514edef1e.mp4>
