### ISSUE TITLE
Serialize OriginInfo data for use within Redux

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#27046]
## Description 

Redux currently recommends that all data used in actions and reducers should be serializable. Serializing the store data allows us to save or send the store state using JSON.

This PR also will prevent warnings regarding non-serializable data in OriginInfo-related transaction actions

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.48.151 Chromium: 109.0.5414.119 (Official Build) beta (64-bit)
-- | --
Revision | `772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#16146](https://github.com/brave/brave-core/pull/16146)
- Verified able to connect to Dapp
- Verified connecting to Dapp continues to work fine
