### ISSUE TITLE
'Change Auto-Contribute Settings' in unverified panel does not appear clickable

### ISSUE THREAD

**Issue by jasonrsadler** [brave/brave-browser#2705]
Follow up from https://github.com/brave/brave-core/pull/1183

## Description 
When viewing Rewards panel of unverified publisher, the link to change unverified checkbox is obscure. The mouse cursor does not change and the link does not change to indicate clickability

## Steps to Reproduce

   1. Enable Rewards
   2. Visit unverified site
   3. Open Rewards panel

## Actual result:

It is difficult to tell that 'Change Auto-Contribute settings' is interactable
<img width="412" alt="screen shot 2018-12-22 at 9 22 08 pm" src="https://user-images.githubusercontent.com/25326067/50380285-bec09600-0630-11e9-84f6-b62150e4cea0.png">

## Expected result:

'Change Auto-Contribute settings' should display similar to a hyperlink (mouse changes, text style changes, etc.)

## Reproduces how often: 

100%

## Brave version (brave://version info)

master - down to 0.58-HF1

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc @NejcZdovc

**Comment by NejcZdovc** [comment]
QA is not needed anymore as we removed this button
