### ISSUE TITLE
Modify ethereum provider P3A metric for native wallets that are not set up

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#27050]
Modify existing ethereum provider P3A metric to emit "none" when the native wallet is the ethereum provider, but the wallet itself is not set up.

What is your preferred Ethereum provider?
`Brave.Wallet.EthProvider.2`

0. None (native wallet not setup or third-party extension not installed)
1. Third-party wallet extension
2. Native wallet (wallet is setup)

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```

Brave | 1.48.128 Chromium: 109.0.5414.87 (Official Build) beta (64-bit)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | Windows 10 Version 21H2 (Build 19044.2486)

```

**Comment by GeetaSarvadnya** [comment]
@DJAndries Verified the test plan https://github.com/brave/brave-core/pull/16155. I don't see the metrics `Brave.Wallet.EthProvider.2` in Android. Could you please check from your end?

**Comment by DJAndries** [comment]
Apologies, I added the Android and iOS labels by mistake. The behavior you're describing sounds correct.
