### ISSUE TITLE
VPN config failed to load with an error `Failed to write the VPN config`

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#27056]
## Description 

VPN config error is shown when tried to connect to VPN in following scenarios:
Also noticed that `rasphone` entry disappears in `%APPDATA%\Microsoft\Network\Connections\Pbk` folder when VPN config error is shown
1.  After removing any previous configs, create a new VPN profile and connect to VPN for the first time
2.  Switch to different region once VPN is successfully connected

#### Scenario 1:  VPN connection fails first time login in  a new profile 
Pre-requisite: Remove any pre-existing VPN configs from Windows settings

1. Install `1.46.130`
2. launch Brave
3. Enable `brave://flags/#brave-vpn `
4. click `Relaunch`
5.  load `account.bravesoftware.com`
6. enter basic-auth creds for site
7. enter an email address and click `Get login link` 
8. check your email inbox
9.  click `Log in to Brave` or the link in the email
10. click on `Browse plans`
11. scroll down and click on `Buy now` for `Brave VPN Subscription`
12. enter payment details on `https://checkout.stripe.com/pay/cs_test…`
13. click `Subscribe`
14. Success screen is shown with `YOU HAVE ACTIVE CREDENTIALS LOADED!` message
15. Click VPN button in the toolbar and connect to VPN

#### Scenario 2: Switch to different region once VPN is successfully connected
- from scenario 1, switch from USA(Northwest) to Australia 
- %APPDATA%\Microsoft\Network\Connections\Pbk - `rasphone` entry disappears

## Actual result:

Got this below error: 
- `Failed to write the VPN config. This may happen if you don't have permission or if you haven't run Windows Update recently.`
- `%APPDATA%\Microsoft\Network\Connections\Pbk%` - do not show `rasphone` entry

#### Work around for both scenarios is 
- close the browser
- reboot the machine
- relaunch Brave 
- Toggled ON to connect VPN in the VPN panel 

Logs show this error: `ERROR: failed to write "NumCustomPolicy" field to rasphone.pbk`

Ex1|Ex2|scenario 2
----|----|----
![Screenshot 2022-11-29 154319](https://user-images.githubusercontent.com/98358127/204681676-6af14beb-1fcf-4bd3-8e0d-9a71a23cc914.png)|![Screenshot 2022-11-29 172703](https://user-images.githubusercontent.com/98358127/204681710-37fb202b-2d4d-4773-a045-99be61193a17.png)|![image](https://user-images.githubusercontent.com/98358127/204681825-aaef5304-7c0d-4eec-934f-b9b803cd4ba8.png)

## Expected result:
 VPN should be connected successfully without errors

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.46.130 Chromium: 108.0.5359.62 (Official Build) (64-bit)
-- | --
Revision | 041930a89a990cfab0315a2d9f20d6429a4a67cf-refs/branch-heads/5359@{#938}
OS | Windows 11 Version 21H2 (Build 22000.1219)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@mattmcalister @rebron @bsclifton @simonhong 
cc: @brave/qa-team

**Comment by kjozwiak** [comment]
The above will require `1.46.141` or higher for `1.46.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.46.141 Chromium: 108.0.5359.99 (Official Build) (64-bit)
-- | --
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | Windows 11 Version 21H2 (Build 22000.1219)
```
Verified using STR from https://github.com/brave/brave-browser/issues/27056#issue-1468905481
Confirmed VPN was successfully at the first try.
![image](https://user-images.githubusercontent.com/98358127/206781519-e9e8fa27-2259-4530-8219-ce341249a29c.png)
