### ISSUE TITLE
Sign Solana transaction with selected account instead of fee payer

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#27051]
We used to assume the wallet account will always be the fee payer and sign our Solana transactions with the fee payer account, which is not necessary the case, we should sign the transactions with the selected account instead.

One use case reported by https://civic.me/:
1. User requests our backend to issue a token
2. Our backend creates and signs a transaction (fee payer must be set at this point, and I think we set it as ourselves)
3. We send the serialised tx back to the user
4. User co-signs and sends to the chain.

In the above case, we should co-sign the transaction with the selected (connected) account.

**Comment by kjozwiak** [comment]
The above requires `1.46.139` or higher for `1.46.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.46.141 Chromium: 108.0.5359.99 (Official Build) (64-bit)
-- | --
Revision | `410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}`
OS | Windows 11 Version 22H2 (Build 22623.1028)

- Verified steps from [brave/brave-core#16154](https://github.com/brave/brave-core/pull/16154)
- Verified able to submit a Sign and Send transaction
- Verified able to submit and confirm transaction on both software and hardware wallet 


https://user-images.githubusercontent.com/17010094/206747848-d52f3f4b-1f60-4865-b756-2ede4b9a3c60.mov

**Comment by srirambv** [comment]
Note: this issue can't be tested on Android since Dapp support is not yet enabled on Release. Its already checked on nightly so leaving the Android label as is
