### ISSUE TITLE
[Brave News]: Subscribe button shouldn't show unless the user has opted in to Brave News.

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#27057]
1. Don't opt in to Brave News
2. Visit a site with an RSS feed

**Actual**
The subscribe button shows up

**Expected**
The subscribe button does not show up because the user hasn't opted in to Brave News

**Comment by btlechowski** [comment]
@rebron @LaurenWags @kjozwiak This fix needs an uplift to 1.47.x as it fixes many issues.

Issue 1: Unable to subscribe to feed through Brave News subscribe button on clean install
Unable to subscribe to first feed
![image](https://user-images.githubusercontent.com/34715963/205950407-1550ab8f-2fda-489e-9b2e-c3ed1c2e2a0f.png)

Issue 2: Blank page after subscribed to a feed and enabling Brave news
![image](https://user-images.githubusercontent.com/34715963/205950975-c17288fa-0745-4f2e-9d85-f2f5e4f0ce53.png)

**Comment by rebron** [comment]
@fallaciousreasoning @petemill Can we get uplifts for this for 1.47.x and 1.46.x?

**Comment by kjozwiak** [comment]
The above requires `1.47.120` or higher for `1.47.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSSED` using 

Brave | 1.47.120 Chromium: 108.0.5359.99 (Official Build) dev (x86_64)
-- | --
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | macOS Version 13.1 (Build 22C65)

### Steps:

1. installed `1.47.120`
2. launched Brave
3. opened `brave://flags`
4. ensured there's no flag for the Brave News button
5. loaded `theatlantic.com`
6. ensured there's no `Manage Subscriptions` button visible in the URL bar
7. opened a new-tab page
8. ensured the Brave News opt-in page is still there
9. clicked on `Customize`
10. clicked on `Brave News`
11. ensured the Brave News opt-in page is still there
12. clicked on `Show Brave News`
13. returned to `theatlantic.com` tab
14. confirmed the `Manage Subscriptions` RSS-feed icon is in the URL bar

#### Confirmed the `Manage Subscriptions` RSS-feed icon isn't visible until opted-in to Brave News

example | example | example | example | example | example | example
---------|----------|---------|----------|---------|----------|---------
<img width="1312" alt="Screenshot 2022-12-08 at 5 32 29 PM" src="https://user-images.githubusercontent.com/387249/206614318-63cb7303-a3a2-4c79-8be6-b2d81fab9fe9.png"> |. <img width="1312" alt="Screenshot 2022-12-08 at 6 57 31 PM" src="https://user-images.githubusercontent.com/387249/206614326-f0a46a80-86b8-45e1-a92f-1f54e85b9b9e.png"> | <img width="1312" alt="Screenshot 2022-12-08 at 6 57 40 PM" src="https://user-images.githubusercontent.com/387249/206614335-2162e6eb-70cd-48bd-a676-83515334e090.png"> | <img width="1312" alt="Screenshot 2022-12-08 at 6 57 49 PM" src="https://user-images.githubusercontent.com/387249/206614345-bbd8a3d3-3127-40f7-9bf4-530d39b11e6b.png"> | <img width="1312" alt="Screenshot 2022-12-08 at 6 58 32 PM" src="https://user-images.githubusercontent.com/387249/206614347-734b0965-d096-4c13-a958-84f458cb4999.png"> | <img width="1312" alt="Screenshot 2022-12-08 at 6 58 40 PM" src="https://user-images.githubusercontent.com/387249/206614349-2f233e54-346c-42e1-b7b1-e83af5ad0e6e.png"> | <img width="1312" alt="Screenshot 2022-12-08 at 6 58 43 PM" src="https://user-images.githubusercontent.com/387249/206614353-6fc66b14-8d48-486a-aaf3-f62d1ffd4860.png">
