### ISSUE TITLE
improve the colour scheme of the `Skip` text/button under onboarding v2

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#27060]
## Description 

I think we can improve the colour scheme of the `Skip` button/text that is appearing under each section of the onboarding. I don't think it matches the colour the general colour scheme and is the only black text in the entire onboarding experience. It's also not as vibrant as the other colours and harder to see on the screen compared to everything else.

## Steps to Reproduce

   1. launch brave (using `1.48.13 Chromium: 108.0.5359.62` in this case)
   2. should see `brave://welcome` (if not, you can directly go into the onboarding experience by loading `brave://welcome`

## Actual result:

![skipColour](https://user-images.githubusercontent.com/2602313/204713973-bbe93301-98d8-452a-9e2f-43d786c5d597.png)

## Expected result:

Should be able to improve the colour scheme of the `Skip` button to make it more vibrant/easier to see on the screen.

## Reproduces how often: 

100% reproducible using the above STR/Cases outlined above.

## Brave version (brave://version info)

```
Brave | 1.48.13 Chromium: 108.0.5359.62 (Official Build) nightly (64-bit)
-- | --
Revision | 041930a89a990cfab0315a2d9f20d6429a4a67cf-refs/branch-heads/5359@{#938}
OS | Windows 11 Version 22H2 (Build 22621.819)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No` (currently in `1.47.x`)
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by kjozwiak** [comment]
The above requires `1.47.131` or higher for `1.47.x` verification 👍

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.47.132 Chromium: 108.0.5359.128 (Official Build) beta (64-bit)
-- | --
Revision | 1cd27afdb8e5d057070c0961e04c490d2aca1aa0-refs/branch-heads/5359@{#1185}
OS | Ubuntu 18.04 LTS

Verified Skip button has better color scheme
![image](https://user-images.githubusercontent.com/34715963/208331033-1c44223e-e10c-4a2f-b0da-8c058b5aef9e.png)
![image](https://user-images.githubusercontent.com/34715963/208331070-7592102d-6ec8-4f47-b3a1-29b060c1b71b.png)

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.47.151 Chromium: 109.0.5414.46 (Official Build) beta (x86_64)
-- | --
Revision | 6e36b77363ef3febbe792af680fa1367993ddcf0-refs/branch-heads/5414@{#709}
OS | macOS Version 11.7.2 (Build 20G1020)

#### Confirmed the `Skip` text is white and clearly legible

### `Dark`

`page 1` | `page 2`
---------|---------
<img width="1292" alt="Screen Shot 2022-12-28 at 12 06 20 PM" src="https://user-images.githubusercontent.com/387249/209866853-a4bc11a7-727c-49f5-b165-b91f28da5294.png"> | <img width="1292" alt="Screen Shot 2022-12-28 at 12 06 30 PM" src="https://user-images.githubusercontent.com/387249/209866860-f2db1ac1-4008-4e09-99c9-d8ae4db000ae.png">



### `Light`

`page 1` | `page 2`
---------|----------
<img width="1292" alt="Screen Shot 2022-12-28 at 12 06 57 PM" src="https://user-images.githubusercontent.com/387249/209866794-20e9d1a7-d5f0-4e0e-89f0-9de736c964f7.png"> | <img width="1292" alt="Screen Shot 2022-12-28 at 12 07 00 PM" src="https://user-images.githubusercontent.com/387249/209866805-c295cf64-a920-49e6-8e74-64acf4445913.png">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.47.149 Chromium: 109.0.5414.46 (Official Build) beta (64-bit)
-- | --
Revision | 6e36b77363ef3febbe792af680fa1367993ddcf0-refs/branch-heads/5414@{#709}
OS | Windows 11 Version 22H2 (Build 22621.963)
```
#### Confirmed `Skip` text is white and clearly legible

Dark - `brave://welcome`

first screen|second screen
------|-------
![image](https://user-images.githubusercontent.com/98358127/209871855-a2872afc-90ae-4a02-968f-2eae43d2ad39.png)|![image](https://user-images.githubusercontent.com/98358127/209871897-b3bd7517-3721-4a80-90ab-e7a82d73f241.png)

Light - `brave://welcome`

first screen|second screen
------|-------
![image](https://user-images.githubusercontent.com/98358127/209872005-2a42531a-d748-4353-b7b7-00c805783db0.png)|![image](https://user-images.githubusercontent.com/98358127/209872025-5605491f-4e4f-4dca-93b7-084fc3864e8e.png)
