### ISSUE TITLE
improve the animation/rendering of onboarding v2

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#27061]
## Description 

When initially launching Brave for the first time, you'll notice that the `brave://welcome` screen is black for a few `ms` before the animations start and the screen loads. You can somewhat see the issue if you load `brave://welcome` in a new tab but it's a lot more noticeable when launching with a new profile for the first time. Seems like the duration is a bit longer compared to when loading via  new tab so it's a lot more noticeable. We should try smoothing this out.

Just a quick note that I'm on a pretty powerful machine running a `AMD Ryzen 9 5950X`, `32 GB RAM` and a dedicated `RTX 3080` GPU so I shouldn't be having any issues with rendering/related to HW acceleration.

## Steps to Reproduce

   1. launch brave (using `1.48.13 Chromium: 108.0.5359.62` in this case)
   2. should see `brave://welcome` (if not, you can directly go into the onboarding experience by loading `brave://welcome`

## Actual result:

https://user-images.githubusercontent.com/2602313/204714713-2522605c-c69c-4c5a-b23c-56c7a1a202e4.mp4

![Screenshot 2022-11-28 142251](https://user-images.githubusercontent.com/2602313/204714754-3f6ec78d-a850-47b5-83db-38ca17941c12.png)

## Expected result:

Animation/Rendering should be a lot smoother compared to what we have now. The user shouldn't see any flickers. Assuming users with slower machines might experience what I'm experience even more.

## Reproduces how often: 

100% reproducible using the STR/Cases outlined above.

## Brave version (brave://version info)

```
Brave | 1.48.13 Chromium: 108.0.5359.62 (Official Build) nightly (64-bit)
-- | --
Revision | 041930a89a990cfab0315a2d9f20d6429a4a67cf-refs/branch-heads/5359@{#938}
OS | Windows 11 Version 22H2 (Build 22621.819)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No` (currently in `1.47.x`)
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by kjozwiak** [comment]
The above requires `1.47.131` or higher for `1.47.x` verification 👍

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.47.132 Chromium: 108.0.5359.128 (Official Build) beta (64-bit)
-- | --
Revision | 1cd27afdb8e5d057070c0961e04c490d2aca1aa0-refs/branch-heads/5359@{#1185}
OS | Ubuntu 18.04 LTS

Verified the test plan from the description
Verified animation is smother even on slow machine
![27061](https://user-images.githubusercontent.com/34715963/208331692-83dee17d-343e-47e1-b57b-96584e2b192c.gif)

I can still see a white page flash though. @kjozwiak not sure if this is an issue.

**Comment by btlechowski** [comment]
Added `QA/Test-All-Platforms` to test on more platforms as this issue can be quite subjective

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```

Brave | 1.47.149 Chromium: 109.0.5414.46 (Official Build) beta (64-bit)
-- | --
Revision | 6e36b77363ef3febbe792af680fa1367993ddcf0-refs/branch-heads/5414@{#709}
OS | Windows 10 Version 21H2 (Build 19044.2364)

```
Verified the test plan from the description
Verified animation is smother even on slow machine

**Comment by LaurenWags** [comment]
Verified with

```
Brave | 1.47.167 Chromium: 109.0.5414.80 (Official Build) (x86_64)
-- | --
Revision | 0f69b168d36a06cace4365e9f029fa987afa5633-refs/branch-heads/5414@{#1178}
OS | macOS Version 12.6.2 (Build 21G320)
```

Compared loading of brave://welcome on 1.47.167 and 1.48.13. The page animation/rendering is smoother on 1.47.x after the fix. On 1.48.x everything kind of pops up where as on 1.47.x they fade in nicer and it's not as jarring.
