### ISSUE TITLE
iframe background is not matching wallet color scheme

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#27068]
![Image](https://user-images.githubusercontent.com/48117473/204846690-73f2f5fb-9cae-47d5-81d5-556eef656c96.png)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.48.141 Chromium: 109.0.5414.119 (Official Build) beta (64-bit) 
-- | --
Revision | `772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}`
OS | Linux

- Verified steps from [brave/brave-core#16173](https://github.com/brave/brave-core/pull/16173)
- Verified market tab is shown correctly on both light and dark theme

Light | Dark
-- | --
![image](https://user-images.githubusercontent.com/17010094/215739776-97c24827-9c95-4b95-a1f1-a02f2e264a40.png) | ![image](https://user-images.githubusercontent.com/17010094/215739852-d934d8e5-74c4-4a77-8e81-05fe8bf6b197.png)

---------------------

Verification passed on 

Brave | 1.48.141 Chromium: 109.0.5414.119 (Official Build) beta (64-bit)
-- | --
Revision | `772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#16173](https://github.com/brave/brave-core/pull/16173)
- Verified market tab is shown correctly on both light and dark theme

Light | Dark
-- | --
![image](https://user-images.githubusercontent.com/17010094/215739635-5d815af4-d4a9-4ae8-9f3c-1a8672d240aa.png) | ![image](https://user-images.githubusercontent.com/17010094/215739696-0bdceab4-861f-4129-8945-969ea673f847.png)

---------------------

Verification passed on 

Brave | 1.48.141 Chromium: 109.0.5414.119 (Official Build) beta (arm64)
-- | --
Revision | `772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#16173](https://github.com/brave/brave-core/pull/16173)
- Verified market tab is shown correctly on both light and dark theme

Light | Dark
-- | --
![image](https://user-images.githubusercontent.com/17010094/215740037-b030a727-88f4-4538-b43c-91474ad1b6b5.png) | ![image](ttps://user-images.githubusercontent.com/17010094/215739969-f7bf3b90-4553-4443-8c02-d9f529f3efb0.png)
