### ISSUE TITLE
Convert "add custom asset" dialog to full screen and create separate NFT screen to add NFT  

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#27070]
## Description

Convert "Add custom asset" and "Add NFT" dialogs into a full screen and show appropriate fields for adding NFTs or custom assets.

### Current Android UI

| Asset | NFT |
| ------- | ------ |
| <img width="400" alt="Screenshot 2023-06-30 at 11 09 27 AM" src="https://github.com/brave/brave-browser/assets/3308503/e21b18c5-bf61-4b5c-96ea-1fc73f84a919"> | <img width="400" alt="Screenshot 2023-06-30 at 11 10 53 AM" src="https://github.com/brave/brave-browser/assets/3308503/608ac875-15c2-460a-b8b9-cc60feaab62d"/> |

### iOS Preview

| Asset | NFT |
| ------- | ------ |
| <img src="https://user-images.githubusercontent.com/11755381/204870384-4a2a4713-6c23-4564-9bf3-3b7718c91c64.png" alt="drawing" width="300"/> | <img src="https://user-images.githubusercontent.com/11755381/204870398-1d1b5b75-6985-4b89-a806-58176cfcad94.png" alt="drawing" width="300"/> |

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.58.117 x64 build
- Verified steps from [brave/brave-core#19195](https://github.com/brave/brave-core/pull/19195)
- Verified able to add custom asset/NFT
- Verified add custom token is shown in full screen similar to iOS

https://github.com/brave/brave-browser/assets/17010094/154c0c43-c3fd-4057-86d6-d7585f801602
