### ISSUE TITLE
Save button in the On Exit page is greyed out

### ISSUE THREAD

**Issue by helpthemfix** [brave/brave-browser#27080]
Tested on Brave 107 and Brave Nightly 108, Same issue. No matter what I click it's still greyed out. Tried checking and unchecking itmes to no avail.

**OS is Windows 10 2021H2**

![Capture](https://user-images.githubusercontent.com/92321993/204928190-d98d4827-924d-4705-ade5-f4ad8da2fa87.PNG)

**Comment by Brave-Matt** [comment]
This issue has already been fixed and is in Nightly builds presently:
https://github.com/brave/brave-browser/issues/26819
