### ISSUE TITLE
Bad layout on https://www.forbes.com

### ISSUE THREAD

**Issue by boocmp** [brave/brave-browser#27086]
## Description 

Article looks ugly in speedreader.

We decided to remove all svg images from the distilled page because we assume that svgs used to display any icons (e.g. on buttons) and these icons are most likely not meaningful content.

## Steps to Reproduce

1. Enable speedreader
2. Navigate to https://www.forbes.com/sites/thomasbrewster/2019/08/15/apple-is-suing-a-cybersecurity-startup-for-illegally-replicating-iphones/

## Actual result:

Page looks ugly because of very big icons

## Expected result:

Page looks readable

## Reproduces how often: 

Easy/100%

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.48.121 Chromium: 109.0.5414.87 (Official Build) beta (x86_64)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | macOS Version 11.7.2 (Build 20G1020)

### Steps:
1. installed `1.48.121`
2. launched Brave
3. loaded `https://www.forbes.com/sites/thomasbrewster/2019/08/15/apple-is-suing-a-cybersecurity-startup-for-illegally-replicating-iphones/`
4. enabled `Speedreader` mode
5. viewed the page

#### Confirmed no more giant icons appearing in the `Speedreader`-mode's content

`1.48.121` | `1.48.121` | `1.47.169` | `1.47.169`
---------|----------|-----------|----
<img width="1782" alt="Screen Shot 2023-01-11 at 4 54 34 PM" src="https://user-images.githubusercontent.com/387249/211950267-95d55291-56e0-425d-a74a-31630d50e596.png"> | <img width="1782" alt="Screen Shot 2023-01-11 at 4 54 39 PM" src="https://user-images.githubusercontent.com/387249/211950274-4254665b-61c2-45d1-a8c1-84068b708daf.png"> | <img width="1312" alt="Screen Shot 2023-01-11 at 4 48 55 PM" src="https://user-images.githubusercontent.com/387249/211950559-c7cd8f38-efe5-4c4b-b481-f2b5e9919a15.png"> | <img width="1312" alt="Screen Shot 2023-01-11 at 4 49 05 PM" src="https://user-images.githubusercontent.com/387249/211950561-87c8ebc8-848c-45cc-8d23-424812a95a19.png">
