### ISSUE TITLE
Replace the Muli font with Poppins (missing places)

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#27081]
## Description 

Adding a few places where Poppins is not loading and it should, so far everything I found is on the NTP

## Steps to Reproduce

1.48.5 Chromium: 108.0.5359.48 (Official Build) nightly (arm64) 
 
   1. Open NTP

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/15734630/204915439-ede359ca-5bbf-4c2b-923e-179781da9710.png">

<img width="586" alt="image" src="https://user-images.githubusercontent.com/15734630/204915461-c46f3be3-39c9-49d5-ae4f-c5479ac6a2b1.png">

<img width="398" alt="image" src="https://user-images.githubusercontent.com/15734630/204915488-a31800c1-1f8c-4486-9732-8addc54c869a.png">

Brave news:
<img width="275" alt="image" src="https://user-images.githubusercontent.com/15734630/204915534-5b8b0f7e-9237-4bb3-bfbb-4f59e4f836bf.png">

**Comment by ksgokul2501** [comment]
Hi, I'd like to take this up. Do you assign issues or shall I open a PR directly? @rebron

**Comment by Simun-12** [comment]
Hi @rebron , I am willing to take up this issue. Will you assign it ?

**Comment by Dev79844** [comment]
Hey @rebron, I would like to work on this issue. Can you assign it to me?

**Comment by rielAsh24** [comment]
@aguscruiz Has #25527 fixed the issue or there are more fixes needed?

**Comment by aguscruiz** [comment]
Hi! We haven't fixed it yet. @rebron leaving it up to you

**Comment by rielAsh24** [comment]
@rebron I'll be glad to contribute to this if assigned!

**Comment by sash9696** [comment]
Hi @rebron , I am interested to take up this issue. Would you assign it ?

**Comment by utkarsh-shrivastav77** [comment]
Hi @rebron  is this issue still open

**Comment by harshita-ramchandani** [comment]
Can you assign this issue to me please? Also, is this issue being assigned or we can directly raise a PR?

**Comment by aguscruiz** [comment]
@rebron this one can be closed

**Comment by rebron** [comment]
Closing as fixed. 

@utkarsh-shrivastav77 @sash9696 @rielAsh24 @Dev79844 @Simun-12 @ksgokul2501 thanks so much for expressing interest to fix this issue. The fixed was done via a UI library update, completed elsewhere. We'll see if we can get you all involved in some other parts of the product. Items tagged good first issue is a good place to start https://github.com/brave/brave-browser/labels/good%20first%20issue
