### ISSUE TITLE
Selecting "Restore settings to their original defaults" broken

### ISSUE THREAD

**Issue by michaellmonaghan** [brave/brave-browser#2708]
## Test plan
See https://github.com/brave/brave-core/pull/2130/files

## Description 

"Restore settings to their original defaults" does nothing. Appears to load indefinitely.

## Steps to Reproduce

   1. Open settings
   2. Click "Restore settings to their original defaults"

## Actual result:

Settings not cleared and the following shown indefinitely.
![image](https://user-images.githubusercontent.com/4855844/50380779-d869d980-0640-11e9-8475-34f0a880eb5e.png)

## Expected result:
Settings would be cleared.

## Reproduces how often: 

Reproducible on both machines I use brave on.

## Brave version (brave://version info)

0.58.16 Chromium: 71.0.3578.98 (Official Build) (64-bit)]

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
not tested

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
no

- Is the issue reproducible on the latest version of Chrome? 
no

**Comment by srirambv** [comment]
Issue reproduced on `0.58.18` as well.

**Comment by rebron** [comment]
cc: @mkarolin can you take a peak when you get a chance?

**Comment by LaurenWags** [comment]
Issue reproduces with 

Brave | 0.62.33 Chromium: 73.0.3683.75 (Official Build) beta(64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Mac OS X

**Comment by jasonrsadler** [comment]
When reset pushed, get in console:
```
[88589:775:0331/105815.341086:ERROR:CONSOLE(123)] "Uncaught TypeError: Cannot set property 'checked' of undefined", source: chrome://settings/reset_page/reset_profile_dialog.js (123)
```

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.64.75 Chromium: 74.0.3729.131 (Official Build) (64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Linux

* Verified reset settings modal is closed after clicking on reset button
* Verified pinned tabs, search engine and new tab settings are reset
* Logged an issue to reset Brave implementations of shields/social media and extensions settings to  be reset #4421
