### ISSUE TITLE
Update "refresh creator status" tooltip

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#27082]
## Description

Update tooltip to say:

"Refresh Creator verification status" 

![image](https://user-images.githubusercontent.com/11497541/204936052-990951a1-5ba3-4dc5-a00b-7c28b604466b.png)

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.48.125 Chromium: 109.0.5414.87 (Official Build) beta (x86_64)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | macOS Version 12.6.2 (Build 21G320)
```

Confirmed updated tooltip:

Dark | Light
---- | ----
<img width="491" alt="Screen Shot 2023-01-13 at 11 27 24 AM" src="https://user-images.githubusercontent.com/28145373/212370334-0bb85cbd-d018-48b5-b4a2-7e9ce51f2526.png"> | <img width="494" alt="Screen Shot 2023-01-13 at 11 28 15 AM" src="https://user-images.githubusercontent.com/28145373/212370335-38c149e2-63a1-4472-a7fe-3b839abdb39e.png">
