### ISSUE TITLE
[Follow up to 26492] Cookie consent banner shown

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#27098]
## Description 
Cookie consent banner shown

Original issue: https://github.com/brave/brave-browser/issues/26492

## Steps to reproduce 

1. Disable Easylist-Cookie List - Filter Obtrusive Cookie Notices in brave://settings/shields/filters
2. Add the following to the Create custom filters box in brave://settings/shields/filters
```
##.civic_cookie__banner
##.civic_cookie__overlay
```
3. Visit https://websummit.com/

## Actual result 
Cookie consent banner shown
Example | Example
-|-
![screenshot-1669917436102](https://user-images.githubusercontent.com/17885425/205133499-98fd7168-1ce8-41eb-8ee6-f813f580cf3a.png) | ![screenshot-1669917454131](https://user-images.githubusercontent.com/17885425/205133500-e06dea7f-cfe6-4122-ae89-81cbca08ae8c.png)

## Expected result
Cookie consent banner should be blocked

## Issue reproduces how often 
Easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung Galaxy devices
   - Android version: 12
   
## Brave version
1.46.133

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

CC: @kjozwiak @srirambv

**Comment by ryanbr** [comment]
Can you check Brave Beta @Uni-verse

**Comment by stephendonner** [comment]
## Verified `PASSED` using `Brave` `1.48.141`, `Chromium` `109.0.5414.19` on a `Google Pixel XL` (`arm64`) running `Android 9`

### Steps:
1. installed `1.48.141`
2. launched Brave
3. opened `brave://adblock`
4. tapped to deselect `Easylist-Cookie List - Filter Obtrusive Cookie Notices`
5. added the following to the bottom textarea:
```
##.civic_cookie__banner
##.civic_cookie__overlay
```
6. loaded `https://websummit.com`
7. confirmed no cookie-confirmation banner

example | example | example | example
---------|---------|----------|---------
![Screenshot_20230128-230332](https://user-images.githubusercontent.com/387249/215311367-2e28f6f2-86af-460f-9aa6-22013401d3ca.png) | ![Screenshot_20230128-230340](https://user-images.githubusercontent.com/387249/215311378-33ffe4a9-f7e2-4218-b4a7-8593c264863a.png) | ![Screenshot_20230128-230953](https://user-images.githubusercontent.com/387249/215311391-76ff1c77-7467-4915-936f-01f3aaf3d7db.png) | ![Screenshot_20230128-231011](https://user-images.githubusercontent.com/387249/215311393-f51d0bf0-c828-4a47-81df-3be67313056b.png)
