### ISSUE TITLE
[Android] YT Improvements - Skip in-video sponsor segments

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#27097]
## Description
We could improve the YT experience in Brave by allowing users to skip sponsor segments. These are the sponsorship segments that are part of the video itself. e.g. MrBeast talking about some kind of product he's selling at the beginning of his videos.

There is an existing open source product SponsorBlock that crowdsources where the segments are found in YT videos. It also has a public API. SponsorBlock also supports skipping other categories, such as intros, outros and reminders to subscribe, and skipping to the point with highlight.

https://sponsor.ajay.app

**Note: sponsor segments might be deemed 1st party, so we will need to investigate the legality of skipping these**

**Comment by ajayyy** [comment]
Feel free to reach out to me if you have any questions
