### ISSUE TITLE
Tips are not laid out neatly

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#2709]
## Description 
Tips may be rendered oddly.

## Steps to Reproduce
1. Make a couple tips: one of 5 BAT and another of 10 BAT.

## Actual result:
Layout is odd.

![image](https://user-images.githubusercontent.com/815158/50380938-dbfc6100-063e-11e9-96ed-090414c36056.png)

## Expected result:
Amounts should be laid out neatly.

## Reproduces how often: 
Depends on the amounts, I believe.

## Brave version (brave://version info)
0.58.16

### Reproducible on current release:
Yes

**Comment by kirkins** [comment]
Having trouble reproducing the issue.

![](https://i.imgur.com/JYKH9cT.png)

Version 0.59.9 Chromium: 72.0.3626.17 (Official Build) unknown (64-bit)

**Comment by LaurenWags** [comment]
@sampson are you still experiencing this?

**Comment by EOstling** [comment]
Is this being worked? If not I would like to contribute :)

**Comment by kjozwiak** [comment]
@EOstling we'll need to find out if @jonathansampson or any other users are still experiencing this issue before taking another look. I've personally haven't experienced this.

@jonathansampson are you still experiencing this issue?

CCing @alexwykoff about contributing towards Rewards.

**Comment by abhishek71994** [comment]
Is this issue being worked on? I can take it up.

**Comment by EOstling** [comment]
@abhishek71994 Yes, once I get the go ahead from @kjozwiak Ill begin dev on it.

**Comment by jonathansampson** [comment]
I don't appear to be experiencing this any longer.

**Comment by kjozwiak** [comment]
Thanks for the double check @jonathansampson 👍I'm going to close this off. If you experience this issue again, please ether re-open or create a new issue.
