### ISSUE TITLE
[Android] YT Improvements - Settings to remove distracting elements

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#27095]
## Description
We could improve the YT experience in Brave by giving users the option to remove "distracting" elements from the page. These could be enabled via a new settings group.

e.g. 

- Comments
- Live chat
- Related videos
- etc

A couple of examples of other products doing this:

- https://piped.video/preferences (https://github.com/TeamPiped/Piped)
- https://unhook.app/ (chrome extension)

### Spec
https://docs.google.com/document/d/1WVisEvd6HDr-QsJ5tZjl1m0ZKTTXIW-yqrAARxeZtS8/edit?usp=sharing

**Comment by stephendonner** [comment]
## Verified `PASSED` using a `Google Pixel XL` (`arm64`) running `Android 9`:

```
Brave	1.52.102 Chromium: 113.0.5672.126 (Official Build) beta (32-bit)
Revision	c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}
OS	Android 9; Build/PQ2A.190305.002; 28; REL
```

### Steps:
1. installed `1.52.102`
2. launched Brave
3. tapped on the 3-dots menu
4. tapped on `Settings`
5. tapped on `Brave Shields & privacy`
6. swiped down to `Youtube` (sic - issue filed on the typo)
7. tapped to enable `Hide YouTube Distracting Elements`
8. loaded `https://www.youtube.com/watch?v=QMxm7z7VFoo`

### Confirmed comments, `Subscribe` button, `Open App`, live chat, like/dislike controls, etc. were hidden

### `Prefs`

example | example
---------|---------
![Screenshot_20230518-144538](https://github.com/brave/brave-browser/assets/387249/b95c8785-1d98-435d-ad98-59748f3aa6bc) | ![Screenshot_20230518-143831](https://github.com/brave/brave-browser/assets/387249/8ffcc04d-541f-48d1-be57-907f20ed1f30) 

### `YouTube content`

example | example
---------|---------
![Screenshot_20230518-145117 (1)](https://github.com/brave/brave-browser/assets/387249/ec4c46d4-ef14-490e-a490-0543e19c11bc) | ![Screenshot_20230518-145215 (1)](https://github.com/brave/brave-browser/assets/387249/75444de9-03ca-49bc-9770-d59f99b378ed)

**Comment by vlad-hoff** [comment]
Verified on `Google Nexus 5X` and `Galaxy Tab S8` using version(s):
```
Device/OS: 
- Google Nexus 5X [Android 8.1]
- SM-X700 Galaxy Tab S8 [gts8wifixx-user 13 TP1A.220624.014 release-keys]
Brave build: 1.52.109
Chromium: 114.0.5735.26 (Official Build) beta (64-bit)
Revision: 7075cbb66f0542ac3e01ddfde6b813e7d61118a5-refs/branch-heads/5735@{#454}
```
---------------------------

**STEPS:**
1. Install 1.52.x
2. Launch Brave
3. Open Hamburger Menu > Settings
4. Brave Shields & privacy
5. Find `Youtube`
6. Enable toggle switch for `Hide YouTube Distracting Elements`
7. Open `youtube.com` > Play any video

**ACTUAL RESULTS:**
- Verified that Comments, Subscribe button, Open App, Live chat, Like/Dislike controls, etc. were hidden

<details>
<summary> Android 8 - PASS </summary>

|Toggle OFF Portrait|Toggle ON Portrait|Toggle OFF Landscape|Toggle ON Landscape|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/0f6f769a-2e56-4a60-ac84-b17318ee3249) | ![2](https://github.com/brave/brave-browser/assets/128532965/0b9dcc26-e715-4988-8ffc-1cb75593e523) | ![3](https://github.com/brave/brave-browser/assets/128532965/db14cc42-9eea-4d1d-ba91-5640ff4b4ce7) | ![4](https://github.com/brave/brave-browser/assets/128532965/db787c94-ebbd-48da-a8ed-cda31eb67598) |
</details>

<details>
<summary> Android 13 Tablet - PASS </summary>

|Toggle OFF Portrait|Toggle ON Portrait|Toggle OFF Landscape|Toggle ON Landscape| 
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/e63ceb73-03ca-4f8b-9124-ecc3e3d5a819) | ![2](https://github.com/brave/brave-browser/assets/128532965/a6a99d4b-ae47-4c9a-b9d4-021f27e2c94d) | ![3](https://github.com/brave/brave-browser/assets/128532965/ccd0accf-5bdb-40da-88be-3b061be5075a) | ![4](https://github.com/brave/brave-browser/assets/128532965/8f6ae87f-b1d5-4fe1-87c5-68dde50d26ec) |
</details>
