### ISSUE TITLE
Add network selector drop down filter on "Edit visible assets" dialog

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#27093]
## Description 
Add network selector drop down filter on "Edit visible assets" dialog and show corresponding assets per network

![Screenshot from 2022-12-01 22-18-19](https://user-images.githubusercontent.com/11755381/205111732-ed431d90-7488-44db-8e7a-afd4070d5735.png)

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.58.117 x64 build
- Verified steps from [brave/brave-core#19015](https://github.com/brave/brave-core/pull/19015)
- Verified network selector is shown in Edit visible asset screen
- Verified network selector is shown on both portfolio edit visible asset and NFT selector 

https://github.com/brave/brave-browser/assets/17010094/68ea95f4-e0bb-4d04-a3cf-dbd5700c9c6a
