### ISSUE TITLE
News and Tor icons should not appear in url bar when entering new url

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#27104]
## Description 

The Brave News icon and the Tor icon may sometimes remain when entering a new url. The url bar should only include the new url being typed.

## Steps to Reproduce

   1. Use 1.47.108 or higher in Beta channel or 1.48.20 or higher in Nightly.
   2. Visit https://nytimes.com
   3. Enter a new url like yahoo.com. Brave News RSS icon or Tor icon should not appear when typing the url.

## Actual result:

<img width="909" alt="Screenshot 2022-12-01 at 3 11 30 PM" src="https://user-images.githubusercontent.com/5951041/205180704-5efcaae9-ed95-400e-93b2-422f6b893574.png">

## Expected result:
<img width="1031" alt="Screenshot 2022-12-01 at 3 29 14 PM" src="https://user-images.githubusercontent.com/5951041/205180881-b36a83b7-a59b-433d-b932-ea9ba54d8d14.png">

## Reproduces how often: 

Easily.

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes for Tor button
- Can you reproduce this issue with the beta channel? yes for RSS and Tor button
- Can you reproduce this issue with the nightly channel? yes for RSS and Tor button

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by kjozwiak** [comment]
The above requires `1.46.143` or higher for `1.46.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS

```
Brave | 1.46.143 Chromium: 108.0.5359.99 (Official Build) (64-bit)
-- | --
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | Windows 10 Version 21H2 (Build 19044.2251)

```
- Verified the STR/Cases outlined via https://github.com/brave/brave-core/pull/16243#issue-1477436617 & https://github.com/brave/brave-browser/issues/27104#issue-1472096765
