### ISSUE TITLE
reward OS notification warning modals are both appearing within the same session

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#27107]
## Description 

Looks like the `Reward` modals are both appearing within the same session. For example, if you disable `Notifications` within Brave, going back to the `Settings` page, you'll receive the warning modal with the `Got it` button. However, if you return to the NTP, you'll get another warning modal, this time the one with the `Turn on Brave notifications` button.

We should probably only be displaying one warning per session and as per https://github.com/brave/brave-browser/issues/26930, we should only be showing them once.

## Steps to reproduce 

   1. install `1.46.133 Chromium: 108.0.5359.71` on `Android 12`
   2. go through onboarding and enable rewards via the panel
   3. once rewards has been enabled, disable OS notifications through Brave using `Settings` -> `Notifications`
   4. tap on `<` which will take you back to `Settings` and you'll see your first `rewards warning` modal (dismiss the modal via `X`)
   5. tap on `X` to close `Settings` and return to the NTP

You'll notice another `rewards warning` modal once again (even though you've just seen one a few seconds ago)

## Actual result 

*`Example of Rewards modal being displayed twice`*

https://user-images.githubusercontent.com/2602313/205184033-fda303a9-faa2-417e-bdd4-e74d63767ec8.mp4

## Expected result

The above might be expected as the modals are different in nature but I think we should probably show them in different sessions rather than both within the same session. For example, display the `Got it` modal first and then the one with `Turn on Brave notifications` after the browser has been restarted.

*`Note:`* The privacy report modals appear to do the suggested behaviour, seems like it's just the `Reward` modals that both show within the same session. Example:

https://user-images.githubusercontent.com/2602313/205184858-40b25b52-f091-4108-88de-114c10f4c98c.mp4

## Issue reproduces how often 

100% reproducible using the STR/Cases outlined above.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `Yes`
- Can you reproduce this issue with the current Play Store Beta version? `Yes` 
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Samsung Galaxy S10+` (Phone)
   - Android version: `Android 12`
   
## Brave version

```
Brave | 1.46.133 Chromium: 108.0.5359.71 (Official Build) (32-bit)
--- | ---
Revision | 1e0e3868ee06e91ad636a874420e3ca3ae3756ac-refs/branch-heads/5359@{#1016}
OS | Android 12; Build/SP1A.210812.016
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

### Additional information

CCing @deeppandya @sujitacharya2005 @Uni-verse @srirambv @timchilds

**Comment by sujitacharya2005** [comment]
@kjozwiak 
Updated this condition as per this
- For 3rd launch case just re-check the conditions and show the proper dialog.
- From Brave Setting case once click on notification and come back show the corresponding dialog.
 
PR : https://github.com/brave/brave-core/pull/16128

1. Application re-launch 3rd time
2. From Brave setting -> notification click each time

If main notification is off, Rewards feature is off, privacy feature is off -> Show Generic Dialog
if main notification is off, Rewards feature is on, privacy feature is off -> Show rewards message dialog
if main notification if off, Rewards feature is off, privacy feature is on -> show Privacy message dialog
if main notification is off, Rewards feature is on, Privacy feature is on -> Show both rewards & privacy message dialog

**Comment by kjozwiak** [comment]
So this appears to have been fixed with https://github.com/brave/brave-core/pull/16681. I'm not seeing the NTP modals appear within the same session anymore once the notifications have been disabled. Went through it several times via https://github.com/brave/brave-core/pull/16681#issuecomment-1383056642 on `Nightly` and https://github.com/brave/brave-browser/issues/27810#issuecomment-1383079491, https://github.com/brave/brave-browser/issues/27808#issuecomment-1383079518 and https://github.com/brave/brave-browser/issues/27809#issuecomment-1383079560 on `release`.
