### ISSUE TITLE
Create a dedicated desktop page for wallet transactions

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#27106]
## Description 

Provide a screen located at `/crypto/transactions` for viewing transactions

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.48.141 Chromium: 109.0.5414.119 (Official Build) beta (64-bit) 
-- | --
Revision | `772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}`
OS | Linux

- Verified steps from [brave/brave-core#16196](https://github.com/brave/brave-core/pull/16196)
- Verified a new tab for transactions is available
- Verified when there are no transactions placeholder text is shown
- Verifies submitted and completed transactions are listed
- Verified transaction state is automatically updated
- Verified able to search for transactions

https://user-images.githubusercontent.com/17010094/215463396-118567d6-dc36-4f6f-b23b-84764db5b2c9.mp4

---------------------

Verification passed on 

Brave | 1.48.141 Chromium: 109.0.5414.119 (Official Build) beta (64-bit)
-- | --
Revision | `772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#16196](https://github.com/brave/brave-core/pull/16196)
- Verified a new tab for transactions is available
- Verified when there are no transactions placeholder text is shown
- Verifies submitted and completed transactions are listed
- Verified transaction state is automatically updated
- Verified able to search for transactions

https://user-images.githubusercontent.com/17010094/215491734-e3a24062-d48c-44a2-866d-c178f2ca0bf2.mp4

---------------------

Verification passed on 

Brave | 1.48.141 Chromium: 109.0.5414.119 (Official Build) beta (arm64)
-- | --
Revision | `772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#16196](https://github.com/brave/brave-core/pull/16196)
- Verified a new tab for transactions is available
- Verified when there are no transactions placeholder text is shown
- Verifies submitted and completed transactions are listed
- Verified transaction state is automatically updated
- Verified able to search for transactions

https://user-images.githubusercontent.com/17010094/215493032-2663510f-6de0-43a7-8e14-fb6eb012600c.mov
