### ISSUE TITLE
`Got it` OS notification warning modals appearing every single time notifications are disabled

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#27108]
## Description 

We're always displaying the `Got it` version of the warning modals when a user disables `OS notifications` within `Brave` using `Settings` -> `Notifications`. As per https://github.com/brave/brave-browser/issues/26930, we should probably only be showing it once per session even though the user disables/enables `OS notifications` several times within a single session.

Believe this also affects `Rewards`, `Privacy Policy` & `Rewards & Privacy Policy` modals

*`Note:`* I would assume this is a corner case as I don't expect a lot of users to disable/enable `OS notifications` several times within the same session but we should probably get this fixed or improve the experience

## Steps to reproduce 

   1. launch `1.46.133 Chromium: 108.0.5359.71`
   2. run through onboarding and enable rewards
   3. once enabled, go into `Settings` -> `Notifications` and disable notifications
   4. go back to the `Settings` via the `<` (back button)
   5. you'll notice you'll get the warning modal
   6. go back into `Notifications` and Enable/Disable once again
   7. go back to the `Settings` via the `<` (back button) & you'll notice you'll get the warning modal once again

Repeat the above and you'll just keep getting the warning modals.

## Actual result 

https://user-images.githubusercontent.com/2602313/205186389-a8d5a956-0b94-4439-bdf4-eeabb19abc16.mp4

## Expected result

We should only be showing the above once. Or at least once per session.

## Issue reproduces how often 

100% reproducible using the STR/Cases outlined above.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `Yes`
- Can you reproduce this issue with the current Play Store Beta version? `Yes` 
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Samsung Galaxy S10+` (Phone)
   - Android version: `Android 12`
   
## Brave version

```
Brave | 1.46.133 Chromium: 108.0.5359.71 (Official Build) (32-bit)
--- | ---
Revision | 1e0e3868ee06e91ad636a874420e3ca3ae3756ac-refs/branch-heads/5359@{#1016}
OS | Android 12; Build/SP1A.210812.016
```

### Website problems only

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

### Additional information

CCing @deeppandya @sujitacharya2005 @Uni-verse @srirambv @timchilds

**Comment by sujitacharya2005** [comment]
@kjozwiak 
Updated this condition as per this
- For 3rd launch case just re-check the conditions and show the proper dialog.
- From Brave Setting case once click on notification and come back show the corresponding dialog.
 
PR : https://github.com/brave/brave-core/pull/16128

1. Application re-launch 3rd time
2. From Brave setting -> notification click each time

If main notification is off, Rewards feature is off, privacy feature is off -> Show Generic Dialog
if main notification is off, Rewards feature is on, privacy feature is off -> Show rewards message dialog
if main notification if off, Rewards feature is off, privacy feature is on -> show Privacy message dialog
if main notification is off, Rewards feature is on, Privacy feature is on -> Show both rewards & privacy message dialog

**Comment by kjozwiak** [comment]
@sujitacharya2005 @deeppandya this should have been added into https://github.com/brave/brave-core/pull/16128 if the PR resolved the above issue. I went through the above cases a bunch of times while verifying both https://github.com/brave/brave-core/pull/16128 and confirmed that the generic `Got it` notification warning only appears once. Updating https://github.com/brave/brave-core/pull/16128 & https://github.com/brave/brave-core/pull/16320#issue-1487820335 to include the above as part of the `Resolved` list.
