### ISSUE TITLE
[iOS] - Cannot build Rust 1.1.0 with Clang x86_64 (lld error)

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-browser#27100]
## Description 
- When compiling Brave-Core for iOS, it compiles Rust 1.1.0 and fails with the error:
```
ld64.lld: error: too many personalities (4) for compact unwind to encode
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

## Steps to Reproduce

   1. Compile Brave-Core iOS for x86_64

## Actual result:
```
ld64.lld: error: too many personalities (4) for compact unwind to encode
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

## Expected result:
- Should compile

## Reproduces how often: 
- Easily Reproduced (100%)

## Brave version:
- 1.48.x

## Version/Channel Information:
- Current release (v1.48.21)

**Comment by kjozwiak** [comment]
Moving this out of `1.48.x` as it still looks opened and hasn't been resolved/merged into `master`. Once fixed, it should go into the `master` milestone which is currently `1.50.x`.
