### ISSUE TITLE
Font color for onboardingv2 for dark theme is too light for import screens

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#27105]
## Description 

Text isn't legible for two of the import screens for onboarding v2 in dark theme.

## Steps to Reproduce

   1. Use 1.47.x or 1.48.x
   2. Go to brave://welcome and go to Import screen screens. 
   3. Text isn't legilble and font color should be darker

## Actual result:

<img width="648" alt="Screenshot 2022-12-01 at 3 40 28 PM" src="https://user-images.githubusercontent.com/5951041/205182168-b6ab5e85-fa6a-456d-a681-78c43d4f3961.png">
<img width="864" alt="Screenshot 2022-12-01 at 3 40 14 PM" src="https://user-images.githubusercontent.com/5951041/205182170-b0bb4539-9c44-40df-87a6-67f4c49fbf84.png">

## Expected result:
<img width="631" alt="Screenshot 2022-12-01 at 3 42 22 PM" src="https://user-images.githubusercontent.com/5951041/205182233-00c40872-c49d-4270-81f4-e9843a730b59.png">
<img width="923" alt="Screenshot 2022-12-01 at 3 42 15 PM" src="https://user-images.githubusercontent.com/5951041/205182237-624381c6-3a43-46b5-97ae-46813e4f1b77.png">

## Reproduces how often: 

easily

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by stephendonner** [comment]
As I saw this on macOS too, marking `QA/Test-All-Platforms` so it can be verified there, also.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.47.149 Chromium: 109.0.5414.46 (Official Build) beta (x86_64)
-- | --
Revision | 6e36b77363ef3febbe792af680fa1367993ddcf0-refs/branch-heads/5414@{#709}
OS | macOS Version 11.7.2 (Build 20G1020)

Followed the steps to reproduce as filed.

#### Confirmed the text throughout the onboarding screens was legible for both `Dark` and `Light` modes

### `Dark`

`Import Settings` | `Select profile to import ` | `Setup complete`
------------------|---------------------------|-------------------
<img width="1312" alt="Screen Shot 2022-12-28 at 10 35 07 AM" src="https://user-images.githubusercontent.com/387249/209858922-2a4e98e4-c908-4cce-8d2b-355359e3949a.png"> | <img width="1312" alt="Screen Shot 2022-12-28 at 10 42 15 AM" src="https://user-images.githubusercontent.com/387249/209858943-10035da0-8c8c-4882-aa69-7fb8f0446170.png"> | <img width="1312" alt="Screen Shot 2022-12-28 at 10 52 34 AM" src="https://user-images.githubusercontent.com/387249/209859130-d602afbb-dc26-4d9d-b2a3-33ea64e8583c.png">





### `Light`

`Import Settings` | `Select profile to import ` | `Setup complete`
------------------|---------------------------|-------------------
<img width="1312" alt="Screen Shot 2022-12-28 at 10 42 53 AM" src="https://user-images.githubusercontent.com/387249/209858767-ec6b604e-d404-4698-a715-e6f4585ed730.png"> | <img width="1312" alt="Screen Shot 2022-12-28 at 10 42 35 AM" src="https://user-images.githubusercontent.com/387249/209858818-05fac367-6983-4050-84ca-4916708ac00b.png"> | <img width="1312" alt="Screen Shot 2022-12-28 at 10 45 31 AM" src="https://user-images.githubusercontent.com/387249/209858862-e73115e6-4219-47bf-b0b4-d62cf185b3ad.png">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED`
```
Brave | 1.47.149 Chromium: 109.0.5414.46 (Official Build) beta (64-bit)
-- | --
Revision | 6e36b77363ef3febbe792af680fa1367993ddcf0-refs/branch-heads/5414@{#709}
OS | Windows 11 Version 22H2 (Build 22621.963)
```
Verified from STR from the description - https://github.com/brave/brave-browser/issues/27105#issue-1472106069

#### Confirmed the text throughout the onboarding screens was legible for both Dark and Light modes

Dark
------

ex1|ex2|ex3
-----|----|-----
<img width="956" alt="image" src="https://user-images.githubusercontent.com/98358127/209873690-7c9d62e0-a123-49b9-b2b4-d07f24de0930.png">|<image width="900" alt="mage" src="https://user-images.githubusercontent.com/98358127/209873708-24689103-3b43-4fdc-9e2c-0c361c4e4c94.png">|<image width="900" alt="image" src="https://user-images.githubusercontent.com/98358127/209873736-0dc9db2c-2375-4b61-8023-98fa990a9399.png">

Light: 
------

ex1|ex2|ex3
-----|----|-----
<image width="900" alt="image" src="https://user-images.githubusercontent.com/98358127/209873839-d4090160-0ab3-4bc5-a538-b0371c0dd7c2.png">|<image width="900" alt="image" src="https://user-images.githubusercontent.com/98358127/209873892-33ec7bae-ae5d-4df3-bb4f-de847cfef9a1.png">|<image width="900" alt="image" src="https://user-images.githubusercontent.com/98358127/209873909-f7ce7e89-416d-4ec7-a9a2-0fbc9e6d9d66.png">
