### ISSUE TITLE
OS VPN entry goes reconnect by itself when wifi is re-enabled

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#27113]
## Steps to Reproduce

   1. Connect vpn with vpn panel
   2. Disable wifi and wait till vpn goes disconnected
   3. Try reconnect with vpn panel
   4. Got connect failed page from vpn panel
   5. Enable wifi
   6. Check os vpn entry is not reconnected by itself
   7. Do retry with vpn panel
   8. Check connect success

## Actual result:

At step 6, os vpn entry goes `connecting` state by itself

## Expected result:
At step 6, os vpn entry shouldn't have any state

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @GeetaSarvadnya

**Comment by kjozwiak** [comment]
The above will require `1.46.141` or higher for `1.46.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS

```
Brave | 1.46.141 Chromium: 108.0.5359.99 (Official Build) (64-bit)
-- | --
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | Windows 10 Version 21H2 (Build 19044.2251)

```
