### ISSUE TITLE
Add custom token prompt is shown even when unchecking the NFT from token registry

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#27114]
## Description 
Add custom token prompt is shown even when unchecking the NFT from token registry

## Steps to reproduce 

   1. Go to add custom token
   2. Search for Crypto Kitty
   3. Click on the checkbox, shows add token form
   4. Uncheck the token checkbox, form is shown again

## Actual result 
https://user-images.githubusercontent.com/17010094/205237116-00452e8e-8e6a-4fb9-bd85-2d14785576eb.mp4

## Expected result
Should not show add form when token is unchecked 

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 12
   
## Brave version
1.48.20

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @wchen342

**Comment by kjozwiak** [comment]
The above requires `1.47.122` or higher for `1.47.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.47.125 x64 beta build
- Verified steps from issue description & [brave/brave-core#16200](https://github.com/brave/brave-core/pull/16200)
- Verified add token form is only shown when the token is clicked
- Verified the token doesn't add a check mark and only brings up the modal every time the token is clicked
- Encountered [#27302](https://github.com/brave/brave-browser/issues/27302)

Oppo Reno 5 (Android 12) | Lenovo Tab (Android 12)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/207056794-c39f1246-062d-49b3-83d2-a8ad141ea9d0.mp4> | <video src=https://user-images.githubusercontent.com/17010094/207056826-0698e0c2-1265-4eeb-85ee-61449ae907c8.mp4>
