### ISSUE TITLE
Update UD, ENS, SNS interstitials text for domain resolve

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#27110]
Per https://github.com/brave/security/issues/1099#issuecomment-1334698536

Current wording for interstitials is:

UD:
`Brave will be using Infura to issue Ethereum JSON-RPC calls to the smart contract from Unstoppable Domains to resolve .crypto (and also .x, .coin, .nft, .dao, .wallet, .blockchain, .bitcoin, .zil) domain name lookup requests. If you enable this, Infura will see those specific domains that you're trying to visit but they will not be able to see other domains. See Infura's <ph name="BEGIN_INFURA_TOU_LINK">&lt;a target="_blank" href="$1"&gt;</ph>terms of use<ph name="END_INFURA_TOU_LINK">&lt;/a&gt;</ph> and <ph name="BEGIN_INFURA_PRIVACY_LINK">&lt;a target="_blank" href="$2"&gt;</ph>privacy policy<ph name="END_INFURA_PRIVACY_LINK">&lt;/a&gt;</ph>.`

ENS:
`Brave will be using Infura to issue Ethereum JSON-RPC calls to the smart contract from Ethereum Name Service to resolve .eth domain name lookup requests. If you enable this, Infura will see the .eth domain that you're trying to visit but they will not be able to see other domains. See Infura's <ph name="BEGIN_INFURA_TOU_LINK">&lt;a target="_blank" href="$1"&gt;</ph>terms of use<ph name="END_INFURA_TOU_LINK">&lt;/a&gt;</ph> and <ph name="BEGIN_INFURA_PRIVACY_LINK">&lt;a target="_blank" href="$2"&gt;</ph>privacy policy<ph name="END_INFURA_PRIVACY_LINK">&lt;/a&gt;</ph>.`

ENS L2:
`Brave will be using offchain gateways to resolve .eth domain name lookup requests. If you enable this, third party gateways will see the .eth domain that you're trying to visit but they will not be able to see other domains. <ph name="BEGIN_BRAVE_LEARN_MORE_LINK">&lt;a target="_blank" href="$1"&gt;</ph>Learn more<ph name="END_BRAVE_LEARN_MORE_LINK">&lt;/a&gt;</ph>.`

SNS:
`Brave will be using Coinbase Cloud to issue Solana JSON-RPC calls to the program from Solana Name Service to resolve .sol domain name lookup requests. If you enable this, Coinbase Cloud will see the .sol domain that you're trying to visit but they will not be able to see other domains. See Coinbase Cloud's <ph name="BEGIN_COINBASE_TOU_LINK">&lt;a target="_blank" href="$1"&gt;</ph>terms of use<ph name="END_COINBASE_TOU_LINK">&lt;/a&gt;</ph> and <ph name="BEGIN_COINBASE_PRIVACY_LINK">&lt;a target="_blank" href="$2"&gt;</ph>privacy policy<ph name="END_COINBASE_PRIVACY_LINK">&lt;/a&gt;</ph>.`

**Comment by supermassive** [comment]
@ShivanKaul, please adjust wording

**Comment by ShivanKaul** [comment]
WIP:

UD:
`Brave will be using Infura to issue Ethereum JSON-RPC calls to the smart contract from Unstoppable Domains to resolve .crypto (and also .x, .coin, .nft, .dao, .wallet, .blockchain, .bitcoin, .zil) domain name lookup requests. If you enable this, Infura will see those specific domains that you're trying to visit but they will not be able to see other domains. See Infura's <ph name="BEGIN_INFURA_TOU_LINK">&lt;a target="_blank" href="$1"&gt;</ph>terms of use<ph name="END_INFURA_TOU_LINK">&lt;/a&gt;</ph> and <ph name="BEGIN_INFURA_PRIVACY_LINK">&lt;a target="_blank" href="$2"&gt;</ph>privacy policy<ph name="END_INFURA_PRIVACY_LINK">&lt;/a&gt;</ph>.`

ENS:
`Brave will be using Infura to issue Ethereum JSON-RPC calls to the smart contract from Ethereum Name Service to resolve .eth domain name lookup requests. If you enable this, Infura will see the .eth domain that you're trying to visit but they will not be able to see other domains. See Infura's <ph name="BEGIN_INFURA_TOU_LINK">&lt;a target="_blank" href="$1"&gt;</ph>terms of use<ph name="END_INFURA_TOU_LINK">&lt;/a&gt;</ph> and <ph name="BEGIN_INFURA_PRIVACY_LINK">&lt;a target="_blank" href="$2"&gt;</ph>privacy policy<ph name="END_INFURA_PRIVACY_LINK">&lt;/a&gt;</ph>.`

ENS L2:
`Brave will be using offchain gateways to resolve .eth domain name lookup requests. If you enable this, third party gateways will see the .eth domain that you're trying to visit but they will not be able to see other domains. <ph name="BEGIN_BRAVE_LEARN_MORE_LINK">&lt;a target="_blank" href="$1"&gt;</ph>Learn more<ph name="END_BRAVE_LEARN_MORE_LINK">&lt;/a&gt;</ph>.`

SNS:
`Brave will be using Coinbase Cloud to resolve .sol domain names. If you enable this, Coinbase will see the .sol domain that you're trying to visit, but nothing else. See Coinbase Cloud's <ph name="BEGIN_COINBASE_TOU_LINK">&lt;a target="_blank" href="$1"&gt;</ph>terms of use<ph name="END_COINBASE_TOU_LINK">&lt;/a&gt;</ph> and <ph name="BEGIN_COINBASE_PRIVACY_LINK">&lt;a target="_blank" href="$2"&gt;</ph>privacy policy<ph name="END_COINBASE_PRIVACY_LINK">&lt;/a&gt;</ph>.`

**Comment by ShivanKaul** [comment]
@PrivacyMatters can you take a look here as well

**Comment by ShivanKaul** [comment]
@diracdeltas if you could take a quick look as well, given that you'd reviewed some of the original Web3 domain resolution PRs.

**Comment by ShivanKaul** [comment]
@supermassive this should be good to ship!

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.48.132 Chromium: 109.0.5414.87 (Official Build) beta (64-bit) 
-- | --
Revision | `2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}`
OS | Linux

- Verified steps from [#27110 (comment)](https://github.com/brave/brave-browser/issues/27110#issuecomment-1335696443)
- Verified UD/ENS/SNS interstitial text is updated before resolving domains

UD | ENS | ENS L2 | SNS
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/214214945-1e18de2d-7812-4fd6-9375-739a68070bf3.png) | ![image](https://user-images.githubusercontent.com/17010094/214214991-ec843e66-8455-4fb5-977e-09ddbcade587.png) | ![image](https://user-images.githubusercontent.com/17010094/214215138-52850309-0037-4374-8811-da0ea62f7f1c.png) | ![image](https://user-images.githubusercontent.com/17010094/214215157-ef91fe01-2db1-4fee-b0c7-edee5baa243f.png)

---------------------

Verification passed on 

Brave | 1.48.132 Chromium: 109.0.5414.87 (Official Build) beta (64-bit)
-- | --
Revision | `2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [#27110 (comment)](https://github.com/brave/brave-browser/issues/27110#issuecomment-1335696443)
- Verified UD/ENS/SNS interstitial text is updated before resolving domains

UD | ENS | ENS L2 | SNS
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/214214731-3b2f964f-1959-457d-ab86-72f8c61bac29.png) | ![image](https://user-images.githubusercontent.com/17010094/214214768-816dd0a6-0085-4952-bdf8-b96ae3337baf.png) | ![image](https://user-images.githubusercontent.com/17010094/214214797-fea3014c-e41b-4314-a887-2eb6a0975bd9.png) | ![image](https://user-images.githubusercontent.com/17010094/214214821-3730ef04-c6e0-4171-b3ae-7ac2c820a383.png)

---------------------

Verification passed on 

Brave | 1.48.132 Chromium: 109.0.5414.87 (Official Build) beta (arm64)
-- | --
Revision | `2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [#27110 (comment)](https://github.com/brave/brave-browser/issues/27110#issuecomment-1335696443)
- Verified UD/ENS/SNS interstitial text is updated before resolving domains

UD | ENS | ENS L2 | SNS
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/214214120-eb1452c3-5f81-4a38-8ae1-81ad64b5ff7c.png) | ![image](https://user-images.githubusercontent.com/17010094/214214103-023c9476-ff1d-4a6f-a521-eaf1d0c47f2b.png) | ![image](https://user-images.githubusercontent.com/17010094/214214127-1d4448f2-a858-4df7-804e-50e41c5d9c17.png) | ![image](https://user-images.githubusercontent.com/17010094/214214124-c08b974b-b354-4a93-a714-cc31f92ffe8a.png)
