### ISSUE TITLE
Diagnostic reports for crashes and freezes should be default checked

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#27126]
## Description 

For the new onboarding screen via brave://welcome, the final screen to Help Improve Brave should have the diagnostic report for crashes and freezes default checked.

## Steps to Reproduce

   1. Use Brave 147.108 or higher in beta or 148.x in nightly.
   2. Fresh install or visit brave://welcome 
   3. Notice final screen during onboarding.

## Actual result:

<img width="856" alt="Screenshot 2022-12-02 at 10 08 31 AM" src="https://user-images.githubusercontent.com/5951041/205358458-868e6527-82fe-45f7-a71d-d5f87a9798d6.png">

## Expected result:
<img width="851" alt="Screenshot 2022-12-02 at 10 08 43 AM" src="https://user-images.githubusercontent.com/5951041/205358475-5a778930-d505-47c9-8950-d52073a20f19.png">

## Reproduces how often: 

Easily

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

Related: https://github.com/brave/brave-core/pull/13405 and https://github.com/brave/security/issues/791#issuecomment-1081088795

**Comment by PrivacyMatters** [comment]
Is there a reason for change in style and language of the notices? That were agreed in https://github.com/brave/security/issues/791  I agree with the pre-ticked defaults **but** I note:

- we have changed from 'Help make Brave Better' to "Fine tuning the product. Protecting your privacy every day."  **Why was the previously agreed wording changed?**  The proposed wording somehow comes across as the end user being the product given that the data relates to them and their devices
- the word 'anonymous' has been removed from the send diagnostics reports. Is it because diagnostics _may_ contain personal data - as we say in this support [article](https://support.brave.com/hc/en-us/articles/360017905872-How-do-I-enable-or-disable-automatic-crash-reporting-) In contrast to the support article we also say "This report contains technical information about your computer system and the event causing the problem. The data can’t be used to identify you."  (cc @pes10k for comment?)

On the matter of crash reports I think it would be good to agree consistent wording

**Comment by PrivacyMatters** [comment]
@nullhook I'm not sure why this has been closed.  I'm still waiting for a response to https://github.com/brave/brave-browser/issues/27126#issuecomment-1337058893

**Comment by rebron** [comment]
@PrivacyMatters Apologies. I replied here https://github.com/brave/security/issues/1132#issuecomment-1344618451

This one is closed because https://github.com/brave/security/issues/1132 is closed. Looks like we'll need a follow-up to add the Learn more links for each checkbox.

**Comment by kjozwiak** [comment]
The above requires `1.47.131` or higher for `1.47.x` verification 👍

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.47.132 Chromium: 108.0.5359.128 (Official Build) beta (64-bit)
-- | --
Revision | 1cd27afdb8e5d057070c0961e04c490d2aca1aa0-refs/branch-heads/5359@{#1185}
OS | Ubuntu 18.04 LTS


Verified crash reporting is enabled by default on beta
![image](https://user-images.githubusercontent.com/34715963/208329827-9c1b31bb-8575-40c2-afb5-1a3d06dc93c0.png)

Verified `Automatically send diagnostic reports` is enabled
![image](https://user-images.githubusercontent.com/34715963/208330384-b55bf26d-b937-4a3f-8719-3c255d6d8f37.png)

Verified the crash report is automatically sent
![image](https://user-images.githubusercontent.com/34715963/208333192-94f65d2a-a824-4a84-a70e-3ac80cfa7d16.png)

**Comment by btlechowski** [comment]
Added `QA/Test-All-Platforms` since generating crashes works differently on different platforms

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.47.135 Chromium: 108.0.5359.128 (Official Build) beta (x86_64)
-- | --
Revision | 1cd27afdb8e5d057070c0961e04c490d2aca1aa0-refs/branch-heads/5359@{#1185}
OS | macOS Version 11.7.2 (Build 20G1020)

### Steps:
1. installed `1.47.135`
2. launched Brave
3. clicked `Skip` on `brave://welcome` 1st page
4. clicked `Skip` on `brave://welcome` 2nd page
5. examined the 3rd page of `brave://welcome`
6. confirmed `Send diagnostic reports if you experience a crash or freeze` is checked by default
7. opened `brave://settings/privacy`
8. confirmed `Automatically send diagnostic reports` is checked by default
9. loaded `brave://crash` to generate a crash incident
10. opened `brave://crashes`
11. confirmed crash report was sent by default


`brave://welcome`, page 3 | `brave://settings/privacy` | `brave://crash` | `brave://crashes`
---|---|---|---
<img width="1312" alt="Screen Shot 2022-12-19 at 6 09 17 PM" src="https://user-images.githubusercontent.com/387249/208564989-6dddbcb5-bdff-47a7-b0f8-689828f4b67c.png"> | <img width="1312" alt="Screen Shot 2022-12-19 at 6 09 38 PM" src="https://user-images.githubusercontent.com/387249/208564997-9a61436c-44b1-49e1-956e-27171cb1e5de.png"> | <img width="1312" alt="Screen Shot 2022-12-19 at 6 09 56 PM" src="https://user-images.githubusercontent.com/387249/208564998-d895a585-50bb-4616-b756-f689020b46ee.png"> | <img width="1312" alt="Screen Shot 2022-12-19 at 6 10 03 PM" src="https://user-images.githubusercontent.com/387249/208565000-cef0aef7-8953-4d7d-b960-617ad03ed448.png">

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using 
```
Brave | 1.47.136 Chromium: 108.0.5359.128 (Official Build) beta (64-bit)
-- | --
Revision | 1cd27afdb8e5d057070c0961e04c490d2aca1aa0-refs/branch-heads/5359@{#1185}
OS | Windows 11 Version 21H2 (Build 22000.1335)
```

Case  1 : `Automatically send diagnostic reports` is checked by default

1. install 1.47.136
2. launch Brave
3. click `Set Brave as default Browser` on brave://welcome`
4. click `Skip` on brave://welcome` on `Import Settings` screen
5. confirmed `Send diagnostic reports if you experience a crash or freeze` is checked by default
6. click the link `brave://settings/privacy below `Finish` button
7. go to the `brave://settings/privacy` tab
8. confirmed `Automatically send diagnostic reports` is enabled default
9. loaded brave://crash to generate a crash incident
10. confirmed crash report was sent by default

step 3|step 5|step 7|step 9|step 10
------|-------|-----|-------|------
<img width="465" alt="image" src="https://user-images.githubusercontent.com/98358127/208788064-7981560a-38b1-447b-95b8-84c9b2e59ac9.png">|<img width="460" alt="image" src="https://user-images.githubusercontent.com/98358127/208788122-f5a0d8a3-2be3-485e-b2d5-b96bc053503b.png">|<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/208788146-d8b887fe-91cf-46b0-bbbf-3931e367e0c3.png">|<img width="460" alt="image" src="https://user-images.githubusercontent.com/98358127/208788684-e8ae4142-946c-4a7b-b240-04db0296ec1c.png">|<img width="462" alt="image" src="https://user-images.githubusercontent.com/98358127/208790589-bb29dc12-2c0e-477a-955b-4940a14db24b.png">

Case  2 : Uncheck `Automatically send diagnostic reports`  option in the new UI 

1. new profile
2. launch Brave
3. click `Set Brave as default Browser` on brave://welcome`
4. click `Skip` on brave://welcome` on `Import Settings` screen
5. uncheck `Send diagnostic reports if you experience a crash or freeze` entry
6. click `Finish` button
7. go to the `brave://settings/privacy` tab
8. confirmed `Automatically send diagnostic reports` is disabled
9. loaded brave://crash to generate a crash incident
10. confirmed `Crash reporting is disabled` message shown

step 3|step 4|step 5|step 8|step 10
-----|------|-------|------|-----
<img width="465" alt="image" src="https://user-images.githubusercontent.com/98358127/208788064-7981560a-38b1-447b-95b8-84c9b2e59ac9.png">|<img width="460" alt="image" src="https://user-images.githubusercontent.com/98358127/208788122-f5a0d8a3-2be3-485e-b2d5-b96bc053503b.png">|<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/208790836-1dabdbe6-53ba-43c4-ad76-67a15f8dc76c.png">|<img width="454" alt="image" src="https://user-images.githubusercontent.com/98358127/208790890-fd0db0cd-4b6d-4789-b22e-a18469912522.png">|<img width="461" alt="image" src="https://user-images.githubusercontent.com/98358127/208791127-8a324dd7-6734-4653-8b58-697bba5a4d11.png">

1. new profile 
2. launched Brave
3. clicked Skip on `brave://welcome` page 
4. clicked Skip on  `Import Settings` page 
5. confirmed `Send diagnostic reports if you experience a crash or freeze` is checked by default
6. opened brave://settings/privacy
7. disable `Automatically send diagnostic reports` and relaunch Brave
8. loaded brave://crash to generate a crash incident
9. opened brave://crashes
10. confirmed crash report was sent by default

ex|ex|ex|ex
---|----|---|---
<img width="464" alt="image" src="https://user-images.githubusercontent.com/98358127/208792618-08056e9d-bf9f-4356-a041-bfebf8397cd5.png">|<img width="462" alt="image" src="https://user-images.githubusercontent.com/98358127/208792665-178eaefb-7b90-4e5b-888c-28204e238a32.png">|<img width="466" alt="image" src="https://user-images.githubusercontent.com/98358127/208792686-5a4f9e2b-76ad-4f07-b9da-7b9a76b9014b.png">|<img width="455" alt="image" src="https://user-images.githubusercontent.com/98358127/208792727-49ec12b2-c23c-4a52-b093-352ceeb4ce9d.png">
