### ISSUE TITLE
[Android] Enforce checking for `ActivityNotFoundException` when calling `getBraveActivity`

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#27121]
## Description 
We should enforce checking for `ActivityNotFoundException` when calling `getBraveActivity` instead of returning `null` for better handling this case.

## Steps to reproduce 

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Marking as `QA/No` after discussion [here](https://bravesoftware.slack.com/archives/C03MMJ4CHEZ/p1680512487527439?thread_ts=1680511920.006979&cid=C03MMJ4CHEZ0). This will be covered as part of the Rewards test done in Manual Pass

cc: @Uni-verse @kjozwiak
