### ISSUE TITLE
Role of sites reversed in brave://settings/content wording

### ISSUE THREAD

**Issue by jidanni** [brave/brave-browser#27125]
brave://settings/content says
>Shields status
> > Sites can block trackers, ads, and fingerprinting using Shields

But the sites are the block-ee, not the block-er.

**Comment by rebron** [comment]
<img width="694" alt="Screenshot 2022-12-02 at 10 04 18 AM" src="https://user-images.githubusercontent.com/5951041/205357146-0a5c4025-5bdc-4c7b-be80-9dceb38dec93.png">

**Comment by bsclifton** [comment]
Closing as fixed with https://github.com/brave/brave-core/pull/21862 😄

**Comment by bsclifton** [comment]
Issue is a duplicate of https://github.com/brave/brave-browser/issues/35765
