### ISSUE TITLE
Use new spelling for Turkey, "Türkiye", in Rewards geo declaration dropdown

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#27127]
## Description

Update to reflect the ISO spelling for Türkiye (formerly Turkey)
https://en.wikipedia.org/wiki/ISO_3166-2:TR. 

![image](https://user-images.githubusercontent.com/11497541/205361053-4d915648-2386-46c1-85c9-ff0c6a38de09.png)

cc: @iambrianfung

**Comment by mkarolin** [comment]
As @zenparsing mentioned we get the country names from ICU. The latest version of ICU (version 72, and underlying CLDR version 42) doesn't contain this change yet, but it seem like the next CLDR version 43 will (see https://cldr.unicode.org/index/downloads/cldr-42#h.x23yntvhn0oj). Chromium is currently on ICU v. 69 (updated in March 2021),
