### ISSUE TITLE
Advanced Solana NFT gallery support (frontend desktop changes)

### ISSUE THREAD

**Issue by nvonpentz** [brave/brave-browser#27129]
This is issue is for tracking the frontend changes required for Solana NFT gallery support.
Backend issue - https://github.com/brave/brave-browser/issues/21858.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.48.151 Chromium: 109.0.5414.119 (Official Build) beta (64-bit)
-- | --
Revision | `772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#16308](https://github.com/brave/brave-core/pull/16308)
- Verified able to view Solana NFT details view
- Verified clicking on Token ID loads the blockexplorer page and loads the NFT details

https://user-images.githubusercontent.com/17010094/216265112-ff9a5149-67ec-49a4-bd70-6b87c92df8e2.mp4

**Comment by DevCon1100** [comment]
Access
