### ISSUE TITLE
Sites incorrectly listed as having/not having custom shield settings

### ISSUE THREAD

**Issue by TheCodesee** [brave/brave-browser#27148]
## Description 
brave://settings/content/braveShields is supposed to show sites that have customised shield settings. However, sites that don't have customised shield settings are incorrectly shown as having such (issue 1), and sites that do have customised shield settings aren't listed as having such (issue 2).

## Steps to Reproduce

To reproduce issue 1:

   1. Visit brave.com
   2. Turn off shields for the site (using toggle button)
   3. Turn on shields for the site (using toggle button)
   4. Visit brave://settings/content/braveShields

To reproduce issue 2:

   1. (if reproduced issue above) Remove brave.com from brave://settings/content/braveShields
   2. Visit brave.com
   3. Customise shields for the site
   4. Visit brave://settings/content/braveShields

## Actual result:

**Issue 1:**
![Capture](https://user-images.githubusercontent.com/115008744/205463236-89bd9943-79c2-4337-afad-5eeed5b1fc88.PNG)

**Issue 2:**
![Capture](https://user-images.githubusercontent.com/115008744/205463263-2cc5a3e8-21f7-4bb1-9d1b-e22095215019.PNG)

## Expected result:

**Issue 1:**
![Capture](https://user-images.githubusercontent.com/115008744/205463263-2cc5a3e8-21f7-4bb1-9d1b-e22095215019.PNG)

**Issue 2:**
![Capture](https://user-images.githubusercontent.com/115008744/205463236-89bd9943-79c2-4337-afad-5eeed5b1fc88.PNG)

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

Brave | 1.46.134 Chromium: 108.0.5359.94 (Official Build) (64-bit)
Revision | 713576b895246504ccc6b92c2fb8ce2d60194074-refs/branch-heads/5359_71@{#3}
OS | Windows 10 Version 22H2 (Build 19045.2251)

## Version/Channel Information:
Reproduced on current release.

**Comment by rebron** [comment]
Sounds like the fix is to check default setting and not show in Shields up section if returning to default state.

**Comment by rebron** [comment]
cc: @bradleyrichter

**Comment by spylogsster** [comment]
@TheCodesee sorry for the delay, customizable Shields options (https, fingerprints and others) managed by own options and can be available only when the main Shields option is enabled. The enabled state is the default state for the shields and we should not show this in the exceptions list unless it is required, policy or other cases for example.

**Comment by spylogsster** [comment]
yep, the`Shields up` list is an exception list from the default state. In order to add it to the exceptions _up_ It could be disabled on some domain, but enabled for subdomains

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.48.125 Chromium: 109.0.5414.87 (Official Build) beta (64-bit)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | Windows 11 Version 21H2 (Build 22000.1455)
```

1. Install 1.48.125
2. launch Brave
3. visit https://brave.com
4. toggle `Off `Shields` in the Shields panel
5. opened `brave://settings/content/braveShields`
6. brave.com is added Shields Down as expected
7. toggle `On` `Shields` in the Shields panel 
8. open `brave://settings/content/braveShields`

#### Confirmed brave.com is not added to the page in `Shields Up` section

step 4|step 6|step 7|result
-----|-----|--------|--------
<img width="478" alt="image" src="https://user-images.githubusercontent.com/98358127/212386894-a3bde61d-1e58-4d61-9a22-22bd9431bb16.png">|<img width="509" alt="image" src="https://user-images.githubusercontent.com/98358127/212389630-0e381068-4c63-4fa4-a4a5-af0a65b812ad.png">|<img width="506" alt="image" src="https://user-images.githubusercontent.com/98358127/212387333-b4861823-afd1-4006-99d5-9df570471efd.png">|<img width="511" alt="image" src="https://user-images.githubusercontent.com/98358127/212387405-54ce7a1e-f145-474b-941b-c1d245ec15e3.png">

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.48.125 Chromium: 109.0.5414.87 (Official Build) beta (x86_64)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | macOS Version 11.7.2 (Build 20G1020)

### Steps:

1. installed `1.48.125`
2. launched Brave
3. visited `https://brave.com/`
4. toggled `Off` Shields in the Shields panel
5. opened `brave://settings/content/braveShields`
6. confirmed `brave.com` is added to `Shields Down` section as expected
7. toggled `On` Shields in the Shields panel
8. opened brave://settings/content/braveShields

#### Confirmed `brave.com` is not added to the page in `Shields Up` section


step 4 | step 6 | step 7 | result
-------|--------|-------|------
<img width="1116" alt="Screen Shot 2023-01-13 at 10 33 26 AM" src="https://user-images.githubusercontent.com/387249/212394219-885be4a4-7005-4095-a87c-f1f699aedbca.png"> | <img width="1154" alt="Screen Shot 2023-01-13 at 10 33 51 AM" src="https://user-images.githubusercontent.com/387249/212394224-3010e654-bca1-4da2-809a-d7cd2d749df6.png"> | <img width="1154" alt="Screen Shot 2023-01-13 at 10 34 15 AM" src="https://user-images.githubusercontent.com/387249/212394226-5d4d58e5-819b-4b5c-8095-4663c7773754.png"> | <img width="1154" alt="Screen Shot 2023-01-13 at 10 34 21 AM" src="https://user-images.githubusercontent.com/387249/212394227-41dec6a2-14b1-4ddb-86e1-36e8ac13e511.png">

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using 
```
Brave | 1.48.137 Chromium: 109.0.5414.87 (Official Build) beta (64-bit)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | Linux
```
1. Install 1.48.137
2. launch Brave
3. open a new tab
4. visit https://brave.com
5. toggle `Off` `Shields` in the Shields panel
6. opened `brave://settings/content/braveShields`
7. confirmed brave.com is added to `Shields Down` section as expected
8. return to brave.com tab and toggle `On` `Shields` in the Shields panel 
9. open `brave://settings/content/braveShields`

#### Confirmed `brave.com` is not added to the page in `Shields Up` section

step 5|step 7|step 8|result
-----|-----|--------|--------
<img width="478" alt="image" src="https://user-images.githubusercontent.com/98358127/214377228-fbe0da16-1a87-4080-b593-eb8289b774c6.png">|<img width="478" alt="image" src="https://user-images.githubusercontent.com/98358127/214377387-c82c5a7d-c50e-4198-baef-a01705989192.png">|<img width="478" alt="image" src="https://user-images.githubusercontent.com/98358127/214377708-40049c11-d4b9-423c-a1ea-9b80bba82bef.png">|<img width="478" alt="image" src="https://user-images.githubusercontent.com/98358127/214377831-aba75a17-9b80-4e14-9499-8bdd75bc4913.png">
