### ISSUE TITLE
Can't install extensions using registry

### ISSUE THREAD

**Issue by bckelley** [brave/brave-browser#27149]
## Description 

trying to build a powershell script to install extensions using registry keys

## Steps to Reproduce

Tried adding the keys to:
"HKLM:\SOFTWARE\Policies\Google\Chrome\ExtensionInstallForcelist"
"HKLM:\SOFTWARE\Polcies\BraveSoftware\Brave-Browser\Extensions"
"HKLM:\SOFTWARE\BraveSoftware\Brave-Browser\Extensions"
"HKLM:\SOFTWARE\BraveSoftware\Brave\Extensions"

## Actual result:

Seen where people have added to:
"HKLM:\SOFTWARE\Policies\Google\Chrome\ExtensionInstallForcelist"

and were able to install it just fine

## Expected result:

figured brave would use something like 
"HKLM:\SOFTWARE\Policies\Google\Chrome\ExtensionInstallForcelist"
"HKLM:\SOFTWARE\Polcies\BraveSoftware\Brave-Browser\Extensions"

one of these to install extensions

## Reproduces how often: 

never have gotten to work

## Brave version (brave://version info)

Version 1.45.133 Chromium: 107.0.5304.141 (Official Build) (64-bit)

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      19043  0       

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

No idea only tried current stable

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

Not sure that would matter

**Comment by rebron** [comment]
cc: @bsclifton

**Comment by bckelley** [comment]
Any updates on this?

**Comment by bsclifton** [comment]
@bckelley yes - hi. You should be able to do this using our group policy templates:
https://support.brave.com/hc/en-us/articles/360039248271-Group-Policy

You can download there - included is a file called `windows\examples\brave.reg`. If you open that in Notepad, you can find the values for `ExtensionInstallForcelist` with an example

Basically, I think you just had the path wrong. It should be:
`HKEY_LOCAL_MACHINE\Software\Policies\BraveSoftware\Brave\ExtensionInstallForcelist`

And then for each entry, make a string value with name being a number (starting at 1; increment with each) and then value being extension ID.

**Comment by bckelley** [comment]
yea it doesn't work

**Comment by Perduarbo** [comment]
Try this location: HKEY_CURRENT_USER\Software\Policies\BraveSoftware\Brave\ExtensionInstallForcelist

**Comment by JaneX8** [comment]
> [@bckelley](https://github.com/bckelley) yes - hi. You should be able to do this using our group policy templates: https://support.brave.com/hc/en-us/articles/360039248271-Group-Policy
> 
> You can download there - included is a file called `windows\examples\brave.reg`. If you open that in Notepad, you can find the values for `ExtensionInstallForcelist` with an example. This file has example values for every possible Chromium group policy
> 
> Basically, I think you just had the path wrong. It should be: `HKEY_LOCAL_MACHINE\Software\Policies\BraveSoftware\Brave\ExtensionInstallForcelist`
> 
> And then for each entry, make a string value with name being a number (starting at 1; increment with each) and then value being extension ID.

This works beautifully. Thank you.
