### ISSUE TITLE
Switching tabs while a dapp transaction is pending causes an error in the transaction

### ISSUE THREAD

**Issue by bcxbb** [brave/brave-browser#27151]
## Description 
Switching tabs while a dapp transaction is pending causes an error in the transaction

## Steps to Reproduce
   1. Initiate a transaction on dapp using Brave wallet
   2. Switch tabs tabs
   3. Error appears - 32002 "the tab is not active" or 32063 Error processing transaction
  
## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Brave: 1.45.133 Chromium: 107.0.5304.141

## Miscellaneous Information:
Happening on polygon testnet. Have not tried mainnets.

**Comment by josheleonard** [comment]
Was able to complete a transaction on Polygon Amoy using https://metamask.github.io/test-dapp/, even when switching tabs before confirming
