### ISSUE TITLE
Remove YT images for unverified publishers in Tip table on Brave Rewards

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#2715]
YT icons for unverified publishers are showing up in tip table.

cc @diracdeltas @NejcZdovc @rebron

**Comment by kirkins** [comment]
They sometimes show, sometimes not https://github.com/brave/brave-browser/issues/2716

**Comment by diracdeltas** [comment]
also Twitch? (any non-site icons)

**Comment by NejcZdovc** [comment]
@diracdeltas we don't have twitch support yet

**Comment by kirkins** [comment]
Here is the example where the non-verified message doesn't show but photo is still generic as opposed to example above.

![](https://i.imgur.com/Cl2oouj.jpg)

**Comment by kjozwiak** [comment]
Verified using the following platforms:

* Ubuntu 18.04 x64 - **PASSED*
* Windows 10 x64 - waiting on builds
* macOS 10.14.2 x64 - waiting on builds

Builds being used:

Brave | 0.58.18 Chromium: 71.0.3578.98 (Official Build) (64-bit)
--- | ---
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}

Example of verified vs unverified using Ubuntu 18.04 x64:

<img width="643" alt="screen shot 2018-12-23 at 4 30 04 pm" src="https://user-images.githubusercontent.com/2602313/50387660-38f42780-06d0-11e9-9057-b2466910d671.png">
