### ISSUE TITLE
No way to see individual cookies stored per-website in brave://settings

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#27150]
## Description 

You can't see individual cookies in brave://settings/cookies any more on Nightly. This must be a Chromium change, I see the same behaviour on Chrome Stable. 

## Steps to Reproduce

   1. Go to brave://settings/cookies
   2. There is no `See all cookies and site data`
   3. Click on `See all site data and permissions` instead
   4. You're redirected to brave://settings/content/all, but clicking on any website in that list sends you to something like `brave://settings/content/siteDetails?site=https%3A%2F%2Fgithub.com%2F`, where you can modify permissions but can't see local stored data in detail. 

## Actual result:

![image](https://user-images.githubusercontent.com/5284154/205463966-15972ca7-e735-4992-9923-96f32b90461d.png)

## Expected result:
![image](https://user-images.githubusercontent.com/5284154/205463978-e2ba8af9-3e56-4c0f-9562-ad95a83ef231.png)

and then clicking on Twitter gives you

![image](https://user-images.githubusercontent.com/5284154/205463999-85def0c4-f4cd-49c8-8c21-9dbd07a56221.png)

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Nightly only `1.48.5 Chromium: 108.0.5359.48 (Official Build) nightly (arm64) `

**Comment by ShivanKaul** [comment]
This is a UX consideration, but ideally we would bring back `brave://settings/cookies/detail?site=xyz.com` page which could be navigated to from the brave://settings/content/siteDetails?site=xyz.com page.

**Comment by ShivanKaul** [comment]
cc @rebron @mkarolin

**Comment by NipLars** [comment]
It is there in brave://settings/content/all which I use as startup page even.
But change of structure completely.

**Comment by diracdeltas** [comment]
as a side note, if this is the menu referred to in https://github.com/brave/brave-browser/issues/12375, the trash icon in that never worked at all.

**Comment by diracdeltas** [comment]
NVM, the menu in #12375 seems to still be there and broken

**Comment by ShivanKaul** [comment]
@bridiver pointed out that you can also see cookies for the current site by clicking the lock icon in the left-hand side of the omnibox and selecting Cookies
![image](https://user-images.githubusercontent.com/5284154/205810411-7c8d1729-3b5c-4686-861e-5b84e182a583.png)

**Comment by kbulgrien** [comment]
Another potential workaround uses Developer Mode albeit a bad UX for non-developers:

> Hamburger Menu
>> Extensions
>>> Developer Mode
 
To access cookies for a particular domain:

> Browse to the domain
>> Ctrl-Shift-I
>>> Network Tab (if not immediately visible, under >>)
>>>> Storage
>>>>> Cookies

From there, right-clicking on a particular cookie offers a delete option and various inspection options also exist.

**Comment by kbulgrien** [comment]
> This is a UX consideration, but ideally we would bring back `brave://settings/cookies/detail?site=xyz.com` page which could be navigated to from the `brave://settings/content/siteDetails?site=xyz.com` page.

IMO, this is more than a UX issue.  It seems also a privacy regression in that it makes a user's stored private information more difficult to access and review.  It should be possible to easily review what a site stores about visits to facilitate making changes to the way one interacts with a site.

**Comment by NipLars** [comment]
Agree - inspection of cookie detail is unfortunate that it's gone as they are stored in brave.
No need to visit a site again first.

Now you only see that it's 6 cookies, and ability to delete all.

**Comment by spylogsster** [comment]
Adding an item to this page

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/2965009/227460839-21b988d5-0da3-4858-bf35-634445476f44.png">

**Comment by ShivanKaul** [comment]
@spylogsster thanks! can you show a screenshot of what page you get when you click on the Cookies and Site Data item?

**Comment by spylogsster** [comment]
<img width="1008" alt="image" src="https://user-images.githubusercontent.com/2965009/227946311-81f97f77-cb9c-44fa-a599-1674c86d0b4c.png">
cc @ShivanKaul

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.52.94 Chromium: 113.0.5672.92 (Official Build) beta (64-bit)
-- | --
Revision | b6f521170062a1fa8a82c33fb223b06fec566da1-refs/branch-heads/5672_63@{#10}
OS | Windows 11 Version 22H2 (Build 22621.1702)
```

Case 1: View and manage individual cookies - `PASSED`
<details>

1. Install 1.52.94
2. launched Brave
3. navigated to coupled sites (github.com and gmail.com)
4. clicked around a bit
5. loaded `brave://settings/cookies`
6. clicked on` See all site data and permissions`
7. clicked on github.com on brave://settings/content/all
8. clicked on Cookies and Site Data on brave://settings/content/siteDetails?site=https%3A%2F%2Fgithub.com%2F
9. clicked on the down arrow to the right of github.com
10. clicked on on the first entry (`__Host-user_session_same_site`)
11. confirmed individual cookie data and ability to Remove via X at brave://settings/cookies/detail?site=github.com
12. also confirmed Remove All

step 5 - 6 | step 7 | step 8 | step 9 -10 | step 11 | step 12
---- | --- | --- | --- | --- | ---- 
<image width = "600" alt ="image" src="https://github.com/brave/brave-browser/assets/98358127/bda045b4-113e-49ae-b551-1a0ad95bbf62">|<image width = "600" alt ="image" src="https://github.com/brave/brave-browser/assets/98358127/fe89760e-004a-46d3-8bb5-f3ded0c1a232">|<image width = "600" alt ="image" src="https://github.com/brave/brave-browser/assets/98358127/9e89bc3d-8fa1-4bf4-aba2-1d3a5cecb069">|<image width = "600" alt ="image" src="https://github.com/brave/brave-browser/assets/98358127/d79139fc-6abd-402f-acb7-c215edff4407">|<image width = "600" alt ="image" src="https://github.com/brave/brave-browser/assets/98358127/cef4a623-c496-45b9-bcbf-dbdedcb631ac">|<image width = "600" alt ="image" src="https://github.com/brave/brave-browser/assets/98358127/8c92fed6-341a-4b5d-8823-d0243c08c7a3">

</details>
Case 2: `brave://settings/content/all` - `PASSED`
<details>

### Steps:
1. new profile 
3. visited bbc.com
4. loaded `brave://settings/cookies`
5. clicked on `See all site data and permissions`
6. clicked on `bbc.com` on `brave://settings/content/all`
7. clicked on `bbc.com` arrow to view all the cookies
8. confirmed I could remove all cookies for a single domain via the `Trash` icon / `Remove www.bbc.com` icon
9. confirmed I could remove all cookies associated with a website (NOT a single domain)
10. confirmed I could remove all data via the `Clear all data` button

step 4 |  step 5 | step 6 | individual delete | top-level delete | `Clear all data` | cleared data
---------|----------|---------|----------|---------|---------|----------
<image width = "600" alt ="image" src="https://github.com/brave/brave-browser/assets/98358127/aef811a6-a650-4e38-88ca-4d3b6444fdcb">|<image width = "600" alt ="image" src="https://github.com/brave/brave-browser/assets/98358127/3ce28140-18a2-407c-ade3-215a9c802868">|<image width = "600" alt ="image" src="https://github.com/brave/brave-browser/assets/98358127/0adbe202-40e6-4ec2-8c51-9a43090aa30c">|<image width = "600" alt ="image" src="https://github.com/brave/brave-browser/assets/98358127/3cc53c3e-8a04-4815-ab7e-0ea5b2187dd5">|<image width = "600" alt ="image" src="https://github.com/brave/brave-browser/assets/98358127/4295b2a6-7aae-424a-8f0a-37f582421dd2">|<image width = "600" alt ="image" src="https://github.com/brave/brave-browser/assets/98358127/d9d264c1-cba2-476e-8cbd-56151cfd43ae">|<image width = "600" alt ="image" src="https://github.com/brave/brave-browser/assets/98358127/82eb8bd7-bb8a-483d-9116-3db8783894d4">

**Comment by stephendonner** [comment]
## Verification `PASSED` using


Case 1: View and manage individual cookies - `PENDING`
<details>

### Steps:
1. installed `1.52.91`
2. launched Brave
3. logged in to `github.com`
4. clicked around a bit
5. loaded `brave://settings/cookies`
6. clicked on `See all site data and permissions`
7. clicked on `github.com` on `brave://settings/content/all`
8. clicked on `Cookies and Site Data` on `brave://settings/content/siteDetails?site=https%3A%2F%2Fgithub.com%2F`
9. clicked on the down arrow to the right of `github.com`
10. clicked on an entry for `www.github.com.com`
11. confirmed individual cookie data and ability to `Remove` via `X` at `brave://settings/cookies/detail?site=github.com`
12. also confirmed `Remove All`

step 5-6 | step 7 | step 8 | step 9  | step 10 | step 12
-----|------|-----|------|-----|--------

</details>

Case 2: `brave://settings/content/all` - `PENDING`
<details>

### Steps:
1. installed `1.52.91`
2. launched Brave
3. loaded `cnn.com`
4. clicked around a bit
5. loaded `brave://settings/cookies`
6. clicked on `See all site data and permissions`
7. clicked on `cnn.com` on `brave://settings/content/all`
8. clicked on the down arrow to the right of `cnn.com`
9. confirmed I could remove all cookies for a single domain via the `Trash` icon / `Remove www.cnn.com` icon
10. confirmed I could remove all cookies associated with a website (NOT a single domain)
11. confirmed I could remove all data via the `Clear all data` button

`brave://settings/content/all` | `cnn.com` cookies | individual delete | top-level delete | `Clear all data` | cleared data
---------|----------|---------|----------|---------|---------




</details>


Case 3: Upgrade - `PENDING`
<details>

### Steps:
1. installed `1.51.114`
2. launched Brave
3. loaded a bunch of websites
4. disabled Shields for a selection of websites (and ensured they got added to `Sites that can always use cookies`)
5. added a few sites to `Sites that can never use cookies`
6. upgraded to `1.52.91`

### Confirmed:
* `Sites that can always use cookies` and `Sites that can never use cookies` were populated correctly on `brave://settings/cookies`
* sites were listed in `brave://settings/content/all`
* `Cookies and site data` link on `brave://settings/content/siteDetails?site=https%3A%2F%2Fwww.youtube.com%2F`
* `Cache Storage`, `Database Storage`, `Local Storage`, and `Service Workers` were present, with values, on `brave://settings/cookies/detail?site=www.youtube.com`
* cookies and their values were present on `brave://settings/cookies/detail?site=youtube.com`

### `1.51.114`

b...s/cookies | b...s/content/all | `b...s/content/siteDetails?site=https%3A%2F%2Fwww.youtube.com%2F` | `b...s/cookies/detail?site=youtube.com` | `b...s/cookies/detail?site=www.youtube.com`
-------------------------|----------------------------|----------------------------------|-----------------------|----------




### `1.52.91`

b...s/cookies | b...s/content/all | `b...s/content/siteDetails?site=https%3A%2F%2Fwww.youtube.com%2F` | `b...s/cookies/detail?site=youtube.com` | `b...s/cookies/details?site=www.youtube.com`
-------------------------|----------------------------|----------------------------------|----------------------|--------------




</details>

Logged:
* https://github.com/brave/brave-browser/issues/30208

**Comment by pkit** [comment]
I'm here in 2025. And it's not there anymore.
You can see "17 cookies" and "Delete data", but there's no way to get the cookies.

**Comment by Dawnexa** [comment]
I wonder why the ability to view individual cookies got removed again

**Comment by SamL98** [comment]
Same thing here. I would like this feature back
