### ISSUE TITLE
Brave Ads clicked events should not trigger if there is no corresponding viewed event for the ad placement

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#27165]
## Description 

Brave Ads clicked events should not trigger if there is no corresponding viewed event for the placement id

## Steps to Reproduce

   1. Join Rewards
   2. View a new tab page sponsored image ad (do not close this tab as it is required in step 6)
   3. Reset Brave Rewards
   4. Join Rewards
   5. Wait for tokens to refill
   6. Click the new tab page sponsored image ad (from step 3)

## Actual result:

User is rewarded

## Expected result:
User should not be rewarded because the ad was viewed with a previous wallet

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.49.91 Chromium: 110.0.5481.77 (Official Build) beta (64-bit) 
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/16712

#### inline ad
<details>



</details>

#### ntp si ad
<details>



</details>
