### ISSUE TITLE
Make `My Node` a link button similar to Details/Manage Peer ID and IPNS Keys

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#27162]
## Description 

`My Node` is a link but looks like a normal text. It should be made into a link button similar to other link buttons on the page

## Steps to Reproduce

   1. Load `brave://ipfs-internals`
   2. Click on Install and Start
   3. My Node shows up but looks like a text rather than a link button

## Actual result:

<img width="571" alt="image" src="https://user-images.githubusercontent.com/17010094/205558502-2718739b-5c50-42c9-b5bf-43b7c2db68fa.png">

## Expected result:
<img width="586" alt="image" src="https://user-images.githubusercontent.com/17010094/205559135-b574a11c-341e-4598-a062-535bf2a83e85.png">

## Reproduces how often: 

Easy

## Brave version (brave://version info)

All

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @cypt4

**Comment by vadimstruts** [comment]
The IPFS local node and scheme has been [deprecated](https://github.com/brave/brave-browser/issues/37735)
