### ISSUE TITLE
Add sidebar position menu entry to sidebar context menu

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#27160]
Add sidebar position menu entry to sidebar context menu like below
![Screenshot 2022-12-05 133402](https://user-images.githubusercontent.com/6786187/205550690-ab472230-4ab2-4f33-943d-607eb5fdf872.png)

When sidebar is on left,  `Move to the right` entry should be added.
When sidebar is on right, `Move to the left` menu should be added.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.48.118 Chromium: 109.0.5414.80 (Official Build) beta (x86_64)
-- | --
Revision | 0f69b168d36a06cace4365e9f029fa987afa5633-refs/branch-heads/5414@{#1178}
OS | macOS Version 11.7.2 (Build 20G1020)

### Steps:

1. Launched Brave and checked sidebar is on left
2. Right-clicked to have sidebar context menu
3. Checked context menu has `Move to the right` entry
4. Clicked `Move to the right` and checked sidebar is moved on right
5. Right-click to have sidebar context menu
6. Check context menu has `Move to the left` entry

example | example | example | example | example
---------|----------|---------|----------|---------
<img width="1312" alt="Screen Shot 2023-01-09 at 5 05 47 PM" src="https://user-images.githubusercontent.com/387249/211438855-3525fe3f-61af-4684-91b0-e21810eeb682.png"> | <img width="1200" alt="Screen Shot 2023-01-09 at 5 06 00 PM" src="https://user-images.githubusercontent.com/387249/211438876-c0e3d47f-ddb6-41d8-9a3b-b81e4927bb76.png"> | <img width="1312" alt="Screen Shot 2023-01-09 at 5 06 04 PM" src="https://user-images.githubusercontent.com/387249/211438883-58d91577-d986-4ecd-a485-13574ec823ca.png"> | <img width="1199" alt="Screen Shot 2023-01-09 at 5 06 17 PM" src="https://user-images.githubusercontent.com/387249/211438885-7d61a7df-e3e4-4b66-9baf-01d91e8ee51a.png"> | <img width="1312" alt="Screen Shot 2023-01-09 at 5 06 29 PM" src="https://user-images.githubusercontent.com/387249/211438893-454b7f3e-8b4e-4efb-8b55-4a364048600c.png">
