### ISSUE TITLE
Add P3A metric for ISO weekly browser usage

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#27178]
Add P3A metric for browser uses in the last ISO week.

How many days did you use the browser in the previous ISO week?
`Brave.Core.WeeklyUsage`

Bucket values are 0 - 7

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on 

```
Brave | 1.50.85 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | Windows 10 Version 21H2 (Build 19044.2604)

```

**Comment by DJAndries** [comment]
@GeetaSarvadnya Updated the wiki. Each answer index corresponds to the number of days used in the previous ISO week. An answer of 2 states that you used the browser two times in the previous week.
