### ISSUE TITLE
Remove icon fetching for unverified media publishers

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#2717]
Remove icon scraping for media publishers if they are not verified.

cc @NejcZdovc @diracdeltas

**Comment by diracdeltas** [comment]
for regular sites, the icon is from chromium icon db, not scraping, so
those can be unchanged

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.58.20 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Windows 7

Used test plan from https://github.com/brave/brave-core/pull/1200
All PASSED
Verified page: https://kjozwiak.github.io/
Unverified page: https://www.interia.pl/
Verified youtube: https://www.youtube.com/watch?v=GNszD3W_G_g
Unverified youtube: https://www.youtube.com/watch?v=ZNjdf0F695Y
