### ISSUE TITLE
Link learn more link to support article for Windows 7/8/8.1 prompt 

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#27176]
## Description 
Learn more link should point to `https://support.brave.com/hc/en-us/articles/11197967945613` from infobar and from brave://settings/help

<img width="1064" alt="screenshot_2022-12-03_at_1 10 28_am" src="https://user-images.githubusercontent.com/5951041/205806063-6b47420e-8754-4f30-8eec-f6e0c1060bf4.png">

## Steps to Reproduce

   1. Go to brave://settings/help using Windows 7, 8, or 8.1 and notice learn more link. Should be using 1.46.34
   2. Link should point to the one in Description.

## Actual result:

Learn more link goes to https://support.brave.com/

## Expected result:
See description.

## Reproduces how often: 

Easily.

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.46.141 Chromium: 108.0.5359.99 (Official Build) (32-bit)
-- | --
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | Windows 7 Service Pack 1 (Build 7601)

Verified `Learn more` on infobar opens brave support article
![image](https://user-images.githubusercontent.com/34715963/206729972-c5a1e85a-3085-4aff-8389-1194cadc04ba.png)
![image](https://user-images.githubusercontent.com/34715963/206730017-bb9104fa-6c85-47dd-9fdd-27d1d6868ac8.png)

Verified `Learn more` on infobar opens brave support article
![image](https://user-images.githubusercontent.com/34715963/206730124-b1658ba0-8bf4-433f-8009-b20c7d3fbc6a.png)
![image](https://user-images.githubusercontent.com/34715963/206730242-9aca84de-e877-4af9-9118-1471532bcf1c.png)
