### ISSUE TITLE
Add flow for no browser detected when onboarding

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#27170]
## Description 

If no browsers are detected during the onboarding v2 import flow, show the `Choose your theme` screen. Default to match system setting. When selecting dark mode, change background of buttons to reflect dark mode choice.

## Steps to reproduce:
1. Fresh install of Brave on macOS with only Safari installed.
2. Notice screen in actual result.

## Actual result:

<img width="1096" alt="Screen Shot 2022-12-04 at 2 05 47 PM" src="https://user-images.githubusercontent.com/5951041/205690734-899b7e93-3c29-423e-84b8-860517a543a0.png">

## Expected result:
<img width="1512" alt="Screenshot 2022-12-06 at 12 33 46 PM" src="https://user-images.githubusercontent.com/5951041/206017373-7c4e32b0-868e-4002-9ced-e2670d68ead8.png">

<img width="1495" alt="Screenshot 2022-12-06 at 12 33 16 PM" src="https://user-images.githubusercontent.com/5951041/206017398-9bbed356-0d7c-4438-9d8d-88261d5d3bcd.png">

https://www.figma.com/file/MFHpcXJMg2RUQpUJMAZZ4R/Desktop-Onboarding?node-id=3325%3A42022&t=LEYjscmyx6nVbe4p-0

## Reproduces how often: 

Easily.

## Brave version (brave://version info)

1.47.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by jenn-rhim** [comment]
How confident are we in detecting that there is no settings to import? @rebron

**Comment by rebron** [comment]
@jenn-rhim Fairly confident. I tested on a normal user's machine and encountered this case.

**Comment by kjozwiak** [comment]
The above requires `1.47.154` or higher for `1.47.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.47.154 Chromium: 109.0.5414.46 (Official Build) beta (x86_64)
-- | --
Revision | 6e36b77363ef3febbe792af680fa1367993ddcf0-refs/branch-heads/5414@{#709}
OS | macOS Version 13.2 (a) (Build 22D7750270d)

### Prerequisites:
<details>

* removed all profile folders for various browsers, in `/Users/sdonner/Library/Application\ Support/`
* removed `Opera's` `com.operasoftware.Opera` file object in the above, top-level
* ran the `Reset Safari Using Terminal` section from `https://www.makeuseof.com/reset-safari-default-mac/` line-by-line:
```
mv ~/Library/Safari ~/Desktop/Safari-`date +%Y%m%d%H%M%S`;
rm -Rf ~/Library/Cache/*;
rm -Rf ~/Library/Caches/Apple\ -\ Safari\ -\ Safari\ Extensions\ Gallery;
rm -Rf ~/Library/Caches/Metadata/Safari;
rm -Rf ~/Library/Caches/com.apple.Safari;
rm -Rf ~/Library/Caches/com.apple.WebKit.PluginProcess;
rm -Rf ~/Library/Cookies/*;
rm -Rf ~/Library/Cookies/Cookies.binarycookies;
rm -Rf ~/Library/Preferences/Apple\ -\ Safari\ -\ Safari\ Extensions\ Gallery;
rm -Rf ~/Library/Preferences/com.apple.Safari.LSSharedFileList.plist;
rm -Rf ~/Library/Preferences/com.apple.Safari.RSS.plist;
rm -Rf ~/Library/Preferences/com.apple.Safari.plist;
rm -Rf ~/Library/Preferences/com.apple.WebFoundation.plist;
rm -Rf ~/Library/Preferences/com.apple.WebKit.PluginHost.plist;
rm -Rf ~/Library/Preferences/com.apple.WebKit.PluginProcess.plist;
rm -Rf ~/Library/PubSub/Database;
rm -Rf ~/Library/Safari/*;
rm -Rf ~/Library/Safari/Bookmarks.plist;
rm -Rf ~/Library/Saved\ Application\ State/com.apple.Safari.savedState;
```

</details>


### Case 1: Dynamic auto-mode selection with `Match system setting` selected - `PASSED`
<details>

`Brave, Dark (Auto)` | `macOS, Dark` | `Brave, Light (Auto)` | `macOS, Light`
---------|----------|---------|---------
<img width="1016" alt="Screenshot 2022-12-29 at 4 41 29 PM" src="https://user-images.githubusercontent.com/387249/210024161-d17e25e8-c60f-401e-88f1-72b61df61f2c.png"> | <img width="827" alt="Screenshot 2022-12-29 at 4 41 36 PM" src="https://user-images.githubusercontent.com/387249/210024164-52731599-4c50-402e-9cf0-6c299a80e747.png"> | <img width="1016" alt="Screenshot 2022-12-29 at 4 41 41 PM" src="https://user-images.githubusercontent.com/387249/210024166-56bcb1f3-2d84-43fd-9c69-b2fef59ad5b2.png"> | <img width="827" alt="Screenshot 2022-12-29 at 4 41 45 PM" src="https://user-images.githubusercontent.com/387249/210024168-33ba1f2f-772f-43c0-ac6a-d3e8d280460c.png">

</details>

#### Case 2: Override the OS setting via `Light mode` and `Dark mode` - `PASSED`
<details>

`Brave, Dark` | `macOS, Light` | `Brave, Light` | `macOS, Dark`
---------|----------|---------|---------
<img width="1016" alt="Screenshot 2022-12-29 at 4 42 58 PM" src="https://user-images.githubusercontent.com/387249/210024071-aec0982d-5a71-4075-95ce-bc5768e235a5.png"> | <img width="827" alt="Screenshot 2022-12-29 at 4 43 01 PM" src="https://user-images.githubusercontent.com/387249/210024075-b74c73e7-9718-4c20-b86f-b9ae6d0a54f9.png"> | <img width="1016" alt="Screenshot 2022-12-29 at 4 43 10 PM" src="https://user-images.githubusercontent.com/387249/210024078-99be6b26-2db0-47ae-9d51-3cc71c1a2321.png"> | <img width="827" alt="Screenshot 2022-12-29 at 4 43 13 PM" src="https://user-images.githubusercontent.com/387249/210024081-b9b1e027-9a94-498a-b29c-ead2872a18cd.png">

#### Confirmed the Brave setting overrides the `macOS` system setting

</details>

#### Case 3: `Skip` on `Choose your theme` leaves pref defaulted to `same as macOS`
<details>

<img width="1016" alt="Screenshot 2022-12-29 at 4 42 11 PM" src="https://user-images.githubusercontent.com/387249/210024789-7ea09735-ac6a-4038-a3c2-836f8944313d.png">
