### ISSUE TITLE
Unnecessary performance hit calculating farbling level

### ISSUE THREAD

**Issue by pilgrim-brave** [brave/brave-browser#27186]
Spun off from https://github.com/brave/brave-core/pull/16216 as per discussion in Slack, we are calculating the farbling level over and over, sometimes in hot paths where every cycle counts.

**Comment by LaurenWags** [comment]
@pes10k @pilgrim-brave please add `QA/Yes` or `QA/No` label - not sure if manual QA is required for this one. If `QA/Yes`, please also add a test plan.

Also, this one needs `release-notes/include` or `release-notes/exclude`.

cc @rebron @kjozwiak

**Comment by pes10k** [comment]
@pilgrim-brave please take a look when you have a chance

**Comment by pilgrim-brave** [comment]
This is well-covered by our regression tests.
