### ISSUE TITLE
There is no way for a user to learn the contract address they are signing a transaction for

### ISSUE THREAD

**Issue by nvonpentz** [brave/brave-browser#27188]
As far as I can tell, there's no way to copy the contract address from our UI when signing a transaction.  As a result, users have no choice but to blindly trust the contract. The frontend should display the full contract address or create a way to copy it so users can look it up before signing.

**Comment by diracdeltas** [comment]
can this be prioritized?

**Comment by bbondy** [comment]
The backend side is here: https://github.com/brave/brave-core/pull/17215 @Douglashdaniel will pickup the front end work next.

**Comment by kjozwiak** [comment]
The above requires `1.49.118` or higher for `1.49.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.49.118 Chromium: 111.0.5563.50 (Official Build) (64-bit) 
-- | --
Revision | `39f3dfc5023fe60997adc4f6cf5439cfa3e6968a-refs/branch-heads/5563@{#903}`
OS | Linux

- Verified steps from [brave/brave-core#17333](https://github.com/brave/brave-core/pull/17333)
- Verified when a contract address is used for sign transaction it updates the address to show as contract address
- Verified clicking on the contract address loads block explorer and sets focus to the code section on the page
- Encountered [#28849](https://github.com/brave/brave-browser/issues/28849)

https://user-images.githubusercontent.com/17010094/223029931-ca25933c-c481-4b40-913a-684d8b65fefc.mp4


---------------------

Verification passed on 

Brave | 1.49.118 Chromium: 111.0.5563.50 (Official Build) (64-bit)
-- | --
Revision | `39f3dfc5023fe60997adc4f6cf5439cfa3e6968a-refs/branch-heads/5563@{#903}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#17333](https://github.com/brave/brave-core/pull/17333)
- Verified when a contract address is used for sign transaction it updates the address to show as contract address
- Verified clicking on the contract address loads block explorer and sets focus to the code section on the page
- Encountered [#28849](https://github.com/brave/brave-browser/issues/28849)

https://user-images.githubusercontent.com/17010094/223027835-092ef3c0-2cb1-4fc3-98f1-a24667cb68a5.mp4

---------------------

Verification passed on 

Brave | 1.49.118 Chromium: 111.0.5563.50 (Official Build) (arm64)
-- | --
Revision | `39f3dfc5023fe60997adc4f6cf5439cfa3e6968a-refs/branch-heads/5563@{#903}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#17333](https://github.com/brave/brave-core/pull/17333)
- Verified when a contract address is used for sign transaction it updates the address to show as contract address
- Verified clicking on the contract address loads block explorer and sets focus to the code section on the page
- Encountered [#28849](https://github.com/brave/brave-browser/issues/28849)

https://user-images.githubusercontent.com/17010094/223028247-96b3adaa-2801-406b-87e2-7842007d8708.mov
