### ISSUE TITLE
`Popular` section of Brave News Customize UI is not shown after enabling Brave News

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#27183]
Note: the issue is fixed after page reload

## Steps to Reproduce

Note: Make sure Brave News Customize 2.0 UI is enabled

1. Clean profile
1. Launch Brave in en_us locale
1. Open a new-tab page
1. Click `Customize`
1. Click `Brave News` in the `Customize Dashboard`
1. Click `Turn on `Brave News`

## Actual result:

`Popular` section is not shown

![image](https://user-images.githubusercontent.com/34715963/205957844-4959aa7b-9d8b-4912-8d98-fee7a1c2e2e4.png)

## Expected result:
`Popular` section is shown

![image](https://user-images.githubusercontent.com/34715963/205958502-ae9577a4-fc3f-438c-b306-d8eea98cc138.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.47.115 Chromium: 108.0.5359.94 (Official Build) beta (64-bit)
-- | --
Revision | 713576b895246504ccc6b92c2fb8ce2d60194074-refs/branch-heads/5359_71@{#3}
OS | Windows 10 Version 21H2 (Build 19044.2251)

Brave | 1.48.29 Chromium: 108.0.5359.94 (Official Build) nightly (64-bit)
-- | --
Revision | 713576b895246504ccc6b92c2fb8ce2d60194074-refs/branch-heads/5359_71@{#3}
OS | Windows 10 Version 21H2 (Build 19044.2251)

cc @rebron @fallaciousreasoning @petemill @mattmcalister

**Comment by btlechowski** [comment]
This is a regression as I am not able to reproduce in 1.46.133

**Comment by fallaciousreasoning** [comment]
I'll take a look

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.48.118 Chromium: 109.0.5414.80 (Official Build) beta (64-bit)
-- | --
Revision | 0f69b168d36a06cace4365e9f029fa987afa5633-refs/branch-heads/5414@{#1178}
OS | Windows 11 Version 21H2 (Build 22000.1335)
```

Reproduced in 1.47.165 using original STR from https://github.com/brave/brave-browser/issues/27183#issue-1479440282


1. Install 1.48.118
2. launch Brave
3. open a new-tab page
4. Click `Customize`
5. Click `Brave News`
6. Click `Turn on Brave News`

#### Confirmed `Popular` section is shown as expected

step 4|step5|step6|popular
----|-----|----|-----
<img width="453" alt="image" src="https://user-images.githubusercontent.com/98358127/211428115-6c8c21e9-4b57-4705-8939-8e9f1bff8141.png">|<img width="459" alt="image" src="https://user-images.githubusercontent.com/98358127/211428135-dc2035a4-d434-45fa-87ba-d93f3100403d.png">|<img width="450" alt="image" src="https://user-images.githubusercontent.com/98358127/211428157-e7737843-a28c-4153-ae7f-64d1d3b49d17.png">|<img width="454" alt="image" src="https://user-images.githubusercontent.com/98358127/211428567-00e04865-9752-4e4e-9366-710803ba17fb.png">

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.48.119 Chromium: 109.0.5414.80 (Official Build) beta (x86_64)
-- | --
Revision | 0f69b168d36a06cace4365e9f029fa987afa5633-refs/branch-heads/5414@{#1178}
OS | macOS Version 11.7.2 (Build 20G1020)

### Steps:
1. installed `1.48.119`
2. launched Brave
3. opened a new-tab page
4. clicked on `Customize`
5. clicked on `Brave News`
6. clicked on `Turn on Brave News`

#### Confirmed Brave News was successfully enabled, with a `Popular` section above `Channels`

example | example | example | example
---------|----------|---------|---------
<img width="1312" alt="Screen Shot 2023-01-10 at 10 16 48 AM" src="https://user-images.githubusercontent.com/387249/211631244-0e7ab9f2-8f80-4ad9-9dc1-78c250e37ff0.png"> | <img width="1312" alt="Screen Shot 2023-01-10 at 10 16 55 AM" src="https://user-images.githubusercontent.com/387249/211631253-476364ce-0611-458a-b133-3636d64dc0c2.png"> | <img width="1312" alt="Screen Shot 2023-01-10 at 10 16 59 AM" src="https://user-images.githubusercontent.com/387249/211631267-5fd208f5-ce70-40a7-a61a-23265d206446.png"> | <img width="1312" alt="Screen Shot 2023-01-10 at 10 18 18 AM" src="https://user-images.githubusercontent.com/387249/211631270-bc116604-9893-4d80-ae7e-0aaeb848e29f.png">
