### ISSUE TITLE
Publisher banner: incorrect letter used thank you banner

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#2718]
When tipping unverified/verified YT channel, the thank you screen shows a “Y” in a circle, vs the first letter of the channel.
Need to use the first letter of the channel consistently across tip-banner and thank-you-banner.

cc @davidtemkin @NejcZdovc

**Comment by jonathansampson** [comment]
This applies to *verified* publishers too:

![image](https://user-images.githubusercontent.com/815158/50386870-a181db00-06b5-11e9-8a06-826fdb37e1fd.png)

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.60.28 Chromium: 72.0.3626.96 (Official Build) beta (64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Windows 7

For some verified publishers there is no icon at all. Logged: https://github.com/brave/brave-browser/issues/3364

Unverified publishers are shown with the proper letter.
Channel URL: `https://www.youtube.com/channel/UCwRMYIQ89FhDouMEASM5uAA`
Channel name: `MrShoptaw`
Banner:
![image](https://user-images.githubusercontent.com/34715963/52824018-52ee2d00-30b7-11e9-9a79-f3efddfafeb0.png)
