### ISSUE TITLE
Unknown Solana instruction shouldn't use first available pubkey as to address

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#27187]
## Description 
Right now if it's not system, voting, or staking programs, we will assign instruction type to unknown (https://github.com/brave/brave-core/blob/71c2c4f5d7d79ef001714cf73690366f64080021/components/brave_wallet_ui/utils/solana-instruction-utils.ts#L114).
And when getting to addresses, we fallback to first pubkey in accounts to be the to address(https://github.com/brave/brave-core/blob/691823f679986f16509b573ad62b5d7099aa237e/components/brave_wallet_ui/utils/tx-utils.ts#L147-L149), which is unlikely to be a correct.
Take token transfer instruction for example, first pubkey is from_address, and the second pubkey is to_address, so in this case, we'll show from address as to address which is wrong. If we can't parse the instruction, the safest is probably just not having to address assigned instead of picking one blindly.

## Steps to Reproduce
Use token transfer as an example:
   1. Open https://pwgoom.csb.app/
   2. Do `Connect` and `Sign and Send SPL Token Transaction`
   3. Check Details in the transaction prompt and scroll down to Accounts section.

## Actual result:

<img width="314" alt="Screen Shot 2022-12-06 at 12 10 32 PM" src="https://user-images.githubusercontent.com/4730197/206012649-4b0bf2fc-cd97-4831-9624-323979db2665.png">
Receiver address is shown as the first account in Accounts.

## Expected result:
Receiver should be the second account in Accounts.

## Reproduces how often: 
Every time

## Version/Channel Information:
Reproduced on all channels. (I tested release and nightly, but I would think beta is just the same.)

**Comment by kjozwiak** [comment]
The above requires `1.46.141` or higher for `1.46.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.46.141 Chromium: 108.0.5359.99 (Official Build) (64-bit)
-- | --
Revision | `410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}`
OS | Windows 11 Version 22H2 (Build 22623.1028)

- Verified steps from [brave/brave-core#16275](https://github.com/brave/brave-core/pull/16275) and issue description

https://user-images.githubusercontent.com/17010094/206728862-dbf36ed3-8a00-41a9-85c7-c5cba72f0c6f.mov
