### ISSUE TITLE
`Can't connect to server` dialog appears after removing `BraveVPN` config and trying to reconnect

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#27196]
## Description 

`Can't connect to server` dialog appears after removing `BraveVPN` config and trying to reconnect

## Steps to Reproduce

1. install `1.46.134`
2. launch Brave
3. open brave://flags
4. set brave://flags/#brave-vpn to Enabled
5. click on Relaunch
6. load account.bravesoftware.com
7. click on Buy now under Brave VPN & Firewall
8. complete Stripe checkout
9. click on the VPN button
10. connect to VPN
11. accept the OS network-config dialog
12. try to connect to BraveVPN

## Actual result:

`Can't connect to server` dialog is shown.  I also see this in the console:

```[11899:259:1206/151621.250347:ERROR:brave_vpn_os_connection_api_mac.mm(250)] Connect - startVPNTunnel error: The operation couldn’t be completed. (NEVPNErrorDomain error 1.)```

<img width="1678" alt="Screen Shot 2022-12-06 at 3 16 45 PM" src="https://user-images.githubusercontent.com/387249/206045856-f5d7468d-3de9-4385-85c6-917ea2959472.png">

## Expected result:

Should be able to connect to `BraveVPN`

<img width="1163" alt="Screen Shot 2022-12-06 at 3 17 05 PM" src="https://user-images.githubusercontent.com/387249/206045905-f569257c-8a57-4661-888a-b077587fc0bc.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.46.134 Chromium: 108.0.5359.94 (Official Build) (x86_64)
-- | --
Revision | 713576b895246504ccc6b92c2fb8ce2d60194074-refs/branch-heads/5359_71@{#3}
OS | macOS Version 11.7.1 (Build 20G918)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

/cc @mattmcalister @bsclifton @simonhong @brave/qa-team @rebron @simonhong @spylogsster

**Comment by stephendonner** [comment]
I don't think this is a launch blocker, but it'd be nice to get a fix ASAP, if we can.

![vpn-cantconnect](https://user-images.githubusercontent.com/387249/206047467-3db3b242-5107-4dd4-84a2-cec4071a7e9f.gif)

**Comment by simonhong** [comment]
Reopened as this is still reproduced on macOS.

**Comment by kjozwiak** [comment]
The above requires `1.47.130` or higher for `1.47.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.47.132 Chromium: 108.0.5359.128 (Official Build) beta (x86_64)
-- | --
Revision | 1cd27afdb8e5d057070c0961e04c490d2aca1aa0-refs/branch-heads/5359@{#1185}
OS | macOS Version 11.7.2 (Build 20G1020)

Followed my original steps to reproduce.

#### Confirmed I never saw the `Can't connect to server` dialog after removing the `BraveVPN` config

![vpn-retry](https://user-images.githubusercontent.com/387249/208236628-adea75e6-e4a8-49a3-9c29-06ef79011bde.gif)
