### ISSUE TITLE
Webcompat - Wyre - Network Requests blocked in Buy crypto purchase flow

### ISSUE THREAD

**Issue by lukemulks** [brave/brave-browser#27192]
## Description 

We're observing high reports of purchase failure rates via Wyre from Brave Wallet users. 

When running a network request check on the https://pay.sendwyre.com tab that opens when invoked from the Brave Wallet => Buy flow, I noticed that there are several 1st party requests invoked from the page that we're currently blocking in Brave. 

I have a strong suspicion that the blocking of these calls is negatively impacting our purchase flow conversion rate. 

## Steps to Reproduce

   1. Go to brave://wallet (desktop) 
   2.  Go through the steps to Buy an asset; select Wyre as the onramp to purchase from
   3.  Open dev tools from the https://pay.sendwyre.com page that's invoked when clicking the buy button. 

## Actual result:

Observing a series of 401 responses related to `api.sendwyre.com` that specifically appear to be related with purchase flow info that we're blocking. 
![brave-wyre-inspection-12062022-401s](https://user-images.githubusercontent.com/8979240/206031634-2d06c904-82d0-4944-97be-9dd70e304785.jpg)
![sendwyre-401-a](https://user-images.githubusercontent.com/8979240/206031639-be1c228f-c426-4b31-99e0-77c19f222751.jpg)
![sendwyre-401-a-a](https://user-images.githubusercontent.com/8979240/206031641-c26f4d73-9eed-4602-ac77-3c42031ea7c1.jpg)
![sendwyre-401-a-c](https://user-images.githubusercontent.com/8979240/206031645-f9fc9971-c1bd-488b-bc1b-7cc176e5dd10.jpg)
![sendwyre-401-b](https://user-images.githubusercontent.com/8979240/206031650-bfc63f45-c7e3-4514-86cc-577a35191175.jpg)
![sendwyre-401-b-a](https://user-images.githubusercontent.com/8979240/206031653-9658cf91-70eb-4280-ae1c-cbf2a6bc7248.jpg)
![sendwyre-401-c](https://user-images.githubusercontent.com/8979240/206031654-342d9f83-f2f7-42cd-ba94-9862791e4f12.jpg)
![sendwyre-401-c-a](https://user-images.githubusercontent.com/8979240/206031659-31325e5a-b4dd-495e-b29b-adf1ebbd9303.jpg)
![sendwyre-401-d](https://user-images.githubusercontent.com/8979240/206031661-147e0ecc-3464-4915-bb1a-5225f7e8a9f3.jpg)
![sendwyre-401-d-a](https://user-images.githubusercontent.com/8979240/206031664-01b8c7d8-ac82-4914-92b0-32faf7be8810.jpg)

Also observing a cloudflare beacon that we're blocking that loads early in the call stack and may be related to conversion rate issues. 

![cloudflare-beacon-a](https://user-images.githubusercontent.com/8979240/206031732-f56294b0-9da0-4f31-8bb5-c712fac5f43a.jpg)
![cloudflare-beacon-a-a](https://user-images.githubusercontent.com/8979240/206031736-938475c6-ed65-4f6e-9133-5a9af5859130.jpg)

Would be worth testing without shields enabled, to see if we have better purchase rates. 

Would also be worth checking on Android in case we're observing similar issues there. 
## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

1.48.32 Chromium: 108.0.5359.94 (Official Build) nightly (64-bit) 
- Can you reproduce this issue with the current release? TBD
- Can you reproduce this issue with the beta channel? TBD
- Can you reproduce this issue with the nightly channel? Y

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by lukemulks** [comment]
cc'ing @husobee @jamesmudgett for visibility @ryanbr ^ 

Unclear to me if these are filter rules related blocking issues, or something more related to core.

**Comment by ryanbr** [comment]
What shows up as blocked items? does disabling ads/tracker specfically help? @lukemulks

**Comment by ryanbr** [comment]
Try the following in brave://adblock, its shot in the dark; @lukemulks 

`@@||googletagmanager.com/gtm.js$domain=sendwyre.com` and/or `@@||google-analytics.com/analytics.js$domain=sendwyre.com`

**Comment by lukemulks** [comment]
Thanks will give that a shot and have a few others try with it and with Shields down.

**Comment by lukemulks** [comment]
Wyre went out of business; closing out this issue.
