### ISSUE TITLE
[Android] Remove `.` period after month name abbreviations in Rewards panel and make date format consistent

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#27193]
## Description

- [ ] Remove periods from abbreviations 
- [ ] 1 December vs. Dec. 1 

>I think on Android we show the dates on the card UI in a different format (1 Dec - 31 Dec) from the one we use in the Rewards panel (Dec. 1 - Dec. 31) @szilardszaloki 

![image](https://user-images.githubusercontent.com/11497541/206034110-76127162-ea6c-47a5-9822-c3b6381c3399.png)

**Comment by stephendonner** [comment]
## Verified `PASSED(*)` using `Brave` `1.48.148`, `Chromium` `109.0.5414.119` on a `Google Pixel XL` running `Android 9`

### Steps:
1. installed `1.48.148`
2. launched Brave
3. set Brave Rewards env. to staging via `QA Preferences`
4. tap on `BAT icon`
5. tap `Start using Brave Rewards`
6. tap `Connect`
7. tapped on `Uphold`
8. logged in to `Uphold`
9. waited
10. looked at the two formatted instances of January

#### Confirmed the month `January` was spelled out and without `.`

`*` As for the other date format, that issue still exists (`Jan 1 - Jan 31`, vs. `1 Jan - 31 Jan`), for which I logged https://github.com/brave/brave-browser/issues/28156.

example | example
---------|---------
![Screenshot_20230130-212405](https://user-images.githubusercontent.com/387249/215675880-77ad61ca-21b9-47c7-abfa-d888fff45a18.png) | ![Screenshot_20230130-212548](https://user-images.githubusercontent.com/387249/215675881-b12f8244-e05c-4c35-8b53-e8733ea75940.png)

**Comment by stephendonner** [comment]
Additionally, logged https://github.com/brave/brave-browser/issues/28157 about that difference in vertical padding.
