### ISSUE TITLE
Annoying website repeatedly displays pop up window to sign up

### ISSUE THREAD

**Issue by jcperil** [brave/brave-browser#27209]
## Description 
A [website](https://gizmodo.com) repeatedly displays pop up window asking you to sign up.

## Steps to reproduce 

   1. Go to https://gizmodo.com
   2. Enable JavaScript for the website if not enabled globally.
   3. Scroll to the bottom of their home page and wait a second or two.

## Actual result 
A dialog box appears asking you to sign up. And repeatedly so when you close it. Screenshot below

![gizmodo](https://user-images.githubusercontent.com/89805719/206117573-51af8b18-4819-4cba-b343-ea8068270e6d.jpg)

## Expected result
Pop up windows asking you to sign up should not appear.

## Issue reproduces how often 
Always

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Didn't test
- Can you reproduce this issue with the current Play Store Nightly version? Didn't test

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 12
   
## Brave version
1.46.134

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Didn't test

**Comment by jcperil** [comment]
cc @ryanbr

**Comment by jcperil** [comment]
As far as I know, brave browser does not allow custom blocklists. Can you link to the aforementioned blocklist?

**Comment by ryanbr** [comment]
brave://adblock @jcperil   Enable Fanboy Annoyances, then refresh gizmodo page

**Comment by jcperil** [comment]
No, it does not appear again in the website.

**Comment by ryanbr** [comment]
So resolved?

**Comment by jcperil** [comment]
Yes. Can you add https://www.rekhta.org to the Annoyances list? While scrolling through, they will show a window asking you to install their app.

> #### Rekhta is better on the app
> To get better and faster experience read this on the all new Rekhta app

**Comment by ryanbr** [comment]
Hmm actually might not be the element, what cosmetic install app? I see a login nag

**Comment by jcperil** [comment]
Which blocklist should I add in brave://adblock?
