### ISSUE TITLE
Unknown Solana instruction shouldn't use first available pubkey as to address (Android)

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#27208]
## Description 
Android issue for https://github.com/brave/brave-browser/issues/27187

**Comment by kjozwiak** [comment]
The above requires `1.47.129` or higher for `1.47.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.47.167 x64 build
- Verified steps from [brave/brave-core#16271](https://github.com/brave/brave-core/pull/16271)
- Verified correct `To` address is shown in transaction confirmation screen

Oppo Reno 5 (Android 12) | Lenovo Tab (Android 12)
-- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/211506712-202491d3-6544-40da-a55e-3fbc84e364e3.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/211506484-fe2d9189-4244-4d91-ad80-4b664e24cadc.png>
<img width=300 src=https://user-images.githubusercontent.com/17010094/211506668-c19b15b8-c413-42ff-976d-f09006404c36.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/211506426-252b2a0a-e7c6-4dd4-bbe9-6b1e6db0ce13.png>
