### ISSUE TITLE
Vertical Tabs Sidebar Does Not Fill Vertical Space

### ISSUE THREAD

**Issue by friedITguy** [brave/brave-browser#27218]
## Description 

The Vertical Tabs Sidebar has a blank space at the bottom, on some systems. In CSS terms, it looks as if the vertical tabs bar has a 'margin' on the bottom.

It could be a coincidence, but the blank space appears to be the same size as the new tab button. See the Miscellaneous Information section for more details.

## Steps to Reproduce

   1. Enable Vertical Tabs

## Actual result:

![205967512-835474ea-a9c2-489b-a552-c44d40a33b7b](https://user-images.githubusercontent.com/7979854/206244427-41558185-91c4-440b-8a6c-80fc79a97195.png)

## Expected result:

![205967512-835474ea-a9c2-489b-a552-c44d40a33b7b-edited](https://user-images.githubusercontent.com/7979854/206244906-50de97e8-65a9-4a74-94d4-02a0d3a8f350.png)

## Reproduces how often: 

Easily reproduced; is a constant issue.

## Brave version (brave://version info)

Brave: 1.48.32  Chromium: 108.0.5359.94 (Official Build) nightly (64-bit) 
Revision: 713576b895246504ccc6b92c2fb8ce2d60194074-refs/branch-heads/5359_71@{#3}
OS: Windows 11 Version 22H2 (Build 22621.819)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No. Even with the Vertical Tabs experiment enabled, it does not occur.
- Can you reproduce this issue with the beta channel? Yes.
- Can you reproduce this issue with the nightly channel? Yes.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

I have tried enabling/disabling 'Float on mouseover' and 'Show title bar', neither have any impact. 

You can see some odd behavior with the new tab button in the following video:

https://user-images.githubusercontent.com/7979854/206257765-6e9d8faa-52b1-4f58-beea-0ee988752d2f.mp4

**Comment by friedITguy** [comment]
I just wanted to note that I can also re-create this issue--at least partially--on the Beta build from my Mac. The brave://version info for that system is:

Brave: 1.47.115 Chromium: 108.0.5359.94 (Official Build) beta (x86_64)
Revision: 713576b895246504ccc6b92c2fb8ce2d60194074-refs/branch-heads/5359_71@{#3}
OS: macOS Version 12.6 (Build 21G115)

In order to re-create the issue, I had to enable vertical tabs and 'Float on mouseover'. Then, when I collapsed the vertical tabs bar and hovered over it, I saw the same issue. Please see this screenshot:

![Image 12-12-22 at 2 17 PM](https://user-images.githubusercontent.com/7979854/207136398-3b91175b-26f3-4854-a53c-63496751586b.JPG)

**Comment by sangwoo108** [comment]
Still happens.

**Comment by Coffeeling** [comment]
#27038 seems related.
