### ISSUE TITLE
[Android] Change "Unverified" text to "Connect" 

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#27215]
## Description

Android version of https://github.com/brave/brave-browser/issues/27191

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using `Brave` `1.48.152`, `Chromium` `109.0.5414.119` on a `Google Pixel XL` (`arm64`)  running `Android 9`



### New profile



### Upgraded profile



### 1.47.161

unverified `brave://rewards` | `Rewards panel` | verified `brave://rewards` | `Rewards panel`
-----------------------------|------------------|--------------------------|------------------
![Screenshot_20230305-001505](https://user-images.githubusercontent.com/387249/215989250-4fb801de-b325-4ae7-a689-ed1677f701eb.png) | ![Screenshot_20230305-001532](https://user-images.githubusercontent.com/387249/215989261-c08f1f6f-23d2-4a5e-a4f3-0a031c658ffa.png) | ![Screenshot_20230305-002029](https://user-images.githubusercontent.com/387249/215989265-22b63473-14c1-400f-8bd6-ee7c943da697.png) | ![Screenshot_20230305-002051](https://user-images.githubusercontent.com/387249/215989267-b28548bc-7c72-4f6a-bf61-505ebbc2ae39.png)
