### ISSUE TITLE
Disable first run dialog temporarily

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#27225]
Don't launch first run dialog as we'll launch new welcome flow.
If new welcome flow is more effective, we'll delete first run dialog.

1. Launch brave with clean profile
2. Check first run dialog is not launched

**Comment by kjozwiak** [comment]
The above requires `1.47.130` or higher for `1.47.x` verification 👍

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.47.132 Chromium: 108.0.5359.128 (Official Build) beta (64-bit)
-- | --
Revision | 1cd27afdb8e5d057070c0961e04c490d2aca1aa0-refs/branch-heads/5359@{#1185}
OS | Ubuntu 18.04 LTS

Verified first run dialog is disabled on clean profile
![27225](https://user-images.githubusercontent.com/34715963/208335723-6383de5a-e76c-4416-9794-0ce3fb2fb34e.gif)

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.47.135 Chromium: 108.0.5359.128 (Official Build) beta (x86_64)
-- | --
Revision | 1cd27afdb8e5d057070c0961e04c490d2aca1aa0-refs/branch-heads/5359@{#1185}
OS | macOS Version 11.7.2 (Build 20G1020)

### Steps:
1. installed `1.47.135`
2. launched Brave
3. confirmed no first-run dialog
4. clicked `Skip` on the `brave://welcome` screen
5. launched Brave 6x
6. confirmed still no first-run dialog

#### Screencast:

![no-first-run](https://user-images.githubusercontent.com/387249/208563737-40cddc97-d207-4be8-b511-b7e66e10b0f7.gif)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.47.136 Chromium: 108.0.5359.128 (Official Build) beta (64-bit)
-- | --
Revision | 1cd27afdb8e5d057070c0961e04c490d2aca1aa0-refs/branch-heads/5359@{#1185}
OS | Windows 11 Version 21H2 (Build 22000.1335)
```

Steps: 

*_new install_*

- installed 1.47.136
- launched Brave
- confirmed no first-run dialog
- clicked Skip on the brave://welcome screen
- launched Brave few times
- confirmed still no first-run dialog

<img width="469" alt="image" src="https://user-images.githubusercontent.com/98358127/208777560-fe6a548d-8d14-4fb5-8d93-4fb461bf82bf.png">

*_new profile_*

- launch Brave with a new profile 
- confirmed no first-run dialog
- clicked Skip on the brave://welcome screen
- launched Brave few times
- confirmed still no first-run dialog

<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/208777255-2d62102e-6723-45b8-b107-8fcdf436668c.png">
