### ISSUE TITLE
Youtube ads

### ISSUE THREAD

**Issue by ghost** [brave/brave-browser#27228]
I submitted a bug report to easylist but there is no answers yet: https://github.com/easylist/easylist/issues/14330

It's very likely to be not their fault but Brave's adblocker fault!

**Comment by antonok-edm** [comment]
(transfered to `brave-browser` repo, as it's more appropriate here)

**Comment by tn1997tn** [comment]
Windows 10 Brave latest. I didn't visit youtube very quickly. After reading news for a while (long enough), I opened youtube. Ads is always show up at the beginning of the videos, not randomly. And I always use private window (but it shows ads on normal window too if you wanted to know).

**Comment by ryanbr** [comment]
https://www.youtube.com/watch?v=KXJZ44FJOk8  (tested in a clean Brave profile). 

Searching on a US vpn, "Movies with ads" is easy replicate ads. I only saw ads when "Allowing ads" in shields here @tn1997tn

**Comment by tn1997tn** [comment]
I have never choose "Allowing ads" and always set to "Aggressive".

**Comment by ryanbr** [comment]
> I have never choose "Allowing ads" and always set to "Aggressive".

I'm just showing, that I only see ads when I change my shields to "Allow", was just a demonstration. Can you install Brave Beta and test that (uses a new profile)

**Comment by antonok-edm** [comment]
@tn1997tn interesting, that's helpful to know, thanks. One more piece of info that'd be useful is if you can open the console in the [dev tools](https://developer.chrome.com/docs/devtools/open/) and type in `JSON.parse`, and say whether that evaluates to `ƒ parse() { [native code] }` or `Proxy {length: 2, name: 'parse'}`.

**Comment by tn1997tn** [comment]
> @tn1997tn interesting, that's helpful to know, thanks. One more piece of info that'd be useful is if you can open the console in the [dev tools](https://developer.chrome.com/docs/devtools/open/) and type in `JSON.parse`, and say whether that evaluates to `ƒ parse() { [native code] }` or `Proxy {length: 2, name: 'parse'}`.

It's `ƒ parse() { [native code] }`.

**Comment by tn1997tn** [comment]
Update: EasyList alone is unable to block youtube ads (I'm using Fanboy Ultimate which included EasyList). After I added all the UbO's filters you normally see enabled by default on UbO then the youtube ads is no longer displayed.

**Comment by rishiraj88** [comment]
> Update: EasyList alone is unable to block youtube ads (I'm using Fanboy Ultimate which included EasyList). After I added all the UbO's filters you normally see enabled by default on UbO then the youtube ads is no longer displayed.

Oh! 
Thanks, @tn1997tn, for testing and sharing the details here.

**Comment by tn1997tn** [comment]
Update: the filter rules on wiki (https://github.com/easylist/easylist/wiki/Youtube-Issues) indeed worked. I didn't try to add them manually because that wiki said they are already included as part of Fanboy Annoyances (I'm using Fanboy Ultimate which included Fanboy Annoyances). For some unknown reasons, you need to add the filter rules on wiki manually for it to work. Long story short, you don't need to add the UbO filters.

**Comment by bsclifton** [comment]
Closing as stale - issues have been addressed, let's open a new issue for any new items 😄 Thanks
