### ISSUE TITLE
Move Aurora to the top of preloading network list (after mainnet)

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#27227]

**Comment by kjozwiak** [comment]
The above requires `1.46.141` or higher for `1.46.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.46.141 Chromium: 108.0.5359.99 (Official Build) (64-bit)
-- | --
Revision | `410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}`
OS | Windows 11 Version 22H2 (Build 22623.1028)

- Verified steps from [brave/brave-core#16283](https://github.com/brave/brave-core/pull/162830)
- Verified Aurora network is listed at the top of secondary networks and below Ethereum Mainnet

<video src=https://user-images.githubusercontent.com/17010094/206725999-d2b4c58e-13e6-49c1-b127-6309dc65ff8f.mov> | ![image](https://user-images.githubusercontent.com/17010094/206725876-23c9a8b7-62cf-41eb-b751-c64cf3fd4c21.png)
-- | --

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.46.141 x64 build
- Verified steps from [brave/brave-core#16283](https://github.com/brave/brave-core/pull/162830)
- Verified Aurora network is listed at the top of secondary networks and below Ethereum Mainnet

https://user-images.githubusercontent.com/17010094/206727641-75277d6b-6485-4faf-8ca6-8a476916b993.mp4
