### ISSUE TITLE
Follow up to move windows related code under win folder for BraveVPN

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#27237]
Follow - up form https://github.com/brave/brave-core/pull/15915 review comments:
- https://github.com/brave/brave-core/pull/15915#discussion_r1033953175
- https://github.com/brave/brave-core/pull/15915#discussion_r1033974096
- https://github.com/brave/brave-core/pull/15915#discussion_r1033982207

**Comment by kjozwiak** [comment]
The above requires `1.47.138` or higher for `1.47.x` verification 👍

**Comment by stephendonner** [comment]
## Verification `PASSED` using <html>

Brave | 1.47.145 Chromium: 109.0.5414.46 (Official Build) beta (64-bit)
-- | --
Revision | 6e36b77363ef3febbe792af680fa1367993ddcf0-refs/branch-heads/5414@{#709}

### Tested the following major-functionality pieces:
* purchased, configured, and connected to `BraveVPN`
* switched server regions
* DNS leak regression tests, with and without DoH

#### Confirmed all the above were working as expected

example | example | example | example | example | example | example
----------|-----------|----------|-----------|-----------|----------|----------
![1](https://user-images.githubusercontent.com/387249/209429406-d01a17fa-0334-4fe1-a58d-1a79559a79a1.png) | ![2](https://user-images.githubusercontent.com/387249/209429407-56d3021e-2ce5-4a39-a7f0-35058330a910.png) | ![3](https://user-images.githubusercontent.com/387249/209429408-b447a0ae-41e4-4499-979b-9d64750b1ab0.png) | ![4](https://user-images.githubusercontent.com/387249/209429409-6ff4d1ee-eeee-4059-9f7b-8a73cbd83cfb.png) | ![5](https://user-images.githubusercontent.com/387249/209429410-2cabfe25-44ee-4542-bc0d-214703453291.png) | ![6](https://user-images.githubusercontent.com/387249/209429411-27686d35-67e2-46e9-b6fe-dec8fa5b35ca.png) | ![7](https://user-images.githubusercontent.com/387249/209429412-e025d967-6c1e-44d8-935e-54bab81accfd.png)
