### ISSUE TITLE
Follow up of #26861: After removing custom filters and running the script, element blocks are still blocked

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#27243]
## Steps to Reproduce

1. Install 1.47.115
2. launch Brave
 3. open `brave://adblock` and add following and click `Save changes` button
 ```
        ##.blocked-class-1
        ##.blocked-class-2
        ##.blocked-class-3
```
5. visit `example.com` site 
6. Open dev tools console
3. run the script in step 3 from https://github.com/brave/brave-browser/issues/26861#issuecomment-1335605869
5. wait till `Done! Scroll to the end to check if there is any visible new element` is shown in the console
7. confirmed dynamically added blocks are blocked as expected
8. return to `brave://adblock` and remove custom filters from above step 3 
9. click `Save changes` button
10. refresh `example.com` site
11. run the script from step 3
12. wait till `Done! Scroll to the end to check if there is any visible new element` is shown in the console

## Actual result:

Ex1|Ex2
---|----
<img width="450" alt="image" src="https://user-images.githubusercontent.com/98358127/206552980-a519bb5a-34f4-4bcb-a75b-50a1a8bef3cc.png">|<img width="952" alt="image" src="https://user-images.githubusercontent.com/98358127/206553007-6b47bbfd-a361-4504-ba95-289db75f4f84.png">

![2022-12-08_12h29_15](https://user-images.githubusercontent.com/98358127/206553552-9581fcc0-cc37-49f2-bde6-f8383ce7c7d4.gif)

## Expected result:
The dynamically added elements blocks are not blocked

ex1|ex2|ex3|ex4
----|----|----|----
<img width="455" alt="image" src="https://user-images.githubusercontent.com/98358127/206553702-326089b8-c286-4743-9c0b-0221a5db7ff0.png">|<img width="901" alt="image" src="https://user-images.githubusercontent.com/98358127/206553745-d1010431-7250-4454-94c6-13dc64543856.png">|<img width="894" alt="image" src="https://user-images.githubusercontent.com/98358127/206553785-be6879db-1f93-4e24-93a3-576976c88a1a.png">|<img width="894" alt="image" src="https://user-images.githubusercontent.com/98358127/206553862-5a90ee0a-b352-4e9a-af63-5b504c7b8722.png">

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.47.115 Chromium: 108.0.5359.94 (Official Build) beta (64-bit)
-- | --
Revision | 713576b895246504ccc6b92c2fb8ce2d60194074-refs/branch-heads/5359_71@{#3}
OS | Windows 11 Version 21H2 (Build 22000.1219)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release?  yes
- Can you reproduce this issue with the beta channel?  yes
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
 @antonok-edm @rebron 
cc: @brave/qa-team

**Comment by rebron** [comment]
@MadhaviSeelam Can you check to see if a browser restart, keeps the expected changes.

**Comment by antonok-edm** [comment]
Actually... this might be an issue with the empty filters list. If a filter list is empty, it won't get updated when saving. This is because of a slightly hacky workaround that should be [fixed](https://github.com/brave/brave-core/pull/16340/files#diff-f6ae5952d28d80ae1dc659bdf18e47f35c4a2912676671ec7bcad84ffed7cfb3R92) when we merge https://github.com/brave/brave-core/pull/16340.

@MadhaviSeelam if you'd like to confirm, try again but make sure the custom filters list isn't empty the second time. For example you could just add a single `!` (comment character) in the box.
