### ISSUE TITLE
Auto discovering Solana assets 

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#27246]
SPL tokens on the Brave Wallet token list will be automatically added to user’s portfolio when they have a positive balance.
Should be doable via:
https://docs.solana.com/developing/clients/jsonrpc-api#gettokenaccountsbyowner

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.49.106 x64 Beta build
- Verified steps from [brave/brave-core#16530](https://github.com/brave/brave-core/pull/16530)
- Verified Solana assets are auto-discovered and listed 
- Verified Solana asset discovery works on importing an account via private key
- Verified Solana asset discovery works on restoring a seed 
- Verified Solana asset discovery works when adding a new account
- Verified on a new wallet it loads the default native token 
----------
Verification passed on Samsung Tab A with Android 10 running 1.49.106 x64 Beta build
- Verified steps from [brave/brave-core#16530](https://github.com/brave/brave-core/pull/16530)
- Verified Solana assets are auto-discovered and listed 
- Verified Solana asset discovery works on importing an account via private key
- Verified Solana asset discovery works on restoring a seed 
- Verified Solana asset discovery works when adding a new account
- Verified on a new wallet it loads the default native token

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta  (64-bit) 
-- | --
Revision | `46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}`
OS | Linux

- Verified steps from [brave/brave-core#16530](https://github.com/brave/brave-core/pull/16530)
- Verified Solana assets are auto-discovered and listed 
- Verified Solana asset discovery works on importing an account via private key
- Verified Solana asset discovery works on restoring a seed 
- Verified Solana asset discovery works when adding a new account
- Verified on a new wallet it loads the default native token 

---------------------

Verification passed on 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta  (64-bit)
-- | --
Revision | `46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#16530](https://github.com/brave/brave-core/pull/16530)
- Verified Solana assets are auto-discovered and listed 
- Verified Solana asset discovery works on importing an account via private key
- Verified Solana asset discovery works on restoring a seed 
- Verified Solana asset discovery works when adding a new account
- Verified on a new wallet it loads the default native token 

---------------------

Verification passed on 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta  (arm64)
-- | --
Revision | `46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#16530](https://github.com/brave/brave-core/pull/16530)
- Verified Solana assets are auto-discovered and listed 
- Verified Solana asset discovery works on importing an account via private key
- Verified Solana asset discovery works on restoring a seed 
- Verified Solana asset discovery works when adding a new account
- Verified on a new wallet it loads the default native token
