### ISSUE TITLE
[Android] Tablet: Blur/darken area that's not being used when tipping banner is visible

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#27251]
## Description 

As per https://github.com/brave/brave-browser/issues/26739#issuecomment-1317148394, we should either blur or darken the area that's not currently active when the tipping banner is visible on tablet devices. With the current implementation, there's too much going at once which might confuse the users re: which UI elements they should be interacting with.

## Steps to reproduce 

   1. install brave that has https://github.com/brave/brave-core/pull/16081 (used `1.48.24 Chromium: 108.0.5359.71`)
   2. enable staging via `Hamburger Menu` -> `Settings` -> `Developer options`
   3. restart the browser and enable rewards via the rewards panel (accept the ~30 BAT ads grant)
   4. visit https://laurenwags.github.io and tap on the BAT icon (initiate a tip so the tipping banner is visible)

## Actual result 

**`Example`** | **`Example`**
----------------|----------------
![Screenshot_20221208_145312_Brave - Nightly](https://user-images.githubusercontent.com/2602313/206555880-144308d5-f087-4b5c-a030-f081bc0c430b.jpg) | ![Screenshot_20221208_145320_Brave - Nightly](https://user-images.githubusercontent.com/2602313/206555889-c0a66c0a-b276-45fa-83e6-de42adf1b111.jpg)

## Expected result

Should either blur or darken the above area to improve UX and show the user which UI elements they should be interacting with.

## Issue reproduces how often 

100% reproducible when using/running through the STR mentioned above.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `No`
- Can you reproduce this issue with the current Play Store Beta version? `Yes`
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

This will be on `Release` once we push out the `1.46.x` maintenance release.

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Samsung Galaxy Tab S8 Ultra` (Tablet)
   - Android version: `Android 13`
   
## Brave version

```
Brave | 1.48.24 Chromium: 108.0.5359.71 (Official Build) canary (32-bit)
--- | ---
Revision | 1e0e3868ee06e91ad636a874420e3ca3ae3756ac-refs/branch-heads/5359@{#1016}
OS | Android 13; Build/TP1A.220624.014
```

### Website problems only

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by anatolydsgn** [comment]
@Miyayes Could you use this scrim #000000 with opacity: 30% as an example? https://www.figma.com/file/EDGI52tfWG1ggC9ZYFguXy/Tipping-Banner?node-id=4893%3A61656&t=wlBkkj4DiJEd8UGN-1

**Comment by Miyayes** [comment]
Superseded by Tip Banner 3.0.
