### ISSUE TITLE
Update cross-custodial tipping notice text

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#27254]
## Description

Update cross-custodial text to:

## Case 1: Rewards panel

![image](https://user-images.githubusercontent.com/11497541/206571551-08dfda28-925e-40a9-9688-2ec691cf1cf1.png)

>**You're connected to {{user's custodian}}, but this creator is connected to {{creator's custodian}}. This means your tip can't reach this creator.** For now, any tip you make will remain pending and retry automatically for 90 days. 

## Case 2: Tipping banner

![image](https://user-images.githubusercontent.com/11497541/206571619-6bc83901-09e3-49a9-8d50-3aaa172d0ff6.png)

>You're connected to {{user's custodian}}, but this creator is connected to {{creator's custodian}}. This means your tip can't reach this creator. For now, any tip you make to this creator will remain pending and retry automatically for 90 days. 

cc: @rmcfadden3

**Comment by rmcfadden3** [comment]
Would recommend a slight tweak to something like:

`Note: You're connected to {{user's custodian}}, but this creator is connected to {{creator's custodian}}. This means Brave can’t connect you. Your tip will remain pending, and retry automatically for 90 days.`

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.48.125 Chromium: 109.0.5414.87 (Official Build) beta (x86_64)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | macOS Version 12.6.2 (Build 21G320)
```
