### ISSUE TITLE
Onboarding P3A opt-in checkbox does not work

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#27253]
## Description 

The P3A opt-in checkbox embedded in the new desktop onboarding UI does not correctly set the P3A preference. If the checkbox is checked, P3A is not enabled.

## Steps to Reproduce

   1. Start with fresh profile
   2. Go through onboarding and ensure P3A checkbox is checked.
   3. Examine P3A preference in the browser settings.

## Actual result:

P3A is disabled.

## Expected result:

P3A should be enabled.

## Reproduces how often: 

Easily

## Desktop Brave version:

1.47 and up

cc @nullhook

**Comment by GeetaSarvadnya** [comment]
Reproduced on `Windows 10 x64 - 1.47.115`

```

Brave | 1.47.115 Chromium: 108.0.5359.94 (Official Build) beta (64-bit)
-- | --
Revision | 713576b895246504ccc6b92c2fb8ce2d60194074-refs/branch-heads/5359_71@{#3}
OS | Windows 10 Version 21H2 (Build 19044.2251)

```

**Comment by kjozwiak** [comment]
The above requires `1.47.131` or higher for `1.47.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.47.149 Chromium: 109.0.5414.46 (Official Build) beta (64-bit)
-- | --
Revision | 6e36b77363ef3febbe792af680fa1367993ddcf0-refs/branch-heads/5414@{#709}
OS | Windows 10 Version 21H2 (Build 19044.2364)

```
