### ISSUE TITLE
[Android] Add drop shadow around Rewards dropdown panel

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#27257]
## Description

The Rewards dropdown panel melds into the underlying webpage on Android because there is no dropshadow separating it from the background:

![image](https://user-images.githubusercontent.com/11497541/206590200-e39f05ac-95bb-4df0-a532-f58f93a6b964.png)

It should be more like desktop, where there's a dropshadow that sets it apart: 

![image](https://user-images.githubusercontent.com/11497541/206590253-b8b6013d-1b4d-49de-bdb1-fa2200c0a9a3.png)

**Comment by Miyayes** [comment]
Android 6/7 APIs different, so we need to make sure it works on all the devices.

**Comment by stephendonner** [comment]
## Verified `PASSED` on `Google Pixel XL` (`arm64`) running `Android 9`:

```
Brave	1.52.102 Chromium: 113.0.5672.126 (Official Build) beta (32-bit)
Revision	c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}
OS	Android 9; Build/PQ2A.190305.002; 28; REL
```

### Steps:
1. installed `1.52.102`
2. launched Brave
3. enabled Rewards staging via `QA Debug` menu
4. relaunched Brave
5. logged into `Uphold's` staging sandbox
6. loaded `laurenwags.github.io`
7. tapped on the `Rewards` icon
8. tapped to enable Rewards
9. tapped again to invoke the dropdown Rewards panel

### Confirmed the dropshadow is now present around the panel

`1.52.102` | `1.51.114`
-----------|----------
![Screenshot_20230518-125009](https://github.com/brave/brave-browser/assets/387249/77467487-fe89-4918-93f4-b45aa0dc3037) | ![Screenshot_20230518-125219](https://github.com/brave/brave-browser/assets/387249/cc09dfa1-a0db-4485-910e-b0c4bc1692fe)

**Comment by vlad-hoff** [comment]
Verified on `Nexus 5X`, `Galaxy Tab S8` and `Google Pixel 7` using version(s):
```
Device/OS: 
- Google Nexus 5X [Android 6.0; Android 7.1.1; Android 8.1]
- SM-X700 Galaxy Tab S8 [gts8wifixx-user 13 TP1A.220624.014 release-keys]
- Google Pixel 7 [panther_beta-user 13 UPB2.230407.014 release-keys]
Brave build: 1.52.102
Chromium: 113.0.5672.126 (Official Build) beta (64-bit)
Revision: c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}
```
Filed follow-up issue #30495
---------------------------

**STEPS:**
1. Install build 1.52.102
2. Launch Brave > Hamburger Menu > Settings
3. Enable Rewards Staging via QA Debug menu > Relaunch Brave
4. Tap on the Rewards icon > Enable Rewards
5. Connect account > Sign in to Uphold or Gemini account
6. Open wikipedia.com, for example
7. Tap Rewards icon to invoke the dropdown Rewards panel

**ACTUAL RESULTS:**
- Verified that drop shadow is shown for the Rewards panel in Light and Dark Modes

<details>
<summary> Android 6 - Not supported </summary>

|1|
|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/6c2053af-9f6a-4bf0-b5b2-5b4b4653faeb) |
</details>

<details>
<summary> Android 7 - PASS </summary>

|Light Mode|
|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/2878728c-5220-46ff-ac94-6aa0cd91d8e1) |
</details>

<details>
<summary> Android 8 - PASS </summary>

|Light Mode|Dark Mode|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/14630656-73cd-424e-a82d-17ce70fb4341) |
</details>

<details>
<summary> Android 13 - PASS </summary>

|Light Mode|Dark Mode|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/20f77b0e-41fe-4131-8d2c-51cbd404466f) | ![2](https://github.com/brave/brave-browser/assets/128532965/e0ab773b-be65-4d31-b121-6a4a71d05cf1) |
</details>

<details>
<summary> Android 14 - PASS </summary>

|Light Mode|Dark Mode|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/c8e465ca-3f74-49e9-982e-e94b665647cb) | ![2](https://github.com/brave/brave-browser/assets/128532965/e1689e22-8c34-4936-a56f-ac301305443e) |
</details>
