### ISSUE TITLE
[Android] Update cross-custodial tipping notice text

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#27255]
Android version of: https://github.com/brave/brave-browser/issues/27254

**Comment by GeetaSarvadnya** [comment]
Verified the issue on `Vivo X70 Pro version 12` against the build `Bravemonoarm64.apk_1.50.90`

Issue is NOT fixed, logged a follow up issue https://github.com/brave/brave-browser/issues/29080

**Comment by GeetaSarvadnya** [comment]
Removed `QA/Yes` label as the follow issue is logged https://github.com/brave/brave-browser/issues/29080
