### ISSUE TITLE
Broken images on sync - Add devices popup

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#2726]
## Description 
Broken images on sync - Add devices popup

## Devices
Device 1: Windows 10 x64  (0.59.12)
Device 2: Android Samsung Galaxy 5.1 (1.0.71 (sync3))

## Steps to Reproduce

   1. Clean profile `0.59.12`
   2. Sync windows and Android
   3. Once sync is established between two devices, click on add devices

## Actual result:
![image 11](https://user-images.githubusercontent.com/38657976/50399500-ee44df00-07a5-11e9-9f41-a5d8c33d3ee7.png)

## Expected result:
Should not be any broken mages

## Reproduces how often: 
Always

## Brave version (brave://version info)

Brave | 0.59.12 Chromium: 72.0.3626.17 (Official Build) beta (64-bit)
-- | --
Revision | 08d2140079f8db14c9eb885a803d231b1a30e817-refs/branch-heads/3626@{#315}

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Yes, reproducible on Dev latest build

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional Information
@brave/legacy_qa

**Comment by kjozwiak** [comment]
@GeetaSarvadnya are you still seeing this with `0.59.20 Chromium: 72.0.3626.28 (Official Build) beta`?

**Comment by GeetaSarvadnya** [comment]
@kjozwiak Issue is not reproducible on latest beta build `0.59.21 Chromium: 72.0.3626.28`. Hence closing the issue.

**Comment by kjozwiak** [comment]
Awesome, thanks for double checking @GeetaSarvadnya 👍
