### ISSUE TITLE
Don't go disconnected state while changing region

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#27267]
## Steps to Reproduce

   1. Set purchased state
   2. Connect to any region
   3. Change to another region

## Actual result:

https://user-images.githubusercontent.com/6786187/206682491-ba7fd500-8c14-49f9-b39c-c4f586bc7b08.mov

## Expected result:

https://user-images.githubusercontent.com/6786187/206682542-ddc86427-c5ce-4aee-a7ec-92c00b8f33ae.mov

## Reproduces how often: 

Easily

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.47.130` or higher for `1.47.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.47.132 Chromium: 108.0.5359.128 (Official Build) beta (x86_64)
-- | --
Revision | 1cd27afdb8e5d057070c0961e04c490d2aca1aa0-refs/branch-heads/5359@{#1185}
OS | macOS Version 11.7.2 (Build 20G1020)

Followed the steps to reproduce in the description.

#### Confirmed when changing regions while connected, it goes `Connected` -> `Disconnecting...` -> `Connecting...` -> `Connected`

![vpn-region-change](https://user-images.githubusercontent.com/387249/208236912-d4b88b86-7bd6-4460-8274-6c195e7b66a5.gif)
