### ISSUE TITLE
Ads Blocked count doesn't stop counting

### ISSUE THREAD

**Issue by sdpolke** [brave/brave-browser#2727]
Similar to #426 

## Description 
Ads Blocked count goes into infinite loop. Not for every website but pages on a certain websites.  

## Steps to Reproduce

   1. Open Browser 
   2. Open sample link http://overdrive.in/reviews/2018-bmw-g-310-r-road-test-review/ or other links on website
   3. Observe the continuous increase of Advt blocking count by opening a new tab

## Actual result:
Ad block count is increasing infinitely

## Expected result:
Once advertisement is blocked, the count should stop increment

## Reproduces how often: 
Every time 

## Brave version (brave://version info)
Version 0.55.20 on Windows 10 1607

![brave-issue](https://user-images.githubusercontent.com/968229/50399728-842d3980-07a7-11e9-8160-ae2421d549da.gif)

**Comment by srirambv** [comment]
You are on a really old version of Brave. Please upgrade to the new version which has the fix

**Comment by sdpolke** [comment]
![capture](https://user-images.githubusercontent.com/968229/50465954-b960a400-09c0-11e9-9e33-d4ebfa26310d.PNG)

I hope this helps. It's the Latest version.

**Comment by srirambv** [comment]
Not really that isn't the latest version. The most recent version is `0.58.18`. You can download the build from [here](https://github.com/brave/brave-browser/releases/tag/v0.58.18) and update manually. Your browser is 3 versions behind the current stable build.
