### ISSUE TITLE
NFT asset details screen

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#27276]
![Screen Shot 2022-12-09 at 10 03 22 AM](https://user-images.githubusercontent.com/318119/206743093-4c5ed738-e854-4f93-82c5-f951aa30f0e5.png)

![simulator_screenshot_B8C8929E-533B-4A05-8895-D8AAFAA712ED](https://user-images.githubusercontent.com/318119/206742527-c1a32d09-bd85-4464-9567-b8611b607a75.png)

Match iOS on NFT display:
- Reuse asset details screen and remove the graph for NFTs.
- Display additional labels needed for metadata: description, collection, etc.
- Display accounts and transactions related to the NFT

**Comment by kjozwiak** [comment]
The above requires `1.48.151` or higher for `1.48.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.48.155 x64 build
- Verified steps from [brave/brave-core#16671](https://github.com/brave/brave-core/pull/16671)
- Verified NFT asset details view is shown when clicked on the NFT
- Verified clicking on the Token ID loads the NFT's page on blockexplorer
- Verified able to view both Solana NFT and Ethereum NFT
- Encountered [#28202](https://github.com/brave/brave-browser/issues/28202)

Oppo Reno 5 (Android 13) | Lenovo Tab (Android 12)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/216903369-4347a5ee-5418-44b7-9d29-c3214ee8950e.mp4> | <video src=https://user-images.githubusercontent.com/17010094/216901807-7194fc12-32b3-4ed2-b15d-946b08390bb4.mp4>
