### ISSUE TITLE
Add help centre link to the wallet

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#27270]
## Description 
Right now we have a help centre link on desktop, I would like to see this on Android as well. Maybe we can insert it on this dropdown 

![Screenshot 2022-12-09 at 14 48 21](https://user-images.githubusercontent.com/12224304/206716622-f771c832-919b-415f-9a51-8264bc75de62.png)

## Steps to reproduce 

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1675951645322039

**Comment by HEagle18** [comment]
cc @kleantzogu

**Comment by HEagle18** [comment]
<img width="262" alt="Screenshot 2023-02-09 at 15 15 24" src="https://user-images.githubusercontent.com/12224304/217837408-b60e3b99-9f5c-4770-9a07-e3ebe928f6b6.png">
<img width="294" alt="Screenshot 2023-02-09 at 15 15 32" src="https://user-images.githubusercontent.com/12224304/217837448-3953d265-7dfc-40aa-ad20-094c34b465e8.png">

What it looks like on desktop

**Comment by kleantzogu** [comment]
Figma link: https://www.figma.com/file/ZK2POu5oNDFtOoz3Xpr9mi/%F0%9F%93%B1-Help-Center?node-id=1701%3A25802&t=r7T7XPSQ5I0j3TVx-4

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.58.93 x64 Beta build
- Verified steps from [brave/brave-core#19692](https://github.com/brave/brave-core/pull/19692)
- Verified Help Centre link is available in Wallet setting and Panel settings

Oppo Reno 5 (Android 13) | Lenovo Tab (Android 12)
-- | --
<video src=https://github.com/brave/brave-browser/assets/17010094/99cbe788-f901-48da-8e27-e793d810d534> | <video src=https://github.com/brave/brave-browser/assets/17010094/0254bd3e-bf43-4643-a187-ef4d467a8f77>
