### ISSUE TITLE
Remove getOrignalProfile() from search utils

### ISSUE THREAD

**Issue by wchen342** [brave/brave-browser#27273]
Context: https://bravesoftware.slack.com/archives/C7VLGSR55/p1670000442736269

QA please test the same as brave/brave-core/pull/15704.

**Comment by kjozwiak** [comment]
Going to label the above as `QA/No` as the above will be verified when we run through https://github.com/brave/brave-core/pull/15704. Similar to what was verified on Nightly via https://github.com/brave/brave-core/pull/15704#issuecomment-1358907472 before https://github.com/brave/brave-core/pull/16316 was uplifted into `1.47.x`.
