### ISSUE TITLE
Getting zero fee for Solana dapps transactions on testnet (Android)

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#27274]
## Description 
On `testnet`, [Android is getting 0 as fee](https://github.com/brave/brave-core/blob/4f507e4d5f7b1689bd9d5014ea0adffc8411bae3/android/java/org/chromium/chrome/browser/crypto_wallet/util/SolanaTransactionsGasHelper.java#L64) for Solana DApps transaction fee estimations but iOS and [desktop](https://github.com/brave/brave-core/blob/784430b81a18ca6f4a7c55c0eb485ec98d461114/components/brave_wallet_ui/common/async/handlers.ts#L437) are getting ` .000005 SOL` as fee.

[sol-fee.webm](https://user-images.githubusercontent.com/11755381/206736294-7bcf35ff-2f78-4750-af97-e6fc50704832.webm)

## Expected result
Android should get the Solana transaction fee.

**Comment by simoarpe** [comment]
Solana DApps transactions work correctly.
Currently, there is no API for DApps to trigger network changes or detect network mismatched. When the network doesn't match, the fee is set to zero.

When the corresponding network is selected the fee is correctly added, I'm attaching a short demo.
The behavior is consistent with Desktop implementation.
I'm closing this issue.

https://github.com/brave/brave-browser/assets/3308503/39d3db29-f0b3-409d-9a8d-340882e90217
