### ISSUE TITLE
HTTPS/SSL Certificate

### ISSUE THREAD

**Issue by DonBolli** [brave/brave-browser#27284]
I have local node for Bitcoin, so there is no valid HTTPS/SSL Certificate, to be honest I do not fully understand the mechanism.
My node offers the possibility to download the certificate, so I did. I wanted to import it to brave. Under my certifcatses ("Meine Zertifikate") i get an error "Der private Schlüssel für dieses Clientzertifikat fehlt oder ist ungültig" so i thought maybe under server. There is no error but nothing happens at all

Steps to repoduce

   1. Take .cert file (I don't know if it is just mine)
   2. Try to import

## Actual result:
Nothing happens

## Expected result:
Import certificates

## Reproduces how often: 
Everytime i tried it, and this was often

## Brave version (brave://version info)
Brave | 1.46.138 Chromium: 108.0.5359.94 (Offizieller Build) (64-Bit)
-- | --
Überarbeitung | 713576b895246504ccc6b92c2fb8ce2d60194074-refs/branch-heads/5359_71@{#3}
Betriebssystem | Linux
JavaScript | V8 10.8.168.21
User-Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Befehlszeile | /opt/brave.com/brave/brave --disable-domain-reliability --enable-dom-distiller --component-updater=url-source=https://go-updater.brave.com/extensions --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --variations-insecure-server-url=https://variations.brave.com/seed --flag-switches-begin --flag-switches-end --desktop-startup-id=cinnamon-1778-computer-/usr/bin/brave-browser-stable-0_TIME308535
Programmdateipfad | /opt/brave.com/brave/brave
Profilpfad | /home/donbolli/.config/BraveSoftware/Brave-Browser/Default
Aktive Variationen | AdRewardsStudy:NextPaymentDayAllowCertainClientHintsStudy:EnabledBraveAdblockCookieListOptInReleaseStudy:EnabledBraveAds.AdServingStudy:DefaultAdNotificationsPerHour=10/MaximumAdNotificationsPerDay=100/MaximumInlineContentAdsPerHour=12/MaximumInlineContentAdsPerDay=60/AdServingVersion=2BraveAds.UserActivityStudy:Triggers=NTPSI/TimeWindow=15m/Threshold=0.0/IdleTimeThreshold=5sBraveDebounceStudy:EnabledBraveRewardsWebUiPanelStudy:EnabledBraveScreenFingerprintingBlockerStudy:DefaultConversionsStudy:NewDefaultPatternDefault1pBlockingStudy:DisabledDisableReduceLanguage:EnabledEphemeralStorageStudy:EnabledFirstPartyEphemeralDomainBlockStudy:EnabledForceDisableBlinkFeatures:EnabledPartitionBlinkMemoryCacheStudy:EnabledPartitionConnectionsByNetworkIsolationKeyStudy:EnabledPermissionLifetimeReleaseStudy:EnabledSpeedreaderReleaseStudy:Enabled

## Version/Channel Information:

- Can you reproduce this issue with the current release?  (yes)
- Can you reproduce this issue with the beta channel? (not tested)
- Can you reproduce this issue with the nightly channel? (not tested)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? (not available in settings)
- Does the issue resolve itself when disabling Brave Rewards? (not available in settings)
- Is the issue reproducible on the latest version of Chrome? (I do not have Chrome)

## Miscellaneous Information:
![Bildschirmfoto vom 2022-12-09 22-11-52](https://user-images.githubusercontent.com/43571844/206797432-66c2d05a-b9b0-4744-aa2c-a15730c0b673.png)

**Comment by rebron** [comment]
Closing per last comment.
