### ISSUE TITLE
Support websocket inspection in the devtools

### ISSUE THREAD

**Issue by theogravity** [brave/brave-browser#27286]
## Description 

The devtools does not have a websocket inspector. As a dev, I'd like to inspect active websockets like I can with Chrome.

## Steps to Reproduce

- Open the inspector
- Go to `Network`
- There is no option to view websocket connections

## Actual result:

Brave:

<img width="863" alt="image" src="https://user-images.githubusercontent.com/855434/206819502-58965ef2-2af3-45a0-b8a0-c93a3202ed30.png">

## Expected result:

Chrome:

<img width="541" alt="image" src="https://user-images.githubusercontent.com/855434/206819491-a9409a90-4ca8-4230-b5fb-bbaf7b3c80de.png">

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
```


Brave | 1.45.133 Chromium: 107.0.5304.141 (Official Build) (x86_64)
-- | --
Revision | cddb1ab381a982f400a57e15e14080e1aaaca4b8-refs/branch-heads/5304_105@{#3}
OS | macOS Version 13.0.1 (Build 22A400)
JavaScript | V8 10.7.193.22
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Command Line | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser --disable-domain-reliability --enable-dom-distiller --component-updater=url-source=https://go-updater.brave.com/extensions --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --variations-insecure-server-url=https://variations.brave.com/seed --flag-switches-begin --flag-switches-end
Executable Path | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path | /Users/theo/Library/Application Support/BraveSoftware/Brave-Browser/Default
Linker | lld
Active Variations | AdRewardsStudy:NextPaymentDayAdvertiserSplitTestStudy:GroupAAllowCertainClientHintsStudy:EnabledBraveAdblockCookieListOptInReleaseStudy:EnabledBraveAds.AdServingStudy:DefaultAdNotificationsPerHour=10/MaximumAdNotificationsPerDay=100/MaximumInlineContentAdsPerHour=12/MaximumInlineContentAdsPerDay=60/AdServingVersion=1BraveAds.FrequencyCappingStudy:ExcludeAdIfWithinTimeWindow=0hBraveAds.UserActivityStudy:Triggers=NTPSI/TimeWindow=15m/Threshold=0.0/IdleTimeThreshold=5sBraveDebounceStudy:EnabledBraveRewardsWebUiPanelStudy:EnabledBraveScreenFingerprintingBlockerStudy:DefaultConversionsStudy:NewDefaultPatternDefault1pBlockingStudy:DisabledDisableReduceLanguage:EnabledEphemeralStorageStudy:EnabledFirstPartyEphemeralDomainBlockStudy:EnabledForceDisableBlinkFeatures:EnabledMacCoreLocationBackendStudy:EnabledPartitionBlinkMemoryCacheStudy:EnabledPartitionConnectionsByNetworkIsolationKeyStudy:EnabledPermissionLifetimeReleaseStudy:EnabledSpeedreaderReleaseStudy:Enabled
```

**Comment by rebron** [comment]
cc: @goodov

**Comment by goodov** [comment]
It should appear if you press this button:
![image](https://user-images.githubusercontent.com/5928869/208047488-a2a271ae-b48b-4f2b-93bd-80ee8ec40761.png)

https://user-images.githubusercontent.com/5928869/208047760-f96ed028-9ea0-4126-a115-0468ab7d820d.mp4

**Comment by theogravity** [comment]
I think I understand why I missed this. The filter icon remains red regardless of the toggled state, so from my POV, the filter was already enabled

<img width="860" alt="image" src="https://user-images.githubusercontent.com/855434/208184625-e404c7de-af0c-4fd4-af8f-7216f61b48b0.png">

**Comment by goodov** [comment]
> I think I understand why I missed this. The filter icon remains red regardless of the toggled state, so from my POV, the filter was already enabled

actually you're right! this is a bug. I checked in Chromium, and it display active/inactive states properly.

**Comment by bsclifton** [comment]
@goodov should we re-open since the display state is wrong?

**Comment by goodov** [comment]
> @goodov should we re-open since the display state is wrong?

There's already a separate issue for an incorrect button color: https://github.com/brave/brave-browser/issues/27437
