### ISSUE TITLE
Computer name is missing in Let’s sync a new device with “”.

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#2728]
## Description 
Computer name is missing in `Let’s sync a new device with “”.`

## Description 
Device 1: Windows 10 x64 (0.60.4 dev build)
Device 2: Android Samsung Galaxy 5.1 (1.0.71 (sync3))

## Steps to Reproduce

   1. Clean install 0.60.4
   2. Sync Windows and Android devices through QR code
   3.  Once sync is established between two devices, click on `Start new sync chain`

## Actual result:
![image 12](https://user-images.githubusercontent.com/38657976/50400890-919af180-07b0-11e9-8a63-b64ddbbfcf80.png)

![computer name missing](https://user-images.githubusercontent.com/38657976/50400910-ca3acb00-07b0-11e9-8fcb-83304ba4ef1a.gif)

## Expected result:
![image](https://user-images.githubusercontent.com/38657976/50400935-f35b5b80-07b0-11e9-9dc7-2f20ec9229ce.png)

## Reproduces how often: 
Easy

## Brave version (brave://version info)

Brave | 0.60.4 Chromium: 72.0.3626.17 (Official Build) dev (64-bit)
-- | --
Revision | 08d2140079f8db14c9eb885a803d231b1a30e817-refs/branch-heads/3626@{#315}
OS | Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? NA

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional Information
@brave/legacy_qa

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.59.18 Chromium: 72.0.3626.28 (Official Build) beta(64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/1191
* Verified STR from description
![screen shot 2019-01-04 at 1 56 45 pm](https://user-images.githubusercontent.com/28145373/50705397-b866ec80-1028-11e9-9ae9-3d36fd2eec5e.png)
