### ISSUE TITLE
Support `eth_subscribe` with `"logs"` param

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#27283]
Expand on the support added here for newHeads https://github.com/brave/brave-browser/issues/21350
The new support should support the `"logs"` param. 

To support "logs" we need to periodically call `JsonRpcService::EthGetLogs` as needed instead of using the `BlockTracker`.
Check metamask as the reference.

Heres some sample code to use in a JS console of any HTTPS page:
```
window.ethereum.on('message', (x, y, z) => console.log('message event: ', x, y, z))
window.ethereum.send({ id:1, method: 'eth_subscribe', params:['logs', {"address":  "0xD9C2ec046dBbDe5e670D27250cf3385300062C5d",  "topics":  ["0x2edcb8328dc82dc24d7a2b50a94f19db11146048d396320228feb7c79c3301e1"]}]}, console.log)
```

**Comment by vadimstruts** [comment]
Created issue: [27842](https://github.com/brave/brave-browser/issues/27842) that is follow up the current one

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta  (64-bit)
-- | --
Revision | `46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#16633](https://github.com/brave/brave-core/pull/16633)
- Verified `eth_subscribe` listens to logs and shows output every 20 secons
- Verified `eth_unsubscribe` stops logging 

https://user-images.githubusercontent.com/17010094/222137895-2dcd1f60-e72e-462e-89f1-0a235ac95906.mp4

**Comment by srirambv** [comment]
Verification passed on Lenovo Tab with Android 12 running 1.49.118 x64 build
- Verified steps from [brave/brave-core#16633](https://github.com/brave/brave-core/pull/16633)
- Verified `eth_subscribe` listens to logs and shows output every 20 secons
- Verified `eth_unsubscribe` stops logging 

https://user-images.githubusercontent.com/17010094/223700755-514f2d45-045f-48bd-b3d6-56477fabbfed.mp4
