### ISSUE TITLE
Brave browser opens two windows when using --tor flag

### ISSUE THREAD

**Issue by bigdiff** [brave/brave-browser#27288]
## Description 

When using the Brave browser with the --tor flag, the browser opens two windows instead of one. This can be confusing for users and may cause issues with navigation and browsing.

## Steps to Reproduce

   1. Use the command line to run Brave with the --tor flag (e.g. "brave --tor")
   2. Observe that two windows are opened instead of one

## Actual result:

When using the --tor flag, Brave should open only one window.

## Expected result:
Brave opens two windows when using the --tor flag.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

1.46.140 Chromium: 108.0.5359.99 (Official Build) (64-bit) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
	- Yes
- Can you reproduce this issue with the beta channel? 
	- Not tested
- Can you reproduce this issue with the nightly channel? 
	- Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
	- No
- Does the issue resolve itself when disabling Brave Rewards? 
	- No
- Is the issue reproducible on the latest version of Chrome? 
	- No as this feature only exists in brave not chrome.

## Miscellaneous Information:

![two tor browser windows after launching it from terminal with '--tor' option in terminal](https://user-images.githubusercontent.com/96084563/206849982-bf7bcda2-6e4c-4161-934f-b04abed90dc5.png)

**Comment by stephendonner** [comment]
Confirmed using 

Brave | 1.48.42 Chromium: 108.0.5359.99 (Official Build) nightly (x86_64)
-- | --
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | macOS Version 13.1 (Build 22C65)

<img width="1680" alt="Screenshot 2022-12-10 at 12 12 00 PM" src="https://user-images.githubusercontent.com/387249/206873621-7ec7222e-5bfd-46ff-a6bc-2db8dc80ef94.png">
