### ISSUE TITLE
Update sidebar config button url

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#27298]
## Description 

As we made separate sidebar section in brave://settings/appearance,
sidebar config button(located at the bottom of sidebar UI) should find with its section name(`Sidebar`) . 

## Steps to Reproduce

   1. Click sidebar config button
   2. Check loaded url
   3. 

## Actual result:

`brave://settings/?search=Show%20Sidebar` is loaded
![image](https://user-images.githubusercontent.com/6786187/206942299-da35927b-988d-4639-9170-65cda0c749e4.png)

## Expected result:
`brave://settings/?search=Sidebar` is loaded
![image](https://user-images.githubusercontent.com/6786187/206942216-45abf4f9-f64d-435a-82fe-938bdfc51fc3.png)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by simonhong** [comment]
cc @rebron

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.48.119 Chromium: 109.0.5414.80 (Official Build) beta (x86_64)
-- | --
Revision | 0f69b168d36a06cace4365e9f029fa987afa5633-refs/branch-heads/5414@{#1178}
OS | macOS Version 11.7.2 (Build 20G1020)

### Steps:
1. installed `1.48.119`
2. launched Brave
3. clicked on the `Settings` / gears icon on the lower left

#### Confirmed clicking on `Settings` went to `brave://settings/?search=Sidebar`

`brave://welcome` | `brave://settings/?search=Sidebar`
-------------------|-----------------------------------
<img width="1312" alt="Screen Shot 2023-01-10 at 9 55 34 AM" src="https://user-images.githubusercontent.com/387249/211626434-85b28b4a-a31d-4dd8-b20f-b302e54edd9b.png"> | <img width="1312" alt="Screen Shot 2023-01-10 at 9 55 42 AM" src="https://user-images.githubusercontent.com/387249/211626439-64e2bb90-2817-4015-82ea-78cf9c1cb437.png">
