### ISSUE TITLE
Rewards opt-in button is displayed on NTP settings when after has enabled Rewards

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#27307]
## Description 

The "Start Using Rewards" button is displayed on the "Background Image" tab in the NTP settings modal when the user has not yet enabled Rewards, or has not enabled Private Ads. If the user has chosen to hide the Rewards card on the NTP, the "Start Using Rewards" button will always be displayed.

## Steps to Reproduce

   1. Visit the NTP and hide the Rewards card.
   2. Close the NTP.
   3. Enable rewards in the rewards panel.
   4. Visit the NTP and show settings.
   5. Scroll down to the sponsored image toggle.

## Actual result:

The "Start Using Rewards" button is displayed.

## Expected result:

The "Start Using Rewards" button should not be displayed.

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by Miyayes** [comment]
Will share designs once ready.

**Comment by Miyayes** [comment]
I think this is resolved with @mkarolin's work https://github.com/brave/brave-browser/issues/27304.
