### ISSUE TITLE
Add import from Yandex browser

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#27301]
Add Yandex browser to brave://settings/importData list

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.48.113 Chromium: 109.0.5414.74 (Official Build) beta (64-bit)
-- | --
Revision | e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}
OS | Windows 11 Version 21H2 (Build 22000.1335)
```
Pre-requisite:  Download `Yandex` browser and have data for History, Bookmarks and Extensions
<details>
<img width="923" alt="image" src="https://user-images.githubusercontent.com/98358127/210903046-bd85297d-3eb5-4884-b02b-3cc7fee86186.png">
</details>

Case 1: Import from `brave://settings/importData` - PASSED

1. Install 1.48.113
2. launch brave
3. click `Skip` >> `Skip` >> `Finish` 
4. open `brave://settings/importData` in the new tab page
5. verified `Yandex` option displayed in the Import bookmarks and settings modal drop down
6. select `Yandex User 1` 
7. keep default selections of  `Browsing history`, `Favorites/Bookmarks` and `Extensions`
8. click `Import`
9. click `Done`

####Confirmed Bookmarks are shown in the bookmarks bar & brave://bookmarks
####Confirmed History is shown in brave://history
####Confirmed Extensions are shown in toolbar and brave://extensions

step 4-5|step 7|step 8|bookmarks|history|extensions
-----|------|-----|----|-----|-----
<img width="469" alt="image" src="https://user-images.githubusercontent.com/98358127/210901951-1cb44e29-0447-4313-a9ca-9edaf1b6ece3.png">|<img width="468" alt="image" src="https://user-images.githubusercontent.com/98358127/210901936-0d98d4ae-fd9a-4d74-a5de-f2b26827e087.png">|<img width="468" alt="image" src="https://user-images.githubusercontent.com/98358127/210901935-8b57315f-2a1e-494a-ba3f-264d5741a4fc.png">|<img width="475" alt="image" src="https://user-images.githubusercontent.com/98358127/210902324-9375e8bf-c89e-4dee-b94e-0a8c16899dee.png">|<img width="469" alt="image" src="https://user-images.githubusercontent.com/98358127/210902512-ef87158a-291d-4264-a7df-bcc5a847db91.png">|<img width="471" alt="image" src="https://user-images.githubusercontent.com/98358127/210902265-47bcbfef-9bd5-43d8-9540-753ecd727f3c.png">

Case 2: Import from clicking `Import bookmarks now...`  link on the bookmarks bar - PASSED

1. new profile
2. launch Brave
3. click `Skip` >> `Skip` >> `Finish` 
4. click Import bookmarks now...in the bookmarks bar
5. verified `Yandex` option displayed in the Import bookmarks and settings modal drop down
6. select `Yandex User 1` 
7. unselect default selections and select `Favorites/Bookmarks`
8. click import
9. click Done

#### Confirmed Bookmarks are shown in the `bookmarks bar` and `brave://bookmarks`

step 4|step 5-8|step 9|bookmarks
----|-----|-----|------
<img width="450" alt="image" src="https://user-images.githubusercontent.com/98358127/210903684-442ab89d-1c63-4123-8a2d-a759b75dd38a.png">|<img width="458" alt="image" src="https://user-images.githubusercontent.com/98358127/210904004-4d36b6b8-71f4-4a25-9450-e7d25c85f4a6.png">|<img width="458" alt="image" src="https://user-images.githubusercontent.com/98358127/210904044-01bf46bc-c60a-45c2-a768-761b4262e101.png">|<img width="660" alt="image" src="https://user-images.githubusercontent.com/98358127/210904300-e5719f81-d1d8-438b-8632-d9552978c8a7.png">

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.48.121 Chromium: 109.0.5414.87 (Official Build) beta (x86_64)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | macOS Version 11.7.2 (Build 20G1020)

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.48.137 Chromium: 109.0.5414.87 (Official Build) beta (64-bit)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | Linux
```
Pre-requisite: Download Yandex browser and have data for History, Bookmarks and Extensions
<details>

Profile 1: History, Bookmarks and Extensions
![Screenshot from 2023-01-23 09-47-27](https://user-images.githubusercontent.com/98358127/214100307-bc2eb1b2-ffba-4a90-866b-57c1c70be726.png)

Profile 2: History, Bookmarks
![Screenshot from 2023-01-23 09-44-18](https://user-images.githubusercontent.com/98358127/214100386-6ae7166d-baac-4c8f-b699-0bedfbddb24b.png)

Profile 3: Bookmarks
![Screenshot from 2023-01-23 10-05-08](https://user-images.githubusercontent.com/98358127/214103140-98703829-d445-486d-ac84-7919815f7185.png)
</details>
