### ISSUE TITLE
Improve Rewards text on Sponsored Images toggle in background settings

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#27304]
## Description 

Improvements on the informational message when rewards are turned off and users go to sponsored images section in the NTP settings page.

## Steps to Reproduce

   1. Have rewards turned off
   2. Click "Customize" on NTP
   3. Go to background images and scroll to the bottom
   4. See info box.

## Actual result:

![image](https://user-images.githubusercontent.com/15734630/207074869-46bb8315-760f-445f-a024-5e775fea0db0.png)

## Expected result:
Figma file:
https://www.figma.com/file/HwsbDLu321SiQlw5t7VA7K/Background-image---Sponsored-images-message?node-id=1%3A7&t=EFNP4WXTSSYm7JpL-3

![image](https://user-images.githubusercontent.com/15734630/207106631-c954489d-ad68-48dc-b0fe-6e7cfeb0e7d4.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

[Version 1.46.138 Chromium: 108.0.5359.94 (Official Build) (arm64)](https://brave.com/latest/)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

_______________

## New designs

https://www.figma.com/file/HwsbDLu321SiQlw5t7VA7K/Brave-rewards---Sponsored-images-message-in-Desktop-settings?node-id=1%3A2&t=g5MSwvCsWsSaSya7-0

**Comment by Miyayes** [comment]
**New designs:** https://www.figma.com/file/HwsbDLu321SiQlw5t7VA7K/Brave-rewards---Sponsored-images-message-in-Desktop-settings?node-id=1%3A2&t=g5MSwvCsWsSaSya7-0

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Samsung Galaxy version 12` running `Bravemonoarm64.apk_1.50.90`
