### ISSUE TITLE
Missing new tab background image options.

### ISSUE THREAD

**Issue by TheJanox824** [brave/brave-browser#27309]
## Description 
All new tab background image related options are missing from the "Customise Dashboard".

## Steps to Reproduce
   1. Go to new tab
   2. Click on "Customise"
   3. See there is no background image tab.

## Actual result:
There are no options related to the background image.
![image](https://user-images.githubusercontent.com/120404709/207132060-37431d62-e2d2-4ab8-8e4c-3d68ee0cc950.png)

## Expected result:
I saw screenshots where there's a background image tab, with options to change background, solid color, show sponsored images, or no image at all.

## Reproduces how often: 
The option is just not there. I never had it in the first place.

## Brave version (brave://version info)
Brave: 1.46.140 Chromium: 108.0.5359.99 (Official Build) (64-bit)
Revision: 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS: Windows 10 Version 22H2 (Build 19045.2311)

## Version/Channel Information:
- Can you reproduce this issue with the current release? Yes (the one I'm using rn)
- Can you reproduce this issue with the beta channel? Yes (I tried this)
- Can you reproduce this issue with the nightly channel? Yes (I tried this)

## Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:
I already tried removing all my extensions, reinstalling the browser, creating a new profile, I even tried on a fresh Windows installation, and a VM, and it's the same. I also tried disabling hardware acceleration (--disable-gpu in shortcut), with no success. This issue is not present on my Ubuntu installation (Brave Flatpak), with the proprietary NVIDIA drivers.

**Comment by rebron** [comment]
@TheJanox824 A couple questions for you. Can you you take a screenshot of the new tab page you have now? Open a new tab and take a screenshot for me. Also, can you tell me what locale or region you're in.

I just checked on 1.46.140 and I'm not seeing what you're seeing, so possibly extension related although you mentioned you turned off Extensions.

**Comment by rebron** [comment]
cc: @sangwoo108

**Comment by rebron** [comment]
@TheJanox824 Keep it open. I think we may have wrapped the setting incorrectly here by locale at the wrong level. Should still be able to change background images no matter what locale setting.

**Comment by rebron** [comment]
cc: @simonhong 
Note to check if this is a super referral issue.

**Comment by simonhong** [comment]
> cc: @simonhong Note to check if this is a super referral issue.

We're not allowing background customization when super referral now.

**Comment by simonhong** [comment]
Closed as duplicated with https://github.com/brave/brave-browser/issues/28144
