### ISSUE TITLE
Brave Tips Not Being Received at Publisher

### ISSUE THREAD

**Issue by BobT36** [brave/brave-browser#2731]
## Description 
Got my GF to tip me some of her BAT on the new Brave browser (v0.58.18), on her end it shows the tips having being sent, (and the wallet amount reducing to 0). But I haven't received any of the BAT on my end (Brave Publisher / Uphold).

Any way to check where that BAT went?

## Steps to Reproduce

   1. Watched 30m+ of Youtube on my Youtube Channel.  
   2. Set a Tip amount for the Youtube channel in Brave browser.
   3. Tip is sent to Youtube account. Brave wallet balance now shows 0.
   4. Funds not received on the other end.
   5. Very little information available, (date / time sent etc). User experience should be far more transparent.

## Actual result:
Funds not received in Brave Publisher account or Uphold wallet, even after days.

## Expected result:
That the funds would be received in the Brave Publisher account and stated as Pending(?)

## Reproduces how often: 
Every Time.

## Brave version (brave://version info)
Brave | 0.58.18 Chromium: 71.0.3578.98 (Official Build) (64-bit)
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Windows

### Reproducible on current release:
Reproducible in Live version. Unsure about Dev.

### Website problems only:  
N/A

### Additional Information
Screenshots included: Tips Sent. Wallet Balance Displayed. Brave Publisher Panel for Youtube Acc. Brave Publisher Statement. Uphold Recent Activity.
The only activity shown is from when the payments worked just once, months ago on the old browser.

![tips](https://user-images.githubusercontent.com/14024619/50405269-fc94fa00-07a9-11e9-8de5-efe1e15b2208.JPG)
![wallet](https://user-images.githubusercontent.com/14024619/50405270-fd2d9080-07a9-11e9-9b4f-433cd611e559.JPG)
![publishers](https://user-images.githubusercontent.com/14024619/50405266-fc94fa00-07a9-11e9-96fd-366ff213c701.PNG)
![statement](https://user-images.githubusercontent.com/14024619/50405268-fc94fa00-07a9-11e9-951d-29c3b979ce7c.PNG)
![recent activity](https://user-images.githubusercontent.com/14024619/50405267-fc94fa00-07a9-11e9-93c3-fbca3c88b957.PNG)

**Comment by eljuno** [comment]
AFAIK, now the balance at publishers dashboard will updated once a month. So you'll not see it in "real-time". :)

**Comment by BobT36** [comment]
Ah-ha, we'll see in a month.

**Comment by BobT36** [comment]
Surely there should be SOME display that money has actually arrived though? People with fans etc could have their fans asking them if they've received their payment (or at least got some notification), and currently it looks as if it's just disappeared into the void..

**Comment by srirambv** [comment]
@BobT36 You can find the details on the [FAQ section](https://brave.com/faq-rewards/#publisher-notification).
