### ISSUE TITLE
IPFS Extension API

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#27310]
IPFS Extension API is needed for content-posting extensions:
At first we need some method that allows to start local node, so extension can communicate with the IPFS network using RPC  calls.
As follow-up we can provide some proxy interface that mirrors Kubo API, to allow using other IPFS client implementations under the hood.

**Comment by diracdeltas** [comment]
is this just for one extension or will any extension have access?

**Comment by yrliou** [comment]
@diracdeltas This came up during IPFS bi-weekly meeting, it should be just for whitelist extensions if we ever moved on with this. I think we're still in some planning phases that we would need to define the use cases clearly and evaluating if the extension API is the best way to go before moving on to one solution.

**Comment by lidel** [comment]
**Exposing the entire RPC is a risky proposition.** It is not future-proof, will lead to feature creep, people asking to safelist more and more, and either we will make a bad call at some point, or will lock ourselves out of supporting alternative implementations (such as Iron in Rust), or have to maintain glue code that translates Kubo RPC to Iroh gRPC.

Instead, we should focus on real user needs and dedicated methods.
afaik the only needs safelisted extensions should have addressed are:
- read-only
  - start/stop/status IPFS daemon
  - read/set preferred way of resolving ipfs:// and ipns:// 
  - read/toggle automatic redirect to local gateway
- writing/publishing
  - onboarding data to IPFS to get a CID and have local node provide it to other peers (incl. pinning)


For read-only path, there is no need for extension to know what is the port of local gateway – it should only learn that ipfs:// is supported (or have ability to enable it), and use that.  `await fetch("ipfs://...")` working seamlessly is what we want.

For writing/publishing, we should not expose Kubo RPC to the web platform. Instead, we should follow Gateway pattern and use implementation/vendor-agnostic interface. FYSA:
- I will be submitting IPIP this quarter to make POST possible on gateways. When it is finalized and implemented in Kubo, Brave will be able to grant access to it via  `await fetch("ipfs://...", {method: 'post'})`. 
- Access to MFS over local gateway is also planned, with intention to provide intuitive pinning management via `fetch` API and things like WebDAV. 

That being said, if `brave://local-kubo-rpc/` proxy is easy to implement and solves write-via-Kubo-RPC  needs flagged by @ikreymer, that is also an acceptable step-gap for now.

**Comment by lidel** [comment]
FYSA I've filled https://github.com/brave/brave-browser/issues/31199 for privileged APIs for IPFS Companion.
I did not reuse this issue because this one is about less privileged APIs that extensions like Webrecorder could use.

**Comment by vadimstruts** [comment]
The IPFS local node and scheme has been [deprecated](https://github.com/brave/brave-browser/issues/37735)
