### ISSUE TITLE
MdTextButton should be refactored to use the same mechanisms as the Chromium impl of MdTextButton

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#27324]
Currently, we have a number of custom hooks. It should be possible to simplify this a bit and make the code easier to understand/override.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using

```
Brave | 1.50.91 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | Windows 11 Version 22H2 (Build 22621.1413)
```

1. Install 1.50.91
2. launch Brave
3. open a new-tab
4. Scroll down and click `Turn on Brave News`
5. visit https://www.theatlantic.com/world/ 
6. click `Manage Subscriptions` icon in the URL bar
7. click `Follow` button
8. click `Manage feeds` 
9. The Atlantic source is in the `Following` column as expected
10. Unfollow `Top Sources` and close the Dashboard
11. refresh the page
12. articles from `The Atlantic` sources are shown as expected

step 4| step 5 -6 |step 7 | step 9 | step 10-11|step 12
----------|--------|--------|----------|----------|-------
<img width="443" alt="image" src="https://user-images.githubusercontent.com/98358127/225368388-bde61c42-a49d-4916-9edf-4163d84d8b0d.png">|<img width="452" alt="image" src="https://user-images.githubusercontent.com/98358127/225368784-3332aa87-2dda-48b1-9854-fb8d19f1b4ad.png">|<img width="452" alt="image" src="https://user-images.githubusercontent.com/98358127/225369019-65577b88-c291-4464-b8ef-981bd6eaae86.png">|<img width="453" alt="image" src="https://user-images.githubusercontent.com/98358127/225369116-ff1249d9-c0fd-466b-b724-5ad70854fb73.png">|<img width="450" alt="image" src="https://user-images.githubusercontent.com/98358127/225369378-c7316286-c115-4cc2-a714-590e0384f491.png">|<img width="456" alt="image" src="https://user-images.githubusercontent.com/98358127/225369764-e8a903ae-d5ae-4350-beae-b57278079497.png">
