### ISSUE TITLE
Unable to obtain credentials on staging (account.bravesoftware.com)

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#27322]
## Description 

Unable to obtain credentials on staging (account.bravesoftware.com)

Filed here because I wasn't sure it which product/component/repo to slate it, and we need visibility.

## Steps to Reproduce

1. delete any `BraveVPN` OS-configs, first
2. install `1.47.125`
3. launch Brave using `--vmodule="*/skus/*"=2 --enable-logging=stdrr --v=1`
4. click `Maybe later`
5. click `Skip welcome tour`
6. open `brave://flags`
7. set `brave://flags/#brave-vpn` to `Enabled`
8. click `Relaunch`
9. click `No thanks` on the `Tired of cookie consent notices?` dialog
10. load `account.bravesoftware.com`
11. enter staging credentials from `1Password`
12. enter a unique email address such as `unique99@mailinator.com` or similar
13. click `Get login link`
14. open the `Log in to your Brave Pre...` email (https://www.mailinator.com/v4/public/inboxes.jsp?to=unique99 in the above case)
15. click on the `Log in to Brave` button
16. click `Browse plans` on `https://account.bravesoftware.com/account/`
17. scroll down
18. click on `Buy now` beneath `Brave VPN Subscription`
19. complete the Stripe checkout using `https://stripe.com/docs/testing#testing-interactively`
20. notice you don't have the `You have active credentials loaded!` messaging
21. click on the `Refresh Brave VPN` button
22. click on the VPN button in the browser toolbar, and attempt to add and connect to the `BraveVPN` config

## Actual result:

<img width="1312" alt="Screen Shot 2022-12-13 at 2 30 53 PM" src="https://user-images.githubusercontent.com/387249/207169823-9270640c-72d6-4198-ad94-efdbcbe34a61.png">

## Expected result:

Valid `BraveVPN` credentials + config

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.47.125 Chromium: 108.0.5359.99 (Official Build) beta (x86_64)
-- | --
Revision | 410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}
OS | macOS Version 11.7.1 (Build 20G918)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

/cc @mattmcalister @husobee @rebron @brave/qa-team @spylogsster @simonhong @bsclifton @AlanBreck

**Comment by simonhong** [comment]
I also saw this issue yesterday and I got proper panel after clicking `Refresh Brave VPN` button.

**Comment by stephendonner** [comment]
> I also saw this issue yesterday and I got proper panel after clicking `Refresh Brave VPN` button.

But is it broken for you now, as it is for me?

**Comment by stephendonner** [comment]
![Uploading vpn-credentials.gif…]()

**Comment by stephendonner** [comment]
![vpn-credentials](https://user-images.githubusercontent.com/387249/207200847-2b157110-4a2a-4a15-a4e2-b230f7abe769.gif)

**Comment by stephendonner** [comment]
Closing this out since I filed https://github.com/brave-intl/challenge-bypass-server/issues/315, which is in the appropriate repo + component, etc.
