### ISSUE TITLE
Update Assets Portfolio Filter

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#27323]
## Description 
We need to make some updates the the `Assets` filter on the `Portfolio` page.

- Remove the `NFTs` option
- Remove the `All Assets` option
- Make `High to Low` option the default
- Make the `High to Low` option the first option above `Low to High`
- Add a `A to Z` and `Z to A` option

![Screen Shot 2022-12-12 at 5 07 11 PM](https://user-images.githubusercontent.com/40611140/207177869-0fe43abe-9a94-4eb1-b040-9abec70b8e51.png)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.48.139 Chromium: 109.0.5414.87 (Official Build) beta (64-bit) 
-- | --
Revision | `2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}`
OS | Linux

- Verified steps from [brave/brave-core#16362](https://github.com/brave/brave-core/pull/16362)
- Verified on the `Portfolio` tab, `Balance high to low` is the default selection
- Verified changing to `Balance low to high` sorts the asset list according to ascending based on balance
- Verified changing to `Name a to z` sorts the asset list alphabetically in ascending order
- Verified changing to `Name z to a` sorts the asset list alphabetically in descending order
- Verified sorting is retained when network is changed in the network selector
- Verified sorting is only affecting tokens on portfolio page and not NFT's 

https://user-images.githubusercontent.com/17010094/214562367-705745a0-76e2-4fcd-98f5-2ba202ef0c84.mp4

---------------------

Verification passed on 

Brave | 1.48.139 Chromium: 109.0.5414.87 (Official Build) beta (64-bit)
-- | --
Revision | `2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#16362](https://github.com/brave/brave-core/pull/16362)
- Verified on the `Portfolio` tab, `Balance high to low` is the default selection
- Verified changing to `Balance low to high` sorts the asset list according to ascending based on balance
- Verified changing to `Name a to z` sorts the asset list alphabetically in ascending order
- Verified changing to `Name z to a` sorts the asset list alphabetically in descending order
- Verified sorting is retained when network is changed in the network selector
- Verified sorting is only affecting tokens on portfolio page and not NFT's 

https://user-images.githubusercontent.com/17010094/214562796-9fec4e3c-c257-4438-8525-b2d48b5cc4f6.mp4

---------------------

Verification passed on 

Brave | 1.48.139 Chromium: 109.0.5414.87 (Official Build) beta (arm64)
-- | --
Revision | `2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#16362](https://github.com/brave/brave-core/pull/16362)
- Verified on the `Portfolio` tab, `Balance high to low` is the default selection
- Verified changing to `Balance low to high` sorts the asset list according to ascending based on balance
- Verified changing to `Name a to z` sorts the asset list alphabetically in ascending order
- Verified changing to `Name z to a` sorts the asset list alphabetically in descending order
- Verified sorting is retained when network is changed in the network selector
- Verified sorting is only affecting tokens on portfolio page and not NFT's 

https://user-images.githubusercontent.com/17010094/214563074-069ee9da-09c5-4682-b6fb-0f18a0460cea.mov
