### ISSUE TITLE
Refactor portfolio to show onscreen network selector and all assets

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#27333]
## Description 
- Refactor portfolio to show onscreen network selector 
- Show assets per network or "All networks" selection

## Expected result

![Screenshot from 2022-12-13 16-07-37](https://user-images.githubusercontent.com/11755381/207295471-12552615-d810-4d8d-b060-61b718a38e54.png)

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.52.92 x64 Beta build
- Verified steps from [brave/brave-core#17796](https://github.com/brave/brave-core/pull/17796)
- Verified search token filters tokens based on selected network in portfolio
- Verified tokens added via search token show up as expected
- Encountered [#30251](https://github.com/brave/brave-browser/issues/30251)

Oppo Reno 5 (Android 13) | Lenovo Tab (Android 12)
-- | --
<video src=https://github.com/brave/brave-browser/assets/17010094/1b5e8df4-c199-42e7-b552-b2ba318c212d> | <video src=https://github.com/brave/brave-browser/assets/17010094/cc1519e1-2749-4918-a335-fb5c0fbd33ac>
