### ISSUE TITLE
upgrades after geolocation fix may have rewards in a bad state in certain cases - follow up to 26286

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#27336]
## Description 
Follow up to #26286 

If someone tried to enable Rewards on Android 6/7 using 1.46.x and encountered the crash from the above issue, when they upgrade to a version with the fix (such as `1.46.143`), their rewards will be in a bad state. Meaning, after they upgrade to a version with the fix - they are not offered country selection/onboarding again. Instead, the panel shows a weird state and brave://rewards-internals shows wallet not created, but they can see/access all UI on panel and brave://rewards page.

Note - this does not seem to happen if a user had rewards enabled in 1.45.x. 

## Steps to reproduce 

Upgrade Scenario 1 - this is the **broken** one
1. Install 1.46.138
2. Get crash on country selection from rewards panel
3. Upgrade to 1.46.143
4. Tap on rewards icon
--> no country selection/onboarding. Panel looks odd. brave://rewards-internals shows "no wallet created". Appears as though rewards is in some kind of borked state.

For comparison, 
Upgrade Scenario 2 - this one is **not broken**
1. Install 1.45.133 (last version before country selection)
2. Enable rewards
3. Confirm brave://rewards-internals shows wallet info
4. Viewed a couple ads to have ad earnings balance
5. Upgrade to 1.46.138
6. Get crash on country selection from rewards panel
7. Upgrade to 1.46.143
8. Tap on rewards icon *note, at this point sometimes the panel is in a "loading" state, close and reopen fixed this. Not sure if a race condition? I think this is known.
9. Get country selection, able to select country successfully, confirmed ad earning balance was retained.

## Actual result 

From Scenario 1 (broken):
Example | Example
---- | ----
![Screenshot_20221213-084250](https://user-images.githubusercontent.com/28145373/207353569-ac68cab9-5a4f-4634-a8ea-e5ee3a9d5882.png) | ![Screenshot_20221213-084311](https://user-images.githubusercontent.com/28145373/207353576-fae13aa6-c86a-4134-9902-6e177b493e71.png)

## Expected result

Should work as it does in upgrade scenario 2, user should be offered country selection and onboarding, then be able to select without crash and proceed successfully.

`1.45.133` | `1.46.143` | `1.46.143`
--- | --- | ---
![Screenshot_20221213-084835](https://user-images.githubusercontent.com/28145373/207354127-78544f78-7015-4b42-b231-fd4d1e6c6c3a.png) | ![Screenshot_20221213-085756](https://user-images.githubusercontent.com/28145373/207354130-a11ec04f-31e3-4019-b8c3-ada38084288e.png) | ![Screenshot_20221213-085808](https://user-images.githubusercontent.com/28145373/207354134-b7317692-856c-4e7b-8668-ae99acf66703.png)

## Issue reproduces how often 
easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? yes
- Can you reproduce this issue with the current Play Store Beta version? probably, unsure
- Can you reproduce this issue with the current Play Store Nightly version? probably, unsure

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
1.46.143

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc @deeppandya @kjozwiak @Uni-verse @tapanmodh @Miyayes

**Comment by kjozwiak** [comment]
Closing as this was uplifted into `1.47.x` & `1.46.x` via https://github.com/brave/brave-core/pull/16370 & https://github.com/brave/brave-core/pull/16365.

**Comment by kjozwiak** [comment]
The the above requires `1.46.145` or higher for `1.46.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress on Samsung J7 Neo with Android 7 running 1.46.145.

<details>
<summary>Clean profile check 1 - InProgress</summary>

1. Install 1.46.145
2. Complete prompts
3. Tap on rewards icon
4. Tap on "Start using Brave Rewards"
5. Select country (I chose US) from country selection --> confirmed no crash
6. Confirm country is set successfully
7. Confirm received onboarding, followed by "first" ad

</details>

<details>
<summary>Clean profile check 2 - TBD</summary>

1. Install 1.46.145
2. Complete prompts
3. Close and relaunch to pull griffin seed
4. Tap on rewards icon
5. Tap on "Start using Brave Rewards"
6. Select country (I chose US) from country selection --> confirmed no crash
7. Confirm country is set successfully
8. Confirm received onboarding, followed by "first" ad

</details>

<details>
<summary>Upgrade Scenario 1 - TBD</summary>

1. Install 1.46.138
2. Tap on Rewards icon, attempt to select country --> get crash on country selection from rewards panel
3. Upgrade to 1.46.145
4. Tap on rewards icon
5. Get country selection UI
6. Confirmed able to select country (US) successfully
7. Was expecting onboarding at this point, but didn't get it. (confirmed this is OK with @Miyayes as per https://bravesoftware.slack.com/archives/C0816QH3R/p1670969485600019?thread_ts=1670563763.844739&cid=C0816QH3R)
8. I did get my "first" ad after selecting the country and confirmed panel displayed as expected
9. Navigated to brave://rewards-internals/ and confirmed that wallet info was displayed as expected, including country

Step 2 | Step 5 | Step 6 | Step 9
---- | ---- | ---- | ----

</details>

<details>
<summary>Upgrade Scenario 2 - TBD</summary>

1. Install 1.45.133 (last version before country selection)
2. Enable rewards
3. Confirm brave://rewards-internals shows wallet info
4. Viewed a couple ads to have ad earnings balance
5. Upgrade to 1.46.138
6. Get crash on country selection from rewards panel
7. Upgrade to 1.46.145
8. Tap on rewards icon 
9. Get country selection, able to select country successfully, confirmed ad earning balance was retained.
10. Navigated to brave://rewards-internals/ and confirmed that wallet info was displayed as expected, including country

Step 3 | Step 9 | Step 9 | Step 10
---- | ---- | ---- | ----

</details>
