### ISSUE TITLE
Update text for `Help make Brave better` screen

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#27339]
## Description 

Update finalized strings for new onboarding `Help make Brave better` screen. 

- [ ] Use the text in the Expected result screenshot. Figma here: https://www.figma.com/file/MFHpcXJMg2RUQpUJMAZZ4R/Desktop-Onboarding?node-id=4205%3A105911&t=OgwXlQ3MZKgS9Dqj-0
- [ ] Learn more link for first check box/crash reports to go to: `https://support.brave.com/hc/en-us/articles/360017905872-How-do-I-enable-or-disable-automatic-crash-reporting`
- [ ]  Learn more link for second check box/P3A to go to: `https://support.brave.com/hc/en-us/articles/9140465918093-What-is-P3A-in-Brave-`

## Actual result:

<img width="851" alt="205358475-5a778930-d505-47c9-8950-d52073a20f19" src="https://user-images.githubusercontent.com/5951041/207391872-1cd74c23-515d-4e52-a10e-a0a17eb4f002.png">

## Expected result:
<img width="1360" alt="Screenshot 2022-12-13 at 8 59 56 AM" src="https://user-images.githubusercontent.com/5951041/207396682-ca2d9b56-09e7-42a1-91ca-a3202e9f08f7.png">

## Reproduces how often: 

Easily

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

Follow-up from: https://github.com/brave/brave-browser/issues/27126
Security review: https://github.com/brave/security/issues/1132
Related Android issue: https://github.com/brave/brave-browser/issues/23989

**Comment by PrivacyMatters** [comment]
Thx @rebron Could we also remove the word anonymous from the diagnostics unless @fmarier and @ShivanKaul believe the measures we have in place to strip personal data from reports, does result in them being anonymous.

**Comment by rebron** [comment]
@PrivacyMatters I updated the screen and removed `anonymous` from the first checkbox.

**Comment by kjozwiak** [comment]
The above requires `1.47.131` or higher for `1.47.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.47.132 Chromium: 108.0.5359.128 (Official Build) beta (x86_64)
--|--
Revision | 1cd27afdb8e5d057070c0961e04c490d2aca1aa0-refs/branch-heads/5359@{#1185}
OS | macOS Version 11.7.2 (Build 20G1020)


`brave://welcome` | `crash reporting` link | `p3a` link
-------------------|-------------------|-------
<img width="1478" alt="Screen Shot 2022-12-17 at 2 27 45 AM" src="https://user-images.githubusercontent.com/387249/208237638-f1bf2e87-f31c-432e-b173-3bee1d90f7e4.png"> | <img width="1478" alt="Screen Shot 2022-12-17 at 2 28 01 AM" src="https://user-images.githubusercontent.com/387249/208237639-51c9489c-c31d-492c-a714-54108a1512f5.png"> | <img width="1478" alt="Screen Shot 2022-12-17 at 2 28 14 AM" src="https://user-images.githubusercontent.com/387249/208237640-cf48a4a1-f2e3-4291-b4c7-5a8bd75c026b.png">


#### Confirmed:

* text/copy changes as implemented match the `Expected Result`, above
* `Learn more.` link for first check box/crash reports goes to: `https://support.brave.com/hc/en-us/articles/360017905872-How-do-I-enable-or-disable-automatic-crash-reporting`
* `Learn more.` link for second check box/P3A to go to: `https://support.brave.com/hc/en-us/articles/9140465918093-What-is-P3A-in-Brave-`
