### ISSUE TITLE
Refactor network selector for multi-chain support and network screen to show grouped networks

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#27332]
## Description 
Refactor network selector for multi-chain support:
- Network screen to show grouped networks
- Support for independent network selector mode

## Expected result
<img src="https://user-images.githubusercontent.com/11755381/207292254-dc5b2886-e6dc-4d64-ba39-ec9702131b1d.jpg" width="300"/>

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.48.155 x64 build
- Verified account change transition is smooth on both wallet panel and on wallet screen
- Verified test networks are nested inside of the main network name for both Solana and Ethereum
- Verified changing network via panel and via wallet home page works as expected 
- Verified changing account from picker updates the network as expected

Oppo Reno 5 (Android 13) | Lenovo Tab (Android 12)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/216881422-b16c5389-088e-429f-bc20-86f6f6897021.mp4> | <video src=https://user-images.githubusercontent.com/17010094/216881443-2ba4a7eb-99de-49ee-9eac-779ce1d60431.mp4>
