### ISSUE TITLE
Application menu name should be labeled with proper channel name

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#27341]
## Description 

Currently with Brave Beta and Nightly, the app name reads as `Brave` on macOS. It should read Brave Beta or Brave Nightly.

## Steps to Reproduce

   1. Use 1.47.126 on Beta channel or 1.48.51 on Nightly. Not clear what version where this regressed.
   2. Notice Application name on top left of screen.
   3. Reads as `Brave` and should read as `Brave Beta` or `Brave Nightly`

## Actual result:

![image](https://user-images.githubusercontent.com/5951041/207403147-9892a8b7-b3e6-48b0-8c8a-52bc72539446.png)

## Expected result:
[design placeholder]

## Reproduces how often: 

Easily.

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.48.119 Chromium: 109.0.5414.80 (Official Build) beta (x86_64)
-- | --
Revision | 0f69b168d36a06cace4365e9f029fa987afa5633-refs/branch-heads/5414@{#1178}
OS | macOS Version 11.7.2 (Build 20G1020)

### Steps:
1. installed `1.48.119`
2. launched Brave
3. looked at the application name in the top-level system menu

#### Confirmed it now says `Brave Beta`

<img width="700" alt="Screen Shot 2023-01-10 at 10 22 45 AM" src="https://user-images.githubusercontent.com/387249/211631899-f8b507aa-f96d-4609-b2c1-0d809e1adb4d.png">
