### ISSUE TITLE
Permissioning access to localhost connections

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#27346]
Similar to https://github.com/brave/brave-browser/issues/26273, we'd like to add a new site permission called **Localhost connections**. There are several legitimate use-cases that involve the website asking for access to localhost e.g. a localhost-based websocket. 

Currently we [block all localhost connections](https://github.com/brave/brave-browser/issues/11733) via [Adblock](https://github.com/brave/adblock-lists/pull/463), but allowlist some in [brave-specific.txt](https://github.com/brave/adblock-lists/blob/16b5388cab382f68f58d3538adcaf38ab740db58/brave-lists/brave-specific.txt#L24).

We will be able to safely add exceptions to the localhost-blocking adblock rules, once we have this. **NOTE: we still want adblock rules to apply before applying this permission.** After this permission is added to Brave, in order for a site to have access to localhost resources, it still needs to do 2 things:
1. It needs to be allowlisted in [brave-specific.txt](https://github.com/brave/adblock-lists/blob/16b5388cab382f68f58d3538adcaf38ab740db58/brave-lists/brave-specific.txt#L24).
2. The user needs to click Allow in the permission prompt.

**NOTE:** we only permission/block requests based on the URL, not the resolved IP address, which still leaves space for DNS rebinding attacks. This will be addressed in a follow-up.

Android follow-up: https://github.com/brave/brave-browser/issues/29730

**Functionality:**
1. Create new permission/content setting called `Localhost Access`.
2. Apply adblock filter rules as normal.
4. Detect if a request is from a valid non-localhost requesting origin for a subresource that looks like a [localhost resource](https://source.chromium.org/chromium/chromium/src/+/main:net/base/url_util.h;l=197;drc=4ced8912f6c8b32715984dd81e3f376a260ebab6;bpv=1;bpt=1).
5. If current permission status is DENY, cancel the request (`net:: ERR_ACCESS_DENIED`).
6. If current permission status is ALLOW, allow the request (`net::OK`).
7. If current permission status is ASK, cancel the request (`net:: ERR_ACCESS_DENIED`), and show permission prompt.
8. If permission granted, reload the tab. Now the permission status will be ALLOW, and the user will not get re-prompted for localhost subresource requests.

**Notes:**
1. Test website: https://fmarier.com/unprotected/localhost-resources.html
2.  There can be multiple requests by the same website, need to take care of that. 
4. This permission is only for subresource requests, not mainframe.
5. WebSockets case should be covered
6. Service Workers case should be covered
7. Make sure that localhost -> localhost requests are not blocked. 
8. Need to think about extensions https://github.com/brave/brave-browser/issues/15107
9. We should also fix the current subnet issue: https://github.com/brave/brave-browser/issues/20457
10. We will also want the ability to refer to localhost connections in adblock filter list rules. Something like `{local}^$third-party`
11. Collect use-cases/apps that need this functionality and figure out which ones to allowlist.

**Comment by ShivanKaul** [comment]
Working on a PR right now. If folks have test websites that don't currently work on Brave, please drop them here, would help a lot with smoke testing.

**Comment by CharlieGreenman** [comment]
@ShivanKaul if interested razroo.com x razroo vscode plugin(https://marketplace.visualstudio.com/items?itemName=Razroo.razroo-vscode-plugin) is a good example(will need to sign up/sign into razroo in order to use. We spin up a local server in the vscode plugin and pass information directly from web to local vscode plugin. It works on chrome, and edge, but no on brave for i believe this reason. If authentication works, it means officially fixed.

**Comment by ShivanKaul** [comment]
Cool, that seems to work well on my local feature branch for this issue. This is the experience:

https://user-images.githubusercontent.com/5284154/220427702-b3cb09db-f848-4f02-905f-3a71ed1557b7.mov

**Comment by CharlieGreenman** [comment]
cool that means it should be working as expected. Prior brave users were unable to authenticate. Thank you

**Comment by ShivanKaul** [comment]
Thanks for the use-case! Helps a lot. If others have ones too, that would help get this out faster because we'd be surer we're not breaking things.

**Comment by nacmonad** [comment]
> Thanks for the use-case! Helps a lot. If others have ones too, that would help get this out faster because we'd be surer we're not breaking things.

Is there a dev branch I can check out?  I am running into this issue presently, but the software is proprietary/beta...

**Comment by CharlieGreenman** [comment]
@nacmonad just to confirm. is that question directed to me or @ShivanKaul

**Comment by CharlieGreenman** [comment]
🚀

**Comment by ShivanKaul** [comment]
This feature has been merged in for both Desktop and [Android](https://github.com/brave/brave-browser/issues/29730) but is default-disabled while we work on a better way of shipping which websites should be allowed to request permission.

**Comment by CharlieGreenman** [comment]
@ShivanKaul why not allow users to decide that on their own?

**Comment by CharlieGreenman** [comment]
Thank you. It goes without saying my thanks as always

<img width="211" alt="Screenshot 2023-04-27 at 9 28 44 PM" src="https://user-images.githubusercontent.com/8540141/234958306-cc017d97-d62d-435d-a814-82462dca4b2a.png">

**Comment by MicahZoltu** [comment]
> default-disabled while we work on a better way of shipping which websites should be allowed to request permission.

I'm generally not a fan of a whitelist (which it sounds like you are suggesting), as that seems fairly antithetical to the idea of a "decentralized and permissionless internet".  Could you solve the spam problem similar to how Firefox (and maybe Brave too) solves the alert popup and new tab spam problem with a dialog that asks if you want to let the site continue to prompt you?

It seems that the same technique as mic/camera/notification access could be used, where the page asks for permission to access other services running on your device and you can accept, reject, and reject with prejudice (never ask again for this site).

**Comment by ShivanKaul** [comment]
The issue is not one particular website doing it (Brave has [finer-grained permission scope and lifetime than other browsers](https://github.com/brave/brave-browser/wiki/Web-API-Permissions)), but multiple websites prompting for the localhost permission. Port-scanning fingerprinting attacks are very common and easy [[1](https://www.bleepingcomputer.com/news/security/ebay-port-scans-visitors-computers-for-remote-access-programs/)], [[2](https://www.bleepingcomputer.com/news/security/list-of-well-known-web-sites-that-port-scan-their-visitors/)]. 

Our general stance has been that Web APIs too harmful for user privacy should be disabled without a permission prompt, because users cannot meaningfully consent to them. In the case of localhost connections, it seems like there _are_ **some** benign use-cases, so we're experimenting with selectively allowing them.

**Comment by MicahZoltu** [comment]
Perhaps I'm misunderstanding.  How would you selectively allow some use cases without doing specific website whitelisting?  Are you thinking of allowing some subset of ports or protocols or something when communicating with localhost, while disallowing port scanning?  Or perhaps constrain how many ports a given website can *attempt* to query locally before they get locked out from querying any additional ports?

**Comment by ShivanKaul** [comment]
We will be allowing only specific websites to ask for this permission.

**Comment by MicahZoltu** [comment]
I don't think that a permissioned/gatekept web is an appropriate solution for this.  Even though I want this feature, I think permissioning it is a strictly *worse* solution than not having it at all because it allows large companies to create moats around their exclusive access to browser features and it reduces the impetus and pressure for the Brave team to find a solution that works for everyone.

As a user and a web/extension developer, Brave implementing a permissioned web in their browser is a *huge* turnoff for me.  I generally like Brave's position on security, privacy, and censorship resistance, but if you all start permissioning/censoring the web it will result in *massive* negative marks in my internal browser scoring rubric.

**Comment by ShivanKaul** [comment]
Just to clarify, there will be a way for a user to override which websites get this permission by going to the permission setting page: brave://settings/content/localhostAccess

This is part of the enhancement we're exploring. 

<img width="671" alt="image" src="https://user-images.githubusercontent.com/5284154/235550793-0baf87a9-f4d5-451a-b394-b458b6cba72a.png">

**Comment by ShivanKaul** [comment]
But there will be a default list of websites that can ask for this permission.

**Comment by MicahZoltu** [comment]
If users can add sites to the whitelist then I think that mitigates a lot of my concerns.  I'm not a huge fan of having a built-in whitelist as it gives preferential treatment to "friends of Brave" (or people who can afford the registration costs, or people who KYC, or people who go through some bureaucratic process or whatever).

Will it be possible to have certain localhost resources made available to all websites?  For example, if I am running a local Ethereum client or IPFS client, I would like any website to be able to probe for and access those.  A website might first probe to see if I have IPFS running locally and if so use that (which I would prefer) then fallback to a central server (same for Ethereum client).  I don't want to have to whitelist every website that wants to use these resources as they are *intended* to made available to web apps.

In this scenario, I would still be fine with getting a prompt "This website wants to access your Ethereum client: Allow, Deny", but I wouldn't want to have to add every single website to the whitelist by hand, and I also wouldn't necessarily want to give every website full unrestricted access to all localhost resources (only a couple that I have intended to make available as part of a suite of decentralized web tools).

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.52.86 Chromium: 113.0.5672.77 (Official Build) beta (x86_64)
-- | --
Revision | c4236862955e005c2187105415ac4a2ecf86dff1-refs/branch-heads/5672_62@{#3}
OS | macOS Version 13.4 (Build 22F5059b)

**Comment by ShivanKaul** [comment]
>I'm not a huge fan of having a built-in whitelist as it gives preferential treatment to "friends of Brave" (or people who can afford the registration costs, or people who KYC, or people who go through some bureaucratic process or whatever).

I'm not sure what the point being made here is, but Brave [heavily contributes to adblock filter list development](https://www.usenix.org/conference/pepr22/presentation/sahib) and maintenance and part of that work is figuring out what network requests are safe or otherwise in the interest of the user (across all adblockers, not just Brave), and which ones are not. We're going through open GitHub issues right now to collect use-cases we can now enable with this feature. We always offer a way for users to add their own lists/rules for adblock, and similarly here, we will offer a way for users to add which websites are considered safe to access localhost resources.

>Will it be possible to have certain localhost resources made available to all websites?

Can you create a new issue for this? We can discuss it there.

**Comment by MicahZoltu** [comment]
I opened #30181 for discussing specific localhost resources being made globally available for permission requests.

> I'm not sure what the point being made here is, but to give a closely-related example, Brave [heavily contributes to adblock filter list development](https://www.usenix.org/conference/pepr22/presentation/sahib) and maintenance and part of that work is figuring out what network requests are safe or otherwise in the interest of the user (across all adblockers, not just Brave), and which ones are not. We're going through open GitHub issues right now to collect use-cases we can now enable with this feature. We always offer a way for users to add their own lists/rules for adblock, and similarly here, we will offer a way for users to add which websites they consider safe to access localhost resources.

The broad point I think is that the failure mode of blacklists is quite different from the failure mode of whitelists.  If Brave is unable to keep up with demand for adding things to a blacklist, then users are not protected as well but new websites aren't prevented from being able to do everything that existing websites do.  If Brave is unable to keep up with demand for whitelist additions, then new websites will not be able to do everything that existing websites do.

IMO, this difference of failure modes is quite significant because a blacklist leaves the web open by default while a whitelist leaves the web closed by default.  I believe that it is important that the web remain open and decentralized by default, with things like AdBlock adding exceptions to the "open by default" rule rather than the other way around.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.52.91 Chromium: 113.0.5672.77 (Official Build) beta (64-bit)
-- | --
Revision | c4236862955e005c2187105415ac4a2ecf86dff1-refs/branch-heads/5672_62@{#3}
OS | Windows 11 Version 22H2 (Build 22621.1555)
```

### Prerequisites:
<details>

1. created a directory `tests`, at `/Users/stephendonner/Desktop/tests`
2. dropped a `logo.png` image into `/tests`
3. ran `python3 -m http.server 8000` from `/tests`:

```
C:\Users\mseel\Documents\tests>python3 -m http.server 8000
Serving HTTP on :: port 8000 (http://[::]:8000/) ...
```

</details>

### Shared Steps:
<details>

1. installed `1.52.91`
5. launched Brave
6. opened `brave://flags`
7. set `#brave-localhost-access-permission` to `Enabled`
8. clicked `Relaunch`
9. opened `brave://adblock`
10. scrolled to `Create custom filters`
11. entered `@@||localhost^$domain=shivankaul.com`
12. clicked `Save changes`
13. loaded `https://shivankaul.com/brave/localhost/` 

`brave://adblock` | `brave://flags`
---------------|-----------------
![image](https://user-images.githubusercontent.com/98358127/236964108-c27b10f7-35dc-46dc-b02d-a791ded81dcc.png)| ![image](https://user-images.githubusercontent.com/98358127/236964034-dc2b9794-170a-40a6-9ccd-2861ce836f21.png)

</details>

### Case 1: Subresource image test - `PASSED`
<details>

### `Allow`

(continued from `Shared Steps`)
1. loaded `https://shivankaul.com/brave/localhost/subresource.html`
2. confirmed I got the permission prompt
3. clicked `Allow`
4. opened `brave://settings/content/localhostAccess`
5. confirmed the site was listed under `Allowed to access localhost resources`
6. `Localhost Access` permissions show `Allow` under brave://settings/content/siteDetails?site=https%3A%2F%2Fshivankaul.com%3A443

### Confirmed `logo.png` rendered

`step 2` | `step 3` | `step 4` | `step 6`
-----------|------|--------|------------
<image width="500" alt="image" src="https://user-images.githubusercontent.com/98358127/236964438-a3cb42ca-807c-4c94-a6bb-f1203e7b0221.png">|<image width="500" alt="image" src="https://user-images.githubusercontent.com/98358127/236964542-5d674307-5d8d-45df-aac5-3acbcf82e646.png">|<image width="500" alt="image" src="https://user-images.githubusercontent.com/98358127/236964598-6145cf69-95d2-4625-aec8-c1a0695acc13.png">|<image width="500" alt="image" src="https://user-images.githubusercontent.com/98358127/236964724-3b9c56b3-9419-4d8e-bc81-58074cf42f36.png">

**Comment by stephendonner** [comment]
a## Verification `IN-PROGRESS` using 






### Prerequisites:
<details>

1. created a directory `tests`, at `/Users/stephendonner/Desktop/tests`
2. dropped a `logo.png` image into `/tests`
3. ran `python3 -m http.server 8000` from `/tests`:

```
stephendonner@Stephens-MBP Desktop % cd tests
stephendonner@Stephens-MBP tests % python3 -m http.server 8000
```

</details>

### Shared Steps:
<details>

1. installed `1.52.86`
5. launched Brave
6. opened `brave://flags`
7. set `brave://flags/#brave-localhost-access-permission` to `Enabled`
8. clicked `Relaunch`
9. opened `brave://adblock`
10. scrolled to `Create custom filters`
11. entered `@@||localhost^$domain=shivankaul.com`
12. clicked `Save changes`
13. loaded `https://shivankaul.com/brave/localhost/` 

`brave://adblock` | `brave://flags`
---------------|-----------------



</details>

### Case 1: Subresource image test - `PASSED`
<details>


### `Allow`

(continued from `Shared Steps`)
1. loaded `https://shivankaul.com/brave/localhost/subresource.html`
2. confirmed I got the permission prompt
3. clicked `Allow`
5. opened `brave://settings/content/localhostAccess`
6. confirmed the site was listed under `Allowed to access localhost resources`

### Confirmed `logo.png` rendered

permission dialog | `Allow`ed | `brave://settings/content/localhostAccess`
------------------|------------|------------------------------------------

### `Block`

(continued from `Shared Steps`)
1. loaded `https://shivankaul.com/brave/localhost/subresource.html`
2. confirmed I got the permission prompt
3. clicked `Block`
4. opened `brave://settings/content/localhostAccess`
5. confirmed the site was listed under `Not allowed to access localhost resources`

### Confirmed `logo.png` was blocked, and a broken-image icon displayed

`Block`ed | `brave://settings/content/localhostAccess`
-----------|-------------------------------------------







</details>


### Case 2: Service worker test - `PASSED`
<details>

### `Allow`

(continued from `Shared Steps`)

1. loaded `https://shivankaul.com/brave/localhost/sw.html`
2. clicked `Allow`
3. opened `brave://settings/content/localhostAccess`
4. confirmed the site was listed under `Allowed to access localhost resources`


### Confirmed `logo.png` rendered

permission dialog | `Allow`ed | `brave://settings/content/localhostAccess`
------------------|------------|------------------------------------------



### `Block`

(continued from `Shared Steps`)


1. loaded `https://shivankaul.com/brave/localhost/sw.html`
2. clicked `Block`
3. opened `brave://settings/content/localhostAccess`
4. confirmed the site was listed under `Not allowed to access localhost resources`

### Confirmed `logo.png` was blocked, and a broken-image icon displayed

`Block`ed | `brave://settings/content/localhostAccess`
-----------|-------------------------------------------





</details>


### Case 3: Websockets test - `PASSED`
<details>

Prerequisites:

* installed `Node.js`
* ran `npm install ws`
* ran `node ws_server.js`

(continued from `Shared Steps`)
1. loaded `https://shivankaul.com/brave/localhost/`
2. clicked on `websockets test page` (`https://shivankaul.com/brave/localhost/ws_client.html`)
3. waited 5 seconds for the redirect to happen
4. opened the `Developer` console
5. confirmed message `ping from server`
6. confirmed message `pong from client` in my `node` terminal
7. loaded `brave://settings/content/localhostAccess`
8. confirmed site entry was added to `Allowed to access localhost resources`

### `Allow`

permission dialog | `Allow`ed | `pong from client!` | `brave://settings/content/localhostAccess`
------------------|------------|--------------------|------------------------------------------


### `Block`

(continued from `Shared Steps`)
1. loaded `https://shivankaul.com/brave/localhost/`
2. clicked on `websockets test page` (`https://shivankaul.com/brave/localhost/ws_client.html`)
3. waited 5 seconds for the redirect to happen
4. opened the `Developer` console
5. clicked `Block`
6. opened `brave://settings/content/localhostAccess`
9. confirmed site entry was added to `Not allowed to access localhost resources`

`Block`ed | `brave://settings/content/localhostAccess`
-----------|------------------------------------------




</details>


### Case 4: Request in <iframe> test - `PASSED`
<details>

### `Allow`

(continued from `Shared Steps`)

1. load `https://shivankaul.com/brave/localhost/`
10. clicked on `request in iframe test page` (`https://shivankaul.com/brave/localhost/iframe.html`)
11. waited 5 seconds for the redirect to happen
12. clicked `Allow`
13. confirmed my `logo.png` image was loaded and rendered
14. (now a 5-second timer in the iframe kicks in, and replaces the image)
15. opened `brave://settings/content/localhostAccess`
16. confirmed site entry in `Allowed to access localhost resources`


step 1-2 | step 3 | step 4 | step 5 | step 6 | `brave://settings/content/localhostAccess`
-----|-----|------|------|-----|-------


### `Block`


(continued from `Shared Steps`)

1. loaded `https://shivankaul.com/brave/localhost/`
2. clicked on request in iframe test page (`https://shivankaul.com/brave/localhost/iframe.html`)
3. waited 5 seconds for the redirect to happen
4. clicked `Block`
7. waited
8. opened `brave://settings/content/localhostAccess`
9. confirmed site entry in `Not allowed to access localhost resources`

### Confirmed `logo.png` did not load nor render

step 1-2 | step 4 | step 5 | `brave://settings/content/localhostAccess`
---------|------|---------|-------------------------------------------



</details>

**Comment by ego-lay-atman-bay** [comment]
I am having an issue with websites not being able to make localhost requests. The current situation I'm in is that I'm uploading to youtube from my terminal, but in order to do that, I need oauth2 consent screen, which sends the callback to `https://localhost:8080/oauth2callback`. Every time I try to allow access to my account, it says something went wrong because it can't send to my localhost server that I need. I had to open google chrome just to get this to work, which I don't like.

I really like the idea of having a prompt whenever a website first tries to send a request to localhost, and it would be like asking for mic/camera access. This way, as a developer, I can let websites request to localhost whenever I need. Of course there would be an option in the settings to always not allow, prompt the user, or always allow. I think that would be better than just blocking them all the time, and not even warning the user (heck, even the console didn't even say localhost was blocked).

**Comment by ShivanKaul** [comment]
> The current situation I'm in is that I'm uploading to youtube from my terminal, but in order to do that, I need oauth2 consent screen, which sends the callback to https://localhost:8080/oauth2callback

What's the website that tries to make the localhost connection? While we come up with something easier, you can selectively add the website to brave://settings/content/localhostAccess (`Allowed to access localhost resources`). Make sure you have the feature flag turned on (brave://flags/#brave-localhost-access-permission).

**Comment by ego-lay-atman-bay** [comment]
> What's the website that tries to make the localhost connection?

Google. I would think that you'd get that from me mentioning that I'm trying to upload to **youtube**, which uses google accounts for youtube channels.

**Comment by ShivanKaul** [comment]
What matters is that the specific [content settings pattern](https://developer.chrome.com/docs/extensions/reference/api/contentSettings) you specify on the content settings page matches the site making the call to the localhost URL. 

<img width="1089" alt="image" src="https://github.com/brave/brave-browser/assets/5284154/59831078-e42f-41e3-9f58-59de13dd1cd1">

**Comment by ego-lay-atman-bay** [comment]
Ah, ok.

**Comment by banool** [comment]
Using Brave version 1.61.104 I can't see any localhost related settings in brave://settings/content. I'd like to allowlist localhost access for certain sites, how do I do that?

**Comment by ego-lay-atman-bay** [comment]
> Using Brave version 1.61.104 I can't see any localhost related settings in brave://settings/content. I'd like to allowlist localhost access for certain sites, how do I do that? Do I just need to wait for a newer version of the browser to roll out?

You have to first go to brave://flags/#brave-localhost-access-permission and enable it (then restart the browser).

**Comment by zvictor** [comment]
For anyone else still lost:

1. go to `brave://flags/#brave-localhost-access-permission` and enable it
1. restart the browser
1. go to `brave://settings/content`, then `Additional permissions` and `Localhost access` should be there:

![Image](https://github.com/user-attachments/assets/ae6b04c6-0586-4a99-868f-d7a71dac5e99)

Or try `brave://settings/content/localhostAccess` directly:

![Image](https://github.com/user-attachments/assets/cdee256c-3055-44dd-97de-ae4254e4f95d)

**Comment by LinuxfarmerHH** [comment]
For information purposes:

In Germany we have an official government app (AusweisApp2) for Linux, Mac and Windows that unlock webpages through 127.0.0.1. The government webpage tries to access the app webserver on 127.0.0.1 and fails if this is blocked. So for usage of Brave browser it's urgent to implement this special connection.

**Comment by MicahZoltu** [comment]
> In Germany we have an official government app (AusweisApp2) for Linux, Mac and Windows that unlock webpages through 127.0.0.1. The government webpage tries to access the app webserver on 127.0.0.1 and fails if this is blocked. So for usage of Brave browser it's urgent to implement this special connection.

I don't think the solution here is to have Brave whitelist a particular app by a particular developer.  It is for that developer to either lobby Brave to open things up for everyone, or for that developer to design their system so that it works within the constraints of what browsers allow.

**Comment by ShivanKaul** [comment]
We're working on V2 of this that will not use an allowlist.
