### ISSUE TITLE
The new beta lost the "New circuit for this site" button

### ISSUE THREAD

**Issue by Qix-** [brave/brave-browser#2734]
**Brave version:** Version 0.58.18 Chromium: 71.0.3578.98 (Official Build) (64-bit)

The template didn't really help much in this case, sorry

The new version of Brave seems to have gotten rid of the familiar Tor interface for a much 'flashier' version, but one that doesn't have any of the Tor related functionality...

How do you change tor circuits for a site in the newest version?

**Comment by Qix-** [comment]
I also can't find where Brave displays the current circuit locations, though I'm not sure if Brave could beforehand (it's something I'm missing from the official browser anyway).

**Comment by srirambv** [comment]
New Tor Identity is available in the hamburger menu
![image](https://user-images.githubusercontent.com/17010094/50423276-4f89b280-0879-11e9-86f4-7becf82ab766.png)

Right now there is no possible way to see the circuit details. This was never implemented in Brave. It will be available in future

**Comment by Qix-** [comment]
New tor identity is not the same as a new circuit, though.

**Comment by srirambv** [comment]
New Tor Identity on Brave == New circuit on Tor Browser.

@riastradh-brave @tomlowenthal correct me if I am wrong on the above analogy

**Comment by Qix-** [comment]
That's fine and well, but IIRC the Tor Browser will clear all tabs, flush all temporal information for the current browsing session, and construct new circuits for all sites.

That's not what "New circuit for this site" does. Brave is using the exact same terminology and phrasing as the Tor browser to do something completely different.

**Comment by tomlowenthal** [comment]
@Qix- Can you point me to where Tor Browser's "New Identity" behavior is documented?

**Comment by Qix-** [comment]
Quick Google search found this. The official site seems to be down for me. 

https://tor.stackexchange.com/a/13986

**Comment by tomlowenthal** [comment]
Opened a new issue for the details of the "New Identity" behavior.

**Comment by diracdeltas** [comment]
I'm not sure why this was closed. Anyway it's now open as #11822
