### ISSUE TITLE
Crash when viewing sync code

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#27343]
## Description 

Crash when viewing sync code in brave://settings/braveSync/setup

Crash Report ID: `1c171b00-fcb4-3d09-0000-000000000000`

## Steps to Reproduce

Preconditions: Have existing sync chain with some devices

   1. Open brave://settings/braveSync/setup
   2. Remove 1 device from sync chain
   3. Click on View Sync Code

## Actual result:

App crashes

## Expected result:
Sync codes should be presented

## Reproduces how often: 

intermittent, very uncommon

## Brave version (brave://version info)

Brave | 1.46.134 Chromium: 108.0.5359.94 (Official Build) (x86_64)
-- | --
Revision | 713576b895246504ccc6b92c2fb8ce2d60194074-refs/branch-heads/5359_71@{#3}
OS | macOS Version 12.6 (Build 21G115)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? No

**Comment by AlexeyBarabash** [comment]
Here are the STR to make this crash
1. Setup the sync chain, enough to have one device
2. Open brave://settings/braveSync/setup
3. Press `View sync code` button
4. Adjust system time on two days before
5. Press `View QR Code` link

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.48.118 Chromium: 109.0.5414.80 (Official Build) beta (64-bit)
-- | --
Revision | 0f69b168d36a06cace4365e9f029fa987afa5633-refs/branch-heads/5414@{#1178}
OS | Windows 11 Version 21H2 (Build 22000.1335)
```

Reproduced the issue in `1.47.165` using the STR from https://github.com/brave/brave-browser/issues/27343#issuecomment-1351906678

Steps: 

1. Install 1.48.118
2. launch Brave
3. click Skip >> Skip >> Finish
4. visit brave://sync
5. click on Start using sync ---> Start a new Sync Chain
6. click Computer
7. click OK
8. click `Manage your synced devices`
9. click `View Sync Code`
10. go to Windows>>Time & language >> Date & Time 
11. change the time to two days prior (i.e.  from Jan 9 to Jan 7)
12. click `View QR Code` link

#### Confirmed QR code is shown

step3|step 4|step 7|step 9|step 10|step 11|step 12|QR code
----|----|----|----|----|---|---|----
<img width="458" alt="image" src="https://user-images.githubusercontent.com/98358127/211403994-6f8f6999-f339-4743-a4d4-0b77b7345d4c.png">|<img width="450" alt="image" src="https://user-images.githubusercontent.com/98358127/211404116-52c820b3-1b1b-4d71-a9c7-0f785956530d.png">|<img width="458" alt="image" src="https://user-images.githubusercontent.com/98358127/211404220-7fd9e76b-c552-4fbc-aede-c92bff026c41.png">|<img width="451" alt="image" src="https://user-images.githubusercontent.com/98358127/211404290-c91ab25d-0587-4a43-ad44-5280e6c171f2.png">|<img width="472" alt="image" src="https://user-images.githubusercontent.com/98358127/211404846-664c6768-c624-4142-a4e0-20bddf0500ee.png">|<img width="475" alt="image" src="https://user-images.githubusercontent.com/98358127/211404906-e93313d9-6c29-44ef-a503-d774474c906d.png">|<img width="458" alt="image" src="https://user-images.githubusercontent.com/98358127/211404427-fd55e881-1675-4b95-8daf-469df9441217.png">|<img width="455" alt="image" src="https://user-images.githubusercontent.com/98358127/211404984-b64c3377-07a4-454f-8886-87ec18e1c3a7.png">

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.48.118 Chromium: 109.0.5414.80 (Official Build) beta (x86_64)
-- | --
Revision | 0f69b168d36a06cace4365e9f029fa987afa5633-refs/branch-heads/5414@{#1178}
OS | macOS Version 11.7.2 (Build 20G1020)

### Steps:

1. installed `1.48.118`
2. launched Brave
3. clicked `Skip` >> `Skip` >> `Finish`
4. visited `brave://sync`
5. clicked on `Start using sync` ---> `Start a new Sync Chain`
6. clicked Computer
7. clicked OK
8. clicked Manage your synced devices
9. clicked View Sync Code
10. go to `Apple` >> `System Preferences` >> `Date & Time`
11. change the time to two days prior (i.e. from Jan 9 to Jan 7)
12. click `View QR Code` link
13. fixed system date
14. joined the Sync chain using iOS

#### Confirmed no crash when viewing or joining the Sync chain using the QR code

step 3 | step 4 | step 7 | step 9 | step 11 | step 12 | QR  code | step 14
-------|-------|--------|-------|---------|--------|--------|----------
<img width="1312" alt="Screen Shot 2023-01-09 at 4 01 50 PM" src="https://user-images.githubusercontent.com/387249/211432626-f38141c0-81f1-482d-8561-f1f6e1c37564.png"> | <img width="1312" alt="Screen Shot 2023-01-09 at 4 02 00 PM" src="https://user-images.githubusercontent.com/387249/211432651-9ec3b0f1-0590-4e9a-97bc-8483bf672ff5.png"> | <img width="1312" alt="Screen Shot 2023-01-09 at 4 02 09 PM" src="https://user-images.githubusercontent.com/387249/211432701-96014764-ef38-4e9f-87ae-eb22c7bbd00d.png"> | <img width="1312" alt="Screen Shot 2023-01-09 at 4 11 38 PM" src="https://user-images.githubusercontent.com/387249/211433093-df66655a-a756-4b42-b549-46ccb93a58c5.png"> | <img width="665" alt="Screen Shot 2023-01-09 at 4 03 41 PM" src="https://user-images.githubusercontent.com/387249/211433022-157477b7-ece2-4c77-bf96-6498624abb4a.png"> | <img width="1312" alt="Screen Shot 2023-01-09 at 4 02 09 PM" src="https://user-images.githubusercontent.com/387249/211432993-3e0c0ac7-38b8-4525-80e8-d420108a647c.png"> | <img width="1312" alt="Screen Shot 2023-01-07 at 4 03 51 PM" src="https://user-images.githubusercontent.com/387249/211432919-e750b584-3e40-4018-865b-b97aafc74ce8.png"> | <img width="1312" alt="Screen Shot 2023-01-09 at 4 05 08 PM" src="https://user-images.githubusercontent.com/387249/211432835-24cca566-8990-4dae-94ac-5ebef2badb75.png">

**Comment by LaurenWags** [comment]
Marking as `QA/Blocked` as this will be uplifted to 1.47.x maintenance release and will need to be retested there.

**Comment by kjozwiak** [comment]
The above requires `1.47.176` or higher for `1.47.x` verification 👍

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.47.177 Chromium: 109.0.5414.87 (Official Build) (64-bit) 
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | Ubuntu 18.04 LTS

Reproduced the issue in `1.47.169` 
<details>

![image](https://user-images.githubusercontent.com/34715963/213470798-b110c6f9-1ddc-4ae9-b69a-f04da2d5c4b4.png)


</details>

Verified in 1.47.177

Steps: 

1. Install 1.47.177
2. launch Brave
3. click `Skip` >> `Skip` >> `Finish`
4. visit `brave://sync`
5. click on `Start using sync` ---> `Start a new Sync Chain`
6. click `Computer`
7. click `OK`
8. click `Manage your synced devices`
9. click `View Sync Code`
10. change system date to two days prior (i.e.  from Jan 9 to Jan 7)
11. click `View QR Code` link

#### Confirmed QR code is shown

step3|step 4|step 7|step 9|step 10|step 12
----|----|----|----|----|---
![image](https://user-images.githubusercontent.com/34715963/213473961-5b354262-fdd6-428b-ae0e-aef4c4540683.png)|![image](https://user-images.githubusercontent.com/34715963/213474033-4c2a7bab-0da2-4c53-9856-05a59c2dc55b.png)|![image](https://user-images.githubusercontent.com/34715963/213474417-a3546855-112a-4aed-a61c-a9073bc72dcd.png)|![image](https://user-images.githubusercontent.com/34715963/213474553-cfeeab08-01f4-4168-a823-83293199c8d7.png)|![image](https://user-images.githubusercontent.com/34715963/213474617-ed585c7a-c12a-42d8-8094-931668232e62.png)|![image](https://user-images.githubusercontent.com/34715963/213474875-4ec1186a-fd9c-4d9e-bb93-d1f66751d4a5.png)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED`
```
Brave | 1.47.177 Chromium: 109.0.5414.87 (Official Build) (64-bit)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | Windows 11 Version 21H2 (Build 22000.1455)
```

Steps: 

1. Install 1.47.177
2. launch Brave
3. open a new-tab
4. visit `brave://sync`
5. click on `Start using sync` ---> `Start a new Sync Chain`
6. click `Computer`
7. click `OK`
8. click `Manage your synced devices`
9. click `View Sync Code`
10. go to Windows Settings>>Time & language >> Date & Time 
11. change system date to two days prior (i.e.  from Jan 19 to Jan 17)
12. click `View QR Code` link

#### Confirmed no crashes occurred and QR code is shown 

step5|step 7|step 8|step 9|step 11|QR code
-------|--------|--------|-------|--------|-------
<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/213484935-66cf9567-a47c-43d9-894f-89c03ff7c3b9.png">|<img width="458" alt="image" src="https://user-images.githubusercontent.com/98358127/213485026-6af37853-bc4e-43dc-93ec-b3caeb090577.png">|<img width="453" alt="image" src="https://user-images.githubusercontent.com/98358127/213486531-9816ee74-443a-4f53-8e24-de3ae77d7063.png">|<img width="458" alt="image" src="https://user-images.githubusercontent.com/98358127/213485131-c15bb4d4-99ae-4b6e-9db9-822dde803816.png">|<img width="508" alt="image" src="https://user-images.githubusercontent.com/98358127/213485328-a930113a-dfde-44d0-9d89-9a8f32e8754e.png">|<img width="458" alt="image" src="https://user-images.githubusercontent.com/98358127/213485660-64ba2998-39c7-44ab-afbd-07576240f5a0.png">

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 



Brave | 1.47.177 Chromium: 109.0.5414.87 (Official Build) (x86_64)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | macOS Version 11.7.2 (Build 20G1020)



### Steps:

1. installed `1.47.177`
2. launched Brave
3. clicked `Skip` >> `Skip` >> `Finish`
4. visited `brave://sync`
5. clicked on `Start using sync` ---> `Start a new Sync Chain`
6. clicked Computer
7. clicked OK
8. clicked Manage your synced devices
9. clicked View Sync Code
10. go to `Apple` >> `System Preferences` >> `Date & Time`
11. change the time to two days prior (i.e. from Jan 19 to Jan 17)
12. click `View QR Code` link
13. fixed system date
14. joined the Sync chain using iOS

#### Confirmed no crash when viewing or joining the Sync chain using the QR code

step 3 | step 4 | step 7 | step 9 | step 11 | step 12 | QR  code | step 14
-------|-------|--------|-------|---------|--------|--------|----------
