### ISSUE TITLE
Frontend Android support for running DiscoverAssets on page refresh

### ISSUE THREAD

**Issue by nvonpentz** [brave/brave-browser#27344]
Same as https://github.com/brave/brave-browser/issues/26547 but for Android.

**Comment by srirambv** [comment]
Verification passed on Lenovo Tab with Android 12 running 1.49.118 x64 build
- Verified steps from [brave/brave-core#16768](https://github.com/brave/brave-core/pull/16768)
- Verified asset auto discovery spinner icon is shown when loading assets
![image](https://user-images.githubusercontent.com/17010094/222775006-55c7f37f-4f63-409c-8af6-5ff796bfa0b2.png)
