### ISSUE TITLE
Implement Solana support for "The Wallet Standard"

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#27340]
Implement Solana support for "The Wallet Standard" https://github.com/wallet-standard/wallet-standard support in brave-core

> jsx
> Hi Brave team :slightly_smiling_face: The Wallet Standard (https://github.com/wallet-standard/wallet-standard) reached 1.0.0 before Breakpoint, and has been stable since. It’s used by many major Solana dapps now (see https://github.com/solana-labs/wallet-adapter/issues/604 for an incomplete list). There’s an integration guide for wallets (https://github.com/solana-labs/wallet-standard/blob/master/WALLET.md). Since Brave already presents a Phantom-compatible interface, this should be very simple to add. It’s a nonbreaking change (your current interfaces will continue to work exactly as is) and adds no external runtime dependencies. If you integrate this, Brave will show up in the top of the wallet adapter list for all these applications and more. You won’t have to overwrite window.solana or conflict with other wallets. Please let me know if I can help support you!

**Comment by kjozwiak** [comment]
The above requires `1.47.178` or higher for `1.47.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.47.181 Chromium: 109.0.5414.87 (Official Build) (64-bit)
-- | --
Revision | `2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}`
OS | Linux

- Verified steps from [brave/brave-core#16724](https://github.com/brave/brave-core/pull/16724)
- Verified able to submit `SignTransaction`, `SignMessage` and `SendTransaction`
- Verified legacy transaction is disabled

https://user-images.githubusercontent.com/17010094/214068709-87378586-8d36-46d5-8ff7-ed8c3ad17fd7.mp4


---------------------

Verification passed on 

Brave | 1.47.181 Chromium: 109.0.5414.87 (Official Build) (64-bit)
-- | --
Revision | `2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#16724](https://github.com/brave/brave-core/pull/16724)
- Verified able to submit `SignTransaction`, `SignMessage` and `SendTransaction`
- Verified legacy transaction is disabled

https://user-images.githubusercontent.com/17010094/214071122-c2f84db1-11fb-4d6a-9c5c-1223ca8bec0f.mp4

---------------------

Verification passed on 

Brave | 1.47.181 Chromium: 109.0.5414.87 (Official Build) (arm64)
-- | --
Revision | `2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#16724](https://github.com/brave/brave-core/pull/16724)
- Verified able to submit `SignTransaction`, `SignMessage` and `SendTransaction`
- Verified legacy transaction is disabled

https://user-images.githubusercontent.com/17010094/214072355-47b9dfef-2e90-4f54-81e6-40d343eb4c44.mov

**Comment by kjozwiak** [comment]
We'll need to recheck this once @darkdh lands a fix that resolves the performance issues mentioned via https://github.com/brave/brave-browser/issues/27997. @darkdh can you let is know once the performance issues are fixed and the above can be verified? We'll probably uplift the above into `1.47.x` as well with the fix.

**Comment by kjozwiak** [comment]
Moving this into `1.48.x` as we neve received another `C109` minor chromium bump that would have triggered another `1.47.x` release. We'll leave https://github.com/brave/brave-core/milestone/267 as there's code that landed in `1.47.x` but we'll close off the `1.47.x - Release #6` milestone and move all the issues within `1.48.x`. The above can be verified with `1.48.156` for `1.48.x`.

**Comment by kjozwiak** [comment]
@srirambv we'll need to re-run through the above now that https://github.com/brave/brave-browser/issues/27997 was fixed/merged. Originally it was planned to go out via `1.47.x` but looks like we never received a `1.47.x` as per https://github.com/brave/brave-browser/issues/27340#issuecomment-1418546176.

I labelled https://github.com/brave/brave-browser/issues/27997#issuecomment-1418544839 as `QA/No` but if you're running through the above and have some time, can run through the cases that @darkdh mentioned via https://github.com/brave/brave-core/pull/16868#issue-1557445940.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.47.182 x64 build
- Verified steps from [brave/brave-core#16724](https://github.com/brave/brave-core/pull/16724)
- Verified able to submit `SignTransaction`, `SignMessage` and `SendTransaction`
- Verified legacy transaction is disabled
 

Oppo Reno 5 (Android 13) | Lenovo Tab (Android 12)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/216954794-7d819ef4-cdb1-445c-9350-9cb2cbba9b5c.mp4> | <video  src=https://user-images.githubusercontent.com/17010094/216954843-13d0d482-20c0-4179-8292-f9d0bbd975e4.mp4>

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.48.157 Chromium: 110.0.5481.77 (Official Build) (64-bit) 
-- | --
Revision | `65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}`
OS | Linux

- Verified steps from [brave/brave-core#16724](https://github.com/brave/brave-core/pull/16724)
- Verified able to submit `SignTransaction`, `SignMessage` and `SendTransaction`
- Verified legacy transaction is disabled

https://user-images.githubusercontent.com/17010094/216966684-c7d2be4a-aec6-4d88-982b-79fa7e7d37e2.mp4

---------------------

Verification passed on 

Brave | 1.48.157 Chromium: 110.0.5481.77 (Official Build) (64-bit)
-- | --
Revision | `65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#16724](https://github.com/brave/brave-core/pull/16724)
- Verified able to submit `SignTransaction`, `SignMessage` and `SendTransaction`
- Verified legacy transaction is disabled

https://user-images.githubusercontent.com/17010094/216965300-11a3ed0a-50e8-4112-ade3-58fce6cc99b3.mp4

---------------------

Verification passed on 

Brave | 1.48.157 Chromium: 110.0.5481.77 (Official Build) (arm64)
-- | --
Revision | `65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#16724](https://github.com/brave/brave-core/pull/16724)
- Verified able to submit `SignTransaction`, `SignMessage` and `SendTransaction`
- Verified legacy transaction is disabled

https://user-images.githubusercontent.com/17010094/216966208-85af903b-53f7-4fdb-bdbe-a3e86d22641d.mov
