### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by jaredthirsk** [brave/brave-browser#27352]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.46.140  Chromium: 108.0.5359.99
Operating System: Windows NT 10.0.19045

URL (if applicable) where crash occurred:  private webapp

Can you reproduce this crash?  Yes

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Go to my webapp's page
2. Make sure the window is short enough, HTML content area of 1014px or less
3. Press Ctrl-P to print
4. Access violation

 !*!*! NOTE: It works if I make my browser taller:
1. Go to my webapp's page
2. Make sure the window is short enough, HTML content area of 1118px or greater
3. Press Ctrl-P to print
4. Print preview shows up properly

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/cdc81b00-fcb4-3d09-0000-000000000000

**Comment by jaredthirsk** [comment]
I reported this to the Chromium team:

https://bugs.chromium.org/p/chromium/issues/detail?id=1400797

I wonder if it is related to similar issues like this one:
https://bugs.chromium.org/p/chromium/issues/detail?id=1399456

**Comment by iefremov** [comment]
fixed upstream
