### ISSUE TITLE
Add Local Storage pref for Portfolio Filters

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#27364]
## Description 
We need to add `Local Storage` prefs for the `Portfolio Filters` to persist the users choice.

- Network Filter Option
- Asset Filter Option
- Account Filter Option

![Screen Shot 2022-12-13 at 11 44 25 PM](https://user-images.githubusercontent.com/40611140/207515985-a21dfa08-c8ea-4f1a-b4f6-dcaa90b0b77c.png)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.50.93 Chromium: 111.0.5563.64 (Official Build) beta  (64-bit) 
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Linux

- Verified steps from [brave/brave-core#16959](https://github.com/brave/brave-core/pull/16959)
- Verified `Network`,  `Account` and `Asset Filter` changes are retained between page refresh on `Portfolio` page

https://user-images.githubusercontent.com/17010094/225843694-58843693-108a-4703-bd7d-809ab495575e.mp4

---------------------

Verification passed on 

Brave | 1.50.93 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from [brave/brave-core#16959](https://github.com/brave/brave-core/pull/16959)
- Verified `Network`,  `Account` and `Asset Filter` changes are retained between page refresh on `Portfolio` page

https://user-images.githubusercontent.com/17010094/225843754-32b8b9d5-23ac-4e49-896e-ca8e769b24a3.mp4


---------------------

Verification passed on 

Brave | 1.50.93 Chromium: 111.0.5563.64 (Official Build) beta (arm64)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#16959](https://github.com/brave/brave-core/pull/16959)
- Verified `Network`,  `Account` and `Asset Filter` changes are retained between page refresh on `Portfolio` page

https://user-images.githubusercontent.com/17010094/225844423-b3c50938-c0f0-4d5b-8ef3-b25696c827e8.mov
