### ISSUE TITLE
Unable add more than one ERC721 token from token registry

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#27368]
## Description 

Unable add more than one ERC721 token from token registry

## Steps to Reproduce

   1. Search for Punks Comic
   2. Click on the checkbox
   3. Enter the ERC721 id and click on add
   4. Ensure NFT is added in portfolio
   5. Go back to add asset and search for Punks comic again
   6. Can't add a second one from token registry

## Actual result:

Unable add more than one ERC721 token from token registry

## Expected result:
Should be able to add more than one. Experience should be similar to what is there on Android

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.47.126 Chromium: 108.0.5359.99 (Official Build) beta (64-bit)
-- | --
Revision | `410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}`
OS | Windows 11 Version 22H2 (Build 22621.755)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Mostly Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel

**Comment by josheleonard** [comment]
closing - NFTs are no longer shown in the available assets list for adding assets
