### ISSUE TITLE
Error while installing from releases

### ISSUE THREAD

**Issue by thesohelshaikh** [brave/brave-browser#2736]
## Description 
I downloaded the zip available on the releases panel using [this](https://github.com/brave/brave-browser/releases/download/v0.58.18/brave-v0.58.18-win32-x64.zip) link.

## Steps to Reproduce
   1. Download the browser [this](https://github.com/brave/brave-browser/releases/download/v0.58.18/brave-v0.58.18-win32-x64.zip) link
   2. Extract the zipped file.
   3. Run the brave.exe file

## Actual result:
![image](https://user-images.githubusercontent.com/26832180/50416374-49c6a980-0846-11e9-9c65-ef74b18e0123.png)

## Expected result:
The browser should have been installed correctly and should be running when the .exe file was executed.

## Reproduces how often: 
Easily Reproduced

## Brave version (brave://version info)
v0.58.18

**Comment by srirambv** [comment]
You are downloading the zip file which is only required for debug. Please download the exe files from the github release page
