### ISSUE TITLE
Crash when selecting a token from Deposit screen

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#27367]
## Description 

Crash when selecting a token from Deposit screen

## Steps to Reproduce

   1. Switch to Market tab
   2. Select Deposit for Solana
   3. Webview crash when token is selected

## Actual result:

Crash log: https://share.backtrace.io/api/share/SC4ZaPbanFVI0nqrx3BM5J0

https://user-images.githubusercontent.com/17010094/207533033-a6916662-8a26-4a03-9282-429e6f5c2c74.mp4

## Expected result:
No crash

## Reproduces how often: 

Happened once

## Brave version (brave://version info)

Brave | 1.47.126 Chromium: 108.0.5359.99 (Official Build) beta (64-bit)
-- | --
Revision | `410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Not checked

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel @darkdh

**Comment by muliswilliam** [comment]
@srirambv I tried reproducing this on 1.47.186(current production release) and on latest master. I did not experience a crash.

**Comment by HEagle18** [comment]
I couldn't replicate either. Can you try it again @srirambv ?

**Comment by srirambv** [comment]
Can't reproduce it as well. Tried on latest release build. Closing the issue for now. Can reopen if the issue resurfaces again

https://user-images.githubusercontent.com/17010094/220260888-780e5ecc-769d-494d-8a91-ea026124dcfb.mp4
