### ISSUE TITLE
Re-sync is not successful with new secrete code (Follow up of #2552)

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#2737]
## Description 
Re-sync is not successful with new secrete code (Follow up of #2552). 

## Devices
Device A: Windows 10 (Bravebeta 0.59.12)
Device B: Windows 10 (Brave Dev 0.60.4)

## Steps to Reproduce

   1. Setup sync chain between device A and B through secrete code
   2. Delete device B from device A
   3. Setup new sync chain on device A and connect device B (Observe the sync code same as step1 - 
       which is not expected as per #2552)
   4. Verify that, sync did not establish with old syc code (step1)
   5. Refresh the brave://sync on both devices
   6. Setup new sync chain on device A and connect device B (Observe the new sync code display -which 
      is different than step1 sync code)

## Actual result:
Re-sync is not successful with new secrete code
![2552_ win and linux](https://user-images.githubusercontent.com/38657976/50421465-a8e7e680-0865-11e9-8355-946f00bb28e6.gif)

## Expected result:
Re-sync should be successful with New secrete code

## Reproduces how often: 
Always

## Brave version (brave://version info)

Brave | 0.59.12 Chromium: 72.0.3626.17 (Official Build) beta (64-bit)
-- | --
Revision | 08d2140079f8db14c9eb885a803d231b1a30e817-refs/branch-heads/3626@{#315}
OS | Windows

### Reproducible on current release: na
- Does it reproduce on brave-browser dev/beta builds? yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? na
- Is the issue reproducible on the latest version of Chrome? na

### Additional Information
@brave/legacy_qa

**Comment by AlexeyBarabash** [comment]
Thanks @GeetaSarvadnya .
Can reproduce on current master `Version 0.61.0 Chromium: 72.0.3626.28`

**Comment by GeetaSarvadnya** [comment]
Verification passed on 


Brave | 0.59.18 Chromium: 72.0.3626.28 (Official Build) beta (64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Windows

- Verified the STR from description.
