### ISSUE TITLE
Expose SNS feature flag via brave:://flags

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#27378]
AFAIK right now we can only enable it via command line, it would be better to have an entry in brave://flags for users who want to try it. cc @supermassive @lukaslevert

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.48.141 Chromium: 109.0.5414.119 (Official Build) beta (64-bit) 
-- | --
Revision | `772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}`
OS | Linux

- Verified steps from [brave/brave-core#16381](https://github.com/brave/brave-core/pull/16381)
- Verified new flag `brave://flags/#brave-wallet-sns` is available and defaulted to disable
- Verified enabling the flag shows the setting under Web3
- Verified able to resolve `.sol` address 

https://user-images.githubusercontent.com/17010094/215738381-f38669b0-36b4-4d12-999f-29dae930e31f.mp4


---------------------

Verification passed on 

Brave | 1.48.141 Chromium: 109.0.5414.119 (Official Build) beta (64-bit)
-- | --
Revision | `772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#16381](https://github.com/brave/brave-core/pull/16381)
- Verified new flag `brave://flags/#brave-wallet-sns` is available and defaulted to disable
- Verified enabling the flag shows the setting under Web3
- Verified able to resolve `.sol` address 

https://user-images.githubusercontent.com/17010094/215737815-68ecbcd0-0e0c-4826-9e6c-18ece8ff9122.mp4


---------------------

Verification passed on 

Brave | 1.48.141 Chromium: 109.0.5414.119 (Official Build) beta (arm64)
-- | --
Revision | `772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#16381](https://github.com/brave/brave-core/pull/16381)
- Verified new flag `brave://flags/#brave-wallet-sns` is available and defaulted to disable
- Verified enabling the flag shows the setting under Web3
- Verified able to resolve `.sol` address 

https://user-images.githubusercontent.com/17010094/215738766-c6fe5630-7c30-49b2-9379-470418c009fc.mov
