### ISSUE TITLE
Update Send NFT Modal Title

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#27374]
## Description 
- Title should say `Select an NFT to send`

![Screen Shot 2022-12-14 at 9 04 54 AM](https://user-images.githubusercontent.com/40611140/207632107-ba23c2c3-98b9-4f18-bee7-7c79cd3abcb4.png)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.48.139 Chromium: 109.0.5414.87 (Official Build) beta (64-bit) 
-- | --
Revision | `2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}`
OS | Linux

- Verified steps from [brave/brave-core#16372](https://github.com/brave/brave-core/pull/16372)
- Verified Send NFT modal title is updated to reflect NFT

https://user-images.githubusercontent.com/17010094/214490493-a263580c-03d4-48bf-9e70-56a51c3c9a2d.mp4


---------------------

Verification passed on 

Brave | 1.48.139 Chromium: 109.0.5414.87 (Official Build) beta (64-bit)
-- | --
Revision | `2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#16372](https://github.com/brave/brave-core/pull/16372)
- Verified Send NFT modal title is updated to reflect NFT

https://user-images.githubusercontent.com/17010094/214490493-a263580c-03d4-48bf-9e70-56a51c3c9a2d.mp4

---------------------

Verification passed on 

Brave | 1.48.139 Chromium: 109.0.5414.87 (Official Build) beta (arm64)
-- | --
Revision | `2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#16372](https://github.com/brave/brave-core/pull/16372)
- Verified Send NFT modal title is updated to reflect NFT

https://user-images.githubusercontent.com/17010094/214490317-3b265804-bc97-4e03-a266-f6e6f0f978a5.mov
