### ISSUE TITLE
[Android] Remove "anonymous" from onboarding diagnostics checkbox

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#27387]
## Description
Remove the word `anonymous` from the onboarding diagnostics checkbox (the first checkbox only).

![image](https://user-images.githubusercontent.com/28269287/207721341-859c3860-3570-4e77-a064-afff91f0591b.png)

### Why
The Desktop implementation recently went through a security review and it was decided to remove the word `anonymous`. Android should match. https://github.com/brave/brave-browser/issues/27339

**Comment by rebron** [comment]
cc: @fmarier @PrivacyMatters

**Comment by stephendonner** [comment]
## Verified `PASSED` using `1.48.134`, `Chromium 109.0.5414.87` on a `Google Pixel XL` running `Android 9`

### Steps:
1. installed `1.48.134`
2. launched Brave
3. tapped `Not now` on the 1st onboarding screen
4. examined the text copy on the 2nd screen

#### Confirmed the word `anonymous` has been removed

![Screenshot_20230121-223207](https://user-images.githubusercontent.com/387249/213903828-0b24701a-0b20-474a-af3b-689272fcc64e.png)
