### ISSUE TITLE
Add different reporting cadences for P3A

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#27386]
Add three classes of reporting cadences for P3A metrics:

1. Slow - will be sent once per month
2. Typical - currently sent once per week
3. Express - will be sent once per day

Add a "cadence" field in the JSON payload which will contain one of the classes above.

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.49.91 Chromium: 110.0.5481.77 (Official Build) beta (64-bit)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | Windows 10 Version 21H2 (Build 19044.2486)

```
