### ISSUE TITLE
'Backup Wallet' Should Link to Backup Page

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#2739]
## Description 
_Backup Wallet_ prompt doesn't navigate to the backup-view in Rewards.

## Steps to Reproduce
Click _Backup Wallet_ from the following prompt:

![image](https://user-images.githubusercontent.com/815158/50425583-d9b52500-083f-11e9-9038-9848e9836e21.png)

## Actual result:
Not taken to backup wallet view

## Expected result:
Should be taken directly to backup wallet view

## Reproduces how often: 
Always

## Brave version (brave://version info)
0.58.18

### Reproducible on current release:
Yes

### Additional Information
Originally implemented here: #1164

**Comment by ryanml** [comment]
This one is no longer blocked

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.62.17 Chromium: 73.0.3683.39 (Official Build) dev (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

Used test plan from https://github.com/brave/brave-core/pull/1641

Added: `"backup_notification_frequency":"50000000","backup_notification_interval":"50000000"`
to `brave.rewards` section of `Preferences` file

![2739](https://user-images.githubusercontent.com/34715963/53852673-2006cd00-3fc3-11e9-8bcc-bc95d960f839.gif)
