### ISSUE TITLE
Add SNS pref for Android

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#27392]
Add SNS pref for Android to enable .sol domains resolution
![image](https://user-images.githubusercontent.com/168356/207778219-31992d1d-a288-46f7-b268-492b98020015.png)

**Comment by Uni-verse** [comment]
In Progress on `Samsung Galaxy S21` using version:

```
Brave	1.48.157 Chromium: 110.0.5481.77 (Official Build) (64-bit) 
Revision	65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS	Android 13; Build/TP1A.220624.014
```
