### ISSUE TITLE
Performance tab is empty

### ISSUE THREAD

**Issue by paulcarroty** [brave/brave-browser#27395]
## Description & Steps to Reproduce
After enabling "Enable the battery saver mode feature in the settings" in `brave://flags` the performance tab in settings is empty

## Brave version (brave://version info)
1.46.144 Chromium: 108.0.5359.128 (Official Build) (64-bit) 
Revision: 1cd27afdb8e5d057070c0961e04c490d2aca1aa0-refs/branch-heads/5359@{#1185}
OS: Linux

**Comment by integrated-circuit** [comment]
+1 happens to me 
![image](https://user-images.githubusercontent.com/68387582/213186540-aeb1b66a-45f5-44f4-9d98-fa1b3580fb90.png)
