### ISSUE TITLE
Update makes 2 downloads every time

### ISSUE THREAD

**Issue by Clorr** [brave/brave-browser#27398]
## Description 
Every time there is an update to Brave Browser, I have 2 downloads : A first small download, and a big that is around 130MB
It looks like a failed incremental update, but maybe it's not. In that case don't take this in account.

## Steps to Reproduce
   1. When an update is available, click on the update button

## Actual result:
One small download starts and complete, then a second download, of around 130MB, starts also

## Expected result:
Why 2 downloads ? Is the first download a delta and the second a full ?
Only one, hopefully delta (small) update should happen

## Reproduces how often: 
Every time since I installed Brave (more than one year ago)

## Brave version (brave://version info)
1.46.144 Chromium: 108.0.5359.128 (Build officiel) (x86_64)
macOS Version 10.15.7 (assemblage 19H2026)

## Version/Channel Information:
Révision | 1cd27afdb8e5d057070c0961e04c490d2aca1aa0-refs/branch-heads/5359@{#1185}

**Comment by diracdeltas** [comment]
@mherrmann

**Comment by mherrmann** [comment]
Thank you for reporting this @Clorr. Your suspicion is correct. I can reproduce this on macOS 10.15.7, updating Brave 1.46.140 -> 1.146.144. This should be a pure delta update (20 MB in this case). But the update mechanism downloads first the delta and then the full 135 MB installer. (This can be inspected with Fiddler Everywhere, for example.)

**Comment by LaurenWags** [comment]
Verification in progress with macOS arm64 12.6.3 using various versions.

See https://bravesoftware.slack.com/archives/C01EVLWS8R5/p1677031515215569 for additional discussion/details.

General note - when installing via .pkg, may still get the sparkle update popups UI where you need to allow the download/install of new version. See https://github.com/brave/brave-browser/issues/9562.

For all failed cases below, the update still occurs, it just falls back to full installer. See https://github.com/brave/brave-browser/issues/28915 for additional information.

<details>
<summary>Delta Installer - InProgress</summary>

Note, for all cases below `1.50.77` was the current public beta build (meaning, available on the update server). `1.49.108` was the _previous_ public beta build (meaning, the last beta version that was available on the update server _prior_ to `1.50.77`). When going from one public build to the next, the delta should be served.

All cases below check background updates.

<details>
<summary>Case 1 - arm64 (.dmg) --> arm64 - InProgress</summary>

Objective: Confirm delta installer used to update from arm64 `1.49.108` --> arm64 `1.50.77`, use .dmg file for initial download

1. Install `1.49.108` (arm64 .dmg version, not universal), close quickly after launching
2. Close browser, advance system clock ~3hrs
3. Ensure Fiddler or similar program is running
4. Relaunch browser from terminal with `--args --enable-logging=stderr`
5. Watch logs and Fiddler
6. Confirm delta update was served successfully (did not fall back to full installer)
7. Once logs mention "will install update" this means download is complete, relaunch
8. Confirm updated version on brave://version

Step 1 | Step 6 | Step 8
--- | --- | ---

Logs from step 7:

```

```

</details>

</details>

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using `Big Sur` `11.7.4`

Delta
Full installer
Update on test channel
On-demand updates

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using `Big Sur` `11.7.4`, `M1/amd64`
