### ISSUE TITLE
Update macOS Nightly Icons to be correct size

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#27399]
## Description 

We need to update our MacOS icons with a minor size update.
Here are the required images
https://drive.google.com/drive/folders/17A01qCt12Tc1qsFMyvGfbnNigcjuSKmU?usp=share_link

**Comment by rebron** [comment]
Closing as dupe of https://github.com/brave/brave-browser/issues/14801 and fixed in 1.51.x. @aguscruiz reopen if I'm incorrect.
