### ISSUE TITLE
Change "No wallet" text in Custodial account connection info in `brave://rewards-internals`

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#27409]
## Description

STR:

1. New profile or one without any Rewards profile generated yet.
2. Go to brave://rewards-internals
3. Observe how it says "Rewards state: Mo wallet" 

![image](https://user-images.githubusercontent.com/11497541/207999263-f4d2b888-76c3-4a61-a84e-ee3e066022e3.png)

## Solution

Change text to:

`Rewards state: Rewards profile not yet created`

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.48.125 Chromium: 109.0.5414.87 (Official Build) beta (x86_64)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | macOS Version 12.6.2 (Build 21G320)
```

**Comment by stephendonner** [comment]
## Verified `PASSED` using `1.48.134` on a `Google Pixel XL` running `Android 9`


### Steps:
1. installed `1.48.134`
2. launched Brave
3. loaded `brave://rewards-internals`
4. checked `Rewards state` status text

#### Confirmed status now reads `Rewards profile not yet created`

`1.48.134` | `1.47.161`
-----------|----------
![Screenshot_20230120-233459](https://user-images.githubusercontent.com/387249/213849190-e1cfeebf-7ffb-4189-9ccd-b01556b8ae6d.png) | ![Screenshot_20230120-233258](https://user-images.githubusercontent.com/387249/213849189-7b8755ce-2397-4339-aaef-7f52b9c405ed.png)
