### ISSUE TITLE
Transaction Submitted Logo is Poorly Rendered

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#27403]
## Description 
The `Transaction Submitted` logo looks to be poorly rendered with white artifacts.
We need to change out for a higher quality graphic.

![image](https://user-images.githubusercontent.com/40611140/207924922-b9c2011a-5e01-4883-b24e-0f66fabaa4c3.png)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.48.139 Chromium: 109.0.5414.87 (Official Build) beta (64-bit) 
-- | --
Revision | `2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}`
OS | Linux

- Verified steps from [brave/brave-core#16387](https://github.com/brave/brave-core/pull/16387)
- Verified Transaction submitted logo is rendered properly

https://user-images.githubusercontent.com/17010094/214491068-d9898bb6-4709-430e-83f0-c05b26eeab8b.mp4

---------------------

Verification passed on 

Brave | 1.48.139 Chromium: 109.0.5414.87 (Official Build) beta (64-bit)
-- | --
Revision | `2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#16387](https://github.com/brave/brave-core/pull/16387)
- Verified Transaction submitted logo is rendered properly

https://user-images.githubusercontent.com/17010094/214491435-35cf5e21-30c6-4973-a9e2-33b7fb18bced.mp4

---------------------

Verification passed on 

Brave | 1.48.139 Chromium: 109.0.5414.87 (Official Build) beta (arm64)
-- | --
Revision | `2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#16387](https://github.com/brave/brave-core/pull/16387)
- Verified Transaction submitted logo is rendered properly

https://user-images.githubusercontent.com/17010094/214491849-d01616b5-057b-4e35-89bc-c5ede1db343b.mov
