### ISSUE TITLE
`Learn more` links under `Help improve Brave` via `brave://welcome` are opening `brave://settings/privacy` tabs

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#27401]
## Description 

When clicking on the `Learn more` links via the `Help improve Brave` under `brave://welcome`, you'll notice that it also opens `brave://settings/privacy` tabs. It should only be opening the links that are mentioned via https://github.com/brave/brave-browser/issues/27339#issue-1494665674.

## Steps to Reproduce

   1. launch `1.48.58 Chromium 108.0.5359.128`
   2. skip through all of the onboarding screens via `brave://welcome` till you get to the `Help improve Brave` screen
   3. click on `Learn more` and notice that `brave://settings/privacy` tabs are being opened

## Actual result:

https://user-images.githubusercontent.com/2602313/207914680-197945ca-3a61-4029-98aa-5ace7110a685.mp4

## Expected result:

We shouldn't be opening `brave://settings/privacy` tabs as per https://github.com/brave/brave-browser/issues/27339#issue-1494665674.

## Reproduces how often: 

100% reproducible when using the STR/Cases outlined above.

## Brave version (brave://version info)

```
Brave | 1.48.58 Chromium: 108.0.5359.128 (Official Build) nightly (64-bit)
-- | --
Revision | 1cd27afdb8e5d057070c0961e04c490d2aca1aa0-refs/branch-heads/5359@{#1185}
OS | Windows 11 Version 22H2 (Build 22621.963)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A`
- Can you reproduce this issue with the beta channel?  `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by rebron** [comment]
cc: @spylogsster

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.50.86 Chromium: 111.0.5563.64 (Official Build) beta (x86_64)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | macOS Version 11.7.4 (Build 20G1120)

#### Confirmed clicking on each link opened it in a new tab, without also opening `brave://settings/privacy`

1st Learn more | 2nd Learn more
---------------|-----------------
<img width="1312" alt="Screen Shot 2023-03-12 at 10 02 04 PM" src="https://user-images.githubusercontent.com/387249/224612338-99889a14-be87-47d6-9a17-7959280cde6e.png"> | <img width="1312" alt="Screen Shot 2023-03-12 at 10 02 10 PM" src="https://user-images.githubusercontent.com/387249/224612342-99e9ae24-df31-47d9-a338-6a463dec39d4.png">
