### ISSUE TITLE
missing double quotes in conf.py

### ISSUE THREAD

**Issue by SamudraMitra** [brave/brave-browser#27411]
## Description 
Under docs\source/conf.py in line 85, the meta tag has two missing double quotes

## Steps to Reproduce
   1. go to docs/source/conf.py
   2. go to line 84
   3. Check out the content and URL attribute of the meta tag

## Actual result:
![image](https://user-images.githubusercontent.com/94888874/208030729-352c51d0-fba8-49de-be02-352facc09e3e.png)

## Expected result:
![image](https://user-images.githubusercontent.com/94888874/208030972-34dc055a-82c8-4681-8f5e-164071500b40.png)

## Reproduces how often: 

Intermittent issue

## Brave version (info found on brave://version)
Version 1.48.60

## Version/Channel Information:
- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Yes

## Miscellaneous Information:
This is a small bug but a syntax error, so it should be fixed

**Comment by SamudraMitra** [comment]
I am new to open-source contributions. I really want to learn. Please assign me this issue @Brave-Matt

**Comment by bsclifton** [comment]
Go for it @SamudraMitra 😄

**Comment by SamudraMitra** [comment]
Thank you @bsclifton . I have created the pull request. Please review it

**Comment by bsclifton** [comment]
Closing as PR was closed - see comment here:
https://github.com/brave/brave-browser/pull/27438#issuecomment-1359112227
