### ISSUE TITLE
Brave Rewards - Remove and/or update Gemini banner with Earn copy in brave://rewards

### ISSUE THREAD

**Issue by lukemulks** [brave/brave-browser#27426]
## Description 

I'm on the latest version of Brave Nightly on Desktop (win10), and noticed that in brave://rewards, we still feature a Gemini promo banner that includes copy regarding earning interest in the US, SG and HK. 

With Gemini Earn being impacted by Genesis contagion, Earn accounts are impacted. 

Strongly suggest we remove the banner as soon as possible, then revisit whether we include it back, and if so, do so with updated copy that does not mention outputs related to the defunct Earn feature. 

Suggest we go forward with it in that order. 

## Steps to Reproduce

   1.  Go to brave://rewards
   2.  Observe in the right rail; gemini banner appears above TAP redemptions, and below Creators banner. 

1.48.61 Chromium: 109.0.5414.46 (Official Build) nightly (64-bit) 

## Actual result:

![rewards-gemini-card-12162022](https://user-images.githubusercontent.com/8979240/208217211-9c870359-225b-4d1e-8d58-6991867fe615.jpg)

## Expected result:
First remove; then revisit. 

## Solution

From @Miyayes 
- [ ] Make Gemini card only appear in US
- [ ] Remove "Plus, you can earn interest in US, HK, and SG." text from the card. 

Would treat as a priority item given situation with Earn. cc: @Miyayes @evq

**Comment by kjozwiak** [comment]
The above requires `1.46.148` or higher for `1.46.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.46.153 Chromium: 108.0.5359.128 (Official Build) (64-bit)
-- | --
Revision | 1cd27afdb8e5d057070c0961e04c490d2aca1aa0-refs/branch-heads/5359@{#1185}
OS | Windows 11 Version 21H2 (Build 22000.1335)
```
Case 1: Make Gemini card only appear in US

1. Install 1.46.153
2. launch Brave
3. click `Skip welcome tour`
4. enable Rewards 
5. select `United States` from `Select your country` dropdown
6. click `Continue`
7. click `Skip for now`
8. visit `brave://rewards`

#### Confirmed `Plus, you can earn interest in US, HK, and SG` text no longer shown in `Link to Rewards to Gemini!` card

ex 1|ex2|
----|----
<img width="453" alt="image" src="https://user-images.githubusercontent.com/98358127/211078635-7801ad1d-b7a8-4eaf-8999-09feebc2f060.png">|<img width="460" alt="image" src="https://user-images.githubusercontent.com/98358127/211078779-751e8590-4e1d-4861-8148-b8d612e4f1e8.png">|

Case 2: Do not show Gemini card for other countries - `UK`

1. new profile 
2. launch Brave
3. click `Skip welcome tour`
4. enable Rewards
5. select `United Kingdom` from `Select your country` dropdown
7. click `Continue`
8. click `Skip for now` >>`Done`
9. visit `brave://rewards`

####Confirmed `Link to Rewards to Gemini!` card is removed for `UK`

ex1|ex2
----|----
<img width="449" alt="image" src="https://user-images.githubusercontent.com/98358127/211080722-84563f2d-cb97-4822-9528-ae54cd78ac03.png">|<img width="458" alt="image" src="https://user-images.githubusercontent.com/98358127/211080773-237a5162-4850-4078-9cd1-d8003e635836.png">
