### ISSUE TITLE
Cancel vpn connection request more quickly if possible

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#27427]
Sometimes it takes some time to cancel when connecting is in-progress.
The reason is connecting process is involved with several network request(fetch hostname or profile credential).
So far, we waited to get responce and then did cancel but we could do more quickly by cancelling this network itself.

## Steps to Reproduce

   1. Launch Brave
   2. connecting vpn and then toggle off quickly
   3. 

## Actual result:

It takes some time to wait response from vpn server

## Expected result:
Cancel immediately

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.47.140` or higher for `1.47.x` verification 👍

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.47.141 Chromium: 109.0.5414.46 (Official Build) beta (32-bit)
-- | --
Revision | 6e36b77363ef3febbe792af680fa1367993ddcf0-refs/branch-heads/5414@{#709}
OS | Windows 10 Version 22H2 (Build 19045.2364)

### Steps:
1. installed `1.47.141`
2. launched Brave
3. purchased, configured, and connected to `BraveVPN`
4. disconnected
5. switched server locations
6. while reconnecting, disconnected and reconnected (and toggled back and forth)
7. rapidly toggled from `Disconnected` to `Connected` and vice-versa

#### Confirmed I was able to quickly disconnect from/switch to new server locations, and reconnect/disconnect, via the main `Disconnected`/`Connected` toggle

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.47.149 Chromium: 109.0.5414.46 (Official Build) beta (x86_64)
-- | --
Revision | 6e36b77363ef3febbe792af680fa1367993ddcf0-refs/branch-heads/5414@{#709}
OS | macOS Version 11.7.2 (Build 20G1020)

Followed the same steps as above.

### Confirmed I was able to quickly disconnect from/switch to new server locations, and reconnect/disconnect, via the main `Disconnected`/`Connected` toggle

![vpn-toggle-quickly](https://user-images.githubusercontent.com/387249/209862370-09b25768-b5d6-468f-bb5f-93e29c15e8b1.gif)
