### ISSUE TITLE
[CR109]: Import bookmarks and settings modal do not get dismissed after importing bookmarks 

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#27425]
## Description 

Bookmarks were successfully imported via new onboarding pages and via import bookmarks & settings modal.  However, the modal doesn't get dismissed

## Steps to Reproduce

   1.  Install 1.48. 61
   2.  launch Brave
   3.  click hamburger menu>>Bookmarks>>Import bookmarks and settings
   4.  select `Microsoft Edge Profile` 
   5. click Import

## Actual result:

Bookmarks were added to the bookmarks bar, but the modal is not auto-dismissed.

https://user-images.githubusercontent.com/98358127/208216311-33c5ebb7-ec86-4f57-b878-a6f75542b8ee.mp4

## Expected result:
When clicked on `Import` button, success message `Your bookmarks and settings are ready` dialog should be shown.  

1.46.x (CR108)
-----
<img width="959" alt="image" src="https://user-images.githubusercontent.com/98358127/208216354-154264ae-b656-403e-abbe-f68306d46826.png">

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Brave | 1.48.61 Chromium: 109.0.5414.46 (Official Build) nightly (64-bit)
-- | --
Revision | 6e36b77363ef3febbe792af680fa1367993ddcf0-refs/branch-heads/5414@{#709}
OS | Windows 11 Version 21H2 (Build 22000.1335)

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
 @mkarolin @rebron @brave/qa-team

**Comment by mkarolin** [comment]
I think this may have something to do with the parallel importer and not firing the `import-data-status-changed` event that the Settings WebUI expects. cc: @nullhook

**Comment by kjozwiak** [comment]
The above requires `1.47.155` or higher for `1.47.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
Brave | 1.47.161 Chromium: 109.0.5414.61 (Official Build) beta (64-bit)
-- | --
Revision | 846c6eff1c374cde417a9cdc44193545cc07f354-refs/branch-heads/5414@{#1030}
OS | Windows 10 Version 21H2 (Build 19044.2364)

```
- Reproduced the issue in 1.48.61
- Verified the STR from the description and ensured that once the bookmarks are imported the success message `Your bookmarks and settings are ready` is shown.
![image](https://user-images.githubusercontent.com/38657976/210381995-10c2b532-e5c6-4592-ae29-fbffbf565f8d.png)
