### ISSUE TITLE
[Android] Playlist - Deeplink for house ads

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#27421]
## Description 
When the android playlist feature launches the marketing team will run house ads to promote. We need a deeplink setup to direct users to the playlist onboarding.

## Requirements
Check the playlist feature flag to determine if we show either:
1. Playlist enabled: open playlist onboarding.
2. Playlist disabled (older versions of Brave): open playlist custom GPC listing:
https://play.google.com/store/apps/details?id=com.brave.browser&listing=playlist

**Comment by larreewong** [comment]
Note from Dan Murphy, not sure if it matters when you are building the deeplink. See [thread](https://bravesoftware.slack.com/archives/C04FA7U39NE/p1671134611048399)

_Regarding deep linking — just a quick clarification  - not all deep links work the same. I need to look up the difference but one requires using a prefix like “chrome://“ and another needs to use “Brave://“ (or something similar) so we sometimes can’t just use one URL for all OSes just yet._
