### ISSUE TITLE
Show Full Address for Resolved Domains Send V2

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#27422]
## Description 
We need to show the full address for resolved domain in the new `Send V2`

![image](https://user-images.githubusercontent.com/40611140/208196496-b7d04641-752e-46be-80e1-ab17f38558b1.png)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta  (64-bit) 
-- | --
Revision | `46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}`
OS | Linux

- Verified steps from [ brave/brave-core#16606](https://github.com/brave/brave-core/pull/16606)
- Verified entering a `UD` / `ENS` domain resolves and shows the full address
- Verified clicking on the address copies it to clipboard
- Verified pasting from clipboard shows full address 

https://user-images.githubusercontent.com/17010094/221617756-47358474-4a91-4b9b-bff3-4e90ce183dea.mp4

---------------------

Verification passed on 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta  (64-bit)
-- | --
Revision | `46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [ brave/brave-core#16606](https://github.com/brave/brave-core/pull/16606)
- Verified entering a `UD` / `ENS` domain resolves and shows the full address
- Verified clicking on the address copies it to clipboard
- Verified pasting from clipboard shows full address 

https://user-images.githubusercontent.com/17010094/221615508-a2d25607-0e48-40c6-b56c-648b825e8b27.mp4

---------------------

Verification passed on 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta  (arm64)
-- | --
Revision | `46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [ brave/brave-core#16606](https://github.com/brave/brave-core/pull/16606)
- Verified entering a `UD` / `ENS` domain resolves and shows the full address
- Verified clicking on the address copies it to clipboard
- Verified pasting from clipboard shows full address 

https://user-images.githubusercontent.com/17010094/221620315-e4034571-d57b-4483-8ed9-e88e05182238.mov
