### ISSUE TITLE
Speedup sync chain creation time

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#2742]
## Description 

Current update interval for fetch records is 60 sec.
When sync chain is creating, device gets aware about it finished when it does fetch and sees other devices in chain. 60 seconds interval affects this phase so Device2 can appear in the list of devices of Device1 in 60 sec, which may seem too long.

## Steps to Reproduce

 1. On Device1 go to chrome://sync/ 
 2. Press "Start new chain" => "Computer" => "Copy code"
 3. On device 2 go to chrome://sync/ 
 4. "Enter sync chain code" button
 5. Paste the code 
 6. "Confirm sync code" button

## Actual result:

Device1 gets created a sync chain much later (>15 sec) than Device2

## Expected result:
Device1 gets created a sync chain not so late (<5 sec) after Device2

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Brave | 0.60.4 Chromium: 72.0.3626.17 (Official Build) dev(64-bit)
-- | --
Revision | 08d2140079f8db14c9eb885a803d231b1a30e817-refs/branch-heads/3626@{#315}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds?

**Comment by srirambv** [comment]
@AlexeyBarabash I see on Linux it takes 8secs as mentioned in https://github.com/brave/brave-browser/issues/2782#issuecomment-455508383. Is this ok? The expected result says <5secs

**Comment by AlexeyBarabash** [comment]
@srirambv 
I think, it is ok. I usually saw it almost rapidly after the PR, and ~1 minute before PR.
So 5 sec or 8 sec it seems the same order of time amount.

**Comment by srirambv** [comment]
Thanks for the confirmation @AlexeyBarabash . So anything below 10secs is a reasonable acceptable time I guess

Verification passed on 

Brave | 0.59.25 Chromium: 72.0.3626.53 (Official Build) beta(64-bit)
-- | --
Revision | 98434e6cd182d68ce396daa92e9c6310422e6763-refs/branch-heads/3626@{#620}
OS | Linux
