### ISSUE TITLE
Drop .coin support for UD

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#27436]
https://bravesoftware.slack.com/archives/CBP2ZKC0H/p1671239158593889?thread_ts=1670441769.222389&cid=CBP2ZKC0H

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.48.141 Chromium: 109.0.5414.119 (Official Build) beta (64-bit) 
-- | --
Revision | `772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}`
OS | Linux

- Verified steps from [brave/brave-core#16399](https://github.com/brave/brave-core/pull/16399)
- Verified `.coin` domain doesn't resolve in both Wallet Send and Omnibox

https://user-images.githubusercontent.com/17010094/215496986-a7740296-d963-4e81-aba2-091125f53ebd.mp4


---------------------

Verification passed on 

Brave | 1.48.141 Chromium: 109.0.5414.119 (Official Build) beta (64-bit)
-- | --
Revision | `772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#16399](https://github.com/brave/brave-core/pull/16399)
- Verified `.coin` domain doesn't resolve in both Wallet Send and Omnibox

https://user-images.githubusercontent.com/17010094/215497010-9d0ce4f6-5c98-4fa4-b019-b714de33c102.mp4


---------------------

Verification passed on 

Brave | 1.48.141 Chromium: 109.0.5414.119 (Official Build) beta (arm64)
-- | --
Revision | `772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#16399](https://github.com/brave/brave-core/pull/16399)
- Verified `.coin` domain doesn't resolve in both Wallet Send and Omnibox

https://user-images.githubusercontent.com/17010094/215497214-94011bf9-09f0-4251-8db1-5b1bf25389e0.mov

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.48.155 x64 build
- Verified steps from [brave/brave-core#16399](https://github.com/brave/brave-core/pull/16399)
- Verified `.coin` domain doesn't resolve in both Wallet Send and Omnibox

Oppo Reno 5 (Android 13) | Lenovo Tab (Android 12)
-- | --
<video  src=https://user-images.githubusercontent.com/17010094/216898373-b6b61cbc-d9b8-45c8-9cbf-b8dc57350a70.mp4> | <video  src=https://user-images.githubusercontent.com/17010094/216898402-08225e28-f58f-4541-ae6c-61b7457e8ef4.mp4>
