### ISSUE TITLE
DevTools Network filter button inactive color is incorrect

### ISSUE THREAD

**Issue by goodov** [brave/brave-browser#27437]
Brave:
https://user-images.githubusercontent.com/5928869/208359142-3f1a8c98-78b7-4f33-8b36-bb7cacf8a360.mp4

Chromium:
https://user-images.githubusercontent.com/5928869/208359081-733eb3ca-f587-4215-b011-e6932a12f446.mp4

**Comment by goodov** [comment]
cc @rebron @simonhong

**Comment by MGreizis** [comment]
Hi! Is this issue still open? It's my first time contributing, as this is an issue with the "good first issue" label. I'd like to work on this, if this is still open.

**Comment by mahir118** [comment]
Hi! I would love to contribute to solving this issue as well. I am new to Open Source Contributions so I would really appreciate if someone can guide me through the steps.

**Comment by kunalshokeen051** [comment]
hi, is the issue solved if not i like to contribute to this repo. so i am ready to solve this issue.

**Comment by dylanyng** [comment]
This issue appears to be solved on my end.
Version 1.46.153 Chromium: 108.0.5359.128 (Official Build) (arm64)

**Comment by VikramDigra** [comment]
This issue is no longer exists

**Comment by holtkampjs** [comment]
@goodov Can you close this issue? The status is still set to open.

**Comment by goodov** [comment]
> @goodov Can you close this issue? The status is still set to open.

sure. the issue seems to be fixed.
