### ISSUE TITLE
Unable to login on accounts.zalando.com

### ISSUE THREAD

**Issue by maxfaa** [brave/brave-browser#27430]
## Steps to Reproduce

   1. Go on any Zalando website (like zalando.be)
   2. Click on login
   3. Try to connect into your account 

## Actual result:

Infinite loading due to this broken/unreachable resource accounts.zalando.com/api/login/

## Expected result:
Be logged in successfully

## Reproduces how often: 

This issue happened every time I try to login

## Brave version (brave://version info)

1.47.129 Chromium: 108.0.5359.128 (Official Build) beta (64-bit) 

## Version/Channel Information:

It works perfectly on any other browser on the same computer

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by ryanbr** [comment]
Attempt to reset password, with fingerprinting enabled will error. Just using my email `some.nzguy(at)gmail.com`  (test account), cc: @pilgrim-brave 

![zalando](https://user-images.githubusercontent.com/1659004/209429591-f947b98c-92d5-4084-9d84-8a51f1ce0c03.png)

**Comment by IamCampos** [comment]
i have the same exact error on the same website (zalando.it) and the same browser (BRAVE). 
Before reading this post I tried the same exact things and it works everywhere but on Brave.
how did you solve that?

**Comment by webst88** [comment]
I also cant Login to Zalando whatever i do. Other Browsers work fine with Zalando.

**Comment by xylaxos** [comment]
Topic is old, but if someone encounters this problem which can occur in different browsers (in my case in Edge), I uninstalled and reinstalled my network adapter in Device Manager. Then reconnect to the network. You can try connecting to a different WiFi network (from your phone) and the problem should go away. Uninstalling the network adapter and reinstalling it should fix the problem.

**Comment by ryanbr** [comment]
This seems to be fixed by the server @IamCampos @maxfaa , if you're still using Brave?

**Comment by maxfaa** [comment]
> This seems to be fixed by the server @IamCampos @maxfaa , if you're still using Brave?

Yes it's working, thanks!!
