### ISSUE TITLE
No cursor on "Send my tip" button

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#2744]
## Description 
Reports that the _Send my tip_ does not display a cursor: https://twitter.com/NinjaMaxR/status/1078111992420945921?s=19

## Steps to Reproduce
1. Hover _Send my tip_

## Actual result:
No cursor displayed.

## Expected result:
Hover should display pointer.

## Reproduces how often: 
TBD

## Brave version (brave://version info)
TBD

### Reproducible on current release:
TBD

## Related Issues
#2705

**Comment by GeetaSarvadnya** [comment]
Verification passed on 


Brave | 0.59.25 Chromium: 72.0.3626.53 (Official Build) beta (64-bit)
-- | --
Revision | 98434e6cd182d68ce396daa92e9c6310422e6763-refs/branch-heads/3626@{#620}
OS | Windows

- Verified cursor on `Send my tip`
