### ISSUE TITLE
Allow `connect-receipt-test` intent for VPN receipt link

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#27451]
## Description 
QA is going to be using `connect-receipt-test` for linking the receipts instead of `connect-receipt`. The original `connect-receipt` will eventually be used - but for now will show a "coming soon" page

## Steps to Reproduce
   1. Be on Android (Nightly), have VPN purchased as an in-app-purchase
   2. Visit https://account.bravesoftware.com?intent=connect-receipt-test&product=vpn
   3. Hit the button to start linking

## Actual result:
It doesn't work (spinner spins for a long time). 

You need to visit these pages in order for it to work
1. https://account.bravesoftware.com?intent=connect-receipt&product=vpn
2. https://account.bravesoftware.com?intent=connect-receipt-test&product=vpn

## Expected result:
It should work when at https://account.bravesoftware.com?intent=connect-receipt-test&product=vpn

**Comment by kjozwiak** [comment]
The above requires `1.47.139` or higher for `1.47.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` & `Samsung Galaxy Tab S7` per https://github.com/brave/brave-browser/issues/27473#issuecomment-1372823513
