### ISSUE TITLE
Android VPN promo link and VPN settings link don't go to the correct URL

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#27452]
## Description 
When shown a link for the link promotion OR when you click the button to start linking, the URL is going to the wrong place

### Promo

   1. Be on Android (Nightly), have VPN purchased as an in-app-purchase
   2. You should see the promotion modal pop up
   3. Click the link
   4. It goes to the wrong URL
       - If in staging, it goes to https://account.bravesoftware.com instead of https://account.bravesoftware.com?intent=connect-receipt&product=vpn
       - If in prod, it goes to https://account.brave.com instead of https://account.brave.com?intent=connect-receipt&product=vpn

**Comment by kjozwiak** [comment]
The above requires `1.47.139` or higher for `1.47.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on Samsung Galaxy S21 & Samsung Galaxy Tab S7 using the following `Nightly` build(s):

```
Brave	1.48.94 Chromium: 109.0.5414.46 (Official Build) canary (64-bit) 
Revision	6e36b77363ef3febbe792af680fa1367993ddcf0-refs/branch-heads/5414@{#709}
OS	Android 12; Build/SP1A.210812.016
```

- Verified receipt link points to the appropriate URL in staging and prod environments using `Nightly Channel`

Example | Example | Example
-|-|-
![screenshot-1672343407297](https://user-images.githubusercontent.com/17885425/210005617-9048c505-d4b8-459d-a94e-fb18dd1ed3c7.png) | ![screenshot-1672342923772](https://user-images.githubusercontent.com/17885425/210005775-06e9f12c-fdf7-407a-9899-cff0f3b42ed4.png) | ![screenshot-1672343328357](https://user-images.githubusercontent.com/17885425/210005787-f5a38125-315f-485f-bc16-a6e8794c0386.png)

**Comment by Uni-verse** [comment]
@Uni-verse to verify on release channel before adding QA labels.
