### ISSUE TITLE
[CR109] Custom Filters textbox appearance in brave://adblock has changed 

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#27450]
## Steps to Reproduce

   1. Install 1.48. 61
   2. launch Brave
   3. navigate to bbc.com/
   4. block an element via `Block element via selector` context-menu item
   5. open brave://adblock 
  6. navigate to Create Custom filter textbox 

## Actual result:

The appearance/css properties  of the textbox seems to be read only.  Couldn't highlight the text. 
However, the functionality works as expected i.e. able to delete the filters and save changes.

<img width="450" alt="image (2)" src="https://user-images.githubusercontent.com/98358127/208474899-2c3ef567-7b54-4483-a447-b83e433103ee.png">

## Expected result:
1.46.x (CR108)
-----

<img width="426" alt="image (3)" src="https://user-images.githubusercontent.com/98358127/208474949-431c9073-9f6f-418c-b8ee-db99931b3914.png">

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.48.61 Chromium: 109.0.5414.46 (Official Build) nightly (64-bit)
-- | --
Revision | 6e36b77363ef3febbe792af680fa1367993ddcf0-refs/branch-heads/5414@{#709}
OS | Windows 11 Version 21H2 (Build 22000.1335)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
<!--Any additional information, related issues, extra QA steps, configuration or data that might be necessary to reproduce the issue--
@mkarolin @rebron @brave/qa-team

**Comment by kjozwiak** [comment]
The above requires `1.47.164` or higher for `1.47.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.47.164 Chromium: 109.0.5414.74 (Official Build) (64-bit)
-- | --
Revision | e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}
OS | Windows 11 Version 22H2 (Build 22621.963)
```

1. Install 1.47.164
2. launch Brave
3. Skip onboarding
4. navigate to bbc.com
5. block an element via Block element via selector context-menu item
6. open brave://adblock
7. navigate to Create Custom filter textbox

Confirmed Custom filters edit box styling/background restored as expected

ex1|ex2
----|----
![image](https://user-images.githubusercontent.com/98358127/210866078-da78b4c7-2b9a-43e4-b92d-fab4fec37b3f.png)|![image](https://user-images.githubusercontent.com/98358127/210866213-2b21a1ca-697d-4262-ae19-ffa5164bbef3.png)
