### ISSUE TITLE
implement 3 minute timer for QA purposes of testing certain error notifications - follow up to 24251

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#27454]
## Description 

Follow up to https://github.com/brave/brave-browser/issues/24251 / https://github.com/brave/brave-core/pull/15722.

While testing above, noticed that the 3 minute shortcut for QA to test the below is not working. The real timer of 15 minutes does work as expected.

```
- new Uphold notifications (which are potentially triggered (every 3 minutes in testing environment, every 15 minutes otherwise) by the same endpoints that trigger the corresponding error modals, see above):
   - BAT not allowed
   - insufficient capabilities
```

## Steps to Reproduce

pre-req: have Charles Proxy running, and have a rule set up to simulate one of the above scenarios, but do not have the rule enabled/running yet.
1. Installed 1.47.x, w/ staging env
2. Relaunched to pull griffin seed
3. Enabled Rewards, selected country (US)
4. Linked KYC'd Uphold account for US
5. Enable the Charles Proxy rule to simulate insufficient capabilities or BAT not allowed
6. Wait 3 minutes
7. Nothing happens (no error on panel), continue waiting until 15 minutes have passed
8. Confirmed notification shows on panel.

## Actual result:

3 minute timer/shortcut does not work

## Expected result:

3 minute timer/shortcut works

## Reproduces how often: 

easily

## Brave version (brave://version info)

```
Brave | 1.47.129 Chromium: 108.0.5359.128 (Official Build) beta (x86_64)
-- | --
Revision | 1cd27afdb8e5d057070c0961e04c490d2aca1aa0-refs/branch-heads/5359@{#1185}
OS | macOS Version 12.6.2 (Build 21G320)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? probably

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @szilardszaloki @Miyayes

**Comment by Miyayes** [comment]
These will now be checked upon every browser restart.
