### ISSUE TITLE
Difficult to "Confirm you are a human being" to claim BAT on Linux

### ISSUE THREAD

**Issue by donateur** [brave/brave-browser#27463]
## Description 
On my Fedora 37 Workstation, running the default GNOME window manager, the "Confirm you are a human being" test, which involves dragging a BAT icon, is difficult to pass because the BAT icon does not align properly with the cursor.

## Steps to Reproduce

   1. Install Fedora 37 Workstation
   2. Install Brave
   3. Earn BAT
   4. After a month try to claim BAT by clicking the BAT icon with a blue check mark
   5. "Confirm you are a human being" is displayed.  It asks you to drag the BAT icon to either a Circle, Square or Triangle target.  Very carefully do so.

## Actual result:

No matter how carefully you drag the icon to the target it displays "Hmm...Not Quite. Try again".

(Sorry can't screenshot or capture video until next month.  This has been happening for months.)

## Expected result:

The test passes and the user is rewarded BAT.

## Reproduces how often: 

Reproducible every month for me.

## Brave version (brave://version info)

1.46.144 Chromium: 108.0.5359.128 (Official Build) (64-bit) 

## Version/Channel Information:
I'm on the production version

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  N/A
- Does the issue resolve itself when disabling Brave Rewards?  N/A
- Is the issue reproducible on the latest version of Chrome?  N/A

## Miscellaneous Information:

* This problem happens when the browser is in any position, or full screen.  The fix is to drag the cursor icon to the correct symbol, NOT the BAT icon.  The BAT icon is misaligned to the left of the actual cursor (I'll try to get a screenshot next month)
* My display is a standard 27 inch 2560 x 1440 model
* I am a heavy Linux user and do not have any other cursor alignment or video problems, even with Brave

**Comment by Chandraprakash-Darji** [comment]
@donateur is it fixed?
I am Fedora 36. facing same issue

**Comment by donateur** [comment]
> @donateur is it fixed? I am Fedora 36. facing same issue

No, it is not fixed.  Dragging the cursor to the correct shape works, you have to ignore the BAT icon as it is misaligned.

**Comment by Miyayes** [comment]
Maybe upstream bug has been fixed -- we introduced offset to handle that bug. But if the upstream has been fixed, then now our offset itself creates a bug. Will investigate. (As noted by zenparsing). cc: @emerick

**Comment by zenparsing** [comment]
It appears the Linux-specific drag image bug may have been [fixed](https://bugs.chromium.org/p/chromium/issues/detail?id=1297990#c26) in 107.0.5268.0. We should be able to remove the Linux-specific workaround in `grant_captcha_challenge.tsx`.

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.49.100 Chromium: 110.0.5481.100 (Official Build) beta (64-bit)
-- | --
Revision | 4be7a36f7cb943af6118e449bbab494b43dcaddd-refs/branch-heads/5481_77@{#14}
OS | Windows 10 Version 21H2 (Build 19044.2486)

```

**Comment by NeuHix** [comment]
Still Not Working in Fedora 37 in the latest version.

**Comment by Miyayes** [comment]
> Still Not Working in Fedora 37 in the latest version. My screen resolution : 1920x1080

Change is in 1.49.x. Are you on 1.48.x?

**Comment by NeuHix** [comment]
Version 1.49.120 Chromium: 111.0.5563.64 (Official Build) (64-bit)

**Comment by Miyayes** [comment]
@NeuHix You still have some ad earnings that can't be claimed due to this? 

In short, this CAPTCHA only exists for virtual BAT, which is being deprecated anyway (see https://brave.com/rewards-changes), and there are no more payouts of virtual BAT anymore. Will you connect an Uphold or Gemini account to your Rewards profile? If so, I can just send you the amount you can't claim directly to your Uphold account, and just wrap things up. Otherwise, your vBAT will be deleted anyway once we reach the sunset deadline (see blog post). Thanks.

**Comment by NeuHix** [comment]
My countries isn't supported. I thought i can tip these BATs to websites i wanna support. even if i can't benefit from them.

**Comment by Miyayes** [comment]
> I thought i can tip these BATs to websites i wanna support. even if i can't benefit from them.

You would be able to, yes. You're just in an awkward position where you can't claim them, and it's unlikely a fix on our end will land before vBAT is expired anyway.

Maybe you can fiddle with OS settings on your end (display resolution settings) to see if you can manage to solve and claim the vBAT so you can tip it away.

**Comment by NeuHix** [comment]
So, what should be my display resolution ?

**Comment by Miyayes** [comment]
> So, what should be my display resolution ?

If there's a display / UI scaling, I would toggle that and try a bunch of different values.

We don't know the answer, so you would have to just try a bunch of different ones and check if it helps!
