### ISSUE TITLE
Enable ENS L2 support for android.

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#27465]
Needs UI similar to desktop one 
![image](https://user-images.githubusercontent.com/168356/208617546-9c2c3766-5d57-4656-af74-a422405731d8.png)

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.48.155
- Verified steps from [brave/brave-core#16453](https://github.com/brave/brave-core/pull/16453)
- Verified new sub-menu is available for ENS L2 under Brave Shields and Privacy -> Ethereum Name Services
- Verified setting it to `Ask` shows confirmation of using offchain lookup

Oppo Reno 5 (Android 13) | Lenovo Tab (Android 12)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/216946731-252b20e9-d1ae-4bc2-8dbe-fa6d2dd2d912.mp4> | <img width=400 src=https://user-images.githubusercontent.com/17010094/216946786-35c1dd45-e04b-4a87-a7b5-8f04b50b9e51.mp4>
