### ISSUE TITLE
Browser showing blank space for displaying Brave Banner

### ISSUE THREAD

**Issue by avndp** [brave/brave-browser#2746]
## Description 
I have displayed a brave banner in my blog and linked it to brave with my referral link. When the shield is on, it is showing large blank space as shown in this snap: https://i.imgur.com/9CnXFw2.png , whereas the image size is only 728x90.  Though it is a brave linked banner, it is still blocked and showing blank space beyond 90px height.

## Steps to Reproduce

   1. Visit the URL: https://aavo.in/the-1st-best-screenshot-software-for-linux-ubuntu/
   2. See the blank space after post title.

## Actual result:
Showing blank space.

## Expected result:
It should either display the banner or block, instead showing huge white space beyond the original banner size.

## Reproduces how often: 
Easily reproduced all the time.

## Brave version (brave://version info)

Brave | 0.60.4 Chromium: 72.0.3626.17 (Official Build) dev(64-bit)
Revision | 08d2140079f8db14c9eb885a803d231b1a30e817-refs/branch-heads/3626@{#315}
(Also tried on Brave Beta and Release channels and the result is same)

### Reproducible on current release:
Yes.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? - YES.
- Is the issue reproducible on the latest version of Chrome? - NO.

**Comment by srirambv** [comment]
Could you try changing the location of the banner image and check if it works? The path might be getting filtered out by the adblock regex string.

**Comment by avndp** [comment]
> Could you try changing the location of the banner image and check if it works? The path might be getting filtered out by the adblock regex string.

Tried it already in footer & sidebar and nothing worked.

**Comment by srirambv** [comment]
>Tried it already in footer & sidebar and nothing worked. 

Not the location of the banner on the page but the path in which you have the banner image uploaded and may be rename the file in the current upload path itself.

**Comment by avndp** [comment]
> > Tried it already in footer & sidebar and nothing worked.
> 
> Not the location of the banner on the page but the path in which you have the banner image uploaded and may be rename the file in the current upload path itself.

When removed 728x90 from the image file name, it's working fine.  Also understood that it is one form of detection (file name) for Brave for blocking ads. Would be great if Brave does not block ads that links to brave itself, may be I'm wrong too.

Thanks for the help @srirambv
