### ISSUE TITLE
Tapping on 'Add New Device' jumps back to sync home page

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#27469]
## Description 
Tapping on 'Add New Device' jumps back to sync home page

## Steps to reproduce 

   1. Clean install 1.48.58 C108
   2. Open sync and select `start a new sync chain`
   3. Tap on `Add New Device`

## Actual result 
When next screen loads after tapping `Add new device` , it jumps back to previous screen

https://user-images.githubusercontent.com/17885425/208711303-b16e1e74-51c6-4041-8405-c730422a0a8d.mp4

## Expected result
Should stay in the device type selection screen

## Issue reproduces how often 
Easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung Galaxy S21, Phone
   - Android version: 12
   
## Brave version
1.48.58

**Comment by AlexeyBarabash** [comment]
I can reproduce it.

This is a regression from  https://github.com/brave/brave-core/pull/16183

**Comment by AlexeyBarabash** [comment]
> This is a regression from [brave/brave-core#16183](https://github.com/brave/brave-core/pull/16183)

And particularly by https://github.com/brave/brave-core/pull/13562

**Comment by kjozwiak** [comment]
The above requires `1.48.133` or higher for `1.48.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using `1.48.134` on a `Google Pixel XL` running `Android 9`

Followed the original steps to reproduce, and could, using `1.48.58`: https://github.com/brave/brave-browser/issues/27469#issue-1504817256.

#### Confirmed tapping on `Add new device` works fine (as do other related menus)

`1.48.134` | `1.48.58`
-----------|----------
<video src="https://user-images.githubusercontent.com/387249/213848676-9aad9164-4792-4d9c-8650-0e805ca358b5.mp4"> | <video src="https://user-images.githubusercontent.com/387249/213848667-de570391-7134-4aca-b65f-382a327560bd.mp4">
