### ISSUE TITLE
`Connect my subscription now` linking button doesn't work

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#27473]
## Description 

`Connect my subscription now` linking button doesn't work

## Steps to Reproduce

1. installed `1.48.71`
2. launched Brave
3. skip onboarding
4. tapped the 3-dots menu
5. tapped `Settings`
6. tapped `QA Preferences`
7. entered QA code
8. tapped on `Brave VPN`
9. tapped to purchase `One Year`
10. tapped `Subscribe`
11. tapped `Install VPN Profile`
12. tapped `OK` at the `Connection request screen`
13. (VPN is now enabled animation)
14. loaded `https://account.bravesoftware.com/?intent=connect-receipt-test&product=vpn` as per https://github.com/brave/brave-browser/issues/27451
15. entered basic-auth credentials
16. click `Connect my subscription now` button

## Actual result:

`Whoops!  We couldn't locate your receipt.  Please contact Brave Support.`

`screenshot` | `screencast`
--------------|-------------
![Screenshot_20221220-091252](https://user-images.githubusercontent.com/387249/208731596-99b02505-f93c-4e16-9c83-386d4abba672.png) | <video src="https://user-images.githubusercontent.com/387249/208731638-54d1a563-8386-4b51-ace2-efa3c5231d86.mp4">

## Expected result:

Should be able to successfullly linked an in-app-purchase of `BraveVPN` with other devices

## Reproduces how often: 

100%

## Brave version (brave://version info)

`1.47.81, Chromium 109.0.5414.46` on a `Google Pixel XL` running `Android 9`

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @brave/qa-team @bsclifton @rebron @deeppandya

**Comment by bsclifton** [comment]
Attempted fix was here:
https://github.com/brave/brave-core/pull/16407

Unfortunately, I didn't test it and it has a bug. Will fix that and verify with local build 😄

**Comment by kjozwiak** [comment]
The above requires `1.47.139` or higher for `1.47.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` & `Samsung Galaxy Tab S7` using the following version(s):

```
Brave	1.47.164 Chromium: 109.0.5414.74 (Official Build) (64-bit) 
Revision	e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}
OS	Android 12; Build/SP1A.210812.016
```

- Verified clicking on `Connect my subscription now` button will successfully link receipt to account.bravesoftware.com

Example | Example 
-|-
![screenshot-1672345961556](https://user-images.githubusercontent.com/17885425/210886642-d6f83723-eb28-465b-bd47-4e23d32009ab.png) | ![screenshot-1672952781920](https://user-images.githubusercontent.com/17885425/210886708-57926955-58f5-41e1-a1ea-9ac27b6434f9.png)
