### ISSUE TITLE
Rewards AC site list overflow issue / names do not wrap in cell

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#27470]
## Description 
Creators/sites with longer names will cause values to overflow in the container for the AC list. The attention value will not be seen unless pans with gesture. Issue seems to be that names are not wrapping in the first cell.

## Steps to reproduce 

   1. Enabled Rewards
   2. Connect account to custodian
   3. Visit creator site or watch youtube video with longer creator name 
   4. Open brave://rewards page and check site list under Auto-Contribute

## Actual result 
Values overflow
<img width="500" alt="actual" src="https://user-images.githubusercontent.com/17885425/208722080-93834626-daf8-4a13-b1c8-792a2d169650.png">

## Expected result
Values should not overflow
<img width="500" alt="expected" src="https://user-images.githubusercontent.com/17885425/208722885-2e80127b-9510-4f98-82c5-56bbf44a7bf6.png">

## Issue reproduces how often 
Easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? No
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone, Samsung Galaxy S21
   - Android version: 12
   
## Brave version
1.48.58

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.48.129 Chromium: 109.0.5414.87 (Official Build) beta (x86_64)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | macOS Version 12.6.2 (Build 21G320)
```

**Comment by stephendonner** [comment]
## Verified `PASSED` using `1.48.134`, `Chromium 109.0.5414.87` on a `Google Pixel XL` running `Android 9`

Followed the steps to reproduce from https://github.com/brave/brave-browser/issues/27470#issue-1504916460.

#### Confirmed long YouTube creator names w/titles were correctly wrapped

`1.47.x` | `1.48.134`
--------|-----------
![Screenshot_20230120-164836](https://user-images.githubusercontent.com/387249/213846820-efb3724d-c963-4796-8fc0-95e1bcd3af39.png) | ![Screenshot_20230120-222219](https://user-images.githubusercontent.com/387249/213846834-da26f47d-bca4-469b-9a4d-38c536356be7.png)
