### ISSUE TITLE
[CR 109] New setting `Certificates managed by Brave` shown in `brave://settings/security` page

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#27476]
## Steps to Reproduce

   1. Install 1.48,71
   2. launch Brave
   3. open brave://settings/security
   4. click on `Certificate managed by Brave` 

## Actual result:

New setting `Certificate managed by Brave` is shown on brave://settings/security
Clicking the link redirects to https://chromium.googlesource.com/chromium/src/+/main/net/data/ssl/chrome_root_store/root_store.md
<img width="453" alt="image" src="https://user-images.githubusercontent.com/98358127/208754274-0e7202f0-53f5-4838-a4f2-19b10f130307.png">|<img width="952" alt="image" src="https://user-images.githubusercontent.com/98358127/208754503-7a9fb358-e89e-43af-a230-e81c2433857c.png">

## Expected result:
No additional setting.

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.48.71 Chromium: 109.0.5414.46 (Official Build) nightly (64-bit)
-- | --
Revision | 6e36b77363ef3febbe792af680fa1367993ddcf0-refs/branch-heads/5414@{#709}
OS | Windows 11 Version 21H2 (Build 22000.1335)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
 @rebron

**Comment by kjozwiak** [comment]
The above will require `1.47.140` or higher for `1.47.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using

Brave | 1.47.143 Chromium: 109.0.5414.46 (Official Build) beta (x86_64)
-- | --
Revision | 6e36b77363ef3febbe792af680fa1367993ddcf0-refs/branch-heads/5414@{#709}
OS | macOS Version 11.7.2 (Build 20G1020)

Followed the steps to reproduce from https://github.com/brave/brave-browser/issues/27476#issue-1505163463

#### Confirmed there's no `Certificates managed by Brave` setting in `brave://settings/security`, and `Manage device certificates` still opens up the macOS system `Keychain Access` app

<img width="1474" alt="Screen Shot 2022-12-23 at 12 22 56 PM" src="https://user-images.githubusercontent.com/387249/209402616-144266d4-7f8a-4279-98fa-5f1a2a415cec.png">
