### ISSUE TITLE
amp="true" doesn't get detected

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#27477]
## Description 
Some AMP pages that have `<... amp="true" ...>` don't get caught by the [AMP detection regex](https://github.com/brave/brave-core/blob/master/components/de_amp/browser/de_amp_util.cc#L25). 

## Steps to reproduce 

   1. Go to https://www.foxbusiness.com/features/presidential-salaries-from-washington-to-trump.amp
   2. See that it is an AMP page

## Actual result 

AMP page

## Expected result

Not AMP page: URL should redirect to canonical link https://www.foxbusiness.com/features/presidential-salaries-from-washington-to-trump

## Issue reproduces how often 
Easily

Marking as `Android` because De-AMP is mainly used on Android. 

## Test Cases
1. If De-AMP preference is on, navigate to https://www.foxbusiness.com/features/presidential-salaries-from-washington-to-trump.amp and see that it auto-redirects
2. Go to google.com and search for "fox business presidential salaries" and click the above link (should be in top few). Check that it also auto-redirects.

**Comment by stephendonner** [comment]
## Verified `PASSED` using `1.48.134` on a `Google Pixel XL` running `Android 9`

### Steps:
1. installed `1.48.134`
2. launched Brave
3. loaded `https://www.foxbusiness.com/features/presidential-salaries-from-washington-to-trump.amp` and confirmed it redirected to `https://www.foxbusiness.com/features/presidential-salaries-from-washington-to-trump`
4. searched `Google.com` for `fox presidential salaries` and tapped the result, which loads the AMP page but redirects also to `https://www.foxbusiness.com/features/presidential-salaries-from-washington-to-trump`


`step 3`, `DevTools` | `step 3, device` | `step 4`, `search result` | `step 4`, `final URL` | `final page`
---------|---------|--------|----------|---------
<img width="1782" alt="Screenshot 2023-01-22 at 12 46 57 AM" src="https://user-images.githubusercontent.com/387249/213907973-97900f74-cf11-4033-b9e7-3e91e3848724.png"> | ![Screenshot_20230122-004742](https://user-images.githubusercontent.com/387249/213907983-eb8e7fc8-160c-4a7c-995c-00771e93c6d7.png) | ![Screenshot_20230122-004912](https://user-images.githubusercontent.com/387249/213907991-e602bccd-14b5-49a6-9bf6-beb6886d73ca.png) | ![Screenshot_20230122-010121](https://user-images.githubusercontent.com/387249/213908042-0b82627c-145a-47b2-b969-eb59b0dfb465.png) | ![Screenshot_20230122-010307](https://user-images.githubusercontent.com/387249/213908094-eb1b7ac7-a65b-47bc-b8e0-ea58cd2374a6.png)
