### ISSUE TITLE
Opening multiple confirm dialogues

### ISSUE THREAD

**Issue by Sajarin-M** [brave/brave-browser#27474]
## Description 
Opening multiple close all tabs confirm dialog when using short cut key ( Alt +f4 ) for closing Brave

## Steps to Reproduce
   1.  Press Alt + f4 multiple times to close the browser with more than 1 tabs opened.

## Actual result:
    Opens multiple confirm dialogues

## Expected result:
    Should not open confirm dialog if there is already one

## Brave version (brave://version info)
     Version 1.46.144

**Comment by rebron** [comment]
Hi @Sajarin-M. What operating system are you using?

**Comment by Sajarin-M** [comment]
> Hi @Sajarin-M. What operating system are you using? 

Fedora 37

**Comment by simonhong** [comment]
@Sajarin-M I also can repro this on ubuntu. Thanks for reporting!

**Comment by btlechowski** [comment]
Reproduced on 1.48.171

![27474](https://user-images.githubusercontent.com/34715963/222792658-b2f7bbbc-a29a-4b1f-b178-7a04bfc54225.gif)

Verification passed on

Brave | 1.49.118 Chromium: 111.0.5563.50 (Official Build) (64-bit) 
-- | --
Revision | 39f3dfc5023fe60997adc4f6cf5439cfa3e6968a-refs/branch-heads/5563@{#903}
OS | Ubuntu 18.04 LTS

Verified test plan from the description
Verified only one dialog is shown
![27474b](https://user-images.githubusercontent.com/34715963/222793538-fefbea75-b302-415d-8ab2-40bedfcd60af.gif)
