### ISSUE TITLE
Favicon for welcome page is missing in 0.59.12

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#2747]
## Description 

Found while testing #1466 
Favicon for welcome page is missing in 0.59.12

## Steps to Reproduce

   1. Open Brave beta 0.59.12
   2. Favicon for welcome page is missing 
   
## Actual result:

![image](https://user-images.githubusercontent.com/38657976/50477328-e4afb700-09f1-11e9-8179-aa4ad3a57e51.png)

## Expected result:
![image](https://user-images.githubusercontent.com/38657976/50477379-22144480-09f2-11e9-8601-451ee66e787e.png)

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 0.59.12 Chromium: 72.0.3626.17 (Official Build) beta (64-bit)
-- | --
Revision | 08d2140079f8db14c9eb885a803d231b1a30e817-refs/branch-heads/3626@{#315}
OS | Windows

### Reproducible on current release: No
- Does it reproduce on brave-browser dev/beta builds? yes on dev as well (0.60.4)

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? na
- Is the issue reproducible on the latest version of Chrome? na

### Additional Information
@brave/legacy_qa

**Comment by rossmoody** [comment]
Snuck an issue and PR in for this one already: https://github.com/brave/brave-browser/issues/2611
