### ISSUE TITLE
Disable serializableCheck Redux middleware

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#27480]
## Description 
The serializableCheck middleware is currently slowing down development builds due to it logging many messages. This should be disabled by default until we reduce the number of warnings. 

## Steps to Reproduce

   1.  Start a dev build
   2. Unlock the wallet
   3. open JS console
   4. observe warnings emitted from serializableCheck

## Actual result:

Checks and logging warning messages slowdown dev machines and obscure other logs

## Expected result:
No slowdown should occur

## Reproduces how often: 

Easily

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.48.141 Chromium: 109.0.5414.119 (Official Build) beta (64-bit) 
-- | --
Revision | `772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}`
OS | Linux

- Verified steps from [brave/brave-core#16435](https://github.com/brave/brave-core/pull/16435)
- Verified no console errors about serializableCheck is shown in console when wallet is unlocked
![image](https://user-images.githubusercontent.com/17010094/215556675-897b064a-f5d0-42d7-a560-45c0f56ca152.png)

---------------------

Verification passed on 

Brave | 1.48.141 Chromium: 109.0.5414.119 (Official Build) beta (64-bit)
-- | --
Revision | `772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#16435](https://github.com/brave/brave-core/pull/16435)
- Verified no console errors about serializableCheck is shown in console when wallet is unlocked
![image](https://user-images.githubusercontent.com/17010094/215556749-290b8905-3edd-4d14-9af6-723b0d2b9f35.png)

---------------------

Verification passed on 

Brave | 1.48.141 Chromium: 109.0.5414.119 (Official Build) beta (arm64)
-- | --
Revision | `772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#16435](https://github.com/brave/brave-core/pull/16435)
- Verified no console errors about serializableCheck is shown in console when wallet is unlocked
![image](https://user-images.githubusercontent.com/17010094/215557100-5a76ddc1-56b6-482a-87e6-d7c08fc8cfd4.png)
