### ISSUE TITLE
Getting STOD (stuck triangle of doom) trying to log in to `account.brave.com` using `Private window`

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#27481]
## Description 

Getting STOD (stuck triangle of doom) trying to log in to `account.brave.com` using `Private window`

(Found by @bsclifton, logged by yours truly)

## Steps to Reproduce

   1. install `1.48.73`
   2. launch Brave
   3. click on the `"hamburger"` menu
   4. click on `New Private Window`
   5. load `account.brave.com`
   6. enter a unique, throwaway `@mailinator.com` address
   7. click on the `Get login link` button
   8. click on the `Log in to Brave` button in the resulting email
   9. wait...

## Actual result:

<img width="1316" alt="Screen Shot 2022-12-20 at 10 50 09 PM" src="https://user-images.githubusercontent.com/387249/208840675-44239a97-2f76-4090-aafb-e305bbdb683c.png">

## Expected result:
Login and website operation should work. Native SKU SDK methods should NOT be exposed when opening JS console on account.brave.com (ex: type in `window.chrome.braveSkus`).

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.48.73 Chromium: 109.0.5414.46 (Official Build) nightly (x86_64)
-- | --
Revision | 6e36b77363ef3febbe792af680fa1367993ddcf0-refs/branch-heads/5414@{#709}
OS | macOS Version 11.7.2 (Build 20G1020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

/cc @bsclifton @brave/qa-team @mattmcalister @rebron @simonhong @spylogsster

**Comment by kjozwiak** [comment]
The above requires `1.47.140` or higher for `1.47.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 


Brave | 1.47.141 Chromium: 109.0.5414.46 (Official Build) beta (32-bit)
-- | --
Revision | 6e36b77363ef3febbe792af680fa1367993ddcf0-refs/branch-heads/5414@{#709}
OS | Windows 10 Version 22H2 (Build 19045.2364)


Followed my original steps to reproduce from https://github.com/brave/brave-browser/issues/27481#issue-1505805652.

#### Confirmed I could log in to `account.brave.com` in a `New Private window`, as well as add `Brave Talk` to my Stripe cart (didn't check out, since it's production)

(Also confirmed `SKU SDK`'s flag is set to `Default`.)

`brave://flags`| `account.brave.com` | `Stripe checkout`
----------|-----------|----------
![27481-1](https://user-images.githubusercontent.com/387249/209210476-7d0d8981-e234-4067-a357-d4ac76e8b72b.png) | 2 | 3

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.47.143 Chromium: 109.0.5414.46 (Official Build) beta (x86_64)
-- | --
Revision | 6e36b77363ef3febbe792af680fa1367993ddcf0-refs/branch-heads/5414@{#709}
OS | macOS Version 11.7.2 (Build 20G1020)

example | example
---------|---------
<img width="1312" alt="Screen Shot 2022-12-23 at 12 53 29 PM" src="https://user-images.githubusercontent.com/387249/209404752-a7e3e5e8-2b74-4f4a-a279-34888a20228d.png"> | <img width="1312" alt="Screen Shot 2022-12-23 at 12 55 27 PM" src="https://user-images.githubusercontent.com/387249/209404757-81070292-3688-4a7f-9672-f002085cffac.png">

#### Confirmed I was able to log in to and purchase a `BraveVPN` subscription from `account.bravesoftware.com` - ran into https://github.com/brave/account-brave-com/issues/53
