### ISSUE TITLE
typo in wiki install instructions

### ISSUE THREAD

**Issue by kreezxil** [brave/brave-browser#2748]
https://github.com/brave/brave-browser/wiki#build-instructions

contains a typo in the initial build requirement command you tell us to get "**rpm**" when you meant "**npm**"

**Comment by srirambv** [comment]
I don't see any typo. Could you point to the exact line?

**Comment by kreezxil** [comment]
![the typo](https://www.kreezcraft.com/wp-content/uploads/2018/12/Screenshot_1.png)

**Comment by bsclifton** [comment]
@kreezxil are you able to directly edit the wiki page? It should be open

**Comment by kreezxil** [comment]
nope, i was not able to directly edit the page, and forking the project did
not clone the wiki either.

**Comment by tomlowenthal** [comment]
Done.
