### ISSUE TITLE
Unable to link Android VPN subscription to desktop - `too many recovery attempts`

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#27483]
## Description 

Unable to link Android VPN subscription to desktop - `too many recovery attempts`

## Steps to Reproduce

   1. install `1.48.74` on Android
   2. launch Brave
   3. follow the instructions from https://github.com/brave/brave-browser/issues/27473 to buy and link a `BraveVPN` subscription from Android to `account.bravesoftware.com`
   4. now, launch desktop Brave `1.48.73`
   5. enable `VPN` via `brave://flags`
   6. click `Relaunch`
   7. load `account.bravesoftware.com`
   8. enter basic-auth credentials
   9. enter `dec2009@mailinator.com` (whatever you used for `step 3`)
   10. click `Get login link`
   11. click on `Log in to Brave`
   12. note successful `Purchased on Android` badge/icon
   13. click on `Refresh Brave VPN`

## Actual result:

`Too many recovery attempts` message

`dec2009@mailinator.com` | `Too many recovery attempts`
----------|-------------
<img width="1312" alt="Screen Shot 2022-12-21 at 12 52 56 AM" src="https://user-images.githubusercontent.com/387249/208869764-7fa82171-e9f7-43d9-a780-9675f92f5fa7.png"> | <img width="1312" alt="Screen Shot 2022-12-21 at 12 53 15 AM" src="https://user-images.githubusercontent.com/387249/208869775-3181a7ff-1759-456a-9370-5fb5828a425b.png">

## Expected result:

`You have active credentials loaded!` message

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.48.73 Chromium: 109.0.5414.46 (Official Build) nightly (x86_64)
-- | --
Revision | 6e36b77363ef3febbe792af680fa1367993ddcf0-refs/branch-heads/5414@{#709}
OS | macOS Version 11.7.2 (Build 20G1020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Miscellaneous Information:

/cc @mattmcalister @rebron @bsclifton @AlanBreck

**Comment by bsclifton** [comment]
Going to try this now - this was working last week 😄

**Comment by bsclifton** [comment]
Requires 1.48.82 or higher for verification

**Comment by kjozwiak** [comment]
The above requires `1.47.144` or higher for `1.47.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.47.145 Chromium: 109.0.5414.46 (Official Build) beta (64-bit)
-- | --
Revision | 6e36b77363ef3febbe792af680fa1367993ddcf0-refs/branch-heads/5414@{#709}
OS | Windows 10 Version 22H2 (Build 19045.2364)

Followed my steps to reproduce from https://github.com/brave/brave-browser/issues/27483#issue-1505980524, but swapped in `iOS`, since the problem was in the client-side linking code.

#### Verified I was able to purchase `BraveVPN` on iOS via in-app purchase, link to `account.bravesoftware.com`, and re-link those credentials to Windows 10 via `Refresh Brave VPN` button



### `iOS`

example | example | example | example | example | example
----------|-----------|-----------|----------|-----------|----------
![IMG_0405](https://user-images.githubusercontent.com/387249/209432073-ede9f54b-5554-481e-9965-4501fcdf13d3.jpg) | ![IMG_0406](https://user-images.githubusercontent.com/387249/209432080-e6b0d5be-7c2d-4329-b6e7-81cf12c5ecd0.jpg) | ![IMG_0408](https://user-images.githubusercontent.com/387249/209432085-1501f2b4-02f5-419b-a36b-3520fa85a19d.jpg) | ![IMG_0409](https://user-images.githubusercontent.com/387249/209432089-2cfb7648-493e-4e4f-9d5d-c7437c5dd078.jpg) | ![IMG_0410](https://user-images.githubusercontent.com/387249/209432097-45f6614c-5c0c-4f0a-9756-2cc71a41cf1e.jpg) | ![IMG_0411](https://user-images.githubusercontent.com/387249/209432104-87b1973d-faaf-402a-aea2-26297e763d0b.jpg)


### `Windows 10`

example | example | example | example
----------|-----------|----------|-----------
![desktop-1](https://user-images.githubusercontent.com/387249/209432228-55e55938-716b-4048-b5b7-158c543d9636.png) | ![desktop-2](https://user-images.githubusercontent.com/387249/209432230-d82b6b9c-d206-411b-8603-6e4d25725158.png) | ![desktop-3](https://user-images.githubusercontent.com/387249/209432232-4991f031-1d65-4b14-83a2-0fbdf83c5df1.png) | ![desktop-4](https://user-images.githubusercontent.com/387249/209432236-dfefa48d-d764-4f81-b16d-e7f6e69fbc2d.png)

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.47.164 Chromium: 109.0.5414.74 (Official Build) (x86_64)
-- | --
Revision | e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}
OS | macOS Version 13.2 (a) (Build 22D7750270d)



`Android`

example | example | example | example | example | example
---------|----------|---------|----------|----------|---------


`macOS`

example | example | example | example | example | example
---------|----------|---------|----------|----------|---------
