### ISSUE TITLE
Extensions import broken

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#27487]
## Description 

Trying to import extensions from other browsers and it doesnt work

## Steps to Reproduce

   1. go to chrome://settings/importData
   2. Import extensions from other browser
 

## Actual result:

Extensions not imported

## Expected result:

Extensions imported

## Reproduces how often: 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by MadhaviSeelam** [comment]
++ 
Reproduced this issue in 
```
Brave | 1.47.139 Chromium: 108.0.5359.128 (Official Build) beta (64-bit)
-- | --
Revision | 1cd27afdb8e5d057070c0961e04c490d2aca1aa0-refs/branch-heads/5359@{#1185}
OS | Windows 11 Version 22H2 (Build 22621.963)
```

**Comment by stephendonner** [comment]
Should this be reopened, @rebron @spylogsster ?

**Comment by spylogsster** [comment]
@MadhaviSeelam mentioned 1.47. the uplift is opened https://github.com/brave/brave-core/pull/16454 to 1.47. cc @stephendonner @rebron

**Comment by kjozwiak** [comment]
The above requires `1.47.155` or higher for `1.47.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using 

Brave | 1.47.161 Chromium: 109.0.5414.61 (Official Build) beta (x86_64)
-- | --
Revision | 846c6eff1c374cde417a9cdc44193545cc07f354-refs/branch-heads/5414@{#1030}
OS | macOS Version 11.7.2 (Build 20G1020)

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using 
```
Brave | 1.47.161 Chromium: 109.0.5414.61 (Official Build) beta (64-bit)
-- | --
Revision | 846c6eff1c374cde417a9cdc44193545cc07f354-refs/branch-heads/5414@{#1030}
OS | Windows 11 Version 21H2 (Build 22000.1335)
```
Pre-requisite:  Have Chrome browser with Extensions installed

1. Install 1.47.161
2. launch Brave
3. click `Set Brave as default browser` button
4. select `Chrome`
5. check `Chrome Person 1`
6. click `Import Profiles` button
7. verified `Setup complete` page shown
8. click `Extensions` icon in the toolbar 
9. open brave://extensions

#### Confirmed 1 Password extension` is imported successfully
#### Confirmed 1 Password extension` is shown 

step 3|step 4|step 5-6|ex|step 8|step 9
-----|-----|------|------|-------|-----
<img width="472" alt="image" src="https://user-images.githubusercontent.com/98358127/210457999-ca69c72e-c7f7-42e8-be1c-60a450ccd2d5.png">|<img width="464" alt="image" src="https://user-images.githubusercontent.com/98358127/210457991-14b3696a-e72f-46d8-8e63-7a74288f9d5d.png">|<img width="462" alt="image" src="https://user-images.githubusercontent.com/98358127/210457977-29d5e25e-ba8a-4a08-9bb2-a42d95bfd47f.png">|<img width="464" alt="image" src="https://user-images.githubusercontent.com/98358127/210457971-a93e7b63-4660-453a-a142-9dcbca1c3d3f.png">|<img width="453" alt="image" src="https://user-images.githubusercontent.com/98358127/210457957-046b4eb7-c65d-415b-b068-e210a4d54e6d.png">|<img width="458" alt="image" src="https://user-images.githubusercontent.com/98358127/210457941-f4668e20-ea05-472e-8bcd-ac16f3feb794.png">

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.47.163 Chromium: 109.0.5414.61 (Official Build) beta (64-bit)
-- | --
Revision | 846c6eff1c374cde417a9cdc44193545cc07f354-refs/branch-heads/5414@{#1030}
OS | Ubuntu 18.04 LTS

Note: Currently import of extensions from Opera is not supported.

Case 1: Import Extensions via onboarding from `Chrome` - `brave://welcome` - `PASSED`
<details>

![image](https://user-images.githubusercontent.com/34715963/210809127-c18e64db-ef4d-4f90-8902-b42a7ea5474e.png)


1. Install 1.47.x
2. launch Brave
3. click `Set Brave as default browser` button
4. select `Chrome`
5. click `Import` button
6. check `Chrome Person 1`
7. click `Import Profiles` button
8. verified `Setup complete` page shown
9. click `Finish` button
10. click `Extensions` icon in the toolbar 
11. open brave://extensions

#### Confirmed extension is successfully imported and shown in `brave://extensions`
![image](https://user-images.githubusercontent.com/34715963/210809429-a5afee4d-23a4-4b8a-8dff-5900c06791b6.png)
![image](https://user-images.githubusercontent.com/34715963/210809880-f1794dc6-77fc-43c1-8e9d-4090f147eea6.png)
![image](https://user-images.githubusercontent.com/34715963/210810031-a03b5049-1632-4af7-931c-d7f857694036.png)



</details>

Case 2: Import Extensions via onboarding from `Chrome Canary` - `brave://welcome` - `Not supported`
<details>

Chrome Canary is no supported on linux

</details>



Case 3: Import Extensions from `Edge` - `brave://welcome` - `PASSED`
<details>

Prerequisite: Install Edge with extensions, bookmarks, saved passwords 
Profile 2: bookmarks, saved passwords & extensions 
Profile 3: bookmarks, extensions 

![image](https://user-images.githubusercontent.com/34715963/210813210-7a319b86-283a-4cd1-83bb-36297a107a0f.png)


1. new profile 
2. launch Brave
3. `Skip` `Set Brave as default browser` button
4. select `Microsoft Edge`
5. click `Import` 
6. select Profile 1 & Profile 2
7. click `Import Profiles` button
8. verified `Setup complete` page shown
9. click `Finish` button
10. click `Extensions` icon in the toolbar 
11.  open brave://extensions

#### Confirmed extensions along with bookmarks from both profiles are successfully imported 

![image](https://user-images.githubusercontent.com/34715963/210813400-37ce4a17-5fb7-4c82-ba25-7752b045b76b.png)
![image](https://user-images.githubusercontent.com/34715963/210813445-772b85d9-e035-4b85-a33b-914d975c170f.png)
![image](https://user-images.githubusercontent.com/34715963/210813530-f26bbf7d-5ac3-4e20-97de-4089f10a8ffc.png)



</details>

Case 4: Import Extensions from `Chrome Dev` - `brave://welcome`- `PASSED`
<details>

![image](https://user-images.githubusercontent.com/34715963/210815265-f8ea5179-bf53-47e6-92d2-74afd7f31754.png)

Profile 1: 2 Extensions
Profile 2: No data (No extensions)

1.new profile 
2. launch Brave
3. click `Set Brave as default browser` button
4. select `Chrome`
5. click `Import` 
6. check `Chrome Dev Person 1 and Chrome Person 2` 
7. click `Import Profiles` button
8. verified `Setup complete` page shown
9. click `Finish` button
10. click `Extensions` icon in the toolbar 
11. open brave://extensions

#### Confirmed extensions are successfully imported and are shown in `brave://extensions`

![image](https://user-images.githubusercontent.com/34715963/210816730-d21e6628-fadf-4af0-af40-bef9a90a849a.png)
![image](https://user-images.githubusercontent.com/34715963/210816836-5235676c-f223-4651-9c8c-1ab27b907586.png)


</details>

Case 5: Import Extensions from `Chrome Beta ` - `brave://welcome`- `PASSED`
<details>
Person 1:  4 extensions 
<img width="957" alt="image" src="https://user-images.githubusercontent.com/98358127/210622260-25efab94-448d-41d1-9429-948f858fab67.png">

1.new profile 
2. launch Brave
3. click `Set Brave as default browser` button
4. select `Chrome`
5. click `Import` 
6. check `Chrome Beta Person 1` 
7. click `Import Profiles` button
8. verified `Setup complete` page shown
9. click `Finish` button
10. click `Extensions` icon in the toolbar 
11. open brave://extensions

#### Confirmed extensions are successfully imported and are shown in `brave://extensions`

![image](https://user-images.githubusercontent.com/34715963/210821369-b8b84760-8501-4ca2-b3ee-be8126c2071a.png)
![image](https://user-images.githubusercontent.com/34715963/210821725-47c9c24a-2125-46df-bc85-b6a723f88f50.png)
![image](https://user-images.githubusercontent.com/34715963/210821811-69a9fad1-7956-4ce4-87b7-1677444b7523.png)


</details>

Case 6: Import Extensions from `Vivaldi` - `brave://welcome`- `PASSED`
<details>

![image](https://user-images.githubusercontent.com/34715963/210822526-afd7654e-a313-4e28-b158-6f1ca7b58b11.png)
![image](https://user-images.githubusercontent.com/34715963/210823118-76e3249d-f79b-43b3-832e-c83197198faf.png)


1. new profile 
2. launch Brave
3. click `Set Brave as default browser` button
4. select `Vivaldi`
5. click `Import` 
6. select Vivaldi Person 1 & Vivaldi Person 2
7. click `Import profiles`
8. verified `Setup complete` page shown
9. click `Finish` button
10. click `Extensions` icon in the toolbar in the new-tab page
11. open brave://extensions

#### Confirmed extensions from both profiles are successfully imported and are shown in `brave://extensions`
![image](https://user-images.githubusercontent.com/34715963/210823335-dba1865f-70f9-4021-97a7-7fc8cb06e9b4.png)
![image](https://user-images.githubusercontent.com/34715963/210823393-32ce34b1-1b2f-48bd-a8c9-f6dfd3de5c5b.png)
![image](https://user-images.githubusercontent.com/34715963/210823594-417a48d0-0982-4643-9cfd-723f211552d1.png)



</details>

Case 7: Import Extensions from `Vivaldi` - `brave://settings/importData` - `PASSED`
<details>

Prerequisite: Install Vivaldi with extensions and bookmarks


1. new profile
2. click `Skip`
3. click `Skip` on `Import Settings page
4. click `Finish` button on `Help make Brave Better` page
5. open `brave:/settings/importData`
6. select `Vivaldi Person 1` from the drop down
7. Uncheck all and check only `Extensions` in the Import bookmarks and settings
8. click `Import` 
9. click `Done`
10. click `Extensions` icon in the toolbar 
11. open `brave://extensions`

#### Confirmed extension is successfully imported and shown in `brave://extensions`

![image](https://user-images.githubusercontent.com/34715963/210824226-e2696d43-dcc1-418e-82fe-90c0ca49b82d.png)
![image](https://user-images.githubusercontent.com/34715963/210824307-89f9552d-86ff-46ef-b2e1-ecd6f5b48d08.png)


</details>
