### ISSUE TITLE
Enable IPFS api on wallet page

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#27494]
Some additional methods are needed on the wallet page
1) Check if IPFS local node is launched
2) Resolve IPFS local node status like income and outcome traffic, cache size etc.
New service could be exposed or probably we can turn on and extend the ipfs_api extension api.

**Comment by vadimstruts** [comment]
The IPFS local node and scheme has been [deprecated](https://github.com/brave/brave-browser/issues/37735)
