### ISSUE TITLE
bug: android auto correct g board textarea at job page

### ISSUE THREAD

**Issue by cauerego** [brave/brave-browser#2749]
## Description 

very specific and weird one, i could easily reproduce it, but only in this very specific scenario below. the auto corrected word will not be properly replaced, causing an unexpected behaviour.

## Steps to Reproduce

   1. go to https://brave.com/jobs on Google Chrome.
   2. try pasting a resume or cover letter.
   3. use g board on Android and swype any word.
   4. replace it with any suggestion.
   5. everything works fine.
   6. now try on brave.

## Actual result:

the word won't be properly replaced. need to manually remove the misspelt one and try again.

## Expected result:
as it happens in any other scenario, such as on Chrome or here, at GitHub textarea.

## Reproduces how often: 

easily. very specific scenario. and very inconvenient one as well.

## Brave version (brave://version info)
 December 24th, Android. please let me know if you really need more.

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
sorry, haven't / won't bother to try it today.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
at this point, if I wanna try anything else, i d have to take long precautions as to not lose my current report, since i'm doing it from mobile.

- Is the issue reproducible on the latest version of Chrome? 
nope, as already mentioned.

### Additional Information

hopefully this is all. cheers, good luck and nice work! ;)

**Comment by srirambv** [comment]
Please use the Android repo to log Android issues. This repo is only for laptop/desktop. You can track your issue here https://github.com/brave/browser-android-tabs/issues/951
