### ISSUE TITLE
Follow up to #26542 - Brave is pinned to the taskbar upon Brave launch (when brave is NOT pinned explicitly)

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#27499]
## Description 

Currently first run dialog is disabled in Nightly and Beta.  But when Brave launched first time, with or without setting Brave as a default, Brave is pinned to the taskbar.   In Nightly (1.48.71), sometimes, along with pinned to taskbar, Brave icon shown as white rectangle icon.  

This issue is not reproducible 100% but I have seen the issue 3 to 4 times in 3 days while dog fooding the beta build (1.46.x)
## Steps to Reproduce

Scenario 1: (This mostly happens in Beta)

   1. Install 1.47.136
   2. launch Brave
   3. context menu in the taskbar shows Brave is not pinned
   4. click on a new-tab
   
Actual results: Context menu in the taskbar shows Brave Pinned to taskbar

Scenario 2: (This mostly happens in Nightly than Beta)

1. Install 1.48.75
2. Launch Brave 

Actual results: Brave icon was pinned to the taskbar upon launch without explicitly pinned to the taskbar

Scenario 3: Brave icon not shown when pinned to the taskbar

1. Install 1.47.139
2. Launch Brave

Actual results:  Sometimes, Brave icon doesn't show when it pins and instead something like white paper icon shown

## Actual result:

Context menu in the taskbar shows Brave Pinned to taskbar
Scenario 1:  Click a new tab
Brave Beta 
Brave not pinned  before|Brave pinned 
---|----
![image](https://user-images.githubusercontent.com/98358127/208997064-eaf91497-6ef3-4d1f-9371-68ac5587229f.png)|![image](https://user-images.githubusercontent.com/98358127/208997063-2d89d281-7fc9-4eb4-9ec3-7bb7cfa22901.png)

Brave Nightly (1.48.75)
Brave not pinned  before|Brave pinned 
----|-----
![image](https://user-images.githubusercontent.com/98358127/208996509-4b1b030f-07ea-4026-8a4d-6b44a28faf45.png)|![image](https://user-images.githubusercontent.com/98358127/208996563-9f525944-fc41-4ba1-b89a-496cd3598561.png)

Scenario 2: Brave icon was pinned to the taskbar upon launch

beta|nightly
-----|-----
<img width="960" alt="image" src="https://user-images.githubusercontent.com/98358127/208998073-41e4667f-9450-439c-9e80-36574388c8b9.png">|<img width="960" alt="image" src="https://user-images.githubusercontent.com/98358127/209000164-cb3e5067-ead1-4ddc-ba59-10fb66451eb0.png">

Scenario 3:  Brave icon is not shown on the taskbar

<img width="955" alt="image" src="https://user-images.githubusercontent.com/98358127/209219065-e367fbee-7f49-4cae-af40-e0a9082f5bf0.png">

## Expected result:
Brave should not be pinned to taskbar upon or when clicked on a new tab.  
Brave icon should be shown on the taskbar

## Reproduces how often: 

Most of the times

## Brave version (brave://version info)

```
Brave | 1.47.136 Chromium: 108.0.5359.128 (Official Build) beta (64-bit)
-- | --
Revision | 1cd27afdb8e5d057070c0961e04c490d2aca1aa0-refs/branch-heads/5359@{#1185}
OS | Windows 11 Version 21H2 (Build 22000.1335)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
<!--Any additional information, related issues, extra QA steps, configuration or data that might be necessary to reproduce the issue--
@rebron 
cc: @GeetaSarvadnya @kjozwiak

**Comment by rebron** [comment]
cc: @simonhong

**Comment by MadhaviSeelam** [comment]
@rebron tested with a new profile and made sure Brave was not pinned before.  Infact, I've uninstalled and reinstalled Brave few times to test this as well.  I think @kjozwiak has seen this issue in Nightly as well.

**Comment by simonhong** [comment]
This change comes from upstream installer changes.
Upstream installer started to pin to taskbar on Win10+ as pin api was added.
Previously only pinned to win7/8.
We don't want to pin by installer?

**Comment by rebron** [comment]
Closing as invalid per last comment by @simonhong. New behavior is expected. 
@MadhaviSeelam to file a separate issue on missing icon.

**Comment by kjozwiak** [comment]
@MadhaviSeelam mind CCing me on the new issue that you create re: icons being blank? I run into that issue on a daily basis when installing Nightly while running through verifications on `Win 11 x64`.

**Comment by MadhaviSeelam** [comment]
Filed separate bug https://github.com/brave/brave-browser/issues/27558 for missing icon (Scenario 3)
cc: @kjozwiak
