### ISSUE TITLE
Characters in URL bar populate one-by-one as popup window resizes with screen farbling on

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#27492]
## Description 

Characters in URL bar populate one-by-one as popup window resizes with screen farbling on

## Steps to Reproduce

   1. install `1.48.75`
   2. launch Brave
   3. log in to LinkedIn
   4. log in to Facebook
   5. load `https://www.linkedin.com/news/story/latest-layoffs-companies-making-cuts-6109906/`
   6. click on the `Share` button
   7. click on `Facebook`
   8. look at the resulting popup

## Actual result:

![job-cuts-bug](https://user-images.githubusercontent.com/387249/208961441-92c1c9bc-fdad-40cd-abf6-ef6fbc3e8abc.gif)

## Expected result:

<img width="1322" alt="Screen Shot 2022-12-21 at 8 57 51 AM" src="https://user-images.githubusercontent.com/387249/208961591-28aa43d1-dc1b-4c99-ac36-ef7c4dd645f5.png">

NOTE: disabling `brave://flags/#brave-block-screen-fingerprinting` fixes it

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.48.75 Chromium: 109.0.5414.46 (Official Build) nightly (x86_64)
-- | --
Revision | 6e36b77363ef3febbe792af680fa1367993ddcf0-refs/branch-heads/5414@{#709}
OS | macOS Version 11.7.2 (Build 20G1020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

/cc @goodov @pilgrim-brave @pes10k @rebron @brave/qa-team @arthuredelstein @fmarier

**Comment by kjozwiak** [comment]
Reproduced as well basically running through the STR/Cases that @stephendonner mentioned via https://github.com/brave/brave-browser/issues/27492#issue-1506629726.

* installed `1.48.75 Chromium: 109.0.5414.46` and ensured that `BraveScreenFingerprintingBlockerStudy` isn't visible under `brave://version`
* logged into both FB & LinkedIn
* opened `https://www.linkedin.com/news/story/latest-layoffs-companies-making-cuts-6109906`
* clicked on `Share` -> `Facebook`
* didn't reproduce the issue as `BraveBlockScreenFingerprinting` hasn't been enabled via `BraveScreenFingerprintingBlockerStudy`
* restarted the browser and ensured that `BraveScreenFingerprintingBlockerStudy:Enabled` via `brave://version`
*  opened `https://www.linkedin.com/news/story/latest-layoffs-companies-making-cuts-6109906`
* clicked on `Share` -> `Facebook`
* you'll notice the issue that @stephendonner mentioned above re: the new window being resized as characters are loading
* disable `brave://flags/#brave-block-screen-fingerprinting`

Once `brave://flags/#brave-block-screen-fingerprinting` has been disabled, the issue stops occurring. I'm going to wait before uplifting https://github.com/brave/brave-variations/pull/493 into `production` so @arthuredelstein can take a look. I don't think we need to revert https://github.com/brave/brave-variations/pull/484 from `Nightly` as the population is pretty small. But we shouldn't enable the feature till we know more re: the above.

**Comment by stephendonner** [comment]
## Verified `PASSED`  using 

Brave | 1.49.88 Chromium: 110.0.5481.77 (Official Build) beta (x86_64)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | macOS Version 11.7.3 (Build 20G1116)

### Steps:

1. launched Brave
2. logged in to LinkedIn
3. logged in to Facebook
4. loaded `https://www.linkedin.com/news/story/latest-layoffs-companies-making-cuts-6109906/`
5. clicked on the Share button
6. clicked on Facebook
7. looked at the resulting popup

#### Confirmed the URL in the popup was immediately fully rendered

**Comment by kjozwiak** [comment]
Removing the `QA Pass` as we uplifted the above into `1.48.x` via https://bravesoftware.slack.com/archives/CHGKGMHDJ/p1677519906590469 and we'll need to re-verify via `1.48.x`. If we don't get a `1.48.x` by the time `1.49.x` goes out, we'll move this back and re-add the `QA Pass` label.

**Comment by kjozwiak** [comment]
The above will require `1.48.173` or higher for `1.48.x` verification 👍

**Comment by kjozwiak** [comment]
Moving this back into `1.49.x` as we never ended up getting another `C110` update which means we never had another `1.48.x` release. We're going to remove the `1.48.x - Release #6` milestone. Re-adding the `QA Pass` label as the above was originally verified via `1.49.x` as per https://github.com/brave/brave-browser/issues/27492#issuecomment-1420320086 so this was technically already verified.
