### ISSUE TITLE
`Samsung Mobile` folder being added into Brave on install that includes several bookmarks

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#27503]
## Description 

When installing `Brave` on `Samsung` devices, it looks like a `Samsung Mobile` folder is created that includes the following bookmarks:

```
* Google - https://www.google.com
* Samsung - https://www.samsung.com
* Samsung Manual - https://www.samsung.com
```

We shouldn't be adding any default bookmarks into `Brave`, especially bookmarks that Brave didn't explicitly add.

## Steps to reproduce 

   1. install `1.48.60 Chromium: 108.0.5359.128`
   2. go into bookmarks and notice there's a `Samsung Mobile` folder

## Actual result 

![image](https://user-images.githubusercontent.com/2602313/209018418-e68d5b3c-24cc-4e0a-a4cb-40d9d6e32936.png)

## Expected result

We shouldn't be adding any default bookmarks into `Brave`, especially bookmarks that Brave didn't explicitly add.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `No`
- Can you reproduce this issue with the current Play Store Beta version? `Yes` 
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Mobile` & `Tablet` (Samsung S10+ & Samsung Tab S8 Ultra)
   - Android version: `Android 13`
   
## Brave version

```
Brave | 1.48.60 Chromium: 108.0.5359.128 (Official Build) canary (32-bit)
--- | ---
Revision | 1cd27afdb8e5d057070c0961e04c490d2aca1aa0-refs/branch-heads/5359@{#1185}
OS | Android 13; Build/TP1A.220624.014
```

```
Brave | 1.47.136 Chromium: 108.0.5359.128 (Official Build) beta (32-bit)
--- | ---
Revision | 1cd27afdb8e5d057070c0961e04c490d2aca1aa0-refs/branch-heads/5359@{#1185}
OS | Android 13; Build/TP1A.220624.014
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by kjozwiak** [comment]
Going to label this as `P2` as we don't want Google and others having a free ride as default bookmarks within Brave.

**Comment by kjozwiak** [comment]
The above requires `1.47.144` or higher for `1.47.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` & `Samsung Galaxy Tab S7` using the following version(s):

```
Brave	1.47.149 Chromium: 109.0.5414.46 (Official Build) beta (64-bit) 
Revision	6e36b77363ef3febbe792af680fa1367993ddcf0-refs/branch-heads/5414@{#709}
OS	Android 12; Build/SP2A.220305.013
```

- Verified Samsung Mobile folder is removed and there are no bookmarks being preloaded into Bookmarks
- Verified user is able to add folder, bookmarks into Mobile bookmarks

Example | Example
-|-
![screenshot-1672329867645](https://user-images.githubusercontent.com/17885425/209986824-2e2fdb92-1ce0-4dde-bef2-ceef22ca68e1.png) | ![screenshot-1672332455178](https://user-images.githubusercontent.com/17885425/209986826-8779e18b-80a4-4318-bca3-da4547cfa119.png)
