### ISSUE TITLE
tor window leaks timezone

### ISSUE THREAD

**Issue by bob808** [brave/brave-browser#27501]
## Description 
did the EFF test and it leaked my timezone. that doesn't happen with the tor browser.

## Steps to Reproduce
try it on https://coveryourtracks.eff.org/ I suppose linking it here is ok as it's a pretty well known test.

## Brave version (brave://version info)

Brave | 1.46.144 Chromium: 108.0.5359.128 (Official Build) (64-bit)

**Comment by pes10k** [comment]
https://github.com/brave/brave-browser/issues/8574

**Comment by ShivanKaul** [comment]
We apply the same fingerprinting protections in Tor mode as well
