### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by saucysoftware** [brave/brave-browser#27505]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.46.146  Chromium: 108.0.5359.128
Operating System: Android 13

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1.
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/c2980000-f164-5909-0000-000000000000

**Comment by bsclifton** [comment]
Backtrace https://brave.sp.backtrace.io/p/brave/debug?filters=(_rxid%3Dc2980000-f164-5909-0000-000000000000)&fingerprint=13688392ddfe6486659dbb640412c67209011f54a093d9ec46fbc5fadec415fd

Looks like it's not symbolized - but it is a `DumpWithoutCrashing`

Do you have more info, @saucysoftware?

**Comment by bsclifton** [comment]
ah - I see the steps in https://github.com/brave/brave-browser/issues/27506 😄 Thanks! 

I'll close this as a duplicate
