### ISSUE TITLE
improve the white spacing borders on the rewards modal

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#27514]
## Description 

We should improve the UI/UX on the rewards panel on `Android` on both `mobile` & `tablet`. It doesn't look as clean as it does on desktop as there's two large white spaces at the top/bottom. The middle section that's grayed out looks like it's being squeezed. Added examples of `Desktop` which looks a lot cleaner compared to `Android`.

## Steps to reproduce 

   1. install/launch `1.48.60 Chromium: 108.0.5359.128` (any version of `1.48.x` that contains the new rewards changes)
   2. tap on the BAT icon to view the rewards panel and notice the "white borders" at the bottom/bottom of the panel

## Actual result 

**`Example (Tablet)`** | **`Example (Mobile/Phone)`**
------------------------|-----------------------------------
![image](https://user-images.githubusercontent.com/2602313/209066784-6c252046-1bf6-47e9-b180-08c749db35b9.png) | ![image](https://user-images.githubusercontent.com/2602313/209067620-b076afcf-5b6c-4f40-8024-b6e05794b9a3.png)

## Expected result

**`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------
![desktop1](https://user-images.githubusercontent.com/2602313/209068390-6e5f1320-7ed1-49c4-ae63-b9a3c64458a2.png) | ![desktop2](https://user-images.githubusercontent.com/2602313/209068397-b5c60648-068a-4d44-ba24-e4fbcb356714.png) | ![desktop3](https://user-images.githubusercontent.com/2602313/209068407-ddc0ee7e-b896-476d-8a43-d113560ca96e.png)

## Issue reproduces how often 

100% reproducible using the STR/Cases mentioned above.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `No`
- Can you reproduce this issue with the current Play Store Beta version? `No` 
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Phone/Mobile` & `Tablet` (using S10+ & Tab S8 Ultra)
   - Android version: `Android 13`
   
## Brave version

```
Brave | 1.48.60 Chromium: 108.0.5359.128 (Official Build) canary (32-bit)
--- | ---
Revision | 1cd27afdb8e5d057070c0961e04c490d2aca1aa0-refs/branch-heads/5359@{#1185}
OS | Android 13; Build/TP1A.220624.014
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by tapanmodh** [comment]
https://github.com/brave/brave-core/pull/16518
