### ISSUE TITLE
Add `Copy Text From Image` entry to image's context menu

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#27513]
Add similar feature of FF's `Copy Text From Image`.
<img width="912" alt="Screenshot 2022-12-22 at 1 51 26 PM" src="https://user-images.githubusercontent.com/6786187/209059541-db13a27f-e4d1-4155-beed-8d2e3c562ef1.png">

When select that entry, browser launches a dialog and that dialog contains text from image.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.49.96 Chromium: 110.0.5481.77 (Official Build) beta (x86_64)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | macOS Version 11.7.3 (Build 20G1116)

### Steps
1. installed `1.49.96`
2. launched Brave
3. loaded `search.brave.com`
4. searched for various memes
5. also tested using `images.google.com`

#### Confirmed `Copy Text From Image` does pretty well with long text, punctuation marks, and at least one additional non-English language, Spanish

example | example | example
---------|----------|---------
<img width="1312" alt="Screen Shot 2023-02-13 at 8 48 01 PM" src="https://user-images.githubusercontent.com/387249/218646312-f903a2ff-f62c-4270-84d5-178c43f1abb9.png"> | <img width="1312" alt="Screen Shot 2023-02-13 at 8 48 32 PM" src="https://user-images.githubusercontent.com/387249/218646314-a4fff4e9-60c0-4fa8-b127-da276ac33504.png"> | <img width="1312" alt="Screen Shot 2023-02-13 at 8 50 33 PM" src="https://user-images.githubusercontent.com/387249/218646318-033ebac9-9e9c-48dd-a27c-0620faf9848e.png">

example | example | example
---------|----------|---------
<img width="1312" alt="Screen Shot 2023-02-13 at 8 41 17 PM" src="https://user-images.githubusercontent.com/387249/218646755-10ac9830-3d75-4ad1-9719-ca6362c58667.png"> | <img width="1312" alt="Screen Shot 2023-02-13 at 8 42 09 PM" src="https://user-images.githubusercontent.com/387249/218646762-ded90884-dce9-4920-8c9a-1b966e84527d.png"> | <img width="1312" alt="Screen Shot 2023-02-13 at 8 44 18 PM" src="https://user-images.githubusercontent.com/387249/218646764-468e5fb0-65c8-4b2e-9242-7c0dcea23cab.png">

**Comment by Dineshsahteli** [comment]
![image](https://user-images.githubusercontent.com/103455527/224203387-8e8b2d42-83eb-488e-968a-fe84ba0418ce.png)

**Comment by luquinhaspmw** [comment]
Not working on my Brave V 1.49.120 - Windows 10 - x64

**Comment by uzuki7777** [comment]
Same I'm also on windows 10 I don't see it working. Maybe it only works on Mac?

**Comment by luquinhaspmw** [comment]
> Same I'm also on windows 10 I don't see it working. Maybe it only works on Mac?

I think so

**Comment by bsclifton** [comment]
@uzuki7777 correct - only works on macOS at the moment
