### ISSUE TITLE
Enable Solana DApps support on stable channel

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#27527]

**Comment by kjozwiak** [comment]
The above will need to be checked using a `1.47.x` RC builds once `1.47.x` moved to the `release` channel.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.47.167 x64 build
- Verified able to connect to Solana Dapps
- Verified able to perform Send Transactions and Sign messages on Solana Dapps

Oppo Reno 5 (Android 12) | Lenovo Tab (Android 12)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/211482577-e066cc07-fbd7-4e64-9552-cb3c5f9cdea6.mp4> | <video src=https://user-images.githubusercontent.com/17010094/211481052-a19f862d-b352-49f6-a4d5-166505bff97b.mp4>
