### ISSUE TITLE
Long NFT Names need to Be Wrapped in Send Tab

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#27521]
## Description 
We need to wrap long NFT names in the `Send` tab.

![Screenshot 2022-12-22 at 9 58 33 AM](https://user-images.githubusercontent.com/40611140/209188056-3f5111a2-ba5b-466a-ac3b-be9ba7fedf31.png)

**Comment by srirambv** [comment]
QA Blocked on [#28131](https://github.com/brave/brave-browser/issues/28131)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.48.155 Chromium: 110.0.5481.77 (Official Build) (64-bit) 
-- | --
Revision | `65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}`
OS | Linux

- Verified steps from [brave/brave-core#16460](https://github.com/brave/brave-core/pull/16460)
- Verified long NFT names are wrapped in Send tab when selected
- Encountered [#28259](https://github.com/brave/brave-browser/issues/28259), [#28275](https://github.com/brave/brave-browser/issues/28275), [#28276](https://github.com/brave/brave-browser/issues/28276), [#28277](https://github.com/brave/brave-browser/issues/28277)

https://user-images.githubusercontent.com/17010094/216656222-6ae775ad-91c4-4577-894c-f6b9d4e60aa3.mp4

---------------------

Verification passed on 

Brave | 1.48.155 Chromium: 110.0.5481.77 (Official Build) (64-bit)
-- | --
Revision | `65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#16460](https://github.com/brave/brave-core/pull/16460)
- Verified long NFT names are wrapped in Send tab when selected
- Encountered [#28259](https://github.com/brave/brave-browser/issues/28259), [#28275](https://github.com/brave/brave-browser/issues/28275), [#28276](https://github.com/brave/brave-browser/issues/28276), [#28277](https://github.com/brave/brave-browser/issues/28277)

https://user-images.githubusercontent.com/17010094/216656576-c5d74004-918d-4d94-8898-c9353be87227.mp4


---------------------

Verification passed on 

Brave | 1.48.155 Chromium: 110.0.5481.77 (Official Build) (arm64)
-- | --
Revision | `65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#16460](https://github.com/brave/brave-core/pull/16460)
- Verified long NFT names are wrapped in Send tab when selected
- Encountered [#28259](https://github.com/brave/brave-browser/issues/28259), [#28275](https://github.com/brave/brave-browser/issues/28275), [#28276](https://github.com/brave/brave-browser/issues/28276), [#28277](https://github.com/brave/brave-browser/issues/28277)

https://user-images.githubusercontent.com/17010094/216657898-f9d00d77-028f-4adb-aff4-46b8cf19547d.mov
