### ISSUE TITLE
Check VPN purchase token format before allowing browser to write it to local storage

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#27524]
## Description
With our cross-platform VPN, users can link their in-app-purchase of Brave VPN to account.brave.com

The purchase token is shared with the website using a render frame observer which writes a local storage value (specifically a session storage value). You can see that here:
https://github.com/brave/brave-core/blob/master/components/brave_vpn/renderer/android/vpn_render_frame_observer.cc#L81

We are assured the purchase token is valid because we have already made it past the check:
https://github.com/brave/brave-core/blob/f35783b3163fcff31cf2cf1a34695e484069bd2c/android/java/org/chromium/chrome/browser/vpn/utils/InAppPurchaseWrapper.java#L144-L151

However, we never check the input before storing the value in preferences. 
https://github.com/brave/brave-core/blob/f35783b3163fcff31cf2cf1a34695e484069bd2c/android/java/org/chromium/chrome/browser/app/BraveActivity.java#L626-L631

Because it's a purchase token, we should be able to check if it's base64.

If the purchase token isn't in that format (should never happen; no known cases), we should set the purchase token to empty string `""` and error out if possible.

**Comment by bsclifton** [comment]
Follow up - purchase token is not Base64 actually. We'll need to find more docs and a proper way to check

**Comment by diracdeltas** [comment]
can we pick this up again? as mentioned in slack i think maybe the purchase token is in `in base64url charset + . https://base64.guru/standards/base64url ` @bsclifton

**Comment by diracdeltas** [comment]
@deeppandya is it not possible to check the first part? attacker could bypass https://github.com/brave/brave-core/commit/dfaa5c48450cb4cfed5121c9770962800832b657#diff-f523af76f7626f7c76a089a2a1f366462204db9d4419497578b6a242942a11b9R164-R165 with a token like `")alert(1).base64part`

**Comment by deeppandya** [comment]
are you suggesting to check first part separately ? if so we can definitely do that.

**Comment by diracdeltas** [comment]
@deeppandya yes

**Comment by deeppandya** [comment]
I have updated the change.

**Comment by kjozwiak** [comment]
The above requires `1.49.118` or higher for `1.49.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on Samsung GS 21 5G using version:

```
Brave	1.49.118 Chromium: 111.0.5563.50 (Official Build) (64-bit) 
Revision	39f3dfc5023fe60997adc4f6cf5439cfa3e6968a-refs/branch-heads/5563@{#903}
OS	Android 13; Build/TP1A.220624.014
```
Ensured user is able to successfully link credentials on `account.brave.com` using test criteria in https://github.com/brave/brave-browser/issues/27524#issue-1508670819

Example | Example | Example
-|-|-
![screenshot-1677879283375](https://user-images.githubusercontent.com/17885425/222835794-6a0c9944-2e09-4258-8622-b738cdb6690c.png) | ![screenshot-1677879295032](https://user-images.githubusercontent.com/17885425/222835799-8793254c-4ae2-40ce-9ff2-c4f73b7f0fc4.png) | ![screenshot-1677879765917](https://user-images.githubusercontent.com/17885425/222835803-17402233-2d48-4261-b20e-8b390d69938e.png)
