### ISSUE TITLE
Vertical tab bar does not work with fullscreen video playback + Vertical tab bar UI glitches

### ISSUE THREAD

**Issue by snocodile** [brave/brave-browser#27537]
## Description 
The vertical tab bar background persists in fullscreen video mode. 
Videos play next to the bar's background. 
Furthermore the bar does not display correctly and there's glitches when it's being extended.

## Steps to Reproduce
   1. Enable [#brave-vertical-tabs](chrome://flags/#brave-vertical-tabs) flag. Restart browser.
   2. Set tab bar to vertical from context menu. Retract/extend tab bar.
   3. Start fullscreen video playback.

## Actual result:
- Persistent Artefact at the bottom of the tab bar.
- When extending the bar (via top button, or "mouse hover" option) more artefacts appear.
- Tab bar background (both when extended or not) persists. Video plays next to it instead of fullscreen.

_See the bottom of the bar:_
![verticaltabs](https://user-images.githubusercontent.com/47285814/209386963-6f6d4ca3-db0c-43bc-a4b3-3c95045c1ed6.png)

_After tab war was extended in the same window:_
![verticaltabs_extend](https://user-images.githubusercontent.com/47285814/209386970-698c5585-09cd-4ea7-9070-983c1d35ad7a.png)

_Same as first when starting with extended tab bar in new window:_
![verticaltabs_extended](https://user-images.githubusercontent.com/47285814/209386977-c89ad584-7e3d-4785-be13-962181ade92d.png)

_Fullscreen playback while tab bar is extended:_
![verticaltabs_extended_fullscreen](https://user-images.githubusercontent.com/47285814/209386985-c424486b-99fe-4d78-9177-fd61e6176f9a.png)

_Fullscreen playback when tab bar is retracted:_
![verticaltabs_fullscreen](https://user-images.githubusercontent.com/47285814/209386994-b4f1823b-43a5-4055-9cf9-01a947e596b9.png)

## Expected result:
- Vertical tab bar follows set theme (extended or not).
- Vertical tab bar auto-hides when entering fullscreen mode. Video plays in fullscreen.

## Reproduces how often: 
Easily reproduced.

## Brave version (brave://version info)
1.47.136 Chromium: 108.0.5359.128 (Official Build) beta (64-Bit) 

## Version/Channel Information:
Beta Channel.

## Other Additional Information:
Disabling Brave Shields, Brave Rewards does **not** solve the issues. 
Neither does resetting/changing the browser's theme or being in non-maximized window mode.

Reverting back to horizontal tab bar solves the issues.

## Miscellaneous Information:
N/A

**Comment by rebron** [comment]
related: https://github.com/brave/brave-browser/issues/25511

**Comment by sangwoo108** [comment]
Hello, I believe this has gone at this moment. So let me close this. Thanks!

**Comment by DanielSmedegaardBuus** [comment]
Yeah, this is completely broken. Would be nice to have a fix :) But nice to have vertical tabs :)

**Comment by sangwoo108** [comment]
Hi, @DanielSmedegaardBuus . Could you let me know which version you're using?
