### ISSUE TITLE
Brave News Customization Revamp

### ISSUE THREAD

**Issue by tapanmodh** [brave/brave-browser#27535]
This is a blanket issue around the new settings UI for the Brave News revamp

## Description 
List of specs around the new settings revamp:

- [Brave News sources spec](https://docs.google.com/document/u/0/d/1jZy_URJVkUVVhLfLIaTviX5x5htlXugfQvPg7yIweTk/edit)
- [Customize Brave News spec](https://docs.google.com/document/u/0/d/1t-XxP5ykelNyrkCVKE4_wtjIZzqPB7-6ZrYTq-KSg-Q/edit)
- [Source Suggestion For Brave News](https://docs.google.com/document/u/0/d/1qddkc3D1Ei8oSqP442cmrJZYUZw24lxC5OUv0gkS-_o/edit)
- [Brave News Internationalization Spec](https://docs.google.com/document/u/0/d/1O1il9DW3Z5b0Twb3x37Ar2g48Zhszr7NXzsM_VK-aCQ/edit)
- [Brave News 2.0 Migration spec](https://docs.google.com/document/u/0/d/1pzULBR3SRgggkams6uciRhE07Lhu1pf73OQpKxIzDyU/edit)

## Steps to reproduce 

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
As discussed with @deeppandya @mattmcalister @timchilds, this we'll get enabled on `1.49.x` as it's still currently disabled using `brave:/flags`. We'll enable the above feature in `1.50.x` for a few days and keep an eye on reports/community. If things appear somewhat stable, we'll enable via `1.49.x`.

@deeppandya mentioned he'll create the issue/PR to get `Brave News v2` enabled on `1.50.x`. @deeppandya once that's done, can you make sure you link any issues that could be used to help us verify the feature within the GH issue that you'll create to enable the above.

**Comment by deeppandya** [comment]
@kjozwiak i have created a PR to enable Brave News V2 on nightly here : https://github.com/brave/brave-variations/pull/520
