### ISSUE TITLE
Google sign in is not working anymore

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#27533]
## Description 

Google sign in is not working anymore https://accounts.google.com in Nightly. When you enter email you get message about enabling cookies. This is working correctly in version 1.46.144 (release), but not in version 1.48.75 (nightly).

I tried disabling shields as well, but it still doesn't work.

## Steps to Reproduce

   1. Download version 1.48.75
   2. Go to https://accounts.google.com
   3.  Enter email

## Actual result:

<img width="665" alt="image" src="https://user-images.githubusercontent.com/9574457/209275463-d0d7352c-5813-4e31-9560-d5611a32e7d5.png">

## Expected result:
You should see input for entering password

## Reproduces how often: 

Every time

## Brave version (brave://version info)

1.48.75

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by rebron** [comment]
I think it's this https://github.com/brave/brave-core/pull/15330 
and reverted here: https://github.com/brave/brave-core/pull/16443

@NejcZdovc can you recheck in 1.48.77 and higher version of nightly? 
And Merry Christmas!

**Comment by ShivanKaul** [comment]
@NejcZdovc hmm, that feature shouldn't be applicable to first party websites like accounts.google.com. Did you receive a permission prompt like this when you tried to login?

<img width="425" alt="image" src="https://user-images.githubusercontent.com/5284154/210123472-3ccb6b65-a67e-4093-8ee5-9e5f16fc949d.png">

**Comment by ShivanKaul** [comment]
@ryanbr could this be connected to https://github.com/easylist/easylist/commit/38891e2b12256204d90d11a2940a2a67a61a18af?

**Comment by ryanbr** [comment]
@ShivanKaul no. Just tested to be sure, enabling FB Annoyances, in a new Brave profile. Able to login without issue. 

Can you update to the latest (later build) @NejcZdovc, can you login?

**Comment by NejcZdovc** [comment]
This is working for me now. 

I went to brave://settings/cookies and noticed that I had `https://accounts.google.com` in section `Sites that can never use cookies` (don't remember disabling cookies). I removed it, install the latest nightly and restart the browser. That fixed it.
