### ISSUE TITLE
No Audio on Facebook Texas Holdem Game

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#2753]
## Description 
Facebook apps/games may not play audio, and don't surface any interactive UI to allow audio.

## Steps to Reproduce
1. Navigate to https://apps.facebook.com/texas_holdem/ (you'll need a Facebook account)
2. Lower your shields for the page to work (this needs another issue)

## Actual result:
No audio is played, and no interactive UI is shown for the user to enable audio.

## Expected result:
Audio should play.

## Reproduces how often: 
Always.

## Brave version (brave://version info)
0.58.18

### Reproducible on current release:
Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? No

### Additional Information
Facebook apps are rendered within ad-hoc iframes, whose source is `javascript:`. This may have something to do with which origins are allowed to play audio.

I suspect this issue impacts other facebook apps/games as well.

This issue was originally [reported on Twitter](https://twitter.com/UnwaveringSptr/status/1078539567198810112).

**Comment by bsclifton** [comment]
Closing as stale; there haven't been any additional reports. Please re-open if this is still a problem
