### ISSUE TITLE
Update hyperlink color in brave://rewards page

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#27546]
## Description

Figma: 
![image](https://user-images.githubusercontent.com/11497541/209588059-475bbb18-89ef-4886-a567-8f21bcbafc7c.png)

Actual:
![image](https://user-images.githubusercontent.com/11497541/209588075-2f08d0a8-8418-48c5-8cb9-4ef02b36a517.png)
![image](https://user-images.githubusercontent.com/11497541/209588085-924f3acb-6416-41cf-858b-b1c8b3c543fa.png)

## Solution

Make conformant to color specified in Figma.

**Comment by kjozwiak** [comment]
The above requires `1.48.121` or higher for `1.48.x` 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on


```
Brave | 1.48.125 Chromium: 109.0.5414.87 (Official Build) beta (64-bit)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | Windows 10 Version 21H2 (Build 19044.2486)
```

- Verified the test plan from https://github.com/brave/brave-core/pull/16542

**_Clean profile_**

- Ensured that the hyperlink color in brave://rewards page is shown as per the test plan or Figma
- Ensured that click on each hyperlink redirects to the intended brave support page

Brave rewrads OFF | Brave rewards ON
---------------------|-----------------------
![image](https://user-images.githubusercontent.com/38657976/212292698-977b9beb-46f6-4a79-a6f2-142f57679d11.png) | ![image](https://user-images.githubusercontent.com/38657976/212292785-4bb784b5-58fe-4a74-b73f-b10e1826b454.png)


**_Upgrade profile_**

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using `Brave` `1.48.140` on a `Google Pixel XL` (`arm64`) running `Android 9`

### Steps:
1. installed `1.47.161`
2. launched Brave
3. skipped onboarding
4. opened `brave://rewards`
5. took note of page styles, font weights, underlines, etc. (screenshot) with Rewards disabled
6. installed `1.48.140`
7. launched Brave
8. opened `Brave Rewards` via the three-dots menu -> `Brave Rewards`
9. compared page styles, font weights, underlines, etc. to that in`1.47.161`
10. tapped on the links

#### `Basic attention token` loads to `https://brave.com/brave-rewards/`
#### `Terms of Service` loads to `https://basicattentiontoken.org/user-terms-of-service/`
#### `Privacy Policy` redirects to https://brave.com/privacy/browser/#rewards`

#### Confirmed `brave://rewards` matches Figma, here




`1.47.161` | `1.48.140`
-----------|----------
![Screenshot_20230125-154924](https://user-images.githubusercontent.com/387249/214721287-4dae1b5d-b250-488d-9593-d0c6c9fa6bf6.png) | ![Screenshot_20230125-154159](https://user-images.githubusercontent.com/387249/214721374-f3973780-f0a4-482e-ac00-856b374bd3d8.png)


`1.47.161` | `1.48.140`
----------|----------
![Screenshot_20230125-154951](https://user-images.githubusercontent.com/387249/214721706-793976bb-0be2-4abb-bf36-f29400c0f98c.png) | ![Screenshot_20230125-155709](https://user-images.githubusercontent.com/387249/214721704-91977ff8-e2de-4a45-83fc-1621e6548f40.png)
