### ISSUE TITLE
Remove "Backup" tab in Manage section in brave://rewards

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#27547]
## Description

- [x] Remove "Backup" tab in the brave://rewards manage section
- [x] Rename to "Reset Brave Rewards"
- [x] Change brave://rewards "Manage" button to say "Reset"
- [x] Remove the pill tab selector in the modal

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.50.85 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | Windows 10 Version 21H2 (Build 19044.2604)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/17173 and the description from the issue
    - Confirmed that "Manage" button is renamed to "Reset"
    - Confirmed that "Manage Brave Rewards" is renamed to "Reset Brave Rewards"
    - Confirmed that "Backup" tab is removed from `Manage Brave Rewards`
    - Confirmed that pill tab selector is reoved from the "Reset Brave Rewards" modal
    - Confirmed that content of the "Reset Brave Rewards" modal is as per the test plan https://github.com/brave/brave-core/pull/17173
    - Confirmed that click on `Learn more` and `supportive article about resetting` is redirected to https://support.brave.com/hc/en-us/articles/10007969237901

Example | Example | Example
---------|------------|----------
![image](https://user-images.githubusercontent.com/38657976/224750445-d5515e8e-7531-4b12-9606-e730fa78674e.png) | ![image](https://user-images.githubusercontent.com/38657976/224750514-1fb3ac63-a763-4d16-a8aa-cd0555cac0af.png) | ![image](https://user-images.githubusercontent.com/38657976/224750964-9dcc32ea-6218-4894-9728-f6f4baf54d9d.png)

**Comment by GeetaSarvadnya** [comment]
@Miyayes Looks like this issue is applicable for Desktop only as we don't see "Backup" tab in brave://rewards, correct me if I am missing anything
cc: @deeppandya @LaurenWags

**Comment by Miyayes** [comment]
@GeetaSarvadnya Yes that's correct. Deep and Emerick were working on also using the "Manage / Reset" modal for Android, but the change wasn't made before this issue, so it is not applicable in this case. I've removed OS/Android for this issue.
