### ISSUE TITLE
Migrate sync code to Syncable Service

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#2754]
https://www.chromium.org/developers/design-documents/sync/syncable-service-api

**Comment by darkdh** [comment]
Test Plan:
1. Test all sync test cases with fresh profile
2. Test all sync test cases launching from legacy sync profile
3. Use new sync device joining existing legacy sync chain(mobile included)
4. Use legacy sync device(mobile included) joining new sync chain

**Comment by btlechowski** [comment]
LGTM.

Verified test plan from https://github.com/brave/brave-browser/issues/2754#issuecomment-496602362

sync 0.71.x with 0.71.x
[PASS] Existing bookmarks sync through code words
[PASS] New bookmark sync
[PASS] New folder sync
[PASS] Moved bookmark
[PASS] Moved bookmark folder
[PASS] Deleted bookmark
[PASS] Deleted bookmark folder
[PASS] 5000 bookmarks sync
[PASS] Sync after going offline

sync 0.71.x with 0.68.x
[PASS] Existing bookmarks sync through code words
[PASS] New bookmark sync
[PASS] New folder sync
[PASS] Moved bookmark
[PASS] Moved bookmark folder
[PASS] Deleted bookmark
[PASS] Deleted bookmark folder
[PASS] 5000 bookmarks sync

sync 0.71.x with Android
[PASS] Existing bookmarks sync through QR code
[PASS] New bookmark sync
[PASS] New folder sync
[PASS] Moved bookmark
[PASS] Moved bookmark folder
[PASS] Deleted bookmark
[PASS] Deleted bookmark folder
[PASS] 5000 bookmarks sync

Also synced multiple devices at once.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.69.130 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Ubuntu 18.04 LTS

Verified `Sync` part of manual testrun
Verified https://github.com/brave/brave-browser/issues/2754#issuecomment-496602362
Verified https://github.com/brave/brave-browser/issues/2754#issuecomment-524852717

Devices used:
Brave 0.69.130
Brave 0.68.142
Android 1.3.2
iOS 1.12.1
