### ISSUE TITLE
blank screen shown after completing onboarding, enabling news and clicking `Customize` button in the new-tab page

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#27556]
## Description 

Found this issue while testing https://github.com/brave/brave-browser/issues/26378.  Launched a new profile and completed on boarding including import.  Gray screen shown after enabling news in the new tab page and clicked Customize button. `Customized Dashboard` screen shown for a quick second before showing gray screen.  However, Gray screen not shown when skipped  when skipped thru onboarding process

## Steps to Reproduce

1. Install 1.47.149
2. launch Brave
3. click `Set Brave as default browser`
4. select `Microsoft Edge` 
5. click `Import`
6. click `Finish`
7. click `Turn on Brave News` in the new tab page
8. click `Customize`

## Actual result:

Gray screen shown when completed onboarding

https://user-images.githubusercontent.com/98358127/209876842-29120e5d-ce94-47df-82ed-ed52fc0ae89c.mp4

Gray screen not shown when skipped thru onboarding process

https://user-images.githubusercontent.com/98358127/209876869-8fe25848-1a6f-4cb2-a0e5-0916de2b5a13.mp4

## Expected result:

Brave news dashboard screen should be shown

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.47.149 Chromium: 109.0.5414.46 (Official Build) beta (64-bit)
-- | --
Revision | 6e36b77363ef3febbe792af680fa1367993ddcf0-refs/branch-heads/5414@{#709}
OS | Windows 11 Version 22H2 (Build 22621.963)
```
## Version/Channel Information:

- Can you reproduce this issue with the current release?  N/A
- Can you reproduce this issue with the beta channel?  Yes
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
@rebron @nullhook

**Comment by rebron** [comment]
cc: @petemill @fallaciousreasoning When you get a chance can you take a look?

**Comment by petemill** [comment]
Let's add the error from devtools when the grey screen is shown, please

**Comment by MadhaviSeelam** [comment]
@petemill here it is:
<img width="959" alt="image" src="https://user-images.githubusercontent.com/98358127/209994787-45df95d3-d322-4d90-a91c-b1ebc628cf9b.png">

**Comment by MadhaviSeelam** [comment]
@fallaciousreasoning  - This is reproducible in `1.47.168`.   It appears this behavior displayed with certain profiles in some browsers.
Note:  **Not seeing this issue with `1.48.118 Chromium: 109.0.5414.80`**

I have following browsers installed:

-  `Microsoft Edge `with 3 profiles 
-  `Vivaldi` with 3 profiles 
-  `Chrome Canary` with 2 profiles 

blank screen shown with `Edge - Profile 1` and `Vivaldi  - Person 2`.  However `Brave News Dashboard `was shown as expected with `Chrome Canary`.  
`Firefox`, `Chrome`, `Edge`, `Vivaldi`, `Opera `are shown blank screen with certain profiles except for `Chrome Canary`


Microsoft Edge Profile 2- Gray/blank screen

https://user-images.githubusercontent.com/98358127/211636936-5cb713b6-ce9e-4ce9-9d74-448e506c936a.mp4


Microsoft Profile 1- Brave news dashboard shown

https://user-images.githubusercontent.com/98358127/211637410-8de35b28-24d5-4a8f-909c-07b4c9e46eff.mp4


cc: @rebron

**Comment by stephendonner** [comment]
I saw this once using `1.48.119 Chromium: 109.0.5414.80 (Official Build) beta (x86_64)`, but am unsuccessful in later retries 😞 

<img width="1077" alt="Screen Shot 2023-01-10 at 1 33 35 PM" src="https://user-images.githubusercontent.com/387249/211670423-17a8678a-673d-4d44-bce5-7cb23d9b971a.png">

**Comment by mattmcalister** [comment]
was this resolved? I can't reproduce.

**Comment by stephendonner** [comment]
> was this resolved? I can't reproduce.

I haven't seen this since, but I'll let @MadhaviSeelam chime in.
