### ISSUE TITLE
`Chromium- based browser` shown on `Import Settings` screen

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#27557]
## Steps to Reproduce

 Pre-requisite:  Brave Nightly and Microsoft Edge browsers are installed

   1. Install 1.47.151
   2. launch Brave
   3. click `Set Brave as default browser`

## Actual result:

`Chromium- based browser` is checked as default

## Expected result:
Along with Edge, Brave Nightly should be listed 
![image](https://user-images.githubusercontent.com/98358127/209884971-4fb95052-39ca-47cc-bd80-837282d3dcf8.png)

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.47.151 Chromium: 109.0.5414.46 (Official Build) beta (64-bit)
-- | --
Revision | 6e36b77363ef3febbe792af680fa1367993ddcf0-refs/branch-heads/5414@{#709}
OS | Windows 11 Version 22H2 (Build 22621.963)
```
## Version/Channel Information:

- Can you reproduce this issue with the current release?  N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
@rebron @nullhook

**Comment by kjozwiak** [comment]
The above requires `1.48.151` or higher for `1.48.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.48.152 Chromium: 109.0.5414.119 (Official Build) beta (64-bit)
-- | --
Revision | 772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}
OS | Windows 11 Version 21H2 (Build 22000.1455)
```

- Install 1.48.152
- launch Brave
- click `Set Brave as default browser` in the `brave://welcome` screen
- verify `Import Settings` page

#### Confirmed `Microsoft Internet explorer` is shown with correct icon not selected as default.


<img width="462" alt="image" src="https://user-images.githubusercontent.com/98358127/216104658-b759013d-62e2-4aad-9531-a7e5dca26a29.png">

**Comment by LaurenWags** [comment]
Removed `QA/Test-All-Platforms` label per discussion with @kjozwiak @rebron
