### ISSUE TITLE
can't disable `video background playback` when enabled via `BgPlaybackStudy`

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#27550]
## Description 

There's a bug with `Video Background Playback` were you can't disable the feature once it's been enabled by `BgPlaybackStudy:Enabled`. It's currently set to `100%` on both `Nightly` & `BETA` and set as `25%` on `release` as per https://github.com/brave/brave-variations/pull/496. We should disable `BgPlaybackStudy` via Griffin on `release` until we fix the above bug. Users should be able to disable the feature and shouldn't be forced to use it. Originally reported by @A-t-s-u-s-h-i.

## Steps to reproduce 

   1. install any version of `Brave` on either `Nightly`, `BETA` or `Release`
   2. restart `Brave` and ensure that `BgPlaybackStudy:Enabled` via `brave://version`
   3. attempt to disable `Video Background Playback` via `Settings`

Quick Note: `BgPlaybackStudy:Enabled` is only enabled at `25%` on the `release` channel as per https://github.com/brave/brave-variations/pull/496.

## Actual result 

https://user-images.githubusercontent.com/2602313/209679894-68fb4454-8ba8-444b-a0ec-7213c6bc776e.mp4

## Expected result

Users should be able to disable `Video Background Playback` without any issues.

## Issue reproduces how often 

100% reproducible using the following STR/Cases.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `Yes`
- Can you reproduce this issue with the current Play Store Beta version? `Yes` 
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Samsung Galaxy S10+`
   - Android version: `Android 13`
   
## Brave version

```
Brave | 1.46.146 Chromium: 108.0.5359.128 (Official Build) (32-bit)
--- | ---
Revision | 1cd27afdb8e5d057070c0961e04c490d2aca1aa0-refs/branch-heads/5359@{#1185}
OS | Android 13; Build/T2B1.221118.006
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by kjozwiak** [comment]
CCing @SergeyZhukovsky

**Comment by kjozwiak** [comment]
Disabling `BgPlaybackStudy` on `production` via https://github.com/brave/brave-variations/pull/498 until the above is addressed.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 13` using the following build(s):

```
Brave | 1.46.154 Chromium: 108.0.5359.128 (Official Build) (32-bit)
--- | ---
Revision | 1cd27afdb8e5d057070c0961e04c490d2aca1aa0-refs/branch-heads/5359@{#1185}
OS | Android 13; Build/T2B1.221118.006
```

* ensured that `brave://flags#brave-background-video-playback` is set as `Default` on new profiles (disabled)
  * ensured that the `Background video playback` feature is disabled
* ensured that `brave://flags#brave-background-video-playback` is set as `Enabled` once `Background video playback` has been enabled via `Settings`
* ensured that `brave://flags#brave-background-video-playback` is set as `Disabled` rather than `Default` when disabling `Background video playback` once it was enabled

**`Clean Profile/First Launch`**

**`Example`** | **`Example`**
---------------|-----------------
![Screenshot_20230106-195603](https://user-images.githubusercontent.com/2602313/211123738-16e03d95-8b70-464b-b035-52618f7b3cc0.png) | ![Screenshot_20230106-195621](https://user-images.githubusercontent.com/2602313/211123742-d38cf180-a82b-4308-add1-8501b3ddc059.png)

**Enabling `Background video playback`**

**`Example`** | **`Example`**
---------------|-----------------
![Screenshot_20230106-195653](https://user-images.githubusercontent.com/2602313/211123756-866c69c9-754b-4cac-9483-62d603785d07.png) | ![Screenshot_20230106-195659](https://user-images.githubusercontent.com/2602313/211123759-4e8cbb0f-630d-47ab-88c4-b1debf50d03c.png)

**Disabling `Background video playback`**

**`Example`** | **`Example`**
---------------|-----------------
![Screenshot_20230106-195716](https://user-images.githubusercontent.com/2602313/211123780-f50cc54a-ed68-4f7a-8744-7cf168940ec2.png) | ![Screenshot_20230106-195723](https://user-images.githubusercontent.com/2602313/211123782-ecef8311-76e0-4243-a06f-28edfeae008a.png)

**Comment by Uni-verse** [comment]
Verified on Samsung Galaxy Tab S7 using version:

Brave 1.46.154 Chromium: 108.0.5359.128 (Official Build) (32-bit)
Revision 1cd27afdb8e5d057070c0961e04c490d2aca1aa0-refs/branch-heads/5359@{https://github.com/brave/brave-browser/issues/1185}
OS Android 12; Build/SP2A.220305.013

- Verified `brave://flags#brave-background-video-playback` is set as default on clean profile
- Verified `background video playback` setting is disabled by default
- Verified `brave://flags#brave-background-video-playback` is enabled when `background video playback` setting is enabled
- Verified `brave://flags#brave-background-video-playback` is disabled when `background video playback` setting is disabled
- Verified when changing `video background playback` setting user is prompted to relaunch browser

Defaults | Defaults
-|-
![screenshot-1673057444404](https://user-images.githubusercontent.com/17885425/211127139-7f11c867-f57d-4d8c-ba6c-cccc423fb097.png) | ![screenshot-1673057480805](https://user-images.githubusercontent.com/17885425/211127141-0e8cbbe7-a436-43e2-bc2e-7f01958f156a.png)

Enabled Flags | Enabled Setting | Disabled
-|-|-
![screenshot-1673057536171](https://user-images.githubusercontent.com/17885425/211127228-771f3856-80b2-4fc5-88e2-d9d1a8043614.png) | ![screenshot-1673057547181](https://user-images.githubusercontent.com/17885425/211127229-f23cd075-cdcf-42d8-99ee-17e2114b45fa.png) | ![screenshot-1673057587291](https://user-images.githubusercontent.com/17885425/211127238-8b38cf9e-3762-4c3f-87c4-3e708d5b3c74.png)
