### ISSUE TITLE
please add cloud storage

### ISSUE THREAD

**Issue by dfmabbas** [brave/brave-browser#2756]
Hi, I need to add cloud storage to **synchronize** mobile data with my personal computer and save cookies, passwords and ... online.

**Please add this, thanks**

**Comment by srirambv** [comment]
You can use Brave Sync to synchronise bookmarks across your devices running Brave once its available on all platforms.

**Comment by dfmabbas** [comment]
@srirambv ** Why ? !! **

**Comment by oky2abbas** [comment]
What if my operating system becomes unusable?
All my information will be erased !
