### ISSUE TITLE
Onboarding does not show profile names

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#27566]
Actual result in brave:
<img width="559" alt="image" src="https://user-images.githubusercontent.com/2965009/209972986-fdd929ef-eaed-4b13-a3f8-560727f89afe.png">

In Chrome:
<img width="308" alt="image" src="https://user-images.githubusercontent.com/2965009/209973806-3d8df4c5-27d5-441a-992a-3160e476b4fd.png">

Related issue:
https://github.com/brave/brave-browser/issues/27561

**Comment by spylogsster** [comment]
cc @rebron

**Comment by rebron** [comment]
@MadhaviSeelam @stephendonner Is this only Firefox?

**Comment by stephendonner** [comment]
> @MadhaviSeelam @stephendonner Is this only Firefox?

Appears that way from my testing progress thus far.

**Comment by MadhaviSeelam** [comment]
> @MadhaviSeelam @stephendonner Is this only Firefox?

Looks to be only Firefox as well in Win 11.

**Comment by bsclifton** [comment]
If the profile name wasn't being shown before, this is definitely better

But still looks a bit weird after you explicitly pick "Mozilla Firefox" for example:
![image](https://user-images.githubusercontent.com/4733304/210407017-5d9275be-19b6-4c98-aa94-80d1e9762925.png)

I think the change here is fine 😄 But maybe we could put the browser logo for the one chosen ABOVE the list of profile names (and then at that point, no need to put `Mozilla Firefox - ` on each entry). Here's a bad mockup:
![image](https://user-images.githubusercontent.com/4733304/210408047-e13cf042-2689-4337-bf26-e34cc93e298c.png)

WDYT, @rebron?

**Comment by bsclifton** [comment]
For QA - it's available on 1.48.108 and newer 😄

**Comment by kjozwiak** [comment]
The above requires `1.47.165` or higher for `1.47.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using 
```
Brave | 1.47.165 Chromium: 109.0.5414.80 (Official Build) (64-bit)
-- | --
Revision | 0f69b168d36a06cace4365e9f029fa987afa5633-refs/branch-heads/5414@{#1178}
OS | Windows 11 Version 21H2 (Build 22000.1335)
```

1. Install 1.47.164 
2. launch Brave
3. click `Set Brave as default browser` button on `brave://welcome` page  
4. select `Mozilla Firefox` on `Import Settings` screen
5. click `Import`
6. click `Select All` 
7. click `Import profiles`
8. `Setup complete` screen displayed
9. click `Finish`

#### Confirmed correct profile names are shown as expected `Select profiles to import` screen

step 3|step 4-5|step 6-7|step 8|step 9
-----|-----|------|-----|-----
<img width="466" alt="image" src="https://user-images.githubusercontent.com/98358127/211121665-2ee2f234-6085-471f-8530-31fe912e765f.png">|<img width="466" alt="image" src="https://user-images.githubusercontent.com/98358127/211121658-c1f24725-87f8-47b6-b12c-43d50a19dcc6.png">|<img width="466" alt="image" src="https://user-images.githubusercontent.com/98358127/211121646-e769c2bf-f699-44e4-92de-12e75d0b72de.png">|<img width="466" alt="image" src="https://user-images.githubusercontent.com/98358127/211121627-9ae92423-0f64-4bfa-8ed8-edb715a19e9e.png">|<img width="466" alt="image" src="https://user-images.githubusercontent.com/98358127/211121619-b0709fa0-58df-441e-b269-dba32e0b1db7.png">|
