### ISSUE TITLE
Provide direct access to 'Add/Import asset' button on the NFT blankslate page

### ISSUE THREAD

**Issue by jenn-rhim** [brave/brave-browser#27567]
Try not to make users futile work and offer assistance on the spot. In this case, the button of adding should be right on this page.
cc: @jamesmudgett @minkyeongshin 

<img width="1523" alt="Screenshot 2022-12-29 at 8 50 22 AM" src="https://user-images.githubusercontent.com/4369856/209984252-403728dc-a208-489a-abb1-9f213937653d.png">

**Comment by HEagle18** [comment]
+1. this is now fixed in 1.49.

![Image](https://user-images.githubusercontent.com/12224304/220201588-11996749-8990-4a95-a25e-9575ef58e983.png)

**Comment by kjozwiak** [comment]
@jamesmudgett @srirambv is the above still a valid issue? If not, lets remove the `close/invalid` label. If it's fixed and not valid anymore. Lets remove it from the backlog and close it off 👍

**Comment by srirambv** [comment]
This is fixed as mentioned in https://github.com/brave/brave-browser/issues/27567#issuecomment-1437576591
