### ISSUE TITLE
not blocking any ads

### ISSUE THREAD

**Issue by y2ng** [brave/brave-browser#27563]
## Description 
browser is not blocking any ads on all website, try disabling and enabling shields, changing to aggresive level, still not working. It happend on a new installed stable version(1.46.144). First time installed on this PC(windows 10, 22H2), I even uninstalled it and downloaded standalone installer to install again, same result. 

I used Brave on the other PC about 2 months ago, shields works fine.

## Steps to Reproduce

   1. Just try the stable version 1.46.144
   

## Actual result:
![image](https://user-images.githubusercontent.com/20290832/209940704-038524eb-33f1-45ce-90ff-ed5cac96a0b0.png)
How could it happen? 0 ad is blocked.

## Expected result:
works better than uBlock Origin

## Reproduces how often: 
Always.

## Brave version (brave://version info)
1.46.144 Chromium: 108.0.5359.128 (正式版本) （64 位） 

## Version/Channel Information:
Stable V1.46.144

- Can you reproduce this issue with the current release?  Yes
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

![image](https://user-images.githubusercontent.com/20290832/209941509-423917be-4f89-4360-89ab-a4d70404f361.png)

**Comment by bsclifton** [comment]
@y2ng this can happen if there is trouble downloading the adblock list. Can you please visit brave://components/ and look for the one called `Brave Ad Block Updater`. There should be a button `Check for update` that you can click to force it to update

Let us know if that works 😄

**Comment by rebron** [comment]
cc: @ryanbr

**Comment by ryanbr** [comment]
Still happening ? @y2ng

**Comment by y2ng** [comment]
> @y2ng this can happen if there is trouble downloading the adblock list. Can you please visit brave://components/ and look for the one called `Brave Ad Block Updater`. There should be a button `Check for update` that you can click to force it to update
> 
> Let us know if that works 😄

after setting global proxy for system, updating works. Related resources might be blocked by gfwlist. Hope I don't need to proxy for browser update.
