### ISSUE TITLE
Skip unnecessary word(s) in the button text: Visible assets -> Add assets (or Import assets) 

### ISSUE THREAD

**Issue by jenn-rhim** [brave/brave-browser#27568]
The action of 'adding' implicitly indicating the user intention of wanting to display the asset. 'Visible' does not add anything in this particular task, but only confuses the user of the purpose of the button and makes it unclear about the CTA.
@kleantzogu cc @jamesmudgett 
<img width="1523" alt="Screenshot 2022-12-29 at 8 42 12 AM" src="https://user-images.githubusercontent.com/4369856/209984892-0b715297-1b14-46d9-802b-c4b922c6c3d8.png">

**Comment by josheleonard** [comment]
@kleantzogu can we close this one?

**Comment by kleantzogu** [comment]
@josheleonard This is fixed on the Wallet 2.0 design.
