### ISSUE TITLE
`Mozilla Firefox` should read `Firefox Browser`, with updated logo, on v2 onboarding import screen

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#27562]
## Description 

`Mozilla Firefox` should read `Firefox Browser`, with updated logo, on v2 onboarding import screen

## Steps to Reproduce

   1. install the latest version of `Firefox Browser` (`108.x`)
   2. launch it, browse, and bookmark a site or two
   3. install `Brave` `1.47.51`
   4. launch `Brave`
   5. click `Skip` on the 1st onboarding screen
   6. on the next, note the `Mozilla Firefox` logo and name

## Actual result:

`Actual` | `Expected (minus the wrong orientation)`
---------|------------
<img width="158" alt="Screen Shot 2022-12-28 at 11 32 11 PM" src="https://user-images.githubusercontent.com/387249/209923718-370f9128-8f66-4a96-bffb-624dc3744fea.png"> | <img width="286" alt="Screen Shot 2022-12-28 at 11 32 28 PM" src="https://user-images.githubusercontent.com/387249/209923719-0e68e856-122a-4eae-a4bb-f4f45dbd09e2.png">

Correct name `Firefox Browser` (per Mozilla's own [Firefox logo-usage guidelines](https://mozilla.design/firefox/#logos-usage)) with updated logo

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.47.151 Chromium: 109.0.5414.46 (Official Build) beta (x86_64)
-- | --
Revision | 6e36b77363ef3febbe792af680fa1367993ddcf0-refs/branch-heads/5414@{#709}
OS | macOS Version 11.7.2 (Build 20G1020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

/cc @rebron @nullhook @spylogsster @aguscruiz @martin-c0des

**Comment by aguscruiz** [comment]
Updated logo here: 
https://www.figma.com/file/MFHpcXJMg2RUQpUJMAZZ4R/Desktop-Onboarding?node-id=5336%3A130882&t=lzg0zHNrVc4PMdkb-1

Also all the other browser logos are now .svg if we want to replace those bitmaps.

**Comment by jenn-rhim** [comment]
@nullhook please update this ^

**Comment by kjozwiak** [comment]
Just a heads up for @brave/qa-team, as per https://github.com/brave/brave-core/pull/16525#issue-1519029054, we're not changing the name/string. Just the logo.

**Comment by kjozwiak** [comment]
The above requires `1.48.151` or higher for `1.48.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.48.152 Chromium: 109.0.5414.119 (Official Build) beta (64-bit)
-- | --
Revision | 772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}
OS | Windows 11 Version 21H2 (Build 22000.1455)
```

- Install 1.48.152
- launch Brave
- click `Skip`
- verify `Import Settings` screen

 #### Confirmed just the `Mozilla Firefox` logo is updated as per the Figma designs and no text has been updated. 

<img width="462" alt="image" src="https://user-images.githubusercontent.com/98358127/216098552-9f9ba6e5-6c39-4b6a-a033-3032f02d03c3.png">

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.48.152 Chromium: 109.0.5414.119 (Official Build) beta (x86_64)
-- | --
Revision | 772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}
OS | macOS Version 11.7.3 (Build 20G1116)

### Steps:
1. new profile
2. launched Brave
3. clicked `Skip`

#### Confirmed the correct Firefox logo, without any text changes

<img width="1312" alt="Screen Shot 2023-02-01 at 11 02 59 AM" src="https://user-images.githubusercontent.com/387249/216139309-4d5ba330-fa82-4cd2-a1d6-6e85a71a5a77.png">

**Comment by LaurenWags** [comment]
Removed `QA/Test-All-Platforms` label per discussion with @kjozwiak @rebron
