### ISSUE TITLE
`Mozilla Firefox` importer in new onboarding skips one (1) profile, in a multi-profile import

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#27561]
## Description 

`Mozilla Firefox` importer in new onboarding skips one (1) profile, in a multi-profile import

## Steps to Reproduce

Prerequisites:
* install Firefox `108.0.1 (64-bit)`
* create and configure 4 distinct profiles

1. install `1.47.151`
2. launch Brave
3. click `Skip` on the 1st onboarding screen
4. at the `Import Settings` screen, select `Mozilla Firefox`

## Actual result:

<img width="1453" alt="Screen Shot 2022-12-28 at 11 25 50 PM" src="https://user-images.githubusercontent.com/387249/209918598-ef5b06ec-9d43-4053-8054-adbceec38076.png">

## Expected result:

I'd expect it to import and list all 4 `Mozilla Firefox` profiles

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.47.151 Chromium: 109.0.5414.46 (Official Build) beta (x86_64)
-- | --
Revision | 6e36b77363ef3febbe792af680fa1367993ddcf0-refs/branch-heads/5414@{#709}
OS | macOS Version 11.7.2 (Build 20G1020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Unknown`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

/cc @rebron @nullhook @spylogsster  @brave/qa-team

**Comment by stephendonner** [comment]
I *think* what might be special about the missed/skipped `Mozilla Firefox` profile is that it's "empty," although it clearly has an entry in `Firefox's` `Profile Manager`...

I was following these steps from `Case 3: Set Brave as default and import from multiple browsers with multiple profiles - Select individually` in `https://github.com/brave/brave-browser/issues/26378`:

> Create 4 Firefox profiles:
Profile 1: Bookmarks, Extensions, Saved passwords
Profile 2: Bookmarks, Extensions
Profile 3: Bookmarks
Profile 4: No data

I believe it's the latter - `Profile 4: No data` that doesn't get marked, somehow, as "dirty" i.e. written to, but again, it shows up in Firefox's own `Profile Manager`, so 🤷

**Comment by MadhaviSeelam** [comment]
@stephendonner couldn't reproduce in `Win 11 x64`.  All four Firefox profiles are shown. 
```
Brave | 1.47.151 Chromium: 109.0.5414.46 (Official Build) beta (64-bit)
-- | --
Revision | 6e36b77363ef3febbe792af680fa1367993ddcf0-refs/branch-heads/5414@{#709}
OS | Windows 11 Version 21H2 (Build 22000.1335)
```

<img width="811" alt="image" src="https://user-images.githubusercontent.com/98358127/209975782-6e07e8b4-36a1-4c01-ab58-db1e3564aef6.png">

**Comment by spylogsster** [comment]
@stephendonner cannot reproduce on my side, pay attention profiles will be shown in the import list if it was launched in the Firefox at least once. if it is still reproduced on your side pls make sure you have launched profiles from about:profiles page, they will initialize profiles.
