### ISSUE TITLE
Update Header "background video playback" setting copy

### ISSUE THREAD

**Issue by sujitacharya2005** [brave/brave-browser#27574]
## Description 
https://github.com/brave/brave-browser/issues/26516

As per discussion
 https://bravesoftware.slack.com/archives/C0816QH3R/p1672425493939739?thread_ts=1672349691.515339&cid=C0816QH3R
Update

**HEADER** :   Background play
**Description** :  Allows audio to play when you switch to another tab in Brave or another app or your device screen is off.

## Steps to reproduce 

   1. 
   2. 
   3. 

## Actual result 
**Header**: Background video playback

## Expected result
**Header**: Background media playback

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21 5G` using version 

```
Brave	1.49.117 Chromium: 111.0.5563.50 (Official Build) (64-bit) 
Revision	39f3dfc5023fe60997adc4f6cf5439cfa3e6968a-refs/branch-heads/5563@{#903}
OS	Android 13; Build/TP1A.220624.014
```
- Ensured header copy is updated and displays `Background play`
- Ensured feature description copy is updated with above https://github.com/brave/brave-browser/issues/27574#issue-1514178812
- Ensured background play works when playing videos

Example | Example
-|-
![screenshot-1677774595480](https://user-images.githubusercontent.com/17885425/222492647-3e00c4f8-0c22-4721-8b51-6b19636cdf3d.png) | ![screenshot-1677774621504](https://user-images.githubusercontent.com/17885425/222492656-6c7b5a4d-07fd-497a-bfc2-4133de83b63f.png)
