### ISSUE TITLE
[Speedreader] Failed to parse schema from @context in json+ld script.

### ISSUE THREAD

**Issue by boocmp** [brave/brave-browser#27576]
## Steps to Reproduce

Open https://www.theverge.com/2022/12/28/23529705/amazon-drone-delivery-prime-air-california-texas in reader mode.

## Actual result:

No publishing date in the article header.

## Expected result:

Date displayed if it is presented in json+ld.

## Reproduces how often: 

Easy 100%.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.49.88 Chromium: 110.0.5481.77 (Official Build) beta (x86_64)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | macOS Version 11.7.3 (Build 20G1116)

(Reproduced in `1.48.157`

#### Confirmed the date shows up now in `1.49.88`, where it didn't before

`1.48.157` | `1.49.88`
---------|---------
<img width="1312" alt="Screen Shot 2023-02-07 at 1 07 42 AM" src="https://user-images.githubusercontent.com/387249/217201079-19536204-3ba3-4e77-a3b2-7e9fb6c9bcf6.png"> | <img width="1312" alt="Screen Shot 2023-02-07 at 1 08 49 AM" src="https://user-images.githubusercontent.com/387249/217201081-8984ae61-4360-449a-8128-5de3e9037700.png">
