### ISSUE TITLE
searching via settings causes "Uncaught Error: Assertion failed: An associated control was expected for SETTINGS-SUBPAGE Manage sync, but was not found." and spinner doesn't stop animating

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#2757]
## Description 
Search `Sync` text doesn't find sync section in Chrome://settings page 

## Steps to Reproduce

   1. Go to `Chrome://settings` page
   2. Search a string 'Sync' or 'sync' 
   3. Finds the sync section only for the first time ( Observe that the finder icon keeps rotating even after search found)
  4. Search a string 'Sync' or 'sync' again
   

## Actual result:
Doesn't find the matching string, Finder icon keeps rotating but it never finds the sync section.

![find sync string- issue](https://user-images.githubusercontent.com/38657976/50535109-51e75780-0b6c-11e9-88b3-e85a3e05f19e.gif)
Console log error:

[5660:1840:1229/132354.759:ERROR:CONSOLE(8)] "Uncaught Error: Assertion failed: An associated control was expected for SETTINGS-SUBPAGE Manage sync, but was not found.", source: chrome://settings/crisper.js (8)
![image](https://user-images.githubusercontent.com/38657976/50535196-89a2cf00-0b6d-11e9-8e29-8f778c4e132a.png)

## Expected result:
Should find the sync section everytime, finder icon should stop after it found search string

## Brave version (brave://version info)

Brave | 0.59.13 Chromium: 72.0.3626.28 (Official Build) beta (64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Windows

### Reproducible on current release: na
- Does it reproduce on brave-browser dev/beta builds? yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? na
- Is the issue reproducible on the latest version of Chrome? na

### Additional Information
@brave/legacy_qa

**Comment by LaurenWags** [comment]
Reproduces on macOS

Brave | 0.59.14 Chromium: 72.0.3626.28 (Official Build) beta(64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Mac OS X

**Comment by btlechowski** [comment]
Reproduces on Ubuntu 17.10

Brave | 0.59.14 Chromium: 72.0.3626.28 (Official Build) beta(64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Linux

**Comment by srirambv** [comment]
@kjozwiak reproduced the same error on console and the spinner when search is done on Linux build as well
![sync](https://user-images.githubusercontent.com/17010094/50676290-96b23900-1019-11e9-8a41-bac92a6f0212.gif)

**Comment by kjozwiak** [comment]
@srirambv do you see the spinner happening when searching for other words like `bookmark` and `password`?

**Comment by srirambv** [comment]
Yes for any search term the spinner shows up

**Comment by LaurenWags** [comment]
Yes, I see the same @kjozwiak

**Comment by GeetaSarvadnya** [comment]
@kjozwiak Tested again for any serach i am seeing the spinner. Getting assertion failed message in console.

**Comment by kjozwiak** [comment]
> changing to feature/settings as this seems more like a settings bug and not specific to sync. please change back if I'm wrong.

Agreed, might have been caused by adding `Sync` into the settings but affecting all of `brave://settings`. I moved it from the `Sync` project to the `General` project board. We should get this fixed for `0.59.x` as it's a new regression. CCing @rebron

**Comment by btlechowski** [comment]
Still reproducible:

Brave | 0.62.16 Chromium: 73.0.3683.39 (Official Build) dev (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

**Comment by GeetaSarvadnya** [comment]
Unable to reproduce, verified on below versions:

`0.63.48` - Not Reproducible
`0.65.74` - Not Reproducible
`0.66.24` - Not Reproducible
`0.64.60` - Not Reproducible
