### ISSUE TITLE
'Lock Wallet' -- > 'Lock wallet'

### ISSUE THREAD

**Issue by jenn-rhim** [brave/brave-browser#27571]
Should be lower case 'wallet' as it's referring to general wallet, not proper name of the product. 

@kleantzogu @jamesmudgett

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.49.91 Chromium: 110.0.5481.77 (Official Build) beta (64-bit) 
-- | --
Revision | `65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}`
OS | Linux

- Verified steps from [brave/brave-core#16649](https://github.com/brave/brave-core/pull/16649)
- Verified `Lock Wallet` is now `Lock wallet`
- Verified text change on both portfolio and panel

Portfolio | Panel
-- | --
![image](https://user-images.githubusercontent.com/17010094/218457532-d9e1010d-f485-4138-af40-7459b38c3185.png) | ![image](https://user-images.githubusercontent.com/17010094/218457575-57cc91e1-a3ec-4f8e-8a3b-ec9ad0daf1c0.png)

---------------------

Verification passed on 

Brave | 1.49.91 Chromium: 110.0.5481.77 (Official Build) beta (64-bit)
-- | --
Revision | `65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#16649](https://github.com/brave/brave-core/pull/16649)
- Verified `Lock Wallet` is now `Lock wallet`
- Verified text change on both portfolio and panel

Portfolio | Panel
-- | --
![image](https://user-images.githubusercontent.com/17010094/218456913-ace1ac54-dec6-4f52-8df8-4de5a7b2f889.png) | ![image](https://user-images.githubusercontent.com/17010094/218456976-56a44b48-edc8-4a2c-b387-e5b31a9c527f.png)

---------------------

Verification passed on 

Brave | 1.49.91 Chromium: 110.0.5481.77 (Official Build) beta (arm64)
-- | --
Revision | `65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#16649](https://github.com/brave/brave-core/pull/16649)
- Verified `Lock Wallet` is now `Lock wallet`
- Verified text change on both portfolio and panel

Portfolio | Panel
-- | --
![image](https://user-images.githubusercontent.com/17010094/218460971-d2c82ee4-0050-4b1d-90b5-661ce512ce40.png) | ![image](https://user-images.githubusercontent.com/17010094/218461013-cbf7ac0d-c3c1-4487-a884-7a5b4d084b3f.png)
