### ISSUE TITLE
Update default for BraveEnableAutoTranslate in the code

### ISSUE THREAD

**Issue by atuchin-m** [brave/brave-browser#27577]
The feature `BraveEnableAutoTranslate` should be disabled by default (the same as in Griffin).

Griffin issue: https://github.com/brave/brave-variations/issues/480 (The steps to verify can be found here)

**Comment by kjozwiak** [comment]
The above requires `1.47.171` or higher for `1.47.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.47.171 Chromium: 109.0.5414.87 (Official Build) (64-bit)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | Windows 10 Version 21H2 (Build 19044.2486)

```
**`Prerequisite:`** ensure that you don't relaunch the browser and pull `BraveAutoTranslateStudy:AutoTranslateDisabled` when verifying the above. Basically need to makes sure that the browser isn't restarted after first launch so it doesn't pull and apply the `seed` file from Griffin. This way, you know you're QAing the change from `b-c`.

* ensured that `Always translate [language]` isn't visible under the `hamburger menu` via `Brave Translate`
* ensured that `Always translate [language]` never appears under the languages being detected after translating several sites
* ensured that Brave Translate appears within the omnibox when it detects a supported locale that it can translate
* ensured that you can translate several websites without any issues (mostly checked on Wikipedia and tried a few randoms)
* ensured that the `auto translate` feature is still disabled once you've restarted the browser and pulled `BraveAutoTranslateStudy:AutoTranslateDisabled` 

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------|----------------|---------------
![image](https://user-images.githubusercontent.com/38657976/212108274-d162584e-af0c-4946-a3a2-c51173ef93b3.png) | ![image](https://user-images.githubusercontent.com/38657976/212108507-e9fa9719-c60a-4317-8318-26e2069fe31c.png) | ![image](https://user-images.githubusercontent.com/38657976/212108769-b8938689-f7f6-46e7-85ac-09f735787d9e.png) | ![image](https://user-images.githubusercontent.com/38657976/212109047-34a71499-d000-41b6-ae07-b7013e4d4d4c.png) | ![image](https://user-images.githubusercontent.com/38657976/212110853-cba2ee56-9209-4584-9cd2-575e16259bf9.png)



Traslated few languages successfully:

Example | Example | Example | Example
----------|-----------|----------|---------
![image](https://user-images.githubusercontent.com/38657976/212109751-64e90d7b-6487-48b2-985a-b68c764c01fa.png) | ![image](https://user-images.githubusercontent.com/38657976/212110063-04744292-99f7-469b-bb3d-83255c0b8f9a.png) | ![image](https://user-images.githubusercontent.com/38657976/212110346-7b72c768-424b-48d7-a2a7-21e8aeeffa6e.png) | ![image](https://user-images.githubusercontent.com/38657976/212110551-c70ed5aa-0517-4c8c-963a-53c14a74646c.png)

**Comment by Uni-verse** [comment]
In progress on Android ARM using version: 

```
Brave	1.47.171 Chromium: 109.0.5414.87 (Official Build) (64-bit) 
Revision	2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS	Android 13; Build/TP1A.220624.014
```
