### ISSUE TITLE
Brave eating up my CPU

### ISSUE THREAD

**Issue by saintmalik** [brave/brave-browser#27582]
## Description 

Brave been making my laptop hand for a long time, checking the activity monitor and brave taps been eating it up, i wasn’t watching video or listening to audios.

## Steps to Reproduce

   1. 
   2. 
   3. 

## Actual result:

![Screenshot 2022-12-30 at 4 51 52 PM](https://user-images.githubusercontent.com/37118134/210090933-568a1be2-4547-4a85-bfbe-793413e067b6.jpg)

## Brave version (brave://version info)

Brave | 1.45.127 Chromium: 107.0.5304.110 (Official Build) (x86_64)
-- | --
Revision | 2a558545ab7e6fb8177002bf44d4fc1717cb2998-refs/branch-heads/5304@{#1202}
OS | macOS Version 13.0.1 (Build 22A400)
JavaScript | V8 10.7.193.22

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Not sure

**Comment by rebron** [comment]
Hi @saintmalik Can you update to 1.46.144 and let us know if you're still having this issue.

**Comment by saintmalik** [comment]
Thanks, looks better now
