### ISSUE TITLE
Brave sync is not renamed to Sync on Linux platform

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#2758]
## Description 
Brave sync is not renamed to Sync in the following places:

1.  Hamburger menu
2. brave://settings sidebar menu
3.  brave://settings -Brave sync section

## Steps to Reproduce

   1. Clean profile 0.59.13
 
## Actual result:

Hamburger menu:

![image](https://user-images.githubusercontent.com/38657976/50535578-8f021880-0b71-11e9-9428-c66403dd5263.png)

Brave://settings sidebar:

![image](https://user-images.githubusercontent.com/38657976/50536929-f32bd900-0b7f-11e9-8896-e16c40966d43.png)

Brave://settings ->Brave sync section

![image](https://user-images.githubusercontent.com/38657976/50536940-0ccd2080-0b80-11e9-9a71-cd3849578742.png)

## Expected result:
Brave Sync should be renamed to Sync

## Reproduces how often: 
Always

## Brave version (brave://version info)
Brave	0.59.13 Chromium: 72.0.3626.28 (Official Build) beta (64-bit)
Revision	997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS	Linux

### Reproducible on current release:na
- Does it reproduce on brave-browser dev/beta builds? yes

### Website problems only:  na
- Does the issue resolve itself when disabling Brave Shields? na
- Is the issue reproducible on the latest version of Chrome? na

### Additional Information
@brave/legacy_qa

**Comment by GeetaSarvadnya** [comment]
Even in `brave://settings` sidebar it shows `Brave Sync` on Linux 

![image](https://user-images.githubusercontent.com/38657976/50536721-57996900-0b7d-11e9-9a2c-920e118d7ab0.png)

**Comment by LaurenWags** [comment]
Does not reproduce on macOS using the below build

Brave | 0.59.14 Chromium: 72.0.3626.28 (Official Build) beta(64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Mac OS X

![screen shot 2019-01-02 at 1 32 09 pm](https://user-images.githubusercontent.com/28145373/50606346-6a6cb000-0e93-11e9-925b-400e940a577d.png)

**Comment by btlechowski** [comment]
Does not reproduce on Ubuntu 17.10 with the new build

Brave | 0.59.14 Chromium: 72.0.3626.28 (Official Build) beta(64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Linux

![image](https://user-images.githubusercontent.com/34715963/50618469-332deb80-0ef3-11e9-9916-269d6055a715.png)

**Comment by srirambv** [comment]
I can reproduce this issue on my Linux machine(Not VM) running `Ubuntu 18.04.1`

**Comment by srirambv** [comment]
here's the recording on  a clean profile https://youtu.be/04K6JYI9Y2E

**Comment by kjozwiak** [comment]
Seeing the same thing under `Mint 18.3 x64 VM` using the following build:

Brave | 0.59.18 Chromium: 72.0.3626.28 (Official Build) beta (64-bit)
--- | ----
Revision| 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Linux

Examples:

<img width="285" alt="screen shot 2019-01-04 at 1 42 44 am" src="https://user-images.githubusercontent.com/2602313/50676433-4fe52480-0fc2-11e9-988d-7cdf9c8a2435.png">

<img width="760" alt="screen shot 2019-01-04 at 1 43 00 am" src="https://user-images.githubusercontent.com/2602313/50676437-54a9d880-0fc2-11e9-88f9-cafcc5b2f737.png">

<img width="222" alt="screen shot 2019-01-04 at 1 43 08 am" src="https://user-images.githubusercontent.com/2602313/50676440-583d5f80-0fc2-11e9-8510-b6348beea58e.png">

**Comment by AlexeyBarabash** [comment]
Don't see it in 


Brave | 0.59.35 Chromium: 72.0.3626.81 (Official Build) (64-bit)
-- | --
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS | Linux



![image](https://user-images.githubusercontent.com/24739341/52712497-71f89c00-2f9d-11e9-9efc-48a5e9822c8d.png)

**Comment by kjozwiak** [comment]
Thanks for double checking @AlexeyBarabash 👍 I checked `Ubuntu 18.04 x64 VM` and `Mint 19.1 x64 VM` and I'm also seeing `Sync` instead of `Brave Sync`. Checked the following:

* checked the hamburger menu and ensured it appeared as `Sync`
* checked `brave://settings` and ensured that the sidebar appeared as `Sync`
* checked `brave://settings` and the sync section is titled as `Sync`

Example:

<img width="1076" alt="screen shot 2019-02-13 at 2 03 57 pm" src="https://user-images.githubusercontent.com/2602313/52736618-40c99d00-2f98-11e9-9fd5-6d71d95fad88.png">

@GeetaSarvadnya mind checking to see if it's working for you now?

**Comment by GeetaSarvadnya** [comment]
The issue is fixed and working fine. Verified on below version Linux mint - '0.63.48` and `0.64.62`

![image](https://user-images.githubusercontent.com/38657976/56756517-8d5b0100-67af-11e9-87d5-4e21dc6669de.png)
