### ISSUE TITLE
excessive use of battery power in macos

### ISSUE THREAD

**Issue by oky2abbas** [brave/brave-browser#2759]
Hi, Brave uses the battery power of my laptop too much, **please optimize this.**

macOS : 10.14.2
Brave : Version 0.58.18 Chromium: 71.0.3578.98 (Official Build) (64-bit)

**Attached image show the amount of battery usage for 1 hour of brave.**.
https://imgur.com/a/6BmSq40
<img src="https://i.imgur.com/5I78eH0.png">

**Comment by ashrafhadden** [comment]
Without knowing what `Energy Impact` and `Avg Energy Impact` are actually measuring it's hard to say what is "too much". It might just be that all web browsers have this same typical energy usage, and it would vary largely depending on what you're doing with the browser. Browsing news sites as opposed to watching videos would likely give drastically different results. To accurately measure energy usage would require a variety of strict benchmarks where you're doing the exact same activity on multiple browsers over multiple intervals of time for comparison. This could be done. For example loading up CNN.com on Safari, Chrome, Firefox and Brave. Measuring `Energy Impact` and `Avg Energy Impact` at 0, 10, and 60 seconds.

**Comment by matthewreimer** [comment]
I think the reason Brave hits the battery so hard is that something is causing the high performance graphics card to be turned on and is keeping it on.

![image](https://user-images.githubusercontent.com/8042028/55348142-5bce6e80-546b-11e9-8fbe-10d16f91709a.png)

**Comment by mbedded** [comment]
Maybe it's related to #4858. I have the issue that my setup (VS Code + Brave) lasts 2-3 hours starting with 100% battery. Same setup with Safari instead of Brave can be used much longer (78 hours). No heavy CPU things were done in both cases like compiling stuff or rendering.

**Comment by oky2abbas** [comment]
After a long time I reinstalled Brave.
Version 1.5 optimizes and performs **better than other brave browsers (like Firefox, Google Chrome, etc.).**

It is actually very optimized and performs exceptionally well. (`good job`)

**thanks @)***

**Comment by rebron** [comment]
Closing per last comment. Thanks for trying again @oky2abbas
