### ISSUE TITLE
importing from multiple profiles dumps all of the data into the default profile within brave

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#27591]
## Description 

When running through https://github.com/brave/brave-core/pull/16472#issuecomment-1367605702, I noticed that we're importing all the data/extensions into a single profile even though the user might import multiple profiles. We should look into keeping the same user/profile structure when users are importing data from chromium based browsers (not sure if this is possible with Firefox).

![210018042-1bf060ab-db39-4ee4-a6ac-edd2f9e2b3d5](https://user-images.githubusercontent.com/2602313/210110736-a7133deb-c7d1-4986-bd3f-ef6c51a68177.png)

For example, in the above case, we should attempt to create a new profile within Brave named `ExtentionTesting` and import all the data into that profile rather than importing it into a single default profile like we do now.

**Updates from Slack**:
- if user is on default profile, and user imports only 1 profile, we should import everyting from profile X into that default profile in Brave, otherwise if multiple profiles selected we create new profiles.
- We apply a randomized avatar index to created profiles

## Steps to Reproduce

   1. import data from a Chromium browser that has multiple profile and notice everything gets dumped into the default profile

## Actual result:

Currently importing data from multiple profiles from other chromium browsers and dumping everything into the default profile.

## Expected result:

We should attempt to keep the same structure and create profiles and then import the data into the correct profiles.

## Reproduces how often: 

100% reproducible using the STR/Cases mentioned above.

## Brave version (brave://version info)

```
Brave | 1.48.97 Chromium: 109.0.5414.46 (Official Build) nightly (64-bit)
-- | --
Revision | 6e36b77363ef3febbe792af680fa1367993ddcf0-refs/branch-heads/5414@{#709}
OS | Windows 11 Version 22H2 (Build 22621.963)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.49.89 Chromium: 110.0.5481.77 (Official Build) beta (64-bit)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | Windows 11 Version 21H2 (Build 22000.1455)
```
Pre-requisites:  
<details>
Download Chrome and create 3 profiles with bookmarks, history and extensions

Person 1|Person 2|Person 3
---|---|---
<img width="483" alt="image" src="https://user-images.githubusercontent.com/98358127/217968765-3a43067c-a358-4321-9c20-e939289816df.png">|<img width="490" alt="image" src="https://user-images.githubusercontent.com/98358127/217969143-ddb4e50e-9ed9-401e-ba3e-426046d4c6bf.png">|<img width="483" alt="image" src="https://user-images.githubusercontent.com/98358127/217969460-96b57d7c-6c31-4c67-a2fb-bc19e1a5c007.png">
</details>

#### Case 1: Single profile from Chrome 
<details>
1. Install 1.49.89
2. launch Brave
3. click `Set Brave as default browser
4. select Chrome
5. click import
6. select `Chrome Person 1, 2 & 5
7. click Import Profiles
8. click Finish
9. click on Profile icon in the new-tab page next to hamburger menu





</details>

#### Case 2: Multiple profiles from Chrome 
<details>

1. new profile 
2. launch Brave
3. click `Set Brave as default browser
4. select Chrome
5. click import
6. select `Chrome Person 1, 2 & 5
7. click Import Profiles
8. click Finish
9. click on Profile icon in the new-tab page next to hamburger menu

#### Confirmed three newly created profiles are shown in the profile manager
#### Confirmed data correctly imported into separate profiles `Chrome Person 1`, Chrome Person 2 & Empty profile from `Chrome Person 5`
#### Confirmed bookmarks, history, and extensions are imported into Chrome Person 1
#### Confirmed bookmarks, history and extensions  are shown in Yandex Cloud profile
#### Confirmed empty profile imported from `Chrome Person 5`

step 3|step 4|step 6|step 8|step 9|result|result
-----|----|-----|-----|-----|-----|------
<img width="460" alt="image" src="https://user-images.githubusercontent.com/98358127/217969724-c762b77c-654b-4529-a140-06bd2724a807.png">|<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/217969581-72276da1-5b3d-4a93-b5c5-3d73f4e42f96.png">|<img width="458" alt="image" src="https://user-images.githubusercontent.com/98358127/217969832-ade63642-d9d1-44b1-a4ca-a99ee20e1666.png">|<img width="467" alt="image" src="https://user-images.githubusercontent.com/98358127/217967567-eab7787d-d935-450f-ba63-97217d656ed9.png">|<img width="454" alt="image" src="https://user-images.githubusercontent.com/98358127/217970033-9fbab2ca-2151-45b2-a56c-53a97b719783.png">|<img width="460" alt="image" src="https://user-images.githubusercontent.com/98358127/217970240-e0565474-3972-4647-b09f-55281769a5ea.png">|<img width="458" alt="image" src="https://user-images.githubusercontent.com/98358127/217970293-db9ca2eb-f6c2-4c69-acdf-a55ea5476baf.png">|<img width="451" alt="image" src="https://user-images.githubusercontent.com/98358127/217970377-226e56a1-ea8f-475d-a82c-c5db77c58279.png">
</details>

Note:  Additional browser testing (Yandex Browser) tested via https://github.com/brave/brave-browser/issues/27760

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.49.116 Chromium: 110.0.5481.177 (Official Build) beta (64-bit)
-- | --
Revision | f34f7ab2d4ca4ad498ef42aeba4f4eb2c1392d63-refs/branch-heads/5481@{#1239}
OS | Linux
```
TestCase 1: Import from Chrome

Pre-requisites:  
<details>

Download Chrome and create 3 profiles 

- Person 1: bookmarks, history, extensions, passwords and cookies
- Person 2: bookmarks, history, passwords
- Person 3: no data: No data

Person 1|Person 2|Person 3
------ | ------ | --------
<image width="400" alt="image" src="https://user-images.githubusercontent.com/98358127/222309652-d77af0a0-c13b-40c8-92d7-c98211335f8f.png"> | <image width="400" alt="image" src="https://user-images.githubusercontent.com/98358127/222309705-038ef93a-ab6f-4443-a106-6a20c451f89a.png"> | <image width="400" alt="image" src="https://user-images.githubusercontent.com/98358127/222309684-f02c01b5-5e8b-4011-bb0e-baf6d0902cfb.png">

Download Yandex: and create 2 profiles 
User 1 | Car
------ | ---------
<image width="400" alt="image" src="https://user-images.githubusercontent.com/98358127/222309470-2e47a463-d1c6-490c-9d1a-6deba41bc727.png">|<image width="400" alt="image" src="https://user-images.githubusercontent.com/98358127/222309566-06063da8-f161-44b4-941b-9741c4006559.png">


### Case 1: Single profile from Chrome 
<details>

1. Install 1.49.116
2. launch Brave
3. click `Set Brave as default browser
4. select Chrome
5. click import
6. select `Chrome Person 1`
7. click Import Profiles
8. click Finish

#### Confirmed importing from only one source profile, i.e. Chrome Profile 1, no new Brave profile is created 
#### Confirmed  bookmarks, history, extensions and passwords  are imported into default profile
#### Confirmed bookmarks are shown on the bookmarks bar and bookmarks sidepanel in a new-tab

Note: no cookies are imported

step 3 | step 4 | step 6 | step 8 | step 9 | new-tab| bookmarks| extensions| history| passwords |cookies
------- | ------- | ------- | ------- | ------- | -------- | -------- |------ | ------- | --------
![image](https://user-images.githubusercontent.com/98358127/222308282-9ae5e2be-a5bb-4597-b0ad-6b97dc6a96ce.png)
![Screenshot from 2023-03-02 08-00-40](https://user-images.githubusercontent.com/98358127/222466752-c9f6e799-22ad-437b-abb6-dae587abcaac.png)
![Screenshot from 2023-03-02 08-00-19](https://user-images.githubusercontent.com/98358127/222466889-570f8b44-e775-4138-b864-a31f0d0435cb.png)
![Screenshot from 2023-03-02 08-00-29](https://user-images.githubusercontent.com/98358127/222466814-9c375b1d-f74b-42a4-9fc6-26e566792904.png)
![Screenshot from 2023-03-02 08-01-34](https://user-images.githubusercontent.com/98358127/222466694-96cc9d2e-9a81-40fe-ad39-3866b89366bf.png)
![Screenshot from 2023-03-02 08-01-47](https://user-images.githubusercontent.com/98358127/222466608-d3f1ec4d-f025-463e-9c63-8398036a5a45.png)
![Screenshot from 2023-03-02 08-02-06](https://user-images.githubusercontent.com/98358127/222466568-e3d83f3e-9ec8-4050-8832-86ae6f6493df.png)
![Screenshot from 2023-03-02 08-02-16](https://user-images.githubusercontent.com/98358127/222466508-5f9fa268-6a56-42b0-b20b-f70ddbf11184.png)
![Screenshot from 2023-03-02 08-02-38](https://user-images.githubusercontent.com/98358127/222466444-85ee620e-de6e-4cea-a6eb-c56aa3167aca.png)
![image](https://user-images.githubusercontent.com/98358127/222466210-0b0b80ea-3483-4bdc-80ba-58aeec05c9a9.png)

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.49.118 Chromium: 111.0.5563.50 (Official Build) (x86_64)
-- | --
Revision | 39f3dfc5023fe60997adc4f6cf5439cfa3e6968a-refs/branch-heads/5563@{#903}
OS | macOS Version 12.6.3 (Build 21G419)
```
