### ISSUE TITLE
Change remote welcome page into a local webui welcome page

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#276]

**Comment by bbondy** [comment]
QA notes:
Please completely test the welcome page in this issue.

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | -- 
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Linux

* Verified first launch showed `chrome://welcome`
* Verified manually typing `chrome://welcome` loads the welcome page
* Verified `Skip welcome tour` loads `chrome://newtab` but doesnt retain the URL
* Verified clicking on `Lets Go` opens the next screen
* Verified `Enable Rewards` opens up `chrome://rewards` on the same tab
* Verified `Import No` opens up `chrome://settings/ImportData` in a new tab
* Verified clicking on `Preferences`  loads `chrome://settings` on the same tab
* Verified clicking `Done` loads `chrome://newtab` without the URL and focus is set to the URL bar
