### ISSUE TITLE
[hackerone] brave today url opening issue

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#27602]
credit: [nishimunea](https://hackerone.com/nishimunea)
https://hackerone.com/reports/1819668

**Comment by kjozwiak** [comment]
@brave/qa-team please post verification notes within the internal issue.

**Comment by kjozwiak** [comment]
The above requires `1.47.168` or higher for `1.47.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.47.168 Chromium: 109.0.5414.87 (Official Build) (x86_64)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | macOS Version 12.6.2 (Build 21G320)
```

See verification notes under https://github.com/brave/internal/issues/987#issuecomment-1377391238

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.47.168 Chromium: 109.0.5414.87 (Official Build) (64-bit)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | Ubuntu 18.04 LTS

Verification in https://github.com/brave/internal/issues/987#issuecomment-1377538050
