### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by satilpereira** [brave/brave-browser#27601]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.46.144  Chromium: 108.0.5359.128
Operating System: Linux 5.15.0-56-generic

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Ocasionally when downloading files
2. Just opened the drive
3. Downloaded a .svg file
4. Browser crashes
5. I can't interact with the browser with my mouse or keyboard, but when i tried to close the window via the ubuntu/GNOME GUI it will pop the dialout saying, "Close all tabs?" and/or if some player is playing, it will keep the reproduction.
6. have to kill the browser process and open it again, and i can use it again

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/ae380400-8f9e-6209-0000-000000000000

**Comment by jafamo** [comment]
I have the same problem, the browser chrases when download any file 
My version[Versión 1.46.144 Chromium: 108.0.5359.128 (Build oficial) (64 bits)](https://brave.com/latest/)
Operating System : 5.15.0-56-generic #62-Ubuntu

I have the same problem with google-chrome
