### ISSUE TITLE
Make sure default account names on wallet are shown in full

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#27612]
## Description 

Right now, parts of the account name on the panel are not shown. We should change the default limit to show the full account name. 
<img width="418" alt="Screenshot 2023-01-03 at 01 12 37" src="https://user-images.githubusercontent.com/12224304/210287232-88981ad1-059c-4bf8-9d36-225811aa7e92.png">

## Steps to Reproduce

   1. 
   2. 
   3. 

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.48.132 Chromium: 109.0.5414.87 (Official Build) beta (64-bit) 
-- | --
Revision | `2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}`
OS | Linux

- Verified steps from [brave/brave-core#16515](https://github.com/brave/brave-core/pull/16515)
- Verified default account names are shown in full
![image](https://user-images.githubusercontent.com/17010094/214367041-e9dd0a75-b4f0-4286-a121-0c6d99f82632.png)

---------------------

Verification passed on 

Brave | 1.48.132 Chromium: 109.0.5414.87 (Official Build) beta (64-bit)
-- | --
Revision | `2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#16515](https://github.com/brave/brave-core/pull/16515)
- Verified default account names are shown in full
![image](https://user-images.githubusercontent.com/17010094/214365938-bc9a75e4-a813-4c13-8f77-9ef36dc9b51a.png)
---------------------

Verification passed on 

Brave | 1.48.132 Chromium: 109.0.5414.87 (Official Build) beta (arm64)
-- | --
Revision | `2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#16515](https://github.com/brave/brave-core/pull/16515)
- Verified default account names are shown in full
![image](https://user-images.githubusercontent.com/17010094/214367346-4842de81-156e-42ef-8fe0-8e164cf965a4.png)
