### ISSUE TITLE
Remove Brave Private Ads icon and text in Brave Private Ads disabled state in brave://rewards 

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#27619]
## Current

![image](https://user-images.githubusercontent.com/11497541/210429332-4d155537-7bd5-4fcb-ab88-b9faeffcc029.png)

## Solution

![image](https://user-images.githubusercontent.com/11497541/210429301-f1bc342b-90be-4a7d-80aa-d324718d98b6.png)

**Comment by stephendonner** [comment]
Except, with the toggle in the 2nd screenshot there set to `Enabled,` correct @Miyayes ?

**Comment by Miyayes** [comment]
> Except, with the toggle in the 2nd screenshot there set to `Enabled,` correct @Miyayes ?

Sorry if I'm misunderstanding the question, but when it's in enabled mode, the part that was removed doesn't show anyway. So these changes are only relevant to the disabled state :)

**Comment by kjozwiak** [comment]
The above requires `1.48.121` or higher for `1.48.x` 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.48.125 Chromium: 109.0.5414.87 (Official Build) beta (x86_64)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | macOS Version 12.6.2 (Build 21G320)
```

**Comment by stephendonner** [comment]
## Verified `PASSED` using `1.48.134`, `Chromium 109.0.5414.87` on a `Google Pixel XL` running `Android 9`

w/refresher promo | `Light` | `Dark`
-------------------|--------|--------
![Screenshot_20230120-225513](https://user-images.githubusercontent.com/387249/213847991-ae3a58d7-a9e1-4e36-a107-45cb26a1ed28.png) | ![Screenshot_20230120-225524](https://user-images.githubusercontent.com/387249/213847993-d119e1b2-8d38-4333-8e3c-bf1f84539353.png) | ![Screenshot_20230120-230111](https://user-images.githubusercontent.com/387249/213848083-88820513-9636-4939-b826-6ef274900dfc.png)
