### ISSUE TITLE
Drop Extension Whitelist

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#27613]
It hasn't been in use for a while and we don't actually need this functionality in the code anymore.

**Comment by iefremov** [comment]
Will need to drop the crx component and archive extension-whitelist and hashset-cpp repos.

**Comment by iefremov** [comment]
Also update wiki pages

**Comment by bsclifton** [comment]
Quick notes- I went ahead and:
- archived https://github.com/brave/extension-whitelist
- archived https://github.com/brave/hashset-cpp
- created https://github.com/brave/brave-core-crx-packager/pull/592 to remove the file from the CRX component
