### ISSUE TITLE
 Rewards menu item is shown in the ☰ menu for users in OFAC list countries

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#27629]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/25275
 Rewards menu item is shown in the ☰ menu for users in OFAC list countries
## Steps to Reproduce

   1. Follow the steps 1 to 8 from Test Case 3 https://github.com/brave/internal/issues/981#issuecomment-1369867279
   2.  Rewards menu item is shown in the ☰ menu for Cuba 
   

## Actual result:

 Rewards menu item is shown in the ☰ menu for users in OFAC list countries
![image](https://user-images.githubusercontent.com/38657976/210549599-a8138382-8fe7-4514-875e-92c228f554c8.png)

## Expected result:
 Rewards menu item should NOT be shown in the ☰ menu for users in OFAC list countries

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave	1.47.161 Chromium: 109.0.5414.61 (Official Build) beta (64-bit) 
Revision	846c6eff1c374cde417a9cdc44193545cc07f354-refs/branch-heads/5414@{#1030}
OS	Windows 10 Version 21H2 (Build 19044.1826)
## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @mkarolin @Miyayes

**Comment by kjozwiak** [comment]
The above requires `1.47.168` or higher for `1.47.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.47.168 Chromium: 109.0.5414.87 (Official Build) (x86_64)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | macOS Version 12.6.2 (Build 21G320)
```
