### ISSUE TITLE
Marketo "view as a webpage" links don't work

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#27625]
Marketo sends emails that contain a "view as a webpage" link in them. They look like: https://info.cloudflare.com/index.php/email/emailWebview?mkt_tok=SOME_LONG_AUTH_ID&md_id=88687

Unfortunately, stripping the `mkt_tok` parameter breaks that page:
![Screenshot from 2023-01-03 16-13-02](https://user-images.githubusercontent.com/167821/210462095-8a1aace5-a740-4bf6-b620-c7751ba8eb9c.png)

We'll probably need to change our Marketo rule (added in https://github.com/brave/brave-core/pull/13726) to also ignore URLs that include `emailWebview` in them.

**Comment by fmarier** [comment]
Real examples seen in the wild:
- https://info.edwards.com/index.php/email/emailWebview?mkt_tok=NzY5LU5PWi05MTcAAAGF1dMjCxuk01CEJX6NdE29gvZHz93qxIpkJoG5oReXXgwMwZBpRx4f3dcL8MsBM88QRkx6yJHtGnU7MWQwjjwufjOYvp4foGL8BW2s8XSoDbU&md_id=8349&aliId=jU1SdsPNLwcJzD8fjoj7RtKe7VyrGOLS1sMFYp2euaBOtzkYFJy7Xg==
- https://go.ucalgary.ca/index.php/email/emailWebview?mkt_tok=MTYxLU9MTi05OTAAAAGIQCcXWxWCOZELZQkZAmx1J32rCV8iXIApfqPri9kTH8MfhtJnA9QpOuxD8QohTXQtD7rEH9i87KTM_UZpqJoGu_G7bW3-l2WgRmaIZg&md_id=215188

**Comment by kjozwiak** [comment]
The above requires `1.48.120` or higher for `1.48.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.48.122 Chromium: 109.0.5414.87 (Official Build) beta (x86_64)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | macOS Version 13.2 (Build 22D5038i)



### Steps:

#### Case 1

opened `https://go.ucalgary.ca/index.php/email/emailWebview?mkt_tok=MTYxLU9MTi05OTAAAAGIQCcXWxWCOZELZQkZAmx1J32rCV8iXIApfqPri9kTH8MfhtJnA9QpOuxD8QohTXQtD7rEH9i87KTM_UZpqJoGu_G7bW3-l2WgRmaIZg&md_id=215188` and confirmed that the page loaded without error.

<img width="1787" alt="Screenshot 2023-01-12 at 2 44 16 AM" src="https://user-images.githubusercontent.com/387249/212046334-6972a3af-c12b-44c2-b614-b7d837fac5e3.png">


#### Case 2

opened `https://brave.com/?mkt_tok=12345` and confirmed that the URL bar only shows `https://brave.com/`

<img width="1787" alt="Screenshot 2023-01-12 at 2 43 01 AM" src="https://user-images.githubusercontent.com/387249/212046022-0c7f1f9e-015e-4ff6-a24c-095eb1e2649f.png">

**Comment by stephendonner** [comment]
## Verified `PASSED` using `1.48.134`, `Chromium 109.0.5414.87` on a `Google Pixel XL` running `Android 9`

### Case 1: 

1. installed `1.48.134`
2. launched Brave
3. opened `https://go.ucalgary.ca/index.php/email/emailWebview?mkt_tok=MTYxLU9MTi05OTAAAAGIQCcXWxWCOZELZQkZAmx1J32rCV8iXIApfqPri9kTH8MfhtJnA9QpOuxD8QohTXQtD7rEH9i87KTM_UZpqJoGu_G7bW3-l2WgRmaIZg&md_id=215188` and confirmed that the page loaded without error.

example | example
---------|---------
![Screenshot_20230120-223715](https://user-images.githubusercontent.com/387249/213847366-96ea7647-dc08-4ed5-9c6f-83542ae8391d.png) | ![Screenshot_20230120-223725](https://user-images.githubusercontent.com/387249/213847367-a1487735-0b0d-4480-96df-3d5c213a0b8f.png)

### Case 2:

1. (continued from `Case 1`
2. opened `https://brave.com/?mkt_tok=12345` and confirmed that the URL bar only shows `https://brave.com/`

example | example
---------|---------
![Screenshot_20230120-223750](https://user-images.githubusercontent.com/387249/213847385-6c0c875b-ca6e-4928-a686-35e54ae42437.png) | ![Screenshot_20230120-223756](https://user-images.githubusercontent.com/387249/213847386-408ec441-8f32-40a3-a55c-0ae6c0ec525e.png)
