### ISSUE TITLE
Update linear gradient in Rewards panel (not-connected state)

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#27620]
## Description

Figma and current Nightly 1.48.100 Chromium: 109.0.5414.46 (Official Build) nightly (x86_64) . 

![image](https://user-images.githubusercontent.com/11497541/210430853-d0e20f64-74e4-4f0d-aae5-8bc8316e47a7.png)

![image](https://user-images.githubusercontent.com/11497541/210430885-15f26f8e-d7b3-4900-b028-9afba5a1fc8b.png)

## Solution 

Use: 

`background: linear-gradient(129.97deg, #4C54D2 9.56%, #A3278F 106.62%);`

**Comment by Miyayes** [comment]
Can we request uplift of this into 1.48.x? I'm seeing it on 1.49.5 Chromium: 109.0.5414.80 (Official Build) nightly (x86_64), public Nightly.

Looking good:

![image](https://user-images.githubusercontent.com/11497541/211135197-8397eb09-0083-4429-a872-9112cb633dca.png)

![image](https://user-images.githubusercontent.com/11497541/211135205-d57bb4b4-32ce-4314-9df7-f40d9b4e8df0.png)

![image](https://user-images.githubusercontent.com/11497541/211135211-cee6a515-365e-4328-bdd1-48f964fca6c1.png)

cc: @zenparsing

**Comment by kjozwiak** [comment]
The above requires `1.48.121` or higher for `1.48.x` 👍

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.48.125 Chromium: 109.0.5414.87 (Official Build) beta (64-bit)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | Windows 10 Version 21H2 (Build 19044.2486)

```
