### ISSUE TITLE
Resolve rewards panel background tint

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#27624]
this issue is to resolve rewards panel background tint mentioned in below image. 

![Screenshot_20230104-044845](https://user-images.githubusercontent.com/5146988/210457619-20af29c0-33df-4f89-90a6-962ee99ba287.png)

**Test plan : **

- install nightly application
- open rewards panel on new profile
- you should be able to see the image above

**Comment by stephendonner** [comment]
## Verified `PASSED` using `1.48.134`, `Chromium 109.0.5414.87` on a `Google Pixel XL` running `Android 9`

### Steps:
1. installed `1.48.134`
2. launched Brave
3. tapped the `BAT` icon
4. tapped `Start using Brave Rewards`
5. compared the resulting widget to the one in https://github.com/brave/brave-browser/issues/27624#issue-1518046908

#### Confirmed the widget's appearance matches and has correct styles for disabled/selected states

#### `Light`

disabled | selected
---------|---------
![Screenshot_20230120-153235](https://user-images.githubusercontent.com/387249/213824132-e7867fac-c9a0-4352-80e8-da4f603e56fd.png) | ![Screenshot_20230120-153635](https://user-images.githubusercontent.com/387249/213824143-1166554a-b59b-41f1-befa-8b1fbbfa6ed4.png)




#### `Dark`

disabled | selected
---------|---------
![Screenshot_20230120-153327](https://user-images.githubusercontent.com/387249/213824180-44ad7851-7f42-45cb-b5ed-2e1c27602c17.png) | ![Screenshot_20230120-153613](https://user-images.githubusercontent.com/387249/213824185-bec74113-1a45-4f89-bc96-1e446debd6f2.png)
