### ISSUE TITLE
Chrome branding present in Notification Permission popup

### ISSUE THREAD

**Issue by gstack** [brave/brave-browser#2762]
## Description 
Text in notification permission denial popup still refers to Chrome, should refer to Brave

## Steps to Reproduce
   1. Open a page which attempts to ask for notification permissions
   2. Deny request

## Actual result:
![image](https://user-images.githubusercontent.com/5206028/50547323-b4803800-0bec-11e9-8b37-801e37083996.png)

## Reproduces how often: 
Easily reproduced

## Brave version (brave info)
Brave | 0.60.5 Chromium: 72.0.3626.28 (Official Build) dev (64-bit)
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Yes

**Comment by srirambv** [comment]
Please update the issue with the template and add details of the browser version you are seeing this.

Regarding the location of the notification, I think we should make the wide URL bar default and have the option to shrink it in settings. @petemill  thoughts?
