### ISSUE TITLE
Use PrefService Java class for local state prefs from BravePrefServiceBridge

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#27632]
Follow-up for https://github.com/brave/brave-core/pull/16386

Edit BravePrefServiceBridge for local state based prefs is not perfect by following reasons:
- it requires add new methods in two files;
- it's easy to make mistake.

The good solution would be to re-use Chromium PrefService class and auto-generated pref names, which is now done for profile-based prefs.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using `1.48.141` `Chromium` `109.0.5414.119` on a `Google Pixel XL` (`arm64`) running `Android 9`

Case 1: `brave.p3a.enabled`



Case 2: `brave.stats.reporting_enabled`
Case 3: `safetynet.status`
Case 4: `brave.unstoppable_domains.resolve_method`
Case 5: `brave.ens.resolve_method`
Case 6: `brave.sns.resolve_method`
Case 7: `brave.ens.offchain_resolve_method`

**Comment by Uni-verse** [comment]
In Progress on Samsung Galaxy S21 using version:

Brave	1.48.157 Chromium: 110.0.5481.77 (Official Build) (64-bit) 
Revision	65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS	Android 13; Build/TP1A.220624.014
