### ISSUE TITLE
Remove Wyre from Wallet Front End

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#27634]
## Description 

Wyre will shut down their services soon, we need to remove Wyre as an onramp option on the Wallet Front End.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.49.3 Chromium: 109.0.5414.74 (Official Build) nightly (64-bit)
-- | --
Revision | e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}
OS | Windows 11 Version 22H2 (Build 22621.963)
```

Using the STR/Cases mentioned via https://github.com/brave/brave-core/pull/16526#issue-1519213845 & https://github.com/brave/brave-core/pull/16526#issuecomment-1373103633, ensured that `Wyre` was removed from `Brave Wallet` as per the following:

**`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------
![fixedPurchaseOnramp](https://user-images.githubusercontent.com/2602313/211091933-dc0f8436-985a-49d2-81a4-fd5551495c1b.png) | ![fixedPurchaseETH](https://user-images.githubusercontent.com/2602313/211091916-c8606eb8-3547-42fe-a130-bafc3e29b6c5.png) | ![fixedPurchasePanel](https://user-images.githubusercontent.com/2602313/211091931-b4115e88-1b48-42c2-bac6-af5443e9e9f7.png)
