### ISSUE TITLE
Display reason for disabled "Add" button when attempting to add an invalid custom token

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#27636]
## Description 

Users should be informed as to why the form submission button ("Add") is disabled  during the process of adding a custom token visible asset. Any validation error should be displayed to the user so that it is clear why the submit button is disabled.

## Steps to Reproduce

   1. Click the Add Visible Assets button on the wallet portfolio screen
   2. click add custom asset
   3. leave all form fields blank 
   4. Attempt to click the "Add" button

## Actual result:

Nothing is displayed to the user as to why the button is disabled.

## Expected result:
UI is displayed to the user that explains why the button is disabled if invalid data is present in the form

## Reproduces how often: 

Easily reproduced

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta  (64-bit) 
-- | --
Revision | `46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}`
OS | Linux

- Verified steps from [brave/brave-core#16550](https://github.com/brave/brave-core/pull/16550)
- Verified tooltip is shown for disabled `Add` button
- Encountered [#28784](https://github.com/brave/brave-browser/issues/28784)

Token | NFT
-- | --
![image](https://user-images.githubusercontent.com/17010094/221639928-2a89eb3f-0e83-48c5-8667-fc44c335b854.png) | ![image](https://user-images.githubusercontent.com/17010094/221639858-2320d9d5-4de1-4bba-9e98-b95ed80ac6e0.png)

---------------------

Verification passed on 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta  (64-bit)
-- | --
Revision | `46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#16550](https://github.com/brave/brave-core/pull/16550)
- Verified tooltip is shown for disabled `Add` button
- Encountered [#28784](https://github.com/brave/brave-browser/issues/28784)

Token | NFT
-- | --
![image](https://user-images.githubusercontent.com/17010094/221639405-722e6dd0-03ff-4012-93bf-c0cf6bd7e950.png) | ![image](https://user-images.githubusercontent.com/17010094/221639653-b6fea83c-13ea-46bd-8a70-30cc24be64cb.png)

---------------------

Verification passed on 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta  (arm64)
-- | --
Revision | `46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#16550](https://github.com/brave/brave-core/pull/16550)
- Verified tooltip is shown for disabled `Add` button
- Encountered [#28784](https://github.com/brave/brave-browser/issues/28784)

Token | NFT
-- | --
![image](https://user-images.githubusercontent.com/17010094/221640627-d7434427-1179-42e7-82a2-5ec9a4787c55.png) | ![image](https://user-images.githubusercontent.com/17010094/221640641-6f794125-7de2-49e9-85ee-363b81007112.png)
