### ISSUE TITLE
Ability to prevent auto downloading and opening seems to be broken

### ISSUE THREAD

**Issue by tapanmodh** [brave/brave-browser#27637]
## Description 
We have option in the `Download` settings to `Automatically open when possible` but it is broken

## Steps to reproduce 

1. Go to `Downloads` settings
2. Turn off `Automatically open when possible`
3. Click https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf
4. Pdf file will be downloaded and opened in a default PDF viewer app.

## Actual result 
Turn off `Automatically open when possible` and downloading the pdf file is opening in the default PDF viewer app

## Expected result
Turn off `Automatically open when possible`, Pdf file should be just downloaded, without opening
Turn on `Automatically open when possible`, Pdf should be opened automatically after downloading

## Issue reproduces how often 
Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone (Pixel 6 Pro, OnePlus 6T)
   - Android version: Android 13, Android 11
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by Uni-verse** [comment]
Verified on `Samsung GS 21 5G` using version: 

```
Brave	1.49.118 Chromium: 111.0.5563.50 (Official Build) (64-bit) 
Revision	39f3dfc5023fe60997adc4f6cf5439cfa3e6968a-refs/branch-heads/5563@{#903}
OS	Android 13; Build/TP1A.220624.014
```

Using the Test Plan in https://github.com/brave/brave-browser/issues/27637#issue-1519433148

- Ensured enabling `Automatically open when possible` will open pdf automatically after downloading

Example | Example
-|-
![screenshot-1678206174904](https://user-images.githubusercontent.com/17885425/223489208-17724cfe-ac05-4897-bd35-75d01a7eccd9.png) | ![screenshot-1678207295853](https://user-images.githubusercontent.com/17885425/223489377-4cde503c-d18b-4e2d-91a7-615e25be3385.png)
