### ISSUE TITLE
Enables SafeBrowsing on Android by default

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#27642]
We want to set the `brave-safe-browsing` flag to Enabled by default and keep it to be able to control the feature by Griffin.

**Comment by Uni-verse** [comment]
Verified on `Samsung GS 21 5G` using version(s):

```
Brave	1.49.118 Chromium: 111.0.5563.50 (Official Build) (64-bit) 
Revision	39f3dfc5023fe60997adc4f6cf5439cfa3e6968a-refs/branch-heads/5563@{#903}
OS	Android 13; Build/TP1A.220624.014
```

- Ensured that Safe Browsing is enabled by default. 
- Ensured that disabling brave-safe-browsing flag will disable safe browsing using `https://testsafebrowsing.appspot.com/`

Example | Example | Example | Example
-|-|-|-
![screenshot-1678151047248](https://user-images.githubusercontent.com/17885425/223293843-e5238e81-9626-4096-ab51-34b4ba46aef8.png) | ![screenshot-1678151400004](https://user-images.githubusercontent.com/17885425/223293872-a30e3147-85f8-4322-9207-af4993654e5c.png) | ![screenshot-1678151451004](https://user-images.githubusercontent.com/17885425/223293889-19ec452c-2880-493a-be7e-063695e3f2c6.png) | ![screenshot-1678151468603](https://user-images.githubusercontent.com/17885425/223293891-be193fd9-de8a-4a7a-a273-843fe0605979.png)
Android 8 | Android 8 | Android 8 | Android 8
![Screen Shot 2023-03-06 at 8 32 45 PM](https://user-images.githubusercontent.com/17885425/223296883-52549c25-7cb4-4c9e-8b73-798a44d344e9.png) | ![Screen Shot 2023-03-06 at 8 34 47 PM](https://user-images.githubusercontent.com/17885425/223296885-bc7463ac-4835-429e-8fad-db5cde02daf2.png) | ![Screen Shot 2023-03-06 at 8 36 23 PM](https://user-images.githubusercontent.com/17885425/223296887-1ba58f34-d4fc-4e56-9ae1-89bfa93d111f.png) | ![Screen Shot 2023-03-06 at 8 38 16 PM](https://user-images.githubusercontent.com/17885425/223296890-92703ca1-1bd5-4b22-8473-6fa53821d647.png)
Example | Example | Example | Example
-|-|-|-
![screenshot-1678153345568](https://user-images.githubusercontent.com/17885425/223297651-e97f2e3c-252a-4fa7-87a0-81000476828a.png) | ![screenshot-1678153394818](https://user-images.githubusercontent.com/17885425/223297652-21e05954-83eb-43e3-970f-de60ea1ef2bb.png) | ![screenshot-1678153431163](https://user-images.githubusercontent.com/17885425/223297655-7f109923-dcbf-4e34-92f2-234bb2bf540f.png) | ![screenshot-1678153446876](https://user-images.githubusercontent.com/17885425/223297656-32a30c70-7005-4e5f-82c5-2a5cbd992d3f.png)
