### ISSUE TITLE
Shields onboarding experience gets interrupted by a few things

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#27644]
## Description
During the onboarding experience (testing done on BETA), we encourage folks to type a URL and visit a site (`See the Brave difference`). The intention is that when the site loads, likely some trackers or ads will be blocked and we can showcase how many were blocked.

The problem is - there are a few things which get in the way.

## Steps to reproduce 

   1. Fresh install of Brave (I used Beta)
   2. Finish the typical onboarding steps and get to the `See the Brave difference` notification
       <img src="https://user-images.githubusercontent.com/4733304/210653419-a8730ddb-fab4-460d-8ea7-4e4ed65c7c80.png" width="250px">
   3. Dismiss the `See the Brave difference` notification
   4. Immediately, `Brave notifications make it easier` modal shows, interrupting the experience
       <img src="https://user-images.githubusercontent.com/4733304/210653679-ada268a9-a1fa-4993-bdc9-bc7a228ab6ff.png" width="250px">
   5. Click either `Continue`
   6. Person is presented with `Allow Brave to send you notifications?`
       <img src="https://user-images.githubusercontent.com/4733304/210654030-beacc641-e8e8-4fab-8a41-9fe23015b734.png" width="250px">
   7. Person can choose `Allow` or `Don't allow` (doesn't matter the choice)
   8. Finally the URL box is focused 🎉 However, there is a widget promotion showing now. It's not entirely clear if this is blocking the experience. It seemed to hide the keyboard for me
       <img src="https://user-images.githubusercontent.com/4733304/210654252-42301968-f97a-40ed-acdb-41835698f982.png" width="250px">
   9. After clicking `Not now` or ignoring (re-clicking the omnibox), the person can finally type the URL they want to visit and hit enter
   10. Shields notification shows 🎉 
          <img src="https://user-images.githubusercontent.com/4733304/210654585-418336fc-c92e-489f-8f27-743b81af0547.png" width="250px">

## Expected result
We should eliminate steps 4 - 8 in the above experience and just allow the user to see the shields being blocked (ex: let them see "the Brave difference"). Those items in 4 - 8 are also important - but we can find a better time to present them (ex: after shields # of items blocked has been acknowledged)

**Comment by anthonypkeane** [comment]
Thanks @bsclifton 

Related Issues
https://github.com/brave/brave-browser/issues/25042
https://github.com/brave/brave-browser/issues/25041

~~~

For context,
- The above flow is present in Nightly & Beta, not **Release**.
- Steps 4-7 are applicable to Android 13 only. 


Please adjust the above as follows:
- The user should be allowed to complete onboarding without any interruptions (i.e. no additional asks, Widget/Notifications permissions etc)
- Move the Widget introduction to Session 25 - tracked here: https://github.com/brave/brave-browser/issues/27648

Regarding the Android 13 notification. 
Right now in Release this is notification is presented after onboarding. Having the permission is important as it enables the media player control in the background, enables Brave Ads etc. We might need to move this request into onboarding as other browsers do but for now leave it as-is until we decide on some next steps.

**Comment by anthonypkeane** [comment]
For clarity on the Android 13 notification.

After onboarding (i.e. Step 10 above) and the user has closed out that notice showing them how many Trackers/Ads were blocked, we will ask them if they would like to opt into receiving notifications from Brave via the screen in step 4 and 6. 

As a future improvement we can look to implement the ask for notifications into the actual onboarding.

**Comment by Uni-verse** [comment]
In Progress on Samsung GS 21 5G using version

Brave	1.50.108 Chromium: 112.0.5615.39 (Official Build) (64-bit) 
Revision	a0e7b9718a92bcd1cf33b7c95316caff3fc20714-refs/branch-heads/5615@{#753}
OS	Android 13; Build/TP1A.220624.014

**Comment by Uni-verse** [comment]
> Thanks @bsclifton
> 
> Related Issues #25042 #25041
> 
> ```
> 
> For context,
> - The above flow is present in Nightly & Beta, not **Release**.
> - Steps 4-7 are applicable to Android 13 only. 
> 
> 
> Please adjust the above as follows:
> - The user should be allowed to complete onboarding without any interruptions (i.e. no additional asks, Widget/Notifications permissions etc)
> - Move the Widget introduction to Session 25 - tracked here: https://github.com/brave/brave-browser/issues/27648
> 
> Regarding the Android 13 notification. 
> Right now in Release this is notification is presented after onboarding. Having the permission is important as it enables the media player control in the background, enables Brave Ads etc. We might need to move this request into onboarding as other browsers do but for now leave it as-is until we decide on some next steps. 
> ```

@anthonypkeane Just wanted to confirm that we shouldn't be showing the widget introduction after user responds to the `See the Brave difference` popup. This is currently the case on 1.50.108. I can open an issue if necessary. Thanks.

**Comment by deeppandya** [comment]
> @Uni-verse From the video above the Widget is still appearing too early. It shouldn't appear until session 25
> cc @timchilds to confirm 

@anthonypkeane this issue is mainly handling notification callout. We have a separate issue for widget callout.
