### ISSUE TITLE
Inconsistent casing between panel and page transaction titles

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#27646]
![Screenshot 2023-01-03 at 11 32 52 AM](https://user-images.githubusercontent.com/30185185/210660160-07b159e0-ffbb-4d7d-85ed-8ee2e0a42d59.png)

## Description 

Casing for transaction title text should match between panel & page UIs

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta  (64-bit) 
-- | --
Revision | `46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}`
OS | Linux

- Verified steps from [ brave/brave-core#16533](https://github.com/brave/brave-core/pull/16533)
- Verified Sent is shown in same casing on both panel and transaction activity page
![image](https://user-images.githubusercontent.com/17010094/221638104-6fb043d0-fe38-4add-8ac4-3253cc260283.png)

---------------------

Verification passed on 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta  (64-bit)
-- | --
Revision | `46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [ brave/brave-core#16533](https://github.com/brave/brave-core/pull/16533)
- Verified Sent is shown in same casing on both panel and transaction activity page
![image](https://user-images.githubusercontent.com/17010094/221636319-0c18d693-14f5-4fa9-9153-f124f99ab78b.png)

---------------------

Verification passed on 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta  (arm64)
-- | --
Revision | `46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [ brave/brave-core#16533](https://github.com/brave/brave-core/pull/16533)
- Verified Sent is shown in same casing on both panel and transaction activity page
![image](https://user-images.githubusercontent.com/17010094/221637994-4acf11e5-ecd1-427a-8baa-97cb0d43b2f5.png)
