### ISSUE TITLE
Follow-up to #27122 Add additional confirmation to end of support message dismissal

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#27649]
## Description 

Update button from "Don't show again" to a check box [ ] Don't show again

When clicking on Don't show again checkbox and "x" to dismiss, show an additional confirmation dialog that reads:

"By clicking OK, you acknowledge that your installation of Brave will NOT receive critical security fixes until you update to Windows 10 or later. This warning will NOT show again." 

Add two buttons "OK" and "Cancel". 
Ok will dismiss the dialog and infobar and not show the message again.
Cancel will dismiss the dialog. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

https://github.com/brave/brave-browser/issues/27122

**Comment by simonhong** [comment]
@rebron I realized that previous infobar change was applied to all OS not just Windows.
So, linux or macOS users also could see system obsolete infobar with `Don't show again` button on their old system.
I think we may also want to use this confirm dialog on all platforms not just Windows. Then, we need different sentences for each platfom. Or if we want to change chromium's infobar style only for Windows, we could do that. WDYT?

**Comment by rebron** [comment]
It's ok to have this style for all OSes. As long as we're not telling Linux or macOS users to upgrade to Windows 10 or higher we should be ok. 

Do you have a pointer for the text for the other platforms? 
"to Windows 10 or later" could be something like "to a supported version of your OS" or "to a newer, supported version of your OS"

**Comment by simonhong** [comment]
> It's ok to have this style for all OSes. As long as we're not telling Linux or macOS users to upgrade to Windows 10 or higher we should be ok.
> 
> Do you have a pointer for the text for the other platforms? "to Windows 10 or later" could be something like "to a supported version of your OS" or "to a newer, supported version of your OS"

Chromium uses different strings per platform and os.
You can see them here - https://source.chromium.org/chromium/chromium/src/+/main:chrome/app/google_chrome_strings.grd;l=428

**Comment by kjozwiak** [comment]
The above requires `1.47.176` or higher for `1.47.x` verification 👍

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.47.177 Chromium: 109.0.5414.87 (Official Build) (64-bit) 
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/16553

<details>

Verified inforbar is shown and that it contains the checkmark

![image](https://user-images.githubusercontent.com/34715963/213493705-b6e763ed-4560-4093-bff9-cf2ce96ff86a.png)

Verified infobar is shown again after browser restart when the checkmark is not marked
![image](https://user-images.githubusercontent.com/34715963/213495495-4811756b-f06d-4980-94e8-4a118e16bfbb.png)|![image](https://user-images.githubusercontent.com/34715963/213495622-23e27a35-ca2e-47ba-962c-03bce850f295.png)
--|--

Verified additional dialog is shown when the checkmark is marked
![image](https://user-images.githubusercontent.com/34715963/213495973-8236b537-fd6e-4ac7-9972-1aa07509caf4.png)|![image](https://user-images.githubusercontent.com/34715963/213496024-1e7e78fe-03ef-4530-a61b-06fd1cc2cd3e.png)
--|--

Verified inforbar is shown again after browser restart when user clicks `Cancel` on additional dialog
![image](https://user-images.githubusercontent.com/34715963/213496433-736444be-9844-4f93-b445-f74ce70aedb2.png)|![image](https://user-images.githubusercontent.com/34715963/213496838-0c2b26f9-fdbd-4f35-ae20-a9854fe15b87.png)
--|--

Verified inforbar is shown again after browser restart when user clicks `Cancel` on additional dialog
![image](https://user-images.githubusercontent.com/34715963/213497134-6256f8fc-18e0-48f4-8d69-4426f8c10e34.png)|![image](https://user-images.githubusercontent.com/34715963/213497192-c035a282-8537-4264-b22f-b566e2e8ca20.png)|![image](https://user-images.githubusercontent.com/34715963/213497265-fa6c2412-46c5-4379-8cb4-fad740e3f1b1.png)
--|--|--

</details>

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 8.1 x64` using the following build(s):

```
Brave | 1.47.183 Chromium: 109.0.5414.119 (Official Build) (64-bit)
--- | ---
Revision | 772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}
OS | Windows 8.1 (Build 9600.20778)
```

* verified the STR/Cases outlined via https://github.com/brave/brave-core/pull/16553#issue-1521947030
* ensured that the correct OS is being listed via the infobar
* ensured that the `Learn more` link worked as expected and opened the correct support page
* ensured that the infobar only appears once per session once it's dismissed
* ensured that the infobar always appears after re-launch if the user hasn't checked off `Don't show again`
* ensured that the infobar always appear after re-launch of the user checked off `Don't show again` but never confirmed
* ensured that the infobar always appears after re-launch when user checked off `Don't show again` but cancelled confirmation
* ensured that the infobar doesn't re-appear again once the user clicks on `OK` and confirms
* ensured that the infobar doesn't re-appear once permanently closed via `Guest`, `PB` & `Tor` windows

**`Example`** | **`Example`** | **`Example`** | **`Example`** 
---------------|-----------------|----------------|----------------
<img width="1053" alt="Screenshot 2023-01-25 at 3 35 50 AM" src="https://user-images.githubusercontent.com/2602313/214517201-687928d0-c66f-42f5-a9fa-2fa0d3a76115.png"> | <img width="1050" alt="Screenshot 2023-01-25 at 3 36 11 AM" src="https://user-images.githubusercontent.com/2602313/214517217-2392baa5-c0f8-4b57-93ee-ec08aa1c8d68.png"> | <img width="1057" alt="Screenshot 2023-01-25 at 3 36 53 AM" src="https://user-images.githubusercontent.com/2602313/214517222-b5fa6f69-b9bc-4212-891b-44f583c94b30.png"> | <img width="1046" alt="Screenshot 2023-01-25 at 3 37 52 AM" src="https://user-images.githubusercontent.com/2602313/214517232-591aff65-204f-4e66-b167-3ed138cc1254.png">

Not related to this PR, but the OS is also starting to warn users as per the following:

<img width="1437" alt="Screenshot 2023-01-19 at 12 54 26 AM" src="https://user-images.githubusercontent.com/2602313/213366784-e1a7e4b2-8bad-4e98-b7b0-bf5a90b35dd5.png">
