### ISSUE TITLE
[CR109] Custom Filters styling not applied for Filter lists and Add custom filter lists

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#27647]
## Description 

Styling is not applied for Filter lists and Add custom filter lists.
Follow-up to https://github.com/brave/brave-browser/issues/27450

## Steps to Reproduce

   1. Visit brave://settings/shields/filters in 1.47.61 with CR 109
   2. Notice styling is off for Custom lists, lacking borders and background fill see screenshot in Expected result.

## Actual result:

<img width="679" alt="Screenshot 2023-01-04 at 2 14 18 PM" src="https://user-images.githubusercontent.com/5951041/210660549-3069911b-9f7d-498d-9141-687632be74a5.png">

<img width="688" alt="Screenshot 2023-01-04 at 2 20 11 PM" src="https://user-images.githubusercontent.com/5951041/210660910-ed8b5d28-902b-4af1-ab3a-8f308e7ab8e5.png">

## Expected result:
<img width="688" alt="Screenshot 2023-01-04 at 2 14 45 PM" src="https://user-images.githubusercontent.com/5951041/210660542-957406ae-8989-4e78-b0e1-64ca6518513a.png">
<img width="706" alt="Screenshot 2023-01-04 at 2 22 05 PM" src="https://user-images.githubusercontent.com/5951041/210661200-2e822e82-e816-4f7e-b8e6-60136ba5c2e7.png">

## Reproduces how often: 

Easily.

## Brave version (brave://version info)

1.47 with CR 109

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by ParagGhatage** [comment]
@rebron 
I would love to work on this issue.
Will you assign it to me?

**Comment by jagadeshjai** [comment]
Hey @ParagGhatage!

Are you still interested in fixing this bug? If so, just mention it here, and you can get started right away!

**Comment by ParagGhatage** [comment]
> Hey @ParagGhatage!
> 
> Are you still interested in fixing this bug? If so, just mention it here, and you can get started right away!

Thank you for reaching out. I’m currently focused on another issue, but I will begin working on this bug as soon as I’ve completed that task.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.71.90 Chromium: 129.0.6668.59 (Official Build) beta (64-bit)
-- | --
Revision | 1f5f0d1b8a45a4c60a78c15df081751e39184b97
OS | Windows 11 Version 23H2 (Build 22631.4169)
```

Reproduced the issue in 1.70.117

![image](https://github.com/user-attachments/assets/1b31bd72-6215-4093-8913-af5e0a0bd1f0)



1. Installed 1.71.90
2. launched Brave
3. opened `brave://settings/shields/filters`


- Confirmed styling is applied for `Filter lists` and `Add custom filter lists` 
- Confirmed the orange color highlight was removed

Light theme

![image](https://github.com/user-attachments/assets/1a862476-5920-4115-b346-c4d552d6de9e)

Dark theme

![image](https://github.com/user-attachments/assets/aeb563fd-c47e-4479-a8ac-ffaa5d839897)
