### ISSUE TITLE
Add import from Whale browser

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#27641]
## Description 
Add Whale browser to brave://settings/importData list

Test plan
(taken from https://github.com/brave/brave-core/pull/16441)
Install Whale browser and check that History, Bookmarks and Extensions can be imported.

## Expected result:

   1. Have Whale browser installed
   2. Install a new fresh version of Brave. When visiting brave://welcome, Whale should be a listed browser.
   3. Alternatively skip brave://welcome onboarding and visit brave://settings/getStarted. Selecting brave://settings/importData should show Whale as a listed browser.

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

related issue: https://github.com/brave/brave-browser/issues/27301

**Comment by rebron** [comment]
cc: @spylogsster @simonhong

**Comment by jenn-rhim** [comment]
Whale logo:


![whale](https://user-images.githubusercontent.com/4369856/210640416-f8bebe0a-4e40-47cc-8ed6-dd5d89c348ac.svg)

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using 
```
Brave | 1.48.158 Chromium: 110.0.5481.77 (Official Build) (64-bit)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | Windows 11 Version 21H2 (Build 22000.1455)
```
Download Whale browser and create 3 Profiles with data - bookmarks, history, extensions and passwords

<img width="929" alt="image" src="https://user-images.githubusercontent.com/98358127/218889182-124844a9-8b33-4ec6-ad08-5926be25e26c.png">

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 


### Prerequisite: Whale browser profile, populated with `bookmarks`, `history`, and `extensions`

### Case 1: Import from `brave://settings/importData` - `PENDING`
<details>

1. installed ``
2. launched Brave
3. clicked `Skip` -> `Skip` -> `Finish`
4. opened `brave://settings/importData` in the new-tab page
5. verified `Whale` option is displayed in the `Import bookmarks and settings` dropdown
6. selected ``
7. kept default selections of `Browsing history`, `Favorites/Bookmarks` and `Extensions`
8. clicked `Import`
9. clicked `Done`

steps 4-5 | step 7 | step 8 | bookmarks | history | extensions
----------|--------|-------|-------------|--------|-----------




#### Confirmed bookmarks are shown in the bookmarks bar & `brave://bookmarks`

#### Confirmed history is shown in `brave://history`

#### Confirmed extensions are shown in toolbar and `brave://extensions`

</details>

### Case 2: Import from `Import Bookmarks Now...` - `PENDING`
<details>

1. new profile
2. launched Brave
3. clicked `Import bookmarks now...` in the bookmarks bar
4. verified `Whale` option displayed in the `Import bookmarks and settings` modal dropdown
5. selected `Whale User 1`
6. unselected default selections and selected `Favorites/Bookmarks`
7. clicked `Import`
8. clicked `Done`

#### Confirmed bookmarks are shown in the `bookmarks bar` and in `brave://bookmarks`

step 4 | steps 5-8 | step 9 | `brave://bookmarks`
-------|-----------|--------|---------------------



</details>


### Case 3: Import from multiple profiles - `PENDING`
<details>

`Whale profiles`



`Yandex User 1` | imported bookmarks | `Yandex User 2` | imported bookmarks | `Yandex User 3` | imported bookmarks
---------|----------|---------|----------|---------|---------


`brave://extensions` | `brave://history`
---------------------|----------------


</details>

### Case 4: Bookmarks imported from `Whale` should sync between devices - `PENDING`
<details>

**device 1** 

1. new profile
2. launch Brave
3. click `Import bookmarks now...` in the bookmarks bar
4. select `Whale User 1` from `Import bookmarks and settings` modal
5. keep default selections of `Browsing history`, `Favorites/Bookmarks`, `Extensions` and complete import
6. confirmed successful import of  `Browsing history`, `Favorites/Bookmarks`, `Extensions`
7. visit `brave://sync`
8. click on `Start using sync` ---> `Start a new Sync Chain`
9. click `Computer`
10. copy the code words
11. under `Sync Settings`, click on the `Sync everything` radio button

example | example | example | example
---------|----------|---------|---------


**device 2**

1. go to `device 2`
2. click on the "hamburger" menu, and then `Sync`
3. click `I have a Sync Code`
4. enter/paste the code words from `device 1`
5. click `Confirm`
6. click `OK`
7. under `Sync Settings`, click on the `Sync everything` toggle

#### Confirmed `Favorites/Bookmarks`, `Extensions` synced successfully

Note:`Browsing history` not synced.  Only URLs of the sites that were visited in the session are synced

example | example | example | example
---------|---------|----------|--------



</details>


### Case 5: Upgrade - `PENDING`
<details>

1. install `1.47.169`
2. launch Brave
3. click `Import bookmarks now...` link in the `bookmarks bar`
4. select `Chrome Canary Person 1` in the `Import bookmarks and settings` modal dialog
5. kept default selections of `Browsing history`, `Favorites/Bookmarks`, `Extensions` and finished the import
6. confirmed successful import of `Browsing history`, `Favorites/Bookmarks`, `Extensions` into Brave
7. close the browser
8. install `1.48.121`
9. relaunch Brave
10. `Browsing history`, `Favorites/Bookmarks`, `Extensions` are retained from `Chrome Canary Person 1` import
11.  go to `Hamburger menu` >>`Bookmarks` >> `Import bookmarks and settings`
12. confirmed `Whale User 1` is  listed in the drop down menu of  `Import bookmarks and settings` modal
13. selected `Whale User 1`  and keep default selections of `Browsing history`, `Favorites/Bookmarks`, `Extensions`
14. completed import

#### Confirmed successfully imported `Browsing history`, `Favorites/Bookmarks`, and `Extensions` from `Whale` 

example | example | example | example
---------|----------|---------|---------


example | example | example | example
---------|----------|---------|---------




</details>

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.49.118 Chromium: 111.0.5563.50 (Official Build) (64-bit) 
-- | --
Revision | 39f3dfc5023fe60997adc4f6cf5439cfa3e6968a-refs/branch-heads/5563@{#903}
OS | Ubuntu 18.04 LTS



### Prerequisite: Whale browser profile, populated with `bookmarks`, `history`, `passwords`, and `extensions`

### Case 1: Import from `brave://settings/importData` - `PASSED (*)`
<details>

1. installed `1.49.x`
2. launched Brave
3. clicked `Skip` -> `Skip` -> `Finish`
4. opened `brave://settings/importData` in the new-tab page
5. verified `Whale Person 1` option is displayed in the `Import bookmarks and settings` dropdown
6. selected `Whale Person 1`
7. kept default selections of `Browsing history`, `Passwords`, `Favorites/Bookmarks` and `Extensions`
8. clicked `Import`
9. clicked `Done`
10. entered macOS password and clicked `Always Allow` at the `Brave Browser Beta Helper` dialog
11. opened `brave://history`
12. opened `brave://settings/passwords`
13. opened `brave://bookmarks`
14. opened `brave://extensions`

steps 4-5 | steps 7-9  | history | passwords | bookmarks | extensions
----------|--------|-------|-------------|------------|--------
![image](https://user-images.githubusercontent.com/34715963/222840488-d9e7de75-48a6-47ee-ade1-f730dea18006.png)|![image](https://user-images.githubusercontent.com/34715963/222840619-fbd722cf-6f2e-401c-ad77-5f14a9154bf8.png)|![image](https://user-images.githubusercontent.com/34715963/222840799-44a71b8f-dc2d-45c6-9037-d4ed908dc219.png)|![image](https://user-images.githubusercontent.com/34715963/222841519-6f45c1a8-35e8-4edb-b61b-abfce02f3dec.png)|![image](https://user-images.githubusercontent.com/34715963/222841700-542c58ff-6149-4bf8-98d5-17507414595c.png)|![image](https://user-images.githubusercontent.com/34715963/222841762-a0360ff9-192b-4527-9834-9371f024bbee.png)

Password import is not supported on Linux 


#### Confirmed bookmarks are shown in the bookmarks bar & `brave://bookmarks`

#### Confirmed history is shown in `brave://history`

#### (*)Could *NOT* confirm extensions import from `Naver Whale Store` (however, `Google Chrome Store` import works, see `Case 5: Upgrade`)




</details>

### Case 2: Import from `Import Bookmarks Now...` - `PASSED`
<details>

1. new profile
2. launched Brave
3. clicked `Import bookmarks now...` in the bookmarks bar
4. verified `Whale` option displayed in the `Import bookmarks and settings` modal dropdown
5. selected `Whale Person 1`
6. deselected default selections and selected `Favorites/Bookmarks`
7. clicked `Import`
8. clicked `Done`
9. opened `brave://bookmarks`

#### Confirmed bookmarks are shown in the `bookmarks bar` and in `brave://bookmarks`

step 4 | steps 5-7  | `brave://bookmarks`
-------|-----------|-----------------------------
![image](https://user-images.githubusercontent.com/34715963/222842469-23bd3051-cca5-4908-80d7-58532da9c422.png)|![image](https://user-images.githubusercontent.com/34715963/222842519-a39b8ec7-3d9b-44b5-8b89-e052403a6aac.png)|![image](https://user-images.githubusercontent.com/34715963/222842582-1d096a34-01d8-47ad-9846-584d3a4fa910.png)


</details>


### Case 3: Import via onboarding - `PASSED`
<details>

![image](https://user-images.githubusercontent.com/34715963/222845806-f86fb6d6-7124-46b2-95d6-a75424853944.png)|![image](https://user-images.githubusercontent.com/34715963/222845852-cf0c027e-6b2a-4b86-9cba-57a9993c1067.png)|![image](https://user-images.githubusercontent.com/34715963/222845943-5f61b7f7-94f8-4107-aa11-fce462c4cda8.png)|![image](https://user-images.githubusercontent.com/34715963/222846041-93b0205d-c3fc-4970-baf7-3b9336abde4c.png)|![image](https://user-images.githubusercontent.com/34715963/222846114-6b4776dd-0687-4d02-b272-cbaf0cdffb13.png)
--|--|--|--|--






</details>

### Case 4: Bookmarks imported from `Whale` should sync between devices - `PASSED`
<details>

Created sync:
![image](https://user-images.githubusercontent.com/34715963/222848970-59770b9f-8708-470d-89c0-95d769ae7c51.png)

Imported data from Whale on Browser 1
![image](https://user-images.githubusercontent.com/34715963/222849207-d06f40e0-f449-4ba7-9850-64a52cc77a02.png)

Verified bookmarks and extensions were synced
![image](https://user-images.githubusercontent.com/34715963/222849777-e4d7f800-f596-4aab-b07e-095b2d89d3b0.png)


</details>


### Case 5: Upgrade - `PASSED`
<details>

1. installed `1.48.164`
2. launched Brave
3. clicked `Import bookmarks now...` link in the `bookmarks bar`
4. selected `Chrome Canary Person 1` in the `Import bookmarks and settings` modal dialog
5. kept default selections of `Browsing history`, `Favorites/Bookmarks`, `Extensions` and finished the import
6. confirmed successful import of `Browsing history`, `Favorites/Bookmarks`, `Extensions` into Brave
7. closed the browser
8. installed `1.49.x`
9. relaunched Brave
10. `Browsing history`, `Favorites/Bookmarks`, `Extensions` are retained from `Chrome Canary Person 1` import
11.  went to `Hamburger menu` >>`Bookmarks` >> `Import bookmarks and settings`
12. confirmed `Whale Person 1` is  listed in the dropdown menu of  `Import bookmarks and settings` modal
13. selected `Whale Person 1`  and kept default selections of `Browsing history`, `Favorites/Bookmarks`, `Extensions`
14. completed import

#### Confirmed successfully imported `Browsing history`, `Favorites/Bookmarks`, and `Extensions` from `Whale` 

![image](https://user-images.githubusercontent.com/34715963/222850045-47748bbf-6fcf-4b5f-a9d3-0deeb2f813a1.png)|![image](https://user-images.githubusercontent.com/34715963/222850110-d83e635a-4ce3-4223-b711-1c43cbd51a8e.png)|![image](https://user-images.githubusercontent.com/34715963/222850227-e3f93780-7019-4e84-be58-7f2b005abef9.png)
--|--|--




</details>
