### ISSUE TITLE
Remove info icon from place holder text in recent transaction view

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#27656]
## Description 

Remove info icon from transaction history place holder text

## Steps to Reproduce

   1. Clean wallet
   2. Open panel and go to recent transactions
   3. Place holder text should not have info icon

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/210781432-7836af3e-02be-4bf6-9b7a-f72d6de35a48.png)

## Expected result:
![image](https://user-images.githubusercontent.com/17010094/210781298-63a73cc0-98c2-498c-a953-6a890929db36.png)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

All

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes with 1.47.x onward
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @kleantzogu

**Comment by josheleonard** [comment]
Closing - This icon is no longer shown in the activity views

![Image](https://github.com/brave/brave-browser/assets/30185185/06deb0e5-c43c-46ee-b9c2-eeb5134c238e)


![Image](https://github.com/brave/brave-browser/assets/30185185/74dd7d8d-06cb-4776-81d6-b5afc4a7f53a)
