### ISSUE TITLE
Error message close button should be properly aligned

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#27655]
## Description 

Error message close button should be properly aligned

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/210780870-6eb4dcb7-6fec-4ff3-a550-95d1be28b91e.png)

## Expected result:
Close button should be properly aligned

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.47.164 Chromium: 109.0.5414.74 (Official Build) (64-bit)
-- | --
Revision | `e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}`
OS | Windows 11 Version 22H2 (Build 22621.963)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @jamesmudgett @onyb

**Comment by josheleonard** [comment]
Closing - No longer seeing this alignment issue

![Image](https://github.com/brave/brave-browser/assets/30185185/498cb301-fa5a-456b-ad9e-2ed462877040)
