### ISSUE TITLE
Rename 'Transactions' screen to 'Activity' 

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#27650]
## Description 

Rename 'Transactions' screen to 'Activity' and re-order wallet page tabs to this following order: [Portfolio, NFTs, Activity**, Accounts, Market]

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta  (64-bit) 
-- | --
Revision | `46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}`
OS | Linux

- Verified steps from issue description
- Verified `Transactions` tab is now renamed to `Activity`
- Verified the tabs are in the order of `Portfolio`, `NFTs`, `Activity`, `Accounts`, `Market`
![image](https://user-images.githubusercontent.com/17010094/222140293-82eeafc5-dc3e-495d-aaeb-cddb16256384.png)

---------------------

Verification passed on 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta  (64-bit)
-- | --
Revision | `46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from issue description
- Verified `Transactions` tab is now renamed to `Activity`
- Verified the tabs are in the order of `Portfolio`, `NFTs`, `Activity`, `Accounts`, `Market`
![image](https://user-images.githubusercontent.com/17010094/222140359-6bdaa70e-e5ef-48f2-be46-5f2b5d5f1948.png)

---------------------

Verification passed on 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta  (arm64)
-- | --
Revision | `46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from issue description
- Verified `Transactions` tab is now renamed to `Activity`
- Verified the tabs are in the order of `Portfolio`, `NFTs`, `Activity`, `Accounts`, `Market`
![image](https://user-images.githubusercontent.com/17010094/222140492-88857f42-28de-4cc4-ab5b-691169f5a88a.png)
