### ISSUE TITLE
Follow up to #6690 place tab speaker mute icon setting with other tab settings

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#27662]
## Description 

`Disable mute function in tab speaker icons` setting should be below `Show tab search buttons` and above `Tab hover mode`

## Steps to Reproduce

   1. Use 1.48.53 and higher
   2. Visit brave://settings/appearance and notice setting placement.
   3. Should match expected result.

## Actual result:

<img width="706" alt="Screenshot 2023-01-05 at 9 11 30 AM" src="https://user-images.githubusercontent.com/5951041/210842070-b2922d8d-d64e-4191-84bd-d7a8686d876c.png">

## Expected result:
<img width="1106" alt="206806752-26aee023-92df-4f7c-b450-ce9e14975768" src="https://user-images.githubusercontent.com/5951041/210842121-74b88c72-0b43-4231-94c0-b0d99674ab28.png">

## Reproduces how often: 

easily

## Brave version (brave://version info)

1.48.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.49.117 Chromium: 111.0.5563.50 (Official Build) (x86_64)
-- | --
Revision | 39f3dfc5023fe60997adc4f6cf5439cfa3e6968a-refs/branch-heads/5563@{#903}
OS | macOS Version 12.6.3 (Build 21G419)
```
