### ISSUE TITLE
Use Mint Address for Solana NFT

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-browser#27664]
1. Change `Token Address` to `Mint Address` in add custom token screen when user selects a Solana network
2. Change `Token ID` to `Mint Address` in Solana NFT detail screen. since (1) user wont input token id when they add custom solana NFT and (2) there is no token id coming from Solana NFT metadata.

iOS screenshots
![simulator_screenshot_09DC352D-24ED-4373-A29E-C8535CE4C615](https://user-images.githubusercontent.com/1187676/210882438-bf949968-2b62-4b5b-9ed1-f017b556e688.png)
![simulator_screenshot_C73EB387-B020-4AC7-82BD-A2B498297BAD](https://user-images.githubusercontent.com/1187676/210882456-d1802707-4c94-41c1-977a-6a473120709e.png)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta  (64-bit)
-- | --
Revision | `46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [ brave/brave-core#16730](https://github.com/brave/brave-core/pull/16730)
- Verified selecting Solana Network from network selector updates `Token Address` to `Mint Address`
- Verified the change happens for both custom tokens and NFT's

Ethereum Token | Solana Token
-- | --
![image](https://user-images.githubusercontent.com/17010094/222139597-d783d78d-f107-4771-80f7-bb03c9a60a8b.png) | ![image](https://user-images.githubusercontent.com/17010094/222139636-336a66c7-b7e7-4346-aa0e-b6ffd9703276.png)

Ethereum NFT| Solana NFT
-- | --
![image](https://user-images.githubusercontent.com/17010094/222139528-7a51c54a-5e20-429d-8d4c-b076a9399d4d.png) | ![image](https://user-images.githubusercontent.com/17010094/222139141-7d565a92-b22b-42a9-a5f6-21931cbcc7c1.png)
