### ISSUE TITLE
ENS offchain lookup ask flow does not create transaction

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#27661]
## Description 

ENS offchain lookup during the Ask flow (default) is not creating the transaction. The user must re-enter the send transaction details and tap `Review order` again (or re-enter domain name after tapping `Use ENS domain`).

## Steps to Reproduce
   1. Visit `brave://settings/web3` and make sure `Allow ENS offchain lookup.` is set to `Ask`
   2. Open send view `brave://wallet/send`
   3. Select an ethereum token and enter a value (you must have >0 balance)
   4. Enter `offchainexample.eth` as the to domain
   5. Tap `Use ENS domain`
   6. Tap `Review order`
   7. Observe transaction confirmation not shown, no pending tx available
   8. Re-enter same details & tap 'Review Order'
   9. Observe transaction confirmation shown 

## Actual result:

https://user-images.githubusercontent.com/5314553/210839122-45d71ff9-04ea-4642-9b67-b12466070eff.mov

## Brave version (brave://version info)

Version 1.48.111 Chromium: 109.0.5414.61 (Official Build) nightly (arm64)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.48.126` or higher for `1.48.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.48.132 Chromium: 109.0.5414.87 (Official Build) beta (64-bit) 
-- | --
Revision | `2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}`
OS | Linux

- Verified steps from [brave/brave-core#16549](https://github.com/brave/brave-core/pull/16549)
- Verified ENS offchain lookup is message is shown before resolving the address

https://user-images.githubusercontent.com/17010094/214352149-76b20453-b9be-4dcf-baa9-41f080d782ed.mp4

---------------------

Verification passed on 

Brave | 1.48.132 Chromium: 109.0.5414.87 (Official Build) beta (64-bit)
-- | --
Revision | `2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#16549](https://github.com/brave/brave-core/pull/16549)
- Verified ENS offchain lookup is message is shown before resolving the address

https://user-images.githubusercontent.com/17010094/214352798-caba0333-b5dd-4005-be67-ca8bca772ed9.mp4

---------------------

Verification passed on 

Brave | 1.48.132 Chromium: 109.0.5414.87 (Official Build) beta (arm64)
-- | --
Revision | `2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#16549](https://github.com/brave/brave-core/pull/16549)
- Verified ENS offchain lookup is message is shown before resolving the address

https://user-images.githubusercontent.com/17010094/214353273-22dd0e66-93d1-48c3-9219-736db278da13.mov
