### ISSUE TITLE
Add Ramp network support and remove wyre

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#27678]
## Description 
Add Ramp network support to buy assets and remove wyre option from buy

**Comment by kjozwiak** [comment]
The above requires `1.47.176` or higher for `1.47.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.47.177 x64 build
- Verified steps from [brave/brave-core#16558](https://github.com/brave/brave-core/pull/16558)
- Verified selecting Buy in the quick action shows `Continue to Ramp`
- Verified clicking on `Continue to Ramp` loads the on-ramp page with the selected token prefilled
- Verified if no amount is entered a default value is pre-populated on the on-ramp page
- Verified selecting a token and clicking on Buy button shows `Continue to Ramp` to proceed to purchase
- Verified able to select address in dropdown to change the deposit address on the on-ramp page
- Verified on the on-ramp page can't change the token for which it is pre-populated

Oppo Reno 5 (Android 12) | Lenovo Tab (Android 12)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/213412661-dd0ce3d3-883e-4dd7-b58c-b67b9d94ce3e.mp4> | <video  src=https://user-images.githubusercontent.com/17010094/213411614-4845894a-d5d9-4823-af72-c06fa9eb92fd.mp4>
