### ISSUE TITLE
Support "Copy clean link" menu from the App menu

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#27676]
When users select URL on the web page, text editing menu items are enabled, such as "copy", and "paste" and etc. In this case, we might be able to insert "Copy clean link"

<img width="605" alt="Screen Shot 2023-01-04 at 3 37 25 PM" src="https://user-images.githubusercontent.com/5474642/210498352-760289a6-e4c4-42f2-b1e1-7652240d46b5.png">

**Comment by rebron** [comment]
cc: @fmarier

**Comment by fmarier** [comment]
This also applies to the contextual menu on Windows/Linux. There is code that detects URLs and triggers the "Go to URL" menu item for example when a URL is selected:
![contextual-menu](https://user-images.githubusercontent.com/167821/211084092-b97a6c64-5dc5-48f1-b0e7-d6e18997db57.png)

**Comment by stephendonner** [comment]
macOS has a separate issue here: https://github.com/brave/brave-browser/issues/27902

**Comment by LaurenWags** [comment]
marking as `QA/Blocked` until questions from https://bravesoftware.slack.com/archives/CKNHM4RTK/p1677768069627199 are resolved.

**Comment by LaurenWags** [comment]
Updated labels and confirmed via above slack thread that this is a duplicate of https://github.com/brave/brave-browser/issues/26825.

Since verification notes are under 26825, left that one to be included in release notes for 1.49.x milestone.
