### ISSUE TITLE
Add back speedreader flag and disable SpeedreaderPanelV2

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#27675]
## Description 

Revert for https://github.com/brave/brave-browser/issues/26777 for 1.47.x to add back speedreader flag and disable speedreader panel v2.

**Comment by kjozwiak** [comment]
The above requires `1.47.169` or higher for `1.47.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.47.169 Chromium: 109.0.5414.87 (Official Build) (64-bit)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | Windows 11 Version 21H2 (Build 22000.1455)
```

1. Install `1.47.169`
2. launch Brave
3. closed and relaunched to pull in Griffin seed
4. skip onboarding 
5. opened `brave://settings/appearance`
6. confirmed `Speedreader` setting is disabled by default
7. visited an article on https://www.cnn.com 
8. confirmed `reader mode`  icon was available 
10. clicked the reader mode icon 
11. confirmed  `Do you want to turn on Speedreader?` speedreader V1 panel displayed
12. clicked `Learn more` link in the panel
13. it navigated to https://support.brave.com/hc/en-us/articles/360045031392-What-is-SpeedReader
14. clicked  `Turn on Speedreader` via the panel enables the feature
15. confirmed Speedreader  enabled via brave://settings/appearance
16. visit https://www.bbc.com/news/world-us-canada-64241784 and toggle `Off` the speedreader
17. confirmed speedreader mode is off
18. close Brave and relaunch
19. confirmed speedreader mode is `off` for https://www.bbc.com/news/world-us-canada-64241784 
20. confirmed speedreader mode is `on` for  https://www.cnn.com/2023/01/11/politics/george-santos-nassau-county-resign/index.html 
21. open  brave://settings/appearance and disable `Speedreader` setting
22. confirmed Speedreader mode is off on both `cnn` and `bbc` sites

step 6|step 8|step 11|step 13|step 14|step 15|step 16|step 17|step 19|step 20|step 21|step 22
----|----|----|----|----|----|----|----|----|------|----|------
<img width="468" alt="image" src="https://user-images.githubusercontent.com/98358127/211916765-7013efd2-67a4-4f94-bd15-92567242ce40.png">|<img width="509" alt="image" src="https://user-images.githubusercontent.com/98358127/211926511-3cc05531-a04a-4864-a34c-3f259650ba9c.png">|<img width="505" alt="image" src="https://user-images.githubusercontent.com/98358127/211926748-553805b1-3146-4178-ac5d-466d60ad9a66.png">|<img width="501" alt="image" src="https://user-images.githubusercontent.com/98358127/211927343-d96482a9-bedf-4d8f-b7aa-fcc34e50c836.png">|<img width="467" alt="image" src="https://user-images.githubusercontent.com/98358127/211928150-0a562338-3947-4312-8b4e-27ae7b9a0947.png">|<img width="467" alt="image" src="https://user-images.githubusercontent.com/98358127/211928373-b9cbc5d6-48db-4ea2-924e-e7d13a129acb.png">|<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/211929179-b4b336d2-55ff-46be-84d2-f232d69b75a5.png">|<img width="470" alt="image" src="https://user-images.githubusercontent.com/98358127/211929246-96969155-2ff9-48a3-9a0c-f05094c8edc7.png">|<img width="465" alt="image" src="https://user-images.githubusercontent.com/98358127/211929793-cba5f185-90f2-482a-ab24-799eb1ec8ef2.png">|<img width="466" alt="image" src="https://user-images.githubusercontent.com/98358127/211929757-9c8ffc0c-d9c2-42be-9cd2-c65e4c3164a5.png">|<img width="470" alt="image" src="https://user-images.githubusercontent.com/98358127/211930203-5ad2b019-2e83-4ff9-9471-eabbd676f4c8.png">|<img width="469" alt="image" src="https://user-images.githubusercontent.com/98358127/211930235-a63c06f1-ca7b-446b-9852-ae9c82fff074.png">
