### ISSUE TITLE
Hide wyre buy option (Android)

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#27681]
## Description 
Hide buy/wyre support/option

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 13` using the following build(s):

```
Brave | 1.46.154 Chromium: 108.0.5359.128 (Official Build) (32-bit)
--- | ---
Revision | 1cd27afdb8e5d057070c0961e04c490d2aca1aa0-refs/branch-heads/5359@{#1185}
OS | Android 13; Build/T2B1.221118.006
```

Using the STR/Cases outlined via https://github.com/brave/brave-core/pull/16559#issue-1522887155 & https://github.com/brave/brave-core/pull/16559#issuecomment-1374186654, ensured that the ability to `Buy` tokens using `Wyre` was removed as per the following:

### `Clean Install/New Profile`

**`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------
![Screenshot_20230106-193556](https://user-images.githubusercontent.com/2602313/211122653-88512126-3b18-4272-af93-ef4d7805ee69.png) | ![Screenshot_20230106-193544](https://user-images.githubusercontent.com/2602313/211122661-2aa55dbe-9775-4ac9-b2e1-03443f243c83.png) | ![Screenshot_20230106-193549](https://user-images.githubusercontent.com/2602313/211122665-5baf6844-e20d-4411-a7fe-696fefa74408.png)

### Upgrade from `1.46.146 Chromium: 108.0.5359.128` -> `1.46.154 Chromium: 108.0.5359.128`

**`1.46.146 Chromium: 108.0.5359.128` (before fix/upgrade)**

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------|----------------|----------------|----------------
![Screenshot_20230106-194351](https://user-images.githubusercontent.com/2602313/211123113-106e15f6-600d-40b9-994f-5cac906c6805.png) | ![Screenshot_20230106-194356](https://user-images.githubusercontent.com/2602313/211123246-27528037-80a9-40b4-97a7-d4f3c81b46b7.png) | ![Screenshot_20230106-194403](https://user-images.githubusercontent.com/2602313/211123249-fed4404a-77d4-4126-8d8c-f7b8c42e58d3.png) | ![Screenshot_20230106-194407](https://user-images.githubusercontent.com/2602313/211123252-cdd01f28-dfd9-49f5-8336-f88e34b9f359.png) | ![Screenshot_20230106-194414](https://user-images.githubusercontent.com/2602313/211123255-4fe4e253-423f-4613-9b27-e6faa2288772.png) | ![Screenshot_20230106-194417](https://user-images.githubusercontent.com/2602313/211123260-6e849fe5-5707-4e25-ac23-172635a2979a.png)

**`1.46.154 Chromium: 108.0.5359.128` (after fix/upgrade)**

**`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------
![Screenshot_20230106-194506](https://user-images.githubusercontent.com/2602313/211123218-e2b3a414-d217-4bd6-9472-73c9277910cd.png) | ![Screenshot_20230106-194510](https://user-images.githubusercontent.com/2602313/211123227-5af603cb-9279-4247-98e1-d7f341caa571.png) | ![Screenshot_20230106-194515](https://user-images.githubusercontent.com/2602313/211123230-71208011-c7a5-4aed-b97c-d1396c0215a4.png)

**Comment by Uni-verse** [comment]
in progress on `Samsung Galaxy Tab S7` using version

Brave 1.46.154 Chromium: 108.0.5359.128 (Official Build) (32-bit)
Revision 1cd27afdb8e5d057070c0961e04c490d2aca1aa0-refs/branch-heads/5359@{https://github.com/brave/brave-browser/issues/1185}
OS Android 12; Build/SP2A.220305.013
