### ISSUE TITLE
`Next payment date` is missing until page refresh

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#27683]
## Description 

`Next payment date` is missing until page refresh

This is similar to https://github.com/brave/brave-browser/issues/20715

## Steps to Reproduce

1. install `1.47.164`
2. enable Brave News
3. view @iambrianfung always-present staging ad
4. enable Rewards
5. look at `Next payment date`

Actual:

`Next payment date` is ` ` (`null`)

example | example
---------|---------
<img width="1312" alt="Screen Shot 2023-01-06 at 9 51 52 AM" src="https://user-images.githubusercontent.com/387249/211081254-33fa274a-ad20-4f78-a847-4885483a15ae.png"> | <img width="1312" alt="Screen Shot 2023-01-06 at 9 51 56 AM" src="https://user-images.githubusercontent.com/387249/211081266-5461efca-1dff-4467-92f3-2c57c224258b.png">

Expected:

`Next payment date` is `Feb 7`

<img width="1312" alt="Screen Shot 2023-01-06 at 10 16 34 AM" src="https://user-images.githubusercontent.com/387249/211081309-1f6ce680-a6aa-4964-bdd7-1be901764f27.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.47.164 Chromium: 109.0.5414.74 (Official Build) (x86_64)
-- | --
Revision | e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}
OS | macOS Version 11.7.2 (Build 20G1020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

/cc @tmancey @btlechowski @brave/qa-team @Miyayes

**Comment by tmancey** [comment]
Closing issue as will be resolved by https://github.com/brave/brave-browser/issues/26592
