### ISSUE TITLE
Kaspersky installation error 1073741845

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#2768]
## Description 

Carried over from https://github.com/brave/browser-laptop/issues/15313
> Operating System: Windows 8.1 Pro
System Specs: i3 Processor, 4GB Ram, 64 Bit Processor
>
> While trying to install Brave browser, it is saying "Downloading...installing..." and after half completion it is saying "The install encountered error 1073741845" . The screenshot is:
>
> ![image](https://user-images.githubusercontent.com/32923858/48180686-a2032400-e34a-11e8-94de-f91eaff92c82.png)

**Comment by avndp** [comment]
Still facing the issue. Tried both installer and standalone versions, same error is still repeating and unable to install:
Still, after posting the issue two months before (November 8th, 2018), facing the issue (1st January, 2019)
![image](https://user-images.githubusercontent.com/32923858/50570651-ecd47180-0db8-11e9-8c62-4cc5eb9b3094.png)

**Comment by TheMenda** [comment]
I'm having the same issue. But right after I get the error window, my AV pops up with a Trojan alert from the installers. 
I read some articles and decided to try the browser myself, but facing this situation... yeah. Not going to touch any of this anymore.

**Comment by avndp** [comment]
> 
> 
> I'm having the same issue. But right after I get the error window, my AV pops up with a Trojan alert from the installers.
> I read some articles and decided to try the browser myself, but facing this situation... yeah. Not going to touch any of this anymore.

+1

**Comment by rebron** [comment]
might be related to: https://github.com/brave/brave-browser/issues/1498

**Comment by bronzekenyan** [comment]
I am getting this exact error, "I'm having the same issue. But right after I get the error window, my AV pops up with a Trojan alert from the installers."

who can help us. I have been suing Brave forever. Feeling so frustrated I cant install the latest version after I uninstalled the older one. Can the Brave folks who are brave enough come to our help?

**Comment by avndp** [comment]
> @bronzekenyan, @avndp What Antivirus program is showing up for you guys?

Kaspersky Endpoint Security 10 for Windows 10.2.4.674

**Comment by Brave-Matt** [comment]
This is definitely related to #1498 
We've worked with Kaspersky and they've confirmed that Brave users should no longer get flagged when attempting to download, install or update Brave.
[More info on Community](https://community.brave.com/t/update-on-brave-being-flagged-as-malware-false-positive-by-kaspersky-anti-virus/43152)

**Comment by rebron** [comment]
Closing. Please reopen if we see additional cases.

**Comment by bsclifton** [comment]
related: https://github.com/brave/brave-browser/issues/1498
