### ISSUE TITLE
Websites without RSS feed button appearing on top

### ISSUE THREAD

**Issue by IronMaltese** [brave/brave-browser#27688]
(All of these websites have available RSS feeds on their website)

https://alternativeto.net/news/all/
https://watch.whatever.social/channel/UCUaT_39o1x6qWjz7K2pWcgw
https://areweanticheatyet.com / --> (https://areweanticheatyet.com/feed.rss)
https://blog.ethereum.org/ -->(https://blog.ethereum.org/en/feed.xml)
https://oxen.io/blog/1 -->  (https://oxen.io/feed)
https://odysee.com/@rossmanngroup:a

(also the button should show when the user is on the rss link’s page)

**Comment by mattmcalister** [comment]
Need to consider alternative approaches to RSS autodiscovery if feed is not clearly present
