### ISSUE TITLE
No keyboard shortcuts to re-order tabs (Windows)

### ISSUE THREAD

**Issue by KiaraGrouwstra** [brave/brave-browser#2769]
## Description 

Re-ordering the tabs can only be done with the mouse. There are keyboard shortcuts to change which tab is active, but not to move tabs. Other browsers (such as Firefox on all platforms and Chrome on linux) use the `ctrl-shift-pageup` and `ctrl-shift-pagedown` to move a tab's index up or down.

### Additional Information

This suggestion was originally posted at the old repo: https://github.com/brave/browser-laptop/issues/11310

**Comment by kirkins** [comment]
What version are you on?

I'm on Brave for linux and I can use `ctrl-shift-pageup` and `ctrl-shift-pagedown`.

**Comment by tycho01** [comment]
Count me confused, on another attempt this seems fine for me as well now. :)
> Version 0.57.18 Chromium: 71.0.3578.80 (Official Build) (64-bit)

**Comment by tycho01** [comment]
Actually, while this worked for me on Linux, on Windows I still appear unable to reorder tabs by keyboard.
> Version 0.58.18 Chromium: 71.0.3578.98 (Official Build) (64-bit)

**Comment by bsclifton** [comment]
There are some keyboard shortcuts now which are customizable for moving tabs

Please see brave://settings/system/shortcuts and search `tabs` to check them out

**Comment by hamirmahal** [comment]
I discovered these just now. They're very handy. Thank you to whoever added them.
