### ISSUE TITLE
Make a flag to suppress tab switching with mouse wheel 

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#27694]
On linux, users can switch the active tab with wheel scroll. But for some users, it feels annoying. so it'd be good to have a flag to disable that.

Requested from https://github.com/brave/brave-core/pull/16501#discussion_r1062854235

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.49.118 Chromium: 111.0.5563.50 (Official Build) (64-bit) 
-- | --
Revision | 39f3dfc5023fe60997adc4f6cf5439cfa3e6968a-refs/branch-heads/5563@{#903}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/16575

#### tab scrolling enabled

Steps:
1. Enable brave://flags/#brave-vertical-tabs
1. Enable brave://flags/#brave-change-active-tab-on-scroll-event
1. Open few NTP
1. hover over tab bar and move your mouse wheel

![image](https://user-images.githubusercontent.com/34715963/222789526-f53de294-1d92-4932-87c2-ac0411c5587b.png)

Verified able to switch tabs with mouse wheel

![27694](https://user-images.githubusercontent.com/34715963/222789794-581d4835-7dbf-455d-a0ae-53854d842e11.gif)


#### tab scrolling disabled

Steps:
1. Enable brave://flags/#brave-vertical-tabs
1. Disable brave://flags/#brave-change-active-tab-on-scroll-event
1. Open few NTP
1. hover over tab bar and move your mouse wheel

![image](https://user-images.githubusercontent.com/34715963/222789140-e97c3a5c-443b-4452-ab2a-8ee532cd2562.png)

Verified unable to switch tabs with mouse wheel
