### ISSUE TITLE
Brave shields toggler is not locked on macos

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#27691]
## Description 

Set osx policy to make Brave Shields disabled and check the shields popup toggler, it still can be toggled despite the existence of policies.

## Steps to Reproduce

   1. Set `defaults write com.brave.Browser BraveShieldsDisabledForUrls -array "https://www.example.com/" "https://brave.com/"` policy on macos
   2. Check shields popup on brave.com
   3. Make sure the shields toggler is locked

## Actual result:

the toggler is not locked

## Expected result:
the toggler is  locked

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment]
Not related to this PR - but there seems to be a regression which is making this hard to test.

Toggling for happy path (when domain is not in list and you can toggle)... this does change the toggle state but then it doesn't reload the page. @stephendonner do you know if there is a bug for not reloading page/shields after toggle?

Works as expected on Release (including 1.47 RC); but problem is in both BETA and NIGHTLY.

**Comment by spylogsster** [comment]
> Not related to this PR - but there seems to be a regression which is making this hard to test.
> 
> Toggling for happy path (when domain is not in list and you can toggle)... this does change the toggle state but then it doesn't reload the page. @stephendonner do you know if there is a bug for not reloading page/shields after toggle?
> 
> Works as expected on Release (including 1.47 RC); but problem is in both BETA and NIGHTLY.

fixed it in this PR

**Comment by stephendonner** [comment]
> Not related to this PR - but there seems to be a regression which is making this hard to test.
> 
> Toggling for happy path (when domain is not in list and you can toggle)... this does change the toggle state but then it doesn't reload the page. @stephendonner do you know if there is a bug for not reloading page/shields after toggle?
> 
> Works as expected on Release (including 1.47 RC); but problem is in both BETA and NIGHTLY.

There was not - thanks for fixing @spylogsster !

**Comment by kjozwiak** [comment]
The above requires `1.48.124` or higher for `1.48.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.48.124 Chromium: 109.0.5414.87 (Official Build) beta (x86_64)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | macOS Version 11.7.2 (Build 20G1020)

### Steps:
1. installed `1.48.124`
2. pasted the following into `Terminal`:
```
defaults write com.brave.Browser.beta  BraveShieldsDisabledForUrls -array "https://twitter.com" "https://www.example.com"
``` 
3. loaded `https://twitter.com` and `https://www.example.com`
4. clicked on the Shields icon in the URL bar for each
5. confirmed both Shields status were set to `Disabled` 
6. also confirmed `Settings managed by your organization` notice
7. opened `brave://policy`
8. confirmed appropriate `BraveShieldsDisabledForUrls` entry with the two above sites

`Terminal.app` | `https://twitter.com` | `https://www.example.com` | `brave://policy`
---------------|-----------------------|----------------------------|---------------
<img width="682" alt="Screen Shot 2023-01-12 at 10 09 41 PM" src="https://user-images.githubusercontent.com/387249/212249792-8c3cd06d-46a3-49c2-bca4-c8bcc54002f8.png"> | <img width="1634" alt="Screen Shot 2023-01-12 at 10 07 13 PM" src="https://user-images.githubusercontent.com/387249/212249863-4024c796-2196-4d33-b4f1-9eeea01be518.png"> | <img width="1634" alt="Screen Shot 2023-01-12 at 10 07 26 PM" src="https://user-images.githubusercontent.com/387249/212249891-ee5f2791-d6e6-49b5-b1e1-efdf5ccb8835.png"> | <img width="1778" alt="Screen Shot 2023-01-12 at 10 07 40 PM" src="https://user-images.githubusercontent.com/387249/212249895-aaaaa1db-2042-4a08-a458-726f0023b77a.png">
