### ISSUE TITLE
Update Auto-Contribute section text on brave://rewards and remove disabled state icon and additional text (Jan 2023)

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#27690]
## Description

- [ ] In disabled state, remove the icon and extra accompanying text (see "disabled state" screenshot below).
- [ ] Change base description text to the following: 

**Current:**

>An automatic way to support publishers and content creators. Set a monthly payment and browse normally. The Brave Verified sites you visit will receive your contributions automatically, based on your attention as measured by Brave.

**New:**

>An automatic way to support sites and content creators. Set a monthly contribution amount and browse normally. [Verified sites and creators](https://creators.brave.com) you visit will receive contributions from you each month, based on the amount of time you spend on their content.

**Disabled state:**

![image](https://user-images.githubusercontent.com/11497541/211885303-19a34dd4-395e-4658-94d8-c6d57cf4986a.png)

## Test Plan:

1. Open Brave and navigate to brave://rewards
2. If not yet done so, join Rewards and connect to wallet provider
3. See Auto-Contribute section and check for the above text change
4. Toggle Auto-Contribute switch and verify that in the disabled state the icon and additional text in the image above are not shown.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.49.92 Chromium: 110.0.5481.77 (Official Build) beta (x86_64)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | macOS Version 12.6.3 (Build 21G419)
```

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Samsung Galaxy Version 12` running `Bravemonoarm64.apk_1.49.116`
