### ISSUE TITLE
Updates to "All Accounts" filter on wallet

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#27705]
Remove grey dot on "All Accounts", should also be "All accounts"

![Image](https://user-images.githubusercontent.com/318119/211375958-c523fed6-8b9e-4e6b-8184-41d0b4e92a16.png)
![Image](https://user-images.githubusercontent.com/318119/211375957-55d9c7e0-7d98-49e1-a197-56a23b64439d.png)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta  (64-bit) 
-- | --
Revision | `46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}`
OS | Linux

- Verified steps from [brave/brave-core#16584](https://github.com/brave/brave-core/pull/16584)
- Verified `All accounts` doesn't have an `orb` shown next to it
- Verified `Accounts` is now `accounts`
![image](https://user-images.githubusercontent.com/17010094/221650382-c3991caf-2755-4ac3-902e-11b8650ac703.png)


---------------------

Verification passed on 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta  (64-bit)
-- | --
Revision | `46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#16584](https://github.com/brave/brave-core/pull/16584)
- Verified `All accounts` doesn't have an `orb` shown next to it
- Verified `Accounts` is now `accounts`
![image](https://user-images.githubusercontent.com/17010094/221650793-2a979d28-4dda-4565-9202-0785634f4f4a.png)

---------------------

Verification passed on 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta  (arm64)
-- | --
Revision | `46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#16584](https://github.com/brave/brave-core/pull/16584)
- Verified `All accounts` doesn't have an `orb` shown next to it
- Verified `Accounts` is now `accounts`
![image](https://user-images.githubusercontent.com/17010094/221651003-a45defe5-6622-4272-99ea-bff18270aeb3.png)
