### ISSUE TITLE
permission expiration (notifications, location) not being respected on certain sites like reddit.com

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#27703]
## Description 

Per https://github.com/brave/brave-browser/issues/26376#issue-1427845948, was verifying permission expiration for notifications, location, etc and noticed that on reddit.com, the notification permission expiration isn't being respected. However, this isn't specific to C109 versions, it is also occurring on released version 1.46.x.

Permission expiration on other sites works fine (browserleaks.com/geo, https://pushalert.co/demo, https://cleverpush.com/en/test-notifications/, etc).

## Steps to Reproduce

   1. Clean profile either 1.46.x (current release) or 1.47.x (RC)
   2. Close/relaunch to pull griffin
   3. Visit [reddit.com](http://reddit.com/)
   4. On the notification permission prompt select "Until I close this site" and either block or allow.
   5. Close the tab with reddit
   6. Open a new tab and navigate to [reddit.com](http://reddit.com/)
   7. No prompt for notification permission
   8. You can try with other options (24h, 1 week) but those don't work either

Note, if you use one of the sites I listed in the description instead of reddit.com, the permission expiration works fine.

## Actual result:

No permission prompt on reddit

## Expected result:

permission prompt

## Reproduces how often: 

easily

## Version/Channel Information:

- Can you reproduce this issue with the current release? 1.46.x yes, 1.47.x yes
- Can you reproduce this issue with the beta channel? 1.48.x yes
- Can you reproduce this issue with the nightly channel?  1.49.x yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
@MadhaviSeelam and I noticed that if you clear cookies on reddit, you get the permission prompt.

**Comment by btlechowski** [comment]
Likely the site is not showing the permission prompt.

**Comment by pes10k** [comment]
is the issue is reddit just not re-asking for the permission (possibly bc its setting some value in local storage or similar saying the site has already asked).  If so, I dont think this is a bug

**Comment by LaurenWags** [comment]
@pes10k yep - I just wanted to flag in case this was problematic (i.e. someone says allow until I close the site, but then doesn't get re-prompted after closing the site).

**Comment by pes10k** [comment]
gotcha gotcha, thanks @LaurenWags ! I think this can be closed then

**Comment by LaurenWags** [comment]
closing per above from @pes10k - thanks for taking a look 😄

**Comment by goodov** [comment]
For similar issues, please refer to the browser permissions list (`brave://settings/content/notifications` for ex.) to check if the permission is still active or if it has actually deleted (expired) as intended.
