### ISSUE TITLE
Update search engine default for IN

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#27709]
## Description 
Update search engine default for India:

- India (IN)

Brave should be at the top of the drop down list at brave://settings/search

Related: https://github.com/brave/brave-browser/issues/18331, https://github.com/brave/brave-browser/issues/23814, and https://github.com/brave/brave-browser/issues/26181

### Region set to IN
1. Fresh profile
2. Default search engine SHOULD be Brave
3. Visit brave://settings/searchEngines
4. Brave SHOULD be first in the `Default search engines` list

### Region set to anything else (excluding CA / DE / FR / GB / US / AT / ES / MX / BR / AR)
1. Fresh profile
2. Default will NOT be Brave Search
3. Visit brave://settings/searchEngines
4. Brave SHOULD be first in the `Default search engines` list - unless you're in a region where Yandex is default (AM, AZ, BY, KG, KZ, MD, RU, TJ, TM, UZ). In that case it will be second.

### Notes for test plan
https://github.com/brave/brave-browser/issues/23814#issuecomment-1195841652

**Comment by deeppandya** [comment]
Thanku ou @spylogsster for working on this issue. 
This issue doesn't have android onboarding changes. I will address it in a separate issue.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.49.101 Chromium: 110.0.5481.104 (Official Build) beta (64-bit)
-- | --
Revision | 46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}
OS | Windows 11 Version 22H2 (Build 22621.1265)
```

Test Case 1: Region set to IN

Case 1: Fresh Install
<details>

1. Install 1.49.101
2. launch Brave
3. open a new tab page
4. navigate to `brave://settings/search`
5. confirmed `Brave` was selected as the default for `Normal window/Private Windows`
6. confirmed `Brave` was the first search engine in the dropdown list in brave://settings/search` for Normal window`
7. verified `Brave` was the first search engine in the dropdown list in brave://settings/search` for Private Window` as expected
8. open a new-tab and navigate to `brave://settings/searchEngines` 
9. confirmed `Brave (Default)` shows first in the Search engines list 
10. verified 1st populated result in the URL bar is the `Brave search` as expected when searched by `brave` string
11. press return/enter after entering `brave` in the URL bar
12. verified Brave Search results page is shown with `Help improve Brave Search by ..` banner as expected


step 5 | step 6| step 7 | step 9 | step 10 | step 12
------ | ------ | ------ | ------| ------- | -------
<img width="470" alt="image" src="https://user-images.githubusercontent.com/98358127/219755598-a6b12024-078d-42c1-b2b5-6f4bc1a04737.png">|<img width="472" alt="image" src="https://user-images.githubusercontent.com/98358127/219755840-a0d6eead-55b1-4396-b4e1-430a766bc22e.png">|<img width="461" alt="image" src="https://user-images.githubusercontent.com/98358127/219755935-666a8f04-82c2-414b-aec2-53d08dccaf3f.png">|<img width="462" alt="image" src="https://user-images.githubusercontent.com/98358127/219756575-e0e66e52-7cda-49d9-8685-bc054a90ac29.png">|<img width="449" alt="image" src="https://user-images.githubusercontent.com/98358127/219757374-508ef9c5-1525-4d89-b232-43e5c0129904.png">|<img width="464" alt="image" src="https://user-images.githubusercontent.com/98358127/219757498-1cb28978-3adf-42b7-8cd1-3d16e24c2ff9.png">
</details>

Case 2: Upgrade 
<details>

1. Install 1.48.167
2. launch Brave
3. open brave://settings/search
4. verified `Google` is shown as expected for Normal Window
5. verified `Google(Default` is shown as expected in brave://settings/searchEngines` 
6. close the browser and rename the profile to beta
7. install 1.49.101
8. relaunch Brave 


step 1 | step 4 | step 5
-----|-----|-------
<img width="618" alt="image" src="https://user-images.githubusercontent.com/98358127/219759298-bc90f9be-1ac5-40b9-835b-72b8352a83d7.png">|<img width="419" alt="image" src="https://user-images.githubusercontent.com/98358127/219758757-2973ac59-643c-4120-9839-032709ad0cce.png">|<img width="614" alt="image" src="https://user-images.githubusercontent.com/98358127/219759042-f3c252f5-00b1-4857-9259-c8b42e9320b9.png">

</details>

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.49.100 Chromium: 110.0.5481.100 (Official Build) beta (x86_64)
-- | --
Revision | 4be7a36f7cb943af6118e449bbab494b43dcaddd-refs/branch-heads/5481_77@{#14}
OS | macOS Version 12.6.3 (Build 21G419)
```

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.49.114 Chromium: 110.0.5481.177 (आधिकारिक बिल्ड) beta (64-बिट) 
पुनरीक्षण	f34f7ab2d4ca4ad498ef42aeba4f4eb2c1392d63-refs/branch-heads/5481@{#1239}
OS	Linux
```

Note, per https://github.com/brave/brave-browser/issues/27709#issue-1526349068 have modeled the below based on https://github.com/brave/brave-browser/issues/23814#issuecomment-1195841652

### IN (India) locale 

<details>
<summary>Clean Profile - InProgress</summary>

* ensured that `Brave` was selected as the default for both Normal/Private windows via `brave://settings/search`
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Private` windows
* ensured that `Brave` was selected as the default via `brave://settings/searchEngines`

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|-----------------|---------------|---------------|---------------

</details>

<details>
<summary>Updated Profile (Google/Google - default SE) - TBD</summary>

* installed `1.48.x`
* ensured that `Google` was the default SE selected under `brave://settings/search` for Normal Windows
* changed `Brave` to `Google` for default SE for Private Windows
* updated to `1.49.x` and ensured that `Google` is still the default SE in both Normal and Private windows SE
  * ensured that it wasn't replaced by `Brave`
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Private` windows

**`1.48.164 Chromium: 110.0.5481.100`** | **`1.49.100 Chromium: 110.0.5481.100`**
--------------------------------------------|----------------------------------------------

**`Example (Brave at top of list)`** | **`Example (Brave at top of list)`** | **`Example (Brave at top of list)`**
--------------------------------------|-----------------------------------------|-----------------------------------------

</details>

<details>
<summary>Updated Profile (Startpage/DDG - modified SE) - TBD</summary>

* installed `1.48.x`
* Selected `Startpage` as the default SE selected under `brave://settings/search` for Normal Windows
* Left `Brave` as the default SE for Private Windows
* updated to `1.49.x` and ensured that previously selected SE is still the default for both Normal and Private windows
  * Normal Windows = `Startpage` and Private Windows = `Brave`
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Private` windows
* ensured that `Brave` was the first engine via the list under `brave://settings/searchEngines`

**`1.48.164 Chromium: 110.0.5481.100`** | **`1.49.100 Chromium: 110.0.5481.100`**
--------------------------------------------|----------------------------------------------

**`Example (Brave at top of list)`** | **`Example (Brave at top of list)`** | **`Example (Brave at top of list)`**
--------------------------------------|-----------------------------------------|-----------------------------------------

- Install `1.48.x`
- Open brave://settings/search and ensure that `Google` is the default SE for both Normal and `Brave` is default for Private windows
- Change the SE to `Startpage` in Normal windows SE dropdown
- Change the SE to `DDG` in Private windows SE dropdown
- Upgrade the profile to `1.49.x`
- Ensured that `Startpage` was the default SE selected under `brave://settings/search` for Normal windows
- Ensured that `DDG` was the default SE selected under `brave://settings/search` for Private windows

**`1.48.164 Chromium: 110.0.5481.100`** | **`1.49.100 Chromium: 110.0.5481.100`**
--------------------------------------|-----------------------------------------

- ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Normal` windows
- ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Private` windows
- ensured that `Brave` was the first engine via the list under `brave://settings/searchEngines`

**`Example (Brave at top of list)`** | **`Example (Brave at top of list)`** | **`Example (Brave at top of list)`**
--------------------------------------|-----------------------------------------|-----------------------------------------

</details>

<details>
<summary>Updated Profile (Bing/Qwant - modified SE) - TBD</summary>

* installed `1.48.x`
* Selected `Bing` as the default SE selected under `brave://settings/search` 
* Left `Brave` as the default SE for Private Windows
* updated to `1.49.x` and ensured that previously selected SE is still the default for Normal and Private windows
  * Normal Windows = `Bing` and Private Windows = `Brave`
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Normal` windows
* ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Private` windows
* ensured that `Brave` was the first engine via the list under `brave://settings/searchEngines`

**`1.48.164 Chromium: 110.0.5481.100`** | **`1.49.100 Chromium: 110.0.5481.100`**
--------------------------------------------|----------------------------------------------

**`Example (Brave at top of list)`** | **`Example (Brave at top of list)`** | **`Example (Brave at top of list)`**
--------------------------------------|-----------------------------------------|-----------------------------------------

- Install version `1.48.x`
- Open brave://settings/search and ensure that `Google` is the default SE for Normal windows
- Ensured `Brave` is the default SE for Private windows
- Change the SE to `Bing` in Normal windows SE dropdown
- Change the SE to `Qwant` in Private windows SE dropdown
- Rename the profile to Release channel and upgrade the profile to `1.49.x`
- Ensured that `Bing` was the default SE selected under `brave://settings/search` for Normal windows
- Ensured that `Qwant` was the default SE selected under `brave://settings/search` for Private windows

**`1.48.164 Chromium: 110.0.5481.100`** | **`1.49.100 Chromium: 110.0.5481.100`**
--------------------------------------|-----------------------------------------

- ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Normal` windows
- ensured that `Brave` was the first engine via the drop down list under `brave://settings/search` for `Private` windows
- ensured that `Brave` was the first engine via the list under `brave://settings/searchEngines`

**`Example (Brave at top of list)`** | **`Example (Brave at top of list)`** | **`Example (Brave at top of list)`**
--------------------------------------|-----------------------------------------|-----------------------------------------

</details>

------------------

**Comment by kjozwiak** [comment]
We shouldn't have removed `OS/Android` from the above as this was also implemented on `Android` by @deeppandya. Thankfully it was partially verified via https://github.com/brave/brave-browser/issues/28656#issuecomment-1457761115 on `OS/Android`. @spylogsster please don't remove `OS` labels in the future if you're not sure. QA or the release team can always remove it if not applicable.
