### ISSUE TITLE
Brave (RC v0.58.18) Shields settings not respected by several domains

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#2770]
## Description 
I’m seeing a lot of Shields config. issues in RC v0.58.18. Not sure if this is the exact issue or if it’s related to this one: https://github.com/brave/brave-browser/issues/2190

:point_up: That’s the only issue I can find that describes what I’m seeing. Essentially Shields settings don’t seem to be taking effect for a good number of sites. Several sites (examples below) that have something blocked by Shields (and thus lack some functionality) cannot be fixed by altering site-level Shields for the domain ( Shields = Off), adjusting individual Shields panel settings, or Global Shields settings.

In addition to the obvious problem that users are unable to access/use some sites because of this, it's also causing a lot of confusion with newer users who aren't versed in Shields concepts.

All of the tests were performed on Mac and I was able to repro them in Win10 as well. I've provided several examples/sites that show this behavior but there's likely more effected by it.

## Steps to Reproduce

   1.  Visit one of the sites listed in my examples (again, could be any site but for the sake of reproducibility its probably easiest to use one of the domains I've confirmed).
   2. Attempt to adjust Shields panel/Global Shields settings and/or disabling Shields to fix [some website function]
   3. Perform the same test in Dev/Beta builds (and/or in chrome)

## Actual result:

Changes in Shields configuration are not respected, site will continue to display with broken elements or functionality.

## Expected result:
Disabling Shields or finding ideal tuning for the site should restore site functionality as intended.

## Reproduces how often: 

Always

## Brave version (brave://version info)

Win10 and macOS
Release Channel build, version 0.58.18

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
No 
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? No

### Additional Information
Examples of sites with this behavior:
![hulu2](https://user-images.githubusercontent.com/3299098/50569464-b516ec80-0d1a-11e9-8c1d-8a4e4edd2b3e.gif)
![ignvid](https://user-images.githubusercontent.com/3299098/50569466-bb0ccd80-0d1a-11e9-99a4-f29e0da39cdf.gif)
![image 1](https://user-images.githubusercontent.com/3299098/50569468-bfd18180-0d1a-11e9-8afd-8e2a08920a79.png)
![nbc](https://user-images.githubusercontent.com/3299098/50569470-c52ecc00-0d1a-11e9-8e62-8848298e2836.gif)
![netflixfail](https://user-images.githubusercontent.com/3299098/50569472-c829bc80-0d1a-11e9-9bcb-5acbd64f8552.gif)
![apv](https://user-images.githubusercontent.com/3299098/50569475-d972c900-0d1a-11e9-95c1-8b3ee09825b5.gif)

**Comment by avndp** [comment]
+1

**Comment by Brave-Matt** [comment]
![imgur](https://user-images.githubusercontent.com/3299098/50605088-12738080-0e76-11e9-8152-c46ea2cbfd60.gif)

**Comment by Brave-Matt** [comment]
Turns out this was due to a corrupt profile. It's unclear what caused it, but after creating a new profile I was able to resume normal site function in Release. 

@bsclifton is examining data pulled from the corrupted profile to find possible causes.

**Comment by bsclifton** [comment]
@Brave-Matt I was unable to load the profile you shared. You can DM me with another copy if you're still seeing this issue. We did land a major CORS fix in 0.58.21... that should have helped in general. But that wouldn't explain problems with shields

Need more info to investigate

**Comment by rebron** [comment]
Closing as stale.
