### ISSUE TITLE
NewTabPage add observer to wrong TemplateUrlServiceFactory when switching tab model

### ISSUE THREAD

**Issue by wchen342** [brave/brave-browser#27711]
## Description 
Under certain circumstances, for example switching from a private tab to a newly created normal tab and immediately do a search, the NTP add itself as an observer to `TemplateUrlServiceFactory` with a wrong profile.

## Steps to reproduce 

See https://github.com/brave/brave-browser/issues/27651.

## Actual result 
Crash

## Expected result
No crash

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
1.49.x

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

The root cause of https://github.com/brave/brave-browser/issues/27572 and https://github.com/brave/brave-browser/issues/27651.

**Comment by Uni-verse** [comment]
Verified on `Samsung GS 21` using version: 

```
Brave	1.49.118 Chromium: 111.0.5563.50 (Official Build) (64-bit) 
Revision	39f3dfc5023fe60997adc4f6cf5439cfa3e6968a-refs/branch-heads/5563@{#903}
OS	Android 13; Build/TP1A.220624.014
```

Spot checked STR in https://github.com/brave/brave-browser/issues/27651#issue-1519763069 as well as the test plan is https://github.com/brave/brave-core/pull/16588#issue-1526414179 and ensured crash in not reproducible when searching. 


https://user-images.githubusercontent.com/17885425/223768684-8a26daf4-d84f-49a2-80bd-fe399eca8af5.mp4
