### ISSUE TITLE
Trezor allow keys popup doesn't show up when approving transaction and doesn't trigger approval on the device

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#27726]
## Description 

Trezor allow keys popup doesn't show up when approving transaction and doesn't trigger approval on the device

## Steps to Reproduce

   1. Install CR 109 build 1.47.168
   2. Submit a send transaction from Trezor account 
   3. Allow key popup for Trezor doesn't show up which causes the transaction approval to not show up on device and hence you can't submit the transaction

## Actual result:

https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1673368917533359

## Expected result:
Popup window should show which triggers the access to private keys for the device to show transaction approval screen 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.47.168 Chromium: 109.0.5414.87 (Official Build) (64-bit)
-- | --
Revision | `2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}`
OS | Windows 11 Version 22H2 (Build 22621.963)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Maybe 
- Can you reproduce this issue with the nightly channel? Maybe 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel @spylogsster

**Comment by kjozwiak** [comment]
The above requires `1.47.169` or higher for `1.47.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.47.164 Chromium: 109.0.5414.87 (Official Build) (64-bit)
-- | --
Revision | `2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}`
OS | Linux

- Verified steps from issue description and [brave/brave-core#16602](https://github.com/brave/brave-core/pull/16602)
- Verified approve public key popup is shown allowing it to approve transaction on the device
- Verified able to successfully approve a transaction from Trezor device

https://user-images.githubusercontent.com/17010094/211855178-8c9b51d9-ee7a-4020-8ea1-5d9e5c4e5787.mp4

---------------------

Verification passed on 

Brave | 1.47.164 Chromium: 109.0.5414.87 (Official Build) (64-bit)
-- | --
Revision | `2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from issue description and [brave/brave-core#16602](https://github.com/brave/brave-core/pull/16602)
- Verified approve public key popup is shown allowing it to approve transaction on the device
- Verified able to successfully approve a transaction from Trezor device

https://user-images.githubusercontent.com/17010094/211856209-864250c3-7e55-4eff-9efe-925419cf52b6.mp4

---------------------

Verification passed on 

Brave | 1.47.169 Chromium: 109.0.5414.87 (Official Build) (arm64)
-- | --
Revision | `2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from issue description and [brave/brave-core#16602](https://github.com/brave/brave-core/pull/16602)
- Verified approve public key popup is shown allowing it to approve transaction on the device
- Verified able to successfully approve a transaction from Trezor device

https://user-images.githubusercontent.com/17010094/211857259-2b692d0c-e394-4465-b4bb-0e44b9a56247.mov
