### ISSUE TITLE
Header fixes for Google Sign-In Permission

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#27723]
The PR for https://github.com/brave/brave-browser/issues/26273 had to be reverted because of header issues that were not caught by CI/tooling. This issue is for follow-up fixed-up PR.

**Comment by LaurenWags** [comment]
@brave/qa-team please ping @LaurenWags or @ShivanKaul for spec for further details 👍🏻

**Comment by LaurenWags** [comment]
Per discussion in https://bravesoftware.slack.com/archives/C6YNM6Y5S/p1676057668806049?thread_ts=1675971598.530879&cid=C6YNM6Y5S, changing this to `QA/No` and `release-notes/exclude` as it will be covered for testing with https://github.com/brave/brave-browser/issues/28440 in 1.50.x milestone.
