### ISSUE TITLE
SiteRemovalNotification isn't disappeared w/o explicit user closing

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#2772]
SiteRemovalNotification isn't disappeared after reloading, creating new tab or browser restart.
It is only disappeared when user explicitly closes it.

<img width="548" alt="screen shot 2019-01-01 at 3 33 13 pm" src="https://user-images.githubusercontent.com/6786187/50570834-e0164480-0ddd-11e9-8a86-0cc5d9a5c3ba.png">

## Steps to Reproduce

   1.  Remove thumbnail
   2. Thumb Removed notification is visible
   3. Try new tab reloading, new tab creation or browser restart

## Actual result:

Thumb Removed notification is visible

## Expected result:
Thumb Removed notification should be hidden

## Reproduces how often: 

Always

## Brave version (brave://version info)

Latest stable/beta/dev/nightly

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
yes
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 
no

**Comment by simonhong** [comment]
If this is intended behavior, please close this.

**Comment by rebron** [comment]
cc: @rossmoody can you take a look?

**Comment by rossmoody** [comment]
That's interesting. Muon behavior was for it to persist until closed inside the NTP you are currently in but not carry over to new ones. This is a little out of my troubleshooting comfort zone so gonna tag in @cezaraugusto.

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.61.37 Chromium: 73.0.3683.39 (Official Build) beta (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

Used test plan from https://github.com/brave/brave-core/pull/1194
