### ISSUE TITLE
Open the connect panel when the same origin requests to connect more than once

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#27729]
When a dapp calls `window.solana.connect()` or `window.ethereum.enable()` more than once, the subsequent request throws:
`Uncaught (in promise) {code: 4001, message: 'The user rejected the request.'}`

It would be nice to still throw the error for that second request, but for the user open up the panel so they can see the request. 
Here's a use case Loom where that shows a user clicking on Connect in a dapp twice and trying to get back to the panel:
https://www.loom.com/share/92b39f2fd0224ba69fd5e694e89511f1

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.57.18 Chromium: 115.0.5790.98 (Official Build) beta (64-bit)
-- | --
Revision | `d515871a6c6df7d2843e755c8b7dda9b744f26d6`
OS | Windows 11 Version 22H2 (Build 22621.1992)

- Verified steps from issue description
- Verified connect panel throws error when rejected for the same origin

https://github.com/brave/brave-browser/assets/17010094/57a892da-1d5e-41c3-87cc-5194251d6226
