### ISSUE TITLE
Sent answers count P3A metric can be incorrect

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#27739]
## Description 

The `Brave.P3A.SentAnswersCount` metric may contain an incorrect value. In many cases, users that have submitted 10+ metrics will report 0 for this metric.

It is suspected that any build that includes the new NTP SI reporting will be affected (1.45+).

Rephrased metric description: "How many weekly questions did the browser send in the previous week?"

## Steps to Reproduce

   1. Launch browser, wait several minutes, verify metrics have been sent via local state page.
   2. Close browser, move system time forward by 7 days, open browser, open local state page.

## Actual result:

Metric value will probably be 0.

## Expected result:

Metric value should reflect the number of metrics sent in the previous week. If it was 10+, the answer should be 3.

**Comment by GeetaSarvadnya** [comment]
"sent": true | Brave.P3A.SentAnswersCount
-------|-------
![image](https://user-images.githubusercontent.com/38657976/220335734-143741f5-afce-4261-92d7-57500bf271ed.png) | ![image](https://user-images.githubusercontent.com/38657976/220335854-5b00c397-0d01-4738-aa74-1bd0ff441b20.png)
