### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by xenothales** [brave/brave-browser#27734]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.46.153  Chromium: 108.0.5359.128
Operating System: Mac OS X 13.1.0

URL (if applicable) where crash occurred:
brave://settings/braveSync/setup
Can you reproduce this crash?
Yes
What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Open "Sync" from "Settings" page
2. Click on "Manage your synced devices"
3. Click on "Add New Device"
4. Prompt will appear for fraction of a second before Brave crashes
Note: Sync chain originated from this device (Macbook) and contains no other devices 

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/b6510600-2ad7-6b09-0000-000000000000

**Comment by AlexeyBarabash** [comment]
Link to backtrace https://brave.sp.backtrace.io/p/brave/debug?time=all&filters=(_rxid%3Db6510600-2ad7-6b09-0000-000000000000)&debug=(%22435a7d6%22,0,0)

**Comment by AlexeyBarabash** [comment]
We need to uplift https://github.com/brave/brave-core/pull/16378 to fix it on 1.47.x

**Comment by AlexeyBarabash** [comment]
Original thread on reddit: https://www.reddit.com/r/brave_browser/comments/107qu6a/sync_not_working_on_ios_and_macos/

**Comment by AlexeyBarabash** [comment]
Similar to https://github.com/brave/brave-browser/issues/27734

**Comment by kjozwiak** [comment]
@AlexeyBarabash going to close this one off and label it was `QA/No` & `release-notes/exclude` as we'll be using https://github.com/brave/brave-browser/issues/27343 as the main issue for verification. Also moving into the correct milestone after closing.
