### ISSUE TITLE
[Android] "Error: Limited Uphold Account Functionality" notification isn't shown for `Insufficient capabilities` case

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#27743]
## Description 

"Error: Limited Uphold Account Functionality" notification isn't shown for `Insufficient capabilities` case
## Steps to reproduce 

   1. Follow the steps for `Insufficient capabilities` case under `New Uphold notifications` https://github.com/brave/brave-browser/issues/24251#issuecomment-1375787294
  
## Actual result 

 "Error: Limited Uphold Account Functionality" notification is not shown on the BR panel for `Insufficient capabilities` case

## Expected result

**Desktop**

![image](https://user-images.githubusercontent.com/38657976/211785951-3f1e7398-5dcf-4f5d-be74-5a70ed0cd8c5.png)

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): all
   - Android version: 12
   
## Brave version
1.47.165

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

CC: @brave/qa-team @Miyayes @deeppandya

**Comment by LaurenWags** [comment]
@Miyayes @deeppandya looks like this notification used to be a modal (see https://github.com/brave/brave-browser/issues/23849 for 1.42.x) but with this version is now a panel notification. Could be the reason it's not showing.

**Comment by deeppandya** [comment]
@LaurenWags we used to show the same modal on brave:rewards page after the verification. It seems to be new. I will look into it

**Comment by Miyayes** [comment]
In this Android case, make sure to implement these toast notifications.

**Comment by Miyayes** [comment]
According to Deep, this should be fixed in 1.48.x.

**Comment by LaurenWags** [comment]
Verification in progress on Google Pixel 3 XL with Android 12 running 1.48.152.
