### ISSUE TITLE
Placeholder text on brave widget doesn't update when changing default SE

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#27749]
## Description 
Placeholder text on brave widget doesn't update when changing default SE

## Steps to reproduce 

   1. Install 1.47
   2. Open 3-dot menu -> settings -> Home screen widget
   3. Tap `Add` to add widget to device home screen
   4. Background brave app, confirm placeholder text on brave widget references current SE 
   5. Open SE settings and change SE
   6. Background brave app again, check placeholder text on brave widget

## Actual result 
![screenshot-1673455054178](https://user-images.githubusercontent.com/17885425/211865722-a0a69a4d-fcd7-4230-a8ad-b3e503f44925.png)

## Expected result
Brave widget should be re-added to home screen with updated SE selected for search

## Issue reproduces how often 
Easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung GS 21
   - Android version: 12
   
## Brave version
`1.47.168, Chromium 109.0.5414.87`

**Comment by kjozwiak** [comment]
The above requires `1.47.178` or higher for `1.47.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version:

```
Brave	1.47.181 Chromium: 109.0.5414.87 (Official Build) (64-bit) 
Revision	2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS	Android 13; Build/TP1A.220624.014
```
STR: https://github.com/brave/brave-browser/issues/27749#issue-1529369172

- Verified changing default SE in search settings will update immediately

Example | Example | Example
-|-|-
![screenshot-1674495908836](https://user-images.githubusercontent.com/17885425/214112121-5efeeec1-1f54-4bc4-8dbe-5c5d5fec7d8d.png) | ![screenshot-1674495895735](https://user-images.githubusercontent.com/17885425/214112118-b4081fc7-d49e-4ecf-b6e5-13c9a5e13ff6.png) | ![screenshot-1674495863538](https://user-images.githubusercontent.com/17885425/214112104-41c7ebaf-cea0-4747-ab41-02c8960219cb.png)
