### ISSUE TITLE
[Android] "Error: BAT unavailable" notification isn't shown for `BAT not allowed` case

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#27742]
## Description 
"Error: BAT unavailable" notification isn't shown for `BAT not allowed` case

## Steps to reproduce 

   1.  Follow the steps for `BAT not allowed` case under `New Uphold notifications` https://github.com/brave/brave-browser/issues/24251#issuecomment-1375787294
  
## Actual result 
"Error: BAT unavailable" notification is not shown on the BR panel for `BAT not allowed` case

## Expected result
`BAT not allowed` notification from Desktop
![image](https://user-images.githubusercontent.com/38657976/211787437-77f3b7c1-5529-4597-aea1-cb8a222d3c0a.png)

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: 12
   
## Brave version

1.47.165
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

CC: @brave/qa-team @Miyayes @deeppandya

**Comment by LaurenWags** [comment]
@Miyayes @deeppandya another panel notification - probably wasn't implemented on Android.

**Comment by Miyayes** [comment]
Deep says this should be resolved in 1.48.x. We should check there.

**Comment by LaurenWags** [comment]
Verification in progress on Google Pixel 3 XL with Android 12 running 1.48.152.
