### ISSUE TITLE
ROS Answers crashes Brave

### ISSUE THREAD

**Issue by piresmicael** [brave/brave-browser#27745]
## Description 
Brave browser crashes upon opening of any page from https://answers.ros.org/ . The website works fine in other browsers (Chrome, Firefox, LibreWolf, Brave version 1.46.144 and android version of Brave)

## Steps to Reproduce

   1. Open any page from https://answers.ros.org/

## Actual result:
Brave crashes

## Expected result:
Browsing https://answers.ros.org/

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

Brave | 1.46.153 Chromium: 108.0.5359.128 (Official Build) (64-bit)
Revision | 1cd27afdb8e5d057070c0961e04c490d2aca1aa0-refs/branch-heads/5359@{#1185}
OS | Linux

**Comment by rebron** [comment]
Hi @piresmicael. When you get a chance can you update to 1.47.171 and let us know if you're still experiencing the crash.

**Comment by piresmicael** [comment]
> Hi @piresmicael. When you get a chance can you update to 1.47.171 and let us know if you're still experiencing the crash.

It appears the bug has been fixed, thank you!
