### ISSUE TITLE
Remove Uphold equities promo card

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#27759]
## Description

Remove: https://github.com/brave/brave-core/blob/master/components/brave_rewards/resources/page/lib/promotions.ts#L86

Was implemented as part of: https://github.com/brave/brave-core/pull/6951/files (https://github.com/brave/brave-browser/issues/12276). 

**Question:** Can we also check under what conditions this promo card even appears?

## Test Plan:

See https://github.com/brave/brave-browser/issues/12276#issuecomment-723284073 and ensure that the card is not shown in the countries noted in the comment.

**Comment by kjozwiak** [comment]
The above requires `1.47.176` or higher for `1.47.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.47.177 Chromium: 109.0.5414.87 (Official Build) (64-bit)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | Windows 11 Version 21H2 (Build 22000.1455)
```
Install 1.47.177
launch Brave
Change locales from the [list](https://github.com/brave/brave-core/pull/6982/files#diff-6b6ed7044cbb83bc4e57c74f9d946505e033ec70915527c7d525351b0a4c8e48) to test 
enable rewards
open brave://rewards  

Confirmed that the  `Uphold Equities Card` is not shown 

Cayman Islands
example|1.47.177
-----|-----
<img width="570" alt="image" src="https://user-images.githubusercontent.com/98358127/213540723-16802102-7adc-4830-aaaf-fa6302ca7d30.png">|<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/213537650-27876513-c513-43d8-baf3-02210044ccc1.png">
