### ISSUE TITLE
Old widgets are not removed in widget list on upgraded profile 

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#27757]
## Description 
Old widgets are not removed in widget list on upgraded profile 

## Steps to reproduce 

   1. Install 1.46.x
   2. Launch Brave
   3. Add brave quick action widget on home screen
   4. Upgrade to 1.47.x
   5. Attempt to add another widget from home screen long press.
   6. Observe list of widgets under brave

## Actual result 

Brave shows list of 5 widgets, 2 of them are legacy widgets (dino, and original search widget)

Example | Example
-|-
![screenshot-1673458004884](https://user-images.githubusercontent.com/17885425/211892601-6aaad742-9aa7-48bb-b0cc-3aa36ba7a19e.png) | ![screenshot-1673458013478](https://user-images.githubusercontent.com/17885425/211892607-c57675c1-4f7c-48b9-8735-927d83d1360c.png)

## Expected result
1. Old widgets should be removed. The list should show 3 widgets like you would see with a fresh profile.
2. Existing search widget should be updated to new version.

## Issue reproduces how often 
Easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung GS 21
   - Android version: 12
   
## Brave version
`1.47.169, Chromium 109.0.5414.87`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.47.179` or higher for `1.47.x` verification 👍

**Comment by Uni-verse** [comment]
In progress on Samsung Galaxy S21 using version:

Brave	1.47.181 Chromium: 109.0.5414.87 (Official Build) (64-bit) 
Revision	2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS	Android 13; Build/TP1A.220624.014
