### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by TWNWAKing** [brave/brave-browser#27768]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.46.153  Chromium: 108.0.5359.128
Operating System: Linux 6.0.0-kali6-amd64

URL (if applicable) where crash occurred: [https://lonmar.cn/2022/03/01/susctf-2022/](https://lonmar.cn/2022/03/01/susctf-2022/)

Can you reproduce this crash? Yes. My Brave on Windows machine crashed while viewing this website, and I tried it on my virtual machine, also crashed. And I've tried viewing this website via original chrome, it works fine. 

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Browse the webstie.
2. Crash!
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/f1090100-d60f-7509-0000-000000000000

**Comment by rebron** [comment]
@TWNWAKing When you get a chance can you update to 1.47.171 and let us know if you're still experiencing the crash.

**Comment by TWNWAKing** [comment]
@rebron Thank you! This bug has been fixed. Checked on Windows and Linux platform.
