### ISSUE TITLE
`brave://welcome` import is missing Yandex

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#27760]
## Description 

`brave://welcome` import is missing Yandex

This is a followup issue found while testing https://github.com/brave/brave-browser/issues/27301.

## Steps to Reproduce

1. populate a Yandex browser with at least bookmarks
2. install `1.48.121`
3. launch Brave
4. on `brave://welcome` look for `Yandex` as an import options

## Actual result:

`Yandex` is missing

<img width="1312" alt="Screen Shot 2023-01-11 at 11 25 48 AM" src="https://user-images.githubusercontent.com/387249/211907056-e5c7236f-045d-48d4-b433-bb26c04553ee.png">

## Expected result:

`Yandex` should be available to import from, with both an icon and its name present on `brave://welcome`

Note: it correctly shows up in `brave://settings/importData` 👍 

<img width="1198" alt="Screen Shot 2023-01-11 at 11 25 33 AM" src="https://user-images.githubusercontent.com/387249/211907263-1e6259cb-8115-418e-b218-0064ee20d4eb.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.48.121 Chromium: 109.0.5414.87 (Official Build) beta (x86_64)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | macOS Version 11.7.2 (Build 20G1020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

/cc @rebron @spylogsster @MadhaviSeelam @nullhook @brave/qa-team

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.49.88 Chromium: 110.0.5481.77 (Official Build) beta (64-bit)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | Windows 11 Version 21H2 (Build 22000.1455)
```


Pre-requisite: Download Yandex browser and have data for History, Bookmarks and Extensions
<details>

Profile 1: Bookmarks, history & extensions
bookmarks | history | extensions
--- | ---| ---
<img width="632" alt="image" src="https://user-images.githubusercontent.com/98358127/217061050-da07bdd7-8599-42e2-853f-fcdaf0cff96c.png">|<img width="627" alt="image" src="https://user-images.githubusercontent.com/98358127/217060998-ffd21184-f32f-4841-b18d-513685b2adce.png">|<img width="626" alt="image" src="https://user-images.githubusercontent.com/98358127/217098121-73e643b4-4a90-4b35-b859-aca1ce672da5.png">

Profile 2:  Bookmarks & History
bookmarks | history
--- | ---
<img width="629" alt="image" src="https://user-images.githubusercontent.com/98358127/217061943-62956c89-d172-47d1-9acb-37784933771f.png">|<img width="633" alt="image" src="https://user-images.githubusercontent.com/98358127/217065136-cbe7570a-a126-4ccb-b83a-d6bd27db0094.png">

Profile 3: Bookmarks
<img width="629" alt="image" src="https://user-images.githubusercontent.com/98358127/217065360-cac50939-c73e-4b15-8e36-748886bdeb16.png">

</details>

Case 1: Verify `Yandex` icon is available in `brave://welcome` page 
<details>

1. Install 1.49.88
2. launch Brave
3. click `Set Brave as default browser`

#### Confirmed `Yandex` icon is available in the `brave://welcome` - first screen

step 3|result
-----|-----
<img width="462" alt="image" src="https://user-images.githubusercontent.com/98358127/217095054-391b7d15-9691-4ec1-a615-0504c9d862ba.png">|<img width="469" alt="image" src="https://user-images.githubusercontent.com/98358127/217095128-4a48ed27-6262-44e9-b779-4f3c7b26d48a.png">
</details>

Case 2: Single profile - Complete Import from `brave://welcome` - Import Settings page
<details>

1. continue from Case 1
     - `Yandex` is shown in `brave://welcome` page - `import settings` screen 
2. click `Import` button   
3. open brave://settings/appearance
4. select `Yandex User 1`  in the `Select profile to import` screen
5. clicked `Import profiles` 
6. verified `Setup complete` screen is displayed as expected 
7. verified  `Help improve Brave` screen is displayed as expected
8. verified new-tab page is shown as expected

### Confirmed Bookmarks imported from `Yandex` are shown in `brave://bookmarks` and bookmarks bar 
### Confirmed History imported from `Yandex` is shown in `brave://history`
### Confirmed Extensions imported from `Yandex` are shown in `brave://extensions`

step 1-2|step 4-5|step 6|step 7|step 8|result|result
-----|----|-----|------|----|----|-----
<img width="449" alt="image" src="https://user-images.githubusercontent.com/98358127/217096520-615463f0-dff4-4478-90d3-da2b83a40829.png">|<img width="453" alt="image" src="https://user-images.githubusercontent.com/98358127/217096807-71c4474b-d2ac-4af3-9306-f5448317b044.png">|<img width="447" alt="image" src="https://user-images.githubusercontent.com/98358127/217096876-3d4f14d4-8271-4d4b-bec6-2522c35a2fff.png">|<img width="450" alt="image" src="https://user-images.githubusercontent.com/98358127/217096899-e4cf8624-067f-44d6-a84f-cf912527a849.png">|<img width="454" alt="image" src="https://user-images.githubusercontent.com/98358127/217098528-b95ee441-909b-491d-983a-e24f3b45c67d.png">|<img width="449" alt="image" src="https://user-images.githubusercontent.com/98358127/217097581-8314bdd0-3655-4056-bba1-de2b98a8f878.png">|<img width="448" alt="image" src="https://user-images.githubusercontent.com/98358127/217097624-fae10641-3d9f-46b7-ad2d-b2f99a239273.png">|<img width="461" alt="image" src="https://user-images.githubusercontent.com/98358127/217098407-df39258b-7289-4b81-940f-a99b10ff682d.png">|<img width="460" alt="image" src="https://user-images.githubusercontent.com/98358127/217104797-e47de25d-81dc-4101-8602-e77e4e90f00f.png">

Case 3: Multiple profiles - Complete Import from `brave://welcome` - Import Settings page
<details>

1. new profile 
2. launch Brave
3. click `Set Brave as default browser`
4. select  `Yandex` in  `import settings` screen 
5. click `Import` button   
6. click `Select All` to select all 3 profiles 
7. select `Yandex User 1`  in the `Select profile to import` screen
8. clicked `Import profiles` 
9. verified `Setup complete` screen is displayed as expected 
10. verified  `Help improve Brave` screen is displayed as expected
11. verified new-tab page is shown as expected

example|example
-----|---
<img width="456" alt="image" src="https://user-images.githubusercontent.com/98358127/217105546-3952638e-d9d2-4e9e-bd0e-a346f1e11f89.png">|<img width="457" alt="image" src="https://user-images.githubusercontent.com/98358127/217105652-bd54af21-a5d9-47e9-b697-081121acb470.png">

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.49.96 Chromium: 110.0.5481.77 (Official Build) beta (x86_64)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | macOS Version 11.7.3 (Build 20G1116)

Case 1: Verify `Yandex` icon is available in `brave://welcome` page - `PASSED`
<details>

1. installed `1.49.96`
2. launched Brave
3. clicked `Set Brave as default browser`

#### Confirmed `Yandex` icon is available in the `brave://welcome` `Import Settings` screen

<img width="1491" alt="Screen Shot 2023-02-13 at 10 30 25 AM" src="https://user-images.githubusercontent.com/387249/218544241-ab22c9e3-04fa-4e0b-bc41-ce2684ac77fb.png">

</details>

Case 2: Single profile - complete import from `brave://welcome` - import settings page - `PENDING`

Case 3: Multiple profiles - complete import from `brave://welcome` - import settings page - `PENDING`

Case 4: Bookmarks imported from `Yandex` should Sync between devices - `PENDING`

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.49.116 Chromium: 110.0.5481.177 (Official Build) beta (64-bit)
-- | --
Revision | f34f7ab2d4ca4ad498ef42aeba4f4eb2c1392d63-refs/branch-heads/5481@{#1239}
OS | Linux
```
Pre-requisite: Download Yandex browser and have data for History, Bookmarks and Extensions
<details>

Download Yandex: and create 2 profiles 

User 1 | Car
------ | ---------
<image width="400" alt="image" src="https://user-images.githubusercontent.com/98358127/222309470-2e47a463-d1c6-490c-9d1a-6deba41bc727.png">|<image width="400" alt="image" src="https://user-images.githubusercontent.com/98358127/222309566-06063da8-f161-44b4-941b-9741c4006559.png">
</details>

#### Case 1: Verify `Yandex` icon is available in `brave://welcome` page - `PASSED`
<details>

1. Install 1.49.116
2. launch Brave
3. click `Set Brave as default browser`

#### Confirmed `Yandex` icon is available in the `brave://welcome` - first screen - `PASSED`

step 3|result
-----|-----
<img width="462" alt="image" src="https://user-images.githubusercontent.com/98358127/217095054-391b7d15-9691-4ec1-a615-0504c9d862ba.png">|<img width="469" alt="image" src="https://user-images.githubusercontent.com/98358127/217095128-4a48ed27-6262-44e9-b779-4f3c7b26d48a.png">
</details>

Case 2: Single profile - complete import from brave://welcome - import settings page - PASSED
<details>

1. Install 1.49.116
2. launch Brave
3. click `Set Brave as default browser
4. select `Yandex`
5. click import
6. select `Yandex User 1`
7. click Import Profiles
8. click Finish

Confirmed Bookmarks imported from Yandex are shown in brave://bookmarks and bookmarks bar
Confirmed History imported from Yandex is shown in brave://history
Confirmed Extensions imported from Yandex are shown in brave://extensions

step 3 | step 4 | step 6 | step 8 |  new-tab | bookmarks | history | extensions 
---------- | ------------ | ----------- | ----------- | ----------- | ----------- | ----------- | ----------- 
<image width="300" alt="image" src="https://user-images.githubusercontent.com/98358127/222526724-1cc423a9-4c62-4f19-ab13-5f2692729627.png">|<image width="300" alt="image" src="https://user-images.githubusercontent.com/98358127/222532377-cceeb22a-4e87-4de0-8875-ab0f02811370.png">|<image width="300" alt="image" src="https://user-images.githubusercontent.com/98358127/222532209-76ae1f10-811a-43df-a600-17bf5dc0adde.png">|<image width="300" alt="image" src="https://user-images.githubusercontent.com/98358127/222526497-e7fd3b8d-1e32-4f11-b7d2-08b1d1141542.png">|<image width="300" alt="image" src="https://user-images.githubusercontent.com/98358127/222534453-d14692b2-e5f2-4a7f-97bb-8b0cf7366b03.png">|<image width="300" alt="image" src="https://user-images.githubusercontent.com/98358127/222531392-2cf09584-ab4b-41ff-89df-d18d8010cc10.png">|<image width="300" alt="image" src="https://user-images.githubusercontent.com/98358127/222531540-341d3bbe-da65-4117-a734-b828f387ac81.png">|<image width="300" alt="image" src="https://user-images.githubusercontent.com/98358127/222531601-79d34fbb-63fe-4a5d-a4b1-1fe4ab910fb7.png">

</details>

#### Case 3: Multiple profiles - Complete Import from `brave://welcome` - Import Settings page - `PASSED`
<details>

1. new profile 
2. launch Brave
3. click `Set Brave as default browser
4. select Yandex 
5. click import
6. select `Yandex User 1, Car, Ball`
7. click Import Profiles
8. click Finish
9. click on Profile icon in the new-tab page next to hamburger menu

#### Confirmed three newly created profiles with randomly assigned Avatars are shown in the profile manager
#### Confirmed three newly created profiles have same names from Yandex imports are shown in the profile manager 
#### Confirmed data correctly imported into separate profiles `Yandex User 1`, `Car` & `Chrome Person 3`
#### Confirmed bookmarks, history, extensions and passwords are imported into `Chrome Person 1`
#### Confirmed bookmarks, history  passwords and extensions  are shown in `Chrome Person 2`
#### Confirmed bookmarks, history  are shown in `Chrome Person 3`
#### Confirmed Brave Profile 1 is created and shown as expected


step 3 | step 4 | step 6 | step 8 |  new-tab | bookmarks | history | extensions 
---------- | ------------ | ----------- | ----------- | ----------- | ----------- | ----------- | ----------- 
<image width="300" alt="image" src="https://user-images.githubusercontent.com/98358127/222526724-1cc423a9-4c62-4f19-ab13-5f2692729627.png">|<image width="300" alt="image" src="https://user-images.githubusercontent.com/98358127/222532377-cceeb22a-4e87-4de0-8875-ab0f02811370.png">|<image width="300" alt="image" src="https://user-images.githubusercontent.com/98358127/222539303-45708e14-4071-4cf7-8ded-c48ff31f9367.png">|<image width="300" alt="image" src="https://user-images.githubusercontent.com/98358127/222526497-e7fd3b8d-1e32-4f11-b7d2-08b1d1141542.png">|<image width="300" alt="image" src="https://user-images.githubusercontent.com/98358127/222539542-4f9cb2c0-21fb-4bd3-bf41-8ceeee0d52ea.png">|<image width="300" alt="image" src="https://user-images.githubusercontent.com/98358127/222538717-69eac4b0-a31c-4829-9f99-efdc469037bf.png">

</Details>

#### Case 4: Bookmarks imported from `Yandex`  should `Sync` between devices 
<Details>

**device 1** 

1. new profile
2. launch Brave
3. click `Set Brave as default browser` on `brave://welcome` page
4. select `Yandex` and click `Import
5. select `Yandex User 1` and click `Import profiles` 
6. click `Finish` 
7. confirmed successful import of  `Browsing history`, `Favorites/Bookmarks`, `Extensions`
8. visit `brave://sync`
9. click on `Start using sync` ---> `Start a new Sync Chain`
10. click `Computer`
11. copy the code words
12. under `Sync Settings`, click on the `Sync everything` radio button


**device 2**

1. go to `device 2`
2. click on the "hamburger" menu, and then `Sync`
3. click `I have a Sync Code`
4. enter/paste the code words from `device 1`
5. click `Confirm`
6. click `OK`
7. under `Sync Settings`, click on the `Sync everything` toggle

#### Confirmed `Favorites/Bookmarks`, `Extensions` synced successfully

Note:`Browsing history` not synced.  Only URLs of the sites that were visited in the session are synced

Step 4 | Step 7 | bookmarks & extensions
-------|--------|-------------

</Details>

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.49.116 Chromium: 110.0.5481.177 (Official Build) beta (64-bit)
-- | --
Revision | f34f7ab2d4ca4ad498ef42aeba4f4eb2c1392d63-refs/branch-heads/5481@{#1239}
OS | Linux
```
Pre-requisite: Download Yandex browser and have data for History, Bookmarks and Extensions
<details>

Download Yandex: and create 2 profiles 

User 1 | Car
------ | ---------
<image width="400" alt="image" src="https://user-images.githubusercontent.com/98358127/222309470-2e47a463-d1c6-490c-9d1a-6deba41bc727.png">|<image width="400" alt="image" src="https://user-images.githubusercontent.com/98358127/222309566-06063da8-f161-44b4-941b-9741c4006559.png">
</details>

#### Case 1: Verify `Yandex` icon is available in `brave://welcome` page - `PASSED`
<details>

1. Install 1.49.116
2. launch Brave
3. click `Set Brave as default browser`

#### Confirmed `Yandex` icon is available in the `brave://welcome` - first screen - `PASSED`

step 3|result
-----|-----
<img width="462" alt="image" src="https://user-images.githubusercontent.com/98358127/217095054-391b7d15-9691-4ec1-a615-0504c9d862ba.png">|<img width="469" alt="image" src="https://user-images.githubusercontent.com/98358127/217095128-4a48ed27-6262-44e9-b779-4f3c7b26d48a.png">
</details>

Case 2: Single profile - complete import from brave://welcome - import settings page - PASSED
<details>

1. Install 1.49.116
2. launch Brave
3. click `Set Brave as default browser
4. select `Yandex`
5. click import
6. select `Yandex User 1`
7. click Import Profiles
8. click Finish

Confirmed Bookmarks imported from Yandex are shown in brave://bookmarks and bookmarks bar
Confirmed History imported from Yandex is shown in brave://history
Confirmed Extensions imported from Yandex are shown in brave://extensions

step 3 | step 4 | step 6 | step 8 |  new-tab | bookmarks | history | extensions 
---------- | ------------ | ----------- | ----------- | ----------- | ----------- | ----------- | ----------- 
<image width="300" alt="image" src="https://user-images.githubusercontent.com/98358127/222526724-1cc423a9-4c62-4f19-ab13-5f2692729627.png">|<image width="300" alt="image" src="https://user-images.githubusercontent.com/98358127/222532377-cceeb22a-4e87-4de0-8875-ab0f02811370.png">|<image width="300" alt="image" src="https://user-images.githubusercontent.com/98358127/222532209-76ae1f10-811a-43df-a600-17bf5dc0adde.png">|<image width="300" alt="image" src="https://user-images.githubusercontent.com/98358127/222526497-e7fd3b8d-1e32-4f11-b7d2-08b1d1141542.png">|<image width="300" alt="image" src="https://user-images.githubusercontent.com/98358127/222534453-d14692b2-e5f2-4a7f-97bb-8b0cf7366b03.png">|<image width="300" alt="image" src="https://user-images.githubusercontent.com/98358127/222531392-2cf09584-ab4b-41ff-89df-d18d8010cc10.png">|<image width="300" alt="image" src="https://user-images.githubusercontent.com/98358127/222531540-341d3bbe-da65-4117-a734-b828f387ac81.png">|<image width="300" alt="image" src="https://user-images.githubusercontent.com/98358127/222531601-79d34fbb-63fe-4a5d-a4b1-1fe4ab910fb7.png">

</details>

#### Case 3: Multiple profiles - Complete Import from `brave://welcome` - Import Settings page - 
<details>

1. new profile 
2. launch Brave
3. click `Set Brave as default browser
4. select Yandex 
5. click import
6. select `Yandex User 1, Car, Ball`
7. click Import Profiles
8. click Finish
9. click on Profile icon in the new-tab page next to hamburger menu

#### Confirmed three newly created profiles with randomly assigned Avatars are shown in the profile manager
#### Confirmed three newly created profiles have same names from Yandex imports are shown in the profile manager 
#### Confirmed data correctly imported into separate profiles `Yandex User 1`, `Car` & `Chrome Person 3`
#### Confirmed bookmarks, history, extensions and passwords are imported into `Chrome Person 1`
#### Confirmed bookmarks, history  passwords and extensions  are shown in `Chrome Person 2`
#### Confirmed bookmarks, history  are shown in `Chrome Person 3`
#### Confirmed Brave Profile 1 is created and shown as expected


step 3 | step 4 | step 6 | step 8 |  new-tab | bookmarks | history | extensions 
---------- | ------------ | ----------- | ----------- | ----------- | ----------- | ----------- | ----------- 
<image width="300" alt="image" src="https://user-images.githubusercontent.com/98358127/222526724-1cc423a9-4c62-4f19-ab13-5f2692729627.png">|<image width="300" alt="image" src="https://user-images.githubusercontent.com/98358127/222532377-cceeb22a-4e87-4de0-8875-ab0f02811370.png">|<image width="300" alt="image" src="https://user-images.githubusercontent.com/98358127/222539303-45708e14-4071-4cf7-8ded-c48ff31f9367.png">|<image width="300" alt="image" src="https://user-images.githubusercontent.com/98358127/222526497-e7fd3b8d-1e32-4f11-b7d2-08b1d1141542.png">|<image width="300" alt="image" src="https://user-images.githubusercontent.com/98358127/222539542-4f9cb2c0-21fb-4bd3-bf41-8ceeee0d52ea.png">|<image width="300" alt="image" src="https://user-images.githubusercontent.com/98358127/222538717-69eac4b0-a31c-4829-9f99-efdc469037bf.png">

</Details>

#### Case 4: Bookmarks imported from `Yandex`  should `Sync` between devices 
<Details>

**device 1** 

1. new profile
2. launch Brave
3. click `Set Brave as default browser` on `brave://welcome` page
4. select `Yandex` and click `Import
5. select `Yandex User 1` and click `Import profiles` 
6. click `Finish` 
7. confirmed successful import of  `Browsing history`, `Favorites/Bookmarks`, `Extensions`
8. visit `brave://sync`
9. click on `Start using sync` ---> `Start a new Sync Chain`
10. click `Computer`
11. copy the code words
12. under `Sync Settings`, click on the `Sync everything` radio button


**device 2**

1. go to `device 2`
2. click on the "hamburger" menu, and then `Sync`
3. click `I have a Sync Code`
4. enter/paste the code words from `device 1`
5. click `Confirm`
6. click `OK`
7. under `Sync Settings`, click on the `Sync everything` toggle

#### Confirmed `Favorites/Bookmarks`, `Extensions` synced successfully

Note:`Browsing history` not synced.  Only URLs of the sites that were visited in the session are synced

Step 4 | Step 7 | bookmarks & extensions
-------|--------|-------------

</Details>
