### ISSUE TITLE
WebGL Games in iframe

### ISSUE THREAD

**Issue by EddieOne** [brave/brave-browser#2776]
## Description 
Iframes are how distribution seems to be headed for WebGL games. However, the behavior is somewhat unexpected for Brave. Detailed with tests here. https://github.com/photonstorm/phaser/issues/4251

## Steps to Reproduce

   1. Visit this page https://jsfiddle.net/pdbjo563/

## Actual result:
Iframe is empty with error. Uncaught Error: Failed to compile Vertex Shader:
null

## Expected result:
Iframe should play Phaser demo.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Version 0.58.18 Chromium: 71.0.3578.98 (Official Build) (64-bit)

### Reproducible on current release:
I'm not sure.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? Yes
- Is the issue reproducible on the latest version of Chrome? No

**Comment by rebron** [comment]
Are you using fingerprint protection/device recognition blocking?

**Comment by EddieOne** [comment]
I just use the default. WebGl does work directly, just not in iframes.

**Comment by stshank** [comment]
Is this another instance? "For compatibility reasons, 3D is not available."
https://www.nti.org/analysis/articles/north-korean-ballistic-missile-models/

I get a WebGL error that directs me here:
https://help.sketchfab.com/hc/en-us/articles/203059088-Compatibility

With shields down it worked fine.

There's a "load unsafe scripts" block, too, but bypassing that didn't do anything.
