### ISSUE TITLE
Fix notification modal description and textual button color in dark mode - follow up to #27004

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#27767]
## Description 

Looking at https://github.com/brave/brave-core/pull/16128/files, it doesn't look like any changes were added into the PR that fixes the colour issue(s) discussed via https://github.com/brave/brave-browser/issues/27004#issue-1466184188. When launching Brave for the first time on `Android 13`, the modal looks the same as before. We need to make sure it we're using the correct colours.

## Steps to reproduce 

Prerequisite: ensure that you're using `dark mode` via `Android 13` before launching Brave.

**`Test Case #1`**

   1. install `1.49.20 Chromium: 109.0.5414.87` using `Android 13`
   2. run through the initial on-boarding and notice that the notification panel looks the same as before and is hard to read

**`Test Case #2`**

   1. install `1.49.20 Chromium: 109.0.5414.87` using `Android 13`
   2. run through the initial on-boarding and enable notifications
   3. go into `Settings` -> `Notifications` and disable all notifications from the `Notifications` page
   4.  tap on `<-` (back button) and go back to the `Settings` page (notice the general warning is also using the incorrect colours)
   
## Actual result 

**`Example`** | **`Example`**
---------------|-----------------
![Screenshot_20230112-002035](https://user-images.githubusercontent.com/2602313/212025795-ce617d6c-2480-4c2f-9819-a60f050f3817.png) | ![Screenshot_20230112-002110](https://user-images.githubusercontent.com/2602313/212025806-25c4955b-de8e-4ab6-84ae-d178bdadefd0.png)

## Expected result

Should be using the scheme mentioned via https://github.com/brave/brave-browser/issues/27004#issue-1466184188 and look like https://www.figma.com/file/sdVBBufbl2A11hAgPNfyqG/Android-13-Notifications?node-id=1243%3A31639&t=7Pd5NQyY0I0HjTn0-1. @sujitacharya2005 also added a screenshot of how it was supposed to look via https://github.com/brave/brave-core/pull/16128#issue-1467834425.

## Issue reproduces how often 

100% reproducible using the STR/Cases outlined above.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `Yes`
- Can you reproduce this issue with the current Play Store Beta version? `Yes` 
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Pixel 6` (Phone)
   - Android version: `Android 13`
   
## Brave version

```
Brave | 1.49.22 Chromium: 109.0.5414.87 (Official Build) canary (32-bit)
--- | ---
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | Android 13; Build/T2B1.221118.006
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

### Additional information

CCing @deeppandya @timchilds @sujitacharya2005

**Comment by deeppandya** [comment]
@sujitacharya2005 we need to uplift the change to 1.47

**Comment by kjozwiak** [comment]
The above requires `1.47.176` or higher for `1.47.x` verification 👍

**Comment by Uni-verse** [comment]
In progress on Samsung Galaxy S21 using version:

Brave	1.47.181 Chromium: 109.0.5414.87 (Official Build) (64-bit) 
Revision	2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS	Android 13; Build/TP1A.220624.014
