### ISSUE TITLE
Use onDiscoverAssetsCompleted callback when assets discovered in background process

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#27776]
## Description 

Currently the [OnDiscoverAssetsCompleted(array<BlockchainToken> discovered_assets)](https://github.com/brave/brave-core/blob/ca44203ce51370dc7cc503d8b8e9b3f7f2b0f8d4/components/brave_wallet/common/brave_wallet.mojom#L1180) callback is only called when we call the [DiscoverAssetsOnAllSupportedChains()](https://github.com/brave/brave-core/blob/ca44203ce51370dc7cc503d8b8e9b3f7f2b0f8d4/components/brave_wallet/common/brave_wallet.mojom#LL1359C3-L1359C40) ourselves. This can cause the UI/front-end to not know when assets are discovered through a background process (wallet import from seed phrase, new account imported from seed phrase) so the discovered asset(s) are not shown until the next wallet open or a page refresh.

## Steps to Reproduce
Wallet import from seed phrase:
   1. Onboard a wallet from seed phrase where the first account has >0 balance of an asset not in our default list
   2. Observe the discovered asset is not listed in Portfolio assets list
   3. Refresh the page
   4. Observe the discovered asset is now listed in Portfolio assets list

Account import from private key:
1. Import an account using it's private key where the first account has >0 balance of an asset not in our default list
   2. Observe the discovered asset is not listed in Portfolio assets list
   3. Refresh the page
   4. Observe the discovered asset is now listed in Portfolio assets list

## Actual result:

Wallet import from seed phrase requires reload to see discovered asset:

https://user-images.githubusercontent.com/5314553/212114737-4154b81d-84f7-4304-a5ce-f1b9ff9f806a.mov

Account import from private key:

https://user-images.githubusercontent.com/5314553/212114816-48bf32e6-fcf4-4008-9a8e-658ca7fa7a5c.mov

## Expected result:

The discovered asset shouldn't require refresh to be visible

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

[Version 1.46.153 Chromium: 108.0.5359.128 (Official Build) (arm64)](https://brave.com/latest/)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by jamesmudgett** [comment]
cc @Douglashdaniel @yrliou

**Comment by yrliou** [comment]
Just a quick summary of our group DM, it makes sense to me to fire both onDiscoverAssetsStarted (for UI to get the indication that auto discovery is now in progress) and onDiscoverAssetsCompleted events no matter it's triggered by core or UI side.

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.52.102 Chromium: 113.0.5672.126 (Official Build) beta (64-bit)
-- | --
Revision | `c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}`
OS | Windows 11 Version 22H2 (Build 22621.1702)

- Verified steps from [brave/brave-core#17825](https://github.com/brave/brave-core/pull/17825)
- Verified adding accounts through any medium (seed words/private key) imports fungible and non-fungible tokens

https://github.com/brave/brave-browser/assets/17010094/5043e718-b2c2-4340-96a0-a1a1f0528192
