### ISSUE TITLE
Cannot import extensions from Chrome

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#27770]
## Steps to Reproduce

   1. Install extensions to chrome
   2. Import Chrome profile to Brave

## Actual result:

Extensions not imported

## Expected result:

Extensions imported

## Reproduces how often: 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Test Plan:
- Install latest Chrome (for win I use 109.0.5414.75 (Official Build) (64-bit)) and install an extension from web store, I use jfbnmfgkohlfclfnplnlenbalpppohkm for testing
- Check `c:\Users\[username]\AppData\Local\Google\Chrome\User Data\Default\Secure Preferences` file, it should have one line without extensions info.
- Try to import from Chrome profile
- Make sure installed extension imported to Brave.
- Additionally check extensions can be imported from Chrome and others Chromium based browsers who keeps information inside `Secure Preferences`, I checked with Yandex.

**Comment by spylogsster** [comment]
cc @rebron

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using


Google Chrome | 110.0.5481.77 (Official Build) (x86_64)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | macOS Version 11.7.3 (Build 20G1116)

and



Brave | 1.49.96 Chromium: 110.0.5481.77 (Official Build) beta (x86_64)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | macOS Version 11.7.3 (Build 20G1116)

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.49.106 Chromium: 110.0.5481.104 (Official Build) beta (64-bit)
-- | --
Revision | 46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}
OS | Windows 11 Version 21H2 (Build 22000.1574)
```
Pre - requisites: Populate Chrome release browser and Vivaldi browser with with at least 2 extensions in a profile
<details>

Chrome: 
<img width="454" alt="image" src="https://user-images.githubusercontent.com/98358127/220419924-c1e6e39e-490d-4d86-aa10-0f123575cdb2.png">

---------
Vivaldi:  Imported  Roblox extension (`jfbnmfgkohlfclfnplnlenbalpppohkm`)and confirmed the extension is shown `Secure Preferences`
<img width="956" alt="image" src="https://user-images.githubusercontent.com/98358127/220427376-9a43900c-90e3-4bf7-9b8c-12070f3690b1.png">
</details>


### Case 1: Import extensions from Google Chrome - `PASSED`
<details>

### Steps:
Prerequisite: latest Chrome release browser, populated with at least 2 extensions in a profile

1. installed `1.49.106 `
2. launched Brave
3. clicked on `Skip`
4. clicked on `Chrome`
5. clicked on `Import`
6. select `Chrome Person 1` 
7. clicked `Import profiles` 
8. clicked on `Finish`
9. opened `brave://extensions`

#### Confirmed all extensions imported except for `Google Docs Offline` 

step 4 - 5 | step 6-7 | step 8 | step 9
------ | ----- | ------ | ------
<img width="461" alt="image" src="https://user-images.githubusercontent.com/98358127/220427725-f0709064-9d1b-44e9-82f2-f9326e21102b.png">|<img width="460" alt="image" src="https://user-images.githubusercontent.com/98358127/220427783-3f74ef01-ffb7-4364-8b51-59b1951be681.png">|<img width="461" alt="image" src="https://user-images.githubusercontent.com/98358127/220429213-cf6f4c8f-bdb2-41f3-8eba-1e191e6c6d6b.png">|<img width="465" alt="image" src="https://user-images.githubusercontent.com/98358127/220429368-eea16100-35cd-40d2-94e7-b4ee233c7c34.png">
</details>

Case 2:  Import extensions from Vivaldi - `PASSED`
<details>

1. New profile
2. launched Brave
3. clicked on `Skip` >> `Skip` >>`Finish`
4. open brave://settings/importData
5. select `Vivaldi Person 1`
6. click `Import`
7. click `Done`
8. opened `brave://extensions`

#### Confirmed all extensions are imported 

step 5-6 | step 7 | step 8
----- | ----- | ------
<img width="462" alt="image" src="https://user-images.githubusercontent.com/98358127/220431563-e5af13e4-9e0f-4853-993f-eea11b747613.png">|<img width="461" alt="image" src="https://user-images.githubusercontent.com/98358127/220431670-fed821a5-4726-4d7c-8e16-01a7612de2e0.png">|<img width="462" alt="image" src="https://user-images.githubusercontent.com/98358127/220431794-274e8bad-e621-4e24-afe6-3722800cfa30.png">

</details>

**Comment by MadhaviSeelam** [comment]
@stephendonner -  `Show YouTube Dislikes`  extension was successfully imported in `Win 11 x64`.  However `Google Docs Offline` was not imported as it was installed by default and it is expected behavior.
cc: @spylogsster.
