### ISSUE TITLE
Show NFT section on portfolio

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#27777]
## Description 
Show NFT section under crypto list

## Expected result
![Screenshot from 2023-01-12 21-51-06](https://user-images.githubusercontent.com/11755381/212122886-ef42a9f0-962e-4d9f-b80d-5daea76ad493.png)

**Comment by kjozwiak** [comment]
The above requires `1.48.141` or higher for `1.48.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on the following devices running 
- Verified steps from [brave/brave-core#16671](https://github.com/brave/brave-core/pull/16671)
- Verified NFT is listed under its own heading in portfolio page
- Verified NFT image/gif is shown on portfolio page
- Verified clicking on NFT loads the NFT details view
- Verified NFT is shown and can be viewed for both Ethereum NFT and Solana NFT
- Verified changing network in network filter updates the NFT view and removes it
- Encountered [#28301](https://github.com/brave/brave-browser/issues/28301)

Oppo Reno 5 (Android 13) | Lenovo Tab (Android 12)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/216908652-a4159065-e5cd-4430-8427-1d683b1429be.mp4> | <img width=400 src=https://user-images.githubusercontent.com/17010094/216908719-0ca5bc77-169a-4df2-9a20-1cb8197c89ca.mp4>
