### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by zsdd89** [brave/brave-browser#27779]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.46.153  Chromium: 108.0.5359.128
Operating System: Windows NT 10.0.22621

URL (if applicable) where crash occurred: https://itcafe.hu 

Can you reproduce this crash?
Yes. Every time i open the beforementioned site  which i was visiting every day for years, but from 2 days ago i cannot access it.
The same happens on my android phone (Oneplus 8T, A13)  with latest Brave version.

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Opening https://itcafe.hu
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/84810100-d60f-7509-0000-000000000000

**Comment by goodov** [comment]
I don't see any similar crash in the latest Brave release version. Can you update and check please?

**Comment by zsdd89** [comment]
Seems yesterday's update v1.47.171 (Jan 12, 2023) fixed this issue, but on android it's still not fixed
