### ISSUE TITLE
IPFS NFT Gateway setting for iOS

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#27781]
Setting should modify NFT Gateway url that is used to fetch metadata in the JsonRpcService and to fetch NFT image

**Comment by kjozwiak** [comment]
Closing this as it looks like https://github.com/brave/brave-core/pull/16646 has been merged into `master` and is being uplifted into `1.48.x` via https://github.com/brave/brave-core/pull/16823. Also changing from `In review` to `Done` as it was reviewed via https://github.com/brave/brave-core/pull/16646#pullrequestreview-1262017821 & https://github.com/orgs/brave/teams/ios and obviously merged.

**Comment by cypt4** [comment]
This issue contains both core and ui changes, still witing for ui changes to be merged

**Comment by kjozwiak** [comment]
> This issue contains both core and ui changes, still witing for ui changes to be merged

Regarding the UI changes, please open a new issue as this was already merged into `1.47.x` and now needs to move there. Because it has a PR associated with it merged that's in `1.47.x`, we close this off.
