### ISSUE TITLE
Link has incorrect color on Rewards page

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#27799]
## Description 

The "learn more" link in the Rewards summary box on the Rewards page is rendered with the incorrect color.

## Steps to Reproduce

   1. Using a "grandfathered unverified" profile (account created in 1.47 or earlier).
   2. Navigate to`brave://rewards`.

## Actual result:

<img width="400" alt="Screen Shot 2023-01-13 at 12 10 20 PM" src="https://user-images.githubusercontent.com/5995084/212379439-6dea5781-3c7e-4473-82b4-bfdf802f6454.png">

## Expected result:

The "learn more" link should be white.

## Reproduces how often: 

Easily reproduced

## Desktop Brave version:

1.48.x

**Comment by kjozwiak** [comment]
The above requires `1.48.132` or higher for `1.48.x` verification 👍

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using `1.48.134`, `Chromium 109.0.5414.87` on a `Google Pixel XL` running `Android 9`.

**Comment by stephendonner** [comment]
## Verified `PASSED` using

Brave | 1.48.137 Chromium: 109.0.5414.87 (Official Build) beta (x86_64)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | macOS Version 11.7.2 (Build 20G1020)

### Steps:

1. installed `1.47.161`
2. launched Brave
3. enabled Brave Rewards
4. installed `1.48.137` atop `1.47.161` (both are beta-channel builds)
5. launched Brave
6. opened `brave://rewards`
7. examined and clicked on the `Learn more` link

#### Confirmed the `-- Learn more` link is white and goes to `https://brave.com/rewards-changes/`

`brave://rewards` | `https://brave.com/rewards-changes/`
------------------|---------------------------------------
<img width="1679" alt="Screen Shot 2023-01-23 at 1 44 37 PM" src="https://user-images.githubusercontent.com/387249/214157604-df805f2e-8ea8-4c8d-be41-7736c7f20a3a.png"> | <img width="1679" alt="Screen Shot 2023-01-23 at 1 50 38 PM" src="https://user-images.githubusercontent.com/387249/214157873-59c23d60-837c-4d58-ae6e-b480aa1a3d33.png">
