### ISSUE TITLE
Update tipping banner text when user is in `Logged out` state

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#27792]
## Description

When user is in the logged out state, this is the text that shows in the tipping banner:

![image](https://user-images.githubusercontent.com/11497541/212237120-ca48cd10-8390-4700-98b1-4118723d0253.png)

Instead of reading "Not enough tokens." It should instead say:

>You're currently logged out.

"logged out" should be a hyperlink to: (brave://rewards)

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.48.158 Chromium: 110.0.5481.77 (Official Build) (x86_64)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | macOS Version 12.6.3 (Build 21G419)
```
