### ISSUE TITLE
Browser crashes when trying to drag vertical tab

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#27796]
## Description 

Browser crashes when I try to drag a vertical tab (single).

|Slack|https://bravesoftware.slack.com/archives/C042KL922P3/p1673587802834749|
-|-

## Steps to Reproduce

   1. Open Brave Nightly, with Vertical Tabs enabled.
   2. Add a vertical tab - could be any website.
   3. Try to drag it.

## Actual result:

https://user-images.githubusercontent.com/3684187/212258255-6d2c6841-50ca-411c-8da5-d88daa47efb2.mov

## Expected result:

No crash

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

Brave | 1.49.24 Chromium: 109.0.5414.87 (Official Build) nightly (arm64)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | macOS Version 13.1 (Build 22C65)

## Version/Channel Information:

- Can you reproduce this issue with the current release? **N/A**
- Can you reproduce this issue with the beta channel? **N/A**
- Can you reproduce this issue with the nightly channel? **Yes**

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

I reproduced with only one vertical tab.

**Comment by illtellyoulater** [comment]
Is this the reason why vertical tabs are now disabled again in stable and cannot be enabled no matter what flag we set?

**Comment by goodov** [comment]
> Is this the reason why vertical tabs are now disabled again in stable and cannot be enabled no matter what flag we set?

@illtellyoulater did you enable it here?
![image](https://user-images.githubusercontent.com/5928869/212332072-8dfbcd38-b784-4a17-9eb2-94cfda691732.png)

**Comment by illtellyoulater** [comment]
@goodov yes I later found that menu item and enabled it, but somehow in the process I lost a window which included 3 saved groups of tabs which also completely disappeared...

**Comment by sangwoo108** [comment]
> @goodov yes I later found that menu item and enabled it, but somehow in the process I lost a window with 3 saved groups of tabs which also completely disappeared...

Hi, @illtellyoulater , It might have crashed. Could you try restroing it with Control + shift + T or Commnad + shift + T ? Sorry for the inconvinience.

**Comment by illtellyoulater** [comment]
@sangwoo108 tried already, all gone, including work stuff. 
Are old windows and tabs persisted somewhere even when they are apparently no longer recoverable by the UI?

**Comment by sangwoo108** [comment]
Sorry, I'm not sure if there's a such a thing.
