### ISSUE TITLE
Set Omaha for Windows 10 only for update server for 1.48

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#27790]
## Description 

Set Omaha for Windows 10 only for update server for 1.48, Chromium major 110.
Windows 7 and 8/8.1 supported through Chromium major 109.

## Brave version (brave://version info)

1.48.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by rebron** [comment]
@mihaiplesa

**Comment by mihaiplesa** [comment]
This has been implemented in https://github.com/brave/devops/blob/master/jenkins/jobs/browser/brave-browser-updates-upload.yml#L308 and can be tested on the other channels already.
