### ISSUE TITLE
Segfault in DomainBlockNavigationThrottle

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#27791]
As per https://github.com/brave/adblock-rust/issues/248:

> add these rules to brave://settings/shields/filters
> 
> ```
> ||startpage.com^$removeparam=sc
> ||startpage.com^$removeparam=t
> ||startpage.com^$removeparam=cat
> ||startpage.com^$removeparam=abp
> ||startpage.com^$removeparam=lui
> ||startpage.com^$removeparam=qloc
> ```
> 
> Go to https://startpage.com/do/settings?query= and change the HTTP request method from POST to GET, then save the settings. Brave should crash immediately.

This is likely related to https://github.com/brave/brave-core/pull/15943

**Comment by kjozwiak** [comment]
The above requires `1.47.176` or higher for `1.47.x` verification 👍

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.47.177 Chromium: 109.0.5414.87 (Official Build) (64-bit) 
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | Ubuntu 18.04 LTS

Reproduced the issue in `1.47.169` 
<details>

![image](https://user-images.githubusercontent.com/34715963/213479894-eff08b57-5661-4d04-80c2-7a13e8581094.png)
![image](https://user-images.githubusercontent.com/34715963/213480129-5c5ba230-df77-4633-82d9-b5e82fdf1640.png)

</details>

Verified in 1.47.177
Steps:
1. Open `brave://settings/shields/filters`
1. Paste the rules below into `Create custom filters`
```
||startpage.com^$removeparam=sc
||startpage.com^$removeparam=t
||startpage.com^$removeparam=cat
||startpage.com^$removeparam=abp
||startpage.com^$removeparam=lui
||startpage.com^$removeparam=qloc
```
3. Click `Save Changes`
1. Open `https://startpage.com/do/settings?query=`
1. Change `HTTP request method` to `GET`
1. Click `Save your settings`

<details>

Saved rules:
![image](https://user-images.githubusercontent.com/34715963/213481268-48a3c9b5-3e92-46d8-acf8-f8036d1acd89.png)

Changed `HTTP request method` to `GET`
![image](https://user-images.githubusercontent.com/34715963/213481689-b0193205-9c85-48ee-8526-636f4adcd9e2.png)

No crash, settings were saved succesfully
![image](https://user-images.githubusercontent.com/34715963/213481944-ad7e7ca1-0c79-4fd0-9988-f428a22d282f.png)



</details>

**Comment by stephendonner** [comment]
## Verification `PASSED` using 

Brave | 1.47.177 Chromium: 109.0.5414.87 (Official Build) (x86_64)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | macOS Version 11.7.2 (Build 20G1020)

Confirmed crash using the below steps, in current `1.47.171` release:

<img width="1187" alt="Screen Shot 2023-01-19 at 9 18 15 AM" src="https://user-images.githubusercontent.com/387249/213515082-dd5b788e-28ec-4bef-bbe8-701e6a95d21e.png">


### Steps:
<details>

1. installed `1.47.177`
2. launched Brave
3. skipped onboarding
4. opened `brave://settings/shields/filters`
5. pasted the following rules into `Create custom filters`
```
||startpage.com^$removeparam=sc
||startpage.com^$removeparam=t
||startpage.com^$removeparam=cat
||startpage.com^$removeparam=abp
||startpage.com^$removeparam=lui
||startpage.com^$removeparam=qloc
```
6. clicked `Save changes`
7. loaded `https://startpage.com/do/settings?query=`
8. changed `HTTP request method` to `GET`
9. clicked `Save your settings`

#### Confirmed no crash

example | example | example
---------|----------|---------
<img width="1187" alt="Screen Shot 2023-01-19 at 9 11 06 AM" src="https://user-images.githubusercontent.com/387249/213515263-fc5481c4-5198-4751-a87e-eb2a596fe985.png">| <img width="1187" alt="Screen Shot 2023-01-19 at 9 11 53 AM" src="https://user-images.githubusercontent.com/387249/213515269-5e0c2d1c-f34c-43cd-9e7c-f0c5c14d6eb9.png"> | <img width="1187" alt="Screen Shot 2023-01-19 at 9 22 07 AM" src="https://user-images.githubusercontent.com/387249/213515731-a4b7678d-68e9-4ca4-9ca0-4e116f7bf480.png">



</details>

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` & `Samsung Galaxy Tab S7` using the following version(s):

```
Brave	1.47.181 Chromium: 109.0.5414.87 (Official Build) (64-bit) 
Revision	2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS	Android 13; Build/TP1A.220624.014
```
```
Brave	1.47.181 Chromium: 109.0.5414.87 (Official Build) (64-bit) 
Revision	2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS	Android 12; Build/SP2A.220305.013
```

STR: 

1. Open brave://adblock for mobile
2. Paste the rules below into Create custom filters

```
||startpage.com^$removeparam=sc
||startpage.com^$removeparam=t
||startpage.com^$removeparam=cat
||startpage.com^$removeparam=abp
||startpage.com^$removeparam=lui
||startpage.com^$removeparam=qloc
```
3. Click Save Changes
4. Open `https://startpage.com/do/settings?query=`
5. Change HTTP request method to `GET`
6. Click `Save your settings`

Example | Example | Example
-|-|-
![screenshot-1674502504428](https://user-images.githubusercontent.com/17885425/214133761-17d709f3-f76a-400e-8026-9c7f079ba887.png) | ![screenshot-1674502653901](https://user-images.githubusercontent.com/17885425/214133772-e5eef2b4-bd69-4ca6-abb8-c00c42f058ba.png) | ![screenshot-1674502675133](https://user-images.githubusercontent.com/17885425/214133775-9070ff2b-f351-4e20-a0c4-8c926f9b3900.png)

Example | Example | Example | Example
-|-|-|-
![screenshot-1674502878591](https://user-images.githubusercontent.com/17885425/214134322-e80ec06c-91fd-43cb-bf1e-5045a5974406.png) | ![screenshot-1674502928634](https://user-images.githubusercontent.com/17885425/214134324-3191575e-25c3-4074-9b56-b7e9b5d21389.png) | ![screenshot-1674502934750](https://user-images.githubusercontent.com/17885425/214134328-16cca34b-d473-475d-9ec7-73b78d90ae1d.png) | ![screenshot-1674502944497](https://user-images.githubusercontent.com/17885425/214134330-327612b8-5000-44d3-a629-529cba66be1f.png)
