### ISSUE TITLE
Make sidebar talk button activate brave talk tab from any window

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#27794]
## Steps to Reproduce

   1. Launch Brave and create two browser window1 and window2
   2. Click sidebar talk item at window1
   3. Activate window2 and click sidebar talk item

## Actual result:

Window2 create new tab for talk

## Expected result:
window 1 is activated and talk tab becomes active tab

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.49.89 Chromium: 110.0.5481.77 (Official Build) beta (x86_64)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | macOS Version 11.7.3 (Build 20G1116)

#### Followed the test plan at https://github.com/brave/brave-browser/issues/27794#issue-1531723126

### Confirmed clicking the `Brave Talk` icon in one open window (of two) doesn't spawn a third window, but focuses the `Brave Talk` window

`window1 focused` | `window2 focused` | `window1 focused`
------------|---------------------|-------------------
<img width="1680" alt="Screen Shot 2023-02-08 at 12 22 56 AM" src="https://user-images.githubusercontent.com/387249/217475014-3fa6a29e-298b-4315-b0f9-2b510b6785c4.png"> | <img width="1680" alt="Screen Shot 2023-02-08 at 12 24 06 AM" src="https://user-images.githubusercontent.com/387249/217475021-f1b127b2-2b37-42e1-ac38-f2970cba8fc8.png"> | <img width="1667" alt="Screen Shot 2023-02-08 at 12 24 37 AM" src="https://user-images.githubusercontent.com/387249/217475024-496c23f2-2a12-4615-9e8f-3c1712dcec7b.png">
