### ISSUE TITLE
Brave makes request to update.googleapis.com (January 2023) and google.com (March 2023) on start-up

### ISSUE THREAD

**Issue by guser56789** [brave/brave-browser#27797]
## Description 
Brave makes request to update.googleapis.com on startup. Fixed sometime ago but has started happening again recently.

Maybe related to:
https://github.com/brave/brave-browser/issues/2280

## Steps to Reproduce
Launch Brave. Observe network connections.

## Actual result:
Brave makes connection to update.googleapis.com

## Expected result:
Brave should not connect to any non-Brave servers.

## Reproduces how often: 
Every single time Brave is launched.

## Brave version (brave://version info)
1.47.171 Chromium: 109.0.5414.87 (Official Build) (x86_64) 
macOS Version 12.6.2

## Version/Channel Information:
- Can you reproduce this issue with the current release? Yes.
- Can you reproduce this issue with the beta channel? Didn't try.
- Can you reproduce this issue with the nightly channel? Didn't try.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Didn't try.
- Does the issue resolve itself when disabling Brave Rewards? Didn't try.
- Is the issue reproducible on the latest version of Chrome? Didn't try.

**Comment by ShivanKaul** [comment]
@guser56789 can you check if Widevine setting is turned on in brave://settings/extensions?

**Comment by guser56789** [comment]
> @guser56789 can you check if Widevine setting is turned on in brave://settings/extensions?

Yes, it is turned on because I need it on to use streaming websites.

I have read https://github.com/brave/brave-browser/issues/27866 and hopefully the call to Google for Widevine will be proxied as well in the future. Thanks!

**Comment by guser56789** [comment]
It has gotten worse. I assume Brave updated itself recently (currently on Version 1.49.128 Chromium: 111.0.5563.110 (Official Build) (x86_64)), and since then Brave not only connects to googleapis.com on start-up, it also connects to google.com.......

**Comment by InHosticus** [comment]
This is still (or again) happening on startup and with each new tab opened.

Brave version :  [Version 1.74.51 Chromium: 132.0.6834.160 (Official Build) (64-bit)]

Wireshark screen shot attached.

![Image](https://github.com/user-attachments/assets/0b72dca0-0048-4976-bb91-1a85b4b7748f)
