### ISSUE TITLE
(Wallet) Add SVG support to NFT images

### ISSUE THREAD

**Issue by simoarpe** [brave/brave-browser#27800]
The Android framework does not support SVG images out of the box. 
We are already using Glide, so a possible option would be to implement a custom SVG decoder using Glide, as explained in the official Glide [examples](https://github.com/bumptech/glide/tree/master/samples/svg). 
This solution would require an [external library](https://github.com/BigBadaboom/androidsvg) to include into the codebase.

**Comment by diracdeltas** [comment]
cc @kdenhartog @thypon for security considerations

**Comment by simoarpe** [comment]
@diracdeltas, @kdenhartog, @thypon, requested security review: https://github.com/brave/security/issues/1202

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.51.97 x64 Beta build
- Verified steps from [brave/brave-core#17330](https://github.com/brave/brave-core/pull/17330)
- Verified able to add the specified NFT (https://opensea.io/assets/ethereum/0xff9c1b15b16263c61d017ee9f65c50e4ae0113d7/6114) to visible asset list 
- Verified NFT image shows up under NFT Tab
- Verified clicking on the NFT loads the NFT details screen and loads the image correctly 

https://user-images.githubusercontent.com/17010094/234473596-ccd0bb45-1d9c-4aa3-a5a2-98f6738084f1.mp4
