### ISSUE TITLE
Android bookmark widgets display incorrectly when minimized vertically 

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#27801]
## Description 
If the Brave "Bookmarks" widget shows incorrectly sized icons. This is especially apparent if the widget is resized to be only a single row (displaying just the icon):
![image](https://user-images.githubusercontent.com/3299098/212385297-d25b747b-2847-40e0-9d21-41e797f19649.png)

## Steps to reproduce 

   1. Add "Bookmarks" widget to Android home screen in Beta/Nightly
   2. Observe incorrectly sized icons

## Issue reproduces how often 
Easily/every time

## Version/Channel Information:

v1.48.122
v1.49.24

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? Yes 
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: Android 12
  

### Additional information

Internal Convo: https://bravesoftware.slack.com/archives/C0816QH3R/p1673630441127669
User report: https://old.reddit.com/r/brave_browser/comments/105mw6r/widgets_in_beta_are_very_bad/
cc @deeppandya

**Comment by kjozwiak** [comment]
As per the discussion on Slack re: the above, we'll keep pushing out `1.47.x` but keep an eye on user reports via the support team. If we notice an influx of reports, we'll push the above via a HF. For now, we're going to get this into the `1.47.x` maintenance release that's schedule for `January 25` as per https://github.com/brave/brave-browser/wiki/Brave-Release-Schedule#release-channel-dates.

**Comment by kjozwiak** [comment]
The above requires `1.47.178` or higher for `1.47.x` verification 👍

**Comment by krakah** [comment]
Looking forward to the 1/25 update.    As someone who just bookmarks a site rather than downloading an intrusive app with the same functionality, this has made my homescreen look really silly!

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version:

```
Brave	1.47.181 Chromium: 109.0.5414.87 (Official Build) (64-bit) 
Revision	2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS	Android 13; Build/TP1A.220624.014
```
**Test Plan:** 

1. Install 1.47
2. Add bookmark widget to the home screen
3. Resize widget vertically to 1 column

- Verified resizing widget down to 1 column displays bookmark favicons correctly

Default | Vertical | Horizontal
-|-|-
![screenshot-1674493863677](https://user-images.githubusercontent.com/17885425/214106941-90ae8d3a-4a51-4c4a-bcec-5b70e9119473.png) | ![screenshot-1674493872884](https://user-images.githubusercontent.com/17885425/214106969-5da49c41-f52e-4f2d-9a46-2c74c6fb014b.png) | ![screenshot-1674493906902](https://user-images.githubusercontent.com/17885425/214106985-564eced1-b2e8-416f-9aca-8b8070168684.png)

**Comment by iamgitcat** [comment]
Since 1.47 the size of icons is smaller, but they are not centered. It looks bad, but better than before. Beta version looks like it always was, the old good way.![Screenshot_20230125-103709.jpg](https://user-images.githubusercontent.com/83538283/214505978-903e1f11-274c-4d22-85f8-6089c0c42e04.jpg)

**Comment by krakah** [comment]
Fixed with latest update.  My homescreen us normal again.

**Comment by iamgitcat** [comment]
Latest update fixed both release and beta. Thank you!
