### ISSUE TITLE
Wallet / Swap: Zero/reset the asset amount when the user changes asset/currency

### ISSUE THREAD

**Issue by lukemulks** [brave/brave-browser#27816]
## Description 

This may be partially related to #27815, but seems like a candidate for a standalone issue. 

When using Swap, after inputting a swap amount for a specific currency/token, if I go to change that specific asset/currency/token to a different token/currency from the asset list, the amount I input persists. 

This isn't really an ideal UX, as if I'm changing from one asset to swap to another, the asset amount should reset to zero to avoid user confusion.

## Steps to Reproduce

   1. From Brave Wallet, select Swap
   2. Input a Swap amount for a specific asset to receive a quote. For example, input 1 ETH as the amount to swap for equiv value of BAT.
   3. The user changes their mind, and decides they'd prefer to swap 500 $USDC instead of 1 ETH. User changes the Swap asset at top from ETH to USDC. 
   4. When the user changes the Swap asset from 1 ETH to USDC, the `1` value persists, as opposed to either resetting to 0, or updating with the equivalent value of 1 ETH in USDC. Ideally, this would just reset to 0 when a user changes their mind and decides to make a swap with a different asset from their wallet. 
   
   Here's step by step in an ideal scenario imo: 
   1. User wants to swap 1 ETH for equiv value of BAT. 
   2. User selects ETH, and inputs 1 as swap value; user also selects BAT as the asset to swap into. 
   3. User changes their mind, switching from ETH as the asset to swap, to USDC; user still wants to swap into BAT, but wants to select 500 USDC to BAT instead of the original 1 ETH to BAT
   4. When the user changes the asset from ETH to USDC, the `1` value that the user input into the Swap should ideally reset to `0`, requiring the user to input the amount of USDC they'd like to swap to BAT.

## Actual result:

- User inputs 1 ETH to swap to equiv value in BAT
- User changes their mind, switching to USDC to swap into equiv value in BAT
- User observes that the price quote is for 1 USDC to equiv value of BAT, as they had previously input 1 ETH for the original swap quote

## Expected result:
- When a user changes their mind about which asset they'd like to swap to another, the Swap feature should zero/reset the original value that was input by the user, requiring them to input a fresh value for the new asset they selected to swap from their wallet.

## Reproduces how often: 

100%

## Brave version (brave://version info)

1.49.27 Chromium: 109.0.5414.87 (Official Build) nightly (64-bit) 
Windows 11

## Version/Channel Information:

- Can you reproduce this issue with the current release? TBD
- Can you reproduce this issue with the beta channel? TBD
- Can you reproduce this issue with the nightly channel? CONFIRMED

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

I suspect @onyb is the right team member to tag on this one, so will assign, but also cc'ing @Douglashdaniel @jamesmudgett @husobee for visibility.

Have not tested this on mobile/android, only desktop/Win11 and only Nightly

**Comment by kjozwiak** [comment]
The above requires `1.48.166` or higher for `1.48.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.48.166 Chromium: 110.0.5481.100 (Official Build) (64-bit)
-- | --
Revision | `4be7a36f7cb943af6118e449bbab494b43dcaddd-refs/branch-heads/5481_77@{#14}`
OS | Windows 11 Version 22H2 (Build 22621.1265)

- Verified steps from issue description
- Verified asset amount is reset when user changes the asset currency

https://user-images.githubusercontent.com/17010094/219612948-a6ef682e-acb9-4b95-9784-5fc0d09114ff.mp4
