### ISSUE TITLE
Windows 7 and portable

### ISSUE THREAD

**Issue by harryray33** [brave/brave-browser#27818]
Which is (or will be) the last version to support Win 7?
Is Brave portable?

**Comment by joejoejo** [comment]
I believe it's fallowing chromes release schedule for that

**Comment by rebron** [comment]
Hi @harryray33. 1.47.x versions will be the last supported versions for Windows 7. The latest is 1.47.171 and we have one more planned for next Wednesday. https://support.brave.com/hc/en-us/articles/11197967945613-Sunsetting-support-for-Windows-7-and-8-8-1

**Comment by harryray33** [comment]
Thanks, I notice that the latest is v1.47.186 is this the last one to work with Win 7 and when will the final release be, as it says that v1.47.186 is pre-release?
