### ISSUE TITLE
Keyboard shortcuts not working with vertical tabs and multiple windows

### ISSUE THREAD

**Issue by spasche** [brave/brave-browser#27812]
## Description 

When switching focus between two browser windows, the keyboard shortcuts stop working.

## Steps to Reproduce

   1. Enable vertical tabs
   2. Go to any website (this doesn't happen on the New Tab page)
   3. Open a new browser window
   4. Move the new window to show the previous browser window
   5. Click on the tab from the previous browser window
   6. Try to use a keyboard shortcut such as Ctrl+T to open a new tab

## Actual result:

The keyboard shortcuts don't work. You have to click either inside of the page content or address bar to have them work again.

## Expected result:

Keyboard shortcuts should work after clicking on the original tab.

## Reproduces how often: 

Happens every time.

## Brave version (brave://version info)

```
Brave | 1.49.27 Chromium: 109.0.5414.87 (Official Build) nightly (64-bit)
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | Windows 11 Version 22H2 (Build 22621.963)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Not applicable

**Comment by shahnawaz323** [comment]
When I press option+Command+arrow to switch tabs on MacOS it shifts to the tabs groups. I wanted the normal behaviour to switch tabs when vertical tabs flag is enabled.
