### ISSUE TITLE
Some `$removeparam` filter rules are not being applied to document requests

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#27819]
Reports from the community:

- https://old.reddit.com/r/brave_browser/comments/10ahpuq/removeparam_not_working_in_filter_lists/
- https://community.brave.com/t/will-the-new-removeparam-feature-work-with-custom-filter-lists/462558/5?u=fmarier
- https://github.com/brave/adblock-rust/issues/247

This can be fixed by updating `adblock-rust` to v0.6.2 - see https://github.com/brave/adblock-rust/commit/8a755bdb190bb55a3a3acee1e6507085051bdeec

**Comment by kjozwiak** [comment]
The above requires `1.47.176` or higher for `1.47.x` verification 👍

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.47.177 Chromium: 109.0.5414.87 (Official Build) (64-bit) 
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | Ubuntu 18.04 LTS

Reproduced the issue in `1.47.169` using test plan from https://github.com/brave/brave-core/pull/16682

<details>

Applied rules
![image](https://user-images.githubusercontent.com/34715963/213484348-3f5ff2ce-1a7d-4f1f-b911-166e6898acf7.png)
parameter `irgwc` is still visible in the URL
![image](https://user-images.githubusercontent.com/34715963/213484534-486aed87-43b2-48d7-aefa-76cb46410e70.png)



</details>

Verified in 1.47.177 using test plan from https://github.com/brave/brave-core/pull/16682

<details>

Applied rules:
![image](https://user-images.githubusercontent.com/34715963/213485541-9e1a859a-5b79-4a44-b535-fe8cccd6963d.png)


parameter `irgwc` is removed
![image](https://user-images.githubusercontent.com/34715963/213485681-4a03b258-be00-4f20-8d37-4f9360f1b42c.png)


</details>

**Comment by stephendonner** [comment]
## Verification `PASSED` using 

Brave | 1.47.177 Chromium: 109.0.5414.87 (Official Build) (x86_64)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | macOS Version 11.7.2 (Build 20G1020)

Reproduced in 1.47.171 using testplan from https://github.com/brave/brave-core/pull/16682#issue-1533509846 

<img width="1097" alt="Screen Shot 2023-01-19 at 10 07 46 AM" src="https://user-images.githubusercontent.com/387249/213526016-e08f708c-ee7f-4374-b407-d2d9ef52f2ca.png">

### Steps:
1. installed `1.47.177`
2. launched Brave
3. opened a new-tab page
4. opened `brave://settings/shields/filters`
5. pasted `https://filters.adtidy.org/windows/filters/17.txt` in the `Add custom filter lists` textbox
6. clicked `Add`
7. opened a new-tab page
8. loaded `https://www.agoda.com/?site_id=1887945&irgwc=1`

#### Confirmed `irgwc=1` is not shown in the URL

steps 5-6|step 8
-----|-----
<img width="1097" alt="Screen Shot 2023-01-19 at 10 10 51 AM" src="https://user-images.githubusercontent.com/387249/213526062-ea922758-9bb1-4b19-8dfa-2e281296c16d.png"> | <img width="1097" alt="Screen Shot 2023-01-19 at 10 10 40 AM" src="https://user-images.githubusercontent.com/387249/213526097-9fd9a75b-7069-4dd9-bafa-068544a0aa74.png">

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` & `Samsung Galaxy Tab S7` using the following version(s):

```
Brave	1.47.181 Chromium: 109.0.5414.87 (Official Build) (64-bit) 
Revision	2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS	Android 13; Build/TP1A.220624.014
```
```
Brave	1.47.181 Chromium: 109.0.5414.87 (Official Build) (64-bit) 
Revision	2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS	Android 12; Build/SP2A.220305.013
```

STR: https://github.com/brave/brave-core/pull/16682#issue-1533509846

Verified `irgwc=1` does not appear in the URL after loading https://www.agoda.com/?site_id=1887945&irgwc=1

Custom Filters | Test URL
-|-
![screenshot-1674501586938](https://user-images.githubusercontent.com/17885425/214131265-5eb9df7d-1d09-44c0-9470-9c53a967e5ed.png) | ![screenshot-1674501727184](https://user-images.githubusercontent.com/17885425/214131270-a58d4ff2-c076-4c3d-982c-f787c70428c5.png)
![screenshot-1674502079601](https://user-images.githubusercontent.com/17885425/214131770-383b8590-3824-4e12-bb55-91850f433dc5.png) | ![screenshot-1674502123240](https://user-images.githubusercontent.com/17885425/214131775-ce0fd10b-8bf9-4154-80bd-557aaee2d04a.png)
