### ISSUE TITLE
Adding a device to sync chain doesn't enable sync on Linux instantly 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#2782]
## Description 

Adding a device to sync chain doesn't enable sync on Linux instantly. Goes back to the Sync welcome screen. Leaving the page open for a min then shows the device details 

## Devices
Sync chain creator: 0.59.14 on Ubuntu
Sync chain device2: Samsung Tab running 1.0.72(sync1)

## Steps to Reproduce

   1. Clean profile on 0.59.14
   2. Enable Sync from hamburger menu
   3. Add a Mobile device on sync creation process
   4. Scan the QR code on the mobile device, wait for the sync chain to be created. Android device shows Linux desktop as listed device but sync doesn't enable on Linux desktop
   5. Click ok to close the modal on desktop, Device is removed from the list 
   6. Open `brave://sync` in a new tab, wait for ~1 min, sync is enabled on Linux

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/50586806-300a0f80-0ea1-11e9-9f25-0d2794e886ef.png)
![image](https://user-images.githubusercontent.com/17010094/50586835-5039ce80-0ea1-11e9-994d-a04ca9523d8b.png)

## Expected result:
Should enable sync instantly when a second device is added to the sync chain

## Reproduces how often: 

Easy, Was able to reproduce the issue 4 times 

## Brave version (brave://version info)

Brave | 0.59.14 Chromium: 72.0.3626.28 (Official Build) beta(64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes on beta

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
N/A
- Is the issue reproducible on the latest version of Chrome? 
N/A

### Additional Information

cc: @brave/legacy_qa @rebron

**Comment by AlexeyBarabash** [comment]
https://github.com/brave/brave-core/pull/1188 should fix the issue.

**Comment by srirambv** [comment]
@AlexeyBarabash what is the expected time duration with the fix? I see its take around 8secs on my machine to list the sync page. Is this expected time or should it be faster?

**Comment by srirambv** [comment]
Verification passed on based on https://github.com/brave/brave-browser/issues/2742#issuecomment-455516376

Brave | 0.59.25 Chromium: 72.0.3626.53 (Official Build) beta(64-bit)
-- | --
Revision | 98434e6cd182d68ce396daa92e9c6310422e6763-refs/branch-heads/3626@{#620}
OS | Linux

**Comment by AlexeyBarabash** [comment]
@srirambv the expected time duration 1 sec to fetch + <delay for over network data transfer netween device2=>AWS=>device2>. The second part of the amount hard to estimate.  I observed < 2 sec. Just in case I wrote in issue 5 sec.  8 sec seems ok, as it is much faster then before the PR.

Thanks @srirambv .
