### ISSUE TITLE
Implement Edit NFTs feature

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#27830]
[Figma Link](https://www.figma.com/file/RVo44kBYw70oNYBEpVzDh4/NFT?node-id=1%3A52&t=kIpNtqt68OAinZm9-1)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.50.94 Chromium: 111.0.5563.64 (Official Build) beta (64-bit) 
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Linux

- Verified steps from [brave/brave-core#16934](https://github.com/brave/brave-core/pull/16934)
- Verified able to edit NFT via the menu
- Encountered [#29011](https://github.com/brave/brave-browser/issues/29011) & [#29199](https://github.com/brave/brave-browser/issues/29199)

https://user-images.githubusercontent.com/17010094/226532328-c5dbbaab-aa95-480d-a293-d5e7507e3010.mp4

---------------------

Verification passed on 

Brave | 1.50.94 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from [brave/brave-core#16934](https://github.com/brave/brave-core/pull/16934)
- Verified able to edit NFT via the menu
- Encountered [#29011](https://github.com/brave/brave-browser/issues/29011) & [#29199](https://github.com/brave/brave-browser/issues/29199)

https://user-images.githubusercontent.com/17010094/226532272-17559d2f-70dc-4fff-861d-b536f9edf052.mp4

---------------------

Verification passed on 

Brave | 1.50.94 Chromium: 111.0.5563.64 (Official Build) beta (arm64)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#16934](https://github.com/brave/brave-core/pull/16934)
- Verified able to edit NFT via the menu
- Encountered [#29011](https://github.com/brave/brave-browser/issues/29011) & [#29199](https://github.com/brave/brave-browser/issues/29199)

https://user-images.githubusercontent.com/17010094/226533017-bcca095d-731b-4498-af76-41cf7304c157.mov
