### ISSUE TITLE
Change "Start using Rewards" text on Rewards NTP widget (January 2023)

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#27845]
## Description

When Brave Private Ads is disabled but Rewards has already been enabled, the following message appears:

![image](https://user-images.githubusercontent.com/11497541/212777732-8f007013-0586-410f-b15a-48e4f331fbf6.png)

This text should be changed to specifically refer to Brave Ads, and not Rewards in general. 

## Solution

Change to "Enable Brave Ads"

**Comment by deeppandya** [comment]
@Miyayes i don't think this issue is related to android.

**Comment by mkarolin** [comment]
QA Test Steps:
1. Start Brave
2. Join Rewards
3. Navigate to brave://rewards and toggle the ads off
4. Navigate to a new tab page and observe the Rewards widget.
