### ISSUE TITLE
cache wallet transaction data within the walletApi Redux slice

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#27869]
## Description 

Caching the transaction data will prevent unneeded lookups from core.
Provide mutations in order to update the invalidate when needed.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta  (64-bit)
-- | --
Revision | `46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#16711](https://github.com/brave/brave-core/pull/16711)
- Verified wallet transactions work as expected
- Verified swaps work fine as expected
