### ISSUE TITLE
Brave does not save Shields settings (Windows 10 and 11)

### ISSUE THREAD

**Issue by Jeffrey-Sardina** [brave/brave-browser#27860]
## Description 
Brave does not save Shield settings after closing and re-opening the browser.

## Steps to Reproduce

   1. Open Brave, go to Brave Sheilds
   2. Set fingerprinting proction to strict and ad blocking to aggressive
   3. Restart Brave and re-open Shields; observe that both are now set to Standard

## Actual result:
Brave Sheilds settings do not save and revert to default when the browser is opened

## Expected result:
That Brave Shield settings be saved after they are changed and the browser is re-opened

## Reproduces how often: 
Always occurs

## Brave version (brave://version info)
1.47.171 Chromium: 109.0.5414.87 (Build oficial) (64 bits)

**Comment by rebron** [comment]
Hi @Jeffrey-Sardina The changes to Shields when using the Shields panel will only apply to the current site you're on. If you want to make a global change you'll need to go to brave://settings/shields for all websites going forward.

After that change, do you still an issue with the settings sticking?

**Comment by Jeffrey-Sardina** [comment]
Hello!

That is where I was making the changes; when I switched them to strict there, they did not save

**Comment by Jeffrey-Sardina** [comment]
I figured it out -- it seems to becoming from (most likely no intentionally) deleting data when the browser closes. When I select "delete site and Sheilds settings" it resets the global settings to their defaults every time for Shields, not just specific site data. So I got what I want working now -- although I am not sure if this (somewhat unintuitive to me) behaviour was desired.

**Comment by DesignerOff** [comment]
Nice spot. Can we get a split of these two settings?

**Comment by rebron** [comment]
Closing per last comment from author https://github.com/brave/brave-browser/issues/27860#issuecomment-1405391359.
