### ISSUE TITLE
Support `:has` pseudoclass in cosmetic filters

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#27874]
The `:has` pseudoclass is now a stable Chromium feature. It's used by a fairly large number of [cosmetic filters](https://github.com/brave/brave-browser/issues/16935#issuecomment-1097235837), so it'd be good to support it natively (as if it weren't a procedural filter) before full procedural filtering support is available.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.49.89 Chromium: 110.0.5481.77 (Official Build) beta (64-bit)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | Windows 11 Version 21H2 (Build 22000.1455)
```

1. Install 1.49.89
2. launch Brave
3. Visit https://metager.org/meta/meta.ger3?eingabe=software%20testing&focus=web&mgv=31901855042b9c5b2820d821141a7be9
4. click on Shields icon to open Shields panel
5. confirmed `Block trackers & ads` setting displayed
6. confirmed `green` `partnershop` labels displayed to the right of the URL in the results list for `Block trackers & ads` setting
      - codecademy.com/.../blog/what-is-software-testing
      - tutorialspoint.com/software_testing/index.htm
      - edureka.co/blog/what-is-software-testing
10. change the setting to `Aggressively block trackers & ads` in the shields panel
11. confirmed the entries previously labeled with `green` `partnership` labels (step 6) are no longer visible.

`standard blocking`| `aggressive blocking`
----  | ----
---- | ---- 
<img width="941" alt="image" src="https://user-images.githubusercontent.com/98358127/217619316-6f04c113-f7e9-4d49-af35-7e1f2239d6f0.png">|<img width="944" alt="image" src="https://user-images.githubusercontent.com/98358127/217619375-cda3e3d2-888e-4315-9dbc-63648aa90d37.png">
<img width="941" alt="image" src="https://user-images.githubusercontent.com/98358127/217618878-b99dc665-2f4c-4e24-8d3c-cf69fddb1571.png">|<img width="941" alt="image" src="https://user-images.githubusercontent.com/98358127/217618872-59b08a5d-0f4c-4029-845b-d5f7a65b6b9a.png">

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.49.90 Chromium: 110.0.5481.77 (Official Build) beta (x86_64)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | macOS Version 11.7.3 (Build 20G1116)

Followed the steps to reproduce and test plan from https://github.com/brave/brave-core/pull/16716#issue-1537347090

#### Confirmed `codecademy` and `tutorialspoint` (and others) so-called `partnershop` ads are removed


`standard blocking`| `aggressive blocking` (no `codecademy`, no `tutorialspoint`)
----  | ----
---- | ---- 
<img width="1312" alt="Screen Shot 2023-02-08 at 4 08 44 PM" src="https://user-images.githubusercontent.com/387249/217681584-19704373-14de-42d3-a5f1-7702d0f9fb0d.png"> | <img width="1312" alt="Screen Shot 2023-02-08 at 4 16 58 PM" src="https://user-images.githubusercontent.com/387249/217681711-b7275fb5-045d-4cf7-a191-09e2d97e3db7.png">
<img width="1312" alt="Screen Shot 2023-02-08 at 4 10 19 PM" src="https://user-images.githubusercontent.com/387249/217681758-79c7693c-edef-4952-8dd4-066dd239036d.png"> | <img width="1312" alt="Screen Shot 2023-02-08 at 4 20 55 PM" src="https://user-images.githubusercontent.com/387249/217681982-6d09ca7f-dfc3-4645-a4c7-7047245f8090.png">

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.49.114 Chromium: 110.0.5481.177 (Official Build) beta (64-bit) 
Revision	f34f7ab2d4ca4ad498ef42aeba4f4eb2c1392d63-refs/branch-heads/5481@{#1239}
OS	Linux
```

**Comment by 424344** [comment]
so this fix will finally enable in brave android the blocking of "promoted" ads on reddit and 9gag?

**Comment by antonok-edm** [comment]
@424344 that should be the case!

**Comment by 424344** [comment]
thanks!

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Samsung Galaxy version 12` running `Bravemonoarm64.apk_1.49.118`

Verified the test plan from https://github.com/brave/brave-core/pull/16716#issue-1537347090.

Reproduced the issue using 1.48.171, green "Partnership" ads visible under both options:

Standard | Aggressive
---- | ----
![Screenshot_20230307-181538_Brave](https://user-images.githubusercontent.com/38657976/223427064-539e7039-80f2-41ea-ba78-60790aaf4e66.jpg) | ![Screenshot_20230307-181516_Brave](https://user-images.githubusercontent.com/38657976/223427103-b7b24754-04d3-4c66-8e5e-f9e444cab685.jpg)


Verified using 1.49.x, green "Partnership" ads only visible under Standard, not Aggressive:

Standard | Aggressive | Aggressive | Aggressive
---- | ----|-----|----
![Screenshot_20230307-181704_Brave](https://user-images.githubusercontent.com/38657976/223427147-045ee867-bb69-4ddf-9917-5f6ed5aebf59.jpg) | ![Screenshot_20230307-181746_Brave](https://user-images.githubusercontent.com/38657976/223427195-8b1cdd49-17bd-4f3b-8b2e-d615142344dc.jpg) | ![Screenshot_20230307-181752_Brave](https://user-images.githubusercontent.com/38657976/223427284-b4439de2-506e-4bb5-b4b3-7687645d57ed.jpg) | ![Screenshot_20230307-181758_Brave](https://user-images.githubusercontent.com/38657976/223427324-446414a8-4373-463f-8052-a105352ac82b.jpg)
