### ISSUE TITLE
Selecting unsupported tokens should disable `Continue to Ramp` button

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#27876]
## Description 
Selecting unsupported tokens should disable `Continue to Ramp` button

## Steps to reproduce 

   1. Add Link token to visible assets
   2. Open token details page 
   3. Click on Buy button in token details page
   4. Click on `Continue to Ramp` button
   5. Page loads but errors out

## Actual result 
Page errors with invalid instruction when an unsupported token is selected 

## Expected result
Disable `Continue to Ramp` button so user isn't navigated to the landing page which errors out. On Desktop it doesn't show the buy button but has the `Select purchase method` button which when clicked doesn't show the `Buy with Ramp` button

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Tablet
   - Android version: 12
   
## Brave version
1.49.36 x64 Nightly 

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @Pavneet-Sing @jamesmudgett @kleantzogu

**Comment by Pavneet-Sing** [comment]
Note: we cannot re-select an unsupported asset on Buy screen so hiding `buy` for asset details screen should fix this issue.

[buy-asset.webm](https://user-images.githubusercontent.com/11755381/213159229-b6a82c17-b96e-4b37-a753-03e4d39a9ce4.webm)

**Comment by kjozwiak** [comment]
The above requires `1.47.178` or higher for `1.47.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on the following devices running 
- Verified steps from [ brave/brave-core#16718](https://github.com/brave/brave-core/pull/16718)
- Verified tokens that doesn't support on-ramp doesn't show Buy button
- Verified unsupported tokens are not show in the drop down list of Buy tokens

Oppo Reno 5 (Android 13) | Lenovo Tab (Android 12)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/214062747-db9e38e2-a534-4467-9144-186e6d50c21f.mp4> | <video  src=https://user-images.githubusercontent.com/17010094/214062769-2302fa84-6bb7-437d-a6ef-dfe6312fce40.mp4>
