### ISSUE TITLE
Add separator to sidebar context menu between `Show Sidebar` and `Position`

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#27880]
F/u issue for https://github.com/brave/brave-browser/issues/27160

Sidebar context menu should have separator above the `Position` like below

![image](https://user-images.githubusercontent.com/6786187/213113199-ab05bf65-a2da-450d-a333-ac924383496e.png)

figma - https://www.figma.com/file/xOdKFSr3P5AXSAbP2r8ung/Sidebar-Desktop?node-id=3716%3A71686&t=yQuSi89twoq6zePW-0

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.48.139 Chromium: 109.0.5414.87 (Official Build) beta (x86_64)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | macOS Version 11.7.2 (Build 20G1020)

### Steps:
1. installed `1.48.139`
2. launched Brave
3. context-clicked on the sidebar
4. noted the added separator `___________` line between the `Show sidebar` and `Position` sections

`Sidebar left` | `Sidebar right`
--------------|----------------
<img width="242" alt="Screen Shot 2023-01-24 at 10 37 34 PM" src="https://user-images.githubusercontent.com/387249/214497597-25d497f4-0a06-4802-a64e-28aa91af78e7.png"> | <img width="210" alt="Screen Shot 2023-01-24 at 10 38 19 PM" src="https://user-images.githubusercontent.com/387249/214497599-4bb5792d-62d4-4345-b396-19dec7799e71.png">
