### ISSUE TITLE
How to use "Brave Rewards" behind the proxy/VPN installed in the browser

### ISSUE THREAD

**Issue by TontyTon** [brave/brave-browser#2788]
## Description 
I use proxy (using browser extension) and don't want to connect directly to the internet.
Brave Rewards doesn't work with it, as I had blocked all non proxy connections.
I want to use Brave Rewards with proxy.

## Steps to Reproduce

   1. Disable all non proxy connections for brave.exe using Windows Firewall
   2.  Go to chrome://rewards/
   3.  Click on Yes I'm Ready

## Actual result:
Error - Wallet creation failed - Please check your Internet connection.

## Expected result:
Wallet is created and Brave Rewards works normally.

## Reproduces how often: 
Always

## Brave version (brave://version info)
0.58.18 Chromium: 71.0.3578.98 (Official Build) (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields?  - No
- Is the issue reproducible on the latest version of Chrome? - Not relevant

**Comment by TontyTon** [comment]
Can I expect this feature to be available in future?

I am astonished that there are not many proxy users on a 'privacy browser', or they don't want to help content providers.

**Comment by tomlowenthal** [comment]
It's not completely clear to me what's happening here. I *think* that either your proxy is deny-listed or the proxy extension isn't proxying everything right. What extension are you using?

**Comment by TontyTon** [comment]
@tomlowenthal , I have tried many VPN extension, non of them work. I think the problem is that user installed extensions don't have enough privilege.
For example - user installed extensions don't work on [Chrome Webstore](https://chrome.google.com/webstore) (_but brave shields work their_)

**Comment by tomlowenthal** [comment]
This doesn't help to distinguish whether the VPN is on Brave Rewards' deny-list or whether extensions can't capture Brave Rewards traffic.

**Comment by NejcZdovc** [comment]
cc @tomlowenthal

**Comment by NejcZdovc** [comment]
not sure if anything can be done in rewards code to fix this

**Comment by TontyTon** [comment]
now it works, from last 2-3 updates. Thanks
