### ISSUE TITLE
The new profile installs some extensions by default

### ISSUE THREAD

**Issue by tafeilgh** [brave/brave-browser#27896]
## Description 
The new profile installs some extensions by default

## Steps to Reproduce

   1. create a new profile
   2. Some extensions are already installed, Avira Browser Safety, Avira Password Manager, Avira Safe Shopping. I have already uninstalled avira

## Actual result:

![newbrave](https://user-images.githubusercontent.com/100503528/213372987-c03bd2bb-3abe-4de2-b98b-db29213f6678.PNG)

## Expected result:

No more default installation of extensions

## Brave version (brave://version info)

1.47.171

**Comment by diracdeltas** [comment]
this is probably due to you installing Avira at some point in the past. the answer in https://superuser.com/a/1548310 might help to remove it permanently.
