### ISSUE TITLE
TokenDetailsModal is missing localized strings

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#27890]
## Description 
The `TokenDetailsModal` is missing localized strings

https://github.com/brave/brave-core/blob/master/components/brave_wallet_ui/components/desktop/views/portfolio/components/token-details-modal/token-details-modal.tsx#L63-L85

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta  (64-bit) 
-- | --
Revision | `46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}`
OS | Linux

- Verified steps from [brave/brave-core#16727](https://github.com/brave/brave-core/pull/16727)
- Verified token details modal has translated string

https://user-images.githubusercontent.com/17010094/221844589-cc660725-dced-498e-b16b-fab36c328e84.mp4
