### ISSUE TITLE
Unable to Hide NFTs with the same contract address

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#27906]
## Description 

If you try to hide an NFT with the same contract address it will either uncheck all or not check at all

## Steps to Reproduce

   1. Add 2 NFT's with the same contract address
   2. Open the Edit visible assets modal
   3. Try to hide one of them, it will either uncheck all or not check at all.

## Actual result:

https://user-images.githubusercontent.com/40611140/213518899-1eaedea1-8982-4ebd-b56d-78cc40feea71.mov

## Expected result:
You should be able to hide individual NFT's with the same contract address.

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta  (64-bit) 
-- | --
Revision | `46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}`
OS | Linux

- Verified steps from [brave/brave-core#16750](https://github.com/brave/brave-core/pull/16750)
- Verified able to hide and show NFT's from the same contract address

https://user-images.githubusercontent.com/17010094/221812775-b2da995a-df67-4de9-94bf-4604e163d674.mp4

---------------------

Verification passed on 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta  (64-bit)
-- | --
Revision | `46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#16750](https://github.com/brave/brave-core/pull/16750)
- Verified able to hide and show NFT's from the same contract address

https://user-images.githubusercontent.com/17010094/221812837-79b160a2-0511-49eb-a215-e3e419aec5dd.mp4

---------------------

Verification passed on 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta  (arm64)
-- | --
Revision | `46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#16750](https://github.com/brave/brave-core/pull/16750)
- Verified able to hide and show NFT's from the same contract address

https://user-images.githubusercontent.com/17010094/221814001-e5b02d17-f0f0-48a8-a36b-1e0b41cfcacc.mov
