### ISSUE TITLE
[Rewards 2.5-3] Rewards panel not showing # of visited verified creators component

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#27907]
## Description

The count of visited verified sites/channels in the non-connected 2.5 panel does not count tabs that were already open before Rewards was enabled, and some other conditions (@zenparsing). 

Issue runs deeper into Rewards code, as it has to do with A-C itself, and this counter depends on the counting that A-C does.

Tangentially related: https://github.com/brave/brave-browser/issues/27936

**Comment by LaurenWags** [comment]
Labelling as `QA/Blocked`, reached out to @Miyayes @zenparsing re: test plan.

**Comment by LaurenWags** [comment]
Removing `QA/Blocked`, test plan was added via https://github.com/brave/brave-core/pull/16774#issue-1551389184

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.49.100 Chromium: 110.0.5481.100 (Official Build) beta (64-bit)
-- | --
Revision | 4be7a36f7cb943af6118e449bbab494b43dcaddd-refs/branch-heads/5481_77@{#14}
OS | Windows 10 Version 21H2 (Build 19044.2486)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/16774#issue-1551389184

**Comment by GeetaSarvadnya** [comment]
Verification **Inprogress** on `Samsung Galaxy Version 12` running `Bravemonoarm64.apk_1.49.116`

- Verified the test plan from https://github.com/brave/brave-core/pull/16774#issue-1551389184

<details>
<summary>Case 1: Open a pub and then enable rewards in another tab</summary>

- Clean profile 1.49.x
- Open a publisher (e.g laurenwags.github.io)
- Open a NTP and tap on the BR panel and enable rewards
- Open the pubs page
- Confirmed that "publishers visited" count is displayed with a value of `1` in the BR panel

![image](https://user-images.githubusercontent.com/38657976/219435538-e5c2e849-cf58-4f8b-887e-95b00822f718.png)

</details>

<details>
<summary>Case 2: Open a pubs page and stay on page to satisfy the "min pubs visit" time and then open a new site in NTP_</summary>

- Clean profile 1.49.x
- Open a publisher (e.g laurenwags.github.io)
- Open BR panel and enable rewrads (select the supported region and skip onboarding)
- Stay on the laurenwags.github.io pub to satisfy the "min pubs visit" time
- Observe that "publishers visited" count is not yet disaplyed in the BR panel
- Open a new tab and open any  new site 
- Come back to laurenwags.github.io
- Confirmed that "publishers visited" count is displayed with a value of `1` in the BR panel

![image](https://user-images.githubusercontent.com/38657976/219432637-c3a2e81f-31c5-4094-a8e6-96812c709de1.png)

</details>

<details>
<summary>Case 3: Open a pubs page and stay on page to satisfy the "min pubs visit" time and then navigate to a brave page tab_</summary>

- Clean profile 1.49.x
- Open a publisher (e.g laurenwags.github.io)
- Open BR panel and enable rewrads (select the supported region and skip onboarding)
- Stay on the laurenwags.github.io pub to satisfy the "min pubs visit" time
- Observe that "publishers visited" count is not yet disaplyed in the BR panel
- Open a already opened tab (e.g brave://welcome)
- Come back to laurenwags.github.io
- Confirmed that "publishers visited" count is displayed with a value of `1` in the BR panel

![image](https://user-images.githubusercontent.com/38657976/219433904-8c82ffbf-d82d-4345-bd7f-9e2776b69dd0.png)

</details>

<details>
<summary>Case 4: Open a pubs page and stay on page to satisfy the "min pubs visit" time and then open a NTP_</summary>

- Clean profile 1.49.x
- Open a publisher (e.g laurenwags.github.io)
- Open BR panel and enable rewrads (select the supported region and skip onboarding)
- Stay on the laurenwags.github.io pub to satisfy the "min pubs visit" time
- Observe that "publishers visited" count is not yet disaplyed in the BR panel
- Open a NTP don't open any site in it
- Come back to laurenwags.github.io
- Confirmed that "publishers visited" count is displayed with a value of `1` in the BR panel

![image](https://user-images.githubusercontent.com/38657976/219433121-5784ac60-e379-4db4-86e3-c57377ff6488.png)

</details>

<details>
<summary>Case 5: Open a pubs page and stay on page to satisfy the "min pubs visit" time and then open and close the panel _</summary>

- Clean profile 1.49.x
- Open a publisher (e.g laurenwags.github.io)
- Open BR panel and enable rewrads (select the supported region and skip onboarding)
- Stay on the laurenwags.github.io pub to satisfy the "min pubs visit" time
- Observe that "publishers visited" count is not yet disaplyed in the BR panel
- Open and close the BR panel in laurenwags.github.io pub
- Confirmed that "publishers visited" count is displayed with a value of `1` in the BR panel

![image](https://user-images.githubusercontent.com/38657976/219436310-72074479-56a6-40ed-a8a3-7abc63c7ddde.png)

</details>
