### ISSUE TITLE
Crash searching log Jenkins log

### ISSUE THREAD

**Issue by rillian** [brave/brave-browser#27908]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.48.122  Chromium: 109.0.5414.87
Operating System: Linux 6.0.15-300.fc37.x86_64

URL (if applicable) where crash occurred: https://ci.brave.com/job/brave-browser-build-macos-x64/5971/consoleFull

Can you reproduce this crash?
It's happened three times now

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Open jenkins build log (e.g. private url above)
2. Click button to expand full log
3. Ctrl-F to search. I was trying `Compile cxx`
4. click next/previous match a few times

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/275a0100-7249-7e09-0000-000000000000

**Comment by iefremov** [comment]
@rillian Was it a browser or renderer crash? Can you try to reproduce it? The crashdump has been expired already. If the log was huge, it could be oom.

**Comment by rillian** [comment]
I think it was just the tab that crashed, but I'm not sure. The original url where I saw the crash is no longer available. I haven't seen a re-occurance, and I haven't been able to reproduce with a similar but more recent log url on 1.51.98, e.g. https://ci.brave.com/job/brave-browser-build-macos-x64/6359/consoleFull

It's still listed in brave://crashes. I can share the dump files from my local profile if that's helpful?

**Comment by iefremov** [comment]
stale
