### ISSUE TITLE
Follow-up to #27649: Additional confirmation to end of support message is not translated

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#27904]
Follow up to #27649

## Steps to Reproduce

1. Use Windows 7/ Windows 8
1. Run Brave in PL Polish Locale
1. Check the `Don't show again` checkmark on obsolete system infobar
1. Click `x` on obsolete system infobar
1. Check the additional dialog 

## Actual result:

Additional confirmation to end of support message is not translated
![image](https://user-images.githubusercontent.com/34715963/213501500-db6a12a2-ee62-4112-a5fc-b65b5a422996.png)

## Expected result:
Additional confirmation to end of support message is translated

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.47.177 Chromium: 109.0.5414.87 (Official Build) (64-bit) 
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | Windows 7 x64

cc @rebron @mkarolin @kjozwiak

**Comment by rebron** [comment]
We'll cover for the translation for this string for the following languages:
Hindi
French
German
Spanish
Portuguese
Japanese
Dutch
Polish
Russian
Vietnamese
Italian
South Korean
Romanian
Simplified Chinese
Turkish

**Comment by kjozwiak** [comment]
Closing as https://github.com/brave/brave-core/pull/16819 was directly merged into `1.47.x`.

**Comment by kjozwiak** [comment]
@btlechowski just pick ~2-3 locales from https://github.com/brave/brave-browser/issues/27904#issuecomment-1399007606 and once you're done with `Win 7`, I'll pick three other locales via `Win 8.1` 👍

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.47.182 Chromium: 109.0.5414.87 (Official Build) (64-bit)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | Windows 7 Service Pack 1 (Build 7601.24544)


#### Hindi
![image](https://user-images.githubusercontent.com/34715963/214297089-048c8809-58a8-4e27-af99-ebf1df52d67d.png)

#### French
![image](https://user-images.githubusercontent.com/34715963/214297333-4769a61d-7e5f-402f-8cab-3952e362dbae.png)

#### German
![image](https://user-images.githubusercontent.com/34715963/214296740-4893424d-a4d6-4154-b3bd-cf938f5d1f41.png)

#### Spanish
![image](https://user-images.githubusercontent.com/34715963/214297786-611fd24a-d7ba-49f5-90d8-7c2dd89b8598.png)

#### Portuguese
![image](https://user-images.githubusercontent.com/34715963/214298098-c059733d-3ad6-497a-85a8-d03d4b24c2a4.png)

#### Japanese
![image](https://user-images.githubusercontent.com/34715963/214298426-89ee5c2f-03f5-468f-81ef-270d7ac57791.png)


#### Dutch
![image](https://user-images.githubusercontent.com/34715963/214298742-c765e8f3-ba92-41c5-92c5-92fd36091a99.png)


#### Polish
![image](https://user-images.githubusercontent.com/34715963/214296501-d1605c45-769b-46a3-9934-3a9e58216027.png)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 8.1 x64` using the following build(s):

```
Brave | 1.47.183 Chromium: 109.0.5414.119 (Official Build) (64-bit)
--- | ---
Revision | 772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}
OS | Windows 8.1 (Build 9600.20778)
```

### `Russia`

**`Example`** | **`Example`**
----------------|----------------
<img width="1060" alt="Screenshot 2023-01-25 at 4 35 43 AM" src="https://user-images.githubusercontent.com/2602313/214529894-1fe7ebfc-bfe9-4c0d-b443-d44b06906665.png"> | <img width="1055" alt="Screenshot 2023-01-25 at 4 35 55 AM" src="https://user-images.githubusercontent.com/2602313/214529907-4a8489ed-39b9-4204-9e49-35d0f540cf01.png">
