### ISSUE TITLE
Assign Copy keyboard shortcut to "copy clean link" - Mac App Menu part

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#27902]
Mac has App Menu in top left display corner with Copy item( hotkey cmd+c) and we show Copy Clean Link if user has url selected in the location bar. Need reassign default hotkeys from copy item to copy clean link item as well.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.49.96 Chromium: 110.0.5481.77 (Official Build) beta (x86_64)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | macOS Version 11.7.3 (Build 20G1116)

### Case 1: `Copy Clean Link`

1. installed `1.49.96`
2. launched Brave
3. loaded `https://brave.com/?foo=bar?baz=foopy?blah=blue`
4. selected the URL
5. context-clicked the URL
6. opened `Apple menubar`  -> `Edit` -> `Copy Clean Link ⌘C`
7. confirmed `Copy Clean Link ⌘C` had shortcut keys `⌘C`
8. copied and pasted the text

#### Confirmed copying and pasting retained parameters (these are not known trackers; this was a negative test)

<img width="1680" alt="Screen Shot 2023-02-13 at 1 26 26 PM" src="https://user-images.githubusercontent.com/387249/218578274-75c2c16e-02cd-40a5-8367-5116d5292b8b.png">


### Case 2: `Copy` 

(continued from above)

* selected only a substring of the full URL

<img width="1680" alt="Screen Shot 2023-02-13 at 1 26 05 PM" src="https://user-images.githubusercontent.com/387249/218578227-d9f2655f-b5bc-4c41-9c23-e03a0c3dc375.png">

#### Confirmed with just text (no canonical URL) we show the `Copy ⌘C` shortcut in the menu

### Case 3: No selection

(continued from above)

* cleared user selection of all text

#### Confirmed with no selection, the shortcut is `Copy ⌘C` in the menu


<img width="1680" alt="Screen Shot 2023-02-13 at 1 24 49 PM" src="https://user-images.githubusercontent.com/387249/218577878-91c1221c-998d-41bc-8126-4a85fc32cb2d.png">

**Comment by dinhanhthi** [comment]
In the version 1.56.14, I cannot use `cmd+C` to copy the URL / selection on the address bar. Every time I use `cmd+C`, it opens the Inspect Element panel. It's annoying!!! The older version doesn't have this issue!
