### ISSUE TITLE
[Followup] Rewards 2.5-3 onboarding cleanup to match design spec

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#27901]
## Description

As documented by @LaurenWags. (Left is 1.48.x; right is Figma.)

- [ ] Case 1
- [ ] Case 2
- [ ] Case 3
- [ ] Case 4
- [ ] Case 5

Case 1: 
![image](https://user-images.githubusercontent.com/11497541/213485426-12aa6501-0164-477a-8336-3c0b92a61873.png)

Case 2:
![image](https://user-images.githubusercontent.com/11497541/213485524-37d608b7-64b6-425b-8147-9d9274723fab.png)

Case 3:
![image](https://user-images.githubusercontent.com/11497541/213485548-5f0f5358-e325-4801-b16b-8581a9c4eb85.png)

Case 4:
![image](https://user-images.githubusercontent.com/11497541/213485573-1605d42a-15b0-4d7d-8a7e-c888a0ab7b84.png)

Case 5: 
![image](https://user-images.githubusercontent.com/11497541/213485600-70c06cd5-4070-412f-9e52-ea4513d3d723.png)

**Comment by GeetaSarvadnya** [comment]
On Android `Bravemonoarm64.apk_1.48.141` also few onboarding slides doesn't match with the figma spec.

Case 1: (see the figma screenshot above https://github.com/brave/brave-browser/issues/27901#issue-1549413447 in case 1)
![image](https://user-images.githubusercontent.com/38657976/215400845-2c3420fc-9bfc-41a6-8854-a8067a665f6f.png)

Case 2: Privacy Policy doesn't have the hyperlink, desktop has the hyperlink for the `Privacy policy` for this slide
![image](https://user-images.githubusercontent.com/38657976/215402038-b47ed593-68ea-4f83-b320-5cb185f0120a.png)

**Comment by GeetaSarvadnya** [comment]
On Android `Bravemonoarm64.apk_1.48.141` also few onboarding slides doesn't match with the figma spec.

Case 1: (see the figma screenshot above https://github.com/brave/brave-browser/issues/27901#issue-1549413447 in case 1)
![image](https://user-images.githubusercontent.com/38657976/215400845-2c3420fc-9bfc-41a6-8854-a8067a665f6f.png)

Case 2: Privacy Policy doesn't have the hyperlink, desktop has the hyperlink for the `Privacy policy` for this slide
![image](https://user-images.githubusercontent.com/38657976/215402038-b47ed593-68ea-4f83-b320-5cb185f0120a.png)

**Comment by Miyayes** [comment]
Superseded by new onboarding.
