### ISSUE TITLE
Unable to connect to snapshot.org

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#27913]
## Description 

Unable to connect to snapshot.org. It's just a rolling bar. Brought up here 
<img width="345" alt="Screenshot 2023-01-19 at 21 09 06" src="https://user-images.githubusercontent.com/12224304/213551356-be45ebee-abf4-4dff-81d3-9c31704fc726.png">
https://bravesoftware.slack.com/archives/C02S9LFEXU4/p1674152634902389

## Steps to Reproduce

   1. try connect to snapshot.org with your brave wallet
   2. you have to click on metamask wallet
   3. 

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? Y
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the nightly channel? Y

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N
- Does the issue resolve itself when disabling Brave Rewards? N
- Is the issue reproducible on the latest version of Chrome?

**Comment by yrliou** [comment]
Closing as duplicated, see https://github.com/brave/brave-browser/issues/28896.
