### ISSUE TITLE
Add an option in Settings to install/enable and uninstall/disable Widevine Plugin (Muon parity)

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#2791]
## Description 
We have an open issue to make the "install/run widevine" prompt more obvious to the user and to display on all sites that require it (rather than having to navigate to Netflix or Hulu to do so). I have seen several users, however, ask if there is a way for the to uninstall Widevine on their machine.

Currently, there's no way to uninstall Widevine without uninstalling Brave entirely. In Brave Muon, there was a switch in Preferences --> Plugins --> Widevine that allowed this functionality. It would be useful to make this accessible to Core builds as well.
![image](https://user-images.githubusercontent.com/3299098/50613683-42eb0700-0ed6-11e9-88bc-0863c99f6bc4.png)

### Additional Information

One user here from Reddit asking how to disable Widevine - will continue to add reports to this thread as I see them:
https://www.reddit.com/r/brave_browser/comments/abp4vq/how_to_disable_widevine/

**Comment by srirambv** [comment]
Check media license in clear data modal under advance. This removes any media related settings that is set on the active profile. It will prompt again to `install and run` when you visit the site again. This avoids the uninstall/reinstall component problem. This is the safest way to ensure the component is installed but only works after you explicitly make it run.

**Comment by Brave-Matt** [comment]
@srirambv, I have a few users saying that this doesn't always fix the issue. The option is also buried fairly deep in content settings. I think components like this should be surfaced as much as possible.

**Comment by rebron** [comment]
Should go in the same area where we display WebTorrent pref.

**Comment by tamj0rd2** [comment]
It would be really helpful to have an option to just install or uninstall it through the settings menu. I'm running into an issue where the install prompt isn't coming up on Netflix. It worked fine when I tried on Windows but isn't working at all on ubuntu using the normal release or Dev.

**Comment by johnsen32** [comment]
In canse anyone else comes across this issue and is still wondering how th heck one can get netflix to work with Brave, here is the solution

> Put shields down. Refresh. Check top right corner for pop-up icon. Right besides Brave rewards. Accpet widewine install. Watch netflix. Keep shields down.

https://www.reddit.com/r/BATProject/comments/a9uqk4/widevine_install_problems_for_brave_browser/


This should not be that hard, took me almost an hour to find the solution.
Please improve usability for such cases.

**Comment by bsclifton** [comment]
@johnsen32 thanks for the feedback 😄Definitely important for us to solve this issue

In the meantime, we do have a more obvious notification (fixed in master). This will be making its way through the channels. Check out a preview of how it looks here:
https://github.com/brave/brave-browser/issues/1940#issuecomment-436438375

**Comment by Brave-Matt** [comment]
+1 from Reddit:
https://www.reddit.com/r/brave_browser/comments/abp4vq/how_to_disable_widevine/ekcnl66?utm_source=share&utm_medium=web2x

**Comment by Brave-Matt** [comment]
+2 from Community:
https://community.brave.com/t/remove-drm-from-brave/54081

**Comment by rebron** [comment]
@tamj0rd2 can you try Netflix/Widevine again on Ubuntu in current release or any channel you prefer (beta/dev/nightly). We have widevine working now as of 62.x.

**Comment by deoxal** [comment]
> Should go in the same area where we display WebTorrent pref.

Would it be possible to use it on a per site basis like with camera, microphone, camera etc?

**Comment by Brave-Matt** [comment]
+1 from reddt:
https://www.reddit.com/r/brave_browser/comments/c86e03/would_like_a_flag_or_setting_to_gloablly_disable/

**Comment by Brave-Matt** [comment]
+1 from Community:
https://community.brave.com/t/how-to-completelly-remove-widevine-from-brave-ubuntu/73658

**Comment by Brave-Matt** [comment]
Several +1s from Reddit thread:
https://www.reddit.com/r/brave_browser/comments/fpuc9z/netflix_and_spotify_on_brave_uninstall_widevine/

**Comment by reelnoncents** [comment]
+1 from Reddit. Can't uninstall WideVine from Brave, and what's worse, the "Clear Media Licenses" options (under Settings --> Adv. --> Privacy and Security --> Content --> Clear browsing data) that Brave Team responded with in this Reddit thread seems to have disappeared since their response :

![image](https://user-images.githubusercontent.com/4936647/80621630-92334000-8a15-11ea-856b-34ab71adc427.png)

How does one either uninstall OR disable WideVine from Brave. Both options would be ideal here. Thanks.

**Comment by Brave-Matt** [comment]
+1 from Reddit:
https://www.reddit.com/r/brave_browser/comments/g9q5ot/how_to_remove_windvine_without_uninstalling_brave/

**Comment by stephendonner** [comment]
Verified with testplan from https://github.com/brave/brave-core/pull/7554 on


Brave | 1.21.44 Chromium: 88.0.4324.146 (Official Build) beta (x86_64)
-- | --
Revision | 406dc88511162d6598242f2c709be1414a042fb0-refs/branch-heads/4324@{#2088}
OS | macOS Version 11.2 (Build 20D64)


<summary>
Case 1:
</summary>
<details>

* go to Settings -> Extensions
* confirm default value "Enable Widevine" is disabled
* log in to `hulu`, `hbomax`, or `netflix`; play media
* confirm install of Widevine, when prompted
* verify playing media works
* return to Settings and confirm that Enable Widevine is now checked

![image](https://user-images.githubusercontent.com/387249/107292698-1bed5080-6a1f-11eb-85e7-86ab5a9bd131.png)

</details>

<summary>
Case 2:
</summary>
<details>

* go to Settings -> Extensions
* confirm default value "Enable Widevine" is disabled
* toggle "Enable Widevine" to on
* confirm you get "Your changes will take effect the next time you relaunch Brave." text at bottom, with "Relaunch Now" button
* click Relaunch Now
* after relaunch, return to Settings and confirm that Enable Widevine is now checked
* open `brave://components`, confirm that `**Widevine Content Decryption Module**` appears, with "Status - Up-to-date"
* log in to `hulu`, `hbomax`, or `netflix`; play media
* verify you are **NOT** prompted to install Widevine, and playing media works

![image](https://user-images.githubusercontent.com/387249/107292894-7090cb80-6a1f-11eb-8404-bb2024053537.png)


</details>

<summary>
Case 3:
</summary>
<details>

* go to Settings -> Extensions
* confirm default value "Enable Widevine" is disabled
* log in to `hulu`, `hbomax`, or `netflix`; play media
* confirm install of Widevine, when prompted
* verify playing media works
* return to Settings and confirm that Enable Widevine is now toggled on
* uncheck "Enable Widevine" and click Relaunch now
* upon relaunch, verify that Widevine doesn't appear in `brave://components/`
![image](https://user-images.githubusercontent.com/387249/107293380-5e635d00-6a20-11eb-8946-b70501e8b147.png)

![image](https://user-images.githubusercontent.com/387249/107292151-3246dc80-6a1e-11eb-9619-d36cdfd24aaf.png)

</details>
