### ISSUE TITLE
Brave News `Customize` window is blank after loading `Learn More` content in its tab

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#27914]
## Description 

Brave News `Customize` window is blank after loading `Learn More` content in its tab

This is a followup from https://github.com/brave/brave-browser/issues/27052, with different steps.

## Steps to Reproduce

1. install `1.49.39`
2. launch Brave
3. open a new-tab page
4. scroll down
5. on the Brave News opt-in dialog, click Learn More (this replaces the tab’s content)
6. now click the Back button on the browser
7. click Show Brave News
8. click Customize

## Actual result:

<img width="1312" alt="Screen Shot 2023-01-19 at 2 28 00 PM" src="https://user-images.githubusercontent.com/387249/213576405-5d36bde8-7ce7-4918-a303-799708d4e884.png">

## Expected result:

<img width="1312" alt="Screen Shot 2023-01-19 at 2 28 22 PM" src="https://user-images.githubusercontent.com/387249/213576464-70cd3fee-8530-4345-b428-a5cc44d2a608.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.49.39 Chromium: 109.0.5414.87 (Official Build) nightly (x86_64)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | macOS Version 11.7.2 (Build 20G1020)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

/cc @fallaciousreasoning @rebron @mattmcalister @brave/qa-team @petemill

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.50.14 Chromium: 110.0.5481.77 (Official Build) nightly (x86_64)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | macOS Version 11.7.3 (Build 20G1116)

### Steps:

1. installed `1.50.14`
2. launched Brave
3. opened a new-tab page
4. scrolled down
5. on the Brave News opt-in dialog, clicked `Learn More` (this replaces the tab’s content)
6. now clicked the `Back` button on the browser
7. clicked `Show Brave News`
8. clicked `Customize`

#### Confirmed I had a working Brave News `Customize` dialog

<img width="962" alt="Screen Shot 2023-02-07 at 12 51 59 AM" src="https://user-images.githubusercontent.com/387249/217197689-6bdd965a-e282-45b9-b796-6114f826a887.png">

**Comment by stephendonner** [comment]
@fallaciousreasoning I hit this in `1.49.100` yesterday; think we can get this uplifted?

**Comment by fallaciousreasoning** [comment]
Good call @stephendonner - uplift request is here:
https://github.com/brave/brave-core/pull/17287

**Comment by kjozwiak** [comment]
The above requires `1.49.109` or newer for `1.49.x` verification 👍 Removing the `QA Pass` label as this will need to be re-verified on `1.49.x`. Used the verification from https://github.com/brave/brave-browser/issues/27914#issuecomment-1420415445 when uplifting https://github.com/brave/brave-core/pull/17287.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.49.109 Chromium: 110.0.5481.177 (Official Build) beta (x86_64)
-- | --
Revision | f34f7ab2d4ca4ad498ef42aeba4f4eb2c1392d63-refs/branch-heads/5481@{#1239}
OS | macOS Version 11.7.4 (Build 20G1120)

example | example | example | example | example
---------|---------|----------|----------|---------
<img width="1312" alt="Screen Shot 2023-02-23 at 5 48 39 PM" src="https://user-images.githubusercontent.com/387249/221072301-8e0475cb-3f6b-48e2-9034-75b110e3bd16.png"> | <img width="1312" alt="Screen Shot 2023-02-23 at 5 48 49 PM" src="https://user-images.githubusercontent.com/387249/221072328-db6fdc89-ef52-4090-8eac-bf68f04defca.png"> | <img width="1312" alt="Screen Shot 2023-02-23 at 5 48 52 PM" src="https://user-images.githubusercontent.com/387249/221072336-6fac4bd7-63c6-4174-81cf-c7383f5cd43a.png"> | <img width="1312" alt="Screen Shot 2023-02-23 at 5 48 59 PM" src="https://user-images.githubusercontent.com/387249/221072337-d3845f89-ebdb-4128-b158-6196ef396cf2.png"> | <img width="1312" alt="Screen Shot 2023-02-23 at 5 49 04 PM" src="https://user-images.githubusercontent.com/387249/221072340-39a35454-b8b1-4632-b67e-523bd986fca0.png">
