### ISSUE TITLE
Bug: User cannot edit fiat amount in transak widget

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#27927]

**Comment by kjozwiak** [comment]
The above requires `1.48.140` or higher for `1.48.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.48.141 Chromium: 109.0.5414.119 (Official Build) beta (64-bit) 
-- | --
Revision | `772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}`
OS | Linux

- Verified steps from [brave/brave-core#16769](https://github.com/brave/brave-core/pull/16769)
- Verified  able to edit values in Transak Widget

https://user-images.githubusercontent.com/17010094/215736527-548c7828-5248-46ac-90a4-045a4725daa2.mp4


---------------------

Verification passed on 

Brave | 1.48.141 Chromium: 109.0.5414.119 (Official Build) beta (64-bit)
-- | --
Revision | `772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#16769](https://github.com/brave/brave-core/pull/16769)
- Verified  able to edit values in Transak Widget

https://user-images.githubusercontent.com/17010094/215736162-06d84ef0-aac7-4f72-8816-2d1abd7e7554.mp4


---------------------

Verification passed on 

Brave | 1.48.141 Chromium: 109.0.5414.119 (Official Build) beta (arm64)
-- | --
Revision | `772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#16769](https://github.com/brave/brave-core/pull/16769)
- Verified  able to edit values in Transak Widget

https://user-images.githubusercontent.com/17010094/215736825-a3a3b09a-bb0b-4d5b-9c40-b82ee097a7fd.mov
