### ISSUE TITLE
Crash Report: Brave reproducibly crashes when loading "brave://welcome" or "brave://settings/importData"

### ISSUE THREAD

**Issue by saladpanda** [brave/brave-browser#27923]
Brave Version: 1.47.171  Chromium: 109.0.5414.87
Operating System: Windows NT 10.0.19044

URL (if applicable) where crash occurred: brave://welcome

Can you reproduce this crash?
yes. every time.

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Fresh install of Brave, All userdata removed.
2. Start Brave. "brave://welcome" is loaded automatically.
3. Brave crashes before the page is loaded successfully

Another way to confirm its "brave://welcome":
1. Launch brave from the commandline with `.\brave.exe "about:blank"` or `.\brave.exe "google.de"` or `.\brave --incognito`
2. Brave launches successfully
3. Browse to "brave://welcome"
4. Brave crashes immediately

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/ba0a0200-7249-7e09-0000-000000000000

**Comment by saladpanda** [comment]
The crash also happens when trying to import data from another browser, i.e. opening "brave://settings/importData".

Crash ID: crash/7e1d0200-7249-7e09-0000-000000000000

**Comment by bsclifton** [comment]
Closing as there's not enough information here to troubleshoot. @saladpanda if you were willing to try again, you can see if it still happens and share a recent crash ID
