### ISSUE TITLE
[2.5-3] Visited creators counter in Rewards panel does not appear in JP case 

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#27936]
## Description

Likely because A-C is disabled in the JP case, the "visited creators" counter doesn't work in the JP case, since it relies on A-C mechanism. Found by @LaurenWags.

**Comment by mkarolin** [comment]
@LaurenWags would it be possible to get the STR?

**Comment by Miyayes** [comment]
> @LaurenWags would it be possible to get the STR?

It would be:

1. Fresh profile in 1.48.x or higher
2. Declare geo to Japan (does not need to be staging -- prod is fine)
3. Navigate to a bunch of verified sites/channels. Notice how there is no "This month, you've visited n creators who are supported by Brave Rewards" counter/UI building up in the Rewards dropdown panel.

**Comment by LaurenWags** [comment]
@mkarolin I think @Miyayes steps from https://github.com/brave/brave-browser/issues/27936#issuecomment-1407249088 should do it, but happy to provide more info if needed.

**Comment by mkarolin** [comment]
@Miyayes & @LaurenWags Thank you!

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.51.79 Chromium: 112.0.5615.49 (Official Build) beta (64-bit)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Windows 10 Version 21H2 (Build 19044.2728)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/17735
- Confirmed that verified creators counter is displayed in the rewards panel
![image](https://user-images.githubusercontent.com/38657976/230346982-9e018f11-73df-4ab9-a36a-84972f1700e4.png)
