### ISSUE TITLE
Brave default-browser icons are incorrectly sized in Android's `Browser app` picker

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#27937]
## Description 

Brave default-browser icons are incorrectly sized in Android's `Browser app` picker

## Steps to reproduce 

   1. install `1.47.175` (and/or `nightly`, `beta`) and at least Google Chrome or Firefox
   2. launch Brave
   3. during onboarding, tap on `Set as default browser`
   4. tap through to see and set the system-default browser
   5. compare Brave's icon to the other browsers'

## Actual result 

![Screenshot_20221221-022752](https://user-images.githubusercontent.com/387249/213772445-bf0ce379-81d7-4c47-8381-9ae2d7e9ca88.png)

## Expected result

Appropriately-sized Brave icons (the irony of my giant screenshot isn't lost on me 😂 )

## Issue reproduces how often 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): `arm64`
   - Device type (Phone, Tablet, Phablet): `Google Pixel XL`
   - Android version: `9`
   
## Brave version

`1.47.175`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

/cc @simoarpe @srirambv @kjozwiak @Uni-verse

**Comment by Uni-verse** [comment]
Verified on `Samsung GS 21 5G` using version(s):

```
Brave	1.49.118 Chromium: 111.0.5563.50 (Official Build) (64-bit) 
Revision	39f3dfc5023fe60997adc4f6cf5439cfa3e6968a-refs/branch-heads/5563@{#903}
OS	Android 13; Build/TP1A.220624.014
```
Example | Example
-|-
![screenshot-1678146705802](https://user-images.githubusercontent.com/17885425/223283666-b5af555c-75aa-4f4f-9839-f4ea391e7055.png) | ![screenshot-1678146944655](https://user-images.githubusercontent.com/17885425/223283683-57441e1f-d0d3-49d4-bfbc-888abbdfd43c.png)
