### ISSUE TITLE
[Sync] Long wait for updates when starting sync device with big amount of objects

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#27931]
1. Take two devices with ~20k bookmarks
2. Create the chain with 1st device
```
2.1 The 1st device enered the sync chain pulls objects from the chain, gots 0, because it is the fisrt device in the chain
2.2 Then 1st device commits all it's object, which may take long - 90 records each 3 sec => 667 sec for 20000 records. 
```
3. The 2nd device joins the sync chain.
```
3.1 It pulls existing objects in the sync chain including device#1 record and some bookmarks from device#1
3.2 Device#1 still keeps sending their bookmarks 
```
4. Device#2 somehow can't send anything and by my observations it started to send only after ~ 10 minutes.

5. Finally both devices are synced. But it takes more than 20 minutes one of them looks does nothing for 10 minutes.

**Comment by kjozwiak** [comment]
The above requires `1.48.169` or higher for `1.48.x` verification. @brave/qa-team can also use https://github.com/brave/brave-core/pull/17077#issuecomment-1439428620 as guidance/template if needed.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.48.169 Chromium: 110.0.5481.104 (Official Build) (x86_64)
-- | --
Revision | 46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}
OS | macOS Version 12.6.3 (Build 21G419)
```

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` running `Android 13` & `Samsung Galaxy Tab S7` running `Android 12` using the following version: 

```
Brave	1.48.171 Chromium: 110.0.5481.177 (Official Build) (64-bit) 
Revision	f34f7ab2d4ca4ad498ef42aeba4f4eb2c1392d63-refs/branch-heads/5481@{#1239}
OS	Android 12; Build/SP2A.220305.013
```

- Ensured that devices with 20k bookmarks were showing up in the sync chain list in ~20-30 secs after joining sync chain
- Ensured that device A can start standalone sync chain with 20k bookmarks and device B can join and shows up in the sync chain list.
- Ensured `send to your devices` works via the share menu and items are retrieved in ~15-30 secs

Example | Example | Example | Example | Example
-|-|-|-|-
![screenshot-1677185272071](https://user-images.githubusercontent.com/17885425/221031501-50b9e259-9881-4c9f-8e80-48db8874f7d9.png) | ![screenshot-1677186236768](https://user-images.githubusercontent.com/17885425/221031504-114ec7ef-8353-4e44-bb8e-363e30ca2af0.png) | ![Screen Shot 2023-02-23 at 4 05 51 PM](https://user-images.githubusercontent.com/17885425/221031542-31ad62da-7862-4ec7-a9d4-b945a35a4a17.png) | ![screenshot-1677184473456](https://user-images.githubusercontent.com/17885425/221031583-48786c0c-81f1-4d95-a2e5-bc6aa789ef33.png) | ![screenshot-1677187113570](https://user-images.githubusercontent.com/17885425/221032532-e97c9d55-d41b-46d1-9def-e4b1b7b09efd.png)
