### ISSUE TITLE
The `Learn more` link in Brave Rewards overlay (not `brave://rewards`) should be white, not gray

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#27941]
## Description 

The `Learn more` link in Brave Rewards overlay (not `brave://rewards`) should be white, not gray

This is a followup from https://github.com/brave/brave-browser/issues/27799.  I verified that issue, but although the link color is improved (not blue), it's still not white, as specified.  I'm not sure if that's correct, or it should be white, hence this issue :-)

## Steps to reproduce 

1. installed `1.47.161`
2. launched Brave
3. enabled Brave Rewards
4. installed `1.48.134` atop `1.47.161` (both are beta-channel builds)
5. launched Brave
6. tapped the BAT icon
7. examined and clicked on the `Learn more` link

## Actual result 

example | example
---------|--------
![Screenshot_20230120-160210](https://user-images.githubusercontent.com/387249/213828418-869d8dbe-5f1a-40da-b0d1-77c94949720f.png) | <img width="458" alt="Screen Shot 2023-01-20 at 4 10 05 PM" src="https://user-images.githubusercontent.com/387249/213828566-0f12e174-4876-413c-9f9f-1b01503ccb92.png">

## Expected result

The link should be white, according to https://github.com/brave/brave-browser/issues/27799#issue-1532662633

## Issue reproduces how often 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): `arm64`
   - Device type (Phone, Tablet, Phablet): `Google Pixel XL`
   - Android version: `9`
   
## Brave version

`1.48.134`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

/cc @Miyayes @deeppandya @zenparsing @Uni-verse @kjozwiak @srirambv

**Comment by stephendonner** [comment]
@aguscruiz was the difference in color for the main `brave://rewards` page and the doorhanger/overlay from the BAT icon intended?

white vs. gray, respectively, per Figma?

If so, this issue is INVALID

`brave://rewards` | from `BAT` icon
------------------|-----------------
![image (1)](https://user-images.githubusercontent.com/387249/213831846-e540af0d-384e-4fa6-9133-dd73486a2bfa.png) | ![image](https://user-images.githubusercontent.com/387249/213831859-9e52927c-f99c-4a9e-8c45-513bed851690.png)

**Comment by aguscruiz** [comment]
Must've been unintentional. I think the correct one is the white one. Also the text size and weight is correct in that one

**Comment by Miyayes** [comment]
Despite it being unintentional, I don't think it's worth fixing. Putting closed/wontfix. Grandfathered state is also temporary and will be eliminated in a couple months.
