### ISSUE TITLE
Make brave://adblock-internals 

### ISSUE THREAD

**Issue by atuchin-m** [brave/brave-browser#27966]
We need a debug page to track a progress over https://github.com/brave/brave-browser/issues/26892

**Comment by LaurenWags** [comment]
Updated to `release-notes/exclude` per discussion with @kjozwiak

**Comment by Uni-verse** [comment]
In progress on `Samsung GS 21 5G` using the following version:

```
Brave	1.49.118 Chromium: 111.0.5563.50 (Official Build) (64-bit) 
Revision	39f3dfc5023fe60997adc4f6cf5439cfa3e6968a-refs/branch-heads/5563@{#903}
OS	Android 13; Build/TP1A.220624.014
```
