### ISSUE TITLE
Remove all remaining occurrences of `base::ListValue`

### ISSUE THREAD

**Issue by cdesouza-chromium** [brave/brave-browser#27964]
`base::ListValue` is getting removed upstream. There are still a few occurrences of it in the codebase that should be replaced with some more appropriate type.

**Comment by LaurenWags** [comment]
@cdesouza-chromium does this need manual QA? I've labelled as `QA/No` and `release-notes/exclude` but if either of these labels are incorrect please advise, thanks.

**Comment by cdesouza-chromium** [comment]
You've labelled it correctly. Cheers.
