### ISSUE TITLE
Remove DictionaryPrefUpdate from the codebase

### ISSUE THREAD

**Issue by cdesouza-chromium** [brave/brave-browser#27962]
As part of the continued refactoring of `base::Value`, `DictionaryPrefUpdate` has been removed upstream in favour of `ScopedDictPrefUpdate`.

**Comment by LaurenWags** [comment]
@cdesouza-chromium does this need manual QA? I've labelled as `QA/No` and `release-notes/exclude` but if either of these labels are incorrect please advise, thanks.

**Comment by cdesouza-chromium** [comment]
No QA or release notes needed.
