### ISSUE TITLE
 Filecoin accounts should be created by default on new wallets and restored wallets

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#27972]
## Description 

At the moment, only ethereum and solana accounts are created on new wallets. We should add Filecoin to this too. Also this should be shown on restored wallets.

See conversation here -> https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1674495125012309

## Steps to Reproduce

   1. 
   2. 
   3. 

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by cypt4** [comment]
Also we can create default filecoin account like for Solana and ETH

**Comment by yrliou** [comment]
We probably don't want to auto create it to avoid irritating users, in the mean time we can do account discovery first (https://github.com/brave/brave-browser/issues/28002) instead to cover the restore use case, which will restore your filecoin accounts if you have previous transactions on it.
https://bravesoftware.slack.com/archives/C04JJNFRPK7/p1675092287227419?thread_ts=1675044887.369699&cid=C04JJNFRPK7 is a relevant discussion we recently had.
cc @bbondy

**Comment by HEagle18** [comment]
I think that works. I will close this out.
