### ISSUE TITLE
30 ads history is blank 

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#27987]
## Description 

30 day ads history is blank.

Should probably determine if this link should be shown for "unverified" and "grandfather unverified" states in 1.48.x. If it is going to be shown, it should list the ads as it did previously.

## Steps to Reproduce

   1. Either be in unverified (new profile with 1.48.x) or grandfathered unverified (unverified upgraded from 1.47.x) state for Rewards or connected (to a custodian such as Uphold)
   2. View at least one ad
   3. Look at 30 day ads history on brave://rewards

## Actual result:

Ads history is blank

Unverified | Connected
---- | ----
<img width="1320" alt="Screen Shot 2023-01-23 at 4 00 44 PM" src="https://user-images.githubusercontent.com/28145373/214149131-38d9c2d6-4378-4dae-9210-b379e182a9ef.png"> | <img width="1312" alt="Screen Shot 2023-01-23 at 4 06 36 PM" src="https://user-images.githubusercontent.com/28145373/214150094-faea0ed9-ec9b-454d-b5c1-8efa8ffacd76.png">

## Expected result:

TBD - maybe not show this link if a user isn't earning? @Miyayes and someone from ads team should determine this.

If the link is shown though, ads information should be listed on the history.

## Reproduces how often: 

easily

## Brave version (brave://version info)

1.48.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? 1.47.x no
- Can you reproduce this issue with the beta channel? 1.48.x yes
- Can you reproduce this issue with the nightly channel? 1.49.x yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @Miyayes @tmancey @btlechowski

**Comment by Miyayes** [comment]
Note: We’re keeping the 30-day ads history link showing in all cases if Brave Private Ads is enabled. But yes, it shouldn’t be empty if the user saw ads!

**Comment by Miyayes** [comment]
Should uplift to 1.48.x since I believe it is a regression starting in 1.48.x.

**Comment by kjozwiak** [comment]
The above requires `1.48.143` or higher for `1.48.x` verification 👍
