### ISSUE TITLE
`-- Learn more` link in Rewards overlay should go to `https://brave.com/rewards-changes` not `https://brave.com/brave-rewards/`

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#27986]
## Description 

`-- Learn more` link in Rewards overlay (i.e., Rewards dropdown panel) should go to `https://brave.com/rewards-changes` not `https://brave.com/brave-rewards/`

## Steps to reproduce 

1. installed `1.47.161`
2. launched Brave
3. enabled Brave Rewards
4. installed `1.48.137` atop `1.47.161` (both are beta-channel builds)
5. launched Brave
6. tapped the `BAT icon`
7. examined and clicked on the `Learn more` link

## Actual result 

Link goes to `https://brave.com/brave-rewards/`

BAT-icon overlay | `https://www.brave.com/rewards`
------------------|---------------------------------
![Screenshot_20230123-125338](https://user-images.githubusercontent.com/387249/214149003-673d9578-a118-4e57-88c0-b22705526340.png)

NOTE: `brave://rewards` has the links correctly

## Expected result

Link should go to `https://brave.com/rewards-changes`

## Issue reproduces how often 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): `arm64`
   - Device type (Phone, Tablet, Phablet): `Google Pixel XL`
   - Android version: `9`
   
## Brave version

`1.48.137`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

/cc @deeppandya @Miyayes @LaurenWags

**Comment by Miyayes** [comment]
Will need uplift to 1.48.x.

**Comment by kjozwiak** [comment]
The above requires `1.48.140` or higher for `1.48.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using `Brave` `1.48.141` on a `Google Pixel XL` (`arm64`) running `Android 9`

Followed my original steps to reproduce

#### Confirmed the link in the panel/overlay now goes to `https://brave.com/rewards-changes`


https://user-images.githubusercontent.com/387249/214908601-28401f34-d0f3-46af-ace7-4f4497b273b0.mp4
