### ISSUE TITLE
Add keyboard shortcut to show/hide sidebar

### ISSUE THREAD

**Issue by A-t-s-u-s-h-i** [brave/brave-browser#27994]
## Description 
I have a user who is considering to change his main browser from Vivaldi to Brave. He says Brave should have a shortcut key to show/hide sidebar. Now users need to move mouse cursor to the side of the browser window or click sidebar button to show/hide sidebar. But sometimes these operations could be frustrating users a bit. It would be very nice if Brave has the shortcut key to show/hide sidebar.

FYI, Vivaldi shows/hides sidebar by [option] + [command] + [p] on MacOS.

**Comment by rebron** [comment]
Proposing Ctrl+B on Windows and command+B on macOS to match Firefox open/close of sidebar.

**Comment by rebron** [comment]
cc: @simonhong @spylogsster 
@bradleyrichter @aguscruiz

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.50.90 Chromium: 111.0.5563.64 (Official Build) beta (x86_64)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | macOS Version 11.7.4 (Build 20G1120)

### Steps:
1. installed `1.50.90`
2. launched Brave
3. clicked on the `Show Sidebar` button on the browser toolbar
4. confirmed it opened
5. pressed `command` + `B`
6. confirmed the sidebar snapped closed
7. pressed `command` + `B` again
8. confirmed the sidebar opened

example | example | example
---------|---------|----------
<img width="1312" alt="Screen Shot 2023-03-13 at 4 01 32 PM" src="https://user-images.githubusercontent.com/387249/224851913-7e8d8774-c7aa-48e2-ace0-09009e4b09ab.png"> | <img width="1312" alt="Screen Shot 2023-03-13 at 4 01 28 PM" src="https://user-images.githubusercontent.com/387249/224851943-be9401fc-89d0-4080-b443-0c7ea0271efb.png"> | <img width="1312" alt="Screen Shot 2023-03-13 at 4 07 32 PM" src="https://user-images.githubusercontent.com/387249/224852048-fa15f226-f2f3-4f01-ada2-90870268cbff.png">

**Comment by LaurenWags** [comment]
@brave/qa-team please check keyboard shortcut on previous release (1.49.x) to confirm we're not overriding a previous keyboard shortcut as well as confirming the keyboard shortcut behaves as expected with 1.50.x.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.50.93 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | Ubuntu 18.04 LTS

New Profile - Sidebar left

1. Install 1.50.x
2. launch Brave
3. clicked on the Show Sidebar button on the browser toolbar
4. confirmed it opened
5. pressed Ctrl+ B
6. confirmed the sidebar snapped closed
7. pressed ctrl + B again
8. confirmed the sidebar opened
9. clicked reading list icon to close the sidepanel and sidebar


![image](https://user-images.githubusercontent.com/34715963/229535507-14eb4a33-093d-40ac-b1b8-f1cc4fd30f0e.png)
![image](https://user-images.githubusercontent.com/34715963/229535727-d72d2eb0-9f0a-4339-a6c4-e617094e8b33.png)


Upgrade - Sidebar right

1. Install 1.49.x
2. launch Brave
3. open brave://settings/appearance
4. select `Show on right` option in `Show Sidebar button
6. close the browser
7. relaunch Brave with 1.50.x
8. clicked on the Show Sidebar button on the browser toolbar
9. confirmed it opened
10. pressed Ctrl+ B
11. confirmed the sidebar snapped closed 

1.49.x
![image](https://user-images.githubusercontent.com/34715963/229537837-22a95dea-116b-47e7-9b0f-be21018bc9d0.png)

1.50.x
![image](https://user-images.githubusercontent.com/34715963/229574906-74fe96e5-83f4-4c26-8968-7f4d66615b70.png)
![image](https://user-images.githubusercontent.com/34715963/229575103-fb24f2b1-eab2-4d1c-badb-347a9a9f44af.png)

**Comment by bastian-purrer** [comment]
As a user that doesn't use the sidebar, this implementation is very flawed. I accidentally open the sidebar, with no obvious way to close it. 
The sidebar is also opened if I explicitely de-activated it in the Brave settings. And there is no way to deactivate or change the shortcut. Major headache

**Comment by simonhong** [comment]
> As a user that doesn't use the sidebar, this implementation is very flawed. I accidentally open the sidebar, with no obvious way to close it. The sidebar is also opened if I explicitely de-activated it in the Brave settings. And there is no way to deactivate or change the shortcut. Major headache

@bastian-purrer I think you could remove unwanted shortcuts from brave://settings/system/shortcuts.
As it's available from 1.53.x(currently in beta), you could customize shortcuts from the next major update if you're using stable channel now. Hope that helps!
<img width="1146" alt="image" src="https://github.com/brave/brave-browser/assets/6786187/d1364823-a65c-4d41-b3c5-eaa1cb346c64">

**Comment by q2apro** [comment]
The decision to user CTRL B is unfortunately bad.

Every time I am using an editor (HTML textarea) and mark a word, then hit Ctrl B, the word gets marked bold - ⚠️ AND the sidebar of Brave shows up.

I cannot deactivate it under brave://settings/system/shortcuts

There are also no browser settings.

Please remove this shortcut again.

**Comment by simonhong** [comment]
> 

@q2apro Sorry for the inconvenience. We're planning to release major update next week.
With it. you could remove `ctrl + b` from brave://settings/system/shortcuts

**Comment by mihaime** [comment]
this one is super annoying especially in Confluence where you use ctrl+b / cmd+b to Bold Text. 
Now instead the sidebar keeps popping up..

**Comment by q2apro** [comment]
The latest update did NOT solve the issue.

**Comment by elron** [comment]
Please re-open this issue. 
The command +B should be reserved to bold text in text editors, not open sidebar. (Personally I don't use the sidebar at all)

**Comment by ioo52987** [comment]
I can see how cmd+B would be an issue for people trying to bold text, but I personally LOVE the shortcut, .... but I also agree with the users above; there needs to be a place where they can override that shortcut. Anyhow, as a big bookmark junkie I'm really into this feature. Ty!
