### ISSUE TITLE
Version 0.60.6 gets "Aw, Snap" in incognito mode with Developer Tools open and you resize the tool window

### ISSUE THREAD

**Issue by aleishman01** [brave/brave-browser#2799]
When you are in an Incognito window, and open Developer Tools, resizing the Developer Tools panel crashes the page with an "Aw, Snap" message

## Steps to Reproduce

   1. Open incognito window
   2. Browse to any web page
   3. Press CTRL+SHIFT+J to open the developer tools
   4. Resize the developer tools panel

## Actual result:

The web page crashes to an "Aw, Snap" screen. The Developer Tools Panel display a message: "DevTools was disconnected from the page. Once page is reloaded, DevTools will automatically reconnect"

## Expected result:
Web page resizes without a crash.

## Reproduces how often: 
Easily reproduced in Windows and Linux (Debian).

## Brave version (brave://version info)

Version 0.60.6 Chromium: 72.0.3626.28 (Official Build) dev (64-bit) (Windows 10)
Version 0.60.6 Chromium: 72.0.3626.28 (Official Build) dev (64-bit) (Debian Testing)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
My issue is with the Dev Builds

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields?  No
- Is the issue reproducible on the latest version of Chrome? No

### Additional Information

Google Chrome does not have this problem

**Comment by Y0HO** [comment]
I also have this issue if Im not in Private / incognito Mode.

**Comment by btlechowski** [comment]
Reproduced on

Brave | 0.60.6 Chromium: 72.0.3626.28 (Official Build) dev (64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Windows 7

**Comment by kjozwiak** [comment]
Pretty easy to reproduce using the original STR, example:

![crashresize](https://user-images.githubusercontent.com/2602313/50857421-9688a500-135b-11e9-8e91-bf4317c23626.gif)

Crashes:

* https://stats.brave.com/dashboard#crash/5c3503f93bc9fb001f13b206
* https://stats.brave.com/dashboard#crash/5c3503f93bc9fb001f13b208

Used the following build to reproduce the issue:

Brave | 0.60.6 Chromium: 72.0.3626.28 (Official Build) dev (64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Mac OS X

**Comment by bsclifton** [comment]
Updated milestone to 0.59.x; Uplift PRs available here:
https://github.com/brave/brave-core/pull/1275
https://github.com/brave/brave-core/pull/1276

cc: @srirambv @kjozwiak @rebron @bbondy

**Comment by dayfuaim** [comment]
I still have the same on OSX 10.10.5
**Версия 0.59.21 Chromium: 72.0.3626.28 (Официальная сборка), beta (64 бит)**

Any change of size/position of DevTools gets page crashed.

"_Версия 0.60.13 Chromium: 72.0.3626.53 (Официальная сборка), dev (64 бит)_" is free of this.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.59.25 Chromium: 72.0.3626.53 (Official Build) beta (64-bit)
-- | --
Revision | 98434e6cd182d68ce396daa92e9c6310422e6763-refs/branch-heads/3626@{#620}
OS | Windows

- Verified the STR from issue. No there is no crash when we resize the developer tool on any site. 
- Verified the STR on Private (Incognito) tabs, Normal Tabs and Tor tabs.

**Comment by dayfuaim** [comment]
Yes, now the bug's gone.
"Zed's dead." :)
