### ISSUE TITLE
First paint performance degradation for v1.49.41..v1.49.45

### ISSUE THREAD

**Issue by atuchin-m** [brave/brave-browser#27997]
Found by brave-perf-dashboard:
https://brave-perf-dashboard.appspot.com/report?sid=81cf487b0d145dbb968f6ba1e9578ad3fb9b61bd94855077f4247ccb27169851
Slack thread: https://bravesoftware.slack.com/archives/C3T9S9WKD/p1674560540571669
![image](https://user-images.githubusercontent.com/45488748/214283069-78b04fab-04d1-472b-aa1f-f2f5079eca1a.png)

**Comment by atuchin-m** [comment]
Confirmed: the perf degradation is fixed: https://github.com/brave/brave-core/pull/16900#issuecomment-1408980732

**Comment by kjozwiak** [comment]
> Confirmed: the perf degradation is fixed: [brave/brave-core#16900 (comment)](https://github.com/brave/brave-core/pull/16900#issuecomment-1408980732)

@atuchin-m I'm not sure if QA can do anything re: the above. Will the performance team run through the same check that was done via https://github.com/brave/brave-core/pull/16900#issuecomment-1408980732 on both the `1.48.x` and `1.47.x` channels? Regarding QA, @srirambv will run through the same cases as before via https://github.com/brave/brave-browser/issues/27340#issuecomment-1400494916.

If we're going to check the performance against both `1.48.x` and `1.47.x`, we can leave this opened and label it as `QA Pass` once completed. However, if we're only checking on `master`, we can label this as `QA/No` unless @darkdh has anything that he would like QA to run through regarding the above.

**Comment by atuchin-m** [comment]
@kjozwiak I believe checking PR performance on nightly was enough for that issue.
cc @iefremov

**Comment by kjozwiak** [comment]
Going to label this one as `QA/No` as per https://github.com/brave/brave-browser/issues/27997#issuecomment-1411715464. However, QA still run through https://github.com/brave/brave-browser/issues/27340 similar to what @srirambv did via https://github.com/brave/brave-browser/issues/27340#issuecomment-1400494916.

**Comment by kjozwiak** [comment]
Moving this into `1.48.x` as we neve received another `C109` minor chromium bump that would have triggered another `1.47.x` release. We'll leave https://github.com/brave/brave-core/milestone/267 as there's code that landed in `1.47.x` but we'll close off the `1.47.x - Release #6` milestone and move all the issues within `1.48.x`.

The above can be verified with `1.48.156` for `1.48.x` as it's been merged into a `1.48.x` a while ago as per https://github.com/brave/brave-core/pull/16900.
