### ISSUE TITLE
Keyboard shortcut for "Switch to this tab"

### ISSUE THREAD

**Issue by BenjaminMichaelis** [brave/brave-browser#27993]
When searching, when the option for "Switch to this tab" I haven't found a keyboard shortcut to select this option. This would allow a user to jump to this open tab without needing to take their hands off the keyboard. Maybe like Ctrl + Shift + Enter or such?

![image](https://user-images.githubusercontent.com/22186029/214194709-27e80449-e265-4644-9786-7159138b6c20.png)

**Comment by rebron** [comment]
Hi @BenjaminMichaelis You can use tab or up and down arrow keys to get focus on that Switch to this tab entry in the url bar.
