### ISSUE TITLE
Remove "Allow contributions for videos" setting in Auto-Contribute because it does not work

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#27990]
## Description 

Previously, the "Allow contributions for videos" auto contribution setting would control whether media publishers could be shown in the auto contribution table.

In 1.47.x, 1.48.x, 1.49.x this setting no longer seems to work. Unsure when it stopped working.

## Steps to Reproduce

   1. Using one of the above versions make sure you can see the auto contribution table on brave://rewards
   2. Visit a handful of sites (videos on YT, regular sites, etc - some verified, some not)
   3. Go to Auto-Contribute section of brave://rewards
   4. Modify the settings so that "Allow contributions for videos" is off 
   5. Close settings and view a-c section
   6. Your video creator(s) are still listed

## Actual result:

1.47.x settings | 1.47.x AC | 1.48.x settings | 1.48.x AC
---- | ---- | ---- | ----
<img width="661" alt="Screen Shot 2023-01-23 at 4 50 40 PM" src="https://user-images.githubusercontent.com/28145373/214157982-8fd24fce-5c6e-4112-9131-e63a9d0007b7.png"> | <img width="659" alt="Screen Shot 2023-01-23 at 4 50 47 PM" src="https://user-images.githubusercontent.com/28145373/214157985-85fa3ece-a4ee-400d-9477-f7b2c2210f95.png"> | <img width="657" alt="Screen Shot 2023-01-23 at 4 51 07 PM" src="https://user-images.githubusercontent.com/28145373/214157986-895a1e1c-41ce-4a7f-bf3f-94b875cdc3e4.png"> | <img width="705" alt="Screen Shot 2023-01-23 at 4 51 14 PM" src="https://user-images.githubusercontent.com/28145373/214157987-4e70632f-3afe-4f3b-8538-89792cb80c67.png">

## Expected result:

Videos (Jonathan Sampson on Youtube in above examples) should not be listed in AC panel

## Reproduces how often: 

easily

## Desktop Brave version:

1.47.x, 1.48.x, 1.49.x

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @Miyayes

**Comment by LaurenWags** [comment]
note, https://github.com/brave/brave-browser/issues/13394 still open - so likely this setting controlled the display of all media publishers (twitter, GH, etc) in the AC list, not just video ones.

**Comment by zenparsing** [comment]
This setting will control whether or not a "media publisher" on one of the Greaselion-enabled sites will be added to the AC table. It currently does not filter out or remove any existing entries in the AC tables.

After GL was implemented, all media sites were changed to be routed through the save "video" AC path for AC measurement purposes. That's the explanation behind #13394.

@Miyayes What do you think the follow-up for this should be?

**Comment by GeetaSarvadnya** [comment]
Unabl eto reproduce the issue on `Samsung Galaxy Android version 12` - running on `Bravemonoarm64.apk_1.48.141`

**Comment by Miyayes** [comment]
We will be removing this toggle as it does not work and does not add much value.

**Comment by LaurenWags** [comment]
@brave/qa-team when testing this also check upgrade scenarios (setting enabled, setting disabled, AC enabled, AC disabled, etc)

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on 

```
Brave | 1.51.79 Chromium: 112.0.5615.49 (Official Build) beta (64-bit)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Windows 10 Version 21H2 (Build 19044.2728)

```
**_Clean profile_**

**_Upgrade profile_**

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Samsung Galaxy version 12` running `Bravemonoarm64.apk_1.51.79`
