### ISSUE TITLE
Migrate `getBuyUrl` call to `getBuyUrlV1`

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#27996]
## Description 
Migrate `BlockchainRegistry` `getBuyUrl` call to `getBuyUrlV1` from `AssetRatioService` for broader support and to [remove old dependency](https://github.com/brave/brave-browser/issues/23503).

## Expected result
The buy click option should work as expected.

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/23316#issuecomment-1465863137. Verified Buy option works as expected
