### ISSUE TITLE
remove grey border from Brave News onboarding card/modal via NTP - follow up to #23755

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#27992]
## Description 

As per https://github.com/brave/brave-browser/issues/23755#issue-1288300671, we should remove the grey border that's appearing on the `Brave News` onboarding card/modal on the NTP. Looks like https://github.com/brave/brave-browser/issues/23755#issuecomment-1203483795 didn't address the issue.

## Steps to reproduce 

   1. install `1.47.175 Chromium: 109.0.5414.87`
   2. run through onboard and take a look at the `Brave News` onboarding card/modal appearing via NTP
   3. notice that there's a hard to see grey border that's being displayed

## Actual result 

![image](https://user-images.githubusercontent.com/2602313/214166355-58db0a77-e66b-4523-875a-e1339fa72fc5.png)

## Expected result

As per https://github.com/brave/brave-browser/issues/23755#issue-1288300671, we shouldn't be displaying a grey border.

## Issue reproduces how often 

100% reproducible using the STR/Cases outlined above.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `Yes`
- Can you reproduce this issue with the current Play Store Beta version? `Yes` 
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Samsung S10+` (Phone)
   - Android version: `Android 12`
   
## Brave version

```
Brave | 1.47.175 Chromium: 109.0.5414.87 (Official Build) (64-bit)
--- | ---
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | Android 12; Build/SP1A.210812.016
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

### Additional information

CCing @srirambv @deeppandya @Uni-verse @tapanmodh @timchilds

**Comment by kjozwiak** [comment]
The above requires `1.48.150` or higher for `1.48.x` verification 👍

**Comment by stephendonner** [comment]
Verified `PASSED` using `1.48.151`, `Chromium` `109.0.5414.119` on a `Google Pixel XL` (`arm64`) running `Android 9`

I zoomed in on this ever-so-faint (darker) border, using `1.47.161`.

Confirmed it's removed in `1.48.151`.

`1.47.161` | `1.48.151`
-----------|---------
![Screenshot_20230131-212151](https://user-images.githubusercontent.com/387249/215958903-02b5b67b-0111-4625-82a7-cd6641e0b3d3.png) | ![Screenshot_20230131-212259](https://user-images.githubusercontent.com/387249/215958912-c3a770ce-2ffc-460e-a0dd-f6041537b8c1.png)

`border` | `no border`
----------|-----------
<img width="611" alt="Screen Shot 2023-01-31 at 9 28 24 PM" src="https://user-images.githubusercontent.com/387249/215959358-692b5cc3-1a5d-42fa-8b6d-75a15f3bf6f3.png"> | <img width="560" alt="Screen Shot 2023-01-31 at 9 28 39 PM" src="https://user-images.githubusercontent.com/387249/215959360-7b8b72bf-672b-401b-bdf2-b501cb6b37a9.png">
