### ISSUE TITLE
DCHECK Failure on Startup

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#280]
## Description 
Brave crashes on startup.

## Steps to Reproduce
Launch Brave.

 ## Actual result:
Crash.

![image](https://user-images.githubusercontent.com/815158/41058152-abf69806-698e-11e8-9cc4-d87ec8b2ef16.png)

## Expected result:
No crash.

## Reproduces how often: 
Always.

**Comment by bbondy** [comment]
I think this should be fixed by this:
https://github.com/brave/brave-browser/issues/277

You could also switch to release builds to avoid debug assertions completely for now.
