### ISSUE TITLE
connected state does not show payout banner on NTP widget

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#28006]
## Description 

See test case 17 from QA doc for testing rewards state changes (see @Miyayes for access).

When a custodian is connected, the processing and complete payout banners display as expected on the panel and brave://rewards. They do not display on the NTP widget.

Note - "pending" messaging displays fine in all 3 places.

## Steps to Reproduce

17.1 Create a new Rewards profile then connect to a custodian (Uphold)
17.2 View couple of ads and confirm ads are cashed in with the server (verify `Successfully redeemed unblinded payment tokens` msg in logs)
17.3 Look for the last message similar to "You have X unblinded payment tokens which will be redeemed in (some hours, minutes, seconds) at (some time)" message, once this time has come, you should then see a response in the logs for "OnRedeemUnblindedPaymentTokens". If this is successful, you can proceed to next steps after closing the browser.

Logs:

```
[4687:259:0124/101421.320639:VERBOSE1:redeem_unblinded_payment_tokens.cc(139)] OnRedeemUnblindedPaymentTokens
[4687:259:0124/101421.320744:VERBOSE6:redeem_unblinded_payment_tokens.cc(141)] URL Response:
  URL: https://mywallet.ads.bravesoftware.com/v3/confirmation/payment/9e1fb591-488f-513c-9db7-c9d0d3cd41d4
  Response Status Code: 200
  Response: {"message":"Ok","status":200}
```

17.4 Advance clock to the next month to the 2nd (or between 1st and 7th), and then relaunch the browser, to see if you see any “Payout will arrive in x days” banner”. This banner displays as expected. Close browser.

Example | Example | Example
---- | ---- | ----
<img width="1862" alt="4a" src="https://user-images.githubusercontent.com/28145373/214335629-4b142853-442d-4b6d-ad5b-ff9046fb0202.png"> | <img width="1868" alt="4b" src="https://user-images.githubusercontent.com/28145373/214335637-42c53a49-6385-4a12-bebd-af7115cc678e.png"> | <img width="1865" alt="4c" src="https://user-images.githubusercontent.com/28145373/214335640-a12b7ac6-2912-4305-8027-577006f78a85.png">

17.5 Advance your clock to the 8th or later and then relaunch the browser.
17.6 Ask someone on server team, or use Charles Proxy to set the payout status at the staging /parameters endpoint to “processing” for Uphold users/payout status.
17.7 Make sure that the browser has picked up this new /parameters value.

Logs:

```
[ REQUEST ]
> URL: https://api.rewards.bravesoftware.com/v1/parameters
> Method: GET
[4991:259:0208/101914.132505:VERBOSE6:logging_util.cc(134)] 
[ RESPONSE - OnResponse ]
> Url: https://api.rewards.bravesoftware.com/v1/parameters
> Result: Success
> HTTP Code: 200
> Body: {"autocontribute":{"choices":[1,2,3,5,7,10,20],"defaultChoice":1},"batRate":0.261167,"custodianRegions":{"bitflyer":{"allow":["JP"],"block":[]},"gemini":{"allow":["AU","AT","BE","CA","CO","DK","FI","HK","IE","IT","NL","NO","PL","PT","SG","ES","SE","GB","US"],"block":[]},"uphold":{"allow":["AU","AT","BE","CA","CO","DK","FI","HK","IE","IT","NL","NO","PL","PT","SG","ES","SE","GB","US","IN"],"block":[]}},"payoutStatus":{"bitflyer":"complete","gemini":"complete","payoutDate":"","unverified":"complete","uphold":"processing"},"tips":{"defaultMonthlyChoices":[1.25,5,10.5],"defaultTipChoices":[1.25,5,10.5]},"vbatDeadline":"2023-01-19T00:00:00Z","vbatExpired":true}
```

--> 17.8 The “processing” banner does appear in the Rewards panel and brave://rewards page but not NTP widget. 

Example | Example | Example
---- | ---- | ----
<img width="1866" alt="8a" src="https://user-images.githubusercontent.com/28145373/214335799-c62b7c34-1e59-4212-b143-b8995941344b.png"> | <img width="1865" alt="8b" src="https://user-images.githubusercontent.com/28145373/214335802-2339f190-c1a8-40a5-acc6-698297251951.png"> | <img width="1871" alt="8c" src="https://user-images.githubusercontent.com/28145373/214335805-135d7b9c-53f1-4c3b-ab7f-18ed1641a86b.png">

17.9 Ask someone on server team, or use Charles Proxy to set the payout status at the staging /parameters endpoint to “complete” for Uphold users/payout status.
17.10 Make sure that the browser has picked up this new /parameters value.

Logs:

```
[ REQUEST ]
> URL: https://api.rewards.bravesoftware.com/v1/parameters
> Method: GET
[5119:259:0208/102136.827925:VERBOSE6:logging_util.cc(134)] 
[ RESPONSE - OnResponse ]
> Url: https://api.rewards.bravesoftware.com/v1/parameters
> Result: Success
> HTTP Code: 200
> Body: {"autocontribute":{"choices":[1,2,3,5,7,10,20],"defaultChoice":1},"batRate":0.26234,"custodianRegions":{"bitflyer":{"allow":["JP"],"block":[]},"gemini":{"allow":["AU","AT","BE","CA","CO","DK","FI","HK","IE","IT","NL","NO","PL","PT","SG","ES","SE","GB","US"],"block":[]},"uphold":{"allow":["AU","AT","BE","CA","CO","DK","FI","HK","IE","IT","NL","NO","PL","PT","SG","ES","SE","GB","US","IN"],"block":[]}},"payoutStatus":{"bitflyer":"complete","gemini":"complete","payoutDate":"","unverified":"complete","uphold":"complete"},"tips":{"defaultMonthlyChoices":[1.25,5,10.5],"defaultTipChoices":[1.25,5,10.5]},"vbatDeadline":"2023-01-19T00:00:00Z","vbatExpired":true}
```

17.11 The “complete” banner does appear in the Rewards panel and brave://rewards page but not NTP widget.

Example | Example | Example
---- | ---- | ----
<img width="1872" alt="11a" src="https://user-images.githubusercontent.com/28145373/214336025-edb1a649-51da-46a3-9f8e-2c99c5cfc4ad.png"> | <img width="1872" alt="11b" src="https://user-images.githubusercontent.com/28145373/214336030-0321c48e-8363-423a-91b9-43e96a7dff98.png"> | <img width="1863" alt="11c" src="https://user-images.githubusercontent.com/28145373/214336036-cc4df38a-306c-44d2-a0be-48bc9e8c174c.png">

17.12 Bring your clock back to the current month to 9th or later, and then relaunch the browser, and make sure you don’t see the banners (because it’s the wrong month)

Example | Example | Example
---- | ---- | ----
<img width="1865" alt="12a" src="https://user-images.githubusercontent.com/28145373/214336095-80a35a9d-982a-4f2e-8f74-3b452755a29d.png"> | <img width="1867" alt="12b" src="https://user-images.githubusercontent.com/28145373/214336098-9442bd69-b78a-4b30-b77c-2f5cf0c7c54d.png"> | <img width="1872" alt="12c" src="https://user-images.githubusercontent.com/28145373/214336102-0c94c557-0d09-4092-aa8f-af6edecc3c32.png">

## Actual result:

see above, screenshots are in line w/ steps

## Expected result:

processing and complete banners should show on NTP widget in steps 8 and 11 respectively as they show on the panel and rewards page.

## Reproduces how often: 

easily

## Desktop Brave version:

1.48.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? no, works on 1.47.x
- Can you reproduce this issue with the beta channel? yes 1.48.x
- Can you reproduce this issue with the nightly channel? likely yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @Miyayes

**Comment by kjozwiak** [comment]
The above requires `1.48.143` or higher for `1.48.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.48.148 Chromium: 109.0.5414.119 (Official Build) beta (x86_64)
-- | --
Revision | 772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}
OS | macOS Version 12.6.3 (Build 21G419)
```
