### ISSUE TITLE
Fix component updater info global/static variables

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#28004]
There are several places with a code-style violation (https://google.github.io/styleguide/cppguide.html#Static_and_Global_Variables), which increases the binary size.

https://github.com/brave/brave-core/blob/master/components/brave_ads/browser/component_updater/components.h#L16

https://github.com/brave/brave-core/blob/master/components/ntp_background_images/browser/sponsored_images_component_data.cc

**Comment by goodov** [comment]
there're many places like that:
Use this search parameters in vscode:
```
^const .*=

files to include:
brave/**/*ad*/**/*.h
```
![image](https://user-images.githubusercontent.com/5928869/214568504-c51fc657-b5d9-409e-a8f6-55ca71cfe0a9.png)
