### ISSUE TITLE
Auto Discovery for Filecoin Assets and Accounts

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#28002]
## Description 

We are building auto discovery for ERC tokens and Solana tokens. We should also do this for Filecoin.

## Steps to Reproduce

   1. 
   2. 
   3. 

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by yrliou** [comment]
AFAIK Filecoin does not have other tokens other than Filecoin itself, so I think we probably only need account discovery for Filecoin.

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.53.94 x64 Beta build
- Verified steps from [brave/brave-core#18283](https://github.com/brave/brave-core/pull/18283)
- Verified importing a wallet restores all non-zero balance accounts for both ETH and SOL

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.53.94 Chromium: 114.0.5735.133 (Official Build) beta (64-bit)
-- | --
Revision | `fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}`
OS | Windows 11 Version 22H2 (Build 22621.1848)

- Verified steps from [brave/brave-core#18283](https://github.com/brave/brave-core/pull/18283)
- Verified importing a wallet restores all non-zero balance accounts for both ETH, SOL & FIL accounts

https://github.com/brave/brave-browser/assets/17010094/fead9909-1bd8-49cd-900e-1618c813a874
