### ISSUE TITLE
Remove reference to rewards on reset flow on Android

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#28003]
## Description 

See screenshot
![Screenshot_20230120_165505_Brave](https://user-images.githubusercontent.com/12224304/214329572-741d4802-2980-48e8-8f18-129ae76f4ae4.jpg)
 Insert Wallet instead of Rewards

## Steps to Reproduce

   1. 
   2. 
   3. 

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by yash251** [comment]
Please assign me this issue

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.58.117 x64 build
- Verified steps from [brave/brave-core#19303](https://github.com/brave/brave-core/pull/19303)
- Verified references to Brave Rewards is removed from the reset wallet confirmation prompt

Oppo Reno 5 (Android 13) | Samsung Tab A (Android 12)
-- | --
<video src=https://github.com/brave/brave-browser/assets/17010094/5e8f62a2-14a9-4e6f-b7b2-7bb0a64d61b8> | <video src=https://github.com/brave/brave-browser/assets/17010094/654eeda1-c16c-47db-adb9-76bddbecbbfe>
