### ISSUE TITLE
grandfathered unverified state does not display processing or complete payout banners

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#28001]
## Description 

The grandfathered unverified state does not display "processing" or "complete" payout banners. It does display the "pending" banner.

See test case 16 from QA doc (see @Miyayes for access to doc)

## Steps to Reproduce

16.1 Create rewards profile on older version of Brave and view some ads. Then update to 1.48.x so that you’re in the grandfathered-unverified state.
16.2 View couple of ads and confirm ads are cashed in with the server (verify `Successfully redeemed unblinded payment tokens` msg in logs)
16.3 Look for the last message similar to "You have X unblinded payment tokens which will be redeemed in (some hours, minutes, seconds) at (some time)" message, once this time has come, you should then see a response in the logs for "OnRedeemUnblindedPaymentTokens". If this is successful, you can proceed to next steps.
16.4 Close browser. Advance clock to the next month to the 2nd (or between 1st and 7th), and then relaunch the browser, to see if you see any “Payout will arrive in x days” banner”. This banner displays as expected:

Example | Example | Example
---- | ---- | ----
<img width="2202" alt="4a" src="https://user-images.githubusercontent.com/28145373/214324197-0e6fa5d4-c53e-4c5c-bd85-39aa47743c58.png"> | <img width="2207" alt="4b" src="https://user-images.githubusercontent.com/28145373/214324202-25ce020b-4d9b-4384-8ebe-522331bb596b.png"> | <img width="2207" alt="4c" src="https://user-images.githubusercontent.com/28145373/214324203-dce22244-e3a4-4d88-b2a4-c1ae9b4b7cea.png">

16.5 Advance your clock to the 8th or later and then relaunch the browser.
16.6 Ask someone on server team, or use Charles Proxy to set the payout status at the staging /parameters endpoint to “processing” for unverified users.
16.7 Make sure that the browser has picked up this new /parameters value.

Logs:

```
[ REQUEST ]
> URL: https://api.rewards.bravesoftware.com/v1/parameters
> Method: GET
......
[ RESPONSE - OnResponse ]
> Url: https://api.rewards.bravesoftware.com/v1/parameters
> Result: Success
> HTTP Code: 200
> Body: {"autocontribute":{"choices":[1,2,3,5,7,10,20],"defaultChoice":1},"batRate":0.261167,"custodianRegions":{"bitflyer":{"allow":["JP"],"block":[]},"gemini":{"allow":["AU","AT","BE","CA","CO","DK","FI","HK","IE","IT","NL","NO","PL","PT","SG","ES","SE","GB","US"],"block":[]},"uphold":{"allow":["AU","AT","BE","CA","CO","DK","FI","HK","IE","IT","NL","NO","PL","PT","SG","ES","SE","GB","US","IN"],"block":[]}},"payoutStatus":{"bitflyer":"complete","gemini":"complete","payoutDate":"","unverified":"processing","uphold":"complete"},"tips":{"defaultMonthlyChoices":[1.25,5,10.5],"defaultTipChoices":[1.25,5,10.5]},"vbatDeadline":"2023-01-19T00:00:00Z","vbatExpired":true}
```

---> 16.8 The “processing” banner does not appear in the Rewards panel, NTP widget, and brave://rewards page as it should:

Example | Example | Example
---- | ---- | ----
<img width="2205" alt="8a" src="https://user-images.githubusercontent.com/28145373/214324752-c03c4a8b-a47d-4661-b65c-cda303151345.png"> | <img width="2218" alt="8b" src="https://user-images.githubusercontent.com/28145373/214324757-9e8edc6f-589a-4713-a638-b19b89ac9c64.png"> | <img width="2205" alt="8c" src="https://user-images.githubusercontent.com/28145373/214324761-1917c3b3-dfe9-4334-9c11-4421ee0918b9.png">

16.9 Ask someone on server team, or use Charles Proxy to set the payout status at the staging /parameters endpoint to “complete” for unverified users.
16.10 Make sure that the browser has picked up this new /parameters value.

Logs:

```
[ REQUEST ]
> URL: https://api.rewards.bravesoftware.com/v1/parameters
> Method: GET
[3896:259:0208/093501.525166:VERBOSE6:logging_util.cc(134)] 
[ RESPONSE - OnResponse ]
> Url: https://api.rewards.bravesoftware.com/v1/parameters
> Result: Success
> HTTP Code: 200
> Body: {"autocontribute":{"choices":[1,2,3,5,7,10,20],"defaultChoice":1},"batRate":0.260985,"custodianRegions":{"bitflyer":{"allow":["JP"],"block":[]},"gemini":{"allow":["AU","AT","BE","CA","CO","DK","FI","HK","IE","IT","NL","NO","PL","PT","SG","ES","SE","GB","US"],"block":[]},"uphold":{"allow":["AU","AT","BE","CA","CO","DK","FI","HK","IE","IT","NL","NO","PL","PT","SG","ES","SE","GB","US","IN"],"block":[]}},"payoutStatus":{"bitflyer":"complete","gemini":"complete","payoutDate":"","unverified":"complete","uphold":"complete"},"tips":{"defaultMonthlyChoices":[1.25,5,10.5],"defaultTipChoices":[1.25,5,10.5]},"vbatDeadline":"2023-01-19T00:00:00Z","vbatExpired":true}
```

---> 16.11 The “complete” banner does not appear in the Rewards panel, NTP widget, or brave://rewards page as expected

Example | Example | Example
---- | ---- | ----
<img width="2207" alt="11a" src="https://user-images.githubusercontent.com/28145373/214325549-9752cda8-6812-4e1b-b2ab-f9a7d71196d6.png"> | <img width="2198" alt="11b" src="https://user-images.githubusercontent.com/28145373/214325551-dbdbce6b-11b3-41a3-a121-2f1501ea7dfa.png"> | <img width="2204" alt="11c" src="https://user-images.githubusercontent.com/28145373/214325554-13859f4e-b5c5-4630-81a1-4800b6ad3722.png">

16.12 Bring your clock back to the current month to 9th or later, and then relaunch the browser, and make sure you don’t see the banners (because it’s the wrong month)

Example | Example | Example
---- | ---- | ----
<img width="2211" alt="12a" src="https://user-images.githubusercontent.com/28145373/214325616-5ce67c2f-58ec-41bf-be36-de56a62fadb0.png"> | <img width="2207" alt="12b" src="https://user-images.githubusercontent.com/28145373/214325619-85b73a1a-a731-4959-b966-8bf382836a5b.png"> | <img width="2208" alt="12c" src="https://user-images.githubusercontent.com/28145373/214325620-9266e973-0883-4539-b0dc-949ba4e2160b.png">

## Actual result:

see above, screenshots are in line w/ steps

## Expected result:

processing and complete banners should show in steps 8 and 11 respectively.

Here's an example from 1.47.x of the "complete" banner:

Example | Example | Example
---- | ---- | ----
<img width="2212" alt="Screen Shot 2023-02-08 at 9 52 24 AM" src="https://user-images.githubusercontent.com/28145373/214327450-a28f4d21-7df4-4f11-a6bf-ea659bf9d538.png"> | <img width="2208" alt="Screen Shot 2023-02-08 at 9 52 34 AM" src="https://user-images.githubusercontent.com/28145373/214327459-c12385bd-adcd-4bfc-8fe0-4ca3d231d333.png"> | <img width="2205" alt="Screen Shot 2023-02-08 at 9 52 44 AM" src="https://user-images.githubusercontent.com/28145373/214327461-a6abc707-4ced-4c64-bd42-98006e5cd2ed.png">

## Reproduces how often: 

easily

## Desktop Brave version:

1.48.x

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? no, works on 1.47.x
- Can you reproduce this issue with the beta channel? yes 1.48.x
- Can you reproduce this issue with the nightly channel? likely yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @Miyayes @brave/qa-team

**Comment by LaurenWags** [comment]
@brave/qa-team when retesting this, we should also re-verify test case 15 from QA doc for "Rewards payout banner status (non-connected state)" to ensure that is still working as expected since that is also an unverified state.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.48.148 Chromium: 109.0.5414.119 (Official Build) beta (x86_64)
-- | --
Revision | 772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}
OS | macOS Version 12.6.3 (Build 21G419)
```

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Samsung Galaxy version 12` running `Bravemonoarm64.aok_1.48.148`
 - Verification notes (case 15, 16 and 17) can be found in https://github.com/brave/brave-browser/issues/27055#issuecomment-1407957831
