### ISSUE TITLE
Add NTP SI P3A metric for total creatives interacted with

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#28012]
Add a metric for the number of creatives that the user interacted with on a given day. The metric name will be `creativeInstanceId.total.count` and will be sent to the P3A creatives endpoint.

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta (64-bit)
-- | --
Revision | 46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}
OS | Windows 10 Version 21H2 (Build 19044.2604)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/16836#issue-1555540945

**Step 0**: 

 - Clean profile 1.50.61
 - Ensured Ads is disabled
 - Ensured no metrics with the prefix creativeInstanceId exist in the local state page under P3A logs in brave://local-state file

**Step 1:**
 - Open NTP until NTP SI is shown
 - Ensured NTP SI is shown in 2nd tab

![image](https://user-images.githubusercontent.com/38657976/222377872-9f47d7de-eb65-4a4d-abc6-eb6e74ad74ff.png)

**Step 2:**
 - Ensured that the metrics value `1` is not sent immediately over the network via https://p3a-creative.brave.com/
![image](https://user-images.githubusercontent.com/38657976/222387213-dddd9249-6e76-4f38-a316-c8689ead52e3.png)

**Step 3:**
  - Closed the browser and set the sys date ahead by one day
  - Relaunch the browser
  - Ensured that the metrics value `1` is sent over the network via https://p3a-creative.brave.com/
