### ISSUE TITLE
[Desktop] Occasionally, Brave News will not peek on NTP

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#28018]
## Description 

Occasionally, Brave News will not peek on NTP

## Steps to Reproduce

   0. Ensure Brave news is Enabled
   2. Open NTP
   3. Wait 3 seconds
(refresh if problem does not reproduce, it should happen at least once within 5 NTP refreshes)
## Actual result:

Brave News does not peek

## Expected result:
Brave News peeks up

## Reproduces how often: 

Sometimes 100%, sometimes 25%

## Brave version (brave://version info)

1.49.52

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.49.89 Chromium: 110.0.5481.77 (Official Build) beta (x86_64)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | macOS Version 11.7.3 (Build 20G1116)

### Reproduced the issue using `1.49.52`: (very intermittent, as noted)

example | example | example
---------|----------|---------
<img width="1312" alt="Screen Shot 2023-02-07 at 4 56 35 PM" src="https://user-images.githubusercontent.com/387249/217401796-72070668-e658-4494-9641-94567ae83deb.png"> | <img width="1312" alt="Screen Shot 2023-02-07 at 4 56 57 PM" src="https://user-images.githubusercontent.com/387249/217401813-0bca5d66-ddf6-4448-bc82-45a90d12fd27.png"> | <img width="1312" alt="Screen Shot 2023-02-07 at 4 57 15 PM" src="https://user-images.githubusercontent.com/387249/217401818-90283dda-6be2-41e2-9407-1cba27228134.png">

### Confirmed the fix using `1.49.89`:

![brave-news-peeking](https://user-images.githubusercontent.com/387249/217402343-4e4ca4ce-576c-4a67-9585-73b30d3b079c.gif)

Tried the following to break it:
* interrupting the auto-peek via `Reload` button or scrolling the viewport up and down
* `shift` + `reload`
* opening successive new tabs/windows
* alternating tabs/windows
* etc.

#### In all cases so far, it returns to auto-scroll, as it should
