### ISSUE TITLE
Postpone showing `You're earning tokens for viewing this sponsored image` message till user connects to a custodian

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#28019]
Currently we are showing this message after enabling rewards and ads

## Steps to Reproduce

1. Clean profile
1. Enable rewards and ads
1. Open NTP till NTP SI is shown
1. Connect to a custodian
1. Open NTP till NTP SI is shown

## Actual result:

`You're earning tokens for viewing this sponsored image` message after enabling ads and rewards
`You're earning tokens for viewing this sponsored image` message is not shown after user connects to a custodian

## Expected result:
`You're earning tokens for viewing this sponsored image` message is shown after user connects to a custodian
![image](https://user-images.githubusercontent.com/34715963/214417039-9922a729-7d2a-44c0-ac81-e0648c8b2339.png)
![image](https://user-images.githubusercontent.com/34715963/214416908-08ae8402-e8c4-4668-9ef8-daa4fe9b3d0c.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.48.132 Chromium: 109.0.5414.87 (Official Build) beta (64-bit)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | Linux

cc @tmancey @Miyayes @LaurenWags

**Comment by LaurenWags** [comment]
Updated to `QA/No` as this will be verified with https://github.com/brave/brave-browser/issues/28016.
