### ISSUE TITLE
Update messaging on NTP SI in `unconnected` or `grandfather unverified` state

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#28016]
In `unconnected` and `grandfather unverified` states we show message that user is paid for viewing ads.

## Steps to Reproduce

1. Clean profile
1. Enable rewards and ads
1. Open NTP till NTP SI is shown

## Actual result:

Message states that user is earning tokens when viewing the NTP SI
Note: `Learn More` opens `https://brave.com/brave-rewards/`

![image](https://user-images.githubusercontent.com/34715963/214417039-9922a729-7d2a-44c0-ac81-e0648c8b2339.png)
![image](https://user-images.githubusercontent.com/34715963/214416908-08ae8402-e8c4-4668-9ef8-daa4fe9b3d0c.png)

## Expected result:
We should urge user to connect to the custodian

Similar to state when user has not enabled rewards:
![image](https://user-images.githubusercontent.com/34715963/214418017-c2156782-d328-463f-ad8d-0d0f2bb08b6a.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.48.132 Chromium: 109.0.5414.87 (Official Build) beta (64-bit)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | Linux

cc @tmancey @Miyayes @LaurenWags

**Comment by Miyayes** [comment]
Will remove this blue tooltip.

**Comment by Miyayes** [comment]
Uplift to 1.48.x.

**Comment by kjozwiak** [comment]
The above requires `1.48.147` or higher for `1.48.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.48.149 Chromium: 109.0.5414.119 (Official Build) beta (x86_64)
-- | --
Revision | 772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}
OS | macOS Version 12.6.3 (Build 21G419)
```
