### ISSUE TITLE
[Android] Update bitFlyer promo notice text on brave://rewards page

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#28010]
## Description

Update text here:
<img src="https://user-images.githubusercontent.com/11497541/214372279-3daf3879-81ea-4c03-bd9d-26a32c2d2c52.jpg" width=300px>

On 1.49.x. 

To the following text:

**Connect to bitFlyer**

Connecting Brave Rewards to a bitFlyer account will let you earn BAT and withdraw your BAT earnings from Brave Rewards.

Learn more

Don't show again

**Comment by Miyayes** [comment]
Doesn't show on desktop -- only shows on Android.

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Samsung Galaxy version 12` running `Bravemonoarm64.apk_1.49.116`

- Verified the description from the issue an ensured updated text is shown in the brave://rewards page

![Screenshot_20230302-202324_Brave - Beta](https://user-images.githubusercontent.com/38657976/222463963-f47982df-0ffc-45d7-9c62-4fcc61bf9963.jpg)
