### ISSUE TITLE
Create OS VPN entry per channel

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#28028]
## Steps to Reproduce

   1. Install two different channels such as nightly and beta
   2. Enable vpn from both releases
   3. Check created os vpn entry

## Actual result:

Only `BraveVPN` entry is created

## Expected result:
Different vpn entry should be created for each channels
`BraveVPN-Nightly`, `BraveVPN-Dev`, `BraveVPN-Beta` and `BraveVPN`

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
@simonhong Windows-only, or should this also apply to `macOS`?

**Comment by simonhong** [comment]
@stephendonner I tagged macOS also. Although macOS already have per-channel entry, their name will be changed like `BraveVPN-Nightly`.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.49.88 Chromium: 110.0.5481.77 (Official Build) beta (x86_64)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | macOS Version 11.7.3 (Build 20G1116)

### Steps:
1. installed `1.49.88`
2. launched Brave
3. purchased, configured, and connected to `BraveVPN` via `account.bravesoftware.com`
4. looked at the macOS entries for `BraveVPN`

#### Confirmed name is `BraveVPN-Beta`, which matches my build's channel

`browser` | `macOS Network config`
-----------|-------------------------
<img width="1680" alt="Screen Shot 2023-02-07 at 12 22 06 AM" src="https://user-images.githubusercontent.com/387249/217191539-b5d7160a-b577-40c9-ac33-98a11ce54342.png"> | <img width="780" alt="Screen Shot 2023-02-07 at 12 22 20 AM" src="https://user-images.githubusercontent.com/387249/217191591-2d753209-371a-4fda-a73d-a992527c7e2a.png">

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.49.106 Chromium: 110.0.5481.104 (Official Build) beta (64-bit)
-- | --
Revision | 46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}
OS | Windows 10 Version 22H2 (Build 19045.2604)

### Steps:
1. installed `1.49.106`
2. launched Brave
3. purchased, configured, and connected to `BraveVPN` via `account.bravesoftware.com`
4. looked at the Windows 10 entry for `BraveVPN`

#### Confirmed name is `BraveVPN-Beta`, which matches my build's channel

`browser` | `Windows 10 network config`
-----------|--------------------------------
![image](https://user-images.githubusercontent.com/387249/220487439-749573ae-739c-40e0-9717-336b4499953f.png) | ![image](https://user-images.githubusercontent.com/387249/220487583-1e4fb671-4985-47fe-92d8-9c63e4ac1d60.png)
