### ISSUE TITLE
Add a way to disable inline tipping buttons without enabling Brave Rewards

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#28023]
## Description

At buttons in brave://settings/rewards that toggle in-line tipping buttons, regardless of whether Rewards is enabled. 

## Solution

- [ ] On brave://settings/rewards when Rewards is *disabled*, use this construct:

![image](https://user-images.githubusercontent.com/11497541/219107789-f8c84b7e-59e6-4042-b9cd-f75811aaa53b.png)

Change text to: 

**Show Tip buttons on sites** [Master toggle]
[checkbox] Twitter
[checkbox] Reddit
[checkbox] GitHub

- [ ] If requires browser relaunch (ideally would work instantly), prompt user to relaunch Brave. 
- [ ] On brave://settings/rewards when Rewards is *enabled*, copy the same construct where "Tip buttons" currently is
- [ ] On brave://rewards page, under Tip settings, replicate same structure: (1) add master toggle, (2) change "Enable content-level tips on these sites" text to "Show Tip buttons on sites", (3) replace site toggles with checkboxes, and place them on the left of site name: e.g., `[checkbox] Reddit`
- [ ] Retain preferences after user enables Rewards: state says exactly the same
- [ ] BAT icon removal toggle is overloaded -- remove inline tip toggle functionality from that toggle

## Test Plan

**Case 1: Migrate from existing profile / tipping buttons enabled / Rewards not joined**
1. Start a version of Brave prior to this change.
2. Do not join Rewards.
3. Navigate to brave://settings/rewards and verify that the `Show Brave Rewards icon in address bar` is turned `on`.
4. Upgrade to the version of Brave with this change.
5. Navigate to brave://settings/rewards.
6. Verify that:
    a. `Show Brave Rewards icon in address bar` is turned `on`.
    b. `Show Tip buttons on sites` is turned `on`.
    c. All checkboxes under the `Show Tip buttons on sites` are checked.
8. Navigate to https://reddit.com and verify that the inline tipping buttons are shown.
9. On brave://settings/rewards turn the `Show Tip buttons on sites` to `off`.
10. Verify that the `Relaunch` button is shown in the toggle.
11. Click the `Relaunch` button.
12. After the browser restarts, navigate to https://reddit.com and verify that the inline tipping buttons are `not` shown.
13. On brave://settings/rewards turn the `Show Tip buttons on sites` to `on` and click the `Relaunch` button.
14. After the browser restarts, on brave://settings/rewards verify that the `Show Tip buttons on sites` is set to `on` and all checkboxes are checked.
15. Uncheck the `Reddit` checkbox.
16. Verify that the `Relaunch` button is shown and click it.
17. After the browser restarts, navigate to https://reddit.com and verify that the inline tipping buttons are `not` shown.

**Case 2: Migrate from existing profile / tipping buttons disabled / Rewards not joined**
1. Start a version of Brave prior to this change.
2. Do not join Rewards.
3. Navigate to brave://settings/rewards and toggle the `Show Brave Rewards icon in address bar` to `off`.
4. Restart the browser
5. Navigate to https://reddit.com and verify that the inline tipping buttons are `not` shown.
6. Upgrade to the version of Brave with this change.
7. Navigate to brave://settings/rewards.
8. Verify that:
    a. `Show Brave Rewards icon in address bar` is turned `off`.
    b. `Show Tip buttons on sites` is turned `off`.
    c. No checkboxes are shown under the `Show Tip buttons on sites` toggle.
10. Navigate to https://reddit.com and verify that the inline tipping buttons are `not` shown.

**Case 3: Migrate from existing profile / tipping buttons enabled / Rewards joined**
1. Start a version of Brave prior to this change.
2. Join Rewards.
3. Navigate to brave://settings/rewards and verify that
    a. the `Show Brave Rewards icon in address bar` is turned `on`.
    b. the toggles for inline tipping buttons (Reddit, Github, Twitter) are turned `on`.
4. Upgrade to the version of Brave with this change.
5. Navigate to brave://settings/rewards.
7. Verify that:
    a. `Show Brave Rewards icon in address bar` is turned `on`.
    b. `Show Tip buttons on sites` is turned `on`.
    c. All checkboxes under the `Show Tip buttons on sites` are checked.

**Case 4: Migrate from existing profile / tipping buttons disabled / Rewards joined** 
1. Start a version of Brave prior to this change.
2. Join Rewards.
3. Navigate to brave://settings/rewards and turn `off` the `Show Brave Rewards icon in address bar` toggle.
4. Upgrade to the version of Brave with this change.
5. Navigate to brave://settings/rewards.
7. Verify that:
    a. `Show Brave Rewards icon in address bar` is turned `off`.
    b. `Show Tip buttons on sites` is turned `off`.
    c. No checkboxes are shown under the `Show Tip buttons on sites`.

**Case 5: Migrate from existing profile / tipping buttons enabled / Rewards joined / Reddit disabled** 
1. Start a version of Brave prior to this change.
2. Join Rewards.
3. Navigate to brave://settings/rewards and verify that
    a. the `Show Brave Rewards icon in address bar` is turned `on`.
    b. the toggles for inline tipping buttons (Reddit, Github, Twitter) are turned `on`.
4. Turn off the `Reddit` toggle and click the `Relaunch` button.
5. After the browser restarts, navigate to https://reddit.com and verify that the inline tipping buttons are `not` shown.
6. Upgrade to the version of Brave with this change.
7. Navigate to brave://settings/rewards.
8. Verify that:
    a. `Show Brave Rewards icon in address bar` is turned `on`.
    b. `Show Tip buttons on sites` is turned `on`.
    c. `Reddit` checkbox is unchecked, the other checkboxes are checked.
9. Navigate to https://reddit.com and verify that the inline tipping buttons are `not` shown.

**Case 6: Fresh profile**
1. Install a version of Brave with this change.
2. Do not join Rewards.
3. Navigate to brave://settings/rewards and verify that the
    a. `Show Brave Rewards icon in address bar` is turned `on`.
    b. `Show Tip buttons on sites` is turned `on`.
    c. All checkboxes under the `Show Tip buttons on sites` are checked.
4. Join Rewards
5. Navigate to brave://rewards and click on the Tips section's settings button
6. Verify that the
    a. `Show Tip buttons on sites` toggle is turned `on`
    b. All checkboxes under the toggle are checked
7. Turn the `Show Tip buttons on sites` toggle to `off`
8. Verify that:
    a. the checkboxes under the toggle are not shown.
    b. the `Relauch` button is shown.
    c.  on brave://settings/rewards page the `Show Tip buttons on sites` also transitioned to `off`, no checkboxes are shown, and the `Relaunch` button is shown.
9. On brave://settings/rewards page toggle the `Show Tip buttons on sites` to `on`
10. Verify that the `Relaunch` button is no longer shown
11. Uncheck `Reddit` checkbox.
12. Verify that the `Relaunch` button is show in the `Show Tip buttons on sites` toggle again.
13. On the brave://rewards -> Tips section's settings screen verify that the `Show Tip buttons on sites` is set to `on` and the `Reddit` checkbox is unchecked.

**Comment by Miyayes** [comment]
Text:

Show Brave Rewards icon in address bar and Tip buttons on sites

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave | 1.50.85 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | Windows 10 Version 21H2 (Build 19044.2604)

```

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.50.92 Chromium: 111.0.5563.64 (Official Build) beta (x86_64)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | macOS Version 12.6.3 (Build 21G419)
```
