### ISSUE TITLE
ads not blocked on slashdot.org

### ISSUE THREAD

**Issue by 424344** [brave/brave-browser#28029]
## Description 

on the main page of https://slashdot.org/ there are some ads that are not blocked, even with aggressive mode.
example:
![image](https://user-images.githubusercontent.com/26486758/214561061-9052d5ce-f9dd-4cf8-baab-bf676a1c5c43.png)

## Steps to Reproduce

   1. just load https://slashdot.org/
   2. search for "sponsored content"
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/40707d8f96b481b444a2406e2ec6badb7844e876

Will resolve it for the time being, we may need to fix it with a procedural filter if the ad reappears.

**Comment by 424344** [comment]
thanks
