### ISSUE TITLE
USD Coin unavailable for Swap with Jupiter

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#28032]
## Description 

Trying to swap Solana for `USD Coin` on Solana Mainnet but USD Coin is not listed as an option in the Swap To tokens list. Noticed `Basic Attention Token (Portal)` on Solana Mainnet is not shown as well.

## Steps to Reproduce
   1. Open swap
   2. Select SOL as from token
   3. Tap 'Select token' and select Solana network
   4. Search `USD`
   5. Observe no `USD Coin` / `USDC` listed, but`USD Coin (Wormhole)` / `wUSD` is listed.

## Actual result:

<img width="909" alt="Screenshot 2023-01-25 at 10 08 37 AM" src="https://user-images.githubusercontent.com/5314553/214605408-58d19dfb-e072-4e00-9f59-ebdfc28b88d9.png">

USD Coin shown with balance in Portfolio:
<img width="914" alt="Screenshot 2023-01-25 at 10 08 26 AM" src="https://user-images.githubusercontent.com/5314553/214605401-55f7aac6-8c9c-438b-9c98-445cc4cd5d48.png">

## Expected result:

USD Coin is shown

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.47.171 Chromium: 109.0.5414.87 (Official Build) (arm64)
-- | --
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | macOS Version 13.2 (Build 22D49)

## Version/Channel Information:

`Version 1.49.56 Chromium: 109.0.5414.87 (Official Build) nightly (arm64)`

- Can you reproduce this issue with the current release? 
    - No, USD Coin is shown for Swap v1 on `Version 1.47.171 Chromium: 109.0.5414.87 (Official Build) (x86_64)`
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 
    - Yes, USD Coin is not shown for Swap v2 on `Version 1.49.56 Chromium: 109.0.5414.87 (Official Build) nightly (arm64)`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

`USD Coin` on Solana Mainnet (from our Blockchain Registry)
Address `EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v`

`Basic Attention Token (Portal)` on Solana Mainnet (from our Blockchain Registry)
Address `EPeUFDgHRxs9xxEPVaL6kfGQvCon7jmAWKVUHuux1Tpz`

**Comment by kjozwiak** [comment]
The above requires `1.49.92` or higher for `1.49.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.48.166 Chromium: 110.0.5481.100 (Official Build) (64-bit)
-- | --
Revision | `4be7a36f7cb943af6118e449bbab494b43dcaddd-refs/branch-heads/5481_77@{#14}`
OS | Windows 11 Version 22H2 (Build 22621.1265)

- Verified steps from [brave/brave-core#17101](https://github.com/brave/brave-core/pull/17101)
- Verified USDT/USDC tokens are listed as Swappable tokens

https://user-images.githubusercontent.com/17010094/219598498-9f1b7fee-e9be-4d85-86ba-234cc92f7ae0.mp4
