### ISSUE TITLE
Solana Send transactions doesn't show receiving address

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#28039]
## Description 

Solana Send transactions doesn't show receiving address

## Steps to Reproduce

   1. Submit a send transaction on Solana
   2. Open panel and navigate to Transaction history
   3. Receiving address is shown as `***` and actual address is not shown

## Actual result:

Panel | Token Transaction
-- | --
![image](https://user-images.githubusercontent.com/17010094/214624132-6c920807-cfd2-47ee-8fa3-4931a65b5f03.png) | ![image](https://user-images.githubusercontent.com/17010094/214624679-41dc5a2b-1574-4478-9052-a23c30885d3d.png)

## Expected result:
Should show the receiving address

## Brave version (brave://version info)

All

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel @josheleonard @onyb

**Comment by josheleonard** [comment]
regression was caused by:
https://github.com/brave/brave-core/pull/15891/files#diff-db0841fffaec0c55469ca8bec60514e543e426e12ab0b47df32b96fba0d7af68R178

**Comment by kjozwiak** [comment]
The above will require `1.48.157` or higher for `1.48.x` verification 👍
