### ISSUE TITLE
Brave does not play videos at utreon.com

### ISSUE THREAD

**Issue by LukasHirt** [brave/brave-browser#28030]
## Description 

Trying to watch videos on [utreon.com](https://utreon.com/) does not play the video in the video player. Looking into the devtools, the src of the video tag is empty. I have made no changes to the shield settings. Disabling the shield solves this issue but that is not really a solution.

## Steps to Reproduce

   1. Open [utreon.com](https://utreon.com/)
   2. Open a video

## Actual result:

Video element shows the poster but removes the src from the video.

![image](https://user-images.githubusercontent.com/25989331/214576375-c529ac3e-4a88-4a57-a889-8b79aa856015.png)

## Expected result:
Video src stays there and I can play it.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave: **1.46.140 Chromium: 108.0.5359.99**
Version: **410951fc34bb4b2cbf182231f9f779efaafaf682-refs/branch-heads/5359_71@{#9}**
OS: **macOS 13.1**

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? yes
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? no

## Miscellaneous Information:

Running the website on localhost with the same data/endpoints work. This issue is reported by users on various devices.

**Comment by ebrawer** [comment]
<img width="503" alt="image" src="https://user-images.githubusercontent.com/19806310/214580894-ac74964d-dfc8-4902-a1f9-bd73fbe97201.png">

> Does the issue resolve itself when disabling Brave Shields? yes

Ok ads are doing this...

Seems Shields is aggressive: https://community.brave.com/t/brave-sheild-breaks-sites-even-when-all-the-settings-are-turned-off/429151

We can either disable ads on Brave, or have a message telling them to disable Brave Shields on Utreon.

**Comment by ebrawer** [comment]
<img width="1232" alt="image" src="https://user-images.githubusercontent.com/19806310/214582575-70f344e4-44d2-4e1d-83e4-9db9f4fea902.png">

I take shields down, and it works.

**Comment by ebrawer** [comment]
<img width="282" alt="image" src="https://user-images.githubusercontent.com/19806310/214582893-533231df-b53c-4a5d-8a61-286856d6483a.png">

<img width="400" alt="image" src="https://user-images.githubusercontent.com/19806310/214582927-4570da30-5373-4bd3-8019-d3381ab17100.png">

...

**Comment by ryanbr** [comment]
@LukasHirt Sorry for the delay, is this still an issue? I checked the site. No issues with video playback here

**Comment by LukasHirt** [comment]
> Sorry for the delay, is this still an issue? I checked the site. No issues with video playback here

Thanks for looking into it! The issue seems to be gone now. There were some PRs related to the same with adblockers (ublock and adblocker). Maybe that has some effect on brave as well?
