### ISSUE TITLE
Auto Contribution still occurs when Rewards or A-C are toggled off

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#2804]
## Description 
If you turn off Rewards via the toggle at the top of brave://rewards page, Auto-Contribute can still occur if the A-C table has sites in it. When Rewards are turned off, auto contribution should not happen. Additionally, if I toggle A-C off but leave Rewards on, auto contribute still occurs when sites are listed in the table. If the table is blank, I'm not seeing contribution happen.

## Steps to Reproduce

   1. Launch Brave with a fresh profile and `--rewards=reconcile-interval=15`(or a shorter amount of minutes if you can work quickly)
   2. Enable Rewards
   3. Fund your wallet, verify amount displays in browser.
   4. Visit some sites to populate a-c table
   5. Turn off Rewards with toggle at the top of brave://rewards page (or toggle A-C off in the pane)
   6. Wait until the reconcile-interval time is met.

## Actual result:
Even though Rewards switch is turned off, Auto Contribute still occurs (at about 1:07ish in this clip you'll see the wallet balance go down 20 BAT, the monthly budget for auto contribute):
![contrib-rewardsoff](https://user-images.githubusercontent.com/28145373/50646378-e292ae80-0f43-11e9-99f3-91ba5576d6e3.gif)

## Expected result:
Rewards is off, Auto Contribute should not happen.

## Reproduces how often: 
Easily

## Brave version (brave://version info)

Brave | 0.59.14 Chromium: 72.0.3626.28 (Official Build) beta(64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? reproduced on beta

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
Originally reported in community https://community.brave.com/t/auto-contribute-gets-triggered-even-when-brave-rewards-is-disabled/40255/6

cc @mandar-brave @rebron @brave/legacy_qa 

Note - If I explicitly toggle Auto Contribute off before toggling Brave Rewards off (in between steps 4 and 5 above), this still occurs.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.58.20 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Windows 7

Used STR from OP. 
Tested with rewards off and ac off.
Made sure that after rewards were reenabled, the contribution went through.
Noticed that ac table was not cleared when rewards were off.
