### ISSUE TITLE
Manual test run on Windows for 1.49.x - Nightly (Checking C110)

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#28042]
The following basically checks and ensures that you cannot install the latest Nightly that includes `C110` on older `Windows` versions as 1.47.x with `C109` is the last supported version for Win 7 and 8.1. For reference, see https://github.com/brave/brave-browser/issues/27790.

* [ ] Windows 7 x64
* [ ] Windows 7 x86
* [ ] Windows 8.1 x64
* [ ] Windows 8.1 x86

**Comment by btlechowski** [comment]
I was able to install Windows 7 x64 https://github.com/brave/brave-browser/issues/28045

**Comment by kjozwiak** [comment]
> I was able to install Windows 7 x64 #28045

Basically got the same thing as you as per https://github.com/brave/brave-browser/issues/28045#issuecomment-1404698633. Going to close this off as completed and we'll address the issues we've found via the issue mentioned above.

**Comment by btlechowski** [comment]
Stub installers install c109 despite c110 being offered:

Windows 7 x64 https://github.com/brave/brave-browser/issues/28045#issuecomment-1406636414
Windows 7 x86 https://github.com/brave/brave-browser/issues/28045#issuecomment-1406766629
