### ISSUE TITLE
EIP712Domain data should be displayed

### ISSUE THREAD

**Issue by kdenhartog** [brave/brave-browser#28048]
see https://hackerone.com/reports/1847102

**Comment by kjozwiak** [comment]
@srirambv created https://github.com/brave/internal/issues/995 for verification purposes as the above is a HacerOne report.

**Comment by kjozwiak** [comment]
The above requires `1.48.156` or higher for `1.48.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.48.157 Chromium: 110.0.5481.77 (Official Build) (64-bit)
-- | --
Revision | `65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}`
OS | Windows 11 Version 22H2 (Build 22621.1105)

- Verified domain info is shown on signing messages for v3/v4 messages

Personal Sign | Sing Type v3 | Sign Type v4
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/216963919-f7ee6dcf-ebdd-478e-ba09-5d2fd45751a4.png) | ![image](https://user-images.githubusercontent.com/17010094/216963971-9e36bad2-4bc8-49dd-9cf7-c5e2e26d42c8.png) | ![image](https://user-images.githubusercontent.com/17010094/216964016-e59c5a42-0462-4ef4-bede-d3876a461c8a.png)

-----------------

Verification passed on Oppo Reno 5 with Android 13 running 1.48.157 x64 build
- Verified domain info is shown on signing message for v3/v4 messages

https://user-images.githubusercontent.com/17010094/216964434-484c2504-ce5b-4e90-bb7f-5df82ad6e8c1.mp4
