### ISSUE TITLE
Update message when there is no FIL token linked to a domain address

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#28041]
## Description 

Update message when there is no FIL token linked to a domain address

## Steps to Reproduce

   1. Select FIL in send token
   2. Type in `brave-qa.crypto` which is a valid domain name 
   3. Shows `Domain is not registered`

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/214643065-9003c5f2-0a93-4870-98d7-e4de74604c0d.png)

## Expected result:
Error should probably say `Domain doesn't have a linked FIL address` cc: @rmcfadden3 for correct wording

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.48.139 Chromium: 109.0.5414.87 (Official Build) beta (64-bit)
-- | --
Revision | `2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}`
OS | Windows 11 Version 22H2 (Build 22621.755)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @yrliou @supermassive @rmcfadden3

**Comment by rmcfadden3** [comment]
@srirambv — this one is out of my area of expertise, but on the surface your copy string looks fine to me!

**Comment by minkyeongshin** [comment]
Here's the updated design.
https://www.figma.com/file/SeRk6BLWnaqK8PQbayXWnx/Send?node-id=1881%3A108479&t=5IoYnr7JdEVzFDZn-1

<img width="505" alt="Screen Shot 2023-02-01 at 10 52 24" src="https://user-images.githubusercontent.com/86380734/216136029-1ee400fb-84db-496d-87d8-6669194e56b0.png">

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.50.93 Chromium: 111.0.5563.64 (Official Build) beta  (64-bit) 
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Linux

- Verified steps from [brave/brave-core#17003](https://github.com/brave/brave-core/pull/17003)
- Verified for `EVM` token, entering `test.crypto` shows message `Domain doesn't have a linked ETH address`
- Verified for `Solana` token, entering `test.crypto` shows message `Domain doesn't have a linked SOL address`
- Verified for `Filecoin` token, entering `test.crypto` shows message `Domain doesn't have a linked FIL address`

https://user-images.githubusercontent.com/17010094/225873385-b58a010b-b967-447d-b424-e4214ecf9845.mp4

---------------------

Verification passed on 

Brave | 1.50.93 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from [brave/brave-core#17003](https://github.com/brave/brave-core/pull/17003)
- Verified for `EVM` token, entering `test.crypto` shows message `Domain doesn't have a linked ETH address`
- Verified for `Solana` token, entering `test.crypto` shows message `Domain doesn't have a linked SOL address`
- Verified for `Filecoin` token, entering `test.crypto` shows message `Domain doesn't have a linked FIL address`

https://user-images.githubusercontent.com/17010094/225873200-3915d519-76b6-42ac-8404-3ed18efbe3f0.mp4

---------------------

Verification passed on 

Brave | 1.50.93 Chromium: 111.0.5563.64 (Official Build) beta (arm64)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#17003](https://github.com/brave/brave-core/pull/17003)
- Verified for `EVM` token, entering `test.crypto` shows message `Domain doesn't have a linked ETH address`
- Verified for `Solana` token, entering `test.crypto` shows message `Domain doesn't have a linked SOL address`
- Verified for `Filecoin` token, entering `test.crypto` shows message `Domain doesn't have a linked FIL address`

https://user-images.githubusercontent.com/17010094/225873664-445a320d-285b-4458-985b-f042f34a5df4.mov
