### ISSUE TITLE
Windows 10 on-boarding showing bogus Chromium-based browser in import step

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#28053]
This is from a fresh Windows 10 installation (in a VM). I don't have a browser installed other than Edge, yet after downloading Brave, I'm presented with two choices for importing my profile:
![Screenshot from 2023-01-25 15-18-32](https://user-images.githubusercontent.com/167821/214714950-314c56b1-f2a2-4e9f-872f-53c0d1c3ca47.png)

Is this "Chromium-based browser" another way to import the Edge settings? If so, maybe we should not include it.

Also, why is the icon missing?

**Comment by stephendonner** [comment]
@fmarier dupe of https://github.com/brave/brave-browser/issues/27557 I think.

**Comment by fmarier** [comment]
@stephendonner That other bug looks like it needs Brave Nightly to be installed along with Edge, no? In my case, I only had a single browser installed (Edge) before installing Brave release, and so I was expecting to see only one entry in the import list.

**Comment by rebron** [comment]
@fmarier Still might be a dupe of #27557. The missing one seems to be Internet Explorer and mislabeled as chromium-based. Fix is in latest nightly https://github.com/brave/brave-core/pull/16800 and looking to uplift into 1.48.x

**Comment by fmarier** [comment]
Ah, I see. I totally forgot about IE 11 :)

**Comment by stephendonner** [comment]
> Ah, I see. I totally forgot about IE 11 :)

Everybody else, too ;-)
