### ISSUE TITLE
1password does not insert fields

### ISSUE THREAD

**Issue by vkuznet** [brave/brave-browser#2805]
## Description 

I'm trying to use 1password with Brave browser but it does not really work. It does not insert my login/password fields in a browser. I can open 1password with option+command+\ options, but then I prompted with option to search rather than having with proper option ready. If I search for my tag and click on fill in 1password nothing really happens in a browser. I used 1password 6 as well as 1password 7 versions and behavior is the same.

## Steps to Reproduce

   1. go to site of interest
   2. invoke 1password extension, it will bring the pop-up window with all stored entries
   3. search for required site entry in 1password
   4. click on Fill

## Actual result:

nothing really is filled in neither in login or password fields of the browser.

## Expected result:
In other browsers (Chrome or Firefox) everything is working as expected, i.e. 1password extension is filled in proper fields in a browser.

## Reproduces how often: 

All the time regardless of site I visit.

## Brave version (brave://version info)

Version 0.58.18 Chromium: 71.0.3578.98 (Official Build) (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Is this on Windows/Mac/Linux?

**Comment by vkuznet** [comment]
Mac, osx 10.14.2

**Comment by vkuznet** [comment]
is there any news on this?

**Comment by remotealex** [comment]
@vkuznet I spoke with support and if it's the same issue I was having, it's a problem with versioning and hard-coded strings. I've now upgraded to the new subscription-based 1Password and their browser plugins work again.

**Comment by tomlowenthal** [comment]
Initial post says that behavior is the same with 1Password 6 and 7, so the hard-coded browser list isn't the issue.

@brave/legacy_qa — could you try to repro this? I can't.

**Comment by remotealex** [comment]
@tomlowenthal Oops! Apologies.

**Comment by vkuznet** [comment]
I do not use subscription-based 1Password, I have stand-alone version (the app).

**Comment by vkuznet** [comment]
I'll be happy to help if you'll give me some directions.

**Comment by dakotahp** [comment]
I have had the same problem ever since the new version of Brave came out and have stopped using it as my primary browser as a result. I even just changed 1Password from the Mac App Store version to the version directly from their website to be sure but it still doesn't work, even after a reboot.

I don't know what else to try.

**1Password 7**
Version 7.2.4 (70204000)
AgileBits Store

**Brave**
Version 0.59.34 Chromium: 72.0.3626.81 (Official Build) (64-bit)

**Mac OS**
10.14.2 (18C54)

**Comment by vkuznet** [comment]
Here is mine with 1Password 6 app
![screen shot 2019-02-01 at feb 1 12 20 05 pm](https://user-images.githubusercontent.com/125138/52138706-efc2bc00-261b-11e9-977e-711593c06bfa.png)

The only way I can use it on a site is to type my pattern in search field and then manually copy my attributes. The autocompletion does not work, if I click it on selected item it redirect to stored URL and does not fill any fields in it.

**Comment by tomlowenthal** [comment]
@vkuznet 1Password 6 is never going to work. There's nothing we can do about that — 1Password won't budge on it.

@dakotahp Have you installed the 1Password extension in Brave?

**Comment by dakotahp** [comment]
@tomlowenthal Following the button in that UI I posted goes [here](https://1password.com/downloads/mac/#browsers) which has no such extension. These are the options:

![image](https://user-images.githubusercontent.com/387930/52153656-b5fbb080-262f-11e9-9a8a-18fd15a87c4b.png)

Unless of course I'm supposed to assume that the Chrome extension works in Brave now that you've switched engines.

**Comment by tomlowenthal** [comment]
Yep, the Chrome extension is the one you want.

**Comment by tomlowenthal** [comment]
@dakotahp Yep, the Chrome extension is the one you want.

**Comment by dakotahp** [comment]
@tomlowenthal That's not intuitive at all despite knowing that you switched to the Chrome engine and the fact that it was native in the prior version. Anyway, thanks for the help! 👍🏼

@vkuznet Sorry for hijacking your issue, you mentioned 1Password 7 which I also had a problem with.

**Comment by tomlowenthal** [comment]
@vkuznet Does this issue still exist with 1Password 7, when you have the extension installed?
@brave/legacy_qa Can you also try to repro?

**Comment by vkuznet** [comment]
I installed 1password BETA and 1password extension for Chrome. In my case, I don't have full license since my 1password 6 license is not applicable, the behavior was the same, i.e. I get pop-up window where I can search for site credentials, but they are not visible by default and neither filled properly. When I click on open and fill I get back 1password winder and nothing happens in a browser.

**Comment by tomlowenthal** [comment]
@vkuznet Does that setup work in Chrome?

**Comment by Jacob-JA-Shanks** [comment]
Still having this issue on Windows 10 (v1803) using Brave Version 0.60.47 Chromium: 72.0.3626.119 (Official Build) (64-bit).

Using the Ctrl+\ shortcut followed by enter as well as using the context menu shortcut or the extension icon don't insert into fields.

**Comment by uatec** [comment]
Why not?

**Comment by uatec** [comment]
> @vkuznet 1Password 6 is never going to work. There's nothing we can do about that — 1Password won't budge on it.

Why not?

**Comment by bsclifton** [comment]
@uatec 1Password 6 has a list compiled into it of browser signatures to recognize. Unfortunately, they don't have this newer version of Brave (I believe they do have the older "Muon" version added, but we are not using the same signature)

The only way that 1Password 6 could work would be if AgileBits released a new version of v6, which I believe they have confirmed that they won't on their message boards. More details here:
- https://discussions.agilebits.com/discussion/97296/1password-6-for-mac-incompatible-with-new-brave-browser-releases/p2
- https://discussions.agilebits.com/discussion/97296/1password-6-for-mac-incompatible-with-brave-browser/
- https://discussions.agilebits.com/discussion/101686/any-plans-to-support-brave-browser
- https://discussions.agilebits.com/discussion/99507/the-latest-version-of-brave-requires-1password-7

**Comment by cyberwombat** [comment]
I have v7 and the same issues so this is still going on.
