### ISSUE TITLE
Update Send V2 Account Selector

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#28069]
## Description 
We need to update the `Send V2` Account Selector to match the updated changes in Figma.

![Screenshot 2023-01-26 at 9 07 56 AM](https://user-images.githubusercontent.com/40611140/214872008-112c8320-8b74-4469-b645-3ad2fbe856bd.png)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta  (64-bit) 
-- | --
Revision | `46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}`
OS | Linux

- Verified steps from [brave/brave-core#16876](https://github.com/brave/brave-core/pull/16876)
- Verified account selector shows `Orb`, `Name` and `Address` is in a single row
- Verified sending account address is disabled

https://user-images.githubusercontent.com/17010094/221864034-9a070fe9-a73f-45f5-911e-8e521964e674.mp4

---------------------

Verification passed on 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta  (64-bit)
-- | --
Revision | `46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#16876](https://github.com/brave/brave-core/pull/16876)
- Verified account selector shows `Orb`, `Name` and `Address` is in a single row
- Verified sending account address is disabled

https://user-images.githubusercontent.com/17010094/221863399-e9871686-cfb9-4140-8db7-9367a4217808.mp4

---------------------

Verification passed on 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta  (arm64)
-- | --
Revision | `46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#16876](https://github.com/brave/brave-core/pull/16876)
- Verified account selector shows `Orb`, `Name` and `Address` is in a single row
- Verified sending account address is disabled

https://user-images.githubusercontent.com/17010094/221866499-eda1271f-cfb1-4bee-9375-a82df6396136.mov
