### ISSUE TITLE
Browser crash when connecting H/W wallet for the first time

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#28061]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.49.59  Chromium: 110.0.5481.40
Operating System: Windows NT 10.0.22621

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Install 1.49.59 CR 110 build
2. Connect Ledger and try to import Ethereum account
3. Browser crashes the first time, but works subsequent attemps

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/8aeb0000-668b-8709-0000-000000000000

Also saw errors on the console when account is imported
![Screenshot 2023-01-26 060040](https://user-images.githubusercontent.com/17010094/214820748-e68ba767-150f-42aa-88ba-64fe5effaa40.png)

cc: @brave/crypto-wallets

**Comment by iefremov** [comment]
can you please re-repro @srirambv ?

**Comment by srirambv** [comment]
This is stale now. Haven't seen any crash when connecting hardware wallet for the first time. Closing as stale
