### ISSUE TITLE
Navigating to `https://brave.com/latest` shows news feed as `Brave Blog Português` 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#28064]
## Description 

Navigating to `https://brave.com/latest` shows news feed as `Brave Blog Português` 

## Steps to Reproduce

   1. Go to About Brave
   2. Click on the version number
   3. New tab loads with `https://brave.com/latest`
   4. Click on the RSS feed button, shows `Brave Blog Português` 

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/214836248-33753241-4120-43f8-9e7b-d9bce54ba1fb.png)

## Expected result:
Not sure 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.49.60 Chromium: 109.0.5414.119 (Official Build) nightly (64-bit)
-- | --
Revision | `772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}`
OS | Windows 11 Version 22H2 (Build 22621.1105)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @fallaciousreasoning @rebron @AlanBreck

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.50.45 Chromium: 110.0.5481.104 (Official Build) nightly (x86_64)
-- | --
Revision | 46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}
OS | macOS Version 11.7.4 (Build 20G1120)

Followed @srirambv 's steps to reproduce, and easily confirmed the issue and the fix.

`1.49.100` | `1.50.43` | example | example | example
---------|----------|---------|----------|----------
<img width="1637" alt="Screen Shot 2023-02-17 at 9 09 51 PM" src="https://user-images.githubusercontent.com/387249/219842049-7c7789d9-c87a-4b4b-81c2-f2edc8952361.png"> | <img width="1721" alt="Screen Shot 2023-02-17 at 9 16 17 PM" src="https://user-images.githubusercontent.com/387249/219842542-311ea909-a8ca-4868-a4b8-70eb8414bfe1.png"> | <img width="1721" alt="Screen Shot 2023-02-17 at 9 10 32 PM" src="https://user-images.githubusercontent.com/387249/219842076-99fb83b4-1c06-4870-a94f-fe209201878e.png"> | <img width="1721" alt="Screen Shot 2023-02-17 at 9 11 55 PM" src="https://user-images.githubusercontent.com/387249/219842090-06618775-3af6-46a8-9ee6-4c8a9028cae9.png"> | <img width="1721" alt="Screen Shot 2023-02-17 at 9 12 33 PM" src="https://user-images.githubusercontent.com/387249/219842096-fa7ff816-5c4f-412d-95e6-581d8035cb98.png">

**Comment by kjozwiak** [comment]
Removing the `QA Pass` label as we'll need to verify the above once again via `1.49.x`. Used the verification via https://github.com/brave/brave-browser/issues/28064#issuecomment-1435487888 for the uplift.

The above requires `1.49.126` or higher for `1.49.x` verification.

**Comment by LaurenWags** [comment]
Verified with

```
Brave | 1.49.126 Chromium: 111.0.5563.64 (Official Build) (x86_64)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | macOS Version 12.6.3 (Build 21G419)
```

Reproduced the issue using `1.49.120`.
Verified STR (note, need to enable Brave News on NTP initially), confirmed issue resolved.

1.49.120 | 1.49.126
--- | ---
<img width="1193" alt="Screen Shot 2023-03-21 at 8 07 34 AM" src="https://user-images.githubusercontent.com/28145373/226601770-3ee89dba-1509-4b2b-80ae-0de450cae238.png"> | <img width="1192" alt="Screen Shot 2023-03-21 at 8 08 10 AM" src="https://user-images.githubusercontent.com/28145373/226601773-ff9bac08-1f69-4046-a9f5-36b10a030726.png">
