### ISSUE TITLE
Use https rather than SSH git URL in wiki

### ISSUE THREAD

**Issue by DougBeney** [brave/brave-browser#2806]
Hi,

The instructions on the wiki tell the user to `git clone git@github.com:brave/brave-browser.git`. When I do that I get this error:

```
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

It works fine with an https URL instead though. 

`git clone https://github.com/brave/brave-browser.git`

Should we change that instruction in the wiki?

**Comment by srirambv** [comment]
Works just fine with `git clone` command. Do you have git installed on your machine?

**Comment by DougBeney** [comment]
Are your SSH keys authenticated with this repo? If so, maybe that's the reason.

I do have git installed.

Here is a screen recording that makes this problem clear: https://www.youtube.com/watch?v=IB7kFAltvzg&feature=youtu.be

**Comment by hamirmahal** [comment]
I run into the same issue, where `git clone git@github.com`... doesn't work, but `git clone https://github.com`... does.

```
0 ~ $ git clone git@github.com:brave/brave-core.git brave-browser/src/brave
Cloning into 'brave-browser/src/brave'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

128 ~ $ git clone https://github.com/brave/brave-core brave-browser/src/brave
Cloning into 'brave-browser/src/brave'...
remote: Enumerating objects: 1157348, done.
remote: Counting objects: 100% (5413/5413), done.
remote: Compressing objects: 100% (2267/2267), done.
remote: Total 1157348 (delta 3348), reused 4375 (delta 2953), pack-reused 1151935 (from 1)
Receiving objects: 100% (1157348/1157348), 3.08 GiB | 28.11 MiB/s, done.
Resolving deltas: 100% (851655/851655), done.
Updating files: 100% (33266/33266), done.
```
