### ISSUE TITLE
Add flag to send all history to sync

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#28062]
Related issue: https://github.com/brave/brave-browser/issues/25650

Chromium limits history sync only to typed url transitions. When user navigates through clicking the link or through the bookmarks - the history visit doesn't get synced.

We need to add the flag, which would allow sync all history. Default value - the same as in Chromium, false.

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using 

Brave | 1.50.92 Chromium: 111.0.5563.64 (Official Build) beta (x86_64)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | macOS Version 11.7.4 (Build 20G1120)

### Steps:
1. installed `1.50.92`
2. launched Brave
3. set `brave://flags/#brave-sync-send-all-history` to `Enabled`
4. clicked `Relaunch`
5. on `desktop1`, clicked on the 3-dots menu
6. clicked on `Sync`
7. clicked on `Start a New Sync Chain`
8.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.50.106 Chromium: 112.0.5615.39 (Official Build) beta (64-bit)
-- | --
Revision | a0e7b9718a92bcd1cf33b7c95316caff3fc20714-refs/branch-heads/5615@{#753}
OS | Windows 11 Version 22H2 (Build 22621.1413)
```
Pre-reqs: Generate some history thru clicking bookmarks and history - navigates through clicking the link or through the bookmarks 
<img width="779" alt="image" src="https://user-images.githubusercontent.com/98358127/228082835-308781da-b409-4c4c-ab25-16fd0e5ce6bf.png">

### Steps:
<details>

1. installed `1.50.106`
2. launched Brave
3. set `brave://flags/#brave-sync-send-all-history` to `Enabled`
4. clicked `Relaunch`
5. on `desktop1`, clicked on the 3-dots menu
6. clicked on `Sync`
7. clicked on `Start a New Sync Chain`
8. joined the Sync chain from `desktop2`
9. on `desktop1`, `desktop2`, and `android1`, enabled `History`, under `Sync data`
10. on `desktop1`, loaded `brave.com`
11. scrolled down to the footer
12. clicked on `F.A.Q.`
13. chose a question about ads, and clicked it
14. opened `brave://history` on `desktop2`
15. opened `brave://history` on `android1`
16. confirmed history was synced
17. on `desktop1`, opened `brave://bookmarks` and created an entry for `BAT`/`https://basicattentiontoken.org`
18. clicked on it
19. visited brave://history on desktop2
20. visited brave://history on android1

#### Confirmed all history was synced among the 3 devices
step 3|
<img width="454" alt="image" src="https://user-images.githubusercontent.com/98358127/228078930-1e09f848-6e2d-4a07-923a-22384811dcf6.png">
<img width="949" alt="image" src="https://user-images.githubusercontent.com/98358127/228082974-ab06d855-7267-461b-a527-cb575d1dc5af.png">
<img width="947" alt="image" src="https://user-images.githubusercontent.com/98358127/228083011-84767b15-2a45-46a4-986c-9a25db835962.png">

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Samsung Galaxy version 12` running `Bravemonoarm64.apk_1.50.108`

### Steps:

1. installed `1.50.106`
2. launched Brave
3. set `brave://flags/#brave-sync-send-all-history` to `Enabled`
4. clicked `Relaunch`
5. on `desktop1`, clicked on the 3-dots menu
6. clicked on `Sync`
7. clicked on `Start a New Sync Chain`
8. joined the Sync chain from `desktop2`
9. on `desktop1`, `desktop2`, and `android1`, enabled `History`, under `Sync data`
10. on `desktop1`, loaded `brave.com`
11. scrolled down to the footer
12. clicked on `F.A.Q.`
13. chose a question about ads, and clicked it
14. opened `brave://history` on `desktop2`
15. opened `brave://history` on `android1`
16. confirmed history was synced
17. on `desktop1`, opened `brave://bookmarks` and created an entry for `BAT`/`https://basicattentiontoken.org`
18. clicked on it
19. visited brave://history on desktop2
20. visited brave://history on android1

#### Confirmed all history was synced among the 3 devices

<details>

desktop 1:
-------
step 5| step 7|step 9|step 12|step 16 | step 17
----|----|-----|-----|----|-----


desktop 2:
------
step 9 | step 16 | step 17
----|-----|----



Android: 
----

device sync|step 9|step 15|step 20
----|----|-----|-----


</details>
