### ISSUE TITLE
Swap quotes continue to fetch even when an order is in review/submitted/executed

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#28063]
## Description 

Swap quotes continue to fetch even when an order is in review/submitted/executed

## Steps to Reproduce

   1. Initiate a Swap transaction
   2. Click on review order so panel opens up to review before submitting
   3. Keep panel open
   4. Swap keeps fetching quote irrespective of order being submitted or not

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/214833062-e4b3e98f-34b8-480f-8dc7-450e0fb8ae27.png)
![image](https://user-images.githubusercontent.com/17010094/214833073-8d0f0a91-83f6-4b32-9dfa-5be9d0cb879b.png)

## Expected result:
Clear out the fields when an order review is submitted

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.49.59 Chromium: 110.0.5481.40 (Official Build) nightly (64-bit)
-- | --
Revision | `371638c3173bebbbb05361ed503673a3aba42e61-refs/branch-heads/5481@{#395}`
OS | Linux

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @onyb @jamesmudgett @minkyeongshin

**Comment by kjozwiak** [comment]
The above requires `1.48.166` or higher for `1.48.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.48.166 Chromium: 110.0.5481.100 (Official Build) (64-bit)
-- | --
Revision | `4be7a36f7cb943af6118e449bbab494b43dcaddd-refs/branch-heads/5481_77@{#14}`
OS | Windows 11 Version 22H2 (Build 22621.1265)

- Verified steps from issue description
- Verified quotes are reset when review order is clicked and panel opens up
- Verified amount is reset when user changes the Swap From token

https://user-images.githubusercontent.com/17010094/219612419-b09c5dd8-b250-46b6-b4dc-9e1fa496d802.mp4
