### ISSUE TITLE
EventSource partitioning (for Desktop)

### ISSUE THREAD

**Issue by arthuredelstein** [brave/brave-browser#28077]
In the [pool party study](https://arxiv.org/abs/2112.06324v2), we found that EventSources can be used for cross-site tracking using a pool party attack. To protect against this, we need to limit the use of EventSources per top-level domain, similar to how @goodov did for WebSockets.

**Comment by arthuredelstein** [comment]
This issue will apply to Desktop only. The Android implementation will be deferred to #28152.

**Comment by LaurenWags** [comment]
@arthuredelstein could you please add a test plan for this one? Labelling as `QA/Blocked` for now.
