### ISSUE TITLE
Auto detect token standard when adding NFT assets

### ISSUE THREAD

**Issue by nvonpentz** [brave/brave-browser#28075]
Currently we assume everything is an ERC721.  To add frontend support for ERC1155 https://github.com/brave/brave-browser/issues/23165, we would either need to require users to input the standard themselves, or add support for auto detecting the standard.  We should auto detect token standard when adding NFT assets.

When adding an asset with is_nft=true in BraveWalletService::AddUserAsset, make a eth_call(s) to the supportsInterface function in order to check if it is an ERC721 or ERC1155.

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.51.97 Chromium: 112.0.5615.138 (Official Build) beta (64-bit)
-- | --
Revision | `2258f2fcaeb07bc95c992b7ca47f0b43ead9865c-refs/branch-heads/5615@{#1282}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from [brave/brave-core#17207](https://github.com/brave/brave-core/pull/17207)
- Verified adding `0x28472a58A490c5e09A238847F66A68a47cC76f0f` adds the token 
- Verified under `brave://pref-internals` shows ` "is_erc1155": true` ,`"is_erc20": false` and `"is_erc721": false`

https://user-images.githubusercontent.com/17010094/233970643-ab6a7d96-0690-4e00-85c9-007796c76ae9.mp4
