### ISSUE TITLE
ads history link color is different than from 1.47.x

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#28078]
## Description 

Link color in ads history is different than 1.47.x.

## Steps to Reproduce

   1. View ads so you have some ads history (any state - connected, grandfathered unverified, or unverified)
   2. Open ads history

## Actual result:

1.49.x:

<img width="957" alt="history 1 49 x" src="https://user-images.githubusercontent.com/28145373/214939977-d915b713-882f-4eed-808d-c85c531d4326.png">

## Expected result:

1.47.x:

<img width="1287" alt="history 1 47 x" src="https://user-images.githubusercontent.com/28145373/214940015-7e407e71-47de-4fc1-a554-446e4bc600af.png">

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.49.62 Chromium: 109.0.5414.119 (Official Build) nightly (x86_64)

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @Miyayes

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.51.79 Chromium: 112.0.5615.49 (Official Build) beta (64-bit)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Windows 10 Version 21H2 (Build 19044.2728)
```
- Verified the STR from the description and ensured that the ads history link color is as expected
![image](https://user-images.githubusercontent.com/38657976/230363036-f194f1b8-f74d-4fc8-acff-d3e62b8d2bee.png)
