### ISSUE TITLE
Left margin for top sites is misaligned

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#28071]
## Description 

On the new tab page, top sites left margin is incorrect and does not have padding. See screenshots in actual and expected result.

## Steps to Reproduce

   1. Use 1.47.186 or later.
   2. Open new tab page.
   3. Visit some sites so frequently visited sites show or add sites to the top sites widget. Hover over top sites kebab menu. Notice left margin and no padding.

## Actual result:

<img width="801" alt="image" src="https://user-images.githubusercontent.com/5951041/214887469-7b2c4490-b4d2-4b59-8e95-92799ea58ba8.png">

## Expected result:
<img width="600" alt="Screenshot 2023-01-20 at 9 37 26 AM" src="https://user-images.githubusercontent.com/5951041/214887678-d1af0369-5676-416f-af22-af9d8b19c1f2.png">

## Reproduces how often: 

Easily.

## Brave version (brave://version info)

1.47.186

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by kjozwiak** [comment]
The above requires `1.48.164` or higher for `1.48.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.48.165 Chromium: 110.0.5481.100 (Official Build) (x86_64)
-- | --
Revision | 4be7a36f7cb943af6118e449bbab494b43dcaddd-refs/branch-heads/5481_77@{#14}
OS | macOS Version 12.6.3 (Build 21G419)
```
