### ISSUE TITLE
Add NFT pinning feature flag

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#28073]

**Comment by kjozwiak** [comment]
@cypt4 going to close this as it was opened ~a month ago and looks like it has a PR associated with it that's in `1.49.x` as per https://github.com/brave/brave-core/pull/16878. It's labelled as `QA/No` so it shouldn't affect QA. Assuming this was re-opened for https://github.com/brave/brave-core/pull/16962? However, that PR is associated with https://github.com/brave/brave-browser/issues/28233 which is in `1.50.x`. Either way, let me know if this needs any other follow-ups from a QA perspective. CCing @srirambv @yrliou
