### ISSUE TITLE
[hackerone] always show both file dialogs on windows

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#28079]
see https://bravesoftware.slack.com/archives/C7VLGSR55/p1674762134098869?thread_ts=1674760928.540849&cid=C7VLGSR55 for details

original hackerone issue: https://hackerone.com/reports/1848062 (credit [ameenbasha](https://hackerone.com/ameenbasha))

**Comment by diracdeltas** [comment]
upstream issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1410578. i'm asking if they would fix it.

**Comment by mkarolin** [comment]
**QA Steps:**
1. Download the file attached to the above mentioned Slack thread.
2. Open the file in Brave
3. Once the file is loaded you will be prompted to pick download saving location. Click Save.
4. Download shelf will appear with the download progress.

Expected result:
Once the file finished downloading you should see a warning in the download shelf informing you that the file may be dangerous. You should see 2 buttons: Keep and Discard.

5. Click on the Discard button. 
6. Verify that the file has not been saved in the location selected in step 3.
7. Click on Reload tab button.
8. Repeat steps 3 and 4.
9. This time click on Keep button. Verify that the file has been saved in the location selected in step 3.

10. Navigate to brave://settings/downloads and toggle the "Ask where to save..." to off
11. Repeat steps 2-4 and verify the expected result.

12. Navigate to brave://settings/downloads and toggle the "Ask where to save..." back to on

**Test that extensions can be manually installed without a warning.**
1. Obtain a packed extension file (.crx). For example, in a different instance of Brave or in Chrome install an extension, then navigate to chrome://extensions. Turn on developer mode and then select pack extension. In the presented dialog specify the extension path (e.g. on Windows c:\Users\<yourusername>\AppData\Local\Google\Chrome\User Data\Default\Extensions\\<extension_id>\\<extension_version>), leave Private Key blank. The packed extension will be saved in the extension path (minus the version) that you specified.
2. Open Brave and navigate to brave://extensions
3. Turn on developer mode
4. Drag the .crx file from step 1 onto the page

Expected result:
There is no download shelf showing a warning about the file being dangerous.

**Comment by kjozwiak** [comment]
@brave/qa-team can find examples/template that can be used via https://github.com/brave/brave-core/pull/16969#issuecomment-1432188438.

**Comment by kjozwiak** [comment]
The above requires `1.48.164` or higher for `1.48.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using 
```
Brave | 1.48.165 Chromium: 110.0.5481.100 (Official Build) (64-bit)
-- | --
Revision | 4be7a36f7cb943af6118e449bbab494b43dcaddd-refs/branch-heads/5481_77@{#14}
OS | Windows 11 Version 21H2 (Build 22000.1574)
```

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.48.165 Chromium: 110.0.5481.100 (Official Build) (x86_64)
-- | --
Revision | 4be7a36f7cb943af6118e449bbab494b43dcaddd-refs/branch-heads/5481_77@{#14}
OS | macOS Version 12.6.3 (Build 21G419)
```
