### ISSUE TITLE
IPFS is initializing daemon without interaction from user

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#28076]
## Description 

On a fresh Nightly profile with 1.49.62, IPFS is initializing a daemon (in my terminal) without any interaction from me. 

This is not occurring on 1.49.60 for me or @srirambv. I think this could be related to https://github.com/brave/brave-browser/issues/19283 which landed after 1.49.60.

## Steps to Reproduce

   1. Clean profile on 1.49.62 (I launched via terminal with `--args --enable-logging=stderr`)
   2. Close and relaunch via terminal again to pull griffin seed.
   3. Wait 1-2 minutes and watch terminal. (usually happens for me after ~1min 15 s)
   4. After you see the messages below, visit brave://ipfs-internals and see that the node is started.

## Actual result:

```
initializing IPFS node at /Users/laurenwags/Library/Application Support/BraveSoftware/Brave-Browser-Nightly/brave_ipfs
to get started, enter:

	ipfs cat /ipfs/QmQPeNsJPyVWPFDVHb77w8G42Fvo15z4bG2X8D2GhfbSXc/readme

Error: daemon not running
Initializing daemon...
Kubo version: 0.17.0
Repo version: 12
System version: amd64/darwin
Golang version: go1.19.1
............
etc
............
WebUI: http://127.0.0.1:45002/webui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/48081
Daemon is ready
```

<img width="492" alt="Screen Shot 2023-01-26 at 2 31 03 PM" src="https://user-images.githubusercontent.com/28145373/214932059-79c84b06-5581-4b5b-8390-f4fd93c4a40b.png">

## Expected result:

IPFS should not be intialized in terminal without any interaction from user

<img width="458" alt="Screen Shot 2023-01-26 at 2 32 28 PM" src="https://user-images.githubusercontent.com/28145373/214932306-c8ad6d54-5739-42e9-84c6-16f2f5e6bcef.png">

## Reproduces how often: 

easily

## Brave version (brave://version info)

```
Brave | 1.49.62 Chromium: 109.0.5414.119 (Official Build) nightly (x86_64)
-- | --
Revision | 772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}
OS | macOS Version 12.6.3 (Build 21G419)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the nightly channel? yes, 1.49.62

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @cypt4

**Comment by srirambv** [comment]
Verification passed on <html>
<body>


Brave | 1.49.91 Chromium: 110.0.5481.77 (Official Build) beta (64-bit)
-- | --
Revision | `65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}`
OS | Windows 11 Version 22H2 (Build 22621.1105)


</body>
</html>

- Verified steps from issue description
- Verified IPFS doesn't initialize until manually done on a clean profile

https://user-images.githubusercontent.com/17010094/218741693-a351d19b-6183-4613-8085-c6328b3f3a1e.mp4
