### ISSUE TITLE
On demand loading wallet-standard

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#28082]
follow-up of https://github.com/brave/brave-core/pull/16868

With the bandaid PR we trade off the ability to prompt users to setup solana wallet if they haven’t when dapp interact with our provider only through `wallet-standard`. We should try to intercept call from dapps and load `wallet-standard` and register our wallet at that point. And we can also try to pass our safe solana web3 from v8 to wallet-standard so we can have only one `@solana/web3.js` loaded instead of our secure minified one plus vanilla one used by `wallet-standard`

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.50.94 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from [brave/brave-core#17005](https://github.com/brave/brave-core/pull/17005)
- Verified when Wallet isn't setup, selecting Brave Wallet in connect window opens a new tab and loads the onboarding page
- Verified with wallet created, able to submit `SignTransaction`, `SignMessage` and `SendTransaction`

https://user-images.githubusercontent.com/17010094/226534053-a004f491-624a-4745-b3aa-6d435e91bbba.mp4
