### ISSUE TITLE
brave:// internal URLs get copy-pasted as chrome:// URLs if you cmd+c/v

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#28083]
## Description 

brave:// internal URLs get copy-pasted as chrome:// URLs if you cmd+c/v, not sure if this was always the case but seems wrong. 

## Steps to Reproduce

   1. Go to brave://settings
   2. Cmd+C on the omnibox and then Cmd+V somewhere

## Actual result:

You get chrome://settings

## Expected result:
brave://settings

## Reproduces how often: 

Easily. Note that right-clicking and copy pasting seems to work fine (but who does that). 

## Brave version (brave://version info)

MacOS, Nightly. Works fine on Stable.

**Comment by rebron** [comment]
Reproducible on 1.49.62 but looks ok in 1.48.x
cc: @emerick

**Comment by rebron** [comment]
dupe of https://github.com/brave/brave-browser/issues/28588?
