### ISSUE TITLE
[Linux] Sound defaults to the wrong device

### ISSUE THREAD

**Issue by jgedri** [brave/brave-browser#2808]
PLEASE USE THE TEMPLATE BELOW TO PROVIDE INFORMATION ABOUT THE ISSUE. 
INSUFFICIENT INFO WILL GET THE ISSUE CLOSED. IT WILL ONLY BE REOPENED AFTER SUFFICIENT INFO IS PROVIDED-->

## Description 

Videos play silently because the wrong output is selected.

## Steps to Reproduce

   1. Play a video.
   2. Start pavucontrol.
   3. Select the right output device.

## Actual result:

Videos play without sound.

## Expected result:
Videos should play with sound.

## Reproduces how often: 

easily reproducible

## Brave version (brave://version info)

Brave v. 0.25.2
rev. 8ea2a
OS: Linux (Debian 9)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 
Chromium automatically selects the right device.
### Additional Information

I'm running Debian "stretch" on a custom-built desktop PC. There are two output devices; the one I use is an Nvidia GM204 audio controller.

**Comment by srirambv** [comment]
You are running the deprecated version of Brave. Please install the new version (0.58.16). You can follow the instructions from [here](https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux)
