### ISSUE TITLE
[Android] panel and brave://rewards have different UI in the "Logged out" state - follow up to 20450

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#28096]
## Description 
Follow up to https://github.com/brave/brave-browser/issues/20450

The panel and brave://rewards page have different UI in "Logged out" state on Android. These two areas match on desktop. Android brave://rewards page matches desktop behavior. The panel is what is inconsistent.

The panel does not show the blue box which says "Log in to [custodian] to see your balance", the panel shows 0.00 balance instead. This is inconsistent with both the brave://rewards page on Android as well as the Desktop implementation.

## Steps to reproduce 

1. Clean install
2. Navigate QA Preferences
3. Enable staging environment, relaunch as necessary
4. Enable Rewards
5. Select Verify Wallet and login with custodial account
6. Confirm balance is shown in UI
7. On custodial site, revoke access to Brave Browser (where applicable)
8. Compare UI on panel and rewards page.

## Actual result 

Panel is missing the blue box and shows 0.00 balance instead:

![1-a](https://user-images.githubusercontent.com/28145373/215127274-023d65fb-c3d6-4f2d-bd3e-018b4ed978f2.png)

## Expected result

should match android brave://rewards page and desktop panel & brave://rewards page:

Android brave://rewards | Desktop Panel | Desktop brave://rewards
---- | ---- | ----
![1-c](https://user-images.githubusercontent.com/28145373/215127472-3d0dd960-ffa6-4c22-bdd8-af1d12bf98dc.png) | <img width="1402" alt="2-a" src="https://user-images.githubusercontent.com/28145373/215127474-e6b4f83f-a29f-45b8-bb56-34101987b9d8.png"> | <img width="1405" alt="2-c" src="https://user-images.githubusercontent.com/28145373/215127476-f755379b-fab5-48e4-9f24-7087ac52d2ae.png">

## Issue reproduces how often 

easily 
## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? n/a
- Can you reproduce this issue with the current Play Store Beta version? yes
- Can you reproduce this issue with the current Play Store Nightly version?yes

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
1.48.141

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc @Miyayes @deeppandya

**Comment by Miyayes** [comment]
## Solution

Match with https://github.com/brave/brave-browser/issues/20991 (desktop).

Figma: https://www.figma.com/file/XnadxdmrOHHPYRCdHFD91b/Rewards-Settings?node-id=1113%3A42664&t=Y73BRFlHPsGqW3aV-0 @deeppandya @sujitacharya2005

**Comment by kjozwiak** [comment]
The above requires `1.49.91` or higher for `1.49.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Samsung Galaxy version 12` running `Bravemonoarm64.apk_1.49.116`

- Verified the STR from the description and ensured that the "Logged out" UI is shown corectly on brave://rewards settings page, BR panel and pubs panel.

Example | Example | Example
----------|----------|-----------
![Screenshot_20230303-135508_Brave - Beta](https://user-images.githubusercontent.com/38657976/222670472-44f8eec4-f55b-44c8-bda0-6beb322473c8.jpg) | ![Screenshot_20230303-135521_Brave - Beta](https://user-images.githubusercontent.com/38657976/222670478-b1254a25-d0cf-4eb6-b3a1-94a8ed65b738.jpg) | ![Screenshot_20230303-135538_Brave - Beta](https://user-images.githubusercontent.com/38657976/222670483-967cc850-739b-485b-8335-deed319e8a38.jpg)
