### ISSUE TITLE
[Android] panel and brave://rewards have different functionality in the "Logged out" state - follow up to 20450

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#28097]
## Description 
Follow up to https://github.com/brave/brave-browser/issues/20450

The panel and brave://rewards page behave differently in "Logged out" state on Android. These two areas match on desktop. Android brave://rewards page matches desktop behavior. The panel is what is inconsistent.

When you tap on "Logged out" from the panel, you are taken to brave://rewards/#verify. You should get a dropdown like you do on brave://rewards page which offers "Log in to your Uphold account". The way the panel is behaving is acting like you've never had a custodian connected. This clashes with the removal of the "Disconnect" functionality as part of the updated rewards states (https://github.com/brave/brave-browser/issues/27055 on Android).

## Steps to reproduce 

1. Clean install
2. Navigate QA Preferences
3. Enable staging environment, relaunch as necessary
4. Enable Rewards
5. Select Verify Wallet and login with custodial account
6. Confirm balance is shown in UI
7. On custodial site, revoke access to Brave Browser (where applicable)
8. Open the panel, tap on "Logged out" --> you are directed to brave://rewards/#verify which looks like you've never connected a custodian which is incorrect 
9. Close this page
10. Navigate to brave://rewards
11. Tap on "Logged out"
12. A drop down opens with a link to log in to custodial site --> this is correct behavior

## Actual result 

Tapping on "Logged out" from panel directs user to brave://rewards/#verify:

![1-b](https://user-images.githubusercontent.com/28145373/215128881-4493f8fa-97e8-480b-83bd-74692d21e1eb.png)

## Expected result

Tapping on "Logged out" should open a drop down with a link to log in to custodial site as it does on Android brave://rewards page and Desktop panel and brave://rewards page

Android brave://rewards | Desktop Panel | Desktop brave://rewards
---- | ---- | ----
![1-d](https://user-images.githubusercontent.com/28145373/215128839-48ddcf74-af6e-4015-bfd6-e18d24203206.png) | <img width="1402" alt="2-b" src="https://user-images.githubusercontent.com/28145373/215128842-d7a34392-2b77-4d44-a8e5-029418c6ef31.png"> | <img width="1406" alt="2-d" src="https://user-images.githubusercontent.com/28145373/215128843-f720966f-49b8-4141-b5d7-0bd3b800940a.png">

## Issue reproduces how often 

easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? n/a
- Can you reproduce this issue with the current Play Store Beta version? yes
- Can you reproduce this issue with the current Play Store Nightly version?yes

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
1.48.141

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc @Miyayes @deeppandya

**Comment by kjozwiak** [comment]
The above requires `1.48.157` or higher for `1.48.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version:

```
Brave	1.48.157 Chromium: 110.0.5481.77 (Official Build) (64-bit) 
Revision	65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS	Android 13; Build/TP1A.220624.014
```

Based on the STR in https://github.com/brave/brave-browser/issues/28097#issue-1559989586

- Ensured user is able to log into custodial page, `Connected` is displayed in brave://rewards, rewards panel.
- Ensured revoking access on the custodian webpage will show `Logged Out` state in the drop down
- Ensured that `You are logged out` popup is displayed on the brave rewards panel
- Ensured that tapping on the `logged out` will open a drop down with a link to log in to the custodian site. 

Example | Example | Example
-|-|-
![screenshot-1675727878019](https://user-images.githubusercontent.com/17885425/217114777-18eaa1f3-9024-4f9e-bbc5-8da000776d93.png) | ![screenshot-1675727908933](https://user-images.githubusercontent.com/17885425/217114781-e685a696-d267-441a-a82f-8029c558b9dd.png) | ![screenshot-1675727950297](https://user-images.githubusercontent.com/17885425/217114782-1f36022c-e458-400b-93b2-b2e5eabb9ca7.png)
