### ISSUE TITLE
Homepage of panel showing up before confirming a transaction

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#28092]
## Description 

When confirming a transaction on the wallet, we show the old homepage of the panel before quickly showing the new signing interface. This happens on many types of transactions. It doesn't look polished. We should try fix it. Attached is video of it and the slack conversation relating to it 

https://user-images.githubusercontent.com/12224304/215077370-67430811-6417-406d-85df-4c8f49133675.mov

https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1674574214620619

## Steps to Reproduce

   1. 
   2. 
   3. 

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.124 Chromium: 127.0.6533.73 (Official Build) beta (64-bit)
-- | --
Revision | dbc9035349f74e493f3293d93f4cbf35c597dfec
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from [brave/brave-core#24039](https://github.com/brave/brave-core/pull/24039)
- Verified homepage of panel is not shown when confirming a transaction

https://github.com/user-attachments/assets/9a6d651e-5b4f-47fb-adf6-4f6fa5a6e532

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.69.152 x64 build
- Verified steps from [brave/brave-core#24039](https://github.com/brave/brave-core/pull/24039)
- Verified homepage of panel is not shown when confirming a transaction
