### ISSUE TITLE
Rotate the Windows update key

### ISSUE THREAD

**Issue by mherrmann** [brave/brave-browser#28091]
## Description 

In addition to SSL, updates on Windows are secured at the transport layer with a mechanism called CUP. The goal of this issue is to rotate the associated keys on the client side.

**Comment by LaurenWags** [comment]
@brave/qa-team we should test this on multiple Windows versions and devices, please don't add labels until all verifications are complete.

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.49.100 Chromium: 110.0.5481.100 (Official Build) beta (64-bit)
-- | --
Revision | 4be7a36f7cb943af6118e449bbab494b43dcaddd-refs/branch-heads/5481_77@{#14}
OS | Windows 10 Version 21H2 (Build 19044.2604)
```
