### ISSUE TITLE
Brave wallet button notification source is shown on every start 

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#28098]

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta  (64-bit) 
-- | --
Revision | `46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}`
OS | Linux

- Verified steps from [brave/brave-core#16893](https://github.com/brave/brave-core/pull/16893)
- Verified closing and relaunching browser doesn't retain the wallet notification badge

https://user-images.githubusercontent.com/17010094/221932897-34e6475a-41a3-4638-921d-89e4c00a1f6b.mp4
