### ISSUE TITLE
Vertical tabs are broken: Left tab edge located at the right end of the vertical tab bar.

### ISSUE THREAD

**Issue by Coffeeling** [brave/brave-browser#28093]
## Description 
Tabs are physically located at the edge of the tab bar, making it impossible to see the names of tabs and tab groups. Most behavior seems otherwise normal and functional.

## Steps to Reproduce

   1. Enable vert tabs on latest Nightly

## Actual result:
![image](https://user-images.githubusercontent.com/54371213/215080327-01748a6a-493c-406e-98c6-9ba394abcfb7.png)

## Brave version (brave://version info)
Brave	1.49.64 Chromium: 110.0.5481.52 (Official Build) nightly (64-bit) 
Revision	979113183ded4544a2c443aceb1629c430907e52-refs/branch-heads/5481@{#636}
OS	Windows 10 Version 22H2 (Build 19045.2486)

## Version/Channel Information:

- Can you reproduce this issue with the beta channel? 
    - Not yet
- Can you reproduce this issue with the nightly channel? 
    - Yes

**Comment by thorrrr** [comment]
HI 
I have reported on a post i had going it can be moved here i guess see [here](https://community.brave.com/t/brave-beta-verticle-tabs-broken-afer-update-today/461223)
