### ISSUE TITLE
Add disable Autoplay support

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#281]
To keep in line with browser-laptop 
![image](https://user-images.githubusercontent.com/17010094/41445098-2edeb334-7015-11e8-906e-e48a6af0ec8c.png)

**Comment by darkdh** [comment]
Follow up items:
1. play() video instead of reload when user click "Allow" from permission bubble (suggested by @bbondy)
2. Merge autoplay and sound into one site setting (suggested by @bridiver)

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | -- 
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Linux

* Verified autoplay bubble is shown when a site is loaded with media content
* Verified `Allow` in the autoplay bubble, clicking media content starts to play
* Verified `Deny` in the autoplay bubble, doens't load media content
* Verified changing Auto play setting from site details dropdown asks to reload the page and changes take effect
