### ISSUE TITLE
Change delete account error message

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#28106]
Follow-up for https://github.com/brave/brave-core/pull/13562 
Found while test https://github.com/brave/brave-browser/issues/22884#issuecomment-1405699779

Change error text 
`Could not join this sync chain. Account was deleted.` => `Could not join this sync chain. The sync chain was deleted.`

**Comment by kjozwiak** [comment]
The above requires `1.49.90` or higher for `1.49.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using the following builds:

#### desktop:

Brave | 1.49.90 Chromium: 110.0.5481.77 (Official Build) beta (64-bit) 
--|--
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | Windows 10 Version 22H2 (Build 19045.2546)

#### Android:

`1.49.90`, `Chromium` `110.0.5481.77` on a `Google Pixel XL` (`arm64`) running `Android 9`

### Steps:

1. installed `1.49.90` on both Android and macOS
2. launched Brave
3. created the sync chain on macOS
4. displayed the QR code and took a screenshot
5. deleted the sync chain from macOS
6. on Android, tried to enter the sync chain by scanning the QR code in the screenshot

#### Confirmed the error message was `Could not join this sync chain.  The sync chain was deleted.`

example | example | example | example | example | `The sync chain was deleted.`
---------|----------|---------|----------|---------|---------
![image](https://user-images.githubusercontent.com/387249/217647218-0f0d4244-78b3-4a3d-ab04-9038fe4e73e8.png) | ![image (1)](https://user-images.githubusercontent.com/387249/217647380-4ccb1bee-7e35-468b-971b-5200185d0d7e.png) | ![image (2)](https://user-images.githubusercontent.com/387249/217647438-2223ccec-2765-45e5-bc83-fb9c841c195c.png) | ![image (3)](https://user-images.githubusercontent.com/387249/217647440-0c5fc696-f4a3-4b39-9039-14e11ba3364f.png) | ![Screenshot_20230208-123434](https://user-images.githubusercontent.com/387249/217647552-b0e3b5d7-ecc4-455f-abf6-dcd0d35b4b85.png) | ![Screenshot_20230208-123505](https://user-images.githubusercontent.com/387249/217647555-e684852a-5faa-449f-a624-0d62e26431dc.png) | ![Screenshot_20230208-123520](https://user-images.githubusercontent.com/387249/217647559-a78b172f-87ba-45c4-a2ee-ee8ce2e2fa72.png)

**Comment by stephendonner** [comment]
Note: I covered `macOS`, `Android`, and `Windows 10` in the course of testing, but only marked `QA Pass-macOS`, as we might want to run through at least another desktop test on `Windows 10`, and on `Android`, do `Android` <-> `Android` etc.

**Comment by Uni-verse** [comment]
Verified on `Samsung GS 21` version:

```
Brave	1.49.118 Chromium: 111.0.5563.50 (Official Build) (64-bit) 
Revision	39f3dfc5023fe60997adc4f6cf5439cfa3e6968a-refs/branch-heads/5563@{#903}
OS	Android 13; Build/TP1A.220624.014
```
Test Plan:

Steps:

1. installed 1.49.118 on both Android
2. launched Brave
3. created the sync chain on macOS
4. displayed the QR code and took a screenshot
5. deleted the sync chain from macOS
6. on Android, tried to enter the sync chain by scanning the QR code in the screenshot
7. Repeated with another Android device 

- Ensured delete sync account copy change
- Ensured deleting sync chain started on another Android device will still display the error message

<img width="400" alt="Android 13" src="https://user-images.githubusercontent.com/17885425/223188527-73055a7e-4684-4fd2-873c-9be713fa1931.png">
