### ISSUE TITLE
Add ads enabled + installation time P3A metric

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#28109]
Add a one-time P3A metric reporting the number of hours between the installation time and the time when ads are enabled.

The bucket values will be as follows:

0. Less than an hour
1. 1 hour or more, less than 12 hours
2. 12 hours or more, less than 24 hours
3. 24 hours or more, less than 72 hours
4. 72 hours or more

The P3A metric will be sent only once, but will be reported via the daily cadence.

Support for ephemeral/one-time P3A metrics is also part of this issue. A new flat set in metric_names.h will be added to enumerate ephemeral metrics.

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave | 1.51.79 Chromium: 112.0.5615.49 (Official Build) beta (64-bit)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Windows 10 Version 21H2 (Build 19044.2728)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/16897
