### ISSUE TITLE
Cannot copy/paste autocompleted url

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#28103]
Broken in https://github.com/brave/brave-core/pull/16764

# Steps to reproduce
- command-T (to create a new tab)
- i type “useni” which autocompletes to [usenix.org/conference/usenixsecurity23/submission-policies-and-instructions]- (http://usenix.org/conference/usenixsecurity23/submission-policies-and-instructions)
- I select and copy just the text [usenix.org/conference/usenixsecurity23/](http://usenix.org/conference/usenixsecurity23/)
- paste gives me chrome://newtab/

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.49.96 Chromium: 110.0.5481.77 (Official Build) beta (x86_64)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | macOS Version 11.7.3 (Build 20G1116)

### Steps:
1. installed `1.49.96`
2. launched Brave
3. loaded `http://usenix.org/conference/usenixsecurity23/submission-policies-and-instructions`
4. hit `return` a few times to build up autocomplete
5. typed `useni` to auto-complete the remaining URL
6. selected just `usenix.org/conference/usenixsecurity23/`
7. pasted `usenix.org/conference/usenixsecurity23/`

#### Confirmed I copied and pasted `usenix.org/conference/usenixsecurity23/`

example | example | example
---------|----------|---------
<img width="1312" alt="Screen Shot 2023-02-13 at 2 38 56 PM" src="https://user-images.githubusercontent.com/387249/218592272-af7679f7-c31b-46f1-970d-a6d314e25265.png"> | <img width="1312" alt="Screen Shot 2023-02-13 at 2 39 07 PM" src="https://user-images.githubusercontent.com/387249/218592292-802dbcfb-2068-4479-904c-67811953f74d.png"> | <img width="1312" alt="Screen Shot 2023-02-13 at 2 50 54 PM" src="https://user-images.githubusercontent.com/387249/218592376-fdd959a3-f94c-44a7-b6c5-052a03de6515.png">
