### ISSUE TITLE
Fix account deletion is in progress modal

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#28105]
Follow-up for https://github.com/brave/brave-core/pull/13562 
Found while test https://github.com/brave/brave-browser/issues/22884#issuecomment-1398865126

The screenshot: 
![image](https://user-images.githubusercontent.com/24739341/215198602-0b55cd6b-1e65-4617-82f3-3e14a05847c0.png)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.57.8 Chromium: 115.0.5790.75 (Official Build) beta (64-bit)
-- | --
Revision | 77bffd419b7e89d7e666c9695e7fa0d1d0367a99
OS | Windows 11 Version 22H2 (Build 22621.1992)
```

1. Install 1.57.8
2. launch Brave
3. opened brave://sync
4. setup a sync chain on Profile 1
5. joined the sync from Profile 2
6. return to brave://settings/braveSync/setup for Profile 1
7. scroll down to the bottom and click `Delete Sync account`
8. clicked on `Permanently delete account` on the `Delete Sync account` dialog

Confirmed margins are fixed around `Account deletion is in progress...` text area

1.52.130 | step 4 | step 5 | step 7 | step 8 | 1.57.8
----- | ----- | ----- | ----- | ----- | -----
![image](https://github.com/brave/brave-browser/assets/98358127/08fb6359-d556-4b3c-bbc1-4d3c70e6f3dc)|![image](https://github.com/brave/brave-browser/assets/98358127/8b845943-bb75-4868-b9f0-19d5b9108daf)|![image](https://github.com/brave/brave-browser/assets/98358127/8d0a7bf9-6009-4d5f-ac39-c17e3a19416a)|![image](https://github.com/brave/brave-browser/assets/98358127/f135777f-1c1f-4519-a89f-b71b1dfa2f41)|![image](https://github.com/brave/brave-browser/assets/98358127/8e3aef17-dd93-4b31-b304-76b2543cde26)|![image](https://github.com/brave/brave-browser/assets/98358127/a14d860f-05a0-43d2-8339-b5b84073a93b)
