### ISSUE TITLE
`Monthly tip failed` button is missing `OK` text

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#28116]
## Description 

`Monthly tip failed` button is missing `OK` text

## Steps to reproduce 

Follow the steps from https://github.com/brave/brave-browser/issues/22374

## Actual result 

Missing the `OK` button text

`Light` | `Dark`
--------|-------
![Screenshot_20230228-025508](https://user-images.githubusercontent.com/387249/215265861-22244733-27bd-4cd7-ba96-a9130eca8e0e.png) | ![Screenshot_20230228-025602](https://user-images.githubusercontent.com/387249/215265863-fbdab1b3-3eb1-4be5-921d-61acc2fc74e5.png)

## Expected result

The button label should say `OK`

## Issue reproduces how often 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): `arm64`
   - Device type (Phone, Tablet, Phablet): `Google Pixel XL`
   - Android version: `9`
   
## Brave version

`1.48.141`, `Chromium` `109.0.5414.119`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

/cc @deeppandya @Miyayes @LaurenWags @kjozwiak @Uni-verse @srirambv @zenparsing

**Comment by kjozwiak** [comment]
The above requires `1.48.155` or higher for `1.48.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress on Google Pixel 3 XL with Android 12 running 1.48.155.
