### ISSUE TITLE
[CR110] Onboarding is not completed

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#28110]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/27221.  Onboarding is stuck at  `Setup complete` page and never progresses to `Help make Brave Better` page. 

## Steps to Reproduce

   1. Install `1.49.64`
   2. launch Brave
   3.  click `Set Brave as default browser`
   4.  select `Chrome` >>` Import`
   5.  Select `Chrome Person 1`>>`Import profiles`
## Actual result:

Onboarding is stuck at `Setup Complete` step

https://user-images.githubusercontent.com/98358127/215210467-93b0dceb-b234-40e0-bbf9-817d2bd044b7.mp4

## Expected result:
`Help make Brave Better` page should be shown
<img width="459" alt="image" src="https://user-images.githubusercontent.com/98358127/215210081-03c4bc49-670d-47a0-90fa-58d331e9c845.png">

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.49.64 Chromium: 110.0.5481.52 (Official Build) nightly (64-bit)
-- | --
Revision | 979113183ded4544a2c443aceb1629c430907e52-refs/branch-heads/5481@{#636}
OS | Windows 11 Version 21H2 (Build 22000.1455)
```
## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@rebron @emerick 
cc: @brave/qa-team

**Comment by rebron** [comment]
cc: @nullhook @spylogsster

**Comment by MadhaviSeelam** [comment]
@rebron Onboarding process progresses from `Setup complete` page to `Help  make Brave better` page and completed successfully in Non Cr 110 nightly  build  (1.49.62 Chromium: 109.0.5414.119 (Official Build)) as expected

ex|ex
----|----
<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/215873282-3da41b6b-9cba-4448-b7d9-05596f525015.png">|<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/215873323-a43ac7a9-7e43-4f0d-bd99-7001bff9d080.png">

@brave/qa-team

**Comment by kjozwiak** [comment]
The above requires `1.48.153` or higher for `1.48.x` verification 👍

**Comment by LaurenWags** [comment]
Removed `QA/Test-All-Platforms` label per discussion with @kjozwiak @rebron but we will want to verify this one on Windows.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.48.155 Chromium: 110.0.5481.77 (Official Build) (64-bit)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | Windows 11 Version 21H2 (Build 22000.1455)
```

1. Install 1.48.155
2. launch Brave
3. click Set Brave as default browser
4. select Chrome >> Import
5. Select Chrome Person 1>>Import profiles

#### Confirmed onboarding process progressed to each step and completed Chrome profile import successfully  

step 3|step 4|step 5|result|result
----|----|----|----|-----
<img width="459" alt="image" src="https://user-images.githubusercontent.com/98358127/216684468-c8f717fe-f5fd-4214-8711-96aa0fa0ccf0.png">|<img width="461" alt="image" src="https://user-images.githubusercontent.com/98358127/216684518-228e4003-979d-40c3-a897-4c297963c9dd.png">|<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/216684568-569ac259-4d49-4ec7-8060-411994565cdd.png">|<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/216684666-1527fbc2-fcb6-4ed0-8aa3-6f6891b33975.png">|<img width="456" alt="image" src="https://user-images.githubusercontent.com/98358127/216684718-452b0d5d-ae0e-460a-8453-67c85fe6917e.png">
