### ISSUE TITLE
Remove widgets components from manifest

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#28118]
This issue is to remove widgets components from android manifest. We need to add a patch to remove the components. 

This was the suggestion from Samsung team, 

[Suggested Solution]

1. delete widget component in Android manifest

![image](https://user-images.githubusercontent.com/2602313/215284310-7c708a2b-230c-4e05-a28a-2e7a31c0ec48.png)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 13` using the following build(s):

```
Brave | 1.47.188 Chromium: 109.0.5414.119 (Official Build) (32-bit)
--- | ---
Revision | 772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}
OS | Android 13; Build/TQ1A.230105.002
```

**`Test Case #1` - Clean  Profile/Install**

* ensured that the widget onboarding appeared/displayed without any issues
* ensured that you can add a widget to the home screen via onboarding
* ensured that there's `5` widgets that are appearing under `Brave`
* ensured that you can add each widget onto the home screen without any issues

**`Example`** | **`Example`** | **`Example`** | **`Example`** |  **`Example`**
----------------|----------------|----------------|----------------|-----------------
![Screenshot_20230129-023742](https://user-images.githubusercontent.com/2602313/215312674-900b721e-3260-494a-8589-b420fa711f96.png) | ![Screenshot_20230129-023747](https://user-images.githubusercontent.com/2602313/215312696-ae24086c-524b-472e-82ca-9dd2ff38293e.png) | ![Screenshot_20230129-023530](https://user-images.githubusercontent.com/2602313/215312685-c544fadf-58f1-421b-a381-de4e76db1882.png) | ![Screenshot_20230129-023536](https://user-images.githubusercontent.com/2602313/215312687-4bcb5ef4-985b-4ae3-ae19-7297ea803ffd.png) | ![Screenshot_20230129-024356](https://user-images.githubusercontent.com/2602313/215312703-8406cc16-e514-441a-a1f1-d90c2bb27e84.png)

**`Test Case #2` - Upgrade from `1.47.186` -> `1.47.188`** (Post https://github.com/brave/brave-browser/issues/27757)

* installed `1.47.186` and ensured that `Brave` only had three available widgets
* added the three available widgets onto the home screen
* updated to  `1.47.188` and ensured that the previously added widgets are still working as expected
* ensured that there's now `5` widgets appearing within the OS `Widget` section
* ensured that you can add the older widgets onto the home screen without any issues

**`1.47.186 - Before Update`**

**`Example`** | **`Example`** 
----------------|---------------
![Screenshot_20230129-025225](https://user-images.githubusercontent.com/2602313/215313230-49ff92f3-b2bf-4d64-b505-7008539f58aa.png) | ![Screenshot_20230129-025335](https://user-images.githubusercontent.com/2602313/215313233-bfd569bd-0042-4e23-b0bf-d199aa853b58.png)

**`1.47.188 - After Update`**

**`Example`** | **`Example`** | **`Example`** 
----------------|----------------|----------------
![Screenshot_20230129-025403](https://user-images.githubusercontent.com/2602313/215313243-ca0d9ff4-d7a5-4e9d-a816-351a973b0634.png) | ![Screenshot_20230129-025409](https://user-images.githubusercontent.com/2602313/215313244-8b3478f9-a109-401f-b410-0dde6c0fd790.png) | ![Screenshot_20230129-025521](https://user-images.githubusercontent.com/2602313/215313245-2b8e403c-2260-4888-bace-9d550acaa3b8.png)

**`Test Case #3` - Upgrade from `1.47.172` -> `1.47.188`** (Pre https://github.com/brave/brave-browser/issues/27757)

* installed `1.47.172` and ensured that `Brave` had four available widgets
* added the four available widgets onto the home screen
* updated to  `1.47.188` and ensured that the previously added widgets are still working as expected
* ensured that there's now `5` widgets appearing within the OS `Widget` section
* ensured that you can add the older widgets onto the home screen without any issues

**`1.47.172 - Before Update`**

**`Example`** | **`Example`** 
----------------|---------------
![Screenshot_20230129-030120](https://user-images.githubusercontent.com/2602313/215313658-8e6d8a92-ab80-48ac-9b3b-3665debfe8ae.png) | ![Screenshot_20230129-030239](https://user-images.githubusercontent.com/2602313/215313660-e875fa41-409f-4990-a298-3de512793c52.png)

**`1.47.188 - After Update`**

**`Example`** | **`Example`** | **`Example`** 
----------------|----------------|----------------
![Screenshot_20230129-030407](https://user-images.githubusercontent.com/2602313/215313669-621dfafa-1514-4f10-a6ca-0978600ad20b.png) | ![Screenshot_20230129-030659](https://user-images.githubusercontent.com/2602313/215313671-7d47789d-ae98-4955-ba32-c98798ec3512.png) | ![Screenshot_20230129-030720](https://user-images.githubusercontent.com/2602313/215313676-8c119485-bbcb-495e-9151-79ca84f43700.png)
