### ISSUE TITLE
Sync Chain Code/QR Code disappearing when importing code fails

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#2812]
## Description 

When you you fail a sync chain code import via `Enter a sync chain code`, the code and QR code under `Start a new sync chain` will won't be displayed as exampled below. Once you either refresh `brave://sync` or close/re-open, the code and QR code will re-appear.

## Steps to Reproduce

   1.  launch brave with sync enabled (`0.59.14 Chromium: 72.0.3626.28` in this case)
   2. go into `brave://sync`
   3. click on `Start a new sync chain` and ensure that you have a code/QR code
   4. go back to the main sync screen and click on `Enter a sync chain code`
   5. click on `Confirm Sync Code` and press `OK` when you get the error
   6. go back into `Start a new sync chain` and you'll notice that the sync codes/QR are not being displayed

## Actual result:

![synccode](https://user-images.githubusercontent.com/2602313/50663086-82693000-0f76-11e9-8bd2-d86d72ab548d.gif)

## Expected result:

<img width="741" alt="screen shot 2019-01-03 at 4 42 19 pm" src="https://user-images.githubusercontent.com/2602313/50663106-914fe280-0f76-11e9-9dc2-f178e33eaded.png">

<img width="724" alt="screen shot 2019-01-03 at 4 42 25 pm" src="https://user-images.githubusercontent.com/2602313/50663112-944ad300-0f76-11e9-8831-54df9a1dc78f.png">

## Reproduces how often: 

100% reproducible when using the above STR.

## Brave version (brave://version info)

Brave | 0.59.14 Chromium: 72.0.3626.28 (Official Build) beta(64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds?

Not reproducible using `0.58.18 Chromium: 71.0.3578.98` which is the current release. Opened `0.58.18 Chromium: 71.0.3578.98` using `--enable-brave-sync` and couldn't reproduce the issue. Seems when you press `OK` on the failed message, the entire modal is closed. With `0.59.14 Chromium: 72.0.3626.28`, pressing `OK` just closes the error message.

### Additional Information

* Win 10 x64 - Reproduced by @kjozwiak & @GeetaSarvadnya 
* Win 7 x64 - Reproduced by @btlechowski 
* Mint 18.3 x64 - Reproduced by @kjozwiak

Possibly related to #2602 & #2604. CCing @cezaraugusto

**Comment by kjozwiak** [comment]
Removed `priority/P3` as refreshing `brave://sync` or closing/re-opening the tab recovers both codes.

**Comment by btlechowski** [comment]
Reproduced on 

Brave | 0.59.14 Chromium: 72.0.3626.28 (Official Build) beta(64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Windows 7

![image](https://user-images.githubusercontent.com/34715963/50668855-144a5a80-0fc2-11e9-9923-59bf683ee2eb.png)

**Comment by srirambv** [comment]
This is also reproduced when you reset sync and try to enable sync again as mentioned in scenario 2 in https://github.com/brave/brave-browser/issues/2801

**Comment by AlexeyBarabash** [comment]
Can reproduce it.
I will take this issue, it looks the issue goes from `brave_sync_service_impl.cc`.
