### ISSUE TITLE
Custom Filter Lists UI in brave://adblock completely broken since Nightly builds went Chromium 110

### ISSUE THREAD

**Issue by Emi-TheDhamphirInLoveUnderTheFrozenStar** [brave/brave-browser#28128]
## Description 

Chromium 110 completely broke the UI section that contains the custom filter lists. Custom lists don't show at all, so they can't be updated or unsubscribed or disabled. The only work around is to do it through editing the Local State file.

Console throws some errors about `Could not find style data in module named null` and `'TrustedHTML'`  and `Trusted Type Expected - Blocked`  and `polymer_bundled.min.js:1 `, the errors only happen when opening brave://adblock page, other pages don't cause that problem. I don't think these errors have to do with this issue #27647 made by @rebron but I better report this, because I didn't see any other issue talking about Chromium 110 breaking the custom lists UI.

Thank you.

## Steps to Reproduce

   1. Go to brave://adblock
   2. Add a list (if empty) should trigger the problem. (If custom lists were added before, the problem should be present.)
   
## Actual result:

Blank UI no custom filter list, names, buttons or anything
![image](https://user-images.githubusercontent.com/122518587/215396221-807a267e-4ac6-460d-8052-356bf1ab948b.png)

![image](https://user-images.githubusercontent.com/122518587/215397052-798364d5-6bbf-404e-a9e8-56f826ac0973.png)

## Expected result:
Being able to see the list of custom filter lists and update them, disable them or remove them.

## Reproduces how often: 

Always since first nightly with Chromium 110.

## Brave version (brave://version info)

Nightly 1.49.75 Chromium: 110.0.5481.52

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the nightly channel? yes (since Nightly is the only build with Chromium 110)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? no, because it is a Brave specific feature.

## Miscellaneous Information:

When fixed, would be good if the UI was tested with more than 15 or 20 custom lists, because last time I was able to update them (before 110), there was a weird behavior after updating the lists that were located at the bottom.
It happens when many list are added, and It's like the UI with the lists collapses, and every list gets hidden/moved upwards, then it gets expanded again after a second, making it slow to update, because there is no way to click the button `⋮` -> update quickly, while the UI gets all weird.
Not critical or related to Chromium 110, but would be good if someone at Brave checked that to understand the issue so it can be fixed in the future, if issue is still present and exists.
Custom lists UI seems to have some issues, would be good if all were covered.

**Comment by Emi-TheDhamphirInLoveUnderTheFrozenStar** [comment]
@BrendanEich @bbondy Can you tell someone from your Brave team in charge with these settings UI stuff to take a look at this issue?

I Just installed pre-release of  [Release v1.48.155 (Chromium 110.0.5481.77) ](https://github.com/brave/brave-browser/releases/tag/v1.48.155) in another device to make sure it is not me, and it has the same exact issue, which is big, because you can't really do anything with custom filter lists, maybe not many users use custom lists anymore, but if it was already hard to update many lists one by one (since they update automatically every 7 days) now it's even worst, I have to close the browser, edit Local State file, put a date from like 4 months ago, open brave and then wait for the lists to get updated.

I don't mind doing that, but it's mostly about the other users who will not know how to update the lists and they don't know what happened to them, they think they got deleted or something.

It's just weird nobody has noticed this big obvious bug that Chromium 110 caused, and I reported it so it would get fixed and apparently nobody sees it or care to see it. It happened with `$removeparam` support, I didn't have a Github account, didn't report it, nobody saw the clear issues with it and then took couple weeks for bad crashes (the most critical issue) to get pushed to stable, and how some rules weren't compatible, and all that because I didn't report it, like if I was the only one using these features.
Now, I report this issue before it hits stable, but it gets ignored like if "completely broken" wasn't dramatic enough, even if it is true, it is completely broken.

You can't release the build next week with this issue, you shouldn't, you should give highest priority instead of other changes that will mean nothing in the end for the user. Imagine you using custom lists, open Brave after the update and you want to add or update a list?

Since you are both founders of Brave I hope you can do something. Maybe in the overall picture it is not the biggest issue Brave will have, but it was working before, now it is broken. Something should be done about it even if not everyone will notice it.

Have a good day.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.48.158 Chromium: 110.0.5481.77 (Official Build) (64-bit) 
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/17059#issuecomment-1420380876

#### Test Case 1 - clean profile


* installed `1.48.158`
* opened `brave://settings/shields/filters`
* added the following custom filter list via `Add custom filter lists` without any issues/failures via `DevTools`
  * `https://easylist-downloads.adblockplus.org/easylistpolish.txt`

![image](https://user-images.githubusercontent.com/34715963/217293632-006daf77-53b6-4df5-88af-0b33ff036ef8.png)

Verified the custom filters are applied:
Open `sadownictwo.com.pl` and verify that top banner is gone

Before | After
-- | --
![image](https://user-images.githubusercontent.com/34715963/217294212-be4f81e7-958c-4064-b498-d1e11f3a73f3.png)|![image](https://user-images.githubusercontent.com/34715963/217294354-f61b44fc-33ed-4a92-844e-edd46cf548f8.png)


#### Test case 2 - upgrade profile

* installed `1.47.x`
* opened `brave://settings/shields/filters`
* added the following custom filter via `Add custom filter lists` without any issues (appears in the list as expected)
  * `https://easylist-downloads.adblockplus.org/easylistpolish.txt`
* updated to `1.48.158`
* ensured that the filter is still being displayed via `Custom Filter` under `brave://settings/shields/filters`
  * ensured that there's no errors/failures via `DevTools` when viewing the `console`

1.47.x | 1.48.x
-- | --
![image](https://user-images.githubusercontent.com/34715963/217296863-2b22fded-7aa9-4dc6-a7a6-dd0d650d262c.png)|![image](https://user-images.githubusercontent.com/34715963/217297457-7cfa1414-f5f6-43b4-9671-3e47dd05b29c.png)


Verified the custom filters are applied:
Open `sadownictwo.com.pl` and verify that the top banner is gone
![image](https://user-images.githubusercontent.com/34715963/217297634-936c9ca8-8774-41c1-8978-8e05f2027812.png)

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using 
```
Brave | 1.48.158 Chromium: 110.0.5481.77 (Official Build) (64-bit)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | Windows 11 Version 21H2 (Build 22000.1455)
```
Case 1: New profile
- installed 1.48.158
- opened brave://settings/shields/filters
- added the following custom filter list via Add custom filter lists without any issues/failures via DevTools:
    - https://easylist-downloads.adblockplus.org/easylistpolish.txt
    - https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Anti-'Google%20Hangouts'%20List.txt


<img width="955" alt="image" src="https://user-images.githubusercontent.com/98358127/217332781-e23557a1-b068-429f-b0b4-0695b3ce4c0d.png">

Case 2: Upgrade

- 
- installed 1.47.186
- opened brave://settings/shields/filters
- added the following custom filter via Add custom filter lists without any issues (appears in the list as expected):
- https://easylist-downloads.adblockplus.org/easylistpolish.txt
- updated to 1.48.158
- ensured that the filter is still being displayed via Custom Filter under brave://settings/shields/filters
- ensured that there's no errors/failures via DevTools when viewing the console
- Verified the custom filters are applied:
- Opened sadownictwo.com.pl and verified that the top banner is gone


1.47.186|1.48.158|ex|ex
-----|----|-----|----
<img width="942" alt="image" src="https://user-images.githubusercontent.com/98358127/217333683-b794c326-16a5-45f7-8603-06dd47bd1547.png">|<img width="945" alt="image" src="https://user-images.githubusercontent.com/98358127/217333958-14706e05-9c70-41d7-8388-d16ba92bf5f4.png">|<img width="958" alt="image" src="https://user-images.githubusercontent.com/98358127/217334619-fcd5cba4-2bc0-4bbc-b59e-45b6d2e717c0.png">|<img width="935" alt="image" src="https://user-images.githubusercontent.com/98358127/217334107-4fe4229a-3459-489a-b6b0-300ba68d8fc4.png">

**Comment by bsclifton** [comment]
Hi @Emi-TheDhamphirInLoveUnderTheFrozenStar

Just wanted to take a minute to thank you for opening this. There are definitely things which break as we upgrade Chromium - there were a few other areas we didn't find until later too. Definitely nothing broken intentionally! I saw your original comment and the edit - huge thanks for your patience. 

Having feedback on Nightly is massively important to us - please do keep reporting issues that you find 😄

**Comment by Emi-TheDhamphirInLoveUnderTheFrozenStar** [comment]
@bsclifton I appreciate the message and I appreciate all the work you and the Brave team do!
I was just worried people's list would appear 'gone' and then people would push the red button and complain, when it could have been avoided, but it's good you guys rushed to fix it!

And don't worry I will keep reporting! lol
For example, I finally just opened an issue about my Miscellaneous Information where I talk about the lists 'collapsing' when updating, https://github.com/brave/brave-browser/issues/28894, not critical like this bug where lists didn't display correctly, but still ugly and annoying, especially when I switch to use Default lists as custom for testing purposes.

Thanks again and have a good day!
