### ISSUE TITLE
System Locks Up After Using Brave

### ISSUE THREAD

**Issue by KnownStormChaser** [brave/brave-browser#28126]
## Description 
The whole system locks up after using Brave for a few seconds, sometimes it takes a couple of minutes.

## Steps to Reproduce

   1. Open Brave
   2. Do anything until whole system locks up (literally anything)

## Actual result:
System freezes and needs to power cycle computer to fix it.

## Expected result:
Works without freezing

## Reproduces how often: 
Every time Brave is opened. Sometimes it happens within seconds, sometimes it takes a couple of minutes.

## Brave version (brave://version info)
Version 1.47.186 Chromium: 109.0.5414.119 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes 
- Can you reproduce this issue with the beta channel? Unknown
- Can you reproduce this issue with the nightly channel? Unknown

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Yes

## Miscellaneous Information:
This kind of lockup also happens occasionally when using Opera browser, not nearly as often, but sill happens sometimes. I think it might be something to do with chromium because it doesn't happen at all with Firefox.

System hardware: 
Ryzen 7700X
Kingston 32 GB 6000MHz
RX 7900 XT
Asus TUF X670E WIFI

**Comment by 424344** [comment]
maybe hardware drivers incompatibility?
tru disabling hardware acceleration.

**Comment by KnownStormChaser** [comment]
Looks like the AMD Radeon driver 23.3.1 fixed the issue.
