### ISSUE TITLE
Migrate `BraveSessionCache` to use WTF types

### ISSUE THREAD

**Issue by cdesouza-chromium** [brave/brave-browser#28133]
Upstream is rolling out compile time checks with a clang plugin to enforce the use of WTF types where appropriate in blink headers. `BraveSessionCache` should be migrated in anticipation of this change to use WTF types.

**Comment by LaurenWags** [comment]
@cdesouza-chromium does this need manual QA? I've labelled as `QA/No` and `release-notes/exclude` but if either of these labels are incorrect please advise, thanks.

**Comment by cdesouza-chromium** [comment]
You've labelled it correctly. Cheers.
