### ISSUE TITLE
nightly MacOS 1.49.69 browser crashed sometimes

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#28134]
Crashes from https://bravesoftware.slack.com/archives/C01826CM3J9/p1675084530072309

```
[ 00 ] -[BraveAppController shouldShowCleanLinkItem] ( raw_ptr.h:1544 )
[ 01 ] -[BraveAppController shouldShowCleanLinkItem] ( brave_app_controller_mac.mm:40 )
[ 02 ] -[BraveAppController menuNeedsUpdate:] ( brave_app_controller_mac.mm:61 )
```

# Steps 
- opened [youtube.com](http://youtube.com/)
- then i closed the window (so Brave is running but has no open windows)
- select Edit menu item in the top mac menu

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

### Steps:
1. installed 
2. launched Brave
3. loaded a few `YouTube` videos
4. created a temporary `Brave Wallet`
5. opened it by clicking on the `Brave Wallet` icon in the toolbar
6. returned to a playing `YouTube` video
7. crashed <-------

Confirmed using `1.49.75`:

example | example
---------|----------
<img width="1312" alt="Screen Shot 2023-02-07 at 3 47 58 PM" src="https://user-images.githubusercontent.com/387249/217394574-b096a481-b60a-428e-ae62-7b7d3c2e216d.png"> | <img width="1312" alt="Screen Shot 2023-02-07 at 3 48 18 PM" src="https://user-images.githubusercontent.com/387249/217394575-b025838a-2f9e-4704-bca0-f0df8b7549cd.png">
