### ISSUE TITLE
Deleting Swap input value retains the swap quotes 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#28137]
## Description 

Deleting Swap input value retains the swap quotes 

## Steps to Reproduce

   1. Select a token to swap
   2. Select a value or select pre-set values
   3. Wait for the swap quote to refresh 
   4. Delete the input value of Swap token, quote refreshes and is retained

## Actual result:

https://user-images.githubusercontent.com/17010094/215513208-2152ef25-4d95-4f8d-af60-a3b7e9ca1745.mp4

## Expected result:
Not sure maybe remove quotes 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.48.141 Chromium: 109.0.5414.119 (Official Build) beta (64-bit)
-- | --
Revision | `772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}`
OS | Windows 11 Version 22H2 (Build 22621.1105)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @onyb @jamesmudgett @minkyeongshin

**Comment by kjozwiak** [comment]
@srirambv as per the discussion via https://bravesoftware.slack.com/archives/CHGKGMHDJ/p1676524126357019, please create a follow up to this one. Labelling as `QA/No` and `release-notes/exclude` as it's still reproducible/not addressed by https://github.com/brave/brave-core/pull/17239.

**Comment by srirambv** [comment]
Logged follow up issue https://github.com/brave/brave-browser/issues/28618
