### ISSUE TITLE
Custom names for NFT's are not shown after adding NFT to portfolio

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#28131]
## Description 

Custom names for NFT's are not shown after adding NFT to portfolio

## Steps to Reproduce

   1. Go Add NFT screen
   2. Give it a custom name and add NFT
   3. Shows the resolved name rather than the custom name

## Actual result:

Custom name is not shown 

## Expected result:
Should show the custom name that is added via the form 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.48.141 Chromium: 109.0.5414.119 (Official Build) beta (64-bit)
-- | --
Revision | `772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}`
OS | Windows 11 Version 22H2 (Build 22621.1105)

</body>
</html>
## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc: @muliswilliam @Douglashdaniel

**Comment by kjozwiak** [comment]
The above requires `1.48.155` or higher for `1.48.x` verification 👍

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/27521#issuecomment-1416119683
