### ISSUE TITLE
Google search banner displayed on NTP when default SE is set to Google [CR110]

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#28145]
## Description 
Selecting Google as default SE will show google search banner on NTP

Brave default SE | Google default SE | Google default SE
-|-|-
![screenshot-1675105258045](https://user-images.githubusercontent.com/17885425/215571479-b163839e-4e76-483d-afb3-0acb100b0046.png) | ![screenshot-1675105309948](https://user-images.githubusercontent.com/17885425/215571492-cb694162-6e82-4658-8ec4-5fa297f8ba74.png) | ![screenshot-1675105214745](https://user-images.githubusercontent.com/17885425/215571629-bce46af7-2c96-43f9-95ae-29ab9a7d1514.png)

## Steps to reproduce 

   1. Install 1.49.64
   2. Change SE to Google if set to Brave on fresh profile
   3. Go back to NTP
   4. Relaunch browser

## Actual result 
Google banner is shown

## Expected result
Should not show google banner

## Issue reproduces how often 
Easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? No
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung Galaxy S21
   - Android version: 13
   
## Brave version
1.49.64 Chromium 110

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.48.153` or higher for `1.48.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21 5G` & `Samsung Galaxy Tab S7` using version `1.48.155, Chromium 110.0.5481.77`

Used STR from https://github.com/brave/brave-browser/issues/28145#issue-1563045720 to ensure that google banner is not displayed when changing default SE to google.

Example | Example
-|-
![screenshot-1675462743440](https://user-images.githubusercontent.com/17885425/216721950-bc992e3e-c917-4bf6-815b-a44aa6a4f82c.png) | ![screenshot-1675462768936](https://user-images.githubusercontent.com/17885425/216721953-8e07c148-ba10-40c8-8a1f-770f2ac9cab5.png)
