### ISSUE TITLE
Background image options do not appear when system default language is set to Spanish

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#28144]
## Description 

A user reported that they were unable to change their background image settings for the NTP because the options for it (`NTP --> Customize --> Background image`) were not appearing for them:
![image](https://user-images.githubusercontent.com/3299098/215569191-705e769b-2ccd-4018-89df-381c5f70736a.png)

After some troubleshooting, it was discovered that this behavior occurs when the OS (I believe) default Language settings were set to Spanish. Changing the language settings back to English, then returning to `NTP --> Customize --> Background image`, the options now appear again as expected. 
![image](https://user-images.githubusercontent.com/3299098/215569942-6c7edc4c-2b70-47db-96a4-a48801e82a1c.png)

Unclear as to whether or not this is specific to the `Espanol (Spanish)` language setting or if this occurs when any other language is selected (will test myself later).

## Brave version (brave://version info)

v1.47.186
macOS versión: 12.6.2 (Monterey)

## Miscellaneous Information:

Initial user report:
https://community.brave.com/t/the-background-image-option-does-not-appear/465543/8

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using 


Reproduced the issue with `1.47.186` and my `macOS` system language set to `Spanish`
<details>
<img width="1312" alt="Captura de Pantalla 2023-02-13 a la(s) 4 54 02 p  m" src="https://user-images.githubusercontent.com/387249/218610341-0fc4a3c7-29b8-4f89-bd6e-50bb1be3c60f.png">


</details>
