### ISSUE TITLE
[Android] Implement Tip / Contribution Banner 3.0

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#28149]
## Description

Android version of: https://github.com/brave/brave-browser/issues/28148

**Comment by LaurenWags** [comment]
@brave/qa-team when testing this issue on Android, please also verify updated tweet text from https://github.com/brave/brave-browser/issues/30331.

**Comment by LaurenWags** [comment]
@brave/qa-team added `QA/Test-All-Device-Types` since this is new UI so we should verify on phone and tablet.

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Samsung Galaxy Tab A7 version 12` running `Bravemonoarm64.apk_1.53.83`

**Comment by GeetaSarvadnya** [comment]
@Miyayes There are few differences found while testing the issue on Android ARM

1. no inline tip icon for both connected and non-connected users in Android I think which is known 
2. No custodian available in region (panel) message is little different in Android, it's not same as Desktop

Desktop | Android
----------|---------
![image](https://github.com/brave/brave-browser/assets/38657976/57d4cafb-7638-4702-956e-b3e31990791e) | ![image](https://github.com/brave/brave-browser/assets/38657976/6115eef9-644a-4985-b760-4cf7bd9e1cee)

4. Custodian is not connected to Rewards (panel) message is little different in Android, it's not same as Desktop

Desktop | Android
----------|---------
![image](https://github.com/brave/brave-browser/assets/38657976/f5149dd4-9162-4f7b-9603-f9567f96ba61) | ![image](https://github.com/brave/brave-browser/assets/38657976/f40da81a-6a15-4b26-a58e-557238bd8d3f)

cc: @LaurenWags @deeppandya

**Comment by LaurenWags** [comment]
fyi @kjozwiak @vlad-hoff @Uni-verse - 

Per discussion with @Miyayes @sujitacharya2005 @deeppandya the Tablet implementation of the tip banner has been deferred and will be implemented with https://github.com/brave/brave-browser/issues/30371.
