### ISSUE TITLE
Remove or randomize serial numbers from WebUSB-accessible devices

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#28146]
Currently sites can use WebUSB to try and get access to users USB devices.  This is permission gated, so its a rare occurrence on the web, but must happen somewhere.

If you give a site access to a USB device, the site can learn the serial number for that USB device, which in some cases will be a fixed global identifier for your machine.  We should probably remove, randomize or farble these serial numbers.

**Comment by LaurenWags** [comment]
@pes10k @pilgrim-brave could we please get a test plan for this one since it's labeled `QA/Yes`?

Marking as `QA/Blocked` until the above is sorted.

**Comment by pes10k** [comment]
okie i'll add one now, hope to have it done by the all hands

**Comment by pes10k** [comment]
@LaurenWags here ya go https://dev-pages.brave.software/fingerprinting/devices.html (the second test on the page)

**Comment by LaurenWags** [comment]
Thanks for the quick assistance @pes10k!

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.51.79 Chromium: 112.0.5615.49 (Official Build) beta (64-bit)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Windows 11 Version 22H2 (Build 22621.1413)
```

1. Install 1.51.79
2. launch Brave
3. attached/inserted couple of USB devices to the laptop(keyboard and Hard drive)
4. visited https://dev-pages.brave.software/fingerprinting/devices.html in a new tab
5. clicked on Query new device button in the WebUSB Serial number
6. a dialog with list of devices is shown in the URL bar
7. clicked `Unknown device from Chicony Electronics Co., Ltd. and clicked connect
8. device is shown as paired
9. clicked ERGOKEY USB keyboard and clicked connect
10. device is shown as paired
11. However, I got `TypeError: devices is not iterable
12. clicked `Query previously connected devices`


step 6| step 11|
-----|----
<img width="770" alt="image" src="https://user-images.githubusercontent.com/98358127/230680377-0ae7e13c-68c1-450a-b9be-34bdb1b2ffe7.png">
![image](https://user-images.githubusercontent.com/98358127/230679975-9f739dea-9971-47ac-8b15-89ba2aab85cb.png)

**Comment by pes10k** [comment]
This is an issue in the test, not the implementation.  I'll fix the test but what your seeing reflects the feature working as expected. Please do not block QA on this

**Comment by pes10k** [comment]
(btw, the test should be fixed now)

**Comment by MadhaviSeelam** [comment]
@pes10k: thanks for the fix on test site (figured that could be).   However, I have a question on `Disabled` scenario.  Where would I disable them? I see `Blocked` setting but NOT Disable `brave://settings/content/siteDetails?site=https%3A%2F%2Fdev-pages.brave.software.`  Is there a different place where I should be disabling? 

ex|ex|ex
---|---|----
<img width="451" alt="image" src="https://user-images.githubusercontent.com/98358127/230949485-9a835151-b766-408b-8ac4-2714f956ab0c.png">|<img width="458" alt="image" src="https://user-images.githubusercontent.com/98358127/230949557-b585ed96-8a10-4873-a1ac-518d6a1f5117.png">|<img width="454" alt="image" src="https://user-images.githubusercontent.com/98358127/230949646-e48323a0-4fdc-4373-8976-7ab102710a13.png">

**Comment by pes10k** [comment]
@MadhaviSeelam if you want to remove access for these devices to this site, I think the only open you have in the "reset permission" button (or to clear all site storage for the site).

But for the test, by disabled, i mean shields disabled, not the USB devices disabled

**Comment by MadhaviSeelam** [comment]
@pes10k thank you!  Didn't test with `Shields Down` but looked at `Allow Finger printing` while `Shields Up`.  Wasn't sure that was the scenario to be tested.  Now I see `Allow Finger printing` and `Shields Disabled` have same values. 
Please review my verification notes if you don't mind.

**Comment by pes10k** [comment]
That all looks good and correct and expected. Thanks!

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.51.84 Chromium: 112.0.5615.49 (Official Build) beta (x86_64)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | macOS Version 13.4 (Build 22F5027f)

### Case 1: Shields Up (default)
<details>

</details>


### Case 2: Shields Down
<details>

</details>

**Comment by stephendonner** [comment]
Sorry - tried to find a USB device which has/emits a serial #, but out of the only 6 I've tried and found at home so far, none have 🤷‍♂️  - @LaurenWags mind trying?

**Comment by LaurenWags** [comment]
np, will put this on my list for today @stephendonner

**Comment by vlad-hoff** [comment]
Verified on `Google Pixel 6` using version(s):

```
Device/OS: Google Pixel 6 [oriole-user 13 TQ2A.230405.003.E1 release-keys]
Brave build: 1.51.109 Chromium: 113.0.5672.63 (Official Build) (64-bit)
```
---------------------------
<details>
<summary> Shields ON - PASS </summary>

**STEPS:**
1. Launch Brave
2. Connect USB device (I have USB-C earphones) to the phone
3. Open https://dev-pages.brave.software/fingerprinting/devices.html in a new tab
4. Keep the Shields ON in the Shields panel
5. In the "WebUSB Serial Number" section tap on the "Query new device" button
6. Select attached device > Connect
7. In the pop-up message "Allow Brave to access <Device name>?" tap OK
8. Repeat steps 3 - 7, but this time open https://dev-pages.bravesoftware.com/fingerprinting/devices.html

**ACTUAL RESULTS:**
- Verified that the Serial number for the attached device is randomized for both URLs when Shields turned ON

|Device #1|Device #1|Device #2|Device #2|
|-|-|-|-|
| ![1](https://user-images.githubusercontent.com/128532965/235499433-91b581a0-497d-4f8a-8427-79489f13429b.png) | ![2](https://user-images.githubusercontent.com/128532965/235499593-76dc1bd0-4d5f-4c11-a267-31e605a1f06d.png) | ![3](https://user-images.githubusercontent.com/128532965/235499687-1ecb4003-6f05-4643-b177-98e70c9e1ab1.png) | ![4](https://user-images.githubusercontent.com/128532965/235499737-60825102-11d4-41ef-88c1-134fc9d2be56.png) |
</details>

<details>
<summary> Shields OFF - PASS </summary>

**STEPS:**
1. Launch Brave
2. Connect USB device (I have USB-C earphones) to the phone
3. Open https://dev-pages.brave.software/fingerprinting/devices.html in a new tab
4. Turn OFF the Shields in the Shields panel
5. In the "WebUSB Serial Number" section tap on the "Query new device" button
6. Select attached device > Connect
7. In the pop-up message "Allow Brave to access <Device name>?" tap OK
8. Repeat steps 3 - 7, but this time open https://dev-pages.bravesoftware.com/fingerprinting/devices.html

**ACTUAL RESULTS:**
- Verified that the Serial number for the attached device is the same for both URLs when Shields turned OFF

|Device #1|Device #1|Device #2|Device #2|
|-|-|-|-|
| ![1](https://user-images.githubusercontent.com/128532965/235500445-de1b7069-219b-4d44-8c5d-b7071b2d044a.png) | ![2](https://user-images.githubusercontent.com/128532965/235500632-bcba4bb0-6e20-47c0-99e9-765e954963fb.png) | ![3](https://user-images.githubusercontent.com/128532965/235500734-e3087836-dc16-488e-93cb-b722305f7d1b.png) | ![4](https://user-images.githubusercontent.com/128532965/235500759-3fcbed64-09fd-471f-8235-bcbdb189b716.png) |
</details>
