### ISSUE TITLE
`Couldn't contact sync servers` dialog has unnecessary scrollbar

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#2814]
## Steps to Reproduce

1. Create a sync chain and ensure you see two devices
2. Quit Brave
3. Launch Brave without internet
4. Check `Couldn't contact Sync servers` error dialog

## Actual result:

The dialog has a vertical scrollbar
![image](https://user-images.githubusercontent.com/34715963/50667328-f4faff80-0fb8-11e9-8e17-73ffd7116b47.png)

## Expected result:
The dialog does not have a vertical scrollbar

## Reproduces how often: 

always

## Brave version (brave://version info)

Brave | 0.59.14 Chromium: 72.0.3626.28 (Official Build) beta(64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Windows 7

Brave | 0.59.14 Chromium: 72.0.3626.28 (Official Build) beta(64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Linux

cc @brave/legacy_qa @cezaraugusto

**Comment by cezaraugusto** [comment]
thanks @GeetaSarvadnya this was fixed by https://github.com/brave/brave-core/pull/1193 and should be available in the next build

**Comment by rebron** [comment]
@cezaraugusto Fixed in 59.x? Can you set the milestone if so? Thanks.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.59.21 Chromium: 72.0.3626.28 (Official Build) beta(64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Mac OS X

* Verified STR from description
![screen shot 2019-01-14 at 5 44 58 pm](https://user-images.githubusercontent.com/28145373/51146282-642beb80-1824-11e9-9ebe-d6d9049cf24a.png)
