### ISSUE TITLE
Re-enable full screen farbling test

### ISSUE THREAD

**Issue by arthuredelstein** [brave/brave-browser#28155]
We partially disabled screen farbling popup test here: https://github.com/brave/brave-browser/issues/28141

Before rolling out the screen farbling protection, we need to re-enable these tests with a fix so that there are no intermittent failures.

**Comment by kjozwiak** [comment]
Even though the above was merged into the `1.48.x` branch, moving this issue into the `1.49.x` milestone as we didn't have another `1.48.x` release. It was uplifted into `1.49.x` & `1.48.x` via https://github.com/brave/brave-core/pull/17351 & https://github.com/brave/brave-core/pull/17352. We'll be closing/removing the `1.49.x - Release #6` milestone.
