### ISSUE TITLE
Date format for `Estimated Earnings` differs between `brave://rewards` and Rewards panel

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#28156]
## Description 

Date format for `Estimated Earnings` differs between `brave://rewards` and Rewards panel

Spun off from https://github.com/brave/brave-browser/issues/27193

## Steps to Reproduce

   1. install `1.48.148`
   2. launch Brave
   3. set Rewards env. to staging via `QA Preferences`
   4. tap the `BAT` icon
   5. tap `Start using Brave Rewards`
   6. tap `Connect`
   7. tap on `Uphold`
   8. log in
   9. wait
   10. compare the date range format above `Estimated` earnings, between`brave://rewards` and the panel

## Actual result:

It's `Jan 1 - Jan 31` on `brave://rewards`

It's `1 Jan - 31 Jan` on the Rewards panel

example | example
---------|---------
![Screenshot_20230130-212405](https://user-images.githubusercontent.com/387249/215674560-24e6afbe-6a92-4b03-8047-aad099d5eefb.png) | ![Screenshot_20230130-212548](https://user-images.githubusercontent.com/387249/215674568-fe4c9f20-b098-4a7e-8e0c-c1d4084089a6.png)

## Expected result:

Probably should be `Jan 1 - Jan 31`

## Brave version (brave://version info)

`1.48.148`, `Chromium` `109.0.5414.119` on a `Google Pixel XL` (`arm64`) running `Android 9`

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @szilardszaloki @Miyayes @LaurenWags @zenparsing @deeppandya

**Comment by Miyayes** [comment]
May be a localization thing because Deep sees something different. That said, the Rewards page and the Rewards panel should be consistent*.

**Comment by deeppandya** [comment]
@Miyayes this issue is irrelevant after new estimated UI changes. can you confirm ?
