### ISSUE TITLE
Recurring tipping still occurs when Rewards are toggled off

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#2815]
## Description 

If you turn off Rewards via the toggle at the top of brave://rewards page, Recurring tipping can still occur if the table has sites in it. When Rewards are turned off, monthly tipping should not happen.

## Steps to Reproduce

   1. Launch Brave with a fresh profile and `--rewards=reconcile-interval=15`(or a shorter amount of minutes if you can work quickly)
   2. Enable Rewards
   3. Fund your wallet, verify amount displays in browser.
   4. Visit some sites and add them to monthly list
   5. Turn off Rewards with toggle at the top of brave://rewards page
   6. Wait until the reconcile-interval time is met.

## Actual result:

contribution happens

## Expected result:
contribution shouldn't happen

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
Verification passed on 


Brave | 0.58.20 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Windows

- Auto contribution did not went through, when Rewards switch turned off during auto contribution (before the completion of reconcile time interval)
- Verified ac table is not cleared when Rewards switch is off and contribution did not go through
- Verified auto contribution went through when Rewards is turned on
