### ISSUE TITLE
Send V2 Clear Address Field on Selecting Different Token

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#28151]
## Description 

The address field does not get cleared when selecting a different token to send.
This can cause a scenario where the user pastes in a `Ethereum` address and then can switch to send a `Solana` token after address verification, creating a broken transaction in the `Panel`.

## Steps to Reproduce

   1. Go to the send tab, select an `Ethereum` token to send and past in a `Ethereum` address
   2. Switch the send token to a `Solana` token and enter an amount to send
   3. You then are able to click `Review order` which will then create a broken transaction and prevent you from opening the panel.

## Actual result:

https://user-images.githubusercontent.com/40611140/215629624-3888d008-dc7e-44e2-aaf8-70223f3c1179.mov

## Expected result:
We should clear the `Send` field when a user selects a different token to send.

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.48.155` or higher for `1.48.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.48.155 Chromium: 110.0.5481.77 (Official Build) (64-bit) 
-- | --
Revision | `65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}`
OS | Linux

- Verified steps from [brave/brave-core#16929](https://github.com/brave/brave-core/pull/16929)
- Verified Address field is cleared when a new token is selected 
- Verified value is also cleared if set when a new token is selected

https://user-images.githubusercontent.com/17010094/216659939-bd02fa0c-2be1-4249-90f0-613f154a670d.mp4

---------------------

Verification passed on 

Brave | 1.48.155 Chromium: 110.0.5481.77 (Official Build) (64-bit)
-- | --
Revision | `65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#16929](https://github.com/brave/brave-core/pull/16929)
- Verified Address field is cleared when a new token is selected 
- Verified value is also cleared if set when a new token is selected

https://user-images.githubusercontent.com/17010094/216660181-448e5c6a-6707-40c1-b8fb-4ea090969f92.mp4


---------------------

Verification passed on 

Brave | 1.48.155 Chromium: 110.0.5481.77 (Official Build) (arm64)
-- | --
Revision | `65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#16929](https://github.com/brave/brave-core/pull/16929)
- Verified Address field is cleared when a new token is selected 
- Verified value is also cleared if set when a new token is selected

https://user-images.githubusercontent.com/17010094/216660887-6f5b5fb3-fc30-49ad-b11a-9116790c31fd.mov
