### ISSUE TITLE
Rewards panel has too much vertical space between `Connected` and `Your Balance`

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#28157]
## Description 

Rewards panel has too much vertical space between `Connected` and `Your Balance` (thx to @GeetaSarvadnya for the find)

## Steps to reproduce 

1. installed `1.48.148`
2. launched Brave
3. set Brave Rewards env. to staging via QA Preferences
4. tap on BAT icon
5. tap Start using Brave Rewards
6. tap Connect
7. tapped on Uphold
8. logged in to Uphold
9. looked at the vertical space between `Connected` and `Your Balance`

## Actual result 

`brave://rewards` | `Rewards panel`
------------------|-----------------
![Screenshot_20230130-212405](https://user-images.githubusercontent.com/387249/215678445-e5384ba2-2dc4-4298-be18-3418cc7c2829.png) |  ![Screenshot_20230130-212548](https://user-images.githubusercontent.com/387249/215678540-600f06bd-db7b-4f30-a72d-ba6b22634cd5.png)

## Expected result

Should look closer to `brave://rewards`

## Issue reproduces how often 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): `arm64`
   - Device type (Phone, Tablet, Phablet): `Google Pixel XL`
   - Android version: `9`
   
## Brave version

`1.48.148`, `Chromium 109.0.5414.119`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc @deeppandya @zenparsing @Miyayes @LaurenWags @Uni-verse @GeetaSarvadnya

**Comment by deeppandya** [comment]
@stephendonner the date format in android matches with desktop panel. In this case, regards page needs updating.

**Comment by stephendonner** [comment]
> @stephendonner the date format in android matches with desktop panel. In this case, regards page needs updating.

@deeppandya did you mean that comment for https://github.com/brave/brave-browser/issues/27193, instead?

**Comment by deeppandya** [comment]
> > @stephendonner the date format in android matches with desktop panel. In this case, regards page needs updating.
> 
> @deeppandya did you mean that comment for https://github.com/brave/brave-browser/issues/27193, instead?

And we agreed on the formatting on rewards panel so it's correct. CC @Miyayes

**Comment by stephendonner** [comment]
This is a duplicate of https://github.com/brave/brave-browser/issues/28157.
