### ISSUE TITLE
Vertical Tab Question and Vision for Brave

### ISSUE THREAD

**Issue by thorrrr** [brave/brave-browser#28168]
HI
I have searched on here and there is a sea of noise and many many tickets that it is hard to know what is what.
I don't want to add another ticket to the mass there is already.

I was happy that vertical tabs were introduced but IMHO what started good has turned to bad.
The functionality is going backwards (or it could be the dev testing different versions)

The concept of pinned tabs sticking horizontal is 100% counter intuitive it creates more effort from a user with double mouse gestures (mouse over to expand collapse then the pinned you hover over shoots up to the top).

So you may ask why not just click it in collapse the answer is easy you only show 2  pinned tabs in collapse! 
Sometimes i get 3 then 2 then 4 no idea why as i have 5!
That makes no logical sense , why hide icons in collapse?

Then we have the poorly designed folder that disappears on collapse
If you leave them open then the text is cut off?

You have missing tabs that are open but not showing ?

Search Tabs text is cutoff !

Pinned tabs should not be horizontal on a laptop i may as well go back to horizontal. The whole idea is screen real-estate for laptop the collapse function i hope is still being perfected. You could easily css style pinned with like a faint box round the icon or something like that.

I would expect what i have open in expand i can see in collapse why remove 4 items ?

My main query is i know we are in beta but is there a vision on how this is going to look and work?

I have tried Stable Beta and Nightly on different machines but we seem 2 steps forward 5 steps back.
That is no offence to the dev but more likely no concrete plan on the design outcome from Brave.

The number of tickets just on this is ridiculous and the dev must be bouncing all over the place.
On one place ticket with vision and roll out would be easier for everybody. 

![expanded showing open items](https://user-images.githubusercontent.com/8
![SearchTabsTextError](https://user-images.githubusercontent.com/8170673/215743310-2e08d20e-a6aa-460d-acf6-87b13ce9e9cb.png)
170673/215743284-3c4a2d74-4ad7-4fbc-82f8-c5d98c0715e5.png)

![missing item in collapse](https://user-images.githubusercontent.com/8170673/215745108-f1f7ec81-12e7-4522-96ba-6630f1f7403f.png)
![expanded showing open items](https://user-images.githubusercontent.com/8170673/215745154-33295e0f-dbad-4f70-b5c4-e485bbb11395.png)

I use mainly Beta [Version 1.48.141 Chromium: 109.0.5414.119 (Official Build) beta (64-bit)](https://brave.com/latest/)
The nightly is currently broken but i think you have a fix due out .

**Comment by cjwijtmans** [comment]
howdid you even get the vertical tabs to work? it doesnt appear for me but rather makes the interface bug out. And the way it works on edge is fine.

**Comment by rebron** [comment]
Hi @thorrrr. We're in active development on vertical tabs so you'll want to check out the progress in Nightly and not what's in beta. Tab search UX will be fixed and some of the UX issues you're encountering with pinned tabs and groups we're aware. 

Great feedback.

**Comment by bsclifton** [comment]
@cjwijtmans you can enable vertical tabs with brave://flags/#brave-vertical-tabs - after enabling, I think you need to restart. Then you can right click any of the tab interface and pick `Use vertical tabs`
![image](https://user-images.githubusercontent.com/4733304/222350513-eb594f0f-5451-4b4e-872c-b9c27b6f1f44.png)

**Comment by bsclifton** [comment]
I'm going to close the issue for now - but thanks for reporting @thorrrr 

You're right - @sangwoo108 is bouncing around with lots of fixes, but you should notice things getting much smoother 😄 

You can see a list of open issues here:
https://github.com/brave/brave-browser/labels/feature%2Fvertical-tabs

If there are some specific ones not logged yet, can you please let me know and I'll get an issue created for each specific problem? Thanks!
