### ISSUE TITLE
Sync: failed DCHECK when delete device record arrives twice

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#2817]
## Description 

If two delete device records arrives to sync service, there is a failed DCHECK
```
[83053:775:0103/160933.609992:FATAL:sync_devices.cc(175)] Check failed: existing_it != std::end(devices_).
```
https://github.com/brave/brave-core/pull/1193#issuecomment-451308001

## Steps to Reproduce

No steps to reproduce for QA, because this appears on debug builds only.
Could be reproduced with a related PR unit-test.

## Brave version (brave://version info)

Version 0.61.0 Chromium: 72.0.3626.28 (Developer Build) (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
no

**Comment by AlexeyBarabash** [comment]
@kjozwiak correct, this issue cannot negatively affect users on production, this appears only in debug builds. 
This is not going to cause issues when users are removing devices.

**Comment by AlexeyBarabash** [comment]
Closed with https://github.com/brave/brave-core/pull/1125 .

**Comment by rebron** [comment]
@AlexeyBarabash can you set the right milestone for this?

**Comment by kjozwiak** [comment]
https://github.com/brave/brave-core/pull/1125 should also have a milestone 👍

**Comment by AlexeyBarabash** [comment]
Thanks @rebron @kjozwiak , just had set the correct milestones.
