### ISSUE TITLE
Cleanup Brave Ads tokens/wallet

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#28172]

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.50.93 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/16958

<details>



</details>
