### ISSUE TITLE
Migrate `RequestTracker` and associate code to `WTF::String`

### ISSUE THREAD

**Issue by cdesouza-chromium** [brave/brave-browser#28185]
Following changes done upstream, and in preparation for `cr111`, `RequestTracker` should have its strings used to express `resource_type` migrated to `WTF::String`.

**Comment by LaurenWags** [comment]
@cdesouza-chromium does this need manual QA? I've labelled as `QA/No` and `release-notes/exclude` but if either of these labels are incorrect please advise, thanks.

**Comment by cdesouza-chromium** [comment]
You've labelled it correctly. Cheers.
