### ISSUE TITLE
Twitter link doesn't work

### ISSUE THREAD

**Issue by A-t-s-u-s-h-i** [brave/brave-browser#28184]
## Description 

A user reported that it would be an error page(please see the attachment) if he click the twitter link like [this](https://twitter.com/i/redirect?url=https%3A%2F%2Ftwitter.com%2Fmask_3dcg%2Fstatus%2F1617094871818596354%3Fcn%3DZmxleGlibGVfcmVjcw%253D%253D%26refsrc%3Demail&t=1+1674400145805&cn=ZmxleGlibGVfcmVjcw%3D%3D&sig=5d71ce9ef69b11a9f5e9ad0489166c17e89947ce&iid=93b0f359fc6f4fe795753cb5475c6801&uid=1360753837754048512&nid=244+276893697). It’s solved by disabling Shields. But I would like to avoid replying like “Please access Twitter without Shields”. I hope we can find any solution for that.

Related issue: #26756

## Steps to Reproduce
   1. copy&paste twitter URL that has `t` parameter

## Actual result:

<img width="828" alt="スクリーンショット 2023-02-01 14 39 08" src="https://user-images.githubusercontent.com/79502386/215960737-7ff59cc2-f96d-426c-b50c-47b9573b1763.png">

## Expected result:
Twitter page will be shown.

## Reproduces how often: 
Easily reproduced

## Desktop Brave version:
1.47.186

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
yes
- Can you reproduce this issue with the beta channel? 
yes
- Can you reproduce this issue with the nightly channel? 
yes
## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
yes

**Comment by fmarier** [comment]
There are a few query string parameters in the [sample URL](https://twitter.com/i/redirect?url=https%3A%2F%2Ftwitter.com%2Fmask_3dcg%2Fstatus%2F1617094871818596354%3Fcn%3DZmxleGlibGVfcmVjcw%253D%253D%26refsrc%3Demail&t=1+1674400145805&cn=ZmxleGlibGVfcmVjcw%3D%3D&sig=5d71ce9ef69b11a9f5e9ad0489166c17e89947ce&iid=93b0f359fc6f4fe795753cb5475c6801&uid=1360753837754048512&nid=244+276893697):
- `t`
- `cn`
- `sig`
- `iid`
- `uid`
- `nid`

With the exception of `cn`, all of these are required for the redirect to work.

**Comment by kjozwiak** [comment]
The above requires `1.48.157` for `1.48.x` verification 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 13` using the following build(s):

```
Brave | 1.48.155 Chromium: 110.0.5481.77 (Official Build) (32-bit)
--- | ---
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | Android 13; Build/TQ1A.230105.002
```

Using the STR/Cases outlined via https://github.com/brave/brave-core/pull/16968#issue-1566888954, ensured that loading the following URL within a new tab correctly loaded the Twitter page rather than displaying an error as per the following:

```
https://twitter.com/i/redirect?url=https%3A%2F%2Ftwitter.com%2Fmask_3dcg%2Fstatus%2F1617094871818596354%3Fcn%3DZmxleGlibGVfcmVjcw%253D%253D%26refsrc%3Demail&t=1+1674400145805&cn=ZmxleGlibGVfcmVjcw%3D%3D&sig=5d71ce9ef69b11a9f5e9ad0489166c17e89947ce&iid=93b0f359fc6f4fe795753cb5475c6801&uid=1360753837754048512&nid=244+276893697
```

![image](https://user-images.githubusercontent.com/2602313/217106971-a30dc657-9b5d-4d21-8270-ca8b19c66b0b.png)

```
https://twitter.com/mask_3dcg/status/1617094871818596354?cn=ZmxleGlibGVfcmVjcw%3D%3D&refsrc=email
```

**Comment by LightColoredLines** [comment]
Hello. i still can't get Twitter to work on Brave since yesterday.
I'm using Arch Linux.
Brave version: [Version 1.48.158 Chromium: 110.0.5481.77 (Official Build) (64-bit)]
![twitter](https://user-images.githubusercontent.com/10070295/217742538-20fce288-189f-49f2-ba5f-33a3ade336b3.png)

**Comment by fmarier** [comment]
@LightColoredLines Twitter has been having lots of outages / problems lately (on their end). Try clearing your cookies and then accessing Twitter again.

**Comment by LightColoredLines** [comment]
> @LightColoredLines Twitter has been having lots of outages / problems lately (on their end). Try clearing your cookies and then accessing Twitter again.

i already clear the cookies with All time option. still can't access it.
![twitbrave](https://user-images.githubusercontent.com/10070295/218004345-a841c71b-9706-4deb-b03c-451f55550548.png)

**Comment by fmarier** [comment]
@LightColoredLines Thanks for trying that. Would you mind filing a new GitHub issue so that we can investigate? It's unlikely to be related to this problem since you're running the version with our fix.

**Comment by LightColoredLines** [comment]
> @LightColoredLines Thanks for trying that. Would you mind filing a new GitHub issue so that we can investigate? It's unlikely to be related to this problem since you're running the version with our fix.

i have created the issue. #28459

**Comment by fmarier** [comment]
Thanks @LightColoredLines
