### ISSUE TITLE
QR Code/Code words disappears when adding a second device to the sync chain

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#2818]
## Description 

QR Code/Code words disappears when adding a second device to the sync chain

## Steps to Reproduce

   1. Enable Sync chain on bc
   2. Scan QR code/ add code words on device 2
   3. QR code/words magically disappear on device 1 but sync chain is successfully created

## Actual result:

QR Code/Code words disappears when adding a second device to the sync chain

## Expected result:
No black magic should happen for sync

## Reproduces how often: 

Intermittent issue. Happened once for me but not again. @LaurenWags mentioned she also saw this issue so she can add more notes on how she saw it

## Brave version (brave://version info)

Brave | 0.59.14 Chromium: 72.0.3626.28 (Official Build) beta(64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | All

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
N./A
- Is the issue reproducible on the latest version of Chrome? 
N/A

### Additional Information

cc: @LaurenWags to add her scenario of this black magic

**Comment by LaurenWags** [comment]
I've experienced disappearing code words when macOS was device 1 and device 2 was linux VM. I haven't gotten it to happen consistently, but I've seen it twice using the STR in the description.
