### ISSUE TITLE
Country flag is not visible from VPN main panel

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#28181]
## Steps to Reproduce

   1. Enable VPN and setup to purchased state
   2. Launch VPN panel
   3. Check country flag is shown

## Actual result:

Only string is shown

<img width="344" alt="Screenshot 2023-02-01 at 2 28 06 PM" src="https://user-images.githubusercontent.com/6786187/215959543-c412fd0e-0b80-44b0-85e6-fce5b5804f6e.png">

## Expected result:
<img width="341" alt="image" src="https://user-images.githubusercontent.com/6786187/215959588-d0913d81-1a03-4e2e-bc65-5fd9c693d461.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

`Version 1.49.78 Chromium: 110.0.5481.52 (Official Build) nightly (x86_64)`

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.48.157` or higher for `1.48.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.48.157 Chromium: 110.0.5481.77 (Official Build) (64-bit)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | Windows 11 Version 21H2 (Build 22000.1455)
```

Verified in 1.49.79 using original STR

<img width="359" alt="image" src="https://user-images.githubusercontent.com/98358127/217039705-bfc60b73-a1bb-4a90-a4c8-01cab15c8658.png">

Install 1.48.157
launch Brave
complete purchase to setup VPN
click VPN panel
verified country flags for US & Japan

#### Confirmed country flag is shown 

Example | Example | Example
---- | ---- | ----
<img width="959" alt="image" src="https://user-images.githubusercontent.com/98358127/217036038-e4ebc06a-2b04-4ea4-a0a6-c88de550bf11.png">|<img width="954" alt="image" src="https://user-images.githubusercontent.com/98358127/217036124-e4b36ae2-e0a9-4eed-b592-dd98528713cf.png">|<img width="462" alt="image" src="https://user-images.githubusercontent.com/98358127/217041091-f2c064a6-0378-4dd4-8ea0-e0150344c6d9.png">
