### ISSUE TITLE
Refactor blink's `RequestTracker`/`ScriptTracker` to use WTF containers

### ISSUE THREAD

**Issue by cdesouza-chromium** [brave/brave-browser#28183]
Due to upstream compile time checks to land on `cr111`, it is necessary to refactor blink code that use std containers to use their corresponding WTF incarnations.

**Comment by LaurenWags** [comment]
@cdesouza-chromium does this need manual QA? I've labelled as `QA/No` and `release-notes/exclude` but if either of these labels are incorrect please advise, thanks.
