### ISSUE TITLE
Ad user model is not allowed to classify pages with certain common caching directives

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-browser#2819]
## Description 
Currently the ads user model will refuse to classify any pages that have "private" set in the cache header.  However, according to the spec, private still means that "A private (non-shared) cache MAY cache the response."  The cache used in the user modeling is of course not shared and remains private.  Furthermore, this prevents us from classifying pages like cnet.com, reddit.com and mashable.com who appear to use the private cache headers simply to indicate that this page may look different for different users.  Therefore, we should allow the ad user model to classify pages with "private" in the cache header.  We should, of course, continue to respect a "no-store" when we receive it and not use any of that in the user model.

## Steps to Reproduce

   1. Go to this page: https://www.cnet.com/news/brave-is-default-browser-on-obscure-htc-crypto-phone/
   2. Examine ad logs

## Actual result:
You will see no "immediateWinner" 

## Expected result:
Log should show an immediateWinner for that page.

## Reproduces how often: 
Easily reproduced

**Comment by jsecretan** [comment]
Per @bridiver change is quick: https://github.com/brave/brave-core/blob/master/components/brave_ads/browser/ads_tab_helper.cc#L63

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.60.26 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Mac OS X

* Launched Brave with `--enable-logging=stderr --vmodule=brave_ads=3 --log-level=0 --brave-ads-debug --brave-ads-testing`. Navigated to some sites and then visited the site from description. Saw this `[51726:775:0212/182438.830276:INFO:ads_impl.cc(381)] Site visited https://www.cnet.com/news/brave-is-default-browser-on-obscure-htc-crypto-phone/, immediateWinner is technology & computing-technology & computing and winnerOverTime is travel-travel` in the logs. `immediateWinner` seems correct for this page. Tried with some other sites as listed in https://github.com/brave/brave-core/pull/1226 as well and got similar results:
`[51726:775:0212/182920.679102:INFO:ads_impl.cc(381)] Site visited https://www.reddit.com/r/BATproject, immediateWinner is technology & computing-technology & computing and winnerOverTime is technology & computing-technology & computing`
`[51726:775:0212/183108.209610:INFO:ads_impl.cc(381)] Site visited https://mashable.com/video/pixar-purl-short/#N73TQ1TolEqt, immediateWinner is arts & entertainment-celebrities and winnerOverTime is technology & computing-technology & computing`
