### ISSUE TITLE
sometimes red or orange colored URLs appear in URL bar

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#28198]
## Description 

See the following slack threads:
- https://bravesoftware.slack.com/archives/C7VLGSR55/p1671131140554189
- https://bravesoftware.slack.com/archives/C07HD31EZ/p1675190310035719

Sometimes red or orange colored URLs display in the URL bar.

## Steps to Reproduce

   1. Clean profile with C109 build, close/relaunch to pull griffin (not sure if necessary, but that's what I did)
   2. Navigated to github.com/brave/brave-core/commits
   3. Open brave://settings/appearance and enabled `Always show full URLs` (toggled it on, off and on again)
   4. Enabled `Autocomplete searches and URLs` under brave://settings/privacy
   5. Opened a new tab, typed "core" into URL bar and selected github.com/brave/brave-core/commits to navigate to it
   6. Opened another new tab, typed "core" --> saw red/orange URL in URL bar

## Actual result:

some URLs are red/orange, additional examples in slack threads above

<img width="1361" alt="Screen Shot 2023-02-01 at 7 14 03 AM" src="https://user-images.githubusercontent.com/28145373/216040733-08015706-620e-42f1-be27-7ca04d4feeee.png">

## Expected result:

normal color I guess

## Reproduces how often: 

easily

## Brave version (brave://version info)

```
Brave | 1.47.186 Chromium: 109.0.5414.119 (Official Build) (x86_64)
-- | --
Revision | 772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}
OS | macOS Version 12.6.3 (Build 21G419)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes 1.47.x
- Can you reproduce this issue with the beta channel? yes 1.48.x
- Can you reproduce this issue with the nightly channel? unsure, probably yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? yes, per https://bravesoftware.slack.com/archives/C7VLGSR55/p1671133807630169?thread_ts=1671131140.554189&cid=C7VLGSR55 same thing, but blue instead of red/orange

## Miscellaneous Information:

cc @brave/qa-team

**Comment by wknapik** [comment]
The issue here is that hits in red can't be edited. They can either be used as they are, or not at all.

**Comment by vrindavan** [comment]
What even is this? Any idea?

**Comment by stephendonner** [comment]
> What even is this? Any idea?

I don't think we've figured it out, yet - it's perplexed us, too, so far!

**Comment by rebron** [comment]
I was able to reproduce following the str. Selecting x for the entry in the url bar, I can't get it come back again.

**Comment by markg85** [comment]
As per the above. Disabling it is possible! (just disabled it here locally)
`chrome://flags/#omnibox-rich-autocompletion-promising`

For the brave devs. Can we please have this feature disabled **by default**?

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.54.90 Chromium: 115.0.5790.56 (Official Build) beta (x86_64)
-- | --
Revision | ebcfb87c1393f36955cfa2f6451a1767e3dc3ee5-refs/branch-heads/5790@{#1193}
OS | macOS Version 11.7.8 (Build 20G1351)

### First, easily reproduced this using `1.47.186`:

<img width="1599" alt="Screen Shot 2023-07-03 at 11 01 28 PM" src="https://github.com/brave/brave-browser/assets/387249/ea12d96c-0604-47df-bf7e-3f954742bbe0">
