### ISSUE TITLE
Support `$match-case` option for adblock filters

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#28194]
Brave's default lists include several `$match-case` regex filters; the option should be supported by Brave Shields for better compatibility.

## Test Plan:

Add the following to `brave://settings/shields/filters`:

```adblock
/^https?:\/\/cdn\.[a-z]{4,6}\.xyz\/test\.json/$3p,match-case
```

Visit https://example.com, open the DevTools panel, and paste each of the following lines into the console:

```js
await fetch('https://cdn.abcdef.xyz/test.json');
```

```js
await fetch('https://cdn.abcdef.xyz/TEST.JSON');
```

Without the fix, both will produce a `net::ERR_BLOCKED_BY_CLIENT` error.

With the fix, the _second_ script should instead produce a `net::ERR_NAME_NOT_RESOLVED` error.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.49.90 Chromium: 110.0.5481.77 (Official Build) beta (64-bit)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | Windows 11 Version 21H2 (Build 22000.1455)
```

1. Install 1.49.90
2. launch Brave
3. open a new-tab page
4. open `brave://settings/shields/filters`
      - `/^https?:\/\/cdn\.[a-z]{4,6}\.xyz\/test\.json/$3p,match-case`
5. click `Save Changes` 
6. visit https://example.com/ in a new tab
7. open the DevTools panel, and paste each of the following lines separately  into the console:
      - `await fetch('https://cdn.abcdef.xyz/test.json');`
      - `await fetch('https://cdn.abcdef.xyz/TEST.JSON');`




before fix (1.48.158)  |step 5-6|step 8a|step 8b
---- | --- | --- | ---
<img width="958" alt="image" src="https://user-images.githubusercontent.com/98358127/217662909-01771286-19d5-477c-9b4b-ea987cc162cd.png">|<img width="941" alt="image" src="https://user-images.githubusercontent.com/98358127/217661015-b14071f0-90db-4ab2-a517-0323de6c440f.png">|<img width="955" alt="image" src="https://user-images.githubusercontent.com/98358127/217661511-503cb6b3-e59b-4be5-bbc3-bfc48582095e.png">|<img width="957" alt="image" src="https://user-images.githubusercontent.com/98358127/217661570-61da24be-9e0b-4c16-b530-0ee1fb1a9895.png">

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.49.96 Chromium: 110.0.5481.77 (Official Build) beta (x86_64)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | macOS Version 11.7.3 (Build 20G1116)

### Steps:
1. installed `1.49.96`
2. launched Brave
3. opened a new-tab page
4. opened `brave://settings/shields/filters`
5. added the following in the `Create custom filters` text box
`/^https?:\/\/cdn\.[a-z]{4,6}\.xyz\/test\.json/$3p,match-case`
6. clicked `Save changes`
7. visit `https://example.com/` in a new tab
8. open the DevTools panel, and paste each of the following lines separately into the console:
`await fetch('https://cdn.abcdef.xyz/test.json');`
`await fetch('https://cdn.abcdef.xyz/TEST.JSON');`

#### Confirmed second script (`await fetch('https://cdn.abcdef.xyz/TEST.JSON';)` produced `net::ERR_NAME_NOT_RESOLVED` error.

steps 5-6 | step 8a | step 8b
----------|---------|--------
<img width="1491" alt="Screen Shot 2023-02-13 at 10 00 24 AM" src="https://user-images.githubusercontent.com/387249/218537025-ee5dd4cc-df6b-4dcf-8ab7-cd295d199dc5.png"> | <img width="1491" alt="Screen Shot 2023-02-13 at 10 04 48 AM" src="https://user-images.githubusercontent.com/387249/218537225-66ebc19e-6ac1-4d6d-a126-03c108034714.png"> | <img width="1491" alt="Screen Shot 2023-02-13 at 10 02 27 AM" src="https://user-images.githubusercontent.com/387249/218537072-c9e75c89-046c-4e5c-8055-d39314a8d6d9.png">

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.49.114 Chromium: 110.0.5481.177 (Official Build) beta (64-bit) 
Revision	f34f7ab2d4ca4ad498ef42aeba4f4eb2c1392d63-refs/branch-heads/5481@{#1239}
OS	Linux
```

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Samsung Galaxy version 12` running `Bravemonoarm65.apk_1.49.118`

Verified test plan from https://github.com/brave/brave-browser/issues/28194#issue-1565777764.

Reproduced the issue using 1.48.171.

1.48.171 | brave://settings/shields/filters | 1.49.118
---- | ---- | ----
![image](https://user-images.githubusercontent.com/38657976/223421531-aad8b6fa-95ba-48d4-8c9b-1e65229747a9.png) | ![Screenshot_20230307-175313_Brave](https://user-images.githubusercontent.com/38657976/223421632-99c1fb10-c068-4731-ae17-d65c3d608836.jpg) | ![image](https://user-images.githubusercontent.com/38657976/223422368-382abb2e-1f86-400e-b479-10bde134679d.png)
