### ISSUE TITLE
Transaction submitted image is blurry

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#28201]
## Description 

See screenshot. This issue has been brought up a few times. 
![transaction submitted screen](https://user-images.githubusercontent.com/12224304/216066602-9dcd4c18-0496-403e-9ee7-c5849fd9f2b4.png)

## Steps to Reproduce

   1. Try sending a transaction on desktop
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by Douglashdaniel** [comment]
Closing as `duplicate` since was fixed in https://github.com/brave/brave-core/pull/16387
