### ISSUE TITLE
Remove the use of `std::vector` from brave's blink code

### ISSUE THREAD

**Issue by cdesouza-chromium** [brave/brave-browser#28200]
Addressing upcoming breaking changes upstream for `cr111`, we should remove any remaining uses of `std::vector` from blink code.

    Chromium change:
    https://chromium.googlesource.com/chromium/src/+/52472aba170b71f97ae9ab17f429ff494537adae
    
    commit 52472aba170b71f97ae9ab17f429ff494537adae
    Author: Xianzhu Wang <wangxianzhu@chromium.org>
    Date:   Mon Jan 9 20:26:58 2023 +0000
    
        Enable discouraged type check for data members under blink/renderer
    
        For existing usages of discouraged type:
        - Simple cases are changed to use blink types;
        - For other cases, ALLOW_DISCOURAGED_TYPE(reason) is added.
    
        Rules audit_non_blink_usages.py checking such usages are removed.
        We'll use the clang plugin from now on.
    
        Bug: 1363780

**Comment by LaurenWags** [comment]
@cdesouza-chromium does this need manual QA? I've labelled as `QA/No` and `release-notes/exclude` but if either of these labels are incorrect please advise, thanks.

**Comment by cdesouza-chromium** [comment]
You've labelled it correctly. Cheers.
