### ISSUE TITLE
Use BalanceScanner contracts for ETH asset discovery

### ISSUE THREAD

**Issue by nvonpentz** [brave/brave-browser#28203]
Depends on https://github.com/brave/brave-browser/issues/28204.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.50.94 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from [brave/brave-core#17049](https://github.com/brave/brave-core/pull/17049)
- Verified restoring an account with token balance via seed phrase, auto-populates all the tokens with balance
- Verified sending a token to an account which doesn't have the balance, lists the token and shows the balance

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.50.93 x64 build
- Verified steps from [brave/brave-core#17049](https://github.com/brave/brave-core/pull/17049)
- Verified restoring an account with token balance via seed phrase, auto-populates all the tokens with balance
- Verified sending a token to an account which doesn't have the balance, lists the token and shows the balance
