### ISSUE TITLE
Registry fix to address file type associations from Muon

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#2821]
## Description 

Setting Brave as a default program for [some] file types produces inconsistent results at best. Opening hyperlinks, for example, generally works, but I've had users report that even that wouldn't always take.

This applies to any way in which file type associations are made:

1. Via reg/command line args
2. `Open With...` --> `Always open...` from context menu
3. `System Settings --> Choose a default app for each type of file`

## Steps to Reproduce

   1. Use any method to associate a file type/extension (`.jpg`, `.html`, `.tiff`, etc) with Brave.
   2. Test the association by opening a file of the appropriate type

## Actual result:

Sometimes works, sometimes doesn't - very inconsistent.

## Expected result:
File type opens in Brave as long as it's capable of doing so.

## Reproduces how often: 

Inconsistently, but often enough that you should be able to reproduce this after a few tries/file types

## Brave version (brave://version info)

Brave Release channel build v0.58.18
Win10 x64

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes

### Additional Information

Report from user with additional details and test methods:
https://community.brave.com/t/file-extensions-wont-associate-with-brave/39034

**Comment by Brave-Matt** [comment]
A few +1's from Reddit:
https://www.reddit.com/r/brave_browser/comments/a671rj/brave_wont_open_links_as_default_browser/

**Comment by SteveTKD64** [comment]
Additional information: This started occuring after I upgraded from the Muon-based Brave to the new Chromium-based Brave.

**Comment by rebron** [comment]
@Brave-Matt Give me a clearer more, specific use case so we can reproduce the issue. I know the intermittent part is difficult but that's why we need specific steps to reproduce.

**Comment by lucazertyui** [comment]
Hi,
I had the same issue on Windows 7 (64 bits) 
As explained `[here](https://www.reddit.com/r/brave_browser/comments/adg3jo/open_a_link_from_outlook_not_forwarded_to_brave/)`, for me the problem was that the value of BraveHTML in Windows Registry (HKEY_CLASSES_ROOT\BraveHTML\shell\open\command) did not match brave.exe location
I change the value and now everything works !

**Comment by SteveTKD64** [comment]
@lucazertyui modifying the registry key value at this location has fixed the problem for me too, thanks! 

It was pointing at "C:\Users\myuser\AppData\Local\Brave\Brave.exe" -- "%1" which must have been the path to the legacy Muon-based Brave installation. 

I've now modified the path to "C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" -- "%1" and it works.

**Comment by LukasGI** [comment]
> @lucazertyui modifying the registry key value at this location has fixed the problem for me too, thanks!
> 
> It was pointing at "C:\Users\myuser\AppData\Local\Brave\Brave.exe" -- "%1" which must have been the path to the legacy Muon-based Brave installation.
> 
> I've now modified the path to "C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" -- "%1" and it works.

This fixed same problem here. Thanks a lot :-)

**Comment by deoxal** [comment]
@lucazertyui I am rejoicing right now. Any idea how to automatically update the icons? If not I can set them manually. For some reason .pdf now has the Brave icon, but .html and others still have the default icon.

**Comment by Brave-Matt** [comment]
+1 from Community:
https://community.brave.com/t/cannot-open-dropbox-file-from-email-link-if-brave-is-default-browser/43536/5

**Comment by rebron** [comment]
cc: @kjozwiak to check

**Comment by Brave-Matt** [comment]
https://community.brave.com/t/file-type-associations-are-unreliable-in-windows/53706/33

**Comment by rebron** [comment]
@Brave-Matt @bsclifton Should we rename this issue to "Registry fix to address file type associations from Muon"? Does that sound right? Looks like we need to do the same registry fix that IE is doing.

**Comment by Brave-Matt** [comment]
@rebron sounds good to me. Lots of happy users with this fix.

**Comment by bsclifton** [comment]
@rebron I would definitely support that! The fix would be easy enough

**Comment by silverlight513** [comment]
I've just updated brave to `Version 1.4.95 Chromium: 80.0.3987.122 (Official Build) (64-bit)` on OSX 10.14.6 and brave will not open links from other apps anymore. Clicking links opens brave but brave seems to do nothing at all

**Comment by bsclifton** [comment]
@silverlight513 weird- definitely not related to this issue, as this issue covers a specific Windows problem

Would you please be able to create a new issue covering that problem?

**Comment by silverlight513** [comment]
@bsclifton Sorry, I was following some links that lead me here. Should have read the ticket in more detail.

I'm not sure that's the same bug. I can still use brave as intended unless I try to open a link from another app.

I'll go make a new ticket now
