### ISSUE TITLE
[Android] Fix spelling error "Accourding" in Limited functionality toast notification

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#28215]
## Description

![image](https://user-images.githubusercontent.com/11497541/216153030-027c4f20-9d54-415f-bc72-62a0a91c7289.png)

Fix "Accourding".

From: https://github.com/brave/brave-browser/issues/27743#issuecomment-1412046688 

cc: @LaurenWags

**Comment by Miyayes** [comment]
I wonder if we can get this into 1.49.x since it's still early in that cycle, and this is actually a pretty common/visible toast notification for users.

**Comment by kjozwiak** [comment]
The above requires `1.49.92` or higher for `1.49.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Samsung Galaxy version 12` running `Bravemonoarm64.apk_1.49.116`

- Verified the steps from https://github.com/brave/brave-browser/issues/27743#issuecomment-1412046688 and ensured that the text `Accourding` is changed to `Accoarding` in the BR panel  toast notification

Light mode | Dark mode
-------------|------------
![Screenshot_20230303-133849_Brave - Beta](https://user-images.githubusercontent.com/38657976/222667039-ccc10ac3-718a-41bd-b30e-719b0c793f63.jpg) | ![Screenshot_20230303-134002_Brave - Beta](https://user-images.githubusercontent.com/38657976/222667052-b7ac2bc2-9286-450e-86a6-bf397c8dbfff.jpg)
