### ISSUE TITLE
Brave Mac crashed on startup

### ISSUE THREAD

**Issue by demo308** [brave/brave-browser#28224]
## Description 

Brave Browser will crash when I do it like opening the app

## Steps to Reproduce

   1.  going to terminal
   2.  clearing tor
   3.  might work but no

## Actual result:

https://youtu.be/cvAk3sSl3RE
## Expected result:
Opening

## Version/Channel Information:
 no

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the nightly channel? no

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? no

## Miscellaneous Information:

 I forgot my brave version

**Comment by demo308** [comment]
> HELP ME

**Comment by rebron** [comment]
Hi @demo308. Can you go to your Applications and select the Brave application and hit Command + I to get the version information.

**Comment by demo308** [comment]
> Hi @demo308. Can you go to your Applications and select the Brave application and hit Command + I to get the version information.

109.1.47.186

**Comment by matthewwong525** [comment]
I'm experiencing crash on open for the beta / nightly versions 109.1.48.151 of brave

**Comment by demo308** [comment]
I dont understand i have public version

**Comment by demo308** [comment]
PLEASE HELP

**Comment by demo308** [comment]
i need help

**Comment by iefremov** [comment]
@demo308 can you try reinstalling brave?

**Comment by demo308** [comment]
Will it save my local data

**Comment by iefremov** [comment]
stale
