### ISSUE TITLE
onboarding in Japan region shows auto contribution slide

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#28221]
## Description 

When you select "Japan" as the country for Rewards, there should not be a slide in onboarding that describes Auto Contribution.

This works as expected on desktop.

## Steps to reproduce 

   1. Have device set to US (or non Japan region)
   2. Install 1.48.x
   3. Select Japan as the country
   4. Go through onboarding

## Actual result 

below slide should not be part of onboarding:

![Screenshot_20230201-164420](https://user-images.githubusercontent.com/28145373/216172125-a11aceeb-a6af-4735-8afa-e1af062eae6e.png)

## Expected result

No AC slide in onboarding

## Issue reproduces how often 

easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? yes
- Can you reproduce this issue with the current Play Store Nightly version? likely

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): all
   - Android version: all
   
## Brave version
1.48.152

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc @Miyayes @deeppandya @brave/qa-team

**Comment by Miyayes** [comment]
Applies to new users whose Android device locale == not-JP, but then declares Japan.

**Comment by Miyayes** [comment]
Target 1.48.x maintenance release

**Comment by kjozwiak** [comment]
The above requires `1.48.161` or higher for `1.48.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung GS 21` using version:

```
Brave	1.48.166 Chromium: 110.0.5481.100 (Official Build) (64-bit) 
Revision	4be7a36f7cb943af6118e449bbab494b43dcaddd-refs/branch-heads/5481_77@{#14}
OS	Android 13; Build/TP1A.220624.014
```
STR: https://github.com/brave/brave-browser/issues/28221#issue-1566893179

- Ensured that auto contribution slide is not displayed in the quick tour upon joining rewards for Japan 

Example | Example | Example
-|-|-
![screenshot-1676650490264](https://user-images.githubusercontent.com/17885425/219716993-45bdbe4c-a0f2-499a-8648-c90a983cd676.png) | ![screenshot-1676650498353](https://user-images.githubusercontent.com/17885425/219716999-33ecf8f4-b53b-4950-ba81-ae97680bb1ff.png) | ![screenshot-1676650654650](https://user-images.githubusercontent.com/17885425/219717001-5f32e679-e05b-4379-9572-424d0863a3f4.png)
