### ISSUE TITLE
Google Sign-In prompt shows up when trying to sign in on developers.google.com

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#28222]
With Google Sign In feature flag on, we prompt for Google Sign-In even on google.com domains, which are not technically 3p. 

Example: try signing in on developers.google.com

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.50.98 Chromium: 111.0.5563.64 (Official Build) beta (x86_64)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | macOS Version 11.7.4 (Build 20G1120)

Reproduced the issue easily with current `1.49.120`

`brave://flags` | `developers.google.com`
---------------|--------------------------
<img width="1312" alt="Screen Shot 2023-03-20 at 5 01 20 PM" src="https://user-images.githubusercontent.com/387249/226491463-09c182e9-35b3-414a-946b-3466663cc07b.png"> | <img width="1312" alt="Screen Shot 2023-03-20 at 5 03 20 PM" src="https://user-images.githubusercontent.com/387249/226491445-475fc823-a606-46ac-8f58-d637912249b8.png">

### Steps:
1. installed `1.50.98`
2. launched Brave
3. opened `brave://flags`
4. set `Enable Google Sign-In Permission Prompt` to `Enabled`
5. clicked `Relaunch`
6. loaded `https://developers.google.com`
7. clicked on `Sign in` at the top right
8. confirmed I went straight to the username/password login page
9. entered credentials
10. logged in successfully

#### Confirmed no `Allow use of third-party cookies for legacy Google Sign-In` dialog

`brave://flags` | `login page` | `Two-factor auth prompt` | `Signed in`
---------------|--------------|---------------------------|------------
<img width="1312" alt="Screen Shot 2023-03-20 at 5 05 22 PM" src="https://user-images.githubusercontent.com/387249/226491915-b8b684bb-be05-47d5-be62-0ce4b6336ef2.png"> | <img width="1312" alt="Screen Shot 2023-03-20 at 5 05 36 PM" src="https://user-images.githubusercontent.com/387249/226491921-57915c44-0e5a-463e-820f-b469bc4e2f69.png"> | <img width="1312" alt="Screen Shot 2023-03-20 at 5 05 55 PM" src="https://user-images.githubusercontent.com/387249/226491922-0e4d56df-4f31-40b5-93a7-39e712a5cbca.png"> | <img width="1312" alt="Screen Shot 2023-03-20 at 5 06 05 PM" src="https://user-images.githubusercontent.com/387249/226491926-f47740cc-7e1a-48f9-aea6-8a95d0e7cb48.png">

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave	1.50.107 Chromium: 112.0.5615.39 (Official Build) beta (64-bit) 
Revision	a0e7b9718a92bcd1cf33b7c95316caff3fc20714-refs/branch-heads/5615@{#753}
OS	Linux
```
