### ISSUE TITLE
incorrect SE being used for `Private Tab` after upgrading - follow up to #18855

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#28232]
## Description 

When upgrading from a Brave version before https://github.com/brave/brave-core/pull/10590, the incorrect SE is being selected within `Private Tab` in certain cases. For example, within `Settings` it's displaying `Qwant` as the default SE for `Private Tab` but when tapping on `Private Tab` and viewing the SE list, you'll notice that another SE is being selected.

This is pretty bad as we're changing users default SE in certain cases which is never good.

## Steps to reproduce 

   1. install `1.49.55 Chromium: 109.0.5414.86`
   2. once installed, run through onboarding and skip the `Widget` onboarding so tapping on `omnibox` triggers SE onboarding
   3. select `Startpage` from the list and tap on `Continue`
   4. go into `Hamburger Menu` -> `Search engines` and notice that `Startpage` is selected
   5. select `Bing` as the default SE for `Standard Tab`
   6. select `Qwant` as the default SR for `Private Tab`
   7. close Brave and update to `1.49.82 Chromium: 110.0.5481.52`
   8. go back into `Hamburger Menu` -> `Search engines`
   9. notice that `Private Tab` appears as `Qwant` but within `Private Tab`, another search engine that's not Qwant is selected

## Actual result 

https://user-images.githubusercontent.com/2602313/216279257-3d2af8b8-92a3-43f8-846a-199eaf33a219.mp4

## Expected result

`Private Tab` should be using the correct SE after upgrading Brave. Currently, it shows the correct SE within the top level via `Settings` but once inside `Private Tab`, it displays the incorrect SE.

## Issue reproduces how often 

100% reproducible using the STR/Cases outlined above.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `N/A`
- Can you reproduce this issue with the current Play Store Beta version? `Yes`
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details

   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Pixel 6` (Phone)
   - Android version: `Android 13`
   
## Brave version

```
Brave | 1.49.82 Chromium: 110.0.5481.52 (Official Build) canary (32-bit)
--- | ---
Revision | 979113183ded4544a2c443aceb1629c430907e52-refs/branch-heads/5481@{#636}
OS | Android 13; Build/TQ1A.230105.002
```

### Website problems only

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by simonhong** [comment]
checking..

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Samsung Galaxy version 12` running `Bravemonoarm64.apk_1.51.105`

- Verified the STR from the description and ensured that the selected SE is retained inside the `Private Tab` SE 

https://user-images.githubusercontent.com/38657976/234931550-4cfef88c-04ab-4f7e-a33c-35691bb5c593.mp4

**Comment by vlad-hoff** [comment]
Verified on `Galaxy Tab S8` using version(s):

```
Device/OS: SM-X700 Galaxy Tab S8 [gts8wifixx-user 13 TP1A.220624.014 release-keys]
Brave build: 1.51.109 Chromium: 113.0.5672.63 (Official Build) (64-bit)
```
---------------------------

**STEPS:**
1. Install 1.50.121
2. Once installed, run through onboarding and skip the Widget onboarding so tapping on omnibox triggers SE onboarding
3. Select `Startpage` from the list and tap on Continue
4. Go into Hamburger Menu -> Search engines and notice that `Startpage` is selected
5. Select `Bing` as the default SE for Standard Tab
6. Select `Qwant` as the default SE for Private Tab
7. Close Brave and update to 1.51.109
8. Go back into Hamburger Menu > Search engines

**ACTUAL RESULTS:**
- Verified that previously set SE is still selected for Normal and Prvate tabs
- Verified that results are appearing with a correct SE for Normal and Prvate tabs

https://user-images.githubusercontent.com/128532965/235780034-97667b9c-dfdb-4862-9e69-9c574185b708.mov
