### ISSUE TITLE
REQ: Pinned tabs as icon-only in vertical tabs mode as it already is in horizontal tabs mode

### ISSUE THREAD

**Issue by DanielSmedegaardBuus** [brave/brave-browser#28236]
## Description 

Thank you for vertical tabs, it's why I'm back on Brave :)

I humbly request having small icon-only pinned tabs at the top, similar to how they are represented in horizontal mode. This not only saves a ton of space for those of us that have a lot of pinned tabs (I have between 16 and 20), and it makes it really easy to quickly discern between pinned and non-pinned tabs.

I think a lot of us pin tabs because we want to keep our mail, twitter, etc. open, but we don't want them to clutter the UI. Having them presented as normal tabs in vertical mode defeats this use case.

This is a screenshot of how pinned tabs look in the Vertical Tabs Reloaded extension for Firefox:

![image](https://user-images.githubusercontent.com/384983/216307791-cc4bd83c-734b-4a89-b35e-66ef2c5064e5.png)

When you have more pinned tabs than can fit in one row, it adds another row below.

Thank you for the consideration!

PS: I know the image isn't actually from Vertical Tabs Reloaded, but I've uninstalled Firefox, and I couldn't find a screenshot online. But they look the same in VTR, except a little prettier without a border around them.

**Comment by rebron** [comment]
@DanielSmedegaardBuus We're already showing pinned tabs as icon only. 

<img width="282" alt="Screenshot 2023-02-07 at 10 44 30 AM" src="https://user-images.githubusercontent.com/5951041/217337182-d1b530d7-a576-4012-9c8b-8e6538cfef7d.png">

**Comment by DanielSmedegaardBuus** [comment]
> @DanielSmedegaardBuus We're already showing pinned tabs as icon only.
> 
> <img alt="Screenshot 2023-02-07 at 10 44 30 AM" width="282" src="https://user-images.githubusercontent.com/5951041/217337182-d1b530d7-a576-4012-9c8b-8e6538cfef7d.png">

Brilliant! Looks awesome :) Will this be in an upcoming update? Or do I need to edit some hidden config?

**Comment by cadatoiva** [comment]
It seems to be in the general build, I used no extra settings. Might need to try unpin and pin again.

**Comment by rebron** [comment]
Closing as works for me.
