### ISSUE TITLE
Brave v 148xxxx

### ISSUE THREAD

**Issue by harryray33** [brave/brave-browser#28234]
I see that Brave 148 is based on Chromium 109...Does this mean that it will work with Windows 7?
I was told that 147.x would be the last to support Win 7.

Thanks.

**Comment by rebron** [comment]
Hi @harryray33 1.48.x is based on Chromium 110. 1.47.x is the last to support Windows 7. 
https://github.com/brave/brave-browser/releases/tag/v1.48.152 is Brave Beta channel and is a 1.48.x version with Chromium 109. That is unsupported.
