### ISSUE TITLE
users `Private` SE choice is being automatically changed to `Brave` - follow up to #18855

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#28235]
## Description 

When a user has `Korea` selected as their region and they update to a newer version of Brave that includes https://github.com/brave/brave-core/pull/10590, their `Private` window SE is always being replaced with `Brave`.

## Steps to Reproduce

   1. ensure that the machines `region` is set as `Korea`
   2. install `1.49.82 Chromium: 110.0.5481.52` and go into `brave://settings/search`
   3. select `Bing` as the `Normal` window SE
   4. select `Qwant` as the `Private` window SE
   5. update brave via `brave://settings/help`
   6. once updated, go back into `brave://settings/search` and notice that the `Private` SE is set as `Brave` rather than `Qwant`

## Actual result:

Users that have `Korea` set as their region are having `Brave` set as the default SE after updating.

## Expected result:

We should be respecting users SE selections, specifically `Private` windows in this case.

## Reproduces how often: 

100% reproducible using the STR/Cases outlined above.

## Brave version (brave://version info)

```
Brave | 1.49.82 Chromium: 110.0.5481.52 (Official Build) nightly (64-bit)
-- | --
Revision | 979113183ded4544a2c443aceb1629c430907e52-refs/branch-heads/5481@{#636}
OS | Windows 11 Version 22H2 (Build 22621.1105)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes` 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by simonhong** [comment]
Checking this.

**Comment by simonhong** [comment]
When previously used search provider for private window is not included in newly updated default provider list,
we consider it as invalid and set Brave instead. We should not consider it as invalid one.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 



Brave | 1.51.77 Chromium: 112.0.5615.49 (공식 빌드) beta (x86_64)
-- | --
개정 | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | macOS 버전 11.7.5(빌드 20G1225)

### Steps:
1. set OS region and language to South Korea and Korean, respectively
2. installed 1.50.106` (also on the `beta` channel)
3. launched Brave
4. opened `brave://settings/search`
5. changed `Normal window` to `Bing`
6. changed `Private window` to `Qwant`
7. shut down Brave
8. installed `1.51.77`
9. launched Brave
10. opened `brave://settings/search`
11. checked search-engine values

#### Confirmed my custom search-engine choices were preserved when upgrading/updating to `1.50.77`


`1.50.106` | `1.51.77`
---------|---------
<img width="1312" alt="스크린샷 2023-04-04 오후 7 21 51" src="https://user-images.githubusercontent.com/387249/229966315-7a1b2ba6-ca4a-40ec-81f9-30b00a24ee50.png"> | <img width="1312" alt="스크린샷 2023-04-04 오후 7 24 52" src="https://user-images.githubusercontent.com/387249/229966319-afacde34-2892-48a7-be08-2eab44f5fe7e.png">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using

```
Brave | 1.51.79 Chromium: 112.0.5615.49 (공식 빌드) beta (64비트)
-- | --
개정 | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Windows 11 Version 22H2 (Build 22621.1413)
```

Steps:

1. set OS region and language to South Korea and Korean, respectively
2. installed 1.50.114 (also on the beta channel)
3. launched Brave
4. opened `brave://settings/search`
5. changed `Normal window` to `Bing`
6. changed `Private window` to `Qwant`
7. shut down Brave
8. installed 1.51.79
9. launched Brave
10. opened brave://settings/search
11. checked search-engine values

#### Confirmed custom search-engine choices in `brave://settings/search` were preserved when upgrading/updating to `1.51.79`

1.50.114 | 1.51.79
------|-----
<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/230659773-0a643465-8f4b-4170-9965-ba33fbc6b605.png">|<img width="459" alt="image" src="https://user-images.githubusercontent.com/98358127/230660066-b2f77dd2-8227-4886-9a45-2a25a7ddccdb.png">
