### ISSUE TITLE
Monthly Dropdown should not be available in Panel until Monthly donation is made.

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#2823]
## Description 
The dropdown to select a recurring contribution in the Rewards Panel should not be visible until a user has made an ad-hoc donation, selecting "Make this Monthly" for that publisher.

Test plan:
1. Start Brave, enable Rewards.
2. Go to a verified publisher's site.
3. Open the Rewards Panel, ensure that no dropdown is available.
4. Send them a recurring tip.
5. Re-open the panel and confirm the dropdown is present with the current recurring amount.
6. Change the donation amount via the panel to `0.0`
7. Confirm the dropdown is no longer available.

**Comment by GeetaSarvadnya** [comment]
Verification passed on 


Brave | 0.65.93 Chromium: 74.0.3729.131 (Official Build) beta (64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Windows 10 OS Build 17134.523

- Verified the test plan from https://github.com/brave/brave-core/pull/2069
