### ISSUE TITLE
Review order button remains disabled when changing Swap tokens 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#28248]
## Description 
Review order button remains disabled when changing Swap tokens 

## Steps to Reproduce

Possible steps not 100% sure about it being accurate

   1. Select USDC in Swap from token field
   2. Select MANA in Swap to field 
   3. Showed `Insufficient liquidity`
   4. Change MANA to 1Inch token, Updates quote and continues to show `Insufficient liquidity`
   5. Change Swap value to Half
   6. Button changes to Review Order but remains disabled
   7. Change Swap To token from 1Inch to something else, Review order button remains disabled 
   8. Reload page and it works fine

## Actual result:

https://user-images.githubusercontent.com/17010094/216343756-6525d799-f224-4f7f-95e3-034268e7d839.mp4

## Expected result:
Review order button shouldn't be disabled when tokens are changed and quotes are updated

## Reproduces how often: 

Happened Once

## Brave version (brave://version info)

Brave | 1.48.151 Chromium: 109.0.5414.119 (Official Build) beta (64-bit)
-- | --
Revision | `772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}`
OS | Windows 11 Version 22H2 (Build 22621.755)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Not checked
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Not checked

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @onyb @Douglashdaniel

**Comment by kjozwiak** [comment]
The above requires `1.48.166` or higher for `1.48.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.48.166 Chromium: 110.0.5481.100 (Official Build) (64-bit)
-- | --
Revision | `4be7a36f7cb943af6118e449bbab494b43dcaddd-refs/branch-heads/5481_77@{#14}`
OS | Windows 11 Version 22H2 (Build 22621.1265)

- Verified steps from issue description
- Verified quotes are reset when review order is clicked and panel opens up
- Verified amount is reset when user changes the Swap From token

https://user-images.githubusercontent.com/17010094/219612469-b1522beb-c525-4731-9a89-df8a88c68c6e.mp4
