### ISSUE TITLE
Insufficient liquidity shown when swap quotes are shown

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#28249]
## Description 

Insufficient liquidity shown when swap quotes are shown

## Steps to Reproduce

Possible steps not 100% accurate
   1. Select USDT as Swap from token
   2. Select a couple of tokens to swap to and get quotes
   3. Select `yearn.finance` from token list, shows quote but review order button changes to `Insufficient liquidity`

Also ran into the issue with USDT->MANA as well

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/216353337-9ebce0b9-0d50-442a-91e1-d07a911687d1.png) | ![image](https://user-images.githubusercontent.com/17010094/216353435-f0306cb5-8d54-401b-b096-a418a4c86296.png)
-- | --

## Expected result:
Not show quotes when insufficient liquidity error is shown

## Reproduces how often: 

Intermittent 

## Brave version (brave://version info)

Brave | 1.48.151 Chromium: 109.0.5414.119 (Official Build) beta (64-bit)
-- | --
Revision | `772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}`
OS | Windows 11 Version 22H2 (Build 22621.755)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Not checked

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @onyb @Douglashdaniel

**Comment by HEagle18** [comment]
this looks to be fixed to me .. agree @onyb @srirambv ?

**Comment by HEagle18** [comment]
closing after messaging @srirambv

**Comment by srirambv** [comment]
Unable to repro the issue now.
