### ISSUE TITLE
NFT with a really long name isn't wrapped in select NFT screen causing the info button to be pushed out of view

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#28259]
## Description 

NFT with a really long name isn't wrapped in select NFT screen causing the info button to be pushed out of view

## Steps to Reproduce

   1. Add an NFT with a really long name
   2. Open Send tab and Select NFT
   3. Click on Select NFT dropdown
   4. Info button is trimmed out because of the unusual long name not wrapped properly

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/216400784-7542c285-e7de-49a2-815a-f787badd4b63.png)

## Expected result:
Wrap name correctly so info button is shown correctly 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.50.3 Chromium: 110.0.5481.52 (Official Build) nightly (64-bit)
-- | --
Revision | `979113183ded4544a2c443aceb1629c430907e52-refs/branch-heads/5481@{#636}`
OS | Linux

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @muliswilliam

**Comment by Douglashdaniel** [comment]
Closed with https://github.com/brave/brave-core/pull/17028

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.50.91 Chromium: 111.0.5563.64 (Official Build) beta  (64-bit) 
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Linux

- Verified steps from issue description
- Verified NFT with a really long name is wrapped to left alignment on Send NFT screen

https://user-images.githubusercontent.com/17010094/225549820-9952cd29-e661-4355-8670-08415acea180.mp4


---------------------

Verification passed on 

Brave | 1.50.91 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from issue description
- Verified NFT with a really long name is wrapped to left alignment on Send NFT screen

https://user-images.githubusercontent.com/17010094/225550765-904594f6-2e49-48d4-9f8d-f35ff89a6474.mp4


---------------------

Verification passed on 

Brave | 1.50.91 Chromium: 111.0.5563.64 (Official Build) beta (arm64)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from issue description
- Verified NFT with a really long name is wrapped to left alignment on Send NFT screen

https://user-images.githubusercontent.com/17010094/225552187-0317b625-ca1c-4a86-bd36-5855bc3bf997.mov
