### ISSUE TITLE
Change request for search result ad click URL

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#28252]
Need to change a search result click URL according to recent spec changes: https://docs.google.com/document/d/1ncuyw0Yv_qawR-FM0_e1r4pNU2pGDhS49KfwfHqqrqs/edit#heading=h.hnm67cu7xxpw

**Comment by LaurenWags** [comment]
Adding `QA/Blocked` as this cannot be checked in 1.49.x until uplifted.
