### ISSUE TITLE
Show skeleton loaders instead of showing crazy values before refreshing quotes

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#28250]
## Description 

Show skeleton loaders instead of showing crazy values before refreshing quotes

## Steps to Reproduce

   1. Select Swap tokens
   2. Keep changing Swap To tokens
   3. Check the Rate field, keeps showing crazy high values in red for some tokens

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/216357047-bcef7332-2faa-439a-9b20-5106d5c9340d.png)

## Expected result:
Add loading skeletons instead of these values

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.48.151 Chromium: 109.0.5414.119 (Official Build) beta (64-bit)
-- | --
Revision | `772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}`
OS | Windows 11 Version 22H2 (Build 22621.755)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @onyb @kleantzogu @Douglashdaniel

**Comment by Douglashdaniel** [comment]
Is no longer replicable, closing as `Invalid`
