### ISSUE TITLE
P3A log store broken after Chromium upgrade

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#28265]
## Description 

The P3A log store is malfunctioning after the recent Chromium upgrade. This is due to two things:

- Conversion of `DictionaryPrefUpdate` to `ScopedDictPrefUpdate`. The latter does not allow reading of existing dictionary values, which `LoadPersistedUnsentLogs` depends on.
- Usage of `SetByDottedPath` for value updates. Since histogram names usually have dots, this results in an incorrect dictionary structure.

## Steps to Reproduce

   1. View local state page.
   2. Note the unusual structure of the p3a dictionary.
   3. Notice that no metrics are sent.

## Brave version:

1.49.x and up

**Comment by kjozwiak** [comment]
The above requires `1.49.88` or higher for `1.49.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
Brave | 1.49.90 Chromium: 110.0.5481.77 (Official Build) beta (64-bit)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | Windows 10 Version 21H2 (Build 19044.2486)

```
