### ISSUE TITLE
Brave Today CDN request sent on startup without Brave News enabled on a clean profile

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#28268]
## Description 

Brave Today CDN request sent on startup without Brave News enabled on a clean profile

## Steps to Reproduce

   1. Clean profile
   2. Check startup calls
   3. Open a new tab
   4. Shows request sent for `brave-today-cdn.brave.com`  even though News is not enabled

## Actual result:

https://user-images.githubusercontent.com/17010094/216606323-e57f8859-d98b-4c5f-9f31-52f91503a662.mov

## Expected result:
No start up calls unless required or opted into

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.48.151 Chromium: 109.0.5414.119 (Official Build) beta (arm64)
-- | --
Revision | `772095164c7d5d4e73160f858efed3b5e87eca83-refs/branch-heads/5414@{#1458}`
OS | macOS Version 13.0 (Build 22A380)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Not checked
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Not checked

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @mattmcalister @rebron @mkarolin @aurangzaib048 @petemill

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.50.94 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | Windows 10 Version 22H2 (Build 19045.2728)

### Steps:
1. installed `1.50.94`
2. launched Charles Proxy
3. launched Brave Beta
4. examined Charles Proxy for outbound network requests on startup/profile settling
5. opened a new-tab page (with Brave News' opt-in dialog "peeking" up)
6. again checked Charles Proxy for outbound network requests to `brave-today-cdn.brave.com`

#### Confirmed no more outbound requests to `brave-today-cdn.brave.com` on app startup + new window

`1.50.94` | `1.49.120`
----------|-----------
![image (1)](https://user-images.githubusercontent.com/387249/226464162-e4c4f741-72dc-4e2d-9dda-4c34762f9015.png) | ![image](https://user-images.githubusercontent.com/387249/226464167-fad5b7a3-6a0c-4bb6-809c-00b58d5fbf8c.png)
