### ISSUE TITLE
Universal Bypass is broken on Brave

### ISSUE THREAD

**Issue by timmyRS** [brave/brave-browser#2826]
I'm working the extension [Universal Bypass](https://universal-bypass.org), which has to send a request to my server to bypass some sites, which users can disable in the options. However, the brave adblock prevents these requests. So, my suggestion would be to add an API so my extension could simply tell the adblocker to allow these requests:

    if(typeof brave != "undefined")
    {
        brave.allowRequestsTo("https://universal-bypass.org/*");
    }

**Comment by Andy987456** [comment]
https://fcc.lc/2020/06/how-to-create-your-business-identity-in-online-marketing-with-web-development/?a=R1Rqa1Nj

It is not working for this site

**Comment by rizkuwu** [comment]
Any update? I would very much like to use Universal Bypass on Brave.

**Comment by Alpha-404** [comment]
for me it works on brave

**Comment by rizkuwu** [comment]
It works for me too now!

**Comment by bsclifton** [comment]
cc: @ryanbr

**Comment by ryanbr** [comment]
Just tested this extension, https://favpng.com/ works fine. @timmyRS  is everything okay now with Universal Bypass and Brave?

@Andy987456   also tested the link, what exactly is the issue with the web site?

**Comment by Sainan** [comment]
@ryanbr The issue here is with the "Crowd Bypass" feature. You can view example links at https://universal-bypass.org/example-links.

**Comment by DylwinTFTW** [comment]
Why hasn't this been fixed yet?

**Comment by LuisHCK** [comment]
I can install the extension, but when i close and open the browser again the extension is removed 
![image](https://user-images.githubusercontent.com/5175137/97757695-db4a7680-1ac2-11eb-8ac9-f25cfda09713.png)

**Comment by jenabaivab** [comment]
> 
> 
> I can install the extension, but when i close and open the browser again the extension is removed
> ![image](https://user-images.githubusercontent.com/5175137/97757695-db4a7680-1ac2-11eb-8ac9-f25cfda09713.png)

Same issue. Half the links are not bypassed and every now and then the extension gets removed.
It's definitely not a chromium issue considering Edge chromium runs it without any issue.

**Comment by huxkon** [comment]
It's working now.

**Comment by LuisHCK** [comment]
I stopped using Brave for this bug. I'll try again

**Comment by nonetrix** [comment]
is this still a issue?

**Comment by ryanbr** [comment]
I've re-installed the extension, seems okay so far. restarting the browser hasn't removed/disabled the extension so far.

**Comment by nonetrix** [comment]
nice brave's adblocking is really effective but seems to break a lot

**Comment by GabiGG0** [comment]
How do i add this api ?

**Comment by sdgrs546547Q** [comment]
brave will fix this? universal bypass is a great extension and is a shame that we cant use it on Brave Browser.

**Comment by trqzh** [comment]
i've been using it on brave browser for years with no issues

**Comment by trqzh** [comment]
> i've been using it on brave browser for years with no issues

after i made this comment, of course it stops working.

**Comment by leodoi3** [comment]
Any update on this? I also want to see Universal Bypass work with Brave.

**Comment by ryanbr** [comment]
> Any update on this? I also want to see Universal Bypass work with Brave.

I've installed it previously (see previous post), other people have installed this extension. What exactly, exactly are we fixing?

**Comment by 0luismario0** [comment]
@leodoi3 [Universal Bypass](https://github.com/Sainan/Universal-Bypass#universal-bypass) is no longer mainteined. You could check out [FastForward](https://github.com/FastForwardTeam/FastForward) which is a continuation of the project. Also, this addon is on the [Chrome Web Store](https://chrome.google.com/webstore/detail/fastforward/icallnadddjmdinamnolclfjanhfoafe).

**Comment by ShivanKaul** [comment]
Given that this extension isn't maintained any more, closing this out as wontfix. Please let us know if the new one doesn't work properly.
