### ISSUE TITLE
crash when quickly selecting SE from `Private Tab` and then closing `Settings` via `X`

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#28262]
## Description 

When you quickly select a SE from `Private Tab` and then close the `Search engines` settings page via `X`, the browser ends up crashing from time to time. I've reproduced the crash several times while running through https://github.com/brave/brave-core/pull/10590.

Crashes:

* https://brave.sp.backtrace.io/p/brave/debug?filters=(_rxid%3Ddad20000-27c7-9009-0000-000000000000)&fingerprint=ebe50b8bb8f7604e067fdd27668bb66628bca37334238b4439ad2fcb26b34af9&debug=(%2244f79e6%22,0,0)
* https://brave.sp.backtrace.io/p/brave/debug?filters=(_rxid%3Dd85c0100-27c7-9009-0000-000000000000)&fingerprint=ebe50b8bb8f7604e067fdd27668bb66628bca37334238b4439ad2fcb26b34af9

## Steps to reproduce 

* install `1.49.55 Chromium: 109.0.5414.86`
* launch `Brave` and quickly go through onboarding (default browser/P3A/Permissions on Android 13)
* go into `Hamburger Menu` -> `Settings` -> `Search engines`
* tap on `Standard` and select `Bing`
* tap on `<` to back to `Settings` and tap on `Private`
* select `Qwant` and then quickly tap on the `X` to dismiss the `Search engines` settings page

Brave will usually crash within a ~ms once the `Search engines` settings page is closed.

## Actual result 

https://user-images.githubusercontent.com/2602313/216433172-645fdf07-b9ba-46a4-ad63-c405cce7477d.mp4

## Expected result

Brave shouldn't be crashing once a user selects a SE via `Private Tab` and closes the settings page via `X`

## Issue reproduces how often 

100% reproducible using the STR/Cases outlined above.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `Yes`
- Can you reproduce this issue with the current Play Store Beta version? `Yes 
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Pixel 6` (Phone)
   - Android version: `Android 13`
   
## Brave version

```
Brave | 1.49.55 Chromium: 109.0.5414.87 (Official Build) canary (32-bit)
--- | ---
Revision | 2dc18eb511c56e012081b4abc9e38c81c885f7d4-refs/branch-heads/5414@{#1241}
OS | Android 13; Build/TQ1A.230105.002
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by kjozwiak** [comment]
The above requires `1.48.164` or higher for `1.48.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung GS 21` using version:

```
Brave	1.48.166 Chromium: 110.0.5481.100 (Official Build) (64-bit) 
Revision	4be7a36f7cb943af6118e449bbab494b43dcaddd-refs/branch-heads/5481_77@{#14}
OS	Android 13; Build/TP1A.220624.014
```

Using STR in https://github.com/brave/brave-browser/issues/28262#issue-1568686705, ensured that crash doesn't occur when selecting SE from private tab and then quickly closing settings with X


https://user-images.githubusercontent.com/17885425/219720409-40007a59-ff47-427e-9c25-5e41336398e4.mp4
