### ISSUE TITLE
[Android] Match onboarding flow to desktop's when skipping Rewards onboarding tour 

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#28260]
## Description 

When skipping the onboarding tour after joining Rewards, Desktop and Android behave differently on the panel.

## Steps to Reproduce

1. Clean profile
2. Close/relaunch to pull griffin
3. Join rewards (I used US as my country)
4. Then select "Skip for now" link to skip the onboarding tour

---> On desktop, you are taken to the slide for Ads per hour setting, when you click "Continue" then you go on to the slide which prompts for connecting a custodian.

Example | Example
---- | ----
<img width="1187" alt="Screen Shot 2023-02-02 at 11 12 33 AM" src="https://user-images.githubusercontent.com/28145373/216414595-0e21f59f-ee5a-4518-bb37-0492b149e2a2.png"> | <img width="1189" alt="Screen Shot 2023-02-02 at 11 12 46 AM" src="https://user-images.githubusercontent.com/28145373/216414598-b09f1f3a-0cf2-4bed-9c3b-cb8cfa416945.png">

---> On Android you get the "Woohoo, you're all set!" slide. You are not prompted to connect a custodian after selecting "Done" 

Example | Example
---- | ----
![Screenshot_20230202-111445](https://user-images.githubusercontent.com/28145373/216415056-5a35006e-8348-43cb-b87c-148a23b75e7d.png) | ![Screenshot_20230202-121407](https://user-images.githubusercontent.com/28145373/216415060-75b434b3-11fc-45b3-a0d1-f695f79f84de.png)

## Actual result:

See above

## Expected result:

Desktop is expected result. — @miyayes 

## Reproduces how often: 

easily

## Desktop Brave version:

 1.48.x

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? 1.48.x yes
- Can you reproduce this issue with the nightly channel? unsure, likely

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @Miyayes

**Comment by Miyayes** [comment]
## Solution

According to @minkyeongshin, if user presses SKIP on onboarding, they should go the Ads frequency settings slide. So, desktop is correct in this case, and Android should match desktop's flow.

**Comment by Miyayes** [comment]
Superseded by new giftbox onboarding.
