### ISSUE TITLE
description text for "Clear cookies and site data..." doesn't make sense

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#28269]
## Description 

The description text below the "Clear cookies and site data when you close all windows" setting doesn't make sense. It says:

```
When on, you'll also be signed out of Brave
```

Users don't sign in to Brave, so this text should be removed.

## Steps to Reproduce

   1. Navigate to brave://settings/cookies

## Actual result:

1.47.186 | 1.48.155
---- | ----
<img width="1347" alt="1 47 186" src="https://user-images.githubusercontent.com/28145373/216616939-4e6f0d6d-79e0-4c08-9fc4-fa05fc6ad2c6.png"> | <img width="1346" alt="1 48 155" src="https://user-images.githubusercontent.com/28145373/216616942-b0652a34-4ef8-41b0-b081-239d083f99ed.png">

## Expected result:

No text below that setting.

## Reproduces how often: 

easily

## Brave version (brave://version info)

1.47.x, 1.48.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes (1.47.x w/ C109 and 1.48.x w/ C110)
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron

**Comment by kjozwiak** [comment]
The above requires `1.48.157` or higher for `1.48.x` verification 👍
