### ISSUE TITLE
Long NFT names overlap on other items when searched 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#28275]
## Description 

Long NFT names overlap on other items when searched 

## Steps to Reproduce

   1. Add an unusually long name for an NFT
   2. Open visible asset list
   3. Search for the long name NFT
   4. Overlaps on the other items listed

## Actual result:

![Overlapping Names](https://user-images.githubusercontent.com/17010094/216654689-be47fcb3-1429-4ab4-b146-7669d7e8b8b5.png)

## Expected result:
Shouldn't overlap

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.48.155 Chromium: 110.0.5481.77 (Official Build) (64-bit)
-- | --
Revision | `65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Not checked
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @muliswilliam @Douglashdaniel

**Comment by Douglashdaniel** [comment]
Accidentally tagged this issue in the wrong PR, reopening.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.50.93 Chromium: 111.0.5563.64 (Official Build) beta  (64-bit) 
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Linux

- Verified steps from [brave/brave-core#17110](https://github.com/brave/brave-core/pull/17110)
- Verified long NFT names are properly wrapped and doesn't overlap on other items when searched
![image](https://user-images.githubusercontent.com/17010094/225820264-1c7c5899-36d9-4583-a39b-db3409f228ec.png)


---------------------

Verification passed on 

Brave | 1.50.93 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from [brave/brave-core#17110](https://github.com/brave/brave-core/pull/17110)
- Verified long NFT names are properly wrapped and doesn't overlap on other items when searched
![brave_v0rrQR3MVZ](https://user-images.githubusercontent.com/17010094/225820681-98dd1183-e51b-4e71-afaf-8cf37413faee.png)

---------------------

Verification passed on 

Brave | 1.50.93 Chromium: 111.0.5563.64 (Official Build) beta (arm64)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#17110](https://github.com/brave/brave-core/pull/17110)
- Verified long NFT names are properly wrapped and doesn't overlap on other items when searched
![image](https://user-images.githubusercontent.com/17010094/225820881-0a670383-6201-4567-90f4-db3414fa0a94.png)
