### ISSUE TITLE
Don't farble Accept-Language when its being set by JS code

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#28279]
Follow up issue from: https://github.com/brave/brave-browser/issues/24314#issuecomment-1416130883

Currently we farble / randomize / reduce the Accept-Language header on every request when i. fingerprinting protections are enabled and ii. the "reduce language based fingerprinting" setting is enabled.

We do this for all requests. However, we should only do it for requests that are determining the accept-language value from the system / profile; if JS client code is explicitly setting it, there is no fingerprinting risk, and so we should not modify the explicit set value.

The two places I can think of where this will matter are the [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Headers) API, and the XMLHTTPRequest [setRequestHeader](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/setRequestHeader) API.

**Comment by kjozwiak** [comment]
@pes10k @pilgrim-brave this part of a uplift but is currently missing the `QA/Yes` or `QA/No` label and doesn't have any STR/Cases. Mind providing the needed information so QA can verify on `master` and get this uplifted into `1.50.x` via https://github.com/brave/brave-core/pull/17697?

**Comment by pes10k** [comment]
Ah, yea, apologies @kjozwiak , i can add a QA test for this tomorrow.  I'll mark as `QA/Yes` now

**Comment by kjozwiak** [comment]
> Ah, yea, apologies @kjozwiak , i can add a QA test for this tomorrow. I'll mark as `QA/Yes` now

Sounds good! Thanks 👍 Once we get some STR, we'll get the above verified on `master` and get it uplifted.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.50.110 Chromium: 112.0.5615.49 (Official Build) (x86_64)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | macOS Version 12.6.4 (Build 21G526)
```

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.50.112 Chromium: 112.0.5615.49 (Official Build) (64-bit) 
Revision	bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS	Linux
```

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 13` using the following build(s):

```
Brave | 1.50.112 Chromium: 112.0.5615.49 (Official Build) (32-bit)
--- | ---
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Android 13; Build/TQ2A.230305.008.E1
```

**`1.49.132` - Standard Fingerprinting Protection** | **`1.50.112` - Standard Fingerprinting Protection** | `1.50.112` - Aggressive Fingerprinting Protection | 
------------|-----------|--------------
![Screenshot_20230403-150225](https://user-images.githubusercontent.com/2602313/229614625-9877b6b5-9755-487d-84ae-a4f7cc34591c.png) | ![Screenshot_20230403-160337](https://user-images.githubusercontent.com/2602313/229615303-991c2039-2f7c-45e3-8d46-73bb76c7d2c7.png) | ![Screenshot_20230403-160357](https://user-images.githubusercontent.com/2602313/229615310-f30f977c-b80e-4c51-9f28-ba2c8a0e8743.png)
