### ISSUE TITLE
Be Able To Completely Disable Both Adblock And Rewards

### ISSUE THREAD

**Issue by 2635599** [brave/brave-browser#2827]
would like to be able to completely disable and hide adblock and rewards. i've noticed that brave likes to block some sites, but if i turn off my vpn the site loads fine. i personally believe that something in your adblock is causing the issue, cause in chrome i do not have to disable my vpn. as for rewards regardless of claims i'll never be comfortable with ads, which is why i have adblock plus and ublock origin installed.

**Comment by gabrielhug** [comment]
Related to #3436, though that issue does not include completely hiding Brave shields.

The closest solution currently is to launch brave with the `--disable-brave-rewards-extension` and `--disable-brave-extension` command-line switches and turn off any unwanted settings in `brave://settings/shields`.

**Comment by srirambv** [comment]
Dont think this will be done. Closing the issue for now

cc: @davidtemkin @tomlowenthal
