### ISSUE TITLE
When the brave shields are on, the chat popup in reddit goes on a infinite loading loop.

### ISSUE THREAD

**Issue by ShockRocky** [brave/brave-browser#2828]
## Description 

When the brave shields are on, the chat popup goes on a infinite loop of loading in reddit.
The chat only opens when the shields are turned off. 
The shields are set in their default settings i.e. ad and tracking blocking and https everywhere is on, as well as, third party cookie blocking and 3rd party device recognition blocking is also on, as is the default setting.

## Steps to Reproduce

   1. Login to the new layout of the reddit page :- https://www.reddit.com/ 
   2. On the upper right hand corner, click on the chat button which is besides on the messages tab on its left hand side.
   3. The chat popup does not materialize and instead goes on a infinite loading spree.

## Actual result:

![reddit issue 1](https://user-images.githubusercontent.com/46404268/50727806-19d0ad80-1146-11e9-8660-c956b7cd3599.JPG)

![reddit issue 2](https://user-images.githubusercontent.com/46404268/50727814-41277a80-1146-11e9-8307-dc9d5b46e0a8.JPG)

![reddit issue 3](https://user-images.githubusercontent.com/46404268/50727818-5bf9ef00-1146-11e9-8c4e-df2d28bcfa8e.JPG)

## Expected result:
![issue solved of reddit maan 1](https://user-images.githubusercontent.com/46404268/50727857-07a33f00-1147-11e9-87c3-4fca2271511a.JPG)

![inkedinkedinkedissue solved of reddit maan 2_li](https://user-images.githubusercontent.com/46404268/50727889-a9c32700-1147-11e9-9c40-c5994e3b5d28.jpg)

## Reproduces how often: 

All the time.

## Brave version (brave://version info)

Brave | 0.58.18 Chromium: 71.0.3578.98 (Official Build) (64-bit)

Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}

OS | Windows 

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Haven't checked.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
Yes.

- Is the issue reproducible on the latest version of Chrome? 
No.

**Comment by ShockRocky** [comment]
> @ShockRocky is this working with the release we just did (0.58.21)?

Yes, it is working fine now :)

**Comment by smhk** [comment]
Cheers team, this absolutely still does NOT work on Mac/Brave as of 2023.

**Comment by bsclifton** [comment]
@smhk do you have more info about which version you're using? (Intel mac or M1? which Brave version? you can visit brave://version)

**Comment by smhk** [comment]
Sorry about that:
MacBook Pro 16-inch, 2023 Apple M2 Max 32 GB "ventura" 13.2.1 (22D68)
brave [Version 1.48.171 Chromium: 110.0.5481.177 (Official Build) (arm64)](https://brave.com/latest/)
