### ISSUE TITLE
sync is not removing: new tabs are being recognized across machines after deleting sync chain, happens on safari when brave is not installed

### ISSUE THREAD

**Issue by coreycosman** [brave/brave-browser#28289]
## Description 
I deleted sync chain on all devices. I only synced bookmarks. While bookmarks are successfully unsynced across a mac mini m1 2020 and a macbook air m1 2020, there is some weirdness happening: new tabs are showing up on each machine's browser. I click a new brave tab on macbook air, go to mac mini, navigate apps with CMD-TAB and it shows a new brave icon indicating there is a new tab available (it has a computer icon on top right and says "from macbook air") and when clicking, it opens the new tab from other machine's browser in same brave window that is currently open. The other way around is same (new tab on mac mini shows up on macbookair, icon says "from mac mini").

Weirdly, because i don't have brave set to default browser on macbook air yet, the exact same behaviour happens but shows "from mac mini" on safari. Not sure where this sync data between machines is stored but have no idea how to remove it. Tried uninstalling and reinstalling brave on both machines and restarting both machines, and when reinstalling, the same thing happens immediately. I tried creating new sync codes and then deleting them. same thing. It also happens when brave is not even installed on either machine.

## Steps to Reproduce

   1. sync devices
   2. delete all devices from original machine that started sync chain
   3. delete sync chain
   4. create new tab on one machine
   5. go to other machine and press CMD-TAB

## Actual result:
even with brave uninstalled on both machines, creating a new tab is recognized across machines, in safari or brave. new brave icon appears when pressing CMD-TAB indicating that there is a new tab from other machine (says "from macbook air" for example)

## Expected result:
deleting sync chain should remove all syncing between machines and syncing should not happen outside of brave

## Reproduces how often: 
only happening on two of my machines but cannot remove sync

## Brave version (brave://version info)
Version 1.47.186 Chromium: 109.0.5414.119 (Official Build) (arm64)](https://brave.com/latest/)

**Comment by thefallofbecause** [comment]
This is an Apple feature called [Handoff](https://support.apple.com/en-us/HT209455), not something from Brave.

**Comment by rebron** [comment]
Thanks @thefallofbecause. Correct this is Apple feature. You can turn it off in Settings > General > AirDrop & Handoff  

<img width="502" alt="Screenshot 2023-02-06 at 4 18 45 PM" src="https://user-images.githubusercontent.com/5951041/217116396-c2e90c7c-12fa-480e-8e50-fae47c87142c.png">

**Comment by coreycosman** [comment]
thanks @thefallofbecause @rebron, wondering why brave's sync triggered this? is it related to some new m1 sync implementation? Was only happening on m1 machines and I synced 4 machines (1 mac intel and 1 android)
