### ISSUE TITLE
Missing space before date

### ISSUE THREAD

**Issue by mbiesiad** [brave/brave-browser#28280]
Hi, not a big deal, but:

## Description 
At this moment there is missing space ( ), before displayed date.

## Steps to Reproduce
Open Brave browser, go to default site (please take a look on screenshots), hover by mouse marked icon (right side).

## Actual result:
With Polish lang. ver. there is missing space, before date.

## Expected result:
Add missing space there.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
1.47.186 Chromium: 109.0.5414.119 (Offic. ver) (64-bit) 

## Version/Channel Information:
NA

## Other Additional Information:
NA

## Miscellaneous Information:
Screenshots:
![image](https://user-images.githubusercontent.com/18367606/216672607-195757f1-e2b4-4968-a4dd-f03568315fd3.png)

![image](https://user-images.githubusercontent.com/18367606/216672729-f9e19f76-50de-40c2-a5e1-7a63f96fee43.png)

Best wishes,

**Comment by kjozwiak** [comment]
The above requires `1.48.164` or higher for `1.48.x` verification 👍
