### ISSUE TITLE
Mixed languages in Privacy and Resources tabs

### ISSUE THREAD

**Issue by mbiesiad** [brave/brave-browser#28281]
Hi,

## Description 
At this moment some elements in mentioned parts are with mix of languages - English and Polish in this case.

## Steps to Reproduce
1. With Polish lang. ver. go to https://brave.com/pl/
2. Check tabs Privacy and Resources 

## Actual result:
For Privacy tab - element 'Privacy glossary' is not translated.
For Resources tab - elements 'Brave blog' and 'Web3 guides' are not translated.

## Expected result:
Translated all of content, so
"Słownik dotyczący prywatności" or similar
"Blog Brave" and "Przewodniki po Web3" or similar

(Polish lang. case)

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
1.47.186 Chromium: 109.0.5414.119 (Offic. ver) (64-bit)

## Version/Channel Information:
NA

## Other Additional Information:
NA

## Miscellaneous Information:
Screenshots:
![image](https://user-images.githubusercontent.com/18367606/216676491-f4dafc30-9dd4-493b-87f7-15ff4084f626.png)

![image](https://user-images.githubusercontent.com/18367606/216676514-8b51d1ee-a96b-4fc5-be29-09554828a42e.png)

Best wishes,

**Comment by antonok-edm** [comment]
@mbiesiad It's probably due to missing Polish localizations for those parts. Thanks for providing translated versions!

@AlanBreck could you help get these into the website?

**Comment by AlanBreck** [comment]
Thank you for reporting! We'll be updating soon.

**Comment by mbiesiad** [comment]
My pleasure! ✨ Sounds great 🎉

**Comment by AlanBreck** [comment]
We should pushed updated translations for those strings.

https://brave.com/pl/

**Comment by mbiesiad** [comment]
I can approve - now it's fine.
