### ISSUE TITLE
Enable SNS feature flag by default and update opt-in page

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#28282]
Once we switch to another provider that can support all RPC calls needed for SNS, we can enable the feature by default and update the opt-in page to specify the provider and link to its ToU and privacy policy. 
cc @jamesmudgett 

<img width="632" alt="Screen Shot 2023-02-03 at 2 48 14 PM" src="https://user-images.githubusercontent.com/4730197/216725616-1dcfd8e7-6661-4478-9b87-8b3cb819987d.png">

Security and privacy review was already done in https://github.com/brave/security/issues/1099.
Main PRs for the feature: https://github.com/brave/brave-core/pull/15617, https://github.com/brave/brave-core/pull/15863
Wallet address resolution UI on Android was done in https://github.com/brave/brave-core/pull/16423.

**Comment by kjozwiak** [comment]
The above requires `1.49.92` or higher for `1.49.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.49.106 x64 build

- Verified steps from [brave/brave-core#17034](https://github.com/brave/brave-core/pull/17034)
- Verified SNS feature is enabled by default and set to Ask
- Verified entering a `.sol` domain in omnibox shows SNS Interstitial page
- Verified `Disable` sets SNS feature to `Disabled`
- Verified `Proceed with Syndica Server` sets SNS feature to `Enabled`
- Verified entering `onybose.sol` and `ironpaw.sol` in Send to field resolves the address

Oppo Reno 5 (Android 13) | Samsung Tab A (Android 10)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/220620120-e84574a6-f32c-44f2-87d2-152b1226ccc5.mp4> | <video src=https://user-images.githubusercontent.com/17010094/220620136-ea630140-0fa1-4aa3-934c-9a93fd51217f.mp4>

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta  (64-bit) 
-- | --
Revision | `46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}`
OS | Linux

- Verified steps from [brave/brave-core#17034](https://github.com/brave/brave-core/pull/17034)
- Verified SNS feature is enabled by default and set to `Ask`
- Verified entering a `.sol` domain in omnibox shows SNS Interstitial page
- Verified `Disable` sets SNS feature to `Disabled`
- Verified `Proceed with Syndica Server` sets SNS feature to `Enabled`
- Verified entering `onybose.sol` and `ironpaw.sol` in Send to field resolves the address

https://user-images.githubusercontent.com/17010094/221915784-0d56dfcb-496c-4d5f-ac88-488c33383611.mp4


---------------------

Verification passed on 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta  (64-bit)
-- | --
Revision | `46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#17034](https://github.com/brave/brave-core/pull/17034)
- Verified SNS feature is enabled by default and set to `Ask`
- Verified entering a `.sol` domain in omnibox shows SNS Interstitial page
- Verified `Disable` sets SNS feature to `Disabled`
- Verified `Proceed with Syndica Server` sets SNS feature to `Enabled`
- Verified entering `onybose.sol` and `ironpaw.sol` in Send to field resolves the address

https://user-images.githubusercontent.com/17010094/221916484-d217aec8-c55e-4aa0-8324-267fe2c7fd11.mp4

---------------------

Verification passed on 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta  (arm64)
-- | --
Revision | `46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#17034](https://github.com/brave/brave-core/pull/17034)
- Verified SNS feature is enabled by default and set to `Ask`
- Verified entering a `.sol` domain in omnibox shows SNS Interstitial page
- Verified `Disable` sets SNS feature to `Disabled`
- Verified `Proceed with Syndica Server` sets SNS feature to `Enabled`
- Verified entering `onybose.sol` and `ironpaw.sol` in Send to field resolves the address

https://user-images.githubusercontent.com/17010094/221916874-271aa218-6798-44aa-b2bc-fe5a8328d48e.mov
