### ISSUE TITLE
HTTPS by Default for Android

### ISSUE THREAD

**Issue by arthuredelstein** [brave/brave-browser#28295]
Once we have resolved https://github.com/brave/brave-browser/issues/27141, we plan to add a UI for HTTPS by Default on Android.

**Comment by arthuredelstein** [comment]
See QA testing info here: https://github.com/brave/brave-core/pull/17581#issuecomment-1468249039

**Comment by kjozwiak** [comment]
QA can also use https://github.com/brave/brave-variations/pull/560#issuecomment-1490789259 as a template. Those are the cases that I went through verifying the feature before enabling it via Griffin 👍 CCing @Uni-verse

**Comment by Uni-verse** [comment]
Verification In Progress on Samsung GS 21 5G using the following versions(s):

```
Brave	1.51.79 Chromium: 112.0.5615.49 (Official Build) beta (64-bit) 
Revision	bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS	Android 13; Build/TP1A.220624.014
```

<details><summary>Case: Griffin Experiment</summary>

</details>


<details><summary>Case: brave://flags</summary>

</details>


<details><summary>Case: New Profile (Negative Test Case)</summary></details>


<details><summary>Case: Require all connections to use HTTPS (strict)</summary></details>


<details><summary>Case: Upgrade to HTTPS whenever possible</summary></details>


<details><summary>Case: Don't upgrade connections to HTTPS (disabled)</summary></details>


<details><summary>Case: Globals</summary></details>


<details><summary>Case: Per-site settings</summary></details>


<details><summary>Case: Shields Toggle</summary></details>


<details><summary>Case: Private Browsing</summary></details>


<details><summary>Case: Upgraded Profile</summary></details>

**Comment by Uni-verse** [comment]
Verification In Progress on Samsung Galaxy Tab S7 using the following versions(s):

```
Brave	1.51.79 Chromium: 112.0.5615.49 (Official Build) beta (64-bit) 
Revision	bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS	Android 13; Build/TP1A.220624.014
```

<details><summary>Case: Griffin Experiment</summary>

</details>


<details><summary>Case: brave://flags</summary>

</details>


<details><summary>Case: New Profile (Negative Test Case)</summary></details>


<details><summary>Case: Require all connections to use HTTPS (strict)</summary></details>


<details><summary>Case: Upgrade to HTTPS whenever possible</summary></details>


<details><summary>Case: Don't upgrade connections to HTTPS (disabled)</summary></details>


<details><summary>Case: Globals</summary></details>


<details><summary>Case: Per-site settings</summary></details>


<details><summary>Case: Shields Toggle</summary></details>


<details><summary>Case: Private Browsing</summary></details>


<details><summary>Case: Upgraded Profile</summary></details>

**Comment by Uni-verse** [comment]
Verification In Progress on Android 8
