### ISSUE TITLE
NFT pinning setting

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#28304]
Setting should be under the NFT Pinning feature flag

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.50.101 Chromium: 111.0.5563.116 (Official Build) beta (64-bit) 
-- | --
Revision | `ade86b9472831e26d87fd569e04b404be01e1e2b-refs/branch-heads/5563@{#1209}`
OS | Linux

- Verified steps from [brave/brave-core#17048](https://github.com/brave/brave-core/pull/17048)
- Verified on a clean profile there is no setting for NFT pinning
- Verified when `brave://flags/#enable-nft-pinning` is enabled, a new setting is shown under `brave://settings/web3`
- Verified the setting is disabled by default
- Verified IPFS Deamon is started automatically when the setting is enabled

https://user-images.githubusercontent.com/17010094/227847533-510392ec-ef76-4749-8960-a2912cc2246e.mp4

---------------------

Verification passed on 

Brave | 1.50.101 Chromium: 111.0.5563.116 (Official Build) beta (64-bit)
-- | --
Revision | `ade86b9472831e26d87fd569e04b404be01e1e2b-refs/branch-heads/5563@{#1209}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from [brave/brave-core#17048](https://github.com/brave/brave-core/pull/17048)
- Verified on a clean profile there is no setting for NFT pinning
- Verified when `brave://flags/#enable-nft-pinning` is enabled, a new setting is shown under `brave://settings/web3`
- Verified the setting is disabled by default
- Verified IPFS Deamon is started automatically when the setting is enabled

https://user-images.githubusercontent.com/17010094/227848028-b5b97589-a5c7-4c32-b234-3445301ee927.mp4

---------------------

Verification passed on 

Brave | 1.50.101 Chromium: 111.0.5563.116 (Official Build) beta (arm64)
-- | --
Revision | `ade86b9472831e26d87fd569e04b404be01e1e2b-refs/branch-heads/5563@{#1209}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#17048](https://github.com/brave/brave-core/pull/17048)
- Verified on a clean profile there is no setting for NFT pinning
- Verified when `brave://flags/#enable-nft-pinning` is enabled, a new setting is shown under `brave://settings/web3`
- Verified the setting is disabled by default
- Verified IPFS Deamon is started automatically when the setting is enabled 

https://user-images.githubusercontent.com/17010094/227849576-a36eccb6-3775-4fac-af28-2ab97360515a.mp4
