### ISSUE TITLE
Unable to add a second NFT with the same token symbol, adding a second one always opens the first one 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#28306]
## Description 
Unable to add a second NFT with the same token symbol, adding a second one always opens the first one 

## Steps to reproduce 

   1. Add a Solana NFT to portfolio (Use `DBCMLy8mrTHdi8tGHT6Yw4NmUkjELawz7wvCTkPqBhBr`)
   2. Add Token Symbol as `CTS`
   3. Try to add a second NFT `6fKXjQ2xD2X7upGrMHqRjjMiKgZvvUsTgtRsnd29Gmv1`
   4. Try to add the same symbol `CTS` doesn't add 
   5. Change symbol to CT allows to add
   6. Portfolio lists both NFT with correct icons
   7. Select either of them loads the same/first NFT

## Actual result 

https://user-images.githubusercontent.com/17010094/216934097-1b99ca06-4efb-482e-84d0-d04a6216da71.mp4

## Expected result
Should be able to add a second NFT with the same Token Symbol 

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: 13
   
## Brave version
1.48.155

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @Pavneet-Sing @simoarpe

**Comment by kjozwiak** [comment]
The above requires `1.48.159` or higher for `1.48.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.48.160 x64 build
- Verified steps from issue description
- Verified able to add multiple NFT's of the same collection

https://user-images.githubusercontent.com/17010094/217760530-b9bf1bab-1f6a-4540-8788-1098c8667e09.mp4
