### ISSUE TITLE
Incorrect NFT's are shown when wallet is unlocked

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#28301]
## Description 
Incorrect NFT's are shown when wallet is unlocked

## Steps to reproduce 
Not sure

## Actual result 
Ethereum NFT's are shown under Solana
![image](https://user-images.githubusercontent.com/17010094/216909394-137d092b-7b6e-4978-adab-4bdab35a4255.png)

## Expected result
Should only list the relevant NFT's when network is changed

## Issue reproduces how often 
Intermittent 

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Maybe 
- Can you reproduce this issue with the current Play Store Nightly version? Maybe

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Tablet
   - Android version: 12
   
## Brave version
1.48.155

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @simoarpe @Pavneet-Sing

**Comment by srirambv** [comment]
Partially verified as part of https://github.com/brave/brave-browser/issues/29274#issuecomment-1511312855. There is still a race condition when switching quickly causes wrong NFT to show up but should be fixed as part of https://github.com/brave/brave-core/pull/17967. So this needs to be verified again when https://github.com/brave/brave-core/pull/17967 on nightly or when migrates to Beta.

**Comment by Pavneet-Sing** [comment]
> Partially verified as part of [#29274 (comment)](https://github.com/brave/brave-browser/issues/29274#issuecomment-1511312855). There is still a race condition when switching quickly causes wrong NFT to show up but should be fixed as part of [brave/brave-core#17967](https://github.com/brave/brave-core/pull/17967). So this needs to be verified again when [brave/brave-core#17967](https://github.com/brave/brave-core/pull/17967) on nightly or when migrates to Beta.

Race condition [is known](https://github.com/brave/brave-core/pull/17967#discussion_r1165465519) and should be fixed with https://github.com/brave/brave-browser/issues/29706 issue.
