### ISSUE TITLE
`Uphold` needs `pending` transaction handling

### ISSUE THREAD

**Issue by szilardszaloki** [brave/brave-browser#28309]
If `Uphold` (`post_commit_transaction_uphold.cc`) reports "processing" as the status of the just-committed transaction, we fail the contribution on our end, whereas the actual transaction might go through on their end.

See Gemini's implementation (`post_commit_transaction_gemini.cc`) for details.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.52.86 Chromium: 113.0.5672.77 (Official Build) beta (x86_64)
-- | --
Revision | c4236862955e005c2187105415ac4a2ecf86dff1-refs/branch-heads/5672_62@{#3}
OS | macOS Version 13.3.1 (Build 22E261)
```

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.52.112`
