### ISSUE TITLE
`Searching for domain...` is constantly shown on Swap screen

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#28307]
## Description 
`Searching for domain...` is constantly shown on Swap screen

## Steps to reproduce 

   1. Open Swap screen
   2. `Searching for domain...` is shown constantly 
   3. Even with value set and quote shown, message is not removed

## Actual result 

https://user-images.githubusercontent.com/17010094/216960592-59381916-3105-4012-8092-458251427c87.mp4

## Expected result
Should not show the message on swap screen

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.48.155

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @Pavneet-Sing @simoarpe @supermassive

**Comment by kjozwiak** [comment]
The above requires `1.48.159` or higher for `1.48.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.48.160 x64 build
- Verified `Searching for domain` is not shown on Swap screen
- Verified `Searching for domain` is only shown on send tab when a domain name is entered in the input

Oppo Reno 5 (Android 13) | Lenovo Tab (Android 12)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/217752682-cbd36dd4-178d-488b-9dc4-af86a6a030e3.mp4> | <video src=https://user-images.githubusercontent.com/17010094/217752778-6bfc6cae-8001-4014-8160-b8233ed06516.mp4>
