### ISSUE TITLE
Prompt user to enable Brave Rewards when Rewards is toggled "off" in non-connected state on NTP Rewards widget

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#28314]
## Description

STR:
1. Enable non-connected Rewards state
2. Toggle "off" (or Brave Private Ads off)
3. Note difference between Rewards panel and NTP widget as screenshotted below

![image](https://user-images.githubusercontent.com/11497541/217012426-5d6c6cca-d93b-45c9-8ea7-699acaa0e017.png)

## Solution

Instead, in this state, it should show this messaging to match the Rewards dropdown panel:

Use this template w/ the "Start using Rewards" button:
![image](https://user-images.githubusercontent.com/11497541/217012772-ec658288-148c-43dc-9301-7d1c95727339.png)

But use this messaging instead:
![image](https://user-images.githubusercontent.com/11497541/217018266-83d47c0d-163c-44b3-b1e3-2c8052a83306.png)

**Comment by LaurenWags** [comment]
@Miyayes should it be "Start using Rewards" or "Enable Brave Ads" from https://github.com/brave/brave-browser/issues/27845 ?

**Comment by Miyayes** [comment]
@LaurenWags It's a good question, but in this particular case, I think "Start using Rewards" makes more sense. Ads vs. Rewards state is tied together in the new non-connected state, and since there isn't really any other functionality for Rewards while in the non-connected state, I think "Start using Rewards" is more general and makes sense in this context.

**Comment by Miyayes** [comment]
Also found this case we should handle: 
![image](https://user-images.githubusercontent.com/11497541/221715113-e0b1bd0f-d599-47e9-83fb-d8d11345fcb9.png)
