### ISSUE TITLE
Several Strings Remain Untranslated

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#2831]
## Description 
Feedback from a user on Discord regarding French translations. Many strings still fall back to English. Screenshots below.

## Brave version (brave://version info)
0.58.18

### Reproducible on current release:
Yes 

### Screenshots

_Shown below:_

- New tab
- New Window
- New private window
- New private window with Tor
- Favoris (child menu)
  - Bookmark this page
  - Bookmark open pages
  - Show bookmarks bar
  - Bookmark manager
  - Import bookmarks and settings…
  - Imported From Firefox (label suggested by Brave)
- Zoom
- Find
- More tools
  - Save page as…
  - Create shortcut…
  - Clear browsing data…
  - Extensions
  - Task manager
  - Developer tools
- Modifier
  - Cut
  - Copy
  - Paste
- About Brave
- (Context menu on tab)
  - New Tab
  - Pin tab
  - Mute site
  - Close tab
  - Close other tabs
  - Close tabs to the right
  - Reopen closed tab
  - Bookmark all tabs…
- (Context menu on dashboard)
  - Back
  - Forward
  - Reload
  - Save as…
  - Print…
  - Brave
  - View page source
  - Inspect
- (Context menu on image link)
  - Open link in new tab
  - Open link in new window
  - Open link in private window
  - Open link in private window with Tor
  - Save link as…
  - Copy link address
  - Open image in new tab
  - Save image as…
  - Copy image
  - Copy image address
  - Search Google for image
  - Brave
  - Inspect
- (Site Shields)
  - Shields UP|DOWN for this site
  - If a site appears broken, try shields down
  - `# Total Blocked
  - Ads and trackers blocked
  - Connections encrypted
  - 3rd-party cookies blocked
  - All scripts allowed
  - 3rd-party device recognition blocked
  - Global shield defaults

![image](https://user-images.githubusercontent.com/815158/50741706-72e02600-11c6-11e9-8de9-a2912f0769a0.png)

**Comment by bbondy** [comment]
QA notes, you can use the hamburger menu:

Old:
<img width="360" alt="capture d ecran le 2019-01-17 a 17 02 40" src="https://user-images.githubusercontent.com/831718/51351745-bfa2e700-1a79-11e9-9c74-43a997ff890e.png">

All of those english strings will be translated now.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.59.28 Chromium: 72.0.3626.64 (Official Build) beta(64-bit)
-- | --
Revision | eaa9668e80ce5405e7f1902579558ea725c06ca1-refs/branch-heads/3626@{#708}
OS | Windows

Shields panel is not translated. Logged https://github.com/brave/brave-browser/issues/3064

[PASS] Hamburger Menu
![image](https://user-images.githubusercontent.com/34715963/51644905-2e98a800-1f72-11e9-960b-8682d751d1eb.png)

[PASS] Context menu on tab
![image](https://user-images.githubusercontent.com/34715963/51644951-5e47b000-1f72-11e9-9ae9-3b387de1735a.png)

[PASS] Context menu on dashboard
![image](https://user-images.githubusercontent.com/34715963/51644985-80d9c900-1f72-11e9-989a-7e6166f15d67.png)

[PASS] Context menu on image link
![image](https://user-images.githubusercontent.com/34715963/51645049-c4ccce00-1f72-11e9-8c85-5d6ae07709d7.png)
