### ISSUE TITLE
In country selection list for declared geo, place OS region/locale country at top of list

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#28321]
## Description

For better UX, we should place the user's device/OS region/locale at the top of the country dropdown list for ease.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.51.80 Chromium: 112.0.5615.49 (Official Build) beta (x86_64)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | macOS Version 13.3.1 (Build 22E261)
```

**Comment by LaurenWags** [comment]
Removing `QA/Blocked` since https://github.com/brave/brave-browser/issues/29609 has been uplifted to 1.51.x, so this can be retested.

@brave/qa-team please use updated test plan on https://github.com/brave/brave-core/pull/17427. My previous testing comment has been hidden so as to avoid confusion.

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave | 1.51.95 Chromium: 112.0.5615.121 (Official Build) beta (64-bit)
-- | --
Revision | 39cc4e45904ae9f1741c4fbaa866e629c96f2268-refs/branch-heads/5615_51@{#8}
OS | Windows 10 Version 21H2 (Build 19044.2846)

```

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.51.105 Chromium: 112.0.5615.165 (Official Build) beta (x86_64)
-- | --
Revision | c262f36e6b1d711ee42d4fbe1343b49960593f18-refs/branch-heads/5615@{#1297}
OS | macOS Version 13.3.1 (Build 22E261)
```

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.51.105 Chromium: 112.0.5615.165 (Official Build) beta (64-bit) 
-- | --
Revision | c262f36e6b1d711ee42d4fbe1343b49960593f18-refs/branch-heads/5615@{#1297}
OS | Ubuntu 18.04 LTS


<details>
<summary>Clean profile - US - PASSED</summary>

1. Set OS locale to `United States`
2. Install brave `1.51.x`
3. Tap on the BAT icon and click on the `Start Brave Rewards`
4. Click on the country dropdown
5. Confirmed that the country which is set in the OS settings will be in the first place in the country dropdown after installing Brave.

![image](https://user-images.githubusercontent.com/34715963/234923920-9fe46416-51ed-4cf8-84f3-aed7c797ca6a.png)


</details>

<details>
<summary>Clean Profile - PL - PASSED</summary>

1. Set OS locale to `Poland`
2. Install brave `1.51.x`
3. Tap on the BAT icon and click on the `Start Brave Rewards`
4. Click on the country dropdown
5. Confirmed that the country which is set in the OS settings will be in the first place in the country dropdown after installing Brave.

![image](https://user-images.githubusercontent.com/34715963/234925075-5b3e08ee-e878-4f15-885a-ad8120bbf48b.png)


</details>

<details>
<summary>Upgrade - US - PASSED</summary>

1. Set OS locale to `US`
2. Clean install RC `1.50.121` enable rewards 
3. Select `UK` from the country dropdown and connect uphold custodian
4. Confirm that custodian is connected
5. Reset rewards
6. Close the browser
7. Rename the profile to beta
8. Install `1.51.x` beta build
9. Tap on the BAT icon and click on country dropdown
10. Confirmed that the country `US` which is set in the OS settings will be in the first place in the country dropdown after installing Beta.

![image](https://user-images.githubusercontent.com/34715963/234926072-5e7d4fef-ced2-4a7d-9a38-7467731f5c48.png)


</details>

<details>
<summary>Upgrade - PL - PASSED</summary>

1. Set OS locale to `Poland`
2. Install the beta build `1.50.86`
3. Select `UK` from the country dropdown and connect uphold custodian
4. Confirm that custodian is connected
5. Open brave://settings/help
6. upgrade to 1.51.x
7. Tap on the BAT and confirm that uphold is in connected state and country dropdown is not shown
8. Reset rewards
9. Tap on the BAT icon and click on the country dropdown and ensure that the country `Poland` which is set in the OS settings will be in the first place as expected

![image](https://user-images.githubusercontent.com/34715963/234926477-56b6e1a6-913b-441b-82ed-9b4233187792.png)


</details>
