### ISSUE TITLE
Google Sign-In UX improvements: reload tab, only request permission for 3p cookie flows

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#28323]
1. Currently, even if the user grants permission for Google Sign-In for a popup flow, the popup doesn't come up and the user doesn't know they have to click the button again. We should reload the page to make it more obvious to the user that something has changed and they should try clicking the button again.
2. Currently, we bring up the Google Sign-In prompt for some websites that use non-legacy (i.e. not needing 3p cookies) Google Sign-In such as nytimes.com, washingtonpost.com. This is because we can only detect Google auth requests by looking at the URL, and just by looking at the request URL's domain it's not possible to tell them apart. Ideally, we would know what script originated the request but that's not possible without a lot of surgery on URLLoader Throttles. Is there something in the query string that can reveal if the request will use 3p cookies?

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.50.106 Chromium: 112.0.5615.39 (Official Build) beta (64-bit)
-- | --
Revision | a0e7b9718a92bcd1cf33b7c95316caff3fc20714-refs/branch-heads/5615@{#753}
OS | Windows 11 Version 22H2 (Build 22621.1413)
```
Verified testplan from https://github.com/brave/brave-core/pull/17058#issue-1573240006
Note:  More in-depth testing has been done via https://github.com/brave/brave-browser/issues/28440

Case 1: Allowing the Google Sign-In permission prompt on any website in - PASSED

Details

1. Install 1.50.106
2. visit `brave://flags` in a new tab
3. set #brave-google-sign-in-permission to Enabled and relaunched Brave
4. visited `https://500px.com/login` in a new tab and clicked `Login with Google` button
5. confirmed Google Sign-in permission prompt is shown
6. clicked `Allow` in the permission prompt`
7. confirmed page is reloaded.
8. visited `brave://settings/content/googleSignIn`
9. confirmed https://500px.com:443` entry shown in `Allowed to use third-party cookies for legacy Google Sign-In entry` is shown

step 3|step 5|step 8
---|----|---
<img width="461" alt="image" src="https://user-images.githubusercontent.com/98358127/228037029-a668f633-e040-44d1-bb4f-c4b66a082df7.png">|<img width="466" alt="image" src="https://user-images.githubusercontent.com/98358127/228037120-9991c0ee-046e-42b5-bf4f-83e96d4fdbd1.png">|<img width="460" alt="image" src="https://user-images.githubusercontent.com/98358127/228037372-b4535af7-67a2-43bb-ae22-ed0275fcd3fe.png">

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.50.110 Chromium: 112.0.5615.49 (Official Build) (x86_64)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | macOS Version 12.6.4 (Build 21G526)
```
