### ISSUE TITLE
Make Keyboard Shortcuts more Discoverable

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#28329]
Currently, we have a lot of shortcuts but it's hard for user's to discover them. We should add a page where it's possible to view all available shortcuts.

This is a prerequisite for #354, where we want to make the shortcuts configurable.

**Comment by fallaciousreasoning** [comment]
Interesting - I think it should be showing keyboard shortcuts too (it definitely does on Linux)
![image](https://user-images.githubusercontent.com/7678024/225131832-969fdcab-ca78-4c12-9476-b18ceeae2af0.png)

I've got another PR which is going to make a bunch of changes to this, might be worth holding off on this till it lands
https://github.com/brave/brave-core/pull/17296

**Comment by LaurenWags** [comment]
@fallaciousreasoning I see, unless that's going to be uplifted to 1.50.x, we still need to figure out what we're doing for this issue. Perhaps this one should be `QA/No` - esp if it's not fully baked?

wdyt @rebron?

**Comment by fallaciousreasoning** [comment]
`QA/No` is probably a good call - I'll update it :smile:

**Comment by LaurenWags** [comment]
thanks @fallaciousreasoning 😄
