### ISSUE TITLE
Sender account name is not show in transactions for Eth and Sol accounts

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#28333]
## Description 

Sender account name is not show in transactions for Eth and Sol accounts

## Steps to Reproduce

   1. Submit a sign transaction from Eth account
   2. Check the transactions tab
   3. Sender account name is not shown

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/217143293-1f3f0c23-0325-485a-b171-e1f3e5073f10.png)

## Expected result:
Show sending account names

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.48.157 Chromium: 110.0.5481.77 (Official Build) (64-bit)
-- | --
Revision | `65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}`
OS | Windows 11 Version 22H2 (Build 22621.1105)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes on 1.48.x RC builds
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @josheleonard @Douglashdaniel

**Comment by kjozwiak** [comment]
The above requires `1.48.160` or higher for `1.48.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.48.167 Chromium: 110.0.5481.104 (Official Build) (64-bit)
-- | --
Revision | `46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}`
OS | Windows 11 Version 22H2 (Build 22621.1265)

- Verified steps from [brave/brave-core#17081](https://github.com/brave/brave-core/pull/17081)
- Verified all account names are shown in transactions tab
![image](https://user-images.githubusercontent.com/17010094/220386491-913869fe-f60e-4a66-9546-325cb675496a.png)
