### ISSUE TITLE
Feature Re-Request: Bring back blank page for new tab

### ISSUE THREAD

**Issue by marc1uk** [brave/brave-browser#2833]
## Description 
As per Issue #1872 one cannot not set a blank page as the new tab. This issue was referenced to issue #993 which is marked Completed and (it's a little unclear to me but if i'm interpreting correctly) seems to be described as fixed in release 0.58.x.

Running 0.58.18, it is not fixed. Please re-open. 

## version info

Brave | 0.58.18 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Windows
JavaScript | V8 7.1.302.31
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
Command Line | "C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --enable-features=EnableEmojiContextMenu,DesktopPWAWindowing,fill-on-account-select,NewExtensionUpdaterService --disable-features=SharedArrayBuffer,DefaultEnableOopRasterization,VizDisplayCompositor,AutofillSaveCardSignInAfterLocalSave,AutofillServerCommunication,UnifiedConsent --flag-switches-begin --flag-switches-end
Executable Path | C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path | C:\Users\ANNIE\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Variations | c134752e-f685ead32c707b42-dcf7018a411b6d4e-3f4a17dfb7d3b6c2-3f4a17dfd01ab0d3-755bc7553e006338-3f4a17df1a0d11d4-2f9febdf66df3e9d-a85d0b2febeb14fc-3f4a17dfb7e2524c-3f4a17dfb3888d8d-afba0f918982496f-3f4a17df61832c80-3f4a17dfcc20827f-77c422c9041608a-3f4a17df2db4845-ace4e13874785582-3f4a17df241fff6c-ddf208789853922b-3f4a17df125b7f68-3f4a17df9ca1387e-3f4a17df1c752ce9-1c752ce941e765a5-3f4a17df884ba84d-999930aab3d6cfd-3f4a17df776de70c-e0278d3ded9149a9-3f4a17dfa5cb8590-3f4a17df34d450b1-3f4a17df6c6c4f61-3f4a17df8f4db35c-3f4a17df76b48ab8-d4bd105cc70841c8-a256700714bdbe54-e8c7a65b8ee5ed19-c3125ea274658432-fa79b94ced7ba060-3f4a17df9e201a2b-3f4a17df27212adc-27212adc591576c8-3f4a17df249dd49a-3f4a17df5274eb09-3f4a17dfceff87ec-3f4a17df44827ee5-3f4a17df8ca44045-3f4a17df8f1e27f-3f4a17dfedbcf7c5-ddf1844d77bbdddc-3f4a17df5485fc4d-3f4a17dfde47491b-3f4a17df93731dca-3f4a17df9b4c4257-3f4a17df8fa604e0-ace4e13843f62d3b-3f4a17df4ae380f4-3f4a17df165e16d1-3f4a17df9e5c75f1-30e1b12b6fa07eb4-7282ca762981bcb4-3f4a17df5139837c-3f4a17df4934552d-3f4a17df7f8176d9-3f4a17df73a8d7f1-1b1a7908f7217a71-b204717823a898eb-fc93cf744ea303a6-3f4a17dfb19465ab-b19465ab6e6e0c7e-3f17a7d895876445-2b71ffe4d92562a9-441539fdfc369826-3f4a17df2b33233e-881ca6c94da5ae82-3f4a17df56302f8c-2f882e7014c5a050-61ceed18cc54eb06-803f8fc4b2612322-8a9180b2cac0a91c-3f4a17dfdf072bba-9a6c5085f56e0452-3f4a17df8576baf1-3f4a17dff3ea30a0-3f4a17df3038aa2e-3f4a17df51b9b54d-3f4a17df7345ea6-3f4a17df4bc337ce-f483b7fd9a2f4e5b-4bc735aeddf77e2c-63745fe11354da85-f1a864dc17507c76-3f4a17df6844d8aa-669a04e0494d8760-3f4a17df3a4029d-d7f231f3bbb8f811-3f4a17df94e68624-803f8fc4cc73f8a1-3f4a17dfb4e8892d-3f4a17df8834fcca-3f4a17df11d91db8-d93a06206204e469-3f4a17dfea0f933d-3f4a17df493ac2c5-803f8fc4

**Comment by srirambv** [comment]
Should be possible as part of #353.

**Comment by marc1uk** [comment]
thanks for forwarding srirambv.
