### ISSUE TITLE
List sites that have custom shield settings

### ISSUE THREAD

**Issue by TheCodesee** [brave/brave-browser#28337]
If by default I'm set to aggressively block trackers and ads, but I change this on a specific site to allow all trackers and ads, there is no way of keeping track of this change - there is no option in settings to see a list of sites where the default shield settings have been changed.

Shields Status was recently added to settings, allowing users to see sites that follow custom shield settings instead of the default (brave://settings/content/braveShields):

![image](https://user-images.githubusercontent.com/115008744/217239407-0eb8e6ea-f0de-447c-a8fc-1f1905c8a287.png)

However, at present the `Shields up` list only shows subdomains that shields are enabled on, but disabled on the wider domain (e.g enabled on help.brave.com but disabled on brave.com)

I think it would be useful if these sites were moved to a new list named `Subdomain exceptions` and the `Shields up` list instead show sites where shields are enabled but have been changed from the default setting (as I mentioned at the start).

This was requested back in 2020: https://github.com/brave/brave-browser/issues/10829

**Comment by antonok-edm** [comment]
@TheCodesee we want to get this in the browser too, it just needs to be prioritized. Do you mind leaving a 👍 and/or comment on #10829, to keep things together in one place?
