### ISSUE TITLE
Nightly: Tab titles are not visible clearly in OS light mode with dark theme on browser

### ISSUE THREAD

**Issue by dpthegrey** [brave/brave-browser#28335]
## Description 

Tab titles are not visible clearly when the OS is in light mode and the browser theme is dark. But when the browser theme is light, tabs title are visible clearly.

## Steps to Reproduce

   1. Have macOS system light mode
   2. Select Black theme from browser

## Actual result:

![image](https://user-images.githubusercontent.com/49444980/217219318-5df6da19-cc9a-4cb8-9dba-3189fe5a111f.png)

## Expected result:
This is dark mode on system. The browser has black theme, Tab titles are visible
![image](https://user-images.githubusercontent.com/49444980/217220921-ea960b41-65c2-49b5-b18a-e3de20a4a790.png)

## Reproduces how often: 

every time when there is light mode on system and we select black theme from browser

## Brave version (brave://version info)

Version 1.49.81 Chromium: 110.0.5481.52 (Official Build) nightly (x86_64)

## Miscellaneous Information:

Light theme in Light mode works fine

![image](https://user-images.githubusercontent.com/49444980/217219078-03de2eaa-4c2b-4c9f-8675-5afa937f6528.png)

**Comment by dpthegrey** [comment]
Same thing happening in Dark mode with a light theme

![image](https://user-images.githubusercontent.com/49444980/217227857-66116fb6-3e10-4f64-8296-85fa9fc6ee40.png)

**Comment by antonok-edm** [comment]
Looks like it is probably related to vertical tabs. Can you confirm that the issue doesn't occur with the default horizontal tab strip?

cc @sangwoo108

**Comment by dpthegrey** [comment]
only occurs in vertical tabs, does not occur in horizontal tab strip

**Comment by sangwoo108** [comment]
Thanks, @dpthegrey @antonok-edm for letting me know this! Will work on this.
