### ISSUE TITLE
Move vpn helper crash dumps to accessible path

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#28343]
If the service started by system it puts crashes to `c:\Windows\System32\config\systemprofile\AppData\Local\BraveSoftware\Brave-Browser-Development\User Data\Crashpad\reports\` , need to save dumps to `%PROGRAMDATA%\BraveSoftware\{service name}\Crashpad` and update uploader to take crashes from this dir

**Comment by stephendonner** [comment]
Note: this will be tested once, over in https://github.com/brave/brave-browser/issues/25489.  I think we can mark `QA/No` as we don't want to duplicate work.

Or, I guess we can de-scope https://github.com/brave/brave-browser/issues/25489 to not cover crash reporting, and cover it here, instead?

**Comment by stephendonner** [comment]
@spylogsster @LaurenWags @kjozwiak thoughts on the above?

**Comment by LaurenWags** [comment]
If it's fully covered by the testing in the issue you linked @stephendonner then I'm ok with `QA/No`, but I defer to @kjozwiak @spylogsster here since I don't have as much context.

**Comment by stephendonner** [comment]
Marking as `QA/No` - this was verified over in https://github.com/brave/brave-browser/issues/25489#issuecomment-1470899471 in the `Crash reporting` section
