### ISSUE TITLE
No sources card missing on NTP when user not following any sources [News v2]

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#28349]
## Description 
No sources card missing on NTP when user following 0 sources 

## Steps to reproduce 

   1. Install 1.48
   2. Enabled `Brave News v2` in `brave://flags`
   3. Enabled Brave News
   4. Unfollow all sources in the news settings

## Actual result 
Example | Example
-|-
![screenshot-1675794940556](https://user-images.githubusercontent.com/17885425/217336467-3961e4cd-c4c6-4843-90eb-63d5db98dce4.png) | ![screenshot-1675794950245](https://user-images.githubusercontent.com/17885425/217336471-018dede9-c528-45bf-945e-ba33098cb6ea.png)

## Expected result
![Screen Shot 2023-02-07 at 1 53 01 PM](https://user-images.githubusercontent.com/17885425/217339011-3240d531-c2b4-47eb-98c7-202ba345c560.png)

## Issue reproduces how often 
Always

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes (internal beta)
- Can you reproduce this issue with the current Play Store Beta version? TBD
- Can you reproduce this issue with the current Play Store Nightly version? TBD

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung Galaxy S21 5G
   - Android version: Android 13
   
## Brave version
`1.48.158, Chromium 110.0.5481.77`

**Comment by vlad-hoff** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 [panther_beta-user 14 UPB2.230407.019 release-keys]
Brave build: 1.53.83
Chromium: 114.0.5735.110 (Official Build) beta (64-bit)
Revision: 1c828682b85bbc70230a48f5e345489ec447373e-refs/branch-heads/5735_90@{#13}
```
---------------------------

**STEPS:**
1. Launch Brave
2. GO to `brave://flags` > Enable `Enabled Brave News v2`
3. Enabled Brave News > See the content
4. Three-dot Menu > Brave News > Unfollow all sources
5. Return to NTP > Load new content > Verify
6. Tap `Choose content sources > Add some news sources
7. Return to NTP > Load new content > Verify

**ACTUAL RESULTS:**
- Verified that `No content` banner is shown when the user unfollowed all news sources
- Verified that user can add news sources using `No content` banner

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/68c94b38-7482-489c-bf91-5a75604f8896) | ![2](https://github.com/brave/brave-browser/assets/128532965/8df4f44d-0a3a-432e-ba23-6e6af73b19bc) |

**Comment by kjozwiak** [comment]
The above requires `1.52.130` or higher for `1.52.x` verification 👍 Removing the `QA Pass` label as the above will need to be rechecked with `1.52.x`.
