### ISSUE TITLE
Brave News 'back button regression' 

### ISSUE THREAD

**Issue by hollons** [brave/brave-browser#28351]
## Description 

When I select an article after scrolling down on Brave News on Desktop, after I read the article and click 'back', I'm directed to the top of the news feed instead of where I left off when clicking the original article.

## Steps to Reproduce

   1. Scroll down several articles
   2. Click on an article
   3. Click on the back button 

## Actual result:

When clicking back I'm taken to the top of the news feed.

## Expected result:

The expected result would be to be taken to where I left off in the news feed when clicking the original article. 

## Reproduces how often: 

Reproduces every time 

## Brave version (brave://version info)

[Version 1.47.186 Chromium: 109.0.5414.119 (Official Build) (arm64)](https://brave.com/latest/)
macOS Monterey Version 12.6.3

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

**Comment by MadhaviSeelam** [comment]
Verification `PASSED`
```
Brave | 1.51.79 Chromium: 112.0.5615.49 (Official Build) beta (64-bit)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Windows 11 Version 22H2 (Build 22621.1413)
```
Verified and reproduced this issue in 1.50.114

ex|ex|ex
----|----|-----
<img width="453" alt="image" src="https://user-images.githubusercontent.com/98358127/230655890-4db85b29-7b5a-4198-a417-22f18228bd12.png">|<img width="452" alt="image" src="https://user-images.githubusercontent.com/98358127/230655811-b5ab01bc-faaf-4b96-a7c5-4910196a1051.png">|<img width="452" alt="image" src="https://user-images.githubusercontent.com/98358127/230655845-c51c2979-59f8-40ad-9942-5d2bb1fed7fd.png">


1. installed 1.51.79
2. launched Brave
3. opened a new-tab page
4. scrolled a bit
5. clicked Turn on Brave News
6. scroll down several articles
7. click on an article
8. click on the browser back button

#### Confirmed when clicked browser back button, it has navigated to the same news card in the news feed 

https://user-images.githubusercontent.com/98358127/230646477-4169397e-f161-4181-a8bf-0a1fe8889e50.mp4

**Comment by stephendonner** [comment]
## Verification `PASSED` using 

Brave | 1.51.84 Chromium: 112.0.5615.49 (Official Build) beta (x86_64)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | macOS Version 13.4 (Build 22F5027f)

First, reproduced using `1.50.114`

example | example | example
---------|----------|---------
<img width="1312" alt="Screenshot 2023-04-10 at 12 50 08 PM" src="https://user-images.githubusercontent.com/387249/230985191-42dd9312-26be-448c-96b4-a6d13668ea6e.png"> | <img width="1312" alt="Screenshot 2023-04-10 at 12 50 13 PM" src="https://user-images.githubusercontent.com/387249/230985198-820272d6-1ca8-4f88-bb5c-0573a8e70535.png"> | <img width="1312" alt="Screenshot 2023-04-10 at 12 50 18 PM" src="https://user-images.githubusercontent.com/387249/230985201-bb199601-133b-4d55-af19-08188db5e3c4.png">



Steps:

1. installed 1.51.79
2. launched Brave
3. opened a new-tab page
4. scrolled a bit
5. clicked Turn on Brave News
6. scroll down several articles
7. click on an article
8. click on the browser back button

#### Confirmed when clicking the `Back` button after clicking an article, the viewport scroll position isn't lost

![news](https://user-images.githubusercontent.com/387249/230986446-2c9732d9-b722-496c-a5fb-8f58bec58555.gif)
