### ISSUE TITLE
Cache private search provider's template url data

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#28360]
As we can update default search provider list in the future, we should cache private search provider's template url data.
If we can use cached template url data for private window's search provider, we can set and use previous default search provider
even if new default search provider list doesn't include it.

* STR
1. Load brave://prefs-internals/
2. check `default_private_search_provider_data` is cached
3. check `default_private_search_provider_data.synced_guid` and `default_private_search_provider_guid` is same

**Comment by LaurenWags** [comment]
@simonhong are there any other pre-requisites for this? I visited `brave://prefs-internals/` and searched for `default_private_search_provider_data` but it wasn't found. 

Maybe I missed some steps? Any additional information is appreciated.

**Comment by simonhong** [comment]
@LaurenWags Hmm, it's strange. There is no prerequisites for this.
I can see `default_private_search_provider_data` with fresh profile or existing profile both.

**Comment by LaurenWags** [comment]
Thanks @simonhong I'll try again - I thought I copied and pasted the search item, but perhaps I mistyped it instead 🤔

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.50.91 Chromium: 111.0.5563.64 (Official Build) beta (x86_64)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | macOS Version 12.6.3 (Build 21G419)
```
