### ISSUE TITLE
Fix SAND contract address in Sardine buy token list

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#28364]
The correct contract address for SAND should be `0x3845badAde8e6dFF049820680d1F14bD3903a5d0`. The address in Sardine token list is `0x0000000000085d4780B73119b644AE5ecd22b376`, it is incorrect.

**Comment by srirambv** [comment]
Marking issue as `QA/Blocked` since there is no value shown for the token in Buy widget. cc: @HEagle18 @muliswilliam 

![image](https://user-images.githubusercontent.com/17010094/226544988-a557534f-454a-4656-85d4-37f2eff1483f.png)

**Comment by srirambv** [comment]
Moving this out of 1.50.x milestone as discussed [here](https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1680088781789039?thread_ts=1679382063.908819&cid=C023VS4HJ6Q). @muliswilliam if we end up doing a different PR to fix this then please add a follow up issue for this and assign the appropriate milestone for it


cc: @HEagle18 @jamesmudgett @bbondy @kjozwiak  for visibility
