### ISSUE TITLE
Console errors on `brave://wallet-panel.top-chrome/`  

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#28365]
## Description 

Console errors on `brave://wallet-panel.top-chrome/`  

## Steps to Reproduce

   1. Open `brave://wallet-panel.top-chrome/`
   2. Open Dev Tools
   3. Throws error about `This document requires 'TrustedScript' assignment.` (Release/Beta/Nightly)
   4. Nightly build shows additional error `'Unable to parse JSON'`

## Actual result:

Release | Beta | Nightly
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/217463979-711d301e-a8b2-4032-bf97-3735a742d842.png) | ![image](https://user-images.githubusercontent.com/17010094/217464059-96a6e6f6-3e9e-4738-9a3f-b98f3db850d6.png) | ![image](https://user-images.githubusercontent.com/17010094/217463929-fdd4a92d-0061-4446-9fb1-43d2f92d0d98.png)

## Expected result:
No errors

## Reproduces how often: 

Easy

## Brave version (brave://version info)

All

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes partial
- Can you reproduce this issue with the beta channel? Yes partial
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel @onyb @josheleonard @muliswilliam

**Comment by Douglashdaniel** [comment]
Made a separate issue to address the `'Unable to parse JSON'` error  https://github.com/brave/brave-browser/issues/28437

**Comment by josheleonard** [comment]
@srirambv , do you still see the TrustedScript log?

**Comment by srirambv** [comment]
Not seeing the issue anymore. Closing the issue as stale
