### ISSUE TITLE
Manifest V2 Support for Select Extensions. [Part 1]

### ISSUE THREAD

**Issue by boocmp** [brave/brave-browser#28367]
## Description 

SPEC: https://docs.google.com/document/d/1fyt_kQv51nkuPOOTz-zgshYq6gLlq2CayqcrZIKTh7k/edit#heading=h.ls63kcwg56s1

Part 1:
Implement "Manifest V2 Extensions" section under the brave://settings/extensions
Add NoScript, uBlock Origin, uMatrix, AdGuard extensions.

**Comment by stephendonner** [comment]
## Verifications `IN-PROGRESS` using 

Brave | 1.51.77 Chromium: 112.0.5615.49 (Official Build) beta (x86_64)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | macOS Version 11.7.5 (Build 20G1225)

### Shared Steps:
1. installed `1.51.77`
2. launched Brave using `--enable-features=ExtensionsManifestV2`
3. opened `brave://settings/extensions`
4. clicked on `Manifest V2 extensions`
5. confirmed new listing of `Enable NoScript`, `Enable uBlock Origin`, `Enable uMatrix`, and `Enable AdGuard` panels with toggles
6. confirmed all V2 extensions were toggled, default, to `Off` / `Disabled/uninstalled`



step 2 | step 3 | step 5
-------|-------|--------
<img width="682" alt="Screen Shot 2023-04-05 at 5 57 43 PM" src="https://user-images.githubusercontent.com/387249/230246355-8d0b026d-c89c-44f4-8874-289069f843b5.png"> | <img width="1312" alt="Screen Shot 2023-04-05 at 5 49 01 PM" src="https://user-images.githubusercontent.com/387249/230246140-eafe85a3-53ee-46a5-8ca4-79d6e7aa582a.png"> | <img width="1312" alt="Screen Shot 2023-04-05 at 5 56 42 PM" src="https://user-images.githubusercontent.com/387249/230246188-a16d5f8e-4747-4f0b-875a-0b2410bc6fdb.png">
