### ISSUE TITLE
Solana Transactions are not shown under Activity tab

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#28368]
## Description 

Solana Transactions are not shown under Activity tab

## Steps to Reproduce

   1. Install 1.50.19
   2. Submit a Solana Transaction
   3. Doesn't show the transaction under Activity Tab
   4. Open Solana Account from Accounts tab
   5. Transactions are listed under the account

## Actual result:

Activity Tab | Account Tab
-- | --
![image](https://user-images.githubusercontent.com/17010094/217512408-8bcb6a16-a86c-4db3-b383-e075cc0c0b4c.png) | ![image](https://user-images.githubusercontent.com/17010094/217512658-09718ddf-71c2-4bfa-bd1f-b64e480393fe.png)

## Expected result:
Should list Solana Transactions under Activity tab

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.50.19 Chromium: 110.0.5481.77 (Official Build) nightly (64-bit)
-- | --
Revision | `65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}`
OS | Linux

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel @josheleonard @muliswilliam @onyb

**Comment by josheleonard** [comment]
Resolved by: https://github.com/brave/brave-core/pull/18379

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.57.18 Chromium: 115.0.5790.98 (Official Build) beta (64-bit)
-- | --
Revision | `d515871a6c6df7d2843e755c8b7dda9b744f26d6`
OS | Windows 11 Version 22H2 (Build 22621.1992)

- Verified steps from issue description
- Verified Solana transactions are shown under Activity tab and Account details screen

https://github.com/brave/brave-browser/assets/17010094/03c61d90-eeb2-496e-82fc-448f2b76bda7
