### ISSUE TITLE
Session cookies are persisted on session restore

### ISSUE THREAD

**Issue by goodov** [brave/brave-browser#28379]
Chromium implements session cookie restore to persist them during updates (browser restart), but this is also applied when "Continue where you left off" is enabled. It's unclear if this is intentional, but this in fact allows these cookies to live much longer than other "persisted" cookie variants.

You can try this test https://bayden.com/test/sessions/
All Chromium browsers persists session cookies (but not sessionStorage) across page closes and browser resets in "Continue where you left off" mode.

An article from Eric Lawrence which also covers this topic:
https://textslashplain.com/2019/06/24/surprise-undead-session-cookies/

**Comment by goodov** [comment]
#### Test case 1 (quit+open)

1. Ensure "Continue where you left off" is enabled.
2. Open https://bayden.com/test/sessions/ and choose `lightcyan` from selector.
3. Ensure `sessionCookie says color is: lightcyan`.
4. Fully quit browser.
5. Open browser.
6. Expect the session is restored and the website is still opened.
7. Refresh the page (Ctrl/Cmd+R).
8. Expect sessionCookie is `undefined`.

#### Test case 2 (brave://restart)

1. Ensure "Continue where you left off" is enabled.
2. Open https://bayden.com/test/sessions/ and choose `lightcyan` from selector.
3. Ensure `sessionCookie says color is: lightcyan`.
4. Restart the browser via `brave://restart`.
5. Expect the session is restored and the website is still opened.
6. Refresh the page (Ctrl/Cmd+R).
7. Expect sessionCookie is `lightcyan`.

#### Test case 3 (browser update)

1. Install slightly old `nightly` version which includes this fix, but which will want to update.
2. Ensure "Continue where you left off" is enabled.
3. Open https://bayden.com/test/sessions/ and choose `lightcyan` from selector.
4. Ensure `sessionCookie says color is: lightcyan`.
5. Apply update via "Update" button, browser should restart automatically.
6. Expect the session is restored and the website is still opened.
7. Refresh the page (Ctrl/Cmd+R).
8. Expect sessionCookie is `lightcyan`.

#### Test case 4 (disabled feature, old behavior)

1. Launch browser with `--disable-features=BraveCleanupSessionCookiesOnSessionRestore`.
2. Ensure "Continue where you left off" is enabled.
3. Open https://bayden.com/test/sessions/ and choose `lightcyan` from selector.
4. Ensure `sessionCookie says color is: lightcyan`.
5. Fully quit browser.
6. Open browser.
7. Expect the session is restored and the website is still opened.
7. Refresh the page (Ctrl/Cmd+R).
8. Expect sessionCookie is `lightcyan`.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.50.92 Chromium: 111.0.5563.64 (Official Build) beta (x86_64)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | macOS Version 12.6.3 (Build 21G419)
```

**Comment by goodov** [comment]
> Test case 3 (browser update) - FAILED, follow up issue logged

I dig a little and found a PR which tries to fix the restart on MacOS. Right now it doesn't work as expected. It's pretty crazy how the "update restart" currently works on MacOS.

https://github.com/brave/brave-core/pull/15257/files#r1140262599

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.50.101 Chromium: 111.0.5563.116 (Official Build) beta (64-bit)
-- | --
Revision | ade86b9472831e26d87fd569e04b404be01e1e2b-refs/branch-heads/5563@{#1209}
OS | Windows 11 Version 22H2 (Build 22621.1413)
```

**Comment by goodov** [comment]
> Test case 5 (disabled feature, old behavior) - FAILED

that's weird. Can you please check `brave://version` after reopening that `--disable-features` parameter is there?

this is what I got:

https://user-images.githubusercontent.com/5928869/227887973-5aa7d956-d7a7-44c8-aaa4-6d2403f3b503.mp4

> Regression set 1 - "Open the New Tab page" - `FAILED` setting
> Regression set 2 - "Open a specific page or set of pages" setting - FAILED

The failed regression cases where you use MacOS as a baseline are initially not exactly correct. The browser **should** restore an old session after a restart triggered by an update *no matter what the current restore mode is selected*. The reason why the browser doesn't do it on MacOS is because of [this](https://github.com/brave/brave-core/pull/15257/files#r1140262599).

So this inconsistency with MacOS is currently expected, but we should use Windows version as the baseline in the update-restart test cases. The browser should restore the active session during update-restart **no matter what the session restore option is selected**. That's the thing we currently miss on MacOS and is visible only when "Continue where you left off" is not selected.

**Comment by ShivanKaul** [comment]
@goodov are session cookies expected to persist between browser restarts on MacOS? I have `Continue where you left off` turned on in latest Nightly on MacOS, and see that the session cookie persists after a browser restart. I'm using https://bayden.com/test/sessions/ to test.

**Comment by ShivanKaul** [comment]
https://github.com/brave/brave-browser/assets/5284154/9f93a165-e14a-4569-b8b0-bf191e3e5c4d

**Comment by goodov** [comment]
> @goodov are session cookies expected to persist between browser restarts on MacOS? I have `Continue where you left off` turned on in latest Nightly on MacOS, and see that the session cookie persists after a browser restart. I'm using https://bayden.com/test/sessions/ to test.

yes. We need to fix the update process on MacOS for this feature to work properly. https://github.com/brave/brave-browser/issues/25576

**Comment by ShivanKaul** [comment]
That issue deals with the case where there's a pending browser update though right? I don't have a pending browser update. I'm able to repro with Brave Release as well.

**Comment by LaurenWags** [comment]
@ShivanKaul afaik this issue was not implemented on macOS due to the issue I faced in https://github.com/brave/brave-browser/issues/29135 which I believe is related to what @goodov noted in https://github.com/brave/brave-browser/issues/28379#issuecomment-1639612213.

**Comment by ShivanKaul** [comment]
That's v helpful, thanks @LaurenWags! I've updated this issue's description to make that clearer.

**Comment by LaurenWags** [comment]
good call, thanks @ShivanKaul. We should have clarified what happened previously 👍🏻

**Comment by goodov** [comment]
> That issue deals with the case where there's a pending browser update though right? I don't have a pending browser update. I'm able to repro with Brave Release as well.

We don't enable the feature because it breaks the update-restart case where session cookies should be kept.

**Comment by Geod24** [comment]
I was looking into this change, as it breaks my organisation's use of Brave, and wanted to control it via policy. I found https://support.brave.com/hc/en-us/articles/360039248271-Group-Policy but it seems that this specific setting is not exposed via a policy ?

**Comment by ShivanKaul** [comment]
@Geod24 can you create a new issue? It would be great if you can also mention what platforms you're interested in, and any other details.
