### ISSUE TITLE
Unable to view submitted Solana transactions in Activity tab

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#28378]
## Description 

Submitted Solana transactions are not appearing in the Activity tab
Regression caused by [feat: cache account transaction data](https://github.com/brave/brave-core/pull/16711#top)

## Steps to Reproduce

   1. Submit a Solana transaction
   2. Open Activity tab
   3. Transaction should be displayed within the transaction list

## Actual result:

Transaction is not displayed within the transaction list

## Expected result:
Transaction should be displayed within the transaction list

## Reproduces how often: 

Easy

## Brave version (brave://version info)

[1.49.x - Beta](https://github.com/brave/brave-core/milestone/260)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.49.97` or higher for `1.49.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta  (64-bit) 
-- | --
Revision | `46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}`
OS | Linux

- Verified steps from [brave/brave-core#17105](https://github.com/brave/brave-core/pull/17105)
- Verified all transactions are listed under Activity tab
![image](https://user-images.githubusercontent.com/17010094/221897845-2d1d053e-c00b-4a3c-bd92-2de298cbc53c.png)


---------------------

Verification passed on 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta  (64-bit)
-- | --
Revision | `46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#17105](https://github.com/brave/brave-core/pull/17105)
- Verified all transactions are listed under Activity tab
![image](https://user-images.githubusercontent.com/17010094/221901198-9aa21d89-47d0-445e-9f09-1eea8c088290.png)

---------------------

Verification passed on 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta  (arm64)
-- | --
Revision | `46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#17105](https://github.com/brave/brave-core/pull/17105)
- Verified all transactions are listed under Activity tab
![image](https://user-images.githubusercontent.com/17010094/221905061-8d6616f9-cfa5-4454-a6b8-465391b627ea.png)
