### ISSUE TITLE
Pending Filecoin transactions cannot be approved

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#28376]
## Description 

Regression caused by: https://github.com/brave/brave-core/pull/16945#top
Filecoin transactions cannot be approve due to it waiting for EIP1559 gas estimates for the TX, which never resolve for FIL txs.

## Steps to Reproduce

   1. Create a Filecoin Send transaction
   2. View the pending transaction in the panel

## Actual result:

The confirm button is disabled, even though network fees are available and visible
Additional loading indicators are shown

## Expected result:
The confirm button should be enabled and gas fees should be shown
No loading indicators should be shown for gas/network fee values

## Reproduces how often: 

Easy

## Brave version (brave://version info)

[1.50.x - Nightly](https://github.com/brave/brave-core/milestone/268) as of https://github.com/brave/brave-core/pull/16945#top

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by josheleonard** [comment]
duplicate of https://github.com/brave/brave-browser/issues/28369

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.50.93 Chromium: 111.0.5563.64 (Official Build) beta  (64-bit) 
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Linux

- Verified steps from [brave/brave-core#17103](https://github.com/brave/brave-core/pull/17103)
- Verified able to submit FIL transactions

https://user-images.githubusercontent.com/17010094/225883662-97e70228-8b92-46f7-b66c-327ea1cbeefa.mp4

---------------------

Verification passed on 

Brave | 1.50.93 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from [brave/brave-core#17103](https://github.com/brave/brave-core/pull/17103)
- Verified able to submit FIL transactions

https://user-images.githubusercontent.com/17010094/225882724-c51f19e5-5b64-43b2-b6f9-80542108b9a1.mp4

---------------------

Verification passed on 

Brave | 1.50.93 Chromium: 111.0.5563.64 (Official Build) beta (arm64)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#17103](https://github.com/brave/brave-core/pull/17103)
- Verified able to submit FIL transactions

https://user-images.githubusercontent.com/17010094/225883438-44281b8e-c8dc-46d1-8192-12f0125eb3b8.mov
