### ISSUE TITLE
x64 version of Brave fails check for update on Arm64 desktop devices

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#28380]
## Description 

Brave update check is failing after downloading Brave via website.  However, no errors shown during update check when installed via test installer `BraveBrowserSetup-a64-r-test.exe`

## Steps to Reproduce

   1.  uninstall existing Brave Installers
   2.  download current release (`Windows 64-bit`) from  [brave.com/download](http://brave.com/download) via Edge
   3.  Accept the UAC prompt with "Yes"
   4.  open `brave://settings/help` 

## Actual result:

`Update check failed to start` error shown

<img width="754" alt="image (3)" src="https://user-images.githubusercontent.com/98358127/217603574-6bcf86f1-e6c4-448c-b19e-0dd40d71bc99.png">

## Expected result:
No errors should be shown
![image](https://user-images.githubusercontent.com/98358127/217603621-9836fbd1-bf26-44b1-85b8-88434aeb1960.png)

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.48.158 Chromium: 110.0.5481.77 (Official Build) (64-bit)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | Windows 11 Version 22H2 (Build 22621.1105)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

Background updates via the Windows Task Scheduler do work.

**Comment by mherrmann** [comment]
We are now working around this issue by installing Arm64 Brave on Arm64 Windows with a universal online installer that installs the correct architecture for the user's system. For technical reasons to do with COM registration, it is not possible to make on-demand updates work in both x64 and Arm64 Brave on Arm64 Windows. I am closing this issue as "wontfix".
