### ISSUE TITLE
No data is imported when importing from Yandex with multiple profiles 

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#28384]
## Description 

When attempted to import from Yandex with multiple profiles, no data was imported.  However, bookmarks, history and extensions are successfully imported from single Yandex profile.  

## Steps to Reproduce

   1. Install 1.49.89
   2. launch Brave
   3.  Select Yandex 
   4. click `Select All` 
   5. click `Import Profiles` 
   6. click `Finish`
   
## Actual result:

No data imported into Brave

https://user-images.githubusercontent.com/98358127/217627600-d48faaac-52a5-46af-a923-6217cfcec2c0.mp4

## Expected result:
Bookmarks, History and Extensions should be imported and should be shown in bookmarks bar, brave://history and  brave://extensions

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.49.89 Chromium: 110.0.5481.77 (Official Build) beta (64-bit)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | Windows 11 Version 21H2 (Build 22000.1455)
```
## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
@rebron @spylogsster 
cc: @stephendonner

**Comment by MadhaviSeelam** [comment]
@rebron I've filed this issue where no data is imported (e.g no bookmarks shown in bookmarks bar) before realizing https://github.com/brave/brave-browser/issues/27591 was landed. @spylogsster mentioned that this was landed 1.49.x and issue might be redundant. I've retested and confirmed imported data is contained in their newly created profiles and shown in the Profile manager. However, I just wanted to confirm  after completing the importing process, bookmarks bar in the new-tab page will not show any imported bookmarks and bookmarks will show only when imported from `brave://settings/importData`
cc: @brave/qa-team

**Comment by rebron** [comment]
Want to confirm that when switching profiles you do see the bookmarks for that profile imported properly.

**Comment by MadhaviSeelam** [comment]
@rebron Yes bookmarks are imported correctly for all imports.  Closing this bug since it's working as expected

ex|ex|ex|ex
---|---|---|---
<img width="454" alt="image" src="https://user-images.githubusercontent.com/98358127/217965900-586c6cbf-594a-4076-89e5-8f1f1c625f62.png">|<img width="454" alt="image" src="https://user-images.githubusercontent.com/98358127/217965925-d8165875-c16a-4154-8578-6518c4e77489.png">|<img width="457" alt="image" src="https://user-images.githubusercontent.com/98358127/217966013-105a6f6b-e8c5-4fe0-91e5-5ef70d17f6a9.png">|<img width="454" alt="image" src="https://user-images.githubusercontent.com/98358127/217965940-ead7c613-8aa9-48e5-a11c-a68d07a7335e.png">
