### ISSUE TITLE
Computer name is missing in Let’s sync a new device with “”. (Follow up of #2728)

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#2839]
## Description 
Computer name is missing in Let’s sync a new device with “”. 

## Devices
Device 1: Windows 10 x64 (0.60.6 dev build)
Device 2: Android Samsung Galaxy 5.1 (1.0.72 (sync1))

## Steps to Reproduce

   1. Clean install 0.60.6
   2. Sync Windows and Android devices through QR code
   3. Once sync is established between two devices leave the sync chain on Windows
   4. Click on Start new sync chain. 

## Actual result:

![image](https://user-images.githubusercontent.com/38657976/50765774-fc622780-129c-11e9-9209-d8b1748fc9a6.png)
![computer name missing - 0 60 6](https://user-images.githubusercontent.com/38657976/50765787-02f09f00-129d-11e9-8b7d-4d25b3b1f985.gif)

## Expected result:
![image](https://user-images.githubusercontent.com/38657976/50765818-1dc31380-129d-11e9-8ab8-69deed7d08bf.png)

## Reproduces how often: 
Always

## Brave version (brave://version info)

Brave | 0.60.6 Chromium: 72.0.3626.28 (Official Build) dev (64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Windows

### Reproducible on current release: NO
- Does it reproduce on brave-browser dev/beta builds? reproducible only Dev not on Beta

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional Information
Could be merge issue PR 1191 says it's already merged to dev channel. Also, before the version bump 0.60.6, PR 1191 commit is available.

@brave/legacy_qa

**Comment by srirambv** [comment]
@GeetaSarvadnya could you please retest this on current beta build and see if it reproduces?

**Comment by GeetaSarvadnya** [comment]
@srirambv Now there is no computer name display on `Start new sync chain`. Not able to reproduce the issue on both Beta (0.59.25) and Dev (0.60.15) builds.

**Comment by srirambv** [comment]
@cezaraugusto this is fixed as part of the https://github.com/brave/brave-core/pull/1193?

**Comment by kjozwiak** [comment]
Where was this fixed @cezaraugusto? We'll need to stick it into the correct milestone as it's closed but still in the `1.x Backlog`. Assuming this was changed in `0.59.x` with the UI redesign?

**Comment by srirambv** [comment]
Marking as `0.59.x` the new UI flow fixed the issue which should be part of general sync flow test.
