### ISSUE TITLE
"Don't warn me about this site again" in the strict-blocking creates too permissive rules

### ISSUE THREAD

**Issue by Yuki2718** [brave/brave-browser#28390]
It now creates `@@||example.com^` but this should be `@@||example.com^$document` only allowing strict-blocking.

**Comment by antonok-edm** [comment]
Great catch, thanks! We definitely shouldn't be exempting it globally.

Makes me wonder if it's worth experimenting with `@@||example.com^$first-party` as an option too.

**Comment by Yuki2718** [comment]
> @@||example.com^$first-party

That's better than the current one, but can still allow too much given Brave blocks 1p ads/tracker once set to Aggressive mode.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 13` using the following build(s):

```
Brave | 1.50.113 Chromium: 112.0.5615.49 (Official Build) (32-bit)
--- | ---
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Android 13; Build/TQ2A.230305.008.E1
```

Using the STR/Cases outlined via https://github.com/brave/brave-core/pull/17117#issue-1576972995, verified that everything was working as expected as per:

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------|----------------|----------------|----------------|----------------|-----------------
![Screenshot_20230404-154354](https://user-images.githubusercontent.com/2602313/229904533-551eca49-93fa-4af1-9cde-ccfe958833bb.png) | ![Screenshot_20230404-154418](https://user-images.githubusercontent.com/2602313/229904541-e4f5eb0b-da2b-4162-8a65-ab263c1af15a.png) | ![Screenshot_20230404-154550](https://user-images.githubusercontent.com/2602313/229904552-3f688536-b149-4af4-9d1a-5bcb9ff95805.png) | ![Screenshot_20230404-154632](https://user-images.githubusercontent.com/2602313/229904563-2fb691ff-ef97-42ce-8d7b-36bfb53177e0.png) | ![Screenshot_20230404-154657](https://user-images.githubusercontent.com/2602313/229904575-4e76bb0c-640c-4859-aef7-5a341d01a3bf.png) | ![Screenshot_20230404-154707](https://user-images.githubusercontent.com/2602313/229904603-8b27c9f5-fcaf-4f09-bd0f-7f565f4d6642.png) | ![Screenshot_20230404-154719](https://user-images.githubusercontent.com/2602313/229904618-fb71a9d8-eb7f-42ed-9944-ff1d5f03ab7d.png) | ![Screenshot_20230404-154731](https://user-images.githubusercontent.com/2602313/229904631-9229e8e1-d8ee-4eb4-9999-2f402c5e057a.png)
