### ISSUE TITLE
Reports of Background Audio is not working properly

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#28392]
## Description 

We see a few reports of Background Audio is not working properly

https://appfigures.com/reviews/266342430751Lpc2IEyq0bW3DV1cXaWRZug?lang=en
https://appfigures.com/reviews/266342430751LLi6J5ou4HlLBJEhwnBmUfg?lang=en

**Comment by SergeyZhukovsky** [comment]
I've tried it on 2 devices. Played with diff apps when the bg audio is on, turned the screen on and off and everything worked smoothly. Not sure what is going on, my guess is something with CPU on problem devices.

**Comment by anthonypkeane** [comment]
can't reproduce, closing the issue.
