### ISSUE TITLE
Wallet is showing the last screen instead of lock screen when browser is reopened

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#28402]
## Steps to Reproduce

   1. Open Buy/Deposit
   2. Close browser and open again
   3. Buy/Deposit is still there, close buy and lock screen is shown

## Actual result:

[wallet is showing the last screen instead of lock screen when closing browser.webm](https://user-images.githubusercontent.com/11755381/217855632-c13c071b-46c8-49de-9597-00d6c3eb5a76.webm)

## Expected result:
Should show the wallet lock screen (I think)

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Version 1.50.20 Chromium: 110.0.5481.77 

## Version/Channel Information:

- Can you reproduce this issue with the current release? N
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? Y

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.50.93 Chromium: 111.0.5563.64 (Official Build) beta  (64-bit) 
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Linux

- Verified steps from issue description
- Verified closing browser with Buy/Deposit screens shows unlock wallet screen after restart

https://user-images.githubusercontent.com/17010094/225818495-63447888-e71b-4e11-9551-afa2f0a70a7c.mp4

---------------------

Verification passed on 

Brave | 1.50.93 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from issue description
- Verified closing browser with Buy/Deposit screens shows unlock wallet screen after restart

https://user-images.githubusercontent.com/17010094/225818284-47c1d3c9-a1f3-4b82-a07d-dfc0d81166ce.mp4

---------------------

Verification passed on 

Brave | 1.50.93 Chromium: 111.0.5563.64 (Official Build) beta (arm64)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from issue description
- Verified closing browser with Buy/Deposit screens shows unlock wallet screen after restart

https://user-images.githubusercontent.com/17010094/225818674-31384e6d-b85f-4a9b-9644-bfebade8f22d.mov
