### ISSUE TITLE
gallery.io gets blocked

### ISSUE THREAD

**Issue by dy** [brave/brave-browser#2840]
Material components website https://gallery.io does not load due to brave.
![image](https://user-images.githubusercontent.com/300067/50779147-9c07c180-126d-11e9-86fe-51c89865f468.png)

Disabling shields makes it work.
Version 0.58.18 Chromium: 71.0.3578.98 (Official Build) (64-bit)

**Comment by ryanbr** [comment]
Re-tested. Still an issue. `Allow all cookies` will fix this.
