### ISSUE TITLE
Misalignment issue on rewards page for non us locales

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#28403]
## Description 
Misalignment issue on rewards page for non us locales

## Steps to reproduce 

   1. Install 1.48.160
   2. Set device language to French or German
   3. Launch app, enable rewards
   4. Open `brave://rewards` page

## Actual result 
Menu and switch misaligned on page

Example | Example | Example
-|-|-
![screenshot-1675955941185](https://user-images.githubusercontent.com/17885425/217857083-d9ca610b-89ad-4c79-9922-152e5ed64acf.png) | ![screenshot-1675955971851](https://user-images.githubusercontent.com/17885425/217857092-fc1750cd-efbf-4ba6-8ce6-779a25f45f55.png) | ![screenshot-1675954935421](https://user-images.githubusercontent.com/17885425/217857213-256ea1b2-845c-4849-93d1-bd0e391bfade.png)

## Expected result
Page should display properly

## Issue reproduces how often 
Always

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes (Internal Beta)
- Can you reproduce this issue with the current Play Store Beta version? TBD
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet):Samsung Galaxy S21 5G, Pixel 3XL
   - Android version: 13, 12
   
## Brave version
1.48.160

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above will require `1.48.163` or higher for `1.48.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung GS 21` using version:

```
Brave	1.48.166 Chromium: 110.0.5481.100 (Official Build) (64-bit) 
Revision	4be7a36f7cb943af6118e449bbab494b43dcaddd-refs/branch-heads/5481_77@{#14}
OS	Android 13; Build/TP1A.220624.014
```
- Ensured that after enabling rewards profile, loading `brave://rewards` page does not have overflow issues with the header
- Ensured that brave://rewards page is displayed properly using `German` and `French` locales

Example | Example
-|-
![screenshot-1676648547975](https://user-images.githubusercontent.com/17885425/219700451-86cfa153-ea48-4b03-874f-727105e32094.png) | ![screenshot-1676648556163](https://user-images.githubusercontent.com/17885425/219700453-80740ae3-1de1-46ec-930d-11445d15f87c.png)
![screenshot-1676648225365](https://user-images.githubusercontent.com/17885425/219700508-ff48ea07-f37c-4f20-b5bc-176167fdb00a.png) | ![screenshot-1676648243222](https://user-images.githubusercontent.com/17885425/219700510-2e9108eb-62c6-4a67-b5c6-7ef98e535078.png)
