### ISSUE TITLE
Show pending transactions in descendant order

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#28409]
When there are pending transactions and users adds a new one then old transaction is shown in the wallet panel.
We need to show them in desc order.

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.53.94 Chromium: 114.0.5735.133 (Official Build) beta (64-bit)
-- | --
Revision | `fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}`
OS | Windows 11 Version 22H2 (Build 22621.1848)

- Verified steps from [brave/brave-core#18310](https://github.com/brave/brave-core/pull/18310)
- Verified the most recent unapproved transaction is shown first
- Verified the first submitted unapproved transaction is shown last
- Encountered [#31140](https://github.com/brave/brave-browser/issues/31140)

https://github.com/brave/brave-browser/assets/17010094/f474f843-9c0a-4b2a-9937-1ceb665cd503
