### ISSUE TITLE
Use nft gateway when fetching the image specified in NFT metadata

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#28407]
We have kIPFSPublicNFTGatewayAddress pref that is used to fetch NFT metadata. But it also should be used in the wallet interface when show NFT image.

Below is the bug report from @dolcegabana with clear description and steps:
## Description 

When using the custom IPFS gateway for NFT assets, the custom gateway is used to resolve the IPFS address from the ERC-721 token, but when trying to display the image referenced in the metadata.json file of the same NFT, http://ipfs.io is used as the gateway regardless of the configured gateway.

## Steps to Reproduce

   1. Configure a custom gateway to resolve NFT assets
   2. Register an NFT in the visible assets screen of the portfolio
   3. View the NFT
   4. Use chromium's F12 mode to inspect the displayed image

## Actual result:
displayed image's URL is using ipfs.io as host instead of the custom gateway

## Expected result:
displayed image's URL is using the custom gateway as the host.

## Brave version (brave://version info)
1.48.171 Chromium: 110.0.5481.177 (Official Build) (64-bit)
f34f7ab2d4ca4ad498ef42aeba4f4eb2c1392d63-refs/branch-heads/5481@{https://github.com/brave/brave-browser/issues/1239}
Windows 10 Version 1803 (Build 17134.2208)

**Comment by kjozwiak** [comment]
The above requires `1.51.79` or higher for `1.50.x` verification 👍

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.51.80 Chromium: 112.0.5615.49 (Official Build) beta (64-bit) 
-- | --
Revision | `bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}`
OS | Linux

- Verified steps from issue description
- Verified displayed NFT image's URL is using the custom gateway as the host
![image](https://user-images.githubusercontent.com/17010094/230890364-fffb73bc-5f5f-4b07-a20f-7090779696a8.png)

---------------------

**Verification passed on**

Brave | 1.51.80 Chromium: 112.0.5615.49 (Official Build) beta (64-bit)
-- | --
Revision | `bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from issue description
- Verified displayed NFT image's URL is using the custom gateway as the host
![brave_YSCRi4dLS9](https://user-images.githubusercontent.com/17010094/230890563-8f56e3f2-845e-483d-98bc-b85b3e283670.png)

---------------------
**Verification passed on**

Brave | 1.51.80 Chromium: 112.0.5615.49 (Official Build) beta (arm64)
-- | --
Revision | `bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from issue description
- Verified displayed NFT image's URL is using the custom gateway as the host
![image](https://user-images.githubusercontent.com/17010094/230890895-9cdc19c9-2544-4c45-851c-c22e07797742.png)
