### ISSUE TITLE
Add additional currencies that Transak supports to buy flow

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#28412]
## Description 

Right now, we only support USD, EUR and GBP on the buy flow. But we should extend that to other countries that Transak supports. 

## Steps to Reproduce

   1. 
   2. 
   3. 

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by muliswilliam** [comment]
@Pavneet-Sing @nuo-xu I added new currencies to currency list, please make sure Android and iOS are working as expected.

**Comment by Pavneet-Sing** [comment]
Thanks though Android yet to have a currency selector https://github.com/brave/brave-browser/issues/27679

**Comment by nuo-xu** [comment]
thank you @muliswilliam 
I've tested iOS with latest core, im seeing all these newly added currencies. and it works correctly for Transak provider.

**Comment by srirambv** [comment]
Removing `OS/Android` label based on https://github.com/brave/brave-browser/issues/28412#issuecomment-1451494540. Android specific issue is #27679

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.50.93 Chromium: 111.0.5563.64 (Official Build) beta  (64-bit) 
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Linux

- Verified steps from [brave/brave-core#17388](https://github.com/brave/brave-core/pull/17388)
- Verified Transak landing page uses the selected currency on the purchase widget

https://user-images.githubusercontent.com/17010094/225858834-982a7ea9-43f7-4896-981e-9b1390658a1b.mp4

---------------------

Verification passed on 

Brave | 1.50.93 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from [brave/brave-core#17388](https://github.com/brave/brave-core/pull/17388)
- Verified Transak landing page uses the selected currency on the purchase widget

---------------------

Verification passed on 

Brave | 1.50.93 Chromium: 111.0.5563.64 (Official Build) beta (arm64)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#17388](https://github.com/brave/brave-core/pull/17388)
- Verified Transak landing page uses the selected currency on the purchase widget

https://user-images.githubusercontent.com/17010094/225859705-695a8f20-1daf-41e7-97d1-e8611528dac1.mp4
