### ISSUE TITLE
add funds button in notification "not enough tokens" does not work

### ISSUE THREAD

**Issue by dy** [brave/brave-browser#2841]
![image](https://user-images.githubusercontent.com/300067/50783399-b98e5880-1278-11e9-993d-91a5f4b615e7.png)
Version 0.58.18 Chromium: 71.0.3578.98 (Official Build) (64-bit)

**Comment by NejcZdovc** [comment]
thank you for the report, we already have this one logged and fixed https://github.com/brave/brave-browser/issues/2628. It landed in 0.60
