### ISSUE TITLE
Unable to go back with one click from send page when wallet is reopened

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#28429]
## Steps to Reproduce

   1. Open send
   2. close browser
   3. Unlock wallet and observe, one back press doesn't do anything

## Actual result:

[twice-back.webm](https://user-images.githubusercontent.com/11755381/218106830-f39438bf-466d-4d11-89a3-46ad0b461cd9.webm)

## Expected result:
Should show home with one back press

## Reproduces how often: 

Easily

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? Y

**Comment by surya-situ** [comment]
Hi, I went through the readme me and installed everything, can you please guide me where can I make change ? 
(is it in brave-core )

**Comment by Douglashdaniel** [comment]
Closing as `Invalid`
