### ISSUE TITLE
The preview images of pictures and web links in the discord forum do not load properly

### ISSUE THREAD

**Issue by lovebigbear** [brave/brave-browser#28428]
## Description 

After I upgraded brave to version 1.48.158 Chromium: 110.0.5481.77 (official version) (arm64), The preview images of pictures and web links in the discord forum do not load properly. 
I could only keep refreshing the browser page to load the image, and all of brave's security blocking features were turned on and off repeatedly, but to no avail. chrome with the same Chromium core does not have this problem.

## Brave version (brave://version info)

1.48.158 Chromium: 110.0.5481.77 (official version) (arm64) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Yes
- Can you reproduce this issue with the beta channel? 
- I have not try
- Can you reproduce this issue with the nightly channel? 
- I have not try

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- No
- Does the issue resolve itself when disabling Brave Rewards? 
- No
- Is the issue reproducible on the latest version of Chrome? 
- No

**Comment by jharwig** [comment]
It seems that Brave is sometimes not firing `onload` (or `onerror`) events for images. I made a test page that tries loading a broken image and ensures on error is called. It fails for me (a timeout occurs instead of `onerror` event) in brave randomly in less than 100 attempts. No other browser fails (safari chrome, chrome canary.) Discord probably checks the that images are available before displaying (I have an application that does similar check and this being broken causes images to not show.)

https://codesandbox.io/s/brave-onload-testing-d9xofv

_(Not sure if other events are not working: document.onload, etc)_

**Comment by Brave-Matt** [comment]
+1 from Community:
https://community.brave.com/t/discord-images-not-loading/470151/2

**Comment by ryanbr** [comment]
I believe this occurred between the Chromium 109->110 bump if someone can confirm? (Nightly build use a sperate profile)

Nightly v1.44.32 (Chromium 104.0.5112.81) OK
Nightly v1.47.91 (Chromium 108.0.5359.48) OK
Nightly v1.49.14 (Chromium 109.0.5414.87) OK
[Nightly v1.49.62 (Chromium 109.0.5414.119) ](https://github.com/brave/brave-browser/releases/tag/v1.49.62)OK
[Nightly v1.49.64 (Chromium 110.0.5481.52)](https://github.com/brave/brave-browser/releases/tag/v1.49.64) BAD
Nightly v1.49.69 (Chromium 110.0.5481.52) BAD
Nightly v1.49.77 (Chromium 110.0.5481.52) BAD

**Comment by MDouglas345** [comment]
I have a similar issue, confirm this [site](https://roarthreejs.onrender.com/) is experiencing the same. Issue not present on Chromium 109.0.5414.119 but is present on 110.0.5481.52.

[Community link](https://community.brave.com/t/threejs-images-occasionally-wont-load/470210)

**Comment by kjozwiak** [comment]
The above requires `1.48.164` or higher for `1.48.x` verification 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.48.171 Chromium: 110.0.5481.177 (Official Build) (64-bit)
-- | --
Revision | f34f7ab2d4ca4ad498ef42aeba4f4eb2c1392d63-refs/branch-heads/5481@{#1239}
OS | Windows 11 Version 22H2 (Build 22621.1265)
```

Went through various Discord channels and ensured that images and link previews are appearing correctly on various channels as per the following:

**`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|----------------
![ds1](https://user-images.githubusercontent.com/2602313/220929703-c8ee3209-a582-490f-ba04-a3e44286d309.png) | ![ds2](https://user-images.githubusercontent.com/2602313/220929755-0f047cf6-7cf6-4102-aa89-b7276c969a81.png) | ![ds3](https://user-images.githubusercontent.com/2602313/220929767-917257df-0ef8-4b70-b76e-78a43957038d.png) | ![ds4](https://user-images.githubusercontent.com/2602313/220929774-de70de13-6f8f-47cb-92f5-ddf15b709ef5.png)
