### ISSUE TITLE
Sync string update

### ISSUE THREAD

**Issue by rossmoody** [brave/brave-browser#2842]
Need to update the body copy in the modal for "I have a sync code". Should read: `Type your supplied sync chain code words into the form below.`

![image](https://user-images.githubusercontent.com/29072694/50786238-ca829e00-1267-11e9-8f36-1aab97676a93.png)

**Comment by LaurenWags** [comment]
@rossmoody - just to confirm, is the only string updated the one from the description? If there are others, can you add a test plan so we know which ones changed?

**Comment by rossmoody** [comment]
Yeah, just the description update, and it's not a change, just a string we missed copying over to match the spec during the locale migration from Brave UI. Here's the spec to check against: https://docs.google.com/document/d/1gvOwHRORwg3xDQEUsWRp_WgYC0_TYc87By8v8r0isYM/edit

**Comment by GeetaSarvadnya** [comment]
Verification passed on

Brave | 0.59.25 Chromium: 72.0.3626.53 (Official Build) beta (64-bit)
-- | --
Revision | 98434e6cd182d68ce396daa92e9c6310422e6763-refs/branch-heads/3626@{#620}
OS | Windows

- Verified the description updated description `Type your supplied sync chain code words into the form below` in Enter a sync code popup

![image](https://user-images.githubusercontent.com/38657976/51339057-77072000-1ab1-11e9-87db-04b5adde075a.png)
