### ISSUE TITLE
Use JsonRpcService::GetERC20TokenBalances API for to fetch EVM token Balances [Desktop]

### ISSUE THREAD

**Issue by nvonpentz** [brave/brave-browser#28420]
The new API added in https://github.com/brave/brave-core/pull/16955 is more efficient since it can fetch multiple balances in a single API call, so we should switch to it where possible.

```
struct ERC20BalanceResult {
  string contract_address;
  string? balance;
};

GetERC20TokenBalances(array<string> contracts,
                      string address,
                      string chain_id) => (array<ERC20BalanceResult> balances,
                                           ProviderError error,
                                           string error_message);
```

Currently only supported on some EVM chains, otherwise returns a Invalid Parameters error, so we should maintain a fallback. There's probably a better way for frontends to know when to use this vs. the fallback.  Open to ideas there.

**Comment by Pavneet-Sing** [comment]
Thanks!
Just to confirm, if we use it only for ERC20 tokens then we won't be requiring any fallback? it should work as expected for ERC20 tokens and chains?
Just curious, if we are planning to do it for Solana and Filecoin soon then probably better to do it all together.

**Comment by nvonpentz** [comment]
@Pavneet-Sing This is just for EVM tokens.  A combined API for all EVM, Solana, and Filecoin tokens may be possible, but I probably wouldn't want to try and abstract that far right now.

We'll need a fallback even for ERC20 tokens.  It will work for any token that implements the standard, but only for chains which there's a BalanceScanner contract deployed (and for which we have a configuration in our code).  This is the list of supported chains https://github.com/brave/brave-core/blob/c605b0ed25ab594811a70f6ad2da47e91bc45308/components/brave_wallet/browser/brave_wallet_constants.cc#L634-L656.

Before the frontends use the GetERC20TokenBalances API, we should determine how to handle this.  Some options
1. Have frontends use the fallback everytime GetERC20TokenBalances returns InvalidParams error (easiest, since no more core implementation is needed, but not the best since there are InvalidParams errors for other reasons).
2. Add a mojo API that provides the list of supported chains
3. Return a more descriptive error type

Doing both (2) and (3) seems best to me, but (3) may be more complicated given how we're just using the error types from the RPC standard.

cc @yrliou @onyb

**Comment by yrliou** [comment]
Personally I would go for option2 first, it's trivial and UI can start very soon so we can use this efficient API for getting balances.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.58.109 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | a4ad1fcdb550daf076384dbb280ae944274b3d35
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#19337](https://github.com/brave/brave-core/pull/19337)
- Verified able to load token balances in Portfolio
- Verified able to load token prices in Portfolio
- Verified able to load pricing history (graph) in Portfolio
- Verified able to load fiat balances in Accounts
- Verified able to load token balances in Swap
- Verified on both panel V2 and Wallet page

https://github.com/brave/brave-browser/assets/17010094/e75f06e0-5541-4d9b-b086-65274c736942
