### ISSUE TITLE
Blank ads placeholders persists on Bhaskar.com

### ISSUE THREAD

**Issue by Cleveho** [brave/brave-browser#28439]
## Description 

AdSense ads are blocked but the placeholder doesn't get removed/hidden even when setting blocking mode to "Aggressively block ads & trackers"

## Steps to Reproduce

   1. Create a new profile & set shield blocking to Aggressive
   2. Visit bhaskar.com
   3. You can see ad placeholder at the top and right side

## Actual result:

![121](https://user-images.githubusercontent.com/48880976/218170055-adbf029b-7cdb-4c6f-b6fc-19265c93f780.png)

## Expected result:
![344](https://user-images.githubusercontent.com/48880976/218170255-974269fe-155d-46be-887d-25402b63ca33.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.48.158 Chromium: 110.0.5481.77 (Official Build) (64-bit)
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | Windows 11 Version 22H2 (Build 22621.1105)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? not applicable
## Miscellaneous Information:

Some ads blocked using brave's block element : 

www.bhaskar.com##.e307bc9e > .cf559a0e.f1ab6437
www.bhaskar.com###Ad--28928716--Bhaskar--Home--DAB_HP_BTF_300x250
www.bhaskar.com##div.cf559a0e.f1ab6437:nth-of-type(5)
www.bhaskar.com###Ad--28928716--Bhaskar--Home--DAB_HP_ATF_300x250
www.bhaskar.com##div.cf559a0e.f1ab6437:nth-of-type(2)
www.bhaskar.com##.cf2f6bd0.cf559a0e.f1ab6437

**Comment by Cleveho** [comment]
Can you fix this @ryanbr ?

**Comment by Cleveho** [comment]
Any update on this @ryanbr ?

**Comment by ryanbr** [comment]
can you restart the browser @Cleveho  and retest? ensure Indian list is enabled in brave://adblock

**Comment by Cleveho** [comment]
Not resolved, tested on new profile with default setting and Indian list enabled.

**Comment by ryanbr** [comment]
Can you update to the latest ver of Brave?

**Comment by Cleveho** [comment]
I am on the latest version
[Version 1.49.120 Chromium: 111.0.5563.64 (Official Build) (64-bit)](https://brave.com/latest/)

**Comment by ryanbr** [comment]
Can you force update the Indian list in brave://components. If that doesn't help re-test in Brave beta which is a completely seperate profile.

**Comment by peterlaws** [comment]
I'm seeing this with the new 1.56.9.... on dailymail especially

**Comment by bsclifton** [comment]
cc: @ryanbr

**Comment by RacerDuke** [comment]
Any progress towards fixing this problem? I've been experiencing the same issue with ad spaces not getting collapsed for a long time now-- most prominently on the iOS version and it's the only thing keeping me from making Brave my default browser over Safari.
