### ISSUE TITLE
Vertical Tabs : Tabs Disappear

### ISSUE THREAD

**Issue by jeff-a-andersen** [brave/brave-browser#28432]
## Description 
Tabs show when the vertical tabs stage is expanded.  When collapsed, they disappear.

![image](https://user-images.githubusercontent.com/20786498/218145237-80c744e5-cc63-425f-9472-c2bdab1ddd50.png)

![image](https://user-images.githubusercontent.com/20786498/218145283-05f7798d-416d-436c-9038-89b3be27d9a1.png)

## Steps to Reproduce
Expand the vertical tabs and open some tabs.
Collapse the vertical tabs and some disappear.

## Actual result:
Tabs disappear

## Expected result:
All tabs should be displayed when collapsed.

## Reproduces how often: 
Easily reproduced

## Brave version (info found on brave://version)
Brave	1.48.158 Chromium: 110.0.5481.77 (Official Build) (64-bit) 
Revision	65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS	Windows 10 Version 20H2 (Build 19042.2486)

## Version/Channel Information:
Haven't tried

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Haven't tried
- Can you reproduce this issue with the dev channel? Haven't tried
- Can you reproduce this issue with the nightly channel? Haven't tried

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:
None

**Comment by jeff-a-andersen** [comment]
@antonok-edm , will do.  Do you want me to keep this open if it's continuing in the Nightly?

**Comment by jeff-a-andersen** [comment]
I can't get vertical tabs to work at all in the Nightly:
![image](https://user-images.githubusercontent.com/20786498/218168703-22021e0e-b66e-4719-9381-335d05608249.png)

**Comment by rebron** [comment]
@jeff-a-andersen What version nightly are you running? will be here: brave://version

**Comment by jeff-a-andersen** [comment]
@rebron here's the info:

Brave	1.50.23 Chromium: 110.0.5481.77 (Official Build) nightly (64-bit) 
Revision	65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS	Windows 10 Version 20H2 (Build 19042.2486)

**Comment by simonhong** [comment]
@jeff-a-andersen needs one more step after enabling from brave://flags.
Open tab's context menu and click `Use Vertical Tabs`
<img width="239" alt="Screenshot 2023-02-11 at 8 21 01 AM" src="https://user-images.githubusercontent.com/6786187/218220759-deb2f628-f23d-47e1-a68f-6a646a13613e.png">

**Comment by jeff-a-andersen** [comment]
Thank you @simonhong , that was it! 🤦‍♂️

I'm going to close this since the nightly build is way different from the production version.  Didn't know this was being so actively worked on and I'm liking what I see in the nightly.  Thanks!
