### ISSUE TITLE
Vertical Tabs : Labels Disappear

### ISSUE THREAD

**Issue by jeff-a-andersen** [brave/brave-browser#28434]
## Description 
On vertical tab, the tab labels randomly disappear.  For instance:
![image](https://user-images.githubusercontent.com/20786498/218150869-b5672963-3c78-4aea-89ec-a2c52a79cf84.png)

## Steps to Reproduce
None, occurs randomly.

## Actual result:
Tab labels disappear.

## Expected result:
Tab labels should be present when the vertical tabs stage is expanded.

## Reproduces how often: 
No steps to reproduce

## Brave version (brave://version info)
Brave	1.48.158 Chromium: 110.0.5481.77 (Official Build) (64-bit) 
Revision	65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS	Windows 10 Version 20H2 (Build 19042.2486)

## Version/Channel Information:

- Can you reproduce this issue with the current release?  Yes
- Can you reproduce this issue with the beta channel? Haven't tried
- Can you reproduce this issue with the nightly channel? Haven't tried

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by antonok-edm** [comment]
See https://github.com/brave/brave-browser/issues/28432#issuecomment-1426176370

cc @sangwoo108

**Comment by jeff-a-andersen** [comment]
Vertical tabs don't work at all in the Nightly build.  See comment https://github.com/brave/brave-browser/issues/28432#issuecomment-1426181881 for details.

**Comment by jeff-a-andersen** [comment]
See https://github.com/brave/brave-browser/issues/28432#issuecomment-1426488687
