### ISSUE TITLE
Unable to parse JSON console error in Wallet

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#28437]
## Description 

Per reported in this issue https://github.com/brave/brave-browser/issues/28365 we need to silently fallback when parsing local storage.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.50.91 Chromium: 111.0.5563.64 (Official Build) beta  (64-bit) 
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Linux

- Verified steps from [brave/brave-core#17142](https://github.com/brave/brave-core/pull/17142)
- Verified no `Unable to parse JSON` error message on both portfolio page and on `brave://wallet-panel.top-chrome/`
- Still encountered [#28365](https://github.com/brave/brave-browser/issues/28365)

Portfolio | Panel 
-- | --
![image](https://user-images.githubusercontent.com/17010094/225529789-bb4b19a9-743e-4a1f-a147-97644c7454b2.png) | ![image](https://user-images.githubusercontent.com/17010094/225529761-895b548b-940e-4e1a-9c6f-38f0681b2017.png)


---------------------

Verification passed on 

Brave | 1.50.91 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from [brave/brave-core#17142](https://github.com/brave/brave-core/pull/17142)
- Verified no `Unable to parse JSON` error message on both portfolio page and on `brave://wallet-panel.top-chrome/`
- Still encountered [#28365](https://github.com/brave/brave-browser/issues/28365)

Portfolio | Panel 
-- | --
![brave_FtJwJxVyXj](https://user-images.githubusercontent.com/17010094/225529922-0ede7710-498c-4c00-8cb0-fb00c5948683.png) | ![brave_tGiBSKiM9R](https://user-images.githubusercontent.com/17010094/225529932-5c2f56e6-d03c-406f-9984-f6d4db055083.png)


---------------------

Verification passed on 

Brave | 1.50.91 Chromium: 111.0.5563.64 (Official Build) beta (arm64)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#17142](https://github.com/brave/brave-core/pull/17142)
- Verified no `Unable to parse JSON` error message on both portfolio page and on `brave://wallet-panel.top-chrome/`
- Still encountered [#28365](https://github.com/brave/brave-browser/issues/28365)

Portfolio | Panel 
-- | --
![image](https://user-images.githubusercontent.com/17010094/225530173-f3a4f359-c53e-434d-b025-93c0e0280a1b.png) | ![image](https://user-images.githubusercontent.com/17010094/225530190-89fc190c-49db-4364-8b71-52b77ffde945.png)
