### ISSUE TITLE
Unplayable Videos on sportsnet.ca

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#2843]
## Description 
Videos are not playable with default shield settings on sportsnet.ca.

## Steps to Reproduce
1. Navigate to https://www.sportsnet.ca/hockey/nhl/talbot-robs-gibbons-doorstep-point-blank-save/
2. Attempt to play the video

## Actual result:
Video will not play.

## Expected result:
Video plays.

## Reproduces how often: 
Always

## Brave version (brave://version info)
0.58.18

### Reproducible on current release:
Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? No

### Additional Information
In order to play the video content, the user must _Allow Ads and Trackers_ and _Allow all Cookies_. This issue was originally [reported on Twitter](https://twitter.com/Joe_Diddly/status/1082347966319468546):

![image](https://user-images.githubusercontent.com/815158/50788412-f78e7b00-127e-11e9-89aa-b788314e57f8.png)

**Comment by mrzealot** [comment]
Allowing all cookies wasn't necessary for me on 0.58.21, only the "Ads and trackers" switch. It also runs into autoplay, which won't be allowed because of the ad blocker catching the video...

**Comment by bbondy** [comment]
This is fixed and under review here:
https://github.com/brave/ad-block/pull/162

If accepted, it'll go onto dev channel which moves to Beta on Jan 29th.

**Comment by srirambv** [comment]
Marking as `0.60.x` as https://github.com/brave/brave-core/pull/1430 is uplifted to `0.60.x`

**Comment by GeetaSarvadnya** [comment]
Verification passed on 

Brave | 0.60.25 Chromium: 72.0.3626.96 (Official Build) beta (64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Windows 10
