### ISSUE TITLE
Large gap in the Asset Details screen

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#28438]
## Description 

There is a large gab between the `Price Chart` and `Accounts` list on the `Asset Details` screen.

## Steps to Reproduce

   1. Go to the portfolio page and select a token
   2. You will see a large gap between the `Price Chart` and the `Accounts` list.

## Actual result:

https://user-images.githubusercontent.com/40611140/218167801-821c9182-154c-4b31-92cb-442e94fde5b5.mov

## Expected result:

There should not be a large gap

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.50.91 Chromium: 111.0.5563.64 (Official Build) beta  (64-bit) 
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Linux

- Verified steps from [brave/brave-core#17143](https://github.com/brave/brave-core/pull/17143)
- Verified there is no visible unusually large gap between `Price chart` and `Account` list  on token details page
![image](https://user-images.githubusercontent.com/17010094/225528344-a964d394-bcd2-456c-ae0a-9a3a8a70a357.png)


---------------------

Verification passed on 

Brave | 1.50.91 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from [brave/brave-core#17143](https://github.com/brave/brave-core/pull/17143)
- Verified there is no visible unusually large gap between `Price chart` and `Account` list  on token details page
![brave_BU7yXTPV8S](https://user-images.githubusercontent.com/17010094/225528457-498b4ad2-f531-4962-b537-66dd3a9e776e.png)

---------------------

Verification passed on 

Brave | 1.50.91 Chromium: 111.0.5563.64 (Official Build) beta (arm64)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#17143](https://github.com/brave/brave-core/pull/17143)
- Verified there is no visible unusually large gap between `Price chart` and `Account` list  on token details page
![image](https://user-images.githubusercontent.com/17010094/225528719-b16bc365-20a7-4f3e-b08e-86d26eaa7c46.png)
