### ISSUE TITLE
Header fixes for Google Sign-In Permission - follow up for #27723

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#28440]
Follow up issue to test #27723 in 1.50.x 

Per discussion via https://bravesoftware.slack.com/archives/C6YNM6Y5S/p1676056695432439?thread_ts=1675971598.530879&cid=C6YNM6Y5S 1.50.x is where we are expecting to enable this feature. Also, additional code has been landed in 1.50.x (https://github.com/brave/brave-core/pull/17088, https://github.com/brave/brave-core/pull/17058, https://github.com/brave/brave-core/pull/16971 as listed in above slack thread) so it doesn't make sense to test this with 1.49.x at this time.

@brave/qa-team as before, please ping @ShivanKaul or @LaurenWags for spec with further details.

**Comment by MadhaviSeelam** [comment]
Verification `In progess` using
```
Brave | 1.50.91 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | Windows 11 Version 22H2 (Build 22621.1413)
```
Case 1: `brave://flags/#brave-google-sign-in-permission` set to default

1. Install 1.50.91
2. launch Brave
3. open a new-tab
4. visit brave://flags
5. new feature flag `#brave-google-sign-in-permission` - `Enable Google Sign-In Permission Prompt` is set to default
6. visit `brave://settings/socialBlocking`
7. verified `Allow use of third-party cookies for legacy Google Sign-In` setting is set to enabled as a default
8. visit `brave://settings/content`  and click `Additional permissions` 
9. confirmed `Google Sign-In` entry is not shown

step 5 | ex|ex
-----|----|----
<img width="450" alt="image" src="https://user-images.githubusercontent.com/98358127/225465987-1bcd1439-fa57-48fb-a3a1-aa3bc45f895b.png">|<img width="516" alt="image" src="https://user-images.githubusercontent.com/98358127/225466488-064bb61c-a7ab-4a62-acdf-60565c6ef32a.png">|<img width="510" alt="image" src="https://user-images.githubusercontent.com/98358127/225468444-480a0477-c461-44d6-ac02-752b0b50a2b9.png">


Case 2: `brave://flags/#brave-google-sign-in-permission` set to default

1. continue from Case 1
    - `#brave-google-sign-in-permission` - `Enable Google Sign-In Permission Prompt` is set to default in `brave://flags`
2. Enabled `brave://flags/#brave-google-sign-in-permission`
3. visit brave://settings/socialBlocking
4. confirmed "Allow Google login buttons on third party sites" setting is  not shown
5. visit brave://settings/content/googleSignIn
6. new `Google Sign-In` page shown


ex|ex|ex
-----|----|----
<img width="502" alt="image" src="https://user-images.githubusercontent.com/98358127/225469030-9a303920-2481-4bb1-9cc5-f7516738589d.png">|<img width="513" alt="image" src="https://user-images.githubusercontent.com/98358127/225469308-9caec35d-7dee-4fd3-9373-b2d69f2f98a4.png">|<img width="514" alt="image" src="https://user-images.githubusercontent.com/98358127/225470356-6409bc72-8d7d-4df0-9526-01df95d5ddf0.png">

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.50.98 Chromium: 111.0.5563.64 (Official Build) beta (x86_64)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | macOS Version 11.7.4 (Build 20G1120)

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave	1.50.107 Chromium: 112.0.5615.39 (Official Build) beta (64-bit) 
Revision	a0e7b9718a92bcd1cf33b7c95316caff3fc20714-refs/branch-heads/5615@{#753}
OS	Linux
```

**Comment by LaurenWags** [comment]
changing to `release-notes/exclude` per https://brave.com/privacy-updates/24-google-sign-in-permission/
