### ISSUE TITLE
Android NTP background images are the wrong aspect ratio

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#28450]
There have been a few reports that NTP images, both sponsored and regular, are being stretched. In portrait mode, that appears to usually make the image wider than it should be.

What we have found out:
- The amount of stretch seems to be dependent on the device size.
- The issue does not happen if the Brave News feature flag is disabled.

The issue seems to be caused by creating an image that is the device width and height, but [setting it directly on the `FrameLayout`](https://github.com/brave/brave-core/blame/2226f39f6d2dec6e7698c7cc00782bf524b9599f/android/java/org/chromium/chrome/browser/app/BraveActivity.java#L1124). The bug was _possibly_ caused in https://github.com/brave/brave-core/pull/13951 because previous to that, the image was being set on a scroll view.

However, it seems that possibly because of the refactor in https://github.com/brave/brave-core/pull/13951 we don't even need to be using the code path involving Glide and the FrameLayout at all:

Bypassing [the code that calls ` BraveActivity.getBraveActivity().setBackground(bgWallpaper);`](https://github.com/brave/brave-core/blob/2226f39f6d2dec6e7698c7cc00782bf524b9599f/android/java/org/chromium/chrome/browser/ntp/BraveNewTabPageLayout.java#L1190-L1196) fixes the issue and doesn't seem to cause any bugs scrolling down to Brave News. So perhaps that code path was only needed when the scroll view was used.
```java
        public void bgWallpaperRetrieved(Bitmap bgWallpaper) {
            // if (ChromeFeatureList.isEnabled(BraveFeatureList.BRAVE_NEWS)) {
                // if (BraveActivity.getBraveActivity() != null && mTabProvider.get() != null
                        // && !mTabProvider.get().isIncognito()) {
                    // BraveActivity.getBraveActivity().setBackground(bgWallpaper);
                // }

            // } else {
                mBgImageView.setImageBitmap(bgWallpaper);
            // }
        }
```

## Test Plan
TBD - something that measures the "squareness" or the aspect ratio of something identifiable on one of the bg images.

**Comment by kjozwiak** [comment]
The above requires `1.48.170` or higher for `1.48.x` verification 👍 @deeppandya will also help verify this on his `Pixel 7 Pro` device that originally reproduced the above issue as well.

**Comment by Uni-verse** [comment]
Verification `Passed` on `Pixel 7 Pro` using the version `1.48.171` per https://bravesoftware.slack.com/archives/C0YL5KMA8/p1677164300099009?thread_ts=1677135710.642299&cid=C0YL5KMA8

https://user-images.githubusercontent.com/17885425/221035928-1f76d83d-ecf3-4100-a3c5-9509c3e4fb0c.mp4

**Comment by Uni-verse** [comment]
Verified on `Samsung GS 21 5G` using version: 

```
Brave	1.48.171 Chromium: 110.0.5481.177 (Official Build) (64-bit) 
Revision	f34f7ab2d4ca4ad498ef42aeba4f4eb2c1392d63-refs/branch-heads/5481@{#1239}
OS	Android 13; Build/TP1A.220624.014
```
- Ensured that NTP SI are displayed properly and have the correct aspect ratio


Example | Example | Example | Example
-|-|-|-
![screenshot-1677189188650](https://user-images.githubusercontent.com/17885425/221039510-ef835eba-87dc-4448-a2b8-e8ad1b6b6cc5.png) | ![screenshot-1677189197513](https://user-images.githubusercontent.com/17885425/221039512-3b1e9eec-6bf2-4529-a12e-701b0f1e4a13.png) | ![screenshot-1677189210272](https://user-images.githubusercontent.com/17885425/221039521-f2f848b0-7128-48f0-bc0a-b02f9d25169b.png) | ![screenshot-1677189224288](https://user-images.githubusercontent.com/17885425/221039522-7b925da9-9890-46d7-8a19-9e7c0f051ab8.png)
