### ISSUE TITLE
warning not being displayed the first time around when clicking on `Confirm Sync Code` without any code added

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#2845]
## Description 

When clicking on `Confirm Sync Code` under `Enter a sync code`, the entire modal will get closed without any warnings. When you open the `Enter a sync code` modal again, you'll get the warning from the previous failure.

## Steps to Reproduce

   1. launch brave (`0.59.20 Chromium: 72.0.3626.28` in this instance)
   2. open `brave://sync` and click on `I Have a Sync Code`
   3. click on `Confirm Sync Code` without adding anything into the text field
   4. you'll notice that the entire modal is closed right away without any warnings
   5. click on `I Have a Sync Code` and you'll receive the warning that should have appeared in the first place

## Actual result:

![syncissue](https://user-images.githubusercontent.com/2602313/50810538-2c7aec00-12d8-11e9-9928-1783cb20916b.gif)

## Expected result:

Should be warning the user that the import failed rather than closing the modal and than warning the user once they go into the `Enter a sync code` for a second time.

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

Brave | 0.59.20 Chromium: 72.0.3626.28 (Official Build) beta(64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds?

Reproducible on `beta` and assuming it's also reproducible on `dev` as well as the new UI would have been merged into `dev` first.

**Comment by LaurenWags** [comment]
Same thing happens if you enter an invalid sync code. STR:
   1. launch brave (`0.59.20 Chromium: 72.0.3626.28` in this instance)
   2. open `brave://sync` and click on `I Have a Sync Code`
   3. enter code that is incorrect and click on `Confirm Sync Code`
   4. you'll notice that the entire modal is closed right away without any warnings
   5. click on `I Have a Sync Code` and you'll receive the warning that should have appeared in the first place

**Comment by btlechowski** [comment]
Reproduced both cases on Windows 7:

Brave | 0.59.20 Chromium: 72.0.3626.28 (Official Build) beta (64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Windows 7

**Comment by rebron** [comment]
@kjozwiak we don't need a new dialog/text for this right? Just need to show the existing one, the "invalid sync code. please try again" instead of going back to the beginning.

**Comment by kjozwiak** [comment]
> @kjozwiak we don't need a new dialog/text for this right? Just need to show the existing one, the "invalid sync code. please try again" instead of going back to the beginning.

yup, correct 👍 With the current behaviour, failing the first time doesn't display the warning and takes you back to the beginning. When you click on `I Have a Sync Code` the second time around, the error that was supposed to appear initially is finally displayed.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.59.26 Chromium: 72.0.3626.64 (Official Build) beta (64-bit)
-- | --
Revision | eaa9668e80ce5405e7f1902579558ea725c06ca1-refs/branch-heads/3626@{#708}
OS | Windows

Used test plan from https://github.com/brave/brave-core/pull/1357 and from https://github.com/brave/brave-browser/issues/2845#issuecomment-452372326

![2845](https://user-images.githubusercontent.com/34715963/51453388-7daac700-1d3f-11e9-8cc1-643fd740e4bc.gif)
