### ISSUE TITLE
IPFS banner should not be shown when there are no NFTs in the user's wallet

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#28466]

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.50.94 Chromium: 111.0.5563.64 (Official Build) beta (64-bit) 
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Linux

- Verified steps from [brave/brave-core#17156](https://github.com/brave/brave-core/pull/17156)
- Verified NFT banner and button are only shown when there is an NFT added to the account 
- Verified for both Solana NFT and Ethereum NFT
- Encountered [#29200](https://github.com/brave/brave-browser/issues/29200)

https://user-images.githubusercontent.com/17010094/226536697-48aff6bd-6b6e-4b5c-bd78-36038025942c.mp4


---------------------

Verification passed on 

Brave | 1.50.94 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from [brave/brave-core#17156](https://github.com/brave/brave-core/pull/17156)
- Verified NFT banner and button are only shown when there is an NFT added to the account 
- Verified for both Solana NFT and Ethereum NFT
- Encountered [#29200](https://github.com/brave/brave-browser/issues/29200)

https://user-images.githubusercontent.com/17010094/226536766-5027babe-f65c-470f-a87f-a20e0deef826.mp4

---------------------

Verification passed on 

Brave | 1.50.94 Chromium: 111.0.5563.64 (Official Build) beta (arm64)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#17156](https://github.com/brave/brave-core/pull/17156)
- Verified NFT banner and button are only shown when there is an NFT added to the account 
- Verified for both Solana NFT and Ethereum NFT
- Encountered [#29200](https://github.com/brave/brave-browser/issues/29200)

https://user-images.githubusercontent.com/17010094/226535853-7cd5fd75-a17a-4798-a677-305bbfca2b01.mov
