### ISSUE TITLE
Wallet More Popup Position is Off

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#28472]
## Description 

The Wallet More Popup position is not relative to the `More` icon.

## Steps to Reproduce

   1. Go to the Portfolio Page and click on the `More` icon
   2. The popup menu is not relative to the `More` icon and is at the top right of the screen.

## Actual result:

![10](https://user-images.githubusercontent.com/40611140/218508244-aea6653c-c130-4386-a402-9c84125a18af.png)

## Expected result:

![11](https://user-images.githubusercontent.com/40611140/218508291-cace704b-1cac-4cd4-971c-6b431ac3892a.png)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.50.91 Chromium: 111.0.5563.64 (Official Build) beta  (64-bit) 
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Linux

- Verified steps from [brave/brave-core#17163](https://github.com/brave/brave-core/pull/17163)
- Verified more menu popup is relative to the button alignment
![image](https://user-images.githubusercontent.com/17010094/225527652-81dcc057-e2dc-4bfc-a3cf-f8adb4d28867.png)

---------------------

Verification passed on 

Brave | 1.50.91 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from [brave/brave-core#17163](https://github.com/brave/brave-core/pull/17163)
- Verified more menu popup is relative to the button alignment
![image](https://user-images.githubusercontent.com/17010094/225527614-9cc6d2d7-ad8a-4b93-94ee-de328a9e2ae4.png)

---------------------

Verification passed on 

Brave | 1.50.91 Chromium: 111.0.5563.64 (Official Build) beta (arm64)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#17163](https://github.com/brave/brave-core/pull/17163)
- Verified more menu popup is relative to the button alignment
![image](https://user-images.githubusercontent.com/17010094/225527806-b420b3bf-eb39-4b86-95e2-931e3ee54ae9.png)
