### ISSUE TITLE
Blank Chrome profile is imported via onboarding import process

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#28478]
## Description 

if multiple Chrome profiles  are imported via onboarding import process and if a profile is blank (with no bookmarks, history or extension data),  a new blank profile is created in the Brave profile manager.  A new blank profile should not be created for blank profile.

## Steps to Reproduce

Pre-requisite: Create 2 Chrome profiles with data and create 1 profile without any data.  

   1. Install 1.49.91
   2. launch Brave
   3. click `Set Brave as default browser`
   4. select `Chrome` and click `Import`
   5. select `Chrome Person 1`,  `Chrome Person 2`, & `Chrome Person 5-no data`
   6. click `Import Profiles`
   7. click `Finish` 
   8. click  `Profile icon` next to hamburger menu
   
## Actual result:

`Chrome Person 5-no data` profile is imported and shown in the Profile manager
(Same issue with Firefox as well)
example |example |example
-------|-------|------
<img width="509" alt="image" src="https://user-images.githubusercontent.com/98358127/218555546-65e69cc0-aabc-44ea-81e1-4723753a2c3d.png">|<img width="451" alt="image" src="https://user-images.githubusercontent.com/98358127/218555426-eb9d224c-a4aa-467f-9955-8515fe475d90.png">|<img width="455" alt="image" src="https://user-images.githubusercontent.com/98358127/218555473-15d0a3a8-7201-4bf8-8743-46aa7ab5c069.png">

## Expected result:
Blank profile should be detected during import and should not be imported.

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.49.91 Chromium: 110.0.5481.77 (Official Build) beta (64-bit)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | Windows 11 Version 21H2 (Build 22000.1455)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
@rebron @spylogsster 
cc: @brave/qa-team

**Comment by bsclifton** [comment]
Closing as `wontfix` as the checks if a profile is blank or not are not trivial (and importing a blank profile is OK; easy enough to delete later). Thanks for reporting 😄
