### ISSUE TITLE
Upgrade from Chromium 110.0.5481.77 to Chromium 110.0.5481.97.

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#28486]
# Minor Chromium bump

https://chromium.googlesource.com/chromium/src/+log/110.0.5481.77..110.0.5481.97?pretty=fuller&n=10000

# QA tests:

* Check branding items
* Check for version bump

# Additional checks:
* No specific code changes in Brave (only line number changes in patches)

**Comment by kjozwiak** [comment]
Closing as https://github.com/brave/brave-core/pull/17184 was merged into `1.48.release3`.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.48.162 Chromium: 110.0.5481.97 (Official Build) (64-bit)
-- | --
Revision | d86ee9f656cd2fd313c1c1f12617008a1c3b571b-refs/branch-heads/5481_77@{#10}
OS | Windows 11 Version 21H2 (Build 22000.1455)
```

<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/218790318-13940b4a-6f4f-49d5-93a1-3861e72b774a.png">

**Comment by LaurenWags** [comment]
Verified with

```
Brave | 1.48.162 Chromium: 110.0.5481.97 (Official Build) (x86_64)
-- | --
Revision | d86ee9f656cd2fd313c1c1f12617008a1c3b571b-refs/branch-heads/5481_77@{#10}
OS | macOS Version 12.6.3 (Build 21G419)
```

<img width="1191" alt="Screen Shot 2023-02-14 at 11 12 04 AM" src="https://user-images.githubusercontent.com/28145373/218793983-2a85943e-de86-4dd9-b4b5-5da970008c2a.png">

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.48.162 Chromium: 110.0.5481.97 (Official Build) (64-bit) 
-- | --
Revision | d86ee9f656cd2fd313c1c1f12617008a1c3b571b-refs/branch-heads/5481_77@{#10}
OS | Ubuntu 18.04 LTS

![image](https://user-images.githubusercontent.com/34715963/218794585-587503fb-ad6e-4e97-9092-47ea3dc92ffd.png)

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version: 

```
Brave	1.48.162 Chromium: 110.0.5481.97 (Official Build) (64-bit) 
Revision	d86ee9f656cd2fd313c1c1f12617008a1c3b571b-refs/branch-heads/5481_77@{#10}
OS	Android 13; Build/TP1A.220624.014
```
- Checked branding items
- Version bump

<img width="500" alt="0" src="https://user-images.githubusercontent.com/17885425/218798922-22ce2b80-4343-43a8-8bcc-7dd35afca2e1.png">

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung Galaxy Tab S8 Ultra` running `Android 13` using the following build(s):

```
Brave | 1.48.162 Chromium: 110.0.5481.97 (Official Build) (32-bit)
--- | ---
Revision | d86ee9f656cd2fd313c1c1f12617008a1c3b571b-refs/branch-heads/5481_77@{#10}
OS | Android 13; Build/TP1A.220624.014
```

**`Example`** | **`Example`**
----------------|---------------
![Screenshot_20230214_114119_Brave](https://user-images.githubusercontent.com/2602313/218801609-95625b84-bc41-44d5-aecf-97138d266720.jpg) | ![Screenshot_20230214_114111_Brave](https://user-images.githubusercontent.com/2602313/218801622-a859ebf1-2374-4012-829c-cb51428e788a.jpg)
