### ISSUE TITLE
"Uncaught ReferenceError: brave_new_tab is not defined" when opening new tab

### ISSUE THREAD

**Issue by ignatiusreza** [brave/brave-browser#2848]
## Description 
The following error will be raised on opening a new tab:

```
Uncaught ReferenceError: brave_new_tab is not defined
    at <anonymous>:1:1
```

## Steps to Reproduce

   1. Open new-tab
   2. Open developer console
   3. See that `Uncaught ReferenceError: brave_new_tab is not defined` is logged

## Actual result:
Error are raised:

![screenshot from 2019-01-08 18-47-31](https://user-images.githubusercontent.com/667726/50822795-e7a59280-1375-11e9-94b7-582a18b86652.png)

## Expected result:
No error raised

## Reproduces how often: 
Every time

## Brave version (brave://version info)
| key | value |
| --- | --- |
| Brave | 0.58.18 Chromium: 71.0.3578.98 (Official Build) (64-bit) |
| Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897} |
| OS | Linux |

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

  not sure...

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 

  since it's on a new tab, Brave Shields is not active yet..

- Is the issue reproducible on the latest version of Chrome? 

  nope, since it's Brave specific code

### Additional Information

I think the code which raised are on this line: https://github.com/brave/brave-core/blob/0.58.x/browser/ui/webui/brave_new_tab_ui.cc#L114 .. i'm cloning the repo and will try to investigate, but not really sure on where to start.. :sweat_smile:

**Comment by caspertone2003** [comment]
Happens to me as well.
0.62.27
Windows 10

I believe it is related to a chrome extension called "close duplicated tabs"

The result of this error in my case is that all open tabs are lost and history cannot be recovered.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.68.109 Chromium: 76.0.3809.62 (Official Build) dev (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Ubuntu 18.04 LTS

Used test plan from the description and https://github.com/brave/brave-core/pull/2831

![image](https://user-images.githubusercontent.com/34715963/61757116-7bddc100-adbf-11e9-9785-7d7fb1fbadc6.png)
