### ISSUE TITLE
Update the Fund Wallet Screens with Nav and Header

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#28490]
## Description 

We need to update the `Fund Wallet` and `Deposit Funds` screens to include the new side nav and header like in the in `Send` and `Swap` screens.

Also need to remove the `Done` and `Skip` buttons.

![17](https://user-images.githubusercontent.com/40611140/218594616-96c22af8-97fb-44d1-98b8-df95af5587af.png)

![18](https://user-images.githubusercontent.com/40611140/218594632-b2856672-f5ea-4a7f-95a4-1ded59cb0660.png)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.50.91 Chromium: 111.0.5563.64 (Official Build) beta  (64-bit) 
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Linux

- Verified steps from [brave/brave-core#17180](https://github.com/brave/brave-core/pull/17180)
- Verified on both Buy and Deposit pages, there is no back button on the routed page
- Verified Brave Logo is shown on the top left corner of both the pages with `Buy` and `Deposit` mentioned on respective pages
- Verified for Buy screen, back button is only available for `Selecting a Buy Option`, `Switching Account`s or `Creating a new account`
- Verified for Deposit screen, back button is only available for `Deposit view (QR code screen)`, `Switching Accounts` or `Creating a new account`

Buy Screen | Deposit Screen
-- | --
<video src=https://user-images.githubusercontent.com/17010094/225526655-15160ebd-4011-40f2-8ed8-6912bf7c986b.mp4> | <video src=https://user-images.githubusercontent.com/17010094/225526668-5879857a-1b4f-47b8-bbf2-2654d334839c.mp4>

---------------------

Verification passed on 

Brave | 1.50.91 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from [brave/brave-core#17180](https://github.com/brave/brave-core/pull/17180)
- Verified on both Buy and Deposit pages, there is no back button on the routed page
- Verified Brave Logo is shown on the top left corner of both the pages with `Buy` and `Deposit` mentioned on respective pages
- Verified for Buy screen, back button is only available for `Selecting a Buy Option`, `Switching Account`s or `Creating a new account`
- Verified for Deposit screen, back button is only available for `Deposit view (QR code screen)`, `Switching Accounts` or `Creating a new account`

Buy Screen | Deposit Screen
-- | --
<video src=https://user-images.githubusercontent.com/17010094/225526955-7160137e-8ac1-4b3f-a9aa-6c1a34c513ae.mp4> | <video src=https://user-images.githubusercontent.com/17010094/225527112-9d4991ff-8d81-4a9b-96fa-c67855a7a411.mp4>

---------------------

Verification passed on 

Brave | 1.50.91 Chromium: 111.0.5563.64 (Official Build) beta (arm64)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#17180](https://github.com/brave/brave-core/pull/17180)
- Verified on both Buy and Deposit pages, there is no back button on the routed page
- Verified Brave Logo is shown on the top left corner of both the pages with `Buy` and `Deposit` mentioned on respective pages
- Verified for Buy screen, back button is only available for `Selecting a Buy Option`, `Switching Account`s or `Creating a new account`
- Verified for Deposit screen, back button is only available for `Deposit view (QR code screen)`, `Switching Accounts` or `Creating a new account`

Buy Screen | Deposit Screen
-- | --
<video src=https://user-images.githubusercontent.com/17010094/225525840-d169cb7e-86c2-4c91-a46f-a399ff8d0a02.mov> | <video src=https://user-images.githubusercontent.com/17010094/225525855-a5f2c7ab-1557-46d0-9d63-6bc56ef2b508.mov>
