### ISSUE TITLE
Extensions are not imported from Firefox during onboarding import process

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#28492]
## Description 

Tried to import bookmarks, history, passwords and extensions from Firefox  via onboarding import process. Bookmarks, history, passwords are successfully but extensions were not imported.  Extensions are successfully imported from Chrome successfully. 

## Steps to Reproduce

Pre-requisite: Create a Firefox profile with  bookmarks, history, passwords and extensions.

1. Install 1.49.91
2. launch Brave
3. click `Set Brave as default browser`
4. select `Mozilla Firefox` and click Import
5. select `Mozilla - Firefox Profile 3`
6. click Import Profiles
7. click Finish

## Actual result:

No extensions are imported (1Password, Adblocker Ultimate)

Firefox|brave
------|-----
<img width="472" alt="image" src="https://user-images.githubusercontent.com/98358127/218600122-4c356fc9-bda6-40cc-8166-6209f2ede765.png">|<img width="472" alt="image" src="https://user-images.githubusercontent.com/98358127/218600438-1ffe6140-5329-429e-9e8d-2abec0086ea9.png">

## Expected result:
Extensions should be imported (1Password, Adblocker Ultimate)

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.49.91 Chromium: 110.0.5481.77 (Official Build) beta (64-bit)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | Windows 11 Version 21H2 (Build 22000.1455)
```
## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
@rebron @spylogsster

**Comment by stephendonner** [comment]
cc @spylogsster @sangwoo108

**Comment by sangwoo108** [comment]
I'm not sure if it's possible. Can Chrome import Fierfox extensions?

**Comment by MadhaviSeelam** [comment]
Closing this as this is working as expected since Firefox extensions are not imported.  (Verified with Chrome and Firefox extensions are not imported)
