### ISSUE TITLE
In context menu on brave://sync in brave://settings, save link as... menu is disabled

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#2849]
## Description 

In context menu on brave://sync in brave://settings, save link as... menu is disabled

## Steps to Reproduce

   1. Open brave://settings
   2. Right click on brave://sync
   3. Check `Save Link As...` is enabled

## Actual result:

Disabled

## Expected result:
Enabled

## Brave version (brave://version info)

0.61.0 Chromium: 72.0.3626.28 (Developer Build)
0.59.12 Chromium: 72.0.3626.17 (Official Build) beta

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? No ( it is enabled on chrome url)

### Additional Information

Maybe all of brave scheme link should have this error.

**Comment by simonhong** [comment]
Changed this milestone to 0.58.x hotfix because this is also fixed by https://github.com/brave/brave-core/pull/1196

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.58.20 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Windows 7

Used test plan from https://github.com/brave/brave-core/pull/1196
Used `--enable-brave-sync` flag

Verification passed on

Brave | 0.59.21 Chromium: 72.0.3626.28 (Official Build) beta (64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Windows 7

Used test plan from https://github.com/brave/brave-core/pull/1196
All TCs PASSED
