### ISSUE TITLE
Custom background image is not rendered frequently

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#28493]
## Description 

When custom image is used for NTP background, sometimes NTP background is not rendered well

## Steps to Reproduce

   1. Load New tab and goto customize dashboard
   2. Select Background Image tab and upload image
   3. Refresh New tab or create new tab

## Actual result:

<img width="1845" alt="image" src="https://user-images.githubusercontent.com/6786187/218611347-f0ce0dc0-8130-41a3-ab0a-90ae45b7e0b2.png">

## Expected result:
Uploaded custom image should be rendered.

## Reproduces how often: 

Easily

## Brave version (brave://version info)

`Version 1.50.32 Chromium: 110.0.5481.77 (Official Build) nightly (x86_64)`

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes - `Version 1.49.91`
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.49.120` or higher for `1.49.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.49.120 Chromium: 111.0.5563.64 (Official Build) (64-bit)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | Windows 11 Version 22H2 (Build 22621.1265)
```

Reproduced the issue using STR https://github.com/brave/brave-browser/issues/28493#issue-1583316000 in `1.50.32 Chromium: 110.0.5481.77`

example | example 
----- | -------
<image width="500" alt="image" src="https://user-images.githubusercontent.com/98358127/223836112-6efa0ce0-4aec-49f4-9d4a-a620d92fe4dc.png">|<image width="500" alt="image" src="https://user-images.githubusercontent.com/98358127/223836161-90ccb6ff-2fb7-4606-bd5e-6b9aea37279d.png">

#### Confirmed background images > 1mb are rendered correctly as expected.

example | example | example 
----- | ------- | -------
<image width="600" alt="image" src="https://user-images.githubusercontent.com/98358127/223836705-6741db0b-1e9b-439f-b371-d78d2fd88fb2.png">|<image width="600" alt="image" src="https://user-images.githubusercontent.com/98358127/223836725-b6859200-a54d-4167-88b4-b15df4ffefbe.png">|<img width="647" alt="image" src="https://user-images.githubusercontent.com/98358127/223839267-8ae590cf-8157-46a1-9135-b6a37ad091b8.png">
