### ISSUE TITLE
Create a new crash reporting endpoint

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#285]

**Comment by bbondy** [comment]
We'll just be re-using `https://laptop-updates.brave.com/1/crashes` for now.
Can this be closed @aekeus or is there anything else to do here?

**Comment by aekeus** [comment]
Yes, we will need to inspect the platform from the crash and send it to a different queue. cc @KarateCowboy

**Comment by emerick** [comment]
Sounds like we'll use the endpoint `1/bc-crashes` for brave-core.

**Comment by aekeus** [comment]
Implemented by 4cf8e5098a9043c40001e3c192883eda0353be76

**Comment by bbondy** [comment]
QA notes: Just make sure you can send a crash from about:crashes and that you can search for the ID.

**Comment by srirambv** [comment]
Linux Crash doesn't list in `chrome://crashes`. Navigating to `chrome://crash` shows this error message
![image](https://user-images.githubusercontent.com/17010094/45901543-450ad900-bdb1-11e8-81f5-aaab628b76e7.png)

**Comment by bbondy** [comment]
@srirambv pls post an issue for the 1.x backlog for ^

**Comment by btlechowski** [comment]
Sending crash reports does not work on Win7: https://github.com/brave/brave-browser/issues/1188

**Comment by GeetaSarvadnya** [comment]
On windows 10 also, crash reports are not getting generated.

**Comment by kjozwiak** [comment]
@emerick there's seems to be a bug on all the platforms where the report that was just submitted doesn't appear under `chrome://crashes` when the tab is restored. @GeetaSarvadnya is creating a new bug. Reports are being submitted though 👍 

Example of the issue that @GeetaSarvadnya is posting:

* visit `chrome://crash` in a new profile
* open a new tab, visit `chrome://crashes` and click on `Send`
* Restart the browser and the restored `chrome://crashes` window won't display the recent crash
* refresh the same tab, and you'll notice that the crash will appear as submitted as expected

I'm guessing it's either:
* `chrome://crashes` isn't correctly refreshed when it's the active tab and is restored
* when `chrome://crashes` is restored, the crash report is still being submitted, hence not appearing

**Comment by srirambv** [comment]
@emerick without enabling it i can still see crash reports uploaded  
![crash](https://user-images.githubusercontent.com/17010094/46104574-b11a8200-c1a1-11e8-92ea-94ff9388d267.gif)

**Comment by emerick** [comment]
@srirambv Yes, manual uploads are still allowed even when "crash reporting" is disabled. I think the option is specifically worded as "Automatically send usage statistics and crash reports to Brave", i.e. the "automatically" is the key part there.

**Comment by emerick** [comment]
@kjozwiak OK, I see. I think you're correct and it's the second option that you list "when chrome://crashes is restored, the crash report is still being submitted, hence not appearing". Probably just down to timing as to whether you will see it that quickly.

**Comment by kjozwiak** [comment]
@emerick @GeetaSarvadnya created https://github.com/brave/brave-browser/issues/1299. However, it's not really a "blocker" or a high priority issue. Maybe it will fix itself once your backend performance improves? Either way, these are the two major issues remaining re: crash reports:

* https://github.com/brave/brave-browser/issues/1251
* https://github.com/brave/brave-browser/issues/1188

**Comment by emerick** [comment]
Is #1188 not the same chrome://settings/ problem?

**Comment by kjozwiak** [comment]
Went through verification using the following build under `macOS 10.13.6 x64` - **PASSED**

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Mac OS X

**Comment by kjozwiak** [comment]
> @kjozwiak Is #1188 not the same chrome://settings/ problem?

Nope, it doesn't work on Win 7 in general. Both manual submission and automatic via `Automatically send crash reports to Brave` doesn't work. Added more information into #1188.

**Comment by emerick** [comment]
@kjozwiak OK, I see, thanks for the details! I don't see any reason that Windows 7 in particular would be excluded, but I'll continue to dig around.

**Comment by kjozwiak** [comment]
Sounds good! Let me know if you need any help testing anything! The Win 7 issue has been around since the early days of b-l. Originally, reporting wasn't working on any platform. Win 7 & Linux where the only ones that weren't fixed. Seemed like the issue has followed us into b-c :(
