### ISSUE TITLE
Vertical tabs: not all icons show when tab strip is minimized with pinned tabs

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#28502]
## Description 
I have a situation where I am using vertical tabs and have 9 pinned tabs, 3 tab groups, and 4 regular tabs. It displays correctly in the tab strip area 😄 
<img src="https://user-images.githubusercontent.com/4733304/218655806-c034cbb5-16a4-402f-a22f-08f86002edeb.png" width="250px">

However, when I minimize it using the button:
![image](https://user-images.githubusercontent.com/4733304/218655687-270699ef-c2f5-4fc2-b9a8-187d3f204d24.png)

It's no longer showing all the icons. I think the pinned tabs are not being counted properly? Also - it seems like the tab group name itself is taking up a tab "slot". Here's what it looks like:
![image](https://user-images.githubusercontent.com/4733304/218655959-140616b7-86b1-4ba8-98fa-cacc6797e360.png)

**Comment by sangwoo108** [comment]
> It's no longer showing all the icons

Sorry, I think I'm not following this properly. I can see 9 pinned tabs when it's collapsed from your second screenshot, then isn't it right? Am I missing something here?

**Comment by sangwoo108** [comment]
Now I can see that that the tabstrip in the picture is clipped on the bottom. Fortunately, I think this was fixed as a side effect of other patches - We keep vertical layout style on floating mode and tab strip area was expanded. Please let me know if you see this again!
