### ISSUE TITLE
Expose ability to get & set UD/SNS/ENS preferences

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#28516]
## Description 

Expose ability to get & set the value of ENS offchain preference for iOS web3/wallet settings. Currently iOS is only able to enable ens offchain preference via JsonRpcService `EnableEnsOffchainLookup()` but we need the ability to set the preference back to `disabled`.

ref: https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1676402611714249

Also, we would like to expose UD/SNS/ENS preferences via mojo API for UI.
ref: https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1676414409246489

**Comment by yrliou** [comment]
Probably just a pair of Set/Get API in BraveWalletService and remove `EnableEnsOffchainLookup()`. cc @supermassive
