### ISSUE TITLE
Installer warning mentions `Win 7` or higher rather than the expected `Win 10` or higher for `C110`

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#28511]
## Description 

When attempting to install `C110` on a `Win 8.1` VM, you get a warning that states that Brave needs `Win 7` or higher which is incorrect as the message should say `Win 10` or higher due to `C110` dropping support for both `Win 7` & `Win 8`.

## Steps to Reproduce

   1. download/install a `.exe` from https://github.com/brave/brave-browser/releases/tag/v1.48.162 on a `Win 7` or `Win 8` machine

## Actual result:

<img width="1501" alt="Screenshot 2023-02-14 at 11 02 09 AM" src="https://user-images.githubusercontent.com/2602313/218793121-05b89865-2faf-4534-8d9a-ca7c95f309cf.png">

## Expected result:

Should say `Brave requires Windows 10 or higher.`

## Reproduces how often: 

100% reproducible using the STR/Cases outlined above.

## Brave version (brave://version info)

```
Brave | 1.48.162 Chromium: 110.0.5481.97 (Official Build) (32-bit)
-- | --
Revision | d86ee9f656cd2fd313c1c1f12617008a1c3b571b-refs/branch-heads/5481_77@{#10}
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @btlechowski @mihaiplesa @mherrmann

**Comment by mherrmann** [comment]
I can only reproduce this with the standalone installer. The online installer installs an older version of Brave that is still compatible with (in my case) Windows 7.

**Comment by btlechowski** [comment]
Reproduced with standalone installer 1.48.164. stub installer installs 1.47.x

![image](https://user-images.githubusercontent.com/34715963/219114305-daaa6d00-0a31-4a4e-ad9d-737a0d889599.png)

**Comment by kjozwiak** [comment]
> I can only reproduce this with the standalone installer. The online installer installs an older version of Brave that is still compatible with (in my case) Windows 7.

@mherrmann yup, only reproducible with the standalone versions as you're trying to install an incompatible version. Stub installers correctly download the latest version that can run on `Win 7` & `Win 8` so no errors/issues.

**Comment by kjozwiak** [comment]
The above requires `1.49.120` or higher for `1.49.x` verification 👍 @brave/qa-team please note, that this only needs to be checked on `Win 8` and `Win 7`. Maybe a quick spot check to makes sure that the `Standalone` executables are working without any issues on `Win 11` & `Win 10`.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.49.120 Chromium: 111.0.5563.64 (Official Build) (64-bit) 
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

![image](https://user-images.githubusercontent.com/34715963/223737182-f58416ce-6121-4b51-905e-9bdc0f83d0b5.png)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.49.120 Chromium: 111.0.5563.64 (Official Build) (64-bit) 
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | Windows 8.1

![image](https://user-images.githubusercontent.com/34715963/223824055-6778f869-61d1-4630-8d53-93fea64fb086.png)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.49.120 Chromium: 111.0.5563.64 (Official Build) (32-bit) 
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | Windows 8.1 32bit

![image](https://user-images.githubusercontent.com/34715963/223872382-2c44ea6e-4805-4851-a152-395a1b887c4d.png)
