### ISSUE TITLE
Rewards - show users a range for when they get payouts instead of specific date - stub issue

### ISSUE THREAD

**Issue by lukemulks** [brave/brave-browser#28528]
## Description 

On community call today, someone brought up a good point that they've observed feedback from new users that were turned off when they didn't get paid out on the expected date. 

The Community member mentioned that they'd get a better first impression if we put a date range for payouts instead of a single date that may be on or after the expected date. 

I think that might be a good idea to range it, or put "payouts begin on x-date, and will complete by y-date" to help answer that question instead of having users ask us. 

If there's a better repro for this, please feel free to move it there - I just wanted to open and capture it live. 

## Steps to Reproduce

   1. 
   2. 
   3. 

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by Miyayes** [comment]
Messaging in updated payout status banners essentially resolve this: https://github.com/brave/brave-browser/issues/31480
