### ISSUE TITLE
Crash when trying to open brave://sync in private window

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#2852]
## Description 

browser crashed when trying to load brave://sync in private window

## Steps to Reproduce

Case 1.
   1. Open brave://settings
   2. Try to open brave://sync to private window via context menu
   3.  Crashed

Case 2.
  1. Open private window
  2. Type brave://sync in omnibox
  3. Crashed
## Actual result:

Crashed

## Expected result:
brave://sync page should be opened in normal window.

## Reproduces how often: 

Every time

## Brave version (brave://version info)

Version 0.59.20 Chromium: 72.0.3626.28 (Official Build) beta (64-bit)
Version 0.60.6 Chromium: 72.0.3626.28 (Official Build) dev (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
both. sync is not enabled in stable
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? No

### Additional Information

We need to add some brave webui to not allowing in private window rules.
Many chrome webui pages are added in that rule. So they are only opened in normal window.

**Comment by simonhong** [comment]
@darkdh @AlexeyBarabash  Or should `brave://sync` be opened in private window also?

**Comment by AlexeyBarabash** [comment]
@simonhong thanks for finding this bug.
There is no point to open `brave://sync` in a private window because it requires / updates the profile data. So `brave://sync` should not be opened in private window.

**Comment by simonhong** [comment]
@AlexeyBarabash Ok. thanks for confirm!

**Comment by btlechowski** [comment]
Reproduced on 

Brave | 0.58.18 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Windows 7

Also reproduces for `Private Window with Tor`

**Comment by btlechowski** [comment]
Reproduced on Ubuntu 17.10

Brave | 0.59.20 Chromium: 72.0.3626.28 (Official Build) beta (64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Linux

**Comment by simonhong** [comment]
Also reproduced for guest window.

Loading brave://sync in private window should be redirected to normal window.
Loading brave://sync in tor/guest window should be blocked.

**Comment by tomlowenthal** [comment]
That's an unfortunate drawback of the current Tor implementation, and we should do everything we can to hide that implementation detail. From the perspective of the person using the browser private and Tor windows should behave identically.

**Comment by srirambv** [comment]
@bbondy @rebron to prioritize the issue

**Comment by simonhong** [comment]
I think this issue could be fixed easily after resolving https://github.com/brave/brave-core/pull/1295.

**Comment by simonhong** [comment]
Separate issue (https://github.com/brave/brave-browser/issues/3003) is created for crash in tor window.

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.62.8 Chromium: 73.0.3683.39 (Official Build) dev (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

Test plan:
Case 1:
1. Open brave://settings in normal window
2. Try to open brave://sync in private window via context menu
[PASS] Open in Private Window is disabled

Case 2:
1. Open private window
2. Type brave://sync in omnibox
[PASS] brave://sync is opened in normal window

[PASS]Case 3:
1. Open private window
2. Type brave://settings
3. Click brave://sync link
[PASS] brave://settings is opened in normal window

Reproduced the crash on Private Window with Tor: https://github.com/brave/brave-browser/issues/3003
Reproduced the crash on Guest Window. Logged https://github.com/brave/brave-browser/issues/3522
