### ISSUE TITLE
Menu frequency P3A question does not record "guest window" menu item accesses

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#28525]
## Description 

The menu frequency P3A question (`Brave.Toolbar.FrequentMenuGroup`) does not record "guest window" menu item accesses.

## Steps to Reproduce

   1. Start with a fresh profile.
   2. Access some "browser view" menu items (i.e. bookmarks).
   3. Ensure the metric answer is 2, as expected.
   4. Repeatedly access the "guest window" menu item, ensure it is accessed more times than the "browser view" accesses.

## Actual result:

The metric answer is still 2.

## Expected result:

It should be 0.

## Reproduces how often: 

Easily

## Desktop Brave version:

1.49.x and up

**Comment by GeetaSarvadnya** [comment]
Verification **INOROGRESS** on

```
Brave | 1.50.84 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | Windows 10 Version 21H2 (Build 19044.2604)

```
