### ISSUE TITLE
Experiment with Shared pinned tabs 

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#28532]
> make pinned tabs present in all windows. And add to that you can only have 1 instance of the pinned tab open at a time. So if I click my gmail pin in a window and I already had activated it in another window, then it automagically moves to the window I clicked the pin in.

Internal thread https://bravesoftware.slack.com/archives/C042KL922P3/p1675992538748969

**Comment by sangwoo108** [comment]
Hi everyone, as of https://github.com/brave/brave-core/pull/23797 , we'll introduce preference for Shared pinned tab under `settings > appearance > tabs`. The flag will only reveal the preference but not enable the preference. Please turn on the pref if you want keep using it.

**Comment by luckydonald** [comment]
Note, the UI settings needs a flag to be enabled, which is called `brave-shared-punned-tabs`.

1. Go [`brave://flags/#brave-shared-pinned-tabs`](brave://flags/#brave-shared-pinned-tabs), and enable "Shared pinned tab"
2. Restart Brave
3. Under Settings > Appearance > Tabs you'll now have a toggle to enable the shared tabs.
