### ISSUE TITLE
Different behavior of loading brave://settings and chrome://settings in private window

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#2853]
## Description 

When typing brave://settings and chrome://settings in private window's omnibox,
both shows different result.
brave://settings is opened in private window and chrome://settings is opened in normal window.

## Steps to Reproduce

   1. Typing brave://settings and chrome://settings in private window's omnibox
   2. Check the opened window (private or normal window)

## Actual result:

Both are opened in different window.
brave://settings is opened in private window.
chrome://settings is opened in normal window.

## Expected result:
Both should be opened in normal window.

## Reproduces how often: 

Always.

## Brave version (brave://version info)

All current channels.

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? No

### Additional Information

Mapping from brave to chrome is not applied when page is checked whether allowed in private window or not.

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.62.10 Chromium: 73.0.3683.39 (Official Build) dev (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

brave://settings and chrome://settings are opened in normal window.

Encountered https://github.com/brave/brave-browser/issues/2995 while testing.
