### ISSUE TITLE
Text needs updating on Acitivity tab

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#28535]
## Description 

We should keep the actions in the same tense. For example, it should be SWAP, RECEIVE, SEND. All actions should be in cap locks too.
Right now, it says 'sent' and 'swap' beside each other
![Screenshot 2023-02-15 at 16 24 28](https://user-images.githubusercontent.com/12224304/219071537-1c6bcd31-f7d9-45c7-8cd6-6d64697971c4.png)

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.52.94 Chromium: 113.0.5672.92 (Official Build) beta (64-bit)
-- | --
Revision | `b6f521170062a1fa8a82c33fb223b06fec566da1-refs/branch-heads/5672_63@{#10}`
OS | Windows 11 Version 22H2 (Build 22621.1702)

- Verified steps from [brave/brave-core#18017](https://github.com/brave/brave-core/pull/18017)
- Verified intent text is now all in uppercase and in bold


Dark | Light 
-- | --
![brave_E14QBCoZJb](https://github.com/brave/brave-browser/assets/17010094/f9333187-eece-4a82-b2e9-0c9c3ee689f0) | ![brave_tpgJQLWGye](https://github.com/brave/brave-browser/assets/17010094/716b31b8-00a7-40d5-bbf2-2f827a3e9e96)
