### ISSUE TITLE
(Tracking) Brave VPN IPv6 tests

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#28530]
## Description 
Before we go live with Brave VPN, we need to verify the IPv6 solution that we worked with the vendor on. Basically, they have a config on Windows only (does not apply to other platforms) which will assign a local link IPv6 IP (which is not routable).  This prevents requests being made on another adapter (if another adapter is configured with IPv6 and a website has IPv6 DNS records; ex `AAAA` record)

## Steps to Reproduce

   1. Be on a Windows machine with IPv6 setup
   2. Visit https://test-ipv6.com/ and make sure you get a good IPv6 score
   3. Buy Brave VPN and login to account.brave.com (or staging equivalent) to get credentials issued
   4. Connect to Brave VPN (any server)
   5. Run a few tests:
      - Open an instance of `cmd.exe` and run `ipconfig /all`. Verify that the `Brave VPN` (name differs depending on channel) connection:
          - Has an IPv4 address assigned
          - Has a local-link IPv6 IP address assigned (starts with `fe80`)
      - Is in the region you selected - visit https://whatismyipaddress.com/
      - https://test-ipv6.com/ should give a failing score (ex: IPv6 is not enabled)

## Expected result:
All of the tests should pass 

cc: @stephendonner @LaurenWags @kjozwiak

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.49.101 Chromium: 110.0.5481.104 (Official Build) beta (64-bit)
-- | --
Revision | 46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}
OS | Windows 10 Version 22H2 (Build 19045.2604)

### Confirmed:
* link-local `fe80::` IPv6 address
* `0/10` on IPv6 test
* no DNS-server (ISP) leaks
* `Cloudflare` was used as the `DoH` `Multi-Home Name Resolution` mitigation DNS provider

`default, 10/10 IPv6` | `Brave VPN, 0/10 IPv6` | `whatismyipaddress.com` | `browserleaks.com/dns` | `dnsleaktest.com`| `link-local fe80::`
----------|-----------|----------|-----------|-----------|----------
![image (5)](https://user-images.githubusercontent.com/387249/219843624-a153c5ad-8c38-458e-af91-4358d54a6235.png) | ![image (4)](https://user-images.githubusercontent.com/387249/219843625-8b5a00de-b7b1-4434-9715-4c81c17ea7ff.png) | ![image (3)](https://user-images.githubusercontent.com/387249/219843626-43d3080c-70e9-44a6-a60b-0e334969d772.png) | ![image (2)](https://user-images.githubusercontent.com/387249/219843627-b7c401c6-e0e7-4d84-9c9a-32be4b748f73.png) | ![image (1)](https://user-images.githubusercontent.com/387249/219843629-0ce313e2-ba1a-4733-af9f-5e3fa36f0f5f.png) | ![image](https://user-images.githubusercontent.com/387249/219843630-bcbd64c8-1be1-4c01-8dfc-a0793cf9e07e.png)

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.49.106 Chromium: 110.0.5481.104 (Official Build) beta (x86_64)
-- | --
Revision | 46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}
OS | macOS Version 11.7.4 (Build 20G1120)
