### ISSUE TITLE
[2.5-4] Device local time in the “Countdown to feature removal notification” is truncated

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#28538]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/27882
Device local time in the “Countdown to feature removal notification” is truncated 
## Steps to Reproduce

(Refer Scenario 3 from https://docs.google.com/document/d/1YVa6Wx4kMd90Q7mfx29iW--xa4tPNl7YXc486CkYQAI/edit#)

   1. Create a profile on 1.47.x or earlier and enable Rewards against staging in the US. 
   2. Update parameters endpoint (or set up a proxy) so that vbatDeadline is in the future. Note that vbatDeadline is a UTC date
   3. Update to 1.49.x. You should now be in the grandfathered-unverified state.
   4. Make sure the right values are coming from /parameters.
   5. Go to NTP Rewards widget, brave://rewards, and Rewards dropdown panel and check for notices.
   6. Inside each of the notices, make sure the date and time correspond with what’s at the /parameters endpoint. The parameters endpoint is in UTC, and the value shown in notices should be translated into your local device time.

## Actual result:

 The date and time which I have set at the /parameters endpoint in UTC 

```

[ REQUEST ]
> URL: https://api.rewards.bravesoftware.com/v1/parameters
> Method: GET
....
[ RESPONSE - OnResponse ]
> Url: https://api.rewards.bravesoftware.com/v1/parameters
> Result: Success
> HTTP Code: 200
> Body: {"autocontribute":{"choices":[1,2,3,5,7,10,20],"defaultChoice":1},"batRate":0.262301,"custodianRegions":{"bitflyer":{"allow":["JP"],"block":[]},"gemini":{"allow":["AU","AT","BE","CA","CO","DK","FI","HK","IE","IT","NL","NO","PL","PT","SG","ES","SE","US","GB"],"block":[]},"uphold":{"allow":["AU","AT","BE","CA","CO","DK","FI","HK","IE","IT","NL","NO","PL","PT","SG","ES","SE","US","GB","IN"],"block":[]}},"payoutStatus":{"bitflyer":"complete","gemini":"complete","payoutDate":"","unverified":"processing","uphold":"complete"},"tips":{"defaultMonthlyChoices":[1.25,5,10.5],"defaultTipChoices":[1.25,5,10.5]},"vbatDeadline":"2023-03-25T04:00:00Z","vbatExpired":false}
[19016:20660:0215/203558.920:VERBOSE9:logging_util.cc(135)]
```
local device time (IST) `March 25, 2023 at 9 AM` (IST = UTC + 5.30)

**Actual**: I am seeing `9 AM` instead of `9:30 AM`
![image](https://user-images.githubusercontent.com/38657976/219077162-fd457dfc-d595-4b10-b356-acd1631638a3.png)

## Expected result:

The device local time should be `9:30 AM` instead of  `9 AM` as the UTC time set at the parameter endpoint is `04:00:00` (IST = UTC +5.30)
## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.49.97 Chromium: 110.0.5481.77 (Official Build) beta (64-bit)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | Windows 10 Version 21H2 (Build 19044.2486)

</body>
</html>
## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @Miyayes @zenparsing

**Comment by kjozwiak** [comment]
The above requires `1.49.108` or higher for `1.49.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta (64-bit)
-- | --
Revision | 46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}
OS | Windows 10 Version 21H2 (Build 19044.2604)
```
- Verified the STR mentioned in the https://github.com/brave/brave-browser/issues/28538#issue-1586086530
- Ensured that the device local time in the “Countdown to feature removal notification” is shown correctly

The date and time which I have set at the /parameters endpoint in UTC
```
[ REQUEST ]
> URL: https://api.rewards.bravesoftware.com/v1/parameters
> Method: GET
....
[ RESPONSE - OnResponse ]
> Url: https://api.rewards.bravesoftware.com/v1/parameters
> Result: Success
> HTTP Code: 200
> Body: {"autocontribute":{"choices":[1,2,3,5,7,10,20],"defaultChoice":1},"batRate":0.262301,"custodianRegions":{"bitflyer":{"allow":["JP"],"block":[]},"gemini":{"allow":["AU","AT","BE","CA","CO","DK","FI","HK","IE","IT","NL","NO","PL","PT","SG","ES","GB"],"block":[]},"uphold":{"allow":["AU","AT","BE","CA","CO","DK","FI","HK","IE","IT","NL","NO","PL","PT","SG","ES","GB"],"block":[]}},"payoutStatus":{"bitflyer":"complete","gemini":"complete","payoutDate":"","unverified":"processing","uphold":"complete"},"tips":{"defaultMonthlyChoices":[1.25,5,10.5],"defaultTipChoices":[1.25,5,10.5]},"vbatDeadline":"2023-03-25T02:00:00Z","vbatExpired":false}
[22648:29344:0228/200934.416:VERBOSE9:logging_util.cc(135)]
```

The time set at the /parameters endpoint in UTC ---> "2023-03-25T02:00:00Z" 
IST (UTC + 5.30 ) --->7:30

brave://rewards | NTP | BR panel
----------------|---------|----------
![image](https://user-images.githubusercontent.com/38657976/221886630-e10d21a5-0383-4d92-ab43-39a7430f1575.png) | ![image](https://user-images.githubusercontent.com/38657976/221886712-99fb7e4c-afcd-4dc6-88a1-5b9e6436b176.png) | ![image](https://user-images.githubusercontent.com/38657976/221886856-dff97ff2-cf17-4bd8-8463-a5ff43938883.png)
