### ISSUE TITLE
Fix issue with multiple onboarding tabs opening up for Magic Eden

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#28546]
## Description 

When we try connect Brave Wallet to Magic Eden on Solana, it just creates multiple tabs endlessly. 

Attached is video replicating this issue. Done on 1.48 on desktop. 

https://user-images.githubusercontent.com/12224304/219126300-11ecdc88-2a5d-4f8a-baeb-dc00b2a96b7c.mov

## Steps to Reproduce

   1. try connecting Brave wallet to magic eden
   2. on 1.48
   3. with a new browser profile and don't have the wallet already created.

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.50.85 Chromium: 111.0.5563.64 (Official Build) beta  (64-bit) 
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Linux

- Verified steps from [brave/brave-core#17241](https://github.com/brave/brave-core/pull/17241)
- Verified only one onboarding tab is loaded when visiting `https://magiceden.io` and clicking on `Connect Wallet`
- Verified if an onboarding tab is already opened via the page, trying again to connect doesn't launch a new one

https://user-images.githubusercontent.com/17010094/224934970-a859c16b-4236-47ae-814b-0dd51ed44e58.mp4

---------------------

Verification passed on 

Brave | 1.50.85 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from [brave/brave-core#17241](https://github.com/brave/brave-core/pull/17241)
- Verified only one onboarding tab is loaded when visiting `https://magiceden.io` and clicking on `Connect Wallet`
- Verified if an onboarding tab is already opened via the page, trying again to connect doesn't launch a new one

https://user-images.githubusercontent.com/17010094/224939815-0b8b33a9-b778-42f7-86b9-9ab8653162f5.mp4


---------------------

Verification passed on 

Brave | 1.50.85 Chromium: 111.0.5563.64 (Official Build) beta (arm64)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#17241](https://github.com/brave/brave-core/pull/17241)
- Verified only one onboarding tab is loaded when visiting `https://magiceden.io` and clicking on `Connect Wallet`
- Verified if an onboarding tab is already opened via the page, trying again to connect doesn't launch a new one

https://user-images.githubusercontent.com/17010094/224940251-21f79067-6862-4ed0-8dea-ff7e5ab7bb4a.mov

**Comment by kjozwiak** [comment]
The above will require `1.49.132` or higher for `1.49.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.49.132 Chromium: 111.0.5563.147 (Official Build) (64-bit)
-- | --
Revision | `029fd65a4dd711d1078468ed2206999cec86066b-refs/branch-heads/5563@{#1239}`
OS | Windows 11 Version 22H2 (Build 22621.1413)

- Verified steps from [brave/brave-core#17241](https://github.com/brave/brave-core/pull/17241)
- Verified only one onboarding tab is loaded when visiting https://magiceden.io and clicking on Connect Wallet
- Verified if an onboarding tab is already opened via the page, trying again to connect doesn't launch a new one

https://user-images.githubusercontent.com/17010094/228196424-5459eedf-08e3-4710-a7ba-d7697e84f100.mp4
