### ISSUE TITLE
Videos on Rumble and Truth social do not play

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#28543]
## Description 

Videos on these websites appear to break unless you turn Shields off in the browser. Until then, rumble.com (for example) displays plain black loading screen. Alternatively, it appears that, for some users, changing the `Autoplay` permission to `Block`, then clicking on the video twice will force it to work.
![image](https://user-images.githubusercontent.com/3299098/219117258-e45a8693-8493-45d4-8a30-f68021b2cb30.png)

## Reproduces how often: 

Every time

## Brave version (brave://version info)

v1.48.164

## Version/Channel Information:

- Can you reproduce this issue with the current release? Y
- Can you reproduce this issue with the beta channel? Y
- Can you reproduce this issue with the nightly channel? Y

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Y
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? N

## Miscellaneous Information:

User thread:
https://community.brave.com/t/videos-wont-play-truth-social-rumble-maybe-more/470419/17

cc @ryanbr

**Comment by stephendonner** [comment]
As a datapoint, this is working for me using 

Brave | 1.49.97 Chromium: 110.0.5481.77 (Official Build) beta (x86_64)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | macOS Version 13.2.1 (Build 22D68)

I was able to play the video https://rumble.com/v29efac-breaking-ufo-pentagon-plot-exposed-as-deep-state-pushes-for-war-with-china-.html and others

<img width="1596" alt="Screenshot 2023-02-15 at 12 33 38 PM" src="https://user-images.githubusercontent.com/387249/219148087-3393b85d-0eb3-4394-994a-e60be7e03942.png">

**Comment by Saoiray** [comment]
Seems like whatever was causing issues has been resolved, at least for now. Not sure what was causing the conflict or if any changes/updates were made.

**Comment by ShivanKaul** [comment]
Closing since the community thread looks resolved

**Comment by nofunsir** [comment]
unresolved.
