### ISSUE TITLE
Cannot copy autocompleted url on macos

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#28542]
## Steps to Reproduce

- open new tab (command-T)
- type in enough text to get it to autocomplete a domain you’re interested in (for me, heart -> https://heartbleed.com/index.html)
- do not hit enter, instead do select all (command-A) and copy (command-C)
- move to slack or whatever and hit paste
- i get chrome://newtab/

## Actual result:

chrome://newtab/ copied

## Expected result:

omnibox url copied

## Reproduces how often: 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.49.118` or higher for `1.49.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.49.117 Chromium: 111.0.5563.50 (Official Build) (x86_64)
-- | --
Revision | 39f3dfc5023fe60997adc4f6cf5439cfa3e6968a-refs/branch-heads/5563@{#903}
OS | macOS Version 12.6.3 (Build 21G419)
```
