### ISSUE TITLE
Incorrect token symbol used when sending MATIC over Mumbai testnet

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#28548]
## Description 

"I sent some matic on Mumbai(Polygon testnet). But BraveWallet shows the history as eth was sent. and blockchain explorer link goes to etherscan(it should go to [mumbai.polygonscan.com](http://mumbai.polygonscan.com/)) even if block explorer was set correctly on setting."

https://bravesoftware.slack.com/archives/C02S9LFEXU4/p1676447615955399

## Actual result:

<img width="801" alt="スクリーンショット 2023-02-15 16 44 33" src="https://user-images.githubusercontent.com/30185185/219140628-9be83c93-efe4-41d0-9d1f-c1026741d9ef.png">

## Expected result:
Should display MATIC instead of ETH

## Reproduces how often: 

Easy

## Brave version (brave://version info)

1.47.186

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
Closing as this was uplifted into `1.48.x` via https://github.com/brave/brave-core/pull/17240. The above will require `1.48.166` or higher for `1.48.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.48.166 Chromium: 110.0.5481.100 (Official Build) (64-bit)
-- | --
Revision | `4be7a36f7cb943af6118e449bbab494b43dcaddd-refs/branch-heads/5481_77@{#14}`
OS | Windows 11 Version 22H2 (Build 22621.1265)

- Verified sending MATIC token on MUMBAI Network shows the correct token name
![image](https://user-images.githubusercontent.com/17010094/219589963-662b087b-3172-40c4-9467-76ae5ea48205.png)
