### ISSUE TITLE
Do not chain calls to fetch balance from custodian

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#28557]
## Description

>There's an issue with fetching the balance: we fetch it for all custodians chained one after the other, which is a bad approach, since there can't be multiple wallet providers connected at the same time. —Szilard

Note that users will be able to have multiple custodians connected in the future. But still, we shouldn't be chaining these calls necessarily.

**Comment by LaurenWags** [comment]
@Miyayes @szilardszaloki would one of you be able to suggest a test plan for this one? Marking as `QA/Blocked` until that's sorted. Thanks!

**Comment by szilardszaloki** [comment]
Given @GeetaSarvadnya's work on https://github.com/brave/brave-core/pull/17294 and https://github.com/brave/brave-core/pull/17480 (and that they're all going to `1.50.x`), I think we should label this as `QA/No`. cc: @Miyayes

**Comment by LaurenWags** [comment]
sgtm, will see what @Miyayes thinks 👍🏻

**Comment by Miyayes** [comment]
Put as QA/No, since I think it's covered by other issues as Szilard mentioned!
