### ISSUE TITLE
`navigator.connection` is present in service/web workers.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#28552]
This is a follow up issue for https://github.com/brave/brave-browser/issues/20122 which removed `navigator.connection`, but the attribute is still available in workers. Workers should not exhibit a different behavior regarding this attribute.

**STR:**
1. Start Brave
2. Navigate to the test page https://dev-pages.brave.software/dom-properties/controlled.html created by @pes10k 
3. Click `Run test`

**Expected results:**
In the `connection` row values for `Service` and `Web` `Workers` should be `null`

**Actual results:**
The values are `NetworkInformation` (meaning the attribute is available).

**Comment by kjozwiak** [comment]
The above requires `1.48.168` or higher for `1.48.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.48.169 Chromium: 110.0.5481.104 (Official Build) (x86_64)
-- | --
Revision | 46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}
OS | macOS Version 12.6.3 (Build 21G419)
```

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.48.169 Chromium: 110.0.5481.104 (Official Build) (64-bit) 
-- | --
Revision | 46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-browser/issues/28552#issue-1586671378.

![image](https://user-images.githubusercontent.com/34715963/220663115-b5e4de81-88b7-45f0-9d8c-5267fdd25916.png)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.48.169 Chromium: 110.0.5481.104 (Official Build) (64-bit)
-- | --
Revision | 46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}
OS | Windows 11 Version 21H2 (Build 22000.1574)
```
Verified with test plan from https://github.com/brave/brave-browser/issues/28552#issue-1586671378

Confirmed connection row values for `Service` and `Web` Workers are `null`

1.48.167 | 1.48.169
------ | ------
<img width="955" alt="image" src="https://user-images.githubusercontent.com/98358127/220673885-b614d5cf-9dfd-4671-b1b8-9d33ad8df9e1.png">|<img width="954" alt="image" src="https://user-images.githubusercontent.com/98358127/220672894-43ce6f0b-49e7-4a08-a8dd-85e7ef2a20ad.png">

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21 5G` using version:

```
Brave	1.48.169 Chromium: 110.0.5481.104 (Official Build) (64-bit) 
Revision	46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}
OS	Android 13; Build/TP1A.220624.014
```
Test Plan: https://github.com/brave/brave-browser/issues/28552#issue-1586671378

- Confirmed connection row values for Service and Web Workers are showing as null

Example | Example
-|-
![screenshot-1677083962862](https://user-images.githubusercontent.com/17885425/220697046-8df2e0ea-c344-4171-b4d5-1274e49cb72b.png) | ![screenshot-1677083990587](https://user-images.githubusercontent.com/17885425/220697055-a42e4ecf-61e3-4eee-97d3-69e9aac5f238.png)
