### ISSUE TITLE
Enable sharing_hub::kDesktopScreenshots feature

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#28560]
Enable `sharing-desktop-screenshots` feature by default

With this feature, we can see `screenshot` menu from sharing hub.
<img width="411" alt="image" src="https://user-images.githubusercontent.com/6786187/219273626-06c165ad-b462-4b4e-8740-d2bed325b659.png">

When download the screenshot file from below bubble,
proposed screenshot file name should have `brave_` prefix instead of `chrome_` prefix.
<img width="409" alt="image" src="https://user-images.githubusercontent.com/6786187/219273977-2bb5a39c-ae1d-47f3-af39-ab1fdd0d8f3c.png">

**Comment by LaurenWags** [comment]
Labelling as `QA/Blocked` for now, pending additional information/clarification on test plan from @rebron 

Current test plan (per description) is:

1. make sure Screenshot is available from sharing hub
2. make sure when downloading screenshot the file prefix is "brave_" not "chrome_"

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.50.110 Chromium: 112.0.5615.49 (Official Build) (x86_64)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | macOS Version 12.6.4 (Build 21G526)
```

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.50.112 Chromium: 112.0.5615.49 (Official Build) (64-bit)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
