### ISSUE TITLE
eth_signTransaction is using selected network for display

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#28564]
## Description 

`eth_signTransaction` is using the currently selected network, so it may display SOL if Solana network is selected

## Steps to Reproduce
   1. Load/run https://github.com/bbondy/eth-manual-tests
   2. Select Solana network in wallet panel
   3. Input to address in field beside `eth_signTransaction`
   4. Select `eth_signTransaction`

## Actual result:

https://user-images.githubusercontent.com/5314553/219460248-3c16bd8c-1e93-42d5-b104-dfb7935ad3d8.mov

## Expected result:

Does not display SOL

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

[Version 1.50.41 Chromium: 110.0.5481.100 (Official Build) nightly (arm64)](https://brave.com/latest/)

## Version/Channel Information:

Nightly

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by josheleonard** [comment]
fixed by: [eth_signTransaction is using selected network for display](https://github.com/brave/brave-browser/issues/28564#top)

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.57.18 Chromium: 115.0.5790.98 (Official Build) beta (64-bit)
-- | --
Revision | `d515871a6c6df7d2843e755c8b7dda9b744f26d6`
OS | Windows 11 Version 22H2 (Build 22621.1992)

- Verified steps from issue description
- Verified `eth_signTransaction` shows the correct token balance and network name on panel

https://github.com/brave/brave-browser/assets/17010094/bddc285a-5192-4da7-8290-11e3742b401f
