### ISSUE TITLE
Portfolio Breaks if Filtered network is hidden in settings

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#28570]
## Description 

If you select a network to filter by on the `Portfolio` page and then hide that network in brave://settings. The portfolio become broken until you select a new network filter.

## Steps to Reproduce

   1. Go to the `Portfolio` page and select a network to filter by
   2. Go to brave://settings and hide that network
   3. Go back to the `Portfolio` page
   4. Prices and balances are broken until you reselect a network to filter by

## Actual result:

https://user-images.githubusercontent.com/40611140/219496471-d445cc33-e12c-4cbc-afe8-afb5ab9b70df.mov

## Expected result:
If a user hides the network they have chosen to filter by on the portfolio, we should default back to `All Networks`

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.50.93 Chromium: 111.0.5563.64 (Official Build) beta  (64-bit) 
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Linux

- Verified steps from [brave/brave-core#17262](https://github.com/brave/brave-core/pull/17262)
- Verified selecting a network in portfolio and hiding it in settings doesn't break the portfolio page
- Verified with both portfolio and with selected network token page

https://user-images.githubusercontent.com/17010094/225829146-e791c3f0-02c2-4747-94e5-5fdc1c26f920.mp4


---------------------

Verification passed on 

Brave | 1.50.93 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from [brave/brave-core#17262](https://github.com/brave/brave-core/pull/17262)
- Verified selecting a network in portfolio and hiding it in settings doesn't break the portfolio page
- Verified with both portfolio and with selected network token page

https://user-images.githubusercontent.com/17010094/225829126-82a6e9c3-a796-4260-9a58-b1f49cecb950.mp4


---------------------

Verification passed on 

Brave | 1.50.93 Chromium: 111.0.5563.64 (Official Build) beta (arm64)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#17262](https://github.com/brave/brave-core/pull/17262)
- Verified selecting a network in portfolio and hiding it in settings doesn't break the portfolio page
- Verified with both portfolio and with selected network token page

https://user-images.githubusercontent.com/17010094/225829454-2899ea03-baaf-4b8a-9879-6ce2a7b80f1b.mov
