### ISSUE TITLE
why customize-chrome-side-panel flag doeesnt work

### ISSUE THREAD

**Issue by NaaeemMalik** [brave/brave-browser#28571]
##  Description 

why does brave side panel width cant be increased decreased while it can be from chrome://flags and works in chrome
if you can tell me how to fix I can create patch for it
did you guys disable it, I dont see anywhere its mentioned in code or issues

ID is SidePanelEntry::Id::kCustomizeChrome 
its being declared in src\chrome\browser\ui\views\side_panel\side_panel_entry.h

## Steps to Reproduce

   1.  chrome://flags 
   2. enable customize-chrome-side-panel flag
   3.  open sidepanel, cant be customized 

## Expected result:
sidepanels width can be customized 

## Brave version (brave://version info)
current  Beta Nightly and Release

@simonhong  @rebron  @bridiver @kim0 @mattmcalister @pes10k @bsclifton

**Comment by rebron** [comment]
Hi @NaaeemMalik. As noted brave://flags and chrome://flags flagged items are experimental features. Chrome's sidepanel and our implementation are different and will continue to be different.

**Comment by NaaeemMalik** [comment]
I want this feature so can you tell me how might I be able to enable it

**Comment by NaaeemMalik** [comment]
I tried to make it BuiltInItemType::kCustomizeChrome in brave code, it showed an additional item with reading list and wallet but it doesnt work 
also  returning 

case BuiltInItemType::kNone:
      // Add a new case for any new types which we want to support.
      // NOTREACHED() << "Asked for a panel Id from a sidebar item which should "
      //                 "not have a panel Id, sending Reading List instead.";
      return SidePanelEntry::Id::kCustomizeChrome;

doesnt do anything in brave\browser\ui\views\sidebar\sidebar_side_panel_utils.cc
