### ISSUE TITLE
[Speedreader] Isolated world id

### ISSUE THREAD

**Issue by boocmp** [brave/brave-browser#28581]
Speedreader part of https://github.com/brave/brave-browser/issues/28569

Using ISOLATED_WORLD_ID_BRAVE_INTERNAL instead of content::ISOLATED_WORLD_ID_CONTENT_END + 9

**Comment by diracdeltas** [comment]
this is actually a dupe of https://github.com/brave/brave-browser/issues/28569 fyi and @bridiver asked me to mark that p1 so this is becoming a p1
