### ISSUE TITLE
`Always Show Full URLs` option appears twice in `brave://settings/appearance`

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#28589]
## Description 

`Always Show Full URLs` option appears twice in `brave://settings/appearance`

## Steps to Reproduce

   1. install `1.50.43`
   2. launch Brave
   3. open `brave://settings/appearance`
   4. look for `Always Show Full URLs`

## Actual result:

It appears twice

<img width="1721" alt="Screen Shot 2023-02-17 at 10 16 25 AM" src="https://user-images.githubusercontent.com/387249/219747531-0961563f-d155-44e5-9b62-7ee7056328cf.png">

## Expected result:

Should only appear once. Top one should appear. The second entry below Show VPN button should be removed.

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.50.43 Chromium: 110.0.5481.100 (Official Build) nightly (x86_64)
-- | --
Revision | 4be7a36f7cb943af6118e449bbab494b43dcaddd-refs/branch-heads/5481_77@{#14}
OS | macOS Version 11.7.4 (Build 20G1120)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

/cc @brave/qa-team @rebron

**Comment by kjozwiak** [comment]
The above requires `1.49.108` or higher for `1.49.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta (x86_64)
-- | --
Revision | 46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}
OS | macOS Version 11.7.4 (Build 20G1120)

### Steps:
1. installed `1.49.108`
2. launched Brave
3. opened `brave://settings/appearance`
4. looked for `Always Show Full URLs`

#### Confirmed there's only 1 instance, it's in the correct position, is defaulted to `Off`/`Disabled` , and works when enabled

<img width="1312" alt="Screen Shot 2023-02-23 at 1 39 16 AM" src="https://user-images.githubusercontent.com/387249/220871729-b81c7e1c-f5e6-4408-bb19-cab9144f6d9c.png">
