### ISSUE TITLE
Verified checkmark icon is transparent rather than white in middle

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#2859]
The verified checkmark icon in brave://rewards is transparent rather than white in the middle. Consequently, when it’s overlaid atop a favicon as it is in brave://rewards, it can be difficult to see, as the underlying favicon shows through the checkmark.

**Comment by rossmoody** [comment]
![image 1](https://user-images.githubusercontent.com/29072694/50851396-8eb40b00-1331-11e9-948c-fcf45917b044.png)

**Comment by NejcZdovc** [comment]
will be pulled in as https://github.com/brave/brave-core/pull/1525 updates UI hash

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.61.37 Chromium: 73.0.3683.39 (Official Build) beta (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

![image](https://user-images.githubusercontent.com/34715963/53370959-628b3280-394f-11e9-97c0-3666c090bb43.png)
