### ISSUE TITLE
`Bookmark bar` should be `Bookmarks bar` in `brave://settings/appearance`

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#28590]
## Description 

`Bookmark bar` should be `Bookmarks bar` in `brave://settings/appearance`

## Steps to Reproduce

   1. install `1.50.43`
   2. launch Brave
   3. open `brave://settings/appearance`
   4. set `Show bookmarks` to `Only on the new tab page`
   5. read the descriptive text
   6. set `Show bookmarks` to `Never`
   7. read the descriptive text

## Actual result:

`Bookmark bar` | `Bookmarks bar`
-----------------|-----------------
<img width="687" alt="Screen Shot 2023-02-17 at 10 23 27 AM" src="https://user-images.githubusercontent.com/387249/219750800-d5212575-6165-4c83-a237-d77095cb35e3.png"> | <img width="668" alt="Screen Shot 2023-02-17 at 10 23 38 AM" src="https://user-images.githubusercontent.com/387249/219750812-43e62615-587a-4340-9cb3-76e7f85c618a.png">

## Expected result:

`Bookmarks bar`

## Reproduces how often: 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

cc @brave/qa-team @rebron @spylogsster @simonhong

**Comment by kjozwiak** [comment]
The above requires `1.49.108` or higher for `1.49.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.49.108 Chromium: 110.0.5481.104 (Official Build) beta (x86_64)
-- | --
Revision | 46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}
OS | macOS Version 11.7.4 (Build 20G1120)

### Steps:
1. installed `1.49.108`
2. launched Brave
3. opened `brave://settings/appearance`
4. changed the value of the `Show bookmarks` option to each of its values
5. examined the descriptive text

#### Confirmed it now reads `Bookmarks bar...` in each of the cases

`Always` | `Never` | `Only on the new tab page`
---------|----------|---------
<img width="1312" alt="Screen Shot 2023-02-23 at 1 47 42 AM" src="https://user-images.githubusercontent.com/387249/220873129-e26489cc-18e7-42e6-bcb4-a6c928200437.png"> | <img width="1312" alt="Screen Shot 2023-02-23 at 1 47 48 AM" src="https://user-images.githubusercontent.com/387249/220873140-15001e55-a13e-419f-9804-ba5b207b3117.png"> | <img width="1312" alt="Screen Shot 2023-02-23 at 1 47 54 AM" src="https://user-images.githubusercontent.com/387249/220873144-dd845d08-59d6-4c2b-a09b-3bba4e955fe3.png">
