### ISSUE TITLE
Vertical tabs: crash when dragging lock (in omnibox) to bookmarks toolbar

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#28592]
## Description 
When you want to add a bookmark to bookmarks toolbar, a common way to do this is dragging the lock icon next to the origin in the omnibox
![image](https://user-images.githubusercontent.com/4733304/219762237-f545d903-a74f-4357-8250-c4ccbb7acb32.png)

Doing this with vertical tabs enabled is crashing 😢

## Steps to Reproduce

   1. Enable vertical tabs
   2. Turn on bookmarks toolbar (Ctrl + Shift + B)
   3. Visit a site
   4. Drag the lock icon (next to origin) in omnibox down into bookmarks toolbar

## Actual result:
Crashes
See https://brave.sp.backtrace.io/p/brave/debug?filters=(_rxid%3Dd2990000-a35d-a509-0000-000000000000)&fingerprint=df991e32054f985cb224ee2700e823844a12dcda82b37a30cbb50fb36c1d8430&debug=(%2245f43ff%22,0,0)

## Expected result:
Should not crash

## Reproduces how often: 
100%

## Brave version (brave://version info)
Nightly - Win10 x64, 1.50.41

cc: @sangwoo108

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.50.91 Chromium: 111.0.5563.64 (Official Build) beta (x86_64)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | macOS Version 12.6.3 (Build 21G419)
```

Reproduced the crash using STR and `1.49.120 Chromium: 111.0.5563.64 (Official Build) (x86_64)`
