### ISSUE TITLE
Add P3A questions for Rewards conversion

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#28597]
Cases to consider:

* Rewards NOT enabled case
* Rewards enabled (non-connected state) && available custodian
* Rewards enabled (non-connected state)  && NO available custodian

Metrics:

All metrics below are ephemeral, meaning they only get sent once per event. This will result in counts of users enabling ads on a weekly basis.

"If you enabled rewards this week, how did you enable it?"
`Brave.Rewards.EnabledSource`

0) Inline tip button
1) BAT icon in the address bar
2) Rewards card on NTP

"If rewards are disabled, did you click on the inline [Tip] button this week?"
`Brave.Rewards.InlineTipTrigger`

1) Yes

"If rewards are disabled, did you click on the BAT icon in the URL this week?"
`Brave.Rewards.ToolbarButtonTrigger`

1) Yes

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave | 1.52.84 Chromium: 113.0.5672.63 (Official Build) beta (64-bit)
-- | --
Revision | 0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}
OS | Windows 10 Version 21H2 (Build 19044.2846)

```

**Comment by GeetaSarvadnya** [comment]
@Miyayes If we enable the rewards via Hamburger menu `Brave Rewards` option the metrics `Brave.Rewards.EnabledSource` is NOT recorded at the client side in the brave://local-state file, Is the scenario skipped intentionally ? the no of user who enable rewards via Hamburger menu is less as compared to BR panel, NTP and Inline tip?? 

cc: @DJAndries @LaurenWags

**Comment by GeetaSarvadnya** [comment]
@DJAndries I don't see the metrics `Brave.Rewards.InlineTipTrigger` and `Brave.Rewards.ToolbarButtonTrigger` in any condition. Could you please let me know the steps to trigger these conditions? Thanks!

**Comment by DJAndries** [comment]
@GeetaSarvadnya 

> If we enable the rewards via Hamburger menu Brave Rewards option and brave://settings/rewards, the metrics Brave.Rewards.EnabledSource is NOT recorded at the client side in the brave://local-state file, these two options to enable the rewards are NOT covered in the description. 

this is correct, we are only monitoring the three mentioned sources

> I don't see the metrics Brave.Rewards.InlineTipTrigger and Brave.Rewards.ToolbarButtonTrigger in any condition.

please ensure that rewards is not enabled, and that you review the local state page before enabling rewards.
