### ISSUE TITLE
Sell UI Improvements

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#28596]
## Description 

Some improvements need for the `Sell` UI

- We need to clear the input amount after closing the `Sell` modal
- Remove `USDC` and `USDT` on `Solana` since they are not available at the moment
- Show a warning message if the user enters an amount less than $50 since that is the minimum for `Ramp`
- Fix text in the `Sell` modal not using font-family `Poppins`

**Comment by kjozwiak** [comment]
The above requires `1.49.117` or higher for `1.49.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.49.118 Chromium: 111.0.5563.50 (Official Build) (64-bit) 
-- | --
Revision | `39f3dfc5023fe60997adc4f6cf5439cfa3e6968a-refs/branch-heads/5563@{#903}`
OS | Linux

- Verified steps from [brave/brave-core#17282](https://github.com/brave/brave-core/pull/17282)
- Verified amount is reset when sell modal is closed and reopened
- Verified `USDC` and `USDT` on Solana Mainnet doesn't show `Sell` option

https://user-images.githubusercontent.com/17010094/222704546-ee6608bc-6d83-49d4-98e0-53cdf0fe89bd.mp4

---------------------

Verification passed on 

Brave | 1.49.118 Chromium: 111.0.5563.50 (Official Build) (64-bit)
-- | --
Revision | `39f3dfc5023fe60997adc4f6cf5439cfa3e6968a-refs/branch-heads/5563@{#903}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#17282](https://github.com/brave/brave-core/pull/17282)
- Verified amount is reset when sell modal is closed and reopened
- Verified `USDC` and `USDT` on Solana Mainnet doesn't show `Sell` option

https://user-images.githubusercontent.com/17010094/222704732-bb0216a4-3e86-4cba-a5f9-715d7cf0e651.mp4

---------------------

Verification passed on 

Brave | 1.49.118 Chromium: 111.0.5563.50 (Official Build) (arm64)
-- | --
Revision | `39f3dfc5023fe60997adc4f6cf5439cfa3e6968a-refs/branch-heads/5563@{#903}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#17282](https://github.com/brave/brave-core/pull/17282)
- Verified amount is reset when sell modal is closed and reopened
- Verified `USDC` and `USDT` on Solana Mainnet doesn't show `Sell` option

https://user-images.githubusercontent.com/17010094/222705234-9f2b964a-db98-49af-a219-862a68777239.mov
