### ISSUE TITLE
9gag promoted ads

### ISSUE THREAD

**Issue by 424344** [brave/brave-browser#28609]
## Description 

on https://9gag.com there are "promoted" posts that are not blocked.
they popup after scrolling down on the main page.

here is an example:
![image](https://user-images.githubusercontent.com/26486758/219939774-e91079d8-b9d6-4613-ac46-5bd83a224211.png)

I have inspected the code:

![image](https://user-images.githubusercontent.com/26486758/219939951-23ce3e97-66cd-4854-91d5-d0fb4199f7f1.png)

the issue is that the article id is random.

## Steps to Reproduce

   1. load the main 9gag page
   2. scroll down until you see a promoted post
   3. 

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by Emi-TheDhamphirInLoveUnderTheFrozenStar** [comment]
`9gag.com#?#article:-abp-has(.promoted)` in Easylist is not supported by Brave, it shall be fixed when https://github.com/brave/adblock-rust/pull/273 is merged.

I don't know if Stable already has :has support but Nightly does, so you can temporary add 9gag.com##article:has(.promoted) until Brave team merges that PR and it gets compatibility with those ABP extended CSS selectors.

**Comment by LaurenWags** [comment]
Not seeing a difference between 1.49.120 (current release) and 1.51.91 (beta).

Asked about it here - https://bravesoftware.slack.com/archives/C3GNZANPR/p1678887643343389.

Labelling as `QA/Blocked` until we figure this out.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.50.91 Chromium: 111.0.5563.64 (Official Build) beta (x86_64)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | macOS Version 12.6.3 (Build 21G419)
```

Verified STR from description.
Confirmed when using `Aggressive` blocking for trackers and ads the promoted posts are not displayed on the site.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.50.99 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | Windows 11 Version 22H2 (Build 22621.1413)
```
Verified STR from description.
Confirmed when using `Aggressive` blocking for trackers and ads the promoted posts are not displayed on the site.

Standard (Default) | Aggressive
----- | ----
<img width="952" alt="image" src="https://user-images.githubusercontent.com/98358127/227254364-24a99470-689e-4e81-8546-8561ebaf3813.png">|<img width="945" alt="image" src="https://user-images.githubusercontent.com/98358127/227254653-a6816e50-54d5-40cf-864e-d4b7d0851f4c.png">

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 13` using the following build(s):

```
Brave | 1.50.112 Chromium: 112.0.5615.49 (Official Build) (32-bit)
--- | ---
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Android 13; Build/TQ2A.230305.008.E1
```

Went through the STR/Cases outlined via https://github.com/brave/brave-browser/issues/28609#issue-1590621561 and ensured that `Promoted` posts/content isn't being displayed when `Aggressive` blocking is being used as per the following:

**`Example`** | **`Example`**
----------------|-----------------
![Screenshot_20230403-232712](https://user-images.githubusercontent.com/2602313/229680030-eae09ed0-4fba-4622-afcd-59e19effafab.png) | ![Screenshot_20230403-232734](https://user-images.githubusercontent.com/2602313/229680036-50810dc3-9082-4da3-bb92-540b44541de7.png)
