### ISSUE TITLE
Problem with extra flags in signing process on CI

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-browser#2860]
## Description 
During CI a dev CI build, it is broken with the following error

`
18:35:42 + [[ -z '' ]]
18:35:42 /Users/jenkins/jenkins/workspace/brave-browser-build-darwin/src/out/Release/Brave Browser Dev Packaging/sign_app.sh: line 68: provisioning_profile: unbound variable
18:35:42 [ERROR] ./../../brave/build/mac/sign_app.sh failed
18:35:42 ../../brave/build/mac/sign_app.sh failed with exit code 1
18:40:19 [12/25] ACTION //brave/app/mac:generate_breakpad_symbols(//build/toolchain/mac:clang_x64)
18:40:19 ninja: build stopped: subcommand failed.
18:40:19 null`

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
0.60.8

**Comment by LaurenWags** [comment]
@jsecretan @bridiver does this require manual QA? If so, could you please add a test plan and appropriate labels?

**Comment by kjozwiak** [comment]
Labelling as `QA/No` after speaking with @bridiver 👍
