### ISSUE TITLE
Add `Power` part in `System` section in Settings UI

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#28615]
STR
1. Load brave://settings
2. Check `System` section has `Performance` part (Memory saver is off by default)
3. Check it has `Power` part when device has battery (First option is selected by default)
4. Go to app menu -> More tools and click Performance and check brave://settings/system page is loaded

**Comment by LaurenWags** [comment]
cc @kjozwiak to take a look at this one on his Win 11 laptop

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.50.101 Chromium: 111.0.5563.116 (Official Build) beta (64-bit)
-- | --
Revision | ade86b9472831e26d87fd569e04b404be01e1e2b-refs/branch-heads/5563@{#1209}
OS | Windows 10 Version 22H2 (Build 19045.2728)

### Shared Steps:
1. installed `1.50.101`
2. launched Brave
3. clicked on the app menu
4. clicked on `More Tools`
5. clicked on `Performance`
6. confirmed it opened `brave://settings/system`
