### ISSUE TITLE
[ CRASH ! ] when dragging URL elements to the address bar or to the bookmarks bar (this has been happening for 2 months now!)

### ISSUE THREAD

**Issue by illtellyoulater** [brave/brave-browser#28613]
Brave crashes immediately when dragging any URL element (<a href ... >) into the address bar, 

It happens as soon as the dragged element enters the address bar area, and before releasing the mouse button.

OS: Window 10 64 bit
Brave version: latest stable build [Version 1.49.120 Chromium: 111.0.5563.64 (Official Build) (64 bit)]

I update Brave regularly, and this has been happening at least for about a month, so I think this was introduced 2 or 3 updates ago.

**Comment by illtellyoulater** [comment]
Why has this not received even a simple acknowledgment from the devs times, given I posted this almost one month ago and considering it's about a bug introduced more than 2 months ago? 

It's also producing a crash and will basically hit you almost every time you are dragging a link around, as I could now verify that it won't only be triggered when dragging to the address bar, but also when dragging to the bookmarks strip.

I think this might be correlated to this other issue: https://github.com/brave/brave-browser/issues/27796

That said... I would have expected at least a decent level of reactivity from the Brave devs... but all I can see here is complete silence...

**Comment by illtellyoulater** [comment]
@simonhong @sangwoo108 @mkarolin @emerick

I've seen you guys have been recently working on very similar issues, so can you please take a look at this?
Thanks!

**Comment by sangwoo108** [comment]
> Why has this not received even a simple acknowledgment from the devs times, given I posted this almost one month ago and considering it's about a bug introduced more than 2 months ago?

Hi, @illtellyoulater . Sorry for delayed response. It seems we didn't notice this issue as no one was assigned. Could you help us to clarify the problem? I have a few questions.

* Are you using the official version?
* Are you using vertical tabs? - in case of this, this could have been resovled in Nightly version.

**Comment by illtellyoulater** [comment]
Hi @sangwoo108, thanks for replying. 
Yes I'm using the official version and vertical tabs.

**Comment by sangwoo108** [comment]
Thanks @illtellyoulater .

> Are you able to reproduce the problem?

Yeah, as you noticed, I belive https://github.com/brave/brave-browser/issues/28592 is the same one for this, and it should be fixed on Beta and Nightly. Unfortunately, as vertical tab strip is an experimental feature, it's unlikely to release a hot fix for this - Even I'm suffering from this myself 😥. So you might want to use Beta or Nightly for a while. Sorry for the inconvenience.

**Comment by sangwoo108** [comment]
Please let me know if you still see this on Beta and Nightly. If you could mention or assign me, I could take a look quickly. Thank you for reporting again!
