### ISSUE TITLE
Unable to Unfollow Brave News Topic (Top sources)

### ISSUE THREAD

**Issue by DesertBear** [brave/brave-browser#28610]
## Description 
On a newly installer Brave browser, I am unable to "unfollow" the default Brave News topic (Top sources).  The mouse click is registered, however it is not possible to unfollow it.

I'm not sure whether it's related to these two closed issues.

https://github.com/brave/brave-browser/issues/26303

https://github.com/brave/brave-browser/issues/26255

## Steps to Reproduce

   1. Open a new tab, which is set to open on the Brave Dashboard.
   2. Go to [Customise > Brave News].
   3. Try to unfollow the "Top sources" topic.

## Actual result:
Clicking on the unfollow button in the left-hand column does not unfollow the "Top sources" topic.  Neither does clicking the unfollow button on the card on the right-hand side.

_Video showing unfollow buttons not working:_

https://user-images.githubusercontent.com/27423064/219960477-2f9a6e6d-000e-4313-8302-b883ea2b6869.mp4

## Expected result:
The unfollow button should unfollow the topic.

## Reproduces how often: 
It is reproducible on this machine every time.  However, I installed Brave in a virtual machine and on that machine I am unable to reproduce the issue.

## Brave version (brave://version info)
```
Brave:     1.48.167 Chromium: 110.0.5481.104 (Official Build) (64-bit) 
Revision:  46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}
OS:        Windows 10 Version 22H2 (Build 19045.2604)
```

**Comment by DesertBear** [comment]
Closing, as I have been unable to reproduce this issue again.

**Comment by ShivanKaul** [comment]
I'm running into this bug on two old profiles locally, though I can't repro on a brand new profile.

https://github.com/brave/brave-browser/assets/5284154/21712dd4-f4ea-4584-8d26-783e776753b2
