### ISSUE TITLE
Implement rounded corners on the Brave Rewards dropdown panel

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#28622]
##

**Comment by mkarolin** [comment]
Test Plan:
1. Start Brave
2. Click on the Rewards button and verify that the panel has rounded corners (all 4).

**Comment by LaurenWags** [comment]
Added `QA/Test-All-Platforms` as we have seen OS specific differences with the rounded corners previously.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.53.83 Chromium: 114.0.5735.110 (Official Build) beta (64-bit)
-- | --
Revision | 1c828682b85bbc70230a48f5e345489ec447373e-refs/branch-heads/5735_90@{#13}
OS | Windows 11 Version 22H2 (Build 22621.1702)
```


non-connected users

- Confirm that the BR panel corners are rounded in non-connected users state
- Confirm that the BR panel corners are rounded for unverified creators

Example | Example 
----- | -----
![image](https://github.com/brave/brave-browser/assets/98358127/091387e2-fd23-4706-8774-9222c260d21f)|![image](https://github.com/brave/brave-browser/assets/98358127/14a8c770-435b-4455-8ada-723a9a804b0c)

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.53.85 Chromium: 114.0.5735.110 (Official Build) beta (x86_64)
-- | --
Revision | 1c828682b85bbc70230a48f5e345489ec447373e-refs/branch-heads/5735_90@{#13}
OS | macOS Version 13.4 (Build 22F66)
```

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.53.87 Chromium: 114.0.5735.110 (Official Build) beta (64-bit) 
Revision	1c828682b85bbc70230a48f5e345489ec447373e-refs/branch-heads/5735_90@{#13}
OS	Linux
```
