### ISSUE TITLE
On Solana Swaps, you can make an order for funds you don't have 

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#28623]
## Description 

We let an order get created even though we know the user doesn't have that balance. Tested this flow on Uniswap, Matcha and Jup.ag and
<img width="633" alt="Screenshot 2023-02-20 at 22 04 44" src="https://user-images.githubusercontent.com/12224304/220198397-0efcbbdf-26a7-4d5d-a7d1-6511443ed64d.png">
 they didn't allow an user to create it. 

Attached is screenshot
<img width="1087" alt="Screenshot 2023-02-20 at 21 58 29" src="https://user-images.githubusercontent.com/12224304/220198072-e6aba93e-cbab-4722-9363-658ce76fba24.png">

## Steps to Reproduce

   1. Select USDC to SOL
   2. Select more USDC than you have in your wallet
   3. Order gets created

## Expected result:

It doesn't allow you to create this transaction
## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.49.118` or higher for `1.49.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.49.118 Chromium: 111.0.5563.50 (Official Build) (64-bit)
-- | --
Revision | `39f3dfc5023fe60997adc4f6cf5439cfa3e6968a-refs/branch-heads/5563@{#903}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from issue description
- Verified cannot place order on Solana Swap when there is no enough token balance
- Verified `Review order` is disabled if the balance is insufficient
- Verified `Review order` button changes to `Insufficient XXX balance` and is disabled preventing user to place order on a token without any balance

![image](https://user-images.githubusercontent.com/17010094/222710143-13e6ab32-b643-4326-af31-2f9da3d05254.png) | ![image](https://user-images.githubusercontent.com/17010094/222710335-feb4f6e8-25d6-477e-90e2-6f77b4d4940d.png)
-- | --
