### ISSUE TITLE
ERC721 NFTs with same token identifiers may show incorrect balance

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#28627]
## Description 
Balance are computed based on symbol and tokenId that can cause issues while computing balance of NFTs having same tokenIds on ETH.

## Steps to reproduce 

Note: Haven't tested but logically the issue should be reproducible with:
   1. Buy NFTs with same IDs [NFT1](https://opensea.io/assets/ethereum/0x23581767a106ae21c074b2276d25e5c3e136a68b/163) and [NFT2](https://opensea.io/assets/ethereum/0x85d39cea74b0baba54d7fd0df42dd3e6e39b1625/163)
   2. The balance will be inaccurate

or can use https://github.com/brave/brave-ios/issues/6954#issuecomment-1437950936

   1. Buy two NFTs with same contract addressed and symbol. e.g.  [NFT1](https://testnets.opensea.io/assets/goerli/0xef6cdea5845c5ce10a533bd20fdfe9b174ab1687/9) and [NFT2](https://testnets.opensea.io/assets/goerli/0xef6cdea5845c5ce10a533bd20fdfe9b174ab1687/4)
   2. Make sure the balance is accurate on Portfolio screen

## Actual result 
Incorrect balance

## Expected result
Correct balance of NFTs with same tokenIds

### Additional information

https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1676555545832879

**Comment by srirambv** [comment]
Marking as QA/No as there is no way to check this one with the new NFT tab. More info [here](https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1682486743965259)
