### ISSUE TITLE
Tab UI breaking on New Window

### ISSUE THREAD

**Issue by dpthegrey** [brave/brave-browser#28625]
## Steps to Reproduce

   1. open new window
   2. tab looks like attached image below
   3. then i add another tab using cmd+t and tabs look alright again

## Actual result:

![image](https://user-images.githubusercontent.com/49444980/220209262-6b4cf870-f93c-4204-93fb-9ab93cfdfb5b.png)

## Expected result:
![image](https://user-images.githubusercontent.com/49444980/220209437-d161a405-66b2-412c-9ecf-b55495475432.png)

## Reproduces how often: 

Every time i open a new window.

## Brave version (brave://version info)

1.48.164 Chromium: 110.0.5481.100 (Official Build) (x86_64) 

## Version/Channel Information:

- Can you reproduce this issue with the current release?   Yes.
- Can you reproduce this issue with the beta channel?       Not tried.
- Can you reproduce this issue with the nightly channel?   Not tried.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?   Not a Brave Shields issue
- Does the issue resolve itself when disabling Brave Rewards?  Not a Brave Rewards issue
- Is the issue reproducible on the latest version of Chrome?     Not used on Chrome.

## Miscellaneous Information:

When I add another tab after opening new window, the tabs go back to normal. That is how I captured the Expected Result picuture.

**Comment by dpthegrey** [comment]
cc: @sangwoo108

**Comment by dpthegrey** [comment]
now this is not happening, I cannot recall what i did specific, might have toggled vertical tabs and got back to normal horizontal tab layout

**Comment by dpthegrey** [comment]
Happened again. Version 1.51.24 Chromium: 111.0.5563.64 (Official Build) nightly (x86_64)

![image](https://user-images.githubusercontent.com/49444980/224469449-afda8192-ef74-48ac-9b97-fb8aecd7788f.png)

**Comment by sangwoo108** [comment]
Thanks @dpthegrey ! I believe those are sorted out in the Nightly. As the vertical tab strip feature is behind the flag, we didn't release a hot fix for them. Please let me know if you see this on Nightly too. Thank you again!

**Comment by sangwoo108** [comment]
Oh, one more thing, currently scrollable tab strip is not working well on Nightly. But it's on my task list.
