### ISSUE TITLE
Brave Rewards should clearly show if wallet is for staging environment

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#2862]
## Description 

When running locally or when using the flags (`--rewards=staging=true`), it's not entirely clear (at least to me) whether the wallet is staging or prod. This can cause some testing confusion.

I'd like to propose showing a `Staging` badge on the page to make it painfully obvious that the wallet in question is for the staging environment.

## Steps to Reproduce

   1. Create a staging wallet
   2. Visit brave://rewards
   3. No indication whether or not wallet is staging

## Reproduces how often: 

100% when running from source or via the flags (`--rewards=staging=true`)

**Comment by bsclifton** [comment]
I think this would be easy enough to add to brave://rewards-internals/

**Comment by mkarolin** [comment]
Notes for QA:
1. This only works for newly created rewards profiles (new browser profile or reset rewards).
2. Design change:
    a. `Creation environment: <Environment>` is added under the `Rewards payment ID:` line.
    b. If the current environment is different from the creation environment then `Current environment: <Environment>` is added underneath in red.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.49.92 Chromium: 110.0.5481.77 (Official Build) beta (x86_64)
-- | --
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | macOS Version 12.6.3 (Build 21G419)
```
