### ISSUE TITLE
Speedup fetching of token balances in Swap

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#28634]
Currently Swap suffers from a performance issue that's unique to it since we fetch balances for the entire tokens list, instead of just the visible assets list. This results in hundreds of mojo calls, which we can potentially cut down to a single one using the new [`GetERC20TokenBalances`](https://github.com/brave/brave-core/blob/974a105a569d11a9bc13e92ba15fc39eba99265f/components/brave_wallet/common/brave_wallet.mojom#L1046-L1054) mojo method.

We can expect a speedup of 3x-10x, depending on the size of the tokens list. Following this improvement, we can also periodically refresh the balances without incurring a heavy cost.

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.51.97 Chromium: 112.0.5615.138 (Official Build) beta (64-bit)
-- | --
Revision | `2258f2fcaeb07bc95c992b7ca47f0b43ead9865c-refs/branch-heads/5615@{#1282}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from [ brave/brave-core#17371](https://github.com/brave/brave-core/pull/17371)
- Verified token balances are correctly fetched in Swap screen
