### ISSUE TITLE
sync chain cancellation in `Start a new sync chain` may confuse users 

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#2863]
## Steps to Reproduce

1. Clean profile
2. Open `brave://sync/`
3. Click `Start a new sync chain`
4. Click `Phone/Tablet`
5. Click `Cancel`

## Actual result:

1 . User clicks `Cancel` and gets `Are you sure?` dialog.
![image](https://user-images.githubusercontent.com/34715963/50865675-02442f80-13a7-11e9-82d0-eaef852c0363.png)
2. User thinks `Yes, Cancel`. User clicks `Cancel` as confirmation of the intent of cancelling the sync.
Alternative choice isn't helpful as it says `Exit modal`. User wonders what a modal is and if `Are you sure?` dialog is a modal.

![cancel sync](https://user-images.githubusercontent.com/34715963/50867132-d9726900-13ab-11e9-899f-a12898e5c74a.gif)

## Expected result:
The dialog should not confuse the user

## Brave version (brave://version info)

Brave | 0.59.20 Chromium: 72.0.3626.28 (Official Build) beta (64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Windows

cc @bradleyrichter @rossmoody @brave/legacy_qa

**Comment by rebron** [comment]
Addressing the changes to dialog here to remove references to "modal". https://github.com/brave/brave-browser/issues/2884

I think we still might need to be clearer with 'Cancel' and 'Exit' on that dialog though.

**Comment by srirambv** [comment]
@rebron we could just add `Cancel Sync Setup` on the QR/Code word modal instead of just `Cancel`. That makes it clear that you want to cancel creating a sync chain. The pop up modal cancel button is self explanatory that you want to cancel the modal and go back

**Comment by rebron** [comment]
@srirambv take a look at what @bradleyrichter proposed for #2884. We needed better wording for that dialog anyway. Should be clearer now.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.59.25 Chromium: 72.0.3626.53 (Official Build) beta (64-bit)
-- | --
Revision | 98434e6cd182d68ce396daa92e9c6310422e6763-refs/branch-heads/3626@{#620}
OS | Windows 7

![image](https://user-images.githubusercontent.com/34715963/51358336-fcdf9700-1ac2-11e9-8c9c-2097e820715d.png)
