### ISSUE TITLE
Swap inputs should be debounced

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#28631]
Currently, N updates to the From/To amounts in Swap will trigger N requests to the 0x/Jupiter APIs. This is not just unnecessary, but also makes the UI sluggish due to large number of HTTP requests being triggered.

The input fields should therefore be debounced - meaning, a request to the 0x/Jupiter API will only be done after 1s (say) has passed since the last keystroke.

**Comment by kjozwiak** [comment]
The above requires `1.49.118` or higher for `1.49.x` verification 👍
