### ISSUE TITLE
Abort fetching of swap quotes if a reset is triggered in-flight

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#28630]
Triggering a reset action, for example by clearing the inputs, should abort any quote requests that are in flight. This avoids having zombie quotes like the one you see in the recording below.

https://user-images.githubusercontent.com/3684187/220304745-55d6285f-1e69-4e84-949b-065fc6128a4c.mov

**Comment by kjozwiak** [comment]
The above requires `1.49.118` or higher for `1.49.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.49.118 Chromium: 111.0.5563.50 (Official Build) (64-bit)
-- | --
Revision | `39f3dfc5023fe60997adc4f6cf5439cfa3e6968a-refs/branch-heads/5563@{#903}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from issue description
- Verified fetching swap quotes is reset when input is deleted during in-flight
- Encountered [#28819](https://github.com/brave/brave-browser/issues/28819)

https://user-images.githubusercontent.com/17010094/222714598-d50815d3-9a2b-4c59-a20d-8112057ec5df.mp4
