### ISSUE TITLE
Swap scans for token balances 3 times on first load

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#28635]
It should scan for token balances only once. This is adversely impacting performance until all the 3 scans are complete.

**Comment by kjozwiak** [comment]
The above requires `1.49.118` or higher for `1.49.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.49.118 Chromium: 111.0.5563.50 (Official Build) (64-bit)
-- | --
Revision | `39f3dfc5023fe60997adc4f6cf5439cfa3e6968a-refs/branch-heads/5563@{#903}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from issue description
- Verified token balance is updated on loading portfolio page and when switching networks or accounts
