### ISSUE TITLE
Solana transactions seems submitted on browser side but looking up at the transaction hash doesn't show any confirmed/failed transactions

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#28645]
## Description 

Solana transactions seems submitted on browser side but looking up at the transaction hash doesn't show any confirmed/failed transactions

## Steps to Reproduce

   1. Submit a Swap transaction of SOL to USDC
   2. Browser shows submitted transaction 
   3. Click on Transaction hash from panel/transactions tab
   4. Block explorer shows no transactions
   5. Transaction remains as submitted

## Actual result:

https://user-images.githubusercontent.com/17010094/220384135-0e461e66-6498-4149-9db8-33b1e87a3db5.mp4

Actual transaction from Brave UI: https://explorer.solana.com/tx/2z4kvG1wUANGGTfgx63KeiiJ5itvQM5qtbsQK7ttJhhTMjT9N16SRuoKzReRut3KR23FaS6U2PoRfC7RCEv1J5gU

## Expected result:
Should retry or fail the transaction 

## Reproduces how often: 

Intermittent

## Brave version (brave://version info)

All

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @onyb @HEagle18

**Comment by jamesmudgett** [comment]
Should retry from core (no UI needed)

**Comment by kjozwiak** [comment]
The above requires `1.52.101` or higher for `1.52.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.52.102 Chromium: 113.0.5672.126 (Official Build) beta (64-bit)
-- | --
Revision | `c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}`
OS | Windows 11 Version 22H2 (Build 22621.1702)

- Verified as part of [#30297 (comment)](https://github.com/brave/brave-browser/issues/30297#issuecomment-1552762322)

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.52.112 x64 build
- Verified as part of [#30297 (comment)](https://github.com/brave/brave-browser/issues/30297#issuecomment-1562742127)
