### ISSUE TITLE
Remove search engine onboarding for IN

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#28656]
This is a follow up of : https://github.com/brave/brave-browser/issues/27709.
we need to remove search engine onboarding for IN region as we have made Brave search as default for IN. 

QA note : We need to make sure that tapping on search bar shouldn't show the search engine onboarding for the first time.

**Comment by kjozwiak** [comment]
@brave/qa-team can use https://github.com/brave/brave-core/pull/17316#issuecomment-1450712852 as an example of the cases/checks to run through as the issue is light on STR/Cases . The above requires `1.49.117` or higher for `1.49.x` verification 👍
