### ISSUE TITLE
[Android] Update "Open tabs in Custom Tabs" setting copy

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#28652]
### Description
Update the copy for the `Open tabs in Custom Tabs` settings toggle:

**Header:** Open external links in Brave webview
**Description:** Opens links from other apps in a Brave webview. Note: Brave must be set as your default browser.

### Why
The existing copy does not accurately describe what happens when the setting is enabled.

cc @bradleyrichter @anthonypkeane @SergeyZhukovsky @samartnik @rmcfadden3

**Comment by vlad-hoff** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 [panther_beta-user 14 UPB2.230407.019 release-keys]
Brave build: 1.53.83
Chromium: 114.0.5735.110 (Official Build) beta (64-bit)
Revision: 1c828682b85bbc70230a48f5e345489ec447373e-refs/branch-heads/5735_90@{#13}
```

NOTE: Confirmed with @deeppandya that the title string updated from `Open external links in Brave webview` to `Open external links in Brave`.

---------------------------

**STEPS:**
1. Launch Brave
2. Three-dot Menu > Settings 
3. Scroll down and find `Open external links in Brave` > Verify

**ACTUAL RESULTS:**
- Verified that the title is `Open external links in Brave`
- Verified that subtitle is `Opens link from other apps in a Brave webview. Note: Brave must be set as your default browser.`
- Verified that the default setting is ON
- Verified that links are opened as expected depending on the setting ON or OFF

![Screen_12-33-47](https://github.com/brave/brave-browser/assets/128532965/b53da6b3-16bd-418a-aa2c-0925b604b1f3)

https://github.com/brave/brave-browser/assets/128532965/57ccd5c8-b708-4654-83cf-e6de18c7fe9f
