### ISSUE TITLE
[Android] Update "Enable Tab Group auto creation" setting copy

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#28653]
### Description
Update the copy for the `Enable Tab Group auto creation` settings toggle:

**Header:** Only open links in current tab group
**Description:** Automatically opens all links in the current tab group

### Why
The existing copy does not accurately describe what happens when the setting is enabled.

cc @bradleyrichter @anthonypkeane @SergeyZhukovsky @samartnik @rmcfadden3

**Comment by vlad-hoff** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 [panther_beta-user 14 UPB2.230407.019 release-keys]
Brave build: 1.53.83
Chromium: 114.0.5735.110 (Official Build) beta (64-bit)
Revision: 1c828682b85bbc70230a48f5e345489ec447373e-refs/branch-heads/5735_90@{#13}
```

Filed follow-up issue #30949

---------------------------

**STEPS:**
1. Launch Brave
2. Three-dot Menu > Settings
3. Scroll down and open `Appearance`
4. Find `Only open links in current tab group` > Verify

**ACTUAL RESULTS:**
- Verified that the title is `Only open links in current tab group`
- Verified that subtitle is `Automatically opens all links in the current tab group`
- Verified that the default setting is ON
- Verified that links are opened as expected depending on the setting ON or OFF

![Screen_14-00-45](https://github.com/brave/brave-browser/assets/128532965/d49584ae-b231-469d-8a7c-e5f6583e5cee)

https://github.com/brave/brave-browser/assets/128532965/540537cd-2ee3-4deb-850d-89e93c1a5797
