### ISSUE TITLE
Update sardine description

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#28665]

**Comment by kjozwiak** [comment]
The above requires `1.49.116` or higher for `1.49.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.49.118 Chromium: 111.0.5563.50 (Official Build) (64-bit)
-- | --
Revision | `39f3dfc5023fe60997adc4f6cf5439cfa3e6968a-refs/branch-heads/5563@{#903}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#17326](https://github.com/brave/brave-core/pull/17326)
- Verified Sardine description is now updated
![image](https://user-images.githubusercontent.com/17010094/222732807-8fec1861-c5ae-4ba1-a64c-a3cac366674a.png)
