### ISSUE TITLE
Desktop P3A menu metrics is being reported on Android

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#28660]
## Description 

The following desktop-only P3A menu metrics are being reported on Android:

- `Brave.Toolbar.FrequentMenuGroup`
- `Brave.Toolbar.MenuDismissRate`
- `Brave.Toolbar.MenuOpens`

## Version/Channel Information:

1.49.x and up

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Samsung Galaxy version 12` running `Bravemonoarm64.apk_1.50.84`

- Verified the description from the issue and ensured that the metrics mentioned below are **NOT** reported in Android:
         - `Brave.Toolbar.FrequentMenuGroup`  
         - `Brave.Toolbar.MenuDismissRate`
         - `Brave.Toolbar.MenuOpens`
