### ISSUE TITLE
Matic balance is not shown per accounts on PortfolioAsset view

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#28669]
## Description 

Matic balance is not shown per accounts on [PortfolioAsset](https://github.com/brave/brave-core/blob/master/components/brave_wallet_ui/components/desktop/views/portfolio/portfolio-asset.tsx) view

## Actual result:

[matic-balance.webm](https://user-images.githubusercontent.com/11755381/220624537-7d17c2c3-78e6-47be-9bc6-db4623dc820e.webm)

## Expected result:
Should show Matic balance

## Reproduces how often: 

easy

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel?  Y

**Comment by kjozwiak** [comment]
The above requires `1.49.116` or higher for `1.49.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.49.118 Chromium: 111.0.5563.50 (Official Build) (64-bit)
-- | --
Revision | `39f3dfc5023fe60997adc4f6cf5439cfa3e6968a-refs/branch-heads/5563@{#903}`
OS | Windows 11 Version 22H2 (Build 22621.755)

- Verified steps from [brave/brave-core#17353](https://github.com/brave/brave-core/pull/17353)
- Verified correct token details page is loaded when selecting asset from portfolio page

https://user-images.githubusercontent.com/17010094/222737141-4c58da15-ced9-492c-a76f-1c52a0f8e5ab.mp4
