### ISSUE TITLE
Coinbase video player: playback issues

### ISSUE THREAD

**Issue by lukemulks** [brave/brave-browser#2866]
## Description 

We've received reports that the video playback for the video player on the Coinbase website is not functioning as expected in Brave on desktop platforms. Reports included that functionality was not performing as expected with shields up and down. 

We have also received reports that the video playback in Brave on mobile platforms is functioning as expected. Have not tested this. 

I've tested on Windows 10 (64 bit), and confirm that I'm experiencing issues with playback with shields up, and with shields down. I'm observing different behavior with shields up and shields down, but am not able to observe successful playback in either mode. 

With shields up, when I click to play the video, I see a static black frame and play icon. 

With shields down, when I click to play the video, the static black frame displays, but the play icon spins as if the player is attempting to load the video. The player never actually plays the video. 

## Steps to Reproduce

   1. Navigate to: https://www.coinbase.com/earn/0x/lesson/1/
   2. Click on the video player to play the video. 

## Actual result:

The video will not play. I see a static black frame and play icon. 

## Expected result:
Video player should play the video. 

## Reproduces how often: 

Easily reproduced.

## Brave version (brave://version info)

v0.58.18 Chromium: 71.0.3578.98 (Official Build) (64-bit)
Revision 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS: Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
No
- Is the issue reproducible on the latest version of Chrome? 
No 
### Additional Information

Shield stats: 5 total items blocked. 

3p FP blocks: 
- https://fast.wistia.net/

3P Ads and Tracking blocked: 
- https://api.amplitude.com/
- https://distillery.wistia.com/x
- https://pipedream.wistia.com/mput?topic=metrics
- https://fg8vvsvnieiv3ej16jby.litix.io/

Playback behavior: Shield testing
- Shields up: No playback. Black frame with static play icon.
- Shields up, 3P FP disabled: Video does not play, but functionality matches observed behavior when all shields are down. Static black frame, infinite loop of play icon load animation. 
- Shields up, 3P FP disabled, All Cookies Allowed: Video does not play. Black frame, infinite loop of play icon load animation. 
- Shields up, 3P FP disabeld, All Cookies Allowed, HTTPS upgrade disabled: Video does not play. Black frame, infinite loop of play icon load animation. 
- Shields up, all settings disabled: Video does not play. Black frame, infinite loop of play icon load animation. 
- Shields down: Video does not play. Black frame, infinite loop of play icon load animation. 

Console Print - Shields Up - Before attempting to play the video
![brave-coinbase-player-issue-01082019-before-playback-shields-up](https://user-images.githubusercontent.com/8979240/50878724-de73f000-138c-11e9-8720-c0f4c185e7a2.JPG)

Console Print - Shields Up - After initiating playback
![brave-coinbase-player-issue-01082019-after-playback-shields-up](https://user-images.githubusercontent.com/8979240/50878773-1a0eba00-138d-11e9-8673-f922b11a9f37.JPG)

**Comment by mrzealot** [comment]
Works for me in Brave 0.58.21 (on Win10 64bit), both with shields up or down.

**Comment by bflora** [comment]
This works for me in the latest version of Brave on a Mac. I had to update to get it working but it works.
