### ISSUE TITLE
Vertical tabs: restore after crash doesn't show pinned tabs

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#28682]
## Description 
Noticed after restoring session after experiencing crash in https://github.com/brave/brave-browser/issues/28592

Basically, when a crash happens, Brave loses the session. You are prompted to restore it:
![image](https://user-images.githubusercontent.com/4733304/220708723-0dc28f70-503c-4321-b164-3a397e93a0ff.png)

Clicking restore will bring your window back, but it doesn't seem to restore pinned tabs. If you press Ctrl+Shift+T it'll restore the same window but WITH pinned tabs.

## Steps to Reproduce

   1. Have a window open with multiple tabs and have some pinned tabs
   2. Enable vertical tabs by flag and change view to be vertical tabs
   3. Crash the browser entirely (either with https://github.com/brave/brave-browser/issues/28592 or with one of the crash URLs like brave://inducebrowsercrashforrealz/)
   4. Launch Brave again
   5. Hit the orange "Restore" button

## Actual result:
Pinned tabs are not restored ☹️ 
![image](https://user-images.githubusercontent.com/4733304/220709398-80a69bb2-5a6c-41b9-9076-eea77eb169bf.png)

It's worth noting that @sangwoo108 discovered if you add another pinned tab to this window, it seems like all the pinned tabs come back. So they might be there but just not showing for some reason.

## Expected result:
Pinned tabs should be restored
![image](https://user-images.githubusercontent.com/4733304/220709502-1f00d43a-c8d2-44e1-894e-55c2acfe3bb9.png)

## Reproduces how often: 
100%

## Brave version (brave://version info)
1.50.53

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.50.91 Chromium: 111.0.5563.64 (Official Build) beta (x86_64)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | macOS Version 12.6.3 (Build 21G419)
```
