### ISSUE TITLE
Same strings are displayed twice in some UI in korean locale

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#2868]
## Description 

Same strings are displayed twice in some UI in korean locale and `<ex>` string is attached.
![2019-01-09 4 36 57](https://user-images.githubusercontent.com/6786187/50884004-0c107600-142d-11e9-90dd-f14f8d0fdedd.png)
![2019-01-09 4 37 31](https://user-images.githubusercontent.com/6786187/50884005-0ca90c80-142d-11e9-9a04-ad61f2bc7ace.png)

This isn't happened in en locale.

## Steps to Reproduce

   1. Visit chrome webstore
   2. Trying to install any extensions
   3. Check dialog displays extension name twice

## Actual result:

dialog displays extension name twice

## Expected result:
dialog title should not display extension name twice

## Reproduces how often: 

All

## Brave version (brave://version info)

0.58.18 Chromium: 71.0.3578.98

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? No

### Additional Information

cc: @rebron

**Comment by simonhong** [comment]
Should be updated in https://www.transifex.com/brave/brave

**Comment by simonhong** [comment]
Updated in transifex.

**Comment by srirambv** [comment]
@simonhong This is what I see on English as well. Similar to #2448
![screenshot from 2019-01-24 12-40-13](https://user-images.githubusercontent.com/17010094/51660957-6127bc80-1fd5-11e9-817f-98723773b0a4.png)
![image](https://user-images.githubusercontent.com/17010094/51661083-bc59af00-1fd5-11e9-8b22-de5cef2c739b.png)

The above screenshots are from 

Brave | 0.59.28 Chromium: 72.0.3626.64 (Official Build) beta(64-bit)
-- | --
Revision | eaa9668e80ce5405e7f1902579558ea725c06ca1-refs/branch-heads/3626@{#708}
OS | Linux

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.59.28 Chromium: 72.0.3626.64 (Official Build) beta (64 bit)
-- | --
Revision | eaa9668e80ce5405e7f1902579558ea725c06ca1-refs/branch-heads/3626@{#708}
OS | Linux

![image](https://user-images.githubusercontent.com/17010094/51662877-350f3a00-1fdb-11e9-8d2a-b3302dc5563a.png)

![image](https://user-images.githubusercontent.com/17010094/51662673-98e53300-1fda-11e9-84a4-cee09dc0d6cc.png)
