### ISSUE TITLE
Webview crashes when ad's enabled

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#2870]
## Description 

Webview crashes when ad's enabled

## Steps to Reproduce

   1. Install build `0.60.9`
   2. Enabled Ads from rewards page
   3. Visit a few sites and keep the tab open
   4. Ensure you click on ad notification to open up
   5. Site visited in step 3 encounters a webview crash

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/50909412-c914c980-1451-11e9-85e0-31bc668df530.png)

## Expected result:
There shouldn't be any webview crash 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.60.9 Chromium: 72.0.3626.28 (Official Build) dev (64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes on dev build
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
N/A
- Is the issue reproducible on the latest version of Chrome? 
N/A

### Additional Information

Issue reproduced by @GeetaSarvadnya 
cc: @bridiver @jsecretan @brave/legacy_qa

**Comment by bridiver** [comment]
not sure what you mean by a "webview" crash. We don't have webviews in brave-core. Did Brave crash? The "actual result" is a bit confusing to me as well because it shows `brave://crashes` as if that page was opened up by clicking on the ad. Are you trying to say that there was some kind of background crash that wasn't visible to you and just showed up in `brave://crashes`? If so, please upload and post the crash id

**Comment by bridiver** [comment]
oops, closed by accident ;)

**Comment by srirambv** [comment]
```
Crashes (15)
Local Crash ID 91c2edf1-ed07-4e5c-b835-c94e9e95185a
Crash report captured on Wednesday, January 9, 2019 at 9:38:47 PM was not uploaded

Send now

Uploaded Crash Report ID 6693df9bcf67625e (Local Crash ID: dd65bf34-9da8-4668-b761-e665ce95de3a)
Crash report captured on Wednesday, January 9, 2019 at 5:19:03 PM, uploaded on Wednesday, January 9, 2019 at 9:36:39 PM

Provide additional details

Uploaded Crash Report ID ee37118cf4abeffa (Local Crash ID: a24fe55b-3003-4e93-a20d-24ca15c87a96)
Crash report captured on Wednesday, January 9, 2019 at 4:37:38 PM, uploaded on Wednesday, January 9, 2019 at 4:37:39 PM

Provide additional details

Uploaded Crash Report ID 4879c13e70ec087f (Local Crash ID: 4faaffae-19b8-406f-a475-32e7445a81ec)
Crash report captured on Wednesday, January 9, 2019 at 2:18:39 PM, uploaded on Wednesday, January 9, 2019 at 9:36:48 PM

Provide additional details

Uploaded Crash Report ID b841687c1ecee056 (Local Crash ID: 57ea5383-ee64-47e6-8ba6-b0d6f3813613)
Crash report captured on Wednesday, January 9, 2019 at 2:17:37 PM, uploaded on Wednesday, January 9, 2019 at 2:18:49 PM

Provide additional details

Uploaded Crash Report ID 2a6e276fe5113158 (Local Crash ID: 111295fb-f8e3-4e70-9158-3ac0508fbb74)
Crash report captured on Wednesday, January 9, 2019 at 2:02:38 PM, uploaded on Wednesday, January 9, 2019 at 2:18:48 PM

Provide additional details

Uploaded Crash Report ID 6a74df4ade7c80ac (Local Crash ID: a93701c1-a835-4c41-bbf5-27d78ed34fd8)
Crash report captured on Wednesday, January 9, 2019 at 2:02:10 PM, uploaded on Wednesday, January 9, 2019 at 2:18:47 PM

Provide additional details

Uploaded Crash Report ID b7b11b99d5f3f66c (Local Crash ID: 620d78dc-b586-43d9-b0f7-27c391bec942)
Crash report captured on Wednesday, January 9, 2019 at 2:01:33 PM, uploaded on Wednesday, January 9, 2019 at 2:18:47 PM

Provide additional details

Uploaded Crash Report ID ca391d4fd7e6043c (Local Crash ID: b21e40ca-0e8c-40dd-ba58-eb06139b22ad)
Crash report captured on Wednesday, January 9, 2019 at 2:01:30 PM, uploaded on Wednesday, January 9, 2019 at 2:18:46 PM

Provide additional details

Uploaded Crash Report ID 101065a5e6b9aed0 (Local Crash ID: 61755736-9110-4a55-a0bd-781ae5536a16)
Crash report captured on Wednesday, January 9, 2019 at 2:01:26 PM, uploaded on Wednesday, January 9, 2019 at 2:18:45 PM

Provide additional details

Uploaded Crash Report ID 9a27575e5f4b3d1f (Local Crash ID: 6123bf13-1609-4e7e-831d-c6b6fe725ce8)
Crash report captured on Wednesday, January 9, 2019 at 2:01:24 PM, uploaded on Wednesday, January 9, 2019 at 2:18:44 PM

Provide additional details

Uploaded Crash Report ID d806374e7930424a (Local Crash ID: 50a6c9c4-a0a8-4fab-89b4-e7e870d1e569)
Crash report captured on Wednesday, January 9, 2019 at 2:01:22 PM, uploaded on Wednesday, January 9, 2019 at 2:18:43 PM

Provide additional details

Local Crash ID 256363d8-1b2b-4862-8df8-1cb42576d224
Crash report captured on Wednesday, January 9, 2019 at 2:01:21 PM was not uploaded

Send now

Uploaded Crash Report ID 9a0899d3176181b5 (Local Crash ID: 5506d783-f609-4783-9314-bfebb0ad9762)
Crash report captured on Wednesday, January 9, 2019 at 2:01:19 PM, uploaded on Wednesday, January 9, 2019 at 2:18:41 PM

Provide additional details

Uploaded Crash Report ID 21b6bfd238966f76 (Local Crash ID: 2a2f155e-5246-4e93-8c34-7e20f26d0c5b)
Crash report captured on Wednesday, January 9, 2019 at 2:01:18 PM, uploaded on Wednesday, January 9, 2019 at 2:01:18 PM
```

>not sure what you mean by a "webview" crash.

The blank screen with the frown face when you visit `brave://crash`. This happens on the sites that are visited which triggered the ads notification.

**Comment by bridiver** [comment]
got it, which crash id is it? The most recent one is not uploaded so there is no server crash id

**Comment by srirambv** [comment]
The most recent one wasn't for the webview. Not sure how it got captured. All the ones between ` 2:18:39 PM` and  ` 2:01:18 PM` are during the first attempt where tabs crashed

**Comment by LaurenWags** [comment]
Not seeing this while testing on macOS. I've viewed each ad I've received for the past hour or so, but no crashes experienced.


Brave | 0.60.9 Chromium: 72.0.3626.28 (Official Build) dev (64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Mac OS X

**Comment by bridiver** [comment]
@srirambv so which tab crashes? The tab that was open or the new tab that opens from clicking on the notification? These crashes are not all the same and don't look ads related, I think this might be an upstream issue that just happens to get triggered by creating a new tab this way

**Comment by bridiver** [comment]
Looks like the tab that was open since the crash reports are mostly `iab.com`. Does the new tab open correctly?

**Comment by srirambv** [comment]
@bridiver That profile where i had these crashes, new tab opened up blank each time. But i couldn't reproduce the same behaviour on a new profile. As for `iab.com` it had crashed both when the tab was in focus and in background. I had `forbes.com` as well which had crashed once. I can share the profile in a DM if you want to have a look

**Comment by jsecretan** [comment]
And I would say @srirambv that we should probably just ignore the case for iab.com for now since actually users won't use that to trigger.  Only the forbes case would be something an actual user would encounter.

**Comment by GeetaSarvadnya** [comment]
Able to reproduce the issue on 0.60.12

STR:

1. Launch Brave using ` BraveSoftware/Brave-Browser-Dev/Application/brave.exe --enable-logging --vmodule=brave_ads=3 --brave-ads-staging --brave-ads-debug --brave-ads-testing`
2. Enable Rewards throgh Hambuger menu/ welcome screen
3. Open `Thomascook.com`
4. Seeing crash on welcome screen, about brave and thomascook pages.
![image](https://user-images.githubusercontent.com/38657976/51117628-5ed69d00-1834-11e9-9122-92a924cc2b8d.png)
![image 14](https://user-images.githubusercontent.com/38657976/51117718-98a7a380-1834-11e9-8dd9-5017efbeba29.png)

**Comment by bridiver** [comment]
@GeetaSarvadnya can you upload the crash reports? That's the only way I can view them

**Comment by GeetaSarvadnya** [comment]
@bridiver Click on `Send now` and restart browser is not providing Uploaded crash report id's. Y'day also i have faced the same issue. Even today i am seeing the same issue. I have profile which has multiple crash issue on 0.60.12. Do let me know if you would for further investigation, i can provide. 
Currently, I am  checking with @aekeus regarding the Uploaded crash report id's not getting generated.

**Comment by bridiver** [comment]
@GeetaSarvadnya did you enable crash reporting? I saw in the screenshot that it was disabled, but there is a delay so usually clicking on the link and then restarting the browser will send it

**Comment by bridiver** [comment]
@GeetaSarvadnya also your STR doesn't seem to match your screenshot. You have more open tabs than the STR would create

**Comment by bridiver** [comment]
I'm not able to repro either of the STRs on master. Can someone else verify?

**Comment by tmancey** [comment]
@bridiver I cannot reproduce on master

**Comment by GeetaSarvadnya** [comment]
@bridiver I have enabled `Automatically send crash reports to Brave` option in Brave, even after that i was not seeing any uploaded crash report id's. Even @NejcZdovc saw this issue last week ( not getting Uploaded crash report id's). Let me test it again on latest dev build and see if i can reproduce the issue.

**Comment by bridiver** [comment]
@GeetaSarvadnya close and reopen Brave and it should send the reports

**Comment by tmancey** [comment]
@bridiver I believe this is related to https://github.com/brave/brave-browser/issues/2970 which after investigating as same steps but is a crash in Shields

**Comment by tmancey** [comment]
@srirambv Can you please retest and let us know if you can reproduce using latest master

**Comment by tmancey** [comment]
@srirambv If you could try on brave-core branch `fix-linking-error-rebase` that would be great

**Comment by srirambv** [comment]
Running from source causes the active page to have a webview crash irrespective of it being a brave page or a webpage.

```
Uploaded Crash Report ID 4d98141e33ca7287 (Local Context: 138cfdd9-0681-4f0c-84d9-2b93c2b59c32)
Crash report captured on Monday, March 4, 2019 at 8:20:57 AM, uploaded on Monday, March 4, 2019 at 8:20:58 AM

Provide additional details

Uploaded Crash Report ID a34ce7c3cc4db401 (Local Context: 27e8d5ee-d950-41be-87ec-d45b78bc440a)
Crash report captured on Monday, March 4, 2019 at 8:20:55 AM, uploaded on Monday, March 4, 2019 at 8:20:58 AM

Provide additional details

Uploaded Crash Report ID 2f3d111ce4bda0fa (Local Context: 54629ab3-6484-4ce6-8327-ffe6964a8055)
Crash report captured on Monday, March 4, 2019 at 8:20:54 AM, uploaded on Monday, March 4, 2019 at 8:20:57 AM

Provide additional details

Uploaded Crash Report ID bf28dcef08e0525f (Local Context: 405aec1f-b4f1-45bc-8036-f462672ab5f9)
Crash report captured on Monday, March 4, 2019 at 8:20:53 AM, uploaded on Monday, March 4, 2019 at 8:20:55 AM

Provide additional details

Uploaded Crash Report ID 98f9f30b6f210e12 (Local Context: 5d328e40-52e6-4c1c-9a32-de5fbd3a849e)
Crash report captured on Monday, March 4, 2019 at 8:20:52 AM, uploaded on Monday, March 4, 2019 at 8:20:56 AM

Provide additional details

Uploaded Crash Report ID ee8e068dac6bd1f8 (Local Context: 2919b1bc-4a2b-4265-9c41-6d7649b6a0c1)
Crash report captured on Monday, March 4, 2019 at 8:20:51 AM, uploaded on Monday, March 4, 2019 at 8:20:55 AM

Provide additional details

Uploaded Crash Report ID cc9cfa715f32dc91 (Local Context: c0f76a48-eb06-45f3-b291-d3798df6d1e4)
Crash report captured on Monday, March 4, 2019 at 8:20:50 AM, uploaded on Monday, March 4, 2019 at 8:21:00 AM

Provide additional details

Uploaded Crash Report ID 9434b79b5e6adfa7 (Local Context: e5d4796f-4689-4806-839b-519623c15b77)
Crash report captured on Monday, March 4, 2019 at 8:20:48 AM, uploaded on Monday, March 4, 2019 at 8:21:03 AM

Provide additional details
```

I am not seeing any ads on running ` npm run start -- Release --enable-logging=stderr --vmodule=brave_ads=3 --brave-ads-staging --brave-ads-debug --brave-ads-testing --brave-ads-locale=en_US`. I still see #2948 consistently as there are no files downloaded into `ads_service` folder which doesn't trigger any ads because the ads catalog is missing.

**Comment by tmancey** [comment]
@srirambv is retesting as Brave Core was on wrong branch

**Comment by srirambv** [comment]
Manually switched branch on `src/brave` to master as `npm run sync -- --all` on brave-browser didn't switch branch automatically. Ran the command `npm run start -- Release --enable-logging=stderr --vmodule=brave_ads=3 --brave-ads-staging --rewards=staging=true  --brave-ads-locale=en_US`, and there was no webview crash on the original page which triggered the ad. However found that https://github.com/brave/brave-browser/issues/2870#issuecomment-469251393 happens only when browser is launched via git bash window with just `npm run start -- Release --enable-logging=stderr --vmodule=brave_ads=3` but launching the same on Windows command prompt doesn't crash the active tab (#3566)

**Comment by tmancey** [comment]
@srirambv We found this issue was caused due to Git Bash . Can you please link this ticket to your new ticket and can we close this ticket as this is no longer an issue.

**Comment by srirambv** [comment]
Unable to reproduce the issue when launching via command prompt. Closing as fixed.
