### ISSUE TITLE
Color Issue when watching Youtube

### ISSUE THREAD

**Issue by FreedomSevenOG** [brave/brave-browser#28701]
Im getting issue with the color while watching youtube videos
See attached pic

![IMG-3508](https://user-images.githubusercontent.com/126120602/220777457-0beaf326-b8da-4210-abf3-dbbb2b9992fe.JPG)

When I tried to take a screen shot and send that
Anytime you hot any button on keyboard the color shift goes back to normal, but then discolors again a few seconds later
Thats why i took a pic with my phone
It only does this on Brave, Firefox is fine and Safari is fine

Im on a late Mac Mini 2014, Big Sur 11.7.2
The only time i see this issue is when watching youtube on Brave

**Comment by bsclifton** [comment]
@FreedomSevenOG can you please try setting this value? Visit brave://flags/#force-color-profile and then pick `sRGB`

Sometimes, something like Adobe Photoshop can override the system colors (Chromium would then use that profile too).

**Comment by FreedomSevenOG** [comment]
Thanks for that
sRGB didnt work, but i changed it to ITU 2020 and now its fine

**Comment by bsclifton** [comment]
@FreedomSevenOG awesome! Thanks for giving that a shot! 😄 

I'll go ahead and close this issue out. Do you have any photo or video editing software installed on your machine?
