### ISSUE TITLE
Inline tipping buttons aren't shown when a new profile is created.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#28702]
STR:

1. Start with a fresh Brave profile
2. Navigate to reddit.com and verify that you see the inline tipping buttons
3. ☰ -> Create a new profile
4. Name the profile (e.g. "Profile 2")
5. In the new profile window navigate to reddit.com and look for the inline tipping buttons
Expected result:
The tipping buttons are shown
Actual result:
The tipping buttons are missing

6. Close all browser windows
7. Start browser again and pick the original profile in the picker ("Profile 1")
8. Navigate to reddit.com and look for inline tipping buttons
Expected result:
The tipping buttons are shown
Actual result:
The tipping buttons are missing

From then on the tipping buttons won't be shown in either profile.

**Comment by mkarolin** [comment]
cc: @emerick

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.51.80 Chromium: 112.0.5615.49 (Official Build) beta (x86_64)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | macOS Version 12.6.4 (Build 21G526)
```
