### ISSUE TITLE
Do not open brave://welcome in incognito

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#28704]
same as brave://settings/importData

**Comment by stephendonner** [comment]
@spylogsster how about in `Guest window`?  Currently, that works, in 

Brave | 1.50.86 Chromium: 111.0.5563.64 (Official Build) beta (x86_64)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | macOS Version 11.7.4 (Build 20G1120)

**Comment by spylogsster** [comment]
> @spylogsster how about in `Guest window`? Currently, that works, in
> 
> Brave	1.50.86 Chromium: 111.0.5563.64 (Official Build) beta (x86_64)
> Revision	c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
> OS	macOS Version 11.7.4 (Build 20G1120)
> <img alt="Screen Shot 2023-03-12 at 5 41 49 PM" width="2000" src="https://user-images.githubusercontent.com/387249/224584675-5c8b7314-0c42-4c49-bdb1-2fab98aaad22.png">

thanks for checking, created https://github.com/brave/brave-browser/issues/29012

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.50.90 Chromium: 111.0.5563.64 (Official Build) beta (x86_64)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | macOS Version 11.7.4 (Build 20G1120)

### Steps:
1. installed `1.50.90`
2. launched Brave
3. clicked on `New Private Window`
4. tried to load `brave://welcome`
5. confirmed it focused the already-open `brave://welcome` tab
6. clicked on `New Private Window with Tor`
7. tried to load `brave://welcome`
8. confirmed it focused the already-open `brave://welcome` tab



![28704](https://user-images.githubusercontent.com/387249/224861978-1e991b6a-eebd-4e18-936b-f5d5cd8c8069.gif)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.50.91 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | Windows 11 Version 22H2 (Build 22621.1265)
```

Steps:

1. installed `1.50.91`
2. launched Brave
3. clicked on `New Private Window`
4. tried to load `brave://welcome`
5. confirmed it focused the already-open `brave://welcome` tab
6. clicked on `New Private Window with Tor`
7. tried to load `brave://welcome`
8. confirmed it focused the already-open brave://welcome tab



https://user-images.githubusercontent.com/98358127/225131962-dd0881ac-324a-4d6a-9c98-4bcf14819b58.mp4
