### ISSUE TITLE
Add `Mute Tab(ctrl+m)` entry to Tab menu in menu bar

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#28705]
It has same behavior with `Mute Tab` in tab's context menu

STR
1. Launch Brave and Playing any clips in youtube
2. Click `Mute Tab` menu via menu bar instead of using tab's context menu
3. Check tab is muted

When unmuted:
<img width="222" alt="Screenshot 2023-02-27 at 6 14 56 PM" src="https://user-images.githubusercontent.com/6786187/221522555-abfec16d-6a6d-47f4-b484-41cd04fe6bd2.png">
When muted
<img width="232" alt="Screenshot 2023-02-27 at 6 15 08 PM" src="https://user-images.githubusercontent.com/6786187/221522586-c2150a36-83f2-45a7-b347-367fca338621.png">

**Comment by LaurenWags** [comment]
Verified using

```
Brave | 1.50.91 Chromium: 111.0.5563.64 (Official Build) beta (x86_64)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | macOS Version 12.6.3 (Build 21G419)
```

Verified STR from description.
Confirmed "Tab" option from macOS application menu had the "Mute Tab" option as per the screenshots in the description.
Confirmed "Mute Tab" worked as expected from the macOS application menu.
Spot checked "Mute Tab" continued to work from tab context menu also.

Example | Example
---- | ----
<img width="1514" alt="Screen Shot 2023-03-14 at 11 44 00 AM" src="https://user-images.githubusercontent.com/28145373/225057910-61c0dfa7-87e1-4966-9224-97a722284cd5.png"> | <img width="848" alt="Screen Shot 2023-03-14 at 11 44 23 AM" src="https://user-images.githubusercontent.com/28145373/225057916-080ae70c-2c14-42fa-aee3-54d0c6fb729e.png">

**Comment by LaurenWags** [comment]
cc @stephendonner for a second verification on macOS

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.50.91 Chromium: 111.0.5563.64 (Official Build) beta (x86_64)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | macOS Version 11.7.4 (Build 20G1120)

### Steps:
1. installed `1.50.91`
2. launched Brave
3. opened `https://www.youtube.com/watch?v=CdV9l8JAaA0&t=194s`
4. clicked `Play`


#### Confirmed:
* context-menu item `Mute Tab`/`Unmute Tab` state changes affect, and are reflected in, the application's top-level `Tab` menu
* vice-versa, for the above
* muted/unmuted state was correct, in various ad-hoc/focused-testing scenarios

example | example | example
---------|----------|---------
<img width="1920" alt="Screen Shot 2023-03-14 at 1 59 53 PM" src="https://user-images.githubusercontent.com/387249/225135432-d3172da8-f942-46ef-9b72-6ef4e24a6f58.png"> | <img width="1919" alt="Screen Shot 2023-03-14 at 2 00 13 PM" src="https://user-images.githubusercontent.com/387249/225135438-41a86dd5-5d09-4154-a752-c4eee140c429.png"> | <img width="1920" alt="Screen Shot 2023-03-14 at 2 01 30 PM" src="https://user-images.githubusercontent.com/387249/225135440-a0a5ab1c-0ac9-4d38-9770-7117f340c835.png">
