### ISSUE TITLE
Asset list sort order is not maintained after price update

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#28706]
## Description 
On portfolio, Asset list sort order is not maintained after price update

## Steps to Reproduce and Actual result

[desktop.webm](https://user-images.githubusercontent.com/11755381/220867779-5ba9468c-c831-4e8b-8034-4704d2f6e411.webm)

## Expected result:
Asset list order should be maintained

## Reproduces how often: 

Easily

## Version/Channel Information:

- Can you reproduce this issue with the current release? Y
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? Y

**Comment by Douglashdaniel** [comment]
The selection for `Balance high/low` and `Balance low/high` is actually being maintained, the reason for the shifting in order is because we are not able to calculate that sort order until prices for each token are returned from the backend.

**Comment by Douglashdaniel** [comment]
Local storage pref for these filters our currently in `nightly` https://github.com/brave/brave-core/pull/16959
