### ISSUE TITLE
Fix detection of Google Chrome Beta/Dev as default browsers

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#28717]
## Test plan 
See https://github.com/brave/brave-core/pull/17414

## Description
Google Chrome Dev and Google Chrome Beta have traslated default browser name, need to read original google translations and compare default browser name it with them

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.50.90 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | Windows 11 Version 22H2 (Build 22621.1265)
```
Pre-requisite: Download `Chrome Beta` and `Chrome Dev` browsers and have data for Bookmarks, History, Passwords and Extensions
<details>

`Chrome Beta`
Person 1:  bookmarks, history and passwords
Person 2:  bookmarks, history and extensions
Person 3:  bookmarks

Person 1|Person 2|Person 3
----- | ----- |-----
<image width="850" alt="image" src="https://user-images.githubusercontent.com/98358127/224786361-806f298f-1c22-4af9-bdb2-5a9e419b3f3c.png">|<image width="550" alt="image" src="https://user-images.githubusercontent.com/98358127/224787126-400b8339-bc1a-4b75-bdb7-da20558aa0e4.png">|<img width="765" alt="image" src="https://user-images.githubusercontent.com/98358127/224845192-6e35dd81-70d9-4c2c-bb29-e5915caed19d.png">

`Chrome Dev`
Person 1: bookmarks, history, extensions and passwords
Person 2: bookmarks and history
ex|ex
----|---
<image width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/224817257-e3e9491d-a6d1-44b3-b4c2-ec65e28cea61.png">|<img width="472" alt="image" src="https://user-images.githubusercontent.com/98358127/224818195-9c1d73ca-d468-4089-a3dc-23548b6132a3.png">
</details>


#### Case 1: Verify `Chrome Beta and Chrome Dev` browsers are detected in `brave://welcome` page - `PASSED`
<details>

1. Install `1.50.99`
2. launch Brave
3. click `Set Brave as default browser`

#### Confirmed `Google Chrome Beta` and `Google Chrome Dev` browsers are detected and are icons are shown in the `brave://welcome` - first screen

step 3|result
-----|-----
<img width="462" alt="image" src="https://user-images.githubusercontent.com/98358127/224820703-5defd413-e7c0-4b09-98b8-bdf889972952.png">|<img width="461" alt="image" src="https://user-images.githubusercontent.com/98358127/224820747-7eaf09dd-a295-4392-84c8-f0dbd5e61c04.png">
</details>

`Google Chrome Beta`

#### Case 2: Single profile - Complete Import from `brave://welcome` - Import Settings page - `PASSED`
<details>

1. continue from Case 1
     - `Google Chrome Beta` is shown in `brave://welcome` page - `import settings` screen 
2. select `Google Chrome Beta` and click `Import` button   
3. select `Google Chrome Beta - Person 1` in the `Select profile to import` screen
4. clicked `Import profiles` 
5. verified `Setup complete` screen is displayed as expected 
6. verified  `Help improve Brave` screen is displayed as expected
7. verified new-tab page is shown as expected

#### Confirmed Bookmarks imported from `Chrome Beta` are shown in `brave://bookmarks` and bookmarks bar 
#### Confirmed History imported from `Chrome Beta` is shown in `brave://history`
#### Confirmed Extensions imported from `Chrome Beta` are shown in `brave://extensions`

step 1-2|step 3-4|step 5|step 6|step 7|result|result|result
-----|----|-----|------|----|----|-----|-----
<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/224821564-4bc45045-c2ab-4639-a4ef-9eae018d24a1.png">|<img width="460" alt="image" src="https://user-images.githubusercontent.com/98358127/224824039-0ecc87cf-574e-43b3-8120-9e71a21ef9f5.png">|<img width="460" alt="image" src="https://user-images.githubusercontent.com/98358127/224824586-8e5046a2-d020-4c04-b785-9fc62744df53.png">|<img width="459" alt="image" src="https://user-images.githubusercontent.com/98358127/224824608-62f59845-fa4d-478f-bbe0-eaa78afb7f1b.png">|<img width="489" alt="image" src="https://user-images.githubusercontent.com/98358127/224827379-8ff1e2fb-c50c-445b-bd60-ca7ce9e91cdf.png">|<img width="498" alt="image" src="https://user-images.githubusercontent.com/98358127/224824685-34e2e2a8-ad33-4a80-8337-04bafebe2bdb.png">|<img width="494" alt="image" src="https://user-images.githubusercontent.com/98358127/224824768-759dc01f-97f6-4d04-950c-32e5dbb539ec.png">|<img width="461" alt="image" src="https://user-images.githubusercontent.com/98358127/224824882-066341fa-3a81-4a90-ac3e-09f8947140c9.png">
</details>

#### Case 3: Multiple profiles - Complete Import from `brave://welcome` - Import Settings page - `FAILED`
<details>

1. new profile 
2. launch Brave
3. click `Set Brave as default browser` on `brave://welcome` page
4. select `Chrome Beta` in `import settings` screen 
5. click `Import` button   
6. click `Select All` to select all 3 profiles 
7. click `Import profiles`
8. click `Finish` 
9. click on Profile icon in the new-tab page next to hamburger menu
    - Confirmed when clicked on Profile 1 icon, all 3 imported Chrome profiles are shown - `Failed`
    - Confirmed three newly created profiles are shown in the profile manager - Failed
    - Confirmed `bookmarks`, `history`, and `passwords` are imported into `Chrome Person 1` profile - `Failed`
    - Confirmed `bookmarks` and `history` & extensions are shown in `Chrome Person 2` profile - `Failed`
    - Confirmed `bookmarks` are shown in `Chrome Person 3` profile - `Failed`

step 4-5 | step 6-7 | step 8 | step 9 | profile manager | ex| ex
----- | ----- | ----- | ----- | ----- | ----- | ----- 
<img width="363" alt="image" src="https://user-images.githubusercontent.com/98358127/224821564-4bc45045-c2ab-4639-a4ef-9eae018d24a1.png">|<img width="365" alt="image" src="https://user-images.githubusercontent.com/98358127/224844884-0f6baa27-18f1-4574-a3b8-0997b63fc34d.png">|<img width="359" alt="image" src="https://user-images.githubusercontent.com/98358127/224844930-38b41bc5-72ca-4986-8bf7-fc22cfb03918.png">|<img width="354" alt="image" src="https://user-images.githubusercontent.com/98358127/224845049-b63cfbe7-87df-4de1-b48d-0116c189aa49.png">|<img width="509" alt="image" src="https://user-images.githubusercontent.com/98358127/224845012-8058f5b1-48e0-488d-aff6-f3476e679666.png">|<img width="956" alt="image" src="https://user-images.githubusercontent.com/98358127/224847296-0b2ef8c1-4d65-4602-b05b-2a5c632b15c8.png">|<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/224847447-e7310698-ce65-482a-baaf-152744877ed3.png">|<img width="951" alt="image" src="https://user-images.githubusercontent.com/98358127/224847538-e644c235-8d23-4036-9fe0-0e4fa03b353c.png">

</details>

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.50.92 Chromium: 111.0.5563.64 (Official Build) beta (x86_64)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | macOS Version 11.7.4 (Build 20G1120)

### Case 1: Set `Google Chrome Beta` as `default` browser


### Case 2: Set `Google Chrome Dev` as `default` browser

**Comment by stephendonner** [comment]
Spun off https://github.com/brave/brave-browser/issues/29095 while testing on `macOS` 👍

**Comment by stephendonner** [comment]
### Status wrapup (wrt `macOS`):

1. 1st attempt in https://github.com/brave/brave-browser/issues/26378
2. 2nd attempt in https://github.com/brave/brave-browser/issues/28573
3. 3rd attempt was in https://github.com/brave/brave-browser/issues/29275
4. final solution landed in https://github.com/brave/brave-browser/issues/29095

The latter two are in `1.51.x` and will ride the trains 👍
