### ISSUE TITLE
Console doesn't capture any log for ads

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#2871]
## Description 
Console doesn't capture any log for ads

## Steps to Reproduce

   1. Clean profile 0.60.9
   2. Launch brave via console 
   3. Enable Ads switch from rewards page 
   5. Check ads notifications (Ads notifications are received)
   

## Actual result:
Console doesn't capture any log for ads

## Expected result:
Console should capture all logs

## Reproduces how often: 
Always

## Brave version (brave://version info)

Brave | 0.60.9 Chromium: 72.0.3626.28 (Official Build) dev (64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Windows

### Reproducible on current release:na
- Does it reproduce on brave-browser dev/beta builds? yes on Dev build

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? na
- Is the issue reproducible on the latest version of Chrome? na

### Additional Information

@brave/legacy_qa

**Comment by kjozwiak** [comment]
@GeetaSarvadnya can you please include the exact commands/variables that you're launching Brave with? This way, whoever takes a look at this will have more details.

**Comment by tmancey** [comment]
@GeetaSarvadnya is this still an issue as I believe this was related to not use the command-line arg for diagnostic logging?

**Comment by GeetaSarvadnya** [comment]
@tmancey If i use --enable-logging=stderr, I am getting error logs on console. Now i am not getting ads notifications, tomorrow i will check again and post console error logs.

**Comment by btlechowski** [comment]
I ad notification logs on Windows 7 x64 and Windows 10 x64. My command line arg is:
`./brave.exe --enable-logging=stderr --vmodule=brave_ads=3 --brave-ads-staging --brave-ads-debug --brave-ads-testing
`

**Comment by GeetaSarvadnya** [comment]
@tmancey I am not getting adds notification on Windows 10 x64 when i use below command-line arg:

`BraveSoftware/Brave-Browser-Dev/Application/brave.exe --enable-logging=stderr --vmodule=brave_ads=3 --brave-ads-staging --brave-ads-debug --brave-ads-testing`
Console Logs:
![image](https://user-images.githubusercontent.com/38657976/51180618-c2bd9c00-18ee-11e9-9b70-ebb73fd96932.png)
Ads_service folder has only one file `client.jason`
![image](https://user-images.githubusercontent.com/38657976/51180704-13cd9000-18ef-11e9-95d0-7c63aa508c9d.png)
Build : `0.60.12`

I am getting adds notification on Windows 10 x64 when i use below command-line arg:

Console log:
![image](https://user-images.githubusercontent.com/38657976/51181505-57c19480-18f1-11e9-9a3b-332394d2a457.png)
Ads_service folder has all the files:
![image](https://user-images.githubusercontent.com/38657976/51181573-80e22500-18f1-11e9-9dae-edeeb76e011d.png)
Build: `0.60.12`

Ads event logs are getting captured in `chrome_debud.log`

![image](https://user-images.githubusercontent.com/38657976/51181731-f1894180-18f1-11e9-95b4-c4db27781026.png)

**Comment by GeetaSarvadnya** [comment]
@kjozwiak Issue logged earlier was generic for all the platform. Hence i have not added command. 
Now, i have provide command along with screen shots for the issue which i am seeing on Windows

https://github.com/brave/brave-browser/issues/2871#issuecomment-454380849

**Comment by btlechowski** [comment]
Re https://github.com/brave/brave-browser/issues/2871#issuecomment-454184234 . I did some investigating and it seems that I also lack some of the ads logs.
ads logs that I get in terminal are from: `ads_service_impl.cc`
ads logs that I do NOT get in terminal are from: `ads_impl.cc`

Interestingly 
`ads_service_impl.cc` is part of `brave-core` and can be found in `/components/brave_ads/browser/ads_service_impl.cc`

`ads_impl.cc` is part of `bat-native-ads` and can be found in `/src/ads_impl.cc`

**Comment by tmancey** [comment]
@btlechowski see https://www.chromium.org/for-testers/enable-logging as stderr cannot be redirected to the console for Windows, for logging you should use the following command-line arguments: `--enable-logging=stderr --log-level=2`

**Comment by GeetaSarvadnya** [comment]
As discussed with @tmancey over the zoom call, on Windows Chromium does not log to stderr.  Inorder to check ads service logs we need to verify `chrome_debug.log` file. 

Hence closing the issue as it works as expected.
