### ISSUE TITLE
Implement 'Send like experience' on Swaps

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#28720]
## Description 

Currently on swaps, you have to select different networks and accounts and then you make the swap. 

If we followed the send like experience, users would be able to see all the assets associated with their wallet on the 'swap from' list. We think this would be a better experience for the user if they could see all the assets they could swap on the dropdown.

Attached is how the send screen looks and the current swap screen. 

## Steps to Reproduce

Currently on Swaps
   1. you have to select your network 
   2. then select your account
   3. then you select the asset from the dropdown

https://user-images.githubusercontent.com/12224304/220963522-4cb1d29d-c3a0-4ec8-bf3c-891bc459864a.mov

## Expected result:
1. you select the 'swap from' list on swaps and you see all the assets that you are currently able to swap.

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by HEagle18** [comment]
cc @Douglashdaniel @onyb @jamesmudgett

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.63.155 Chromium: 122.0.6261.29 (Official Build) (64-bit)
-- | --
Revision | b2be2c6f5b7340629f672ce706f5bfd62b113f82
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from [brave/brave-core#21274](https://github.com/brave/brave-core/pull/21274)
- Verified `Send` and `Swap` uses the new composed UI
- Verified `Send` and `Swap` works as expected
- Verified the new UI on both Wallet page and panel

https://github.com/brave/brave-browser/assets/17010094/3346407d-235c-4bdf-a430-f808d17f8f2e

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.63.157 x64 build
- Verified steps from [brave/brave-core#21274](https://github.com/brave/brave-core/pull/21274)
- Verified `Send` and `Swap` uses the new composed UI
- Verified `Send` and `Swap` works as expected
- Verified the new UI on both Wallet page and panel

https://github.com/brave/brave-browser/assets/17010094/c6ee3b64-da8d-4a92-a701-7e835d6dcc6e
