### ISSUE TITLE
[ads] Implement `AdsObserver`

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#28726]
- [x] OnBraveRewardsDidChange
- [x] OnBrowserUpgradeRequiredToServeAds
- [x] OnIneligibleRewardsWalletToServeAds
- [x] OnRemindUser

**Comment by btlechowski** [comment]
Verified with

Brave | 1.62.107 Chromium: 120.0.6099.115 (Official Build) beta (64-bit)
-- | --
Revision | 67a3b21572338a0660bb25a5855da0f1e9372a39
OS | Linux

#### Reminders

Verified ad reminder is shown
![image](https://github.com/brave/brave-browser/assets/34715963/07b98e45-722d-40e8-a38c-719a4bbb7c34)|![image](https://github.com/brave/brave-browser/assets/34715963/81e292e6-c4e6-4683-b2cf-f67ef6c93ebe)
--|--

#### brave://rewards

Verified brave://rewards ads shown are automatically updated

![image](https://github.com/brave/brave-browser/assets/34715963/a8575683-4fc1-4d63-9eea-69802890e230)|![image](https://github.com/brave/brave-browser/assets/34715963/763f9e5c-32fe-4bb5-a76f-6121ac52cb0a)
--|--

#### upgrade browser required (426)

Browser upgrade required did not trigger `Upgrade required` modal. Logged:
