### ISSUE TITLE
Add dark mode capabilities to other areas of Wallet

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#28723]
## Description 

Right now, you can only select dark mode in the swaps section. We want to be able to do that throughout the wallet. 

@Douglashdaniel has thoughts on how this can be implemented. Needs design help as well. 

## Steps to Reproduce

   1. 
   2. 
   3. 

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by Douglashdaniel** [comment]
Theme toggle was removed from the `Swap` page when it was moved directly to core. Closing as `invalid`
