### ISSUE TITLE
Ads only display on main screen even if using Brave on external monitor

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#2872]
## Description 
If you are using Brave on an external monitor, the Ad notification only displays on your main (laptop) screen, so it is easily missed.

## Steps to Reproduce

   1. Have an external monitor set up.
   2. Launch 0.60.9 to use Ads.
   3. Enable Ads if not already enabled.
   4. Browse for awhile until you get an Ad

## Actual result:
Ad notification is displayed on laptop screen but you are working on external monitor. Some other apps also behave this way (Slack for example).

## Expected result:
Would be nice if Ad notification could be displayed on the monitor you are working on.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.60.9 Chromium: 72.0.3626.28 (Official Build) dev (64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Dev

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
cc @jsecretan

**Comment by tmancey** [comment]
@LaurenWags This is a limitation of macOS whereby notifications appear on the same display as the menu bar

**Comment by srirambv** [comment]
This is a limitation on Windows as well. Notifications always shows up on main screen irrespective of where the app is (primary display or secondary display)
