### ISSUE TITLE
Add clickable centered block to support new tab page sponsored images

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#28736]
## Description 

New tab page sponsored images contain visual interest that's centered on the user's screen. Oftentimes users will want to clickthrough on that item instead of clicking through on the bottom left call out.

We need a clickable centered block to allow users to clickthrough on sponsored images. The centered block will be removed altogether when the viewport is minimized. 

Clicking through the center block should change the mouseover/hover icon to show that the center is clickable. Further, the clickable space should maintain ample space for the widgets to reduce any mis-clicks.

## Steps for new feature:

   1. Visit a new tab page sponsored image by creating a new tab page.
   2. Hover onto the center of the sponsored image, between widgets and above Brave News.
   3. Click on image and it should direct you to the proper destination url (similar to clicking the bottom left call out).

## Expected result:
<img width="1410" alt="Screenshot 2023-02-22 at 3 19 10 PM" src="https://user-images.githubusercontent.com/5951041/221062905-4d14638f-db0f-430f-9fc0-b60b861a10a5.png">

## Reproduces how often: 

n/a

## Brave version (brave://version info)

Targeting 1.49.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.50.91 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | Windows 11 Version 22H2 (Build 22621.1265)
```
 
1. Install 1.50.91
2. launch Brave
3. open a new-tab page
4. added few sites to NTP
5. visit a new tab page to load a sponsored image 
6. hover onto the center of the sponsored image, between widgets and above Brave News.
7. click on image and it should direct you to the proper destination url (similar to clicking the bottom left call out)
8. adds a click box to new tab page sponsored images and it slots in between the NTP grid and the widgets on the right
9. If widgets are showing and the screen is in one column mode, we don't add the clickbox 
10. If widgets are not showing, the clickbox is shown
11. click on the bottom left click box to confirm it's working as expected
12. clickable centered block is not shown on new tab pages

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.50.92 Chromium: 111.0.5563.64 (Official Build) beta (x86_64)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | macOS Version 11.7.4 (Build 20G1120)

### Case 1: New install
<details>

Install 1.50.92
launched Brave
opened a new-tab page
added few top sites to NTP
visited a new tab page to load a sponsored image
click box/clickable area is shown to new tab page sponsored images in between the NTP grid and the widgets on the right
hovered and clicked onto the center of the sponsored image, between top sites and widgets and above Brave News.
it redirected to the proper destination url (similar to clicking the bottom left call out) - https://brave.com/brave-ads/?source=sponsoredimage20230315
confirmed destination URL is shown bottom left - https://brave.com/brave-ads/?source=sponsoredimage20230315
clicked anywhere in the clickable area to redirect to destination URL - https://brave.com/brave-ads/?source=sponsoredimage20230315
If widgets are showing and the screen is in one column mode, we don't add the clickbox
If widgets are not visible, the clickbox/clickable area is shown
clicked on the bottom left link or image to confirm it's working as expected
clickable centered block is not shown on non NTPSI pages

</details>

### Case 2: Upgrade
<details>

Installed 1.49.120
launch Brave
open a NTP SI page
added few top sites
close the browser
rename the profile to Brave-Beta
install 1.50.92
relaunch Brave

</details>

**Comment by kjozwiak** [comment]
Removing `QA Pass` labels as this will need to get re-checked via `1.49.x`.

**Comment by kjozwiak** [comment]
The above requires `1.49.127` or higher for `1.49.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.49.128 Chromium: 111.0.5563.110 (Official Build) (x86_64)
-- | --
Revision | 3da375c9e9e5ad9b556af5df708a6e6c01d8cfb1-refs/branch-heads/5563@{#1202}
OS | macOS Version 12.6.3 (Build 21G419)
```

**Comment by stephendonner** [comment]
## Verification `PASSED` using 

Brave | 1.49.128 Chromium: 111.0.5563.110 (Official Build) (64-bit)
-- | --
Revision | 3da375c9e9e5ad9b556af5df708a6e6c01d8cfb1-refs/branch-heads/5563@{#1202}
OS | Windows 10 Version 22H2 (Build 19045.2728)


### Case 1: New install - `PASSED`
<details>

1. installed `1.49.128`
2. launched Brave
3. opened a new-tab page
4. added few top sites to NTP
5. visited a new tab page to load a sponsored image
6. click box/clickable area is shown to new tab page sponsored images in between the NTP grid and the widgets on the right
7. hovered and clicked onto the center of the sponsored image, between top sites and widgets and above Brave News.
8. it redirected to the proper destination url (similar to clicking the bottom left call out) - `https://search.brave.com/?brave-creative-id=ee855d01-3203-4a07-963c-5b59fd2b63be&source=sponsoredimage20230317`
9. confirmed destination URL is shown bottom left - `https://search.brave.com/?brave-creative-id=ee855d01-3203-4a07-963c-5b59fd2b63be&source=sponsoredimage20230317`
10. clicked anywhere in the clickable area to redirect to destination URL - `https://search.brave.com/?brave-creative-id=ee855d01-3203-4a07-963c-5b59fd2b63be&source=sponsoredimage20230317`
11. If widgets are showing and the screen is in one column mode, we don't add the clickbox
12. If widgets are not visible, the clickbox/clickable area is shown
13. clicked on the bottom left link or image to confirm it's working as expected
14. clickable centered block is not shown on non NTPSI pages

`default spaces` | `no widgets` | `no topsites` | `no widgets nor topsites`
-----------------|---------------|--------------|-------------------------
![image](https://user-images.githubusercontent.com/387249/227018871-414ca617-e2fc-4dc8-9279-07c7f43ef789.png) |![image](https://user-images.githubusercontent.com/387249/227019636-f790988e-6128-4b66-a1db-805a804b701f.png) | ![image](https://user-images.githubusercontent.com/387249/227019221-189444c2-f618-4734-9c19-766b662f363a.png) | ![image](https://user-images.githubusercontent.com/387249/227019907-4e736c9b-8257-4e7f-9494-ad9df2ff1318.png)







</details>

### Case 2: Upgrade - `PENDING`
<details>

1. installed 1.49.120
2. launched Brave
3. opened a NTP SI page
4. added a few top sites
5. closed the browser
6. renamed the profile to `Brave-Beta`
7. installed `1.49.128`
8. relaunched Brave

### Confirmed functionality worked as expected as in `Case 1`

.

</details>
