### ISSUE TITLE
Graph is not loaded with all assets are visible

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#28748]
## Description 
Graph is empty when all found assets are visible/discovered.

## Steps to reproduce 
Note: Can be reproduced with same list of assets on other platforms
   1. Make sure to use nightly for asset discovery
   2. Restore wallet and note empty graph

## Actual result 
Graph is empty

[discovery-asset-grpah-issue.webm](https://user-images.githubusercontent.com/11755381/221208084-0d579225-b7c9-4143-b076-a547ba0620e2.webm)

## Expected result
Graph should be shown

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version?
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?Y

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.51.97 x64 Beta build
- Verified steps form [brave/brave-core#17641](https://github.com/brave/brave-core/pull/17641) and issue description
- Verified graph is loaded when network is changed

https://user-images.githubusercontent.com/17010094/234471095-80cfdcb8-201d-4d7f-bbb6-d2881667875c.mp4
