### ISSUE TITLE
Rewards Panel height should be dynamic based on content, not fixed

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#2874]
Currently a minimum height is enforced on the Rewards panel, leading to large white space gaps at the bottom of the Rewards summary view and some publisher views with little information.

The height should become un-fixed with a standard bottom padding under whatever the content is.

**Comment by NejcZdovc** [comment]
+1 from https://github.com/brave/brave-browser/issues/3056

**Comment by NejcZdovc** [comment]
+1 from https://github.com/brave/brave-browser/issues/3332

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.64.60 Chromium: 74.0.3729.91 (Official Build) beta (64-bit)
-- | --
Revision | 03844ed83e02b8add3f4b9cb859a7108d55b2e4d-refs/branch-heads/3729@{#860}
OS | Windows 10 OS Build 17134.523

Used test plan https://github.com/brave/brave-core/pull/1895
