### ISSUE TITLE
Auto-discovery of assets resets the visible assets pref.

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#28749]
Now that we have full asset auto-discovery of L2s setting an asset to hidden will be overwritten next time AD returns results. I'm setting USDC on Solana to hidden but seeing it return in my portfolio.

**Comment by diracdeltas** [comment]
bumping to p2 due to the privacy concern

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.53.102 Chromium: 114.0.5735.133 (Official Build) (64-bit)
-- | --
Revision | `fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}`
OS | Linux

- Verified steps from issue description
- Verified disabling a token from visible list and importing a new account to trigger auto-discover doesn't add the disabled token to visible list

---------------------

**Verification passed on**

Brave | 1.53.102 Chromium: 114.0.5735.133 (Official Build) (64-bit)
-- | --
Revision | `fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}`
OS | Windows 11 Version 22H2 (Build 22621.1848)

- Verified steps from issue description
- Verified disabling a token from visible list and importing a new account to trigger auto-discover doesn't add the disabled token to visible list

---------------------

**Verification passed on**

Brave | 1.53.102 Chromium: 114.0.5735.133 (Official Build) (64-bit)
-- | --
Revision | `fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from issue description
- Verified disabling a token from visible list and importing a new account to trigger auto-discover doesn't add the disabled token to visible list
