### ISSUE TITLE
Fiat value showing 0 when having the same tokens on different chains

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#28753]
## Description 

If you add a multiple of the same tokens on different chains and one of them doesn't have a balance, the fiat value will show 0.00 for the one that does have a balance.

## Steps to Reproduce

   1. Add a token that has a balance on a L2 chain
   2. Now add that same token on a `L1` chain without a balance
   3. The L2 fiat balance will show 0.00

## Actual result:

https://user-images.githubusercontent.com/40611140/221291160-e9d2425d-5319-46f3-959c-e3ccacc0bbc5.mov

## Expected result:

Should show the fiat balance.

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.50.91 Chromium: 111.0.5563.64 (Official Build) beta  (64-bit) 
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Linux

- Verified steps from [brave/brave-core#17367](https://github.com/brave/brave-core/pull/17367)
- Verified same tokens on different chains shows correct balance

https://user-images.githubusercontent.com/17010094/225520675-0d935e00-4b88-4275-9b00-0b4f2c2d1a67.mp4


---------------------

Verification passed on 

Brave | 1.50.91 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from [brave/brave-core#17367](https://github.com/brave/brave-core/pull/17367)
- Verified same tokens on different chains shows correct balance

https://user-images.githubusercontent.com/17010094/225515694-c7fc2321-81c1-41fa-8966-8fb1965fcf1e.mp4

---------------------

Verification passed on 

Brave | 1.50.91 Chromium: 111.0.5563.64 (Official Build) beta (arm64)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#17367](https://github.com/brave/brave-core/pull/17367)
- Verified same tokens on different chains shows correct balance

https://user-images.githubusercontent.com/17010094/225521319-ebb44899-4b89-4803-8af4-d82e272747f3.mov
