### ISSUE TITLE
Request Off-The-Record mode

### ISSUE THREAD

**Issue by pilgrim-brave** [brave/brave-browser#28750]
Design spec: https://docs.google.com/document/d/1J1x-pNyT5CENzdb-RxzPxLxFLE4c_PRlz6T-usJUQR4

**Comment by stephendonner** [comment]
## Verification `PASSED` using 

Brave | 1.53.74 Chromium: 114.0.5735.53 (Official Build) beta (x86_64)
-- | --
Revision | c499d7ea22c8b2dba278465a5df7b86a8efa4e64-refs/branch-heads/5735@{#970}
OS | macOS Version 11.7.7 (Build 20G1345)

### Steps:
1. installed `1.53.74`
2. set `brave://flags/#brave-request-otr-tab` to `Enabled`
3. visited a request-OTR enrolled site: `loveisrespect.org`
4. confirmed that the “would you like OTR mode” interstitial appears
5. clicked `Proceed Off-The-Record` to go into OTR mode
6. confirmed that the requested page appears, and that there is an info bar at the top of the page describing how to leave OTR mode
7.  opened dev tools went into the console and ran this code: `window.localStorage.braveQATest = true`
8. closed the OTR’ed site
9. confirmed that the OTR’ed site was not included in your browsing history
10. revisited `loveisrespect.org`, this time declining OTR mode
11. opened the dev tools console and ran this in the console: `console.log(window.localStorage.braveQATest)`

### Confirmed that `undefined` was returned

`Step 2` | `Step 5` | `Step 6` | `Step 6.5` | `Step 7` | `Step 10` | `Step 11`
--------|----------|---------|---------|-----------|---------|----------
<img width="1312" alt="Screen Shot 2023-05-30 at 5 35 23 PM" src="https://github.com/brave/brave-browser/assets/387249/da3e3003-6e4c-4f18-b81c-029ad6fa0267"> | <img width="1312" alt="Screen Shot 2023-05-30 at 5 35 19 PM" src="https://github.com/brave/brave-browser/assets/387249/fbb81d69-6d90-4cb3-b2f9-d926e1a60841"> | <img width="1312" alt="Screen Shot 2023-05-30 at 5 36 21 PM" src="https://github.com/brave/brave-browser/assets/387249/d7e907a1-311d-4eac-b85b-5b197779ee82"> | <img width="1312" alt="Screen Shot 2023-05-30 at 5 36 25 PM" src="https://github.com/brave/brave-browser/assets/387249/31c224c7-0979-4b44-9a9e-d946930427ba"> | <img width="1312" alt="Screen Shot 2023-05-30 at 5 37 13 PM" src="https://github.com/brave/brave-browser/assets/387249/69336f96-5bee-4d4d-acaa-8d9bc42b3044"> | <img width="1312" alt="Screen Shot 2023-05-30 at 5 37 55 PM" src="https://github.com/brave/brave-browser/assets/387249/08ff1b61-9eac-4c4e-8f73-eea7ec48f12f"> | <img width="1312" alt="Screen Shot 2023-05-30 at 5 38 46 PM" src="https://github.com/brave/brave-browser/assets/387249/73558996-c55a-4bfd-8655-853454a1160b">

`brave://history`, `step 9`  | `brave://history`, `step 10+`
------------------------|-----------------------
<img width="1312" alt="Screen Shot 2023-05-30 at 5 51 34 PM" src="https://github.com/brave/brave-browser/assets/387249/19691e66-42b0-438f-a504-3d1200fe08aa"> | <img width="1312" alt="Screen Shot 2023-05-30 at 5 51 27 PM" src="https://github.com/brave/brave-browser/assets/387249/30f347b6-6a1e-4b82-848b-ca53da8e6d29">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.53.76 Chromium: 114.0.5735.90 (Official Build) beta (64-bit)
-- | --
Revision | 386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}
OS | Windows 11 Version 22H2 (Build 22621.1702)
```

#### Case 1: Proceed to OTR - `PASSED` 

1. installed 1.53.76
2. launch Brave
3. set `brave://flags/#brave-request-otr-tab` to Enabled
4. visited a request-OTR enrolled site: https://navegandolibres.org/
5. confirmed that the “would you like OTR mode” interstitial appears
6. clicked `Proceed Off-The-Record` to go into OTR mode
7. confirmed that the requested page appears, and that there is an info bar at the top of the page describing how to leave OTR mode
8. opened dev tools went into the console and ran this code: `window.localStorage.braveQATest = true`
9. closed the OTR’ed site
10. confirmed that the OTR’ed site was not included in your browsing history


step 3 | step 5 | step 7 | step 8 | step 10
---- | --- | --- | --- | ----
<image width="650" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/2b859e3d-7c53-47a6-988a-0f5952161776">|<image width="650" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/8cd42c19-5be6-4cc7-b1d6-5ad3be8fec0f">|<image width="650" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/08de2241-aca5-4991-b6d7-2913d37fb735">|<image width="650" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/4b6b6250-9df8-4978-8f19-1450bc70e5d2">|<image width="650" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/47b4ec60-77ac-44d7-8d5c-40c849030ff8">

#### Case 2:  Decline OTR mode - `PASSED` 

1. Continue from Case 1
    - closed the OTR’ed site
    - no record of `OTR'ed site in `brave://history`
2.  visited https://navegandolibres.org/ in a new tab,
3.  clicked `Proceed Normally` to decline OTR mode
4.  verified info bar at the top of the page is not available
5.  opened the dev tools console and ran this in the console: `console.log(window.localStorage.braveQATest)`

Confirmed that undefined was returned
Confirmed brave://history shows the OTR’ed site

ex | ex | ex | ex | ex 
---- | ---- | ---- | ---- | ----
<image width="650" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/710cac53-d772-4ca0-b0bc-e2abf809b368">|<image width="650" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/61cede8f-ddb1-4d2b-9481-60db3ce9e5e8">|<image width="650" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/a9647261-ba1b-470e-980e-d9cb4ac52151">|<image width="650" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/d52c1c55-925b-4354-acb8-d2ca729f586e">|<image width="650" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/a41bde80-803c-46a6-9c33-f50bc959a436:">

#### Case 3: Turn Off from the infobar - `PASSED` 

1.new profile
2.launch Brave 
3. set `brave://flags/#brave-request-otr-tab` to Enabled
4. visited a request-OTR enrolled site: https://navegandolibres.org/
5. clicked `Proceed Off-The-Record` to go into OTR mode
6. clicked `Turn off` in the infobar 
7. opened brave://history

Confirmed `brave://history` shows the OTR’ed site

step 4 | step 6 | step 7
--- | --- | ----
<image width="650" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/8cd42c19-5be6-4cc7-b1d6-5ad3be8fec0f">|<image width="650" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/70b7e9bb-f54b-48c8-97cd-2aece9a533aa">|<image width="650" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/45c71b78-ad6c-4069-a0a0-007b1d64c686">

**Comment by MadhaviSeelam** [comment]
Verification In progress using
```
Brave | 1.53.85 Chromium: 114.0.5735.110 (Official Build) beta (64-bit)
-- | --
Revision | 1c828682b85bbc70230a48f5e345489ec447373e-refs/branch-heads/5735_90@{#13}
OS | Linux
```

**Comment by sangwoo108** [comment]
Hi, everyone. I'm a bit worried about OTR tab. Many UI components in a browser window are assuming that every tabs and BrowserKeyedService is using same Profile(BrowserContext) with that of `Browser` object. So it's quite common practice for UI code to get profile from the `Browser` object. Not 100% sure but I kind of feel like maybe we're exposing potential risk. 

In the previous patch, it looks like we've done
* Reload web contents
* Override history service
* Add Network throttle
right? If I understand things right, still sometimes we get browser context keyed services from WebContetns's browser context, so wondering if we've switched browser context too. Otherwise, we might access wrong profile for the contents.

I think opening a new incognito window from the interstitial page would be much safer.

cc @petemill @simonhong @bsclifton

**Comment by pes10k** [comment]
Opening a new incognito window doesn’t solve the problem we’re aiming to solve here, for reasons explained in the spec. 

However, @pilgrim-brave and @bridiver have a new approach for OTR-tabs that we think will more comprehensively address these concerns. Though one of them could explain the how and why better than me

**Comment by sangwoo108** [comment]
Thanks @pes10k for the explanation. I agree that OTR tab is worthy.
