### ISSUE TITLE
Incorrect block explorer launched with the correct transaction hash (Back end)

### ISSUE THREAD

**Issue by vadimstruts** [brave/brave-browser#28754]
## Description 

Incorrect block explorer launched with the correct transaction hash, because we don't have chain_id value for each transaction.
Next things should be implemented:
1. Extend each returned TransactionInfo with chain_id property. 
2. Implement migration procedure for already existing transactions

## Steps to Reproduce

   1. Check the TransactionInfo JSON data in the preferences file:
   

## Actual result:

TransactionInfo does not contain the chain_id property
![image](https://user-images.githubusercontent.com/118171981/221305278-51830f4f-6c22-4283-8a95-6bcde3d60277.png)

## Expected result:
TransactionInfo contains the chain_id property
![image](https://user-images.githubusercontent.com/118171981/221298481-81e77cb7-f73d-46c6-a6f9-fa74d8599113.png)

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.51.97 Chromium: 112.0.5615.138 (Official Build) beta (64-bit)
-- | --
Revision | `2258f2fcaeb07bc95c992b7ca47f0b43ead9865c-refs/branch-heads/5615@{#1282}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from [brave/brave-core#17181](https://github.com/brave/brave-core/pull/17181)
- Verified `chain_id` property is being sent in each transaction info

https://user-images.githubusercontent.com/17010094/234013499-3eac1401-f771-4a8a-9ced-fea78f6cd508.mp4
