### ISSUE TITLE
cUSDT is autodiscovered even when the user does not hold it

### ISSUE THREAD

**Issue by nvonpentz** [brave/brave-browser#28752]
It's because the BalanceScanner contract returns `0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000` and we're just doing a simple string comparison of that value against `0x0000000000000000000000000000000000000000000000000000000000000000` [here](https://github.com/brave/brave-core/blob/906ffe6eaff87d0181fd4a061612d1c0f58ca6f7/components/brave_wallet/browser/asset_discovery_manager.cc#L282-L288).

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.50.85 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from [brave/brave-core#17403](https://github.com/brave/brave-core/pull/17403)
- Verified cUSDT isn't auto discovered or added to the token list on a new wallet or a restored one

https://user-images.githubusercontent.com/17010094/224979669-17ef31e2-3743-4117-9b9e-75cf8cbfaca8.mp4
