### ISSUE TITLE
Brave News doesn't update the publisher cache on unsubscribe

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#28765]
## Description 

Unsubscribing from a source doesn't trigger the list of sources to update until the browser is restarted

## Steps to Reproduce

   1. Subscribe to two sources
   2. Reload the NTP
   3. Unsubscribe from one source
   4. Reload the NTP
   5. View sources 

## Actual result:
The source you just unsubscribed from is visible again

## Expected result:
The source is gone

## Reproduces how often: 
Every time

## Mitigations
Subscribing to a source, or restarting the browser will correctly show the source as unsubscribed.

**Comment by kjozwiak** [comment]
The above requires `1.49.117` or higher for `1.49.x` verification 👍

**Comment by kjozwiak** [comment]
@fallaciousreasoning is this valid on `Android` with the old UI/UX? That's currently only on `1.50.x` at the moment and not `1.49.x`.

**Comment by Uni-verse** [comment]
In progress on `Samsung Galaxy S21 5G` using version 

```
Brave	1.49.117 Chromium: 111.0.5563.50 (Official Build) (64-bit) 
Revision	39f3dfc5023fe60997adc4f6cf5439cfa3e6968a-refs/branch-heads/5563@{#903}
OS	Android 13; Build/TP1A.220624.014
```

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.49.118 Chromium: 111.0.5563.50 (Official Build) (64-bit)
-- | --
Revision | 39f3dfc5023fe60997adc4f6cf5439cfa3e6968a-refs/branch-heads/5563@{#903}
OS | Windows 11 Version 22H2 (Build 22621.1265)
```

### Upgrade:

1. Install 1.48.171
2. launch Brave
3. Open a new-tab page
4. click `Turn on Brave News`
6. click `Follow` for sources - `NASA Image of the Day` and `The Spruce Easts`
7. Un followed Top sources in the sidebar for easier view of just the subscribed sources
8. closed `Dashboard`
9. Refreshed NTP
10. verified both articles from both the news sources are shown
11. click `Customize` to return to Brave News Dashboard
12. clicked `Unfollow` on `The Spruce Eats`  
13. close the Dashboard and return to NTP 
14. click `Load new content` or refresh the page

Reproduced the issue that the articles from `The Spruce Eats` are shown.  

steo 4 | step 5 | step 10 | step 9 | step 12 | reproduced the issue
----- | ----- | ------| ------ | ----- | ------
<img width="453" alt="image" src="https://user-images.githubusercontent.com/98358127/222777105-6473737c-cbd3-42a9-9883-2efd5e1b447e.png"> | <img width="457" alt="image" src="https://user-images.githubusercontent.com/98358127/222777153-b639f966-7e66-4ff1-ba66-dd8a242ebec4.png"> | <img width="455" alt="image" src="https://user-images.githubusercontent.com/98358127/222777422-acc5554f-eb95-46cb-b7b0-a4b36e99c345.png"> | <img width="457" alt="image" src="https://user-images.githubusercontent.com/98358127/222777665-57f72c4c-fef6-41c0-b70c-c5e1dd12e040.png"> | <img width="452" alt="image" src="https://user-images.githubusercontent.com/98358127/222777741-77c7af0a-22e7-4199-acc4-77964bc026f0.png"> | <img width="455" alt="image" src="https://user-images.githubusercontent.com/98358127/222777957-34d1cca8-c515-46b7-ba6e-419b3d36727a.png">

After Upgrade:  

1. Close the browser from step 15
    -  Articles from `The Spruce Eats` are shown
2. Install 1.49.118
3. Upgrade to 1.49.118
4. refresh NTP 

### Confirmed articles from `The Spruce Eats` no longer shown and feed is updated accordingly 

step 1 | step 3 | results
------- | ------ | --------
<img width="451" alt="image" src="https://user-images.githubusercontent.com/98358127/222778911-094fdd73-ca68-43d7-8286-d85d6025fe8b.png"> | <img width="471" alt="image" src="https://user-images.githubusercontent.com/98358127/222782612-a08039e5-5030-4686-8cee-b89c5d852591.png"> | <img width="456" alt="image" src="https://user-images.githubusercontent.com/98358127/222782989-09b1e24d-4ab6-4537-9668-75a256d0879e.png">

### New Install

1. Install 1.49.118
2. launch Brave
3. Open a new-tab page
4. click `Turn on Brave News`
5. click `Customize`
6. click `Follow` for sources - `NASA Image of the Day` and `The Spruce Easts`
7. Un followed Top sources in the sidebar for easier view of just the subscribed sources
8. clicked `Back to Dashboard`
9. Refreshed NTP
10. confirmed both articles from both the news sources are shown
11. click `Customize` to return to Brave News Dashboard
12. clicked `Unfollow` on `The Spruce Eats`  
13. close the Dashboard and return to NTP 
14. click `Load new content` or refresh the page

#### Confirmed articles from `The Spruce Eats` no longer shown and feed is updated accordingly 

step 4 | step 5 | step 6 | step 10 | step 12 | step 14 | results
----- | ----- | ----- | ------ | ----- | ------ | -----
<img width="449" alt="image" src="https://user-images.githubusercontent.com/98358127/222765725-fc136dca-65a8-41b0-9c02-4c8935c7e4aa.png">|<img width="454" alt="image" src="https://user-images.githubusercontent.com/98358127/222765860-d7136e2f-f724-4677-9854-9f80fdd5f9ac.png">|<img width="465" alt="image" src="https://user-images.githubusercontent.com/98358127/222766554-28e09428-cc17-48b3-b45c-b47e21485adf.png">|<img width="455" alt="image" src="https://user-images.githubusercontent.com/98358127/222768237-760e7e8a-c5db-4dd9-aa3e-3ca679923ef6.png">|<img width="454" alt="image" src="https://user-images.githubusercontent.com/98358127/222769743-52f8fde4-d3cc-40e6-9965-0c8d86186624.png">|<img width="453" alt="image" src="https://user-images.githubusercontent.com/98358127/222769911-221db132-4df1-46ee-a3e9-455b64c52763.png">|<img width="454" alt="image" src="https://user-images.githubusercontent.com/98358127/222770103-af5b64ad-9b06-4658-a1cb-cd9029489f0a.png">
