### ISSUE TITLE
condense Add Funds window layout to improve layout for smaller screen size

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#2876]
## Description 

![image](https://user-images.githubusercontent.com/5951041/50929003-fa20da00-1410-11e9-9122-1af6aeee1e62.png)

Current 'Add Funds' windows requires a vertical scroll for smaller screens. Let's condense the layout/content so we can see more information and to remove as much of the vertical scroll as possible.

## Steps to Reproduce
1. Click 'Add Funds' from Panel or Rewards Settings.
2. Resize window to 1366 x 768 
3. Notice vertical scroll.

## Expected result:
1. Less of a vertical scroll on 1024 x 768. 
2. Design to fill in target minimum resolution for no vertical scroll at all.

**Comment by NejcZdovc** [comment]
cc @bradleyrichter @jenn-rhim

**Comment by NejcZdovc** [comment]
closing as this will be replaced with uphold widget
