### ISSUE TITLE
Hide accounts that don't hold a the asset balance (asset detail view)

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#28761]
Accounts with 0 holdings should be hidden from the accounts list.

![Image](https://user-images.githubusercontent.com/318119/221390221-11ed8671-582e-4941-966a-4e35493d3524.png)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.50.91 Chromium: 111.0.5563.64 (Official Build) beta  (64-bit) 
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Linux

- Verified steps from [brave/brave-core#17395](https://github.com/brave/brave-core/pull/17395)
- Verified only accounts with balance is shown on token details page

https://user-images.githubusercontent.com/17010094/225524539-7413bfb2-f0fc-44e7-a957-727205a6085e.mp4

---------------------

Verification passed on 

Brave | 1.50.91 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from [brave/brave-core#17395](https://github.com/brave/brave-core/pull/17395)
- Verified only accounts with balance is shown on token details page

https://user-images.githubusercontent.com/17010094/225524892-4aef4880-a01b-4794-8a5e-3c4e8f4b5847.mp4


---------------------

Verification passed on 

Brave | 1.50.91 Chromium: 111.0.5563.64 (Official Build) beta (arm64)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#17395](https://github.com/brave/brave-core/pull/17395)
- Verified only accounts with balance is shown on token details page

https://user-images.githubusercontent.com/17010094/225525147-5ef8f32f-40a4-424d-b39c-62b7b5e72008.mov
