### ISSUE TITLE
Unable to create a crypto wallet

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#28778]
## Description 
Unable to create a crypto wallet on `1.50.62` Nightly.

## Steps to reproduce 

   1. Install `1.50.62` Nightly
   2. Open `Settings->Wallet`
   3. Click `Get Started`

## Actual result 
It's back to a tab view Activity

## Expected result
Should proceed to a wallet creation.

## Issue reproduces how often 
Always

## Version/Channel Information:

It happens only on Nightly channel

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? No
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
1.50.62

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.50.83 x64 Beta build
- Verified steps from issue description
- Verified able to create a new wallet
- Verified able to import wallet via seed phrase 
-----------
Verification passed on Lenovo Tab with Android 12 running 1.50.83 x64 Beta build
- Verified steps from issue description
- Verified able to create a new wallet
- Verified able to import wallet via seed phrase
