### ISSUE TITLE
`Ethereum` and `Location` content settings are missing in a site content settings

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#28773]
## Description 

`Ethreum` and `Location` content settings are missing in a site content settings in CR 110 and CR 111 works fine in CR 109

## Steps to Reproduce

   1. 1.48.x (CR 110) or 1.50.62 (CR 111)
   2. Open a site
   3. Go into `Site settings`
   4. `Ethreum` and `Location` content settings are missing in a site content settings

## Actual result:

**CR 111**
![image](https://user-images.githubusercontent.com/38657976/221562406-a7e3a00e-aa70-4533-ab18-48923d54ac66.png)

**CR 110**
![image (8)](https://user-images.githubusercontent.com/38657976/221563935-c0e0e6f6-03c3-4e73-85ad-d6a7c2475616.png)

## Expected result:
**CR 109**
![image (7)](https://user-images.githubusercontent.com/38657976/221563098-381a0d05-d426-4828-8434-9d472ad48e8b.png)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.50.62 Chromium: 111.0.5563.33 (Official Build) nightly (64-bit)
-- | --
Revision | 19bd6d0186b7912604e18191826dab9d1df00e2e-refs/branch-heads/5563@{#557}
OS | Windows 10 Version 21H2 (Build 19044.2604)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes in 1.48.x (cr 110) not in 1.47.x (cr 109)
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @rebron @mkarolin @emerick

**Comment by kjozwiak** [comment]
The above requires `1.49.116` or higher for `1.49.x` verification 👍

**Comment by LaurenWags** [comment]
Verified with

```
Brave | 1.49.118 Chromium: 111.0.5563.50 (Official Build) (x86_64)
-- | --
Revision | 39f3dfc5023fe60997adc4f6cf5439cfa3e6968a-refs/branch-heads/5563@{#903}
OS | macOS Version 12.6.3 (Build 21G419)
```

Verified STR from description.
Confirmed labels are displayed as expected.

<img width="1571" alt="Screen Shot 2023-03-03 at 9 05 12 AM" src="https://user-images.githubusercontent.com/28145373/222740728-01b3e5b0-c09b-4ec0-8de3-2564256b676f.png">
