### ISSUE TITLE
Can't connect Brave Wallet to Snapshot.org

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#28774]
## Description 

Twitter user brought it up here -> https://twitter.com/K4y1s/status/1630112344335429632

## Steps to Reproduce

   1. Tried connecting Brave Wallet to Snapshot.org
   2. clicked on the metamask icon
   3. it's just stuck in  loading 

## Actual result:

<img width="1278" alt="Screenshot 2023-02-27 at 15 54 36" src="https://user-images.githubusercontent.com/12224304/221597183-cc3ad53b-e162-4168-9370-c71571e01ac3.png">

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by yrliou** [comment]
Closing as duplicated, see https://github.com/brave/brave-browser/issues/28896.
