### ISSUE TITLE
`Shield settings` header is missing in brave://settings/content page

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#28772]
## Description 

`Shield settings` header is missing in brave://settings/content page in both CR 110 and CR 111 but it works fine in CR 109
## Steps to Reproduce

   1. 1.48.x (CR 110) or 1.50.62 (CR 111)
   2. Navigate to brave://settings/content
   3. `Shield settings` header is missing 

## Actual result:

`Shield settings` header is missing in brave://settings/content page

**CR 111**
![image](https://user-images.githubusercontent.com/38657976/221561404-fec0a9a6-d608-4cee-9b24-ae4cc5d0b04f.png)

**CR 110**
![image](https://user-images.githubusercontent.com/38657976/221564281-0befb6f9-7c95-4567-af2c-84e6726ff788.png)

## Expected result:
**1.47.x - CR 109**
![image](https://user-images.githubusercontent.com/38657976/221561327-7d6a34d9-7733-4d73-82f4-a0552dfab422.png)

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.50.62 Chromium: 111.0.5563.33 (Official Build) nightly (64-bit)
-- | --
Revision | 19bd6d0186b7912604e18191826dab9d1df00e2e-refs/branch-heads/5563@{#557}
OS | Windows 10 Version 21H2 (Build 19044.2604)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes in 1.48.x (cr 110) not in 1.47.x (cr 109)
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron @mkarolin @emerick

**Comment by kjozwiak** [comment]
The above requires `1.49.116` or higher for `1.49.x` verification 👍

**Comment by LaurenWags** [comment]
Verified with

```
Brave | 1.49.117 Chromium: 111.0.5563.50 (Official Build) (x86_64)
-- | --
Revision | 39f3dfc5023fe60997adc4f6cf5439cfa3e6968a-refs/branch-heads/5563@{#903}
OS | macOS Version 12.6.3 (Build 21G419)
```

Reproduced the issue using STR and `1.49.116 Chromium: 110.0.5481.177`.
Confirmed expected header is shown when using `1.49.117 Chromium: 111.0.5563.50`.

1.49.116 | 1.49.117
---- | ----
<img width="1257" alt="Screen Shot 2023-03-02 at 9 53 10 AM" src="https://user-images.githubusercontent.com/28145373/222464189-f67c759f-be44-447b-a57e-2113fd481189.png"> | <img width="1450" alt="Screen Shot 2023-03-02 at 9 53 33 AM" src="https://user-images.githubusercontent.com/28145373/222464192-50f19bda-ad2b-4b55-8e81-adf604e6c0a0.png">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.49.120 Chromium: 111.0.5563.64 (Official Build) (64-bit)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | Windows 11 Version 22H2 (Build 22621.1265)
```

Reproduced issue using STR from https://github.com/brave/brave-browser/issues/28772#issue-1601077709 in `1.48.171 Chromium: 110.0.5481.177`

Confirmed `Shields settings` header is shown as expected in `brave://settings/content` page 

1.48.171 | 1.49.120
------ | -------
<img width="943" alt="image" src="https://user-images.githubusercontent.com/98358127/223777039-389f8146-ac44-4632-8142-b8afb9196549.png">|<img width="943" alt="image" src="https://user-images.githubusercontent.com/98358127/223777306-64f304ef-2df9-457b-8a12-2def06a105b2.png">
