### ISSUE TITLE
Extra permission item in Settings -> Privacy and Security -> Website/specific permission

### ISSUE THREAD

**Issue by dpthegrey** [brave/brave-browser#28779]
## Description 

There is an extra permission thing without any title, when you click on a website from recent activity and also shows when you go though a specific permission.

For Example: when you click on `Notification` permission then it shows multiple websites which has Notification allowed or not. In there, there is such a block which has the `Extension` like icon and a drop-down permission drawer but there is no title what permission it is for.

## Steps to Reproduce

   1. Go to Settings
   2. Privacy and security
   3. open site under Recent activity

## Actual result:

![image](https://user-images.githubusercontent.com/49444980/221620269-2eb02300-1ddb-41fd-8267-1c789669c6fc.png)

## Expected result:
Either there should be a title containing type of permission or this extra block should not be visible to users.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

1.50.62 Chromium: 111.0.5563.33 (Official Build) nightly (x86_64) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes, shows 2 such
- Can you reproduce this issue with the beta channel? Not tried beta
- Can you reproduce this issue with the nightly channel? Yes, shows 1 of such

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Not tried

## Miscellaneous Information:

Public release shows 2 of those as attached below.

Public Release Version: 1.48.171 Chromium: 110.0.5481.177 (Official Build) (x86_64) 

![image](https://user-images.githubusercontent.com/49444980/221624124-92ceb00b-d5a2-4c10-9aeb-f21d78fcc2f6.png)

**Comment by rebron** [comment]
Closing as dupe of https://github.com/brave/brave-browser/issues/28773
