### ISSUE TITLE
Browser crash when trying to import accounts from Ledger

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#28770]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.49.108  Chromium: 110.0.5481.104
Operating System: Windows NT 10.0.22621

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Clean profile on 1.49.108
2. Connect Ledger wallet and open Filecoin App
3. Import Filecoin account from Ledger
4. Browser crashes

https://user-images.githubusercontent.com/17010094/221551404-93b35e21-5233-4a9b-adfd-b45165732651.mp4

**Reproduced only once. Subsequent attempts worked fine** 

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/fc6f0500-b06f-ac09-0000-000000000000

cc: @brave/crypto-wallets-core

**Comment by iefremov** [comment]
@srirambv can you please re-repro?

**Comment by srirambv** [comment]
Haven't seen this crash recently. Closing as stale
