### ISSUE TITLE
Verify media type before pinning an NFT

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#28775]
According sec review https://github.com/brave/security/issues/1182#issuecomment-1434728109 we should verify that content has supported media format before pinning.
At the moment image is only supported format.

**Comment by kjozwiak** [comment]
The above requires `1.50.94` or higher for `1.50.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.50.94 Chromium: 111.0.5563.64 (Official Build) beta (64-bit) 
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Linux

- Verified steps from [brave/brave-core#17392](https://github.com/brave/brave-core/pull/17392)
- Verified when `content-type` is not `image/png` NFT Pinning fails 

Pinning success | Pinning failure
-- | --
![image](https://user-images.githubusercontent.com/17010094/226275174-f07651dd-2cec-4ee8-a423-71bfc13c2a18.png) | ![image](https://user-images.githubusercontent.com/17010094/226273387-f32c7881-8a0e-4c02-b85c-da889463a940.png)

---------------------

Verification passed on 

Brave | 1.50.94 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Windows 11 Version 22H2 (Build 22621.1344)
- Verified steps from [brave/brave-core#17392](https://github.com/brave/brave-core/pull/17392)
- Verified when `content-type` is not `image/png` NFT Pinning fails 

Pinning success | Pinning failure
-- | --
![image](https://user-images.githubusercontent.com/17010094/226303406-07e682f3-22df-439b-ba7a-c519d3ee06ca.png)
![image](https://user-images.githubusercontent.com/17010094/226303381-bd087b81-fc43-40f8-84ce-e4cca97962bf.png)
