### ISSUE TITLE
Onboarding: Import button should be disabled if there's no selection

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#28788]
## Description 
If you install Brave and go through the steps in the onboarding, one is import. If you de-select everything, you can still click the `Import` button (although it doesn't do anything).

We should disable the button unless something is selected

## Steps to Reproduce

   1. Have other browsers installed (and have profile data for them)
   2. Fresh install of Brave
   3. Go through onboarding until Import screen
   4. Deselect any browser selection (nothing should be selected)

## Actual result:
Import button is active and clickable. Doesn't do anything - but it's not disabled.

## Expected result:
Button should be disabled

**Comment by kjozwiak** [comment]
The above requires `1.50.112` or higher for `1.50.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.50.113 Chromium: 112.0.5615.49 (Official Build) (64-bit)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Windows 10 Version 21H2 (Build 19044.2728)

```

- Reproduced the issue on `1.50.108` 
![image](https://user-images.githubusercontent.com/38657976/229852529-db748792-03f2-47b8-bbf4-9dd9f754d97c.png)

- Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/28788#issue-1601811480, ensured the following:

* ensured that `Import` is not clickable when a browser has not been selected during the `Import` phase
* ensured that selecting a browser enables the `Import` button without any issues
  * ensured that clicking the `Import` button works as expected and moves onto the next phase of `Import`

**`Example`** | **`Example`**
----------------|-----------------
![image](https://user-images.githubusercontent.com/38657976/229853326-193990f0-710a-4b6e-b31c-1dc70b1a3747.png) | ![image](https://user-images.githubusercontent.com/38657976/229854139-a73171a5-53c4-4cb3-9fbe-62c480a6f193.png)
