### ISSUE TITLE
Onboarding: setting as default may break import flow

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#28787]
## Description 
Capturing feedback from https://github.com/brave/brave-core/pull/17270

Has not been verified as an issue (yet) - but we should check this. If it's not an issue, we can close this out 😄 

## Steps to Reproduce

   1. Have a browser which isn't Brave registered as the default browser
   2. Install Brave (fresh install)
   3. In onboarding, accept Brave as the default browser
   4. You're prompted to import

## Actual result:
Brave is now your default browser - but we should show what USED to be the default browser.

## Expected result:
Whatever used to be your default should be the pre-selected choice for importing

**Comment by MadhaviSeelam** [comment]
Reproduced using STR from https://github.com/brave/brave-browser/issues/28787#issue-1601807078

```
Brave | 1.50.107 Chromium: 112.0.5615.39 (Official Build) beta (64-bit)
-- | --
Revision | a0e7b9718a92bcd1cf33b7c95316caff3fc20714-refs/branch-heads/5615@{#753}
OS | Windows 11 Version 22H2 (Build 22621.1413)
```

Currently user pre-selected default browser (i.e. Edge) is shown on the Import Settings screen when clicked `Skip` on `brave://welcome`- first screen.  However, when clicked `Set Brave as default browser` button, user's selection wasn't shown in the Import Settings screen. 


Skip| Set Brave as default browser 
----|----
<img width="457" alt="image" src="https://user-images.githubusercontent.com/98358127/228601398-6fac7bc0-771b-45f0-af3b-30baa236f1a7.png">|<img width="459" alt="image" src="https://user-images.githubusercontent.com/98358127/228600902-cb889aa2-a9a8-4c36-bde8-e0e12df155f1.png">

**Comment by kjozwiak** [comment]
The above requires `1.50.111` or higher for `1.50.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.50.113 Chromium: 112.0.5615.49 (Official Build) (64-bit)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Windows 10 Version 21H2 (Build 19044.2728)
```
Verified the issue on 1.50.113 and ensured that the user pre-selected default browser (i.e. Edge) is shown as selected on the `Import Settings screen` when `Set Brave as default browser` option is selected in the brave://welcome screen

**Case 1:**
 
1. Set other browsers (apart from brave) e.g `Edge` as default
2. Clean install `1.50.113`
3. In brave://welcome screen, select `Set Brave as default browser`
4. User pre-selected default browser (i.e. Edge) is shown as selected on the `Import Settings screen` as expected
5. Ensured that brave is default browser now


Example | Example 
----------|-----------
![image](https://user-images.githubusercontent.com/38657976/229856167-0675ba53-e23d-4ac1-9639-d1a00e7ace8b.png) | ![image](https://user-images.githubusercontent.com/38657976/229856014-88613d51-7072-41dc-89b7-297c92520b05.png)



**Case 2:**

1. Set other browsers (apart from brave) e.g `Edge` as default
2. Clean install `1.50.113`
3. In brave://welcome screen, select `Skip`
4. User pre-selected default browser (i.e. Edge) is shown as selected on the `Import Settings screen` as expected

Example | Example 
----------|-----------
![image](https://user-images.githubusercontent.com/38657976/229856482-2b13e988-6c45-4dd2-9c65-3fd8bb537cf7.png) | ![image](https://user-images.githubusercontent.com/38657976/229856536-62240a2b-b2f3-4c3a-8c5b-094a4026f669.png)
