### ISSUE TITLE
Remove Google icon in address bar when performing search via Google.com

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#28790]
## Description 

When a user uses Google to search and clicks on a result, a Google icon appears in the address bar:
![image](https://user-images.githubusercontent.com/3299098/221698697-ebcb184a-2f52-4766-b4a7-84899ca77695.png)
This is a chromium feature that allows users to click this option to open a side-panel with the search results from their previous search in it for easy navigation.

This feature should be removed as it does not work in Brave and it is (clearly) Google branded, which is not ideal. 

## Steps to Reproduce

   1. Perform a search on Google.com
   2. Click a result
   3. Observe the Google icon appear in the address bar

## Reproduces how often: 

Easily reproduced

## Brave version (info found on brave://version)

v1.48.164

## Version/Channel Information:

- Can you reproduce this issue with the current release? Y
- Can you reproduce this issue with the beta channel? Y
- Can you reproduce this issue with the dev channel? Y
- Can you reproduce this issue with the nightly channel? Y

## Miscellaneous Information:

cc @rebron @simonhong

**Comment by simonhong** [comment]
It looks like cr111 doesn't have this issue. As we'll release 1.49.x with cr111, let's wait for 1.49.x

**Comment by bsclifton** [comment]
Closing as this is resolved in Chromium 111

**Comment by rebron** [comment]
<img width="977" alt="Screenshot 2023-03-02 at 8 08 40 PM" src="https://user-images.githubusercontent.com/5951041/222629137-e629f056-9304-4e7a-8b4e-d8086365fd4a.png">
This is showing up in 1.49 RC

Brave | 1.49.117 Chromium: 111.0.5563.50 (Official Build) (arm64)
-- | --
Revision | 39f3dfc5023fe60997adc4f6cf5439cfa3e6968a-refs/branch-heads/5563@{#903}
OS | macOS Version 13.3 (Build 22E5219e)
JavaScript | V8 11.1.277.13
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36

**Comment by vrindavan** [comment]
Hey @bsclifton seems like this is back. Screenshot:
![image](https://user-images.githubusercontent.com/50140643/227785846-d007f33d-9500-448c-8feb-fd0a6fed0fc0.png)

**Comment by simonhong** [comment]
> Looks like this is back (_1.49.x stable_). Screenshot:
> 
> ![image](https://user-images.githubusercontent.com/50140643/227785846-d007f33d-9500-448c-8feb-fd0a6fed0fc0.png)

The fix is not yet arrived to current stable `1.49.x`.
It's merged to `1.51.x` and you can get the fix when `1.51.x` becomes stable.
