### ISSUE TITLE
HTTPS shield setting from `Normal` windows are leaking into `Private` windows

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#28792]
## Description 

As per https://github.com/brave/brave-core/pull/17236, HTTPS shield settings from `Normal` windows shouldn't be leaking into either `Tor` or `Private` windows. Currently `Tor` is working as expected but the changes via `Normal` are leaking into `Private` windows. @arthuredelstein confirmed that he can reproduce as well.

## Steps to Reproduce

* launch `1.50.67 Chromium: 111.0.5563.33`
* restart the browser using the following and ensure that you're added into `BraveHttpsByDefaultRolloutStudy:Enabled`
  * `--variations-server-url=https://variations.bravesoftware.com/seed`
* visit https://insecure.arthuredelstein.net and select `Don't upgrade connections to HTTPS` via the shields panel
* launch a PB window and load https://insecure.arthuredelstein.net
* notice that the HTTPS setting changes from `Normal` window are leaking into `Private` window

## Actual result:

HTTPS shields settings that have been changed via `Normal` windows leaking into `Private` windows and not being isolated

## Expected result:

HTTPS shield settings shouldn't be leaking from `Normal` to `Private` windows and need to be isolated.

## Reproduces how often: 

100% reproducible when using the STR/Case outlined above.

## Brave version (brave://version info)

```
Brave | 1.50.67 Chromium: 111.0.5563.33 (Official Build) nightly (64-bit) 
--- | ---
Revision | 19bd6d0186b7912604e18191826dab9d1df00e2e-refs/branch-heads/5563@{#557}
OS | Windows 11 Version 22H2 (Build 22621.1265)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A`
- Can you reproduce this issue with the beta channel? `N/A`
- Can you reproduce this issue with the nightly channel? `N/A`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by arthuredelstein** [comment]
To update here -- we decided to make sure that _more permissive_ settings do not leak from normal windows to incognito windows. However we do want a _less permissive_ setting (such as global strict or per-site strict mode) to be inherited by incognito windows.

**Comment by kjozwiak** [comment]
The above requires `1.50.110` or higher for `1.50.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave	1.50.108 Chromium: 112.0.5615.39 (Official Build) (64-bit) 
Revision	a0e7b9718a92bcd1cf33b7c95316caff3fc20714-refs/branch-heads/5615@{#753}
OS	Linux
```
### Shared Steps (but each test was done clean):
<details>

1. installed `1.50.110`
2. opened `brave://flags`
3. toggled `brave://flags/#https-by-default` to `Enabled`
4. clicked on `Relaunch`




</details>

### Case 1 - Upgrade connections to HTTPS - ``
<details>


1. launched/restarted `1.50.110`
2. visited `http://upgradable.arthuredelstein.net/` in a `Normal window` and ensured that `Upgrade connections to HTTPS` was selected in the Shields panel
3. ensured that `http://upgradable.arthuredelstein.net `-> `https://upgradable.arthuredelstein.net`
4. opened a `Private window` and visited `http://upgradable.arthuredelstein.net/` and ensured `Upgrade connections to HTTPS`
5. ensured that `http://upgradable.arthuredelstein.net` -> `https://upgradable.arthuredelstein.net`

#### Ensured that connections were upgraded to HTTPS

step 2 | step 3 | step 4 | step 5
-------|-------|--------|-------






</details>


### Case 2 - Only connect using HTTPS - ``
<details>

1. launched/restarted `1.50.110`
2. visited `http://upgradable.arthuredelstein.net/` switched `HTTPS upgrades` to `Only connect with HTTPS`
3. ensured that `http://upgradable.arthuredelstein.net` -> `https://upgradable.arthuredelstein.net`
4. opened a `Private window` and visited `http://upgradable.arthuredelstein.net/` and ensured `Only connect with HTTPS`
5. ensured that `http://upgradable.arthuredelstein.net` -> `https://upgradable.arthuredelstein.net`

#### Ensured that connections used HTTPS

step 2 | step 3 | step 4 | step 5
-------|-------|--------|-------





</details>

### Case 3 - Don't upgrade HTTPS connections - ``
<details>


1. launched/restarted `1.50.110`
2. visited `http://upgradable.arthuredelstein.net/` and switched `HTTPS upgrades` to `Don't upgrade HTTPS connections` in the `Shields` panel
3. reloaded `http://upgradable.arthuredelstein.net/` and ensured that the website was _not_ being upgraded to HTTPS
4. opened a `Private window` and visited `http://upgradable.arthuredelstein.net/` and ensured `Upgrade connections to HTTPS` was selected in the `Shields` panel
5. ensured that `http://upgradable.arthuredelstein.net` -> `https://upgradable.arthuredelstein.net`


### Ensured that `Don't upgrade HTTPS connections` is _NOT_ being used

step 2 | step 3 | step 4 | steps 5-6
-------|-------|---------|--------



</details>


### Case 4 - Don't upgrade HTTPS connections (Private Window Only) - ``
<details>

1. launched/restarted `1.50.110` 
2. opened a `Private window` and visited `http://upgradable.arthuredelstein.net/` and ensured `Upgrade connections to HTTPS` was selected
3. ensured that `http://upgradable.arthuredelstein.net` -> `https://upgradable.arthuredelstein.net`
4. changed the `HTTPS upgrade` setting to `Don't upgrade HTTPS connections` and loaded `http://upgradable.arthuredelstein.net`
5. ensured that `http://upgradable.arthuredelstein.net` is _NOT_ upgraded

step 2 | step 3 | step 4 | step 5
--------|-------|---------|--------



</details>

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.50.110 Chromium: 112.0.5615.49 (Official Build) (64-bit)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Windows 11 Version 22H2 (Build 22621.1413)
```
