### ISSUE TITLE
Please add filter adblockid for strong blockig ads indonesia

### ISSUE THREAD

**Issue by Jokopentil** [brave/brave-browser#28802]
Blocking ads indonesia more powerful
If abpindo+adblockid added

**Comment by YellowStar11** [comment]
@Jokopentil Hi there you can manually add AdblockID filter in brave://adblock 

I had suggest to add adblockID as new regional filter for Indonesian users. And the engineer FanboyNZ already did review & His review is the filter (adblockID) contains problematic filter such as they target international site that already covered by Easylist.I think ABPindo is more than enough even uBO also use that filter https://community.brave.com/t/request-add-new-regional-list-filter/428329/2 

Jika anda melihat iklan disitus yang anda kunjungi, anda dapat melapornya github ABPindo

**Comment by bsclifton** [comment]
Thanks for the assist @YellowStar11 😄 

cc: @ryanbr

**Comment by bsclifton** [comment]
@Jokopentil you can check any additional boxes you'd like - if the sources you want are missing, we can look at adding them
![image](https://user-images.githubusercontent.com/4733304/222233393-ec5743cf-e057-42e3-b3c0-1681b2e2fae4.png)

**Comment by ryanbr** [comment]
We'll follow the default lists in uBO, there could be some redundancy or false positives including 2 indo lists. But you're free to add it via the list subscription in brave://adblock @YellowStar11 @Jokopentil
