### ISSUE TITLE
Fiat Balances are broken for test networks

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#28806]
## Description 

Fiat balance are broken for test network tokens

## Steps to Reproduce

   1. Enable a test network in settings
   2. Go to the portfolio page and filter by that test network
   3. The Fiat balance never loads.

## Actual result:

![Before1](https://user-images.githubusercontent.com/40611140/221945232-38304711-6f70-48c8-8bc4-cd38582f59d1.png)

![Before2](https://user-images.githubusercontent.com/40611140/221945275-d531d5a2-50e7-4877-899b-f378cc7e0cb3.png)

## Expected result:
Should load Fiat balances

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.50.108` or higher for `1.50.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.50.108 Chromium: 112.0.5615.39 (Official Build) (64-bit)
-- | --
Revision | `a0e7b9718a92bcd1cf33b7c95316caff3fc20714-refs/branch-heads/5615@{#753}`
OS | Linux

- Verified steps from [brave/brave-core#17415](https://github.com/brave/brave-core/pull/17415)
- Verified Fiat balance is shown for all test networks

https://user-images.githubusercontent.com/17010094/228474478-8d4c9f3e-34b5-45e9-894c-0bf389f7d1d0.mp4
