### ISSUE TITLE
Background images are not rotating for new tabs [C111]

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#28803]
## Description 
Opening a new tab displays the same bg image every time. The SI images are not shown and bg images are not rotating.

## Steps to reproduce 

   1. `Install 1.50.67, Chromium 111.0.5563.33`
   2. Launch app, open some new tabs
   3. Observe NTP background image

## Actual result 
Every NTP has same bg image
![screenshot-1677602071795](https://user-images.githubusercontent.com/17885425/221919241-9f38fec7-9eeb-4ab7-be9a-04a925accc9c.png)

## Expected result
Should rotate between bg images, SI images every 4th tab

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? N/A 
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung GS 21
   - Android version: 13
   
## Brave version
`1.50.67, Chromium 111.0.5563.33`

**Comment by kjozwiak** [comment]
The above requires `1.49.116` or higher for `1.49.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21 5G` using version 

```
Brave	1.49.117 Chromium: 111.0.5563.50 (Official Build) (64-bit) 
Revision	39f3dfc5023fe60997adc4f6cf5439cfa3e6968a-refs/branch-heads/5563@{#903}
OS	Android 13; Build/TP1A.220624.014
```
- Ensured that background images are being cycled through when opening new tabs
- Ensured Si images are shown
- Ensured user is able to disable background images on NTP

<table><tr><td>

https://user-images.githubusercontent.com/17885425/222495893-6a97fc97-1a5e-473c-919b-2be69f1233b5.mp4

</td><td>

<img width="400" alt="tabs" src="https://user-images.githubusercontent.com/17885425/222496283-8321d958-8f2a-4cba-87f1-4b1aeb572df5.png">

</td></tr></table>
