### ISSUE TITLE
'Create QR code' editing broken

### ISSUE THREAD

**Issue by wedebe** [brave/brave-browser#28808]
Previous issues searched but not found.

## Description 

Can't empty the text input field, paste to replace the content, or edit it properly.

## Steps to Reproduce

   1. Open the Share menu from the URL bar
   2. Click `Create QR code`
   3. Try either to:
       - paste some simple text to replace the content
       - _select all_ -> _delete_ the content of the input field
       - edit out the semicolon character

## Actual result:

All of the above attempts will fail (field doesn't change)

## Expected result:
The text input field should be freely editable

## Reproduces how often: 

Every time. 

## Brave version (brave://version info)

Brave | 1.48.171 Chromium: 110.0.5481.177 (Official Build) (x86_64)
-- | --
Revision | f34f7ab2d4ca4ad498ef42aeba4f4eb2c1392d63-refs/branch-heads/5481@{#1239}
OS | macOS Version 12.6.3 (Build 21G419)

## Version/Channel Information:

- Can you reproduce this issue with the current release? **Not tried**
- Can you reproduce this issue with the beta channel? **Not tried**
- Can you reproduce this issue with the nightly channel? **Not tried**

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? **No**
- Does the issue resolve itself when disabling Brave Rewards? **N/A**
- Is the issue reproducible on the latest version of Chrome? **Not tried**

## Miscellaneous Information:

This only started happening after I updated earlier today.

**Comment by bsclifton** [comment]
This is a weird one - I've confirmed it's working as expected on Nightly. But it's broken on Release and Beta

![qr-code](https://user-images.githubusercontent.com/4733304/222066727-f1115ab1-74ad-464d-aaf7-548b1ffdf8a7.gif)

**Comment by bsclifton** [comment]
@wedebe OK I checked Chrome and it happens there too. So it seems this is upstream and will be fixed when we have the upgrade to Chromium 111. For Brave, this is due in release channel on March 7th 😄 

I'll close this issue and put in the milestone - heads up @brave/qa-team
