### ISSUE TITLE
HTTPS Upgrades should prevent referrer stripping on same site

### ISSUE THREAD

**Issue by arthuredelstein** [brave/brave-browser#28809]
When the referrer policy is `strict-origin-when-cross-origin`, clicking from a secure page to a same-site insecure link should result in stripping the path from the referrer. However, if HTTPS by Default (or HTTPS-Only Mode) upgrades navigation to HTTPS, then we effectively have a same-origin navigation and the referrer should not be stripped. Unfortunately it looks HTTPS-Only Mode (and therefore HTTPS by Default) are allowing the referrer to be stripped because of the way they use an internal dummy redirect.

**Steps to reproduce:**

1. Use devtools to use a mobile UA (I used Android (4.0.2) browser.
2. Visit https://anicobin.ldblog.jp/archives/59981055.html
3. Click on the comments button:
  ![image](https://user-images.githubusercontent.com/355566/222008868-eb53aca4-a0a8-4c6b-93aa-73117ce59276.png)

**Expected result**
A page with comments should be loaded:
  
![image](https://user-images.githubusercontent.com/355566/222009603-9fe2f98e-9ca1-4277-a0e0-c018c3eb1174.png)

**Actual result**
A "load error" page will be displayed:
![image](https://user-images.githubusercontent.com/355566/222009066-4a65e918-f66a-4d83-bf53-158aaa88a072.png)

Demo at https://gif.fanboy.co.nz/gif/anicobin.gif

**Comment by diracdeltas** [comment]
> However, if HTTPS by Default (or HTTPS-Only Mode) upgrades navigation to HTTPS, then we effectively have a same-origin navigation and the referrer should not be stripped.

what happens if the navigation target is HTTP but gets upgraded through HSTS? does the same bug occur?

**Comment by arthuredelstein** [comment]
> > However, if HTTPS by Default (or HTTPS-Only Mode) upgrades navigation to HTTPS, then we effectively have a same-origin navigation and the referrer should not be stripped.
> 
> what happens if the navigation target is HTTP but gets upgraded through HSTS? does the same bug occur?

No, it does not occur in that case.

**Comment by arthuredelstein** [comment]
I confirmed that this bug was fixed by https://github.com/brave/brave-core/pull/17856

**Comment by kjozwiak** [comment]
Added this issue into https://github.com/brave/brave-core/pull/17856#issue-1649852946 & https://github.com/brave/brave-core/pull/18179#issue-1677582014 so it can also be verified. Also adding missing labels/milestones.

**Comment by kjozwiak** [comment]
The above requires `1.51.107` or higher for `1.51.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.51.107 Chromium: 113.0.5672.63 (Official Build) (x86_64)
-- | --
Revision | 0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}
OS | macOS Version 13.4 (Build 22F5049e)

### Followed the steps in this issue, as reported

## Confirmed I could load & read the comments section on `https://anicobin.ldblog.jp/archives/59981055.html`

example | example | example | example
---------|----------|---------|---------
<img width="2007" alt="Screenshot 2023-04-29 at 3 39 47 AM" src="https://user-images.githubusercontent.com/387249/235298661-be4bdc45-abc4-4da5-b2f0-dc8399f0d18d.png"> | <img width="2007" alt="Screenshot 2023-04-29 at 3 40 07 AM" src="https://user-images.githubusercontent.com/387249/235298666-0ad0fb0e-5425-4c4a-9827-faea5a2f7cc0.png"> | <img width="2007" alt="Screenshot 2023-04-29 at 3 40 18 AM" src="https://user-images.githubusercontent.com/387249/235298668-aec917be-ab4c-4c91-9690-2882006d95f3.png"> | <img width="2007" alt="Screenshot 2023-04-29 at 3 46 22 AM" src="https://user-images.githubusercontent.com/387249/235298766-6f1e5d9c-0894-49be-89a1-5f368057d01b.png">

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 14` using the following build(s):

```
Brave | 1.53.1 Chromium: 113.0.5672.53 (Official Build) canary (32-bit)
--- | ---
Revision | 12f5dac35d12e8f4e72d7dd11df557ef93bc046f-refs/branch-heads/5672@{#703}
OS | Android 13; Build/UPB1.230309.014; 33; UpsideDownCake
```

Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/28809#issue-1603968960, ensured the following:

* loaded https://anicobin.ldblog.jp/archives/59981055.html and ensured that clicking on the `comment` image loads the page
* ensured that the comment section loaded without any issues

**`Example`** | **`Example`** | **`Example`**
---------------|-----------------|-----------------
![Screenshot_20230501-002616](https://user-images.githubusercontent.com/2602313/235406650-0a96b668-f536-4640-953f-bb81b88b1fb1.png) | ![Screenshot_20230501-002632](https://user-images.githubusercontent.com/2602313/235406658-4fd36a1a-ecf8-452d-978d-e9a14e746598.png) | ![Screenshot_20230501-002638](https://user-images.githubusercontent.com/2602313/235406664-9c927e41-62f2-4a22-994e-e3f6247847e6.png)
