### ISSUE TITLE
[Android] [Rewards 2.5 Phase 4] Click on “Connect account” in the vBat expiry notice via the BR panel doesn't open the connect account modal

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#28816]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/27883
Click on “Connect account” via BR panel doesn't open the connect account modal popup
## Steps to Reproduce

   1. Follow the steps from scenario 3 via https://docs.google.com/document/d/1YVa6Wx4kMd90Q7mfx29iW--xa4tPNl7YXc486CkYQAI/edit#heading=h.t2vdk6dnw3tr 
   

## Actual result:

[Rewards 2.5 Phase 4] Click on “Connect account” in the vBat expiry notice via the BR panel doesn't open the connect account modal
![image](https://user-images.githubusercontent.com/38657976/222078835-0c517d7d-5904-4201-8be1-323634d3fa65.png)

## Expected result:
Click on “Connect account” via BR panel should open up the connect account modal popup

## Reproduces how often: 

Easy
## Brave version (brave://version info)

1.49.108

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @Miyayes @deeppandya

**Comment by deeppandya** [comment]
@GeetaSarvadnya when you click on `connect account`, it doesn't do anything ? Which page it redirects to ?

**Comment by GeetaSarvadnya** [comment]
@deeppandya Click on "connect account" does nothing, it stays on the same BR panel

**Comment by Miyayes** [comment]
> @deeppandya Click on "connect account" does nothing, it stays on the same BR panel

When this happens, can you go to brave://rewards-internals and see what it says? Does it say "Rewards profile not yet created", or do things look normal?

**Comment by Miyayes** [comment]
If it turns out to be due to https://github.com/brave/brave-browser/issues/21057, then will remove release blocking.

**Comment by GeetaSarvadnya** [comment]
@Miyayes I don't see any specific errors related to this issue in brave://rewards-internals. But I do see some exception in Android studio when I click on "Connect account" in BR panel

cc: @deeppandya 
```
2023-03-02 12:19:11.062 24752-24752/? E/GEL_DELAYED_EVENT_DEBUG: Volley request failed for type akit
    dos: auga: Exception in CronetUrlRequest: net::ERR_CERT_AUTHORITY_INVALID, ErrorCode=11, InternalErrorCode=-202, Retryable=false
        at rts.run(PG:35)
        at aekq.run(PG:3)
        at oox.run(PG:5)
        at opb.run(PG:23)
        at opo.run(PG:63)
        at nxm.run(PG:7)
        at java.lang.Thread.run(Thread.java:1012)
        at opg.run(PG:5)
     Caused by: auga: Exception in CronetUrlRequest: net::ERR_CERT_AUTHORITY_INVALID, ErrorCode=11, InternalErrorCode=-202, Retryable=false
        at org.chromium.net.impl.CronetUrlRequest.onError(PG:5)
2023-03-02 12:19:11.336 24752-24752/? E/YouTube: Volley request retry failed for type akit
    dos: auga: Exception in CronetUrlRequest: net::ERR_CERT_AUTHORITY_INVALID, ErrorCode=11, InternalErrorCode=-202, Retryable=false
        at rts.run(PG:35)
        at aekq.run(PG:3)
        at oox.run(PG:5)
        at opb.run(PG:23)
        at opo.run(PG:63)
        at nxm.run(PG:7)
        at java.lang.Thread.run(Thread.java:1012)
        at opg.run(PG:5)
     Caused by: auga: Exception in CronetUrlRequest: net::ERR_CERT_AUTHORITY_INVALID, ErrorCode=11, InternalErrorCode=-202, Retryable=false
        at org.chromium.net.impl.CronetUrlRequest.onError(PG:5)
```

**Comment by kjozwiak** [comment]
The above requires `1.49.120` or higher for `1.49.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Samsung Galaxy Version 12` running `Bravemonoarm64.apk_1.49.120`

- Followed the steps from scenario 3 via https://docs.google.com/document/d/1YVa6Wx4kMd90Q7mfx29iW--xa4tPNl7YXc486CkYQAI/edit#heading=h.t2vdk6dnw3tr 
- Ensured that the click on “Connect account” in the vBat expiry notice via the BR panel open up the connect account modal

BR panel on pubs page | click on "connect" | connect account modal
---------------------------|---------------------|--------------------------



BR panel on NTP | click on "connect" | connect account modal
-------------------|---------------------|--------------------------


Logs for vbatDeadline set in the future

```
 

```
Also, ensured that click on “Connect account” in the vBat expiry notice via the brave://rewards settings page opens up the connect account modal

Brave://rewards settings page | click on "connect" | connect account modal
----------------------------------|---------------------|--------------------------
