### ISSUE TITLE
Vertical tabs hover-mode pinned tabs should be full-width so tabs are in the same place in minimized-mode

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#28810]
Pinned tab in hover-mode would show without tab title. Only the favicon should show, centered.

**Comment by sangwoo108** [comment]
the same response from our users: https://github.com/brave/brave-browser/issues/464#issuecomment-1376892765

**Comment by sangwoo108** [comment]
Edge shows title too even tabs are pinned on floating(hover) mode.

<img width="258" alt="image" src="https://user-images.githubusercontent.com/5474642/222054919-978359d5-3e94-45f9-9d46-d282b3a1774f.png">

@petemill , Do you think hiding title is better? cc @aguscruiz (this is what we've talked a long time ago)

**Comment by aguscruiz** [comment]
Yeah I think this is the way to go for this, otherwise it becomes jarring if the thing you want to hover on moves around as soon as you do it

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.51.84 Chromium: 112.0.5615.49 (Official Build) beta (x86_64)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | macOS Version 13.4 (Build 22F5027f)

### Steps:
1. installed `1.51.84`
2. launched Brave
3. opened `brave://flag`
4. enabled `brave://flags/#brave-vertical-tabs` flag
5. clicked `Relaunch`
6. loaded a few sites
7. pinned most of them
