### ISSUE TITLE
Add `SESSION_EXPIRED` state to vpn's purchased state

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#28811]
Provide separated panel view for some time when current subscription is expired instead of showing sell panel.

![image](https://user-images.githubusercontent.com/6786187/222056886-807eac69-c4fd-45fb-a80b-6651a732f4a0.png)

cc @bsclifton

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.51.47 Chromium: 112.0.5615.29 (Official Build) nightly (64-bit)
-- | --
Revision | 8a59304c62e066962363d2fd8edd8e7b459c42bd-refs/branch-heads/5615@{#497}
OS | Windows 10 Version 22H2 (Build 19045.2728)

### Steps:
1. installed `1.51.47`
2. launched Brave
3. purchased and configured VPN
4. connected to `BraveVPN`
5. confirmed `status` of `paid` in `Local State`
6. clicked `Cancel plan` on `account.brave.com`
7. shut down Brave
8. examined `Local State` for `expires_at`
9. confirmed `expires_at` was set to `4-20`
10. adjusted system date to `March 22, 2023`
11. relaunched Brave
12. clicked on the `VPN` button in the toolbar
13. confirmed I saw the new `Session expired` dialog
14. clicked on the `Brave Account` link
15. confirmed it loaded `https://account.brave.com` in a new tab

`system date 4/22` | `Session-expired dialog`
----------|----------
![image (1)](https://user-images.githubusercontent.com/387249/226448405-b9f4b329-b1d4-443a-b7c2-19d79011445c.png) | ![image](https://user-images.githubusercontent.com/387249/226448410-770bdba5-846f-4c86-9abd-636ab658ec8d.png)

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 


Brave | 1.49.128 Chromium: 111.0.5563.110 (Official Build) (64-bit)
-- | --
Revision | 3da375c9e9e5ad9b556af5df708a6e6c01d8cfb1-refs/branch-heads/5563@{#1202}
OS | Windows 10 Version 22H2 (Build 19045.2728)

### Steps:
1. installed `1.51.47`
2. launched Brave
3. purchased and configured VPN
4. connected to `BraveVPN`
5. confirmed `status` of `paid` in `Local State`
6. clicked `Cancel plan` on `account.brave.com`
7. shut down Brave
8. examined `Local State` for `expires_at`
9. confirmed `expires_at` was set to `4-20`
10. adjusted system date to `March 22, 2023`
11. relaunched Brave
12. clicked on the `VPN` button in the toolbar
13. confirmed I saw the new `Session expired` dialog
14. clicked on the `Brave Account` link
15. confirmed it loaded `https://account.brave.com` in a new tab
16. changed system date back to current
17. relaunched Brave
18. confirmed I was connected to `Brave VPN`

`Canceled` status | `expires_at`
-------------------|-------------


system date `4/22` | `Session-expired` dialog
----------|--------------------------


system date `5/11` | `Buy/Already-purchased VPN?` dialog
--------------------|------------------------------------------

system date `current` | `Connected` dialog
----------------------|----------------------

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.49.128 Chromium: 111.0.5563.110 (Official Build) (x86_64)
-- | --
Revision | 3da375c9e9e5ad9b556af5df708a6e6c01d8cfb1-refs/branch-heads/5563@{#1202}
OS | macOS Version 11.7.4 (Build 20G1120)
