### ISSUE TITLE
Searching or opening pages through omnibox does not trigger events for user activity

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#28826]
The user activity is not increased as there is no events triggered when searching or opening pages through URL bar

## Steps to reproduce 

1. Clean profile
1. Enable rewards and ads
1. Wait for unblinded tokens refill
1. open a NTP
1. Search for `test` through omnibox (url address bar)

## Actual result 
Events are triggered and User activity is not increased

## Expected result
Events are triggered and User activity is increased

## Issue reproduces how often 
Easily reproduced

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Tablet
   - Android version: 11
   
## Brave version

Brave v1.48.171 on Lenovo TB-8506FS (Android 11.0)

Also reproducible on 
Brave v1.48.171 on Samsung Galaxy M21 (Android 12.0)

cc  @tmancey @aseren

**Comment by kjozwiak** [comment]
The above requires `1.49.124` or higher for `1.49.x` verification 👍
