### ISSUE TITLE
a-c table not being updated correctly

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#2882]
## Description 
Updating from 0.58.18 to 0.58.20 appears to keep the Auto Contribute table intact. However, once you start visiting sites, you'll notice that the a-c table isn't being updated properly. For example, the first site you visit which meets criteria to be added to the table (regardless of whether it was already in the table previously), is listed at 100%. If you visit a site that was already in the table, you will see two listings for that site. It seems like your already existing sites (prior to update) don't appear to be taken into account - it's like you started with a completely clean table.

## Steps to Reproduce

   1. Have a profile with rewards data from 0.58.18.
   2. Update to 0.58.20 (I can only update on `test` channel, so I swapped the .app files on mac)
   3. Launch 0.58.20 and open brave://rewards page. You will see that your a-c table looks intact.
   4. Visit a site that isn't already in the table so that it meets minimum criteria.
   5. Go back to brave://rewards.
   6. Site is listed first at 100% and already existing sites remain displayed in table
![screen shot 2019-01-09 at 5 09 15 pm](https://user-images.githubusercontent.com/28145373/50932478-bd1a0f00-1433-11e9-9a9d-dc0dda8a4554.png)

## Actual result:
When you continue to visit sites, some already in table and some not, you will see that your % values don't add up. Your already existing sites (prior to update) don't appear to be taken into account - it's like you started with a completely clean table. Below I visited a site which was already in the table. You'll see that it gets added a second time:
![ac-table](https://user-images.githubusercontent.com/28145373/50932556-fa7e9c80-1433-11e9-9294-325649858078.gif)

## Expected result:
Existing sites should not be ignored and should be taken into account for table entries and % values

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.58.20 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information
cc @brave/legacy_qa for verification on other platforms
cc @rebron @NejcZdovc @mandar-brave

**Comment by kjozwiak** [comment]
@LaurenWags I couldn't reproduce this on clean/new profiles on `Win 10` and `macOS 10.14.2`. Example:

![updateactable](https://user-images.githubusercontent.com/2602313/50946289-7d204f80-1466-11e9-8028-bc29aaf2a120.gif)

From the looks of the gif that you added, looks like there's ~41 websites in the table. Was this an old profile or a new one that you generated and loaded 41 websites? Can you reproduce with a new profile? I basically went through the following:

* installed `0.58.18`, enabled `brave://rewards` and loaded a few websites
* removed the old installation (kept the profile) and installed `0.58.20`
* visited several new websites which were correctly calculated
* visited websites that were already in the table and those were updated with the new %

Maybe I'm doing something wrong? But I couldn't reproduce. Maybe @GeetaSarvadnya & @srirambv will have better luck once they're online.

**Comment by srirambv** [comment]
I couldn't reproduce on Linux as well. Here's the steps that I followed

* Clean profile on `0.58.18`
* Enable rewards and visited a few sites to add in a-c list
* Upgraded via command line to `0.58.20`
* Ensured a-c list remained intact
* Visited a few new sites, a-c list got updated correctly
* Visited sites that were already in the a-c list before upgrade, % got calculated correctly, no duplicate entries were added for those sites

**Comment by GeetaSarvadnya** [comment]
Could not reproduce the issue on Windows 10 x64. Followed the below steps
1. Clean profile 0.58.18
2. Enable Rewards through rewards panel
3. Added few sites to A-C table and close the browser
4. Upgraded profile to 0.58.20 (Previous version ledger data is retained after upgrade)
5. Added new site to A-C table, verified the  % attention value calculated correctly.
2. Added a site which is already added in ac table (step 3), verified the updated new % attenstion value.

**Comment by NejcZdovc** [comment]
@GeetaSarvadnya basically you need to have all sites in Dec and then just add one in Jan and you will have it 100%

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.58.21 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Mac OS X

* Verified with following STR:
Used profile with Rewards Data from Dec 2018
Launched with 0.58.20
Visited a couple of sites (google.com and DDG)
Saw a-c % values start over (google+ddg=100%)
Closed Brave, relaunched profile with 0.58.21
Visited a site for minimum amount of time
Reviewed a-c table.
Verified % values were back to normal, all values added up to 100%
However, DDG was still listed twice. Logged https://github.com/brave/brave-browser/issues/2911 for this.

**Comment by GeetaSarvadnya** [comment]
Verified the issue on Windows 10 x64 - Followed below steps
1.	Clean profile 0.58.20
2.	Add two sites to A-C table (for my test I have added brianbony.com and nytimes)
3.	Close the browser and set the Month and year as Dec 2018 for both sites ( I have set this date in publishers_info_db) 
 
![publishers_info_db_1](https://user-images.githubusercontent.com/38657976/51023431-eb6f2a00-15ac-11e9-9e61-426424658da5.png)


4.	Upgrade the profile with 0.58.21
5.	Add new site to A-C table (Added CNN.com)
6.	Viewed A-C table (% values added up to 100% for 3 sites)
7.	Visit the site which is already added to A-C table in 0.58.20 (in my tc I have added brianbondy.com again in 0.58.21)
8.	Viewed A-C table
 
![0 58 21](https://user-images.githubusercontent.com/38657976/51023449-f6c25580-15ac-11e9-87b4-a68ce12837aa.png)


Publisher_info_db:
 
![publishers_info_db_2](https://user-images.githubusercontent.com/38657976/51023457-fb870980-15ac-11e9-8d91-71495171104c.png)
@NejcZdovc Can you verify the steps and let me know. Is this the correct way to test this defect.
@LaurenWags can you please verify steps and let me know if i have missed anything.

**Comment by NejcZdovc** [comment]
@GeetaSarvadnya steps looks good to me
