### ISSUE TITLE
Brave can't change to another language on Android 13 

### ISSUE THREAD

**Issue by ChowMein47** [brave/brave-browser#28822]
## Description  
Currently my phone default language is English. I want to change brave language to Indonesian but can't change it and it always reverts to English following the device default language

## Steps to reproduce 

   1. Open Brave
   2. Go to settings, choose languages and set to another language  
   3. Restart 

## Actual result  
Still stuck in English following current device language 

## Expected result
The language should be change after restart Brave Browser

## Issue reproduces how often  
easily 

## Version/Channel Information:
 I tested on Stable 

- Can you reproduce this issue with the current Play Store version? YES
- Can you reproduce this issue with the current Play Store Beta version? -
- Can you reproduce this issue with the current Play Store Nightly version?-

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Realme 9 Pro
   - Android version: 13

**Comment by YellowStar11** [comment]
@bsclifton Can you take a look this??

**Comment by YellowStar11** [comment]
@srirambv can you check this plz?

**Comment by apolymen** [comment]
Same here.
Android 13, phone language Greek, changing Brave language to English reverts back to Greek after restart.

**Comment by jagdishveera** [comment]
Hello,
This issue is specific to Android 13 OS and is working fine in other OS.
Issue is happening because android added new feature Per-app language preferences and only that app which are added in language section will be able to change the language.
May you please fix this issue as language change is not working in my device.
Thanks

**Comment by FelipeTankian** [comment]
Hi, i have the same issue here on
Brave 1.60.125, Chromium 119.0.6045.199
for a device
Samsung SM-G985F,
exynos990,
Android 13 (Build/TP1A.220624.014).

**Comment by deeppandya** [comment]
Hey guys, just want to give you an update on the issue. I am actively looking into it. And planning to include the fix for the 1.64 release. Please stay tuned for the update.

**Comment by deeppandya** [comment]
@ChowMein47 @FelipeTankian @jagdishveera we have resolved the issue in latest nightly.

**Comment by kjozwiak** [comment]
The above requires `1.64.120` or higher for `1.64.x` verification 👍 @Uni-verse @hffvld lets make sure that the above hasn't regressed older `Android` versions (`Android 12` or lower including `Android 8`).

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy Tab S7` using version: 

```
Brave	1.64.122 Chromium: 123.0.6312.122 (Official Build) (64-bit) 
Revision	a5b964f45dca7b87fc0f2adf2660d6fd6a6608b8
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

Using Steps to Reproduce in https://github.com/brave/brave-browser/issues/28822#issue-1604968399:

- Ensured language is not changed after switching to another language and restarting.
- Ensured changing back to default language works.

Example | Example | Example
-|-|-
![Screenshot 2024-04-11 at 10 21 24 AM](https://github.com/brave/brave-browser/assets/17885425/a849a432-9917-446b-9831-8e5ba8b739c3) | ![Screenshot 2024-04-11 at 10 22 14 AM](https://github.com/brave/brave-browser/assets/17885425/6e445a90-cb37-49f2-96e2-2fdca86770fb) | ![Screenshot 2024-04-11 at 10 22 27 AM](https://github.com/brave/brave-browser/assets/17885425/7811284d-33e7-4fb9-9455-b5711a461710)

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version: 

```
Brave	1.64.122 Chromium: 123.0.6312.122 (Official Build) (64-bit) 
Revision	a5b964f45dca7b87fc0f2adf2660d6fd6a6608b8
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

Using Steps to Reproduce in https://github.com/brave/brave-browser/issues/28822#issue-1604968399:

- Ensured language is not changed after switching to another language and restarting on fresh and upgraded profiles.
- Ensured changing back to default language works.

Example | Example
-|-
![Screenshot 2024-04-11 at 10 30 40 AM](https://github.com/brave/brave-browser/assets/17885425/7613c167-6efd-455a-907c-7f05a45684b2) | ![Screenshot 2024-04-11 at 10 31 32 AM](https://github.com/brave/brave-browser/assets/17885425/1cd46833-f9d0-419a-9acf-8c5efcde673f)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 2 XL` running `Android 11` using the following build(s):

```
Brave | 1.64.122 Chromium: 123.0.6312.122 (Official Build) (64-bit)
-- | --
Revision | a5b964f45dca7b87fc0f2adf2660d6fd6a6608b8
OS | Android 11; Build/RP1A.201005.004.A1; 30; REL
```

**`Example`** | **`Example`** | **`Example`**
----------------|----------------|---------------
![Screenshot_20240411-172243](https://github.com/brave/brave-browser/assets/2602313/94335ffe-3361-4337-9000-aebe8c92f3bd) | ![Screenshot_20240411-172305](https://github.com/brave/brave-browser/assets/2602313/46e6bff5-f969-4074-b1f3-0fa7c7c56c5d) | ![Screenshot_20240411-172315](https://github.com/brave/brave-browser/assets/2602313/54ea59f1-c1d3-479b-a73c-140eedbb2e21)

**Comment by jagdishjnu08** [comment]
Before this fix , it was asking for restart of the browser.
Now the brave setting fragment is getting restart and it does not ask for restart the browser.
Just a question.
Is this change in behavior okay?
Thanks

**Comment by bsclifton** [comment]
cc: @deeppandya on above question

**Comment by deeppandya** [comment]
@jagdishjnu08 it would ask you to restart the app if the selected language is not available to switch right away. if you are using a new language, it would fetch the language package and ask you to restart the app to apply the change.

**Comment by jagdishjnu08** [comment]
PFA
https://github.com/user-attachments/assets/c60c23bd-0ff5-4301-9096-2bf32fdae379
Thanks
