### ISSUE TITLE
Add a time to read estimate 

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#28827]
## Description 

Add a time to read estimate for articles in speedreader mode. The estimate should be grouped with the author and article date and time information and Time = ceil (words / average words pre minute) and 265 words per minute 

## Design/Expected result:

<img width="893" alt="Screenshot 2023-03-01 at 7 19 11 AM" src="https://user-images.githubusercontent.com/5951041/222183575-f3c81258-d0ce-4878-8000-22f662a78d05.png">

## Brave version (brave://version info)

Targeting 1.51.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.51.77 Chromium: 112.0.5615.49 (Official Build) beta (64-bit)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Windows 10 Version 22H2 (Build 19045.2788)

### Steps:
1. installed `1.51.77`
2. launched Brave
3. loaded `https://www.cbsnews.com/sanfrancisco/news/earthquake-mangitude-4-6-hollister-tres-pinos-san-benito-county/`
4. loaded `https://www.whitehouse.gov/briefing-room/speeches-remarks/2023/03/28/remarks-by-president-biden-on-investing-in-america/`
5. loaded ` https://www.euronews.com/my-europe/2023/04/04/a-new-era-begins-as-finland-becomes-natos-newest-member`
6. enabled Speedreader mode for each article


#### Confirmed the Speedread articles have a stopwatch + reading-time-estimate (relative to the length of the article, in words) below or beneath the timestamp

cbsnews.com | whitehouse.gov | euronews.com
---------------|-------------------|-----------------
![image](https://user-images.githubusercontent.com/387249/229942090-ac6c606a-f476-4d3a-b83c-6103236542e5.png) | ![image](https://user-images.githubusercontent.com/387249/229942475-6f750039-d8b4-48ae-9a0d-900113eb7319.png) | ![image](https://user-images.githubusercontent.com/387249/229942931-e7063b9c-d9c7-48ff-aedc-fafe57a1caad.png)
