### ISSUE TITLE
Down Arrow Key does not scroll page.

### ISSUE THREAD

**Issue by Carandiru0** [brave/brave-browser#28820]
## Description 
Pressing the down arrow key does not scroll the page. It's almost as if I have to set focus with a mouse click first (sometimes).
So the down arrow key does *nothing* when I press it (often), however if focus is set sometimes it works.
Scrolling the page with the mouse wheel works, however if I scroll for a long time with the mouse and then decide for some reason to adjust my posture and use the keyboard only, press the down arrow key and what does it do? It scrolls up to somewhere the start of the page! 

I do not believe this is the intended behavior designed for user input.

Should be a really simple fix. **When ever the down key or up key is pressed, scroll the page relative to the current position appropriately.**

No exceptions.

## Steps to Reproduce

   1.  Outlined the steps above.
   2. press the down key
   3. observe behavior 

## Actual result:
Down key does not respond. Down key scrolls up to somewhere near at the start of the page.

## Expected result:
Down key scrolls down always. Focus does not need to be set if the user is already interacting with the browser (which is in focus).

## Reproduces how often: 
 Always, however various unexpected response to input does not always produce the same problem.

## Brave version (brave://version info)
Latest Updated Version of Brave

## Version/Channel Information:
All Versions.

- Can you reproduce this issue with the current release? Yes.
- Can you reproduce this issue with the beta channel? idk.
- Can you reproduce this issue with the nightly channel? idk.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no.
- Does the issue resolve itself when disabling Brave Rewards? no.
- Is the issue reproducible on the latest version of Chrome? idk.

## Miscellaneous Information:
For someone on the brave team with working knowledge of the large codebase this should be a very simple bugfix. I hope it is seen
with high priority, even though it's only a Usability Issue.

**Comment by bsclifton** [comment]
@Carandiru0 the browser has to have focus for the arrow key to work. 

If you do already have the focus inside a web page in the browser it depends on what the page is showing. Right now, I'm focused into a textbox and pressing up and down arrow keys moves the caret up or down in the text box.

You should be able to see a focus ring around the element that is focused and you can use TAB to cycle forward and Shift+TAB to cycle backwards through the focus elements. I would recommend doing that until pressing down arrow key works
