### ISSUE TITLE
Update column width for speedreader/distilled articles

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#28828]
## Description 

Current width for speedreader/distilled articles are too wide and over 75 characters. Column width should be at a maximum 75 characters to improve readability.

## Design/Expected result:

![image-1](https://user-images.githubusercontent.com/5951041/222186351-ca51b707-4c15-460b-a5b4-4c71407ce8a7.png)

## Currently in release for reference: 

![brave_screenshot_www nytimes com](https://user-images.githubusercontent.com/5951041/222186537-ed6ab270-ec72-4477-a61a-cf07baa2f92f.png)

## Brave version (brave://version info)

Targeting 1.51.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a 
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.51.77 Chromium: 112.0.5615.49 (Official Build) beta (64-bit)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Windows 10 Version 22H2 (Build 19045.2788)

### Steps:
1. installed `1.51.77`
2. launched Brave
3. loaded `https://www.whitehouse.gov/briefing-room/speeches-remarks/2023/03/28/remarks-by-president-biden-on-investing-in-america/`
4. loaded `https://www.cbsnews.com/sanfrancisco/news/earthquake-mangitude-4-6-hollister-tres-pinos-san-benito-county/`
5. enabled `Speedreader` mode
6. checked column width/margins
7. compared to `1.49.130`

#### Confirmed <75 characters per line (68 on the first line in the CBSNews article) in `1.51.x`; confirmed previous behavior of >75 (83 in the same example)

`cbsnews.com/...`

`1.51.77` | `1.49.130`
----------|-----------
![image (5)](https://user-images.githubusercontent.com/387249/229945168-0939770c-98b6-4bc4-acd7-34156d627c54.png)! | ![image (4)](https://user-images.githubusercontent.com/387249/229945414-c2cbcaf4-bb73-46d6-995b-22045d753133.png)

`whitehouse.gov/...`

`1.51.77` | `1.49.130`
----------|-----------
![image (6)](https://user-images.githubusercontent.com/387249/229945281-fdc75427-29ee-4a7e-8dc3-1a04fa8f3a80.png) | ![image (7)](https://user-images.githubusercontent.com/387249/229945336-209b601e-8c02-4939-9d9e-7567bf424a8f.png)

**Comment by QS0x01** [comment]
Oh no.
Don't you think it is a waste of page screen?
