### ISSUE TITLE
Invalid asset highlighted on Buy and Deposit

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#28829]
## Description 

Mostly Solana assets are being selected irrespective of selected asset chain.

[invalid-selected-deposit-asset.webm](https://user-images.githubusercontent.com/11755381/222191253-940b5643-23b3-4575-928c-26eaab080d65.webm)

## Expected result:
Should select the correct asset with chain

## Reproduces how often: 

Easy

## Version/Channel Information:

- Can you reproduce this issue with the current release? Y
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? Y

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/26246#issuecomment-1522856327

**Comment by srirambv** [comment]
Removing `OS/Android` label as this is desktop only. Android has a different flow on Buy screen as of now.
