### ISSUE TITLE
Clear notifications from BAT logo

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#2883]
There are consistent reports regarding notification from BAT logo not clearing. This is creating a ton of user feedback re: annoyance of the user needing to take action but there is lack of clarity on taking action OR that notification does not clear irrespective of taking action.

Known issue-1: Grant is available, bat logo is set. User clicks logo but at click grants are not available anymore - it is not clear to the user what triggered the notification
Solve-1: Can we increase checks for grants availability and remove notification if grant server has no more grants. Ideally, the system should do this every hour.

Known issue-2: when notifications for grant-server not available or grant can't be claimed, there is a missing explicit action (Close, OK)
Solve-1: Can we make the notification close buttons larger and bolder?
Solve-2: Can we add a button like OK to ensure explicit action against notifications

Default Solve:
We can have buttons for user to take actions but the notification itself needs to be cleared 

A. When a user sees any related notification or takes action against it
B. even if they haven’t seen it when it expires (in case of grants not available, clear notification as well)

cc @davidtemkin @LaurenWags @jenn-rhim  @bradleyrichter for more situations detail

**Comment by NejcZdovc** [comment]
@emerick could you take this one?

**Comment by NejcZdovc** [comment]
+1 from https://github.com/brave/brave-browser/issues/2774

**Comment by tuxracer** [comment]
Is the BAT logo able to be hidden / disabled altogether?

**Comment by NejcZdovc** [comment]
@tuxracer we have this issue tracking this problem https://github.com/brave/brave-browser/issues/1475

**Comment by sobolevn** [comment]
I also had this issue in https://github.com/brave/brave-browser/issues/1475#issuecomment-444780997 And I also want to disable it completely 🙂

**Comment by LaurenWags** [comment]
+1 from https://community.brave.com/t/cant-acces-wallet/42593 - user has a notification for unable to contribute due to lack of funds, and clicking on the X does not close this notification.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.59.31 Chromium: 72.0.3626.71 (Official Build) (64-bit)
-- | --
Revision | f52ccad2a6a3c65fc9e0c591a517ceab1198dac0-refs/branch-heads/3626@{#763}
OS | Linux

* Verified test plan from https://github.com/brave/brave-core/pull/1424

**Comment by kjozwiak** [comment]
Looks like this fixed the issue I was having on my personal `dev` install. I had 4 notifications but couldn't close three of them due to the third notification not being dismissible via the `OK` button. Once I updated to `0.60.17 Chromium: 72.0.3626.64`, I was able to dismiss all my notifications without any issues 👍
