### ISSUE TITLE
Warn users when diagnostic id v4 GUID is invalid

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#28830]
Follow up to https://github.com/brave/brave-browser/issues/25649
Currently we silently fail when GUID is invalid.
We should give warning that user made a mistake when entering GUID.

## Steps to Reproduce

1. Clean profile
1. Enable rewards and ads
1. Wait for unblinded tokens refill
1. Open `brave://rewards-internals > Ads diagnostsics`
1. Type `fail` into `Diagnostic id`

## Actual result:

no warning that the diagnostic id is invalid
![image](https://user-images.githubusercontent.com/34715963/222207533-6ca43391-29d5-4d4d-bd4c-a12f55af6d5a.png)

## Expected result:
warning that the diagnostic id is invalid, for example the text field may flash red and give a error underneath 

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

Brave | 1.49.110 Chromium: 110.0.5481.177 (Official Build) beta (64-bit)
-- | --
Revision | f34f7ab2d4ca4ad498ef42aeba4f4eb2c1392d63-refs/branch-heads/5481@{#1239}
OS | Ubuntu 18.04 LTS

cc @tmancey @aseren

**Comment by tmancey** [comment]
This is intentional so that non Brave employees are unlikely to use this feature. Only GUIDs provided by us to Brave employees will be used. Thanks
