### ISSUE TITLE
Selected currency not updating when user goes to select token step

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#28845]
Issue described in [slack](https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1676303656313639)

**Comment by srirambv** [comment]
Verification passed on  

Brave | 1.51.109 Chromium: 113.0.5672.63 (Official Build) (64-bit)
-- | --
Revision | `0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}`
OS | Windows 11 Version 22H2 (Build 22621.1555)

- Verified steps from [ brave/brave-core#17442](https://github.com/brave/brave-core/pull/17442)
- Verified correct fiat currency is shown when on Buy token widget on onramp page

https://user-images.githubusercontent.com/17010094/235600799-dfe95101-6ba0-4135-9ae2-931fed9f570a.mp4
