### ISSUE TITLE
Wallet Permission Duration (Desktop UI) 

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#28841]
Parent issue: https://github.com/brave/brave-browser/issues/28840
Pass user chosen lifetime option (kPageClosed, k24Hours, k7Days and kForever) to new mojo `PanelHandler::ConnectToSite` API.
QA should at least test `kPageClosed` and `kForever`

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.51.103 Chromium: 112.0.5615.165 (Official Build) beta (64-bit) 
-- | --
Revision | `c262f36e6b1d711ee42d4fbe1343b49960593f18-refs/branch-heads/5615@{#1297}`
OS | Linux

- Verified steps from [brave/brave-core#17700](https://github.com/brave/brave-core/pull/17700)
- Verified permission duration is shown before connecting to Dapp
- Verified permission is removed when the dapp is closed when set to `Until I close the site`
- Verified for both Solana and Ethereum Dapps

https://user-images.githubusercontent.com/17010094/234502436-27797986-26cc-4178-933d-9158808e3d33.mp4


---------------------

**Verification passed on**

Brave | 1.51.103 Chromium: 112.0.5615.165 (Official Build) beta (64-bit)
-- | --
Revision | `c262f36e6b1d711ee42d4fbe1343b49960593f18-refs/branch-heads/5615@{#1297}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from [brave/brave-core#17700](https://github.com/brave/brave-core/pull/17700)
- Verified permission duration is shown before connecting to Dapp
- Verified permission is removed when the dapp is closed when set to `Until I close the site`
- Verified for both Solana and Ethereum Dapps

https://user-images.githubusercontent.com/17010094/234502004-7ea558d3-4928-4ec7-ae1a-f01ba5615d64.mp4


---------------------

**Verification passed on**

Brave | 1.51.103 Chromium: 112.0.5615.165 (Official Build) beta (arm64)
-- | --
Revision | `c262f36e6b1d711ee42d4fbe1343b49960593f18-refs/branch-heads/5615@{#1297}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#17700](https://github.com/brave/brave-core/pull/17700)
- Verified permission duration is shown before connecting to Dapp
- Verified permission is removed when the dapp is closed when set to `Until I close the site`
- Verified for both Solana and Ethereum Dapps

https://user-images.githubusercontent.com/17010094/234501701-1333fae6-2ef5-45ac-8067-53ec44fd5af1.mov
