### ISSUE TITLE
German translation issue

### ISSUE THREAD

**Issue by DasCanard** [brave/brave-browser#28852]
## Description 

In [this Line](https://github.com/brave/brave-core/blob/24619d20ce8f69fa81b1a10c2658cc353eeb0cfd/app/resources/brave_generated_resources_de.xtb#L146) the word "Mouse" needs to be replaced with "Maus".

## Steps to Reproduce
![image](https://user-images.githubusercontent.com/17070204/222429640-fe8e9ac3-ca8c-4fe2-a544-b1ef2c53b50d.png)

## Actual result:
![image](https://user-images.githubusercontent.com/17070204/222429689-4b41adbb-15d4-4ad3-94a3-a9099594f7b2.png)

## Expected result:

"Wenn die Maus darüber ist"

## Brave version (brave://version info)

1.48.171 Chromium: 110.0.5481.177 (Offizieller Build) (64-Bit) 

## Version/Channel Information:

Stable Channel

**Comment by rebron** [comment]
cc: @mkarolin

**Comment by kjozwiak** [comment]
The above requires `1.49.120` or higher for `1.49.x` verification 👍
