### ISSUE TITLE
Remove note about potential lost BAT from Reset Rewards modal

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#28864]
Remove the "Note:" section from the Reset Rewards modal:

![image_from_ios](https://user-images.githubusercontent.com/5033691/222514178-45f80e17-66a2-40de-9095-a05045a77beb.jpg)

**Comment by emerick** [comment]
cc: @Miyayes

**Comment by kjozwiak** [comment]
The above requires `1.50.94` or higher for `1.50.x` verification 👍
