### ISSUE TITLE
Site specific site details page in settings is blank

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#28861]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/28773.

Using STR from above issue, the site specific "Site Settings" page doesn't display any settings, that section is blank.

Works on C110 (`1.49.116 Chromium: 110.0.5481.177`), does not work on C111 (`1.49.117 Chromium: 111.0.5563.50`).

## Steps to Reproduce

   1. Clean profile, relaunch to pull griffin
   2. Open a site (I used brave.com)
   3. Click on the lock icon in URL bar
   4. Select "Site settings" from drop down
   5. Page you are navigated to doesn't show any site settings (the middle part is blank), but the left nav menu displays fine.

## Actual result:

1.49.117

<img width="1446" alt="Screen Shot 2023-03-02 at 10 01 31 AM" src="https://user-images.githubusercontent.com/28145373/222465960-529427eb-7602-4532-afaa-b639312b41a1.png">

## Expected result:

1.49.116 (except the missing setting labels should be shown, this is what was logged under #28773)

<img width="1252" alt="Screen Shot 2023-03-02 at 10 02 34 AM" src="https://user-images.githubusercontent.com/28145373/222466061-a8404323-c9f4-49dc-9778-7c8208fa2942.png">

## Reproduces how often: 

easily

## Version/Channel Information:

- Can you reproduce this issue with the current release? 1.48.x no, 1.49.x yes
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron @emerick

**Comment by LaurenWags** [comment]
Devtools console shows the following error (thanks for the pointer here @emerick!)

<img width="1453" alt="Screen Shot 2023-03-02 at 10 12 07 AM" src="https://user-images.githubusercontent.com/28145373/222469265-f561de0f-0290-4624-8185-f029ec43a0b2.png">

```
Uncaught ReferenceError: I18nBehavior is not defined
    at site-details (settings.js:2816:282)
    at addBraveTemplateModifications (shared.rollup.js:495:1037)
    at SiteDetailsElement.BravePolymer_PrepareTemplate (shared.rollup.js:495:6516)
    at SiteDetailsElement._finalizeClass (polymer_bundled.min.js:1:47261)
    at SiteDetailsElement.finalize (polymer_bundled.min.js:1:44964)
    at HTMLElement._initializeProperties (polymer_bundled.min.js:1:48728)
    at new <anonymous> (polymer_bundled.min.js:1:16820)
    at new <anonymous> (polymer_bundled.min.js:1:32678)
    at new <anonymous> (polymer_bundled.min.js:1:48600)
    at new WebUiListenerMixin (shared.rollup.js:499:112)
```

**Comment by kjozwiak** [comment]
Closing as https://github.com/brave/brave-core/pull/17452 was merged directly into `1.49.x`. The above requires `1.49.118` or higher for `1.49.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.49.118 Chromium: 111.0.5563.50 (Official Build) (x86_64)
-- | --
Revision | 39f3dfc5023fe60997adc4f6cf5439cfa3e6968a-refs/branch-heads/5563@{#903}
OS | macOS Version 12.6.3 (Build 21G419)
```

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.49.120 Chromium: 111.0.5563.64 (Official Build) (64-bit)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | Windows 11 Version 22H2 (Build 22621.1265)
```

Reproduced the issue using STR https://github.com/brave/brave-browser/issues/28861#issue-1606975226 in `1.49.117 Chromium: 111.0.5563.50`

![image (5)](https://user-images.githubusercontent.com/98358127/223769727-d3b69390-d53a-4634-ac33-c965639eb283.png)


#### Confirmed site specific site details page is not blank.

Example | Example
---- | -----
<img width="947" alt="image" src="https://user-images.githubusercontent.com/98358127/223769942-768d2bec-5c4e-465a-896e-17efaa370af4.png"> | <img width="955" alt="image" src="https://user-images.githubusercontent.com/98358127/223770023-bab1ea03-4dff-426a-a32e-d79e020d3e3d.png">
