### ISSUE TITLE
for Transak onramp, assets are showing up that are not supported for US users

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#28866]
## Description 

With Transak, there is an asset list for global users and then an asset list for US users. Here is the list https://docs.transak.com/docs/on-ramp-crypto-currency-coverage. right now we are showing the global list to all users.

See conversation here  https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1677758889153949

We need to find a way to show only assets that are support for US users to users that have selected USD currency.

## Steps to Reproduce

   1. 
   2. 
   3. 

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by muliswilliam** [comment]
This was fixed here: https://github.com/brave/brave-core/pull/17773

**Comment by srirambv** [comment]
@muliswilliam Please add appropriate QA label for this. Adding it to 1.51.x as the linked PR is set for that milestone

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.51.109 Chromium: 113.0.5672.63 (Official Build) (64-bit)
-- | --
Revision | `0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- tokens that only had Transak as provider is not shown in the asset list on Buy screen.

https://user-images.githubusercontent.com/17010094/235695977-3e6931de-0878-438e-ab9f-c5b4e23ae014.mp4

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.51.109 x64 build
- Verified Transak is shown only for supported tokens in the US

https://user-images.githubusercontent.com/17010094/235869510-7b96d710-ead9-44bb-9b79-7f1ed979a6d4.mp4
