### ISSUE TITLE
News articles opened in new tab always get grouped

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#28868]
## Description 
After disabling tab groups, news articles always open in grouped tabs. 

## Steps to reproduce 

   1. Install 1.49
   2. Enable news
   3. Long press on an article on NTP and open in new tab
   4. Now disable tab groups, restart app
   5. long press on an article on NTP and open in new tab

## Actual result 
Tabs are grouped

## Expected result
Should not be grouped

Example | Example
-|-
![screenshot-1677790234039](https://user-images.githubusercontent.com/17885425/222551539-5fb5e3d1-0ef0-4eb2-adfa-a11f11a6859b.png) | ![screenshot-1677790320853](https://user-images.githubusercontent.com/17885425/222551550-f15626d4-de3f-4de7-9068-49add6d5a789.png)

## Issue reproduces how often 
Easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? N/A
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung GS 21
   - Android version: 13
   
## Brave version
`1.49.117, Chromium 111.0.5563.50`

**Comment by vlad-hoff** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 [panther_beta-user 14 UPB2.230407.019 release-keys]
Brave build: 1.53.83
Chromium: 114.0.5735.110 (Official Build) beta (64-bit)
Revision: 1c828682b85bbc70230a48f5e345489ec447373e-refs/branch-heads/5735_90@{#13}
```
---------------------------

**STEPS:**
1. Launch Brave
2. NTP > Show Brave News
3. Tap and hold on an article on NTP News > Open in New Tab > Verify
4. Three-dot Menu > Settings > Appearance > Set `Only open links in current tab group` to OFF
5. On NTP News tap and hold on an article > Open in New Tab > Verify

**ACTUAL RESULTS:**
- Verified that news articles opened in the current tab group when `Only open links in current tab group` set to ON
- Verified that news articles opened in the new tab when `Only open links in current tab group` set to OFF

https://github.com/brave/brave-browser/assets/128532965/49ae9e7e-ec22-4324-ae51-c9f6607ceb5f
