### ISSUE TITLE
Balance or asset are not being updated correctly

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#28879]
## Description 
- Balance or asset are not being updated correctly due to getting old responses after the newer ones and updated state being overridden by the old responses.
- Assets are not updated correctly after network switching

## Actual result 

[balance-asset-issues.webm](https://user-images.githubusercontent.com/11755381/222724187-2a6a4bfd-29a6-4440-8d4d-8fbc468b3b8e.webm)

## Expected result
Balance and asset should update correctly

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Y
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version? Y

**Comment by kjozwiak** [comment]
The above requires `1.49.124` or higher for `1.49.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.49.126 x64 build
- Verified steps from [brave/brave-core#17540](https://github.com/brave/brave-core/pull/17540)
- Verified correct token balance is shown when changing network/account

Oppo Reno 5 (Android 13) | Lenovo Tab (Android 12)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/226526386-d303c063-8190-4e44-93a5-247be0573fc0.mp4> | <video src=https://user-images.githubusercontent.com/17010094/226526228-d2c322b4-0460-4ce2-8330-9480426b00c9.mp4>
