### ISSUE TITLE
Enable brave://flags/#brave-vertical-tabs in Nightly channel

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#28872]
## Description 

Enable brave://flags/#brave-vertical-tabs as default for Nightly channel

## Steps to Reproduce

   1. Go to brave://flags/#brave-vertical-tabs and check that it's selected as Default
   2. Default value should be enabled.
   3. Right click on any tab in horizontal view to see that Vertical tabs option is selected.

## Brave version (brave://version info)

1.51.x.

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.51.85 Chromium: 112.0.5615.49 (Official Build) beta (x86_64)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | macOS Version 11.7.6 (Build 20G1231)

**Comment by stephendonner** [comment]
@rebron @sangwoo108 looks like we need this enabled on `beta` channel, too, if we're to test it in `1.51.x`: https://github.com/brave/brave-core/pull/17458/files

cc @brave/qa-team and setting as `QA/Blocked` for now

**Comment by LaurenWags** [comment]
@stephendonner @rebron we should probably have a separate issue for Beta. Might as well have one for Release too.

**Comment by kjozwiak** [comment]
Going to label this as `QA/No` as the verification on `beta` will be done via https://github.com/brave/brave-browser/issues/29658 once https://github.com/brave/brave-core/pull/18065 has been uplifted into `1.51.x`.
