### ISSUE TITLE
Brave Ads notification icon is too small and almost invisible

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#2887]
## Description 

Notification icon is too small and almost invisible

## Steps to Reproduce

   1. Clean install 0.60.9
   2. Enable rewards and ads 
   3. Wait till an ad notification comes though
   4. Icon is too small on the notification 

## Actual result:

Icon on the notification is too small. Might need an appointment with ophthalmologist 

## Expected result:
No doctor appointment needed (unless really required) and icons should be large enough to fit in the ad notification

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.60.9 Chromium: 72.0.3626.28 (Official Build) dev(64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | All

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes on dev build
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
No
- Is the issue reproducible on the latest version of Chrome? 
No
### Additional Information

cc: @jsecretan @bridiver  @brave/legacy_qa

**Comment by bridiver** [comment]
Too small based on what? The spec only shows macos notifications and the icons match the specs afaik. On some (maybe all) platforms we have no control over this anyway.

**Comment by srirambv** [comment]
This is how it looks on Windows. And this is a zoomed in version of the print screen.
![image](https://user-images.githubusercontent.com/17010094/51011909-80a7f980-1580-11e9-8501-505f22450e09.png)

**Comment by bridiver** [comment]
can you take this to product? There is nothing in the spec for windows and I'm not sure if it's even possible to control the size of the icon or not on windows. Either way strictly speaking this isn't a bug, it's feature request.

**Comment by kjozwiak** [comment]
@bridiver do you know who from the product side is currently working on ads? CCing @bradleyrichter.

**Comment by tmancey** [comment]
@bridiver @kjozwiak With regards to icon size, this is not possible on macOS.

@mandar @kjozwiak Mandar is working on Ads

**Comment by kjozwiak** [comment]
@srirambv mind adding a screenshot/example of the above for Windows so @mandar-brave can visually see the issue and if we need to improve the icon sizes?

> @bridiver @kjozwiak With regards to icon size, this is not possible on macOS.

Looks like this isn't possible on macOS as per @tmancey so added the `OS/Linux` and `OS/Window` flags.

**Comment by mandar-brave** [comment]
thanks @kjozwiak 
Never seen the issue at my end on Windows to-date so must be related to some hi-res screen needs. But waiting to see screenshots and will do needful.

**Comment by srirambv** [comment]
@kjozwiak @mandar-brave screenshot is added here https://github.com/brave/brave-browser/issues/2887#issuecomment-453367842. You can see how small the Brave icon is compared to the size of the notification. This is on 125% DPI default setting on a 1920x1080(16:9) display. Pretty sure as the DPI increases the notification size increases proportionately but not the Brave icon

**Comment by mandar-brave** [comment]
@tmancey @bridiver is there a limitation with windows API? I am very sure this is not an issue with Mac as such but checking in; we can expect the image to scale proportionately as well. Thanks

**Comment by srirambv** [comment]
>The spec only shows macos notifications and the icons match the specs afaik

Specs should contain behaviour on all platforms and **not just macOS** so that these issues can be ironed out early on

**Comment by mandar-brave** [comment]
@srirambv couple things - we have been relegated to use an existing API so the spec does not "say what OS" - it is suggesting format. We are not developing a custom notification if you read the spec - we are going to use a standard chrome API that is available to us. Same will happen to local notifications on Android. The entire idea = use local system notifications.

@jsecretan the UX here will look horrible for high DIP issues; upgrading to P2 for launch

**Comment by jonathansampson** [comment]
Came here to say the same thing. Ad icons are too small on Windows. For comparison, here's a 160x160 image in a Web Notification (right) next to one of our ads today:

![image](https://user-images.githubusercontent.com/815158/54160982-ded94780-441e-11e9-9d32-75c334f64a45.png)

**Comment by srirambv** [comment]
Small icon issue on Linux as well. Compared to the size of the notification the icon is too small 
![Screenshot from 2019-04-04 16-19-45](https://user-images.githubusercontent.com/17010094/55586298-a0216f00-56f6-11e9-8c44-31fd9eafe2d4.png)

**Comment by tmancey** [comment]
See `enable_hidpi` in codebase

**Comment by tmancey** [comment]
Blocked until https://github.com/brave/brave-browser/issues/9592 is implemented

**Comment by tmancey** [comment]
Closing issue as superseded by https://github.com/brave/brave-browser/issues/9592
