### ISSUE TITLE
Use vertical Tabs + Tab Scrolling flag = Brave doesn't open

### ISSUE THREAD

**Issue by Emi-TheDhamphirInLoveUnderTheFrozenStar** [brave/brave-browser#28877]
## Description 

@sangwoo108 Brave doesn't open/breaks when when Tab Scrolling `brave://flags/#scrollable-tabstrip` flag is enabled and `Use vertical tabs` is on.
This doesn't happen when using normal horizontal tabs, so the only workaround is to switch to horizontal tabs before closing the browser, if not, then the easiest solution would be to edit the Local State file to disable the flag or edit Preferences file to disable Use vertical tabs.

## Steps to Reproduce

   1. Enable brave://flags/#scrollable-tabstrip
   2. Enable Use vertical tabs
   3. Restart
   4. Brave doesn't open.

## Brave version (brave://version info)

1.51.2 Chromium: 111.0.5563.50 (Official Build) nightly (64-bit)

**Comment by sangwoo108** [comment]
Thanks for reporting. I'll take a look ASAP.

**Comment by Ayern12** [comment]
##how can i do it...

Pada Jum, 3 Mac 2023, 18:33 Sangwoo Ko ***@***.***> menulis:

**Comment by sangwoo108** [comment]
Sorry for the inconvinience. I made a patch so that you can open browser. But scrollable tab strip flag is not fully supported yet under vertical tab strip 😥 Will take a look soonish.

**Comment by sangwoo108** [comment]
The follow-up issue is here: https://github.com/brave/brave-browser/issues/28906

**Comment by Emi-TheDhamphirInLoveUnderTheFrozenStar** [comment]
Thanks for the quick fix and your work @sangwoo108.

PS. I love the new Shared pinned tab feature. Great work there too and Vertical tabs. 😁👌

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.51.85 Chromium: 112.0.5615.49 (Official Build) beta (x86_64)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | macOS Version 11.7.6 (Build 20G1231)

### Steps:
1. installed `1.51.85`
2. launched Brave
3. opened `brave://flags`
4. confirmed `default` for `brave://flags/#brave-vertical-tabs`
5. confirmed `default` for `brave://flags/#scrollable-tabstrip`
6. enabled both of the above
7. clicked `Relaunch`
8. loaded `msnbc.com`
9. context-clicked and chose `Use vertical tabs`
10. confirmed no crash
11. loaded a few other sites and continued to use vertical tabs

#### Confirmed that vertical-tab scrolling, when enabled, no longer breaks Brave (it's known that it needs work, still)

example | example | example | example | example | example
---------|----------|---------|----------|----------|---------
<img width="1312" alt="Screen Shot 2023-04-11 at 3 35 46 PM" src="https://user-images.githubusercontent.com/387249/231305172-7e9fec2c-4014-4271-804c-0c1d6e0687ec.png"> | <img width="1312" alt="Screen Shot 2023-04-11 at 3 36 02 PM" src="https://user-images.githubusercontent.com/387249/231305179-c9410738-6caf-4b9a-a7f5-7df5efe68593.png"> | <img width="1312" alt="Screen Shot 2023-04-11 at 3 36 10 PM" src="https://user-images.githubusercontent.com/387249/231305183-655a94a1-a095-4967-a487-e3e3bff6f23f.png"> | <img width="1201" alt="Screen Shot 2023-04-11 at 3 37 47 PM" src="https://user-images.githubusercontent.com/387249/231305185-00508521-b625-4f4f-818d-0c6d7b8fd8fe.png"> | <img width="1312" alt="Screen Shot 2023-04-11 at 3 37 56 PM" src="https://user-images.githubusercontent.com/387249/231305193-1b3a0347-9d41-4552-a933-fc67eaedfdf8.png"> | <img width="1312" alt="Screen Shot 2023-04-11 at 3 40 25 PM" src="https://user-images.githubusercontent.com/387249/231305199-660f9109-d52c-466b-bcb1-960228b728de.png">
