### ISSUE TITLE
hamburger menu not visible under `brave://downloads`

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#28874]
## Description 

Hamburger menu under `brave://downloads` while using the `Light theme` isn't visible until hovering over the button. However, even when you hover over the button, the hamburger menu is still difficult to see. Most likely related to `C111`.

## Steps to Reproduce

   1. install `1.51.1 Chromium: 111.0.5563.41` (ensure the build is running on `C111`)
   2. go into `brave://downloads` and observe that the `hamburger menu` isn't visible via `light` theme.

## Actual result:

**`Example`** | **`Example`**
---------------|-------------------
![download1](https://user-images.githubusercontent.com/2602313/222645122-39ffd88b-dc58-4abf-8db8-c955224994aa.png) | ![download2](https://user-images.githubusercontent.com/2602313/222645124-fb6a8e2b-0168-4326-a3a7-8292885d6eb6.png)

## Expected result:

**`Example`** | **`Example`**
---------------|-------------------
![image](https://user-images.githubusercontent.com/2602313/222642583-1cab2d73-d60e-4134-90fd-cedba000bd63.png) | ![example](https://user-images.githubusercontent.com/2602313/222643073-e60aa513-88a7-4010-9848-50434839f50b.png)

## Reproduces how often: 

100% reproducible using the STR/Cases outlined above.

## Brave version (brave://version info)

```
Brave | 1.51.1 Chromium: 111.0.5563.41 (Official Build) nightly (64-bit)
-- | --
Revision | 976ef12907ef9b413c2d929c043307b415d27b9e-refs/branch-heads/5563@{#737}
OS | Windows 11 Version 22H2 (Build 22621.1265)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by GeetaSarvadnya** [comment]
Added `Regression` label as issue is working fine in CR 110 - 1.48.171 and reproducible only in `CR 111`

**CR 110**
![image](https://user-images.githubusercontent.com/38657976/222752694-ece7e3cf-85f7-4929-9763-00c2d6d4391d.png)

**CR 111**
![image](https://user-images.githubusercontent.com/38657976/222752872-bd03e020-4db8-4faf-bc56-2ac9dc1b3e27.png)

**Comment by kjozwiak** [comment]
The above requires `1.49.120` or higher for `1.49.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.49.120 Chromium: 111.0.5563.64 (Official Build) (64-bit)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | Windows 11 Version 22H2 (Build 22621.1265)
```

Reproduced with  `1.51.2 Chromium: 111.0.5563.50`
downloads | bookmarks
---- | -----
<img width="467" alt="image" src="https://user-images.githubusercontent.com/98358127/223763463-bd3fd9cf-dafd-4dd4-b820-bc932191a68f.png">|<img width="467" alt="image" src="https://user-images.githubusercontent.com/98358127/223763397-3be85858-c45b-4296-b7bc-6eec5ce775bb.png">


Confirmed hamburger icon is visible w/o hovering over in downloads and bookmarks page in light theme.

`Downloads`

dark theme | light theme
------ | ------
<img width="513" alt="image" src="https://user-images.githubusercontent.com/98358127/223758495-74458af8-fdef-402f-9c1c-3ecf87996601.png"> | <img width="529" alt="image" src="https://user-images.githubusercontent.com/98358127/223758689-e2ffe367-673d-4c46-8f7b-f825088cf246.png">

`Bookmarks` 

dark theme | light theme
------ | ------
<img width="589" alt="image" src="https://user-images.githubusercontent.com/98358127/223764324-f66b3648-eee6-460b-844a-c113808ef9af.png">|<img width="537" alt="image" src="https://user-images.githubusercontent.com/98358127/223759753-1c95bf28-6744-4718-a1e4-fc807088d51c.png">
