### ISSUE TITLE
Subscription `Status` and `Expires` fields are blank in Brave Firewall + VPN modal after redeeming in Android device  

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#28871]
## Description 
Noticed while testing https://github.com/brave/brave-browser/issues/25680 where Subscription Status and Expiry fields are blank in  Brave Firewall + VPN modal in Android device. However, Desktop subscription page shows expiration date (30 days) when cancelled. 

## Steps to reproduce 

   1. Purchase VPN in Prod (account.brave.com) via Desktop  
   2.  Redeem in Android Device
   3.  Enable VPN via Settings menu
   4.  Verify `Status` and `Expires` fields in Settings =>Brave Firewall + VPN modal
   
## Actual result 
`Status` and `Expires` fields are blank

<image width = "300" alt="image" src="https://user-images.githubusercontent.com/98358127/222581873-a0ecb71e-bb83-4ba6-a648-d4c840b720ea.jpg">

## Expected result
`Status` and `Expires` fields should be populated??

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version?  N/A
- Can you reproduce this issue with the current Play Store Beta version? N/A
- Can you reproduce this issue with the current Play Store Nightly version? N/A

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Galaxy A53 
   - Android version: 13
   
## Brave version
1.48.171 Chromium 110.0.5481.177

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information
 @mattmcalister @bsclifton @deeppandya 
cc: @Uni-verse @stephendonner

**Comment by deeppandya** [comment]
@MadhaviSeelam currently we show expires details only when user buys the subscription from in app purchase.

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/28910
