### ISSUE TITLE
Expose navigator.globalPrivacyControl in workers

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#28885]
Brave [already supports globalPrivacyControl](https://github.com/brave/brave-browser/issues/11917) in most situations, but `navigator.globalPrivacyControl` is not currently available in worker environments.

**Comment by pes10k** [comment]
there is also a QA test for this here https://dev-pages.brave.software/dom-properties/controlled.html

**Comment by goodov** [comment]
QA test page https://dev-pages.brave.software/dom-properties/controlled.html

check `GPC/Workers` values.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.51.77 Chromium: 112.0.5615.49 (Official Build) beta (x86_64)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | macOS Version 13.4 (Build 22F5027f)


### Steps:
1. installed `1.51.77`
2. launched Brave
3. loaded `https://dev-pages.bravesoftware.com/dom-properties/controlled.html`
4. clicked on `Run test`
5. noted the results
6. clicked on `Other site` to load `https://dev-pages.brave.software/dom-properties/controlled.html`
7. clicked on `Run test`
8. noted the results
9. compared with current `1.49.130` release

#### Confirmed we now show `true` where `null` was, for `GPC/Workers`

`1.51.77`

set 1 | set 2
------|-----
<img width="1496" alt="Screenshot 2023-04-04 at 1 48 00 PM" src="https://user-images.githubusercontent.com/387249/229918070-1f79d55f-fe0e-4923-ad94-e5bb40e49f28.png"> | <img width="1496" alt="Screenshot 2023-04-04 at 1 48 07 PM" src="https://user-images.githubusercontent.com/387249/229918076-06650fb7-9a48-41d5-939d-d1c232042e5c.png">





`1.49.130`

set 1 | set 2
------|-----
<img width="1463" alt="Screenshot 2023-04-04 at 1 48 27 PM" src="https://user-images.githubusercontent.com/387249/229917331-46802685-4c08-4366-a123-931ddd287012.png"> | <img width="1463" alt="Screenshot 2023-04-04 at 1 48 23 PM" src="https://user-images.githubusercontent.com/387249/229917376-c0d39cbf-e0ff-4806-9ac3-5b14ca0f045b.png">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED`
```
Brave | 1.51.79 Chromium: 112.0.5615.49 (Official Build) beta (64-bit)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Windows 11 Version 22H2 (Build 22621.1413)
```

### Steps:
1. installed `1.51.79`
2. launched Brave
3. loaded `https://dev-pages.bravesoftware.com/dom-properties/controlled.html`
4. clicked on `Run test`
5. noted the results
6. clicked on `Other site` to load `https://dev-pages.brave.software/dom-properties/controlled.html`
7. clicked on `Run test`
8. noted the results
9. compared with current `1.49.130` release

#### Confirmed we now show `true` where `null` was, for `GPC/Workers`


Shields Up
-----
#### Set 1

1.51.79| 1.50.114
-----|------
<img width="954" alt="image" src="https://user-images.githubusercontent.com/98358127/230484586-6e183b2d-b444-4a7f-93ab-d87fd26a93d5.png">|<img width="954" alt="image" src="https://user-images.githubusercontent.com/98358127/230484689-7ee50c85-ec33-467a-a4b0-52a45f948f5c.png">

#### Set 2

1.51.79| 1.50.114
-----|------
<img width="954" alt="image" src="https://user-images.githubusercontent.com/98358127/230486466-0c61362d-fe7b-421d-ae12-a26bdb519b3f.png">|<img width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/230486188-b97bae25-b0a8-485e-bade-43c0332129d3.png">


Shields Down
------
#### Set 1

1.51.79| 1.50.114
-----|------
<img width="956" alt="image" src="https://user-images.githubusercontent.com/98358127/230486558-e9066c2d-4da6-44b8-b838-4f5098bf9456.png">|<img width="957" alt="image" src="https://user-images.githubusercontent.com/98358127/230486629-21c75aa3-2788-4dbe-9091-02a8f0192152.png">

#### Set 2

1.51.79| 1.50.114
-----|------
<img width="955" alt="image" src="https://user-images.githubusercontent.com/98358127/230486777-61b8c93e-b856-4e4d-b38f-c0cd19e04a0d.png">|<img width="955" alt="image" src="https://user-images.githubusercontent.com/98358127/230486858-8816b676-fdc3-4144-9bc3-e7c74dfc0a81.png">

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 14` using the following build(s):

```
Brave | 1.51.107 Chromium: 113.0.5672.63 (Official Build) (32-bit)
--- | ---
Revision | 0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}
OS | Android 13; Build/UPB1.230309.014; 33; UpsideDownCake
```

### Steps:
1. installed `1.51.107 Chromium: 113.0.5672.63`
2. launched Brave
3. loaded `https://dev-pages.bravesoftware.com/dom-properties/controlled.html`
4. clicked on `Run test` while `Shields Up`
5. noted the results
6. clicked on `Other site` to load `https://dev-pages.brave.software/dom-properties/controlled.html`
7. clicked on `Run test`
8. noted the results
9. ran step 3 - 8 for `Shields Down`
10. compared with current `1.49.130` release

#### Confirmed we now show `true` where `null` was, for `GPC/Workers` for `Shields Up` and `Shields Down` and matched with expected values

Shields Up
-----

1.51.107 Chromium: 113.0.5672.63 | 1.50.121 Chromium: 112.0.5615.138
-----|------
![Screenshot_20230501-004528](https://user-images.githubusercontent.com/2602313/235408296-e0b8052c-4512-47d3-9c80-8245be7a74d4.png) | ![Screenshot_20230501-005448](https://user-images.githubusercontent.com/2602313/235408852-d97d38bf-da5c-4104-94e6-c05458a7a034.png)

1.51.107 Chromium: 113.0.5672.63 | 1.50.121 Chromium: 112.0.5615.138
-----|------
![Screenshot_20230501-004546](https://user-images.githubusercontent.com/2602313/235408301-c606d083-afe3-4914-96b0-1ac51c05c19f.png) | ![Screenshot_20230501-005453](https://user-images.githubusercontent.com/2602313/235408861-3eead68a-6f22-46b9-9ed7-b972f23e1ad7.png)

Shields Down
------

1.51.107 Chromium: 113.0.5672.63 | 1.50.121 Chromium: 112.0.5615.138
-----|------
![Screenshot_20230501-004600](https://user-images.githubusercontent.com/2602313/235408371-f2054181-eb79-45b7-b38f-a0086e85dc34.png) | ![Screenshot_20230501-005508](https://user-images.githubusercontent.com/2602313/235408874-d67e4e18-2461-4f9b-885f-b7ad6cee0cb5.png)

1.51.107 Chromium: 113.0.5672.63 | 1.50.121 Chromium: 112.0.5615.138
-----|------
![Screenshot_20230501-004622](https://user-images.githubusercontent.com/2602313/235408379-364ec804-090a-4297-896f-1bd59bc87302.png) | ![Screenshot_20230501-005518](https://user-images.githubusercontent.com/2602313/235408883-b58558a1-0e4c-4f44-9c06-a7dd19c77cce.png)
