### ISSUE TITLE
support "Copy clean link" from macOS app menu when selecting text URL on page (not link from omnibox) - Follow up to #27676

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#28880]
## Description 

Follow up to https://github.com/brave/brave-browser/issues/27676

Above issue requests "When users select URL on the web page, text editing menu items are enabled, such as "copy", and "paste" and etc. In this case, we might be able to insert "Copy clean link"".

This is specific to macOS and their app menu.

See discussion under https://bravesoftware.slack.com/archives/CKNHM4RTK/p1677768069627199.

## Steps to Reproduce

   1. Using 1.49.117, clean profile
   2. Navigate to [google.com](http://google.com/)
   3. In the search box, enter `www.brave.com`
   4. On resulting search page, highlight `www.brave.com` in the search box
   5. Click on the Edit menu item from macOS app menu
---> would like to see "Copy clean link" from Edit menu in this case, but it does not show.

## Actual result:

<img width="721" alt="1" src="https://user-images.githubusercontent.com/28145373/222733102-c830e99b-1a2d-4240-94d4-b553eaa5fc8a.png">

## Expected result:

to see "Copy clean link"

<img width="243" alt="Screen Shot 2023-03-03 at 8 33 42 AM" src="https://user-images.githubusercontent.com/28145373/222733271-d80a8f5d-65dd-4831-b5a5-abe6ef74b7e4.png">

## Reproduces how often: 

easily

## Brave version (brave://version info)

```
Brave | 1.49.117 Chromium: 111.0.5563.50 (Official Build) (x86_64)
-- | --
Revision | 39f3dfc5023fe60997adc4f6cf5439cfa3e6968a-refs/branch-heads/5563@{#903}
OS | macOS Version 12.6.3 (Build 21G419)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron @sangwoo108

**Comment by spylogsster** [comment]
Decided to close as wontfix becasue the implementation complexity not worth the issue

**Comment by bsclifton** [comment]
For more context / posterity - potential solution was shared with myself and @fmarier. Basically would involve at a minimum touching the following:
- Starts here [https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/ui/views/frame[…]8ae287d5adc828b9546eec95f668a?q=browser_view.cc&ss=chromium](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/ui/views/frame/browser_view.cc;l=4729;drc=da35f4ed6398ae287d5adc828b9546eec95f668a?q=browser_view.cc&ss=chromium)
- WebContents [https://source.chromium.org/chromium/chromium/src/+/main:content/public/browser/web_co[…]98ae287d5adc828b9546eec95f668a?q=web_contents.h&ss=chromium](https://source.chromium.org/chromium/chromium/src/+/main:content/public/browser/web_contents.h;l=894;drc=da35f4ed6398ae287d5adc828b9546eec95f668a?q=web_contents.h&ss=chromium)
- WebContentsImpl https://source.chromium.org/chromium/chromium/src/+/main:content/browser/web_contents/web_contents_impl.cc;l=4968?q=web_contents_impl.cc
- And deeper in third_party/blink [https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/public/mojo[…]38;drc=da35f4ed6398ae287d5adc828b9546eec95f668a;bpv=1;bpt=1](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/public/mojom/input/input_handler.mojom;l=338;drc=da35f4ed6398ae287d5adc828b9546eec95f668a;bpv=1;bpt=1)

Touching these means we'd end up with patches and other difficult to review items. Thanks for investigating, @spylogsster! 😄
