### ISSUE TITLE
Update "are" to "is" in Brave Rewards disabled text in Rewards settings in brave://settings/rewards

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#28888]
## Description

![image](https://user-images.githubusercontent.com/11497541/222802049-1335a4b7-9041-4ec2-a050-a7135680fea7.png)

It should say "Brave Rewards is disabled".

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.51.77 Chromium: 112.0.5615.49 (Official Build) beta (x86_64)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | macOS Version 11.7.5 (Build 20G1225)

### Steps:
1. installed `1.51.77`
2. launched Brave
3. opened `brave://settings/rewards`
4. examined the descriptive text


#### Confirmed it now reads `Brave Rewards is disabled`

<img width="1829" alt="Screen Shot 2023-04-05 at 5 40 09 PM" src="https://user-images.githubusercontent.com/387249/230244231-d602fa8f-64a9-4119-b6af-1dc7c7cdd1f0.png">
