### ISSUE TITLE
Disabling Rewards should also disable Ads

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#2888]
## Description 
Disabling Rewards via the main toggle under `brave://rewards` should also disable Ads

## Steps to Reproduce

1.  Enable Rewards
2. If not automatically enabled, enable Ads.
3. Verify you see some Ads after some time browsing
4. Turn off Rewards (do not explicitly turn off Ads)

## Actual result:

Ads is still enabled and notifications are still delivered

## Expected result:
Ads should be disabled

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by NejcZdovc** [comment]
I think this needs to be fixed in ads library to check if rewards are enabled or not

**Comment by NejcZdovc** [comment]
we do the same thing with everything else cc @bridiver @tmancey

**Comment by ryanml** [comment]
Fixed with: https://github.com/brave/brave-core/pull/1297

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.60.28 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Mac OS X

* Verified test plan in https://github.com/brave/brave-core/pull/1297
* Additional testing notes outlined here: https://github.com/brave/brave-browser/issues/2972#issuecomment-464192927
