### ISSUE TITLE
Change title to "Add NFT"

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#28882]
![Image](https://user-images.githubusercontent.com/318119/222735694-29918df5-8aa7-428c-9f07-dbce610240dc.png)

**Comment by muliswilliam** [comment]
@wknapik Done. Thank yoy.

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.51.103 Chromium: 112.0.5615.165 (Official Build) beta (64-bit) 
-- | --
Revision | `c262f36e6b1d711ee42d4fbe1343b49960593f18-refs/branch-heads/5615@{#1297}`
OS | Linux

- Verified steps from [brave/brave-core#17491](https://github.com/brave/brave-core/pull/17491)
- Verified `Edit NFT` is now renamed to `Import NFT`
![image](https://user-images.githubusercontent.com/17010094/234488708-044c58b9-ff74-427f-9c2e-6f19c761186f.png)

---------------------

**Verification passed on**

Brave | 1.51.103 Chromium: 112.0.5615.165 (Official Build) beta (64-bit)
-- | --
Revision | `c262f36e6b1d711ee42d4fbe1343b49960593f18-refs/branch-heads/5615@{#1297}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from [brave/brave-core#17491](https://github.com/brave/brave-core/pull/17491)
- Verified `Edit NFT` is now renamed to `Import NFT`
![brave_lfXBgPZOBa](https://user-images.githubusercontent.com/17010094/234488649-1155b911-ece5-4f23-aad9-79e2a95f0ba2.png)


---------------------

**Verification passed on**

Brave | 1.51.103 Chromium: 112.0.5615.165 (Official Build) beta (arm64)
-- | --
Revision | `c262f36e6b1d711ee42d4fbe1343b49960593f18-refs/branch-heads/5615@{#1297}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#17491](https://github.com/brave/brave-core/pull/17491)
- Verified `Edit NFT` is now renamed to `Import NFT`
![image](https://user-images.githubusercontent.com/17010094/234488797-33f15c97-92d7-4c1c-b32e-15fa87c4783f.png)
