### ISSUE TITLE
brave shield does not block video ads on yahoo news 

### ISSUE THREAD

**Issue by bruhdev1290** [brave/brave-browser#28884]
steps to reproduce:

go to https://www.yahoo.com/news/ron-desantis-loses-cool-reporter-113028906.html

and play the video 

brave [Version 1.48.171 Chromium: 110.0.5481.177] windows 11

**Comment by rebron** [comment]
cc: @ryanbr

**Comment by ryanbr** [comment]
Switch to Aggressive mode, the ads seem to delivered via first-party @bruhdev1290
