### ISSUE TITLE
Unnecessary margins on welcome flow and tipping banner

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#2889]
## Description 
The welcome screen has a margin around the body element, creating an unsightly gap between the design of the page and the edge of the browser.

## Steps to Reproduce
1. Navigate to brave:welcome

## Brave version (brave://version info)
0.58.18

### Additional Information
![image](https://user-images.githubusercontent.com/815158/50954200-56b8df00-147b-11e9-8841-1a5e43dcc6a1.png)

**Comment by NejcZdovc** [comment]
same thing happens to site banner (image was done on 0.59)

![image](https://user-images.githubusercontent.com/9574457/50954348-5a1d8c00-14b6-11e9-91be-0eb7b10d1876.png)

**Comment by rebron** [comment]
@jonathansampson still an issue with beta/dev builds with new welcome screen?

**Comment by rebron** [comment]
Closing. This looks fixed in 59.33 for both tipping banner and welcome flow.
