### ISSUE TITLE
Copy keyboard shortcut is not assigned to "copy clean link" in context menu on Linux

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#28891]
Follow up from https://github.com/brave/brave-browser/issues/26761
This is a visual bug. The control+c shortcut actually works as `copy clean link`

## Steps to Reproduce

1. new profile
2. launched Brave
3. loaded `https://twitter.com/fmarier/status/1574869891978784769?s=21&t=lkfjeslkfjes&fbclid=1234`
4. selected the whole URL
5. right click to open context menu

## Actual result:

Copy keyboard shortcut is not assigned to "copy clean link" on Linux
![image](https://user-images.githubusercontent.com/34715963/222834908-c0413ca6-6a9d-4782-89c3-e4a78fb394f4.png)

## Expected result:
Copy keyboard shortcut is assigned to "copy clean link" on Linux

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.49.118 Chromium: 111.0.5563.50 (Official Build) (64-bit) 
-- | --
Revision | 39f3dfc5023fe60997adc4f6cf5439cfa3e6968a-refs/branch-heads/5563@{#903}
OS | Ubuntu 18.04 LTS

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

cc @spylogsster @fmarier @rebron

**Comment by kjozwiak** [comment]
The above requires `1.49.126` or higher for `1.49.x` verification 👍
