### ISSUE TITLE
Can't connect Brave Wallet to snapshot.org

### ISSUE THREAD

**Issue by samuveth** [brave/brave-browser#28896]
## Description 
Since updating from 1.44 to 1.48 on macOS, `provider.getNetwork()` returns undefined.

## Steps to Reproduce

   1. Go to snapshot.org and login with Brave
   2. See error in the console

## Actual result:
```
TypeError: Illegal invocation: Function must be called on an object of type JSEthereumProvider
    at Web3Provider.jsonRpcFetchFunc (index.19479770.js:329:143236)
    at Web3Provider.send (index.19479770.js:329:144115)
    at Web3Provider.listAccounts (index.19479770.js:329:105615)
    at k (index.19479770.js:799:4783)
    at _ (index.19479770.js:799:3998)
    at async Ie (index.19479770.js:853:23442)
...
useWeb3.ts:86 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'chainId')
    at loadProvider (useWeb3.ts:86:34)
    at login (useWeb3.ts:30:13)
    at async handleLogin (NavbarAccount.vue:19:3)
loadProvider @ useWeb3.ts:86
login @ useWeb3.ts:30
Promise.catch (async)
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:166
emit$1 @ runtime-core.esm-bundler.js:711
onClick @ ModalAccount.vue:42
callWithErrorHandling @ runtime-core.esm-bundler.js:155
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:164
invoker @ runtime-dom.esm-bundler.js:370
index.ts:269 Uncaught (in promise) Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.1)
    at Logger.makeError (index.ts:269:28)
    at Logger.throwError (index.ts:281:20)
    at Web3Provider.<anonymous> (json-rpc-provider.ts:483:23)
    at Generator.next (<anonymous>)
    at fulfilled (json-rpc-provider.ts:16:1)
```

## Expected result:
Should work like with Brave version 1.44 the wallet should connected.

## Reproduces how often: 
Easily reproducible 

## Brave version (brave://version info)
[Version 1.48.171 Chromium: 110.0.5481.177 (Official Build) (arm64)](https://brave.com/latest/)

- Can you reproduce this issue with the current release? 
Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
No
- Does the issue resolve itself when disabling Brave Rewards?
No
- Is the issue reproducible on the latest version of Chrome?
No

**Comment by samuveth** [comment]
The issue still persists, can we get an update please?

**Comment by yrliou** [comment]
@samuveth I have started looking into it, and have it working in my local build, will give more updates here very soon. Thank you for your patience.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.49.126 Chromium: 111.0.5563.64 (Official Build) (64-bit)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Linux

Verified steps from [brave/brave-core#17658](https://github.com/brave/brave-core/pull/17658)
Verified able to connect and disconnect the wallet from `https://snapshot.org`

https://user-images.githubusercontent.com/17010094/226528044-70ff8356-2623-4c18-be0c-280b0d37069d.mp4
