### ISSUE TITLE
"Set Default browser" bar with vertical tabs on is sized weirdly.

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#28899]
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/5474642/222935123-5d4e04f9-f858-4008-9161-a32a1d9d7462.png">

**Comment by sangwoo108** [comment]
only happens on NTP

**Comment by 18009292019** [comment]
###https://github.com/brave/brave-browser/issues/28899#issue-1610000549``

**Comment by 18009292019** [comment]
https://github.com/brave/brave-browser/issues/28899#issue-1610000549
