### ISSUE TITLE
Don't remove MacOS Mojave 10.14 support on Brave, even if Google now announced to us that they will do that

### ISSUE THREAD

**Issue by browserwatchtg** [brave/brave-browser#28909]
![Image Copied on 2023-03-06 at 11 59 21 AM](https://user-images.githubusercontent.com/114294762/223095833-5048c334-dc9d-4814-b0a5-a59e1e26ecf0.jpeg)

Few hours ago Senior Dev reported us the no interest of keeping MacOS Mojave support on Chrome.
In 2 years they are removing the 2 best MacOS ever released, before Apple started to downgrade features in MacOS (and obviously adding some other too), especially related to all backup workflows, that now are more complex, but even to permissions and multiple other things. We reported the new downgrade for external drives implemented in MacOS 12/13 [previously](https://old.reddit.com/r/appledatahoarding/comments/11ikj38/next_macos_downgrade_available_with_monterey/), but this is not the point now.

We explained already [here](https://bugs.chromium.org/p/chromium/issues/detail?id=1413784&q=sierra%20chrome&can=1) why they should keep support for such MacOS, and later again [here](https://bugs.chromium.org/p/chromium/issues/detail?id=1322548#c68).

Now the point is: we are trying our best to revert such decision, like we wrote [here](https://old.reddit.com/r/appledatahoarding/comments/11jufgo/google_chrome_support_will_end_in_few_months_for/), but it's important that other chromium based devs know about such problematic and evaluate to continue support, if this is technically possible. Remember that MacOS 10.14 is not like all other MacOS released by Apple, so removing such MacOS is not like removing Catalina, High Sierra etc. 

If there are question why MacOS Mojave support is so important, just write directly to us. We already experienced the direct consequence of removing MacOS on Chromium on all browsers and apps few months ago with Sierra.

Please keep in mind that this is not just related to Chrome, but even Chromium based browsers, Mac Apps using Electron, and all other Mac Apps too (because if one is starting to remove support, especially big brands, the other will follow much easier*). So be open with your mind and don't write "i'm not using Chrome or Mojave, doesn't matter for me".

There is the possibility that Google maybe know about some changes with Xcode, like we wrote [here](https://old.reddit.com/r/appledatahoarding/comments/11jho7y/meanwhile_the_batch_deletion_of_other_2_macos_by/), but probably is not the case. If this is true, then the situation would be much worse, if now Apple really decides to remove multiple MacOS, like we previously reported with out [thoughts](https://old.reddit.com/r/appledatahoarding/comments/114o7zt/remember_2023_will_be_the_most_crucial_year_of/).

*Keep in mind that almost 70%+ of all browsers available for MacOS (80+) are Chromium based.

------------
In case you will not doing that and Google will not keep support for Mojave, please provide directly link to download a browser version compatible with up to MacOS Sierra and one up to MacOS Mojave, instead of just download last version. Avoid auto update of the app too. So don't install new incompatible app automatically, which make no sense at all.

**Comment by bsclifton** [comment]
It would be a lot of effort to support OSes that Chromium declares end of life for (with support). I don't see us not following suite as Chromium upgrades are already difficult as-is.

cc: @rebron

**Comment by bsclifton** [comment]
Thanks for the feedback @browserwatchtg - I've shared with our product owner (maybe we can have a Mojave specific download page). We realistically can't continue to support though if Chromium pulls the plug so I'm going to close as `wontfix`
