### ISSUE TITLE
New Tab page Crashes - when Brave News in brave://flags is disabled

### ISSUE THREAD

**Issue by brokoler** [brave/brave-browser#28901]
## Description 
When the flag "Enable Brave News" is disabled in brave://flags, upon relaunch the New Tabe page gives the "Aww snap" error every time. As soon the flag is set to default, this doesn't happen. For users that disable Brave News on purpose for privacy and performance reasons, there should be a fix for this.

The issue was already posted but closed, still the issue persists:
https://github.com/brave/brave-browser/issues/27184

## Steps to Reproduce

   1. Goto Brave://flags
   2. Search for Enable Brave News
   3. Set it to be disabled
   4. Relaunch the browser and open new tab

## Actual result:
We get Aw, Snap!
Error Code: RESULT_CODE_KILLED_BAD_MESSAGE

![brave-newtab](https://user-images.githubusercontent.com/57031979/222957073-e0943f49-ca4e-48da-a879-2b6d71eaee02.png)

## Expected result:
New tab page loads fine

## Reproduces how often: 
Every time with Windows 10 and Windows 11, this can be reproduced without problems.
Wasn't able to test with different operating systems.

## Brave version (brave://version info)
1.48.171 Chromium: 110.0.5481.177 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release?  yes (tested with Brave Stable 1.48.171)
- Can you reproduce this issue with the beta channel? yes (tested with Brave Beta 1.50.78)
- Can you reproduce this issue with the nightly channel? yes (tested with Brave Nightly 1.51.6)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? no

## Miscellaneous Information:
Happens since a few months now with different Brave Releases, at least since following version:
1.46.134 Chromium: 108.0.5359.94 (Official Build) (64-bit)

**Comment by bsclifton** [comment]
Closing as stale - this flag no longer exists

cc: @fallaciousreasoning
