### ISSUE TITLE
[Android] The `Brave Rewards` option is shown in the 3 dot menu for the brave rewards unavailable countries

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#28908]
## Description 
Found while testing https://github.com/brave/brave-browser/issues/25276
The `Brave Rewards` option is shown in the 3 dot menu for the brave rewards unavailable countries
## Steps to reproduce 

   1. Follow the steps 1 to 6 from Test Case 1 https://github.com/brave/internal/issues/981#issuecomment-1453252866
   2. In step 6, The `Brave Rewards` option is shown in the 3 dot menu for the brave rewards unavailable country "Russia"

## Actual result 
The `Brave Rewards` option is shown in the 3 dot menu for the brave rewards unavailable countries

![image](https://user-images.githubusercontent.com/38657976/223076354-ffa7bf00-4e2c-4e0e-acca-7af70123e753.png)

## Expected result
The `Brave Rewards` option should NOT be shown in the 3 dot menu for the brave rewards unavailable countries

## Issue reproduces how often 

Easy
## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung Galaxy 
   - Android version: 12
   
## Brave version
1.49.118

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @deeppandya @Miyayes @brave/qa-team

**Comment by GeetaSarvadnya** [comment]
Similar issue on Desktop #27629
cc: @deeppandya

**Comment by deeppandya** [comment]
@GeetaSarvadnya we didn't want to hide the rewards button in OFAC case. But if we decide to hide, I have created a PR for the change.

**Comment by Miyayes** [comment]
@deeppandya We ended up removing it in the desktop case: https://github.com/brave/brave-browser/issues/27629 So let's remove it on the Android case as well.

**Comment by deeppandya** [comment]
> @deeppandya We ended up removing it in the desktop case: #27629 So let's remove it on the Android case as well.

@Miyayes in that case, we already have the PR ready for the issue.

**Comment by kjozwiak** [comment]
The above requires `1.50.94` or higher for `1.50.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Samsung Galaxy version 12` running `Bravemonoarm64.apk_1.50.101`

- Veriified the test plan from https://github.com/brave/brave-browser/issues/28908#issue-1611045157
- Confirmed that the `Brave Rewards` settings is removed from the 3 dot menu for brave rewards unavailable country "Russia"

**_Russia_**

Example | Example 
----------|-----------
![Screenshot_20230328-152348_Settings](https://user-images.githubusercontent.com/38657976/228199715-4f1b00ae-f589-44bb-93c5-fcf8b34051e9.jpg) | ![Screenshot_20230328-152303_Brave - Beta](https://user-images.githubusercontent.com/38657976/228199770-19e64466-005e-4690-af09-c455ece1cde6.jpg)
