### ISSUE TITLE
Tab crashes when watching videos

### ISSUE THREAD

**Issue by serber1990** [brave/brave-browser#28902]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.48.171  Chromium: 110.0.5481.177
Operating System: Linux 5.19.0-35-generic

URL (if applicable) where crash occurred:
www.youtube.com / www.twitch.tv

Can you reproduce this crash?
It happens randomly every X minutes.

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Play any Video from Youtube or Twitch
2. After some time 30 minutes, maybe more it stops and crashes the tab
3. I have to close the tab and open a new one and it just works again

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/a8270400-5aad-b509-0000-000000000000

**Comment by iefremov** [comment]
Looks like an OOM crash, @serber1990 can you please update, try to reproduce, and share new IDs if any? Feel free to reopen the issue
