### ISSUE TITLE
Hide in app purchase details

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#28910]
This issue is to hide manage subscription , expires , status  if user has an active desktop subscription and only show them if the subscription is through in app purchase.

For more details : https://bravesoftware.slack.com/archives/C021S0FN3V1/p1677776529727149

**Comment by kjozwiak** [comment]
The above requires `1.49.124` or higher for `1.49.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung GS 21 5G` using version(s):

```
Brave	1.49.129 Chromium: 111.0.5563.116 (Official Build) (64-bit) 
Revision	ade86b9472831e26d87fd569e04b404be01e1e2b-refs/branch-heads/5563@{#1209}
OS	Android 13;
```
Test Plan: 

1. Purchase VPN desktop client using production credentials
2. Install 1.49.129 on Android device
3. Redeem VPN from account.brave.com
4. Enable VPN profile
5. Open VPN settings
6. Confirm `manage subscription` , `expires` , `status` fields are hidden

- Ensured manage subscription, expires and status fields are hidden
- Ensured user is able to enable VPN profile and it is functional
- Ensured manage subscription, expires and status fields are shown when purchasing VPN subscription on Android app using IAP.

Example | Example | Example | Example
-|-|-|-
![screenshot-1679530472837](https://user-images.githubusercontent.com/17885425/227067551-062bc592-b27e-49c3-8e9d-ad2731bbaaf7.png) | ![screenshot-1679530498645](https://user-images.githubusercontent.com/17885425/227067556-281ca4dc-136c-41b1-a578-e276573e2d82.png) | ![screenshot-1679530528529](https://user-images.githubusercontent.com/17885425/227067558-2be0ba08-4cd3-44f9-9ce9-0cafd8775ae9.png) | ![screenshot-1679530546547](https://user-images.githubusercontent.com/17885425/227067559-3ca28d55-10d6-4366-b7af-ee108cd20fa6.png)

VPN subscription purchased on Android app

Example | Example | Example
-|-|-
![screenshot-1679497508927](https://user-images.githubusercontent.com/17885425/227067703-0440b225-e22a-46a2-89c1-8ce89a975a83.png) | ![screenshot-1679497529048](https://user-images.githubusercontent.com/17885425/227067742-76298cf9-a47b-4148-a21f-645bb0e8d9f5.png) | ![screenshot-1679500973821](https://user-images.githubusercontent.com/17885425/227067768-ee4ef7f9-65ec-44c3-84fb-623ffae27966.png)
