### ISSUE TITLE
how IPFS functionality doesnt work in my component build

### ISSUE THREAD

**Issue by NaaeemMalik** [brave/brave-browser#28911]
Brave browser gets stuck on IPFS installing step in my build and also in brave official nightly channel and I need to know how to make it work

## Actual result:
clicking on local node doesnt do anything except saying installing 

## Expected result:
clicking on local node shows enable extension dialogue 

## OS
Version 1.48.142  Chromium: 109.0.5414.119 (Developer Build)  (64-bit)
Windows 11 22H2

**Comment by srirambv** [comment]
Can you add OS details?

**Comment by NaaeemMalik** [comment]
sorry I checked again by deleting user data folder it works in nightly now but still not in my component build
