### ISSUE TITLE
Show swap button on AssetDetails in stacked view

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#28914]
## Expected result

![Screenshot from 2023-03-03 12-11-39](https://user-images.githubusercontent.com/11755381/223137945-1a37a103-1022-4190-a2a2-bd7527b8115d.png)

**Comment by kjozwiak** [comment]
The above requires `1.49.124` or higher for `1.49.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.49.126 x64 build
- Verified steps from [brave/brave-core#17540](https://github.com/brave/brave-core/pull/17540)
- Verified `Swap` button is shown on Ethereum network for supported tokens

Oppo Reno 5 (Android 13) | Lenovo Tab (Android 12)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/226524227-c82548d7-501f-4e82-b8d7-6a5f772007d6.mp4> | <video src=https://user-images.githubusercontent.com/17010094/226524250-075ac871-57a6-48f8-a5ca-a97f22a68f4f.mp4>
