### ISSUE TITLE
[Android] Google Sign-In permission

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#28927]
Android port of https://github.com/brave/brave-core/pull/16595

When feature is on:
1. Prompt users for Google Sign In permission when visiting websites that use legacy Google Sign In
2. Have an entry for `Google Sign In` in `Site Settings` in Settings. Adding/subtracting exceptions should work.
3. There shouldn't be any global Allow Google Login toggle under Social Media Blocking in Settings under `Privacy & shields`

**Comment by Uni-verse** [comment]
In progress on Samsung Galaxy Tab S7 using version:

```
Brave	1.51.109 Chromium: 113.0.5672.63 (Official Build) (64-bit) 
Revision	0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
Test Plan: https://github.com/brave/brave-core/pull/16595#issue-1527191336

<details><summary>Feature Flag</summary>

- Verified Google Sign-in permission is disabled when set to default.
- Verified pop-up is shown when signing in to www.fandango.com if feature flag #brave-google-sign-in-permission is enabled.
- Verified sign-in permission pop-up not shown when logging into www.fandango.com if feature flag is disabled or set to default.

Example | Example | Example
-|-|-
![screenshot-1682975856172](https://user-images.githubusercontent.com/17885425/235697823-94c02784-efb9-48ef-850d-5b5a5a33de80.png) | ![screenshot-1682972758246](https://user-images.githubusercontent.com/17885425/235697698-1cbf8d98-3596-4867-8e56-170bacfccdbb.png) | ![screenshot-1683037732231](https://user-images.githubusercontent.com/17885425/235697863-52ddac25-d9ae-4119-a1a0-18b9a602cf4a.png)

</details>

<details><summary>Functionality</summary>

- Verified that Google Sign-in permission pop-up is shown when feature is enabled and user tries to log into sites that use 3rd party cookies based on the list in https://docs.google.com/spreadsheets/d/1323Jfy5l1Iotcvv2hdzW-HTSz7A0698wM9XFbdICVjw/edit#gid=0
- Verified that Google Sign-in permission pop-up is NOT shown when feature is disabled and user signs into the sites mentioned in https://docs.google.com/spreadsheets/d/1323Jfy5l1Iotcvv2hdzW-HTSz7A0698wM9XFbdICVjw/edit#gid=0
- Verified Google Sign-in permission pop-up is not shown for websites that do not use 3rd party cookies based on the list in https://github.com/brave/brave-core/pull/16595#issue-1527191336. User is still able to successfully sign in.
- Verified setting the cookie for 24 hours will not bring up the pop-up even after closing the tab and requesting to sign-in with google to fandango.com

Example | Example | Example
-|-|-
![screenshot-1683039168486](https://user-images.githubusercontent.com/17885425/235704307-2cd7003b-d4f8-4ba9-a853-da67565bd711.png) | ![screenshot-1682974824339](https://user-images.githubusercontent.com/17885425/235704603-279ddd9f-23c3-449d-9955-cebe0226197f.png) | ![screenshot-1682977482072](https://user-images.githubusercontent.com/17885425/235704809-6ef2a9f3-a122-4928-9a45-1f93e68209f9.png)

</details>

<details><summary>Brave Settings</summary>

- Verified `Allow Google login buttons on third party sites` Social Media Blocking switch is removed when feature is enabled and is shown if disabled.

Example | Example
-|-
![screenshot-1682976295414](https://user-images.githubusercontent.com/17885425/235705200-83e836fb-be8f-401b-acf7-6361f29ed229.png) | ![screenshot-1682977214660](https://user-images.githubusercontent.com/17885425/235705207-23a5e79c-6888-4573-b2b9-f984a61daf9c.png)


</details>
