### ISSUE TITLE
Update `HTTPS by Default` to work with `HttpsFirstModeV2`

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#28935]
Chromium 112 has [enabled `HttpsFirstModeV2`](https://chromium.googlesource.com/chromium/src/+/9c6408ef696e83a9936b82bbead3d41c93c82ee4) feature flag by default. This feature provides a new implementation for HTTPS by default (see [the tracking issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1394910)).

For now, we turned the flag to being disabled by default in [Chromium 112 bump](https://github.com/brave/brave-core/pull/17187), but before the old implementation is removed upstream we need to update our [implementation](https://github.com/brave/brave-core/pull/16521) to work with `HttpsFirstModeV2`

**Test Plan**:
Same test plan as outlined in https://github.com/brave/brave-core/pull/16521#issue-1518508196 and https://github.com/brave/brave-browser/issues/27141#issuecomment-1441252025

cc: @arthuredelstein @pes10k

**Comment by kjozwiak** [comment]
@brave/qa-team [here's the ](https://github.com/brave/brave-core/pull/17856#issuecomment-1524719533) are the reduced cases that I ran through while verifying on `master` before uplifting into `1.51.x`. One other thing that we'll need to make sure that is working is upgrading from the previous implementation of `HTTPS By Default` to `HttpsFirstModeV2` and make sure everything is retained/working as expected.

**Comment by kjozwiak** [comment]
The above requires `1.51.107` or higher for `1.51.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave | 1.51.107 Chromium: 113.0.5672.63 (Official Build) (64-bit)
-- | --
Revision | 0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}
OS | Windows 10 Version 21H2 (Build 19044.2846)
```

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.51.107 Chromium: 113.0.5672.63 (Official Build) (x86_64)
-- | --
Revision | 0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}
OS | macOS Version 11.7.6 (Build 20G1231)



### Steps:
Use devtools to use a mobile UA (I used Android (4.0.2) browser.
Visit https://anicobin.ldblog.jp/archives/59981055.html
Click on the comments button:

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Vivo X70 Pro version 12` runnig `Bravemonoarm64.apk_1.51.109`

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung Galaxy Tab S8 Ultra` running `Android 13` using the following build(s):

```
Brave | 1.51.109 Chromium: 113.0.5672.63 (Official Build) (32-bit)
--- | ---
Revision | 0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}
OS | Android 13; Build/TP1A.220624.014; 33; REL
```

### `Case #1` (from https://github.com/brave/brave-browser/issues/27141) - `PASSED`
<details>

#### Shields Panel (`Upgrade to HTTPS whenever possible (default)`)

* ensured that `Upgrade to HTTPS whenever possible (default)` is selected as the default (if the user hasn't changed anything)
  * ensured that http://insecure.arthuredelstein.net loads without any issues (shouldn't be upgrading)
  * ensured that http://http.badssl.com loads without any issues (shouldn't be upgrading)
  * ensured that http://upgradable.arthuredelstein.net -> https://upgradable.arthuredelstein.net (should be upgraded)

**`Example`** | **`Example`** | **`Example`** |  **`Example`**
----------------|----------------|----------------|----------------
![Screenshot_20230502_211118_Brave](https://user-images.githubusercontent.com/2602313/235816785-c5ac3432-de1d-4e69-aca2-cfd2855398f6.jpg) | ![Screenshot_20230502_211149_Brave](https://user-images.githubusercontent.com/2602313/235816791-ffb4d412-0686-48bd-a3e8-4a945b50d7cd.jpg) | ![Screenshot_20230502_211302_Brave](https://user-images.githubusercontent.com/2602313/235816796-53d6bf3e-3b60-49b7-8414-21bfdc014812.jpg) | ![Screenshot_20230502_211309_Brave](https://user-images.githubusercontent.com/2602313/235816803-91f36232-b760-41a3-88b6-19fad7149e4d.jpg)

#### Shields Panel (`Require all connections to use HTTPS (strict)`)

* visit http://insecure.arthuredelstein.net, http://http.badssl.com and http://upgradable.arthuredelstein.net and ensure that `Require all connections to use HTTPS (strict)` is selected via the shields panel
  * ensure that http://insecure.arthuredelstein.net displays `The connection to insecure.arthuredelstein.net is not secure`
    * ensure that `Continue to site` loads http://insecure.arthuredelstein.net without any issues
    * ensured that http://insecure.arthuredelstein.net loads without any issues after several restarts once `Continue` is selected
    * ensured that you `Turn on warnings` works as expected via the `Not Secure` drop down
  * ensure that http://http.badssl.com displays `The connection to http.badssl.com is not secure`
    * ensure that `Continue to site` loads http://http.badssl.com without any issues
    * ensured that http://http.badssl.com loads without any issues after several restarts once `Continue` is selected
    * ensured that you `Turn on warnings` works as expected via the `Not Secure` drop down
  * ensured that http://upgradable.arthuredelstein.net -> https://upgradable.arthuredelstein.net (should be upgraded)

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** 
----------------|----------------|----------------|----------------|---------------
![Screenshot_20230502_211519_Brave](https://user-images.githubusercontent.com/2602313/235816883-b8955aa5-adaa-4d2e-a702-73f23bed6e12.jpg) | ![Screenshot_20230502_211433_Brave](https://user-images.githubusercontent.com/2602313/235816894-7fa8793b-be39-4ddf-875a-1162c53ceafe.jpg) | ![Screenshot_20230502_211439_Brave](https://user-images.githubusercontent.com/2602313/235816897-5cc5ff9a-82c2-4200-b296-d24b916fccf9.jpg) | ![Screenshot_20230502_211527_Brave](https://user-images.githubusercontent.com/2602313/235816904-923b703e-1cbd-4e14-958b-16869c3506c5.jpg) | ![Screenshot_20230502_211531_Brave](https://user-images.githubusercontent.com/2602313/235816908-3acd41aa-bb67-4504-b63d-1b9d51fc09cc.jpg)

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** 
----------------|----------------|----------------|----------------|---------------
![Screenshot_20230502_212025_Brave](https://user-images.githubusercontent.com/2602313/235818207-79deb7b3-a46c-4d59-b227-0c4ac2b2e108.jpg) | ![Screenshot_20230502_212030_Brave](https://user-images.githubusercontent.com/2602313/235818211-19b79ab7-0dbb-4b3c-aeb4-ecd84effe6c4.jpg) | ![Screenshot_20230502_212038_Brave](https://user-images.githubusercontent.com/2602313/235818213-1fd9083b-e119-4b14-ae6d-b505b3441878.jpg) | ![Screenshot_20230502_212042_Brave](https://user-images.githubusercontent.com/2602313/235818215-3264c2f4-a08f-47d3-86d1-096efa49f777.jpg) | ![Screenshot_20230502_212046_Brave](https://user-images.githubusercontent.com/2602313/235818321-c394d4c7-6a89-40b9-9fb9-ca5371246b94.jpg)

#### Shields Panel (`Don't upgrade connections to HTTPS (disabled)`)

* visit http://insecure.arthuredelstein.net, http://http.badssl.com and http://upgradable.arthuredelstein.net and ensure that `Don't upgrade connections to HTTPS (disabled)` is selected via the shields panel
  * ensure that http://insecure.arthuredelstein.net loads without any issues
  * ensure that http://http.badssl.com loads without any issues
  * ensured that http://upgradable.arthuredelstein.net doesn't upgrade to `HTTPS` (make sure website loads without issues)
    * basically ensuring that https://upgradable.arthuredelstein.net doesn't load

**`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------|----------------
![Screenshot_20230502_213842_Brave](https://user-images.githubusercontent.com/2602313/235818674-0881d7cc-32d4-41d0-bd82-941b53836377.jpg) | ![Screenshot_20230502_213829_Brave](https://user-images.githubusercontent.com/2602313/235818676-d5f4d023-c5fc-4b49-86d3-5b8bb77f084f.jpg) | ![Screenshot_20230502_213836_Brave](https://user-images.githubusercontent.com/2602313/235818680-2286dcba-be3d-4caf-9813-838778c83c68.jpg) | ![Screenshot_20230502_213848_Brave](https://user-images.githubusercontent.com/2602313/235818684-399273e4-61b0-40d8-ad66-baacf45c4276.jpg)

#### Prevent permissive HTTPS Upgrade settings from leaking from `Normal` to `Private` windows

Basically used the STR/Cases outlined via https://github.com/brave/brave-core/pull/17421#issuecomment-1489678235 and went through the following:

### `Test Case #1` - `Upgrade to HTTPS whenever possible (default)`

* visited http://upgradable.arthuredelstein.net in a `Normal` window and ensured that `Upgrade to HTTPS whenever possible (default)`
  * ensured that `http://upgradable.arthuredelstein.net` -> `https://upgradable.arthuredelstein.net`
* opened a `Private` window and visited http://upgradable.arthuredelstein.net and ensured `Upgrade to HTTPS whenever possible (default)`
  * ensured that `http://upgradable.arthuredelstein.net` -> `https://upgradable.arthuredelstein.net`

### `Test Case #2` - `Require all connections to use HTTPS (strict)`

* visited http://upgradable.arthuredelstein.net and switched HTTPS upgrades to `Require all connections to use HTTPS (strict)`
  * ensured that `http://upgradable.arthuredelstein.net` -> `https://upgradable.arthuredelstein.net`
* opened a `Private` window and visited http://upgradable.arthuredelstein.net and ensured `Require all connections to use HTTPS (strict)`
  * ensured that `http://upgradable.arthuredelstein.net` -> `https://upgradable.arthuredelstein.net`

### `Test Case #3` - `Don't upgrade connections to HTTPS (disabled)`

* visited http://upgradable.arthuredelstein.net switched HTTPS upgrades to `Don't upgrade connections to HTTPS (disabled)`
* reloaded http://upgradable.arthuredelstein.net and ensured that the website was not being upgraded to HTTPS
* opened a `Private` window and visited http://upgradable.arthuredelstein.net and ensured `Upgrade to HTTPS whenever possible (default)`
  * ensured that `http://upgradable.arthuredelstein.net` -> `https://upgradable.arthuredelstein.net`

Ensure that `Don't upgrade connections to HTTPS (disabled)` is NOT being used

### `Test Case #4` - `Don't upgrade HTTPS connections` (Private Window Only)

* opened a `Private` window and visited http://upgradable.arthuredelstein.net and ensured `Upgrade to HTTPS whenever possible (default)`
  * ensured that `http://upgradable.arthuredelstein.net` -> `https://upgradable.arthuredelstein.net`
* change the HTTPS upgrade setting to `Don't upgrade connections to HTTPS (disabled)` and load `http://upgradable.arthuredelstein.net`

Ensure that `http://upgradable.arthuredelstein.net` is not upgrade. With this case, we're basically ensuring that you can still use `Don't upgrade HTTPS connections` if changed within the `Private` window.
</details>
