### ISSUE TITLE
Blob partitioning fails on Android

### ISSUE THREAD

**Issue by goodov** [brave/brave-browser#28934]
https://dev-pages.brave.software/storage/partitioning.html

![image](https://user-images.githubusercontent.com/5928869/223452716-276c7bc2-9c0a-4ffd-b825-cc7797046447.png)
![image](https://user-images.githubusercontent.com/5928869/223452728-ecb27376-9d02-4dfe-975c-b1b73ba4271c.png)

**Comment by goodov** [comment]
QA test https://dev-pages.brave.software/storage/partitioning.html

**Comment by kjozwiak** [comment]
The above requires `1.49.126` or higher for `1.49.x` verification 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 13` using the following PR(s):

```
Brave | 1.49.129 Chromium: 111.0.5563.116 (Official Build) (64-bit)
--- | ---
Revision | ade86b9472831e26d87fd569e04b404be01e1e2b-refs/branch-heads/5563@{#1209}
OS | Android 13; Build/TQ1A.230205.002
```

![image](https://user-images.githubusercontent.com/2602313/227101058-b58ce942-c3a7-4418-912b-b8bc05aabe65.png)
