### ISSUE TITLE
drag and drop of a vertical tab to a new window results in narrow window size for new window created

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#28936]
## Description 

When you drag and drop vertical tab into its own window (creating a new window from the single dropped tab), the resulting window is very narrow, was expecting it to be the same size as original window.

## Steps to Reproduce

   1. Have vertical tabs enabled and be using them
   2. Grab a single vertical tab and drag it from original window
   3. Drop elsewhere on the screen to create a new window

## Actual result:

Compare original window to newly created window:

<img width="2092" alt="Screen Shot 2023-03-07 at 10 20 35 AM" src="https://user-images.githubusercontent.com/28145373/223468515-94e98a51-b4dd-4bd6-8321-a8b483b3aac1.png">

## Expected result:

Expected new window to be same size as original window

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.51.12 Chromium: 111.0.5563.50 (Official Build) nightly (x86_64)
-- | --
Revision | 39f3dfc5023fe60997adc4f6cf5439cfa3e6968a-refs/branch-heads/5563@{#903}
OS | macOS Version 12.6.3 (Build 21G419)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? unsure
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron

**Comment by stephendonner** [comment]
## Verification `PASSED` using 

Brave | 1.51.79 Chromium: 112.0.5615.49 (Official Build) beta (x86_64)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | macOS Version 11.7.5 (Build 20G1225)

### Steps:
1. installed `1.51.79`
2. launched Brave
3. opened `brave://flags`
4. set `brave://flags/#brave-vertical-tabs` to `Enabled`
5. clicked on `Relaunch`
6. context-clicked on the tab's titlebar
7. clicked on `Use Vertical tabs`
8. loaded `cnn.com`
9. loaded `brave.com`
10. clicked on and dragged the `cnn.com` tab from the tab strib, into its own window on the desktop
11. examined the size of the window

### Confirmed the resulting window is the same size/dimensions as its parent window/tab (super-imposed/overlaid them, as proof)

`step 4` | `step 7a` | `step 7b` | `step 8`
---------|----------|---------|---------
<img width="1312" alt="Screen Shot 2023-04-06 at 9 37 29 PM" src="https://user-images.githubusercontent.com/387249/230542011-dd77b9f8-4298-4d1b-b422-63e4e8744c28.png"> | <img width="1194" alt="Screen Shot 2023-04-06 at 9 37 43 PM" src="https://user-images.githubusercontent.com/387249/230542023-a75a0171-66f9-449e-9af9-38d4fc4b50bb.png"> | <img width="1312" alt="Screen Shot 2023-04-06 at 9 37 48 PM" src="https://user-images.githubusercontent.com/387249/230542030-1e99c51f-77c1-4f3a-ba2e-f2665c4ccce4.png"> | <img width="1312" alt="Screen Shot 2023-04-06 at 9 37 57 PM" src="https://user-images.githubusercontent.com/387249/230542039-92123259-e3b3-4fae-8c85-9b93db7f9fb5.png">

`step 9` | `step 10` | `step 11a` | `step 11b`
---------|----------|---------|---------
<img width="1312" alt="Screen Shot 2023-04-06 at 9 38 12 PM" src="https://user-images.githubusercontent.com/387249/230542049-f3d48ccf-86cb-46d6-9287-b3448c486025.png"> | <img width="1920" alt="Screen Shot 2023-04-06 at 9 40 59 PM" src="https://user-images.githubusercontent.com/387249/230542375-b82b1885-38bd-44e2-adfe-f9a32e37c8b3.png"> | <img width="1268" alt="Screen Shot 2023-04-06 at 9 41 36 PM" src="https://user-images.githubusercontent.com/387249/230542379-affb6be7-3fba-4958-90bd-690e18fbd1b3.png"> | <img width="1218" alt="Screen Shot 2023-04-06 at 9 41 56 PM" src="https://user-images.githubusercontent.com/387249/230542382-dd499ef5-81dc-4fba-87c0-6af9a9093e5d.png">
