### ISSUE TITLE
Unable to login https://account.t-mobile.com/

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-browser#28945]
## Description 
Unable to login into https://account.t-mobile.com/ due to fingerprinting.

## Steps to Reproduce

   1. Open https://account.t-mobile.com/
   2. Get a error message
   3. Unable to login

## Actual result:
![screenshot_2023-03-07_at_5 36 28_pm_720](https://user-images.githubusercontent.com/1659004/223598080-c6384143-f5f8-43c2-ac1b-2743a6f2fb42.png)
<img width="573" alt="screenshot_2023-03-07_at_5 38 30_pm" src="https://user-images.githubusercontent.com/1659004/223598084-1035631f-df35-45d8-80c4-a34a137b46f0.png">

## Expected result:
Allow user to login

## Reproduces how often: 

With a US login, reproducible with fingerprinting enabled

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  Yes
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
Debuging with @okidokiokami   Disabling Language fingerprinting resolves this issue. 

cc: @pilgrim-brave

**Comment by pilgrim-brave** [comment]
reproduced

**Comment by pilgrim-brave** [comment]
During authentication flow, site makes an XHR request to `/eui/v1/initSession` with an explicit `Accept-Language: en` header, which we are overwriting with `Accept-Language: en-US,en;q=0.8`, which causes the server to return an HTTP error 400.

**Comment by pilgrim-brave** [comment]
Overwrite is intentional and occurs here: https://github.com/brave/brave-core/blob/master/browser/net/brave_reduce_language_network_delegate_helper.cc#L106

But for XHRs where the page script has explicitly set an `Accept-Language` header, we should leave it alone instead of farbling it.

**Comment by pilgrim-brave** [comment]
By "intentional" I mean Brave is doing what we designed it to do. It just needs to do something else (in limited circumstances).

**Comment by Uni-verse** [comment]
Verified on `Android` and `MacOS` per https://github.com/brave/brave-core/pull/17549#issuecomment-1489242782

**Comment by kjozwiak** [comment]
Removing `QA Pass` labels as the verifications via https://github.com/brave/brave-core/pull/17549#issuecomment-1489242782 were used to check that the above was working as expected before uplifting into `1.50.x` via https://github.com/brave/brave-core/pull/17697. Once this lands in `1.50.x` and we get builds, we can verify and add the appropriate labels.

**Comment by kjozwiak** [comment]
The above requires `1.50.110` or higher for `1.50.x` verification 👍

**Comment by Uni-verse** [comment]
In progress using version:

Brave | 1.50.112 Chromium: 112.0.5615.49 (Official Build) (x86_64)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | macOS Version 12.6 (Build 21G115)

**Comment by Uni-verse** [comment]
Verified on `Samsung GS 21` using the following version:

```
Brave	1.50.113 Chromium: 112.0.5615.49 (Official Build) (64-bit) 
Revision	bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS	Android 13;
```
Using STR in https://github.com/brave/brave-browser/issues/28945#issue-1614498813

- Confirmed user is able to log into `https://account.t-mobile.com` and view dashboard

<img width="500" alt="1" src="https://user-images.githubusercontent.com/17885425/229964523-d627c97e-c149-471b-8000-0fff4a1bee28.png">
