### ISSUE TITLE
Show What's New page in foreground after major version updates

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#28947]
## Description 

When users update to a major update of the browser e.g. 1.50.x to 1.51.x, we will display the What's New page served from https://brave.com/whats-new/ in the foreground in a new tab.

We will control display of the page via griffin with a new variation: `WhatsNewStudy`. 100% channel Nightly, Platforms: Windows, Mac, Linux  and country: US, GB, DE, FR, ES, JA, KO, PT, CN

Supported languages/translations for the What's New page are: Simplified Chinese, French, German, Japanese, Korean, Portuguese, and Spanish.

## Brave version (brave://version info)

Target version is 1.51.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

brave://whats-new/ would be the internal page. We're sending users to https://brave.com/whats-new/

**Comment by simonhong** [comment]
Chrome has whatsnew entry in app menu.
![image](https://user-images.githubusercontent.com/6786187/224227928-8b877c0b-b3a5-4d90-972b-7d315703c21d.png)

**Comment by simonhong** [comment]
Chrome's what's new page doesn't show up when browser is inactive state after launching.
It's good practice and we should have same logic.

**Comment by LaurenWags** [comment]
@rebron @simonhong is there any determination on whether griffin is being used or not? Test plan in PR (https://github.com/brave/brave-core/pull/17593) mentions a possible griffin trial but QA needs to know for testing.

Adding `QA/Blocked` until this is determined/additional information is provided.

**Comment by simonhong** [comment]
@LaurenWags We can check whether we showed what's new or not by checking local prefs.
In the brave://brave://local-state/, we'll see `brave.whats_new.last_version` and it has the major version string like `1.51`.
If it has `1.50`, it means we already launched what's new for `1.50`. If `brave.whats_new.last_version` is not existed, we didn't  launche whats-new page so far.

**Comment by LaurenWags** [comment]
Thanks @simonhong. Was also wondering about testing the country part as well. Assuming we need to set our OS region to accomplish this? Not sure if this uses `countryid_at_install` from `Preferences` file?

**Comment by simonhong** [comment]
> Thanks @simonhong. Was also wondering about testing the country part as well. Assuming we need to set our OS region to accomplish this? Not sure if this uses `countryid_at_install` from `Preferences` file?

Well.. not sure `countryid_at_install` is used by griffin. but I tested by changing os region settings and it worked.

**Comment by stephendonner** [comment]
This will need the Griffin trial to be activated before testing, per https://bravesoftware.slack.com/archives/CC5SA8CCB/p1681239259640369?thread_ts=1681238839.066039&cid=CC5SA8CCB

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.51.104 Chromium: 112.0.5615.165 (Official Build) beta (x86_64)
-- | --
Revision | c262f36e6b1d711ee42d4fbe1343b49960593f18-refs/branch-heads/5615@{#1297}
OS | macOS Version 11.7.6 (Build 20G1231)

**Comment by stephendonner** [comment]
Restoring `QA/Blocked` until we have the Griffin study `What'sNew:Enabled` on `staging` - currently it's only on `nightly`: https://github.com/brave/brave-variations/blob/f4d06965753a4c708984e2aa8c0d3a82f2f4cb1f/seed/seed.json#L1850

**Comment by btlechowski** [comment]
Griffin studies use `x-country` header from `https://variations.bravesoftware.com/seed` response to determine the country

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.40.94 Chromium: 102.0.5005.115 (Official Build) beta (64-bit
-- | --
Revision | 174dbe6e33bc81994fceb71d751be201d0b4803d-refs/branch-heads/5005_109@{#3}
OS | Ubuntu 18.04 LTS


Verified `what's new` page is shown on major update

<details>

Steps:
1. Set OS to supported locale
1. Clean profile release channel
1. Install 1.50.x release channel
1. Run Brave with command line:
```
--enable-logging=stderr --vmodule="*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6,"*/bat_ads/*"=6,"*/whats_new/*"=9 --variations-server-url=https://test --rewards=staging=true --use-dev-goupdater-url --force-fieldtrials="WhatsNewStudy/Enabled" --force-fieldtrial-params="WhatsNewStudy.Enabled:target_major_version_stable/1.51"
```
1. Close Brave
1. Install 1.51.x release channel
1. Run Brave using:
```
--enable-logging=stderr --vmodule="*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6,"*/bat_ads/*"=6,"*/whats_new/*"=9 --variations-server-url=https://test --rewards=staging=true --use-dev-goupdater-url --force-fieldtrials="WhatsNewStudy/Enabled" --force-fieldtrial-params="WhatsNewStudy.Enabled:target_major_version_stable/1.51"
```

Verified `what's new` page is shown 
![image](https://user-images.githubusercontent.com/34715963/234988912-1c1628ab-2b32-469d-b14a-1bef27806e4a.png)


</details>

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.51.106 Chromium: 113.0.5672.53 (Official Build) (x86_64)
-- | --
Revision | 12f5dac35d12e8f4e72d7dd11df557ef93bc046f-refs/branch-heads/5672@{#703}
OS | macOS Version 13.4 (Build 22F5049e)

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on 

```
Brave | 1.51.106 Chromium: 113.0.5672.53 (Official Build) (64-bit)
-- | --
Revision | 12f5dac35d12e8f4e72d7dd11df557ef93bc046f-refs/branch-heads/5672@{#703}
OS | Windows 10 Version 21H2 (Build 19044.2846)
```
