### ISSUE TITLE
`Can't connect to server` error message shown when switched regions in the VPN panel when connected via `Already purchased VPN` link in desktop 2

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#28941]
## Description 

This issue specifically relates to clicking the link `Already purchased VPN` in `onboarding/Buy` modal after logging into desktop 2 with existing prod VPN credentials.  In this case, after successfully logging, I didn't click `Refresh Brave VPN` button, instead clicked  `VPN` button =>`Already purchased VPN` link in the `Buy modal`.  When I toggle `On` from `Disconnected` to `Connected`, it was successfully connected. However, it failed with `Can't connect to server` error message error when switched from default locale `US ( West)`  to `Canada`.

## Steps to Reproduce

   1.   Install 1.49.118
   2.   launch Brave
   3.   enable `brave://flags/#brave-vpn`
   4.   login to desktop 2 with already purchased Brave prod VPN credentials 
   5.   click on `VPN` button next to hamburger menu
   6.   click `Already purchased VPN` link
   7.   successfully connected when toggled `On` from `Disconnected` to `Connected` in the VPN panel
   8.   select another region `Canada` 
  
   
## Actual result:

`Can't connect to server` error message shown 

https://user-images.githubusercontent.com/98358127/223520518-14c65306-807d-421d-b228-0dc761015799.mp4

 Unfortunately I didn't grab logs today. These logs are from yesterday's testing with same scenario.
```
[27952:26596:0306/133735.035:WARNING:CONSOLE(952)] "Connection has failed", source: chrome-untrusted://vpn-panel.top-chrome/brave_vpn_panel.bundle.js (952)
```
## Expected result:
Brave VPN should connect successfully to other regions without errors

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.49.118 Chromium: 111.0.5563.50 (Official Build) (64-bit)
-- | --
Revision | 39f3dfc5023fe60997adc4f6cf5439cfa3e6968a-refs/branch-heads/5563@{#903}
OS | Windows 11 Version 22H2 (Build 22621.1265)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel?  N/A
- Can you reproduce this issue with the nightly channel?  N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
 @bsclifton  @mattmcalister

**Comment by mattmcalister** [comment]
Closing as stale
