### ISSUE TITLE
"Lock Private tabs when you leave Brave" present in release (with visual issues), missing in beta and nightly

### ISSUE THREAD

**Issue by wknapik** [brave/brave-browser#28958]
The "Lock Private tabs when you leave Brave" feature is present in 1.48.171 on Android, under Settings -> Brave Shields & privacy. 

That option is missing in 1.50.83 and 1.51.16. I hope it hasn't been removed.

On release channel, when the option is enabled, along with the dark theme, and the user tries to access a private tab after switching away from the browser, a screen is presented where the fingerprint can be used to unlock. That screen contains a dark blue background, with a white square in the middle (?) and an orange button at the bottom, with slightly darker orange text on it saying "Unlock Private", which needs to be pressed to bring up the fingerprint dialog. This looks really bad and could lock the user out of their browser entirely, if they don't figure it out. It gets worse if that screen is accessed from regular tabs, since there's an extra bar at the bottom, which obscures half of the orange button with orange text, lowering the likelihood that anyone will be able to read the text on it pretty much to zero.

I'd take a screenshot, but I get en error saying "this action isn't allowed by the app or your organization".

**Comment by samartnik** [comment]
This was temporarily disabled https://github.com/brave/brave-browser/issues/29786
Should be tested in the context of the https://github.com/brave/brave-browser/issues/29688

**Comment by CodeCubeNeo** [comment]
Any ETA?

**Comment by deeppandya** [comment]
@CodeCubeNeo i have added the issue : https://github.com/brave/brave-browser/issues/29688 for further discussion.

**Comment by Z04RD** [comment]
For me the "private tab lock" does not work on my main phone. I have Android 10 on my Huawei Mate 10 pro. 
On my Samsung Galaxy S23 SF I have Android 14, the exact same version of Brave (1.74.51) and the option wiuthin the security settings to turn this feature on is presen, but on my aAte 10 pro it doesn't evcen show up in the Security options. Is it an Android version issue? Both phones have fingerprint and face rrecognition capabilities, I1m using the fingerprint on both, yet this security feature is not available. Why?
