### ISSUE TITLE
Wallet signing UI does not appear when provided a partially signed Solana transaction with a different fee payer

### ISSUE THREAD

**Issue by steveluscher** [brave/brave-browser#28955]
## Description 

@mcintyre94 and @yamijuan encountered a failure of the signing UI to appear when a Solana transaction provided is partially signed (eg. because someone other than the identity wants to act as a the fee payer).

## Steps to Reproduce

From @mcintyre94:

> I've been able to repro this issue with a slightly modified version of our solana-pay-scaffold: https://github.com/mcintyre94/solana-pay-scaffold (change-fee-payer branch)
>
> To test it, copy .env.example to .env, put any private key with devnet SOL in as `WALLET_PRIVATE_KEY`, yarn, yarn dev. Click connect wallet (use a different one to the .env one) and then send with wallet on the transaction request page (localhost:3000/)
>
> The main branch uses a simple transaction with no other signers and works correctly in Brave, the change-fee-payer branch has the same issue reported here
>
> I've also tested the `window.solana.signAndSendTransaction()` and the behaviour is exactly the same
## Actual result:

Wallet extension opens but no signing UI appears.

## Expected result:

Signing UI should appear

## Reproduces how often: 

Always.

## Brave version (brave://version info)

Brave | 1.48.171 Chromium: 110.0.5481.177 (Official Build) (arm64)
-- | --
Revision | f34f7ab2d4ca4ad498ef42aeba4f4eb2c1392d63-refs/branch-heads/5481@{#1239}
OS | macOS Version 13.2.1 (Build 22D68)

## Version/Channel Information:

Untested.

## Other Additional Information:

None.

## Miscellaneous Information:

None.

**Comment by yrliou** [comment]
See the test plan in the PR for easier testing steps without setting up a repo locally.

**Comment by kjozwiak** [comment]
The above requires `1.49.124` or higher for `1.49.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on Lenovo Tab with Android 12 running 1.49.126 x64 build
- Verified steps from [brave/brave-core#17553](https://github.com/brave/brave-core/pull/17553)
- Verified able to submit the transaction successfully

https://user-images.githubusercontent.com/17010094/226526845-aa6bfa7f-2457-4e22-a2e9-698acb47f3a0.mp4

----------------------
Verification passed on 

Brave | 1.49.126 Chromium: 111.0.5563.64 (Official Build) (64-bit)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Linux

- Verified steps from [brave/brave-core#17553](https://github.com/brave/brave-core/pull/17553)
- Verified able to submit the transaction successfully

https://user-images.githubusercontent.com/17010094/226527631-2a65ed3c-541f-4ef2-b47c-a2dfff4b92a2.mp4
