### ISSUE TITLE
Add Filecoin EVM to preloaded networks

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#28954]
https://chainlist.org/chain/314

**Comment by yrliou** [comment]
cc @cypt4

**Comment by kjozwiak** [comment]
The above requires `1.50.103` or higher for `1.50.x` verification 👍

**Comment by srirambv** [comment]
**Verification passed on** 

Brave | 1.50.106 Chromium: 112.0.5615.39 (Official Build) beta (64-bit) 
-- | --
Revision | `a0e7b9718a92bcd1cf33b7c95316caff3fc20714-refs/branch-heads/5615@{#753}`
OS | Linux

- Verified steps from [brave/brave-core#17563](https://github.com/brave/brave-core/pull/17563)
- Verified upon upgrade to `1.50.76`, `Filecoin EVM Mainnet -0x13a https://api.node.glif.io/rpc/v1` &  `Filecoin EVM Testnet - 0x4cb2f https://api.calibration.node.glif.io/rpc/v1` is shown under network list 
- Verified `Filecoin EVM Mainnet` is enabled by default and `Filecoin EVM Testnet` is disabled by default
- Verified able to send `FIL on Filecoin EVM Testnet` from one account to another
- Verified clicking on `View on blockchain explorer` loads the correct block explorer
- Verified sent transaction is listed under activity tab
- Verified selecting `FIL on Filecoin EVM Mainnet/Testnet` shows all the accounts that hold the balance of the token
- Verified able to hide network and hide the token from portfolio page

Transaction | Upgrade scenario
-- | --
<video src=https://user-images.githubusercontent.com/17010094/228179990-cacad033-0963-45c2-a93f-7041435a19c8.mp4> | <video src=https://user-images.githubusercontent.com/17010094/228180088-bf8714be-004e-427d-8a73-d1f62f450fbf.mp4>

---------------------

**Verification passed on** 

Brave | 1.50.106 Chromium: 112.0.5615.39 (Official Build) beta (64-bit)
-- | --
Revision | `a0e7b9718a92bcd1cf33b7c95316caff3fc20714-refs/branch-heads/5615@{#753}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from [brave/brave-core#17563](https://github.com/brave/brave-core/pull/17563)
- Verified upon upgrade to `1.50.78`, `Filecoin EVM Mainnet -0x13a https://api.node.glif.io/rpc/v1` &  `Filecoin EVM Testnet - 0x4cb2f https://api.calibration.node.glif.io/rpc/v1` is shown under network list 
- Verified `Filecoin EVM Mainnet` is enabled by default and `Filecoin EVM Testnet` is disabled by default
- Verified able to send `FIL on Filecoin EVM Testnet` from one account to another
- Verified clicking on `View on blockchain explorer` loads the correct block explorer
- Verified sent transaction is listed under activity tab
- Verified selecting `FIL on Filecoin EVM Mainnet/Testnet` shows all the accounts that hold the balance of the token
- Verified able to hide network and hide the token from portfolio page

Transaction | Upgrade scenario
-- | --
<video src=https://user-images.githubusercontent.com/17010094/228161341-691d3ec6-956f-4f2f-a54a-05030c77b31d.mp4> | <video src=https://user-images.githubusercontent.com/17010094/228162574-e46ce881-f08d-470c-84b9-dbd2fa6799ec.mp4>

**Mainnet Transaction**
- Verified able to send FIL on FEVM Mainnet
- Verified able to load block explorer from transaction menu/panel
- Verified able to show/hide token from portfolio page
- Eth Transaction Hash `0x41e30fbc33b8acee63700a1b509ea41d9329b8c34cd55fe852d3c1c8579ad3c1`

---------------------

**Verification passed on** 

Brave | 1.50.106 Chromium: 112.0.5615.39 (Official Build) beta (arm64)
-- | --
Revision | `a0e7b9718a92bcd1cf33b7c95316caff3fc20714-refs/branch-heads/5615@{#753}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#17563](https://github.com/brave/brave-core/pull/17563)
- Verified upon upgrade to `1.50.76`, `Filecoin EVM Mainnet -0x13a https://api.node.glif.io/rpc/v1` &  `Filecoin EVM Testnet - 0x4cb2f https://api.calibration.node.glif.io/rpc/v1` is shown under network list 
- Verified `Filecoin EVM Mainnet` is enabled by default and `Filecoin EVM Testnet` is disabled by default
- Verified able to send `FIL on Filecoin EVM Testnet` from one account to another
- Verified clicking on `View on blockchain explorer` loads the correct block explorer
- Verified sent transaction is listed under activity tab
- Verified selecting `FIL on Filecoin EVM Mainnet/Testnet` shows all the accounts that hold the balance of the token
- Verified able to hide network and hide the token from portfolio page

Transaction | Upgrade scenario
-- | --
<video src=https://user-images.githubusercontent.com/17010094/228160043-c0584901-a5d3-4771-be8e-387f1e9bbf77.mp4>  | <video src=https://user-images.githubusercontent.com/17010094/228160072-2c3cc1fd-1912-4e3e-9ed3-9834dc57e040.mp4>
__________________________________________________________
