### ISSUE TITLE
Use Token Amount instead of Fiat Amount in Offramp Flow

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#28960]
## Description 

We need to update the `Offramp` flow to have the users enter the `Token` amount they want to sell instead of `Fiat` amount

- Enter crypto amount instead of fiat amount
- Remove fiat balances
- Remove the minimum threshold of `$50` for entered amount

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.51.103 Chromium: 112.0.5615.165 (Official Build) beta (64-bit) 
-- | --
Revision | `c262f36e6b1d711ee42d4fbe1343b49960593f18-refs/branch-heads/5615@{#1297}`
OS | Linux

- Verified steps from [brave/brave-core#17535](https://github.com/brave/brave-core/pull/17535)
- Verified input amount is now taking `Token` amount and not `Fiat` amount
- Verified minimum $50 sell amount message is not shown anymore
- Verified input amount is carry forwarded to the off-ramp page

https://user-images.githubusercontent.com/17010094/234499656-46c44a51-9e7f-4c3e-8f32-d3c1c1932bf1.mp4

---------------------

**Verification passed on**

Brave | 1.51.103 Chromium: 112.0.5615.165 (Official Build) beta (64-bit)
-- | --
Revision | `c262f36e6b1d711ee42d4fbe1343b49960593f18-refs/branch-heads/5615@{#1297}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from [brave/brave-core#17535](https://github.com/brave/brave-core/pull/17535)
- Verified input amount is now taking `Token` amount and not `Fiat` amount
- Verified minimum $50 sell amount message is not shown anymore
- Verified input amount is carry forwarded to the off-ramp page

https://user-images.githubusercontent.com/17010094/234499847-7df60044-8344-4407-ae41-1022202f0420.mp4


---------------------

**Verification passed on**

Brave | 1.51.103 Chromium: 112.0.5615.165 (Official Build) beta (arm64)
-- | --
Revision | `c262f36e6b1d711ee42d4fbe1343b49960593f18-refs/branch-heads/5615@{#1297}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#17535](https://github.com/brave/brave-core/pull/17535)
- Verified input amount is now taking `Token` amount and not `Fiat` amount
- Verified minimum $50 sell amount message is not shown anymore
- Verified input amount is carry forwarded to the off-ramp page

https://user-images.githubusercontent.com/17010094/234500094-9ff78af1-a2a9-49f7-a3ec-2afa11a4de9f.mov
