### ISSUE TITLE
Session storage for VPN linking lost during login

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#28963]
## Description 
When a person has VPN purchased as in-app-purchase, they can link it using the account.brave.com website

In product, they'd go to Brave Firewall + VPN and link account. This asks the user to login which involves sending an email with a magic link.

If you click the link instead of copying it into your browser, it opens a new session (new tab) which no longer has the purchase token information shared. When doing a link the user is met with an error (see screenshot below)

## Steps to reproduce 

   1. Have VPN purchased on Android
   2. Go to `Settings` > `Brave Firewall + VPN`
   3. Click link to link account
   4. account.brave.com is pulled up (if inspected, the `braveVpn.receipt` value will be there in session storage)
   5. You'll be prompted for email. Enter and click OK
   6. Check email
   7. Don't copy/paste URL into your original window. Instead, either open a new tab and paste OR click the link (if you're using webmail which will open in Brave)

## Actual result 
![image](https://user-images.githubusercontent.com/4733304/223879690-b0946864-c006-4e72-96f6-97c050649218.png)

## Expected result
Details should be readable by account.brave.com website

## Issue reproduces how often 
100%

**Comment by Uni-verse** [comment]
Verification on Nightly channel (1.51.x) has been completed per https://github.com/brave/brave-core/pull/17537#issuecomment-1485896568.

**Comment by kjozwiak** [comment]
> Verification on Nightly channel (1.51.x) has been completed per [brave/brave-core#17537 (comment)](https://github.com/brave/brave-core/pull/17537#issuecomment-1485896568).

Just a quick heads up that we usually don't add the `QA Pass` label when checking something on Nightly when uplifting as the issue we'll need to get reverified on the landed branch. So for this example, we'll need to check/verify the above on `1.50.x`. The verification on Nightly as basically to ensure that were not uplifting something that's obviously broken/causing regressions.

**Comment by kjozwiak** [comment]
The above requires `1.50.107` or higher for `1.50.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung GS 21 5G` using the following version(s):

```
Brave	1.50.113 Chromium: 112.0.5615.49 (Official Build) (64-bit) 
Revision	bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS	Android 13; Build/TP1A.220624.014
```
Test Steps: https://github.com/brave/brave-browser/issues/28963#issue-1616165980

- Ensured that braveVPN.receipt was shown in localStorage
- Ensured that braveVPN.receipt was removed from sessionStorage
- Ensured that user is able to link credentials in the same tab when using the email link (tapping link)

account.brave.com (localStorage) | accuont.brave.com (sessionStorage) | Email Link | Connecting | Account Plans
-|-|-|-|-
<img width="1309" alt="Screen Shot 2023-04-04 at 10 30 14 PM" src="https://user-images.githubusercontent.com/17885425/229967151-e8b9eeaf-c489-481d-9769-60d37980c157.png"> | <img width="1307" alt="Screen Shot 2023-04-04 at 10 30 28 PM" src="https://user-images.githubusercontent.com/17885425/229967152-68a2bf8e-7a37-469c-bd48-f3a68a282ebf.png"> | <img width="1309" alt="Screen Shot 2023-04-04 at 10 31 59 PM" src="https://user-images.githubusercontent.com/17885425/229967154-0ab161f4-0368-4b62-b0fb-78947d298015.png"> | <img width="1306" alt="Screen Shot 2023-04-04 at 10 32 17 PM" src="https://user-images.githubusercontent.com/17885425/229967155-2b89dbe9-7930-4c94-9464-6df93f89641a.png"> | <img width="1308" alt="Screen Shot 2023-04-04 at 10 32 36 PM" src="https://user-images.githubusercontent.com/17885425/229967157-26e525d4-2979-4a14-9734-306d248594b6.png">
