### ISSUE TITLE
Adblock setting doesn't show option selected under shields

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#28975]
## Description 
Adblock setting not selected under shields panel. 

Regression with 1.49.x, upgrading from 1.48.x causes this UI issue in shields

## Steps to reproduce 

   1. Install 1.49.x or upgrade from 1.48.x to 1.49.x
   2. Load a webpage
   3. Tap on shields icon to open shields settings
   4. Tap on `Block trackers & ads`

## Actual result 
Example | Example | Example
-|-|-
![screenshot-1678380954373](https://user-images.githubusercontent.com/17885425/224099986-ab10f44c-5fb3-4956-aee7-fac746385dd0.png) | ![screenshot-1678380992352](https://user-images.githubusercontent.com/17885425/224099990-6b71b629-4e34-4409-97fc-e65fd0d05907.png) | ![screenshot-1678376027326](https://user-images.githubusercontent.com/17885425/224100048-a829ae46-4ee3-4204-9bc8-8a8bbb34f52b.png)

## Expected result
<img width="500" alt="expected result" src="https://user-images.githubusercontent.com/17885425/224100280-7a86e8a1-18aa-4a91-b82d-bd6696fe8b9b.png">

## Issue reproduces how often 
Always

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung GS 21, Tab S7
   - Android version: 13, 12
   
## Brave version
`1.49.20, Chromium 111.0.5563.64`

**Comment by GeetaSarvadnya** [comment]
Reproduced on `Samsung Galaxy version 12` running `Bravemonoarm64.apk_1.49.120`

**Comment by kjozwiak** [comment]
The above requires `1.49.122` or higher for `1.49.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung GS 21` using version: 

```
Brave	1.49.122 Chromium: 111.0.5563.64 (Official Build) (64-bit) 
Revision	c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS	Android 13;
```

**Fresh Profile:** 

1. Install `1.49.122, Chromium 111.0.5563.64`
2. Load a webpage
3. Tap on shields icon to open shields settings
4. Tap on Block trackers & ads
5. Open Youtube.com and confirm preroll ads are blocked

**Existing Profile (1.49.x)**

1. Install `1.49.20`
2. Open various webpages
3. Open shields and confirm Adblock setting is not populated, ensure a similar amount of ads are being blocked on the page.
4. Update to version `1.49.122`
5. Open shields and confirm adblock setting is populated (standard setting)
6. Open buzzfeed.com & youtube.com to make sure content ads and pre-roll video ads are removed.

**Existing Profile (1.48.171 -> 1.49.122.x)**

1. Install app store version
2. Open various web pages and change some settings around (leave adblock as default)
3. Load some videos on youtube
4. Upgrade to version 1.49.122
5. Check that adblock settings are populated and shields are working

- Ensured that `Block trackers & ads` setting is populated under shields panel on `fresh profile` as well as `upgraded profile`
- Ensured that changing `global settings` will take effect on sites
- Ensured that pre-roll ads as well as content ads are blocked

1.49.120 | 1.49.122
-|-
![screenshot-1678416639549](https://user-images.githubusercontent.com/17885425/224212605-0feb05a3-e877-40aa-b413-6e9917d5b744.png) | ![screenshot-1678416758729](https://user-images.githubusercontent.com/17885425/224212613-674b0c55-cb96-423a-8667-c6e87e6b9550.png)
![screenshot-1678416633915](https://user-images.githubusercontent.com/17885425/224212645-94123a5b-6a56-4bdb-8e1f-9060bb564b9e.png) | ![screenshot-1678416752269](https://user-images.githubusercontent.com/17885425/224212679-b6c02dcb-bc72-49e2-95f3-3ed9afee8111.png)
