### ISSUE TITLE
Copy clean link is shown for plain text

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#28973]
## Description 

This bug was introduced here https://github.com/brave/brave-core/pull/17494

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/2965009/224054084-6b50e7f5-617f-413d-bfda-e4948e8d26d4.png">

## Steps to Reproduce

   1.  Select any plain text on pages
   2. Click by right mouse button to show the context menu for the selection
   3. "Copy clean link" item will be visible in the context menu

## Actual result:

"Copy clean link" item will be visible in the context menu

## Expected result:

"Copy clean link" is visible only for selected urls

## Reproduces how often: 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.49.126` or higher for `1.49.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.49.126 Chromium: 111.0.5563.64 (Official Build) (x86_64)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | macOS Version 12.6.3 (Build 21G419)
```

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.49.126 Chromium: 111.0.5563.64 (Official Build) (64-bit)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | Ubuntu 18.04 LTS

Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/28973#issue-1617360793, ensured that the `Copy clean link` item is not being added into the context menu for plain text as per the following:

* ensured that plain text doesn't include the `Copy clean link` item within the right click context menu
* ensured that `Copy clean link` is available for links
* ensured that `Copy clean link` is available for image links
* ensured that all tests under https://fmarier.github.io/brave-testing/copy-clean-link.html are passing as expected

<details>

![image](https://user-images.githubusercontent.com/34715963/226623501-6df8f911-0485-4add-b329-e841069b22d2.png)
![image](https://user-images.githubusercontent.com/34715963/226623683-7d1398e8-0e62-48fa-8f7d-22e1cd10ccf9.png)
![image](https://user-images.githubusercontent.com/34715963/226623856-71443104-a36d-47ef-b52f-2b0b9893dc03.png)


</details>

Logged https://github.com/brave/brave-browser/issues/29210

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.49.126 Chromium: 111.0.5563.64 (Official Build) (64-bit)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | Windows 10 Version 22H2 (Build 19045.2728)

Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/28973#issue-1617360793, ensured that the `Copy clean link` item is not being added into the context menu for plain text as per the following:

* ensured that plain text doesn't include the `Copy clean link` item within the right click context menu
* ensured that `Copy clean link` is available for links
* ensured that `Copy clean link` is available for image links
* ensured that all tests under https://fmarier.github.io/brave-testing/copy-clean-link.html are passing as expected

<details>

![image](https://user-images.githubusercontent.com/34715963/226631834-89ce0e24-d8e4-463c-94c9-83ea4c2e3074.png)
![image](https://user-images.githubusercontent.com/34715963/226632110-54391349-4e23-4d3c-ae97-86e82524a3d4.png)
![image](https://user-images.githubusercontent.com/34715963/226632439-80f864c1-9666-43bf-b267-81bc4f7ea06d.png)


</details>
