### ISSUE TITLE
Reland again brave/brave-core/pull/17431

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#28978]
PR brave/brave-core/pull/17431 was reverted twice:
- https://github.com/brave/brave-core/pull/17451 - it broke any Release build;
- https://github.com/brave/brave-core/pull/17526 - it broke Stable builds after reland.

Original issue: https://github.com/brave/brave-browser/issues/28831
Original PR: https://github.com/brave/brave-core/pull/17431

Test plan:
1. Ensure Stable channel Release build is not broken:
`npm run build -- Release --target_arch=x86 --target_android_base=mono --target_os=android --target_android_output_format=apk`;
2. Ensure there is no crash on app start and possible to pass onboarding.

**Comment by kjozwiak** [comment]
As per https://github.com/brave/brave-core/pull/17545#issue-1617849518, the QA will basically run through the STR/Cases every time we install the app while running through `1.51.x` verifications. So this will get verified several times by default. Labelling as `QA/No`.

**Comment by AlexeyBarabash** [comment]
:+1:
