### ISSUE TITLE
unexpected ads notification shown when changing application focus

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#2898]
## Steps to Reproduce

1. Clean profile
2. Enable rewards and ads
3. Open new tab and load `https://hotel-deals.club/`
4. Focus Brave
5. Wait 30 seconds
6. Focus another application

Optional:
7. Wait 30 seconds
8. Focus Brave

## Actual result:

IMPORTANT: those notifications can exceed the max number of ads per hour
IMPORTANT: those notifications are always triggered thus the system can be gamed.

Focus change: Brave->Other App
this one doesn't look good, because the ad notification will be shown when Other App is in focus. Looks like Other App's notification.
![ads 2](https://user-images.githubusercontent.com/34715963/50984028-1ac85d00-1501-11e9-9522-6e4457f08745.gif)

Focus change: Other App->Brave
![ads 1](https://user-images.githubusercontent.com/34715963/50983984-fd938e80-1500-11e9-9af5-b84c49537508.gif)

## Expected result:
Only show ads notification when Brave is in focus.
Do not exceed the max number of ads per hour

## Reproduces how often: 

always

## Brave version (brave://version info)

Brave | 0.60.9 Chromium: 72.0.3626.28 (Official Build) dev (64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Windows

Reproduced on Windows 7 and Windows 10

cc: @bridiver @jsecretan @brave/legacy_qa

**Comment by btlechowski** [comment]
After further investigation it seems that the issue only reproduces when `iab.com` is opened in one of the tabs. The behavior seems intentional. Closing as invalid.

**Comment by bridiver** [comment]
@archlemon the ad notifications are not related to the active tab. They are triggered by a background mechanism and they can only be globally disabled/enabled. Any site settings to disable html5 notifications still apply as normal.
