### ISSUE TITLE
NFT Pinning design updates

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#28986]
**Banner** 

- Layout
- Color(Dark theme)

![Image](https://user-images.githubusercontent.com/48117473/224352099-70c4f305-17db-4bba-9221-2065c3192cf9.png)

**NFT IPFS main**

- Text update
- Keep only one CTA button “Keep my NFTs always online”

![Image](https://user-images.githubusercontent.com/48117473/224352194-a2b1af91-84d8-4835-a956-9fde0d354bbf.png)

**Available to pin screen**

- Network icon update
- Image update
- Tooltip
- Layout adjustment

![Image](https://user-images.githubusercontent.com/48117473/224352337-84898004-2e45-4d28-97e8-7369e5749f2a.png)

**NFT detail screen - Screenshot 4**

- Pinning status dark theme
- Tooltip

![Image](https://user-images.githubusercontent.com/48117473/224352535-9a63dc57-72d0-45e0-a45b-e66bf6e1007f.png)

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.51.80 Chromium: 112.0.5615.49 (Official Build) beta (64-bit) 
-- | --
Revision | `bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

<details>
<summary>Verified steps from issue description and <a href=https://github.com/brave/brave-core/pull/17557>brave/brave-core#17557</a></summary>
<br>

- Verified UI updates to NFT pinning

Banner Main

Light | Dark
-- | --
![brave_ak6bBtlf92](https://user-images.githubusercontent.com/17010094/230871459-6d3d1557-d4a1-4602-b183-1ae30a6f1f4f.png) | ![brave_7dW30wj7r0](https://user-images.githubusercontent.com/17010094/230871385-f579f1ef-197f-453a-8fb8-71a139a2e1af.png)

Banner Uploading

Light | Dark
-- | --
![brave_PZr9Lm3css](https://user-images.githubusercontent.com/17010094/230871484-ca9b68e7-ea41-4624-97ea-4fab743df11d.png) | ![brave_rdQhXXBdM2](https://user-images.githubusercontent.com/17010094/230871504-d743a262-43e8-4d2e-ad9e-0a74e66ac54b.png)

Banner Success

Light | Dark
-- | --
![brave_qp231uQQmx](https://user-images.githubusercontent.com/17010094/230871568-d36a641d-9a0d-4ffc-b899-f32dd61ec7d7.png) | ![brave_3Vhvoaj6Zn](https://user-images.githubusercontent.com/17010094/230871558-a189f9cf-2fda-4da6-afe0-e6f9ab118e82.png)

NFT-IPFS Interstitial page

Light | Dark 
-- | --
![brave_wsY4POWQAr](https://user-images.githubusercontent.com/17010094/230871223-46a7a82c-6970-423d-8fa9-15517f1b69f1.png) | ![brave_2lTcILlwMj](https://user-images.githubusercontent.com/17010094/230871260-b58f2c3d-fa48-47ca-aca8-02fd2a566a0c.png)

NFT-IPFS Interstitial page (Available NFT pins)

Light | Dark 
-- | --
![brave_IYU6mvS6Ew](https://user-images.githubusercontent.com/17010094/230871184-cbb8518b-1a0b-4716-8384-770a8b9d18bc.png) | ![brave_6oR0SRaNmg](https://user-images.githubusercontent.com/17010094/230871168-25dc35fb-747c-423f-b628-e73b0087f5ee.png)

NFT Details page

Light | Dark 
-- | --
![brave_zl6AMlqTno](https://user-images.githubusercontent.com/17010094/230871105-3328f636-00e8-4bef-8311-039dc8bc3bae.png) | ![brave_d3zFdGuFrs](https://user-images.githubusercontent.com/17010094/230871127-21bb820d-8937-4245-9a57-29463c1c436f.png)

- Encountered [brave-browser#29514](https://github.com/brave/brave-browser/issues/29514)
</details>

---------------------

**Verification passed on**

Brave | 1.51.80 Chromium: 112.0.5615.49 (Official Build) beta (64-bit)
-- | --
Revision | `bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}`
OS | Linux

<details>
<summary>Verified steps from issue description and <a href=https://github.com/brave/brave-core/pull/17557>brave/brave-core#17557</a></summary>
<br>

- Verified UI updates to NFT pinning

Banner Main

Light | Dark
-- | --
![image](https://user-images.githubusercontent.com/17010094/230875344-32221154-47b2-4b89-9ba5-70dcda546b85.png) | ![image](https://user-images.githubusercontent.com/17010094/230875373-da3e5e7c-f1cf-4202-9c44-d86bc4a4cff3.png)


Banner Uploading

Light | Dark
-- | --
![image](https://user-images.githubusercontent.com/17010094/230875612-625756a7-de53-4d67-a42a-cdf37e9bce57.png) | ![image](https://user-images.githubusercontent.com/17010094/230875710-66d6ce34-4244-4504-a1c0-499136b886ef.png)


Banner Success

Light | Dark
-- | --
![image](https://user-images.githubusercontent.com/17010094/230876120-5531afd9-ebfa-4545-9782-d372cdf4b06b.png) | ![image](https://user-images.githubusercontent.com/17010094/230875004-0d857aed-cbbe-453e-8ed0-3efcf734c4ca.png)


NFT-IPFS Interstitial page

Light | Dark 
-- | --
![image](https://user-images.githubusercontent.com/17010094/230875500-545a79c2-a36a-442e-a9af-4f686cca9915.png) | ![image](https://user-images.githubusercontent.com/17010094/230875411-ebcae2b7-dfe9-4c40-975b-6209f7d67de9.png)



NFT-IPFS Interstitial page (Available NFT pins)

Light | Dark 
-- | --
![image](https://user-images.githubusercontent.com/17010094/230875472-0ab4d144-37c2-4f09-8772-81d145a67a0f.png) | ![image](https://user-images.githubusercontent.com/17010094/230875441-70f933a2-ffbb-49a9-b00a-e278a99bc998.png)


NFT Details page

Light | Dark 
-- | --
![image](https://user-images.githubusercontent.com/17010094/230875862-e00c720f-726d-45b5-90e0-a86a775291d1.png) | ![image](https://user-images.githubusercontent.com/17010094/230875878-e25e475c-ae41-4938-a25c-17e7e14b3729.png)


- Encountered [brave-browser#29514](https://github.com/brave/brave-browser/issues/29514)
</details>

---------------------

**Verification passed on**

Brave | 1.51.80 Chromium: 112.0.5615.49 (Official Build) beta (arm64)
-- | --
Revision | `bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}`
OS | macOS Version 13.0 (Build 22A380)

<details>
<summary>Verified steps from issue description and <a href=https://github.com/brave/brave-core/pull/17557>brave/brave-core#17557</a></summary>
<br>

- Verified UI updates to NFT pinning

Banner Main

Light | Dark
-- | --
![bannermainlight](https://user-images.githubusercontent.com/17010094/230872508-4477078a-4547-4e13-a8e8-3cbafb5d9f3a.png) | ![bannermaindark](https://user-images.githubusercontent.com/17010094/230872529-0f2b64ac-96a6-4c64-a508-338776899fe7.png)

Banner Uploading

Light | Dark
-- | --
![banneruploadrk](https://user-images.githubusercontent.com/17010094/230874030-5ac016b5-a1cd-4f3f-8570-7fb2a4236fb9.png) | ![banneruploadlgt](https://user-images.githubusercontent.com/17010094/230874018-df18e1eb-615b-4b11-9c08-97fc569db888.png)

Banner Success

Light | Dark
-- | --
![successlight](https://user-images.githubusercontent.com/17010094/230872504-9afb09ed-88d1-4bef-9997-826d2f22cc11.png) | ![successdark](https://user-images.githubusercontent.com/17010094/230872490-a370ac5e-391b-4f9e-8487-43ddcd77ab7d.png)

NFT-IPFS Interstitial page

Light | Dark 
-- | --
![interstitial2light](https://user-images.githubusercontent.com/17010094/230872551-94af4cbd-5845-45ce-b099-a804f6261ed9.png) | ![interstitial2dark](https://user-images.githubusercontent.com/17010094/230872573-6c2a42c3-ef8c-4777-ba88-eafda8daeff4.png)

NFT-IPFS Interstitial page (Available NFT pins)

Light | Dark 
-- | --
![interstitial1light](https://user-images.githubusercontent.com/17010094/230872560-dfc34d30-3afd-47ec-ad5a-c10a9b06969d.png) | ![interstitial1dark](https://user-images.githubusercontent.com/17010094/230872563-6510c0f9-f587-45a9-8762-63db9a553229.png)

NFT Details page

Light | Dark 
-- | --
![nftdetailslight](https://user-images.githubusercontent.com/17010094/230872545-569fede1-e3a7-4f26-a8b6-e2d292a95a14.png) | ![nftdetailsdark](https://user-images.githubusercontent.com/17010094/230872537-96e0c657-bf1c-4e1d-9c24-907de40b086f.png)

- Encountered [brave-browser#29514](https://github.com/brave/brave-browser/issues/29514)
</details>
