### ISSUE TITLE
Copy text from image

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#29003]
## Description 
Exact same feature / capability as https://github.com/brave/brave-browser/issues/27513 (macOS) - but on Windows and Linux

Unlike macOS, there isn't a clear API to use. That'll be the challenging part of this task

**Comment by luquinhaspmw** [comment]
is it working on windows?

**Comment by bsclifton** [comment]
@luquinhaspmw no, this feature is not available on Windows (yet). There are some leads we have about something which might work. I'll add those to the ticket soon here

**Comment by simonhong** [comment]
### Investigations  on Windows
It seems chromium already service `TextDetection::Detect` interface(`textdetection.mojom`) via `ShapeDetectionService` service (`shape_detection_service.mojom`).
To use that service, we need to launch `ShapeDetectionService` and bind `TextDetection`.
After that, we could call `TextDetection::Detect(skia.mojom.BitmapN32 bitmap_data)` to get text from bitmap.
```
shape_detection::mojom::ShapeDetectionService* GetShapeDetectionService() {
  static base::NoDestructor<
      mojo::Remote<shape_detection::mojom::ShapeDetectionService>>
      remote;
  if (!*remote) {
#if BUILDFLAG(GOOGLE_CHROME_BRANDING) && BUILDFLAG(IS_CHROMEOS)
    ServiceProcessHost::Launch<shape_detection::mojom::ShapeDetectionService>(
        remote->BindNewPipeAndPassReceiver(),
        ServiceProcessHost::Options()
            .WithDisplayName("Shape Detection Service")
            .Pass());
#else
    auto* gpu = GpuProcessHost::Get();
    if (gpu)
      gpu->RunService(remote->BindNewPipeAndPassReceiver());
#endif
    remote->reset_on_disconnect();
  }

  return remote->get();
}
```
```
void BindTextDetection(
    mojo::PendingReceiver<shape_detection::mojom::TextDetection> receiver) {
  GetShapeDetectionService()->BindTextDetection(std::move(receiver));
}
```
