### ISSUE TITLE
systemTimestamp user data should be regenerated for confirmation retries

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#29005]

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.51.80 Chromium: 112.0.5615.49 (Official Build) beta (64-bit) 
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Ubuntu 18.04 LTS

Verified the test plan from https://github.com/brave/brave-core/pull/17584

<details>


</details>
