### ISSUE TITLE
NFT-IPFS  Icon is only shown on hover

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#29009]
## Description 

NFT Icon is only shown on hover

## Steps to Reproduce

   1. Install 1.50.x 
   2. Enable `brave://flags/#enable-nft-pinning`
   3. Go to NFT Tab
   4. IPFS pinning icon is not shown
   5. Hover over the button, shows NFT icon

## Actual result:

https://user-images.githubusercontent.com/17010094/224611342-25bbcb62-3f1f-4e24-a203-536118cf32eb.mp4

## Expected result:
Should show the button icon always

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.50.85 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @muliswilliam @Douglashdaniel

**Comment by muliswilliam** [comment]
Fixed here: https://github.com/brave/brave-core/pull/17557

**Comment by kjozwiak** [comment]
The above requires `1.51.79` or higher for `1.51.x` verification 👍

**Comment by srirambv** [comment]
**Verification passed on **

Brave | 1.51.80 Chromium: 112.0.5615.49 (Official Build) beta (64-bit) 
-- | --
Revision | `bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}`
OS | Linux

- Verified steps from issue description
- Verified NFT-IPFS Icon is always shown
- Verified on hover changes the button colour
- Verified still able to click the button to show/hide the message
- Verified button visibility on both dark and light theme

https://user-images.githubusercontent.com/17010094/230869139-7350dc5c-2147-4934-94d1-9c49010bcc5e.mp4


---------------------

**Verification passed on**

Brave | 1.51.80 Chromium: 112.0.5615.49 (Official Build) beta (64-bit)
-- | --
Revision | `bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from issue description
- Verified NFT-IPFS Icon is always shown
- Verified on hover changes the button colour
- Verified still able to click the button to show/hide the message
- Verified button visibility on both dark and light theme

https://user-images.githubusercontent.com/17010094/230868983-60523eb8-9375-43a3-b091-3025bc8c5afa.mp4


---------------------

**Verification passed on**

Brave | 1.51.80 Chromium: 112.0.5615.49 (Official Build) beta (arm64)
-- | --
Revision | `bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from issue description
- Verified NFT-IPFS Icon is always shown
- Verified on hover changes the button colour
- Verified still able to click the button to show/hide the message
- Verified button visibility on both dark and light theme

https://user-images.githubusercontent.com/17010094/230869334-fe270a7e-5205-494c-bd78-6b77c83a973b.mov
