### ISSUE TITLE
收藏栏是否可以自定义拖动，block？

### ISSUE THREAD

**Issue by 839781960** [brave/brave-browser#29014]
## Description 

拖动？
![image](https://user-images.githubusercontent.com/114645865/224673288-5a716b69-57a4-48e7-8f7f-bba7cf58cd61.png)

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
它可以隐藏，但不能移动。 转到自定义仪表板以隐藏常用站点。 我希望这能回答你的问题。
