### ISSUE TITLE
NFT edit button is not visible on light background

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#29011]
## Description 

NFT edit button is not visible on light background

## Steps to Reproduce

   1. Add a bunch of NFT with light and dark background
   2. Edit menu is shown on dark themed NFT's
   3. Edit menu is not visible on light themed NFT's 

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/224650370-6fe54759-645d-4ea7-9824-191a73f08243.png)

## Expected result:
Edit menu should be visible on all NFT's

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.50.85 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @muliswilliam @jamesmudgett @kleantzogu @minkyeongshin

**Comment by muliswilliam** [comment]
@srirambv This is fixed with the current nightly

**Comment by srirambv** [comment]
@muliswilliam can you please link the PR and close this issue as dupe of the issue that the pr fixes it?

**Comment by muliswilliam** [comment]
@srirambv The PR that fixes this: https://github.com/brave/brave-core/pull/18493. Closing as dupe.
