### ISSUE TITLE
Developer Tools - Network Tab - Right Click doesn't work on request items

### ISSUE THREAD

**Issue by bitroniq** [brave/brave-browser#29022]
## Description 

Developer Tools - Network Tab - Right Click doesn't work on request items.

## Steps to Reproduce

   1.  Open Brave on Win11
   2.  Open any page
   3.  F12 to open Developer Tools
   4.  Switch to the Network tab
   5.  Left Click on the network request
   6. Right-click on it

## Actual result:

Nothing happens

## Expected result:

The context menu should show up.

## Reproduces how often: 

Always

## Desktop Brave version:

Brave | 1.49.120 Chromium: 111.0.5563.64 (Official Build) (64-bit)
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | Windows 11 Version 22H2 (Build 22621.1265)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
no

- Does the issue resolve itself when disabling Brave Rewards? 
no

- Is the issue reproducible on the latest version of Chrome? 
no - works fine on the latest chrome

## Miscellaneous Information:

As a workaround, I can open any page in Private Tab, then Right Click on network requests works fine.

For testing - I disabled all extensions in normal mode and restarted Brave - still right click doesn't work.

**Comment by thelyrebird** [comment]
I have gone through the same procedure on MacOS Ventura 13.2.1, Apple Silicion M1 Macbook Pro and I can confirm that the same issue exists with MacOS. 

[Version 1.49.128 Chromium: 111.0.5563.110 (Official Build) (arm64)](https://brave.com/latest/)

In a private window, the context menu appears and works as expected

**Comment by suicide** [comment]
Same issue on Arch Linux from AUR package (brave-bin)
Version 1.49.132 Chromium: 111.0.5563.147 (Official Build) (64-bit)

**Comment by bitroniq** [comment]
brave://version

```
Brave | 1.50.114 Chromium: 112.0.5615.49 (Official Build) (64-bit)
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Windows 11 Version 22H2 (Build 22621.1485)
```

Finally, it works

![image](https://user-images.githubusercontent.com/1032724/231252008-35f1d3fb-8ed6-410e-8049-6a590c040de0.png)

Closing the ticket
