### ISSUE TITLE
Token List in Panel needs alignment

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#29038]
## Description 

The `Token` list in the `Wallet` Panel needs text alignment.

## Steps to Reproduce

   1. Open the panel and click on `View Account Assets`
   2. The text alignments for `Name and Symbol` needs to be aligned `left`
   3. The text alignment for `Balances` needs to be aligned `right

## Actual result:

![Screenshot 9](https://user-images.githubusercontent.com/40611140/224794754-5056ead9-4a21-4620-8489-463ca8b6bbd6.png)

## Expected result:

![Screenshot 10](https://user-images.githubusercontent.com/40611140/224794802-6a6dc186-087d-42c3-bbb7-ea437316347a.png)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.51.103 Chromium: 112.0.5615.165 (Official Build) beta (64-bit) 
-- | --
Revision | `c262f36e6b1d711ee42d4fbe1343b49960593f18-refs/branch-heads/5615@{#1297}`
OS | Linux

- Verified steps from issue description and [brave/brave-core#17586](https://github.com/brave/brave-core/pull/17586)
- Verified `Name and Symbol` are left aligned
- Verified `Balances` are right aligned 

https://user-images.githubusercontent.com/17010094/234483148-e20c5ba4-f785-4a90-84a5-ed6e9069311f.mp4

---------------------

**Verification passed on**

Brave | 1.51.103 Chromium: 112.0.5615.165 (Official Build) beta (64-bit)
-- | --
Revision | `c262f36e6b1d711ee42d4fbe1343b49960593f18-refs/branch-heads/5615@{#1297}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from issue description and [brave/brave-core#17586](https://github.com/brave/brave-core/pull/17586)
- Verified `Name and Symbol` are left aligned
- Verified `Balances` are right aligned 

https://user-images.githubusercontent.com/17010094/234482552-1a18fe77-3672-4de0-b970-dae0b673e1dd.mp4


---------------------

**Verification passed on**

Brave | 1.51.103 Chromium: 112.0.5615.165 (Official Build) beta (arm64)
-- | --
Revision | `c262f36e6b1d711ee42d4fbe1343b49960593f18-refs/branch-heads/5615@{#1297}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from issue description and [brave/brave-core#17586](https://github.com/brave/brave-core/pull/17586)
- Verified `Name and Symbol` are left aligned
- Verified `Balances` are right aligned 

https://user-images.githubusercontent.com/17010094/234483428-d113e082-e87a-485b-9235-791f34d0082b.mov
