### ISSUE TITLE
NFT description should be moved below the image to view properly

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#29047]
## Description 

NFT description should be moved below the image to view properly

## Steps to Reproduce

   1. Add an NFT
   2. Start reducing the window size
   3. See the description text 

## Actual result:

<img width=300 src=https://user-images.githubusercontent.com/17010094/224909170-417fda80-7676-4daa-be64-3ebd86889265.png> | <img width=300 src=https://user-images.githubusercontent.com/17010094/224909407-2195db9c-86c8-4508-b160-f7ebaa8d267d.png>
-- | --

## Expected result:
Move text below the image when the screen size is reduced 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.51.29 Chromium: 111.0.5563.64 (Official Build) nightly (arm64)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel @muliswilliam

**Comment by Douglashdaniel** [comment]
This was addressed in `V2` updates, closing as `Invalid`
![Screenshot 67](https://github.com/brave/brave-browser/assets/40611140/5b6ae808-05e3-45f4-bb71-ac4dd3895ce9)
