### ISSUE TITLE
add way to close or cancel from 'Choose Device Type dialog'

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#2904]
## Description 
![screen shot 2019-01-09 at 2 53 06 pm](https://user-images.githubusercontent.com/5951041/51000053-c8774400-14e0-11e9-9e98-e127b2024251.png)

A user has to choose Phone/Tablet or Computer to proceed and may want to cancel out of this process all together. Need a method to close out of this dialog and go back to previous screen. An "x" button, top right corner may suffice and consistent with other UI.

**Comment by btlechowski** [comment]
Still reproducible

![image](https://user-images.githubusercontent.com/34715963/72851848-0f2f7a80-3cad-11ea-9d38-abe9edd0746c.png)

Brave | 1.5.46 Chromium: 79.0.3945.130 (Official Build) nightly (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Ubuntu 18.04 LTS

cc @cezaraugusto @jsecretan
