### ISSUE TITLE
Turning off Autocomplete Suggestions without turning off Browsing History suggestions doesn't work.

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#29043]
## Description 

Carry over from https://github.com/brave/brave-browser/issues/26894?notification_referrer_id=NT_kwDOAHUoSLI0ODg3NjgxODg5Ojc2NzgwMjQ#issuecomment-1466337096

## Steps to Reproduce

   1. Set default search provider to Google
   2. Search for `Hello World`
   3. Ensure `Browsing History`  suggestions are on.
   4. Turn off `Show autocomplete suggestions in address bar`
   5. Open a new tab and focus the omnibox

## Actual result:
Autocomplete suggestions for `Hello World` is shown

## Expected result:
No autocomplete suggestions from history are shown.

## Reproduces how often: 
Every time

## Brave version (brave://version info)
1.51.16

## Version/Channel Information:
All

**Comment by kjozwiak** [comment]
The above requires `1.50.106` or higher for `1.50.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.50.110 Chromium: 112.0.5615.49 (Official Build) (x86_64)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | macOS Version 12.6.4 (Build 21G526)
```
