### ISSUE TITLE
Longer browser profile names are shown in brave://welcome pages

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#29046]
## Description 

It appears there is a browser profile name change occurred with 1.50.x  as the profiles names shown are very long that included browser name for all the detected browsers in the `brave://welcome` - `Select profile to import` - screen.  eg.  `Chrome Person 1` is shown `Google Person 1 - Google Chrome`.   Profile names should be displayed same as in 1.49.x  `Chrome Person 1`

## Steps to Reproduce

   1.  Install 1.50.x
   2.  launch Brave
   3.  select `Set Brave as default browser`
   4.  select `Google Chrome`
   5.  verify profile name 

## Actual result:

Profile names shown as 
`Google Chrome Person 1 - Google Chrome` 
`Google Chrome Person 2 - Google Chrome` 

<img width="458" alt="image" src="https://user-images.githubusercontent.com/98358127/224859769-b87cb7b1-31da-4524-a32a-674fa87db5ae.png">

## Expected result:

`Chrome Person 1` and `Chrome Person 2`

<img width="459" alt="image" src="https://user-images.githubusercontent.com/98358127/224859934-a6f79b3d-a529-4bcb-b1c2-343c7f112e52.png">

## Reproduces how often: 

Yes

## Brave version (brave://version info)

Brave | 1.50.90 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | Windows 11 Version 22H2 (Build 22621.1265)

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel?  Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
 @spylogsster @rebron

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.51.76 Chromium: 112.0.5615.49 (Official Build) beta (64-bit)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Windows 10 Version 22H2 (Build 19045.2788)

Followed the original steps to reproduce.

#### Verified browser-profile names not longer repeat

`1.51.76`

`Google Chrome Dev` | `Google Chrome Beta` | `Google Chrome`
------------------------|--------------------------|--------------------
![image (2)](https://user-images.githubusercontent.com/387249/229641375-cf2cad00-cb40-4f0b-83a9-3c4de597211b.png) | ![image (1)](https://user-images.githubusercontent.com/387249/229641378-c2991871-d525-4057-bb5c-6b7f0be1eb41.png) | ![image](https://user-images.githubusercontent.com/387249/229641380-9f60d698-c740-45fa-a22f-9c38bc6f0b37.png)




`1.50.130`

`Google Chrome Dev` | `Google Chrome Beta` | `Google Chrome`
------------------------|--------------------------|--------------------
![image (1)](https://user-images.githubusercontent.com/387249/229641060-6708e85f-abfa-4f91-bee2-a6d0c3858c91.png) | ![image](https://user-images.githubusercontent.com/387249/229641083-00471942-d5f8-4d65-8931-982855bab5bb.png) | ![image (2)](https://user-images.githubusercontent.com/387249/229641128-312d193d-9462-405c-b014-3454c560b012.png)
