### ISSUE TITLE
[Android] `Loading...` spinner animation is NOT shown in the BR panel when rewards custodian is failed to fetch the balance

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#29054]
## Description 
Found while testing https://github.com/brave/brave-browser/issues/28549#issuecomment-1467899827

[Android] `Loading...` spinner animation is NOT shown in the BR panel when rewards custodian is failed to fetch the balance
## Steps to reproduce 

pre-req: have Charles Proxy set up to return 500 error for https://api.sandbox.gemini.com/v1/balances)
   1. Clean profile 1.50.90
   2. Enable staging rewards flags via QA preferences
   3. Enable rewards
   4. Connect Gemini wallet
   5. Open brave://rewrads settings and brave://rewards-internals pages, ensured that the `Loading...` spinner animation is shown
   6. Open BR panel, `Loading...` spinner animation is NOT shown

## Actual result 
`Loading...` spinner animation is NOT shown in the BR panel when rewards custodian is failed to fetch the balance

![Screenshot_20230314-163321_Brave - Beta](https://user-images.githubusercontent.com/38657976/224987562-afb53745-1780-4563-a831-e3f5ce35684b.jpg)

## Expected result
`Loading...` spinner animation should be shown in the BR panel when rewards custodian is failed to fetch the balance

should be same as Desktop
![image](https://user-images.githubusercontent.com/38657976/224987519-ac87f9bc-ed44-42bc-b2a6-3945beaca2a6.png)

## Issue reproduces how often 

Easy
## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung Galaxy
   - Android version: 12
   
## Brave version
1.50.90

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

CC: @Miyayes @brave/qa-team @deeppandya

**Comment by Miyayes** [comment]
Will be orange spinner (without "Loading...") text on Android. That is acceptable for this iteration.

**Comment by kjozwiak** [comment]
The above requires `1.50.120` or higher for `1.50.x` verification 👍
