### ISSUE TITLE
Google account saved passwords is not imported

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#29051]
## Description 

![image](https://user-images.githubusercontent.com/2965009/224939643-1a1722d5-ff47-407c-bcdd-8df1ab715cf7.png)

![image](https://user-images.githubusercontent.com/2965009/224939675-2e9718b5-f92d-45bf-850f-48baab5b3808.png)

## Steps to Reproduce

   1. Enable Google Account passwords in Chrome
   2. Import data from Chrome profile

## Actual result:

Google account passwords are not imported

## Expected result:

Google account passwords imported

## Reproduces how often: 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.51.79 Chromium: 112.0.5615.49 (Official Build) beta (64-bit)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Windows 11 Version 22H2 (Build 22621.1413)
```
Pre-requisite steps:
<details>
Download and Install Chrome browser
Create a new profile - Person 2
Navigate to www.expensify.com and login with Google SSO password
Navigate to Walmart.com and login to the site. Save the password in the password manager
Navigate to target.com and login to the site.  Do not save the password in the password manager

![image](https://user-images.githubusercontent.com/98358127/230446684-5d448831-a837-4b0f-b76b-6b8e2b18e8d5.png)
</details>

Steps: 

1. Install 1.51.79
2. launch Brave
3. click Set Brave as default browser
4. `Google Chrome` selected 
5. click `Import`
6. click `Select All`
7. click `Import profiles`
8. click `Finish`
9. click Profile icon next to hamburger menu in a new tab page
10. select `Google Chrome person 2` 
11. open `brave://settings/passwords`

#### Confirmed password saved (walmart.com) in Google password manager is imported 
#### Confirmed password Never saved  (target.com) is imported into `Never saved` entry

step 2|step 4|step 6|step 9|step 11
------|-----|-----|-----|-----
<img width="464" alt="image" src="https://user-images.githubusercontent.com/98358127/230443461-92730553-de7f-452e-8c52-e28564db9bc7.png">|<img width="465" alt="image" src="https://user-images.githubusercontent.com/98358127/230443498-c348ecee-62b7-4398-90eb-bdc1576ac2f3.png">|<img width="461" alt="image" src="https://user-images.githubusercontent.com/98358127/230443632-4a2efbec-7f39-40df-8b82-37430306214a.png">|<img width="453" alt="image" src="https://user-images.githubusercontent.com/98358127/230446955-04b8befc-69bc-4234-ac89-61681d0f41ad.png">|<img width="461" alt="image" src="https://user-images.githubusercontent.com/98358127/230446902-f06cd155-cc1e-4478-96d2-a69341b41997.png">

</details>
