### ISSUE TITLE
Question : accessing adblock count from a local webpage/plugin

### ISSUE THREAD

**Issue by lapingenieur** [brave/brave-browser#29068]
I'd like to retrieve statistical data that stay on the new tab page into a local webpage (with js) or into a plugin, like the number of blocked trackers.

I searched all around and all I found is that the brave new tab page gets these from `react-redux` in [these tsx files](https://github.com/brave/brave-core/blob/master/components/brave_new_tab_ui/containers/app.tsx#L79), and then passes it to containers.

This stuff might be private to brave... Is there any way to access it?

**Comment by bsclifton** [comment]
Hi @lapingenieur - apologies it's taken so long to get a response. This data is in JSON format in the `Preferences` file in your profile directory. There isn't a way to get this data from an extension or local webpage.
