### ISSUE TITLE
Add interim support to none fields to the `json-schema-compiler`

### ISSUE THREAD

**Issue by cdesouza-chromium** [brave/brave-browser#29064]
Brave news seems to be broken on master, due to our server APIs producing a JSON string that omits optional fields in some cases by setting them as `null`. We should add some interim support to the `json-schema-compiler`, to allow those fields to be treated as absent, when dealing with optional fields.

**Comment by stephendonner** [comment]
@cdesouza-chromium this is `QA/Yes`, but is lacking a testplan.  Mind attaching one @brave/qa-team can use?  Thanks!

**Comment by cdesouza-chromium** [comment]
I guess the test plan is to check that brave news is working.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.51.77 Chromium: 112.0.5615.49 (Official Build) beta (x86_64)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | macOS Version 13.4 (Build 22F5027f)

### Steps:
1. installed `1.51.77`
2. launched Brave
3. opened a new-tab page
4. scrolled a bit
5. clicked `Turn on Brave News`
6. loaded `https://planet.mozilla.org/`
7. clicked on the `Manage Subscriptions` icon in the URL bar
8. clicked on `Follow` next to `Planet Mozilla`
9. clicked on `Manage Feeds`
10. clicked `Unfollow` on `Top Sources`
11. clicked `Follow` on `Fox News`
12. scrolled Brave News
13. clicked on `Load new content`
14. confirmed `Planet Mozilla` blog posts
15. clicked `Unfollow` next to `Planet Mozilla` in the `Customize` dialog
16. clicked `Load new content`
17. confirmed I only saw `Fox News` articles/posts

#### Confirmed I was able to subscribe to, unsubscribe from, and search for RSS/ATOM feeds

example | example | example | example | example
---------|----------|---------|----------|--------
<img width="1312" alt="Screenshot 2023-04-04 at 3 22 32 PM" src="https://user-images.githubusercontent.com/387249/229936488-294e9e0c-ddfc-43f7-99f0-88e4399a708b.png"> | <img width="1312" alt="Screenshot 2023-04-04 at 3 18 04 PM" src="https://user-images.githubusercontent.com/387249/229935603-ac136984-a979-4f90-b4e0-27400a552997.png"> | <img width="1312" alt="Screenshot 2023-04-04 at 3 18 10 PM" src="https://user-images.githubusercontent.com/387249/229935608-94acbe25-3769-477b-8e54-acc88d7ced8c.png"> | <img width="1312" alt="Screenshot 2023-04-04 at 3 25 36 PM" src="https://user-images.githubusercontent.com/387249/229936234-f04b8ffa-2b40-497d-9a96-33d59023d0a0.png"> | <img width="1312" alt="Screenshot 2023-04-04 at 3 21 29 PM" src="https://user-images.githubusercontent.com/387249/229935612-ec7afadb-4b21-4745-8ddf-53c8366f5525.png">

example | example | example | example | example
---------|----------|---------|---------|----------
<img width="1312" alt="Screenshot 2023-04-04 at 3 25 08 PM" src="https://user-images.githubusercontent.com/387249/229936495-25aeeb20-373a-483f-a264-2dd40a005af4.png"> | <img width="1312" alt="Screenshot 2023-04-04 at 3 25 10 PM" src="https://user-images.githubusercontent.com/387249/229936499-9cfa5a69-71d1-4811-bc5c-a9f62bea3a63.png"> | <img width="1312" alt="Screenshot 2023-04-04 at 3 25 19 PM" src="https://user-images.githubusercontent.com/387249/229936506-5bbb0ed9-6e87-48a8-9024-00c8284dcb60.png"> | <img width="1312" alt="Screenshot 2023-04-04 at 3 30 48 PM" src="https://user-images.githubusercontent.com/387249/229936882-4e1b2a2f-a7ec-4a9a-8c82-cd69bac751e1.png"> |<img width="1312" alt="Screenshot 2023-04-04 at 3 31 20 PM" src="https://user-images.githubusercontent.com/387249/229936891-5cab92cb-95af-427b-9de2-93057048590e.png">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.51.79 Chromium: 112.0.5615.49 (Official Build) beta (64-bit)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Windows 11 Version 22H2 (Build 22621.1413)
```

### Steps:
1. installed `1.51.79`
2. launched Brave
3. opened a new-tab page
4. scrolled a bit
5. clicked `Turn on Brave News`
6. loaded `https://planet.mozilla.org/`
7. clicked on the `Manage Subscriptions` icon in the URL bar
8. clicked on `Follow` next to `Planet Mozilla`
9. clicked on `Manage Feeds`
10. clicked `Unfollow` on `Top Sources`
11. clicked `Follow` on `CNN`
12. scrolled Brave News
13. clicked on `Load new content`
14. confirmed `Planet Mozilla` blog posts
15. clicked `Unfollow` next to `Planet Mozilla` in the `Customize` dialog
16. clicked `Load new content`
17. confirmed I only saw `CNN` articles/posts

#### Confirmed I was able to subscribe to, unsubscribe from, and search for RSS/ATOM feeds

step 5 | step 8| step 10| step 11| step 14|step 15| step 16
---------|----------|---------|----------|--------|-----|-------
<img width="449" alt="image" src="https://user-images.githubusercontent.com/98358127/230464650-6e7add53-588c-413e-95ab-1b24c87ced8f.png">|<img width="462" alt="image" src="https://user-images.githubusercontent.com/98358127/230464972-267ab6c2-22a2-465b-8441-8c432b9ff4c2.png">|<img width="463" alt="image" src="https://user-images.githubusercontent.com/98358127/230465039-445ed7d8-c472-4211-8a61-e8cec0234046.png">|<img width="458" alt="image" src="https://user-images.githubusercontent.com/98358127/230465110-3a4aa6a0-0254-437c-81a5-fa30dc8873ad.png">|<img width="449" alt="image" src="https://user-images.githubusercontent.com/98358127/230465279-41ae9f65-20a0-47c2-94fd-c774b019797d.png">|<img width="460" alt="image" src="https://user-images.githubusercontent.com/98358127/230465410-d6f28d6c-8e04-4d5a-932a-5f2b3b47b754.png">|<img width="453" alt="image" src="https://user-images.githubusercontent.com/98358127/230465497-20bf65f5-8e35-4d10-a96a-62e534571b61.png">
