### ISSUE TITLE
Inform Confirmations issuers have changed in the Ads Serve Catalog

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#2906]
**Subtasks:**

- [x] Implement Ads service implementation `SetCatalogIssuers` as a proxy to bat-native-ledger `SetCatalogIssuers`
- [ ] Implement bat-native-ledger `SetCatalogIssuers` as a proxy to bat-native-confirmations `SetCatalogIssuers` (see `void AdsServiceImpl::SetCatalogIssuers(std::unique_ptr<ads::IssuersInfo> info)`)

**Comment by tmancey** [comment]
Closing as will be resolved as part of #2912

**Comment by LaurenWags** [comment]
Discussed with Terry/Jimmy - marking as QA/No as testing will be completed with https://github.com/brave/brave-browser/issues/3117
