### ISSUE TITLE
Confirm if Ad can be shown

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#2907]
**Subtasks:**

- [x] Implement Ads service implementation `IsConfirmationsReadyToShowAds` as a proxy to bat-native-ledger `IsConfirmationsReadyToShowAds`
- [ ] Implement bat-native-ledger `IsConfirmationsReadyToShowAds` as a proxy to bat-native-confirmations `IsConfirmationsReadyToShowAds` (see `bool AdsServiceImpl::IsConfirmationsReadyToShowAds()`)

**Comment by tmancey** [comment]
Closing as will be resolved as part of #2912

**Comment by LaurenWags** [comment]
Discussed with Terry/Jimmy - marking as QA/No as testing will be completed with https://github.com/brave/brave-browser/issues/3117
