### ISSUE TITLE
Add inline toolbar for Speedreader options for themes, font, and text size

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#29075]
## Description 

When a page is in Speedreader mode, we should provide an inline toolbar to allow users to change themes, fonts, and text size.

## Design

   1. Go to an article page that can be viewed with Speedreader/Reader mode layout.
   2. See Figma doc. `https://www.figma.com/file/YHMNRL2XpZDOUe6n1Dw6K1/Reader-mode?node-id=2180%3A61903`
   3. User should be able to select theme choices of Light, Sepia, Dark, and Automatic (default); font choices of Sans (default), Serif, Mono, and Dyslexic; and text size from 25%, 33%, 50% 67%, 75%, 80% 90%, 100% (default), 110%, 125%, 133%, 140%, 150%, 175%, 200%, 250%, 300%, 400%, 500%
   
<img width="965" alt="Screenshot 2023-03-14 at 7 57 10 PM" src="https://user-images.githubusercontent.com/5951041/225193673-f20494e7-3a9b-448e-b15a-b6a310e4a064.png">

## Brave version (brave://version info)

Target 1.51.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by LaurenWags** [comment]
`QA/Blocked` as we're waiting on a test plan (@rebron to provide)

**Comment by MadhaviSeelam** [comment]
Removing `QA/Blocked` as per the discussion with @rebron. Will be doing initial testing.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.58.101 Chromium: 116.0.5845.114 (Official Build) beta (64-bit)
-- | --
Revision | f6b6f6271f9a51efe3c5e2be309f1a12012880c6
OS | Windows 11 Version 22H2 (Build 22621.2134)
```

Case 1: Speedreader icon/button in the URL bar

1. Install 1.58.101
2. launch Brave
3. open brave://settings/appearance
4. verified `Speedreader` setting toggle is `Off`
5. navigated to nytimes.com and opened an article (https://www.nytimes.com/interactive/2023/03/16/travel/things-to-do-taipei.html)
6. confirmed Speedreader mode button is available in the URL bar
7. toggle `On` Speedreader mode button  
8. confirmed article layout is shown in Speedreader mode 
9. confirmed inline toolbar is shown on the top of the article
10. Appearance 
10. return to brave://settings/appearance and switched to Dark theme

step 4 | step 6 | step 8
----- | ---- | -----
<img width="645" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/83b4055c-e34e-47d7-8f31-0903367cec7d">|<img width="645" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/467dd3f5-5042-4eca-a6fa-87ad48358de8">|<img width="645" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/e76717e0-fc47-46c1-99cd-a2d48d53a3ce">

Dark theme
----
example | example 
---- | -----
<img width="645" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/95f4f378-6004-40b6-a321-4160d0f7156a">|<img width="645" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/a09208c6-7f42-46df-b92d-a014a56cd0e8">


Case 2 : Inline toolbar controls

1. Continue from Case 1
      - article is in Speedreader mode 
2. Inline toolbar shows Appearance settings, Speedreader mode toggle, `X` buttons
3. click on Appearance settings button
4. confirmed Speedreader toggle, Theme options, Font options control, and Text size control are shown
4. click on each theme choice:  Light, Sepia, Dark, System (default)
5. confirmed the article reflected selected theme as expected
6. click on each font choice: Sans (default), Serif, Mono, and Dyslexic
7. confirmed the article reflected the selected font as expected
8. click `+` to increase text size from 25%, 33%, 50% 67%, 75%, 80% 90%, 100% (default), 110%, 125%, 133%, 140%, 150%, 175%, 200%, 250%, 300%, 400%, 500%. These are per profile settings
9. click `-` to decrease text size minimum size 50%
10. click Close button 

step 2a | step 2b | step 3 
----- | ----- | ------
<img width="946" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/e8f9317b-c3e5-4f92-8f92-8afbb87acfe9">|<img width="948" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/041ef5ae-1294-406a-96e6-0f1fd5958a50">|<img width="946" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/f254d5cf-c97d-47b8-9bd7-0e4670851d03">


Light | Sepia | Dark | System (default)
------- | -------- | ------- | --------
<img width="946" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/99e80e0e-2cc1-42a1-b627-361d1062683d">|<img width="946" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/209742f9-45dc-49ca-8812-9ebbc2bf5c48">|<img width="946" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/f14973a2-a4e0-4f1b-a80d-1f7d693c3fa2">|<img width="946" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/7c3869f0-c10b-4775-b1fd-635fffc68f97">

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.58.105 Chromium: 116.0.5845.114 (Official Build) beta (x86_64)
-- | --
Revision | 5a895596bcd7fcd930dab0714ea5cfa86c5aa0a7
OS | macOS Version 11.7.9 (Build 20G1426)
```

## Case 1: Speedreader icon/button in the URL bar
<details>


</details>

## Case 2: Inline toolbar controls - Default selections

## Case 3: Inline toolbar controls - User selections

## Case 4: User selections in the Speedreader mode are carried to another article in the same profile

**Comment by LaurenWags** [comment]
Per discussion with @rebron the run Test Case 1 (Normal Window) and sub cases 3, 4, 5 from https://github.com/brave/brave-browser/issues/29075#issuecomment-1693865229 on Linux.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using 
```
Brave	1.58.117 Chromium: 116.0.5845.180 (Official Build) (64-bit) 
Revision	99255ad6abf2fa399c063683c051f973e1f5c0af
OS	Linux
```


## Normal window - single profile - `PASSED`

### Case 1: Speedreader icon/button in the URL bar - `PASSED`
<details>

### Steps:
1. installed `1.58.117`
2. launched Brave
3. opened `brave://settings/appearance`
4. verified `Speedreader` setting is `Off`
5. navigated to `usatoday.com` and opened an article (`https://www.usatoday.com/story/news/nation/2023/08/28/idalia-hurricane-forecast-rapid-intensification-explained/70699372007/`)
6. confirmed `Speedreader settings` button is available in the URL bar
7. clicked `Speedreader settings` button
8. confirmed article layout is shown in `Speedreader settings`
9. confirmed inline toolbar is shown at the top of the article

step 4 | step 6 | step 7 | step 8 
--|--|--|--
