### ISSUE TITLE
"Redirect IPFS resources [...]" redirects non-IPFS URLs to invalid IPFS URLs

### ISSUE THREAD

**Issue by jayschwa** [brave/brave-browser#29078]
## Description 

The "Redirect IPFS resources [...]" setting is causing non-IPFS URLs to be redirected to invalid IPFS URLs. I noticed it when I tried to go to https://github.com/ipfs/kubo and was redirected to `ipfs://kubo`. It has been awhile since I ran with IPFS active, but I don't remember this happening before. I think it might be a regression. Related issue: #21505.

## Steps to Reproduce

   1. Enable "Redirect IPFS resources to the configured IPFS gateway" in browser settings.
   2. Navigate to any URL where the first path component is `ipfs`. Example: https://github.com/ipfs/kubo

## Actual result:

The browser erroneously redirects to `ipfs://kubo`, which doesn't work.

## Expected result:

No redirect to a invalid IPFS URL.

## Reproduces how often: 

Easy to reproduce.

## Brave version (brave://version info)

1.49.120 Chromium: 111.0.5563.64 (Official Build) (64-bit) 

## Version/Channel Information:

I'm using Ubuntu snap latest/stable. Snap doesn't appear to have any newer test builds uploaded.

**Comment by yrliou** [comment]
cc @cypt4

**Comment by lidel** [comment]
@cypt4 any ETA for the fix?

**Comment by cypt4** [comment]
> @cypt4 any ETA for the fix?

It was merged in this PR https://github.com/brave/brave-core/pull/19451

**Comment by cypt4** [comment]
Duplicate https://github.com/brave/brave-browser/issues/31145
