### ISSUE TITLE
[Android] Follow up of #27255 - Cross custodial tipping notice text is not updated in BR panel and tipping banner

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#29080]
## Description 
Found while testing #27255

Follow up of #27255 - Cross custodial tipping notice text is not updated in BR panel and tipping banner
## Steps to reproduce 

   1. Clean profile 1.50.90 
   2. Connect Uphold custodian
   3. Follow the test plan from https://github.com/brave/brave-core/pull/16323#issue-1489497107
   4. Open http://github.com/miyayes (pub verified with Gemini) or alexvincentmusic.com (pubs verified with bitFlyer)
   5. Cross custodial tipping notice text is not updated in BR panel and tipping banner for the above pubs
 
## Actual result 

Cross custodial tipping notice text is not updated in BR panel and tipping banner

BR panel | Tipping banner
----------|-----------------
![image](https://user-images.githubusercontent.com/38657976/225266358-edc591fd-becd-44d1-9a30-e70fa5e7ef14.png) | ![image](https://user-images.githubusercontent.com/38657976/225266444-bb6755f4-ec7c-43ee-80de-581073df5192.png)

## Expected result
When Uphold KYC'd wallet is used with Rewards, the text on the panel and tipping banner is NOT updated when attempting to tip Gemini and bitFlyer verified creators.

Desktop

panel | tipping banner
-------|---------------
![image](https://user-images.githubusercontent.com/38657976/225267242-6f675ea0-ba99-4f72-820d-90e7a1514882.png) | ![image](https://user-images.githubusercontent.com/38657976/225267395-a4845f99-baa9-42b7-8842-e1a6e5ad1cfc.png)

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Vivo X70 Pro
   - Android version: 12
   
## Brave version
1.50.90

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/qa-team @deeppandya @sujitacharya2005 @Miyayes

**Comment by kjozwiak** [comment]
The above requires `1.50.121` or higher for `1.50.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.50.121`

**Cross custodian pubs `https://github.com/miyayes`**

BR panel | Tipping Banner
----------|----------------------
![Screenshot_20230419_180644](https://user-images.githubusercontent.com/38657976/233077467-7b52e685-09f6-4f74-849f-29521f9ddb26.jpg) | ![Screenshot_20230419_180649](https://user-images.githubusercontent.com/38657976/233077493-d593b2cd-388d-4b12-a3cc-bcede7b93da3.jpg)


**Cross custodian pubs `https://alexvincentmusic.com`**

BR panel | Tipping Banner
----------|----------------------
![Screenshot_20230419_180712](https://user-images.githubusercontent.com/38657976/233077531-81258873-5f44-446e-b58d-8f21c2e04697.jpg) | ![Screenshot_20230419_180717](https://user-images.githubusercontent.com/38657976/233077557-4357f46d-d070-4168-955d-363725e9925e.jpg)
