### ISSUE TITLE
Confirm user has sustained viewing an Ad

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#2908]
**Subtasks:**

- [x] Implement Ads service implementation `AdSustained` as a proxy to bat-native-ledger `AdSustained`
- [ ] Implement bat-native-ledger `AdSustained` as a proxy to bat-native-confirmations `AdSustained` (see `void AdsServiceImpl::AdSustained(std::unique_ptr<ads::NotificationInfo> info)`)

**Comment by tmancey** [comment]
Closing as will be resolved as part of #2912

**Comment by LaurenWags** [comment]
Discussed with Terry/Jimmy - marking as QA/No as testing will be completed with https://github.com/brave/brave-browser/issues/3117
