### ISSUE TITLE
[Android] `Note:` text is displayed twice in the cross custodial tipping notice

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#29081]
## Description 
Found while testing https://github.com/brave/brave-browser/issues/27255
`Note:` text is displayed twice in the cross custodial tipping notice
## Steps to reproduce 

   1. Follow the steps 1 to 4 from https://github.com/brave/brave-browser/issues/29080#issue-1625111842
   2. Open the tipping banner for http://github.com/miyayes or alexvincentmusic.com
   3. `Note:` text is displayed twice in the cross custodial tipping notice

## Actual result 

`Note:` text is displayed twice in the cross custodial tipping notice
![image](https://user-images.githubusercontent.com/38657976/225269247-babe0cda-94d1-42c5-8a95-a21a50b7a41b.png)

## Expected result

`Note:` text should be displyed once although the remaining message is not correct which will be taken care in #29080

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86): All
   - Device type (Phone, Tablet, Phablet): Vivo X70 Pro
   - Android version: 12
   
## Brave version

1.50.90
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/qa-team @sujitacharya2005 @deeppandya @Miyayes

**Comment by kjozwiak** [comment]
The above requires `1.50.121` or higher for `1.50.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.50.121`

- Verified the STR from https://github.com/brave/brave-browser/issues/29081#issue-1625132013 and ensured that the `Note` text is NOT displayed twice in the tipping banner

**_Gemini pubs_** | **_Bitflyer pubs_**
--------------------|------------------
![Screenshot_20230419_180649](https://user-images.githubusercontent.com/38657976/233078419-f940d0cb-e753-4e75-9129-c5b85dd44742.jpg) | ![Screenshot_20230419_180717](https://user-images.githubusercontent.com/38657976/233078468-441baf86-ace4-4d40-bd13-518c58b43054.jpg)
