### ISSUE TITLE
Remove identity patch for auth token

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#29096]
## Description 

follow up from https://github.com/brave/brave-core/pull/17187#discussion_r1137688218, Google's PR https://crrev.com/c/2704571 is wip and probably abandonet so we need to rewrite it another way

**Comment by bridiver** [comment]
also we should add test coverage for this

**Comment by bsclifton** [comment]
Originally implemented here https://github.com/brave/brave-core/pull/14069

The proposed CL by Chromium authors was shared on the embedded mailing list as one other browsers (like us) can implement after the ability to use 1st party identity was removed upstream for non-Chrome cases.

**Comment by LaurenWags** [comment]
@spylogsster @bsclifton is the extension listed in the PR test plan vetted? It looks like we may need to login with Google account credentials. 

Should @brave/qa-team use fake credentials for this?

**Comment by spylogsster** [comment]
> @spylogsster @bsclifton is the extension listed in the PR test plan vetted? It looks like we may need to login with Google account credentials. Also, does this code differ from OS to OS? Should we verify on all 3 - Windows, macOS, and Linux?
> 
> Should @brave/qa-team use fake credentials for this?

Code is same, it is enough to check only one OS. The extension uses necessary api and taked by "Samples" link from Google api help page https://developer.chrome.com/docs/extensions/reference/identity/

**Comment by LaurenWags** [comment]
thanks @spylogsster!

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.52.103 Chromium: 113.0.5672.126 (Official Build) beta (x86_64)
-- | --
Revision | c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}
OS | macOS Version 11.7.6 (Build 20G1231)
```
