### ISSUE TITLE
Support scriptlet arguments with quotes

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#29099]
See https://github.com/brave/adblock-rust/issues/237 for details. This is now starting to cause problems on some sites which rely on scriptlets with quoted arguments in upstream uBO lists. For example, the following rule:

```adblock
lightnovelpub.*,[lightnovelworld.com](http://lightnovelworld.com/),[novelpub.com](http://novelpub.com/),[webnovelpub.com##+js(nostif](http://webnovelpub.com/##+js(nostif), (""))
```

Without that rule working properly, https://lightnovelpub.com appears with gray placeholders where the images should be.

**Comment by mkarolin** [comment]
@antonok-edm could you, please, set the appropriate QA and release-notes labels, if needed.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.51.77 Chromium: 112.0.5615.49 (Official Build) beta (64-bit)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Windows 10 Version 22H2 (Build 19045.2788)

### Steps:
1. installed `1.51.77`
2. launched Brave
3. loaded `https://lightnovelpub.com/`
4. looked for the light-novel images
5. compared to `1.49.130` and `1.50.113`

#### Confirmed I could again see images on https://lightnovelpub.com/, below a gray (also blank, but not part of this issue) advertisement placeholder

`1.51.77` | `1.50.113`
----------|----------
![image (9)](https://user-images.githubusercontent.com/387249/229947183-a1f6b677-f1e0-4f54-a6a4-b4322d4e40d3.png) | ![image (8)](https://user-images.githubusercontent.com/387249/229947186-8dfd9487-7066-41d3-9da1-f44c5a9033d8.png)

**Comment by vlad-hoff** [comment]
Verified, the issue is not reproducible in build 1.51.x. Gray placeholders instead of images are not show anymore.

------------------

```
Device/OS: Pixel 6 [oriole-user 13 TQ2A.230405.003.E1 release-keys]
Brave build: 1.51.105 [Beta]
```

Screenshot/Screencast:

|1|2|
|-|-|
| ![1](https://user-images.githubusercontent.com/128532965/234715279-42144605-7d36-4e1b-9273-da4e9476c391.png) | ![2](https://user-images.githubusercontent.com/128532965/234715522-dd5d8b4c-a6d9-4bb7-bd6c-5315c67c68af.png) |
