### ISSUE TITLE
Switch Avalanche RPC to use Infura proxied through Brave

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#29109]
We currently use a public RPC for Avalanche C-Chain, which can be unreliable during peak activity. Switch to dedicated Infura RPC proxied through Brave.

|RPC|`https://mainnet-avalanche.wallet.brave.com/{PROJECT_KEY_ID}`|
-|-

### Test plan

1. **Settings > Web3 > Wallet networks** should show the following for Avalanche.
    <img width="399" alt="avax" src="https://user-images.githubusercontent.com/3684187/226897096-0c8f9856-358b-48e6-9f93-d9a6786c031e.png">

2. Balances under Avalanche network are correctly displayed.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.51.109 Chromium: 113.0.5672.63 (Official Build) (arm64)
-- | --
Revision | `0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}`
OS | macOS Version 13.3.1 (Build 22E261)

- Verified Avalanche RPC calls are proxied through Brave
![image](https://user-images.githubusercontent.com/17010094/235645843-0a921920-bab3-4be8-bbd2-3b9c68c39cec.png)
