### ISSUE TITLE
Implement is_production command-line argument for Confirmations

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#2910]
Implement command-line argument for Confirmations `_is_production` boolean flag

**Comment by tmancey** [comment]
This makes more sense to be completed as part of #2912 as `_is_production` boolean flag in bat-native-confirmations needs setting to same value as `_is_production` boolean flag in bat-native-ads

**Comment by LaurenWags** [comment]
Discussed with Terry/Jimmy - marking as QA/No as testing will be completed with https://github.com/brave/brave-browser/issues/3117
