### ISSUE TITLE
Add onboarding for hardware wallets

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#29107]

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.52.102 Chromium: 113.0.5672.126 (Official Build) beta (64-bit)
-- | --
Revision | `c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}`
OS | Linux

- Verified steps from [brave/brave-core#17637](https://github.com/brave/brave-core/pull/17637)
- Verified selecting hardware wallet during onboarding brings up connect hardware wallet route after agreeing to terms.
- Verified able to select EVM/Solana/Filecoin hardware wallet accounts directly during onboarding

https://github.com/brave/brave-browser/assets/17010094/488cf30d-2c5f-46c5-978d-87e8db4fcb81


---------------------
**Verification passed on**

Brave | 1.52.102 Chromium: 113.0.5672.126 (Official Build) beta (64-bit)
-- | --
Revision | `c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}`
OS | Windows 11 Version 22H2 (Build 22621.1702)

- Verified steps from [brave/brave-core#17637](https://github.com/brave/brave-core/pull/17637)
- Verified selecting hardware wallet during onboarding brings up connect hardware wallet route after agreeing to terms.
- Verified able to select EVM/Solana/Filecoin hardware wallet accounts directly during onboarding
https://github.com/brave/brave-browser/assets/17010094/db26c6b7-6c4e-43e8-af2d-ba87f2994f14
---------------------
**Verification passed on**

Brave | 1.52.102 Chromium: 113.0.5672.126 (Official Build) beta (arm64)
-- | --
Revision | `c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#17637](https://github.com/brave/brave-core/pull/17637)
- Verified selecting hardware wallet during onboarding brings up connect hardware wallet route after agreeing to terms.
- Verified able to select EVM/Solana/Filecoin hardware wallet accounts directly during onboarding

https://github.com/brave/brave-browser/assets/17010094/960c9a2a-ceac-498f-a69a-6953b98759b7
