### ISSUE TITLE
Rename Binance Smart Chain to BNB Smart Chain

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#29110]
News regarding the rebranding: https://www.coindesk.com/business/2022/02/15/binance-smart-chain-rebrands-to-bnb-chain/

**Comment by onyb** [comment]
The name should be **BNB Smart Chain** and not BNB Chain, which is like a meta name for BSC + Binance Chain.

<img width="820" alt="Screenshot 2023-03-17 at 23 09 46" src="https://user-images.githubusercontent.com/3684187/225978773-be8cd8a4-c56c-48ad-b89b-cb1af085d485.png">

**Comment by vednp** [comment]
Hey @onyb I would like to do this can you assign it to me?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.67.83 Chromium: 125.0.6422.41 (Official Build) beta (64-bit)
-- | --
Revision | d80b776d8894973bb67aab6b82202fd332da33c7
OS | Windows 11 Version 23H2 (Build 22631.3527)

- Verified steps from [brave/brave-core#23392](https://github.com/brave/brave-core/pull/23392)
- Verified `Binance Smart Chain` is now remaned to `BNB Smart Chain` through out the wallet

https://github.com/brave/brave-browser/assets/17010094/8e56ee68-a7ac-40a7-83ad-c4c1d0a2c135
