### ISSUE TITLE
a-c table not being updated correctly - follow up to 2882

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#2911]
## Description 
Follow up to #2882 

While testing above issue, found that if you visited a site in Dec 2018 (eg. DDG) and then again in 2019, your table still lists DDG twice. However, the % values in the table all add up to 100%.

## Steps to Reproduce

   1. Have a rewards profile from Dec 2018 with some data in it
   2. Launch Brave with that profile in Jan 2019 (using 0.58.18)
   3. Visit some sites (one not in the list already and one in the list already)
   4. View A-C table
   5. % values started over at 100% for these two recently visited sites
   6. Close Brave, swap out .app file to be 0.58.21
   7. Visit one of the sites again.
   8. Go back to A-C table. 
   9. All percentage values are back to normal (all add up to 100%) but the site which was already in the table is listed twice still.

## Actual result:
Site is listed twice
![screen shot 2019-01-10 at 6 25 10 pm](https://user-images.githubusercontent.com/28145373/51003774-0dfa3800-1506-11e9-80d0-289c8bc6adfd.png)

![screen shot 2019-01-10 at 6 25 01 pm](https://user-images.githubusercontent.com/28145373/51003777-10f52880-1506-11e9-898a-e994736c48a1.png)

## Expected result:
Site only listed once

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.58.21 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by NejcZdovc** [comment]
this one is currently blocked as we need to decide what we would like to do with monthly reports

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.63.14 Chromium: 73.0.3683.75 (Official Build) dev(64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Mac OS X

- Verified test plan from https://github.com/brave/brave-core/pull/1760
- Encountered https://github.com/brave/brave-browser/issues/3783 while testing
