### ISSUE TITLE
Rename GPU process

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#29113]
as per the research, GPU drivers like `chrome.exe` more than anything else. Let's start with windows.

https://habr-com.translate.goog/ru/company/yandex/blog/721374/?_x_tr_sl=en&_x_tr_tl=ru&_x_tr_hl=en&_x_tr_pto=wapp

**Comment by LaurenWags** [comment]
Adding `QA/Blocked` until the variations test is completed and merged. 

@kjozwiak will remove label once this one can be checked.

**Comment by kjozwiak** [comment]
Removing `QA/Blocked` as https://github.com/brave/brave-variations/pull/602 has been merged into `production`. Quick note that it's currently set at `50%` on both `Nightly` & `Beta`. So when verifying, it might take a few tries to get into `ModuleFileNamePatchStudy:Enabled`. Can find STR/Cases via https://github.com/brave/brave-core/pull/18050#issuecomment-1510958761.

We'll basically want to make sure that if you've been added into `ModuleFileNamePatchStudy:Enabled`, that the paths under `Executable path` are appearing as `chrome.exe` and not `brave.exe`. @iefremov & @boocmp want to collect some information via `P3A` so it's entirely possible we might not enable this via `1.51.x`. Or if we do, maybe later down the road rather than right after the initial release.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.51.95 Chromium: 112.0.5615.121 (Official Build) beta (64-bit)
-- | --
Revision | 39cc4e45904ae9f1741c4fbaa866e629c96f2268-refs/branch-heads/5615_51@{#8}
OS | Windows 11 Version 22H2 (Build 22621.1555)
```

`ModuleFileNamePatchStudy:Enabled`

1. Installed 1.51.95 
2. launched Brave
3. opened `brave://flags`
4. enabled `#brave-module-filename-patch`
5. clicked `Restart`
6. opened brave://version
7. opened brave://gpu

- Confirmed `brave://version shows `ModuleFileNamePatchStudy:Enabled` 
- Confirmed `brave://gpu` shows that all the paths under Executable path are pointing to `chrome.exe`

```
GetModuleFileNameExA = C:\Program Files\BraveSoftware\Brave-Browser-Beta\Application\chrome.exe 
GetModuleFileNameExW = C:\Program Files\BraveSoftware\Brave-Browser-Beta\Application\chrome.exe 
GetModuleFileNameA = C:\Program Files\BraveSoftware\Brave-Browser-Beta\Application\chrome.exe 
GetModuleFileNameW = C:\Program Files\BraveSoftware\Brave-Browser-Beta\Application\chrome.exe
```
step 4 | step 6 | step 7
----- | ---- |------
<img width="852" alt="image" src="https://user-images.githubusercontent.com/98358127/232837180-f465428e-09b5-45d5-b779-13d61e8b86c5.png">|<img width="852" alt="image" src="https://user-images.githubusercontent.com/98358127/232837993-78725430-5e0b-407c-8df0-7ebe5bf130cb.png">|<img width="852" alt="image" src="https://user-images.githubusercontent.com/98358127/232839730-78dbee19-6e91-4496-8448-05af164746e1.png">

`ModuleFileNamePatchStudy:Default`

1. New profile
2. launched Brave
3. opened `brave://flags`
4. enabled `#brave-module-filename-patch`
5. clicked `Restart`
6. opened brave://version
7. opened brave://gpu

- Confirmed `brave://version shows `ModuleFileNamePatchStudy:Default` 
- Confirmed `brave://gpu` shows that all the paths under Executable path are pointing to `brave.exe`

```
GetModuleFileNameExA = C:\Program Files\BraveSoftware\Brave-Browser-Beta\Application\brave.exe
GetModuleFileNameExW = C:\Program Files\BraveSoftware\Brave-Browser-Beta\Application\brave.exe 
GetModuleFileNameA = C:\Program Files\BraveSoftware\Brave-Browser-Beta\Application\brave.exe
GetModuleFileNameW = C:\Program Files\BraveSoftware\Brave-Browser-Beta\Application\brave.exe
```

step 4 | step 6a| step 6b|step 7
------- | ------ | ------ | ------
<img width="852" alt="image" src="https://user-images.githubusercontent.com/98358127/232842942-5b912083-ead1-4bf6-9e47-8a5c4fa2beee.png">|<img width="852" alt="image" src="https://user-images.githubusercontent.com/98358127/232843057-0fda048b-39f2-40d6-80f6-4e456dd5d238.png">|<img width="852" alt="image" src="https://user-images.githubusercontent.com/98358127/232843241-cb989513-895e-4be4-b5d8-1c80408fae77.png">|<img width="852" alt="image" src="https://user-images.githubusercontent.com/98358127/232843422-0e276375-d265-4007-8cbc-4baece256bce.png">

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.51.95 Chromium: 112.0.5615.121 (Official Build) beta (64-bit)
-- | --
Revision | 39cc4e45904ae9f1741c4fbaa866e629c96f2268-refs/branch-heads/5615_51@{#8}
OS | Windows 10 Version 22H2 (Build 19045.2846)

`ModuleFileNamePatchStudy:Enabled`

`ModuleFileNamePatchStudy:Default`

**Comment by geekyBoogiepop** [comment]
Please refer to the issue mentioned above to see why you should reconsider renaming back to chrome.exe
