### ISSUE TITLE
Always install Arm64, not x64, Brave on Arm64 Windows

### ISSUE THREAD

**Issue by mherrmann** [brave/brave-browser#29112]
In #28380, we have an issue where x64 Brave on Arm64 Windows exhibits a bug. After extensive research, no straightforward fix could be found for the problem described there.

The goal of the present issue is to mitigate #28380 by making it impossible to install x64 Brave on Arm64 Windows. This is precisely what Microsoft do with Edge: Edge's _online_ installer always installs the same architecture (x64 or Arm64) as the OS. And even its x64 _offline_ installer does the same. That is, Edge's x64 offline installer installs x64 Edge on x64 Windows and Arm64 Edge on Arm64 Windows. This even though there is a dedicated Arm64 installer. But it seems the x64 offline installer was purposely programmed to also be able to install Arm64 Edge.

Before implementing this issue, we should bring Arm64 Brave to feature parity with x64 Brave. At the moment, Arm64 Brave for example lacks Widevine support (#28318). Once the present issue is implemented, it will likely also make sense to update existing x64 clients on Arm64 Windows to Arm64 Brave.

The changes to achieve the above will likely include modifications to the channels on the update server. It may also make sense to update our fork of Google Update (a.k.a. Omaha) to include the commit https://github.com/google/omaha/commit/ba19b2d90d0fdaa43ae2571d321e7e68683a9a57. Though it looks like it is related to offline installers ([source](https://github.com/brave/omaha/blob/826cb43721b58d6da989c8486af9bfe0edb99e22/CHANGELOG.txt#L554)).
```[tasklist]
### Tasks
- [ ] https://github.com/brave/brave-browser/issues/32598
- [ ] https://github.com/brave/brave-browser/issues/32599
```

**Comment by nsait-linaro** [comment]
@mherrmann Is widevine support going to be a blocker for Windows Arm64 support? I think the previous plan was to release  without widevine support.

**Comment by mherrmann** [comment]
@mihaiplesa do you know what the official stance is with regards to @nsait-linaro's question?

**Comment by mherrmann** [comment]
Maybe I can make @mihaiplesa's statement a little more precise: on-demand updates via `brave://settings/help` don't work. Background updates do work.

**Comment by nsait-linaro** [comment]
Thanks @mihaiplesa @mherrmann.

Are there any external dependencies for the browser update issue?

**Comment by mherrmann** [comment]
If we could use Arm64EC, then that would fix the browser update issue. That would be an external dep. Other than that, it's in our hands. But it's a complex problem without a simple solution.

**Comment by nsait-linaro** [comment]
Thanks again @mherrmann. 

Is the update issue ( lack of native 3rd party libraries for Arm64) similar to widevine support? Which libraries are you looking at?

Is it challenging to add MSVC support for Brave? I guess Edge uses MSVC so chromium etc. should be supporting MSVC.

**Comment by mherrmann** [comment]
> Is the update issue also blocked due to lack of native 3rd party libraries for Arm64? Which libraries are you looking at?

In a way, yes. We use github.com/google/omaha for auto-updating on Windows. This only has 32- and 64-bit DLLs (because Chrome only supports those architectures). The problem is that the (COM) DLLs need to be registered and the place for doing so is the same for x64 and Arm64. So we can generate an Arm64 DLL. But when we register it, then x64 Brave can no longer check for updates. On the other hand, when we keep x64 registered, then Arm64 Brave can't check for updates. If Brave were Arm64EC, then that problem would go away.

> Is it challenging to add MSVC support for Brave?

At least I haven't tried. But it would certainly be a very profound change. I'm not sure we want this just to get two DLLs working.

> I guess Edge uses MSVC

It sounds likely, but I wouldn't be certain.

> chromium etc. should be supporting MSVC.

Searching a little online, it appears that at least WebRTC does not support MSVC.

**Comment by nsait-linaro** [comment]
> > we want to support both x64 and arm64 binaries for Windows Arm64 machines
> 
> Sorry for the blunt question: Who's "we" in this sentence? Which software should support x64 and arm64 on arm64?

Brave browser :-) 

Please correct me if I misunderstood your comments. The COM DLL issue you described above seems to be an issue only if x64 and arm64 brave need to be supported on Windows Arm64 machines. And considering the lack of widevine support for arm64, probably both x64 and arm64 binaries need to be supported now.

**Comment by mherrmann** [comment]
> considering the lack of widevine support for arm64, probably both x64 and arm64 binaries need to be supported now.

At this very moment, yes. At the top of this issue I describe a solution where we do not support x64 Brave on arm64 Windows.

**Comment by mherrmann** [comment]
This issue has two parts:

1. Installing Arm64 Brave from the online installer, when run on Arm64 Windows (#32598).
2. Installing Arm64 Brave even when the user runs the x64 offline installer (#32599).

The first point 1. is already done.

The motivation for 2. was to mirror what Microsoft are doing with Edge. But I just tested Edge's x64 offline installer (its Beta installer, to be exact) again and it does give me the x64 version (not the Arm64 version) of the browser. So I believe point 2. is obsolete. (See also my [comment](https://github.com/brave/brave-browser/issues/32599#issuecomment-1768497440) on #32599.)

Because the work that was performed is documented in #32598, I will close this issue as unplanned.
