### ISSUE TITLE
Replace wallet usage P3A metrics with new ones in proper cadences

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#29123]
Replace `Brave.Wallet.UsageMonthly.2` and `Brave.Wallet.UsageDaysInWeek` with `Brave.Wallet.UsageMonthly`, `Brave.Wallet.UsageWeekly` and `Brave.Wallet.UsageDaily` set in the monthly, weekly and daily cadences, respectively.

Question: Did you use the wallet this month/week/day?

The metrics will be ephemeral/one-time, and will only be reported max once per cadence + once per wallet unlocking, combined.

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.52.109 Chromium: 114.0.5735.26 (Official Build) beta (64-bit)
-- | --
Revision | 7075cbb66f0542ac3e01ddfde6b813e7d61118a5-refs/branch-heads/5735@{#454}
OS | Windows 10 Version 22H2 (Build 19045.2965)
```

**Comment by GeetaSarvadnya** [comment]
@DJAndries Could you review the scenario below? Thanks!

1. Clean profile 1.52.x
2. Enable wallet 
3. Open brave://local-state file 
4. Look for the metrics `Brave.Wallet.UsageDaily`, `Brave.Wallet.UsageWeekly` and `Brave.Wallet.UsageMonthly` 
5. All the 3 metrics responses are `1` as expected
6. Close the browser
7. Set the sys date ahead by 1 day (i.e 25th May)
8. Look for the metrics `Brave.Wallet.UsageDaily`, `Brave.Wallet.UsageWeekly` and `Brave.Wallet.UsageMonthly` 
9. All the 3 metrics responses are `1` - I was expecting `Brave.Wallet.UsageDaily` metrics should not be shown in the local state file as I have not unlocked the wallet on 25th May
10. Close the browser
11. Set the sys date ahead by 1 day (i.e 26th May)
12. I am getting the same response as step 9

**Comment by DJAndries** [comment]
@GeetaSarvadnya the metrics will only be removed from local state after they are sent

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.52.112`
