### ISSUE TITLE
Account icons are squished when account names is usually long

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#29129]
## Description 

Account icons are squished when account names is usually long

## Steps to Reproduce

   1. Add a really long name for an account
   2. Select Account dropdown in portfolio
   3. Icon are squished 

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/225843188-7909da11-dffc-4de9-9740-d215fbd117ac.png)

## Expected result:
Should show proper icons

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.50.93 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel

**Comment by vaibhavtevatia** [comment]
Hi, @srirambv can you help me locate the issue? Because in my wallet this is what I see.
![image](https://user-images.githubusercontent.com/86671961/226181417-d3d49f5f-89da-47fb-a181-14506093d169.png)

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.51.103 Chromium: 112.0.5615.165 (Official Build) beta (64-bit) 
-- | --
Revision | `c262f36e6b1d711ee42d4fbe1343b49960593f18-refs/branch-heads/5615@{#1297}`
OS | Linux

- Verified steps from [brave/brave-core#17733](https://github.com/brave/brave-core/pull/17733)
- Verified account icon is not squished when the account name is unusually long
![image](https://user-images.githubusercontent.com/17010094/234495494-829fab40-1823-48bc-9a37-9876a96a31e2.png)

---------------------

**Verification passed on**

Brave | 1.51.103 Chromium: 112.0.5615.165 (Official Build) beta (64-bit)
-- | --
Revision | `c262f36e6b1d711ee42d4fbe1343b49960593f18-refs/branch-heads/5615@{#1297}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from [brave/brave-core#17733](https://github.com/brave/brave-core/pull/17733)
- Verified account icon is not squished when the account name is unusually long
![brave_TXt7M5r6On](https://user-images.githubusercontent.com/17010094/234495822-735ef4fc-81e8-4443-ba42-0e2307d7a117.png)

---------------------

**Verification passed on**

Brave | 1.51.103 Chromium: 112.0.5615.165 (Official Build) beta (arm64)
-- | --
Revision | `c262f36e6b1d711ee42d4fbe1343b49960593f18-refs/branch-heads/5615@{#1297}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#17733](https://github.com/brave/brave-core/pull/17733)
- Verified account icon is not squished when the account name is unusually long
![image](https://user-images.githubusercontent.com/17010094/234496136-a2387a4b-71b1-4193-aa57-305caadcb73b.png)
