### ISSUE TITLE
Add core usage ping metrics via P3A

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#29122]
To reduce the amount of requests sent to P3A servers, it would be ideal to only send answers if the question is relevant to the user.

To do this, we can eliminate the "none" bucket that most questions come with. Percentages for certain buckets are calculated by taking the amount of samples for a bucket, and dividing by the amount of total samples for the question. However, if we eliminate the "none" bucket for some questions, then we cannot use the total amount of samples for the particular question as a denominator for calculating the bucket percentage/ratio, as the sample count does not capture the full browser WAU.

To mitigate this, we can use the total sample count from another question that is reported for all users, and use that as a denominator for calculating bucket ratios for questions are not reported for all users. The "usage ping" metrics will be added for monthly and daily cadences via P3A.

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave | 1.52.109 Chromium: 114.0.5735.26 (Official Build) beta (64-bit)
-- | --
Revision | 7075cbb66f0542ac3e01ddfde6b813e7d61118a5-refs/branch-heads/5735@{#454}
OS | Windows 10 Version 22H2 (Build 19045.2965)

```

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on running `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.52.109`

- Verified the test plan https://github.com/brave/brave-core/pull/17649

<details>
<summary>Brave.Core.UsageMonthly_PASSED</summary>

1. Clean profile 1.52.x
2. Open brave://local-state 
3. Look for the metrics `Brave.Core.UsageMonthly`
4. Confirmed that the metrics `Brave.Core.UsageMonthly` response value is `1` as expected

![Screenshot_20230523_233604](https://github.com/brave/brave-browser/assets/38657976/78021f23-6e42-4659-9ba4-0077ef89b203)


</details>


<details>
<summary>Brave.Core.UsageDaily_PASSED</summary>

1. Clean profile 1.52.x
2. Open brave://local-state 
3. Look for the metrics `Brave.Core.UsageDaily`
4. Confirmed that the metrics `Brave.Core.UsageDaily` response value is `1` as expected

![Screenshot_20230523_233604](https://github.com/brave/brave-browser/assets/38657976/b3e9e0d1-f4a9-4cdd-8e86-7d18f14fff3c)


</details>
