### ISSUE TITLE
Copy/Paste CTRL C/CTRL V does not work on Brave/ M1 Mac

### ISSUE THREAD

**Issue by 007vasy** [brave/brave-browser#29128]
## Description 

Copy/Paste CTRL C/CTRL V does not work on Brave/ M1 Mack

## Steps to Reproduce

   1. go to (chatGPT)[https://chat.openai.com/chat]
   2. type in `lorem ipsum`
   3. copy the response with cmd+c (right click + copy works)
   4. use cmd+v
   5. get back the url https://chat.openai.com/chat

## Actual result:

![image](https://user-images.githubusercontent.com/12837887/225823849-b6a666cc-3dc6-4c45-9164-f0d871da875b.png)

## Expected result:
lorem ipsum text after hitting ctrl+v

## Reproduces how often: 

100%

## Brave version (brave://version info)

Desktop
Release Notes v1.49.120 (Mar 9, 2023)
M1 Mac

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
Yes
- Can you reproduce this issue with the beta channel? 
Did not tried
- Can you reproduce this issue with the nightly channel? 
Did not tried
## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
No
- Does the issue resolve itself when disabling Brave Rewards? 
No
- Is the issue reproducible on the latest version of Chrome? 
I tried but it worked
Version 111.0.5563.64 (Official Build) (arm64)
## Miscellaneous Information:

(issue on the brave community page)[https://community.brave.com/t/copy-and-paste-not-working/477181/3]

**Comment by skull141209** [comment]
Hi, on mac it's different than the windows machine, copy is Command + C. Can you try to use cmd-c or cmd-v first to make sure it's a problem with the browser itself?

**Comment by yjukaku** [comment]
I'm facing the same issue, and I believe the issue only comes if you are copying from certain elements. In my case, an example is that GitHub's new Pull Request page's "title" entry fails to copy when trying to copy via Command + C. It puts the current URL into the clipboard instead.  I must right click then click "Copy" as the OP stated.

![Screenshot 2023-03-17 at 2 30 18 PM](https://user-images.githubusercontent.com/908365/225988776-b3ea91b8-bbf0-4797-94b2-2f0a759f9ff8.png)

**Comment by 007vasy** [comment]
@skull141209 I use an external keyboard, it's the same with CMD+c, CMD+v as well

**Comment by 4tal** [comment]
Didn't manage to identify when works or not but I'm having issues as well with copy paste. 
MBP (not M1) with external Mac keyboard

**Comment by 4tal** [comment]
More information: 
Whenever I'm copy text with link in it, it copy only the link.

MBP Intel, external keyboard.

**Comment by raweber42** [comment]
Got the same issue here. I'm on a MacBook Pro (M2). Only using my internal keyboard though.

**Comment by loke-dev** [comment]
If you check the `edit` menu, you can see that `copy clean link` gets the `cmd+c` command while the normal copy gets no key bind. I have not found a way around this issue.

![image](https://user-images.githubusercontent.com/14079937/226284971-0c5b701b-4e3b-41a5-8b4b-fdc3a7226a74.png)

**Comment by tcampbPPU** [comment]
> If you check the `edit` menu, you can see that `copy clean link` gets the `cmd+c` command while the normal copy gets no key bind. I have not found a way around this issue.
> 
> ![image](https://user-images.githubusercontent.com/14079937/226284971-0c5b701b-4e3b-41a5-8b4b-fdc3a7226a74.png)

Yup the same thing is happening to me. If I quit brave it goes away for a little but then it will happen again randomly

**Comment by spylogsster** [comment]
This should be fixed in Nightly already

**Comment by kroko23** [comment]
From what I observed, this only happens when the address bar is highlighted in red. The solution is to click on the address bar and press the Escape key. This should fix the issue and allow you to copy the desired text.

**Comment by rebron** [comment]
Hi @007vasy @kaliy @kroko23 @loke-dev @raweber42 @4tal @tcampbPPU and others I may have missed. If you have a chance, can you install our latest release candidate that includes this fix https://github.com/brave/brave-browser/releases/tag/v1.49.126 and let us know if you're still encountering the issue.

**Comment by 007vasy** [comment]
@rebron, @spylogsster installed checked works for me
