### ISSUE TITLE
Clear local-storage for wallet page & panel when resetting Brave Wallet

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#29138]
## Description 

Resetting Brave Wallet should remove local-storage data for `brave://wallet/` and `brave://wallet-panel.top-chrome/`

## Steps to Reproduce

   1.  Create a wallet
   2. Select a filter option on the portfolio page
   3. Observe that the selection is persisted to local-storage
   4. open `brave://settings/web3`
   5. Click "Reset Brave Wallet"
   6. Type "Yes" and click OK

## Actual result:

Wallet Local-storage data is unaltered

## Expected result:
Wallet Local-storage should be cleared

## Reproduces how often: 

Easily

## Brave version (brave://version info)

v1.49.120

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

This is a dependency for this PR: [feat(wallet): partially persist redux stores](https://github.com/brave/brave-core/pull/17631#top)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.52.102 Chromium: 113.0.5672.126 (Official Build) beta (64-bit)
-- | --
Revision | `c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}`
OS | Windows 11 Version 22H2 (Build 22621.1702)

- Verified steps from [brave/brave-core#17809](https://github.com/brave/brave-core/pull/17809)
- Verified resetting wallet clears out local-storage for wallet page 
- Encountered [#30455](https://github.com/brave/brave-browser/issues/30455)

https://github.com/brave/brave-browser/assets/17010094/0e045e45-f5c6-46fb-970e-5654ee8d9e23
