### ISSUE TITLE
Social media blocking settings `Allow use of third-party cookies for legacy Google Sign-In` is removed in an upgraded profile

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#29131]
## Description 

Social media blocking settings `Allow use of third-party cookies for legacy Google Sign-In` is removed in an upgraded profile
## Steps to Reproduce

   1. Clean profile 1.49.x /1.50.x nightly build 
   2. Open brave://settings/socialBlocking
   3. Ensure that `Allow use of third-party cookies for legacy Google Sign-In` settings is shown
   4. Upgrade the profile to 1.51.x
   5. Open brave://settings/socialBlocking
   6. `Allow use of third-party cookies for legacy Google Sign-In` settings is removed after upgrade

## Actual result:

Social media blocking settings `Allow use of third-party cookies for legacy Google Sign-In` is removed in an upgraded profile
![image](https://user-images.githubusercontent.com/38657976/225855399-c33fa6d4-fb65-4fba-8745-9972bc1318ca.png)

## Expected result:
The settings should not be removed 

![image](https://user-images.githubusercontent.com/38657976/225855516-54a8b50e-d425-4b9e-9818-dbbe0b3384f0.png)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.51.37 Chromium: 112.0.5615.29 (Official Build) nightly (64-bit)
-- | --
Revision | 8a59304c62e066962363d2fd8edd8e7b459c42bd-refs/branch-heads/5615@{#497}
OS | Windows 10 Version 21H2 (Build 19044.2728)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @ShivanKaul @rebron

**Comment by ShivanKaul** [comment]
This is expected, part of the work in https://github.com/brave/brave-core/pull/16595
