### ISSUE TITLE
Pairing error on messages.android.com

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#2913]
## Description 
User is unable to access the messages.android.com domain.

## Steps to Reproduce
Navigate to messages.android.com

## Actual result:
User is presented with a "Pairing error" message.

## Expected result:
User is not presented with any error messages, and the service works as intended.

## Reproduces how often: 
Easily

## Brave version (brave://version info)
0.58.18

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? Yes
- Is the issue reproducible on the latest version of Chrome? No

### Additional Information
Third party cookies are needed for this page to work properly. When thid-party cookies are blocked via the shields panel, the page fails to fetch a resource at Request URL: https://instantmessaging-pa.googleapis.com/$rpc/google.internal.communications.instantmessaging.v1.Pairing/RegisterPhoneRelay.

**Comment by ryanbr** [comment]
Seems safe to close this @jonathansampson  Domain changed to `https://messages.google.com/`  No cookies being blocked.
