### ISSUE TITLE
Continous crashing while using search bar on any website like google search engine, github.com etc and many others. Now crashing on all websites wherin we try search bars to search something

### ISSUE THREAD

**Issue by tathastu871** [brave/brave-browser#29130]
## Steps to reproduce 

  -> Use google as default search engine in settings
-> perform any search on brave
-> try clicking search bar of google.com search engine to change the query
-> immefiately brave will crash

-> after every two or three search it crashes. been crashed 20 times in last 1 hour. this problem is occuring for last several month

pleaase do somethhing
![20230317_132650](https://user-images.githubusercontent.com/65007212/225845938-b2a533f5-7e63-4180-9143-b8c7189e8538.jpg)

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by tathastu871** [comment]
i am a heavy web surfer i keep searching on google.com
and brave crashes after every 2-3 searches fuck

**Comment by bsclifton** [comment]
@tathastu871 sorry that this issue fell through the cracks ☹️ Do you have any flags on? Like if you visit brave://flags?

Let us know if you're still using Brave. Device details and Android version are appreciated too. Other details like - do you have sync enabled? These types of details will help us narrow down or reproduce the issue. Thanks!

**Comment by tathastu871** [comment]
> @tathastu871 sorry that this issue fell through the cracks ☹️ Do you have any flags on? Like if you visit brave://flags?
> 
> Let us know if you're still using Brave. Device details and Android version are appreciated too. Other details like - do you have sync enabled? These types of details will help us narrow down or reproduce the issue. Thanks!

Sync Enabled
Android 10
Brave Latest via play store
No flags altered by me

Of 10 searches 8 searches causes crash. After crash when i restart browser upto two searches work notmally then crash again.

I am heavy user of search engine i used to search information continously whole day.

**Not only on google.com, Mostly every site i visit that havr search bar when i click search bar brave crashes, specially on heavy sites like google github youtube etc**


Its Increasingly annoying in 5 minutes bravr crashes 7-8 times

**Comment by galaxyrun** [comment]
I have exactly the same problem!

[Screenshot_20230418_213728.jpg](https://user-images.githubusercontent.com/76906352/232886816-075d4795-8742-4b9f-8790-bf313f3756a0.jpg)

**Comment by tathastu871** [comment]
@bsclifton 
Its getting even annoying. Last 5 days i had been observing crashes on clicking back button that takes us to previous websites

**Comment by tathastu871** [comment]
Since devs not responding and correvting this  crash issue
It is excessivley annoying every 5 s and it ctades i visit two website and when i click serach bar to edit the search it crashes


It occurs on all website whethe is yahoo google github any blog or any*** site when we try to click search bar


Here is bloddy proof

https://github.com/brave/brave-browser/assets/65007212/459d9d25-9723-4532-aa00-1a6ae778c28f

**Comment by tathastu871** [comment]
i cant keep my screen records2r 24/7 on to give brave dev the proof that  brabe keeps crashing every few seconds or minutes beacsue that also invade my browsing privact

howver this clip above shows how brave crashes when we click in search bar

**Comment by tathastu871** [comment]
after crashing i would haved clicked send feedback button thousands of time i  this year but looks like brave devs not looking at it

**Comment by amit-katyal** [comment]
> after crashing i would haved clicked send feedback button thousands of time i this year but looks like brave devs not looking at it

Similar situation here, I would suggest you to switch to kiwi with ublock origin until it gets fixed. At this point the crashing on third party search engines seems intentional for them to gain traffic on their own search engine. I personally opened the issue with recording and everything, go no reply. Even reported on crash feedback popup menu as well. This issue is still present on beta and nighty builds after reporting several times. Switching to a different browser will be a smart move at this point.

**Comment by tathastu871** [comment]
It may be occuring as brave cannot handle more than 50tabs open in that case the memory crash may be happening 
@bsclifton pleSe do something notify dev its not about featire request it about crash so it has to be urgently treated

**Comment by tathastu871** [comment]
> > after crashing i would haved clicked send feedback button thousands of time i this year but looks like brave devs not looking at it
> 
> Similar situation here, I would suggest you to switch to kiwi with ublock origin until it gets fixed. At this point the crashing on third party search engines seems intentional for them to gain traffic on their own search engine. I personally opened the issue with recording and everything, go no reply. Even reported on crash feedback popup menu as well. This issue is still present on beta and nighty builds after reporting several times. Switching to a different browser will be a smart move at this point.

Kiwi is ultimate browser just that it doesnt have sync 
and i was used to brave ui

**Comment by amit-katyal** [comment]
> > > after crashing i would haved clicked send feedback button thousands of time i this year but looks like brave devs not looking at it
> > 
> > 
> > Similar situation here, I would suggest you to switch to kiwi with ublock origin until it gets fixed. At this point the crashing on third party search engines seems intentional for them to gain traffic on their own search engine. I personally opened the issue with recording and everything, go no reply. Even reported on crash feedback popup menu as well. This issue is still present on beta and nighty builds after reporting several times. Switching to a different browser will be a smart move at this point.
> 
> Kiwi is ultimate browser just that it doesnt have sync and i was used to brave ui

I am currently using floccus extension for syncing.
Here is a guide to set it up with nextcloud: https://www.reddit.com/r/kiwibrowser/comments/qozcww/kiwi_and_floccus_bookmark_syncing/?utm_source=BD&utm_medium=Search&utm_name=Bing&utm_content=PSR1

you can also use gdrive to setup floccus, works flawlessly!

**Comment by iefremov** [comment]
stale

**Comment by tathastu871** [comment]
Why close. brave still keeps crashing

**Comment by iefremov** [comment]
@tathastu871 can you provide more details on how exactly it crashes and upload dumps from brave://crashes?

**Comment by tathastu871** [comment]
Thats the problem whenever it crashes there are no crash reports generated ocassionaly when cradhed it give option to send feedback report but none od them were read by devs

**Comment by iefremov** [comment]
>  it give option to send feedback report

what option? how does it look? Can you please screenshot it? Also do you have anything on brave://crashes ?
