### ISSUE TITLE
Notify existing opted in Brave Rewards users of Brave Ads launch

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#2914]
For existing Brave Rewards users, notify them of Brave Rewards availability. When Ads are available, drop a notification per image below. Users will be opted in only when they click the button. Users that do-not-click Turn-ON button, ignore the message or closeout will not opted-in to Ads.

Expire message in 1 week if not acted upon. Until then BAT logo notification stays ON.

![image](https://user-images.githubusercontent.com/35932307/51004326-f95e7580-14ee-11e9-9a31-ea9cf2028e40.png)

For users that did not opt-in to Brave Rewards, no message for Ads is shown. cc @davidtemkin @jenn-rhim - please comment on no notification to non Brave Rewards users.

**Comment by NejcZdovc** [comment]
it was reverted https://github.com/brave/brave-core/pull/2295

**Comment by GeetaSarvadnya** [comment]
Verification passed on 


Brave | 0.63.47 Chromium: 74.0.3729.108 (Official Build) (64-bit)
-- | --
Revision | daaff52abef89988bf2a26091062160b1482b108-refs/branch-heads/3729@{#901}
OS | Windows 10 OS Build 17134.523

- Verified the test plan from https://github.com/brave/brave-core/pull/1365
![image (1)](https://user-images.githubusercontent.com/38657976/56579539-0f9bc780-65ee-11e9-87ba-2aeae5819c12.png)

**Comment by srirambv** [comment]
Marking issue as Windows/MacOS. Logged  #4206 as a followup for Linux
