### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by vwalker04** [brave/brave-browser#29148]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.49.122  Chromium: 111.0.5563.64
Operating System: Android 13

URL (if applicable) where crash occurred:

Can you reproduce this crash?
Yes

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Enter credit card payment details on site 
2. Submit
3. Page crashes/ disappears. Doesn't have a problem in Chrome

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/9b8c0100-d711-c809-0000-000000000000

**Comment by bsclifton** [comment]
Backtrace link:

https://brave.sp.backtrace.io/p/brave/debug?time=quarter&filters=(_deleted%3D0%2C_rxid%3D%229b8c0100-d711-c809-0000-000000000000%22)&fingerprint=bc91eacc9fa02fee7cbc45f6fc1f5e9ed33628c11387309e02839d37973fc962&debug=(%2247a7e03%22,0,0)

**Comment by SergeyZhukovsky** [comment]
@vwalker04 we are rolling out `v1.49.132` currently, you should see an update today-tomorrow. Could you please try it there and report it back, does it solve your problem or not? I don't see such crashes in it anymore.

**Comment by bsclifton** [comment]
Closing as stale - let's re-open if this is still present 😄
