### ISSUE TITLE
Can't log into mixer.com

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#2915]
## Description 
The user is unable to log into mixer.com.

## Steps to Reproduce
1. Go to mixer.com
2. Click Sign In
3. Click Sign in with Microsoft

## Actual result:
User cannot log into mixer.com without first _allowing all cookies_.

## Expected result:
User is able to log into mixer.com without complication.

## Reproduces how often: 
Easily.

## Brave version (brave://version info)
0.58.18

### Reproducible on current release:
Yes 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? Yes
- Is the issue reproducible on the latest version of Chrome? No

### Additional Information
Allowing all cookies from the Shields Panel resolves the issue.

**Comment by ryanbr** [comment]
@jonathansampson  was able to login with shields on/cross-site cookies. Can you confirm?

**Comment by ryanbr** [comment]
Given the age of the report, and works fine (re-tested), closing this report.
