### ISSUE TITLE
Links from Reddit Email Digest Won't Open in Brave Browser

### ISSUE THREAD

**Issue by jerryisaac** [brave/brave-browser#29151]
## Description 
Following the latest upgrade of Brave [Version 1.49.120 Chromium: 111.0.5563.64 (Official Build) (arm64)] on my M2-based MacBook Air running macOS 13.2.1 (22D68), the links that I click on from within my Reddit email digest suddenly don't properly render in Brave. All I see is {}.

## Steps to Reproduce
   1.  Click on this [link](https://reddit.app.link/3p?$3p=e_as&$original_url=https%3A%2F%2Fwww%2Ereddit%2Ecom%2Fr%2FPython%2Fcomments%2F11syxd0%2Fthe%5Fruff%5Fpython%5Flinter%5Fis%5Finsanely%5Fgood%2F%3F%24deep%5Flink%3Dtrue%26correlation%5Fid%3Db365f1ae%2D4649%2D4e92%2Da24d%2Dc4058f5c2558%26post%5Ffullname%3Dt3%5F11syxd0%26post%5Findex%3D1%26ref%3Demail%5Fdigest%26ref%5Fcampaign%3Demail%5Fdigest%26ref%5Fsource%3Demail%26utm%5Fcontent%3Dpost%5Ftitle), which was taken from my Reddit digest.

## Actual result:
<img width="1225" alt="Screenshot 2023-03-18 at 9 47 13 AM" src="https://user-images.githubusercontent.com/90640923/226121011-5e9e95d3-1601-4a80-9f8e-97b6755c8019.png">

## Expected result:
I expect to go to the Reddit page, like I'm able to in iOS and in Safari on my Mac (here's the image from the Selenium-opened instance of Brave, which actually works; see "Other Additional Information" below for more details about this).

<img width="1026" alt="Screenshot 2023-03-18 at 10 00 55 AM" src="https://user-images.githubusercontent.com/90640923/226121760-28958b06-d721-4003-a70b-30eb20ed2792.png">

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Brave	1.49.120 Chromium: 111.0.5563.64 (Official Build) (arm64) 
Revision	c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS	macOS Version 13.2.1 (Build 22D68)
JavaScript	V8 11.1.277.13
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Command Line	/Applications/Brave Browser.app/Contents/MacOS/Brave Browser --allow-pre-commit-input --disable-background-networking --disable-blink-features=AutomationControlled --disable-client-side-phishing-detection --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-hang-monitor --disable-infobars --disable-popup-blocking --disable-prompt-on-repost --enable-blink-features=ShadowDOMV0 --enable-logging --log-level=0 --no-first-run --no-sandbox --no-service-autorun --password-store=basic --remote-debugging-port=0 --start-maximized --test-type=webdriver --use-mock-keychain --user-data-dir=/var/folders/yv/_kckxfx138s_shj15q4_mg3w0000gn/T/.com.google.Chrome.FHkokO --disable-domain-reliability --enable-dom-distiller --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --variations-insecure-server-url=https://variations.brave.com/seed --flag-switches-begin --flag-switches-end --component-updater=url-source=https://go-updater.brave.com/extensions data:,
Executable Path	/Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path	/private/var/folders/yv/_kckxfx138s_shj15q4_mg3w0000gn/T/.com.google.Chrome.FHkokO/Default
Linker	lld

## Version/Channel Information:
Only specific to the Brave browser instance on my Mac that I manually open (as opposed to a Selenium-opened instance).

- Can you reproduce this issue with the current release? Yes.
- Can you reproduce this issue with the beta channel? Didn't try, but I will.
- Can you reproduce this issue with the nightly channel? I'm not sure what this is, but I'll investigate this.

## Other Additional Information:
I had two instances of Brave open, one I manually opened, and one opened by Selenium from a Python script I ran. What's interesting is when I closed the manually opened instance, then clicked on the reddit link, a tab in the Selenium-opened instance correctly rendered the link. So, something's going on with my personal settings.

Disabling Brave Shields does not resolve this issue.
Disabling Brave Rewards does not resolve this issue.
I didn't try on Chrome because I don't what to use it at all (that's why I'm using Brave!). However, I can try this if you really need me to.

## Miscellaneous Information:
Nothing else I can think of.

## Update to Issue (3/19/23):
I struck through my first edit immediately below; it's still valid, but the issue returned after I uninstalled the beta version of Brave. So, I'm hopeful that when the beta version is released into production, this issue will go away.

~~I am no longer having this issue, but I'm not sure how it got resolved. The only thing I did that might have affected this is the downloading of the beta version of Brave (perhaps the beta installation overwrote a file that's shared with the non-beta version, but I'm just speculating). FWIW, the Reddit links work properly in both browser versions. Thanks to all who responded!~~

**Comment by gothy** [comment]
Same here on Android, too.

**Comment by mer2329** [comment]
ive got this too. it takes me to a page that simply has curvy brackets
brave shields off as well.

**Comment by Ghost-Moose** [comment]
I am getting the same. All links in the reddit daily email just opens to a page with curly brackets { }

**Comment by tgiannet** [comment]
I'm having the same issue on Windows PC - I think it started happening about a week or so ago, but it's very odd. I tested the EXACT same link in Chrome and it works - I assume it's working in all CHROMIUM browsers.

> Brave is up to date
> [Version 1.49.120 Chromium: 111.0.5563.64 (Official Build) (64-bit)](https://brave.com/latest/)

**Comment by tgiannet** [comment]
> ive got this too. it takes me to a page that simply has curvy brackets brave shields off as well.
> 
> edit: i disabled all private allowed extensions and tried and it did the same
> 
> edit 2: i made brave use a new profile, (followed this [guide](https://www.chromium.org/developers/creating-and-using-profiles/)) and the reddit email links worked. i dont know what changed that broke it for us.

We shouldn't have to change our profile to get this working... Please help, dev team

**Comment by Ghost-Moose** [comment]
Confirmed. This appears to be working properly now.
