### ISSUE TITLE
address `Sonarcloud` warning regarding not using `noopener` 

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#29159]
Please take a look and address the security warnings that https://sonarcloud.io/project/security_hotspots?id=brave_brave-core&pullRequest=17633&resolved=false&types=SECURITY_HOTSPOT flagged re: ensuring that not using `noopener` is safe. Looks like the affected code is found via `components/brave_wallet_ui/stories/wallet-extension-panels.tsx`.

![image](https://user-images.githubusercontent.com/2602313/226232698-7453a9fb-f840-45b2-b640-2611cc291b3a.png)

CCing @diracdeltas

**Comment by Douglashdaniel** [comment]
I believed this has been addressed by **https://github.com/brave/brave-browser/issues/28700**
cc: @diracdeltas ?

**Comment by diracdeltas** [comment]
this is a different one but it's not a big deal since it's in storybook only AFAICT. i'll close
