### ISSUE TITLE
Add missing network icons to show Android

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#29166]
## Description 
Add missing network icons (Aurora, Arbitrum etc.) to show actual icon instead of ETH icon on Asset list (Portfolio etc).

## Expected
Should show the correct network icon in asset list (e.g. Portfolio, add assets, buy, send, swap etc.)

Related: [Update ETH icon to use Aurora ETH icon](https://github.com/brave/brave-browser/issues/24210)

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.51.87 x64 Beta build
- Verified steps from issue description and [brave/brave-core#17692](https://github.com/brave/brave-core/pull/17692)
- Verified Network icon is shown for native assets as expected

Oppo Reno 5 (Android 13) | Lenovo Tab (Android 12)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/232076903-fe84e31c-72cb-45cd-a39d-3463babbc992.mp4> | <video src=https://user-images.githubusercontent.com/17010094/232076840-46622892-339c-444d-8299-f5ca9e5e90e5.mp4>
