### ISSUE TITLE
Show network filter for Solana/Filecoin only when respective testnets are enabled

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#29161]
## Description 

Show network filter for Solana/Filecoin only when respective testnets are enabled

## Steps to Reproduce

   1. Select Solana Account or Filecoin Account on portfolio page
   2. Open network filter
   3. Shows `All networks` which is redundant for Solana/Filecoin network when respective testnetworks are disabled

## Actual result:

Solana | Filecoin
-- | --
![image](https://user-images.githubusercontent.com/17010094/226247160-0f229fdf-5138-481f-89c6-d915bbc8adb5.png) | ![image](https://user-images.githubusercontent.com/17010094/226247233-a210b1b7-902d-4685-a622-bd0b7b2ed5dd.png)

## Expected result:
Enable network filter by default for EVM's and only enable network filter for Solana/Filecoin only when testnet is enabled

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.51.38 Chromium: 111.0.5563.64 (Official Build) nightly (64-bit)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Linux

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel

**Comment by Douglashdaniel** [comment]
Dropdown filters were removed in `Wallet V2` is no longer an issue, closing as `Invalid`

![Screenshot 71](https://github.com/brave/brave-browser/assets/40611140/8555f4f7-fb8e-4a2c-9c4a-0034cd8b6c2b)
