### ISSUE TITLE
Show overlapping network icon and network name on assets list item

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#29165]
## Description 
Show overlapping network icon and network name on assets list item on Portfolio

Image: 

![Screenshot from 2023-03-20 13-56-23](https://user-images.githubusercontent.com/11755381/226285141-f180d8e4-d36d-4f27-ba75-c99032eefd02.png)

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.51.87 x64 Beta build
- Verified steps from issue description and [brave/brave-core#17692](https://github.com/brave/brave-core/pull/17692)
- Verified network icon is added to all assets to differentiate visually

Oppo Reno 5 (Android 13) | Lenovo Tab (Android 12)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/232076903-fe84e31c-72cb-45cd-a39d-3463babbc992.mp4> | <video src=https://user-images.githubusercontent.com/17010094/232076840-46622892-339c-444d-8299-f5ca9e5e90e5.mp4>
