### ISSUE TITLE
Remove Celo from preloaded networks

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#29162]
We've had negligible activity on Celo for a while, so remove it from the list of preloaded networks. Users should still be able to add Celo network from Web3 settings.

### Test plan

1. Celo network is no longer a preloaded network
2. If Celo is manually added as a network, then the assets belonging to the Celo network can be seen in Swap/Buy/Sell.

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.51.109 Chromium: 113.0.5672.63 (Official Build) (64-bit)
-- | --
Revision | `0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from issue description
- Verified Celo network is removed from pre-loaded network list on a clean profile
- Verified Celo network is not retained on an upgraded profile in a wallet that is already created and token balance is available
- Verified Celo network when added as a custom network shows token for Buy/Sell/Swap
