### ISSUE TITLE
Tabs Search Button Setting not being respected by Brave Browser

### ISSUE THREAD

**Issue by Vactarian** [brave/brave-browser#29176]
## Description 

In brave://settings/appearance I set "Show Tab Search Button" to OFF, The tab search button disappears as it should, then when I restart the browser the tabs search button is now back, When I go into brave://settings/appearance I find the option is still set to OFF however the tabs search button is still showing.

## Steps to Reproduce

   1. Go into brave://settings/appearance turn Show Tab Search Button to OFF.
   2. Restart the browser.
   3. Go back into brave://settings/appearance and you will see the Show Tab Search Button setting is set to Off yet the button is showing.

## Expected result:
Should turn the Tabs Search button off and the button show stay not showing even upon restart of the browser.

## Brave version (brave://version info)

Brave | 1.51.43 Chromium: 111.0.5563.64 (Official Build) nightly (64-bit)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | Linux
JavaScript | V8 11.1.277.13
User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Command Line | /opt/brave.com/brave-nightly/brave --desktop-startup-id=PrimeCore;1679328820;340631;25238_TIME133606190 --disable-domain-reliability --enable-dom-distiller --lso-url=https://no-thanks.invalid --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --variations-insecure-server-url=https://variations.brave.com/seed --variations-server-url=https://variations.brave.com/seed --restart --flag-switches-begin --top-chrome-touch-ui=disabled --enable-features=BraveBlockScreenFingerprinting,BraveReduceLanguage --disable-features=AllowCertainClientHints,AllowedToFallbackToCustomAdNotifications,BraveChangeActiveTabOnScrollEvent,BraveFederated,BraveNews,BraveNewsCardPeek,BraveNewsV2,BraveRewardsAllowUnsupportedWalletProviders,BraveRewardsGemini,BraveRewardsVBatNotice,BraveRewardsVerboseLogging,BraveWalletDappsSupport,BraveWalletFilecoin,BraveWalletPanelV2,BraveWalletSns,BraveWalletSolana,BraveWalletSolanaProvider,CryptoWalletsForNewInstallsFeature,CustomAdNotifications,EnableTabMuting,LayoutExtraction,NativeBraveWallet,OmniboxDocumentProvider,ScrollableTabStrip,TabScrollingButtonPosition,WebBluetooth,WebBluetoothNewPermissionsBackend,WebUsbDeviceDetection,kScrollableTabStripWithDragging --flag-switches-end --component-updater=url-source=https://go-updater.brave.com/extensions,url-source=https://go-updater.brave.com/extensions
Executable Path | /opt/brave.com/brave-nightly/brave
Profile Path | /home/seb/.config/BraveSoftware/Brave-Browser-Nightly/Default
Active variations | AdRewardsStudy:NextPaymentDayAllowCertainClientHintsStudy:EnabledBraveAdblockCookieListOptInStudy:EnabledBraveAds.AdNotificationsStudy:AdNotificationTimeout=60BraveAds.AdServingStudy:DefaultAdNotificationsPerHour=10/MaximumAdNotificationsPerDay=100/MaximumInlineContentAdsPerHour=6/MaximumInlineContentAdsPerDay=20/AdServingVersion=2/AdPredictorWeights=32.0,16.0,16.0,8.0,4.0,2.0,1.0BraveAds.FrequencyCappingStudy:ExcludeAdIfWithinTimeWindow=0hBraveAutoTranslateStudy:AutoTranslateDisabledBraveDebounceStudy:EnabledBraveGoogleSignInPermissionStudy:EnabledBraveHttpsByDefaultRolloutStudy:EnabledBraveRewardsWebUiPanelStudy:EnabledBraveScreenFingerprintingBlockerStudy:EnabledBraveSearchPromotionDesktopNTPStudy:EnabledConversionsStudy:NewDefaultPatternCosmeticFilteringChildFramesStudy:EnabledDeAMPStudy:EnabledDefault1pBlockingStudy:DisabledDisableReduceLanguage:EnabledEphemeralStorageStudy:EnabledFirstPartyEphemeralDomainBlockStudy:EnabledForceDisableBlinkFeatures:EnabledHangWatcher:HangWatcherEnableDumpsPartitionBlinkMemoryCacheStudy:EnabledPartitionConnectionsByNetworkIsolationKeyStudy:EnabledPermissionLifetimeStudy:EnabledUserActivityStudy:Triggers

## Version/Channel Information:

- Can you reproduce this issue with the current release?  Unsure
- Can you reproduce this issue with the beta channel?  Unsure
- Can you reproduce this issue with the nightly channel?  Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? Unknown

## Miscellaneous Information:

I do not have any other channel of this browser installed on my system aside from nightly so I am not sure if it is happening on other channels.

**Comment by joecorporon** [comment]
Hi Vactarian,

I'm glad you reported this issue. I'm using Brave on Manjaro Linux and have noticed the same behavior.

**Comment by rebron** [comment]
Hi @Vactarian @joecorporon Are you still seeing this issue in 1.52.130? We addressed this issue with https://github.com/brave/brave-browser/issues/30829

**Comment by joecorporon** [comment]
The issue seems to be resolved for me. Thanks!

Joe Corporon

**Comment by rebron** [comment]
Closing per last comment. Thanks for verifying.
