### ISSUE TITLE
Wrap copy clean link hotkey replacement to a feature flag

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#29177]
We replace default `ctrl+c` hotkey to copy sanitized links by default, need to add a feature flag to let users use default logic if needed.

**Comment by spylogsster** [comment]
cc @rebron @fmarier @bsclifton

**Comment by kaliy** [comment]
Yes, please! That would solve the issue #29128 :)

**Comment by mkamranpk** [comment]
> We replace default `ctrl+c` hotkey to copy sanitized links by default, need to add a feature flag to let users use default logic if needed.

I would argue it should be the other way around: 'ctrl+c' should copy by default, and the feature flag should enable switching to 'copy sanitized links' - thanks!

**Comment by LaurenWags** [comment]
@brave/qa-team should verify this on Win, Linux and macOS. On macOS should verify on both Intel and M1.

**Comment by kjozwiak** [comment]
The above requires `1.49.127` or higher for `1.49.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.49.128 Chromium: 111.0.5563.110 (Official Build) (x86_64)
-- | --
Revision | 3da375c9e9e5ad9b556af5df708a6e6c01d8cfb1-refs/branch-heads/5563@{#1202}
OS | macOS Version 12.6.3 (Build 21G419)
```

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.49.128 Chromium: 111.0.5563.110 (Official Build) (64-bit)
-- | --
Revision | 3da375c9e9e5ad9b556af5df708a6e6c01d8cfb1-refs/branch-heads/5563@{#1202}
OS | Ubuntu 18.04 LTS


<details>
<summary>Default - PASSED</summary>

Ran through the below steps to confirm expected locations of "Copy clean link" option from, context menu, share menu, and keyboard shortcut:

0. Confirmed value of "Default" for brave://flags/#brave-copy-clean-link-by-default
1. Visited `https://dev-pages.bravesoftware.com/clean-urls/?brave_testing1=foo&brave_testing2=bar&brave_testing3=keep&&;b&d&utm_content=removethis&e=&f=g&=end`
3. Right-clicked the URL and confirmed "Copy clean link" is in the context menu
4. Confirmed "Copy clean link" is displayed in the share menu from URL bar
5. Used "Cmd + C" while the URL bar is in focus to copy the URL
6. Opened a new tab and pasted the copied URL
7. Confirmed link is `https://dev-pages.bravesoftware.com/clean-urls/?brave_testing3=keep&&;b&d&e=&f=g&=end` as per the original issue verification from https://github.com/brave/brave-browser/issues/23315
8. Opened a new tab and visited `https://twitter.com/LBC/status/1577628501364146176?s=20&t=fpVMBMSfgI_pNGQxxpV6bw`
9. Used "Cmd + C" while the URL bar is in focus to copy the URL
10. Opened a new tab and pasted the copied link
11. Confirmed link pasted is `https://twitter.com/LBC/status/1577628501364146176` as per the original issue verification from https://github.com/brave/brave-browser/issues/23315

![image](https://user-images.githubusercontent.com/34715963/226937190-23ffa14d-f0a1-414e-a52c-a785ab07430b.png)|![image](https://user-images.githubusercontent.com/34715963/226937817-e21a3f0d-2e1a-4ef9-8251-32216d33b49f.png)|![image](https://user-images.githubusercontent.com/34715963/226937945-440c9581-ddbb-4103-a868-e188d28bee39.png)|![image](https://user-images.githubusercontent.com/34715963/226938295-01199054-3aa4-41c6-a64d-57d833e15212.png)|![image](https://user-images.githubusercontent.com/34715963/226938525-448ed98e-f30c-4f71-8b17-6afd0ee3ebbb.png)|![image](https://user-images.githubusercontent.com/34715963/226938626-8744d8ed-545a-4106-b2b8-8b7c19e51e05.png)
--|--|--|--|--|--


</details>

<details>
<summary>Disabled - PASSED</summary>

Case A: Ran through appropriate cases on https://fmarier.github.io/brave-testing/copy-clean-link.html to confirm functionality still works with the keyboard shortcut disabled. (spot check of "Copy clean link" functionality)

Case B: Ran through the below steps to confirm expected locations of "Copy clean link" option and confirm that keyboard shortcut is not used for "Copy clean link":

0. Confirmed value of "Disabled" for brave://flags/#brave-copy-clean-link-by-default
1. Visited `https://dev-pages.bravesoftware.com/clean-urls/?brave_testing1=foo&brave_testing2=bar&brave_testing3=keep&&;b&d&utm_content=removethis&e=&f=g&=end`
3. Right-clicked the URL and confirmed "Copy clean link" is in the context menu
4. Confirmed "Copy clean link" is displayed in the share menu from URL bar
5. Used "control + C" while the URL bar is in focus to copy the URL
6. Opened a new tab and pasted the copied URL
7. Confirmed link pasted is the original URL with all parameters: `https://dev-pages.bravesoftware.com/clean-urls/?brave_testing1=foo&brave_testing2=bar&brave_testing3=keep&&;b&d&utm_content=removethis&e=&f=g&=end`
8. Opened a new tab and visited `https://twitter.com/LBC/status/1577628501364146176?s=20&t=fpVMBMSfgI_pNGQxxpV6bw`
9. Used "control + C" while the URL bar is in focus to copy the URL
10. Opened a new tab and pasted the copied link
11. Confirmed link pasted is the original URL with all parameters `https://twitter.com/LBC/status/1577628501364146176?s=20&t=fpVMBMSfgI_pNGQxxpV6bw` 

![image](https://user-images.githubusercontent.com/34715963/226940274-f7ca3458-02a7-421a-bbfa-bb9eded1e2a5.png)|![image](https://user-images.githubusercontent.com/34715963/226942376-773a50b8-5110-493f-b606-dbfad20790f4.png)|![image](https://user-images.githubusercontent.com/34715963/226942561-3eff32b2-4041-4cf4-85a1-128d45956baf.png)|![image](https://user-images.githubusercontent.com/34715963/226942851-7f3ab306-2cba-45d1-839b-307082291000.png)|![image](https://user-images.githubusercontent.com/34715963/226942707-b3b28577-6979-4eb0-81bd-4c573494a375.png)
--|--|--|--|--


</details>

<details>
<summary>Enabled - PASSED</summary>

Case A: Ran through appropriate cases on https://fmarier.github.io/brave-testing/copy-clean-link.html to confirm functionality works as expected with the keyboard shortcut enabled. (spot check of "Copy clean link" functionality)

Case B: Ran through the below steps to confirm expected locations of "Copy clean link" option and confirm that keyboard shortcut is used for "Copy clean link":

0. Confirmed value of "Default" for brave://flags/#brave-copy-clean-link-by-default
1. Visited `https://dev-pages.bravesoftware.com/clean-urls/?brave_testing1=foo&brave_testing2=bar&brave_testing3=keep&&;b&d&utm_content=removethis&e=&f=g&=end`
3. Right-clicked the URL and confirmed "Copy clean link" is in the context menu
4. Confirmed "Copy clean link" is displayed in the share menu from URL bar
5. Used "Cmd + C" while the URL bar is in focus to copy the URL
6. Opened a new tab and pasted the copied URL
7. Confirmed link is `https://dev-pages.bravesoftware.com/clean-urls/?brave_testing3=keep&&;b&d&e=&f=g&=end` as per the original issue verification from https://github.com/brave/brave-browser/issues/23315
8. Opened a new tab and visited `https://twitter.com/LBC/status/1577628501364146176?s=20&t=fpVMBMSfgI_pNGQxxpV6bw`
9. Used "Cmd + C" while the URL bar is in focus to copy the URL
10. Opened a new tab and pasted the copied link
11. Confirmed link pasted is `https://twitter.com/LBC/status/1577628501364146176` as per the original issue verification from https://github.com/brave/brave-browser/issues/23315

![image](https://user-images.githubusercontent.com/34715963/226966663-602c0bd9-5e36-4ac1-a1b3-d49a173a0d27.png)|![image](https://user-images.githubusercontent.com/34715963/226966853-102dc7bf-dcff-4573-8cf2-20352acdac31.png)|![image](https://user-images.githubusercontent.com/34715963/226966972-68169424-3ba2-46a1-bdb2-fad56e04f268.png)|![image](https://user-images.githubusercontent.com/34715963/226967098-1e1deb64-975a-4ea0-aef3-2adc3689731c.png)|![image](https://user-images.githubusercontent.com/34715963/226967270-5f716af0-e2bd-4b9e-bd1c-41f7519bad6c.png)![image](https://user-images.githubusercontent.com/34715963/226967344-4787f557-0bd1-46de-be31-6533f1711b7b.png)
--|--|--|--|--|--

</details>

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.49.128 Chromium: 111.0.5563.110 (Official Build) (arm64)
-- | --
Revision | 3da375c9e9e5ad9b556af5df708a6e6c01d8cfb1-refs/branch-heads/5563@{#1202}
OS | macOS Version 12.6.3 (Build 21G419)
```

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.49.128 Chromium: 111.0.5563.110 (Official Build) (64-bit)
-- | --
Revision | 3da375c9e9e5ad9b556af5df708a6e6c01d8cfb1-refs/branch-heads/5563@{#1202}
OS | Windows 10 Version 22H2 (Build 19045.2728)

<details>
<summary>Default - PENDING</summary>



</details>

<details>
<summary>Disabled - PENDING</summary>


</details>

<details>
<summary>Enabled - PENDING</summary>

</details>

**Comment by marcfitt** [comment]
Hell yeah! Do you think we can have it disable by default?

**Comment by dextart** [comment]
> > > We replace default `ctrl+c` hotkey to copy sanitized links by default, need to add a feature flag to let users use default logic if needed.
> > 
> > 
> > I would argue it should be the other way around: 'ctrl+c' should copy by default, and the feature flag should enable switching to 'copy sanitized links' - thanks!
> 
> 100% We've already had multiple users ditch Brave because of this change.

Totally agree. You can't just switch universally used shortcut to something only a handful people find useful. I lost productive time and sanity and almost switched back to Chrome before finding this thread and the flag. Whoever thought this was a good idea didn't have their brightest moment.
