### ISSUE TITLE
Relaunch button mismatch between brave://rewards and brave://settings/rewards - Follow up to 28023

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#29182]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/28023

Found several scenarios which lead to either brave://rewards or brave://settings/rewards displaying a `Relaunch` button, and the other page does not.

## Steps to Reproduce

Scenario 1:

1. Install 1.50.x.
2. Join Rewards and connect to custodian
3. On brave://rewards, click on the Tips section's settings button
4. Note that the
    a. `Show Tip buttons on sites` toggle is turned `on`
    b. All checkboxes under the toggle are checked
5. Turn the `Show Tip buttons on sites` toggle to `off`
6. Verify that:
    a. the checkboxes under the toggle are not shown.
    b. the `Relauch` button is shown.
7. Open brave://settings/rewards page in a new tab or new window.
---> the `Show Tip buttons on sites` also transitioned to `off`, no checkboxes are shown, but the `Relaunch` button is not shown. So we have a mismatch between brave://rewards and brave://settings/rewards on whether to relaunch or not.
---> Note, if you had brave://settings/rewards open prior to making the change in step 5, then the `Relaunch` button is shown correctly

Step 7:
<img width="2386" alt="TC1 step 7" src="https://user-images.githubusercontent.com/28145373/226423555-02aa6ba6-918f-4332-81a2-cd4ea2318512.png">

Scenario 2:

1. Install 1.50.x.
2. Join Rewards and connect to custodian (close brave://rewards page if open)
3. Nav to brave://settings/rewards
4. Note that the
    a. `Show Tip buttons on sites` toggle is turned `on`
    b. All checkboxes under the toggle are checked
5. Turn the `Show Tip buttons on sites` toggle to `off`
6. Verify that:
    a. the checkboxes under the toggle are not shown.
    b. the `Relauch` button is shown.
7. Open brave://rewards page in a new tab or new window and open the "Tips" settings
---> the `Show Tip buttons on sites` also transitioned to `off`, no checkboxes are shown, but the `Relaunch` button is not shown. So we have a mismatch between brave://rewards and brave://settings/rewards on whether to relaunch or not.
---> Note, if you had brave://rewards open prior to making the change in step 5, then the `Relaunch` button is shown correctly

Step 7:

<img width="2392" alt="TC2 step 7" src="https://user-images.githubusercontent.com/28145373/226423811-c8dd6ad0-097e-4945-b01e-91f70fa95748.png">

Scenario 3:

1. Install 1.50.x.
2. Join Rewards and connect to custodian
3. Navigate to brave://rewards and click on the Tips section's settings button
4. Note that the
    a. `Show Tip buttons on sites` toggle is turned `on`
    b. All checkboxes under the toggle are checked
5. Open brave://settings/rewards page in a new tab or new window.
6. Go back to brave://rewards and turn the `Show Tip buttons on sites` toggle to `off`
7. Verify that:
    a. the checkboxes under the toggle are not shown.
    b. the `Relaunch` button is shown.
8. Go to already opened brave://settings/rewards page and the `Show Tip buttons on sites` also transitioned to `off`, no checkboxes are shown, and the `Relaunch` button is shown.
9. On brave://settings/rewards page toggle the `Show Tip buttons on sites` to `on`
10. Verify that the `Relaunch` button is no longer shown
11. Go back to the already opened brave://rewards -> Tips section's settings screen
---> `Relaunch` button still shown

Step 7-8 | Step 9-11
--- | ---
<img width="2387" alt="TC4 step 7 and 8" src="https://user-images.githubusercontent.com/28145373/226424003-51c07814-a305-4012-b351-3c215b1c265e.png"> | <img width="2387" alt="TC4 step9-11" src="https://user-images.githubusercontent.com/28145373/226424006-2e73eb7d-5473-4f6a-b785-7a187ae4906c.png">

## Actual result:

See screenshots above.

## Expected result:

brave://rewards and brave://settings/rewards should match on whether a "Relaunch" button is displayed.

## Reproduces how often: 

easily

## Brave version (brave://version info)

1.50.92 Chromium: 111.0.5563.64 (Official Build) beta (x86_64) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? no, `Show Tip buttons on sites` toggle is not in 1.49.x
- Can you reproduce this issue with the beta channel? yes 1.50.x
- Can you reproduce this issue with the nightly channel? unsure, probably yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @Miyayes

**Comment by mkarolin** [comment]
No longer valid as tipping buttons have been removed (https://github.com/brave/brave-browser/issues/34367).
