### ISSUE TITLE
"Relaunch" button did not go away on brave://rewards - follow up to 28023

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#29183]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/28023

`Relaunch` button did not go away on brave://rewards when changing the `Show Tip buttons on sites` toggle back to the original setting.

## Steps to Reproduce

1. Install 1.50.x.
2. Join Rewards and connect to custodian
3. On brave://rewards, click on the Tips section's settings button
4. Note that the
    a. `Show Tip buttons on sites` toggle is turned `on`
    b. All checkboxes under the toggle are checked
5. Turn the `Show Tip buttons on sites` toggle to `off`
6. Verify that:
    a. the checkboxes under the toggle are not shown.
    b. the `Relaunch` button is shown.
7. Turn the `Show Tip buttons on sites` toggle to `on` and the checkboxes come back into view as expected
---> However, the `Relaunch` button does not go away 

Note, if you repeat this test on the brave://settings/rewards page, the `Relaunch` button goes away as expected

## Actual result:

Step 6 | Step 7
--- | ---
<img width="1189" alt="TC3 Step 6" src="https://user-images.githubusercontent.com/28145373/226425576-c1713773-99ff-4e37-bbb5-c1c0ffec1c36.png"> | <img width="1191" alt="TC3 Step 7" src="https://user-images.githubusercontent.com/28145373/226425578-25778f7f-5d04-4ca8-9cae-13c163b1a50c.png">

## Expected result:

Expected "Relaunch" button to go away on step 7 since the toggle was set back to the original without relaunching. 

## Reproduces how often: 

easily

## Brave version (brave://version info)

1.50.92 Chromium: 111.0.5563.64 (Official Build) beta (x86_64) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? no, `Show Tip buttons on sites` toggle is not in 1.49.x
- Can you reproduce this issue with the beta channel? yes 1.50.x
- Can you reproduce this issue with the nightly channel? unsure, probably yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @Miyayes

**Comment by mkarolin** [comment]
No longer valid as tipping buttons have been removed (https://github.com/brave/brave-browser/issues/34367).
