### ISSUE TITLE
Issue with element block picker when the extension Dark Reader is installed

### ISSUE THREAD

**Issue by Zelmanyr** [brave/brave-browser#29185]
Hi,

When Dark Reader is installed on Brave, when a website is stylised by it and we want to block an element on the page with Right Click > Brave > Blocked element, normally we would see the website and can select an element, but now we see a blank page but still can select an element to block (but it is annoying since we don't really see the element due to the blank page).

Screenshot: https://i.imgur.com/flt4kZp.png

To note that, if Dark Reader is disabled, it works correctly.

Edit: Now that I tried more, it seems that it also have an issue on Github whether the Dark Reader extension is disabled or not. Yeah, I confirm that with all extensions disabled, the blocked element picker does not work on Github. Other websites might be affected too then.

Have a good day.

**Comment by antonok-edm** [comment]
Appears to be related to the CSS [`color-scheme` property](https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme). Apparently the iframe is given a non-transparent black background in a dark color scheme, but a transparent background in a light color scheme. We could fix this by forcing a light colorscheme on the generated iframe element.

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` 

Brave | 1.51.77 Chromium: 112.0.5615.49 (Official Build) beta (x86_64)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | macOS Version 11.7.5 (Build 20G1225)

### Case One: `Dark` mode - `PENDING`
<details>



</details>


### Case Two: `#enable-force-dark` mode - `PASSED`
<details>

### Steps:
1. installed `1.51.77`
2. launched Brave
3. opened `brave://flags`
4. set `brave://flags/#enable-force-dark` to `Enabled`
5. clicked `Relaunch`
6. loaded `https://github.com/brave/brave-browser`
7. context-clicked on a page element
8. chose `Brave > Block element`
9. clicked `Create`
10. confirmed the blocked region's content was hidden/blocked
11. opened `brave://adblock`
12. confirmed the filter-rules were present
13. removed them
14. clicked `Saved changes`
15. reloaded `github.com`
16. confirmed the previously-blocked content re-appeared

`brave://flags` | `example` | `example` | `example` | `example` | `example` | `example`
----------------|-----------|-----------|------------|-----------|------------|-----------
<img width="1312" alt="Screen Shot 2023-04-05 at 4 24 09 PM" src="https://user-images.githubusercontent.com/387249/230236126-75ace437-9b95-4553-bedf-cf504ec450cc.png"> | <img width="1312" alt="Screen Shot 2023-04-05 at 4 26 59 PM" src="https://user-images.githubusercontent.com/387249/230236159-8664acb1-99d1-45b4-82f3-00f8014c3160.png"> | <img width="1312" alt="Screen Shot 2023-04-05 at 4 29 04 PM" src="https://user-images.githubusercontent.com/387249/230236163-97723fc1-2731-4e11-b930-c242a63288c9.png"> | <img width="1312" alt="Screen Shot 2023-04-05 at 4 29 12 PM" src="https://user-images.githubusercontent.com/387249/230236166-9241f776-a7e9-407a-b660-3d402c2d595d.png"> | <img width="1312" alt="Screen Shot 2023-04-05 at 4 29 21 PM" src="https://user-images.githubusercontent.com/387249/230236169-472ce6a8-16b3-4be2-b6af-8f47334329d7.png"> | <img width="1312" alt="Screen Shot 2023-04-05 at 4 38 21 PM" src="https://user-images.githubusercontent.com/387249/230236901-25460550-064a-4ba0-9848-0d4b73dfea9e.png"> | <img width="1312" alt="Screen Shot 2023-04-05 at 4 38 38 PM" src="https://user-images.githubusercontent.com/387249/230236912-1b19d696-6aae-404f-99b9-30b5c694cabc.png">

</details>
