### ISSUE TITLE
Updating NFT details doesn't update the image and doesn't show image in details page

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#29199]
## Description 

Updating NFT details doesn't update the image and doesn't show image in details page

## Steps to Reproduce

   1. Add [this NFT](https://opensea.io/assets/ethereum/0x59468516a8259058bad1ca5f8f4bff190d30e066/2964) to portfolio
   2. Ensure it shows the correct image
   3. Edit the NFT and update the Token ID to `2587`
   4. Ensure it updates the image correctly
   5. Edit the NFT again and update the contract address to `0x282bdd42f4eb70e7a9d9f40c8fea0825b7f68c5d` and token id to `500` which doesn't have any [transactions](https://etherscan.io/token/0x282BDD42f4eb70e7A9D9F40c8fEA0825B7f68C5D?a=500)
   6. NFT Image continues to show for Invisible Friends added in steps 1 but the name shows for `V1 Cryptopunks (Wrapped)`
   7. Click on the NFT icon to load details page, shows error 

## Actual result:

https://user-images.githubusercontent.com/17010094/226532112-d0c4115c-b0d2-4214-a0c1-19f08dac35e6.mp4

## Expected result:
Show placeholder image instead of showing existing NFT image

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.50.94 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Most likely but not checked

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @muliswilliam @minkyeongshin @kleantzogu @jamesmudgett

**Comment by josheleonard** [comment]
It seems like token id `500` is not a valid punk. Looks like the token ids start at `1000` https://v1punks.io/token/ETHEREUM:0x282bdd42f4eb70e7a9d9f40c8fea0825b7f68c5d:500

**Comment by kjozwiak** [comment]
The above requires `1.69.123` or higher for `1.69.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.124 Chromium: 127.0.6533.73 (Official Build) beta (64-bit)
-- | --
Revision | dbc9035349f74e493f3293d93f4cbf35c597dfec
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from issue description
- Verified NFT details and image update when a different contract address is added to an existing NFT
- Encountered [#40028](https://github.com/brave/brave-browser/issues/40028)

https://github.com/user-attachments/assets/96ddb29f-390f-49ab-926f-42a0c34a027c
