### ISSUE TITLE
Add additional buckets to Ethereum provider P3A metric, add duplicate metric for Solana

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#29193]
Replace Ethereum provider question with another one including additional buckets. The buckets will indicate whether the current preferred provider overrides another installed provider, or if the native wallet provider is disabled.

What is your preferred Ethereum provider?
`Brave.Wallet.EthProvider.3`

0) None, because no wallet is setup
1) None, because the default provider setting is set to none
2) Brave Wallet (wallet is setup, definitely not overridden by an installed extension)
3) Brave Wallet (wallet is setup, an extension may *potentially* be installed but cannot override native provider)
4) Third-party extension (not overriding a setup Brave Wallet)
5) Third-party extension (overriding a setup Brave Wallet)

Add another question for Solana (`Brave.Wallet.SolProvider`)

**Comment by GeetaSarvadnya** [comment]
>Yeah, it does look like the dropdown changed... Unfortunately, i was not aware of this. I think I'll have to update the metrics at some point. Can you confirm that you see the answer 1 when the wallet is either not setup OR the default is set to "extensions (no fallback)"? If this is the case, i'll rename the answers for now and create an issue

@DJAndries Please see the responses below:

1. Looks like the dropdown items changed
2. when the wallet is not set up the metrics `Brave.Wallet.EthProvider.3` is NOT shown in the local state file
3. when the wallet is not set up and `Extensions (no fallback)` selected in the `web3` dropdown, the metrics `Brave.Wallet.EthProvider.3` is NOT shown in the local state file

![image](https://github.com/brave/brave-browser/assets/38657976/6314571f-8232-4977-b7cb-656809d44995)

Dropdown items are changed I am unable to test conditions  3 and 5  for the issue https://github.com/brave/brave-browser/issues/29193, Although conditions 2 and 4 are worked fine easily, could you let me know the steps to trigger these conditions?
