### ISSUE TITLE
Auto Contribute Failed popup does not close and is persistent reducing functionality

### ISSUE THREAD

**Issue by Programatic** [brave/brave-browser#2919]
## Description 

When opening the rewards tab, the "Your scheduled monthly payment for Auto-Contribute and ..." popup appears but when clicking on the x, will not disappear. It will also not disappear and blocks several other elements from appearing which makes it difficult to use the rewards. 

## Steps to Reproduce

   1. Fail to have funds for auto-contribute
   2. Try to use brave rewards
 

## Reproduces how often: 

Every time it fails to auto-contribute and try to open the brave rewards

## Brave version (brave://version info)

0.58.18 Chromium: 71.0.3578.98 (Official Build) (64-bit) 
Brave | 0.58.18 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
I am not sure. I haven't tested it

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 
N/A

**Comment by wizonesolutions** [comment]
I am encountering the same issue. Contribution is being retried at least once a second, and I currently have hundreds of "failed" notifications.

Pic: 
![image](https://user-images.githubusercontent.com/344116/69049806-00082400-0a01-11ea-9c00-7bcb5443cc05.png)

**Comment by NejcZdovc** [comment]
@Programatic still a problem?

@wizonesolutions we fixed this in https://github.com/brave/brave-core/pull/4132

**Comment by Programatic** [comment]
Nope, seems to be fixed. Thanks!
