### ISSUE TITLE
Hiding NFT from visible asset list continues to show the NFT in NFT tab

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#29200]
## Description 

Hiding NFT from visible asset list continues to show the NFT in NFT tab

## Steps to Reproduce

   1. Add an NFT to portfolio
   2. Go to visible asset list
   3. Uncheck the NFT from visible assets lists
   4. NFT is hidden in protfolio
   5. Go to NFT tab, NFT continues to show there

## Actual result:

https://user-images.githubusercontent.com/17010094/226536174-0061f8bd-2165-43d9-807d-696f428c1323.mp4

## Expected result:
Hide NFT in NFT tab as well? 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.50.94 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | `c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}`
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

As a consequence of this the NFT-IPFS banner is also not removed when an NFT is hidden from visible list

cc: @muliswilliam @cypt4 @jamesmudgett @minkyeongshin @kleantzogu

**Comment by josheleonard** [comment]
Closing: no longer valid since NFTs are no longer shown in the edit visible assets modal list
