### ISSUE TITLE
NFT pinning not started after wallet reset until browser is restarted

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#29207]
1) Add several pinnable NFTs
2) Reset wallet
3) Add them again and enable NFT pinning
4) Pinning won't start until browser is restarted

**Comment by kjozwiak** [comment]
The above requires `1.51.95` or higher for `1.51.x` verification 👍

**Comment by kjozwiak** [comment]
Closing as I believe this was fixed via https://github.com/brave/brave-core/pull/17983 and verified by @srirambv via https://github.com/brave/brave-core/pull/17983#issuecomment-1510952888. The above requires `1.51.95` or higher for `1.51.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.51.107 Chromium: 113.0.5672.63 (Official Build) (64-bit)
-- | --
Revision | `0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}`
OS | Windows 11 Version 22H2 (Build 22621.1555)

- Verified steps from [brave/brave-core#17983](https://github.com/brave/brave-core/pull/17983)
- Verified after resetting wallet newly added NFT in new wallet automatically starts pinning if the auto pin nft setting is enabled

https://user-images.githubusercontent.com/17010094/235194188-a4fcca86-6a81-4ce7-8b51-d2168be6c287.mp4
