### ISSUE TITLE
Onboarding/Info text should be more clear for non-English speakers to understand

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#2920]
Based on discussion from https://bravesoftware.slack.com/archives/C43LW5U2H/p1547067981091400, It would be good to revisit and rework on the wording used in onboarding screen and any other info shown on the browser. Certain things might not make immediate sense to a non-English speaker at first read. 

cc: @bbondy @jenn-rhim @brave/design  @kjozwiak @davidtemkin

**Comment by kjozwiak** [comment]
> Certain things might not make immediate sense to a non-English speaker at first read.

@srirambv do you have any specific examples? Some folks might not have access to the above Slack conversation. Mind breaking down the examples and why they might confuse none-english speakers?

**Comment by srirambv** [comment]
![image](https://user-images.githubusercontent.com/17010094/51099466-e30a2f80-17f6-11e9-9b1f-a9029dab89e0.png)

This was the feedback from non-English speaker user, who was on muon and migrated to the new bc but never used payments/rewards. Not a power user and neither a beginner. Feedback and follow up questions were 

#### "It sounds like I get rewarded (like loyalty points) for using Brave and I _need to give it away(loyalty points)_ to any content creators I like"
Follow up questions after reading were
1. Why should I watch ads to get paid if browser is supposed to block them?
2. When you say get paid can I get local currency if not then whats the point?
3. What does privacy-respecting ads mean. Isn't all ads bad?

From non-English speaker perspective its quite easy to lose interest if it doesn't make any sense. Using flashy words might make it look appealing to a native English speaker. And not just that, these onboarding text when translated to other languages might end up sounding a lot different than what it is in English.

**Comment by rebron** [comment]
@srirambv do you have additional/specific suggestions?

**Comment by bsclifton** [comment]
Closing as this doesn't have any specific examples - also, with https://github.com/brave/brave-browser/issues/9712 fixed folks in non-English locales should properly see welcome screen text in their native language
