### ISSUE TITLE
Use ENS domain button is disabled until a value is entered

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#29214]
## Description 

'Use ENS domain' button is disabled until a value is entered to send

## Steps to Reproduce
   1. Set `Resolve Ethereum Name Service (ENS) domain names` to `Enabled` in `brave://settings/web3`
   2. Set `Allow ENS offchain lookup.` to `Ask`
   3. Visit brave://wallet/send
   4. Select an Ethereum token to send
   5. Enter `offchainexample.eth`
   6. Observe button disabled
   7. Enter a value >0 in value field
   8. Observe button enable

## Actual result:

<img width="587" alt="Screenshot 2023-03-21 at 1 07 31 PM" src="https://user-images.githubusercontent.com/5314553/226690463-acb22981-b6c9-4b7e-beae-1bb408c00c39.png">

## Expected result:

'Use ENS domain' button is enabled without a value entered

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.51.103 Chromium: 112.0.5615.165 (Official Build) beta (64-bit) 
-- | --
Revision | `c262f36e6b1d711ee42d4fbe1343b49960593f18-refs/branch-heads/5615@{#1297}`
OS | Linux

- Verified steps from [brave/brave-core#17702](https://github.com/brave/brave-core/pull/17702)
- Verified ENS domain button is enabled and able to resolve address without having to enter a send value

https://user-images.githubusercontent.com/17010094/234494568-251d6bcc-b36a-46c2-b95c-5161200df595.mp4


---------------------

**Verification passed on**

Brave | 1.51.103 Chromium: 112.0.5615.165 (Official Build) beta (64-bit)
-- | --
Revision | `c262f36e6b1d711ee42d4fbe1343b49960593f18-refs/branch-heads/5615@{#1297}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from [brave/brave-core#17702](https://github.com/brave/brave-core/pull/17702)
- Verified ENS domain button is enabled and able to resolve address without having to enter a send value

https://user-images.githubusercontent.com/17010094/234494378-cea62f8c-4720-4a16-b6d1-93cf938a8650.mp4


---------------------

**Verification passed on**

Brave | 1.51.103 Chromium: 112.0.5615.165 (Official Build) beta (arm64)
-- | --
Revision | `c262f36e6b1d711ee42d4fbe1343b49960593f18-refs/branch-heads/5615@{#1297}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#17702](https://github.com/brave/brave-core/pull/17702)
- Verified ENS domain button is enabled and able to resolve address without having to enter a send value

https://user-images.githubusercontent.com/17010094/234494843-8b4ee9e6-0275-45c3-bac3-2a3e0d7b24ab.mov
