### ISSUE TITLE
Wrong translation for copy clean link in Polish locale

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#29210]
Current translation for `Copy clean link`: `Skopiuj wyczyszczone lacze`
`Copy link` translation: `Kopiuj adres linku` 
Both should be similar

## Steps to Reproduce

1. Open context menu on a link on a page

## Actual result:

 translation for `Copy clean link`: `Skopiuj wyczyszczone lacze`

## Expected result:
 translation for `Copy clean link`: `Kopiuj czysty adres linku` or `Kopiuj wyczyszczony adres linku`

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.49.126 Chromium: 111.0.5563.64 (Official Build) (64-bit)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | Ubuntu 18.04 LTS

cc @rebron @mkarolin

**Comment by kjozwiak** [comment]
The above requires `1.50.113` or higher for `1.50.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.50.113 Chromium: 112.0.5615.49 (Oficjalna wersja) (64-bitowa)
-- | --
Wersja | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
System operacyjny | Windows 10 Version 21H2 (Build 19044.2728)

```
- Verified the description from the issue and ensured that the string copy clean link is translated in polish locale as `Kopiuj wyczyszczony adres linku`

![image](https://user-images.githubusercontent.com/38657976/229845591-fd991536-20fe-4617-b435-db6391dbd661.png)
