### ISSUE TITLE
Do not allow selecting assets in Buy/Sell that belong to hidden networks

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#29216]
Unless there's a good reason for it, if a network is hidden under Web3 Settings it should not be visible in Buy/Sell flow for selection. Additionally, any asset belonging to a hidden network should not be part of the buy/sell options.

https://user-images.githubusercontent.com/3684187/226711723-9b511f9d-6185-406a-9c9b-fd4352958e73.mov

cc: @muliswilliam

**Comment by Douglashdaniel** [comment]
This was intentional to allow users to still be able to `Discover/Buy` tokens when coming from the `Market` tab. https://github.com/brave/brave-browser/issues/28009

**Comment by Douglashdaniel** [comment]
Closing as `invalid` per https://github.com/brave/brave-browser/issues/28009
