### ISSUE TITLE
Use ETH icons for EVM networks with ETH as the Native Asset

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#29225]
## Description 

Use ETH icon for EVM networks with ETH as the Native Asset

Example `Aurora Mainnet` and `Optimism`

![Screenshot 35](https://user-images.githubusercontent.com/40611140/226802226-d6195adb-056a-4c5f-9bb7-60bf31c2d1b7.png)

**Comment by srirambv** [comment]
**Verification passed on **

Brave | 1.51.79 Chromium: 112.0.5615.49 (Official Build) beta (64-bit) 
-- | --
Revision | `bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}`
OS | Linux

- Verified steps from [brave/brave-core#17716](https://github.com/brave/brave-core/pull/17716)
- Verified ETH icon is shown for native asset for Aurora and Optimism EVM's with network icon 
- Verified selecting the native asset shows the correct network name 

https://user-images.githubusercontent.com/17010094/230834419-6f90a9cc-70ac-423f-ad95-78cbb6ec91f6.mp4


---------------------

**Verification passed on**

Brave | 1.51.79 Chromium: 112.0.5615.49 (Official Build) beta (64-bit)
-- | --
Revision | `bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from [brave/brave-core#17716](https://github.com/brave/brave-core/pull/17716)
- Verified ETH icon is shown for native asset for Aurora and Optimism EVM's with network icon 
- Verified selecting the native asset shows the correct network name 

https://user-images.githubusercontent.com/17010094/230832412-2e088132-beb5-4102-a9aa-e1ccf069b484.mp4

---------------------

**Verification passed on**

Brave | 1.51.79 Chromium: 112.0.5615.49 (Official Build) beta (arm64)
-- | --
Revision | `bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#17716](https://github.com/brave/brave-core/pull/17716)
- Verified ETH icon is shown for native asset for Aurora and Optimism EVM's with network icon 
- Verified selecting the native asset shows the correct network name 

https://user-images.githubusercontent.com/17010094/230832677-1c22f74e-a46e-486f-8392-649a35c7bdc3.mov
