### ISSUE TITLE
Ads box should respect rewards status

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#2922]
## Description 

When you disable rewards, ads box should be disabled as well.

Current:
![image](https://user-images.githubusercontent.com/9574457/51031171-06856e00-159c-11e9-97be-0610fd2440fa.png)

Should be like auto contribute

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.60.28 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/1297
![screen shot 2019-02-15 at 3 46 11 pm](https://user-images.githubusercontent.com/28145373/52883453-f6335680-3138-11e9-8b42-abbd3d4e1cbb.png)
