### ISSUE TITLE
Add Swap to the FAB button in wallet to open a tab to brave://wallet/swap

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#29223]
Update with release of new swap webUI brave://wallet/swap

**Comment by kjozwiak** [comment]
Closing as this was fixed via https://github.com/brave/brave-core/pull/17947 but wasn't closed automatically due to `Resolve` being used incorrectly via https://github.com/brave/brave-core/pull/17947#issue-1657228685.

**Comment by kjozwiak** [comment]
The above requires `1.50.120` or higher for `1.50.x` verification 👍

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/29221#issuecomment-1513017428
