### ISSUE TITLE
Caption font-color should be white in dark mode 

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#29224]
## Description 

In Speedreader dark mode, the caption for images should be white. 

## Steps to Reproduce

   1. Use nightly or 1.51.51 and higher.
   2. Go to a page that can distilled into speedreader mode e.g. `https://www.sfchronicle.com/weather/article/storm-center-eye-satellite-17852701.php`
   3. Notice caption font color is dark and should be white.

## Actual result:

<img width="698" alt="Screenshot 2023-03-21 at 8 07 31 PM" src="https://user-images.githubusercontent.com/5951041/226792220-ac3b9484-a7d4-4743-ae8a-96cc33172937.png">

## Expected result:
See str.

## Reproduces how often: 

Easily.

## Brave version (brave://version info)

1.51.51 and higher

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by aguscruiz** [comment]
We have the right styles for that here
https://www.figma.com/file/YHMNRL2XpZDOUe6n1Dw6K1/Reader-mode?node-id=2180%3A60385&t=SF0ZFKGMyK0kyzgU-1

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.51.76 Chromium: 112.0.5615.49 (Official Build) beta (x86_64)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | macOS Version 13.4 (Build 22F5027f)

### Steps:
1. installed `1.51.76`
2. launched Brave
3. loaded `https://www.sfchronicle.com/weather/article/storm-center-eye-satellite-17852701.php`
4. enabled Speedreader mode
5. examined caption text + color
6. switched to `Dark` mode
7. examined caption text + color
8. also compared to `1.50.130`

#### Confirmed the caption text in Speedreader is gray and matches the Figma spec

`1.51.76`

`Figma spec` | `Dark` | `Light`
--------------|--------|-------
<img width="1496" alt="Screenshot 2023-04-03 at 2 25 24 PM" src="https://user-images.githubusercontent.com/387249/229631834-6ad4196e-3473-4c52-aaaf-e8115cbac4a4.png"> | <img width="1496" alt="Screenshot 2023-04-03 at 2 33 43 PM" src="https://user-images.githubusercontent.com/387249/229632902-26083827-07fa-49a9-9435-a019b7e64611.png"> | <img width="1496" alt="Screenshot 2023-04-03 at 2 32 40 PM" src="https://user-images.githubusercontent.com/387249/229633012-bafbc382-5d82-4fcd-92f9-1746453f7cb7.png">

`1.49.130`

`Dark` | `Light`
--------|------
<img width="1389" alt="Screenshot 2023-04-03 at 2 35 29 PM" src="https://user-images.githubusercontent.com/387249/229633183-e801a1ee-981b-4d2f-b3cf-f378d77a0a5b.png"> | <img width="1389" alt="Screenshot 2023-04-03 at 2 33 25 PM" src="https://user-images.githubusercontent.com/387249/229633178-4f56f8ec-125d-4e61-8a92-d08100c50ff1.png">
