### ISSUE TITLE
NFT pinning optimisation

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#29230]
Currently we pin root CID for metadata and url which may include unnecessary data.
For example pinning of ipfs://bafy/1.png leads to pinning of ipfs://bafy1.
We should pin exact file recursively and path to the file non-recursively.

**Comment by srirambv** [comment]
**Verification passed on **

Brave | 1.51.80 Chromium: 112.0.5615.49 (Official Build) beta (64-bit) 
-- | --
Revision | `bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}`
OS | Linux

- Verified steps from [brave/brave-core#17742](https://github.com/brave/brave-core/pull/17742)
- Verified NFT folder metadata is pinned directly
- Verified NFT metadata is pinned recursively

https://user-images.githubusercontent.com/17010094/230862310-07ca0109-4613-47a2-99d9-8ca24a51fff3.mp4

---------------------

**Verification passed on**

Brave | 1.51.80 Chromium: 112.0.5615.49 (Official Build) beta (64-bit)
-- | --
Revision | `bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from [brave/brave-core#17742](https://github.com/brave/brave-core/pull/17742)
- Verified NFT folder metadata is pinned directly
- Verified NFT metadata is pinned recursively

https://user-images.githubusercontent.com/17010094/230857335-6368256a-7061-4469-9b7b-f122ff1d3680.mp4

---------------------

**Verification passed on**

Brave | 1.51.80 Chromium: 112.0.5615.49 (Official Build) beta (arm64)
-- | --
Revision | `bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#17742](https://github.com/brave/brave-core/pull/17742)
- Verified NFT folder metadata is pinned directly
- Verified NFT metadata is pinned recursively

https://user-images.githubusercontent.com/17010094/230861333-cafcc650-835b-46ee-b96b-d8e62437eb8e.mov
