### ISSUE TITLE
NTP quick actions (Customize, Settings, etc) are not placed on NTP SI appropriately when the clock is removed from view - Follow up to 28736

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#29246]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/28736.

If you remove the clock from view on NTP, when an NTP SI is displayed the actions normally in the lower right corner (Customize, Bookmarks, etc) are now displayed about halfway up the NTP. 

Furthermore, if the widgets aren't displayed either, these actions are "behind" the clickable NTP SI area, so clicking on them results in you visiting the area the URL is set to.

## Steps to Reproduce

   1. Remove all items from view on NTP
   3. Navigate to NTP SI if not already on one
   4. See Customize, Settings, etc about halfway up the page
   5. Try to click on Customize to fix clock view, get directed to clickable area's URL
   6. If you go to regular NTP, Customize, etc display appropriately
   7. Re-enable cards/widgets only (not clock)
   8. Nav to NTP SI again
   9. Customize, etc are still improperly placed.

## Actual result:

Nothing on NTP SI | Cards/Widgets only | Clock only | Regular NTP
---- | ---- | --- | ----
<img width="1610" alt="1" src="https://user-images.githubusercontent.com/28145373/226956202-e135ac9b-2f0d-4581-bc6f-64841afe74ae.png"> | <img width="1179" alt="2" src="https://user-images.githubusercontent.com/28145373/226956205-713edcc3-0eb0-405d-b1a6-0f234ed62fe9.png"> | <img width="1610" alt="3" src="https://user-images.githubusercontent.com/28145373/226956208-5a00fc0e-39fd-4399-85aa-76ef91efbc9c.png"> | <img width="1184" alt="4" src="https://user-images.githubusercontent.com/28145373/226956213-6a27496d-fcda-4ea5-a125-0ffe51b60ab7.png">

## Expected result:

Customize, etc should always be placed appropriately on NTP SI even if elements like clock are not displayed

This is from 1.49.120:

<img width="1470" alt="Screen Shot 2023-03-22 at 11 38 54 AM" src="https://user-images.githubusercontent.com/28145373/226957809-1edefaec-2136-4b5d-8655-15cfc59ee48f.png">

## Reproduces how often: 

easily

## Brave version (brave://version info)

```
Brave | 1.49.128 Chromium: 111.0.5563.110 (Official Build) (x86_64)
-- | --
Revision | 3da375c9e9e5ad9b556af5df708a6e6c01d8cfb1-refs/branch-heads/5563@{#1202}
OS | macOS Version 12.6.3 (Build 21G419)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 1.49.128 yes, 1.49.120 n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? unsure, probably yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron @brave/qa-team

**Comment by kjozwiak** [comment]
The above requires `1.50.107` or higher for `1.50.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.50.110 Chromium: 112.0.5615.49 (Official Build) (x86_64)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | macOS Version 12.6.4 (Build 21G526)
```
