### ISSUE TITLE
Wallet on ramp providers for native assets

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#29248]
## Description 
We currently allow to buy native network assets even though on ramp provider doesn't support it.

## Steps to reproduce 

   1. Set a locale to US so Sardine provider could be seen.
   2. Create a wallet and go to a Buy flow.
   3. Pick a `Binance Smart Chain Mainnet` and `BNB` as an asset to buy.
   4. Press Buy button.

## Actual result 
Observe `Ramp.Network`, `Sardine` and `Transak` there.
![Screenshot_20230321_144408](https://user-images.githubusercontent.com/12011303/226996626-5c5196bc-cf44-4826-b308-5657640a42a7.png)

## Expected result
Only `Ramp.Network` and `Transak` should be there as you can't buy `BNB` via `Sardine`.

## Issue reproduces how often 
Always

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
1.51.x

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.50.106` or higher for `1.50.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.50.107 x64 beta build
- Verified steps from issue description
- Verified `Sardine` is not shown for `Binance Smart Chain` and only shows `Ramp.network` and `Transak`

Oppo Reno 5 (Android 13) | Lenovo Tab (Android 12)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/228425269-1f1f567e-dd24-4870-937e-10b85efe0d3a.mp4> | <video src=https://user-images.githubusercontent.com/17010094/228425954-bde88218-ce3f-4308-83f1-b66f0cc27b6d.mp4>
