### ISSUE TITLE
UI: selected groups in tab bar stick with the group title

### ISSUE THREAD

**Issue by choyshaowei** [brave/brave-browser#29259]
## Description 
UI issues on the selected groups tabs are too close with the group title, check the screenshoots below. 

## Steps to Reproduce
   1. Create multiple group
   2. Add tabs into groups
   3. Click the tab next to the group title

## Actual result:

![image](https://user-images.githubusercontent.com/33794625/227089361-6e9cfba7-5614-4d8a-ac13-6e6f7f55176d.png)

## Expected result:
Few pixels away from title, something like
![image](https://user-images.githubusercontent.com/33794625/227089509-2582de60-3c9f-44e8-a0e1-4846971a1f35.png)

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
1.49.120

## Version/Channel Information:
Current release channel

- Can you reproduce this issue with the current release? 
Yes

**Comment by peize-li123** [comment]
Working on this!

**Comment by peize-li123** [comment]
Hi, I found the file to fix this bug but it's inside the chrome folder that was generated from npm init. I wasn't able to find the same file in brave-core folder. Does anyone know how I can submit my code change in this situation?
