### ISSUE TITLE
Users can't deploy contract using Brave

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#29252]
Remix GitHub issue: https://github.com/ethereum/remix-project/issues/3369
Community: https://community.brave.com/t/internal-json-rpc-error-when-using-brave-wallet-to-deploy-contracts/478192

**Comment by kjozwiak** [comment]
The above requires `1.50.107` or higher for `1.50.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.50.108 Chromium: 112.0.5615.39 (Official Build) (64-bit)
-- | --
Revision | `a0e7b9718a92bcd1cf33b7c95316caff3fc20714-refs/branch-heads/5615@{#753}`
OS | Linux

- Verified steps from [brave/brave-core#17715](https://github.com/brave/brave-core/pull/17715)
- Verified when on Mainnet, deploying contract shows the transaction confirmation screen and doesn't error out
- Verified when on Goerli Testnet, deploying contract shows the transaction confirmation screen and able to successfully submit the transaction

https://user-images.githubusercontent.com/17010094/228481954-58d46ce4-da5e-402b-a32b-a9bf2f7f92eb.mp4
