### ISSUE TITLE
Use WireGuard for VPN instead of System API

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#29253]
## Description 
The current implementation of VPN on Desktop works on macOS and Windows using OS specific code. This has some limitations which don't offer the best customer experience. Here are some examples:
1. Folks that get disconnected (ex: coming back after computer was asleep) don't get reconnected automatically
2. Windows in particular has some bugs - some give a horrible user experience. For a detailed example [see our support article](https://support.brave.com/hc/en-us/articles/13653403930637-Cannot-connect-to-BraveVPN-the-parameter-is-incorrect-Error-87-)
3. There is no implementation on Linux

Android is already using WireGuard and iOS is using the Guardian Connect API which we can change to be using WireGuard. We should look at getting Desktop moved over too

Some requirements:
- Config should be stored outside of Brave
- Folks should be able to connect to VPN outside of Brave
- We may need to install binaries depending on OS support

Additional requirements(added by @spylogsster )
- Fallback to IKEv2 VPN for win

Spec: https://docs.google.com/document/d/18HMN-G4NAxrdaihC-ybl9-blhCqT7Vca-E1TdK2zJls/edit?usp=sharing

**Comment by bsclifton** [comment]
cc: @spylogsster who has done some research already

**Comment by thypon** [comment]
We should leave the WireGuard binary out of the main bundle, since it may be marked by AVs

**Comment by spylogsster** [comment]
Refactoring for BraveVpn connection to add Wireguard support https://github.com/brave/brave-browser/issues/30024

**Comment by spylogsster** [comment]
Fallback from Wireguard to IKEv2 https://github.com/brave/brave-browser/issues/30666
Add System Tray icon UI for BraveVpnWireguardService  https://github.com/brave/brave-browser/issues/30708

**Comment by spylogsster** [comment]
OSX part https://github.com/brave/brave-browser/issues/32612

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/32612
