### ISSUE TITLE
[Android] YouTube Auto Pause Blocker

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#29251]
## Description
Investigate possibility to remove the "video paused, continue watching?" notice that appears on youtube.com after playing a video for some time. There are a few chrome extensions that can do this, so it seems to be possible.

e.g. YoutubeNonStop
- https://chrome.google.com/webstore/detail/youtube-nonstop/nlkaejimjacpillmajjnopmpbkbnocid?hl=en
- https://github.com/lawfx/YoutubeNonStop

## Why
We see a fairly large number of reviews complaining about the auto pause:

- https://appfigures.com/reviews/266342430751LK7hUwp4BVdanw8PAXuSB4Q?lang=en
- https://appfigures.com/reviews/266342430751LClAfcaoGgDvqNhxUZuo9eA?lang=en
- https://appfigures.com/reviews/266342430751LQDHda6urwl2HxFv587ICwQ?lang=en
- https://appfigures.com/reviews/266342430751L2yEK8l_t2iPl2uwR7UWehg?lang=en

**Comment by anthonypkeane** [comment]
I think we should have a setting for it too Tim is Ryan can figure it out

**Comment by deeppandya** [comment]
@timchilds @anthonypkeane we should prioritize this issue and include the option in new YT section with other youtube improvements.

**Comment by bridiver** [comment]
I think this falls under general blocking/webcompat cc @ShivanKaul

**Comment by ShivanKaul** [comment]
If we're planning to ship adblock filters for a new feature or bundle a new list, please check with the privacy team first.

**Comment by ryanbr** [comment]
Check out enabling Experimental list in brave://settings/shields/filters Enable that. Its something I want to roll out at some stage, website detection of the user.
