### ISSUE TITLE
Network Icons are getting clipped on Send page

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#29267]
## Description 

The network icons are getting clipped in the `Select Token to Send` modal.

## Actual result:

![Screenshot 39](https://user-images.githubusercontent.com/40611140/227234608-a0ac8b2c-a2d0-43f9-84b4-dc94a6828a95.png)

## Expected result:
Should not be getting clipped.

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.51.103 Chromium: 112.0.5615.165 (Official Build) beta (64-bit) 
-- | --
Revision | `c262f36e6b1d711ee42d4fbe1343b49960593f18-refs/branch-heads/5615@{#1297}`
OS | Linux

- Verified steps from [brave/brave-core#17736](https://github.com/brave/brave-core/pull/17736)
- Verified network icons are not clipped on Send page
![image](https://user-images.githubusercontent.com/17010094/234481714-8ec731c7-344a-4818-9ef9-ea4a9e66f411.png)

---------------------

**Verification passed on**

Brave | 1.51.103 Chromium: 112.0.5615.165 (Official Build) beta (64-bit)
-- | --
Revision | `c262f36e6b1d711ee42d4fbe1343b49960593f18-refs/branch-heads/5615@{#1297}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from [brave/brave-core#17736](https://github.com/brave/brave-core/pull/17736)
- Verified network icons are not clipped on Send page
![brave_S5H391U7kL](https://user-images.githubusercontent.com/17010094/234481065-cc5ffe70-ea5f-4f99-8e43-672a3ca4847a.png)

---------------------

**Verification passed on**

Brave | 1.51.103 Chromium: 112.0.5615.165 (Official Build) beta (arm64)
-- | --
Revision | `c262f36e6b1d711ee42d4fbe1343b49960593f18-refs/branch-heads/5615@{#1297}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#17736](https://github.com/brave/brave-core/pull/17736)
- Verified network icons are not clipped on Send page
![image](https://user-images.githubusercontent.com/17010094/234481391-9eea7d44-8376-478f-922b-d92ccc4a6c3a.png)
