### ISSUE TITLE
Wallet Activity is not showing the right message for active accounts with transactions

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#29272]
## Description 

Right now, when you go to the activity tab after you open the wallet, it says you have no transactions made even you have. This is a bug

## Steps to Reproduce

   1. 
   2. 
   3. 

## Actual result:

<img width="1281" alt="Screenshot 2023-03-23 at 17 54 44" src="https://user-images.githubusercontent.com/12224304/227278093-d67ea3eb-068c-4720-a353-5510945e75a8.png">

## Expected result:
<img width="1230" alt="Screenshot 2023-03-23 at 17 55 41" src="https://user-images.githubusercontent.com/12224304/227278122-480d9d67-0dc2-4542-a507-bf6e46345371.png">

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.52.102 Chromium: 113.0.5672.126 (Official Build) beta (64-bit)
-- | --
Revision | `c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}`
OS | Windows 11 Version 22H2 (Build 22621.1702)

- Verified steps from [brave/brave-core#18161](https://github.com/brave/brave-core/pull/18161)
- Verified activity tab shows all transactions
- Encountered [#30454](https://github.com/brave/brave-browser/issues/30454)
