### ISSUE TITLE
Reduce Android apk by optimizing images

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#29279]
Some images might be optimized but format will be kept.
For some images it might be worth to be converted from png to svg.

**Comment by kjozwiak** [comment]
@AlexeyBarabash looking at https://github.com/brave/brave-core/pull/17655#issuecomment-1476283069, looks like the example screenshots are basically showing the onboarding. Was there anything else that was edited re: image optimizations? Or is it basically just onboarding? Looks like https://github.com/brave/brave-core/pull/17655#issuecomment-1478503102 mentions `Sync Button`. Should the sync section be checked as well? Adding `QA/Blocked` till we know more.

**Comment by AlexeyBarabash** [comment]
@kjozwiak yes, onboarding is the screen with the most changes.

Other screens are wallet and sync.

**Comment by kjozwiak** [comment]
@srirambv keep an eye on Brave Wallet in term of images appearing correctly while you're running through verifications. We run through onboarding basically every time we install `Brave` while running through verifications. So assuming we'll be able to spot issues if there's any pretty quickly in that part of the code. With `Sync`, we'll run through the full manual passes so we'll do a pass on `Sync` and keep an eye on images being loaded/rendered incorrectly etc..

CCing @Uni-verse @vlad-hoff

**Comment by Uni-verse** [comment]
Verified on `Samsung GS 21 5G` using app version: 

```
Brave	1.51.109 Chromium: 113.0.5672.63 (Official Build) (64-bit) 
Revision	0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

_Onboarding Screens_

- Verified onboarding screens are rendered correctly and layout is not broken on 1.51.x and user is able to complete onboarding successfully.

<table><tr><td>1.50</td><td>1.51</td></tr>

<tr><td>

https://user-images.githubusercontent.com/17885425/235757874-00042b6c-9fdc-4d05-b80e-d99f50d20757.mp4

</td><td>

https://user-images.githubusercontent.com/17885425/235757740-be549dcb-09f3-4286-b122-127094739f03.mp4

</td></tr></table>

_Sync Flow_

- Verified sync chain flow screens when joining a sync chain via scanning code/code words and also starting standalone sync chain on device

Example | Example | Example
-|-|-
![screenshot-1683049528708](https://user-images.githubusercontent.com/17885425/235761039-790c9314-6f82-4a2b-a7f8-ce4df6237034.png) | ![screenshot-1683049542648](https://user-images.githubusercontent.com/17885425/235761043-938fec9f-46bb-49b9-b7c1-0ef2387e3f87.png) | ![screenshot-1683049636580](https://user-images.githubusercontent.com/17885425/235761045-0f526fb1-80e7-457d-85f8-6cae50c61a9b.png)

_Wallet_

- Verified creating wallet screens are displayed correctly and layout is correct. 
- Verified some settings/navigation in Brave Wallet.

Example | Example | Example | Example | Example
-|-|-|-|-
![screenshot-1683051452124](https://user-images.githubusercontent.com/17885425/235762595-4c92b6f6-f2be-4f48-8df0-dda6f8c9ce00.png) | ![screenshot-1683054413029](https://user-images.githubusercontent.com/17885425/235762597-b6522f51-e58f-49d8-9c4a-ff4dfd6ab5e8.png) | ![screenshot-1683054432597](https://user-images.githubusercontent.com/17885425/235762598-2ca49ecd-eb72-4096-a438-a90d379ed530.png) | ![screenshot-1683054446985](https://user-images.githubusercontent.com/17885425/235762599-be640975-65f7-495a-b2ef-e8207ff3a8fd.png) | ![screenshot-1683054463068](https://user-images.githubusercontent.com/17885425/235762601-36c78de1-5772-45b4-9c51-4ed2e10b970b.png)

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy Tab S7` using version:

```
Brave	1.51.109 Chromium: 113.0.5672.63 (Official Build) (64-bit) 
Revision	0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

_Onboarding_

- Verified onboarding screens are rendered correctly and layout is not broken 

https://user-images.githubusercontent.com/17885425/235766027-d5592d06-29f7-4bc1-82d7-8190b8c9100a.mp4

_Sync_

- Verified sync chain flow screens when joining a sync chain via scanning code/code words and also starting standalone sync chain on device

Example | Example | Example | Example | Example
-|-|-|-|-
![screenshot-1683055074663](https://user-images.githubusercontent.com/17885425/235766305-891bc916-f38e-4ab9-b891-5ec7afcffa60.png) | ![screenshot-1683055085415](https://user-images.githubusercontent.com/17885425/235766307-84fe4247-b6c7-4607-8b7c-52d9b85cc86d.png) | ![screenshot-1683055125563](https://user-images.githubusercontent.com/17885425/235766309-e212fade-b1b0-4e4d-b2cd-621a3b41803f.png) | ![screenshot-1683055147804](https://user-images.githubusercontent.com/17885425/235766314-c874f4b1-30ce-44bf-9e0f-13f5b1c88700.png) | ![screenshot-1683055161376](https://user-images.githubusercontent.com/17885425/235766316-55f3d585-7446-46ad-b326-6b2e11e38491.png)

_Brave Wallet_

- Spot checked images on wallet screens that they are not broken.
- Verified user is able to create new wallet and connect to dApps.

Example | Example | Example | Example | Example | Example | Example
-|-|-|-|-|-|-
![screenshot-1683055396520](https://user-images.githubusercontent.com/17885425/235766734-2ce2b74d-3c67-4197-8139-61b53faadce7.png) | ![screenshot-1683055402123](https://user-images.githubusercontent.com/17885425/235766736-37d0128f-870b-4ba0-97a5-6f8f557d389f.png) | ![screenshot-1683055420750](https://user-images.githubusercontent.com/17885425/235766737-0b5efe32-e8d3-4ee1-b60b-4e64e37217df.png) | ![screenshot-1683055455348](https://user-images.githubusercontent.com/17885425/235766738-5980915e-9f6f-463d-a4a6-c8e2db26fad5.png) | ![screenshot-1683055498605](https://user-images.githubusercontent.com/17885425/235766741-1181c79d-0e0d-48d5-b86a-34c13bf4896e.png) | ![screenshot-1683055520735](https://user-images.githubusercontent.com/17885425/235766744-f8d9f40a-41cb-4649-8623-129abeb2c755.png) | ![screenshot-1683055526756](https://user-images.githubusercontent.com/17885425/235766747-6b8d8051-aeb0-4719-8584-7bf1a75855a7.png)

**Comment by Uni-verse** [comment]
Verified on `Google Pixel 5 x86` running `Android 8` using version: 

```
Brave	1.51.109 Chromium: 113.0.5672.63 (Official Build) (32-bit) 
Revision	0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}
OS	Android 8.0.0; Build/OSR1.180418.026; 26; REL
```
_Onboarding_

- Verified onboarding screens are rendered correctly and layout is not broken 

Example | Example
-|-
![Screenshot 2023-05-02 at 3 47 23 PM](https://user-images.githubusercontent.com/17885425/235799331-b98b02a8-78f0-4bc5-9855-737a7c8d44dc.png) | ![Screenshot 2023-05-02 at 3 47 43 PM](https://user-images.githubusercontent.com/17885425/235799334-51e3b6a3-617c-4512-8d07-01709ee9318c.png)


_Sync_

- Verified sync chain flow screens when joining a sync chain via scanning code/code words and also starting standalone sync chain on device

Example | Example | Example
-|-|-
![Screenshot 2023-05-02 at 6 24 22 PM](https://user-images.githubusercontent.com/17885425/235799377-f1eedc40-90b5-4e49-be81-3cf113248290.png) | ![Screenshot 2023-05-02 at 6 24 33 PM](https://user-images.githubusercontent.com/17885425/235799378-34db88d7-6786-41ed-ba89-f37d473980c3.png) | ![Screenshot 2023-05-02 at 6 24 57 PM](https://user-images.githubusercontent.com/17885425/235799380-a9a2c705-b8f5-4332-b5b1-327111e8c6b6.png)


_Brave Wallet_

- Spot checked images on wallet screens that they are not broken.
- Verified user is able to create new wallet and connect to dApps.

Example | Example | Example | Example
-|-|-|-
![Screenshot 2023-05-02 at 6 25 29 PM](https://user-images.githubusercontent.com/17885425/235799464-87f1d393-941f-4168-a6ec-a64581973b9a.png) | ![Screenshot 2023-05-02 at 6 26 10 PM](https://user-images.githubusercontent.com/17885425/235799465-4d5383f9-128f-4255-a1e2-64680d8756a7.png) | ![Screenshot 2023-05-02 at 6 26 31 PM](https://user-images.githubusercontent.com/17885425/235799469-90941419-6195-49d4-a432-ff3f13a40978.png) | ![Screenshot 2023-05-02 at 6 26 52 PM](https://user-images.githubusercontent.com/17885425/235799472-df4cbbf4-3980-4072-a7c0-8b0b189428f0.png)
