### ISSUE TITLE
Remove the chrome repository erroneously added by brave-browser on Linux

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#2927]
As a follow-up to #1084, we should clean up existing installations that have had the Google repo added automatically by the cronjob.

Files to delete (if they exist):

- `/etc/default/brave-browser`
- `/etc/apt/sources.list.d/brave-browser.list` or `/etc/yum.repos.d/brave-browser.repo`

And then there's the Google repository signing key. For that, we need to first check whether or not chrome is installed on the machine. To do this, we could look for one of these files:

- `/etc/cron.daily/google-chrome`
- `/etc/default/google-chrome` 
- `/etc/apt/sources.list.d/google-chrome.list` or `/etc/yum.repos.d/google-chrome.repo`

or their equivalents for beta:

- `/etc/cron.daily/google-chrome-beta`
- `/etc/default/google-chrome-beta`
- `/etc/yum.repos.d/google-chrome-beta.repo`

or dev:

- `/etc/cron.daily/google-chrome-unstable`
- `/etc/default/google-chrome-unstable`
- `/etc/yum.repos.d/google-chrome-unstable.repo`-

If there are no traces of Chrome, then we can remove the Google package signing key:

    apt-key del D38B4796

or

    rpm -e gpg-pubkey-7fac5991-4615767f
    rpm -e gpg-pubkey-d38b4796-570c8cd3

**Comment by fmarier** [comment]
Note: the google-chrome packages don't remove their signing keys when the packages are `apt purge`d.

**Comment by rebron** [comment]
@fmarier QA needed?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.63.46 Chromium: 74.0.3729.91 (Official Build) (64-bit)
-- | --
Revision | 03844ed83e02b8add3f4b9cb859a7108d55b2e4d-refs/branch-heads/3729@{#860}
OS | Linux

* Verified installing `0.58.16` added `brave-browser.list` file in `etc/apt/sources.list.d/` 
* Verified upgrading to current release build via apt created `brave-browser-release-bionic.list` file along with `brave-browser.list`
* Verified upgrading to `0.63.46` removed `brave-browser.list` file from `etc/apt/sources.list.d/`
