### ISSUE TITLE
Default-browser checkmarks are missing for Chrome Dev and Chrome Beta during import

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#29275]
## Description 

Default-browser checkmarks are missing for `Google Chrome Dev` and `Google Chrome Beta` during import

NOTE: Spun off from https://github.com/brave/brave-browser/issues/29095, which was spun off from https://github.com/brave/brave-browser/issues/28717

## Steps to Reproduce

1. install `Google Chrome Dev` and `Google Chrome Beta`
2. launch and populate them with bookmarks, browsing session/history, etc.
3. set one of the above as the default browser in `Apple menu` --> `System Preferences` --> `General`
4. install Brave `1.51.56`
5. launch it
6. click `Skip` on the 1st page
7. on the next page, look for `Google Chrome Dev` or `Google Chrome Beta`
8. see if it has a checkmark

## Actual result:

Missing its checkmark

<img width="1198" alt="225424570-5ae1777f-f2e9-4915-af73-fc7ad2a6e2e2" src="https://user-images.githubusercontent.com/387249/227291232-092a9f61-5a84-41af-909c-0155e6eec341.png">

## Expected result:

Has a checkmark, indicating it's the currently default browser

`Google Chrome Dev` | `Google Chrome Beta`
---------|---------
<img width="1920" alt="Screen Shot 2023-03-23 at 10 20 13 AM" src="https://user-images.githubusercontent.com/387249/227291862-5b57c1ca-607c-4c0e-83e5-a69581365216.png"> | <img width="1919" alt="Screen Shot 2023-03-23 at 10 23 55 AM" src="https://user-images.githubusercontent.com/387249/227291874-a2135027-f974-44eb-aff2-37a968dded7d.png">

`Google Chrome Dev`
```
[29519:259:0323/104128.106481:ERROR:welcome_dom_handler.cc(131)] OnGetDefaultBrowsername:Google Chrome Dev.app
[29519:259:0323/104128.106528:ERROR:welcome_dom_handler.cc(138)] OnGetDefaultBrowserbrowser_name:Google Chrome Dev
[29519:259:0323/104128.106547:ERROR:welcome_dom_handler.cc(141)] OnGetDefaultBrowserdefault_browser_name_:Google Chrome Dev
```

`Google Chrome Beta`
```
[29404:259:0323/102332.606932:ERROR:welcome_dom_handler.cc(131)] OnGetDefaultBrowsername:Google Chrome Beta.app
[29404:259:0323/102332.606984:ERROR:welcome_dom_handler.cc(135)] OnGetDefaultBrowserbrowser_name:Google Chrome Beta
[29404:259:0323/102332.606994:ERROR:welcome_dom_handler.cc(141)] OnGetDefaultBrowserdefault_browser_name_:Google Chrome Beta
```

## Reproduces how often: 

100%

## Brave version (brave://version info)

/cc @LaurenWags 

Brave | 1.51.56 Chromium: 112.0.5615.29 (Official Build) nightly (x86_64)
-- | --
Revision | 8a59304c62e066962363d2fd8edd8e7b459c42bd-refs/branch-heads/5615@{#497}
OS | macOS Version 11.7.4 (Build 20G1120)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `n/a`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Miscellaneous Information:

cc @LaurenWags @spylogsster @rebron

**Comment by stephendonner** [comment]
Also, Chrome stable:

<img width="1920" alt="Screen Shot 2023-03-23 at 10 47 37 AM" src="https://user-images.githubusercontent.com/387249/227298279-1a91c40e-adf9-434d-b1bd-afbd981ada24.png">



`Google Chrome`:
```
[29624:259:0323/104715.550199:ERROR:welcome_dom_handler.cc(131)] OnGetDefaultBrowsername:Google Chrome.app
[29624:259:0323/104715.550242:ERROR:welcome_dom_handler.cc(141)] OnGetDefaultBrowserdefault_browser_name_:Google Chrome.app
```

**Comment by stephendonner** [comment]
<img width="1919" alt="Screen Shot 2023-03-23 at 10 54 14 AM" src="https://user-images.githubusercontent.com/387249/227301620-688e66b5-952a-424a-b18e-cd529ec494a0.png">


`Chrome Canary`:
```
[29702:259:0323/105323.848949:ERROR:welcome_dom_handler.cc(131)] OnGetDefaultBrowsername:Google Chrome Canary.app
[29702:259:0323/105323.848986:ERROR:welcome_dom_handler.cc(141)] OnGetDefaultBrowserdefault_browser_name_:Google Chrome Canary.app
```

**Comment by stephendonner** [comment]
From `Ventura 13.3`:

`Google Chrome Dev`

<img width="1680" alt="Screenshot 2023-03-23 at 2 40 08 PM" src="https://user-images.githubusercontent.com/387249/227371005-0e73ea89-b0e2-436d-97d1-f94aeb805a35.png">


`Google Chrome Beta`

<img width="1680" alt="Screenshot 2023-03-23 at 2 38 51 PM" src="https://user-images.githubusercontent.com/387249/227370764-a8f46e63-3ec5-48aa-abf9-996bba28a6e2.png">

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using `Big Sur`

Brave | 1.51.76 Chromium: 112.0.5615.49 (Official Build) beta (x86_64)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | macOS Version 11.7.5 (Build 20G1225)

`Google Chrome Beta`

`Google Chrome Dev`

**Comment by stephendonner** [comment]
## Verification `PASSED` on `Ventura`


Brave | 1.51.76 Chromium: 112.0.5615.49 (Official Build) beta (x86_64)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | macOS Version 13.4 (Build 22F5027f)

### Steps:

1. installed Google Chrome Dev and Google Chrome Beta
2. launched and populated them with bookmarks, browsing session/history, etc.
3. set one of the above as the default browser in `Apple menu` --> `System Preferences` --> `General`
4. installed Brave `1.51.76`
5. launched it
6. clicked `Skip` on the 1st page
7. on the next page, look for `Google Chrome Dev` or `Google Chrome Beta`
8. see if it has a checkmark

#### Confirmed the default-browser checkmark is applied to the appropriate, default browser


`Google Chrome Beta`

`Google Chrome Beta` default | `brave://welcome`
-------------------------------|-------------------
<img width="827" alt="Screenshot 2023-04-03 at 1 19 30 PM" src="https://user-images.githubusercontent.com/387249/229620859-1bf0cd68-b5a8-4396-ae9b-7b95fb397563.png"> | <img width="1374" alt="Screenshot 2023-04-03 at 1 24 54 PM" src="https://user-images.githubusercontent.com/387249/229621210-d455eb9a-5af7-4d27-8860-d15aeaf24a6b.png">


`Google Chrome Dev`

`Google Chrome Dev` default | `brave://welcome`
------------------------------|-------------------
<img width="827" alt="Screenshot 2023-04-03 at 1 19 36 PM" src="https://user-images.githubusercontent.com/387249/229620951-8163ca35-cec7-4591-a3f2-b19dc6fce663.png"> | <img width="1195" alt="Screenshot 2023-04-03 at 1 20 58 PM" src="https://user-images.githubusercontent.com/387249/229621050-9c4b19ab-6e52-4095-8d87-781e8bd3e444.png">

**Comment by LaurenWags** [comment]
Removed `QA/Test-All-Platforms` as this was originally working on Win and Linux per the original issue (https://github.com/brave/brave-browser/issues/28717) but was not working on macOS. This is the follow up issue for macOS. Added `OS/macOS` label.
