### ISSUE TITLE
(Wallet) Add new NFT tab

### ISSUE THREAD

**Issue by simoarpe** [brave/brave-browser#29274]
## Description 

Implements new NFT tab in the Wallet section.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.51.89 x64 Beta build
- Verified steps from [brave/brave-core#17738](https://github.com/brave/brave-core/pull/17738)
- Verified on mobile there are only 2 NFTs shown in a row
- Verified on tablet there are 4 NFT's shown in a row
- Verified clicking on the NFT shows the details screen
- Verified able to add NFT from both `Edit visible NFTs` in NFT tab and `Visible asset list` from portfolio tab
- Verified able to add both Ethereum and Solana NFTs
- Encountered [#29779](https://github.com/brave/brave-browser/issues/29779) & [29780](https://github.com/brave/brave-browser/issues/29780)

Oppo Reno 5 (Android 13) | Lenovo Tab (Android 12)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/232491197-2364c59e-b960-41d7-a1d7-187e4d13b429.mp4> | <video src=https://user-images.githubusercontent.com/17010094/232491231-67e8492f-f93b-4fff-9bdb-dc9625679c29.mp4>
