### ISSUE TITLE
Update extension install warning text

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#29280]
## Test plan
Text when installing an extension should be:
> Brave does not review extensions for security and safety. Install this extension only if you trust the developer.

## Description 
We should update the text shown when installing an extension

Change itself can be made here:
https://github.com/brave/brave-core/blob/ed2b2745a98c2605c447c5fbc23ff9505c0739a1/app/brave_generated_resources.grd#L279-L281

This is used here:
https://github.com/brave/brave-core/blob/ed2b2745a98c2605c447c5fbc23ff9505c0739a1/chromium_src/chrome/browser/extensions/extension_install_prompt.cc#L15-L20

## Steps to Reproduce

   1. Visit https://chrome.google.com/webstore/category/extensions?hl=en-US
   2. Find an interesting extension
   3. Install that extension

## Actual result:
![image](https://user-images.githubusercontent.com/4733304/227378463-e8040fb7-05fe-49bc-bbb1-55420484f198.png)

## Expected result:
TBD - help needed from @rmcfadden3 

## Notes
Internal discussion can be found at https://bravesoftware.slack.com/archives/C2J3NA3L7/p1679586946528949

**Comment by stephendonner** [comment]
## Verified `PASSED` using

### Steps:
1. installed `1.52.32`
2. launched Brave
3. loaded `https://chrome.google.com/webstore/detail/shimeji-browser-extension/gohjpllcolmccldfdggmamodembldgpc`
4. loaded `https://chrome.google.com/webstore/detail/brave-talk-for-google-cal/nimfmkdcckklbkhjjkmbjfcpaiifgamg`
5. loaded `https://chrome.google.com/webstore/detail/1password-%E2%80%93-password-mana/aeblfdkhhhdcdjpifhhbdiojplfjncoa`
6. loaded `https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm`
7. clicked on `Add to Brave`
8. examined the text in the dialog

#### Confirmed the text reads, "`Brave does not review extensions for safety and security.  Install this extension only if you trust the developer.`"

`Shimeji` | `Brave Talk for Google Calendar` | `1Password` | `uBlock Origin`
----------|-----------|----------|-----------
![image](https://user-images.githubusercontent.com/387249/231022990-9f5ed7db-4923-45c6-b862-17bfdcd9a173.png) | ![image](https://user-images.githubusercontent.com/387249/231023212-bffa160d-1b96-43ca-afb2-7329253d1dd2.png) | ![image](https://user-images.githubusercontent.com/387249/231024318-f299cc13-5cbd-4977-b3e4-4e90e5e20c35.png) | ![image](https://user-images.githubusercontent.com/387249/231024221-0b70870f-dded-4554-8abb-01a6d05752c6.png)
