### ISSUE TITLE
Brave connection to clients4.google.com for RAPPOR

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#2928]
see https://hackerone.com/bugs?subject=brave&report_id=455845

**Comment by bbondy** [comment]
Is this fixed here?
https://github.com/brave/brave-browser/issues/2255

**Comment by NejcZdovc** [comment]
@bbondy yes it is

**Comment by bbondy** [comment]
closing, but pls re-open if I'm wrong in closing it.
