### ISSUE TITLE
Update icon for `FIL on Filecoin EVM`

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#29295]
## Description 
Update icon for `FIL on Filecoin EVM`

## Steps to reproduce 

   1. Create wallet 
   2. Change network for FIL on Filecoin EVM Mainnet/Testnet
   3. Shows Eth icon rather than FIL icon

## Actual result 

Mainnet | Testnet
-- | --
![image](https://user-images.githubusercontent.com/17010094/227588073-8124a2c1-9f8d-4d45-9137-9b848c184743.png) | ![image](https://user-images.githubusercontent.com/17010094/227588089-93bf62da-5f77-483a-913b-f8f4726b69dc.png)

## Expected result
Use FIL icon

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 13
   
## Brave version
1.51.57

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @Pavneet-Sing @cypt4 @yrliou

**Comment by kjozwiak** [comment]
The above requires `1.50.111` or higher for `1.50.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.50.112 x64 build
- Verified FIL on Filecoin EVM shows the correct icon
- Verified FIL icon is shown on portfolio and on Send screen 

Oppo Reno 5 (Android 13) | Lenovo Tab (Android 12)
-- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/229485555-57e01133-f894-45db-92fb-032c13e4594e.png>  | <img width=400 src=https://user-images.githubusercontent.com/17010094/229486975-3868f563-b584-42ef-9abc-ebeae2121d58.png>
<img width=300 src=https://user-images.githubusercontent.com/17010094/229485568-1b822187-a013-4a40-b8dc-33c64052b67b.png>  | <img width=400 src=https://user-images.githubusercontent.com/17010094/229487025-4446e87e-7efa-4e71-b79c-ef33cf63c1da.png>
<img width=300 src=https://user-images.githubusercontent.com/17010094/229485598-67a7e81d-025f-41ae-9c7e-62c3af2946ec.png>  | <img width=400 src=https://user-images.githubusercontent.com/17010094/229487061-07cc8758-5ac3-429b-a1af-03ba14cffabe.png>
