### ISSUE TITLE
Block explorer doesn't load for FEVM transactions

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#29296]
## Description 
Block explorer doesn't load for FEVM transactions

## Steps to reproduce 

   1. Submit a FEVM transaction
   2. Wait for transaction confirmation
   3. Open block explorer from transaction menu, loads page but shows doesn't exist

## Actual result 

https://user-images.githubusercontent.com/17010094/227588988-552fa940-3991-458f-9d93-96219c8a1d35.mp4

## Expected result
Should load block explorer

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 13
   
## Brave version
1.51.57

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @cypt4 @yrliou @Pavneet-Sing

**Comment by kjozwiak** [comment]
The above requires `1.50.111` or higher for `1.50.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.50.112 x64 build
- Verified steps from issue description
- Verified correct transaction page is loaded when selecting from transaction history
- Encountered [#29380](https://github.com/brave/brave-browser/issues/29380)

https://user-images.githubusercontent.com/17010094/229486306-3d61f135-a9f9-4b8c-8b4c-0622765afe46.mp4
