### ISSUE TITLE
VPN panel outline is shown when the panel is dismissed making it looks like a ghost window 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#29298]
## Description 

VPN panel outline is shown when the panel is dismissed making it looks like a ghost window 

## Steps to Reproduce

   1. Clean profile on Beta
   2. Click on the VPN panel 
   3. Click outside to dismiss it, a panel outline flashes making it look like its a ghost panel window

## Actual result:

https://user-images.githubusercontent.com/17010094/227598277-12979c3c-59f1-4ea3-91fb-bddd611f8e6c.mp4

## Expected result:
No panel outlines when panel is closed

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.50.101 Chromium: 111.0.5563.116 (Official Build) beta (64-bit)
-- | --
Revision | `ade86b9472831e26d87fd569e04b404be01e1e2b-refs/branch-heads/5563@{#1209}`
OS | Windows 11 Version 22H2 (Build 22621.1413)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Maybe
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @mattmcalister @spylogsster @brave/qa-team

**Comment by bsclifton** [comment]
@srirambv is this still an issue? I can't reproduce

**Comment by srirambv** [comment]
Not reproducible anymore. Closing as stale
