### ISSUE TITLE
Implement welcome Brave Ads notification when user connects custodial account: tell user they're now earning, and clicking isn't required

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#29297]
## Description

After user connects custodial account and transitions from non-connected state to connected state, show the following in a system notification (same format as Brave Ads push notifications):

>🎉 You’re now earning for Brave Ads! For example, you earn whenever a notification like this appears on your screen. You don’t need to click to earn.

cc: @ddvorin1 @tmancey

**Comment by tmancey** [comment]
@LaurenWags it should timeout the same as push, hopefully this is the case? Thanks

**Comment by LaurenWags** [comment]
@brave/qa-team when testing this, in addition to the test plan under https://github.com/brave/brave-core/pull/17881#issue-1652115776, we should also verify the following:
- notification can be closed manually
- notification times out after 2 minutes as per above comments
- clicking on the notification does not close the notification nor does it direct to any specific URL

We should also check the following scenarios:
1. For a grandfathered unverified user in 1.51.x, when they upgrade to 1.52.x no notification is shown. However, if a custodial wallet is connected using 1.52.x, then the notification shows.
2. For a user who is connected to a custodian in 1.51.x (not logged out/disconnected verified) and upgrades to 1.52.x, no notification is shown.
3. For a user who is connected to a custodian in 1.51.x and is also in the logged out/disconnected verified state and upgrades to 1.52.x, they will still be in logged out/disconnected verified state after upgrading. When the user logs back into their custodian/re-connects to verified, no notification is shown.

cc @emerick @Miyayes to confirm the above

**Comment by Miyayes** [comment]
1, 2, 3 are correct @LaurenWags. The criterion is: Did user move from non-connected state to connected state? It does *not* include moving from loggedOut state to connected state.

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave | 1.52.94 Chromium: 113.0.5672.92 (Official Build) beta (64-bit)
-- | --
Revision | b6f521170062a1fa8a82c33fb223b06fec566da1-refs/branch-heads/5672_63@{#10}
OS | Windows 10 Version 21H2 (Build 19044.2965)

```

**Comment by GeetaSarvadnya** [comment]
@Miyayes @emerick : Click on the notification dismiss the ad notification, it doesn't open the landing page. Is this expected?

**Comment by tmancey** [comment]
@GeetaSarvadnya @btlechowski this is fixed by @aseren recent fix which he has requested uplift.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.52.108 Chromium: 114.0.5735.26 (Official Build) beta (x86_64)
-- | --
Revision | 7075cbb66f0542ac3e01ddfde6b813e7d61118a5-refs/branch-heads/5735@{#454}
OS | macOS Version 13.4 (Build 22F66)
```
