### ISSUE TITLE
Disable Copy Clean link hotkeys for OSX

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#29303]
Disable feature kBraveCopyCleanLinkByDefault on osx by default

**Comment by LaurenWags** [comment]
@brave/qa-team added `QA/Test-All-Platforms` since we should confirm the following:
- disabled by default on macOS
- enabled by default on Windows and Linux

See https://github.com/brave/brave-browser/issues/29177 verification notes for for examples.

**Comment by kjozwiak** [comment]
The above requires `1.49.131` or higher for `1.49.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.49.131 Chromium: 111.0.5563.116 (Official Build) (arm64)
-- | --
Revision | ade86b9472831e26d87fd569e04b404be01e1e2b-refs/branch-heads/5563@{#1209}
OS | macOS Version 12.6.3 (Build 21G419)
```

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.49.131 Chromium: 111.0.5563.116 (Official Build) (x86_64)
-- | --
Revision | ade86b9472831e26d87fd569e04b404be01e1e2b-refs/branch-heads/5563@{#1209}
OS | macOS Version 11.7.4 (Build 20G1120)


<details>
<summary>Default - PENDING</summary>

Case A: Ran through appropriate cases on https://fmarier.github.io/brave-testing/copy-clean-link.html to confirm functionality still works with the keyboard shortcut disabled. (spot check of "Copy clean link" functionality)

Case B: Ran through the below steps to confirm expected locations of "Copy clean link" option and confirm that keyboard shortcut (command + C on macOS) is not used for "Copy clean link":

0. Confirmed value of `Default` for `brave://flags/#brave-copy-clean-link-by-default`
1. Visited `https://dev-pages.bravesoftware.com/clean-urls/?brave_testing1=foo&brave_testing2=bar&brave_testing3=keep&&;b&d&utm_content=removethis&e=&f=g&=end`
2. Right-clicked the URL and confirmed "Copy clean link" is in the context menu
3. Confirmed "Copy clean link" is displayed in the share menu from URL bar
4. Used "command + C" while the URL bar is in focus to copy the URL
5. Opened a new tab and pasted the copied URL
6. Confirmed link pasted is the original URL with all parameters: `https://dev-pages.bravesoftware.com/clean-urls/?brave_testing1=foo&brave_testing2=bar&brave_testing3=keep&&;b&d&utm_content=removethis&e=&f=g&=end`
7. Opened a new tab and visited `https://twitter.com/LBC/status/1577628501364146176?s=20&t=fpVMBMSfgI_pNGQxxpV6bw`
8. Used "command+ C" while the URL bar is in focus to copy the URL
9. Opened a new tab and pasted the copied link
10. Confirmed link pasted is the original URL with all parameters `https://twitter.com/LBC/status/1577628501364146176?s=20&t=fpVMBMSfgI_pNGQxxpV6bw` 

Step 0 | Step 2 | Step 3 | Step 6 | Step 7 | Step 10
---- | ---- | ---- | ---- | ---- | ----


</details>

<details>
<summary>Enabled - PENDING</summary>

Case A: Ran through appropriate cases on https://fmarier.github.io/brave-testing/copy-clean-link.html to confirm functionality works as expected with the keyboard shortcut enabled. (spot check of "Copy clean link" functionality)

Case B: Ran through the below steps to confirm expected locations of "Copy clean link" option and confirm that keyboard shortcut (command + C on macOS) is used for "Copy clean link":

0. Confirmed value of `Default` for `brave://flags/#brave-copy-clean-link-by-default`
1. Visited `https://dev-pages.bravesoftware.com/clean-urls/?brave_testing1=foo&brave_testing2=bar&brave_testing3=keep&&;b&d&utm_content=removethis&e=&f=g&=end`
2. Right-clicked the URL and confirmed "Copy clean link" is in the context menu
3. Confirmed "Copy clean link" is displayed in the share menu from URL bar
4. Used "command + C" while the URL bar is in focus to copy the URL
5. Opened a new tab and pasted the copied URL
6. Confirmed link is `https://dev-pages.bravesoftware.com/clean-urls/?brave_testing3=keep&&;b&d&e=&f=g&=end` as per the original issue verification from https://github.com/brave/brave-browser/issues/23315
7. Opened a new tab and visited `https://twitter.com/LBC/status/1577628501364146176?s=20&t=fpVMBMSfgI_pNGQxxpV6bw`
8. Used "command + C" while the URL bar is in focus to copy the URL
9. Opened a new tab and pasted the copied link
10. Confirmed link pasted is `https://twitter.com/LBC/status/1577628501364146176` as per the original issue verification from https://github.com/brave/brave-browser/issues/23315

Step 0 | Step 2 | Step 3 | Step 6 | Step 7 | Step 10
---- | ---- | ---- | ---- | ---- | ----



</details>



<details>
<summary>Disabled - PENDING</summary>


0. Confirmed value of `Default` for `brave://flags/#brave-copy-clean-link-by-default`
1. Visited `https://dev-pages.bravesoftware.com/clean-urls/?brave_testing1=foo&brave_testing2=bar&brave_testing3=keep&&;b&d&utm_content=removethis&e=&f=g&=end`
2. Right-clicked the URL and confirmed "Copy clean link" with Ctrl +C as the shortcut in the context menu
3. Confirmed "Copy clean link" is displayed in the share menu from URL bar
4. Used "command + C" while the URL bar is in focus to copy the URL
5. Opened a new tab and pasted the copied URL
6. Confirmed link is `https://dev-pages.bravesoftware.com/clean-urls/?brave_testing3=keep&&;b&d&e=&f=g&=end` as per the original issue verification from https://github.com/brave/brave-browser/issues/23315
7. Opened a new tab and visited `https://twitter.com/LBC/status/1577628501364146176?s=20&t=fpVMBMSfgI_pNGQxxpV6bw`
8. Used "command` + C" while the URL bar is in focus to copy the URL
9. Opened a new tab and pasted the copied link
10. Confirmed link pasted is `https://twitter.com/LBC/status/1577628501364146176` as per the original issue verification from https://github.com/brave/brave-browser/issues/23315

Step 0 | Step 2 | Step 3 | Step 6 | Step 7 | Step 10
---- | ---- | ---- | ---- | ---- | ----











</details>








</details>

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.49.132 Chromium: 111.0.5563.147 (Official Build) (64-bit)
-- | --
Revision | 029fd65a4dd711d1078468ed2206999cec86066b-refs/branch-heads/5563@{#1239}
OS | Windows 10 Version 21H2 (Build 19044.2728)

```
