### ISSUE TITLE
Remove `Brave.Rewards.AutoContributionsState.2` and replace with `Brave.Rewards.AutoContributionsState.3`

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#29300]
## Description

`Brave.Rewards.AutoContributeState.3`

Question:  If you’re a Brave Rewards user with a custodial account linked, is your Auto-Contribute feature ON?

1. It’s ON
2. It’s OFF

**Comment by DJAndries** [comment]
edited question above

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave | 1.52.85 Chromium: 113.0.5672.63 (Official Build) beta (64-bit)
-- | --
Revision | 0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}
OS | Windows 10 Version 21H2 (Build 19044.2846)

```

**_New user_**

<details>
<summary>Case 1: Brave.Rewards.AutoContributeState.3 = 0</summary>


</details>

<details>
<summary>Case 1: Brave.Rewards.AutoContributeState.3 = 0</summary>


</details>

**_Existing user_**

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.52.112`

- Verified the description from the issue

**_New user_**

<details>
<summary>Case 1: Brave.Rewards.AutoContributionsState = 0_PASSED</summary>

1. Clean profile 1.52.x
2. Enable rewards but don't connect to any custodian wallet
3. Open brave://local-state 
4. Look for the metrics `Brave.Rewards.AutoContributionsState.3`
5. Confirmed that the metrics `Brave.Rewards.AutoContributionsState.3` is NOT shown in the local-state file

Example | Example
----------|-----------


</details>

<details>
<summary>Case 2: Brave.Rewards.AutoContributionsState = 1_PASSED</summary>

<details>
<summary>Case 2.1_Enable rewards and connect wallet custodian_PASSED</summary>

1. Clean profile 1.52.x
2. Enable rewards and connect to any custodian wallet
3. Open brave://local-state 
4. Look for the metrics `Brave.Rewards.AutoContributionsState.3`
5. Confirmed that the metrics `Brave.Rewards.AutoContributionsState.3` is displayed with the response value `1` as expected.

Example | Example
----------|-----------


</details>


<details>
<summary>Case 2.2_Reset rewards_PASSED</summary>

1. Clean profile 1.52.x
2. Enable rewards and connect to any custodian wallet
3. Open brave://local-state 
4. Look for the metrics `Brave.Rewards.AutoContributionsState.3`
5. Confirmed that the metrics `Brave.Rewards.AutoContributionsState.3` is displayed with the response value `1` as expected.
6. Reset rewards via `Reset` option
7. Reload brave://local-state file
8. Confirmed that the metrics `Brave.Rewards.AutoContributionsState.3` is NOT shown in the local-state file

Example | Example | Example
----------|-----------|---------



</details>

</details>

**_Existing user_**

<details>
<summary>Case 1: Brave.Rewards.AutoContributionsState = 0_PASSED</summary>

1. Clean profile 1.51.x
2. Enable rewards but don't connect to any custodian wallet
3. Open brave://local-state 
4. Confirmed that the metrics `Brave.Rewards.AutoContributionsState.2` is displayed with the response value `3` 
5. Upgrade the profile to 1.52.x 
6. Reload brave://local-state file
7. Confirmed that the metrics `Brave.Rewards.AutoContributionsState.3` is NOT shown in the local-state file as expected

**`1.51.x`** | **`1.51.x`** | **`1.52.x`** | **`1.52.x`**
------------|--------------|-------------|--------


</details>

<details>
<summary>Case 2: Brave.Rewards.AutoContributionsState = 1_PASSED</summary>

1. Clean profile 1.51.x
9. Enable rewards and connect to any custodian wallet
10. Open brave://local-state 
11. Look for the metrics `Brave.Rewards.AutoContributionsState.3`
12. Confirmed that the metrics `Brave.Rewards.AutoContributionsState.2` is displayed with the response value `3` 
13. Upgrade the profile to 1.52.x 
14. Reload brave://local-state file
15. Confirmed that the metrics `Brave.Rewards.AutoContributionsState.3` is displayed with the response value `1` as expected


**`1.51.x`**  | **`1.52.x`**
-------------|-------------



</details>
