### ISSUE TITLE
Many websites are not loading completely after browser restart

### ISSUE THREAD

**Issue by Liunkae** [brave/brave-browser#2930]
## Description 
Parts of many websites are not loading after a browser restart. The sites do not load even if you turn shields off. The developer console does not show anything (it has other errors that occur for any GitHub page). This problem only happens after you have used the browser more than once (launch fresh profile, quit, relaunch).

Examples:
- https://github.com while logged in: If you go to the GitHub home page while logged in, GitHub shows your Recent Activity in the dashboard. In Brave, the Recent Activity section does not load.
- https://hstspreload.org/?domain=brave.com: The HSTS check does not finish loading.
- https://brave.com/jobs/: The job listings do not load.

## Steps to Reproduce
   1. Start with a fresh profile.
   2. Quit the browser.
   3. Start Brave again.
   4. Go to https://github.com/login and log in.
   5. Go to https://github.com/ (the dashboard page).

## Actual result:
![image](https://user-images.githubusercontent.com/19424103/51077030-41ec6f00-1666-11e9-9ed1-16e635629303.png)

## Expected result:
Here is what Safari shows:
![image](https://user-images.githubusercontent.com/19424103/51077033-516bb800-1666-11e9-9af9-d58f1cd1052f.png)

## Reproduces how often: 
Always.

## Brave version (brave://version info)
Brave | 0.60.11 Chromium: 72.0.3626.28 (Official Build) dev(64-bit)
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Yes, 0.60.11 dev.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No.
- Is the issue reproducible on the latest version of Chrome? Not sure. It works fine with Safari.

**Comment by Liunkae** [comment]
After I created a fresh profile, the problem went away. Then I changed some settings, and the problem returned. I created another fresh profile and tried changing settings again, but I could not reproduce the problem. I have not found out which setting caused the problem.

**Comment by bbondy** [comment]
@kjozwiak @srirambv could one of you check this?

**Comment by Liunkae** [comment]
Duplicate of #2901
