### ISSUE TITLE
Videos don't play on videoportal.joj.sk

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#2931]
## Description 
[A user on Twitter](https://twitter.com/MayoKucerka/status/1084107491233927168) has reported that videos don't play properly on videoportal.joj.sk.

## Steps to Reproduce
1. Navigate to https://videoportal.joj.sk/vsetko-co-mam-rad/epizoda/61134-vsetko-co-ma-ander-rad
2. Click to play the video

## Actual result:
Video doesn't play; appears to be stuck _loading_.

## Expected result:
Video loads as needed, and begins playing promptly.

## Reproduces how often: 
Easily.

## Brave version (brave://version info)
0.58.21

### Reproducible on current release:
Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? Yes
- Is the issue reproducible on the latest version of Chrome? No

### Additional Information
In order to play the videos, the user must disable 'ads and trackers blocked' via the site shields panel.

**Comment by mrzealot** [comment]
Did a comparison between Brave and an ABP'd Chrome, and managed to trace the issue back to how we treat [ima3.js](https://developers.google.com/interactive-media-ads/docs/sdks/html5/). ABP blocks the request (a failure the system can tolerate by simply leaving out the ads from the video), while we use a 307 internal redirect to an empty data URL which suggests to the code that ima *should* be loaded.

I'm not super familiar with the pros/cons of blocking the 307 way, but this time that's the issue. It also causes console errors in #3031 but there it's not a big thing. CC @bbondy

**Comment by bbondy** [comment]
@mrzealot I think ultimately we'll let the matching block rule decide to block or 200 ok, but default to 200 ok.

**Comment by btlechowski** [comment]
@bbondy PR for 0.63.x is not merged. https://github.com/brave/brave-core/pull/2012

**Comment by bbondy** [comment]
Yep I was going to rebase today and reland tomorrow. Sorry for the delay.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.63.35 Chromium: 74.0.3729.61 (Official Build) beta(64-bit)
-- | --
Revision | 5df2c8936783bd7575987e45d72a92fcf528496b-refs/branch-heads/3729@{#645}
OS | Linux

* Verified the video loaded without having to change default shields settings
* Verified the page loaded with 200 OK status in network tab
