### ISSUE TITLE
Update wireguard deps to tunnel-1.0.20230321

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#29319]
This issue is to update wireguard dependency to tunnel-1.0.20230321.

More details at https://central.sonatype.com/artifact/com.wireguard.android/tunnel/1.0.20230321:

**Comment by vlad-hoff** [comment]
Verified on `Google Pixel 6` using version(s):

```
Device/OS: Google Pixel 6 [oriole-user 13 TQ2A.230405.003.E1 release-keys]
Brave build: 1.52.69, Chromium: 113.0.5672.53 (Official Build) canary (64-bit) 
```
---------------------------

**Preconditions:**
- Install build 1.51.x
- Enable Brave VPN option from QA preferences
- Once the VPN option is enabled, you would be able to see the Brave VPN Menu item in the Context Menu as well as the Brave VPN option in the settings

<details>
<summary> New user with fresh subscription - PASS </summary>

**STEPS:**
1. Click on Brave VPN from Context Menu > It should open the subscription page
2. Buy a `monthly subscription`
3. Select the `Test card, always approves` > Subscribe
4. Once you are done buying the subscription, click on Install VPN Profile and it would show the prompt to accept the consent
5. VPN should be turned on right after accepting the consent and VPN notification should be shown
6. Try turning On/Off VPN with the same menu option
7. If you go to settings > Brave Firewall + VPN > Check for the automatically selected server location
10. Check https://ipinfo.io for correct server details

**ACTUAL RESULTS:**
- Verified that VPN is enabled when purchasing a new subscription and accepting the consent
- Verified that automatically selected server location matches the device timezone when first time enabling VPN
- Verified that correct server details are shown on https://ipinfo.io when Turning On/Off VPN 

|Turned Off|Turned On|Turned On|Turned On|
|-|-|-|-|
| ![1](https://user-images.githubusercontent.com/128532965/235540169-add8c5e4-e7e5-4ce8-b90f-530f02bcd317.png) | ![2](https://user-images.githubusercontent.com/128532965/235540843-fd565624-7fb0-4b31-9118-7b3bbe7f3553.png) | ![3](https://user-images.githubusercontent.com/128532965/235540254-e8ed97dc-0b93-4c92-bf7f-fec27051738b.png) | ![4](https://user-images.githubusercontent.com/128532965/235540434-441324b0-43ce-4f93-8873-0caa09f692f8.png) |
</details>

<details>
<summary> Multiple server change - PASS </summary>

**STEPS:**
1. Follow all steps from `New user with fresh subscription`
2. Go to settings > Brave Firewall + VPN > Change server location from the Location section
3. Check https://ipinfo.io for correct server details
4. Try changing the servers to different locations
5. Check https://ipinfo.io for correct server details

**ACTUAL RESULTS:**
- Verified the changes applied in the Server Location setting when updating the server
- Verified that correct server details are shown on https://ipinfo.io when changing Server Location

|JP|BR|AU|
|-|-|-|
| ![1](https://user-images.githubusercontent.com/128532965/235542552-694e1b55-b518-4f77-bf5e-60fedab4fbc8.png) | ![2](https://user-images.githubusercontent.com/128532965/235542567-fcb93760-1bdb-448f-affd-01037c027dcf.png) | ![3](https://user-images.githubusercontent.com/128532965/235542579-d2f76843-9f20-4d70-9813-407a002278e6.png) |
</details>

<details>
<summary> Existing user with Existing subscription - PASS </summary>

**STEPS:**
1. Follow all steps from `New user with fresh subscription` on Phone 1
2. Follow the Precondition steps on Phone 2
3. Tap on Brave VPN from the Context Menu or go to settings > Brave Firewall + VPN > Tap on Enabled
4. It should open the subscription page and If the subscription was bought using the same user, you are using on Phone 2, it should show the Restore button in the top right corner
5. Tap on Restore to restore the subscription for the same user
6. Tap on Install VPN and it would show the prompt to accept the consent
7. Try turning On/Off VPN with the same menu option
8. If you go to settings > Brave Firewall + VPN > Check for the automatically selected server location
9. Check https://ipinfo.io for correct server details

**ACTUAL RESULTS:**
- Verified that VPN must be turned on right after accepting the consent and VPN notification must be shown
- Verified that automatically selected server location matches the device timezone when first time enabling VPN
- Verified that correct server details are shown on https://ipinfo.io when Turning On/Off VPN 

|Turned Off|Turned On|Turned On|Turned On|
|-|-|-|-|
| ![1](https://user-images.githubusercontent.com/128532965/235544513-982ee269-7b3f-465d-a8f6-384c9e33b585.png) | ![2](https://user-images.githubusercontent.com/128532965/235544531-f21073bc-f4fe-4c66-adf6-2f9c13779557.png) | ![3](https://user-images.githubusercontent.com/128532965/235544608-fc40304a-e3d3-4649-a1b0-12a4b4261b23.png) |
</details>
