### ISSUE TITLE
Implement reminder notification: If user clicks same ad 3 times, then show reminder notification that clicking is not necessary to earn

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#29313]
## Description

If user clicks same ad 3 times, then show reminder notification that clicking is not necessary to earn:

>Reminder: You earn when a Brave Ads notification appears. 
>You don’t need to click to earn, but do click if you’re interested!

* Will show every time same ad is clicked 3 times
* Click threshold # is editable via Griffin
* If user clicks on the notification, takes them to https://support.brave.com/hc/en-us/articles/14648356808845 

cc: @ddvorin1 @tmancey

**Comment by LaurenWags** [comment]
@Miyayes could you add appropriate "QA" label (`QA/Yes` or `QA/No`) and appropriate release notes label (`release-notes/include` or `release-notes/exclude`)? Thanks!

**Comment by btlechowski** [comment]
Added [QA/Test-All-Platforms](https://github.com/brave/brave-browser/labels/QA%2FTest-All-Platforms). 

Please test only `Reminder notification after single notification ad` from https://github.com/brave/brave-browser/issues/29313#issuecomment-1544109394

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.52.103 Chromium: 113.0.5672.126 (Official Build) beta (x86_64)
-- | --
Revision | c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}
OS | macOS Version 13.4 (Build 22F66)

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using

```
Brave | 1.52.109 Chromium: 114.0.5735.26 (Official Build) beta (64-bit)
-- | --
Revision | 7075cbb66f0542ac3e01ddfde6b813e7d61118a5-refs/branch-heads/5735@{#454}
OS | Windows 11 Version 22H2 (Build 22621.1702)
```

### Reminder notification after single notification ad - `PASSED`

### Steps:
1. installed `1.52.109`
2. launched Brave using 
```
--enable-logging=stderr --vmodule="*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6,"*/bat_ads/*"=6 --variations-server-url=https://test --enable-features=Reminder:remind_user_if_clicking_the_same_ad_after/1 --rewards=staging=true --use-dev-goupdater-url
```
3. enabled Rewards and Ads
4. viewed a notification ad
5. clicked the notification ad

### Confirmed clicking on the 1st ad notification yielded `You earn when a Brave ads notifi...` notification

Also confirmed the notification's link is `https://support.brave.com/hc/en-us/articles/14648356808845`

example | example | example | example 
---------|---------|----------|-----------
![image](https://github.com/brave/brave-browser/assets/98358127/dfb32d35-2734-45d6-821c-a9adb91923c1)|![image](https://github.com/brave/brave-browser/assets/98358127/3f609dd2-95b4-4f41-bc70-6a4871012862)|![image](https://github.com/brave/brave-browser/assets/98358127/c32e2fac-9641-4556-a434-23278fd83564)|![image](https://github.com/brave/brave-browser/assets/98358127/ae6e9631-40db-47ef-9abd-702a50b8d592)
