### ISSUE TITLE
Bug: Select Text not working 

### ISSUE THREAD

**Issue by 6d7a** [brave/brave-browser#29329]
## Description 
On certain sites, most notably github, selecting text does not work. I'm using a plain old mouse for input.

## Steps to Reproduce
   1. Open [https://github.com/brave/brave-browser](https://github.com/brave/brave-browser) or any other repo.
   2. Try selecting a paragraph of text from the README

## Actual result:
Text selection does not work. 
![brave_issue](https://user-images.githubusercontent.com/56823591/227871261-e3747580-a150-41b5-a7ef-ec64e69bd736.gif)

## Expected result:
![expected](https://user-images.githubusercontent.com/56823591/227871858-8b4948a7-dff8-4035-9edc-19323cd21b0f.gif)

## Reproduces how often: 
Constant behavior. 

## Brave version (brave://version info)
 - **Brave** 1.49.128 Chromium: 111.0.5563.110 (Official Build) (64-bit) 
 - **Revision** 3da375c9e9e5ad9b556af5df708a6e6c01d8cfb1-refs/branch-heads/5563@{#1202}
 - **OS** Windows 11 Version 22H2 (Build 22621.1413)
 - **JavaScript** V8 11.1.277.17
 - **User Agent** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
 - **Command Line** "C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe" --disable-domain-reliability --enable-dom-distiller --lso-url=https://no-thanks.invalid --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --variations-insecure-server-url=https://variations.brave.com/seed --variations-server-url=https://variations.brave.com/seed --restart --flag-switches-begin --enable-experimental-web-platform-features --flag-switches-end --component-updater=url-source=https://go-updater.brave.com/extensions,url-source=https://go-updater.brave.com/extensions
 - **Executable Path** C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe
 - **Profile Path** C:\Users\[USERNAME]\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
 - **Active Variations** AdRewardsStudy:NextPaymentDay
AllowCertainClientHintsStudy:Enabled
BraveAdblockCookieListOptInReleaseStudy:Enabled
BraveAdblockMobileNotificationsListDefault:Enabled
BraveAds.AdServingStudy:DefaultAdNotificationsPerHour=10/MaximumAdNotificationsPerDay=100/MaximumInlineContentAdsPerHour=6/MaximumInlineContentAdsPerDay=20/AdServingVersion=1
BraveAutoTranslateStudy:AutoTranslateDisabled
BraveDebounceStudy:Enabled
BraveRewardsWebUiPanelStudy:Enabled
BraveScreenFingerprintingBlockerStudy:Default
ConversionsStudy:NewDefaultPattern
CrossPlatformVPNStudy:Enabled
Default1pBlockingStudy:Disabled
DisableReduceLanguage:Enabled
EphemeralStorageStudy:Enabled
FirstPartyEphemeralDomainBlockStudy:Enabled
ForceDisableBlinkFeatures:Enabled
MetricsAndCrashSampling:OutOfReportingSample
PartitionBlinkMemoryCacheStudy:Enabled
PartitionConnectionsByNetworkIsolationKeyStudy:Enabled
PermissionLifetimeReleaseStudy:Enabled
SpeedreaderReleaseStudy:Enabled
UserActivityStudy:Triggers

## Version/Channel Information:

- Can you reproduce this issue with the current release? **Yes**
- Can you reproduce this issue with the beta channel? **No**
- Can you reproduce this issue with the nightly channel? **No**

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? **No**
- Does the issue resolve itself when disabling Brave Rewards? **No**
- Is the issue reproducible on the latest version of Chrome? **No**

**Comment by TunaOnAir** [comment]
It worked for me after disabling "Experimental Web Platform features" from brave://flags.

**Comment by rebron** [comment]
Closing as wontfix. Feature flag related.
