### ISSUE TITLE
Update toolbar's download button style

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#29324]
In progress (captured from figma)
<img width="359" alt="Screenshot 2023-03-27 at 3 37 40 PM" src="https://user-images.githubusercontent.com/6786187/227860636-004ba0a8-2174-44fb-a7bd-317f773b26a8.png">
<img width="204" alt="Screenshot 2023-03-27 at 3 43 49 PM" src="https://user-images.githubusercontent.com/6786187/227861256-8553feb8-6c32-47c6-927e-faf093a546d8.png">

Completed
<img width="216" alt="Screenshot 2023-03-27 at 3 37 53 PM" src="https://user-images.githubusercontent.com/6786187/227860642-5dee852f-3fde-4a10-9b33-2e481c1aba2a.png">
<img width="204" alt="Screenshot 2023-03-27 at 3 43 58 PM" src="https://user-images.githubusercontent.com/6786187/227861289-5a568f49-eb26-447f-af84-690c94fb0bed.png">

**Comment by kjozwiak** [comment]
@rebron maybe we should look into using another colour for the progress indication in dark mode? It's pretty hard to see as we're using a dark blue against black. It's not the easiest to see. Example via https://github.com/brave/brave-core/pull/17769#issuecomment-1489379137.

**Comment by rebron** [comment]
@aguscruiz We probably want to go lighter color for contrast for dark mode. Really subtle with the progress bar.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.50.110 Chromium: 112.0.5615.49 (Official Build) (x86_64)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | macOS Version 12.6.4 (Build 21G526)
```

**Comment by MadhaviSeelam** [comment]
Verification `PASSED`
```
Brave | 1.50.110 Chromium: 112.0.5615.49 (Official Build) (64-bit)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Windows 11 Version 22H2 (Build 22621.1413)
```

<details>
<summary>Normal Window - PASSED</summary>

Light theme | Dark theme
---- | ----
<img width="276" alt="image" src="https://user-images.githubusercontent.com/98358127/229249627-7e4134ae-b4df-47da-8db2-581316cfa0b9.png"> | <img width="293" alt="image" src="https://user-images.githubusercontent.com/98358127/229249730-3b22fe90-1f99-4220-bb11-d6f457715f2f.png"> 
<img width="278" alt="image" src="https://user-images.githubusercontent.com/98358127/229254696-2b717b3d-d7e9-4f92-abd6-966fe614ee92.png"> | <img width="269" alt="image" src="https://user-images.githubusercontent.com/98358127/229254671-8348031f-f499-4d7a-abe6-3cb7157d7c6e.png">

</details>

<details>
<summary>Tor Window - PASSED</summary>

download in-progress | download complete
---- | ----
<img width="248" alt="image" src="https://user-images.githubusercontent.com/98358127/229249759-9c95d645-50f4-4856-a7ea-947050cb9945.png">|<img width="245" alt="image" src="https://user-images.githubusercontent.com/98358127/229253003-f4618dbb-3419-4ece-8e67-94cf9515442e.png">

</details>

<details>
<summary>Private Window - PASSED</summary>

download in-progress | download complete
---- | ----
<img width="246" alt="image" src="https://user-images.githubusercontent.com/98358127/229249833-b4ed9411-9990-4791-bed8-63c7f68749b0.png">|<img width="247" alt="image" src="https://user-images.githubusercontent.com/98358127/229253336-f81934f5-7575-4560-a542-7b85d7b04c8d.png">

</details>
<details>
<summary>Guest Window - PASSED</summary>

download in-progress | download complete
---- | ----
<img width="255" alt="image" src="https://user-images.githubusercontent.com/98358127/229249811-1c943530-2a19-4e1d-aee4-152242318e8c.png">|<img width="255" alt="image" src="https://user-images.githubusercontent.com/98358127/229253488-db652d66-679d-48d7-bd55-d54706979347.png">
</details>
