### ISSUE TITLE
(Wallet) Remove NFTs from Portfolio

### ISSUE THREAD

**Issue by simoarpe** [brave/brave-browser#29330]
## Description 
Removes NFTs from Portfolio section in Brave Wallet.

![Screenshot_1679909671](https://user-images.githubusercontent.com/3308503/227903202-cb6f714a-e3ad-49c2-8a2a-890869fde2d9.png)

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.51.79  x64 build
- Verified steps from [brave/brave-core#17797](https://github.com/brave/brave-core/pull/17797)
- Verified on upgrade from previous version, added NFT's are automatically removed from portfolio and added under the NFT tab
- Verified on clean install a NFT tab is shown by default
- Verified adding an custom token which is NFT is automatically listed under the NFT tab
- Encountered [#29615](https://github.com/brave/brave-browser/issues/29615) & [#29616](https://github.com/brave/brave-browser/issues/29616)

Oppo Reno 5 (Android 13) | Lenovo Tab (Android 12)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/231142182-be05bae6-9640-4948-92d9-e9ce3a79d23a.mp4> | <video src=https://user-images.githubusercontent.com/17010094/231142484-a6081d85-e42c-44d8-adf8-88e2a5e053e5.mp4>
