### ISSUE TITLE
Gif images only show one frame on portfolio 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#29332]
## Description 

Gif images only show one frame on portfolio 

## Steps to Reproduce

   1. Add an NFT (Invisible Friends)
   2. Image shows only one frame of the gif image in portfolio
   3. Open NFT details page, shows the proper gif image

## Actual result:

https://user-images.githubusercontent.com/17010094/227930307-dbf6d96f-100c-44cc-a168-9ff27b394330.mp4

## Expected result:
Should show the gif image on portfolio as well

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.50.101 Chromium: 111.0.5563.116 (Official Build) beta (64-bit)
-- | --
Revision | `ade86b9472831e26d87fd569e04b404be01e1e2b-refs/branch-heads/5563@{#1209}`
OS | Windows 11 Version 22H2 (Build 22621.1413)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @muliswilliam @Douglashdaniel @jamesmudgett

**Comment by josheleonard** [comment]
Closing, as this is no longer valid
