### ISSUE TITLE
`Use secure DNS` is locked when brave_vpn_helper service is running

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#29338]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/28195
`Use secure DNS` is locked when brave_vpn_helper service is running
## Steps to Reproduce

   1. Install `1.50.101`
   2. launch Brave
   3. restart (to pick up Griffin changes)
   4. purchase/link/set up `BraveVPN`
   5. connect to `BraveVPN`
   6. press `ctrl` + `alt` + `del` to open `Task Manager`
   7. look for the `Brave VPN Helper` task
   8. Ensure that `brave_vpn_helper` service is running under `Details` tab in task manager
   9. Open brave://settings/security
   10. `Use secure DNS` is locked when brave_vpn_helper service is running
   

## Actual result:

`Use secure DNS` is locked when brave_vpn_helper service is running
![image (4)](https://user-images.githubusercontent.com/38657976/227997910-fb85fb29-a95a-4dc9-bf79-e271a60ad593.png)

## Expected result:
`Use secure DNS` should not be locked when brave_vpn_helper service is running

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.50.101 Chromium: 111.0.5563.116 (Official Build) beta (64-bit)
-- | --
Revision | ade86b9472831e26d87fd569e04b404be01e1e2b-refs/branch-heads/5563@{#1209}
OS | Windows 10 Version 21H2 (Build 19044.2728)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @spylogsster @brave/qa-team @bsclifton

**Comment by stephendonner** [comment]
@spylogsster @bsclifton locking `Use Secure DNS`'s toggle was part of connecting to the VPN helper server on Windows, I thought, per https://github.com/brave/brave-browser/issues/28195#issuecomment-1481723596.

Why/when did we diverge? Just trying to understand so I can verify properly, thanks!

**Comment by spylogsster** [comment]
> @spylogsster @bsclifton @GeetaSarvadnya locking `Use Secure DNS`'s toggle was part of connecting to the VPN helper server on Windows, I thought, per [#28195 (comment)](https://github.com/brave/brave-browser/issues/28195#issuecomment-1481723596).
> 
> Why/when did we diverge? Just trying to understand so I can verify properly, thanks!
> 
> In [#28195 (comment)](https://github.com/brave/brave-browser/issues/28195#issuecomment-1485067627), these two things are at odds:
> 
> <img alt="Screen Shot 2023-05-10 at 6 18 46 PM" width="976" src="https://user-images.githubusercontent.com/387249/237548252-ed3ea2d0-f886-4abf-8d39-8b99a407b8a8.png">

`Use Secure DNS` can be enabled only if `brave_vpn_helper.exe` was unable to set filters, if it was crashed or so, it (locking DNS settings) works as fallback now if `brave_vpn_helper.exe` does not work as expected.

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS`  using 

Brave | 1.52.99 Chromium: 113.0.5672.92 (Official Build) beta (64-bit)
-- | --
Revision | b6f521170062a1fa8a82c33fb223b06fec566da1-refs/branch-heads/5672_63@{#10}
OS | Windows 10 Version 22H2 (Build 19045.2965)

### Steps:
1. installed `1.52.99`
2. launched Brave
3.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using 
```
Brave | 1.52.102 Chromium: 113.0.5672.126 (Official Build) beta (64-bit)
-- | --
Revision | c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}
OS | Windows 11 Version 22H2 (Build 22621.1702)
```
