### ISSUE TITLE
Remove transak assets not supported in US

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#29334]
Remove assets listed here: https://docs.google.com/spreadsheets/d/1if2bR-1ANdZ1-hNSE0NXHcfPutLEVBgszlc6cmS5AlQ/edit#gid=168038617

**Comment by kjozwiak** [comment]
The above requires `1.50.110` or higher for `1.50.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.50.110 Chromium: 112.0.5615.49 (Official Build) (64-bit)
-- | --
Revision | `bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}`
OS | Windows 11 Version 22H2 (Build 22621.1413)

- Verified tokens that only had Transak as provider is not shown in the asset list on Buy screen. 

https://user-images.githubusercontent.com/17010094/229089348-a3e283dc-666e-4c11-9223-b537b4dfe1d7.mp4
