### ISSUE TITLE
Update list of licenses for adblock lists

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#29346]
We need to ensure that all of the lists we use in https://github.com/brave/adblock-resources/tree/master/filter_lists are disclosed in `brave://credits`.

**Comment by fmarier** [comment]
The better way to solve this and ensure that the data is never out-of-date is to [move the licensing info to the component](https://github.com/brave/adblock-resources/issues/7).

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.51.77 Chromium: 112.0.5615.49 (Official Build) beta (x86_64)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | macOS Version 13.4 (Build 22F5027f)

### Steps:
1. installed `1.51.77`
2. launched Brave
3. opened `brave://credits`
4. scrolled down
5. searched for `blocklists`

#### Confirmed no errors, and the updated license content for `Blocklists Anti-porn list` and others, is in

<img width="1312" alt="Screenshot 2023-04-04 at 3 42 07 PM" src="https://user-images.githubusercontent.com/387249/229938529-c1930615-51ca-4bad-adaf-9de548d58bbe.png">

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.51.105`

- Verified the test plan from https://github.com/brave/brave-core/pull/17786

#### Confirmed no errors, and the updated license content for `Blocklists Anti-porn list` and others, is in
![Screenshot_20230427_165711](https://user-images.githubusercontent.com/38657976/234849234-51eb3771-2a00-45ca-a1f1-cc7ba53afb38.jpg)
