### ISSUE TITLE
Profile directory uses a huge amount of space when multiple NFT's are pinned

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#29356]
## Description 

Profile directory uses a huge amount of space when multiple NFT's are pinned

## Steps to Reproduce

   1. Create wallet and enable NFT pinning flag
   2. Add a bunch of NFT's and pin them 
   3. Check the size of the profile directory

## Actual result:

Profile directory uses a huge amount of space when multiple NFT's are pinned (found mine to be around 7.4 GB on a clean profile that had only NFT's pinned)

## Expected result:
Limit the size of the profile folder

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.50.106 Chromium: 112.0.5615.39 (Official Build) beta (64-bit)
-- | --
Revision | `a0e7b9718a92bcd1cf33b7c95316caff3fc20714-refs/branch-heads/5615@{#753}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @cypt4 @yrliou @jamesmudgett @bbondy

**Comment by josheleonard** [comment]
Closing. NFT pinning is no longer supported as of https://github.com/brave/brave-core/pull/23808
