### ISSUE TITLE
Disabling `Automatically pin NFTs` settings doesn't update the IPFS banner on portfolio/nft page

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#29354]
## Description 

Disabling `Automatically pin NFTs` settings doesn't update the IPFS banner on portfolio/nft page

## Steps to Reproduce

   1. Add an NFT and enable pinning 
   2. Go to `brave://settings/web3` and disable `Automatically pin NFTs` 
   3. Go back to wallet, IPFS pinning banner doesn't update from `You’re running IPFS node. File is being fetched to local IPFS node.` to IPFS pinning banner

## Actual result:

https://user-images.githubusercontent.com/17010094/228141727-371ebf5b-1915-41f5-9f6b-b3cefe844e0e.mp4

## Expected result:
Should update the banner when setting is disabled without requiring a page refresh

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.50.106 Chromium: 112.0.5615.39 (Official Build) beta (64-bit)
-- | --
Revision | `a0e7b9718a92bcd1cf33b7c95316caff3fc20714-refs/branch-heads/5615@{#753}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @muliswilliam @cypt4 @yrliou

**Comment by kjozwiak** [comment]
The above requires `1.51.95` or higher for `1.51.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.51.107 Chromium: 113.0.5672.63 (Official Build) (64-bit)
-- | --
Revision | 0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}
OS | Windows 11 Version 22H2 (Build 22621.1555)

- Verified steps from [brave/brave-core#17983](https://github.com/brave/brave-core/pull/17983)
- Verified disabling `Automatically pin NFTs` setting auto-updates the IPFS banner on Portfolio/NFT page

https://user-images.githubusercontent.com/17010094/235189445-3be825ef-dad6-49e1-828d-abf3112776cb.mp4
