### ISSUE TITLE
Added NFT's for pinning are not removed when a new wallet is restored

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#29357]
## Description 

Added NFT's for pinning are not removed when a new wallet is restored

## Steps to Reproduce

   1. Create a wallet and and enable NFT pinning flag
   2. Add a bunch of NFT's and pin them
   3. Lock Wallet and restore a different wallet from seed phrase
   4. All NFT's that are pinned before is still retained

## Actual result:

https://user-images.githubusercontent.com/17010094/228175636-76664b8a-8f00-4058-90b3-b97fa41005e2.mp4

## Expected result:
Should probably remove the NFT's pinned for that wallet

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.50.106 Chromium: 112.0.5615.39 (Official Build) beta (64-bit)
-- | --
Revision | `a0e7b9718a92bcd1cf33b7c95316caff3fc20714-refs/branch-heads/5615@{#753}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA 
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @jamesmudgett @cypt4 @yrliou

**Comment by josheleonard** [comment]
Closing since NFT pinning is no longer supported
