### ISSUE TITLE
Allow estore.htc.com to set 3p cookies for www.htcsense.com

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#2936]
See:
https://github.com/brave/browser-android-tabs/pull/961/files

We should add a 3p whitelist exception for 3p cookie blocking for 1p URL pattern
https://estore.htc.com/* to allow for https://www.htcsense.com/*

# Steps to reproduce

https://github.com/brave/browser-android-tabs/issues/964

**Comment by ryanbr** [comment]
We could possibly close this ticket, `https://estore.htc.com/` seems to be a dead domain, (and htcsense.com domain is also changed)  @bbondy

**Comment by bsclifton** [comment]
@ryanbr sounds good- I'll close it out 😄
