### ISSUE TITLE
30-day Ads History modal overflows (ad is too long)

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#29365]
## Description

![image](https://user-images.githubusercontent.com/11497541/231159135-600557a5-8244-4285-8e76-cd602a942450.png)

**Comment by Miyayes** [comment]
Similar: https://github.com/brave/brave-browser/issues/17179

**Comment by Miyayes** [comment]
Can even just make the modal bigger to accommodate.

**Comment by Miyayes** [comment]
@stephendonner Fixed image.

**Comment by Miyayes** [comment]
Similar: https://github.com/brave/brave-browser/issues/17179

**Comment by mkarolin** [comment]
@Miyayes is this still an issue? I see that https://github.com/brave/brave-browser/issues/27987 added the code to limit the text to 50 characters, so the long lines have ellipsis, for example:

<img src="https://github.com/brave/brave-browser/assets/41635752/a5932c45-6904-471c-a5f0-463f037afc90" height="50%" width="50%"/>

**Comment by mkarolin** [comment]
@Miyayes the limitation to 50 characters is for both the title and the description:

<image src="https://github.com/brave/brave-browser/assets/41635752/069f411d-83ed-457c-8b26-c6cde77aada8" width="50%" height="50%"/>

**Comment by mkarolin** [comment]
Oh I see, it doesn't account for the font width differences:

![image](https://github.com/brave/brave-browser/assets/41635752/90300a16-95fa-42d3-9a7b-787df4d84263)
