### ISSUE TITLE
Update playlist onboarding and warning copy

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#29362]
This issue is to update the playlist onboarding copy as below, 
![Screenshot_20230313-115330](https://user-images.githubusercontent.com/5146988/228237066-13f55796-4ef1-49f4-9320-fe79dd5294ae.png)
and warning copy as below,
![Screenshot_20230313-114802](https://user-images.githubusercontent.com/5146988/228237130-27141630-716a-4553-bfae-ea12677501d7.png)

**Comment by kjozwiak** [comment]
See context via https://github.com/brave/brave-browser/issues/30072#issue-1690337197 re: why this was labelled as `QA/No` & `release-notes/exclude`.
