### ISSUE TITLE
Accept-Language headers in service workers are missing a farbled weight

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#29372]
https://dev-pages.brave.software/fingerprinting/exceptions.html shows the issue

requests issued from service workers is missing a farbled weight value (i.e., the `q=.[0-9]`).

**Comment by pilgrim-brave** [comment]
Unable to reproduce this with latest local build. Perhaps this was fixed?
<img width="1712" alt="Screenshot 2023-06-02 at 11 09 47 AM" src="https://github.com/brave/brave-browser/assets/43750833/e9536f86-592b-4420-b310-584403932c77">

**Comment by pes10k** [comment]
I'm still seeing on 1.54.22

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.54.90 Chromium: 115.0.5790.56 (Official Build) beta (x86_64)
-- | --
Revision | ebcfb87c1393f36955cfa2f6451a1767e3dc3ee5-refs/branch-heads/5790@{#1193}
OS | macOS Version 14.0 (Build 23A5276g)

### Steps:
1. installed `1.54.90`
2. launched Brave
3. loaded `https://dev-pages.brave.software/fingerprinting/exceptions.html`
4. clicked `Start tests`
5. noted the values for `Service Workers` `Default fetch` were `en-US,en;q=0.7`
6. compared to `1.53.107`

### Confirmed the `Accept-Language` headers now have farbling weights, for `Service Workers`, as shown

### `https://dev-pages.brave.software/fingerprinting/exceptions.html`

`1.53.107` | `1.54.90`
-----------|---------
<img width="1676" alt="Screenshot 2023-07-03 at 4 07 13 PM" src="https://github.com/brave/brave-browser/assets/387249/14c0c569-2401-48e4-8ec8-3f7acc057cab"> | <img width="1312" alt="Screenshot 2023-07-03 at 4 07 55 PM" src="https://github.com/brave/brave-browser/assets/387249/1b410216-0560-4ddd-a873-5e5ba6233c5a">

### `https://dev-pages.bravesoftware.com/fingerprinting/exceptions.html`

`1.53.107` | `1.54.90`
-----------|---------
<img width="1669" alt="Screenshot 2023-07-03 at 4 18 51 PM" src="https://github.com/brave/brave-browser/assets/387249/e42c55c4-265a-423a-b361-e7529b1d488e"> | <img width="1312" alt="Screenshot 2023-07-03 at 4 17 10 PM" src="https://github.com/brave/brave-browser/assets/387249/ba0c756b-86cb-4f04-b304-8001a0768f5d">

**Comment by MadhaviSeelam** [comment]
Verifcation `PASSED` using
```
Brave | 1.57.41 Chromium: 115.0.5790.171 (Official Build) beta (64-bit)
-- | --
Revision | adc7e3e2defac3f9b39cb22bcbb354b72b74c2eb
OS | Windows 11 Version 22H2 (Build 22621.1992)
```


### Steps:
1. installed `1.57.41`
2. launched Brave
3. loaded `https://dev-pages.brave.software/fingerprinting/exceptions.html`
4. clicked `Start tests`
5. noted the values for `Service Workers` `Default fetch` were `en-US,en;q=0.7`
6. compared to `1.56.20`

### Confirmed the `Accept-Language` headers now have farbling weights, for `Service Workers`, as shown

### `https://dev-pages.brave.software/fingerprinting/exceptions.html`

`1.56.20` | `1.57.41`
----- | -----
<img width="639" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/43eccd07-d909-47db-82b6-b84fa9da42f9">|<img width="648" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/ec20d25e-4012-407c-b212-a6fa24fee0e9">

### `https://dev-pages.bravesoftware.com/fingerprinting/exceptions.html`

`1.56.20` | `1.57.41`
--------|---------
<img width="644" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/b116ff04-3c15-40e5-8625-bf9b43866fcf">|<img width="644" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/7acce9fa-f2ac-4fc4-b2ad-b9a48bf94670">
