### ISSUE TITLE
Download indicator shows progress for insecure download, before allowing to download

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#29376]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/28562
for insecure download, download indicator shows progress even before clicking `Continue download` button.  It appears to be chromium upstream issue.  

## Steps to Reproduce

1. installed 1.50.101
2. launched Brave
3. loaded https://www.thinkbroadband.com/download
4. context-clicked on http://ipv4.download.thinkbroadband.com:8080/1GB.zip
5. chose Save Link As...
6. clicked Save
7. clicked download button in the toolbar 

## Actual result:

Download indicator shows progress even before clicking blocked notification and clicking `Continue to download`

https://user-images.githubusercontent.com/98358127/228390382-4007cff7-416a-48af-a898-f63f838bfd3e.mp4

## Expected result:
Download should not be progressed for insecure download before clicking `Continue to download`

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.50.107 Chromium: 112.0.5615.39 (Official Build) beta (64-bit)
-- | --
Revision | a0e7b9718a92bcd1cf33b7c95316caff3fc20714-refs/branch-heads/5615@{#753}
OS | Windows 11 Version 22H2 (Build 22621.1413)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
@rebron @simonhong 
cc: @brave/qa-team

**Comment by stephendonner** [comment]
Also good for testing is https://www.leaseweb.com/platform/network just FYI in case it helps 👍

**Comment by stephendonner** [comment]
example | example | example | example | example
---------|----------|---------|----------|--------
<img width="1312" alt="Screen Shot 2023-03-29 at 10 46 36 AM" src="https://user-images.githubusercontent.com/387249/228624992-6c1b8311-6869-4dfc-b956-5262bc06d161.png"> | <img width="1312" alt="Screen Shot 2023-03-29 at 10 46 40 AM" src="https://user-images.githubusercontent.com/387249/228625019-bcc02d1c-2233-4b9d-9934-dc9e45371e82.png"> | <img width="1312" alt="Screen Shot 2023-03-29 at 10 46 42 AM" src="https://user-images.githubusercontent.com/387249/228625029-5caba78a-a86a-4e3e-8428-7d12a67751c8.png"> | <img width="1312" alt="Screen Shot 2023-03-29 at 10 46 46 AM" src="https://user-images.githubusercontent.com/387249/228625042-321e50cf-5c06-47b8-a6d1-854f73822985.png"> | <img width="1312" alt="Screen Shot 2023-03-29 at 10 48 17 AM" src="https://user-images.githubusercontent.com/387249/228625049-beb6a859-14ba-4106-b185-48eaff86689c.png">

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 


Brave | 1.52.85 Chromium: 113.0.5672.63 (Official Build) beta (64-bit)
-- | --
Revision | 0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}
OS | Windows 10 Version 22H2 (Build 19045.2913)

### Steps:
1. installed `1.52.85`
2. launched Brave
3. loaded `https://www.leaseweb.com/platform/network`
4. context-clicked on a `10,000 mb` file
5. chose `Save link as...`
6. clicked `Save` in the file picker
7. examined the `Downloads` button on the browser toolbar
8.
