### ISSUE TITLE
Discovered ERC-1155 tokens not showing balance

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#29375]
## Description 

Discovered `ERC-1155` tokens never load balances

## Steps to Reproduce

   1. Restore a wallet with a `ERC-1155` token
   2. Wait for it to be Discovered
   3. The balance never loads

## Actual result:

![Screenshot 14](https://user-images.githubusercontent.com/40611140/228390153-04744926-6078-4299-8431-879340f3637f.png)

## Expected result:
Should load a balance of `1`

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by yrliou** [comment]
Probably needs an UI side update to call GetERC1155TokenBalance when is_erc1155 is true, I'm guessing it's currently using other get balance API.

**Comment by yrliou** [comment]
Closing this as we have reverted the core PR via https://github.com/brave/brave-core/pull/17813, shouldn't see those being discovered anymore.

**Comment by yrliou** [comment]
cc @nvonpentz and @muliswilliam to make sure discovered ERC-1155 tokens will work as expected when adding ERC-1155 support on desktop frontend.
