### ISSUE TITLE
Update Wallet Desktop Layout

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#29377]
## Description 

Update the `Wallet` desktop to the new layout designs in Figma

![Screenshot 15](https://user-images.githubusercontent.com/40611140/228391111-ce0334ac-eaa1-4f00-9b93-5bbe71ab29db.png)

![Screenshot 16](https://user-images.githubusercontent.com/40611140/228391115-389a902b-cb45-4fae-b9e3-b97402ea7a92.png)

![Screenshot 17](https://user-images.githubusercontent.com/40611140/228391117-f82b3e40-b0a9-432f-a17d-357316f1632e.png)

![Screenshot 18](https://user-images.githubusercontent.com/40611140/228391118-577eb39a-61cb-4f9e-ab3e-8467b51ed62e.png)

![Screenshot 19](https://user-images.githubusercontent.com/40611140/228391121-bba7e959-3178-49cf-820b-72a045207ef8.png)

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.52.102 Chromium: 113.0.5672.126 (Official Build) beta (64-bit) 
-- | --
Revision | `c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}`
OS | Linux

- Verified steps from [brave/brave-core#17844](https://github.com/brave/brave-core/pull/17844)
- Verified desktop wallet has the new layout as per design
- Verified onboarding routes doesn't have the new design
- Verified all wallet routes works as expected 
- Verified `Send` and `Swap` has new background gradient
- Verified `Side navigation` routes work as expected 

https://github.com/brave/brave-browser/assets/17010094/7a7f494f-014f-4915-a7dc-ef74238ebcc9


---------------------

**Verification passed on**

Brave | 1.52.102 Chromium: 113.0.5672.126 (Official Build) beta (64-bit)
-- | --
Revision | `c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}`
OS | Windows 11 Version 22H2 (Build 22621.1702)

- Verified steps from [brave/brave-core#17844](https://github.com/brave/brave-core/pull/17844)
- Verified desktop wallet has the new layout as per design
- Verified onboarding routes doesn't have the new design
- Verified all wallet routes works as expected 
- Verified `Send` and `Swap` has new background gradient
- Verified `Side navigation` routes work as expected 

https://github.com/brave/brave-browser/assets/17010094/3449a347-b2f9-464e-a28c-0027c5aa9b64


---------------------

**Verification passed on**

Brave | 1.52.102 Chromium: 113.0.5672.126 (Official Build) beta (arm64)
-- | --
Revision | `c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#17844](https://github.com/brave/brave-core/pull/17844)
- Verified desktop wallet has the new layout as per design
- Verified onboarding routes doesn't have the new design
- Verified all wallet routes works as expected 
- Verified `Send` and `Swap` has new background gradient
- Verified `Side navigation` routes work as expected 

https://github.com/brave/brave-browser/assets/17010094/38a180fe-70d7-4ea3-8929-1e4ebedafcf3
