### ISSUE TITLE
[Shortcuts]: Integrate with the menus on OSX

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#29373]
Currently the source of truth for shortcuts is `GetAcceleratorList` in `accelerator_table.cc`. However, on OSX there is an additional source of truth: The menus

We should include the menu shortcuts in our list of defaults. 

Blocks https://github.com/brave/brave-browser/issues/354

**Comment by sangwoo108** [comment]
@fallaciousreasoning , I was wrong in a point. When we add a new shortcut to blank item, which is in global menu, it works.

**Comment by fallaciousreasoning** [comment]
Oh that's great news! I guess we should add all the default shortcuts from the menu to our list of default accelerators in `brave/browser/ui/commands/default_accelerators.h`

Thanks @sangwoo108!
