### ISSUE TITLE
Remove .888 TLD from supported UD Extensions

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#29371]
## Description 

ref: https://github.com/brave/security/issues/981

Mis-match between `kUDPattern` regex and `supportedUDExtensions` list (`.zil` in regex, `.888` in extensions): 

```
export const supportedUDExtensions = [
  '.crypto', '.x', '.nft', '.dao', '.wallet', '.888', '.blockchain', '.bitcoin']
```
https://github.com/brave/brave-core/blob/master/components/brave_wallet_ui/common/constants/domain-extensions.ts#L9

```
constexpr char kUDPattern[] =
    "(?:[a-z0-9-]+)\\.(?:crypto|x|nft|dao|wallet|blockchain|bitcoin|zil)";
```
https://github.com/brave/brave-core/blob/master/components/brave_wallet/browser/json_rpc_service.cc#L63

**Comment by yrliou** [comment]
cc @supermassive
