### ISSUE TITLE
"Brave Rewards" button in NTP background / NTPSI settings does not do anything

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#29389]
## Description

![image](https://user-images.githubusercontent.com/11497541/228615321-0319739b-b454-4eae-bf92-bb298c9047b6.png)

`1.51.54 Chromium: 112.0.5615.29 (Official Build) nightly (x86_64)`

When I click "Brave Rewards" button in NTPSI settings, nothing happens.

I am in the non-connected state.

**Comment by mkarolin** [comment]
QA Steps:
* Start the browser
* Open click on the Rewards icon and join the rewards, but do not connect to a custodian.
* Open a new tab page
* Click on the settings icon
* In the Background Image tab scroll down to the Show Sponsored Images toggle
* Click on Brave Rewards button
Expected result:
Rewards panel open up.

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on 

```
Brave | 1.50.120 Chromium: 112.0.5615.121 (Official Build) (64-bit)
-- | --
Revision | 39cc4e45904ae9f1741c4fbaa866e629c96f2268-refs/branch-heads/5615_51@{#8}
OS | Windows 10 Version 21H2 (Build 19044.2846)

```
- Verified the STR from the description and ensured that the click on `Brave Rewards` opens up the Rewards panel
![image](https://user-images.githubusercontent.com/38657976/232767963-f8a4c942-c024-422a-b393-80cfbc21d3d8.png)
