### ISSUE TITLE
Do not add non-verified Creators to Auto-Contribute list and remove related toggle

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#29393]
## Description

- [ ] Only add sites / channels to A-C list if Verified Creator
- [ ] Remove the toggle screenshotted below

![image](https://user-images.githubusercontent.com/11497541/228625642-568687b8-eb52-40e7-a91c-9f1dc5c9de6b.png)

cc: @LaurenWags Based on some discussion on Tip Banner 3.0 Demo call.

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.53.76 Chromium: 114.0.5735.90 (Official Build) beta (64-bit)
-- | --
Revision | 386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}
OS | Windows 10 Version 22H2 (Build 19045.2965)

```

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.53.83`
