### ISSUE TITLE
Group Policy - expose a way to disable Brave VPN

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#29397]
## Description 
Originally reported here:
https://github.com/brave/brave-browser/issues/26502#issuecomment-1483771581

Brave should have a new option to disable Brave VPN. `BraveVPNDisabled` - with 0 being default (enabled) and 1 being disabled

See https://support.brave.com/hc/en-us/articles/360039248271-Group-Policy for existing group policies

## Opens
Should this cover Android also? Android does support group policy. If it's easy enough, we can consider doing this for Android too (if so, add the `OS/Android` label)

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.52.92 Chromium: 113.0.5672.92 (Official Build) beta (x86_64)
-- | --
Revision | b6f521170062a1fa8a82c33fb223b06fec566da1-refs/branch-heads/5672_63@{#10}
OS | macOS Version 11.7.6 (Build 20G1231)

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.52.93 Chromium: 113.0.5672.92 (Official Build) beta (64-bit)
-- | --
Revision | b6f521170062a1fa8a82c33fb223b06fec566da1-refs/branch-heads/5672_63@{#10}
OS | Windows 10 Version 22H2 (Build 19045.2965)

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.52.102 Chromium: 113.0.5672.126 (Official Build) beta (64-bit)
-- | --
Revision | c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}
OS | Windows 11 Version 22H2 (Build 22621.1702)
```
### Case 1: Defaults
<details>

### Steps:

1. installed `1.52.102`
2. launched Brave
3. loaded `brave://flags`
4. clicked on the `VPN` button in the toolbar
5. loaded `brave://policy`
6. loaded `brave://version`

### Confirmed:
* `brave://flags/#brave-vpn` is set to `default`
* clicking on the `VPN` button opens the `Buy` / `Already purchased...?` dialog
* no active browser-management policies
* enrolled in `CrossPlatformVPNStudy:Enabled` (Griffin study)

`brave://flags` | `VPN` button/`Buy` dialog | `Brave VPN` menu item | `brave://policy` | `brave://version`
---------|---------|----------|---------|--------------------
<image width="500" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/0d6f1f80-9e8a-4590-8367-b1537aaacb8d">|<image width="500" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/ae7ea84c-e0e0-45b6-80fe-5d6276db1e89">|<image width="500" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/c7ef4e30-e523-40a3-88c0-3232b4986ef8">|<image width="500" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/ac8d509e-67c1-4166-83ab-2370a5e6236f">|<image width="500" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/d670e3b4-5252-4cae-aacc-31b6ca10eb42">

</details>

### Case 2: Enabling `BraveVPNDisabled` policy - `PASSED`
<details>

### Steps:
1. installed `1.52.93`
2. launched `Local Group Policy Editor`, and added an entry for `Brave`, per `https://support.brave.com/hc/en-us/articles/360039248271-Group-Policy`
3. launched `Registry Editor`, and added `BraveVPNDisabled` as a `DWORD` to `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\BraveSoftware\Brave`
4. launched Brave
5. loaded `brave://flags`
6. loaded `brave://settings/appearance`
7. loaded `brave://policy`
8. loaded `brave://version`

### Confirmed:
* `brave://flags/#brave-vpn` is set to `default`
* the `VPN` button has been removed/hidden
* top-level `Brave VPN` menu item is removed/hidden
* no `Show VPN button` toggle in `brave://settings/appearance`
* `brave://policy` shows `BraveVPNDisabled` set to `true`
* enrolled in `CrossPlatformVPNStudy:Enabled` (Griffin study)

`brave://flags` | `Local policy editor` | `Windows registry` | `No BraveVPN menu item/button` | `brave://settings/appearance` | `brave://policy` | `brave://version`
---------------|-----------------------|------------------|--------------------|-----------------|---------------------|-------------------
<image width="700" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/c5b451c4-c18e-4891-acd4-9db5c056f9b0">|<image width="700" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/5eb73b33-c878-4eab-b7b4-c77246a4443d">|<image width="700" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/90c17986-cd02-4e88-9c96-88751a56e6e0">|<image width="700" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/e3e2d676-18c4-4cb2-b00d-5e79ca8878ee">|<image width="200" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/b4996cb0-f672-4f89-bc9b-1b3c3e2bf1ee">|<image width="700" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/6cd5e976-679f-473d-95ed-3a71fd4843e5">|<image width="700" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/782169aa-19d5-410f-8e06-86877441e658">

</details>


### Case 3: Disabling `BraveVPNDisabled` policy - `PASSED`
<details>

### Steps:
(continued from n Case 2: `Enabling BraveVPNDisabled Policy`

1. opened `Registry Editor`
2. set `BraveVPNDisabled` in `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\BraveSoftware\Brave` to `0`
3. launched Brave
5. loaded `brave://flags`
6. loaded `brave://settings/appearance`
7. loaded `brave://policy`
9. loaded `brave://version`

### Confirmed:
* `brave://flags/#brave-vpn` is set to `default`
* the `VPN` button is present on the toolbar
* top-level `Brave VPN` menu item is present
* `Show VPN button` toggle is present in `brave://settings/appearance`
* clicking either of the above opens the `Buy`/`Already purchased...?` dialog
* enrolled in `CrossPlatformVPNStudy:Enabled` (Griffin study; mentioned only for completeness)

`brave://flags` | `Windows registry` | `VPN` button / `Buy` dialog | `Brave VPN` menu item |  `brave://settings/appearance` | `brave://policy` | `brave://version`
---------|---------|----------|---------------|-----------|-------------|---------------------
<image width="700" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/4e5a502a-d47f-464a-b3f9-def81e958716">|<image width="700" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/a4ca7ece-df6e-4792-b871-f69bfd49980a">|<image width="700" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/181c9abd-ec2a-4497-91ce-d0680bde6be3">|<image width="700" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/bbf93207-875e-4dd5-82e5-1fb46bfb4f65">|<image width="700" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/874c7032-1663-49e9-89be-e3f3e1046ab7">|<image width="700" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/ce893a93-dd27-4100-8af8-07a162b4c835">|<image width="700" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/c73f9042-b429-4b95-a2dc-72dd90aae0dd">
</details>

### Case 4: Removing `BraveVPNDisabled` policy completely - `PASSED`
<details>

### Steps:
(continued from Case 3 `Disabling BraveVPNDisabled Policy` 

Steps:
1. opened `Registry Editor`
2. context-clicked on `BraveVPNDisabled` in `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\BraveSoftware\Brave`
3. chose `Delete`
4. clicked `Yes` in the next dialog
5. opened `brave://flags`
6. opened `brave://settings/appearance`
7. opened `brave://policy`
8. opened `brave://version`

### Confirmed:
* `brave://flags/#brave-vpn` is set to `default`
* clicking on the `VPN` button opens the `Buy` / `Already purchased...?` dialog
* `Show VPN button` toggle is present in `brave://settings/appearance`
* no active browser-management policies listed in `brave://policy`
* enrolled in `CrossPlatformVPNStudy:Enabled` (Griffin study)

### `Windows registry`

example | example | example
----------|----------|---------
![image](https://github.com/brave/brave-browser/assets/98358127/bff63bb5-71ce-4ec5-9b4a-067bf06f12d2)|![image](https://github.com/brave/brave-browser/assets/98358127/d3084d45-e1f8-48d3-a7c0-99ee02133eb0)|![image](https://github.com/brave/brave-browser/assets/98358127/6fbeeae1-dbda-41bb-8738-ebf4aa6e0480)


`brave://flags` | `Brave VPN` button / `Buy` dialog | `Brave VPN` menu item | `brave://settings/appearance` | `brave://policy` | `brave://version`
---------|---------|----------|---------|-----------|---------------
![image](https://github.com/brave/brave-browser/assets/98358127/3910aff3-6059-4d44-90a4-6e6e699b37cd)|![image](https://github.com/brave/brave-browser/assets/98358127/13cb6665-dc74-447f-9492-9e56ca64eb83)|![image](https://github.com/brave/brave-browser/assets/98358127/9f5aae78-36de-4018-94bf-119ddbc3276e)|![image](https://github.com/brave/brave-browser/assets/98358127/11f27309-7469-4e4c-8b11-ac36eed3b42a)|![image](https://github.com/brave/brave-browser/assets/98358127/76c2d4eb-9aff-42a2-a6af-b59631e9465b)|![image](https://github.com/brave/brave-browser/assets/98358127/17313d8d-979f-4e97-bc0c-f91b36b285e7)

</details>

**Comment by bsclifton** [comment]
Removed `OS/Android` label because disabling group policy doesn't turn off in-app-purchases (will disable the render frame observer code, used for linking receipt)
