### ISSUE TITLE
Allow to change New Tab Background based on theme from Chrome Web Store

### ISSUE THREAD

**Issue by dpthegrey** [brave/brave-browser#29409]
## Description 

When a new theme is installed from [Chrome Web Store](https://chrome.google.com/webstore/category/themes), Make `Brave Browser` **change** `New Tab` page **based on the theme background**.

## Steps to Reproduce

   1. Install theme from Chrome Web Store
   2. Open New tab

## Actual result:

![image](https://user-images.githubusercontent.com/49444980/228829032-7eb26e68-cbd3-4d2c-a862-8bdeffe19667.png)

Currently there is only option to change background based on 4 options
1. Use your own
2. Brave Backgrounds
3. Solid colours
4. Gradients

## Expected result:
Expected some way to use the background based on the theme. like this image

![image](https://user-images.githubusercontent.com/49444980/228828706-0d8ac78c-1d5a-4734-8cdd-20a41f8dd3df.png)
![image](https://user-images.githubusercontent.com/49444980/228828848-bfc8fea3-416c-4b94-bbd6-cf7abd53179e.png)
![image](https://user-images.githubusercontent.com/49444980/228833595-33ef8192-70ce-4b28-8baf-5bf886373345.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Version 1.49.132 Chromium: 111.0.5563.147 (Official Build) (x86_64)

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? Chrome has this by default

## Miscellaneous Information:

These themes does have really nice backgrounds and sometimes it is hard to find it separately to set it manually, I wish there was a native way to adopt background which theme uses.

**Comment by bsclifton** [comment]
Chrome is displaying the brave://new-tab-page - which we don't support and have an issue for removing
https://github.com/brave/brave-browser/issues/10676

cc: @rebron

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/34304
