### ISSUE TITLE
Enable OnDemand when creating VPN config for macOS

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#29406]
## Description 
When folks are using VPN on macOS and have the computer asleep, the VPN is dropping and not automatically reconnecting when they come back.  We can make use of a feature called on-demand to get this working how folks would expect.

Here's an example that was shared with us:
https://github.com/GuardianFirewall/GuardianConnect/blob/3f0b9e6d588c986a4b8cdc204e8e9d0f142eada4/GuardianConnect/Classes/GRDVPNHelper.m#L751-L761

## Steps to Reproduce

   1. Have VPN on macOS (purchased, configured, etc)
   2. Connect to VPN
   3. Put computer to sleep for ~5 mins
   4. Wake computer up

## Actual result:
VPN doesn't reconnect automatically

## Expected result:
It should reconnect automatically

**Comment by simonhong** [comment]
Added `design/needs-mock-up` to have toggle option for onDemand feature. cc @rebron

**Comment by bsclifton** [comment]
I'm not sure we want this, after all consideration. It causes some problems on iOS, especially if WiFi is lost and it tries to connect before WiFi reconnects.

We might try to promote the WireGuard work (under way) on as the solution for having the VPN stay always on. The OS specific settings can be tricky.

I'm going to close as `wontfix` for now - but we can re-open if we want the system VPN to have this behavior

**Comment by bsclifton** [comment]
Re-opening after some discussion

**Comment by Brave-Matt** [comment]
I have had several users reach out via Zendesk about this — expecting the VPN to stay enabled while they are away from the computer/computer is put to sleep etc.

**Comment by aguscruiz** [comment]
Adding design here and Figma link

https://www.figma.com/file/qtMYwoj3JWJO5xzwLt6j2f/Desktop-VPN?type=design&node-id=28%3A12100&mode=design&t=GKpLyjJT4sKoJFfS-1

![image](https://github.com/brave/brave-browser/assets/15734630/7d9c4475-afa8-42c1-81d2-ec557f2241b2)

**Comment by simonhong** [comment]
Working on this. Do we want to turn off by default? @bsclifton  @rebron @mattmcalister

**Comment by bsclifton** [comment]
@simonhong yes - it's very important to have OFF by default

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using

```
Brave	1.65.87 Chromium: 123.0.6312.46 (Official Build) beta (x86_64) 
Revision	2babfcf82ebba4c5dc0146d2ca66229ffd3ac02d
OS	macOS Version 11.7.10 (Build 20G1427)
```

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using

```


```

### Steps:
1. installed `1.65.87`
2. launched Brave
3. purchased and configured `Brave VPN`
4. clicked on the `VPN` button in the browser toolbar
5. clicked on the `Settings` icon in the `VPN`-button's dialog
6. confirmed `Reconnect automatically` was defaulted to `Off`/`Disabled`
7. clicked to enable `Reconnect automatically`
8. connected to `Brave VPN`
9. confirmed connected
10. restarted `macOS`
11. without launching Brave, confirmed I was connected to `Brave VPN`
12. clicked on the `VPN` button in the browser toolbar
13. clicked on the `Settings` icon
14. toggled `Reconnect automatically` to `Off`/`Disabled`
15. confirmed `Brave VPN` is still connected
16. clicked again on the `VPN` button in the browser toolbar
17. clicked on `Settings`
18. toggled `Reconnect automatically` to `On`/`Enabled`
19. restarted `macOS`


### Confirmed upon restart, `Brave VPN` is still connected

example | `Step 6` | `Step 7` | `Step 11`
---------|---------|----------|---------


`Step 14` | `Step 15` | `Step 18` | example | example
---------|----------|----------|---------|---------
