### ISSUE TITLE
Use 'mint address' rather than 'contract' when referring to Solana NFTs in UI

### ISSUE THREAD

**Issue by nvonpentz** [brave/brave-browser#29401]
Also, some token information is cut off per https://bravesoftware.slack.com/archives/C02HSD2FUQJ/p1680127455969099?thread_ts=1679956644.595699&cid=C02HSD2FUQJ.

**Comment by srirambv** [comment]
Dupe of #29008

**Comment by muliswilliam** [comment]
@srirambv Can I close this because is a duplicate of #29008 ?

**Comment by srirambv** [comment]
Yup. Closing it a dupe
