### ISSUE TITLE
[Android] Rewards buttons to link custodians are not functioning when engaged with, and BAT icon in url bar not responsive

### ISSUE THREAD

**Issue by lukemulks** [brave/brave-browser#29403]
## Description 
When I attempt to link my Gemini account to Brave://Rewards on Android, both custodial account buttons are not functioning correctly. 
The buttons are responsive when tapped, but do not navigate to the custodial partner to link the account when engaged with. 

## Steps to reproduce 

   1. On Android, go to brave://rewards 
   2. Click to connect custodial account on either option. 
   3. Buttons respond, but do not navigate to custodial partner to link account. 
   
For bat icon being unresponsive in url bar, try tapping on the icon. 

## Actual result 
Video of bat icon in url bar being unresponsive: 

https://user-images.githubusercontent.com/8979240/228725230-93327946-ab2d-4dc1-bdbd-71602422f58c.mp4

Video of custodial account buttons not navigating to partner sites when engaged with: 

https://user-images.githubusercontent.com/8979240/228725738-a69650cd-0a1c-44e4-b3b2-7b097b063195.mp4

Note: I am on a Samsung Fold3 phone, and have attempted this for both items above in folded and unfolded mode, and am encountering the same issue from both screen modes. 

## Expected result
buttons should work 

## Version/Channel Information:
 tbd

- Can you reproduce this issue with the current Play Store version? Yes v1.49.429
- Can you reproduce this issue with the current Play Store Beta version? Tbd
- Can you reproduce this issue with the current Play Store Nightly version? Tbd

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet): Samsung Fold3 
   - Android version:
   
## Brave version
1.49.429

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? Na
- Does the issue resolve itself when disabling Brave Rewards? Na
- Is the issue reproducible on the latest version of Chrome? Na

### Additional information

Cc: @Miyayes and @anthonypkeane - I am hoping my case is an anomaly, but we should look into this as a priority because this breaks the ability to earn BAT.

**Comment by Miyayes** [comment]
Possibly related to https://github.com/brave/brave-browser/issues/21057? @lukemulks will help confirm with his brave://rewards-internals while this issue is actively occurring.

**Comment by Miyayes** [comment]
Continuing to assume it is https://github.com/brave/brave-browser/issues/21057. Workaround for now is an app restart. We also merged in some code that might make mitigate this issue and make it less likely.
