### ISSUE TITLE
Sync'd bookmarks doesn't retain favicon, adds it when the bookmark is loaded 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#2941]
## Description 

Sync'd bookmarks doesn't retain favicon, adds it when the bookmark is loaded 

## Steps to Reproduce

   1. Create sync chain and add two devices to it
   2. Import bookmarks file on device 1
   3. Wait till it sync's over to device 2, doesn't show any favicon, just has generic file icon

## Actual result:

Sync'd bookmarks doesn't retain favicon, adds it when the bookmark is loaded 

## Expected result:
Should sync favicons as well

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.59.21 Chromium: 72.0.3626.28 (Official Build) beta (64-bit)
-- | --
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | All

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes on beta

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
No
- Is the issue reproducible on the latest version of Chrome? 
No

**Comment by rebron** [comment]
I'll check to see if this behavior with Chrome sync/Firefox sync?

**Comment by rebron** [comment]
This works properly with Chrome and Firfeox bookmark sync and favicons are imported over without having to visit each site.

**Comment by jsecretan** [comment]
Specifically tested this out on sync v2 and saw it working.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.12.102 Chromium: 84.0.4147.89 (Official Build) dev (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | Ubuntu 18.04 LTS

Added Bookmark after sync:
![image](https://user-images.githubusercontent.com/34715963/88586918-701d7e00-d055-11ea-9318-1b47fcaf2137.png)

Verified icon is synced when Bookmark was imported before sync chain
Verified icon is synced when Bookmark was imported after sync chain
Bookmarks used: 
[bookmarks_interia.html.txt](https://github.com/brave/brave-browser/files/4984254/bookmarks_interia.html.txt)

**Comment by srirambv** [comment]
Verification passed on OnePlus 6T and Samsung Tab A with Android 10 running 1.12.111 x63 build
- Verified bookmarks favicons is sync'd on all devices

**Desktop bookmarks**

Desktop | OnePlus 6T | Samsung Tab A 
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/89876114-1de06f00-dbb6-11ea-911e-a1fb9355f0d4.png)| ![image](https://user-images.githubusercontent.com/17010094/89876057-073a1800-dbb6-11ea-8896-3aff837a78eb.png) | ![image](https://user-images.githubusercontent.com/17010094/89876069-0d2ff900-dbb6-11ea-9964-7b815aa4dcd5.png)

**Mobile Bookmarks**

Desktop | OnePlus 6T | Samsung Tab A 
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/89876165-2f297b80-dbb6-11ea-8792-80a38a8c8f7a.png) | ![image](https://user-images.githubusercontent.com/17010094/89876178-33ee2f80-dbb6-11ea-9ec8-9322d7081899.png) | ![image](https://user-images.githubusercontent.com/17010094/89876211-3f415b00-dbb6-11ea-98bf-45461544ed01.png)
