### ISSUE TITLE
Audio continues in background after removing item from playlist

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#29417]
## Description 
Video plays in background after removing from playlist

## Steps to reproduce 

   1. Install 1.52.2
   2. Enable playlist via `brave://flags#playlist`
   3. Navigate to youtube.com
   4. Add video to playlist, open playlist
   5. Begin playing video in play
   6. Press back with pausing
   7. Remove item from the playlist
   8. Close tabs
  

## Actual result 
playback continues in background

## Expected result
Playback should end when removing playlist item

## Issue reproduces how often 
Easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? No
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung GS 21
   - Android version: 13
   
## Brave version
1.52.2

**Comment by kjozwiak** [comment]
As discussed with @deeppandya via https://bravesoftware.slack.com/archives/C03MMJ4CHEZ/p1686260940735599, this issue will be added into the `master` playlist PR. This way the above won't be missed and will be verified. Reasoning is that the above code landed in `1.53.x` so the issue should stay in `1.53.x` and shouldn't be moved into other milestones.
