### ISSUE TITLE
(Wallet) Refactor visible asset list

### ISSUE THREAD

**Issue by simoarpe** [brave/brave-browser#29412]
## Description 

Performs refactoring to improve visible asset list of `EditVisibleAssetsBottomSheetDialogFragment`.
The fragment `EditVisibleAssetsBottomSheetDialogFragment` has different entry points and shows a list containing coins and NFTs.

When `EditVisibleAssetsBottomSheetDialogFragment` is shown from `PortfolioFragment` it should display all non-NFT tokens (including native assets).

When `EditVisibleAssetsBottomSheetDialogFragment` is shown from `NftFragment` it should display only NFT tokens (excluding native assets).

![Screenshot_1680182030](https://user-images.githubusercontent.com/3308503/228847499-a76f8337-6593-43b6-9d2c-f0db1c39640d.png)

**Comment by srirambv** [comment]
Verification passed the following devices running 1.52.92 x64 build
- Verified steps from [brave/brave-core#17840](https://github.com/brave/brave-core/pull/17840)
- Verified NFT's are not listed under `Edit visible asset` lists
- Verified tokens are not listed under `Edit visible NFTs` 
- Encountered [#30259](https://github.com/brave/brave-browser/issues/30259)

Oppo Reno 5 (Android 13) | Lenovo Tab (Android 12)
-- | --
<video src=https://github.com/brave/brave-browser/assets/17010094/22e15a0e-a420-4862-9d7a-63bc39b2718e> | <video src=https://github.com/brave/brave-browser/assets/17010094/99d59737-5647-4abf-9ba3-e206e27937b3>
