### ISSUE TITLE
Item can be added to the playlist multiple times on YT

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#29418]
## Description 
Same item can be added to the playlist multiple times

## Steps to reproduce 

   1. Install 1.52.2
   2. Enable playlist via brave://flags#playlist
   3. Navigate to  youtube.com
   4. Begin playing a video
   5. Add item to playlist using the icon
   6. Open playlist
   7. Press back button to exit playlist
   8. Add item again to playlist

## Actual result 
<img width="500" alt="1" src="https://user-images.githubusercontent.com/17885425/228891266-edad5425-7bbf-450e-b359-fb9afb0282ab.png">

## Expected result
Once video is added to playlist, user should not see `Add Media` in the playlist menu

## Issue reproduces how often 
Easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? No
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung GS 21
   - Android version: 13
   
## Brave version
`1.52.2, Chromium 112.0.5615.39`

**Comment by peize-li123** [comment]
This is an interesting one! Working on it!

**Comment by kjozwiak** [comment]
After speaking with @deeppandya @Uni-verse @hffvld, we'll leave the above in `1.63.x` but label the issue as `QA/No` as `Playlist` has been moved from `1.63.x` -> `1.64.x`. @deeppandya mentioned that we'll have a `master` issue via `1.64.x` that will list all the `QA/Yes` issues that have been in the various milestones before `1.64.x`. This way QA will have a list of past `QA/Yes` issues that need to be checked/verified.
