### ISSUE TITLE
Content section at top of playlist only displays first item in list

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#29422]
## Description 
Content section at top of playlist only displays first item in list

## Steps to reproduce 

1. Install 1.52.2
2. Enable playlist via brave://flags#playlist
3. Navigate to youtube.com
4. Begin playing a video
5. Add item to playlist using the icon
6. Open playlist
7. Press back button to exit playlist
8. Add another video to playlist
9. Open playlist again
10. Play second item in the list 

## Actual result 
<img width="500" alt="1" src="https://user-images.githubusercontent.com/17885425/228895719-51e5b517-6f6b-4094-bd23-68fb6bc603af.png">

## Expected result
Should show cover graphic for current item playing

## Issue reproduces how often 
Easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No 
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung GS 21
   - Android version: 13
   
## Brave version
`1.52.2, Chromium 112.0.5615.39`

**Comment by deeppandya** [comment]
@Uni-verse this is expected as we show the first item's thumbnail as cover for the playlist.

**Comment by deeppandya** [comment]
Closing this issue as it's not relevant at this time.
