### ISSUE TITLE
Outdated install dialog loads chrome install url

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#2942]
## Description 

When trying to install via outdated dialog, it loads chrome's install url.

When update is outdated, out dated menu is visible in app menu.
![screen shot 2019-01-14 at 13 29 33](https://user-images.githubusercontent.com/6786187/51096541-7bf17880-1800-11e9-9ce0-a2ba65568464.png)

When click menu item in app menu, below outdated dialog is launched.
![screen shot 2019-01-14 at 13 28 12](https://user-images.githubusercontent.com/6786187/51096545-814ec300-1800-11e9-9214-afb00bc19119.png)

When click `Reinstall Brave` button, it loads chrome's install url.

## Steps to Reproduce

   1. Launch browser with `yarn start --simulate-outdated`
   2. Click top menu of app menu
   3. Click `Reinstall Brave` button in launched dialog

## Actual result:

chrome install url is loaded

## Expected result:
brave install url is loaded

## Reproduces how often: 

Always

## Brave version (brave://version info)

0.58.21 Chromium: 71.0.3578.98

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome?  No

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.61.37 Chromium: 73.0.3683.39 (Official Build) beta (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

Used test plan from the description.
Used `--simulate-outdated` flag.
Verified that `https://www.brave.com/download` is opened after clicking `Reinstall Brave`
