### ISSUE TITLE
Playlist icon is still showing after closing all tabs

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#29420]
## Description 
Playlist icon is showing after closing all tabs

## Steps to reproduce 

   1. Enable playlist via brave://flags
   2. Open youtube.com
   3. Play a video
   4. Confirm playlist icon is shown
   5. Now, close this tab

## Actual result 
Icon is shown 
<img width="500" alt="1" src="https://user-images.githubusercontent.com/17885425/228894108-aec12225-21db-41a3-bb80-7fab16db18fd.png">

## Expected result
Should not be shown after closing the associated tab

## Issue reproduces how often 
Easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? No
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung GS 21 
   - Android version: 13
   
## Brave version
`1.52.2, Chromium 112.0.5615.39`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
As discussed with @deeppandya via https://bravesoftware.slack.com/archives/C03MMJ4CHEZ/p1686260940735599, this issue will be added into the `master` playlist PR. This way the above won't be missed and will be verified. Reasoning is that the above code landed in `1.53.x` so the issue should stay in `1.53.x` and shouldn't be moved into other milestones.
