### ISSUE TITLE
Playlist icon disappears when opening new tab

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#29423]
## Description 
Playlist icon disappears when opening new tab and then returning to the tab playing the video

## Steps to reproduce 

1. Install 1.52.2
2. Enable playlist via brave://flags#playlist
3. Navigate to youtube.com
4. Begin playing a video
5. Use tab tray to open new tab
6. Return to tab that has the video loaded

## Actual result 

https://user-images.githubusercontent.com/17885425/228898407-a8fc5ffb-ea12-4b24-9e8e-4cf4946376f0.mp4

## Expected result
Playlist icon should be shown

## Issue reproduces how often 
Easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? No
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung GS 21
   - Android version: 13
   
## Brave version
`1.52.2, Chromium 112.0.5615.39`

**Comment by deeppandya** [comment]
@Uni-verse this issue is tricky as we need to load the page to run the script to get the content. and we need to remove the playlist icon as we leave the page. i will look into it.

**Comment by kjozwiak** [comment]
As discussed with @deeppandya via https://bravesoftware.slack.com/archives/C03MMJ4CHEZ/p1686260940735599, this issue will be added into the `master` playlist PR. This way the above won't be missed and will be verified. Reasoning is that the above code landed in `1.53.x` so the issue should stay in `1.53.x` and shouldn't be moved into other milestones.
