### ISSUE TITLE
Consecutive Items do not show up in the playlist the first time [intermittent]

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#29424]
## Description 
Item does not show up in playlist after opening first time, it will show up after opening playlist again. 

## Steps to reproduce 

1. Clean Install 1.52.2
2. Enable playlist via brave://flags#playlist
3. Navigate to youtube.com
4. Begin playing a video
5. Add item to playlist using the icon
6. Open playlist
7. Press back button
8. Add another video
9. Open playlist again

## Actual result 
Sometimes the item does not show up in the playlist the first time user opens it

https://user-images.githubusercontent.com/17885425/228901365-15a951dc-2f6f-4f5d-8d7b-c45f01a9de1e.mp4

## Expected result
Should show up

## Issue reproduces how often 
`Intermittent`

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? No
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): `Samsung GS 21`
   - Android version: 13
   
## Brave version
`1.52.2, Chromium 112.0.5615.39`

**Comment by deeppandya** [comment]
@Uni-verse it happens because of the time it takes to add an item to the playlist.

**Comment by kjozwiak** [comment]
As discussed with @deeppandya via https://bravesoftware.slack.com/archives/C03MMJ4CHEZ/p1686260940735599, this issue will be added into the `master` playlist PR. This way the above won't be missed and will be verified. Reasoning is that the above code landed in `1.53.x` so the issue should stay in `1.53.x` and shouldn't be moved into other milestones.
