### ISSUE TITLE
Can't hide video-control when tapping on the screen in Fullscreen on Playlist for Android

### ISSUE THREAD

**Issue by Sayum24** [brave/brave-browser#29439]
## Description 
When clicking on the screen the video-control icons which are in the middle of the screen don't hide.
They seem to hide after 4/ 5 seconds automatically.

## Steps to reproduce 

   1. Watch a video in Brave-Playlist in Fullscreen
   2. click on the video to hide video-controls

## Actual result 
nothing happens, video-controls hide after about 5 seconds

## Expected result
controls should hide when tapped on the screen

## Issue reproduces how often 
happens always.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
 Android 12; Build/SP1A.210812.016
   
## Brave version
Brave - Nightly 1.52.5, Chromium 112.0.5615.49

**Comment by kjozwiak** [comment]
> > @deeppandya reopening this one. This is still not working for me. I tap the screen, the controls do not hide. The controls auto hide 5/6 seconds after.
> 
> @timchilds we usually don't re-open issues that already have code associated with it merged into a milestone. For example, [brave/brave-core#18333](https://github.com/brave/brave-core/pull/18333) is currently in `1.56.x` but [brave/brave-core#18879](https://github.com/brave/brave-core/pull/18879) which looks like @deeppandya is working on will be in another milestone. So now we have an issue that is associated with two different fixes in two different milestones.
> 
> Going to close this one off and create a follow up. Labelling as `QA/No` as this one is a playlist which we're not verifying till we get the new version of it landed in Nightly. I'll update [brave/brave-core#18879 (comment)](https://github.com/brave/brave-core/pull/18879#issue-1754411766) as well and edit the issue number and remove this one.

Created https://github.com/brave/brave-browser/issues/31716 as mentioned above.
