### ISSUE TITLE
Tab hover glow effect in dark mode is too strong 

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#29436]
![image](https://user-images.githubusercontent.com/5474642/229020112-fbcb0dd0-e581-43e3-8f7e-833aaad31d99.png)

**Comment by kjozwiak** [comment]
The above requires `1.51.86` or higher for `1.51.x` verification 👍

**Comment by stephendonner** [comment]
## Verification `PASSED` using 

Brave | 1.51.86 Chromium: 112.0.5615.49 (Official Build) beta (x86_64)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | macOS Version 11.7.6 (Build 20G1231)

### Steps:
1. installed `1.51.86`
2. launched Brave
3. opened `brave://flags`
4. set `brave://flags/#brave-vertical-tabs` to `Enabled`
5. clicked `Relaunch`
6. loaded `brave.com`
7. loaded `mozilla.org`
8. context-clicked on the `brave.com` tab
9. chose `Use Vertical Tabs`
10. set `Brave colors` in `brave://settings/appearance` to `Dark`
11. hovered over the tabs

#### Confirmed a much lighter, but still noticeable highlight effect on hover

`default` | `on hover`
---------|---------
<img width="1378" alt="Screen Shot 2023-04-12 at 9 37 57 AM" src="https://user-images.githubusercontent.com/387249/231524377-1cd5bd28-350b-4dbd-9ddb-7fe73bb6063a.png"> | <img width="1378" alt="Screen Shot 2023-04-12 at 9 38 26 AM" src="https://user-images.githubusercontent.com/387249/231524475-86fdc900-76b8-4766-992a-1bb701b94b7a.png">
