### ISSUE TITLE
Still can use video time-slider when opening menu 'Play Later' in Brave Playlist

### ISSUE THREAD

**Issue by Sayum24** [brave/brave-browser#29442]
## Description 
When watching a video in Playlist and looking at the menu 'Play Later' (appears when you watch video in vertical mode and scrolling from the bottom up) you can still move the time-slider of the video when only 1 item is in the playlist.

## Steps to reproduce 

   1. Watch a video in Brave-Playlist (not in fullscreen)
   2. expand the 'Play Later' menu
   3. try moving the time-slider of the current video

## Actual result 
the timeslider gets dragged to the desired time in the video
![image](https://user-images.githubusercontent.com/65895765/229132163-4ae67c5d-c4ab-4077-ab7a-000a221f8f5c.png)

## Expected result
Nothing should happen or the Play Later menu should minimize

## Issue reproduces how often 
happens always.

## Device details
 - Android 12; Build/SP1A.210812.016
 - device: realme 8 (RMX3085_11)
   
## Brave version
Brave - Nightly 1.52.5, Chromium 112.0.5615.49

**Comment by kjozwiak** [comment]
As discussed with @deeppandya via https://bravesoftware.slack.com/archives/C03MMJ4CHEZ/p1686260940735599, this issue will be added into the `master` playlist PR. This way the above won't be missed and will be verified. Reasoning is that the above code landed in `1.53.x` so the issue should stay in `1.53.x` and shouldn't be moved into other milestones.
