### ISSUE TITLE
Remove "Ready to start earning?" modal and update custodial selection modal

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#29448]
## Description

Consolidate these two modals into a single step (keep the custodial selection modal).

On the custodial selection modal:

(1) Remove "If you already have..." paragraph

(2) Add these bullet points:
![image](https://user-images.githubusercontent.com/11497541/229178025-79ba110a-494c-42c2-8359-30e616660645.png)

But change "Tip your favorite..." to "Send on-demand contributions to..."

(3) Modify disclaimer at bottom to say: 

>Custodial account providers are required to verify your identity, which may include submitting a photo ID. See the [Brave Rewards Privacy Policy.](https://brave.com/privacy/#rewards) See here to [learn more about BAT.](https://brave.com/rewards)

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.52.86 Chromium: 113.0.5672.77 (Official Build) beta (x86_64)
-- | --
Revision | c4236862955e005c2187105415ac4a2ecf86dff1-refs/branch-heads/5672_62@{#3}
OS | macOS Version 13.3.1 (Build 22E261)
```

**Comment by vlad-hoff** [comment]
Verified on `Google Pixel 7` using version(s):
```
Device/OS: Google Pixel 7 [panther_beta-user 14 UPB2.230407.014 release-keys]
Brave build: 1.52.110
Chromium: 114.0.5735.35 (Official Build) (64-bit)
Revision: 7429f911c043513bd013a56876f67313d91dcbfd-refs/branch-heads/5672_132@{#8}
```
---------------------------

**STEPS:**
1. Clean profile
2. Enable Rewards > Select country
3. Tap `Connect account` button in Rewards panel

**ACTUAL RESULTS:**
- Verified that Connect modal looks/behaves as described in issue

<details>
<summary> 2 custodians available (US) - PASSED </summary>

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/172f3714-efed-4880-baf9-19475b186422) | ![2](https://github.com/brave/brave-browser/assets/128532965/620985b2-ec36-41b7-a76b-6fded24cf66d) |
</details>

<details>
<summary> Uphold custodian available, Gemini unavailable (India) - PASSED </summary>

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/57aa0450-80fd-40c3-842e-53176b613c70) | ![2](https://github.com/brave/brave-browser/assets/128532965/562e1fe1-29ae-4dce-8632-90c6ce35d861) |
</details>

<details>
<summary> Only 1 custodian (bitFlyer) available (Japan) - PASSED </summary>

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/8260a59a-4e22-4d64-a38b-353398680284) | ![2](https://github.com/brave/brave-browser/assets/128532965/b537527d-28e3-4347-b1fe-4ba58cd8fcea) |
</details>
