### ISSUE TITLE
(Wallet) Integrate multichain support for NFT grid

### ISSUE THREAD

**Issue by simoarpe** [brave/brave-browser#29444]
## Description 

Integrates multichain support for NFT grid screen.

### Other changes:

* Adds network icons to the lower right side for NFT items shown in the grid.
* Includes plus icon as a menu action button in the toolbar to open dialog for adding new NFTs.
* Improves custom assets dialog.
* Improves loading spinner behavior.
* Addresses [comment #1150817680](https://github.com/brave/brave-core/pull/17797#discussion_r1150817680). 
* Addresses [comment #1151711434](https://github.com/brave/brave-core/pull/17796/files#r1151711434).
* Makes loading placeholder not circular.
* Improves algorithm to center letters in the blockies.
* Improves `ImageLoader` by switching in favor of `RequestManager` and preventing illegal argument exceptions.
* Shows token name + ID in the title, and NFT symbol in the subtitle for both screens: NFT grid, and NFT details

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.52.92 x64 beta build
- Verified steps from [brave/brave-core#17967](https://github.com/brave/brave-core/pull/17967)
- Verified can filter NFTs based on network
- Verified when adding an NFT, Add button is only enabled when token id is specified
- Encountered [#30273](https://github.com/brave/brave-browser/issues/30273) & [#30274](https://github.com/brave/brave-browser/issues/30274)

Oppo Reno 5 (Android 13) | Lenovo Tab (Android 12)
-- | --
<video src=https://github.com/brave/brave-browser/assets/17010094/b1f56498-2eb8-46df-9d0a-fc7bbcda173c> | <video src=https://github.com/brave/brave-browser/assets/17010094/efb85423-ffc5-4c07-b15b-e9891662184b>
