### ISSUE TITLE
Device dimms after some time while watching a video in Android Playlist

### ISSUE THREAD

**Issue by Sayum24** [brave/brave-browser#29440]
## Description 
When watching a video in Playlist. The screen dimms the brightness after some time.

## Steps to reproduce 

   1. Watch a video in Brave-Playlist in Fullscreen
   2. don't interact with the screen

## Actual result 
the screen dimms its brightness depending on the powersaving mode. (for me it was about 1 minute)

## Expected result
The screen should stay bright because I am watching a video.

## Issue reproduces how often 
happens always.

## Device details
 - Android 12; Build/SP1A.210812.016
 - device: realme 8 (RMX3085_11)
   
## Brave version
Brave - Nightly 1.52.5, Chromium 112.0.5615.49

**Comment by kjozwiak** [comment]
As discussed with @deeppandya via https://bravesoftware.slack.com/archives/C03MMJ4CHEZ/p1686260940735599, this issue will be added into the `master` playlist PR. This way the above won't be missed and will be verified. Reasoning is that the above code landed in `1.53.x` so the issue should stay in `1.53.x` and shouldn't be moved into other milestones.
