### ISSUE TITLE
Nothing happens when clicking on the notification of a playing video of Brave-Playlist

### ISSUE THREAD

**Issue by Sayum24** [brave/brave-browser#29441]
## Description 
When watching a video in Playlist. The screen dimms the brightness after some time.

## Steps to reproduce 

   1. Watch a video in Brave-Playlist
   2. click on the homescreen and/ or start another app
   3. open notification-center and click on the notification (not on the control-icons - they work)

## Actual result 
nothing happens
![image](https://user-images.githubusercontent.com/65895765/229111375-37d6c055-39ec-45df-88d9-9f8d53f63cdc.png)

## Expected result
Brave Browser App should come to the foreground and you should be able to see the video playing.

## Issue reproduces how often 
happens always.

## Device details
 - Android 12; Build/SP1A.210812.016
 - device: realme 8 (RMX3085_11)
   
## Brave version
Brave - Nightly 1.52.5, Chromium 112.0.5615.49

**Comment by kjozwiak** [comment]
As discussed with @deeppandya via https://bravesoftware.slack.com/archives/C03MMJ4CHEZ/p1686260940735599, this issue will be added into the `master` playlist PR. This way the above won't be missed and will be verified. Reasoning is that the above code landed in `1.53.x` so the issue should stay in `1.53.x` and shouldn't be moved into other milestones.
