### ISSUE TITLE
When minimizing playing video in Brave Playlist, can't return to the playing video.

### ISSUE THREAD

**Issue by Sayum24** [brave/brave-browser#29443]
## Description 
When watching a video in Playlist and you click on the minimize-icon in the top-right corner the video keeps playing, but you can't return to it, easily.
Because: 
1. the notification doesn't work - see #29441
2. there is no other visual link to the playing video

## Steps to reproduce 

   1. Watch a video in Brave-Playlist (not in fullscreen)
   2. click on the minimize-icon in the top-right corner
![image](https://user-images.githubusercontent.com/65895765/229114425-3e445156-3a68-41b5-a27f-cdae746a0c0a.png)

## Actual result 
video is hidden - for me no way to retrieve it - look at it again

## Expected result
maybe a little video player like in youtube where the video still plays and you can make it fullscreen by clicking on it.

## Issue reproduces how often 
happens always.

## Device details
 - Android 12; Build/SP1A.210812.016
 - device: realme 8 (RMX3085_11)
   
## Brave version
Brave - Nightly 1.52.5, Chromium 112.0.5615.49

**Comment by kjozwiak** [comment]
As discussed with @deeppandya via https://bravesoftware.slack.com/archives/C03MMJ4CHEZ/p1686260940735599, this issue will be added into the `master` playlist PR. This way the above won't be missed and will be verified. Reasoning is that the above code landed in `1.53.x` so the issue should stay in `1.53.x` and shouldn't be moved into other milestones.
