### ISSUE TITLE
Intergrate SafetyNet check

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#2946]
On Android on Brave Rewards page, if grants are available, when button Claim is clicked, instead of captcha, we should use SafetyNet attestation process to assess whether grants should be received.

QA steps:
Case 1:

On real device open chrome://rewards page.
Claim button should be visible.
Click Claim. No captcha should be there. Grants should be received automatically.
Case 2:

On virtual device open chrome://rewards page.
There should not be Claim button as SafetyNet attestation won't be passed on virtual device.

**Comment by samartnik** [comment]
Yes, it is closed. I don't have permission for editing milestones.

**Comment by NejcZdovc** [comment]
@samartnik @rebron what should be a milestone here as it was not merged to the master, but in android branch
