### ISSUE TITLE
Tabs jumps when selecting multiple tabs

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#29465]
## Description 

Original report: https://github.com/brave/brave-browser/issues/24717#issuecomment-1491128796

## Steps to Reproduce

   1. Create multiple tabs
   2. Select multiple tabs with shift + click - click a tab and then shift+click another tab below

## Actual result:

The selected tabs jumps down and come back to their position

## Expected result:

They shouldn't jump around

## Reproduces how often: 

Easily reproducible

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.51.97` or higher for `1.50.x` verification 👍

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 



Followed the specific steps to reproduce for each case, below, from https://github.com/brave/brave-core/pull/17876#issue-1652065354.

### Steps:
1. installed `1.51.99`
2. launched Brave
3. set `brave://flags/#brave-vertical-tabs` to `Enabled`
4. clicked `Relaunch`

### Tab-jumping
<details>

(continued from `Steps`)
5. loaded a bunch of sites in tabs
6. context-clicked on a tab
7. chose `Use vertical tabs`
8. selected a few contiguous tabs using `shift`

#### Confirmed no more tab-jumping behavior, as seen below in `1.51.95`

`1.51.99` | `1.51.95`
----------|----------
. | ![tab-jump-beta](https://user-images.githubusercontent.com/387249/232988183-6354962d-5cf5-4488-ab62-11d2ebed2d53.gif)

</details>

### Window-jumping
<details>

(continued from `Steps`)
5. loaded a bunch of sites in tabs
6. context-clicked on a tab
7. chose `Use vertical tabs`
8. selected the first and last tab, while holding `shift` to trigger contiguous selection

#### Confirmed no more window-jumping behavior, as seen below in `1.51.95`


`1.51.99` | `1.51.95`
----------|----------
 | ![window-jumping](https://user-images.githubusercontent.com/387249/232991316-d48af8ec-d677-488e-a8a0-27e9f88da3fd.gif)


</details>
