### ISSUE TITLE
Option for turning off search suggestions isn't working as intended

### ISSUE THREAD

**Issue by Debagnik** [brave/brave-browser#29461]
## Description 

As per the image attached below, the old searches are turned on but I cannot find the option for disabling that.

I have turned off Settings > appearance > “Show autocomplete suggestions in address bar” options and Settings > privacy and security > “Auto-complete searches and URLs” but these did not help. Images attached below. Any Ideas

I have already asked in the Brave community page about this which could be found [here](https://community.brave.com/t/how-do-i-turn-off-the-search-suggestion-in-the-address-bar/472247) but the solution doesn't seem to work.

## Steps to Reproduce

   1. launch brave.
   2. open a new tab.
   3. click on the address bar
   4. observe that the old searches appear as suggestions

## Actual result:

The search suggestions still show.

[IMG_1](https://global.discourse-cdn.com/brave/optimized/3X/a/0/a041601a7f4a6d28bda5801103278118b9822520_2_1035x582.jpeg)
[IMG_2](https://global.discourse-cdn.com/brave/optimized/3X/c/3/c3177ba71f7f68e636087766be5db1b3e079cce4_2_1035x582.png)
[IMG_3](https://global.discourse-cdn.com/brave/optimized/3X/a/e/aebaecb4279814448027b6dd7c87721d71ef14b4_2_1035x582.png)

## Expected result:

* Clicking on the address bar does not show previous searches
* Clicking on the address bar does not show previously visited URLs
* Clicking on the address bar does not show any kind of menu of options.

## Reproduces how often: 

Easily reproduced in all my Desktop devices

## Brave version (brave://version info)

[Version 1.48.167 Chromium: 110.0.5481.104 (Official Build) (64-bit)](https://brave.com/latest/)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Not known/Not Tested     
- Can you reproduce this issue with the beta channel?  
- Not Known/Not Tested     
- Can you reproduce this issue with the nightly channel? 
- Not Known/Not Tested     

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- No
- Does the issue resolve itself when disabling Brave Rewards?
- No 
- Is the issue reproducible on the latest version of Chrome?
- Not Tested 

## Miscellaneous Information:

Just to mention that I have tried to remove cookies, and history and disable/remove chrome/brave extensions as well. one of the method worked, for more insights on the troubleshooting methods I used please use [this link](https://community.brave.com/t/how-do-i-turn-off-the-search-suggestion-in-the-address-bar/472247)

**Comment by rebron** [comment]
Hi @Debagnik. Can you update to 1.50.114 that we just released today and see if you're still seeing this issue? You can go here to get the update manually brave://settings/help I

https://github.com/brave/brave-browser/issues/29043 is the duplicate issue.

**Comment by Debagnik** [comment]
Hi, @rebron thank you for taking the time to comment and work on this issue.

As I can see this issue is addressed on the latest build and the functionality to stop showing suggestions is now restored.
