### ISSUE TITLE
Add `Remove from list` menu entry to download bubble context menu

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#29475]
When user clicks download button, download bubble is shown and it shows all items.
Add `Remove from list` menu entry to the below context menu in each item.
With that, user could remove item from download bubble directly instead of going to download page.

`Remove from list` should be visible for completed or cancelled download item.

<img width="493" alt="Screenshot 2023-04-10 at 4 57 17 PM" src="https://user-images.githubusercontent.com/6786187/231310646-532a713a-7c5d-4ec6-bf69-c649f764b22d.png">

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.52.37 Chromium: 112.0.5615.49 (Official Build) nightly (64-bit)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Windows 10 Version 22H2 (Build 19045.2846)

### Steps:
1. installed `1.52.37`
2. launched Brave
3. loaded `https://www.leaseweb.com/platform/network`
4. downloaded `10000mb.bin` from the `San Francisco...` link, to the right
5. downloaded `BraveBrowserStandaloneNightlySetup.exe`
6. context-clicked on the `.exe` file and chose `Remove from list`
7. did the same, for the completed `10000mb.bin` file
8. confirmed I could remove the completed download from the list

example | example | example | example | example
----------|-----------|-----------|-----------|---------
![image (1)](https://user-images.githubusercontent.com/387249/231598358-e6d9f9b5-b6b6-40bf-9acb-2ebb3903cf18.png) | ![image (2)](https://user-images.githubusercontent.com/387249/231598356-28124a4c-7fec-4e34-84b7-d2281078da0e.png) | ![image](https://user-images.githubusercontent.com/387249/231598888-e57dd5c3-2172-45aa-b953-6e4a420dcee1.png) | ![image](https://user-images.githubusercontent.com/387249/231598924-cf224457-6c57-443b-b047-51e7a2ec53b0.png) | ![image](https://user-images.githubusercontent.com/387249/231598966-4566a0de-e307-422e-b178-24dc6812b63c.png) | ![image](https://user-images.githubusercontent.com/387249/231602911-48ad04e1-cc0f-416a-8ff7-adca6e1096af.png)
