### ISSUE TITLE
Update NFT Details Screen

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#29472]

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.52.102 Chromium: 113.0.5672.126 (Official Build) beta (64-bit)
-- | --
Revision | `c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}`
OS | Windows 11 Version 22H2 (Build 22621.1702)

- Verified steps from [brave/brave-core#17885](https://github.com/brave/brave-core/pull/17885)
- Verified NFT details screen is updated to the new design

https://github.com/brave/brave-browser/assets/17010094/354f7764-8e45-4de1-bf4b-8e901385d2aa
