### ISSUE TITLE
Delta updates on non-Release channels don't work on Windows

### ISSUE THREAD

**Issue by mherrmann** [brave/brave-browser#29474]
## Description 

On Windows, delta updates do not work for non-release channels. That is, we do have them. But they fail and fall back to the full update.

## Steps to Reproduce

1. Uninstall Brave Release.
2. Install the last-but-one public release of a non-Release channel. Eg. if the latest public Beta is 1.51.71 and the public Beta before that was 1.50.101, then install 1.50.101.
3. Open brave://settings/help.

## Actual result:

Two update cycles are shown in immediate succession. That is, the indicated update progress goes from 0% to 100%, then back to 0% and 100% again before completing. This is because first the delta update is attempted and fails. Then, the full update gets downloaded and installed.

## Expected result:

Only one update cycle should be shown. Also, `BraveUpdate.log` for the time period of the update should mention `brave_installer-delta-x64.exe` but not `brave_installer-x64.exe`.

## Reproduces how often: 

Always.

## Brave version (brave://version info)

I tested with Beta 1.50.101.

## Reason

Procmon indicates that the delta installer queries the registry key `...\ClientState\{AFE...}`. This is the registry key for Brave Release, not Brave Beta.

## Related issues

The following issues also affect delta updates on Windows:

 * #28989
 * #29469

**Comment by mherrmann** [comment]
Actually, it's working. I think I made a mistake when reproducing the issue.

**Comment by kjozwiak** [comment]
The above is resolved by https://github.com/brave/brave-core/pull/19659. QA will run through the verifications mentioned via https://github.com/brave/brave-core/pull/19659#issue-1847785722 using https://github.com/brave/brave-browser/issues/31977. STR/Cases that were used on Nightly before uplifting can be found via https://github.com/brave/brave-core/pull/19659#issuecomment-1697979753.
