### ISSUE TITLE
Brave crashed when VPN was enabled with existing Prod credentials 

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#29477]
## Description 

Found this while testing https://github.com/brave/brave-browser/issues/25489.  This issue was reproducible only in 1.50.112  logged in with prod credentials.  No crashes found in 1.50.110.  

## Steps to Reproduce

   1.  Install 1.50.112
   2.  launch/relaunch Brave
   3.  login with prod credentials
   4.  enable VPN 

## Actual result:

Brave Crashed
```
Uploaded Crash Report ID:	a51b0700-2274-db09-0000-000000000000
Upload Time:	Monday, April 3, 2023 at 12:07:24 PM
[ 0 ] RasEntryToPhonebookEntry
[ 1 ] RasSetEntryPropertiesW
[ 2 ] brave_vpn::internal::CreateEntry(std::Cr::basic_string<wchar_t,std::Cr::char_traits<wchar_t>,std::Cr::allocator<wchar_t> > const &,std::Cr::basic_string<wchar_t,std::Cr::char_traits<wchar_t>,std::Cr::allocator<wchar_t> > const &,std::Cr::basic_string<wchar_t,std::Cr::char_traits<wchar_t>,std::Cr::allocator<wchar_t> > const &,std::Cr::basic_string<wchar_t,std::Cr::char_traits<wchar_t>,std::Cr::allocator<wchar_t> > const &) ( utils.cc:368 )
[ 3 ] static void sqlite3DbNNFreeNN(struct sqlite3 *, void *) ( sqlite3.c:29507 )
[ 4 ] 0x7ffdcdfe04f1
```
## Expected result:
No crash

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.50.112 Chromium: 112.0.5615.49 (Official Build) (64-bit)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Windows 11 Version 22H2 (Build 22621.1413)
```
## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
 @mattmcalister  @bsclifton 
@brave/qa-team

**Comment by bsclifton** [comment]
Related:
- https://github.com/brave/brave-browser/issues/29502
- https://github.com/brave/brave-browser/issues/28940

**Comment by kjozwiak** [comment]
Labelling as `QA/No` and `release-notes/exclude` in favour of https://github.com/brave/brave-browser/issues/28940.
