### ISSUE TITLE
Images are not shown for NFTs which contain non-ipfs image urls

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#29486]
Images are not shown on the NFT wallet page for NFTs with non-ipfs image urls.
For example this one: https://opensea.io/assets/ethereum/0x70a422c390e8c7682f36611283e8a12254346ee3/1051
Related to https://github.com/brave/brave-browser/issues/28407

**Comment by kjozwiak** [comment]
The above requires `1.51.87` or higher for `1.51.x` verification 👍

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/29487#issuecomment-1527694068
