### ISSUE TITLE
NFT pinning status is not updated while staying on the NFT details page

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#29487]
1) Start pinning some NFT
2) Open details page related to the NFT
3) Check that status is "in-progress"
4) Wait for a while
5) Status is still in progress, until re-enter details page

Browser version : 1.51

**Comment by kjozwiak** [comment]
The above requires `1.51.87` or higher for `1.51.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.51.107 Chromium: 113.0.5672.63 (Official Build) (64-bit)
-- | --
Revision | 0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}
OS | Windows 11 Version 22H2 (Build 22621.1555)

- Verified steps from [brave/brave-core#17868](https://github.com/brave/brave-core/pull/17868)
- Verified NFT pinning banner is hidden if the setting is "on" and there are no pinned\in-progress NFTs.
- Verified NFTs with non-ipfs image like `https://opensea.io/assets/ethereum/0x70a422c390e8c7682f36611283e8a12254346ee3/1050` are correctly displayed but not being pinned
- Verified NFT pinning status is correctly updated while staying on the NFT's detail page.

https://user-images.githubusercontent.com/17010094/235181978-52428aa2-52db-4ee8-9578-054a41670b6c.mp4
