### ISSUE TITLE
Use MutationObserver to detect dynamically added media files

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#29488]
In order to use MutationObserver, we should attach that to renderer.

**Comment by diracdeltas** [comment]
in the past we've had some performance issues with mutationobservers so please be sure to do performance testing

**Comment by sangwoo108** [comment]
@diracdeltas , Thank you so much for the advice. Do you happen to know where the Github issue is? I hope I can check if it's our case here.

**Comment by diracdeltas** [comment]
i don't think there is a github issue (this was a long time ago) but it was something like https://bravesoftware.slack.com/archives/C3T9S9WKD/p1662752809753299?thread_ts=1662544398.836149&cid=C3T9S9WKD.

**Comment by sangwoo108** [comment]
Thank you so much. The thread is gold!

Current state of the implementation is quite alike cosmetic filter case. For now, MutationObserver is attached only to a background web contents, which is not in tab strip. And Playlist doesn't trigger reflow by manipulating CSS. So, hopefully it might not be that bad or impact user experience.

But we might need the observer on the contents in tabstrip as well in the future. Of what @atuchin-m suggested, using native mutation observer looks promising.
