### ISSUE TITLE
NFT Pinning text updates

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#29482]

**Comment by kjozwiak** [comment]
The above requires `1.51.80` or higher for `1.51.x` verification 👍

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.51.80 Chromium: 112.0.5615.49 (Official Build) beta (64-bit) 
-- | --
Revision | `bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}`
OS | Linux

- Verified steps from [brave/brave-core#17900](https://github.com/brave/brave-core/pull/17900)
- Verified  NFT pinning interstitial page text is updated

NFT-IPFS Interstitial page

Light | Dark 
-- | --
![image](https://user-images.githubusercontent.com/17010094/230875500-545a79c2-a36a-442e-a9af-4f686cca9915.png) | ![image](https://user-images.githubusercontent.com/17010094/230875411-ebcae2b7-dfe9-4c40-975b-6209f7d67de9.png)
---------------------

**Verification passed on**

Brave | 1.51.80 Chromium: 112.0.5615.49 (Official Build) beta (64-bit)
-- | --
Revision | `bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from [brave/brave-core#17900](https://github.com/brave/brave-core/pull/17900)
- Verified  NFT pinning interstitial page text is updated

NFT-IPFS Interstitial page

Light | Dark 
-- | --
![brave_wsY4POWQAr](https://user-images.githubusercontent.com/17010094/230871223-46a7a82c-6970-423d-8fa9-15517f1b69f1.png) | ![brave_2lTcILlwMj](https://user-images.githubusercontent.com/17010094/230871260-b58f2c3d-fa48-47ca-aca8-02fd2a566a0c.png)


---------------------

**Verification passed on**

Brave | 1.51.80 Chromium: 112.0.5615.49 (Official Build) beta (arm64)
-- | --
Revision | `bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#17900](https://github.com/brave/brave-core/pull/17900)
- Verified  NFT pinning interstitial page text is updated

NFT-IPFS Interstitial page

Light | Dark 
-- | --
![interstitial2light](https://user-images.githubusercontent.com/17010094/230872551-94af4cbd-5845-45ce-b099-a804f6261ed9.png) | ![interstitial2dark](https://user-images.githubusercontent.com/17010094/230872573-6c2a42c3-ef8c-4777-ba88-eafda8daeff4.png)
