### ISSUE TITLE
Rejecting biometric unlock when restoring wallet still prompts for biometric unlock when trying to unlock wallet

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#29490]
## Description 
Rejecting biometric unlock when restoring wallet still prompts for biometric unlock when trying to unlock wallet

## Steps to reproduce 

   1. Install 1.52.15
   2. Set up (create/restore) wallet with bio-metric
   3. Restore wallet via seed phrase
   4. Cancel biometric unlock feature when prompted
   5. Lock wallet manually or let it auto-lock
   6. Prompts for biometric unlock

## Actual result 
Rejecting biometric unlock when restoring wallet still prompts for biometric unlock when trying to unlock wallet

## Expected result
Should disable biometric unlock if user cancels it when restoring wallet

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 13
   
## Brave version
1.52.15

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information
cc: @Pavneet-Sing @jamesmudgett @simoarpe

**Comment by Pavneet-Sing** [comment]
I am not able to reproduce this. I cancelled the bio-metric (on the black screen) and didn't get any prompt afterwards.

[biometric-login-issue.webm](https://user-images.githubusercontent.com/11755381/229788865-8a5dc503-d500-4e63-86fb-d3e1989d30d7.webm)

cc: @srirambv

**Comment by kjozwiak** [comment]
The above requires `1.50.117` or higher for `1.50.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.50.120 x64 build

- Verified cancelling Biometric unlock during wallet recovery, with an existing wallet with Biometric unlock enabled, doesn't show the Biometric unlock. Additional verification done [#20807 (comment)](https://github.com/brave/brave-browser/issues/20807#issuecomment-1512950347)
