### ISSUE TITLE
Update Icon for the new Navigation

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#29499]
## Description 

We need to change the `Buy`, `Swap`, `Deposit` icons back to the older ones.

![Screenshot 41](https://user-images.githubusercontent.com/40611140/229845593-5638def2-1db3-4b74-93f4-cef833c19120.png)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.52.100 Chromium: 113.0.5672.92 (Official Build) beta (64-bit)
-- | --
Revision | `b6f521170062a1fa8a82c33fb223b06fec566da1-refs/branch-heads/5672_63@{#10}`
OS | Linux

- Verified test plan from [brave/brave-core#17913](https://github.com/brave/brave-core/pull/17913)
- Verified icons are updated back to the old ones 
![image](https://github.com/brave/brave-browser/assets/17010094/df5b3702-002b-4585-8e11-2499e9a1d2c6)
