### ISSUE TITLE
Market Tab does not scroll all the way to the bottom

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#29497]
## Description 

Market Tab does not scroll all the way to the bottom of the `Wallet` card.

## Steps to Reproduce

   1. Go to the `Market` tab,
   2. Scroll all the way to the bottom,
   3. The end gets cut off.

## Actual result:

https://user-images.githubusercontent.com/40611140/229835157-b2e69bb8-5e6c-463e-a12a-6520037b5876.mov

## Expected result:
Should scroll all the way to the bottom.

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.52.102 Chromium: 113.0.5672.126 (Official Build) beta (64-bit) 
-- | --
Revision | `c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}`
OS | Linux

- Verified steps from [brave/brave-core#17912](https://github.com/brave/brave-core/pull/17912)
- Verified able to scroll all the way to the bottom of the market tab

https://github.com/brave/brave-browser/assets/17010094/cb3f9f70-d63b-4dad-b065-542cac411a83


---------------------

**Verification passed on**

Brave | 1.52.102 Chromium: 113.0.5672.126 (Official Build) beta (64-bit)
-- | --
Revision | `c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}`
OS | Windows 11 Version 22H2 (Build 22621.1702)

- Verified steps from [brave/brave-core#17912](https://github.com/brave/brave-core/pull/17912)
- Verified able to scroll all the way to the bottom of the market tab

https://github.com/brave/brave-browser/assets/17010094/23f72c96-cae6-4e65-ac4b-e46b63b0771a


---------------------

**Verification passed on**

Brave | 1.52.102 Chromium: 113.0.5672.126 (Official Build) beta (arm64)
-- | --
Revision | `c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#17912](https://github.com/brave/brave-core/pull/17912)
- Verified able to scroll all the way to the bottom of the market tab

https://github.com/brave/brave-browser/assets/17010094/a1e3285d-6cfd-46b6-a961-ad6e59ae79f2
