### ISSUE TITLE
Brave crashed when VPN was enabled with newly purchased VPN Prod credentials 

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#29502]
## Description 

Purchased new VPN in Prod VPN environment this morning.  VPN subscription page kept spinning.   Waited more than 5 minutes. 
Reloaded the page and active credentials are loaded.  Enabled VPN in the VPN page but Brave crashed in Win 11 x64.    Verified on 1.50.110, 112 & 113. 

## Steps to Reproduce

1. Install 1.50.113
2. launch/relaunch Brave
3. Purchase new Prod VPN

## Actual result:

- VPN subscription page kept spinning (>5 minutes)
- Reloaded subscription page to load Active credentials 
- Enable VPN in the VPN panel

## Expected result:
Load time for active VPN credentials should not take >5 mins
Brave shouldn't crash when VPN is enabled

## Brave version (brave://version info)

Brave | 1.50.113 Chromium: 112.0.5615.49 (Official Build) (64-bit)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Windows 11 Version 22H2 (Build 22621.1413)

Crash from Tuesday, April 4, 2023 at 9:42:10 AM
Status:	Uploaded
Uploaded Crash Report ID:	ee6f0800-2274-db09-0000-000000000000
Upload Time:	Tuesday, April 4, 2023 at 10:00:19 AM
```
[ 0 ] RasEntryToPhonebookEntry
[ 1 ] RasSetEntryPropertiesW
[ 2 ] brave_vpn::internal::CreateEntry(std::Cr::basic_string<wchar_t,std::Cr::char_traits<wchar_t>,std::Cr::allocator<wchar_t> > const &,std::Cr::basic_string<wchar_t,std::Cr::char_traits<wchar_t>,std::Cr::allocator<wchar_t> > const &,std::Cr::basic_string<wchar_t,std::Cr::char_traits<wchar_t>,std::Cr::allocator<wchar_t> > const &,std::Cr::basic_string<wchar_t,std::Cr::char_traits<wchar_t>,std::Cr::allocator<wchar_t> > const &) ( utils.cc:368 )
[ 3 ] 0x7ff9d0e204f1
[ 4 ] 0x7ff9d0e1c028
```
## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
@clifton @mattmcalister 
cc: @brave/qa-team

**Comment by bsclifton** [comment]
Related:
- https://github.com/brave/brave-browser/issues/29477
- https://github.com/brave/brave-browser/issues/28940

**Comment by kjozwiak** [comment]
Labelling as `QA/No` and `release-notes/exclude` in favour of https://github.com/brave/brave-browser/issues/28940.
