### ISSUE TITLE
Simplify text on non-connected Brave Rewards panel and NTP Rewards widget

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#29506]
```[tasklist]
### Tasks
- [ ] Rewards panel
- [ ] NTP widget (desktop only)
```

**Rewards panel:**

1. New text: **Ready to start earning?** Connect or create an account with one of our partners.
2. "Learn more about BAT" --> "Learn more about earning BAT"

**NTP widget:**

New text: 

>**Ready to start earning?** Connect or create an account with one of our partners.

![image](https://user-images.githubusercontent.com/11497541/229891820-5a9f7412-3436-4a63-ac61-8a59b3c06656.png)

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.52.86 Chromium: 113.0.5672.77 (Official Build) beta (x86_64)
-- | --
Revision | c4236862955e005c2187105415ac4a2ecf86dff1-refs/branch-heads/5672_62@{#3}
OS | macOS Version 13.3.1 (Build 22E261)
```
