### ISSUE TITLE
[Android] Simplify text on non-connected Brave Rewards panel

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#29507]
## Description

**Rewards panel:**

1. New text: **Ready to start earning?** Connect or create an account with one of our partners.
2. "Learn more about BAT" --> "Learn more about earning BAT"

Android version of: https://github.com/brave/brave-browser/issues/29506

**Comment by deeppandya** [comment]
After the update : 
![Screenshot_20230411-215825](https://user-images.githubusercontent.com/5146988/231328465-6d33d978-e4ad-492e-9238-065a99b40e8a.png)

**Comment by vlad-hoff** [comment]
Verified on `Google Pixel 7` using version(s):
```
Device/OS: Google Pixel 7 [panther_beta-user 14 UPB2.230407.014 release-keys]
Brave build: 1.52.102
Chromium: 113.0.5672.126 (Official Build) beta (64-bit)
Revision: c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}
```
---------------------------

**STEPS:**
1. Launch Brave > Hamburger Menu > Settings
2. Enable `Use Rewards staging server` in Dev options > Relaunch Brave
3. Tap `Rewards panel` > Choose country > Continue > Skip tour > Verify
4. Open Rewards settings > Verify

<details>
<summary> United States (two custodians available) - PASSED </summary>

**ACTUAL RESULTS:**
- Verified new text `Ready to start earning? Connect or create an account with one of our partners.`
- Verified new text `Learn more about earning BAT`

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/b2126381-99ef-46c3-bfbc-30848f027076) | ![2](https://github.com/brave/brave-browser/assets/128532965/67e4d606-e4ba-4079-967c-db308697e131) |
</details>

<details>
<summary> Japan (one custodian available) - PASSED </summary>

**ACTUAL RESULTS:**
- Verified new text `Ready to start earning? Connect or create an account with one of our partners.`
- Verified new text `Learn more about earning BAT`

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/eb943857-8eec-432f-af71-5f1c321721d7) | ![2](https://github.com/brave/brave-browser/assets/128532965/c4972e19-e94d-4728-8351-dcff142a74d6) |
</details>

<details>
<summary> Rewards supported country where no custodians are available (Aruba) - PASSED </summary>

**ACTUAL RESULTS:**
- Verified that no regression was observed and no wording changed

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/f3ffacff-c4f5-4957-9a25-87f84e64bec8) | ![2](https://github.com/brave/brave-browser/assets/128532965/91195fc8-ab66-4ef2-ad8b-87601e654f9c) |
</details>

<details>
<summary> Non-Rewards supported country (Iran) - PASSED </summary>

**ACTUAL RESULTS:**
- Verified that no regression was observed and no wording changed

|1|
|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/6a76e1fc-b7b5-4a7b-a9b1-5890558ef9c6) |
</details>
