### ISSUE TITLE
Check for Tor binary when starting Tor windows

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#2950]
According to [this community post](https://community.brave.com/t/kts19-detecting-bravesoftware-tor-0-3-4-9-win32-brave-0/41120/16): if you delete the Tor binary, you can still open private windows with Tor, and they appear to work normally — but they aren't actually Tor-ified.

We should reasonably anticipate the possibility of the Tor binary being deleted by overzealous anti-malware tools. When the Tor binary is unavailable, we shouldn't just act like everything is okay. Windows with Tor should probably just be unusable in this case. Greying-out the menu items and disabling the shortcuts should work.

Those changes don't give any feedback about what's going wrong. If it's paranoid AV, there's probably something the a person can do to fix it — changing AV vendor, whitelisting the file, and so forth. So it'd be good to have a venue for communicating this rather than just silently breaking.

**Comment by riastradh-brave** [comment]
I am a bit confused by the report -- the screenshot at the end shows a non-private, non-Tor window, where it is not surprising that check.torproject.org says no Tor:

https://community.brave.com/t/kts19-detecting-bravesoftware-tor-0-3-4-9-win32-brave-0/41120/16

Is the issue, then, that the 'New private window with Tor' menu item opens a non-private, non-Tor window in this case?  Or that there's no feedback when it fails?  Or what?  Has anyone on Windows reproduced this?

**Comment by bsclifton** [comment]
@darkdh you had recently modified the behavior to download on open. Do you know if this would be resolved?

**Comment by darkdh** [comment]
Yes, https://github.com/brave/brave-core/pull/6081 resolves this issue.
