### ISSUE TITLE
[Brave News]: RSS Feed Parsing Performance

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#29511]
This is a followup to https://github.com/brave/brave-browser/issues/29438 where we limited the number of feeds which could be parsed at the same time.

Looks like the root cause of the slowdown is that `voca_rs` is looking at graphemes when they shouldn't be (resulting in some O(N^2+) algorithms). As a temporary fix, I'm looking at manually stripping the HTML tags.

However, in future it would be good to do the following:
1. Use the Browser HTML Parser (might be quite heavy duty).
2. Don't parse the RSS feed in the browser process (we should probably do this in a sandboxed process).

**Comment by fallaciousreasoning** [comment]
Instructions for testing are in @stephendonner's comment here: https://github.com/brave/brave-browser/issues/29438#issuecomment-1496337724

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using

Brave | 1.53.74 Chromium: 114.0.5735.53 (Official Build) beta (64-bit)
-- | --
Revision | c499d7ea22c8b2dba278465a5df7b86a8efa4e64-refs/branch-heads/5735@{#970}
OS | Windows 10 Version 22H2 (Build 19045.3031)

### Case One: `mate-desktop.org`

### Case Two:

### Case Three:

**Comment by stephendonner** [comment]
In addition, I also tested -- but didn't save/post results, here -- `planet.mozilla.org` and `pravda.com`, both of which have numerous feeds which also would've triggered this problem (and did), but now no longer do.

**Comment by vlad-hoff** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 [panther_beta-user 14 UPB2.230407.019 release-keys]
Brave build: 1.53.81
Chromium: 114.0.5735.90 (Official Build) beta (64-bit)
Revision: 386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}
```
---------------------------

**STEPS:**
1. Install `Cpu Monitor` app
2. Launch Brave and Cpu Monitor in `Split Screen` Mode
3. Open a new tab page > Enable Brave News
4. Go to www.mate-desktop.org
5. Wait ~30 seconds > Verify CPU usage
6. Go to www.planet.mozilla.org
7. Wait ~30 seconds > Verify CPU usage

**ACTUAL RESULTS:**
- Verified that CPU usage is between 16% and 25% when the news feed is loading

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/f8d19811-ba60-43f7-8e31-a29153f294aa) | ![2](https://github.com/brave/brave-browser/assets/128532965/baa0f156-ae7e-47f1-a5f3-f65cb9e36da2) | ![3](https://github.com/brave/brave-browser/assets/128532965/f79ee16a-2b3c-46ba-a69a-f5c2b7bc5b24) | ![4](https://github.com/brave/brave-browser/assets/128532965/d113f75e-3cd0-495a-bc12-6db8ecea5505) |
 
https://github.com/brave/brave-browser/assets/128532965/474f48bf-9fff-4a19-afce-67bf913f5dcb

NOTE: When no apps opened, the lowest CPU usage was ~16%

**Comment by kjozwiak** [comment]
Removing `QA Pass-Win64` & `QA Pass - Android ARM` as the above will need to be rechecked via `1.52.x` due to uplifting via https://github.com/brave/brave-core/pull/18805. Used the verifications from https://github.com/brave/brave-browser/issues/29511#issuecomment-1569095695 & https://github.com/brave/brave-browser/issues/29511#issuecomment-1577820763 for the `1.52.x` uplift rather than checking via `Nightly` as we usually do 👍

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.52.125 Chromium: 114.0.5735.110 (Official Build) (64-bit)
-- | --
Revision | 1c828682b85bbc70230a48f5e345489ec447373e-refs/branch-heads/5735_90@{#13}
OS | Windows 10 Version 22H2 (Build 19045.2965)

```

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.52.125 Chromium: 114.0.5735.110 (Official Build) (x86_64)
-- | --
Revision | 1c828682b85bbc70230a48f5e345489ec447373e-refs/branch-heads/5735_90@{#13}
OS | macOS Version 13.4 (Build 22F66)
```

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.52.125 Chromium: 114.0.5735.110 (Official Build) (64-bit) 
-- | --
Revision | 1c828682b85bbc70230a48f5e345489ec447373e-refs/branch-heads/5735_90@{#13}
OS | Ubuntu 18.04 LTS

### Steps:
1. installed `1.52.125`
2. launched Brave
3. skipped onboarding
4. opened a new-tab page
5. enabled Brave News
6. loaded `mate-desktop.org`
7. waited 30 seconds
8. checked `brave.exe` CPU usage

### Confirmed CPU usage was very low - reaching a high of 1%, idling slightly lower, on average

![image](https://github.com/brave/brave-browser/assets/34715963/1a41a449-4ec3-44b7-a66f-a35a68bea8a2)

**Comment by vlad-hoff** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 [panther_beta-user 14 UPB2.230407.019 release-keys]
Brave build: 1.52.125 
Chromium: 114.0.5735.110 (Official Build) (64-bit)
Revision: 1c828682b85bbc70230a48f5e345489ec447373e-refs/branch-heads/5735_90@{#13}
```
---------------------------

**STEPS:**
1. Install `Cpu Monitor` app
2. Launch Brave and Cpu Monitor in `Split Screen` Mode
3. Open a new tab page > Enable Brave News
4. Go to www.mate-desktop.org
5. Wait ~30 seconds > Verify CPU usage

**ACTUAL RESULTS:**
- Verified that CPU usage is between 16% and 25% when the news feed is loading

https://github.com/brave/brave-browser/assets/128532965/074d29cb-d4d2-4126-9675-5e2f3cb4f5ae

NOTE: When no apps opened, the lowest CPU usage was ~16-20%
