### ISSUE TITLE
"You can start a private call in Brave" showing up multiple times in one profile on ntp

### ISSUE THREAD

**Issue by wknapik** [brave/brave-browser#29513]
## Description 

This is showing up multiple times in the same profile on release channel on Linux

![image](https://user-images.githubusercontent.com/1129003/229956312-b77681b8-5c94-488c-bf22-ad0458d58472.png)

So far I've seen it 7 times in a few days, the last 3 today

## Steps to Reproduce

   1. Open new tab

## Actual result:

This is showing up multiple times per profile

## Expected result:
This should show up once per profile

## Reproduces how often: 

Intermittent issue

## Brave version (brave://version info)

Brave | 1.49.132 Chromium: 111.0.5563.147 (Official Build) (64-bit)
-- | --
Revision | 029fd65a4dd711d1078468ed2206999cec86066b-refs/branch-heads/5563@{#1239}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? ?
- Can you reproduce this issue with the nightly channel? ?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by kjozwiak** [comment]
Removing `OS/Linux` as we'll need to verify on other platforms as well due to removing the Brave Talk prompt entirely.

**Comment by kjozwiak** [comment]
The above requires `1.53.101` or higher for `1.53.x` verification 👍

**Comment by stephendonner** [comment]
> Removing `OS/Linux` as we'll need to verify on other platforms as well due to removing the Brave Talk prompt entirely.

Adding `QA/Test-All-Platforms`, given the above.  Please remove if I misunderstood!

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using



Brave | 1.53.102 Chromium: 114.0.5735.133 (Official Build) (x86_64)
-- | --
Revision | fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}
OS | macOS Version 14.0 (Build 23A5276g)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.53.102 Chromium: 114.0.5735.133 (Official Build) (64-bit)
-- | --
Revision | fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}
OS | Linux
```
### Steps:
1. installed `1.53.102`
2. launched Brave
3. completed onboarding
4. examined the new-tab page
5. hovered over the `Brave Talk` icon on the `Customize` row
6. confirmed `You can start a private call in Brave.` icon tooltip
7. clicked on the `Brave Talk` icon

### Confirmed the `You can start a private call in Brave.` promo is gone; also confirmed I could launch and use `Brave Talk` from its icon

`new-tab page` | `You can start a private call in Brave.` tooltip | `Brave Talk` | `Customize Dashboard` dialog 
-----------------|--------------------------------|-------------|---------------------------------
![Screenshot from 2023-06-22 17-39-07-1](https://github.com/brave/brave-browser/assets/98358127/30103a7d-544e-4af2-a79d-b12c0f5fb5e8)|![Screenshot from 2023-06-22 17-41-46](https://github.com/brave/brave-browser/assets/98358127/ca07061f-e89b-4a2b-be05-6f83058164e2)|![Screenshot from 2023-06-22 17-40-09](https://github.com/brave/brave-browser/assets/98358127/8f4adf18-2071-4161-93fb-c3fb79808ad1)|![Screenshot from 2023-06-22 17-41-17](https://github.com/brave/brave-browser/assets/98358127/c5180089-4575-4c21-a4f1-4a759c3e7a85)


### Upgrade - `PASS`
<details>

### Steps:
1. installed `1.52.126`
2. launched Brave
3. populated a typical browsing session, with bookmarks, etc.
4. opened a new-tab page
8. confirmed I saw the `You can start a private call in Brave.` promo, above the Brave Talk icon, on the bottom `Customize` row in the new-tab page
9. updated to and launched `1.53.102`
10. opened a new-tab page
11. hovered over the `Brave Talk` icon on the `Customize` row
12. confirmed it read `You can start a private call in Brave Talk.`
13. clicked on the `Brave Talk` icon

### Confirmed the `You can start a private call in Brave Talk.` promo is no longer present; also confirmed working `Brave Talk` via its icon

*Note: Have not seen  `You can start a private call in Brave Talk` in `1.52.126` or `1.49.132`

`1.52.126` |  `You can start a private call in Brave Talk.` tooltip | `Customize Dashboard` dialog
-----------|------------|-----------|-----------
![Screenshot from 2023-06-22 18-06-55](https://github.com/brave/brave-browser/assets/98358127/478eda29-7b90-46eb-ad8c-8f49aab8696c)|![Screenshot from 2023-06-22 18-13-12](https://github.com/brave/brave-browser/assets/98358127/4cb38bc4-e8d0-404d-afa5-4e072928b8a6)|![Screenshot from 2023-06-22 18-14-27](https://github.com/brave/brave-browser/assets/98358127/7bfd1230-1706-409a-925a-effac92dac5f)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.53.102 Chromium: 114.0.5735.133 (Official Build) (64-bit)
-- | --
Revision | fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}
OS | Windows 11 Version 22H2 (Build 22621.1848)
```
### Steps:
1. installed `1.53.102`
2. launched Brave
3. completed onboarding
4. examined the new-tab page
5. hovered over the `Brave Talk` icon on the `Customize` row
6. confirmed `You can start a private call in Brave.` icon tooltip
7. clicked on the `Brave Talk` icon

### Confirmed the `You can start a private call in Brave.` promo is not shown; also confirmed I could launch and use `Brave Talk` from its icon

`new-tab page` | `You can start a private call in Brave.` tooltip | `Brave Talk` | `Customize Dashboard` dialog 
-----------------|--------------------------------|-------------|---------------------------------
![image](https://github.com/brave/brave-browser/assets/98358127/8cea91c7-a30c-42c9-9cc5-f98e8c836474)|![2023-06-22_18h23_30](https://github.com/brave/brave-browser/assets/98358127/c5f05f70-e9ee-4064-85a1-d6fffa90bccb)|![image](https://github.com/brave/brave-browser/assets/98358127/9c11e99a-00b5-4727-8d8e-df9dadf605cd)|![image](https://github.com/brave/brave-browser/assets/98358127/24265171-efad-4902-b584-5e16af5ee214)

### Upgrade - `PASS`
<details>

### Steps:
1. installed `1.52.126`
2. launched Brave
3. populated a typical browsing session, with bookmarks, etc.
4. opened a new-tab page
8. confirmed I saw the `You can start a private call in Brave.` promo, above the Brave Talk icon, on the bottom `Customize` row in the new-tab page
9. updated to and launched `1.53.102`
10. opened a new-tab page
11. hovered over the `Brave Talk` icon on the `Customize` row
12. confirmed it read `You can start a private call in Brave Talk.`
13. clicked on the `Brave Talk` icon

### Confirmed the `You can start a private call in Brave Talk.` promo is no longer present; also confirmed working `Brave Talk` via its icon

*Note: Have not seen  `You can start a private call in Brave Talk` in `1.52.126` 

`1.52.126` |  `You can start a private call in Brave Talk.` tooltip | `Customize Dashboard` dialog
-----------|------------|-----------
![2023-06-22_18h28_19](https://github.com/brave/brave-browser/assets/98358127/ec2c3f0d-db00-48ba-9a05-5f64fb10df61)|![2023-06-22_18h30_06](https://github.com/brave/brave-browser/assets/98358127/3b224f31-1ef8-419e-bc82-548491a7c039)|![2023-06-22_18h30_36](https://github.com/brave/brave-browser/assets/98358127/ebe9b757-937c-4fb2-8a13-bedb68f6ba94)

**Comment by stephendonner** [comment]
Ah, @MadhaviSeelam of course - it was uplifted to `1.52.x` over in https://github.com/brave/brave-core/pull/18825, so we'd have to test with a seeded profile (as we did), or use `1.51.x`, looks like 👍
