### ISSUE TITLE
Gyazo Capture doesn't work that well with brave + it doesn't open capture in a new tab

### ISSUE THREAD

**Issue by AustinGitHub** [brave/brave-browser#29515]
Hi, 
I use gyazo capture because it is more convenient way for my to take screenshots but for some reason it doesn't work with brave browser. When I hit the print screen button that it's mapped to it doesn't work. It works though on chrome browser (both browsers on latest versions)

I am on windows 11, using both latest versions of chrome/brave. And latest version of gyazo. Please add support for this tool. It appears the print screen button is mapped so it can't be overwritten. 
Thanks!

**Comment by rebron** [comment]
cc: @fallaciousreasoning keyboard mapping related

**Comment by fallaciousreasoning** [comment]
Interesting @AustinGitHub does it happen in a new profile (or in a guest window)? I had a quick look at the KeyMapping in Brave and it doesn't look like we've bound anything to the `PrtScn` button. Does the button do anything in Brave when you press it?

**Comment by AustinGitHub** [comment]
@fallaciousreasoning when I restarted my computer I saw it open up new tabs, but I also see issue now where it also tries to bookmark the tab at the same time. I'm on windows and it's hard for me to tell if this is a gyazo problem or brave issue, thanks.

**Comment by fallaciousreasoning** [comment]
Interesting - it tries to bookmark a tab when you press the `PrtScn` button? That isn't ideal. Out of interest, is it possible to give gyazo a different shortcut and see if that works in Brave? That way we can determine if it's the shortcut which is broken, gyazo, or Brave :smile:

**Comment by AustinGitHub** [comment]
I will check tonight

**Comment by AustinGitHub** [comment]
@fallaciousreasoning yes, I changed keybind for the screenshot to one and it still tries to bookmark it

**Comment by fallaciousreasoning** [comment]
Okay, that's really weird, especially if a different shortcut also tries to bookmark. Okay I've got a few more ideas for trouble shooting:
1. Does it happen in a Private Window?
2. Do you have any extensions installed (if you don't mind, it'd be helpful to know what they are - sometimes extensions register their own shortcuts, and that might explain what we're seeing).
3. Does it happen in a new profile?
     
     ![image](https://user-images.githubusercontent.com/7678024/232912676-74fcd655-d0eb-4bf5-84db-a5e43ee0037e.png)
4. Can you use the built in screenshot tool, or is that broken too?
    ![image](https://user-images.githubusercontent.com/7678024/232913002-1d857d68-8e07-4a26-b352-cf923ed216a0.png)
5. Does it also happen in Brave Nightly? https://brave.com/download-nightly/

Hopefully this will help us work out what's going on

**Comment by AustinGitHub** [comment]
Hi, I am no longer having this issue. I am going to close it, thanks!
