### ISSUE TITLE
Failed NFT pinning tooltip needs border 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#29514]
## Description 

Failed NFT pinning tooltip needs border 

## Steps to Reproduce

   1. Add an NFT to pin
   2. Ensure it fails to add
   3. Hover over the message, tooltip blends into the white background and can't really make out

## Actual result:

Dark | Light
-- | --
![dark](https://user-images.githubusercontent.com/17010094/229995131-03c85f3b-f243-4e8b-9f85-3fdcfab21b35.png) | ![light](https://user-images.githubusercontent.com/17010094/229995159-38f04974-7964-4f5f-a9c6-7d191301e8c8.png)

## Expected result:
Tooltip should be distinguishable 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.52.17 Chromium: 112.0.5615.49 (Official Build) nightly (64-bit)
-- | --
Revision | `bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}`
OS | Windows 11 Version 22H2 (Build 22621.1485)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel @muliswilliam

**Comment by muliswilliam** [comment]
Fixed in https://github.com/brave/brave-browser/issues/28986
