### ISSUE TITLE
Speedreader prompt showing even when in Speedreader mode

### ISSUE THREAD

**Issue by wchen342** [brave/brave-browser#29523]
## Description 
Context: https://bravesoftware.slack.com/archives/CHGKGMHDJ/p1680245080661029?thread_ts=1679415767.066209&cid=CHGKGMHDJ
Sometimes you get a `Enable Speedreader` modal even though the article looks like it's in `Speedreader` mode.

## Steps to reproduce 

   1. Enable Speedreader in preference.
   2. Open a webpage that supports Speedreader mode and wait for it to load.
   3. Switch away from Brave, and switch back.
   4. See the `Enable Speedreader` prompt.

## Actual result 
An `Enable Speedreader` prompt is shown.

## Expected result
There shall be no prompt.

## Issue reproduces how often 
Easy.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
## Verified `PASSED` using a `Google Pixel XL` (`arm64`) running `Android 9`:

```
Brave	1.52.102 Chromium: 113.0.5672.126 (Official Build) beta (32-bit)
Revision	c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}
OS	Android 9; Build/PQ2A.190305.002; 28; REL
```

### Steps:
1. installed `1.52.102`
2. launched Brave
3. tapped on the 3-dots menu
4. tapped `Settings`
5. tapped on `Appearance`
6. confirmed `Enabled Speedreader` was defaulted to `Disabled` / `Off`
7. toggled it to `Enabled` / `On`
8. tapped `Relaunch now`
9. loaded `https://abcnews.go.com/Politics/dianne-feinstein-suffered-brain-inflammation-complication-shingles-aide/story?id=99439726`
10. confirmed it loaded in `Speedreader` view mode
11. switched apps away to `Google Chrome`
12. switched back to `Brave`

### Confirmed I was **_NOT_** prompted to enable `Speedreader` mode (repeated a few times)

example | example | example | example | example | example
---------|---------|----------|----------|---------|---------
![Screenshot_20230518-140541](https://github.com/brave/brave-browser/assets/387249/851d50b8-2832-4231-86b0-aa4351f79f7f) | ![Screenshot_20230518-140547](https://github.com/brave/brave-browser/assets/387249/5a8691b5-30f2-4a12-8502-2cddf85744fd) | ![Screenshot_20230518-140654](https://github.com/brave/brave-browser/assets/387249/729a9eb4-877d-4d2f-b133-3ae88fd7297e) | ![Screenshot_20230518-141337](https://github.com/brave/brave-browser/assets/387249/290094df-6e27-42cd-8cc3-584f19d8afa1) | ![Screenshot_20230518-140715](https://github.com/brave/brave-browser/assets/387249/d609cce3-bc99-4ff4-a007-05c1ab152dfa) | ![Screenshot_20230518-140722](https://github.com/brave/brave-browser/assets/387249/def86021-bb5f-4557-b43d-24db457f4748)
