### ISSUE TITLE
Simplify Purchased step on desktop

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#29520]
On desktop, we're waiting to enter `Purchased` status when we have valid region data after getting subscriber credential.
We do this because region data is needed to show vpn main panel.
However, region data is not related with purchasing and it makes purchased status handling complex.
Also, because of that we have many `ifdef android` because android doesn't need region data from `BraveVpnService`.

To make it more simpler, we could enter `Purchased` state after getting subscriber credential.
and region data handling is done by `BraveVPNOSConnectionAPI`.
As region data is used for connecting, `BraveVPNOSConnectionAPI` would be good place to manage region data.

VPN panel can show sell view when it's not purchased state yet.
and VPN panel can show main view when `BraveVPNOSConnectionAPI` have valid region data.

**Comment by kjozwiak** [comment]
The above requires `1.51.110` or higher for `1.51.x` verification 👍

**Comment by stephendonner** [comment]
@simonhong mind giving us a unique testplan for this one?  What's written so far in the PR for https://github.com/brave/brave-core/pull/18009#issue-1663572860 seems to apply more to https://github.com/brave/brave-browser/issues/29728.

And/or if we already verified https://github.com/brave/brave-browser/issues/29728#issuecomment-1533429211, can that verification apply?  Thanks!

**Comment by bsclifton** [comment]
@stephendonner added test plan! 😄 

And yes! https://github.com/brave/brave-browser/issues/29728#issuecomment-1533429211 should be perfect

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.51.110 Chromium: 113.0.5672.77 (Official Build) (x86_64)
-- | --
Revision | c4236862955e005c2187105415ac4a2ecf86dff1-refs/branch-heads/5672_62@{#3}
OS | macOS Version 13.4 (Build 22F5059b)

Followed the testplan in https://github.com/brave/brave-browser/issues/29520#issue-1655248821 and covered it via https://github.com/brave/brave-browser/issues/29728#issuecomment-1533429211
