### ISSUE TITLE
Add Label Reveal to Wallet Nav

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#29529]
## Description 

We need to add a `Label` reveal to the `Wallet Nav`

https://user-images.githubusercontent.com/40611140/230129320-41fe0d78-87af-4620-9f57-ee2e7a4533b6.mov

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.52.94 Chromium: 113.0.5672.92 (Official Build) beta (64-bit) 
-- | --
Revision | `0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}`
OS | Linux

- Verified steps from [brave/brave-core#17938](https://github.com/brave/brave-core/pull/17938)
- Verified wallet navigation shows label on mouse over and hides when mouse out

https://github.com/brave/brave-browser/assets/17010094/9341f3bb-c44d-424c-b9f5-3ef03072427f


---------------------

**Verification passed on**

Brave | 1.52.94 Chromium: 113.0.5672.92 (Official Build) beta (64-bit)
-- | --
Revision | `0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from [brave/brave-core#17938](https://github.com/brave/brave-core/pull/17938)
- Verified wallet navigation shows label on mouse over and hides when mouse out

https://github.com/brave/brave-browser/assets/17010094/e9550455-ab88-4e78-af37-ab00cec5a503

---------------------

**Verification passed on**

Brave | 1.52.94 Chromium: 113.0.5672.92 (Official Build) beta (arm64)
-- | --
Revision | `0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#17938](https://github.com/brave/brave-core/pull/17938)
- Verified wallet navigation shows label on mouse over and hides when mouse out

https://github.com/brave/brave-browser/assets/17010094/91ade3b2-8907-4c7e-bbc9-400e1246acad
