### ISSUE TITLE
Fix pinning status background and text color

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#29521]

**Comment by kjozwiak** [comment]
The above requires `1.51.87` or higher for `1.51.x` verification 👍

**Comment by LaurenWags** [comment]
Changing to `release-notes/exclude` per https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1683095542952369?thread_ts=1683004583.554499&cid=C023VS4HJ6Q
