### ISSUE TITLE
Update label in brave://settings/newTab

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#29524]
Change label from `Customize the background image and widgets that appear on the new tab page` to `Customize new tab page`.

![Screen Shot 2023-04-04 at 11 56 00 PM](https://user-images.githubusercontent.com/6786187/230068772-ed49d7e4-911b-4d36-90ac-01af22de8237.png)

**Comment by kjozwiak** [comment]
The above requires `1.51.87` or higher for `1.51.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using

Brave | 1.51.87 Chromium: 112.0.5615.49 (Official Build) beta (64-bit)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Windows 10 Version 22H2 (Build 19045.2846)

### Confirmed the new string reads `Customize new tab page` on `brave://settings/newTab`

![image](https://user-images.githubusercontent.com/387249/231714093-9eef4136-8446-44a3-9ec6-0754d2badb89.png)
