### ISSUE TITLE
[FEATURE] Option to import search engines from Chromium

### ISSUE THREAD

**Issue by donquixote** [brave/brave-browser#2953]
I have used Chromium a lot in the past, and created/saved a bunch of search engines. Some regular web search engines (e.g. dict.leo.org), some bookmarklet-style script-based search engines.

Now I am moving to Brave, I can import all the bookmarks (and bookmarklets), but not the search engines from Chromium.

(There is only an option to import them from Firefox, but that's not what I need right now)

Has this just not been implemented yet, or is there a reason that makes this specifically difficult?

## Brave version

Brave | 0.58.21 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Linux

### Reproducible on current release:
Dunno.

**Comment by alexWhitworth** [comment]
Any chance of upgrading this from P5? Not only a text-file import but also including as part of the sync code settings... For instance, whenever I reformat a hard-drive or get a new work computer, I have to manually import all my custom search engines. It's a PITA.

Thanks!

**Comment by bsclifton** [comment]
Closing as stale - it also seems there have been some changes on the Chromium side. Chromium before was adding all the Open Search based search engines automatically in Chrome - but it seems like that has changed
