### ISSUE TITLE
cache NFT metadata responses

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#29532]
## Description 

Store valid NFT metadata responses within the api cache to speedup subsequent requests for NFT metadata

## Steps to Reproduce

   1. Create a Brave Wallet
   2. Add an NFT to portfolio
   3. View the NFT page
   4. Navigate to a different page
   5. return to the NFT page

## Actual result:

The NFT meta data was not cached, preventing speedup of the second page load

## Expected result:
The NFT metadata is cached, allowing for speedup on the second page load

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by cypt4** [comment]
We can change policy in the APIRequestHelper for some requests. At the moment it bypasses cache. I think for erc721 tokens we could at least cache getting of metadata url.

**Comment by nvonpentz** [comment]
Removed QA/Yes because this isn't easily verifiable by QA team.
