### ISSUE TITLE
Do not change NFT route to portfolio when NFT details view is selected

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#29545]
## Description 

Do not change NFT route to portfolio when NFT details view is selected

## Steps to Reproduce

   1. Add an NFT to list
   2. Open the NFT to see details
   3. Side navigation changes to Portfolio 

## Actual result:

https://user-images.githubusercontent.com/17010094/230267062-98125a83-23ef-4c72-a2e5-ae2810608e01.mp4

## Expected result:
Should remain on NFT selection in side navigation

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.52.17 Chromium: 112.0.5615.49 (Official Build) nightly (64-bit)
-- | --
Revision | `bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}`
OS | Windows 11 Version 22H2 (Build 22621.1485)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? nA

## Miscellaneous Information:

cc: @Douglashdaniel

**Comment by Douglashdaniel** [comment]
NTF view is now part of the `Portfolio`, closing as `Invalid`
