### ISSUE TITLE
Additional Sync P3A question

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#29549]
It is required to add these P3A questions for sync:

I. `Brave.Sync.SyncedObjectsCount`
```
If you are opted into sync, how many objects are synced?
0) 0..1000;
1) 1001..10000;
2) 10001..49000;
3) 49001 and more.
```

II. `Brave.Sync.EnabledTypes`
```
If you are opted into sync, which types are enabled in Sync?
0) no types or only Bookmarks;
1) only Bookmarks + History;
2) more than (Bookmarks + History) but less than (Sync All);
3) all types.
```

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave | 1.52.92 Chromium: 113.0.5672.92 (Official Build) beta (64-bit)
-- | --
Revision | b6f521170062a1fa8a82c33fb223b06fec566da1-refs/branch-heads/5672_63@{#10}
OS | Windows 10 Version 21H2 (Build 19044.2965)

```

**Comment by GeetaSarvadnya** [comment]
@AlexeyBarabash: Is `SyncedObjectsCount` shown anywhere on the client side? I have verified brave://sync-internals/ and brave://histograms/.  I don't see synced object count in these two places. To test the following conditions, I would need this detail.

```
If you are opted into sync, how many objects are synced?
0) 0..1000;
1) 1001..10000;
2) 10001..49000;
3) 49001 and more.
```

**Comment by AlexeyBarabash** [comment]
> @AlexeyBarabash: Is `SyncedObjectsCount` shown anywhere on the client side? I have verified brave://sync-internals/ and brave://histograms/. 

@GeetaSarvadnya , no, it is not shown as a single number. 

`SyncedObjectsCount` is the total sum of all values at `Live Entries` column at  brave://sync-internals/ 
![image](https://github.com/brave/brave-browser/assets/24739341/20d494a8-f89a-4a0f-9a2c-ad5aedb1eb84)

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.52.112`

**Brave.Sync.SyncedObjectsCount**

<details>
<summary>Case 1: Brave.Sync.SyncedObjectsCount = 0_PASSED</summary>

<details>
<summary>Case 1.1: No bookmarks added_PASSED</summary>

1. Clean profile 1.52.x
2. Sync two device
3. Open the brave://local-state file
4. Look for the metrics `Brave.Sync.SyncedObjectsCount`
5. Confirmed that the metrics `Brave.Sync.SyncedObjectsCount` response value is `0` as expected

Local-state | brave://sync | Bookmarks manager
-------------|---------------|-----------------------
![image](https://github.com/brave/brave-browser/assets/38657976/818282fd-4dc7-4cdc-83f6-cacbc50e831c) | ![image](https://github.com/brave/brave-browser/assets/38657976/3534cf8f-f803-40dc-8a32-a53b54e11831) | ![image](https://github.com/brave/brave-browser/assets/38657976/86cdffe0-ea8f-4738-b70d-e78d393602ba)

</details>

<details>
<summary>Case 1.2: 50+ bookmarks added _PASSED</summary>

1. Clean profile 1.52.x
2. Sync two device
3. Import or add bookmarks 50+
4. Open the brave://local-state file
5. Look for the metrics `Brave.Sync.SyncedObjectsCount`
6. Confirmed that the metrics `Brave.Sync.SyncedObjectsCount` response value is `0` as expected

Local-state | brave://sync | brave://sync-internals
-------------|---------------|-----------------------
![image](https://github.com/brave/brave-browser/assets/38657976/f61f414d-02ae-405f-964a-bb193cef7fde) | ![image](https://github.com/brave/brave-browser/assets/38657976/c6270191-54cf-4741-8e7c-ccb3785d80bd) | ![image](https://github.com/brave/brave-browser/assets/38657976/eda1aa7b-9c9f-452c-87dd-e9d32455cdda)


</details>

</details>

<details>
<summary>Case 2: Brave.Sync.SyncedObjectsCount = 1_PASSED</summary>

1. Clean profile 1.52.x
2. Sync two device
3. Import bookmarks and select `sync everything` from brave://settings/braveSync/setup
4. Make sure no of bookmarks added are in the range 1000 to 10000
5. Open the brave://local-state file
6. Look for the metrics `Brave.Sync.SyncedObjectsCount`
7. Confirmed that the metrics `Brave.Sync.SyncedObjectsCount` response value is `1` as expected

Local-state | brave://sync | brave://sync-internals
-------------|---------------|-----------------------
![image](https://github.com/brave/brave-browser/assets/38657976/485b5333-d3a3-4a73-bb0f-b9f4058f7a2a) | ![image](https://github.com/brave/brave-browser/assets/38657976/803bbb9c-eb27-4d9a-b5e1-4a791f11f24c) | ![image](https://github.com/brave/brave-browser/assets/38657976/f8fafdfe-ac00-43cd-8697-dae2614aa252)

</details>

<details>
<summary>Case 3: Brave.Sync.SyncedObjectsCount = 2_PASSED</summary>

1. Clean profile 1.52.x
2. Sync two device
3. Import bookmarks and select `sync everything` from brave://settings/braveSync/setup
4. Make sure no of bookmarks added are in the range 10001 to 49000
5. Open the brave://local-state file
6. Look for the metrics `Brave.Sync.SyncedObjectsCount`
7. Confirmed that the metrics `Brave.Sync.SyncedObjectsCount` response value is `2` as expected

Local-state | brave://sync | brave://sync-internals
-------------|---------------|-----------------------
![image](https://github.com/brave/brave-browser/assets/38657976/d930d0a7-d7dc-406d-8f2b-34dfd7e7b65a) | ![image](https://github.com/brave/brave-browser/assets/38657976/63704a88-0069-4249-b8bd-ffb041ef1d12) | ![image](https://github.com/brave/brave-browser/assets/38657976/05a64c3d-95ce-4649-a334-505586ddf28f)

</details>

<details>
<summary>Case 4: Brave.Sync.SyncedObjectsCount = 3_PASSED</summary>

1. Clean profile 1.52.x
2. Sync two device
3. Import bookmarks and select `sync everything` from brave://settings/braveSync/setup
4. Make sure no of bookmarks are more than 49001 +
5. Open the brave://local-state file
6. Look for the metrics `Brave.Sync.SyncedObjectsCount`
7. Confirmed that the metrics `Brave.Sync.SyncedObjectsCount` response value is `3` as expected

Local-state | brave://sync | brave://sync-internals
-------------|---------------|-----------------------
![image](https://github.com/brave/brave-browser/assets/38657976/f49a1f43-ed7b-437e-a3c7-43503f0b8c5b) | ![image](https://github.com/brave/brave-browser/assets/38657976/9abed2a6-8e07-4370-bb7c-ada14edb432b) | ![image](https://github.com/brave/brave-browser/assets/38657976/af883eee-07ed-4b70-acbd-0eb6dfb67054)

</details>


**Brave.Sync.EnabledTypes**

<details>
<summary>Case 1: Only Bookmarks_PASSED</summary>

1. Clean profile 1.52.x
2. Sync two device
3. Import bookmarks  
4. Keep `Bookmarks` selected as it is in brave://settings/braveSync/setup
5. Open the brave://local-state file
6. Look for the metrics `Brave.Sync.EnabledTypes`
7. Confirmed that the metrics `Brave.Sync.EnabledTypes` response value is `0` as expected

brave://sync | local-state
--------------|------------
![image](https://github.com/brave/brave-browser/assets/38657976/d7da15e4-1ca7-455e-a5cc-4d7cf412736c) | ![image](https://github.com/brave/brave-browser/assets/38657976/1fc1f93f-fbbf-4008-846d-e336b373f0e7)

</details>

<details>
<summary>Case 2: Only Bookmarks+History_PASSED</summary>

1. Clean profile 1.52.x
2. Sync two device
3. Import bookmarks  
4. select `History` from brave://settings/braveSync/setup
5. Open the brave://local-state file
6. Look for the metrics `Brave.Sync.EnabledTypes`
7. Confirmed that the metrics `Brave.Sync.EnabledTypes` response value is `1` as expected

brave://sync | local-state
--------------|------------
![image](https://github.com/brave/brave-browser/assets/38657976/402deaee-6bbb-4486-b9fa-43190e1fbc3b) | ![image](https://github.com/brave/brave-browser/assets/38657976/987e3076-d3b1-4bd2-8101-1deddb21df95)

</details>

<details>
<summary>Case 3: more than (Bookmarks + History) but less than (Sync All)_PASSED</summary>

1. Clean profile 1.52.x
2. Sync two device
3. Import bookmarks  
4. select `History`, `Extension`, `Passwords` and `Open Tabs` from brave://settings/braveSync/setup
5. Open the brave://local-state file
6. Look for the metrics `Brave.Sync.EnabledTypes`
7. Confirmed that the metrics `Brave.Sync.EnabledTypes` response value is `1` as expected

brave://sync | local-state
--------------|------------
![image](https://github.com/brave/brave-browser/assets/38657976/865191dc-24a0-4f10-b75d-8bac5f0a8bf2) | ![image](https://github.com/brave/brave-browser/assets/38657976/5fc1f6c9-3d26-48a0-b3cc-3a643a506be3)

</details>

<details>
<summary>Case 4: all types_PASSED</summary>

1. Clean profile 1.52.x
2. Sync two device
3. Import bookmarks  
4. Select `Sync everything` from brave://settings/braveSync/setup
5. Open the brave://local-state file
6. Look for the metrics `Brave.Sync.EnabledTypes`
7. Confirmed that the metrics `Brave.Sync.EnabledTypes` response value is `3` as expected

brave://sync | local-state
--------------|------------
![image](https://github.com/brave/brave-browser/assets/38657976/581af951-7cb0-4780-94a7-86dc5289dcf2) | ![image](https://github.com/brave/brave-browser/assets/38657976/74406926-b98c-4423-b021-e5744d06895a)


</details>

<details>
<summary>Case 5: No types_PASSED</summary>

1. Clean profile 1.52.x
2. Sync two device
3. Import bookmarks  
4. Unselect `Bookmarks` in brave://settings/braveSync/setup
5. Open the brave://local-state file
6. Look for the metrics `Brave.Sync.EnabledTypes`
7. Confirmed that the metrics `Brave.Sync.EnabledTypes` response value is `0` as expected

brave://sync | local-state
--------------|------------
![image](https://github.com/brave/brave-browser/assets/38657976/fd3285ed-7fa7-4c90-803e-4477e7b8671b) | ![image](https://github.com/brave/brave-browser/assets/38657976/46a3d8f7-edcd-45d5-90b4-66b4cc9afd03)



</details>
