### ISSUE TITLE
Tweak transaction UI for Solana versioned transactions

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#29543]
Now that we supported versioned transactions, we need to tweak transaction UI when dApp is using address lookup table to load more accounts.
Please refer to https://github.com/brave/brave-core/pull/17542/commits/96ef88d88cf5e1c80644fc5daec5e619326f723a and https://github.com/brave/brave-core/pull/17542/commits/d6c4df810793d2b15798f6ad3471293b570dd3d7 for what needs to be updated.
Mainly, for UI that we show the address before, when SolanaAccountMeta.addr_table_lookup_index has value, we should show the index along with the pubkey so user would have the correct info about which account stored on chain is actually used in the instructions.

UI changes in desktop in https://github.com/brave/brave-core/pull/17542:
1) Transactions in account activity
<img width="691" alt="Screen Shot 2023-04-05 at 3 27 29 PM" src="https://user-images.githubusercontent.com/4730197/230225671-ec0d1381-e9c8-4484-8b04-f6b9ae8cf3fa.png">
Transaction on the top is using an account stored on chain, so we would not wrongly show the address table lookup account as the receiver but shows ***. The other transaction is a legacy transaction and uses static accounts (no tables involved) only, so receiver is shown here.

2) Transaction approval screen
Before two UI commits listed above, UI looks like:
<img width="314" alt="Screen Shot 2023-04-05 at 3 36 55 PM" src="https://user-images.githubusercontent.com/4730197/230226853-9abc6b9f-928b-4784-beee-298e96f6a645.png">

After two UI commits listed above, UI looks like:
<img width="320" alt="Screen Shot 2023-04-05 at 3 25 40 PM" src="https://user-images.githubusercontent.com/4730197/230226579-c1ec814b-c5ed-49a6-b115-fd8490e18599.png">

The actual `To Account` in this case is the account at index 1 (Ed8j...) stored in the address table lookup account (CE7e...).
<img width="1594" alt="Screen Shot 2023-04-03 at 4 22 30 PM" src="https://user-images.githubusercontent.com/4730197/229647631-0e0c326d-e409-45c9-99fa-739709549bfc.png">

To test versioned transactions, please visit https://pwgoom.csb.app/, connect your account on devnet, then click `Sign and Send Transaction (v0 + lookup table) (devnet only)`.

cc @Pavneet-Sing @simoarpe @SergeyZhukovsky

**Comment by yrliou** [comment]
This would needs to be landed in 1.52.x.

**Comment by kjozwiak** [comment]
The above requires `1.52.95` or higher for `1.52.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.52.112 x64 build
- Verified steps from [ brave/brave-core#18293](https://github.com/brave/brave-core/pull/18293)
- Verified All cases with v0 keyword in https://codesandbox.io/s/github/darkdh/solana-provider-test worked as expected
- Verified all three Send Transactions cases in the bottom row in https://solana-labs.github.io/wallet-adapter/example/ worked as expected

https://github.com/brave/brave-browser/assets/17010094/9ff19615-253d-466b-820c-1cd8daf4ef7b
