### ISSUE TITLE
[FEATURE] Nickname/keyword for bookmarks

### ISSUE THREAD

**Issue by donquixote** [brave/brave-browser#2954]
In Opera, it [used to be](https://web.archive.org/web/20150516202809/http://help.opera.com/Windows/12.10/en/bookmarks.html) ( * ) possible to store a nickname/keyword for a bookmark.
You could enter the keyword in the address bar and hit enter, and the page would open.

( * ) I have not used Opera for a while so I don't know if it is still possible.

In Chromium, such a feature does not exist. Keywords can be added for searches, but not for bookmarks. A search needs an additional parameter to open it.
In Firefox, I am not sure, the doc page talks about search keywords mostly, http://kb.mozillazine.org/Using_keyword_searches#Creating_bookmarks_with_keywords

Could such a feature be added to Brave browser?

Bookmark keywords/nicknames are especially useful for js bookmarklets.

**Comment by tomlowenthal** [comment]
Searches don't need to have an additional parameter. If you create a new "search" operator without `%s` in the URI, it works just like a bookmark keyword.

**Comment by juligreen** [comment]
I also miss this feature!

Coming from Vivaldi, there I can use the bookmark nickname in the "quick command" window and have the sites open immediately
