### ISSUE TITLE
Adding NFT from the same collection doesn't show the pinning state until browser restart

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#29551]
## Description 

Adding NFT from the same collection doesn't show the pinning state until browser restart

## Steps to Reproduce

   1. Add an NFT from a collection 
   2. Ensure it is pinned
   3. Add a few more from the same collection
   4. Open NFT details page for newly added NFT
   5. Doesn't show NFT pinning state
   6. Reload page, still no status
   7. Restart browser, shows NFT pinning state

## Actual result:

https://user-images.githubusercontent.com/17010094/230362546-ba002ec1-6c3f-4cd8-b80a-b69e180b11fd.mp4

## Expected result:
Should show status without having to restart browser

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.52.17 Chromium: 112.0.5615.49 (Official Build) nightly (64-bit)
-- | --
Revision | `bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}`
OS | Windows 11 Version 22H2 (Build 22621.1485)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @cypt4 @muliswilliam

**Comment by kjozwiak** [comment]
The above requires `1.51.95` or higher for `1.51.x` verification 👍

**Comment by srirambv** [comment]
<html>
<body>


Brave | 1.51.107 Chromium: 113.0.5672.63 (Official Build) (64-bit)
-- | --
Revision | `0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}`
OS | Windows 11 Version 22H2 (Build 22621.1555)


</body>
</html>

- Verified steps from [brave/brave-core#17983](https://github.com/brave/brave-core/pull/17983)
- Verified adding an NFT from the same collection automatically shows the pinning status and doesn't require browser restart
