### ISSUE TITLE
Show "All Networks" assets on edit visible assets dialog

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#29555]
Show assets of all network on edit-visible dialog. ([Previously, Edit visible dialog was showing assets of default network when all network is selected on Portfolio](https://github.com/brave/brave-core/blob/master/android/java/org/chromium/chrome/browser/crypto_wallet/fragments/PortfolioFragment.java#L466-L469))

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.52.92 x64 beta build
- Verified steps from [brave/brave-core#18096](https://github.com/brave/brave-core/pull/18096)
- Verified able to see all tokens in edit visible asset dialog
- Verified filtering network in portfolio also filters visible asset lists 
- Verified NFT's can also be filtered based on network

https://github.com/brave/brave-browser/assets/17010094/64aa3e08-a93d-43ae-be8b-720c730e2f82
