### ISSUE TITLE
Show/hide account button is too close to the scroll bar

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#29550]
## Description 

Show/hide account button is too close to the scroll bar

## Steps to Reproduce

   1. Add an NFT
   2. Open NFT details view
   3. Show/hide Account button is too close to the scroll bar

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/230358606-99877b81-48f3-45c3-926a-193e404408d3.png)

## Expected result:
Add more padding to the right 
![image](https://user-images.githubusercontent.com/17010094/230359305-8dd5cd71-1f95-42af-aca2-44e81230663c.png)

## Reproduces how often: 

Easy
## Brave version (brave://version info)

<html>
<body>

Brave | 1.52.17 Chromium: 112.0.5615.49 (Official Build) nightly (64-bit)
-- | --
Revision |` bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}`
OS | Windows 11 Version 22H2 (Build 22621.1485)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @muliswilliam

**Comment by Douglashdaniel** [comment]
That button was removed in `Wallet V2`, closing as `Invalid`

![Screenshot 72](https://github.com/brave/brave-browser/assets/40611140/7a6c0e3d-386c-4015-9cf1-ea03ec73a1c9)
