### ISSUE TITLE
Clearing pinned NFT still shows `NFT data is being pinned to your local IPFS node` on NFT details screen

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#29553]
## Description 

Clearing pinned NFT still shows ` NFT data is being pinned to your local IPFS node` on NFT details screen

## Steps to Reproduce

   1. Add a few NFT's and pin them
   2. Ensure NFT show successfully pinned message
   3. Disable auto-pinning NFT from setting
   4. Click on `Clear Pinned NFT`
   5. Go back to NFT details view
   6. Banner changes to Learn more 
   7. Open NFT details view
   8. Shows `NFT data is being pinned to your local IPFS node`
   9. Restart browser, continues to show the message from step 8

## Actual result:

https://user-images.githubusercontent.com/17010094/230390220-fefcbd5d-1769-404d-a429-1cdfb0b14e72.mp4

## Expected result:
Should not show `NFT data is being pinned to your local IPFS node` on NFT details screen when `Clear pinned NFT` is selected

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html><head></head>
<body>

Brave | 1.52.17 Chromium: 112.0.5615.49 (Official Build) nightly (64-bit)
-- | --
Revision | `bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}`
OS | Windows 11 Version 22H2 (Build 23424.1000)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @cypt4

**Comment by kjozwiak** [comment]
The above requires `1.51.95` or higher for `1.51.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.51.107 Chromium: 113.0.5672.63 (Official Build) (64-bit)
-- | --
Revision | `0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}`
OS | Windows 11 Version 22H2 (Build 22621.1555)

- Verified steps from [brave/brave-core#17983](https://github.com/brave/brave-core/pull/17983)
- Verified adding an NFT from the same collection automatically shows the pinning status and doesn't require browser restart

https://user-images.githubusercontent.com/17010094/235191075-50a03d29-3f75-45f6-9a89-fbbbde8f74fc.mp4
