### ISSUE TITLE
Crash when you try to tip someone

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#29562]
That is basically the same as https://github.com/brave/brave-browser/issues/28088 where it wasn't fixed. It happens on stable channel as well and only on Android 8 devices.
The steps are:

- install Brave on Android 8.
- connect to a provider.
- try to tip some creator by clicking `Send Tip` button.

[tipping_crash.webm](https://user-images.githubusercontent.com/12011303/230472644-5c2069de-b901-479e-8c90-eb659eb63c83.webm)

**Comment by kjozwiak** [comment]
The above requires `1.50.118` or higher for `1.50.x` verification 👍

**Comment by Uni-verse** [comment]
In Progress on `Samsung GS 21` running `Android 13` using the following build(s):

```
Brave	1.50.120 Chromium: 112.0.5615.121 (Official Build) (64-bit) 
Revision	39cc4e45904ae9f1741c4fbaa866e629c96f2268-refs/branch-heads/5615_51@{#8}
OS	Android 13; Build/TP1A.220624.014
```
