### ISSUE TITLE
Allow new Wallet Wrapper to Scroll

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#29564]
## Description 

We need to allow the the Wallet Wrapper to scroll when the screen height is less than the `min-height` of the `nav` and `container`

https://user-images.githubusercontent.com/40611140/230497777-4fecca92-5888-4c46-8061-42d91f0b93e8.mov

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.52.94 Chromium: 113.0.5672.92 (Official Build) beta (64-bit) 
-- | --
Revision | `0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}`
OS | Linux

- Verified steps from [brave/brave-core#17957](https://github.com/brave/brave-core/pull/17957)
- Verified vertical scrolling works even when window is small

https://github.com/brave/brave-browser/assets/17010094/948e8455-939a-4689-8511-61238e21ddc4


---------------------

**Verification passed on**

Brave | 1.52.94 Chromium: 113.0.5672.92 (Official Build) beta (64-bit)
-- | --
Revision | `0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from [brave/brave-core#17957](https://github.com/brave/brave-core/pull/17957)
- Verified vertical scrolling works even when window is small

https://github.com/brave/brave-browser/assets/17010094/d13977f8-3eb1-4ea9-864e-24a516738b5a


---------------------

**Verification passed on**

Brave | 1.52.94 Chromium: 113.0.5672.92 (Official Build) beta (arm64)
-- | --
Revision | `0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#17957](https://github.com/brave/brave-core/pull/17957)
- Verified vertical scrolling works even when window is small

https://github.com/brave/brave-browser/assets/17010094/208c4f36-2134-40c3-ad82-7887447bbb5d
