### ISSUE TITLE
Captcha target not fully shown if the target is below the visible BR panel

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#2956]
## Description 

Captcha target not fully shown if the target is below the visible BR panel

## Steps to Reproduce

   1. Set browser zoom to 125% 
   2. Enable rewards on BR Panel and claim grant
   3. Ensure one of the target is below the standard view of the BR Panel
   4. Scroll down the panel won't see the full target (See screentshot)

## Actual result:

![screenshot from 2019-01-15 10-26-35](https://user-images.githubusercontent.com/17010094/51160523-5160f780-18b4-11e9-9734-976a63fc66e3.png)

## Expected result:
Browser zoom level shouldn't affect the CATPCHA shown on BR panel

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.60.13 Chromium: 72.0.3626.53 (Official Build) dev(64-bit)
-- | --
Revision | 98434e6cd182d68ce396daa92e9c6310422e6763-refs/branch-heads/3626@{#620}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes on Dev
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

@brave/legacy_qa to verify on other platforms, @NejcZdovc @ryanml @rebron

**Comment by btlechowski** [comment]
Reproduced on Windows 7 by changing global page zoom setting in `chrome://settings/?search=page+zoom`

![image](https://user-images.githubusercontent.com/34715963/51213588-ab48d800-191b-11e9-9085-6013e2c38bad.png)

Brave | 0.60.13 Chromium: 72.0.3626.53 (Official Build) dev (64-bit)
-- | --
Revision | 98434e6cd182d68ce396daa92e9c6310422e6763-refs/branch-heads/3626@{#620}
OS | Windows

**Comment by NejcZdovc** [comment]
closing this one as it's not a problem anymore
