### ISSUE TITLE
NFT discovery setting is not respected

### ISSUE THREAD

**Issue by nvonpentz** [brave/brave-browser#29575]

**Comment by kjozwiak** [comment]
The above requires `1.51.87` or higher for `1.51.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.51.109 Chromium: 113.0.5672.63 (Official Build) (64-bit)
-- | --
Revision | `0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}`
OS | Windows 11 Version 22H2 (Build 22621.1555)

- Verified steps from [brave/brave-core#17960](https://github.com/brave/brave-core/pull/17960)
- Verified restoring wallet with NFT isn't automatically discovered and added to visible list

https://user-images.githubusercontent.com/17010094/235596927-06dbd7d5-f156-4d4a-827a-5058c2ae1e6f.mp4
