### ISSUE TITLE
BR panel keeps showing `1` notification message even when rewards is not turned on

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#2957]
## Description 

BR panel keeps showing `1` notification message even when rewards is not turned on

## Steps to Reproduce

1. Clean profile on Linux
2. BR panel shows 1 notification 
3. Click on BR panel, notification goes away
4. Click on BR panel again notification comes back

## Actual result:

BR panel keeps showing `1` notification message even when rewards is not turned on

## Expected result:
Should not show 1 notification message when rewards is turned off

## Reproduces how often: 

Easy on Linux

## Brave version (brave://version info)

Brave | 0.60.13 Chromium: 72.0.3626.53 (Official Build) dev(64-bit)
-- | --
Revision | 98434e6cd182d68ce396daa92e9c6310422e6763-refs/branch-heads/3626@{#620}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes on Dev build
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

@brave/legacy_qa to verify on other platforms @NejcZdovc

**Comment by btlechowski** [comment]
Not reproducible on Windows 7 x64. The notification goes away when brave panel is opened for the first time and never comes back. Tried reloading the page, restarting the browser. 

Brave | 0.60.13 Chromium: 72.0.3626.53 (Official Build) dev (64-bit)
-- | --
Revision | 98434e6cd182d68ce396daa92e9c6310422e6763-refs/branch-heads/3626@{#620}
OS | Windows

**Comment by NejcZdovc** [comment]
reproduced on macOS and it's a regression from this PR https://github.com/brave/brave-core/pull/1409, so we need this fix in 0.60

cc @kjozwiak @rebron

**Comment by kjozwiak** [comment]
> reproduced on macOS and it's a regression from this PR [brave/brave-core#1409](https://github.com/brave/brave-core/pull/1409), so we need this fix in 0.60
> 
> cc @kjozwiak @rebron

@NejcZdovc are we still considering uplifting this into `0.60.x`?

**Comment by NejcZdovc** [comment]
@kjozwiak I would uplift it yes. Let me create PR for it

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.60.23 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/1486
* Verified that if you don't click on the panel, navigate to brave://rewards and enable Rewards, the 1 notification goes away as well.
