### ISSUE TITLE
Swap page does not appearing on Android (brave://wallet/swap)

### ISSUE THREAD

**Issue by vadimstruts** [brave/brave-browser#29577]
## Description 

Swap page does not appearing on Android

## Steps to reproduce 

   1. Initialize wallet on android
   2. open new tab and type: `brave://wallet/swap`

## Actual result 

Page is empty and it throws exceptions in console

## Expected result

UI is displayed, throws no errors
![image](https://user-images.githubusercontent.com/118171981/230642475-9f3bbb6d-1b41-4411-986b-00e3c8fdc57e.png)

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.52.92 x64 beta build
- Verified test plan from [brave/brave-core#17981](https://github.com/brave/brave-core/pull/17981)
- Verified Swap page loads when wallet is created
- Verified Swap page is empty when wallet is not created


https://github.com/brave/brave-browser/assets/17010094/6d0f19c2-16bb-4799-acf0-424bad03e674
