### ISSUE TITLE
Adblock detected spigotunlocked.com

### ISSUE THREAD

**Issue by DasCanard** [brave/brave-browser#29572]
## Description 

https://spigotunlocked.com/ will popup a Adblock detected Banner 

I also tested the site with uBlock Origin, but there was no popup (Edge Browser).
## Steps to Reproduce

   1. Go on https://spigotunlocked.com/

## Actual result:

![image](https://user-images.githubusercontent.com/17070204/230553228-5792d0b6-c286-4efa-9c6f-478821258720.png)

## Expected result:
No Adblock detected Banner

## Reproduces how often: 

Easily reproduced

## Desktop Brave version:

1.50.114 Chromium: 112.0.5615.49 (Offizieller Build) (64-Bit) 

## Version/Channel Information:

Stable, Beta, Nightly

## Miscellaneous Information:

- my Brave shield is set to aggressive
- using following lists 
![image](https://user-images.githubusercontent.com/17070204/230554504-3e81faf9-a7f5-4329-9435-ddf090613bdc.png)

**Comment by DasCanard** [comment]
Do you maybe got a solution for that?
@ryanbr @antonok-edm

**Comment by ryanbr** [comment]
Not getting any anti-adblock message here @DasCanard Does it work in private window mode?

**Comment by DasCanard** [comment]
> Not getting any anti-adblock message here @DasCanard Does it work in private window mode?

It actually works there, I hadn't tested it there, sorry.

The reason was the "Netcraft Extension". Thanks for the hint!
