### ISSUE TITLE
BraveVpnHelper doesnt restart after crash

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#29579]
## Description 

If we add `--crash-me` flag the service is not restarted sometimes.

## Steps to Reproduce

   1. Add `--crash-me` flag to the service in the registry `HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\Brave{Channel}VpnService` -> `ImagePath`
   2.  Connect brave vpn
   3. Check service crashed, but not restarted
   4. Only one dump created in `%PROGRAMDATA%\BraveSoftware\{service name}\Crashpad`

## Actual result:

The service crashed, but not restarted and Only one dump created in `%PROGRAMDATA%\BraveSoftware\{service name}\Crashpad`

## Expected result:

The service should restart and crash again until the flag `--crash-me` removed from registry

## Reproduces how often: 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using 

Brave | 1.52.92 Chromium: 113.0.5672.92 (Official Build) beta (64-bit)
-- | --
Revision | b6f521170062a1fa8a82c33fb223b06fec566da1-refs/branch-heads/5672_63@{#10}
OS | Windows 10 Version 22H2 (Build 19045.2965)

### Steps:
1. installed `1.52.92`
2. purchased, configured, and connected to `Brave VPN`
3. disconnected from VPN and shut down Brave
4. opened `rededit` (registry editor)
5. added `--crash-me` to the `ImagePath`
6. relaunched Brave
7. reconnected to `Brave VPN`
8. confirmed I saw the `Brave VPN helper service` dialog
9. confirmed I saw the `Brave VPN Helper Service` in the `Task Manager`


![image (1)](https://github.com/brave/brave-browser/assets/387249/118c123b-0621-4610-83ef-b287c0327605)

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.52.102 Chromium: 113.0.5672.126 (Official Build) beta (64-bit)
-- | --
Revision | c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}
OS | Windows 11 Version 22H2 (Build 22621.1702)
```
### Steps:
1. installed `1.52.92`
2. purchased, configured, and connected to `Brave VPN`
3. disconnected from VPN and shut down Brave
4. opened `rededit` (registry editor)
5. added `--crash-me` to the `ImagePath`
6. relaunched Brave
7. reconnected to `Brave VPN`
8. confirmed I saw the `Brave VPN helper service` dialog
9. confirmed I saw the `Brave VPN Helper Service` in the `Task Manager`
10. opened `C:\ProgramData\BraveSoftware\BraveBetaVpnService\Crashpad\reports`

### Confirmed the Brave VPN helper service process crashed and restarted, writing crash dumps each time

step 3 | step 5 | step 8 | step 9 | step 10
-------|---------|--------|--------|------
![image](https://github.com/brave/brave-browser/assets/98358127/3dbb4e64-2286-420d-ada7-08c5398d5664)|![image](https://github.com/brave/brave-browser/assets/98358127/d94cacda-8752-4724-ae44-bc55036bfd6c)|![image](https://github.com/brave/brave-browser/assets/98358127/1be06dd8-a22b-425b-91dd-08bf091df00a)|![image](https://github.com/brave/brave-browser/assets/98358127/5062662d-76dd-4c50-a0e3-7fbd7562f8c8)|![image](https://github.com/brave/brave-browser/assets/98358127/e6a30140-c406-42c1-a844-49850210158b)
