### ISSUE TITLE
[Reader mode] Add on-demand reader mode.

### ISSUE THREAD

**Issue by boocmp** [brave/brave-browser#29570]
Change reader mode behaviour:

1. Use the current state of document instead of a full reload from the network
2. Show 'reader mode' button on pages marked as 'readable' by Chromium's ```dom_distiller::DistillabilityObserver.```

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.52.91 Chromium: 113.0.5672.77 (Official Build) beta (64-bit)
-- | --
Revision | c4236862955e005c2187105415ac4a2ecf86dff1-refs/branch-heads/5672_62@{#3}
OS | Windows 11 Version 22H2 (Build 22621.1555)
```
### Case 1:  Enable Distillability Service via command line - `PASSED`

- Installed 1.52.91
- launched Brave with `--enable-distillability-service`
- opened a new tab
- visited `https://www.cnet.com/tech/mobile/what-ios-16-and-android-13-tell-us-about-the-future-smartphones/` from [here](https://github.com/brave/brave-browser/issues/23418#issue-1268502919)
- clicked `Speedreader` icon

### Confirmed the page is distilled and is shown in reader mode/view 

Example | Example 
---- | -----
<image width="600" alt="image" src="https://user-images.githubusercontent.com/98358127/236938582-21a38b17-e0d8-4af0-93e8-107fb7f2d5e1.png">|<image width="800" alt="image" src="https://user-images.githubusercontent.com/98358127/236936346-645cc349-3dab-4ec4-acef-2a26b9b3ce2c.png">

Case 2: Enable `ReaderMode` via brave://flags - `FAILED`

- new profile
- launched Brave
- opened a new tab
- visited `https://www.cnet.com/tech/mobile/what-ios-16-and-android-13-tell-us-about-the-future-smartphones/` from [here](https://github.com/brave/brave-browser/issues/23418#issue-1268502919)


*** No `Speedreader` icon available

Example | Example 
---- | -----
<image width="800" alt="image" src="https://user-images.githubusercontent.com/98358127/236940306-5f360702-5928-4450-a5b3-97a6411b2198.png">|<image width="800" alt="image" src="https://user-images.githubusercontent.com/98358127/236940278-e299af78-83a7-4f5a-a834-819eac5abb5d.png">

**Comment by boocmp** [comment]
In brave://flags, `Reading Mode` is a new `Read Anything` feature introduced about 3 months ago. I was referring to the `Read Mode` feature, which was called "Enable Read mode" in brave://flags, but it expired in version 112, so you can't enable it in flags, only from the command line "--enable-features=ReaderMode".
