### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by krsaurabh1000** [brave/brave-browser#29578]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.50.114  Chromium: 112.0.5615.49
Operating System: Windows NT 10.0.22621

URL (if applicable) where the crash occurred: https://www.youtube.com/watch?v=e3SutBOVKok | https://www.youtube.com/watch?v=QvkpnSMHMVg

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1.
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/a0710200-cefb-e309-0000-000000000000

**Comment by iefremov** [comment]
Thanks for the report @krsaurabh1000 , this was our of memory... Doesn't look very actionable by us.
