### ISSUE TITLE
BR Panel momentarily flashes Welcome page before showing Rewards is off message

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#2958]
## Description 

BR Panel momentarily flashes Welcome page before showing Rewards is off message

## Steps to Reproduce

1. Clean profile on Linux
2. Click the BR panel immediately after the browser is launched
3. BR panel flashes the welcome message before showing the Rewards off message

## Actual result:

BR Panel momentarily flashes Welcome page before showing Rewards is off message

## Expected result:
Should not show the welcome message if rewards isn't enabled

## Reproduces how often: 

Easy on Linux but you have to be very quick in noticing it

## Brave version (brave://version info)

Brave | 0.60.13 Chromium: 72.0.3626.53 (Official Build) dev(64-bit)
-- | --
Revision | 98434e6cd182d68ce396daa92e9c6310422e6763-refs/branch-heads/3626@{#620}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes on Dev build
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

@brave/legacy_qa to verify on other platforms, @NejcZdovc

**Comment by btlechowski** [comment]
Not reproducible on Windows 7 x64. 

Brave | 0.60.13 Chromium: 72.0.3626.53 (Official Build) dev (64-bit)
-- | --
Revision | 98434e6cd182d68ce396daa92e9c6310422e6763-refs/branch-heads/3626@{#620}
OS | Windows

**Comment by GeetaSarvadnya** [comment]
Not reproducible on windows 10 x64.

Brave | 0.60.13 Chromium: 72.0.3626.53 (Official Build) dev (64-bit)
-- | --
Revision | 98434e6cd182d68ce396daa92e9c6310422e6763-refs/branch-heads/3626@{#620}
OS | Windows 10

**Comment by NejcZdovc** [comment]
closing as stale
