### ISSUE TITLE
Manually-blocked script source shows as `null` in Shields' `Blocked count` section

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#29585]
## Description 

Manually-blocked script source shows as `null` in Shields' `Blocked count` section

## Steps to Reproduce

1. installed `1.52.23`
2. launched Brave
3. logged in to `facebook.com` (yes, sorry, this is a requirement for this issue)
4. loaded `https://apps.facebook.com/wordswithfriends`
5. clicked on the `Shields` icon in the URL bar
6. clicked to toggle `Block scripts` to `On` / `Enabled`
7. clicked on the blocked-count #
8. clicked `Allow` beside `https://apps.facebook.com`
9. looked at the resulting path(s), under `20 Blocked scripts`

## Actual result:

`null` type/value shows up:

<img width="1312" alt="Screenshot 2023-04-08 at 12 26 29 AM" src="https://user-images.githubusercontent.com/387249/230709384-9035e568-91c3-438b-8833-017de96729e7.png">

example | example | example | example | example | example
---------|----------|---------|----------|----------|---------
<img width="1312" alt="Screenshot 2023-04-08 at 12 26 12 AM" src="https://user-images.githubusercontent.com/387249/230709547-7938e3df-a8e6-407c-bbe6-4053cf455175.png"> | <img width="1312" alt="Screenshot 2023-04-08 at 12 26 16 AM" src="https://user-images.githubusercontent.com/387249/230709549-6f34b0f2-2c54-466d-a678-93c488a85ffa.png"> | <img width="1312" alt="Screenshot 2023-04-08 at 12 26 22 AM" src="https://user-images.githubusercontent.com/387249/230709551-9b86bbd9-097a-4ed0-a7c0-6cefebfc7828.png"> | <img width="1312" alt="Screenshot 2023-04-08 at 12 26 29 AM" src="https://user-images.githubusercontent.com/387249/230709552-a25d2c5f-81be-469c-9018-8eb53f5c82fd.png"> | <img width="1312" alt="Screenshot 2023-04-08 at 12 26 34 AM" src="https://user-images.githubusercontent.com/387249/230709553-3d3fdd3f-f298-4751-ab7b-4ada490e9692.png"> | <img width="1312" alt="Screenshot 2023-04-08 at 12 27 01 AM" src="https://user-images.githubusercontent.com/387249/230709555-7286a204-1a57-4d6e-a7d0-ea0207e71c98.png">

`
null
application/x-javascript; charset=utf-8;base64,Oy8qRkJfUEtHX0RFTElNKi8KCl9fYW5ub3RhdG9yPWZ1bmN0aW9uKGEpe3JldHVybiBhfSxfX2Rfc3R1Yj1bXSxfX2Q9ZnVuY3Rpb24oYSxiLGMsZCxlKXtfX2Rfc3R1Yi5wdXNoKFthLGIsYyxkLGVdKX0sX19ybF9zdHViPVtdLHJlcXVpcmVMYXp5PWZ1bmN0aW9uKCl7X19ybF9zdHViLnB1c2goYXJndW1lbnRzKX07Ci8vIyBzb3VyY2VVUkw9aHR0cHM6Ly9zdGF0aWMueHguZmJjZG4ubmV0L3JzcmMucGhwL3YzL3lYL3IvUkJDYnp3T0NsU3IuanM/X25jX3g9bkpGMUhzSTcxYkMK
`

## Expected result:

Actual FQDN/script URL

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.52.23 Chromium: 112.0.5615.49 (Official Build) nightly (x86_64)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | macOS Version 13.4 (Build 22F5027f)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

/cc @MadhaviSeelam @spylogsster @rebron @pes10k @bsclifton

**Comment by stephendonner** [comment]
Also cc @fmarier

**Comment by pes10k** [comment]
Guessing this is what happens for scripts w/o sources?  If thats the case, it should report the domain / site used for executing the frame (which most, but not all, of the time will just be from `document.location`)

**Comment by kjozwiak** [comment]
The above requires `1.51.95` or higher for `1.51.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.51.95 Chromium: 112.0.5615.121 (Official Build) beta (x86_64)
-- | --
Revision | 39cc4e45904ae9f1741c4fbaa866e629c96f2268-refs/branch-heads/5615_51@{#8}
OS | macOS Version 11.7.6 (Build 20G1231)

### Steps:

1. installed `1.51.95`
2. launched Brave
3. logged in to facebook.com (yes, sorry, this is a requirement for this issue)
4. loaded `https://apps.facebook.com/wordswithfriends`
5. clicked on the `Shields` icon in the URL bar
6. clicked to toggle `Block scripts` to `On` / `Enabled`
7. clicked on the blocked-count #
8. clicked `Allow` beside `https://apps.facebook.com`
9. looked at the resulting path(s), under `20 Blocked scripts`

#### Confirmed there were no longer instances of `null` for either `Allowed` or `Blocked scripts`

example | example | example | example
---------|----------|---------|---------
<img width="1769" alt="Screen Shot 2023-04-18 at 2 15 55 PM" src="https://user-images.githubusercontent.com/387249/232907522-51873919-de5b-4505-ad02-d02542f6f692.png"> | <img width="1769" alt="Screen Shot 2023-04-18 at 2 16 22 PM" src="https://user-images.githubusercontent.com/387249/232907528-26c8c39f-c644-4f23-8333-6106457723d0.png"> | <img width="1769" alt="Screen Shot 2023-04-18 at 2 16 44 PM" src="https://user-images.githubusercontent.com/387249/232907533-da56c339-963b-4757-8247-2997fd4cb054.png"> | <img width="1769" alt="Screen Shot 2023-04-18 at 2 17 08 PM" src="https://user-images.githubusercontent.com/387249/232907541-69c61fd5-bad8-4de0-919c-da45a7dd0398.png">
