### ISSUE TITLE
Youslist conflicts with other lists with brave browser

### ISSUE THREAD

**Issue by zekecarter** [brave/brave-browser#29595]
## Description 
the list (youslist) causes crashes when using other lists to remove anti adblockers from the Filecr.com website and other web pages as well, within the Brave browser.

## Steps to Reproduce

   1. open browser
   2. enter filecr.com
   3. click on any program to download and click on direct download

## Actual result and Expected result:

https://user-images.githubusercontent.com/83554130/230837343-78042f9a-bf73-477e-a59d-7bce6390d765.mp4

## Brave version (brave://version info)
1.50.114 Chromium: 112.0.5615.49 (Build oficial) (64 bits) 

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? yes

**Comment by rebron** [comment]
cc: @ryanbr

**Comment by ryanbr** [comment]
Thanks for the notification. @zekecarter 

https://github.com/yous/YousList/commit/4d72dd79701c037dd6ce92ea30d7ce7cb072e3f1  Commited 8hrs ago, lets see if this fixes it (give it 24hrs to roll out). 

Would avoid enabling every list btw, would slow things down and create false positives.

**Comment by zekecarter** [comment]
> Thanks for the notification. @zekecarter
> 
> [yous/YousList@4d72dd7](https://github.com/yous/YousList/commit/4d72dd79701c037dd6ce92ea30d7ce7cb072e3f1) Commited 8hrs ago, lets see if this fixes it (give it 24hrs to roll out).
> 
> Would avoid enabling every list btw, would slow things down and create false positives.

sorry it still doesn't work, the youslist filter conflicts with other lists.

I have tried with the ublockorigin custom list specifically (quick-fixes) and it works fine, but keeping the youslist disabled because if I enable the youslist it stops working.

here is the link to the ublockorigin list (quick-fixes) and an example video:
https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/quick-fixes.txt

https://user-images.githubusercontent.com/83554130/231182873-183ef6ed-3e2d-46fd-b225-fbb04a4a9170.mp4

**Comment by ryanbr** [comment]
https://github.com/brave/adblock-lists/pull/1137  

Give it 24/48hrs. see if this helps.

**Comment by zekecarter** [comment]
> Resolved with default shields now ? @zekecarter

Solved 😁 thank you!!!
