### ISSUE TITLE
Closing a pinned tab with wheel button doesn't trigger layout

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#29594]
## Description 

We have empty space when closing a pinned tab with wheel button

## Steps to Reproduce

   1. Pin tabs in vertical tabs
   2. Close a pineed tab in the middle of tabs

## Actual result:

<img width="282" alt="image" src="https://user-images.githubusercontent.com/5474642/230835806-bd2187c9-e4e7-4ebe-8db2-316ee15fc80d.png">

## Expected result:
<img width="256" alt="image" src="https://user-images.githubusercontent.com/5474642/230835867-b26fc286-a0da-4b9d-9d0c-419e3bf61f9a.png">

## Reproduces how often: 

Always

## Brave version (brave://version info)

Nightly

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A - behind flag
- Can you reproduce this issue with the beta channel? Yes - flag is enabled by default
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.51.87` or higher for `1.51.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.51.87 Chromium: 112.0.5615.49 (Official Build) beta (64-bit) 
--|--
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Windows 10 Version 22H2 (Build 19045.2846)

### Steps:
1. installed `1.51.87`
2. launched Brave
3. enabled `Use vertical tabs` flag in `about://flags`
4. clicked `Relaunch`
5. loaded a few sites
6. context-clicked on a tab and chose `Use vertical tabs`
7. pinned a bunch of tabs
8. context-clicked on a middle tab
9. chose `Close`
10. compared results to `1.51.79`

### Confirmed there's no empty slot in the tab strip after closing any tab(s)

### `1.51.87`

example | example | example | example
----------|----------|------------|---------
![image (3)](https://user-images.githubusercontent.com/387249/231846455-8070dae2-1660-49d6-af82-1d0cb050d158.png) |  ![image (4)](https://user-images.githubusercontent.com/387249/231846485-9fbfefea-e2ae-42ca-8b5d-e207f293e39f.png) | ![image (5)](https://user-images.githubusercontent.com/387249/231846537-26de86ba-bc8f-4e2f-abb0-ffdb3e0124ed.png) | ![image (6)](https://user-images.githubusercontent.com/387249/231846535-e2727f62-0165-432e-8e22-d3042f0ebefe.png)





### `1.51.79`

example | example | example
----------|----------|-----------
![image (2)](https://user-images.githubusercontent.com/387249/231846197-e0438871-55f8-41de-9c9b-fec55d34d388.png) | ![image (1)](https://user-images.githubusercontent.com/387249/231846199-93bda5b9-ffac-4ee4-a815-8fc7725246bd.png) | ![image](https://user-images.githubusercontent.com/387249/231846202-4ebd0a20-f6e5-4a6f-a274-ce35e99398c8.png)
