### ISSUE TITLE
Tab search bubble should be opened under the button on the frame

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#29592]
original report: https://github.com/brave/brave-browser/issues/24717#issuecomment-1501186375

On Windows 10, the tab search button is on the window frame. But tab search bubble still opens next to the vertical tab strip. The bubble should open as it was - below the tab search button on the frame.

## Steps to reproduce
* Press Ctrl + Alt + A on Windows 10, which has the tab search button on the frame while the vertical tab strip is enabled.

## Actual
* Tab search bubble is shown next to vertical tab strip, even the search button isn't there
![brave_2023-04-09_11-46-23](https://user-images.githubusercontent.com/122518587/230788425-8ff85c9a-5137-4947-97f6-8684ca447849.gif)

## Expected
* The bubble should be shown under the bubble.
<img width="1044" alt="image" src="https://user-images.githubusercontent.com/5474642/230808611-d86ff38d-9079-47a3-9ff5-74a67f0b9160.png">

As Vertical tab strip feature flag is enabled by default, we should uplift this to Beta.

**Comment by kjozwiak** [comment]
The above requires `1.51.87` or higher for `1.51.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.51.87 Chromium: 112.0.5615.49 (Official Build) beta (64-bit)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Windows 11 Version 22H2 (Build 22621.1555)
```
Install 1.51.87
launched Brave
opened `brave://flags` in a new tab
selected `Enabled` for `#brave-vertical-tabs`
clicked Relaunch
visited bbc.com
right clicked on the tab to open context menu
enabled `Use vertical tabs`
added few more tabs to Vertical tabs side panel
clicked keyboard shortcut `Ctrl + Shift + A` for the Search tabs button

- Confirmed  Search list opened under the `Search tabs` arrow when clicked `Ctrl+Shift+A` 
- Confirmed  Search list opened under the `Search tabs` arrow when clicked `Search tabs` on the top right in the title bar 

![image](https://user-images.githubusercontent.com/98358127/232540103-2917a9f6-ce2b-499e-ab0a-af9ed9127136.png)
