### ISSUE TITLE
Vertical tab strip's toggle button doesn't have tooltip

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#29593]
![image](https://user-images.githubusercontent.com/5474642/230809889-3e1dace5-3c81-45b6-91fe-a0c12a118b0f.png)

Should be `minimize tabs` / `expand tabs`

---

As Vertical tab strip feature flag is enabled by default, we should uplift this to Beta.

**Comment by kjozwiak** [comment]
The above requires `1.51.86` or higher for `1.51.x` verification 👍
