### ISSUE TITLE
Make BAT browser action extension to show next to Brave one

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#296]
Each extension can have at most one browser action and this seems needed for ledger 2.0.

**Comment by bbondy** [comment]
I actually do prefer it as WebUI but I don't think we'll get brave-extension in time converted to WebUI too.  So not sure if it will work for UI consistently.  It's probably best to do it from the start in WebUI.

**Comment by bbondy** [comment]
I don't think the page will make the network requests though, it can call into C++ which can do it though.

**Comment by NejcZdovc** [comment]
@bbondy page will not make any network requests, everything will be done via C++

**Comment by petemill** [comment]
Duplicate of https://github.com/brave/brave-browser/issues/669
