### ISSUE TITLE
Implement Smart Truncation for extracted article content

### ISSUE THREAD

**Issue by nullhook** [brave/brave-browser#29608]
Currently, the article distiller feature truncates the content naively to 9k characters. However, this can lead to summaries that look incomplete and cut off from sentence run-ons.

To improve the quality of the generated summaries, it would be beneficial to implement smart truncation in the article summary feature. This would involve in capturing all parts of the content necessary for a coherent summary, while still meeting the character limitation requirements.

One possible implementation of smart truncation would be to extract a sentence from each paragraph of the content, ensuring that the summary includes key information from all parts of the article. Additionally, the feature could prioritize summarizing the introduction and conclusion sections of the article, as they typically provide a good overview of the content.

**Comment by stevelaskaridis** [comment]
Related: https://github.com/brave/aichat/issues/11#issuecomment-1687622659
