### ISSUE TITLE
Implement real-time text streaming in AI Chat

### ISSUE THREAD

**Issue by nullhook** [brave/brave-browser#29607]
Currently, the AI Chat feature consumes HTTP responses that wait for the entire text to be generated before returning to the user. This can lead to a delay in the user's ability to see the words as it is being generated, which can impact the overall user experience.

It would be beneficial to implement real-time text streaming in the AI Chat feature. This would allow users to see the words being generated as they are typed, providing a more interactive and engaging experience

**Comment by LaurenWags** [comment]
@rebron @nullhook could you please add the following required labels as necessary:
- `QA/Yes` or `QA/No` (if `QA/Yes`, please provide a manual test plan)
- `release-notes/include` or `release-notes/exclude`

Thanks!

**Comment by nullhook** [comment]
Added a test plan

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.55.79 Chromium: 115.0.5790.40 (Official Build) nightly (64-bit)
-- | --
Revision | 8e88e8a303d83c88737e91375a2cbdb98ca6759e
OS | Windows 10 Version 22H2 (Build 19045.3155)
