### ISSUE TITLE
NFT loading indicator is placed on the top left corner of the window 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#29616]
## Description 
NFT loading indicator is placed on the top left corner of the window 

## Steps to reproduce 

   1. Add an NFT to account
   2. Switch to NFT tab
   3. Loading indicator is shown on the top left corner of the NFT tab

## Actual result 

Mobile | Tablet
-- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/231142030-45f74c1a-82e5-4a9f-91cd-d0f868fab4ce.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/231142051-3bd48b73-1817-46fc-840a-929ffee8e1cb.png>

## Expected result
TBD by @brave/design-team 

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): All
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.51.79

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @simoarpe @jamesmudgett @minkyeongshin @kleantzogu @SergeyZhukovsky

**Comment by simoarpe** [comment]
Issue fixed when Wallet switched to WebUI implementation. I'm closing this.
