### ISSUE TITLE
Update IPFS banner text

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#29613]

**Comment by kjozwiak** [comment]
The above requires `1.51.87` or higher for `1.51.x` verification 👍

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.51.97 Chromium: 112.0.5615.138 (Official Build) beta (64-bit)
-- | --
Revision | `2258f2fcaeb07bc95c992b7ca47f0b43ead9865c-refs/branch-heads/5615@{#1282}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from [brave/brave-core#17987](https://github.com/brave/brave-core/pull/17987)
- Verified IPFS banner text is updated 

https://user-images.githubusercontent.com/17010094/233960558-8e8e6fc4-a679-4639-9edd-6198bdae4ba0.mp4
