### ISSUE TITLE
Hover state indicator is not positioned in centre when vertical tabs are in collapsed state

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#29614]
## Steps to Reproduce

   1. Enable vertical tabs flag
   2. Set vertical tabs to collapsed state
   3. Hover over the tab 
   4. Hover state is not positioned correctly on the close button

## Actual result:

https://user-images.githubusercontent.com/17010094/231092642-e0e9ed5e-60ae-4b16-b9a9-7f03ae7b9fb2.mp4

## Expected result:
Hover state should be properly positioned on close button

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.52.26 Chromium: 112.0.5615.49 (Official Build) nightly (64-bit)
-- | --
Revision | `bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}`
OS | Windows 11 Version 22H2 (Build 22621.1485)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @sangwoo108 @simonhong @rebron

**Comment by kjozwiak** [comment]
The above requires `1.51.98` or higher for `1.51.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.51.99 Chromium: 112.0.5615.165 (Official Build) beta (64-bit)
-- | --
Revision | c262f36e6b1d711ee42d4fbe1343b49960593f18-refs/branch-heads/5615@{#1297}
OS | Windows 10 Version 22H2 (Build 19045.2846)

### Followed the inline steps to reproduce

### Confirmed the `x` hover-state highlight image is centered, in both `Dark` and `Light` modes

`Dark` | `Light`
-------|--------
![Capture](https://user-images.githubusercontent.com/387249/233746011-c41e9a9f-4982-4cab-b9fc-c0f7a4a11ac5.PNG) | ![image](https://user-images.githubusercontent.com/387249/233745978-dc0f58ee-40cb-461f-87ab-b857dcf869ad.png)

`Dark`, large | `Light`, large
--------------|--------------
![image](https://user-images.githubusercontent.com/387249/233746243-c87521ea-156e-4fb7-b590-15d95d9bb334.png) | ![image](https://user-images.githubusercontent.com/387249/233746277-a25f98ff-c719-4431-8687-a5c193ce337b.png)
