### ISSUE TITLE
Crash Report - Been crashing frequently today !

### ISSUE THREAD

**Issue by pgthevenkat** [brave/brave-browser#29619]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.50.114  Chromium: 112.0.5615.49
Operating System: Mac OS X 13.2.1

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1.
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/88c50500-cefb-e309-0000-000000000000

**Comment by iefremov** [comment]
@pgthevenkat unfortunately, this is not actionable without steps to reproduce, please share if any and reopen the issue.
