### ISSUE TITLE
Update Portfolio Line Chart Colors

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#29610]
## Description 

We need to update the `Portfolio` line chart colors to match the new Designs in Figma

![Screenshot 62](https://user-images.githubusercontent.com/40611140/231003105-878f547d-3dcd-4429-a55a-06a1e9f4abc6.png)

![Screenshot 61](https://user-images.githubusercontent.com/40611140/231003112-b2b16949-97d9-4690-9183-038fd24e4df4.png)

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/29834#issuecomment-1547926781
