### ISSUE TITLE
Enable Brave VPN by default

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#29612]
## Test plan
See https://github.com/brave/brave-core/pull/17989

## Description 
VPN is enabled now via a Griffin experiment `CrossPlatformVPNStudy` which enable the following features:
- BraveVPN
- BraveVPNLinkSubscriptionAndroidUI

These features are enabled for all channels (Nightly, Beta, Release) and percentage is at 100%. We should enable this by default so that we can remove the Griffin experiment.

**Comment by stephendonner** [comment]
## Verification `PASSED` using 

Brave | 1.52.85 Chromium: 113.0.5672.63 (Official Build) beta (x86_64)
-- | --
Revision | 0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}
OS | macOS Version 11.7.6 (Build 20G1231)

### Steps:
1. installed `1.52.85`
2. launched Brave
3. confirmed `VPN` button on the toolbar
4. clicked to confirm`Buy`/`Already purchased VPN?` dialog
5. opened `brave://flags`
6. confirmed `brave://flags/#brave-vpn` is set to `Default`


`Brave VPN dialog` | brave://flags
--------------------|--------------
<img width="1551" alt="Screen Shot 2023-05-03 at 4 02 30 PM" src="https://user-images.githubusercontent.com/387249/236069560-2acf6181-726e-458a-a932-5c083dd37a9a.png"> | <img width="1551" alt="Screen Shot 2023-05-03 at 4 04 07 PM" src="https://user-images.githubusercontent.com/387249/236069572-951a424f-0f9d-4f26-abe0-623b6f4cf88b.png">

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.52.92 Chromium: 113.0.5672.92 (Official Build) beta (64-bit)
-- | --
Revision | b6f521170062a1fa8a82c33fb223b06fec566da1-refs/branch-heads/5672_63@{#10}
OS | Windows 10 Version 22H2 (Build 19045.2913)

### Steps:
1. installed `1.52.92`
2. launched Brave
3. confirmed `VPN` button on the toolbar
4. clicked to confirm `Buy` / `Already purchased VPN?` dialog
5. opened `brave://flags`
6. confirmed `brave://flags/#brave-vpn` is set to `Default`

**Comment by stephendonner** [comment]
@MadhaviSeelam mind verifying on Windows 11, and slapping on `QA-Pass/Win64`, when you do?  Thanks!

**Comment by kjozwiak** [comment]
The above requires `1.51.116` or higher for `1.51.x` verification. Going to remove the `QA Pass` labels as we'll need to retest on `1.51.x` once we get the RC builds.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.51.117 Chromium: 113.0.5672.92 (Official Build) (64-bit)
-- | --
Revision | b6f521170062a1fa8a82c33fb223b06fec566da1-refs/branch-heads/5672_63@{#10}
OS | Windows 11 Version 22H2 (Build 22621.1702)
```


1. installed `1.51.117`
2. launched Brave
3. confirmed `VPN` button on the toolbar
4. clicked to confirm `Buy` / `Already purchased VPN?` dialog
5. confirmed successfully logged into VPN with existing prod credentials
6. opened `brave://flags`
7. confirmed `brave://flags/#brave-vpn` is set to `Default`

step 3-4 | step 5 | step 6-7
---- | ---- | -----
![image](https://github.com/brave/brave-browser/assets/98358127/5f099e95-b2fe-42f4-9e34-17d585df9e26)|!![image](https://github.com/brave/brave-browser/assets/98358127/8d62e6d6-cdab-41b0-b1fc-f38461cacf5d)|![image](https://github.com/brave/brave-browser/assets/98358127/1e9f6e18-9b79-4b2f-9beb-989586442134)

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.51.117 Chromium: 113.0.5672.92 (Official Build) (x86_64)
-- | --
Revision | b6f521170062a1fa8a82c33fb223b06fec566da1-refs/branch-heads/5672_63@{#10}
OS | macOS Version 11.7.6 (Build 20G1231)

### Steps:
1. installed `1.51.117`
2. launched Brave
3. confirmed `VPN` button on the toolbar
4. clicked to confirm `Buy`/`Already purchased VPN....?` dialog
5. opened `brave://flags`
6. confirmed `brave://flags/#brave-vpn` is set to `Default`

`Brave VPN` dialog | `brave://flags`
--------------------|---------------
<img width="1312" alt="Screen Shot 2023-05-16 at 9 50 04 AM" src="https://github.com/brave/brave-browser/assets/387249/9bf43867-ba9c-44d5-bdb3-cd99dadc93be"> | <img width="1312" alt="Screen Shot 2023-05-16 at 9 50 15 AM" src="https://github.com/brave/brave-browser/assets/387249/5f4ee8e1-d460-4e8e-9ff8-0a5d80b5bfb2">

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

### Steps:
1. installed `1.51.117`
2. launched Brave
3. confirmed `VPN` button in the toolbar
4. clicked to confirm `Buy`/`Already purchased...?` dialog
5. opened `brave://flags`
6. confirmed `brave://flags/#brave-vpn` is set to `Default`

`Brave VPN` dialog | `brave://flags`
----------------------|---------------
![image](https://github.com/brave/brave-browser/assets/387249/c655919e-0e3a-4c17-93e6-c6b5afdaedf2) | ![image](https://github.com/brave/brave-browser/assets/387249/d9f5b6f0-c81b-47cd-83ac-3264f460f5fc)

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21 5G` using the following version(s):

```
Brave	1.51.118 Chromium: 113.0.5672.126 (Official Build) (64-bit) 
Revision	c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

Using **Test Plan** in https://github.com/brave/brave-core/pull/15602#issue-1418938955

1. Install 1.51.118
2. Open menu, tap on VPN
3. Purchase using IAP
4. Install VPN profile
5. Open VPN settings and confirm subscription
6. Confirm Link Subscription option is available in the VPN settings
7. Confirm tapping on Link Subscription will open account.brave.com with intent params
8. Open app switcher and close brave app
9. Relaunch brave, confirm VPN link subscription callout is shown

- Confirmed `Brave VPN` is shown in the menu on fresh install.
- Confirmed VPN connection is enabled after installing profile.
- Confirmed `Link purchase to your Brave account` option is shown in settings and callout is presented to user.

Example | Example | Example | Example
-|-|-|-
![screenshot-1684333090305](https://github.com/brave/brave-browser/assets/17885425/99a38727-1035-4e64-b9f8-1f6cd41bb59e) | ![screenshot-1684333977235](https://github.com/brave/brave-browser/assets/17885425/14b8549b-19c5-4110-a4c1-a7e7ee21ab33) | ![screenshot-1684334942009](https://github.com/brave/brave-browser/assets/17885425/433eaa17-738e-42a6-8930-0be76681d255) | ![screenshot-1684334956979](https://github.com/brave/brave-browser/assets/17885425/0376a59b-5908-4393-abad-cafa9893a839)
