### ISSUE TITLE
Rewards ON/OFF state is not same on different Reward tabs

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#2961]
## Description 
When user turned on/off Rewards, the changes should get reflect on all the opened rewards pages. But, currently it's taking effect on only one page which is wrong. 

## Steps to Reproduce

1. Create a new profile with staging variable
2. Enable rewards through Welcome page 
3. Turn OFF the rewards switch 
4. Verify, user cannot accept UGP grants from both places (From CLAIM button and URL grants notification)
5. Click on `Settings` in BR panel and see Rewards page opened and Rewards switch is OFF
6. Turn on the Rewards
7. Open the BR panel and DND the Source captcha outside the BR panel
8. Navigate to other rewards page and see 

## Actual result:
- Rewards switch is OFF 
Rewards is turned ON in step 6, So, we should be able to see Rewards ON in all other opened tabs instead of OFF state.

https://drive.google.com/open?id=1f2LJNjW5Uml-Ui4dmAdAqSh4Hcg0YMEN
## Expected result:
Rewards ON/OFF state in one page should get reflect on all other opened Rewards pages/tabs.

## Reproduces how often: 
Always

## Brave version (brave://version info)

Brave | 0.60.13 Chromium: 72.0.3626.53 (Official Build) dev (64-bit)
-- | --
Revision | 98434e6cd182d68ce396daa92e9c6310422e6763-refs/branch-heads/3626@{#620}
OS | Windows 10

### Reproducible on current release: NA
- Does it reproduce on brave-browser dev/beta builds? Dev build 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional Information

@brave/legacy_qa

**Comment by NejcZdovc** [comment]
it looks like that just that pages didn't received event that rewards were turned on. So I think the problem is not that you can claim grant when rewards are off (you enabled them, so they are not off), but the problem is that if you have multiple rewards page opened and you enable rewards in one, this is not reflected in all of them

**Comment by GeetaSarvadnya** [comment]
@NejcZdovc Updated the Appropriate subejct for the issue.

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.60.25 Chromium: 72.0.3626.96 (Official Build) beta (64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Windows 10
  
- Verified the STR mentioned in the description
- Logged https://github.com/brave/brave-browser/issues/3309
