### ISSUE TITLE
enabling rewards via the panel doesn't always display the welcome screen and doesn't always correctly create the wallet

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#2962]
## Description 

There seems to be several issues with `0.60.x` where pressing on the `Rewards` panel causes several unexpected results, examples:

* pressing on the `Rewards` panel under `0.60.13` before the notification appears doesn't display the `Welcome` screen and displays a `Rewards has been disabled` message. Please see examples outlined below.

* pressing on the `Rewards` panel on `0.60.10` and other lower `0.60.x` versions will automatically open the `Rewards Summary` panel even though the user hasn't enabled rewards. This causes several issue including creating an empty `ledger-state` file thats missing it's values:

```{"walletInfo":{"paymentId":"","addressBAT":"","addressBTC":"","addressCARD_ID":"","addressETH":"","addressLTC":"","keyInfoSeed":""},"bootStamp":0,"reconcileStamp":0,"last_grant_fetch_stamp":1547539523,"personaId":"","userId":"","registrarVK":"","masterUserToken":"","preFlight":"","fee_currency":"","settings":"adFree","fee_amount":0.0,"user_changed_fee":false,"days":0,"rewards_enabled":false,"auto_contribute":false,"transactions":[],"ballots":[],"ruleset":"","rulesetV2":"","batch":[],"current_reconciles":{}}```

Spent ~1.5hrs with @NejcZdovc debugging this and ended up reproducing similar issues on all the of the `0.60.x` versions. @NejcZdovc also ended up reproducing the issue on his VM.

Making this as a `release/blocking` as this could screw up a lot of wallets on the `dev` channel.

## Steps to Reproduce

   1. launch any of the `0.60.x` versions and click on the `Brave` panel

You'll reproduce 100% when you don't see the initial notification appear within the `Rewards` panel.

## Actual result:

![braverewards](https://user-images.githubusercontent.com/2602313/51166453-8566f900-1871-11e9-8bf5-51cc4b4337e6.gif)

<img width="1069" alt="screen shot 2019-01-15 at 3 17 35 am" src="https://user-images.githubusercontent.com/2602313/51167379-75044d80-1874-11e9-92b6-2f5a804e1ba9.png">

![braverewards](https://user-images.githubusercontent.com/2602313/51167140-b5af9700-1873-11e9-890f-a1e41106a37d.gif)

## Expected result:

Clicking on the `Rewards` panel should always display the `Welcome` screen within the panel for new users.

## Reproduces how often: 

90% reproducible, @NejcZdovc witnessed this happening quiet a few times when we were on the Zoom call attempting to figure what's going on with the `Rewards` panel.

## Brave version (brave://version info)

Brave | 0.60.13 Chromium: 72.0.3626.53 (Official Build) dev (64-bit)
--- | ---
Revision | 98434e6cd182d68ce396daa92e9c6310422e6763-refs/branch-heads/3626@{#620}
OS | Windows

Brave | 0.60.10 Chromium: 72.0.3626.28 (Official Build) dev (64-bit)
--- | ---
Revision | 997b1040b63bac324e815797ba52be0cd8f616ed-refs/branch-heads/3626@{#461}
OS | Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

Couldn't reproduce this with the latest `0.59.x` but I'm assuming once we get the newest build, this issue might have been uplifted into `0.59.x` as well. Will double check once we get new builds. `v0.59.21` was built ~6 days ago.

### Additional Information

https://github.com/brave/brave-browser/issues/2958 might be related to this issue as well. CCing @NejcZdovc @brave/legacy_qa

**Comment by kjozwiak** [comment]
I can reproduce this on `Win 10 x64 VM` using the following build:

Brave | 0.59.24 Chromium: 72.0.3626.53 (Official Build) beta (64-bit)
--- | --- 
Revision | 98434e6cd182d68ce396daa92e9c6310422e6763-refs/branch-heads/3626@{#620}
OS | Windows

Example of the issue occurring on `0.59.24 Chromium: 72.0.3626.53`:

![braverewards](https://user-images.githubusercontent.com/2602313/51226816-337cac80-191f-11e9-91a8-411a229f63cd.gif)

**Comment by srirambv** [comment]
Possibly related to #1429

**Comment by NejcZdovc** [comment]
@kjozwiak @rebron moved this into 0.59 as it's showing there now as well

**Comment by btlechowski** [comment]
Verification passed on Ubuntu 17.10

Brave | 0.59.28 Chromium: 72.0.3626.64 (Official Build) beta(64-bit)
-- | --
Revision | eaa9668e80ce5405e7f1902579558ea725c06ca1-refs/branch-heads/3626@{#708}
OS | Linux

I could not reproduce it after 30 tries.
