### ISSUE TITLE
crash when changing IPFS size

### ISSUE THREAD

**Issue by serkonda7** [brave/brave-browser#29621]
## Description 

Brave crashes when setting IPFS cache size below one.

## Steps to Reproduce

   1. got to settings page and search for `ipfs`
   2. locate `Maximum IPFS cache size (GB)`
   3. Enter a value below 1, e.g. `0.5`
   4. click out of the input field and observe crash

## Actual result:

Browser crashes

## Expected result:
- Either: Provide an error message that the value is not supported
- Or: do not crash 

## Reproduces how often: 

Always

## Brave version (brave://version info)

1.50.114 Chromium: 112.0.5615.49 (Official Build) (64-bit)
--
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Linux
JavaScript | V8 11.2.214.9

## Version/Channel Information:

I have not tried other channels.

**Comment by hashmi-waseem** [comment]
Steps to reproduce this crash:

1. go to brave://settings/web3
2. Scroll down to IPFS section
3. Change the 'Method to resolve IPFS resources' to 'Brave local IPFS node'
4. Scroll down to the option 'Maximum IPFS cache size (GB)' (bottom of IPFS section)
5. Enter any decimal value (eg. 1.5)
6. Press enter button on the keyboard
7. Observe the browser crash

Issue occurs on version: [Version 1.65.126 Chromium: 124.0.6367.118 (Official Build) (64-bit)]

Fix for the issue: https://github.com/hashmi-waseem/brave-core/commit/454d43eeed5a88625989096789d5bf82bdb5720e

![Screenshot (4)](https://github.com/brave/brave-browser/assets/93036184/4e130952-a267-419e-a55f-9c2701ff50a3)
