### ISSUE TITLE
Able to DND source captch from brave rewards CLAIM button page

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#2963]
## Description 
Able to DND source captch from brave rewards CLAIM button page

## Steps to Reproduce

   1. Clean profile 0.60.13
   2. Enable rewards through Welcome page or Hamburger menu
   3. Click CLAIM button
   4. DND the source captcha into URL bar

## Actual result:
Able to DND source captcha. It's loading image source instead of Image, Also its trying to load the png via `Brave://rewards...`

![dnd captch source from brave rewards page](https://user-images.githubusercontent.com/38657976/51170704-158a5a00-18d5-11e9-9c85-8be7eb7bb801.gif)

## Expected result:
As per my knowledge, it shouldn't allow Captcha to DND into the URL bar.

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 0.60.13 Chromium: 72.0.3626.53 (Official Build) dev (64-bit)
-- | --
Revision | 98434e6cd182d68ce396daa92e9c6310422e6763-refs/branch-heads/3626@{#620}
OS | Windows

### Reproducible on current release: yes
- Does it reproduce on brave-browser dev/beta builds? yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional Information

@brave/legacy_qa

**Comment by NejcZdovc** [comment]
this is image, so it can be dropped into url bar. And we can't do really anything about it. Closing for now
