### ISSUE TITLE
Implement selected network per origin (Android)

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#29635]
Parent issue: https://github.com/brave/brave-browser/issues/24414

Core network related API will have optional `Origin` when setting/getting network. If origin is not provided, a fallback default network will be used. (one per coin type)

**Comment by darkdh** [comment]
Update:

1. `JsonRpcService.getChainId(CoinType coin, url.mojom.Origin? origin)` has been split into `GetDefaultChainId` and `GetChainIdForOrigin`
2. There are convenient methods `GetChainIdForActiveOrigin` and `SetChainIdForActiveOrigin` in `BraveWalletService` can be used if `BraveWalletServiceDelegate::GetActiveOrigin` has been implemented properly on the platform

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.57.27 x64 Beta build
- Verified steps from [brave/brave-core#18921](https://github.com/brave/brave-core/pull/18921)
- Verified different origin retains different network selection
- Encountered [#31946](https://github.com/brave/brave-browser/issues/31946)

https://github.com/brave/brave-browser/assets/17010094/c4a2f6e0-975a-4875-bcd5-27f5d8c2bb56
