### ISSUE TITLE
Add "Enable NFT auto-discovery" popup

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#29648]

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.52.102 Chromium: 113.0.5672.126 (Official Build) beta (64-bit) 
-- | --
Revision | `c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}`
OS | Linux

- Verified steps from [brave/brave-core#18010](https://github.com/brave/brave-core/pull/18010)
- Verified when switching to NFT tab for the first time shows a popup to enable NFTs automatically
- Verified selecting `Yes proceed` enables the auto-discovery settings in `brave://settings/web3` and auto-adds any NFTs owned by the wallet address

https://github.com/brave/brave-browser/assets/17010094/a055c2fb-f18c-4431-bb4f-92c79df76119

---------------------

**Verification passed on**

Brave | 1.52.102 Chromium: 113.0.5672.126 (Official Build) beta (64-bit)
-- | --
Revision | `c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}`
OS | Windows 11 Version 22H2 (Build 22621.1702)

- Verified steps from [brave/brave-core#18010](https://github.com/brave/brave-core/pull/18010)
- Verified when switching to NFT tab for the first time shows a popup to enable NFTs automatically
- Verified selecting `Yes proceed` enables the auto-discovery settings in `brave://settings/web3` and auto-adds any NFTs owned by the wallet address

https://github.com/brave/brave-browser/assets/17010094/5f39b034-2455-4a4d-8641-8a616470b239


---------------------

**Verification passed on**

Brave | 1.52.102 Chromium: 113.0.5672.126 (Official Build) beta (arm64)
-- | --
Revision | `c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#18010](https://github.com/brave/brave-core/pull/18010)
- Verified when switching to NFT tab for the first time shows a popup to enable NFTs automatically
- Verified selecting `Yes proceed` enables the auto-discovery settings in `brave://settings/web3` and auto-adds any NFTs owned by the wallet address

https://github.com/brave/brave-browser/assets/17010094/53fba4eb-11fd-4729-8b89-1b440cfc55ca
