### ISSUE TITLE
Problem to run google keep app

### ISSUE THREAD

**Issue by dfmabbas** [brave/brave-browser#2964]
OS : `macOS Mojave`
Brave : `0.58.21`
Google Keep - notes and lists : `https://chrome.google.com/webstore/detail/google-keep-notes-and-lis/hmjkmjkepdijhoojdojkdfohbdgmmhki/related?hl=en`

Hi, the `google keep` app is not running, please check and **fix** the problem.

**Comment by srirambv** [comment]
Please use the template to provide info and steps. One line message to fix it wont help. Please update the issue with the template and reopen it
