### ISSUE TITLE
IPFS settings doens't match feature state

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#29647]
IPFS setting switches off after re-enter settings page.

## Steps to reproduce 

   1. Open settings
   2. Turn on using IPFS setting
   3. Re-enter settings(relaunch app)

## Actual result 
The setting is off

## Expected result
The setting is on

- Can you reproduce this issue with the current Play Store version? +
- Can you reproduce this issue with the current Play Store Beta version? + 
- Can you reproduce this issue with the current Play Store Nightly version? +

## Device details
   - Install type (ARM, x86): Arm
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 11
   
## Brave version
1.50

**Comment by vlad-hoff** [comment]
Verified on `Google Pixel 7` and `Galaxy Tab S8` using version(s):
```
Device/OS: 
- Google Pixel 7 [panther_beta-user 14 UPB1.230309.017 release-keys]
- SM-X700 Galaxy Tab S8 [gts8wifixx-user 13 TP1A.220624.014 release-keys]
Brave build: 1.52.92 Chromium: 113.0.5672.92 (Official Build) beta (64-bit)
```
---------------------------

**STEPS:**
1. Launch Brave > Hamburger Menu > Settings
2. Brave Shields & privacy
3. Find IPFS Gateway and enable it
4. Go back to a previous screen or close and reopen the settings

**ACTUAL RESULTS:**
- Verified that the IPFS toggle switch is set to ON by default
- Verified that going back and forth, closing and reopening Brave doesn't affect the current state of the IPFS toggle switch

https://github.com/brave/brave-browser/assets/128532965/e065f2b3-d229-4c84-9e37-f3d415072c02

**Comment by kjozwiak** [comment]
Used https://github.com/brave/brave-browser/issues/29647#issuecomment-1542758098 as the verification for the uplift into `1.51.x`. Removing the `QA Pass` labels as this will need to be re-checked using `1.51.x` once we get the RC builds.

**Comment by kjozwiak** [comment]
The above requires `1.51.117` or higher for `1.51.x` verification 👍

**Comment by vlad-hoff** [comment]
Verified on `Google Pixel 7`using version(s):
```
Device/OS: Google Pixel 7 [panther_beta-user 13 UPB2.230407.014 release-keys]
Brave build: 1.51.117 
Chromium: 113.0.5672.92 (Official Build) (64-bit)
```
---------------------------

**STEPS:**
1. Launch Brave > Hamburger Menu > Settings
2. Brave Shields & privacy
3. Find IPFS Gateway and enable it
4. Go back to a previous screen or close and reopen the settings

**ACTUAL RESULTS:**
- Verified that the IPFS toggle switch is set to ON by default
- Verified that going back and forth, closing and reopening Brave doesn't affect the current state of the IPFS toggle switch

https://github.com/brave/brave-browser/assets/128532965/2137bb88-d11c-4628-873c-b842c44cd727
