### ISSUE TITLE
Enable `brave://flags/#brave-vertical-tabs` in `Release` channel

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#29659]
## Description 

Placeholder for when we're ready to ship, and can enable `brave://flags/#brave-vertical-tabs` in `Release` channel

## Steps to Reproduce

   1. install latest release-candidate build of `1.51.x`
   2. launch Brave
   3. load `brave://flags`
   4. confirm that `brave://flags/#brave-vertical-tabs` is set to `Default`
   5. load a few tabs
   6. context-click a tab
   7. look for the option to `Use Vertical Tabs`

Cross-reference:
* `beta`: https://github.com/brave/brave-browser/issues/29658
* `nightly`: https://github.com/brave/brave-browser/issues/28872

## Actual result:

It's absent.

## Expected result:

<img width="598" alt="Screen Shot 2023-04-12 at 10 13 28 AM" src="https://user-images.githubusercontent.com/387249/231532971-5a666bd4-2319-4cd0-af7e-2e508be531a7.png">

## Reproduces how often: 

100%

## Brave version (brave://version info)

`1.51.x` (`release candidate`/`release` build)

## Miscellaneous Information:

/cc @rebron @sangwoo108 @brave/qa-team

**Comment by sangwoo108** [comment]
@rebron Please let me know if this needs uplifting

**Comment by kjozwiak** [comment]
The above requires `1.52.102` or higher for `1.52.x` verification 👍 @brave/qa-team note that we'll need to verify that `vertical tabs` are enabled by default via `beta` and then `release` once we do channel migrations and `1.52.x` gets moved into `release`.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.52.108 Chromium: 114.0.5735.26 (Official Build) beta (64-bit)
-- | --
Revision | 7075cbb66f0542ac3e01ddfde6b813e7d61118a5-refs/branch-heads/5735@{#454}
OS | Windows 11 Version 22H2 (Build 22621.1702)
```

1. installed 1.52.85
2. launched Brave
3. open few tabs and right click on a tab to open context menu
4. confirmed `Use vertical tabs` option is available
5. clicked on `Use vertical tabs` 
6. vertical tabs panel is shown with all the tabs
7. opened brave://flags
8. confirmed `brave://flags/#brave-vertical-tabs` is set to Default


step 4 | step 8
---- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/8495b3f6-716d-44cd-a8af-060df6911f35)|![image](https://github.com/brave/brave-browser/assets/98358127/100609fb-c22e-49f1-9d94-7065890b352c)

**Comment by stephendonner** [comment]
## Verified `PASSED`

Brave | 1.52.108 Chromium: 114.0.5735.26 (Official Build) beta (x86_64)
-- | --
Revision | 7075cbb66f0542ac3e01ddfde6b813e7d61118a5-refs/branch-heads/5735@{#454}
OS | macOS Version 13.5 (Build 22G5027e)

1. installed `1.52.108`
2. launched Brave
3. opened a few tabs and context-clicked on a tab
4. confirmed `Use vertical tabs` option is available
5. clicked on `Use vertical tabs`
6. vertical tabs panel is shown with all the tabs
7. opened `brave://flags`
8. confirmed `brave://flags/#brave-vertical-tabs` is set to Default

example | example
---------|---------
<img width="1202" alt="Screenshot 2023-05-22 at 7 54 09 PM" src="https://github.com/brave/brave-browser/assets/387249/3bd27a9b-a562-4273-b10b-8ff64f21cc52"> | <img width="1204" alt="Screenshot 2023-05-22 at 7 54 39 PM" src="https://github.com/brave/brave-browser/assets/387249/2d41473a-2dc9-4176-8239-9c31aa6daf05">

**Comment by LaurenWags** [comment]
Removing `QA/Blocked` as the first 1.52.x RC is available via  https://github.com/brave/brave-browser/releases/tag/v1.52.110

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.52.110 Chromium: 114.0.5735.35 (Official Build) (64-bit)
-- | --
Revision | 2295354895fa3652ae47b651481831484f16d1ff-refs/branch-heads/5735@{#713}
OS | Windows 11 Version 22H2 (Build 22621.1702)
```


1. Installed 1.52.110  
2. launch Brave
3. load brave://flags
4. confirm that brave://flags/#brave-vertical-tabs is set to Default
5. load a few tabs
6. context-click a tab
7. verified the option to Use Vertical Tabs is available 
8. selected `Used Vertical Tabs` 

- Confirmed vertical-tabs is enabled as default inbrave://flags
- Confirmed vertical tab panel is shown with opened tabs 
- Confirmed vertical tab functionality worked as expected

 
example | example | example 
------ | ----- | -----
![image](https://github.com/brave/brave-browser/assets/98358127/9368c632-03e4-45e3-9351-e805043960d8)|![image](https://github.com/brave/brave-browser/assets/98358127/bf4c6a0f-df18-4a5c-9266-7e5014fa4566)|![image](https://github.com/brave/brave-browser/assets/98358127/d45de7ea-852f-403e-af9a-70e262485839)

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave	1.52.112 Chromium: 114.0.5735.35 (Official Build) (64-bit) 
Revision	2295354895fa3652ae47b651481831484f16d1ff-refs/branch-heads/5735@{#713}
OS	Linux
```

### Steps:

1. installed 1.52.112
2. launched Brave
3. loaded `brave://flags`
4. confirmed that `brave://flags/#brave-vertical-tabs` is set to `Default`
5. loaded a few tabs
6. context-clicked a tab
7. verified the option to Use Vertical Tabs is available
8. selected `Used Vertical Tabs`
9. confirmed vertical-tabs is enabled as default in `brave://flags`

example | example | example
---------|----------|--------
<img width="1783" alt="Screen Shot 2023-05-25 at 10 00 02 PM" src="https://github.com/brave/brave-browser/assets/387249/27c43476-7212-4028-ac62-03c9ea0312bf"> | <img width="1783" alt="Screen Shot 2023-05-25 at 10 00 56 PM" src="https://github.com/brave/brave-browser/assets/387249/9df40ab1-199e-46dd-ac9c-bb8982a32398"> | <img width="1783" alt="Screen Shot 2023-05-25 at 10 04 42 PM" src="https://github.com/brave/brave-browser/assets/387249/03efdd31-6a24-4bed-8b08-ff290c48e790">
