### ISSUE TITLE
Incorrect response value when ads is enabled after 48 hours but before 72 hours 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#29653]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/28109
Incorrect response value when ads is enabled after 48 hours and before 72 hours 

## Steps to Reproduce

1. Clean profile 1.51.x
2. Open brave://local-state file
3. Confirm that the metrics `Brave.Rewards.EnabledInstallationTime` is not shown in the local state file
4. Close the browser, set the sys clock ahead by 48+ hours but before 72 hours
5. Relaunch browser and enable rewards/Ads 
6. Reload brave://local-state file and ensure that the metrics `Brave.Rewards.EnabledInstallationTime` response value is `4` instead of `3`
7. Open charles and wait until the metrics is sent over the network via Charles
8. Confirmed that the metrics is listed under the host `p3a-json.brave.com` over the network and the `metrics_value` is `4` instead of `3`

   

## Actual result:

Incorrect response value when ads is enabled after 48 hours and before 72 hours 

`p3a-json.brave.com` | `brave://local-state`
------------------------|---------------------
![image](https://user-images.githubusercontent.com/38657976/231442153-476beaf1-2976-42fa-8e29-d2da44e123c4.png) | ![image](https://user-images.githubusercontent.com/38657976/231442177-6740c3f8-1f02-4b08-a567-e1b08955d952.png)
   
## Expected result:

Value should be `3`

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.51.79 Chromium: 112.0.5615.49 (Official Build) beta (64-bit)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Windows 10 Version 21H2 (Build 19044.2728)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @DJAndries @mattmcalister

**Comment by GeetaSarvadnya** [comment]
The issue is reproducible on `Samsung Galaxy version 12` running `Bravemonoarm64.apk_1.51.79`

**Comment by DJAndries** [comment]
Tested with 50 hours and 71 hours, could not reproduce

**Comment by GeetaSarvadnya** [comment]
@DJAndries: Thanks for checking from your end. Let me retest the issue and post my observations.

**Comment by GeetaSarvadnya** [comment]
Works as expected hence closing the issue.
