### ISSUE TITLE
`Failed to switch network` while using `app.uniswap.org`

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#29655]
## Description 

Running into `Failed to switch network - To use Uniswap on [networ name], switch the network in your wallet settings` error when attempting to switch networks via `app.uniswap.org`. Other DApps could also be affected. Ran into this issue when attempting to verify https://github.com/brave/brave-core/pull/17950 as per https://github.com/brave/brave-core/pull/17950#issuecomment-1504534245. @srirambv also reproduced the issue on his device re: not being able to switch networks without running into the error.

## Steps to reproduce 

   1. launch `1.52.36 Chromium: 112.0.5615.49` and create a `Brave Wallet`
   2. once created, visit `app.uniswap.org` and connect to `Brave Wallet` via the `Connect` button
   3. once connected, attempt to switch the network and you'll reproduce the error

## Actual result 

https://user-images.githubusercontent.com/2602313/231507328-f9b42db9-1d53-489c-9dab-758c13c9abcb.mp4

## Expected result

Users should be able to switch networks without any issues.

## Issue reproduces how often 

100% reproducible using the STR/Cases outlined above.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `No`
- Can you reproduce this issue with the current Play Store Beta version? `No` 
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM` & `x86`
   - Device type (Phone, Tablet, Phablet): `Pixel 6` & `Pixel 6 Pro (Emulator)`
   - Android version: `Android 13` & `Android 8 (Emulator)`
   
## Brave version

```
Brave | 1.52.36 Chromium: 112.0.5615.49 (Official Build) canary (32-bit)
--- | ---
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Android 13; Build/TQ2A.230305.008.E1
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

### Additional information

CCing @SergeyZhukovsky

**Comment by kjozwiak** [comment]
The above requires `1.50.118` or higher for `1.50.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.50.120 x64 build
- Verified steps from issue description and [brave/brave-core#18029](https://github.com/brave/brave-core/pull/18029)
- Verified no error when switching networks on `https://app.uniswap.org`
- Verified no crash when switching networks on Android 8.1.0 device
- Verified no error or crash when switching to preloaded networks
- Verified no error or crash when switching to a network that is not added and prompts to add the network before switching

Huawei P20 (Android 8.1.0) | Lenovo (Android 12) | Oppo Reno 5 (Android 13)
-- | -- | --
<video src=https://user-images.githubusercontent.com/17010094/232781905-0b6ea2e7-10cf-4b45-b243-e8f8c5aa7e38.mp4> | <video src=https://user-images.githubusercontent.com/17010094/232781964-d35e25ae-86d1-4cee-96ef-e3960a803dab.mp4> | <video src=https://user-images.githubusercontent.com/17010094/232781930-9ec4ee80-c02a-4ac2-884b-3b36266d2a3b.mp4>
