### ISSUE TITLE
Downloads bubble doesn't popup when the download is blocked/dangerous (safe browsing disabled)

### ISSUE THREAD

**Issue by Emi-TheDhamphirInLoveUnderTheFrozenStar** [brave/brave-browser#29651]
## Description 

@simonhong there is an tiny little bug with the Downloads bubble, where if you disable Safe browsing and a 'dangerous' downloaded is blocked, the bubble doesn't popup, and the only way to download the file is by going to downloads page (ctrl+j) and click keep and then keep it anyway.

The easiest way to reproduce this is by creating a **new profile**, but I noticed it is also affecting my normal profile where I have never had Safe Browsing enabled.

The bug seems to get resolved in normal windows if you click `keep` and then `keep anyway`, in my test, new downloads are working as expected after doing that, even on restart.
Also, it worked fine when I had Safe Browsing on and downloaded a file, and then disabled it.

I guess the problem seems to be bigger for InPrivate windows though, because I noticed that if you download a file and 'fix' the issue by keeping the file, once you close the window and open a new InPrivate window and try to download a 'dangerous' file again, the bubble will not popup until you keep it and keep it anyway again.

## Steps to Reproduce

   1. Create new profile/User Data.
   2. go to brave://settings/security and disable Safe Browsing.
   3. Go to `https://www.majorgeeks.com/mg/get/fort_firewall,2.html`
   4. Nothing seems to happen
   5. Go to downloads page, and the download should only appear there to _discard_ it or _keep_ it
   6. (optional) Discard it and go back to the page and try to download the file again to confirm it still doesn't work.
   7. Click keep and then keep anyway
   8. Future downloads should show the bubble as expected (until it doesn't)

## Actual result:

![brave_2023-04-12_04-19-29](https://user-images.githubusercontent.com/122518587/231433638-41cbddf4-3550-44b3-8564-dc244eb43a82.gif)

## Brave version (brave://version info)

1.52.36 Chromium: 112.0.5615.49 (Official Build) nightly (64-bit)  - Windows 11 Pro 21H2 22000.1696

**Comment by simonhong** [comment]
@Emi-TheDhamphirInLoveUnderTheFrozenStar Thanks for reporting. I'll take a look.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.53.74 Chromium: 114.0.5735.53 (Official Build) beta (x86_64)
-- | --
Revision | c499d7ea22c8b2dba278465a5df7b86a8efa4e64-refs/branch-heads/5735@{#970}
OS | macOS Version 11.7.7 (Build 20G1345)

### `Safe Browsing` **_disabled_**

example | example | example | example | example | example
---------|---------|----------|----------|---------|---------
<img width="1775" alt="Screen Shot 2023-05-30 at 10 45 42 PM" src="https://github.com/brave/brave-browser/assets/387249/0d586879-6885-4c04-a7ca-3b9aae9c7a5f"> | <img width="1775" alt="Screen Shot 2023-05-30 at 10 45 49 PM" src="https://github.com/brave/brave-browser/assets/387249/aaa55510-22d4-43a5-b23e-4b03e1e6c98c"> | <img width="1775" alt="Screen Shot 2023-05-30 at 10 46 23 PM" src="https://github.com/brave/brave-browser/assets/387249/2df21c3d-7e81-421f-96c6-c3d5285e89f8"> | <img width="1775" alt="Screen Shot 2023-05-30 at 10 47 01 PM" src="https://github.com/brave/brave-browser/assets/387249/4a5c098e-33c6-4420-964c-4eafa95697bb"> | <img width="1775" alt="Screen Shot 2023-05-30 at 10 47 53 PM" src="https://github.com/brave/brave-browser/assets/387249/21ef119c-4168-45ed-b5b7-15a0a34d60cf"> | <img width="1775" alt="Screen Shot 2023-05-30 at 10 47 58 PM" src="https://github.com/brave/brave-browser/assets/387249/d2a1cfcc-acde-4dd9-8cb9-78a21969853e">

### `Safe Browsing` **__enabled (default)__**

example | example | example | example | example | example
---------|---------|----------|----------|---------|---------

**Comment by stephendonner** [comment]
@simonhong mind reviewing my steps and results, from above, before I mark it as `QA Pass-macOS`?  Maybe `macOS` and `Windows` have different ideas of what "dangerous files" are?  I checked with `1.52.116` on `macOS`, and it behaves the same as above, in both cases, also  🤷

**Comment by simonhong** [comment]
> @simonhong mind reviewing my steps and results, from above, before I mark it as `QA Pass-macOS`? Maybe `macOS` and `Windows` have different ideas of what "dangerous files" are? I checked with `1.52.116` on `macOS`, and it behaves the same as above, in both cases, also 🤷

Hmm, I also can't repro anymore. it's always treated as normal download file..
Not sure but could it be possible that this file link was danger but changed to safe now? :)
don't know much about how safe browsing works.

**Comment by stephendonner** [comment]
> > @simonhong mind reviewing my steps and results, from above, before I mark it as `QA Pass-macOS`? Maybe `macOS` and `Windows` have different ideas of what "dangerous files" are? I checked with `1.52.116` on `macOS`, and it behaves the same as above, in both cases, also 🤷
> 
> Hmm, I also can't repro anymore. it's always treated as normal download file.. Not sure but could it be possible that this file link was danger but changed to safe now? :) don't know much about how safe browsing works.

OK, I'll redo the `Safe Browsing` `Enabled` case using `https://www.leaseweb.com/platform/network`, then, as that triggers the dialog, I now recall:

![Uploading Screen Shot 2023-05-30 at 11.56.22 PM.png…]()

**Comment by stephendonner** [comment]
@simonhong @rebron can you/the team take a look at https://github.com/brave/brave-browser/issues/30626 when you get a chance?  I keep running into it on both `nightly` and `beta`, when trying to test this issue and around the area, too.  Thanks!

**Comment by simonhong** [comment]
> @simonhong @rebron can you/the team take a look at #30626 when you get a chance? I keep running into it on both `nightly` and `beta`, when trying to test this issue and around the area, too. Thanks!

I'll take a look

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.53.81 Chromium: 114.0.5735.90 (Official Build) beta (64-bit)
-- | --
Revision | 386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}
OS | Windows 11 Version 22H2 (Build 22621.1702)
```
Safe Browsing disabled
<details>


1. installed 1.53.74
2. launched Brave
3. selected `No Protection` radio button for  `Safe Browsing` in `brave://settings/security`
4. confirmed warning about `Turn off Safe Browsing?`
5. loaded https://www.majorgeeks.com/mg/get/fort_firewall,2.html
6. confirmed auto-download save-as-file location-picker dialog (!) came up
7. clicked Save
8. clicked on download button
9. clicked Keep
10. removed file


step 4|step 4a|step 6|step 8|step 9|ex|ex|step 10
----- | ---- | ----- | ----- | ---- | ---- | ---- |-----
![image](https://github.com/brave/brave-browser/assets/98358127/e06072a9-ab32-4a40-aef6-c5739f2f2dd8)|![image](https://github.com/brave/brave-browser/assets/98358127/6db95e6a-dcf8-4d3b-bbbd-5c97484a7c69)|![image](https://github.com/brave/brave-browser/assets/98358127/cfa6f4a9-ebce-4859-9dbe-adc7a538dee4)|![image](https://github.com/brave/brave-browser/assets/98358127/2900410c-1f6e-4e06-a162-a01869c45179)|![image](https://github.com/brave/brave-browser/assets/98358127/30a4335d-e22a-4e9d-acae-28e9271ab8ea)|![image](https://github.com/brave/brave-browser/assets/98358127/6a7dba6f-723d-4675-83f6-952c0930329f)|![image](https://github.com/brave/brave-browser/assets/98358127/0f319f9b-d8a1-4e4c-90e8-4ebb068bb7ca)|![image](https://github.com/brave/brave-browser/assets/98358127/ba49dc3e-3287-4fba-8ec0-ac8adf682247)|![image](https://github.com/brave/brave-browser/assets/98358127/b752a296-e4de-432f-8856-b87475c26408)

**Comment by stephendonner** [comment]
> > @simonhong mind reviewing my steps and results, from above, before I mark it as `QA Pass-macOS`? Maybe `macOS` and `Windows` have different ideas of what "dangerous files" are? I checked with `1.52.116` on `macOS`, and it behaves the same as above, in both cases, also 🤷
> 
> Hmm, I also can't repro anymore. it's always treated as normal download file.. Not sure but could it be possible that this file link was danger but changed to safe now? :) don't know much about how safe browsing works.

Ditto; I did find `https://testsafebrowsing.appspot.com/` which I can and will use to help test this on `macOS` 👍

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave	1.53.87 Chromium: 114.0.5735.110 (Official Build) beta (64-bit) 
Revision	1c828682b85bbc70230a48f5e345489ec447373e-refs/branch-heads/5735_90@{#13}
OS	Linux
```

**Comment by kjozwiak** [comment]
The above requires `1.52.130` or higher for `1.52.x` verification 👍 Removing the `QA Pass` labels as the above will need to be rechecked with `1.52.x`.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.52.130 Chromium: 114.0.5735.198 (Official Build) (x86_64)
-- | --
Revision | c3029382d11c5f499e4fc317353a43d411a5ce1c-refs/branch-heads/5735@{#1394}
OS | macOS Version 13.4.1 (Build 22F82)
```

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.52.130 Chromium: 114.0.5735.198 (Official Build) (64-bit)
-- | --
Revision | c3029382d11c5f499e4fc317353a43d411a5ce1c-refs/branch-heads/5735@{#1394}
OS | Linux
```

### `Safe Browsing` **_disabled_** - `PASSED`

<details>

### Steps:
1. installed `1.52.130`
2. launched Brave
3. toggled `Safe Browsing` to `No Protection` in `brave://settings/security`
4. confirmed warning about disabling `Safe Browsing`
5. loaded `https://www.majorgeeks.com/mg/get/fort_firewall,2.html`
6. confirmed auto-download save-as-file location-picker dialog (!) came up
7. clicked `Save`
8. confirmed file downloaded without additional warnings
9. cleared file
10. repeated steps 5-8

example | example | example | example | example | example 
---------|---------|----------|----------|----------|-----------
![Screenshot from 2023-07-06 09-41-06](https://github.com/brave/brave-browser/assets/98358127/f3a6a60d-72ec-439c-a8f8-0d4684a9912d)|![Screenshot from 2023-07-06 09-41-24](https://github.com/brave/brave-browser/assets/98358127/04ea96e0-5361-4c33-914a-05c52f6982d0)|![Screenshot from 2023-07-06 09-42-42](https://github.com/brave/brave-browser/assets/98358127/3c6aeaf8-dbcc-49cf-bb39-2830f9e8021f)|![Screenshot from 2023-07-06 09-42-57](https://github.com/brave/brave-browser/assets/98358127/a60234f3-275d-424a-bd0b-b36d7d68de31)|![Screenshot from 2023-07-06 09-43-16](https://github.com/brave/brave-browser/assets/98358127/b9e10307-0904-4144-9dc3-8c4cc613161c)|![Screenshot from 2023-07-06 09-44-49](https://github.com/brave/brave-browser/assets/98358127/3a13b818-2cd7-4e54-a918-bd7e2f235259)

</details>

### `Safe Browsing` **__enabled__** (`Standard protection`; default) - `PASSED`
<details>

### Steps:
1. installed `1.52.130`
2. launched Brave, waited ~8 minutes and confirmed Safe Browsing was downloaded before proceeding with the rest of the steps
3. confirmed `Safe Browsing` was set to `Standard Protection` in `brave://settings/security`
4. loaded `https://www.majorgeeks.com/mg/get/fort_firewall,2.html`
5. confirmed auto-download save-as-file location-picker dialog (!) came up
6. clicked `Save`
7. confirmed file downloaded without additional warnings
8. cleared file
9. repeated steps 4-7

example | example | example | example | example
---------|---------|----------|----------|---------
![Screenshot from 2023-07-06 10-42-01](https://github.com/brave/brave-browser/assets/98358127/7dbce3a2-8c3a-421d-8b81-dbd02bc0e898)|![Screenshot from 2023-07-06 10-43-09](https://github.com/brave/brave-browser/assets/98358127/7050da19-c7f3-4132-9fa0-3c34bdc83d3f)|![Screenshot from 2023-07-06 10-43-36](https://github.com/brave/brave-browser/assets/98358127/c32a1bf3-179e-426c-98a3-475aa8190d60)|![Screenshot from 2023-07-06 10-43-45](https://github.com/brave/brave-browser/assets/98358127/3753db8f-4400-450d-a312-c92b6b9309e4)|![image](https://github.com/brave/brave-browser/assets/98358127/dd4e8250-c70e-46d2-afd1-bf3987b85f8c)

</details>

## Blocked downloads

### Blocked, `Dangerous` - `PASSED`

<details>

### Steps:
1. installed `1.52.130`
2. launched Brave, waited ~8 min and confirmed Safe Browsing was downloaded before proceeding
3. loaded `https://testsafebrowsing.appspot.com/`
4. clicked on and saved `https://testsafebrowsing.appspot.com/s/content.exe`

Example | Example
--- | ---
![Screenshot from 2023-07-06 10-55-46](https://github.com/brave/brave-browser/assets/98358127/185ff60d-7547-4492-adc3-6b0d2e791dc1)|![Screenshot from 2023-07-06 10-56-07](https://github.com/brave/brave-browser/assets/98358127/bcf9f4c5-f8b6-42ca-9fcb-2e50288048f4)

</details>

### Blocked, `Uncommon file` - `PASSED`

<details>

### Steps:
1. installed `1.52.130`
2. launched Brave, waited ~8 min and confirmed Safe Browsing was downloaded before proceeding
3. opened `https://testsafebrowsing.appspot.com`
4. clicked on and saved `https://testsafebrowsing.appspot.com/s/unknown.exe`

Example | Example
--- | ---
![image](https://github.com/brave/brave-browser/assets/98358127/a7eee193-b397-4273-9736-c41e9b3da650)|![image](https://github.com/brave/brave-browser/assets/98358127/3ec73c45-8b42-4603-b998-6cdf43da7d0d)


</details>

### `Keep` flow - `PASSED`

<details>

`Keep dangerous file` | `Keep anyway` | `Downloaded file`
---------|----------|---------
![image](https://github.com/brave/brave-browser/assets/98358127/a76dfb14-da6e-4d76-bd3f-373df2e17f5e)|![image](https://github.com/brave/brave-browser/assets/98358127/325bcd66-8d6d-4810-9eb9-3e8a3a9fac42)|![image](https://github.com/brave/brave-browser/assets/98358127/c33bb3f6-6c74-4c2f-8115-442e967731a6)

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave	1.52.130 Chromium: 114.0.5735.198 (Official Build) (64-bit) 
Revision	c3029382d11c5f499e4fc317353a43d411a5ce1c-refs/branch-heads/5735@{#1394}
OS	Windows 10 Version 22H2 (Build 19045.3155)
```
