### ISSUE TITLE
Update playlist icon in settings menu

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#29656]
## Description 
Update Playlist icon in settings menu to match other

3 Dot Menu | Settings Menu
-|-
![Screenshot 2023-04-12 at 12 00 29 PM](https://user-images.githubusercontent.com/17885425/231516106-7a8f19f3-e9a4-422f-b4d8-f7c2925980bd.png) | ![Screenshot 2023-04-12 at 12 00 18 PM](https://user-images.githubusercontent.com/17885425/231516128-eb2951ed-e424-4d2d-9783-2f650bcaac4d.png)
![Screenshot 2023-04-12 at 2 27 51 PM](https://user-images.githubusercontent.com/17885425/231551238-4d748011-729b-4878-aca6-5c252d6aad73.png) | ![Screenshot 2023-04-12 at 2 27 51 PM](https://user-images.githubusercontent.com/17885425/231551289-8936d3ca-fff8-4578-81f4-606e96f55ae1.png)

## Steps to reproduce 

   1. Install 1.52.x 
   2. Enabled brave://flags#playlist
   3. Open hamburger menu

## Actual result 
Does not match 

## Expected result
Should match the one in the main menu

## Issue reproduces how often 
Always

## Version/Channel Information:
 

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? No
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung GS, Samsung G Tab S7
   - Android version: 13
   
## Brave version
`1.52.26, Chromium 112.0.5615.49`

**Comment by kjozwiak** [comment]
As discussed with @deeppandya via https://bravesoftware.slack.com/archives/C03MMJ4CHEZ/p1686260940735599, this issue will be added into the `master` playlist PR. This way the above won't be missed and will be verified. Reasoning is that the above code landed in `1.53.x` so the issue should stay in `1.53.x` and shouldn't be moved into other milestones.
