### ISSUE TITLE
Enable `brave://flags/#brave-vertical-tabs` in `Beta` channel

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#29658]
## Description 

Enable `brave://flags/#brave-vertical-tabs` in `Beta` channel

(We set it for `Nightly` over in https://github.com/brave/brave-browser/issues/28872.)

## Steps to Reproduce

   1. install latest `beta` build
   2. launch Brave
   3. load `brave://flags`
   4. confirm that `brave://flags/#brave-vertical-tabs` is set to `Default`
   5. load a few tabs
   6. context-click a tab
   7. look for the option to `Use Vertical Tabs`

## Actual result:

Not present

## Expected result:

`brave://flags/#brave-vertical-tabs` should be set internally to `Enabled`, making `Use Vertical Tabs` available as a toggle on tabs

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.51.86 Chromium: 112.0.5615.49 (Official Build) beta (x86_64)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | macOS Version 11.7.6 (Build 20G1231)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `No`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

/cc @rebron @sangwoo108 @brave/qa-team

**Comment by kjozwiak** [comment]
The above requires `1.51.96` or higher for `1.51.x` verification 👍
