### ISSUE TITLE
Allow checking hardware wallet balance across all networks during import

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#29662]
## Description 

When importing a hardware wallet account, provide a network selector in the UI so that the account balance can be checked for networks other than the "default" for the account coin-type. (We already do this for Filecoin, EVM and SOL chain selectors missing)

## Steps to Reproduce

   1. Select an EVM network such as BNB-Chain
   2. Navigate to the accounts page and click "import from hardware wallet"
   3. select Ethereum/EVM option
   4. connect the hardware device and view the list of accounts

## Actual result:

Native asset ticket is not shown next to the balance
No UI is provided to select a different chain

## Expected result:
UI is provided to select a different EVM chain
Native asset balance and ticker are updated when chain selection changes

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

After this change is made, the concept of a "default network" can be deprecated from desktop UI logic

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.52.102 Chromium: 113.0.5672.126 (Official Build) beta (64-bit)
-- | --
Revision | `c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}`
OS | Windows 11 Version 22H2 (Build 22621.1702)

- Verified steps from [brave/brave-core#18152](https://github.com/brave/brave-core/pull/18152)
- Verified network filter is shown on import hardware wallet  screen
- Verified able to view balance based on network and derivation path
- Verified for EVM/Solana/Filecoin
- Encountered [#30484](https://github.com/brave/brave-browser/issues/30484)


Solana | EVM | Filecoin
-- | -- | --
![brave_bNOtRFHajH](https://github.com/brave/brave-browser/assets/17010094/cca9eaf7-59ed-415c-8d60-1d66b5b11489) | ![brave_uFiytubOgz](https://github.com/brave/brave-browser/assets/17010094/a3636352-c78d-4536-ba36-70e0e73dd34a) | ![brave_9ofnSMPjnf](https://github.com/brave/brave-browser/assets/17010094/d88164e9-770e-4191-bd76-70556d191a2a)
