### ISSUE TITLE
Brave can't update subscription filters 

### ISSUE THREAD

**Issue by ChowMein47** [brave/brave-browser#29661]
Hi @antonok-edm It looks like brave adblock has a problem updating subscription filters. Brave version: 1.50.114 Android 13
![Screenshot_2023-04-12-08-01-17-00_e4424258c8b8649f6e67d283a50a2cbc](https://user-images.githubusercontent.com/98148960/231320815-b6062b34-eb79-4c87-b4ad-e1777c8620fa.jpg)

**Comment by antonok-edm** [comment]
@YellowStar11 if you tap on the triple-dot icon and select "Update now", does that make any difference?

**Comment by YellowStar11** [comment]
> @YellowStar11 if you tap on the triple-dot icon and select "Update now", does that make any difference?

No difference, still failure with manual update

**Comment by ryanbr** [comment]
Fixed @ChowMein47  ?
