### ISSUE TITLE
Perf: Add UserTokens Registry to base query cache

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#29665]
## Description 

Race conditions can occur when attempting to fetch a query result from within another query. Move requests for user `BlockchainTokens` into the base query cache, so that queries with query dependencies will forcefully resolve

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.52.102 Chromium: 113.0.5672.126 (Official Build) beta (64-bit)
-- | --
Revision | `c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}`
OS | Windows 11 Version 22H2 (Build 22621.1702)

- Verified steps from [brave/brave-core#18031](https://github.com/brave/brave-core/pull/18031)
- Verified token symbol is shown properly
- Encountered [#30447](https://github.com/brave/brave-browser/issues/30447)
