### ISSUE TITLE
Asset detail screen displays selected network info from `Market` tab

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-browser#29663]
## Steps to Reproduce

   1. Open wallet on nightly 
   2. select solana mainnet from `Swap`
   3. navigate the `Market` tab and open Btc

## Actual result:

Asset detail screen displays `BTC on Solana Mainnet Beta`

## Expected result:
There should be no network info in Asset detail screen if user comes from `Market` tab

## Brave version (brave://version info)

Version 1.52.37 Chromium: 112.0.5615.49 (Official Build) nightly (arm64)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.52.102 Chromium: 113.0.5672.126 (Official Build) beta (64-bit)
-- | --
Revision | `c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}`
OS | Windows 11 Version 22H2 (Build 22621.1702)

- Verified steps from [brave/brave-core#18048](https://github.com/brave/brave-core/pull/18048)
- Verified selecting a token from Market tab doesn't show any info about `Network`, `Accounts` or `Transactions`

https://github.com/brave/brave-browser/assets/17010094/7032adf2-51b6-4ea4-bf1d-336de71d6c00
