### ISSUE TITLE
Vertical tabs' titles glyphs show after being drag and dropped in floating mode

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#29668]
## Description 

Vertical tabs' titles glyphs show after being drag and dropped in floating mode

## Steps to Reproduce

   1. install `1.52.37`
   2. launch Brave
   3. set `Use vertical tabs` to `Enabled` via `brave://flags`
   4. load a few sites
   5. context-click any tab
   6. choose `Use Vertical Tabs`
   7. with `Float on mouseover` checked, ensure the tab strip is collapsed
   8. drag any site (via its favicon) out into its own window
   9. drag and drop it back into the tab strip
   10. notice the tab strip

## Actual result:

Tab strip now has textual artifacts/glyphs from the tab's title

`example, in context` | `extra text showing`
-----------------------|----------------------
![image (2)](https://user-images.githubusercontent.com/387249/231617337-8cf330f3-ffac-404f-b9a3-5d052d54f7a6.png) | ![image (3)](https://user-images.githubusercontent.com/387249/231617351-bdb55768-fffb-4f0f-b554-656ea6c4b20f.png)

## Expected result:

No such artifacts

![image](https://user-images.githubusercontent.com/387249/231617562-84ea2847-a923-4e52-9e5a-547eab54c718.png)

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.52.37 Chromium: 112.0.5615.49 (Official Build) nightly (64-bit)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Windows 10 Version 22H2 (Build 19045.2846)

## Miscellaneous Information:

/cc @sangwoo108 @rebron @brave/qa-team

**Comment by srirambv** [comment]
This happens on collapsed view as well and on the teared out window as well. Reported a duplicate issue [here](https://github.com/brave/brave-browser/issues/29725)

**Comment by kjozwiak** [comment]
The above requires `1.51.97` or higher for `1.51.x` verification 👍

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.51.97 Chromium: 112.0.5615.138 (Official Build) beta (64-bit)
-- | --
Revision | 2258f2fcaeb07bc95c992b7ca47f0b43ead9865c-refs/branch-heads/5615@{#1282}
OS | Windows 10 Version 22H2 (Build 19045.2846)

### Steps:
Followed my original steps to reproduce; note that I did have issues re-attaching a window back to the tab strip; I'll investigate, but it's separate from this issue and verification

#### Confirmed dragging out and dropping back in correctly placed the tab in its drop-target position, without leaving glyphs of the tab titles from the various float/expanded/minimized modes

![issue29668](https://user-images.githubusercontent.com/387249/233382757-36e524f9-bb42-49ad-861e-1fedc1b1c051.gif)
