### ISSUE TITLE
Swap option on Buy/Send/Swap button only shows up when you select a token on Swap screen

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#29682]
## Description 
Swap option on Buy/Send/Swap button only shows up when you select a token on Swap screen

## Steps to reproduce 

   1. Install 1.52.40 clean install and create wallet
   2. Click on Buy/Send/Swap button
   3. Only Buy and Send options are shown
   4. Open a new tab and load `brave://wallet/swap`
   5. Select a Swap from and Swap to token
   6. Go back to wallet and select Buy/Send/Swap token, now Swap is shown

## Actual result 

https://user-images.githubusercontent.com/17010094/231758033-84d5d7d7-8707-4311-b486-927080758fda.mp4

## Expected result
Should always show the Swap button

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA 
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 13
   
## Brave version
1.52.40

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc; @vadimstruts @SergeyZhukovsky @jamesmudgett

**Comment by kjozwiak** [comment]
The above requires `1.52.95` or higher for `1.52.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.52.113 x64 build
- Verified steps from issue description
- Verified Swap option is shown on the Buy/Send/Swap button on a clean install 
- Verified selecting Swap from wallet screen sets Ethereum as the default network irrespective of which network is set as default in wallet panel screen.


https://github.com/brave/brave-browser/assets/17010094/31fdc047-92cd-4c7b-bef9-eb27387b8765
