### ISSUE TITLE
[Android] Improve UI for private tabs reauth feature

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#29688]
## Description 
We want to replace this icon https://source.chromium.org/chromium/chromium/src/+/main:chrome/android/java/res/drawable/ic_incognito_reauth_promo_icon.xml
![Screenshot_20230412-144943](https://user-images.githubusercontent.com/30602739/231790208-aa6fda7f-7a2b-43fb-88cf-8d139d992513.png)

We want to revisit these UI's
![Screenshot_20230413-101136](https://user-images.githubusercontent.com/30602739/231790231-693e8e5f-9810-43e1-8752-d9b73978ceec.png)

![Screenshot_20230413-101153](https://user-images.githubusercontent.com/30602739/231790246-e8d07f64-13b4-48e0-826c-522bf9c1620d.png)

## Steps to reproduce 

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by aguscruiz** [comment]
Design is ready here:
https://www.figma.com/file/6KPhbe8yqCPOLgFT2AYlju/Private-nav---Application-lock?node-id=1%3A5720&t=akjs30qOI2MTM5UX-1

![image](https://user-images.githubusercontent.com/15734630/233992360-7d089af2-549c-42ef-863a-567733733c2d.png)

**Comment by CodeCubeNeo** [comment]
Any updates on this?

**Comment by anthonypkeane** [comment]
Pls use the UI from https://github.com/brave/brave-ios/issues/7810

**Comment by samartnik** [comment]
So here we just updated icons and buttons to match Figma to unlock the feature itself. Private tab UI overhaul will be done as a separate task https://github.com/brave/brave-browser/issues/33949
![Screenshot_20231026_143531](https://github.com/brave/brave-browser/assets/30602739/5798751d-2579-481e-9f59-fa893cb1b3a1)
![Screenshot_20231026_115757](https://github.com/brave/brave-browser/assets/30602739/d32f9595-c2cd-40cb-8b51-14a277004428)

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.62.121`
