### ISSUE TITLE
Crash when loading SOL account page with null tx decodedData

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#29698]
## Description 

Solana account page crashes if the account has transactions with `null` `decodedData`

## Steps to Reproduce

1. Create & fund a Solana account
1. initiate a transaction that cant be decoded
This should contain instructions other than
- SolanaSystemInstruction
    - CreateAccount
    - Assign
    - Transfer
    - CreateAccountWithSeed
    - AdvanceNonceAccount
    - WithdrawNonceAccount
    - InitializeNonceAccount
    - AuthorizeNonceAccount
    - Allocate
    - AllocateWithSeed
    - AssignWithSeed
    - TransferWithSeed
    - UpgradeNonceAccount
- SolanaTokenInstruction
    - InitializeMint
    - InitializeAccount
    - InitializeMultisig
    - Transfer
    - Approve
    - Revoke
    - SetAuthority
    - MintTo
    - Burn
    - CloseAccount
    - FreezeAccount
    - ThawAccount
    - TransferChecked
    - ApproveChecked
    - MintToChecked
    - BurnChecked
    - InitializeAccount2
    - SyncNative
    - InitializeAccount3
    - InitializeMultisig2
    - InitializeMint2
 
(A swap from Brave Wallet should be sufficient) 

1. open wallet page
1. go to accounts
1. click on the SOL account that initiated the transactions

## Actual result:

the page crashes, logs an error

## Expected result:
the page should load and the transaction should be displayed

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.52.102 Chromium: 113.0.5672.126 (Official Build) beta (64-bit)
-- | --
Revision | c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}
OS | Windows 11 Version 22H2 (Build 22621.1702)

- Verified steps from [brave/brave-core#18044](https://github.com/brave/brave-core/pull/18044)
- Verified no crash when loading Solana account that initiated swap
