### ISSUE TITLE
picture display issue

### ISSUE THREAD

**Issue by MynameisAlexB** [brave/brave-browser#2969]
I only use Brave for a few days. I have a problem with displaying images. In very dark tones, the images often have green artifacts. 

Brave version 0.58.18 Chromium: 71.0.3578.98 (Build officiel) (64 bits)
No issue with Chrome
Problem still visible when disabling Brave Shields

Thanks a lot

two examples :

![issue1](https://user-images.githubusercontent.com/46720266/51195087-acaedc00-18ec-11e9-9ad9-06e030c6708c.jpg)

![issue2](https://user-images.githubusercontent.com/46720266/51195089-acaedc00-18ec-11e9-983a-3939c56b4ded.jpg)

**Comment by MynameisAlexB** [comment]
I only use Brave for a few days. I have a problem with displaying images. In very dark tones, the images often have green artifacts. 

Brave version 0.58.18 Chromium: 71.0.3578.98 (Build officiel) (64 bits)
No issue with Chrome
Problem still visible when disabling Brave Shields

Thanks a lot

two examples :

![issue1](https://user-images.githubusercontent.com/46720266/51195087-acaedc00-18ec-11e9-9ad9-06e030c6708c.jpg)

![issue2](https://user-images.githubusercontent.com/46720266/51195089-acaedc00-18ec-11e9-983a-3939c56b4ded.jpg)

**Comment by bsclifton** [comment]
@MynameisAlexB can you please try the following?
1. Visit chrome://flags/#force-color-profile
2. In the drop-down, pick `sRGB`

You may need to restart the browser? But I believe this may resolve the issue. Please let us know 😄

**Comment by MynameisAlexB** [comment]
Thank you very much @bsclifton, it works perfectly now ! 😄

**Comment by bsclifton** [comment]
@MynameisAlexB awesome! I'll go ahead and close this issue and share the fix with our support team. Thanks for confirming 😄

**Comment by kneekoo** [comment]
What happened to sRGB in the latest Brave? The colors are wrong, but this flag is no longer present to fix the issue.

**Comment by bsclifton** [comment]
@kneekoo great question - you might try enabling / disabling brave://flags/#forced-colors and let us know if this has any effect

**Comment by kneekoo** [comment]
Yeah, I tried that when I noticed #force-color-profile was no longer there, but toggling that setting (default/enabled/disabled) didn't fix the colors. Why was the #force-color-profile flag removed? Chromium 83 still has it.
