### ISSUE TITLE
Show Buy-Send-Swap actions on Portfolio, NFT, Account tab and use default network for BSS

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#29695]
## Description 
Bind Buy Send Swap actions to 

```[tasklist]
### Tasks
- [x] Show Buy-Send-Swap actions always on Portfolio, NFT, and Account tab (iOS reference issue https://github.com/brave/brave-ios/issues/6811)
- [x] Always use default network (ETH) for BSS
```
[More info link](https://bravesoftware.slack.com/archives/C04RSGAAF0X/p1681452087723369)

Related:
- https://github.com/brave/brave-browser/issues/29682
- https://bravesoftware.slack.com/archives/C04DTJT4MDG/p1682611903977659

**Comment by kjozwiak** [comment]
The above requires `1.52.95` or higher for `1.52.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.52.113 x64 build
- Verified steps from [brave/brave-core#18343](https://github.com/brave/brave-core/pull/18343)
- Verified Buys/Send/Swap button is shown on Portfolio/NFT/Accounts tab and defaults to Ethereum when selected

https://github.com/brave/brave-browser/assets/17010094/8aeabd73-2e01-4a53-b360-48cfb3bf0b13
