### ISSUE TITLE
Add Vertical Tabs feature

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#29692]
## Description 

Allow users the ability to view their tabs in a vertical format on the left side of the browser window.

## Brave version (brave://version info)

Target release 1.51.x/1.52.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.51.86 Chromium: 112.0.5615.49 (Official Build) beta (64-bit)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Windows 11 Version 22H2 (Build 22621.1555)
```
Case 1:  Vertical tabs enabled via brave://flags
<details>

1. Install 1.51.86
2. launch Brave
3. click `Set Brave as default Browser` 
4. click `Import` to import `Microsoft Edge`
5. Select `Profile 1` >>`Import profiles`
6. click `Finish`
7. open brave://flags
8. select `Enabled` for `#brave-vertical-tabs`
9. click Relaunch
10. click to open `BBC` bookmark
11. right click on the tab to open context menu

- Confirmed `Use vertical tabs` entry is shown in the context menu
- Confirmed Vertical tab strip positioned on the left
- Confirmed Sidebar moved to right as expected

step 4|step 5|step 8|step 12
-----|-----|-----|------
<img width="476" alt="image" src="https://user-images.githubusercontent.com/98358127/231604482-9b267ce1-695c-4d76-a65c-104f6229c664.png">|<img width="476" alt="image" src="https://user-images.githubusercontent.com/98358127/231607290-e10a04e5-aa23-4cbd-bd9e-f3147f915249.png">|<img width="464" alt="image" src="https://user-images.githubusercontent.com/98358127/231607449-72668750-a840-49af-9722-ac2ee81798a2.png">|<img width="478" alt="image" src="https://user-images.githubusercontent.com/98358127/231607580-197370cc-13e9-4ea7-b986-f2143c58a4d0.png">
</details>

Case 2: Vertical tabs:  Appearance/UI
<details>

Light mode | Dark mode
-----|------
<img width="959" alt="image" src="https://user-images.githubusercontent.com/98358127/231610114-65bd7c87-bb25-4f0e-ac70-44e7585127eb.png">|<img width="958" alt="image" src="https://user-images.githubusercontent.com/98358127/231610068-543636c7-0389-409b-a989-56580a3e3d0e.png">

</details>

Case 3:  Tab strip orientation change - horizontal tabs to vertical tabs and vice versa
<details>

1. Continue from Case 1
    - `Use vertical tabs` entry is shown in the context menu
2. clicked `Use vertical tabs` entry in the context menu
3. Uncheck `Use vertical tabs` entry 
4. recheck `Use vertical tabs` entry 

- Confirmed orientation of the tab strip has changed and is shown on vertical tab strip on the left side of the screen
- Confirmed orientation switched back to horizontal tab strip 
- Confirmed Vertical strip show again 
- 
step 2|step 3|step 4
----|------|---
<img width="952" alt="image" src="https://user-images.githubusercontent.com/98358127/231613757-01b6b54c-e2cc-43f7-a874-e86486e9882a.png">|<img width="950" alt="image" src="https://user-images.githubusercontent.com/98358127/231614194-f4f142ac-b88c-4923-8490-f1529aa90fc5.png">|<img width="952" alt="image" src="https://user-images.githubusercontent.com/98358127/231850334-ef9c7830-a7ca-422a-8d99-2a2ec4165484.png">

</details>

Case 4: Vertical tab strip's visual modes - Floating mode, Expanded & Minimized modes
<details>

*_Floating on mouseover_* - Default mode

1. Continue from Case 3
    - Vertical tab strip is shown on the left of the screen
2. right click on a vertical tab (BBC - Homepage)
3. confirmed context menu shows `Float on mouseover` checked
4. confirmed Vertical tab strip is in expanded mode
5. clicked minimized button 

#### Confirmed vertical tab strip is on float when hovered over 
#### Confirmed when clicked minimized button again to discontinue Float 

https://user-images.githubusercontent.com/98358127/231858017-11f9c41a-cedd-4bca-9ca0-dda7b3abc253.mp4

*_Expanded mode_*

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.51.93 Chromium: 112.0.5615.121 (Official Build) beta (x86_64)
-- | --
Revision | 39cc4e45904ae9f1741c4fbaa866e629c96f2268-refs/branch-heads/5615_51@{#8}
OS | macOS Version 13.4 (Build 22F5037d)

**Comment by rebron** [comment]
Closing per verifications. Still need https://github.com/brave/brave-browser/issues/29659.

**Comment by LaurenWags** [comment]
Per discussion in today's desktop call, marking this as `QA Pass-Linux` as the Linux vertical tab testing was crowdsourced from internal folks via https://bravesoftware.slack.com/archives/C042KL922P3/p1684265068786289. Special thanks to @srirambv @rillian for helping out and reporting issues. 

Some open issues include:
- https://github.com/brave/brave-browser/issues/30389
- https://github.com/brave/brave-browser/issues/30392
- https://github.com/brave/brave-browser/issues/30398
