### ISSUE TITLE
Disable ipfs-internals page on Android

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#29697]
Since brave://ipfs-internals page is about working with local node,  which is not supported on Android - it should be disabled from build to save some space in apk/aab.

Related issues:
https://github.com/brave/brave-browser/issues/25103
https://github.com/brave/brave-browser/issues/28060

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.52.92 x64 beta build
- Verified steps from [brave/brave-core#17999](https://github.com/brave/brave-core/pull/17999)
- Verified able to load IPFS URI using public gateway settings
- Verified navigating to `brave://ipfs-internals` and/or `chrome://ipfs-internals` doesn't load
- Verified there is no entry for ipfs-internals page in `brave://chrome-pages`

Oppo Reno 5 (Android 13) | Lenovo Tab (Android 12)
-- | --
<video src=https://github.com/brave/brave-browser/assets/17010094/a1f6b443-679a-42f2-863a-79a2fb8f28a6> | <video src=https://github.com/brave/brave-browser/assets/17010094/98719552-3c5f-417f-b195-d237a85c7ee0>
<img width=300 src=https://github.com/brave/brave-browser/assets/17010094/0a94f2ed-70eb-4983-831c-7482564f12c8> | <img width=400 src=https://github.com/brave/brave-browser/assets/17010094/ab6706c2-c42a-4ac9-8f27-eba07c416276>
