### ISSUE TITLE
`What's new` page appears as defaulted tab, before even `brave://welcome`, upon Griffin-seed restart

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#29709]
## Description 

`What's new` page appears as defaulted tab, before even `brave://welcome`, upon Griffin-seed restart

## Steps to Reproduce

   1. install `1.52.42`
   2. launch Brave using `--variations-server-url=https://variations.bravesoftware.com/seed`
   3. shut down
   4. relaunch using `--variations-server-url=https://variations.bravesoftware.com/seed`
   

## Actual result:

example | example | example
---------|----------|--------
<img width="1312" alt="Screen Shot 2023-04-13 at 12 25 46 PM" src="https://user-images.githubusercontent.com/387249/231871853-237846ab-f1d2-4cc0-a7d8-df9d2f7cdff1.png"> | <img width="1312" alt="Screen Shot 2023-04-13 at 1 14 34 PM" src="https://user-images.githubusercontent.com/387249/231873122-32828b1f-719f-4533-b6cb-314c2d50f779.png"> | <img width="1379" alt="Screen Shot 2023-04-13 at 11 58 51 AM" src="https://user-images.githubusercontent.com/387249/231873126-f2c33fc6-048e-4e30-ba1a-df01827ac445.png">

## Expected result:

Not sure, but as the user hasn't even gone through the onboarding/`brave://welcome` experience yet, we shouldn't show this (yet/here)

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.52.42 Chromium: 112.0.5615.87 (Official Build) nightly (x86_64)
-- | --
Revision | 12315abe04d2dc2cac3055bd52ce662b2e742fbe-refs/branch-heads/5615_49@{#4}
OS | macOS Version 11.7.6 (Build 20G1231)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

/cc @rebron @simonhong @bsclifton @kjozwiak @LaurenWags @aguscruiz

**Comment by stephendonner** [comment]
Also, the timing of that cookie-consent dialog and this == too much.

**Comment by stephendonner** [comment]
Also reproduced in 

Brave | 1.52.43 Chromium: 112.0.5615.87 (Official Build) nightly (64-bit)
-- | --
Revision | 12315abe04d2dc2cac3055bd52ce662b2e742fbe-refs/branch-heads/5615_49@{#4}
OS | Windows 10 Version 22H2 (Build 19045.2846)

![image](https://user-images.githubusercontent.com/387249/231876984-a25a506a-51d7-4c79-83f5-cb984e2c6c92.png)

**Comment by LaurenWags** [comment]
it seems weird to me that a user is getting it at all in this scenario. they didn't update, just relaunched the same version. shouldn't even be seeing it in that case IMO.

**Comment by simonhong** [comment]
For existing users(not the first run user), `What's-new` page could be launched even welcome page tab is activated tab.
Should we block `What's-new` always if welcome page is activated one?

and I realized that new user could see `What's new` page in the second launch because we can't get griffin data at first run. In the second launch, browser becomes existing user. so what's new is launched. This should be addressed.

**Comment by stephendonner** [comment]
> For existing users(not the first run user), `What's-new` page could be launched even welcome page tab is activated tab. Should we block `What's-new` always if welcome page is activated one? cc @rebron
<snip>

Can we tell if users have "completed" the `brave://welcome` experience, or not?  That page can be visited any time, so its presence might not mean 100% new user.

**Comment by simonhong** [comment]
> > For existing users(not the first run user), `What's-new` page could be launched even welcome page tab is activated tab. Should we block `What's-new` always if welcome page is activated one? cc @rebron
> 
> Can we tell if users have "completed" the `brave://welcome` experience, or not? That page can be visited any time, so its presence might not mean 100% new user.

Good question. @spylogsster can we know user completed or not?

**Comment by simonhong** [comment]
@rebron @stephendonner  BTW, how about showing `What's new` page at second launch for new user in that version?
I think introducing new features for that version not in the first run would be fine?

**Comment by stephendonner** [comment]
> @rebron @stephendonner BTW, how about showing `What's new` page at second launch for new user in that version? I think introducing new features for that version not in the first run would be fine?

I'm fine with this, and think it makes good sense 👍

**Comment by stephendonner** [comment]
> > @rebron @stephendonner BTW, how about showing `What's new` page at second launch for new user in that version? I think introducing new features for that version not in the first run would be fine?
> 
> I'm fine with this, and think it makes good sense 👍

Although, let's not forget that the cookie-content blocking dialog is also on 2nd run, too - so in terms of "too much all at once" for new-ish users, we should be careful

**Comment by simonhong** [comment]
I found an useful api that gives the version of Brave which created current profile.
With this api, we can show whats-new tab only for updated user.
With that, whats-new tab would not be overlapped with welcome pages or cookie-content blocking dialog

**Comment by spylogsster** [comment]
> 

we can add a pref or handler for this

**Comment by spylogsster** [comment]
> > > For existing users(not the first run user), `What's-new` page could be launched even welcome page tab is activated tab. Should we block `What's-new` always if welcome page is activated one? cc @rebron
> > 
> > 
> > Can we tell if users have "completed" the `brave://welcome` experience, or not? That page can be visited any time, so its presence might not mean 100% new user.
> 
> Good question. @spylogsster can we know user completed or not?

we can add a pref or handler for this

**Comment by kjozwiak** [comment]
The above requires `1.51.99` or higher for `1.51.x` verification 👍

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.51.99 Chromium: 112.0.5615.165 (Official Build) beta (x86_64)
-- | --
Revision | c262f36e6b1d711ee42d4fbe1343b49960593f18-refs/branch-heads/5615@{#1297}
OS | macOS Version 11.7.6 (Build 20G1231)

### Steps:
1. installed `1.51.99`
2. launched Brave using `--variations-server-url=https://variations.bravesoftware.com/seed`
3. noted experience
4. shut down
5. relaunched Brave using `--variations-server-url=https://variations.bravesoftware.com/seed`
6. noted experience

### Confirmed no `What's New` page launched

1st run | 2nd run | `brave://version` | `brave://local-state`
-------|----------|-----------------|---------------------
