### ISSUE TITLE
Network Icons Not Working on NFTs tab

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#29701]
## Description 

Network Icons are not displaying on NFTs tab.

## Steps to Reproduce

   1. Go to the NFTs tab
   2. The icons do not show up at the bottom right of the pictures

## Actual result:

![Screenshot 69](https://user-images.githubusercontent.com/40611140/231842053-8fd55fd5-381b-4353-ab0c-3cfc3f7edf62.png)

![Screenshot 70](https://user-images.githubusercontent.com/40611140/231842057-a9659616-2e11-4281-9503-a35ea3150f9c.png)

## Expected result:
Network Icons should show up

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.52.94 Chromium: 113.0.5672.92 (Official Build) beta (64-bit) 
-- | --
Revision | `0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}`
OS | Linux

- Verified steps from [brave/brave-core#18056](https://github.com/brave/brave-core/pull/18056)
- Verified network icons are shown on each NFT in the NFT tab
![image](https://github.com/brave/brave-browser/assets/17010094/3dec30a1-d43c-4fdb-aded-acb8959d0697)


---------------------

**Verification passed on**

Brave | 1.52.94 Chromium: 113.0.5672.92 (Official Build) beta (64-bit)
-- | --
Revision | `0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from [brave/brave-core#18056](https://github.com/brave/brave-core/pull/18056)
- Verified network icons are shown on each NFT in the NFT tab
![9Y33Im31Ok](https://github.com/brave/brave-browser/assets/17010094/4698cec2-d9e6-49e5-a5fa-afb57253bf45)

---------------------

**Verification passed on**

Brave | 1.52.94 Chromium: 113.0.5672.92 (Official Build) beta (arm64)
-- | --
Revision | `0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#18056](https://github.com/brave/brave-core/pull/18056)
- Verified network icons are shown on each NFT in the NFT tab
![image](https://github.com/brave/brave-browser/assets/17010094/c293fdf9-db11-433f-a21a-638c305d74e8)
