### ISSUE TITLE
(Wallet) Improve network selector behavior in NFT section

### ISSUE THREAD

**Issue by simoarpe** [brave/brave-browser#29706]
## Description 

Network selector may end up in an inconsistent state if the network changes quickly many times in a row (see demo below).
Explanation of the issue: under the hood, the live data does not emit the selected network quickly enough and the UI reflects an old selected network.

[231820893-835bd243-b7cf-4639-a15c-da98c939358d.webm](https://user-images.githubusercontent.com/3308503/231852473-064a0bff-25a1-4713-9645-1747ee176823.webm)

**Comment by HEagle18** [comment]
could help with nft load time as well.

**Comment by josheleonard** [comment]
@simoarpe , is this still a valid issue now that android is using webUI?

**Comment by simoarpe** [comment]
This issue is not relevant anymore. I'm closing it.
