### ISSUE TITLE
Market tab doesn't allow for horizontal scrolling

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#29716]
## Description 

Market tab doesn't allow for horizontal scrolling 

## Steps to Reproduce

   1. Create wallet on nightly
   2. Enable Vertical tabs flag
   3. Switch to vertical tabs
   4. Go to wallet and select Market tab
   5. Can't scroll horizontally 

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/231942717-97ecafc4-58e9-4979-8c9f-933dc390ff16.png)

## Expected result:
Should be able to scroll horizontally if the view port is small

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.52.42 Chromium: 112.0.5615.87 (Official Build) nightly (64-bit)
-- | --
Revision | `12315abe04d2dc2cac3055bd52ce662b2e742fbe-refs/branch-heads/5615_49@{#4}`
OS | Windows 11 Version 22H2 (Build 22621.1555)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

Note: This is happening on my daily driver profile but with the same screen resolution and browser zoom levels set in a VM its working fine. 
cc: @Douglashdaniel @josheleonard

**Comment by Douglashdaniel** [comment]
Is no longer an issue after `Wallet V2` updates, closing as `Invalid`

![Screenshot 73](https://github.com/brave/brave-browser/assets/40611140/a67f40bb-7d6b-410f-bb86-b5f739f545a0)
