### ISSUE TITLE
Can't toggle "block cross site cookies"

### ISSUE THREAD

**Issue by SylwesterDu** [brave/brave-browser#29718]
## Description 
Automatically changes to "allow all cookies"

## Steps to reproduce 

   1. Go to settings -> brave shields and privacy 
   2. Tap block cookies
   3. Try to select second option

## Actual result 
https://user-images.githubusercontent.com/61783625/231967676-f7df8737-9d1f-4d81-880d-24ed7d80954b.mp4

- Can you reproduce this issue with the current Play Store version?
Yes
- Can you reproduce this issue with the current Play Store Nightly version?
Yes

## Device details
   - Install type (ARM, x86): arm64
   - Device type (Phone, Tablet, Phablet): phone
   - Android version: 13

**Comment by unknown4849** [comment]
almost made dup issues, 

anyway this effect to global rules, but idk this effect to the cookie or not .
https://streamable.com/cq1gps

https://streamable.com/yhxohd ( another proff who to got this problem from my end)

**Comment by Wallymick** [comment]
Any news when this bug will be resolved?

Still present on Android Brave Beta v1.52.84.

**Comment by kjozwiak** [comment]
We'll use https://github.com/brave/brave-browser/issues/33473 as the main issue re: QA verification 👍
