### ISSUE TITLE
Color of the progress bar in brave://downloads doesn't match the download button progress

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#29714]
See https://bravesoftware.slack.com/archives/CKNHM4RTK/p1681339023053969 for more details

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.52.84 Chromium: 113.0.5672.63 (Official Build) beta (x86_64)
-- | --
Revision | 0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}
OS | macOS Version 11.7.6 (Build 20G1231)

### Steps:
1. installed `1.52.84`
2. launched Brave
3. switched to `Dark` mode in `brave://settings/appearance`
4. loaded `https://www.leaseweb.com/platform/network`
5. downloaded a large test file
6. opened `brave://downloads/`
7. checked the color
8. compared to `1.51.110`

### Confirmed the progress-meter color is now "blurple", and matches the download button's.

NOTE: the middle progress meter will be taken care of in https://github.com/brave/brave-browser/issues/29919

`1.52.84` | `1.51.110`
----------|---------
<img width="1008" alt="Screen Shot 2023-05-03 at 3 14 47 PM" src="https://user-images.githubusercontent.com/387249/236062517-209fc5b4-8626-414f-b4a4-2d4edb5f9f52.png"> | <img width="874" alt="Screen Shot 2023-05-03 at 3 21 22 PM" src="https://user-images.githubusercontent.com/387249/236062781-afecebe3-e8d4-4361-84e6-85ecae52141a.png">
