### ISSUE TITLE
Rework "Forget by default" to be per-domain.

### ISSUE THREAD

**Issue by goodov** [brave/brave-browser#29723]
Follow up for https://github.com/brave/brave-browser/issues/26465

After some testing we saw that the usual Shields approach (per host cleanup) doesn't work quite well for bounce-like auth scenarios (docs.google.com->accounts.google.com).

If we "remember" the website, we should do it for eTLD+1 (cover all subdomains), otherwise the cookie cleanup step is impossible to align correctly.

The updated approach should move the setting into a separate toggle:
![image](https://user-images.githubusercontent.com/5928869/231480497-ed531c57-9efa-4b3f-8edc-536fe9cde455.png)

![image](https://user-images.githubusercontent.com/5928869/231480315-e93c1c78-bf1d-4047-9ad6-20e529529322.png)

**Comment by kjozwiak** [comment]
Changing the above to `QA/Yes` and `QA/Test-All-Platforms` as the above is planned to go out via `1.53.x` as per the discussion with @pes10k. Labelling as `QA/Blocked` for now until we get https://github.com/brave/brave-variations/pull/571 into Nightly today and into `BETA` sometime this week if things are looking stable on Nightly once `BraveForgetFirstPartyStorage` has been enabled via Griffin.

**Comment by kjozwiak** [comment]
Removed `QA/Blocked` as https://github.com/brave/brave-variations/pull/649 has been merged into `beta`.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.53.93 Chromium: 114.0.5735.110 (Official Build) beta (64-bit)
-- | --
Revision | 1c828682b85bbc70230a48f5e345489ec447373e-refs/branch-heads/5735_90@{#13}
OS | Windows 11 Version 22H2 (Build 22621.1702)
```


Case 1 - Before feature being enabled via Griffin

1. Installed 1.53.93
2. launched Brave using brave.exe --enable-logging=stderr 
3. confirmed `BraveForgetFirstPartyStorage`  isn't visible under `brave://version`
4. visited nytimes.com in a new tab
5. clicked Shields icon to open the Shields panel
6. opened brave://settings/shields

- Confirmed `Forget me when I close this site` toggle doesn't appear via the Shields panel
- Confirmed `Forget me when I close this site` toggle doesn't appear via `brave://settings/shields`

step 3 | step 5 | step 6
---- | ---- | ----
<image width="700" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/2548f505-799c-4fcf-8ca5-954ba5e066a9">|<image width="700" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/bb6f53d5-2927-424c-b61b-fd344294c14a">|<image width="700" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/9b1e5b44-f8ea-4abf-abae-0c34c8d80242">

Case 2: Ensure feature being enabled via Griffin

1. continue from Case 1: 
- `BraveForgetFirstPartyStorage`  isn't visible under `brave://version`
-  `Forget me when I close this site` toggle doesn't appear via the Shields panel for nytimes.com
2. closed and restarted Brave using brave.exe --enable-logging=stderr
3. confirmed `BraveForgetFirstPartyStorage:Enabled` is shown in `brave://version`
4. opened Shields panel in the nytimes.com tab
5. opened brave://settings/shields

- Confirmed `Forget me when I close this site` toggle appears in the Shields panel and is `Off` by default
- Confirmed `Forget me when I close this site` toggle appears in the `brave://settings/shields` and is `Off` by default

step 3 | step 4 | step 5
---- | ---- | ----
<image width="700" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/31d94694-e903-4204-87b4-9d54c5d3d4f6">|<image width="700" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/ea67f63a-8499-4475-86e5-0e847d30b3b6">|<image width="700" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/e75e8d5d-d688-4270-816b-67dfa1cf8b9b">

light theme
shields panel | brave://settings/shields
--- | ---
![image](https://github.com/brave/brave-browser/assets/98358127/40f961ef-979d-4941-813b-466be22d97ef)|![image](https://github.com/brave/brave-browser/assets/98358127/0c4654b4-1bee-464a-a3fa-f5219fc80787)

**Comment by LaurenWags** [comment]
Per discussion via https://bravesoftware.slack.com/archives/CHGKGMHDJ/p1687362687017369?thread_ts=1680615454.570509&cid=CHGKGMHDJ, changing this to `QA/No` and `release-notes/exclude` and removing `QA/Test-All-Platforms` as this is not going to be enabled on release channel with 1.53.x.
