### ISSUE TITLE
Ad notifications sometimes presented to user when Ads toggle is off

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#2972]
## Description 
Sometimes when Ads is off, users are still being presented with Ads.

## Steps to Reproduce
NOTE: these steps are in progress and not 100% confirmed

   1. Have a Dev profile with Rewards enabled (note, Ads is not enabled) on 0.60.9.
   2. Update to 0.60.13.
   3. Navigate to brave://rewards
   4. Verify Ads are not shown as enabled.
   5. Browse normally.

## Actual result:
You may be presented with an Ad.

## Expected result:
No Ads since you did not manually enable with 0.60.13.

## Reproduces how often: 
unsure

## Brave version (brave://version info)

Brave | 0.60.13 Chromium: 72.0.3626.53 (Official Build) dev(64-bit)
-- | --
Revision | 98434e6cd182d68ce396daa92e9c6310422e6763-refs/branch-heads/3626@{#620}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? saw on Dev

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
cc @mandar-brave @jsecretan @mrose17

**Comment by GeetaSarvadnya** [comment]
1+https://community.brave.com/t/ads-notifications-in-brave-dev/42613

**Comment by kjozwiak** [comment]
@ryanml this has been merged into `0.60.x` via https://github.com/brave/brave-core/pull/1353 correct? Changing the milestone from `1.x Backlog` --> `0.60.x`. Please let me know if that's not the case 👍

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.60.28 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Mac OS X

* Launched Brave with `/Applications/Brave\ Browser\ Beta.app/Contents/MacOS/Brave\ Browser\ Beta --enable-logging=stderr --vmodule=brave_ads=3 --log-level=0`. Verified when Rewards were ON and Ads were ON, there were `AdsService Event Log` messages in terminal. Verified when Rewards (as a whole) were OFF, there were no `AdsService Event Log` messages in terminal. Verified when Rewards were ON and Ads were OFF, there were no `AdsService Event Log` messages in terminal. Verified when Ads were ON, some Ad notifications were displayed to me as expected. I have not experienced Ad notifications when Rewards and/or Ads were toggled OFF.

**Comment by LaurenWags** [comment]
Logged #3408 as follow up issue
