### ISSUE TITLE
Improve vpn region data update

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#29728]
## Description 

When vpn region list is updated, browser should get latest one.
We have background update logic for it but we found that it's triggered 5h later after launching.
That means user should use more than 5h to get update.
We should try to update region data 5h later from the last update check.

It's difficult to have STR because region data is updated from guardian.
https://github.com/brave/brave-browser/issues/29719 is another related issue.

## Steps to Reproduce

   1. Launch brave with existing profile that has already purchased state 
   2. Relaunching again before 5h passed
   3. Use more than 5h from launching

## Actual result:

Region data is not updated - BR region is not visible from vpn panel

## Expected result:
Region data is updated - BR region is visible from vpn panel

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.51.110` or higher for `1.51.x` verification 👍

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.51.110 Chromium: 113.0.5672.77 (Official Build) (x86_64)
-- | --
Revision | c4236862955e005c2187105415ac4a2ecf86dff1-refs/branch-heads/5672_62@{#3}
OS | macOS Version 11.7.6 (Build 20G1231)
