### ISSUE TITLE
Serve vpn region flag from leo instead of using static image

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#29727]
STR:
1. Launch VPN and set purchased state
2. Check main panel show flag images properly

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.53.67 Chromium: 114.0.5735.53 (Official Build) beta (x86_64)
-- | --
Revision | c499d7ea22c8b2dba278465a5df7b86a8efa4e64-refs/branch-heads/5735@{#970}
OS | macOS Version 11.7.7 (Build 20G1345)

example | example | example | example
---------|----------|---------|---------
<img width="1647" alt="Screen Shot 2023-05-26 at 6 43 54 PM" src="https://github.com/brave/brave-browser/assets/387249/86366c2b-e56b-4c3f-9e0a-bd58ed2b4fab"> | <img width="1647" alt="Screen Shot 2023-05-26 at 6 37 11 PM" src="https://github.com/brave/brave-browser/assets/387249/2c5544f7-3beb-4c79-8aa2-a1d18f81295e"> | <img width="1647" alt="Screen Shot 2023-05-26 at 6 37 33 PM" src="https://github.com/brave/brave-browser/assets/387249/1bfc1a69-7524-46f9-9b74-199c284b385c"> | <img width="1647" alt="Screen Shot 2023-05-26 at 6 38 06 PM" src="https://github.com/brave/brave-browser/assets/387249/1f9b465c-eb04-40eb-bc56-34ab043fc42a">

example | example | example | example
---------|----------|---------|---------
<img width="1647" alt="Screen Shot 2023-05-26 at 6 38 13 PM" src="https://github.com/brave/brave-browser/assets/387249/2f54b0ea-191d-4cbc-bbbe-3cf87538d6f3"> | <img width="1647" alt="Screen Shot 2023-05-26 at 6 38 20 PM" src="https://github.com/brave/brave-browser/assets/387249/a9f1c5bd-9409-4410-a14f-3b07f9b9da9e"> | <img width="1647" alt="Screen Shot 2023-05-26 at 6 38 22 PM" src="https://github.com/brave/brave-browser/assets/387249/7fc385e7-3064-4e67-8997-f1b330835f70"> | <img width="1647" alt="Screen Shot 2023-05-26 at 6 38 37 PM" src="https://github.com/brave/brave-browser/assets/387249/80c2c552-bdc0-43a6-bb66-1de2051a3e1d">
