### ISSUE TITLE
Help Centre button to link to Wallet help centre category instead of the Wallet FAQ

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#29729]
## Description 

We now have a Wallet category on the community site. Lets point help centre links to this (https://support.brave.com/hc/en-us/categories/360001059151-Brave-Wallet) instead of wallet FAQ. 

<img width="249" alt="Screenshot 2023-04-14 at 15 57 55" src="https://user-images.githubusercontent.com/12224304/232065375-74cdda4e-b2cd-401f-916e-eeea52fbc9f0.png">
<img width="278" alt="Screenshot 2023-04-14 at 15 58 15" src="https://user-images.githubusercontent.com/12224304/232065381-57065e8f-8f88-4405-9171-3ca28abff848.png">

## Steps to Reproduce

   1. click on help centre link with wallet menu
   2. it brings you to the wallet FAQ
   3. 

## Expected result:
if you click on help centre, it will bring you to the brave wallet help centre https://support.brave.com/hc/en-us/categories/360001059151-Brave-Wallet

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Removing OS/Android label as there is an Android specific issue for this https://github.com/brave/brave-browser/issues/27270

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.52.84 Chromium: 113.0.5672.63 (Official Build) beta (64-bit)
-- | --
Revision | 0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}
OS | Windows 11 Version 22H2 (Build 22621.1635)

- Verified test plan from [brave/brave-core#18075](https://github.com/brave/brave-core/pull/18075)
- Verified `Help centre` now loads `https://support.brave.com/hc/en-us/categories/360001059151-Brave-Wallet`

https://user-images.githubusercontent.com/17010094/237027647-fe532517-1e86-466d-8647-bedcf74062f6.mp4

**Comment by busyjordy** [comment]
Hi, I want to alert you to an issue I have with Google Sign-in service. I can't find another way to contact anyone about this, so excuse me for writing here. I cannot login at all, the page that is supposed to display the login 2FA verification does not load at all for many weeks now, so I am unable to sign in. I use Chrome instead, but I prefer to use Brave, so let me know whom I can contact to resolve this persistent issue please.
