### ISSUE TITLE
[Android] Localhost permission

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#29730]
Android port of https://github.com/brave/brave-browser/issues/27346

When feature is on:
1. Prompt users for localhost permission when visiting websites that make connections to localhost subresources.
2. Have an entry for `Localhost` in `Site Settings` in Settings. Adding/subtracting exceptions should work.

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using the following version(s):

```
Brave	1.52.112 Chromium: 114.0.5735.35 (Official Build) (64-bit) 
Revision	2295354895fa3652ae47b651481831484f16d1ff-refs/branch-heads/5735@{#713}
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
Feature flag: `#brave-localhost-access-permission`
Ad Block Rule: @@||localhost^$domain=shivankaul.com

Using test plan in https://github.com/brave/brave-core/pull/17321#issue-1594465275

- Ensured loading subresource image test page will prompt user with permission dialog,
- Ensured loading server worker test page will prompt user with permission dialog.
- Ensured loading websockets test page will prompt user with permission dialog.
- Ensured loading iframe test page will prompt user with permission dialog.
- Ensured that allowing localhost permission on test pages will load the resource.
- Ensured selecting localhost permission will set the appropriate exception for the domain under `localhost` in `site settings.`
- Ensured changing exception from allow to block or vice versa will be applied on the test page.
- Ensured manually enter exception site under site settings works.

Example | Example | Example | Example | Example | Example
-|-|-|-|-|-
![screenshot-1685033633798](https://github.com/brave/brave-browser/assets/17885425/63031aa3-095f-4d84-8eab-dbd9b8b1f8ce) | ![screenshot-1685045733208](https://github.com/brave/brave-browser/assets/17885425/1f18b14a-84a5-4a7e-b615-cb764fd99842) | ![screenshot-1685045744692](https://github.com/brave/brave-browser/assets/17885425/9dd6f645-2763-48be-a5d2-ff1c9a9d58be) | ![screenshot-1685045754443](https://github.com/brave/brave-browser/assets/17885425/5f28a222-1c0d-43c9-9843-efb6ea06b719) | ![screenshot-1685047308430](https://github.com/brave/brave-browser/assets/17885425/72105147-944d-4261-853c-d9d0fdc83792) | ![screenshot-1685047340297](https://github.com/brave/brave-browser/assets/17885425/be875e8a-d215-4724-9350-b89d024bb822) | ![screenshot-1685050352246](https://github.com/brave/brave-browser/assets/17885425/50518801-6109-4509-9106-1ee031fbc2c5)

**Comment by Uni-verse** [comment]
Verified on Samsung Galaxy Tab S7 using the following version(s):

```
Brave	1.52.112 Chromium: 114.0.5735.35 (Official Build) (64-bit) 
Revision	2295354895fa3652ae47b651481831484f16d1ff-refs/branch-heads/5735@{#713}
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
Using test plan in https://github.com/brave/brave-core/pull/17321#issue-1594465275

- Ensured loading subresource image test page will prompt user with permission dialog,
- Ensured loading server worker test page will prompt user with permission dialog.
- Ensured loading websockets test page will prompt user with permission dialog.
- Ensured loading iframe test page will prompt user with permission dialog.
- Ensured that allowing localhost permission on test pages will load the resource.
- Ensured selecting localhost permission will set the appropriate exception for the domain under localhost in site settings.
- Ensured changing exception from allow to block or vice versa will be applied on the test page.
- Ensured manually enter exception site under site settings works.

Example | Example | Example | Example | Example
-|-|-|-|-
![screenshot-1685118529982](https://github.com/brave/brave-browser/assets/17885425/e3cf30e3-d998-49d4-96da-406b31ed31a6) | ![screenshot-1685118541415](https://github.com/brave/brave-browser/assets/17885425/d49b488d-2a0a-4222-90cb-7db0be0af6d7) | ![screenshot-1685118561549](https://github.com/brave/brave-browser/assets/17885425/817a071f-8cc0-4e31-a8ea-9bc2c3d6d3c4) | ![screenshot-1685118574041](https://github.com/brave/brave-browser/assets/17885425/4f287e19-5d43-4c56-86f8-b5eb3af52bc2) | ![screenshot-1685118593043](https://github.com/brave/brave-browser/assets/17885425/92034675-45d5-47e5-b156-50e2812a9e93)
![screenshot-1685118610866](https://github.com/brave/brave-browser/assets/17885425/32cc386b-f8b9-4900-83ce-7b2cd6e8aa79) | ![screenshot-1685118661683](https://github.com/brave/brave-browser/assets/17885425/1c69f71e-1314-4d4b-9c1a-4249e1ed3e6e) | ![screenshot-1685118684412](https://github.com/brave/brave-browser/assets/17885425/35f6219a-b972-4921-b186-e8c22be70283) | ![screenshot-1685118945514](https://github.com/brave/brave-browser/assets/17885425/a3fd632d-8afa-4917-a202-7e4933b6a481) | ![screenshot-1685119051390](https://github.com/brave/brave-browser/assets/17885425/63a9ad60-1a95-40d9-89ca-0fab46372922)
