### ISSUE TITLE
Solana swap fails if Associated Token Account does not exist yet

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#29733]
Try doing a `SOL-USDC` swap from an account that does not have the USDC ATA account created yet. It fails with the following error:

```
Program logged: "AnchorError caused by account: token_account. Error Code: AccountNotInitialized. Error Number: 3012. Error Message: The program expected this account to be already initialized."
```

Transaction: https://explorer.solana.com/tx/2NMYnGrQ5ExkrxopQvnwhwdhDuFSpS1JiPQBmQFsaH44fwLYMFngL49CLBGrLd6scPZXUURnJYAMUY6QfGy9q545

**Comment by yrliou** [comment]
We add an instruction for creating ATA account when doing SPL token transfer when it's not existed yet, maybe can reference that for this too.

**Comment by kjozwiak** [comment]
The above requires `1.52.101` or higher for `1.52.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.52.102 Chromium: 113.0.5672.126 (Official Build) beta (64-bit)
-- | --
Revision | `c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}`
OS | Windows 11 Version 22H2 (Build 22621.1702)

- Verified as part of [#30297 (comment)](https://github.com/brave/brave-browser/issues/30297#issuecomment-1552762322)

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.52.112 x64 build
- Verified as part of [#30297 (comment)](https://github.com/brave/brave-browser/issues/30297#issuecomment-1562742127)
