### ISSUE TITLE
Optimise publisher update feedback

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#2973]
- onPublisherInfoUpdated calls synopsis
- onSetPublisherInfo calls synopsis

Flow should be more optimised.

**Comment by NejcZdovc** [comment]
There is also a lot of responses send to the panel that are the same and that should be reduced just to ones that are actually different and needed. Most of the code that is responsible for sending this out is inside `bat_get_media`.

**Comment by btlechowski** [comment]
@NejcZdovc Could you provide test plan for this issue or set it to QA/No if testing is not needed?

**Comment by NejcZdovc** [comment]
@btlechowski added QA/No flag
