### ISSUE TITLE
[hackerone] Show a prompt for QR-code scanned URLs

### ISSUE THREAD

**Issue by stoletheminerals** [brave/brave-browser#29743]
We should show a prompt before navigating to a URL that was scanned with the QR-code scanner.

https://hackerone.com/reports/1946534

Edit: per the latest discussions we decided to go without any prompt but we paste the qr url into address bar but don't submit it, you have press 'return/go' manually

**Comment by tapanmodh** [comment]
@stoletheminerals If scanned string is not url than we are searching the scanned text into default search engine. should we change that as well?

**Comment by stephendonner** [comment]
## Verified `PASSED` on a `Google Pixel XL` (`arm64`) running `Android 9`:

```
Brave	1.52.102 Chromium: 113.0.5672.126 (Official Build) beta (32-bit)
Revision	c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}
OS	Android 9; Build/PQ2A.190305.002; 28; REL
```

### Steps:
1. installed `1.52.102`
2. launched Brave
3. loaded `brave.com` on `macOS` (latest `beta`)
4. clicked on its URL bar's `Share this page` icon
5. chose `Create QR Code`
6. on Android, scanned the above desktop-generated QR code
7. tapped to load `brave.com`

### Confirmed `brave.com` URL text was prepopulated in the URL bar, and that I had to tap to load it

example | example | example | example | example | example
---------|----------|---------|----------|---------|---------
![Screenshot 2023-05-18 at 1 38 00 PM](https://github.com/brave/brave-browser/assets/387249/54fc66db-6ee7-4129-a564-219603027489) | ![Screenshot_20230518-133511](https://github.com/brave/brave-browser/assets/387249/ed824016-b163-4406-842d-ba47c09d87cf) | ![Screenshot_20230518-133520](https://github.com/brave/brave-browser/assets/387249/5a300116-eefb-428f-8e34-21f407eb85af) | ![Screenshot_20230518-133533](https://github.com/brave/brave-browser/assets/387249/b6cdf5a1-38d6-45bb-8a3b-ebe79ebeabef) | ![Screenshot_20230518-133540](https://github.com/brave/brave-browser/assets/387249/8d22a10d-7dcb-4ec8-8b93-8e88fca25e09) | ![Screenshot_20230518-133601](https://github.com/brave/brave-browser/assets/387249/fbe628fd-84b7-42b2-b5bc-bcad358f6a90) | ![Screenshot_20230518-133601](https://github.com/brave/brave-browser/assets/387249/cb7d4921-2c52-4645-ba43-0875405a7c23)

**Comment by vlad-hoff** [comment]
Verified on `Galaxy Tab S8` using version(s):
```
Device/OS: SM-X700 Galaxy Tab S8 [gts8wifixx-user 13 TP1A.220624.014 release-keys]
Brave build: 1.52.109
Chromium: 114.0.5735.26 (Official Build) beta (64-bit)
Revision: 7075cbb66f0542ac3e01ddfde6b813e7d61118a5-refs/branch-heads/5735@{#454}
```
---------------------------

**STEPS:**
1. Install build 1.52.x
2. Launch Brave
3. Load `brave.com` on desktop
4. Click on its URL bar's `Share this page` icon
5. Choose `Create QR Code`
6. On Android scan the above desktop-generated QR code
7. Tap to load `brave.com` 

**ACTUAL RESULTS:**
- Verified that the QR code URL was pasted into the address bar automatically, but didn't submit it. User must have to tap 'Enter' manually.

https://github.com/brave/brave-browser/assets/128532965/9be8745b-34da-4628-960e-f047a524c970
