### ISSUE TITLE
Add a new setting that allows Brave Rewards icon to be hidden when inactive

### ISSUE THREAD

**Issue by davidtemkin** [brave/brave-browser#2975]
## Test plan
See https://github.com/brave/brave-core/pull/1552

## Description
Add a new on/off setting in the "Appearance" section, below "Use wide location bar", as follows:

"Hide Brave Rewards icon in location bar when Rewards is not enabled"

This option should default to off -- i.e., the default setting is that Brave Rewards icon is *always* visible, whether or not Rewards is active. 

When the setting is on, the Brave Rewards icon should be hidden *unless Rewards is on*. If Rewards is on, the icon is visible regardless of the setting. 

The setting only controls whether or not the icon is visible when Rewards is off.

**Comment by eljuno** [comment]
Related to #1475?

**Comment by davidtemkin** [comment]
Yes. This is how we are solving that issue.

**Comment by davidtemkin** [comment]
Updated the string in initial comment.

**Comment by rebron** [comment]
We could also do two lines:
"Show Brave Rewards button"
"Hide Brave Rewards button in address bar when Rewards is not enabled"

**Comment by davidtemkin** [comment]
If it were two lines the second line would need to be a more detailed explanation of the first line (in keeping with Chrome style): 

First line: "Always show Brave Rewards icon in location bar"
Second line: "Shows Brave Rewards icon even when Rewards is not enabled"

That could work. Don't know if it's preferable.

**Comment by rebron** [comment]
I think the original language was right with a few updates using "button" and "address bar":

first line: Hide Brave Rewards button
second line: Hides Brave Rewards button in address bar when Rewards is not enabled

We'll change instances of location bar/url bar to address bar to be consistent.

**Comment by mkarolin** [comment]
@rebron How should Guest/Tor windows behave? There is no `Appearance` section in settings for those and, currently, the button is always disabled in them.

**Comment by tomlowenthal** [comment]
The setting's relationship to the icon should function the same way in private windows.

If Brave Rewards _is not_ enabled AND the setting _is_: do not show the icon.
If Brave Rewards is enabled OR the setting is disabled: show the disabled icon.

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.61.37 Chromium: 73.0.3683.39 (Official Build) beta (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

Used test plan from https://github.com/brave/brave-core/pull/1552

![image](https://user-images.githubusercontent.com/34715963/53377016-c23e0980-3960-11e9-8afe-e520665e030c.png)
![image](https://user-images.githubusercontent.com/34715963/53377055-dd107e00-3960-11e9-85a7-4f8ec55827a9.png)
![image](https://user-images.githubusercontent.com/34715963/53377073-eef22100-3960-11e9-9b60-4ca15f07ef80.png)
![image](https://user-images.githubusercontent.com/34715963/53377083-f9acb600-3960-11e9-9e7b-49c03aea0242.png)
