### ISSUE TITLE
Follow up of #27936 - Visited creators counter in Rewards panel does not appear in JP case in Production environmnet

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#29771]
## Description 

Follow up of #27936 - Visited creators counter in Rewards panel does not appear in JP case in Production environmnet

## Steps to reproduce 

   1. Launch the browser in production env, don't use the staging flags to launch the browser
   2. Follow the test plan from https://github.com/brave/brave-core/pull/17735#issue-1637846551
   3. Visited creators counter is NOT shown in the rewards panel
   

## Actual result 

Visited creators counter in Rewards panel does not appear in JP case in Production environmnet
## Expected result

Visited creators counter should be shown in Rewards panel for JP region
## Issue reproduces how often 

Easy
## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86): ARM,
   - Device type (Phone, Tablet, Phablet): Samsung Galaxy version 12
   - Android version: 12
   
## Brave version
1.51.80

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/qa-team @deeppandya @Miyayes

**Comment by GeetaSarvadnya** [comment]
Reproduced the issue on Windows 10 x64 - 1.51.89

![image](https://user-images.githubusercontent.com/38657976/232455083-7efd07a7-d438-4c64-af58-f0a55bef72d9.png)

**Comment by Miyayes** [comment]
@GeetaSarvadnya I think this may be invalid, since the website you're visiting (alexvincentmusic.com) is verified on staging but isn't verified on production?
