### ISSUE TITLE
Add "Enable NFT auto-discovery" popup

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#29778]
## Description 

```[tasklist]
### Tasks
- [x] Add "Enable NFT auto-discovery" popup in NFT tab
- [x] Add Web3 "Enable NFT discovery" option in Settings
```

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.52.94 x64 Beta build
- Verified steps from [brave/brave-core#18185](https://github.com/brave/brave-core/pull/18185)
- Verified `Learn more` on the auto-discovery prompt and settings load `https://github.com/brave/brave-browser/wiki/NFT-Discovery`
- Verified NFT discovery dialog is not shown once Enable/cancel is clicked
- Verified NFTs are auto added to the visible list when NFT auto-discovery is enabled either via settings or via the NFT discovery prompt

https://github.com/brave/brave-browser/assets/17010094/5187dec7-0235-4b44-a3e7-82c002561080
