### ISSUE TITLE
Sort Portfolio and NFTs assets by balance

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#29770]
## Description 
Sort assets list in Portfolio by balance.

Details: https://bravesoftware.slack.com/archives/C02S9LFEXU4/p1681538988908419

**Comment by josheleonard** [comment]
@simoarpe, can this be closed?

**Comment by simoarpe** [comment]
Yes, this issue can be closed as it's not relevant anymore.
