### ISSUE TITLE
Add NFT works without entering Token ID for Ethereum NFTs

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#29779]
## Description 
Add NFT works without entering Token ID for Ethereum NFTs

## Steps to reproduce 

   1. Go to visible asset list and add a custom token
   2. Enter a token address for an NFT
   3. Wait for fields to auto-populate
   4. Add button gets enabled without entering token id
   5. Able to submit the form but no token is added 

## Actual result 

https://user-images.githubusercontent.com/17010094/232492262-163e9933-15d4-41f8-9d44-e81b76867ae3.mp4

## Expected result
Add button should only be enabled when token id is entered

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: 13
   
## Brave version
1.51.89

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @simoarpe

**Comment by simoarpe** [comment]
Closing this as not relevant anymore.
