### ISSUE TITLE
Can not change adsPerDay through UI

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#2977]
## Steps to Reproduce

1. Go to `brave://rewards`
2. Enable rewards
3. Enable ads
4. Click on `Ads Settings`

## Actual result:

Not possible to change adsPerDay through UI
Only possible to set adds per hour
![image](https://user-images.githubusercontent.com/34715963/51218410-8ad54980-192c-11e9-80ec-71d8d512f0f2.png)

## Expected result:
Possible to change adsPerDay through UI
Which is required by the `Brave Ads Client V1.0 Client` spec:
`Follow max ads per day and max ads per hour user settings for capping ads`

## Brave version (brave://version info)

Brave | 0.60.13 Chromium: 72.0.3626.53 (Official Build) dev (64-bit)
-- | --
Revision | 98434e6cd182d68ce396daa92e9c6310422e6763-refs/branch-heads/3626@{#620}
OS | Windows

cc @mrose17 @brave/legacy_qa

**Comment by mrose17** [comment]
I am reliably informed that this is no longer a requirement.  Perhaps in the future, we may bring it back!
