### ISSUE TITLE
[Android] Implement auto-select via onFocus in country selection / geo declaration dropdown

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#29785]
Android version of: https://github.com/brave/brave-browser/issues/29606 

When user presses on the dropdown menu, it should be autoselected and scrolled down to the country we think the user is in. Note United States:

Right when user presses on dropdown menu:
![image](https://user-images.githubusercontent.com/11497541/232527031-4738e9c3-f69b-4b08-beac-744dacde56c3.png)

After user presses on United States:
![image](https://user-images.githubusercontent.com/11497541/232527071-a39675f0-27ba-4c72-bc40-a5123d2eade2.png)

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Vivo x70 Pro version 12` running `Bravemonoarm64,aapk_1.60.85`

- Confirmed OS country is selected first in the geo declaration dropdown
- Confirmed that the OS country is displayed alphabetically within the geo declaration dropdown

**OS country is `US`**

Example | Example | Example
----------|----------|----------
![Screenshot_20231012_164546](https://github.com/brave/brave-browser/assets/38657976/05fa6ec9-2452-4e6d-9614-e38cb4207132) | ![Screenshot_20231012_170624](https://github.com/brave/brave-browser/assets/38657976/3aa1a987-68eb-4c89-b803-dd32864dcee6) | ![Screenshot_20231012_170312](https://github.com/brave/brave-browser/assets/38657976/0a2ac575-b09b-4683-a711-e9b044857414)
