### ISSUE TITLE
Tor window always starts with default shields setting

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#2978]
## Description 

Tor window always starts with default shields settings when user has different shields settings in normal profile

## Steps to Reproduce

   1. Change any settings in default shields settings in normal window
   2. Launch tor window
   3. Check it is applied to tor window

## Actual result:

Tor window always starts with default shields setting

## Expected result:
Tor window starts with custom shields settings of normal window

## Reproduces how often: 

always

## Brave version (brave://version info)

every version

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
yes
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? No

### Additional Information

Currently, this is expected behavior because tor window uses different profile with other normal windows.

**Comment by user809256** [comment]
Is there any fix for this issue?

I kinda don't see point in Tor network when fingerprint and script shields are down by default. I need to enable all shields manually for every website because global settings don't exist for guest/tor user?

Please tell me if there is any workarounds currently for this issue. Thanks ^^

**Comment by yrliou** [comment]
This is fixed by https://github.com/brave/brave-core/pull/3319.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.72.110 Chromium: 78.0.3904.70 (Official Build) dev (64-bit)
-- | --
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS | Ubuntu 18.04 LTS

Verified test plan from the description
Verified test plan from https://github.com/brave/brave-core/pull/3319
Verified bookmarks and global settings are shared between normal and tor window. Extensions are not shared yet per https://github.com/brave/brave-browser/issues/2307#issuecomment-538018323
Verified that brave://settings page is redirected to normal window.
