### ISSUE TITLE
Blank/grey tab is shown in between tabs after scrolling down to the last tab and scrolled back up in light theme

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#29791]
## Description 

@kjozwiak noticed this issue initially.  Reproduced in 1.51.87 while testing https://github.com/brave/brave-browser/issues/29692.   If Brave browser is set to light theme and after  enabling vertical tab view, scrolling down to the last tab and scrolling back up, a blank/grey tab is shown in between tabs. 

## Steps to Reproduce

1. Install 1.51.87
2. launch Brave
3. open brave://flags
4. select Enabled for #brave-vertical-tabs
5. click Relaunch
6. visited bbc.com
7. right click on the tab to open context menu
8. enable `Use vertical tabs`
9. add few tabs in the vertical sidepanel to enable scroll
10. scroll down to the last tab which will be highlighted to grey
11. scroll back up 

## Actual result:

blank grey tab is shown in between tabs when scrolled back up. 
![image](https://user-images.githubusercontent.com/98358127/232578811-39ac9d49-07b9-4f80-8cf0-78a4e5fd8b49.png)

https://user-images.githubusercontent.com/98358127/232578368-73f3d28a-2552-4ffe-8de6-56a36660392b.mp4

## Expected result:
Tabs should be highlighted with grey similar to 1.52.x?

![image](https://user-images.githubusercontent.com/98358127/232575994-6c86edbd-9f2f-45f5-8b4b-46e94d8b7999.png)

## Brave version (brave://version info)

```
Brave | 1.51.87 Chromium: 112.0.5615.49 (Official Build) beta (64-bit)
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Windows 11 Version 22H2 (Build 22621.1555)
```
## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
@rebron @sangwoo108 
cc: @brave/qa-team

**Comment by kjozwiak** [comment]
The above requires `1.51.100` or higher for `1.51.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.51.109 Chromium: 113.0.5672.63 (Official Build) (x86_64)
-- | --
Revision | 0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}
OS | macOS Version 11.7.6 (Build 20G1231)

Reproduced the issue using `1.51.87`; confirmed the gray tab at the bottom, after scrolling down and back up

<img width="1829" alt="Screen Shot 2023-05-01 at 12 37 45 PM" src="https://user-images.githubusercontent.com/387249/235517425-008aa94c-9d53-4c5e-a30b-b345374a5ab2.png">


### Steps:
1. installed `1.51.109`
2. launched Brave
3. ensured I was using the `Light` theme
4. switched to using vertical tabs
5. opened a bunch of tabs
6. looked at the bottom tab(s)

### Confirmed the tab highlight was the right color/style, and there were no blank/gray tabs after scrolling up and down

<img width="1795" alt="Screen Shot 2023-05-01 at 12 30 55 PM" src="https://user-images.githubusercontent.com/387249/235516403-adfffb5f-7933-4681-991f-4129815ecd23.png">
