### ISSUE TITLE
Rename `Addresses, payment info, etc.` Sync pref

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#29813]
At the commit https://github.com/brave/brave-core/pull/13562/commits/6fb25244d32873004d52076325ac6b15f8724418 error was introduced, that datatype does not sync credit card info.
It should be renamed to `Phone numbers, emails, and addresses`

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.52.86 Chromium: 113.0.5672.77 (Official Build) beta (x86_64)
-- | --
Revision | c4236862955e005c2187105415ac4a2ecf86dff1-refs/branch-heads/5672_62@{#3}
OS | macOS Version 11.7.6 (Build 20G1231)

### Steps:
1. installed `1.52.86`
2. launched Brave
3. loaded `brave://sync`
4. clicked on `Start using Sync`
5. clicked on `Start a New Sync Chain`
6. clicked on `Computer`
7. clicked `OK`
8. clicked on `Manage your synced devices`
9. scrolled down and looked at the last label

### Confirmed the label now reads `Phone numbers, emails, and addresses`


`1.52.86` | `1.51.110`
----------|----------
<img width="1278" alt="Screen Shot 2023-05-04 at 8 11 20 AM" src="https://user-images.githubusercontent.com/387249/236251706-2165d1b0-9582-4fda-8b70-dedc0cd07344.png"> | <img width="1312" alt="Screen Shot 2023-05-04 at 8 12 15 AM" src="https://user-images.githubusercontent.com/387249/236251715-0a12b810-0843-49e0-aebe-324e0273de82.png">

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave	1.52.102 Chromium: 113.0.5672.126 (Official Build) beta (32-bit)
Revision	c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}
OS	Android 9; Build/PQ2A.190305.002; 28; REL
```

### Steps:
1. installed `1.52.102`
2. launched Brave
3. tapped the 3-dot menu
4. tapped `Settings`
5. tapped `Sync`
6. tapped `Start a new sync chain`
7. tapped `Add a Mobile Device`
8. tapped `Done`
9. tapped `Data Preferences`
10. examine the sync fields' labels

### Confirmed the string now reads `Phone numbers, emails, and addresses`

`1.52.102` | `1.51.114`
-----------|----------
![Screenshot_20230518-122717](https://github.com/brave/brave-browser/assets/387249/b7f5ad4f-5a31-478c-9376-b721ca52211e) | ![Screenshot_20230518-122810](https://github.com/brave/brave-browser/assets/387249/4e4d24b8-a834-478f-abe5-14e4dbd471b5)
