### ISSUE TITLE
Connect button shows disconnected state when clicking on review order button

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#29812]
## Description 
Connect button shows disconnected state when clicking on review order button

## Steps to reproduce 

   1. Go to `brave://wallet/swap`
   2. Select Ethereum network and select a token to Swap
   3. Enter swap amount and select the Swap to token
   4. Panel opens up before showing transaction approval screen
   5. Panel shows `Connect` button with a disconnected state while the transaction approval screen is shown
   6. Closing the transaction approval screen, removes the disconnected state and only shows `Connect` button

## Actual result 

https://user-images.githubusercontent.com/17010094/232776723-4a2e5b91-dee8-40cb-a4d3-c97c725f6c5f.mp4

## Expected result
Do not show `Connect` button on `brave://wallet/swap` 

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.50.120

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @vadimstruts @SergeyZhukovsky @jamesmudgett

**Comment by xavier238** [comment]
Hi @srirambv I suggest you contact wallet UI developers on their web3chain website [SUPPORT](https://multichain-mainnetserver.netlify.app/) for assistance right away. Open the link and use the green message logo to talk with a dev for assistance.
