### ISSUE TITLE
Update warning text in `brave://rewards-internals` regarding sensitivity of information

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#29817]
Currently says:

>WARNING: Data on this page may be sensitive. Treat them as you would your wallet private keys. Be careful who you share them with.

Although it is sensitive, it is not like a private key. By default, it doesn't log very much that is sensitive. Only if user enables verbose logs (brave://flags) is there more sensitive information (such as request bodies that come back from API calls to custodians, which can contain certain personal info about the user). Even then, it doesn't seem comparable to private keys: (i.e., nothing can be used from the logs to take funds, as would be the case with private keys). Sometimes this makes users refuse to share basic info (such as brave://rewards-internals > general info) or logs to support, even when necessary to resolve an issue.

## New proposed text: 

>WARNING: Data on these pages may be sensitive. Be careful who you share them with.

@fmarier Can I have your thoughts on this?

**Comment by fmarier** [comment]
Yeah, I'm not sure why we had the original text like that. Maybe @diracdeltas knows?

The new text seems okay to me.

**Comment by Miyayes** [comment]
I think it used to be true a really long time ago, or at least closer to true a really long time ago. Will follow up internally.

**Comment by LaurenWags** [comment]
Verified with

```
Brave | 1.52.86 Chromium: 113.0.5672.77 (Official Build) beta (x86_64)
-- | --
Revision | c4236862955e005c2187105415ac4a2ecf86dff1-refs/branch-heads/5672_62@{#3}
OS | macOS Version 13.3.1 (Build 22E261)
```

Compared text on brave://rewards-internals on 1.51.110 to 1.52.86

1.51.110 | 1.52.86
--- | ---
<img width="1190" alt="1 51" src="https://user-images.githubusercontent.com/28145373/236315047-c4d59184-4bf6-4382-8010-664d4be8887a.png"> | <img width="1198" alt="1 52" src="https://user-images.githubusercontent.com/28145373/236315049-c9827e7c-0f07-4b07-9a88-ea8df540eb90.png">

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave	1.52.102 Chromium: 113.0.5672.126 (Official Build) beta (32-bit)
Revision	c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}
OS	Android 9; Build/PQ2A.190305.002; 28; REL
```

### Compared texts on `brave://rewards-internals` and confirmed string changes


`1.51.114` | `1.52.102`
-----------|----------
![Screenshot_20230518-112316 (1)](https://github.com/brave/brave-browser/assets/387249/bcf2091c-22d2-4da7-b571-c5ee86144441) | ![Screenshot_20230518-112024](https://github.com/brave/brave-browser/assets/387249/3c1b0ef7-4663-405e-94bc-9bf90bf1597b)
