### ISSUE TITLE
update "Float on mouseover" text

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#29818]
## Description 

Per https://bravesoftware.slack.com/archives/C042KL922P3/p1681485812446839?thread_ts=1681407763.525229&cid=C042KL922P3, the option "Float on mouseover" should be renamed/re-worded as it is confusing.

## Steps to Reproduce

   1. Have vertical tabs enabled
   2. Look for "Float on mouseover"

## Actual result:

<img width="710" alt="Screenshot 2023-05-05 at 10 48 29 AM" src="https://github.com/brave/brave-browser/assets/5951041/f8f8a75b-dbe3-4d19-90ed-25e0167f2e8a">

"Float on mouseover" shown as context menu option for vertical tabs

## Expected result:

Label for setting should be `Expand vertical tabs panel on mouseover when collapsed`

## Reproduces how often: 

easily

## Brave version (brave://version info)

1.52.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

cc @rebron

**Comment by rmcfadden3** [comment]
@rebron — just re-read the thread. I'd still vote "Hide / show on mouse over"

**Comment by kjozwiak** [comment]
The above requires `1.52.110` or higher for `1.52.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.52.112 Chromium: 114.0.5735.35 (Official Build) (x86_64)
-- | --
Revision | 2295354895fa3652ae47b651481831484f16d1ff-refs/branch-heads/5735@{#713}
OS | macOS Version 13.5 (Build 22G5027e)

### Steps:
1. installed `1.52.112`
2. launched Brave
3. context-clicked on a tab and chose Use Vertical Tabs
4. opened `brave://settings/appearance`
5. confirmed pref label below `Show title bar` changed

Confirmed the text now reads, "`Expand vertical tabs panel on mouseover when collapsed`"

<img width="1623" alt="Screenshot 2023-05-25 at 11 25 43 AM" src="https://github.com/brave/brave-browser/assets/387249/e79de0a6-ef75-4ea2-b1fc-6497647186f9">
