### ISSUE TITLE
`start_date` and `end_date` in variation seed is not respected

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#29810]
`start_date` and `end_date` in variation seed is ignored.

## Steps to Reproduce

1. Make sure that the study is enabled on [griffin](https://github.com/brave/brave-variations/blob/a5d9a0f052ae7514fa79ef450d53973627ac7874/seed/seed.json#L599). 
1. Clean profile
1. Use staging seed variation
1. Run Brave
1. Restart Brave:
1. Open `brave://version`
1. Scroll down to `Active Variations`

## Actual result:
The study is enabled:
```
DefaultAdNotificationsPerHour=10/MaximumAdNotificationsPerDay=100/MaximumInlineContentAdsPerHour=6/MaximumInlineContentAdsPerDay=20/AdServingVersion=2
```
![image](https://user-images.githubusercontent.com/34715963/232771404-86ccbaae-e782-4bda-9613-a21bdd2c2893.png)

## Expected result:
The study is enabled:
```
DefaultAdNotificationsPerHour=10/MaximumAdNotificationsPerDay=100/MaximumInlineContentAdsPerHour=6/MaximumInlineContentAdsPerDay=20/MaximumNewTabPageAdsPerDay=0/AdServingVersion=2
```

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

Brave | 1.51.80 Chromium: 112.0.5615.49 (Official Build) beta (64-bit) 
-- | --
Revision | bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}
OS | Ubuntu 18.04 LTS

cc @tmancey @aseren @iefremov @goodov

**Comment by goodov** [comment]
@btlechowski start_date/end_date now work as expected.

![image](https://user-images.githubusercontent.com/5928869/232812552-a11d436e-cee7-4f20-9780-71a72577aacb.png)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.50.121 Chromium: 112.0.5615.138 (Official Build) (64-bit) 
-- | --
Revision | 2258f2fcaeb07bc95c992b7ca47f0b43ead9865c-refs/branch-heads/5615@{#1282}
OS | Ubuntu 18.04 LTS

Verified `start_date` and `end_date` are supported as study that is only available on 18th Apr is enabled on that date

Verified study with `MaximumNewTabPageAdsPerDay=0` is enabled
![image](https://user-images.githubusercontent.com/34715963/233079818-d7319508-4a73-4eea-bb1e-9005caa5763c.png)


Verified NTPSI was not served:
```
[28916:28916:0419/145856.808365:VERBOSE2:permission_rule_util.cc(25)] You have exceeded the allowed new tab page ads per day
[28916:28916:0419/145856.808638:VERBOSE1:new_tab_page_ad_serving.cc(65)] New tab page ad not served: Not allowed due to permission rules

```

**Comment by kjozwiak** [comment]
Going to move this into `1.51.x` even though it technically will go live earlier via `1.50.x` once it's pushed to `production` via https://github.com/brave/brave-variations/pull/596. But `1.51.x` is the next major release so we'll add it into this milestone.
