### ISSUE TITLE
What happened to binary downloads of release candidates?

### ISSUE THREAD

**Issue by Smooey** [brave/brave-browser#2981]
Not all Linux distros are Ubuntu, Fedora, etc and not all have Brave in their Repos. So how does someone download the old desired "brave-{version}-linux-x64.zip" archives, so they can extract it and install it, etc? Or are there instructions and so forth to install for Slackware, Gentoo, etc? You do realize right that not all distros have Brave in their repos, unless you're only catering to distros that do have Brave in their repos and all other distros that don't, can go jump off a bridge? Can someone tell me how to use Ubuntu DEB repo to slackware or void linux etc?

So explain how this will work in Slackware? 

curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo apt-key add -

source /etc/os-release

echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ $UBUNTU_CODENAME main" | sudo tee /etc/apt/sources.list.d/brave-browser-release-${UBUNTU_CODENAME}.list

sudo apt update

sudo apt install brave-browser brave-keyring

**Comment by Brave-Matt** [comment]
@Smooey, this question is best left in places like our [Community Website.](https://community.brave.com) Repost there and I'd be happy to help you out.

**Comment by rebron** [comment]
Closing. Will take care of response/support in community website.

**Comment by Smooey** [comment]
I had account deleted in community so can't post there hence posting here lol
