### ISSUE TITLE
Revert changes to Extensions page strings

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#2982]
Due to localization issues with string containing tags brave/brave-core#1080, which fixed #1013 and #2497, needs to be reverted.

**Comment by mkarolin** [comment]
Clarification: on Extensions page phrases `You don't have any extensions yet. Would you like to [install some]?` (when you have no extensions installed) and `Looking for even more extensions?` (when you have installed extensions) will revert to `Find extensions and themes in the [Web Store]` in both cases.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.59.26 Chromium: 72.0.3626.64 (Official Build) beta (64-bit)
-- | --
Revision | eaa9668e80ce5405e7f1902579558ea725c06ca1-refs/branch-heads/3626@{#708}
OS | Windows 7

![image](https://user-images.githubusercontent.com/34715963/51453475-edb94d00-1d3f-11e9-8e59-d15a7f589ea4.png)
![image](https://user-images.githubusercontent.com/34715963/51453499-04f83a80-1d40-11e9-9a25-fe3129b80ce3.png)
