### ISSUE TITLE
Rename BraveVpnServiceName to BraveVpnHelperName

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#29820]
In order to prepare to land implementation of  https://github.com/brave/brave-browser/issues/29253  we need to do some refactorings. BraveVpnHelper is used as BraveVpnService sometimes and would be better to name it as BraveVpnHelper evrywhere

**Comment by stephendonner** [comment]
Since I'm blocked on `Windows 10` by https://github.com/brave/brave-browser/issues/30291 (thx @MadhaviSeelam !), will test `macOS` end-to-end, as a regression check 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.52.94 Chromium: 113.0.5672.92 (Official Build) beta (x86_64)
-- | --
Revision | b6f521170062a1fa8a82c33fb223b06fec566da1-refs/branch-heads/5672_63@{#10}
OS | macOS Version 11.7.6 (Build 20G1231)

### Steps:
1. installed `1.52.94`
2. launched Brave
3. using `account.bravesoftware.com`, purchased, configured, and connected to `Brave VPN`
4. changed regions to Brazil
5. loaded `browserleaks.com/dns` and confirmed no IPv4 or IPv6 DNS-server IP address leaks

### Confirmed I could purchased, configure, and connect to `Brave VPN`

example | example | example | example
---------|----------|---------|---------
<img width="1312" alt="Screen Shot 2023-05-11 at 5 12 12 PM" src="https://github.com/brave/brave-browser/assets/387249/bd785a13-2efd-4c06-8bc9-83ea5bcede9c"> | <img width="1628" alt="Screen Shot 2023-05-11 at 5 14 00 PM" src="https://github.com/brave/brave-browser/assets/387249/beeeeabc-97d0-4de3-8ddb-012e71f25c82"> | <img width="1628" alt="Screen Shot 2023-05-11 at 5 14 06 PM" src="https://github.com/brave/brave-browser/assets/387249/06cba6ef-fc51-4c1b-9121-e65096a59888"> | <img width="1628" alt="Screen Shot 2023-05-11 at 5 14 33 PM" src="https://github.com/brave/brave-browser/assets/387249/bcf94afe-5122-4eda-97cb-2a6c1303e499">

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.52.99 Chromium: 113.0.5672.92 (Official Build) beta (64-bit)
-- | --
Revision | b6f521170062a1fa8a82c33fb223b06fec566da1-refs/branch-heads/5672_63@{#10}
OS | Windows 10 Version 22H2 (Build 19045.2965)

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.52.102 Chromium: 113.0.5672.126 (Official Build) beta (64-bit)
-- | --
Revision | c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}
OS | Windows 11 Version 22H2 (Build 22621.1702)
```
