### ISSUE TITLE
Private window doesn't respect "Ask where to save each file before downloading" option.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#29823]
Based on the comment https://github.com/brave/brave-browser/issues/28562#issuecomment-1509355291

Reproduced with `1.52.51`

STR:

1. Start Brave
2. Navigate to brave://settings/downloads
3. Toggle the `Ask where to save each file before downloading` setting to `off`
4. Paste a file download link (e.g. http://ipv4.download.thinkbroadband.com:8080/1GB.zip) into the location bar and press <Enter>
5. Click "Continue to site" on the "Connection is not secure" page
6. **Observe:** the download starts without asking where to save the file (the download progress bubble is shown)
7. Open a Private window
8. Repeat steps 4-5

**Actual result:**
* Save File dialog is shown

**Expected result:**
* Save File dialog is **NOT** shown
* The download starts (the download progress bubble is shown)

**NOTE:** Also reproducible in Chrome (`113.0.5672.35`).

**Comment by mkarolin** [comment]
Upstream issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1381219

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.53.67 Chromium: 114.0.5735.53 (Official Build) beta (x86_64)
-- | --
Revision | c499d7ea22c8b2dba278465a5df7b86a8efa4e64-refs/branch-heads/5735@{#970}
OS | macOS Version 11.7.7 (Build 20G1345)

#### Followed the steps to reproduce provided in https://github.com/brave/brave-browser/issues/29823#issue-1673441291.

### Confirmed I wasn't prompted to save the file with the file picker; it just auto-downloaded, in both `Normal` and `Private`-window cases

### `Settings`

<img width="1647" alt="Screen Shot 2023-05-26 at 6 48 50 PM" src="https://github.com/brave/brave-browser/assets/387249/45851ebe-16f7-4875-9457-faf95d750ca6">

### `Normal Window`

example | example | example
--------|-----------|---------
<img width="1312" alt="Screen Shot 2023-05-26 at 6 58 54 PM" src="https://github.com/brave/brave-browser/assets/387249/131fd979-3bac-4669-a94b-676d224ed493"> | <img width="1312" alt="Screen Shot 2023-05-26 at 6 58 59 PM" src="https://github.com/brave/brave-browser/assets/387249/045715af-bd8b-4bde-9f6a-9bd04e6822ec"> | <img width="1312" alt="Screen Shot 2023-05-26 at 6 59 06 PM" src="https://github.com/brave/brave-browser/assets/387249/ec72f4f4-33c1-4265-9847-70ff4641afdd">

### `Private Window`

example | example | example
---------|----------|--------
<img width="1312" alt="Screen Shot 2023-05-26 at 6 59 39 PM" src="https://github.com/brave/brave-browser/assets/387249/26ad42cd-a677-41b8-badb-a230ca4280d0"> | <img width="1312" alt="Screen Shot 2023-05-26 at 6 59 47 PM" src="https://github.com/brave/brave-browser/assets/387249/a15d79ea-d2e7-4317-85cb-5a93af43818c"> | <img width="1312" alt="Screen Shot 2023-05-26 at 6 59 51 PM" src="https://github.com/brave/brave-browser/assets/387249/22055792-0c10-40aa-890a-81a10f27bc5e">

**Comment by stephendonner** [comment]
Spun off https://github.com/brave/brave-browser/issues/30626 while testing the above 👍

**Comment by xxjoe2** [comment]
still showing download prompt for me on both windws and linux in private mode, no problem with chrome (ungoogled) nor vivaldi

[https://github.com/brave/brave-browser/releases/download/v1.54.52/brave-v1.54.52-win32-x64.zip](url)

![Capture1](https://github.com/brave/brave-browser/assets/83495134/ff422a3a-cedf-4e82-81c7-7a5e1802464c)
![Capture2](https://github.com/brave/brave-browser/assets/83495134/8ed2b349-d1e8-4627-a9fc-ace74896e8b5)
![Capture3](https://github.com/brave/brave-browser/assets/83495134/02546729-0e49-42b5-b68e-715c8dad9d7e)
