### ISSUE TITLE
Change "Brave Web Store" strings to "Web Store"

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#2983]
Because of localization issues with string containing tags and consequently brave/brave-core#1080 (which fixed #1013 and #2497) being reverted (by #2982), strings showing "Brave Web Store" would show up on Extensions page and elsewhere. We need to apply the same fix as was done in #2625 to 0.59.x and above - replace `Chrome Web Store` to just `Web Store`, so that it doesn't get affected by global replacement of Chrome with Brave.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.59.26 Chromium: 72.0.3626.64 (Official Build) beta (64-bit)
-- | --
Revision | eaa9668e80ce5405e7f1902579558ea725c06ca1-refs/branch-heads/3626@{#708}
OS | Windows 7

Used test plan from https://github.com/brave/brave-core/pull/1358

![image](https://user-images.githubusercontent.com/34715963/51453475-edb94d00-1d3f-11e9-8e59-d15a7f589ea4.png)
![image](https://user-images.githubusercontent.com/34715963/51453499-04f83a80-1d40-11e9-9a25-fe3129b80ce3.png)
![image](https://user-images.githubusercontent.com/34715963/51453618-b5663e80-1d40-11e9-8fda-7e32a768809f.png)

**Comment by yodaross** [comment]
TeamBrave

Your handwork will not gunappreciated

Sometimeshashesinthenglish(ofcourseyoualreadyknow);

Wemayhavesomepensionsinterestedinworkingwithyourbatokens

Solookaliveweneverdie

Bornsandbondsandyouwillrollforever

Letsusknowifyouneedanything

Besidesemployees, maybefunandusun





On Jan 20, 2019, at 11:52 PM, btlechowski <notifications@github.com> wrote:

Verification passed on

Brave	0.59.26 Chromium: 72.0.3626.64 (Official Build) beta (64-bit)
Revision	eaa9668e80ce5405e7f1902579558ea725c06ca1-refs/branch-heads/3626@{#708 <https://github.com/brave/brave-browser/issues/708>}
OS	Windows 7
Used test plan from brave/brave-core#1358 <https://github.com/brave/brave-core/pull/1358>
 <https://user-images.githubusercontent.com/34715963/51453475-edb94d00-1d3f-11e9-8e59-d15a7f589ea4.png>
 <https://user-images.githubusercontent.com/34715963/51453499-04f83a80-1d40-11e9-9a25-fe3129b80ce3.png>
 <https://user-images.githubusercontent.com/34715963/51453618-b5663e80-1d40-11e9-8fda-7e32a768809f.png>
