### ISSUE TITLE
Activity events are triggered for restored tabs

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#29830]

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.52.86 Chromium: 113.0.5672.77 (Official Build) beta (64-bit) 
-- | --
Revision | c4236862955e005c2187105415ac4a2ecf86dff1-refs/branch-heads/5672_62@{#3}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/18130

<details>

Verified following events are triggered after `Successfully initialized ads`:
- User activity triggered events: Triggered event: …
- File resource initialized events: Successfully initialized … resource
- Tab events tab_manager.cc: Tab id HTML content changed, Tab id text content changed, Opened new tab

</details>
