### ISSUE TITLE
Update Wallet Line Chart to Wallet V2

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#29834]
## Description 

Update the Wallet LineChart to match the new Wallet V2 designs

![Screenshot 80](https://user-images.githubusercontent.com/40611140/232894561-53874fc6-8a47-4e75-bbae-23235df02899.png)

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.52.94 Chromium: 113.0.5672.92 (Official Build) beta (64-bit) 
-- | --
Revision | `0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}`
OS | Linux

- Verified steps from [brave/brave-core#18132](https://github.com/brave/brave-core/pull/18132)
- Verified LineChart is updated as per the new design
- Verified LineChart is updated on both portfolio and tokens

https://github.com/brave/brave-browser/assets/17010094/63006edd-9235-43a0-aa5a-aa57063932d4

---------------------

**Verification passed on**

Brave | 1.52.94 Chromium: 113.0.5672.92 (Official Build) beta (64-bit)
-- | --
Revision | `0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from [brave/brave-core#18132](https://github.com/brave/brave-core/pull/18132)
- Verified LineChart is updated as per the new design
- Verified LineChart is updated on both portfolio and tokens

https://github.com/brave/brave-browser/assets/17010094/59626b52-1c00-4568-a2a2-1e8c819660a1

---------------------

**Verification passed on**

Brave | 1.52.94 Chromium: 113.0.5672.92 (Official Build) beta (arm64)
-- | --
Revision | `0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#18132](https://github.com/brave/brave-core/pull/18132)
- Verified LineChart is updated as per the new design
- Verified LineChart is updated on both portfolio and tokens

https://github.com/brave/brave-browser/assets/17010094/2f5d4e7b-b180-4635-b67a-90dda1c8de89
