### ISSUE TITLE
Remove `PurchasedState::INVALID` from `BraveVpnService`

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#29846]
## Description 
We currently have a `PurchasedState::INVALID` which (when set) will show this message to the user:
![image](https://user-images.githubusercontent.com/4733304/232980822-1547fca9-c436-47b7-883c-2d67368921b0.png)

There are a few problems with this:

1. At no time do we ever have any billing information. This error is misleading - it was one of the original messages we made and the circumstances that show it have changed. We also don't have a proper deep link for `Edit payment method`. It's just getting the person into account.brave.com

2. The conditions putting the user into `PurchasedState::INVALID` are wrong. We currently allow this to happen in two scenarios:
    - `BraveVpnService` passes SKU credential to Guardian VPN but credential has already been redeemed
    - When SKU backend presents a credential which (when compared to system clock) is expired

Both of these situations, we should instead use the `PurchasedState::FAILED` state. 

We should also consider allowing for `PurchasedState::FAILED` to show a custom message (to go along with the generic message). If we allow a custom message to be shown, we can show a real error message which can help support with troubleshooting. If we do allow a custom message, we should provide the text ourselves and NOT present response text from the service call (unless we create a privacy/security review and showing that is OK).

## Notes on removal
- We can remove the `PurchasedState::INVALID` enum value from the code
- We can replace conditions using this with `PurchasedState::FAILED`
- In the webui code, we need to remove the `ViewType.Invalid` value and where it's used in https://github.com/brave/brave-core/blob/master/components/brave_vpn/resources/panel/container.tsx
- In the webui code, we can completely delete the `error-subscription-failed-panel` component https://github.com/brave/brave-core/blob/master/components/brave_vpn/resources/panel/components/error-subscription-failed-panel/index.tsx

**Comment by kjozwiak** [comment]
The above requires `1.51.109` or higher for `1.51.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave | 1.51.110 Chromium: 113.0.5672.77 (Official Build) (64-bit)
-- | --
Revision | c4236862955e005c2187105415ac4a2ecf86dff1-refs/branch-heads/5672_62@{#3}
OS | Windows 10 Version 21H2 (Build 19044.2846)
```
### Token no longer valid - ``
<details>

### Steps:
1. installed `1.53.10`
2. launched Brave
3. purchased, configured, and connected to `Brave VPN`
4. shut down Brave
5. opened `Local State` in my user-profile dir
6. changed the following:
```
"subscriber_credential":{"credential":"","expiration":"13027600124000000", "skus_credential": "111"}}
```
7. relaunched Brave
8. connected to `Brave VPN`
9. examined the error message

### Confirmed I saw the `Token no longer valid` error message

![image](https://user-images.githubusercontent.com/387249/235729130-745324d0-3485-4660-b4d0-bd86d9e89ee6.png)

</details>

### Credentials expiry date elapsed - ``
<details>

### Steps:
1. installed `1.53.10`
2. launched Brave
3. purchased, configured, and connected to `Brave VPN`
4. shut down Brave
5. opened `Local State` in my user-profile dir
6. edited `"expiration":"13327600124000000"` -> `"expiration":"13027600124000000"` (replaced the 2nd `3` with a `0`)
7. relaunched Brave
8. connected to `Brave VPN`
9. noted the error message

### Confirmed I got the `Session Expired` error message, with `log in` link

brave://local-state | `Session expired` 
---------------------|------------------
![image](https://user-images.githubusercontent.com/387249/235773614-6743eed0-6629-40a8-8ded-3fc2fa1f44cc.png) | ![image (1)](https://user-images.githubusercontent.com/387249/235732003-ecd6eee6-beaa-4618-82b3-db5f72dba1a6.png)


</details>

**Comment by LaurenWags** [comment]
Tested the below cases using

```
Brave | 1.51.110 Chromium: 113.0.5672.77 (Official Build) (x86_64)
-- | --
Revision | c4236862955e005c2187105415ac4a2ecf86dff1-refs/branch-heads/5672_62@{#3}
OS | macOS Version 13.3.1 (Build 22E261)
```

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using
