### ISSUE TITLE
`Learn more` under the HTTPS only interstitial page pointing to Google support page

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#29844]
## Description 

When visiting a website that can't be upgraded to `HTTPS` when `Only connect with HTTPS` is selected via the shields panel, clicking on the `Learn more` link via the interstitial page will first open https://support.google.com/chrome?p=first_mode and then will redirect the user to https://support.google.com/chrome/answer/10468685?visit_id=638174771573106524-829840701&p=first_mode&rd=1#https-only-mode. We usually prefer to point users to the `Brave Help Center` via https://support.brave.com/hc/en-us.

## Steps to Reproduce

   1. install brave and visit http://insecure.arthuredelstein.net
   2. set the shields settings to `Only connect with HTTPS`
   3. reload the page and you should see a `The connection to insecure.arthuredelstein.net is not secure` interstitial page
   4. click on `Learn more` and you'll notice a Google support page being opened rather than a Brave support page

## Actual result:

User is redirected to https://support.google.com/chrome/answer/10468685?visit_id=638174771573106524-829840701&p=first_mode&rd=1#https-only-mode which is a Google support page.

## Expected result:

We should probably be point users to a support page via https://support.brave.com/hc/en-us

## Reproduces how often: 

100% reproducible using the STR/Cases outlined above.

## Desktop Brave version:

```
Brave | 1.52.54 Chromium: 112.0.5615.121 (Official Build) nightly (64-bit)
-- | --
Revision | 39cc4e45904ae9f1741c4fbaa866e629c96f2268-refs/branch-heads/5615_51@{#8}
OS | Windows 11 Version 22H2 (Build 22621.1555)
```

## Android Device details:
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Pixel 6` (mobile but all devices are affected)
   - Android version: `Android 14`

Same versions of `Android` are also affected as this is a `Desktop` & `Android` issue.

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @arthuredelstein  @fmarier @Brave-Matt in case we need a new entry created under https://support.brave.com/hc/en-us.

**Comment by arthuredelstein** [comment]
I created proposed text in Google docs, here: https://github.com/brave/support/issues/4488

**Comment by arthuredelstein** [comment]
QA testing idea:
- First test in a Tor Window, then set Upgrade Connections to HTTPS to Strict (global shield settings) and test in a normal window.
- To test:
  - Visit http://insecure.arthuredelstein.net or http://http.badssl.com
  - Confirm that the interstitial warning page is shown
  - Click on the "Learn More link" and confirm that it takes you to the relevant page on https://support.brave.com

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.53.67 Chromium: 114.0.5735.53 (Official Build) beta (x86_64)
-- | --
Revision | c499d7ea22c8b2dba278465a5df7b86a8efa4e64-refs/branch-heads/5735@{#970}
OS | macOS Version 11.7.7 (Build 20G1345)

### `Private window with Tor`

http://insecure.arthuredelstein.net | http://http.badssl.com
-----------------------------------|-----------------------


### Normal window

http://insecure.arthuredelstein.net | http://http.badssl.com
-----------------------------------|-----------------------

**Comment by vlad-hoff** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 [panther_beta-user 14 UPB2.230407.019 release-keys]
Brave build: 1.53.81
Chromium: 114.0.5735.90 (Official Build) beta (64-bit)
Revision: 386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}
```
---------------------------
<details>
<summary> Private Tab - PASS </summary>

**STEPS:**
1. Launch Brave and open `New Private tab` from any entry point
2. Go to http://insecure.arthuredelstein.net/
3. Brave Shields > Upgrade connections to HTTPS
4. Set the shields settings to `Require all connections to use HTTPS (strict)` > Done
5. Reload the page > You should see a `The connection to insecure.arthuredelstein.net is not secure` interstitial page
6. Tap `Learn more` > Verify

**ACTUAL RESULTS:**
- Verified that https://support.brave.com/hc/en-us/articles/15513090104717 is opened in `Private tab`

https://github.com/brave/brave-browser/assets/128532965/a7937fb6-0b4b-4741-a7a2-3f2a8b0348a3

</details>

<details>
<summary> Normal Tab - PASS </summary>

**STEPS:**
1. Launch Brave and open `New tab` from any entry point
2. Go to http://insecure.arthuredelstein.net/
3. Brave Shields > Upgrade connections to HTTPS
4. Set the shields settings to `Require all connections to use HTTPS (strict)` > Done
5. Reload the page > You should see a `The connection to insecure.arthuredelstein.net is not secure` interstitial page
6. Tap `Learn more` > Verify

**ACTUAL RESULTS:**
- Verified that https://support.brave.com/hc/en-us/articles/15513090104717 is opened in `Normal tab`

https://github.com/brave/brave-browser/assets/128532965/a983e326-e4b4-432c-bf1e-af78e9ac196c

</details>
