### ISSUE TITLE
make top of window resizable when `Show title bar` is disabled

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#29842]
## Description 

When a user enables `vertical tabs`, the title bar is removed by default via the `Show title bar` setting. However, this removes the functionality/ability to resize the window at the top. Users can still resize by either dragging the corners or the bottom of the screen, but they lose the ability to resize the window where the title bar used to be.

## Steps to Reproduce

   1. install `1.52.54 Chromium: 112.0.5615.121`
   2. right click on a tab and select `Use vertical tabs`
   3. once selected, notice that the `title bar` has been removed
   4. attempt to resize the window using the top area where the `title bar` used to be displayed

## Actual result:

When `vertical tabs` are enabled, users lose the ability to resize windows from the top as per the following example:

![resize](https://user-images.githubusercontent.com/2602313/232964598-331f4732-9a77-4016-81b6-73866f09e8c3.png)

## Expected result:

Users should be able to resize the window from the top even though the `title bar` as been removed/disabled.

## Reproduces how often: 

100% reproducible using the STR/Cases outlined above.

## Brave version (brave://version info)

```
Brave | 1.52.54 Chromium: 112.0.5615.121 (Official Build) nightly (64-bit)
-- | --
Revision | 39cc4e45904ae9f1741c4fbaa866e629c96f2268-refs/branch-heads/5615_51@{#8}
OS | Windows 11 Version 22H2 (Build 22621.1555)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by kjozwiak** [comment]
The above requires `1.51.105` or higher for `1.51.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Filed a follow up issue https://github.com/brave/brave-browser/issues/30050 so QA passing this issue
