### ISSUE TITLE
Make default contribution amount 0.00 BAT

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#29858]
## Description

In the contribution banner, default amount selected is 5 BAT. If user presses "Send" right away, there's no additional confirmation screen, so it sends immediately. This could lead to unhappy misclicks and unexpected sends. 

We should make it 0.00 BAT so that user has to explicitly set the value they like.

Currently, if you input 0.00 BAT, it rounds up to 0.25 BAT. So this fix might interfere with that logic. 

- [ ] Make default input amount 0.00 BAT when contribution banner is initially opened

**Worth noting:** After vBAT sunset, we can also remove all the rounding logic around 0.25 BAT increments.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.52.86 Chromium: 113.0.5672.77 (Official Build) beta (x86_64)
-- | --
Revision | c4236862955e005c2187105415ac4a2ecf86dff1-refs/branch-heads/5672_62@{#3}
OS | macOS Version 13.3.1 (Build 22E261)
```
