### ISSUE TITLE
Monthly contributions are not going through in 1.51

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#29859]
## Description 
Found while testing https://github.com/brave/brave-browser/issues/28173
Monthly contributions are not going through in 1.51
## Steps to reproduce 

1. Clean profile `1.51.x` enabled Rewards and connect to an an external wallet
2. Set monthly tip to a verified publishers
3. Wait for the monthly tip to process 
7. The monthly contributions are not going through

## Actual result 

The monthly contributions are not going through

## Expected result
The monthly contributions should go through

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86): all
   - Device type (Phone, Tablet, Phablet):all
   - Android version: 12
   
## Brave version

1.51.80
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

CC: @brave/qa-team @Miyayes @zenparsing 

slack thread about the issue discussion https://bravesoftware.slack.com/archives/CNH9Q6REV/p1681746838676479

**Comment by Miyayes** [comment]
How to test this:
* Turn off A-C, then set up the monthly contribution (so there's no A-C in the way in the first place), and then see if the Monthly Contribution goes through. 

@zenparsing @GeetaSarvadnya

**Comment by LaurenWags** [comment]
tried several times using `1.51.105` and AC and monthly tips went through successfully on my Google Pixel 3XL. will sync with @GeetaSarvadnya  to see if we can determine where our steps differ.

I have some example logs I can share if needed.

**Comment by kjozwiak** [comment]
@LaurenWags @GeetaSarvadnya lets try to narrow this one down. If it's a real issue, we'll want to get this fixed in `1.51.x`. Sounds like it's not occurring in `1.50.x` as per the notes in the original issue so we'll be regressing users.

**Comment by GeetaSarvadnya** [comment]
@LaurenWags Thanks for cheking!

I have tried AC and monthly contribution together on `1.51.105`, only AC is going through. Also I have tried Monthly contribution alone (AC is turned OFF) monthly tips are NOT processing alone also. It looks strange I am not sure why it's working for me.

**Comment by GeetaSarvadnya** [comment]
The issue is Reproducible on both `Desktop` and `Android`. Steps which I followed on Desktop and Android are listed below.

**Desktop**

1. Clean profile `1.51.105`
2. Launch browser using cmd line flag `brave.exe --enable-logging=stderr --vmodule="*/bat-native-ledger/*"=9,"*/brave_rewards/*"=9,"*/bat-native-ads/*"=9,"*/bat-native-confirmations/*"=9,"*/brave_ads/*"=9,"*/brave_user_model/*"=9 --rewards=staging=true,rewards=debug=true`
3. Enable rewards and connect to a custodian
4. Setup AC and monthly tips
5. `Next Contribution date` is disaplyed as `27th May` in AC and monthly tips panel
6. Close the browser 
7. Set the sys date to `27th May`
8. Relaunched the browser
9. AC is processed
10. **_Monthly tips are not processed_**

**Android**

1. Clean profile `1.51.105`
2. Enable rewards staging flags via `QA preferences`
3. Enable rewards, select the country from the dropdown (I have selected UK as my uphold act is created for this region)
4. Connect to a uphold wallet
5. Open laurenwags.github.io
6. Setup default monthly tip of `1.25 BAT`
7. The site laurenwags.github.io was added into AC table
8. The `Next contribution date` is dispalyed as `27 May` in AC and Monthly tips panel
9. Removed app from memory
10. Set the system date as `27 May`
12. Relaunch the browser
13. In a min or so, site got removed from the AC table and AC went through
14. **_Waited for more than 30 mins, monthly tip did not process_**

**Comment by LaurenWags** [comment]
Reproduced on both desktop and android using @GeetaSarvadnya steps above and `1.51.106`.

Not sure if it's helpful, but when I was trying without any sites in my AC list (empty list, not AC disabled), I saw this in my logs (I took out superfluous info re: prefix list download, etc)

```
[27106:259:0527/093538.496519:VERBOSE1:contribution.cc(275)] Auto-contribute timer set for 2.592e+06 s
[27106:259:0527/093538.497075:VERBOSE1:contribution.cc(241)] Starting auto-contribute
[27106:259:0527/093538.498514:VERBOSE1:contribution_ac.cc(31)] Starting auto contribution
[27106:259:0527/093538.499832:VERBOSE1:contribution.cc(308)] Monthly contribution timer set for -3e-06 s
[27106:259:0527/093538.500754:VERBOSE1:publisher.cc(447)] Publisher list is empty
[27106:259:0527/093538.500868:VERBOSE1:contribution_ac.cc(51)] AC list is empty
[27106:259:0527/093538.502397:VERBOSE1:contribution.cc(216)] Starting monthly contributions
[27106:259:0527/093539.069106:VERBOSE1:contribution.cc(135)] Queue timer set for 2 s
[27106:259:0527/093539.298212:VERBOSE1:contribution.cc(308)] Monthly contribution timer set for 2.592e+06 s
```

Note, when I was initially trying via https://github.com/brave/brave-browser/issues/29859#issuecomment-1523988179, I had been using a similar command line but the one I was using had `reconcile-interval=10` as part of the `--rewards=` section. Seems like when we use command line to set this value then everything processes as expected, but without `reconcile-interval=somevalue`, then monthly tips do not process.

**Comment by kjozwiak** [comment]
The above requires `1.51.109` or higher for `1.51.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave | 1.51.109 Chromium: 113.0.5672.63 (Official Build) (64-bit)
-- | --
Revision | 0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}
OS | Windows 10 Version 21H2 (Build 19044.2846)

```

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.51.109`

<details>
<summary>Clean profile - </summary>

Per https://github.com/brave/brave-core/pull/18282#issue-1687240171, confirming that issue does not reproduce on a clean profile with RC/1.51.109.

1. Clean profile 1.51.109
2. Enable rewards staging flags via QA preferences
3. Enable rewards, select the country from the dropdown (I have selected UK as my uphold act is created for this region)
Connect to a uphold wallet
4. Setup AC and monthly tips (note, in Nightly setting a monthly tip sends one right away as well as schedules one for the future)
5. `Next Contribution date` is displayed as `31st May` in AC and monthly tips panel
6. Close the browser 
7. Set the sys date to `31st May`
8. Relaunched the browser
9. AC is processed
10. Confirmed monthly tips are processed

Step 4 | Step 4 | Step 9/10 | Step 9/10 | Step 9/10 | Step 9/10 | Step 9/10 
--- | --- | --- | --- | --- | --- | ---



</details>

<details>
<summary>Upgrade profile - </summary>

Per https://github.com/brave/brave-core/pull/18282#issue-1687240171, set up issue using 1.51.107 RC, then updated to version with the fix to confirm issue is resolved.

(**Note**: In Android we don't have option to rename the profile from RC to nightly, hence I have installed 1.52.x nightly build where I was able to reproduce the issue 29859, and then updated/installed 1.53.4 on top of it where the fix is available)

1. Clean profile `1.51.107` RC build
2. Enable rewards staging flags via QA preferences
3. Enable rewards and connect to a custodian
4. Setup AC and monthly tips (note, in 1.51.107 setting a monthly tip does not send one right away it only schedules one for the future)
5. `Next Contribution date` is displayed as `31st May` in AC and monthly tips panel
6. Close the browser 
7. Set the sys date to `31st May`
8. Update the profile to `1.51.109` with the fix
9. AC is processed
10. Confirmed monthly tips are processed

Step 4 | Step 4 | Step 9/10 | Step 9/10 | Step 9/10 | Step 9/10 
--- | --- | --- | --- | --- | --- 



</details>
