### ISSUE TITLE
Share button in Brave Shields does nothing

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#29856]
It happens on a stable 1.50.x channel as well. It looks like it regressed for some time.

Edit: It looks it works on some devices. I tried on Pixel 6 Android 13 and it doesn't work.

**Comment by deeppandya** [comment]
it's known issue for android 13. could be related to runtime permissions

**Comment by kjozwiak** [comment]
@deeppandya @SergeyZhukovsky I couldn't reproduce the issue I saw re: the icon being greyed out but I can confirm that I can reproduce the same issue on `Pixel 6` running `Android 14`. I can reproduce it without/with `Notifications` enabled.

```
Brave | 1.50.121 Chromium: 112.0.5615.138 (Official Build) (32-bit)
--- | ---
Revision | 2258f2fcaeb07bc95c992b7ca47f0b43ead9865c-refs/branch-heads/5615@{#1282}
OS | Android 13; Build/UPB1.230309.014
```

Even though the above mentions `Android 13`, it's `Android 14` as they haven't updated the OS version yet. Appears as `UpsideDownCake`.

STR/Cases:

* launch  `1.50.121 Chromium: 112.0.5615.138` and run through onboarding
* open any website and tap on the brave shields panel, tap on the `Share` icon and notice nothing happens

Reproduceable with `All Brave notifications` enabled and disabled. Seems to be working fine via `Android 12`. Tapping on the `Share` button initiates a request for permissions. I think @timchilds was right re: the above regressing with `Android 13` permissions introduction. Example of `Android 12` working:

https://user-images.githubusercontent.com/2602313/233259981-badc28bd-7fbc-4db3-beef-18a01b2f7da1.mp4

**Comment by vlad-hoff** [comment]
Verified on `Pixel 2 XL`, `Pixel 6`, `Pixel 7`, `Galaxy A32 5G` and `Galaxy Tab S8` using version(s):
```
Device/OS: 
- Pixel 2 XL [taimen-user 8.1.0 OPM2.171026.006.H1 release-keys]
- Pixel 6 [oriole-user 13 TQ2A.230505.002 release-keys]
- Pixel 7 [panther_beta-user 14 UPB2.230407.014 release-keys]
- Galaxy A32 5G [a32xsq-user 13 TP1A.220624.014 release-keys]
- Galaxy Tab S8 [gts8wifixx-user 13 TP1A.220624.014 release-keys]
Brave build: 1.53.81
Chromium: 114.0.5735.90 (Official Build) beta (64-bit)
Revision: 386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}
```
---------------------------

**STEPS:**
1. Install Brave > Launch Brave 
2. Run through onboarding
3. Open any website > Tap on the Brave Shields panel
4.  Tap on the `Share` icon > Verify 

**ACTUAL RESULTS:**
- Verified that Brave Shields `Share` button is working fine on Android 8, Android 13 and Android 14

**Android 8**

https://github.com/brave/brave-browser/assets/128532965/bb42015f-fded-45e5-a909-1c5a74721811

**Android 13**

https://github.com/brave/brave-browser/assets/128532965/548f6a53-347d-4642-9c30-9e0635ec1fb8

**Android 14**

https://github.com/brave/brave-browser/assets/128532965/7b79c02e-7e83-41f0-9530-a6dd1c07e92f

**Comment by kjozwiak** [comment]
The above requires `1.52.130` or higher for `1.52.x` verification 👍 QA has verified the PR on `1.53.x` (BETA) as per https://github.com/brave/brave-browser/issues/29856#issuecomment-1577528173.

**Comment by Uni-verse** [comment]
In Progress on `Samsung Galaxy S21 5G` using version:

```
Brave	1.52.130 Chromium: 114.0.5735.198 (Official Build) (32-bit) 
Revision	c3029382d11c5f499e4fc317353a43d411a5ce1c-refs/branch-heads/5735@{#1394}
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
