### ISSUE TITLE
Rename "Extensions" setting to "Extensions (Brave Wallet fallback)", and "None" to "Extensions (no fallback)"

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#29852]
Due to an increase in confusion around Brave Wallet default provider settings with "Extensions" and Brave Wallet fallback behavior, it would be best to revert the "Extensions" setting to "Extensions (Brave Wallet fallback)" and rename "None" to "Extensions (no fallback)"

**Comment by yrliou** [comment]
Assigned to @cypt4

**Comment by yrliou** [comment]
We can probably just update the strings displayed to users.

**Comment by yrliou** [comment]
Screenshot after the PR:
<img width="691" alt="Screen Shot 2023-04-20 at 1 45 39 PM" src="https://user-images.githubusercontent.com/4730197/233483883-19746b3c-facf-4b41-a136-b92e1c82b2dd.png">

**Comment by kjozwiak** [comment]
The above requires `1.50.126` or higher for `1.50.x` verification if @srirambv decides to `QA/Yes` the above.

**Comment by kjozwiak** [comment]
Moving this into `1.51.x` as it looks like we're not going to get another `1.50.x` release.
