### ISSUE TITLE
Crash when dragging a tab group

### ISSUE THREAD

**Issue by wknapik** [brave/brave-browser#29866]
Brave Version: 1.50.119  Chromium: 112.0.5615.121
Operating System: Linux 6.1.21-hardened1-1-hardened

URL (if applicable) where crash occurred: n/a

Can you reproduce this crash? Yes

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Start the browser with a new profile
2. Add the new tab to a new group and name it
3. Open a new tab
4. Drag the tab group to the right

`f1280000-a435-f609-0000-000000000000`
`292f0000-a435-f609-0000-000000000000`

In my main profile this is 100% reproducible and the browser crashes entirely, but it seems in fresh profiles, across channels, this doesn't reproduce as easily and also the browser windows disappear, but some browser processes stick around, have to be killed manually.

https://bravesoftware.slack.com/archives/C01826CM3J9/p1681925022878289

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/292f0000-a435-f609-0000-000000000000

**Comment by bsclifton** [comment]
Couldn't reproduce on Windows - I tried Release (1.50.119) and Nightly (1.52.57)

**Comment by fallaciousreasoning** [comment]
I enabled those flags @wknapik and tested on 1.50.114 and couldn't reproduce. Weirdly, when I dragged the grouped tabs it ungrouped them (no crash though).

Without the flags it still ungroups on drag - maybe it's intentional?

**Comment by bsclifton** [comment]
@fallaciousreasoning can you try updating to 1.50.119? Maybe the latest Chromium bump introduced something?

**Comment by fallaciousreasoning** [comment]
Wow, good find!

**Comment by iefremov** [comment]
@wknapik i guess we really do not guarantee stable work with all combos of upstream flags
