### ISSUE TITLE
Add Portfolio Customizations to Wallet Popup Settings

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#29868]
## Description 

These settings should not be viewable on Wallet Panel until ready.
- Add `Hide balances` setting
- Add `Show graph` setting

![Screenshot 1](https://user-images.githubusercontent.com/40611140/233175063-c6f84234-446c-4bcf-b049-2093439f053c.png)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.52.100 Chromium: 113.0.5672.92 (Official Build) beta (64-bit)
-- | --
Revision | b6f521170062a1fa8a82c33fb223b06fec566da1-refs/branch-heads/5672_63@{#10}
OS | Linux

- Verified steps from  [brave/brave-core#18171](https://github.com/brave/brave-core/pull/18171)
- Verified Hide balance works between page refresh and page navigation
- Verified Hide graph works between page refresh and page navigation
- Verified panel doesn't have any of the two customisation options

https://github.com/brave/brave-browser/assets/17010094/a1801c33-2b68-452a-8359-d06c2747c704


----------------
Verification passed on 

Brave | 1.52.100 Chromium: 113.0.5672.92 (Official Build) beta (64-bit)
-- | --
Revision | b6f521170062a1fa8a82c33fb223b06fec566da1-refs/branch-heads/5672_63@{#10}
OS | Windows 11 Version 22H2 (Build 22621.1702)

- Verified steps from  [brave/brave-core#18171](https://github.com/brave/brave-core/pull/18171)
- Verified Hide balance works between page refresh and page navigation
- Verified Hide graph works between page refresh and page navigation
- Verified panel doesn't have any of the two customisation options

https://github.com/brave/brave-browser/assets/17010094/75d358f0-ba06-48bf-b956-5ebe336f9f9c



----------------
Verification passed on 

Brave | 1.52.100 Chromium: 113.0.5672.92 (Official Build) beta (64-bit)
-- | --
Revision | b6f521170062a1fa8a82c33fb223b06fec566da1-refs/branch-heads/5672_63@{#10}
OS | macOS Version 13.3.1 (a) (Build 22E772610a)

- Verified steps from  [brave/brave-core#18171](https://github.com/brave/brave-core/pull/18171)
- Verified Hide balance works between page refresh and page navigation
- Verified Hide graph works between page refresh and page navigation
- Verified panel doesn't have any of the two customisation options

https://github.com/brave/brave-browser/assets/17010094/9829dbcf-f315-4485-800c-ff1914551813
