### ISSUE TITLE
Remove misplaced Tip buttons on GitHub organization pending invitations page

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#29861]
https://github.com/orgs/{{orgname}}/people/pending_invitations

![image](https://user-images.githubusercontent.com/11497541/233156636-9b70d20e-b879-4f73-8333-2fc90e9060ad.png)

## Solution

Let's just remove the Tip buttons on these pages. Doesn't seem like an appropriate place to have Tip buttons in any case.

**Comment by mkarolin** [comment]
No longer valid as tipping buttons have been removed (https://github.com/brave/brave-browser/issues/34367).
