### ISSUE TITLE
Ads toggle turned on when updated to 0.60.14 

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#2986]
## Description 
When I updated my personal Dev profile from 0.60.13 to 0.60.14, Ads became enabled on 0.60.14. That should not have happened. Ads were off (per UI toggle on 0.60.13) but on 0.60.14 Ads UI toggle switched to on. 

This did not reproduce with a clean profile. Meaning, clean profile with 0.60.13, enable rewards, toggle Ads off. Update to 0.60.14 and Ads toggle was still off.

## Steps to Reproduce

   1. Have a Dev profile with Rewards enabled that you've used for several versions.
   2. Verify Ads toggle is off on 0.60.13.
   3. Update to 0.60.14

## Actual result:
Your Ads toggle may be switched on.
![adstoggle](https://user-images.githubusercontent.com/28145373/51266634-c9e5b800-1989-11e9-90d5-f044948437b8.gif)

## Expected result:
Ads toggle should be off.

## Reproduces how often: 
Unsure, I only have been able to reproduce with my personal profile.

## Brave version (brave://version info)

Brave | 0.60.14 Chromium: 72.0.3626.53 (Official Build) dev(64-bit)
-- | --
Revision | 98434e6cd182d68ce396daa92e9c6310422e6763-refs/branch-heads/3626@{#620}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Dev

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information
cc @jsecretan @ryanml @brave/legacy_qa

**Comment by rebron** [comment]
@LaurenWags @NejcZdovc @jasonrsadler @ryanml is this happening on 59.x?

**Comment by LaurenWags** [comment]
@rebron iirc this didn't happen all the time (@ryanml had a very tough time reproducing).

**Comment by NejcZdovc** [comment]
@rebron @LaurenWags I know what the problem is and I will fix it

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.60.23 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/1416
* Encountered https://github.com/brave/brave-browser/issues/3309 while testing the test plan
