### ISSUE TITLE
Add ability to start Brave Ads in a separate thread

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#29869]

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.53.84 Chromium: 114.0.5735.110 (Official Build) beta (64-bit) 
-- | --
Revision | 1c828682b85bbc70230a48f5e345489ec447373e-refs/branch-heads/5735_90@{#13}
OS | Ubuntu 18.04 LTS



Verified test plan from https://github.com/brave/brave-core/pull/18151

<details>


</details>
