### ISSUE TITLE
Shared Pinned Tabs: popups don't auto-close

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#29865]
## Description 
When a web page opens a popup for sign in / payment confirmation, it doesn't close when a close is requested.

I suspect this is because it's prompting `Close all tabs?` (although it's not visible). The window hangs open

## Steps to Reproduce

   1. Enable brave://flags/#brave-shared-pinned-tabs and restart browser
   2. Load a page that has a popup (ex: sign in with Google, pay with PayPal, etc). A good example is logging into a site like charthop.com using Google
   3. Use the popup to do sign in
   4. Finish w/ the popup (click finish or close)

## Actual result:
It stays open
![image](https://user-images.githubusercontent.com/4733304/233164875-8a82a47d-3082-4311-9543-a385687e3f1a.png)

## Expected result:
It should close

## Reproduces how often: 
100%

## Brave version (brave://version info)
1.52.54 Chromium: 112.0.5615.121 (Official Build) nightly (64-bit) 
This is on Windows 11 (x64) OS Build 22621.1555

## Version/Channel Information:
Nightly

**Comment by sangwoo108** [comment]
It seems it's sorted out. Let me know if it's still reproducible.
