### ISSUE TITLE
After tearing off a tab (Move tab to another window)  in vertical tab minimized mode, unable to move/drop the tab back to original window  

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#29876]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/29692
In vertical tab view minimized mode, after selecting `Move tab to another window` option in context menu, tried to drop back to original window and sometimes I was able to but sometimes nothing happened.  It wasn't a clean move  and and when the tab moved back, partial title was shown.  However, able to move back to original window in expanded mode. 

## Steps to Reproduce

1. Install 1.51.95
2. launch Brave
3. visit abcnews.com
4. enable vertical tabs in brave://flags
5. enable Use vertical tabs in context menu
6. add few more tabs 
7. right click on a tab and select `Move tab to another window` >> New window
8. tried to drag back the tab to original window

## Actual result:

Drag/move back didn't work always in minimized mode. 

https://user-images.githubusercontent.com/98358127/233227568-2f922607-2eb3-4c6f-b204-c4c2f1b0b48e.mp4

## Expected result:
Should be able to move back to original window as in expanded mode

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.51.95 Chromium: 112.0.5615.121 (Official Build) beta (64-bit)
-- | --
Revision | 39cc4e45904ae9f1741c4fbaa866e629c96f2268-refs/branch-heads/5615_51@{#8}
OS | Windows 11 Version 22H2 (Build 22621.1555)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
@rebron @sangwoo108 
 cc: @brave/qa-team

**Comment by sangwoo108** [comment]
It looks like around 50 sec in the video is the problem. This looks like due to the same reason with https://github.com/brave/brave-browser/issues/29836 - close button consumes the event. And again, in this case it's expected behavior.

**Comment by MadhaviSeelam** [comment]
Closing as I am not able to reproduce the issue

https://github.com/brave/brave-browser/assets/98358127/3296c069-7409-4fed-b6b1-23aa782e51df
