### ISSUE TITLE
Disabling safe browsing doesn't work and brave://downloads/ freezes brave

### ISSUE THREAD

**Issue by BartAgterbosch** [brave/brave-browser#29892]
## Description 
Since the latest version, V1.50.119, setting safe browsing to "No protection" under brave://settings/security, no longer does anything, as in it is blocking any executables by default again, which is I assume not its' intended behavior.
And if it is the intended behavior then that's very, very, very annoying (and quite frankly dumb) behavior..
To make matters worse, opening the brave://downloads/ tab now often (not always for some reason) grinds brave to a near halt and it becomes completely unresponsive for a couple of minutes, this is weirdly enough not reflected in cpu or memory usage, which both remain at perfectly normal levels.

It didn't used to do either of these things, as a rough estimate, both these issues didn't exist before the active download ui shifted from being at the bottom of the screen, to the top right download button (which I unfortunately cannot test to make sure at this point, nor check which version that was).

## Reproduces how often: 
Upon every executable file download
About 50/50 when opening the downloads tab

## Brave version (brave://version info)
1.50.119 Chromium: 112.0.5615.121 (Official Build) (64-bit

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No 
- Does the issue resolve itself when disabling Brave Rewards?  No
- Is the issue reproducible on the latest version of Chrome? No

Fyi: Doesn't happen in Chromium or Vivaldi either

**Comment by guij2** [comment]
I'm having this issue as well.

**Comment by khaliewicz** [comment]
This needs fixing. I'm getting blocked downloads constantly.

**Comment by fmarier** [comment]
Looks like the same root cause as https://github.com/brave/brave-browser/issues/28917. There is now a flag to disable these warnings when Safe Browsing is OFF.
