### ISSUE TITLE
PriceHistory Loading State overlaps Wallet Menu

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#29912]
## Description 

PriceHistory Loading State overlaps Wallet Menu

## Steps to Reproduce

   1. Refresh the wallet and open the `Wallet` menu
   2. The PriceHistory loading state overlaps the menu

## Actual result:

https://user-images.githubusercontent.com/40611140/233492048-c49b45b1-8ea2-4119-9697-84897ae3eab7.mov

## Expected result:
Should not overlap the menu

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.52.100 Chromium: 113.0.5672.92 (Official Build) beta (64-bit) 
-- | --
Revision | `b6f521170062a1fa8a82c33fb223b06fec566da1-refs/branch-heads/5672_63@{#10}`
OS | Windows 11 Version 22H2 (Build 22621.1702)

- Verified steps from [brave/brave-core#18176](https://github.com/brave/brave-core/pull/18176)
- Verified price history loading state doesn't overlap on wallet menu

https://github.com/brave/brave-browser/assets/17010094/c61435db-a5e3-475c-8911-b7fc0af49a02
