### ISSUE TITLE
Add four P3A metrics for Playlist (Desktop + Android)

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#29913]
Add four metrics for Playlist:

As a user that used Playlist at least once, when was the last time I used or added content to Brave Playlist? (monthly, regular, only active users)
`Brave.Playlist.LastUsageTime`

1) 0 - 6 days ago (less than a week)
2) 7 - 13 days ago (one week ago or more)
3) 14 - 20 days ago (two weeks ago or more)
4) 21 - 27 days ago (three weeks ago or more)
5) 28 - 59 days ago (four weeks ago or more)
6) 60 days ago or more (two months ago or more)

As a first-time user of Brave Playlist this week, did I return again to use or add content to Brave Playlist during the first 7-day period? (weekly, regular, only active users)
`Brave.Playlist.NewUserReturning`

1) I have used Brave Playlist, but I'm not a first-time Brave Playlist user this week
2) I'm a first-time Brave Playlist user this week but, no, I did not return the rest of the week
3) I'm a first-time Brave Playlist user this week and, yes, I returned and used it again the following day
4) I'm a first-time Brave Playlist user this week and, yes, I returned and used it again this week but not the following day

As a user that used Playlist this week, how many days did I use or add content to Brave Playlist in the past 7 days? (weekly, ephemeral, only active users)
`Brave.Playlist.UsageDaysInWeek`

1) 1 to 2 days
2) 3 to 4 days
3) 5 to 6 days
4) 7 days

As a new user of Playlist this week, how long did it take for new Brave users to use Playlist for the first time? (weekly, ephemeral, only active users)
`Brave.Playlist.FirstTimeOffset`

0) Less than 1 day
1) 1 - 6 days
2) 7 - 13 days 
3) 14 - 20 days 
4) 21 - 27 days 
5) Longer than 27 days

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.52.94`

- Verified the test plan mentioned in the description https://github.com/brave/brave-browser/issues/29913#issue-1677563857

**Comment by GeetaSarvadnya** [comment]
Playlist is tartgeted for the 1.55/1.56 milestone on Desktop as per my discussion with @rebron in slack thread https://bravesoftware.slack.com/archives/CKJCXTP9B/p1683823626553539?thread_ts=1683823503.073009&cid=CKJCXTP9B. Hence removing the Desktop label from the issue.

@DJAndries Please let me know if we need to create follow up issue for Desktop. Thanks!
