### ISSUE TITLE
Tab strip/panel from vertical-tabs' layout flashes on window restore, after switching tab views

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#29917]
## Description 

Tab strip/panel from vertical-tabs' layout flashes on window restore, after switching tab views

## Steps to Reproduce

   1. install `1.52.61`
   2. launch Brave
   3. load a bunch of tabs
   4. context-click on a tab and choose `Use Vertical Tabs`
   5. now, context-click again and deselect `Use Vertical Tabs` to return to the default mode
   6. minimize Brave (but don't shut it down)
   7. restore the window
   8. examine the left panel

## Actual result:

There's a brief flash of the previously vertical-tabs' strip/panel, on window restore.

## Expected result:

No such flash.

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.52.61 Chromium: 112.0.5615.138 (Official Build) nightly (x86_64)
-- | --
Revision | 2258f2fcaeb07bc95c992b7ca47f0b43ead9865c-refs/branch-heads/5615@{#1282}
OS | macOS Version 11.7.6 (Build 20G1231)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

/cc @rebron @sangwoo108 @brave/qa-team

**Comment by stephendonner** [comment]
`Screencast:`

![vertical-tab-ghosting](https://user-images.githubusercontent.com/387249/233517875-8c98fdba-918f-4f4f-b76b-cc3cd8c19b88.gif)

**Comment by sangwoo108** [comment]
Hi, @stephendonner . Is this a Mac specific bug?

**Comment by stephendonner** [comment]
> Hi, @stephendonner . Is this a Mac specific bug?

@sangwoo108 hello!  Appears to be!  Unable to reproduce the issue on `Windows 10`: 

Brave | 1.51.104 Chromium: 112.0.5615.165 (Official Build) beta (64-bit)
-- | --
Revision | c262f36e6b1d711ee42d4fbe1343b49960593f18-refs/branch-heads/5615@{#1297}
OS | Windows 10 Version 22H2 (Build 19045.2846)

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.52.94 Chromium: 113.0.5672.92 (Official Build) beta (x86_64)
-- | --
Revision | b6f521170062a1fa8a82c33fb223b06fec566da1-refs/branch-heads/5672_63@{#10}
OS | macOS Version 11.7.6 (Build 20G1231)

### Steps:
1. installed `1.52.94`
2. launched Brave
3. loaded a bunch of tabs
4. context-clicked on a tab and chose `Use Vertical Tabs`
5. now, context-clicked again and deselected `Use Vertical Tabs` to return to the default mode
6. minimized Brave (but didn't shut it down)
7. restored the window
8. examined the left panel

### Confirmed no tab-panel artifacts switching to and from both vertical and default (horizontal) tab modes

![tab-switch](https://github.com/brave/brave-browser/assets/387249/c3856b34-c845-45ea-9ab7-a75e38385a3d)
