### ISSUE TITLE
Brave crashed when a bookmark was drag/opened from the bookmark bar in vertical tab view

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#29929]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/29692
Brave crashed when I tried to drag a bookmark in vertical tab view

## Steps to Reproduce

   1. Installed 1.51.97
   2. launch Brave
   3. import few bookmarks
   4. enable vertical tab view
   5. drag a bookmark from the bookmarks bar

## Actual result:

Brave crashed
```
cba20000-4b76-f809-0000-000000000000 -BuildUserDefinedReasonArray
```

https://user-images.githubusercontent.com/98358127/233700599-c1ec4b44-06a2-49a3-bf09-cf3bc3f0b2ad.mp4

## Expected result:
Brave should not crash and bookmark should open a new tab similar to horizontal view

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Brave | 1.51.97 Chromium: 112.0.5615.138 (Official Build) beta (64-bit)
-- | --
Revision | 2258f2fcaeb07bc95c992b7ca47f0b43ead9865c-refs/branch-heads/5615@{#1282}
OS | Windows 11 Version 22H2 (Build 22621.1555)

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@rebron @sangwoo108 
cc: @brave/qa-team

**Comment by stephendonner** [comment]
Just reproduced this with <html>

Brave | 1.51.99 Chromium: 112.0.5615.165 (Official Build) beta (64-bit)
-- | --
Revision | c262f36e6b1d711ee42d4fbe1343b49960593f18-refs/branch-heads/5615@{#1297}
OS | Windows 10 Version 22H2 (Build 19045.2846)

Unfortunately, not much of a stacktrace here, either:

```
[ 0 ] 0x7ff9834ebc27
[ 1 ] 0x7ff8f232ca40
[ 2 ] 0x7ff8f22da371
[ 3 ] 0x7ff98349febb
[ 4 ] 0x7ff8f7d8df10
[ 5 ] 0x7ff9834ebc27
```

Hope those offsets help.

Incident link is: https://share.backtrace.io/api/share/bknAfrEmmakEh2Cydx2ZQG1

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.52.87 Chromium: 113.0.5672.77 (Official Build) beta (64-bit)
-- | --
Revision | c4236862955e005c2187105415ac4a2ecf86dff1-refs/branch-heads/5672_62@{#3}
OS | Windows 11 Version 22H2 (Build 22621.1555)
```
1. Installed 1.52.87
2. launched Brave
3. imported few bookmarks 
4. opened few tabs
5. right clicked on a tab to open context menu
6. selected `Use vertical tabs`
7. clicked `Minimize tabs` button to enable `Float on mouseover` mode
8. dragged a bookmark from the bookmarks bar

#### Confirmed no crash happened when bookmark is dragged
#### Confirmed when clicked bookmark, the site opened in a new tab  

![2023-05-05_14h59_33](https://user-images.githubusercontent.com/98358127/236577106-a1890206-c641-4ea5-973b-09f6416dd6d1.gif)

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.52.91 Chromium: 113.0.5672.77 (Official Build) beta (x86_64)
-- | --
Revision | c4236862955e005c2187105415ac4a2ecf86dff1-refs/branch-heads/5672_62@{#3}
OS | macOS Version 11.7.6 (Build 20G1231)

### Steps:
1. installed `1.52.91`
2. launched Brave
3. enabled vertical-tabs view
4. loaded a few sites
5. bookmarked a couple sites
6. attempted to drag and drop both from and to the bookmarks bar

### Confirmed no crash on drag and drop operations with bookmarks and vertical tabs

![no-crash-tabs](https://user-images.githubusercontent.com/387249/236907918-52b7ee07-f299-4df9-b919-9b394abfdce9.gif)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave	1.52.109 Chromium: 114.0.5735.26 (Official Build) beta (64-bit) 
Revision	7075cbb66f0542ac3e01ddfde6b813e7d61118a5-refs/branch-heads/5735@{#454}
OS	Linux
```
Steps: 

1. Installed 1.52.109
2. launched Brave
3. imported few bookmarks 
4. opened few tabs
5. right clicked on a tab to open context menu
6. selected `Use vertical tabs`
7. dragged a bookmark from the bookmarks bar

#### Confirmed no crash happened when bookmark is dragged
#### Confirmed when clicked bookmark, the site opened in a new tab  

https://github.com/brave/brave-browser/assets/98358127/351e3107-4fc3-4d49-9f7e-1b8df20f42d2
