### ISSUE TITLE
Resurrect context menu to switching tab strip orientation

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#29939]
<img width="296" alt="image" src="https://user-images.githubusercontent.com/5474642/233754511-cddab7d7-6d15-463f-843e-ed5fd1c620ae.png">

As per the latest design, we should leave "Use vertical tabs" context menu.

**Comment by kjozwiak** [comment]
The above requires `1.51.106` or higher for `1.51.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.51.106 Chromium: 113.0.5672.53 (Official Build) (64-bit)
-- | --
Revision | 12f5dac35d12e8f4e72d7dd11df557ef93bc046f-refs/branch-heads/5672@{#703}
OS | Windows 11 Version 22H2 (Build 22621.1555)
```

1. Installed 1.51.106
2. launch Brave
3. opened `brave://flags`
4. enabled `#brave-vertical-tabs`
5. opened a new tab and right clicked to open context menu
6. selected `Use vertical tabs` 

- Confirmed Vertical tabs view is shown in expanded mode as default as expected
- Confirmed all three modes Float on mouseover, Expanded and Minimized mode working as expected
- Confirmed horizontal tab view shown when unselected `Use vertical tabs` in the context menu

example | example | example | example
----- | ----- | ----- | -------
<image width ="500" alt = "image" src="https://user-images.githubusercontent.com/98358127/234931162-bbbcda4e-818a-489c-bfef-65ba2f090dc9.png">|<image width ="500" alt = "image" src="https://user-images.githubusercontent.com/98358127/234931464-d16c55eb-5778-4ec6-a114-49cac6318dc1.png">|<image width ="500" alt = "image" src="https://user-images.githubusercontent.com/98358127/234931627-ad676442-d3a0-461f-8c28-2a1408035ed4.png">|<image width ="700" alt = "image" src="https://user-images.githubusercontent.com/98358127/234933238-54364e7b-e9e5-4dff-9d8d-91a981b9616b.png">

Float on mouseover| Expanded | Minimized 
----- | ----- | ----- 
<image width ="600" alt = "image" src="https://user-images.githubusercontent.com/98358127/234932690-41451af8-4805-4530-9c7f-1ae41e8e5478.png">|<image width ="600" alt = "image" src="https://user-images.githubusercontent.com/98358127/234932742-babd1bc5-cd77-42f2-8dd7-cc0db631aa18.png">|<image width ="100" alt = "image" src="https://user-images.githubusercontent.com/98358127/234932886-7e4eb6fe-d94b-4609-8c63-325142d914b1.png">
