### ISSUE TITLE
Vertical tab strip doesn't expand on Windows / And tabs are wider than it should be

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#29937]
## Description 

Original report: https://github.com/brave/brave-browser/issues/24717#issuecomment-1490862226
Reporter: @Emi-TheDhamphirInLoveUnderTheFrozenStar

## Steps to Reproduce

In Windows - 1.52.5 Chromium: 112.0.5615.49 (Official Build) nightly (64-bit).

This is what happens when you attach/re-attach tabs from another window. The issue happens on both collapsed (which I usually use) and float mode.

![2023-03-30_13-28-34](https://user-images.githubusercontent.com/122518587/228944812-b1d4d832-07f3-49d5-9ce1-560df6bb85e3.gif)

As you can see, it displays some of the title of the tab,

![2023-03-30_13-44-23](https://user-images.githubusercontent.com/122518587/228947464-3fb1f995-35c6-42ea-92d9-7f4273932043.gif)

## Actual result:
Reattaching should expand the vertical tab strip

reference: screen recording in https://github.com/brave/brave-core/pull/17690

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by sangwoo108** [comment]
@MadhaviSeelam Could you help me with finding out steps-to-reproduce for this? I think I've seen this before but not sure how it could be reproduced.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.52.87 Chromium: 113.0.5672.77 (Official Build) beta (64-bit)
-- | --
Revision | c4236862955e005c2187105415ac4a2ecf86dff1-refs/branch-heads/5672_62@{#3}
OS | Windows 11 Version 22H2 (Build 22621.1555)
```

1. Installed 1.52.87
2. launched Brave
3. opened few tabs
4. right clicked on a tab to open context menu
5. selected `Use vertical tabs`
6. clicked `Minimize tabs` button to enable `Float on mouseover` mode
7. pressed down a tab before the vertical tab strip is expanded before releasing the mouse
8. drag a tab to another window and drop

#### Confirmed tabs are as wide as vertical tab panel
#### Confirmed when dragging a tab into another window and drop, the tab strip stayed open if mouse is over tab strip.

<image width = "450" alt="image" src="https://user-images.githubusercontent.com/98358127/236567102-18582e05-d545-43cb-a3c9-4397d1f79764.png">

https://user-images.githubusercontent.com/98358127/236567185-614631f5-10a9-4766-b2bf-16cb2a7e0cf1.mp4>
