### ISSUE TITLE
Vertical tabs sometimes lose their whole tab-panel content until next reopen/reflow/repaint

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#29941]
## Description 

Vertical tabs sometimes lose their whole tab-panel content until next reopen/reflow/repaint

## Steps to Reproduce

1. install `1.52.65`
2. launch Brave
3. click to check `Use vertical tabs` in `brave://settings/appearance`
4. `command` / `ctrl` + `T` a bunch of times to open new tabs
5. load a website, any new or existing one
6. mouse-over the left tab panel to see the site favicons and page titles
7. load any website
8. hover back over the left panel, click on any new tab
9. load any website
10. keep repeating (variants) of `steps 4-10` until you see...(or don't see, as the case might be)

### Here are three instances of it occurring:

screenshot 1 | screenshot 2 | screenshot 3 | screencast
------------|-----------|----------|------------
<img width="1312" alt="Screenshot 2023-04-21 at 10 10 58 PM" src="https://user-images.githubusercontent.com/387249/233765452-98ac21f2-5191-461c-a852-93099f397afc.png"> | <img width="1125" alt="Screenshot 2023-04-21 at 10 36 18 PM" src="https://user-images.githubusercontent.com/387249/233765453-dbe35509-9dae-4887-a3da-b3c83e502ba5.png"> | <img width="1125" alt="Screenshot 2023-04-21 at 10 36 26 PM" src="https://user-images.githubusercontent.com/387249/233765454-d812bf2b-7faf-48ad-9968-d5c8d42d9cde.png"> | `COMING SOON!!!`

Intermittently, there's a tab blankening, which auto-fixes on next repaint

## Expected Results:

No flash of missing tab-pane content

<img width="1920" alt="Screenshot 2023-04-21 at 11 01 13 PM" src="https://user-images.githubusercontent.com/387249/233765772-8fddead3-27a9-4fb2-8149-ba331abc6d66.png">

## Reproduces how often: 

100% (eventually, within a few minutes, if these steps are all you do, repeatedly)

## Brave version (brave://version info)

Brave | 1.52.65 Chromium: 113.0.5672.53 (Official Build) nightly (x86_64)
-- | --
Revision | 12f5dac35d12e8f4e72d7dd11df557ef93bc046f-refs/branch-heads/5672@{#703}
OS | macOS Version 13.4 (Build 22F5037d)

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

/cc @sangwoo108 @rebron @brave/qa-team @bsclifton @jonathansampson @brave/user-support-team

**Comment by sangwoo108** [comment]
Okay, I think I found a 100% steps-to-reproduce. 

* Press down a tab before the vertical tab strip is expanded and don't release the mouse

**Comment by stephendonner** [comment]
> Okay, I think I found a 100% steps-to-reproduce.
> 
> * Press down a tab before the vertical tab strip is expanded and don't release the mouse

Sorry, realized I never did finally attach a screencast; looks like you nailed it without it :-)

**Comment by stephendonner** [comment]
> Okay, I think I found a 100% steps-to-reproduce.
> 
> * Press down a tab before the vertical tab strip is expanded and don't release the mouse

Nice catch; can confirm 100% using 

Brave | 1.51.110 Chromium: 113.0.5672.77 (Official Build) (x86_64)
-- | --
Revision | c4236862955e005c2187105415ac4a2ecf86dff1-refs/branch-heads/5672_62@{#3}
OS | macOS Version 11.7.6 (Build 20G1231)

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.52.86 Chromium: 113.0.5672.77 (Official Build) beta (x86_64)
-- | --
Revision | c4236862955e005c2187105415ac4a2ecf86dff1-refs/branch-heads/5672_62@{#3}
OS | macOS Version 11.7.6 (Build 20G1231)

Followed my original steps to reproduce, as well as the 100% reproducible step mentioned in https://github.com/brave/brave-browser/issues/29941#issuecomment-1519281018

### Confirmed tab-strip contents (favicons, titles) were left intact

`1.52.86` | `1.51.110`
----------|----------
. | 
![1-53-100](https://user-images.githubusercontent.com/387249/236232404-39c10192-495a-4cde-abf5-83f210d62809.gif)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.52.87 Chromium: 113.0.5672.77 (Official Build) beta (64-bit)
-- | --
Revision | c4236862955e005c2187105415ac4a2ecf86dff1-refs/branch-heads/5672_62@{#3}
OS | Windows 11 Version 22H2 (Build 22621.1555)
```

1. Installed 1.52.87
2. launched Brave
3. opened few tabs
4. right clicked on a tab to open context menu
5. selected `Use vertical tabs`
6. clicked `Minimize tabs` button to enable `Float on mouseover` mode
7. pressed down a tab before the vertical tab strip is expanded and before releasing the mouse

#### Confirmed vertical tab panel contents (favicons, titles) were left intact


1.51.110 | 1.52.87
------- | --------
![image](https://user-images.githubusercontent.com/98358127/236571724-00e28564-16a6-4f98-a54b-90a1d605e4ea.png)| ![2023-05-05_14h23_08](https://user-images.githubusercontent.com/98358127/236572204-3cd511d7-b22c-4fe6-9215-1b3657dfa7a6.gif)

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave	1.52.109 Chromium: 114.0.5735.26 (Official Build) beta (64-bit) 
Revision	7075cbb66f0542ac3e01ddfde6b813e7d61118a5-refs/branch-heads/5735@{#454}
OS	Linux
```

1. Installed 1.52.87
2. launched Brave
3. opened few tabs
4. right clicked on a tab to open context menu
5. selected `Use vertical tabs`
6. clicked `Minimize tabs` button to enable `Float on mouseover` mode
7. pressed down a tab before the vertical tab strip is expanded and before releasing the mouse

#### Confirmed vertical tab panel contents (favicons, titles) were left intact


1.51.110 | 1.52.87
------- | --------
