### ISSUE TITLE
Installing both Release and Beta through Google Play makes one version not update at all.

### ISSUE THREAD

**Issue by DKB-91** [brave/brave-browser#29942]
## Description 

After installing Beta, the Release version won't update anymore and copies the last time Beta was updated, but the release version is two versions behind. (With both two critical security issues still active)

## Steps to reproduce 

   1. Install Brave Browser
   2. Install later Brave Browser - Beta
   3. Update Brave Browser - Beta

## Actual result 

Brave Browser (Release) doesn't update and Google Play thinks it's updated at the same time as the Beta version.
Despite being still the April 5th release.

(Release)
-![Screenshot_20230422-194319_Brave.jpg](https://user-images.githubusercontent.com/124310619/233799060-7c9da1de-5d7c-485d-bf6d-23a5985be95d.jpg)

(Beta)
![Screenshot_20230422-194331_Brave - Beta.jpg](https://user-images.githubusercontent.com/124310619/233799131-da38ba84-5c00-4655-b578-81df08831b3a.jpg)

Disinstalling the Beta version does not make Google Play find the new Release update, and reinstalling the Beta changes nothing.

## Expected result

Both version should be updated with their security fixes and new features applied.

## Issue reproduces how often 

Only this month.

## Version/Channel Information:

Release version.

- Can you reproduce this issue with the current Play Store version? 

Yes

- Can you reproduce this issue with the current Play Store Beta version? 

Yes

- Can you reproduce this issue with the current Play Store Nightly version?

No, haven't installed.

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
Arm v8a
Phone (Samsung A70)
Android 11

## Brave version

Release version
1.50.114

Beta version
1.51.97

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

Apps installed through Google Play. (Release version almost a year ago, Beta this year)

**Comment by welkinpc-91** [comment]
Forgot to upload this:

![Screenshot_20230422-194352_Google Play Store.jpg](https://user-images.githubusercontent.com/124310619/233799372-3cefbc0b-9ce3-4731-94df-dee1aa71ab9c.jpg)

For non-Italian readers, it says 3 days ago...but as you can see, the releass version is two updates behind.
