### ISSUE TITLE
Add tests to detect the kind of issues we had on v1.50.121 on Linux

### ISSUE THREAD

**Issue by wknapik** [brave/brave-browser#29957]
We made a new stable release with tabs crashing immediately on open on Linux systems. This was painful for end users and for us. Let's catch these sorts of issues in CI.

The suspected problem is [this freetype issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1434194). If so it would depend on the particular site and the fonts it uses. Most reports were on Arch, Gentoo, and Fedora. We test on Debian, so different system fonts might explain why ci tests didn't flag this before release, or we just didn't have coverage. All this is speculation though.

## Steps

- [x] Look at crash reports/otherwise debug to confirm the cause
- [x] Write a regression test.

Maybe we could load snapshots of some major websites as a smoke test. Reproduction reports mentioned brave.com, github.com (probably with a login cookie), and https://tailwindcss.com/docs/vertical-align.

See internal discussion https://bravesoftware.slack.com/archives/C04PX1BUN/p1682350161448199?thread_ts=1681933501.320839&cid=C04PX1BUN

**Comment by rillian** [comment]
Based on discussion, we can focus this on a browser or unit regression test for the specific crash.

**Comment by rillian** [comment]
I wasn't able to reproduce with a local dev build from the `v1.50.121` tag. Trying a release build next.

**Comment by rillian** [comment]
Crash reports have no symbols. Perhaps that's not surprising if a `sigill` means the stack is completely smashed. I don't have enough ram to link a release build, but it should be possible to use the published symbols from the official package.

Here's a minimal reproduction from bisecting the brave.com landing page against our official rpm release build.

```html
<select style="font-family: Noto Sans;">
  <option>crash me</option>
</select>
```
Note that this depends on the particular version of Noto Sans available as a system font on my Fedora Linux 37 system. If I replace it with an `@import` for the fonts.google.com version, it renders without error.

Since it's requires both a specific font and the `<select>` environment, the freetype crash is the still the likely culprit.

**Comment by rillian** [comment]
This seems to be `NotoSans-VF.ttf` version 2.008 (2021) from google-noto-sans-vf-fonts-20201206^1.git0c78c8329-7.fc37.noarch.

**Comment by rillian** [comment]
[Here](https://gist.github.com/rillian/297a44bf1695d2603bc014791bd43ee2) is an 8k reproduction, although I haven't confirmed it's actually using the data url.

**Comment by rillian** [comment]
My example above had a CSS typo and was falling back to the system font. Having fixed that it looks like none of my minimisation attempts worked, so I'm back to a 844k test file.

**Comment by rillian** [comment]
Unfortunately my regression test isn't triggering in ci. Rebasing on `v1.50.121` I see
```
> /home/ubuntu/workspace/pr-brave-browser-freetype-regression-1.50.121-linux-x64/src/out/Static/brave_browser_tests --enable-logging=stderr --v=0 --test-launcher-jobs=4 --use_goma --target_arch=x64 --target_os=linux --output=brave_browser_tests.xml --gtest_output=xml:brave_browser_tests.xml
[...]
[2023-05-01T20:50:46.431Z] [894/1228] FontBrowserTest.FreetypeRegression (781 ms)
[...]
[2023-05-01T20:53:01.613Z] SUCCESS: all tests passed.
```

Are these debug builds? I also can't reproduce with a local debug build, but loading the test case the the brave 1.50.121 release crashes the tab.
