### ISSUE TITLE
Move Account Actions into a Popup Menu

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#29954]
## Description 

We need to move the `Account` actions into a `Popup` menu

Current:

![Screenshot 10](https://user-images.githubusercontent.com/40611140/234035174-3fa8240c-d2b8-4664-a374-e77df66109bb.png)

Needs to be:

![Screenshot 11](https://user-images.githubusercontent.com/40611140/234035509-45aa3c5c-9902-4d90-b0f3-04c482494eed.png)

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.52.94 Chromium: 113.0.5672.92 (Official Build) beta (64-bit) 
-- | --
Revision | `0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}`
OS | Linux

- Verified steps from [brave/brave-core#18218](https://github.com/brave/brave-core/pull/18218)
- Verified account actions is moved inside a popup window
- Verified all account actions work as expected

https://github.com/brave/brave-browser/assets/17010094/1600f9a6-a558-4191-998b-ca02ed32c39b

---------------------

**Verification passed on**

Brave | 1.52.94 Chromium: 113.0.5672.92 (Official Build) beta (64-bit)
-- | --
Revision | `0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

- Verified steps from [brave/brave-core#18218](https://github.com/brave/brave-core/pull/18218)
- Verified account actions is moved inside a popup window
- Verified all account actions work as expected

https://github.com/brave/brave-browser/assets/17010094/3cb819f6-89a7-4ccc-9503-db63fb307ff8

---------------------

**Verification passed on**

Brave | 1.52.94 Chromium: 113.0.5672.92 (Official Build) beta (arm64)
-- | --
Revision | `0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#18218](https://github.com/brave/brave-core/pull/18218)
- Verified account actions is moved inside a popup window
- Verified all account actions work as expected

https://github.com/brave/brave-browser/assets/17010094/0510b086-bacb-46f3-95f4-7df7e2045a93
