### ISSUE TITLE
When Brave is closed and relaunched, a crash report is generated

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#29961]
## Description 

After a new install/new profile, closed and relaunch browser and navigated to brave://crashes.  Page shows 2 new crashes.  Found while verifying `brave://crash`, `brave://gpucrash` tests for `Cr 113 manual pass`- https://github.com/brave/brave-browser/issues/29930 in Win 11 x64.  Hence, verified without `brave://crash` and `brave://gpucrash` and found crash reports are generated with close and relaunch of the browser.   This behavior is not shown in current release or previous nightly build before this version (`Nightly v1.52.64 (Chromium 112.0.5615.165`)

## Steps to Reproduce

   1. Install 1.52.69
   2. launch Brave
   3. Skip>>Skip>>Finish
   4. close and relaunch Brave Browser
   5. open brave://crashes
   6. click Send now

## Actual result:

Page shows two reports 
```
Status: | Uploaded
-- | --
Uploaded Crash Report ID: | ead90400-4b76-f809-0000-000000000000
Upload Time: | Monday, April 24, 2023 at 1:47:18 PM
```

```
[ 0 ] crash_reporter::DumpWithoutCrashing() ( crashpad.cc:274 )
[ 1 ] _tailMerge_esent.dll
[ 2 ] malloc ( allocator_shim_override_ucrt_symbols_win.h:71 )
[ 3 ] memset ( memset.asm:491 )
[ 4 ] crash_reporter::DumpWithoutCrashing() ( crashpad.cc:274 )
[ 5 ] DependencyManager::AddComponent(KeyedServiceBaseFactory *) ( dependency_manager.cc:56 )
```

![image](https://user-images.githubusercontent.com/98358127/234114383-bcc18cc4-f93a-4531-aecf-5ee43eb430be.png)

## Expected result:

No crash reports should be generated

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.52.69 Chromium: 113.0.5672.53 (Official Build) nightly (64-bit)
-- | --
Revision | 12f5dac35d12e8f4e72d7dd11df557ef93bc046f-refs/branch-heads/5672@{#703}
OS | Windows 11 Version 22H2 (Build 22621.1555)
```
## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
@Max 
cc: @rebron @brave/qa-team

**Comment by kjozwiak** [comment]
The above requires `1.51.106` or higher for `1.51.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.51.106 Chromium: 113.0.5672.53 (Official Build) (64-bit)
-- | --
Revision | 12f5dac35d12e8f4e72d7dd11df557ef93bc046f-refs/branch-heads/5672@{#703}
OS | Windows 11 Version 22H2 (Build 22621.1555)
```


Verified with original STR from  https://github.com/brave/brave-browser/issues/29961#issue-1682031834

- Confirmed no crash reports shown in brave://crashes after closing and relaunching Brave
- Confirmed when brave crashed with brave://crash and brave://gpucrash, brave://crashes page shows only two crash reports 

ex|ex
---|---
<image width="500" alt="image" src="https://user-images.githubusercontent.com/98358127/234927649-d33c9e78-f98f-4113-b849-1c9317a9ae7c.png">|<image width="500" alt="image" src="https://user-images.githubusercontent.com/98358127/234928109-fb65ee27-50ea-4a9f-8894-59e80815900b.png">
