### ISSUE TITLE
HelpBubbleView's secondary button text is not visible

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#29964]
## Description 

~~Hide the `Make Brave faster` popup modal~~
Original issue description is updated.
See https://github.com/brave/brave-browser/issues/29964#issuecomment-2133350589 

## Steps to Reproduce

   1. Launch brave with clean profile and open more than 12 tabs
   2. Check bubble's button text is visible
 

## Actual result:

![image](https://user-images.githubusercontent.com/38657976/234168790-252b7358-30a6-4e1e-883d-21c9b661e2ed.png)

## Expected result:
Hide the `Make Brave faster` popup modal

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.52.68 Chromium: 113.0.5672.53 (Official Build) nightly (64-bit)
-- | --
Revision | 12f5dac35d12e8f4e72d7dd11df557ef93bc046f-refs/branch-heads/5672@{#703}
OS | Windows 10 Version 21H2 (Build 19044.2846)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @rebron @mkarolin

**Comment by GeetaSarvadnya** [comment]
Chrome popup modal
![image](https://user-images.githubusercontent.com/38657976/234514976-82578e29-9a7d-4c11-b1ba-5e3f7f244fbd.png)

**Comment by stephendonner** [comment]
Just for easier reproducibility when verifying, if you open 12 or more tabs, you'll see the above.

**Comment by srirambv** [comment]
Probably need to make sure the below is also removed/hidden if we decide to hide the original 

![image](https://user-images.githubusercontent.com/17010094/235062019-4160d474-ccfb-4835-a725-3ca7fa99ce4b.png)

**Comment by GeetaSarvadnya** [comment]
cc: @aguscruiz

**Comment by aguscruiz** [comment]
This one should use our default style for dialogs
https://www.figma.com/design/H11ZOl6JMYbCTW4ZJXqR5V/%F0%9F%A6%81-Browser?node-id=6697-27337&t=B9Uj4dHnKD9GZsuA-1

**Comment by aguscruiz** [comment]
General issue here:
https://github.com/brave/brave-browser/issues/38603

**Comment by emerick** [comment]
This issue wasn't totally clear to me. The description says we should hide the bubble, but then later it sounds like we're talking about updating the fonts/colors.

**Comment by stephendonner** [comment]
> This issue wasn't totally clear to me. The description says we should hide the bubble, but then later it sounds like we're talking about updating the fonts/colors.

@rebron we decided on keeping this feature/dialog, right?  If so, this issue is about updating the dialog, then?

**Comment by simonhong** [comment]
Looking. I think the background color should be cleared. Blue background is not aligned with our new button style.

**Comment by kjozwiak** [comment]
The above requires `1.67.101` or higher for `1.67.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.67.101 Chromium: 126.0.6478.26 (Official Build) beta (64-bit)
-- | --
Revision | a561f4b53cdb831888e5cd702d2b8f9598c00f50
OS | Windows 11 Version 23H2 (Build 22631.3672)
```

1. Installed 1.67.101
2. launched Brave
3. opened 12 tabs

Confirmed `Turn on` and `No thanks` button text is visible  

Light | Dark
---- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/f1bfe58d-604f-40b8-ba77-5f2eb604e234)|![image](https://github.com/brave/brave-browser/assets/98358127/b1c8b197-d94f-4108-a03e-29ba67d920ab)
