### ISSUE TITLE
Surface script blocking shortcuts to "Allow once", fix scripts functionality, focus indicators, and scroll

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#2996]
## Description
- Make script blocking shortcuts to "Allow once" as easy to access as Muon (legacy). Previously it took 2 clicks in Muon: 
[noscript.mov.zip](https://github.com/brave/brave-browser/files/2766578/noscript.mov.zip)
The current design takes 3 clicks:
   1. Click on the shields icon
   2. Click on the scripts dropdown
   3. Click "Allow all" link
- Fix functionality in scripts detail view so that users can allow/block all sources of Javascript or select individual sources to allow/block
- Enable scrolling on the detailed view 
- Fix focus indicators

## Designs 
![shields scripts breakdown](https://user-images.githubusercontent.com/2388823/53041139-0e0c2280-3438-11e9-8de5-d3c59cf0fab4.png)

When looking at the scripts detail view, we should enable horizontal scrolling so that someone can see the full FQDN. 
![registered domain explanation](https://user-images.githubusercontent.com/2388823/53041460-e9fd1100-3438-11e9-92a9-d727bdcca1ba.jpg)
If it's longer than the content area, the additional text to the left of the registered domain (ETLD+1) is initially truncated as an ellipses. In this new design, we do not show the path or "https://" at all. Only the full FQDN or (...)(registered domain) is shown.

![scroll behavior](https://user-images.githubusercontent.com/2388823/52826754-113d9200-3077-11e9-89b9-5c7b24f90632.png)

All interactive UI elements in the scripts detail view should have keyboard support and the appropriate focus treatment.
![scripts focus states](https://user-images.githubusercontent.com/2388823/52826761-169adc80-3077-11e9-85ce-6db829d42b2c.png)

The interface should accommodate long strings when translated. For example, the strings in the Shields panel translated to Russian should wrap like this:
![long string](https://user-images.githubusercontent.com/2388823/52826771-1b5f9080-3077-11e9-9362-406eac5bf351.png)

Grab the SVG assets from this ZIP folder:
[icons.zip](https://github.com/brave/brave-browser/files/3104450/icons.zip)

For more CSS and plain text, check Abstract link: https://share.goabstract.com/68d70c4d-8c77-4588-9ee5-ce6418505c79

## Theme Update
Since we enabled light/dark theme switching in a quick fix, here is the updated color theming for your reference:
![shields theme update](https://user-images.githubusercontent.com/2388823/56699461-5c44d880-66aa-11e9-9c48-27fc5ee73966.png)
Abstract link: https://share.goabstract.com/bb5e3286-b046-4276-9651-37768069932e

**Comment by karenkliu** [comment]
Added dash.svg to the zipped folder per Cezar's feedback.

**Comment by cezaraugusto** [comment]
@karenkliu could you please take a look at this and check what items remain missing? It would be best if we can split them into multiple smaller issues.

**Comment by cezaraugusto** [comment]
At a quick glance, it seems only full FQDN display is missing, but I can be possibly wrong.

**Comment by cezaraugusto** [comment]
FQDN was split from here a while ago https://github.com/brave/brave-browser/issues/4574. I did a new check and it does seem it's the only item left. I'm going to close this one for now but please re-open if I'm mistaken.
