### ISSUE TITLE
min custom tip amount message needs to be shown on the tipping banner when user enter `0.01` BAT

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#29973]
## Description 

min custom tip amount message needs to be shown on the tipping banner when user enter `0.01` BAT
## Steps to Reproduce

   1. Clean profile 1.52.x
   2. Enable rewards and connect to a external custodian
   3. Open a verified pubs laurenwags.github.io
   4. Open the BR panel and click on the `Send Contributions` 
   5. Click on the `Custom` and enter the tip amount as `0.01` BAT
   6. `Send` button gets activated but click on send doesn't send custom tip to pubs also there is no error message for not sending the custom tip

## Actual result:

`Send` button gets activated but click on send doesn't send custom tip to pubs, also there is no error message for not sending the custom tip
## Expected result:
min custom tip contribution message needs to be shown on the tipping banner

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.52.69 Chromium: 113.0.5672.53 (Official Build) nightly (64-bit)
-- | --
Revision | 12f5dac35d12e8f4e72d7dd11df557ef93bc046f-refs/branch-heads/5672@{#703}
OS | Windows 10 Version 21H2 (Build 19044.2846)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? NA

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @zenparsing @Miyayes @brave/qa-team

**Comment by kjozwiak** [comment]
The above requires `1.52.92` or higher for `1.52.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.52.102 Chromium: 113.0.5672.126 (Official Build) beta (64-bit)
-- | --
Revision | c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}
OS | Windows 10 Version 21H2 (Build 19044.2965)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/18256
1. Confirmed that, if user tried to sent one-time tip/monthly custom tip amount `less than 0.25 BAT` then the `Send` button in the tipping banner is NOT activated
3. Confirmed that the `Send` button gets activated only when the custom tip amount is `greater than or equals to 0.25 BAT`
4. Confirmed that when user tries to send custom tip amounts like `0.26 BAT` or `0.27 BAT` or `0.28 BAT` or `0.29 BAT` or `0.30 BAT` or `0.31  BAT` etc... then the custom tip values is rounded down to `0.25 BAT` when focus leaves the input.

**`custom tip amount < 0.25 BAT`** | **`custom tip amount >= 0.25 BAT`** 
----------------------------------------|-----------------------------------------
![image](https://github.com/brave/brave-browser/assets/38657976/4e840fc7-7660-4a9c-b837-5e35958e50f6) | ![image](https://github.com/brave/brave-browser/assets/38657976/dab4b6b9-2211-4199-8a17-68d29ea5f15a)
