### ISSUE TITLE
Estimated earnings data shows blank in the BR panel upon upgrade

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#29978]
## Description 

Found this issue while verifying manual test run https://github.com/brave/brave-browser/issues/29930 ads testcases. Have a profile which has 3 ads and the estimated earnings show 0.135 in the rewards panel when I launched with 1.50.x.  Upgraded to 1.52.x.   Ads received correctly shows 3 in the brave://rewards page and Ads history in shows correct count but `Estimated Earnings` show blank

## Steps to Reproduce

   1.  Install 1.50.x 
   2. launch Brave with ads data (3 ads shown) in the BR panel
   3. upgrade to 1.52.69

   
## Actual result:

 `Estimated ads earnings` field shows blank (0.000 BAT)
 
 1.50.x | 1.52.x
 -- | ----
<image width ="600" alt="image" src="https://user-images.githubusercontent.com/98358127/234345610-a8421c26-9ec5-464c-9fc7-b159819e5823.png">|<image width ="600" alt="image" src="https://user-images.githubusercontent.com/98358127/234345833-f73f9aa4-e4bd-4d57-aa0f-7539f83c34d2.png">

 

## Expected result:
Correct amount should be displayed (i.e. before upgrade amount 0.135 BAT)

## Brave version (brave://version info)

```
Brave | 1.52.69 Chromium: 113.0.5672.53 (Official Build) nightly (64-bit)
-- | --
Revision | 12f5dac35d12e8f4e72d7dd11df557ef93bc046f-refs/branch-heads/5672@{#703}
OS | Windows 11 Version 22H2 (Build 22621.1555)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel?  No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
 @tmancey 
cc: @rebron  @brave/qa-team

**Comment by MadhaviSeelam** [comment]
@btlechowski @GeetaSarvadnya Thanks for double checking this issue.  Please feel free to add any relevant notes.

**Comment by btlechowski** [comment]
This is a regression in 1.52.x. Not reproducible in 1.51.x. Probably due to https://github.com/brave/brave-browser/issues/21238

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.52.76 Chromium: 113.0.5672.53 (Official Build) nightly (64-bit)
-- | --
Revision | 12f5dac35d12e8f4e72d7dd11df557ef93bc046f-refs/branch-heads/5672@{#703}
OS | Windows 11 Version 22H2 (Build 22621.1555)
```
Verified with original STR https://github.com/brave/brave-browser/issues/29978#issue-1683516696

Confirmed Estimated earnings data is not lost after upgrade and is showing correct amount i.e. same as before upgrade `0.135 BAT`

1.50.121 | 1.52.76
--- | ---
<image width="600" alt="image" src="https://user-images.githubusercontent.com/98358127/234634605-b86a4029-5c47-421f-bff3-de1729e4200d.png">|<image width="600" alt="image" src="https://user-images.githubusercontent.com/98358127/234634651-e85bf16e-6736-4791-bb3c-003804a95456.png">

**Comment by kjozwiak** [comment]
> Verification `PASSED` using
> 
> ```
> Brave | 1.52.76 Chromium: 113.0.5672.53 (Official Build) nightly (64-bit)
> -- | --
> Revision | 12f5dac35d12e8f4e72d7dd11df557ef93bc046f-refs/branch-heads/5672@{#703}
> OS | Windows 11 Version 22H2 (Build 22621.1555)
> ```
> 
> Verified with original STR [#29978 (comment)](https://github.com/brave/brave-browser/issues/29978#issue-1683516696)
> 
> Confirmed Estimated earnings data is not lost after upgrade and is showing correct amount i.e. same as before upgrade `0.135 BAT`
> 
> 1.50.121	1.52.76
> <img alt="image" width="600" src="https://user-images.githubusercontent.com/98358127/234634605-b86a4029-5c47-421f-bff3-de1729e4200d.png">	<img alt="image" width="600" src="https://user-images.githubusercontent.com/98358127/234634651-e85bf16e-6736-4791-bb3c-003804a95456.png">

Thanks for running through the above @MadhaviSeelam 👍 Unblocks channel migrations.

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21 5G` using the following version(s):

```
Brave	1.52.102 Chromium: 113.0.5672.126 (Official Build) beta (64-bit) 
Revision	c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
Using STR in https://github.com/brave/brave-browser/issues/29978#issue-1683516696

- Verified `Estimated earnings` data is retained when upgrading from `1.50.106` -> `1.52.102.`
- Verified  Ads are shown and `Estimated earnings` is updated when ads are shown after upgrading from `1.50.106.`

1.50.106 | 1.52.102 | 1.52.102 (Ad)
-|-|-
![screenshot-1684766393471](https://github.com/brave/brave-browser/assets/17885425/3bd24b34-ca15-4a61-94df-083644a802dc) | ![screenshot-1684766621304](https://github.com/brave/brave-browser/assets/17885425/bdf40301-fa3d-4359-8ffe-e53e6eeb5592) | ![screenshot-1684766671205](https://github.com/brave/brave-browser/assets/17885425/5bbf484c-d41a-48d2-8b35-6c2da0538d46)

**Comment by stephendonner** [comment]
## Verification `PASSED` using 

Brave | 1.52.108 Chromium: 114.0.5735.26 (Official Build) beta (x86_64)
-- | --
Revision | 7075cbb66f0542ac3e01ddfde6b813e7d61118a5-refs/branch-heads/5735@{#454}
OS | macOS Version 11.7.7 (Build 20G1345)

Followed the original steps to reproduce from https://github.com/brave/brave-browser/issues/29978#issue-1683516696

### Confirmed `Estimated Earnings` is populated with its value retained, when upgrading

example | example | example
---------|----------|--------
<img width="1312" alt="Screen Shot 2023-05-22 at 5 42 14 PM" src="https://github.com/brave/brave-browser/assets/387249/718c87d0-f813-472a-a50a-8ffe2d32ddf3"> | <img width="1312" alt="Screen Shot 2023-05-22 at 5 44 06 PM" src="https://github.com/brave/brave-browser/assets/387249/9bf4e329-146b-4737-b86c-299d1c81ffe7"> | <img width="1312" alt="Screen Shot 2023-05-22 at 5 44 28 PM" src="https://github.com/brave/brave-browser/assets/387249/8785e45b-cae9-49fd-800e-5942e9df8e92">

**Comment by vlad-hoff** [comment]
Verified on `Galaxy Tab S8` using version(s):
```
Device/OS: SM-X700 Galaxy Tab S8 [gts8wifixx-user 13 TP1A.220624.014 release-keys]
Brave build: 1.52.109
Chromium: 114.0.5735.26 (Official Build) beta (64-bit)
Revision: 7075cbb66f0542ac3e01ddfde6b813e7d61118a5-refs/branch-heads/5735@{#454}
```
---------------------------

**STEPS:**
1. Install 1.50.x
2. Launch Brave with ads data (3 ads shown) in the BR panel
3. Upgrade to 1.52.x > Verify 

**ACTUAL RESULTS:**
- Verified that `Ads received this month`, `Current earnings this month (estimated)` and `Estimated Earnings` shows correct info after an upgrade.

|1.50.107|1.50.107|1.52.109|1.52.109|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/ee33b0a9-25b3-46b9-9c3f-78aafa9d3df6) | ![2](https://github.com/brave/brave-browser/assets/128532965/f8e1b033-81c4-409c-99f3-9f235483087c) | ![3](https://github.com/brave/brave-browser/assets/128532965/0cf8cc14-b445-4e88-b3c6-7f06ec03bf2a) | ![4](https://github.com/brave/brave-browser/assets/128532965/21defb8c-bf12-45ac-9bb0-5b0f72f99bd1) |

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.52.109 Chromium: 114.0.5735.26 (Official Build) beta (64-bit)
-- | --
Revision | 7075cbb66f0542ac3e01ddfde6b813e7d61118a5-refs/branch-heads/5735@{#454}
OS | Ubuntu 18.04

Followed the original steps to reproduce from https://github.com/brave/brave-browser/issues/29978#issue-1683516696

<details>

Confirmed `Estimated Earnings` is populated with its value retained, when upgrading

![image](https://github.com/brave/brave-browser/assets/34715963/15643af1-d562-4b9b-a6e2-522bc8147865)


</details>
