### ISSUE TITLE
Transaction status change mutation fails due to invalid return data

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#29988]
## Description 

the `transactionStatusChanged` mutation is throwing error when called due to it returning `undefined` as the result data

logged error:

```
"Error encountered handling the endpoint transactionStatusChanged.
              `queryFn` returned an object containing neither a valid `error` and `result`. At least one of them should not be `undefined`
              It needs to return an object with either the shape `{ data: <value> }` or `{ error: <value> }` that may contain an optional `meta` property.
              Object returned was: [object Object]", source: chrome://wallet/brave_wallet_page.bundle.js (115730)
```

## Steps to Reproduce

   1. Create and fund a wallet with EVM funds
   2. initiate an EVM transaction
   3. open the panel page (brave://wallet-panel.top-chrome/)
   4. open the JS console
   5. reject the transaction

## Actual result:

An error is logged to the console

## Expected result:
No errors should be logged to the console

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.53.102 Chromium: 114.0.5735.133 (Official Build) (64-bit)
-- | --
Revision | `fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}`
OS | Linux

- Verified steps from [brave/brave-core#18236](https://github.com/brave/brave-core/pull/18236)
- Verified rejecting a transaction doesn't log any invalid return data error in console

https://github.com/brave/brave-browser/assets/17010094/5922d39a-8196-45f1-a7b3-9c29eec10179

---------------------

**Verification passed on**

Brave | 1.53.102 Chromium: 114.0.5735.133 (Official Build) (64-bit)
-- | --
Revision | `fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}`
OS | Windows 11 Version 22H2 (Build 22621.1848)

- Verified steps from [brave/brave-core#18236](https://github.com/brave/brave-core/pull/18236)
- Verified rejecting a transaction doesn't log any invalid return data error in console

https://github.com/brave/brave-browser/assets/17010094/81bea471-f3f9-44bf-98ff-20eb9f86bff9

---------------------

**Verification passed on**

Brave | 1.53.102 Chromium: 114.0.5735.133 (Official Build) (64-bit)
-- | --
Revision | `fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#18236](https://github.com/brave/brave-core/pull/18236)
- Verified rejecting a transaction doesn't log any invalid return data error in console

https://github.com/brave/brave-browser/assets/17010094/c715fd68-94e8-4606-95b0-cca16200c92f
