### ISSUE TITLE
[Rewards] Tip amount is not shown for both One-time and Monthly tip

### ISSUE THREAD

**Issue by vlad-hoff** [brave/brave-browser#29981]
## Description 

Tip amount is not shown for both One-time and Monthly tip

## Steps to reproduce 

   1. Activate Rewards and connect the wallet first
   2. Open amazon.com for example > Rewords thumbnail in a search bar
   3. Tap "Send tip" > One-Time Tips > Choose amount > Send Tip > Observe
   4. Repeat steps 2 and 3, but choose "Monthly" option now now
   5. Choose amount > Set monthly tip > Observe

## Actual result 

When user is trying to send One-Time or Monthly Tip, sent amount is not shown on the confirmation page

|1|2|
|-|-|
| ![1](https://user-images.githubusercontent.com/128532965/234359798-f2292aa1-ec4e-44b8-9553-7fad8db4d59a.png) | ![2](https://user-images.githubusercontent.com/128532965/234359840-58b016e2-79b7-43ac-a17d-eb0aa6df8583.png) |

[log_oriole-user_10-55-16.txt](https://github.com/brave/brave-browser/files/11325507/log_oriole-user_10-55-16.txt)

## Expected result

Sent tip amount must be shown on the confirmation page

## Issue reproduces how often 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Pixel 6 [phone]
   - Android version: oriole-user 13 TQ2A.230305.008.E1 release-keys
   
## Brave version

1.52.69, Chromium 113.0.5672.53 (Official Build) canary (32-bit)

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by Miyayes** [comment]
solved by banner 3.0
