### ISSUE TITLE
Unable to close grant notification by clicking ok button

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#2998]
## Description 

Unable to close grant notification by clicking ok button

## Steps to Reproduce

   1. Clean profile on 0.59.24
   2. Click on BR panel button, shows Token grant notification
   3. Click the OK button, notification doesn't dismiss, have to click the notification close button to dismiss it

## Actual result:

![rewards](https://user-images.githubusercontent.com/17010094/51296021-20adc900-1a40-11e9-9b26-560261106683.gif)

## Expected result:
Should be able to clear the notification by clicking the ok button

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.59.25 Chromium: 72.0.3626.53 (Official Build) beta(64-bit)
-- | --
Revision | 98434e6cd182d68ce396daa92e9c6310422e6763-refs/branch-heads/3626@{#620}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes only on Beta
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

#2833

**Comment by btlechowski** [comment]
Unable to reproduce on Windows 7 x64

Brave | 0.59.25 Chromium: 72.0.3626.53 (Official Build) beta (64-bit)
-- | --
Revision | 98434e6cd182d68ce396daa92e9c6310422e6763-refs/branch-heads/3626@{#620}
OS | Windows 7

![2998](https://user-images.githubusercontent.com/34715963/51408221-4a5d1200-1b5e-11e9-9ec4-f169e95351bc.gif)

**Comment by ryanml** [comment]
See this fix which was uplifted in to `0.59.x` here: https://github.com/brave/brave-core/pull/1388

This addresses the issue where the panel was showing when rewards disabled, and in turn will solve this issue. @srirambv please let me know there was something else with this one, thanks!

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.59.28 Chromium: 72.0.3626.64 (Official Build) beta(64-bit)
-- | --
Revision | eaa9668e80ce5405e7f1902579558ea725c06ca1-refs/branch-heads/3626@{#708}
OS | Linux
