### ISSUE TITLE
[Rewards] Unable to claim a token grant. Infinite spinner/Error is shown.

### ISSUE THREAD

**Issue by vlad-hoff** [brave/brave-browser#29987]
## Description 

Unable to claim a token grant. Infinite spinner/Error is shown.

## Steps to reproduce 

   1. Activate Rewards and connect the wallet first
   2. Open Rewords thumbnail in a search bar > Confirm that "A taken grant is available!" is shown
   3. Tap "Claim Rewards" > Observe an error
   4. Now go to brave://rewards > Tap "Claim" on "A taken grant is available!" > Observe infinite loading spinner

## Actual result 

When user is trying to claim a token grant from brave://rewards page, infinite loading spinner is shown. When user is trying to claim it through Rewards Menu, then error is shown.

NOTE: I can reproduce it on GP Release build 1.50.114 on the same phone, but I wasn't able to reproduce it on Nightly on Pixel 7 [Android 14] and SM A32 [Android 13]

![1](https://user-images.githubusercontent.com/128532965/234389752-1560511c-412b-410d-9a89-d478b83b76b7.png)

https://user-images.githubusercontent.com/128532965/234391289-ebb4fd42-237d-4bb8-a21c-4a6af43b7039.mov

## Expected result

User must be able to claim a token grant

## Issue reproduces how often 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Pixel 6 [phone]
   - Android version: oriole-user 13 TQ2A.230405.003.E1 release-keys
   
## Brave version

1.52.69, Chromium 113.0.5672.53 (Official Build) canary (32-bit)

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by Miyayes** [comment]
Are you on staging or prod when you try to do this?
