### ISSUE TITLE
`Copy Clean Link` in `Share this page` should read `Copy clean link`

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#29989]
## Steps to Reproduce

   1. install `1.52.72`
   2. launch Brave
   3. load `brave.com`
   4. click on the `Share this page` icon in the URL bar
   5. notice the spelling of `Copy link` and `Copy Clean Link`

## Actual result:

<img width="1312" alt="Screen Shot 2023-04-25 at 1 45 42 PM" src="https://user-images.githubusercontent.com/387249/234400643-415afbcf-a02a-4f83-999f-7f9b635b6577.png">

One of the above -- I'm not sure which -- is wrong.  

`Copy link` (lowercase)
`Copy Clean Link` (uppercase)

## Expected result:

Perhaps `Copy clean link`?  I think text here should be normal capitalization rules, but not sure.

Their casing should be the same, rule-wise.

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.52.72 Chromium: 113.0.5672.53 (Official Build) nightly (x86_64)
-- | --
Revision | 12f5dac35d12e8f4e72d7dd11df557ef93bc046f-refs/branch-heads/5672@{#703}
OS | macOS Version 11.7.6 (Build 20G1231)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

/cc @rebron @rmcfadden3 @spylogsster @LaurenWags

**Comment by bsclifton** [comment]
Link is added to menu here:
https://github.com/brave/brave-core/blob/c5020b7d9bc5a20cab58aefd85e514fd9fa44f8e/chromium_src/chrome/browser/sharing_hub/sharing_hub_model.cc#L39-L40

Not sure why it pulls the title case one? Maybe the logic is correct but there aren't title case entries for the others (ex: `Copy link`)

**Comment by spylogsster** [comment]
> Link is added to menu here: https://github.com/brave/brave-core/blob/c5020b7d9bc5a20cab58aefd85e514fd9fa44f8e/chromium_src/chrome/browser/sharing_hub/sharing_hub_model.cc#L39-L40
> 
> Not sure why it pulls the title case one? Maybe the logic is correct but there aren't title case entries for the others (ex: `Copy link`)

Thanks @bsclifton , Im not able to reproduce the issue but this looks like it could be a reason, created PR to use separate label for this item.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.58.78 Chromium: 116.0.5845.51 (Official Build) nightly (x86_64)
-- | --
Revision | ca260d83d1ffda3cb35bff4bdc3251f30f9c8ccd
OS | macOS Version 11.7.9 (Build 20G1426)
```

<img width="1413" alt="Screen Shot 2023-08-07 at 2 04 27 PM" src="https://github.com/brave/brave-browser/assets/387249/abf40e1e-9f56-4882-a33c-db0a9ba5a51b">
