### ISSUE TITLE
Cookie List should be enabled at first launch

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#29986]
## Description 

Set Cookie List filter (Easylist - Cookie List) as enabled for all new and existing users.

See: https://github.com/brave/brave-browser/issues/10433

## Expected result:
1. Start browser with a new profile.
2. Navigate to brave://adblock.
3. Expand the list of filters, and verify that the "Cookie List" filter has been enabled.

## Brave version (brave://version info)

tbd.

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a 
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

Related issue: https://github.com/brave/brave-browser/issues/10433

**Comment by arthuredelstein** [comment]
One idea could be to show an in-app notification to users informing them that blocking has been turned on by default. This would:
 - Let users know about a very nice built-in feature in Brave.
 - Ensure that any users who have previously said "no" to cookie prompt blocking are aware that blocking will now be happening (and giving them a link to turn off blocking if they really wish to do so).

**Comment by antonok-edm** [comment]
@rebron I updated the issue slightly - the dialog code will be repurposed according to https://bravesoftware.slack.com/archives/C06UXF3KJ/p1692219055340939?thread_ts=1692213061.694329&cid=C06UXF3KJ, and it's already off by default in the code, so no changes required there. Just going to turn the Griffin flag _ON_ by default for enabling the cookie list.

**Comment by kjozwiak** [comment]
The above requires `1.58.117` or higher for `1.58.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.58.117 Chromium: 116.0.5845.180 (Official Build) (x86_64)
-- | --
Revision | 99255ad6abf2fa399c063683c051f973e1f5c0af
OS | macOS Version 13.5.2 (Build 22G91)
```
