### ISSUE TITLE
Sidebar is defaulting to left instead to the right when vertical tabs are enabled in Nightly for a new install

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#29992]
## Description 

Sidebar is defaulting to left instead to the right when vertical tabs are enabled in Nightly for a new install. (Note: Sidebar position is not changed prior)
## Steps to Reproduce

   1. Install 1.52.73
   2. launch Brave
   3. open `brave://settings/appearance` in a new-tab 
   4. enable `Use vertical tabs`

## Actual result:

ex|ex
---|---
<image width="550" alt="image" src="https://user-images.githubusercontent.com/98358127/234433916-6fa954d6-1b49-4cdc-a1ba-22fa7d9785aa.png">|<image width="550" alt="image" src="https://user-images.githubusercontent.com/98358127/234433949-111b209c-36c5-4e1e-966e-3b1a64f8f326.png">

## Expected result:
Sidebar should be defaulted to right

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.52.73 Chromium: 113.0.5672.53 (Official Build) nightly (64-bit)
-- | --
Revision | 12f5dac35d12e8f4e72d7dd11df557ef93bc046f-refs/branch-heads/5672@{#703}
OS | Windows 11 Version 22H2 (Build 22621.1555)
```
## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the nightly channel?  Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
 @sangwoo108 @rebron

**Comment by sangwoo108** [comment]
This would happen only when the vertical tab state is changed via settings page. Enabling it with context menu could be working as expected.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.53.19 Chromium: 113.0.5672.77 (Official Build) nightly (64-bit)
-- | --
Revision | c4236862955e005c2187105415ac4a2ecf86dff1-refs/branch-heads/5672_62@{#3}
```

#### Case 1: enable `Use vertical tabs` via `brave://settings/appearance` 

1. Install 1.53.19
2. launch Brave
3. click `Set Brave as default browser`
4. select `Vivaldi` >> `Import` >> `Finish` 
5. open brave://settings/appearance
6. enable `Use vertical tabs` 

#### Confirmed Sidebar defaulted to right

<image width = "500" alt="image" src="https://user-images.githubusercontent.com/98358127/236263682-f7ae6d59-34fb-42ac-a179-0e878e6cb372.png">

#### Case 2: enable `Use vertical tabs` via `context menu`

1. new profile 
2. launch Brave
3. click `Set Brave as default browser`
4. select `Microsoft Edge` >> `Select All` >> `Import profiles` >> `Finish` 
5. open few tabs from imported edge profiles (Profile 1)
6. right click on a tab (BBC) to open context  menu
7. select `Use vertical tabs`

#### Confirmed Sidebar defaulted to right

example | example
----- | ------
<image width = "400" alt="image" src="https://user-images.githubusercontent.com/98358127/236268121-6f2da748-1be9-427a-8592-5c94c582f69f.png">|<image width = "400" alt="image" src="https://user-images.githubusercontent.com/98358127/236268537-a94b0810-81c7-4fd6-b240-fe8a601a5302.png">

#### Case 3: select `Show on left` for `Show Sidebar button`

1. new profile 
2. launch Brave
3. click `Skip` >> `Skip` >> `Finish`
4. select `Microsoft Edge` >> `Select All` >> `Import profiles` >> `Finish` 
5. open brave://settings/appearance
6. enable `Use vertical tabs`
7. select `Show on left` radio button for `Show Sidebar button` 

#### Confirmed `Sidebar` shown left next to the vertical tab panel

example | example
----- | ------
<image width = "400" alt="image" src="https://user-images.githubusercontent.com/98358127/236271592-4a483d58-0c7e-4267-8dce-f6c6a08c3cd8.png">|<image width = "500" alt="image" src="https://user-images.githubusercontent.com/98358127/236271843-70766a56-82ae-4315-bf5c-dafbd23e409d.png">

**Comment by kjozwiak** [comment]
The above requires `1.52.92` or higher for `1.52.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.52.92 Chromium: 113.0.5672.92 (Official Build) beta (x86_64)
-- | --
Revision | b6f521170062a1fa8a82c33fb223b06fec566da1-refs/branch-heads/5672_63@{#10}
OS | macOS Version 11.7.6 (Build 20G1231)

### Steps:
1. installed `1.52.92`
2. launched Brave
3. skipped onboarding
4. noted the position of the sidebar (on the left-hand side)
5. context-clicked on the new tab
6. chose `Use Vertical Tabs`

### Confirmed the sidebar moved to the right-hand side

example | example | example
---------|----------|---------
<img width="1312" alt="Screen Shot 2023-05-09 at 9 51 37 AM" src="https://github.com/brave/brave-browser/assets/387249/a952c07c-c28e-49a9-9349-48a3cc869df8"> | <img width="1195" alt="Screen Shot 2023-05-09 at 9 51 50 AM" src="https://github.com/brave/brave-browser/assets/387249/0876ea70-8626-4436-846b-1e130b584128"> | <img width="1312" alt="Screen Shot 2023-05-09 at 9 51 56 AM" src="https://github.com/brave/brave-browser/assets/387249/7abab24e-835a-4a4b-821f-aafe7cbf7498">

**Comment by adriancostin6** [comment]
Writing here, after I've done a fair bit of looking through the settings and searching the web. Can the user configure the vertical tab bar to appear on the right hand side? If not, can a feature for this be requested 👍 ?

**Comment by sangwoo108** [comment]
Hi, @adriancostin6 . We don't have that setting at this moment. cc @rebron
