### ISSUE TITLE
Enable rich version of Brave Search autocomplete

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#29997]
## Description 

Brave Search provides a richer version of autocomplete suggestions and should be supported in the address bar.

## Expected result

   1. Type in a keyword such as `bicycle`
   2. Compare autocomplete in Brave Search https://search.brave.com with the address bar. 
   3. Richer autocomplete which displays thumbnail preview should display with the address bar autocomplete.

<img width="745" alt="Screenshot 2023-04-25 at 8 45 18 PM" src="https://user-images.githubusercontent.com/5951041/234465571-3d200f50-90c1-446f-a9e6-29841257c407.png">
<img width="263" alt="Screenshot 2023-04-25 at 8 46 21 PM" src="https://user-images.githubusercontent.com/5951041/234465572-f2eb4e1a-d802-4e7e-9739-71f28e33552f.png">

## Reproduces how often: 

Easily

## Desktop Brave version:

Tbd.

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

Related issue: https://github.com/brave/brave-browser/issues/29517

**Comment by sangwoo108** [comment]
As our rich suggest and Google's have different format, we need to duck type our return type.

**Comment by MadhaviSeelam** [comment]
Verification PASSED using
```
Brave | 1.68.84 Chromium: 126.0.6478.40 (Official Build) beta (64-bit)
-- | --
Revision | c5a3b2ff9dcc938c32b2c1b3a66847661db5d005
OS | Windows 11 Version 23H2 (Build 22631.3672)
```

1. Installed 1.68.84
2. launched Brave
3. opened `brave://settings/search` in a new tab
4. enabled `Improve search suggestions`
5. entered few letters in the omnibox (`Worl`, `Ire`, `bic`) 

Confirmed entities with image and description as below

- `Worl` --> World map and World market images are shown and descriptions returned 
- `Ire` --> `Ireland` map and `Ireland Baldwin` images and descriptions returned 
- `bic` --> `Bichon Frise` & `Bicarbonate` images and descriptions returned
- `hel` --> `Helldrivers 2 & Hello(Adele song) images and descriptions returned


brave://settings/search | `Worl` | `Ire` | `bic` | `hel` 
----- | ------ | ------ | ------ | -------
<img width="953" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/f2cc4cc9-91fe-4a9f-b409-0edd1ed04101">|<img width="953" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/c5f15564-e572-4acb-a921-677e1eb8bc29">|<img width="959" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/39a4a840-4c13-4d89-8ec0-38c4adf0fb25">|<img width="953" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/6e869b1d-ceae-46f0-bae0-8df10d5a4f06">|<img width="953" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/da3a0c6d-10e9-4c3e-ad03-3a0ff0dab66a">

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.68.86 Chromium: 126.0.6478.56 (Official Build) beta (x86_64)
-- | --
Revision | b4eadb4942277a3eb455fc7c3c8569185bd745af
OS | macOS Version 11.7.10 (Build 20G1427)
```

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave	1.68.87 Chromium: 126.0.6478.56 (Official Build) beta (64-bit) 
Revision	786b6b66ebe624e5c4ef760b3fe3047ea61932de
OS	Linux
```

**Comment by hffvld** [comment]
Verified on `Galaxy Tab S8` and `Pixel 7` using version(s):
```
Device/OS: 
- Galaxy Tab S8 / gts8wifixx-user 14 UP1A.231005.007 release-keys
- Pixel 7 / panther_beta-user 15 AP31.240517.031 release-keys
Brave build: 1.68.101
Chromium: 126.0.6478.126 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Launch Brave
2. Settings > Brave Shields & privacy > Enable `Improve search suggestions`
3. Go back and tap in a URL search bar
4. Type:
- `tiger` > *Verify that thumbnails for `Tiger` and `Tiger Woods` are shown*
- `brave` > *Verify that thumbnails for `Brave search` and `Atlanta Braves` are shown*
- `car` > *Verify that thumbnails for `CarMax` and `Carvana` are shown*
- `cat` > *Verify that thumbnails for `Cathay Pacific` and `Cate Blanchett` are shown*
- `wall` > *Verify that thumbnails for `Wallpaper Engine` is shown*
- `iron` > *Verify that thumbnails for `Iron`, `Ironmouse`, `Iron Man` and `The Iron Claw (film)` are shown*

**ACTUAL RESULTS:**
- Verified that thumbnail previews are only shown in search results when `Improve search suggestions` is enabled
- Verified that the rich version of Brave Search is working as expected

---------------------------

|`Improve search suggestions` is OFF|`Improve search suggestions` is ON|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/abcad6cf-1078-4711-bfd4-bff663d48a83) | ![2](https://github.com/brave/brave-browser/assets/128532965/35458b0a-4dc1-4d7d-9adf-5991ca74540b) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/2ccc5359-686a-4c71-8000-84dcd03fa312) | ![2](https://github.com/brave/brave-browser/assets/128532965/51bb2dac-8ebb-40b4-b089-0d99ed5a25ea) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/5ed0c1aa-8146-43de-b74a-c86d6d44609f) | ![2](https://github.com/brave/brave-browser/assets/128532965/02f8db9d-039c-4963-850f-f4aa92f6cc0f) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/9c11b360-5478-4a1a-ba91-1248a94cdf98) | ![2](https://github.com/brave/brave-browser/assets/128532965/3c868dfe-3a29-41dc-85eb-b3c2c91caa17) |

`Pixel 7`

|`Improve search suggestions` is OFF|`Improve search suggestions` is ON|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/56166896-679b-4a6f-a821-a12b0e78c170) | ![2](https://github.com/brave/brave-browser/assets/128532965/65ecb37f-5b73-4559-98aa-ec395e4c73a6) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/aef74c23-54bd-45e5-863a-91081e15eae1) | ![2](https://github.com/brave/brave-browser/assets/128532965/472bbdc3-a861-4d56-8d55-04a9ff9bf993) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/3bf8b6e7-c6ce-4bde-9307-2a7586c56593) | ![2](https://github.com/brave/brave-browser/assets/128532965/81cdd1e2-7620-4d13-be96-a39aee59be41) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/d7a5114b-4930-495c-8755-e13a8f610587) | ![2](https://github.com/brave/brave-browser/assets/128532965/40465612-c72a-4c54-84e2-397785d7ea23) |
