### ISSUE TITLE
Updated Portfolio Graph Layout with New Selector

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#29996]
## Description 

We need to update the `Portfolio` graph section to match the new designs in figma and build out the new `Timeline` menu.

![Screenshot 17](https://user-images.githubusercontent.com/40611140/234465114-8a5da223-9fa6-4a2f-803b-e0df65511ba9.png)

![Screenshot 18](https://user-images.githubusercontent.com/40611140/234465117-e25f7af2-351d-4f2c-aec9-8baadc40b641.png)

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.53.102 Chromium: 114.0.5735.133 (Official Build) (64-bit)
-- | --
Revision | `fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}`
OS | Linux

- Verified steps from [brave/brave-core#18251](https://github.com/brave/brave-core/pull/18251)
- Verified graph updates based on `Time Line` selection from dropdown
- Verified `Fiat` and `Percentage` changes according to `Time Line` change
- Verified reloading the page retains the selected `Time Line`

https://github.com/brave/brave-browser/assets/17010094/4f956055-4e99-41b1-9ca6-da6bd1c18907

---------------------

**Verification passed on**

Brave | 1.53.102 Chromium: 114.0.5735.133 (Official Build) (64-bit)
-- | --
Revision | `fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}`
OS | Windows 11 Version 22H2 (Build 22621.1848)

- Verified steps from [brave/brave-core#18251](https://github.com/brave/brave-core/pull/18251)
- Verified graph updates based on `Time Line` selection from dropdown
- Verified `Fiat` and `Percentage` changes according to `Time Line` change
- Verified reloading the page retains the selected `Time Line`

https://github.com/brave/brave-browser/assets/17010094/a652075a-bd48-4216-9015-1c8f924c6de5

---------------------

**Verification passed on**

Brave | 1.53.102 Chromium: 114.0.5735.133 (Official Build) (64-bit)
-- | --
Revision | `fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#18251](https://github.com/brave/brave-core/pull/18251)
- Verified graph updates based on `Time Line` selection from dropdown
- Verified `Fiat` and `Percentage` changes according to `Time Line` change
- Verified reloading the page retains the selected `Time Line`

https://github.com/brave/brave-browser/assets/17010094/0f17f4cb-9333-4741-adb3-aa4e60a884bc
