### ISSUE TITLE
Vertical tabstrip focus does not give owner window focus

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#29993]
## Description 

Vertical tabstrip focus does not give owner window focus

## Steps to Reproduce

   0. Enable vertical tabs
   2. Open 2 windows
   3. Click the tab strip of the inactive window
   4. Press cmd/ctrl-t

## Actual result:

A new tab is opened in the previously-active window

## Expected result:
A new tab is opened in the window we clicked the tab strip on

## Reproduces how often: 

100% on macOS

## Brave version (brave://version info)

1.52.54

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
## Verification `PASSED` using 

Brave | 1.52.86 Chromium: 113.0.5672.77 (Official Build) beta (x86_64)
-- | --
Revision | c4236862955e005c2187105415ac4a2ecf86dff1-refs/branch-heads/5672_62@{#3}
OS | macOS Version 11.7.6 (Build 20G1231)

### Steps:
1. installed `1.52.86`
2. launched Brave
3. enabled vertical tabs
4. opened two windows side-by-side
5. focused `window 1`
6. clicked on the **_tab strip_** of `window 2` 
7. pressed `command` + `T` to open a new tab

### Confirmed clicking on the inactive-window's tab strip set window focus, and opened the new tab within `window 2`

example | example | example
---------|----------|---------
<img width="1916" alt="Screen Shot 2023-05-04 at 12 47 52 PM" src="https://user-images.githubusercontent.com/387249/236316080-3ec7de30-b820-40d5-8a5c-bc638cd82cfd.png"> | <img width="1919" alt="Screen Shot 2023-05-04 at 12 58 52 PM" src="https://user-images.githubusercontent.com/387249/236316105-b0c398c9-e9dc-4cd9-a897-dc22ee57049d.png"> | <img width="1920" alt="Screen Shot 2023-05-04 at 12 59 28 PM" src="https://user-images.githubusercontent.com/387249/236316118-d93e332d-5653-4e3b-9d2e-b92a96708805.png">
