### ISSUE TITLE
Make Flash plan for the first release

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#30]
Chrome's Flash deprecation policy is here:
https://www.chromium.org/flash-roadmap

As of C68 we'll have:

```
Non-Persisted HTML5 by Default (Target: Chrome 68 - July 2018)
Summary
Sites using Flash will require explicit permission to run, every time the user restarts the browser.
Rationale
Require affirmative user choice to run Flash Player content, without that choice persisting across multiple sessions.
```

For the initial version that is OK.

We can diverge from the Disable by default (Chrome 76+ - July 2019) and Remove Flash completely ( Dec 2020) in separate issues.

**Comment by bbondy** [comment]
CC @diracdeltas in case there are objections.  See above https://github.com/brave/brave-browser/issues/30#issue-279511519

**Comment by bbondy** [comment]
Talked to @diracdeltas and she'd like to match this milestone:
https://www.chromium.org/flash-roadmap#TOC-Flash-Disabled-by-Default-Target:-Chrome-76---July-2019-

So re-opening.

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Linux

* Verified visiting http://homestarrunner.com/ showed `Plugin blocked` message on URL bar
* Verified clicking `Run flash this time` reloads the page
* Verified `Enable Plugin` is shown in right click context menu after page reloads, clicking it loads the flash content
