### ISSUE TITLE
style import window

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#3000]
## Description 
Carry over font and button styling from main settings for Import dialog.

## Currently:
<img width="516" alt="screen shot 2019-01-16 at 10 01 20 pm" src="https://user-images.githubusercontent.com/5951041/51298716-72bc0380-19da-11e9-9738-7439db8183d6.png">

## Expected result:
Need screenshot

**Comment by rebron** [comment]
@petemill This looks fixed. ok to close?

**Comment by petemill** [comment]
Yes this was addressed with https://github.com/brave/brave-core/pull/1422
