### ISSUE TITLE
Update wallet reset title

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#30005]
## Description 
Update wallet reset title to `Reset and clear wallet data` [as discussed here](https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1682324758670509).

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.53.94 x64 Beta build
- Verified steps form [brave/brave-core#18246](https://github.com/brave/brave-core/pull/18246)
- Verified reset wallet title is changed from `Reset Brave Wallet` to `Reset and clear wallet data`

Light | Dark
-- | --
![image](https://github.com/brave/brave-browser/assets/17010094/ac2fd41a-95ca-4730-aeca-798f100dcf25) | ![image](https://github.com/brave/brave-browser/assets/17010094/fc742614-ddf3-461f-b616-ddec7abb6aef)

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.53.94 Chromium: 114.0.5735.133 (Official Build) beta (64-bit)
-- | --
Revision | `fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}`
OS | Windows 11 Version 22H2 (Build 22621.1848)

- Verified steps from [brave/brave-core#18246](https://github.com/brave/brave-core/pull/18246)
- Verified reset wallet title is changed from `Reset Brave Wallet` to `Reset and clear wallet data`

Dark | Light
-- | --
![brave_EPRJKlAZ1a](https://github.com/brave/brave-browser/assets/17010094/fa734792-ce93-4aee-aa81-1ae7aba4f33e) | ![brave_XFXQQ5ASaS](https://github.com/brave/brave-browser/assets/17010094/1b3957ca-e449-40fb-bb19-3d71bd702092)

**Comment by kjozwiak** [comment]
The above requires `1.52.130` or higher for `1.52.x` verification 👍 Removing the `QA Pass` label(s) as the above will need to be rechecked with `1.52.x`.
