### ISSUE TITLE
Update NFT IPFS banner text to "Back up your NFT data with IPFS."

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#30019]

**Comment by kjozwiak** [comment]
The above requires `1.52.83` or higher for `1.52.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.52.100 Chromium: 113.0.5672.92 (Official Build) beta (64-bit) 
-- | --
Revision | `b6f521170062a1fa8a82c33fb223b06fec566da1-refs/branch-heads/5672_63@{#10}`
OS | Windows 11 Version 22H2 (Build 22621.1702)

- Verified NFT IPFS banner is updated as per the new review copy

https://github.com/brave/brave-browser/assets/17010094/fe31598d-ac74-4158-baa5-a1b54c70c3fc
