### ISSUE TITLE
aw snap, if I try to login on gitlab.com

### ISSUE THREAD

**Issue by harridu** [brave/brave-browser#30013]
## Description 
If I try to login on gitlab.com using Brave Version 1.50.121 Chromium: 112.0.5615.138 on Debian Testing I get an Aw, snap instead.

## Steps to Reproduce

   1. logout from gitlab.com
   2. visit https://gitlab.com/users/sign_in 
   3. enter your credentials

## Actual result:
There is an Aw, Snap saying

    Something went wrong while displaying this webpage.
    Error code: 4

## Expected result:

I would prefer if it could let me work on gitlab.com. 

## Reproduces how often: 

Every time. A week ago it still worked. There is no such issue with Debian's chromium.

## Brave version (brave://version info)

* 1.50.121 Chromium: 112.0.5615.138 (Official Build) (64-bit) 
* 2258f2fcaeb07bc95c992b7ca47f0b43ead9865c-refs/branch-heads/5615@{#1282}
* Linux

**Comment by rebron** [comment]
Hi @harridu Can you update to 1.50.125 and see if you're still seeing this issue?

**Comment by harridu** [comment]
Works for me. 

Thank you very much. Please keep on your good work
