### ISSUE TITLE
Enable `title bar` by default when enabling `vertical tabs` (Windows only)

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#30027]
## Description 

As discussed, we should enable `title bar` by default when `vertical tabs` are being enabled. Currently `title bar` is disabled by default which might confuse some users. Because the `title bar` is pretty much an expected part of every window, we should make it appear/displayed as default and more advanced users can disable via `brave://settings/appearance`.

## Steps to Reproduce

   1. launch `1.52.72 Chromium: 113.0.5672.53`
   2. enable `vertical tabs` via the right click context menu or `brave://settings/appearance`

Notice that the `title bar` is currently disabled by default.

## Actual result:

![image](https://user-images.githubusercontent.com/2602313/234729791-b903134e-f48f-4cc1-99b3-c8f9365f4024.png)

## Expected result:

![image](https://user-images.githubusercontent.com/2602313/234729727-d82fe946-f36c-4872-b0c6-fdb024e92b91.png)

## Reproduces how often: 

100% reproducible when using the STR/Cases outlined above.

## Brave version (brave://version info)

```
Brave | 1.52.72 Chromium: 113.0.5672.53 (Official Build) nightly (64-bit)
-- | --
Revision | 12f5dac35d12e8f4e72d7dd11df557ef93bc046f-refs/branch-heads/5672@{#703}
OS | Windows 11 Version 22H2 (Build 22621.1555)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @rebron @sangwoo108 @simonhong @brave/qa-team

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.52.93 Chromium: 113.0.5672.92 (Official Build) beta (64-bit)
-- | --
Revision | b6f521170062a1fa8a82c33fb223b06fec566da1-refs/branch-heads/5672_63@{#10}
OS | Windows 11 Version 22H2 (Build 22621.1555)
```


- Install 1.52.93
- launch Brave
- click Set Brave as default browser
- select Vivaldi>> Import >> Finish
- select `Target` bookmark to open the site
- open `brave://settings/appearance`
- enable `Use vertical tabs`

Confirmed `Show title bar` is checked by default in `brave://settings/appearance`
Confirmed the title bar is shown with vertical tabs enabled - `Target : Expect More, Pay less. - Brave`
Confirmed when `Show title bar` unchecked in `brave://settings/appearance`, title bar is not shown

example | example | example | example
---- | ---- | ---- | -----
<image width = "700" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/fe75d6f9-8483-4b53-ac45-ddb3326da2ed">|<image width = "700" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/d4c13c32-22d1-418f-a755-75eca171051b">|<image width = "700" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/d9214077-9180-4ddb-b869-ee7b722cc317">|<image width = "700" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/153164cb-e161-48a1-a572-46ea92062352">
