### ISSUE TITLE
Crash when trying to open brave://sync in tor window

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#3003]
## Description 

browser crashed when trying to load brave://sync in tor window

## Steps to Reproduce

Case 1.
   1. Open brave://settings in normal window
   2. Try to open brave://sync to tor window via context menu
   3.  Crashed

Case 2.
  1. Open tor window
  2. Type brave://sync in omnibox
  3. Crashed

Case 3.
  1. Open tor window
  2. Type brave://settings
  3. Click brave://sync link
  4. Crashed

## Actual result:

Crashed

## Expected result:
Case 1) `Open Link in Private Window With Tor` is disabled in context menu
Case 2, 3) Not crashed

## Reproduces how often: 

Every time

## Brave version (brave://version info)

Version 0.59.20 Chromium: 72.0.3626.28 (Official Build) beta (64-bit)
Version 0.60.6 Chromium: 72.0.3626.28 (Official Build) dev (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
both. sync is not enabled in stable
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? No

### Additional Information

Guest window has same crash.

**Comment by simonhong** [comment]
To fix this crash quickly, I think loading sync page should be blocked in tor & guest window.

**Comment by Jacalz** [comment]
I have run in to this too when using 0.59.34 on Linux...

**Comment by simonhong** [comment]
@tomlowenthal @rebron How about making priority more higher than p4 because this is crash issue?

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.63.4 Chromium: 73.0.3683.67 (Official Build) dev (64-bit)
-- | --
Revision | a83fd4f3207ae83412d329a9ca1239dd1e068345-refs/branch-heads/3683@{#760}
OS | Windows 7 Service Pack 1 Build 7601.24312

Used test plan from the description
![image](https://user-images.githubusercontent.com/34715963/54250333-aaab7700-4543-11e9-8479-5d5811d8ce37.png)
![image](https://user-images.githubusercontent.com/34715963/54250293-7df75f80-4543-11e9-8905-ceaf4c411ec5.png)
