### ISSUE TITLE
brave://new-tab-page & brave://new-tab-page-third-party don't act properly

### ISSUE THREAD

**Issue by AlbydST** [brave/brave-browser#30035]
## Description 

Going to brave://new-tab-page or brave://new-tab-page-third-party displays a google-like new tab page with brave search instead of the same as brave://newtab

## Steps to Reproduce

   1. Go to brave://new-tab-page or brave://new-tab-page-third-party
   2. 
   3. 

## Actual result:

![image](https://user-images.githubusercontent.com/119180144/234933725-0fd56990-4c2e-44d9-8a7d-344941ba10ef.png)

## Expected result:
The page is identical or redirects to brave://newtab

## Reproduces how often: 
 Only reproducable intentionally

## Desktop Brave version:
 [Versione 1.48.164 Chromium: 110.0.5481.100 (Build ufficiale) (64 bit)]

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/10676 (removing this page). Thanks for the report 😄
