### ISSUE TITLE
Android should use same webcompat report url as desktop does

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#30034]
Currently URL for webcompan reports is taken from:

Desktop: `https://webcompat.brave.com/1/webcompat` or `webcompat_report_api_endpoint` `.npmrc` arg, [link](https://github.com/brave/brave-core/blob/master/build/commands/lib/config.js#L147)

Android, hard-coded `https://laptop-updates.brave.com/1/webcompat` [BraveShieldsUtils.httpUrl](https://github.com/brave/brave-core/blob/master/android/java/org/chromium/chrome/browser/shields/BraveShieldsUtils.java#L36)

It should be taken from the same place, https://webcompat.brave.com/1/webcompat

**Comment by vlad-hoff** [comment]
Verified on `Google Pixel 7` using version(s):
```
Device/OS: Google Pixel 7 [panther_beta-user 14 UPB2.230407.014 release-keys]
Brave build: 1.53.76
Chromium: 114.0.5735.90 (Official Build) beta (64-bit)
Revision: 386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}
```
---------------------------

**STEPS:**
1. Launch Brave
2. Open some website
3. Brave Shields > Turn the shields off
4. Press `Report a broken site` > Submit > Verify

**ACTUAL RESULTS:**
- Verified that `Thank you!` message is shown when reporting a broken website
- Verified that Brave is not crashing when reporting a broken website

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/9e5100a1-6253-4b56-b492-573299307b49) | ![2](https://github.com/brave/brave-browser/assets/128532965/d9ebec3c-6563-4f10-8be2-38a271adfb2c) |

https://github.com/brave/brave-browser/assets/128532965/56c09be5-344c-4fee-b7dd-a8e5c62adffd

NOTE: Issue #30440 is seen as well as `500 error` described in https://github.com/brave/brave-core/pull/18281#issue-1687238057. CC @AlexeyBarabash
