### ISSUE TITLE
Incorrect 'last_used' value in Local State file after using private window with Tor

### ISSUE THREAD

**Issue by fbelzile** [brave/brave-browser#3004]
## Description
The value 'last_used' in the in the Local State file (%LOCALAPPDATA%\BraveSoftware\Brave-Browser\User Data\Local State) is incorrect after opening and closing a new private window with Tor. 

## Steps to Reproduce
   1. Open Brave, then open new private window with Tor
   2. last_used value is correct: Tor Profile
   3. Close the private window with Tor, and visit a website using Default profile
   4. last_used value is incorrect: Tor Profile, expected: Default

## Reproduces how often: 
Every time. Until the profile is changed manuall or until the guest profile is used.

## Brave version (brave://version info)
Version 0.58.21 Chromium: 71.0.3578.98 (Official Build) (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes, on:
Version 0.60.13 Chromium: 72.0.3626.53 (Official Build) dev (64-bit)

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

### Additional Information
This issue was initially reported by uses of my software. My software checks to see if an extension is installed or not on Chrome, Firefox, Opera, Vivaldi and Brave: https://getcoldturkey.com

**Comment by srirambv** [comment]
cc: @riastradh-brave @bbondy

**Comment by rebron** [comment]
Tor is using guest profile so expected for now.

**Comment by fbelzile** [comment]
> Tor is using guest profile so expected for now.
I agree that this is good. The issue I'm trying to point out is after closing the Tor window and returning back to the regular "default" profile, the last_used value isn't updated to reflect that. It continues to remain "Tor Profile" instead of "Default" long after the user is not using the Tor window (even after restarting Brave).

I'm not going to push this since I have a workaround (switching to the Guest profile and then back) for my users, but just wanted to provide a heads up since it may create compatibility issues with other external software like mine.
