### ISSUE TITLE
Randomize USB serial numbers per device

### ISSUE THREAD

**Issue by pilgrim-brave** [brave/brave-browser#30041]
Current implementation <https://github.com/brave/brave-core/pull/17470> may end up with duplicate serial numbers if multiple USB devices are connected.

**Comment by kjozwiak** [comment]
The above requires `1.51.117` or higher for `1.51.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED using 
```
Brave | 1.51.117 Chromium: 113.0.5672.92 (Official Build) (64-bit)
-- | --
Revision | b6f521170062a1fa8a82c33fb223b06fec566da1-refs/branch-heads/5672_63@{#10}
OS | Windows 11 Version 22H2 (Build 22621.1702)
```

Using the STR/Cases outlined via https://dev-pages.brave.software/fingerprinting/devices.html, went through the following:

Ensured that there's multiple USB devices connected to the machine as per the following:

![image](https://github.com/brave/brave-browser/assets/98358127/de6bf3e7-f15c-4d72-a652-538f89cbf9b5)



*_Allow Fingerprinting_*

Example | Example  
------- | ------- 
![image](https://github.com/brave/brave-browser/assets/98358127/098a4054-cc7d-4f9b-91f6-187058833b06)|![image](https://github.com/brave/brave-browser/assets/98358127/f336589c-51b8-4afe-9cba-97881c8a7d1e)

*_Block Fingerprinting_*

Example | Example 
----- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/f17ed963-e494-4f76-9a45-2a51848a8414)|![image](https://github.com/brave/brave-browser/assets/98358127/2848acc3-7e01-4e68-aa5a-362c22cdf601)

*_Aggressively block Fingerprinting_*

Example | Example 
----- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/16381ce4-da90-4d6a-a020-cc0fabed73ed)|![image](https://github.com/brave/brave-browser/assets/98358127/ccf7a151-c132-47ec-8702-ad64265c9263)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.51.118 Chromium: 113.0.5672.126 (Official Build) (64-bit) 
-- | --
Revision | c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}
OS | Ubuntu 18.04 LTS


*_Allow Fingerprinting_*

Example | Example  
------- | ------- 
![image](https://github.com/brave/brave-browser/assets/34715963/d01da402-8ca2-4d5f-9490-c0a0a9728d42)|![image](https://github.com/brave/brave-browser/assets/34715963/83b84385-d497-48fc-bc54-cac2c7755bab)


*_Block Fingerprinting_*

Example | Example 
----- | ----
![image](https://github.com/brave/brave-browser/assets/34715963/8a711d3c-33b7-498e-90e0-b9c76f4300bf)|![image](https://github.com/brave/brave-browser/assets/34715963/77e77526-e66a-4e97-bbff-f8ce81422e0a)


*_Aggressively block Fingerprinting_*

Example | Example 
----- | ----
![image](https://github.com/brave/brave-browser/assets/34715963/d836395f-a833-4bae-9579-393b3c8f0a5f)|![image](https://github.com/brave/brave-browser/assets/34715963/4d4d89f0-1158-4cce-87c5-e3a62b109f3a)

**Comment by vlad-hoff** [comment]
Verified on `Google Pixel 7` and `Galaxy Tab S8` using version(s):
```
Device/OS: 
- Google Pixel 7 [panther_beta-user 14 UPB1.230309.017 release-keys]
- SM-X700 Galaxy Tab S8 [gts8wifixx-user 13 TP1A.220624.014 release-keys]
Brave build: 1.51.118
Chromium: 113.0.5672.126 (Official Build) (64-bit)
Revision: c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}
```
---------------------------

**STEPS:**
1. Connect multiple USB devices
2. Open to https://dev-pages.brave.software/fingerprinting/devices.html
3. Go through the flow
4. Now open https://dev-pages.bravesoftware.com/fingerprinting/devices.html
5. Go through the flow

**ACTUAL RESULTS:**
- Verified when multiple USB devices are connected, no duplicate serial numbers are shown

<details>
<summary> Phone - PASS </summary>

**Allow all fingerprinting**
|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/80aaa8ff-9c10-45e9-80de-2cc50317b978) | ![2](https://github.com/brave/brave-browser/assets/128532965/827eef04-0191-4935-93f8-8183559d63f7) | ![3](https://github.com/brave/brave-browser/assets/128532965/4e3d808e-386b-44e2-89a5-e1eb081dc74c) | ![4](https://github.com/brave/brave-browser/assets/128532965/b36a36fd-727a-49eb-b200-6469d21bdc9e) |

**Fingerprinting blocked (standard)**
|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/d1ba1d08-e955-43b8-8a40-812524b4cea9) | ![2](https://github.com/brave/brave-browser/assets/128532965/dc828837-2d34-43c2-90b1-3a8a114ab4b8) | ![3](https://github.com/brave/brave-browser/assets/128532965/ef1f85a7-d8ce-4d07-a2fe-6ac95320596f) | ![4](https://github.com/brave/brave-browser/assets/128532965/88b7289f-3f0f-48b5-81d2-970ffdd4cc10) |

**Fingerprinting blocked (strict, may break sites)**
|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/d0171438-9cc8-4f5f-bf8f-0d5d4cee8979) | ![2](https://github.com/brave/brave-browser/assets/128532965/cb8824ba-0d9e-4761-9001-03b64feed6db) | ![3](https://github.com/brave/brave-browser/assets/128532965/5432cc5a-70c0-442a-b364-94b84cd2a887) | ![4](https://github.com/brave/brave-browser/assets/128532965/00b20982-8034-4d31-8f53-0d56d9befd28) |
</details>

<details>
<summary> Tablet - PASS </summary>

**Allow all fingerprinting**
|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/7ba43a59-d05a-4fe4-95b2-8b2d02f02d87) | ![2](https://github.com/brave/brave-browser/assets/128532965/7f1181bc-c322-4d46-bfa9-6d6175d2ffb7) | ![3](https://github.com/brave/brave-browser/assets/128532965/dbdb29fa-63e4-405f-b270-b7d295513337) |

**Fingerprinting blocked (standard)**
|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/aee83826-7e0f-46a5-9363-a87fa445a867) | ![2](https://github.com/brave/brave-browser/assets/128532965/3bd25def-d70d-46ce-93a6-b0941ef1595d) | ![3](https://github.com/brave/brave-browser/assets/128532965/23ff4e99-70f0-47f7-86fb-99ebea26fefb) |

**Fingerprinting blocked (strict, may break sites)**
|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/aee83826-7e0f-46a5-9363-a87fa445a867) | ![2](https://github.com/brave/brave-browser/assets/128532965/c94e1e10-099e-42a1-8c05-827fd46337f0) | ![3](https://github.com/brave/brave-browser/assets/128532965/f587377d-46fe-4ce1-ab62-225f8131dfe7) |
</details>
