### ISSUE TITLE
Banners need padding on Portfolio View

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#30049]
## Description 

We need to adding padding for the `Banners` on the `Portfolio` view

![Screenshot 26](https://user-images.githubusercontent.com/40611140/234991460-698b0af4-8d28-4e18-baa2-3a2a3e58bd0f.png)

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.53.102 Chromium: 114.0.5735.133 (Official Build) (64-bit)
-- | --
Revision | `fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}`
OS | Linux

- Verified steps from [brave/brave-core#18287](https://github.com/brave/brave-core/pull/18287)
- Verified banner has padding on portfolio page

![image](https://github.com/brave/brave-browser/assets/17010094/8da7ead8-a010-4cc6-bd03-2c1ea4320d77) | ![image](https://github.com/brave/brave-browser/assets/17010094/794f5211-6f3d-44ad-ae35-1972fe69b525) | ![image](https://github.com/brave/brave-browser/assets/17010094/c8d46881-0115-4a2f-a68f-e999686d2cc0)
-- | -- | --

---------------------

**Verification passed on**

Brave | 1.53.102 Chromium: 114.0.5735.133 (Official Build) (64-bit)
-- | --
Revision | `fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}`
OS | Windows 11 Version 22H2 (Build 22621.1848)

- Verified steps from [brave/brave-core#18287](https://github.com/brave/brave-core/pull/18287)
- Verified banner has padding on portfolio page


![image](https://github.com/brave/brave-core/assets/17010094/02c5425e-2dc6-41a4-92a1-4c7f1fbdcaca) | ![image](https://github.com/brave/brave-core/assets/17010094/ad27b338-345d-4435-ae6a-fbce2c4481e2) | ![image](https://github.com/brave/brave-core/assets/17010094/37cb881b-f375-46cd-9610-55a364d81fba)
-- | --|  --

---------------------

**Verification passed on**

Brave | 1.53.102 Chromium: 114.0.5735.133 (Official Build) (64-bit)
-- | --
Revision | `fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#18287](https://github.com/brave/brave-core/pull/18287)
- Verified banner has padding on portfolio page

![image](https://github.com/brave/brave-browser/assets/17010094/b03ccb46-b52a-4e23-8d2a-28c837fb3056) | ![image](https://github.com/brave/brave-browser/assets/17010094/0b2568d4-edc3-4c64-a498-0f6f6b7916ee) | ![image](https://github.com/brave/brave-browser/assets/17010094/5a8090f7-ae16-484a-8dc7-b769af82d9cb)
-- | -- | --
