### ISSUE TITLE
Hide network icon(1.51.x only)

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#30057]
![Image](https://user-images.githubusercontent.com/48117473/235157699-a4fea6d8-2adf-4bc8-821b-a4f6159bc6cf.png)

**Comment by kjozwiak** [comment]
Closing as https://github.com/brave/brave-core/pull/18296 was merged into `1.51.x`. The above will require `1.51.109` or higher for `1.51.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.51.109 Chromium: 113.0.5672.63 (Official Build) (64-bit)
-- | --
Revision | `0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}`
OS | Windows 11 Version 22H2 (Build 22621.1555)

- Verified network icon is not shown anymore on the NFT details screen. Just shows the token type
![8d1bPEafj8](https://user-images.githubusercontent.com/17010094/235583909-f976c23b-6960-4b49-8a90-7c14011413db.png)
