### ISSUE TITLE
Use Native mutation observer for playlist

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#30052]
This issue is a follow-up of https://github.com/brave/brave-browser/issues/29488

We might need to attach MutationObserver for the actual web contents managed by `TabStripMdel`. In that case, we should worry about performance of it. - related internall thread: https://bravesoftware.slack.com/archives/C3T9S9WKD/p1662544398836149

As per the thread, it's recommended to use native mutation observer, so we should try that.

Example:
https://github.com/chromium/chromium/blob/main/third_party/blink/renderer/core/exported/web_form_element_observer_impl.cc#L40-L62

**Comment by bsclifton** [comment]
Closing as the new approach we can use (injection-less) can detect the videos via Global Media Controls.
