### ISSUE TITLE
Follow up of #29842 - Make top of window resizable when Show title bar is disabled

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#30050]
## Description 

Filing a follow up for https://github.com/brave/brave-browser/issues/29842.  Unable to resize the window when `Show title bar` is  unchecked in `Tabs` section in brave://settings/appearance,   

## Steps to Reproduce

   1. Install 1.51.106
   2. launch Brave
   3. enable vertical tabs in brave://flags
   4. enable `Use vertical tabs` from context menu
   5. verified `Show title bar` is unchecked in brave://settings/appearance
   6. moved the mouse over the edge of the toolbar on the top 

## Actual result:

Resize cursor is not shown while mousing over the edge of the toolbar on the top and unable to resize the window. 
However, when the `Show title bar` was checked, able to resize the window
Able to resize the window in horizontal tab view as well   

https://user-images.githubusercontent.com/98358127/234992853-5c651f12-e0a6-4ca5-804a-4112a4997ccc.mp4

## Expected result:
Resize cursor should be shown and able to resize the window

## Reproduces how often: 

Easily 

## Brave version (brave://version info)

```
Brave | 1.51.106 Chromium: 113.0.5672.53 (Official Build) (64-bit)
-- | --
Revision | 12f5dac35d12e8f4e72d7dd11df557ef93bc046f-refs/branch-heads/5672@{#703}
OS | Windows 11 Version 22H2 (Build 22621.1555)
```
## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel?  Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
@rebron @sangwoo108 @kjozwiak 
cc: @brave/qa-team

**Comment by kjozwiak** [comment]
@MadhaviSeelam can you still reproduce this? Just curious as it's working on my machine using `1.53.30 Chromium: 113.0.5672.92`. Added an example below of me resizing the window while `Show title bar` was disabled. Let me know if I'm doing something wrong. I'm on `Win 11 x64` as well.

![resizeWindowTitlebar](https://github.com/brave/brave-browser/assets/2602313/531d6279-b917-469d-8586-8756a5f84e8f)

**Comment by MadhaviSeelam** [comment]
@kjozwiak  Still not working for me in Full screen in `1.53.30 Chromium: 113.0.5672.92`.  You may have to maximize the screen to see the issue. 


https://github.com/brave/brave-browser/assets/98358127/5ade4bed-2094-4011-8452-390947cc3962

**Comment by kjozwiak** [comment]
@GeetaSarvadnya hmm I see what you mean 👍 But you can't resize the window if it has the `Show title bar` enabled either. So I guess the issue is to remove the resizing icon when in full screen. For example, when you're in full screen mode while `Show title bar` is enabled, you won't get any resizing icons when getting near the border/edge of the window which indicates that the window can't be resized when it's in full screen mode. Does resizing for you work when you're not in full screen mode?

**Comment by MadhaviSeelam** [comment]
Closing the issue.  Able to resize the window when `Show title bar is disabled`.  


https://github.com/brave/brave-browser/assets/98358127/1145ff49-967c-4c93-8ed8-1fee32456ff4
