### ISSUE TITLE
[Android] Change "Tip" language to "Contribution" language and remove "One-time" language

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#30058]
General rules:

Replace "Tip" with "Contribution" where it makes sense (note pluralization)
Monthly Tips --> Monthly Contributions
Tipped --> Contributed
Send Tip --> Send Contribution

**Android version of: https://github.com/brave/brave-browser/issues/29603**

**Comment by vlad-hoff** [comment]
Verified on `Google Pixel 7` using version(s):
```
Device/OS: Google Pixel 7 [panther_beta-user 14 UPB2.230407.014 release-keys]
Brave build: 1.53.74
Chromium: 114.0.5735.53 (Official Build) beta (64-bit)
Revision: c499d7ea22c8b2dba278465a5df7b86a8efa4e64-refs/branch-heads/5735@{#970}
```
---------------------------

**STEPS:**
1. Launch Brave > Enable Rewards Staging in Dev options
2. Enable Rewards and connect custodian
3. Verify multiple spots according to https://github.com/brave/brave-browser/issues/30058#issuecomment-1551285633

**ACTUAL RESULTS:**
- Verified that `tip` was replaced with `contribution` where it makes sense (note pluralization)
- Verified that:
  - `Include in Auto-Contribute` [1]
  - `Monthly tip` removed [1]
  - `Send Tip` replaced with `Send Contribution` [1][2]
  - `Tip` replaced with `Contribute` [1][2][3]
  - `This Creator is not yet verified with Brave Creators. You'll be able to send them contributions once they're verified. Learn more` [2]
  - `Auto-Contribute` [3][10]
  - `One-Time Tips` replaced with `Contributions` [3][10]
  - `Monthly Tips` replaced with `Monthly Contributions` [3][10]
  - `Welcome! Users can support this content creator by sending them contributions. It's a way of thanking them for making great content.` [4]
  - `Can't send your contribution` [5]
  - `This creator is unable to receive contributions from <Custodian name>` [5]
  - `Brave collects 5% of the tip amount as a processing fee.` replaced with `Brave collects 5% of the sent amount as a processing fee.` [5][6][7]
  - `Set as monthly contribution` [6]
  - `Make this a monthly recurring contribution. You can cancel it at any time.` [7]
  - `Contribution sent!` [8]
  - `I just contributed <amount> BAT using the Brave Browser. See how you can support your favorite creators and sites too: https://brave.com/rewards` [9]
  - `Tips` replaced with `Contributions` [11]
  - `See the one-time tips you've given to websites and creators. Learn more about tipping.` replaced with `See the on-demand contributions you've given to websites and creators. Learn more about contributions.` [11]
  - `Total tips this month` replaced with `Total contributions this month` [11]
  - `Have you tipped your favorite content creator today?` replaced with `Have you contributed to your favorite content creator today?` [11]
  - `Monthly Tips` replaced with `Monthly Contributions` [11]
  - `Set up recurring monthly tips so you can  continually support your favorite creators.` replaced with `Set up recurring monthly contributions so you can  continually support your favorite creators.` [11]
  - `No monthly tips set up yet.` replaced with `No monthly contributions set up yet.` [11]

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/ff3ef526-d987-4f38-82bb-d1a4f2861ae4) | ![2](https://github.com/brave/brave-browser/assets/128532965/f354f4a5-80cf-4905-b296-dc25bd21daf0) | ![3](https://github.com/brave/brave-browser/assets/128532965/f4788200-7a4d-451b-b689-afb603f115a4) | ![4](https://github.com/brave/brave-browser/assets/128532965/f08d165b-5e62-423f-a6b8-39b413adb557) |
|5|6|7|8|
| ![1](https://github.com/brave/brave-browser/assets/128532965/b30eec96-0694-4cc0-bfbc-c55504fe9f74) | ![2](https://github.com/brave/brave-browser/assets/128532965/896e3d5b-22f6-4691-8cfb-729749bba4e0) | ![3](https://github.com/brave/brave-browser/assets/128532965/301e1c01-a408-468d-89c7-b4d62e011ee1) | ![4](https://github.com/brave/brave-browser/assets/128532965/0f15839d-8a92-4d0d-903c-f0b3cf6688d0) |
|9|10|11|12|
| ![1](https://github.com/brave/brave-browser/assets/128532965/af00c3fe-f147-4a24-ba3c-3500b5e1f1cb) | ![2](https://github.com/brave/brave-browser/assets/128532965/b3b0ce44-1030-4c02-b69f-a95617ef7505) | ![3](https://github.com/brave/brave-browser/assets/128532965/dc34eb78-2067-4b87-8690-92d83633b7a2) | ![4](https://github.com/brave/brave-browser/assets/128532965/1bcc352a-c22e-43ef-812e-0baa86ff2136) |
