### ISSUE TITLE
 `Send a tip` to verified publisher shows up incorrect a-c balance sometimes

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#3006]
## Description 
After `Send a tip` to verified publisher, the total a-c balance is shown incorrectly. For e.g if a-c balance is 35 BAT, after send a tip to verified publisher a-c balance shows up 69 BAT( sometimes 70 BAT). Sometimes this unknown value remained permanently. Even after page reload it doesn't change to correct value.

## Steps to Reproduce

   1. Clean Profile 0.59.25
   2. Enable Rewards through BR panel
   3. Claim UGP grants ( UGP grant was 35 BAT)
   4. Tip a verified site (for my test tip amount is 1 BAT)
   5. Reload the rewards page to see a-c balance

## Actual result:
a-c balance shows up as 69 BAT (sometimes 70 BAT) instead of 34 BAT.

## Expected result:
a-c should show correct total balance 

## Reproduces how often: 

Intermittent issue - 80% Reproducible rate

## Brave version (brave://version info)

Brave | 0.59.25 Chromium: 72.0.3626.53 (Official Build) beta (64-bit)
-- | --
Revision | 98434e6cd182d68ce396daa92e9c6310422e6763-refs/branch-heads/3626@{#620}
OS | Windows 10

### Reproducible on current release: no
- Does it reproduce on brave-browser dev/beta builds? yes 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? na
- Is the issue reproducible on the latest version of Chrome? na

### Additional Information
@brave/legacy_qa

**Comment by kjozwiak** [comment]
@GeetaSarvadnya if you have some time, mind editing the above and adding a GIF? Makes it easier understand the issue when there's a visual example. Screenshot will work as well 👍

**Comment by GeetaSarvadnya** [comment]
Unable to reproduce the issue now. Since there are no UGP grants just tried with recovering the wallet and sent tip to verified pus the account balance is displayed correctly.
