### ISSUE TITLE
Infinite loading on buy screen

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#30089]
## Description 
Infinite loading on buy screen (nightly).

## Actual result 
[Screencast from 02-05-23 02:01:07 PM IST.webm](https://user-images.githubusercontent.com/11755381/235618763-623960f5-dfbe-4bb6-a88d-415bc29094de.webm)

## Expected result
Should show/load buy assets.

## Issue reproduces how often 
easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version? Y

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
Version 1.53.10 Chromium: 113.0.5672.63 (Official Build) nightly (64-bit)

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.52.100 Chromium: 113.0.5672.92 (Official Build) beta (64-bit)
-- | --
Revision | b6f521170062a1fa8a82c33fb223b06fec566da1-refs/branch-heads/5672_63@{#10}
OS | Linux

- Verified steps from [brave/brave-core#18438](https://github.com/brave/brave-core/pull/18438)
- Verified there is no constant loading on Buy screen
- Verified Buy screen shows properly when navigated directly using routes in a new tab

https://github.com/brave/brave-browser/assets/17010094/cf4d9adb-7ea8-4797-8342-d48406110815
