### ISSUE TITLE
Remove unused divider in the main menu on NTP

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#30084]
## Description 
There is an excessive divider shown in the main menu on NTP
![Screenshot_20230501-184046](https://user-images.githubusercontent.com/30602739/235546185-9c59a518-1555-41c6-8b32-d7abc835aba2.png)

## Steps to reproduce 

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.52.103` or higher for `1.52.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using a `Google Pixel XL` (`arm64`) running `Android 9`

```
Brave	1.52.103 Chromium: 113.0.5672.126 (Official Build) beta (32-bit) 
Revision	c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}
OS	Android 9; Build/PQ2A.190305.002; 28; REL
```

### Steps:
1. installed `1.52.103`
2. launched Brave
3. tapped on the 3-dots menu
4. examined the menu items/separator lines

### Confirmed the extraneous separator line after `Recent Tabs` and before `Settings`, is removed

`brave://version` | `1.52.103` | `1.51.114`
---------|----------|---------
![Screenshot_20230519-045718](https://github.com/brave/brave-browser/assets/387249/ed40dfa3-a6ac-4d9c-8643-58082daf929b) | ![Screenshot_20230519-045401](https://github.com/brave/brave-browser/assets/387249/83ccccfb-5e60-4c37-b0d1-997cecae3727) | ![Screenshot_20230518-131348](https://github.com/brave/brave-browser/assets/387249/c4ca06bf-5e86-4531-9fef-3a349fe4e08c)
