### ISSUE TITLE
Add google play integrity implementation

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#30083]
This issue is to add google play integrity deps as safetynet is getting deprecated on june 2023. 
For more context :
API details : https://developer.android.com/google/play/integrity/overview
API deps : https://mvnrepository.com/artifact/com.google.android.play/integrity/1.1.0

**Comment by kjozwiak** [comment]
The above requires `1.53.102` or higher for `1.53.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Samsung Galaxy version 12` running `Bravemonoarm64.apk_1.53.102`

**Comment by Uni-verse** [comment]
Verification completed on `Samsung Galaxy S21` using the following build version(s):

```
Brave	1.53.104 Chromium: 115.0.5790.40 (Official Build) canary (32-bit) 
Revision	f9b78cf410ecd5b372310ef25a12ef456c77d90f-refs/branch-heads/5790@{#724}
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

Test Scenario: https://github.com/brave/internal/issues/1044#issuecomment-1598522330

- Installed `1.53.104 Chromium: 115.0.5790.40` (Custom rewards captcha build)
- enabled Developer options
    - enabled Use Rewards staging sever under QA Preferences
    - enabled Verbose Logs for Ad-Rewards under QA Preferences
- added --rewards=staging=true under Command Line Strings
- re-launched `1.53.104 Chromium: 115.0.5790.40`
- enabled Brave Reward via the panel
- retrieved the Rewards payment ID via brave://rewards-internals

Once the `Rewards payment ID` has been retrieved, flagged the ID using the following via the terminal/CLI:

`curl -XPUT -H "Authorization: Bearer {auth token}" -H "Content-Type: application/json" https://reputation.rewards.bravesoftware.com/v3/captcha/challenge/66854df0-1773-50b7-a33a-343692135110?type=3`

![Screenshot 2023-06-26 at 11 38 46 AM](https://github.com/brave/brave-browser/assets/17885425/e3e4d7b7-1b83-4738-ab73-3dd734b794e4)

![Screenshot 2023-06-26 at 6 49 09 PM](https://github.com/brave/brave-browser/assets/17885425/fec4eae6-f0f8-4520-a311-937e2011c6c7)


- Verified after scheduling captcha and serving ad event, the required captcha is solved
- Verified unblinded tokens were refilled.

**Comment by Uni-verse** [comment]
Verification completed on `Samsung Galaxy Tab S7` using the following build version(s):

```
Brave	1.53.104 Chromium: 115.0.5790.40 (Official Build) canary (32-bit) 
Revision	f9b78cf410ecd5b372310ef25a12ef456c77d90f-refs/branch-heads/5790@{#724}
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

Test Scenario: https://github.com/brave/internal/issues/1044#issuecomment-1598522330

- Installed `1.53.104 Chromium: 115.0.5790.40` (Custom rewards captcha build)
- enabled Developer options
    - enabled Use Rewards staging sever under QA Preferences
    - enabled Verbose Logs for Ad-Rewards under QA Preferences
- added --rewards=staging=true under Command Line Strings
- re-launched `1.53.104 Chromium: 115.0.5790.40`
- enabled Brave Reward via the panel
- retrieved the Rewards payment ID via brave://rewards-internals

Once the `Rewards payment ID` has been retrieved, flagged the ID using the following via the terminal/CLI:

`curl -XPUT -H "Authorization: Bearer {auth token}" -H "Content-Type: application/json" https://reputation.rewards.bravesoftware.com/v3/captcha/challenge/{Rewards payment ID}?type=3`

![Screenshot 2023-06-26 at 7 41 55 PM](https://github.com/brave/brave-browser/assets/17885425/c6776378-bb7a-42bd-bc8a-5639f33adc3c)

![Screenshot 2023-06-26 at 7 42 08 PM](https://github.com/brave/brave-browser/assets/17885425/b50e336d-89ea-4332-a8ec-26d9b19d0788)

- Verified after scheduling captcha and serving ad event, the required captcha is solved
- Verified unblinded tokens were refilled.
