### ISSUE TITLE
[FBD] Synchronize ephemeral and first party storage cleanup event

### ISSUE THREAD

**Issue by goodov** [brave/brave-browser#30090]
Modify ES cleanup event to trigger **after** 30 seconds the website is closed as discussed in the "Forget first party by default" PR: https://github.com/brave/brave-core/pull/16470#issuecomment-1433587516

This will allow us to perform cleanup for all parts (permissions, ephemeral storage, first party storage) at the same time.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.57.8 Chromium: 115.0.5790.75 (Official Build) beta (64-bit)
-- | --
Revision | 77bffd419b7e89d7e666c9695e7fa0d1d0367a99
OS | Windows 11 Version 22H2 (Build 22621.1992)
```

 Verification in progress using STR from https://github.com/brave/brave-browser/issues/30090#issuecomment-1587341331

Test Case 1 - Enabling `BraveForgetFirstPartyStorage` feature via Griffin 

Case 1 - Before feature being enabled via Griffin 
<details>

1. Installed 1.57.8
2. launched Brave 
3. confirmed `BraveForgetFirstPartyStorage` isn't visible under `brave://version`
4. visited github.com in a new tab
5. clicked Shields icon to open the Shields panel
6. opened brave://settings/shields

- Confirmed `Forget me when I close this site` toggle doesn't appear via the Shields panel
- Confirmed `Forget me when I close this site` toggle doesn't appear via `brave://settings/shields`

step 3 | step 5 | step 6
---- | ---- | ----
(https://github.com/brave/brave-browser/assets/98358127/d2f636cd-b53b-418a-919b-0752d1490634)|![image](https://github.com/brave/brave-browser/assets/98358127/42157faf-3ce3-4a61-b5f2-3027addf237a)|![image](https://github.com/brave/brave-browser/assets/98358127/37736a58-4e28-49bc-a8ad-0465f97cc9ae)

</details>

Case 2: Ensure feature being enabled via Griffin 
<details>

1. continue from Case 1: 
- `BraveForgetFirstPartyStorage` isn't visible under `brave://version`
-  `Forget me when I close this site` toggle doesn't appear via the Shields panel for nytimes.com
2. closed and restarted Brave using brave.exe --enable-logging=stderr
3. confirmed `BraveForgetFirstPartyStorage:Enabled` is shown in `brave://version`
4. opened Shields panel in the nytimes.com tab
5. opened brave://settings/shields

- Confirmed `Forget me when I close this site` toggle appears in the Shields panel and is `Off` by default
- Confirmed `Forget me when I close this site` toggle appears in the `brave://settings/shields` and is `Off` by default

step 3 | step 4 | step 5
---- | ---- | ----


light theme
shields panel | brave://settings/shields
--- | ---
![image](https://github.com/brave/brave-browser/assets/98358127/40f961ef-979d-4941-813b-466be22d97ef)|![image](https://github.com/brave/brave-browser/assets/98358127/0c4654b4-1bee-464a-a3fa-f5219fc80787)

</details>

Test Case 2:  Enable `Forget me when I close this site` setting in the Shields panel per domain

Case 1 - Enabling `Forget me when I close this site` setting in the Shields panel (Toggle per site/wait 30s) 
<details>

1. continue from Case 2 (Test Case 1)
    - `BraveForgetFirstPartyStorage` is shown under `brave://version`
    -  `Forget me when I close this site` toggle is shown via the Shields panel for nytimes.com
    -  `Forget me when I close this site` toggle is shown via `brave://settings/shields`
2.  logged into https://www.nytimes.com and saved password credentials 
3.  confirmed password credentials are saved in `brave://settings/passwords`
4.  confirmed `nytimes.com` entry is shown in `brave://settings/content/all`
5.  visited https://www.joinhoney.com and logged into the account 
6.  confirmed password credentials are saved in `brave://settings/passwords`
8. confirmed `joinhoney.com` entry is shown in `brave://settings/content/all`
9. restarted the browser and confirmed that I am still logged into both nytimes & joinhoney
10. toggle/enable `Forget me when I close this site` for nytimes.com  in the Shields panel and wait ~30 sec
11. toggle/enable `Forget me when I close this site` for joinhoney.com  in the Shields panel and wait ~30 sec
12. open `brave://settings/content/all` in a new tab
13. confirmed both `joinhoney.com` & `nytimes.com` have been completely removed from `brave://settings/content/all`
14. re-opened both https://joinhoney.com & https://www.nytimes.com sites
15. confirmed that I have been logged out of both the sites i.e. `joinhoney.com` & `nytimes.com` 
16. confirmed nytimes.com and Joinhoney.com entries haven't been removed/cleared from `brave://history` 
17. confirmed that passwords are not being removed via `brave://settings/passwords`


step 2 | step 3 | step 4 | step 5 | step 6 | step 7 | step 8a | step 8b | step 9 | step 10 | step 12 | step 14a | step 14b | step 15 | step 16
---  | --- | ---  | --- | --- | ---  | --- | --- | ---  | --- |--- | ---  | --- | ---  | ----

</details>

Case #2 - Enabling `Forget me when I close this site` setting in the Shields panel (Re-opening website within ~30s)

1. new profile 
2. launched Brave with `brave.exe --enable-logging=stderr `
3. relaunched Brave and verified followed: 
    - `BraveForgetFirstPartyStorage` is shown under `brave://version`
    -  `Forget me when I close this site` toggle is shown via `brave://settings/shields`
4.  logged into https://www.nytimes.com and saved password credentials 
5.  confirmed password credentials are saved in `brave://settings/passwords`
6.  confirmed `nytimes.com` entry is shown in `brave://settings/content/all`
7.  open the Shields panel for https://www.nytimes.com site and verified `Forget me when I close this site` toggle is `OFF`
8.   toggle `On`/enable `Forget me when I close this site` from step 7 
9.  close `https://www.nytimes.com` site 
10. quickly re-load the website within ~30s and verify you're still logged in
11. confirmed password credentials are still shown in `brave://settings/passwords`
12. confirmed `nytimes.com` entry is still shown in `brave://settings/content/all`
10. ran through this using different times. Example: 5s, 10s, 20s (ensured storage wasn't removed)
11. close https://www.nytimes.com and wait ~30s and ensure nytimes.com is removed from brave://settings/content/all
12. re-open https://www.nytimes.com/ and ensure that you're not logged into Gmail
ensure that brave://history hasn't been removed/cleared
13. confirmed that passwords are not being removed via brave://settings/passwords


`with in 30 sec`
step 3a | step 3b| step 4 | step 5 | step 6| step 7 | step 8 | step 9 | step 11 | step 12 
---- | ---- | ---- | ---- | ---- | ---- | ----- | ---- | ---- | ---- 




within 20s 
---- | ---- | ----
new profile 
verified with https://joinhoney.com
followed test steps from above and loaded the website within ~20 secs


example | example | example | example | example | example 
----- | ----- | ----- | ----- | ----- | -----



within 10s
new profile
verified with https://microsoft.com
followed test steps from above and loaded the website within ~10 secs

example | example | example | example | example | example 
----- | ----- | ----- | ----- | ----- | -----


within 5s
new profile 
https://bloomberg.com/ 
followed test steps from above and loaded the website within ~5 secs

example | example | example 
----- | ----- | -----

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.57.16 Chromium: 115.0.5790.98 (Official Build) beta (x86_64)
-- | --
Revision | d6c8a44fbe78ae6ee53d838307b4d17bec8de940
OS | macOS Version 11.7.8 (Build 20G1351)

**Comment by stephendonner** [comment]
Removing `QA/Blocked` per Slack conversation: https://bravesoftware.slack.com/archives/C7VLGSR55/p1690463757139679?thread_ts=1689815943.379709&cid=C7VLGSR55

**Comment by LaurenWags** [comment]
Per discussion with @rebron @pes10k @MadhaviSeelam @stephendonner @LaurenWags today, QA is going to skip tests that are associated with test pages (such as https://dev-pages.brave.software/storage/ephemeral-storage.html) as noted in https://github.com/brave/brave-browser/issues/30090#issuecomment-1587341331. 

@pes10k noted via https://bravesoftware.slack.com/archives/C7VLGSR55/p1690918874502599?thread_ts=1689815943.379709&cid=C7VLGSR55 that this unintentionally overloads this test page and FBD + Ephemeral Storage should have their own specific (and likely separate) test page(s). When @goodov returns from PTO, @pes10k has graciously offered to sync up so that this can be sorted out (thank you!).

Once FBD + Ephemeral Storage tests are in place, QA can then verify, although this likely will not be in time for the initial 1.57.x release. During today's call risk for skipping these tests was deemed minimal so the group was comfortable delaying this testing until later.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.57.36 Chromium: 115.0.5790.171 (Official Build) beta (64-bit) 
Revision	a4bb683f14dc402f5da13707e13559dc4d5ef08b
OS	Linux
```

**Comment by Uni-verse** [comment]
Verified for `1.57.x` on `Android` using the following devices:

`Samsung Galaxy S21 (ARM64)` - https://github.com/brave/brave-browser/issues/26465#issuecomment-1674976786
`Samsung Galaxy Tab S7 (ARM64)` - https://github.com/brave/brave-browser/issues/26465#issuecomment-1674979766
`Pixel 5 (x86)` - https://github.com/brave/brave-browser/issues/26465#issuecomment-1675301831
