### ISSUE TITLE
NFT image is not loaded in Panel

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#30091]
## Description 

NFT image is not loaded in Panel

## Steps to Reproduce

   1. Add Solana NFT from mainnet
   2. Open Wallet panel and load the assets
   3. NFT image is not loaded 

## Actual result:

![ApplicationFrameHost_BE3lajmtN6](https://user-images.githubusercontent.com/17010094/235702774-3f43dd32-8f2c-41ab-a572-8ea149e702ec.png)

## Expected result:
Should show image

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.51.109 Chromium: 113.0.5672.63 (Official Build) (64-bit)
-- | --
Revision | `0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}`
OS | Windows 11 Version 22H2 (Build 22621.1344)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Not checked
- Can you reproduce this issue with the nightly channel? Not checked

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @nvonpentz

**Comment by josheleonard** [comment]
Closing - The latest panel UI correctly renders Solana NFTs 

![Image](https://github.com/brave/brave-browser/assets/30185185/dee54620-a553-4870-981a-8aa17e59d7a4)
