### ISSUE TITLE
Add empty state shown when NFT auto discovery is enabled

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#30105]
Figma link: https://www.figma.com/file/mvoB5HzIyQT9O4vbcA1XhP/NFT-Tab?type=design&node-id=220%3A97408&t=rfTOXewYHfCvW9TG-1

**Comment by srirambv** [comment]
Verification passed on  

Brave | 1.53.94 Chromium: 114.0.5735.133 (Official Build) beta (64-bit)
-- | --
Revision | `fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}`
OS | Windows 11 Version 22H2 (Build 22621.1848) 

- Verified steps from [brave/brave-core#18344](https://github.com/brave/brave-core/pull/18344)
- Verified new placeholder empty state is shown when there are no NFTs added 

Light | Dark
-- | --
![brave_4yLOQkJ9qp](https://github.com/brave/brave-browser/assets/17010094/f9011f88-c369-4039-90eb-54629c5db0a6) | ![brave_L3RqoOSV6H](https://github.com/brave/brave-browser/assets/17010094/c62241cf-ffe1-4175-99ab-a273369c33f1)
