### ISSUE TITLE
Rounded corners for panels on Windows show a solid background and aren't transparent

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#30106]
Example on Rewards panel:

![image](https://user-images.githubusercontent.com/11497541/235929400-09a87b69-6c41-4500-bb79-2746dbd978ec.png)

Apparently this is also the case on the Contribution Banner 3.0.

**Comment by mkarolin** [comment]
Please, verify on all Desktop platforms, but on Windows both 10 and 11 need to be checked.

Test plan:
1. Start Brave
2. Join Rewards
3. Navigate to a verified publisher site
4. Open tipping banner
5. Verify that the banner's corners don't show drawing artifacts

**Comment by LaurenWags** [comment]
Removed `OS/Windows` and added `QA/Test-All-Platforms` per https://github.com/brave/brave-browser/issues/30106#issuecomment-1536530799

**Comment by kjozwiak** [comment]
The above requires `1.52.95` or higher for `1.52.x` verification 👍

**Comment by LaurenWags** [comment]
Removed `QA/Test-All-Platforms` as additional fixes for rounded corners are pending uplift to 1.52.x for https://github.com/brave/brave-browser/issues/30489.

As such, the testing for #30489 will supersede this one, so #30489 is marked `QA/Test-All-Platforms` and will be tested once uplifted to 1.52.x.
