### ISSUE TITLE
Update Wallet Scroll Behavior

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#30103]
## Description 

We need to update the `Scroll Behavior` in the wallet to match the new design in Figma

- Container Card should no longer be a fixed height
- Content should scroll inside to the top of the Container Card
- `Side Nav` and `Header` should stay fixed.

![Screenshot 35](https://user-images.githubusercontent.com/40611140/235832156-1815789d-c00c-4537-9374-9e206ed914c4.png)

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.53.102 Chromium: 114.0.5735.133 (Official Build) (64-bit)
-- | --
Revision | `fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}`
OS | Linux

- Verified steps from [brave/brave-core#18370](https://github.com/brave/brave-core/pull/18370)
- Verified `Portfolio`, `Assets`, `NFTs` page scroll as a whole and not just the container
- Verified reducing the browser width causes side navigation to be moved to the bottom. Verified as part of [#30433 (comment)](https://github.com/brave/brave-browser/issues/30433#issuecomment-1600686441)

https://github.com/brave/brave-browser/assets/17010094/c1bc2b77-c051-4509-96f9-adbfb95f522a

---------------------

**Verification passed on**

Brave | 1.53.102 Chromium: 114.0.5735.133 (Official Build) (64-bit)
-- | --
Revision | `fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}`
OS | Windows 11 Version 22H2 (Build 22621.1848)

- Verified steps from [brave/brave-core#18370](https://github.com/brave/brave-core/pull/18370)
- Verified `Portfolio`, `Assets`, `NFTs` page scroll as a whole and not just the container
- Verified reducing the browser width causes side navigation to be moved to the bottom. Verified as part of [#30433 (comment)](https://github.com/brave/brave-browser/issues/30433#issuecomment-1600686441)

https://github.com/brave/brave-browser/assets/17010094/6feb16ff-db38-46cf-938d-4c343c66a212

---------------------

**Verification passed on**

Brave | 1.53.102 Chromium: 114.0.5735.133 (Official Build) (64-bit)
-- | --
Revision | `fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#18370](https://github.com/brave/brave-core/pull/18370)
- Verified `Portfolio`, `Assets`, `NFTs` page scroll as a whole and not just the container
- Verified reducing the browser width causes side navigation to be moved to the bottom. Verified as part of [#30433 (comment)](https://github.com/brave/brave-browser/issues/30433#issuecomment-1600686441)

https://github.com/brave/brave-browser/assets/17010094/4a6e03ea-527a-4d00-bc97-3974e620a73f
