### ISSUE TITLE
Some sidebar panels should be tab-specific

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#30119]
As suggested by @aguscruiz , some sidebar panels should only be activated for the "current" tab. When the active tab is changed, the active sidebar panel should be restored to any "global" sidebar panel state, which could be either a non-tab-specific sidebar panel being active, or no panel being active.

This would apply to any panels which are specific to the Tab, such as:
- Brave News feed
- AIChat summarizer

**Comment by petemill** [comment]
This has to be QA'ed against nightly for now, where AI Chat (the only use of this feature, currently) is pinned.

**Comment by LaurenWags** [comment]
Labeling as `QA/Blocked` for now, @kjozwiak to provide additional information.

Also updated to `release-notes/exclude`.

**Comment by LaurenWags** [comment]
@brave/qa-team removed `QA/Blocked` - this one can be verified on Nightly per discussions under  https://bravesoftware.slack.com/archives/C04KPE0BUDU/p1693665530143249?thread_ts=1688150893.428279&cid=C04KPE0BUDU.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.59.76 Chromium: 116.0.5845.163 (Official Build) nightly (64-bit)
-- | --
Revision | 882a1d617108cea1c78439e27c5f19c46b276508
OS | Windows 10 Version 22H2 (Build 19045.3393)
```
