### ISSUE TITLE
[hackerone] Brave Wallet pop-up hides `fullscreen` toast

### ISSUE THREAD

**Issue by stoletheminerals** [brave/brave-browser#30113]
https://hackerone.com/reports/1954620

We should displace Brave Wallet pop-up so it doesn't hide other browser toasts.

**Comment by diracdeltas** [comment]
@jamesmudgett can we get some design help to come up with a way of showing brave wallet popups that don't interfere with other popups (like the fullscreen toast)?

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.58.117 x64 build. Verification notes can be found [here](https://github.com/brave/internal/issues/1073#issuecomment-1713290806)
