### ISSUE TITLE
"IPFS Gateway" toggle switch is self-disabling when a user is leaving the settings

### ISSUE THREAD

**Issue by vlad-hoff** [brave/brave-browser#30116]
## Description 

The "IPFS Gateway" toggle switch is self-disabling when a user is leaving the settings

## Steps to reproduce 

   1. Launch Brave > Hamburger Menu > Settings
   2. Brave Shields & privacy
   3. Find `IPFS Gateway` and enable it
   4. Go back to a previous screen or close and reopen settings > Observe `IPFS Gateway` toggle switch is OFF

## Actual result 

The "IPFS Gateway" toggle switch is self-disabling when a user is leaving the settings

https://user-images.githubusercontent.com/128532965/236053303-5f11f115-0159-4570-b4b1-c575fbaf0dc5.mp4

## Expected result

When the user enables the `IPFS Gateway` setting then leaves the settings and returns back to it, `IPFS Gateway` toggle switch must be ON

## Issue reproduces how often 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? YES
- Can you reproduce this issue with the current Play Store Beta version? NO
- Can you reproduce this issue with the current Play Store Nightly version? NO

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Galaxy Tab S8 [Tablet]
   - Android version: Android 13 [gts8wifixx-user 13 TP1A.220624.014 release-keys]
   
## Brave version

1.51.110 Chromium: 113.0.5672.77 (Official Build) (32-bit)
1.50.121 Chromium: 112.0.5615.138 (Official Build) (32-bit)

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
@vlad-hoff mind checking this one again? Possibly related to https://github.com/brave/brave-browser/issues/29647 which was already fixed via `1.52.x`. Could be a duplicate.

**Comment by vlad-hoff** [comment]
I just checked it in Beta 1.52.92. IPFS switch is set to ON now by default, and the issue is not reproducible.

https://github.com/brave/brave-browser/assets/128532965/a5da3800-7197-48c2-893d-cc617b595597

**Comment by deeppandya** [comment]
> I just checked it in Beta 1.52.92. IPFS switch is set to ON now by default, and the issue is not reproducible.
> 
> https://github.com/brave/brave-browser/assets/128532965/a5da3800-7197-48c2-893d-cc617b595597
> 
> 
> 

Thank you @vlad-hoff for checking

**Comment by vlad-hoff** [comment]
Marked this issue as a duplicate of #29647
