### ISSUE TITLE
Use localhost-permission-allow-list.txt to decide which websites to prompt for

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#30121]
If localhost permission is not already given, only prompt if requesting URL is on allowlist which will be shipped as a component update. 

1. This list will live at https://github.com/brave/adblock-lists/tree/master/brave-lists. PR: https://github.com/brave/adblock-lists/pull/1156
2. The `localhost-permission-allow-list.txt` will be bundled in `Brave Local Data Updater` similar to `debounce.json` or `https-exceptions-list.txt`. PR: https://github.com/brave/brave-core-crx-packager/pull/620
3. Currently localhost connections are blocked via adblock: https://github.com/brave/adblock-lists/blob/master/brave-lists/brave-specific.txt#L1-L12. We will remove those once we have the new list in place.

If a user goes into brave://settings/content/localhostAccess and adds a website to Allow or Deny we should honour that first.

**Comment by kjozwiak** [comment]
@brave/qa-team this one can be completed at the same alongside https://github.com/brave/brave-browser/issues/30151.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.53.76 Chromium: 114.0.5735.90 (Official Build) beta (64-bit)
-- | --
Revision | 386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}
OS | Windows 10 Version 22H2 (Build 19045.3031)

### Steps:
1. installed `1.53.76`
2. launched Brave
3. opened `brave://flags`
4. toggled `brave://flags/#brave-localhost-access-permission` to `Enabled`
5. clicked on `Relaunch`
6. shut down Brave
7. added `https://shivankaul.com/brave/localhost/` to `localhost-permission-allow-list.txt` in `C:\Users\steph\AppData\Local\BraveSoftware\Brave-Browser-Beta\User Data\afalakplffnnnlkncjhbmahjfjhmlkal\1.0.342\1`
8. ...

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 



Brave | 1.53.81 Chromium: 114.0.5735.90 (Official Build) beta (x86_64)
-- | --
Revision | 386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}
OS | macOS Version 11.7.7 (Build 20G1345)



### Shared Steps:
<details>

1. installed `1.53.81`
2. launched Brave
3. set `brave://flags/#brave-localhost-access-permission` to `Enabled`
4. clicked `Relaunch`
5.  added the following:
  ```
  # https://shivankaul.com/brave/localhost/
  shivankaul.com
  ```
6. to `localhost-permission-allow-list.txt` in `C:\Users\steph\AppData\Local\BraveSoftware\Brave-Browser-Beta\User Data\afalakplffnnnlkncjhbmahjfjhmlkal\1.0.342\1`
7. created a `tests` dir on my desktop
8. placed a `logo.png` file in the same directory
9. ran `python3 -m http.server 8000`, also from `tests`

example | example | example
----------|----------|-----------



</details>

### Subresource test - `PENDING`
<details>

(continued from `Shared Steps`)

1. added `@@||localhost^$domain=shivankaul.com` to `Create custom filters` in `brave://settings/shields/filters`
2. loaded `https://shivankaul.com/brave/localhost/subresource.html`
3. confirmed I was prompted to `Allow` or `Block`
4. clicked `Allow`
5. confirmed my `logo.png` loaded
6. confirmed `https://shivankaul.com:443` appeared under `Allowed to access localhost resources`, in `brave://settings/content/localhostAccess`
7. repeated, this time clicking `Block`
8. confirmed `logo.png` showed a broken-image placeholder
9. confirmed `https://shivankaul.com:443` appeared under `Not allowed to access localhost resources` in `brave://settings/content/localhostAccess`

`Custom filter rule`| `localhost-permission prompt` | `Allow`ed | `Block`ed | `Allowed to access...` | `Not allowed to access...`
---------|------------|----------|----------|-------|----------




</details>

### iframe test - `PENDING`
<details>

(continued from `Shared Steps`)

1. loaded `https://shivankaul.com/brave/localhost/iframe.html`
2. confirmed I was prompted to `Allow` or `Block`
3. clicked `Allow`
4. confirmed my `logo.png` loaded
5. confirmed `https://shivankaul.com:443` appeared under `Allowed to access localhost resources`, in `brave://settings/content/localhostAccess`
6. repeated, this time clicking `Block`
7. confirmed `logo.png` showed a broken-image placeholder
8. confirmed `https://shivankaul.com:443` appeared under `Not allowed to access localhost resources` in `brave://settings/content/localhostAccess`

`Custom filter rule`| `localhost-permission prompt` | `Allow`ed | `Redirect` | `Block`ed | `Allowed to access...` | `Not allowed to access...`
---------|------------|----------|----------|-------|----------|-----------





</details>

### localhostAccess-priority test - `PENDING`
<details>

(continued from `Shared Steps`)

### `Allowed` test case

1. added `shivankaul.com` to `Allowed to access localhost resources`, in `brave://settings/content/localhostAccess`
2. loaded `https://shivankaul.com/brave/localhost/subresource.html`
3. confirmed no localhost-permissions prompt dialog

### Confirmed `logo.png` rendered

example | example
----------|---------


### `Not allowed` test case

1. added `shivankaul.com` to `Not allowed to access localhost resources` in `brave://settings/content/localhostAccess`
2. loaded `https://shivankaul.com/brave/localhost/subresource.html`
3. confirmed no localhost-permissions prompt dialog

### Confirmed `logo.png` didn't render; only a broken-image icon, in its place

example | example
----------|-----------



</details>

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.53.85 Chromium: 114.0.5735.110 (Official Build) beta (64-bit)
-- | --
Revision | 1c828682b85bbc70230a48f5e345489ec447373e-refs/branch-heads/5735_90@{#13}
OS | Linux
```

### Shared Steps:
<details>

1. installed `1.53.85`
2. launched Brave
3. set `brave://flags/#brave-localhost-access-permission` to `Enabled`
4. clicked `Relaunch`
5.  added the following:
  ```
  # https://shivankaul.com/brave/localhost/shivankaul.com
  ```
6. to `localhost-permission-allow-list.txt` in `/home/braveubuntu/.config/BraveSoftware/Brave-Browser-Beta/afalakplffnnnlkncjhbmahjfjhmlkal/1.0.348/1`
7. created a `tests` dir on my desktop
8. placed a `logo.png` file in the same directory
9. ran `python3 -m http.server 8000`, also from `tests`

example | example | example
----------|----------|-----------
![Screenshot from 2023-06-08 15-39-59](https://github.com/brave/brave-browser/assets/98358127/10857aee-a567-4873-9443-eda285ca1a80)|![Screenshot from 2023-06-08 15-46-46](https://github.com/brave/brave-browser/assets/98358127/da2b3ec8-af90-4a8d-b260-c7b4e45f2ba7)|![Screenshot from 2023-06-08 16-02-05](https://github.com/brave/brave-browser/assets/98358127/534dd0ce-c1fb-4469-96d5-6c8aa9d4f1a7)
</details>

### Subresource test - `PASSED`
<details>

(continued from `Shared Steps`)

1. added `@@||localhost^$domain=shivankaul.com` to `Create custom filters` in `brave://settings/shields/filters`
2. loaded `https://shivankaul.com/brave/localhost/subresource.html`
3. confirmed I was prompted to `Allow` or `Block`
4. clicked `Allow`
5. confirmed my `logo.png` loaded
6. confirmed `https://shivankaul.com:443` appeared under `Allowed to access localhost resources`, in `brave://settings/content/localhostAccess`
7. repeated, this time clicking `Block`
8. confirmed `logo.png` showed a broken-image placeholder
9. confirmed `https://shivankaul.com:443` appeared under `Not allowed to access localhost resources` in `brave://settings/content/localhostAccess`

`Custom filter rule`| `localhost-permission prompt` | `Allow`ed | `Block`ed | `Allowed to access...` | `Not allowed to access...`
---------|------------|----------|----------|-------|----------
![Screenshot from 2023-06-08 16-05-37](https://github.com/brave/brave-browser/assets/98358127/91e8d1e5-197d-4b1b-b5ac-c447f1587d00)|![Screenshot from 2023-06-08 16-13-36](https://github.com/brave/brave-browser/assets/98358127/19aef168-c14c-4524-8037-f6d490658609)|![Screenshot from 2023-06-08 16-29-47](https://github.com/brave/brave-browser/assets/98358127/a124251a-7d60-461f-ab08-2bdb5dbd2417)|![Screenshot from 2023-06-08 16-30-25](https://github.com/brave/brave-browser/assets/98358127/049a2528-2e18-4c3c-a7b0-39418ad928bc)|![Screenshot from 2023-06-08 16-29-54](https://github.com/brave/brave-browser/assets/98358127/b608921f-390c-478d-ab28-c460e59b18cb)|![Screenshot from 2023-06-08 16-30-33](https://github.com/brave/brave-browser/assets/98358127/9c960728-b894-4d65-9a35-a1e446ae2248)
</details>
