### ISSUE TITLE
Properly patch `Web Store` link in brave://extensions

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#3012]
## Test plan
See https://github.com/brave/brave-core/pull/1615

## Description
As @bridiver commented https://github.com/brave/brave-core/pull/1364#discussion_r248752525 this change needs to be externalized to simplify patching.

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.63.4 Chromium: 73.0.3683.67 (Official Build) dev (64-bit)
-- | --
Revision | a83fd4f3207ae83412d329a9ca1239dd1e068345-refs/branch-heads/3683@{#760}
OS | Windows 7 Service Pack 1 Build 7601.24312

Used test plan from https://github.com/brave/brave-core/pull/1615

![image](https://user-images.githubusercontent.com/34715963/54252341-b189b800-454a-11e9-9728-8fbf7aec14ff.png)
![image](https://user-images.githubusercontent.com/34715963/54252524-7b990380-454b-11e9-9736-5b945e52bfd5.png)
![image](https://user-images.githubusercontent.com/34715963/54252551-98cdd200-454b-11e9-8888-7557f1920f48.png)
