### ISSUE TITLE
Build out reusable card header

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#30120]
## Description 

We need to build out a `Card Header` that can be reused throughout the `Wallet`.

![Screenshot 38](https://user-images.githubusercontent.com/40611140/236106828-5c84d336-2feb-48ce-921a-fd59e2277147.png)

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.53.102 Chromium: 114.0.5735.133 (Official Build) (64-bit)
-- | --
Revision | `fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}`
OS | Linux

- Verified steps from [brave/brave-core#18416](https://github.com/brave/brave-core/pull/18416)
- Verified header card is always shown when scrolling 

https://github.com/brave/brave-browser/assets/17010094/813fa3ae-c6a5-4248-926c-878aa69bed35


---------------------

**Verification passed on**

Brave | 1.53.102 Chromium: 114.0.5735.133 (Official Build) (64-bit)
-- | --
Revision | `fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}`
OS | Windows 11 Version 22H2 (Build 22621.1848)

- Verified steps from [brave/brave-core#18416](https://github.com/brave/brave-core/pull/18416)
- Verified header card is always shown when scrolling 

https://github.com/brave/brave-browser/assets/17010094/3eb7844f-763c-47cc-b694-92b11ad1858c


---------------------

**Verification passed on**

Brave | 1.53.102 Chromium: 114.0.5735.133 (Official Build) (64-bit)
-- | --
Revision | `fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#18416](https://github.com/brave/brave-core/pull/18416)
- Verified header card is always shown when scrolling 

https://github.com/brave/brave-browser/assets/17010094/f25da205-a2e5-472d-a131-9019cadbd3a2
