### ISSUE TITLE
brave://welcome not displayed for fresh installs/profiles

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#30139]
## Description 

Clean installs of Beta (1.52.x) and Nightly (1.53.x) do not show brave://welcome on a fresh install/profile, just the new tab page is displayed.

## Steps to Reproduce

   1. Remove any existing profile for Beta or Nightly
   2. Install/launch latest 1.52.x or 1.53.x

## Actual result:

New tab page is displayed

<img width="1199" alt="Screenshot 2023-05-04 at 11 44 58 AM" src="https://user-images.githubusercontent.com/28145373/236259865-d54a5008-4218-4044-b02d-4fe96c1ea00d.png">

## Expected result:

brave://welcome should be displayed

<img width="1258" alt="Screenshot 2023-05-04 at 11 43 47 AM" src="https://user-images.githubusercontent.com/28145373/236259926-753c84c1-82a8-4f71-a603-77b866b0e385.png">

## Reproduces how often: 

easily

## Brave version (brave://version info)

Brave | 1.52.86 Chromium: 113.0.5672.77 (Official Build) beta (x86_64)
-- | --
Revision | c4236862955e005c2187105415ac4a2ecf86dff1-refs/branch-heads/5672_62@{#3}
OS | macOS Version 13.3.1 (Build 22E261)

Brave | 1.53.18 Chromium: 113.0.5672.77 (Official Build) nightly (x86_64)
-- | --
Revision | c4236862955e005c2187105415ac4a2ecf86dff1-refs/branch-heads/5672_62@{#3}
OS | macOS Version 13.3.1 (Build 22E261)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no, does not reproduce with 1.51.110
- Can you reproduce this issue with the beta channel? yes 1.52.86
- Can you reproduce this issue with the nightly channel? yes 1.53.18

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

reproduced by @stephendonner 

cc @rebron

**Comment by LaurenWags** [comment]
Might be intermittent? have tried multiple times, and usually no brave://welcome, but sometimes it does show.

**Comment by kjozwiak** [comment]
Adding `release/blocking` till we know more re: what's happening. We'll definitely want to make sure that `brave://welcome` is appearing as expected for new installs. Releasing with the above intermittent issue could impact retention so this will need to be addressed.

**Comment by rebron** [comment]
cc: @wknapik reproduced on Linux and @LaurenWags on macOS Intel. Haven't been able to reproduce on Windows yet.

**Comment by bsclifton** [comment]
Quick note - I am not able to reproduce on Windows. @simonhong tried Linux and macOS and was not able to reproduce

@LaurenWags @wknapik when you all are running into this, you're deleting the profile directory beforehand?

**Comment by LaurenWags** [comment]
@bsclifton I was removing profile folder from `~/Library/Application Support/BraveSoftware` and cache from `~/Library/Caches/BraveSoftware` which is all I usually do when creating new profiles.

**Comment by simonhong** [comment]
@wknapik @LaurenWags Still reproducible? I tested on my all machines (Win11, macOS, Ubuntu) and I didn't see this issue..

**Comment by LaurenWags** [comment]
@simonhong yes, I just experienced it with beta built yesterday, 1.52.94.

**Comment by simonhong** [comment]
I'm seeing this also with local build in linux.
When this happens, `base::FeatureList::IsEnabled(kForYouFre);` gives true during the session.
In the relaunching after this happens, welcome page is shown even it's not the first run.
It's weird because we disabled `kForYouFre` feature by default. Investigating more..

**Comment by simonhong** [comment]
@rebron @kjozwiak @LaurenWags I found that upstream has client-side field trial for `kForYouFre`.
If `kForYouFre` feature is enabled, welcome page is not shown at first run.
and we've been disabled that feature.

According to the below method, beta & nightly has 50:50 enabling probability.
So, this issue was not reproduced always.
```
std::string PickTrialGroupWithoutActivation(base::FieldTrial& trial,
                                            version_info::Channel channel) {
  int enabled_percent;
  int disabled_percent;
  int default_percent;
  switch (channel) {
    case version_info::Channel::UNKNOWN:
    case version_info::Channel::CANARY:
    case version_info::Channel::DEV:
    case version_info::Channel::BETA:
      enabled_percent = 50;
      disabled_percent = 50;
      default_percent = 0;
      break;
    case version_info::Channel::STABLE:
      // Disabled on stable pending approval. http://launch/4200918
      enabled_percent = 0;
      disabled_percent = 0;
      default_percent = 100;
      break;
  }
  DCHECK_EQ(kTotalProbability,
            enabled_percent + disabled_percent + default_percent);

  trial.AppendGroup(kEnabledGroup, enabled_percent);
  trial.AppendGroup(kDisabledGroup, disabled_percent);
  trial.AppendGroup(kDefaultGroup, default_percent);

  return trial.GetGroupNameWithoutActivation();
}
```
As stable channel always use default value(disabled) 100%.
this will not be happened on stable with current implementation.
Pushed https://github.com/brave/brave-core/pull/18476 for preventing default value overriding.

**Comment by LaurenWags** [comment]
Added `QA/Blocked` until uplifted to 1.52.x

**Comment by kjozwiak** [comment]
The above requires `1.52.101` or higher for `1.52.x` verification 👍 Removing `QA/Blocked`.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.52.101 Chromium: 113.0.5672.92 (Official Build) beta (x86_64)
-- | --
Revision | b6f521170062a1fa8a82c33fb223b06fec566da1-refs/branch-heads/5672_63@{#10}
OS | macOS Version 11.7.6 (Build 20G1231)

### Steps:
1. installed `1.52.101`
2. launched Brave via `commandline` (`./Brave Beta`) -and-
3. launched Brave using the app icon in macOS's `Dock`
4. confirmed in both launch cases that the `brave://welcome` screen was shown
5. removed profile using `rm -rf /Users/stephendonner/Library/Application\ Support/BraveSoftware/Brave-Browser-Beta`
6. repeated steps 2-5 10-15x for each launch type

### Confirmed `brave://welcome` always loaded after removing profile and relaunching, via both methods mentioned above

<img width="1360" alt="Screen Shot 2023-05-17 at 3 50 58 PM" src="https://github.com/brave/brave-browser/assets/387249/b634ea46-e527-4968-92cc-36cd1824ae41">
