### ISSUE TITLE
Old icons in rewards settings in 0.59.x

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#3013]
Follow up from https://github.com/brave/brave-browser/issues/1825

## Steps to Reproduce

   1. open `brave://rewards`
   2. Turn off rewards

## Actual result:

![image](https://user-images.githubusercontent.com/34715963/51357706-7e81f580-1ac0-11e9-8d8b-e3aeb00b9dc6.png)

## Expected result:
![image](https://user-images.githubusercontent.com/34715963/51357731-9b1e2d80-1ac0-11e9-84bf-be064a80f688.png)

## Brave version (brave://version info)

Brave | 0.59.25 Chromium: 72.0.3626.53 (Official Build) beta (64-bit)
-- | --
Revision | 98434e6cd182d68ce396daa92e9c6310422e6763-refs/branch-heads/3626@{#620}
OS | Windows 7

Not reproducible in 0.60.15 Windows 7

cc @brave/legacy_qa @NejcZdovc @ryanml

**Comment by ryanml** [comment]
All we should need to do for this one is uplift the brave-ui update.

Only issue is, Ads aren't on 59.x yet, so the update would remove the Coming Soon text, which may be an issue. cc: @NejcZdovc @btlechowski

**Comment by NejcZdovc** [comment]
I think it's fine if we just not do this in 0.59

**Comment by srirambv** [comment]
I agree with @NejcZdovc . 

cc: @rebron to take call on keeping the issue open

**Comment by NejcZdovc** [comment]
closing for now, we can reopen it if needed
