### ISSUE TITLE
When a monthly tip is set up for a publisher, the one-time tip is sent automatically.

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#30132]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/29302
When a monthly tip is set up for a publisher, the one-time tip is sent automatically.

## Steps to Reproduce

   1. Clean profile 1.52.x
   2. Enable rewards and connect to a custodian
   3. Open a verified pubs laurenwags.github.io
   4. Open BR panel and click on `Send Contributions`
   5. In the BR panel, select any default tip OR click on the custom and enter the custom tip amount and click on the `Send` buttom
   6. Go to brave://rewards page
   7. Monthly tip and one time tip are displayed in their respective panels

## Actual result:

When a monthly tip is set up for a publisher, the one-time tip is sent automatically.

![30132](https://user-images.githubusercontent.com/38657976/236168668-930642bf-51f0-4e33-ad0a-b1144a8130f1.gif)

## Expected result:
When a monthly tip is set up for a publisher, the one-time tip should not be sent automatically.

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.52.85 Chromium: 113.0.5672.63 (Official Build) beta (64-bit)
-- | --
Revision | 0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}
OS | Windows 10 Version 21H2 (Build 19044.2846)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @Miyayes @zenparsing

**Comment by Miyayes** [comment]
This is intended change. Setting up monthly tip is just an option on a one-time tip.
