### ISSUE TITLE
Improve text on aggressive mode interstitial to explain link to aggressive mode

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#30142]
Some users are surprised when they see the interstitial appear in aggressive mode.

https://bravesoftware.slack.com/archives/C6YNM6Y5S/p1683211033792949

It would be good to add additional text stating (straw text)
- this is because of aggressive mode
- brave by default protects your privacy on every site you visit
- this dialog is an extra aggressive warning that you're visiting a site that may be privacy-hostile

**Comment by pilgrim-brave** [comment]
Proposed text: "Because you requested to aggressively block trackers and ads, Brave is blocking this site before the first network connection."

<img width="1712" alt="Screenshot 2023-06-02 at 11 26 51 AM" src="https://github.com/brave/brave-browser/assets/43750833/664514ca-5a79-403c-825d-0b8366bd5b52">

**Comment by LaurenWags** [comment]
@pilgrim-brave @pes10k could one of you please provide a test plan for this one as it's labeled `QA/Yes`. Thanks!

**Comment by pes10k** [comment]
@LaurenWags this should work:

1. visit https://antitracking.owncast.online/ with aggressive blocking
2. verify that the text has been changed and matches @pilgrim-brave 's screenshot above

**Comment by LaurenWags** [comment]
Thanks @pes10k!

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.57.2 Chromium: 115.0.5790.56 (Official Build) beta (x86_64)
-- | --
Revision | ebcfb87c1393f36955cfa2f6451a1767e3dc3ee5-refs/branch-heads/5790@{#1193}
OS | macOS Version 11.7.8 (Build 20G1351)

### Steps:
1. installed `1.57.2`
2. launched Brave
3. loaded `https://antitracking.owncast.online/`
4. confirmed no interstitial-blocking message
5. switched to `Aggressively block trackers & ads` in the Shields dropdown
6. confirmed page reloaded, now with intersitial-blocking message
7. clicked on `Proceed`
8. confirmed I was shown `https://antitracking.owncast.online/` without the interstitial

example | example | example | example | example
---------|----------|---------|----------|--------
<img width="1583" alt="Screen Shot 2023-07-07 at 11 47 31 PM" src="https://github.com/brave/brave-browser/assets/387249/8d588600-307c-49d0-bf54-4531bb52e2de"> | <img width="1583" alt="Screen Shot 2023-07-07 at 11 48 00 PM" src="https://github.com/brave/brave-browser/assets/387249/7ace4949-f9c6-4d13-b059-53181e18ffff"> | <img width="1583" alt="Screen Shot 2023-07-07 at 11 48 18 PM" src="https://github.com/brave/brave-browser/assets/387249/68bb51a7-cb05-4670-8919-4b5c0a8d65a0"> | <img width="1583" alt="Screen Shot 2023-07-07 at 11 48 21 PM" src="https://github.com/brave/brave-browser/assets/387249/50ae595f-8338-4e4c-ba48-c7178f10b993"> | <img width="1583" alt="Screen Shot 2023-07-07 at 11 48 49 PM" src="https://github.com/brave/brave-browser/assets/387249/bb0f5bf1-adb0-4f1f-93ba-ec4ae66b1381">
