### ISSUE TITLE
Update NFT discovery dialog selection choice to show again after reset

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#30140]
## Description 
Clear NFT discovery dialog selection choice to show again after wallet reset.

## Actual result 
NFT discovery dialog doesn't show up after wallet reset if it was previously enabled or cancelled

## Expected result
NFT discovery dialog should show up always after wallet reset if the NFT discovery is not enabled.

## Additional
May require UI updates per discussion: https://bravesoftware.slack.com/archives/C0569LGK2HH/p1683218428828789

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.53.94 x64 Beta build
- Verified steps [brave/brave-core#18378](https://github.com/brave/brave-core/pull/18378)
- Verified resetting wallet with `Enable NFT discovery` disabled, shows the NFT discovery dialog on the new wallet as well
- Verified resetting wallet with `Enable NFT discovery` enabled, doesn't show the NFT discovery dialog on a new wallet
- Verified if the setting is enabled, resetting wallet doesn't reset it to disabled (default state)
