### ISSUE TITLE
Add Buy Send Swap More buttons to portfolio for Smaller Width

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#30148]
## Description 

We need to add `Buy, Send, Swap, More` buttons to the `Portfolio` view for small width screens.

![image](https://user-images.githubusercontent.com/40611140/236327262-67a1158e-8104-4b1a-8759-7821f3f33194.png)

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.53.102 Chromium: 114.0.5735.133 (Official Build) (64-bit)
-- | --
Revision | `fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}`
OS | Linux

- Verified steps from [brave/brave-core#18431](https://github.com/brave/brave-core/pull/18431)
- Verified Buy/Send/Swap/Deposit buttons work on collapsed navigation in smaller window size

https://github.com/brave/brave-browser/assets/17010094/7162df94-ac19-4431-a9d5-0137ac40f9ca


---------------------

**Verification passed on**

Brave | 1.53.102 Chromium: 114.0.5735.133 (Official Build) (64-bit)
-- | --
Revision | `fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}`
OS | Windows 11 Version 22H2 (Build 22621.1848)

- Verified steps from [brave/brave-core#18431](https://github.com/brave/brave-core/pull/18431)
- Verified Buy/Send/Swap/Deposit buttons work on collapsed navigation in smaller window size

https://github.com/brave/brave-browser/assets/17010094/cadc4dfe-403b-400f-8674-2d180e85b655

---------------------

**Verification passed on**

Brave | 1.53.102 Chromium: 114.0.5735.133 (Official Build) (64-bit)
-- | --
Revision | `fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#18431](https://github.com/brave/brave-core/pull/18431)
- Verified Buy/Send/Swap/Deposit buttons work on collapsed navigation in smaller window size

https://github.com/brave/brave-browser/assets/17010094/77737f65-3c6b-48d3-9e75-cd373d266d5a
