### ISSUE TITLE
Don't throttle extension requests to localhost

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#30151]
We currently do not block extension requests to localhost via adblock. With the new localhost permission feature, as we move away from using adblock for blocking, we should continue not doing that.

**Comment by kjozwiak** [comment]
@brave/qa-team this one can be completed at the same alongside https://github.com/brave/brave-browser/issues/30121.

**Comment by stephendonner** [comment]
Followed the same steps to reproduce from the testplan, and confirmed the fix - details over in https://github.com/brave/brave-browser/issues/30121#issuecomment-1572957978.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.53.81 Chromium: 114.0.5735.90 (Official Build) beta (x86_64)
-- | --
Revision | 386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}
OS | macOS Version 11.7.7 (Build 20G1345)



Followed the same steps to reproduce from the testplan, and confirmed the fix - details over in https://github.com/brave/brave-browser/issues/30121#issuecomment-1577582830

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.53.85 Chromium: 114.0.5735.110 (Official Build) beta (64-bit)
-- | --
Revision | 1c828682b85bbc70230a48f5e345489ec447373e-refs/branch-heads/5735_90@{#13}
OS | Linux
```
Verification notes in https://github.com/brave/brave-browser/issues/30121#issuecomment-1583604230
