### ISSUE TITLE
"Block cross-site Cookies" option is not saved in Brave Shields advanced settings

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#30155]
## Description 

The "Block cross-site Cookies" option is not saved in Brave Shields advanced settings

## Steps to reproduce 

   1. Launch Brave > Hamburger Menu > Settings
   2. Brave Shields & privacy > Block Cookies
   3. Set to `Block all cookies` or `Allow all cookies` > Done
   4. Open Block Cookies again > Set to `Block cross-site cookies` > Done > Observe

## Actual result 

The `Block cross-site cookies` option is not saved in Brave Shields advanced settings while staying on that page. It's always switching to `Allow all cookies` instead. If you want to save cookies in the `Block cross-site cookies` state, then need to close the `Brave Shields & privacy` settings or Brave itself.

https://user-images.githubusercontent.com/128532965/236368773-4aba8454-2d63-44be-aa38-53d9801d8b26.mp4

## Expected result

The `Block cross-site cookies` state must be saved without leaving `Brave Shields & privacy` settings or closing Brave

## Issue reproduces how often 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Pixel 6 [phone]
   - Android version: Android 13 [oriole-user 13 TQ2A.230405.003.E1 release-keys]
   
## Brave version

1.52.86 Chromium: 113.0.5672.77 (Official Build) beta (32-bit)

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by DanielProg39** [comment]
More details for this issue in [this video](https://drive.filen.io/d/2cb22936-1c8f-4921-89aa-8f746aea1218#oMyI4sXq4ykaAp9xHAtUcseRKBLkfZIX). Blocking third party cookies work only when enabled in the Site settings section of the browser settings, in the Brave Shield this feature doesn't work at all.

**Comment by DanielProg39** [comment]
Blocking third party cookies work only when enabled in the Site settings section of the browser settings, in the Brave Shield this feature doesn't work at all.

**Comment by Saoiray** [comment]
@deeppandya +1 on this at https://community.brave.com/t/cookie-settings-bug/506418/

Want to also point out some possible extra info. 

* When you change from `Allow all cookies` to `Block all cookies` it will show as if it's still on `Allow all cookies`. Yet if you exit the menu and return, it will show that it did retain `Block all cookies`. 

* An issue though is if you then go to `Settings` -> `Site Settings` -> `Cookies` the option will show `Allow cookies`. So even though `Brave Shields & Privacy` shows `Block cross-site cookies` this doesn't. You can change it to `Block third-party cookies` and the setting will stick. 

I'm not sure why there's a disconnect between these settings? Also not sure why it is visually showing in `Brave Shields & Privacy` like it's auto switching to `Allow all cookies` when anyone enters that menu. 

On top of that, why is it changing the setting in one location is not changing it in the other? If Shields is set to block cross-site, shouldn't the cookies settings in site settings show the same? If not, then how is the browser handling the conflicting options?

**Comment by Brave-Matt** [comment]
Some extensive testing on this issue done in this thread here:
https://community.brave.com/t/cookie-settings-bug/506418/15

**Comment by YellowRoseCx** [comment]
I also noticed that after setting my global cookies setting to "Block cross-site cookies," the "advanced controls" for cookies in the Brave Shield settings on individual sites stick to "allow all cookies"

This is on Android 11, "Brave 1.57.47, Chromium 116.0.5845.96"

**Comment by deeppandya** [comment]
we missed `break` for switch in https://github.com/brave/brave-core/commit/3ee7f22fa0834e619cdbccfbbcfdc0890f9cb73c

**Comment by kjozwiak** [comment]
The above requires `1.59.120` or higher for `1.59.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version:

```
Brave	1.59.120 Chromium: 118.0.5993.88 (Official Build) (64-bit) 
Revision	135f92a9af2134bc7d7aeba82f87ff5e68669410
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

- Ensured that the correct selection is being saved/used via Block Cookies via Settings
- Ensured that the change is being outlined via the shields panel on websites that are still using the default settings
- Ensured that website(s) that have already changed Block Cookies are not changed when a new global selection is made
- Ensured that changing Block Cookies via Settings multiple times doesn't cause any issues
- Ensured that the selection/choice is persistent after restarting Brave
- Ensured that you can change Block Cookies via the panel without any issues
- Also quickly checked and ensured that Block trackers & ads, Upgrade connections to HTTPS & Block Fingerprinting was still working as expected when changing the settings globally via Settings.
- Ensured that cookie preference is preserved in the upgrade path

Example | Example | Example
-|-|-
![Screenshot 2023-10-18 at 3 48 40 PM](https://github.com/brave/brave-browser/assets/17885425/d153c670-f11a-4266-b049-9337f754d446) | ![Screenshot 2023-10-18 at 3 46 26 PM](https://github.com/brave/brave-browser/assets/17885425/68c2ee92-d5aa-4ead-a368-e59db23d2a39) | ![Screenshot 2023-10-18 at 3 46 31 PM](https://github.com/brave/brave-browser/assets/17885425/ecc6c5ba-85c5-4af1-a659-d98e42122fa4)
