### ISSUE TITLE
[Regression]: Copying console messages has an offset on copied text, very annoying when debugging 

### ISSUE THREAD

**Issue by AustinGitHub** [brave/brave-browser#30156]
Version
[Version 1.51.110 Chromium: 113.0.5672.77 (Official Build) (64-bit)](https://brave.com/latest/)

https://user-images.githubusercontent.com/10100397/236382244-f03ae245-21db-40c1-9e38-00c4718853b2.mp4

If I do `ctrl+c` I see this, if I highlight right click and do copy I see this. 
Please fix, thanks!

Not sure who to tag for this, thanks!

**Comment by rebron** [comment]
@AustinGitHub What OS are you using? Can you go to brave://version and copy and paste your version up to the User Agent line?

**Comment by rebron** [comment]
cc: @spylogsster Copy clean link related?

**Comment by AustinGitHub** [comment]
I see this on Windows 11 and MacOS. Both computers are up to date

**Comment by AustinGitHub** [comment]
This is fixed, thanks!
