### ISSUE TITLE
Implement stub brave://skus-internals page

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#30153]
This is sub task of https://github.com/brave/brave-browser/issues/26788
Implement stub brave://skus-internals page

<img width="792" alt="Screenshot 2023-05-04 at 1 47 47 PM" src="https://user-images.githubusercontent.com/6786187/236355110-24687c5d-7efd-4dc6-ac54-d28bf2278853.png">

**Comment by stephendonner** [comment]
<3
