### ISSUE TITLE
Wrong `Attention` value in auto-contribute table when `Allow contribution to non-verified sites` is changed

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#3015]
## Steps to Reproduce

test case 1
1. Clean profile 
2. Enable rewards
3. Go to a non-verified publisher (`interia.pl`) and wait on the page for 10s
4. Turn off `Allow contribution to non-verified sites` in auto-contribute settings
5. Go to a verified publisher (`https://kjozwiak.github.io/`) and wait on the page for 10s
6. Turn on `Allow contribution to non-verified sites`

test case 2 
1. Clean profile 
2. Enable rewards
3. Go to a non-verified publisher (`interia.pl`) and wait on the page for 10s
4. Go to a verified publisher (`https://kjozwiak.github.io/`) and wait on the page for 10s
5. Turn off `Allow contribution to non-verified sites` in auto-contribute settings

## Actual result:

test case 1:
![image](https://user-images.githubusercontent.com/34715963/51393616-6948ad80-1b38-11e9-9815-b74c61416003.png)

test case 2:
![image](https://user-images.githubusercontent.com/34715963/51393973-5d112000-1b39-11e9-946a-b6b462e436bf.png)

## Expected result:
On `Allow contribution to non-verified sites` change, the values are recalculated

## Reproduces how often: 

always

## Brave version (brave://version info)

Brave | 0.59.25 Chromium: 72.0.3626.53 (Official Build) beta (64-bit)
-- | --
Revision | 98434e6cd182d68ce396daa92e9c6310422e6763-refs/branch-heads/3626@{#620}
OS | Windows 7

cc @brave/legacy_qa @NejcZdovc

**Comment by LaurenWags** [comment]
Reproduced on macOS

Brave | 0.59.28 Chromium: 72.0.3626.64 (Official Build) beta(64-bit)
-- | --
Revision | eaa9668e80ce5405e7f1902579558ea725c06ca1-refs/branch-heads/3626@{#708}
OS | Mac OS X

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.61.37 Chromium: 73.0.3683.39 (Official Build) beta (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

Used STR from the description. Also check publishers on youtube and twitch.
