### ISSUE TITLE
Sets the same z-order  as the browser window for custom notifications by default

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#30164]

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.53.99 Chromium: 114.0.5735.133 (Official Build) beta (64-bit) 
-- | --
Revision | fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}
OS | Windows 10 Version 22H2 (Build 19045.3086)

Verified test plan from https://github.com/brave/brave-core/pull/18384

<details>

Run Brave with:
```
 --enable-logging=stderr --vmodule="*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6,"*/bat_ads/*"=6,"*/whats_new/*"=9 --variations-server-url=https://variations.bravesoftware.com/seed1 --rewards=staging=true --use-dev-goupdater-url --enable-features=CustomNotificationAds
```

Verified custom notification is attached to Brave Window:
![30164](https://github.com/brave/brave-browser/assets/34715963/b5c8e8c3-ef89-4fbf-99e0-79408c22cf7b)


</details>
