### ISSUE TITLE
Add error handling to the panel for wallet creation

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#3016]
We need to show try again message when user experience problem creating a wallet. We should also persist creating state in the panel.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.60.23 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/1389
