### ISSUE TITLE
ERR_BLOCKED_BY_RESPONSE when navigating to Google.com

### ISSUE THREAD

**Issue by eMadman** [brave/brave-browser#30162]
## Description 
The issue is intermittent and  not consistently reproduceable.  Google.com and google search only works while using incognito.

In regular browsing mode, google gives a ERR_BLOCKED_BY_RESPONSE.  

Google subdomains work when this occurs:  gmail, google docs, google drive, photos, etc.

## Steps to Reproduce

   1. Perform a google search or navigate to google.com
   2. See ERR_BLOCKED_BY_RESPONSE
   3. Open Incognito window and do a search or navigate to google.com
   4. See expected results.

## Actual result:

I'm not currently seeing the issue - will provide a screenshot next time it occurs.

## Reproduces how often: 

Intermittent

## Desktop Brave version:

Version 1.51.110 Chromium: 113.0.5672.77 (Official Build) (64-bit)](https://brave.com/latest/)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- No

- Does the issue resolve itself when disabling Brave Rewards? 
- No

-  Is the issue reproducible on the latest version of Chrome?
- No

**Comment by bsclifton** [comment]
@breinhart @eMadman do you mind sharing the value from brave://version/ ?

Basically, I'm interested in the values under `Active Variations`

**Comment by eMadman** [comment]
> @breinhart @eMadman do you mind sharing the value from brave://version/ ?
> 
> Basically, I'm interested in the values under `Active Variations`

There have been a few updates since this issue started and it has stopped as a result of one of them.  

<html>
<body>


Brave | 1.51.118 Chromium: 113.0.5672.126 (Official Build) (64-bit)
-- | --
Revision | c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}
OS | Windows 11 Version 22H2 (Build 22621.1702)
JavaScript | V8 11.3.244.11
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
Command Line | "C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe" --disable-domain-reliability --enable-dom-distiller --lso-url=https://no-thanks.invalid --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --variations-insecure-server-url=https://variations.brave.com/seed --variations-server-url=https://variations.brave.com/seed --restart --flag-switches-begin --enable-experimental-web-platform-features --flag-switches-end --component-updater=url-source=https://go-updater.brave.com/extensions,url-source=https://go-updater.brave.com/extensions
Executable Path | C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path | C:\Users\emadm\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Active Variations | AdRewardsStudy:NextPaymentDayAllowCertainClientHintsStudy:EnabledBraveAdblockCookieListOptInReleaseStudy:EnabledBraveAdblockMobileNotificationsListDefault:EnabledBraveAds.AdServingStudy:DefaultAdNotificationsPerHour=10/MaximumAdNotificationsPerDay=100/MaximumInlineContentAdsPerHour=6/MaximumInlineContentAdsPerDay=20/AdServingVersion=2BraveAds.FrequencyCappingStudy:ExcludeAdIfWithinTimeWindow=0hBraveAutoTranslateStudy:AutoTranslateDisabledBraveDebounceStudy:EnabledBraveGoogleSignInPermissionStudy:DisabledBraveHttpsByDefaultRolloutStudy:DefaultBraveRewardsWebUiPanelStudy:EnabledBraveScreenFingerprintingBlockerStudy:EnabledConversionsStudy:NewDefaultPatternCrossPlatformVPNStudy:EnabledDefault1pBlockingStudy:DisabledDisableReduceLanguage:EnabledEphemeralStorageStudy:EnabledFirstPartyEphemeralDomainBlockStudy:EnabledForceDisableBlinkFeatures:EnabledMetricsAndCrashSampling:OutOfReportingSamplePartitionBlinkMemoryCacheStudy:EnabledPartitionConnectionsByNetworkIsolationKeyStudy:EnabledPermissionLifetimeReleaseStudy:EnabledSpeedreaderReleaseStudy:EnabledUserActivityStudy:TriggersWhatsNewStudy:Enabled


</body>
</html>

**Comment by bsclifton** [comment]
cc: @ShivanKaul just in case this is related to the Google sign in Griffin changes

**Comment by ShivanKaul** [comment]
@eMadman @breinhart any chance you could show the console logs under dev console? You can see them this way https://grantwinney.com/how-do-i-view-the-dev-console-in-my-browser/#brave

**Comment by eMadman** [comment]
@ShivanKaul - this issue stopped for me after some update to the browser about a week or so after I reported it.  Here's the console log for google.com as of today:

![image](https://github.com/brave/brave-browser/assets/24726844/be54b672-f38d-428a-bb4f-8aaba08a4378)

**Comment by Kosezu** [comment]
I am having this same issue, but with Brave.com and mail.proton.me addresses. No fix. Happened immediately after latest Brave Beta update as of the time of this post.
