### ISSUE TITLE
Sync is not running after 1.50.125=>1.51.110 on Linux with KDE

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#30167]
Reported by numerous messages at community.brave.com:
https://community.brave.com/t/sync-stopped-working-after-updating-to-1-51-110/485598/12
https://community.brave.com/t/sync-not-working-brave-was-unable-to-access-your-systems-secure-storage/485452/21

I also was able to reproduce
1. Install fresh Kubuntu 22.10 [kubuntu-22.10-desktop-amd64.iso](https://cdimage.ubuntu.com/kubuntu/releases/kinetic/release/kubuntu-22.10-desktop-amd64.iso)
2. Install brave-keyring with modified instruction from https://brave.com/linux/#debian-ubuntu-mint
```

sudo apt install curl

sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg

echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"|sudo tee /etc/apt/sources.list.d/brave-browser-release.list

sudo apt update

sudo apt install brave-keyring

```

3. Download [brave-browser_1.50.125_amd64.deb](https://github.com/brave/brave-browser/releases/tag/v1.50.125) and install it
```
sudo dpkg -i brave-browser_1.50.125_amd64.deb 
```
4. Launch browser, setup sync, ensure sync runs well

5. Download [brave-browser_1.51.110_amd64.deb](https://github.com/brave/brave-browser/releases/tag/v1.50.125) and install it
```
sudo dpkg -i brave-browser_1.51.110_amd64.deb
```
6. Launch browser, check sync status. For me it was good.
7. Restart browser, check sync status. I saw this  

![image](https://user-images.githubusercontent.com/24739341/236502362-2ae43ca5-6738-40db-9057-2df6d189d50d.png)

![image](https://user-images.githubusercontent.com/24739341/236502462-9941f215-2222-45bd-bef6-bf6f662e29c0.png)

![image](https://user-images.githubusercontent.com/24739341/236502201-ad6bc731-b40c-4132-b8d6-327e40b8f7e9.png)

**Comment by Tortillas-IT** [comment]
same issue here on Arch + KDE

**Comment by Tortillas-IT** [comment]
btw, if i try to delete brave keys using kwallet by KDE and restart brave all seems fine, but if i restart brave again... it breaks again

**Comment by AlexeyBarabash** [comment]
Closing current as a duplicate of https://github.com/brave/brave-browser/issues/30147
