### ISSUE TITLE
Unreadable `New` text in `More tools` -> `Performance` flyout menu

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#30173]
## Description 

Unreadable `New` text in `More tools` -> `Performance` flyout menu

## Steps to Reproduce

1. install `.152.85`
2. launch Brave
3. open app menu -> `More tools`
4. look at the `Performance` `New` text

## Actual result:

`Light` | `Dark`
-------|-------
![image](https://user-images.githubusercontent.com/387249/236524825-0620774a-1889-4195-8963-d3384e477ef7.png) | ![image](https://user-images.githubusercontent.com/387249/236525535-d287e05b-c0e6-4154-99fa-c228798cedd2.png)

## Expected result:

Readable `New` text, regardless of theme/`Brave colors` choices

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.52.85 Chromium: 113.0.5672.63 (Official Build) beta (64-bit)
-- | --
Revision | 0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}
OS | Windows 10 Version 22H2 (Build 19045.2913)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron @brave/qa-team @aguscruiz @mkarolin

**Comment by aguscruiz** [comment]
Added designs here:

https://www.figma.com/file/tU9zrk9Ite8B06JSjHAHhn/General-dialogs-and-popups?node-id=21%3A26871&t=Sr1UlwXeY8eZfpFl-1

![image](https://user-images.githubusercontent.com/15734630/236527207-efeca100-b465-4855-8c10-93bceac12db5.png)

![image](https://user-images.githubusercontent.com/15734630/236527276-d8c59419-f685-43d2-8b2c-1325a2c33b1f.png)

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.53.45 Chromium: 114.0.5735.26 (Official Build) nightly (x86_64)
-- | --
Revision | 7075cbb66f0542ac3e01ddfde6b813e7d61118a5-refs/branch-heads/5735@{#454}
OS | macOS Version 11.7.6 (Build 20G1231)




`Dark` | `Light`
-------|--------
<img width="1657" alt="Screen Shot 2023-05-16 at 6 36 50 PM" src="https://github.com/brave/brave-browser/assets/387249/24402629-feb4-4379-84a2-a8ba065fb8a7"> | <img width="1657" alt="Screen Shot 2023-05-16 at 6 37 11 PM" src="https://github.com/brave/brave-browser/assets/387249/0404ab1b-050e-489e-8ce7-cdd3c86ab642">
