### ISSUE TITLE
[Android] Custom filter lists via settings

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#30174]
_**Related issue:** https://github.com/brave/brave-browser/issues/26587 (ideally we do both at the same time)_

## Description
Currently users can add custom filter lists via settings on iOS and Desktop. This ticket is to bring over the same feature to Android.

| iOS Filter Lists  | iOS Add Custom Filter List |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/28269287/236526056-ed0b33d0-b6dd-473d-a0b2-f8230a9c01ca.png) | ![image](https://user-images.githubusercontent.com/28269287/236525828-bccc9307-e48a-46fd-9761-a3440b96ac76.png)

## Requirements

- Android users are able to add custom filter lists via settings.
- The setting should live under Brave Shields & privacy, after the "prevent fingerprinting via language settings" toggle.

### Design
If possible copy the iOS layout. If an Android-specific design is required then design is TBD.

cc @deeppandya @anthonypkeane

**Comment by deeppandya** [comment]
CC @tapanmodh for more context : 
https://github.com/brave/brave-browser/assets/5146988/505f7ebb-259f-4abb-b89d-e39e7f7b1722

**Comment by tapanmodh** [comment]
thank you @deeppandya

**Comment by car12o** [comment]
indeed, this would be super to have on android.
currently, I have to switch browser in order to see some beach cams in my town.

**Comment by deeppandya** [comment]
> indeed, this would be super to have on android.
> currently, I have to switch browser in order to see some beach cams in my town.

@car12o we are currently looking into it and it would be merged into the nightly application soon. So please stay tuned.
