### ISSUE TITLE
Remove duplicated state selection during gas edit

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#30175]
## Description 

We currently are requesting the selected pending transaction multiple times when editing gas. Remove the additional state selector to reduce component complexity

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.53.104 Chromium: 115.0.5790.40 (Official Build) (64-bit)
-- | --
Revision | `071c9ddea889c3c7887daf4eac13fed72d4fff62-refs/branch-heads/5790@{#979}`
OS | Windows 11 Version 22H2 (Build 22621.1848)

- Verified steps from [brave/brave-core#18390](https://github.com/brave/brave-core/pull/18390)
- Verified editing gas settings for transaction doesn't cause it to fail or error
- Verified able to successfully submit and confirm transaction by editing gas fee settings
