### ISSUE TITLE
Referer is not hidden

### ISSUE THREAD

**Issue by ggttttggggtt** [brave/brave-browser#30184]
## Description 
The referrer is not hidden from websites, even with fingerprinting and tracking set to be agressively blocked.

## Steps to Reproduce

   1. Click on this link: https://referer.rustybrick.com/ 
   2. Notice that it correctly tells you that you came from github
   3. If you like, retry with shields set to aggressively block trackers and fingerprinting
   4. Observe the same result
 
## Expected result:
Websites shouldn't allowed to see my referer, at least when aggressive anti-fingerprinting is on

## Reproduces how often: 
Always

## Brave version (brave://version info)
Brave: 1.51.110 Chromium: 113.0.5672.77 (Official Build) (64-bit)
Revision: c4236862955e005c2187105415ac4a2ecf86dff1-refs/branch-heads/5672_62@{#3}
OS: Linux

## Version/Channel Information:
Only tested with the current release, from the AUR

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
No
- Does the issue resolve itself when disabling Brave Rewards? 
No
- Is the issue reproducible on the latest version of Chrome? 
Didn't try, most likely

**Comment by diracdeltas** [comment]
@pes10k is this a regression? according to https://brave.com/privacy-updates/5-grab-bag/#2referrer-policy-changes navigation to a new site should send no referrer.

**Comment by pes10k** [comment]
No, this is intentional, and has been this way since 2021.  Web compat issues forced us to change things to a default policy of `strict-origin-when-cross-origin` (see https://github.com/brave/brave-browser/issues/13464).  The blog post pre-dates this change.  I will update the blog post
