### ISSUE TITLE
[Leo Icons]: Update permission icons

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#30189]
Subissue of https://github.com/brave/brave-browser/issues/30092 for updating permission icons (i.e. camera/microphone ect)

@aguscruiz there are a bunch of permission icons we probably want to update too - for example, have a look at any site in brave://settings/content/all (most of these can be shown in the toolbar)

Chromium Icons
![image](https://user-images.githubusercontent.com/7678024/236707457-47bc4cf1-2f17-4324-aaf3-6b91896c3591.png)

Leo Icons
![image](https://github.com/brave/brave-browser/assets/7678024/9a540ff0-e700-4f22-a306-e889a468c64a)

**Note:** This issue only relates to the icons on the site settings page, not the ones which show up in the toolbar.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.54.85 Chromium: 115.0.5790.56 (Official Build) beta (64-bit)
-- | --
Revision | ebcfb87c1393f36955cfa2f6451a1767e3dc3ee5-refs/branch-heads/5790@{#1193}
OS | Windows 10 Version 22H2 (Build 19045.3155)

### Confirmed the new icon set in `brave://settings/content/all` for any given site

`1.54.85` | `1.52.129`
---------|-------------
![image (6)](https://github.com/brave/brave-browser/assets/387249/f3b21a69-91f9-4b6e-a6a8-a5eb8aca4704) | ![image (5)](https://github.com/brave/brave-browser/assets/387249/d8eee53d-e205-448b-9239-4a680fb693ed)

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.54.85 Chromium: 115.0.5790.56 (Official Build) beta (x86_64)
-- | --
Revision | ebcfb87c1393f36955cfa2f6451a1767e3dc3ee5-refs/branch-heads/5790@{#1193}
OS | macOS Version 11.7.8 (Build 20G1351)

## Confirmed the new icon set in `brave://settings/content/all` for any given site

`1.54.85` | `1.52.129`
----------|---------
<img width="1312" alt="Screen Shot 2023-07-01 at 3 57 16 PM" src="https://github.com/brave/brave-browser/assets/387249/039b3a67-dbfb-4767-b9c0-8541bacedd97"> | <img width="1312" alt="Screen Shot 2023-07-01 at 3 58 33 PM" src="https://github.com/brave/brave-browser/assets/387249/e0880e5a-703c-4e2b-86ba-d028103ab161">

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave	1.57.33 Chromium: 115.0.5790.114 (Official Build) beta (64-bit) 
Revision	86b4ea1d70ce73c4468d84cc8277f1f9de14b8bc
OS	Linux
```
