### ISSUE TITLE
[Leo Icons]: Update Toolbar Icons

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#30186]
Subissue of https://github.com/brave/brave-browser/issues/30092 for updating the toolbar icons

## Icons
- [x] Back `browser-back`
- [x] Forward `browser-forward`
- [x] Reload `browser-refresh`
- [x] Bookmark 
    - [x] Bookmark `browser-bookmark-normal`
    - [x] Bookmarked `bookmark-added`
- [x] Lock
    - [x] Lock, secure (`lock-plain`)
    - [x] Lock, loading (`warning-circle-filled`) 
    - [x] Lock insecure (`warning-triangle-filled`)
- [x] Extensions `browser-extensions`
- [x] Wallet `product-brave-wallet`
- [x] Hamburger button `hamburger-menu`
- [x] Home button `browser-home`
- [x] Download button `download`
- [x] Battery saver `energy-saver`
- [x] Install PWA `pwa-install`
- [x] Reader mode `product-readermode`
- [x] Speedreader mode `product-speedreader`
- [x] Playlist
- [x] Share `share-browser`
- [x] Zoom
    - [x] Zoomed in `search-zoom-in`
    - [x] Zoomed out `search-zoom-out`
- [x] Find icon (when CTRL+F is pressed) `window-search`

**Comment by fallaciousreasoning** [comment]
@aguscruiz the `pwa-install` icon doesn't render properly in the browser - I think it's something to do with having multiple paths (this might be a problem on my end).

The other thing I noticed is that we don't have an icon for playlist!

**Comment by aguscruiz** [comment]
Oh, sorry about that. I think I fixed it now.

We have an icon for playlist, it's called `product-playlist`. There are a bunch of them according to state but this is the one you want
<img width="247" alt="image" src="https://user-images.githubusercontent.com/15734630/236824714-59f9bd00-2cbc-46e3-afc6-f4e28413f2ca.png">

**Comment by fallaciousreasoning** [comment]
Yeah, I think the `pwa-install` icon is a problem with how we're handling Chromium icons unfortunately. I'll have to dig into it a bit more.

Okay, so this is looking really good at the moment. My todo list is shrinking:
1. Close button is too small now when we swap between the `browser-reload` and the `close` button the close button looks tiny

    Refresh | Close
    ----------- | ----------------
    ![Leo Refresh](https://leo.bravesoftware.com/icons/browser-refresh.svg) | ![Leo Close](https://leo.bravesoftware.com/icons/close.svg)

2. The `pwa-install` icon doesn't render properly in Chromium (this one is for me to suss out)
3. Just to confirm, this is the icon that `product-playlist` icon is replacing, right?
    ![image](https://github.com/brave/brave-browser/assets/7678024/13ce9754-15e1-46bc-b2a0-e152c346e2c3)

**Comment by fallaciousreasoning** [comment]
Agreed! `music-tones` looks good to me :smile: 

I think we do have playlist on desktop but it's hidden behind a flag brave://flags/#playlist (currently I think we're using that same icon as that one, and we only show it in the sidebar!)

**Comment by MadhaviSeelam** [comment]
Waiting on testplan as discussed in the Desktop Planning & Triage call.

**Comment by fallaciousreasoning** [comment]
Updated the description with a test plan - I don't think we need to verify more than "there is still an icon" for each of the listed icons.

**Comment by MadhaviSeelam** [comment]
Adding Figma designs by @aguscruiz 
https://www.figma.com/file/tLXWGCpNoiJxDZDdpfordj/Desktop-Settings?type=design&node-id=4081%3A81070&mode=design&t=GURivpDwF1HOuLMR-1

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.57.27 Chromium: 115.0.5790.114 (Official Build) beta (x86_64)
-- | --
Revision | 18977fb43f693d5a8deeb48bd1cfa52651d3f73e
OS | macOS Version 13.5 (Build 22G74)
```

**Comment by fallaciousreasoning** [comment]
Hah! I used badssl for testing the lock icon too @LaurenWags :laughing:

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.57.32 Chromium: 115.0.5790.114 (Official Build) beta (64-bit)
-- | --
Revision | bf9c67d9dafde9e2cc2219abd8ddfe738f316b3c
OS | Windows 10 Version 22H2 (Build 19045.3208)

```

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave	1.57.33 Chromium: 115.0.5790.114 (Official Build) beta (64-bit) 
Revision	86b4ea1d70ce73c4468d84cc8277f1f9de14b8bc
OS	Linux
```

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21 5G` using version: 

```
Brave	1.57.42 Chromium: 116.0.5845.51 (Official Build) (64-bit) 
Revision	e25036a089c476c56bf71774a898a1fee014e00d
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
- Verified all applicable items in test plan for https://github.com/brave/brave-browser/issues/30186#issue-1699280100

Example | Example
-|-
![Screenshot 2023-08-09 at 5 47 30 PM](https://github.com/brave/brave-browser/assets/17885425/a1d37785-ce0c-4c24-af43-1491d9a7a13a) | ![Screenshot 2023-08-09 at 6 08 09 PM](https://github.com/brave/brave-browser/assets/17885425/c200d286-789f-4c63-8281-e1a80d568d3c)
![Screenshot 2023-08-09 at 6 10 06 PM](https://github.com/brave/brave-browser/assets/17885425/57ed6993-c27c-4ea1-8fa6-61a0e3ac8b28) | ![Screenshot 2023-08-09 at 6 09 42 PM](https://github.com/brave/brave-browser/assets/17885425/610c171d-19cc-4242-9d86-43e8f71261ad)
![Screenshot 2023-08-09 at 5 47 06 PM](https://github.com/brave/brave-browser/assets/17885425/d4494184-0387-4c3f-a2e2-e8659445e594) | ![Screenshot 2023-08-09 at 6 06 10 PM](https://github.com/brave/brave-browser/assets/17885425/b9d1fbbd-2270-47cb-890b-6f2c710ec9d2)
![Screenshot 2023-08-09 at 5 50 15 PM](https://github.com/brave/brave-browser/assets/17885425/06aea279-6dd0-42d8-b244-fb283a323943) | ![Screenshot 2023-08-09 at 6 03 20 PM](https://github.com/brave/brave-browser/assets/17885425/8146aa13-0a9f-4cf6-8569-589c7fa775ba)
![Screenshot 2023-08-09 at 5 52 19 PM](https://github.com/brave/brave-browser/assets/17885425/69b38742-a3e2-4ffb-8413-ed99b6aa6720) | ![Screenshot 2023-08-09 at 6 07 26 PM](https://github.com/brave/brave-browser/assets/17885425/4ae2f7c8-41ff-474a-85b8-1df798be1d5a)
![Screenshot 2023-08-09 at 5 48 00 PM](https://github.com/brave/brave-browser/assets/17885425/e6074fe5-18d2-41bf-a6ff-6ac6329c8523) | ![Screenshot 2023-08-09 at 6 06 51 PM](https://github.com/brave/brave-browser/assets/17885425/59f858b2-b7d4-4aff-b822-0b79dd594aea)
![Screenshot 2023-08-09 at 5 55 41 PM](https://github.com/brave/brave-browser/assets/17885425/70e9c751-0841-425d-bebd-52506cce3b84) | ![Screenshot 2023-08-09 at 5 50 33 PM](https://github.com/brave/brave-browser/assets/17885425/2fc522cd-e6be-40be-b477-75441a9594b5) | ![Screenshot 2023-08-09 at 5 49 54 PM](https://github.com/brave/brave-browser/assets/17885425/750718fa-e349-408c-afc5-e75c7d2131fe)
![Screenshot 2023-08-09 at 5 49 54 PM](https://github.com/brave/brave-browser/assets/17885425/e00dad7c-ead6-4e0d-8fd9-66cb51967bd5) | ![Screenshot 2023-08-09 at 6 25 14 PM](https://github.com/brave/brave-browser/assets/17885425/3d2b9aa7-5053-4165-8b29-68631e7e1bac)
![Screenshot 2023-08-09 at 5 52 42 PM](https://github.com/brave/brave-browser/assets/17885425/261890af-e5bc-45c5-b0d9-c6cdfffae0d2) | ![Screenshot 2023-08-09 at 6 30 34 PM](https://github.com/brave/brave-browser/assets/17885425/0064dd4d-2331-430e-b7b4-28d0b62b4e0c)
![Screenshot 2023-08-09 at 5 59 58 PM](https://github.com/brave/brave-browser/assets/17885425/c79969a7-8542-4c21-a384-48d1bec25b67) | ![Screenshot 2023-08-09 at 6 26 08 PM](https://github.com/brave/brave-browser/assets/17885425/65bb0ab2-9264-483c-8ec9-ac92e6bf3a68)
![Screenshot 2023-08-09 at 5 59 32 PM](https://github.com/brave/brave-browser/assets/17885425/53c233ee-2efd-422c-9824-0ce8304895c1) | ![Screenshot 2023-08-09 at 6 29 22 PM](https://github.com/brave/brave-browser/assets/17885425/a723c86e-1ca4-48e0-89ef-022b797e2b9e)

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy Tab S7` using version: 

```
Brave	1.57.42 Chromium: 116.0.5845.51 (Official Build) (64-bit) 
Revision	e25036a089c476c56bf71774a898a1fee014e00d
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
- Verified all applicable items in test plan for https://github.com/brave/brave-browser/issues/30186#issue-1699280100
- Verified icons in URL bar are showing up in private tabs

Example | Example
-|-
![Screenshot 2023-08-09 at 7 20 34 PM](https://github.com/brave/brave-browser/assets/17885425/043bf4f3-7f36-4a80-af06-4fbff9c69a62) | ![Screenshot 2023-08-09 at 7 20 56 PM](https://github.com/brave/brave-browser/assets/17885425/da26da81-516d-42bc-a8ab-0930cb5b403f)
![Screenshot 2023-08-09 at 7 21 58 PM](https://github.com/brave/brave-browser/assets/17885425/6d77d11f-19d5-4620-92e2-215c210475c0) | ![Screenshot 2023-08-09 at 7 21 42 PM](https://github.com/brave/brave-browser/assets/17885425/40b68c4f-d09c-415c-8090-caf5132546bb)
![Screenshot 2023-08-09 at 7 22 34 PM](https://github.com/brave/brave-browser/assets/17885425/1594cd78-5fa8-4cc9-b9d0-eefffba79734) | ![Screenshot 2023-08-09 at 7 22 51 PM](https://github.com/brave/brave-browser/assets/17885425/daf90da8-5e69-46c2-91b7-fea58248e0a8)
![Screenshot 2023-08-09 at 7 23 42 PM](https://github.com/brave/brave-browser/assets/17885425/115f5eeb-7afe-43d0-8bc5-86ffe1761629) | ![Screenshot 2023-08-09 at 7 24 01 PM](https://github.com/brave/brave-browser/assets/17885425/676878d0-2982-499b-a9db-8d6325d2dc15)
![Screenshot 2023-08-09 at 7 24 33 PM](https://github.com/brave/brave-browser/assets/17885425/d93d186d-346b-4d17-b2f3-99b6c1aaae2e) | ![Screenshot 2023-08-09 at 7 25 01 PM](https://github.com/brave/brave-browser/assets/17885425/62bc71d8-c029-4c69-b301-6044b2f73a58)
![Screenshot 2023-08-09 at 7 24 47 PM](https://github.com/brave/brave-browser/assets/17885425/1991a750-f64d-45c8-b4ff-e4569ff39353) | ![Screenshot 2023-08-09 at 7 25 08 PM](https://github.com/brave/brave-browser/assets/17885425/ba445ba7-e8d1-4256-9f5b-58af485bc3f1)
![Screenshot 2023-08-09 at 7 27 28 PM](https://github.com/brave/brave-browser/assets/17885425/db3cf19e-632f-4ded-939d-7e24d8657f4a) | ![Screenshot 2023-08-09 at 7 28 15 PM](https://github.com/brave/brave-browser/assets/17885425/b0559e65-3957-47e5-bab8-f044150a06be)
![Screenshot 2023-08-09 at 7 29 28 PM](https://github.com/brave/brave-browser/assets/17885425/9c4d667f-d96f-4e25-9a02-560c6469cf31) | ![Screenshot 2023-08-09 at 7 28 47 PM](https://github.com/brave/brave-browser/assets/17885425/8daf2e62-3af5-42a7-8372-774f25d5c137)
![Screenshot 2023-08-09 at 7 31 20 PM](https://github.com/brave/brave-browser/assets/17885425/c5ddddca-ffba-4fad-9385-8905f11489b5) | ![Screenshot 2023-08-09 at 7 32 09 PM](https://github.com/brave/brave-browser/assets/17885425/f5adc4a2-e896-45d0-a133-242d24692990)

**Comment by Uni-verse** [comment]
Verified on `Pixel 5` (x86) running `Android 8` using version: 

```
Brave	1.57.44 Chromium: 116.0.5845.82 (Official Build) (32-bit) 
Revision	109e984111c5152478bf49d266f4e19861c0b63e
OS	Android 8.0.0; Build/OSR1.180418.026; 26; REL
```

- Verified all applicable items in test plan for https://github.com/brave/brave-browser/issues/30186#issue-1699280100
- Verified icons in URL bar are showing up in private tabs

Example | Example
-|-
![Screenshot 2023-08-10 at 11 00 59 AM](https://github.com/brave/brave-browser/assets/17885425/83cf0961-12fb-4ec7-9e65-407992b2b8b1) | ![Screenshot 2023-08-10 at 11 02 50 AM](https://github.com/brave/brave-browser/assets/17885425/0a8350dd-0626-481c-90c4-62a1484e3fcd)
![Screenshot 2023-08-10 at 11 03 44 AM](https://github.com/brave/brave-browser/assets/17885425/6d37937f-2bd6-4fc5-8d61-6a652c216636) | ![Screenshot 2023-08-10 at 11 03 24 AM](https://github.com/brave/brave-browser/assets/17885425/3be7bac1-1973-41d4-84c8-1e21b3d182bb)
![Screenshot 2023-08-10 at 11 03 53 AM](https://github.com/brave/brave-browser/assets/17885425/b46588b3-935a-4230-8883-1f08be0a0d89) | ![Screenshot 2023-08-10 at 11 04 08 AM](https://github.com/brave/brave-browser/assets/17885425/5169e729-fe4b-4466-ae8d-74b3b50fc2c9)
![Screenshot 2023-08-10 at 11 04 45 AM](https://github.com/brave/brave-browser/assets/17885425/b0413833-c2e8-4710-b35b-9d6e98888dd3) | ![Screenshot 2023-08-10 at 11 04 30 AM](https://github.com/brave/brave-browser/assets/17885425/da6716df-096a-45f9-a5e1-80a62735be4c)
![Screenshot 2023-08-10 at 11 05 20 AM](https://github.com/brave/brave-browser/assets/17885425/b67b9139-e18e-4c7b-be65-d26cfc18a6c4) | ![Screenshot 2023-08-10 at 11 05 43 AM](https://github.com/brave/brave-browser/assets/17885425/bd00abad-c223-4fe4-a3f8-896105ae42f9)
![Screenshot 2023-08-10 at 11 07 08 AM](https://github.com/brave/brave-browser/assets/17885425/e14a4736-26bf-42a3-9571-add9c785bd6e) | ![Screenshot 2023-08-10 at 11 06 38 AM](https://github.com/brave/brave-browser/assets/17885425/2bce27e8-9758-458e-b14c-616d05a9791e)
![Screenshot 2023-08-10 at 11 08 25 AM](https://github.com/brave/brave-browser/assets/17885425/a9bed28a-20e0-4732-9a47-950cdf1554df) | ![Screenshot 2023-08-10 at 11 15 53 AM](https://github.com/brave/brave-browser/assets/17885425/5bb97b14-9a7b-4e38-85df-4ced6a9c2c6e)
![Screenshot 2023-08-10 at 11 16 33 AM](https://github.com/brave/brave-browser/assets/17885425/475af302-2fc2-4439-a72f-5f39315a5429) | ![Screenshot 2023-08-10 at 11 16 15 AM](https://github.com/brave/brave-browser/assets/17885425/6bce2894-12c2-4941-9f32-d7223cfe7b2a)
![Screenshot 2023-08-10 at 11 16 57 AM](https://github.com/brave/brave-browser/assets/17885425/706738be-b618-43a1-adef-4ebe0c0696d2) | ![Screenshot 2023-08-10 at 11 17 16 AM](https://github.com/brave/brave-browser/assets/17885425/19d62abb-797d-468b-b6c4-dfc81ac776fb)
