### ISSUE TITLE
Use cached transactions on the wallet account detail page

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#30194]
## Description 

We should use the cached transactions list on the wallet account detail page so that we can fetch transactions only when required and to work towards deprecating the uncached transactions list state.

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on  

Brave | 1.53.104 Chromium: 115.0.5790.40 (Official Build) (64-bit)
-- | --
Revision | `071c9ddea889c3c7887daf4eac13fed72d4fff62-refs/branch-heads/5790@{#979}`
OS | Windows 11 Version 22H2 (Build 22621.1848)

- Verified steps from [brave/brave-core#18399](https://github.com/brave/brave-core/pull/18399)
- Verified transactions continue to show on account details page

https://github.com/brave/brave-browser/assets/17010094/fba6967c-67d7-4f38-b570-66c704213e5c
