### ISSUE TITLE
Display tracker count in the shields panel

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#3019]
If the end of the redirect chain has the same origin as the starting site, display the tracker count in the shields panel.

**Comment by jumde** [comment]
Does this proposal sound good? cc: @snyderp @tomlowenthal @bridiver

**Comment by tomlowenthal** [comment]
I'm into it. But it sounds exceedingly rare?

**Comment by snyderp** [comment]
That makes sense to me, but i think that will be the small small minority case.  TBH, the cases we're catching are pretty rare (1p redirection tracking) so for my 2 cents, its probably fine to just not worry about shields counts for them.  Smarter people than me (eg. @tomlowenthal @bridiver ) should make that call

**Comment by snyderp** [comment]
seems like @tomlowenthal literally beat me by seconds to making the same point :)

**Comment by jumde** [comment]
Ok cool, let's not worry about the count for now. I'll close this issue and we can open a new one, if there is an explicit request for the tracker count. Thanks @tomlowenthal @snyderp
