### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by saitakturk** [brave/brave-browser#30199]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.50.121  Chromium: 112.0.5615.138
Operating System: Mac OS X 13.3.1

URL (if applicable) where crash occurred:

Can you reproduce this crash?
Yes

What steps will reproduce this crash (or if it's not reproducible,
what were you doing just before the crash)?
(1) Click search bar.
(2) Write 'İ' four times .
(3) Chromium process crashes.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/be4c0500-1cae-080a-0000-000000000000

**Comment by rebron** [comment]
Hi @saitakturk 

Can you update to our latest 1.51.114 and let us know if you're still experiencing this crash?

**Comment by iefremov** [comment]
stale
