### ISSUE TITLE
Unable to submit transactions on Ethereum Testnet

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#30198]
## Description 
Unable to submit transactions on Ethereum Testnet

## Steps to reproduce 

   1. Install 1.52.84 build
   2. Switch network to Goerli/Sepolia
   3. Submit a Send transaction, never submits, can only reject

## Expected result
Able to submit transaction on Testnet

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Not checked

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 13
   
## Brave version
1.52.84 x64 Beta

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information
cc: @wchen342 @Pavneet-Sing

**Comment by Pavneet-Sing** [comment]
This appeasers to be happening due to low balance in wallet. Please after adding more balance on the same version.

**Comment by simoarpe** [comment]
With the transition to the new WebUI this issue will be fixed.
I'm including a short demo.

If the problem persists even after merging https://github.com/brave/brave-core/pull/20635, please reopen and ping me!

https://github.com/brave/brave-browser/assets/3308503/ff142f49-d19d-42b8-b222-c3ed549aa398
