### ISSUE TITLE
Brave keeps running in the background and eats A LOT OF ram after closing it even though setting is set to not to

### ISSUE THREAD

**Issue by marlester-dev** [brave/brave-browser#30206]
## Description 

Brave just keeps running in the background and eats A LOT OF ram even though I selected not to run in the background  in brave://settings/system. I feel like it didn't happen before but I'm not sure because I don't remember.
This is a SERIOUS bug, eating like 500 mb ram in the background is NOT ok.

## Steps to Reproduce

   1. Open the Brave
   2. Change the setting to not run in the background in brave://settings/system
   3. Close the Brave
   4. Look at task manager. There are still some processes in the background eating A LOT of ram and even some cpu/network.

## Actual result:

![R178](https://user-images.githubusercontent.com/77095872/236899522-2ed65006-00f7-4a45-9a67-8804e8095dbe.PNG)

## Expected result:
Not run in the background.

## Reproduces how often: 

Easy I guess.

## Brave version (brave://version info)

1.51.110 Chromium: 113.0.5672.77 x64
Windows 10 Version 22H2 (Build 19045.2846)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Yeah
- Can you reproduce this issue with the beta channel? 
- I don't know, sorry, I am a typical user and I am too lazy to test it out.
- Can you reproduce this issue with the nightly channel? 
- I don't know, sorry, I am a typical user and I am too lazy to test it out.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Uhh, no.
- Does the issue resolve itself when disabling Brave Rewards? 
- nah.
- Is the issue reproducible on the latest version of Chrome? 
- I don't know, I deinstalled chrome few months ago, it does not happen on the edge at least.

## Miscellaneous Information:

Definitely needs to be fixed, if not so it will be really bad.

**Comment by rebron** [comment]
@marlester-dev I'm going to ahead and close per your last comment. Please re-open if you're having issues again.
