### ISSUE TITLE
Show first-party subtrees without significant text in default cosmetic filtering mode

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#30202]
In standard blocking mode, elements are being unhidden if:
- the tree is first-party, _AND_
- there is no "significant text"

...when the original design was intended to unhide elements if:
- the tree is first-party, _OR_
- there is no "significant text"

This is causing unexpected behavior on https://dev-pages.bravesoftware.com/filtering/cosmetic-filtering.html, where the first-party images are being hidden because of the lack of significant text.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.53.74 Chromium: 114.0.5735.53 (Official Build) beta (x86_64)
-- | --
Revision | c499d7ea22c8b2dba278465a5df7b86a8efa4e64-refs/branch-heads/5735@{#970}
OS | macOS Version 11.7.7 (Build 20G1345)

### Steps:
1. installed `1.53.74`
2. launched Brave
3. loaded `https://dev-pages.bravesoftware.com/filtering/cosmetic-filtering.html`
4. clicked `Run tests` (with `Shields` preset to `Standard`)
5. noted values and content for both `first` and `third` partiness
6. set `Shields` to `Aggressive`
7. clicked `Run tests`

### Confirmed images for `first` parties were shown in `Standard` blocking, and with `Aggressive` blocking enabled, neither `first` nor `third` parties had images

Standard blocking | Aggressive blocking
-------------------|--------------------
<img width="1684" alt="Screen Shot 2023-05-30 at 2 54 10 PM" src="https://github.com/brave/brave-browser/assets/387249/9140ca5d-0592-479b-94dc-186ef0e07dca"> | <img width="1684" alt="Screen Shot 2023-05-30 at 2 58 28 PM" src="https://github.com/brave/brave-browser/assets/387249/bb7ceed1-77eb-4d44-a34d-aaf925c7eade">

**Comment by vlad-hoff** [comment]
Verified on `Google Pixel 7` using version(s):
```
Device/OS: Google Pixel 7 [panther_beta-user 14 UPB2.230407.014 release-keys]
Brave build: 1.53.74
Chromium: 114.0.5735.53 (Official Build) beta (64-bit)
Revision: c499d7ea22c8b2dba278465a5df7b86a8efa4e64-refs/branch-heads/5735@{#970}
```
---------------------------

**STEPS:**
1. Launch Brave > Open https://dev-pages.bravesoftware.com/filtering/cosmetic-filtering.html
2. Brave Shields > Block trackers & ads > Make sure it set to `Standard` Mode > Done
3. Tap `Run test` > Verify results
4.  Brave Shields > Block trackers & ads > Set to `Aggressive` Mode > Done
5. Tap `Run test` > Verify results

**ACTUAL RESULTS:**
- Verified that in `Standard Mode` images are shown only for `first` Partiness, but not shown for `third` Partiness
- Verified that in `Aggressive Mode` images are not shown for both `first` and `third` Partiness

|Standard|Standard|Aggressive|Aggressive|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/32fadd42-7731-4774-981e-8fa7a794def5) | ![2](https://github.com/brave/brave-browser/assets/128532965/46b34662-2d93-4314-864d-5eac700ff448) | ![3](https://github.com/brave/brave-browser/assets/128532965/e7d18759-834a-41ea-9bfb-262d164dbb87) | ![4](https://github.com/brave/brave-browser/assets/128532965/0499f20d-2a57-4fdb-93db-55a049788cc8) |

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.53.76 Chromium: 114.0.5735.90 (Official Build) beta (64-bit)
-- | --
Revision | 386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}
OS | Windows 11 Version 22H2 (Build 22621.1702)
```

Steps:

1. installed 1.53.76
2. launched Brave
3. loaded https://dev-pages.bravesoftware.com/filtering/cosmetic-filtering.html
4. clicked Run tests (with Shields preset to Standard)
5. noted values and content for both first and third partiness
6. set Shields to Aggressive
7. clicked Run tests


#### Confirmed images for first parties were shown in Standard blocking, and with Aggressive blocking enabled, neither first nor third parties had images

#### Confirmed that the images for the first parties were visible in Standard blocking, while third party elements are hidden.
#### Confirmed that no images are shown in Aggressive blocking mode in both first and third parties 


Standard | Aggressive
---- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/03cb2cdd-b22d-4248-b500-501d0d13d7a2)|![image](https://github.com/brave/brave-browser/assets/98358127/5e3461c8-ff53-49ed-b8df-67c5aaac824b)
![image](https://github.com/brave/brave-browser/assets/98358127/5d77f815-de41-4dbf-9031-6232b61d1153)|![image](https://github.com/brave/brave-browser/assets/98358127/d08ce5f9-5d12-4362-a6c8-905fadd2dac6)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.53.85 Chromium: 114.0.5735.110 (Official Build) beta (64-bit)
-- | --
Revision | 1c828682b85bbc70230a48f5e345489ec447373e-refs/branch-heads/5735_90@{#13}
OS | Linux
```


Steps:

1. installed 1.53.76
2. launched Brave
3. loaded https://dev-pages.bravesoftware.com/filtering/cosmetic-filtering.html
4. clicked Run tests (with Shields preset to Standard)
5. noted values and content for both first and third partiness
6. set Shields to Aggressive
7. clicked Run tests


#### Confirmed images for first parties were shown in Standard blocking, and with Aggressive blocking enabled, neither first nor third parties had images

#### Confirmed that the images for the first parties were visible in Standard blocking, while third party elements are hidden.
#### Confirmed that no images are shown in Aggressive blocking mode in both first and third parties 


Standard | Aggressive
---- | ----
![Screenshot from 2023-06-08 13-35-23](https://github.com/brave/brave-browser/assets/98358127/808bb2b0-aced-48d1-8664-26d8de0f92f6)|![Screenshot from 2023-06-08 13-36-53](https://github.com/brave/brave-browser/assets/98358127/5271cfdf-d40d-4feb-a33c-b7d98c1b82a6)
|![Screenshot from 2023-06-08 13-35-57](https://github.com/brave/brave-browser/assets/98358127/54506b56-8906-495c-a896-18822f3f87d3)|![Screenshot from 2023-06-08 13-37-04](https://github.com/brave/brave-browser/assets/98358127/9e515c56-0527-409f-bd9e-0f54d440c911)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung Galaxy Tab S8 Ultra` running `Android 13` using the following build(s):

```
Brave | 1.56.8 Chromium: 115.0.5790.98 (Official Build) (64-bit)
--- | ---
Revision | 4eacc220b55f07c57d5a1f4b7e0e63a6f7e420a1-refs/branch-heads/5790_90@{#4}
OS | Android 13; Build/TP1A.220624.014; 33; REL
```

**STR:**

1. Launch Brave > Open https://dev-pages.bravesoftware.com/filtering/cosmetic-filtering.html
2. Brave Shields > `Block trackers & ads` > Make sure it set to `Standard` Mode > Done
3. Tap `Run test` > Verify results
4.  Brave Shields >` Block trackers & ads` > Set to `Aggressive` Mode > Done
5. Tap `Run test` > Verify results

**ACTUAL RESULTS:**

- Verified that in `Standard Mode` images are shown only for `first` Partiness, but not shown for `third` Partiness
- Verified that in `Aggressive Mode` images are not shown for both `first` and `third` Partiness

**`Standard Mode`**

**`Example`** | `**Example`**
---------------|----------------
![Screenshot_20230719_003331_Brave](https://github.com/brave/brave-browser/assets/2602313/18fc7ef7-0f68-4685-9d72-c4afdc51b50a) | ![Screenshot_20230719_003357_Brave](https://github.com/brave/brave-browser/assets/2602313/23b77609-835b-4b77-b6ed-e754c3fc84c2)


**`Aggressive Mode`**

**`Example`** | `**Example`**
---------------|----------------
![Screenshot_20230719_003411_Brave](https://github.com/brave/brave-browser/assets/2602313/ae7e1ee8-465a-418c-9d67-691d23069ea9) | ![Screenshot_20230719_003429_Brave](https://github.com/brave/brave-browser/assets/2602313/bfbec030-1159-41d6-8056-59702bda2c7f)
