### ISSUE TITLE
[Shortcuts]: On macOS you can't create shortcuts with the Command key

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#30218]
This is because the key is sent to the backend as `Meta` but the backend only knows how to parse `Command`

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.53.81 Chromium: 114.0.5735.90 (Official Build) beta (x86_64)
-- | --
Revision | 386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}
OS | macOS Version 11.7.7 (Build 20G1345)

**Comment by fallaciousreasoning** [comment]
Note: JavaScript sometimes requires other keys to be pressed to register Meta key presses. For example, if I just press the Meta key on Linux, the shortcuts UI doesn't get any input which is a bit weird to me. I get the same results in https://css-tricks.com/snippets/javascript/javascript-keycodes/

If this turns out to be a big problem, we can add a special mojom interface, just for this and not use the existing JS key handlers.
