### ISSUE TITLE
Move Portfolio Customization Settings to Sticky Header

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#30216]
## Description 

We need to move the `Portfolio Customization Settings` out of `Wallet Settings` and into the `Portfolio Overview` sticky header.

![Screenshot 42](https://user-images.githubusercontent.com/40611140/236971122-04f16423-cab6-4972-9d17-2ce418a9e2c9.png)

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.53.104 Chromium: 115.0.5790.40 (Official Build) (64-bit)
-- | --
Revision | `071c9ddea889c3c7887daf4eac13fed72d4fff62-refs/branch-heads/5790@{#979}`
OS | Linux

- Verified steps from [brave/brave-core#18424](https://github.com/brave/brave-core/pull/18424)
- Verified Portfolio customization settings are moved in to sticky header section of Portfolio 

https://github.com/brave/brave-browser/assets/17010094/a8c1948c-574e-406c-a04c-aa6c86616566

---------------------

**Verification passed on**

Brave | 1.53.104 Chromium: 115.0.5790.40 (Official Build) (64-bit)
-- | --
Revision | `071c9ddea889c3c7887daf4eac13fed72d4fff62-refs/branch-heads/5790@{#979}`
OS | Windows 11 Version 22H2 (Build 22621.1848)

- Verified steps from [brave/brave-core#18424](https://github.com/brave/brave-core/pull/18424)
- Verified Portfolio customization settings are moved in to sticky header section of Portfolio 

https://github.com/brave/brave-browser/assets/17010094/2dadbdb4-10c2-4d54-b15b-9cc1ca234c42

---------------------

**Verification passed on**

Brave | 1.53.104 Chromium: 115.0.5790.40 (Official Build) (64-bit)
-- | --
Revision | `071c9ddea889c3c7887daf4eac13fed72d4fff62-refs/branch-heads/5790@{#979}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#18424](https://github.com/brave/brave-core/pull/18424)
- Verified Portfolio customization settings are moved in to sticky header section of Portfolio 

https://github.com/brave/brave-browser/assets/17010094/9502a173-f5c9-4692-966b-bc1adddbd8cc
