### ISSUE TITLE
URL not allowed from system network delegate: https://update.googleapis.com/service/update2/json

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#3021]
`https://update.googleapis.com/service/update2` was added to the [system network whitelist](https://github.com/brave/brave-core/blob/4a40853b887971aa6444eb19bfa857e6447a38d8/browser/net/brave_static_redirect_network_delegate_helper.cc#L47) in brave/brave-core#406 in order to fix #163.

However, I see messages like this on my terminal though when I run master:

    ERROR:brave_static_redirect_network_delegate_helper.cc(79)] URL not allowed from system network delegate: https://update.googleapis.com/service/update2/json

`https://update.googleapis.com/service/update2/json` is one of the two component updater endpoints defined in https://cs.chromium.org/chromium/src/components/component_updater/component_updater_url_constants.cc?rcl=85a8aae0b6208c2a76d1a6e6c0c617070d5df010 though it's missing from our whitelist.

I assume we should either whitelist both of them (assuming this is required for non-supported extensions from the Chrome store) or neither.

**Comment by rebron** [comment]
cc: @jumde is this fixed with the proxy pr? If so, can we close this one.

**Comment by jumde** [comment]
@rebron - This should be fixed by the changes made in `go-updater`. The changes have not yet been pushed to production yet, will keep it assigned to myself and test it again when the changes land in production.

**Comment by fmarier** [comment]
I can't reproduce this anymore and so I'll assume it's fixed.
