### ISSUE TITLE
[hackerone] unexpected payload of EIP-712

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#30212]
https://hackerone.com/reports/1974397

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.53.94 Chromium: 114.0.5735.133 (Official Build) beta (64-bit)
-- | --
Revision | `fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}`
OS | Linux

- Verified steps form issue description and [brave-core#17292](https://github.com/brave/brave-core/pull/17292)
- Verified no crash when clicking on sign


https://github.com/brave/brave-browser/assets/17010094/505b3645-0caa-488f-9803-eec025e15874

**Comment by kjozwiak** [comment]
The above requires `1.52.130` or higher for `1.52.x` verification. Removing `QA Pass-Win64` as this will need to be re-checked with `1.52.x`.

**Comment by srirambv** [comment]
Verification passed on  

Brave | 1.52.130 Chromium: 114.0.5735.198 (Official Build) (64-bit)
-- | --
Revision | `c3029382d11c5f499e4fc317353a43d411a5ce1c-refs/branch-heads/5735@{#1394}`
OS | Linux

- Verified steps form issue description and [brave-core#17292](https://github.com/brave/brave-core/pull/17292)
- Verified no crash when clicking on sign

https://github.com/brave/brave-browser/assets/17010094/0f2bcf19-ccfb-4a8f-a128-9a293d84ffcb
