### ISSUE TITLE
Sent address are shown as `***` instead of the actual address

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#30223]
## Description 

Sent address are shown as `***` instead of the actual address

## Steps to Reproduce

   1. Submit transactions on `https://pwgoom.csb.app`
   2. Open activity tab
   3. Transaction shows `account -> ***`  instead of `account1 -> address`

## Actual result:

Activity Tab | Account details 
-- | --
![image](https://user-images.githubusercontent.com/17010094/237045781-7d7eb1bf-e944-4135-b8a2-ad61c656de89.png) | ![image](https://user-images.githubusercontent.com/17010094/237045879-dbc83b9f-3b65-4d9f-8e10-10727685590c.png)

## Expected result:
Show proper address

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.52.92 Chromium: 113.0.5672.92 (Official Build) beta (64-bit)
-- | --
Revision | `b6f521170062a1fa8a82c33fb223b06fec566da1-refs/branch-heads/5672_63@{#10}`
OS | Windows 11 Version 22H2 (Build 22621.1635)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Not checked

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @josheleonard @Douglashdaniel

**Comment by StephenHeaps** [comment]
Potentially related to Solana Versioned Transactions: https://github.com/brave/brave-browser/issues/29543

<img width="691" alt="230225671-ec0d1381-e9c8-4484-8b04-f6b9ae8cf3fa" src="https://user-images.githubusercontent.com/4730197/230225671-ec0d1381-e9c8-4484-8b04-f6b9ae8cf3fa.png">

> Transaction on the top is using an account stored on chain, so we would not wrongly show the address table lookup account as the receiver but shows ***. The other transaction is a legacy transaction and uses static accounts (no tables involved) only, so receiver is shown here.

**Comment by Douglashdaniel** [comment]
Tested with the new `Activity` tab, is no longer an issue now. Closing as `invalid`

![Screenshot 77](https://github.com/brave/brave-browser/assets/40611140/287c7e00-03c9-4c29-b5a0-a2177837a4fa)

![Screenshot 78](https://github.com/brave/brave-browser/assets/40611140/deaae859-980f-427e-b5f0-657b73463bca)
