### ISSUE TITLE
Remove empty button from solana transaction list items

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#30226]
## Description 

An empty button is shown within listed Solana transactions. This needs to be removed.
![image (1)](https://github.com/brave/brave-browser/assets/30185185/6204a59e-adbc-4dfb-80cb-6705ea5d8307)

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.53.100 Chromium: 114.0.5735.133 (Official Build) beta (64-bit)
-- | --
Revision | `fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}`
OS | Linux

- Verified steps from [brave/brave-core#18420](https://github.com/brave/brave-core/pull/18420)
- Verified button is removed from Solana transaction list item 
- Verified button is not shown for sending tokens/NFT or Swaping tokens
![image](https://github.com/brave/brave-browser/assets/17010094/0ae2b2db-10a3-4d94-81e0-a01a6d276f5d)


---------------------

**Verification passed on**

Brave | 1.53.100 Chromium: 114.0.5735.133 (Official Build) beta (64-bit)
-- | --
Revision | `fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}`
OS | Windows 11 Version 22H2 (Build 22621.1848)

- Verified steps from [brave/brave-core#18420](https://github.com/brave/brave-core/pull/18420)
- Verified button is removed from Solana transaction list item 
![brave_QNAy9nFLGg](https://github.com/brave/brave-browser/assets/17010094/4bb13c85-f22b-4c9b-8f77-ace6af38acbf)

---------------------

**Verification passed on**

Brave | 1.53.100 Chromium: 114.0.5735.133 (Official Build) beta (64-bit)
-- | --
Revision | `fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#18420](https://github.com/brave/brave-core/pull/18420)
- Verified button is removed from Solana transaction list item 
![image](https://github.com/brave/brave-browser/assets/17010094/12a75246-6186-402b-9224-60f2761a32f0)
