### ISSUE TITLE
Some transactions are not properly aligned in activity tab

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#30224]
## Description 

Some transactions are not properly aligned in activity tab

## Steps to Reproduce

   1. Submit multiple transactions
   2. Open activity tab
   3. All transaction data is not properly aligned 

## Actual result:

Activity Tab | Account details 
-- | --
![image](https://user-images.githubusercontent.com/17010094/237045781-7d7eb1bf-e944-4135-b8a2-ad61c656de89.png) | ![image](https://user-images.githubusercontent.com/17010094/237045879-dbc83b9f-3b65-4d9f-8e10-10727685590c.png)

## Expected result:
Align properly 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.52.92 Chromium: 113.0.5672.92 (Official Build) beta (64-bit)
-- | --
Revision | `b6f521170062a1fa8a82c33fb223b06fec566da1-refs/branch-heads/5672_63@{#10}`
OS | Windows 11 Version 22H2 (Build 22621.1635)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Not checked

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @josheleonard @Douglashdaniel

**Comment by josheleonard** [comment]
@srirambv, is this occurring with the new activity designs?

**Comment by srirambv** [comment]
This is not an issue anymore with new activity designs. Closing as stale
