### ISSUE TITLE
Update Gemini promo card on brave://rewards page (May 2023)

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#30230]
## Description 

Replace current text with the following text:

>**Sign up to Gemini to store your BAT securely**
Connect Brave Rewards to Gemini to receive your BAT earnings directly to your Gemini account. Gemini is a full reserve and highly regulated cryptocurrency exchange and custodian. 
>
>Millions of customers in 70+ countries choose Gemini to buy, sell, store, and stake over 90+ cryptos with ease.

This currently exceeds the word limits, but let's adjust the styling to accommodate. 

Make sure this promo card only appears for US.

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.53.76 Chromium: 114.0.5735.90 (Official Build) beta (64-bit)
-- | --
Revision | 386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}
OS | Windows 10 Version 22H2 (Build 19045.2965)

```
- Confirmed that the `Gemini promo card` is available only for US region
- Confirmed that the text in the promo card is as per the description text 

```
Connect Brave Rewards to Gemini to receive your BAT earnings directly to your Gemini account. Gemini is a full reserve and highly regulated cryptocurrency exchange and custodian.

Millions of customers in 70+ countries choose Gemini to buy, sell, store, and stake over 90+ cryptos with ease.
```


**`1.52.x`** | **`1.53.x`**
-------------|-----------
![image](https://github.com/brave/brave-browser/assets/38657976/8d8208c9-be75-4b50-a85c-147bd8b55253) | ![image](https://github.com/brave/brave-browser/assets/38657976/69bbaa59-5fcd-4064-bacb-6482934be427)
