### ISSUE TITLE
Create reusable component for pending transaction fee + network settings

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#30235]
## Description 

Create reusable component for pending transaction fee + network settings so that the values and controls can be reused within different transaction confirmation components

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
This is blocked on https://github.com/brave/brave-browser/issues/31883

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/31883#issuecomment-1661632834. Verified Network fee settings is working as expected and shows the correct values
