### ISSUE TITLE
Add confirmation dialog after first establishing a monthly tip that indicates amount and date of first tip

### ISSUE THREAD

**Issue by davidtemkin** [brave/brave-browser#3023]
After a user has set up a monthly tip using the tipping panel, a confirmation dialog should appear in place of the current simple "Thank you" dialog that says thank you, and also indicates the name of the site being tipped, amount of monthly tip, and the date on which the first tip will be sent.

**Comment by ryanml** [comment]
Design to be implemented:

![image](https://user-images.githubusercontent.com/8732757/51435914-eb6fc980-1c3f-11e9-99d4-10550d4bf069.png)

**Comment by NejcZdovc** [comment]
note that there should be letter/logo instead of paper plane, like we have it now

**Comment by kjozwiak** [comment]
Will this design also change the look of a regular tip that's not set as recurring? Assuming yes. Could we get a design added into the issue with both recurring and none-recurring implementations? Assuming it will look similar to the above but removing the `Monthly` and `Your first monthly tip will be sent on` parts for none-recurring tips.

**Comment by kjozwiak** [comment]
> Will this design also change the look of a regular tip that's not set as recurring? Assuming yes. Could we get a design added into the issue with both recurring and none-recurring implementations? Assuming it will look similar to the above but removing the `Monthly` and `Your first monthly tip will be sent on` parts for none-recurring tips.

Closing the loop here, both designs for recurring and none-recurring tips are outlined in https://github.com/brave/brave-core/pull/1433.

**Comment by davidtemkin** [comment]
@jenn-rhim see @kjozwiak above

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.61.37 Chromium: 73.0.3683.39 (Official Build) beta (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

Used test plan from https://github.com/brave/brave-core/pull/1433

twitch verified
![image](https://user-images.githubusercontent.com/34715963/53377321-de8e7600-3961-11e9-8c07-9ef363829d30.png)

twitch unverified
![image](https://user-images.githubusercontent.com/34715963/53377428-46dd5780-3962-11e9-853f-e16e3a4a5b91.png)

youtube verified
![image](https://user-images.githubusercontent.com/34715963/53377519-96bc1e80-3962-11e9-8e6d-1ffec8d22c13.png)

youtube unverified
![image](https://user-images.githubusercontent.com/34715963/53377538-a76c9480-3962-11e9-8cdc-574510d7cec2.png)

site verified
![image](https://user-images.githubusercontent.com/34715963/53377563-be12eb80-3962-11e9-9e73-d0862b3b15bb.png)

site unverified
![image](https://user-images.githubusercontent.com/34715963/53377577-cec36180-3962-11e9-8b1c-47b31d86abcf.png)
