### ISSUE TITLE
Playlist menu onboarding redirection

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#30246]
We need to redirect user to the playlist feature url once user is done with onboarding from playlist menu option. 
This issue is to track the work.

**Comment by kjozwiak** [comment]
As discussed with @deeppandya via https://bravesoftware.slack.com/archives/C03MMJ4CHEZ/p1686260940735599, this issue will be added into the `master` playlist PR. This way the above won't be missed and will be verified. Reasoning is that the above code landed in `1.53.x` so the issue should stay in `1.53.x` and shouldn't be moved into other milestones.
