### ISSUE TITLE
All network button hides `Add custom asset` and `Add NFT` buttons

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#30259]
## Description 
All network button hides `Add custom asset` and `Add NFT` buttons

## Steps to reproduce 

   1. Set network to `All networks` in portfolio
   2. Go to visible asset list, can't see `Add custom asset` button
   3. Go to NFT tab and click on `Edit visible NFTs`, can't see `Add NFT` button
   4. Change network to Ethereum, buttons are visible now

## Actual result 

https://github.com/brave/brave-browser/assets/17010094/7e7a2c8f-cdc8-475a-9d5d-01febc5e2a1c

## Expected result
`All networks` button shouldn't hide `Add custom asset` and `Add NFT` buttons

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: All
   
## Brave version
1.52.92

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @simoarpe @Pavneet-Sing

**Comment by Pavneet-Sing** [comment]
Need network selector in edit visible screen and add custom asset dialog as we cannot use the default network: here'e the issue https://github.com/brave/brave-browser/issues/29552 MC support.

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.58.114 x64 Beta build
- Verified steps from issue description
- Verified `All network` dropdown is not covering up `Add custom asset` button

https://github.com/brave/brave-browser/assets/17010094/9278eeaf-550e-4ccf-9d8b-40c0e29827c9
