### ISSUE TITLE
Enabling AI chat flag adds the Brave AI button in between side bar items 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#30256]
## Description 

Enabling AI chat flag adds the Brave AI button in between side bar items 

## Steps to Reproduce

   1. Add a bunch of side bar items 
   2. Enable Brave AI Chat flag
   3. Relaunch browser, AI chat button is added in between side bar items rather than below the reading list 

## Actual result:

![image](https://github.com/brave/brave-browser/assets/17010094/866d745c-28c6-49b0-9601-089011d9e6f0)

## Expected result:
Add the button below reading list for now until position is finalized

## Reproduces how often: 

Happened once

## Brave version (brave://version info)

<html>
<body>

Brave | 1.53.26 Chromium: 113.0.5672.77 (Official Build) nightly (64-bit)
-- | --
Revision | `c4236862955e005c2187105415ac4a2ecf86dff1-refs/branch-heads/5672_62@{#3}`
OS | Windows 11 Version 22H2 (Build 22621.1702)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @petemill @rebron

**Comment by rebron** [comment]
Move AI chat button to below Wallet by default.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.60.76 Chromium: 118.0.5993.32 (Official Build) nightly (x86_64)
-- | --
Revision | c66376dd699f9327afd2f556c90b029bf4aa32e9
OS | macOS Version 11.7.10 (Build 20G1427)
```
