### ISSUE TITLE
[hackerone][Android] `Sync` settings should be behind biometrics / passcode authentication

### ISSUE THREAD

**Issue by stoletheminerals** [brave/brave-browser#30268]
More details: https://hackerone.com/reports/1975155

When pressing Sync in settings users should be prompted with biometrics/passcode authentication.

**Comment by diracdeltas** [comment]
ios issue: https://github.com/brave/brave-ios/issues/7436

**Comment by diracdeltas** [comment]
@deeppandya @anthonypkeane can we just copy the iOS behavior for now? or if it's too much friction, just enable it if password sync is enabled?

**Comment by anthonypkeane** [comment]
Slack: https://bravesoftware.slack.com/archives/C0816QH3R/p1685503730825809

**Comment by hffvld** [comment]
Verified on `Pixel 2 XL`, `Galaxy Tab S8` and `Pixel 7` using version(s):
```
Device/OS: 
- Pixel 2 XL / taimen-user  8.1.0 OPM2.171026.006.H1 release-keys
- Galaxy Tab S8 / gts8wifixx-user 13 TP1A.220624.014 release-keys
- Pixel 7 / panther_beta-user 14 U1B2.230922.013 release-keys
Brave build: 1.61.85
Chromium: 119.0.6045.163 (Official Build) beta (64-bit)
```

OR

Filed follow-up issue #
---------------------------

**PRECONDITIONS:**
- `Sync` must be preconfigured

**STEPS:**
1. Followed the steps from https://github.com/brave/brave-core/pull/19477#issue-1827034686

**ACTUAL RESULTS:**
- Verified that device `biometrics/passcode` required to enable `Passwords` or `Sync everything`
- Verified that device `biometrics/passcode` is not required during 60 seconds to re-enable `Passwords` or `Sync everything`
- Verified that device `biometrics/passcode` required to enable `Passwords` or `Sync everything` if Brave closed and relaunched
- Verified that `biometrics/passcode` is not required to disable `Passwords` or `Sync everything`

---------------------------

<details>
<summary> Lock screen is enabled on the device </summary>

<details>
<summary> Pixel 2 XL / Android 8 </summary>

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/7136824d-6d76-429e-9846-a41022c0f426) | ![2](https://github.com/brave/brave-browser/assets/128532965/fe7dee3c-a37f-4c10-bc7f-b5bafc1303a4) |

https://github.com/brave/brave-browser/assets/128532965/e0f99740-7962-4dfd-8758-cc13300aa556

</details>

<details>
<summary> Galaxy Tab S8 / Android 13 </summary>



</details>

<details>
<summary> Pixel 7 / Android 14 </summary>



</details>
