### ISSUE TITLE
[Android] YT recommended content filter - update toggle copy

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#30263]
## Description
We decided to not hide youtube home screen recommended content when the hide recommended content filter is enabled.

Please update the toggle copy to reflect that. Remove "home screen" from the copy.

![image](https://github.com/brave/brave-browser/assets/28269287/25063d4d-23e1-4523-8406-3e448d722984)

**Comment by kjozwiak** [comment]
@brave/qa-team can use https://github.com/brave/brave-core/pull/18447#issuecomment-1560045549 as the example of what's expected in terms of string changes.

**Comment by kjozwiak** [comment]
The above requires `1.52.110` or higher for `1.52.x` verification 👍

**Comment by vlad-hoff** [comment]
Verified on `Google Pixel 7` using version(s):
```
Device/OS: Google Pixel 7 [panther_beta-user 14 UPB2.230407.014 release-keys]
Brave build: 1.52.112
Chromium: 114.0.5735.35 (Official Build) (64-bit)
Revision: 2295354895fa3652ae47b651481831484f16d1ff-refs/branch-heads/5735@{#713}
```
---------------------------

**STEPS:**
1. Launch Brave > Hamburger Menu > Settings
2. Brave Shields & privacy > YouTube > `Block YouTube recommended content` > Verify subtitle string
3. Confirm/Turn off the toggle switch for `Block YouTube recommended content`
4. Open `youtube.com` > Verify Manin page content
5. Open any video > Verify page content
6. Open settings once again > Turn on the toggle switch for `Block YouTube recommended content`
7. Return to `youtube.com` > Refresh the page > Verify Manin page content
8. Open any video > Verify page content

**ACTUAL RESULTS:**
- Verified subtitle string is `Blocks the up next and end card elements on youtube.com`
- Verified that recommended content on YouTube Home Screen is not hidden when `Block YouTube recommended content` filter is enabled
- Verified that other recommended videos are not shown on the page of a specific video

<details>
<summary> Block YouTube recommended content is OFF - PASS </summary>

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/aebc5541-7f7f-45fb-9b57-3914de872135) | ![2](https://github.com/brave/brave-browser/assets/128532965/cdad46ce-5a8d-46ae-bf84-b24e16d62f1f) | ![3](https://github.com/brave/brave-browser/assets/128532965/d0f101f3-145b-4c2e-8030-5b697e265667) |
</details>

<details>
<summary> Block YouTube recommended content is ON - PASS </summary>

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/7dba36d2-1524-43bb-8d9b-cfc7482f2de2) | ![2](https://github.com/brave/brave-browser/assets/128532965/97bbc8de-1364-46af-9b08-b00a2fef925f) | ![3](https://github.com/brave/brave-browser/assets/128532965/83737cab-9ec0-4a76-9c43-431473165263) |
</details>
