### ISSUE TITLE
Browser crashes when cancelling edit gas screen

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#30261]
## Description 
Browser crashes when cancelling edit gas screen

## Steps to reproduce 

   1. Initiate a swap 
   2. Select edit on the transaction screen
   3. Select Cancel
   4. Browser crashes

## Actual result 
Browser crash when canceling on edit gas fee screen

Crash ID: `c92b0000-fde7-110a-0000-000000000000`
Backtrace link for the crash: https://share.backtrace.io/api/share/B3wAo3eUqnSox1x3mZPU8Cb0

## Expected result
No crash

## Issue reproduces how often 
1.51.114 and 1.52.92

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Not checked

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 13
   
## Brave version
Release and Beta builds

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @SergeyZhukovsky @vadimstruts @Pavneet-Sing @simoarpe

**Comment by iefremov** [comment]
stale
