### ISSUE TITLE
Use correct network instead of default for transactions list and Tx approval

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#30277]
## Description 
Currently Android is showing all transactions with invalid amount/gas (due to using default network). `getAllTransactionInfo` needs a chain_id to get network specific transactions.

## Steps to reproduce 

   1. Open account details
   2. Create transactions on multiple networks having same coin type
   3. View list of transactions showing all transaction with invalid balance/gas for the same account

## Actual result 
Showing all transaction instead of network specific tx with invalid amount/gas by using the current selected network.
All transactions are not BNB tx, but are Sol or Eth.

![Screenshot from 2023-05-11 16-49-59](https://github.com/brave/brave-browser/assets/11755381/f2d5fbf0-77a9-4dc9-9c4f-3bf1ffa9bb32)

## Expected result
Correct network and gas on transactions list or tx approval

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.53.94 x64 Beta build
- Verified steps from [brave/brave-core#18477](https://github.com/brave/brave-core/pull/18477)
- Verified correct network name and token details are shown for unapproved transactions under account details 
- Verified Solana account only shows unapproved Solana transactions
- Verified Ethereum Account only shows unapproved Ethereum and EVM transactions 

https://github.com/brave/brave-browser/assets/17010094/f122a1e4-36ec-4e45-8777-2085e9fd0a38
