### ISSUE TITLE
Use consistent naming for "fingerprinting" / "device recognition"

### ISSUE THREAD

**Issue by agentofuser** [brave/brave-browser#3027]
## Description 
Global shield settings has a dropdown for "Fingerprinting protection," whereas per-site shield settings features a "device recognition" dropdown. I guess these refer to the same thing, but it is not obvious. It would be better to use consistent wording for this feature.

## Steps to Reproduce

   1. Open brave://settings
   2. Search for "shield"
   3. Note label saying "Fingerprinting protection"
   4. Open brave.com
   5. Click Brave shield icon
   6. Note dropdown with string "Device recognition"

## Actual result:
Global shield settings use "Fingerprinting", domain-specific shield settings use "device recognition."

## Expected result:
UI should use "device recognition" everywhere consistently.

## Reproduces how often: 
Always

## Brave version (brave://version info)
Brave | 0.60.15 Chromium: 72.0.3626.53 (Official Build) dev(64-bit)
Revision | 98434e6cd182d68ce396daa92e9c6310422e6763-refs/branch-heads/3626@{#620}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds?
Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by srirambv** [comment]
cc: @karenkliu @bradleyrichter

**Comment by karenkliu** [comment]
^^^ It should be "device recognition" everywhere.

**Comment by agentofuser** [comment]
Isn't this a bit inaccurate though? If a laptop is used by multiple people who each have their own user profile, fingerprinting could detect who the current _user_ is by looking at installed extensions and other user-specific settings, thereby inferring more information than just which device is being used.

**Comment by karenkliu** [comment]
@agentofuser Yes - the label "device recognition" can be misleading, but we know that "fingerprinting" is even more confusing to non-tech-savvy users than the former. Also, this group of users typically one have 1 profile per device.

This Github issue is about label consistency; the question of whether or not there is a better term than "device recognition" still requires further user research. I'm in agreement that we might still be able to come up with something better - something that is understandable to power users *and* the typical casual user.

**Comment by agentofuser** [comment]
Good point. I agree.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.68.113 Chromium: 76.0.3809.62 (Official Build) beta (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Linux

* Verified global shields settings has shields info and naming convention as mentioned in test plan
![image](https://user-images.githubusercontent.com/17010094/62138241-4fd9a880-b2b5-11e9-8576-a14843fb6ff5.png)
* Verified Shields has the same naming convention as global shields settings 
![image](https://user-images.githubusercontent.com/17010094/62138378-8d3e3600-b2b5-11e9-94b1-c8dc2c82487a.png)
