### ISSUE TITLE
Improve loading of NFTs

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#30275]
## Description 
Improve loading of NFTs

## Steps to reproduce 

   1. Add a bunch of NFTs from different networks
   2. Switch networks
   3. Image takes a long time to load
   4. Set network to all networks
   5. Images takes a long time to load 

## Actual result 
Loading of images is slow for NFTs especially when you have a bunch of them added from different networks

## Expected result
Faster image loading 

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Maybe not checked
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Most likely yes but not checked

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
All

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @simoarpe

**Comment by HEagle18** [comment]
across all networks. not anyone in specific.

**Comment by HEagle18** [comment]
maybe we can do more caching here (cc @nvonpentz ) and maybe work with simplehash @jamesmudgett

**Comment by srirambv** [comment]
This is not relevant anymore. Closing as stale
