### ISSUE TITLE
Changing network to Solana shows Select Network instead of Solana

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#30276]
## Description 
Changing network to Solana shows Select Network instead of Solana 

## Steps to reproduce 

   1. Install nightly build
   2. Go to brave://wallet/swap
   3. Change network from Solana to Ethereum
   4. Shows Ethereum icon
   5. Change back to Solana, shows Select network instead of network icon

## Actual result 

https://github.com/brave/brave-browser/assets/17010094/d71b4a67-d18b-4cc2-9d7d-8f826cae61f5

![image](https://github.com/brave/brave-browser/assets/17010094/b0832277-7c97-45db-b9a3-895b3335b348)

## Expected result
Should show the network icon

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: All
   
## Brave version
1.53.26

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @vadimstruts @SergeyZhukovsky

**Comment by kjozwiak** [comment]
The above requires `1.52.101` or higher for `1.52.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.52.112 x64 build
- Verified steps from issue description
- Verified changing network to Solana shows the network icon
- Verified changing network automatically updates the account as well

Oppo Reno 5 (Android 13) | Lenovo Tab (Android 12)
-- | --
<video src=https://github.com/brave/brave-browser/assets/17010094/2a3e1b84-a834-486d-94a0-7a1b3d256302> | <video src=https://github.com/brave/brave-browser/assets/17010094/3a1929b1-b0d6-435f-ba5f-0d3de3f0b3ec>
