### ISSUE TITLE
Implement `brave://settings/?search=` query support for Brave Ads target URLs

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#30289]

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.53.99 Chromium: 114.0.5735.133 (Official Build) beta (64-bit) 
-- | --
Revision | fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/18349


Ads are not shown when target url is `"chrome://settings/?search=ipfs` or `"brave://settings/?search=ipfs`
