### ISSUE TITLE
Implement new design for NFT details screen

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#30286]

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.53.94 Chromium: 114.0.5735.133 (Official Build) beta (64-bit)
-- | --
Revision | `fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}`
OS | Windows 11 Version 22H2 (Build 22621.1848)

- Verified steps from [brave/brave-core#18457](https://github.com/brave/brave-core/pull/18457)
- Verified NFT details screen shows the new layout
- Verified when NFT details is loaded shows IPFS pinning status
- Verified if NFT details are not loaded continues to show the error message

https://github.com/brave/brave-browser/assets/17010094/21d84456-83f0-4399-bd7a-608561b26edc
