### ISSUE TITLE
Follow up to #29313: Clicking Reminder Notification yields no action

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#30281]
Follow up to #29313

## Steps to Reproduce

1. Clean profile
1. Run Brave with 
```
--enable-logging=stderr --vmodule="*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6,"*/bat_ads/*"=6 --variations-server-url=https://test --enable-features=Reminder:remind_user_if_clicking_the_same_ad_after/1 --rewards=staging=true --use-dev-goupdater-url
```
3. Enable rewards and ads
4. View a notification ad
5. Click the notification ad
6. Click the Reminder Notification

## Actual result:

Clicking Reminder Notification yields no action

## Expected result:
Clicking Reminder Notification opens `https://support.brave.com/hc/en-us/articles/14648356808845`

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.52.93 Chromium: 113.0.5672.92 (Official Build) beta (64-bit) 
-- | --
Revision | b6f521170062a1fa8a82c33fb223b06fec566da1-refs/branch-heads/5672_63@{#10}
OS | Ubuntu 18.04 LTS

cc @tmancey @Miyayes @emerick

**Comment by kjozwiak** [comment]
The above requires `1.52.100` or higher for `1.52.x` verification 👍

**Comment by stephendonner** [comment]
## Verification `PASSED` using 

Brave | 1.52.103 Chromium: 113.0.5672.126 (Official Build) beta (x86_64)
-- | --
Revision | c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}
OS | macOS Version 13.4 (Build 22F66)

### Steps:
1. installed `1.52.103`
2. launched Brave using 
```
--enable-logging=stderr --vmodule="*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6,"*/bat_ads/*"=6 --variations-server-url=https://test --enable-features=Reminder:remind_user_if_clicking_the_same_ad_after/1 --rewards=staging=true --use-dev-goupdater-url
```
3. enabled Rewards and Ads
4. viewed a notification ad
5. clicked the notification ad

### Confirmed:
* clicking on the 1st ad notification yielded `You earn when a Brave ads notifi...` notification
* clicking on the above notification opens `https://support.brave.com/hc/en-us/articles/14648356808845` in a new tab

example | example | example | example | example
---------|---------|----------|-----------|--------
<img width="1312" alt="Screenshot 2023-05-19 at 11 04 06 AM" src="https://github.com/brave/brave-browser/assets/387249/4d291a7d-3cb1-4fe4-aab8-662517e69f11"> | <img width="1312" alt="Screenshot 2023-05-19 at 11 04 10 AM" src="https://github.com/brave/brave-browser/assets/387249/624fecde-541f-4ae1-b7a3-f479aa2ecd64"> | <img width="1312" alt="Screenshot 2023-05-19 at 11 04 20 AM" src="https://github.com/brave/brave-browser/assets/387249/8cbb962f-fcde-4db2-ba36-c9ae1fddebe5"> | <img width="1375" alt="Screenshot 2023-05-19 at 11 04 49 AM" src="https://github.com/brave/brave-browser/assets/387249/092f9241-cb3a-4beb-9be9-104798b7ebe5"> | <img width="1312" alt="Screenshot 2023-05-19 at 11 04 57 AM" src="https://github.com/brave/brave-browser/assets/387249/7ee37f54-8523-48a8-8346-fce97e427fab"> | <img width="1312" alt="Screenshot 2023-05-19 at 11 05 39 AM" src="https://github.com/brave/brave-browser/assets/387249/536948f3-17de-4eb7-9858-48005952d1f3">

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.52.109 Chromium: 114.0.5735.26 (Official Build) beta (64-bit)
-- | --
Revision | 7075cbb66f0542ac3e01ddfde6b813e7d61118a5-refs/branch-heads/5735@{#454}
OS | Windows 10 Version 22H2 (Build 19045.2965)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.52.109 Chromium: 114.0.5735.26 (Official Build) beta (64-bit)
-- | --
Revision | 7075cbb66f0542ac3e01ddfde6b813e7d61118a5-refs/branch-heads/5735@{#454}
OS | Ubuntu 18.04 LTS

Verified test plan from the description

<details>

Verified clicking on the reminder notification opens https://support.brave.com/hc/en-us/articles/14648356808845
![image](https://github.com/brave/brave-browser/assets/34715963/e8fef6cf-c639-43a3-b15a-0940ee45e773)
![image](https://github.com/brave/brave-browser/assets/34715963/062c542f-3626-4ac6-9ee7-e56f7d4e3f6b)


</details>
