### ISSUE TITLE
Option to disable Java JIT like Vanadium and Bromite

### ISSUE THREAD

**Issue by JohnBetaro** [brave/brave-browser#30283]
The title says it all, Brave will be the perfect browser balancing between security and privacy and convenience, just try to add this option because it's very important for security minded people. 

I have nothing more to ask but this option. Please consider my thoughts.

**Comment by ggttttggggtt** [comment]
Would love to see an option, or flag, to disable JIT, or ideally, an ability to toggle it per website.

**Comment by JohnBetaro** [comment]
I'm not using this browser anymore.
