### ISSUE TITLE
Follow up to #29313: Reminder notification is not shown for ntp si and Brave News inline ad

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#30280]
Follow up to #29313

### ntp si
1. Clean profile
1. Run Brave with 
```
--enable-logging=stderr --vmodule="*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6,"*/bat_ads/*"=6 --variations-server-url=https://test --enable-features=Reminder:remind_user_if_clicking_the_same_ad_after/1 --rewards=staging=true --use-dev-goupdater-url
```
3. Enable rewards and ads
4. View a ntp-si ad
5. Click the ntp si ad

### Brave News inline ad
1. Clean profile
1. Run Brave with 
```
--enable-logging=stderr --vmodule="*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6,"*/bat_ads/*"=6 --variations-server-url=https://test --enable-features=Reminder:remind_user_if_clicking_the_same_ad_after/1 --rewards=staging=true --use-dev-goupdater-url
```
3. Enable rewards and ads
4. View a inline ad
5. Click the inline ad

## Actual result:

Reminder notification is not shown

## Expected result:
Reminder notification is shown

![image](https://github.com/brave/brave-browser/assets/34715963/129c010b-e132-42b1-a60a-9859c6d7e591)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.52.93 Chromium: 113.0.5672.92 (Official Build) beta (64-bit) 
-- | --
Revision | b6f521170062a1fa8a82c33fb223b06fec566da1-refs/branch-heads/5672_63@{#10}
OS | Ubuntu 18.04 LTS

cc @tmancey @Miyayes @emerick

**Comment by Miyayes** [comment]
Thanks. This is invalid for now, since we intentionally only implemented reminder notification for the push notification ad unit for now.
