### ISSUE TITLE
Follow up to #29512 - Brave VPN Connect failed with Failed to write the VPN config

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#30291]
## Description 

Brave VPN connection is failed with `Failed to write with config` error in the VPN panel.  Tested the connection with no other VPN entries (i.e Brave VPN, Brave VPN Nightly) in the OS/Network settings.  

## Steps to Reproduce

1. Install 1.52.94
2. launch Brave
3. connect to VPN either with a new purchase in staging (or with existing prod credentials)
4. toggle On from Disconnected to Connected in the VPN panel
5. switched the server location

## Actual result:

`Failed to write to config` error shown in the VPN panel
No VPN entries are shown in the OS/Network settings

![image](https://github.com/brave/brave-browser/assets/98358127/4ee97cae-c6f0-4652-9b77-a0ac49cddf03)

## Expected result:
Brave VPN should connect successfully without errors

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.52.94 Chromium: 113.0.5672.92 (Official Build) beta (64-bit)
-- | --
Revision | b6f521170062a1fa8a82c33fb223b06fec566da1-refs/branch-heads/5672_63@{#10}
OS | Windows 11 Version 22H2 (Build 22621.1702)
```
## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
 cc: @stephendonner

**Comment by stephendonner** [comment]
@simonhong any further ideas on what the file-writing difference could be, here, affecting `1.52.x`?

I verified the hyphen-removal PR for uplift in https://github.com/brave/brave-core/pull/18466#issuecomment-1550083407, but @MadhaviSeelam and I are still having to use the workaround of first connecting to `Brave VPN` using a `release` build (to write out the `.ini` file).

**Comment by simonhong** [comment]
> @simonhong any further ideas on what the file-writing difference could be, here, affecting `1.52.x`?
> 
> I verified the hyphen-removal PR for uplift in [brave/brave-core#18466 (comment)](https://github.com/brave/brave-core/pull/18466#issuecomment-1550083407), but @MadhaviSeelam and I are still having to use the workaround of first connecting to `Brave VPN` using a `release` build (to write out the `.ini` file).

I'm trying another approach - https://github.com/brave/brave-core/pull/18510

**Comment by kjozwiak** [comment]
The above requires `1.52.107` or higher for `1.52.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.52.109 Chromium: 114.0.5735.26 (Official Build) beta (64-bit)
-- | --
Revision | 7075cbb66f0542ac3e01ddfde6b813e7d61118a5-refs/branch-heads/5735@{#454}
OS | Windows 10 Version 22H2 (Build 19045.2965)

### Steps:
1. installed `1.52.109`
2. launched Brave
3. loaded `account.bravesoftware.com`
4. clicked on `Start free trial`
5. completed Stripe checkout
6. clicked on the `VPN` button in the browser toolbar
7. toggle to `Connected`

### Confirmed I could connect to `Brave VPN` on-demand, and `BraveVPNBeta` was created without issue

example | example
----------|----------
![image](https://github.com/brave/brave-browser/assets/387249/868c10b2-6fd6-4430-bade-8f1c4573f08c) | ![image](https://github.com/brave/brave-browser/assets/387249/58966742-ab12-41a7-9035-a96d5ae3fe74)
