### ISSUE TITLE
Use versioned transactions for Jupiter swaps on Solana

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#30296]
**Excerpt from Slack:**
> We really need this in Brave Wallet to support more optimised Jupiter swaps using indirect routes.
>
> Without this feature, our swap quotes won’t be as competitive as Phantom swaps, without sacrificing on UX. If you recall, indirect routes in Jupiter require 3 sequential transactions for each swap. In order to not sacrifice on UX, we only supported direct routes in our swap product.

Now that versioned transactions is live in 1.52.x (https://github.com/brave/brave-browser/issues/26042), we can make this transition and make Solana swaps more optimal.

**Comment by kjozwiak** [comment]
The above requires `1.52.101` or higher for `1.52.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.52.102 Chromium: 113.0.5672.126 (Official Build) beta (64-bit)
-- | --
Revision | `c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}`
OS | Windows 11 Version 22H2 (Build 22621.1702)

- Verified as part of [#30297 (comment)](https://github.com/brave/brave-browser/issues/30297#issuecomment-1552762322)

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.52.112 x64 build
- Verified as part of [#30297 (comment)](https://github.com/brave/brave-browser/issues/30297#issuecomment-1562742127)
