### ISSUE TITLE
Upgrade Jupiter Swap API to v4

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#30297]
From Jupiter SDK Notifications channel on Telegram:

<img width="491" src="https://github.com/brave/brave-browser/assets/3684187/ba9b968e-a256-4663-bdb5-a70a969bf22c">

We're actually on v1 API right now, so already running on fumes. The associated PR must be uplifted to 1.52.x to match versioned transactions support on Solana.

**Comment by kjozwiak** [comment]
The above requires `1.52.101` or higher for `1.52.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.52.102 Chromium: 113.0.5672.126 (Official Build) beta (64-bit)
-- | --
Revision | `c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}`
OS | Windows 11 Version 22H2 (Build 22621.1702)

- Verified steps from [brave/brave-core#18467](https://github.com/brave/brave-core/pull/18467)
- Verified able to swap SOL<-> USDC and USDC <-> SOL successfully
- Verified able to see complex routes for tokens swaps

https://github.com/brave/brave-browser/assets/17010094/41348875-bd39-45d7-9726-23d6e393b32b

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.52.112 x64 build
- Verified steps from [brave/brave-core#18467](https://github.com/brave/brave-core/pull/18467)
- Verified able to swap SOL<-> USDC and USDC <-> SOL successfully
- Verified able to see complex routes for tokens swaps

https://github.com/brave/brave-browser/assets/17010094/591541a6-5059-42fe-8e18-dabb7947b625
