### ISSUE TITLE
Replace Wallet onboarding P3A metric, add metric for new user balances

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#30292]
Replace `Brave.Wallet.OnboardingConversion.2` with the following metric:

If you accessed the Wallet onboarding page this week, where did you stop in the onboarding process?
`Brave.Wallet.OnboardingConversion.3`

0) Viewed onboarding splash
1) Between "Legal stuff" and "Create password"
2) During "recovery phrase" steps
3) Completed onboarding after completing "recovery phrase" steps
4) Completed onboarding after skipping "recovery phrase" steps

Add metric to monitor new balances shortly after wallet creation:

If you created a wallet within the last week, did you make a deposit this week? 
`Brave.Wallet.NewUserBalance`

1. Yes

Both metrics are weekly ephemeral metrics

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave | 1.54.91 Chromium: 115.0.5790.56 (Official Build) beta (64-bit)
-- | --
Revision | ebcfb87c1393f36955cfa2f6451a1767e3dc3ee5-refs/branch-heads/5790@{#1193}
OS | Windows 10 Version 22H2 (Build 19045.3086)

```

**Comment by DJAndries** [comment]
Is this happening on Android? Just tested latest 1.54.x apk and noticed the metric after two minutes of stopping the onboarding process.

**Comment by GeetaSarvadnya** [comment]
I have tested the issue on the desktop https://github.com/brave/brave-browser/issues/30292#issuecomment-1620473033

**Comment by DJAndries** [comment]
Just tested this on desktop. Are you waiting two minutes, as described in the test plan?

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.57.32`


- Verified the test plan from https://github.com/brave/brave-core/pull/18473

### Brave.Wallet.OnboardingConversion.3

<details>
<summary>Brave.Wallet.OnboardingConversion.3 = 0_</summary>

1. Clean profile `1.54.91`
2. Click on the wallet iocn in the URL bar
3. Open the onboarding 1st screen
4. Wait for 2 mins
5. Open brave://local-state file
6. Confirmed that the metrics `Brave.Wallet.OnboardingConversion.3` response value is `0` as expected

Example | Example
----------|-----------
![image](https://github.com/brave/brave-browser/assets/38657976/f04192de-c8cb-43fe-a8cf-689be07b1477) | ![image](https://github.com/brave/brave-browser/assets/38657976/ed0fe310-2ae7-4e4e-a32f-ba6eddf23613)


</details>

<details>
<summary>Brave.Wallet.OnboardingConversion.3 = 1_</summary>

**Case 3.1**

1. Clean profile `1.54.91`
2. Click on the wallet iocn in the URL bar
3. Open the onboarding 2nd screen `Legal Stuff`
4. Wait for 2 mins
5. Open brave://local-state file
6. Confirmed that the metrics `Brave.Wallet.OnboardingConversion.3` response value is `1` as expected

Example | Example
----------|-----------
![image](https://github.com/brave/brave-browser/assets/38657976/5d47b5a7-3241-4fe5-b646-961ec5be530b) | ![image](https://github.com/brave/brave-browser/assets/38657976/692fabc2-09c6-4fb4-9e5a-5604e020b933)

**Case 3.2**

1. Clean profile `1.54.91`
2. Click on the wallet iocn in the URL bar
3. Open the onboarding 3rd  screen `Create a password`
4. Wait for 2 mins
5. Open brave://local-state file
6. Confirmed that the metrics `Brave.Wallet.OnboardingConversion.3` response value is `1` as expected

Example | Example
----------|-----------
![image](https://github.com/brave/brave-browser/assets/38657976/a2554453-3438-4d51-8407-f7b81b9cafd8) | ![image](https://github.com/brave/brave-browser/assets/38657976/4b629e15-c2c8-4668-b276-f8f3d2a315a7)

</details>

<details>
<summary>Brave.Wallet.OnboardingConversion.3 = 2_</summary>

1. Clean profile `1.54.91`
2. Click on the wallet iocn in the URL bar
3. Open the "recovery phrase" steps
4. Wait for 2 mins
5. Open brave://local-state file
6. Confirmed that the metrics `Brave.Wallet.OnboardingConversion.3` response value is `2` as expected

Example | Example
----------|-----------
![image](https://github.com/brave/brave-browser/assets/38657976/c5f26aa1-39ed-4b17-a3d7-b4bd4d90ca8e) | ![image](https://github.com/brave/brave-browser/assets/38657976/33b4737a-ad23-4d25-a4bd-51513838b0f7)

</details>

<details>
<summary>Brave.Wallet.OnboardingConversion.3 = 3_</summary>

1. Clean profile `1.54.91`
2. Click on the wallet iocn in the URL bar
3. Completed onboarding after completing "recovery phrase" steps
4. Wait for 2 mins
5. Open brave://local-state file
6. Confirmed that the metrics `Brave.Wallet.OnboardingConversion.3` response value is `4` as expected

Example | Example
----------|-----------
![image](https://github.com/brave/brave-browser/assets/38657976/94c38f26-a9a9-4047-be5c-38ba6d3f5fdc)
![image](https://github.com/brave/brave-browser/assets/38657976/714a4dd5-43f7-4b57-b87c-543dc40ae23f)

</details>

<details>
<summary>Brave.Wallet.OnboardingConversion.3 = 4_</summary>

1. Clean profile `1.54.91`
2. Click on the wallet iocn in the URL bar
3. Completed onboarding after skipping "recovery phrase" steps and click on `Done`
4. Wait for 2 mins
5. Open brave://local-state file
6. Confirmed that the metrics `Brave.Wallet.OnboardingConversion.3` response value is `4` as expected

Example | Example
----------|-----------
![image](https://github.com/brave/brave-browser/assets/38657976/64613ad2-9b89-4c48-8021-dc3908c1038c) | ![image](https://github.com/brave/brave-browser/assets/38657976/eb75e142-b13f-40f5-81c1-6b7409a21090)

</details>

### Brave.Wallet.NewUserBalance

<details>
<summary>Brave.Wallet.NewUserBalance = 1_</summary>

1. Clean profile 1.54.x, launch browser using `Brave.exe --p3a-count-wallet-test-networks`
2. Create a wallet
3. Create a Ethereum accounts
4. Go to brave://settings/wallet/networks and click on 3 dot menu for `Sepolia Test Network` and click on `set as active`
5. Enable the `Show test networks` switch (now this settings is removed from 1.54.x)
6. Send Eth to Ethereum accounts via https://sepolia-faucet.pk910.de/
7. Ensured that the Eth appeared in the Ethereum account
8. Open brave://local-state file and ensured that the metrics `Brave.Wallet.ActiveEthAccounts` response value is `1` as expected

Eth account | local state
--------------|------------
![image](https://github.com/brave/brave-browser/assets/38657976/9ef29779-1c35-41de-9172-1c44fb537975) | ![image](https://github.com/brave/brave-browser/assets/38657976/88f00dc0-d239-4d2b-b3fe-4187ffa9dfdd)

9. Confirm that the both metrics `Brave.Wallet.OnboardingConversion.3` and `Brave.Wallet.NewUserBalance` flag value is set to `"sent": true,` 
10. Close the browser
11. Set the sys date ahead by 1 month
12. Reload brave://local-state file
13. Confirm that both metrics are removed from the local-state file
</details>

**Comment by GeetaSarvadnya** [comment]
@DJAndries The step 14 for the case above `Brave.Wallet.NewUserBalance` is failing. The metrics `Brave.Wallet.OnboardingConversion.3` and `Brave.Wallet.NewUserBalance` are shown in the brave://local-state file when the sys date is set ahead by 1 month. Looks like a bug could you review this from your end, please? Thanks!

**Comment by DJAndries** [comment]
@GeetaSarvadnya I'm not able to reproduce this. `Brave.Wallet.OnboardingConversion.3` disappears after advancing the system time, after the metric has been sent.

**Comment by GeetaSarvadnya** [comment]
@DJAndries I have verified the issue again on Android. The issue is still reproducible. The metrics `Brave.Wallet.OnboardingConversion.3` and `Brave.Wallet.NewUserBalance` are shown in the brave://local-state file when the sys date is set ahead by 1 month.
