### ISSUE TITLE
Implement new Rewards onboarding ("giftbox")

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#30308]
## Description

**Designs:** https://www.figma.com/file/VIkvO8TBQXVBnvKn4w8iYu/BR-onboarding?type=design&node-id=0-1

```[tasklist]
### Tasks
- [ ] Rewards panel
- [ ] NTP Rewards widget
- [ ] brave://rewards page
```

**Comment by mkarolin** [comment]
**Test Plan**

**Existing profile with Rewards enabled**
1. Open Brave with an existing profile already with Rewards already enabled.
2. Open NTP and verify that the rewards widget shows the balance and not the Onboarding slide.

**New profile**
1. Open Brave with a new profile
2. Open NTP and verify that the rewards widget shows the onboarding slide.
3. Verify that clicking the button opens the Rewards panel on the country selection slide.
4. Click outside the panel to close it
5. Navigate to brave://rewards and verify that the page shows the onboarding UI.
6. Verify that clicking the button opens the Rewards panel on the country selection slide.
7. Click outside the panel to close it
8. Click on the rewards icon to open the rewards panel
9. Verify that panel opens with the onboarding slide
10. Click "Start ..." button
11. Select country
12. Click "Continue" 
13. Click "Done"
14. Verify that the rewards tour is opened in a new tab

Also, verify any links that show on any of the slides.

**Existing pre-rewards 2.5 profile with Rewards not yet enabled**
1. Open Brave with an existing pre-rewards 2.5 profile with Rewards not yet enabled
2. Open NTP and verify that the rewards widget show the country selection slide
3. Click "Continue" and verify that the rewards panel opens on the country selection slide
4. Click outside the panel to close it
5. Click on the rewards icon to open the rewards panel
6. Verify that the rewards panel opens on the country selection slide

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave | 1.57.1 Chromium: 115.0.5790.56 (Official Build) beta (64-bit)
-- | --
Revision | ebcfb87c1393f36955cfa2f6451a1767e3dc3ee5-refs/branch-heads/5790@{#1193}
OS | Windows 10 Version 22H2 (Build 19045.3086)

```

**Comment by GeetaSarvadnya** [comment]
@mkarolin Need few clarifications on the rewards onboarding tour.

1. Content of the onboarding tour in 3rd step is not as per the spec. Is this known/expected change?

1.57.6 | Spec
------|-------
![image](https://github.com/brave/brave-browser/assets/38657976/6fa35363-7507-4b2c-9b71-93e3d44872fe) | ![image](https://github.com/brave/brave-browser/assets/38657976/f7b14b3c-1df8-49ea-a226-711cbfbb5627)

2. Click on `Done` (in the Woohoo! You’re all set! slide), `How does Brave Rewards work` or `How does it work?` opens up the rewards tour in a new tab page even though the page is already opened - Is this expeted?

cc: @Miyayes @LaurenWags

**Comment by Miyayes** [comment]
@GeetaSarvadnya Regarding content on brave.com/rewards-tour, you can skip checking that. Just make sure it loads properly and nothing obvious is wrong. The actual text / images are in flux :)

**Comment by Miyayes** [comment]
>Click on Done (in the Woohoo! You’re all set! slide), How does Brave Rewards work or How does it work? opens up the rewards tour in a new tab page even though the page is already opened - Is this expeted?

The brave.com/rewards-tour should only appear after the user is done onboarding (presses "Done", or presses "How does it work?" on the last slide of onboarding). If it opens twice, that is not expected cc: @mkarolin. 

However, if you navigated to brave.com/rewards-tour manually yourself, and then *also* went through onboarding, then it's expected that it opens another new tab with brave.com/rewards-tour, even if you already had a tab open with brave.com/rewards-tour (since there is no detection based on which tabs you already have open).

**Comment by mkarolin** [comment]
@GeetaSarvadnya regarding 2, what @Miyayes said, if you already have the tour tab opened (manually or from a previous test run) we don't check if there's one already open and we'll open a new one if you go through the onboarding and click Done or "How does it work?" link again.

Regarding 3, I didn't word it correctly. It's pre-rewards 2.5 profile where you joined rewards already, but haven't declared the locale.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.57.16 Chromium: 115.0.5790.98 (Official Build) beta (x86_64)
-- | --
Revision | d6c8a44fbe78ae6ee53d838307b4d17bec8de940
OS | macOS Version 13.4.1 (a) (Build 22F770820b)
```

**Comment by LaurenWags** [comment]
@brave/qa-team we should run through the following reduced cases on Linux (from https://github.com/brave/brave-browser/issues/30308#issuecomment-1640893065):

Existing user
- Existing user_non connected state
- Existing user_connected state
- Existing grandfathered_unverified state

New user
- Onboarding via NTP_Light theme OR Dark theme (don't need both themes, just one)
- Onboarding via a Site_Light OR Dark theme (check whichever color wasn't used in above case)

Can generally skip checking Rewards Tour per https://github.com/brave/brave-browser/issues/30308#issuecomment-1631192154

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.57.32 Chromium: 115.0.5790.114 (Official Build) beta (64-bit) 
Revision	bf9c67d9dafde9e2cc2219abd8ddfe738f316b3c
OS	Linux
```

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave	1.57.33 Chromium: 115.0.5790.114 (Official Build) beta (64-bit) 
Revision	86b4ea1d70ce73c4468d84cc8277f1f9de14b8bc
OS	Linux
```
