### ISSUE TITLE
[Android] Implement new Rewards onboarding ("giftbox")

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#30309]
## Description 

**Designs:** https://www.figma.com/file/VIkvO8TBQXVBnvKn4w8iYu/BR-onboarding?type=design&node-id=0-1

**Comment by Miyayes** [comment]
QA, please note that the brave://rewards portion was not implemented as part of the PR for this issue. It'll be implemented here: https://github.com/brave/brave-browser/issues/31592 But you can QA it as part of this larger issue.

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.58.114`

**Comment by GeetaSarvadnya** [comment]
Verification **Inprogress** on `Samsung Galaxy Tab A7 version 12` running `Bravemonoarm64.apk_1.58.121`

- Verified the Figma and description from https://github.com/brave/brave-browser/issues/30309#issue-1707984275
- Confirmed that content of the each slide is as per the Figma spec and content is inlined with Desktop
- Confirmed that animation of each slide is as per the Figma spec
- Open brave and Open a NTP and tap on the BAT logo or open any publisher page and tap on the BR panel opens up the `Start using Rewards` slide with the `How does it work?` link. Confirmed that the click on the link redirects to the https://brave.com/rewards-tour/ 
- Confirmed that click on the `Learn more` link brave rewrads page redirects to the https://brave.com/rewards-tour/ 
- Confirmed that click on `How does Brave Rewrads work?` link in the `Woohoo! You're all set!` slide redirects to https://brave.com/rewards-tour/ page
- Confirmed that click on `Done` in the `Woohoo! You're all set!` slide redirects to https://brave.com/rewards-tour/ page
- Confirmed that click on the Brave Rewards via Hamburger menu opens up the brave://rewrads page with the test message `Press the BAT icon in the URL bar to start` message as expected

**_Entry points for onboarding slides_**

Example | Example | Example
----------|----------|---------


**_Onboarding slides_**

Example | Example | Example | Example
----------|-----------|----------|---------

**Comment by GeetaSarvadnya** [comment]
@Miyayes @deeppandya : User can't scroll navigate through the onboarding slides like Android ARM. The `next` button is present to navigate through the slide also user can click on each slide header to view the content of each slide same like Desktop. I am not sure this is exepcted or should it made same like Android ARM. Figma spec doesn't have Android Tablet specifications. I just wanted to bring it to your notice.

cc: @LaurenWags

**Comment by Miyayes** [comment]
> @Miyayes @deeppandya : User can't scroll navigate through the onboarding slides in Tablet like Android ARM . The `next` button is present to navigate through the slides also user can click on each slide header to view the content of each slide same like Desktop. I am not sure this is exepcted or should it made same like Android ARM. Figma spec doesn't have Android Tablet specifications. I just wanted to bring it to your notice.
> 
> cc: @LaurenWags

I think we should file @GeetaSarvadnya

**Comment by Uni-verse** [comment]
Verified on `Pixel 2 XL` running `Android 8.1.0` using version(s)

```
Brave	1.58.122 Chromium: 117.0.5938.62 (Official Build) (64-bit) 
Revision	623437a8c792953b7bc4574f2d9ccdfd59e0ca67
OS	Android 8.1.0; Build/OPM2.171026.006.H1; 27; REL
```

Encountered: https://github.com/brave/brave-browser/issues/32988

- Verified the Figma and description from https://github.com/brave/brave-browser/issues/30309#issue-1707984275
- Confirmed that content of the each slide is as per the Figma spec and content is inlined with Desktop
- Confirmed that animation of each slide is as per the Figma spec
- Open brave and Open a NTP and tap on the BAT logo or open any publisher page and tap on the BR panel opens up the `Start using Rewards` slide with the `How does it work?` link. Confirmed that the click on the link redirects to the https://brave.com/rewards-tour/ 
- Confirmed that click on the `Learn more` link brave rewrads page redirects to the https://brave.com/rewards-tour/ 
- Confirmed that click on `How does Brave Rewrads work?` link in the `Woohoo! You're all set!` slide redirects to https://brave.com/rewards-tour/ page
- Confirmed that click on `Done` in the `Woohoo! You're all set!` slide redirects to https://brave.com/rewards-tour/ page
- Confirmed that click on the Brave Rewards via Hamburger menu opens up the brave://rewrads page with the test message `Press the BAT icon in the URL bar to start` message as expected

Example | Example | Example | Example
-|-|-|-
![Screenshot 2023-09-13 at 5 05 44 PM](https://github.com/brave/brave-browser/assets/17885425/4b5034ee-6fb4-4054-9f17-c857ca45be3e) | ![Screenshot 2023-09-13 at 5 05 57 PM](https://github.com/brave/brave-browser/assets/17885425/990fe85d-2e89-482f-b093-1c18c889fec1) | ![Screenshot 2023-09-13 at 5 36 13 PM](https://github.com/brave/brave-browser/assets/17885425/42dc4979-9462-4fde-97c3-70ccd91c0a8c) | ![Screenshot 2023-09-13 at 5 40 37 PM](https://github.com/brave/brave-browser/assets/17885425/5b8cf5fd-33c6-401c-953e-f6d930bf198b)
