### ISSUE TITLE
(Wallet) Market tab

### ISSUE THREAD

**Issue by simoarpe** [brave/brave-browser#30301]
## Description 

Integrate Market tab section.

Figma design: https://www.figma.com/file/muVcmcu4RFNu0LkXe9VRDl/Wallet-Panel?node-id=1406-218312&t=EssV5dFsjKICuh2p-0

Each Token row should show: token name, token symbol, token image, 24h price change %, price of asset.
Tapping an asset will open asset details.

![Simulator Screenshot - iPhone 14 Pro - 2023-05-12 at 11 24 04](https://github.com/brave/brave-browser/assets/3308503/d0e0b4cd-6e84-4b68-84c3-bbf127990c77)

Include shimmer effect when loading the list.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.57.18 x64 Beta build
- Verified steps from [brave/brave-core#18691](https://github.com/brave/brave-core/pull/18691)
- Verified Market tab is shown when wallet is opened
- Verified Market tab lists tokens similar to Desktop

Oppo Reno 5 (Android 13) | Lenovo Tab (Android 12)
-- | --
<video src=https://github.com/brave/brave-browser/assets/17010094/cf53abad-2419-4b1c-9346-4771f21c36f6> | <video src=https://github.com/brave/brave-browser/assets/17010094/00bac7bf-3ca2-4587-bb3c-89118e6bdb31>
