### ISSUE TITLE
Incognito window doesn't open from shortcut when a search extension is installed

### ISSUE THREAD

**Issue by sammacbeth** [brave/brave-browser#30305]
## Description 
When launching the browser directly into incognito mode via a Windows desktop shortcut, the browser fails to launch when search extensions are installed and enabled. This is the case even if these extensions are not set to run in incognito mode.

I've reproduced this issue with the DuckDuckGo Privacy Essentials extension (which was reported on [reddit](https://www.reddit.com/r/duckduckgo/comments/13du8wq/private_window_issue_with_the_ddg_extension/?utm_name=androidcss), and Ecosia extension, which makes me assume this is related to extensions that use `chrome_settings_overrides` to override the search provider.

## Steps to Reproduce

   1. Create an incognito mode desktop shortcut: Right click on the desktop -> chose new: Shortcut -> Specify the target as `"C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe" -incognito`.
   2. Install the [DuckDuckGo](https://chrome.google.com/webstore/detail/duckduckgo-privacy-essent/bkdgflcldnnnapblkhphbgpggdiikppg/related) or [Ecosia](https://chrome.google.com/webstore/detail/ecosia-the-search-engine/eedlgdlajadkbbjoobobefphmfkcchfk) extensions from the Chrome Web Store.
   3. Close all Brave windows.
   4. Double click on the shortcut.

## Actual result:
Brave does not launch.

## Expected result:
Brave launches a new incognito window.

## Reproduces how often: 
Easily reproduced. This happens every time after the extension is installed. Relaunching the browser in a normal window and disabling the extension fixes it.

## Brave version (brave://version info)

1.51.114 Chromium: 113.0.5672.92 (Official Build) (64-bit) 
Revision: b6f521170062a1fa8a82c33fb223b06fec566da1-refs/branch-heads/5672_63@{#10}
OS: Windows 11 Version 22H2 (Build 22621.1555)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by simonhong** [comment]
@sammacbeth Thanks for reporting!
It seems brave is crashed immediately. Looking.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.53.75 Chromium: 114.0.5735.58 (Official Build) beta (64-bit)
-- | --
Revision | ef012197ab4bc867d7b1dd80a001d0be7da8a714-refs/branch-heads/5735_52@{#7}
OS | Windows 11 Version 22H2 (Build 22621.1702)
```


Reproduced this issue in `1.51.x `.  Private window doesn't launch when double clicked on Brave icon on the taskbar

ex|ex|ex
--- | --- |---
![image](https://github.com/brave/brave-browser/assets/98358127/45c0bc4f-9b42-4e51-b005-9e3d94cc9d0d)|![image](https://github.com/brave/brave-browser/assets/98358127/b6c1ead0-0ccb-4435-9465-7ecedd36aa09)|![image](https://github.com/brave/brave-browser/assets/98358127/5f2b5458-8196-42ea-bb3f-3295351ec126)

Steps:

1. Installed 1.53.75
2. launched Brave
3. visit chrome.google.com/webstore in a new tab
4. search for `Ecosia` and clicked `Add to Brave` >> `Add extension`
5. verified the extension is added to `brave://extensions`
6. opened brave://settings/search 
7. verified `Ecosia` was selected and greyed out for Normal window
8. closed Brave
9. followed below steps to launch Private window 
    - right clicked on the Brave icon in the taskbar (or on the desktop) to open context menu 
    - right clicked `Brave` 
    - selected `Properties` in the context menu
    - specified the target as "C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe" -incognito.
10. double clicked the shortcut to launch Private window
11. enter `travel` in the URL  bar

- Confirmed Private windows launched successfully with `Ecosia` icon shown in the URL bar
- Search results returned using Ecosia search engine


step 4 | step 5 | step 7 | step 9a | step 9b | step 10 | step 11
---- | ----- | ----- | ----- | ----- | ----- | ---- 
<image width="700" alt = "image" src="https://github.com/brave/brave-browser/assets/98358127/77adc495-ad40-43be-9ace-ff57dd81366e">|<image width="700" alt = "image" src="https://github.com/brave/brave-browser/assets/98358127/9625f3c1-ba85-4174-90e0-aa6d152ccd61">|<image width="700" alt = "image" src="https://github.com/brave/brave-browser/assets/98358127/7871f107-0b30-4e40-8ece-ff2b4d94cff6">|<image width="700" alt = "image" src="https://github.com/brave/brave-browser/assets/98358127/237be606-dc5c-406f-b9a4-775aaac8c5e8">|<image width="700" alt = "image" src="https://github.com/brave/brave-browser/assets/98358127/47d2831c-1a6b-403c-8015-3c1b7d778c52">|<image width="700" alt = "image" src="https://github.com/brave/brave-browser/assets/98358127/69572f83-a007-44b4-979d-3037758774e7">|<image width="700" alt = "image" src="https://github.com/brave/brave-browser/assets/98358127/cc035f49-f1ff-4754-952a-e18dc2b1984c">
