### ISSUE TITLE
Compatibility with Brightcove player 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#3031]
## Description 

Brave has compatibility issues with brightcove player which is used on sites. Video fails to play even when shields is down. This has been an [issue](https://github.com/brave/browser-laptop/issues?q=is%3Aissue+brightcove+is%3Aclosed) on muon as well for good number of sites. 

## Steps to Reproduce

   1. Visit [this link](https://www.aljazeera.com/programmes/countingthecost/2019/01/economic-toll-britain-brexit-chaos-190119082641310.html)
   2. Try playing video with shields up, play button doesn't work
   3. Disable shields, if you are in luck video player starts but if you aren't goes into an infinite loop

## Actual result:

![screenshot from 2019-01-21 15-09-58](https://user-images.githubusercontent.com/17010094/51465782-a27a5b00-1d8e-11e9-8295-509d6ae87517.png)
With shields down when it plays
![screenshot from 2019-01-21 15-10-46](https://user-images.githubusercontent.com/17010094/51466267-c5f1d580-1d8f-11e9-903e-57781fca3136.png)

## Expected result:
Should play irrespective of shields settings. Should have a site hack for brightcove player to make it work

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.58.21 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | All

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes same on dev/beta

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
Sometimes not always not sure why
- Is the issue reproducible on the latest version of Chrome? 
Works on Chrome with uBlock Origin. Takes around 8secs before the video starts playing
![screenshot from 2019-01-21 15-16-13](https://user-images.githubusercontent.com/17010094/51466183-98a52780-1d8f-11e9-8d92-9c11b3a49dc9.png)

### Additional Information

cc: @bbondy

**Comment by mrzealot** [comment]
Spent some time on this as a case study, here's what I found:

The "sometimes it starts, sometimes it doesn't" seems related to the default autoplay blocking (which does pop up in the address bar). Allowing it caused reliable video starts for me, while the default behavior seemed to loop until a initiated a seek event, played pause/play again, etc. These probably overrode the need for autostart by issuing an explicit play command on the video.

The "whether it starts at all" part is 3rd-party cookie related within the shields. Brightcove itself shouldn't require cookies at all ([policy](https://support.brightcove.com/brightcove-player-cookies)), but there is an integration with [Conviva](https://www.brightcove.com/en/partners/conviva) that wants to access the local storage (which I assume is considered cookie-like, and is blocked for within-an-iframe scripts by default). This causes an unexpected error in initialization so the player doesn't even get to the loading of the video file (which, again, wouldn't require cookies in itself).

Don't have a clear idea on what we should do with this yet. Maybe a "trusted embedders" list could improve the default 3rd-party blocking behavior, but then the problem becomes the compilation of that list. Detection of these "video not starting" cases could use a crawler, too.

**Comment by ryanbr** [comment]
Re-opened. This fix will allow the video player on `https://www.aljazeera.com/programmes/countingthecost/2019/01/economic-toll-britain-brexit-chaos-190119082641310.html`

**Comment by ryanbr** [comment]
@srirambv   is this resolved? just tested in Release

**Comment by ryanbr** [comment]
Before closing, did re-test this. Video working, no playback issues.
