### ISSUE TITLE
Update Approve transaction to show gas spent amount on activity tab

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#30325]
## Description 

Update Approve transaction to show gas spent amount on activity tab

## Steps to Reproduce

   1. Select a token to approve 
   2. Go to activity tab
   3. Shows empty

## Actual result:

![image](https://github.com/brave/brave-browser/assets/17010094/a130985d-6a9a-4c06-808f-0ed08eb61790)

## Expected result:
Mention only gas value spent and not the token value

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.52.94 Chromium: 113.0.5672.92 (Official Build) beta (64-bit)
-- | --
Revision | `b6f521170062a1fa8a82c33fb223b06fec566da1-refs/branch-heads/5672_63@{#10}`
OS | Windows 11 Version 22H2 (Build 22621.1702)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @josheleonard @jamesmudgett @onyb @Douglashdaniel

**Comment by josheleonard** [comment]
![Screenshot 2023-05-30 at 12 29 01 PM](https://github.co@srirambv rave/brave-browser/assets/30185185/cc117d17-8383-48de-aecc-0eb357552ba7)
@srirambv - the gas fee is displayed within tooltip of the coins icon

**Comment by josheleonard** [comment]
@HEagle18 , @srirambv  can we close this?

**Comment by josheleonard** [comment]
@srirambv, we now show the gas fee in the details modal mind if we close this?

**Comment by srirambv** [comment]
Closing as stale.
