### ISSUE TITLE
Website Holaspirit doesnt work at all

### ISSUE THREAD

**Issue by Omaha2002** [brave/brave-browser#3032]
## Description 
https://app.holaspirit.com/

## Steps to Reproduce

   1.  go to https://app.holaspirit.com
   2.  fill in username /passwd
   3.  click login

## Actual result:
Nothing happens

## Expected result:
Login to the website

## Reproduces how often: 
always

## Brave version (brave://version info)
Version 0.58.21 Chromium: 71.0.3578.98 (Official Build) (64-bit)

### Reproducible on current release:
don't know, didnt try

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
No, disabling shield doesnt help
- Is the issue reproducible on the latest version of Chrome? 
No, on Chrome the site works. (version Versie 71.0.3578.98 (Officiële build) (64-bits))

**Comment by rebron** [comment]
@Omaha2002 Do you see any errors in the console? Can you post a screenshot? Having some issues reproducing as we need to have an account for this website.
