### ISSUE TITLE
Resize handle for vertical tab strip

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#30322]
Currently, vertical tab strip has fixed width. But it'd be useful if we can resize it with a resize handle.

**Comment by spotco** [comment]
Was google-ing how to do this in brave with brave://flags/#brave-vertical-tabs enabled.
Looking forward to seeing this in - thank you very much!

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.53.67 Chromium: 114.0.5735.53 (Official Build) beta (x86_64)
-- | --
Revision | c499d7ea22c8b2dba278465a5df7b86a8efa4e64-refs/branch-heads/5735@{#970}
OS | macOS Version 11.7.7 (Build 20G1345)

Steps:
1. installed `1.53.67`
2. launched Brave
3. context-clicked my open tab
4. chose `Use Vertical Tabs`
5. played around with the dynamic tab-pane resizer

### Confirmed:
* minimum and maximum viewport sizes (see attached screenshots)
* no crashes
* chosen tab-pane width persists between new windows
* tab titles get covered and uncovered without any glyphs

example | example
---------|---------
<img width="1581" alt="Screen Shot 2023-05-26 at 6 08 39 PM" src="https://github.com/brave/brave-browser/assets/387249/1c4f9688-5e84-4e81-ae34-b290cd62f972"> | <img width="1581" alt="Screen Shot 2023-05-26 at 6 08 33 PM" src="https://github.com/brave/brave-browser/assets/387249/2c0529f6-d966-4e87-b1d3-9d477a761f4a"> 

example | example
---------|--------
<img width="1647" alt="Screen Shot 2023-05-26 at 6 14 05 PM" src="https://github.com/brave/brave-browser/assets/387249/c6879e4c-263a-4d2a-a4e6-c588a4541598"> | <img width="1647" alt="Screen Shot 2023-05-26 at 6 14 14 PM" src="https://github.com/brave/brave-browser/assets/387249/25b83c19-ffd4-4c5e-b6ff-92d5e7438610">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED`
```
Brave | 1.53.76 Chromium: 114.0.5735.90 (Official Build) beta (64-bit)
-- | --
Revision | 386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}
OS | Windows 11 Version 22H2 (Build 22621.1702)
```

Steps:
1. installed `1.53.76`
2. launched Brave
3. context-clicked my open tab
4. chose `Use Vertical Tabs`
5. played around with the dynamic tab-pane resizer

### Confirmed:
* minimum and maximum viewport sizes (see attached screenshots)
* no crashes
* chosen tab-pane width persists between new windows
* tab titles get covered and uncovered without any glyphs
* double clicked on the resizer handle to return to default width




https://github.com/brave/brave-browser/assets/98358127/a0126cc9-8765-45ba-8aae-ac049bab82ec

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.53.85 Chromium: 114.0.5735.110 (Official Build) beta (64-bit)
-- | --
Revision | 1c828682b85bbc70230a48f5e345489ec447373e-refs/branch-heads/5735_90@{#13}
OS | Linux
```

Steps:

1. installed `1.53.76`
2. launched Brave
3. context-clicked my open tab
4. chose `Use Vertical Tabs`
5. played around with the dynamic tab-pane resizer
6. closed and restarted Brave

### Confirmed:
* dragging the right side of vertical tab strip changed the width to minimum & maximum viewport sizes
* no crashes
* chosen tab-pane width persists between new windows
* tab titles get covered and uncovered without any glyphs
* double clicked on the resizer handle to return to default width
* changed width was persistent after restarting the browser.

**Comment by Sa-Ja-Di** [comment]
How does that work? Not working in the latest available beta?

**Comment by Sa-Ja-Di** [comment]
Does not work here with the right now installable 1.53.83 Beta - can not resize tabs under Windows here - how to enable this feature?

**Comment by MadhaviSeelam** [comment]
@Sa-Ja-Di   Can not resize in mouseover/minimized mode but able to resize in expanded mode.  Here is the recording. 


https://github.com/brave/brave-browser/assets/98358127/9bd3ce73-99d7-4e45-af5c-da280a21ae18

**Comment by Sa-Ja-Di** [comment]
> @Sa-Ja-Di Can not resize in mouseover/minimized mode but able to resize in expanded mode. Here is the recording.
> 
>  2023-06-08_16h59_08.mp4

@MadhaviSeelam Zero working in Windows 11 - sorry
