### ISSUE TITLE
Reducing the side bar causes the wallet navigation to overlap on the main container

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#30328]
## Description 

Reducing the side bar causes the wallet navigation to overlap on the main container

## Steps to Reproduce

   1. Reduce the size of the window horizontally
   2. Side navigation bar overlaps on the main container view

## Actual result:

https://github.com/brave/brave-browser/assets/17010094/33f0f9e8-aa08-44ee-bd9c-09d4274b874a

## Expected result:
TBD

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.52.94 Chromium: 113.0.5672.92 (Official Build) beta (64-bit)
-- | --
Revision | `b6f521170062a1fa8a82c33fb223b06fec566da1-refs/branch-heads/5672_63@{#10}`
OS | Windows 11 Version 22H2 (Build 22621.1702)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @josheleonard @Douglashdaniel @kleantzogu @jamesmudgett

**Comment by Douglashdaniel** [comment]
@srirambv this is address in https://github.com/brave/brave-core/pull/18462

`Swap` and `Send` screens are still a work in progress with the responsiveness and are waiting on design.

https://github.com/brave/brave-browser/assets/40611140/9bc1081e-c88c-4573-816b-e6056a35e729

**Comment by HEagle18** [comment]
@srirambv to confirm that this is fixed.

**Comment by srirambv** [comment]
This is fixed on Nightly and Beta. Closing as not valid
