### ISSUE TITLE
Update playlist package to reduce size [1.51.x]

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#30334]
this issue only affects release channel.
This issue is only to add new playlist package on release channel.

**Comment by kjozwiak** [comment]
Closing as the above was uplifted into `1.52.x` & `1.51.x` via https://github.com/brave/brave-core/pull/18481 & https://github.com/brave/brave-core/pull/18480. As mentioned via https://github.com/brave/brave-core/pull/18480#pullrequestreview-1427380998, QA will basically ensure that here's no obvious issues with the appl which will be checked by default when running through the manual passes. Playlist is behind a flag and not scheduled for till `1.53.x` on `Android` and `1.55.x` or `1.56.x` for `desktop`.
