### ISSUE TITLE
Turn on Sardine on for all wallet users

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#30333]
## Description 

Right now, Sardine is only turned on for US users. We want to turn it on for global wallet users now as well. They recently added global support for cards. 

link to discussion -> https://bravesoftware.slack.com/archives/C03FP409W2X/p1683817345044179

## Steps to Reproduce

   1. 
   2. 
   3. 

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Android specific issue logged https://github.com/brave/brave-browser/issues/31096. Removing `OS/Android` label
