### ISSUE TITLE
Update pre-canned tweet for contribution

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#30331]
## Description 

Per discussion via https://bravesoftware.slack.com/archives/CB0KCRCQN/p1683918270493159, when tweeting about a contribution, "BAT" should be included in the pre-canned tweet.

So for example, when you select "Share your support" on success message in tip banner 3.0, (if you're logged in to twitter), you'll get the pre-canned tweet which reads:

> I just contributed 1.25 using the Brave Browser! See how you can support your favorite creators and sites too: https://brave/com/rewards

We should add "BAT" after the value of contribution in the pre-canned tweet (1.25 in above example).

FYI @brave/qa-team I added `OS/Android` so this can be verified there as well.

## Steps to Reproduce

   1. Be logged in to twitter
   2. Have rewards enabled and connected to a custodian
   3. Navigate to a creator who is verified with same custodian as you
   4. Make a contribution
   5. On success banner, select "Share your support"
   6. View pre-canned tweet on twitter

## Actual result:

<img width="608" alt="tweet" src="https://github.com/brave/brave-browser/assets/28145373/b560391c-bff6-4a08-9443-b30de51791d9">

## Expected result:

Addition of "BAT" to pre-canned tweet

## Reproduces how often: 

easily

## Desktop Brave version:

```
Brave | 1.52.94 Chromium: 113.0.5672.92 (Official Build) beta (x86_64)
-- | --
Revision | b6f521170062a1fa8a82c33fb223b06fec566da1-refs/branch-heads/5672_63@{#10}
OS | macOS Version 13.3.1 (a) (Build 22E772610a)
```

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a, tweet is different on this version
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? probably yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @Miyayes @zenparsing

**Comment by kjozwiak** [comment]
The above requires `1.52.110` or higher for `1.52.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.52.110 Chromium: 114.0.5735.35 (Official Build) (x86_64)
-- | --
Revision | 2295354895fa3652ae47b651481831484f16d1ff-refs/branch-heads/5735@{#713}
OS | macOS Version 13.4 (Build 22F66)
```

**Comment by vlad-hoff** [comment]
Checked this with Prod build `1.52.110` and still see the old Rewards panel UI and old tweet message. This should be tested with 11.53.x1 build.

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/3d965bb1-80b4-45e2-9837-d3bb020d7e8c) | ![2](https://github.com/brave/brave-browser/assets/128532965/ae3514b4-f3e3-4935-9332-45717578e86e) |

https://github.com/brave/brave-browser/issues/28149#issuecomment-1561881094

**Comment by kjozwiak** [comment]
Moving this back into `1.52.x` as there's code that was uplifted for `desktop` via https://github.com/brave/brave-core/pull/18569. The above was already verified on `1.52.x` via https://github.com/brave/brave-browser/issues/30331#issuecomment-1561039605.

@zenparsing @deeppandya assuming we can remove the `OS/Android` label from this issue? I believe the new banner work is going to be in `1.53.x` for `Android`.

**Comment by LaurenWags** [comment]
@kjozwiak when I had logged this one I wasn't sure when/if Android would get the updated tweet text. so added https://github.com/brave/brave-browser/issues/28149#issuecomment-1561881094 on the Tip/Contribution banner 3.0 issue for Android to check tweet text.

**Comment by kjozwiak** [comment]
> @kjozwiak when I had logged this one I wasn't sure when/if Android would get the updated tweet text. so added [#28149 (comment)](https://github.com/brave/brave-browser/issues/28149#issuecomment-1561881094) on the Tip/Contribution banner 3.0 issue for Android to note for @brave/qa-team to check tweet text.

That works 👍 We can remove `OS/Android` and handle the changes via https://github.com/brave/brave-browser/issues/28149 on `Android` once we start work on `1.53.x`. @deeppandya @zenparsing let me know if you have any objections/concerns.

**Comment by deeppandya** [comment]
> > @kjozwiak when I had logged this one I wasn't sure when/if Android would get the updated tweet text. so added [#28149 (comment)](https://github.com/brave/brave-browser/issues/28149#issuecomment-1561881094) on the Tip/Contribution banner 3.0 issue for Android to note for @brave/qa-team to check tweet text.
> 
> That works 👍 We can remove `OS/Android` and handle the changes via https://github.com/brave/brave-browser/issues/28149 on `Android` once we start work on `1.53.x`. @deeppandya @zenparsing let me know if you have any objections/concerns.

Sounds good @kjozwiak
