### ISSUE TITLE
(Wallet) Turn on flag to enable Filecoin support

### ISSUE THREAD

**Issue by simoarpe** [brave/brave-browser#30342]
Related to https://github.com/brave/brave-core/pull/18144
Full discussion: https://github.com/brave/security/issues/1256#issuecomment-1545558654

## Description 

Enable support for Filecoin once these issues will be addressed:
* Implement Filecoin send action - https://github.com/brave/brave-browser/issues/30402
* Ellipsify contract address in status bar of BuySendSwapActivity - https://github.com/brave/brave-browser/issues/30340
* Show full network name in status bar of BuySendSwapActivity - https://github.com/brave/brave-browser/issues/30341

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/30402#issuecomment-1708548078
