### ISSUE TITLE
Add Hide NFTs Tab Feature

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#30345]
## Description 

We need to a hide `NFTs tab` checkbox to the `Portfolio Settings` menu.

- Unchecking the `NFTs tab` checkbox should hide the `Segmented Control` nav on the `Portfolio Overview` page
- If the user is on the `NFTs tab` and unchecks the `NFTs tab` checkbox, it should also route to the `Portfolio Assets` page

![Screenshot 57](https://github.com/brave/brave-browser/assets/40611140/bc6005d8-7fb8-4aa6-b054-a008fce95bc4)

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.53.94 Chromium: 114.0.5735.133 (Official Build) beta (64-bit)
-- | --
Revision | `fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}`
OS | Linux

- Verified steps from [brave/brave-core#18486](https://github.com/brave/brave-core/pull/18486)
- Verified `Hide NFT` option is available in `Portfolio Settings`
- Verified selected state of `Hide NFT` option is retained between page refresh
- Verified still able to see NFTs using direct route `brave://wallet/crypto/portfolio/nfts` when `Hide NFT` is enabled

https://github.com/brave/brave-browser/assets/17010094/ef65d8a9-bff2-46a9-8b4e-8797ce620746


---------------------

**Verification passed on**

Brave | 1.53.94 Chromium: 114.0.5735.133 (Official Build) beta (64-bit)
-- | --
Revision | `fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}`
OS | Windows 11 Version 22H2 (Build 22621.1848)

- Verified steps from [brave/brave-core#18486](https://github.com/brave/brave-core/pull/18486)
- Verified `Hide NFT` option is available in `Portfolio Settings`
- Verified selected state of `Hide NFT` option is retained between page refresh
- Verified still able to see NFTs using direct route `brave://wallet/crypto/portfolio/nfts` when `Hide NFT` is enabled

https://github.com/brave/brave-browser/assets/17010094/85ddf3ba-b4ce-4c91-8fb2-9fcda69ba0c9


---------------------

**Verification passed on**

Brave | 1.53.94 Chromium: 114.0.5735.133 (Official Build) beta (64-bit)
-- | --
Revision | `fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#18486](https://github.com/brave/brave-core/pull/18486)
- Verified `Hide NFT` option is available in `Portfolio Settings`
- Verified selected state of `Hide NFT` option is retained between page refresh
- Verified still able to see NFTs using direct route `brave://wallet/crypto/portfolio/nfts` when `Hide NFT` is enabled


https://github.com/brave/brave-browser/assets/17010094/5217427b-6ea0-45c0-aaa1-76652b6cd47b
