### ISSUE TITLE
WebTorrent should be responsive

### ISSUE THREAD

**Issue by rossmoody** [brave/brave-browser#3034]
## Test plan
See https://github.com/brave/brave-core/pull/1406

## Description
The WebTorrent view has a tendency to break and/or format poorly if sized down. Could use some responsive designations and a few polish tweaks to the copy. Should also likely surface copy for the ability to disable this feature in settings until a proper product/design spec can be made and put on the roadmap to address a cohesive experience with this feature. 

<img width="1021" alt="screen shot 2019-01-21 at 11 30 40 am" src="https://user-images.githubusercontent.com/29072694/51495328-c8910280-1d70-11e9-9d05-56b6b3db5c47.png">

**Comment by LaurenWags** [comment]
@rossmoody the 'Privacy Warning' in 0.60.23 doesn't exactly match the text on the screenshots in the PR. Here's what's in 0.60.23:
![screen shot 2019-02-11 at 5 03 20 pm](https://user-images.githubusercontent.com/28145373/52596758-1902f980-2e1f-11e9-9a1d-9cc3e87c4eb9.png)

Can you confirm if this Privacy Warning is what is expected?

**Comment by rossmoody** [comment]
@LaurenWags good spot. this text is intended except for that one typo. will fix today.

**Comment by LaurenWags** [comment]
thanks @rossmoody 😄

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.60.26 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/1406
* Questions/comments from https://github.com/brave/brave-browser/issues/3034#issuecomment-462513480 were addressed
* Logged https://github.com/brave/brave-browser/issues/3315 for typo
![screen shot 2019-02-11 at 6 28 36 pm](https://user-images.githubusercontent.com/28145373/52600886-18706000-2e2b-11e9-9572-00e3714d5530.png)
![screen shot 2019-02-11 at 6 28 50 pm](https://user-images.githubusercontent.com/28145373/52600889-1a3a2380-2e2b-11e9-8d00-5384d385830e.png)
![screen shot 2019-02-11 at 6 28 59 pm](https://user-images.githubusercontent.com/28145373/52600891-1c03e700-2e2b-11e9-8694-0fe2992f65f5.png)
