### ISSUE TITLE
(Wallet) Ellipsify contract address in status bar of BuySendSwapActivity

### ISSUE THREAD

**Issue by simoarpe** [brave/brave-browser#30340]
Related to https://github.com/brave/brave-core/pull/18144
Releated to https://github.com/brave/brave-browser/issues/30341
Related to https://github.com/brave/brave-browser/issues/30402

## Description 

Emerged during [security review for Filecoin support](https://github.com/brave/security/issues/1256#issuecomment-1541126523): there's evidence of attacks where attackers have found ways to specifically craft addresses in a way that can trick the user into thinking their transacting with the wrong address. Here's an [example](https://decrypt.co/125037/address-poisoning-attack-sees-scammer-make-off-1-3m-in-arb-tokens) of how that was conducted in Metamask. 
Ideally, we should display the full address to make it easier to spot these issues. If there's not enough room available, we should default to the same logic adopted by iOS where we display the first 4 and last 4 characters.

![image](https://github.com/brave/brave-browser/assets/3308503/dd601016-19d0-447f-8ad9-58186aaf9dcb)

⚠️ Note: [enable Filecoin support](https://github.com/brave/brave-browser/issues/30342) once https://github.com/brave/brave-browser/issues/30340, https://github.com/brave/brave-browser/issues/30341, and https://github.com/brave/brave-browser/issues/30402 will be addressed.

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.57.27 x64 Beta build
- Verified steps from [brave/brave-core#18862](https://github.com/brave/brave-core/pull/18862)
- Verified contract address in status bar is using `Eplises`

https://github.com/brave/brave-browser/assets/17010094/15d54d11-df84-40cb-bec9-6f9686995003
