### ISSUE TITLE
(Wallet) Show full network name in status bar of BuySendSwapActivity

### ISSUE THREAD

**Issue by simoarpe** [brave/brave-browser#30341]
Related to https://github.com/brave/brave-core/pull/18144
Related to https://github.com/brave/brave-browser/issues/30340
Related to https://github.com/brave/brave-browser/issues/30402

## Description 

Emerged during [security review for Filecoin support](https://github.com/brave/security/issues/1256#issuecomment-1541126523): with the current UI is not clearly indicative of which network the user is on as the networks are displayed with an abbreviate form. With Filecoins for example, both Filecoin mainnet and Filecoin testnet appear as the same text "Filecoin" with no way to easily differentiate which network is in use.

<img width="547" alt="Security_review_for_Filecoin_network_support_·_Issue__1256_·_brave_security" src="https://github.com/brave/brave-browser/assets/3308503/7eaed5ea-5951-4a98-81fa-9bc01bd5ec20">

⚠️ Note: [enable Filecoin support](https://github.com/brave/brave-browser/issues/30342) once https://github.com/brave/brave-browser/issues/30340, https://github.com/brave/brave-browser/issues/30341, and https://github.com/brave/brave-browser/issues/30402 will be addressed.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.57.18  x64 Beta build
- Verified steps from [brave/brave-core#18866](https://github.com/brave/brave-core/pull/18866)
- Verified full network name is shown in the Send screen

Oppo Reno 5 (Android 13) | Lenovo Tab (Android 12)
-- | --
<video src=https://github.com/brave/brave-browser/assets/17010094/a3c81289-99bf-4b8a-b485-0b173d3b92c4> | <video src=https://github.com/brave/brave-browser/assets/17010094/eb83d89e-9610-46c9-944b-c0d00e337e33>
