### ISSUE TITLE
[Android] Implement Estimated Earnings indicator 2.0 

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#30352]
## Description

```[tasklist]
### Tasks
- [x] Add new estimated earnings indicator to Rewards panel
- [x] Update other minor design changes to Rewards panel
```

Note: Change font to default Android font in this PR. Also, remove the USD values from the Rewards summary table. @sujitacharya2005 

@Miyayes for spec.

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.5719`

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Samsung Tab A7 version 12` running `Bravemonoarm64.apk_1.57.32`
