### ISSUE TITLE
Follow up of PR #18392 - Incorrect response for the metrics `Brave.Rewards.TipsSent` when 4+ tips are sent

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#30350]
## Description 

Found while testing the PR https://github.com/brave/brave-core/pull/18392

## Steps to Reproduce

   1. Follow the steps 1 to 10 from https://github.com/brave/brave-browser/issues/30133#issue-1695693750
   2. In step 10, the metrics `Brave.Rewards.TipsSent` response value is `1` instead of `2`
   3. The metrics response should be `2` as no of tips sent are 5

## Actual result:

Incorrect response for the metrics `Brave.Rewards.TipsSent` when 4+ tips are sent

Example | Example
---------|----------
![image](https://github.com/brave/brave-browser/assets/38657976/58d8e204-8158-4280-a043-6b3ae6278db8) | ![image](https://github.com/brave/brave-browser/assets/38657976/b47f3ba1-a953-4e64-8783-8b7920ccf0a0)

## Expected result:

The metrics response should be `2` as no of tips sent are 5
## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.53.42 Chromium: 113.0.5672.92 (Official Build) nightly (64-bit)
-- | --
Revision | b6f521170062a1fa8a82c33fb223b06fec566da1-refs/branch-heads/5672_63@{#10}
OS | Windows 10 Version 21H2 (Build 19044.2965)

</body>
</html>
## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? No, works as expected
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @DJAndries @mattmcalister

**Comment by DJAndries** [comment]
@GeetaSarvadnya In your steps, you sent three tips. We no longer count monthly tips twice.

**Comment by GeetaSarvadnya** [comment]
@DJAndries In the case above, I have sent 1 - one time tip, 2- monthly tips in this case 2 - one time tips are also sent simultaneously which is expected as per the implementation.

Step 4: 1- One time tip
Step 5: 1 - monthly tips, 1- One time tip
Step 7: 1 - monthly tips, 1- One time tip

>@GeetaSarvadnya In your steps, you sent three tips. We no longer count monthly tips twice.

 In the case above, only step 5 is considered?

**Comment by DJAndries** [comment]
@GeetaSarvadnya  Yes, that's correct that one time tips are sent under the hood when sending a monthly tip, but from a user/UX perspective, the user sent three tips. All of the steps you mentioned are considered, but only 1 is counted for each step.

**Comment by GeetaSarvadnya** [comment]
Tips are counted as below, metrics count falls under the bucket `1` (2 to 3 tips). This response I am already seeing in the step 2. Hence closing the issue as expected. 

```
Step 4: 1- One time tip
Step 5: 1 - monthly tip
Step 7: 1 - monthly tip
```
