### ISSUE TITLE
[hackerone] data is being displayed erroneously in wallet

### ISSUE THREAD

**Issue by kdenhartog** [brave/brave-browser#30354]
See https://hackerone.com/reports/1988349

**Comment by kjozwiak** [comment]
The above requires `1.53.103` or higher for `1.53.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on  

Brave | 1.53.104 Chromium: 115.0.5790.40 (Official Build) (64-bit)
-- | --
Revision | `071c9ddea889c3c7887daf4eac13fed72d4fff62-refs/branch-heads/5790@{#979}`
OS | Windows 11 Version 22H2 (Build 22621.1848)

- Verified steps from [brave/brave-core#18963](https://github.com/brave/brave-core/pull/18963)

https://github.com/brave/brave-browser/assets/17010094/67730ebd-6104-4d65-9501-c4165146fbf1

**Comment by srirambv** [comment]
Changes are backend only. Discussed with @onyb and verification on desktop is sufficient. Removing OS/Android label so it doesn't list on pending verifications for Android.
