### ISSUE TITLE
Hide/Unhide NFTs

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#30367]

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.53.94 Chromium: 114.0.5735.133 (Official Build) beta (64-bit)
-- | --
Revision | `fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}`
OS | Windows 11 Version 22H2 (Build 22621.1848)

- Verified steps from [brave/brave-core#18493](https://github.com/brave/brave-core/pull/18493)
- Verified able to hide NFT from menu
- Verified hidden NFTs are listed under the `Hidden` tab 
- Verified able to unhide NFTs and list it in visible NFTs

https://github.com/brave/brave-browser/assets/17010094/6d026920-2772-4c01-8909-a3c0cb22c025
