### ISSUE TITLE
[cr114 followup] Fix iOS browser prefs patch

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#30369]
In cr114, `BRAVE_MIGRATE_OBSOLETE_BROWSER_STATE_PREFS` was patched into the wrong function in `ios/chrome/browser/prefs/browser_prefs.mm` resulting in a crash in iOS.

cc: @kylehickinson

**Comment by kjozwiak** [comment]
Labelling the above as `QA/No` as there's nothing QA can do in terms of verification in terms of the desktop browser. @kylehickinson do we need to get a https://github.com/brave/brave-ios/issues created for the above? Or will the above basically be verified by default when QA starts running through `1.52` verifications with the `C114` components.

**Comment by kylehickinson** [comment]
@kjozwiak you'll catch it with the manual verifications (app launches), so qa/No is fine! 🙂

**Comment by kjozwiak** [comment]
> @kjozwiak you'll catch it with the manual verifications (app launches), so qa/No is fine! 🙂

Thanks 👍
