### ISSUE TITLE
Compatibility issue with resources.azure.com

### ISSUE THREAD

**Issue by MisinformedDNA** [brave/brave-browser#3036]
## Description 
When I go to this particular Azure URL, https://resources.azure.com/, I'm getting a Basic Auth dialog, even after authenticating directly with Microsoft.

## Steps to Reproduce

   0. _(if needed)_ Create an Azure account
   1. Go https://resources.azure.com/
   2. Enter username and then follow pages to fully authenticate

## Actual result:

![image](https://user-images.githubusercontent.com/1784452/51500511-d86e0e00-1d93-11e9-974f-79f798f5f648.png)

## Expected result:
![image](https://user-images.githubusercontent.com/1784452/51500526-eb80de00-1d93-11e9-9649-cebbe3d75e7d.png)

## Reproduces how often: 
Always

## Brave version (brave://version info)
0.58.21

### Reproducible on current release:
Repos in 0.59.26

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields?  No
- Is the issue reproducible on the latest version of Chrome?  No

**Comment by rebron** [comment]
cc: @mbacchi @mihaiplesa Can you check this out, you guys having login issues?

**Comment by mihaiplesa** [comment]
Happens to me only when previously logged in through https://portal.azure.com then go to https://resources.azure.com. Doesn't happen when not logged in or in Chrome. Tested on `0.61.22`

**Comment by ryanbr** [comment]
Not sure if you're still using brave @MisinformedDNA   Is this still an issue?

**Comment by MisinformedDNA** [comment]
My work said I can't use Brave, so I don't know. Feel free to close.
