### ISSUE TITLE
Add Help Centre link to beside 'Privacy Policy' on Swaps and change link destination

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#30372]
## Description 

Right now, we want to move the help centre link out of the network dropdown and put it beside 'privacy policy'. It should also link to https://support.brave.com/hc/en-us/categories/360001059151-Brave-Wallet rather than the wallet FAQs. This needs to be changed on android too. 

## Steps to Reproduce

   1. 
   2. 
   3. 

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.57.18 x64 Beta build
- Verified steps from [brave/brave-core#18739](https://github.com/brave/brave-core/pull/18739)
- Verified Help Centre link is shown next to the `Privacy Policy` link on Swap screen
- Verified Help Centre links to `https://support.brave.com/hc/en-us/categories/360001059151-Brave-Wallet`

Oppo Reno 5 (Android 13) | Lenovo Tab (Android 12)
-- | -- 
<video src=https://github.com/brave/brave-browser/assets/17010094/175d6974-d22b-42c9-9590-6d0bfb4a48b3> | <video src=https://github.com/brave/brave-browser/assets/17010094/c51906fd-826b-4270-86ff-e312d6a7fa0a>

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.57.23 Chromium: 115.0.5790.102 (Official Build) beta (64-bit)
-- | --
Revision | `d515871a6c6df7d2843e755c8b7dda9b744f26d6`
OS | Linux

- Verified steps from [brave/brave-core#18739](https://github.com/brave/brave-core/pull/18739)
- Verified Help Centre link is shown next to the `Privacy Policy` link on Swap screen
- Verified Help Centre links to `https://support.brave.com/hc/en-us/categories/360001059151-Brave-Wallet`

https://github.com/brave/brave-browser/assets/17010094/06c7711e-c2b8-4da3-a6d7-0eaf0e3eb9e8



---------------------

**Verification passed on**

Brave | 1.57.23 Chromium: 115.0.5790.102 (Official Build) beta (64-bit)
-- | --
Revision | `d515871a6c6df7d2843e755c8b7dda9b744f26d6`
OS | Windows 11 Version 22H2 (Build 22621.1992)

- Verified steps from [brave/brave-core#18739](https://github.com/brave/brave-core/pull/18739)
- Verified Help Centre link is shown next to the `Privacy Policy` link on Swap screen
- Verified Help Centre links to `https://support.brave.com/hc/en-us/categories/360001059151-Brave-Wallet`

https://github.com/brave/brave-browser/assets/17010094/24c84e96-2ebe-48f0-8b0e-79be8609670c


---------------------

**Verification passed on**

Brave | 1.57.23 Chromium: 115.0.5790.102 (Official Build) beta (64-bit)
-- | --
Revision | `d515871a6c6df7d2843e755c8b7dda9b744f26d6`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#18739](https://github.com/brave/brave-core/pull/18739)
- Verified Help Centre link is shown next to the `Privacy Policy` link on Swap screen
- Verified Help Centre links to `https://support.brave.com/hc/en-us/categories/360001059151-Brave-Wallet`

https://github.com/brave/brave-browser/assets/17010094/1c5464ac-fc87-4f81-8dc4-ac8eb08efd21
