### ISSUE TITLE
Ads on new tabs

### ISSUE THREAD

**Issue by AuracleTech** [brave/brave-browser#30387]
I do not wish to see this when making a new tab

![image](https://github.com/brave/brave-browser/assets/40531871/bc53e431-f412-404a-bed0-0639a2d4da5e)

**Comment by jschuhmann47** [comment]
You can click on `Customize` down there -> `Background Image` -> `Show Sponsored Images` (set it to off, it's at the bottom)

**Comment by AuracleTech** [comment]
Ok good thank you I was starting to lose it
