### ISSUE TITLE
Remove `Block third-party cookies` toggle from Cookies and site data popup in lock icon 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#30396]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/29600
Remove `Block third-party cookies` toggle from Cookies and site data popup in lock icon 
## Steps to Reproduce

   1. NA
 
## Actual result:

![image](https://github.com/brave/brave-browser/assets/38657976/8bb238a1-9679-4903-bf0e-fb36e6dfdd4c)

## Expected result:
Keep the `Manage cookies site data` but remove the `Block third-party cookies` toggle from Cookies. 
Discussion reg the toggle removal https://bravesoftware.slack.com/archives/CU5UXM3EC/p1684304100013889?thread_ts=1683915585.881759&cid=CU5UXM3EC

## Reproduces how often: 

Easy 
## Brave version (brave://version info)

Brave | 1.53.44 Chromium: 114.0.5735.26 (Official Build) nightly (64-bit)
-- | --
Revision | 7075cbb66f0542ac3e01ddfde6b813e7d61118a5-refs/branch-heads/5735@{#454}
OS | Windows 10 Version 21H2 (Build 19044.2965)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @rebron @emerick

**Comment by bridiver** [comment]
I don't think this is right, I think we want to disable the entire menu with `kPageInfoCookiesSubpage`. Exposing the cookie settings here just causes even more problems beyond what we already have with brave://settings/cookies
cc @pes10k

**Comment by kjozwiak** [comment]
As per the above, we'll want to have the above fixed before `1.52.x` ships. Hence, labelling the above as `release/blocking` and added it into the `1.52.x` milestone so it doesn't slip through the cracks.

**Comment by LaurenWags** [comment]
Adding `QA/Blocked` until this is uplifted to 1.52.x 👍🏻

**Comment by kjozwiak** [comment]
The above requires `1.52.112` or higher for `1.52.x` verification 👍 Removing `QA/Blocked`.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.52.112 Chromium: 114.0.5735.35 (Official Build) (x86_64)
-- | --
Revision | 2295354895fa3652ae47b651481831484f16d1ff-refs/branch-heads/5735@{#713}
OS | macOS Version 13.5 (Build 22G5027e)
