### ISSUE TITLE
Enable Sidebar to the right by default

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#30397]
## Description 

Enable Sidebar to the right by default for all new users. (This is a separate from work already done of moving sidebar to the right when users turn on vertical tabs).

## Steps to Reproduce

Beta/Nightly

   1. Launch a new Beta build or nightly build
   2. Side bar is set to show on left by default
   3. Enable vertical tabs
   4. Sidebar is moved to the right without a clue

Release

   1. Launch release build
   2. Side bar is set to disabled by default
   3. Enable side bar or click on the reading list button on the URL 
   4. Enable vertical tabs
   5. Sidebar is moved to the right without a clue

## Actual result:

Side bar is moved to the right side of the window when vertical tabs are enabled

## Expected result:
On Release when user enabled sidebar show it on the right by default. On Beta/Nightly have the side bar on right by default 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

All

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @rebron @sangwoo108 @simonhong @aguscruiz

**Comment by stephendonner** [comment]
Should `Side bar is set to show on right by default` read `Side bar is set to show on left by default` in the `beta/nightly` steps?

**Comment by srirambv** [comment]
Yup updated the step

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.53.67 Chromium: 114.0.5735.53 (Official Build) beta (x86_64)
-- | --
Revision | c499d7ea22c8b2dba278465a5df7b86a8efa4e64-refs/branch-heads/5735@{#970}
OS | macOS Version 11.7.7 (Build 20G1345)

### Steps:
1. installed `1.53.67`
2. launched Brave
3. checked which side sidebar defaulted to
4. also checked pref value in `brave://settings/appearance`

### Confirmed sidebar defaulted to the right

default | `brave://settings/appearance`
--------|------------------------------
<img width="1312" alt="Screen Shot 2023-05-26 at 5 28 58 PM" src="https://github.com/brave/brave-browser/assets/387249/d59825f2-bdd9-409d-840d-f6eafb8f0ee8"> | <img width="1312" alt="Screen Shot 2023-05-26 at 5 29 17 PM" src="https://github.com/brave/brave-browser/assets/387249/bb805324-15df-4c8d-a693-59901108a6ca">
