### ISSUE TITLE
Brave Verified Publisher and Send a Tip not showing at all for a Brave Verified Publisher

### ISSUE THREAD

**Issue by jfnasp** [brave/brave-browser#3039]
## Description 
Brave Verified Publisher icon and Send a Tip button do not show for a publisher that is a Brave Verified Publisher.  (SpanishDict.com)  

Seems to be similar to Issue #2816. 

## Steps to Reproduce

   1. Go to the site spanishdict.com
   2. Click on the orange triangle.
   3. Brave Verified Publisher icon and Send a Tip button never appears, even after waiting for a minute.  On other sites, whether verified (vimeo.com) or unverified (google.com), it appears about every other time.  The problem seems to be a timeout on checking the site on the Brave servers.  

## Actual result:

![image](https://user-images.githubusercontent.com/46907019/51504385-f2ace980-1d9d-11e9-909c-c7c195745b01.png)

## Expected result:
![image](https://user-images.githubusercontent.com/46907019/51504399-0c4e3100-1d9e-11e9-973f-a496aad59c4f.png)

## Brave version (brave://version info)

Brave | 0.58.21 Chromium: 71.0.3578.98 (Official Build) (64-bit)
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Windows
JavaScript | V8 7.1.302.31
Flash | (Disabled)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields?  YES.
- Is the issue reproducible on the latest version of Chrome?  

### Additional Information

Note that after contacting Spanishdict, the problem is only on my end.  They could not reproduce my problem.

**Comment by mouradski** [comment]
my site appear to be verified under windows but not on Mac OS

**Comment by NejcZdovc** [comment]
@mouradski did you just verified your site or was verified for few days now?

**Comment by mouradski** [comment]
@NejcZdovc about 3 days ago, but i tested other sites like vice.com with same issue

my site : https://www.2giga.link, as you can see it's verified under windows

**Comment by NejcZdovc** [comment]
I see it as verified on macOS. This is not platform specific. It's how up to date is your publisher_list. Will checkout logic again, maybe there is something more to it. Thank you for the report

**Comment by mouradski** [comment]
thanx @NejcZdovc for your work 

i added a screen

http://prntscr.com/mtxuo0

**Comment by mouradski** [comment]
i waited 48h and my site still not verified on mac

**Comment by bsclifton** [comment]
cc: @atsyed87 RE: @mouradski above

**Comment by atsyed87** [comment]
> i waited 48h and my site still not verified on mac

Sometimes the Rewards panel  fails to download the list of verified publishers. You can force the browser to re-download the list.

Locate the “publishers_list” file in your Brave user files directory. I’ve added the path to each file, based on OS: 

OSX: /Users/[You]/Library/Application Support/BraveSoftware/Brave-Browser-Development/Default

Windows: AppData/Local/ OR AppData/Roaming/ (look for a Brave folder; the file should be in there)

Linux: /.config/BraveSoftware/Brave-Browser-Development/Default 

The publishers_list file will be in one of these folders. Close all instances of Brave, delete the publishers_list file, and reopen the browser. Your site should come up as verified.

**Comment by mouradski** [comment]
thanks for your answer @atsyed87 

the publishers_list already contains my site   ["2giga.link",true,false,{"channel_id":"de9c1c4f-aeb8-4ec5-b773-f2b8a0388235","title":"Brave Rewards","description":

i stopped brave instance and deleted file then launched brave browser, my site still not verified

Version 0.60.48 Chromium: 72.0.3626.121 (Build officiel) (64 bits)

[publishers_list.txt](https://github.com/brave/brave-browser/files/2954258/publishers_list.txt)

**Comment by NejcZdovc** [comment]
deleting publisher list will not help. We are fixing this scenario here https://github.com/brave/brave-browser/issues/3639

**Comment by NejcZdovc** [comment]
closing as #3639 was merged
