### ISSUE TITLE
Focus MenuBar Shortcut has duplicate entries

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#30390]
Issue created from https://github.com/brave/brave-browser/issues/354#issuecomment-1487814843

Blocks #354

**Comment by stephendonner** [comment]
@fallaciousreasoning you mention `ALT` specifically; is this `Windows`-only, then?

Or does/can it apply to `macOS`, too (which has none bound to it by default).

<img width="1312" alt="Screen Shot 2023-05-30 at 10 16 40 PM" src="https://github.com/brave/brave-browser/assets/387249/57f32b9d-6a24-4435-80ca-02316e3d4440">

**Comment by fallaciousreasoning** [comment]
It applies to at least Linux and Windows (and I imagine macOS too). Sorry, I use `Alt` for `Option` and whatever it is on Linux.

The shortcut it normally shows up for is `Focus Menu Bar` because it's bound just to the `Alt` key (and it doesn't work, even in upstream Chromium, at least on Linux).

Normally shortcuts are given a key_code and a list of modifiers. Alt would normally be a modifier, but in this specific case it was being treated as a key_code, and the difference between Left Alt, Right Alt, and Alt was not being handled properly.

**Comment by stephendonner** [comment]
How's this look, @fallaciousreasoning ?

![image](https://github.com/brave/brave-browser/assets/387249/0f3bab92-73a8-4648-b486-e5d05092efbb)

**Comment by fallaciousreasoning** [comment]
That looks perfect @stephendonner - just to confirm, if you restart the browser there should still only be one Alt shortcut and one AltGr shortcut.

**Comment by stephendonner** [comment]
> That looks perfect @stephendonner - just to confirm, if you restart the browser there should still only be one Alt shortcut and one AltGr shortcut.

Confirmed, thanks!

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.53.76 Chromium: 114.0.5735.90 (Official Build) beta (64-bit)
-- | --
Revision | 386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}
OS | Windows 10 Version 22H2 (Build 19045.3031)

### Steps:
1. installed `1.53.76` 
2. launched Brave
3. set `brave://flags/#brave-commands` to `Enabled`
4. clicked `Relaunch`
5. opened `brave://settings/system/shortcuts`
6. searched for `focus menu bar`
7. examined the bound shortcut keys/sequences

### Confirmed (even after subsequent restart) that there are only two unique `Alt`/ `AltGr`

![image](https://github.com/brave/brave-browser/assets/387249/278efe79-bc41-4bda-850f-f3efd0fa4ab8)

**Comment by fallaciousreasoning** [comment]
Thanks @stephendonner!
