### ISSUE TITLE
Spacing issue in `on exit` tab in Clear browsing data modal

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#30394]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/29600
Spacing issue in `on exit` tab in Clear browsing data modal
## Steps to Reproduce

   1. NA
  

## Actual result:

![image](https://github.com/brave/brave-browser/assets/38657976/ea25e0c7-19ac-43be-9d4f-1502e203be07)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.53.44 Chromium: 114.0.5735.26 (Official Build) nightly (64-bit)
-- | --
Revision | 7075cbb66f0542ac3e01ddfde6b813e7d61118a5-refs/branch-heads/5735@{#454}
OS | Windows 10 Version 21H2 (Build 19044.2965)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @emerick @rebron

**Comment by GeetaSarvadnya** [comment]
cc: @aguscruiz

**Comment by kjozwiak** [comment]
The above requires `1.52.106` or higher for `1.52.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.52.108 Chromium: 114.0.5735.26 (Official Build) beta (64-bit)
-- | --
Revision | 7075cbb66f0542ac3e01ddfde6b813e7d61118a5-refs/branch-heads/5735@{#454}
OS | Windows 11 Version 22H2 (Build 22621.1702)
```
Installed 1.52.108
launched Brave
open `brave://settings/clearBrowserData`

Confirmed no additional space is shown in between entries in `On exit` tab


![image](https://github.com/brave/brave-browser/assets/98358127/00634cca-fe02-49a1-8667-f213f8ce24af)
