### ISSUE TITLE
Embedded YT videos doesn't show favicons on a-c list

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#3040]
## Steps to Reproduce

   1. Clean profile on release build
   2. Visit https://www.neowin.net/news/lenovo-yoga-c630-review-windows-on-arm-in-a-real-laptop-with-8gb-ram and scroll down and play the YT video
   3. Check rewards a-c list, YT doesn't show favicon, 

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/51511959-75c75180-1e29-11e9-9538-be733c436e20.png)

## Expected result:
Verified pub should show channel icon, non-verified pubs should show YT icon not generic icon

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.58.21 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
N/A
- Is the issue reproducible on the latest version of Chrome? 
No

**Comment by GeetaSarvadnya** [comment]
Reproducible on Windows 10 x64


Brave | 0.58.21 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Windows 10

**Comment by NejcZdovc** [comment]
I checked and https://www.youtube.com/channel/UCqK_cgbk6Hxmw0aAN8BC1og is not verified. So this is expected. Closing for now. @srirambv if you find this still a problem please reopen and provide new url where I can test embedded video with verified publisher. Thank you

**Comment by srirambv** [comment]
@NejcZdovc even if the publisher isn't verified, shouldn't it show default YT favicon and not generic page icon?

**Comment by NejcZdovc** [comment]
it will show yt icon when you visit youtube page. Until you visit youtube, we don't have yt favicon
