### ISSUE TITLE
Translate FEVM addresses to f410 addresses and allow to choose existing FEVM address as recipient

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#30403]
Root ticked https://github.com/brave/brave-browser/issues/30400

**Comment by kjozwiak** [comment]
The above requires `1.57.45` or higher for `1.57.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.57.45 Chromium: 116.0.5845.82 (Official Build) (64-bit)
-- | --
Revision | c43241b101a636729252df90d1a1a7b72f2a9f94
OS | Linux

- Verified steps from [brave/brave-core#19330](https://github.com/brave/brave-core/pull/19330)
- Verified sending FIL from FIL Mainnet to Ethereum network shows the warning message
- Verified sending automatically gets the FEVM address for the receiving address
- Verified able to successfully send FIL on maninet to FEVM on Ethereum network

https://github.com/brave/brave-browser/assets/17010094/c68873fb-9c4c-4f2b-a174-6f5cbfdfcf70
