### ISSUE TITLE
(Wallet) Implement Filecoin send action

### ISSUE THREAD

**Issue by simoarpe** [brave/brave-browser#30402]
![image (4)](https://github.com/brave/brave-browser/assets/3308503/ba2f4fb3-7151-423b-bada-e44b98ac53b4)

## Description 

Implement send action for Filecoins.
Values to calculate are:

```java
public String nonce;
public String gasPremium;
public String gasFeeCap;
public String gasLimit;
public String maxFee;
public String to;
public String from;
public String value;
```

Check  generated class `FilTxData`.
`BuySendSwapActivity` contains an initial check for coin type equals to Filecoin marked as `TODO`.

⚠️ Note: [enable Filecoin support](https://github.com/brave/brave-browser/issues/30342) once https://github.com/brave/brave-browser/issues/30340, https://github.com/brave/brave-browser/issues/30341, and https://github.com/brave/brave-browser/issues/30402 will be addressed.

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.58.114 x64 Beta build
- Verified steps from [brave/brave-core#18881](https://github.com/brave/brave-core/pull/18881)
- Verified able create a Filecoin account
- Verified Filecoin account is restored when restoring a wallet
- Verified able to Send FIL tokens from one account to another 
- Verified able to load the correct block explorer

https://github.com/brave/brave-browser/assets/17010094/732c1728-7786-4f6a-95af-1c79bcb7c95c
