### ISSUE TITLE
Remove BraveVPN connection when uninstalling the browser

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#30416]
## Description 

Removed browser but brave vpn connection still work and able to connect.

## Steps to Reproduce

   1. Install Brave
   2. Enable and connect BraveVpn
   3. Uninstall browser from windows

## Actual result:

Vpn connection can be used from system after uninstalling.

## Expected result:

Vpn connection should be removed with the browser.

## Reproduces how often: 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by spylogsster** [comment]
cc @bsclifton @rebron

**Comment by stephendonner** [comment]
Also @mattmcalister

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.53.75 Chromium: 114.0.5735.58 (Official Build) beta (64-bit) 
Revision | ef012197ab4bc867d7b1dd80a001d0be7da8a714-refs/branch-heads/5735_52@{#7}
OS | Windows 10 Version 22H2 (Build 19045.3031)
```

**Comment by MadhaviSeelam** [comment]
Verification `PASSED`
```
Brave | 1.53.75 Chromium: 114.0.5735.58 (Official Build) beta (64-bit)
-- | --
Revision | ef012197ab4bc867d7b1dd80a001d0be7da8a714-refs/branch-heads/5735_52@{#7}
OS | Windows 11 Version 22H2 (Build 22621.1702)
```

Steps:

1. removed any/all BraveVPN connections from previous testing
2. installed 1.53.75
3. launched Brave
4. purchased, configured, and connected to BraveVPN
5. confirmed BraveVPNBeta entry in Settings -> Network & Internet -> VPN
6. ran browserleaks.com/dns to confirm both connection to VPN (Datacamp), without DNS leaks (Cloudflare)
7. clicked Uninstall via the Brave Beta entry on Uninstall or change a program in Control Panel -> Programs -> Programs and Features
8. selected Also delete your browsing data in the Uninstall Brave dialog
9. clicked Uninstall
10. confirmed Brave VPN is removed in Installed apps / Control Panel menus
11. confirmed Microsoft Edge loaded brave.com on uninstall (usually used for Uninstall Survey)
12. confirmed BraveVPNBeta is removed from the VPN panel in Network & Internet
13. also confirmed BraveVPN* entries were removed, using the Registry Editor



step 1 | step 4 | step 5 | step 6 | step 9 | step 10 | step 11 | step 12 | step 13
---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- | ----       
<image width="750" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/c855401b-af04-46e2-9262-0dce6af6ea85">|<image width="750" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/fb68e1e3-17f7-47ed-860c-bdd61903a16f">|<image width="750" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/d08c4779-6148-4d00-9eb8-52c3e263aa36">|<image width="750" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/b5032a1e-66d1-44aa-987f-548c36cac75d">|<image width="750" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/d95ce7fc-f41a-41ec-bbda-08a190804981">|<image width="750" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/dff4c545-e2ec-4869-b032-24dc4bd727f4">|<image width="750" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/22078ec4-ce67-44e3-973b-519512a96d25">|<image width="750" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/43b40547-84c0-4a93-bebe-9e5df023d277">|<image width="750" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/123ccec4-e3e8-4440-ac8f-d0699a17cb6b">
