### ISSUE TITLE
Vertical tab pane animation feels unpolished

### ISSUE THREAD

**Issue by rillian** [brave/brave-browser#30417]
## Description 

Trying out the vertical tabs feature, I like to have the tab bar collapsed but expand on hover. Is there an animation for the open/close transition? It looks like it just blinks on. Also, the new tab `+` at the bottom shifts position between collapsed and expanded. Both of these feel unpolished.

[Demonstration of the plus shift](https://github.com/brave/brave-browser/assets/225102/320cfcb6-cd38-4283-8d7b-1bd066a03822)

The hover delay also feels sluggish sometimes. A few frames of transition might reduce the impact of transient mouse-over while making intentional opening more responsive. Or maybe something that takes into account cursor velocity and proximity to the screen edge, to optimize for Fitt's law?

## Steps to Reproduce

   1. Enable vertical tabs in brave://settings/appearance
   2. Make sure "Float on mouseover" is checked
   3. Collapse vertical tab panel
   4. Move mouse pointer in an out of the tab panel

## Actual result:

Vertical tab panel "pops" open and closed as the mouse pointer moves into and out of it. Feels janky.

## Expected result:
Interaction should feel polished and smoothly responsive.

## Reproduces how often: 

Always for me. Testing on Linux with the GTK theme.

## Brave version (brave://version info)

1.52.100 Chromium: 113.0.5672.92 (Official Build) beta (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

**Comment by rebron** [comment]
@stephendonner Linux only?

**Comment by rebron** [comment]
cc: @sangwoo108 @aguscruiz

**Comment by sangwoo108** [comment]
Yup, we should tween the width.
