### ISSUE TITLE
Update Brave VPN toolbar icon for on/off and error states

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#30410]
## Description 

Update the Brave VPN button icons to improve off, on, and error state indication for VPN subscribers.

## Design:

<img width="962" alt="Screenshot 2023-05-17 at 10 52 24 AM" src="https://github.com/brave/brave-browser/assets/5951041/9aae1102-2a02-43ed-8f94-16e9d16dbda4">

`https://www.figma.com/file/qtMYwoj3JWJO5xzwLt6j2f/Desktop-VPN?type=design&node-id=1822-19229&t=rbGaXUgJWpgnEvLd-0`

## Brave version (brave://version info)

tbd

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

cc: @aguscruiz @stephendonner

**Comment by thypon** [comment]
Nit the red off state might be excessive. Red means:

- something is broken
- stop here
- immediate attention is required

This is ~kinda worldwide universal for anybody who got a driving license.

While urgency may be good, suggesting something is broken in the default state, may be detrimental to the message.

**Comment by stephendonner** [comment]
Note for @brave/qa-team: parts of the design mockups here (particularly around VPN off states) are slightly outmoded, and are supplanted by the updated ones in https://github.com/brave/brave-browser/issues/30930 👍  (Leaving `QA/Yes` for now.)

**Comment by stephendonner** [comment]
Marking as `QA/No` in favor of https://github.com/brave/brave-browser/issues/30930#issuecomment-1616185364 which is where we're verifying these.
