### ISSUE TITLE
Cosmetic filter !important

### ISSUE THREAD

**Issue by rulatir** [brave/brave-browser#3041]
## Description 
The cosmetic filters don't work with elements that set the `display` property using the `style` attribute.

Proposed solution: in the rule created by the cosmetic filter, the `display` property should be `!important`.

Please implement!

[Detailed STR on PR]

**Comment by srirambv** [comment]
Probably covered under #904

**Comment by rulatir** [comment]
Please give it a MINUTE of your time to actually look into the issue. The element in question has an `id` attribute, so the style rule injected by the cosmetic filter is super simple:
```
#element-id {
   display: none;
}
```
But the element has `style` attribute with `display: block`, so this overrides `display: none` in the injected stylesheet. It's pure CSS as CSS behaves. Nothing to analyse further. This has **nothing** to do with wrong element being matched. Replacing the unique-selector library will not fix this. No tweaks to the selector of the cosmetic filter's rule will fix this. The element being matched is the right one, it's just that the cosmetic filter's style rule is to weak.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.69.129 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/3121
For reddit portion I had to lower shields first to show promoted posts.
