### ISSUE TITLE
Selecting specific filter causes the accounts dropdown to move to the next line

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#30429]
## Steps to Reproduce

   1. Go to portfolio and select Binance Smart Chain Mainnet or Solana Mainnet Beta 
   2. Account dropdown is moved to the next line

## Actual result:

![pSD1oTBycO](https://github.com/brave/brave-browser/assets/17010094/56018026-6e1a-4c72-8bbe-2aae2a0260dc)

## Expected result:
Resize search box to show filters in line 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.52.102 Chromium: 113.0.5672.126 (Official Build) beta (64-bit)
-- | --
Revision | `c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}`
OS | Windows 11 Version 22H2 (Build 22621.1702)

</body>
</html>
## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel @kleantzogu

**Comment by Douglashdaniel** [comment]
Dropdown filters were removed from the `Portfolio` in `Wallet V2` updates. Closing as `Invalid`

![Screenshot 74](https://github.com/brave/brave-browser/assets/40611140/c480cb1b-d58d-4058-a45a-aa2383ea9bc5)
