### ISSUE TITLE
[Custom Tabs Mode] "Open external links in Brave" toggle switch is OFF by default, but links still opened in Custom Tab Mode

### ISSUE THREAD

**Issue by vlad-hoff** [brave/brave-browser#30421]
## Description 

`Open external links in Brave` toggle switch is OFF by default, but links still open in Custom Tab Mode

## Steps to reproduce 

   1. Fresh install Brave 1.53.x > Launch the app and go through the onboarding
   2. Hamburger Menu > Settings
   3. Scroll down to see `Open external links in Brave` toggle switch > Observe, it set to OFF be default
   4. Launch Gmail, for example > Open any email that contains links > Open the link > Observe, it opened in Custom Tab Mode

## Actual result 

`Open external links in Brave` toggle switch is set to OFF by default, but links still open in Custom Tab Mode when opening it from other apps

|1.51.x|1.53.x|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/8d0e3765-208e-42f1-9cee-88825d7526e2) | ![2](https://github.com/brave/brave-browser/assets/128532965/80d8c6cb-f842-4506-a110-409056092141) |

https://github.com/brave/brave-browser/assets/128532965/87403603-012d-444d-92dc-a6f6385b52e4

## Expected result

`Open external links in Brave` toggle switch must be set to ON by default and links must be opened in Custom Tab Mode

## Issue reproduces how often 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? No
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Pixel 7 [phone]
   - Android version: Android 14 [panther_beta-user 14 UPB2.230407.014 release-keys]
   
## Brave version

Brave build: 1.53.47
Chromium: 114.0.5735.26 (Official Build) canary (64-bit)
Revision: 7075cbb66f0542ac3e01ddfde6b813e7d61118a5-refs/branch-heads/5735@{#454}

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
@vlad-hoff nice find 👍 Seems `C114` related. We'll basically need to do the following:

* fix the issue re: being able to open Brave externally via 3rd party apps even though the setting is disabled
* decide if we want to keep the above enabled like it's currently with `1.51.x` & `1.52.x` or leave it disabled

**Comment by kjozwiak** [comment]
Change related to https://github.com/brave/brave-core/pull/18316. Just need to fix the following issues:

* default value - should be enabled by default similar to `1.52.x` & `1.51.x` which have `Open tabs in Custom Tabs` enabled
* figure out why custom tabs are still being used when the feature is disabled (assuming related to default values)

As per @samartnik & @deeppandya, the above isn't related to `C114`.

**Comment by kjozwiak** [comment]
The above requires `1.53.82` or higher for `1.53.x` verification 👍
