### ISSUE TITLE
Weird KO translation of Welcome page

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#30423]
First one is eng version and next one is ko version.
<img src="https://github.com/brave/brave-browser/assets/6786187/6705d5f4-e7d9-48fe-b419-4bb11936b8b5" width="600"><img src="https://github.com/brave/brave-browser/assets/6786187/e4a4088b-b058-4644-a071-8816b4479d36" width="600">

`Privately` is translated to `남들 모르게 말이죠`. However it delivers another meaning.
`남들 모르게 말이죠` could be same meaning with `Without anyone knowing`.

I think we can remove `남들 모르게 말이죠` in ko translation.

Internal discussion about this - https://bravesoftware.slack.com/archives/C3HN7S9QD/p1684198116801569

**Comment by simonhong** [comment]
cc @rebron @mkarolin

**Comment by mkarolin** [comment]
Removed `남들 모르게 말이죠` in Transifex. The new translation will be pulled in for `1.52.x`

**Comment by mkarolin** [comment]
This should be addressed by https://github.com/brave/brave-core/pull/18664
