### ISSUE TITLE
Crash Reports are not sending automatically (Confirmed on Desktop, needs testing/confirmation for Android)

### ISSUE THREAD

**Issue by Saoiray** [brave/brave-browser#30434]
## Description 
Crash reports are not automatically uploading despite the setting **Automatically send diagnostic reports** being enabled. Through testing on this, they will upload if the User goes to **brave://crashes** a few times, but it won't send otherwise. 

## Steps to Reproduce

   1. Have Brave crash. For troubleshooting I used **brave://crash** to generate a crash. 
   2. Logs appear in local folders. Give it time and the logs remain. Some of mine have been there for a month or longer in the past.
   3. You can try exiting Brave, closing browsers, restarting the OS, etc but it still doesn't send. Crash report remains on device unless the User goes to **brave://crashes** to trigger the upload.

## Actual result:
Any crashes remain on device and never get submitted to Brave unless the User thinks to visit **brave://crashes** and/or manually decides to **Send Now**

## Expected result:

Crash reports should automatically send without any User input.

## Reproduces how often: 
Every time.

## Desktop Brave version:
Brave Version 1.51.118
This has been an ongoing occurrence since at least 2022, if not longer, so it's occurred on every version. It's not new. 

## Android Device details:

Not going to have information on this, as I don't have Android anymore. However, it had been the same type of issue when I had Android back in 2021 and part of 2022. I still occasionally see where Users on Community will have reports from days or weeks prior that have not been sent. 

## Version/Channel Information:

Happens on all channels

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? I'm assuming, didn't download it on any device
- Can you reproduce this issue with the nightly channel?  Yes, able to replicate on Nightly.

## Other Additional Information:

I have been sharing information with @jonathansampson and @bsclifton @BrendanEich, to which they advised me to create a bug report here on Github. Hopefully I've properly shared information as necessary and in the right format. Also will have fingers crossed this gets handled, as imagine this means many crash reports aren't finding their way to Brave. 

- Does the issue resolve itself when disabling Brave Shields?  
I did not test this yet. But assuming it should have no bearing. 

- Does the issue resolve itself when disabling Brave Rewards? 

 I did not test this yet. But assuming it should have no bearing. 

Is the issue reproducible on the latest version of Chrome? 

Did not test this yet. 

## Miscellaneous Information:

As I was troubleshooting on my end, the one thing I have not done yet is disable **Continue running background apps when Brave is closed**. However, I have manually exited Brave multiple times where the only things running on Task Manager were BraveSoftware Update and BraveSoftware Update (32 bit), both of which reference BraveCrashHandler64.exe and BraveCrashHandler.exe respectively.

**Comment by Saoiray** [comment]
Just a FYI, here we are on 5/22/2023 and reports from 5/17/23 through 5/19/23 still have not sent. So it seems they'll sit there forever until I go to **brave://crashes** which might then trigger it. I'm hoping this will get picked up on

![Screenshot 5_22_2023 13_45_10](https://github.com/brave/brave-browser/assets/99627477/9e8f73fb-1669-4c6f-ae12-4524e4912c56)
![Crash Reports are not sending automatically (Confirmed on Desktop, needs testing_confirmation for Android) · Issue #30434 · brave_brave-browser - Brave 5_22_2023 13_45_34](https://github.com/brave/brave-browser/assets/99627477/25202212-57b8-4bfc-a6d3-5d06517d2405)

**Comment by Saoiray** [comment]
@iefremov  forgot I was told you tag you in on this.

**Comment by Saoiray** [comment]
I had been tracking, even shared videos with Mattches and Steeven from where crashes weren't uploading. Seems crashes from a few days ago finally sent today. So where things were pending weeks, months, or longer in the past...that's at least good news. Just wish I knew what the trigger had been. 

Do we know how often it's supposed to attempt to upload?

**Comment by iefremov** [comment]
normally it happens almost immediately @Saoiray

**Comment by Saoiray** [comment]
Okay, so regardless of what I'm looking at, that's definitely not happening on my end @iefremov. And based on how we often have to instruct people to hit **Send Now** when speaking to Users on Brave Community, I'd say it's safe to assume that's not happening for the majority of people. 

Video I just took a moment ago is at https://youtu.be/LKcLY3nCxkc It abruptly ends as I went to show WinMTR as I figured probably not good to have my exact IP address and all for the public to see. But I did run it and no packet loss. Internet connection is fairly solid as well, 475mbps download with 11mbps upload with about 17ms latency or so.  

Examples of other Community posts where this is an issue:

https://community.brave.com/t/desktop-app-crash-while-closing-any-tab/488425/4?u=saoiray

https://community.brave.com/t/brave-crash-lost-passwords/473681/9?u=saoiray

I'm sure I could try to track further along, but at least is two which clearly shows people saying it hadn't sent. 

If there's anything more I can do that might help you on trying to figure out what's going on, please do advise. Otherwise I'm going to hope it's able to be replicated by your team and resolved.

Thanks!

**Comment by Saoiray** [comment]
Just wanted to advise still an ongoing issue. Hadn't opened for searches in a little while. You can see that I have crash from May 31 and another from June 2 that hadn't uploaded. Here it is, end of day June 6. 

![unsent crashes](https://github.com/brave/brave-browser/assets/99627477/1d15fdc0-296d-4986-a5ad-80fb9b2bc1fa)

**Comment by Saoiray** [comment]
Seems to be fixed in recent updates. It doesn't necessarily send right away but am seeing reports go away on a pretty regular basis. That said, it doesn't leave any **Uploaded Crash Report ID** or anything. Instead it just disappears. Hopefully it's getting to you guys, but at least it's not lingering without uploads.
