### ISSUE TITLE
Add min-height to Wallet Card for Panel Size

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#30433]
## Description 

We need to add a `min-height` to the Wallet `Card` for `panel` widths so the card stretches to the bottom of the screen.

https://github.com/brave/brave-browser/assets/40611140/9a89e576-2002-4cde-9034-00b710843c75

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.53.100 Chromium: 114.0.5735.133 (Official Build) beta (64-bit)
-- | --
Revision | `fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}`
OS | Linux

- Verified steps from [brave/brave-core#18533](https://github.com/brave/brave-core/pull/18533)
- Verified shrinking the `width` of the Browser until the panel layout snaps in
- Verified the height of the Wallet Card stretches all the way to the bottom of the screen when the browser window is reduced

https://github.com/brave/brave-browser/assets/17010094/be2d0eb7-ede5-49fe-9f1a-843ac5250e02


---------------------

**Verification passed on**

Brave | 1.53.100 Chromium: 114.0.5735.133 (Official Build) beta (64-bit)
-- | --
Revision | `fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}`
OS | Windows 11 Version 22H2 (Build 22621.1848)

- Verified steps from [brave/brave-core#18533](https://github.com/brave/brave-core/pull/18533)
- Verified shrinking the `width` of the Browser until the panel layout snaps in
- Verified the height of the Wallet Card stretches all the way to the bottom of the screen when the browser window is reduced

https://github.com/brave/brave-browser/assets/17010094/ab7f5570-08b1-44bc-b865-7c3c9ee87374


---------------------

**Verification passed on**

Brave | 1.53.100 Chromium: 114.0.5735.133 (Official Build) beta (64-bit)
-- | --
Revision | `fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#18533](https://github.com/brave/brave-core/pull/18533)
- Verified shrinking the `width` of the Browser until the panel layout snaps in
- Verified the height of the Wallet Card stretches all the way to the bottom of the screen when the browser window is reduced

https://github.com/brave/brave-browser/assets/17010094/0834a87f-6e55-4682-9691-98b1a709a2bd
