### ISSUE TITLE
"Don't upgrade connections to HTTPS (disabled)" is not working 

### ISSUE THREAD

**Issue by vlad-hoff** [brave/brave-browser#30436]
## Description 

"Don't upgrade connections to HTTPS (disabled)" is not working 

## Steps to reproduce 

   1. Launch Brave > Hamburger Menu
   2. Settings > Brave Shields & privacy 
   3. Upgrade connections to HTTPS > Choose `Don't upgrade connections to HTTPS (disabled)`
   4. Return to NTP and open `http://https-everywhere.badssl.com/` > Observe

## Actual result 

When `Don't upgrade connections to HTTPS (disabled)` setting is applied, pages are still opened and upgraded to HTTPS. The only way to disable forced upgrade to HTTPS is to turn off Shields. The same issue was observed on Nightly and Beta build, but not on Prod.

https://github.com/brave/brave-browser/assets/128532965/4fae0731-60dc-418f-bac0-9859b3f5a80a

## Expected result

No HTTPS upgrade must be triggered when `Don't upgrade connections to HTTPS (disabled)` setting is applied

## Issue reproduces how often 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Pixel 7 [phone]
   - Android version: Android 14 [panther_beta-user 14 UPB2.230407.014 release-keys]
   
## Brave version

Brave build: 1.53.47
Chromium: 114.0.5735.26 (Official Build) canary (64-bit)
Revision: 7075cbb66f0542ac3e01ddfde6b813e7d61118a5-refs/branch-heads/5735@{#454}

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
@pes10k @arthuredelstein I'm pretty sure the above isn't valid anymore as we don't use `http://https-everywhere.badssl.com` as an `HTTPS` upgrade case. We should be using both http://http.badssl.com & http://upgradable.arthuredelstein.net with `HTTPS By Default` correct? Just double checking before I close this off as invalid.

**Comment by kjozwiak** [comment]
The above requires `1.52.115` or higher fort `1.52.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.52.115 Chromium: 114.0.5735.53 (Official Build) (x86_64)
-- | --
Revision | c499d7ea22c8b2dba278465a5df7b86a8efa4e64-refs/branch-heads/5735@{#970}
OS | macOS Version 11.7.7 (Build 20G1345)

* Verified the STR from the description
* Reproduced the issue on `1.52.113`

`1.52.115` | `1.52.113`
-----------|---------
<img width="1312" alt="Screen Shot 2023-05-30 at 11 29 29 AM" src="https://github.com/brave/brave-browser/assets/387249/2701e5b8-4fd9-401a-b295-d340e900619e"> | <img width="1312" alt="Screen Shot 2023-05-30 at 11 34 57 AM" src="https://github.com/brave/brave-browser/assets/387249/1626f3cb-0bc9-4ee2-8811-f165e1fba735">

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 14` using the following build(s):

```
Brave | 1.52.115 Chromium: 114.0.5735.53 (Official Build) (64-bit)
--- | ---
Revision | c499d7ea22c8b2dba278465a5df7b86a8efa4e64-refs/branch-heads/5735@{#970}
OS | Android 13; Build/UPB2.230407.014; 33; UpsideDownCake
```

Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/30436#issue-1716057635, ensured that http://https-everywhere.badssl.com is not being upgraded when `Don't upgrade connections to HTTPS (disabled)` is set via brave://settings/shields as per the following:

**`1.51.121 Chromium 113.0.5672.163`** | **`1.52.115 Chromium: 114.0.5735.53`**
---------------------------------------------|---------------------------------------------
![Screenshot_20230530-185656](https://github.com/brave/brave-browser/assets/2602313/4977b63a-9672-426d-9b61-ff4de36304eb) | ![Screenshot_20230530-190113](https://github.com/brave/brave-browser/assets/2602313/9d4e6b3b-fd9b-42b0-a695-9d91474b0707)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.52.115 Chromium: 114.0.5735.53 (Official Build) (64-bit) 
-- | --
Revision | c499d7ea22c8b2dba278465a5df7b86a8efa4e64-refs/branch-heads/5735@{#970}
OS | Ubuntu 18.04 LTS

* Verified the STR from the description
* Reproduced the issue on `1.52.113`

`1.52.115` | `1.52.113`
-----------|---------
![image](https://github.com/brave/brave-browser/assets/34715963/b832ee80-5197-4881-bcce-eaf978d2f82a)|![image](https://github.com/brave/brave-browser/assets/34715963/d744e0cd-a6e5-4996-9684-9c7381288f44)
