### ISSUE TITLE
Add "Open Rewards panel" item to NTP Rewards widget menu

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#30432]
## Description

Add "Open Rewards panel" item to NTP Rewards widget menu that pops open the Rewards panel. If BAT icon is hidden, then it can temporarily show the BAT icon so that the panel can be displayed until closed again (as we do in similar cases when BAT icon is hidden). 

![image](https://github.com/brave/brave-browser/assets/11497541/8a42c45d-bf49-4a4d-a28d-1a24557265d3)

**Comment by ryanml** [comment]
Hey @Miyayes ! I’d love to take this one. What is your suggestion for the item’s icon? cc: @bbondy

**Comment by Miyayes** [comment]
Hey @ryanml! :D I think we can use the skeleton BAT icon. This one but in white: 

![image](https://github.com/brave/brave-browser/assets/11497541/539296da-12f0-4182-82a9-949bcd7131bf)

It should exist in the codebase, because it's the icon we use for inline tip buttons on Twitter, Reddit, etc.

**Comment by ryanml** [comment]
@Miyayes great! Can you assign me to this?

**Comment by GeetaSarvadnya** [comment]
@Miyayes If `Show Brave Rewards icon in address bar` is disabled in brave://settings/rewards, click on `Open Rewards panel` in the  NTP Rewards widget menu opens up the BR panel poiting to brave shield icon, looks like a bug?

![BAT icon disable](https://github.com/brave/brave-browser/assets/38657976/0339faaa-7250-41d8-b747-525f5bde55bc)

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave | 1.59.90 Chromium: 117.0.5938.88 (Official Build) beta (64-bit)
-- | --
Revision | 5272112c86588e44ec7c0b766c318cddccbced85
OS | Windows 10 Version 22H2 (Build 19045.3448)

```
- Verified the description from the issue https://github.com/brave/brave-browser/issues/30432#issue-1715716329

**Comment by LaurenWags** [comment]
@GeetaSarvadnya re: https://github.com/brave/brave-browser/issues/30432#issuecomment-1723844761, it seems like a bug since @Miyayes mentioned per the description that:

> If BAT icon is hidden, then it can temporarily show the BAT icon so that the panel can be displayed until closed again

However, let's have him confirm expectations 👍🏻

**Comment by GeetaSarvadnya** [comment]
@Miyayes Could you confirm the issue above? Thanks!

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.59.99 Chromium: 117.0.5938.92 (Official Build) beta (arm64)
-- | --
Revision | 189010a9093526dbe96f0d187eacd29c3ba827b5
OS | macOS Version 14.0 (Build 23A344)
```

Verified the test plan from https://github.com/brave/brave-core/pull/19717#issue-1853272312

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.59.107 Chromium: 117.0.5938.140 (Official Build) beta (64-bit) 
Revision	5bbd53ed3e41461e15555b7ce0490464656b236f
OS	Linux
```
