### ISSUE TITLE
Swap transaction shows incorrect token symbol in submitted state. Updates correctly when Swap is completed

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#30447]
## Description 

Swap transaction shows incorrect token symbol in submitted state. Updates correctly when Swap is completed

## Steps to Reproduce

   1. Initiate a Swap from a ERC20 token to ETH
   2. Go to activity tab
   3. Shows swap for ETH -> ETH
   4. Wait for the transaction to complete
   5. Activity tab updates correctly ERC20 -> ETH 

## Actual result:

![image](https://github.com/brave/brave-browser/assets/17010094/9d474705-002e-4ef1-b35c-3233daa5f6b7)

## Expected result:
![image](https://github.com/brave/brave-browser/assets/17010094/fc3a95e7-18ad-43de-b50f-91928f7c5b86)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.52.102 Chromium: 113.0.5672.126 (Official Build) beta (64-bit)
-- | --
Revision | `c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}`
OS | Windows 11 Version 22H2 (Build 22621.1702)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Not checked

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @onyb

**Comment by srirambv** [comment]
Also noticed Approve transaction doesn't show the token name when the swap transaction is in progress and only shows up the token symbol when swap is completed

**Comment by josheleonard** [comment]
@srirambv , I can no longer reproduce on master. Was most-likely fixed by: https://github.com/brave/brave-core/pull/18379


https://github.com/brave/brave-browser/assets/30185185/b9a26a8a-0bea-4bc6-a92a-5a84c15ab3ed

**Comment by josheleonard** [comment]
Resolved by: https://github.com/brave/brave-core/pull/18379

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.57.18 Chromium: 115.0.5790.98 (Official Build) beta (64-bit)
-- | --
Revision | `d515871a6c6df7d2843e755c8b7dda9b744f26d6`
OS | Windows 11 Version 22H2 (Build 22621.1992)

- Verified steps from issue description
- Verified correct token symbol is shown in activity tab for Swap transactions
- Verified correct token symbol is shown for Unapproved -> Approved -> Submitted -> Completed state

https://github.com/brave/brave-browser/assets/17010094/f646802e-1772-4dd9-9b2b-941f98a32d32
