### ISSUE TITLE
Network is reset to `All networks` in visible asset modal instead of filtered network from portfolio

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#30449]
## Description 

Network is reset to `All networks` in visible asset modal instead of filtered network from portfolio

## Steps to Reproduce

   1. Change network to Polygon on portfolio
   2. Click on Visible asset 
   3. Network is reset to `All networks` instead of Polygon

## Actual result:

Network is reset to `All networks` in visible asset modal instead of filtered network from portfolio

## Expected result:
Retain selected network from portfolio on to visible asset list

## Reproduces how often: 

Easy

## Brave version (brave://version info)

All

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:
cc: @Douglashdaniel @kleantzogu @jamesmudgett

**Comment by Douglashdaniel** [comment]
There is no longer a network dropdown filter on the `Portfolio` page after `Wallet V2`, we also moved away from having a global selected network. Closing as `Invalid`

![Screenshot 74](https://github.com/brave/brave-browser/assets/40611140/b14d7566-af29-4b34-ba90-61ed033356a3)
