### ISSUE TITLE
Market Tab should scroll with Page not the Container

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#30446]
## Description 

The market data tab should scroll with the `Page` rather than the `Container`.

https://github.com/brave/brave-browser/assets/40611140/5909feec-1299-4648-a601-53cda20ebbb5

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.53.100 Chromium: 114.0.5735.133 (Official Build) beta (64-bit)
-- | --
Revision | `fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}`
OS | Linux

- Verified steps from [brave/brave-core#18539](https://github.com/brave/brave-core/pull/18539)
- Verified Market tab scroll is not contained to container instead scrolls the entire page

https://github.com/brave/brave-browser/assets/17010094/d4d3ca91-0847-440b-be57-af56f0981aa3


---------------------

**Verification passed on**

Brave | 1.53.100 Chromium: 114.0.5735.133 (Official Build) beta (64-bit)
-- | --
Revision | `fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}`
OS | Windows 11 Version 22H2 (Build 22621.1848)

- Verified steps from [brave/brave-core#18539](https://github.com/brave/brave-core/pull/18539)
- Verified Market tab scroll is not contained to container instead scrolls the entire page

https://github.com/brave/brave-browser/assets/17010094/7808dad6-0cd4-45ba-820f-6dc94360f568


---------------------

**Verification passed on**

Brave | 1.53.100 Chromium: 114.0.5735.133 (Official Build) beta (64-bit)
-- | --
Revision | `fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#18539](https://github.com/brave/brave-core/pull/18539)
- Verified Market tab scroll is not contained to container instead scrolls the entire page

https://github.com/brave/brave-browser/assets/17010094/94e494d8-bf4b-4430-92cb-415a39d9f170
