### ISSUE TITLE
Brave Crashes Dozens of Times per day

### ISSUE THREAD

**Issue by jonatino** [brave/brave-browser#30443]
## Description 

Just installed Brave after not using it for a couple years. I'm experiencing a dozen crashes + freezes a day when doing very basic web browsing.
![image](https://github.com/brave/brave-browser/assets/1808569/15777aac-2ea1-4d03-b30b-3afed9a5d40f)

## Steps to Reproduce

Can't reliably reproduce, just happens eventually. Usually starts lagging when I close tabs quickly.

## Expected result:
No crashing :(

## Brave version (brave://version info)
1.51.118 Chromium: 113.0.5672.126 (Official Build) (64-bit) 

Windows 11 

I have lot's of dump files from crashes, just looking to get someones help debugging this. Would love to see this browser more stable than this....

**Comment by jonatino** [comment]
Possibly related to #30437

**Comment by iefremov** [comment]
can you please open brave://crashes, upload some dumps and share their IDs here?

**Comment by jonatino** [comment]
@iefremov absolutely! Hopefully we can fix this issue. 

In order from earliest crash to latest crash:
db1d0200-8e2d-1b0a-0000-000000000000
de1d0200-8e2d-1b0a-0000-000000000000
e21d0200-8e2d-1b0a-0000-000000000000
e41d0200-8e2d-1b0a-0000-000000000000
e61d0200-8e2d-1b0a-0000-000000000000
e81d0200-8e2d-1b0a-0000-000000000000
ea1d0200-8e2d-1b0a-0000-000000000000
ec1d0200-8e2d-1b0a-0000-000000000000
ee1d0200-8e2d-1b0a-0000-000000000000
ef1d0200-8e2d-1b0a-0000-000000000000

**Comment by iefremov** [comment]
stale
