### ISSUE TITLE
[Rewards] Contribution screen is not closed after a user sent contribution

### ISSUE THREAD

**Issue by vlad-hoff** [brave/brave-browser#30445]
## Description 

The contribution screen is not closed after a user sent a contribution

## Steps to reproduce 

   1. Launch Brave > Enable Rewards Staging and connect custodian
   2. Go to a verified creator, for example, https://github.com/laurenwags
   3. Open Rewards panel > Send Contribution > Use Brave Rewards
   4. Choose contribution amount > Send 
   5. Tap `Go Back` > Observe

## Actual result 

After a user sent a contribution to the verified creator and tapped `Go Back`, the Contribution panel is shown again.

https://github.com/brave/brave-browser/assets/128532965/2c1cdae9-8460-4ff2-b10f-ebbb7451e848

## Expected result

The contribution panel must not be shown after a user sent a contribution to a verified creator. It must be returned to a Rewards panel.

## Issue reproduces how often 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? No
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Pixel 7 [phone]
   - Android version: Android 14 [oriole-user 14 TQ2A.230505.002 release-keys]
   
## Brave version

Brave build: 1.53.47
Chromium: 114.0.5735.26 (Official Build) canary (64-bit)
Revision: 7075cbb66f0542ac3e01ddfde6b813e7d61118a5-refs/branch-heads/5735@{https://github.com/brave/brave-browser/issues/454}

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by Miyayes** [comment]
The “Go back” button should close everything related to making a contribution, and the user will just see the site they were on again.

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Vivo X70 Pro version 12` running `Bravemonoarmx64.apk_1.57.19`

Uploading vidma_recorder_26072023_221007.mp4…
