### ISSUE TITLE
Update "Requires Uphold verification" text on TAP promo card

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#30453]
## Description

Update it to say: "Requires Uphold account." 

![image](https://github.com/brave/brave-browser/assets/11497541/cb61dd98-2385-40f7-b964-e1ec4de49d16)

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.53.74 Chromium: 114.0.5735.53 (Official Build) beta (x86_64)
-- | --
Revision | c499d7ea22c8b2dba278465a5df7b86a8efa4e64-refs/branch-heads/5735@{#970}
OS | macOS Version 11.7.7 (Build 20G1345)

### Steps:
1. installed `1.53.74`
2. launched Brave
3. skipped onboarding
4. clicked on `Start using Rewards` on the new-tab page
5. clicked on `Start using Brave Rewards` in the doorhanger popop
6. selected `United States`
7. clicked `Continue`
8. loaded `brave://rewards`
9. compared the last string on `Redeem BAT for Gift Cards` to `1.52.115`

### Confirmed the string now reads `Requires Uphold account.`

`1.53.74` - `Requires Uphold account.` | `1.52.115` - `Requires Uphold Verification.`
----------------------------------------|--------------------------------------------
<img width="1312" alt="Screen Shot 2023-05-30 at 2 38 00 PM" src="https://github.com/brave/brave-browser/assets/387249/5ff438a1-cf20-430e-8c74-00d20a6d6d7a"> | <img width="1312" alt="Screen Shot 2023-05-30 at 2 40 08 PM" src="https://github.com/brave/brave-browser/assets/387249/ed5a33f4-1fac-4145-b7c5-f991dc438cb6">
