### ISSUE TITLE
Browser crash when "İSKİYÖNETMELİĞİ" entered in address tab.

### ISSUE THREAD

**Issue by MelihCelik00** [brave/brave-browser#30452]
## Description 
Entered a keyword with Turkish letters uppercase İ (type of I) and Ğ (soft G) and got the crash.

## Steps to Reproduce

   1. Open Brave
   2. Search for "İSKİYÖNETMELİĞİ" entered in the address tab.
   3. Get crash.

## Actual result:
Crashed rather than getting search results.

## Expected result:
Search resulted for the keyword.

## Reproduces how often: 
Always, every time.

## Brave version (info found on brave://version)
Brave version: 1.51.114
Device: MacBook Pro Intel Core i5 2017
OS: MacOS Monterey

## Miscellaneous Information:

I can't add labels idk why but let me put labels to here:
- crash
- OS/Desktop

**Comment by Fleurdel34** [comment]
Hello,
J'aurai aimé travaillé sur l'erreur que vous rencontrez mais je ne trouve pas les fichiers avec le code d'origine. J'ai pensé à deux solutions à savoir la mise en place de la balise dans le fichier html <meta charset=utf8> et dans le fichier javascript utiliser un REGEX pour autoriser les caractères souhaités dans le password.

**Comment by Fleurdel34** [comment]
Je me présente. Je suis Johanna developpeuse web alumini junior en France

**Comment by xBZZZZ** [comment]
replicated in `Version 1.53.50 Chromium: 114.0.5735.26 (Official Build) nightly (64-bit)`

note you need to left click this (outlined yellow) using mouse:
![screenshot](https://github.com/brave/brave-browser/assets/91378413/d8ceef02-b224-46d2-abb4-32de0b95b9f8)
not press enter!

**Comment by MelihCelik00** [comment]
Hi @rebron! Yes, of course. I just sent it and guess this is the id you are looking for: 
`50d4a3ed-530d-4dd7-a829-12727c6a7fce`

**Comment by MelihCelik00** [comment]
Hey @rebron, I just wanted to give you a heads-up! Are there any new developments regarding solving this issue?

**Comment by iefremov** [comment]
fixed upstream
