### ISSUE TITLE
Local storage doesn't record anything for wallet panel

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#30455]
## Description 

Local storage doesn't record anything for wallet panel

## Steps to Reproduce

   1. Open `brave://wallet-panel.top-chrome` and open dev tools
   2. Change networks/accounts in the panel 
   3. Local storage for the panel page doesn't record anything

## Actual result:

https://github.com/brave/brave-browser/assets/17010094/617c43b4-ead3-483b-aa9d-66e57d462115

## Expected result:
Should capture changes in panel to the local storage of the panel page

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.52.102 Chromium: 113.0.5672.126 (Official Build) beta (64-bit)
-- | --
Revision | `c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}`
OS | Windows 11 Version 22H2 (Build 22621.1702)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Not checked
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Not checked

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @josheleonard

**Comment by josheleonard** [comment]
@srirambv , We currently are not storing any data in local storage for the panel.

**Comment by srirambv** [comment]
Closing the issue based on previous comment... Can reopen if required or when implemented
