### ISSUE TITLE
Detect IPFS hints and display extension install prompt

### ISSUE THREAD

**Issue by lidel** [brave/brave-browser#3045]
> This task was extracted from "Notes on bringing IPFS to Brave": https://github.com/brave/brave-browser/issues/819#issuecomment-456039555
> Please read the link above before this one.
> #### ps. this work should happen in `ipfs` branch 

How to onboard IPFS users?

  - We don't want to run IPFS node by default. 
  - Opt-in should be a conscious decision (just like Widevine install or opening a Tor tab are)
  - Onboarding should be presented just-in-time

### IPFS support prompt

The initial idea is for Brave to detect IPFS resource or a hint on a website and ask user if support for IPFS should be installed.
  - IPFS support would be delivered by [IPFS Companion](https://github.com/ipfs/ipfs-companion/) extension
  - Explicit opt-in should happen over a flow similar to Widevine ([screenshot](https://ipfs.io/ipfs/QmNuP5hFymRBuVrwL8JwDKd2T7QeX5GbSsWQg64Utxur1o)), but text about IPFS will be more friendly and educational
      - After IPFS Companion install is successful, the tab that triggered it gets reloaded 
      - UX around caching negative decision per site could be the same 

### IPFS hints

CID (content identifier in IPFS) spec is [here](https://github.com/multiformats/cid), it can be validated to remove false-positives.

Good candidates for IPFS hints that could be detected by Brave itself (very light on resources):
- HTTP request for IPFS resource:
  - path starting with `/ipfs/<cid>` ([path gateway](https://docs.ipfs.io/guides/guides/addressing/#path-gateway))
  - hostname starting with `<cid>.ipfs.*` ([subdomain gateway](https://docs.ipfs.io/guides/guides/addressing/#subdomain-gateway))
- HTTP response headers including [`x-ipfs-path`](https://github.com/ipfs-shipyard/ipfs-companion/blob/v2.7.0/docs/x-ipfs-path-header.md#hinting-dnslink-lookups) 
  _(best-effort way to detect DNSLinked sites without expensive lookups)_
- JS on a website making a getter call for [`window.ipfs`](https://github.com/ipfs-shipyard/ipfs-companion/blob/master/docs/window.ipfs.md)  (or `window.ipfs.enable()` call itself)
  _(reliable signal website could opportunistically use native ipfs support, similar to `window.ethereum` and MetaMask)_

Potentially more expensive hint is to check DNS of every visited domain for TXT record indicating presence of [DNSLink](https://docs.ipfs.io/guides/concepts/dnslink/) (removes the need for initial HTTP request to check for `x-ipfs-path` header)

**Comment by bbondy** [comment]
Duping to https://github.com/brave/brave-browser/issues/10220
Thanks for the info above though 👍
