### ISSUE TITLE
Set dependency on brave-keyring package in all channels

### ISSUE THREAD

**Issue by oajara** [brave/brave-browser#30467]
Currently, only the Linux repositories for the `release` channel contain the `brave-keyring` package, upon which the `brave-browser` package is built with a dependency. We have now added the `brave-keyring` package to the repositories for the `beta` and `nightly` channels (see [related PR](https://github.com/brave/brave-release/pull/31)). Consequently, we need to establish a dependency for the `brave-browser` package on these channels to the `brave-keyring` package as well.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.58.83 Chromium: 116.0.5845.62 (Official Build) beta (64-bit) 
-- | --
Revision | 6790b00a844c526d81126dd437569d1b205979ec
OS | Ubuntu 18.04 LTS


### Brave Beta

<details>

Verified beta deb is dependent on `brave-keyring`  on clean Ubuntu install
![image](https://github.com/brave/brave-browser/assets/34715963/1bf279f3-5f91-4a30-813e-40e35706d1b1)

Verified the `brave-keyring` is installed before Brave
![image](https://github.com/brave/brave-browser/assets/34715963/f99699c5-b2b4-4301-b00a-4efb4fbbfbdf)


Verified Brave works
![image](https://github.com/brave/brave-browser/assets/34715963/5edabeb8-e67b-44f7-89c2-8e77ea4ceabb)


</details>

Verification passed on

Brave | 1.59.14 Chromium: 116.0.5845.82 (Official Build) nightly (64-bit) 
-- | --
Revision | ad0dfa4522233e43e64bb3d4616bcec49fa1dc3a
OS | Ubuntu 18.04 LTS

### Brave Nightly

<details>

Verified deb is dependent on `brave-keyring` on clean Ubuntu install
![image](https://github.com/brave/brave-browser/assets/34715963/9d1184e9-fae3-416c-bedc-7ef6bd604003)


Verified the `brave-keyring` is installed before Brave
![image](https://github.com/brave/brave-browser/assets/34715963/665563d3-4a79-4299-a106-38fe1ef01180)



Verified Brave works
![image](https://github.com/brave/brave-browser/assets/34715963/a0b3cc3e-3930-451d-bb2a-2a2b789e7a87)


</details>
