### ISSUE TITLE
bottom corners on contribution/tip banner are rounded and square simultaneously - follow up to 30282

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#30463]
## Description 

After https://github.com/brave/brave-core/pull/18487 landed in Nightly, still seeing issue as described in https://github.com/brave/brave-browser/issues/30282

## Steps to Reproduce

   1. Clean profile 1.52.x or 1.53.x
   2. Close/relaunch to pull griffin
   3. Enable Rewards, connect a custodian (I used Uphold)
   4. Open a new tab and navigate to laurenwags.github.io
   5. Open tip banner for site, bottom rounded corners look fine
   6. Open a new tab, do not re-use same tab
   7. Open alexvincentmusic.com
   8. Open tip banner for site --> bottom corners are rounded and square

Reproduced with both light and dark themes.

## Actual result:

Dark | Light
--- | ---
<img width="1183" alt="1" src="https://github.com/brave/brave-browser/assets/28145373/fe9f9fb2-1612-4acb-acfb-40710f70a27e"> | <img width="1188" alt="2" src="https://github.com/brave/brave-browser/assets/28145373/cb4e0340-8e86-47b2-a113-2ad14ebd1a12">

## Expected result:

rounded corners only

## Reproduces how often: 

easily

## Brave version (brave://version info)

```
Brave | 1.53.52 Chromium: 114.0.5735.26 (Official Build) nightly (x86_64)
-- | --
Revision | 7075cbb66f0542ac3e01ddfde6b813e7d61118a5-refs/branch-heads/5735@{#454}
OS | macOS Version 13.3.1 (a) (Build 22E772610a)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? per original issue, yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @Miyayes @zenparsing

**Comment by GeetaSarvadnya** [comment]
Reproduced the issue, In windows only the bottom corners are rounded - `Windows 10 x64 - 1.52.102`


Light | Dark
-------|------
![image](https://github.com/brave/brave-browser/assets/38657976/82a50a7f-5e5b-4151-9e08-05495570b27b) | ![image](https://github.com/brave/brave-browser/assets/38657976/db5cbbce-d939-4ec6-8391-799e808d242f)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.52.110 Chromium: 114.0.5735.35 (Official Build) (64-bit)
-- | --
Revision | 2295354895fa3652ae47b651481831484f16d1ff-refs/branch-heads/5735@{#713}
OS | Windows 11 Version 22H2 (Build 22621.1702)
```
Verified STR from https://github.com/brave/brave-browser/issues/30463#issue-1717414750:

   1. Clean profile 1.52.x
   2. Close/relaunch to pull griffin
   3. Enable Rewards, connect a custodian (I used Uphold)
   4. Open a new tab and navigate to laurenwags.github.io
   5. Open tip banner for site, bottom rounded corners look fine
   6. Open a new tab, do not re-use same tab
   7. Open alexvincentmusic.com
   8. Open tip banner for site
---> Confirmed bottom corners were rounded - no artifacts making corners appear rounded and square as in the image in issue description

Step 5 | Step 8
--- | ---
![image](https://github.com/brave/brave-browser/assets/98358127/d84c09c9-2521-4c24-887d-3cb4351642a7)|![image](https://github.com/brave/brave-browser/assets/98358127/0703880e-9155-4d34-a5bb-f41723e09ef2)

Repeated above test using light theme as well (fresh profile):

Step 5 | Step 8
--- | ---
![image](https://github.com/brave/brave-browser/assets/98358127/e45432f5-120e-4f4c-ada0-3d9a65bb6f18)|![image](https://github.com/brave/brave-browser/assets/98358127/d4d49ae2-de9d-4702-9f3d-d822c55efc7c)

Generally visited various verified creators and confirmed the bottom corners of the contribution banners were rounded as expected using both light and dark themes:

Example | Example | Example | Example
--- | --- | --- | ---
![image](https://github.com/brave/brave-browser/assets/98358127/41831c50-c661-4823-8fbd-0764c8bf42a5)|![image](https://github.com/brave/brave-browser/assets/98358127/da08f6c9-b49b-4c2b-8c56-80897298c044)|![image](https://github.com/brave/brave-browser/assets/98358127/cddee06f-946d-4abb-8fae-2c5f16996c9f)|![image](https://github.com/brave/brave-browser/assets/98358127/bb019899-8157-47d1-a7b4-34efab27eb09)

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.52.112 Chromium: 114.0.5735.35 (Official Build) (64-bit)
-- | --
Revision | 2295354895fa3652ae47b651481831484f16d1ff-refs/branch-heads/5735@{#713}
OS | Windows 10 Version 22H2 (Build 19045.2965)
```
Verified STR from https://github.com/brave/brave-browser/issues/30463#issue-1717414750:

   1. Clean profile 1.52.x
   2. Close/relaunch to pull griffin
   3. Enable Rewards, connect a custodian (I used Uphold)
   4. Open a new tab and navigate to laurenwags.github.io
   5. Open tip banner for site, bottom rounded corners look fine
   6. Open a new tab, do not re-use same tab
   7. Open alexvincentmusic.com
   8. Open tip banner for site
---> Confirmed bottom corners were rounded - no artifacts making corners appear rounded and square as in the image in issue description

Step 5 | Step 8
--- | ---
![image](https://github.com/brave/brave-browser/assets/38657976/07f4204f-d8a3-4ea1-993e-c21ff05b6f5a) | ![image](https://github.com/brave/brave-browser/assets/38657976/1b284772-c913-4c87-b874-0bb68ded8bfc)

Repeated above test using Dark theme as well (fresh profile):

Step 5 | Step 8
--- | ---
![image](https://github.com/brave/brave-browser/assets/38657976/182b1a5f-136f-4e92-8f07-38b0ef3e2da0) | ![image](https://github.com/brave/brave-browser/assets/38657976/9ab06880-271e-41cd-a2a6-f9a6422dbb61)


Generally visited various verified creators and confirmed the bottom corners of the contribution banners were rounded as expected using both light and dark themes:

Example | Example |Example | Example
--- | --- | --- | ----
![image](https://github.com/brave/brave-browser/assets/38657976/64c35b31-a123-44be-a4a6-2d5e66caebc3) | ![image](https://github.com/brave/brave-browser/assets/38657976/471273cc-e56f-46a4-89d9-083099506da9) | ![image](https://github.com/brave/brave-browser/assets/38657976/2d6bb3b3-2d75-4813-a202-217a3aa32213) | ![Uploading image.png…]()

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.52.112 Chromium: 114.0.5735.35 (Official Build) (64-bit)
-- | --
Revision | 2295354895fa3652ae47b651481831484f16d1ff-refs/branch-heads/5735@{#713}
OS | Ubuntu 18.04 LTS

Verified STR from https://github.com/brave/brave-browser/issues/30463#issue-1717414750:


<details>

   1. Clean profile 1.52.x
   2. Close/relaunch to pull griffin
   3. Enable Rewards, connect a custodian (I used Uphold)
   4. Open a new tab and navigate to laurenwags.github.io
   5. Open tip banner for site, bottom rounded corners look fine
   6. Open a new tab, do not re-use same tab
   7. Open alexvincentmusic.com
   8. Open tip banner for site
---> Confirmed bottom corners were rounded - no artifacts making corners appear rounded and square as in the image in issue description

![image](https://github.com/brave/brave-browser/assets/34715963/0a7ec12d-ad85-4fdb-befc-4aa6cd776eee)



Repeated above test using Dark theme as well (fresh profile):

![image](https://github.com/brave/brave-browser/assets/34715963/fd0b32b8-8541-425e-8cba-3af4adf369af)



</details>
