### ISSUE TITLE
fix users in a bad state due to 2962

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#3046]
## Description 
Follow up to #2962 

Due to 2962 some users got into a bad state where they are unable to join Brave Rewards. We should fix users in this bad state so they can join Brave Rewards.

Additionally, some users reported unable to join Brave Rewards with https://github.com/brave/brave-browser/issues/2997 - I am unsure if this is the same root cause, but it would be nice to fix for them as well.

## Steps to Reproduce

Steps copied from #2962 

   1. launch any of the 0.60.x versions and click on the Brave panel
You'll reproduce 100% when you don't see the initial notification appear within the Rewards panel.

Note - was able to get into this bad state on 0.60.13 Dev and 0.59.25 Beta per comments on that issue.

## Actual result:
Clicking on the BAT logo opts you into rewards, but your ledger_state file is missing values so you don't have a real wallet. Additionally, you may or may not see a wallet creation failed error on brave://rewards page when trying to opt in after getting into this bad state.

## Expected result:
This issue should fix anyone currently in a bad state.

## Reproduces how often: 
easily

## Brave version (brave://version info)
0.60.13 Dev or 0.59.25 Beta

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information
cc @NejcZdovc @kjozwiak

**Comment by LaurenWags** [comment]
cc @mandar-brave

**Comment by greyl0ck** [comment]
Thank you for providing all of the technical lingo & info for us laymen. It's greatly appreciated.

**Comment by Liunkae** [comment]
See also: #2649

**Comment by LaurenWags** [comment]
@Liunkae - do you happen to know what the panel (when you click on BAT logo) shows when you're in this 'unable to create wallet' state from 2649?

**Comment by Liunkae** [comment]
@LaurenWags I'll get a screenshot once I get back to my computer in a few hours.

**Comment by LaurenWags** [comment]
awesome, thanks @Liunkae !

**Comment by Liunkae** [comment]
@LaurenWags Here is what the panel shows when I launch Brave:
![](https://user-images.githubusercontent.com/19424103/51563589-7d4f2080-1e52-11e9-9f0f-a78c055e9ff5.png)
After I go to brave://rewards/ and click Try again, the panel then shows this:
![](https://user-images.githubusercontent.com/19424103/51563617-95bf3b00-1e52-11e9-833b-15c5b86524db.png)

**Comment by Liunkae** [comment]
@dontezuma Until the underlying problem is found, the only way to fix this is to completely reset the browser profile. On macOS (it's different for each platform), you have to rename/delete `~/Library/Application Support/BraveSoftware/Brave-Browser`.

**Comment by dontezuma** [comment]
The goal, of course, is to have one wallet associated with whatever device I'm using Brave on.  I'm using Sync as a beta, and would hope that I could set up my wallet address on any instance of Brave associated with me.

**Comment by LaurenWags** [comment]
Thanks for grabbing that screenshot @Liunkae - sounds exactly like a scenario I hope this issue will resolve.

**Comment by NejcZdovc** [comment]
@LaurenWags can you please add broken profile to this issue. Please point it to staging. Thank you

**Comment by LaurenWags** [comment]
@NejcZdovc I couldn't reproduce on macOS, so here's a Windows profile 
[Brave-Browser-Beta-05925.zip](https://github.com/brave/brave-browser/files/2823589/Brave-Browser-Beta-05925.zip)

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.62.25 Chromium: 73.0.3683.67 (Official Build) beta (64-bit)
-- | --
Revision | a83fd4f3207ae83412d329a9ca1239dd1e068345-refs/branch-heads/3683@{#760}
OS | Windows 7 Service Pack 1 Build 7601.24312

Used staging profile provided by @LaurenWags : https://github.com/brave/brave-browser/issues/3046#issuecomment-459891243

If I go to `brave://rewards` I can join the rewards through `Yes, I am in` button, which was not possible before the fix(tested on 0.61.51).

I can still see the `Brave Rewards is off` message in Brave Panel, just like in https://github.com/brave/brave-browser/issues/2962
Logged https://github.com/brave/brave-browser/issues/3697
