### ISSUE TITLE
spotify ads not properly being skipped in the web browser

### ISSUE THREAD

**Issue by robot514** [brave/brave-browser#30476]
## Description 

some ads will be skipped but then it will freeze spotify on an ad forcing a refresh of the page in order for it to work again
(some times it will properly skip through an ad break but more often then not it freezes completly)

## Steps to Reproduce

   1.   open the spotify web player using brave browser with brave sheild on
   2.   play through a few tracks on the spotify web browser until you encounter an ad break
  

## Actual result:

the web player perminantly freezes on an ad break forcing a refresh of the page

![Screenshot 2023-05-20 164229](https://github.com/brave/brave-browser/assets/24964409/3021e5ff-0a87-4f4f-9aec-d34c83f4289b)

## Expected result:

the ad break should be skipped through without the web player freezing

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Version 1.51.118 Chromium: 113.0.5672.126 (Official Build) (64-bit)

c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}

Windows 11 Version 21H2 (Build 22000.1936)

## Version/Channel Information:

- Can you reproduce this issue with the current release? YES
- Can you reproduce this issue with the beta channel? YES
- Can you reproduce this issue with the nightly channel? YES

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  YES
- Does the issue resolve itself when disabling Brave Rewards? NO
- Is the issue reproducible on the latest version of Chrome? NO

## Miscellaneous Information:

attemps at reinstalling brave, clearing cookies and reseting settings have been unsuccesful at resolving the issue

**Comment by ryanbr** [comment]
Possibly related: https://old.reddit.com/r/uBlockOrigin/comments/13n998i/using_spotify_web_player_and_instead_of_moving/  Which we would be affected also.

**Comment by Kurtty5878** [comment]
Mine's not even blocking ads anymore

**Comment by ryanbr** [comment]
Test the following: 

```
||akamaized.net/audio/$media,redirect-rule=noop-1s.mp4,domain=open.spotify.com,important
||scdn.co/audio/*$media,redirect=noop-1s.mp4,domain=open.spotify.com,important
```

**Comment by ryanbr** [comment]
@robot514 @Kurtty5878 @khot-aditya Everything better now with Spotify?

**Comment by khot-aditya** [comment]
> @robot514 @Kurtty5878 @khot-aditya Everything better now with Spotify?

@ryanbr Yes, ads are getting skipped now. Thanks. 👍

**Comment by Kurtty5878** [comment]
I'm getting ads again that dont skip but completely pause and I have to refresh again.
