### ISSUE TITLE
Unable to use zkSync Era on Brave Wallet

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#30473]
Users are unable to transfer out assets on zkSync Era. This is an EVM-compatible zk-rollup, so support should've been out of the box.

|Community|https://community.brave.com/t/wallet-does-not-allow-to-sent-crypto-in-zksync-era-network-to-metamask/487880|
-|-

Possibly related to https://github.com/brave/brave-browser/issues/19869 per https://github.com/brave/brave-browser/issues/19869#issuecomment-1489752406.

**Update: May 26, 2023**

More users complaining!

|<img src="https://github.com/brave/brave-browser/assets/3684187/a6dacdd4-5a56-4252-8226-8772b1e82682">|<img src="https://github.com/brave/brave-browser/assets/3684187/c09b32d0-718d-492a-a517-9366d409ec04">|
-|-

**Comment by kjozwiak** [comment]
The above requires `1.52.124` or higher for `1.52.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.52.125 Chromium: 114.0.5735.110 (Official Build) (64-bit)
-- | --
Revision | `1c828682b85bbc70230a48f5e345489ec447373e-refs/branch-heads/5735_90@{#13}`
OS | Windows 11 Version 22H2 (Build 22621.1778)

- Verified steps from [brave/brave-core#18707](https://github.com/brave/brave-core/pull/18707)
- Verified able to Swap on `https://syncswap.xyz/` on zkSync Era Mainnet
- Verified able to send ETH on zkSync Era Mainnet between wallets without any issues

https://github.com/brave/brave-browser/assets/17010094/1c84832b-36fa-4f3d-a144-0cb5342f4319
