### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by sameerchoubey** [brave/brave-browser#30478]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.51.118 Chromium: 113.0.5672.126
Operating System: Mac OS X 13.3.1

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1.
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/826e0500-8e2d-1b0a-0000-000000000000

**Comment by iefremov** [comment]
stale
