### ISSUE TITLE
Install/uninstall brave vpn wireguard service

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#30486]
Root issue https://github.com/brave/brave-browser/issues/29253

In previous steps we created brave vpn wireguard service and now we are ready to ship it with the browser. The service requires external dll dependencies `tunnel.dll` and `wireguard.dll` which will be pre-build with `brave_vpn_wireguard_service.exe` to brave installer and installed/registered with the browser. Updates will be possible only with the browser together

The binaries will be uploaded to brave-build-deps-public.s3.brave.com, downloaded during runhooks and pre-built to the browser installer.

**Comment by LaurenWags** [comment]
@brave/qa-team we should test this on both Windows 10 and Windows 11, please don't add the pass label until this has been verified on both

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.57.24 Chromium: 115.0.5790.136 (Official Build) beta (64-bit)
-- | --
Revision | 8099932ede6f8d4624fbddf39d27abb3b340d8c9
OS | Windows 10 Version 22H2 (Build 19045.3208)

### Shared Steps:
<details>

1. installed `1.57.24`
2. launched Brave
3. set `brave://flags/#brave-vpn-wireguard` to `Enabled`
4. clicked `Relaunch`
5. purchased, configured, and connected to `Brave VPN` using `https://account.bravesoftware.com/`

example | example
----------|----------
![image](https://github.com/brave/brave-browser/assets/387249/61b7919c-4adb-413c-a5a0-58a540bd266d) | ![image](https://github.com/brave/brave-browser/assets/387249/240eeae9-0848-45b1-9673-eb15fd6fc4d0)


</details>

**Comment by stephendonner** [comment]
Removing `QA/In-Progress` for my run on `Windows 10`, which is completed.  @MadhaviSeelam - LMK if you run into any snags on `Windows `11` 👍

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using 
```
Brave | 1.57.34 Chromium: 115.0.5790.114 (Official Build) beta (64-bit)
-- | --
Revision | 053d4a655f3b76858472b8715b5f320c674848cd
OS | Windows 11 Version 22H2 (Build 22621.1992)
```

## Shared Steps:
<details>

1. installed `1.57.34`
2. launched Brave
3. set `brave://flags/#brave-vpn-wireguard` to `Enabled`
4. clicked `Relaunch`
5. purchased, configured, and connected to `Brave VPN` using `https://account.bravesoftware.com/`

example | example
----------|----------

<img width="910" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/5fa3e39a-cd18-4977-be9e-6b5ec7bc54fc">|<img width="951" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/7d1c2d92-e32f-4b0f-8372-585cfe337e04">
