### ISSUE TITLE
Selecting All networks import hardware wallet screen stops showing balance

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#30484]
## Description 

Selecting All networks import hardware wallet screen stops showing balance 

## Steps to Reproduce

   1. Connect hardware wallet
   2. Select any network and select All network
   3. Balance is hidden

## Actual result:

Solana | EVM | Filecoin
-- | -- | --
![brave_PqxangOVqb](https://github.com/brave/brave-browser/assets/17010094/96a6e9f9-90f1-46d8-8e1e-deed74f9a764) | ![brave_jg8pnUgdcp](https://github.com/brave/brave-browser/assets/17010094/7d385c02-0ff1-4d78-a61e-9bcb8166e04e) | ![brave_tb7HAw48Ls](https://github.com/brave/brave-browser/assets/17010094/0170d813-2317-44b8-af8a-fc3aaf89b8ce)

## Expected result:
Hide All networks when not applicable. 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.52.102 Chromium: 113.0.5672.126 (Official Build) beta (64-bit)
-- | --
Revision | `c541687b21a73452ab403e2dced7033ddc97ee9d-refs/branch-heads/5672@{#1202}`
OS | Windows 11 Version 22H2 (Build 22621.1702)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

Note: Also showing `All networks` for Solana and Filecoin doesn't make sense 

cc: @Douglashdaniel @jamesmudgett @josheleonard

**Comment by HEagle18** [comment]
@kleantzogu might be worth thinking about for wallet 2.0 designs.

**Comment by srirambv** [comment]
Verification passed on  

Brave | 1.62.128 Chromium: 120.0.6099.144 (Official Build) beta (64-bit)
-- | --
Revision | 41f5844c06c7db1017f39b5b6dc9ba81a6b1b9d6
OS | Windows 11 Version 23H2 (Build 22631.2861)

- Verified steps from [brave/brave-core#20872](https://github.com/brave/brave-core/pull/20872)
- Verified `All Networks` option is removed from import hardware wallet 
- Verified only selected Network types are listed when importing accounts via hardware wallet

Ethereum/EVM | Solana | Filecoin
-- | -- | --
![brave_nHOoPOHMhQ](https://github.com/brave/brave-browser/assets/17010094/23349975-3039-469f-b172-8c6f38e5adff) | ![brave_SPRJ2qOi4C](https://github.com/brave/brave-browser/assets/17010094/d6ef3603-99d1-4122-b2ac-54642dc8a2da) | ![brave_BHFdBz4GA5](https://github.com/brave/brave-browser/assets/17010094/919c85c0-d9bf-4d5a-9f41-57eeae584205)
