### ISSUE TITLE
Make all 4 corners of tip panel rounded on all platforms

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#30489]
On MacOS, all four corners of the panel are rendered with the same radius, even when different values are specified for each corner (likely due to an upstream bug). In order to normalize across platforms and avoid issues, we should temporarily make all corners rounded on all desktop platforms.

**Comment by LaurenWags** [comment]
@brave/qa-team when testing on Windows, please test this on both Windows 10 and Windows 11. Do not add `QA Pass-Win64` label until both platforms are verified, thanks!

**Comment by kjozwiak** [comment]
The above requires `1.52.110` or higher for `1.52.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.52.110 Chromium: 114.0.5735.35 (Official Build) (x86_64)
-- | --
Revision | 2295354895fa3652ae47b651481831484f16d1ff-refs/branch-heads/5735@{#713}
OS | macOS Version 13.4 (Build 22F66)
```

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.52.110 Chromium: 114.0.5735.35 (Official Build) (64-bit)
-- | --
Revision | 2295354895fa3652ae47b651481831484f16d1ff-refs/branch-heads/5735@{#713}
OS | Windows 11 Version 22H2 (Build 22621.1702)
```

- Confirmed all 4 corners of contribution (tip) banner are rounded for various tip banners.
- Confirmed on both Dark and Light themes.

Dark | Light
--- | ---
<img width="1235" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/d84c09c9-2521-4c24-887d-3cb4351642a7">|<img width="1135" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/e45432f5-120e-4f4c-ada0-3d9a65bb6f18">
<img width="1235" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/0703880e-9155-4d34-a5bb-f41723e09ef2">|<img width="1235" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/d4d49ae2-de9d-4702-9f3d-d822c55efc7c">
<img width="1235" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/cddee06f-946d-4abb-8fae-2c5f16996c9f">|<img width="1235" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/41831c50-c661-4823-8fbd-0764c8bf42a5">
<img width="1235" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/bb019899-8157-47d1-a7b4-34efab27eb09">|<img width="1235" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/da08f6c9-b49b-4c2b-8c56-80897298c044">

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.52.112 Chromium: 114.0.5735.35 (Official Build) (64-bit)
-- | --
Revision | 2295354895fa3652ae47b651481831484f16d1ff-refs/branch-heads/5735@{#713}
OS | Windows 10 Version 22H2 (Build 19045.2965)
```

- Confirmed all 4 corners of contribution (tip) banner are rounded for various tip banners.
- Confirmed on both Dark and Light themes.

Dark | Light
--- | ---
![image](https://github.com/brave/brave-browser/assets/38657976/3c486cde-2b9d-43d9-91ae-26a040d9652f) | ![image](https://github.com/brave/brave-browser/assets/38657976/3103e979-0ccd-4c55-b91f-64c6eabad058)
![image](https://github.com/brave/brave-browser/assets/38657976/c1d6596e-3979-4117-9fd0-3f97bab2b0cf) | ![image](https://github.com/brave/brave-browser/assets/38657976/313081b0-1262-41c3-8686-6f6639978ac7)
![image](https://github.com/brave/brave-browser/assets/38657976/b24a6986-e5d2-4cf6-b3ef-5e04ea173e8b) | ![image](https://github.com/brave/brave-browser/assets/38657976/401548ba-a9bf-499c-ad94-ac9f50eb2e55)
![image](https://github.com/brave/brave-browser/assets/38657976/ac11b96e-0846-4736-af9d-887f7e2b6d5a) | ![image](https://github.com/brave/brave-browser/assets/38657976/f29d5e4b-4b65-49f6-96f8-106d7f93d725)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.52.112 Chromium: 114.0.5735.35 (Official Build) (64-bit)
-- | --
Revision | 2295354895fa3652ae47b651481831484f16d1ff-refs/branch-heads/5735@{#713}
OS | Ubuntu 18.04 LTS


<details>

- Confirmed all 4 corners of contribution (tip) banner are rounded for various tip banners.
- Confirmed on both Dark and Light themes.

Light:
![image](https://github.com/brave/brave-browser/assets/34715963/8dcb7fef-a7d0-4ce0-8714-501422621d0d)|![image](https://github.com/brave/brave-browser/assets/34715963/8afd41d0-63fd-4f47-bf99-8afba6f8d722)|![image](https://github.com/brave/brave-browser/assets/34715963/bcea87c4-2211-4aae-9e90-e96504e379b3)|![image](https://github.com/brave/brave-browser/assets/34715963/d08955e4-58fe-4ab6-b551-806debd28953)
--|--|--|--


Dark:
![image](https://github.com/brave/brave-browser/assets/34715963/a1650cdc-eea3-4be7-b694-0d87a58c13a7)|![image](https://github.com/brave/brave-browser/assets/34715963/f38a0e06-78e0-498d-a2bd-3da2a9d469ad)|![image](https://github.com/brave/brave-browser/assets/34715963/26e970d2-8f8a-463c-ba26-800592c974bd)|![image](https://github.com/brave/brave-browser/assets/34715963/6e81708b-e033-4c6d-bcf9-3a4a33c53a5d)
--|--|--|--


</details>
