### ISSUE TITLE
Does Brave browser support Policy Templates?

### ISSUE THREAD

**Issue by TontyTon** [brave/brave-browser#3048]
## Description 

Does Brave browser support Policy Templates?
They have many useful extra settings.
[https://support.google.com/chrome/a/answer/187202](https://support.google.com/chrome/a/answer/187202?hl=en)

## Steps to Reproduce

   1. 
   2. 
   3. 

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
cc: @bbondy

**Comment by TontyTon** [comment]
An example- policy templates have an option to disable notification - 'to disable developer extension'. (very irritating). 
![1](https://user-images.githubusercontent.com/35778430/52517903-abad6800-2c68-11e9-9259-9046df91e546.PNG)
Again, its just ***an*** example.

It have many more settings, not included in the UI.

**Comment by rebron** [comment]
cc: @tomlowenthal

**Comment by tomlowenthal** [comment]
We get the policy template code from Chromium AFAIK, but we don't officially support it, and we haven't added policy options for Brave-specific features. Use at your own risk.

**Comment by TontyTon** [comment]
@tomlowenthal Where is .adm file for Brave?

**Comment by tomlowenthal** [comment]
Like I said, this is not a feature we support right now.

**Comment by TontyTon** [comment]
Ok, You said "Use at your own risk", so I thought that you may have adapted the file but don't support it. But now I understand that that you haven't.
To use Policy Templates, I would have to adapt it myself, which I am not capable of, so I can't use them. :(
