### ISSUE TITLE
Playlist Crash

### ISSUE THREAD

**Issue by ghost** [brave/brave-browser#30493]
## Description 
When i add a video to a playlist, open it, then loop it, at the end of the video the app crashes/restarts.

## Steps to reproduce 

   1.Add video to Playlist
   2.Open the video
   3.Loop it
   4. App crashes/restarts

## Expected result
No crashes/restarts

## Issue reproduces how often 
Everytime

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): ARM64
   - Device type (Phone, Tablet, Phablet): Android
   - Android version: MIUI 13.0.3 Android 12 SKQ1.211202.001
   
## Brave version
 I am using 1.53.60 Nightly

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
Closing in favour of https://github.com/brave/brave-browser/issues/30682 which is basically the same issue. Thanks for reporting 👍
