### ISSUE TITLE
Enabling Chrome Refresh 2023 flag makes the hamburger menu crash the browser when it's clicked on

### ISSUE THREAD

**Issue by joejoejo** [brave/brave-browser#30499]
Description
When having the Chrome Refresh 2023 flag enabled, it makes it so that when you clock on the hamburger menu, it crashes the browser.

Steps to Reproduce

   1. enable Chrome Refresh 2023 in flags
   2. restart brave
   3. Click on the hamburger menu.

Actual result:
can't do screenshots because it crashes, and can't screenshot a crash that does not have a error message with it

Expected result:
opens the hamburger menu.

Reproduces how often:
really easy after enabling that flag.

Brave version (info found on brave://version)

Version/Channel Information:
Version 1.52.108 Chromium: 114.0.5735.26 (Official Build) beta (64-bit)

- Can you reproduce this issue with the current release? No, because it does not have Chrome v114 yet.
- Can you reproduce this issue with the beta channel? YES
- Can you reproduce this issue with the dev channel? No, because it does not have Chrome v114 yet.
- Can you reproduce this issue with the nightly channel? YES

Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NO
- Does the issue resolve itself when disabling Brave Rewards? NO
- Is the issue reproducible on the latest version of Chrome? NO

Miscellaneous Information:
I want to keep the Chrome Refresh 2023 flag enabled because it enables a new look for Chrome with new, updated theming and icons.

Also, you can enable a lot of the Chrome Refresh 2023 without having to enable all of it; just search for cr23 in the flags search box.

**Comment by stephendonner** [comment]
Confirmed in 

Brave | 1.52.108 Chromium: 114.0.5735.26 (Official Build) beta (x86_64)
-- | --
Revision | 7075cbb66f0542ac3e01ddfde6b813e7d61118a5-refs/branch-heads/5735@{#454}
OS | macOS Version 11.7.7 (Build 20G1345)

**Comment by stephendonner** [comment]
Here's the stacktrace from https://share.backtrace.io/api/share/ThFNihGP4UfhH01wE3Kp60 (incident ID: `0ff20700-8e2d-1b0a-0000-000000000000`)

```
[ 00 ] logging::LogMessage::~LogMessage() ( immediate_crash.h:148 )
[ 01 ] logging::LogMessage::~LogMessage() ( logging.cc:723 )
[ 02 ] logging::LogMessage::~LogMessage() ( logging.cc:723 )
[ 03 ] logging::CheckError::~CheckError() ( check.cc:198 )
[ 04 ] logging::CheckError::~CheckError() ( check.cc:190 )
[ 05 ] crash_reporter::(anonymous namespace)::AbslAbortHook(char const*, int, char const*, char const*, char const*) ( crashpad.cc:63 )
[ 06 ] absl::raw_log_internal::(anonymous namespace)::RawLogVA(absl::LogSeverity, char const*, int, char const*, __va_list_tag*) ( atomic_hook.h:117 )
[ 07 ] absl::raw_log_internal::RawLog(absl::LogSeverity, char const*, int, char const*, ...) ( raw_logging.cc:225 )
[ 08 ] absl::optional_internal::throw_bad_optional_access() ( bad_optional_access.cc:39 )
[ 09 ] BraveAppMenuModel::Build() ( brave_app_menu_model.cc:0 )
[ 10 ] AppMenuModel::Init() ( app_menu_model.cc:416 )
[ 11 ] AppMenuButton::RunMenu(std::Cr::unique_ptr<AppMenuModel, std::Cr::default_delete<AppMenuModel>>, Browser*, int) ( app_menu_button.cc:65 )
[ 12 ] base::RepeatingCallback<void (media::EmeInitDataType, std::Cr::vector<unsigned char, std::Cr::allocator<unsigned char>> const&)>::Run(media::EmeInitDataType, std::Cr::vector<unsigned char, std::Cr::allocator<unsigned char>> const&) const & ( callback.h:333 )
[ 13 ] views::MenuButtonController::Activate(ui::Event const*) ( button.h:105 )
[ 14 ] views::MenuButtonController::OnMousePressed(ui::MouseEvent const&) ( menu_button_controller.cc:109 )
[ 15 ] ToolbarButton::OnMousePressed(ui::MouseEvent const&) ( toolbar_button.cc:489 )
[ 16 ] views::View::ProcessMousePressed(ui::MouseEvent const&) ( view.cc:3387 )
[ 17 ] views::View::OnMouseEvent(ui::MouseEvent*) ( view.cc:1518 )
[ 18 ] ui::ScopedTargetHandler::OnEvent(ui::Event*) ( scoped_target_handler.cc:28 )
[ 19 ] ui::EventDispatcher::DispatchEvent(ui::EventHandler*, ui::Event*) ( event_dispatcher.cc:187 )
[ 20 ] ui::EventDispatcher::ProcessEvent(ui::EventTarget*, ui::Event*) ( event_dispatcher.cc:136 )
[ 21 ] ui::EventDispatcherDelegate::DispatchEventToTarget(ui::EventTarget*, ui::Event*) ( event_dispatcher.cc:82 )
[ 22 ] ui::EventDispatcherDelegate::DispatchEvent(ui::EventTarget*, ui::Event*) ( event_dispatcher.cc:54 )
[ 23 ] views::internal::RootView::OnMousePressed(ui::MouseEvent const&) ( root_view.cc:464 )
[ 24 ] views::Widget::OnMouseEvent(ui::MouseEvent*) ( widget.cc:1730 )
[ 25 ] views::NativeWidgetMacNSWindowHost::OnMouseEvent(std::Cr::unique_ptr<ui::Event, std::Cr::default_delete<ui::Event>>) ( native_widget_mac_ns_window_host.mm:917 )
[ 26 ] -[BridgedContentView mouseEvent:] ( bridged_content_view.mm:650 )
[ 27 ] 0x7fff232c076e
[ 28 ] 0x7fff2322ff88
[ 29 ] 0x7fff2322f346
[ 30 ] -[NativeWidgetMacNSWindow sendEvent:] ( native_widget_mac_nswindow.mm:463 )
[ 31 ] 0x7fff2322d754
[ 32 ] __34-[BrowserCrApplication sendEvent:]_block_invoke ( chrome_browser_application_mac.mm:351 )
[ 33 ] base::mac::CallWithEHFrame(void () block_pointer)
[ 34 ] -[BrowserCrApplication sendEvent:] ( chrome_browser_application_mac.mm:327 )
[ 35 ] 0x7fff235064f1
[ 36 ] 0x7fff230965ee
[ 37 ] base::MessagePumpNSApplication::DoRun(base::MessagePump::Delegate*) ( message_pump_mac.mm:827 )
[ 38 ] base::MessagePumpCFRunLoopBase::Run(base::MessagePump::Delegate*) ( message_pump_mac.mm:170 )
[ 39 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool, base::TimeDelta) ( thread_controller_with_message_pump_impl.cc:651 )
[ 40 ] non-virtual thunk to base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool, base::TimeDelta) ( thread_controller_with_message_pump_impl.cc:0 )
[ 41 ] base::RunLoop::Run(base::Location const&) ( run_loop.cc:134 )
[ 42 ] content::BrowserMainLoop::RunMainMessageLoop() ( browser_main_loop.cc:1072 )
[ 43 ] content::BrowserMainRunnerImpl::Run() ( browser_main_runner_impl.cc:159 )
[ 44 ] content::BrowserMain(content::MainFunctionParams) ( browser_main.cc:34 )
[ 45 ] content::RunBrowserProcessMain(content::MainFunctionParams, content::ContentMainDelegate*) ( content_main_runner_impl.cc:706 )
[ 46 ] content::ContentMainRunnerImpl::RunBrowser(content::MainFunctionParams, bool) ( content_main_runner_impl.cc:1276 )
[ 47 ] content::ContentMainRunnerImpl::Run() ( content_main_runner_impl.cc:1130 )
[ 48 ] content::RunContentProcess(content::ContentMainParams, content::ContentMainRunner*) ( content_main.cc:326 )
[ 49 ] content::ContentMain(content::ContentMainParams) ( content_main.cc:343 )
[ 50 ] ChromeMain ( chrome_main.cc:187 )
[ 51 ] main ( chrome_exe_main_mac.cc:216 )
[ 52 ] 0x7fff207c0f3d
```

**Comment by gh0sti** [comment]
crashes for me as well just updated to [Version 1.52.110 Chromium: 114.0.5735.35 (Official Build) (64-bit)](https://brave.com/latest/)

**Comment by joejoejo** [comment]
still crashing on Version 1.53.67 Chromium: 114.0.5735.53 (Official Build) beta (64-bit)

**Comment by joejoejo** [comment]
Why wont you guys fix this blatant bug that you cant open the hamburger menu when you have the new 2023 chrome refresh flags on. it does not seem right to have a new refresh that is going to be the default interface sometime this year as not going to fix,

**Comment by joejoejo** [comment]
if it is closed then why it is still open. cant answer that one but i can answer that this needs to fixed before chrome makes it the default ui

**Comment by gh0sti** [comment]
> if it is closed then why it is still open. cant answer that one but i can answer that this needs to fixed before chrome makes it the default ui

it might also not be ready by google chrome itself since its a beta feature that has to be turned on in flags. If you tried it on chrome or chromium there might be bugs in those browsers as well. Also google hasn't pushed that flag to production and forced the new UI on chrome/chromium. There is time for the UI/flag to be tweaked

**Comment by joejoejo** [comment]
i have tried on chrome and i don't see any problems

**Comment by joejoejo** [comment]
if this is fixed then why has it not been implemented into the release and beta/dev builds

**Comment by gh0sti** [comment]
> if this is fixed then why has it not been implemented into the release and beta/dev builds. this is not completed if the builds i and [gh0st](https://github.com/gh0sti) use are not fixed yet

it's been added to Nightly build which will make its way down to dev,beta, then release. Again 2023 flag hasn't been enforced yet in chrome. flags are beta features anyways and aren't fully fleshed out.

**Comment by joejoejo** [comment]
> > if this is fixed then why has it not been implemented into the release and beta/dev builds. this is not completed if the builds i and [gh0st](https://github.com/gh0sti) use are not fixed yet
> 
> it's been added to Nightly build which will make its way down to dev,beta, then release. Again 2023 flag hasn't been enforced yet in chrome. flags are beta features anyways and aren't fully fleshed out.

I know what you're saying, and it makes sense, but it will be at least a month before we get the fix in the beta/dev builds, and it would take a lot longer for the release builds. I just want to have my hamburger menu fixed already, which it could have been by now.

**Comment by gh0sti** [comment]
> > > if this is fixed then why has it not been implemented into the release and beta/dev builds. this is not completed if the builds i and [gh0st](https://github.com/gh0sti) use are not fixed yet
> > 
> > 
> > it's been added to Nightly build which will make its way down to dev,beta, then release. Again 2023 flag hasn't been enforced yet in chrome. flags are beta features anyways and aren't fully fleshed out.
> 
> I know what you're saying, and it makes sense, but it will be at least a month before we get the fix in the beta/dev builds, and it would take a lot longer for the release builds. I just want to have my hamburger menu fixed already, which it could have been by now.

Just turn the flag off until it comes down to other versions or install the nightly build. I understand you want to use the New UI from Google Chrome but it's not being enforced yet—just my 2 cents.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.58.80 Chromium: 116.0.5845.51 (Official Build) nightly (64-bit)
-- | --
Revision | 4408cc9795df260c5d5f033660ce757782b53b32
OS | Windows 10 Version 22H2 (Build 19045.3271)
```

### Steps:
1. installed `1.58.80`
2. launched Brave
3. enabled both `brave://flags/#chrome-refresh-2023` and `brave://flags/#chrome-webui-refresh-2023`
4. clicked `Relaunch`

### Confirmed UI became `Chrome`y (rounded corners, etc.) and didn't crash

`brave://flags` | `brave://settings`
----------------|-------------------
![image](https://github.com/brave/brave-browser/assets/387249/61898ade-2fe4-4e99-9345-d3af2e823266) | ![image](https://github.com/brave/brave-browser/assets/387249/3c9aeabb-18e5-4ec1-b0f9-e25669ca36e5)

**Comment by stephendonner** [comment]
## Verified `PASSED` using



Brave | 1.58.80 Chromium: 116.0.5845.51 (Official Build) nightly (x86_64)
-- | --
Revision | 4408cc9795df260c5d5f033660ce757782b53b32
OS | macOS Version 11.7.9 (Build 20G1426)

### Steps:

1. installed 1.58.80
2. launched Brave
3. enabled `brave://flags/#chrome-refresh-2023`
4. clicked `Relaunch`

## Confirmed UI became Chromey (rounded corners, etc.) and didn't crash

`brave://flags` | `brave://settings`
---------------|-----------------
<img width="1312" alt="Screen Shot 2023-08-08 at 11 47 58 AM" src="https://github.com/brave/brave-browser/assets/387249/7aefdc8d-7476-4dd8-85b1-d27d65aad66f"> | <img width="1312" alt="Screen Shot 2023-08-08 at 11 48 16 AM" src="https://github.com/brave/brave-browser/assets/387249/1a307838-0aca-464a-9f8b-d7bd5a71f7ca">

**Comment by LaurenWags** [comment]
updated to `release-notes/exclude` per discussion with @kjozwiak
