### ISSUE TITLE
Remove Swap V2 Theming from Side Nav

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#30498]
## Description 

Now that we have migrated `Swap V2` into brave-core, there is no longer a theme toggle on the `Swap` page. So we need to remove the special variables in the `Side` nav so that it changes with the `Browser` theme.

![Screenshot 4](https://github.com/brave/brave-browser/assets/40611140/0c5a947a-401b-4300-a0ad-ba7324c7a5d4)

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.57.24 Chromium: 115.0.5790.136 (Official Build) beta (64-bit)
-- | --
Revision | `8099932ede6f8d4624fbddf39d27abb3b340d8c9`
OS | Linux

- Verified steps from [brave/brave-core#18634](https://github.com/brave/brave-core/pull/18634)
- Verified `Side Nav` updates according to browser theme

https://github.com/brave/brave-browser/assets/17010094/dd134a25-ddbf-4516-8f17-bd2ded26649b

---------------------

**Verification passed on**

Brave | 1.57.24 Chromium: 115.0.5790.136 (Official Build) beta (64-bit)
-- | --
Revision | `8099932ede6f8d4624fbddf39d27abb3b340d8c9`
OS | Windows 11 Version 22H2 (Build 22621.1992)

- Verified steps from [brave/brave-core#18634](https://github.com/brave/brave-core/pull/18634)
- Verified `Side Nav` updates according to browser theme

https://github.com/brave/brave-browser/assets/17010094/68b54d31-33c9-49d1-a42c-384987eef755

---------------------

**Verification passed on**

Brave | 1.57.24 Chromium: 115.0.5790.136 (Official Build) beta (arm64)
-- | --
Revision | `8099932ede6f8d4624fbddf39d27abb3b340d8c9`
OS | macOS Version 13.4.1 (c) (Build 22F770820d)

- Verified steps from [brave/brave-core#18634](https://github.com/brave/brave-core/pull/18634)
- Verified `Side Nav` updates according to browser theme

https://github.com/brave/brave-browser/assets/17010094/220e5ad9-b889-4829-9eb8-0b65091289e3
