### ISSUE TITLE
Build out Portfolio Filters and Display Settings Modal

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#30496]
## Description 

We need to build out the `Portfolio Filters and Display Settings` modal

![Screenshot 3](https://github.com/brave/brave-browser/assets/40611140/3b1e9a5b-eb8c-4dcd-9d9d-47744e1fc6b1)

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.57.24 Chromium: 115.0.5790.136 (Official Build) beta (64-bit)
-- | --
Revision | `8099932ede6f8d4624fbddf39d27abb3b340d8c9`
OS | Linux

- Verified steps from [brave/brave-core#18727](https://github.com/brave/brave-core/pull/18727)
- Verified able to group assets by `Accounts`(default), `Networks` and `None`
- Verified grouping assets by `Accounts` shows all the tokens in the account
- Verified grouping assets by `Networks` groups tokens from all accounts and groups it based on network
- Verified grouping assets set to `None` shows all tokens as a single list
- Verified setting `Sort assets` to `High to Low` orders the tokens in descending order of balance/value
- Verified setting `Sort assets` to `Low to High` orders the tokens in ascending order of balance/value
- Verified setting `Sort assets` to `A to Z` orders the tokens in alphabetical order
- Verified setting `Sort assets` to `Z to A` orders the tokens in reverse alphabetical order
- Verified able to filter accounts based on network. 
- Verified able to filter list based on accounts 
- Verified `Hide small balances` when enabled hides all tokens from all accounts/networks which has value < $1

Group by | Sort Assets | Hide small balance | Network filter | Account filter
-- | -- | -- | -- | --
<video src=https://github.com/brave/brave-browser/assets/17010094/2a080536-87a7-46db-a6c0-508b3711db28>| <video src=https://github.com/brave/brave-browser/assets/17010094/f01241d6-97ca-41b6-acdc-0f18cf6b0ee1> | <video src=https://github.com/brave/brave-browser/assets/17010094/53bdb961-642d-4c5f-93dc-1902bfb5825e> | <video src=https://github.com/brave/brave-browser/assets/17010094/4eb5f5bc-90d6-4b9a-b22d-ea429ce5c19d> | <video src=https://github.com/brave/brave-browser/assets/17010094/c1fdd5f5-35f8-4d4a-a66c-4ce14b8fbb88>

---------------------

**Verification passed on**

Brave | 1.57.24 Chromium: 115.0.5790.136 (Official Build) beta (64-bit)
-- | --
Revision | `8099932ede6f8d4624fbddf39d27abb3b340d8c9`
OS | Windows 11 Version 22H2 (Build 22621.1992)

- Verified steps from [brave/brave-core#18727](https://github.com/brave/brave-core/pull/18727)
- Verified able to group assets by `Accounts`(default), `Networks` and `None`
- Verified grouping assets by `Accounts` shows all the tokens in the account
- Verified grouping assets by `Networks` groups tokens from all accounts and groups it based on network
- Verified grouping assets set to `None` shows all tokens as a single list
- Verified setting `Sort assets` to `High to Low` orders the tokens in descending order of balance/value
- Verified setting `Sort assets` to `Low to High` orders the tokens in ascending order of balance/value
- Verified setting `Sort assets` to `A to Z` orders the tokens in alphabetical order
- Verified setting `Sort assets` to `Z to A` orders the tokens in reverse alphabetical order
- Verified able to filter accounts based on network. 
- Verified able to filter list based on accounts 
- Verified `Hide small balances` when enabled hides all tokens from all accounts/networks which has value < $1

Group by | Sort Assets | Hide small balance | Network filter | Account filter
-- | -- | -- | -- | --
<video src=https://github.com/brave/brave-browser/assets/17010094/4880620f-d4ff-4583-9c24-2da4105c38e8>| <video src=https://github.com/brave/brave-browser/assets/17010094/21820f53-ef9d-4d75-8cc9-e357fa7c6792> | <video src=https://github.com/brave/brave-browser/assets/17010094/7c705b32-b477-449b-829b-96c91849c553> | <video src=https://github.com/brave/brave-browser/assets/17010094/a2e3bbc5-5ffe-4a36-94ab-4f85afcf735f> | <video src=https://github.com/brave/brave-browser/assets/17010094/2881d92c-e26d-47db-8f2e-cb277dfe9613>

---------------------

**Verification passed on**

Brave | 1.57.24 Chromium: 115.0.5790.136 (Official Build) beta (arm64)
-- | --
Revision | `8099932ede6f8d4624fbddf39d27abb3b340d8c9`
OS | macOS Version 13.4.1 (c) (Build 22F770820d)

- Verified steps from [brave/brave-core#18727](https://github.com/brave/brave-core/pull/18727)
- Verified able to group assets by `Accounts`(default), `Networks` and `None`
- Verified grouping assets by `Accounts` shows all the tokens in the account
- Verified grouping assets by `Networks` groups tokens from all accounts and groups it based on network
- Verified grouping assets set to `None` shows all tokens as a single list
- Verified setting `Sort assets` to `High to Low` orders the tokens in descending order of balance/value
- Verified setting `Sort assets` to `Low to High` orders the tokens in ascending order of balance/value
- Verified setting `Sort assets` to `A to Z` orders the tokens in alphabetical order
- Verified setting `Sort assets` to `Z to A` orders the tokens in reverse alphabetical order
- Verified able to filter accounts based on network. 
- Verified able to filter list based on accounts 
- Verified `Hide small balances` when enabled hides all tokens from all accounts/networks which has value < $1

Group by | Sort Assets | Hide small balance | Network filter | Account filter
-- | -- | -- | -- | --
<video src=https://github.com/brave/brave-browser/assets/17010094/f489f336-814e-4edd-915c-4fed56d9d946>| <video src=https://github.com/brave/brave-browser/assets/17010094/d47bffd0-ee84-4354-bce5-8af333ba3813> | <video src=https://github.com/brave/brave-browser/assets/17010094/520dfa86-0306-4871-a44f-441ee8f21caf> | <video src=https://github.com/brave/brave-browser/assets/17010094/a0a3a8c5-a6c4-4fa5-9144-097aab6d6a8c> | <video src=https://github.com/brave/brave-browser/assets/17010094/2c85e425-8c0f-46a6-8453-f121faafdf05>
