### ISSUE TITLE
Brave immediately crashes in incognito window

### ISSUE THREAD

**Issue by V01dgazer** [brave/brave-browser#30509]
## Description 
Brave immediately crashes when opening an incognito window.

## Steps to Reproduce

   1.  Run `brave --incognito`

## Actual result:

![image](https://github.com/brave/brave-browser/assets/24936843/f4a80f8d-e374-40af-9aca-ea69cd94dd74)

## Expected result:
Brave incognito window is opened

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 1.31.87 Chromium: 95.0.4638.54 (Official Build) (64-bit)
-- | --
Revision | d31a821ec901f68d0d34ccdbaea45b4c86ce543e-refs/branch-heads/4638@{#871}
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  No
- Does the issue resolve itself when disabling Brave Rewards? No 
- Is the issue reproducible on the latest version of Chrome?  No

**Comment by rebron** [comment]
@Selvdrap Can you send the crash report from brave://crashes and post the id here.

**Comment by Selvdrap** [comment]
Uploaded Crash Report ID: | a0df0800-8e2d-1b0a-0000-000000000000
-- | --

I figured out that it's being caused by Cookie-Editor extension, although it's not allowed in incognito mode.

**Comment by simonhong** [comment]
@Selvdrap Can you share the webstore link that causes this crash? thanks!

**Comment by iefremov** [comment]
doesn't reproduce anymore
