### ISSUE TITLE
Linux/Fedora: Beta and Nightly UI/text have inproper scaling. 

### ISSUE THREAD

**Issue by pjolt** [brave/brave-browser#30516]
## Description 
Some UI elements have inproper scaling in Linux Fedora 38. Like the text/title of tabs, right click menu, also main settings drop down menu has same issue with scaling/fonts. No issue with scaling/fonts with webpages or the ui in brave://settings/ 

## Steps to Reproduce
Updated from Beta 1.52.102 > 1.52.109 and noticed some elements/fonts are zoomed in. So i nstalled Nightly and same issue. 

   1. Update **from** Version 1.52.102 Chromium: 113.0.5672.126 (Official Build) beta (64-bit)
   2. Update **to** Version 1.52.109 Chromium: 114.0.5735.26 (Official Build) beta (64-bit)
   Nightly:
   1. Update **from** Version 1.53.41 Chromium: 113.0.5672.92 (Official Build) nightly (64-bit)
   2. Update **to** Version 1.53.44 Chromium: 114.0.5735.26 (Official Build) nightly (64-bit). Final Nightly w/o issue was the 1.53.41. And issue remains in Nightly up until Nightly v1.53.63 (Chromium 114.0.5735.26) which was the latest at time of testing. 

## Actual result:
![Nightly-1 53 44](https://github.com/brave/brave-browser/assets/120338442/d7edbaa1-f3d8-4297-a381-eddb08d4e419)
![Nightly-1 53 44__settings](https://github.com/brave/brave-browser/assets/120338442/be79119c-6ce0-4ae9-bed4-dace232d9122)

## Expected result:
![Nightly-1 53 41](https://github.com/brave/brave-browser/assets/120338442/0f09f774-5f09-4f06-afe5-ef5fee097156)
![Nightly-1 53 41_settings](https://github.com/brave/brave-browser/assets/120338442/32cc7123-b8d9-4d7f-bc47-e26899b4485c)

## Reproduces how often: 
Everytime. 

## Brave version (brave://version info)
Version 1.52.109 Chromium: 114.0.5735.26 (Official Build) beta (64-bit)
Version 1.53.44 Chromium: 114.0.5735.26 (Official Build) nightly (64-bit)

## Version/Channel Information:
Beta and Nightly. 

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:
- Is the issue reproducible on the latest version of Chrome? **No** (113.0.5672.126) (Also Vivaldi is unaffected). 
- Also tested by installing Brave Beta in developmental version of Fedora (Rawhide), same issue remains
- Tested with different scaling options for the display going from my default of 200 down and up, also tested with changing ozone from auto to wayland. Issue remains. 
- Also did a remove of Nightly config folder (.config/BraveSoftware) on installing each version when testing this to find which version this started with. 
- If more info is needed please provide detailed instructions and i'll be happy to assist in whatever way i can. 

## Miscellaneous Information:
Operating System: Fedora Linux 38
KDE Plasma Version: 5.27.5
KDE Frameworks Version: 5.106.0
Qt Version: 5.15.9
Kernel Version: 6.2.15-300.fc38.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 16 × 12th Gen Intel® Core™ i7-1260P
Graphics Processor: Mesa Intel® Graphics
2880x1800@90Hz with 200% scaling

**Comment by mgis90** [comment]
"zoomed in"? Are your fonts too big?

I have the issue where these fonts are too small.
As you wrote, right-click menu,

![too-small-brave](https://github.com/brave/brave-browser/assets/39676092/cbef9745-9ed6-41f4-bdc8-28a4d25c0242)

app main menu, especially tab titles, and bookmarks bar are affected

**Comment by pjolt** [comment]
> "zoomed in"? Are your fonts too big?
Maybe I should have said that fonts are too big instead. Which they are. 

I blame the fact of too little sleep on my poor choice of words.
