### ISSUE TITLE
Feature request: Add option for "Copy Cleanest Link"

### ISSUE THREAD

**Issue by mrose17** [brave/brave-browser#30524]
## Description 
"Copy Clean Link" is designed to deal with unnecessary query params. However, that's the low-hanging fruit. Many sites put the actual URL in a parameter, e.g., `https://${SITE}?u=${URL}` so that they can very effectively track where you go. While we debounce most of them and therefore clean the links of them, we specifically exclude bouncers that exist for security purposes (e.g. the Facebook and Google ones) from the default debouncer.

## Steps to Reproduce

   1. Go to a `${SITE}` (e.g., Facebook) that displays links to other sites (e.g., your own site, `${SITE2}`)
   2. What you see in the lower left-hand corner is not what the link actually is. (It looks like something that "Copy Clean Link" would fix!)
   3. Click on the link and watch as the browser re-directs you through `${SITE}` to get to `${SITE2}`

## Actual result:

1.  If you use "Copy Clean Link", it's a no-op: you go to `${SITE}` to get to `${SITE2}`

## Expected result:

!. If you use (the yet-undefined) "Copy Cleanest Link", then the link would be matched against a pattern database and the `${SITE2}` link would be the target.

## Reproduces how often: 
All too often.

**Comment by fmarier** [comment]
We could potentially add a second debounce step to the existing "copy clean link" with a list of bouncers that are out-of-scope for the debouncer, but would be appropriate for cleaning up URLs further.

**Comment by fmarier** [comment]
Merging with https://github.com/brave/brave-browser/issues/32299
