### ISSUE TITLE
Make user avatar in Rewards panel circular

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#30532]
```[tasklist]
### Tasks
- [ ] Make User avatar favicon circular (ensure that the size of the image remains reasonable)
- [ ] Do not touch website Favicons -- they can remain square
```

![image](https://github.com/brave/brave-browser/assets/11497541/2bd6c99c-d1ef-4473-a734-2a34f8fbd1a8)

**Comment by Miyayes** [comment]
Is this actually the same issue but in different form? @emerick 
![image](https://github.com/brave/brave-browser/assets/11497541/4e49192d-46bc-4302-b8af-d02d0186042a)

**Comment by emerick** [comment]
It looks like it!

**Comment by LaurenWags** [comment]
@emerick so would a test plan for this issue be just to confirm that for GitHub, Reddit, etc the favicon on the panel is round and for websites (i.e. brave.com) the favicon is square? anything else we'd need to check?

cc @Miyayes 

Example:
1.57.x | 1.58.x
--- | ---
<img width="402" alt="57" src="https://github.com/brave/brave-browser/assets/28145373/8a307331-28fb-4343-a955-10e0e9155d4b"> | <img width="401" alt="58" src="https://github.com/brave/brave-browser/assets/28145373/81c86087-e649-46b7-a76a-a2efe32b5d4c">

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.58.88 Chromium: 116.0.5845.82 (Official Build) beta (x86_64)
-- | --
Revision | acf16e35d5897fd4bf9b1b5a93b56aff2ed64bba
OS | macOS Version 13.5 (Build 22G74)
```

**Comment by LaurenWags** [comment]
Per discussion with @Miyayes changed this to be `release-notes/exclude`
