### ISSUE TITLE
Wallet addresses are not fully displayed in `Add Funds`

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#3053]
## Steps to Reproduce

   1. Clean profile
   2. Open `brave://rewards`
   3. Click `Add Funds`

## Actual result:

Some wallet addresses may be cropped
![wallet_addresses](https://user-images.githubusercontent.com/34715963/51573401-74d60480-1ea9-11e9-83cd-95dcf8491db0.gif)

## Expected result:
All wallet addresses are fully displayed

## Reproduces how often: 

always, with below recover codes:
`design flavor soldier news dismiss viable subject empower eight world swear lady range gloom romance dilemma risk dry remember frame duck orchard among barely`

## Brave version (brave://version info)

Brave | 0.59.26 Chromium: 72.0.3626.64 (Official Build) beta (64-bit)
-- | --
Revision | eaa9668e80ce5405e7f1902579558ea725c06ca1-refs/branch-heads/3626@{#708}
OS | Windows 7

Brave | 0.58.21 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Windows

Brave | 0.60.16 Chromium: 72.0.3626.64 (Official Build) dev (64-bit)
-- | --
Revision | eaa9668e80ce5405e7f1902579558ea725c06ca1-refs/branch-heads/3626@{#708}
OS | Windows

cc @brave/legacy_qa @NejcZdovc

**Comment by NejcZdovc** [comment]
cc @jenn-rhim @bradleyrichter

**Comment by kjozwiak** [comment]
Same results on `macOS 10.14.2 x64` using `0.59.26 Chromium: 72.0.3626.64`. Example:

<img width="453" alt="screen shot 2019-01-23 at 1 51 31 am" src="https://user-images.githubusercontent.com/2602313/51588255-88856900-1eb1-11e9-8908-5e8fb7949eee.png">

Displaying `0x093DFa3f64c9D8158Bd03BAB299aC574f76c366` but should be displaying `0x093DFa3f64c9D8158Bd03BAB299aC574f76c366f`

**Comment by NejcZdovc** [comment]
note: this is not a overside, we were aware of this limitation when designs were created

**Comment by LaurenWags** [comment]
It would be nice if we had a 'Copy' button for each address like in muon since I believe muon also had this limitation.

**Comment by NejcZdovc** [comment]
closing as this will be replaced with uphold widget
