### ISSUE TITLE
Add contract address and tokenId parameters to send page

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#30547]

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.57.23 Chromium: 115.0.5790.102 (Official Build) beta (64-bit)
-- | --
Revision | `d515871a6c6df7d2843e755c8b7dda9b744f26d6`
OS | Windows 11 Version 22H2 (Build 22621.1992)

- Verified steps from [brave/brave-core#18592](https://github.com/brave/brave-core/pull/18592)
- Verified contract address and token id parameters are shown in the URL on Send NFT page

https://github.com/brave/brave-browser/assets/17010094/5db97bd2-d7c8-473f-8ea0-29d699dd33fc
