### ISSUE TITLE
"URLFetcherCore::URLFetcherCore" crash when viewing YT videos

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#3054]
## Description 

[User from the community](https://community.brave.com/t/brave-crashes-when-playing-video-on-youtube/) is running into crashes whenever watching YouTube videos. User provided the following crash reports:

* https://stats.brave.com/dashboard#crash/5c471dc82daad9001fa87afd
* https://stats.brave.com/dashboard#crash/5c471dc7e70c50001f38757a
* https://stats.brave.com/dashboard#crash/5c471dc72242d6001f4d8ad6
* https://stats.brave.com/dashboard#crash/5c40de7e5d2553001f1a4dac

All of the above crash reports seem to be crashing here:

```URLFetcherCore::URLFetcherCore(net::URLFetcher *,GURL const &,net::URLFetcher::RequestType,net::URLFetcherDelegate *,net::NetworkTrafficAnnotationTag) [url_fetcher_core.cc : 106 + 0x0]```

## Steps to Reproduce

N/A as this is a user report. Hopefully the crash reports indicate what's causing these crashes.

## Actual result:

Brave crashing whenever playing videos on YT.

## Expected result:

Brave shouldn't be crashing when viewing YT videos.

## Reproduces how often: 

Seems like the user is running into this pretty often from the sounds of the report in Community.

## Brave version (brave://version info)

```
0.58.21 Chromium: 71.0.3578.98
```

### Website problems only:  

- Does the issue resolve itself when disabling Brave Shields?

No, user mentioned that disabling shields doesn't resolve the issue they're experiencing.

- Is the issue reproducible on the latest version of Chrome?

**Comment by adjakfar** [comment]
Any update on this issue? I still have problem with below Brave version. Thanks.
Windows 10
Version 0.61.52 Chromium: 73.0.3683.86 (Official Build) (64-bit)

**Comment by kjozwiak** [comment]
@adjakfar appreciate the update. Just out of curiosity, if you have Chrome installed, can you reproduce the same issue on there or does this just happen in Brave? It's currently labelled as a `P4`. Hopefully we can get a developer on this once some of the bigger `P3` tasks get completed.

In the meantime, I'll see if I can check and see how many folks might be running into the above crash.

**Comment by iefremov** [comment]
stale
