### ISSUE TITLE
Brave pkg installer creates BraveSoftware folder as root

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#30546]
## Description 

Pkg installer sets root permission to `~/Library/Application Support/BraveSoftware` folder.
`drwxr-xr-x   3 root   staff    96 May 24 13:10 BraveSoftware`.
It doesnt allow browsers from other channels to create their profiles.

## Steps to Reproduce

   1. Install brave stable from pkg
   2. Install brave Nightly/Beta from dmg or build from sources

## Actual result:

Browser crashed on start

## Expected result:

Browser launched successfully

## Reproduces how often: 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
@spylogsster will this fix anyone currently experiencing this issue or will this only prevent the problem going forward?

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.57.27 Chromium: 115.0.5790.114 (Official Build) beta (arm64) 
Revision	18977fb43f693d5a8deeb48bd1cfa52651d3f73e
OS	macOS Version 13.5 (Build 22G74)
```

**Comment by kjozwiak** [comment]
The above requires `1.56.18` or higher for `1.56.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.56.18 Chromium: 115.0.5790.138 (Official Build) (x86_64) 
Revision	0567db0e7dcdfee5c109c167119ac2a92b9b3e1a-refs/branch-heads/5790_85@{#9}
OS	macOS Version 12.6.8 (Build 21G725)
```

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.56.18 Chromium: 115.0.5790.138 (Official Build) (x86_64)
-- | --
Revision | 0567db0e7dcdfee5c109c167119ac2a92b9b3e1a-refs/branch-heads/5790_85@{#9}
OS | macOS Version 14.0 (Build 23A5301h)

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.56.20 Chromium: 115.0.5790.171 (Official Build) (arm64)
-- | --
Revision | cf9067bf10d8f798c24643029af1d24e275646d6-refs/branch-heads/5790@{#1924}
OS | macOS Version 13.5 (Build 22G74)
