### ISSUE TITLE
Unclaimed ad grants shows remaining days in negative number

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#30544]
## Description 
Unclaimed ad grants shows remaining days in negative number

## Steps to reproduce 

   1. Enable rewards and view ads 
   2. Wait for ad grants to show up
   3. Do not claim and wait for the grants to expiry
   4. Notification number is shown on rewards icon
   5. Open Rewards panel, ad grant shows negative days to claim the grant

## Actual result 
Expired grant shouldn't show `Claim Rewards` instead should show `Close` with an grant expired message. Also with this situation it can't get rid of the ad grant notifications in the panel

![image](https://github.com/brave/brave-browser/assets/17010094/333b1af9-6726-48fd-93c2-c8006fcc1d43) | ![image](https://github.com/brave/brave-browser/assets/17010094/8d919546-0c91-4dff-8d15-0fb6602e7594) | ![image](https://github.com/brave/brave-browser/assets/17010094/3857e3af-1c9f-4e06-bf0b-f9a2c9ff574a)
-- | -- | --

## Expected result
Should just say as expired and be able to close the notification.

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? NA

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 10
   
## Brave version
Release build from GPS 

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/rewards-client @husobee @Miyayes @emerick @brave/legacy_qa

**Comment by Miyayes** [comment]
Check date , if it's past the current time, don't show this notification.

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Samsung Galaxy version 12` running `Bravemonoarm64.apk_1.58.121`

- Confirmed that the no of days left is not displayed in -ve numbers

Example | Example | Example | Example | Example | Example | Example
----------|------------|---------|-----------|----------|-----------|----------
![Screenshot_20230912-180240_Brave](https://github.com/brave/brave-browser/assets/38657976/3eea3d18-1041-4947-8dec-880b95677ede) | ![Screenshot_20230912-180347_Brave](https://github.com/brave/brave-browser/assets/38657976/b4805884-432c-44bf-9e4b-6cd655b2fe91) | ![Screenshot_20230912-180353_Brave](https://github.com/brave/brave-browser/assets/38657976/524af5aa-2480-426e-9b00-a3d524c88160) | ![Screenshot_20231112-180545_Brave](https://github.com/brave/brave-browser/assets/38657976/f62efd61-d902-4c25-b745-e8696cf597f4) | ![Screenshot_20231112-180552_Brave](https://github.com/brave/brave-browser/assets/38657976/df4d68e3-c844-462b-9038-b4ccbf6774a6) | ![Screenshot_20231212-180635_Brave](https://github.com/brave/brave-browser/assets/38657976/086258f5-461d-468f-a85a-a11f59581db5) | ![Screenshot_20231212-180642_Brave](https://github.com/brave/brave-browser/assets/38657976/c522cf9c-a58a-41b4-8a08-cda97e4353de)
