### ISSUE TITLE
Implement full page view in chrome-untrusted://chat

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#30554]
See Figma designs here:
[https://www.figma.com/proto/h7fKSJF2P556bZWfyLTfwD/Brave-AI?page-id=700%3A19297&typ[…]717%2C0.65&scaling=min-zoom&starting-point-node-id=718%3A21889](https://www.figma.com/proto/h7fKSJF2P556bZWfyLTfwD/Brave-AI?page-id=700%3A19297&type=design&node-id=718-21889&viewport=-14%2C-1717%2C0.65&scaling=min-zoom&starting-point-node-id=718%3A21889)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.74.15 Chromium: 131.0.6778.85 (Official Build) beta (64-bit)
-- | --
Revision | d1293587128488865fa61e9fa277dd54aa2270b0
OS | Windows 11 Version 23H2 (Build 22631.4460)

- Verified steps from [brave/brave-core#25800](https://github.com/brave/brave-core/pull/25800)
- Verified Leo full page view is loaded when visiting `chrome-untrusted://chat` in a new tab
- Verified Leo has an expand view clicking on it expands  to full page view of Leo
- Verified Conversation history option is shown in menu
- Verified able to add new conversations when a new chat is created either via Leo side panel or full page view
- Verified when a conversation is selected, shows a back arrow to go back to conversation list
- Verified each conversation list retains the conversation history of that selected conversation
- Verified able to rename conversations
- Verified opening Leo on an article and clicking on expand loads the Chat in `chrome-untrusted:/chat/<UUID>` in a new tab
- Encountered [#42450](https://github.com/brave/brave-browser/issues/42450),[42451](https://github.com/brave/brave-browser/issues/42451), [42452](https://github.com/brave/brave-browser/issues/42452), [42610](https://github.com/brave/brave-browser/issues/42610), [42612](https://github.com/brave/brave-browser/issues/42612)

https://github.com/user-attachments/assets/9d74e26d-351b-45e1-919f-1144abe4fa9c

**Comment by LaurenWags** [comment]
Updated to `release-notes/exclude` per discussion with @kjozwiak @srirambv
