### ISSUE TITLE
Update NFT Pinning eligibility text

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#30550]
Figma [link](https://www.figma.com/file/4e7rsWzBUKv3dCdxCqB6CR/NFT-IPFS?type=design&node-id=1843-100527&t=goBCDGCbDzq2FBRu-0)

**Comment by srirambv** [comment]
Verification passed on  

Brave | 1.58.106 Chromium: 116.0.5845.114 (Official Build) beta (64-bit)
-- | --
Revision | 601f5c9afccc48f581021ae0e0ee6c85b58821d2
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#18692](https://github.com/brave/brave-core/pull/18692)
- Verified NFT pinning eligibility text is updated as per Figma link

![brave_Zx8uvONY2t](https://github.com/brave/brave-browser/assets/17010094/15d0a4ab-3125-422c-9a26-80ce7eaddfe6) | ![brave_zyc682QHJS](https://github.com/brave/brave-browser/assets/17010094/b040a3db-c510-4fa4-a37f-2e742e2a7c40)
-- | --
