### ISSUE TITLE
can't connect to VPN tunnel

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#30552]
## Description 

As per the discussion via https://bravesoftware.slack.com/archives/C03MMJ4CHEZ/p1684948501354339, it looks like VPN has regressed on Nightly. Once https://github.com/brave/brave-core/pull/18516 landed in `Nightly`, the user can create/install the VPN profile without any issues but won't be able to connect to the VPN tunnel. Checking several `what is my ip` websites, it looks like all the traffic is going through the local ISP even though the VPN has been enabled. Another indicator is that the data stream isn't appearing within the `VPN Notification`.

@Uni-verse @deeppandya & @vlad-hoff reproduced the issue as well. Current assumption is that it's `C114` related.

#### Perquisite: ensure that notifications are enabled via `Android 13+`

   1. install Nightly and ensure that you've enabled VPN
   2. once VPN is enabled, run through the process of purchasing a subscription via staging
   3. you'll notice that you'll be able to create/install a VPN profile
   4. VPN will look enabled but notice there's no data stream via the VPN notification
   5. visit https://ipinfo.io and notice that it's still listing your local ISP

## Actual result 

**`Example`** | **`Example`** | **`Example`**
----------------|----------------|-----------------
![Screenshot_20230524-130833](https://github.com/brave/brave-browser/assets/2602313/e2ab1c7a-0b76-4911-bec8-369ca11f5898) | ![Screenshot_20230524-130843](https://github.com/brave/brave-browser/assets/2602313/d5f7bf3e-cc6b-4712-83fe-5ebe0cab2109) | ![Screenshot_20230524-130849](https://github.com/brave/brave-browser/assets/2602313/1781f855-11d1-4f42-9af7-594ebd8bfc19)

## Expected result

Should be able to connect to the VPN tunnel and route data without any issues.

## Issue reproduces how often 

100% reproducible using the STR/Cases outlined above.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `No`
- Can you reproduce this issue with the current Play Store Beta version? `Yes` 
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Pixel 6`
   - Android version: `Android 14`
   
## Brave version

```
Brave | 1.54.3 Chromium: 114.0.5735.35 (Official Build) canary (64-bit)
--- | ---
Revision | 2295354895fa3652ae47b651481831484f16d1ff-refs/branch-heads/5735@{#713}
OS | Android 13; Build/UPB2.230407.014; 33; UpsideDownCake
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

### Additional information

CCing @deeppandya @Uni-verse @vlad-hoff @brave/qa-team

**Comment by kjozwiak** [comment]
@brave/qa-team when verifying the above, ensure that https://github.com/brave/brave-browser/issues/30419 is also working after the fix. Basically ensuring that the VPN profile is being created/installed without any issues. Will be verified by default when connecting to the VPN but make sure that you're installing using a new profile so we can verify that there's no issues with the profile creation portion of the code.

**Comment by kjozwiak** [comment]
@Uni-verse @vlad-hoff As per @deeppandya, we'll need to make sure that VPN is working when installing using both the `apk` and `aab`. Regarding `aab`, that can be verified/checked by installing the RC via the GPS internal beta channel once the above is uplifted and merged into the `1.52.x` branch.

**Comment by deeppandya** [comment]
> @Uni-verse @vlad-hoff As per @deeppandya, we'll need to make sure that VPN is working when installing using both the `apk` and `aab`. Regarding `aab`, that can be verified/checked by installing the RC via the GPS internal beta channel once the above is uplifted and merged into the `1.52.x` branch.

And @kjozwiak of we can make sure to verify the feature on 32 bit and 64 bit apk. We can check it through brave://version

**Comment by kjozwiak** [comment]
The above requires `1.52.115` or higher for `1.52.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21 5G` on the following build version(s): 

```
Brave	1.52.115 Chromium: 114.0.5735.53 (Official Build) (64-bit) 
Revision	c499d7ea22c8b2dba278465a5df7b86a8efa4e64-refs/branch-heads/5735@{#970}
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
```
Brave	1.52.115 Chromium: 114.0.5735.53 (Official Build) (32-bit) 
Revision	c499d7ea22c8b2dba278465a5df7b86a8efa4e64-refs/branch-heads/5735@{#970}
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

- Ensured purchasing a VPN subscription is successful via GPS build (64-bit) as well as using .apk build (32-bit).
- Ensured tunneling is working after VPN connection is established, VPN status is shown in the notification tray.
- Ensured that toggling VPN off/on works and disconnecting from VPN via the notification tray drop down will disabled the VPN.
- Ensured that `link VPN subscription` option is shown in the VPN settings and tapping it will load the brave.com page.
- Ensured that linking VPN subscription callout is shown after re-launching browser.
- Ensured that reseting configuration will remove VPN profile from settings and user is able to re-connect by installing profile once again.

Example | Example | Example | Example | Example | Example | Example 
-|-|-|-|-|-|-
![screenshot-1685465206619](https://github.com/brave/brave-browser/assets/17885425/b845d6e7-850b-4f66-8d3f-7c93c080c34b) | ![screenshot-1685465674837](https://github.com/brave/brave-browser/assets/17885425/6e353aaa-80b3-428d-a2a3-872a2e101096) | ![screenshot-1685465788866](https://github.com/brave/brave-browser/assets/17885425/0ccb6ae1-5c90-4eb4-8368-83d3eccf48a5) | ![screenshot-1685465710292](https://github.com/brave/brave-browser/assets/17885425/7214cf0d-c09d-4635-a84f-0206df258a1b) | ![screenshot-1685466740543](https://github.com/brave/brave-browser/assets/17885425/9480af84-6419-4f21-95fc-7199c7ea5677) | ![screenshot-1685465736707](https://github.com/brave/brave-browser/assets/17885425/74c2976a-8a6f-402a-942b-83e1e3fa24cd) | ![screenshot-1685466375249](https://github.com/brave/brave-browser/assets/17885425/10f80ba0-262d-4797-8935-ec86d55dc6d9)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Redmi Note 4` running `Android 7` using the following build(s):

```
Brave | 1.52.115 Chromium: 114.0.5735.53 (Official Build) (64-bit)
-- | --
Revision | c499d7ea22c8b2dba278465a5df7b86a8efa4e64-refs/branch-heads/5735@{#970}
OS | Android 7.0; Build/NRD90M; 24; REL
```

* ensured that `VPN` is not enabled as `VPN` is only enabled on `Android 8+`

**`Example`** | **`Example`**
----------------|-----------------
![Screenshot_2023-05-30-23-15-24-964_com brave browser](https://github.com/brave/brave-browser/assets/2602313/650fe1bb-7515-4af7-b57e-f41b72028623) | ![Screenshot_2023-05-30-23-15-53-023_com brave browser](https://github.com/brave/brave-browser/assets/2602313/90f5995c-73b1-4edd-8a16-cb24746a9379)
