### ISSUE TITLE
[Android] Playlist: lag before currently playing item is highlighted

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#30568]
## Description 
Minor thing but there is sometimes a little lag before the currently playing item gets highlighted. See video below.

https://github.com/brave/brave-browser/assets/28269287/bbbf89fa-d5dd-4394-ae0f-6549fbae3910

**Comment by kjozwiak** [comment]
After speaking with @deeppandya @Uni-verse @hffvld, we'll leave the above in `1.63.x` but label the issue as `QA/No` as `Playlist` has been moved from `1.63.x` -> `1.64.x`. @deeppandya mentioned that we'll have a `master` issue via `1.64.x` that will list all the `QA/Yes` issues that have been in the various milestones before `1.64.x`. This way QA will have a list of past `QA/Yes` issues that need to be checked/verified.
