### ISSUE TITLE
[Android] Playlist: show onboarding on tap of add button

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#30567]
### Current Behavior
When entering playlist onboarding from youtube video page = the onboarding opens on page load.

https://github.com/brave/brave-browser/assets/28269287/542e3c00-f59e-4136-a98b-4d5a5b26db51

### Expected Behavior
When entering playlist onboarding from youtube video page = the onboarding opens when user taps the add button.

### Why
We should not show playlist onboarding before the user interacts with the feature.

**Comment by kjozwiak** [comment]
After speaking with @deeppandya @Uni-verse @hffvld, we'll leave the above in `1.63.x` but label the issue as `QA/No` as `Playlist` has been moved from `1.63.x` -> `1.64.x`. @deeppandya mentioned that we'll have a `master` issue via `1.64.x` that will list all the `QA/Yes` issues that have been in the various milestones before `1.64.x`. This way QA will have a list of past `QA/Yes` issues that need to be checked/verified.
