### ISSUE TITLE
`Send a Tip...` for unverified publisher is hidden on Rewards Panel due to long translation strings

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#3056]
## Steps to Reproduce

   1. Change Brave language to `French`
   2. Open an unverified publisher page

## Actual result:

`Send a Tip...` for unverified publisher is hidden behind `Rewards Summery`
![image](https://user-images.githubusercontent.com/34715963/51581038-d789c900-1ec6-11e9-9a99-da007e978461.png)

## Expected result:
`Send a Tip...` is visible

## Reproduces how often: 

always

## Brave version (brave://version info)

Brave | 0.59.26 Chromium: 72.0.3626.64 (Official Build) beta (64-bit)
-- | --
Revision | eaa9668e80ce5405e7f1902579558ea725c06ca1-refs/branch-heads/3626@{#708}
OS | Windows

cc @brave/legacy_qa @NejcZdovc

**Comment by NejcZdovc** [comment]
will be fixed with https://github.com/brave/brave-browser/issues/2874
