### ISSUE TITLE
Audit if Brave Chat should be allowed in Guest, Private Windows, and Tor Windows

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#30561]
The current handling is:

- ✅ Normal windows: Leo is available in the sidebar
- ✅ Private window: Leo is available in the sidebar
- ❌ Tor window: Leo sidebar item is disabled, Leo is not available

Note that there was a bug introduced where URL bar suggestions were being added, this is being tracked and will be fixed soon here: https://github.com/brave/brave-browser/issues/33429

**Comment by stephendonner** [comment]
> @stephendonner please close this issue and mark the label `closed/not-actionable` after you confirm everything works as expected across the window types. See also this thread: https://bravesoftware.slack.com/archives/C8MP8ME4C/p1696509783923589

Done!  Verified all window types in https://github.com/brave/brave-browser/issues/33429#issuecomment-1761820338 👍
