### ISSUE TITLE
[Android] Playlist: improve fullscreen mode

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#30569]
## Description
There are a couple of issues with playlist fullscreen mode:

1. The device top bar is displayed in fullscreen mode. See photos below comparing playlist vs. youtube.com full screen.
- Perhaps because we do not maintain original aspect ratio of source video?
2. The add button is displays in fullscreen mode. Can swipe the button to make it disappear, maybe annoying for users.

| Brave Playlist | youtube.com |
| ------------- | ------------- |
| ![image](https://github.com/brave/brave-browser/assets/28269287/8fb8b410-c0a5-4120-b352-b6695d7bc2bb) | ![image](https://github.com/brave/brave-browser/assets/28269287/f1ccfe77-0220-4bfc-84d9-1c14ddfeb8c6) |

**Comment by kjozwiak** [comment]
After speaking with @deeppandya @Uni-verse @hffvld, we'll leave the above in `1.63.x` but label the issue as `QA/No` as `Playlist` has been moved from `1.63.x` -> `1.64.x`. @deeppandya mentioned that we'll have a `master` issue via `1.64.x` that will list all the `QA/Yes` issues that have been in the various milestones before `1.64.x`. This way QA will have a list of past `QA/Yes` issues that need to be checked/verified.
