### ISSUE TITLE
Website UI getting messed up.

### ISSUE THREAD

**Issue by Joel-N99** [brave/brave-browser#30579]
Websites displayed on brave are messed up. Missing text boxes, page elements completely missing, page labels and contents overlapping on one another, sometimes when I move another window on top of the browser and then move the window away it leaves an empty space in the browser through which my desktop wallpaper is visible. 

Version: Brave Browser 113.1.51.118

My system specs:
![fedora_system-spec](https://github.com/brave/brave-browser/assets/134592111/0e0a608b-0aa2-45b7-921e-7996764fab71)

**Comment by Joel-N99** [comment]
Here is a sample:
![brave_problem](https://github.com/brave/brave-browser/assets/134592111/48cb6456-cd98-427c-9adc-2df67bb93bce)

Here I have opened gmail where half of the search bar was missing, the labels around the search bar was overlapping on it. The long broken black line-thingy you see is me trying to get an area-screenshot. Prior to that the screenshot program left its silhouette on the gmail page which is dimly visible in the middle. This is happening today. Yesterday it was fine.

**Comment by LeoFibo** [comment]
If it was related to graphics drivers then theoretically it should also affect other applications. I have firefox installed beside brave and it works fine (except that it demands more cpu than brave).

**Comment by Joel-N99** [comment]
Its not driver related problem i think because firefox is working fine.

**Comment by ItaloFalzoni** [comment]
I am also having this problem. I updated the Ubuntu driver list, got some errors and forced the update. Among them, includes the mesa packages.
Here are the drivers that were updated and that caused problems in my Brave Browser.

mesa-vulkan-drivers:amd64 (22.2.5-0ubuntu0.1~22.04.1, 22.2.5-0ubuntu0.1~22.04.2)
mesa-vdpau-drivers:amd64 (22.2.5-0ubuntu0.1~22.04.1, 22.2.5-0ubuntu0.1~22.04.2)

**Comment by Joel-N99** [comment]
My mesa-vulkan-drivers are at version 23.0.3 so upgrading them (If possible) won't be helpful for you guys. 
Which version of brave are you guys using? Maybe if the version is common, then its safe to assume that its the software and not the drivers.

**Comment by tom-greene** [comment]
I am on Brave 1.51.118 and was still present in downgrading to 1.51.114 and 1.51.110. Did not seem to make a difference which version of Brave I was using. 

mesa-vulkan-drivers and mesa-vdpau-drivers are the same as @ItaloFalzoni before and after.

**Comment by ItaloFalzoni** [comment]
@Joel-N99 I see this info when I execute the `apt list` on ubuntu
`brave-browser/stable,now 1.51.118 amd64 [installed]`

**Comment by tom-greene** [comment]
@Joel-N99 I cannot tinker with settings because the settings page won't even render properly. Is there a way to pass in any rendering fallback flags?

**Comment by Joel-N99** [comment]
I don't know. I'd have to check when I get back home.
Try running 'brave-browser --help' from terminal. See if there is an option for it. Let me know.

**Comment by tom-greene** [comment]
This was a known issue for Brave. It did indeed have to do with the upgrade to the drivers.

The way to correct the situation in Linux is to remove the GPUCache directory. I removed it on my system and it did resolve the issue. 

`rm -fr .config/BraveSoftware/Brave-Browser/Default/GPUCache/`

Source: https://community.brave.com/t/latest-brave-update-fails-to-render-any-webpage-correctly/485593

**Comment by ed555009** [comment]
Removing `GPUCache` did not work on my mac, run with `-use-gl=egl` did, but brave starts a bit slower though.

Ref: [https://community.brave.com/t/brave-is-not-working-doesnt-show-pages-correctly-cant-even-change-settings/488593/3](https://community.brave.com/t/brave-is-not-working-doesnt-show-pages-correctly-cant-even-change-settings/488593/3)

**Comment by Joel-N99** [comment]
The solution given by @tom-greene worked! 

> Delete the entire GPUCache directory in ~/.config/BraveSoftware/Brave-Browser/Default/GPUCache (Do 'rm -rf' from terminal)
> Then restart brave.

@ed555009 have you found a solution on your system yet?

**Comment by ed555009** [comment]
@Joel-N99 Nope, but I tried turn off `Use hardware acceleration when available` then everything works as expected again.

No idea why but the `delete` method just don't work on mac. I will leave it there and wait for the next update.
