### ISSUE TITLE
Impact of future chromium changes

### ISSUE THREAD

**Issue by t0m5k1** [brave/brave-browser#3057]
Not exactly an issue "Yet"! but a potential one.

Just wanted to know how this:
https://www.theregister.co.uk/2019/01/22/google_chrome_browser_ad_content_block_change/

Will affect Brave if at all?

TL;DR

How will replacing the webRequest API with declarativeNetRequest API affect the ad blocking provided by Brave?

**Comment by t0m5k1** [comment]
TL;DR

How will replacing the webRequest API with declarativeNetRequest API affect the ad blocking provided by Brave?

**Comment by rebron** [comment]
Hi @t0m5k1. Closing this issue. If you can go to community.brave.com and ask there it's a better forum for this type of discussion. Thanks.
