### ISSUE TITLE
Remove the Brave News feature flag

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#30576]
The flag has been around for quite a while, and has been on by default for quite a while, so we should remove it. It's easier to turn Brave News off via the UI.

In addition, the NTP crashes when the flag is disabled (and probably has since the V2 release).

Related: https://github.com/brave/brave-browser/issues/30566

**Comment by Chaython** [comment]
Also setting the flag to disable it causes new tab page to be broken and fail to load "aw snap"
[#brave-news](chrome://flags/#brave-news)

**Comment by LaurenWags** [comment]
Verified with

```
Brave | 1.57.18 Chromium: 115.0.5790.98 (Official Build) beta (x86_64)
-- | --
Revision | d515871a6c6df7d2843e755c8b7dda9b744f26d6
OS | macOS Version 13.4.1 (a) (Build 22F770820b)
```

Verified test plan from https://github.com/brave/brave-browser/issues/30576#issuecomment-1588018740.

Confirmed "Brave News" flag is removed from 1.57.x, 1.59.6 is below for comparison.

1.56.9 | 1.57.18
--- | ---
<img width="1196" alt="1 56 9" src="https://github.com/brave/brave-browser/assets/28145373/d29b094d-1fac-4fe4-b63f-bfffc3b487d3"> | <img width="1197" alt="1 57 18" src="https://github.com/brave/brave-browser/assets/28145373/155263c1-6bfd-4862-bed3-7536cc419ab8">
