### ISSUE TITLE
Incorrect response for the metrics `Brave.Wallet.EthProvider.3` 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#30585]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/29193
Incorrect response for the metrics `Brave.Wallet.EthProvider.3` 
## Steps to Reproduce

1. Clean profile 1.52.x
2. Make sure the default provider is set to Brave wallet 
3. Set up a MM wallet
4. Open any HTTPS site
5. The metrics `Brave.Wallet.EthProvider.3` response value is `0`  instead of `3`

![image](https://github.com/brave/brave-browser/assets/38657976/21e7009b-397f-4f96-9c25-1c0691b4b636)

## Actual result:

Incorrect response for the metrics `Brave.Wallet.EthProvider.3` 
## Expected result:

The metrics response should be `3` `Brave Wallet (wallet is setup, an extension may potentially be installed but cannot override native provider)`

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.52.112 Chromium: 114.0.5735.35 (Official Build) (64-bit)
-- | --
Revision | 2295354895fa3652ae47b651481831484f16d1ff-refs/branch-heads/5735@{#713}
OS | Windows 10 Version 22H2 (Build 19045.2965)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @DJAndries @mattmcalister @brave/qa-team

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.54.64 Chromium: 114.0.5735.133 (Official Build) nightly (64-bit)
-- | --
Revision | fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}
OS | Windows 10 Version 22H2 (Build 19045.3086)

```

**Comment by kjozwiak** [comment]
The above requires `1.53.106` or higher for `1.53.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.53.108 Chromium: 115.0.5790.56 (Official Build) (64-bit)
-- | --
Revision | ebcfb87c1393f36955cfa2f6451a1767e3dc3ee5-refs/branch-heads/5790@{#1193}
OS | Windows 10 Version 22H2 (Build 19045.3086)

```
- Verified the issue in https://github.com/brave/brave-browser/issues/30874#issuecomment-1614775077
