### ISSUE TITLE
Cannot connect to bitFlyer in 1.53.x: Unexpected redirection or does not get to expected URL 

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#30589]
## Description

* Happens both on Android and desktop

@GeetaSarvadnya Had these logs:

```
2023-05-25 20:16:45.722 17834-17834/? I/chromium: [INFO:post_oauth_bitflyer.cc(54)] Unexpected HTTP status: 400
2023-05-25 20:16:45.723 17834-17834/? I/chromium: [INFO:connect_bitflyer_wallet.cc(77)] Couldn't get token
```
Geeta on 1.53.63. Also reported by a user in the wild in Japan, which means it reproduces in `prod` as well as `staging`. 

It is NOT reproducing on versions lower than 1.53.x, according to @A-t-s-u-s-h-i. 

<img src="https://github.com/brave/brave-browser/assets/11497541/d8b213f8-7e2e-46ac-913e-989a2a692914" width=400px>
<img src="https://github.com/brave/brave-browser/assets/11497541/d4cfee10-4ccb-4eba-a970-612258ace6cc" width=400px>

**Comment by szilardszaloki** [comment]
Issue was DevOps-related, new beta/nightly builds are in progress. @GeetaSarvadnya Would you mind reverifying with them on staging? @Miyayes This issue should only affect bitFlyer's sandbox envrionment, but just to make sure, could you try connecting with bitFlyer in production? Thanks!

**Comment by A-t-s-u-s-h-i** [comment]
> could you try connecting with bitFlyer in production?

I tried connecting bitFlyer account in prod, but somehow it doesn't connect. (v1.54.14) I don't see any error in rewards.log. @szilardszaloki 

https://github.com/brave/brave-browser/assets/79502386/8961b43b-36f7-44db-8151-d16b4c7f38b0

**Comment by GeetaSarvadnya** [comment]
Beta - 1.53.71 | Dev | Nightly
---------------|-------|-----------
![image](https://github.com/brave/brave-browser/assets/38657976/88b3de7c-1135-4a20-945a-ef4ff56d65ab)

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Samsung Galaxy version 12` running `Bravemonoarm.apk_1.53.91`

**Comment by LaurenWags** [comment]
@Miyayes helped coordinate the required checks on this one with @A-t-s-u-s-h-i.

Testing was completed and confirmed via https://bravesoftware.slack.com/archives/C01QVPRR3RR/p1686795418279699?thread_ts=1686586227.731559&cid=C01QVPRR3RR.

Thank you for the help!

**Comment by LaurenWags** [comment]
The testing for this on Android was also completed by @A-t-s-u-s-h-i.

Testing was confirmed and completed via https://bravesoftware.slack.com/archives/C01QVPRR3RR/p1687343247806969?thread_ts=1686586227.731559&cid=C01QVPRR3RR.

Thank you for the help with this one as well @A-t-s-u-s-h-i 😄
