### ISSUE TITLE
Optimised getPrice API call to fetch prices of all token via single call than individually (desktop)

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#30582]
## Description 

Desktop issue for https://github.com/brave/brave-browser/issues/30581

[desktop](https://github.com/brave/brave-core/blob/master/components/brave_wallet_ui/common/async/lib.ts#LL721C44-L721C44) are fetching prices of tokens individually but it can be fetched in a single call as getPrice can take token array as an input.

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.57.18 Chromium: 115.0.5790.98 (Official Build) beta (64-bit)
-- | --
Revision | `d515871a6c6df7d2843e755c8b7dda9b744f26d6`
OS | Windows 11 Version 22H2 (Build 22621.1992)

- Verified steps from issue description
- Verified prices for all tokens are shown correctly in Portfolio and on individual token details page
