### ISSUE TITLE
Add Wallet v2 header to screens

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#30583]

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.57.18 Chromium: 115.0.5790.98 (Official Build) beta (64-bit)
-- | --
Revision | `d515871a6c6df7d2843e755c8b7dda9b744f26d6`
OS | Windows 11 Version 22H2 (Build 22621.1992)

- Verified steps from [brave/brave-core#18733](https://github.com/brave/brave-core/pull/18733)

Buy | Send | Swap | Deposit 
-- | -- | -- | --
![brave_7OnKoIg6b8](https://github.com/brave/brave-browser/assets/17010094/f63b823d-d842-488f-b57a-7e4a0dab8294) | ![brave_bdOgYr0jv3](https://github.com/brave/brave-browser/assets/17010094/8d316e47-3e8c-40ac-908e-eec3f56b5f87) | ![brave_g4fHxEVc6b](https://github.com/brave/brave-browser/assets/17010094/0f9b09f0-97a6-4e53-b989-39fe00a48ffc) | ![brave_w2Z41Q4r8c](https://github.com/brave/brave-browser/assets/17010094/1a2cb116-910d-4369-a451-1286119c6087) 
Market | Account | Account details | Activity
| ![brave_l0Pxm7BVjQ](https://github.com/brave/brave-browser/assets/17010094/164c2750-ec68-49ba-aea7-f9d227e6f00a) | ![brave_H6zTa9reCn](https://github.com/brave/brave-browser/assets/17010094/4f28f378-d776-44df-a94c-056bf8b830d7) | ![brave_qYskjtHf08](https://github.com/brave/brave-browser/assets/17010094/181bfaec-6890-48fb-8099-631ed7486394) | ![brave_8VtuVoqVi4](https://github.com/brave/brave-browser/assets/17010094/b1cd8af2-004c-453e-9fc3-1e9beb60f969)
