### ISSUE TITLE
Tor not working just after clean install

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#3058]
## Steps to Reproduce

   1. Clean install (make sure that profile does not exists)
   2. Immediately after Brave is launched open `https://check.torproject.org/` in Tor Window

## Actual result:

Tor is not used
Tor will not be used till browser restart.
Tor process is not running.
![tor](https://user-images.githubusercontent.com/34715963/51619615-06d52000-1f31-11e9-9586-72f9e63ee378.gif)

## Expected result:
Tor is used

## Reproduces how often: 

90% of the time

## Brave version (brave://version info)

Reproduced on the latest builds for all channels.

Brave | 0.58.21 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Windows 7

Brave | 0.59.28 Chromium: 72.0.3626.64 (Official Build) beta (64-bit)
-- | --
Revision | eaa9668e80ce5405e7f1902579558ea725c06ca1-refs/branch-heads/3626@{#708}
OS | Windows 7

Brave | 0.60.16 Chromium: 72.0.3626.64 (Official Build) dev (64-bit)
-- | --
Revision | eaa9668e80ce5405e7f1902579558ea725c06ca1-refs/branch-heads/3626@{#708}
OS | Windows 7

cc @brave/legacy_qa @tomlowenthal @riastradh-brave

**Comment by LaurenWags** [comment]
haven't been able to reproduce on macOS yet using

Brave | 0.59.28 Chromium: 72.0.3626.64 (Official Build) beta(64-bit)
-- | --
Revision | eaa9668e80ce5405e7f1902579558ea725c06ca1-refs/branch-heads/3626@{#708}
OS | Mac OS X

**Comment by kjozwiak** [comment]
Same results as @LaurenWags. Tried reproducing it ~20 times on macOS without any luck. Used `0.59.28 Chromium: 72.0.3626.64`.

**Comment by tomlowenthal** [comment]
Sounds like a race condition?

**Comment by srirambv** [comment]
@kjozwiak I can reproduce this on Linux. This is an issue because the option available in hamburger menu. Until Tor binaries are downloaded the Tor Window options is not shown on profile icon which is correct. Because we have the option to launch a Tor window from hamburger menu it creates a Tor window without the binaries downloaded completely. Thats why even after Tor binaries are downloaded it doesn't work until browser is restarted. Ideal behaviour should be show Tor window option in hamburger menu only after Tor binaries are downloaded. 

I used keyboard shortcuts to reproduce the issue as it works quickly than using the hamburger menu.

**Comment by tomlowenthal** [comment]
Ideal behavior is to ship Tor binaries with the installer so you don't have to wait.

**Comment by riastradh-brave** [comment]
See https://github.com/brave/brave-browser/issues/3349 for diagnosis of a related bug whose fix might fix this too.

Progress bar is blocked on https://github.com/brave/brave-browser/issues/359.

**Comment by grand-lotus-iroh** [comment]
I had this similar issue on Windows Desktop and I was able to fix it by cut & pasting two folders from a previous User Data Brave install.

`C:\Users\420VaypeNaysh\AppData\Local\BraveSoftware\Brave-Browser\User Data`

- tor
- Tor Profile

Close / Quit Brave and just rename your existing folders before you cut / paste.

![explorer_2019-02-14_14-48-16](https://user-images.githubusercontent.com/1291364/52813331-631df200-304e-11e9-9252-a8338f93c7f9.png)

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.61.38 Chromium: 73.0.3683.39 (Official Build) beta (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

This issue is partially fixed. It is no longer possible to open pages without Tor (Error page is shown).
But Tor is still not usable till browser restart. Logged: https://github.com/brave/brave-browser/issues/3512
