### ISSUE TITLE
profile manager shows wrong background

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#30599]
## Description 

Profile manager shows wrong background due to CR 114. 

## Steps to Reproduce

   1. Have multiple profiles from 1.51.x
   2. Upgrade to 1.52.112
   3. Notice the profile manager screen show the incorrect background/branding

## Actual result:

<img width="1047" alt="Screenshot 2023-05-25 at 12 13 58 PM" src="https://github.com/brave/brave-browser/assets/5951041/892abcf4-2b70-49b5-90e8-8b4b7e732d10">

## Expected result:
No background image
<img width="1046" alt="Screenshot 2023-05-25 at 12 18 39 PM" src="https://github.com/brave/brave-browser/assets/5951041/ca4d2019-83f6-41ef-a997-f9e6e18a2c6e">

## Reproduces how often: 

Easily

## Brave version (brave://version info)

1.52.112 and higher with CR 114

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a Release candidate
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by kjozwiak** [comment]
The above requires `1.52.115` or higher for `1.52.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.52.115 Chromium: 114.0.5735.53 (Official Build) (64-bit)
-- | --
Revision | c499d7ea22c8b2dba278465a5df7b86a8efa4e64-refs/branch-heads/5735@{#970}
OS | Windows 10 Version 22H2 (Build 19045.2965)

```
