### ISSUE TITLE
Add support for EIP-6963

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#30595]
Add support for  EIP-6963 https://eips.ethereum.org/EIPS/eip-6963
You can test via:
https://eip6963.org/

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.58.108 Chromium: 116.0.5845.114 (Official Build) beta (64-bit)
-- | --
Revision | f08ffbe3ce0069ad8207b9d2d7dee38afcccc1b9
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#18751](https://github.com/brave/brave-core/pull/18751)

Brave Wallet | Extensions (Brave Wallet fallback) | Extensions (no fallback)
-- | -- | --
<video src=https://github.com/brave/brave-browser/assets/17010094/0c2eb484-d0d4-4841-bb50-4b3a504ee333> | <video src=https://github.com/brave/brave-browser/assets/17010094/4135ed6d-7a6b-4123-b54f-2b490627dad3> | <video src=https://github.com/brave/brave-browser/assets/17010094/90bda873-b6f8-4a45-833c-697b0933e37d>

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.58.117 x64 build
- Verified steps from [brave/brave-core#18751](https://github.com/brave/brave-core/pull/18751)
- Verified Brave Wallet is detected with or without Brave wallet being created

https://github.com/brave/brave-browser/assets/17010094/3dcc0cdb-902a-4dfd-95da-47e6597dab17
