### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by HagDady** [brave/brave-browser#30593]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.51.118 Chromium: 113.0.5672.126
Operating System: Windows NT 10.0.22621

URL (if applicable) where crash occurred: brave://settings/passwords

Can you reproduce this crash? Yes

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Will crash each time I load the URL
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/d9950100-4f5d-240a-0000-000000000000

**Comment by iefremov** [comment]
stale
