### ISSUE TITLE
Add a new brave://settings/leo-assistant section

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#30590]
- Automatically generating suggested questions while the panel is open
- Hide from sidebar
- Ability to reset

See Figma for latest designs, but here is the last I saw:
![Image](https://github.com/brave/brave-browser/assets/831718/a12f1527-92d5-4f85-ad0c-bc1b0a1daede)

Figma file: `https://www.figma.com/file/h7fKSJF2P556bZWfyLTfwD/Brave-AI?type=design&node-id=1105-28707&mode=design&t=K5RC3egmQTxtm05B-0`

**Comment by LaurenWags** [comment]
Added `QA/Blocked` - @kjozwiak to provide additional information

**Comment by bbondy** [comment]
@LaurenWags I answered this on the 15th but not sure if it was relayed.
I just mentioned that we should make sure it doesn't appear outside of Nightly and that on Nightly the settings do what they say they do.

**Comment by LaurenWags** [comment]
thanks @bbondy. I thought @kjozwiak had a follow up question, but I'll confirm with him. Is a single platform check ok or should this one be verified on all OSes?

**Comment by bbondy** [comment]
1 platform is enough. Thanks!

**Comment by LaurenWags** [comment]
@brave/qa-team removed `QA/Blocked` - this one can be verified on Nightly as per https://github.com/brave/brave-browser/issues/30590#issuecomment-1694348542. 

Additional comments/information/discussion can be found under https://bravesoftware.slack.com/archives/C04KPE0BUDU/p1693665530143249?thread_ts=1688150893.428279&cid=C04KPE0BUDU.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.59.76 Chromium: 116.0.5845.163 (Official Build) nightly (64-bit)
-- | --
Revision | 882a1d617108cea1c78439e27c5f19c46b276508
OS | Windows 11 Version 22H2 (Build 22621.2134)
```
