### ISSUE TITLE
paymentId/address discrepancy in ledger_state file - follow up to 2172

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#3060]
## Description 
Logging as a follow up to https://github.com/brave/brave-browser/issues/2172#issuecomment-456826171 per discussion with @NejcZdovc 

We have some users who are in a state where their paymentId/addresses in ledger_state don't match (the paymentId in ledger_state is not actually associated with the addresses listed) per #1831. We need to fix users who are in this state. 

Background/Context for historical purposes:
Logged in issue #1831 you'll see that there was an issue with paymentId and address mismatch after using Restore functionality. This issue was fixed for users going forward, however, we still need to fix users who are already in this mismatched state. That was logged in #2172 as a follow up issue. However, there was some miscommunication where it was thought that the ledger_state file contained the correct addresses, where unfortunately it did not. The fix for 2172 was to have the UI update to reflect what was in ledger_state, but what is in ledger_state is wrong. We need to take an additional step to update the addresses in ledger_state to be the ones that correspond with the paymentId in ledger_state. After this is done, the fix from 2172 should correctly display the addresses in the UI.

## Steps to Reproduce

1. Install 0.56.6 dmg (this is a Beta version)
2. Launch with clean profile and enable rewards.
3. Note backup words.
4. Note addresses displayed in Add Funds. 
5. Note paymentId, addresses, and CARD_ID from `ledger_state`.
6. Use restore functionality to Restore a wallet.
7. Note backup words (they updated to the words from the restored wallet and are different than step 3).
8. Note addresses in Add Funds (these are still the same as step 4). 
9. Open `ledger_state` and note paymentId (this was updated, so it's different than step 5) addresses and CARD_ID (these are all still the same as step 5).
At this point, you now have a paymentId/address discrepancy or mismatch. If you were to put the paymentId from step 9 into this URL: https://ledger.mercury.basicattentiontoken.org/v2/wallet/<paymentId> you can see what addresses should be displayed to compare to what is actually displayed.
10. Update to 0.59.28 Beta version.
11. Navigate to Rewards page.

## Actual result:
- Backup words for wallet match step 7 and paymentId matches step 9 (pass)
- Addresses in Add Funds are still the same as steps 4/8 (fail)
- Addresses and CARD_ID are still the same as steps 5/9 (fail)

## Expected result:
Backup words/paymentId for wallet should be accurate
Addresses in Add Funds should be updated to be the ones that correspond with the correct paymentID
Addresses and CARD_ID should be updated to be the ones that correspond with the correct paymentID

## Reproduces how often: 
easily with steps above

## Brave version (brave://version info)

Brave | 0.59.28 Chromium: 72.0.3626.64 (Official Build) beta(64-bit)
-- | --
Revision | eaa9668e80ce5405e7f1902579558ea725c06ca1-refs/branch-heads/3626@{#708}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information
cc @brave/legacy_qa

**Comment by btlechowski** [comment]
Reproduced on Ubuntu 17.10

Brave | 0.59.28 Chromium: 72.0.3626.64 (Official Build) beta(64-bit)
-- | --
Revision | eaa9668e80ce5405e7f1902579558ea725c06ca1-refs/branch-heads/3626@{#708}
OS | Linux

**Comment by LaurenWags** [comment]
@NejcZdovc I tried using the test plan in https://github.com/brave/brave-core/pull/1508 to test this issue but it wasn't working for me. Step 10 I get a message about how my wallet is corrupted and I need to restore (so I can't check addresses or backup words). So I skipped that and continued on in the test plan, but once I get to step 13 I see the same message so I can't see what recovery keys are:
![screen shot 2019-02-11 at 4 24 14 pm](https://user-images.githubusercontent.com/28145373/52594420-7c8a2880-2e19-11e9-8963-86de0f2c4cf4.png)

**Comment by NejcZdovc** [comment]
@LaurenWags will check it out and ping you tomorrow to see what is going on

**Comment by NejcZdovc** [comment]
Did you do first portion of the test on old version of the browser, right? That don't have this code in yet

**Comment by LaurenWags** [comment]
@NejcZdovc yep - I did steps 1-10 from test plan on 0.59.35 (current release channel version) - should I use an older version? 

fwiw - following the steps to reproduce from the description to test worked as expected.

**Comment by NejcZdovc** [comment]
@LaurenWags did you used this seed `OIeFXZsZd5rHDzAMwN1I0F1AX4S9KPM78uNTvmJZak8=`? If so you need to do test against staging

**Comment by NejcZdovc** [comment]
also did you modify paymentId by mistake? paymentId needs to be the same through the whole test

**Comment by LaurenWags** [comment]
@NejcZdovc what about card_id - should that be modified or left alone?

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.60.28 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/1508
* Verified STR from description
