### ISSUE TITLE
Branding/Design issue: Brave://new-tab-page/ still redirects to the Google New Tab page

### ISSUE THREAD

**Issue by Sa-Ja-Di** [brave/brave-browser#30601]
Issue: Brave://new-tab-page/ still redirects to the Google New Tab page

Issue:
-----------------
Enter brave://new-tab-page/
inside the browser

Result:
-----------------
Chromium internal new tab page with Google logo is appearing:
![Branding Issue](https://github.com/brave/brave-browser/assets/25885496/c098c1fc-7319-4101-9d8c-27a3adf4adf2)

Expected Result:
-----------------
Brave new tab page should appear

**Comment by Brave-Matt** [comment]
cc @rebron

**Comment by Sa-Ja-Di** [comment]
@Brave-Matt Nobody cares?

Also check out issue 
https://github.com/brave/brave-browser/issues/30611

**Comment by Sa-Ja-Di** [comment]
@rebron Hopefully this gets fixed :)

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/10676 (removing this page). Thanks for the report 😄
