### ISSUE TITLE
Custom-ad notification text is truncated/ellipsized

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#30605]
## Description 

Custom-ad notification text is truncated/ellipsized

Found while testing https://github.com/brave/brave-browser/issues/30510

## Steps to Reproduce

1. install `1.52.112`
2. launch Brave
3. open `brave://flags`
4. set `brave://flags/#brave-ads-custom-push-notifications-ads` to `Enabled`
5. enable `Rewards`
6. connect to a custodian
7. examine the first custom-ad notification

## Actual result:

example | example | example | example
---------|----------|---------|---------
<img width="1460" alt="Screen Shot 2023-05-25 at 5 09 39 PM" src="https://github.com/brave/brave-browser/assets/387249/6544f015-46b1-4db0-b584-b64fe2f21dfc"> | <img width="1460" alt="Screen Shot 2023-05-25 at 5 10 12 PM" src="https://github.com/brave/brave-browser/assets/387249/09af9d84-c4bf-4d3e-be2d-e385c7c76a7a"> | <img width="1783" alt="Screen Shot 2023-05-25 at 5 10 18 PM" src="https://github.com/brave/brave-browser/assets/387249/e07eec87-fd54-4b80-97f2-f1342010ede1"> | <img width="1783" alt="Screen Shot 2023-05-25 at 5 10 40 PM" src="https://github.com/brave/brave-browser/assets/387249/a0e74d9b-8b28-4955-a4d5-d50b478ee1a3">

## Expected result:

Not clipped (this is the default ad-notification dialog)

<img width="1783" alt="Screen Shot 2023-05-25 at 5 12 32 PM" src="https://github.com/brave/brave-browser/assets/387249/a86c2c1e-4173-4438-8bf5-4d982101bf5e">

## Reproduces how often: 

100% on Linux

## Brave version (brave://version info)

`1.52.112 Chromium: 114.0.5735.35`

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @emerick @btlechowski @Miyayes @rebron

**Comment by btlechowski** [comment]
cc @aseren @tmancey

**Comment by stephendonner** [comment]
## Verified `PASSED` using

Followed my original steps to reproduce in https://github.com/brave/brave-browser/issues/30605#issue-1726661880.

### Confirmed the custom-ad notification text isn't clipped/ellipsized, but renders in full

(Not sure why it doesn't appear to respect `Light` mode, but that's a separate issue.)

`Dark` mode | `Light` mode
--------------|-------------
<img width="1392" alt="Screen Shot 2023-08-07 at 5 03 33 PM" src="https://github.com/brave/brave-browser/assets/387249/9f55f624-13c6-436a-b6fa-e7850aab7ded"> | <img width="1392" alt="Screen Shot 2023-08-07 at 5 08 59 PM" src="https://github.com/brave/brave-browser/assets/387249/df3f2c03-eff1-4fdc-8c5e-ad3906fe1aaf">

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.58.101 Chromium: 116.0.5845.114 (Official Build) beta (x86_64)
-- | --
Revision | f6b6f6271f9a51efe3c5e2be309f1a12012880c6
OS | macOS Version 14.0 (Build 23A5328b)

### Steps:
1. installed `1.58.101`
2. launched Brave using `--enable-logging=stderr --vmodule="*/bat-native-ledger/*"=9,"*/brave_rewards/*"=9,"*/bat-native-ads/*"=9,"*/bat-native-confirmations/*"=9,"*/brave_ads/*"=9,"*/brave_user_model/*"=9 --rewards=staging=true,debug=true`
3. enabled Rewards
4. connected to Uphold via its staging sandbox
5. waited for an ad
6. clicked on it

### Confirmed the custom-ad notification text is displayed in full, and loads the `Brave Support` article

example | example | example
---------|----------|---------
<img width="1920" alt="Screenshot 2023-08-25 at 1 02 43 PM" src="https://github.com/brave/brave-browser/assets/387249/84a8090d-4148-4518-8ed3-fcb1fae6a76f"> | <img width="1920" alt="Screenshot 2023-08-25 at 12 58 33 PM" src="https://github.com/brave/brave-browser/assets/387249/a01fb6c2-9b03-4dc3-a840-1c6411592720"> | <img width="1584" alt="Screenshot 2023-08-25 at 12 58 40 PM" src="https://github.com/brave/brave-browser/assets/387249/39dca70f-7007-4a2e-adcf-09d20211bc8c">

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.58.101 Chromium: 116.0.5845.114 (Official Build) beta (64-bit)
-- | --
Revision | f6b6f6271f9a51efe3c5e2be309f1a12012880c6
OS | Windows 10 Version 22H2 (Build 19045.3393)
```

### Steps:
1. installed `1.58.101`
2. launched Brave using `--enable-logging=stderr --rewards=staging=true,debug=true`
3. enabled Rewards
4. connected to Uphold's staging sandbox
5. waited for an ad
6. clicked on it


example | example
---------|-----------
![image](https://github.com/brave/brave-browser/assets/387249/e1bac93d-6583-4cb8-9aad-4bc8cad98254) | ![image (1)](https://github.com/brave/brave-browser/assets/387249/ba961bf7-424a-49fd-82ab-763ed1aa20ce)
