### ISSUE TITLE
improve design how server locations are displayed

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#30606]
## Description 

We should improve the design/how the different VPN server locations appear via the `VPN Settings`. Currently they all appear in a grey box with grey text. At first, it looks like everything is `disabled`. Usually features that are disabled/non-selectable are lightly greyed out. Another suggestion would be to bold the server location that's currently selected rather than just displaying ✔️.

## Steps to reproduce 

   1. install brave and ensure that VPN has been enabled
   2. go into `Settings` -> `Brave Firewall + VPN` -> `Location`

## Actual result 

![Screenshot_20230524-130745](https://github.com/brave/brave-browser/assets/2602313/84aed354-5a8e-44e9-8325-5b47d2af375d)

## Expected result

* should make the server location selection screen more appealing/easier on the eye (looks like it's all greyed out right now)
* maybe also bold the selected location so its easier to see which one has been selected rather than just the ✔️ 

## Issue reproduces how often 

100% reproducible using the STR/Cases outlined above.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `Yes`
- Can you reproduce this issue with the current Play Store Beta version? `Yes` 
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Pixel 6`
   - Android version: `Android 14`
   
## Brave version

```
Brave | 1.52.112 Chromium: 114.0.5735.35 (Official Build) (32-bit)
--- | ---
Revision | 2295354895fa3652ae47b651481831484f16d1ff-refs/branch-heads/5735@{#713}
OS | Android 13; Build/UPB2.230407.014; 33; UpsideDownCake
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by mattmcalister** [comment]
Closing as stale. New issues being created such as:

- [ ] https://github.com/brave/brave-browser/issues/36277
- [ ] https://github.com/brave/brave-browser/issues/36409
