### ISSUE TITLE
Remove widget promo

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#30618]
This issue is to remove widget promo to improve UX. 
For more context : https://bravesoftware.slack.com/archives/C0816QH3R/p1684715131423109

**Comment by kjozwiak** [comment]
The above requires `1.52.115` or higher for `1.52.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy Tab S7` using the following build(s):

```
Brave	1.52.115 Chromium: 114.0.5735.53 (Official Build) (64-bit) 
Revision	c499d7ea22c8b2dba278465a5df7b86a8efa4e64-refs/branch-heads/5735@{#970}
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
Using Test Plan in https://github.com/brave/brave-core/pull/18638#issuecomment-1567680559

#### `Test Case #1` (opening tabs/restarting browser)

* opened ~30 tabs and ensured that the OSK is being shown when tapping on the omnibox every single time
  * ensured that the `Widget onboarding` modal isn't triggered/appearing when tapping on the omnibox
  * after opening ~30 different tabs, restart the browser ~20 times and ensured that the `Widget onboarding` isn't displayed
  * ensured that you can still add a home widget via `Hambruger Menu` -> `Settings` -> `Home screen widget`
    * ensured that you can add other Brave widgets via `Widgets` on the `Android Home` screen
* ensured that all the widgets are removed when Brave is uninstalled

#### `Test Case #2` (restarting browser/opening tabs)

* opened Brave ~30 times and ensured that the OSK is being shown when tapping on the omnibox every single time
  * ensured that the `Widget onboarding` modal isn't triggered/appearing when tapping on the omnibox
  * after opening Brave ~30 different times, opened ~20 tabs and ensured that the `Widget onboarding` isn't displayed
  * ensured that you can still add a home widget via `Hambruger Menu` -> `Settings` -> `Home screen widget`
    * ensured that you can add other Brave widgets via `Widgets` on the `Android Home` screen
* ensured that all the widgets are removed when Brave is uninstalled

**Comment by Uni-verse** [comment]
In progress using 

Brave	1.52.115 Chromium: 114.0.5735.53 (Official Build) (32-bit) 
Revision	c499d7ea22c8b2dba278465a5df7b86a8efa4e64-refs/branch-heads/5735@{#970}
OS	Android 8.0.0; Build/OSR1.180418.026; 26; REL
