### ISSUE TITLE
Say Brave main menu

### ISSUE THREAD

**Issue by jidanni** [brave/brave-browser#30613]
Here using the "close all tabs" menu item, we see references to Chrome instead of Brave.

![Screenshot_20230526_093052_Brave - Beta.jpg](https://github.com/brave/brave-browser/assets/1230959/3e1e88ec-10bb-4f8a-8a22-d62c65eed997)

**Comment by kjozwiak** [comment]
The above requires `1.53.107` or higher for `1.53.x` verification 👍

**Comment by kjozwiak** [comment]
The above requires `1.52.130` or higher for `1.52.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21 5G` using the following build:

```
Brave	1.52.130 Chromium: 114.0.5735.198 (Official Build) (32-bit) 
Revision	c3029382d11c5f499e4fc317353a43d411a5ce1c-refs/branch-heads/5735@{#1394}
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
- Verified closing all tabs from the tab menu references "Brave."

![screenshot-1688656870315](https://github.com/brave/brave-browser/assets/17885425/fa7409e1-ea04-4476-8551-e7230eddf7f5)
