### ISSUE TITLE
Update Widevine signature generation script to Python 3

### ISSUE THREAD

**Issue by mherrmann** [brave/brave-browser#30615]
Widevine is the DRM technology that protects access to streaming videos. Its implementation in browsers requires that its binaries be signed. We need to generate `brave.exe.sig` and `chrome.dll.sig` on Windows and similar files on macOS. Widevine reads the `.sig` files to determine whether the application was modified, and thus whether or not it can be trusted. If it cannot be trusted, then streaming providers such as Netflix serve lower-quality videos.

We use a script to generate the `.sig` files. (It is not checked into brave-core for licensing reasons.) It is written with Python 2 and requires the `cryptography` library to be installed on developer machines. The goal of this issue is to migrate the script to Python 3 and invoke it with `vpython3`, which ships with the `cryptography` library, so devs don't have to install it.

The purpose of having this issue in `brave-browser` is for QA to know and please test that DRM-protected content can still be streamed at the highest quality on Windows and macOS. See for example https://github.com/brave/brave-browser/issues/29469#issuecomment-1544976210 for some good tests.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.58.80 Chromium: 116.0.5845.51 (Official Build) nightly (x86_64)
-- | --
Revision | 4408cc9795df260c5d5f033660ce757782b53b32
OS | macOS Version 11.7.9 (Build 20G1426)
```

Widevine component details:

Amazon Prime

HBO Max

Netflix

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.58.96 Chromium: 116.0.5845.96 (Official Build) beta (64-bit)
-- | --
Revision | 153399f19fc2a3db55e64efb3ad06cb52d8a39fb
OS | Windows 11 Version 22H2 (Build 22621.2134)
```

**_Netflix_** - `PASSED

1. installed 1.58.96
2. launched Brave
3. loaded netflix.com
4. signed in
5. confirmed I was prompted to Install and run Widevine
6. clicked Allow
7. played the show

Confirmed Widevine component was installed and Netflix the content was streamed in High-Definition (HD) content, through visual inspection

example | example | example | example 
---- | ----- | ---- | -----
<img width="956" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/8e14b780-5cf9-4521-9530-101c44d0c06f">|<img width="935" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/67831a1e-5ff3-408a-8a86-974cda09ceab">|<img width="221" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/a2c8bda7-ff58-4b7c-8dda-928a6989e6fa">|<img width="956" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/86bfdc9e-57c4-407e-bd53-38af255dc630">
</Details>

**_Amazon Prime_** - PASSED
<Details>

1. installed 1.58.96
2. launched Brave
3. loaded [www.amazon.com](http://www.amazon.com/)
4. confirmed I was prompted to install Widevine
5. logged in and tried to play a video
6. clicked on Allow
7. successfully played the video 

#### Confirmed the content was streamed in High-Definition (HD) quality. "Best" quality level @ 1080p - (6.84 GB per hour)

example | example 
---- | ----
<img width="499" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/b0a2a584-ea70-4e52-8144-f4a4db7efd57">|<img width="499" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/12a1fcbe-4494-4d2c-80f5-b1b87e5c3206">

</Details>

**_HBO Max_** - PASSED
<Details>

Steps:

1. installed 1.58.96
2. launched Brave
3. loaded max.com
4. logged in
5. tried to play Dune
6. confirmed I was prompted to Install and run Widevine
7. clicked on Restart to play the movie

#### Confirmed the content was streamed in High-Definition (HD) quality, through visual inspection

example | example 
---- | -----
<img width="232" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/9d291a5a-cd48-4799-89bb-0403899cbf85">|<img width="232" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/e29df986-3627-4c09-9242-29b0d6c557fe">

</Details>
