### ISSUE TITLE
Scrolling is too aggressive with tab groups, can scroll to have an empty panel

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#30627]
## Description 

With vertical tabs enabled and with a group with lots of tabs, can get into a state (by collapsing the tabs group) where scrolling doesn't stop and can appear to have an empty vertical tabs panel.

It seems like when tab groups are collapsed, it's scrolling as if tabs groups is expanded.

## Steps to Reproduce

   1. Enable vertical tabs. 
   2. Create a tab group with 20+ tabs in that group.
   3. Collapse tab group and scroll. Notice you can make the vertical tabs panel appear empty.

## Actual result:

<img width="348" alt="Screenshot 2023-05-26 at 2 06 32 PM" src="https://github.com/brave/brave-browser/assets/5951041/07787da3-a4b8-48da-ad83-61bbc02b8e18">
<img width="280" alt="Screenshot 2023-05-26 at 2 07 02 PM" src="https://github.com/brave/brave-browser/assets/5951041/9edf14a0-78d4-42ee-ac24-992bb4c744a6">

## Expected result:
Tab scroll should stop.

## Reproduces how often: 

Easily.

## Brave version (brave://version info)

1.53.66

## Version/Channel Information:

- Can you reproduce this issue with the current release? (didn't check but likely)
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by sangwoo108** [comment]
On Mac, it doesn't seem to reproducible but on Windows it does.

**Comment by sangwoo108** [comment]
@rebron Can you reproduce this on Nightly too?

**Comment by kjozwiak** [comment]
The above requires `1.53.101` or higher for `1.53.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.53.102 Chromium: 114.0.5735.133 (Official Build) (64-bit)
-- | --
Revision | fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}
OS | Windows 11 Version 22H2 (Build 22621.1848)
```

Reproduced using original STR from the description in https://github.com/brave/brave-browser/issues/30627#issue-1728255233 in `1.53.66 Chromium: 114.0.5735.35`
However, this is not reproducible in current release `1.52.126 Chromium: 114.0.5735.133 (Official Build) (64-bit)` 

https://github.com/brave/brave-browser/assets/98358127/cd3271af-f334-4de4-a5e9-794d69b408e0



Confirmed no empty vertical tab panel is shown when tab group is collapsed and tab scroll is not available

https://github.com/brave/brave-browser/assets/98358127/79c42972-6380-4bc0-8031-e043e0d5d8d9
