### ISSUE TITLE
Follow up of #24338 - Constellation/STAR encryption for P3A is not working on Android

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#30622]
## Description 
Found while testing #24338 
Follow up of #24338 - Constellation/STAR encryption for P3A is not working on Android
## Steps to reproduce 

   1. Follow the test plan from https://github.com/brave/brave-core/pull/14399
   2. `brave.p3a.approved_cert_fp` , `brave.p3a.current_epoch`, `brave.p3a.current_pk`, `brave.p3a.next_epoch_time` and `p3a.logs_constellation_prep` are not shown in the brave://local-state file
   3. p3a.constellation_logs.{epoch number} is not shown in the local state file
   4. randomness requests are NOT sent when browser is launched using `--enable-features="BraveP3AConstellation" --p3a-star-randomness-host=https://star-randsrv.bsg.brave.software/ --p3a-constellation-upload-url=https://collector.bsg.bravesoftware.com/ --p3a-fake-star-epoch=0`
   
![image](https://github.com/brave/brave-browser/assets/38657976/bdf8bb75-a72e-4875-bf59-efdc5befe272)

## Actual result 

Follow up of #24338 - Constellation/STAR encryption for P3A is not working on Android
## Expected result

Constellation/STAR encryption for P3A should be working on Android
## Issue reproduces how often 
1.52.112

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version?Not sure

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet):all
   - Android version: 12
   
## Brave version
1.52.112

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

CC: @brave/qa-team @DJAndries @mattmcalister @rillian

**Comment by DJAndries** [comment]
@GeetaSarvadnya please omit the trailing slash on the `--p3a-star-randomness-host` switch, and omit the `--p3a-fake-star-epoch=0` flag depending on which test plan you're following

**Comment by GeetaSarvadnya** [comment]
@DJAndries In step 0 (https://github.com/brave/brave-core/pull/14399) I have used the cmd line flag as `--enable-features="BraveP3AConstellation" p3a-star-randomness-host=https://star-randsrv.bsg.brave.software --p3a-constellation-upload-url=https://collector.bsg.bravesoftware.com/` even though it's not working as expected

**Comment by DJAndries** [comment]
@GeetaSarvadnya please add two hyphens before the `p3a-star-randomness-host` switch

**Comment by GeetaSarvadnya** [comment]
@DJAndries I have launched the browser using the cmd line flag `--enable-features="BraveP3AConstellation" --p3a-star-randomness-host=https://star-randsrv.bsg.brave.software --p3a-constellation-upload-url=https://collector.bsg.bravesoftware.com/` still it's not working

**Comment by DJAndries** [comment]
@GeetaSarvadnya Today I updated the test plan with a new star randomness host. Please test using `--p3a-star-randomness-host=https://star-randsrv.bsg.bravesoftware.com`. thanks

**Comment by GeetaSarvadnya** [comment]
@DJAndries I have retested issue using the cmd line mentioned above `--p3a-star-randomness-host=https://star-randsrv.bsg.bravesoftware.com. thanks` - The issue is still reproducible.

**Comment by DJAndries** [comment]
Can you please clarify what isn't working? I just tested using the command line: `--enable-features="BraveP3AConstellation" --p3a-star-randomness-host=https://star-randsrv.bsg.bravesoftware.com --p3a-constellation-upload-url=https://collector.bsg.bravesoftware.com/`

I'm able to see all the relevant details in local state, and i'm seeing metrics in the `logs_constellation_prep` getting sent/prepared.

**Comment by GeetaSarvadnya** [comment]
@DJAndries Verified the issue on `Samsung Galaxy version 12` running `Bravemonoarm64.apk_1.53.108` 

The issue is not working as expected, detained steps are mentioned below:


### 1.  Test without a MITM proxy

1. Install Brave `1.55.108` on Android device
2. Enable the developer option
3. Open the QA Preferences and enter the cmd line `brave.exe --enable-features="BraveP3AConstellation" --p3a-star-randomness-host=https://star-randsrv.bsg.brave.software --p3a-constellation-upload-url=https://collector.bsg.bravesoftware.com/` in the `Command Line string`
4. Relaunch the browser
5. Open https://star-randsrv.bsg.brave.software/info and look for the parameter `currentEpoch`
6. Confirm that the parameter `currentEpoch` value is `0`
7. Open brave://local-state file and look for `brave.p3a.approved_cert_fp` 
8. **The parameter `approved_cert_fp` is not shown under brave://local-state file**
9. **The parameter `current_pk` is not shown under brave://local-state file**
10. **The parameter.next_epoch_time` is not shown under brave://local-state file**
11. Confirm that `p3a.logs_constellation_prep` exist with the typical list of metrics/values/etc.

The steps 8,9 and 10 are not working 

step 8 | step 9 | step 10 | step 11
-------|--------|---------|---------
![Screenshot_20230630-223348_Brave](https://github.com/brave/brave-browser/assets/38657976/95e780e2-4faf-453c-a0ca-dee381b0f370) | ![Screenshot_20230630-223414_Brave](https://github.com/brave/brave-browser/assets/38657976/b456416c-e24d-4f28-81ab-156cd496201a) | ![Screenshot_20230630-223439_Brave](https://github.com/brave/brave-browser/assets/38657976/9aa91030-32d6-49ea-a80a-398e8b196bf5) | ![Screenshot_20230630-223544_Brave](https://github.com/brave/brave-browser/assets/38657976/957b04ed-ebe3-479d-87b7-38e478a4ca8c)

**Comment by DJAndries** [comment]
Please use the command line value in my previous comment. You also may have to wait up to 10 seconds for the preferences to show up in the local state page.

**Comment by DJAndries** [comment]
@GeetaSarvadnya Please use the command line value in my previous comment. You also may have to wait up to 10 seconds for the preferences to show up in the local state page.

**Comment by GeetaSarvadnya** [comment]
@DJAndries I used the cmd line flag which you mentioned above https://github.com/brave/brave-browser/issues/30622#issuecomment-1595451715 and reverified the issue, still I don't see the parameters `approved_cert_fp`, `current_pk` and `next_epoch_time` in the local-state file I waited for more than 15 mins.

`--enable-features="BraveP3AConstellation" --p3a-star-randomness-host=https://star-randsrv.bsg.bravesoftware.com --p3a-constellation-upload-url=https://collector.bsg.bravesoftware.com/`


step 8 | step 9 | step 10 | step 11
-------|--------|---------|---------
![Screenshot_20230703-164857_Brave](https://github.com/brave/brave-browser/assets/38657976/c2fa6dd8-c5a0-4015-853b-4a5092d6a2fa) | ![Screenshot_20230703-164755_Brave](https://github.com/brave/brave-browser/assets/38657976/055b8ac4-1795-4dc1-b4cc-97dc9930eb64) | ![Screenshot_20230703-164832_Brave](https://github.com/brave/brave-browser/assets/38657976/9ddc12e2-4838-48ec-8e6b-7559e3d347a2)

**Comment by DJAndries** [comment]
Are you using a MITM proxy? Please note that there are two test plans: one that uses a MITM proxy and one that doesn't. If you are using a proxy, you must append the `--p3a-disable-star-attestation` switch.

**Comment by GeetaSarvadnya** [comment]
@DJAndries I have tested the above case without using the proxy.

**Comment by DJAndries** [comment]
it seems that `star-randsrv.bsg.bravesoftware.com` is down at the moment. could you please try `star-randsrv.bsg.brave.com` in the meantime?

**Comment by GeetaSarvadnya** [comment]
@DJAndries: Verifie the issue using the `star-randsrv.bsg.brave.com,` I have verified the issue without proxy using the cmd line flag `--enable-features="BraveP3AConstellation" --p3a-star-randomness-host=https://star-randsrv.bsg.brave.com/ --p3a-constellation-upload-url=https://collector.bsg.brave.com/` on the following build

```
Verified on `Vivo x70 Pro version 12` running `Bravemonoarmx64.apk_1.57.41`
```

I can see the metrics `brave.p3a.current_epoch` , `brave.p3a.current_pk`, `brave.p3a.next_epoch_time` in the local state file also the `p3a.logs_constellation_prep` is  shown in the brave://local-state file as expected. _**But the metrics `brave.p3a.approved_cert_fp` is NOT shown in the brave://local-state file**_ I have waited for the enough time (more than 15mins )

Example | Example | Example | Example | Example | Example
----------|-----------|-----------|----------|-----------|---------
![Screenshot_20230809_114232](https://github.com/brave/brave-browser/assets/38657976/2a335662-b279-43a1-b7d3-e8e282d51ff9) | ![Screenshot_20230809_122246](https://github.com/brave/brave-browser/assets/38657976/35c9d2ac-6e2a-4df5-a64c-8982f2e041e0) | ![Screenshot_20230809_122333](https://github.com/brave/brave-browser/assets/38657976/dafe0b65-915a-485b-a3f5-7765cc1c6d01) | ![Screenshot_20230809_122414](https://github.com/brave/brave-browser/assets/38657976/bcb291be-a68d-4739-91b2-045125d98756) | ![Screenshot_20230809_122536](https://github.com/brave/brave-browser/assets/38657976/0d2b5f62-3de0-4d9f-9900-c88a6b81fb08) | ![Screenshot_20230809_122923](https://github.com/brave/brave-browser/assets/38657976/a5317adc-7034-488a-8c5a-ee6c5414afdb)

Example | Example | Example
---------|-----------|---------
![Screenshot_20230809_123604](https://github.com/brave/brave-browser/assets/38657976/c9da3c50-99bf-4d9e-8816-5092a634d00c) | ![Screenshot_20230809_123617](https://github.com/brave/brave-browser/assets/38657976/a40f6db2-53cd-4dcd-bf49-9a1c501f91bb) | ![Screenshot_20230809_123628](https://github.com/brave/brave-browser/assets/38657976/84646e6d-e87a-48a9-8e30-d8835cc2703c)


Q1: The `current_epoch` value is `14` in Android but in Desktop the  `current_epoch` value is `0` is this expected?

**Comment by GeetaSarvadnya** [comment]
@DJAndries: Verifie the issue using the `star-randsrv.bsg.brave.com,` above https://github.com/brave/brave-browser/issues/30622#issuecomment-1671028697. 
I need clarification on few points which are listed below


Q1: The `current_epoch` value is `14` in Android but in Desktop the  `current_epoch` value is `0` is this expected?
Q 2: The metrics `brave.p3a.approved_cert_fp` is NOT shown in the brave://local-state file I have waited for the enough time (more than 15mins )

**Comment by DJAndries** [comment]
@GeetaSarvadnya 

Q1: Yes
Q2: Enclave attestation is temporarily disabled for all clients, so this is expected.

**Comment by GeetaSarvadnya** [comment]
As per the above comments, the issue is working as expected hence closing the issue.
