### ISSUE TITLE
Vertical tab bar appears in front of page content after exiting fullscreen

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#30629]
After entering and then exiting fullscreen, the page content will show up behind the vertical tab bar instead of next to it. This persists across all tabs in that window until toggling the vertical tab bar width.

https://github.com/brave/brave-browser/assets/22821309/717434a2-ada8-4c8f-964f-3301b5da8d62

Note that the effect is subtle with minimized tab bar  as shown here, but much more noticeable/problematic when expanded.

I am using [bspwm](https://github.com/baskerville/bspwm) as my window manager, if that is useful information.

**Comment by kjozwiak** [comment]
The above requires `1.56.18` or higher for `1.56.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave	1.56.18 Chromium: 115.0.5790.138 (Official Build) (64-bit) 
Revision	0567db0e7dcdfee5c109c167119ac2a92b9b3e1a-refs/branch-heads/5790_85@{#9}
OS	Linux
```
![enter and exit fullscreen](https://github.com/brave/brave-browser/assets/38657976/6e1c8e11-2bd5-41bd-815b-0e87f589b06b)

**Comment by kjozwiak** [comment]
@antonok-edm who originally reported the above also confirmed/verified that the issue has been resolved on the machine that was reproducing the above. I couldn't reproduce the original issue on my `PopOS 22.04 x64` VM so asked @antonok-edm if he could also verify/double check that it's been resolved.
