### ISSUE TITLE
Hide tab switcher button in tab overview mode

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#30621]
## Description 

After the latest `C114` bump we have a visual issue that needs to be fixed via `tab overview` as exampled below. The `tab counter` needs to be removed.

## Steps to reproduce 

   1. launch a version of brave that's using `114.0.5735.53`
   2. open the `tab overview` and notice that there's a blank `tab icon/count` in the right corner

## Actual result 

![Screenshot_20230526_135022](https://github.com/brave/brave-browser/assets/30602739/93dc2c07-bb2b-4cfe-86bd-07cf2206f216)

## Expected result

![Screenshot_20230526-145043](https://github.com/brave/brave-browser/assets/2602313/1045071e-1c49-4e3c-a840-ba3480be3bc3)

## Issue reproduces how often 

100% reproducible using the STR/Cases outlined above.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `No`
- Can you reproduce this issue with the current Play Store Beta version? `Yes. Introduced via 114.0.5735.53`
- Can you reproduce this issue with the current Play Store Nightly version? `Yes. Introduced via 114.0.5735.53`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Pixel 6` (Phone)
   - Android version: `Android 13` & `Android 14`
   
## Brave version

```
Brave | 1.52.112 Chromium: 114.0.5735.35 (Official Build) (32-bit)
--- | ---
Revision | 2295354895fa3652ae47b651481831484f16d1ff-refs/branch-heads/5735@{#713}
OS | Android 13; Build/UPB2.230407.014; 33; UpsideDownCake
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by kjozwiak** [comment]
@brave/qa-team we'll also need to check and ensure that the `tab overview` looks correct on both `mobile` & `tablet` for both `landscape` and `portrait` modes. Added `QA/Test-All-Platforms`.

**Comment by kjozwiak** [comment]
@brave/qa-team can find examples of the STR/Cases via https://github.com/brave/brave-core/pull/18640#issuecomment-1567454880 based off the information fromhttps://github.com/brave/brave-browser/issues/30621#issuecomment-1564848305.

The above requires `1.52.115` or higher for `1.52.x` verification 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 14` using the following build(s):

```
Brave | 1.52.115 Chromium: 114.0.5735.53 (Official Build) (64-bit)
--- | ---
Revision | c499d7ea22c8b2dba278465a5df7b86a8efa4e64-refs/branch-heads/5735@{#970}
OS | Android 13; Build/UPB2.230407.014; 33; UpsideDownCake
```

* ensured that the `tab overview` looks as expected as per https://github.com/brave/brave-browser/issues/30621#issue-1728047230
  * ensured that both `Portrait` & `Landscape` modes appear/work as expected
    * ensured that you can switch between the both views without any issues
  * ensured that you can move around tabs within the `tab overview` without any issues
  * ensured that you can group tabs without any issues
  * ensured that you can open new tabs via `+` without any issues
  * ensured that you can access the `Hamburger Menu` while in `Portrait` mode
  * ensured that the above checks apply to both `Normal` & `Private` tabs

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|----------------|----------------|----------------
![Screenshot_20230530-130838](https://github.com/brave/brave-browser/assets/2602313/e3d56cd2-ecf1-4b30-83a5-4154c91bf969) | ![Screenshot_20230530-130849](https://github.com/brave/brave-browser/assets/2602313/13e8b2da-6b15-4f57-bf6e-eaabbc71ba41) | ![Screenshot_20230530-130915](https://github.com/brave/brave-browser/assets/2602313/db36ff0c-8093-4b5b-bf8f-f6d3fcef76c7) | ![Screenshot_20230530-130924](https://github.com/brave/brave-browser/assets/2602313/1d592f8c-6a98-4809-a49d-c0402e83f900) | ![Screenshot_20230530-130948](https://github.com/brave/brave-browser/assets/2602313/912d8b18-117c-4538-9e93-bb99e173c7ff) | ![Screenshot_20230530-130956](https://github.com/brave/brave-browser/assets/2602313/3d25e452-9a1a-4c18-99ce-93954e4086f4)
