### ISSUE TITLE
Add P3A metrics for Android Privacy Hub report

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#30623]
Add two monthly metrics for Privacy Hub reporting on Android.

Do you have privacy report enabled? (only reported for users that have the feature enabled)
`Brave.PrivacyHub.IsEnabled`

1) Yes

If you opened privacy report in the past 30 days, how many times did you open it?
`Brave.PrivacyHub.Views`

0) 1
1) 2-10
2) 11-20
3) 21+

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave | 1.54.76 Chromium: 115.0.5790.32 (Official Build) beta (64-bit)
-- | --
Revision | f9b78cf410ecd5b372310ef25a12ef456c77d90f-refs/branch-heads/5790@{#724}
OS | Windows 10 Version 22H2 (Build 19045.3086)

```

**Comment by GeetaSarvadnya** [comment]
@DJAndries Could you provide me the steps to trigger the response value `2` ? I have tried multiple ways I am unabl eto see the response value 2.

**Comment by DJAndries** [comment]
I was able to trigger value 2 for `Brave.PrivacyHub.Views` by opening the privacy report 11 times.

**Comment by GeetaSarvadnya** [comment]
@DJAndries I assume opening the `Privacy report` is nothing but opening NTP 11 times? if not correct me, I did open the NTP 11 times after opening few websites but I don't see the response value `2`

**Comment by DJAndries** [comment]
You must tap on the stats on the NTP to open the privacy report.

**Comment by GeetaSarvadnya** [comment]
Now I can see the correct values. Thanks @DJAndries .
