### ISSUE TITLE
rendering issue with brave (suddenly the brave screen goes like broken on F38).

### ISSUE THREAD

**Issue by Abdelkader-gnichi** [brave/brave-browser#30639]
## Description 

rendering issue with brave (suddenly the brave screen goes like broken on F38).i use brave on F38 and suddenly the brave interface(screen) goes like indicated in the 3 pics.

i don't do anything special today with my system expect that i upgrade it but the problem appears after hours since i make the sys upgrade, after the upgrade i use brave a least for 2 hours.

after the problem occurred i try to reboot the system hoping that the issue will be fixed, but it still exists then i try to remove brave and reinstall it and see what will happen also nothing happened brave still unusable.
## Steps to Reproduce

   1. useing brave normally
   2. upgrade the system while using brave in the same time 
   3. there is no an problem after the upgrade for a couple of hours (2 hours)
   4. suddenly the i got that issue with rendering the interface (the issue showed in 3 pictures below)
   5. i try to reboot the system thinking that the pb will gone, but unfortunately the problem sill there.
   6. also i try to remove and reinstall brave,but nothing happened .

## Expected result:
![Screenshot from 2023-05-27 18-48-31](https://github.com/brave/brave-browser/assets/64486451/7329860c-7da6-4fa9-bd13-b27f395354ec)
![Screenshot from 2023-05-27 18-48-50](https://github.com/brave/brave-browser/assets/64486451/32f5428a-bed8-47a1-9f6c-de6966f0ac66)
![Screenshot from 2023-05-27 18-49-09](https://github.com/brave/brave-browser/assets/64486451/14428201-b8a9-4d58-8adc-ea7fd65e2a50)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by Sa-Ja-Di** [comment]
Try to deactivate hardware acceleration, considering how many issues this one makes in Chromium based browsers lately, it is the best choice to do, browser runs here quite stable and still rather fast with hardware acceleration disabled.

Perhaps it helps in your case too. You find that setting in the option menu.

**Comment by Milralze** [comment]
The settings of Brave open in page inside the Brave Browser, so you can't change the settings with this problem... I have the same problem, now I going back the firefox.

**Comment by webvoyant** [comment]
I had the same issue on Linux Mint 21.1 with Brave version 1.51.118. The browser is completely unusable on that version for me.

I downgraded to 1.50.125 and it works fine.

**Comment by Lavatera** [comment]
Same here on multiple laptops

**Comment by Abdelkader-gnichi** [comment]
@Lavatera just make a downgrade and it will work, i just downgrade to 1.51.14 version a couple minutes ago .

**Comment by Lavatera** [comment]
Thanks, will do but it isn't a real fix... Hope the problem will be solved in the next few days

**Comment by Lavatera** [comment]
When I install a new brave through the snap store it works great alongside of my old one

**Comment by Abdelkader-gnichi** [comment]
@Lavatera see [This](https://www.reddit.com/r/Fedora/comments/139ghan/glitch_in_google_chrome_on_fedora_38_restarted/?utm_source=share&utm_medium=ios_app&utm_name=ioscss&utm_content=1&utm_term=1) i think that it is the same issue.

**Comment by Sa-Ja-Di** [comment]
> The settings of Brave open in page inside the Brave Browser, so you can't change the settings with this problem... I have the same problem, now I going back the firefox.

@Milralze You can add to the shortcut of Brave the following:
--disable-gpu

This has the same effect, hardware acceleration disabled. No need to leave for Firefox or downgrade that way :)

**Comment by webvoyant** [comment]
I upgraded back to 1.51.118 to test emptying the GPUCache folder and that works. Thanks @Sa-Ja-Di !

If you're using the default profile, it's at:

`~/.config/BraveSoftware/Brave-Browser/Default/GPUCache/`

Then just restart the browser.

**Comment by Abdelkader-gnichi** [comment]
> I upgraded back to 1.51.118 to test emptying the GPUCache folder and that works. Thanks @Sa-Ja-Di !
> 
> If you're using the default profile, it's at:
> 
> `~/.config/BraveSoftware/Brave-Browser/Default/GPUCache/`
> 
> Then just restart the browser.

this is the solution thanks for all i will close this issue.
