### ISSUE TITLE
My Dad Said ''Brave Search Results Not Great,''.

### ISSUE THREAD

**Issue by Good-Vibes-Chat-N-Chew-UK** [brave/brave-browser#30633]
Hi, I'm 7 Years Old And I'm Using Github For The First Time. I'm New To Coding So I Love The Brave Browser But My Dad Thinks That Its Search Results Are Not Great Can You Please Fix Them? Hope You're Working On It.

Bye 👋

Ezel Kalam From UK 

❤️💕😍😊

**Comment by Good-Vibes-Chat-N-Chew-UK** [comment]
Also, You Could Add A Option In The Brave Browser Settings For Fallback Mixing In Search And The Options Can Be Google And Bing. ❤️💕😍😊

Bye 👋

Ezel Kalam From UK

**Comment by xBZZZZ** [comment]
search results are [search engine's](https://search.brave.com/) fault, not browser's
I think https://github.com/brave/brave-browser is **wrong** place to post this

**Comment by Good-Vibes-Chat-N-Chew-UK** [comment]
Ok, xBZZZZ. I'll close this then.
