### ISSUE TITLE
Uninstaller is unsigned

### ISSUE THREAD

**Issue by da2x** [brave/brave-browser#3063]
## Description 

The uninstaller is unsigned.

## Steps to Reproduce

   1. Install Brave on Windows
   2. Uninstall Brave again

## Actual result:

Triggers uninstaller with an UAC dialog. Dialog warns that the uninstaller is unsigned and from an unknown developer.

## Expected result:
A signed uninstaller just like the installer and the main program.

## Reproduces how often: 

Every time.

## Brave version (brave://version info)

Brave | 0.60.16 Chromium: 72.0.3626.64 (Official Build) dev (64-bit)
Revision | eaa9668e80ce5405e7f1902579558ea725c06ca1-refs/branch-heads/3626@{#708}
OS | Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Stable and developer.

### Additional Information

Clearly an oversight in the signing process on he build-system.

**Comment by jumde** [comment]
@da2x - I'm not able to repro this on Win 10 with the latest release (0.66.101), could you confirm if this is fixed for you as well? cc: @mbacchi

**Comment by bsclifton** [comment]
Closing - let's re-open if the issue still exists
