### ISSUE TITLE
[Android] Implement Manage Brave Ads

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#30638]
Android version of: https://github.com/brave/brave-browser/issues/30637

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.58.114`

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Samsung Galaxy version 12` running `Bravemonoarm64.apk_1.58.121`

<details>
<summary>New profile test case - </summary>

1. Clean profile `1.58.x`
3. Enable rewards
4. Confirmed that the `Manage Brave Ads` section is shown in the brave://rewards page
5. Confirmed that `New tab page ads` and `Notification ads` switches are enabled by default
6. Confirmed that `Max 10 ads per hour` option is selected by default
7. Confirmed that tooltip next to Brave News ads says that `Brave News is disabled` and digit on the right is grayed out
8. Confirmed that Brave News ads tooltip says that `Brave News Ads cannot be independently disabled` and confirmed that the digit is no longer grayed out when brave news is enabled and the counter is working.
9. Confirmed that `New tab page ads` and `Notification ads` are served to the users when the swicthes are enabled
10. Confirmed that brave news inline content ads are served to the user when Brave news is enabled
11. Confirmed that users are rewarded for viewing brave news `inline content ads`, `New tab page ads` and `Notification ads`
12. Confirmed that counter on each ad types is shown correctly after viewing ads
13. Verified the toggle ON/OFF new tab page ads and confirmed that this works by checking the New Tab Page for New Tab Page ads, and that the ads viewed counter is working for this ad unit
14. Go into “Settings->New tab page->Show Sponsored Images” via 3 dot menu, and toggle ON/OFF sponsored images settings and then look in brave://rewards Manage Brave Ads and onfirmed the new tab page ads toggle updates its state accordingly.
15. Toggle ON/OFF new tab page ads via brave://rewards Manage Brave Ads, and confirmed that the toggle in “Settings->New tab page->Show Sponsored Images” updates its state accordingly.
16. Exception case: Make sure New Tab Page ads are ON inside Customize Dashboard. Then, turn off background images completely. 
a. New Tab Page ads should still be on in Manage Brave Ads
b. Turn off New Tab Page ads in Manage Brave Ads
c. Enable background images in Customize Dashboard
d. Check that the New Tab Page ads/sponsored images toggle in Customize Dashboard is OFF (matches Manage Brave Ads state)
e. Then toggle New Tab Page ads on in Customize Dashboard, and check if state updates and matches in Manage Brave Ads
18. Connect a custodian, and then check that the blue notice telling users to connect to a custodian (“Ready to start earning?”) no longer appears, and that things still appear to be working properly.


Example | Example | Example | Example | Example | Example | Example
----------|----------|-----------|----------|-----------|------------|----------
![Screenshot_20230907-201142_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/dbfdeb7d-07b1-43cb-b4be-66d3cd1218dc) | ![Screenshot_20230907-201357_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/ea86b02a-6c09-4bf7-adb4-bd74919d5ae2) | ![Screenshot_20230907-203630_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/6bb09263-7609-4bc8-9caf-9bc145f6b93f) | ![Screenshot_20230907-210100_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/72af3d90-fb7d-4f37-b901-6b2343af36ee) | ![Screenshot_20230907-210148_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/6e65429c-2454-415d-a860-312578938805) | ![Screenshot_20230907-210253_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/5681ff2e-65da-4124-836d-0cd0b829471c) | ![Screenshot_20230907-210504_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/d6e1fb15-30d9-40d5-a631-e30d23b1bcef)

**Step 14**

Example | Example
----------|---------
![Screenshot_20230908-170019_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/b78db2af-9788-40d7-8b09-2b8c910f4a01) | ![Screenshot_20230908-170033_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/d4200cf9-af6a-4573-bb95-95360b178195)

**Step 15**

Example | Example
----------|---------
![Screenshot_20230908-170033_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/857ff9a7-07a4-47d7-827c-fa1dffda2269) | ![Screenshot_20230908-170019_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/e2294c23-896e-4833-90f4-8c348f1dfbea)

**Step 16**

Example | Example | Example | Example | Example | Example
----------|-----------|----------|-----------|-----------|----------
![Screenshot_20230908-170539_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/23db4806-4f8a-40d7-95b8-a794607d5005) | ![Screenshot_20230908-170613_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/dad5741a-01e3-48b0-a665-65c2bfd0195a) | ![Screenshot_20230908-170620_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/ff8fff1b-8606-4524-9715-06ae0639f45d) | ![Screenshot_20230908-170650_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/03c15409-77c5-44e2-bca6-20498b4c0430) | ![Screenshot_20230908-170726_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/af093e4b-e782-4b32-ad63-a29c611604a9) | ![Screenshot_20230908-170730_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/77ae47fe-3deb-4177-9e24-b6315545985b)

**Step 17**

Example | Example
----------|---------
![Screenshot_20230908-172049_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/a92be83f-537f-40f0-aa76-d2c61d761871) | ![Screenshot_20230908-171953_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/fd7d7027-f040-4bf8-bb9b-283ca2def86b)


**_Notification ads logs_**

```
2023-09-07 20:36:19.098 8387-8387/? V/chromium: [VERBOSE1:notification_ad_handler.cc(185)] Served notification ad:
      placementId: 0a8274c3-e269-418e-9a8b-50d6c4e03886
      creativeInstanceId: 98bd3e17-2733-4365-89d3-7baae4bb571b
      creativeSetId: 0c5dbff2-ae64-4997-97ab-eae435fee259
      campaignId: 770bd7ed-0ba8-48d8-8dfb-5f86f6d3e005
      advertiserId: 86025555-2064-4671-b1b6-765c64cf023c
      segment: untargeted
      title: Download Brave on your desktop
      body: Watch YouTube videos ad-free on your desktop!
      targetUrl: https://brave.com/?ref=YMS691/
2023-09-07 20:36:19.143 8387-8387/? V/chromium: [VERBOSE1:notification_ad_serving.cc(161)] Maybe serve notification ad in 0 hours, 6 minutes, 0 seconds at 20:42:19.111
2023-09-07 20:36:19.148 8387-8387/? V/chromium: [VERBOSE3:notification_ad_handler.cc(196)] Served notification ad with placement id 0a8274c3-e269-418e-9a8b-50d6c4e03886 and creative instance id 98bd3e17-2733-4365-89d3-7baae4bb571b
2023-09-07 20:36:19.152 8387-8387/? V/chromium: [VERBOSE3:notification_ad_handler.cc(205)] Viewed notification ad with placement id 0a8274c3-e269-418e-9a8b-50d6c4e03886 and creative instance id 98bd3e17-2733-4365-89d3-7baae4bb571b
```
```
2023-09-07 20:36:19.158 8387-8387/? V/chromium: [VERBOSE3:account.cc(242)] Successfully processed deposit for ad_notification with creative instance id 98bd3e17-2733-4365-89d3-7baae4bb571b and view valued at 0.01
```

**_New tab page ads logs_**

```
2023-09-07 20:27:27.458 32615-32615/? V/chromium: [VERBOSE1:new_tab_page_ad_handler.cc(166)] Served new tab page ad:
      placementId: 6fb2bdfc-5ef2-4674-bc34-14742df54eef
      creativeInstanceId: 1c531704-1887-448d-b603-f2e8ba3bce52
      creativeSetId: b0096651-d3ce-4de0-968a-725c65cdbfc7
      campaignId: 9c25e7a1-1a8e-4821-94c1-ef4c11f58618
      advertiserId: 216c5e8c-434d-4c72-a9c5-3a11343dde48
      segment: untargeted
      companyName: Brave VPN
      imageUrl: https://mobile-data.s3.brave.com/assets/ntp-si/183f3cfe-9479-4c5e-9ea5-68582510844c.png
      alt: Brave VPN - Cover all your devices with 1 VPN, across Android iOS & desktop. Right from the browser - Get Brave VPN
      targetUrl: https://brave.com/firewall-vpn/?mtm_source=brave-browser&mtm_medium=brave-ntp&mtm_campaign=brave-vpn&mtm_content=%%CREATIVE_INSTANCE%%&mtm_date=20230907
      wallpaper:
        imageUrl: https://mobile-data.s3.brave.com/assets/ntp-si/46299a16-c025-4383-b8db-8189efa697ff.jpg
        focalPoint:
          x: 1119
          y: 720
2023-09-07 20:27:27.465 32615-32615/? V/chromium: [VERBOSE3:new_tab_page_ad_handler.cc(173)] Served new tab page ad with placement id 6fb2bdfc-5ef2-4674-bc34-14742df54eef and creative instance id 1c531704-1887-448d-b603-f2e8ba3bce52
2023-09-07 20:27:27.489 10266-11479/? W/chromium: [WARNING:ev_root_ca_metadata.cc(118)] Not implemented
```
```
2023-09-07 20:27:27.721 32615-32615/? V/chromium: [VERBOSE3:account.cc(242)] Successfully processed deposit for new_tab_page_ad with creative instance id 1c531704-1887-448d-b603-f2e8ba3bce52 and view valued at 0.005
```

**_Inline content ads logs_**

```
2023-09-07 21:16:19.375 18397-18397/? V/chromium: [VERBOSE1:inline_content_ad_handler.cc(130)] Served inline content ad:
      placementId: 5256b084-2096-4c92-8ce0-ef5a983dae38
      creativeInstanceId: 877231dc-1675-43bb-9757-f3369b0ddcd8
      creativeSetId: df061ee5-c016-4ad8-b6d7-98b2218e6e92
      campaignId: 10ee7a4b-cfb5-4501-b6d4-59f7d8ca23db
      advertiserId: 6a231afd-670a-49dc-915f-8dad52266dcb
      segment: untargeted
      title: Explore multichain Web3. Select Wallet from the browser settings menu to get started!
      description: Brave
      imageUrl: https://pcdn.brave.com/brave-news-ads/8af2a80b-d368-4ff7-8bfe-8ea24a37edeb.jpg.pad
      dimensions: 900x750
      ctaText: Learn More
      targetUrl: https://brave.com/wallet/?brave-creative-id=877231dc-1675-43bb-9757-f3369b0ddcd8&source=news
2023-09-07 21:16:19.379 18397-18397/? V/chromium: [VERBOSE3:inline_content_ad_handler.cc(137)] Served inline content ad with placement id 5256b084-2096-4c92-8ce0-ef5a983dae38 and creative instance id 877231dc-1675-43bb-9757-f3369b0ddcd8
```
```
2023-09-07 21:16:22.349 18397-18397/? V/chromium: [VERBOSE3:account.cc(242)] Successfully processed deposit for inline_content_ad with creative instance id 877231dc-1675-43bb-9757-f3369b0ddcd8 and view valued at 0.025
```

</details>

<details>
<summary>Upgrade profile case (view counts and ad settings) - </summary>

Note: Main things to worry about are turning on ads for someone who had them off in previous version.

1. Create profile prior to existence of Manage Brave Ads (where it still has Brave Private Ads section).
15. Enable Rewards, and see some New Tab Page ads and some push notification ads.
17. Disable New Tab Page ads via `Settings->New tab page`
19. Set max ads frequency to 0 in Brave Private Ads (this corresponds to push notification ads)
20. Upgrade to version with Manage Brave Ads and make sure Manage Brave Ads is there.
21. Check that Notification Ads are toggled OFF in Manage Brave Ads, given that ads frequency was set to 0 in step 3. (There is no more “ads frequency = 0 / none” option in the notification ads dropdown) ---> FAILED, logged follow up issue https://github.com/brave/brave-browser/issues/32651.
22. Check that New Tab Page ads are OFF, given that they were turned off in step 2. 
23. Check that breakdown of ad views per ad unit in Manage Brave Ads makes sense with how many ads you saw in step 2. 

**`1.57.x` ** | **`1.57.x `** | **`1.57.x `** 
-------------|-------------|-----------
![Screenshot_20230908-140933_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/039d0f36-6ce4-4697-a3cf-7e5de033de28) | ![Screenshot_20230908-141226_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/38388b0c-1e9b-4947-a3b1-b4d6534dbb58) | ![Screenshot_20230908-141237_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/f4f20113-4f69-4f60-98ca-01e269701b8b)


1.58.x  | 1.58.x 
-------|--------
![Screenshot_20230908-141331_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/ee265d78-729c-4095-81b1-e7300831f8ad) | ![Screenshot_20230908-141507_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/75a479a9-d88b-4149-b371-53fd5a0de5d5) 


24. Re-enable New Tab Page ads and notification ads via toggles in Manage Brave Ads, and make sure that everything works, and that the New Tab Page ads toggle in Manage Brave Ads corresponds with the toggle in Customize Dashboard.
-  Confirmed that new tab page ads are served in an upgraded profile after enabling the new tab page ads switch via `Manage Brave Ads` page
- Confirmed that notification ads are served in an upgraded profile after changing "None" to a different value in the list:

```
2023-09-08 14:18:29.780 9485-9485/? V/chromium: [VERBOSE1:notification_ad_serving.cc(136)] Maximum notification ads per hour changed to 10
```

1.58.x  | 1.58.x | 1.58.x
-------|-------|-------
![Screenshot_20230908-141531_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/ef35df27-0ce2-415b-81a6-c873807a6c1a) | ![Screenshot_20230908-141540_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/0cfa4dce-6be0-458e-a9aa-abbfe87df96f) | ![Screenshot_20230908-141559_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/882cfbae-0a7b-40de-a545-3e1efc0e7eeb)


</details>

<details>
<summary>Reset Rewards case - </summary>

1. Create new profile and go to brave://rewards > Manage Brave Ads
2. Toggle off New tab page ads and Notification ads in Manage Brave Ads
3. Reset Rewards profile
4. Ensure that the new Rewards profile has New tab page ads OFF, and notification ads ON

Example | Example | Example | Example
----------|-----------|-----------|----------
![Screenshot_20230908-164540_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/cdff5366-8364-4f67-aba5-8372eac63316) | ![Screenshot_20230908-164549_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/4d5e1dbb-f001-4c51-a47b-675690b344b3) | ![Screenshot_20230908-164605_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/4051a527-f96d-4162-9cf4-20a4238f5031) | ![Screenshot_20230908-164610_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/179a9184-d80f-484a-ae9d-aaee847f15fe) | ![Screenshot_20230908-164624_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/8ec3cf0b-5194-42f1-b23d-6cf9400798a2)


</details>

<details>
<summary>New profile in no custodian region - </summary>

1. Create new profile and set Rewards region to somewhere with no custodial support (like Antarctica)
2. Go to brave://rewards for Manage Brave Ads and make sure that it shows the “There is no available custodian in your region” notice in the Manage Brave Ads section. 

Example | Example
----------|--------
![Screenshot_20230908-165142_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/d35cc653-0030-4c5c-9117-9bf681b2bc23) | ![Screenshot_20230908-165154_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/074413c1-e392-448b-a903-cf989cc667c9)


</details>

**Comment by Uni-verse** [comment]
In progress on Pixel 2 XL running Android 8.1.0

**Comment by btlechowski** [comment]
Verification passed on Brave v1.58.121 on Lenovo TB-8506FS (Android 11.0)

Verified general regression ads testing

### Notification ads
<details>


</details>

### NTP SI
<details>


</details>


### Brave News/Inline ads
<details>


</details>


### Unblinded tokens
<details>


</details>



### Payment tokens redemption
<details>


</details>
