### ISSUE TITLE
Failed to create send/swap transactions on Arbitrum/Polygon

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#30641]
🐛 Failed to create send/swap transactions originating from the wallet. Steps to reproduce below. 👇 

1. Add Arbitrum network.
2. Go to Send, and create a transaction.
3. Nothing happens. The console logs show the following error:
    ```
    Sending unapproved transaction failed:
      from=0xa92D461a9a988A7f11ec285d39783A637Fdd6ba4
      err=Failed to get the gas fees for EIP-1559 transaction
    ```

⚠️ **Update:** Polygon is also broken

## Reproduces how often: 

Every time

## Version/Channel Information:

Reproduces on 1.52+. Added the P1 label since 1.52 is due for release on May 31, 2023.

**Comment by kjozwiak** [comment]
The above requires `1.52.116` or higher for `1.52.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.52.116 Chromium: 114.0.5735.58 (Official Build) (64-bit)
-- | --
Revision | `ef012197ab4bc867d7b1dd80a001d0be7da8a714-refs/branch-heads/5735_52@{#7}`
OS | Windows 11 Version 22H2 (Build 22621.1778)

- Verified steps from issue description
- Verified able to perform Send/Swap transactions on both Polygon and Arbitrum One

https://github.com/brave/brave-browser/assets/17010094/aa0a4df8-df65-47bd-9390-2612df4e7e02
