### ISSUE TITLE
Shields panel is not translated

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#3064]
Follow up from https://github.com/brave/brave-browser/issues/2831

## Steps to Reproduce

   1. Change Brave language to `French`
   2. Open Brave Shields

## Actual result:

Brave shields panel is not translated
![image](https://user-images.githubusercontent.com/34715963/51644659-415ead00-1f71-11e9-8bb5-ad87d0dc8b43.png)

## Expected result:
Brave shields panel is translated to French

## Reproduces how often: 

always

## Brave version (brave://version info)

Brave | 0.59.28 Chromium: 72.0.3626.64 (Official Build) beta(64-bit)
-- | --
Revision | eaa9668e80ce5405e7f1902579558ea725c06ca1-refs/branch-heads/3626@{#708}
OS | Windows

cc @brave/legacy_qa @bbondy

**Comment by kjozwiak** [comment]
@btlechowski do you know if this affects other locales or just French?

**Comment by btlechowski** [comment]
@kjozwiak reproduced on following locales: Polish, Czech, German, Dutch, Danish, Finnish, Italian, Japanese, Korean, Norwegian, Russian, Spanish.

Sanity checked all above locales for any missing strings. 
Found: https://github.com/brave/brave-browser/issues/3094 https://github.com/brave/brave-browser/issues/3095

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.60.44 Chromium: 72.0.3626.109 (Official Build) (64-bit)
-- | --
Revision | fae8db7ab9280fa6704a59980263c804f809ebd5-refs/branch-heads/3626@{#857}
OS | Windows 7

Verified languages:
Arabic, Bulgarian, Chinese(Traditional), Croatian, Czech, Danish, Dutch, Finish, French, German, Greek, Hebrew, Hungarian, Italian, Japanese, Korean, Lithuanian, Polish, Portuguese, Russian, Slovak, Slovenian, Spanish, Turkish, Vietnamese

Norwegian not translated. Logged: https://github.com/brave/brave-browser/issues/3425

![image](https://user-images.githubusercontent.com/34715963/53059498-3d15a900-34b7-11e9-9dda-0ecfa7296d24.png)
![image](https://user-images.githubusercontent.com/34715963/53059851-aea22700-34b8-11e9-8e2a-4071e1fc5f1f.png)
