### ISSUE TITLE
1.52.113 segmentation fault on start when running on Linux

### ISSUE THREAD

**Issue by szymonpk** [brave/brave-browser#30648]
## Description

After upgrading from 1.51.118 to 1.52.113 (stable), browser crashes on start with "Segmentation fault" error in console.

## Steps to Reproduce

   1. Upgrade to 1.52.113 using https://github.com/brave/brave-browser/releases/download/v1.52.113/brave-browser-1.52.113-linux-amd64.zip
   2. Start the browser

## Actual result:

```
Gtk-Message: 05:51:02.349: Failed to load module "appmenu-gtk-module"
[12591:12591:0529/055102.388287:ERROR:chrome_browser_cloud_management_controller.cc(162)] Cloud management controller initialization aborted as CBCM is not enabled.
[0529/055102.418312:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0529/055102.418378:ERROR:elf_dynamic_array_reader.h(64)] tag not found
Segmentation fault
```

## Expected result:

Running browser.

## Reproduces how often: 

Always

## Desktop Brave version:

I cannot go to 'version' page on 1.52.113, I am running Linux, Xorg 21.1.8.

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? I do not know
- Can you reproduce this issue with the nightly channel?  I do know know

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Latest Chrome (113.0.5672.126) works fine

## Miscellaneous Information:

I have tried clean profile, it does not help. It crashes before profile page pick up screen, so it probably does not matter.

**Comment by szymonpk** [comment]
I have found reference to [something similar](https://techcommunity.microsoft.com/t5/discussions/microsoft-edge-crashes-on-linux-with-work-profile/m-p/3724709) reported by Edge users.

**Comment by szymonpk** [comment]
I had to wipe the whole `$HOME/.config/BraveSoftware`, and start from scratch :( Now it works.

**Comment by chaitanya-lakkundi** [comment]
🎉 Hey everyone,

Just wanted to share a workaround. 
**Setup**: Brave 1.52.122 Chrome 114.0.5735.110 on Kubuntu 22.04.1

Here are the steps I followed:

1. Renamed my previous BraveSoftware directory.
`mv $HOME/.config/BraveSoftware $HOME/.config/BraveSoftware_old`
3. Launched Brave and created new corresponding work profiles.
4. Closed Brave.
5. Deleted the old Default profile and all other profiles.
`rm $HOME/.config/BraveSoftware/Brave-Browser/Default`
`rm $HOME/.config/BraveSoftware_old/Brave-Browser/Profile*`
7. Copied the old Default and other profiles to the new BraveSoftware directory.
`cp -r ~/.config/BraveSoftware_old/Brave-Browser/Default/ ~/.config/BraveSoftware/Brave-Browser/`
`cp -r ~/.config/BraveSoftware_old/Brave-Browser/Profile* ~/.config/BraveSoftware/Brave-Browser/`
9. Launched Brave again, and my profiles were restored! 🚀

I hope this solution works for you too!
