### ISSUE TITLE
Unable to sign transactions on custom EVM networks

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#30642]
🐛 Failed to sign EVM dapp requests on Arbitrum (ex, matcha.xyz). Steps to reproduce below: 👇 
1. Add Arbitrum network and switch to it.
2. Go to matcha.xyz, and create an Arbitrum swap.
3. The panel pops up without any transaction visible to sign.
4. Going to Activity tab, with "All networks" dropdown option selected, no unapproved transaction is visible.
5. **However**, if the "Arbitrum" network is selected in the dropdown, it is visible.

The above implies that there's something wrong with the code that handles reading from transaction prefs. Likely related to https://github.com/brave/brave-core/pull/17986.

**⚠️ Please note the following:**
* The bug affects all custom networks, since I also reproduced it on zkSync Era during local tests (but **NOT** related to https://github.com/brave/brave-browser/issues/30473).
* Another similar bug on Arbitrum, but doesn't seem related: https://github.com/brave/brave-browser/issues/30641

## Reproduces how often: 

Every time

## Version/Channel Information:

Reproduces on 1.52+. Added the P1 label since 1.52 is due for release on May 31, 2023.

**Comment by kjozwiak** [comment]
The above requires `1.52.115` or higher for `1.52.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.52.116 Chromium: 114.0.5735.58 (Official Build) (64-bit)
-- | --
Revision | `ef012197ab4bc867d7b1dd80a001d0be7da8a714-refs/branch-heads/5735_52@{#7}`
OS | Windows 11 Version 22H2 (Build 22621.1778)

- Verified steps from issue description and [brave/brave-core#18651](https://github.com/brave/brave-core/pull/18651)
- Verified able to filter submitted and unsubmitted transaction in activity tab only once but then after encountered [#30703](https://github.com/brave/brave-browser/issues/30703)

**Comment by srirambv** [comment]
Android and iOS doesn't require any checks as the fix is on backend and affected all clients
