### ISSUE TITLE
Sometimes pinned tabs jump to the bottom of the vertical tabs list

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#30646]
## Description 
I don't have exact steps to reproduce this, but this is the result:
![image](https://github.com/brave/brave-browser/assets/7678024/a8934eed-1a14-4444-8a88-3f7431abb702)

cc @sangwoo108

**Comment by sangwoo108** [comment]
I think the steps-to-reproduce is something like

* when we have a tab group containing multiple tabs and the group is expanded.
* Activate the previous tab with keyboard shortcut until scroll state gets weird.

**Comment by fallaciousreasoning** [comment]
I think last time I triggered it was by clicking on a pinned tab

**Comment by kjozwiak** [comment]
The above requires `1.56.18` or higher for `1.56.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave	1.56.18 Chromium: 115.0.5790.138 (Official Build) (64-bit) 
Revision	0567db0e7dcdfee5c109c167119ac2a92b9b3e1a-refs/branch-heads/5790_85@{#9}
OS	Linux
```

Using the same STR/Cases mentioned above, ensured that the issue isn't occurring when switching between different tabs using `1.56.18 Chromium: 115.0.5790.138`.
![image](https://github.com/brave/brave-browser/assets/38657976/24dc6f95-e202-42f0-93d4-206d7b9cca04)
