### ISSUE TITLE
Fallback from Wireguard to IKEv2

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#30666]
Fallback to IKEv2 protocol If we find problems when working through Wireguard. Initial implementation will check if Wireguard service crashes 3 times in sequence and asking user to fallback to IKEv2. 

~In order to avoid browser restart we might need to move the feature flag to enable Wireguard-based vpn service to settings page preference.~ The connection service now doesnt support hot reload.

## Test Plan:

- case 1:
   - Install browser to program files
   - Enable wireguard experiment
   - Remove tunnel.dll or wireguard.dll and try to connect, after 3-4 attempts the browser should show the fallback dialog
 - case 2:
   - Install browser to program files
   - Enable wireguard experiment
   - Connect to VPN
   - Kill brave_vpn_wireguard_service.exe from Task Manager 
   - Repeat last 2 steps few times and you should see the fallback dialog.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.58.100 Chromium: 116.0.5845.114 (Official Build) beta (64-bit)
-- | --
Revision | a8c0058265009a1858c4502b9ba413671fbb61e1
OS | Windows 10 Version 22H2 (Build 19045.3324)
```

## Shared Steps:
<details>


</details>

## Case 1
<details>

</details>


## Case 2
<details>

</details>

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using 
```
Brave | 1.58.100 Chromium: 116.0.5845.114 (Official Build) beta (64-bit)
-- | --
Revision | a8c0058265009a1858c4502b9ba413671fbb61e1
OS | Windows 11 Version 22H2 (Build 22621.2134)
```

Verified with following pre-requisites:  
<details>

- Company Wireguard is in inactive status
- removed any previous Brave VPNs entries (i.e. BraveVPNNightly. BraveVPN etc)

<img width="512" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/ddf6ce91-fd03-4351-b8f4-4e58c9373b2e">
</details>
Testcase 1:  Fallback to IKEv2 protocol from `Wireguard` by removing `tunnel.dll` or `wireguard.dll`

#### Case 1:  Remove `tunnel.dll` before connecting VPN to fallback from `Wireguard to IKV2`
<details>

1. Installed 1.58.100
2. launched Brave
3. open `brave://flags` in a new tab and enabled **[#brave-vpn-wireguard](chrome://flags/#brave-vpn-wireguard)**
4. clicked Relaunch 
5. opened **"C:\Program Files\BraveSoftware\Brave-Browser-Beta\Application\116.1.58.100"**
6. deleted `tunnel.dll` from `BraveVpnWireguardService`  
7. purchased, configured VPN 
8. clicked `Refresh Brave VPN` button (5 times)
9. enabled VPN in the VPN panel
10. confirmed fallback from `Wireguard to IKV2` dialog is shown
11. clicked `Restart Browser` on the dialog
12. Brave relaunched successfully
13. connected to VPN via VPN panel
14. confirmed `#brave-vpn-wireguard` is disabled in the `brave://flags`
15. opened OS Network settings
16. confirmed successfully connected to VPN via IKEv2

step 3 | step 5 | step 6 | step 7 | step 8 | step 9 | step 10-11 | step 13 | step 13a | step 14 | step 15| step 16
----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ------
<img width="643" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/3e577470-73e7-478a-a530-27888c364150">|<img width="610" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/1fcd3cdd-707d-4e94-b3c5-dc46ed637134">|<img width="608" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/ffde6d3f-ac2f-4968-b1b4-86be2dd7f494">|<img width="971" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/3a38f8ff-5118-4780-8539-cf15736aea0f">|<img width="951" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/58318301-aa0e-4335-ba9d-39cf113cac3a">|<img width="956" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/7e3e2b88-e8ef-47a7-be4c-54fe6fe875bf">|<img width="958" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/8429467e-46af-4d5a-a937-f9cab57fefa3">|<img width="955" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/45d6d07b-12bb-4a11-bb68-3e3811b542ff">|<img width="957" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/8a85fa98-299c-45a3-aa8d-f904999ce6dc">|<img width="645" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/f657015c-b2df-4607-97de-b9f9d3372526">|<img width="380" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/f1067df1-2ed8-4d4d-8491-b102091f040d">|<img width="380" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/afa1900a-37a6-4359-8e68-4af62e43cd36">

Step 8 (iterations)

 iteration 2a| loading | iteration 3a| loading | iteration 4a| loading| iteration 5a | loading
 ----- | ----- | ----- | ----- | ------ | ----- | ------ | ----- 
<img width="955" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/42b11049-d34c-4807-a1c0-52831bfbd9c2">|<img width="959" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/46082494-1042-441a-90e3-31db16d32c6a">|<img width="956" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/0d42e58c-8689-42e0-bd74-88ec7584605b">|<img width="957" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/03ae508e-05b6-42e0-9f16-a7b3f38341f3">|<img width="960" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/3fa9cbc1-3c34-46c0-b527-d3bb47a02ba2">|<img width="956" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/28f735cf-76d8-4d20-aa25-e1b1de1cbd91">|<img width="955" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/4b40c0e1-8b18-4ff9-90c8-76f4a4988c47">|<img width="956" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/8a2bf1a3-3c89-419d-b50c-be4d6a2f5cc0">

</details>

#### Case 2:  Connect to VPN and remove `wireguard.dll` to fallback from `Wireguard to IKV2` 
<details>

1. Installed 1.58.100
2. launched Brave
3. open `brave://flags` in a new tab and enabled **[#brave-vpn-wireguard](chrome://flags/#brave-vpn-wireguard)**
4. clicked Relaunch 
5. purchase and configure and connect to VPN via VPN panel 
6. disconnected VPN and closed Brave
7. navigated to **"C:\Program Files\BraveSoftware\Brave-Browser-Beta\Application\116.1.58.100"**
8. deleted `wireguard.dll` from `BraveVpnWireguardService`  
9. re-launch Brave 
10. enabled VPN in the VPN panel
11. VPN was disconnected and tried to connect again 
12. `Can't connect to Server` modal is shown with VPN status changed to disconnected - `Failed`
13. clicked VPN button and enabled VPN 
14. confirmed fallback from `Wireguard to IKV2` dialog is shown
15. clicked `Restart Browser` on the dialog
16. Brave relaunched successfully
17. connected to VPN via VPN panel
18. confirmed `#brave-vpn-wireguard` is disabled in the `brave://flags`
19. opened OS Network settings
20. confirmed successfully connected to VPN via IKEv2

step 3 | step 5 | step 6 | step 7 | step 8 | step 9 | step 10 | step 11 | step 12 | step 13 | step 14 | step 17 | step 18 | step 20
----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ------ | ----  | ------
<img width="647" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/468d079d-2304-42cc-bfc8-2ca24410eea8">|<img width="953" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/85026ae9-5935-415b-a906-42f4b2d76aed">|<img width="955" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/ed9c9945-2f34-4682-bc61-6dd56983a614">|<img width="442" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/c20e4130-7889-4ec9-a422-3968fd6004fc">|<img width="454" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/a4d28eb3-7f81-419c-9732-5b00bcdce2c2">|<img width="953" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/1c003ed1-fac1-4a8c-8787-8d3e804f9f07">|<img width="946" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/184179c0-d758-460e-8013-aadbdb849e85">|<img width="950" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/1d892e6e-3245-40d5-9035-5c73097cdd8d">|<img width="950" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/362fdb27-8564-4a4d-9286-c715fe1d92f5">|<img width="949" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/ad7043ca-6846-4cce-9f8d-a00f261c1e47">|<img width="949" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/2b12fd2b-a594-4516-a7ec-7634f466c6d4">|<img width="953" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/7e4d6d8a-1245-4d08-ad26-4794d6771010">|<img width="956" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/9e9f7013-702c-425b-9f5f-cd0c375e3c64">|<img width="717" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/269a5488-83bb-4b4b-9d7f-4710d1b2525e">

</details>

Testcase 2:  Fallback to IKEv2 protocol from `Wireguard` by killing `brave_vpn_wireguard_service.exe`

Kill brave_vpn_wireguard_service.exe from Task Manager
Repeat last 2 steps few times and you should see the fallback dialog.

1. Installed 1.58.100
2. launched Brave
3. open `brave://flags` in a new tab and enabled **[#brave-vpn-wireguard](chrome://flags/#brave-vpn-wireguard)**
4. clicked Relaunch 
5. purchase and configure and connected to VPN via VPN panel 
6. opened Taskmanager>>Details>>
7. end task for brave_vpn_wireguard_service.exe
