### ISSUE TITLE
Remove Vertical tab flags 

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#30662]
When the feature seems to be stable, remove the feafure flag / buildflag.

* Now we have `vertical tab` and `sticky pinned tabs` flags enabled by default. After we remove the flags, every behavior should be the same as before.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.60.81 Chromium: 118.0.5993.54 (Official Build) beta (x86_64)
-- | --
Revision | 1efb3f333eb41cc34af46ca31fb33c30e0afbfae
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.60.81`
2. launched Brave
3. opened `brave://flags`
4. searched for `vertical tabs`
5. confirmed no vertical-tabs flags
6. opened a new-tab page
7. loaded a few sites
8. context-clicked on a tab
9. chose `Use Vertical Tabs`

example | example
---------|---------
<img width="1300" alt="Screen Shot 2023-10-06 at 12 58 34 PM" src="https://github.com/brave/brave-browser/assets/387249/7beb0d41-afc1-4818-8dff-83bccf34ba29"> | <img width="1483" alt="Screen Shot 2023-10-06 at 2 00 53 PM" src="https://github.com/brave/brave-browser/assets/387249/047d4b2b-0646-4503-873a-9a3eb699fec1">
