### ISSUE TITLE
Swap screen is not loading on nightly

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#30667]
## Description 
Swap screen is not loading on nightly, showing blank screen

## Steps to reproduce 

   1. Login to wallet
   2. Open swap

## Actual result 
[swap-tx-issue.webm](https://github.com/brave/brave-browser/assets/11755381/ee3db627-3141-49f5-b37e-8eabc58124fa)

## Expected result
Should be able to swap

## Issue reproduces how often 
easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? N
- Can you reproduce this issue with the current Play Store Beta version? N
- Can you reproduce this issue with the current Play Store Nightly version? Y

## Brave version
1.54.16 Chromium: 114.0.5735.53 (Official Build) canary (32-bit) 

cc: @onyb @SergeyZhukovsky @vadimstruts

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.57.27 x64 Beta build
- Verified steps from [brave/brave-core#18678](https://github.com/brave/brave-core/pull/18678)
- Verified able to load Swap from Wallet
- Verified able to switch accounts on Swap screen

https://github.com/brave/brave-browser/assets/17010094/27180bbe-e0f1-4b77-a672-fe56e0655006
