### ISSUE TITLE
Update Play Billing Library

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#30673]
We have a message from Google that the current Play Billing Library version we use is going to be deprecated on November 1, 2023. We should migrate to the version 5.

**Comment by kjozwiak** [comment]
@vlad-hoff @SergeyZhukovsky we should also spot check the above via `Android 13` & `Android 14` just to make sure VPN is working. If we have time, a quick check on `Android 8` is probably a good idea as well. The above requires `1.58.122` or higher for `1.58.x` verification 👍
