### ISSUE TITLE
Rewards utility process is not restarted after crash or exit

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#30680]
Currently the Rewards utility process is not restarted if it crashes or is stopped, leading to confusing UX as reported in https://github.com/brave/brave-browser/issues/30573.

The utility process should be restarted in such cases, but we need to be careful to avoid "restart loops".

**Comment by LaurenWags** [comment]
@zenparsing how would we test this on Android? or should we remove `OS/Android` as it pertains to testing this issue?

cc @Miyayes

**Comment by Miyayes** [comment]
@timchilds (@deeppandya): If we don't have a way of testing this on Android, let's remove the OS/Android label.

**Comment by LaurenWags** [comment]
Per https://bravesoftware.slack.com/archives/C03MMJ4CHEZ/p1694554223243969?thread_ts=1694544433.513969&cid=C03MMJ4CHEZ, https://bravesoftware.slack.com/archives/C03MMJ4CHEZ/p1694554404421149?thread_ts=1694544433.513969&cid=C03MMJ4CHEZ, and https://github.com/brave/brave-browser/issues/30680#issuecomment-1708663836 removing the `OS/Android` label for this issue.

Pls advise if there are any concerns.

cc @sujitacharya2005 @deeppandya @Miyayes
