### ISSUE TITLE
&amp; shown on onboarding first screen

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#3068]
## Description 

&amp; shown on onboarding first screen

## Steps to Reproduce

   1. Clean profile 
   2. Click `Lets go` 
   3. Shows `&amp;` instead of `&`

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/51659163-cb3d6300-1fcf-11e9-9ce2-2173b8632c54.png)

## Expected result:
Should show as per specs

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.59.28 Chromium: 72.0.3626.64 (Official Build) beta(64-bit)
-- | --
Revision | eaa9668e80ce5405e7f1902579558ea725c06ca1-refs/branch-heads/3626@{#708}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Should be a problem on all channels
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

Marking issue as P2 and sticking it into 0.59.x milestone as the new welcome screen is supposed to be part of this release and this is a bad onboarding screen for Linux 
cc: @rebron @rossmoody @kjozwiak @bbondy @cezaraugusto

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Mint 19.1 x64 VM` using the following build:

Brave | 0.59.30 Chromium: 72.0.3626.71 (Official Build) (64-bit)
--- | ---
Revision | f52ccad2a6a3c65fc9e0c591a517ceab1198dac0-refs/branch-heads/3626@{#763}
OS | Linux

<img width="1099" alt="screen shot 2019-01-28 at 12 39 58 am" src="https://user-images.githubusercontent.com/2602313/51816607-46836b00-2295-11e9-8faa-186f7c7079be.png">
