### ISSUE TITLE
Onboarding doesn't auto navigate to the next step when going back to brave://welcome screen

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#3069]
## Description 

Onboarding doesn't auto navigate to the next step when going back to brave://welcome screen

## Steps to Reproduce

   1. Clean profile 
   2. Click `Lets go` on the first screen
   3. Click on `Import`, opens importer screen in a new tab
   4. Switch back to brave://welcome, automatically navigates to the next step 
   5. Click on `Settings`, opens settings page in a new tab
   6. Switch back to brave://welcome, doesn't navigate to the next step, user has to manually navigate 
   7. Repeat for all the subsequent steps, same doesn't auto navigate to the next step

## Actual result:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/17010094/51659628-1c018b80-1fd1-11e9-9027-947c9ca9b70e.gif)

## Expected result:
If user performs a step on onboarding screen, switching back should auto proceed to the next step

## Reproduces how often: 

Easy

## Brave version (brave://version info)

All

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
All
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @rossmoody @cezaraugusto @rebron

**Comment by btlechowski** [comment]
Reproduced on Windows 7 x64

Brave | 0.59.28 Chromium: 72.0.3626.64 (Official Build) beta(64-bit)
-- | --
Revision | eaa9668e80ce5405e7f1902579558ea725c06ca1-refs/branch-heads/3626@{#708}
OS | Windows

**Comment by kjozwiak** [comment]
Noticed this as well a few days ago but forgot to file an issue for it :( The only one that works and moves to the next one is the `Import` screen. Opening it via the `Import` button opens `chrome://settings/importData` and than switches to `Settings` when going back to `brave://welcome`.

Definitely not a blocker but would be a nice to have. It's not a regression as the older `brave://welcome` implementation did the same thing.

**Comment by cezaraugusto** [comment]
@srirambv onboarding flow changed a bit since this bug. Could you confirm issue persists?

**Comment by bsclifton** [comment]
Closing as stale. Let's re-open if it's still an issue. Thanks!
