### ISSUE TITLE
Navigating back causes stats to reset on that tab

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#307]
## Description 
Navigating back causes stats to reset on that tab

## Steps to Reproduce

   1. Build from source ( aa02380)
   2. Open a new tab and visit a site so that stats get updated
   3. Open a second tab and ensure the updated stats are shown
   4. Search/visit a new site in the second tab
   5. Click back button to go back to new tab, stats reset to 0, reload doesn't change
   6. Open a third tab, stats show correctly 

 ## Actual result:

![privatetav](https://user-images.githubusercontent.com/17010094/41135832-6bfb0bf6-6aa1-11e8-91d8-643227c7b404.gif)

## Expected result:
Navigating back shouldn't reset stats on the new tab page

## Reproduces how often: 
100%

## Brave version (about:brave info)
 aa02380

### Additional Information
Same behaviour on both normal tabs and private tabs

**Comment by srirambv** [comment]
Issue looks fixed on master (3924de4e2feab94fc10d1eb11eca8896ecc7bb24)

**Comment by btlechowski** [comment]
Still reproducible, tested:

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7

![307_fail](https://user-images.githubusercontent.com/34715963/45865396-a618b980-bd7d-11e8-8426-188f4134abc5.gif)

**Comment by kjozwiak** [comment]
Reproducible under `macOS 10.13.6 x64` using the same build @btlechowski mentioned above.

**Comment by srirambv** [comment]
Broken on Linux as well for `0.55.5`

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/homepage-shows-0-for-all-stats-if-you-go-back/33755

**Comment by Liunkae** [comment]
Still reproducible for me with Brave 0.57.3 on macOS 10.14.
![](https://user-images.githubusercontent.com/19424103/47545343-6a5b9d00-d8b1-11e8-8627-c4111a122de3.gif)

**Comment by srirambv** [comment]
+1 from @sillibird via #1865

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.58.11 Chromium: 71.0.3578.80 (Official Build) beta(64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Linux

- Opened a site in a new tab 
- Checked stats on second newtab
- Visited a different site in second newtab and navigated back, stats didnt get reset
