### ISSUE TITLE
Canvas fingerprint is forged: pixels

### ISSUE THREAD

**Issue by hzdlive** [brave/brave-browser#30704]
## Description 

Canvas fingerprint is forged: pixels

## Steps to Reproduce

   1. https://www.owlssky.com/buildins/check.html
   2. 
   3. 

## Actual result:

![20230531143232](https://github.com/brave/brave-browser/assets/3319136/f7bcb289-d263-4453-a268-553140766716)

## Brave version (brave://version info)
1.51.114 Chromium:113.0.5672.92 x64

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment]
cc: @pes10k

**Comment by pes10k** [comment]
This isn't a bug, this is the feature working as intended (see screenshot of different fingerprints in a private window vs a normal window)

https://brave.com/privacy-updates/4-fingerprinting-defenses-2.0/#2-fingerprinting-protections-20-farbling-for-great-good

If im missing something feel free to re-open, but this looks like the protection being successul

**Comment by pes10k** [comment]
<img width="409" alt="Screenshot 2023-05-31 at 15 04 04" src="https://github.com/brave/brave-browser/assets/76526/2a1b4d1e-1b28-448a-bfed-7aaac99b19be">
