### ISSUE TITLE
Wait until Wireguard service stopped

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#30706]
Remove TODO https://github.com/brave/brave-core/blob/master/components/brave_vpn/browser/connection/wireguard/win/brave_vpn_wireguard_service/wireguard_tunnel_service.cc#L144
and add something like https://source.chromium.org/chromium/chromium/src/+/main:chrome/credential_provider/extension/os_service_manager.cc;l=125?q=OSServiceManager::WaitForServiceStopped&sq=&ss=chromium

**Comment by LaurenWags** [comment]
Relabeled as `QA/No` per discussion via https://bravesoftware.slack.com/archives/CC5SA8CCB/p1692642914862249, will be verified in 1.59.x with https://github.com/brave/brave-browser/issues/32003 per https://github.com/brave/brave-browser/issues/32003#issuecomment-1688708057.
