### ISSUE TITLE
Unable to view activity tab after submitting an Arbitrum transaction 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#30703]
## Description 

Unable to vie activity tab after submitting an Arbiturum transaction 

## Steps to Reproduce

   1. Submit a Arbitrum transaction on `https://match.xyz`
   2. Go to activity tab
   3. Reload the page, console throws error and page goes blank

## Actual result:

![brave_h1d7RFcOgp](https://github.com/brave/brave-browser/assets/17010094/48ebcc16-55a3-4ca4-b142-0d19a923cc0a)

## Expected result:
No errors. Activity should be shown

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.52.116 Chromium: 114.0.5735.58 (Official Build) (64-bit)
-- | --
Revision | `ef012197ab4bc867d7b1dd80a001d0be7da8a714-refs/branch-heads/5735_52@{#7}`
OS | Windows 11 Version 22H2 (Build 22621.1778)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Not checked
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:
cc: @onyb

**Comment by josheleonard** [comment]
fixed by: https://github.com/brave/brave-core/pull/18299

**Comment by srirambv** [comment]
Closing as Dupe of https://github.com/brave/brave-browser/issues/23565 as its already fixed with https://github.com/brave/brave-core/pull/18299
