### ISSUE TITLE
Incorrect response for the metrics `Brave.Today.IsEnabled` when brave news is turned OFF and ON via different NTP's

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#30709]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/30154
Incorrect response for the metrics `Brave.Today.IsEnabled` when brave news is turned OFF and ON via different NTP's
## Steps to Reproduce

1. Clean profile 1.53.x
2. Open an NTP and scroll down to view brave news welcome screen and click on the `No thanks` button 
3. Open brave://local-state
4. Look for the metrics `Brave.Today.IsEnabled`
5. Confirmed that the metrics `Brave.Today.IsEnabled` response value is `0` as expected
6. Open 2nd NTP
7. Click on the `Customize->Brave News->Turn on Brave news` via NTP dashboard settings in 2nd NTP 
8. Reload brave://local-state, the metrics `Brave.Today.IsEnabled` response is still `0` instead of `1`
9. Open 3rd NTP and view brave news feeds
10. Reload brave://local-state, the metrics `Brave.Today.IsEnabled` response is still `0` instead of `1`
11. Exit the browser and restart
12. Reload brave://local-state, the metrics `Brave.Today.IsEnabled` response is still `0` instead of `1`

## Actual result:

Incorrect response for the metrics `Brave.Today.IsEnabled` when brave news is turned OFF and ON via different NTP's
## Expected result:

Response should `1` when Brave news is enabled via 2nd NTP
## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.53.74 Chromium: 114.0.5735.53 (Official Build) beta (64-bit)
-- | --
Revision | c499d7ea22c8b2dba278465a5df7b86a8efa4e64-refs/branch-heads/5735@{#970}
OS | Windows 10 Version 22H2 (Build 19045.2965)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @DJAndries @mattmcalister

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.54.64 Chromium: 114.0.5735.133 (Official Build) nightly (64-bit)
-- | --
Revision | fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}
OS | Windows 10 Version 22H2 (Build 19045.3086)

```

1. Clean profile 1.53.x
2. Open an NTP and scroll down to view brave news welcome screen and click on the `No thanks` button 
3. Open brave://local-state
4. Look for the metrics `Brave.Today.IsEnabled`
5. Confirmed that the metrics `Brave.Today.IsEnabled` response value is `0` as expected
6. Open 2nd NTP
7. Click on the `Customize->Brave News->Turn on Brave news` via NTP dashboard settings in 2nd NTP 
8. Reload brave://local-state, the metrics `Brave.Today.IsEnabled` response is still `0` instead of `1`
9. Open 3rd NTP and view brave news feeds
10. Reload brave://local-state, the metrics `Brave.Today.IsEnabled` response is still `0` instead of `1`
11. Exit the browser and restart
12. Reload brave://local-state, the metrics `Brave.Today.IsEnabled` response is still `0` instead of `1`

step 5 | step 7 | step 8 | step 9 | step 10 | step 12
-------|--------|---------|--------|---------|---------
![image](https://github.com/brave/brave-browser/assets/38657976/4f4db5a4-6b72-4c23-a2d0-f7149b349b9a) | ![image](https://github.com/brave/brave-browser/assets/38657976/550f13bd-81c7-42ec-8509-e70d19deba48) | ![image](https://github.com/brave/brave-browser/assets/38657976/65d3a15e-9cb1-4a38-b284-d5426a3992d0) | ![image](https://github.com/brave/brave-browser/assets/38657976/a13a9ac0-a690-46e8-8249-6a747a96ae99) | ![image](https://github.com/brave/brave-browser/assets/38657976/e2d8327e-3bd5-418c-a0a0-198eb8e5f143) | ![image](https://github.com/brave/brave-browser/assets/38657976/700bc41f-4726-49ac-9bf9-b4a3c09d5053)

**Comment by kjozwiak** [comment]
Removing `QA Pass-Win64` as the above will need to be re-checked via `1.53.x` now that it's been uplifted via https://github.com/brave/brave-core/pull/18935. @GeetaSarvadnya honestly, can probably just do a quick spot check as you've basically already checked this on `1.55.x` & `1.54.x` via https://github.com/brave/brave-browser/issues/30709#issuecomment-1594592309 & https://github.com/brave/brave-core/pull/18701#issuecomment-1603699205.

@DJAndries labelled it as `Done` but not sure about the `wiki` part of the above (not 100% sure what the process is)

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
Brave | 1.53.104 Chromium: 115.0.5790.40 (Official Build) (64-bit)
-- | --
Revision | 071c9ddea889c3c7887daf4eac13fed72d4fff62-refs/branch-heads/5790@{#979}
OS | Windows 10 Version 22H2 (Build 19045.3086)
```
1. Clean profile 1.53.104
2. Open an NTP and scroll down to view brave news welcome screen and click on the `No thanks` button 
3. Open brave://local-state
4. Look for the metrics `Brave.Today.IsEnabled`
5. Confirmed that the metrics `Brave.Today.IsEnabled` response value is `0` as expected
6. Open 2nd NTP
7. Click on the `Customize->Brave News->Turn on Brave news` via NTP dashboard settings in 2nd NTP 
8. Reload brave://local-state, the metrics `Brave.Today.IsEnabled` response is still `0` instead of `1`
9. Open 3rd NTP and view brave news feeds
10. Reload brave://local-state, the metrics `Brave.Today.IsEnabled` response is still `0` instead of `1`
11. Exit the browser and restart
12. Reload brave://local-state, the metrics `Brave.Today.IsEnabled` response is still `0` instead of `1`

step 5 | step 7 | step 8 | step 9 | step 10 | step 12
-------|--------|---------|--------|---------|---------
![image](https://github.com/brave/brave-browser/assets/38657976/02387eb6-f9f5-4b75-b463-4617a94307d3) | ![image](https://github.com/brave/brave-browser/assets/38657976/9e19039b-4cc1-49b9-8ec8-7b1eb2e784ab) | ![image](https://github.com/brave/brave-browser/assets/38657976/d01ee886-c84d-4165-b3d0-ef545c58b937) | ![image](https://github.com/brave/brave-browser/assets/38657976/2e63f16c-4188-45b5-9953-043f09a7fb21) | ![image](https://github.com/brave/brave-browser/assets/38657976/938a0492-683d-457d-be11-74ddc56a31da) | ![image](https://github.com/brave/brave-browser/assets/38657976/1d0b3591-d49b-4d96-ac4b-566d4d0020a4)
