### ISSUE TITLE
Wallet's Keyring Id should be an enum instead of set of string constants.

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#30705]
Wallet's Keyring Id should be an enum instead of set of string constants.

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.57.18 Chromium: 115.0.5790.98 (Official Build) beta (64-bit)
-- | --
Revision | `d515871a6c6df7d2843e755c8b7dda9b744f26d6`
OS | Windows 11 Version 22H2 (Build 22621.1992)

- Verified steps from [brave/brave-core#18690](https://github.com/brave/brave-core/pull/18690)
- Verified wallet account functionality works as expected

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.57.44 x64 build
- Verified steps from [brave/brave-core#18690](https://github.com/brave/brave-core/pull/18690)
- Verified wallet account functionality works as expected
