### ISSUE TITLE
Add System Tray icon UI for BraveVpnWireguardService

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#30708]
We would like to let users to work with Brave VPN without browser, as one of solutions is to add system tray menu to manage vpn connection.
- The service should setup tray icon once connection happened and remove it if the wireguard experiment will be disabled or the browser removed

```
(If connected)
- Status: Active | Region
- Disconnect
(If disconnected)
- Status: Inactive
- Connect
       -----
- Select Region:
    - Region1
    - Region2
    - ...
- Manage Account (link to [account.brave.com](http://account.brave.com/))
- About Brave VPN (link to https://brave.com/firewall-vpn/)
```

https://docs.google.com/document/d/18HMN-G4NAxrdaihC-ybl9-blhCqT7Vca-E1TdK2zJls/edit#bookmark=id.om2p9c6c252k

**Comment by spylogsster** [comment]
cc @aguscruiz for system tray icon

**Comment by bsclifton** [comment]
@spylogsster icon available in Figma:
https://www.figma.com/file/qtMYwoj3JWJO5xzwLt6j2f/Desktop-VPN?type=design&node-id=2160-55535&t=Asw3DxXeQC3IVUSI-0

Under `Production - VPN Icon in System tray`

**Comment by spylogsster** [comment]
Issue to add localization for menu items https://github.com/brave/brave-browser/issues/30959

**Comment by spylogsster** [comment]
Placeholder for future to promote a tray icon from the overflow area to the taskbar https://github.com/brave/brave-browser/issues/30960
