### ISSUE TITLE
Macbook m1 (arm) crash after launching brave wallet

### ISSUE THREAD

**Issue by nbdy-coder** [brave/brave-browser#30714]
## Description 
Hello,
Since few weeks, if i open the brave wallet with my macbook pro m1, my computer crash and reboot.
I also test with another macbook m1 and same problem.
Both mac are updated and brave browser have the last update. I had the same problem with the old updates.

## Steps to Reproduce
   1. connect brave wallet
   2. navigate in the wallet during few seconds/minutes
   3. computer crash and reboot

## Actual result:
crash and reboot

## Expected result:
should not crash

## Reproduces how often: 
easily

## Brave version (brave://version info)
1.51.118 Chromium: 113.0.5672.126 (Official Build) (arm64)

**Comment by nbdy-coder** [comment]
i still have the error on differents mac with the last update :
[Version 1.52.122 Chromium: 114.0.5735.110 (Official Build) (arm64)](https://brave.com/latest/)

It's totally unstable...

**Comment by nbdy-coder** [comment]
Hello,

I stil have the error on 2 macbook pro 1.

Can you do something ??? It's not fcking normal than launch your wallet = freeze the mac, crash it and auto reboot

**Comment by josheleonard** [comment]
@nbdy-coder Is this still occurring for you? If so, do you have a large amount of enabled chains, assets and/or accounts?

**Comment by nbdy-coder** [comment]
> @nbdy-coder Is this still occurring for you? If so, do you have a large amount of enabled chains, assets and/or accounts?

the issue is fixed since the update 1.58.129.
https://github.com/brave/brave-browser/issues/32427#issuecomment-1728879067
