### ISSUE TITLE
Incorrect response value for the metrics `Brave.Today.UsageMonthly` 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#30722]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/30154
Incorrect response value for the metrics `Brave.Today.UsageMonthly` 
## Steps to Reproduce

   1. Clean profile 1.53.x
   2. Enable Brave News via NTP (31st May)
   3. View brave news feeds via NTP
   4. Open brave://local-state file 
   5. Confirmed that the metrics `Brave.Today.UsageMonthly` response value is `1`  and the flag value is set to "true" as expected
   6. Close the browser
   7. Set the sys date ahead by one day (i.e 1st June 2023 in my case)
   8. Relaunch the browser
   9. Reload brave://local-state and look for the metrics `Brave.Today.UsageMonthly`
   10. The metrics `Brave.Today.UsageMonthly` response value is still  `1` which is incorrect as 1st June I have not viewed any brave news feeds
![image](https://github.com/brave/brave-browser/assets/38657976/0ad322f8-e56e-48a8-9e8b-bc6748abf356)

## Actual result:

Incorrect response value for the metrics `Brave.Today.UsageMonthly` 
## Expected result:
the metrics `Brave.Today.UsageMonthly` should not be shown in June month as no news feeds are viewed in June month

## Reproduces how often: 

Easy
## Brave version (brave://version info)

<html>
<body>

Brave | 1.53.74 Chromium: 114.0.5735.53 (Official Build) beta (64-bit)
-- | --
Revision | c499d7ea22c8b2dba278465a5df7b86a8efa4e64-refs/branch-heads/5735@{#970}
OS | Windows 10 Version 22H2 (Build 19045.2965)

</body>
</html>
## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @DJAndries @mattmcalister

**Comment by DJAndries** [comment]
@GeetaSarvadnya did you ensure the sent flag was set to true before advancing the system time? Also I see that you have an NTP in your tabs. If that's a restored tab with a news session, then the metric will be recorded as expected.

**Comment by GeetaSarvadnya** [comment]
>did you ensure the sent flag was set to true before advancing the system time? 

@DJAndries The sent flag value is "true" which is mentioned in the step 5 above.

>Also I see that you have an NTP in your tabs. If that's a restored tab with a news session, then the metric will be recorded as expected.

@DJAndries Let me close the NTP before I advance the sys date and try again. Thanks!

**Comment by GeetaSarvadnya** [comment]
@DJAndries I have closed the NTP before advancing the sys date, After advancing the sys date, the usagemonthly metrics value is still `1` looks like a bug

**Comment by GeetaSarvadnya** [comment]
The issue is reproducible in Android as well hence adding OS/Android label

**Comment by DJAndries** [comment]
@GeetaSarvadnya I noticed that you're advancing the clock by one day. Please advance it by one calendar month instead

**Comment by GeetaSarvadnya** [comment]
@DJAndries In the scebario above, If I set the sys date ahead by one day a month is changing (i.e May 31st->1st June) but there is only one day difference between the two month, so I though the monthly usage metrics should not be shown on the 1st June if I have viewed brave news feeds on 1st June. 

But, if the monthly usage metrics calculation is considering the **calendar month** then this issue is working as expected. e.g If I view brave news feeds today 14th June and confirmed monthly usage metrics response value is `1` and sent flag value is "true" then fwd the sys clock by one month (i.e 14th July), relaunch the browser will not show the monthly usage and daily usage metrics in brave://local-state file as expected.

**Comment by DJAndries** [comment]
@GeetaSarvadnya sorry, i just realized that you were testing at the end of the month, which should work...

I just followed your steps, but used the dates June 30 and July 1. The results were expected. Could you please re-test with these dates? again, sorry for the confusion

**Comment by GeetaSarvadnya** [comment]
Viewed brave news on month end June 30th and fwd the sys clock by one day (i.e July 1st), relaunch the browser, shows the monthly usage response value as `1` .

June 30 | July 1st
---------|--------
![image (3)](https://github.com/brave/brave-browser/assets/38657976/0432e5ab-1781-4204-b803-93bbe5088009) | ![image (4)](https://github.com/brave/brave-browser/assets/38657976/e8a1b6e0-bc55-44b6-86f6-04cf366fe4da)
