### ISSUE TITLE
Brave opening in light mode despite dark mode specified in settings

### ISSUE THREAD

**Issue by WilhelmVonHindenburger** [brave/brave-browser#30729]
## Description 

I am using Linux Mint 21.1 "Vera" with Brave Version 1.52.117 Chromium: 114.0.5735.90 (Official Build) (64-bit)
The problem started after updating to 1.52.117 using Mint's update manager, I am using the apt package.

I have Brave set to dark mode, but every time I open the browser it opens in light mode.
The settings page, however, still shows that it is dark mode but the entire UI (including the settings page) is in light mode.
![image](https://github.com/brave/brave-browser/assets/104843104/0a8712a4-38bd-4846-b0f3-feef265fc0fa)
I have to manually set it to light mode and then back to dark mode for dark mode to work properly.

## Steps to Reproduce

   1. Close the browser
   2. Open the browser

## Actual result:

![image](https://github.com/brave/brave-browser/assets/104843104/f9f0e2ab-1c0d-4678-ad06-7e7a98979c9f)
It shows up in light mode, despite saying it is in dark mode.

## Expected result:
It should open in dark mode.

## Reproduces how often: 

I have managed to consistently have this issue every time I launch the browser.

## Brave version (brave://version info)

1.52.117 Chromium: 114.0.5735.90 (Official Build) (64-bit) 
Revision 386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}
Apt package for GNU/Linux

## Version/Channel Information:

I have only experienced this on the latest apt package (1.52.117), the previous version of the apt package (1.51.118) did not have this issue.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- No, it is not related to Shields or Rewards.

- Is the issue reproducible on the latest version of Chrome? 
- I have not tested it on Chrome

**Comment by kraizelburg** [comment]
I also confirm this bug in Linux. I think it is a problem of the latest version, testen on arch and mint so far.

**Comment by NathanCampioni** [comment]
I also have this issue, I did report it on the reddit page, a few other people had the same problem:
https://www.reddit.com/r/brave_browser/comments/13ws8as/linux_version_bug_with_new_version/

**Comment by WilhelmVonHindenburger** [comment]
I have also experienced the GTK theme issue you described.

**Comment by cyber-shifter** [comment]
Add another one to the count. Worst bug ever! :-P My system config is the same as the OP.

**Comment by tomarus** [comment]
Same issue here. I'm on debian bookworm.

**Comment by jschuhmann47** [comment]
Same here on Mint 21.1

**Comment by thatanjan** [comment]
I am also facing this issue in Manjaro. I am using `Brave Browser 114.1.54.25 nightly`

**Comment by gscbravo** [comment]
Same issue here on Linux Mint 21.1.

**Comment by zquestz** [comment]
Also affected. Arch with Cinnamon.

**Comment by TAmzid2872** [comment]
I'm also having this issue. Both on flatpak and system package. Linux mint 21.1 Cinnamon

**Comment by HFMorais** [comment]
I have the same issue with Mint 21.1, in 2 distinct machines

**Comment by ZReC** [comment]
yep, the same happening here (arch linux btw)

Version 1.52.117 Chromium: 114.0.5735.90 (Official Build) (64-bit)

**Comment by WilhelmVonHindenburger** [comment]
The workaround seems to have worked for me, still don't know why this issue happened

**Comment by TAmzid2872** [comment]
the workaround worked but i hope this gets fixed in a newer release.

**Comment by WilhelmVonHindenburger** [comment]
Issue still occurs on 1.52.122 (just updated the apt package)
If you have done the workaround and want to confirm for yourself, just run `gsettings reset org.gnome.desktop.interface color-scheme`
You can always apply the workaround again

**Comment by cyber-shifter** [comment]
Just updated to 1.52.122 and still having this issue. Anybody know what has caused the issue and why they can't seem to fix it?

**Comment by WilhelmVonHindenburger** [comment]
On Chromium 113.0.5672.126~linuxmint1+vera I have this same issue, complete with GTK... except the workaround _doesn't work_

**Comment by brunolpsousa** [comment]
> Just updated to 1.52.122 and still having this issue. Anybody know what has caused the issue and why they can't seem to fix it?

Probably related to #14685

**Comment by WilhelmVonHindenburger** [comment]
Still occurs on 1.52.126

**Comment by temper1234** [comment]
Same.  I thought it was a flatpak issue so i installed the regular version and it still does it.  Fix it please.

**Comment by thatanjan** [comment]
I have switched to Arco Linux and seems to be work fine on `Version 1.54.71 Chromium: 114.0.5735.133 (Official Build) nightly (64-bit)`

**Comment by USerneindanke** [comment]
I have the same issue on linux mint 21. My browser version:

`Brave | 1.52.126 Chromium: 114.0.5735.133 (Offizieller Build) (64-Bit)
-- | --
Überarbeitung | fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}
Betriebssystem | Linux
JavaScript | V8 11.4.183.23`

**Comment by munovrizall** [comment]
same issue here in Mint 21.1 Vera

**Comment by WilhelmVonHindenburger** [comment]
Just updated to 1.52.129, still happening

**Comment by temper1234** [comment]
Does anyone even read these messages?  Seems like an internet black hole.  This is an annoying bug.

**Comment by WilhelmVonHindenburger** [comment]
Should I close the issue then?

**Comment by brunolpsousa** [comment]
> Should I close the issue then?

Yes, the issue was fixed with this [PR](https://github.com/brave/brave-core/pull/19000)

**Comment by joeelmahallawy** [comment]
I'm having this problem on MacOS v1.60.114. It happened all of a sudden out of nowhere.
