### ISSUE TITLE
Create interface between Brave Rewards and Brave Wallet (Phase 1)

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#30720]
## Description

Issue just to track this task item. 

```[tasklist]
### Tasks
- [x] Create minimal interface for MVP (to show Rewards custodial balance in Brave Wallet)
- [ ] Create roadmap for future of Rewards APIs // legacy extension APIs
```

**Comment by zenparsing** [comment]
The Brave Wallet UI will use the Rewards extension API for now (which is also used by the NTP and the Rewards panel). We can transition all of them to a new mojo-based API at the same time.

**Comment by Miyayes** [comment]
Will close this for now as dupe of https://github.com/brave/brave-core/pull/18823#top
