### ISSUE TITLE
Insecure file download warning icon in toolbar size is increased

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#30736]
## Description 

While checking https://github.com/brave/brave-browser/issues/30626, I found warning icon size is changed.
Latest:
<img width="190" alt="Screenshot 2023-06-01 at 1 25 05 PM" src="https://github.com/brave/brave-browser/assets/6786187/e15249e2-9bde-460f-a713-8dacc0bb94a4">

Beta
<img width="137" alt="Screenshot 2023-06-01 at 1 28 00 PM" src="https://github.com/brave/brave-browser/assets/6786187/96706a87-f8ed-49a5-8394-122e581c57dc">

## Steps to Reproduce

1. load https://www.leaseweb.com/platform/network
2. context-click on any file-download link
3. choose Save Link As...
4. click Save

## Actual result:

Icon size should be same with current beta above.

## Expected result:
Larger icon is used

## Reproduces how often: 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.54.26 Chromium: 114.0.5735.90 (Official Build) nightly (64-bit)
-- | --
Revision | 386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}
OS | Windows 10 Version 22H2 (Build 19045.3031)

### Steps:
1. installed `1.54.26`
2. launch Brave
3. loaded `https://www.leaseweb.com/platform/network`
4. context-clicked on `10,000 mb`
5. chose `Save link as...`
6. clicked `Save`
7. confirmed insecure-download warning icon appeared on the browser toolbar

### Confirmed the insecure-download warning icon is now properly-sized

in context | up close
-----------|-----------
![image](https://github.com/brave/brave-browser/assets/387249/5552b6d8-7e07-4d20-b75a-e7b79007a99a) | ![image](https://github.com/brave/brave-browser/assets/387249/6401bb24-4a83-4d1f-9799-af7cb329c9b1)
