### ISSUE TITLE
Remove query trackers from Hive email newsletters

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#30731]
https://www.hive.co/ is an email marketing platform that appears to insert unique `h_sid` and `h_slt` query parameters.

Sample unsubscribe link: https://app.hive.co/email/elt/?h_sid=3d...22d0&hash=20...2&next=https%3A%2F%2Fapp.hive.co%2Femail%2Funsubscribe%2Ftour%2F%3Ftour_id%3D130179%26user_id%3D33...9%26hash%3Db72...d6%26utm_source%3Dhive%26utm_medium%3Demail%26utm_campaign%3Dhive_email_id_196293_pizza-city-fest

I confirmed that neither `h_sid` nor `h_slt` are necessary for unsubscribing from a list.

Also this contains a sample link that can be debounced: https://app.hive.co/email/elt/?h_sid=3d...22d0&hash=20..2&next=https%3A//www.hive.co/%3Ftid%3Dfteremail%26utm_source%3Dhive%26utm_medium%3Demail%26utm_campaign%3Dhive_email_id_196293_pizza-city-fest

**Comment by fmarier** [comment]
I couldn't find any documentation about what the parameters represent in their [documentation](https://faq.hive.co/en/). However, it seems likely that `h_sid` stands for _subscribed ID_, likely a unique ID for a user.

The `h_slt` param is base64-encoded and contains the following JSON information:
```
{"hash":"7026...78b","hive_user_id":33...89}
```
and so it contains a unique user ID that we should remove.

**Comment by fmarier** [comment]
Unfortunately, we can't strip them out of all URLs because it breaks these two types of pages:
- https://app.hive.co/email/28077/view/public?h_sid=1271475706-5aba9932b99a399aeb76f234&hash=a5a07febf520004
- https://app.hive.co/email//elt/?h_sid=48e61db721-599f6907b822446c56ff58e4&hash=7c241dd75c08b18&next=https%3A%2F%2Fwww.complex.com%2Fpop-culture%2F2018%2F06%2Fjohnny-knoxville-gets-smoked-by-spicy-wings-hot-ones

Therefore we'll have to exempt the `app.hive.co` domain from this filtering.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.57.10 Chromium: 115.0.5790.75 (Official Build) beta (x86_64)
-- | --
Revision | 6fbe50fcb5cd24cd6bd0fe48aee3a108eb21441e
OS | macOS Version 13.4.1 (a) (Build 22F770820b)
```
