### ISSUE TITLE
Brave Debian Release Channel Installation issue 

### ISSUE THREAD

**Issue by MehtabRiaz** [brave/brave-browser#30739]
## Description 

I was trying to install brave debian package via release channel and got an error on one the commands mentioned on website. So I am unable to install it. 

 
## Steps to Reproduce

   1. Once you try to install brave release channel debian package website provides these commands bellow. 
![image](https://github.com/brave/brave-browser/assets/69873770/d8420c19-f019-46b2-8938-64b077206919)
   3. but once you run the highlighted command you get an error.
![image](https://github.com/brave/brave-browser/assets/69873770/1b4b3cbf-06b3-4bff-b03f-031d5b54193e)
   5. later on `sudo apt install brave-browser` you get that package cannot be loacted.

## Actual result:

![image](https://github.com/brave/brave-browser/assets/69873770/1b4b3cbf-06b3-4bff-b03f-031d5b54193e)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

-> I tried with release, beta and nightly channel and issue persists for all three. 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by MehtabButt** [comment]
working fine now!
