### ISSUE TITLE
Tab search button is shown when it's turned off

### ISSUE THREAD

**Issue by Ptaski** [brave/brave-browser#30746]
PLEASE USE THE TEMPLATE BELOW TO PROVIDE INFORMATION ABOUT THE ISSUE. 
INSUFFICIENT INFO WILL GET THE ISSUE CLOSED. IT WILL ONLY BE REOPENED AFTER SUFFICIENT INFO IS PROVIDED-->

## Description 

Tab search button is shown even if option `Show tab search button` is off.
(After turning option on and off tab search button disappears, but when restarting browser the button reappears.) 

## Steps to Reproduce

   1. Update browser to newest version
   2. Launch browser 
   3. Tab search button, it's just there.

## Actual result:

![image](https://github.com/brave/brave-browser/assets/132298731/0faae792-3497-4fab-b309-dbc7f0a1c3c5)

## Expected result:
Tab search button shouldn't be seen

## Reproduces how often: 

Easily reproduced. 

## Brave version (brave://version info)

**Brave**: 1.52.117 Chromium: 114.0.5735.90 (Official Build) (64-bit) 
**Revision**: 386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}
**OS**: Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Yes
- Can you reproduce this issue with the beta channel? 
- I do not know
- Can you reproduce this issue with the nightly channel? 
- I do not know

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- No
- Does the issue resolve itself when disabling Brave Rewards? 
- No (That was disabled long before this bug)
- Is the issue reproducible on the latest version of Chrome? 
Not tested
## Miscellaneous Information:

I think I updated Brave yesterday, and this issue appeared just today, meaning this bug didn't appear right after update.

**Comment by kraizelburg** [comment]
I also report this issue in Mac OS and Linux. Windows is fine

**Comment by jschuhmann47** [comment]
Same here on Linux Mint 21.1

**Comment by steviator** [comment]
Confirmed on up to date Arch Linux too.
