### ISSUE TITLE
Subsequent delta updates on Windows fail

### ISSUE THREAD

**Issue by mherrmann** [brave/brave-browser#30748]
This issue behaves exactly like #29469, except the reason now is different.

The present reason is that after a normal installation, `setup.exe` in Brave's installation directory is code signed. But delta updates put a non-signed version of `setup.exe` into the installation directory. When the next delta update runs, it expects the code signed file. It sees a "different" file and falls back to the full update.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.54.53 Chromium: 114.0.5735.110 (Official Build) nightly (64-bit)
-- | --
Revision | 1c828682b85bbc70230a48f5e345489ec447373e-refs/branch-heads/5735_90@{#13}
OS | Windows 11 Version 22H2 (Build 22621.1702)
```

Verified as following for 1.54.43 -->1.54.48-->1.53.53

Run following Pre-requisites: 

- Uninstall Brave from your system (all channels)
- Run the following in an Administrator command prompt: "C:\Program Files (x86)\BraveSoftware\Update\BraveUpdate.exe" /uninstall
- The following registry key should now not exist: HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\BraveSoftware\Update\Clients.
- Delete the following file if it exists: C:\ProgramData\BraveSoftware\Update\Log\BraveUpdate.log.
- Set the registry value HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\BraveSoftware\UpdateDev\IsEnabledLogToFile to DWORD 1.


1. Install Brave 1.54.43 using its [offline installer](https://github.com/brave/brave-browser/releases/download/v1.54.43/BraveBrowserStandaloneNightlySetup.exe).
2. Accept the UAC prompt to perform a system-wide installation.
3. Close Brave and disconnect from internet so Brave doesn't accidentally get updated.
4. Open a Windows command prompt with Administrator privileges (right-click->"Run as Administrator").
5. Download the [delta installer to go from Brave 1.54.43 to 1.54.48](https://updates-cdn.bravesoftware.com/delta/Brave-Browser-Nightly/x64-ni/win/114.1.54.48/114.1.54.43/brave_installer-delta-x64.exe).
6. Enter the following in the command prompt: 
      - set BraveSoftwareUpdateIsMachine=1
7. Execute the delta installer in the same command prompt for Nightly. For example by typing: 
     - C:\Users\mseel\Downloads\brave_installer-delta-x64.exe --chrome-sxs
8. Repeat steps 5 - 7 for the [delta installer to go from Brave 1.54.48 to 1.54.53](https://updates-cdn.bravesoftware.com/delta/Brave-Browser-Nightly/x64-ni/win/114.1.54.53/114.1.54.48/brave_installer-delta-x64.exe)
9. Start Brave


![image](https://github.com/brave/brave-browser/assets/98358127/770c4231-ea44-42d1-8b6c-ef8a136956d8)
![image](https://github.com/brave/brave-browser/assets/98358127/a344327f-88f5-4aa4-be2d-f9590a977a4e)

```
[06/12/23 13:09:50.795][BraveUpdate:goopdate][33560:35344][Installing][display name: Brave-Browser-Nightly][app id: {C6CB981E-DB30-4876-8639-109F8933582C}][installer path: C:\Program Files (x86)\BraveSoftware\Update\Install\{88239D9D-341F-4830-9F15-408008C11BF3}\brave_installer.exe][manifest args: --do-not-launch-chrome --chrome-sxs][installer data: ][untrusted data: ][priority: 10]
[06/12/23 13:09:50.796][BraveUpdate:goopdate][33560:35344][Running installer][C:\Program Files (x86)\BraveSoftware\Update\Install\{88239D9D-341F-4830-9F15-408008C11BF3}\brave_installer.exe][--do-not-launch-chrome --chrome-sxs][{C6CB981E-DB30-4876-8639-109F8933582C}]
[06/12/23 13:09:56.605][BraveUpdate:goopdate][33560:35344][InstallerResult][{C6CB981E-DB30-4876-8639-109F8933582C}][0]
[06/12/23 13:09:56.605][BraveUpdate:goopdate][33560:35344][InstallApp returned][0x0][{C6CB981E-DB30-4876-8639-109F8933582C}][type:1][code: 0][]["C:\Program Files\BraveSoftware\Brave-Browser-Nightly\Application\brave.exe" --from-installer]
[06/12/23 13:09:56.700][BraveUpdate:goopdate][33560:24160][Started process][32556]
```

**Comment by MadhaviSeelam** [comment]
@mherrmann  I am not seeing delta updates.  Can you check the `Actual Results` above please?

**Comment by mherrmann** [comment]
@MadhaviSeelam the way you documented the steps are really clear to understand. Thank you!

When you invoke `brave_installer-delta-x64.exe` from the command line, then the contents of `BraveUpdate.log` do not matter. All that matters is that `brave://version` shows the expected new version.

Let me explain why.

Brave's update mechanism on Windows works as follows: It asks the update server for a new version. If there is a new version, then the server returns the URL to a `.exe` file. The updater downloads and runs this file. As it performs these steps, it writes to `BraveUpdate.log`.

If the `.exe` fails with a non-zero exit code, then the updater repeats the process on the same channel, but with `-full` appended to the channel name. This lets the updater fall back to the full update when a delta update fails. For example: The typical Nightly channel is `x64-ni`. Say the updater obtained a delta update `brave_installer-delta-x64.exe` from there, but this `.exe` fails. Then the updater performs an update check on `x64-ni-full`. This returns the full installer, and so (hopefully) the update goes through even though the delta update failed.

Now to tie this back to `BraveUpdate.log`: When we manually execute `brave_installer-delta-x64.exe` on the command line, then we are simulating what the updater would do. The reason why we do it this way is that the updater would receive the full update 1.54.43 -->1.54.53 from the server, which would prevent us from testing the delta 1.54.43 -->1.54.48. The relevant log file for `brave_installer-delta-x64.exe` is `C:\Users\<user>\AppData\Local\Temp\chromium_installer.log`.

I hope this helps clarify the context?

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using 
```
Brave | 1.57.16 Chromium: 115.0.5790.98 (Official Build) beta (64-bit)
-- | --
Revision | d6c8a44fbe78ae6ee53d838307b4d17bec8de940
OS | Windows 11 Version 22H2 (Build 22621.1992)
```

Verified as following for 1.57.16 -->1.57.18-->1.57.24

Run following Pre-requisites: 

- Uninstall Brave from your system (all channels)
- Run the following in an Administrator command prompt: "C:\Program Files (x86)\BraveSoftware\Update\BraveUpdate.exe" /uninstall
- The following registry key should now not exist: HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\BraveSoftware\Update\Clients.
- Delete the following file if it exists: C:\ProgramData\BraveSoftware\Update\Log\BraveUpdate.log.
- Set the registry value HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\BraveSoftware\UpdateDev\IsEnabledLogToFile to DWORD 1.


1. Install Brave 1.57.16 using its [offline installer](https://github.com/brave/brave-browser/releases/tag/v1.57.16).
2. Accept the UAC prompt to perform a system-wide installation.
3. Close Brave and disconnect from internet so Brave doesn't accidentally get updated.
4. Open a Windows command prompt with Administrator privileges (right-click->"Run as Administrator").
5. Download the [delta installer to go from Brave 1.57.16 to 1.57.18](https://updates-cdn.bravesoftware.com/delta/Brave-Browser-Beta/x64-be/win/115.1.57.18/115.1.57.16/brave_installer-delta-x64.exe
6. Enter the following in the command prompt: 
      - set BraveSoftwareUpdateIsMachine=1
7. Execute the delta installer in the same command prompt for beta. For example by typing: 
     - C:\Users\mseel\Downloads\brave_installer-delta-x64.exe --chrome-beta
8. Repeat steps 5 - 7 for the [delta installer to go from Brave 1.57.16 to 1.54.18](https://updates-cdn.bravesoftware.com/delta/Brave-Browser-Beta/x64-be/win/115.1.57.24/115.1.57.18/brave_installer-delta-x64.exe)
9. Start Brave

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using 
```
Brave | 1.57.16 Chromium: 115.0.5790.98 (Official Build) beta (64-bit)
-- | --
Revision | d6c8a44fbe78ae6ee53d838307b4d17bec8de940
OS | Windows 11 Version 22H2 (Build 22621.1992)
```

Verified as following for 1.57.16 -->1.57.18-->1.57.24

Run following Pre-requisites: 

- Uninstall Brave from your system (all channels)
- Run the following in an Administrator command prompt: "C:\Program Files (x86)\BraveSoftware\Update\BraveUpdate.exe" /uninstall
- The following registry key should now not exist: HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\BraveSoftware\Update\Clients.
- Delete the following file if it exists: C:\ProgramData\BraveSoftware\Update\Log\BraveUpdate.log.
- Set the registry value HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\BraveSoftware\UpdateDev\IsEnabledLogToFile to DWORD 1.

1. Install Brave 1.57.16 using its [offline installer](https://github.com/brave/brave-browser/releases/tag/v1.57.16).
2. Accept the UAC prompt to perform a system-wide installation.
3. Close Brave and disconnect from internet so Brave doesn't accidentally get updated.
4. Open a Windows command prompt with Administrator privileges (right-click->"Run as Administrator").
5. Download the [delta installer to go from Brave 1.57.16 to 1.57.18](https://updates-cdn.bravesoftware.com/delta/Brave-Browser-Beta/x64-be/win/115.1.57.18/115.1.57.16/brave_installer-delta-x64.exe
6. Enter the following in the command prompt: 
      - set BraveSoftwareUpdateIsMachine=1
7. Execute the delta installer in the same command prompt for beta. For example by typing: 
     - C:\Users\mseel\Downloads\brave_installer-delta-x64.exe --chrome-beta
8. Repeat steps 5 - 7 for the [delta installer to go from Brave 1.57.16 to 1.54.18](https://updates-cdn.bravesoftware.com/delta/Brave-Browser-Beta/x64-be/win/115.1.57.24/115.1.57.18/brave_installer-delta-x64.exe)
9. Start Brave

**Comment by MadhaviSeelam** [comment]
Verification  on Win 10
```
Brave | 1.57.27 Chromium: 115.0.5790.114 (Official Build) beta (64-bit)
-- | --
Revision | 18977fb43f693d5a8deeb48bd1cfa52651d3f73e
OS | Windows 10 Version 22H2 (Build 19045.3208)
```
ex | ex | BraveUpdate| chromium_installer 
---- | ---- | ---  | ---
![image](https://github.com/brave/brave-browser/assets/98358127/83b1012b-188b-4c69-b2c4-4a6166d87fd6)|![image](https://github.com/brave/brave-browser/assets/98358127/fd37d9da-fe6e-4690-8363-210b05caa727)|![image](https://github.com/brave/brave-browser/assets/98358127/e610a295-a1fc-4841-b6bc-3fa4048f45c2)|![image](https://github.com/brave/brave-browser/assets/98358127/5ff40f3f-237a-4fd6-84ac-e1dcfc42f323)

**Comment by mherrmann** [comment]
@MadhaviSeelam let's ignore the log files for now please.

By "successfully updated via brave://settings/help", do you mean that you had internet access and updated from a previous Brave version by opening that page?

What I want to know please is if, after running each `brave_installer-delta-x64.exe` and without internet access, you see the correct version in `brave://settings/help`.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.57.24 Chromium: 115.0.5790.136 (Official Build) beta (64-bit)
-- | --
Revision | 8099932ede6f8d4624fbddf39d27abb3b340d8c9
OS | Windows 11 Version 22H2 (Build 22621.1992)
```

1. Install Brave 1.57.24 using it's offline installer, [BraveBrowserStandaloneBetaSetup.exe](https://github.com/brave/brave-browser/releases/download/v1.57.24/BraveBrowserStandaloneBetaSetup.exe)
2. Accept the UAC prompt to perform a system-wide installation.
3. Close Brave and disconnect from internet so Brave doesn't accidentally get updated.
4. Open a Windows command prompt with Administrator privileges (right-click->"Run as Administrator").
5. Download the [delta installer to go from Brave 1.57.24 to 1.57.27](https://updates-cdn.bravesoftware.com/delta/Brave-Browser-Beta/x64-be/win/115.1.57.27/115.1.57.24/brave_installer-delta-x64.exe)
6. Enter the following in the command prompt:
        - set BraveSoftwareUpdateIsMachine=1
7. Execute the delta installer in the same command prompt for beta. For example by typing:
          - C:\Users\mseel\Downloads\brave_installer-delta-x64.exe --chrome-beta
8. Start Brave (without internet)
9. verify updates via brave://setting/help
10. Repeat steps 5 - 7 for the [delta installer to go from Brave 1.57.27 to 1.57.33](https://updates-cdn.bravesoftware.com/delta/Brave-Browser-Beta/x64-be/win/115.1.57.33/115.1.57.33/brave_installer-delta-x64.exe)
11. Start Brave (without internet)
12. verified brave updates via brave://settings/help 
13. verify the logs in C:\ProgramData\BraveSoftware\Update\Log\BraveUpdate.log
14. verify `brave_installer-delta-x64.exe` in C:\Users\mseel\AppData\Local\Temp\chromium_installer.log

Actual Results:

  - When Brave started without internet, Brave is updated to `1.57.27` & `1.57.33` which is shown `brave://version`. However, `brave://settings/help` shows an error `Unable to connect to Internet` 
  - After connected to internet, Brave was successfully updated

step 1 | step 6| step 8 | step 9 | Step 10 | Step 11 | Step 12 | ex | Step 13 | Step 14 
--- | --- | --- | --- | --- | --- | ----- | ----- | ---- | -----
<img width="487" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/b1f55b73-1a09-43ca-8fd3-0fa35f02bd9c">|<img width="487" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/35aef237-9c8c-40fa-8c52-aeb901a5b729">|<img width="487" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/e4988449-a5e8-4c36-9ace-aec7bb986c88">|<img width="487" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/2eecc640-3cff-43f9-94f4-e723dce7e8e4">|<img width="487" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/c3d78421-9d39-4b34-a54d-95655902fc65">|<img width="644" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/04cd6900-4e25-433d-a9b4-e50796e4bda8">|<img width="487" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/3f08eee3-1665-4b91-a331-bcec9a3afe3d">|<img width="642" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/dbe8ba8e-4355-46a5-b931-9cb586b8854b">|<img width="487" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/815716e6-4c01-4f3f-b817-931de027efc9">|<img width="709" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/676219dd-9169-4776-bb2d-28d377187d34">

**Comment by MadhaviSeelam** [comment]
@mherrmann so the update is successful without connecting to internet which was verified via brave://version.  However, when I checked via brave://settings/help, got an error `Unable to connect to Internet` (which is expected I suppose) 
No errors are shown this time in `chromium_installer.log` & `BraveUpdate.log` files

**Comment by mherrmann** [comment]
@MadhaviSeelam yes, `Unable to connect to Internet` is expected. It seems like everything worked now. Thank you for checking again! 🙏

**Comment by MadhaviSeelam** [comment]
@GeetaSarvadnya  I am yet verify Win arm64.  When you get a chance, please test this issue on Win 10.

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.57.35 Chromium: 115.0.5790.171 (Official Build) beta (64-bit)
-- | --
Revision | 776897328898241b35b83878040730e73e749c06
OS | Windows 10 Version 22H2 (Build 19045.3208)
```

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.57.27 Chromium: 115.0.5790.114 (Official Build) beta (arm64)
-- | --
Revision | 18977fb43f693d5a8deeb48bd1cfa52651d3f73e
OS | Windows 11 Version 22H2 (Build 22621.1992)
```

Verified with public beta releases   1.57.27 --> 1.57.33 -->  1.57.35

1. Install Brave 1.57.27 using it's offline installer, [BraveBrowserStandaloneBetaSetupArm64.exe] https://github.com/brave/brave-browser/releases/download/v1.57.27/BraveBrowserStandaloneBetaSetupArm64.exe
2. Accept the UAC prompt to perform a system-wide installation.
3. Close Brave and disconnect from internet so Brave doesn't accidentally get updated.
4. Open a Windows command prompt with Administrator privileges (right-click->"Run as Administrator").
5. Download the [delta installer to go from Brave 1.57.27 to 1.57.33](https://updates-cdn.bravesoftware.com/delta/Brave-Browser-Beta/arm64-be/win/115.1.57.33/115.1.57.27/brave_installer-delta-arm64.exe)
6. Enter the following in the command prompt:
        - set BraveSoftwareUpdateIsMachine=1
7. Execute the delta installer in the same command prompt for beta. For example by typing:
          - C:\Users\mseel\Downloads\brave_installer-delta-arm64.exe --chrome-beta
8. Start Brave (without internet)
9. updates via brave://setting/help failed as the internet is off 
10. verified the new updated version via brave://version
11. Repeat steps 5 - 7 for the [delta installer to go from Brave 1.57.33 to 1.57.35](https://updates-cdn.bravesoftware.com/delta/Brave-Browser-Beta/arm64-be/win/115.1.57.35/115.1.57.33/brave_installer-delta-arm64.exe)
12. Start Brave (without internet)
13. updates via brave://setting/help failed as the internet is off 
14. verified the new updated version via brave://version
15. verify the logs in C:\ProgramData\BraveSoftware\Update\Log\BraveUpdate.log
16. verify `brave_installer-delta-x64.exe` in C:\Users\mseel\AppData\Local\Temp\chromium_installer.log
17. connected to internet, opened brave://settings/help and no errors shown  

step 1 | step 6-7 | step 9 | step 10 | step11 | step 14 | step 15 | step 16 | step 17 
--- | ---- | ---- | ---- | ---- | ----- | ---- | ----  | ------
<image width ="700" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/36b02fc7-b47b-428e-b2ec-3507bb7e53b9">|<image width ="700" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/fc53faca-6f59-4897-9a1e-c6d3fdd52e0e">|<image width ="700" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/3e82c142-1c7d-4628-9cd2-4c05456f077c">|<image width ="700" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/39a70383-339d-4d05-a450-c3c3dc67a3f5">|<img width="405" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/a2caa738-de30-4254-a91a-d60c77eb3784">|<image width ="700" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/f3e27642-dcd6-4f5f-903b-f62a96a049ee">|<image width ="700" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/cbdc4c0e-9b70-4ce6-a268-ebbace4546ca">|<image width ="700" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/cfb3a90a-566a-4a58-b0ff-4b68f68a0286">|<image width ="700" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/495fd19d-1d96-4b80-9759-f026ba01136f">|<img width="461" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/469199c7-39d9-4bc2-9be4-b9527ff08cad">

**Comment by MadhaviSeelam** [comment]
@mherrmann Delta updates are failing for Per-user installs for both Win 11 x64 & Win arm64.  
(However, on-demand updates were successful in Win 11 x64 but they are failing as well in Win arm64. Currently this is a known issue as it was found via #31696 testing. Will file an issue for it) 

Win 11 x64 -Per- User Install - Failed - https://github.com/brave/brave-browser/issues/30748#issuecomment-1661234180 (Please see actual results) 
Win arm64 - Per-user Install - Failed - https://github.com/brave/brave-browser/issues/30748#issuecomment-1666244554 - (Please see actual results)

**Comment by mherrmann** [comment]
@MadhaviSeelam thank you for checking this. I need to aplogise: The instructions were not correct for per-user installations. For per-user installations, we want to use a normal command prompt, not an Administrator command prompt, and we should not set `BraveSoftwareUpdateIsMachine=1`. Your replication steps work for me with these adjustments. Can you check whether they work for you too? Sorry for the trouble.

**Comment by GeetaSarvadnya** [comment]
@MadhaviSeelam I have done testing on Windows 10 x64, please add the QA pass label once you're done with the per-user installations on windows 11. Thanks!

**Comment by MadhaviSeelam** [comment]
@mherrmann: Followed your modified test steps for Per-user install on both Win 11 x64 & Win arm64. 
i.e. 

- Open normal command prompt (without admin)
- Do not set `BraveSoftwareUpdateIsMachine=1` 
- run `C:\Users\...\Downloads\brave_installer-delta-arm64.exe --chrome-beta`

Verified with public beta releases 1.57.27 --> 1.57.33 --> 1.57.35.  
However, I am still seeing some messages in the logs as below.  Not sure if these are expected.|

`C:\Users....\AppData\Local\Temp\chromium_installer.log`

- Failed creating a fire rules. Continuing with install.
- Failed to create Software/Microsoft\MediaPlayer\ShimInclusionList
- Could not add Chrome to media player inclusion list

<image width = "500" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/720798f8-7e82-4346-933d-d50ca8258201">

`C:\ProgramData\BraveSoftware\Update\Log\BraveUpdate.log` 

- Elevated metainstaller failed` 

<image width = "500" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/476cf54c-6e5d-4019-b7d8-2a0f132127e8">

Additionally `Main failed` entry is shown in `C:\ProgramData\BraveSoftware\Update\Log\BraveUpdate.log` .  However, this entry is now shown when installed with Network/WiFi is on for Machine-wide installs
 
<image width = "500" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/0239eb93-3f41-45d6-82ab-e4c8cea44a5d">

**Comment by mherrmann** [comment]
Thank you @MadhaviSeelam. Do you see the correct versions in `brave://version`?

**Comment by MadhaviSeelam** [comment]
@mherrmann Yes. I see correct versions. (Verified logs in `C:\Users....\AppData\Local\Temp\chromium_installer.log` and in `brave://version` after each update)

**Comment by mherrmann** [comment]
@MadhaviSeelam great, thanks. As long as the correct version is shown in `brave://version`, then I don't consider the log files important.

**Comment by MadhaviSeelam** [comment]
@mherrmann sounds good.  QA passing this issue.
