### ISSUE TITLE
Selecting account in panel is broken

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#30740]
Could not change selected account after https://github.com/brave/brave-core/pull/18564

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.57.18 Chromium: 115.0.5790.98 (Official Build) beta (64-bit)
-- | --
Revision | `d515871a6c6df7d2843e755c8b7dda9b744f26d6`
OS | Windows 11 Version 22H2 (Build 22621.1992)

- Verified steps from issue description
- Verified able to select accounts via panel

https://github.com/brave/brave-browser/assets/17010094/34a0f166-879a-4164-bfff-5650d7128c7d
