### ISSUE TITLE
Brave Ads should not redeem unblinded payment tokens after ~1 minute for fresh installs after joining Brave Rewards

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#30742]
## Steps to Reproduce

   1. Fresh install
   2. Join Brave Rewards

## Actual result:

Unblinded payment tokens are redeemed after ~1 minute

## Expected result:
Should redeem unblinded payment tokens after ~24 hours

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.57.27 Chromium: 115.0.5790.114 (Official Build) beta (64-bit) 
-- | --
Revision | 18977fb43f693d5a8deeb48bd1cfa52651d3f73e
OS | Ubuntu 18.04 LTS

Verified test plan from the description and https://github.com/brave/brave-core/pull/18928

<details>

Verified redeeming unblinded payment tokens is not triggered after 1 minute after joining rewards
Verified redeeming unblinded payment tokens is not triggered after 24h

</details>
