### ISSUE TITLE
NFT Details Send button doesn't have Pointer

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#30755]
## Description 

The NFT Details `Send` button should have `cursor: pointer` declared.

## Steps to Reproduce

   1. Go to the `NFT's` view and select and `NFT`
   2. The `Send` button in the `header` does not have a `pointer` for the cursor.

## Actual result:

https://github.com/brave/brave-browser/assets/40611140/f599cc13-068f-46a6-b2b6-a1d90eecba99

## Expected result:
`Send` button should have a `Pointer` for the `cursor`

https://github.com/brave/brave-browser/assets/40611140/32cc9c7a-8759-4d7e-bc27-ddcf70f5a108

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.53.100 Chromium: 114.0.5735.133 (Official Build) beta (64-bit)
-- | --
Revision | `fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}`
OS | Linux

- Verified steps from [brave/brave-core#18722](https://github.com/brave/brave-core/pull/18722)
- Verified the `Send` button in the `header` has a `pointer` for the cursor.

https://github.com/brave/brave-browser/assets/17010094/d573e7f7-f498-44e7-9160-5628a554470c


---------------------

**Verification passed on**

Brave | 1.53.100 Chromium: 114.0.5735.133 (Official Build) beta (64-bit)
-- | --
Revision | `fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}`
OS | Windows 11 Version 22H2 (Build 22621.1848)

- Verified steps from [brave/brave-core#18722](https://github.com/brave/brave-core/pull/18722)
- Verified the `Send` button in the `header` has a `pointer` for the cursor.

https://github.com/brave/brave-browser/assets/17010094/43404b53-d0e5-496a-b7d3-ee8cedcb7626


---------------------

**Verification passed on**

Brave | 1.53.100 Chromium: 114.0.5735.133 (Official Build) beta (64-bit)
-- | --
Revision | `fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}`
OS | macOS Version 13.0 (Build 22A380)

- Verified steps from [brave/brave-core#18722](https://github.com/brave/brave-core/pull/18722)
- Verified the `Send` button in the `header` has a `pointer` for the cursor.

https://github.com/brave/brave-browser/assets/17010094/2fbdc975-d370-45fd-9fc5-6b6cb5b1042c
