### ISSUE TITLE
Add Group By option to Portfolio Filters and Display Settings

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#30753]
## Description 

We need to add a `Group By` option to the Portfolio Filters and Display Settings modal

![Screenshot 26](https://github.com/brave/brave-browser/assets/40611140/eb30985b-50c4-461e-915c-d702d79a0f5e)

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/30496#issuecomment-1651552993
