### ISSUE TITLE
Button colors/styles in `Dark` mode need to be like mockup

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#30757]
## Description 

Button colors/styles in `Dark` mode need to be like mockup

Discovered while testing https://github.com/brave/brave-browser/issues/29349

## Steps to Reproduce

1. installed `1.53.76`
2. launched Brave
3. opened `brave://flags`
4. set `brave://flags/#brave-commands` to `Enabled`
5. clicked `Relaunch`
6. opened `brave://settings/system/shortcuts`
7. switched to `Dark` mode via `Brave Colors` in `brave://settings/appearance`

## Actual result:

![image (1)](https://github.com/brave/brave-browser/assets/387249/767690bf-a1d5-4531-8c26-07101c123d68)

## Expected result:

From [Figma](https://www.figma.com/file/tLXWGCpNoiJxDZDdpfordj/Desktop-Settings?type=design&node-id=3761%3A60146&t=B3MxvBG62dG94PJB-1):

![image](https://github.com/brave/brave-browser/assets/387249/967ba55f-2d02-43a5-b4f9-a99ae111bb1c)

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.53.76 Chromium: 114.0.5735.90 (Official Build) beta (64-bit)
-- | --
Revision | 386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}
OS | Windows 10 Version 22H2 (Build 19045.3031)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @aguscruiz @rebron @fallaciousreasoning @brave/qa-team

**Comment by stephendonner** [comment]
🎉

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.53.102 Chromium: 114.0.5735.133 (Official Build) (x86_64)
-- | --
Revision | fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}
OS | macOS Version 13.4.1 (Build 22F82)
```
