### ISSUE TITLE
Enable sticky pinned tabs by default 

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#30761]
The default value was disabled. Now we think it's good to go.

---

### Verification steps
* Go to brave://flags/#brave-vertical-tabs-stick-pinned-tabs and set it "Default"
* Feature described from https://github.com/brave/brave-browser/issues/29935 should work, and other vertical tabs features should work as expected.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.54.75 Chromium: 115.0.5790.32 (Official Build) beta (64-bit)
-- | --
Revision | f9b78cf410ecd5b372310ef25a12ef456c77d90f-refs/branch-heads/5790@{#724}
OS | Windows 11 Version 22H2 (Build 22621.1848)
```
