### ISSUE TITLE
Content labeling Accessibility issue

### ISSUE THREAD

**Issue by sujitacharya2005** [brave/brave-browser#30763]
Brave Version : Brave nightly 1.54.25

![image](https://user-images.githubusercontent.com/32419898/242786951-0ddc2c0e-98bc-4d7a-bcee-fec785da0759.png)

![image](https://user-images.githubusercontent.com/32419898/242787134-1a4370c1-7adf-400e-8462-ea30308b2b89.png)

![image](https://github.com/brave/brave-browser/assets/32419898/8e9dc8bd-fa28-4ca4-87fb-e9d3a7c32992)

![image](https://github.com/brave/brave-browser/assets/32419898/47b96985-69f2-41fa-b65c-5b6f98d2923d)

![image](https://github.com/brave/brave-browser/assets/32419898/ac9a685c-eaf8-47dc-9c70-24476317b9ae)

_Originally posted by @sujitacharya2005 in https://github.com/brave/roadmap/issues/706#issuecomment-1571962958_

**Comment by Uni-verse** [comment]
In Progress on `Samsung Galaxy S21` & `Samsung Galaxy Tab S7` using version(s):

```
Brave	1.57.35 Chromium: 115.0.5790.171 (Official Build) beta (64-bit) 
Revision	776897328898241b35b83878040730e73e749c06
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
