### ISSUE TITLE
Cannot send Optimism transactions

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#30776]
When I try to do an Optimism transfer from the Send page, I get the following error in the console. The strange thing is that Optimism does not support EIP-1559, but we tried creating a Type-2 transaction. Other networks might be impacted too.

```
Sending unapproved transaction failed:
  from=0xa92D461a9a988A7f11ec285d39783A637Fdd6ba4
  err=Failed to create Eth transaction: Failed to get the gas fees for EIP-1559 transaction ::payload:: {
  "network":{
    "chainId":"0xa",
    "chainName":"Optimism",
    "blockExplorerUrls":[
      "https://optimistic.etherscan.io"
    ],
    "iconUrls":[
      
    ],
    "activeRpcEndpointIndex":0,
    "rpcEndpoints":[
      {
        "url":"https://mainnet-optimism.brave.com/"
      }
    ],
    "symbol":"ETH",
    "symbolName":"Ether",
    "decimals":18,
    "coin":60,
    "isEip1559":false
  },
  "fromAccount":{
    "accountId":{
      "coin":60,
      "keyringId":0,
      "kind":0,
      "address":"0xa92D461a9a988A7f11ec285d39783A637Fdd6ba4"
    },
    "accountType":"Primary",
    "address":"0xa92D461a9a988A7f11ec285d39783A637Fdd6ba4",
    "hardware":null
  },
  "to":"0xbc5d6cd6f7225bfCCc58F7B75AaeB641ECCD5419",
  "value":"0x5af3107a4000"
}
```

Reproduces on 1.54.x. Does not reproduce on 1.52.x.

**Comment by kjozwiak** [comment]
The above requires `1.53.103` or higher for `1.53.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.53.104 Chromium: 115.0.5790.40 (Official Build) (64-bit)
-- | --
Revision | `071c9ddea889c3c7887daf4eac13fed72d4fff62-refs/branch-heads/5790@{#979}`
OS | Windows 11 Version 22H2 (Build 22621.1848)

- Verified steps from [brave/brave-core#18968](https://github.com/brave/brave-core/pull/18968)
- Verified able to Send/Swap on Optimism
- Verified transactions is submitted as an EIP-1559 transaction

https://github.com/brave/brave-browser/assets/17010094/30e908ef-5f2a-4d46-8873-41418a6b9d45

**Comment by kjozwiak** [comment]
The above requires `1.52.130` or higher for `1.52.x` verification 👍 Removing the `QA Pass` label as the above will need to be rechecked with `1.52.x`.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.52.130 Chromium: 114.0.5735.198 (Official Build) (64-bit)
-- | --
Revision | `c3029382d11c5f499e4fc317353a43d411a5ce1c-refs/branch-heads/5735@{#1394}`
OS | Linux

 
- Verified steps from [brave/brave-core#18968](https://github.com/brave/brave-core/pull/18968)
- Verified able to Send/Swap on Optimism
- Verified transactions is submitted as an EIP-1559 transaction

https://github.com/brave/brave-browser/assets/17010094/980bb3a1-7aa6-4ec8-b6f0-2492e6101908
