### ISSUE TITLE
In a non-connected state, the link `brave://rewards#monthly-statements` opens up the monthly statement which doesn't exist

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#30771]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/16628
In a non-connected state, the link `brave://rewards#monthly-statements` opens up the monthly statement which doesn't exist
## Steps to Reproduce

   1. Clean profile 1.52.x
   2. Enable rewards and don't connect any custodian
   3. Open a new tab and enter brave://rewards#monthly-statements
   4. `Monthly statement` modal popup is opened

## Actual result:

In a non-connected state, the link `brave://rewards#monthly-statements` opens up the monthly statement which doesn't exist

## Expected result:
Monthly statement modal popup should not open as it doesn't exist in a non-connected state

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.53.76 Chromium: 114.0.5735.90 (Official Build) beta (64-bit)
-- | --
Revision | 386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}
OS | Windows 10 Version 22H2 (Build 19045.2965)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @mkarolin @Miyayes

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.57.6 Chromium: 115.0.5790.75 (Official Build) beta (x86_64)
-- | --
Revision | 3433e4d513e8454ba0243deea3d53693661dc0c3-refs/branch-heads/5790@{#1430}
OS | macOS Version 13.4.1 (Build 22F82)
```
