### ISSUE TITLE
Migrate to RTK for querying balances

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#30779]
|Community|https://community.brave.com/t/macos-computer-crashes-when-trying-to-send-crypto-with-brave-wallet/485399/3|
-|-

Some users have been reporting very high CPU usage since at least 1.51.x, but it's been a major problem all along. https://github.com/brave/brave-core/pull/18735 brings some significant performance improvements. We would like to extend this work beyond the panel to speed up the wallet page.

The problem is particularly bad when there a lot of accounts and custom networks. Since we refresh balances periodically, this leads to spikes in CPU usage like this:

![image](https://github.com/brave/brave-browser/assets/3684187/fab3eafb-906a-4b76-891f-64927c50d29f)

### Definition of done

- [x] No more `await Promise.all(...)` for balance queries.
- [x] No more `tokenBalanceRegistry` in the legacy Redux store.
- [x] Remove the custom optimisations done in Swap, and use the api slices for it.
- [x] No more or reduced spiking in CPU usage.
- [x] No more use of `useBalanceUpdater()` hook.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.58.109 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | a4ad1fcdb550daf076384dbb280ae944274b3d35
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#19337](https://github.com/brave/brave-core/pull/19337)
- Verified able to load token balances in Portfolio
- Verified able to load token prices in Portfolio
- Verified able to load pricing history (graph) in Portfolio
- Verified able to load fiat balances in Accounts
- Verified able to load token balances in Swap
- Verified on both panel V2 and Wallet page

https://github.com/brave/brave-browser/assets/17010094/e75f06e0-5541-4d9b-b086-65274c736942
