### ISSUE TITLE
OnNetworkListChanged is incorrectly fired on switching to custom networks

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#30778]
The **`BraveWalletService::OnNetworkListChanged`** event is fired merely upon switching to a custom network. The reason is not clear, but this makes switching to custom networks a painfully slow experience. One of the reasons zksync is unusable (assuming #30473 is fixed).

https://github.com/brave/brave-core/blob/0a1a304fdb27e2063af3d817cbf948c08300b682/components/brave_wallet/browser/brave_wallet_service.cc#L210-L213

**Comment by kjozwiak** [comment]
The above requires `1.52.124` or higher for `1.52.x` verification 👍

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/30473#issuecomment-1588564322

**Comment by kjozwiak** [comment]
> Verified as part of [#30473 (comment)](https://github.com/brave/brave-browser/issues/30473#issuecomment-1588564322). Confirmed with @onyb verification is sufficient on Desktop as the fix is on core side.

Adding the `QA Pass - Android ARM` in that case so we can get this off our QA verification list.
