### ISSUE TITLE
Account transactions not shown within activity panel view

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#30780]
## Description 

Regression caused by [feat: deprecate uncached transaction state](https://github.com/brave/brave-core/pull/18379#top)

Viewing the activity panel never shows the account's/network's transactions

## Steps to Reproduce

   1. Submit a transaction
   2. open the panel
   3. click the activity tab button
   4. view the activity panel screen

## Actual result:

No transactions are shown

## Expected result:
All transactions for the selected account + network should be listed

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Master

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.57.27 Chromium: 115.0.5790.1314 (Official Build) beta (64-bit)
-- | --
Revision | `18977fb43f693d5a8deeb48bd1cfa52651d3f73e`
OS | Windows 11 Version 22H2 (Build 22621.1992)

- Verified steps from [brave/brave-core#18740](https://github.com/brave/brave-core/pull/18740)
- Verified Account transactions are shown in Activity panel on the panel 
- Encountered [#31982](https://github.com/brave/brave-browser/issues/31982)
