### ISSUE TITLE
[Android] Add option to enable/disable private mode download confirmation bubble

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#30784]
### Summary
We have users complaining about the download confirmation bubble in private mode. 

**Bubble Example:**

| Download confirmation |
| ------------- |
| ![Screenshot_20230602-121754](https://github.com/brave/brave-browser/assets/5146988/a0ced4c5-64f9-451b-be9c-153df1a0a40e) | 

**For context**
https://bravesoftware.slack.com/archives/C0YL5KMA8/p1685650270998319

### Requirements
We should disable the bubble by default and add an option in download settings to allow users to switch the bubbles on/off.

**Comment by anthonypkeane** [comment]
A "dont show again" box might work but lets work it through with design.
