### ISSUE TITLE
Ask where to save each file before downloading should be enabled by default

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#308]
## Description 
Ask where to save each file before downloading should be enabled by default

 ## Actual result:

Default setting is off

## Expected result:
Should match browser-laptop behaviour to prompt user to choose location by default

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows 7
