### ISSUE TITLE
gn patches break `gn gen` for ios

### ISSUE THREAD

**Issue by bridiver** [brave/brave-browser#3080]
## Description 
Running `gn gen` for ios causes dependency errors that make it impossible to run for ios. Resetting the chromium repo fixes the issue so we need to find the offending patches and fix them.

**Comment by kylehickinson** [comment]
Patch for Cargo.py no longer required. Issue will be fixed on challenge-bypass-ristretto-ffi end: https://github.com/brave-intl/challenge-bypass-ristretto-ffi/pull/27

**Comment by bridiver** [comment]
leveldatabase also removed here https://github.com/brave/brave-core/pull/1464
