### ISSUE TITLE
Make sidebar panel resizable

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#30808]

**Comment by LaurenWags** [comment]
The above requires `1.57.7` or higher for `1.57.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.57.8 Chromium: 115.0.5790.75 (Official Build) beta (64-bit)
-- | --
Revision | 77bffd419b7e89d7e666c9695e7fa0d1d0367a99
OS | Windows 11 Version 22H2 (Build 22621.1992)
```
1. Installed 1.57.8
2. launched Brave
3. clicked on sidebar toolbar button 
4. resized side panel by grabbing side panel border 
5. closed and relaunched Brave. 
6. clicked sidebar toolbar button again
7. confirmed the resized side panel persisted. 
8. enable vertical tabs 
9. confirmed able to resize both vertical tab panel and side panel 
10. verified sidebar doesn't occupy whole content page
11. opened original window, Private window & new Private window with Tor
12. confirmed all three reflected original window width of the side panel
13. resized Private window and confirmed original window, new window & new Private window with Tor reflects the resized width of the side panel


step 3 | step 4 | step 7 | step 9 | new window | private window | Tor window | step 13a | step 13b
------- | ------- | -------- | -------- | ------- | -------- | --------- | ----- | ------ 
<image width ="600" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/eec5d42b-a104-4490-a0e9-ef1955f55981">|<image width ="600" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/b5b5c64a-5745-4f03-ab8b-df5eb4357972">|<image width ="600" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/ee852b31-282f-47d5-bc06-397324488e2c">|<image width ="600" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/efcd2625-4c0c-4cbe-8bdd-5ce6e4cdae9c">|<image width ="400" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/2d88c510-fd0f-438a-acad-ae63d7747bed">|<image width ="400" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/81ed8dec-664b-4ca0-9398-d5a3673168a9">|<image width ="400" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/994daebd-8673-49bf-ab07-7bff871e952a">|<image width ="500" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/4ed29e37-04b7-49ae-bfdc-e84916a244ef">|<image width ="500" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/24b17079-7beb-4428-baa9-e690be2d97c2">

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave	1.57.33 Chromium: 115.0.5790.114 (Official Build) beta (64-bit) 
Revision	86b4ea1d70ce73c4468d84cc8277f1f9de14b8bc
OS	Linux
```
### Steps:
1. installed `1.57.x`
2. launched Brave
3. clicked on sidebar toolbar button
4. resized side panel by grabbing side panel border
5. closed and relaunched Brave.
6. clicked sidebar toolbar button again
7. confirmed the resized side panel persisted.
8. enable vertical tabs
9. confirmed able to resize both vertical tab panel and side panel
10. verified sidebar doesn't occupy whole content page
11. opened original window, Private window & new Private window with Tor
12. confirmed all three reflected original window width of the side panel
13. resized Private window and confirmed original window, new window & new Private window with Tor reflects the resized width of the side panel

step 3 | step 4 | step 7 | step 9 | new window | private window | Tor window | step 13a | step 13b | step 13c
-------|-------|--------|-------|--------------|----------------|-------------|---------|----------|---------
