### ISSUE TITLE
non-verified sites are retained in AC table after upgrade to 1.53.x

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#30818]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/29393
non-verified sites are retained in AC table after upgrade to 1.53.x
## Steps to Reproduce

   1. Clean profile 1.52.x
   2. Connect custodian
   3. Add few verfied  + non verified creators to AC table
   4. Upgrade the profile to 1.53.x
   5. non-verified sites are retained in AC table after upgrade to 1.53.x
   6. uphold.com is added to AC table with attention 100% which is wrong in an upgraded profile

## Actual result:

non-verified sites are retained in AC table after upgrade to 1.53.x
![image (4)](https://github.com/brave/brave-browser/assets/38657976/1768648a-7503-4434-8730-456a87a874c2)

Also
![image](https://github.com/brave/brave-browser/assets/38657976/16e118c4-6ef1-43f6-8be6-9c8b2bf852e4)

## Expected result:

non-verified sites should not be retained in AC table after upgrade to 1.53.x as `Show non verified site in list` toggle is removed from 1.53.x
## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.53.76 Chromium: 114.0.5735.90 (Official Build) beta (64-bit)
-- | --
Revision | 386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}
OS | Windows 10 Version 22H2 (Build 19045.2965)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @zenparsing @Miyayes

**Comment by GeetaSarvadnya** [comment]
@zenparsing non-verified sites needs to be removed from the `Excluded list` also in an upgraded profile 1.53.x.

![image](https://github.com/brave/brave-browser/assets/38657976/e6b586c0-c5f1-4b9e-989c-074b6446e47d)

**Comment by GeetaSarvadnya** [comment]
Reproduced the issue on `Vivo X70 Pro version 12` running `Bravemonoarm64.1pk_1.53.83`

**Comment by kjozwiak** [comment]
The above requires `1.53.109` or higher for `1.53.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave | 1.53.110 Chromium: 115.0.5790.56 (Official Build) (64-bit)
-- | --
Revision | ebcfb87c1393f36955cfa2f6451a1767e3dc3ee5-refs/branch-heads/5790@{#1193}
OS | Windows 10 Version 22H2 (Build 19045.3086)

```
<details>
<summary>Reproduced the issue upgrading from 1.52.126 --> 1.53.104</summary>

1. Installed 1.52.126 w/ staging env flags
2. Close and relaunch to pull griffin
3. Enable Rewards, connect a custodian
4. Visit some verified and non-verified sites to populate AC list
5. Upgrade to 1.53.104
6. Open a new tab and visit a site (I used a non-verified creator) for minimum 10s
7. Open brave://rewards
--> AC list percentages are incorrect

1.52.126 | 1.53.104
--- | ---


</details>

<details>
<summary>Scenario A - AC list contains both verified and non-verified creators prior to upgrade - </summary>

Case 1
1. Installed 1.52.126 w/ staging env flags
2. Close and relaunch to pull griffin
3. Enable Rewards, connect a custodian
4. Visit 1 verified creator and a couple non-verified sites to populate AC list
5. Upgrade to 1.55.15
6. Open a new tab and visit a site (I used a non-verified creator) for minimum 10s
7. Open brave://rewards
8. Confirmed AC list percentages are correct

Step 4 | Step 8
--- | ---


Case 2
1. Installed 1.52.126 w/ staging env flags
2. Close and relaunch to pull griffin
3. Enable Rewards, connect a custodian
4. Visit a couple verified creators and a couple non-verified sites to populate AC list
5. Upgrade to 1.55.15
6. Open a new tab and visit a site (I used a non-verified creator) for minimum 10s
7. Open brave://rewards
8. Confirmed AC list percentages are correct

Step 4 | Step 8
--- | ---
>

Note on above cases:

After upgrade to 1.55.x, if you don't visit a site and navigate straight to brave://rewards, your AC % values will be incorrect. This was discussed via https://bravesoftware.slack.com/archives/CHGKGMHDJ/p1687884257057629?thread_ts=1687807360.080769&cid=CHGKGMHDJ. Per this discussion, in order to trigger the AC % recalculation, visiting either a verified creator OR a never-before visited non-verified creator will suffice. Visiting a non-verified creator who was in your AC list prior to upgrade will not trigger this recalculation. See above thread for more details.

</details>

<details>
<summary>Scenario B - AC list contains only non-verified creators prior to upgrade - </summary>

1. Installed 1.52.126 w/ staging env flags
2. Close and relaunch to pull griffin
3. Enable Rewards, connect a custodian
4. Visit only a few non-verified sites to populate AC list
5. Upgrade to 1.55.15
6. Navigate to brave://rewards and confirm AC list is blank
7. Open a new tab and visit a verified creator for ~10s
8. Open brave://rewards
9. Confirm creator is listed in AC and percentage is as expected

Step 4 | Step 6 | Step 9
--- | --- | ---


</details>

<details>
<summary>Scenario C - AC list contains only verified creators prior to upgrade - </summary>

1. Installed 1.52.126 w/ staging env flags
2. Close and relaunch to pull griffin
3. Enable Rewards, connect a custodian
4. Toggle "Show non-verified sites in list" off
5. Visit only a few verified sites to populate AC list
6. Upgrade to 1.55.15
7. Navigate to brave://rewards and confirm AC list is showing as it was in step 5
8. Open a new tab and visit any verified creator (new or already in AC list) for ~10s
9. Open brave://rewards
10. Confirm creator is listed in AC and percentage is as expected

Step 4 | Step 5 | Step 7 | Step 10
--- | --- | --- | ---


</details>

<details>
<summary>Scenario D - AC off prior to upgrade - </summary>

1. Installed 1.52.126 w/ staging env flags
2. Close and relaunch to pull griffin
3. Enable Rewards, connect a custodian
4. Toggle AC off
5. Upgrade to 1.55.15
6. Visit brave://rewards and confirm AC still off
7. Visit a verified creator for ~10s
8. Visit brave://rewards and confirm AC still off

Step 4 | Step 6 | Step 8
--- | --- | ---


</details>

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Vivo x70 Pro version 12` running `Bravemonoarm64.apk_1.56.1`

<details>
<summary>Scenario A - AC list contains both verified and non-verified creators prior to upgrade - </summary>

Case 1
1. Installed 1.52.126 w/ staging env flags
2. Close and relaunch to pull griffin
3. Enable Rewards, connect a custodian
4. Visit 1 verified creator and a couple non-verified sites to populate AC list
5. Upgrade to 1.53.110
6. Open a new tab and visit a site (I used a non-verified creator) for minimum 10s
7. Open brave://rewards
8. Confirmed AC list percentages are correct

Step 4 | Step 8
--- | ---



Case 2
1. Installed 1.52.126 w/ staging env flags
2. Close and relaunch to pull griffin
3. Enable Rewards, connect a custodian
4. Visit a couple verified creators and a couple non-verified sites to populate AC list
5. Upgrade to 1.53.110
6. Open a new tab and visit a site (I used a non-verified creator) for minimum 10s
7. Open brave://rewards
8. Confirmed AC list percentages are correct

Step 4 | Step 8
--- | ---


Note on above cases:

After upgrade to 1.53.110, if you don't visit a site and navigate straight to brave://rewards, your AC % values will be incorrect. This was discussed via https://bravesoftware.slack.com/archives/CHGKGMHDJ/p1687884257057629?thread_ts=1687807360.080769&cid=CHGKGMHDJ. Per this discussion, in order to trigger the AC % recalculation, visiting either a verified creator OR a never-before visited non-verified creator will suffice. Visiting a non-verified creator who was in your AC list prior to upgrade will not trigger this recalculation. See above thread for more details.

</details>

<details>
<summary>Scenario B - AC list contains only non-verified creators prior to upgrade - </summary>

1. Installed 1.52.126 w/ staging env flags
2. Close and relaunch to pull griffin
3. Enable Rewards, connect a custodian
4. Visit only a few non-verified sites to populate AC list
5. Upgrade to 1.53.110
6. Navigate to brave://rewards and confirm AC list is blank
7. Open a new tab and visit a verified creator for ~10s
8. Open brave://rewards
9. Confirm creator is listed in AC and percentage is as expected

Step 4 | Step 6 | Step 9
--- | --- | ---



</details>

<details>
<summary>Scenario C - AC list contains only verified creators prior to upgrade - </summary>

1. Installed 1.52.126 w/ staging env flags
2. Close and relaunch to pull griffin
3. Enable Rewards, connect a custodian
4. Toggle "Show non-verified sites in list" off
5. Visit only a few verified sites to populate AC list
6. Upgrade to 1.53.110
7. Navigate to brave://rewards and confirm AC list is showing as it was in step 5
8. Open a new tab and visit any verified creator (new or already in AC list) for ~10s
9. Open brave://rewards
10. Confirm creator is listed in AC and percentage is as expected

Step 4 | Step 5 | Step 7 | Step 10
--- | --- | --- | ---



</details>

<details>
<summary>Scenario D - AC off prior to upgrade - </summary>

1. Installed 1.52.126 w/ staging env flags
2. Close and relaunch to pull griffin
3. Enable Rewards, connect a custodian
4. Toggle AC off
5. Upgrade to 1.53.110
6. Visit brave://rewards and confirm AC still off
7. Visit a verified creator for ~10s
8. Visit brave://rewards and confirm AC still off

Step 4 | Step 6 | Step 8
--- | --- | ---


</details>
