### ISSUE TITLE
Sidebar's `Show on right` option should located first

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#30810]
As we made right-side as a default for sidebar position, `Show on right` should be located before `Show on left`.

<img width="720" alt="Screenshot 2023-06-05 at 2 07 12 PM" src="https://github.com/brave/brave-browser/assets/6786187/097cb82f-bd6c-4108-94ac-32eaa2db50e6">

**Comment by MadhaviSeelam** [comment]
Verifictaion `PASSED` using
```
Brave | 1.54.90 Chromium: 115.0.5790.56 (Official Build) beta (64-bit)
-- | --
Revision | ebcfb87c1393f36955cfa2f6451a1767e3dc3ee5-refs/branch-heads/5790@{#1193}
OS | Windows 11 Version 22H2 (Build 22621.1928)
```
Case 1: Fresh Install

1. Install 1.54.90
2. launch Brave
3. open `brave://settings/appearance`

#### Confirmed `Show on right` setting shows on top of `Show on left` setting and the sidebar is shown on the right

Case 2: Upgrade

1. Install 1.52.129
2. launch Brave
3. open brave://settings/appearance
4. verified `Show on left` setting position is on top of `Show on right` and is shown as default
5. enabled `Show Sidebar Always` from Hamburger menu and the sidebar is shown on left
6. rename the profile to `Brav-Browser-Beta`
7. relaunch Brave with 1.54.90 
8. verified brave://settings/appearance 

#### Confirmed `Show on right` setting position is reversed and shows on top of `Show on left` setting
#### Confirmed `Show on right` settings shown as default and Sidebar is shown on right

step 4-5 | step 8a | step 8b
--- | ---- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/a8b63d8d-0801-440e-a81f-3431a23acaf2)|![image](https://github.com/brave/brave-browser/assets/98358127/c7180aad-e566-47e6-967d-d71e990b6c8e)|![image](https://github.com/brave/brave-browser/assets/98358127/59ae23dc-3c74-4ed9-b354-6c01a8f420aa)
