### ISSUE TITLE
Tab separator is too thick

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#3081]
Consensus from @brave/design and some user feedback is that the 2dp border between tabs is too priminent. Althought that prominence is a feature to aid cognitive understanding of where the different tabs begin and end, it can also add to cognitive load.

**Comment by bbondy** [comment]
Bumping this to 0.61.x since it'll be included as part of a rebase conflict that will be included with the 73.0.3683.27 upgrade.

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.61.37 Chromium: 73.0.3683.39 (Official Build) beta (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

Used test plan from https://github.com/brave/brave-core/pull/1449. The tab separator has 1 px.

top: 0.61.37
bottom: 0.60.45
![image](https://user-images.githubusercontent.com/34715963/53377751-5c06b600-3963-11e9-9bd4-256375806a16.png)
