### ISSUE TITLE
Optional vertical tabs position to the right

### ISSUE THREAD

**Issue by sameyepatch** [brave/brave-browser#30812]
## Description 
Add an option to place the vertical tabs to the right.

## Steps to Reproduce
    1. Go to brave://settings/appearance
    2. Activate vertical tabs

## Actual result:
Vertical tabs get activated, placed to the left by default

## Expected result:
Activate vertical tabs, placed to the left by default, but give the option to place the vertical tabs bar to the right in the Appearance settings

## Brave version (brave://version info)
1.52.117 Chromium: 114.0.5735.90 (Official Build) (64-bit)

**Comment by JamesDAdams** [comment]
Yes please, it's better to the right for me :)

**Comment by bsclifton** [comment]
cc: @rebron

**Comment by bard** [comment]
Additional motivation: when tabs are minimized, hovering will cause them to appear and cover the most information-dense side of the page (at least in left-to-right languages), making it unreadable. (Try it on this page: they'll cover usernames and the beginning of every comment.)

If they were on the right side, one could look at the tab list and still access the web page content.

**Comment by kevineduardo** [comment]
I also need this

**Comment by micpub** [comment]
cmon, such a simple feature to implement takes so long...

**Comment by sangwoo108** [comment]
Applolgies, I've been working on other features. Let me find some time for working on this.

**Comment by bard** [comment]
Brilliant, going to switch to nightly for this, thank you @sangwoo108!

**Comment by kevineduardo** [comment]
Guys, don't waste your time with this, I just tried all the nightly builds available and no one of them has the feature, we will just have to wait another thousand years for this highly advanced features.

**Comment by sangwoo108** [comment]
Hi @kevineduardo , The feature has been merged but the nightly version was not released during the weekend. I believe it'd be released soon.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.63.101 Chromium: 120.0.6099.199 (Official Build) nightly (64-bit)
-- | --
Revision | 8d3f0a563e185b6a763cc8e210ab24775dfb9047
OS | Windows 11 Version 22H2 (Build 22621.2861)
```

1. Installed 1.63.101
2. launched Brave
3. opened `brave://settings/appearance` in a new tab
4. toggled "On" `Use vertical tabs`  
5. verified vertical tabs is enabled 
6. verified `Show on the left` option is selected by default 
7. selected `Show on the right` option

#### Confirmed vertical tabs strip positioned to the right

step 6 | step 7 
----- | -----
<img width="958" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/04bdaeb4-6e85-4dd0-8aa6-820daeedc7dd">|<img width="958" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/9cce84d1-7203-4e5a-90ce-3d817f6a8ad2">
