### ISSUE TITLE
"Show tab search button" resets when a new window is open 

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#30829]
## Description 

In Brave on macOS, if the `Show tab search button` option in `Settings --> Appearance --> Tabs` is toggled "off", the tab search button stops displaying as intended. However if a new window is opened, not only does the tab search button reappear, but the setting itself is toggled back "on" for both windows that are open. 

This option should persist across Windows and browsing sessions.

## Steps to Reproduce

Launch Brave

1. Go to `Settings --> Appearance --> Tabs`
2. Toggle `Show tab search button` option “off” so that the tab search button does not display in the top-right
3. Open a new browser window (`Cmd + N`)
4. Observe that the tab search button is now showing. Further, observe that the setting in the original window you opened is now toggled back “on”

## Reproduces how often: 

Every time

## Brave version (brave://version info)

[Version 1.52.117 Chromium: 114.0.5735.90 (Official Build) (arm64)](https://brave.com/latest/)

## Version/Channel Information:

In the Beta, Dev and Nightly builds, the same behavior happens, except for the option in Settings is not toggled back on (that is, it stays toggled "off"), but the button _does appear_. To clarify, for all builds other than Stable:
1. Go to `Settings --> Appearance --> Tabs`
2. Toggle `Show tab search button` option “off” so that the tab search button does not display in the top-right
3. Open a new browser window (`Cmd + N`)
4. Observe that the tab search button is now showing in the new window.
5. Close this window and observe that in the original window, the tab button is now showing, but the toggle option in `Settings` _stays_ "off"
6. 
## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by chunga2020** [comment]
I'm using version 1.52.117 on Arch Linux (linux kernel 6.3.5), and I experience similar behavior.  However, on my system, the tab button remains hidden in the original window

**Comment by sangwoo108** [comment]
I can't reproduce the preference part, but the button's visibility is definitely a regression from vertical tabs. I'm on it.

**Comment by kjozwiak** [comment]
The above requires `1.52.125` or higher for `1.52.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.52.125 Chromium: 114.0.5735.110 (Official Build) (64-bit)
-- | --
Revision | 1c828682b85bbc70230a48f5e345489ec447373e-refs/branch-heads/5735_90@{#13}
OS | Windows 10 Version 22H2 (Build 19045.2965)

```
- Confirmed that the `Show tab search button` off settings doesn't reset when a new window is opened

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.52.125 Chromium: 114.0.5735.110 (Official Build) (x86_64)
-- | --
Revision | 1c828682b85bbc70230a48f5e345489ec447373e-refs/branch-heads/5735_90@{#13}
OS | macOS Version 13.4 (Build 22F66)
```

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.52.125 Chromium: 114.0.5735.110 (Official Build) (64-bit)
-- | --
Revision | 1c828682b85bbc70230a48f5e345489ec447373e-refs/branch-heads/5735_90@{#13}
OS | Linux
```
Reproduced the issue in `1.52.122`. As the tab search button is hidden in the original but is shown in the new window when `Show tab search` button is toggle `Off`
![image](https://github.com/brave/brave-browser/assets/98358127/d4c2070e-b2cf-41b0-b0c9-b5bb7bd5bbe4)

Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/30829#issue-1742411141, verified that the search button was being removed correctly as per the following:


* ensured that toggling `Show tab search button` via `brave://settings/appearance` correctly removes the search button
  * ensured it's being removed from the current active window
  * ensured it's being removed from all other currently opened windows
  * ensured it's not being added when opening new windows
* ensured that the `Show tab search button` state is persistent (not being enabled/disabled when it shouldn't)
  * ensured that the `Show tab search button` state is persistent across several restarts

Show tab search button (off)  |  Show tab search button (on)
------  | -----
![Screenshot from 2023-06-13 12-19-11](https://github.com/brave/brave-browser/assets/98358127/786a7812-7f25-48f6-8e72-96c7258c3e1b) | ![Screenshot from 2023-06-13 12-28-35](https://github.com/brave/brave-browser/assets/98358127/c06534b9-65b5-4589-8427-0d71abe0faf5)

**Comment by Lhotka** [comment]
I am getting this issue. When I turn on vertical tabs, the button dissapears. Note I'm using Linux Mint, I don't get the issue on Windows 10.
