### ISSUE TITLE
Unable to log in to Bing Rewards with Brave

### ISSUE THREAD

**Issue by singhkays** [brave/brave-browser#3082]
## Description 
Unable to log in to Bing Rewards with Brave

## Steps to Reproduce

   1. Signed into outlook.com/Microsoft account
   2. Click sign in on the Bing.com rewards drop down
   

## Actual result:
![image](https://user-images.githubusercontent.com/6164178/51704757-b2807d80-1fce-11e9-9994-15cb2d82fc0a.png)

Not logged in

## Expected result:
Logged in to Bing rewards

## Reproduces how often: 
Everytime

## Brave version (brave://version info)

Brave | 0.58.21 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Mac OS X

### Reproducible on current release:
On stable 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields?  [No]
- Is the issue reproducible on the latest version of Chrome?  [No]

**Comment by singhkays** [comment]
@srirambv Yep, that fixed it

**Comment by srirambv** [comment]
Reopening the issue and adding to webcompat project to have the site hack fix

**Comment by skst** [comment]
This issue still happens for me when I have _All cookies allowed_ set or Brave Shields are down. Same symptoms: I sign in to Outlook.com then go to Bing.com. When I click "Sign in," the page refreshes, but it still shows "Sign in" instead of my profile (and does not award my Bing Rewards points to my account).

```
Brave | 0.60.48 Chromium: 72.0.3626.121 (Official Build) (64-bit)
Revision | da3787ba355f18db7db52abf75c42afb408d656f-refs/branch-heads/3626@{#883}
OS | Windows
Windows 10 Pro 1809 (17763.348)
```

> Does the issue resolve itself when disabling Brave Shields? [No]
> Is the issue reproducible on the latest version of Chrome? [No]

I've only started using Brave recently, so I'm not very familiar with it. Maybe I'm doing something wrong?

**Comment by icmonkey123** [comment]
I had the same problem after enabling all cookies. It was fixed after I deleted the browser data excluding history and tried to sign in again.

**Comment by icmonkey123** [comment]
> This issue still happens for me when I have _All cookies allowed_ set or Brave Shields are down. Same symptoms: I sign in to Outlook.com then go to Bing.com. When I click "Sign in," the page refreshes, but it still shows "Sign in" instead of my profile (and does not award my Bing Rewards points to my account).
> 
> ```
> Brave | 0.60.48 Chromium: 72.0.3626.121 (Official Build) (64-bit)
> Revision | da3787ba355f18db7db52abf75c42afb408d656f-refs/branch-heads/3626@{#883}
> OS | Windows
> Windows 10 Pro 1809 (17763.348)
> ```
> > Does the issue resolve itself when disabling Brave Shields? [No]
> > Is the issue reproducible on the latest version of Chrome? [No]
> 
> I've only started using Brave recently, so I'm not very familiar with it. Maybe I'm doing something wrong?

I had the same problem after enabling all cookies. It was fixed after I deleted the browser data excluding history and tried to sign in again.

**Comment by skst** [comment]
Thank you but still no joy. I went to **Clear browsing data** and selected *All time* and ticked *Cookies and other site data* and *Cached images and files* (not *Browsing history*). I pressed **Clear data**. I went to Bing.com, enabled all cookies, refreshed the page, and signed in to Microsoft Bing. Bing.com still says "Sign in" instead of my profile. I'm signed in to Microsoft Account but, even with Shields Down, Bing doesn't recognize it.

**Comment by Brave-Matt** [comment]
Confirming that this is still an issue and should probably be resolved. The `Allow all cookies` workaround no longer applies -- Bing displays `Sign in` on front page regardless of whether you are signed into your account. `Allow all cookies` and Shields = "down" do not have any effect either.

Several +1's in this thread: https://community.brave.com/t/bing-sign-in-not-working/43833/16

**Comment by desertrambler** [comment]
I am having this issue on Windows 10 + Brave + Bing rewards login. Continues to hit redirects and fails back to the Bing page with no login. My Microsoft Account uses 2-Factor Authentication with my phone Authenticator app - I don't know if that is making a difference.

> Does the issue resolve itself when disabling Brave Shields? [No]
> Is the issue reproducible on the latest version of Chrome? [No]

`Version 0.61.52 Chromium: 73.0.3683.86 (Official Build) (64-bit)`

**Comment by sayashr** [comment]
Same problem here as @desertrambler.  I turned off all Brave shields >_< and it still won't login. (Logs in fine on normal Chrome)

**Comment by rebron** [comment]
@Brave-Matt Let's add more steps in this issue. I'm actually able to login to Microsoft Rewards https://account.microsoft.com/rewards/ but I'm seeing that I'm not recognized on Bing.com

Steps:
1) Login to outlook.com
2) Go to Bing.com
3) Notice not recognized on bing.com. Can't sign in when selecting "Sign in" on top page. Selecting "Rewards" Sign-in takes me to https://account.microsoft.com/rewards/ where I am logged-in and recognized but the Rewards sign-in should recognize login and display the following screen:
![Screen Shot 2019-03-27 at 10 11 43 AM](https://user-images.githubusercontent.com/5951041/55097263-bf762780-5078-11e9-8818-e0a947d37bd3.png)

**Comment by jefetienne** [comment]
To add to the discussion of the issue:

If I use Brave (with the Brave Shields off), right-click the Bing 'Sign in' button at the homepage and open it in a new window, the URL returns "about:blank#blocked".

Now if I use Opera and right-click the Bing 'Sign in button', the URL just returns 'about:blank' but no '#blocked'. So maybe this '#blocked' is an indication that Brave might be blocking some sort of component or script.

**Comment by adamoo1** [comment]
> Now if I use Opera and right-click the Bing 'Sign in button', the URL just returns about:blank but no '#blocked'. So maybe this '#blocked' is an indication that Brave might be blocking some sort of component or script.

If I try the same steps in Chrome 74 I also see about:blank#blocked

**Comment by SoNic1967** [comment]
This is still not solved. I really want to ditch Firefox and Chrome... Please fix this.

**Comment by NickDiMucci** [comment]
Still an issue, even with all shields down. `Version 0.63.48 Chromium: 74.0.3729.108 (Official Build) (64-bit)`

**Comment by ivandere** [comment]
Still an issue. On all microsoft products like mixer, outlook, onedrive, etc.

**Comment by Brave-Matt** [comment]
+1 from reddit:
https://www.reddit.com/r/brave_browser/comments/bg4pry/signing_in_to_bing/

**Comment by Brave-Matt** [comment]
+1 from zendesk:
(translated)
![image](https://user-images.githubusercontent.com/3299098/57718645-adeddc80-7632-11e9-9d26-36e8c9d561e0.png)

**Comment by Ranger327** [comment]
This issue is the only reason I have not switched to using Brave. As soon as it's fixed I'll be able to finally ditch Chrome.

**Comment by chuckdee68** [comment]
Just another +1 on this.  It works on one of my computers, so I was surprised that when I started to switch on my other computers that this was a problem.

**Comment by Brave-Matt** [comment]
+1 from reddit:
https://www.reddit.com/r/brave_browser/comments/c0e0ds/cannot_log_into_bing_rewards_too_many_redirects/

**Comment by KashUppuluri** [comment]
Allowing all cookies from shields worked for me.

**Comment by bsclifton** [comment]
@Ranger327 (and others wanting a temporary work-around)... on bing.com, you can click the Lion and allow all cookies. That choice will only be saved for the domain you're on
<img width="413" alt="Screen Shot 2019-06-25 at 3 02 27 PM" src="https://user-images.githubusercontent.com/4733304/60136898-4ca14900-975a-11e9-998a-80d680a44857.png">

**Comment by VictoryRice** [comment]
Deleting all cookies for bing.com worked for me. Steps are:

- With bing.com loaded in browser, right-click a blank area of the page, and choose Inspect
- choose the Application tab in the inspector (may have to click the ">>" to reveal it)
- click the arrow next to Cookies (under the Storage group in the left column) to expand it
- Right-click https://www.bing.com and choose Clear to wipe all cookies
- Close the inspector and try signing in again

**Comment by I2ascal** [comment]
Had successfully been using Microsoft Rewards with Brave until I cleared cookies, and then was experiencing the same issue and couldn't resolve with any of the above solutions.

I created an account here specifically to share my workaround:

- With a secondary browser of choice (I used Chrome), login to Microsoft Rewards from Bing.com
- Close the secondary browser
- With Brave, Settings -> Import bookmarks and settings
- Select the secondary browser and ensure you have cookies selected
- When you return to Bing.com on Brave, you should see yourself already logged in

Hope this primitive solution works for everyone else!

**Comment by PL47ER** [comment]
@I2ascal 

While I have tried your solution and it worked smoothly, I have also found discussion here on Brave Community which resolved the issue as well.

https://community.brave.com/t/bing-sign-in-not-working/43833/36

**Comment by rebron** [comment]
cc: @simonhong

**Comment by cubanx** [comment]
So I had the same issue and the workaround that worked for me was:
1. Disable Shields on Bing (or whatever)
1. Cleared all cookies from history
1. Go into Brave global settings and allow 3rd party cookies
1. Now login (you may already be logged in)
1. Go put it all back as it should be

I closed the browser and so far so good...hope this helps someone.

**Comment by cjmccormick** [comment]
Almost a year has passed and still the same issue. Little bugs like this makes me want to rethink switching from chrome to Brave. This shouldn't be a problem whatsoever if the Brave browser is basically Chrome in the first place (Chromium). What seems to be the issue here?

**Comment by cjmccormick** [comment]
A lot of issues yet with Brave I can see, I will come back when Brave is actually good. Thanks.

**Comment by sushihangover** [comment]
> Deleting all cookies for bing.com worked for me. Steps are:
> 
> * With bing.com loaded in browser, right-click a blank area of the page, and choose Inspect
> * choose the Application tab in the inspector (may have to click the ">>" to reveal it)
> * click the arrow next to Cookies (under the Storage group in the left column) to expand it
> * Right-click https://www.bing.com and choose Clear to wipe all cookies
> * Close the inspector and try signing in again

Thanks for posting this (this does work for me, I've been using this technique for a while)

While I've had to do this once a month or so, now I am now doing it every couple of days. (As much as I like Brave, items like this on a major site is pushing me away from it as this issue has been open for 10 months...and do not get my started on the Instagram issues )

**Comment by jumde** [comment]
this works on Chromium (v80.0.3973.0 (Developer Build) (64-bit)) with 3p cookie blocking enabled.

**Comment by 0x6A7232** [comment]
As noted [here](https://community.brave.com/t/bing-sign-in-not-working/43833/37) signing out from both login.live.com (after it redirects) and bing.com (might be easier to just clear cookies, at least for those particular sites instead, that'll be sure to log you out) and then loading both sites and disabling the shields for both seems to work.

Now note, if you happen to have the uMatrix plugin, of course you've got to enable access to some sites from bing.com (azureedge.net and msauth.net I believe) but ALSO, you have to go into uMatrix options (right click uMatrix > options) and under "settings" disable "Spoof HTTP referrer string of third-party requests" -- once you've logged in, you can re-enable that setting.

... at least that's what worked for me.

**Comment by ScuzzyHoulihan** [comment]
I found a workaround but not a solution. What you can do is have a tab open logged into your bing account and set the bing as the default search engine. You will always collect the points but you will always have to have a tab on bing. Hopefully, there is a solution soon.

**Comment by jumde** [comment]
Fixed in 1.2 by https://github.com/brave/referrer-whitelist/pull/17 cc: @brave/legacy_qa

**Comment by kjozwiak** [comment]
@jumde seems like it's working in terms of being able to login into Bing Rewards without changing the default `Shields` settings. However, I noticed that you won't be automatically logged into your Outlook account in the following two cases:

##### `Case #1`

* visit https://outlook.live.com/
* login into your account (works without any issues)
* visit https://www.bing.com and you'll notice that you're not logged in
* click on `Sign In` and you'll be logged in automatically. You should be logged into Bing Rewards if you've already opted-in.

##### `Case #2`

* visit https://outlook.live.com/
* login into your account (works without any issues)
* visit https://www.bing.com and you'll notice that you're not logged in
* click on the `Rewards` button under Bing and select `Sign In`
* you'll be redirected to https://account.microsoft.com/rewards/ and will be logged in
* visit https://www.bing.com and you'll notice that you're not logged in/using out Outlook account
* click on `Sign In` and you'll be logged in automatically. You should be logged into Bing Rewards and view the panel if you've already opted-in.

The above two cases work on Chrome without any issues. @rebron is the above expected? Assuming the only thing that we're worried about here is being able to login into Bing Rewards without changing the default `Shields` settings?  Mind checking if https://github.com/brave/brave-browser/issues/3082#issuecomment-477260841 is working for you now?

**Comment by rebron** [comment]
Both cases look good on my end using  Version 1.2.40 Chromium: 79.0.3945.88 (Official Build) (64-bit). The original issue was about not being able to login at all into Bing Rewards regardless of shields settings. 

I'm not so sure that being recognized automatically into Bing.com from a previous login from outlook.live.com is a bug or an issue we need to address.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.15.2 x64` using the following build:

Brave | 1.2.40 Chromium: 79.0.3945.88 (Official Build) (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | macOS Version 10.15.2 (Build 19C57)

* Verified signing through https://www.bing.com using the `Sign In` button worked without any issues and also signed you into Bing Rewards
* Verified clicking on `Sign In` under https://www.bing.com logged you in without any issues when you're already logged into https://outlook.live.com/
* Ensured that the above cases worked with the default `Shields` settings
