### ISSUE TITLE
Create base api slice

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#30827]
## Description 

Create a base for the api slice so that endpoints can be defined across multiple files

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.57.33 Chromium: 115.0.5790.114 (Official Build) beta (64-bit)
-- | --
Revision | 86b4ea1d70ce73c4468d84cc8277f1f9de14b8bc
OS | Windows 11 Version 22H2 (Build 22621.1992)

- Verified wallet works as expected
