### ISSUE TITLE
[Shortcuts]: Translate commands

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#30831]
Currently, commands are available only in English. You can see this by visiting `chrome://settings/system/shortcuts` with the `brave://flags/#brave-commands` flag enabled with a non-english language (the commands are still in English).

We should make it possible to view the commands in other languages. Note: This also applies to the quick commands.

**Comment by LaurenWags** [comment]
@fallaciousreasoning what does this fix exactly? it looks like the shortcuts are translated in 1.53.107 as per the following screenshot. Am I misunderstanding what this fix should cover?

<img width="1186" alt="Bildschirmfoto 2023-06-30 um 1 58 40 PM" src="https://github.com/brave/brave-browser/assets/28145373/c9a8fd62-9b84-49da-883f-49511d41d957">

**Comment by fallaciousreasoning** [comment]
Hi @LaurenWags, this was uplifted to 1.53 via https://github.com/brave/brave-core/pull/18780 :smile: That's exactly what you should be seeing :smile: 

Thanks for all your work!

**Comment by LaurenWags** [comment]
thanks @fallaciousreasoning! so was this issue missed as part of uplift to 1.53.x? Or does it need to be re-tested as part of 1.54.x? Want to be sure QA checks this one if needed.

I guess it could also be marked `QA/No` and left in the 1.54.x milestone if testing is not needed. wdyt @fallaciousreasoning @kjozwiak @rebron?

**Comment by fallaciousreasoning** [comment]
I think this is passing in 1.53.x - before this PR the commands you're seeing in 1.53.107 would have been in English not German.

Probably doesn't need to be retested in 1.54.x

**Comment by LaurenWags** [comment]
Sounds like you're leaning towards `QA/No` for this one @fallaciousreasoning, any objections @kjozwiak @rebron?

**Comment by kjozwiak** [comment]
> Sounds like you're leaning towards `QA/No` for this one @fallaciousreasoning, any objections @kjozwiak @rebron?

No objections 👍

**Comment by LaurenWags** [comment]
Updated to `QA/No` - thanks all!
