### ISSUE TITLE
Add keyboard shortcuts

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#30840]
## Description 

Provide a way for users to see via a list and to find via a search field, all the available keyboard shortcuts. Users  should be able to easily add/remove or edit existing keyboard shortcuts or create new ones.

Keyboard shortcuts should be made available here: brave://settings/system/ and brave://settings/system/shortcuts

## Expected result:
https://www.figma.com/file/tLXWGCpNoiJxDZDdpfordj/Desktop-Settings?node-id=3617-77370&t=HKTZrtO87yiUZkol-0

## Brave version (brave://version info)

Targeting 1.53.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

Related issues: 
- https://github.com/brave/brave-browser/issues/354
- https://github.com/brave/brave-browser/issues/29349
- https://github.com/brave/brave-browser/issues/30831
- https://github.com/brave/brave-browser/issues/30757
- https://github.com/brave/brave-browser/issues/30879 (non blocking)
- https://github.com/brave/brave-browser/issues/30880
- https://github.com/brave/brave-browser/issues/30895
- https://github.com/brave/brave-browser/issues/30931
- https://github.com/brave/brave-browser/issues/30962
- https://github.com/brave/brave-browser/issues/31032
- https://github.com/brave/brave-browser/issues/31035

1.53.x uplift PR:
https://github.com/brave/brave-core/pull/18780

To make life easier for @kjozwiak we're going to uplift these to 1.53.x in as few PRs as possible (seeing as non of these are critical unless most of them land).

## Test Plan
1. Existing shortcuts should still work in a new profile - verify (CTRL+T for new tab, CTRL+N for new window, CTRL+L to focus the location bar.
2. It should be possible to add new shortcuts to these commands on brave://settings/system/shortcuts
    1. Add `Backspace` as a shortcut for `Back`
    2. Press `Backspace` - the browser should navigate back
    3. Reset the shortcut. Backspace should no longer navigate back
    4. Add `ALT+LeftArrow` as a shortcut for `Forward`. A warning should pop up saying `This combination is being used for "Back". Saving will override that shortcut.`
    5. Pressing Alt+Left should now navigate forward.
    6. Add Alt+Left as a shortcut to the `Back` command (neither back nor forward should be resettable now, as they are already at their defaults)
3. It should be possible to remove shortcuts from the commands
    1. Remove Alt+Left from Back. Pressing the shortcut should no longer navigate back.
    2. Add Alt+Left to Forward. No warning should appear.
4. It should be possible to add shortcuts to commands that didn't have them previously.
    1. Add Alt+P to Pin Tab & Alt+D to duplicate tab
    2. Alt+P should toggle whether a tab is pinned. Alt+D should duplicate the current tab (same as right-click duplicate)
5. It should be possible to reset all commands
    1. Click the `Reset all to defaults` button at the bottom of the page.
    2. All edited shortcuts should be reset.

**Note:** On macOS some shortcuts cannot be changed via the shortcuts UI. For these shortcuts, no remove button should show up, and it should not be possible to override them by adding their key combination to another shortcut.

**Comment by fallaciousreasoning** [comment]
**Note for QA:** It's a known issue that pressing `Shift+=` will display as `Shift++` in the recorder (but will still be recorded properly). See https://github.com/brave/brave-browser/issues/30879

**Comment by kjozwiak** [comment]
@fallaciousreasoning @rebron should this issue be closed? I believe at this point we basically have everything merged into `1.56.x`.  Or should this stay in progress till https://github.com/brave/brave-browser/issues/30879 is done? We have about ~week and a half left before we push out `1.56.x` on `July 18th`.

Should https://github.com/brave/brave-browser/issues/354 also be closed at this point?

CCing @LaurenWags

**Comment by fallaciousreasoning** [comment]
I think we can close this and #354, but let's have @rebron confirm. Thanks for all the uplifts/testing @kjozwiak & @LaurenWags!

**Comment by LaurenWags** [comment]
if we close this one out for 1.53.x we should have a test plan for it - we've verified various issues as listed above but afaik we still don't have a feature test plan, only the individual issues. I believe @rebron mentioned he'd work with you @fallaciousreasoning to get a test plan together?

**Comment by fallaciousreasoning** [comment]
Added a test plan to this issue :smile: Let me know if you think there's anything missing

**Comment by LaurenWags** [comment]
@fallaciousreasoning is there anything Windows (or Linux) specific we should be aware of when testing this one?

cc @brave/qa-team

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.56.1 Chromium: 115.0.5790.75 (Official Build) (x86_64)
-- | --
Revision | 3433e4d513e8454ba0243deea3d53693661dc0c3-refs/branch-heads/5790@{#1430}
OS | macOS Version 11.7.8 (Build 20G1351)

**Comment by fallaciousreasoning** [comment]
> @fallaciousreasoning is there anything Windows (or Linux) specific we should be aware of when testing this one?

Nope, there's just the MacOS thing, where some shortcuts can't be edited.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.56.1 Chromium: 115.0.5790.75 (Official Build) (64-bit)
-- | --
Revision | 3433e4d513e8454ba0243deea3d53693661dc0c3-refs/branch-heads/5790@{#1430}
OS | Windows 11 Version 22H2 (Build 22621.1928)
```
 ### Shared Steps:
<details>

1. installed `1.56.1`
2. launched Brave
3. opened `brave://flags`
4. set `brave://flags/#brave-commands` to `Enabled`
5. clicked `Relaunch`
6. opened `brave://settings/`
7. clicked on `System`
8. clicked on `Shortcuts`

`brave://flags` | `brave://settings/system/shortcuts`
---------------|------------------------------------
![image](https://github.com/brave/brave-browser/assets/98358127/8dacb17a-d8c9-4323-926c-e1c198662d01)|![image](https://github.com/brave/brave-browser/assets/98358127/e586b716-f22d-4c0d-9426-4eba8a89330f)

</details>

Ensure (pre)existing shortcuts continue to work - `PASSED`
<details>

Ensured all of the following commands' keybindings/shortcuts worked:

- `New tab` - `CTRL` + `T`
- `New window` - `CTRL+N` + `N`
- `Focus location bar` - `CTRL+L`  
- `Bookmark this tab` - `CTRL` + `D`
- `Back` - `Alt` + `ArrowLeft`
- `Forward` - `Alt` +` ArrowRight`

</details>


Add new shortcuts to existing commands - `PASSED`
<details>

(continued from `Shared Steps`)

`Back` shortcut- `PASSED`

### Steps:
1. clicked on `Add` in the `Back` section
2. pressed `Backspace` as a new shortcut
3. clicked `Save`
4. confirmed `Backspace` shortcut is added 
5. confirmed `Alt+BrrowLeft`& `Backspace worked`  
6. clicked `Reset`. 
7. confirmed `Backspace` no longer navigated back

example | example | example | example | example | example
---------|---------|----------|----------|---------|---------
![image](https://github.com/brave/brave-browser/assets/98358127/d270a8aa-5be6-47a9-9903-dc527faa97fe)|![image](https://github.com/brave/brave-browser/assets/98358127/7716fa22-977e-4e3a-b067-a769ebf25f54)|![image](https://github.com/brave/brave-browser/assets/98358127/cc9982fa-45d1-4f60-8713-49aedf895e9e)|![image](https://github.com/brave/brave-browser/assets/98358127/6b15b5de-b5df-42e9-bd41-010184c4a385)|![image](https://github.com/brave/brave-browser/assets/98358127/ee850702-3490-42e9-8d89-ad3de47853fc)|![image](https://github.com/brave/brave-browser/assets/98358127/5f238763-b4cd-4ec2-aac9-5d52e4b4543f)

  `Forward` shortcut
 
clicked on `Add` in the `Forward` section
Press `ALT+LeftArrow` as a shortcut 
A warning message shown `This combination is being used for "Back". Saving will override that shortcut.`
clicked `Save` 
verified `Alt+ArrowLeft` is switched from `Back` to `Forward`
confirmed pressing Alt+ArrowLeft navigated forward.
clicked `Add` to add back `Alt+ArrowLeft` Or `Reset`
confirmed `Alt+ArrowLeft` is added to Back` and `Reset` option is not available for `Back` & `Forward` sections


example | example | example 
--- | ---- | ----- 
![image](https://github.com/brave/brave-browser/assets/98358127/09d5299f-8cab-498e-a5ce-2a539ad45e64)|![image](https://github.com/brave/brave-browser/assets/98358127/faf909aa-0d49-4cd3-81f8-04ee10faa3a9)|![image](https://github.com/brave/brave-browser/assets/98358127/5a38e950-c4e4-43a6-ae64-f7db964a0c00)

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave	1.56.5 Chromium: 115.0.5790.75 (Official Build) (64-bit) 
Revision	3433e4d513e8454ba0243deea3d53693661dc0c3-refs/branch-heads/5790@{#1430}
OS	Linux
```

### Shared Steps:
<details>

1. installed `1.56.1`
2. launched Brave
3. opened `brave://flags`
4. set `brave://flags/#brave-commands` to `Enabled`
5. clicked `Relaunch`
6. opened `brave://settings/`
7. clicked on `System`
8. clicked on `Shortcuts`

`brave://flags` | `brave://settings/system/shortcuts`
---------------|------------------------------------
<img width="1483" alt="Screen Shot 2023-07-10 at 1 52 59 PM" src="https://github.com/brave/brave-browser/assets/387249/f58113de-bf6b-4e09-b5cb-4399938b4974"> | <img width="1483" alt="Screen Shot 2023-07-10 at 1 53 15 PM" src="https://github.com/brave/brave-browser/assets/387249/e9ae70b3-888a-4544-9555-d99146c129d8">

</details>

Ensure (pre)existing shortcuts continue to work - `PASSED`
<details>

Ensured all of the following commands' keybindings/shortcuts worked:

- `New tab` - `command` + `T`
- `New window` - `command` + `N`
- `Focus location bar` - `command` + `L`
- `Bookmark this tab` - `command` + `D`
- `Back` - `command` + `{`
- `Forward` - `command` +` }`

</details>

Add new shortcuts to existing commands - `PASSED`
<details>

(continued from `Shared Steps`)

`Back` binding - `PASSED`

### Steps:
1. clicked on `Add` next to `Back`
2. pressed `delete` (`Backspace`)
3. clicked `Save`
4. confirmed `Back` showed two keybindings/shortcuts
5. confirmed both worked
6. scrolled all the way down and clicked on `Reset all to defaults`
7. confirmed the added shortcut was removed
8. confirmed `command` + `[` still navigated backwords
 

example | example | example | example | example | example
---------|---------|----------|----------|---------|---------
<img width="1073" alt="Screen Shot 2023-07-10 at 3 06 38 PM" src="https://github.com/brave/brave-browser/assets/387249/40cd5a81-3662-471e-8787-fc690b59f4fe"> | <img width="1117" alt="Screen Shot 2023-07-10 at 3 06 45 PM" src="https://github.com/brave/brave-browser/assets/387249/2e76f1e3-0947-41b8-9590-ffc8914a734a"> | <img width="1117" alt="Screen Shot 2023-07-10 at 3 06 49 PM" src="https://github.com/brave/brave-browser/assets/387249/f9edcbc4-0f52-4a9d-ad40-73d707f6e87e"> | <img width="1117" alt="Screen Shot 2023-07-10 at 3 11 56 PM" src="https://github.com/brave/brave-browser/assets/387249/69121058-f730-4ff4-863e-9de14ea02ed0"> | <img width="1117" alt="Screen Shot 2023-07-10 at 3 12 04 PM" src="https://github.com/brave/brave-browser/assets/387249/6a36c214-bca4-4a0d-9207-766c5cc7802a"> | <img width="1117" alt="Screen Shot 2023-07-10 at 3 06 49 PM" src="https://github.com/brave/brave-browser/assets/387249/57318029-ab6b-49c5-a5a3-e86d99c6c5bd">


(continued from `Shared Steps`


`Forward` binding - `PASSED`


### Steps:
1. clicked on `Add` next to `Forward`
2. pressed `command` + `left arrow`
3. clicked `Save`
4. confirmed `Forward` showed two keybindings/shortcuts
5. confirmed they both navigated forwards

example | example | example
---------|---------|----------
<img width="1073" alt="Screen Shot 2023-07-10 at 3 16 43 PM" src="https://github.com/brave/brave-browser/assets/387249/f9160cb9-3803-41cd-866e-2894bfb1617c"> | <img width="1073" alt="Screen Shot 2023-07-10 at 3 29 36 PM" src="https://github.com/brave/brave-browser/assets/387249/a1521025-61ce-4524-b262-832e1615bf56"> | <img width="1117" alt="Screen Shot 2023-07-10 at 3 16 49 PM" src="https://github.com/brave/brave-browser/assets/387249/34e6464b-ea72-4dcd-96da-5ea405dbe7b3">

</details>



Remove added shortcuts - `PASSED`
<details>
(continued from `Shared Steps`)

Steps:
1. added `command` + `left arrow` to `Back`
2. added `command` + `right arrow` to `Forward`
3. confirmed both worked
4. confirmed both had `Reset` next to `Add`, now
5. hovered over both `command` + `left arrow` & command` + `right arrow`
6. confirmed both had `-`
7. clicked on them
8. confirmed `Reset` disappears for both, as they are now back to their defaults

example | example | example | example
---------|----------|---------|---------
<img width="1117" alt="Screen Shot 2023-07-10 at 3 36 42 PM" src="https://github.com/brave/brave-browser/assets/387249/85354d0d-e02a-4645-ae1d-212a632724d0"> | <img width="1117" alt="Screen Shot 2023-07-10 at 3 41 01 PM" src="https://github.com/brave/brave-browser/assets/387249/edbe4c1c-85ed-4b58-a594-e5aa12154967"> | <img width="1117" alt="Screen Shot 2023-07-10 at 3 41 08 PM" src="https://github.com/brave/brave-browser/assets/387249/95c79348-3560-4166-9a00-ecc4de01de64"> | <img width="1117" alt="Screen Shot 2023-07-10 at 3 41 11 PM" src="https://github.com/brave/brave-browser/assets/387249/727e889c-85ba-47d3-81d8-a823d80e0859">



</details>


Add new shortcuts as a new command - `PASSED`
<details>

### Steps:
(continued from `Shared Steps`)

1. searched for `pin tab`
10. clicked `Add`
11. pressed `control` + `P`
12. clicked `Save`
13. pressed `control` + `P`
14. confirmed the current tab became pinned

example | example | example | example
---------|---------|----------|---------
<img width="1117" alt="Screen Shot 2023-07-10 at 2 34 11 PM" src="https://github.com/brave/brave-browser/assets/387249/efaec1d7-d7c7-4675-b0a7-b91ad47a6342"> | <img width="1002" alt="Screen Shot 2023-07-10 at 2 34 47 PM" src="https://github.com/brave/brave-browser/assets/387249/11d571f9-0be6-4e8f-a14e-5703ec3b97e6"> | <img width="1117" alt="Screen Shot 2023-07-10 at 2 34 59 PM" src="https://github.com/brave/brave-browser/assets/387249/396f9bd3-1b47-4063-8c31-66218db3e2d7"> | <img width="1117" alt="Screen Shot 2023-07-10 at 2 35 10 PM" src="https://github.com/brave/brave-browser/assets/387249/444d5450-ad3c-4043-9798-f46921dfcdaa">



</details>



Unable to change system-level commands/key bindings - `PASSED`
<details>

(continued from `Shared Steps`)

### Steps:
1.  searched for `back`
2. confirmed no ability to remove the keybinding shortcut of `command` + `[`
3. clicked on `Add` for the next binding
4. tried to bind using `command` + `[`
5. confirmed I got an error about it being a system shortcut, and where to modify it, in `System Settings`
6. also confirmed with `Print`, `Copy`, etc.

example | example | example | example
---------|---------|----------|---------
<img width="1117" alt="Screen Shot 2023-07-10 at 2 47 23 PM" src="https://github.com/brave/brave-browser/assets/387249/2955bc8e-0912-4a58-a5cb-0a3cfeebb166"> | <img width="1073" alt="Screen Shot 2023-07-10 at 2 50 32 PM" src="https://github.com/brave/brave-browser/assets/387249/58dd1922-ba9e-4c91-89d1-c3d24e97c2c4"> | <img width="1765" alt="Screen Shot 2023-07-12 at 1 36 50 PM" src="https://github.com/brave/brave-browser/assets/387249/dca9de0a-f597-4076-aad6-2f2f4cbe2b10"> | <img width="1765" alt="Screen Shot 2023-07-12 at 1 37 38 PM" src="https://github.com/brave/brave-browser/assets/387249/5001fe41-03ac-4cef-b262-08169fc488d5">



</details>

Adding duplicate shortcuts - `FAILED`
<details>

(continued from `Shared Steps`)

1. clicked on `Add` next to `Web app info`
2. pressed `Command` + `D`
3. clicked `Save`
4. pressed `Command` + `D`

Expected:

Should open `Web app info` / not be allowed to be assigned as a shortcut

Actual:

Able to visibly create the assigned shortcut for `Web app info`, but it still works as regular `Bookmark Tab`

example | example | example
---------|---------|---------
<img width="1159" alt="Screen Shot 2023-07-11 at 3 35 43 AM" src="https://github.com/brave/brave-browser/assets/387249/47d931e6-f1ca-475f-9d06-f616c06cdf2f"> | <img width="1203" alt="Screen Shot 2023-07-11 at 3 35 48 AM" src="https://github.com/brave/brave-browser/assets/387249/fbf38351-2092-4e7f-8a1c-74d611ebf770"> | <img width="1203" alt="Screen Shot 2023-07-11 at 3 42 14 AM" src="https://github.com/brave/brave-browser/assets/387249/8fb89146-e19b-4c79-baf7-236f59be2467">

NOTE: Retest with latest `nightly` build after https://github.com/brave/brave-browser/issues/31552 lands

</details>

</details>
