### ISSUE TITLE
Refactor WalletAccount in ui 

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#30851]
Should decrease use of AccountInfo.address field for referencing accounts

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.57.18 Chromium: 115.0.5790.98 (Official Build) beta (64-bit)
-- | --
Revision | `d515871a6c6df7d2843e755c8b7dda9b744f26d6`
OS | Windows 11 Version 22H2 (Build 22621.1992)

- Verified wallet works as expected
