### ISSUE TITLE
Follow up of #17434 - Long domain names overflow in Rewards `Show -All` screen

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#30858]
## Description 

Found while testing #17434 
Follow up of #17434 - Long domain names overflow Rewards `Show -All` screen
## Steps to Reproduce

   1. Please see STR from https://github.com/brave/brave-browser/issues/17434#issue-966706329
 

## Actual result:

 Long domain names overflow in Rewards `Show -All` screen
![long domain names in show all popup modal](https://github.com/brave/brave-browser/assets/38657976/2f87a526-8dfb-4afa-b6fa-7597808752d4)

## Expected result:

Long domain names should not overflow in Rewards `Show -All` screen
## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.53.82 Chromium: 114.0.5735.90 (Official Build) beta (64-bit)
-- | --
Revision | 386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}
OS | Windows 10 Version 22H2 (Build 19045.2965)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Not sure
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @mkarolin @Miyayes

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.57.6 Chromium: 115.0.5790.75 (Official Build) beta (x86_64)
-- | --
Revision | 3433e4d513e8454ba0243deea3d53693661dc0c3-refs/branch-heads/5790@{#1430}
OS | macOS Version 13.4.1 (Build 22F82)
```
