### ISSUE TITLE
Brave auto-reloads "vk.com" pages every 3 seconds if "Prevent sites from fingerprinting me based on my language preferences" is enabled

### ISSUE THREAD

**Issue by 0ember1** [brave/brave-browser#30855]
## Description 
On both Android app and PC client, everytime you visit vk.com it reloads the page every 3 seconds, making you unable to do anything on the page. If you're not logged into your account on vk.com, and try to login, it won't let you input your phone number/email and just put you on the same page everytime you try to reload it. As this setting is turned on in the Mobile/PC client automatically, this causes a lot of problems for Brave users visiting vk.com

## Steps to Reproduce
   1. Have "Prevent sites from fingerprinting me based on my language preferences" enabled in the browser.
   2. Visit vk.com
   3. Input your phone or email
   4. Done, it won't redirect you to the password input page and just reload it

## Steps to Reproduce (if you're logged onto the site)
   1. Have "Prevent sites from fingerprinting me based on my language preferences" enabled in the browser.
   2. Visit vk.com
   3. Witness page reloading every 3 seconds

## Actual result:
Page auto-reloads every 3 seconds when you visit it

## Expected result:
Page loads in normally and nothing else happens

## Reproduces how often: 
Page of vk.com reloads everytime you visit it

## Desktop Brave version:
1.52.119 Chromium: 114.0.5735.90 (Official Build) (64-bit) 

## Android Device details:
   - Install type (ARM, x86): ARMv8
   - Device type (Phone, Tablet, Phablet): Phone (Samsung M51)
   - Android version: 12

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? I don't know
- Can you reproduce this issue with the nightly channel? What is that

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes (turning "Prevent sites from fingerprinting me based on my language preferences" off removes the effect)
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by Sinamore** [comment]
Having the same problem on v1.60.125, Desktop/Linux

**Comment by artromone** [comment]
same problem kubutnu 22.04/windows 10
[Version 1.62.165 Chromium: 121.0.6167.184 (Official Build) (64-bit)](https://brave.com/latest/)

**Comment by ryanbr** [comment]
@artromone @Sinamore @Kirius88 @0ember1  If its still an issue

- Install Brave Nightly
- Enabled `brave://flags/#brave-webcompat-exceptions-service`
- Restart Brave
- Visit VK with fingerprinting enabled
- Click on the number next to toggle the various fingerprint options. (trying to work which fingerprint option helps stop the reload)

![vk-test](https://github.com/user-attachments/assets/4165c68b-6ae3-41e6-8ad5-68eca08bbbf5)

**Comment by Sinamore** [comment]
@ryanbr it seems to be working even in stable version (v 1.68.134) now. Thanks!

**Comment by ryanbr** [comment]
Thanks for confirming
