### ISSUE TITLE
SIGSEGV on Brave beta 1.53.77

### ISSUE THREAD

**Issue by morialo3** [brave/brave-browser#30869]
## Description 
Browser crashes after some time, sending the session to freeze (sometimes) in my case Xwayland process stuck at 100% cpu (always),maybe related to X11 but now brave is my main suspect.

## Steps to Reproduce

   1. Start Brave for  ~2 or more hours.
   2. The tricky part: Toggle any extension on or off from the extensions menu.
   3. Voilà!!!

## Actual result:
Crashed and  coredump was created.

## Expected result:
No crash should've occured by toggling extensions (on/off).

## Reproduces how often: 
Reproducible if you are willing to keep the browser on and busy for long hours.

## Brave version (brave://version info)

Brave | 1.53.77 Chromium: 114.0.5735.90 (Official Build) beta (64-bit)
-- | --
Revision | 386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}
OS | Linux

## Version/Channel Information:
Stable version also have the issue.

- Can you reproduce this issue with the current release? yes.
- Can you reproduce this issue with the beta channel? yes.
- Can you reproduce this issue with the nightly channel? not tested.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? not tested.
- Does the issue resolve itself when disabling Brave Rewards? off on both beta and stable versions.
- Is the issue reproducible on the latest version of Chrome? not tested.

## Miscellaneous Information:
stack trace: https://gist.github.com/morialo3/7e832de1226fcf19993d82fa0fa3622c

**Comment by iefremov** [comment]
stale
