### ISSUE TITLE
Replace "async" npm dependency with "async/mapLimit"

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#30863]
## Description 

`mapLimit` is the only function exported from async that we are currently using in the wallet.
Replace the dependency with "async/mapLimit" to reduce the amount of node_module files.

**Comment by Aditay2002** [comment]
@jamesmudgett @josheleonard i will like to  contribute towards this issue . can you please assing it to me?

**Comment by josheleonard** [comment]
Closing since we now use more methods from this package
