### ISSUE TITLE
Brave does not open without passing a URL

### ISSUE THREAD

**Issue by aHappyConstant** [brave/brave-browser#30862]
## Description 

Brave does not open if I open the shortcut in the Desktop or in the taskbar or run `"C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe"`. If I run the same with a URL, then only it runs

## Steps to Reproduce

   1. Run `"C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe"`. You will see that it does not open.

## Actual result:

It does not open.

## Expected result:
It opens.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

1.52.119 Chromium: 114.0.5735.90 (Official Build) (64-bit) 
386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}
Windows 11 Version 22H2 (Build 22621.1702)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Did not test yet
- Can you reproduce this issue with the nightly channel? Did not test yet

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

If you run `"C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe" https://example.com`, then only it runs.
Also, Brave also runs if you right-click the Brave icon in the taskbar and select New Private Window, or open a link or open an HTML file

**Comment by Brave-Matt** [comment]
@aHappyConstant,
Seems like this may be related to an extension — can you tell me if you have any installed at this time? Additionally, the first thing I would do is update the browser to the latest build (v1.52.122 at the time of writing this) and check to see if the issue persists. If it does, I've got a couple tests for you to try out.

First, can you please try launching Brave (with the URL so that it actually opens), then creating a new browser profile (`Menu --> Create a new profile`), closing all Brave windows and then trying to launch Brave with the new profile normally and tell me if the same thing happens?

**Comment by aHappyConstant** [comment]
> Seems like this may be related to an extension — can you tell me if you have any installed at this time? Additionally, the first thing I would do is update the browser to the latest build (v1.52.122 at the time of writing this) and check to see if the issue persists. If it does, I've got a couple tests for you to try out.
I think i may have no extensions which may be interfering with the browser
> First, can you please try launching Brave (with the URL so that it actually opens), then creating a new browser profile (`Menu --> Create a new profile`), closing all Brave windows and then trying to launch Brave with the new profile normally and tell me if the same thing happens?
I think it may be a profile issue. I have two profiles, and once i switched to the other one all of the browser windows crashed. I tried reinstalling the browser but it didn't work.

But when i unified brave using a third party uninstaller, and installed it again, it worked. Anyway I'm gonna close this issue
