### ISSUE TITLE
Change payout countdown to use earnings range

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#30866]
## Description

Payout countdown shows this: 
![image](https://github.com/brave/brave-browser/assets/11497541/276ffec6-45eb-4340-893b-a35b51a19866)

- [ ] New text: Your [month] earnings of [insert range] BAT will arrive in x days.

However, it should show earnings range instead. 

Repro'd on 1.54.22 Chromium: 114.0.5735.90 (Official Build) nightly (x86_64)

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.57.6 Chromium: 115.0.5790.75 (Official Build) beta (64-bit)
-- | --
Revision | 3433e4d513e8454ba0243deea3d53693661dc0c3-refs/branch-heads/5790@{#1430}
OS | Windows 10 Version 22H2 (Build 19045.3208)
```

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Vivo X70 Pro version 12` running `Bravemonoarmx64.apk_1.57.19`

![image](https://github.com/brave/brave-browser/assets/38657976/57ed023f-56f8-4c71-9f0d-732facab2001)
