### ISSUE TITLE
Create Account Prompt not working in Wallet Panel

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#30864]
## Description 

When switching to the `Filecoin` network in the panel, the create account prompt is not showing up if you don't have an account.

## Steps to Reproduce

   1. Create a new `Wallet`
   2. Open the `Wallet Panel` and switch to the `Filecoin Mainnet` network
   3. The prompt to create an account does not show up

## Expected result:
Should prompt to create an account if you don't yet have an account for a network.

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.57.24 Chromium: 115.0.5790.136 (Official Build) beta (64-bit)
-- | --
Revision | `8099932ede6f8d4624fbddf39d27abb3b340d8c9`
OS | Linux

- Verified steps from [brave/brave-core#18776](https://github.com/brave/brave-core/pull/18776)
- Verified account creation prompt is shown when Filecoin is selected from network selector
- Encountered [#31909](https://github.com/brave/brave-browser/issues/31909)

https://github.com/brave/brave-browser/assets/17010094/2da7bcad-d881-4cb4-9014-6bc86a5ce8af



---------------------

**Verification passed on**

Brave | 1.57.24 Chromium: 115.0.5790.136 (Official Build) beta (64-bit)
-- | --
Revision | `8099932ede6f8d4624fbddf39d27abb3b340d8c9`
OS | Windows 11 Version 22H2 (Build 22621.1992)


- Verified steps from [brave/brave-core#18776](https://github.com/brave/brave-core/pull/18776)
- Verified account creation prompt is shown when Filecoin is selected from network selector
- Encountered [#31909](https://github.com/brave/brave-browser/issues/31909)

https://github.com/brave/brave-browser/assets/17010094/92f8e382-e805-4bb4-b1b0-e69964aba6f2

---------------------

**Verification passed on**

Brave | 1.57.24 Chromium: 115.0.5790.136 (Official Build) beta (arm64)
-- | --
Revision | `8099932ede6f8d4624fbddf39d27abb3b340d8c9`
OS | macOS Version 13.4.1 (c) (Build 22F770820d)

- Verified steps from [brave/brave-core#18776](https://github.com/brave/brave-core/pull/18776)
- Verified account creation prompt is shown when Filecoin is selected from network selector
- Encountered [#31909](https://github.com/brave/brave-browser/issues/31909)

https://github.com/brave/brave-browser/assets/17010094/03662c6a-8a6f-48b2-b5b6-0c005925cf0d
