### ISSUE TITLE
[Shortcuts]: Capture KeyEvents at the Views layer for use in shortcuts

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#30879]
Currently, we just use the existing JS event handlers for capturing shortcut keys. However, this has a number of limitations, and caveats where we don't capture exactly what we'd expect:
- Shift + key might be a different key (i.e. shift+= will be registered as the `+` key instead of `=`)
- `Meta` key presses are not registered until another key is pressed
- @rebron got the `Dead` key to show up, which is a special windows key sometimes bound to a combination of others

These issues are not fixable if we keep using the JS event handlers.

**Comment by kjozwiak** [comment]
The above requires `1.57.42` or higher for `1.57.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.57.42 Chromium: 116.0.5845.51 (Official Build) (64-bit)
-- | --
Revision | e25036a089c476c56bf71774a898a1fee014e00d
OS | Windows 11 Version 22H2 (Build 22621.1992)
```

1. Installed 1.57.42
2. launched Brave
3. navigated brave://settings/system/shortcuts

### `Control` + `=` 
4. clicked `Add` next to `Exit` shortcut
5. pressed `Control` + `=` on the keyboard
6. confirmed `Control` `=` displayed in the dialog
7. clicked `Save` button
8. confirmed keyboard shortcut displayed for `Exit` shortcut and worked as expected

step 6 | step 8
---- | -----
![image](https://github.com/brave/brave-browser/assets/98358127/14b32518-71ea-410c-b2ea-f9498bac6c9d)|![image](https://github.com/brave/brave-browser/assets/98358127/39d0062c-660c-4e69-aa25-9b7393125ab1)

### Control + Shift + =  
9. clicked `Add` next to `Close other tabs` shortcut 
10. clicked `Save` button
11. confirmed keyboard shortcut displayed for `Close other tabs` and worked as expected

step 9 | step 11
---- | -----
![image](https://github.com/brave/brave-browser/assets/98358127/ceadd6ac-6c06-465f-9965-d8abbea3f510)|![image](https://github.com/brave/brave-browser/assets/98358127/d9d0d62d-3d96-4874-be98-5db0b539b0be)

### Alt+P 
12. clicked `Add` next to `About Brave` shortcut 
13. clicked `Save` button
14. confirmed keyboard shortcut displayed for `About Brave` and worked as expected

step 12 | step 14
---- | -----
![image](https://github.com/brave/brave-browser/assets/98358127/0bc70453-32d1-4df3-99b9-5b447521c699)|![image](https://github.com/brave/brave-browser/assets/98358127/556e4610-722b-4aeb-be60-889003b63a11)
