### ISSUE TITLE
Fix/replace EthProvider and SolProvider P3A metrics

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#30874]
Since the wallet setting dropdown menu items have changed, and provider injection rules have changed (thus breaking the existing EthProvider/SolProvider metrics, as noted in https://github.com/brave/brave-browser/issues/30585), new metrics must be introduced to account for this.

What is your preferred Ethereum provider?
`Brave.Wallet.EthProvider.4`

0) None, because no wallet is setup
1) None, because the default provider setting is set to "Extensions (no fallback)"
2) Brave Wallet (wallet is setup, no installed extension)
3) Brave Wallet (wallet is setup, an extension may *potentially* be installed but cannot override native provider)
4) Third-party extension (not overriding a setup Brave Wallet)
5) Third-party extension (overriding a setup Brave Wallet)

Add another question for Solana (`Brave.Wallet.SolProvider.2`)

`Brave.Wallet.EthProvider.3` and `Brave.Wallet.SolProvider` will be removed.

**Comment by kjozwiak** [comment]
The above requires `1.53.106` or higher for `1.53.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.53.108 Chromium: 115.0.5790.56 (Official Build) (64-bit)
-- | --
Revision | ebcfb87c1393f36955cfa2f6451a1767e3dc3ee5-refs/branch-heads/5790@{#1193}
OS | Windows 10 Version 22H2 (Build 19045.3086)

```
