### ISSUE TITLE
Wallet `window.ethereum` provider is not injected into existing tabs after wallet creation

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#30873]
## Description 

When a Brave Wallet is created, the `window.ethereum` provider is not injected into existing tabs. This is due to the `BraveRendererUpdater` not updating the renderer configuration upon wallet creation.

Probably the same issue for `window.solana`.

## Steps to Reproduce

   1. Start with fresh profile
   2. Open brave.com. Open dev tools and verify that `window.ethereum` is undefined.
   3. In another tab, setup Brave Wallet.
   4. Reload the brave.com tab, re-evaluate `window.ethereum`.

## Actual result:

`window.ethereum` is undefined

## Expected result:

Should be populated.

## Reproduces how often: 

Easily

## Brave version (brave://version info)

1.52.x+

cc @cypt4

**Comment by kjozwiak** [comment]
The above requires `1.53.106` or higher for `1.53.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.53.108 Chromium: 115.0.5790.56 (Official Build) (64-bit)
-- | --
Revision | ebcfb87c1393f36955cfa2f6451a1767e3dc3ee5-refs/branch-heads/5790@{#1193}
OS | Windows 10 Version 22H2 (Build 19045.3086)
```
- Verified the description from the issue https://github.com/brave/brave-browser/issues/30873#issue-1744773938
- Confirmed that when `window.ethereum` is executed via console in dev tool, `Brave wallet` enabled "true" and other parameters are populated  in `1.53.108`
![image](https://github.com/brave/brave-browser/assets/38657976/be93614c-d036-434e-b5d3-7bff6d8fa6d0)
