### ISSUE TITLE
Vertical tab is not resizable when `sticky pinned tabs` flag is enabled

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#30877]
## Steps to Reproduce

   1. Enable vertical tab and check it's resizable
   2. Enable `sticky pinned tabs` from brave://flags
   3. Relaunch and check vertical tab is resizable

## Actual result:

Not resizable

## Expected result:
Resizable

## Reproduces how often: 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @sangwoo108

**Comment by sangwoo108** [comment]
https://github.com/brave/brave-core/pull/18724 would fix this together.

**Comment by LaurenWags** [comment]
@rebron @sangwoo108 could one of you please determine if this is `release-notes/include` or `release-notes/exclude` please? Thanks!

**Comment by MadhaviSeelam** [comment]
Verification `In progress`  using 
```
Brave | 1.54.90 Chromium: 115.0.5790.56 (Official Build) beta (64-bit)
-- | --
Revision | ebcfb87c1393f36955cfa2f6451a1767e3dc3ee5-refs/branch-heads/5790@{#1193}
OS | Windows 11 Version 22H2 (Build 22621.1848)
```

1. Installed 1.54.90
2. launched Brave
3. opened few tabs
4. enabled vertical tabs via context menu
5. verified able to resize the vertical tab panel
6. opened brave://flags
7. enabled `#brave-vertical-tabs-stick-pinned-tabs`


- Confirmed able to resize the vertical tab panel with `#brave-vertical-tabs-stick-pinned-tabs` enabled
- Additionally verified vertical tab panel can be resized with  `#brave-vertical-tabs-stick-pinned-tabs` `Disabled` and `Default` selections. 


https://github.com/brave/brave-browser/assets/98358127/9de85de6-0e55-439a-9840-7cb31a1cf36a
