### ISSUE TITLE
Make NTP background images service available to iOS

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-browser#30871]
## Description 

The `ntp_background_images` component needs to be updated to be available for iOS to wrap and use in brave-ios

## Test Case

Sanity test background images/sponsored images on desktop/android. iOS will be tested in a later PR

**Comment by kjozwiak** [comment]
The above requires `1.53.96` or higher for `1.53.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave | 1.53.99 Chromium: 114.0.5735.133 (Official Build) beta (64-bit)
-- | --
Revision | fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}
OS | Windows 10 Version 22H2 (Build 19045.3086)

```
Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/30871#issue-1744611079, ensured that both NTP & NTP SI images were being displayed/working as expected.

- Confirmed that new background image is displayed when a new tab is opened
- Confirmed that the background image in NTP is not repeated
- Confirmed that NTP SI is displayed at 2nd, 4th and 8th tabs so on... as expected.
