### ISSUE TITLE
Move `Improve search suggestions` option to brave://settings/search

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#30878]
## Description 

Move `Improve search suggestions` options from brave://settings/privacy to below the Normal Window search engine setting in brave://settings/search

## Steps to Reproduce

   1. Load brave://settings/search and check `Improve search suggestions` option is visible
   2. Load brave://settings/privacy and check `Improve search suggestions` option is hidden
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.54.90 Chromium: 115.0.5790.56 (Official Build) beta (64-bit)
-- | --
Revision | ebcfb87c1393f36955cfa2f6451a1767e3dc3ee5-refs/branch-heads/5790@{#1193}
OS | Windows 11 Version 22H2 (Build 22621.1848)
```
Install 1.54.90
launch Brave
open brave://settings/search in a new tab
open brave://settings/privacy in a new tab

Confirmed `Improve search suggestions` setting is visible and toggled `Off` as a default
Confirmed `Improve search suggestions` settings is not shown 

brave://settings/search | brave://settings/privacy
----- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/a91d267a-bfe1-48c0-8e29-8df477ef3f14)|![image](https://github.com/brave/brave-browser/assets/98358127/e79f84bd-8d59-4080-92be-f88141375f7a)
