### ISSUE TITLE
Incorrect state of VPN button when user refreshes credentials

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#30881]
## Description 

Incorrect state of VPN button when user refreshes credentials

## Steps to Reproduce

   1. Refresh VPN credentials from `https://account.brave.com`
   2. Wait for the Panel to load the VPN state
   3. Button is disabled but VPN is enabled
   4. If you have multiple profiles it shows correctly when launching other profile

## Actual result:

![image](https://github.com/brave/brave-browser/assets/17010094/2a920950-51c0-41a6-8da8-d2e3f87d527e)
![image](https://github.com/brave/brave-browser/assets/17010094/1f1bd294-3e2d-438b-bef1-4aea858901a1)

## Expected result:
Should show correct state

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.54.38 Chromium: 114.0.5735.90 (Official Build) nightly (64-bit)
-- | --
Revision | `386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}`
OS | Windows 11 Version 22H2 (Build 22621.1778)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? Maybe
- Can you reproduce this issue with the beta channel? Maybe
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @bsclifton @brave/qa-team

**Comment by simonhong** [comment]
Trying to repro.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.54.91 Chromium: 115.0.5790.56 (Official Build) beta (64-bit)
-- | --
Revision | ebcfb87c1393f36955cfa2f6451a1767e3dc3ee5-refs/branch-heads/5790@{#1193}
OS | Windows 11 Version 22H2 (Build 22621.1848)
```

Verified using STR from https://github.com/brave/brave-browser/issues/30881#issue-1745298667 & https://github.com/brave/brave-browser/issues/30881#issuecomment-1584057475


#### Confirmed VPN button shows correct state (with green check mark ✅) when VPN is connected via VPN panel & OS settings
#### Confirmed VPN button shows correct state (with gray minus ➖) if VPN is disconnected 
#### Confirmed VPN button shows correct state (with red VPN button) if VPN connection fails

Connected | Disconnected | Failed
---- | ---- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/85d7b97f-b644-4552-af4c-ea4cbb0eff0a)
![image](https://github.com/brave/brave-browser/assets/98358127/c7fa0297-98fa-4744-a7c5-2705342cf0e8)
![image](https://github.com/brave/brave-browser/assets/98358127/695fd7e0-f119-4755-b756-1bd482c24591)

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.57.36 Chromium: 115.0.5790.171 (Official Build) beta (x86_64)
-- | --
Revision | a4bb683f14dc402f5da13707e13559dc4d5ef08b
OS | macOS Version 14.0 (Build 23A5301h)
