### ISSUE TITLE
[Commands]: Open shortcuts command still has the old url

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#30880]
## Steps to Reproduce

   1. Open the command palette (CTRL+Space with the quick-commands flag enabled)
   2. Search for shortcuts
   3. Press enter

## Actual result:
chrome://commands is opened, which doesn't load (because the url changed)

## Expected result:
chrome://settings/system/shortcuts is opened and you can edit shortcuts.

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.53.100` or higher for `1.53.x` verification 👍

**Comment by LaurenWags** [comment]
Verified with

```
Brave | 1.53.100 Chromium: 114.0.5735.133 (Official Build) beta (x86_64)
-- | --
Revision | fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}
OS | macOS Version 13.4 (Build 22F66)
```

Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/30880#issue-1744976826, ensured that selecting `Shortcuts` via the URL bar while `brave://flags/#quick-commands` is enabled opens `brave://settings/system/shortcuts` without any issues.
