### ISSUE TITLE
Download bubble doesn't open up when a file download is completed

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#30882]
## Description 

Download bubble doesn't open up when a file download is completed

## Steps to Reproduce

   1. Install 1.51.x and download a file
   2. Download bubble opens up when the file download is completed
   3. Upgrade to 1.52.x and download a second file
   4. Download bubble doesn't automatically open up when the file download is completed

## Actual result:

Download bubble doesn't open up when a file download is completed

## Expected result:
Probably open the download bubble when the download is complete 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

1.52.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? Not checked but @GeetaSarvadnya mentioned its the same

## Miscellaneous Information:

cc: @rebron @simonhong @brave/qa-team

**Comment by stephendonner** [comment]
Here's @GeetaSarvadnya 's screencast showing it in action, in `1.51.x`:

![1 51](https://github.com/brave/brave-browser/assets/387249/05284018-69e2-42b6-a182-1ad053b685a4)

**Comment by kjozwiak** [comment]
The above requires `1.52.125` or higher for `1.52.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.52.125 Chromium: 114.0.5735.110 (Official Build) (64-bit)
-- | --
Revision | 1c828682b85bbc70230a48f5e345489ec447373e-refs/branch-heads/5735_90@{#13}
OS | Windows 10 Version 22H2 (Build 19045.2965)
```
