### ISSUE TITLE
Request Feature button overlaps nav on Send Screen

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#30885]
## Description 

The `Request Feature` button overlaps the bottom nav on Send Screen

## Steps to Reproduce

   1. Go to the `Send` screen
   2. Decrease the `Browser` width until the nav snaps to the bottom
   3. The `Request Feature` button overlaps the nav

## Actual result:

https://github.com/brave/brave-browser/assets/40611140/b6534fde-96aa-4d48-89e6-e7875461584a

## Expected result:
The `Request Feature` button should disappear once the nav moves to the bottom of the screen.

https://github.com/brave/brave-browser/assets/40611140/30c66ece-a9a4-4563-96dd-d35ef92af951

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.57.24 Chromium: 115.0.5790.136 (Official Build) beta (64-bit)
-- | --
Revision | `8099932ede6f8d4624fbddf39d27abb3b340d8c9`
OS | Linux

- Verified steps from [brave/brave-core#18790](https://github.com/brave/brave-core/pull/18790)
- Verified `Request Feature` button is not shown any more on Send Screen when the browser window size is reduced to move the navigation bar to the bottom of the screen.

https://github.com/brave/brave-browser/assets/17010094/70746bbb-0893-4a19-98d9-a10795a71dfc



---------------------

**Verification passed on**

Brave | 1.57.24 Chromium: 115.0.5790.136 (Official Build) beta (64-bit)
-- | --
Revision | `8099932ede6f8d4624fbddf39d27abb3b340d8c9`
OS | Windows 11 Version 22H2 (Build 22621.1992)

- Verified steps from [brave/brave-core#18790](https://github.com/brave/brave-core/pull/18790)
- Verified `Request Feature` button is not shown any more on Send Screen when the browser window size is reduced to move the navigation bar to the bottom of the screen.

https://github.com/brave/brave-browser/assets/17010094/227d8395-0576-4503-a1d1-00d95eae3b6c


---------------------

**Verification passed on**

Brave | 1.57.24 Chromium: 115.0.5790.136 (Official Build) beta (arm64)
-- | --
Revision | `8099932ede6f8d4624fbddf39d27abb3b340d8c9`
OS | macOS Version 13.4.1 (c) (Build 22F770820d)

- Verified steps from [brave/brave-core#18790](https://github.com/brave/brave-core/pull/18790)
- Verified `Request Feature` button is not shown any more on Send Screen when the browser window size is reduced to move the navigation bar to the bottom of the screen.

https://github.com/brave/brave-browser/assets/17010094/ab71d3d9-5dc6-4a4e-8f0a-ff999cbeb6f3
