### ISSUE TITLE
[Bug] Toolbar dial and other NTP extensions will show Brave NTP on restart 

### ISSUE THREAD

**Issue by Joovsr** [brave/brave-browser#30890]
Hello. I don't like the default new tab layout in this browser. Therefore, I use a third-party extension - "toolbar dial". It replaces the default new tab layout.
The bug is that if you create a new empty tab and then restart the browser, the old native start screen is displayed in the new tab! When creating further new tabs already the extension works fine.
In google chrome, everything works as it should - at startup, the previous tabs open and if there are confusing ones among them, then the "toolbar dial" works as it should.
I think the problem is with all extensions that replace the default new tab screen.
Thank you.

`https://chrome.google.com/webstore/detail/toolbar-dial/nejdcfinmjpapnkjffcejgcidjmbipcp?hl=en`

**Comment by rebron** [comment]
We'll want to verify that isn't a problem with another extension too like `https://chrome.google.com/webstore/detail/momentum/laookkfknpbbblfpciffpaejjkokdgca`

**Comment by MadhaviSeelam** [comment]
@rebron  reproduced this issue in 1.52.122 with both the extensions. 
```
Brave | 1.52.122 Chromium: 114.0.5735.110 (Official Build) (64-bit)
-- | --
Revision | 1c828682b85bbc70230a48f5e345489ec447373e-refs/branch-heads/5735_90@{#13}
OS | Windows 11 Version 22H2 (Build 22621.1702)
```
https://github.com/brave/brave-browser/assets/98358127/086c70f3-ca38-4216-8b80-b6729f9d395b


https://github.com/brave/brave-browser/assets/98358127/e2a1e4a2-34c8-4930-879e-29367f1ede00

**Comment by MadhaviSeelam** [comment]
@rebron 

`brave://settings`

![image](https://github.com/brave/brave-browser/assets/98358127/2c7d2716-52c8-489e-8848-22d873957ff3)


another way to reproduce the issue

https://github.com/brave/brave-browser/assets/98358127/f0976957-b7e5-4797-afab-0c66badfd94c

**Comment by simonhong** [comment]
Confirmed that newtab url overriding is done  via `ExtensionWebUI::RegisterOrActivateChromeURLOverrides()` before tab restoring during the startup. but restored new tab doesn't use overridden url. Checking..

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.57.8 Chromium: 115.0.5790.75 (Official Build) beta (64-bit)
-- | --
Revision | 77bffd419b7e89d7e666c9695e7fa0d1d0367a99
OS | Windows 11 Version 22H2 (Build 22621.1992)
```

Case 1: Install Tooldial extension

1. Install 1.57.8
2. launch Brave
3. install following extension in chrome.google.com/webstore
    - https://chrome.google.com/webstore/detail/toolbar-dial/nejdcfinmjpapnkjffcejgcidjmbipcp?hl=en
4. open a new tab    
5. verified `ToolbarDial` NTP page is shown
6. clicked `Keep it`    
7. click a new tab
8. verified Brave NTP page is not shown as expected   
9. close Brave and relaunch 
10. opened brave://settings

Confirmed Brave NTP is not shown.
Confirmed when clicked to open new tabs, Toolbar dial tabs are opened 
Confirmed ` Toolbar is controlling this setting.. ` message shown

step 3 | step 5 | step 8 | step 9 | step 10
------ | ----- | ----- | ----- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/4bd1f30a-40cb-4cba-8d48-c1a69d59ce78)|![image](https://github.com/brave/brave-browser/assets/98358127/3aa2a407-ac8e-4580-9c14-9a8db4c41117)|![image](https://github.com/brave/brave-browser/assets/98358127/89716297-549a-4b55-b8ab-d9fedd0d8c2d)|![image](https://github.com/brave/brave-browser/assets/98358127/e71f9057-e709-427a-8fe3-ec30c04007af)|![image](https://github.com/brave/brave-browser/assets/98358127/5329e504-3307-42f4-8b3d-078a79d79933)


Case 2: Install Momentum extension
1. new profile 
2. launch Brave
3. install following extension in chrome.google.com/webstore
    - https://chrome.google.com/webstore/detail/momentum/laookkfknpbbblfpciffpaejjkokdgca
4. verified `Momentum` NTP page is shown in a new tab
6. clicked `Keep it`    
7. click a new tab
8. verified Brave NTP page is not shown as expected   
9. close Brave and relaunch 
10. opened brave://settings

Confirmed Brave NTP is not shown.
Confirmed when clicked to open new tabs, `Momentum` tabs are opened 
Confirmed ` Momentum is controlling this setting.. ` message shown

step 3-4 | step 8-9 | step 10
---- | ---- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/bd0402e0-5a85-421d-8f96-eef532a365c9)|![image](https://github.com/brave/brave-browser/assets/98358127/61d4e187-2f94-417a-ac72-4f7b854c5e4a)|![image](https://github.com/brave/brave-browser/assets/98358127/e0a60f96-0524-428f-8231-4525eb76204e)
