### ISSUE TITLE
Force aggressive cosmetic filtering on YouTube

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#30896]
https://github.com/brave/brave-browser/issues/17607 applied aggressive cosmetic filtering mode for network blocking. We need to apply the same treatment to cosmetic filtering.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.58.89 Chromium: 116.0.5845.82 (Official Build) beta (x86_64)
-- | --
Revision | 178049e05b89fc5bcb71ae5d2af40e095246c2d4
OS | macOS Version 11.7.9 (Build 20G1426)
```

### Steps:
1. installed `1.58.89`
2. launched Brave
3. loaded `youtube.com`
4. found the `YouTube` `Free with ads` movies: `https://www.youtube.com/feed/storefront?bp=ogUCKAY%3D`
5. played a movie
6. clicked on the shields icon, clicked `Advanced Controls`
7. confirmed `Block trackers & ads` 
8. changed the player's seek position, to try to trigger ads
9. changed shield's setting to `Aggressively block trackers & ads`
10. loaded the `youtube.com` homepage, and generally clicked around for a while
11. switched back to `Block trackers & ads` and clicked around
12. finally, disabled shields and noted the ads

example | example | example
---------|---------|----------
<img width="1312" alt="Screen Shot 2023-08-15 at 2 59 24 PM" src="https://github.com/brave/brave-browser/assets/387249/43dfd29c-525c-4520-9b30-dedf25fce644"> | <img width="1312" alt="Screen Shot 2023-08-15 at 3 02 20 PM" src="https://github.com/brave/brave-browser/assets/387249/f0a515c0-5464-422c-a6a8-3350f9ea90bf"> | <img width="1383" alt="Screen Shot 2023-08-15 at 3 04 12 PM" src="https://github.com/brave/brave-browser/assets/387249/cbbff3d9-8552-4b00-ae4b-5c262302df85">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.58.96 Chromium: 116.0.5845.96 (Official Build) beta (64-bit)
-- | --
Revision | 153399f19fc2a3db55e64efb3ad06cb52d8a39fb
OS | Windows 11 Version 22H2 (Build 22621.2134)
```


Steps:

1. installed 1.58.96
2. launched Brave
3. loaded youtube.com
4. found and played YouTube Free with ads movies: https://www.youtube.com/watch?v=INWZNWBIqRY (The Big Trip)
5. clicked on the Shields icon, clicked Advanced Controls
6. confirmed Block trackers & ads
7. changed the player's seek position, to try to trigger ads 
8. changed shield's setting to Aggressively block trackers & ads and movie reloaded and no ads are shown
9. loaded the youtube.com homepage, and generally clicked around for a while
10. switched to Allow all trackers and & ads and previously played video reloaded to show ads
11. finally, disabled shields and noted the ads

Confirmed:
  - no pre-roll or interstitial ads when viewing The Hunger Games with either:
  - Block trackers & ads (default) Brave Shields setting
  - Aggressively block trackers & ads setting
  - pre-roll, interstitial, and static (top-right) ads returned when Brave Shields was either disabled or set to Allow all trackers & ads


### Ad-sponsored movie (`The Big Trip`)

`Block trackers & ads` | `Aggressively block trackers & ads` | `Allow all trackers & ads` | `Brave Shields, down` 
---------|----------|---------|---------
<img width="958" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/32ccfc2b-055e-4467-b0a2-857df142be93">|<img width="920" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/db4b9b00-036f-4c3c-9eb7-e3fabafaf02c">|<img width="957" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/cd17a6b9-35d2-4754-8b01-12553937701b">|<img width="918" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/c35c5f6c-e5ac-4c6a-8a1b-8a5a2ebf4436">

`CNN.com`

`Block trackers & ads` | `Aggressively block trackers & ads` | `Allow all trackers & ads` | `Brave Shields, down` 
---------|----------|---------|---------
<img width="959" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/f0ea7626-4da1-4f33-b4a3-db79a434657d">|<img width="919" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/3dd0c280-a664-4664-9a72-cebcafa3c427">|<img width="953" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/02794dfe-a483-495a-b5e3-8fcdd8099767">|<img width="946" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/2f8590e0-3000-4837-9e91-176163789c92">

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using



## Steps:
1. installed 1.58.101
2. launched Brave
3. loaded youtube.com
4. found and played YouTube Free with ads movies: https://www.youtube.com/watch?v=INWZNWBIqRY (The Big Trip)
5. clicked on the Shields icon, clicked Advanced Controls
6. confirmed Block trackers & ads
7. changed the player's seek position, to try to trigger ads 
8. changed shield's setting to Aggressively block trackers & ads and movie reloaded and no ads are shown
9. loaded the youtube.com homepage, and generally clicked around for a while
10. switched to Allow all trackers and & ads and previously played video reloaded to show ads
11. finally, disabled shields and noted the ads

### Confirmed:
  - no pre-roll or interstitial ads when viewing The The Big Trip with either:
  - Block trackers & ads (default) Brave Shields setting
  - Aggressively block trackers & ads setting
  - pre-roll, interstitial, and static (top-right) ads returned when Brave Shields was either disabled or set to Allow all trackers & ads


### Ad-sponsored movie (``)

`Block trackers & ads` | `Aggressively block trackers & ads` | `Allow all trackers & ads` | `Brave Shields, down` 
---------|----------|---------|---------


`huffpost.com`

`Block trackers & ads` | `Aggressively block trackers & ads` | `Allow all trackers & ads` | `Brave Shields, down` 
---------|----------|---------|---------


`YouTube.com`

`Block trackers & ads` | `Aggressively block trackers & ads` | `Allow all trackers & ads` | `Brave Shields, down` 
---------|----------|---------|---------

**Comment by Uni-verse** [comment]
In Progress on Android ARM

**Comment by Uni-verse** [comment]
In progress on `Samsung Tab S7` using version(s):

```
Brave	1.58.117 Chromium: 116.0.5845.180 (Official Build) (64-bit) 
Revision	99255ad6abf2fa399c063683c051f973e1f5c0af
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

**Comment by Uni-verse** [comment]
Verified on `Pixel 2XL` using version(s):

```
Brave	1.58.117 Chromium: 116.0.5845.180 (Official Build) (64-bit) 
Revision	99255ad6abf2fa399c063683c051f973e1f5c0af
OS	Android 8.1.0; Build/OPM2.171026.006.H1; 27; REL
```
Test Plan: https://github.com/brave/brave-core/pull/18813#issue-1747055830

- Ensured preroll ads and content ads are not shown on youtube.com when using `Block trackers & ads` & `Aggressively block trackers & ads`
- Ensured bringing Shields down will disable ad blocking on youtube. Preroll and content ads will be shown
- Ensured that setting Ad Block settings in shields panel to `Allow all trackers & ads` will display ads and preroll ads

Example | Example | Example
-|-|-
![Screenshot 2023-09-08 at 2 16 15 PM](https://github.com/brave/brave-browser/assets/17885425/a8926959-eecd-4d2d-9a4d-22f9cc87857b) | ![Screenshot 2023-09-08 at 2 16 59 PM](https://github.com/brave/brave-browser/assets/17885425/ba3b7d87-b090-4dc3-a16d-470561808f9d) | ![Screenshot 2023-09-08 at 2 17 16 PM](https://github.com/brave/brave-browser/assets/17885425/09a10084-af95-4ff2-b04f-c45eb921162a)
