### ISSUE TITLE
Vertical tabs hide animation results in favicons shifting rapidly

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#30897]
## Description 

When in minimized mode and un-hovering from the floating vertical tab strip, the favicons bounce a few pixels from side to side

Version 1.54.38
macOS

**Comment by EtFX1** [comment]
> The new version of vertical tabs don't appear in fullscreen. So not tab at all in fullscreen

good, so i know I'm not the only one.

**Comment by sangwoo108** [comment]
Hi, we'd removed vertical tab strip on fullscreen but decided to revert it as it's imperfect fix. Please refer to https://github.com/brave/brave-browser/issues/33020
