### ISSUE TITLE
(tracking) Brave News Tab Helper causes high cpu parsing feeds on Tab navigation

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#30898]
## Description 

As per https://github.com/brave/brave-browser/issues/29125 it seems like the root cause of high cpu on some sites is parsing all the rss feeds found on any page. Some feeds are large and take some cpu time to parse. This is to power the "Follow this source in 1-click" feature:
<img width="528" alt="image" src="https://github.com/brave/brave-browser/assets/741836/f257d4ee-d0d9-42a7-a3ba-9249e23321fe">

As a result, after verifying this is the issue, or regardless, we should consider:
- Only check for <link> and parse the feeds if brave news is enabled, since the "follow this source" UI won't be shown anyway
- Fetch the <link> elements, but don't parse them until the user opens the panel (and show loading indicator whilst open). With this, we'll still be able to know to show the icon and the followed/unfollowed state since we'll have the feed URLs.
- To get the feed title, perhaps don't parse the whole feed, but just enough to find the title element.

Thanks to @arthuredelstein for figuring out the potential (and probable) cause of https://github.com/brave/brave-browser/issues/29125 and thinking about the solution.

## Steps to Reproduce

   1. 
   2. 
   3. 

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by petemill** [comment]
Since the speed improvements of https://github.com/brave/brave-core/pull/17923 is so great, perhaps the only thing left to do is 
- Only check for and parse the feeds if brave news is enabled, since the "follow this source" UI won't be shown anyway
What do you think @fallaciousreasoning ?

**Comment by fallaciousreasoning** [comment]
That sounds about right :smile:
