### ISSUE TITLE
New keybinding popup dialog needs better `Dark`-mode treatment

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#30895]
## Description 

New keybinding popup dialog needs better `Dark`-mode treatment

## Steps to Reproduce

1. install `1.54.44`
2. launched Brave
3. opened `brave://flags`
4. set `brave://flags/#brave-commands` to `Enabled`
5. clicked `Relaunch`
6. opened `brave://settings/system/shortcuts`
7. clicked on `Add`
8. press some keys
9. hover over the `Cancel` button

## Actual result:

![image](https://github.com/brave/brave-browser/assets/387249/7aa48e42-bade-45be-a414-53db2dc742e7)

## Expected result:

The dialog should be themed for `Dark` mode

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.54.44 Chromium: 114.0.5735.110 (Official Build) nightly (64-bit)
-- | --
Revision | 1c828682b85bbc70230a48f5e345489ec447373e-refs/branch-heads/5735_90@{#13}
OS | Windows 10 Version 22H2 (Build 19045.3031)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron @fallaciousreasoning @aguscruiz @brave/qa-team

**Comment by stephendonner** [comment]
Found while testing https://github.com/brave/brave-browser/issues/29349

**Comment by fallaciousreasoning** [comment]
I'm going to fix this by migrating to the Leo Dialog component (it didn't exist when I started this). I was playing around with the keyboard focus and I've deliberately disabled tabbing to the buttons (which makes it easier to make shortcuts with Tab in them) but if you press `Enter` by itself it will accept the shortcut (if it's valid) or if you press `Escape` it will cancel.

**Comment by fallaciousreasoning** [comment]
**Note:** The new dialog backdrop is more subtle, which is intentional :smile:

**Comment by stephendonner** [comment]
> I'm going to fix this by migrating to the Leo Dialog component (it didn't exist when I started this). I was playing around with the keyboard focus and I've deliberately disabled tabbing to the buttons (which makes it easier to make shortcuts with Tab in them) but if you press `Enter` by itself it will accept the shortcut (if it's valid) or if you press `Escape` it will cancel.

Oops, yeah, I'm now laughing at my suggestion to `tab` through the dialog, as that keypress and others will get eaten/captured by the dialog ;-)

**Comment by kjozwiak** [comment]
The above requires `1.53.100` or higher for `1.53.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.53.102 Chromium: 114.0.5735.133 (Official Build) (x86_64)
-- | --
Revision | fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}
OS | macOS Version 13.4.1 (Build 22F82)
```
