### ISSUE TITLE
`Send` tip button doesn't get activated when min custom tip of `0.25 BAT` is entered

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#30909]
## Description 
Found while testing https://github.com/brave/brave-browser/issues/28149
`Send` tip button doesn't gets activated when min custom tip of `0.25 BAT` is entered
## Steps to reproduce 

**Case 1:**

   1. Clean profile 1.53.x
   2. Enable rewards and connect uphold custodian
   3. Open the uphold verified creator laurenwags.github.io
   4. Open the tipping banner and click on the `Custom` 
   2. Enter the custom tip mini amount of `0.25 BAT` 
   3. `Send` tip button doesn't get activated when min custom tip of `0.25 BAT` is entered

**Case 2:**

   1. Clean profile 1.53.x
   2. Enable rewards and connect uphold custodian
   3. Open the uphold verified creator laurenwags.github.io
   4. Open the tipping banner and click on the `Custom` 
   2. Enter the custom tip mini amount of `0.26 BAT` 
   3. Send button gets activated
   4. Click on the up and down arrow to convert the USD and BAT values
   5. The custom tip amount `0.26 BAT` is rounded to `0.25 BAT` as expected but the `Send` button is not activated
   6. `Send` tip button doesn't get activated when min custom tip of `0.25 BAT` is entered

## Actual result 
`Send` tip button doesn't get activated when min custom tip of `0.25 BAT` is entered

![image](https://github.com/brave/brave-browser/assets/38657976/9cbc9b0e-7aac-4dcb-b733-8cd09df384ce)

## Expected result

The `Send` tip button should get activated when min custom tip of `0.25 BAT` is entered
## Issue reproduces how often 

Easy
## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86): all
   - Device type (Phone, Tablet, Phablet): all
   - Android version: 12
   
## Brave version
1.53.83

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/qa-team @Miyayes @deeppandya @sujitacharya2005

**Comment by kjozwiak** [comment]
The above requires `1.53.96` or higher for `1.53.x` verification 👍
