### ISSUE TITLE
Filecoin EVM Testnet shown in Secondary Networks list (Android)

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#30903]
## Description 

> Filecoin EVM Testnet should be shown with the Goerli testnet and Sepolia testnet, not in the Secondary Networks list.

Android issue for https://github.com/brave/brave-ios/issues/7583

## Expected result
Show File coin testnet under Ethereum

### Additional information

[Discussion thread](https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1686161405273159)

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.57.18 x64 Beta build
- Verified steps from [brave/brave-core#18818](https://github.com/brave/brave-core/pull/18818)
- Verified Filecoin EVM Testnet is shown under Ethereum

Oppo Reno 5 (Android 13) | Lenovo Tab (Android 12)
-- | --
<video src=https://github.com/brave/brave-browser/assets/17010094/e338df9e-c1f5-4656-b457-d48c8084ab58> | <video src=https://github.com/brave/brave-browser/assets/17010094/84804ab7-52dc-40f2-ac98-d70f27189366>
