### ISSUE TITLE
`You don't have enough tokens` message is not refreshed/removed from the tipping banner when the tip amount is lesser than the wallet balance

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#30907]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/28149
`You don't have enough tokens` message is not refreshed/removed from the tipping banner when the tip amount is lesser than the wallet balance

## Steps to reproduce 

   1. Clean profile 1.53.x
   2. Enable rewards and connect uphold custodian
   3. Open the uphold verified creator laurenwags.github.io
   4. Open the tipping banner and click on the `Custom` 
   5. Enter the custom amount which is greater than the wallet balance
   6. Confirm that the `You don't have enough tokens` message is displayed as expected
   7. Enter the custom tip amount lesser than the wallet balance
   8. `You don't have enough tokens` message is STILL disaplyed which is not correct
   

## Actual result 

`You don't have enough tokens` message is not refreshed/removed from the tipping banner when the tip amount is lesser than the wallet balance
![Screenshot_20230609_145909](https://github.com/brave/brave-browser/assets/38657976/435bae73-7362-4305-acf9-8fcc746e94ca)

## Expected result
`You don't have enough tokens` message should not be shown when the tip amount is lesser than the wallet balance

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86): all 
   - Device type (Phone, Tablet, Phablet):all
   - Android version: 12
   
## Brave version

1.53.83
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/qa-team @Miyayes @deeppandya @sujitacharya2005

**Comment by kjozwiak** [comment]
The above requires `1.53.96` or higher for `1.53.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.53.99`

- Verified the STR from the issue https://github.com/brave/brave-browser/issues/30907#issue-1747518464
- Confirmed that `You don't have enough tokens message` is NOT shown when the entered custom tip amount lesser than the wallet balance

_One-time tip_

Example | Example
----------|---------



_Monthly tips_

Example | Example
----------|---------
