### ISSUE TITLE
Add licensing info for Brave VPN WireGuard Service

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#30902]
The [Brave VPN WireGuard Service](https://github.com/brave/brave-core/tree/master/components/brave_vpn/browser/connection/wireguard/win/brave_vpn_wireguard_service) is a separate executable that the browser uses in order to start/stop VPN connections.

It is licensed under a different license from Brave ([GPL-2.0-or-later](https://spdx.org/licenses/GPL-2.0-or-later.html)) and it uses the following third-party libraries:
- https://git.zx2c4.com/wireguard-nt/about/
- https://git.zx2c4.com/wireguard-windows/about/

**Comment by LaurenWags** [comment]
@fmarier is this Windows only?

**Comment by fmarier** [comment]
The licensing info is actually the same for all platforms (we have https://github.com/brave/brave-browser/issues/9936 to fix this).

However in this specific case, we ended up reverting this change temporarily and so if you look at `brave://credits` today you'll see that _Brave VPN WireGuard Service_ is showing the Mozilla Public License.

**Comment by fmarier** [comment]
Marking as `QA/No` since this change is no longer in Nightly.

**Comment by LaurenWags** [comment]
Thanks @fmarier!
