### ISSUE TITLE
Unable to empty or make the custom tip value to 0.0 always 5 BAT is displayed in the text box

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#30908]
## Description 
Found while testing https://github.com/brave/brave-browser/issues/30907
Unable to empty or make the custom tip value to 0.0 always 5 BAT is displayed in the text box
## Steps to reproduce 

**Case 1:**

   1. Clean profile 1.53.x
   2. Enable rewards and connect uphold custodian
   3. Open the uphold verified creator laurenwags.github.io
   4. Open the tipping banner and click on the `Custom` 
   2. Put cursor on the `0.0 BAT` textbox
   3. Use backspace to remove `0.0 BAT` 
   4. Always 5 BAT is shown in the textbox  

**Case 2:**

   1. Clean profile 1.53.x
   2. Enable rewards and connect uphold custodian
   3. Open the uphold verified creator laurenwags.github.io
   4. Open the tipping banner and select any default tip amount (e.g 10.5)
   5. Click on the `Custom` 
   2. Put cursor on the `10.5 BAT` textbox
   3. Use backspace to remove `10.5 BAT` 
   4. Always `5 BAT` is shown in the textbox  after removing `10.5 BAT`

   

## Actual result 

Unable to empty or make the custom tip value to 0.0 always 5 BAT is displayed in the text box
![image](https://github.com/brave/brave-browser/assets/38657976/445626e1-d063-4b12-8bb1-058b3723b11e)

## Expected result
should work same as Desktop

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86): all
   - Device type (Phone, Tablet, Phablet): all
   - Android version: 12
   
## Brave version
1.53.83

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/qa-team @Miyayes @deeppandya @sujitacharya2005

**Comment by sujitacharya2005** [comment]
https://github.com/brave/brave-core/pull/18841

**Comment by kjozwiak** [comment]
The above requires `1.53.96` or higher for `1.53.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Vivo X70 Pro version 12` running `Bravemonoarm64.aok_1.53.99`
