### ISSUE TITLE
Ads subdivision code is not being stored properly

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#30918]
## Description 

The Ads subdivision code (which can be set on the Rewards settings page) is not being stored correctly to Preferences. Instead of a code, the subdivision name is being stored.

## Steps to Reproduce

   1. Open Rewards settings and click the "config" button on the ads panel.
   2. Set the subdivision.
   3. Inspect Preferences

## Actual result:

<img width="499" alt="Screenshot 2023-06-08 at 11 07 56 AM" src="https://github.com/brave/brave-browser/assets/5995084/22dd96b6-58de-4623-be9d-7f83eadc897b">

## Expected result:

The stored value should be a code (e.g. `US-MA`)

## Additional Information

Likely related to https://github.com/brave/brave-core/pull/18753.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.57.27 Chromium: 115.0.5790.114 (Official Build) beta (64-bit) 
-- | --
Revision | 18977fb43f693d5a8deeb48bd1cfa52651d3f73e
OS | Ubuntu 18.04 LTS

Verified test plan from the description

<details>


</details>
