### ISSUE TITLE
Earth View extension cancels bookmark bar

### ISSUE THREAD

**Issue by noircir** [brave/brave-browser#3091]
## Description 

Earth View extension shows satellite images as wallpaper when opening a new tab. However, bookmark bar is not present. 
See attached comparison pictures: new tab in Brave Browser and in Google Chrome.

## Steps to Reproduce

   1. Install "Earth View from Google Earth" Chrome extension.
   2. Open a new tab.
   3. 

## Actual result:

No bookmark bar present.

## Expected result:
Bookmark bar is present.

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by noircir** [comment]
<img width="715" alt="screen shot 2019-01-24 at 4 14 04 pm" src="https://user-images.githubusercontent.com/22533804/51709436-5af50880-1ff4-11e9-9785-5516ab9fc798.png">
<img width="1262" alt="screen shot 2019-01-24 at 4 14 30 pm" src="https://user-images.githubusercontent.com/22533804/51709456-66483400-1ff4-11e9-9cfe-f1c9f96147fe.png">
<img width="587" alt="screen shot 2019-01-24 at 4 24 00 pm" src="https://user-images.githubusercontent.com/22533804/51709488-7cee8b00-1ff4-11e9-8acc-3c55d773b513.png">

**Comment by srirambv** [comment]
Is the bookmark bar enabled? 
![image](https://user-images.githubusercontent.com/17010094/51723622-cfc15480-207f-11e9-85ed-9a0b728d7ff8.png)

**Comment by noircir** [comment]
Ok, this is not an issue. Closing.
