### ISSUE TITLE
`You don't have enough token` message is shown when USD to BAT or vice versa conversion

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#30911]
## Description 
Found while testing https://github.com/brave/brave-browser/issues/28149
`You don't have enough token` message is shown when USD to BAT or vice versa conversion
## Steps to reproduce 

   1. Clean profile 1.53.x
   2. Enable rewards and connect uphold custodian
   3. Open the uphold verified creator laurenwags.github.io
   4. Open the tipping banner and click on the up and down arrow multiple times for the `0.0 BAT` BAT and USD conversion
   5. Make sure `0.0 BAT` is at the left side and `0.0 USD` is at the right side
   6. Select the default tip amount `5.0 BAT` or any default value
   7. Click on the up and down arrow multiple times for the USD and BAT conversion
   8. Incorrect `25.25 BAT` values is shown in the tipping banner which is incorrect
   9. `You don't have enough token` message is shown which is incorrect

**Note:** : Repeat the steps above for the default values `10.5 BAT` and `1.25 BAT`

## Actual result 

`You don't have enough token` message is shown when USD to BAT or vice versa conversion
![image](https://github.com/brave/brave-browser/assets/38657976/ffd9ff49-6aad-4b44-be2f-16eb64150397)

## Expected result
USD to BAT or vice versa conversion should happen correctly and `You don't have enough token` message should not be shown when the tip amount is lesser than the wallet balance

## Issue reproduces how often 

Easy
## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86): All
   - Device type (Phone, Tablet, Phablet): All
   - Android version: 12
   
## Brave version

1.53.83
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/qa-team @Miyayes @deeppandya @sujitacharya2005

**Comment by kjozwiak** [comment]
The above requires `1.53.96` or higher for `1.53.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.53.99`

- Verified the STR from the https://github.com/brave/brave-browser/issues/30911#issue-1747682796
- Confirmed that the `You don't have enough token` message is NOT shown during USD to BAT or vice versa conversion

https://github.com/brave/brave-browser/assets/38657976/6c758bff-3355-48b7-ad3a-a5a66e14afbb
