### ISSUE TITLE
Creation of desktop shortcut with default run of tor private browsing.

### ISSUE THREAD

**Issue by 413x-4rtur0** [brave/brave-browser#3092]
Hello i'm trying to create a desktop shortcut to run brave as new instance in **incognito Tor** mode app like google chrome run when modify the Target adding this, 

`%ProgramFiles(x86)%\Google\Chrome\Application\chrome.exe  --profile-directory=default --incognito --app="https://github.com/"`

These run on brave as incognito and trying this, but i there is a option to start the tor browser mode

`%ProgramFiles(x86)%\\BraveSoftware\Brave-Browser\Application\brave.exe --profile-directory=default --incognito --app="https://github.com/"`

There are some solution or operator to add?, Thanks.

**Comment by srirambv** [comment]
Tor windows are guest windows. As far as I know Chromium doesn't allow you to launch guest windows using command line switches. This would be possible when we implement Tor to have a separate profile https://github.com/brave/brave-browser/issues/1115 

cc: @riastradh-brave @darkdh to confirm this

**Comment by tomlowenthal** [comment]
Closed in favor of #2105.
