### ISSUE TITLE
`You're already sending a monthly contribution` message doesn't have the indicator icon

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#30923]
## Description 
Found while testing https://github.com/brave/brave-browser/issues/28149
`You're already sending a monthly contribution` message doesn't have the indicator icon
## Steps to reproduce 

   1. Clean profile 1.53.x
   2. Enable rewards and connect custodian
   3. Open laurenwags.github.io
   4. Set up a monthly contribution to this publisher
   5. Open the laurenwags.github.io panel and confirm that the monthly contribution is set
   6. Open the tipping banner
   7. `You're already sending a monthly contribution` message is displayed but the indicator icon is missing in the message

## Actual result 
![image](https://github.com/brave/brave-browser/assets/38657976/500a122a-e754-457d-ae1a-6b893784b36f)

## Expected result

**Desktop**
![image](https://github.com/brave/brave-browser/assets/38657976/d7f01f28-7401-4430-b969-f97c721f24ab)

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86): All
   - Device type (Phone, Tablet, Phablet):All
   - Android version: 12
   
## Brave version

1.53.83
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/qa-team @Miyayes @deeppandya @sujitacharya2005

**Comment by sujitacharya2005** [comment]
@GeetaSarvadnya 
This is expected.
All warning message will not show icon in mobile design. See this discussion in figma.

**The icon should only appear in the desktop version, since we have more space there.

In tablet and mobile, the icon doesn't appear.

It's not a general or universal rule, but more applies to this specific scenario of warnings inside this block.**
