### ISSUE TITLE
clear out loading indicator when asset discovery is not being run.

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#30921]
## Description 

Issue - loading indicator keeps going at the bottom of the wallet portfolio

Please see conversation here --> https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1686164364305479

Nick's comments - ´I think the loading indicator is not being cleared in cases when asset discovery is not being run on portfolio refresh due to rate limiting.  I think the frontend is waiting for an onDiscoverAssetsCompleted event that will never actually come.
<img width="984" alt="Screenshot 2023-06-07 at 20 13 03" src="https://github.com/brave/brave-browser/assets/12224304/298ee0ae-9f21-4f18-a1aa-7b4cf4b9ea0e">

The frontend might be assuming asset discovery is run on every single portfolio refresh, when it should only make that assumption when it receives a onDiscoverAssetsStarted event´

## Steps to Reproduce
 

   1. 
   2. 
   3. 

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by HEagle18** [comment]
@Douglashdaniel @nvonpentz to discuss exactly what's needed here.

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.62.123 x64 Beta build
- Verified steps from [brave/brave-core#20738](https://github.com/brave/brave-core/pull/20738)
- Verified loading state indicator is cleared when asset discovery is complete

https://github.com/brave/brave-browser/assets/17010094/abcb28e9-4e5c-4faf-80e8-31950cc40513

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.62.130 Chromium: 120.0.6099.199 (Official Build) beta (64-bit)
-- | --
Revision | `6d589c6dc0f3489830d40332c82cdd5597e41c88`
OS | Windows 11 Version 23H2 (Build 22631.2861)

- Verified steps from [brave/brave-core#20738](https://github.com/brave/brave-core/pull/20738)
- Verified loading state indicator is cleared when asset discovery is complete

https://github.com/brave/brave-browser/assets/17010094/6399f816-9747-43ce-8ca2-d72f2b81de79
