### ISSUE TITLE
Hide/Unhide NFT's is making unnecessary price history calls

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#30925]
## Description 

Hide/Unhide NFT's is making unnecessary price history calls causing the `Portfolio` balance to change.

## Steps to Reproduce

   1. Go to the NFT's tab and Hide/Unhide some nft's
   2. Price history will change sometimes.

## Actual result:

https://github.com/brave/brave-browser/assets/40611140/626ef8c2-002b-436d-b659-73d95a034a29

## Expected result:
We shouldn't need to update price history when hiding or unhiding nft's

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
@Douglashdaniel  think this is still happening as the price change happens when I hide/unhide NFTs

https://github.com/brave/brave-browser/assets/17010094/d117dc29-165c-4976-b832-f9317928e61b
