### ISSUE TITLE
Crash Report opening a new tab page

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#30932]
Brave Version: 1.53.85 Chromium: 114.0.5735.110
Operating System: Linux 6.2.6-76060206-generic

URL (if applicable) where crash occurred: new tab page

Can you reproduce this crash? No.

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. I hit Ctrl+t to open a new tab.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/79b20300-84d8-360a-0000-000000000000

**Comment by abbasnaqdi** [comment]
+1

**Comment by rebron** [comment]
@fmarier @sri I think maybe a dupe of https://github.com/brave/brave-browser/issues/30938

**Comment by punitkr03** [comment]
I am using Windows 11 and also facing the same issue but it's hard to reproduce and only occurs occasionally.

**Comment by abbasnaqdi** [comment]
+1
**Android** 11
Brave 1.51.121

**Comment by srirambv** [comment]
> @fmarier @sri I think maybe a dupe of #30938

Yes looks like it
