### ISSUE TITLE
Custodian mismatch message is displayed in the tipping banner for the grandfathered unconnected user in 1.53

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#30935]
## Description 
Found while testing https://github.com/brave/brave-browser/issues/28149
Custodian mismatch message is displayed in the tipping banner for the grandfathered unconnected user in 1.53
## Steps to reproduce 

   1. Clean profile 1.47.119 beta build
   2. Enable rewards and claim UGP grants or Ad garnts
   3. Upgrade the profile to 1.53.x
   4. Open the laurenwags.githu.io verified creator
   5. Open the tipping banner (there is UPHOLD icon disaplyed, logged https://github.com/brave/brave-browser/issues/30936)
   6. Confirmed that there is no mismatch custodian message on the tipping banner as expected
   7. Open github.com/miyayes verified creator
   8. Open the tipping banner
   9. Custodian mismatch message is displayed in the tipping banner
   10. Open alexvincentmusic.com verified creator
   11. Open the tipping banner
   12. Custodian mismatch message is displayed in the tipping banner
   

## Actual result 
Custodian mismatch message is displayed in the tipping banner for the grandfathered unconnected user in 1.53

Gemini | bitFlyer
--------|--------
![Screenshot_20230709_114808](https://github.com/brave/brave-browser/assets/38657976/bf22c655-3f7d-4f15-8cc3-895c1891c8c8) | ![Screenshot_20230709_114838](https://github.com/brave/brave-browser/assets/38657976/5b46d5dc-3e79-4230-9123-6cc7a02928da)
![Screenshot_20230609_123410](https://github.com/brave/brave-browser/assets/38657976/8d5ec01d-993b-40de-9a58-7d9771fbc814) | ![Screenshot_20230609_123440](https://github.com/brave/brave-browser/assets/38657976/9af29707-10be-4ffd-a91e-e77605130929)

## Expected result
custodian mismatch message should not be displayed in the tipping banner for the grandfathered unconnected user 

## Issue reproduces how often 

Easy
## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86): All
   - Device type (Phone, Tablet, Phablet):All
   - Android version: 12
   
## Brave version
1.53.83

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/qa-team @Miyayes @deeppandya @sujitacharya2005

**Comment by kjozwiak** [comment]
The above requires `1.53.102` or higher for `1.53.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Samsung Galaxy version 12` running `Bravemonoarm64.apk_1.53.102`

- Verified the STR from https://github.com/brave/brave-browser/issues/30935#issue-1749269083
- Confirmed that the custodian mismatch message is not displayed in the tipping banner for the grandfathered unconnected user in 1.55.2

Example | Example  
----------|-----------
![Screenshot_20230622-205356_Brave](https://github.com/brave/brave-browser/assets/38657976/5d6053ae-bf3e-4dcd-89fd-d36bf8a18888) | ![Screenshot_20230622-205423_Brave](https://github.com/brave/brave-browser/assets/38657976/c76d7c4a-f4b8-4e51-bba9-0e718ab5493a)
