### ISSUE TITLE
[Debug] DCHECK failure on extension install

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#3093]
## Description 
On installing the honey extension, and closing the tab opened by the extension. A crash is triggered by a dcheck failure: std::find(surface_ids.begin(), surface_ids.end(), GetCurrentSurfaceId()) != surface_ids.end()

## Steps to Reproduce
   1.  Download `Honey extension` from Chrome WebStore
   2. After installation, close the new tab that is opened by the extension for registration.
   3. Crash!

## Actual result:
Crash

## Expected result:
No Crash

## Reproduces how often: 
Easily

## Brave version (brave://version info)
0.61.0 Chromium: 72.0.3626.64 (Developer Build) (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? No

**Comment by iefremov** [comment]
seems not reproducible
