### ISSUE TITLE
Update VPN Toolbar button style

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#30930]
F/u issue for https://github.com/brave/brave-browser/issues/30410

<img width="1267" alt="image" src="https://github.com/brave/brave-browser/assets/6786187/438b7d82-6cf8-4cc9-84c9-cc253070d511">

Internal only design link - https://www.figma.com/file/qtMYwoj3JWJO5xzwLt6j2f/Desktop-VPN?type=design&node-id=1822-19229&t=vH3fd5mYS94U7WlK-0

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.54.85 Chromium: 115.0.5790.56 (Official Build) beta (x86_64)
-- | --
Revision | ebcfb87c1393f36955cfa2f6451a1767e3dc3ee5-refs/branch-heads/5790@{#1193}
OS | macOS Version 11.7.8 (Build 20G1351)

**Comment by stephendonner** [comment]
For the record (since this will also be verified on `Windows`), the Figma link (`https://www.figma.com/file/qtMYwoj3JWJO5xzwLt6j2f/Desktop-VPN?type=design&node-id=1822-19229&t=vH3fd5mYS94U7WlK-0`) shows toolbar-mockup treatments for both `Private Window` and `Private Window with Tor`

But the `VPN` button doesn't appear in those window types.

cc @aguscruiz

**Comment by aguscruiz** [comment]
Shouldn't it appear anyways? Curious as to why

**Comment by stephendonner** [comment]
> Shouldn't it appear anyways? Curious as to why

From @bsclifton in https://bravesoftware.slack.com/archives/CC5SA8CCB/p1677299268356949, "`SKU SDK calls won't work in a private context`"

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.57.33 Chromium: 115.0.5790.114 (Official Build) beta (64-bit)
-- | --
Revision | 86b4ea1d70ce73c4468d84cc8277f1f9de14b8bc
OS | Windows 11 Version 22H2 (Build 22621.1992)
```


### Shared Steps:
<details>

1. installed `1.57.33`
2. launched Brave
3. loaded `account.bravesoftware.com`
4. purchased, configured, and connected to `Brave VPN`


</details>

## Default State
<details>


. | VPN Off | VPN On | Error
---|---|---|---
`Green`| <img width="188" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/b5235647-7fe7-4d6e-afd1-ed74c65e5b54">|<img width="188" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/b2581727-f017-4965-8393-2f18549afbeb">|<img width="189" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/c7749be8-738f-46b1-ab09-075c3c6b3f77">
`Red`| <img width="184" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/3adb9da5-0c22-44d4-ad5d-f46299bb7372">|<img width="192" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/23747651-f3eb-40ab-9e5d-0ed185698584">|<img width="189" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/b78a2930-a985-48a9-95bc-4caa5d86db11">
`Light`| <img width="188" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/cb82df7a-d460-45a8-b686-1d3ec95abf16">|<img width="190" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/9119c821-2d68-4258-babe-d2c5610da336">|<img width="189" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/2b880cb0-ed79-4e8a-b5a2-cb6b1413681b">
`Dark` | <img width="185" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/80dbaed8-5e27-47be-b41e-4c13b5fdfb60">|<img width="193" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/683d83e2-6006-4b72-8300-1ca2054a3115">|<img width="189" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/d22d0718-a51c-48d2-8140-a6b49c9984e0">


. | VPN Off | VPN On | Error
---|---|---|---
`Green`|


`Red`|

`Light`|
