### ISSUE TITLE
[Shortcuts]: Translate the shortcuts UI page

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#30931]
## Description 

This is a follow up to https://github.com/brave/brave-browser/issues/30831 which translates the name of the various command. This ticket is for translating the UI strings on the chrome://settings/system/shortcuts page.

## Steps to Reproduce

   1. Open chrome://settings/system/shortcuts in a non English locale

## Actual result:
Strings are in English

## Expected result:
Strings are in the current language

## Reproduces how often: 

Easily

**Comment by kjozwiak** [comment]
The above requires `1.53.100` or higher for `1.53.x` verification 👍 The above will need to wait for translations to land in `1.53.x`. Labelling as `QA/Blocked` for now.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.53.107 Chromium: 115.0.5790.40 (Official Build) (x86_64)
-- | --
Revision | 071c9ddea889c3c7887daf4eac13fed72d4fff62-refs/branch-heads/5790@{#979}
OS | macOS Version 13.4.1 (Build 22F82)
```
