### ISSUE TITLE
Local host access permissions were cached after resetting

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#30948]
## Steps to Reproduce

1. Install 1.53.97
2. launched Brave
3. set `brave://flags/#brave-localhost-access-permission` to Enabled
4. clicked Relaunch
5. added the following to localhost-permission-allow-list.txt `shivankaul.com`
6. placed a logo.png file in the newly created test dir
7. ran python3 -m http.server 8000, also from tests
8. added @@||localhost^$domain=shivankaul.com to Create custom filters in `brave://settings/shields/filters`
9. loaded `https://shivankaul.com/brave/localhost/subresource.html`
10. clicked Allow and confirmed my logo.png loaded
11. reset permissions in `brave://settings/content/siteDetails?site=https%3A%2F%2Fshivankaul.com%3A443`
12. return to the tab `https://shivankaul.com/brave/localhost/subresource.html` and click Reload button

## Actual result:

- Nothing happens 
- Image is still shown as it's cached
- return to brave://settings/content/localhostAccess and the page is blank
- Permission prompt is shown when hard refresh of the page is done

https://github.com/brave/brave-browser/assets/98358127/d0b0c0f4-6263-4496-8d79-9ae01aef7f5e

## Expected result:
Permission prompt should be shown.  
## Reproduces how often: 

https://github.com/brave/brave-browser/assets/98358127/d4afb923-ad21-44b5-990a-6a11c33a9a07

## Version/Channel Information:

```
Brave | 1.53.87 Chromium: 114.0.5735.110 (Official Build) beta (64-bit)
-- | --
Revision | 1c828682b85bbc70230a48f5e345489ec447373e-refs/branch-heads/5735_90@{#13}
OS | Windows 11 Version 22H2 (Build 22621.1702)
```
- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
 @rebron @ShivanKaul 
cc: @stephendonner

**Comment by ShivanKaul** [comment]
On more thought, I don’t think this is actually an issue — the permission prompt wasn’t shown because a new network request wasn’t made, because the resource (logo.png) was loaded from cache. Thanks for catching this scenario though.
