### ISSUE TITLE
[Follow up to #28653] Strings are not translated for "Only open links in current tab group"

### ISSUE THREAD

**Issue by vlad-hoff** [brave/brave-browser#30949]
## Description 

Follow-up to #28653

## Steps to reproduce 

   1. Switch device language from English to any other one
   2. Launch Brave
   3. Three-dot Menu > Settings
   4. Scroll down and open `Appearance`
   5. Find `Only open links in current tab group` > Observe

## Actual result 

`Only open links in current tab group` and `Automatically opens all links in the current tab group` are not translated into other languages.

|Spanish|German|Russian|Japanise|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/4698fed1-a3b8-4303-95f2-3a113519ee9b) | ![2](https://github.com/brave/brave-browser/assets/128532965/8dab055b-d55a-4a83-a21a-4b56af26d290) | ![3](https://github.com/brave/brave-browser/assets/128532965/dffe6a8c-c86e-4563-90ab-ba6084d4fa1e) | ![4](https://github.com/brave/brave-browser/assets/128532965/8a4aa000-2994-4af0-93d5-990ee8bbf848) |

## Expected result

`Only open links in current tab group` and `Automatically opens all links in the current tab group` must be translated into other languages.

## Issue reproduces how often 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Pixel 7 (phone)
   - Android version: Android 14 [panther_beta-user 14 UPB3.230519.008 release-keys]
   
## Brave version

Brave build: 1.53.83
Chromium: 114.0.5735.110 (Official Build) beta (64-bit)
Revision: 1c828682b85bbc70230a48f5e345489ec447373e-refs/branch-heads/5735_90@{#13}

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.53.107` or higher for `1.53.x` verification 👍
