### ISSUE TITLE
Avoid uploading the GPG key on every run

### ISSUE THREAD

**Issue by oajara** [brave/brave-browser#30942]
We don't need the GPG public key to be uploaded on every pipeline run.

**Comment by LaurenWags** [comment]
@oajara could you please add the following required labels as necessary:
- `QA/Yes` or `QA/No` (if `QA/Yes`, please provide a manual test plan)
- `OS/Desktop` and/or `OS/Android`
- `release-notes/include` or `release-notes/exclude`

Thanks!
