### ISSUE TITLE
[Follow up to #28652] Strings are not translated for "Open external links in Brave"

### ISSUE THREAD

**Issue by vlad-hoff** [brave/brave-browser#30947]
## Description 

Follow-up to #28652

## Steps to reproduce 

   1. Switch device language from English to any other one
   2. Launch Brave
   3. Three-dot Menu > Settings
   4. Scroll down and find `Open external links in Brave` > Observe

## Actual result 

`Open external links in Brave` and `Opens link from other apps in a Brave webview. Note: Brave must be set as your default browser.` are not translated to other languages.

|Spanish|German|Russian|Japanise|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/69efa357-4fb7-4efd-94b0-4643030f1aa7) | ![2](https://github.com/brave/brave-browser/assets/128532965/ed21fd2d-2370-4c56-8f76-e2719f4d0ee1) | ![3](https://github.com/brave/brave-browser/assets/128532965/ecc658c1-c127-402a-86d8-b596731065d6) | ![4](https://github.com/brave/brave-browser/assets/128532965/0b18727a-7fd7-48aa-9b06-767996f66e0d) |

## Expected result

`Open external links in Brave` and `Opens link from other apps in a Brave webview. Note: Brave must be set as your default browser.` must be translated to other languages.

## Issue reproduces how often 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Pixel 7 (phone)
   - Android version: Android 14 [panther_beta-user 14 UPB3.230519.008 release-keys]
   
## Brave version

Brave build: 1.53.83
Chromium: 114.0.5735.110 (Official Build) beta (64-bit)
Revision: 1c828682b85bbc70230a48f5e345489ec447373e-refs/branch-heads/5735_90@{#13}

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.53.107` or higher for `1.53.x` verification 👍
