### ISSUE TITLE
`New private window with Tor` is not translated to some locales

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#3095]
## Steps to Reproduce

   1. Change locale
   2. Open Hamburger Menu

## Actual result:

Failed locales: Czech, German, Dutch, Danish, Finnish, Italian, Japanese, Korean, Norwegian, Russian
Passed locales: Polish, Spanish
Note: above locales were checked, could be that other locales also miss translations

![image](https://user-images.githubusercontent.com/34715963/51717994-6cb1cc80-2043-11e9-805b-5f7cf4604f36.png)

## Reproduces how often: 

always

## Brave version (brave://version info)

Brave | 0.59.28 Chromium: 72.0.3626.64 (Official Build) beta(64-bit)
-- | --
Revision | eaa9668e80ce5405e7f1902579558ea725c06ca1-refs/branch-heads/3626@{#708}
OS | Windows

cc @brave/legacy_qa @tomlowenthal

**Comment by kjozwiak** [comment]
CCing @bbondy as he usually deals with translations as well.

**Comment by btlechowski** [comment]
Not reproducible on

Brave | 0.66.88 Chromium: 75.0.3770.87 (Official Build) beta (64-bit)
-- | --
Revision | 9dc58a2353af60ab2b48bab98a25bc43ed59085d-refs/branch-heads/3770@{#982}
OS | Windows 7 Service Pack 1 (Build 7601.24465)

![image](https://user-images.githubusercontent.com/34715963/59383519-568d7a00-8d60-11e9-82ed-001383c8df0c.png)

Also not reproducible on: Czech, German, Dutch, Danish, Finnish, Italian, Japanese, Norwegian, Russian
