### ISSUE TITLE
Add localization to Brave vpn wireguard  service tray menu

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#30959]
It could be added same way as updater does https://source.chromium.org/chromium/chromium/src/+/main:docs/updater/design_doc.md by taking it from browser grd's via generate_embedded_i18n

**Comment by LaurenWags** [comment]
Relabeled as `QA/No` per discussion via https://bravesoftware.slack.com/archives/CC5SA8CCB/p1692642914862249, will be verified in 1.59.x with https://github.com/brave/brave-browser/issues/32003 per https://github.com/brave/brave-browser/issues/32003#issuecomment-1688708057.
