### ISSUE TITLE
DDG modal wrongly shows "Add to Chrome"

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#3096]
## Description 

DDG modal wrongly shows "Add to Chrome"

## Steps to Reproduce

   1. Open https://duckduckgo.com/ in a new tab
   2. Add DDG modal detects it as Chrome

## Actual result:

![screenshot from 2019-01-25 09-53-10](https://user-images.githubusercontent.com/17010094/51725212-0a7abb00-2087-11e9-9859-39a20f30f532.png)
![screenshot from 2019-01-25 09-50-01](https://user-images.githubusercontent.com/17010094/51725218-12d2f600-2087-11e9-99c4-bcec3c400ed6.png)

## Expected result:
Should say `Add DuckDuckGo to Brave`

## Reproduces how often: 

Easy

## Brave version (brave://version info)

All

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes on all channels
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @lukemulks @bbondy

**Comment by IOI-655321** [comment]
Same for startpage

https://www.startpage.com/en/search/download-startpage-plugin.html

**Comment by bbondy** [comment]
I think this is a change duckduckgo and startpage respectively would have to make.

**Comment by eljuno** [comment]
+1 from Community https://community.brave.com/t/search-engines-recognizing-brave-as-chrome/67473?u=eljuno

**Comment by bsclifton** [comment]
Happy to report this was fixed a few months ago by the folks at DuckDuckGo 😄 Should be working on Brave 1.3 or newer
