### ISSUE TITLE
Unable to connect using Wireguard in Nightly

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#30968]
## Description 

Unable to connect to BraveVpn using Wireguard in Nightly

## Steps to Reproduce

   1. Enable brave://flags/#brave-vpn-wireguard
   2. Try to connect to BraveVpn

## Actual result:

- connection failed

## Expected result:

- vpn connected

## Reproduces how often: 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
@spylogsster added `OS/Windows` as this looks like it's only available on Windows. Is that accurate?

**Comment by spylogsster** [comment]
> @spylogsster added `OS/Windows` as this looks like it's only available on Windows. Is that accurate?

yes, only windows

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using 
```
Brave | 1.54.91 Chromium: 115.0.5790.56 (Official Build) beta (64-bit)
-- | --
Revision | ebcfb87c1393f36955cfa2f6451a1767e3dc3ee5-refs/branch-heads/5790@{#1193}
OS | Windows 11 Version 22H2 (Build 22621.1848)
```

Reproduced the issue in 1.53.83 using the STR from description.  VPN connection spins when `#brave-vpn-wireguard` flag is enabled


https://github.com/brave/brave-browser/assets/98358127/72479cb6-d537-4ab2-a0de-104f883b27e1


1. Installed 1.54.91
2. launched Brave
3. purchase and login to VPN in the staging VPN environment
4. open brave://flags/ in a new tab
5. enable the flag `#brave-vpn-wireguard` 
6. return to VPN tab and connect to VPN
7. disable the flag `#brave-vpn-wireguard` 


**VPN Panel shows Can't connect to server` message in the VPN panel**

**However, Windows OS settings>Network & internet > VPN shows VPN is connected**

**When `#brave-vpn-wireguard` flag disabled in `brave://flags`,  no error is shown in the VPN panel and green checkmark shown on the VPN button**



https://github.com/brave/brave-browser/assets/98358127/b68c04cc-59ea-486e-8341-7dd8dddd3606

**Comment by LaurenWags** [comment]
Removed `QA Pass-Win64` so we check this on Win 10 also.

@stephendonner when you get a chance, could you 
1. Verify this issue on Win 10
2. Since Wireguard isn't on macOS, just spot check connecting to VPN works ok on macOS (just to be safe)

**Comment by stephendonner** [comment]
## Verifcation `IN-PROGRESS` using

```
Brave | 1.57.6 Chromium: 115.0.5790.75 (Official Build) beta (64-bit)
-- | --
Revision | 3433e4d513e8454ba0243deea3d53693661dc0c3-refs/branch-heads/5790@{#1430}
OS | Windows 10 Version 22H2 (Build 19045.3155)
```

**Comment by stephendonner** [comment]
## Verification `PASSED` using 

Brave | 1.57.6 Chromium: 115.0.5790.75 (Official Build) beta (x86_64)
-- | --
Revision | 3433e4d513e8454ba0243deea3d53693661dc0c3-refs/branch-heads/5790@{#1430}
OS | macOS Version 11.7.8 (Build 20G1351)

### Steps:
1. installed `1.57.6`
2. launched Brave
3. opened `brave://flags`
4. confirmed no `Wireguard` flag(s)
5. purchased, configured, and connected to `Brave VPN`

### Confirmed I was able to connect to `Brave VPN`

example | example | example | example
---------|----------|---------|---------
<img width="1204" alt="Screen Shot 2023-07-10 at 11 28 53 AM" src="https://github.com/brave/brave-browser/assets/387249/4560cfa4-72a7-4c03-bddc-52a53ee66195"> | <img width="1412" alt="Screen Shot 2023-07-10 at 11 30 34 AM" src="https://github.com/brave/brave-browser/assets/387249/5f79a150-2f08-4cda-baa3-25116f2c0df2"> | <img width="1412" alt="Screen Shot 2023-07-10 at 11 30 40 AM" src="https://github.com/brave/brave-browser/assets/387249/c439e996-f95e-473a-baa4-2636d3369e56"> | <img width="1412" alt="Screen Shot 2023-07-10 at 11 30 44 AM" src="https://github.com/brave/brave-browser/assets/387249/41acb250-4ff9-4ec4-85e5-d2d982171935">
