### ISSUE TITLE
Temporarily expanded vertical tab strip stays when switching to another app

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#30966]
## Description 
When you eanble "Expand vertical tabs panel on mouseover when collapsed" feature, sometimes it's stuck expanded while mouse is out of it.

https://bravesoftware.slack.com/archives/C042KL922P3/p1686346797654149

## Steps to Reproduce

* Maximize browser and another App.
* Move mouse onto vertical tab strip to expand it
* Activate another App with Alt tab
* Move mouse to the right side of the App, so that it would be out of underlying vertical tab strip
Activate browser again with Alt tab
* Vertical tab strip will stay expanded until mouse enters and exit again.

## Actual result:
Vertical tab will stay expanded

## Expected result:
Vertical tab should be collapsed when the window is deactivated

## Reproduces how often: 
Easily (Didn't tested other platforms than Windows)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.57.2 Chromium: 115.0.5790.56 (Official Build) beta (64-bit)
-- | --
Revision | ebcfb87c1393f36955cfa2f6451a1767e3dc3ee5-refs/branch-heads/5790@{#1193}
OS | Windows 11 Version 22H2 (Build 22621.1928)
```
Reproduced the issue in `1.52.130 Chromium: 114.0.5735.198` using STR in the description https://github.com/brave/brave-browser/issues/30966#issue-1752399617

https://github.com/brave/brave-browser/assets/98358127/27b55518-9991-405e-9ace-50297c8e6488


1. Install `1.57.2`
2. launch Brave
3. open few tabs 
4. enabled vertical tabs and in float/mouseover mode
5. clicked on tab to open a site (https://usatoday.com)
6. hover over the vertical tab strip to expand it
7. switch to another App (github.com) with Alt + tab
8. moved mouse to the right side of the page
9. activated browser again with Alt + tab


#### Confirmed vertical tab panel shows minimized mode and no longer stayed expanded.


https://github.com/brave/brave-browser/assets/98358127/b72b6ea3-7059-4409-a113-70ee033c8d14
