### ISSUE TITLE
No captcha shown to claim ad grants but panel continues to show `Congrats! You May rewards have arrived!`

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#30965]
## Description 

On my daily driver profile, I never received the captcha to solve to claim ad grants. I got the your ads grant will be available message but then no captcha was given to claim the grant and now it shows `Congrats! Your May rewards have arrived!`

## Actual result:

No captcha provided to claim ad grants

## Expected result:
Show Ad grant captcha when grants have arrivied

## Reproduces how often: 

Easy on my daily driver profile

## Brave version (brave://version info)

Brave | 1.54.48 Chromium: 114.0.5735.110 (Official Build) nightly (64-bit)
-- | --
Revision | `1c828682b85bbc70230a48f5e345489ec447373e-refs/branch-heads/5735_90@{#13}`
OS | Windows 11 Version 22H2 (Build 22621.1778)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @GeetaSarvadnya @LaurenWags @Miyayes @zenparsing @emerick

**Comment by Miyayes** [comment]
> I got the your ads grant will be available message

Hm, was this a toast notification in the Rewards panel or something else? Do you have a screenshot by any chance?

We do not issue vBAT / "ad grant" payouts anymore, so there are no more CAPTCHAs, and no more ad grants.

**Comment by srirambv** [comment]
> Hm, was this a toast notification in the Rewards panel or something else? Do you have a screenshot by any chance?

![Screenshot (9)](https://github.com/brave/brave-browser/assets/17010094/22e4dbe6-6462-4bc0-897b-d01141a93629)

**Comment by Miyayes** [comment]
That looks right to me. In other words, you are seeing this because your deposit into your Uphold account should be complete.
