### ISSUE TITLE
Update Rewards title colors to match design system

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#30971]
## Description

```[tasklist]
### Tasks
- [ ] brave://rewards title sections
- [ ] Rewards panel and summary BAT number colors
```
Figma:

**Comment by emerick** [comment]
@Miyayes From what I recall we wanted to make all of the title sections and BAT numbers black, correct? Do we have an updated Figma that shows that design (not that it's hard! I just want to make sure I don't miss anything :-)

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.58.79 Chromium: 116.0.5845.51 (Official Build) nightly (x86_64)
-- | --
Revision | 329052e01b863ee3939d05c5338ccece2b04e210
OS | macOS Version 13.5 (Build 22G74)
```
