### ISSUE TITLE
Auto discover POAPs

### ISSUE THREAD

**Issue by nvonpentz** [brave/brave-browser#30977]
Based on SimpleHash's docs, we should be able to do this using the same endpoint that we discover NFTs from by supplying a specific contract address:
>If you need to query POAPs for a specific wallet, use the [NFTs by Wallet(s)](https://docs.simplehash.com/reference/nfts-by-owners) endpoint instead and filter for 0x22C1f6050E56d2876009903609a2cC3fEf83B415 in the contract_addresses field.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.57.35 Chromium: 115.0.5790.171 (Official Build) beta (arm64)
-- | --
Revision | 776897328898241b35b83878040730e73e749c06
OS | macOS Version 13.4.1 (c) (Build 22F770820d)

- Verified steps from [brave/brave-core#18886](https://github.com/brave/brave-core/pull/18886)
- Verified POAPs are auto discovered when the supported network is preloaded
- Verified POAPs are auto discovered on an existing wallet when the supported network is added and manually refreshed 

https://github.com/brave/brave-browser/assets/17010094/ab31a9c1-8d97-470c-8d36-00a6a966abab
