### ISSUE TITLE
Talk shortcut icon missing on NTP

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#30978]
## Description 

The Brave Talk shortcut icon is missing in the NTP footer area.

The icon was inadvertently removed by https://github.com/brave/brave-core/pull/18775.

## Steps to Reproduce

   1. Open NTP

## Actual result:

<img width="308" alt="Screenshot 2023-06-12 at 11 17 25 AM" src="https://github.com/brave/brave-browser/assets/5995084/b9ebecb9-3d73-48b2-a6b2-6be6229419a9">

## Expected result:

<img width="331" alt="Screenshot 2023-06-12 at 8 01 45 AM" src="https://github.com/brave/brave-browser/assets/5995084/c8a0fa2a-c87c-464d-9423-881d44185f6a">

## Brave version (brave://version info)

1.54.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using 

```
Brave | 1.54.84 Chromium: 115.0.5790.40 (Official Build) beta (x86_64)
-- | --
Revision | 071c9ddea889c3c7887daf4eac13fed72d4fff62-refs/branch-heads/5790@{#979}
OS | macOS Version 14.0 (Build 23A5276g)
```
