### ISSUE TITLE
Allow sponsored image after initial and every nth tab to be configured via Griffin

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#30974]

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.57.27 Chromium: 115.0.5790.114 (Official Build) beta (64-bit) 
-- | --
Revision | 18977fb43f693d5a8deeb48bd1cfa52651d3f73e
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/18865

<details>

Verified NTPSI is shown on first NTP tab when `BraveNTPBrandedWallpaper:initial_count_to_branded_wallpaper/0`
![image](https://github.com/brave/brave-browser/assets/34715963/141c51e6-ff93-4518-bdee-4e516544ba95)

Verified NTPSI every 3rd tab when `BraveNTPBrandedWallpaper:count_to_branded_wallpaper/2`
![image](https://github.com/brave/brave-browser/assets/34715963/73b086dc-2260-49aa-b8a2-8ecaecdd82ef)


</details>
