### ISSUE TITLE
Add a More Menu for each Portfolio Asset

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#30982]
## Description 

We need to add a `More Menu` for each asset on the `Portfolio Overview` screen

![Screenshot 28](https://github.com/brave/brave-browser/assets/40611140/26c2c49d-1926-4b23-b874-83947a4e534c)

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.58.109 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Linux

- Verified steps from [brave/brave-core#19528](https://github.com/brave/brave-core/pull/19528)
- Verified `Buy` button is shown for all assets that are buyable
- Verified `Send` button is shown for all assets that has a balance
- Verified `Swap` button is shown for all assets that has a balance
- Verified `Deposit` button is always shown for all assets 
- Verified `Sell` button is only shown when the asset has a balance and `Portfolio` is grouped by `Accounts`
- Logged [#32724](https://github.com/brave/brave-browser/issues/32724) & [#32725](https://github.com/brave/brave-browser/issues/32725)

https://github.com/brave/brave-browser/assets/17010094/efe74272-7874-4c2e-a0ff-751ddfa6a2bf


---------------------

**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build)) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#19528](https://github.com/brave/brave-core/pull/19528)
- Verified `Buy` button is shown for all assets that are buyable
- Verified `Send` button is shown for all assets that has a balance
- Verified `Swap` button is shown for all assets that has a balance
- Verified `Deposit` button is always shown for all assets 
- Verified `Sell` button is only shown when the asset has a balance and `Portfolio` is grouped by `Accounts`
- Logged [#32724](https://github.com/brave/brave-browser/issues/32724) & [#32725](https://github.com/brave/brave-browser/issues/32725)

https://github.com/brave/brave-browser/assets/17010094/a4d122f5-064e-4f82-9f98-52a6676252b9


---------------------

**Verification passed on**

Brave | 1.57.27 Chromium: 115.0.5790.114 (Official Build) beta (arm64)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | macOS Version 13.4.1 (c) (Build 22F770820d)

- Verified steps from [brave/brave-core#19528](https://github.com/brave/brave-core/pull/19528)
- Verified `Buy` button is shown for all assets that are buyable
- Verified `Send` button is shown for all assets that has a balance
- Verified `Swap` button is shown for all assets that has a balance
- Verified `Deposit` button is always shown for all assets 
- Verified `Sell` button is only shown when the asset has a balance and `Portfolio` is grouped by `Accounts`
- Logged [#32724](https://github.com/brave/brave-browser/issues/32724) & [#32725](https://github.com/brave/brave-browser/issues/32725)

https://github.com/brave/brave-browser/assets/17010094/060aef71-6795-4fe6-aefa-8113d17e9929
