### ISSUE TITLE
Crash with brave_ads::GetCountryCode

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#30984]
The crash in nightly:

https://brave.sp.backtrace.io/p/brave/explore?time=all&aggregations=((ver%2Crange)%2C(callstack%2Chead))&fingerprint=c6a297775b0d35d9b7940822ceddb7c644e565305ef6eb5e0420f4163ce3bf94&

756 crashes in 7 days. No steps to reproduce.

**Comment by tmancey** [comment]
Closing as no new crash reports
