### ISSUE TITLE
Separate Accounts and Transactions in Assets details Screen

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#30981]
## Description 

We need to add a `Segmented` controller to the `Asset Details` screen to separate `Accounts` and `Transactions`.

![Screenshot 27](https://github.com/brave/brave-browser/assets/40611140/e3bf5a34-dd7b-4630-b0e4-d9f0d4159763)

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#19092](https://github.com/brave/brave-core/pull/19092)
- Verified `Accounts` and `Transactions` routes work as expected for a token

https://github.com/brave/brave-browser/assets/17010094/782eea42-e9b7-4028-95ae-b41c78bfb254
