### ISSUE TITLE
User-provided Max priority gas fees not applying to pending transaction

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#30992]
## Description 

An uncaught error is being thrown within the api slice when updating EVM transaction gas preferences for a pending transaction. 
The causes the user's gas fee option selections to not get applied to any pending EVM transaction

## Steps to Reproduce

   1. Attempt an EVM transaction
   2. click the edit button in the gas fee section
   3. select a different gas option
   4. save the selection

## Actual result:

When returning to the pending transaction screen, the gas fee is not updated.

## Expected result:
When returning to the pending transaction screen, the gas fee is updated.

## Reproduces how often: 

Easy

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.57.23 Chromium: 115.0.5790.102 (Official Build) beta (64-bit)
-- | --
Revision | `d515871a6c6df7d2843e755c8b7dda9b744f26d6`
OS | Windows 11 Version 22H2 (Build 22621.1992)

- Verified steps from issue description
- Verified user provided max prioirty gas fee is applied for transactions

https://github.com/brave/brave-browser/assets/17010094/f94d0bad-52d3-4579-8977-b1fe8d2c932c
