### ISSUE TITLE
Localhost adblock rules should only apply if localhost permission is switched off

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#30996]
We currently bundle localhost adblock rules in the default adblock engine: https://github.com/brave/adblock-lists/blob/master/brave-lists/brave-specific.txt#L2

With the new localhost permission, these localhost adblock rules need to be removed in order to allow the permission to apply to localhost requests (otherwise they would just all get blocked by the adblock engine). Unfortunately, we can't control adblock rules per-channel via Griffin, which makes the adblock rule removal an all-or-nothing procedure. This doesn't work well with our planned rollout strategy for the localhost permission feature, which is to slowly increase rollout via Griffin.

We can badfilter the localhost adblock rules iff the localhost feature flag is on -- this would ensure that the localhost adblock rules would still apply if the feature was off, but not apply if the feature was on. However, in order to do this, adblock filter provider manager will have to be refactored.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.58.90 Chromium: 116.0.5845.96 (Official Build) beta (x86_64)
-- | --
Revision | c112ad8c854bd34b48f4e87bfb3f7951e426a1d4
OS | macOS Version 11.7.9 (Build 20G1426)

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.58.91 Chromium: 116.0.5845.96 (Official Build) beta (64-bit)
-- | --
Revision | 620fa9c0307b294dd6e7c6b0976bc1f93fecf369
OS | Windows 10 Version 22H2 (Build 19045.3324)
```


brave://flags | localhost-permission-allow-list.txt | http server | example | example
--------------|---------------------------------------|-------------|-----------|----------
![image](https://github.com/brave/brave-browser/assets/387249/bd7112ab-5666-4e89-9a47-90d380adf413)


example | example | example | example | example
----------|----------|------------|----------|----------

**Comment by kjozwiak** [comment]
Added `QA Pass - Android ARM` after discussing with @ShivanKaul re: not being able to verify the above due to not having a rooted device for `Android`. Even though the above wasn't verified via `Android`, adding label to remove the issue from our list if needed verifications for `1.58.x`.
