### ISSUE TITLE
[CR115] Disable password manager redesign

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#30993]
The password manager is being redesigned upstream. This feature is currently disabled upstream, but we should also ensure it remains disabled with a feature override. May also want to investigate `kPasswordGenerationExperiment` and do the same thing.

**Comment by emerick** [comment]
@rebron Just wondering if this issue is still relevant or I should close it out? It came up during the review of CR115, but I think it may be out of date now.

**Comment by bsclifton** [comment]
I'll close this out - @rebron let's create another issue if there's new information or new Chromium upgrades enable this functionality
