### ISSUE TITLE
Asset Details Back button breaks when coming from Panel

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#30995]
## Description 

If you expand to the `Asset Details` view from the panel, the back button breaks the UI

## Steps to Reproduce

   1. Open the `Panel` and click on `View account assets`, select an asset.
   2. Once the `Asset Details` page loads, click on the `Back` button in the header
   3. The wallet UI breaks

## Actual result:

https://github.com/brave/brave-browser/assets/40611140/3f2e8e06-3381-405a-9837-fb7ecd6fc78b

## Expected result:
Should route back to an appropriate route.

https://github.com/brave/brave-browser/assets/40611140/f55f208e-6f48-431b-b750-0febf0cc56f2

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.57.24 Chromium: 115.0.5790.136 (Official Build) beta (64-bit)
-- | --
Revision | `8099932ede6f8d4624fbddf39d27abb3b340d8c9`
OS | Linux

- Verified steps from [brave/brave-core#18875](https://github.com/brave/brave-core/pull/18875)
- Verified selecting asset from panel and clicking on back button loads the portfolio asset page
- Verified selecting NFT from panel and clicking on back button loads the portfolio NFT page

https://github.com/brave/brave-browser/assets/17010094/54902210-0a7a-4667-aa2e-3890ef29694c

---------------------

**Verification passed on**

Brave | 1.57.24 Chromium: 115.0.5790.136 (Official Build) beta (64-bit)
-- | --
Revision | `8099932ede6f8d4624fbddf39d27abb3b340d8c9`
OS | Windows 11 Version 22H2 (Build 22621.1992)

- Verified steps from [brave/brave-core#18875](https://github.com/brave/brave-core/pull/18875)
- Verified selecting asset from panel and clicking on back button loads the portfolio asset page
- Verified selecting NFT from panel and clicking on back button loads the portfolio NFT page

https://github.com/brave/brave-browser/assets/17010094/04fd6529-c407-4dbd-a651-0b18489d7701


---------------------

**Verification passed on**

Brave | 1.57.24 Chromium: 115.0.5790.136 (Official Build) beta (arm64)
-- | --
Revision | `8099932ede6f8d4624fbddf39d27abb3b340d8c9`
OS | macOS Version 13.4.1 (c) (Build 22F770820d)

- Verified steps from [brave/brave-core#18875](https://github.com/brave/brave-core/pull/18875)
- Verified selecting asset from panel and clicking on back button loads the portfolio asset page
- Verified selecting NFT from panel and clicking on back button loads the portfolio NFT page

https://github.com/brave/brave-browser/assets/17010094/60d1fbe9-5884-463e-953a-2749ad80d565
