### ISSUE TITLE
Widevine support

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#31]
- [x] Windows
- [x] macOS

**Comment by JEM-Mosig** [comment]
Is nobody doing this for Linux?

**Comment by bbondy** [comment]
We'll be doing it for linux too but the issue is moved to:
https://github.com/brave/brave-browser/issues/413

**Comment by btlechowski** [comment]
Verification passes on

Brave | 0.55.10 Chromium: 70.0.3538.22 (Official Build) beta (64-bit)
-- | --
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | Windows 7

Installed plugin through URL bar. 
Checked in Widevine Content Decryption Module version in chrome://components/
Played Netflix movies.
