### ISSUE TITLE
Infinite loading on buy screen

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#31000]
## Description 
Infinite loading on buy screen (nightly).

## Actual result 
[buy-loading.webm](https://github.com/brave/brave-browser/assets/11755381/1cd116d8-44f9-4e52-ab02-8809d79b842b)

## Expected result
Should show/load buy assets.

## Issue reproduces how often 
easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? Y
- Can you reproduce this issue with the current Play Store Nightly version? Y
   
## Brave version
1.54.53 Chromium: 114.0.5735.110 (Official Build) nightly (64-bit) 

cc: @muliswilliam @Douglashdaniel

**Comment by muliswilliam** [comment]
@Pavneet-Sing I am looking into this

**Comment by muliswilliam** [comment]
@Pavneet-Sing I tested on my local build, running with `npm run start -- --use-dev-goupdater-url` works.

**Comment by Pavneet-Sing** [comment]
@muliswilliam Just updated the version and I am only able to reproduce it on beta.
[Screencast from 04-07-23 05:21:46 PM IST.webm](https://github.com/brave/brave-browser/assets/11755381/698b1a60-a95b-48e3-ba64-a0fbdc595a6d)

**Comment by nvonpentz** [comment]
After a recent [change](https://github.com/brave/brave-core/pull/18798), this feature depends on having a recent version of the Brave Wallet files component downloaded to your browser. If I understand this bug right, if your component is up-to-date, it should work, regardless of version.  @Pavneet-Sing If you are still having issues, could you go to brave://components, manually update the wallet data files component and let me know if that fixes the issue?

**Comment by Pavneet-Sing** [comment]
It's up to date but still happening on beta, not sure if it is only me (if yes then feel free to close this issue).
[Screencast from 06-07-23 12:38:42 PM IST.webm](https://github.com/brave/brave-browser/assets/11755381/73db762d-8c0e-404b-bdc9-e31d88b48d53)

Console log (might help):
![Screenshot from 2023-07-06 12-39-54](https://github.com/brave/brave-browser/assets/11755381/92f8fd5a-830f-41b9-94b7-f5bdb2b6a31e)

**Comment by josheleonard** [comment]
Closing as not reproducible
