### ISSUE TITLE
HLS support for playlist

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#31001]
This issue is to add HLS support for playlist. 
it's a follow up issue to : https://github.com/brave/brave-browser/issues/30102

**Comment by kjozwiak** [comment]
After speaking with @deeppandya @Uni-verse @hffvld, we'll leave the above in `1.63.x` but label the issue as `QA/No` as `Playlist` has been moved from `1.63.x` -> `1.64.x`. @deeppandya mentioned that we'll have a `master` issue via `1.64.x` that will list all the `QA/Yes` issues that have been in the various milestones before `1.64.x`. This way QA will have a list of past `QA/Yes` issues that need to be checked/verified.
