### ISSUE TITLE
Brave News shouldn't look for feeds on the page when Brave News is disabled

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#31019]
## Description 

Brave News' Tab Helper will possibly still check if the page has rss feeds, even if it won't display the UI prompting the user to subscribe to them.

**Comment by LaurenWags** [comment]
@fallaciousreasoning could we get a test plan for this one? Thanks!

**Comment by fallaciousreasoning** [comment]
Hey @LaurenWags - I'm a little unsure the best way to test this, as you need to verify a request isn't made. I was doing it by adding `LOG` statements to the code to make sure the request weren't being triggered when the feature was disabled.

Another way to do it would be to use something like [Fiddler](https://www.telerik.com/fiddler) and verify that the RSS feeds for the page aren't fetched:
1. Setup fiddler
2. Navigate to https://hacks.mozilla.org/ with Brave News disabled
3. No request to the feed url (https://hacks.mozilla.org/feed/) is made

**Comment by LaurenWags** [comment]
thanks @fallaciousreasoning! we can give that a try and report back if we have problems 👍🏻

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.60.89 Chromium: 118.0.5993.70 (Official Build) beta (x86_64)
-- | --
Revision | 801f851e0c0664d110cccd46708cd084a83c3729
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. launched `Fiddler Everywhere`
2. installed `1.60.89`
3. launched Brave
4. loaded `https://hacks.mozilla.org`
5. filtered by `hacks.mozilla.org`

### Confirmed no requests for `https://hacks.mozilla.org/feed/`



`hacks.mozilla.org` | `Fiddler Everywhere`
--------------------|---------------------
<img width="1312" alt="Screen Shot 2023-10-13 at 10 15 12 AM" src="https://github.com/brave/brave-browser/assets/387249/5aa2ac58-fab5-4514-a35f-e39f27387233"> | <img width="1392" alt="Screen Shot 2023-10-13 at 10 15 09 AM" src="https://github.com/brave/brave-browser/assets/387249/53c90e90-8804-4b2b-9125-cc237ad1e135">

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 [panther_beta-user 14 U1B2.230922.010 release-keys]
Brave build: 1.60.106
Chromium: 119.0.6045.59 (Official Build) (64-bit) 
Revision: 16064193dde8c55f64dabd32f125c0cd9380f96a
```
---------------------------

**STEPS:**
1. Launch Fiddler or Charles Proxy
2. Launch Brave
3. Keep `Brave News` disabled
4. Navigate to https://hacks.mozilla.org > Verify

**ACTUAL RESULTS:**
- Verified that no request to the feed URL (https://hacks.mozilla.org/feed/) is made when `Brave News` is disabled.
- Verified the same with `Mobile site` and `Desktop site`.

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/934f2473-e000-4e75-80dc-fce86ad08a56) | ![2](https://github.com/brave/brave-browser/assets/128532965/9ad8c39c-4b39-4d2e-a811-b65b543b8b87) | ![3](https://github.com/brave/brave-browser/assets/128532965/a25b89b4-5a08-4838-aacb-5d153b57cc69) | ![4](https://github.com/brave/brave-browser/assets/128532965/1608076b-4853-4a53-9a6d-a93c3529e545) |
