### ISSUE TITLE
No New Tab when drag and drop elements like images into the vertiical tab area

### ISSUE THREAD

**Issue by encryptionstudio** [brave/brave-browser#31016]
## Description 

I tested the new vertical tab system in brave 1.52.112, and was very convinced of it. The only issue i detected was that open a tab with drag and drop doesn't worked. In the horizontal layout it was part of my daily browsing routine that i drag and dropped an image to the tab area and it opened as a new tab.

## Steps to Reproduce

   1. Use the vertical tab layout
   2. Drag an image from the current tab
   3. drop it inside the tab area

## Actual result:

Nothing happens.

## Expected result:
A new tab with the image should open, like in the horizontal layout.

## Reproduces how often: 

Easily reproduced/happens everytime

## Brave version (brave://version info)

Brave: 1.52.122 Chromium: 114.0.5735.110 (Offizieller Build) (64-Bit) 
Revision: 1c828682b85bbc70230a48f5e345489ec447373e-refs/branch-heads/5735_90@{#13}
OS: Windows 10 Version 22H2 (Build 19045.2965)

## Version/Channel Information:

- Can you reproduce this issue with the current release? -Yes
- Can you reproduce this issue with the beta channel? -N/A
- Can you reproduce this issue with the nightly channel? -N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Nope
- Does the issue resolve itself when disabling Brave Rewards? Nope
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

It does also not work when drag and dropping a marked text.

**Comment by MadhaviSeelam** [comment]
@rebron reproduced the issue in 
```
Brave | 1.52.126 Chromium: 114.0.5735.133 (Official Build) (64-bit)
-- | --
Revision | fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}
OS | Windows 11 Version 22H2 (Build 22621.1848)
```

https://github.com/brave/brave-browser/assets/98358127/8a88e2ae-f600-4087-82e5-f3238720b6e6

**Comment by Emi-TheDhamphirInLoveUnderTheFrozenStar** [comment]
resolved by https://github.com/brave/brave-core/pull/19785
