### ISSUE TITLE
Add read\write IPFS Settings extension API

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#31012]
Should be accessible from blessed extensions via chrome.ipfs.get\set methods.
Things to provide:
1) Resolve method type : local/gateway/ask/disabled
2) Whether dnslink autoredirects are enabled
3) Whether gateway-like urls autoredirects are enabled
4) Max ipfs storage size
5) Whether autofallback to gateway is enabled

Will be used by IPFS companion extension to customize own behaviour

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.58.109 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | a4ad1fcdb550daf076384dbb280ae944274b3d35
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#18901](https://github.com/brave/brave-core/pull/18901)
- Verified permission text for Extension installation has additional IPFS warnings
- Verified able set or changes settings via console using `chrome.ipfs` methods

https://github.com/brave/brave-browser/assets/17010094/b6716dc7-1747-41e0-b69c-7f9c8c9ab298
