### ISSUE TITLE
Refactor wallet SelectedAccount entity

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#31013]
Instead of 
`GetSelectedCoin()->coin` `SetSelectedCoin(coin)`
`GetSelectedAccount(coin)->account` `SetSelectedAccount(coin, account)`
we need 
`GetSelectedAccount()->account` `SetSelectedAccount(account)`
`GetSelectedEthDappAccount()->account`
`GetSelectedSolDappAccount()->account` 
wallet APIs

Per coin selected account is needed only for dApps and doesn't make sense for bitcoin and filecoin

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.58.108 Chromium: 116.0.5845.114 (Official Build) beta (64-bit)
-- | --
Revision | f08ffbe3ce0069ad8207b9d2d7dee38afcccc1b9
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified wallet works as expected
