### ISSUE TITLE
Conversion Envelop is not attached when there are other confirmations in the queue

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#31011]
Follow up to https://github.com/brave/brave-browser/issues/31003

Note: conversion envelop is attached when confirmation queue is empty

## Steps to Reproduce

1. Clean profile
2. Overwrite catalog so that only ad with conversion is there
3. Enable rewards and ads
4. Trigger the ad
5. Dismiss the ad and immediately after
6. Trigger the conversion
7. Close Brave
8. Move clock forward 24h
9. Run Brave
10. Wait for the confirmation for the conversion

## Actual result:

conversion envelop is not attached

![image](https://github.com/brave/brave-browser/assets/34715963/a02b452e-2f26-4034-acb0-ad831ca550bd)

## Expected result:
conversion envelop is attached

## Reproduces how often: 

Easily reproduced

## Desktop Brave version:

Brave | 1.52.125 Chromium: 114.0.5735.110 (Official Build) (64-bit) 
-- | --
Revision | 1c828682b85bbc70230a48f5e345489ec447373e-refs/branch-heads/5735_90@{#13}
OS | Ubuntu 18.04 LTS

cc @tmancey @aseren @iambrianfung

**Comment by tmancey** [comment]
Closing as resolved by https://github.com/brave/brave-browser/issues/23308
