### ISSUE TITLE
[BUG] Playlist causes High CPU usage when Private Windows are opened.

### ISSUE THREAD

**Issue by Emi-TheDhamphirInLoveUnderTheFrozenStar** [brave/brave-browser#31020]
## Description 

As I mentioned in https://github.com/brave/brave-browser/issues/30037#issuecomment-1527886281, when Playlist Flag is enabled, it causes high CPU usage of the Browser when Private Windows are opened. The problem is still present today, and still making my CPU go to 100%.

Task manager shows high CPU in any Extension process allowed to to run in Private mode, Brave process and any opened tab process even if it is the NTP.
But I disabled all extensions even Brave one with `--disable-brave-Extension` and still same issue, so it has nothing to do with extensions, they just get affected with it apparently.

I use Win11, and I could reproduce this in another computer with Win11, I don't know about other Windows versions or OSs. I was using the original Win11 version and I upgraded to 22H2 and same issue.

It is a critical bug, I am making this a Desktop only issue, because I don't know if it also happens in Android, but for example, it would be good to properly test CPU usage on Android as well, before merging https://github.com/brave/brave-core/pull/18880, just to avoid issues.

That PR for Android was just the reminder to test this bug after so long on Desktop, and then make a proper issue about it, since it started in 1.53.5 and seems like it was forgotten since I mentioned in a comment on that other issue I made.

On desktop it is pretty easy to test and reproduce, so I hope it gets fixed soon, to test Playlist more on Desktop without having to disable the flag all the time because I open Private windows often.

## Steps to Reproduce

   1.  Enable `brave://flags/#playlist` and restart.
   2. Check CPU usage 
   3.  Open and close Private windows 
   4. the CPU always goes high as soon as the window is opened and goes down immediately when closing. 

## Actual result:

![brave_2023-04-28_11-24-32](https://user-images.githubusercontent.com/122518587/235213865-fedc9fb4-1268-447f-8ebf-aca7c4aab353.gif)

## Expected result:
No high CPU usage especially if Playlist is planned to be default.

## Reproduces how often: 

Always

## Brave version (brave://version info)

Since 1.53.5 and now we are in 1.54.56 Chromium: 114.0.5735.110 (Official Build) nightly (64-bit)

**Comment by rebron** [comment]
cc: @sangwoo108

**Comment by rebron** [comment]
cc: @atuchin-m

**Comment by sangwoo108** [comment]
Playlist might not be the culprit. It's supposed to be unsupported on the OTR profile.

**Comment by atuchin-m** [comment]
@sangwoo108 In fact I can reproduce the issue on Nightly 1.59.47 (mac, arm64)
1. Run browser with a clean profile
2. Enable playlist via brave://flags
3. Restart
4. Open an incognito tab
<img width="1006" alt="Screenshot 2023-08-29 at 22 24 21" src="https://github.com/brave/brave-browser/assets/45488748/bc38f069-1b55-4fbc-a0a3-2f42f4c6032b">

**Comment by atuchin-m** [comment]
chrome://tracing shows a lot of IPC microtasks related to playlist feature. Each task is fast enough, but in total they consume scary CPU time.
<img width="922" alt="Screenshot 2023-08-29 at 22 29 32" src="https://github.com/brave/brave-browser/assets/45488748/2c18ef6c-100a-4a2b-a5dc-eeb8c31dd982">

cc @iefremov

**Comment by sangwoo108** [comment]
Thanks @mihaiplesa That's really helpful! Let me look into it.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.59.100 Chromium: 117.0.5938.92 (Official Build) beta (arm64)
-- | --
Revision | 3243fffc43431ab8677e8139859670b4cd2df843
OS | macOS Version 14.0 (Build 23A344)
```
