### ISSUE TITLE
Whitelisting access to chrome.sockets API for local dev with unpacked extension

### ISSUE THREAD

**Issue by lidel** [brave/brave-browser#3102]
### Problem Summary

I am trying to whitelist access to `chrome.sockets.*` for local development with unpacked extension to test how feasible those APIs are for use in [IPFS integration](https://github.com/brave/brave-browser/issues/819).

#### Why?

> Related notes on bringing IPFS to Brave: https://github.com/brave/brave-browser/issues/819#issuecomment-456039555
> Upstream issue to add support for `chrome.sockets.*` APIs to IPFS Companion: https://github.com/ipfs-shipyard/ipfs-companion/issues/664, cc #829

### Steps to Reproduce

I suspect I am just missing some obvious step, so below is what I did:

1. I loaded an unpacked extension with [`sockets` section added to  manifest](https://developer.chrome.com/apps/manifest/sockets#manifest) ([this branch](https://github.com/ipfs-shipyard/ipfs-companion/tree/feat/brave-build-with-chrome-sockets)), it got assigned ID `paanflafljinkomjoheoobkeigpakegp`. 

2. Generated ID shortcut via:

   ```console
   $ echo -n paanflafljinkomjoheoobkeigpakegp | openssl sha1 | tr '[:lower:]' '[:upper:]'
   (STDIN)= CEBF34BE446B77F39E2C535566F8C27F9A460B1E
   ```
 
3. and added it to whitelists for `sockets.*`  APIs in [`src/brave/common/extensions/api/_api_features.json`](https://github.com/brave/brave-core/blob/bc836d540a9aef6c5371fad89f5da2f77f7a212e/common/extensions/api/_api_features.json#L61-L75))
```diff
--- a/common/extensions/api/_api_features.json
+++ b/common/extensions/api/_api_features.json
@@ -60,18 +60,18 @@
   }],
   "sockets.tcp": {
     "dependencies": ["manifest:sockets"],
-    "contexts": ["blessed_extension"],
-    "whitelist": ["3D9518A72EB02667A773B69DBA9E72E0F4A37423"]
+    "contexts": ["blessed_extension","unblessed_extension"],
+    "whitelist": ["3D9518A72EB02667A773B69DBA9E72E0F4A37423","CEBF34BE446B77F39E2C535566F8C27F9A460B1E"]
   },
   "sockets.tcpServer": {
     "dependencies": ["manifest:sockets"],
-    "contexts": ["blessed_extension"],
-    "whitelist": ["3D9518A72EB02667A773B69DBA9E72E0F4A37423"]
+    "contexts": ["blessed_extension","unblessed_extension"],
+    "whitelist": ["3D9518A72EB02667A773B69DBA9E72E0F4A37423","CEBF34BE446B77F39E2C535566F8C27F9A460B1E"]
   },
   "sockets.udp": {
     "dependencies": ["manifest:sockets"],
-    "contexts": ["blessed_extension"],
-    "whitelist": ["3D9518A72EB02667A773B69DBA9E72E0F4A37423"]
+    "contexts": ["blessed_extension","unblessed_extension"],
+    "whitelist": ["3D9518A72EB02667A773B69DBA9E72E0F4A37423","CEBF34BE446B77F39E2C535566F8C27F9A460B1E"]
   },
   "braveRewards": {
     "channel": "stable",
```

4. Rebuilt Brave via `npm run build` 
5. Started it via `npm start`
6. Loaded extension again, it got the same ID (`paanflafljinkomjoheoobkeigpakegp`) but whitelisting did not work and I got this error:

   > ![sockets-error-2019-01-25--11-01-52](https://user-images.githubusercontent.com/157609/51740094-5f243300-2093-11e9-98db-01587c672f99.png)

I also tried to remove `"whitelist"` and added `"unblessed_extension"` to `"context"`, but the result was the same.

Would appreciate some guidance on what am I missing, or where should I look.

**Comment by yrliou** [comment]
I think you’ll also need to add your extension into the whitelist in https://github.com/brave/brave-core/blob/master/common/extensions/api/_manifest_features.json

**Comment by lidel** [comment]
@yrliou that did the trick, thank you!

> ![2019-01-25--16-37-31](https://user-images.githubusercontent.com/157609/51755692-9a3c5b80-20bf-11e9-9260-8d989c12659f.png)
