### ISSUE TITLE
Sort Portfolio Groups by Fiat Value

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#31024]
## Description 

We need to sort the `Portfolio` `Groups` (Networks or Accounts) by fait value.

https://github.com/brave/brave-browser/assets/40611140/7cdccaf6-d333-4100-a34a-59e8e3d5e4be

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.57.24 Chromium: 115.0.5790.136 (Official Build) beta (64-bit)
-- | --
Revision | `8099932ede6f8d4624fbddf39d27abb3b340d8c9`
OS | Linux

- Verified steps from [brave/brave-core#18891](https://github.com/brave/brave-core/pull/18891)
- Verified Account/Network group by is sorted high to low

https://github.com/brave/brave-browser/assets/17010094/136e9fff-0571-4983-a8d8-c39563b1593c


---------------------

**Verification passed on**

Brave | 1.57.24 Chromium: 115.0.5790.136 (Official Build) beta (64-bit)
-- | --
Revision | `8099932ede6f8d4624fbddf39d27abb3b340d8c9`
OS | Windows 11 Version 22H2 (Build 22621.1992)

- Verified steps from [brave/brave-core#18891](https://github.com/brave/brave-core/pull/18891)
- Verified Account/Network group by is sorted high to low

https://github.com/brave/brave-browser/assets/17010094/3ff6054e-354a-4972-afb9-3c051945972d


---------------------

**Verification passed on**

Brave | 1.57.24 Chromium: 115.0.5790.136 (Official Build) beta (arm64)
-- | --
Revision | `8099932ede6f8d4624fbddf39d27abb3b340d8c9`
OS | macOS Version 13.4.1 (c) (Build 22F770820d)

- Verified steps from [brave/brave-core#18891](https://github.com/brave/brave-core/pull/18891)
- Verified Account/Network group by is sorted high to low

https://github.com/brave/brave-browser/assets/17010094/e116cb9f-8140-4571-8838-fbed88570853
