### ISSUE TITLE
Remove Click Outside Event for the Portfolio Filters Modal

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#31021]
## Description 

We need to remove the `Out Side Click` closing event for the `Portfolio Filters` modal to prevent accidental closing of unsaved changes.

https://github.com/brave/brave-browser/assets/40611140/543fbf69-eccc-4878-aaed-025bc841a21b

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.57.27 Chromium: 115.0.5790.1314 (Official Build) beta (64-bit)
-- | --
Revision | `18977fb43f693d5a8deeb48bd1cfa52651d3f73e`
OS | Windows 11 Version 22H2 (Build 22621.1992)

- Verified steps from [brave/brave-core#18884](https://github.com/brave/brave-core/pull/18884)
- Verified Portfolio filters is not dismissed when clicked outside

https://github.com/brave/brave-browser/assets/17010094/4c12d9f5-38bd-425b-b009-196f071d23ab
