### ISSUE TITLE
[CR115] Investigate whether AcceleratorServiceFactory should/shouldn't allow guest profiles

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#31025]
This came up during the CR115 review and was noticed by @goodov. We should investigate whether `AcceleratorServiceFactory` shouldn't allow guest profiles (the `WithGuest` line here):

```
AcceleratorServiceFactory::AcceleratorServiceFactory()
    : ProfileKeyedServiceFactory(
          "AcceleratorServiceFactory",
          ProfileSelections::Builder()
              .WithRegular(ProfileSelection::kRedirectedToOriginal)
              .WithGuest(ProfileSelection::kRedirectedToOriginal)
              .Build()) {}
```

When I removed that line, however, it led to several Brave and upstream test failures. There seemed to be two main issues:
- `BraveBrowserView` performs a `ScopedObservation` of `AccelatorService::Observer`, but that will be null in guest sessions
- The vertical tabs feature attempts to retrieve accelerators in guest sessions

**Comment by goodov** [comment]
tbh I'm not 100% sure if `AcceleratorServiceFactory` should or should not exist in Guest profile.

We might just need to have it enabled to support hotkeys in all profiles if that's the main use case of this service.

**Comment by emerick** [comment]
Thanks, I updated this issue to reflect that this issue requires some investigation to determine the appropriate course of action.
