### ISSUE TITLE
[Shortcuts] Support different display NumPad keys

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#31035]
Currently, NumPad keys are shown as identical to their non-numpad equivalents. In some cases (i.e. Enter, Equals) this is correct, but in other cases (1, Num1) it can be confusing because they are treated as two separate keys:
![image](https://github.com/brave/brave-browser/assets/7678024/ff274421-b7c4-4c90-86b4-5c2ace116b75)

We should treat these keys as separate in the UI, where appropriate (in the backend, we're doing the right thing already)

**Comment by kjozwiak** [comment]
The above requires `1.53.100` or higher for `1.53.x` verification 👍

**Comment by LaurenWags** [comment]
Verified with

```
Brave | 1.53.100 Chromium: 114.0.5735.133 (Official Build) beta (x86_64)
-- | --
Revision | fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}
OS | macOS Version 13.4 (Build 22F66)
```

Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/31035#issue-1755795731, ensured that the `Select Tab` had both `[x]` & `Num[x]` shorts being displayed under `brave://settings/system/shortcuts` as per the following:

<img width="1449" alt="1" src="https://github.com/brave/brave-browser/assets/28145373/00c57cf1-0c9f-42db-9528-f8a5ee894848">
