### ISSUE TITLE
BR panel shows Include in Auto-Contribute as enabled when a-c is disabled globally

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#3103]
## Description 

BR panel shows Include in Auto-Contribute as enabled when a-c is disabled globally

## Steps to Reproduce

   1. Enable rewards
   2. Disable a-c in brave://rewards
   3. Visit any site and open BR panel , `Include in  Auto-Contribute` is enabled even though a-c is disabled in rewards settings page

## Actual result:

BR panel shows Include in Auto-Contribute as enabled when a-c is disabled globally

## Expected result:
BR panel should probably hide the `Attention` and `Include in Auto-contribute` lines when a-c is disabled.

## Reproduces how often: 

Easy

## Brave version (brave://version info)

All

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
No
- Is the issue reproducible on the latest version of Chrome? 
No

### Additional Information

cc: @davidtemkin @jenn-rhim @NejcZdovc 
Issue reported by community user https://community.brave.com/t/bug-alert-i-turned-off-the-automatic-rewards-but-it-turns-itself-on-for-any-new-website-visited/43082/7

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.61.37 Chromium: 73.0.3683.39 (Official Build) beta (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

Used test plan from https://github.com/brave/brave-core/pull/1525

a-c on
![image](https://user-images.githubusercontent.com/34715963/53370155-46869180-394d-11e9-9a2d-ad98f5a7b1d6.png)

a-c off
![image](https://user-images.githubusercontent.com/34715963/53370192-5f8f4280-394d-11e9-8ae0-6374c41591e4.png)
