### ISSUE TITLE
Bundle `brave_extension` and `brave_rewards` into Linux source zip file 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#3104]
## Description 

Bundle `brave_extension` and `brave_rewards` into Linux source zip file. Not bundling this caused UI issues on Arch based distros. Thanks to @rjocoleman for finding the root cause of the issue https://github.com/brave/brave-browser/issues/1150#issuecomment-456952877

### Additional Information

https://community.brave.com/t/brave-shield-ui-bug/33570/63
Bundling the locales would fix the following issues 
#1150 #2138 #1555 

cc: @bbondy @rebron @bsclifton @kjozwiak would be good to get this done on the next beta/dev and then for release so that fixes the UI for Arch based distros

**Comment by flipsa** [comment]
Just adding to this and #1150: I use Gentoo and I'm affected as well, so it's not just Arch based distros...

**Comment by simonhong** [comment]
Duplicated with https://github.com/brave/brave-browser/issues/3399 and fixed by https://github.com/brave/brave-browser/pull/3446.

**Comment by simonhong** [comment]
@srirambv Should we set milestone also for closed issue with duplication?

**Comment by bbondy** [comment]
@simonhong only if the steps to reproduce are different and we want to verify it.  Otherwise just goes in the duplicate / not actionable milestone. I'll put it there.

**Comment by simonhong** [comment]
@bbondy got it. Thanks! Done for https://github.com/brave/brave-browser/issues/1150.
