### ISSUE TITLE
[Sync] Copy code words icon is missing on current Nightly

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#31040]
## Description 

Copy code words icon is missing on current Nightly

## Steps to Reproduce

   1. Take 1.54.38 Nightly
   2. Create Sync Chain
   3. Try to copy sync code - there is no icon on a button, but the button is still clickable, see the screenshot below

## Actual result:

![image](https://github.com/brave/brave-browser/assets/24739341/4a8b33c5-22cf-479f-b1ed-04c4c498093b)

## Expected result:
There is an icon

## Reproduces how often: 

Easily

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

1.54.38 Chromium: 114.0.5735.90 (Official Build) nightly (64-bit) - reproduced
1.53.85 Chromium: 114.0.5735.110 (Official Build) beta (64-bit) - not reproduced
1.52.122 Chromium: 114.0.5735.110 (Official Build) (64-bit) - not reproduced

+Update
1.54.56 Chromium: 114.0.5735.110 (Official Build) nightly (64-bit) - reproduced
1.53.87 Chromium: 114.0.5735.110 (Official Build) beta (64-bit) - not reproduced

1.54.20 - not reproduced
1.54.21 - reproduced

Tested all on Linux

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.54.83 Chromium: 115.0.5790.40 (Official Build) beta (x86_64)
-- | --
Revision | 071c9ddea889c3c7887daf4eac13fed72d4fff62-refs/branch-heads/5790@{#979}
OS | macOS Version 11.7.8 (Build 20G1351)

Followed the steps to reproduce found in https://github.com/brave/brave-browser/issues/31040#issue-1756462570

### Confirmed the clipboard icon is present and has click/highlighted states

`Dark` | `Light`
-------|-------
<img width="1964" alt="Screen Shot 2023-06-28 at 5 58 42 PM" src="https://github.com/brave/brave-browser/assets/387249/3825bdc1-ced1-4cb9-b8e0-4d0a62432b54"> | <img width="1964" alt="Screen Shot 2023-06-28 at 6 03 21 PM" src="https://github.com/brave/brave-browser/assets/387249/7cab2d40-233d-4646-b4d4-208267b7f734">

Also confirmed (not pictured) that the icon hover-state highlight worked
