### ISSUE TITLE
Add Wallet v2 filters to NFT tab

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#31041]

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.58.105 Chromium: 116.0.5845.114 (Official Build) beta (64-bit)
-- | --
Revision | 5a895596bcd7fcd930dab0714ea5cfa86c5aa0a7
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#18902](https://github.com/brave/brave-core/pull/18902)
- Verified NFT tokens can be grouped by Account or Networks 
- Verified Network icon can be shown/hidden

https://github.com/brave/brave-browser/assets/17010094/3afb82eb-02d1-49c0-a57f-65b5038d4564
