### ISSUE TITLE
Show desktop notification to the user when establishing a vpn connection from Wireguard service

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#31053]
If connection established we have to show desktop notification with connection details

**Comment by spylogsster** [comment]
cc @bsclifton @mattmcalister @rebron

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.59.94 Chromium: 117.0.5938.88 (Official Build) beta (64-bit)
-- | --
Revision | 2dca22d0a20096c32df5af4c88700a0b31acb55c
OS | Windows 11 Version 22H2 (Build 22621.2283)
```

Notification shown when `Wireguard protocol in Brave VPN` setting is enabled 

1. Install 1.59.94
2. launched Brave
3. open System > Notifications
4. confirmed `Brave Beta` is enabled for Notifications 
5. open `brave://settings/system` 
6. verified `Brave VPN` setting is enabled
7. purchased, configured Brave VPN
8. connected to VPN via VPN panel 
9. disconnected to VPN via VPN panel 
10. open notification center

#### Confirmed `Brave VPN - Connected` notification is shown in the lower right corner
#### Confirmed `Brave VPN - Disconnected` notification is shown in the lower right corner 
#### Confirmed `Brave VPN - Connected` notification is shown in Windows notifications center  
#### Confirmed `Brave VPN - Disconnected` notification is shown in Windows notifications center

step 8 | step 9 | step 10
--- | --- | -----
<img width="957" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/083b50b7-f8e4-47ee-a280-c234994093e4">|<img width="954" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/f4eb8ebc-0d7e-4b82-88cf-29f3dcceb91c">|<img width="171" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/d7a7b0c1-2165-4a42-865f-d3bbc74b7d63">

**Comment by stephendonner** [comment]
## Verification `PENDING` using

```

```

1. install `1.59.94`
2. launched Brave
3. open `System` > `Notifications`
4. confirmed `Brave Beta` is enabled for Notifications 
5. open `brave://settings/system` 
6. verified `Brave VPN` setting is enabled as a default
7. purchased and configured Brave VPN
8. connected to VPN via VPN panel 
9. disconnected to VPN via VPN panel 
10. open notification center

### Confirmed notifications are shown when `Wireguard protocol in Brave VPN` setting is enabled as following:
  - Confirmed `Brave VPN - Connected` notification is shown in the lower right corner of the screen
  - Confirmed `Brave VPN - Disconnected` notification is shown in the lower right corner of the screen
  - Confirmed `Brave VPN - Connected` notification is shown in Windows notifications center  
  - Confirmed `Brave VPN - Disconnected` notification is shown in Windows notifications center

step 8 | step 9 | step 10
--- | --- | -----
