### ISSUE TITLE
cmd+a shortcut to select all text not working on URL bar

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#31059]
## Description 

Reported by @StephenHeaps and reproduced by @soner-yuksel and @LaurenWags 

See https://bravesoftware.slack.com/archives/C02DT9F5EP5/p1686766361475489?thread_ts=1686624460.493189&cid=C02DT9F5EP5 for more info.

Generally, with the URL bar focused, pressing CMD+A (macOS select-all text) or selecting Edit > Select All from macOS menu is moving to the next tab unless all text is already selected in the URL bar.

Maybe the shortcuts functionality is causing this issue or some other griffin study enabled on relaunch as the issue does not reproduce on a clean profile prior to getting griffin seed.

## Steps to Reproduce

   1. Clean profile 1.53.x (do not relaunch to pull griffin)
   2. Open a 3-4 tabs with a few sites
   3. On the first tab focus on URL box but don't have any text selected
   4. Either cmd+a or if on macOS, go to Edit from macOS menu and choose "Select all" --> all text in URL bar is selected as expected
   5. Close and relaunch to pull griffin
   6. On the first tab focus on URL box but don't have any text selected
   7. Either cmd+a or if on macOS, go to Edit from macOS menu and choose "Select all" --> you are navigated to the next tab and your URL text is not selected

## Actual result:

Navigated to next tab and URL bar text is not selected. Thanks for the videos @StephenHeaps!

https://bravesoftware.slack.com/archives/C02DT9F5EP5/p1686766361475489?thread_ts=1686624460.493189&cid=C02DT9F5EP5

https://bravesoftware.slack.com/archives/C02DT9F5EP5/p1686767019516679?thread_ts=1686624460.493189&cid=C02DT9F5EP5

## Expected result:

All text in URL bar to be selected

## Reproduces how often: 

easily

## Brave version (brave://version info)

```
Brave | 1.53.92 Chromium: 114.0.5735.110 (Official Build) beta (x86_64)
-- | --
Revision | 1c828682b85bbc70230a48f5e345489ec447373e-refs/branch-heads/5735_90@{#13}
OS | macOS Version 13.4 (Build 22F66)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? yes 1.53.x
- Can you reproduce this issue with the nightly channel? yes 1.54.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron @brave/qa-team

**Comment by hamza-syndica** [comment]
I was going crazy, I thought my Karabiner setup was messed up. I hope, it fixes quick.

**Comment by kjozwiak** [comment]
The above requires `1.53.102` or higher for `1.53.x` verification 👍
