### ISSUE TITLE
Edit Visible Assets modal is not return full token list on second open

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#31051]
## Description 

The `Edit Visible Assets` modal is not return the  `full token list` on second open

## Steps to Reproduce

   1. Open the `Wallet` and open the `Edit Visible Assets` modal
   2. Scroll the list, it shows the `Full token list`
   3. Close the `Edit Visible Assets` modal and reopen it
   4. Scroll the list, it only shows the users visible tokens.

## Actual result:

https://github.com/brave/brave-browser/assets/40611140/5fcee0b4-b4c4-4ed3-939f-76618b98f669

## Expected result:
Should always include the full tokens list.

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.57.24 Chromium: 115.0.5790.136 (Official Build) beta (64-bit)
-- | --
Revision | `8099932ede6f8d4624fbddf39d27abb3b340d8c9`
OS | Linux

- Verified steps from [brave/brave-core#18905](https://github.com/brave/brave-core/pull/18905)
- Verified full token list is shown when opening the edit visible asset list second open

https://github.com/brave/brave-browser/assets/17010094/c90abdad-03a5-4b72-9e76-c1e53865db97


---------------------

**Verification passed on**

Brave | 1.57.24 Chromium: 115.0.5790.136 (Official Build) beta (64-bit)
-- | --
Revision | `8099932ede6f8d4624fbddf39d27abb3b340d8c9`
OS | Windows 11 Version 22H2 (Build 22621.1992)

- Verified steps from [brave/brave-core#18905](https://github.com/brave/brave-core/pull/18905)
- Verified full token list is shown when opening the edit visible asset list second open

https://github.com/brave/brave-browser/assets/17010094/849c073b-4787-46a5-a140-e5686828b80b


---------------------

**Verification passed on**

Brave | 1.57.24 Chromium: 115.0.5790.136 (Official Build) beta (arm64)
-- | --
Revision | `8099932ede6f8d4624fbddf39d27abb3b340d8c9`
OS | macOS Version 13.4.1 (c) (Build 22F770820d)

- Verified steps from [brave/brave-core#18905](https://github.com/brave/brave-core/pull/18905)
- Verified full token list is shown when opening the edit visible asset list second open

https://github.com/brave/brave-browser/assets/17010094/3262c26c-9697-44b2-b992-685ed7e9579e
