### ISSUE TITLE
about:gpu differences between Brave and Chrome

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#3105]
I verified this with C72 for both Chrome and Brave.

Actual: Viz Service Display Compositor: Disabled on Brave vs enabled on chrome.
Expected: They should be the same

<img width="468" alt="capture d ecran le 2019-01-25 a 09 24 12" src="https://user-images.githubusercontent.com/831718/51751527-0f3d7000-2083-11e9-921d-460e2e359343.png">

<img width="438" alt="capture d ecran le 2019-01-25 a 09 26 01" src="https://user-images.githubusercontent.com/831718/51751687-73603400-2083-11e9-9553-b1f39fda90a5.png">

Viz Service Display Compositor
Chrome 71: Disabled
Chrome 72: Enabled

Brave 71: Disabled
Brave 72: Disabled

**Comment by LaurenWags** [comment]
@bbondy verified the `Viz Service Display Compositor` setting says `Enabled`, any other testing required for this one?
![screen shot 2019-01-25 at 3 03 41 pm](https://user-images.githubusercontent.com/28145373/51770085-d1f0d680-20b2-11e9-8ccd-b1034de8ec02.png)

**Comment by bbondy** [comment]
nothing else required. Thanks!

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.59.30 Chromium: 72.0.3626.71 (Official Build) (64-bit)
-- | --
Revision | f52ccad2a6a3c65fc9e0c591a517ceab1198dac0-refs/branch-heads/3626@{#763}
OS | Mac OS X
