### ISSUE TITLE
Update local geo value

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#31058]
## Description

https://github.com/brave/internal/issues/1039

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.58.91 Chromium: 116.0.5845.96 (Official Build) beta (x86_64)
-- | --
Revision | 620fa9c0307b294dd6e7c6b0976bc1f93fecf369
OS | macOS Version 13.5 (Build 22G74)
```

**Comment by GeetaSarvadnya** [comment]
Verificaton **PASSED** on `Vivo X70 Pro version 12` running `Bravemonoarm54.apk_1.58.110`

Verification notes can be found under https://github.com/brave/internal/issues/1039#issuecomment-1705435274
