### ISSUE TITLE
[Android] Add P3A for set brave as default feature

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#31056]
Currently there's a P3A question Brave.Core.IsDefault. It always returns "No" when filtering by Android.
This issue is to set `Brave.Core.IsDefault` based on whether Brave is set as a default browser on device. 
We already have the function to check for the default browser and based on that we decide to show the UI for the feature.

**Comment by deeppandya** [comment]
@DJAndries Do we have any native function we can for android ?

**Comment by DJAndries** [comment]
> @DJAndries Do we have any native function we can for android ?

We can use `MiscAndroidMetrics` as the bridge

**Comment by kjozwiak** [comment]
The above requires `1.65.110` or higher for `1.65.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 15 AP31.240322.018 release-keys
Brave build: 1.65.110
Chromium: 124.0.6367.29 (Official Build) (64-bit) 
```
---------------------------

<details>
<summary> Brave.Core.IsDefault = 0 </summary>

**STEPS:**
1. Fresh install Brave
2. Go through onboarding > Make sure Brave is not the `default` browser
3. Open `brave://local-state` file
4. Look for `Brave.Core.IsDefault` metrics > *Verify*

**ACTUAL RESULTS:**
- Verified that the metrics `Brave.Core.IsDefault` response value is `0` as expected as brave is not the default browser

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/82829e3c-971b-4a85-ae5c-b755ec6ff281) | ![2](https://github.com/brave/brave-browser/assets/128532965/68461ebe-8039-4bd1-89ce-2e630e79df57) | ![3](https://github.com/brave/brave-browser/assets/128532965/fe5df480-43d4-4437-921e-f252026c5156) |
</details>

<details>
<summary> Brave.Core.IsDefault = 1 </summary>

**STEPS:**
1. Fresh install Brave
2. Go through onboarding > Set Brave as the `default` browser
3. Restart the browser
4. Open `brave://local-state` file
5. Look for `Brave.Core.IsDefault` metrics > *Verify*

**ACTUAL RESULTS:**
- Verified that the metrics `Brave.Core.IsDefault` response value is `1` as expected as brave is not the default browser

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/3cd501a8-c886-4006-a01b-c5ea2f74d78a) | ![2](https://github.com/brave/brave-browser/assets/128532965/491f075d-52a1-4670-89d5-6104a27f7d14) | ![3]() | ![4]() |
</details>
