### ISSUE TITLE
get asset info for EVM assets when contract address is inputted

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#31062]
## Description 

at the moment, we only asset info for assets on Ethereum Mainnet. We should enable this for all other preloaded networks and potentially Arbitrum and Zksync networks.

## Steps to Reproduce

   1. try adding GMX (contract address -> 0x62edc0692bd897d2295872a9ffcac5425011c661 https://www.coingecko.com/en/coins/gmx) to brave wallet
   2. 
   3. 

## Actual result:

![Screenshot 2023-06-14 at 21 38 23](https://github.com/brave/brave-browser/assets/12224304/fa0781ff-a117-4cc2-a308-6be45d7e5e69)

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by Douglashdaniel** [comment]
We need some `brave-wallet-core` support to do this. At the moment our `assetRatioService.getTokenInfo(contract_address)` method can only query `Token Info` from the `Ethereum Mainnet`, `EVM` chains and `Solana` networks are not supported.

We should add a `chainId` argument `getTokenInfo(contract_address, chain_id)` to allow querying `Token Info` for other chains.

**Comment by onyb** [comment]
Fixed in https://github.com/brave/brave-core/pull/21191

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.63.169 Chromium: 122.0.6261.111 (Official Build) (64-bit)
-- | --
Revision | 0e0a975cf46d4d026e184ca61788e1da6f0d76bc
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from issue description
- Verified able to add EVM tokens
- Verified adding contract address automatically populates the token details

https://github.com/brave/brave-browser/assets/17010094/b52d8980-8aa5-4546-865a-30fed403a19c
