### ISSUE TITLE
Migrate to slices for querying prices

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#31065]
### Definition of done

- [ ] Do not fetch spot prices for tokens with no balances
- [ ] Avoid duplicate price requests
- [ ] Most/all usages of `assetRatioService.getPrice` are migrated to slices.
- [ ] No more usage of `refreshPrices()`.

### Test plan

Do a basic check of all places wherever fiat values or prices are displayed.

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.57.18 Chromium: 115.0.5790.98 (Official Build) beta (64-bit)
-- | --
Revision | `d515871a6c6df7d2843e755c8b7dda9b744f26d6`
OS | Windows 11 Version 22H2 (Build 22621.1992)

- Verified steps from issue description
- Verified fiat values are properly shown in all the places
