### ISSUE TITLE
Dupe Networks showing up on network dropdown

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#31063]
## Description 

see post -> https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1686770659965979

## Steps to Reproduce

   1. zksync showing up twice
   2. 
   3. 

## Actual result:

![Screenshot 2023-06-14 at 21 22 51](https://github.com/brave/brave-browser/assets/12224304/47815294-be3d-4df8-9bb3-88640b613e96)

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.53.103` or higher for `1.53.x` verification 👍

**Comment by srirambv** [comment]
**Verification passed on **

Brave | 1.53.104 Chromium: 115.0.5790.40 (Official Build) (64-bit)
-- | --
Revision | `071c9ddea889c3c7887daf4eac13fed72d4fff62-refs/branch-heads/5790@{#979}`
OS | Windows 11 Version 22H2 (Build 22621.1848)

- Verified steps from issue description
- Verified zksync networks are only shown once

https://github.com/brave/brave-browser/assets/17010094/1307aa60-6323-4df8-8c6d-0be12dceae3a
