### ISSUE TITLE
[Feature Request] Expose Vertical tabs Toggle and Mouseover Expand/Collapse as Quick Commands and Shortcuts.

### ISSUE THREAD

**Issue by Emi-TheDhamphirInLoveUnderTheFrozenStar** [brave/brave-browser#31064]
Vertical Tabs Expand and Collapse and the mouseover actions should be exposed as commands and shortcuts, so [power] users can easily trigger them with Quick commands (`Ctrl+space`) or bind them to a customized shortcut to easily do these things with keyboard in Brave without having to always go to Settings or mouse and click buttons.

**Comment by rebron** [comment]
cc: @fallaciousreasoning @sangwoo108 @aguscruiz  I don't know if there's a keyboard binding that's obvious here.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.58.96 Chromium: 116.0.5845.96 (Official Build) beta (x86_64)
-- | --
Revision | 153399f19fc2a3db55e64efb3ad06cb52d8a39fb
OS | macOS Version 11.7.9 (Build 20G1426)
```

**Comment by ibehnam** [comment]
> ## Verification `PASSED` using
> ```
> Brave | 1.58.96 Chromium: 116.0.5845.96 (Official Build) beta (x86_64)
> -- | --
> Revision | 153399f19fc2a3db55e64efb3ad06cb52d8a39fb
> OS | macOS Version 11.7.9 (Build 20G1426)
> ```
> 
> ### NOTE: only covered `Toggle Vertical Tabs Expand`, here; #32445 covers the rest.
> ## Keyboard Shortcuts
> ### `Toggle Vertical Tabs Expand` - `PASSED`
> Steps:
> 
> 1. installed `1.58.96`
> 2. launched Brave
> 3. opened `brave://settings`
> 4. clicked on `System`
> 5. clicked on `Shortcuts`
> 6. searched for `toggle vertical tabs expand`
> 7. clicked `Add`
> 8. pressed `Command` + `E`
> 9. clicked `Save`
> 10. context-clicked on a tab
> 11. selected `Use Vertical Tabs`
> 12. loaded a few news websites in new tabs
> 13. pressed `Command` + `E`
> 14. confirmed tabs collapsed
> 15. pressed `Command` + `E` again
> 16. confirmed tabs expanded
> 
> example	example	example	example
> <img alt="Screen Shot 2023-08-21 at 12 22 46 PM" width="1226" src="https://github.com/brave/brave-browser/assets/387249/d9bc915c-6ddb-4ba6-bfc5-9fe8de50cc0a">	<img alt="Screen Shot 2023-08-21 at 12 23 21 PM" width="1226" src="https://github.com/brave/brave-browser/assets/387249/05023c05-42c8-47b8-b898-7908ab3a64dd">	<img alt="Screen Shot 2023-08-21 at 12 26 06 PM" width="1226" src="https://github.com/brave/brave-browser/assets/387249/6ce30769-7248-4bb7-ad4d-f56beaa565b9">	<img alt="Screen Shot 2023-08-21 at 12 26 04 PM" width="1226" src="https://github.com/brave/brave-browser/assets/387249/8519a146-a479-4d08-a312-e7f22ad1ee4f">
> ## Quick Commands
> ### `Toggle Vertical Tabs Expanded` - `PASSED`
> ### Steps:
> 1. installed `1.58.96`
> 2. launched Brave
> 3. opened `brave://flags`
> 4. set `brave://flags/#quick-commands` to `Enabled`
> 5. clicked `Relaunch`
> 6. loaded a bunch of news sites in new tabs
> 7. pressed `control` + `spacebar` to invoke `Quick Commands`
> 8. used type-down autocomplete + arrows to select `Toggle Vertical Tabs Expanded`
> 9. pressed `return`
> 10. confirmed vertical tabs expanded
> 11. repeated steps 7-9
> 12. confirmed vertical tabs collapsed
> 
> example	example	example	example	example
> <img alt="Screen Shot 2023-08-21 at 1 00 22 PM" width="1226" src="https://github.com/brave/brave-browser/assets/387249/41a7d854-d222-4095-899f-d1415ede437f">	<img alt="Screen Shot 2023-08-21 at 1 01 12 PM" width="1226" src="https://github.com/brave/brave-browser/assets/387249/25a483be-bfd8-4aae-936c-590c4515ae9a">	<img alt="Screen Shot 2023-08-21 at 1 01 17 PM" width="1226" src="https://github.com/brave/brave-browser/assets/387249/538f4bbf-f138-4d78-9264-3b8c5745b1a4">	<img alt="Screen Shot 2023-08-21 at 1 01 23 PM" width="1226" src="https://github.com/brave/brave-browser/assets/387249/9d76190c-2894-4c82-b8f3-c338a29e1894">	<img alt="Screen Shot 2023-08-21 at 1 01 26 PM" width="1226" src="https://github.com/brave/brave-browser/assets/387249/8e6ff6d7-8973-44c6-b1d9-26fb0ef5e88c">

This seems to be removed in the latest Brave version on macOS. There's no place to add the shortcut for toggling the side bar tabs.

**Comment by fallaciousreasoning** [comment]
Can you access the brave://settings/system/shortcuts page?

**Comment by ibehnam** [comment]
> brave://settings/system/shortcuts

No, it redirects to `brave://settings/`. I can access another page `brave://extensions/shortcuts` but that's just for the extension shortcuts.

**Comment by fallaciousreasoning** [comment]
Can you check brave://flags/#brave-commands is enabled (or set to default)?

**Comment by ibehnam** [comment]
> Can you check brave://flags/#brave-commands is enabled (or set to default)? I get the same behavior you're describing when I disable that flag.

Thank you! Yes, that was disabled. After enabling it, I was able to see the systems shortcut page and set a shortcut for vertical tabs.

**Comment by fallaciousreasoning** [comment]
Glad I could help!

**Comment by peterszarvas94** [comment]
Note: you also need to disable "Expand vertical tabs independently per window", otherwise it will not work, even if the above steps are done!

https://community.brave.com/t/shortcut-not-working-toggle-vertical-tabs-expanded/595843
