### ISSUE TITLE
Throttle concurrent promises

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#31066]
## Description 

The wallet is creating too many promises at a time, overworking the CPU. Batch `Promise.all` calls to reduce the amount for promises to await at a given time.

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.57.18 Chromium: 115.0.5790.98 (Official Build) beta (64-bit)
-- | --
Revision | `d515871a6c6df7d2843e755c8b7dda9b744f26d6`
OS | Windows 11 Version 22H2 (Build 22621.1992)

- Verified steps from [brave/brave-core#18913](https://github.com/brave/brave-core/pull/18913)
- Verified wallet works as expected
- Verified price load for throttled for native token first and then the remaining tokens in the asset list
