### ISSUE TITLE
Migrate Etherscan calls to new proxy

### ISSUE THREAD

**Issue by nvonpentz** [brave/brave-browser#31079]
We have new proxies deployed, so we should update the codebase to point to the new URLs.  The response schema has changed slightly (no more wrapper with lastUpdated), so well need to update ParseTokenInfo incomponents/brave_wallet/browser/asset_ratio_response_parser.cc to parse the new response format.

Also we'll need to add the Brave Services Key if it's not included already.

**Comment by kjozwiak** [comment]
@srirambv going to label this one as `QA/Yes` so we can quickly verify that the Stripe onramp is working as mentioned via https://github.com/brave/brave-core/pull/19566#issue-1835600879. The above requires `1.57.41` or higher for `1.57.x` verification 👍
