### ISSUE TITLE
Permission is not reset on page reopen if 30 seconds has not passed

### ISSUE THREAD

**Issue by goodov** [brave/brave-browser#31072]
After https://github.com/brave/brave-browser/issues/30090 when permission is set to "forget on website close", it is reset after 30 seconds the tab is closed.

But this change introduced a subtle bug: if you reopen the same website BEFORE 30 seconds has expired, the permission won't be reset after the tab is closed.

**Comment by LaurenWags** [comment]
@goodov sounds like the test is basically:

1. Open a site, select "Forget me" from shields
2. Close site
3. Reopen site within 30 seconds
4. Close site again
5. Wait at least 30 seconds
6. Ensure first party storage is cleared

Is the above correct? if not, could you provide a test plan?

**Comment by goodov** [comment]
> @goodov sounds like the test is basically:
> 
> 1. Open a site, select "Forget me" from shields
> 2. Close site
> 3. Reopen site within 30 seconds
> 4. Close site again
> 5. Wait at least 30 seconds
> 6. Ensure first party storage is cleared
> 
> Is the above correct? if not, could you provide a test plan?

Not exactly. This is about resetting a permission when it's expired. This is covered by "Test case 3" here https://github.com/brave/brave-browser/issues/30090#issuecomment-1587341331

```
#### Test case 3

1. Open https://permission.site
2. Trigger any permission, choose permission lifetime "until I close the site".
3. Close the website, wait 30 seconds, reopen it.
4. Expect permission is reset.
```

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.54.90 Chromium: 115.0.5790.56 (Official Build) beta (x86_64)
-- | --
Revision | ebcfb87c1393f36955cfa2f6451a1767e3dc3ee5-refs/branch-heads/5790@{#1193}
OS | macOS Version 14.0 (Build 23A5276g)

### Steps:
1. installed `1.54.90`
2. launched Brave
3. loaded `permission.site`
4. clicked on `Screen Share`
5. granted `Brave Browser Beta` the appropriate permission via the macOS `Screen Recording` dialog
6. chose a tab to share
7. clicked `Share`
8. 


example | example | example | example
---------|---------|----------|---------
<img width="1285" alt="Screenshot 2023-07-03 at 3 01 46 PM" src="https://github.com/brave/brave-browser/assets/387249/e2c585eb-f94f-48fa-9bb1-5a5894e12bfb"> | <img width="573" alt="Screenshot 2023-07-03 at 2 50 06 PM" src="https://github.com/brave/brave-browser/assets/387249/31791b32-d176-4b67-8c99-3ad1864cf6c2"> | <img width="827" alt="Screenshot 2023-07-03 at 3 04 29 PM" src="https://github.com/brave/brave-browser/assets/387249/42bfd4fa-54ef-46dc-b800-4ddb8903991e"> | <img width="862" alt="Screenshot 2023-07-03 at 2 50 10 PM" src="https://github.com/brave/brave-browser/assets/387249/d44f9754-4fd0-4250-9acd-f8eceb4c7487">

**Comment by LaurenWags** [comment]
thanks for the clarification @goodov! have updated my initial comment so hopefully no one tries to test the wrong thing 😄

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.57.41 Chromium: 115.0.5790.171 (Official Build) beta (64-bit)
-- | --
Revision | adc7e3e2defac3f9b39cb22bcbb354b72b74c2eb
OS | Windows 11 Version 22H2 (Build 22621.1992)
```
Steps:

1. installed 1.57.41
2. launched Brave
3. loaded permission.site
4. clicked on Microphone
5. clicked `Allow` on the permissions prompt for default selection, until I close this site  
6. opened a new window
7. closed the previous tab/window
8. waited 30 seconds
9. reopened permission.site
10. checked the status of the Microphone button on the page
11. clicked on it
12. confirmed I was again prompted for permissions

step 3 | step 5 | step 9 | step 10 | step 12
---- | ---- | ----- | ---- | -----
<img width="956" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/dbb9941c-e432-4293-88f2-c54d3c2c238b">|<img width="954" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/8d82ba5d-a542-4dd7-b8cc-c16864910eb9">|<img width="960" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/a0edf864-0854-4836-a3c9-4e1586a51efe">|<img width="946" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/8572127e-ed94-42d5-a609-655359c2908c">|<img width="959" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/a1da2e4b-1e7b-45de-8d5e-97b26f07e90b">
