### ISSUE TITLE
Portfolio Group showing loading skeleton during search

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#31070]
## Description 

When searching for a token that you don't have on the `Portfolio` screen,
the group balance will show a loading skeleton.

## Steps to Reproduce

   1. Go to the `Portfolio` and group by networks.
   2. Search for a token that you don't have.
   3. The groups will show a loading skeleton for the balance.

## Actual result:

https://github.com/brave/brave-browser/assets/40611140/7c4c6308-5e7b-43b1-8725-01902aed7ea2

## Expected result:
Should just show a `$0.00` balance if no token is found.

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.57.24 Chromium: 115.0.5790.136 (Official Build) beta (64-bit)
-- | --
Revision | `8099932ede6f8d4624fbddf39d27abb3b340d8c9`
OS | Linux

- Verified steps from [brave/brave-core#18917](https://github.com/brave/brave-core/pull/18917)
- Verified searching for a non-existent token doesn't show loading skeletons under accounts

https://github.com/brave/brave-browser/assets/17010094/0a86f1eb-a4c8-4c67-950d-153aaac64205

---------------------

**Verification passed on**

Brave | 1.57.24 Chromium: 115.0.5790.136 (Official Build) beta (64-bit)
-- | --
Revision | `8099932ede6f8d4624fbddf39d27abb3b340d8c9`
OS | Windows 11 Version 22H2 (Build 22621.1992)

- Verified steps from [brave/brave-core#18917](https://github.com/brave/brave-core/pull/18917)
- Verified searching for a non-existent token doesn't show loading skeletons under accounts

https://github.com/brave/brave-browser/assets/17010094/63729508-7c4f-4229-b284-6945ce5a148a

---------------------

**Verification passed on**

Brave | 1.57.24 Chromium: 115.0.5790.136 (Official Build) beta (arm64)
-- | --
Revision | `8099932ede6f8d4624fbddf39d27abb3b340d8c9`
OS | macOS Version 13.4.1 (c) (Build 22F770820d)

- Verified steps from [brave/brave-core#18917](https://github.com/brave/brave-core/pull/18917)
- Verified searching for a non-existent token doesn't show loading skeletons under accounts

https://github.com/brave/brave-browser/assets/17010094/b7c6ea80-01dd-4ffd-b809-00154138f061
