### ISSUE TITLE
Portfolio Fiat change showing more than 2 decimals

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#31081]
## Description 

The Portfolio `Fiat change` is showing more than 2 decimals

## Steps to Reproduce

   1. Go to the `Portfolio` page and switch between history timeliness
   2. Sometimes the `Fiat change` decimal places are more than 2

## Actual result:

https://github.com/brave/brave-browser/assets/40611140/51144ff3-39b1-4ded-91e6-bac83b4ad320

## Expected result:
Should limit to 2 decimal places

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.57.24 Chromium: 115.0.5790.136 (Official Build) beta (64-bit)
-- | --
Revision | `8099932ede6f8d4624fbddf39d27abb3b340d8c9`
OS | Linux

- Verified steps from [brave/brave-core#18933](https://github.com/brave/brave-core/pull/18933)
- Verified Portolio Fiat changes shows only 2 decimal values

https://github.com/brave/brave-browser/assets/17010094/631ca0fd-14e5-4c73-b8a0-5d2446045dfb


---------------------

**Verification passed on**

Brave | 1.57.24 Chromium: 115.0.5790.136 (Official Build) beta (64-bit)
-- | --
Revision | `8099932ede6f8d4624fbddf39d27abb3b340d8c9`
OS | Windows 11 Version 22H2 (Build 22621.1992)

- Verified steps from [brave/brave-core#18933](https://github.com/brave/brave-core/pull/18933)
- Verified Portolio Fiat changes shows only 2 decimal values

https://github.com/brave/brave-browser/assets/17010094/796706fc-8704-42cb-84db-9219f88e9517


---------------------

**Verification passed on**

Brave | 1.57.24 Chromium: 115.0.5790.136 (Official Build) beta (arm64)
-- | --
Revision | `8099932ede6f8d4624fbddf39d27abb3b340d8c9`
OS | macOS Version 13.4.1 (c) (Build 22F770820d)

- Verified steps from [brave/brave-core#18933](https://github.com/brave/brave-core/pull/18933)
- Verified Portolio Fiat changes shows only 2 decimal values

https://github.com/brave/brave-browser/assets/17010094/0e30eadc-6946-4b7f-b76d-a97b772e14c4
