### ISSUE TITLE
Google Drive files popup doesn't appear when attempting to open a file via 3rd-party website

### ISSUE THREAD

**Issue by Eido95** [brave/brave-browser#3108]
## Description 
Important to note: **The issue resolve itself when disabling Brave Shields.**

I want to open a file, which is stored on my Google Drive, via [Xodo PDF Editor App](https://www.xodo.com/app/), for editing purposes.

When clicking the _Google Drive_ button, to browse the file from Google Drive, the Google Drive files explorer popup - not being shown.

## Steps to Reproduce

   1. Open Brave browser.
   2. Navigate to https://www.xodo.com/app/.
   3. Click on _Google Drive_ button.

## Actual result:
1. Nothing happens (Google Drive files explorer not being shown).
2. Error in JavaScript file seems to be thrown (build.js:37), so no _actual_ requests are sent to Google Drive API (as seems in Developer tools Network tab).

## Expected result:
1. Google Drive files explorer should be shown, and it will be possible to browse a file from Google Drive, to be opened via the Xodo App.
2. Requests should be sent to Google Drive API.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
```
Brave: 0.58.21 Chromium: 71.0.3578.98 (Official Build) (64-bit)
Revision: 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS: Windows
JavaScript: V8 7.1.302.31
Flash: (Disabled)
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
```

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Didn't try that.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
**Yes!**
- Is the issue reproducible on the latest version of Chrome?  
No.

### Additional Information
**The issue resolve itself when disabling Brave Shields.**

**Comment by srirambv** [comment]
Can you  enabling all cookies from shields and check if it solves the issue?

**Comment by Eido95** [comment]
@srirambv, I tested what you requested.
Allowing all cookies from shields while shield is up, DID solve the issue.

**Comment by srirambv** [comment]
Reopening the issue and assigning to webcompat project.

**Comment by diracdeltas** [comment]
Almost certainly a 3rd party referer issue

**Comment by pes10k** [comment]
fixed with https://github.com/brave/brave-browser/issues/8696
