### ISSUE TITLE
Remove pk_cid parameter

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#31084]
While [described as a campaign tracking ID](https://help.piwik.pro/support/questions/how-can-i-customize-piwik-pro-campaign-parameters/), the official Piwik documentation says that the glcid is typically passed through in this parameter.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.58.78 Chromium: 116.0.5845.51 (Official Build) nightly (64-bit)
-- | --
Revision | ca260d83d1ffda3cb35bff4bdc3251f30f9c8ccd
OS | Windows 10 Version 22H2 (Build 19045.3271)
```

### Followed the steps to reproduce using https://github.com/brave/brave-core/pull/19144#issue-1788775220

## Confirmed both the `mtm_cid` and `pk_cid` parameters were dropped from the page load, by an internal redirect

![image](https://github.com/brave/brave-browser/assets/387249/aa15356b-95b8-4fd4-836e-e47d2fe32774)
