### ISSUE TITLE
Allow selecting existing f1 address as recipient when sending FEVM tokens

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#31101]
Root issue https://github.com/brave/brave-browser/issues/30400
When Filecoin EVM is selected recipient list should include existing filecoin accounts

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.58.108 Chromium: 116.0.5845.114 (Official Build) beta (64-bit)
-- | --
Revision | f08ffbe3ce0069ad8207b9d2d7dee38afcccc1b9
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#18966](https://github.com/brave/brave-core/pull/18966)
- Verified FVM accounts are only listed in receiving address when FEVM tokens are selected in Send screen
- Verified FEVM -> FVM transactions work on mainnet and testnet as well

https://github.com/brave/brave-browser/assets/17010094/5055c3d5-d644-43e0-9b13-42e219d2fa5b
