### ISSUE TITLE
Enable "HTTPS by Default" by default

### ISSUE THREAD

**Issue by arthuredelstein** [brave/brave-browser#31104]
Now that we have completed the rollout of HTTPS by Default using griffin, we can set the feature to be enabled by default.

**Comment by mihaiplesa** [comment]
@arthuredelstein 
```
Please specify either QA/Yes or QA/No.
If you specify QA/Yes, then please also specify a test plan.
Please also specify either release-notes/include or release-notes/exclude.
For more information see https://github.com/brave/brave-browser/wiki/Missing-release-note-labels and
https://github.com/brave/brave-browser/wiki/Missing-QA-labels
```

**Comment by arthuredelstein** [comment]
QA testing: Once we remove the griffin study for Nightly or Release in https://github.com/brave/brave-variations, then testing can confirm that the Https by Default feature remains enabled. See tests in https://github.com/brave/brave-browser/issues/27141. I will post here when the griffin studies are removed.

**Comment by LaurenWags** [comment]
@arthuredelstein sounds like this one is `release-notes/exclude`. Will add that label.

Also, going to add `QA/Blocked` label until you post here since we're dependent upon the removal of the griffin studies. Is there a planned timeline for that?

It seems like we can spot check that the feature is enabled by default, doesn't seem necessary to run through all the same tests again. Let me know if that's an accurate assessment (I believe that's what we normally do when we switch from a griffin study to enabling by default via code). cc @kjozwiak to confirm that.

**Comment by arthuredelstein** [comment]
> @arthuredelstein sounds like this one is `release-notes/exclude`. Will add that label.

Great, thanks.

> Also, going to add `QA/Blocked` label until you post here since we're dependent upon the removal of the griffin studies. Is there a planned timeline for that?

Makes sense. I expect to remove griffin studies for Nightly shortly, and then for Release once the patch here has reached Release.

> It seems like we can spot check that the feature is enabled by default, doesn't seem necessary to run through all the same tests again. Let me know if that's an accurate assessment (I believe that's what we normally do when we switch from a griffin study to enabling by default via code). cc @kjozwiak to confirm that.

Yes, a sport check sounds good.

**Comment by LaurenWags** [comment]
@brave/qa-team to test this without waiting for the griffin studies to be removed, we can launch a clean profile and ensure no griffin studies are listed under brave://version.

Then can spot check this feature is available under shields panel and brave://settings. Once the griffin study is removed (@arthuredelstein to create PRs and to post here when this is complete) we can check that brave://version after restart and ensure the study is not being listed.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 



Brave | 1.58.92 Chromium: 116.0.5845.96 (Official Build) beta (x86_64)
-- | --
Revision | 8e2896b3a1286e25b85ff82ab828fb7a807e1e26
OS | macOS Version 11.7.9 (Build 20G1426)



### Griffin-study removal - `PENDING`
<details>

1. installed `1.5`
2. launched Brave
3. restarted
4. opened `brave://version`
5. confirmed I saw `BraveHttpsByDefaultRolloutStudy:Enabled`
6. opened `brave://flags/#https-by-default`
7. confirmed I saw `Default`

`brave://version` | `brave://flags`
------------------|---------------




</details>

---

### Default - `Upgrade connections to HTTPS`, `Standard` - `PENDING`
<details>

1. installed `1.50.106`
8. launched Brave
9. confirmed `Upgrade connections to HTTPS` is set to `Standard` in `brave://settings/shields`
10. loaded `http://insecure.arthuredelstein.net`
11. loaded `http://http.badssl.com`
12. loaded `http://upgradeable.arthuredelstein.net`
13. opened a `New Private Window with Tor` and loaded each of the above

`default` | `insecure.arthuredelstein.net` | `http.badssl.com` | `upgradable.arthuredelstein.net`
----------|-------------------------------|--------------------|---------------------------------


#### Tor

`insecure.arthuredelstein.net` | `http.badssl.com` | `upgradable.arthuredelstein.net`
-------------------------------|-------------------|----------------------------------



</details>

### `Upgrade connections to HTTPS`, `Strict` - `PENDING`
<details>

1. installed `1.50.106`
2. launched Brave
3. changed `Upgrade connections to HTTPS` to `Strict` in `brave://settings/shields`
4. loaded `http://insecure.arthuredelstein.net`
5. loaded `http://http.badssl.com`
7. loaded `http://upgradeable.arthuredelstein.net`
8. opened a `New Private Window with Tor` and loaded each of the above

`Upgrade connections, Strict` | `insecure.arthuredelstein.net` | `http.badssl.com` | `upgradable.arthuredelstein.net`
----------|-------------------------------|--------------------|---------------------------------







#### Tor

`insecure.arthuredelstein.net` | `http.badssl.com` | `upgradable.arthuredelstein.net`
-------------------------------|-------------------|----------------------------------



</details>

### `Upgrade connections to HTTPS`, `Disabled` - `PENDING`
<details>

1. installed `1.50.106`
2. launched Brave
3. changed `Upgrade connections to HTTPS` to `Disabled` in `brave://settings/shields`
4. loaded `http://insecure.arthuredelstein.net`
5. loaded `http://http.badssl.com`
6. loaded `http://upgradeable.arthuredelstein.net`
7. opened a `New Private Window with Tor` and loaded each of the above

`Upgrade connections, Disabled` | `insecure.arthuredelstein.net` | `http.badssl.com` | `upgradable.arthuredelstein.net`
-------------------------------|-------------------------------|--------------------|---------------------------------








#### Tor

`insecure.arthuredelstein.net` | `http.badssl.com` | `upgradable.arthuredelstein.net`
-------------------------------|-------------------|----------------------------------




</details>

## `Between-window-type preferences` - `PENDING`
<details>

### Regular --> `Private` window, _upgrade_ - `PENDING`
<details>

- loaded `http://insecure.arthuredelstein.net` in a normal window
- clicked on the `Shields` icon
- changed `Upgrade connections to HTTPS` in the `Advanced controls` view to `Only connect with HTTPS`
- loaded `http://insecure.arthuredelstein.net` in a Private (not Tor) window
- clicked on the `Shields` icon
- confirmed I saw the `The connection to insecure.arthuredelstein.net is not secure` interstitial warning
- clicked through via `Continue to site`
- confirmed it loaded, printing `Hello`

example | example | example | example
---------|----------|---------|----------





</details>

### Regular --> `Private` window, _downgrade_: - `PENDING`
<details>

- loaded `http://insecure.arthuredelstein.net` in a normal window
- clicked on the `Shields` icon
- changed `Upgrade connections to HTTPS` in the `Advanced controls` view to `Don't upgrade HTTP connections`
- loaded `http://insecure.arthuredelstein.net` in a Private (not Tor) window
- clicked on the `Shields` icon
- confirmed it loaded, printing `Hello`


normal window | Private window
----------------|----------------




</details>

</details>

### Shields down - `PENDING`

<details>

1. installed `1.50.106`
2. launched Brave
3. loaded `http://insecure.arthuredelstein.net`
4. loaded `http://http.badssl.com`
5. loaded `http://upgradeable.arthuredelstein.net`
6. clicked on the `Brave Shields` icon in the URL bar
7. toggled each of the above loaded sites' Shields to `DOWN`
8. opened a `New Private Window with Tor` and loaded each of the above

`Global Shields pref` | `insecure.arthuredelstein.net` | `http.badssl.com` | `upgradable.arthuredelstein.net`
-------------------------------|-------------------------------|--------------------|---------------------------------













#### Tor

`insecure.arthuredelstein.net` | `http.badssl.com` | `upgradable.arthuredelstein.net`
-------------------------------|-------------------|----------------------------------



</details>

### (Pref) Migrations - `PENDING`
<details>

#### defaults - `PENDING`
<details>

1. installed `1.49.128`
2. confirmed default of `Always use secure connections` set to `Off` in `brave://settings/security`
3. upgraded to `1.50.106` by renaming `Brave-Browser` profile to `Brave-Browser-Beta`
4. launched Brave
5. confirmed via `brave://settings/shields` that `Upgrade connections to HTTPS` is set to `Standard`

`1.49.128` | `1.50.106`
-----------|----------




</details>

#### `Always use secure connections` set to `On` - `PENDING`
<details>

1. installed `1.49.128`
2. clicked to toggle `Always use secure connections` set to `On` in `brave://settings/security`
3. upgraded to `1.50.106` by renaming `Brave-Browser` profile to `Brave-Browser-Beta`
4. launched Brave
5. confirmed via `brave://settings/shields` that `Upgrade connections to HTTPS` is set to `Strict`

`1.49.128` | `1.50.106`
-----------|----------



</details>


</details>

**Comment by kjozwiak** [comment]
> It seems like we can spot check that the feature is enabled by default, doesn't seem necessary to run through all the same tests again. Let me know if that's an accurate assessment (I believe that's what we normally do when we switch from a griffin study to enabling by default via code). cc @kjozwiak to confirm that.

Apologies for the delayed response but looks like @arthuredelstein already answered as well. Agreed, a quick spot check is basically all we really need to do. All we're doing is enabling the feature by default rather than requiring the restart to apply the study from Griffin.
