### ISSUE TITLE
improve the "BETA" tag under brave://sync

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#3110]
## Description 

We decided to add a `Beta` string into `brave://sync` but due to time constraints and limited resources as folks were on PTO, we added some text rather than making it look like it did under `muon`. The current fix looks a bit sloppy and needs to be improved.

## Steps to Reproduce

   1. open `0.59.30 Chromium: 72.0.3626.71`
   2. visit `brave://sync`

## Actual result:

<img width="875" alt="screen shot 2019-01-25 at 4 03 36 pm" src="https://user-images.githubusercontent.com/2602313/51772755-cdc8b700-20ba-11e9-9733-0afa292d8e84.png">

## Expected result:

<img width="306" alt="screen shot 2019-01-25 at 4 09 39 pm" src="https://user-images.githubusercontent.com/2602313/51773074-a4f4f180-20bb-11e9-8717-cb083b64cc7f.png">

The above or something similar that looks better.

## Reproduces how often: 

100% reproducible using the above STR.

## Brave version (brave://version info)

Brave | 0.59.30 Chromium: 72.0.3626.71 (Official Build) (64-bit)
-- | --
Revision | f52ccad2a6a3c65fc9e0c591a517ceab1198dac0-refs/branch-heads/3626@{#763}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

Reproducible on all channels that have `Sync` enabled by default

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

CCing @rebron & @bsclifton

**Comment by rossmoody** [comment]
After talking with @rebron yesterday in the office, the consensus is to not add the `beta` label to this and the change that created the above `(beta)` string has been reverted. So it will just read `Sync Setup`.
