### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by MilkFullCream** [brave/brave-browser#31102]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.52.126 Chromium: 114.0.5735.133
Operating System: Windows NT 10.0.22621

URL (if applicable) where crash occurred: 

Can you reproduce this crash? yes

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. open brave://flags/
2. search " Chrome Refresh 2023 " , and " Chrome WebUI Refresh 2023 "
3. make them enable and restart brave
4. open the 3 dot and brave crash. 

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/b3010400-7c09-400a-0000-000000000000

**Comment by simonhong** [comment]
Closed as duplicated with https://github.com/brave/brave-browser/issues/30499
