### ISSUE TITLE
document.fonts.check() can be used for fingerprinting due to Chromium bug

### ISSUE THREAD

**Issue by simevidas** [brave/brave-browser#31108]
## Description 

The `document.fonts.check` method is defined to return `true` for all non-web fonts, but there is a bug in Chromium where the browser actually checks if the font is available locally.

https://bugs.chromium.org/p/chromium/issues/detail?id=1416842

## Steps to Reproduce

   1. Open the browser’s console
   2. Run `document.fonts.check('16px Menlo')` and `document.fonts.check('16px Calibri')`

## Actual result:

Brave will return `true` or `false` depending on whether the given font is available on your device.

<img width="688" alt="Screenshot 2023-06-16 at 20 18 00" src="https://github.com/brave/brave-browser/assets/716405/79b336f3-61f0-4a68-beff-67f1047f09ea">

## Expected result:

The browser should return `true` for all non-web fonts.

## Reproduces how often: 

Easily reproduced

## Desktop Brave version:

1.52.126 Chromium: 114.0.5735.133 (Official Build) (x86_64)

**Comment by diracdeltas** [comment]
Closing as this seems to be fixed in Chromium
