### ISSUE TITLE
Solana connect prompt should provide a list of available accounts for users to choose

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#31109]
This report came from @mrose17 when integrating wallet with Brave Talk

Currently we only show the "selected" account despite the user has more than one SOL accounts
![Screen Shot 2023-06-16 at 09 28 15](https://github.com/brave/brave-browser/assets/11330831/7872e69f-d973-4782-ba20-1382cd4e557f)

We should let user to choose which SOL account to connect and the account will be selected afterward if the user approve the request.
Note that the user can only choose "ONE" account in the list due to SOL dapp limitation

cc @jamesmudgett @Douglashdaniel

**Comment by mrose17** [comment]
Thank you!

**Comment by darkdh** [comment]
This is more of a backend issue, we only propagate "selected" account to the permission system and then to UI for the user to decide. Instead, all SOL accounts should be passed and in `SolanaProviderImpl::OnConnect` setting the granted account as selected one if it is not selected yet.

**Comment by srirambv** [comment]
Verification passed on  

Brave | 1.58.105 Chromium: 116.0.5845.114 (Official Build) beta (64-bit)
-- | --
Revision | 5a895596bcd7fcd930dab0714ea5cfa86c5aa0a7
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#19200](https://github.com/brave/brave-core/pull/19200)
- Verified solana connect prompt shows all available Solana accounts when connecting to a Dapp

https://github.com/brave/brave-browser/assets/17010094/045fd8cc-a50a-4137-9170-d75b1c1d57d9
