### ISSUE TITLE
[ads] Add "Sponsored" text to custom notification ad

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#31118]

**Comment by jenn-rhim** [comment]
This is not for all ads. So I'd say rather than saying 'Change', it'd be 'Add a label'. 

We'd need a table that would sort the ads.

**Comment by aseren** [comment]
@jenn-rhim, labels are created as vector icons. Could you please provide new icons with `Sponsored` text for light and dark modes?

Current icons are the following:
* https://github.com/brave/brave-core/blob/master/app/vector_icons/brave_ads_light_mode_info_button.icon
* https://github.com/brave/brave-core/blob/master/app/vector_icons/brave_ads_dark_mode_info_button.icon

**Comment by tmancey** [comment]
Closing as will be resolved by https://github.com/brave/brave-browser/issues/31119
