### ISSUE TITLE
Fix/replace browser onboarding metric

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#31116]
The existing browser onboarding metric (`Brave.Welcome.InteractionStatus`) has been broken since the rollout of the new onboarding flow. Replace it with a new metric.

What was the last screen that you viewed during the browser onboarding process?
`Brave.Welcome.InteractionStatus.2`

0. Only viewed the welcome screen, performed no action
1. Viewed the profile import screen
2. Viewed the diagnostic/analytics consent screen
3. Finished the onboarding process

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.58.91 Chromium: 116.0.5845.96 (Official Build) beta (64-bit)
-- | --
Revision | 620fa9c0307b294dd6e7c6b0976bc1f93fecf369
OS | Windows 10 Version 22H2 (Build 19045.3324)
```
