### ISSUE TITLE
Brave Rewards close icons should be consistent and visible

### ISSUE THREAD

**Issue by rossmoody** [brave/brave-browser#3111]
After a meeting with @mandar-brave, there was a small initiative put in place to refresh the `X` close icons within Brave Rewards panels to ensure they are consistent and discoverable.  The strokes of the `X` icons were rendering a little thin and becoming lost in the UI in certain instances.

The following screens were revised with before on the left and after on the right. 
![close](https://user-images.githubusercontent.com/29072694/51773207-f47af380-20a2-11e9-9dd3-13838f7f2fd6.png)

**Comment by NejcZdovc** [comment]
@rossmoody can this one be closed, based on the fact that new icons were added?

**Comment by rossmoody** [comment]
I think so!
