### ISSUE TITLE
Rewards onboarding polishes: Remove default focus ring from "Start using Rewards" due to auto-focus

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#31112]
```[tasklist]
### Tasks
- [ ] Remove auto-focus when opening the Rewards panel
```

![image](https://github.com/brave/brave-browser/assets/11497541/4333c7f4-9080-4791-b4b5-10262491a528)

Brave | 1.54.65 Chromium: 114.0.5735.133 (Official Build) nightly (x86_64)
-- | --
Revision | fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}
OS | macOS Version 13.4 (Build 22F66)

Put QA/No because this should just be viewed as part of the Rewards onboarding testing, and any version higher than when this fix goes in should be fine.

**Comment by kjozwiak** [comment]
The above requires `1.54.85` or higher for `1.54.x` verification 👍
