### ISSUE TITLE
import of passwords or cookies from muon or chrome fails

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#3112]
## Description 
Importing passwords and/or cookies from muon or Chrome fails. It seems this broke with CR72. 

0.58.8 Beta (on CR71) --> Import of passwords/cookies works
0.59.9 Beta (on CR72) --> Import of passwords/cookies fails

Additionally, when importing all data (history, payments info, tabs, etc) from muon, once the password import failed, nothing else was imported. Unsure if it should have continued to import remaining items.

## Steps to Reproduce

1. have a profile set up on muon with at least passwords and cookies (mine has everything - bookmarks, payment data, etc)
2. Launch 0.59.30 with a clean profile.
3. Attempt to import everything. Note - I was prompted for my computer password since I’m on macOS and yes, I did provide it.

## Actual result:
Passwords (and everything after it in the import list) is not imported.
Additionally, you can clear the profile and repeat STR (uncheck passwords this time) and see that Cookies (and everything after it in the list) is not imported.
Same happens for importing from Chrome.

## Expected result:
Passwords and Cookies should be imported from both muon and Chrome.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.59.30 Chromium: 72.0.3626.71 (Official Build) (64-bit)
-- | --
Revision | f52ccad2a6a3c65fc9e0c591a517ceab1198dac0-refs/branch-heads/3626@{#763}
OS | Mac OS X

But occurs on all CR72 instances of Brave

### Reproducible on current release: - does not reproduce on 0.58.21
- Does it reproduce on brave-browser dev/beta builds? yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information
Reproduced by @kjozwiak on macOS

**Comment by kjozwiak** [comment]
Looks like this is a macOS specific issue. As @LaurenWags mentioned above, I could reproduce this easily on `macOS 10.14.2 x64` using `0.59.30 Chromium: 72.0.3626.71` but can't reproduce it on my `Win 10 x64` machine. Example:

![importing](https://user-images.githubusercontent.com/2602313/51775903-40d72b00-20c5-11e9-90c7-3ab19b063bee.gif)

**Comment by kjozwiak** [comment]
@btlechowski mind giving this a go on your Win 7 machine to see if you can reproduce? Seems to be working on Win on my end. Would be nice to get another set of eyes on Win 👍

**Comment by btlechowski** [comment]
@kjozwiak I was not able to reproduce it on 0.59.30 Windows 7 x64 and Windows 10 x64.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.2 x64` using the following build:

Brave | 0.59.31 Chromium: 72.0.3626.71 (Official Build) (64-bit)
-- | --
Revision | f52ccad2a6a3c65fc9e0c591a517ceab1198dac0-refs/branch-heads/3626@{#763}
OS | Mac OS X

Went through the following cases:

* logged into FB, Gmail, Comic Geeks, Fantasy PL under `muon` and imported into `0.59.x`
* logged into FB, Gmail, Comic Geeks, Fantasy PL under `Chrome` and imported into `0.59.x`
* ensured that I was still logged into and that the passwords were also imported
