### ISSUE TITLE
Unchecked NFTs should be shown under Hidden NFT

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#31134]
## Description 

Unchecked NFTs should be shown under Hidden NFT

## Steps to Reproduce

   1. Add an NFT to collection
   2. Go to portfolio and search for NFT
   3. Unchecked the visible checkbox
   4. Go to NFT tab and select `Hidden`
   5. NFT removed from step 3 isn't shown under hidden

## Actual result:

Unchecked NFTs should be shown under Hidden NFT

## Expected result:
Should move visible NFT to hidden tab if the NFT is unchecked from visible asset list

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.53.94 Chromium: 114.0.5735.133 (Official Build) beta (64-bit)
-- | --
Revision | `fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}`
OS | Windows 11 Version 22H2 (Build 22621.1848)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @kleantzogu @muliswilliam

**Comment by josheleonard** [comment]
Closing since this is no longer valid. NFTs are not listed in the edit visible assets modal anymore
