### ISSUE TITLE
Support multihash enclave attestation user_data in STAR P3A

### ISSUE THREAD

**Issue by rillian** [brave/brave-browser#31131]
## Description 

Per https://github.com/brave/nitriding-daemon/issues/23 we want to change the encoding scheme for the TLS certificate fingerprint returned by the STAR randomness server in response to remote attestation requests to something easier to parse reliably.

To support transition to the new scheme:
1. Add support for the scheme alongside the old
2. Once client support is deployed in release, switch the star-randsrv deployment to the new scheme
3. When that is confirmed working, remove client support for the old scheme

This means we'll stop receiving STAR (constellation) P3A reports from older clients. However, rollout is in early stages with the 1.52.x releases under Griffin control, so I don't expect this to be a serious concern.

**Comment by LaurenWags** [comment]
changing to `release-notes/exclude` per discussion with @rebron @kjozwiak
