### ISSUE TITLE
Make vertical tab expanded even when mouse is on the resize area

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#31135]
Internal thread: https://bravesoftware.slack.com/archives/C042KL922P3/p1686602569958969

When a window is flush to the left and we throw mouse to the side, vertical tab won't be expanded even "Float on mousehover" is enabled. Even when mouse cursor is on the resize area, we should trigger the action.

## Steps to reproduce
* Maximize the browser window - if you're using multiple monitors, please make sure that the browser window is on the the left most monitor
* Enable vertical tab and "Float on mouehover"
* Move mouse to the left top of montior
* Move mouse down along the left edge.
* Check if vertical tab is opened when mouse cursor enters the vertical tab area

### Expected
* Vertical tab should be expanded when some amount of time passes.

### Actual
* It doesn't expand

**Comment by LaurenWags** [comment]
Verified passed with

```
Brave | 1.57.18 Chromium: 115.0.5790.98 (Official Build) beta (x86_64)
-- | --
Revision | d515871a6c6df7d2843e755c8b7dda9b744f26d6
OS | macOS Version 13.4.1 (a) (Build 22F770820b)
```

Reproduced the issue using `1.56.9 Chromium: 115.0.5790.98`. Note, it was helpful when reproducing to have my browser window aligned on the very left most edge of my left monitor. Just having the browser window display in the left most monitor wasn't quite enough.
Verified test plan from https://github.com/brave/brave-browser/issues/31135#issue-1762945172.
Confirmed vertical tab is opened when mouse cursor enters the vertical tab area.
