### ISSUE TITLE
Allow pinning the pinned tabs container in vertical tabs mode

### ISSUE THREAD

**Issue by morsagmon** [brave/brave-browser#31143]
This is a feature request for the Brave browser.

When in vertical-tabs mode, and the tab list is long enough to be scrollable, the pinned tabs at the top are scrolled away as the user scrolls down.
It would be very helpful if we can fix the pinned tabs container to be decoupled from the tabs list scroll area.
The motivation here is that pinned tabs are very popular and often visited, and it is annoying to have to scroll up to jump to a pinned tab evey time, and then scroll back down searching for the last worked-on tab.

**Comment by Coffeeling** [comment]
Pinned tabs stay visible on Nightly.

**Comment by morsagmon** [comment]
> Pinned tabs stay visible on Nightly.

Sounds good. This means we will have this soon in the production release. Correct?
