### ISSUE TITLE
Purple "IPFS badge" displays for non-"IPFS" sites

### ISSUE THREAD

**Issue by BigLep** [brave/brave-browser#31145]
## Description 

Purple "IPFS badge" displays for non-"IPFS" sites.

Example: https://github.com/ipfs/github
<img width="421" alt="image" src="https://github.com/brave/brave-browser/assets/85411/8c305e29-216a-478a-bd42-073bde666a6a">

## Steps to Reproduce

   1. Have IPFS enabled
   2. Visit a site that has /ipfs at the root path like github.com/ipfs that isn't hosted by an IPFS HTTP gateway returning the `x-ipfs-path` header and doesn't have DNSLink setup.
  
## Actual result:
See above

## Expected result:
No purple badge

## Reproduces how often: 
Every time

## Brave version (brave://version info)
Brave | 1.50.121 Chromium: 112.0.5615.138 (Official Build) (arm64)
-- | --
Revision | 2258f2fcaeb07bc95c992b7ca47f0b43ead9865c-refs/branch-heads/5615@{#1282}
OS | macOS Version 13.4 (Build 22F66)
JavaScript | V8 11.2.214.14
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Command Line | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser --disable-domain-reliability --enable-dom-distiller --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --variations-insecure-server-url=https://variations.brave.com/seed --flag-switches-begin --flag-switches-end --component-updater=url-source=https://go-updater.brave.com/extensions
Executable Path | /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
Profile Path | /Users/sal/Library/Application Support/BraveSoftware/Brave-Browser/Profile 2
Linker | lld
Active Variations | AllowCertainClientHintsStudy:EnabledBraveAdblockCookieListOptInReleaseStudy:EnabledBraveAdblockMobileNotificationsListDefault:EnabledBraveAds.AdServingStudy:DefaultAdNotificationsPerHour=10/MaximumAdNotificationsPerDay=100/MaximumInlineContentAdsPerHour=6/MaximumInlineContentAdsPerDay=20/AdServingVersion=2BraveAutoTranslateStudy:AutoTranslateDisabledBraveCleanupSessionCookiesOnSessionRestore:DisabledBraveDebounceStudy:EnabledBraveGoogleSignInPermissionStudy:EnabledBraveHttpsByDefaultRolloutStudy:EnabledBraveRewardsWebUiPanelStudy:EnabledBraveScreenFingerprintingBlockerStudy:EnabledCrossPlatformVPNStudy:EnabledDefault1pBlockingStudy:DisabledDisableReduceLanguage:EnabledEphemeralStorageStudy:EnabledFirstPartyEphemeralDomainBlockStudy:EnabledForceDisableBlinkFeatures:EnabledMacCoreLocationBackendStudy:EnabledPartitionBlinkMemoryCacheStudy:EnabledPartitionConnectionsByNetworkIsolationKeyStudy:EnabledPermissionLifetimeReleaseStudy:EnabledSpeedreaderReleaseStudy:EnabledUserActivityStudy:TriggersWhatsNewStudy:Enabled

## Version/Channel Information:

- Can you reproduce this issue with the current release?  Yes
- Can you reproduce this issue with the beta channel?  Haven't tried
- Can you reproduce this issue with the nightly channel? Haven't tried 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  No
- Does the issue resolve itself when disabling Brave Rewards?  No
- Is the issue reproducible on the latest version of Chrome?  n/a

## Miscellaneous Information:

I searched for existing issues about this by looking at:
https://github.com/brave/brave-browser/issues?q=is%3Aissue+ipfs+is%3Aopen
https://github.com/brave/brave-browser/issues?page=3&q=is%3Aissue+ipfs+badge

I assume there is logic from https://www.npmjs.com/package/is-ipfs related to https://docs.ipfs.tech/how-to/address-ipfs-on-web/ that hasn't been properly ported over.

**Comment by BigLep** [comment]
Looking at the release checklist ([example](https://github.com/brave/brave-browser/issues/29773)), I see there are various positive tests affirming the IPFS badge's presence.  It would probably be good to add a negative case (asserting that the badge isn't present).

**Comment by lidel** [comment]
@cypt4 i think this may be a regression in URL/DNSLink processing pipeline, perhaps due to recent refactors? 
You can reference  https://github.com/ipfs/ipfs-docs/pull/1295 → https://github.com/ipfs/ipfs-docs/blob/feat/how-to-implement-support-in-a-web-browser.md/docs/how-to/detect-ipfs-on-web.md or ask me on Slack if needed.

I agree with @BigLep, we need QA tests for this, filled https://github.com/brave/qa-resources/pull/526 to close the gap.

**Comment by kjozwiak** [comment]
The above requires `1.57.45` or higher for `1.57.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.57.45 Chromium: 116.0.5845.82 (Official Build) (64-bit)
-- | --
Revision | c43241b101a636729252df90d1a1a7b72f2a9f94
OS | Linux

- Verified steps from issue description
- Verified visiting a site that has `/ipfs` at the root path that isn't hosted on IPFS doesn't show the IPFS badge

https://github.com/brave/brave-browser/assets/17010094/10e51419-535e-4fd4-b074-1e2d53e2aa36
