### ISSUE TITLE
Vertical tabs Expand-Collapse icon should update when switching modes (again).

### ISSUE THREAD

**Issue by Emi-TheDhamphirInLoveUnderTheFrozenStar** [brave/brave-browser#31149]
## Description 

When clicking on the button to change from collapse-to-expand and vice versa, the icon stays the same, before the icon would update when changing modes, but some update that broke it some months ago.

## Actual result:

![brave_2023-06-19_16-43-46](https://github.com/brave/brave-browser/assets/122518587/fd05ac04-2f69-43e3-9f57-32fec8458b6e)

## Expected result (with the new/updated icon):

![Icon](https://user-images.githubusercontent.com/4733304/218655687-270699ef-c2f5-4fc2-b9a8-187d3f204d24.png)

I found This video showing the correct behavior in an old PR https://github.com/brave/brave-core/pull/17483.

https://github.com/brave/brave-browser/assets/122518587/26ca2009-325e-450d-8c82-3541edd9803c

## Brave version (brave://version info)

1.54.71 Chromium: 114.0.5735.133 (Official Build) nightly (64-bit)

**Comment by antonok-edm** [comment]
cc @sangwoo108

**Comment by sangwoo108** [comment]
Thanks @Emi-TheDhamphirInLoveUnderTheFrozenStar . This slipped out of my mind. I opened a PR right away.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.58.88 Chromium: 116.0.5845.82 (Official Build) beta (64-bit)
-- | --
Revision | acf16e35d5897fd4bf9b1b5a93b56aff2ed64bba
OS | Windows 11 Version 22H2 (Build 22621.2134)
```

Reproduced the issue in 1.56.20 using above STR.

https://github.com/brave/brave-browser/assets/98358127/ccc5dc71-8572-46a6-a780-df3f70520c3e


1. Install 1.58.88
2. launched Brave
3. enabled vertical tabs via tab context menu 
4. expanded vertical tab strip by clicking the Expand/Collapse button

#### Confirmed Expand/Collapse button is highlighted even after mouse is released in Expanded mode


https://github.com/brave/brave-browser/assets/98358127/7b531c83-57b2-47dc-b308-41ebd281fa5f
