### ISSUE TITLE
[Android] External deep link behaviour

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#31148]
- [x] Deep link behaviour for already installed application
In this scenario, we assume that user has already gone through the onboarding. so we don not need to do anything for existing users.
- [x] Deep link behaviour for fresh install
In this scenario, we need to show app onboarding with `Help make Brave better` and `Set as default browser` pages. and redirect user directly to feature specific modals. we need to delay highlighting the user bar for later sessions.

**Comment by Uni-verse** [comment]
In progress on Android ARM

**Comment by Uni-verse** [comment]
Verified on Samsung Galaxy Tab S7 using version(s):

```
Brave	1.58.117 Chromium: 116.0.5845.180 (Official Build) (64-bit) 
Revision	99255ad6abf2fa399c063683c051f973e1f5c0af
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
Using Test Plan in https://github.com/brave/brave-core/pull/19107#issue-1781185541

_VPN_

- Ensured deep link for VPN will take user to the app store brave page and installing/opening the app will take user to VPN subscription screen.
- Ensured that user is presented with default browser + P3A onboarding screens.
- Ensured that when app is installed, using the deep link will just open the app.

_Playlist_

- Ensured deep link for Playlist will take user to the play store brave download page and installing/opening the app will take user to playlist screens.
- Ensured that user is presented with default browser + P3A onboarding screens.
- Ensured that when app is installed, using the deep link will just open the app.

<table><tr><td>VPN</td><td>Playlist</td></tr>

<tr><td>

https://github.com/brave/brave-browser/assets/17885425/376ce5bf-ee1d-4b60-afbd-1b1288b745e0

</td><td>

https://github.com/brave/brave-browser/assets/17885425/ae85c2fa-e38a-4586-b2c3-bc1888b6bdf7

</td></tr></table>
