### ISSUE TITLE
Fix action color in dark mode

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#31141]
## Actual result 
![Screenshot from 2023-06-19 17-21-38](https://github.com/brave/brave-browser/assets/11755381/e0133aa4-f411-49f4-832d-2553d690a5a7)

## Expected result
![Screenshot from 2023-06-19 17-13-22](https://github.com/brave/brave-browser/assets/11755381/aaf68a75-e620-4e90-af02-b5d87337bea4)

### Additional information

Same for:
- Add NFT action

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.58.114 x64 Beta build
- Verified steps from issue description
- Verified `Add custom asset` button is now properly visible in dark theme

https://github.com/brave/brave-browser/assets/17010094/6a80572a-bb62-4ff5-bfbc-db618b6a24aa
