### ISSUE TITLE
Unable to submit Solana transactions

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#31140]
## Description 

Unable to submit Solana transactions

## Steps to Reproduce

   1. Install 1.54.94 build
   2. Initiate a Solana send transaction 
   3. Fails to submit the transaction with error

## Actual result:

![brave_YQt1AoiSuY](https://github.com/brave/brave-browser/assets/17010094/8e6541c3-6a77-4a84-9293-3db3a46f4316)

## Expected result:
Successfully submit Solana transactions

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.53.94 Chromium: 114.0.5735.133 (Official Build) beta (64-bit)
-- | --
Revision | `fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}`
OS | Windows 11 Version 22H2 (Build 22621.1848)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Not checked

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:
cc: @onyb @supermassive

**Comment by kjozwiak** [comment]
The above requires `1.53.106` or higher for `1.53.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.53.107 Chromium: 115.0.5790.40 (Official Build) (64-bit)
-- | --
Revision | `071c9ddea889c3c7887daf4eac13fed72d4fff62-refs/branch-heads/5790@{#979}`
OS | Windows 11 Version 22H2 (Build 22621.1848)

- Verified steps from issue description
- Verified able to submit Solana/Filecoin transactions

https://github.com/brave/brave-browser/assets/17010094/3c59329d-3689-4c95-a53f-a734d492f3ef
