### ISSUE TITLE
[Android] Browser Address Bar not showing Correct Route for Wallet

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#31153]
## Description 

The Browsers `Address Bar` is not showing the correct route for the `Wallet`.

## Steps to Reproduce

   1. Open the `Brave Wallet`
   2. Click through the `Navigation`
   3. The `Address Bar` is not reflecting the correct routes.

## Actual result:

https://github.com/brave/brave-browser/assets/40611140/82f5a6b6-f5e3-4b86-82c1-3abd1fe979db

## Expected result:
The `Address bar` should reflect the correct route for whichever page the `Wallet` is on.

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by Douglashdaniel** [comment]
Reopened because seems to be an issue for `Linux` and `Android`

**Comment by simoarpe** [comment]
Link to Slack discussion: https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1699017339052679

**Comment by yrliou** [comment]
I wasn't able to reproduce on desktop, and it looks it wouldn't have this problem to me from code perspective, so change this to Android only issue for now.
We can open a new one if we do see it on desktop later.
