### ISSUE TITLE
Follow up to #30289: Ads are not  shown for ad with target url `brave://settings/?search=` 

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#31155]
Follow up to #30289

Ads are not shown

## Steps to Reproduce

1. Clean profile
1. Use ads catalog that has ad with `chrome://settings/?search=ipfs` or `brave://settings/?search=ipfs`
1. Enable rewards and ads
1. Trigger the ad with `chrome://settings/?search=ipfs` or `brave://settings/?search=ipfs`

## Actual result:

Ad is not shown

## Expected result:
Ad is shown

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.53.99 Chromium: 114.0.5735.133 (Official Build) beta (64-bit) 
-- | --
Revision | fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}
OS | Ubuntu 18.04 LTS

cc @tmancey @aseren

**Comment by tmancey** [comment]
@btlechowski by design we only support `chrome://settings/search?search=ipfs` or `brave://settings/search?search=ipfs`
