### ISSUE TITLE
Can't log into Plex with Google

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#3115]
## Description 
Cannot use google to log into app.plex.tv

## Steps to Reproduce
1. Go to app.plex.tx

## Actual result:
Option to log in with Google is disabled

## Expected result:
User is able to authenticate via their Google account

## Reproduces how often: 
Always

## Brave version (brave://version info)
0.58.21

### Reproducible on current release:
Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? Yes
- Is the issue reproducible on the latest version of Chrome? No

### Additional Information
User needs to _allow all cookies_ to proceed.

![google-plex-login](https://user-images.githubusercontent.com/815158/51783620-06d84a00-2102-11e9-8031-1c67a1ce219b.gif)

**Comment by mrzealot** [comment]
@jonathansampson Hope you don't mind, if I piggyback on this issue with my PR that addresses embedded Google logins: https://github.com/brave/brave-core/pull/1748
