### ISSUE TITLE
Shield settings icon missing in brave://settings/content page

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#31162]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/30200
Shield settings icon missing in brave://settings/content page
## Steps to Reproduce

   1. 
   2. 
   3. 

## Actual result:

![image](https://github.com/brave/brave-browser/assets/38657976/0a130286-a137-494c-9efc-cbbde33f917b)

## Expected result:
![image](https://github.com/brave/brave-browser/assets/38657976/ecbda1e7-be56-49ef-8875-0afce27b46cb)

## Reproduces how often: 

Easy
## Brave version (brave://version info)

<html>
<body>

Brave | 1.54.72 Chromium: 115.0.5790.32 (Official Build) nightly (64-bit)
-- | --
Revision | f9b78cf410ecd5b372310ef25a12ef456c77d90f-refs/branch-heads/5790@{#724}
OS | Windows 10 Version 22H2 (Build 19045.3086)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @emerick @rebron

**Comment by emerick** [comment]
I think this might be related to https://github.com/brave/brave-browser/issues/30189 rather than cr115, but please let me know. cc: @fallaciousreasoning @petemill

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.57.16 Chromium: 115.0.5790.98 (Official Build) beta (x86_64)
-- | --
Revision | d6c8a44fbe78ae6ee53d838307b4d17bec8de940
OS | macOS Version 11.7.8 (Build 20G1351)

### Steps:
1. installed `1.57.16`
2. launched Brave
3. opened `brave://settings/content`
4. double-checked the icon beneath `Shields status`

### Confirmed the icon appears in both `Light` and `Dark` themes

`Light` | `Dark`
-------|-------
<img width="1312" alt="Screen Shot 2023-07-18 at 2 58 46 PM" src="https://github.com/brave/brave-browser/assets/387249/5e32d4a7-831c-4225-8a4f-bfd407f50705"> | <img width="1312" alt="Screen Shot 2023-07-18 at 2 59 02 PM" src="https://github.com/brave/brave-browser/assets/387249/7ab2ecb8-79b2-4bcb-a47c-aa9899099dc0">
