### ISSUE TITLE
Icon is missing for `Protected content ID's` content settings

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#31160]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/30200
Icon is missing for `Protected content ID's` content settings
## Steps to Reproduce

   1. NA
  

## Actual result:

![image](https://github.com/brave/brave-browser/assets/38657976/cf0e77c7-003e-4129-a5cd-06f1a8c124f2)

## Expected result:
![image](https://github.com/brave/brave-browser/assets/38657976/14af033e-afd6-4219-bafe-bfd06768a9f2)

## Reproduces how often: 

Easy
## Brave version (brave://version info)

<html>
<body>

Brave | 1.54.72 Chromium: 115.0.5790.32 (Official Build) nightly (64-bit)
-- | --
Revision | f9b78cf410ecd5b372310ef25a12ef456c77d90f-refs/branch-heads/5790@{#724}
OS | Windows 10 Version 22H2 (Build 19045.3086)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @emerick @rebron @brave/qa-team

**Comment by emerick** [comment]
I think this might be related to https://github.com/brave/brave-browser/issues/18688 rather than cr115, but please let me know. cc: @fallaciousreasoning @petemill

**Comment by GeetaSarvadnya** [comment]
@emerick This issue is reproducible in nightly build with CR 114 so it's not related to CR 115 definately

**Comment by fallaciousreasoning** [comment]
Looks like this one was missed because it's windows only :laugh

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.57.18 Chromium: 115.0.5790.98 (Official Build) beta (64-bit)
-- | --
Revision | d515871a6c6df7d2843e755c8b7dda9b744f26d6
OS | Windows 10 Version 22H2 (Build 19045.3208)

```
![image](https://github.com/brave/brave-browser/assets/38657976/8fbd82c2-42fe-419b-8c4d-adb97116810e)
