### ISSUE TITLE
"Ad not served: Network connection not available" even though I have a connection

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#3116]
## "Ad not served: Network connection not available" even though I have a connection
Console log reported Ad was not served due to unavailable network connection, however I do have a network connection as I am able to visit any website

## Steps to Reproduce

   1. Enable rewards
   2. Visit a website
   3. Wait 15 seconds (without touching any input devices) for browser to change state to idle
   4. Move mouse so that browser changes state to un-idle

## Actual result:
Ad is not shown as it is reported in the console log that we have no network connection

## Expected result:
Ad should be shown if there is a network connection

## Reproduces how often: 
Intermittent issue

## Brave version (brave://version info)
issues/0.62.x commit hash d4066b8cf2e6ab1b60194e3bf67d08ed62d4b4fd

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? N/A

### Additional Information

This issue would occur if `content::GetNetworkConnectionTracker()->IsOffline()` is returning `false` if there is a valid network connection

**Comment by mrose17** [comment]
@tmancey - what does logging show?

**Comment by tmancey** [comment]
Logging shows "Ad not served: Network connection not available", and next time the issue occurs I will see if there are any further logs from core

**Comment by tmancey** [comment]
Speaking with @AlexeyBarabash they had a similar issue with Sync (https://github.com/brave/brave-core/pull/1643), therefore I would recommend we remove the network connection check and when an Ad is viewed in the new tab we allow the browser to show its error.

**Comment by jsecretan** [comment]
Yes, this sounds like a good solution, as really a network connection is not required to see ads, only to click through and the browser will already handle reasonably.

**Comment by srirambv** [comment]
Seeing this on Linux as well with a wired connection on desktop. 
```
[1:1:0701/111033.369779:INFO:ads_impl.cc(211)] Browser state changed to idle
[1:1:0701/111046.385684:INFO:ads_impl.cc(218)] Browser state changed to unidle
[1:1:0701/111046.388115:INFO:ads_impl.cc(1086)] Ad not served: Network connection not available
[1:1:0701/111046.388742:INFO:client.cc(267)] Successfully saved client state
```

**Comment by tmancey** [comment]
Closing as I have not seen this issue reoccur
