### ISSUE TITLE
Integrated support for the FilForwarder experience - enabling 0x/f410 addresses to send to f1,f2,f3 style addresses.

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#31169]
Reference https://github.com/lotus-web3/fil-forwarder-frontend
GLIF UX https://www.glif.io/?txtype=forward
FIL Forwarder UX https://github.com/lotus-web3/FilForwarder

**Comment by cypt4** [comment]
This is done in https://github.com/brave/brave-browser/issues/30400
