### ISSUE TITLE
Quora "formatting"/"Post" options are blocked by Shields

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#31175]
## Description 

When trying to ask a question and/or create a post on Quora, Brave's Shields block the actual `Post` button as well as the additional formatting options that appear in the editor:
(Shields up)
![image](https://github.com/brave/brave-browser/assets/3299098/7d3db6c7-2d22-402f-b14a-34252df3db4a)

(Shields down)
![image](https://github.com/brave/brave-browser/assets/3299098/434e8fbd-7852-4f64-9f42-794be1b71f7b)

## Steps to Reproduce

   1. Visit Quora
   2. Click `Ask a question` on top right
   3. Observe the editor

## Reproduces how often: 

Always

## Brave version (brave://version info)

v1.52.126

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

Original user thread:
https://community.brave.com/t/quora-there-is-a-formatting-bar-at-the-bottom-of-the-answer-form-brave-stopped-displaying-it/492937

**Comment by ryanbr** [comment]
@Brave-Matt  can you update Brave Ad Block Updater - Version: 1.0.340 in brave://components

**Comment by ryanbr** [comment]
Still an issue @Brave-Matt  ?

**Comment by arthuredelstein** [comment]
Looks to me like this is fixed.
