### ISSUE TITLE
Balance Updater causing Loading Skeletons in Portfolio

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#31177]
## Description 

The Balance Updater is causing `Loading Skeletons` on the `Portfolio` page 

## Steps to Reproduce

   1. Go to the `Portfolio` page
   2. Wait `60` seconds
   3. When balances are updated you will see loading skeleton.

## Actual result:

https://github.com/brave/brave-browser/assets/40611140/050eef00-d868-4c57-9e91-fdd5e42aec1f

## Expected result:
No need to show a `Loading Skeleton` when the `Wallet` refreshes balances in the background, it should just update.

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.57.24 Chromium: 115.0.5790.136 (Official Build) beta (64-bit)
-- | --
Revision | `8099932ede6f8d4624fbddf39d27abb3b340d8c9`
OS | Linux

- Verified steps from [brave/brave-core#18971](https://github.com/brave/brave-core/pull/18971)
- Verified no `Loading Skeletons` are shown price are refreshed after `60 seconds

---------------------

**Verification passed on**

Brave | 1.57.24 Chromium: 115.0.5790.136 (Official Build) beta (64-bit)
-- | --
Revision | `8099932ede6f8d4624fbddf39d27abb3b340d8c9`
OS | Windows 11 Version 22H2 (Build 22621.1992)

- Verified steps from [brave/brave-core#18971](https://github.com/brave/brave-core/pull/18971)
- Verified no `Loading Skeletons` are shown price are refreshed after `60 seconds

---------------------

**Verification passed on**

Brave | 1.57.24 Chromium: 115.0.5790.136 (Official Build) beta (arm64)
-- | --
Revision | `8099932ede6f8d4624fbddf39d27abb3b340d8c9`
OS | macOS Version 13.4.1 (c) (Build 22F770820d)

- Verified steps from [brave/brave-core#18971](https://github.com/brave/brave-core/pull/18971)
- Verified no `Loading Skeletons` are shown price are refreshed after `60 seconds
