### ISSUE TITLE
CR 115 - Create a profile modal is referencing the upstream branding instead of the Brave

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#31173]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/30200
Create profile modals referencing upstream branding instead of Brave

## Steps to Reproduce

   1. Clean profile 1.54.72
   2. Click on the `Create a new profile` via Hamburger menu
   3. `Welcome to Brave profiles` modal popup is opened
   4. Tap on '+` or Add
   5. Create profile upsteam modal is opened but the `Done` and `Delete profile` controls are not as per the Brave brand

## Actual result:

![image](https://github.com/brave/brave-browser/assets/38657976/a4b0f84a-a8c1-4e32-bd9d-7ddb947494d8)

## Expected result:

Controls should be Brave branded
## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.54.72 Chromium: 115.0.5790.32 (Official Build) nightly (64-bit)
-- | --
Revision | f9b78cf410ecd5b372310ef25a12ef456c77d90f-refs/branch-heads/5790@{#724}
OS | Windows 10 Version 22H2 (Build 19045.3086)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? No 
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @rebron @aguscruiz @emerick

**Comment by kjozwiak** [comment]
The above requires `1.53.103` or higher for `1.53.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 



Brave | 1.53.103 Chromium: 115.0.5790.32 (Official Build) (x86_64)
-- | --
Revision | f9b78cf410ecd5b372310ef25a12ef456c77d90f-refs/branch-heads/5790@{#724}
OS | macOS Version 11.7.8 (Build 20G1351)



Notes can be found in the final section of https://github.com/brave/brave-browser/issues/30200#issuecomment-1604344525
