### ISSUE TITLE
Quick Commands not working great in Chromium 115.

### ISSUE THREAD

**Issue by Emi-TheDhamphirInLoveUnderTheFrozenStar** [brave/brave-browser#31170]
## Description 

@fallaciousreasoning

Quick commands are not working great since **Nightly 1.54.72** with the new **Chromium 115.0.5790.32** version.

![image](https://github.com/brave/brave-browser/assets/122518587/41bcc766-7887-41cc-bdc4-406ae89090df)

As you can see the UI looks wrong with all those Brave icons displaying between each command.

Technically the commands work, but only when you click on the Brave icons, which means, to navigate with keyboard, you have to go to the command and then hit `tab` to select the Brave button to be able to hit enter and use it without a mouse.

Also, some commands are getting duplicated when you search for them. for example when using `:> close`

Using Windows 11 22h2, and tested it in a new profile with only Quick Commands flag enabled, to make sure it is not a conflict with other flags or settings.

**Comment by fallaciousreasoning** [comment]
Good find! I'll have to see what they changed

**Comment by fallaciousreasoning** [comment]
Looks like they changed how takeover actions work :laughing: I have a fix ready so hopefully it'll land in Nightly in a few days (once it's been reviewed).

**Comment by simonhong** [comment]
As https://github.com/brave/brave-core/pull/18976 doesn't include fix for below, I think it should be opened in a separated issue.
`Also, some commands are getting duplicated when you search for them. for example when using :> close`

**Comment by fallaciousreasoning** [comment]
Whoops, that'll teach me to read to the end! Nice catch @simonhong

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.58.84 Chromium: 116.0.5845.82 (Official Build) beta (64-bit)
-- | --
Revision | b1eb6c7b59795a7a26ae5f6aba87cca8ede0ede2
OS | Windows 10 Version 22H2 (Build 19045.3324)
```

### Steps:
1. installed `1.58.84`
2. launched Brave
3. opened `brave://flags`
4. set `brave://flags/#quick-commands` to `Enabled`
5. clicked `Relaunch`
6. pressed `ctrl` + `spacebar`
7. confirmed I saw the list of quick commands, without icons below them
8. cleared the URL bar of input
9. typed `close`
10. confirmed the list of actions were de-duplicated

`brave://flags` | `ctrl` + `spacebar` | `close` search
----------------|--------------------|----------------
![image](https://github.com/brave/brave-browser/assets/387249/52fc4833-22be-4950-b2e6-95f56116afee) | ![image (1)](https://github.com/brave/brave-browser/assets/387249/8a84ed43-2d83-4832-9a6a-5f4ccc7fd182) | ![image (2)](https://github.com/brave/brave-browser/assets/387249/fd7af9c7-f489-4048-ada7-003753d35169)
