### ISSUE TITLE
"Import/Export bookmarks" strings not translated to other languages

### ISSUE THREAD

**Issue by vlad-hoff** [brave/brave-browser#31176]
## Description 

`Import bookmarks` and `Export bookmarks` are not translated into other languages.

## Steps to reproduce 

   1. Launch Brave 1.53.x
   2. Three-dot menu > Bookmarks
   3. Change device language in device settings
   4. In Brave on the Bookmarks screen tap Three-dot menu in the top right corner > Observe

## Actual result 

`Import bookmarks` and `Export bookmarks` on the Bookmarks screen are not translated into other languages.

|English|German|Russian|Japanese|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/09ba844d-82c2-4907-9c50-c0d838ccb4fe) | ![2](https://github.com/brave/brave-browser/assets/128532965/b5586086-e32b-4c01-ae3a-1a53de096ef1) | ![3](https://github.com/brave/brave-browser/assets/128532965/d8f430ea-899b-417a-a071-1903be84237b) | ![4](https://github.com/brave/brave-browser/assets/128532965/42e18245-f153-4b1e-b1b2-667c9d058c8a) |

## Expected result

`Import bookmarks` and `Export bookmarks` must be translated into other languages.

## Issue reproduces how often 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Pixel 7 (phone)
   - Android version: Android 14 [panther_beta-user 14 UPB3.230519.014 release-keys]
   
## Brave version

Brave build: 1.53.100
Chromium: 114.0.5735.133 (Official Build) beta (64-bit)
Revision: fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.53.107` or higher for `1.53.x` verification 👍
