### ISSUE TITLE
Confirmations implementation

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#3117]
Implement Confirmations into Brave Core

**Comment by bsclifton** [comment]
@tmancey can you add a test plan in here? (or in the PR- and then link to it from the top post)

**Comment by tmancey** [comment]
Test Plan: https://docs.google.com/document/d/1ym8tTKdwSkKUPEI4O_iD2qLaYFMdsCjsUdEod5ouZIg/edit#

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.63.45 Chromium: 74.0.3729.75 (Official Build) beta(64-bit)
-- | --
Revision | fdb7915642fef8cf997beac2554709d148e3c187-refs/branch-heads/3729@{#754}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-browser/issues/3117#issuecomment-483226255
