### ISSUE TITLE
Add network selector in add custom asset dialog

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#31188]

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.58.114 x64 Beta build
- Verified steps from issue description
- Verified network selector is shown in add custom asset dialog

https://github.com/brave/brave-browser/assets/17010094/f6117b1b-4b2e-4884-aa6e-cad3e0864d38
