### ISSUE TITLE
Not able to play flash videos on hbonordic.com

### ISSUE THREAD

**Issue by Skretch** [brave/brave-browser#3118]
## Description 
When I try to play videos on https://no.hbonordic.com/ the site throws an error telling me that "Adobe Flash needs to be installed and activated to play video content" even though I have enabled flash for the website and disabled all shields

## Steps to Reproduce
1. Visit https://no.hbonordic.com/
2. Disable all shields
3. Enable flash with the little padlock to the left of the search field
4. Click play on a video

## Actual result:
http://prntscr.com/mcewos

## Expected result:
The website should load another page and play the video

## Reproduces how often: 
Easily reproduced, as far as I know it happens every time.

## Brave version (brave://version info)

Brave | 0.58.21 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Windows
JavaScript | V8 7.1.302.31
Flash | 32.0.0.114 C:\WINDOWS\system32\Macromed\Flash\pepflashplayer64_32_0_0_114.dll

Originaly I hadn't downloaded pepflashplayer but when I install it the website throws another error that tells me there was and error and that I should try again later.

### Reproducible on current release:
Yes, its reproducible on current release

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields?  No
- Is the issue reproducible on the latest version of Chrome? No

### Additional Information

Flash works on these websites:
- http://techno.org/electronic-music-guide/
- http://www.zombo.com/
- http://homestarrunner.com/

Haven't been able to find any other websites that uses flash player for videos.

**Comment by NumDeP** [comment]
flash's dead baby, flash's dead.

**Comment by ryanbr** [comment]
Safe to close @Skretch ? https://homestarrunner.com/main works using a flash replacement.  Couldn't test https://no.hbonordic.com/

**Comment by ryanbr** [comment]
Closing ticket, since flash has been removed. This is no longer applicable
