### ISSUE TITLE
"Bookmarks imported/exported successfully." strings are not translated into other languages

### ISSUE THREAD

**Issue by vlad-hoff** [brave/brave-browser#31183]
## Description 

`Bookmarks imported successfully.` and `Bookmarks exported successfully.` are not translated into other languages.

## Steps to reproduce 

   1. Launch Brave 1.53.x
   2. Three-dot menu > Bookmarks
   3. Change device language in device settings
   4. In Brave on the Bookmarks screen tap Three-dot menu in the top right corner
   5. Tap `Export bookmarks` > Observe pop-up message
   6. Now close that message and tap Three-dot menu in the top right corner again
   7. Tap `Import bookmarks` > Choose file > Observe pop-up message

## Actual result 

Observed that `Bookmarks imported successfully.` and `Bookmarks exported successfully.` on the confirmation message are not translated into other languages.

|English|German|Russian|Japanese|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/26350244-7e1c-404d-b7af-92d3fa6427b3) | ![2](https://github.com/brave/brave-browser/assets/128532965/2bb71005-8144-40f2-8f3e-2f926c76b467) | ![3](https://github.com/brave/brave-browser/assets/128532965/611e6258-1f86-489c-9ed8-999e7876b826) | ![4](https://github.com/brave/brave-browser/assets/128532965/3a108142-98b4-45e4-8621-1cd60fc885f6) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/5944f48a-f135-4b29-8794-64e6c732b31a) | ![2](https://github.com/brave/brave-browser/assets/128532965/f41fbd6e-99e1-4a77-a18e-026c4675fdad) | ![3](https://github.com/brave/brave-browser/assets/128532965/6c885176-d3a6-42ad-b2c1-b39abc0c3676) | ![4](https://github.com/brave/brave-browser/assets/128532965/19b3d7b2-0fdd-455e-b43f-2db565814adb) |

## Expected result

`Import bookmarks` and `Export bookmarks` must be translated into other languages.

## Issue reproduces how often 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Pixel 7 (phone)
   - Android version: Android 14 [panther_beta-user 14 UPB3.230519.014 release-keys]
   
## Brave version

Brave build: 1.53.100
Chromium: 114.0.5735.133 (Official Build) beta (64-bit)
Revision: fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.53.107` or higher for `1.53.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using the following version(s):

```
Brave	1.56.5 Chromium: 115.0.5790.75 (Official Build) (64-bit) 
Revision	3433e4d513e8454ba0243deea3d53693661dc0c3-refs/branch-heads/5790@{#1430}
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
Using STR in https://github.com/brave/brave-browser/issues/31183#issue-1766174194

- Verified that dialog in the popup for importing and exporting bookmarks is translated.

Example | Example | Example | Example
-|-|-|-
![screenshot-1689278130353](https://github.com/brave/brave-browser/assets/17885425/61933cee-d811-45b2-bbe2-2b46fae4f380) | ![screenshot-1689278171810](https://github.com/brave/brave-browser/assets/17885425/c6677a59-900a-45fe-b49a-cff97d61d6ee) | ![screenshot-1689278208438](https://github.com/brave/brave-browser/assets/17885425/99ce4c99-e0d1-4083-bb0c-921ed5a18916) | ![screenshot-1689278233508](https://github.com/brave/brave-browser/assets/17885425/447608f5-6845-4419-982f-8853cb94cd04)
![screenshot-1689278151303](https://github.com/brave/brave-browser/assets/17885425/ce96da0b-d6e3-4f11-a531-b6f465a92a91) | ![screenshot-1689278190094](https://github.com/brave/brave-browser/assets/17885425/a8152a4d-be21-4c29-8281-d01ae49c3522) | ![screenshot-1689278217186](https://github.com/brave/brave-browser/assets/17885425/1be41bb4-df0b-42c6-96d5-6e6bc80e9aba) | ![screenshot-1689278233508](https://github.com/brave/brave-browser/assets/17885425/4c8c2404-e860-4786-a27c-3c78c146589a)
