### ISSUE TITLE
Cannot open pdf file in new window, No problems with Chrome.

### ISSUE THREAD

**Issue by juliangent** [brave/brave-browser#3119]
## Description 
Cannot open pdf file in new window. No problem using chrome.

PDF document is supposed to open when clicking link in a separate window.

message says 'this plugin is not supported'

expected result
pdf file should open in new window. No problems with chrome browser.

## Reproduces how often: 
every time

## Brave version (brave://version info)
Version 0.58.21 Chromium: 71.0.3578.98 (Official Build) (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? no
![1548528867391](https://user-images.githubusercontent.com/47064698/51791509-1fc01a00-2159-11e9-90b0-afca40ef4c5b.jpg)

### Additional Information
no

**Comment by srirambv** [comment]
Could you add the details of the site?

**Comment by rebron** [comment]
possibly flash related, still need steps to reproduce.

**Comment by juliangent** [comment]
Thank you. The problem is the browser can open pdfs embedded within the browser but pdfs in pop up windows do not open. I am including some screenshots. The same pdf should open in the small window. Says plugin not installed.   01.02.2019, 12:46, "Rafael Ebron" <notifications@github.com>:possibly flash related, still need steps to reproduce.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by andyrpearson** [comment]
I get a similar problem within Xero (sorry you'll need an account to replicate) where they have a 'print PDF' button on invoices that triggers some javascript that opens an in-browser popup that shows while the PDF is being generated. In chrome this downloads; in brave it replaces the current window with the Brave PDF plugin but shows an error as per screenshot. I can't find any way around this to get the PDF other than reverting to Chrome. Error shown is:
> Unexpected server response (500) while retrieving PDF "https://go.xero.com/AccountsReceivable/InvoiceDownloader.aspx?PrintJobId=3495306".
Screenshot:
<img width="1552" alt="screenshot 2019-02-14 at 12 39 04" src="https://user-images.githubusercontent.com/18284988/52787401-a4fe6680-3055-11e9-88c7-200c157e64c1.png">

**Comment by andyrpearson** [comment]
I got round my issue by changing the settings to default to downloading PDFs rather than opening them (which I guess just bypasses the PDF extension that was causing the problem)

**Comment by juliangent** [comment]
Thanks --Sent from Yandex.Mail for mobile14.02.2019, 04:49, "andyrpearson" <notifications@github.com>:I got round my issue by changing the settings to default to downloading PDFs rather than opening them (which I guess just bypasses the PDF extension that was causing the problem)

**Comment by bsclifton** [comment]
I believe I have repro steps for this!

Visit https://pdfobject.com/examples/detection.html

## Expected
Message `This browser supports inline PDFs` should be shown (green color)

## Actual
Message `This browser does not support inline PDFs` shows (red color)

**Comment by juliangent** [comment]
Thank you for your reply. I use a website that opens the pdf in a separate window and allows to scroll and resize the page quickly. It works fine with Google Chrome. But Brave opens the pdf below in the same page and does not allow scrolling. Please see screenshot. The window about:blank is empty. The pdf should open there.               25.04.2019, 15:38, "Brian Clifton" <notifications@github.com>:I believe I have repro steps for this!Visit https://pdfobject.com/examples/detection.htmlExpectedMessage This browser supports inline PDFs should be shown (green color)ActualMessage This browser does not support inline PDFs shows (red color)—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by bsclifton** [comment]
@juliangent OK thanks for the update - maybe we can share an update when we have a potential fix

**Comment by mckenzieja** [comment]
+1 Here.

We tried to implement [jsPDF](http://raw.githack.com/MrRio/jsPDF/master/) (An HTML5 JavaScript PDF generation Library) and noticed that PDFs opened in a new window automatically triggered the download dialog and spent some considerable time scratching our heads (we realized it was Brave related).

Fortunately this is very VERY easy to test using jsPDF.
`npm install jspdf`

run this simple script in the browser

```
var doc = new JsPDF();

doc.setFontSize(40);
doc.text("We Love Brave!", 35, 25);
doc.output('dataurlnewwindow'); //Outputs the rendered PDF in a new window
```

**Chrome**: Renders PDF within the browser PDF viewer in the new window (works)
**Brave**: Opens the new window (blank) "Save As" download dialog prompt opens. (Cancelling the download closes the window)

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.68.113 Chromium: 76.0.3809.62 (Official Build) beta (64-bit)
-- | --
Revision | 7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS | Windows 7 Service Pack 1 (Build 7601.24494)

Verified test plan from https://github.com/brave/brave-core/pull/2342
Verified test plan provided in https://github.com/brave/brave-browser/issues/3119#issuecomment-486847180
