### ISSUE TITLE
Login issue on live.com

### ISSUE THREAD

**Issue by pilgrim-brave** [brave/brave-browser#31196]
(selected snippets from Slack conversation)

Hello, on https://login.live.com/, the site doesn’t load browser language setting(brave://settings/languages) if Prevent sites from fingerprinting me based on my language is enabled on brave://settings/shields. If the setting is enabled, the site is shown in English even if I set Japanese on the language setting. But the site is shown in Japanese if I turn off that setting. I have a user who would like to see the site in Japanese with Shields enabled.

I can reproduce the issue with non-aggressive mode(standard shields setting).

might be good to hardcode an exception then for uplift, and then bite the bullet and add a component so we can handle going forward

**Comment by pilgrim-brave** [comment]
@pes10k @A-t-s-u-s-h-i @ryanbr

**Comment by kjozwiak** [comment]
The above requires `1.53.106` or higher for `1.53.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.53.107 Chromium: 115.0.5790.40 (Official Build) （64 ビット）
-- | --
変更履歴 | 071c9ddea889c3c7887daf4eac13fed72d4fff62-refs/branch-heads/5790@{#979}
OS | Windows 11 Version 22H2 (Build 22621.1848)
```



Reproduced the issue in `1.52.129 Chromium: 114.0.5735.198` 

example | example 
---- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/9ed0e40a-42e7-4675-a84e-efb979f50aad)|![image](https://github.com/brave/brave-browser/assets/98358127/b11534ed-f174-4b5d-94c4-507c062348e2)

Confirmed https://login.live.com is translated in 1.53.107 Chromium: 115.0.5790.40

example | example 
---- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/4664624e-bb3a-414f-882a-5589be59e3df)|![image](https://github.com/brave/brave-browser/assets/98358127/af620075-3aa1-4e86-9026-f7d24c0dde7f)

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using the following version(s):

```
Brave	1.56.3 Chromium: 115.0.5790.75 (Official Build) (64-bit) 
Revision	3433e4d513e8454ba0243deea3d53693661dc0c3-refs/branch-heads/5790@{#1430}
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

**Case 1: OS settings**

- Verified page is translated on clean profile based on OS language preferences when viewing `https://login.live.com.` 
- Verified user is page able to translate page using the toolbar.

Example | Example
-|-
![screenshot-1689197882897](https://github.com/brave/brave-browser/assets/17885425/c02ccf89-6ea4-4228-86df-88a9d85c5f7f) | ![screenshot-1689197946989](https://github.com/brave/brave-browser/assets/17885425/4de10894-0949-4347-b19d-d13f81cb8ecf)

**Case 2: Brave preferred language**

- Verified login.live.com is translated when making Japanese preferred language in settings

**Case 3: Accept Languages**

- Verified all languages are listed under `Accept-Language` in the headers for `login.live.com`
- Verified only single language is listed other other sites

live.com | other site
-|-
![Screenshot 2023-07-12 at 5 52 10 PM](https://github.com/brave/brave-browser/assets/17885425/d72726ce-7603-4668-b611-378423836861) | ![Screenshot 2023-07-12 at 5 55 53 PM](https://github.com/brave/brave-browser/assets/17885425/889d2009-39e2-45d5-a642-b0d73490d904)
