### ISSUE TITLE
`Copy clean link` on macOS context menu should be title case (`Copy Clean Link`)

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#31198]
## Description 
![image](https://github.com/brave/brave-browser/assets/4733304/cffe06a8-9819-4548-80f5-d5d9fa98fdd8)

## Steps to Reproduce

   1. Be on macOS
   2. Set locale as en_GB (UK)
   3. Load a web page which has links in it
   4. Right click / Cmd click a link

## Actual result:
Context menu shows `Copy clean link`

## Expected result:
- macOS should show `Copy Clean Link`
- Other OS should stay as `Copy clean link`

## Reproduces how often: 
100%

**Comment by bsclifton** [comment]
This looks good in our code - this is a problem with the translations (en-GB)
https://github.com/brave/brave-core/blob/c5020b7d9bc5a20cab58aefd85e514fd9fa44f8e/app/resources/brave_generated_resources_en-GB.xtb#L9

**Comment by bsclifton** [comment]
Updated in Transifex - this string is good to go and should be pulled down for 1.53.x

However, there are some inconsistencies with en-GB in general 🤔 Other title case ones are put in regular sentence case
![image](https://github.com/brave/brave-browser/assets/4733304/a1997d54-e415-4e51-9ba7-9dd5c103c1cf)

**Comment by LaurenWags** [comment]
Added `QA/Blocked` label until 1.53.x gets translations added.

**Comment by LaurenWags** [comment]
Verified with

```
Brave | 1.53.107 Chromium: 115.0.5790.40 (Official Build) (x86_64)
-- | --
Revision | 071c9ddea889c3c7887daf4eac13fed72d4fff62-refs/branch-heads/5790@{#979}
OS | macOS Version 13.4.1 (Build 22F82)
```

Verified STR from description. 
Confirmed correct case for "Copy Clean Link" on macOS when language is UK English.

OS Setting | 1.52.129 | 1.53.107
--- | --- | ---
<img width="726" alt="1" src="https://github.com/brave/brave-browser/assets/28145373/8b81cba0-c5d2-42fa-9b7b-3243436cabf9"> | <img width="328" alt="1 52 129" src="https://github.com/brave/brave-browser/assets/28145373/2d6c6171-52d1-4e7c-af4c-77f0129c6b3c"> | <img width="346" alt="1 53 107" src="https://github.com/brave/brave-browser/assets/28145373/651ee533-9d41-41bd-96b0-1bcd3e51270e">

**Comment by LaurenWags** [comment]
@brave/qa-team added `QA/Test-All-Platforms` as the description specifies that other OSes should not have the same case as macOS, so we should confirm this on Windows and Linux.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.53.107 Chromium: 115.0.5790.40 (Official Build) (64-bit)
-- | --
Revision | 071c9ddea889c3c7887daf4eac13fed72d4fff62-refs/branch-heads/5790@{#979}
OS | Windows 11 Version 22H2 (Build 22621.1848)
```
Verified STR from description.
Confirmed no change in the case for "Copy Clean link" on Windows as when language is UK English.

OS settings | `1.52.129` | `1.53.107`
---- | ----- | -----
<image width = "700" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/8d559a4f-0db2-44f0-a98e-dfcd74924fe5">|<image width = "700" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/9dfa72fb-bbcd-486e-bf06-622bca232c67">|<image width = "700" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/2600e11b-1961-49e0-a9ba-a6338024c2fa">
