### ISSUE TITLE
Manually block page elements via right click context menu

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#312]
Cross posting issue from https://github.com/brave/browser-laptop/issues/7521. Would be great to ship it with 1.0

**Comment by Jacalz** [comment]
+1 from me and sorry for pressning the wrong button 😬

**Comment by bbondy** [comment]
Being worked right now and being tracked here:
https://github.com/brave/brave-browser/issues/312

**Comment by bbondy** [comment]
We'd like this to ship with brave-core, I think it will.
