### ISSUE TITLE
Scroll bar for vertical tabs 

### ISSUE THREAD

**Issue by RDKRACZ** [brave/brave-browser#31204]
Vertical tabs would benefit from having a visible scroll bar to indicate current position since we don't know how many tabs are there - in horizontal tabs mode, tab width is shorter the more you have of them, but obviously this is not an option for vertical tabs.

A scroll bar would also be helpful for, well scrolling if someone is using touchpad - because of the lack of the scroll wheel.

https://github.com/brave/brave-browser/issues?q=vertical+tabs+scroll+bar

**Comment by is-this-c** [comment]
Not sure why nothing's happening here.  Vertical tabs is not really usable without a scroll bar.  Hence, I'm forced to continue using Edge. However, I quickly looked at the code. There seems to be support for a scroll bar. But it has been set to a hidden mode. It seems that it will be easy to fix. @sangwoo108

**Comment by sangwoo108** [comment]
@is-this-c Thanks for letting me know. 

@aguscruiz , @rebron , how about making an option for toggle scrollbar on vertical tabs? I've seen someone want it so that they could scroll it with tablet.

**Comment by RDKRACZ** [comment]
Another problem related to the missing scroll bar is that when the vertical tab list is full and I open a new tab in the background (with the ctrl key) while being on the last one, I need to manually scroll the tab list down to see if it actually opened.

With the scroll bar I would see it's no longed at the bottom so there must be a tab below the one I'm currently on.

**Comment by naciacia** [comment]
How long we need to wait for this? You gave as vertical tabs but You didn't give as basic functionality so we can use these vertical tabs??

**Comment by sangwoo108** [comment]
Apologies, I've been working on other features. Let me find some time for this.

**Comment by sangwoo108** [comment]
Hello, everyone. I'm on my vacation but checked if this could be easily done. But unfortunately, Mac implementation would require more effort. By the way, I'm curious if Mac users also want this feature, as the scrollbar style seems to be control by the OS setting. If not, maybe we can support this setting only for Linux and Windows users.

**Comment by petemill** [comment]
As a mac user, I would like the scrollbar to at least follow the macOS style of being a scroll "indicator". In other words, show only when scrolling, and appear on top of content. At least then I would have some guidance on how big the list of Tabs is and where in the list I am currently looking.
I can see why this is more difficult on other OSes. I believe on other OS we should have it behave like an indicator too... but we could make it a preference between scroll indicator and permanent scroll bar.

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.63.24 Chromium: 120.0.6099.71 (Official Build) nightly (64-bit)
-- | --
Revision | 8858c508f9a33d9cb69c2b3f2da81a52a15040f6
OS | Windows 10 Version 22H2 (Build 19045.3758)
```

### Steps:
1. installed `1.63.24`
2. launched Brave
3. loaded a plethora of sites in new tabs (same window) which overflow the current viewport
4. context-clicked on a tab and chose `Use Vertical tabs`
5. confirmed no scrollbar present
6. opened `brave://flags`
7. set `brave://flags/#brave-vertical-tab-scroll-bar` to `Enabled`
8. clicked `Relaunch`

### Confirmed visible and working scrollbar appeared

`brave://flags` | `Enabled` | `Disabled`
----------|------------|---------
![image](https://github.com/brave/brave-browser/assets/387249/284c1785-cbe8-4380-8145-1d03a9626cef) | ![image](https://github.com/brave/brave-browser/assets/387249/98a204fb-e3e8-46ba-876d-1d16abba88c3) | ![image](https://github.com/brave/brave-browser/assets/387249/3d117c36-4c7c-4f7f-b97b-e17b804e71ba)

**Comment by tastyLT** [comment]
I'm not sure if I'm supposed to comment here, but after some heavy Google searching I found this gem. Thank you so much for adding this feature!

**Comment by aguscruiz** [comment]
> I'm not sure if I'm supposed to comment here, but after some heavy Google searching I found this gem. Thank you so much for adding this feature!

I'm glad you like it! ❤️
