### ISSUE TITLE
Prompt user to switch to native ipfs:// or ipns://  when on IPFS resource

### ISSUE THREAD

**Issue by lidel** [brave/brave-browser#31203]
> filled this based on the SOW document and verbal from last sync

When user is on IPFS page that is a known IPFS resource (has X-Ipfs-Path header, or URL is matching public gateway URL, or website with valid DNSLink), we show the purple button:

> ![2023-06-21_19-44](https://github.com/brave/brave-browser/assets/157609/6929ff73-99cf-4d96-85ea-4fb1d7dceb2d)

Then clicked, it opens native `ipns://` in a new tab (and if user has no IPFS enabled, opens onboarding page UI).

### How to improve user onboarding

The idea here is to go beyond purple button and add interactive prompt when  IPFS support is not enabled yet OR when it is enabled, but redirect to local node is disabled. This way, users have opportunity to opt-in to loading IPFS resources over native protocol, when possible.

> "Would you like to load this webpage over native IPFS?"
> 
> - Don't ask again (checkbox)
> - Only this time (button, opens via native URI, but does not enable redirect)
> - Always, all IPFS pages  (button, opens via native URI and enables redirect)

There is some prior art interface in Chromium already, it is used for DRM opt-in, perhaps this UI pattern could be reused:

> ![2023-06-21_19-44_1](https://github.com/brave/brave-browser/assets/157609/b74d90e7-b91b-4edf-ab06-8460aefb8946)

cc @cypt4 @autonome

**Comment by cypt4** [comment]
IPFS promo infobar was added here https://github.com/brave/brave-browser/issues/33007
