### ISSUE TITLE
Option to hide Brave Shields activity count

### ISSUE THREAD

**Issue by innergy** [brave/brave-browser#3121]
## Test plan
See https://github.com/brave/brave-core/pull/3150

## Description 
Some people think the incrementing block count on Brave Shields is distracting. 

> The color of the icon is enough for me to know whether it's enabled or not, and if it's enabled I trust that it's working. I'm happy to click the icon if I need more details, but that's rare.

Provide the option to hide the block count while still keeping the shields up.

## Designs
Add "Indicate the number of blocked items on the Shields icon"  to Shields settings: 

![shields hide block count indicator](https://user-images.githubusercontent.com/2388823/56168117-10e64800-5f8f-11e9-8647-61ed83998afc.png)

It will be toggled ON by default. If the user toggles the indicator OFF, the Shields icon will not have the incrementing blocked item counter, but will still be colored when it's enabled.

**Comment by Liunkae** [comment]
This feature used to be available with Brave Muon: brave/browser-laptop#8613, brave/browser-laptop#8701

Tag: [browser-laptop-parity](https://github.com/brave/brave-browser/labels/browser-laptop-parity)

**Comment by Liunkae** [comment]
This feature used to be available with Brave Muon: brave/browser-laptop#8613, brave/browser-laptop#8701

Label: [browser-laptop-parity](https://github.com/brave/brave-browser/labels/browser-laptop-parity)

**Comment by b-mueller** [comment]
+1. 

The count being displayed is horrible for somebody with OCD tendencies (like me). It constantly makes me feel like there are some open notifications I'm supposed to handle 😞

**Comment by ryder203** [comment]
+1 - please devs, give us an option to hide that counter and a seperate option to hide the lion icon. It's useless for me, and IMHO not aesthetic all in all. Less is more.

**Comment by english06** [comment]
+1

**Comment by hamishr** [comment]
+1

**Comment by vladk** [comment]
+1 all popular ad blockers have option to hide blocked items counter, that's very surprising brave browser doesn't have that. that counter is super distracting, so actually brave browser isn't usable for me while there is no option to hide it

**Comment by colonicregulator** [comment]
> +1 all popular ad blockers have option to hide blocked items counter, that's very surprising brave browser doesn't have that. that counter is super distracting, so actually brave browser isn't usable for me while there is no option to hide it

Echo this. Completely unusable without this option. Back to Firefox for time being.

**Comment by karenkliu** [comment]
Designs added.

**Comment by caroltoo** [comment]
Can I ask what P3 backlog means in terms of timelines? This is incredibly distracting to me too and I would love to know if this is going to be updated soon after I just migrated everything from Chrome.

**Comment by bsclifton** [comment]
@caroltoo hard to estimate a timeline, but this issue is definitely on our radar 😄 I don't think it would be a terribly difficult change to make (we'd just need to set aside the time to do it)

**Comment by Brave-Matt** [comment]
+1 from Reddit:
https://www.reddit.com/r/brave_browser/comments/bjdk7d/how_to_turn_off_the_number_of_ads_blocked_on/

**Comment by usaccounts** [comment]
Time to fork guys.

**Comment by usaccounts** [comment]
:D

**Comment by pioul** [comment]
Nice to see this is being considered. I'd also be happy with a setting to hide the Brave Ad Block icon altogether while we're at it (and the Brave Rewards icon too, for that matter – f/u to https://github.com/brave/brave-browser/issues/1475), since they're both already available from the menu dropdown.

In the same way that any extension can be hidden in the Brave Menu, my opinion is that those two features should follow a similar pattern, and allow icons to be hidden for users who don't interact with them too often. I acknowledge that the decision for the Brave Rewards icon might be different because having the icon out there is a way to encourage the feature's usage, but for Brave Ad Block I'd see no drawbacks to allowing the icon to be hidden entirely.

**Comment by igekaratas** [comment]
Hi, how do I put this setting into my Brave browser? I am not good with Github, I don't know how to apply these kind of settings.
Thanks.

**Comment by bsclifton** [comment]
@igekaratas thanks for your patience; we're reviewing now and should be able to merge a fix for this soon 😄

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 1.7.67 Chromium: 80.0.3987.149 (Official Build) beta (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | Windows 10 OS Version 1803 (Build 17134.1006)


- Verified the test plan from https://github.com/brave/brave-core/pull/3150
- Verified  `Show the number of blocked items on the Shields icon` works as expected when toggle OFF/ON
- Verified that changes are reflected across all the tabs in Normal Tab/Private Tab/Private tab with Tor
- Verified in both clean and upgraded profiles

**Comment by usaccounts** [comment]
Brave is now usable. Switched.
