### ISSUE TITLE
Vertical tabs hover mode card stays open when switching apps or mission control 

### ISSUE THREAD

**Issue by justindoody** [brave/brave-browser#31211]
## Description 
With tab hover mode of card in use with vertical tabs if you have your mouse over a tab triggering the card and then switch to a different app or workspace or trigger mission control (macOS) and then come back to the browser the hover cards stays stuck open when interacting with the browser until you interact again with the vertical tabs sidebar triggering a new (or the same) hover card. When using non vertical tabs in a similar situation the card may stay upon but close as soon as you interact with any part of the browser window again.

## Steps to Reproduce

   1. Enable vertical tabs and tab hover mode "card"
   2. Move mouse onto vertical tab sidebar and over a tab to trigger the card preview
   3. Activate another app with command + tab or open mission control (three finger swipe up)
   4. Return to the browser (mousing over anything besides the vertical tab sidebar)
   5. Card preview stays expanded until vertical tab sidebar entered and exited again.

## Actual result:
Card stays stuck open.

## Expected result:
Card should close when interacting with other parts of the browser window.

## Reproduces how often: 
Easily reproduced. (Only confirmed on macOS)

## Brave version (brave://version info)

Brave | 1.52.122 Chromium: 114.0.5735.110 (Official Build) (arm64)
-- | --
Revision | 1c828682b85bbc70230a48f5e345489ec447373e-refs/branch-heads/5735_90@{#13}
OS | macOS Version 13.4 (Build 22F66)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

This should be pretty similar to https://github.com/brave/brave-browser/issues/30966 but for the card preview instead of the whole sidebar expansion.

Fairly minor issue but in my workflow at least I encounter this often enough to be a bit annoying.

**Comment by rebron** [comment]
@sangwoo108 I'm wondering if your other changes may address this one as well.

**Comment by sangwoo108** [comment]
I think it's not reproduced anymore. Please let me know if it still happens.

**Comment by DomiMili** [comment]
This still happens to me, on Windows, very annoying. I use two browser windows, one on each monitor and when sliding over to the left one, one tab hover on the right always gets stuck just because I slid a mouse on top of it. It's super frustrating.
