### ISSUE TITLE
The metrics `Brave.Wallet.EthProvider.4` response is incorrect when both Brave wallet and MM wallets are created

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#31224]
## Description 

Found while testing https://github.com/brave/brave-core/pull/18782
The metrics `Brave.Wallet.EthProvider.4` response is incorrect when both Brave wallet and MM wallets are created
## Steps to Reproduce

1. Clean profile 1.55.2
2. Install and create a MM wallet and create a Brave wallet
3. Open any HTTPS site
4. Open brave://local-state file and look for the metrics `Brave.Wallet.EthProvider.4`
5. The metrics `Brave.Wallet.EthProvider.4` response value is `2` `Brave Wallet (wallet is setup, no installed extension)` instead of `4` or `5` not sure but definately not `2` response

   

## Actual result:

The metrics `Brave.Wallet.EthProvider.4` response is incorrect when both Brave wallet and MM wallets are created

## Expected result:

Response should be `4` or `5` 
## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.55.2 Chromium: 115.0.5790.32 (Official Build) nightly (64-bit)
-- | --
Revision | f9b78cf410ecd5b372310ef25a12ef456c77d90f-refs/branch-heads/5790@{#724}
OS | Windows 10 Version 22H2 (Build 19045.3086)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @mattmcalister @DJAndries

**Comment by DJAndries** [comment]
> Clean profile 1.52.2

You meant 1.55.x, right?

When the web3 menu setting is set to "Extensions (Brave Wallet fallback)", I get answer 5, which is expected.

**Comment by GeetaSarvadnya** [comment]
@DJAndries Verified the issue again, now I am getting the correct response as `5` I am not sure why I was getting `2` yesterday. Closing the issue. Thanks!
