### ISSUE TITLE
Add learn more to Brave Rewards: Welcome page

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#3122]
Add "Learn More" to the Brave Rewards welcome page text at the bottom.

Learn More should link to: https://brave.com/faq/

cc @jenn-rhim @NejcZdovc

**Comment by amad-person** [comment]
Would like to take this issue up!
I'm a new contributor, so I had a question regarding where to add the "Learn More" link - does it need to be added in `brave://rewards/` and in the welcome tour `brave://welcome/`?

**Comment by NejcZdovc** [comment]
@amad-person hi, welcome!

This would needs to be added to `brave://rewards/` page. I will get more info/designs and let you know in this issue when we have them.

**Comment by amad-person** [comment]
@NejcZdovc thanks!

**Comment by NejcZdovc** [comment]
cc @jenn-rhim

**Comment by NejcZdovc** [comment]
friendly ping @jenn-rhim @rossmoody

**Comment by NejcZdovc** [comment]
closing as stale
