### ISSUE TITLE
Incorrect response for `Brave.Wallet.EthProvider.4` when MM is installed and wallet is created

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#31226]
## Description 

Found while testing https://github.com/brave/brave-core/pull/18782
Incorrect response for `Brave.Wallet.EthProvider.4` when MM is installed and wallet is created
## Steps to Reproduce

1. Clean profile 1.55.2
2. Select "Extension (no fallback)" from `Web 3` dropdown
3. Install and create a MM wallet
4. Open any HTTPS site
5. Open brave://local-state file and look for the metrics `Brave.Wallet.EthProvider.4`
6. The metrics `Brave.Wallet.EthProvider.4` response value is `4` instead of `5` 
   

## Actual result:

Incorrect response for `Brave.Wallet.EthProvider.4` when MM is installed and wallet is created
## Expected result:
The response should be `5`

## Reproduces how often: 

Easy
## Brave version (brave://version info)

<html>
<body>

Brave | 1.55.2 Chromium: 115.0.5790.32 (Official Build) nightly (64-bit)
-- | --
Revision | f9b78cf410ecd5b372310ef25a12ef456c77d90f-refs/branch-heads/5790@{#724}
OS | Windows 10 Version 22H2 (Build 19045.3086)

</body>
</html>
## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @mattmcalister @DJAndries

**Comment by DJAndries** [comment]
As stated in step 5 of the test plan, 4 is the correct answer.

**Comment by GeetaSarvadnya** [comment]
@DJAndries : The test plan case is different in tets plan in step 5 `Extension (Brave wallet fallback)` is selected from web 3 but in this issue the selection is `Extension (no fallback)` 

When the selection is `Extension (no fallback)`  - Extension will take the precedance over any installed wallet and only extension is considered for the communication, hence I was expecting the response as `5` `Third-party extension (overriding a setup Brave Wallet)` discussed with wallet QA spoc @srirambv. Thanks!

cc: @srirambv

**Comment by DJAndries** [comment]
@GeetaSarvadnya Step 5 states "Set the default provider setting to "extensions (no fallback)". Reload page. Ensure the metric has a value of 4."

**Comment by GeetaSarvadnya** [comment]
@DJAndries So do you mean `Extension (no fallback)` setting will not take presendece over brave wallet or any other wallet? If so, then why does the extension is taking presendece when Brave wallet is created in the below case? correct me if I am wrong. Thanks!

```
1. Clean profile 1.55.2
2. Select "Extension (no fallback)" from `Web 3` dropdown
3. Create a Brave wallet
4. Open any HTTPS site
5. Open brave://local-state file and look for the metrics `Brave.Wallet.EthProvider.4`
6. The metrics `Brave.Wallet.EthProvider.4` response value is `1` ((None, because the default provider setting is set to "Extensions (no fallback)")) as expected

```

**Comment by DJAndries** [comment]
With the "extensions (no fallback)" setting, the third-party extension does take precedence. It ensures that the Brave provider is never injected, even when the wallet is setup. This will result in answer 1, when the Brave Wallet is setup and no extension is setup. It will also result in answer 4 when an extension is setup, because the Brave provide is not overridden, because it was never injected in the first place.

**Comment by GeetaSarvadnya** [comment]
As per the comments above, closing the issue as invalid.
