### ISSUE TITLE
Incorrect response for the metrics `Brave.Wallet.EthProvider.4` when Brave wallet is created no other extensions installed

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#31225]
## Description 

Found while testing https://github.com/brave/brave-core/pull/18782
Incorrect response for the metrics `Brave.Wallet.EthProvider.4` when Brave wallet is created no other extensions installed

## Steps to Reproduce

1. Clean profile 1.55.2
2. Select "Brave wallet" from `Web 3` dropdown
3. Create a Brave wallet
4. Open any HTTPS site
5. Open brave://local-state file and look for the metrics `Brave.Wallet.EthProvider.4`
6. The metrics `Brave.Wallet.EthProvider.4` response value is `3` `Brave Wallet (wallet is setup, an extension may potentially be installed but cannot override native provider)` instead of `2` `(Brave Wallet (wallet is setup, no installed extension))`
 

## Actual result:

Incorrect response for the metrics `Brave.Wallet.EthProvider.4` when Brave wallet is created no other extensions installed

## Expected result:
The response should be `2`

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.55.2 Chromium: 115.0.5790.32 (Official Build) nightly (64-bit)
-- | --
Revision | f9b78cf410ecd5b372310ef25a12ef456c77d90f-refs/branch-heads/5790@{#724}
OS | Windows 10 Version 22H2 (Build 19045.3086)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @mattmcalister @DJAndries

**Comment by DJAndries** [comment]
As stated in step 3 of the test plan, 3 is the correct answer.

**Comment by GeetaSarvadnya** [comment]
@DJAndries I will go with your comments and close the issue. Thanks!
