### ISSUE TITLE
Getting error modal if closing/relaunching the browser on `brave://rewards` after being redirected to it by a wallet provider.

### ISSUE THREAD

**Issue by szilardszaloki** [brave/brave-browser#31237]
STR:
1. join Rewards
2. connect with Uphold (wait for them to redirect you back to `brave://rewards`)
3. don't navigate away from `brave://rewards`
4. close the browser
5. relaunch

Above results in:

![image](https://github.com/brave/brave-browser/assets/5390451/5fbbd375-1dd3-4508-9476-eb2c0cd95e79)

Note: `window.location` seems to always contain the previous URL, not the actual one.

In this specific case, `window.location` is `chrome://rewards/uphold/authorization?code=2e6f0c65d0aa7fb052611a915f15a523cda92c89&state=E9BDCC834A0562E8B82A22AC3D7AFE8EF935A9E3F6A15AE532273B518D04E3B2` after the restart, hence Rewards is trying to connect to Uphold again, but fails to do so, as it's already connected. Weird thing is that, _before_ restart, we call `history.replaceState({}, '', '/')` right after processing the URL, therefore `window.location` should be `brave://rewards` after restart.

**Comment by emerick** [comment]
This issue was introduced by https://github.com/brave/brave-core/pull/18898. @simonhong can that fix be made a little more resilient so that it doesn't trip up Rewards users who restore their session after authing with an external wallet? I'm happy to test out any potential fix, it's very easy for me to repro.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.58.88 Chromium: 116.0.5845.82 (Official Build) beta (x86_64)
-- | --
Revision | acf16e35d5897fd4bf9b1b5a93b56aff2ed64bba
OS | macOS Version 13.5 (Build 22G74)
```
