### ISSUE TITLE
Expires property in some lists is not read and set properly by Brave.

### ISSUE THREAD

**Issue by Emi-TheDhamphirInLoveUnderTheFrozenStar** [brave/brave-browser#31238]
## Description 

@antonok-edm
Because of the  conversation about the `$badfilter` and the Default lists and Different Engines, I decided to use the Default lists as Custom lists to test the Expires feature in a greater scale than `uBlock Quick Fixes` list and my own ones.

Well, the feature works great when the Expires property is set to only `Expires: # days` BUT I noticed the property is not read and set properly by Brave in some lists where there are more than that.

Easylist, Easylist Privacy, have it as `Expires: 4 days (update frequency)` and urlhaus-filter-agh-online has it as `Expires: 1 day (update frequency)` same as fanboy-notifications.txt (added by me) but they are set in Local State file to 168 hours, and not the 96 and 24 hours that should be, respectively.
So, Expires should also take into account the `(update frequency)` some lists decided to add.

![image](https://github.com/brave/brave-browser/assets/122518587/ff0d7237-3e09-4c52-b2db-74859bb28bee)

**Comment by Emi-TheDhamphirInLoveUnderTheFrozenStar** [comment]
This is being fixed in the PR https://github.com/brave/adblock-rust/pull/298, everything shall work fine when its merged and available for users.

Thanks to @DJAndries 👍

**Comment by antonok-edm** [comment]
@Emi-TheDhamphirInLoveUnderTheFrozenStar I'll leave this open for the team track the feature in `brave-core` until it lands in Nightly.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.58.90 Chromium: 116.0.5845.96 (Official Build) beta (x86_64)
-- | --
Revision | c112ad8c854bd34b48f4e87bfb3f7951e426a1d4
OS | macOS Version 11.7.9 (Build 20G1426)
