### ISSUE TITLE
Swap page available for locked wallet

### ISSUE THREAD

**Issue by vadimstruts** [brave/brave-browser#31236]
## Description 

Swap page allows to see account balances without wallet to be unlocked

## Steps to Reproduce

   1. Unlock wallet
   2. Go to swap page
   3. Close the browser by clicking "Exit"
   4. Open browser

## Actual result:

You can see balance for the accounts

## Expected result:
No swap page opened (just blank screen)

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on Oppo reno 5 with Android 13 running 1.58.117 x64 build
- Verified steps from [brave/brave-core#18998](https://github.com/brave/brave-core/pull/18998)
- Verified Swap page doesn't show any wallet info when wallet is locked
- Encountered [#32794](https://github.com/brave/brave-browser/issues/32794) 

https://github.com/brave/brave-browser/assets/17010094/1c648e94-0aef-449e-b476-312faf984e28
