### ISSUE TITLE
Unable to submit support form on bfore.ai website

### ISSUE THREAD

**Issue by OJ7** [brave/brave-browser#31239]
## Description 

When filling out the form on https://bfore.ai/support, the submit button does not seem to do anything. This happens with Brave Shields disabled and other adblockers disabled.

## Steps to Reproduce

   1. Go to https://bfore.ai/support/
   2. Fill out form
   3. Click Submit button

## Actual result:

Nothing, no network requests or any visible feedback

## Expected result:
Form submits fine and redirects to a new page

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.52.126 Chromium: 114.0.5735.133 (Official Build) (x86_64)
Revision | fbfa2ce68d01b2201d8c667c2e73f648a61c4f4a-refs/branch-heads/5735@{#1270}
OS | macOS Version 13.4 (Build 22F66)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Nope
- Does the issue resolve itself when disabling Brave Rewards? Nope
- Is the issue reproducible on the latest version of Chrome? Unsure, but the issue is NOT reproducible on Safari (form successfully submit on there)

**Comment by rebron** [comment]
<img width="1158" alt="Screenshot 2023-06-23 at 9 03 17 AM" src="https://github.com/brave/brave-browser/assets/5951041/7fe5f2d2-2b51-431a-93ef-3046c8cb9670">

Thanks for reporting. I wasn't able to reproduce and was able to submit the form. I'm sure you filled in everything properly but sometimes the website's form validation itself is a little tricky.
