### ISSUE TITLE
Onboarding page for Brave Rewards (first time view on opt in)

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#3123]
- All titles for all panels need to be colored appropriately (based on design provided)
- Toggles for a-c and Ads Panel need to be turned ON (no toggle for Tips)
- All Panels should have bolded/colored explainer text (based on design provided)

@jenn-rhim @NejcZdovc

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.61.37 Chromium: 73.0.3683.39 (Official Build) beta (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

Used test plan from https://github.com/brave/brave-core/pull/1574

**Comment by GeetaSarvadnya** [comment]
On Linux - Toggle is not available for Ads, is this because Ads is not yet implemented for Linux platform? 

![image](https://user-images.githubusercontent.com/38657976/53487844-ab0f3100-3ab2-11e9-84af-f1e61e13cfce.png)
@jenn-rhim @NejcZdovc

**Comment by NejcZdovc** [comment]
@GeetaSarvadnya ads are still disabled

**Comment by GeetaSarvadnya** [comment]
@NejcZdovc Do you mean Ads are still disabled on Linux platform. Hence the toggle switch is not shown?

**Comment by NejcZdovc** [comment]
@GeetaSarvadnya correct
