### ISSUE TITLE
Crash in `brave_ads::ConfirmationType::ConfirmationType`

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#31235]
200 crashes for 30 days. Max affected version is 1.52.126

https://brave.sp.backtrace.io/p/brave/triage?time=month&filters=W1siY2FsbHN0YWNrIiwiY29udGFpbnMiLCJicmF2ZV9hZHM6OkNvbmZpcm1hdGlvblR5cGU6OkNvbmZpcm1hdGlvblR5cGUiXSxbImZpbmdlcnByaW50O2lzc3VlcztzdGF0ZSIsImVxdWFsIiwib3BlbiJdLFsiY2FsbHN0YWNrIiwiY29udGFpbnMiLCJicmF2ZV9hZHMiXV0%3D&aggregations=((ver%2Cmax)%2C(guid%2Cunique)%2C(classifiers%2Chead))&similarity=false

No steps to reproduce.

**Comment by kjozwiak** [comment]
The above requires `1.53.106` or higher for `1.53.x` verification 👍
