### ISSUE TITLE
Shields Up section in Shields Status settings page should not exist

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#31230]
Users can see Shields-setting-per-site via brave://settings/content/braveShields, which is accessible from the Site Settings page:

![image](https://github.com/brave/brave-browser/assets/5284154/0313bef9-aa00-44eb-81bb-5847b767ca14)

The Shields Down setting is very helpful because it tells you which website you've had to turn Shields down for. But given that we don't (and shouldn't) have a global Shields toggle, the Shields Up section is a bug:

![image](https://github.com/brave/brave-browser/assets/5284154/f609301e-2ac1-4ac5-844d-7383778f7cea)

**Comment by spylogsster** [comment]
@ShivanKaul this option used by policies https://github.com/brave/brave-browser/issues/25394 cc @bsclifton @rebron
