### ISSUE TITLE
[Android] Crash in ad notification

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#31243]
## Description 
The brave crash is happening only for the ads which don't have a [brave.com](http://brave.com/) landing page or  target URL.

## Steps to reproduce 

1. Clean profile on manual build with unblinded token set 21
2. Enable all the required flags via QA preferences
3. Enter "--rewards=staging=true" in the cmd line string via QA preferences
4. Enable rewards and get the payment id via brave://rewrads-internals/
5. Schedule 1st captcha
6. Confirmed that 21 unblinded payment tokens are added via logs
7. Open cnn.com and wait for the Ad
8. Confirmed 1 unblinded token is redeemed for ad view event and 20 unblinded token are remained
9. Tap on the Ad from the notification center, when we got "Required captcha" logs in Android studio app crashed on my Android device (when the app crashed I was still on the ads landing page)
After step 9, I scheduled 2nd captcha and was able to solve the captcha and 2 payment tokens have been added to the logs

## Actual result 
The brave crash is happening when we tap on ad notification which don't have a [brave.com](http://brave.com/) landing page or  target URL.

## Expected result
It should not crash the app. 

## Issue reproduces how often 
Easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by deeppandya** [comment]
@GeetaSarvadnya can we close this issue if it's irrelevant right now ?

**Comment by GeetaSarvadnya** [comment]
@deeppandya I didn't see any crash when 50 token limit is set on Android, looks good from end. @Uni-verse did you see any crash while testing the adaptive captcha on production on your device?

**Comment by deeppandya** [comment]
Closing the issue as irrelevant.
