### ISSUE TITLE
[Follow up to #28209] "Verified creator" blue checkmark icon is not updated on "Auto-Contribute" pop-up list

### ISSUE THREAD

**Issue by vlad-hoff** [brave/brave-browser#31246]
## Description 

Follow-up to #28209

## Steps to reproduce 

1. Launch Brave 1.53.102
2. Eanble Rewards Staging environment > Enable Rewards > Connect custodian
3. Open at least 6 verified creator's websites > Go to `brave://rewards`
4. Scroll down to `Auto-Contribute` section
5. Tap `Show All` > Observe all blue checkmark

## Actual result 

`Verified creator` blue checkmark icon is not updated on `Auto-Contribute` pop-up list

![Screen_20-54-41](https://github.com/brave/brave-browser/assets/128532965/2a20566e-d658-4d35-92e8-056914616650)

## Expected result

`Verified creator` blue checkmark icon must be updated on each screen

## Issue reproduces how often 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? No
- Can you reproduce this issue with the current Play Store Nightly version? No

## Device details
   - Install type (ARM, x86): Any
   - Device type (Phone, Tablet, Phablet): Phone and Tablet
   - Android version: Any
   
## Brave version

1.53.102

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by deeppandya** [comment]
@zenparsing would you be able to check if it's updated on brave://rewards page ?

**Comment by Miyayes** [comment]
I think fix is in 1.54.x: https://github.com/brave/brave-browser/issues/30817

**Comment by Miyayes** [comment]
Note: brave://rewards is shared between desktop and Android.
