### ISSUE TITLE
Rewards opt in needs a ToS link as part of opt in

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#3124]
When a new user opts in to Brave Rewards, the ToS should be made available as part of the opt in process.

@jenn-rhim please add mock for how the ToS and needed text should be place at opt in.
@NejcZdovc - part of the Brave Rewards spec review flow.

**Comment by mandar-brave** [comment]
Three separate use cases to resolve;
<img width="432" alt="screen shot 2019-02-04 at 2 55 54 pm" src="https://user-images.githubusercontent.com/35932307/52256707-a64cc800-28cc-11e9-86a6-d6d7c497c929.png">

<img width="433" alt="screen shot 2019-02-04 at 2 51 52 pm" src="https://user-images.githubusercontent.com/35932307/52256697-9c2ac980-28cc-11e9-8d89-64fbda8d38ac.png">

![br off](https://user-images.githubusercontent.com/35932307/52256721-b2388a00-28cc-11e9-950f-5ed497446971.png)

**Comment by NejcZdovc** [comment]
@mandar-brave what is the use case for the first screen?

**Comment by LaurenWags** [comment]
Verified passed with:

Brave | 0.65.95 Chromium: 74.0.3729.131 (Official Build) beta(64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2136
* Verified able to opt into Rewards from panel, and both places on brave://rewards
* Logged https://github.com/brave/brave-browser/issues/4489
