### ISSUE TITLE
Some commands you can add shortcuts to are no-ops

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#31244]
@mkarolin found these commands:
```
IDC_FOCUS_THIS_TAB
IDC_SHOW_SETTINGS_RESET_BUBBLE
IDC_TRANSLATE_ORIGINAL_LANGUAGE_BASE
idc_content_clipboard_history_menu
idc_always_on_top
idc_edit_menu
idc_show_srt_bubble
idc_media_router_show_in_toolbar
idc_find_and_edit_menu
```

And I found a few more after digging a bit deeper:

```
IDC_FIND_MENU
IDC_HISTORY_MENU
IDC_BRAVE_VPN_MENU
IDC_PASSWORDS_AND_AUTOFILL_MENU
```

Removing these will reduce the number of strings we need to translate.

Test Plan:
1. Navigate to chrome://settings/system/shortcuts
2. The above commands should not be available.

**Comment by kjozwiak** [comment]
The above requires `1.53.108` or higher for `1.53.x` verification 👍 Labelled as `QA/Test-All-Platforms` just to make sure that all these have been removed so users don't accidently use them on the various platforms.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.53.108 Chromium: 115.0.5790.56 (Official Build) (64-bit)
-- | --
Revision | ebcfb87c1393f36955cfa2f6451a1767e3dc3ee5-refs/branch-heads/5790@{#1193}
OS | Windows 11 Version 22H2 (Build 22621.1848)
```

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave	1.53.108 Chromium: 115.0.5790.56 (Official Build) (64-bit) 
Revision	ebcfb87c1393f36955cfa2f6451a1767e3dc3ee5-refs/branch-heads/5790@{#1193}
OS	Linux
```

1. Install `1.53.108`
2. launched Brave
3. opened `brave://flags`
4. enabled `#bravecommands`
5. clicked Relaunch
6. opened `brave://settings/system/shortcuts`
7. verified commands listed in https://github.com/brave/brave-browser/issues/31244#issue-1770735415 are not shown in brave://settings/system/shortcuts as below:

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
1.53.110
```
