### ISSUE TITLE
Reinstate passkey entitlement

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#31258]
During work on CR115, we discovered that passkey support was added upstream. However, Brave did not have the required passkey entitlement, so we encountered a signature-related error that prevented Brave from launching on Mac. In order to proceed with 115 testing, we temporarily removed the passkey entitlement here: https://github.com/brave/brave-core/commit/dc06648bed4b84cd7e0e2416baa4c608b7ab29d6.

We're currently working to add this entitlement to our provisioning profiles for nightly/dev/beta/release. Once that is done, we should reinstate the passkey entitlement (i.e., revert the above commit) and then verify with QA that we no longer see any signature-related launch errors on Mac.

cc: @bsclifton @rebron

**Comment by kjozwiak** [comment]
The above requires `1.53.110` or higher for `1.53.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress on macOS x64

```
Brave | 1.53.110 Chromium: 115.0.5790.56 (Official Build) (x86_64)
-- | --
Revision | ebcfb87c1393f36955cfa2f6451a1767e3dc3ee5-refs/branch-heads/5790@{#1193}
OS | macOS Version 13.4.1 (Build 22F82)
```

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.53.110 Chromium: 115.0.5790.56 (Official Build) (x86_64)
-- | --
Revision | ebcfb87c1393f36955cfa2f6451a1767e3dc3ee5-refs/branch-heads/5790@{#1193}
OS | macOS Version 11.7.8 (Build 20G1351)

Case 1: x64 .dmg - `PENDING`
<details>

</details>

Case 2: x64 .pkg - `PENDING`
<details>

</details>

Case 3: universal .dmg - `PENDING`
<details>

</details>

Case 4: universal .pkg - `PENDING`
<details>

</details>

**Comment by LaurenWags** [comment]
Verification in progress on macOS arm64 13.4.1:

```
Brave	1.53.110 Chromium: 115.0.5790.56 (Official Build) (arm64) 
Revision	ebcfb87c1393f36955cfa2f6451a1767e3dc3ee5-refs/branch-heads/5790@{#1193}
OS	macOS Version 13.4.1 (Build 22F82)
```

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave	1.53.110 Chromium: 115.0.5790.56 (Official Build) (arm64) 
Revision	ebcfb87c1393f36955cfa2f6451a1767e3dc3ee5-refs/branch-heads/5790@{#1193}
OS	macOS Version 11.7.8 (Build 20G1351)

```

Case 1: arm64 .dmg - `PENDING`
Case 2: arm64 .pkg - `PENDING`
<details>

</details>

Case 3: universal .dmg - `PENDING`
<details>

</details>

Case 4: universal .pkg - `PENDING`
<details>

</details>
