### ISSUE TITLE
Two banners at the same time

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#3125]
## Steps to Reproduce

   1. enable rewards
   2. go to a site and open tip banner
   3. open new window, load a site and open tip banner
   4. banner from step 2 will be updated with banner from site 3
## Actual result:

![image](https://user-images.githubusercontent.com/9574457/51819410-946a9400-22d2-11e9-9f92-b13c0d5e3ad0.png)

Same happens if you open it in one tab and then in another and then come back to the initial tab, banner will be wrong

## Expected result:
banner should be per tab

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc @petemill

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.61.37 Chromium: 73.0.3683.39 (Official Build) beta (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

Used test plan from https://github.com/brave/brave-core/pull/1490

![image](https://user-images.githubusercontent.com/34715963/53371961-f0681d00-3951-11e9-9feb-9fa94f3d3893.png)
