### ISSUE TITLE
Github edit

### ISSUE THREAD

**Issue by Yamura3** [brave/brave-browser#31261]
Hello there, 

i have a portfolio build with github but every time i want to edit it with Brave it crash. I have to edit it with Google and i want to use brave :(

Pls fix this!
Regards Yamura4

**Comment by rebron** [comment]
Hi @Yamura3 closing this one out. 
Can you please file a new issue https://github.com/brave/brave-browser/issues/new?assignees=&labels=OS%2FDesktop&projects=&template=desktop.md&title= 
and use the issue template and provide as much information as you.
