### ISSUE TITLE
AI Chat should not require summarization before user can ask questions about content

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#31268]
## Description 

When the UI Chat panel is opened, users should be able to ask any questions about the page content (or about other topics), and not have to request a summary first.

## Steps to Reproduce

   1. Visit an article in a Tab
   2. Open Chat UI

## Actual result:

Have to click "Summarize" button before can submit free form text

## Expected result:
Can immediately submit free form text

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
Updated milestone to 1.57.x per https://github.com/brave/brave-core/pull/19269
