### ISSUE TITLE
AI Chat should suggest questions

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#31269]
## Description 

AI Chat can pull out important pieces of information to know about in some content. Those could be introduced as short questions that the user can click on to find out more about that area of the content.

Since it will require sending the current article content, it must be initiated by a user action - either on-demand or opting-in to automatic sending _only when the panel is open_.

**Comment by LaurenWags** [comment]
Updated milestone to 1.57.x per https://github.com/brave/brave-core/pull/19269
