### ISSUE TITLE
AI Chat shouldn't fetch page content if the panel is closed and not opted-in

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#31266]
## Description 

In order to verify this, verbose logging would need to be enabled via `--v=0 --vmodule="*ai_chat*"=4`

## Steps to Reproduce

   1. Opt-in to AI Chat
   2. Close the panel
   3. Navigate to new sites

## Actual result:

The code will distill the content from the page

## Expected result:
The code shouldn't distill the content from the page

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
Updated milestone to 1.57.x per https://github.com/brave/brave-core/pull/19269
