### ISSUE TITLE
Confirmation can be lost during request when browser is closed

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#31270]
During confirmation request, the confirmation can be lost when user closes browser

## Steps to Reproduce

1. Clean profile
1. Enable rewards and ads
1. Trigger an ad
1. Close browser(or turn off  ads) during confirmation request ()

## Actual result:

Confirmation is lost

## Expected result:
Confirmation is not lost

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.54.74 Chromium: 115.0.5790.32 (Official Build) nightly (64-bit) 
-- | --
Revision | f9b78cf410ecd5b372310ef25a12ef456c77d90f-refs/branch-heads/5790@{#724}
OS | Ubuntu 18.04 LTS

cc @tmancey @aseren

**Comment by tmancey** [comment]
Closing as issue was resolved by another PR. cc @btlechowski to test on latest nightly (there will always be an opportunity for a confirmation to be lost if it is not saved, but the window of opportunity will be much smaller now)
