### ISSUE TITLE
Portfolio Tokens Disappear While Add Asset Modal is Open

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#31275]
## Description 

The `Portfolio` token list disappears in the background when the `Edit Visible Assets` modal is open

## Steps to Reproduce

   1. Go to the `Portfolio` page and open the `Edit Visible Assets` modal
   2. Observe that the `Portfolio` token list disappears in the background while the modal is open

## Actual result:

https://github.com/brave/brave-browser/assets/40611140/f0305866-1d8b-4b2c-bac8-043b2bb99351

## Expected result:
`Portfolio` token list should not disappear while the `Edit Visible Assets` modal is open

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Yes
- Does the issue resolve itself when disabling Brave Rewards? Yes
- Is the issue reproducible on the latest version of Chrome? Yes

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Linux

- Verified steps from [brave/brave-core#19026](https://github.com/brave/brave-core/pull/19026)
- Verified Portfolio tokens list is retained when Add asset modal is opened

https://github.com/brave/brave-browser/assets/17010094/90f3ce3a-ca34-4d5b-9171-ff6aaed97355

---------------------

**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#19026](https://github.com/brave/brave-core/pull/19026)
- Verified Portfolio tokens list is retained when Add asset modal is opened

https://github.com/brave/brave-browser/assets/17010094/177c264c-1015-4ac0-9f9b-170e569245eb


---------------------

**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (arm64)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | macOS Version 13.4.1 (c) (Build 22F770820d)

- Verified steps from [brave/brave-core#19026](https://github.com/brave/brave-core/pull/19026)
- Verified Portfolio tokens list is retained when Add asset modal is opened

https://github.com/brave/brave-browser/assets/17010094/27116892-b2c8-4dd6-95dc-86d4ba012c55
