### ISSUE TITLE
Brave screen recording all the time?

### ISSUE THREAD

**Issue by frankhart2018** [brave/brave-browser#31278]
## Description 
I recently got the macOS 14 beta 2 (Sonoma), and it shows a notification when screen is being recorded and it shows that Brave is recording my screen when I did not share my screen in any way. I closed brave and it showed me the same thing. Is this a Sonoma issue or does Brave record all the time? 

## Steps to Reproduce

   1. Upgrade to macOS Sonoma beta 2
   2. Open brave
   3. Check the top bar where screen sharing icon shows up

## Reproduces how often: 

- As soon as I turned off the permission to share screen it went away. 

## Brave version (brave://version info)

- 1.52.126 Chromium: 114.0.5735.133 (Official Build) (arm64)

**Comment by Josh4532** [comment]
have the same,  How did you turn permission off

**Comment by harshithmohan** [comment]
> have the same, How did you turn permission off

Settings -> Privacy & Security -> Screen Recording

**Comment by frankhart2018** [comment]
Yeah I had to reboot too.

**Comment by diracdeltas** [comment]
seems like this could be an apple bug. curious if it happens as well with chrome, given the API changes affect them as well. https://bugs.chromium.org/p/chromium/issues/detail?id=1309653

cc @thypon @rebron

**Comment by phocean** [comment]
Yes, same issue with Chrome.

**Comment by rebron** [comment]
We're seeing this same issue in Safari. We can reproduce on a site that uses WebRTC. We still need a few examples of sites where the screen capture API where the screen sharing icon appears unexpectedly.

**Comment by rebron** [comment]
We should consider UI for when webrtc is first used explaining why the icon shows up for this version of macOS.

**Comment by Saoiray** [comment]
@rebron can we circle back around to this? It's labeled as an upstream issue but it supposed was **Fixed (Closed)** according to https://bugs.chromium.org/p/chromium/issues/detail?id=1309653

This has been brought up by a few people recently at https://community.brave.com/t/why-is-brave-browser-capturing-my-screen/510814/6 and also https://www.reddit.com/r/brave_browser/comments/179yqoc/i_never_gave_screen_recordingcamera_and_mic/

**Comment by Saoiray** [comment]
Sorry, addendum. Linked the chromium in above comment because I saw it above. But also see @Brave-Matt mentioned https://bugs.chromium.org/p/chromium/issues/detail?id=1457180 on the Community topic, so perhaps that's the open and related one? Not sure how they are linked. 

But regardless, just verifying if any fix is in sight and if is pretty much low priority and waiting for upstream? Thanks.

**Comment by rebron** [comment]
This is the related issue https://bugs.chromium.org/p/chromium/issues/detail?id=1309653 and we'll also be rolling out the fix soon via griffin.

**Comment by sofinico** [comment]
<img width="440" alt="screenshot" src="https://github.com/brave/brave-browser/assets/36451685/1a047484-ccb8-4326-b32b-e26a00d46d5e">

**Comment by thypon** [comment]
This has been fixed upstream

**Comment by bsclifton** [comment]
We're getting a report of this again- asking for more info

Brave employees can see here for more info:
https://bravesoftware.slack.com/archives/C01EVLWS8R5/p1750787461930639

**Comment by bsclifton** [comment]
Looks like this was reported upstream with https://issues.chromium.org/issues/418310536

**Comment by Invinciblebond** [comment]
i have the same issue and its 2026

<img width="540" height="498" alt="Image" src="https://github.com/user-attachments/assets/979a2aa0-36e3-4051-8d12-23d27dde407c" />
