### ISSUE TITLE
Unable to upload the images in imgur.com

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#3128]
## Description 

Unable to upload the images in imgur.com

## Steps to Reproduce

   1. Clean profile 0.58.21
   2. Upload any image
   3. It takes lot of time to process the request and never upload the image

## Actual result:

Unable to upload the images

Shield Enabled:

![image](https://user-images.githubusercontent.com/38657976/51823666-0ad4b980-2306-11e9-933b-e90fb4b95544.png)

Shield disabled:

![image](https://user-images.githubusercontent.com/38657976/51824331-fa254300-2307-11e9-8508-a2563b1c0048.png)

## Expected result:
Able to upload the image

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 0.58.21 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? no
- Is the issue reproducible on the latest version of Chrome? no

### Additional Information

Issue is reported by community user:
https://community.brave.com/t/uploading-images-to-imgur/43491

**Comment by srirambv** [comment]
Works fine on Linux with shields up as well.

**Comment by kjozwiak** [comment]
@GeetaSarvadnya looks like you used `0.58.21 Chromium: 71.0.3578.98 (Official Build) (64-bit)` as per your original comment. Does this reproduce for you using `0.59.31 Chromium: 72.0.3626.71`?

I couldn't reproduce the issue on `macOS 10.14.2 x64` using default shield settings with the following build:

Brave | 0.59.31 Chromium: 72.0.3626.71 (Official Build) (64-bit)
-- | --
Revision | f52ccad2a6a3c65fc9e0c591a517ceab1198dac0-refs/branch-heads/3626@{#763}
OS | Mac OS X

I also attempted to reproduce the issue with `0.58.21 Chromium: 71.0.3578.98` but couldn't reproduce the issue either.

**Comment by kjozwiak** [comment]
BTW, couldn't reproduce on my Win 10 x64 laptop using `0.58.21 Chromium: 71.0.3578.98` and `0.59.31 Chromium: 72.0.3626.71`.

@LaurenWags @btlechowski can you guys check your Win VM's and see if you can reproduce?

**Comment by rebron** [comment]
cc: @GeetaSarvadnya can you try again with 59.34?

**Comment by GeetaSarvadnya** [comment]
@kjozwiak @LaurenWags Thanks for checking.

**Comment by GeetaSarvadnya** [comment]
@rebron https://github.com/brave/brave-browser/issues/3128#issuecomment-459842065 - I will test it again today and update the Appropriate comments. Thanks!

**Comment by GeetaSarvadnya** [comment]
Tested again the issue using `0.59.35` - I am not seeing any issues, image uploaded successfully. Hence closing the issue.
