### ISSUE TITLE
[Commands]: New commands for grouping and closing

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#31298]
After talking with @rebron in Slack we came up with a few more commands which might be useful:
1. Add origin to group (adds all tabs in an origin to a new group)
2. Move group to new window (moves all tabs in a group to a new window)
3. Close duplicate tabs (closes all tabs on the same origin)

Test Plan:
1. Search in chrome://settings/system/shortcuts for `Move group to new window`, `Close duplicate tabs`, `Toggle vertical tabs expanded` and `Group tabs on current origin`.
2. The commands should be triggerable (either via a new shortcut, or by the command palette, if chrome://flags#quick-commands is enabled).

**Comment by fallaciousreasoning** [comment]
We're just giving people the ability to use them :smile: No default shortcuts here

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.58.91 Chromium: 116.0.5845.96 (Official Build) beta (x86_64)
-- | --
Revision | 620fa9c0307b294dd6e7c6b0976bc1f93fecf369
OS | macOS Version 14.0 (Build 23A5312d)
