### ISSUE TITLE
Build out Wallet Panel V2 Header

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#31300]
## Description 

We need to build out the Wallet `Panel V2` Header.

![Screenshot 8](https://github.com/brave/brave-browser/assets/40611140/572ac3bb-4181-4e70-8d85-173f6082b9a7)

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.58.109 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Linux

- Verified steps from [brave/brave-core#19051](https://github.com/brave/brave-core/pull/19051)
- Verified Panel V2 is as per design

https://github.com/brave/brave-browser/assets/17010094/fa09b8a1-d19f-4091-98aa-df957bf6e8c8

---------------------

**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build)) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#19051](https://github.com/brave/brave-core/pull/19051)
- Verified Panel V2 is as per design

https://github.com/brave/brave-browser/assets/17010094/ce7ca7f4-34ec-4fd3-842b-8ba7af8c8175

---------------------

**Verification passed on**

Brave | 1.57.27 Chromium: 115.0.5790.114 (Official Build) beta (arm64)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | macOS Version 13.4.1 (c) (Build 22F770820d)

- Verified steps from [brave/brave-core#19051](https://github.com/brave/brave-core/pull/19051)
- Verified Panel V2 is as per design
