### ISSUE TITLE
AI Chat should only be useable in nightly

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#31302]
The entire AI Chat feature should, for now, only be useable from Nightly (or local)

## Test plan
0. When on a non-nightly build...
1. Verify -> AI Chat does not appear in brave://flags
2. Verify -> AI Chat does not appear on the sidebar

**Comment by LaurenWags** [comment]
@brave/qa-team this requires `1.57.10` or higher for `1.57.x` verification

**Comment by stephendonner** [comment]
## Verification `PASSED` using 

Brave | 1.57.16 Chromium: 115.0.5790.98 (Official Build) beta (x86_64)
-- | --
Revision | d6c8a44fbe78ae6ee53d838307b4d17bec8de940
OS | macOS Version 11.7.8 (Build 20G1351)

### Steps:
1. installed `1.57.16`
2. launched Brave
3. opened `brave://flags`
4. typed `ai chat` (and substrings)
5. confirmed `Brave AI Chat` doesn't appear, as it does in `nightly`
6. checked the sidebar items

### Confirmed there was no `Brave AI` button on the sidebar

`1.57.16` | `nightly`
---------|---------
<img width="1312" alt="Screen Shot 2023-07-18 at 1 38 40 PM" src="https://github.com/brave/brave-browser/assets/387249/b114c94b-2754-437a-bfe2-da1e8b142bea"> | <img width="1290" alt="Screen Shot 2023-07-18 at 1 38 04 PM" src="https://github.com/brave/brave-browser/assets/387249/36c70b15-0005-407f-bcc9-32b4b85984c1">
