### ISSUE TITLE
Market Tab not loading Data

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#31301]
## Description 

The `Market` tab is currently not loading any data on `Nightly`

## Steps to Reproduce

   1. Open the `Wallet` and nav to the `Market` tab
   2. No market data is loaded

## Actual result:

https://github.com/brave/brave-browser/assets/40611140/39ecd6f0-dac1-4852-aaba-ee628e628dee

## Expected result:
Should load market data

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by nvonpentz** [comment]
Related to https://github.com/brave/anon-proxy/pull/38
