### ISSUE TITLE
NFT Details is Broken Wallet Panel V2

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#31314]
## Description 

The `NFT Details` tab is broken in the Wallet `Panel V2`, we need to add permissions to load NFT iframe meta-data to the brave://wallet-panel.top-chrome/ origin.

![Screenshot 11](https://github.com/brave/brave-browser/assets/40611140/0120d778-ae88-4f41-ac8e-421cec6d1807)

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Linux

- Verified steps from [brave/brave-core#19196](https://github.com/brave/brave-core/pull/19196)
- Verified NFT details work as expected on Wallet Panel V2
- Encountered [#32753](https://github.com/brave/brave-browser/issues/32753) & [#32754](https://github.com/brave/brave-browser/issues/32754)


https://github.com/brave/brave-browser/assets/17010094/eca4d7c2-a8d6-4f61-852b-2fb9dbf97bc3

---------------------

**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#19196](https://github.com/brave/brave-core/pull/19196)
- Verified NFT details work as expected on Wallet Panel V2
- Encountered [#32753](https://github.com/brave/brave-browser/issues/32753) & [#32754](https://github.com/brave/brave-browser/issues/32754)


https://github.com/brave/brave-browser/assets/17010094/030b449c-fb2d-40e6-ae18-accedf5aef8b

---------------------

**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (arm64)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | macOS Version 13.4.1 (c) (Build 22F770820d)

- Verified steps from [brave/brave-core#19196](https://github.com/brave/brave-core/pull/19196)
- Verified NFT details work as expected on Wallet Panel V2
- Encountered [#32753](https://github.com/brave/brave-browser/issues/32753) & [#32754](https://github.com/brave/brave-browser/issues/32754)

https://github.com/brave/brave-browser/assets/17010094/392176fe-76a6-41aa-b07b-b6649935fb6e
