### ISSUE TITLE
Market Tab is Broken Wallet Panel V2

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#31313]
## Description 

The `Market` tab is broken in the Wallet `Panel V2`, we need to add permissions to load market iframe data to the brave://wallet-panel.top-chrome/ origin.

![Screenshot 13](https://github.com/brave/brave-browser/assets/40611140/df716991-7de6-46cf-b5d5-3cd8fe3a9005)

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Linux

- Verified steps from [brave/brave-core#19129](https://github.com/brave/brave-core/pull/19129)
- Verified Market tab works as expected in Wallet Panel V2
- Encountered [#32749](https://github.com/brave/brave-browser/issues/32749) & [#32750](https://github.com/brave/brave-browser/issues/32750)

https://github.com/brave/brave-browser/assets/17010094/b8baf15a-77bc-4bcc-89d3-9a3123f34dfb

---------------------

**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#19129](https://github.com/brave/brave-core/pull/19129)
- Verified Market tab works as expected in Wallet Panel V2
- Encountered [#32749](https://github.com/brave/brave-browser/issues/32749) & [#32750](https://github.com/brave/brave-browser/issues/32750)

https://github.com/brave/brave-browser/assets/17010094/fb4a9e68-e308-4c02-8624-35be537d04bc

---------------------

**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (arm64)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | macOS Version 13.4.1 (c) (Build 22F770820d)

- Verified steps from [brave/brave-core#19129](https://github.com/brave/brave-core/pull/19129)
- Verified Market tab works as expected in Wallet Panel V2
- Encountered [#32749](https://github.com/brave/brave-browser/issues/32749) & [#32750](https://github.com/brave/brave-browser/issues/32750)

https://github.com/brave/brave-browser/assets/17010094/fa664ef1-9d04-4f9f-96a2-f44616c0a4d1
