### ISSUE TITLE
Add Media Queries to Activity Page for Panel V2

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#31316]
## Description 

We need to clean up and and add `Media Queries` to the `Activity` page for `Panel V2`

![Screenshot 12](https://github.com/brave/brave-browser/assets/40611140/5fbc6011-5833-41b5-8526-a31653879049)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.61.85 Chromium: 119.0.6045.163 (Official Build) beta (64-bit)
-- | --
Revision | 5e2736df90772dd1b66ca5013e47c1fc467c9762
OS | Windows 11 Version 23H2 (Build 22631.2715)

- Verified steps from [brave/brave-core#20461](https://github.com/brave/brave-core/pull/20461)
- Verified `Submitted`, `Confirmed` and `Unapproved` state is shown correctly on all transactions in Activity tab on both panel and full wallet view
- Verified on Activity tab on panel, clicking on a transaction shows the `Details` 
- Verified all status is shown correctly in `Details` view of a transaction

https://github.com/brave/brave-browser/assets/17010094/db45508b-6ef0-462a-9b35-f1e72d1e6a88
