### ISSUE TITLE
Rewards panel shows Summary when windowId is undefined

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#3133]
## Description 
Logging on behalf of @jonathansampson 

As mentioned in Slack, @jonathansampson experienced the Rewards panel not displaying publisher info (unverified status, ability to tip) when windowId is undefined.

## Steps to Reproduce
unknown at this time

## Actual result:
![image 9](https://user-images.githubusercontent.com/28145373/51852931-24213a00-22f5-11e9-8e8b-45b91baadc93.png)

## Expected result:
![image 10](https://user-images.githubusercontent.com/28145373/51852943-2a171b00-22f5-11e9-83aa-1e6a4f5d5e4b.png)

## Reproduces how often: 
unsure

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information
cc @jonathansampson to add additional details and information

**Comment by eljuno** [comment]
+1 from Community https://community.brave.com/t/brave-rewards-problems/44032?u=eljuno

> when Brave Shield is activated, I can’t donate BAT. ... but when I deactivate Brave Shield, and reload the page, I can donate BAT.

**Comment by NejcZdovc** [comment]
closing as stale
