### ISSUE TITLE
Move IPFS banner to NFT tab

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#31332]
Move IPFS banner from portfolio to NFT tab section(It should only be visible when the users selects NFTs in the switch.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.58.105 Chromium: 116.0.5845.114 (Official Build) beta (64-bit)
-- | --
Revision | 5a895596bcd7fcd930dab0714ea5cfa86c5aa0a7
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#19061](https://github.com/brave/brave-core/pull/19061)
- Verified IPFS banner is only shown on NFT tab
- Encountered [#32522](https://github.com/brave/brave-browser/issues/32522)


https://github.com/brave/brave-browser/assets/17010094/055ac133-f32d-42e8-9a7f-bb529c0c286c
