### ISSUE TITLE
can't manually install a newer beta build because the installer says I have a newer build already installed

### ISSUE THREAD

**Issue by joejoejo** [brave/brave-browser#31343]
Description:
I can’t install a newer version of the beta builds because it says I have a newer version than the one I am trying to update to. I normally use the standalone full update file to install the newer beta build unless the internal updater says there is a newer build and is installing it.

Steps to Reproduce
1. Download and install Version 1.54.76 beta for Windows.
2. Downloads and installs a newer beta build.
3. It will give you an error saying that you have a newer build of Brave.

Actual result:
![Screenshot 2023-06-27 091351](https://github.com/brave/brave-browser/assets/5640119/3d08358a-63b7-45e6-872d-2b75cb09f311)

Expected result:
Should allow you to install the newer build.

Reproduces how often:

Every time for the last week or so

Brave version (brave://version info)
1.54.76 Chromium: 115.0.5790.32 (Official Build) beta (64-bit)

Version/Channel Information:
- Can you reproduce this issue with the current release?
Not enough versions in v1.53
- Can you reproduce this issue with the beta channel?
This is the beta version I am referring to.
- Can you reproduce this issue with the nightly channel?
Not that I can find

Other Additional Information:
I don't know if the internal updater that can be accessed via brave://settings/help has the same issue right now because sometimes it takes days for it to say there is a new beta build even though there have been many beta builds released between the one installed and the one it picked up as newer and installs.
- Does the issue resolve itself when disabling Brave Shields?
N/A
- Does the issue resolve itself when disabling Brave Rewards?
N/A
- Is the issue reproducible on the latest version of Chrome?
N/A

**Comment by bsclifton** [comment]
Seems this is a reoccurrence of https://github.com/brave/brave-browser/issues/1855

**Comment by bsclifton** [comment]
@joejoejo sorry you didn't get a prompt response - but if you're still using Brave, does this still happen?

**Comment by joejoejo** [comment]
This does not happen anymore

**Comment by bsclifton** [comment]
Awesome, huge thanks for confirming! 😄 The similar issue I had found seems to have been fixed. I do remember seeing fixes (upstream in Chromium) to the mini-installer which should have been where this was happening. I'll go ahead and close this out
