### ISSUE TITLE
Corrupted auto-contribute table

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#3134]
Sometimes a-c table gets corrupted. 

## Steps to Reproduce

   1. Clean profile
   2. Enable rewards
3. Change `Minimum page time before logging a visit` to 5 in a-c table settings    
4. Open `https://kjozwiak.github.io/` and wait 7 seconds
5. Restart the browser
6. Open `https://kjozwiak.github.io/` and wait 7 seconds
7. check `publisher_info_db`

## Actual result:

auto-contribute table becomes corrupted
Not able to add sites to ledger
`score` for `https://kjozwiak.github.io/` in `publisher_info_db` is negative

![image](https://user-images.githubusercontent.com/34715963/51859649-edb8de80-2337-11e9-94b7-bbb6b1129903.png)

![3134](https://user-images.githubusercontent.com/34715963/51866343-0e3d6480-2349-11e9-9696-a8c3073e1165.gif)

[publisher_info_db.zip](https://github.com/brave/brave-browser/files/2804468/publisher_info_db.zip)

## Expected result:
ac table is not curropted

## Reproduces how often: 

100% reproduction rate

## Brave version (brave://version info)

Brave | 0.59.30 Chromium: 72.0.3626.71 (Official Build) (64-bit)
-- | --
Revision | f52ccad2a6a3c65fc9e0c591a517ceab1198dac0-refs/branch-heads/3626@{#763}
OS | Windows 7

cc @brave/legacy_qa @NejcZdovc

**Comment by NejcZdovc** [comment]
let's re-test this one after https://github.com/brave/brave-core/pull/1457 and https://github.com/brave/brave-core/pull/1399 lands

**Comment by kjozwiak** [comment]
@NejcZdovc this seems pretty bad. Both @btlechowski and @GeetaSarvadnya reproduced this issue after upgrading. When it happens, they both mentioned that new websites are not being added into the `a-c` table and the % are not being recalculated when revisiting publishers that are already in the table.

@LaurenWags attempting to reproduce on macOS right now. I'm going to try reproducing on Win to see if this is a Win related issue or a general problem.

**Comment by LaurenWags** [comment]
Reproduced a corrupted a-c table with these steps (thanks @GeetaSarvadnya !):
1. installed 0.58.21
2. Enable rewards and restore wallet which has balance
3. Change `Auto-Contribute Settings` default settings for page time and visit( I have set 5seconds and 1 visit)
4. Add few sites - added 6 sites ( Verified + non verified sites)
5. Tip a site and close the browser
6. Install 0.59.31
7. Visit the same sites in the a-c table - I visited the site I tipped --> attention % rate is not increased
8. Attempt to add a new site to a-c table --> site not added to a-c table

When I look at `publisher_info_db` the site I visited in steps 7 and 8 have negative score values:
![screen shot 2019-01-28 at 2 54 31 pm](https://user-images.githubusercontent.com/28145373/51862440-a537fb80-230c-11e9-8ad5-c5f719976b4d.png)

**Comment by LaurenWags** [comment]
Reproduced a corrupted a-c table when updating from 0.58.18 --> 0.58.21 as well. These were my steps:
1. installed 0.58.18
2. Enable rewards and restore wallet which has balance
3. Change `Auto-Contribute Settings` default settings for page time and visit( I have set 5seconds and 1 visit)
4. Add few sites - added 6 sites ( Verified + non verified sites)
5. Tip a site.
6. Navigate to brave://settings/help to trigger update check. Relaunch after update is downloaded.
7. Visit the same sites in the a-c table --> attention % rate is not increased
8. Attempt to add a new site to a-c table --> first site visited is added to a-c table with 0%, second site visited is not added to a-c table at all.

When I look at publisher_info_db the site I visited in steps 7 and 8 have negative score values:
![screen shot 2019-01-28 at 3 08 41 pm](https://user-images.githubusercontent.com/28145373/51863282-9f431a00-230e-11e9-9eaa-02f2abe5abe1.png)

**Comment by LaurenWags** [comment]
Quicker repro steps:
1. Install Brave (I was using 0.58.21), enable rewards
2. Change Auto-Contribute Settings default settings for page time (change from 8s to 5s)
3. Add a few sites (I used clifton.io, ddg, google)
4. Close and relaunch Brave
5. Visit a site already in a-c table --> attention % does not change
6. Visit a new site (it was added with 0%)
![screen shot 2019-01-28 at 3 44 14 pm](https://user-images.githubusercontent.com/28145373/51865176-99036c80-2313-11e9-8429-06c5c287f77a.png)

**Comment by btlechowski** [comment]
I updated the main issue with reliable STR. Thanks @GeetaSarvadnya and @LaurenWags !

**Comment by kjozwiak** [comment]
Thanks @LaurenWags @btlechowski @GeetaSarvadnya 👍

Labelled this as a blocker and it will put users in a bad state whenever they update any of the `a-c` settings. Once you get into the above state, new publishers won't be added into the `a-c` table and old publishers that are already in the `a-c` table won't be updated correctly.

I'm not 100% sure how many users actually play around with the `a-c` settings but whoever does will most likely get into the above state. We should probably fix this as we don't need anymore users in bad states.

@NejcZdovc when you take a look at this one, can you also check if there's a way to fix users who might be in this broken state?

**Comment by Sh1d0w** [comment]
FYI This bug is present in the official release 0.58.21. I've been observing it for at least two weeks without being able to contribute to a verified websites, which still shows as unverified.

Thought it was related to https://github.com/brave/brave-browser/issues/2816#issuecomment-458271799 so I've reported it there.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.59.33 Chromium: 72.0.3626.81 (Official Build) (64-bit)
-- | --
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS | Mac OS X

* Verified STR on clean profile does not cause issue 
* Verified when a profile (from 0.58.21) with issue as described is updated to 0.59.33, and a new site is visited, has the table correctly displayed (no sites lost, % values are accurate, weights in `publisher_info_db` are accurate)
* Verified when a profile (from 0.58.21) without the issue as described is updated to 0.59.33 and a new site is visited has the table correctly displayed (no sites lost, % values are accurate, weights in `publisher_info_db` are accurate)
