### ISSUE TITLE
Add grouping to NFT tab

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#31342]
NFT tab filters should allow a user to group tokens by Accounts or Networks.

Test plan:
1. Select NF tab in Portfolio Overview
2. Click on filter icon
3. In the filter modal select group by network or account and save the filters
4. NFT should be grouped by the selected criteria

https://github.com/brave/brave-browser/assets/48117473/1548a922-a047-4c60-bc06-fcbb84fc70a3

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.58.105 Chromium: 116.0.5845.114 (Official Build) beta (64-bit)
-- | --
Revision | 5a895596bcd7fcd930dab0714ea5cfa86c5aa0a7
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#19066](https://github.com/brave/brave-core/pull/19066)
- Verified able to group NFTs by network or accounts or none as default

https://github.com/brave/brave-browser/assets/17010094/bf4fbbf2-490c-4885-9a49-9e6cf92eacc2
