### ISSUE TITLE
Group By Filter Option missing on Portfolio Assets Tab

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#31350]
## Description 

The `Group By` filter option is missing on Portfolio `Assets` Tab

## Steps to Reproduce

   1. Go to the `Portfolio` tab
   2. Open the `Filters and display settings`
   3. The `Group By` option is missing

## Actual result:

https://github.com/brave/brave-browser/assets/40611140/06ddee98-93a6-4b4e-9242-33dfa6b10825

## Expected result:
The `Group By` filter option should be available for both `Assets` and `NFTs` tabs.

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Linux

- Verified steps from [brave/brave-core#19075](https://github.com/brave/brave-core/pull/19075)
- Verified Group by filter option is available for Portfolio
- Verified able to group by portfolio either by accounts or by network

https://github.com/brave/brave-browser/assets/17010094/0a00360b-a199-4859-9f73-f7fb243f9fa2


---------------------

**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#19075](https://github.com/brave/brave-core/pull/19075)
- Verified Group by filter option is available for Portfolio
- Verified able to group by portfolio either by accounts or by network

https://github.com/brave/brave-browser/assets/17010094/ffad3a37-c552-4c41-a503-62dbfbe2e8b5

---------------------

**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (arm64)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | macOS Version 13.4.1 (c) (Build 22F770820d)

- Verified steps from [brave/brave-core#19075](https://github.com/brave/brave-core/pull/19075)
- Verified Group by filter option is available for Portfolio
- Verified able to group by portfolio either by accounts or by network

https://github.com/brave/brave-browser/assets/17010094/07d2698b-b43d-405a-a2bd-2570d31550b5
