### ISSUE TITLE
Remove Chrome branding from close all tabs prompt

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#31354]
## Description 
Remove Chrome branding from close all tabs prompt

## Steps to reproduce 

   1. Open tab tray
   2. Select close all tabs from menu
   3. Prompt shows Chrome main menu

## Actual result 
![Screenshot_2023-06-27-22-46-41-883_com brave browser_beta](https://github.com/brave/brave-browser/assets/17010094/2863b144-4510-4db7-926b-97106ad3e948)

## Expected result
No Chrome branding

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 13
   
## Brave version
All

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc: @samartnik @vlad-hoff @Uni-verse @kjozwiak

**Comment by kjozwiak** [comment]
Nice catch @srirambv. Looks like we had a duplicate via https://github.com/brave/brave-browser/issues/30613 which was just uplifted into `1.53.x` via https://github.com/brave/brave-core/pull/19085. Closing this one as `closed/duplicate`.
