### ISSUE TITLE
[Shortcuts]: Mark some shortcuts as unmodifiable on MacOS

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#31353]
Many shortcuts on MacOS are managed via the System and can be configured there. When the Brave shortcuts disagree with the system shortcuts, the system one wins out (this is desirable, as it lets MacOS users modify the shortcuts in a way they're familiar with).

We should update the the shortcuts page to list, but not allow editing of these shortcuts on MacOS, as the system shortcuts CANNOT be removed from commands.

## Test Plan
1. Navigate to brave://settings/system/shortcuts (on MacOS)
2. Try removing a shortcut visible in the menus (i.e. Ctrl+T for new tab). It should not be possible
3. Try adding CTRL+T to another command. It should not be possible.
4. It should be possible to add additional shortcuts to these commands (i.e. it should be possible to add an Alt+P shortcut to new tab).

**Comment by kjozwiak** [comment]
The above requires `1.53.110` or higher for `1.53.x` verification 👍

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.53.110 Chromium: 115.0.5790.56 (Official Build) (x86_64)
-- | --
Revision | ebcfb87c1393f36955cfa2f6451a1767e3dc3ee5-refs/branch-heads/5790@{#1193}
OS | macOS Version 11.7.8 (Build 20G1351)
```

### Steps:
1. installed `1.53.110`
2. launched Brave
3. set `brave://flags/#brave-commands` to `Enabled`
4. clicked `Relaunch`
5. opened `brave://settings/`
6. clicked on `System`
7. clicked on `Shortcuts`
8. ensured you cannot re-bind system-default keyboard shortcuts

`1.55.80`



command + T | command + P | command + V | command + ] | new shortcut
---------------|--------------|----------------|-------------|---------------
<img width="1408" alt="Screen Shot 2023-07-05 at 4 29 54 PM" src="https://github.com/brave/brave-browser/assets/387249/714ee2cd-a986-428f-ad27-a34bff7c8081">
