### ISSUE TITLE
Hide local network assets when local networks are disabled (Crash)

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#31357]
## Description 
Hide local network assets when local networks are disabled, could cause a crash like https://github.com/brave/brave-browser/issues/31303
Local networks are disabled in all GPS versions.

## Actual result 
[network-crash.webm](https://github.com/brave/brave-browser/assets/11755381/ca74dcb7-23d7-44b2-8bf0-4b0657204be7)

## Expected result
Local network assets should be hidden when local networks are disabled.

## Issue reproduces how often 
easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Y
- Can you reproduce this issue with the current Play Store Beta version? Y
- Can you reproduce this issue with the current Play Store Nightly version? Y

**Comment by kjozwiak** [comment]
The above requires `1.52.130` or higher for `1.52.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.52.130 x64 build

- Verified steps from [brave/brave-core#19113](https://github.com/brave/brave-core/pull/19113)
- Verified localhost network is not listed in the GPS build for any network

https://github.com/brave/brave-browser/assets/17010094/4738d8f4-3f0e-4226-9d56-2ffa4fc17e6e
