### ISSUE TITLE
YT creators are not appear in Brave Panel

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#3135]
## Steps to Reproduce

   1. Open any YT link
   2. Open Brave Panel

## Actual result:

Nothing appear there related to the YT channel creator

## Expected result:
YT channel creator info appear for verified creators and YT icon for non verified

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.61.37 Chromium: 73.0.3683.39 (Official Build) beta (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

![image](https://user-images.githubusercontent.com/34715963/53367823-6d41c980-3947-11e9-8f92-8e8a89ce77e1.png)
![image](https://user-images.githubusercontent.com/34715963/53368112-2d2f1680-3948-11e9-9a86-2365f1a3a21b.png)
