### ISSUE TITLE
Follow up of # PR 18834 - The tabs opened in PT and TOR windows are not considered for the metrics response calculation

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#31367]
## Description 

Found while testing https://github.com/brave/brave-core/pull/18834
Follow up of # PR 18834 - Follow up of # PR 18834 - The tabs opened in PT and TOR windows are not considered for the metrics response calculation
## Steps to Reproduce

1. Clean profile `1.55.17`
2. Enable vertical tabs view
3. Add 7 sites in 7 tabs
4. Confirm that the metrics `Brave.VerticalTabs.OpenTabs` response value is `2` as expected
5. Open a PT window and add two tabs with sites loaded
6. Open a TOR window and add two tabs with sites loaded
7. Number tabs in all the 3 window types (Regular, PT and TOR window) is 11
8. Reload brave://local-state file
9. The metrics `Brave.VerticalTabs.OpenTabs` response value is `2` instead of `3`
10. If we look at the metrics `Brave.Core.TabCount` it gives the correct reponse when tab count is `7` and `11`
  
## Actual result:

The tabs opened in PT and TOR windows are not considered for the metrics response calculation

## Expected result:
Tabs opened in all the window types needs to be considered for the metrics response calculation

## Reproduces how often: 

<html>
<body>

Brave | 1.55.17 Chromium: 115.0.5790.40 (Official Build) nightly (64-bit)
-- | --
Revision | 071c9ddea889c3c7887daf4eac13fed72d4fff62-refs/branch-heads/5790@{#979}
OS | Windows 10 Version 22H2 (Build 19045.3086)

</body>
</html>
## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @DJAndries @mattmcalister @rebron

**Comment by GeetaSarvadnya** [comment]
Please note that the issue is reproducible for the metrics `Brave.VerticalTabs.GroupTabs` and `Brave.VerticalTabs.PinnedTabs` also. The pinned and grouped tabs are not considered for the metrics repsonse calculation. I have just logged a common issue, while fixing this issue, these two metrics response needs to be fixed. 
cc: @DJAndries

**Comment by DJAndries** [comment]
This is expected. We do not monitor Private Tab/Tor window usage for all P3A questions.
