### ISSUE TITLE
Follow up of # PR 18834 - Incorrect response for the metrics Brave.VerticalTabs.PinnedTabs when tabs are pinned and unpinned

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#31365]
## Description 

Found while testing https://github.com/brave/brave-core/pull/18834
Follow up of # PR 18834 - Incorrect response for the metrics Brave.VerticalTabs.PinnedTabs when tabs are pinned and unpinned
## Steps to Reproduce

   1. Clean profile 1.55.17
   2. Open brave://local-state 
   3. Right click on the brave://local-state tab, select `Use vertical tabs` context menu option
   4. Pin the tab on the vertical tab view
   5. Open another 5 tabs and open sites in the tabs
   6. Pin the 5 tabs, confirmed that total 6 tabs are pinned including brave://local-state
   7. Reload brave://local-state file
   8. Confirm that the metrics `Brave.VerticalTabs.PinnedTabs` response value is `2` as expected
   9. Unpin the 3 tabs and ensure that only 3 tabs are pinned
   10. Reload brave://local-state file
   11. The metrics `Brave.VerticalTabs.PinnedTabs` response value is `2` instead of `1`
   

## Actual result:

Incorrect response for the metrics Brave.VerticalTabs.PinnedTabs when tabs are pinned and unpinned

## Expected result:
correct response should be shown for the metrics `Brave.VerticalTabs.PinnedTabs` when tabs are pinned and unpinned

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.55.17 Chromium: 115.0.5790.40 (Official Build) nightly (64-bit)
-- | --
Revision | 071c9ddea889c3c7887daf4eac13fed72d4fff62-refs/branch-heads/5790@{#979}
OS | Windows 10 Version 22H2 (Build 19045.3086)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @DJAndries @mattmcalister

**Comment by DJAndries** [comment]
This is expected. The metric is supposed to report the max amount of tabs for the past week: "As a user with vertical tabs enabled and had at least one pinned tab this week, what is the **max amount** of pinned tabs this week?"

**Comment by GeetaSarvadnya** [comment]
@DJAndries Verifie the metrics `Brave.VerticalTabs.OpenTabs`, `Brave.VerticalTabs.PinnedTabs` and `Brave.VerticalTabs.GroupTabs`


I have set the sys date to 19th June (starting day of the week) and verified the metrics as below

1. Set sys date to 19th June
2. Clean profile `1.55.1`
3. Open brave://local-state file, right click on the tab and select `Use vertical tab` context menu
4. Open 5 more tabs and pin all the tabs including brave://local-state file
5. Reload brave://local-state file
6. The metrics `Brave.VerticalTabs.PinnedTabs` response value is `2` as expected
7. Unpin 3 tabs and reload brave://local-state file and enured metrics response value is still `2`
8. Fwd the sys clock ahead by 8 days (i.e 26th June in my case)
9. Reload brave://local-state file
**Actual**: The metrics `Brave.VerticalTabs.PinnedTabs` response value is `1` which is correct, but I am getting value after a week, as per the decsription in https://github.com/brave/brave-browser/issues/30928#issue-1748831549 
`As a user with vertical tabs enabled and had at least one pinned tab this week, what is the max amount of pinned tabs this week?` the response `1` should be shown on 25th June instead of 26th June. Could you review this case and let me know your thoughts? Thanks!

**Comment by DJAndries** [comment]
A couple questions:

- Are you restarting the browser after step 8?
- Could it be that the answer is 1 because you still have 3 tabs pinned after 8 days?

**Comment by GeetaSarvadnya** [comment]
>Are you restarting the browser after step 8?

Yes, I did restart the browser after setting the system date ahead

> Could it be that the answer is 1 because you still have 3 tabs pinned after 8 days?

yes it could be but the description says `As a user with vertical tabs enabled and had at least one pinned tab this week, what is the max amount of pinned tabs this week?` - In a week if we update the pin tabs e.g Pin 6 tabs and then unpin 3 tabs, the latest event response is not captured which is not correct

**Comment by DJAndries** [comment]
> yes it could be but the description says As a user with vertical tabs enabled and had at least one pinned tab this week, what is the max amount of pinned tabs this week? - In a week if we update the metrics twice e.g 1. Pin 6 tabs and then 2. unpin 3 tabs, the latest event response is not captured in the same week which is not correct

The metric is meant to measure the max total amount of active pinned tabs in a given week, rather than the action of pinning a tab.

**Comment by GeetaSarvadnya** [comment]
>The metric is meant to measure the max total amount of active pinned tabs in a given week, rather than the action of pinning a tab.

In this case, the pinned max count is 2 (6 tabs pinned) is the correct response? even if we unpin 3 tabs after that in the same week

**Comment by DJAndries** [comment]
You had 6 tabs pinned, and unpinned 3 tabs. The max for the first week is 6 tabs. Next week you launched the browser with 3 pinned tabs remaining, the max amount of tabs for that given week is 3, so you should expect the answer `1`.

**Comment by GeetaSarvadnya** [comment]
As per the above comments closing the issue as expected.
