### ISSUE TITLE
Add Media Queries to Filters and Display Settings Modal

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#31360]
## Description 

We need to clean up and and add `Media Queries` to the `Filters and Display Settings` modal for `Panel V2`

![Screenshot 20](https://github.com/brave/brave-browser/assets/40611140/d0818939-3ce6-4f8c-a36c-c014411c6914)

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Linux

- Verified steps from [brave/brave-core#19089](https://github.com/brave/brave-core/pull/19089)
- Verified Portfolio filter is shown correctly in V2 panel
- Encountered [#32751](https://github.com/brave/brave-browser/issues/32751)
![Linux](https://github.com/brave/brave-browser/assets/17010094/263483cc-179c-492f-a52e-bafc98c20f9a)

---------------------

**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#19089](https://github.com/brave/brave-core/pull/19089)
- Verified Portfolio filter is shown correctly in V2 panel
- Encountered [#32751](https://github.com/brave/brave-browser/issues/32751)
![image](https://user-images.githubusercontent.com/17010094/265625333-1cb60ca0-fd7a-4878-9a85-927f605cf170.png)

---------------------

**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (arm64)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | macOS Version 13.4.1 (c) (Build 22F770820d)

- Verified steps from [brave/brave-core#19089](https://github.com/brave/brave-core/pull/19089)
- Verified Portfolio filter is shown correctly in V2 panel
- Encountered [#32751](https://github.com/brave/brave-browser/issues/32751)
![image](https://github.com/brave/brave-browser/assets/17010094/c26f6ca9-8a62-4d0b-afdf-332598dea823)
