### ISSUE TITLE
Update Visible Assets Modal to V2 Design

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#31389]
## Description 

We need to update the `Edit Visible Assets` modal to the `V2` design.

![Screenshot 26](https://github.com/brave/brave-browser/assets/40611140/d559089e-9df3-4ed2-a1b0-94e52947887b)

![Screenshot 27](https://github.com/brave/brave-browser/assets/40611140/2e3bd8fe-76b7-4e55-bf9c-8968097ce583)

![Screenshot 28](https://github.com/brave/brave-browser/assets/40611140/06a2d0ff-d6b6-494b-93fc-cf0833bebf98)

![Screenshot 29](https://github.com/brave/brave-browser/assets/40611140/0d86aac0-8b03-4b08-aa40-fea24e860bef)

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Linux

- Verified steps from [brave/brave-core#19190](https://github.com/brave/brave-core/pull/19190)
- Verified `Visible Assets` modal is as per new design
- Verified `My assets` is selected by default
- Verified `hiding` an asset and clicking `Save changes` work as expected
- Verified `Deleting` an asset work as expected
- Verified `Add custom asset` work as expected

https://github.com/brave/brave-browser/assets/17010094/f368aa08-b09a-4be4-8722-11ef111a4e62

---------------------

**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#19190](https://github.com/brave/brave-core/pull/19190)
- Verified `Visible Assets` modal is as per new design
- Verified `My assets` is selected by default
- Verified `hiding` an asset and clicking `Save changes` work as expected
- Verified `Deleting` an asset work as expected
- Verified `Add custom asset` work as expected

https://github.com/brave/brave-browser/assets/17010094/d91e4098-3a4c-4f7b-ad68-55df991fc1a6

---------------------

**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (arm64)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | macOS Version 13.4.1 (c) (Build 22F770820d)

- Verified steps from [brave/brave-core#19190](https://github.com/brave/brave-core/pull/19190)
- Verified `Visible Assets` modal is as per new design
- Verified `My assets` is selected by default
- Verified `hiding` an asset and clicking `Save changes` work as expected
- Verified `Deleting` an asset work as expected
- Verified `Add custom asset` work as expected

https://github.com/brave/brave-browser/assets/17010094/7da8266b-372d-4b68-99de-86b9ae423c0c
