### ISSUE TITLE
Implement v2 Designs for Buy Screen

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#31384]
Figma link: https://www.figma.com/file/muVcmcu4RFNu0LkXe9VRDl/Wallet-2.0?type=design&node-id=3390%3A259319&mode=dev

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.58.105 Chromium: 116.0.5845.114 (Official Build) beta (64-bit)
-- | --
Revision | 5a895596bcd7fcd930dab0714ea5cfa86c5aa0a7
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#19103](https://github.com/brave/brave-core/pull/19103)
- Verified Buy screen is using V2 design

https://github.com/brave/brave-browser/assets/17010094/140127d7-fe61-4e3d-b6cb-28359854ec50
