### ISSUE TITLE
No UI feedback when Copy button is clicked on manage your wallet modal

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#3139]
## Description 

No UI feedback when Copy button is clicked on manage your wallet modal

## Steps to Reproduce

   1. Enable rewards
   2. Go to settings to backup wallet
   3. Click on Copy button, no UI feedback that recovery code is copied into clipboard

## Actual result:

No UI feedback when Copy button is clicked on manage your wallet modal

## Expected result:
Should show some UI feedback that text is copied to clipboard

## Reproduces how often: 

Easy

## Brave version (brave://version info)

All

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
N/A
- Is the issue reproducible on the latest version of Chrome? 
N/A
### Additional Information

cc: @NejcZdovc

**Comment by Miyayes** [comment]
There are no more copy words for backup & restore section in Manage Brave Rewards section. Also, things have changed a lot since this issue was filed in general.
