### ISSUE TITLE
Improve the flow for manually adding an NFT

### ISSUE THREAD

**Issue by simoarpe** [brave/brave-browser#31399]
## Description

Adding an NFT on Android is a cumbersome operation, as the button to reach the dialog is a bit hidden in the UI. 

### Android - iOS Comparison

https://github.com/brave/brave-browser/assets/3308503/cde9b008-b6bc-4dc6-85f1-deb66da41a82

The main difference is that on Android the button is inside the screen to edit the visible assets. 
We should go in favor of the iOS solution: the plus icon should be repositioned in the NFT screen.

⚠️ Note: because the current Android implementation is relying on a dialog and is sharing the logic with the screen behind, we should implement [27070](https://github.com/brave/brave-browser/issues/27070) first.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.58.117 x64 build
- Verified steps from [brave/brave-core#19404](https://github.com/brave/brave-core/pull/19404)
- Verified new adding a new NFT shows the new network selector
- Verified manually added NFTs are listed in a grid 

Oppo Reno 5 (Android 13) | Lenovo Tab (Android 12)
-- | --
<video src=https://github.com/brave/brave-browser/assets/17010094/27cf5c5e-2e60-4f2b-a323-985681d0b878> | <video src=https://github.com/brave/brave-browser/assets/17010094/3d407d18-d6cf-4f15-baa9-b674f7931e6f>
