### ISSUE TITLE
Wallet crashing when attempting to format certain numeric values

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#31392]
## Description 

The desktop wallet UI is failing to render and logs an error to the console when attempting to format numbers with an invalid min/max fraction-digit options.

## Steps to Reproduce

Not known at this time

## Actual result:

![image (2)](https://github.com/brave/brave-browser/assets/30185185/a005fca7-7ae1-4207-95da-b7299717f587)

## Expected result:
The wallet should not crash when numbers are formatted

## Reproduces how often: 

Difficult to reproduce. No documented steps to re-create

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.54.94` or higher for `1.54.x` verifications 👍

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.57.24 Chromium: 115.0.5790.136 (Official Build) beta (64-bit)
-- | --
Revision | `8099932ede6f8d4624fbddf39d27abb3b340d8c9`
OS | Linux

- Verified steps from [brave/brave-core#19109](https://github.com/brave/brave-core/pull/19109)
- Verified no webview crash when loading Portfolio or Assets screen

---------------------

**Verification passed on**

Brave | 1.57.24 Chromium: 115.0.5790.136 (Official Build) beta (64-bit)
-- | --
Revision | `8099932ede6f8d4624fbddf39d27abb3b340d8c9`
OS | Windows 11 Version 22H2 (Build 22621.1992)

- Verified steps from [brave/brave-core#19109](https://github.com/brave/brave-core/pull/19109)
- Verified no webview crash when loading Portfolio or Assets screen

---------------------

**Verification passed on**

Brave | 1.57.24 Chromium: 115.0.5790.136 (Official Build) beta (arm64)
-- | --
Revision | `8099932ede6f8d4624fbddf39d27abb3b340d8c9`
OS | macOS Version 13.4.1 (c) (Build 22F770820d)

- Verified steps from [brave/brave-core#19109](https://github.com/brave/brave-core/pull/19109)
- Verified no webview crash when loading Portfolio or Assets screen
