### ISSUE TITLE
AI Chat error states

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#31391]
## Description 
We need to design and implement AI Chat error states.
- Send a message, but a network issue prevented getting a response (e.g. "There was a network issue connecting to Leo, check your connection and try again")
- Send a message, but a rate limit has been reached (i.e. "Leo is busy, try again in a minute")

Maybe they are the same error?

Right now we simply add the error message as a conversation bubble, i.e. each error message stays in place in the part of the conversation where it happened.

![image](https://github.com/brave/brave-browser/assets/741836/f71e3926-817a-4ea4-a4fb-d0598ef76fba)

**Comment by aguscruiz** [comment]
Added in Figma:
https://www.figma.com/file/h7fKSJF2P556bZWfyLTfwD/Brave-AI?type=design&node-id=1520%3A30055&mode=design&t=BIJ98u8xeRJPSD06-1

**Comment by bbondy** [comment]
The rate limiting will be http status code of 429

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.60.64 Chromium: 118.0.5993.21 (Official Build) nightly (x86_64)
-- | --
Revision | f05e9ca819b9af4850b13764e15631322922d47c
OS | macOS Version 11.7.10 (Build 20G1427)
```

## `Leo is too busy right now` - rate-limiting error message - `PASSED`
<details>

### Steps:
0. launched `Fiddler Everywhere`
1. installed `1.60.64`
2. launched Brave
3. restarted (to pick up Griffin seed)
4. clicked on `Brave Leo`
5. loaded `https://slate.com/news-and-politics/2023/09/republican-debate-haley-ramaswamy-desantis-scott-trump.html`
6. clicked on all the `Summarize this page` and subsequent pre-suggested questions
7. waited for responses
8. followed up info with multiple additional, targeted questions
9. hit the rate-limit error notification
10. checked the status code in `Fiddler Everywhere`

### Confirmed `Leo is too busy right now.  Please try again in a few minutes` rate-limit error message

</details>
