### ISSUE TITLE
Lookalike URL popup has a broken Learn more link

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#31396]
The popup that warns users about [lookalike sites](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/docs/security/lookalikes/lookalike-domains.md):
<img width="343" alt="braze-not-brave" src="https://github.com/brave/brave-browser/assets/167821/8ba81ee9-1c27-4467-9875-7d48c34cd741">
![Screenshot (Jun 30, 2023 13_23_59)](https://github.com/brave/brave-browser/assets/167821/87d2155d-4a6c-43ef-ab9a-3ee44b93e6ee)

unhelpfully links to the https://support.brave.com/ homepage.

We should create a custom support.brave.com page which links to the Chrome technical documentation so that users can understand why they're being shown these messages.

**Comment by Brave-Matt** [comment]
Document is live here:
https://support.brave.com/hc/en-us/articles/17550072876045

**Comment by stephendonner** [comment]
## Verification `PASSED` using


```
Brave | 1.58.90 Chromium: 116.0.5845.96 (Official Build) beta (x86_64)
-- | --
Revision | c112ad8c854bd34b48f4e87bfb3f7951e426a1d4
OS | macOS Version 11.7.9 (Build 20G1426)
```

### Steps:
1. installed `1.58.90`
2. launched Brave
3. opened `brave://components`
4. confirmed `Safety Tips` `2987` component
5. clicked on `Check for update`
6. confirmed it showed no updates
7. loaded `http://www.ogogle.com/`
8. confirmed `Did you mean Google.com?` popup
9. clicked on `Learn more`

### Confirmed clicking on the `Learn more` link took me to the appropriate Support article: `https://support.brave.com/hc/en-us/articles/17550072876045-Lookalike-URLs`

example | example | example | example
---------|----------|---------|----------
<img width="1751" alt="Screen Shot 2023-08-16 at 10 47 04 AM" src="https://github.com/brave/brave-browser/assets/387249/199605cb-8172-4070-994a-fbc90e6501cf"> | <img width="1751" alt="Screen Shot 2023-08-16 at 10 47 10 AM" src="https://github.com/brave/brave-browser/assets/387249/5cfaa537-9795-4bbb-afe5-bd09885d51be"> | <img width="1751" alt="Screen Shot 2023-08-16 at 10 47 18 AM" src="https://github.com/brave/brave-browser/assets/387249/7185e3bb-cffa-49bc-8aec-476aae31aba8"> | <img width="1751" alt="Screen Shot 2023-08-16 at 10 47 28 AM" src="https://github.com/brave/brave-browser/assets/387249/eb3c8ef7-6bff-483a-a472-252553ab91ec">
