### ISSUE TITLE
AI Chat UI State when conversation is too long

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#31406]
A conversation has a maximum amount of text. 

When the user is approaching the limit **for the current model**, we can display an inline warning alert that the conversation is getting too long for the model. We can also put a premium prompt in there.

When the server detects the context is too long to be able to answer, it will provide a `413` error. When this is hit we can display a message to the user and disable further inputs. The user can be prompted to reset the conversation to continue talking about a specific Tab content, or start a new conversation if it's general non-Tab-related chat.

**Comment by aguscruiz** [comment]
Is there a way we could do this automatically without any real visual indicators? So it seems like the conversation continues even if it's a new one?

Or is all the context lost too when the conversation resets?

**Comment by petemill** [comment]
@nullhook see https://github.com/brave/brave-browser/issues/31405#issuecomment-1749430273. That issue is very similar to this one, so perhaps do in the same PR.

**Comment by petemill** [comment]
There's 1 error state missing in the figma, and that's the error alert when the conversation is _actually_ too long, and we receive the error from the server. At that point, the conversation cannot continue, and the user needs to start a new one. Suggestion:

> [Error Alert]
> This conversation is too long and cannot continue. There may be other models available with which Leo is capable of maintaining accuracy for longer conversations.
> [ Start a new conversation ]

The action button should be the "faint" kind.

We could also have a button which switches to a larger context model, if there is one. But I think that's too complex for MVP considering it should be an edge case for users to reach the limit.

cc @aguscruiz in case you want to change this.

**Comment by aguscruiz** [comment]
Added that error state here:
https://www.figma.com/file/h7fKSJF2P556bZWfyLTfwD/Leo-MVP?type=design&node-id=4504%3A45162&mode=design&t=uJLxkY223qan3ixn-1

![image](https://github.com/brave/brave-browser/assets/15734630/38570f95-c763-4aba-921e-b64ba0719618)

**Comment by kjozwiak** [comment]
The above requires `1.60.105` or higher for `1.60.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.60.106 Chromium: 119.0.6045.59 (Official Build) (64-bit)
-- | --
Revision | 16064193dde8c55f64dabd32f125c0cd9380f96a
OS | Windows 11 Version 22H2 (Build 22621.2428)
```
