### ISSUE TITLE
New feature: Suggest password

### ISSUE THREAD

**Issue by lukaslevert** [brave/brave-browser#31401]
## Description 

This is a request to add a similar feature to Safari that suggests a strong password that don't use a 3rd party password manager. The objective is to make it easy for the user to practice safe password hygiene.

Strong generated password suggestion would appear if a password doesn't already exist in Brave's autofill, and then subsequently be saved to Brave's auto-fill.

![image](https://github.com/brave/brave-browser/assets/79997955/fcceccf0-4c49-4ddc-ba56-52df65c068ae)

**Comment by fmarier** [comment]
Yes, it's a great feature and it's already built into Chromium, we just have to enable it: https://github.com/brave/brave-browser/issues/4901
