### ISSUE TITLE
[ads] Resize custom notification ads to match native notifications

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#31407]
MacOS - 344px
Windows - 336px
Linux - 370px (was changed here https://github.com/brave/brave-core/pull/19054)

cc @aguscruiz @jenn-rhim

**Comment by btlechowski** [comment]
Verified with

Brave | 1.62.107 Chromium: 120.0.6099.115 (Official Build) beta (64-bit)
-- | --
Revision | 67a3b21572338a0660bb25a5855da0f1e9372a39
OS | Linux

Verified ad width is 370px

![image](https://github.com/brave/brave-browser/assets/34715963/e8fc479e-63f1-435f-9bb8-f2a33e4b1095)
