### ISSUE TITLE
AI Chat UI state for when article (or video) text is too long

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#31405]
When the content length is too long, we limit the amount of the article text or video transcript that will be sent. We should perhaps design a message that shows to the user saying only partial content will be sent since this content is so long.

**Comment by aguscruiz** [comment]
We should improve the copy a bit (@rebron ?) but I'm trying to standardize all the messages like this. Let me know what you think

https://www.figma.com/file/h7fKSJF2P556bZWfyLTfwD/Brave-AI?type=design&node-id=1723%3A33226&mode=design&t=bY3ddFmMLqgrr58E-1

**Comment by petemill** [comment]
Let's make our `.substr` model-specific, and report to the Conversation that a substring was taken.

**Comment by petemill** [comment]
How much to reserve?

Currently, for llama2 we hardcode:
```
  // tokens + max_new_tokens must be <= 4096 (llama2)
  // 8092 chars, ~3,098 tokens (reserved for article)
  // 1k chars, ~380 tokens (reserved for prompt)
```

We can use the same technique for claude

**Comment by kjozwiak** [comment]
The above requires `1.60.105` or higher for `1.60.x` verification 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.60.106 Chromium: 119.0.6045.59 (Official Build) (64-bit)
-- | --
Revision | 16064193dde8c55f64dabd32f125c0cd9380f96a
OS | Windows 11 Version 22H2 (Build 22621.2506)
```

Using the STR/Cases outlined via https://github.com/brave/brave-core/pull/20439#issuecomment-1780163500, ensured that the correct error re: `The page is too long for Leo` was being displayed. @stephendonner technically already went through the above as well via https://github.com/brave/brave-browser/issues/33923#issuecomment-1783896120.

![image](https://github.com/brave/brave-browser/assets/2602313/f1712cb0-1cd3-43ad-a96b-c46ecd6cade8)
