### ISSUE TITLE
global shields are applied to local files

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#3140]
## Steps to Reproduce

   1. Open `brave://settings/?search=Script+blocking`
   2. Turn `Script Blocking` on
   3. Open(CTRL+O) this file: [test_block_script.zip](https://github.com/brave/brave-browser/files/2807821/test_block_script.zip)

## Actual result:

Page shows `FAIL`
Script was blocked
Global shield setting are not applied to local files

![image](https://user-images.githubusercontent.com/34715963/51911381-f65df300-23d1-11e9-8f68-d8bb42f0e1f9.png)

## Expected result:
Page shows `PASS`
Script was not blocked
Global shield setting should not apply to local files

## Reproduces how often: 

easily reproduced

## Brave version (brave://version info)

Brave | 0.59.31 Chromium: 72.0.3626.71 (Official Build) (64-bit)
-- | --
Revision | f52ccad2a6a3c65fc9e0c591a517ceab1198dac0-refs/branch-heads/3626@{#763}
OS | Windows 7

Brave | 0.59.31 Chromium: 72.0.3626.71 (Official Build) (64-bit)
-- | --
Revision | f52ccad2a6a3c65fc9e0c591a517ceab1198dac0-refs/branch-heads/3626@{#763}
OS | Linux

Brave | 0.60.17 Chromium: 72.0.3626.64 (Official Build) dev (64-bit)
-- | --
Revision | eaa9668e80ce5405e7f1902579558ea725c06ca1-refs/branch-heads/3626@{#708}
OS | Windows 7

cc @brave/legacy_qa @tomlowenthal

**Comment by tomlowenthal** [comment]
Global shields settings are supposed to apply to the `file://` protocol as well as the regular web.
