### ISSUE TITLE
Ephemeral storage origins to cleanup are not removed until restart

### ISSUE THREAD

**Issue by goodov** [brave/brave-browser#31417]
`brave://prefs-internals/` should have this list empty in most cases:

```
"ephemeral_storage": {
      "first_party_storage_origins_to_cleanup": [ ... ]
}
```

an item should only exist there to delay the cleanup for 30 seconds (keep alive) if a user decides to reopen a website.

**Comment by kjozwiak** [comment]
The above requires `1.54.94` or higher for `1.54.x` verification. 👍

**Comment by kjozwiak** [comment]
@goodov changed the above to `QA/Yes` as we can do a quick check like I did before getting the above uplifted as per https://github.com/brave/brave-core/pull/19126#issuecomment-1624155591. If you disagree, just change it back to `QA/No`. We'll leave the above as `release-notes/exclude` though 👍

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.57.8 Chromium: 115.0.5790.75 (Official Build) beta (64-bit)
-- | --
Revision | 77bffd419b7e89d7e666c9695e7fa0d1d0367a99
OS | Windows 11 Version 22H2 (Build 22621.1992)
```

1. Install 1.57.8
2. launch Brave
3. visit https://github.com/
4. click Shields icon and verified `Forget me when I close this site` toggle is not available
5. relaunch Brave to pull in Griffin seed `BraveForgetFirstPartyStorage:Enabled`
6. return to https://github.com/ site 
7. click on Shields icon 
8. confirmed `Forget me when I close this site` toggle is available and turned `Off` as a default
9. toggle `On` `Forget me when I close this site` on the Shields panel
10. login to Github
11. open brave://prefs-internals/
12. verified the value in    
            - "ephemeral_storage": {
                    "first_party_storage_origins_to_cleanup": [  ]

step 1 | step 4 | step 8 | step 9 | step 10 | step 12
------- | ------ | ------ | ------ | ------- | --------
![image](https://github.com/brave/brave-core/assets/98358127/3f666f70-62a5-46bd-b036-40ed8fb19f77)|![image](https://github.com/brave/brave-core/assets/98358127/c0ac1552-c079-44fd-b1cc-df0d76d9cd7d)|![image](https://github.com/brave/brave-browser/assets/98358127/3757ebb8-64cd-40e0-a9a3-b1307f55f449)|![image](https://github.com/brave/brave-browser/assets/98358127/41db6069-b6f1-4272-a032-d0ec4bc311de)|![image](https://github.com/brave/brave-browser/assets/98358127/98afd1d1-9905-4dd2-8b04-7211836dac70)|![image](https://github.com/brave/brave-browser/assets/98358127/d4517b37-a8f7-4065-819e-cbec06a4e7c0)
