### ISSUE TITLE
Ads Confirmations/Rewards UI tracker

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-browser#3141]
0.60 Beta
Continue work-stream for Ads Beta in 0.60. For Beta 0.60 expectation is to server Ads but no expectation for Rewards or Confirmations

0.60 Release
Continue Ads "Coming soon" from 0.59, as is.

0.61 - all channels
Expectation is to have Confirmations and Rewards to be fully functional

cc @kjozwiak @NejcZdovc @mrose17 @tmancey @LaurenWags

**Comment by tmancey** [comment]
👍

**Comment by mandar-brave** [comment]
0.60 Beta
Continue work-stream for Ads Beta in 0.60. For Beta 0.60 expectation is to server Ads but no expectation for Rewards or Confirmations

0.60 Release specific
Continue Ads "Coming soon" from 0.59, as is.

0.61 Release specific
Continue Ads "Coming soon" from 0.60, as is

0.61 all channels
Expectation is to have Confirmations and Rewards to be fully functional

**Comment by NejcZdovc** [comment]
@mandar-brave now that confirmations landed can we close this one?

**Comment by mandar-brave** [comment]
@NejcZdovc you can - did they land in to 0.62?.
But sure!
