### ISSUE TITLE
Dragging out `vertical tab strip toggle button` hides highlight effect

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#31421]
## Steps to Reproduce

   1. Expand vertical tab strip so that toggle button on it is highlighted
   2. Press the button and try moving cursor out of it

## Actual result:

The highlight effect goes away

## Expected result:
The highlight effect should remain

## Reproduces how often: 

Always

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.58.88 Chromium: 116.0.5845.82 (Official Build) beta (64-bit)
-- | --
Revision | acf16e35d5897fd4bf9b1b5a93b56aff2ed64bba
OS | Windows 11 Version 22H2 (Build 22621.2134)
```


1. Install 1.58.88
2. launched Brave
3. enabled vertical tabs via tab context menu 
4. expanded vertical tab strip by clicking the Expand/Collapse button

#### Confirmed Expand/Collapse button is highlighted even after moving the cursor away in Expanded mode


https://github.com/brave/brave-browser/assets/98358127/0a07cf5c-7338-412b-ac1b-88f6a2a05bfa
