### ISSUE TITLE
Disable Google search metrics to be written into preferences file

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#3142]
## Description 

Preferences file adds an entry for `"last_google_search_domain_mixing_matrix_time:<UNIXTIMESTAMP>"` into preferences file which is part of https://cs.chromium.org/chromium/src/chrome/browser/google/google_search_domain_mixing_metrics_emitter.cc. 

## Steps to Reproduce

   1. Create a new profile
   2. Close browser and open preferences pages
   3. Search for `last_google_search_domain_mixing_matrix_time`,shows up at the beginning of the file 

## Actual result:

Unwanted Google service is written into file 

## Expected result:
Nothing related to Google should be written into file

## Reproduces how often: 

Easy

## Brave version (brave://version info)

All

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @bbondy @pilgrim-brave

**Comment by bbondy** [comment]
Mark looked at the code and as far as he can tell it writes to the prefs file unconditionally because of the way the code is architected.  The service itself is unused and the data is not sent anywhere. 

I'm going to close as wontfix since I don't think this poses any threat.
