### ISSUE TITLE
TorProfileManager::SwitchToTorProfile crashes when incognito mode is not available

### ISSUE THREAD

**Issue by goodov** [brave/brave-browser#31434]
Tor profile cannot be opened (browser crashes) when incognito mode is not available. I assume we need to remove all Tor entry points (context menu, app menu, throttler) when incognito is not available.

cc @bsclifton can you assign the right person please?

crash happens here:
https://github.com/chromium/chromium/blob/7b5dc41373751fbe8f7ec0b25688a400dbadcf24/chrome/browser/profiles/off_the_record_profile_impl.cc#L201-L203

Steps to reproduce:

Windows:
1. In admin cmd execute:
  ```REG ADD HKLM\SOFTWARE\Policies\BraveSoftware\Brave /v IncognitoModeAvailability /t REG_DWORD /d 1```
2. Open brave, try to open Tor window, it leads to crash.
3. Exectute ```REG ADD HKLM\SOFTWARE\Policies\BraveSoftware\Brave /v IncognitoModeAvailability /t REG_DWORD /d 0``` to default IncognitoModeAvailability value

```
[ 00 ] base::ImmediateCrash() ( immediate_crash.h:144 )
[ 01 ] logging::CheckFailure() ( check.h:150 )
[ 02 ] OffTheRecordProfileImpl::Init() ( off_the_record_profile_impl.cc:200 )
[ 03 ] OffTheRecordProfileImpl::Init() ( off_the_record_profile_impl.cc:200 )
[ 04 ] Profile::CreateOffTheRecordProfile(Profile*, Profile::OTRProfileID const&) ( off_the_record_profile_impl.cc:662 )
[ 05 ] ProfileImpl::GetOffTheRecordProfile(Profile::OTRProfileID const&, bool) ( profile_impl.cc:1013 )
[ 06 ] TorProfileManager::GetTorProfile(Profile*) ( tor_profile_manager.cc:72 )
[ 07 ] TorProfileManager::SwitchToTorProfile(Profile*, base::OnceCallback<void (Profile*)>) ( tor_profile_manager.cc:49 )
[ 08 ] brave::NewOffTheRecordWindowTor(Browser*) ( browser_commands.cc:85 )
[ 09 ] chrome::BraveBrowserCommandController::ExecuteBraveCommandWithDisposition(int, WindowOpenDisposition, base::TimeTicks) ( brave_browser_command_controller.cc:275 )
[ 10 ] chrome::BraveBrowserCommandController::ExecuteCommandWithDisposition(int, WindowOpenDisposition, base::TimeTicks) ( brave_browser_command_controller.cc:95 )
[ 11 ] BraveAppMenu::ExecuteCommand(int, int) ( brave_app_menu.cc:39 )
[ 12 ] views::internal::MenuRunnerImpl::OnMenuClosed(views::internal::MenuControllerDelegate::NotifyType, views::MenuItemView*, int) ( menu_runner_impl.cc:233 )
[ 13 ] non-virtual thunk to views::internal::MenuRunnerImpl::OnMenuClosed(views::internal::MenuControllerDelegate::NotifyType, views::MenuItemView*, int) ( menu_runner_impl.cc:0 )
[ 14 ] views::MenuController::ExitMenu() ( menu_controller.cc:3205 )
[ 15 ] base::OnceCallback<void (NSArray*)>::Run(NSArray*) && ( callback.h:152 )
[ 16 ] gfx::AnimationContainer::Run(base::TimeTicks) ( animation_container.cc:99 )
[ 17 ] base::RepeatingCallback<void (base::TimeTicks)>::Run(base::TimeTicks) const & ( callback.h:333 )
[ 18 ] gfx::AnimationRunner::Step(base::TimeTicks) ( animation_runner.cc:78 )
[ 19 ] (anonymous namespace)::DefaultAnimationRunner::OnTimerTick() ( animation_runner.cc:52 )
[ 20 ] base::OnceCallback<void ()>::Run() && ( callback.h:152 )
[ 21 ] base::OneShotTimer::RunUserTask() ( timer.cc:178 )
[ 22 ] base::OneShotTimer::FireNow() ( timer.cc:163 )
[ 23 ] base::TaskAnnotator::RunTaskImpl(base::PendingTask&) ( callback.h:152 )
```

```
[ 00 ] base::ImmediateCrash() ( immediate_crash.h:146 )
[ 01 ] logging::CheckFailure() ( check.h:156 )
[ 02 ] OffTheRecordProfileImpl::Init() ( off_the_record_profile_impl.cc:201 )
[ 03 ] OffTheRecordProfileImpl::Init() ( off_the_record_profile_impl.cc:201 )
[ 04 ] Profile::CreateOffTheRecordProfile(Profile*, Profile::OTRProfileID const&) ( off_the_record_profile_impl.cc:667 )
[ 05 ] ProfileImpl::GetOffTheRecordProfile(Profile::OTRProfileID const&, bool) ( profile_impl.cc:1034 )
[ 06 ] TorProfileManager::GetTorProfile(Profile*) ( tor_profile_manager.cc:72 )
[ 07 ] TorProfileManager::SwitchToTorProfile(Profile*, base::OnceCallback<void (Browser*)>) ( tor_profile_manager.cc:49 )
[ 08 ] tor::OnionLocationNavigationThrottle::WillProcessResponse() ( onion_location_navigation_throttle_delegate.cc:42 )
[ 09 ] content::NavigationThrottleRunner::ProcessInternal() ( navigation_throttle_runner.cc:0 )
[ 10 ] content::NavigationThrottleRunner::ProcessNavigationEvent(content::NavigationThrottleRunner::Event) ( navigation_throttle_runner.cc:122 )
[ 11 ] content::NavigationRequest::WillProcessResponse() ( navigation_request.cc:6841 )
```

**Comment by LaurenWags** [comment]
@brave/qa-team this requires `1.56.3` or higher for 1.56.x verification

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using 



Reproduced the issue in 1.52.130 using the STR from https://github.com/brave/brave-core/pull/19211#issuecomment-1631386442 and https://github.com/brave/brave-browser/issues/31434#issue-1787858296

example | example | example | example | example
--- | --- | ---  | --- | ---
![image](https://github.com/brave/brave-browser/assets/98358127/d6d1ae33-46c1-40e4-9d93-b229efe25bac)|![image](https://github.com/brave/brave-browser/assets/98358127/2f613d62-5163-4be2-ae33-98b194e06b9d)|![image](https://github.com/brave/brave-browser/assets/98358127/e51d5aaf-aa26-4ddd-b356-6fb4174f5831)|![image](https://github.com/brave/brave-browser/assets/98358127/735d7aee-d246-4267-acbb-d2d10d1233b6)|![image](https://github.com/brave/brave-browser/assets/98358127/97681034-a8c0-4b24-a8f6-0522921db917)

Steps: 

1. Installed 1.56.3
2. launched Brave
3. confirmed "New Private Window with Tor" is displayed in the hamburger menu
4. open terminal as an admin and executed
        -  `REG ADD HKLM\SOFTWARE\Policies\BraveSoftware\Brave /v IncognitoModeAvailability /t REG_DWORD /d 1`
5. relaunched 1.58.10
6. confirmed 'New private window with Tor' in main menu is not available and "New Private Window" is grayed out
7. opened brave://settings/privacy and confirmed Tor settings are disabled except for Snowflake extension setting
8. ran keyboard shortcut for "New Private Window with Tor" (Alt + Shift+ N) did not open a new Tor window and did not cause a crash
9. Right clicked on a link on brave.com, no option to "Open Link in Private Window with Tor" is displayed
10. close Brave
11. return default policy value by running following command in the cmd window
      -`REG ADD HKLM\SOFTWARE\Policies\BraveSoftware\Brave /v IncognitoModeAvailability /t REG_DWORD /d 0`
12. relaunch brave

Confirmed Brave is not crashed in Step 8
Confirmed Tor windows settings in `brave://settings/privacy` are enabled as expected.

step 3 | step 4 | step 6 | step 7 | step 9 | step 12a| step 12b
---- | ---- | ---- | ----- | ---- | ---- | -----
![image](https://github.com/brave/brave-browser/assets/98358127/b68b4e95-6a6f-4944-824a-f45b4a0b59d6)|![image](https://github.com/brave/brave-browser/assets/98358127/096d6ace-e72e-4671-b275-3bb0c696e2e2)|![image](https://github.com/brave/brave-browser/assets/98358127/baefe3d3-5b82-4729-aaac-0856bdc224db)|![image](https://github.com/brave/brave-browser/assets/98358127/b27804cf-7730-4dfc-84a9-691e826f1870)|![image](https://github.com/brave/brave-browser/assets/98358127/b860797d-1c8e-48d3-8c7c-596b76972d02)|![image](https://github.com/brave/brave-browser/assets/98358127/ebb85cc0-eea1-4d4d-ab7f-ef46bf1a5042)|![image](https://github.com/brave/brave-browser/assets/98358127/ece205ca-b204-4957-b088-9f11b4686cd1)

**Comment by stephendonner** [comment]
## Verification `PASSED` using 

Brave | 1.56.3 Chromium: 115.0.5790.75 (Official Build) (x86_64)
-- | --
Revision | 3433e4d513e8454ba0243deea3d53693661dc0c3-refs/branch-heads/5790@{#1430}
OS | macOS Version 11.7.8 (Build 20G1351)

### Steps:
1. in the console window, entered `defaults write com.brave.Browser IncognitoModeAvailability -integer 1`
2. installed `1.56.3`
3. launched Brave
4. confirmed `New Private Window` was disabled
5. confirmed `New Private Window with Tor` was hidden
6. opened `brave://settings/privacy`
7. confirmed all options except for `Snowflake` were disabled
8. opened `brave://policy/`
9. confirmed `IncognitoModeAvailability` was `1` (disabled)
10. confirmed keyboard shortcuts were listed as disabled
11. confirmed keyboard shortcuts didn't open `Private` or `Private with Tor` windows
12. confirmed context-menu item `Open Link in Private Window` was disabled
13. restored feature by entering `defaults write com.brave.Browser IncognitoModeAvailability -integer 0` into the console window
14. confirmed everything was restored

### Confirmed no crashes, and disabling/re-enabling the features worked

example | example | example | example | example
---------|----------|---------|----------|---------
<img width="682" alt="Screen Shot 2023-07-12 at 11 48 41 AM" src="https://github.com/brave/brave-browser/assets/387249/cca9100e-5b2f-4c2e-97ef-27506b004f3d"> | <img width="1697" alt="Screen Shot 2023-07-12 at 11 56 12 AM" src="https://github.com/brave/brave-browser/assets/387249/073e7d69-30be-48b4-a9c0-161c332725f2"> | <img width="1809" alt="Screen Shot 2023-07-12 at 11 57 24 AM" src="https://github.com/brave/brave-browser/assets/387249/615cd37f-a1f3-4944-91ba-28366b59778c"> | <img width="327" alt="Screen Shot 2023-07-12 at 11 59 28 AM" src="https://github.com/brave/brave-browser/assets/387249/6fd949c1-4fa1-4ce5-9de6-ea3c1d4c689e"> | <img width="1696" alt="Screen Shot 2023-07-12 at 12 03 28 PM" src="https://github.com/brave/brave-browser/assets/387249/6ed95987-597a-46f8-854c-6d508cc93571">

example | example | example | example | example | example
---------|----------|---------|----------|----------|--------
<img width="682" alt="Screen Shot 2023-07-12 at 12 06 15 PM" src="https://github.com/brave/brave-browser/assets/387249/33101482-6deb-4f9f-afa1-bb18dcd88318"> | <img width="1697" alt="Screen Shot 2023-07-12 at 12 07 22 PM" src="https://github.com/brave/brave-browser/assets/387249/e0f22187-4168-458c-9739-9f1628b18d32"> | <img width="1809" alt="Screen Shot 2023-07-12 at 12 09 43 PM" src="https://github.com/brave/brave-browser/assets/387249/40e24435-ca89-43bf-a77e-d11b1a7288a0"> | <img width="1809" alt="Screen Shot 2023-07-12 at 12 09 58 PM" src="https://github.com/brave/brave-browser/assets/387249/0d4c6ad6-1ed6-4737-887c-e11ffe03cb79"> | <img width="1809" alt="Screen Shot 2023-07-12 at 12 10 14 PM" src="https://github.com/brave/brave-browser/assets/387249/0dd96004-8b1d-45bb-99ac-1568f5e1f826"> | <img width="327" alt="Screen Shot 2023-07-12 at 12 10 20 PM" src="https://github.com/brave/brave-browser/assets/387249/c01b4237-0802-4bb7-a7f0-aa0639d159bd">
