### ISSUE TITLE
brave::CopyLinkWithStrictCleaning crash

### ISSUE THREAD

**Issue by goodov** [brave/brave-browser#31435]
https://brave.sp.backtrace.io/p/brave/triage?time=year&filters=W1siY2FsbHN0YWNrIiwiY29udGFpbnMiLCJicmF2ZTo6Q29weUxpbmtXaXRoU3RyaWN0Q2xlYW5pbmciXSxbImNhbGxzdGFjay5mdW5jdGlvbnMiLCJjb250YWlucyIsIkJyYXZlUmVuZGVyVmlld0NvbnRleHRNZW51OjpFeGVjdXRlQ29tbWFuZCJdXQ%3D%3D&aggregations=((guid%2Cunique)%2C(classifiers%2Chead))

```
[ 0 ] base::raw_ptr<Profile, (base::RawPtrTraits)1>::GetForExtraction() const ( raw_ptr.h:1029 )
[ 1 ] base::raw_ptr<Profile, (base::RawPtrTraits)1>::operator Profile*() const ( raw_ptr.h:802 )
[ 2 ] Browser::profile() const ( browser.h:409 )
[ 3 ] brave::CopyLinkWithStrictCleaning(Browser*, GURL const&) ( browser_commands.cc:216 )
[ 4 ] BraveRenderViewContextMenu::ExecuteCommand(int, int) ( render_view_context_menu.cc:267 )
[ 5 ] BraveRenderViewContextMenu::ExecuteCommand(int, int) ( render_view_context_menu.cc:267 )
[ 6 ] -[MenuControllerCocoa itemSelected:] ( menu_controller.mm:331 )
[ 7 ] -[NSApplication(NSResponder) sendAction:to:from:]
[ 8 ] base::mac::CallWithEHFrame(void () block_pointer)
```

**Comment by goodov** [comment]
@spylogsster please uplift this to beta/release.

**Comment by LaurenWags** [comment]
Added `OS/macOS` as test plan only mentions macOS. Confirmed with @spylogsster via https://bravesoftware.slack.com/archives/CHGKGMHDJ/p1689087296562049?thread_ts=1689074532.651189&cid=CHGKGMHDJ.

**Comment by LaurenWags** [comment]
@brave/qa-team this requires 1.56.3 or higher for verification on 1.56.x.

**Comment by stephendonner** [comment]
## Verification `PASSED` using 

Brave | 1.56.3 Chromium: 115.0.5790.75 (Official Build) (x86_64)
-- | --
Revision | 3433e4d513e8454ba0243deea3d53693661dc0c3-refs/branch-heads/5790@{#1430}
OS | macOS Version 11.7.8 (Build 20G1351)

### Steps:
1. installed `1.56.3`
2. launched Brave
3. entered `https://brave.com/?foo=bar?baz=foopy?blah=blue` in the URL bar
4. context-clicked on the URL
5. loaded `https://www.nbcnews.com/`
6. scrolled to the bottom (infinity scroll)
7. context-clicked on a link with referrers and chose `Copy Clean Link`
8. pasted successfully without tracking/referral parameters

### Confirmed no crash when using `Copy Clean Link` (and pasting) from various entrypoints

URL bar context menu | pasted | in-page context menu | pasted
-----------------------|-----------------------|-----------------|-------------
<img width="1696" alt="Screen Shot 2023-07-12 at 11 22 01 AM" src="https://github.com/brave/brave-browser/assets/387249/689be955-9503-4cfe-a067-1d175974d07c"> | <img width="1809" alt="Screen Shot 2023-07-12 at 11 22 11 AM" src="https://github.com/brave/brave-browser/assets/387249/4a8c6e3a-3349-4c80-b3ad-97eac92c22c4"> | <img width="1700" alt="Screen Shot 2023-07-12 at 11 32 16 AM" src="https://github.com/brave/brave-browser/assets/387249/df82e787-aeed-4909-87bf-13d7e2c7df90"> | <img width="1697" alt="Screen Shot 2023-07-12 at 11 36 07 AM" src="https://github.com/brave/brave-browser/assets/387249/6f54a542-3025-4ed3-9e99-3cec47572d87">
