### ISSUE TITLE
browser requires restart for "x-brave-partner" headers to start working

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#3143]
## Description 

Similar to #2020 (might be the same issue), the `x-brave-partner` headers are not being used when initially launching Brave. I'm not 100% sure if it's timed base and we have to wait X amount of minutes before `x-brave-partner` starts being being used or if there's an issue with the header on first launch. Restarting the browser fixes the problem.

## Steps to Reproduce

   1.  download & install `0.58.21 Chromium: 71.0.3578.98`
   2. launch `0.58.21` and visit https://cheddar.com
   3. open the browser console within DevTools
   4. you'll notice that `x-brave-partner: cheddar` is missing
   5. restart the browser, open the browser console under https://cheddar.com
   6. you'll notice that `x-brave-partner: cheddar` is now appearing

## Actual result:

<img width="1414" alt="screen shot 2019-01-29 at 12 43 41 pm" src="https://user-images.githubusercontent.com/2602313/51928422-e50dea00-23c3-11e9-9091-5c9853a10173.png">

## Expected result:

<img width="1511" alt="screen shot 2019-01-29 at 12 47 12 pm" src="https://user-images.githubusercontent.com/2602313/51928471-04a51280-23c4-11e9-9969-4b407d366d79.png">

## Reproduces how often: 

100% reproducible when going through the above STR.

## Brave version (brave://version info)

Brave | 0.58.21 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds?

Yes, also reproducible on the following build:

Brave | 0.59.31 Chromium: 72.0.3626.71 (Official Build) (64-bit)
-- | --
Revision | f52ccad2a6a3c65fc9e0c591a517ceab1198dac0-refs/branch-heads/3626@{#763}

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 

N/A

- Is the issue reproducible on the latest version of Chrome? 

N/A

**Comment by GeetaSarvadnya** [comment]
Reproducible on Windows 10 x64 - `0.58.21`

![image](https://user-images.githubusercontent.com/38657976/51930121-d9501100-241f-11e9-820e-5786453277ba.png)

**Comment by emerick** [comment]
We have the following logic in our code and I think it's the root cause of the problem:

```
  // On first run, read the promo code from user-data-dir and
  // initialize the referral.
  bool checked_for_promo_code_file =
      pref_service_->GetBoolean(kReferralCheckedForPromoCodeFile);
  std::string download_id = pref_service_->GetString(kReferralDownloadID);
  if (!checked_for_promo_code_file && download_id.empty())
    task_runner_->PostTaskAndReply(
        FROM_HERE,
        base::Bind(&BraveReferralsService::ReadPromoCode,
                   base::Unretained(this)),
        base::Bind(&BraveReferralsService::OnReadPromoCodeComplete,
                   weak_factory_.GetWeakPtr()));
  else
    FetchReferralHeaders();
```

If it's the first run, we read the promo code and initialize the referral. If it's not the first run, we fetch the referral headers. That means the first run won't have referral headers until a restart (or until the next time we periodically fetch them, but that's once a day so that's not terribly useful).

Seems like the fix would be to just remove the `else` and always fetch the referral headers on startup.

cc: @rebron

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.59.32 Chromium: 72.0.3626.81 (Official Build) (64-bit)
-- | --
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS | Windows 10

- Verified the STR from description

![image](https://user-images.githubusercontent.com/38657976/51998811-5ee6c600-24df-11e9-92b8-142bcb7f1419.png)
