### ISSUE TITLE
Add `#brave-adblock-scriptlet-debug-logs` flag for filter authors

### ISSUE THREAD

**Issue by Emi-TheDhamphirInLoveUnderTheFrozenStar** [brave/brave-browser#31438]
## Description 

uBlock released the new scriptlet format and Brave added support for it in https://github.com/brave/brave-core-crx-packager/pull/599.

I don't know how much % of the new scriptlets format should work inside Brave, but for example, uBlock removed the [aell.js / addEventListener-logger.js](https://github.com/gorhill/uBlock/blob/07d3c96261656e44f674550fbde50da8f6a15acc/assets/resources/scriptlets.js#L352) and added the debug and logging inside [addEventListener-defuser.js](https://github.com/gorhill/uBlock/blob/07d3c96261656e44f674550fbde50da8f6a15acc/assets/resources/scriptlets.js#L308)

and in the uBlock PRs give the example on how to use it like this:
```
brave.com##+js(aeld, click, , log, 1)
```

So how to log addEventListener inside Brave? was it meant to be working or it is planned to be supported or I am just doing it wrong @pes10k?

For now I just kept and added the old `addEventListener-logger.js` scriptlet to the brave's resources.json file, just like how I add my own scriptlets and use it that way.
99% of people might not need it, but for example, to make a rule like this `tiktok.com##+js(aeld, visibilitychange, document)` so tiktok videos don't stop when the video is not in focus or you switch tabs, the logging was needed.

Thank you and have a good day!

# Edit:
Doing some investigative work, I found out:

1. the syntax is simpler now and not JSON-like, so the Wiki is outdated and therefore useless, I had to see it in a newer PR to see how truly use the logging. https://github.com/gorhill/uBlock/commit/1d9ee00498584b8370840de297e748295b6f472f

2. It seems that the logging and debugging only works in the development version of uBlock or by setting to true filterAuthorMode in the advanced settings, so it adds this to the scriptlet which can be seen easily with the debugScriptlets, and it works automatically in Dev version of uBlock because of this https://github.com/brave/uBlock/blob/862ee273db5203a075a6a0909e46e2c3b0f05700/src/js/scriptlet-filtering.js#L401
``` 
a const scriptletGlobals = new Map([
  [
    "canDebug",
    true
  ]
]);
```

3. But then, because of that information, I remembered I saw a comment by @antonok-edm https://github.com/brave/uBlock/pull/101#issuecomment-1494758480 
> should be alright without any changes; we won't be setting this so it's effectively a no-op
> 
> ```js
> scriptletGlobals.has('canDebug')
> ```

So, do I understand correctly that it is a no no, (or at least for now?) which means that the only workaround to log addEventListeners is to use uBlock or unofficially add the deprecated and removed `addEventListener-logger.js` back to the resources.json file?

I don't understand uBlock changes sometimes.

**Comment by antonok-edm** [comment]
> So, do I understand correctly that it is a no no, (or at least for now?) which means that the only workaround to log addEventListeners is to use uBlock or unofficially add the deprecated and removed `addEventListener-logger.js` back to the resources.json file?

Yep, that's basically correct. There's been a lot of updates to the uBO resources recently in places that historically haven't been changed, and we don't exactly get advance notice :sweat_smile: 

I might be able to quickly add a `brave://flags` configuration to set `canDebug` in `scriptletGlobals`, if that would be useful.

**Comment by Emi-TheDhamphirInLoveUnderTheFrozenStar** [comment]
Yeah sometimes it seems they add unnecessary changes, the most annoying part is how the Wiki is outdated as well, but it's his project, it affects Brave though, so I care about it! I know you have been working in the past months to make sure not much breaks with the new changes!

And a flag with the canDebug, would be great!
Logging the addEventListener is necessary for users to get rid of anti-right-click pages, and the TikTok or Instagram stopping the video on tab change, or well, something more important to stop some anti-adblock. 613 rules use it, not many, but without the logging would be harder to create them. So, being able to use it without having to keep adding the old scriptlet, would be awesome.

Thanks!

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS`  using

```
Brave | 1.58.80 Chromium: 116.0.5845.51 (Official Build) nightly (64-bit)
-- | --
Revision | 4408cc9795df260c5d5f033660ce757782b53b32
OS | Windows 10 Version 22H2 (Build 19045.3271)
```

example | example
----------|----------
![image](https://github.com/brave/brave-browser/assets/387249/fc8c6dfd-e3b0-420f-ae87-161614960fb1) | ![image](https://github.com/brave/brave-browser/assets/387249/aeb59353-4bdc-4fc3-abab-9a0752261436)

**Comment by midnight-wonderer** [comment]
### Is this still working?
Hi, I have discovered this feature recently.

I
* enabled the flag (and relaunch)
* insert `reddit.com##+js(aeld)`; according to the wiki, this should log all event listeners.
* try browsing reddit
* I also tried `+js(aeld, click, , log, 1)` variant mentioned in the PR.

Nothing gets logged. I wonder if there is something wrong on my part or if the feature is not supported anymore.
