### ISSUE TITLE
History clearing for Brave AI chat

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#31441]
Add a checkbox to clear "Leo assistant history" in brave://settings/clearBrowserData (Both on Advanced and On Exit tabs):
<img width="1291" alt="Screenshot 2023-07-17 at 10 33 41 AM" src="https://github.com/brave/brave-browser/assets/5951041/574c0718-27e7-4580-8515-87340ba38bf1">

It should call some empty handlers for now since there is no chat history to clear

The clear in brave://settings/leo-assistant should have only 1 link and it should have a dialog to confirm when you clear. This one will in the future clear history. But it will also continue to clear the opt-in status and reset any other future settings related to our browser AI. 

Here is how the confirmation dialog should be:
<img width="1162" alt="Screenshot 2023-07-17 at 10 33 18 AM" src="https://github.com/brave/brave-browser/assets/5951041/651070cf-46eb-43a5-b5b7-a3c0437a53da">

Text should read:

Reset Brave Leo
Resetting the Leo assistant will require you to opt-in to use Brave Leo in the future and will also clear your chat history.  Clearing your chat history will delete all your previous conversations with Brave Leo. This action cannot be undone.

**Comment by aguscruiz** [comment]
I like having it as a checkbox on the clear browsing data panel. 

Also, Added a separate button in Leo Settings to clear chat history so you users don't have to clear all Leo data along with it.

https://www.figma.com/file/h7fKSJF2P556bZWfyLTfwD/Brave-AI?type=design&node-id=1105%3A28709&mode=design&t=a3n39VowDTWloKOM-1

**Comment by bbondy** [comment]
Comment 0 is updated with the latest.

**Comment by fmarier** [comment]
> I like having it as a checkbox on the clear browsing data panel.

That also seems to me like the most natural way to do this.

So maybe we could have two separate things:
- "Leo chat history" checkbox in `brave://settings/clearBrowserData` (both _Advanced_ and _On exit_ tabs).
- "Reset and clear Leo data" in  `brave://settings/leo-assistant`.

**Comment by bbondy** [comment]
Updated comment 0 again with the latest understanding of the work. You should be good to go @vadimstruts

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.60.89 Chromium: 118.0.5993.70 (Official Build) beta (x86_64)
-- | --
Revision | 801f851e0c0664d110cccd46708cd084a83c3729
OS | macOS Version 11.7.10 (Build 20G1427)
```

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version:

```
Brave	1.60.109 Chromium: 119.0.6045.59 (Official Build) (64-bit) 
Revision	fc399c7c433510eb03c2b35281bf8935804b99de
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
Note: This is still in progress on Android and not ready for testing. 

Encountered: https://github.com/brave/brave-browser/issues/34018
