### ISSUE TITLE
Videos on Amazon Prime not playable

### ISSUE THREAD

**Issue by AstroGD** [brave/brave-browser#3144]
## Description 
Videos on Amazon Prime are not playable - EVEN WITH SHIELDS DOWN!
Tried for 30 Minutes and did not find a workaround.

## Steps to Reproduce

   1. Go to Amazon.de
   2. Watch any Prime Video
   3. Disable Shields or leave them enabled
   4. Error occurres

## Actual result:
![image](https://user-images.githubusercontent.com/35271072/51929333-3d5edf00-23f8-11e9-845c-bc604a6e8057.png)
Video does not play and instead throws an error

## Expected result:
Video should play normal

## Reproduces how often: 
Easily reproduced 100% of tries

## Brave version (brave://version info)
0.58.21 Chromium: 71.0.3578.98 (Offizieller Build) (64-Bit)
15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Not tried yet

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
No
- Is the issue reproducible on the latest version of Chrome? 
No

**Comment by kjozwiak** [comment]
@AstroGD, this was actually fixed in `0.59.x` in https://github.com/brave/brave-browser/issues/1985 which is being released on Thursday. I'm going to close this off for now but once `0.59.x` is released and you're still experiencing issues, please re-open the issue 👍

**Comment by AstroGD** [comment]
@kjozwiak Thank you very much for your fast reply. Ill reopen the issue if I encounter this problem after the update.

**Comment by AstroGD** [comment]
I 've just seen something: I have Widevine installed. This is not the same error telling that Widevine is missing.

**Comment by kjozwiak** [comment]
@AstroGD lets see if it works tomorrow when `0.59.x` is released. If you're still having issues, re-open the issue and we'll take a look and see if we can figure out what's going on 👍

**Comment by AstroGD** [comment]
Okay

**Comment by kjozwiak** [comment]
@AstroGD we ran into some issues last night. We're actually about to release in the next ~1hr or so. Should be receiving an update shortly.

**Comment by AstroGD** [comment]
Ah I see. Its downloading right now. Thanks for the quick response

**Comment by AstroGD** [comment]
@kjozwiak Tested it with the new version. Problem still occurs. There was just one improvement: The Video now plays with Shields down for around 5 Seconds and then the error message pops up. Note: I am using the german website of amazon and amazon prime, could be important maybe?
I have widevine installed, because I searched for this error and visited netflix to get the installation notification.
