### ISSUE TITLE
Side panel that not manged by sidebar model should be handled properly

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#31446]
## Description 

Extension side panel is not managed by sidebar model . so it's icon is not shown in sidebar UI.
Regardless of it, extension side panel is not restored when active tab is changed and previous tab has tab specific panel.

## Steps to Reproduce

STR 1.
   1. Enable AI chat feature flag from brave://flags
   2. Install any extension side panel ex, https://chrome.google.com/webstore/detail/flow-chatgpt-sidebar/ndmldohefgmnciihihioeeoiobchcmgi/related
   3. Relaunch
   4. Open extension side panel at Tab A
   5. Create another tab(Tab B) and check side panel is still opened
   6. Open Brave AI side panel item at Tab B
   7. Activate Tab A

STR 2. (NOTE, this STR is only available in nightly)
  1. Enable Playlist feature from brave://flags and relaunch
  2. Remove playlist item from sidebar UI
  3. Load any youtube clip and click playlist action icon from location bar
  4. Click `Open in playlist` from playlist bubble

## Actual result:

STR1 - Side panel is closed
STR2 - Nothing happened

## Expected result:
STR1 - Extension side panel should be opened
STR2 - Playlist side panel is opened

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

When active tab is changed from Tab A(that has per-tab sidebar item) to Tab B, another sidebar item should be opened if global tab was used. This issue happens because extension side panel is not set as browser-wide panel yet.

**Comment by LaurenWags** [comment]
@simonhong are there any other steps/cases to verify the above as AI Chat is only available on Nightly and Playlist is still in active development? If not, perhaps we should `QA/No` this one for now.

Also, changing to `release-notes/exclude` as AI Chat and Playlist will not be released with this milestone.

cc @rebron @kjozwiak

**Comment by simonhong** [comment]
@LaurenWags Don't have other STRs. Let's set `QA/No` for now.

**Comment by LaurenWags** [comment]
gotcha, sounds good. thanks @simonhong!

@rebron @kjozwiak changing this one to `QA/No`.
