### ISSUE TITLE
Swap activity info not displaying in Wallet Panel views

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#31456]
## Description 

When viewing the wallet activity panel, `swap` transactions are rendered without summary text. only the confirmation status and relative date info is shown

## Steps to Reproduce

   1. Submit a swap transaction
   2. Open the panel
   3. view the Activity tab
   4. observe the listing in the activity list

## Actual result:

Summary info text is missing

![Screenshot 2023-06-30 at 14 38 02](https://github.com/brave/brave-browser/assets/30185185/db108302-6ed5-462d-b330-8e82a4125644)

## Expected result:
Summary text should be visible
![Screenshot 2023-07-05 at 11 02 17 AM](https://github.com/brave/brave-browser/assets/30185185/fc33d214-2e32-4dc6-876a-8d9f6fb1a27c)

## Version/Channel Information:

Nightly

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.57.41` or higher for `1.57.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.57.41 Chromium: 115.0.5790.171 (Official Build) beta (64-bit)
-- | --
Revision | adc7e3e2defac3f9b39cb22bcbb354b72b74c2eb
OS | Windows 11 Version 22H2 (Build 22621.2134)

- Verified steps from issue description
- Verified Swap transactions are shown on panel

https://github.com/brave/brave-browser/assets/17010094/1265fe4e-2d31-4b13-8dc5-abfbff872ba6
