### ISSUE TITLE
Upgrade from 72.0.3626.71 to 72.0.3626.81

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#3146]
QA notes:

* Check version matches
* Look for new elements needing to be branded

**Comment by GeetaSarvadnya** [comment]
Verification passed on



Brave | 0.59.32 Chromium: 72.0.3626.81 (Official Build) (64-bit)
-- | --
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS | Windows 10
