### ISSUE TITLE
Create an admin policy for disabling Browser-AI related functionality

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#31461]
We should have a way for admins to disable all functionality related to Browser-AI

**Comment by bbondy** [comment]
As a workaround until we implement this feature. Network admins can disable HTTPS access to ai-chat.bsg.brave.com for the time being to effectively break the feature.

**Comment by petemill** [comment]
Can admins force any feature flag to disabled?

**Comment by bbondy** [comment]
I don't think so

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.64.97 Chromium: 122.0.6261.111 (Official Build) beta (x86_64)
-- | --
Revision | f7c8f13563bfe1063db456650cb43207e1c960c0
OS | macOS Version 13.6.4 (Build 22G513)
```

**Comment by hffvld** [comment]
Hi @darkdh  does this apply for Android, if so, can you provide a test plan, please?

**Comment by darkdh** [comment]
No, any group policies we added never get tested on Android. Setting up the cloud test server is complex
https://www.chromium.org/developers/how-tos/enterprise/running-the-cloud-policy-test-server/

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave	1.64.104 Chromium: 123.0.6312.46 (Official Build) (64-bit) 
Revision	0ca3d372cf8aab96fafdd75f5c5c8d2012bc0cc6
OS	Linux
```

<img width="815" alt="Screen Shot 2024-03-14 at 4 05 08 PM" src="https://github.com/brave/brave-browser/assets/387249/1f26d647-0da2-4bef-b712-420f609c8dea">

<img width="1193" alt="Screen Shot 2024-03-14 at 4 02 55 PM" src="https://github.com/brave/brave-browser/assets/387249/d42525d1-3d87-47da-a500-2822738b63c8">
<img width="1193" alt="Screen Shot 2024-03-14 at 4 03 09 PM" src="https://github.com/brave/brave-browser/assets/387249/c263de93-cccc-4bbe-92aa-1e09002e57c7">
<img width="1193" alt="Screen Shot 2024-03-14 at 4 03 25 PM" src="https://github.com/brave/brave-browser/assets/387249/b97936b1-0df2-455f-bbbb-2aafa81c7ce7">
<img width="1193" alt="Screen Shot 2024-03-14 at 4 03 37 PM" src="https://github.com/brave/brave-browser/assets/387249/00b3949c-e813-4e81-8f53-166fce34eddc">
<img width="1193" alt="Screen Shot 2024-03-14 at 4 03 54 PM" src="https://github.com/brave/brave-browser/assets/387249/cd8cd9d7-e5f0-4528-aa63-6deee5ec0ec4">
