### ISSUE TITLE
Crash in brave_ads::*AdHandler::TriggerEvent

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#31472]
```
[ 00 ] base::ImmediateCrash() ( immediate_crash.h:148 )
[ 01 ] logging::CheckFailure() ( check.h:184 )
[ 02 ] brave_ads::NotificationAdHandler::TriggerEvent(std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char>> const&, brave_ads::mojom::NotificationAdEventType, base::OnceCallback<void (bool)>) ( notification_ad_handler.cc:97 )
[ 03 ] bat_ads::mojom::BatAdsStubDispatch::AcceptWithResponder(bat_ads::mojom::BatAds*, mojo::Message*, std::__Cr::unique_ptr<mojo::MessageReceiverWithStatus, std::__Cr::default_delete<mojo::MessageReceiverWithStatus>>) ( bat_ads.mojom.cc:16980 )
[ 04 ] mojo::InterfaceEndpointClient::HandleValidatedMessage(mojo::Message*) ( interface_endpoint_client.cc:970 )
[ 05 ] mojo::MessageDispatcher::Accept(mojo::Message*) ( interface_endpoint_client.cc:363 )
[ 06 ] mojo::InterfaceEndpointClient::HandleIncomingMessage(mojo::Message*) ( interface_endpoint_client.cc:701 )
[ 07 ] mojo::internal::MultiplexRouter::ProcessIncomingMessage(mojo::internal::MultiplexRouter::MessageWrapper*, mojo::internal::MultiplexRouter::ClientCallBehavior, base::SequencedTaskRunner*) ( multiplex_router.cc:1096 )
[ 08 ] mojo::internal::MultiplexRouter::ProcessTasks(mojo::internal::MultiplexRouter::ClientCallBehavior, base::SequencedTaskRunner*) ( multiplex_router.cc:925 )
[ 09 ] mojo::internal::MultiplexRouter::LockAndCallProcessTasks() ( multiplex_router.cc:1124 )
[ 10 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::LazyNow*) ( callback.h:152 )
[ 11 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() ( thread_controller_with_message_pump_impl.cc:351 )
[ 12 ] non-virtual thunk to base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() ( thread_controller_with_message_pump_impl.cc:0 )
[ 13 ] base::MessagePumpDefault::Run(base::MessagePump::Delegate*) ( message_pump_default.cc:40 )
[ 14 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool, base::TimeDelta) ( thread_controller_with_message_pump_impl.cc:651 )
[ 15 ] non-virtual thunk to base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool, base::TimeDelta) ( thread_controller_with_message_pump_impl.cc:0 )
[ 16 ] base::RunLoop::Run(base::Location const&) ( run_loop.cc:134 )
[ 17 ] content::UtilityMain(content::MainFunctionParams) ( utility_main.cc:392 )
[ 18 ] content::RunOtherNamedProcessTypeMain(std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char>> const&, content::MainFunctionParams, content::ContentMainDelegate*) ( content_main_runner_impl.cc:767 )
[ 19 ] content::ContentMainRunnerImpl::Run() ( content_main_runner_impl.cc:1140 )
[ 20 ] content::RunContentProcess(content::ContentMainParams, content::ContentMainRunner*) ( content_main.cc:326 )
[ 21 ] content::ContentMain(content::ContentMainParams) ( content_main.cc:343 )
[ 22 ] ChromeMain ( chrome_main.cc:187 )
[ 23 ] main ( chrome_exe_main_mac.cc:216 )
[ 24 ] 0x7ff805ddd41f
[ 25 ] 0x7ff805ddd5a0
[ 26 ] 0x7ff805ddd536
[ 27 ] AutoreleasePoolPage::print()
[ 28 ] 0x7ff805ddc070
```

https://brave.sp.backtrace.io/p/brave/triage?time=month&filters=W1siY2FsbHN0YWNrIiwiY29udGFpbnMiLCJicmF2ZV9hZHM6Ok5vdGlmaWNhdGlvbkFkSGFuZGxlcjo6VHJpZ2dlckV2ZW50KHN0ZDo6X19Dcjo6YmFzaWNfc3RyaW5nPGNoYXIsIHN0ZDo6X19Dcjo6Y2hhcl90cmFpdHM8Y2hhcj4sIHN0ZDo6X19Dcjo6YWxsb2NhdG9yPGNoYXI%2BPiBjb25zdCYsIGJyYXZlX2Fkczo6bW9qb206Ok5vdGlmaWNhdGlvbkFkRXZlbnRUeXBlLCBiYXNlOjpPbmNlQ2FsbGJhY2s8dm9pZCAoYm9vbCk%2BKSJdLFsiZmluZ2VycHJpbnQ7aXNzdWVzO3N0YXRlIiwiZXF1YWwiLCJvcGVuIl0sWyJjYWxsc3RhY2siLCJjb250YWlucyIsImJyYXZlX2FkcyJdXQ%3D%3D&aggregations=((ver%2Cmax)%2C(guid%2Cunique)%2C(classifiers%2Chead))&similarity=false

**Comment by tmancey** [comment]
STR:

- Join Brave Rewards
- View a push notification ad
- Wait until the notification ad moves to the system tray
- Reset Brave Rewards
- Click push notification ad in the system tray

EXPECTED RESULT: Brave ads should not crash
ACTUAL RESULT: Brave ads crashes

**Comment by kjozwiak** [comment]
The above requires `1.58.107` or higher for `1.58.x` verification 👍

**Comment by btlechowski** [comment]
Verification PASSED

Brave | 1.58.97 Chromium: 116.0.5845.96 (Official Build) beta (64-bit)
-- | --
Revision | c983323d5ff7738a3c8d3bf491a7241c24b4d65a
OS | Linux


Verified test plan from https://github.com/brave/brave-browser/issues/31472#issuecomment-1690319185

Verified ad was shown:

![image](https://github.com/brave/brave-browser/assets/34715963/4644ba4f-40c9-4426-8369-9552256cea7b)

Verified ad was hidden after resetting rewards and no crash
![image](https://github.com/brave/brave-browser/assets/34715963/e113837a-0779-47b0-bb04-8e03af427fd3)

**Comment by btlechowski** [comment]
Verification passed on Brave v1.58.121 on Lenovo TB-8506FS (Android 11.0)


Verified test plan from https://github.com/brave/brave-browser/issues/31472#issuecomment-1690319185


Verified ad was shown and placed in notification center

![image](https://github.com/brave/brave-browser/assets/34715963/0b5dc734-41a2-4ca4-9276-ba6577f5be04)

Reset Rewards:
![image](https://github.com/brave/brave-browser/assets/34715963/34c3bbee-84e2-418e-9525-86cab8cf1675)

No crash after clicking the ad in the notification center
![image](https://github.com/brave/brave-browser/assets/34715963/f2ef5236-5c54-424d-8ee2-3adf2e2f5003)
