### ISSUE TITLE
Texts not looking good

### ISSUE THREAD

**Issue by jahirfiquitiva** [brave/brave-browser#3147]
## Description 

I just started trying Brave and I like it so far, except for this thing with the texts or fonts rendering, which does not happen in menus only, but also in many websites.

## Steps to Reproduce

   1. Open a menu in Chrome and Brave and compare the look between them.

## Actual result:

**Menu in Chrome vs Brave**

![image](https://user-images.githubusercontent.com/815158/51944693-5066b480-23e2-11e9-83d6-4afaf0182c2a.png)

## Expected result:
Normal looking texts, just like in Chrome

## Reproduces how often: 

Always, aka all the time.

## Brave version (brave://version info)

Brave | 0.58.21 Chromium: 71.0.3578.98 (Build oficial) (64 bits)
-- | --
Revisión | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
SO | Mac OS X
JavaScript | V8 7.1.302.31
Flash | (Disabled)
User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
I don't know.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
No
- Is the issue reproducible on the latest version of Chrome? 
No

### Additional Information

No

**Comment by thepcwiz101** [comment]
Unlikely to be changed unless enough people complain about it. Recommend tags for the devs are Priority 5 and macOS,

**Comment by petemill** [comment]
Could be to do with different gpu settings via https://github.com/brave/brave-browser/issues/3105?

**Comment by jahirfiquitiva** [comment]
@rebron Yep ... With the new release everything looks much better! Thank you!

**Comment by srirambv** [comment]
Closing based on last comment
