### ISSUE TITLE
`Backspace` and other lengthy text overflows its fixed borders

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#31482]
## Description 

`Backspace` and other lengthy text overflows its fixed borders

## Steps to Reproduce

1. install `1.55.99`
2. launch Brave
3. click on `System`
4. click on `Shortcuts`
5. click on `Add` for any shortcut
6. start pressing multiple-key combinations (as shown in screenshot) 3 or 4, including `Backspace` or other lengthy words will do

## Actual result:

<img width="1986" alt="Screen Shot 2023-07-05 at 11 51 40 PM" src="https://github.com/brave/brave-browser/assets/387249/7d337a87-b116-4e0a-9349-05492ca65d31">

## Expected result:

More-readable text

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.55.99 Chromium: 115.0.5790.56 (Official Build) nightly (x86_64)
-- | --
Revision | 0a52c26fd8c1f5cd75774ca72dce80859aac23fd
OS | macOS Version 11.7.8 (Build 20G1351)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

/cc @fallaciousreasoning @rebron @brave/qa-team

**Comment by MadhaviSeelam** [comment]
Reproduced the issue in Win 11 
```
Brave | 1.56.1 Chromium: 115.0.5790.75 (Official Build) (64-bit)
-- | --
Revision | 3433e4d513e8454ba0243deea3d53693661dc0c3-refs/branch-heads/5790@{#1430}
OS | Windows 11 Version 22H2 (Build 22621.1928)
```

![image](https://github.com/brave/brave-browser/assets/98358127/cb545029-39e2-4d99-9564-cd5d201930b9)

**Comment by fallaciousreasoning** [comment]
Hopefully this is fixed in 1.58.x

**Comment by stephendonner** [comment]
> Hopefully this is fixed in 1.58.x - I'll create an uplift.

Fine with `1.54.14`

![Screen Shot 2023-07-12 at 4 05 45 PM](https://github.com/brave/brave-browser/assets/387249/4cca0d16-2ab9-49c0-bc48-8c64f53cf597)

**Comment by LaurenWags** [comment]
@brave/qa-team this requires 1.56.6 or higher for 1.56.x verification.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.56.6 Chromium: 115.0.5790.90 (Official Build) (x86_64)
-- | --
Revision | 86fb9d04c92b490e6cc0026ca58cb1a98735eea3-refs/branch-heads/5790@{#1583}
OS | macOS Version 13.4.1 (a) (Build 22F770820b)
```

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.56.6 Chromium: 115.0.5790.90 (Official Build) (64-bit)
-- | --
Revision | 86fb9d04c92b490e6cc0026ca58cb1a98735eea3-refs/branch-heads/5790@{#1583}
OS | Linux
```

Verified using original STR from https://github.com/brave/brave-browser/issues/31482#issue-1790946314

Confirmed labels were within their containers, and wrapped keys accordingly

![image](https://github.com/brave/brave-browser/assets/98358127/48aba290-bcd7-41cf-b204-eee5c1843a0a)
