### ISSUE TITLE
Payout Status Banner 2.0: Update client-side payout status countdown logic and text

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#31480]
## Description

Update payout status banner logic and text.

## Solution

**1. WILL BEGIN BANNER:** From 1st of month to payment date, say “The payout for [previous month] rewards will begin processing by [payment date]”
**2. PROCESSING BANNER:** If “processing” at `/parameters`, show “The payout for [previous month] rewards is in progress. **Check status**”
**3. COMPLETE BANNER:** If “complete” at `/parameters`, show “The payout for [previous month] rewards has completed. **Support**” ("Support" links out to community.brave.com)

* "processing" and "complete" values from `/parameters` will take precedence over WILL BEGIN BANNER.
* WILL BEGIN BANNER takes precedence over "off" from /parameters.

**Comment by GeetaSarvadnya** [comment]
@emerick @Miyayes Could you review the cases above and let me know if I missed anything. Thanks!

**Comment by Miyayes** [comment]
@GeetaSarvadnya I think the only other test case is this:

1. Set date to 1-7th of the month, and set /parameters to "complete" or "processing". 

In these cases, the COMPLETE and PROCESSING banners should show, and the WILL BEGIN BANNER should _not_ show.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.58.100 Chromium: 116.0.5845.114 (Official Build) beta (x86_64)
-- | --
Revision | a8c0058265009a1858c4502b9ba413671fbb61e1
OS | macOS Version 13.5 (Build 22G74)
```

**Comment by btlechowski** [comment]
Verified PASSED

Brave | 1.58.120 Chromium: 117.0.5938.48 (Official Build) (64-bit)
-- | --
Revision | 8b2e2785c90c076fc1413acb2c003e603eac02d3
OS | Linux

- Verified the description from https://github.com/brave/brave-browser/issues/31480#issue-1790732774

```
- If `complete` is set on the /parameter endpoint, we show the message `The payout for xxx rewards has completed`
- If `processing` is set on the /parameter endpoint, we show the message `The payout for xxx rewards is in progress`
- If neither of those are set on the /parameter endpoint, then we show `The payout for xxx rewards will begin processing by yyy`
```

<details>
<summary>Payout begin banner - PASSED</summary>

1. Clean profile 1.58.x
2. Enable rewards and connect a custodian
3. View a couple of Ads and confirm ads are cashed in with the server
4. Close the browser
5. Advance the sys clock to any date between 1st to 7th of next month (I have set date as 1st Oct)
6. Use Charles Proxy to simulate pending message being returned from the `/parameter` endpoint (I have set empty string for the gemini custodian)
7. Relaunch the browser
8. Confirmed that “The payout for [previous month] rewards will begin processing by [payment date]” message is shown in the rewards settings page, BR Panel and NTP

```
> Url: https://api.rewards.bravesoftware.com/v1/parameters
> Result: Success
> HTTP Code: 200
> Body: {"autocontribute":{"choices":[1,2,3,5,7,10,20],"defaultChoice":1},"batRate":0.173384,"custodianRegions":{"bitflyer":{"allow":["JP"],"block":[]},"gemini":{"allow":["US","CA","SG","GB"],"block":[]},"uphold":{"allow":["AD","AU","AR","AT","BE","BR","BS","BZ","CA","CH","CL","CO","CR","CY","CZ","DK","EC","EE","FI","FR","GD","GT","GR","HK","HN","HU","IE","IS","IT","JM","KY","LI","LT","LV","LU","MC","MT","MX","NI","NO","NZ","PE","PT","PY","SG","TR","UY","ES","SE","GB","US","UM","ZA","PL","SK","HR","SI","GR","TW"],"block":[]},"zebpay":{"allow":["IN"],"block":[]}},"payoutStatus":{"bitflyer":"","gemini":"","payoutDate":"","unverified":"","uphold":"","zebpay":""},"tips":{"defaultMonthlyChoices":[1.25,5,10.5],"defaultTipChoices":[1.25,5,10.5]},"vbatExpired":false}

```

brave://rewards | BR Panel | NTP
------------------|-----------|-------
![image](https://github.com/brave/brave-browser/assets/34715963/51e3919d-7128-4c96-944d-1d8b133d2894)|![image](https://github.com/brave/brave-browser/assets/34715963/598878d0-3c57-4e5e-a55b-9f64df51e69f)|![image](https://github.com/brave/brave-browser/assets/34715963/915d7507-252f-4cdb-9509-09936a1018ed)


9. Close the browser
10. Set the system date to payout date or after the payout date (I used Oct 10)
11. Relaunch the browser
12. Confirmed that the payout pending banner is not shown


![image](https://github.com/brave/brave-browser/assets/34715963/829a528c-f1e5-4cb3-ae90-b13df9026052)|![image](https://github.com/brave/brave-browser/assets/34715963/f3634f70-2660-4a51-915a-cba682e88782)
--|--

13. Confirmed that empty string payout status is returned from the `/parameters` endpoint

```
> Url: https://api.rewards.bravesoftware.com/v1/parameters
> Result: Success
> HTTP Code: 200
> Body: {"autocontribute":{"choices":[1,2,3,5,7,10,20],"defaultChoice":1},"batRate":0.173384,"custodianRegions":{"bitflyer":{"allow":["JP"],"block":[]},"gemini":{"allow":["US","CA","SG","GB"],"block":[]},"uphold":{"allow":["AD","AU","AR","AT","BE","BR","BS","BZ","CA","CH","CL","CO","CR","CY","CZ","DK","EC","EE","FI","FR","GD","GT","GR","HK","HN","HU","IE","IS","IT","JM","KY","LI","LT","LV","LU","MC","MT","MX","NI","NO","NZ","PE","PT","PY","SG","TR","UY","ES","SE","GB","US","UM","ZA","PL","SK","HR","SI","GR","TW"],"block":[]},"zebpay":{"allow":["IN"],"block":[]}},"payoutStatus":{"bitflyer":"","gemini":"","payoutDate":"","unverified":"","uphold":"","zebpay":""},"tips":{"defaultMonthlyChoices":[1.25,5,10.5],"defaultTipChoices":[1.25,5,10.5]},"vbatExpired":false}

```

</details>

<details>
<summary>Processing banner - PASSED</summary>

1. Clean profile 1.58.x
2. Enable rewards and connect a custodian
3. View a couple of Ads and confirm ads are cashed in with the server
4. Close the browser
5. Advance the sys clock to any date in the next month (I set date to Oct 10)
6. Use Charles Proxy to simulate "Processing" message being returned from the `/parameter` endpoint
7. Relaunch the browser
8. Confirmed that “The payout for [previous month] rewards is in progress. Check status” message is shown in the rewards settings page, BR Panel and NTP
9. Confirmed that click on the "Check status" link redirects to `https://community.brave.com/t/ads-payout-status-update/287895` page

brave://rewards | BR Panel | NTP
------------------|-----------|-------
![image](https://github.com/brave/brave-browser/assets/34715963/c846e598-4752-4ca9-a759-8bb3f1619d7f)|![image](https://github.com/brave/brave-browser/assets/34715963/0a2f4108-3242-491c-a5bd-7a8492550499)|![image](https://github.com/brave/brave-browser/assets/34715963/17cdfb54-9946-4450-8ecf-e944f7661e1f)


10. Confirmed that “processing” payout status is returned from the `/parameters` endpoint

```
[ RESPONSE - OnResponse ]
> Url: https://api.rewards.bravesoftware.com/v1/parameters
> Result: Success
> HTTP Code: 200
> Body: {"autocontribute":{"choices":[1,2,3,5,7,10,20],"defaultChoice":1},"batRate":0.173384,"custodianRegions":{"bitflyer":{"allow":["JP"],"block":[]},"gemini":{"allow":["US","CA","SG","GB"],"block":[]},"uphold":{"allow":["AD","AU","AR","AT","BE","BR","BS","BZ","CA","CH","CL","CO","CR","CY","CZ","DK","EC","EE","FI","FR","GD","GT","GR","HK","HN","HU","IE","IS","IT","JM","KY","LI","LT","LV","LU","MC","MT","MX","NI","NO","NZ","PE","PT","PY","SG","TR","UY","ES","SE","GB","US","UM","ZA","PL","SK","HR","SI","GR","TW"],"block":[]},"zebpay":{"allow":["IN"],"block":[]}},"payoutStatus":{"bitflyer":"","gemini":"","payoutDate":"","unverified":"","uphold":"processing","zebpay":""},"tips":{"defaultMonthlyChoices":[1.25,5,10.5],"defaultTipChoices":[1.25,5,10.5]},"vbatExpired":false}

```

</details>

<details>
<summary>Complete banner - PASSED</summary>

1. Clean profile 1.58.x
2. Enable rewards and connect a custodian
3. View a couple of Ads and confirm ads are cashed in with the server
4. Close the browser
5. Advance the sys clock to any date in the next month (I set date to Oct 10)
6. Use Charles Proxy to simulate "Complete" message being returned from the `/parameter` endpoint
7. Relaunch the browser
8. Confirmed that “The payout for [previous month] rewards has completed. Support” message is shown with the support link in the rewards settings page, BR Panel and NTP
9. Confirmed that click on the "Support" link redirects to `community.brave.com` page

brave://rewards | BR Panel | NTP
------------------|-----------|-------
![image](https://github.com/brave/brave-browser/assets/34715963/291623cd-207e-413c-ad03-aaf87c2e8f38)|![image](https://github.com/brave/brave-browser/assets/34715963/220b71a0-71a8-4c64-a1d6-cb3e4955f2ac)|![image](https://github.com/brave/brave-browser/assets/34715963/23c34714-bd67-4ea1-aea9-451b2bbb599e)



10.Confirmed that “complete” payout status is returned from the `/parameters` endpoint

```
[ RESPONSE - OnResponse ]
> Url: https://api.rewards.bravesoftware.com/v1/parameters
> Result: Success
> HTTP Code: 200
> Body: {"autocontribute":{"choices":[1,2,3,5,7,10,20],"defaultChoice":1},"batRate":0.173384,"custodianRegions":{"bitflyer":{"allow":["JP"],"block":[]},"gemini":{"allow":["US","CA","SG","GB"],"block":[]},"uphold":{"allow":["AD","AU","AR","AT","BE","BR","BS","BZ","CA","CH","CL","CO","CR","CY","CZ","DK","EC","EE","FI","FR","GD","GT","GR","HK","HN","HU","IE","IS","IT","JM","KY","LI","LT","LV","LU","MC","MT","MX","NI","NO","NZ","PE","PT","PY","SG","TR","UY","ES","SE","GB","US","UM","ZA","PL","SK","HR","SI","GR","TW"],"block":[]},"zebpay":{"allow":["IN"],"block":[]}},"payoutStatus":{"bitflyer":"","gemini":"","payoutDate":"","unverified":"","uphold":"complete","zebpay":""},"tips":{"defaultMonthlyChoices":[1.25,5,10.5],"defaultTipChoices":[1.25,5,10.5]},"vbatExpired":false}


```

</details>

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Samsung Tab A7 version 12` running `Bravemonoarm64.apk_1.58.121`
