### ISSUE TITLE
Hi sorry if this has already been covered but I'm sort of new to this. When trying to download Brave to Fedora I get the following error message- sudo dnf install brave-browser brave-keyring created by dnf config-manager from https://brav 0.0  B/s |   0  B     00:01     Failed to synchronize cache for repo 'brave-browser-rpm-release.s3.brave.come_x86_64_', ignoring this repo. Last metadata expiration check: 0:51:46 ago on Tue 29 Jan 2019 21:49:28 GMT. No match for argument: brave-browser No match for argument: brave-keyring Error: Unable to find a match Can anyone help?

### ISSUE THREAD

**Issue by Droppedyursoap** [brave/brave-browser#3148]
## Steps to Reproduce

   1. 
   2. 
   3. 

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
Hi @Droppedyursoap,

Can you please create another issue that follows the template when creating new issues? Adding everything into the title makes it difficult to narrow down the issue that you're having. Here's an example of an issue that follows the template: https://github.com/brave/brave-browser/issues/3112.

If you're not comfortable creating a ticket, please request for some support under http://community.brave.com where someone can help you and will create a ticket for you if needed.
