### ISSUE TITLE
Add loading skeleton to after refreshing NFT page.

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#31485]
## Description 

Currently, when you refresh the NFT page , the user doesn't know that the page is being refreshed. 
Link to conversation here https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1688551278398419

https://github.com/brave/brave-browser/assets/12224304/a3f1dc01-4ff4-439a-a4e7-e2a950b10cb2

cc @minkyeongshin for designs

## Steps to Reproduce

   1. 
   2. 
   3. 

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by minkyeongshin** [comment]
Design link 
https://www.figma.com/file/muVcmcu4RFNu0LkXe9VRDl/Wallet-2.0?type=design&node-id=5012%3A350339&mode=design&t=bxH3aUjWUfYs1Jlg-1

**Comment by LaurenWags** [comment]
@muliswilliam please add the appropriate missing labels:
- `QA/Yes` or `QA/No`
- `release-notes/include` or `release-notes/exclude`

cc @HEagle18 @kjozwiak @rebron

**Comment by muliswilliam** [comment]
@LaurenWags Done.

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Linux

- Verified steps from [brave/brave-core#19418](https://github.com/brave/brave-core/pull/19418)
- Verified loading skeleton is shown after refreshing NFT page

https://github.com/brave/brave-browser/assets/17010094/5c9d0617-23c2-477f-bc72-3b8383863e1e


---------------------

**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#19418](https://github.com/brave/brave-core/pull/19418)
- Verified loading skeleton is shown after refreshing NFT page

https://github.com/brave/brave-browser/assets/17010094/deba1c06-917b-4098-9da5-39b3b008494d


---------------------

**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (arm64)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | macOS Version 13.4.1 (c) (Build 22F770820d)

- Verified steps from [brave/brave-core#19418](https://github.com/brave/brave-core/pull/19418)
- Verified loading skeleton is shown after refreshing NFT page

https://github.com/brave/brave-browser/assets/17010094/9321fe95-8223-4ae4-af14-8baf89b10868

**Comment by srirambv** [comment]
Removed `OS/Android` as it requires Android specific implementation. cc: @Pavneet-Sing  to log an issue if its already not addressed in another Android specific issue
