### ISSUE TITLE
Use deposit screen from Desktop as web UI in Android

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#31495]

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.58.114 x64 Beta build
- Verified steps from [brave/brave-core#19256](https://github.com/brave/brave-core/pull/19256)
- Verified Deposit option shows deposit screen on a new tab
- Verified able to manually navigate to `brave://wallet/deposit-funds` and still load the deposit screen

Oppo Reno 5 (Android 13) | Lenovo Tab (Android 12)
-- | --
<video src=https://github.com/brave/brave-browser/assets/17010094/6a01437b-6447-498d-8372-7d07bfcfc141> | <video src=https://github.com/brave/brave-browser/assets/17010094/7716b746-5372-4f3c-a318-d8c462dd38cf>
