### ISSUE TITLE
Use buy from desktop as web UI in Android

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#31494]

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.58.117 x64 build
- Verified steps from [brave/brave-core#19334](https://github.com/brave/brave-core/pull/19334)
- Verified Buy opens webUI in a new tab
- Verified able to navigate directly to the route when wallet is enabled
- Verified able to select account on the webui
- Verified account creation works on the buy ui similar to desktop

Oppo Reno 5 (Android 13) | Lenovo Tab (Android 12)
-- | --
<video src=https://github.com/brave/brave-browser/assets/17010094/87a57796-3c4f-40b7-9fc2-ddc99d2e388d> | <video src=https://github.com/brave/brave-browser/assets/17010094/73bfbc10-85d2-4b3a-86cb-3211ed2a442b>
