### ISSUE TITLE
[ads] Fix frequency capping should work across multiple user profiles

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#31500]
Brave ads frequency capping is broken with `ShouldLaunchBraveAdsAsInProcessService` feature enabled.

Investigate deprecating the following as part of this fix:
- [ ]  CacheAdEventForInstanceId
- [ ] GetCachedAdEvents
- [ ] ResetAdEventCacheForInstanceId

**Comment by tmancey** [comment]
Closing as works for me
