### ISSUE TITLE
Show Solana at top in the list of networks

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#31506]
## Description 
Show Solana at top in the list of networks (Everywhere) and sort alphabetically within the group.

## Actual result 
![Screenshot from 2023-07-07 11-10-31](https://github.com/brave/brave-browser/assets/11755381/b77f82a7-cf3f-4412-bcea-bec86ef27ee0)

## Expected result
Show Solana below All networks everywhere, above others and sort alphabetically within the group.

### Additional information

Threads:
- https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1688382379595339?thread_ts=1688373306.010959&cid=C023VS4HJ6Q
- https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1688646673669829

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.58.114 x64 Beta build
- Verified steps from issue description
- Verified Solana is shown on top of network list 
- Encountered [#32791](https://github.com/brave/brave-browser/issues/32791)

https://github.com/brave/brave-browser/assets/17010094/ffc7cc59-a1be-4f40-8f5f-abf31ca054d4
