### ISSUE TITLE
Disconnect vpn and remove the wireguard service on uninstall

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#31507]
## Description 

The wireguard service is not removed if vpn connected during Brave browser uninstall.

## Steps to Reproduce

   1. Connect to Wireguard vpn.
   2. Uninstall Brave

## Actual result:

- VPN remains connected and wireguard executable still in program files

## Expected result:

- Vpn disconnected and Browser files removed with wireguard service files

## Reproduces how often: 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment]
Note for QA - it's important to test uninstalling Brave with this 😄 

If you don't have this fix, Brave won't be able to be uninstalled. You'll have to delete the service manually using `sc.exe`

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

[Windows build ID]

### Brave Installation

example | example | example
---------|----------|--------
![image (2)](https://github.com/brave/brave-browser/assets/387249/9eb7e1da-a59d-497e-9e58-885e7fbea6ab) | ![image (1)](https://github.com/brave/brave-browser/assets/387249/e9dd006f-8c81-4c5e-b8ad-68edbfa84f0a) | ![image](https://github.com/brave/brave-browser/assets/387249/53c7e213-6d95-4702-9097-72b675be6101)

### Brave VPN using WireGuard



`whatismyipaddress.com` | `Windows 10`, `VPN` panel
---------|---------
![image (5)](https://github.com/brave/brave-browser/assets/387249/45b6c65f-9981-4dc9-b13f-6c9d58d6166b) | ![image (6)](https://github.com/brave/brave-browser/assets/387249/59f6718c-b99f-4144-a2f4-4a1eb648df8b)

### Uninstallation


### "Brave" sweep

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.58.91 Chromium: 116.0.5845.96 (Official Build) beta (64-bit)
-- | --
Revision | 620fa9c0307b294dd6e7c6b0976bc1f93fecf369
OS | Windows 11 Version 22H2 (Build 22621.2134)
```

### Steps:
1. installed `1.58.89`
2. launched Brave
3. set `brave://flags/#brave-vpn-wireguard` to `Enabled`
4. clicked `Relaunch`
5. purchased, configured, and connected to `Brave VPN`
6. confirmed I was connected via `WireGuard` to `Brave VPN`, using `whatismyipaddress.com`
7. clicked on the `Windows` logo on the bottom left
8. clicked `Settings`
9. clicked `Apps`
10. selected `Brave Beta` from the list
11. clicked `Uninstall`
12. confirmed choice
13. selected `Also delete your browsing data?`
14. clicked `Uninstall`
15. waited
16. confirmed `Microsoft Edge` launched, post-uninstall

### Confirmed:
* `Brave VPN` w/`WireGuard` was stopped, before returning to complete uninstallation
* was prompted to shut down Brave before resuming uninstallation
* Brave was removed from:
  * "Programs" menu
  * `Apps & Features` menu
  * `Task Manager` (all services)

Brave VPN connected
step 3 | step 6 | 
---- | ----
<img width="644" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/aa9040e2-b9be-495f-9086-8a4beacfae56">|<img width="953" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/73fa2d3b-c784-4829-88ef-4f9474459c1b">

Brave Uninstall

step 11 

<img width="682" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/a2cc987c-7b12-4bd0-a4f5-ba1cf82c794d">
