### ISSUE TITLE
Perf: Wallet is over-selecting redux wallet slice state in some components

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#31511]
## Description 

Some UI components are subscribing to all state changes within the `wallet` slice, instead of the subset of state that the components are consuming.
Refactor the selectors used in these components to utilize the our selector functions instead of selecting the entire slice state to prevent unneeded re-renders.

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.58.105 Chromium: 116.0.5845.114 (Official Build) beta (64-bit)
-- | --
Revision | 5a895596bcd7fcd930dab0714ea5cfa86c5aa0a7
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#19198](https://github.com/brave/brave-core/pull/19198)
- Verified Send/Swap screens work as expected
- Verified currency selection works as expected on Buy screen
- Verified account selection works as expected on Wallet page and in panel
- Verified Dapp connections works as expected
- Verified site permissions works as expected
