### ISSUE TITLE
Deposit screen loads slow compared to other screens

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#31513]
## Description 

Deposit screen loads slow compared to other screens

## Steps to Reproduce

   1. Open Wallet
   2. Go to Deposit screen
   3. Page render is slow

## Actual result:

Deposit screen loads slow compared to other screens

## Expected result:
Should be rendered 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Alll
## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel @StephenHeaps

**Comment by Douglashdaniel** [comment]
Was fixed via https://github.com/brave/brave-core/pull/19306#top
