### ISSUE TITLE
Add toolbar for text to speech

### ISSUE THREAD

**Issue by boocmp** [brave/brave-browser#31540]

**Comment by kjozwiak** [comment]
@brave/qa-team the above is being enabled on `Nightly` via Griffin as per https://github.com/brave/brave-variations/pull/758. Can also use some the STR/Cases that I used via https://github.com/brave/brave-variations/pull/757#issuecomment-1749970998 as a template to verify the above feature. @rebron are we planning on releasing this via `1.60.x`?

**Comment by LaurenWags** [comment]
@rebron as per the above, is there a flag under brave://flags we can use to check this if we don't enable on Beta via Griffin?

**Comment by boocmp** [comment]
You can pass ```--enable-features=Speedreader:tts/true``` to the command line

**Comment by LaurenWags** [comment]
awesome, thanks @boocmp 👍🏻

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.60.86 Chromium: 118.0.5993.54 (Official Build) beta (x86_64)
-- | --
Revision | a174cdee5ce1b329d409f3dd8c450e98b7ff4511
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.60.86`
2. launched Brave using `--enable-features=Speedreader:tts/true`
3. loaded `https://www.vox.com/politics/2023/10/10/23911661/hamas-israel-war-gaza-palestine-explainer`
4. clicked on the `Turn on Speedreader` icon in the URL bar
5. confirmed the article rendered in Speedreader mode
6. clicked on the `Text to speech` headphones icon
7. clicked on `Play`
8. confirmed audio playback with the default voice
9. confirmed I can change voices
10. confirmed I can slow the playback
11. confirmed I can speed up the playback
12. confirmed I can `Pause`
13. confirmed I can `Resume`
14. confirmed I can skip forward
15. confirmed I can skip backward


example | voices | example | `Speed` | `Skip forward` | `Skip backward`
---------|----------|---------|---------|---------------|-----------------
<img width="1412" alt="Screen Shot 2023-10-11 at 2 35 10 PM" src="https://github.com/brave/brave-browser/assets/387249/cc26bcbc-976a-4f16-9979-a52c9e5cd932"> | <img width="159" alt="Screen Shot 2023-10-11 at 2 35 20 PM" src="https://github.com/brave/brave-browser/assets/387249/97d7be23-4273-4381-9518-4f12516e0330"> | <img width="1301" alt="Screen Shot 2023-10-11 at 2 35 45 PM" src="https://github.com/brave/brave-browser/assets/387249/6980abc6-673f-40fa-9972-e0e26a945013"> | <img width="1412" alt="Screen Shot 2023-10-11 at 2 47 10 PM" src="https://github.com/brave/brave-browser/assets/387249/f96c0ecc-5bbf-43fc-9f8c-ae93b60a1a3e"> | <img width="1412" alt="Screen Shot 2023-10-11 at 2 37 55 PM" src="https://github.com/brave/brave-browser/assets/387249/6ac3aa0f-cacb-4c9d-86e8-0588a61381cc"> | <img width="1412" alt="Screen Shot 2023-10-11 at 2 37 59 PM" src="https://github.com/brave/brave-browser/assets/387249/11ac1926-2727-4ce1-b7f7-e8faa70f4751">

**Comment by btlechowski** [comment]
Verified with

Brave | 1.60.102 Chromium: 118.0.5993.96 (Official Build) beta (64-bit)
-- | --
Revision | 3598a9fc6b7752181feb25caa131bc386d6d054c
OS | Linux

### Steps:
1. installed `1.60.x`
2. launched Brave using `--enable-features=Speedreader:tts/true`
3. loaded `https://www.vox.com/politics/2023/10/10/23911661/hamas-israel-war-gaza-palestine-explainer`
4. clicked on the `Turn on Speedreader` icon in the URL bar
5. confirmed the article rendered in Speedreader mode
6. clicked on the `Text to speech` headphones icon
7. clicked on `Play`
8. confirmed audio playback with the default voice
9. confirmed I can change voices
10. confirmed I can slow the playback
11. confirmed I can speed up the playback
12. confirmed I can `Pause`
13. confirmed I can `Resume`
14. confirmed I can skip forward
15. confirmed I can skip backward

<details>

![image](https://github.com/brave/brave-browser/assets/34715963/6bccf093-8f2c-4e1c-bf39-9f2b39ad476d)
![image](https://github.com/brave/brave-browser/assets/34715963/9fd8629d-29cf-4b35-9804-73bb82c0cd05)



</details>
