### ISSUE TITLE
Google Sheets does not work on Windows (Nightly)

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#31544]
## Description 
Opening Google Sheets appears to work for a moment - but then an error message is shown.

Ultimately, you can't use the site.

## Steps to Reproduce

   1. Be on Windows with latest Nightly
   2. Load https://docs.google.com/spreadsheets/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms/edit#gid=0
   3. Wait a few seconds

## Actual result:
After a few seconds, the following is shown:
![image](https://github.com/brave/brave-browser/assets/4733304/fe4b5994-0736-4d9f-b0aa-deeddc45fc03)

When you click `OK`, the following is shown:
![image](https://github.com/brave/brave-browser/assets/4733304/c144acab-4021-4139-87d9-0eef9bd24777)

If you click `Refresh`, the loop starts over again

## Expected result:
You should be able to use the Google Sheet

## Reproduces how often: 
100%

## Brave version (brave://version info)
1.58.2 Chromium: 115.0.5790.56 (Official Build) nightly (64-bit) 

## Version/Channel Information:

- Can you reproduce this issue with the current release?  NO
- Can you reproduce this issue with the beta channel?  NO
- Can you reproduce this issue with the nightly channel?  YES

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NO
- Does the issue resolve itself when disabling Brave Rewards? NO
- Is the issue reproducible on the latest version of Chrome? NO (checked Canary too)

**Comment by bsclifton** [comment]
Found regression range:
`1.55.102` = problem happens here
`1.55.92` = problem does NOT happen here

**Comment by bsclifton** [comment]
Does not appear to be related to variations server - thanks to @jonathansampson for asking about and helping rule that out

**Comment by jonathansampson** [comment]
In my testing, Brave Nightly encounters a `RangeError` whereas other browsers do not. This happens when the browser is about to execute a function (i.e. `jPw`) which contains a peculiar variable assignment consisting of over 328k characters, and a function (i.e. `Pp`) being nested as an argument to itself over 500 times.

Brave | 1.58.2 Chromium: 115.0.5790.56 (Official Build) nightly (64-bit)
-- | --
Revision | ab0f05e3cfda45b9da6588ff946a61c17b2dddda
OS | Windows 10 Version 22H2 (Build 19045.3208)
JavaScript | V8 11.5.150.13

![spreadsheets-testing](https://github.com/brave/brave-browser/assets/815158/be730f7e-fb0a-4fa4-8622-144ca2c6b7f1)

**Comment by jonathansampson** [comment]
I did a bit more experimenting, and this doesn't appear to be limited to nested functions or recursive calls. For example, I was able to replicate similar behavior just by wrapping a value in more and more parens. I went ahead and tested a few different scenarios:

# Nested Anonymous Functions

```js
let lastGoodAnonFuncs = "";

function checkMaxAnonFuncs (depth = 1) {
  const front = `(function() {`.repeat(depth);
  const close = `})()`.repeat(depth);
  const myFunc = new Function(`${front}1${close}`);
  try {
    myFunc();
    lastGoodAnonFuncs = myFunc.toString();
    return checkMaxAnonFuncs(depth + 1);
  } catch (e) {
    console.log('lastGoodAnonFuncs', lastGoodAnonFuncs, lastGoodAnonFuncs.length, 'Depth', depth);
    return depth;
  }
}

checkMaxAnonFuncs();
```

Metric | Google | Brave 1.56.11 | Brave (Nightly, v1.58.43)
-- | --: | --: | --:
Function Body Length (Chars) | 4,498 | 4,498 | 3,614
Max Depth | 263 | 263 | 211

# Nested Arrow Functions

```js
let lastGoodArrowFuncs = "";

function checkMaxArrowFuncs (depth = 1) {
  const front = `(() => {`.repeat(depth);
  const close = `})()`.repeat(depth);
  const myFunc = new Function(`${front}1${close}`);
  try {
    myFunc();
    lastGoodArrowFuncs = myFunc.toString();
    return checkMaxArrowFuncs(depth + 1);
  } catch (e) {
    console.log('lastGoodArrowFuncs', lastGoodArrowFuncs, lastGoodArrowFuncs.length, 'Depth', depth);
    return depth;
  }
}

checkMaxArrowFuncs();
```

Metric | Google | Brave 1.56.11 | Brave (Nightly, v1.58.43)
-- | --: | --: | --:
Function Body Length (Chars) | 3,159 | 3,159 | 3,087
Max Depth | 261 | 261 | 255

# Nested Paren-Wrapped Values

```js
let lastGoodMaxParens = "";

function checkMaxParens (depth = 1 ) {
  const front = '('.repeat(depth);
  const close = ')'.repeat(depth);
  const myFunc = new Function(`${front}1${close}`);
  try {
    myFunc();
    lastGoodMaxParens = myFunc.toString();
    return checkMaxParens(depth + 1);
  } catch (e) {
    console.log('lastGoodMaxParens', lastGoodMaxParens, lastGoodMaxParens.length, 'Depth', depth);
    return depth;
  }
}

checkMaxParens();
```

Metric | Google | Brave 1.56.11 | Brave (Nightly, v1.58.43)
-- | --: | --: | --:
Function Body Length (Chars) | 2,159 | 2,159 | 1,203
Max Depth | 1,066 | 1,066 | 588

**Comment by bsclifton** [comment]
Have been characterizing this with @jonathansampson and then @goodov has recently jumped in to help

@goodov correctly found this error happens when PGO (performance guided optimizations) are in place:
> my local tests showed that PGO-enabled build fails, but non-PGO build works.
also slightly changing JS stack size does fix the issue. For ex.: `brave.exe --js-flags="--stack_size=512"` (default is 984 on Windows).

Knowing that, I was finally able to reproduce the problem with these steps:
- download latest master
- `npm run init`
- go into `.gclient` and set `checkout_pgo_profiles` to `True`
- edit `~/npmrc` and add a value `is_brave_release_build=1`
- `npm run sync` (so that hooks run again, PGO is downloaded to `chrome/build/pgo_profiles/`)
- `npm run build -- Release`
- `npm start -- Release`
- Load https://docs.google.com/spreadsheets/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms/edit#gid=0 

@goodov also shares:
> this change does "fix" the issue, but the underlying problem is still unknown to me, i.e. something else might break, we just cannot see it.
>
> my very careful assumption: PGO doesn't work well with upstream-enabled rust.

With the following patch:
```diff
--- a/src/parsing/pending-compilation-error-handler.h
+++ b/src/parsing/pending-compilation-error-handler.h
@@ -50,7 +50,7 @@ class PendingCompilationErrorHandler {

   bool stack_overflow() const { return stack_overflow_; }

-  void set_stack_overflow() {
+  V8_NOINLINE void set_stack_overflow() {
     has_pending_error_ = true;
     stack_overflow_ = true;
   }
```

I don't have this file (Chromium 115) so I can't verify. But we're still left without knowing the root cause.
Some additional notes from @goodov:
> Brave built from `cr116` branch with PGO enabled works fine.
>
> I'm pretty sure this is rust-related.
>
> In nightly we currently have Chromium that does not have rust enabled on all platforms. This means chromium Windows PGO profile does not contain upstream rust changes and is most likely built with different flags.
https://chromium.googlesource.com/chromium/src/+/refs/tags/115.0.5790.98/DEPS#263
>
> `cr116` has rust enabled on all platforms which means build flags are the same for PGO instrumentation and final PGO-enabled binary:
https://chromium.googlesource.com/chromium/src/+/refs/tags/116.0.5845.42/DEPS#263

This could help explain why Chromium 116 works and helps hint at a root cause

**Comment by bsclifton** [comment]
Thanks to @goodov for digging in and finding the root cause 😄 

The root cause is that we're building with one version of clang - but PGO profile uses a different clang version. For example, you can see https://github.com/brave/brave-core/blob/6624a94670ce6410eab68b5ec3da7d602a009ec4/patches/tools-clang-scripts-update.py.patch#L9C52-L12 which was introduced with https://github.com/brave/brave-core/pull/18955

This will be fixed when https://github.com/brave/brave-core/pull/18808 merges. The version used by PGO profile and for building should match.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.58.88 Chromium: 116.0.5845.82 (Official Build) beta (64-bit)
-- | --
Revision | acf16e35d5897fd4bf9b1b5a93b56aff2ed64bba
OS | Windows 11 Version 22H2 (Build 22621.2134)
```

Reproduced the issue  in `1.58.2 Chromium: 115.0.5790.56`  using original STR https://github.com/brave/brave-browser/issues/31544#issue-1797201035

example | example 
---- | ----
<img width="299" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/ba4e7dc7-8d68-4c3b-84a1-23191278c60e">|<img width="302" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/848705d3-a077-4ea7-a20d-380bc7f04d46">


- Install 1.58.88
- launch Brave
- loaded https://docs.google.com/spreadsheets/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms/edit#gid=0
- Waited a few seconds

#### Confirmed Google sheet load successfully without errors

<img width="961" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/9c62b401-a05f-433d-939c-94f7f05077c4">
