### ISSUE TITLE
WDP for Japan

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#31545]
## Description 

During onboarding, please add this screen requesting users in Japan to enable WDP if they wish. 

Region: Japan only
Default Status: Off (Users need to enable)

cc @bradleyrichter and @rebron for implementation details. 

![image](https://github.com/brave/brave-browser/assets/7606853/e0a4a7aa-5143-4bb8-8afd-74506a10a0f0)

Learn More: https://support.brave.com/hc/en-us/articles/4409406835469-What-is-the-Web-Discovery-Project-

**Comment by A-t-s-u-s-h-i** [comment]
> Want better search results?

検索精度を向上させたいですか？

> Join the movement, contribute to Brave Search.

新たなWebをつくるため、Brave Searchへの貢献にご協力ください。

> Help us fix the web by participating in Brave's Web Discovery Project. By sharing completely anonymous search signals, you can help Brave grow the search index. Learn more.

BraveのWeb Discovery Projectに参加し、Webの修復にご協力ください。完全に匿名化されたサーチ・シグナルのシェアにより、Braveの検索インデックスの改善をサポートすることができます。[詳細はこちら](https://support.brave.com/hc/en-us/articles/4410421247885)

> Sure, I'll help

はい、協力します

> Maybe later

後ほど検討します

> Learn More: https://support.brave.com/hc/en-us/articles/4409406835469-What-is-the-Web-Discovery-Project-

We have the translated helpdesk article.

https://support.brave.com/hc/en-us/articles/4410421247885

**Comment by sangwoo108** [comment]
https://www.figma.com/file/MFHpcXJMg2RUQpUJMAZZ4R/Desktop-Onboarding?type=design&node-id=3325-42022&mode=design&t=WaxzMjcm53gxr34Y-0

**Comment by sangwoo108** [comment]
Is this page intended to show up after "Help imrove browser" page?

<img width="804" alt="image" src="https://github.com/brave/brave-browser/assets/5474642/3c0cee52-3634-47db-aa87-75feef640a0b">

Then what the button label should say instead of "Finish"?

**Comment by rebron** [comment]
Page should show up right before this page.

**Comment by sangwoo108** [comment]
Could you confirm that what we do when "I'll help" is clicked is the same with what we did with the WDP infobar? https://github.com/brave/brave-core/pull/15822

**Comment by rebron** [comment]
@sangwoo108 Yes. "I'll help" should be the same function as clicking on "Ok" from the WDP infobar.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.66.81 Chromium: 124.0.6367.60 (Official Build) beta (64-bit)
-- | --
Revision | ee44f88609d4a72c5d0cb3305c5f340b6203a917
OS | Windows 10 Version 22H2 (Build 19045.4291)
```

## Japanese (`ja`, `ja-JP`) users

## Others

**Comment by LaurenWags** [comment]
Adding `QA/Blocked` until we get https://github.com/brave/brave-browser/issues/37671 uplifted to 1.66.x.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.66.90 Chromium: 124.0.6367.82 (Official Build) beta （64 ビット）
-- | --
変更履歴 | 803a4c629341791205b744969c48b8da9f2cfa4d
OS | Windows 11 Version 23H2 (Build 22631.3527)
```




## Japanese (`ja`, `ja-JP`) users - enabled `WDP`
<details>

### Steps:
1. set `region` to `Japan` in Windows
2. set `language` to `Japanese` in Windows
3. installed `1.66.90`
4. launched Brave
5. skipped through the 1st onboarding screen
6. skipped through the 2nd onboarding screen
7. clicked the equivalent of `Yes` on the 3rd screen
8. clicked to acknowledge the 4th screen
9. opened `brave://settings/search`

### Confirmed the `Web Discovery Project` toggle was on in `brave://settings/search` 

screen 1 | screen 2 | screen 3 | screen 4 | `brave://settings/search`
----------|-----------|----------|----------|--------------------------
![image](https://github.com/brave/brave-browser/assets/98358127/a34e0b82-5563-45d5-87e7-892d0a91be70)|![image](https://github.com/brave/brave-browser/assets/98358127/1fafea93-f418-41b0-9dbc-7fdcd76db8ed)|![image](https://github.com/brave/brave-browser/assets/98358127/4ba6ac26-e8db-43b5-b986-f483f66545a2)|![image](https://github.com/brave/brave-browser/assets/98358127/4aa89403-9a41-4f0a-83dc-701ff258a4e1)|![image](https://github.com/brave/brave-browser/assets/98358127/a8fcd438-582b-4882-a9e2-e2369906e3ce)


</details>

## Japanese (`ja`, `ja-JP`) users - default; `WDP` disabled
<details>

### Steps:
1. set `region` to `Japan` in Windows
2. set `language` to `Japanese` in Windows
3. installed `1.66.81`
4. launched Brave
5. skipped through the 1st onboarding screen
6. skipped through the 2nd onboarding screen
7. clicked the equivalent of `No` on the 3rd screen
8. clicked to acknowledge the 4th screen
9. opened `brave://settings/search`

### Confirmed the `Web Discovery Project` toggle defaulted to `Off` in `brave://settings/search` 

screen 1 | screen 2 | screen 3 | screen 4 | `brave://settings/search`
----------|-----------|----------|----------|--------------------------
![image](https://github.com/brave/brave-browser/assets/98358127/7675995e-1209-46dc-827f-fae1011c1dac)|![image](https://github.com/brave/brave-browser/assets/98358127/04f0db79-6bb4-478d-80cb-27dba1a38b18)|![image](https://github.com/brave/brave-browser/assets/98358127/69ed825d-5b69-4383-837b-2cc262a84315)|![image](https://github.com/brave/brave-browser/assets/98358127/e5d2a636-29dd-412e-ade4-3b58b54862e7)|![image](https://github.com/brave/brave-browser/assets/98358127/3504a8b0-82b7-493b-a4f4-53371a94bef0)

## Other, non-ja-JP/ja users
<details>

### Steps:
1. installed `1.66.81`
2. launched Brave
3. enabled the `WDP...` flag via `brave://flags`
4. went through onboarding
5. confirmed the 4th screen was the `Want better search results?` opt-in for `WDP`
6. clicked on `Sure, I'll help`

Also repeated steps 1-5 above, but declined to opt-in

### Confirmed in the case of opting in, brave://settings/search has `Web Discovery Project` set to `On`/`Enabled`

`brave://flags` | screen 1 | screen 2 | screen 3 | screen 4 | `brave://settings/search`
-----------------|----------|-----------|----------|-----------|-------------------

**Comment by MadhaviSeelam** [comment]
Verification `In Progress` using
```




## Japanese (`ja`, `ja-JP`) users - enabled `WDP` - PASSED
<details>

### Steps:
1. set `region` to `Japan` in Windows
2. set `language` to `Japanese` in Windows
3. installed `1.66.90`
4. launched Brave
5. skipped through the 1st onboarding screen
6. skipped through the 2nd onboarding screen
7. clicked the equivalent of `Yes` on the 3rd screen
8. clicked to acknowledge the 4th screen
9. opened `brave://settings/search`

### Confirmed the `Web Discovery Project` toggle was on in `brave://settings/search` 

</details>

## Japanese (`ja`, `ja-JP`) users - default; `WDP` disabled - PASSED
<details>

### Steps:
1. set `region` to `Japan` in Windows
2. set `language` to `Japanese` in Windows
3. installed `1.66.81`
4. launched Brave
5. skipped through the 1st onboarding screen
6. skipped through the 2nd onboarding screen
7. clicked the equivalent of `No` on the 3rd screen
8. clicked to acknowledge the 4th screen
9. opened `brave://settings/search`

### Confirmed the `Web Discovery Project` toggle defaulted to `Off` in `brave://settings/search` 


## Other, non-ja-JP/ja users - PASSED
<details>

### Steps:
1. installed `1.66.81`
2. launched Brave
3. enabled the `WDP...` flag via `brave://flags`
4. went through onboarding
5. confirmed the 4th screen was the `Want better search results?` opt-in for `WDP`
6. clicked on `Sure, I'll help`

Also repeated steps 1-5 above, but declined to opt-in

### Confirmed in the case of opting in, brave://settings/search has `Web Discovery Project` set to `On`/`Enabled`


</details>
