### ISSUE TITLE
Update Ramp URLs

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#31541]
## Description 

Update Ramp URLs. Old Ones will be made redundant on October 10th. See post here https://bravesoftware.slack.com/archives/C03BNU0KGC8/p1688984387350299

From Ramp:

```
We will be making the following changes to our URLs, and we need your help to ensure a smooth transition. Please review the details below:
Current 				             New
api-instant.ramp.network	     api.ramp.network
buy.ramp.network			     app.ramp.network
We’ve already updated our documentation to reflect these changes. Moving forward, all references to the old domains should be updated accordingly.
 **Implementation Date**
The domain changes will take effect today, 10 July 2023.
Please ensure that you are prepared for this transition. There will be a grace period of 3 months, so old domains will stay live until 10 October 2023.

```

## Steps to Reproduce

   1. 
   2. 
   3. 

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
@HEagle18 @nvonpentz please specify if this is `release-notes/include` or `release-notes/exclude`. Thanks!

cc @kjozwiak @rebron
