### ISSUE TITLE
Reset NTP Sponsored Image counter every 24 hours

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#31551]
## Description 

Currently:
After startup, we show a sponsored image on the NTP on the 2nd view and then every 4 views. 

New functionality:
We should reset this count every 24 hours, after which we show a sponsored image on the NTP on the 2nd view and then every 4 views.

**Comment by btlechowski** [comment]
Verified with

Brave | 1.60.102 Chromium: 118.0.5993.96 (Official Build) beta (64-bit)
-- | --
Revision | 3598a9fc6b7752181feb25caa131bc386d6d054c
OS | Linux


#### opted out - with reset

<details>

Steps:
1. Clean profile
2. Run Brave with:
```
BraveNTPBrandedWallpaper:initial_count_to_branded_wallpaper/1/count_to_branded_wallpaper/5/reset_counter_after/1m
```
3. Open NTP
4. Open NTP -> 1st NTP SI is shown
5. Wait more than 1 minute
6. Open NTP
7. Open NTP -> 2nd NTP SI is shown

1st NTP SI on 2nd NTP:
![image](https://github.com/brave/brave-browser/assets/34715963/c76ac454-75ab-48a8-a652-04df319fcda4)

2nd NTP SI on 4th NTP:
![image](https://github.com/brave/brave-browser/assets/34715963/006a9a53-f36d-439c-b42c-71768a8471b7)

</details>


#### opted out - no reset

<details>

Steps:
1. Clean profile
2. Run Brave with:
```
BraveNTPBrandedWallpaper:initial_count_to_branded_wallpaper/1/count_to_branded_wallpaper/2/reset_counter_after/5m
```
3. Open NTP
4. Open NTP -> 1st NTP SI is shown
5. Open NTP
6. Open NTP
7. Open NTP -> 2nd NTP SI is shown

1st NTP SI on 2nd NTP:
![image](https://github.com/brave/brave-browser/assets/34715963/d5b10d08-6625-4eb7-b1b3-5e022aa26e68)


2nd NTP SI on 5th NTP:
![image](https://github.com/brave/brave-browser/assets/34715963/c6f1fbe2-a490-4f46-be53-472c9daea85d)


</details>

#### opted in - with reset

<details>

Steps:
1. Clean profile
2. Run Brave with:
```
BraveNTPBrandedWallpaper:initial_count_to_branded_wallpaper/1/count_to_branded_wallpaper/5/reset_counter_after/1m
```
3. Enable rewards
4. Make sure tokens are refilled 
1. Open NTP
1. Open NTP -> 1st NTP SI is shown
1. Wait more than 1 minute
1. Open NTP
1. Open NTP -> 2nd NTP SI is shown

1st NTP SI on 2nd NTP:
![image](https://github.com/brave/brave-browser/assets/34715963/802c260a-25b5-44ab-8b52-ba472b5159dc)

2nd NTP SI on 4th NTP:
![image](https://github.com/brave/brave-browser/assets/34715963/93f0e93c-f7a2-4e52-88b7-6ba9dea62eb1)


</details>

#### opted in - no reset

<details>

Steps:
1. Clean profile
2. Run Brave with:
```
BraveNTPBrandedWallpaper:initial_count_to_branded_wallpaper/1/count_to_branded_wallpaper/2/reset_counter_after/5m
```
1. Open NTP
1. Open NTP -> 1st NTP SI is shown
1. Wait more than 1 minute
1. Open NTP
1. Open NTP -> 2nd NTP SI is shown

1st NTP SI on 2nd NTP:
![image](https://github.com/brave/brave-browser/assets/34715963/126b660c-17aa-42bc-9c82-fa556c9a2cfc)


2nd NTP SI on 5th NTP:
![image](https://github.com/brave/brave-browser/assets/34715963/ff3e9fbc-56ab-40e4-81d4-14a391a57f99)


</details>

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 [panther_beta-user 14 U1B2.230922.010 release-keys]
Brave build: 1.60.109
Chromium: 119.0.6045.59 (Official Build) (64-bit) 
Revision: fc399c7c433510eb03c2b35281bf8935804b99de
```
Filled follow-up issue #34022, plus existing issue #33837 is still opened
---------------------------
<details>
<summary> Opted out from Rewards - FAILED </summary>

**STEPS:**
1. Clean profile > Launch Brave
2. Land on the 1st `NTP`
3. Open 2nd `NTP` > Verify that the 1st `NTP SI` is opened on the 2nd `NTP`
4. Open 3 more `NTP` > Verify that the 2nd `NTP SI` is opened on the 3rd `NTP` thereafter
5. Open more `NTP` > Verify that each next `NTP Si` is shown on the 3rd `NTP` thereafter
6. Close and relaunch Brave > Repeat steps 2 - 5 > Verify the same
7. Now open `NTP` so you land on `NTP SI` > Keep Brave opened
8. Go to device settings and update the system date to 24 hours from now
9. Return to Brave > Open 2 `NTP` > Verify if `NTP SI` is shown on the 2nd `NTP`

**ACTUAL RESULTS:**
- Verified that the 1st `NTP SI` is opened on the 2nd `NTP`
- Verified that the 2nd each next `NTP SI` is opened on the 3rd `NTP` thereafter
- Verified that the count reset after Brave closed and relaunched
- Verified that we should reset the `NTP SI` count every 24 hours, after which we must show a sponsored image on the `NTP` on the 2nd view and then every 3 views

---------------------------

*No reset*

https://github.com/brave/brave-browser/assets/128532965/13e1ce1d-14df-461f-9693-f94c315a1d04

*After reset*

https://github.com/brave/brave-browser/assets/128532965/7306cea2-9a31-4379-b242-62edba759b67

</details>

<details>
<summary> Opted in to Rewards - FAILED </summary>

**STEPS:**
1. Clean profile > Launch Brave
2. Enable `Rewards`
3. Close and relaunch Brave
4. Land on the 1st `NTP`
5. Open 2nd `NTP` > Verify that the 1st `NTP SI` is opened on the 2nd `NTP`
6. Open 3 more `NTP` > Verify that the 2nd `NTP SI` is opened on the 3rd `NTP` thereafter
10. Open more `NTP` > Verify that each next `NTP Si` is shown on the 3rd `NTP` thereafter
11. Close and relaunch Brave > Repeat steps 4 - 7 > Verify the same

**ACTUAL RESULTS:**
- Verified that the 1st `NTP SI` is opened on the 2nd `NTP`
- Verified that the 2nd each next `NTP SI` is opened on the 3rd `NTP` thereafter
- Verified that the count reset after Brave closed and relaunched

---------------------------

https://github.com/brave/brave-browser/assets/128532965/63157ca9-409f-4a01-bc64-af9f6c97e2ec
</details>
