### ISSUE TITLE
Portfolio Filter Dropdowns have uneven widths

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#31559]
## Description 

Portfolio Filter Dropdown's have uneven widths.

## Steps to Reproduce

   1. Open the Portfolio `Filters and display settings`
   2. The `dropdown's` have uneven widths.

## Actual result:

![Screenshot 51](https://github.com/brave/brave-browser/assets/40611140/a71c5e6a-0aea-45c9-951f-27dc72f91571)

## Expected result:
Both dropdown's should have the same width as per design

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.58.109 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Linux

- Verified steps from [brave/brave-core#19223](https://github.com/brave/brave-core/pull/19223)
- Verified Portfolio filter dropdown are properly aligned 
![LInux](https://github.com/brave/brave-browser/assets/17010094/8704c09e-7168-4def-9c02-83a614ed0b0d)


---------------------

**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build)) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#19223](https://github.com/brave/brave-core/pull/19223)
- Verified Portfolio filter dropdown are properly aligned 
![brave_VdaZMdEJEp](https://github.com/brave/brave-browser/assets/17010094/5eb1e7e6-fc2c-402a-9519-7f0e6281731a)


---------------------

**Verification passed on**

Brave | 1.57.27 Chromium: 115.0.5790.114 (Official Build) beta (arm64)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | macOS Version 13.4.1 (c) (Build 22F770820d)

- Verified steps from [brave/brave-core#19223](https://github.com/brave/brave-core/pull/19223)
- Verified Portfolio filter dropdown are properly aligned 
![image](https://github.com/brave/brave-browser/assets/17010094/a5036206-0156-4635-86ac-e6d945290d47)
