### ISSUE TITLE
Shortcut for `New window` shows `Command` + `NumDecimal`, rather than `Command` + `N`

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#31552]
## Description 

Shortcut for `New window` shows `Command` + `NumDecimal`, rather than `Command` + `N`

## Steps to Reproduce

1. install `1.58.7`
2. launch Brave
3. open `brave://settings/system/shortcuts`
4. type `new window`
5. examine the keybinding/shortcut

## Actual result:

Shows `Command` + `NumDecimal`

<img width="1367" alt="Screen Shot 2023-07-10 at 4 17 01 PM" src="https://github.com/brave/brave-browser/assets/387249/458da428-c297-40ad-a81d-e963a3d6c800">

## Expected result:

Should show `Command` + `N`

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.58.7 Chromium: 115.0.5790.75 (Official Build) nightly (x86_64)
-- | --
Revision | db3af86e921baa371556e158292bc36a74aea794
OS | macOS Version 11.7.8 (Build 20G1351)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @fallaciousreasoning @rebron @brave/qa-team

**Comment by LaurenWags** [comment]
@brave/qa-team this requires `1.56.5` or higher for 1.56.x verification

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.56.5 Chromium: 115.0.5790.75 (Official Build) (x86_64)
-- | --
Revision | 3433e4d513e8454ba0243deea3d53693661dc0c3-refs/branch-heads/5790@{#1430}
OS | macOS Version 11.7.8 (Build 20G1351)

Followed my original steps to reproduce from https://github.com/brave/brave-browser/issues/31552#issue-1797769512.

### Confirmed the shortcut binding for `New window` is `Command` + `N`, and works
 
`brave://settings/system/shortcuts` | `New window`
------------------------------------|----------------
<img width="1809" alt="Screen Shot 2023-07-12 at 3 00 58 PM" src="https://github.com/brave/brave-browser/assets/387249/f39afcc2-3f5b-4b58-90ec-81418dc877f8"> | <img width="1809" alt="Screen Shot 2023-07-12 at 3 04 53 PM" src="https://github.com/brave/brave-browser/assets/387249/0364bab4-0271-40dd-85f7-504e5511942f">
