### ISSUE TITLE
`https://github.com/ipfs/boxo` shows `IPFS` badge/icon in the URL bar

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#31562]
## Description 

`https://github.com/ipfs/boxo` shows `IPFS` badge/icon in the URL bar

## Steps to Reproduce

   1. Visit `https://github.com/ipfs/boxo` 
   2. URL bar shows IPFS badge

## Actual result:

![image](https://github.com/brave/brave-browser/assets/17010094/29e3efec-f046-4ad2-9b6c-d4277401af89)

## Expected result:
No IPFS badge when there is no valid CID link

## Reproduces how often: 

Easy

## Brave version (brave://version info)

 
Brave | 1.57.1 Chromium: 115.0.5790.56 (Official Build) beta (64-bit)
-- | --
Revision | `ebcfb87c1393f36955cfa2f6451a1767e3dc3ee5-refs/branch-heads/5790@{#1193}`
OS | Windows 11 Version 22H2 (Build 22621.1848)

```
Node info
Version: kubo/0.21.0/brave
Brave IPFS Client Updater (Windows): 1.0.106
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? NA

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @cypt4 @lidel

**Comment by lidel** [comment]
@srirambv  iiuc this is a duplicate of https://github.com/brave/brave-browser/issues/31145  – maybe bump in priority?

**Comment by srirambv** [comment]
Yup. Closing it as dupe of #31145 and adding a `P3` label for #31145
