### ISSUE TITLE
secp256k1_context instance should be global

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#31563]
More in PR https://github.com/brave/brave-core/pull/19229/files

**Comment by srirambv** [comment]
Verification passed on  

Brave | 1.58.105 Chromium: 116.0.5845.114 (Official Build) beta (64-bit)
-- | --
Revision | 5a895596bcd7fcd930dab0714ea5cfa86c5aa0a7
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified basic wallet features work as expected.

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.58.117 x64 build
- Verified basic wallet features work as expected
