### ISSUE TITLE
Gettr.com comment function does not work with Shields enabled 

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#31568]
## Description 

On Gettr.com, the comment box does not appear when clicked if Brave's Shields are enabled. Site will simply turn "darker" but the actual element does not appear on screen:
![image](https://github.com/brave/brave-browser/assets/3299098/b1b3966f-6273-4374-82ea-97b24e876c9e)
![image](https://github.com/brave/brave-browser/assets/3299098/23a6cd8f-4da0-4b09-8a79-08574b22311e)

## Steps to Reproduce

   1. Visit gettr.com
   2. Attempt to leave a comment

## Reproduces how often: 

Easily

## Brave version (brave://version info)

v1.52.130

## Version/Channel Information:

- Can you reproduce this issue with the current release? Y
- Can you reproduce this issue with the beta channel? Y
- Can you reproduce this issue with the nightly channel? Y

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Y
- Does the issue resolve itself when disabling Brave Rewards? N
- Is the issue reproducible on the latest version of Chrome? N

## Miscellaneous Information:

cc @ryanbr

**Comment by ryanbr** [comment]
Should be resolved now, closing.
