### ISSUE TITLE
Inline Tip buttons not appearing on new Reddit site while not logged in

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#31569]
## Description

In this new view of Reddit, Tip buttons do not appear to be showing. This might be the view of new Reddit when you're not logged in? 

![image](https://github.com/brave/brave-browser/assets/11497541/9ade1577-d01b-4feb-bd6f-327ab3f37266)

https://www.reddit.com/r/BATProject/comments/14ubt1h/your_june_rewards_have_arrived_but_the_payment_is/

**Comment by emerick** [comment]
Closing as this has been superseded by https://github.com/brave/brave-browser/issues/33783

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.62.93 Chromium: 120.0.6099.35 (Official Build) beta (x86_64)
-- | --
Revision | 2032da61e85b8d826ab474ee36fee9a9cee09907
OS | macOS Version 13.6.1 (Build 22G313)
```
