### ISSUE TITLE
Several keys/key presses are dropped/missing, on a multi-line, custom shortcut

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#31577]
## Description 

Discovered by @MadhaviSeelam.

Several keys/key presses are dropped/missing, on a multi-line, custom shortcut

## Steps to Reproduce

1. install `1.58.11`
2. launch Brave
3. ensure `brave://flags/#brave-commands` is set to `Enabled`
4. click `Relaunch`, if needed
5. open `brave://settings/system/shortcuts`
6. click `Add` next to `Reload clearing cache` or similar unassigned command
7. enter a bunch of chained keypresses, such as `Shift` + `Command` + `Z` + `M` + `K` + `Backspace`
8. click `Save`
9. look at the resulting assigned shortcut keybinding for the `Reload clearing cache` command
 

## Actual result:

It only shows `Command` + `Shift` + `Backspace`

`Shift` + `Command` + `Z` + `M` + `K` + `Backspace` shortcut (input) | `Command` + `Shift` + `Backspace`  (saved as) | `Reload clearing cache` (default)
---------|----------|---------
<img width="1790" alt="Screen Shot 2023-07-11 at 3 15 01 PM" src="https://github.com/brave/brave-browser/assets/387249/a720838d-6c32-419f-90ce-933f3d9b4be2"> | <img width="1790" alt="Screen Shot 2023-07-11 at 3 15 18 PM" src="https://github.com/brave/brave-browser/assets/387249/b13fec81-04c8-4bc3-9a63-7d24f9ad55b6"> | <img width="1790" alt="Screen Shot 2023-07-11 at 3 16 57 PM" src="https://github.com/brave/brave-browser/assets/387249/cfd2ce7b-2599-4937-82da-ecee3bdb77e5">

## Expected result:

It should either be assigned properly, and read 

`Shift` + `Command` + `Z` + `M` + `K` + `Backspace` (i.e. not drop the `Z`, `M`, and `K` keys)

or it should error out somehow, earlier, before saving

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.58.11 Chromium: 115.0.5790.75 (Official Build) nightly (arm64)
-- | --
Revision | 6f661683ebbc39d361b8a06b0005598ef0a0be1a
OS | macOS Version 11.7.8 (Build 20G1351)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @MadhaviSeelam @rebron @fallaciousreasoning @sangwoo108 @brave/qa-team

**Comment by fallaciousreasoning** [comment]
The UI should definitely show an error / or just accept one key. Chromium shortcuts don't support chords, so we can only have modifiers + one key.

**Comment by kjozwiak** [comment]
The above requires `1.56.9` or higher for `1.56.x` verification 👍

**Comment by stephendonner** [comment]
## Verification `PASSED` using 

Brave | 1.56.9 Chromium: 115.0.5790.98 (Official Build) (x86_64)
-- | --
Revision | 4eacc220b55f07c57d5a1f4b7e0e63a6f7e420a1-refs/branch-heads/5790_90@{#4}
OS | macOS Version 11.7.8 (Build 20G1351)

Followed the steps to reproduce from  https://github.com/brave/brave-browser/issues/31577#issue-1799864981.

### Confirmed using `Shift` + `Command` + `Z` + `M` + `K` + `Backspace` resulted in `Shift` + `Command` +  `K` being accepted, and confirmed it worked to reload the page

example | example
---------|---------
<img width="1765" alt="Screen Shot 2023-07-19 at 10 24 46 AM" src="https://github.com/brave/brave-browser/assets/387249/eff32c93-99f6-42c6-afff-ddc5a1da1d75"> | <img width="1809" alt="Screen Shot 2023-07-19 at 10 24 51 AM" src="https://github.com/brave/brave-browser/assets/387249/84e6e087-739d-4fa1-8ab1-f413b6dbf293">
