### ISSUE TITLE
Brave does not load CSS?

### ISSUE THREAD

**Issue by KrzysztofRozmus** [brave/brave-browser#31585]
## Description 
Pages don't load all the way, even browser settings don't work.

## Actual result:
LinkedIn: 
![linkedin](https://github.com/brave/brave-browser/assets/104672770/fbc4bb11-f047-4c88-959a-3a53b7304a48)
Brave settings: 
![settings](https://github.com/brave/brave-browser/assets/104672770/4824d80e-e6cd-4622-9719-0375120126f8)

## Expected result:
Restore the browser to function properly.

## Brave version (brave://version info)
[Version 1.52.130 Chromium: 114.0.5735.198 (Official version) (64-bit]
[Ubuntu 22.04.2 LTS x86_64]
[Kernel: 5.19.0-46-generic]

**Comment by KrzysztofRozmus** [comment]
I reinstalled barave and it started working properly. I still don't know the cause of the problem.

**Comment by bevas** [comment]
Hello, I have the same issue, with same setup.

[Ubuntu 22.04.2 LTS]
[Kernel: 5.19.0-46-generic]

Plain re-installation did not work for me. 
I've tried to downgrade to older version and it seems that Brave 1.52.122 Chromium: 114.0.5735.110 (Official Build) (64-bit) is last working version for me.

**Comment by kamilko** [comment]
Same issue on TUXEDO OS 2 (Ubuntu 22.04 with kernel 6.2).
I did downgrade to 1.52.126 to have Brave working.
Issue is not only on web pages, but also in settings.
Im using `https://brave-browser-apt-release.s3.brave.com/ stable main` as a package source.

**Comment by KrzysztofRozmus** [comment]
> Hello, I have the same issue, with same setup.
> 
> [Ubuntu 22.04.2 LTS] [Kernel: 5.19.0-46-generic]
> 
> Plain re-installation did not work for me. I've tried to downgrade to older version and it seems that Brave 1.52.122 Chromium: 114.0.5735.110 (Official Build) (64-bit) is last working version for me.

I removed Brave via Ubuntu Software (SNAP), used `sudo apt autoremove` command in terminal then install it from original web `https://brave.com/linux/` again and it works fine... at least for now. I already have the same version [Version 1.52.130 Chromium: 114.0.5735.198]

**Comment by KrzysztofRozmus** [comment]
> 

I removed Brave via Ubuntu Software (SNAP), used sudo apt autoremove command in terminal then install it from original web https://brave.com/linux/ again and it works fine... at least for now. I already have the same version [Version 1.52.130 Chromium: 114.0.5735.198]

**Comment by KrzysztofRozmus** [comment]
> Same issue on TUXEDO OS 2 (Ubuntu 22.04 with kernel 6.2). I did downgrade to 1.52.126 to have Brave working. Issue is not only on web pages, but also in settings. Im using `https://brave-browser-apt-release.s3.brave.com/ stable main` as a package source.

I removed Brave via Ubuntu Software (SNAP), used sudo apt autoremove command in terminal then install it from original web https://brave.com/linux/ again and it works fine... at least for now. I already have the same version [Version 1.52.130 Chromium: 114.0.5735.198]

**Comment by kz6fittycent** [comment]
I can confirm the same issues with my (apt) installed version on:

- Pop!_OS 22.04
- Kernel: 6.2.6-76060206-generic
- Brave version: Brave Browser 114.1.52.130

**Comment by Fly-Style** [comment]
Hi, have the same problem - Ubuntu 22.04.2 LTS x86_64, kernel 5.19.0-46-generic, tried to reinstall brave with multiple versions -  1.52.130, 1.52.129, 1.52.122, 1.51.118 -- nothing helped me.

**Comment by darkoje** [comment]
Turning off option "Use hardware acceleration when available" in Settings does the trick without reinstalling or downgrading.

**Comment by kamilko** [comment]
> Turning off option "Use hardware acceleration when available" in Settings does the trick without reinstalling or downgrading.

So maybe it is related with particular hardware/drivers?
My hardware: AMD ATI Lucienne GPU on Ryzen 7 5700U.

**Comment by KrzysztofRozmus** [comment]
> Turning off option "Use hardware acceleration when available" in Settings does the trick without reinstalling or downgrading.

In my case, it didn't work

**Comment by KrzysztofRozmus** [comment]
> > Turning off option "Use hardware acceleration when available" in Settings does the trick without reinstalling or downgrading.
> 
> So maybe it is related with particular hardware/drivers? My hardware: AMD ATI Lucienne GPU on Ryzen 7 5700U.

Doubtful. In my case:
Intel i5-4570 (4) @ 3.600GHz
AMD ATI Radeon RX 480

**Comment by kz6fittycent** [comment]
Worked for me - RX480. Glad to be back on a REAL browser!
