### ISSUE TITLE
follow-up to #29075 - Speedreader design updates

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#31583]
## Design

Follow-up items to #29075 
See Figma:
https://www.figma.com/file/YHMNRL2XpZDOUe6n1Dw6K1/Reader-mode?type=design&node-id=2121-58994&mode=design&t=RtAqCsemnq3g5SWI-0

<img width="1060" alt="Screenshot 2023-07-12 at 8 37 31 AM" src="https://github.com/brave/brave-browser/assets/5951041/4e7d14d9-e350-4270-ac1a-a28deb71f3ba">

## Description
**Speedreader button in address bar**

- [x] If Speedreader is enabled as always on, Speedreader button in address bar should still just be a toggle to enter/exit Speedreader.  
- [x] For left click action, hide secondary dialog toggle and introductory dialog that turns Speedreader "always on option" on/off. On right click, show dialog for always on or per site setting. 

<img width="376" alt="Screenshot 2023-07-11 at 9 47 22 PM" src="https://github.com/brave/brave-browser/assets/5951041/a633ee3b-52c4-49bd-96fc-3a300f0e3a57">

**Speedreader settings**

- [x] Add settings dialog and use the Customize icon for speedreader mode for this site and all sites off the speedreader toolbar. 
- [x] Also move the Customize icon to left most position. Both settings should be default off. The always on setting should match the same one that is in brave://settings/appearance (see Design)

**Text change**

- [x] Change all text instances of `Reader mode` to `Speedreader`. (see Design)

## Brave version (brave://version info)

1.58.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by kjozwiak** [comment]
The above requires `1.58.113` or higher for `1.58.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | 21631edab5a70964c2f5817bfa4d06c32b4ab314
OS | Windows 11 Version 22H2 (Build 22621.2134)
```

### Case 1: Speedreader button with new tune speedreader dialog in the URL bar  
<details>

1. Install `1.58.114`
2. launched Brave
3. opened `brave://settings/appearance`
4. verified `Speedreader` setting is `Off` 
5. clicked the link `Learn more` 
6. confirmed correct help article displayed - old article??
7. navigated to nytimes.com and opened an article - https://www.nytimes.com/2022/12/12/travel/maine-balsam-tippers.html
8. verified `Speedreader` button is available in the URL bar
9. hovered over and correct text displayed `Turn on speedreader` - File as a follow up- correct text `Speedreader`
10. clicked `Speedreader` button 
11. confirmed when Speedreader button is clicked, no other bubbles shown in the URL bar
12. confirmed article layout is shown in `Speedreader` 
13. right clicked `Speedreader` button in the URL bar
14. confirmed new `Tune speedreader` dialog is shown with default options `Off`
15. clicked/toggled `Off` speedreader button in the URL bar
16. confirmed the speedreader mode off and article is no longer shown in speedreader mode and no toolbar is shown

step 4 | step 9 | step 14 | step 16
-------- |--------- | ------- | ------ 
<img width="643" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/296c52b2-ed39-4685-addb-93cfe69ef5db">|<img width="643" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/fc67a917-bb66-4ff1-8569-efffcd649f86">|<img width="646" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/aeb8e272-4623-4625-b77e-d6f8b63b4992">|<img width="644" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/15d36afd-ad16-41bd-82d0-fbd2bfb4e6e8">|<img width="646" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/f2ae9138-0c00-4e95-b18e-fec18314f610">
</details>

### Case 2:  Speedreader buttons UI  
<details>

1. continue from Case 1
      - Speedreader turned on for an article in a new tab - https://www.nytimes.com/2022/12/12/travel/maine-balsam-tippers.html
2. confirmed following `Speedreader` buttons/options are shown above the article, match to Figma designs/screenshot in the issue and are in the correct order left to right
      - `Tune speedreader` button
      - `Appearance settings` (Aa control)
      - `Speedreader` text
      - `X` control
3. confirmed the `Tune speedreader` icon matches the figma designs
4. clicked on `Tune Speedreader` button 
5. confirmed the default options are `off` as below in the `Tune speedreader` and match to Figma designs/screenshots 
       - `Always use speedreader for this site`
       - `Always use speedreader for all sites` 
       
step 1 | step 2a | step 2b | step 2c | step 5 
------ | ----- | ---- | ----- | ----- 
<img width="646" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/9aa0e6f1-b855-49d7-8853-192d64c722bc">|<img width="646" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/edb1b62c-b76c-4784-9654-3dc0f5245638">|<img width="646" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/547fc392-e9c6-4be9-a8a6-21414d4b74e6">|<img width="646" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/35b1ddf4-dba8-421d-bf90-28dc2bc264f1">|<img width="956" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/4abb2ff8-4ec3-4868-9c83-d2a70a734a58">

</details>

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.58.115 Chromium: 116.0.5845.163 (Official Build) beta (x86_64)
-- | --
Revision | 4d8f3ac31e950c7bb505b61fd9d86ed7f4888a71
OS | macOS Version 11.7.9 (Build 20G1426)
```

Case 1: Speedreader button with new tune speedreader dialog in the URL bar
Case 2: Speedreader buttons UI
Case 3: Tune speedreader dialog functionality

**Comment by rebron** [comment]
cc: @Brave-Matt See above use cases if there any questions.

@MadhaviSeelam we're in process of getting this updated, thanks for flagging. `https://support.brave.com/hc/en-us/articles/360045031392-What-is-SpeedReader`

**Comment by LaurenWags** [comment]
Per discussion with @rebron - run through cases 1 and 2 from https://github.com/brave/brave-browser/issues/31583#issuecomment-1707223146 on Linux.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.58.117 Chromium: 116.0.5845.180 (Official Build) (64-bit)
-- | --
Revision | 99255ad6abf2fa399c063683c051f973e1f5c0af
OS | Linux
```
