### ISSUE TITLE
Summarizer should know today's date

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#31599]
## Description 

Ask our summarizer for today's date e.g. "what day is it today?"
Should accurately respond with today's date e.g. "Today is July 12, 2023".

## Steps to Reproduce

   1. Access summarizer and query for date like above.
   2. Notice result is not accurate.

## Actual result:

Wrong date.
<img width="446" alt="Screenshot 2023-07-12 at 12 06 09 PM" src="https://github.com/brave/brave-browser/assets/5951041/b0b10c17-2ee5-4a8b-9883-8418220fd83c">

## Expected result:
Correct date.

## Reproduces how often: 

Easily.

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.60.30 Chromium: 117.0.5938.88 (Official Build) nightly (x86_64)
-- | --
Revision | 51564671a5c657bcf2633e5d26878d3633c6b338
OS | macOS Version 11.7.10 (Build 20G1427)
```

Asked for today's date in a plethora of ways

inset | in context
-----|-----------
<img width="389" alt="Screen Shot 2023-09-17 at 11 44 07 PM" src="https://github.com/brave/brave-browser/assets/387249/4c6cd92b-de49-480c-ad93-9ed589402b44"> | <img width="1494" alt="Screen Shot 2023-09-17 at 11 43 10 PM" src="https://github.com/brave/brave-browser/assets/387249/dee2d181-1a05-4d51-a9a7-7ee68b6b2926">
