### ISSUE TITLE
Disabling "safe browsing" "function" is completely broken

### ISSUE THREAD

**Issue by BartAgterbosch** [brave/brave-browser#31593]
So, basically the same story as it has been for over a year now, the "safe browsing" function is completely and entirely broken, busted, non-functional.
As in there is no way to turn this piece of shit off, you can switch the setting to off so that it looks like it's off, but it's not actually off..
It keeps blocking exe files or any other executable files, even though it's turned off..
This thing has been broken for well over a year now, perhaps even 2 years.
Add onto that the completely backwards decision to just nuke the download bar AND the top right downloads icon when you're not currently downloading something, and brave has turned into a big fat steaming pile of shit.
A bad excuse for a browser, which is borderline unusable today (even though it never used to be), whose only selling points are privacy and a builtin adblocker.
All I can say is that it's so damn broken nowadays, even though I have reported this issue several times, on several platforms, who knows how many times, that I cannot even muster the spirit to write any further version details, platform, or reproduction steps, as the report will probably be thrown by the wayside again anyway.
Writing down a version is pointless, as it's been broken on the latest version for so long that I don't even know where it began.
Real shame, I loved brave

**Comment by fmarier** [comment]
> It keeps blocking exe files or any other executable files, even though it's turned off..

I think you're running into this problem: https://github.com/brave/brave-browser/issues/28917
