### ISSUE TITLE
Enable update status check by help page on MacOS

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#316]
- [x] Delete `Update Brave` menu item (https://github.com/brave/brave-core/pull/271)
- [x] Delete `BraveAppControllerMac` - move SUUpdaterDelegate impl to sparkle_glue (https://github.com/brave/brave-core/pull/271)
- [x] Move sparkle related impl to `brave/browser/mac`
- [x] Use webui as chrome does and don't use sparkle dialog
- [x] Enable UpgradeDetector for MacOS
- [x] Check how to get download/install progress info
- [x] Try to remove passing `--disable_brave_update` in `yarn test` and check in runtime instead.

**Comment by kjozwiak** [comment]
Went through verification using the following build under macOS 10.13.6 x64 - PASSED

Brave | 0.55.10 Chromium: 70.0.3538.22 (Official Build) beta(64-bit)
-- | --
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | Mac OS X
