### ISSUE TITLE
[Android] Improve search suggestions

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#31607]
When Brave Search is set as the default search engine (Standard Tab), search suggestions will be enabled by default. Given this, for New Users of Brave who download the browser in countries where Brave Search is the default, please:

- [ ] Enable Search Suggestions (Standard Tab Only)
- [ ]  Prevent search suggestions from displaying when text is copy-pasted into the URL bar
- [ ]  Remove personally identifiable information (PII) and sensitive data from URL bar input, similar to how it is currently handled in search See here: https://github.com/brave/search/blob/e4e1b2b2cee4d33ec42960f8f82cf7d8b8cc4976/services/mixer/serpkit/src/lib/components/suggest/queryChecker.ts#L37
- [ ]  Ensure that search suggestions remain active if a user manually switches their search engine to another provider.

For Reference:
The 12 countries where Brave Search is currently set as default include: US, CA, GB, DE, FR, MX, BR, IN, ES, AR, AT, IT.

Additionally:
If a user enables search suggestions in settings at any point, that preference should be respected, regardless of the search engine in use.
If a user disables search suggestions in settings, that preference should also be respected, regardless of the search engine.

**Comment by anthonypkeane** [comment]
@deeppandya & @timchilds along with the work to enable search suggestions and update the UI to follow iOS, please note the following: 

For context please search for Spec: Brave Search Suggestions Default On (2024) on GDrive
Security Review:https://github.com/brave/reviews/issues/1567

When Brave Search is set as the default search engine (Standard Tab), search suggestions will be enabled by default. Given this, for **New Users** of Brave who download the browser in countries where Brave Search is the default, please:

- [ ]  Enable Search Suggestions (Standard Tab Only)
- [ ]  In Settings rename the setting “Improve search suggestions” to “Show search suggestions” and move into the Search engine menu (as iOS does)
- [ ]  Prevent search suggestions from displaying when text is copy-pasted into the URL bar
- [ ] Remove personally identifiable information (PII) and sensitive data from URL bar input, similar to how it is currently handled in search See here: https://github.com/brave/search/blob/e4e1b2b2cee4d33ec42960f8f82cf7d8b8cc4976/services/mixer/serpkit/src/lib/components/suggest/queryChecker.ts#L37
- [ ] Ensure that search suggestions remain active if a user manually switches their search engine to another provider.


**For Reference:**
The 12 countries where Brave Search is currently set as default include: US, CA, GB, DE, FR, MX, BR, IN, ES, AR, AT, IT.

**Additionally:**
If a user enables search suggestions in settings at any point, that preference should be respected, regardless of the search engine in use.
If a user disables search suggestions in settings, that preference should also be respected, regardless of the search engine.

**Comment by kjozwiak** [comment]
As discussed via the `Android` call, leaving a note here to check with @deeppandya to make sure that this is the correct implementation that we want to go with via `1.69.x`. There was some discussion re: what `iOS` & `Desktop` will be doing as we want we want to share the implementation on the different platforms. @hffvld @Uni-verse please double check to make sure we're going with this implementation when starting verification once we're running through `1.69.x`.

**Comment by Uni-verse** [comment]
In progress on `Samsung Galaxy S21` using version: 

```
Brave	1.69.131 Chromium: 127.0.6533.88 (Official Build) beta (64-bit) 
Revision	7f9c5cb9840ea18f57d485ee263b5bf4b1075953
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
<details><summary>New Install - Brave default (US)</summary>

</details>

<details><summary>New install - Non-default (SG)</summary>

</details>

<details><summary>Upgraded Profile</summary>

</details>
