### ISSUE TITLE
Assets are being sorted by global level on the Portfolio page

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#31602]
## Description 

Assets are being sorted by global level on the Portfolio page

## Steps to Reproduce

   1. Go to the `Portfolio` page and add multiple accounts with token balances
   2. Group you `Portfolio` by `Accounts` and sort your assets from `High to Low`
   3. Assets are being sorted at a global level

## Actual result:

https://github.com/brave/brave-browser/assets/40611140/3164c515-b5fd-46f8-a633-0a3632579266

## Expected result:
Assets should be sorted at a group level

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Linux

- Verified steps from [brave/brave-core#19259](https://github.com/brave/brave-core/pull/19259)
- Verified able to sort Portfolio by assets by high to low or low to high bay value

https://github.com/brave/brave-browser/assets/17010094/11493a81-0c9d-4606-80a2-b7874548731b

---------------------

**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#19259](https://github.com/brave/brave-core/pull/19259)
- Verified able to sort Portfolio by assets by high to low or low to high bay value

https://github.com/brave/brave-browser/assets/17010094/881f1765-22f0-4998-a238-1f22d0a2dde7

---------------------

**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (arm64)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | macOS Version 13.4.1 (c) (Build 22F770820d)

- Verified steps from [brave/brave-core#19259](https://github.com/brave/brave-core/pull/19259)
- Verified able to sort Portfolio by assets by high to low or low to high bay value

https://github.com/brave/brave-browser/assets/17010094/c8672565-481f-4fab-982b-394940ae9210
