### ISSUE TITLE
Update Wallet Unlock screen to V2 design

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#31603]
## Description 

We need to update the Wallet `Unlock` screen to the new Wallet V2 design

![Screenshot 54](https://github.com/brave/brave-browser/assets/40611140/15adb96b-8b60-4b69-b14f-3d7f36156af8)

![Screenshot 55](https://github.com/brave/brave-browser/assets/40611140/7b414e54-0c2b-4a15-9783-5431eb0bf3ef)

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Linux

- Verified steps from [brave/brave-core#19280](https://github.com/brave/brave-core/pull/19280)
- Verified lock screen is as per new design
- Verified error state is shown correctly when wrong password is typed in
- Verified restore option works as expected from lock screen
- Verified lock screen on both Wallet page and Wallet panel work as expected

https://github.com/brave/brave-browser/assets/17010094/7650fc76-ef99-4cc4-bb74-d154e9c74b99

---------------------

**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#19280](https://github.com/brave/brave-core/pull/19280)
- Verified lock screen is as per new design
- Verified error state is shown correctly when wrong password is typed in
- Verified restore option works as expected from lock screen
- Verified lock screen on both Wallet page and Wallet panel work as expected

https://github.com/brave/brave-browser/assets/17010094/77a66622-55dc-442d-aec5-a9ac36c12131

---------------------

**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (arm64)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | macOS Version 13.4.1 (c) (Build 22F770820d)

- Verified steps from [brave/brave-core#19280](https://github.com/brave/brave-core/pull/19280)
- Verified lock screen is as per new design
- Verified error state is shown correctly when wrong password is typed in
- Verified restore option works as expected from lock screen
- Verified lock screen on both Wallet page and Wallet panel work as expected

https://github.com/brave/brave-browser/assets/17010094/0766fa20-0613-4df5-9ee9-4085eb0ce19b
