### ISSUE TITLE
Missing logo for Localhost Access permission

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#31600]
Localhost Access permission is missing an icon in `brave://settings/content/siteDetails?site=xyz`
![image](https://github.com/brave/brave-browser/assets/5284154/10d939d5-2c49-463e-a6a2-e7443911efd1)

It appears correctly on `brave://settings/content`

![image](https://github.com/brave/brave-browser/assets/5284154/aef68b48-94a2-43db-8fa5-d08ea11c8355)

Also, "Localhost Access" string should be "Localhost access"

**Comment by ShivanKaul** [comment]
I think this is related to https://github.com/brave/brave-browser/issues/30189 cc @fallaciousreasoning

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.58.90 Chromium: 116.0.5845.96 (Official Build) beta (x86_64)
-- | --
Revision | c112ad8c854bd34b48f4e87bfb3f7951e426a1d4
OS | macOS Version 11.7.9 (Build 20G1426)

### Steps:
1. installed `1.58.90`
2. launched Brave
3. set `brave://flags/#brave-localhost-access-permission` to `Enabled`
4. clicked `Relaunch`
5. logged in to `Google.com`
6. opened `brave://settings/content/siteDetails?site=https%3A%2F%2Fwww.google.com%2F`
7. opened `brave://settings/content`

### Confirmed:
* `Localhost access` icon is present
* spelling fix of `Localhost Access` -> `Localhost access` in `brave://settings/content`

`brave://flags` | `Google site details` | `Google site details` | `brave://settings/content`
---------------|----------|---------|---------
<img width="2032" alt="Screen Shot 2023-08-16 at 10 13 46 AM" src="https://github.com/brave/brave-browser/assets/387249/6ba5b6c5-a0a8-4160-b08e-5cb917a20d0d"> | <img width="2032" alt="Screen Shot 2023-08-16 at 10 09 38 AM" src="https://github.com/brave/brave-browser/assets/387249/b3938b04-de48-4dcf-b4a1-df7b25491307"> | <img width="2032" alt="Screen Shot 2023-08-16 at 10 10 21 AM" src="https://github.com/brave/brave-browser/assets/387249/7ac8222a-3c41-4c4e-816e-13d9c4ed0fd6"> | <img width="2032" alt="Screen Shot 2023-08-16 at 10 10 46 AM" src="https://github.com/brave/brave-browser/assets/387249/a4da7fd2-7192-492e-9df0-e8505fa541db">
