### ISSUE TITLE
Put WebBluetooth functionality behind a flag

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#31605]
As mentioned in #15637 WebBluetooth was disabled (in https://github.com/brave/brave-core/pull/114).

Once we have audited this feature and have a good understanding of its privacy properties, we could provide a flag in `brave://flags` (default off) to allow users who need it to enable it. When that flag is off, it should remove the *Ask* and *Ask (default)* options in `brave://settings/content/siteDetails`, as we [plan to do for all disabled features](https://github.com/brave/brave-browser/issues/18417).

**Comment by ShivanKaul** [comment]
We need additional text/permission prompting for this before making enable-able.

**Comment by pes10k** [comment]
Suggested text:

```Allowing a site to access a Bluetooth device will allow the site to read identifying and potentially sensitive information about you. Only allow sites you trust to access Bluetooth devices.```

WDYT @diracdeltas @fmarier ?

**Comment by pes10k** [comment]
great! @diracdeltas did you mention @goodov might be able to handle this?

**Comment by diracdeltas** [comment]
i don't think he volunteered but i suggested @goodov since he did the other flags fix :)

**Comment by pes10k** [comment]
Sounds great!  @goodov do you have availability to make this text change and then add the flag (default off) back? If not, no worries, we can all discuss on Slack who would be best to handle

**Comment by goodov** [comment]
> Sounds great! @goodov do you have availability to make this text change and then add the flag (default off) back? If not, no worries, we can all discuss on Slack who would be best to handle

I can do this. Where do you want to put the text? Should it be on the `brave://flags` page or in the Bluetooth permission popup?

![image](https://github.com/brave/brave-browser/assets/5928869/e4068937-ae9e-4927-b2c4-8c03b443abf5)

**Comment by pes10k** [comment]
it should be in the permission popup.  Though, just noticing, how / where would permission lifetimes come up for this too?

**Comment by mholt** [comment]
This is good timing.

We exclusively use Brave on the iPad for our family.

Our current use case is we need the WebBluetooth API for an app like this: https://loginov-rocks.github.io/Web-Bluetooth-Terminal/ -- which allows the kids to communicate with their Arduino HM-10 module from the iPad so they can continue to learn and explore programming and robotics.

Moving to Chrome or installing a native app would have an _adverse_ affect on the privacy and security of our family, so I really appreciate that Brave has relaxed its position of "no, absolutely not" to "no by default, but you can turn it on if you know what you're doing."

**Comment by fmarier** [comment]
> How does one access the flags on Brave for iOS? 🧐 I can't seem to load them

@mholt This is not going to help for the iOS version of Brave which, due to Apple's platform restrictions, is using a Safari-based webview. As far as I know, there are no browsers on iOS that implement WebBluetooth since Safari [does not support WebBluetooth](https://caniuse.com/?search=webbluetooth).

**Comment by mholt** [comment]
Aw man :slightly_frowning_face: 

I do believe it is possible with iOS though, for example, https://www.greenparksoftware.co.uk/projects/webble/1.2.3 is an iOS browser that apparently brings WebBluetooth support to iOS, even though Webkit doesn't support it natively. I was hoping that because Brave is based on Chrome it can support it.

Anyway, I realize that tangent is off-topic for this issue. I was just hoping to share my enthusiasm (now crushed) and add a use case to legitimize the need for this feature.

**Comment by goodov** [comment]
Test-case:
1. Open `brave://flags`, enable `Web Bluetooth API` flag, restart Brave.
2. Open https://permission.site
3. Press "Bluetooth"
4. Except permission dialog with a footnote message that has "Learn more" leading to https://github.com/brave/brave-browser/wiki/Privacy-risks-from-allowing-sites-to-access-hardware

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.59.100 Chromium: 117.0.5938.92 (Official Build) beta (arm64)
-- | --
Revision | 3243fffc43431ab8677e8139859670b4cd2df843
OS | macOS Version 14.0 (Build 23A344)
```

**Comment by LaurenWags** [comment]
@goodov just confirming that Step 4 above when I get the OS prompt is ok/expected?

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version:

```
Brave	1.59.109 Chromium: 118.0.5993.21 (Official Build) beta (64-bit) 
Revision	aacb6a6f8bd916bd49f064b2137b007fa6c47b51
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
Verified test plan in https://github.com/brave/brave-browser/issues/31605#issuecomment-1686344320

Flag: `brave://flags#brave-web-bluetooth-api`

1. Load https://permission.site
2. Select `Bluetooth`
3. Confirm prompt is shown to update permissions to scan for nearby devices
4. Select `Update permission`
5. Allow permission
6. Confirm list of nearby devices are shown
7. Select device from list, confirm pairing works
8. Ensure `Get help` will redirect user to web api guide

Example | Example | Example | Example | Example | Example
-|-|-|-|-|-
![Screenshot 2023-10-04 at 3 59 11 PM](https://github.com/brave/brave-browser/assets/17885425/5174f190-5afd-4403-bfc6-347ad5cb4439) | ![Screenshot 2023-10-04 at 3 59 40 PM](https://github.com/brave/brave-browser/assets/17885425/212e9628-2329-4206-a451-b895eeb4718d) | ![Screenshot 2023-10-04 at 3 59 48 PM](https://github.com/brave/brave-browser/assets/17885425/97d2eb7f-7b51-4cb2-9af3-882062d49510) | ![Screenshot 2023-10-04 at 4 00 11 PM](https://github.com/brave/brave-browser/assets/17885425/3e8c4ce8-2966-4466-b937-00aa22b17517) | ![Screenshot 2023-10-04 at 4 12 24 PM](https://github.com/brave/brave-browser/assets/17885425/5bfb2b41-4d93-40a8-ba2b-b8f65d691414) | ![Screenshot 2023-10-04 at 4 12 43 PM](https://github.com/brave/brave-browser/assets/17885425/13f52e46-de3b-4097-9305-4dd5d52908c1)
