### ISSUE TITLE
Implement market data v2 designs

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#31611]
Figma link: https://www.figma.com/file/muVcmcu4RFNu0LkXe9VRDl/Wallet-2.0?type=design&node-id=2093%3A511724&mode=dev

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.58.105 Chromium: 116.0.5845.114 (Official Build) beta (64-bit)
-- | --
Revision | 5a895596bcd7fcd930dab0714ea5cfa86c5aa0a7
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#19274](https://github.com/brave/brave-core/pull/19274)
- Verified market tab is using V2 design on both panel and wallet page
- Encountered [#32544](https://github.com/brave/brave-browser/issues/32544)

https://github.com/brave/brave-browser/assets/17010094/980e6bea-d383-4ae7-af2e-08fa5afb9aa7
