### ISSUE TITLE
Secondary network position changes when any network is selected 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#31610]
## Description 
Secondary network position changes when any network is selected 

## Steps to reproduce 

   1. Visit any page that triggers Web3 connection to shown wallet icon in URL bar
   2. Open the panel and select network selector
   3. Select any network and look at the position of the secondary networks

## Actual result 

https://github.com/brave/brave-browser/assets/17010094/b86d0073-1a13-48fe-ac24-7bbf2a5f3d31

## Expected result
Should not change position

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Not checked

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 13
   
## Brave version
1.57.1 x64 Beta build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @Pavneet-Sing @simoarpe

**Comment by simoarpe** [comment]
It seems from the video recorded that also primary network position changes when tapped.

**Comment by kjozwiak** [comment]
The above requires `1.57.42` or higher for `1.57.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.57.42 x64 build
- Verified steps from issue description
- Verified secondary networks position doesn't change when a different network is selected

https://github.com/brave/brave-browser/assets/17010094/9d41c7ab-dc6a-4d41-a739-8379accc63df
