### ISSUE TITLE
Brave crashes when new key is added and reset and reload using CRTL+R

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#31614]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/30840
Brave crashes when new key is added and reset and reload using CRTL+R
## Steps to Reproduce

   1. Clean profile 1.56.5
   2. Open brave://flags 
   3. set brave://flags/#brave-commands to Enabled
   4. Relaunch brave
   5. Open system->shortcuts
   6. Enter the `Pin` string in the the search for command textbox
   7. Add shortcut key alt+p `Pin tab` 
   8. Add shortcut key ctrl+alt+p for `Pin this page to Start screen…` 
   9. Click on the `Reset all to defaults` button at the bottom
   10. Make sure `Pin tab`  and `Pin this page to Start screen…`  are set to default
   11. Remove `Pin` string from the search for command textbox
   12. Reload using `CTRL+R` or `CTRL+Shift+R`
   13. Brave crashes

## Actual result:

Crash id
```
Crash from Thursday, 13 July 2023 at 17:08:50
Status:	Uploaded
Uploaded crash report ID:	c4540100-e8f6-640a-0000-000000000000
Upload time:	Thursday, 13 July 2023 at 17:08:52

```
## Expected result:

should not be any crash
## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave	1.56.5 Chromium: 115.0.5790.75 (Official Build) (64-bit) 
Revision	3433e4d513e8454ba0243deea3d53693661dc0c3-refs/branch-heads/5790@{#1430}
OS	Linux
## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Not sure
- Can you reproduce this issue with the nightly channel? Not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @rebron @brave/qa-team @fallaciousreasoning

**Comment by GeetaSarvadnya** [comment]
The issue is NOT reproducible on Windows 10 x64 - 1.56.5

**Comment by fallaciousreasoning** [comment]
Reproduces in 1.57.1

**Comment by fallaciousreasoning** [comment]
**Note:** more minimal repro is:
1. Change a shortcut
2. Reset shortcuts
3. Refresh the page.

**Comment by kjozwiak** [comment]
The above requires `1.56.9` or higher for `1.56.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave	1.56.9 Chromium: 115.0.5790.98 (Official Build) (64-bit) 
Revision	4eacc220b55f07c57d5a1f4b7e0e63a6f7e420a1-refs/branch-heads/5790_90@{#4}
OS	Linux
```

Followed the steps to reproduce from https://github.com/brave/brave-browser/issues/31614#issue-1802883703.

### Confirmed no crash when resetting and filtering for shortcuts

example | example | example
---------|----------|--------
<img width="1496" alt="Screen Shot 2023-07-19 at 10 54 55 AM" src="https://github.com/brave/brave-browser/assets/387249/eb768cae-f623-4f02-afeb-21b8039c878d"> | <img width="1496" alt="Screen Shot 2023-07-19 at 10 55 05 AM" src="https://github.com/brave/brave-browser/assets/387249/e3c662fc-cd64-416a-922d-73bf47b56448"> | <img width="1496" alt="Screen Shot 2023-07-19 at 10 55 10 AM" src="https://github.com/brave/brave-browser/assets/387249/595940be-5266-4686-b863-41131f3a5427">
