### ISSUE TITLE
Update Account Details Page to V2 Design

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#31617]
## Description 

We need to update the `Account Details` page to the new Wallet V2 design

![Screenshot 58](https://github.com/brave/brave-browser/assets/40611140/8dbd631c-6414-4b9e-a44c-12598bcb4ace)

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Linux

- Verified steps from [brave/brave-core#19372](https://github.com/brave/brave-core/pull/19372)
- Verified Accounts tab is now showing new V2 designs
- Verified all options on Account tab works as expected

https://github.com/brave/brave-browser/assets/17010094/81d1d05e-1c43-4746-b745-6439f9c66a7d

---------------------

**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#19372](https://github.com/brave/brave-core/pull/19372)
- Verified Accounts tab is now showing new V2 designs
- Verified all options on Account tab works as expected

https://github.com/brave/brave-browser/assets/17010094/df25fd9a-1633-44cd-ad47-fb762877f0b5

---------------------

**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (arm64)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | macOS Version 13.4.1 (c) (Build 22F770820d)

- Verified steps from [brave/brave-core#19372](https://github.com/brave/brave-core/pull/19372)
- Verified Accounts tab is now showing new V2 designs
- Verified all options on Account tab works as expected

https://github.com/brave/brave-browser/assets/17010094/725fb9d0-1e22-43b5-b185-55777c80b121
