### ISSUE TITLE
Update "flagged" error modal text (linking flow) | July 2023

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#31619]
## Description

Update text to:

>Unfortunately, your Brave Rewards profile was flagged because our automated checks found some unexpected Brave Ads activity. 
>
>While your profile is flagged, you may continue to see ads, but won't be eligible to receive payouts. You also won't be able to connect a custodial account to Brave Rewards.
>
>It's possible your profile was flagged in error, and no immediate action is required on your part. The flag on your profile may be removed in the future.
>
>[Learn more about Brave's process for flagging Rewards profiles.]

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.58.91 Chromium: 116.0.5845.96 (Official Build) beta (x86_64)
-- | --
Revision | 620fa9c0307b294dd6e7c6b0976bc1f93fecf369
OS | macOS Version 13.5 (Build 22G74)
```

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.58.110`

pre-req: Have Charles Proxy running with rewrite rule (for both HTTP code and response body) for claim endpoint

1. Clean profile, staging env
2. Close and relaunch to get griffin seed
3. Enable Rewards, link custodian
4. Confirm rewrite rule worked and you see expected message

```
  [ REQUEST ]
    > URL: https://grant.rewards.bravesoftware.com/v3/wallet/uphold/a7303339-10e6-534e-b256-94b32dad0231/claim
    > Method: POST
    > Content: {"signedLinkingRequest":"eyJib2R5Ijp7ImRlb....E3ODQzN1wifSJ9"}
    > Content Type: application/json; charset=utf-8
-----
  [ RESPONSE - OnResponse ]
    > Url: https://grant.rewards.bravesoftware.com/v3/wallet/uphold/a7303339-10e6-534e-b256-94b32dad0231/claim
    > Result: Failure
    > HTTP Code: 400
    > Body: {"message":"error linking wallet: unable to link - unusual activity: unusual activity","code":400}
2023-09-04 19:23:19.727 26998-26998/? I/chromium: [INFO:post_connect.cc(60)] Flagged wallet!
2023-09-04 19:23:19.730 26998-26998/? I/chromium: [INFO:connect_external_wallet.cc(186)] Failed to connect uphold wallet!
```
![Screenshot_20230904_192429](https://github.com/brave/brave-browser/assets/38657976/a6580d9d-eb1a-4ad4-b53a-dfcc834659cd)

**Comment by shuhei-fujita** [comment]
私も同じ問題が発生しています🤔

```
$ sw_vers

ProductName:		macOS
ProductVersion:		13.5.2
BuildVersion:		22G91
```

**Comment by Miyayes** [comment]
Hi @shuhei-fujita, if you are seeing this notice, please contact jpsupport@brave.com and copy-paste the information from your brave://rewards-internals page. cc: @A-t-s-u-s-h-i
