### ISSUE TITLE
Cannot connect wallet on GMX

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#31629]
## Description 

Connect panel gets dismissed frequently reported by @lukaslevert 

[video](https://github.com/brave/brave-browser/assets/11330831/0ced521a-eb5c-4b19-bc59-f2f02b1c4ac1
) captured by @StephenHeaps 

## Steps to Reproduce

   1. Setup wallet
   2. Navigate to https://app.gmx.io/#/trade 
   3. Click connect wallet and choose MetaMask

## Actual result:

Won't be able to finish connect request because request panel keeps getting dismissed

## Expected result:
Should be able to grant permission without panel being dismissed.

## Reproduces how often: 

100%

## Brave version (brave://version info)

v1.52.130 and v1.58.2

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on  

Brave | 1.56.6 Chromium: 115.0.5790.90 (Official Build) (64-bit)
-- | --
Revision | `86fb9d04c92b490e6cc0026ca58cb1a98735eea3-refs/branch-heads/5790@{#1583}`
OS | Windows 11 Version 22H2 (Build 22621.1992)

- Verified steps from issue description
- Verified able to successfully connect to Dapp

https://github.com/brave/brave-browser/assets/17010094/aab0315f-5c25-4c48-bea3-447e77b21fa3
