### ISSUE TITLE
keyboard shortcuts created with the "Option" key don't display as expected

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#31625]
## Description 

Keyboard shortcuts with the "Option" (macOS) key don't display properly when creating, but do display as expected after saving.

## Steps to Reproduce

   1. Enable brave://flags/#brave-commands if not already enabled
   2. Navigate to brave://settings/system/shortcuts
   3. Add a keyboard shortcut to any action listed
   4. Use the Option key plus a letter (ex. P)

## Actual result:

"P" is not displayed correctly in the add window

<img width="521" alt="1" src="https://github.com/brave/brave-browser/assets/28145373/9af60be3-acbc-4703-9ba3-cdb1b4e19db1">

## Expected result:

"P" should be displayed correctly in the add window, as it is when the shortcut is saved

<img width="686" alt="2" src="https://github.com/brave/brave-browser/assets/28145373/6432f87d-3cd4-4372-b187-cf3af488b396">

## Reproduces how often: 

easily

## Brave version (brave://version info)

```
Brave | 1.56.5 Chromium: 115.0.5790.75 (Official Build) (x86_64)
-- | --
Revision | 3433e4d513e8454ba0243deea3d53693661dc0c3-refs/branch-heads/5790@{#1430}
OS | macOS Version 13.4.1 (a) (Build 22F770820b)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? y 1.56.x
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? y 1.58.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron

**Comment by LaurenWags** [comment]
note, you may also see the below depending on which letter you use to test, per discussion with @rebron this is a separate issue, already filed.

<img width="526" alt="3" src="https://github.com/brave/brave-browser/assets/28145373/d38db285-c5ed-47a0-b8d5-e64ce7f15049">

**Comment by MadhaviSeelam** [comment]
Not able to reproduce in `Win 11` using `1.56.5`

![image](https://github.com/brave/brave-browser/assets/98358127/500b03e2-529f-43e9-82b8-283ca88fa80d)

**Comment by GeetaSarvadnya** [comment]
Not reproducible on `Linux - Brave version 1.56.5`

Example | Example
----------|----------
![image](https://github.com/brave/brave-browser/assets/38657976/a8cee552-a025-439a-8336-f21453636470) | ![image](https://github.com/brave/brave-browser/assets/38657976/8b2eb79e-49c6-4c62-ad04-aa2b6c72ffcb)

**Comment by fallaciousreasoning** [comment]
I think this has the same cause as this issue:
https://github.com/brave/brave-browser/issues/30879

Basically, what I'm displaying is the `Pressed Key`, which is generally some special key when you press Alt+Key on MacOS

**Comment by sangwoo108** [comment]
May I ask you what keyboard layout you're using?

**Comment by kjozwiak** [comment]
The above requires `1.57.42` or higher for `1.57.x` verification 👍
