### ISSUE TITLE
Do not show line separator after last line item in Rewards summary view

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#31621]
## Description

Remove the last line separator under the last line item in the Rewards summary view. For example, in the screenshot below, there should be no line separator under "Monthly Contributions".

![image](https://github.com/brave/brave-browser/assets/11497541/3156dadc-1de4-4047-a9b8-89523a3065cf)

```[tasklist]
### Tasks
- [ ] Rewards panel
- [ ] brave://rewards page panel card
```

**Comment by bharathkalyans** [comment]
Doesn't make much difference right?

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.58.88 Chromium: 116.0.5845.82 (Official Build) beta (x86_64)
-- | --
Revision | acf16e35d5897fd4bf9b1b5a93b56aff2ed64bba
OS | macOS Version 13.5 (Build 22G74)
```
