### ISSUE TITLE
Weight is not implemented correctly

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#3163]
In normalizer we are not correctly calculating weights.

JS implementation: https://github.com/brave/browser-laptop/blob/master/app/browser/api/ledger.js#L597

C++ implementation: https://github.com/brave/brave-core/blob/a30b7755df1bf4b9646a836e14fc3c65c903f5ce/vendor/bat-native-ledger/src/bat_publishers.cc#L554

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.59.33 Chromium: 72.0.3626.81 (Official Build) (64-bit)
-- | --
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/1510
* Verified when a profile from 0.58.21 is updated to 0.59.33 and a new site is visited, the a-c table correctly displayed (no sites lost, % values are accurate, weights in `publisher_info_db` are accurate)
