### ISSUE TITLE
Balances not showing on connect to site panel

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#31638]
## Description 

On nightly v1.58, balances associated with accounts doesn't show up. Likely only happening for users with a few accounts. 

![Screenshot 2023-07-13 at 15 03 51](https://github.com/brave/brave-browser/assets/12224304/2edd2fd3-46c5-4c0e-b748-a4b356a83f95)

cc @Douglashdaniel @onyb might have a solution for this 

## Steps to Reproduce

   1. 
   2. 
   3. 

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by darkdh** [comment]
For dapp logo I think it is CSP violation because I got this error every time I triggered the connect panel
```
[90804:259:0714/092330.296703:ERROR:CONSOLE(0)] "Refused to load the image 'chrome://favicon/size/64@1x/https://github.com' because it violates the following Content Security Policy directive: "img-src 'self' chrome://resources chrome://erc-token-images https://assets.cgproxy.brave.com data:".
", source: chrome://wallet-panel.top-chrome/?addr=0x7d944b3900750aac472324ddb5750b2154a1c203&addr=0x5e9e3e881b087994b56954dafd978449cb6f1aec&addr=0x1bf592b728267c3ba2afa4bfd6dcc70affe7731a&addr=0x781efcb08f722664bfaa2ea73b80cd79d115d91a&origin-scheme=https&origin-host=github.com&origin-port=443&origin-spec=https://github.com&etld-plus-one=github.com#connectWithSite (0)
```

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.58.109 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | a4ad1fcdb550daf076384dbb280ae944274b3d35
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#19337](https://github.com/brave/brave-core/pull/19337)
- Verified able to load token balances in Portfolio
- Verified able to load token prices in Portfolio
- Verified able to load pricing history (graph) in Portfolio
- Verified able to load fiat balances in Accounts
- Verified able to load token balances in Swap
- Verified on both panel V2 and Wallet page

https://github.com/brave/brave-browser/assets/17010094/e75f06e0-5541-4d9b-b086-65274c736942
