### ISSUE TITLE
Bump trezor-connect and protobufjs

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#31633]
Bump versions of trezor-connect and protobufjs to fix a high-severity audit issue.

|Audit issue| https://github.com/brave/brave-core/security/dependabot/54|
-|-

### Test plan

Ensure that you can continue to do the following actions using your Trezor device (testing with either One or T is enough):
- able to connect
- able to create account managed by Trezor
- able to create and sign a simple transaction

**Comment by onyb** [comment]
Resolved by https://github.com/brave/brave-core/pull/19199

**Comment by srirambv** [comment]
Verification passed on  

Brave | 1.56.6 Chromium: 115.0.5790.90 (Official Build) (64-bit)
-- | --
Revision | `86fb9d04c92b490e6cc0026ca58cb1a98735eea3-refs/branch-heads/5790@{#1583}`
OS | Windows 11 Version 22H2 (Build 22621.1992)

- Verified steps from issue description
- Verified able to create account managed by Trezor
- Verified able to create and sign a simple transaction

https://github.com/brave/brave-browser/assets/17010094/71b309d3-9dfe-4efa-9875-ca3df2f103e4
