### ISSUE TITLE
Fix Brave Ads custom notification ad positioning

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#31649]
Testing on MacOS:

- `normalized_display_coordinate_x` set to 1.0 do not show a custom ad on the right border.
- initial custom notification ad position is calculated for primary display only, even if it is shown on another display.

**Comment by kjozwiak** [comment]
The above requires `1.57.33` or higher for `1.57.x` 👍

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.57.36 Chromium: 115.0.5790.171 (Official Build) beta (64-bit) 
-- | --
Revision | a4bb683f14dc402f5da13707e13559dc4d5ef08b
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/19355

<details>

Verified that for `normalized_display_coordinate_x/0.0/normalized_display_coordinate_y/0.0/inset_x/0/inset_y/0` the custom ad is shown in top-left corner
![image](https://github.com/brave/brave-browser/assets/34715963/6ffbc30a-a755-40c8-ac1c-84dd7c0a1980)


Verified able to move the custom ad

Verified the position of custom ads is retained even after browser restart
![image](https://github.com/brave/brave-browser/assets/34715963/f52172ee-3600-40f4-b7ab-6395bf1cdb88)


Verified that for `normalized_display_coordinate_x/1.0/normalized_display_coordinate_y/1.0/inset_x/0/inset_y/0` the custom ad is shown in bottom-right corner
![image](https://github.com/brave/brave-browser/assets/34715963/25da6bdc-9934-4cbd-b121-c631ae3ad22e)


</details>
