### ISSUE TITLE
Update theme colors for light, dark, private window and private window with Tor

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#31644]
## Description 

Update the theme colors for light, dark, private window and private window with Tor.

## Design
<img width="1201" alt="Screenshot 2023-07-14 at 8 23 52 AM" src="https://github.com/brave/brave-browser/assets/5951041/d4d6776b-632b-4e7e-9c15-8f79853639ce">

Figma: https://www.figma.com/file/H11ZOl6JMYbCTW4ZJXqR5V/%F0%9F%A6%81-Browser?type=design&node-id=3014%3A33123&mode=design&t=nhfxV22NiGDSYN2e-1

## Reproduces how often: 

n/a

## Brave version (brave://version info)

n/a

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.62.28 Chromium: 119.0.6045.105 (Official Build) nightly (64-bit)
-- | --
Revision | af1dadeae432bc6f1bed980ac4123d5b7dda6e24
OS | Windows 11 Version 22H2 (Build 22621.2428)
```

- Installed 1.62.28
- launched Brave
- imported bookmarks
- opened few tabs, pinned tabs


#### *_Normal window_*
 
Light theme - horizontal| Light theme - vertical  
----- | ------  
<img width="958" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/f4d81a9b-f1bc-49be-a414-7b0396bcf78c">|<img width="961" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/bcf87588-824e-4072-bac5-2b08ea44a3ac">

Dark theme - horizontal| Dark theme - vertical  
----- | ------  
<img width="959" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/9be439ad-b3d1-42c1-b652-a7e8506f08a3">|<img width="958" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/943d3432-da9e-4cb6-ad3f-07e42d5fc035">

#### *_Private window_*

example | example | example 
----- | ------ | ------
<img width="956" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/be01b0a1-d91d-45ec-ab2b-8a8aecbfd3ac">|<img width="959" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/cb47b28a-9dec-4011-bebb-6c592285d6bf">|<img width="953" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/e2f5d23e-5950-436b-a2ee-480d2d1a296d">

#### *_Private window with Tor_*

example | example  
----- | ------ 
<img width="957" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/77c99f4e-14a3-47c6-8b2d-41249da17dd2">|<img width="962" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/971bc5f0-993f-421e-bd9a-0ab1b6fe2beb">

**Comment by aguscruiz** [comment]
Just noting here that in private/tor windows, we're showing a dark mode header and light mode content.
We should show them according to the mode the user selected and not mix them

![image](https://github.com/brave/brave-browser/assets/15734630/8d297f1d-7678-4de3-a7ca-0897c3871a96)

**Comment by simonhong** [comment]
> Just noting here that in private/tor windows, we're showing a dark mode header and light mode content. We should show them according to the mode the user selected and not mix them
> 
> ![image](https://user-images.githubusercontent.com/15734630/281026689-8d297f1d-7678-4de3-a7ca-0897c3871a96.png)

Filed https://github.com/brave/brave-browser/issues/34165

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.62.104 Chromium: 120.0.6099.71 (Official Build) beta (x86_64)
-- | --
Revision | e2b266991247b909fa88520bb12d018223872d29
OS | macOS Version 11.7.10 (Build 20G1427)
```

#### *_Normal window_*
 <details>
 
 Light theme - horizontal tab view
 1.60.x | 1.62.x 
 ----- | -----

 
 Light theme - vertical tab view
  1.60.x | 1.62.x 
 ----- | -----


Dark theme - horizontal tab view
 
  1.60.x | 1.62.x 
 ----- | -----

 Dark theme - vertical tab view
  1.60.x | 1.62.x 
 ----- | -----


 </details>

#### *_Private window_*
 <details>

 Light theme - horizontal tab view
 1.60.x | 1.62.x 
 ----- | -----


 Light theme - vertical tab view
  1.60.x | 1.62.x 
 ----- | -----

 Dark theme - horizontal tab view
  1.60.x | 1.62.x 
 ----- | -----


 Dark theme - vertical tab view
  1.60.x | 1.62.x 
 ----- | -----


 </details>

#### *_Private window with Tor_*
 <details>

 Light theme - horizontal tab view

  1.60.x | 1.62.x 
 ----- | -----


 Light theme - vertical tab view
  1.60.x | 1.62.x 
 ----- | -----


 Dark theme - horizontal tab view
  1.60.x | 1.62.x 
 ----- | -----


 Dark theme - vertical tab view
  1.60.x | 1.62.x 
 ----- | -----


 </details>

#### *_Guest window_*
 <details>

  1.60.x | 1.62.x 
 ----- | -----


 </details>

#### *_Profile custom theme_*
 <details>

Light theme - horizontal | Light theme - vertical
------- | --------


Dark theme - horizontal | Dark theme - vertical
------- | --------



Light theme - horizontal | Light theme - vertical
------- | --------


Dark theme - horizontal | Dark theme - vertical
------- | --------

 </details>

**Comment by btlechowski** [comment]
## Verification `PASSED` using

Brave | 1.62.122 Chromium: 120.0.6099.144 (Official Build) beta (64-bit)
-- | --
Revision | cfddebe77d394064c472fda64afcd9fbed34ceb4
OS | Linux


#### *_Normal window_*
 <details>
 
 Light theme - horizontal tab view

![image](https://github.com/brave/brave-browser/assets/34715963/1a112b94-af4b-48de-8d92-c15a184c0e60)


 Light theme - vertical tab view

![image](https://github.com/brave/brave-browser/assets/34715963/0c462583-ce53-49fb-9507-10e827ca978d)


Dark theme - horizontal tab view
 
![image](https://github.com/brave/brave-browser/assets/34715963/52517803-08a5-4305-8fd7-aa802de1d992)



 Dark theme - vertical tab view

![image](https://github.com/brave/brave-browser/assets/34715963/73326788-05d7-49bc-8409-9c8aafa5ff04)



 </details>

#### *_Private window_*
 <details>

 Light theme - horizontal tab view

![image](https://github.com/brave/brave-browser/assets/34715963/70812a42-2eb5-432e-b379-1313a3daaee3)


 Light theme - vertical tab view


![image](https://github.com/brave/brave-browser/assets/34715963/7135e2c7-de43-444d-8ed5-2274e886aa1a)


 Dark theme - horizontal tab view

![image](https://github.com/brave/brave-browser/assets/34715963/a537bebb-72c4-4c60-b93f-69556f0454a4)



 Dark theme - vertical tab view

![image](https://github.com/brave/brave-browser/assets/34715963/f3f1d99c-ee5a-40b7-a6bb-f13aaf08e1d7)




 </details>

#### *_Private window with Tor_*
 <details>

 Light theme - horizontal tab view


![image](https://github.com/brave/brave-browser/assets/34715963/18607364-5fc1-4fe4-9de7-9c0de1173857)



 Light theme - vertical tab view

![image](https://github.com/brave/brave-browser/assets/34715963/6f3432c7-2919-45c3-ac20-ca07772f3d06)


 Dark theme - horizontal tab view

![image](https://github.com/brave/brave-browser/assets/34715963/8776e674-9ce7-4f15-a5b5-d019326a0b56)



 Dark theme - vertical tab view

![image](https://github.com/brave/brave-browser/assets/34715963/22b134d1-e931-4d32-a3ac-18ee3ab09f43)



 </details>

#### *_Guest window_*
 <details>


![image](https://github.com/brave/brave-browser/assets/34715963/9822a5a0-e799-43a3-9010-7c88973c0f8d)




 </details>

#### *_Custom-theme profile_*
 <details>

## `Profile 1`, Dark Teal

Light theme - horizontal | Light theme - vertical
------- | --------
![image](https://github.com/brave/brave-browser/assets/34715963/5ef0653a-d679-4496-831f-56e8daa4b9a4)|![image](https://github.com/brave/brave-browser/assets/34715963/3013946b-7987-4ac1-b391-1618d820f534)


Dark theme - horizontal | Dark theme - vertical
------- | --------
![image](https://github.com/brave/brave-browser/assets/34715963/0b3500b7-455d-4f88-920c-141ae5b496cc)|![image](https://github.com/brave/brave-browser/assets/34715963/b385e29b-734c-4525-a19f-cd8fb8250c58)



 </details>

**Comment by nintendork07** [comment]
any chance this change could get reversed??? the new themes are too dark and text is much less legible, especially in private windows. it's giving me a lot more eye strain trying to read the tab & URL text fields

**Comment by devusr1x** [comment]
Looks horrible. Why push this to production?

Making text less legible, and changing something that stayed the same since the initial release, is generally frowned upon and a bad idea. This looks like I'm running a CRT filter on my screen.

You should all know this, but if I something isn't broken, don't to try fix it.

**Comment by devusr1x** [comment]
Meanwhile, 1.61.120 is working fine:

1. Download it from https://github.com/brave/brave-browser/releases/tag/v1.61.120
2. Uninstall the current version (without deleting your data, it will ask for this)
3. Install 1.61.120
4. Right after installing it, find a way to disable all Brave update services in your OS (I use Microsoft Autoruns, Ctrl+F for Brave)
5. Don't ever open the 'About' page (you can see the current version in the settings page)

And please don't bother with warnings about running old versions and security patches. I'm way more scared of the dev team at this point. This past year has been a mess, I don't know what's happening with direction.

**Comment by mc0ps** [comment]
I loved the default theme color for dark mode before this change. Not sure what the motivation was to mess with something that everyone seemed to like. I have a similar issue with the recent "polishing" of the icons by rounding the corners. Please consider reverting these styling changes or give users an option to retain the legacy styling.

**Comment by drkdw** [comment]
I like the new dark theme! 

I do have a question, how do you place the slack, twitter and gmail icon next to the tabs? I want to try that too.

**Comment by JoshAntBrown** [comment]
I'm all for improvements, but I don't understand how this can be considered an improvement. I'm sure dark mode probably looks nice, but the light mode theme now looks washed out and broken.

I've left some feedback on the community forum: https://community.brave.com/t/what-did-you-do-the-ui-looks-broken/528747.

If you want to introduce a new theme for some reason, then build it as a theme and make it the default, allow people to revert back to the previous theme.

**Comment by aguscruiz** [comment]
Hi everyone, thanks for the feedback. 
We're working on some color tweaks that should improve contrast and brightness a bit. 

@drkdw if you want to test out the new look and feel for the icons, you have to enable this flag #brave-horizontal-tabs-update. We're testing it out internally first :)

**Comment by drkdw** [comment]
@aguscruiz Thx! Looks great ;)

**Comment by devusr1x** [comment]
@aguscruiz 's "solution" once again broke my perfectly working browser with some awful new theme. Half of the point for me to use Brave instead of just using Chrome is better-looking square tabs with a lower height when compared to Chrome.

Unless I'm missing something here, this flag was **pushed remotely** to my browser today, even though I have auto updates disabled and I'm still on 1.61.120. Would anyone care to explain why Brave has remote access to my settings? This is not looking good at all.

Anyway, if you get pushed the new theme on 1.61.120 (pixelated outline for pinned tabs, round tabs which weren't present in Brave at all), you can disable it at the flags page:

chrome://flags/#brave-horizontal-tabs-update

**Comment by stephendonner** [comment]
We've landed a followup to lighten-up some of these colors; you can see it using the current `nightly` builds: https://github.com/brave/brave-browser/issues/35624

**Comment by devusr1x** [comment]
Brave started nagging me again today with a message about running older builds, which steals focus from anything you have running (I'm still running 1.61.120, since Brave devs seem to have to much of an ego to roll back on their poor decisions, despite threads with thousands of views about this on the official forums, or at least was the case before they were closed and vanished from the first page results).

You can disable these messages by running Brave with the flag `--disable-features=OutdatedBuildDetector`.

If you're running it from the taskbar on Windows, you will to modify the Brave taskbar shortcut which is located at `%AppData%\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar`.

And before you waste your time testing it, the current nightly does not fix the issue at all.

**Comment by nintendork07** [comment]
was this changed again? i updated to 1.70.117 today and the colors are too way dark.

![Screenshot 2024-09-19 at 3 10 23 PM](https://github.com/user-attachments/assets/33a0fb6d-f387-41df-88b1-f3a135fa7049)
