### ISSUE TITLE
Update "lock" icon to "tune" icon in address bar

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#31642]
## Description 

Chrome will be updating their lock icon per https://blog.chromium.org/2023/05/an-update-on-lock-icon.html and changing to a tune icon.

Update the "lock" icon to "tune" icon to match.

## Design:
<img width="573" alt="Screenshot 2023-07-14 at 8 15 06 AM" src="https://github.com/brave/brave-browser/assets/5951041/6abd5936-0ed6-4003-b928-ddbdee49185a">

https://www.figma.com/file/H11ZOl6JMYbCTW4ZJXqR5V/%F0%9F%A6%81-Browser?type=design&node-id=186%3A17108&mode=design&t=nhfxV22NiGDSYN2e-1

## Reproduces how often: 

n/a

## Brave version (brave://version info)

Target Chromium 117 and 1.58.x 

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

cc: @fmarier @diracdeltas

**Comment by diracdeltas** [comment]
We should make sure at least the settings that pop up when you click the tune icon match Chromium.

cc @ShivanKaul

**Comment by ShivanKaul** [comment]
I think they do currently.

One change I would like to see is that when you click the icon -> click `Cookies`, there should be some way to go directly to the cookies page for that site in Site Settings (e.g. brave://settings/cookies/detail?site=github.com).

**Comment by hy4l** [comment]
I thought my browser was hacked or somebody messed with encryption of my browser or something is going with DNS server redirection :-O It took me two days to figure out that I can search change log of Brave :D

**Comment by fallaciousreasoning** [comment]
Glad you found this PR!

**Comment by dncoder** [comment]
Is there any setting to revert back to the lock icon?

**Comment by fallaciousreasoning** [comment]
I'm afraid not @dncoder - now that most sites are HTTPS, the lock doesn't actually indicate security (just because a site is HTTPS doesn't mean it isn't phising).
