### ISSUE TITLE
Update horizontal tab shape for pins, normal tabs, and groups

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#31646]
## Description 

Add padding all around individual pins, tabs, and grouped tabs. Adding the border all around will make the bottom border appear to "detach" tabs from the main content window and will allow for better highlighting/color grouping of grouped tabs. 

Add border around pinned tabs.

## Design

<img width="1158" alt="Screenshot 2023-07-14 at 8 56 48 AM" src="https://github.com/brave/brave-browser/assets/5951041/6247e70a-880a-4694-8f23-f2be90a786c0">

Figma: https://www.figma.com/file/H11ZOl6JMYbCTW4ZJXqR5V/%F0%9F%A6%81-Browser?type=design&node-id=125%3A9048&mode=design&t=nhfxV22NiGDSYN2e-1

## Reproduces how often: 

n/a

## Brave version (brave://version info)

n/a

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by rebron** [comment]
@dpthegrey Is there a specific feature in Firefox with the Tabs UI that you're wanting to see?

**Comment by dpthegrey** [comment]
Hello @rebron , With Firefox we can change the tabs shape and in general customise the browser's appearance using CSS. The [FirefoxCSS Store](https://firefoxcss-store.github.io/) which showcases what the community has built to customize the shape of Firefox tabs and themes. I would like to see Brave offer similar customisation options.

and/or if we could include a few static tab shapes that are widely used in common browsers, in addition to the proposed design above. These shapes could be available in the settings menu, in a dropdown format just like there use to be a flag which could change tabs shape in earlier versions. 

#### Tab shape in Firefox
![image](https://github.com/brave/brave-browser/assets/49444980/d3868112-cc66-4909-8eca-93eca03a7e98)

#### Tab shape in Google Chrome
![image](https://github.com/brave/brave-browser/assets/49444980/37c49a48-b1df-4dfc-ad95-0686928d40d1)

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.60.81 Chromium: 118.0.5993.54 (Official Build) beta (64-bit)
-- | --
Revision | 1efb3f333eb41cc34af46ca31fb33c30e0afbfae
OS | Windows 11 Version 22H2 (Build 22621.2283)
```

1. Installed 1.60.81
2. launched Brave
3. opened `brave://flags`
4. enabled `#brave-horizontal-tabs-update` flag
5. opened few tabs

**_Normal tabs_**

- clicked on a tab to make the tab active
- hover over inactive tabs
- compared when #brave-horizontal-tabs-update` flag disabled vs enabled

#### Confirmed active tab shown with bottom border appeared to be `detached` from the main content window
#### Confirmed inactive tab, when hovered over, shown with bottom border appeared to be `detached` from the main content window

step 3 | step 6 | step 7 
----- | ---- | -----
<img width="959" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/69cf0994-17c0-4136-b947-ace7ee589b1b">|<img width="959" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/2634bc24-b213-465b-b080-a93a91c68d45">|<img width="959" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/aafb1aaa-6d88-440d-8d7e-6059e539bf91">

`#brave-horizontal-tabs-update` flag: 
example | example 
----- | -----
<img width="958" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/0b7866e2-2a8a-41ee-be64-e4d8e3ac6e07">|<img width="958" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/b0a9a607-08f4-458f-b1b2-afdd3f73aea1">

**_Pinned tabs_** 

- selected Pin tab from the context menu
- pinned 3 tabs 
- compared when #brave-horizontal-tabs-update` flag disabled vs enabled

#### Confirmed border around pinned tabs are shown and the shape is shown as per the Figma

example | example 
----- | ------
<img width="955" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/61f5e63a-af99-43c1-b7e3-6057adbc2ebe">|<img width="958" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/e9c5f39a-5843-4055-a350-00b7213b1eb3">

`#brave-horizontal-tabs-update` flag: 

Disabled | Enabled
----- | ------
<img width="961" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/c1a1317d-2b63-45fe-abbc-5ed69e8818bc">|<img width="960" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/df66c7bf-7c31-499e-9b0f-8ce8f440f27b">

**_Grouped tabs_**

- selected `Add tab to new group` >> New group
- Name the group (eg. newspapers)
- Add each tab to the group (eg. newspapers) via context menu
- hover over the group to view the added tabs
- click on the group expand or collapse the group
- compared when #brave-horizontal-tabs-update` flag disabled vs enabled

#### Confirmed highlighting/color grouping of grouped tabs. shown as per the Figma 

example | example | example |example | example | example 
-----| ----- | ----- | ------ | ------ | -------
<img width="159" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/5c4bd6eb-872e-4bbc-b674-d8d73adb14ff">|<img width="164" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/aa421e8b-2ade-4bb8-8877-fa8a2abc33ea">|<img width="158" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/937da22d-bd48-4d54-ba61-64fda57af881">|<img width="233" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/c8fdb761-d6c1-43d8-9d77-4d96e0b1e095">|<img width="955" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/5e2f19da-d29b-42c4-aa17-7b2e2a43fafb">|<img width="547" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/76e87310-f7a6-41f7-bf6f-2bbdde9692ce">

`#brave-horizontal-tabs-update` flag: 

Disabled | Enabled
----- | ------
<img width="955" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/a20d6e0a-009f-4826-8deb-30a89421ac14">|<img width="959" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/52e83f7d-6660-4443-a560-662d3936aa38">

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.60.86 Chromium: 118.0.5993.54 (Official Build) beta (x86_64)
-- | --
Revision | a174cdee5ce1b329d409f3dd8c450e98b7ff4511
OS | macOS Version 13.6 (Build 22G120)
```
