### ISSUE TITLE
Add padding and shadow to main content window

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#31645]
## Description 

Add padding and shadow to main content window to show separation. Add border radius to all four corners.
This will allow for clear separation when vertical and sidebar are open.

## Design

<img width="947" alt="Screenshot 2023-07-14 at 8 33 30 AM" src="https://github.com/brave/brave-browser/assets/5951041/65ad07e1-da8a-4229-9a83-a015eac75442">
<img width="961" alt="Screenshot 2023-07-14 at 8 36 14 AM" src="https://github.com/brave/brave-browser/assets/5951041/e75d4fef-bc80-4b0e-be97-4030256da045">

Figma: https://www.figma.com/file/H11ZOl6JMYbCTW4ZJXqR5V/%F0%9F%A6%81-Browser?type=design&node-id=186%3A17108&mode=design&t=nhfxV22NiGDSYN2e-1

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using 

```
Brave | 1.61.60 Chromium: 119.0.6045.105 (Official Build) beta (64-bit)
-- | --
Revision | 1ecda441378e2e473fd84b38456413224121751c
OS | Windows 11 Version 22H2 (Build 22621.2428)
```

Installed 1.61.60
launched Brave
opened brave://flags in a new tab
enabled `#brave-web-view-rounded-corners` 



before enabling the flag | after enabling the flag
------- | -------
<img width="553" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/70aa0450-38b9-48d0-9130-492dc6f2347c">|<img width="550" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/d5ecee72-2f32-4ed0-b454-874d856b5352">



https://github.com/brave/brave-browser/assets/98358127/4024b59b-a632-449f-90fe-2f5fca488720

**Comment by MadhaviSeelam** [comment]
Added `QA/Test-All-Platforms` label because found #34067 which could be windows specific and may not be an issue in macOS as confirmed by @aguscruiz

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.61.82 Chromium: 119.0.6045.163 (Official Build) beta (64-bit) 
Revision	c5d19b3a31e7e3ddaaa1fa2ea52b9338003e754e
OS	Linux
```

**Comment by LaurenWags** [comment]
changing to `release-notes/exclude` per discussion with @rebron

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.61.83 Chromium: 119.0.6045.163 (Official Build) beta (64-bit)
-- | --
Revision | f5a497784a959e96317dc946d9086098d8fa6c50
OS | Windows 10 Version 22H2 (Build 19045.3693)

```

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.61.83 Chromium: 119.0.6045.163 (Official Build) beta (64-bit)
-- | --
Revision | f5a497784a959e96317dc946d9086098d8fa6c50
OS | Windows 11 Version 22H2 (Build 22621.2715)
```


Steps:

1. installed 1.61.x
2. launched Brave
3. relaunched Brave to pull in griffin
4. verified `BraveWebViewRoundedCornersStudy:Enabled` entry shown
5. opened brave://flags in a new tab
6. verified brave://flags/#brave-web-view-rounded-corners is enabled as default
7. enabled vertical-tab view
8. opened the sidepanel

step 3 | step 4
----- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/c1526b26-6675-4e65-93c0-52b1545f57a7)|![image](https://github.com/brave/brave-browser/assets/98358127/8eff34b1-3677-49dc-b2ff-d5967c8730c7)

#### Light mode
Horizontal tab view | Vertical tab view | Reading list | Bookmarks | Leo panel | Brave talk | Wallet
----- | ----- | ----- | ----- | ----- | ----- | ------
<img width="1434" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/2cb6a329-d596-42fa-b658-e7b32125e62e">|<img width="960" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/6514dffb-53af-4fae-9234-4e43482ca074">|<img width="1434" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/d9124fcf-3a16-46a5-9ee4-0db35250560d">|<img width="961" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/a647df08-9806-4526-b06d-b1ef8d4b498d">|<img width="1434" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/c60513ec-1fff-4b0c-8c06-118e60762d14">|<img width="1434" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/9a0f50db-d8df-42ed-8eb5-4c20f264f166">|<img width="1434" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/50b5d033-38f8-4fe9-bb0d-c4453086777e">

#### Dark mode
Horizontal tab view | Vertical tab view | Reading List | Bookmarks | Leo panel | Wallet | Brave talk
----- | ----- | ----- | ----- | ----- | ----- | ------
![image](https://github.com/brave/brave-browser/assets/98358127/64c25a68-5c84-44cd-b13d-fca2e431f2d9)|![image](https://github.com/brave/brave-browser/assets/98358127/a79ec0f8-72d3-462f-a313-36a21ca28e6b)|![image](https://github.com/brave/brave-browser/assets/98358127/75f1032c-c04d-4f04-a678-cf638f788748)|![image](https://github.com/brave/brave-browser/assets/98358127/84cec505-6c8b-4c02-9a48-368c77c43037)|![image](https://github.com/brave/brave-browser/assets/98358127/7faf8009-134f-437d-8f37-0ff89c579d40)|![image](https://github.com/brave/brave-browser/assets/98358127/e73c5a71-eb8f-4d7d-b4c8-0d1670e1b5c6)|![image](https://github.com/brave/brave-browser/assets/98358127/893fee5c-c8a9-483f-aa46-10c00f84a9c0)
