### ISSUE TITLE
Remote Images are not loading in Brave Wallet

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#31647]
## Description 

on desktop, v1.58 the logo isn't showing up.

- Go to https://matcha.xyz/ and try to connect, the `Favicon` doesn't load`

<img width="422" alt="Screenshot 2023-07-14 at 18 25 36" src="https://github.com/brave/brave-browser/assets/12224304/2765584b-dd8e-4b43-adb1-0d4e97e41b0a">

- Go to https://www.coingecko.com/en/coins/aircoins and click `Add to Metamask`, the icon doesn't load.
- Add the token to your wallet and then open the panel and click on `View account assets`, the icon doesn't load.

![Screenshot 72](https://github.com/brave/brave-browser/assets/40611140/bc4c368d-e261-4ced-96e1-a9fc0fdd0bfc)

## Steps to Reproduce

   1. 
   2. 
   3. 

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by darkdh** [comment]
https://github.com/brave/brave-browser/issues/31638#issuecomment-1636091172
