### ISSUE TITLE
Load sidebar settings page in a new tab when clicks sidebar settings button

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#31663]
## Description 

Load sidebar settings page in a new tab when clicks sidebar settings button

## Steps to Reproduce

   1.  Click Sidebar settings button

## Actual result:

Sidebar settings page is loaded in current tab

## Expected result:
Sidebar settings page is loaded in new tab

If current tab is new tab, settings page is loaded in current tab.
If browser windows already has sidebar settings tab, it's activated instead of creating new tab

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by Silvrbckw** [comment]
commit and push

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.58.88 Chromium: 116.0.5845.82 (Official Build) beta (64-bit)
-- | --
Revision | acf16e35d5897fd4bf9b1b5a93b56aff2ed64bba
OS | Windows 11 Version 22H2 (Build 22621.2134)
```

Reproduced the issue in 1.56.20 

https://github.com/brave/brave-browser/assets/98358127/2b2ae55b-9928-49ad-80ee-6476910de72b

Steps: 

- Installed 1.58.88
- launched Brave
- clicked `Settings` button in the Sidebar

### Confirmed `brave://settings/?search=Sidebar` page loaded in a new tab


https://github.com/brave/brave-browser/assets/98358127/7a5080ce-4056-4201-8414-3463a6b5fbad
