### ISSUE TITLE
Perf: Virtualize the tokens list in the buy & deposit screens

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#31675]
## Description 

Use a virtualized list to prevent rendering too many below-the-fold list items.

## Steps to Reproduce

   1. Open the deposit screen
   2. select the all networks option from the filter

## Actual result:

The page loads the entire list all at once

## Expected result:
The tokens list should only render the list items that are visible

## Reproduces how often: 

Easy

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.58.100 Chromium: 116.0.5845.114 (Official Build) beta (64-bit)
-- | --
Revision | a8c0058265009a1858c4502b9ba413671fbb61e1
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#19306](https://github.com/brave/brave-core/pull/19306)
- Verified Buy and Deposit screens work as expected
