### ISSUE TITLE
Fix dark mode contribution value colors in Rewards panel

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#31676]
Followup to https://github.com/brave/brave-browser/issues/30971.

@szilardszaloki noticed that the original PR didn't factor in dark mode, so the BAT totals are too dark to see clearly in the Rewards panel.

## Actual

![Screenshot 2023-07-17 131546](https://github.com/brave/brave-browser/assets/5033691/3534180c-84cb-401d-9d8a-5e47b5baad08)

## Expected

![Screenshot 2023-07-17 131810](https://github.com/brave/brave-browser/assets/5033691/6be8d9e3-ea40-4778-bc8e-bf27e50a51a9)

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.58.79 Chromium: 116.0.5845.51 (Official Build) nightly (x86_64)
-- | --
Revision | 329052e01b863ee3939d05c5338ccece2b04e210
OS | macOS Version 13.5 (Build 22G74)
```

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Samsung galaxy version 12` running `Bravemonoarm64.apk_1.58.11`

Example | Example
----------|---------
![Screenshot_20230911-122247_Brave](https://github.com/brave/brave-browser/assets/38657976/bfd2b865-4f13-42ba-9113-b8355a481201) | ![Screenshot_20230911-122301_Brave](https://github.com/brave/brave-browser/assets/38657976/5c0de241-336f-447d-99cc-3094801e964b)
