### ISSUE TITLE
Perf: cache prices of purchasable assets

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#31685]
## Description 

Utilize the session cache to save the price of tokens displayed as available for purchase so that prices arent refetched as the virtualized list hides/shows items

## Steps to Reproduce

   1. Open the "buy" screen within the wallet
   2. scroll the list of tokens from top to bottom and back

## Actual result:

Prices are refetched as the list scrolls items into view

https://github.com/brave/brave-browser/assets/30185185/c1f42527-70b8-4bf0-b6f9-01afc9df84be

## Expected result:
Prices should not refresh when the list is scrolled

## Reproduces how often: 

Easy

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build)) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#19319](https://github.com/brave/brave-core/pull/19319)
- Verified price is only fetched once and scrolling doesn't refresh the price

https://github.com/brave/brave-browser/assets/17010094/f2ceae7b-f86e-4da2-b427-6a05bec593f1
