### ISSUE TITLE
Portfolio Settings Missing in Panel

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#31684]
## Description 

The Portfolio dropdown settings are missing on the `Panel` more menu

## Steps to Reproduce

   1. Open the Wallet Panel and open on the `More Menu`
   2. The Portfolio `Settings`  are missing

## Actual result:

![Screenshot 75](https://github.com/brave/brave-browser/assets/40611140/7d4883ea-6e57-4162-b7bf-14a30c969272)

## Expected result:
Should display the following settings when on the Portfolio's `Assets` or `NFT's` page
- Balances
- Graph
- NFTs tab

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.58.109 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Linux

- Verified steps from [brave/brave-core#19317](https://github.com/brave/brave-core/pull/19317)
- Verified Portfolio settings menu is shown in panel V2
![1](https://github.com/brave/brave-browser/assets/17010094/7c1ed0cc-728c-45a3-94bb-2c1588db255d)


---------------------

**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build)) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#19317](https://github.com/brave/brave-core/pull/19317)
- Verified Portfolio settings menu is shown in panel V2
![brave_Hcu3xyjbzG](https://github.com/brave/brave-browser/assets/17010094/daa0297a-5c15-4a02-8281-e2af56bd947b)

---------------------

**Verification passed on**

Brave | 1.57.27 Chromium: 115.0.5790.114 (Official Build) beta (arm64)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | macOS Version 13.4.1 (c) (Build 22F770820d)

- Verified steps from [brave/brave-core#19317](https://github.com/brave/brave-core/pull/19317)
- Verified Portfolio settings menu is shown in panel V2
![image](https://github.com/brave/brave-browser/assets/17010094/ab08ffc7-aff9-4756-85ab-85ea69b8f57f)
