### ISSUE TITLE
Release a new version of the Windows updater (Omaha) with the new code signing certificate

### ISSUE THREAD

**Issue by mherrmann** [brave/brave-browser#31696]
Our current Windows code signing certificate expires in August. We need to release a new version of our Windows updater that is signed with our new certificate. This happens independently of the browser's release schedule. The purpose of this issue is to document and capture QA efforts for testing that everything works as expected. There are no functional changes in the new version of the updater.

# Test plan

Please see the [attached PDF](https://github.com/brave/brave-browser/files/12079643/Testing.Brave.s.auto-update.mechanism.on.Windows.pdf).

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave | 1.56.9 Chromium: 115.0.5790.98 (Official Build) (64-bit)
-- | --
Revision | 4eacc220b55f07c57d5a1f4b7e0e63a6f7e420a1-refs/branch-heads/5790_90@{#4}
OS | Windows 10 Version 22H2 (Build 19045.3208)

```

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.56.9 Chromium: 115.0.5790.98 (Official Build) (64-bit)
-- | --
Revision | 4eacc220b55f07c57d5a1f4b7e0e63a6f7e420a1-refs/branch-heads/5790_90@{#4}
OS | Windows 11 Version 22H2 (Build 22621.1992)
```

1.  Uninstalled all copies of Brave and Omaha 
2.  Downloaded `BraveBrowserStandaloneSetup.exe` standalone installer `1.56.9 Chromium: 115.0.5790.98` and installed Brave
3. Opened Registry editor and verified the registry value via:   
      - `\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\BraveSoftware\Update\Clients\{B131C935-9BE6-41DA-9599-1F776BEB8019}` - `pv` was set to ` 1.3.361.137`
4. noted the `ap` value is  `x64-rel` via: 
    -  `\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\BraveSoftware\Update\ClientState\{AFE6A462-C574-4B8A-AF43-4CC60DF4563B}`  
5. changed ap from `x64-rel` ->`non-existent`  via 
   - `HKEY_LOCAL_MACHINE\SOFTWARE\BraveSoftware\Update\ClientState\{AFE6A462-C574-4B8A-AF43-4CC60DF4563B}`
6. created a new string value named `ap` and assigned it `beta` via
   - HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\BraveSoftware\Update\ClientState\{B131C935-9BE6-41DA-9599-1F776BEB8019}
7. connected to internet
8. Deleted the registry value `BraveSoftware\Update\LastChecked``
9. ran BraveSoftwareUpdateTaskMachineUA{......} via the Task Scheduler. This can take 2-3 minutes. Refresh with
F5 until the task status has switched back from Running to Ready.
10. confirmed omaha was successfully updated by verifying `pv` value changed to `1.3.361.141` in the registry eans 
         - `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\BraveSoftware\Update\ClientState\{B131C935-9BE6-41DA-9599-1F776BEB8019}`


step 2 | step 3 | step 4 | step 5 | step 6 | step 8 | step 9 | step 10
------- | -------- | -------- | -------- | ------- | ----- | ----- | ------
![image](https://github.com/brave/brave-browser/assets/98358127/5c8d1441-74ee-48a6-8aba-6fd9ac1dce1e)|![image](https://github.com/brave/brave-browser/assets/98358127/d8aa91ce-c817-447a-afa8-85ab53fdcd70)|![image](https://github.com/brave/brave-browser/assets/98358127/486e3285-c53d-4329-8807-2ca282c002d2)|![2023-07-21_13h04_56](https://github.com/brave/brave-browser/assets/98358127/df901316-11bd-474c-8bdc-5b410fc89434)|![2023-07-21_13h07_48](https://github.com/brave/brave-browser/assets/98358127/5b7d3e40-2e82-4ff9-8c06-8d8ad783ae3c)|![2023-07-21_13h10_36](https://github.com/brave/brave-browser/assets/98358127/b956e198-0f12-44de-8ecd-c4571cb33185)|![2023-07-21_13h15_44](https://github.com/brave/brave-browser/assets/98358127/5d4e255c-32e7-4fe0-9f0a-2ae4fd74847d)|![2023-07-21_13h21_45](https://github.com/brave/brave-browser/assets/98358127/6cfe3fc3-f2e6-4210-abdd-b22c2652b32c)

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using 
```
Brave	1.56.9 Chromium: 115.0.5790.98 (Official Build) (arm64) 
Revision	4eacc220b55f07c57d5a1f4b7e0e63a6f7e420a1-refs/branch-heads/5790_90@{#4}
OS	Windows 11 Version 22H2 (Build 22621.1848)
```
`Machine-wide` STR/Cases - `PASSED`

1.  Uninstalled all copies of Brave and Omaha 
2.  Downloaded `BraveBrowserStandaloneSetup.exe` standalone installer `1.56.9 Chromium: 115.0.5790.98` and installed Brave
3. disconnect from the internet to prevent accidental automatic updates
4. installed `Brave` with admin rights
5. Opened Registry editor and verified the registry value via:   
      - `\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\BraveSoftware\Update\Clients\{B131C935-9BE6-41DA-9599-1F776BEB8019}` - `pv` was set to ` 1.3.361.137`
6. noted the `ap` value is  `x64-rel` via: 
    -  `\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\BraveSoftware\Update\ClientState\{AFE6A462-C574-4B8A-AF43-4CC60DF4563B}`  
7. changed ap from `arm64-rel` ->`arm64-release1`  via 
   - `HKEY_LOCAL_MACHINE\SOFTWARE\BraveSoftware\Update\ClientState\{AFE6A462-C574-4B8A-AF43-4CC60DF4563B}`
8. created a new string value named `ap` and assigned it `beta` via
   - HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\BraveSoftware\Update\ClientState\{B131C935-9BE6-41DA-9599-1F776BEB8019}
8. connected to internet
9. Delete the registry value `BraveSoftware\Update\LastChecked`` if it exists - exists none
10. ran `BraveSoftwareUpdateTaskMachineUA{F2704819-7B56-454C-8997-16FF73DFB05A}` via the Task Scheduler. This can take 2-3 minutes. Refresh with F5 until the task status has switched back from Running to Ready.
11. confirmed omaha was successfully updated by verifying `pv` value changed to `1.3.361.141` in the registry via 
         - `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\BraveSoftware\Update\ClientState\{B131C935-9BE6-41DA-9599-1F776BEB8019}`
12. confirmed `BraveUpdate.exe` in Omaha’s installation directory has a digital signature that
expires in August 2024. (Rightlick -> Properties -> Digital Signatures -> sha1 / sha256 -> Details
-> View Certificate -> Valid from … to.)
13. changed the registry value
      - BraveSoftware\Update\ClientState\{B131C935-9BE6-41DA-9599-1F776BEB801 9}\ap to nightly. (we will now simulate another update of the updater to make sure updater is not left in a broken state by the update
14. repeat steps 8 and 9 to simulate another background update cycle.
15. verified the registry value `BraveSoftware\Update\Clients\{B131C935-9BE6-41DA-9599-1F776BEB8019}\pv` value changed to `1.3.361.143` and which mean Omaha was successfully updated again
16. Restored  BraveSoftware\Update\ClientState\{AFE6A462-C574-4B8A-AF43-4CC60DF4563 B}\ap to its original value. (check that on-demand updates of the browser still work)
17. Open Brave.
18. Navigate to brave://settings/help. Check that this updates Brave to the latest public version



step 4 | step 5 | step 6 | step 7 | step 8 | step 11 | step 12 | step 13 | x
------- | ------- | -------- | -------- | ------- | ------- | ------ | ---- | ------
![image](https://github.com/brave/brave-browser/assets/98358127/80d069f0-5d11-4c59-82e2-5e3d79f8c369)|![machine2_14h55_09](https://github.com/brave/brave-browser/assets/98358127/2aaf31ec-4f35-4f9b-942c-c5433cec0513)|![image](https://github.com/brave/brave-browser/assets/98358127/2ebcdfd4-07b9-4de6-856a-9312fd9be561)|![machine 3-14h55_53](https://github.com/brave/brave-browser/assets/98358127/4a556a90-ebc6-4af6-9c5a-868fe99ab8fb)|![image](https://github.com/brave/brave-browser/assets/98358127/f68259a9-9587-407a-a460-1ce67c0ca32a)|[machine 4_14h56_23](https://github.com/brave/brave-browser/assets/98358127/a1047306-d875-4f5f-a5f1-e61f2ab3c99a)|![machine 5_14h57_01](https://github.com/brave/brave-browser/assets/98358127/2238e6a1-f5fa-461c-8f52-7f624d609e2c)|![image](https://github.com/brave/brave-browser/assets/98358127/a96ba2c4-db7d-44d0-9532-c8e76597e832)|![image](https://github.com/brave/brave-browser/assets/98358127/f21696a8-f6d1-4fce-a70e-fcbba880cd03)



step 14 | step 15a | 15b | step 16 | step 17 | step 19a | step 19b
---- | ----- | ----- | ----- | ----- | ----- | -----
![image](https://github.com/brave/brave-browser/assets/98358127/fc72c1b4-7dc6-47ea-9cea-5045df1bd8a6)
![image](https://github.com/brave/brave-browser/assets/98358127/a7ed3b2d-7660-45ad-8cbd-c46e8a7c0d66)
![image](https://github.com/brave/brave-browser/assets/98358127/c4ceaa0f-f33b-426b-ab5b-3a896f7279bc)
![image](https://github.com/brave/brave-browser/assets/98358127/b8740366-61ce-45bb-8006-86f8e71c0e9d)

**Comment by kjozwiak** [comment]
## `Win 10 x86` verifications

### `Machine-wide` STR/Cases - `PASSED`

* installed `1.52.122 Chromium 114.0.5735.110` using the standalone installer via `BraveBrowserStandaloneSetup32.exe`
* once installed, checked `HKEY_LOCAL_MACHINE\SOFTWARE\BraveSoftware\Update\Clients\{B131C935-9BE6-41DA-9599-1F776BEB8019}` and ensured that `pv` was set as `1.3.361.137`
* noted that `ap` is set as `x86-rel` via `HKEY_LOCAL_MACHINE\SOFTWARE\BraveSoftware\Update\ClientState\{AFE6A462-C574-4B8A-AF43-4CC60DF4563B}`
* changed `ap` from `x86-rel` -> `non-existent` via `HKEY_LOCAL_MACHINE\SOFTWARE\BraveSoftware\Update\ClientState\{AFE6A462-C574-4B8A-AF43-4CC60DF4563B}`
* created a new `String Value` named `ap` and assigned it `beta` via `HKEY_LOCAL_MACHINE\SOFTWARE\BraveSoftware\Update\ClientState\{B131C935-9BE6-41DA-9599-1F776BEB8019}`
* once all of the above was completed, enanled the network on the VM machine
* ran `BraveSoftwareUpdateTaskMachineUA{89BBE5D5-6A6F-4B94-953B-3E90520BF833}` via the `Task Scheduler`
* checked `HKEY_LOCAL_MACHINE\SOFTWARE\BraveSoftware\Update\Clients\{B131C935-9BE6-41DA-9599-1F776BEB8019}` and ensured that `pv` was set as `1.3.361.141`
* Checked `BraveUpdate.exe` via `C:\Program Files\BraveSoftware\Update\1.3.361.141` and ensured that both certificates under `SHA1` & `SHA256` are appearing as `August 2024`
* changed `ap` to `Nightly` via `HKEY_LOCAL_MACHINE\SOFTWARE\BraveSoftware\Update\ClientState\{B131C935-9BE6-41DA-9599-1F776BEB8019}`
* removed `LastChecked` from `HKEY_LOCAL_MACHINE\SOFTWARE\BraveSoftware\Update`
* ran `BraveSoftwareUpdateTaskMachineUA{89BBE5D5-6A6F-4B94-953B-3E90520BF833}` via the `Task Scheduler`
* ensured that `pv` was set as `1.3.361.143` under `HKEY_LOCAL_MACHINE\SOFTWARE\BraveSoftware\Update\Clients\{B131C935-9BE6-41DA-9599-1F776BEB8019}`
* Checked `BraveUpdate.exe` via `C:\Program Files\BraveSoftware\Update\1.3.361.143` and ensured that both certificates under `SHA1` & `SHA256` are appearing as `August 2024`
* restored `ap` to `x86-rel` via `HKEY_LOCAL_MACHINE\SOFTWARE\BraveSoftware\Update\ClientState\{AFE6A462-C574-4B8A-AF43-4CC60DF4563B}`
* opened Brave and navigated to `brave://settings/help` and ensured Brave was updated to `1.56.11 Chromium: 115.0.5790.102`

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** 
----------------|----------------|----------------|----------------|----------------|----------------
![image](https://github.com/brave/brave-browser/assets/2602313/5123c24d-dd5d-4a3a-bf13-983784f27da4) | ![image](https://github.com/brave/brave-browser/assets/2602313/8c6a2b4d-f17b-4d24-935b-d3d7b47584f7) | ![image](https://github.com/brave/brave-browser/assets/2602313/82744324-9a1e-4ad7-ad83-58a5f23dd9b8) | ![image](https://github.com/brave/brave-browser/assets/2602313/3613e02b-f98a-4319-b1c0-669cf787e0f6) | ![image](https://github.com/brave/brave-browser/assets/2602313/c04b24ae-40df-498c-a000-0c541d446bc1) | ![image](https://github.com/brave/brave-browser/assets/2602313/7758b5c5-f83a-4cbd-b8a6-a8945dc7aaba)

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** 
----------------|----------------|----------------|----------------|----------------|----------------
![image](https://github.com/brave/brave-browser/assets/2602313/56601b73-6b8f-4088-8bb3-e7334c9cadb7) | ![image](https://github.com/brave/brave-browser/assets/2602313/b0fc31a5-4d82-4db4-91df-7400a6e04147) | ![image](https://github.com/brave/brave-browser/assets/2602313/8f04f23c-da20-4d94-8009-ca74297f87a2) | ![image](https://github.com/brave/brave-browser/assets/2602313/96475ea2-7013-499a-a7b9-864746c6c98c) | ![image](https://github.com/brave/brave-browser/assets/2602313/60bbb43c-d4cc-4c7c-bb35-25449f9e6525) | ![image](https://github.com/brave/brave-browser/assets/2602313/99d4c04f-812a-48a4-82e6-9add430eaeee)

**`Example`** | **`Example`** | **`Example`**
----------------|----------------|---------------
![image](https://github.com/brave/brave-browser/assets/2602313/3b759867-2708-4174-b3b8-e153b22f16f6) | ![image](https://github.com/brave/brave-browser/assets/2602313/7aac5fdd-dde0-44a7-8798-151b3b54f37d) | ![image](https://github.com/brave/brave-browser/assets/2602313/bfa75633-10bb-40d8-9342-9f5a0b4529a4)

### `Per-user` STR/Cases - `PASSED`

* installed `1.52.122 Chromium 114.0.5735.110` using the standalone installer via `BraveBrowserStandaloneSetup32.exe`
* once installed, checked `HKEY_CURRENT_USER\SOFTWARE\BraveSoftware\Update\ClientState\{B131C935-9BE6-41DA-9599-1F776BEB8019}` and ensured that `pv` was set as `1.3.361.137`
* noted that `ap` is set as `x86-rel` via `HKEY_CURRENT_USER\SOFTWARE\BraveSoftware\Update\ClientState\{AFE6A462-C574-4B8A-AF43-4CC60DF4563B}`
* changed `ap` from `x86-rel` -> `non-existent` via `HKEY_CURRENT_USER\SOFTWARE\BraveSoftware\Update\ClientState\{AFE6A462-C574-4B8A-AF43-4CC60DF4563B}`
* created a new `String Value` named `ap` and assigned it `beta` via `HKEY_CURRENT_USER\SOFTWARE\BraveSoftware\Update\ClientState\{B131C935-9BE6-41DA-9599-1F776BEB8019}`
* once all of the above was completed, enanled the network on the VM machine
* ran `BraveSoftwareUpdateTaskUserS-1-5-21-1130056253-3312545454-914106924-1001UA{827132BF-9B8E-4836-97FE-2E86DD89FC5A}` via the `Task Scheduler`
* checked `HKEY_CURRENT_USER\SOFTWARE\BraveSoftware\Update\Clients\{B131C935-9BE6-41DA-9599-1F776BEB8019}` and ensured that `pv` was set as `1.3.361.141`
* Checked `BraveUpdate.exe` via `C:\Users\kjozwiak-Win86\AppData\Local\BraveSoftware\Update\1.3.361.141` and ensured that both certificates under `SHA1` & `SHA256` are appearing as `August 2024`
* changed `ap` to `Nightly` via `HKEY_CURRENT_USER\SOFTWARE\BraveSoftware\Update\ClientState\{B131C935-9BE6-41DA-9599-1F776BEB8019}`
* removed `LastChecked` from `HKEY_CURRENT_USER\SOFTWARE\BraveSoftware\Update`
* ran `BraveSoftwareUpdateTaskUserS-1-5-21-1130056253-3312545454-914106924-1001UA{827132BF-9B8E-4836-97FE-2E86DD89FC5A}` via the `Task Scheduler`
* ensured that `pv` was set as `1.3.361.143` under `HKEY_CURRENT_USER\SOFTWARE\BraveSoftware\Update\Clients\{B131C935-9BE6-41DA-9599-1F776BEB8019}`
* Checked `BraveUpdate.exe` via `C:\Users\kjozwiak-Win86\AppData\Local\BraveSoftware\Update\1.3.361.143` and ensured that both certificates under `SHA1` & `SHA256` are appearing as `August 2024`
* restored `ap` to `x86-rel` via `HKEY_CURRENT_USER\SOFTWARE\BraveSoftware\Update\ClientState\{AFE6A462-C574-4B8A-AF43-4CC60DF4563B}`
* opened Brave and navigated to `brave://settings/help` and ensured Brave was updated to `1.56.11 Chromium: 115.0.5790.102`

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** 
----------------|----------------|----------------|----------------|----------------|----------------
![image](https://github.com/brave/brave-browser/assets/2602313/7c1bf2e7-cd0b-46fd-a3a2-2aa67979f616) | ![image](https://github.com/brave/brave-browser/assets/2602313/f69bf08a-6270-4190-8af0-75214d9dab92) | ![image](https://github.com/brave/brave-browser/assets/2602313/133220d4-bc4f-4671-968d-ca44168f4c1c) | ![image](https://github.com/brave/brave-browser/assets/2602313/866a82f7-1e8c-48f0-a729-75c845e7ff7c) | ![image](https://github.com/brave/brave-browser/assets/2602313/e8dfcdfc-b2cd-4782-a3b4-d5853b2bfbee) ![image](https://github.com/brave/brave-browser/assets/2602313/8c76822e-8a7f-4d25-87c6-7d3c73db63e2)

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** 
----------------|----------------|----------------|----------------|----------------|----------------
![image](https://github.com/brave/brave-browser/assets/2602313/f3e8feda-5e1f-4388-a3e3-767ad546b522) | ![image](https://github.com/brave/brave-browser/assets/2602313/040ee4f6-aad1-4be9-b947-65ca02e7861b) | ![image](https://github.com/brave/brave-browser/assets/2602313/b1df679e-a1cf-4939-808f-ab8aee9a01b0) | ![image](https://github.com/brave/brave-browser/assets/2602313/1dbd7484-5426-4d39-a028-6a965f1ac93e) | ![image](https://github.com/brave/brave-browser/assets/2602313/069ae6df-a95c-4d0a-b14e-31778f674d49) | ![image](https://github.com/brave/brave-browser/assets/2602313/0d88cf29-3898-4f1e-9628-ba5d3074108b)

**`Example`** | **`Example`** | **`Example`**
----------------|----------------|---------------
![image](https://github.com/brave/brave-browser/assets/2602313/202e56c8-f8b0-496d-9ac7-60ad5db2058c) | ![image](https://github.com/brave/brave-browser/assets/2602313/0f1d518b-bafa-4650-8c7c-0e4095f32f54) | ![image](https://github.com/brave/brave-browser/assets/2602313/8f2f5721-727e-4647-892b-11cbc664f7f8)

**Comment by DesertBear** [comment]
Is there a reason why the delta update executables are no longer code-signed from Brave 1.56? See the post here:

https://community.brave.com/t/sign-executables-with-publisher-certificates-for-allow-listing/498494

**Comment by mherrmann** [comment]
@DesertBear thank you for pointing this out. I've opened an [issue](https://github.com/brave/brave-browser/issues/31977) for this.

**Comment by MadhaviSeelam** [comment]
Retested Per_user install and on demand updates are failing via `brave://settings/help`

### **_`Per user` STR/Cases_**  

1.  uninstalled all copies of Brave and Omaha 
2.  downloaded `[BraveBrowserStandaloneSetupArm64.exe](https://github.com/brave/brave-browser/releases/download/v1.56.14/BraveBrowserStandaloneSetupArm64.exe) ` standalone installer `1.56.14 Chromium: 115.0.5790.98` 
3. disconnected from the internet to prevent accidental automatic updates
4. installed `Brave` without admin rights
5. opened Registry editor and verified the registry value via: 
      - `HKEY_CURRENT_USER\SOFTWARE\BraveSoftware\Update\Clients\{B131C935-9BE6-41DA-9599-1F776BEB8019}` and confirmed that pv was set as `1.3.361.137`
6. noted that ap is set as `arm64-rel` via 
      -  `HKEY_CURRENT_USER\SOFTWARE\BraveSoftware\Update\ClientState\{AFE6A462-C574-4B8A-AF43-4CC60DF4563B}`
7. changed ap from `arm64-rel` -> `arm64-release1` via `HKEY_CURRENT_USER\SOFTWARE\BraveSoftware\Update\ClientState\{AFE6A462-C574-4B8A-AF43-4CC60DF4563B}`
8. created a new string value named `ap` and assigned it `beta` via 
      - `HKEY_CURRENT_USER\SOFTWARE\BraveSoftware\Update\ClientState\{B131C935-9BE6-41DA-9599-1F776BEB8019}`
9. connected to internet
10. delete the registry value `BraveSoftware\Update\LastChecked` if it exists. - None
        - HKEY_CURRENT_USER\Software\BraveSoftware\Update
11. ran `BraveSoftwareUpdateTaskUserS-1-5-21-15201386-997740192-2843101882-1001UA{BB5591F1-3B75-43F0-89EA-EA878F4A19C1}` via the Task Scheduler. This can take 2-3 minutes. Refresh with F5 until the task status has switched back from Running to Ready.
12. confirmed omaha was successfully updated by verifying `pv` value changed to `1.3.361.141` in the registry via
      - `HKEY_CURRENT_USER\SOFTWARE\BraveSoftware\Update\Clients\{B131C935-9BE6-41DA-9599-1F776BEB8019}\pv`
13. confirmed `BraveUpdate.exe` in Omaha’s installation directory has a digital signature that
expires in August 2024. (Rightlick -> Properties -> Digital Signatures -> sha1 / sha256 -> Details
-> View Certificate -> Valid from … to.)
14. changed the registry value `ap` to `nightly` via 
       - `BraveSoftware\Update\ClientState\{B131C935-9BE6-41DA-9599-1F776BEB801 9}\`. (we will now simulate another update of the updater to make sure updater is not left in a broken state by the update
15. repeat steps 10 and 11 to simulate another background update cycle.
16. verified the registry `pv` value changed to `1.3.361.143` via
       - `BraveSoftware\Update\Clients\{B131C935-9BE6-41DA-9599-1F776BEB8019}\pv`   which means that Omaha was successfully updated again.
17. Restored `BraveSoftware\Update\ClientState\{AFE6A462-C574-4B8A-AF43-4CC60DF4563 B}\ap` to its original value to check that on-demand updates of the browser still work
       - `ap` - `arm64-rel`
18. opened Brave.
19. navigated to `brave://settings/help` and verified Brave updated to the latest public version `1.56.11`


step 4 | step 5 | step 6 | step 7| step8 | step 10 | step 11 | step 12 | step 13
---- | ---- | ----- | ----- | ----- | ---- | ------ | ----- | ------
<img width="515" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/122be52a-1dc4-405d-981e-641a418dd0cf">|<img width="515" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/08ab1cba-0cc6-4595-9d3c-9da1c7b3224f">|<img width="515" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/e2c2fc64-b005-4cee-8c94-61ad2f8c8024">|<img width="515" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/d19f3478-17e4-45a5-a015-d9acc88be87e">|<img width="515" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/56de9741-4a9d-4bee-9bbb-8e536f9907a5">|<img width="515" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/0db91dac-6f8e-44f0-b061-da9a7e593b4e">|<img width="515" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/5d8c5775-b387-4d46-98b2-b1cbc3f42632">|<img width="515" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/09ea32c8-a39c-459b-904a-20133fe241c2">|<img width="515" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/796634cf-ada9-4f58-967c-1a52ec38f2e6">

step 14 | step 15 | step 16 | step 17 | step 19 
---- | ----- | ----- | ----- | ----- 
<img width="515" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/1f988689-4604-4a15-92c6-99174191bc1e">|<img width="515" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/65189cb8-dc95-499c-ae64-674097d87728">|<img width="515" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/83f4ec56-7468-43b9-b350-6fae750fea92">|<img width="515" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/759f0277-f261-4c8c-894b-2551c3b43cc1">|<img width="515" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/f6f97fc0-23b8-4c1a-9a07-69e62bda10bd">
