### ISSUE TITLE
Brave Android Crashes On Clicking Search Bars

### ISSUE THREAD

**Issue by anxiouslelimo** [brave/brave-browser#31699]
## Description 

Issue happening for months. To be specific going to google.com, turning search history off and performing a search crashes brave. Similar crashes happen with other websites too. It makes brave unusable.

## Steps to reproduce 

   1. Go to google.com
   2. Turn search history toggle off
   3. Type on search bar. 

## Actual result 

Brave Crashes

## Expected result

Shouldn't crash and perform the search

## Issue reproduces how often 

Easily reproduced

## Version/Channel Information:

Happens in all channels
- Can you reproduce this issue with the current Play Store version?  Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes 
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM64
   - Device type (Phone, Tablet, Phablet): Phone (Samsung Galaxy M30s)
   - Android version: 11
   
## Brave version

Multiple brave versions

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by anxiouslelimo** [comment]
Random crashes. Even in brave search. 

4ced0900-e8f6-640a-0000-000000000000
f7250a00-e8f6-640a-0000-000000000000

**Comment by anxiouslelimo** [comment]
Searching through the community, found the workaround. Bitwarden autofill is causing the issue for me. Turned autofill and inline fill off. Brave does not crash. Through accessibility and draw over bitwarden autofill workaround also works.  

https://community.brave.com/t/brave-crashes-when-search-bar-is-clicked/463700
https://community.brave.com/t/brave-crashes-when-search-bar-is-clicked-round-two/484607/16
https://community.brave.com/t/brave-crash-after-when-trying-new-google-search/462608/22

**Comment by amit-katyal** [comment]
> Searching through the community, found the workaround. Bitwarden autofill is causing the issue for me. Turned autofill and inline fill off. Brave does not crash. Through accessibility and draw over bitwarden autofill workaround also works.  
> 
> https://community.brave.com/t/brave-crashes-when-search-bar-is-clicked/463700
> https://community.brave.com/t/brave-crashes-when-search-bar-is-clicked-round-two/484607/16
> https://community.brave.com/t/brave-crash-after-when-trying-new-google-search/462608/22

Yes you are right, although in my case Google search didn't crash but Duckduckgo and Bing crashed. Turning off bitwarden autofill service, fixed it. Seems like brave is constantly making queries with bitwarden (or vice versa) when a search is performed.

**Comment by brambedkar59** [comment]
@amit-katyal I am not using Bitwarden autofill service, instead I have MS Authenticator for my passwords. It still crashes Brave. So annoying. 
I have disabled autofill service, let's see how that goes.

**Comment by amit-katyal** [comment]
> @amit-katyal I am not using Bitwarden autofill service, instead I have MS Authenticator for my passwords. It still crashes Brave. So annoying. 
> I have disabled autofill service, let's see how that goes.

Perhaps, it's just got to do with password managers & authenticators in general. I am not using brave anymore, so I can't confirm. 
The devs aren't paying attention to this issue, it might not be as widespread because majority of people aren't using autofill services. And yes, it is quite annoying!

**Comment by iefremov** [comment]
does it still happen for anyone?

**Comment by iefremov** [comment]
pls reopen if someone can reproduce and upload dumps from brave://crashes, thanks!
