### ISSUE TITLE
Pattern for one-off checks after Rewards engine initialization 

### ISSUE THREAD

**Issue by szilardszaloki** [brave/brave-browser#31698]
Currently, we implement one-off checks with a `base::RetainingOneShotTimer` that does polling to determine whether the Rewards engine is ready, or not. If it's ready, it does the check, if it's not, then it resets itself. Technically, there's no actual polling taking place (as the `delay` parameter of the timer is set to 1 minute, which is plenty for the utility process to init), but this approach is not ideal by any means.

**Comment by zenparsing** [comment]
Currently, "post-initialization jobs" are started from `RewardsEngineImpl::StartServices`, but this requires wiring every job through the `RewardsEngineImpl` API hierarchy.

Some options that have been discussed:

- Create an observation API, and have helpers listen for an "initialized" event.
- Create a post-initialization callback registration API.
- Use a `base::SupportsUserData` style approach for composing engine helpers and have an initialization manager that directly calls out to the various helpers that need to have some post-initialization work started.
