### ISSUE TITLE
Wrong path preview of 'open source software' at chrome://settings/help

### ISSUE THREAD

**Issue by anushshetty8** [brave/brave-browser#3170]
## Description 
As we navigate to chrome://settings/help, and hover the cursor over 'open source software', the location preview on the bottom left shows it's location to be chrome://credits, while the location actually is brave://credits .
## Steps to Reproduce

   1. Navigate to chrome://settings/help
   2. Hover the pointer over 'open source software'
   3. You'll find the wrong path preview on the bottom left
## Actual result:
Link to screenshot:
https://pasteboard.co/HYViPNV.png
(My pointer is placed over 'open source software'. The pointer wasn't captured.)

## Expected result:
The preview path should be brave://credits

## Reproduces how often: 
Easily reproduces

## Brave version (brave://version info)
Brave Version 0.58.21 Windows
Chromium: 71.0.3578.98 (Official Build) (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
No
- Is the issue reproducible on the latest version of Chrome? 
No

**Comment by anushshetty8** [comment]
Not chrome://settings/help, but brave://settings/help.

**Comment by srirambv** [comment]
Should be fixed as part of #326 and  #1616 (#1774)
