### ISSUE TITLE
Add Brave Rewards custodial balances into Brave Wallet 

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#31713]
## Description

Show Brave Rewards custodial balances in Brave Wallet. 

https://www.figma.com/file/eqdxJmEUTSUrTJhYN21Cqp/BAT-on-chain-payout?type=design&node-id=3050%3A194110&mode=design&t=gA4UntccJzitRctQ-1

![image](https://github.com/brave/brave-browser/assets/11497541/cecd7c4e-7d84-477f-89c7-544e6ea1d1f1)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.61.91 Chromium: 119.0.6045.163 (Official Build) beta (64-bit)
-- | --
Revision | 3605d2d6aef7a52416f219a66838809b9254b3c4
OS | Windows 11 Version 23H2 (Build 22631.2715)
Custodian | Uphold

- Verified steps from [brave/brave-core#20524](https://github.com/brave/brave-core/pull/20524)
- Verified on a clean profile, creating wallet doesn't show any Rewards custodian balance under Portfolio or list custodian accounts under Accounts tab
- Verified on connecting to a custodian account, Wallet adds the custodian account to the list of available accounts
- Verified Portfolio balance is updated with custodian account balance (shows custodian balance if there is no wallet balance, adds balance to wallet balance if wallet is restored)
- Verified graph updates with custodian balance shown in the Portfolio
- Verified able to list custodian account when filtered by Network/Account 
- Verified custodian provider is listed under `Platform` in `Portfolio Filters`
- Verified clicking on `Brave Rewards BAT on <custodian>` loads the asset details view for the platform
- Verified route path contains the custodian name similar to `brave://wallet/crypto/portfolio/assets/uphold/0x0...`
- Verified disconnecting custodian shows `You’re currently logged out of <custodianAcc>. Please log in to view your balance.`
- Verified clicking on the `Login` button from the message redirects to the custodian page
- Verified when connected to a custodian, resetting wallet and creating a new wallet or importing wallet, automatically adds the custodian account details in Wallet
- Verified connecting to a custodian and creating wallet in older version and then upgrading to 1.61.x automatically shows the custodian details 


Connect on new profile | Reset & Import Wallet | Reset Wallet with connected Custodian | Profile upgrade with connected custodian
-- | --  | --  | --
<video src=https://github.com/brave/brave-browser/assets/17010094/ac9698a2-6dce-44c8-a704-fb73d445be43>| <video src=https://github.com/brave/brave-browser/assets/17010094/42729217-bc7b-433d-9a17-50595c6a9b2a> | <video src=https://github.com/brave/brave-browser/assets/17010094/259d3d31-738a-4682-a40f-97fd938b0970> | <video src=https://github.com/brave/brave-browser/assets/17010094/af2a2b16-355b-40f4-9e93-1f747ec2c50c>
