### ISSUE TITLE
Rewards publisher list is currently fetching every 48 hours. Should be set to 24 hours.

### ISSUE THREAD

**Issue by jasonrsadler** [brave/brave-browser#3171]
## Description 

Publisher list is fetched every 48 hours. This should be changed to 24 hours.

## Steps to Reproduce

   1. Enable Rewards
   2. Wait 24 hours

## Actual result:

Publisher list is not downloaded as it's set for 48 hours.

## Expected result:
Publisher list should download after 24 hours.

## Reproduces how often: 

always

## Brave version (brave://version info)

Brave | 0.58.21 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc @mandar-brave @rebron @Miyayes

**Comment by LaurenWags** [comment]
@jasonrsadler per step 4 in the test plan (https://github.com/brave/brave-core/pull/1524), what should we be looking for in the terminal? I'm launching with `--enable-logging=stderr --v=1 --vmodule=*rewards*=5`, is that what I need to launch with in order to see some kind of messaging in the terminal?

**Comment by jasonrsadler** [comment]
@LaurenWags Confused this test plan with grant checking. Updated step 4 to check timestamp on file.

**Comment by LaurenWags** [comment]
thanks @jasonrsadler!

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.60.26 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/1524
