### ISSUE TITLE
CR115 - The global switch for Autoplay/Solana/Ethereum content settings are missing

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#31710]
## Description 

The issue is reported by @rebron 
CR115 - The global switch for Autoplay/Solana/Ethereum/GoogleSignIn/LocalhostAccess content settings are missing

## Steps to Reproduce

Visit any of the following 5 pages:
   1. brave://settings/content/autoplay
   2. brave://settings/content/ethereum
   3. brave://settings/content/solana
   4. brave://settings/content/googleSignIn
   5. brave://settings/content/localhostAccess
  
**Note**: The last two pages require enabling the corresponding feature in brave://flags

## Actual result:

Autoplay | Solana | Ethereum | Google SignIn | Localhost Access
-----------|--------|------------|-----------------|-------------------
![autoplay](https://github.com/brave/brave-browser/assets/5033691/b49d7deb-d0ae-4185-93f7-d927a982b61f) | ![solana](https://github.com/brave/brave-browser/assets/5033691/60b2be52-fa08-49c6-aa67-940dbb4c934c) | ![ethereum](https://github.com/brave/brave-browser/assets/5033691/a3cc1744-2910-4f6a-93c9-05bf74f06ea9) | ![google](https://github.com/brave/brave-browser/assets/5033691/4333dc46-9084-4fb6-9ee9-7c7044cc4e93) | ![localhost](https://github.com/brave/brave-browser/assets/5033691/d022f367-05db-4800-8c21-e4e5436eebc3)

## Expected result:

Autoplay | Solana | Ethereum | Google SignIn | Localhost Access
-----------|--------|------------|-----------------|-------------------
![autoplay](https://github.com/brave/brave-browser/assets/5033691/bd86eb45-ebb7-48da-933e-9e8ace107480)| ![solana](https://github.com/brave/brave-browser/assets/5033691/08a87761-552d-4b9f-a8f4-6fc1f8db33ed) | ![ethereum](https://github.com/brave/brave-browser/assets/5033691/16f47397-6e36-4cb9-aa54-d0a97656cf63) | ![google](https://github.com/brave/brave-browser/assets/5033691/317c3f71-0d54-41e7-83fa-98dce53769a6) | ![localhost](https://github.com/brave/brave-browser/assets/5033691/dd2b0b91-a4c3-4d83-b3da-1737c332d385)

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.56.8 Chromium: 115.0.5790.98 (Official Build) (64-bit)
-- | --
Revision | 4eacc220b55f07c57d5a1f4b7e0e63a6f7e420a1-refs/branch-heads/5790_90@{#4}
OS | Windows 10 Version 22H2 (Build 19045.3208)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes in 1.56.x not in `1.52.130`
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @emerick @rebron @brave/qa-team

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave | 1.56.9 Chromium: 115.0.5790.98 (Official Build) (64-bit)
-- | --
Revision | 4eacc220b55f07c57d5a1f4b7e0e63a6f7e420a1-refs/branch-heads/5790_90@{#4}
OS | Windows 10 Version 22H2 (Build 19045.3208)

```

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.56.9 Chromium: 115.0.5790.98 (Official Build) (x86_64)
-- | --
Revision | 4eacc220b55f07c57d5a1f4b7e0e63a6f7e420a1-refs/branch-heads/5790_90@{#4}
OS | macOS Version 11.7.8 (Build 20G1351)

Autoplay | Solana | Ethereum | Google Signin | Localhost Access
---------|--------|-----------|---------------|------------------
