### ISSUE TITLE
Add Media Queries to the Export Account modal for Wallet Panel V2

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#31722]
## Description 

We need to add `Media Queries` to the `Export Account` modal to look good in the `Wallet Panel`

![Screenshot 2](https://github.com/brave/brave-browser/assets/40611140/6b287e2c-919a-4fc8-95ab-e7b45cf29d95)

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Linux

- Verified steps from [brave/brave-core#19388](https://github.com/brave/brave-core/pull/19388)
- Verified Edit account modal is shown correctly in Wallet Panel V2
![Export](https://github.com/brave/brave-browser/assets/17010094/8628aa82-547a-413a-8521-b2310e09f5f0)

---------------------

**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#19388](https://github.com/brave/brave-core/pull/19388)
- Verified Edit account modal is shown correctly in Wallet Panel V2
![brave_X0OLLUYH1V](https://github.com/brave/brave-browser/assets/17010094/22de46c8-b177-41fd-af78-d06c5baad7d9)

---------------------

**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (arm64)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | macOS Version 13.4.1 (c) (Build 22F770820d)

- Verified steps from [brave/brave-core#19388](https://github.com/brave/brave-core/pull/19388)
- Verified Edit account modal is shown correctly in Wallet Panel V2
![image](https://github.com/brave/brave-browser/assets/17010094/111fb036-4048-4f6b-87e6-09128853bfd8)
