### ISSUE TITLE
Add Media Queries to the Account Deposit modal for Wallet Panel V2

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#31723]
## Description 

We need to add `Media Queries` to the `Account Deposit` modal to look good in the `Wallet Panel`

![Screenshot 3](https://github.com/brave/brave-browser/assets/40611140/df66ead9-1200-4459-b7d1-cad0f8de1a95)

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Linux

- Verified steps from [brave/brave-core#19388](https://github.com/brave/brave-core/pull/19388)
- Verified Account Deposit modal is shown correctly in Wallet Panel V2
![Deposit](https://github.com/brave/brave-browser/assets/17010094/bf61c3a4-dd07-4105-bbe4-3121b187caf6)

---------------------

**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#19388](https://github.com/brave/brave-core/pull/19388)
- Verified Account Deposit modal is shown correctly in Wallet Panel V2
![brave_SwHChsrFTj](https://github.com/brave/brave-browser/assets/17010094/e25e47c4-3cab-4376-adfd-6b9c5d491a65)

---------------------

**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (arm64)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | macOS Version 13.4.1 (c) (Build 22F770820d)

- Verified steps from [brave/brave-core#19388](https://github.com/brave/brave-core/pull/19388)
- Verified Account Deposit modal is shown correctly in Wallet Panel V2
![image](https://github.com/brave/brave-browser/assets/17010094/defaf6a4-c534-4a37-8201-c402ff5f814c)
