### ISSUE TITLE
Add Media Queries to Sell Modal for Wallet Panel V2

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#31720]
## Description 

We need to add `Media Queries` to the `Sell` modal to look good in the `Wallet Panel`

![Screenshot](https://github.com/brave/brave-browser/assets/40611140/0973ecb7-9f33-4531-82bb-b2e088359ac9)

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Linux

- Verified steps from [brave/brave-core#19374](https://github.com/brave/brave-core/pull/19374)
- Verified Sell modal is shown correctly on Wallet Panel V2
![Sell](https://github.com/brave/brave-browser/assets/17010094/1c1e1e49-915b-413b-8325-1a97cb5f6dcb)

---------------------

**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#19374](https://github.com/brave/brave-core/pull/19374)
- Verified Sell modal is shown correctly on Wallet Panel V2
![brave_mOw3T131An](https://github.com/brave/brave-browser/assets/17010094/c48a9a9a-6a1f-40bd-ba69-e51434f0800b)

---------------------

**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (arm64)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | macOS Version 13.4.1 (c) (Build 22F770820d)

- Verified steps from [brave/brave-core#19374](https://github.com/brave/brave-core/pull/19374)
- Verified Sell modal is shown correctly on Wallet Panel V2
![image](https://github.com/brave/brave-browser/assets/17010094/9da1d349-72e7-46c4-8cdc-1a33cb2fd806)
