### ISSUE TITLE
Content settings header UI issue for Autoplay/Solana/Ethereum/Google-sign/Local host

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#31727]
## Description 

Found while testing https://github.com/brave/brave-core/pull/19340
Content settings header UI issue for Autoplay/Solana/Ethereum/Google-sign/Local host
## Steps to Reproduce

 Visit any of the following 5 pages:
   1. brave://settings/content/autoplay
   2. brave://settings/content/ethereum
   3. brave://settings/content/solana
   4. brave://settings/content/googleSignIn
   5. brave://settings/content/localhostAccess
  
**Note**: The last two pages require enabling the corresponding feature in brave://flags

## Actual result:

The content header is shown below the back arrow and font is not in bold letters
Autoplay | Solana | Ethereum | Google SignIn | Localhost Access
-----------|--------|------------|-----------------|-------------------
![image](https://github.com/brave/brave-browser/assets/38657976/6ab053e2-63a6-4296-a857-326ac55ce82f) | ![image](https://github.com/brave/brave-browser/assets/38657976/334e5801-1861-4b06-952c-6fda4621f0a0) | ![image](https://github.com/brave/brave-browser/assets/38657976/dfb6112b-afe1-4599-ac5f-89cfb214fef9) | ![image](https://github.com/brave/brave-browser/assets/38657976/ec56442b-e388-45fd-aeaf-57edd2af7a80) | ![image](https://github.com/brave/brave-browser/assets/38657976/d72d2622-3a43-4a1b-9951-5640c912d74d)

## Expected result:

**The content header should be shown behind the back arrow and font should be in bold**

Autoplay | Solana | Ethereum | Google SignIn | Localhost Access
-----------|--------|------------|-----------------|-------------------
![image](https://github.com/brave/brave-browser/assets/38657976/9bbf1cbc-02a8-41cf-9e1f-b1c23986f310) | ![image](https://github.com/brave/brave-browser/assets/38657976/321895d7-d170-4158-9ee4-87d69264c607) | ![image](https://github.com/brave/brave-browser/assets/38657976/70dd6715-b815-4560-8ce3-0371e4e5d7e1) | ![image](https://github.com/brave/brave-browser/assets/38657976/07bd8bf3-04eb-490d-b95d-67411d7dcbcd) | ![image](https://github.com/brave/brave-browser/assets/38657976/49366a6b-e361-410d-b60f-a9b1f3ef5416)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.58.31 Chromium: 115.0.5790.98 (Official Build) nightly (64-bit)
-- | --
Revision | e6a99ccb3ccfb160f5b6780a4aa83beceb024f62
OS | Windows 10 Version 22H2 (Build 19045.3208)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @emerick @rebron @brave/qa-team

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.60.81 Chromium: 118.0.5993.54 (Official Build) beta (x86_64)
-- | --
Revision | 1efb3f333eb41cc34af46ca31fb33c30e0afbfae
OS | macOS Version 13.6 (Build 22G120)
```
