### ISSUE TITLE
Submit button on VPN support ticket can get cut off

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#31726]
## Description 
Depending on the computer resolution or where the window is placed, the `Contact technical support` form can be cut off, hiding the `Submit` button.

Based on real screenshot below, resolution may be 1024 x 768

## Steps to Reproduce

   1. Have a smaller resolution
   2. Have VPN purchased
   3. VPN button > Gear icon > Contact technical support

## Actual result:
![image](https://github.com/brave/brave-browser/assets/4733304/e80b7eae-2c41-459c-ab83-e7571731b545)

## Expected result:
Submit button should be visible / clickable

**Comment by Bahubaliak** [comment]
Can you please assign this issue to me, I would like to contribute to this issue.
Thanks!

**Comment by bsclifton** [comment]
@Bahubaliak sure - you're welcome to grab it 😄
