### ISSUE TITLE
Add Media Queries to the Edit Account modal for Wallet Panel V2

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#31721]
## Description 

We need to add `Media Queries` to the `Edit Account` modal to look good in the `Wallet Panel`

![Screenshot 1](https://github.com/brave/brave-browser/assets/40611140/28aacfc5-a0ea-4d18-8724-8b75a6680791)

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Linux

- Verified steps from [brave/brave-core#19388](https://github.com/brave/brave-core/pull/19388)
- Verified Edit account modal is shown correctly in Wallet Panel V2
![Edit](https://github.com/brave/brave-browser/assets/17010094/8c5a6958-9b54-4778-99d3-0ac59a1cd37d)


---------------------

**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#19388](https://github.com/brave/brave-core/pull/19388)
- Verified Edit account modal is shown correctly in Wallet Panel V2
![brave_qzMlocJo3n](https://github.com/brave/brave-browser/assets/17010094/8b305a5c-4965-4d15-9a02-0c0d7808353c)

---------------------

**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (arm64)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | macOS Version 13.4.1 (c) (Build 22F770820d)

- Verified steps from [brave/brave-core#19388](https://github.com/brave/brave-core/pull/19388)
- Verified Edit account modal is shown correctly in Wallet Panel V2
![image](https://github.com/brave/brave-browser/assets/17010094/be4d750a-72b7-4451-94ee-9b0d78802002)
