### ISSUE TITLE
All information typed when submitting a VPN support request is lost when clicking outside panel

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#31728]
## Description 
VPN customers can open a support ticket. On Desktop, they're presented with a form asking for more information about the problem experienced and their email address.

If folks click OUTSIDE of the panel for any reason the panel will get dismissed. This causes the loss of all information which was input / submitted which is a bad customer experience.

## Steps to Reproduce

   1. Have VPN purchased
   2. Click `VPN` button (next to hamburger menu)
   3. Click the gear in the top right of the VPN panel
   4. Click `Contact technical support` in VPN panel
   5. Start to fill out the form
   6. Click outside of the panel

## Actual result:
Support form is closed. If re-opened, the state is lost
![ticket](https://github.com/brave/brave-browser/assets/4733304/b2105d62-745b-4a23-9310-d5cb34a0a671)

## Expected result:
A few ways we can handle this:
- Present the support form outside of the VPN panel (ex: have a new modal)
- Don't lose the state. It's annoying it closes, but when you open it again it's currently losing all the info you typed in
- Can we force it to stay open?

**Comment by Bahubaliak** [comment]
If anyone not working on this issue please assign this to me, I can work on this.
Thanks!
