### ISSUE TITLE
Crash when launching browser

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#31732]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.58.26 Chromium: 115.0.5790.90
Operating System: Android 13

URL (if applicable) where crash occurred:
Performed search on Brave search

Can you reproduce this crash?
Happened 3 times

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Perform search via url bar (Brave search as default)
2. Browser crashes after search result loads
3. Relaunch crashes again

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/a4660a00-e8f6-640a-0000-000000000000
Crash ID: crash/a2660a00-e8f6-640a-0000-000000000000
Crash ID: crash/a0660a00-e8f6-640a-0000-000000000000

cc: @iefremov

**Comment by iefremov** [comment]
@srirambv i guess this is stale, pls reopen if needed
