### ISSUE TITLE
perf: allow extracting multiple IPFS URLs via braveWalletIpfsService 

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#31739]
## Description 

To reduce the number of mojom call made by the front-ends, we should add a function to `BraveWalletIpfsService` that is similar to `extractIPFSUrlFromGatewayLikeUrl`, but allows a list URLS to be passed-in as an argument.

**Comment by vadimstruts** [comment]
The IPFS local node and scheme has been [deprecated](https://github.com/brave/brave-browser/issues/37735)
