### ISSUE TITLE
Update banner type omnibox search promotion UI

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#31746]

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.58.90 Chromium: 116.0.5845.96 (Official Build) beta (64-bit)
-- | --
Revision | c112ad8c854bd34b48f4e87bfb3f7951e426a1d4
OS | Windows 11 Version 22H2 (Build 22621.2134)
```

Steps:

1. Install 1.58.90
2. launched Brave with `--variations-server-url=https://variations.bravesoftware.com/seed`
3. opened brave://version and verified `BraveSearchPromotionBannerStudy` is not shown
4. closed Brave and relaunched with the griffin again `--variations-server-url=https://variations.bravesoftware.com/seed`
5. opened brave://settings/search in a new tab
6. set `Google` as a default search engine
7. open a new tab and type any keywords (eg. Brave)
8.  confirmed promotion banner is shown as a last omnibox entry
9.  clicked `Maybe later` on the banner
10. confirmed the banner is dismissed
11. retyped keyword `Brave` in the URL bar 
12. confirmed banner no longer dismissed 
13. closed Brave 
14.  open Preferences file in the profile (`C:\Users\...\AppData\Local\BraveSoftware\Brave-Browser-Beta\User Data\Default`)
      and checked `maybe_later_clicked_time` 
15. manually change system time to pass 3 days (8/16/2023 - 8/20/2023)
16. relaunch Brave again with `--variations-server-url=https://variations.bravesoftware.com/seed`
17. type keyword `brave` again in the URL bar

### Confirmed promotion banner is shown till 3 days passed 

step 2 | step 3| step 4 | step 5 | step 6 | step 8 | step 12 | step 14 | step 15 | step 17
--------- | -------- | --------- | -------- | -------- | ----- | ----- | ------ | ------ | -------
<img width="554" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/99b45771-7a1f-4ba3-9a99-58096990886c">|<img width="634" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/6b74a0c4-07d7-48d5-90df-a074b812af50">|<img width="646" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/fc62f9f4-762e-40d1-9b2f-a0d5848e9fd8">|<img width="642" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/1dd112f3-7f7e-4815-9198-3e7a305e0e87">|<img width="647" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/9cfa7fdd-0edc-4844-930b-527d1ccd9403">|<img width="948" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/01c7379b-3dbf-4356-96d6-f9296201a1d2">|<img width="952" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/790fc7f8-7665-4642-9563-52a973398e2a">|<img width="698" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/465c0572-2f3d-43cb-a6b1-e4ce7dc4a03f">|<img width="534" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/09e00c7e-d44c-4bf6-815a-318e476a8fa5">|<img width="956" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/b346d016-59c8-4974-99c5-4ea07c4be286">

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.58.91 Chromium: 116.0.5845.96 (Official Build) beta (x86_64)
-- | --
Revision | 620fa9c0307b294dd6e7c6b0976bc1f93fecf369
OS | macOS Version 11.7.9 (Build 20G1426)




Steps:

### Case 1:  3 Days Passed to show the promotion banner again if `Maybe Later` is clicked
<details> 

1. Install 1.58.90
2. launched Brave with `--variations-server-url=https://variations.bravesoftware.com/seed`
3. opened `brave://version` and verified `BraveSearchPromotionBannerStudy` is not shown
4. closed Brave and relaunched with `--variations-server-url=https://variations.bravesoftware.com/seed`
5. opened `brave://version` and confirmed `BraveSearchPromotionBannerStudy:banner_type_A` is shown
6. opened `brave://settings/search` in a new tab
7. set `Google` as a default search engine
8. open a new tab and type any keywords (eg. Brave)
9.  confirmed promotion banner is shown as a last omnibox entry
10.  clicked `Maybe later` on the banner
11. confirmed the banner is dismissed
12. retyped keyword `Brave` in the URL bar 
13. confirmed banner no longer shown
14. closed Brave 
15. opened `Preferences` file in the profile folder and checked `maybe_later_clicked_time` ( Didn't modify this field)
16. advance system date to 8/20/2023 to pass 3 days for the banner to show again (8/16/2023 - 8/19/2023)
17. relaunched Brave again with `--variations-server-url=https://variations.bravesoftware.com/seed`
18. typed keyword `brave` in the URL bar

### Confirmed promotion banner is shown after 3 days passed 

step 2 | step 3| step 5 | step 6 | step 7 | step 9 | step 11 | step 15 | step 16 | step 18
--------- | -------- | --------- | -------- | -------- | ----- | ----- | ------ | ------ | -------


</details> 

### Case 2: If 3 days NOT passed, promotion banner not shown when `Maybe Later` is clicked
<details> 

1. new profile
2. launched Brave with `--variations-server-url=https://variations.bravesoftware.com/seed`
3. opened `brave://version` and verified `BraveSearchPromotionBannerStudy` is not shown
4. closed Brave and relaunched with `--variations-server-url=https://variations.bravesoftware.com/seed`
5. opened `brave://version` and confirmed `BraveSearchPromotionBannerStudy:banner_type_B` is shown
6. opened `brave://settings/search` in a new tab
7. set `Google` as a default search engine
8. open a new tab and type any keywords (eg. Purina)_
9. confirmed promotion banner is shown as a last omnibox entry
10.  clicked `Maybe later` on the banner
11. confirmed the banner is dismissed
12. retyped keyword `Purina` in the URL bar 
13. confirmed banner no longer shown
14. closed Brave 
15. opened `Preferences` file in the profile folder and checked `maybe_later_clicked_time` ( Didn't modify this field)
16. advance system date to 8/19/2023 to pass 2 days for the banner to show again (8/17/2023 - 8/19/2023)
17. relaunched Brave again with `--variations-server-url=https://variations.bravesoftware.com/seed`
18. typed keyword `Purina` in the URL bar

### Confirmed promo banner is not shown within two days 

step 5 | step 7 | step 9 | step 11 | step 15 | step 16 | step 18
------ | ----- | ------ | ------ | ---- | ---- | -----


</details> 

### Case 3:  UI 
<details>

### **_BraveSearchPromotionBannerStudy:banner_type_A_**

Dark theme | Light theme
---- | -----


### **_BraveSearchPromotionBannerStudy:banner_type_B_**

Dark theme | Light theme
---- | -----


### **_BraveSearchPromotionBannerStudy:banner_type_C_**

Dark theme | Light theme
---- | -----


### **_BraveSearchPromotionBannerStudy:banner_type_D_** 

Dark theme | Light theme
---- | -----

</details>

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave	1.58.98 Chromium: 116.0.5845.96 (Official Build) beta (64-bit) 
Revision	71ede8911313dd18e7355402a3878f568944c568
OS	Linux
```

## Case 1: 3 days passed to show the promotion banner again if `Maybe Later` is clicked

## Case 2: if 3 days have NOT passed, promotion banner isn't shown when `Maybe Later` is clicked

## Case 3: UI
