### ISSUE TITLE
Crash: "Immersive fullscreen toolbar" flag causes Brave to crash

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#31744]
## Description 

Enabling the `#enable-immersive-fullscreen-toolbar` flag in Brave causes the browser to crash unexpectedly for many users. Note that users report the feature working as expected in Chrome. I also cannot reproduce the crash in Chrome. More users are turning to this feature flag in order to hide address bar/tabs/toolbar from persisting on screen when in fullscreen mode. Might be worth trying to fix.

Will add crash reports to this issue as I receive them.

## Steps to Reproduce

   1. Go to `brave://flags`
   2. Set `#enable-immersive-fullscreen-toolbar` flag value to `Enabled`
   3. Watch the browser crash

## Brave version (brave://version info)

v1.52.130

## Version/Channel Information:

- Can you reproduce this issue with the current release? Y
- Can you reproduce this issue with the beta channel? Y
- Can you reproduce this issue with the nightly channel? Y

**Comment by Brave-Matt** [comment]
Crash reports:
```
84bd0100-b231-6e0a-0000-000000000000
d1180000-b231-6e0a-0000-000000000000
974c0700-84d8-360a-0000-000000000000
```

**Comment by iefremov** [comment]
unfortunately we cannot guarantee stable work with upstream flags
