### ISSUE TITLE
Bump `wallets/{rewards-payment-id}` version to `/v4` and sign requests

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#31743]
## Description

Bump to `/v4` and start signing requests with Rewards key.

See: https://github.com/brave-intl/tickets-ledger/issues/131

**Comment by emerick** [comment]
Just noting that the `v4` server endpoint is actually `/v4/wallets/{rewards-payment-id}` with an `s` on the end of `wallets`.

**Comment by LaurenWags** [comment]
@emerick @Miyayes looks like there's a clean profile test plan in https://github.com/brave/brave-core/pull/19540#issue-1833411730, but is there anything that needs to be done for existing users (upgrade case where user is already connected to a custodian)?

**Comment by emerick** [comment]
@LaurenWags We just want to ensure that whenever the `/v4/wallets` endpoint is hit, the request is signed.

**Comment by GeetaSarvadnya** [comment]
Verification **INPRPGRESS** on `Samsung galaxy version 12` running `Bravemonoarm64.apk_1.58.117`
