### ISSUE TITLE
AI Chat page context disclaimer

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#31741]
Whilst we do show when the AI Chat sidebar is Tab-related via the favicon and page title, it could be considered too subtle to let the user know that all page content will be sent to the AI Chat server when any user input is submitted.

(Page content is sent for any user submission on that conversation and not just requests for summaries.)

It could be a short message attached to the favicon and page title:
_"Page content will be sent to Brave Leo along with your messages."_

We could also provide with a button which disconnects the conversation from the page in order to not send the page content, or have a standalone conversation.

This would be disabled after the conversation is started. The conversation would need to be cleared to use this button again. OR the button could remain enabled and could clear the conversation when it is disconnected from the Page.

**Comment by aguscruiz** [comment]
Adding design here, we can massage the copy if needed:
https://www.figma.com/file/h7fKSJF2P556bZWfyLTfwD/Brave-AI?type=design&node-id=1902%3A42546&mode=design&t=Y3VzWeLdAFAxmiLR-1

**Comment by petemill** [comment]
Duplicated by https://github.com/brave/brave-browser/issues/32039
