### ISSUE TITLE
Add detailed view of pending contributions

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#3175]
Add detailed view (like we have see all for AC) for pending contribution. Also add manual removal for contribution

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.67.106 Chromium: 75.0.3770.100 (Official Build) beta(64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/1528
* Verified AC, recurring tips, and one time tips are added to the table and displayed.
* Verified for regular sites, YT channels, Twitch, and Twitter.
* Verified when a site/channel was removed from the list, the sum/total of pending contributions displayed on brave://rewards and from panel was updated accordingly.
![Screen Shot 2019-07-10 at 9 44 34 AM](https://user-images.githubusercontent.com/28145373/60976207-48009700-a2fb-11e9-9f00-be58cd8461a6.png)
![Screen Shot 2019-07-10 at 9 45 07 AM](https://user-images.githubusercontent.com/28145373/60976222-4a62f100-a2fb-11e9-8418-c7327e55d11d.png)
