### ISSUE TITLE
Forget by default ignores shields toggle on subdomains

### ISSUE THREAD

**Issue by goodov** [brave/brave-browser#31755]
FBD is controlled per wildcard domain as: `[*.]a.com`, but shields are controlled per host like `sub.a.com`, `a.com`.

When FBD is enabled, but shields are disabled on subdomain, FDB cleanup is still executed. This is unexpected and incorrect, but turns out there's no clear way to solve this consistently, because we store FBD toggle and Shields toggle differently (`[*.]a.com` vs `sub.a.com`, `a.com`, etc. see https://github.com/brave/brave-browser/issues/29723).

Consider this: 
1. Enable Forget by default globally.
2. Open `sub.a.com`, disable shields, close page, expect 1p storage is not cleared up.
3. Open `a.com`, enable shields, close page, expect 1p storage is cleared up.
4. Open both `www.a.com` and `a.com` in two tabs, close both tabs. What is expected?

Proposed solution: do not cleanup first party storage when a visit to a website with disabled shields was encountered for the active `TLDEphemeralLifetime` instance (that is used by both `sub.a.com` and `a.com`). For the example above: don't perform FDB cleanup when the last tab was closed *no matter what exactly tab was closed last*.

**Comment by pes10k** [comment]
@goodov thats a tricky situation, but I think your approach makes sense as the least awkward option here. Great work!

**Comment by kjozwiak** [comment]
The above requires `1.57.33` or higher for `1.57.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS`


Case 1: Enable `Forget when I close this site` via Per site and open the site in a single tab - PASSED

1. install 1.58.50 
2. launch Brave
3. relaunch Brave to enable griffin study for `BraveForgetFirstPartyStorage` which is visible under `brave://version`
4. verified `Forget me when I close this site` toggle appear and is `Off` in `brave://settings/shields`
5. visited `https://joinhoney.com/` and enabled `Forget me when I close this site toggle` via the Shields panel
6. log into `https://joinhoney.com/`
7. verified joinhoney.com entry in `brave://settings/content/all` and in `local storage data` in `brave://settings/cookies/detail?site=www.joinhoney.com`
8. verified that password entry is shown via `brave://settings/passwords`
9. disable `Shields` in the Shields panel for the site joinhoney.com
10. closed the tab for `joinhoney.com` and wait for ~30s
11. opened `brave://settings/content/all` and confirmed joinhoney.com entry and local storage is `NOT` removed as expected
12. reopened joinhoney.com and confirmed I am not logged out of joinhoney.com and Shields is still disabled
13. re-enable shields on the Shields panel for `joinhoney.com` but leave `Forget me when I close this site` toggle
14. closed https://joinhoney.com/ and wait ~30s
15. confirmed `https://joinhoney.com/` is retained in `brave://settings/content/all` but local storage in `brave://settings/cookies/detail?site=www.joinhoney.com` (which is the expected result)
16. confirmed that passwords are not being removed via `brave://settings/passwords`
17. confirmed that `brave://history` hasn't been removed/cleared

- Confirmed when Forget me when I close this site enabled and disabled Shields, local storage is not removed as expected.
- Confirmed when Forget me when I close this site enabled and enabled Shields, local storage is removed as expected.

step 3 | step 4 | step 5 | step 7a | step 7b | step 8| step 9 | step 11 | step 12  
----- | ------ | ------ | ------ | ------- | ------ | ----- | ----- | ------


step 13 | step 15a | step 15b | step 16 | step 17 
---- | ----- | ------- | ------ | -------


Case 2: Enable `Forget when I close this site` via via global defaults (brave://settings/shields) and open the site in a in two tabs - PASSED

1. new profile 
2. launch Brave
3. relaunch Brave to enable griffin study for `BraveForgetFirstPartyStorage` which is visible under `brave://version`
4. enabled `Forget me when I close this site` toggle in `brave://settings/shields`
5. logged into `https://joinhoney.com/`
6. open joinhoney.com site in another tab
7. verified joinhoney.com entry in `brave://settings/content/all` and in `local storage data` in `brave://settings/cookies/detail?site=www.joinhoney.com`
8. verified that password entry is shown via `brave://settings/passwords`
9. disable `Shields` in the Shields panel for the site joinhoney.com 
10. closed both tabs for `joinhoney.com` and wait for ~30s
11. opened `brave://settings/content/all` and confirmed joinhoney.com entry and local storage is `NOT` removed as expected
12. reopened joinhoney.com in two tabs and confirmed I am not logged out of joinhoney.com and Shields is still disabled
13. confirmed that passwords are not being removed via `brave://settings/passwords`
14. confirmed that `brave://history` hasn't been removed/cleared

- Confirmed when `Forget me when I close this site enabled` and disabled Shields, local storage is not removed as expected.

step 3 | step 4 | step 5 | step 6 | step 7 a | step 7b | step 9a | step 9b | step 11a | step 11b | step 12a | step 12b | step 13 | step 14 
----- | ----- | ----- | ------ | ----- | ----- | ------ | ------ | ------ | ----- | ------ | ----- | ------ | -----
