### ISSUE TITLE
POAPs didn't load successfully on desktop. 

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#31763]
## Description 

I tried to look at the metadata associated with my POAP on the gnosis chain and It failed to load. My address is 0x9Fd5f126bc52F7735F8aEB8a994c5aA9e799a32f if you want to see the POAPs and attached is the vid. I was using 1.58.32

## Steps to Reproduce

   1. 
   2. 
   3. 

## Actual result:

https://github.com/brave/brave-browser/assets/12224304/0c9ea86d-884e-4bca-b0f6-fc29d8bc9cdc

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.59.109 Chromium: 118.0.5993.21 (Official Build) beta (64-bit)
-- | --
Revision | aacb6a6f8bd916bd49f064b2137b007fa6c47b51
OS | Windows 11 Version 22H2 (Build 22621.2283)

- Verified steps from [brave/brave-core#19647](https://github.com/brave/brave-core/pull/19647)
- Verified POAP loads successfully 

https://github.com/brave/brave-browser/assets/17010094/be424d52-c547-4ecf-8df2-c6a898bb6e1b
