### ISSUE TITLE
Unsafe memory write in BraveNetworkDelegateBase

### ISSUE THREAD

**Issue by iefremov** [brave/brave-browser#3176]
## Description 
In `BraveNetworkDelegateBase::GetReferralHeaders()`[1] pointer is written on UI thread, at the some moment it could be read on IO thread. 

[1] https://github.com/brave/brave-core/blob/master/browser/net/brave_network_delegate_base.cc#L86

## Brave version (brave://version info)

Brave | 0.62.0 Chromium: 72.0.3626.71 (Developer Build) (64-bit)
-- | --
Revision | f52ccad2a6a3c65fc9e0c591a517ceab1198dac0-refs/branch-heads/3626@{#763}

### Reproducible on current release:
yes

**Comment by rebron** [comment]
cc: @brave/legacy_qa please see pr for details

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.62.25 Chromium: 73.0.3683.67 (Official Build) beta (64-bit)
-- | --
Revision | a83fd4f3207ae83412d329a9ca1239dd1e068345-refs/branch-heads/3683@{#760}
OS | Windows 7 Service Pack 1 Build 7601.24312

Test plan is based on this comment: https://github.com/brave/brave-core/pull/1531#issuecomment-460650117
Verified `marketwatch.com` and `barrons.com`  got `X-Brave-Partner: dowjones` header
Verified `cheddar.com`  got `X-Brave-Partner: cheddar` header
Verified `coinbase.com`  got `x-brave-partner: coinbase` header

![image](https://user-images.githubusercontent.com/34715963/54249764-b85ffd00-4541-11e9-95e1-89f7cafebe2e.png)
![image](https://user-images.githubusercontent.com/34715963/54249963-44722480-4542-11e9-93ca-97d60c4f92b4.png)
