### ISSUE TITLE
Add Neon EVM preload

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#31760]
https://chainlist.org/chain/245022934

https://docs.neonfoundation.io/

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.59.109 Chromium: 118.0.5993.21 (Official Build) beta (64-bit)
-- | --
Revision | aacb6a6f8bd916bd49f064b2137b007fa6c47b51
OS | Windows 11 Version 22H2 (Build 22621.2283)

- Verified steps from [brave/brave-core#19574](https://github.com/brave/brave-core/pull/19574)
- Verified Neon EVM is added as a pre-loaded network when upgrading to 1.59.x
- Verified Neon EVM is added as a pre-loaded network on new profile 
- Verified adding Neon EVM as a custom network in older profile and upgrading to new one moves it from custom network to pre-loaded network (removes the option to remove network)


<video src=https://github.com/brave/brave-browser/assets/17010094/8a09320f-7728-475d-a47f-8dbc57de826b> | <video src=https://github.com/brave/brave-browser/assets/17010094/a6fbad0b-d23d-42a8-be75-b83e928a07a8>
-- | --
