### ISSUE TITLE
Brave App Icon Color

### ISSUE THREAD

**Issue by chrisliu298** [brave/brave-browser#31771]
Today I redownloaded Brave on macOS and realized that the color of the app icon changed.

After some research I realized that the app icon of Brave was adjusted to align with Apple's guidelines in #14801. However, I couldn't find why the color also changed. So I wonder if this is also intended.

For comparison, see the official icon in [Brave Branding Assets](https://brave.com/brave-branding-assets/) and the current app icon (on macOS) posted below:

![2023-07-21 at 10 02 10@2x](https://github.com/brave/brave-browser/assets/59010212/09f3cc63-1dc6-40a9-99f6-c023926519e0)

**Comment by aguscruiz** [comment]
Hi @chrisliu298! Thanks for noticing and filing the issue. It's an intended color adjustment for the app icons 🙂

**Comment by rebron** [comment]
Closing per last comment.
