### ISSUE TITLE
Monthly Tips not displayed in Rewards Summary when accessed from BAT logo

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#3177]
## Description 
Monthly (recurring) tips are sent out at the same time as the Auto-Contribution. Auto-Contribution is listed in the Rewards Summary when accessed via the BAT logo but Monthly Tips are not listed in this view. You can still see Monthly Tips in the Rewards summary when on brave://rewards page.

## Steps to Reproduce

   1. Launch Brave with `--rewards=staging=true,reconcile-interval=10`
   2. Enable Rewards
   3. Claim staging grant. See this listed in both places on Rewards Summary.
   4. Tip a site that is verified on staging (such as DDG) one time. See this listed in both places on Rewards Summary.
   5. Set up a recurring monthly tip for a site that is verified.
   6. Visit some verified/non verified sites for a-c table.
   7. After 10 minutes a-c happens.
   8. View brave://rewards page and Rewards Summary from BAT logo.

## Actual result:
Monthly Tips not listed on Rewards Summary from BAT logo:
![screen shot 2019-01-31 at 11 23 42 am](https://user-images.githubusercontent.com/28145373/52069240-5a0c2b80-254c-11e9-8c74-2faa7ba5bee5.png)

## Expected result:
Monthly Tips should be listed in Rewards Summary like it is on brave://rewards page:
![screen shot 2019-01-31 at 11 23 53 am](https://user-images.githubusercontent.com/28145373/52069268-642e2a00-254c-11e9-8227-e0352d5a6a28.png)

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.59.33 Chromium: 72.0.3626.81 (Official Build) (64-bit)
-- | --
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
This also reproduces in currently released version

Brave | 0.58.21 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Mac OS X

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.62.17 Chromium: 73.0.3683.39 (Official Build) dev (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

Used test plan from https://github.com/brave/brave-core/pull/1721

![image](https://user-images.githubusercontent.com/34715963/53857092-39187980-3fd5-11e9-98fe-25376cdca3f7.png)
