### ISSUE TITLE
[Shortcuts]: Keyboard shortcuts are broken for non US layouts

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#31770]
We have a report of Keyboard Shortcuts not working in the Czech keyboard layout in 1.56.

Report:
https://community.brave.com/t/keyboard-shortcuts-suddenly-broken/497495/5

I'm hoping that this only affects macOS.

**Comment by stephendonner** [comment]
I took a quick look at this and cant seem to reproduce the issue as filed

<img width="780" alt="Screen Shot 2023-07-20 at 5 09 37 PM" src="https://github.com/brave/brave-browser/assets/387249/3edbdcfa-db29-4703-aca2-3b10f440b097"> 
<img width="1312" alt="Screen Shot 2023-07-20 at 5 14 01 PM" src="https://github.com/brave/brave-browser/assets/387249/d94f84d3-8919-4fb3-b6ba-ff2d46138673">
<img width="1312" alt="Screen Shot 2023-07-20 at 5 19 19 PM" src="https://github.com/brave/brave-browser/assets/387249/aed2c477-a57c-40a8-9966-722afd3ff960">
<img width="1312" alt="Screen Shot 2023-07-20 at 5 19 48 PM" src="https://github.com/brave/brave-browser/assets/387249/dc120a6c-8ca8-4acf-b629-806eca425bbc">

**Comment by fallaciousreasoning** [comment]
Hmm interesting - that's what I would expect too.  Is it the same results with the other Czech keyboard layouts? I tried a few on Linux and they all seemed to work okay.

**Comment by fallaciousreasoning** [comment]
Interesting - I also tried changing the language to Czech, and it didn't seem to have any effect either. I guess we'll need some more info to try and reproduce.

**Comment by sangwoo108** [comment]
Luckily, I can reproduce it on my machine. =ventura. Just saying, now I dunno how to type parenthesis in this keyboard layout 😂

**Comment by fallaciousreasoning** [comment]
Thanks @sangwoo108 - I wonder what's different on your machine than mine and @stephendonner's?

**Comment by sangwoo108** [comment]
Well, maybe mac os version? Mine is `ventura 13.4.1 (c) (22F770820d)`

**Comment by fallaciousreasoning** [comment]
That could be it - mine is Catalina 10.15.7, so a wee bit older :laughing:

**Comment by sangwoo108** [comment]
Looks like our parsing logic to get Mac keycode is broken when the mapped character is unicode. We seem to gete keycode considering keyboard layout.

**Comment by sangwoo108** [comment]
I'm not sure but maybe OS updates how they represets the dead key. I'm wondering what you see when you click 'view' menu on the app menu.

<img width="335" alt="image" src="https://github.com/brave/brave-browser/assets/5474642/217b7461-1065-4290-8da1-931f1993ea4c">

This is mine, and as you can see '=' is represetned as '%'. Actually with Czech-qwerty layout, the = key is a "dead key" which must be used with a followed character to build an accent character. So if your version represets '=' as '=' then everything will be fine but in my case, % can't be parsed well, so I'm not sure what we can do with this. Maybe we should add daed keys to unmodifiable shortcuts. But still trying to find a way.

FYI, our web ui shows 'DEAD' when type = with Czech-qwerty layout
<img width="475" alt="image" src="https://github.com/brave/brave-browser/assets/5474642/c4dede93-e6ee-422a-a14e-0e4187187fb9">

---

As for the IDC_BACK case, I think we can make it work.

**Before**
<img width="667" alt="image" src="https://github.com/brave/brave-browser/assets/5474642/ffa32861-6aaf-4776-8bee-7facf77c5415">

**After**
<img width="796" alt="image" src="https://github.com/brave/brave-browser/assets/5474642/6dd853fc-e6ab-4c71-b2c8-33490853a907">

**Comment by fallaciousreasoning** [comment]
I've just been having a look at how we parse the `keyEquivalent` to a `ui::KeyboardCode`. I'm wondering if we can use `ui/events/keycodes/dom/dom_keyboard_layout_map_mac.mm` to get the original keycode:

```cpp

auto dom_key = ui::DomKey::FromCharacter(keyEquivalent);

// somehow get the correct ui::DomCode for this key string

```

alternatively, I was reading the docs for `NSMenuItem` - it looks like there's a flag to disable automatic keycode localization. I wonder if setting that would solve this?

https://developer.apple.com/documentation/appkit/nsmenuitem/3787554-allowsautomatickeyequivalentloca

**Comment by sangwoo108** [comment]
> https://developer.apple.com/documentation/appkit/nsmenuitem/3787554-allowsautomatickeyequivalentloca (macOS 12+, which is probably why I didn't see it in 10.57)

That's super brilliant! Let me try that

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.58.105 Chromium: 116.0.5845.114 (Official Build) beta (x86_64)
-- | --
Revision | 5a895596bcd7fcd930dab0714ea5cfa86c5aa0a7
OS | macOS Version 11.7.9 (Build 20G1426)
```


## Big Sur

## Sonoma

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave	1.58.105 Chromium: 116.0.5845.114 (Official Build) beta (arm64) 
Revision	5a895596bcd7fcd930dab0714ea5cfa86c5aa0a7
OS	macOS Version 13.5 (Build 22G74)
```

## Ventura (macOS `13.5`)
<details>

</details>
