### ISSUE TITLE
Portfolio Change amount doesn't match portfolio change %

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#31778]
## Description 

When i load the wallet on 1.58.32, sometimes the amount of the portfolio change doesn't match the % portfolio change amount. This is fixed when i refresh it. 
Examples in screenshot, before refresh and after refresh 

## Steps to Reproduce

   1. 
   2. 
   3. 

## Actual result:

<img width="848" alt="Screenshot 2023-07-21 at 15 13 11" src="https://github.com/brave/brave-browser/assets/12224304/dacdccef-f31d-41b9-8fa2-56444fee6012">

## Expected result:
<img width="931" alt="Screenshot 2023-07-21 at 15 13 32" src="https://github.com/brave/brave-browser/assets/12224304/17a0560e-cec6-447d-b721-290074a2c81a">

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.58.109 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | a4ad1fcdb550daf076384dbb280ae944274b3d35
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#19337](https://github.com/brave/brave-core/pull/19337)
- Verified able to load token balances in Portfolio
- Verified able to load token prices in Portfolio
- Verified able to load pricing history (graph) in Portfolio
- Verified able to load fiat balances in Accounts
- Verified able to load token balances in Swap
- Verified on both panel V2 and Wallet page

https://github.com/brave/brave-browser/assets/17010094/e75f06e0-5541-4d9b-b086-65274c736942
