### ISSUE TITLE
[Leo]: Icon overriding strategy

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#31772]
Currently, each Polymer page which wants to override the settings icons needs to do so separately, and bespokely. This isn't ideal because it means that when you update an icon in one place, it's easy to miss it elsewhere.

We should consolidate our strategy for overriding Leo icons, and make it as easy as possible. This will prevent issues like https://github.com/brave/brave-browser/issues/31600

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.59.100 Chromium: 117.0.5938.92 (Official Build) beta (x86_64)
-- | --
Revision | 3243fffc43431ab8677e8139859670b4cd2df843
OS | macOS Version 14.0 (Build 23A344)
```

## _`Dark`_ mode

`brave://settings` | `brave://settings/privacy` | `brave://settings/content`
------------------|---------------------------|--------------------------
<img width="1157" alt="Screenshot 2023-09-26 at 7 10 22 PM" src="https://github.com/brave/brave-browser/assets/387249/d2514a8b-d7ec-4975-b2e5-b69e25b36158"> | <img width="1157" alt="Screenshot 2023-09-26 at 7 13 28 PM" src="https://github.com/brave/brave-browser/assets/387249/54f06425-8e3f-45db-9cc6-d9d64b864f84"> | <img width="1157" alt="Screenshot 2023-09-26 at 7 14 03 PM" src="https://github.com/brave/brave-browser/assets/387249/f1da8f4c-3602-4a90-80c0-8572eadbaaf4">

## _`Light`_ mode

`brave://settings` | `brave://settings/privacy` | `brave://settings/content`
------------------|---------------------------|--------------------------
