### ISSUE TITLE
Portfolio value shows 0.00% change while price history is being loaded

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#31776]
The portfolio fiat value and percentage change shows `+$0.00` and `0.00%` respectively, while the price history is being computed, which can take a while for fat wallets. Show a skeleton instead. This is probably hard to fix without migrating balances and price history to RTK slices.

<img width="272" src="https://github.com/brave/brave-browser/assets/3684187/b0b12db2-1891-4e6a-9b88-54366d31a350">

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.58.109 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | a4ad1fcdb550daf076384dbb280ae944274b3d35
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#19337](https://github.com/brave/brave-core/pull/19337)
- Verified able to load token balances in Portfolio
- Verified able to load token prices in Portfolio
- Verified able to load pricing history (graph) in Portfolio
- Verified able to load fiat balances in Accounts
- Verified able to load token balances in Swap
- Verified on both panel V2 and Wallet page

https://github.com/brave/brave-browser/assets/17010094/e75f06e0-5541-4d9b-b086-65274c736942
