### ISSUE TITLE
Portfolio momentarily shows wrong balance before showing the right one

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#31781]
Reported by @HEagle18 on Slack:

> On nightly, it always give a false balance first and then figures itself out and gets the real balance .. slightly worries me because the lag could continue to grow and I wonder should we wait until we have the right balance ??

https://github.com/brave/brave-browser/assets/3684187/7447231e-32fe-43ec-85fa-80652bc30174

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.58.109 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | a4ad1fcdb550daf076384dbb280ae944274b3d35
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#19337](https://github.com/brave/brave-core/pull/19337)
- Verified able to load token balances in Portfolio
- Verified able to load token prices in Portfolio
- Verified able to load pricing history (graph) in Portfolio
- Verified able to load fiat balances in Accounts
- Verified able to load token balances in Swap
- Verified on both panel V2 and Wallet page

https://github.com/brave/brave-browser/assets/17010094/e75f06e0-5541-4d9b-b086-65274c736942
