### ISSUE TITLE
Change table remove icons from X to trash in Rewards

### ISSUE THREAD

**Issue by rossmoody** [brave/brave-browser#3178]
After discussion with @jenn-rhim and @NejcZdovc and @srirambv, we're gonna switch up the table row icons from a X to a trash can for continuity and to distance from the "close" feeling. 
![image](https://user-images.githubusercontent.com/29072694/52074229-4659c880-253e-11e9-8d98-2b70235a26fe.png)

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.62.8 Chromium: 73.0.3683.39 (Official Build) dev (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

![image](https://user-images.githubusercontent.com/34715963/53537209-79758480-3b09-11e9-8c56-1769f081f0ba.png)
![image](https://user-images.githubusercontent.com/34715963/53537218-81cdbf80-3b09-11e9-9787-b85dfd80c6ca.png)
