### ISSUE TITLE
VAPID protocol not supported

### ISSUE THREAD

**Issue by ggirard07** [brave/brave-browser#31793]
## Description 
Got the following error when trying to enable push notifications on [Elk Mastodon client](https://elk.zone/):
> Your browser supports Web Push Notifications, but does not seem to implement the VAPID protocol.

## Steps to Reproduce

   1. Ensure you are properly logged in on Elk
   2. Go to https://elk.zone/notifications
   3. Click "Enable push notifications"
   4. In authorization pop-up, select "forever" for "Remember my decision" then "Allow"

## Actual result:
Elk provides the followink error:
```
Could not subscribe to push notifications
Your browser supports Web Push Notifications, but does not seem to implement the VAPID protocol.
You can consult a list of frequently asked questions to try to solve the problem: https://docs.elk.zone/pwa#faq.
[Elk's repository in GitHub](https://github.com/elk-zone/elk)
```

## Expected result:
Push notifications are enabled properly

## Reproduces how often: 
Easily reproduced

## Desktop Brave version:
1.52.130 Chromium: 114.0.5735.198 (Official Build) (64-bit) 

## Version/Channel Information:
Tested only on Stable channel

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? Already disabled
- Is the issue reproducible on the latest version of Chrome? I do not use Chrome, but [according to Elk documentation, this is supported by Chrome](https://docs.elk.zone/pwa#your-browser-supports-web-push-notifications-but-does-not-seem-to-implement-the-vapid-protocol)

## Miscellaneous Information:

Not sure what else to add except that I do not even know what VAPID is 😅

**Comment by kernoeb** [comment]
Hi ! Just got the same issue, it looks like you have to allow Google push notifications in security settings

**Comment by ggirard07** [comment]
@kernoeb thanks! I did search for "vapid" in settings... I should have done it with "push" instead!

Can I close this or you want to keep it around to perhaps improve user experience related to "VAPID" protocol error?

**Comment by kernoeb** [comment]
Actually, I think we can also improve Elk documentation to help Brave users 👍 
You can close the issue, it may help some people too

**Comment by kernoeb** [comment]
And here it is : https://github.com/elk-zone/elk/pull/2260/files
