### ISSUE TITLE
No Android apks in latest stable releases

### ISSUE THREAD

**Issue by AaronChen0** [brave/brave-browser#31797]
Hi. I regularly install brave browser from github releases instead of google play. But I notice in the recent stable releases, there's no android apks. Is this on purpose or a mistake?

https://github.com/brave/brave-browser/releases/tag/v1.56.11

**Comment by deeppandya** [comment]
@AaronChen0 Thank you for reporting the issue. we had an issue in the past and it should be fixed with latest releases. can you try the latest release ?
