### ISSUE TITLE
Account selection in deposit screen not working

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#31792]
## Description 

Clicking an account in the account selection screen during the deposit funds flow does not select the account and does not close the selection screen

## Steps to Reproduce

   1. create more than one EVM, FIL or SOL account
   2. Go to deposit screen
   3. select a token
   4. try to change the deposit address

## Actual result:

address cannot be changed

## Expected result:
address can be changed

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

Needs uplift to beta

**Comment by kjozwiak** [comment]
The above requires `1.57.26` or higher for `1.57.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.57.33 Chromium: 115.0.5790.114 (Official Build) beta (64-bit)
-- | --
Revision | 86b4ea1d70ce73c4468d84cc8277f1f9de14b8bc
OS | Windows 11 Version 22H2 (Build 22621.1992)

- Verified steps from issue description
- Verified able to select account address on deposit screen
- Encountered [#31880](https://github.com/brave/brave-browser/issues/31880)

https://github.com/brave/brave-browser/assets/17010094/318b933c-c002-42f7-892d-083219eaadf1
