### ISSUE TITLE
macOS: Keyboard shortcut to switch windows now opens settings

### ISSUE THREAD

**Issue by vollkorntomate** [brave/brave-browser#31799]
## Description 
Since the last (or second last) update (1.56.11), I can't use macOS's default system keyboard shortcut to switch between multiple windows anymore.
Usually, when there are multiple windows of the same app open on the same space/virtual desktop (e.g., two separate windows of Brave), pressing `Cmd`+`<` (with the German keyboard layout) would switch between the windows.
In one of the last updates, this keyboard shortcut has supposedly been overwritten and now opens Brave's settings. The default shortcut to access the settings (`Cmd`+`,`) still works, so there are now two ways to open the settings, but no way to switch between windows.

## Brave version (brave://version info)
1.56.11 Chromium: 115.0.5790.102 (arm64)
macOS Version 13.4.1 (c) (Build 22F770820d)

## Miscellaneous Information:
I have the German keyboard layout and thus, some shortcuts may work differently than on other keyboards. I haven't tested it with any other layout.

**Comment by floze** [comment]
see #31758

**Comment by vollkorntomate** [comment]
> see #31758

Ah, I didn't see that one. Thanks!
