### ISSUE TITLE
Earnings from ads shows `0.00 BAT` instead of link to custodian when in Logged Out state

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#31791]
## Description

STR:

1. Connect to custodian
2. Enter Logged Out state
3. Check Rewards statement
4. Note "Ad earnings" is 0.00 BAT instead of a link to the custodian page 

![image](https://github.com/brave/brave-browser/assets/11497541/d8b620c4-6e57-4abe-8691-376fef407d24)

Brave | 1.56.9 Chromium: 115.0.5790.98 (Official Build) (x86_64)
-- | --
Revision | 4eacc220b55f07c57d5a1f4b7e0e63a6f7e420a1-refs/branch-heads/5790_90@{#4}

Also reproduces on:

Brave | 1.58.37 Chromium: 115.0.5790.98 (Official Build) nightly (x86_64)
-- | --
Revision | 595f87fc43e76e1f0bf0158ad518c50afb342437

**Comment by emerick** [comment]
@Miyayes Do we have any mockups or other guidance on what this link should look like and say?

**Comment by Miyayes** [comment]
@emerick Let's just make it same as in the non-logged out case. It'll send the user to the custodian's website and they can log in there. It won't necessarily re-auth in Rewards, but this is technically separate from the OAuth and only about viewing the deposit history inside the custodian dashboard.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.59.86 Chromium: 117.0.5938.62 (Official Build) beta (x86_64)
-- | --
Revision | 3c4c1c3b2eef0fcbe8485c67e1df504942deadca
OS | macOS Version 13.5.2 (Build 22G91)
```
