### ISSUE TITLE
Sort accounts in portfolio asset view

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#31798]
The accounts in portfolio asset view are no longer sorted in decreasing order of fiat value, since merging https://github.com/brave/brave-core/pull/19337.

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.58.109 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Linux

- Verified steps from issue description
- Verified able to sort portfolio by accounts
- Verified able to sort portfolio by descending order of Fiat value

https://github.com/brave/brave-browser/assets/17010094/1e75f5c2-6abc-431b-9615-5c85792d3b58



---------------------

**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build)) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from issue description
- Verified able to sort portfolio by accounts
- Verified able to sort portfolio by descending order of Fiat value

https://github.com/brave/brave-browser/assets/17010094/efa6983c-58ae-4423-9a61-81ff30f02632


---------------------

**Verification passed on**

Brave | 1.57.27 Chromium: 115.0.5790.114 (Official Build) beta (arm64)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | macOS Version 13.4.1 (c) (Build 22F770820d)

- Verified steps from issue description
- Verified able to sort portfolio by accounts
- Verified able to sort portfolio by descending order of Fiat value

https://github.com/brave/brave-browser/assets/17010094/ac19a427-9701-4623-8271-ed35fdc6ebcf
