### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by dmbortz** [brave/brave-browser#31800]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.43.89  Chromium: 105.0.5195.102
Operating System: Linux 6.2.0-25-generic

URL (if applicable) where crash occurred:

Can you reproduce this crash?

*** I've sent several of these reports. And, yes, I can reproduce it simply by opening brave. Even with a blank window open, after a minute or two, brave crashed.

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. It's crashed with just a blank window with just one tab
2. It's crashed when I had 5 tabs open and was using several google services.
3. It's crashed when I had 20+ tabs open doing work on sites like researchgate.com and arxiv.org

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/ecbb0400-b231-6e0a-0000-000000000000

**Comment by atuchin-m** [comment]
@dmbortz 
According to the backtrace info, it's an super old issue that is fixed now.
The 1.43.89 is released about a year ago, just update the browser.
