### ISSUE TITLE
`Request-OTR` should work with `<meta http-equiv>` tags

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#31804]
# STR:

- load the following HTML page on a localhost server
    ```html
    <!doctype html>
    <html>
      <head>
        <meta http-equiv="Request-OTR" content="1" />
      </head>
      <body>
        <p>Request-OTR demo</p>
      </body>
    </html>
    ```
- it should show the Request-OTR interstitial

**Comment by ShivanKaul** [comment]
> This probably wont be possible, since we'll have already processed any Set-Cookie and similar instructions before we hit the meta-tag

Yeah, that's what we figured as well. [This is where](https://source.chromium.org/chromium/chromium/src/+/refs/heads/main:third_party/blink/renderer/core/loader/http_equiv.cc;l=31;drc=a742c65cc620d2b7b262b5514540ebdb510a7121) the http equiv processing happens in Chromium, fwiw. 

I think we can close this.
