### ISSUE TITLE
`:remove()` actions stripped from filters

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#31805]
In Nightly, `:remove`, `:remove-attr`, and `:remove-class` filters are treated as if the action part of the rule was not present (i.e. the filter becomes a hide rule). This can lead to big webcompat issues, since those actions are generally specified when "just hiding" the elements is _not_ sufficient. This regression was introduced in https://github.com/brave/adblock-rust/commit/de8f6eb77b386b691be67636fca9a89bba500e8d.

**Comment by antonok-edm** [comment]
Labeled as `release-notes/exclude` since the change would not be visible to users in Beta or Release (it's fixing a regression within 1.58.x). Feel free to change that if I've misinterpreted the intent of the release notes though!

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.58.80 Chromium: 116.0.5845.51 (Official Build) nightly (x86_64)
-- | --
Revision | 4408cc9795df260c5d5f033660ce757782b53b32
OS | macOS Version 11.7.9 (Build 20G1426)

Followed the steps to reproduce from https://github.com/brave/brave-core/pull/19400#issue-1816885301

### Steps:
1. installed 11.58.80`
2. launched Brave
3. added `example.com##h1:remove()` under `Create Custom Filters` on `brave://settings/shields/filters`
4. clicked `Save`
5. loaded `example.com`
6. opened the Developer Tools console
7. pasted the snippet from the test plan

### Confirmed the testcase shows `Success`

`brave://settings/shields/filters` | `example.com`
--------------------------------|----------------
<img width="1714" alt="Screen Shot 2023-08-08 at 12 24 41 PM" src="https://github.com/brave/brave-browser/assets/387249/84a98f79-f8c9-493c-a450-fa5be99e7a0b"> | <img width="1714" alt="Screen Shot 2023-08-08 at 12 21 50 PM" src="https://github.com/brave/brave-browser/assets/387249/d8f3ce6d-4cd1-4511-a5b2-496607743f73">

**Comment by Uni-verse** [comment]
In progress on Android ARM
