### ISSUE TITLE
Use Leo controls on the new tab page settings dialog

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#31810]
Currently, the new tab page settings dialog uses a mix of Leo, `brave-ui` and custom controls. We should update it to use Leo controls.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.58.91 Chromium: 116.0.5845.96 (Official Build) beta (x86_64)
-- | --
Revision | 620fa9c0307b294dd6e7c6b0976bc1f93fecf369
OS | macOS Version 11.7.9 (Build 20G1426)

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.58.100 Chromium: 116.0.5845.114 (Official Build) beta (64-bit)
-- | --
Revision | a8c0058265009a1858c4502b9ba413671fbb61e1
OS | Linux
```
