### ISSUE TITLE
Use correct fiat values for test network assets

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#31819]
## Description 

The main-net token's price is being used as the test net token's price.
Most test-net tokens do not have a market to determine their real-world value.
Goerli Ether has a real world price that differs from the ETH on Ethereum mainnet price

## Steps to Reproduce

   1. Create testnet accounts for FIL and Goerli ETH
   2. view the portfolio page

## Actual result:

- Goerli ETH is displayed as having the same price as Mainnet ETH.
- Testnet FIL displayed as having the same price as Mainnet FIL. 

## Expected result:
- The correct Goerli ETH price is displayed (https://www.coingecko.com/en/coins/goerli-eth)
- Testnet FIL price should be $0

## Reproduces how often: 

Easy

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.59.109 Chromium: 118.0.5993.21 (Official Build) beta (64-bit)
-- | --
Revision | aacb6a6f8bd916bd49f064b2137b007fa6c47b51
OS | Windows 11 Version 22H2 (Build 22621.2283)

- Verified steps from issue description
- Verified ETH price on Goerli is correct and not same as Mainnet ETH
- Verified Testnet FIL price is shown as $0

https://github.com/brave/brave-browser/assets/17010094/11f7ee10-c61c-4640-b48f-2c183111274a
