### ISSUE TITLE
Fix "BAT" alignment in Rewards summary panels and font color in dark mode [followup to #30971]

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#31817]
![image](https://github.com/brave/brave-browser/assets/11497541/8a4b1d4d-ae44-4af1-95e6-6873e9d57dd3)

In this screenshot, ignore the black text. Just focus on the alignment issue.

- [ ] "BAT" word / denomination should be properly aligned with surrounding text and numbers

**Comment by Miyayes** [comment]
Followup to https://github.com/brave/brave-browser/issues/30971 cc: @emerick

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.59.86 Chromium: 117.0.5938.62 (Official Build) beta (x86_64)
-- | --
Revision | 3c4c1c3b2eef0fcbe8485c67e1df504942deadca
OS | macOS Version 13.5.2 (Build 22G91)
```
