### ISSUE TITLE
Route Restore to to full page view from Panel

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#31818]
## Description 

For now, we need to open the `Restore` wallet page in the full page view until we have `Restore` wallet mockups for `Panel`

![Screenshot 21](https://github.com/brave/brave-browser/assets/40611140/8f85cce7-e61c-4e69-866d-89903c18505c)

![Screenshot 22](https://github.com/brave/brave-browser/assets/40611140/8dd654a5-3bd4-49a3-9d11-761fdcb73f45)

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.58.109 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | `a4ad1fcdb550daf076384dbb280ae944274b3d35`
OS | Linux

- Verified steps from [brave/brave-core#19405](https://github.com/brave/brave-core/pull/19405)
- Verified clicking restore in panel opens the full page view for restore wallet

https://github.com/brave/brave-browser/assets/17010094/70ebd335-030e-46d6-af58-54fe2ef5719d


---------------------

**Verification passed on**

Brave | 1.57.27 Chromium: 115.0.5790.1314 (Official Build) beta (64-bit)
-- | --
Revision | `a4ad1fcdb550daf076384dbb280ae944274b3d35`
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#19405](https://github.com/brave/brave-core/pull/19405)
- Verified clicking restore in panel opens the full page view for restore wallet

https://github.com/brave/brave-browser/assets/17010094/e0b2267d-642c-4d16-9311-b25d0a54d4c1


---------------------

**Verification passed on**

Brave | 1.57.27 Chromium: 115.0.5790.114 (Official Build) beta (arm64)
-- | --
Revision | `a4ad1fcdb550daf076384dbb280ae944274b3d35`
OS | macOS Version 13.4.1 (c) (Build 22F770820d)

- Verified steps from [brave/brave-core#19405](https://github.com/brave/brave-core/pull/19405)
- Verified clicking restore in panel opens the full page view for restore wallet

https://github.com/brave/brave-browser/assets/17010094/722a1c53-364e-43aa-98b4-6499a9839445
