### ISSUE TITLE
Show test networks in a separate section and show icons

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#31815]
## Description 
Show test networks in a separate section (without any nested hierarchy).

## Actual result
Test networks are being shown under primary networks as nested list

## Expected result
![Screenshot from 2023-07-24 16-41-35](https://github.com/brave/brave-browser/assets/11755381/5a07228b-2fe2-44cc-94e9-479461cf35b8)

**Comment by kjozwiak** [comment]
The above requires `1.57.42` or higher for `1.57.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.57.42 x64 build
- Verified steps from issue description
- Verified test networks are listed under a separate `Test Networks` heading

https://github.com/brave/brave-browser/assets/17010094/a4925bfc-0aad-4ce9-9a4b-a7ec5418081e
