### ISSUE TITLE
Sync chain creator does not get some bookmarks on initial sync

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#3182]
## Steps to Reproduce

bookmarks: [bookmarks.zip](https://github.com/brave/brave-browser/files/2819534/bookmarks.zip)

Note: Windows is the sync chain creator

   1. Clean install on Windows
   2. On Windows: import attached bookmarks: bookmarks_windows.html
   3. Clean install on Linux
4. On Linux: import attached bookmarks: bookmarks_linux.html
5. On Windows: Go to `brave://sync/` and  `Start a new sync chain`
6. On Windows: Click `Computer` and copy sync code
7. On Linux: Go to `brave://sync/` and click `I have a sync code`
8. On Linux: Paste the sync code from 6.

## Actual result:

Partial sync on Windows (sync chain creator)
Bookmarks from Linux are not synced or are synced partially
![image](https://user-images.githubusercontent.com/34715963/52094564-e99ef200-25bf-11e9-9652-da232540cb68.png)

Full sync on Linux.

## Expected result:
Full sync on Windows (sync chain creator)
![image](https://user-images.githubusercontent.com/34715963/52094661-48fd0200-25c0-11e9-9750-6b7922854535.png)

Full sync on Linux.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.59.33 Chromium: 72.0.3626.81 (Official Build) (64-bit)
-- | --
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS | Windows 7 & Linux

The regression was introduced between 0.59.21 and 0.59.25. 

Found by @LaurenWags .

cc @brave/legacy_qa @rebron @AlexeyBarabash @darkdh

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.59.34 Chromium: 72.0.3626.81 (Official Build) (64-bit)
-- | --
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS | Linux

* Verification passed on different profiles on Linux, full bookmarks sync on both profiles
![screenshot from 2019-02-01 13-46-14](https://user-images.githubusercontent.com/17010094/52110791-c4de6500-2627-11e9-92ca-4b5c45fb8776.png)

**Comment by kjozwiak** [comment]
Moving this into https://github.com/brave/brave-browser/milestone/15 as it was resolved by reverting https://github.com/brave/brave-core/pull/1188 and pushed into the `0.59.34` release.
