### ISSUE TITLE
Add Media Queries to Remove Account modal for Wallet Panel V2

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#31827]
## Description 

We need to add `Media Queries` to the `Remove Account` modal to look good in the `Wallet Panel`

![Screenshot 24](https://github.com/brave/brave-browser/assets/40611140/d1171b12-a4a8-4399-99b4-60ed6e68f358)

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Linux

- Verified steps from [brave/brave-core#19408](https://github.com/brave/brave-core/pull/19408)
- Verified `Remove` account modal looks good on V2 panel
![Linux](https://github.com/brave/brave-browser/assets/17010094/ae0b3f1b-7c9e-487e-b049-a9719f9e774d)


---------------------

**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#19408](https://github.com/brave/brave-core/pull/19408)
- Verified `Remove` account modal looks good on V2 panel
![brave_M8mSyOaB0A](https://github.com/brave/brave-browser/assets/17010094/bebd51de-ca30-419e-bac1-415a0cc6371b)

---------------------

**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (arm64)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | macOS Version 13.4.1 (c) (Build 22F770820d)

- Verified steps from [brave/brave-core#19408](https://github.com/brave/brave-core/pull/19408)
- Verified `Remove` account modal looks good on V2 panel
![image](https://github.com/brave/brave-browser/assets/17010094/5ce0aa20-c6b8-47a5-970d-2a5b5ece8cac)
