### ISSUE TITLE
Add Media Queries to Create Account modals for Wallet Panel V2

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#31822]
## Description 

We need to add `Media Queries` to the `Create Account` modals to look good in the `Wallet Panel`

https://github.com/brave/brave-browser/assets/40611140/d00c5f8f-04ea-451f-8b86-b6a815603d68

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Linux

- Verified steps from [brave/brave-core#19406](https://github.com/brave/brave-core/pull/19406)
- Verified create account modals work as expected for Wallet Panel V2
- Encountered [#32748](https://github.com/brave/brave-browser/issues/32748)

https://github.com/brave/brave-browser/assets/17010094/79aa4884-afa0-432e-a8bd-6153a92f1d6f


---------------------

**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#19406](https://github.com/brave/brave-core/pull/19406)
- Verified create account modals work as expected for Wallet Panel V2
- Encountered [#32748](https://github.com/brave/brave-browser/issues/32748)

https://github.com/brave/brave-browser/assets/17010094/9a0c507d-0311-43ea-ac1c-963ebc9c8582

---------------------

**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (arm64)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | macOS Version 13.4.1 (c) (Build 22F770820d)

- Verified steps from [brave/brave-core#19406](https://github.com/brave/brave-core/pull/19406)
- Verified create account modals work as expected for Wallet Panel V2
- Encountered [#32748](https://github.com/brave/brave-browser/issues/32748)

https://github.com/brave/brave-browser/assets/17010094/9708e080-b6e5-4a00-b684-c73a83d51b6e
