### ISSUE TITLE
Download Brave Wallet data files component on demand on Android

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#31824]
Currently `Brave Wallet data files` component is downloaded even if Wallet is not used on Android. This consumes ~4MB of device storage. This component must be downloaded only if Wallet is in use.

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.58.114 x64 Beta build
- Verified steps from [brave/brave-core#19086](https://github.com/brave/brave-core/pull/19086)
- Verified without any network throttle wallet data files are downloaded instantly 
- Verified when network is throttled Wallet data file download is shown on all onboarding screens on a new wallet creation
- Verified when network is throttled Wallet data file download is shown on all onboarding screen when restoring wallet

Create New Wallet

![image](https://github.com/brave/brave-browser/assets/17010094/2176ac69-217c-4752-94f3-6c16d12379ce) | ![image](https://github.com/brave/brave-browser/assets/17010094/4e9627ef-cd1f-4f9e-aae3-f75e2d384975) | ![image](https://github.com/brave/brave-browser/assets/17010094/b3e5bca9-2b70-42a6-b431-dd21c07d113d) | ![image](https://github.com/brave/brave-browser/assets/17010094/ea19ca5d-7ad6-4b51-b825-12c14eb68fc2) | ![image](https://github.com/brave/brave-browser/assets/17010094/67229c08-e640-420f-afe6-ddc448239922)
-- | -- | -- | -- | --

Restore Wallet 

<img width=150 src=https://github.com/brave/brave-browser/assets/17010094/a8c1115d-e52a-4bc5-a4d7-d1ec5ec7982d> | <img width=150 src=https://github.com/brave/brave-browser/assets/17010094/92eeb41a-a259-43a3-83d5-539e21bc3fff>
-- | --
