### ISSUE TITLE
Unable to Import Wallet with JSON file in Panel

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#31835]
## Description 

We are currently unable to `import` a wallet with a `JSON` file in the Wallet `Panel`.

![Screenshot 26](https://github.com/brave/brave-browser/assets/40611140/9b2cf60c-2d66-4dcd-a805-95bc414fae14)

https://github.com/brave/brave-browser/assets/40611140/ba99b7ea-eb93-4b29-8693-df291a960fa6

**Comment by darkdh** [comment]
This is a core issue. When panel is loaded in `WebUIBubbleDialogView`, it can't open up system file selection dialog. However, if we loaded in a page like navigating to brave://wallet-panel.top-chrome directly, it doesn't have this limitation.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.59.112 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | 967f25f295938c64c24e2e6a1790470668757655
OS | Windows 11 Version 22H2 (Build 22621.2283)

- Verified steps from [brave/brave-core#19871](https://github.com/brave/brave-core/pull/19871)
- Verified able to import JSON file in panel
- Verified able to close panel when clicked outside

https://github.com/brave/brave-browser/assets/17010094/0d2ad673-6765-4545-8732-7053029670a9
