### ISSUE TITLE
Replace "ads enabled duration" P3A metric with "ad types enabled"

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#31841]
Replace `Brave.Rewards.AdsEnabledDuration` with `Brave.Rewards.AdTypesEnabled`.

If you have rewards enabled, which ad types do you have enabled?

0. None
1. NTP only
2. Push only
3. NTP + Push

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave | 1.58.90 Chromium: 116.0.5845.96 (Official Build) beta (64-bit)
-- | --
Revision | c112ad8c854bd34b48f4e87bfb3f7951e426a1d4
OS | Windows 10 Version 22H2 (Build 19045.3324)

```

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Vivo X70 Pro version 12` version `Bravemonoarm64.apk_1.58.90`


- Verified the test pan from https://github.com/brave/brave-core/pull/19409

<details>
<summary>Brave.Rewards.AdTypesEnabled = Metrics not shown_PASSED</summary>

1. Clean profile 1.58.x
2. Open brave://local-state file
3. Look for the metrics `Brave.Rewards.AdTypesEnabled`
4. Confirmed that the metrics `Brave.Rewards.AdTypesEnabled` is NOT shown in the local state file

![image](https://github.com/brave/brave-browser/assets/38657976/768e962a-1b23-43a4-9b72-fae05574c832)

</details>

<details>
<summary>Brave.Rewards.AdTypesEnabled = 0_PASSED</summary>

1. Clean profile 1.58.x
2. Enable Rewards
3. Open brave://rewards settings page and ensure that the `New tab page ads` and `Notification ads` switches are enabled by default
4. Turn off both the switches 
5. Open brave://local-state file 
6. Look for the metrics `Brave.Rewards.AdTypesEnabled`
7. Confirmed that the metrics `Brave.Rewards.AdTypesEnabled` response value is `0` `None` as expected as both switches are OFF

Example | Example
----------|---------
![image](https://github.com/brave/brave-browser/assets/38657976/0eedc4ff-3571-48c7-9162-62edde8e6280) | ![image](https://github.com/brave/brave-browser/assets/38657976/221e8eda-6e6e-48dd-bb92-e6a747586781)

</details>

<details>
<summary>Brave.Rewards.AdTypesEnabled = 1_PASSED</summary>

1. Clean profile 1.58.x
2. Enable rewards
3. Open brave://rewards settings page and ensure that the `New tab page ads` and `Notification ads` switches are enabled by default
4. Turn off the `Notification ads` switch
10. Open brave://local-state file
11. Look for the metrics `Brave.Rewards.AdTypesEnabled`
12. Confirmed that the metrics `Brave.Rewards.AdTypesEnabled` response value is `1` `NTP only` as expected

Example | Example
----------|---------
![image](https://github.com/brave/brave-browser/assets/38657976/ebdfadcc-a014-46ba-97a6-befbc5c1fbee) | ![image](https://github.com/brave/brave-browser/assets/38657976/88ea1b96-25ed-4d39-a40d-d62c6c14c7d8)


</details>

<details>
<summary>Brave.Rewards.AdTypesEnabled = 2_PASSED</summary>

1. Clean profile 1.58.x
2. Enable rewards
3. Open brave://rewards settings page and ensure that the `New tab page ads` and `Notification ads` switches are enabled by default
4. Turn off the `New tab page ads` switch
10. Open brave://local-state file
11. Look for the metrics `Brave.Rewards.AdTypesEnabled`
12. Confirmed that the metrics `Brave.Rewards.AdTypesEnabled` response value is `2` `Push only` as expected

Example | Example
----------|---------
![image](https://github.com/brave/brave-browser/assets/38657976/5474629f-94ec-4ce3-b606-3fd99c69f8be) | ![image](https://github.com/brave/brave-browser/assets/38657976/a5e152db-2e6b-4430-9461-fe1abbe189ba)

</details>

<details>
<summary>Brave.Rewards.AdTypesEnabled = 3_PASSED</summary>

1. Clean profile 1.58.x
2. Enable rewards
3. Open brave://rewards settings page and ensure that the `New tab page ads` and `Notification ads` switches are enabled by default
4. Open brave://local-state file
5. Look for the metrics `Brave.Rewards.AdTypesEnabled`
6. Confirmed that the metrics `Brave.Rewards.AdTypesEnabled` response value is `3` `NTP+Push`

Example | Example
----------|---------
![image](https://github.com/brave/brave-browser/assets/38657976/41be4b6c-e86c-435f-b841-bdab4ceba06f) | ![image](https://github.com/brave/brave-browser/assets/38657976/faaced70-4427-468e-88eb-7ade4e907813)

</details>

<details>
<summary>Brave.Rewards.AdTypesEnabled = Reset rewards_PASSED</summary>

1. Clean profile 1.58.x
2. Enable rewards
3. Open brave://rewards settings page and ensure that the `New tab page ads` and `Notification ads` switches are enabled by default
4. Reset the rewards via `Reset` button in brave://rewards settings page
5. Open brave://local-state file
6. Look for the metrics `Brave.Rewards.AdTypesEnabled`
7. Confirmed that the metrics `Brave.Rewards.AdTypesEnabled` is NOT shown in the local state file as expected

Example | Example
----------|---------
![image](https://github.com/brave/brave-browser/assets/38657976/94513eb6-92c2-4df5-b63f-d6f32534572d) | ![image](https://github.com/brave/brave-browser/assets/38657976/20fc338d-4f46-4b6a-84fd-0d2523229912)

</details>

**Comment by GeetaSarvadnya** [comment]
@DJAndries In the `Brave.Rewards.AdTypesEnabled = Reset rewards` case above, when rewards is reset the metrics `Brave.Rewards.AdTypesEnabled` is shown under the `constellation_logs` in Android, but in Desktop once the rewards is reset the metrics `Brave.Rewards.AdTypesEnabled` is NOT shown under brave://local-state file. Is this expected behavior for Android?

**Comment by DJAndries** [comment]
@GeetaSarvadnya Yes, that's fine. As long as the metric disappears from `logs` and `logs_constellation_prep`
