### ISSUE TITLE
Wallet New Connection Panel closes / reopens on Magic Eden

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#31853]
## Description 

When attempting to connect to connect to Magic Eden for the first time, the wallet panel opens and closes repeatedly. Magic Eden appears to continually send new connection requests which get rejecting automatically due to the pending request still being open (rejections visible in console).

## Steps to Reproduce
   1. Clear browsing data for Magic Eden, bug appears to only work when first visiting.
   2. Visit https://magiceden.io/ and click `Connect Wallet`, Select `Brave Wallet`
   3. Observe panel opens and closes repeatedly. If you check the console, you can see more requests being send and rejected due to pending request.
   4. Quit Brave
   5. Re-launch Brave
   6. You should be able to connect as expected now. Clear browsing data & Solana permissions to reproduce again.

## Actual result:

https://github.com/brave/brave-browser/assets/5314553/44effac3-f086-437b-b4af-8e05862a64b4

## Expected result:

Panel does not close until user closes it via cancel / approve / clicking elsewhere.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Version 1.58.46 Chromium: 115.0.5790.136 (Official Build) nightly (arm64)

## Version/Channel Information:

- Can you reproduce this issue with the current release?  
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on  

Brave | 1.58.100 Chromium: 116.0.5845.114 (Official Build) beta (64-bit)
-- | --
Revision | a8c0058265009a1858c4502b9ba413671fbb61e1
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from issue description
- Verified wallet connection panel doesn't close when loading `https://magiceden.io`
- Verified able to connect and sign without issues

https://github.com/brave/brave-browser/assets/17010094/6c26d71a-2bc3-4e6a-9bc3-f55d794b0f7f
