### ISSUE TITLE
s/Wireguard for Android/WireGuard for Android in `brave://credits`

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#31854]
## Description 

`Wireguard for Android` should read `WireGuard for Android` in `brave://credits`

## Steps to Reproduce

   1. install `1.57.24`
   2. launch Brave
   3. open `brave://credits`
   4. look at `Wireguard for Android` heading

## Actual result:

`Wireguard for Android`

![image](https://github.com/brave/brave-browser/assets/387249/c622896b-54b5-441a-bf53-59a62c9b2d1f)

## Expected result:

`WireGuard for Android`

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.57.24 Chromium: 115.0.5790.136 (Official Build) beta (64-bit)
-- | --
Revision | 8099932ede6f8d4624fbddf39d27abb3b340d8c9
OS | Windows 10 Version 22H2 (Build 19045.3208)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

/cc @rebron @spylogsster

**Comment by spylogsster** [comment]
cc @deeppandya

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.67.90`

Confirmed that `Wireguard for Android` is renamed as `WireGuard for Android` in brave://credits
![Uploading Screenshot_20240530_173057.jpg…]()
