### ISSUE TITLE
[Android] Upgrade from Chromium 115.0.5790.136 to Chromium 115.0.5790.138 (1.56.x only).

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#31869]
# Minor Chromium bump

https://chromium.googlesource.com/chromium/src/+log/115.0.5790.136..115.0.5790.138?pretty=fuller&n=10000

**Note:** 1.56.x branch will be on 115.0.5790.114, which already includes the .136->.138 fixes, so this will just update the version number.

# QA tests:

* Check branding items
* Check for version bump

# Additional checks:
* No specific code changes in Brave (only line number changes in patches)

**Comment by kjozwiak** [comment]
Closing as https://github.com/brave/brave-core/pull/19432 was merged into `1.56.x`. The above requires `1.56.16` or higher for `1.56.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version:

```
Brave	1.56.16 Chromium: 115.0.5790.138 (Official Build) (32-bit) 
Revision	0567db0e7dcdfee5c109c167119ac2a92b9b3e1a-refs/branch-heads/5790_85@{#9}
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

- [x] version bump
- [x] branding items

Example | Example
-|-
![Screenshot 2023-07-26 at 8 55 30 PM](https://github.com/brave/brave-browser/assets/17885425/80584652-c2f2-4b18-8046-5b5f830717bc) | ![Screenshot 2023-07-26 at 8 57 11 PM](https://github.com/brave/brave-browser/assets/17885425/fecbef13-2c6d-4d2c-bf51-efaa4fa79c29)

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy Tab S7` using version:

```
Brave	1.56.16 Chromium: 115.0.5790.138 (Official Build) (64-bit) 
Revision	0567db0e7dcdfee5c109c167119ac2a92b9b3e1a-refs/branch-heads/5790_85@{#9}
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
- [x] version bump
- [x] branding items

Example | Example 
-|-
![Screenshot 2023-07-26 at 9 01 23 PM](https://github.com/brave/brave-browser/assets/17885425/ece006d8-660a-4cf5-9fbb-a85018387c65) | ![Screenshot 2023-07-26 at 9 01 43 PM](https://github.com/brave/brave-browser/assets/17885425/0ad73a3a-02b4-413d-b4ea-49c8f0d8466d)
