### ISSUE TITLE
seeing advertisement on youtube.

### ISSUE THREAD

**Issue by prajjwaldevkota** [brave/brave-browser#31888]
## Description 

Brave isnt blocking advertisement on youtube. 

## Steps to Reproduce

   1. 
   2. 
   3. 

## Actual result:

![image](https://github.com/brave/brave-browser/assets/68115199/a33f8498-d324-44ec-b222-b12d16807d0c)

## Expected result:
Advertisements should be blocked, I think it stopped after the newest update.

## Brave version (brave://version info)

Brave	1.56.11 Chromium: 115.0.5790.102 (Official Build) (64-bit) 
Revision	90efd4b0ad6aa15eeafcdabd5817ae939f7ba059-refs/branch-heads/5790_90@{#9}
OS	Windows 11 Version 23H2 (Build 22631.2050)
JavaScript	V8 11.5.150.16
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Command Line	"C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe" --disable-domain-reliability --enable-dom-distiller --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --variations-insecure-server-url=https://variations.brave.com/seed --flag-switches-begin --disable-smooth-scrolling --flag-switches-end --component-updater=url-source=https://go-updater.brave.com/extensions
Executable Path	C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path	C:\Users\PC\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Active Variations	AllowCertainClientHintsStudy:Enabled
BraveAdblockMobileNotificationsListDefault:Enabled
BraveAds.AdServingStudy:DefaultAdNotificationsPerHour=10/MaximumAdNotificationsPerDay=100/MaximumInlineContentAdsPerHour=6/MaximumInlineContentAdsPerDay=20/AdServingVersion=2
BraveAutoTranslateStudy:AutoTranslateDisabled
BraveDebounceStudy:Enabled
BraveGoogleSignInPermissionStudy:Disabled
BraveHttpsByDefaultRolloutStudy:Enabled
BraveP3AConstellationReleaseRollout:Default
BraveRewardsWebUiPanelStudy:Enabled
BraveScreenFingerprintingBlockerStudy:Enabled
CookieListDefaultStudy:Enabled
CrossPlatformVPNStudy:Enabled
Default1pBlockingStudy:Disabled
DisableReduceLanguage:Enabled
EphemeralStorageStudy:Enabled
FirstPartyEphemeralDomainBlockStudy:Enabled
ForceDisableBlinkFeatures:Enabled
PartitionBlinkMemoryCacheStudy:Enabled
PartitionConnectionsByNetworkIsolationKeyStudy:Enabled
PermissionLifetimeReleaseStudy:Enabled
SpeedreaderReleaseStudy:Enabled
UserActivityStudy:Triggers
WhatsNewStudy:Enabled

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by jmerc77** [comment]
same. on win 10.

**Comment by bsclifton** [comment]
@prajjwaldevkota just wanted to check in 😄 How are things looking?

**Comment by prajjwaldevkota** [comment]
Hey. Its working fine now. I dont know why I needed to change the setting since it was working perfectly fine without the aggressive mode. Maybe brave changed something

**Comment by ryanbr** [comment]
Youtube blocking changes happening regularly (changes every few days), countering the anti-adblock and still blocking the ads is still on going. Glad its working for the time being
