### ISSUE TITLE
on v1.56.9, Assets manually added don't get added to deposit list

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#31889]
## Description 

See thread here - > https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1690382104488839

User brought it up here - > https://community.brave.com/t/please-add-plu-pluton-support/495588/5

## Steps to Reproduce

   1. try to add a token manually
   2. then try see if its on deposit list
   3. 

## Actual result:

https://github.com/brave/brave-browser/assets/12224304/283f7b98-3934-4742-8c2a-926eef772ba8

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.58.98` or higher for `1.58.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on  

Brave | 1.58.100 Chromium: 116.0.5845.114 (Official Build) beta (64-bit)
-- | --
Revision | a8c0058265009a1858c4502b9ba413671fbb61e1
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#19702](https://github.com/brave/brave-core/pull/19702)
- Verified added tokens show up on deposit screen

https://github.com/brave/brave-browser/assets/17010094/fe9da2de-17be-4f0a-95ab-8a9365e9beb4

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.58.117 x64 build
- Verified steps from [brave/brave-core#19702](https://github.com/brave/brave-core/pull/19702)
- Verified added tokens show up on deposit screen

https://github.com/brave/brave-browser/assets/17010094/a9cce0bb-c761-46b8-aded-dacb7f9f2263
