### ISSUE TITLE
Network fee remains 0.00 for Swap transactions

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#31883]
## Description 

Network fee remains 0.00 for transactions

## Steps to Reproduce

   1. Submit a Swap transaction
   2. Edit the network fee
   3. Shows 0.00

## Actual result:

https://github.com/brave/brave-browser/assets/17010094/bf8480bf-56de-46f9-9af6-f85db897be9a

## Expected result:
Show network fee value 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.57.24 Chromium: 115.0.5790.136 (Official Build) beta (64-bit)
-- | --
Revision | 8099932ede6f8d4624fbddf39d27abb3b340d8c9
OS | Windows 11 Version 22H2 (Build 22621.1992)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @onyb @josheleonard

**Comment by kjozwiak** [comment]
The above requires `1.57.33` or higher for `1.57.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.57.33 Chromium: 115.0.5790.114 (Official Build) beta (64-bit)
-- | --
Revision | 86b4ea1d70ce73c4468d84cc8277f1f9de14b8bc
OS | Windows 11 Version 22H2 (Build 22621.1992)

- Verified steps from issue description
- Verified network fee is updated correctly in the panel based on user setting

https://github.com/brave/brave-browser/assets/17010094/b5190f8b-db10-44c2-bfb1-86ece91e5860
