### ISSUE TITLE
Estimated earnings tooltip background is not visible on brave://rewards summary section

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#31887]
## Description 
Found while testing https://github.com/brave/brave-browser/issues/30352
Estimated earnings tooltip boarders are not visible in light/dark theme in brave://rewards summary section
## Steps to reproduce 

 NA

## Actual result 

Light theme | Dark theme
--------------|-------------
![Screenshot_20230726_174439](https://github.com/brave/brave-browser/assets/38657976/59ecdc49-0318-469b-a38d-2d12d6b2f9c3) | ![Screenshot_20230726_174511](https://github.com/brave/brave-browser/assets/38657976/e775d7a9-364d-4610-9844-03d1a49fec70)

## Expected result
Estimated earnings tooltip boarders should be shown clearly same like BR panel

**BR Panel**
![Screenshot_20230726_174449](https://github.com/brave/brave-browser/assets/38657976/929aa741-b1c5-41c3-8d6b-bcd8abc4d7bc)

## Issue reproduces how often 

Easy
## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86): all
   - Device type (Phone, Tablet, Phablet): all
   - Android version: 12
   
## Brave version
1.57.19

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/qa-team @deeppandya @sujitacharya2005 @Miyayes

**Comment by GeetaSarvadnya** [comment]
This issue is reproducible on `Samsung Tab A7 version 12` running `Bravemonoarm64.apk_1.57.32`

Light theme | Dark theme
--|--
![Screenshot_20230801-173143_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/9bd9c9ab-7561-4d30-a442-ef12a0a6b854) | ![Screenshot_20230801-173052_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/1d82da2a-e1d1-48de-82d5-ed5f75ff4959)

**Comment by kjozwiak** [comment]
The above requires `1.57.35` or higher for `1.57.x` verification 👍

**Comment by kjozwiak** [comment]
Created https://github.com/brave/brave-browser/issues/32052 while running through https://github.com/brave/brave-core/pull/19518#issuecomment-1663071925.
