### ISSUE TITLE
Bookmarks on device where sync was reset isn't sent across the chain

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#3188]
## Description 

Bookmarks on device where sync was reset isn't sent across the chain. 

## Devices
Device 1: Samsung Tab running 1.0.76
Device 2: Pixel 3XL running 1.0.76
Device 3: Linux running 0.59.34 profile 1 (Sync already created and reset)
Device 4: Linux running 0.59.34 profile 2 

## Steps to Reproduce

   1. Create bookmarks and folders on device 1
   2. Create sync chain on Device 1 and scan QR code on device 2, ensure all bookmarks are sync'd on device2
   3. Reset existing sync on device 3 which has existing bookmarks 
   4. Enter code words from device 1 and join device 3 on the sync chain, bookmarks from device 1 sync on device 3
   5. Existing bookmarks from device 3 isn't sync'd to device 1 or device 2
   6. Create bookmarks on device 4 and join the sync chain using code words
   7. Once device is listed, device 4 sync's all bookmarks from device 1, similarly device 1,2 & 3 sync's all bookmarks from device 4

## Actual result:

Device 1
![screenshot_20190201-051813_brave](https://user-images.githubusercontent.com/17010094/52117091-e09e3700-2638-11e9-9625-a9d0cfb1a2b9.jpg)
Device 2
![screenshot_20190201-154748](https://user-images.githubusercontent.com/17010094/52117096-e5fb8180-2638-11e9-894b-f8b396616bf8.png)
Device 3 (Contains 2 bookmark folder `Linux` and `Windows` which doesn't sync)
![screenshot from 2019-02-01 15-46-41](https://user-images.githubusercontent.com/17010094/52117116-f01d8000-2638-11e9-8cc5-0387418d13a1.png)
Device 4
![screenshot from 2019-02-01 15-47-14](https://user-images.githubusercontent.com/17010094/52117121-f4e23400-2638-11e9-9ea6-ffeb57025929.png)

## Expected result:
Irrespective of previous sync state all bookmarks should be sync'd across all devices

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.59.34 Chromium: 72.0.3626.81 (Official Build) (64-bit)
-- | --
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS | Linux

Android Build 1.0.76

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @SergeyZhukovsky @brave/legacy_qa @AlexeyBarabash @darkdh

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.61.38 Chromium: 73.0.3683.39 (Official Build) beta (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

Used STR from https://github.com/brave/brave-core/pull/1560.
All the devices got the expected bookmarks.
