### ISSUE TITLE
Unable to Select Market Token in Wallet Panel

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#31893]
## Description 

We are currently unable to select a `Market Token` in the Wallet `Panel`

https://github.com/brave/brave-browser/assets/40611140/5b5e4b1e-95b2-42f3-94f4-3ae5c848d754

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.59.115 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | `82b05012fc6b5ab8535cf283db6856ad5eedd7eb`
OS | Windows 11 Version 22H2 (Build 22621.2283)

- Verified steps from [brave/brave-core#19671](https://github.com/brave/brave-core/pull/19671)
- Verified able to select market token from wallet panel
- Encountered [#33515](https://github.com/brave/brave-browser/issues/33515)

https://github.com/brave/brave-browser/assets/17010094/2b974381-1815-41d2-b4bf-2734fae55caa


---------------------

**Verification passed on**

Brave | 1.59.115 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | `82b05012fc6b5ab8535cf283db6856ad5eedd7eb`
OS | Linux

- Verified steps from [brave/brave-core#19671](https://github.com/brave/brave-core/pull/19671)
- Verified able to select market token from wallet panel
- Encountered [#33515](https://github.com/brave/brave-browser/issues/33515)

https://github.com/brave/brave-browser/assets/17010094/b75be267-914b-4554-9e3d-fb42705a5211


---------------------

**Verification passed on**

Brave | 1.59.115 Chromium: 118.0.5993.54 (Official Build) (arm64)
-- | --
Revision | `82b05012fc6b5ab8535cf283db6856ad5eedd7eb`
OS | macOS Version 14.0 (Build 23A344)

- Verified steps from [brave/brave-core#19671](https://github.com/brave/brave-core/pull/19671)
- Verified able to select market token from wallet panel
- Encountered [#33515](https://github.com/brave/brave-browser/issues/33515)

https://github.com/brave/brave-browser/assets/17010094/5c4d06b6-58dc-46fd-8272-6269da132be6
