### ISSUE TITLE
Chromium WEI: Web Environment Integrity

### ISSUE THREAD

**Issue by aaronclong** [brave/brave-browser#31897]
I wanted to raise this issue about the recent addition of WEI to Chrome by Google. I wanted to get a sense of Brave's ideas about this new feature, and the controversy it has created among the web and developer community. 

Brave being chromium based will eventually inherit this feature from Google. As an avid Brave user, I wanted to know the stance on this divisive feature.

- https://rupertbenwiser.github.io/Web-Environment-Integrity/
- https://github.com/chromium/chromium/commit/6f47a22906b2899412e79a2727355efa9cc8f5bd

**Comment by aaronclong** [comment]
![Buelller?](https://media3.giphy.com/media/vHwGAMZfWj3mU/giphy.gif)

**Comment by mlhaufe** [comment]
Brendan has tweeted on this:

https://twitter.com/BrendanEich/status/1684561924191842304

> We are a fork, have been all along, [...]. We won’t be shipping WEI support, just as we disable or otherwise nullify lots of other junk that Google puts into Chromium.

**Comment by rebron** [comment]
Closing per last comment. "We won't be shipping WEI support" is about as clear as you can get. 

"Brave being chromium based will eventually inherit this feature from Google" is not a true statement please see https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove).

I'm refraining from responding in a more colorful way, the referenced tweet should suffice.

**Comment by aaronclong** [comment]
@rebron  and @mlhaufe, thanks for responding to this. I don't use twitter much as of late, and have never followed the CEO Brave. I don't think this tweet has gotten as much reach at the response would suggest.

@rebron thank you for sharing deviations from Chromium document. I believe stumbled upon that earlier but didn't see the WEI issue. Hence me raising the question here.

Assuming good intentions, thank you both and happy weekend.
