### ISSUE TITLE
[Android] Slow loading FB timeline

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#31894]
## Description
We got a report that the FB timeline takes ~5 seconds to load in Brave Android. The timeline loads almost immediately in Brave Desktop, Brave iOS and other browsers.
https://community.brave.com/t/brave-loads-facebook-really-slowly/498222/2

@timchilds was able to reproduce the issue with below STR. Please check then recording for more details. 

## STR
1. Open m.facebook.com.
2. Observe how long it takes for the timeline to load.

https://github.com/brave/brave-browser/assets/28269287/ac5b4479-3923-403a-8d84-4ad465fee758

**Comment by SergeyZhukovsky** [comment]
the API returns
`INTERNAL_ERROR, code: 8` on links like that, I assume because of `wss` schema
`wss://kaios-d.facebook.com`

**Comment by kjozwiak** [comment]
The above requires `1.56.120` or higher for `1.56.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version: 

```
Brave	1.56.20 Chromium: 115.0.5790.171 (Official Build) (32-bit) 
Revision	cf9067bf10d8f798c24643029af1d24e275646d6-refs/branch-heads/5790@{#1924}
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

- Verified loading facebook.com and timeline is instant

![Screenshot 2023-08-03 at 12 38 05 PM](https://github.com/brave/brave-browser/assets/17885425/c719f503-ccfc-4878-885f-35a53a709808)
