### ISSUE TITLE
Text in the shield menu should not be selectable

### ISSUE THREAD

**Issue by Jacalz** [brave/brave-browser#319]
## Description 
It is currently possible to select the text in the shield menu...

 ## Actual result:
![image](https://user-images.githubusercontent.com/25466657/41287006-a65397d4-6e41-11e8-9667-625fd6feb646.png)

## Expected result:
text should not be selectable

## Brave version (about:brave info)

Version 67.0.3396.62

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | -- 
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Linux
