### ISSUE TITLE
Create Filecoin account prompt is only dismissed after creating 2 accounts

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#31909]
## Description 

Create Filecoin account prompt is only dismissed after creating 2 accounts

## Steps to Reproduce

   1. Create a new Wallet
   2. Go to Accounts tab
   3. Open Panel and switch to Filecoin Account
   4. Shows prompt to create an account
   5. Click Yes, creates account but doesn't close the prompt
   6. Click Yes again, prompt is closed, 2 Filecoin accounts are created

## Actual result:

https://github.com/brave/brave-browser/assets/17010094/66f904c9-e405-4d95-8f3b-afd830ef3b7f

## Expected result:
Should dismiss account creation prompt when account is created successfully

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.57.24 Chromium: 115.0.5790.136 (Official Build) beta (64-bit)
-- | --
Revision | `8099932ede6f8d4624fbddf39d27abb3b340d8c9`
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

cc: @Douglashdaniel

**Comment by kjozwiak** [comment]
Closing as the above was fixed/uplifted into `1.57.x` via https://github.com/brave/brave-core/pull/19502.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.57.35 Chromium: 115.0.5790.171 (Official Build) beta (arm64)
-- | --
Revision | 776897328898241b35b83878040730e73e749c06
OS | macOS Version 13.4.1 (c) (Build 22F770820d)

- Verified steps from issue description
- Verified only one Filecoin account is created when selecting Filecoin Mainnnet from network selector in Panel

https://github.com/brave/brave-browser/assets/17010094/318f53d5-fd2a-40c3-a1ec-2af64e6f1192
