### ISSUE TITLE
CR116 - Toolbar buttons are not placed correctly when switching to `Vertical Tabs` on Windows

### ISSUE THREAD

**Issue by Emi-TheDhamphirInLoveUnderTheFrozenStar** [brave/brave-browser#31908]
## Description 

1.58.51 Chromium: 116.0.5845.51 (Official Build) nightly (64-bit) on Windows 11 22H2 22621.1992

Using Vertical Tabs with the `Settings` -> `Appearance` -> `Show Title Bar` setting set to off, makes Brave top window part to look like this on Windows.

![image](https://github.com/brave/brave-browser/assets/122518587/37bc32db-0f0a-4996-95af-d6f44f5f53ef)

**Comment by GeetaSarvadnya** [comment]
Issue is reproducible on `Windows 10 x64 - 1.58.52`

Steps to reproduce:

1. Clean profile 1.58.52 - CR 116 or 1.58.51 - CR 116
2. Enable vertical tabs via brave://settings/appearance
3. Uncheck the `Show tile bar` checkbox

![image](https://github.com/brave/brave-browser/assets/38657976/424dd51c-675f-4841-b496-70313c5fb643)

**Comment by GeetaSarvadnya** [comment]
The issue is related to CR 116 as issue isn't reproducible in `1.58.50 Chromium: 115.0.5790.114`

**Comment by Emi-TheDhamphirInLoveUnderTheFrozenStar** [comment]
@mkarolin This issue is still not completely fixed in 1.58.57.

https://github.com/brave/brave-browser/assets/122518587/9653d773-9db9-4172-a2b3-91e6541d786c

Opening Brave will cause the buttons to still be messed up. The only way to fix it is by Toggling on and off the Show Title Bar or use the quick command `:> Toggle vertical tabs window title`.

The problem as you can see in the videos is that opening any new window, Normal, Private or Tor, will cause the buttons to be messed up again on those windows. So you have to turn Title bar on and off again to fix them.

Another problem which is hard to tell when using quick commands is that the title bar doesn't show, when the title bar is turned on the first time after the buttons are messed up, so you have to turn it on, then off, and then on again to see it. This happens on both, Maximized or Window mode.

https://github.com/brave/brave-browser/assets/122518587/f21ee4b9-48a0-49f6-8013-4202c3a9a35f

So the problem is still present, at least for now the experience is better since toggling Title on and off fixes the issue in the meantime.

**Comment by mkarolin** [comment]
Thanks @Emi-TheDhamphirInLoveUnderTheFrozenStar, I'll reopen the issue. 

@sangwoo108, would you mind taking a look on Monday?

**Comment by Emi-TheDhamphirInLoveUnderTheFrozenStar** [comment]
Also, I noticed a tiny little visual bug when the title bar is showing. The window buttons hovering effect, when the window is maximized and you switch tabs from Horizontal / Vertical mode. The height between the title bar in Horizontal Mode is different than the one in Vertical tabs, causing the Window buttons hovering effect to not change height and then causing some overlap the toolbar buttons from horizontal -> vertical) or being smaller from vertical to horizontal.

The only way to fix it is to change window size and maximize it again.

I tried to show it in this video, because the size of the hovering effect changes depending on if the window was opened with Horizontal tabs or Vertical tabs.

https://github.com/brave/brave-browser/assets/122518587/a70642cf-da54-4415-b42b-1bd8f9f2aca2

**Comment by Coffeeling** [comment]
Confirming Emi's report of sometimes fixed, sometimes still occurring bug. The Nightly update before this had the bug always.

macOS Ventura
Brave Nightly: Version 1.58.57 Chromium: 116.0.5845.51 (Official Build) nightly (arm64)

**Comment by sangwoo108** [comment]
@Emi-TheDhamphirInLoveUnderTheFrozenStar @Coffeeling , thanks for the report. Let me split the issue.

**Comment by kjozwiak** [comment]
The above requires `1.57.42` or higher for `1.57.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.57.42 Chromium: 116.0.5845.51 (Official Build) (64-bit)
-- | --
Revision | e25036a089c476c56bf71774a898a1fee014e00d
OS | Windows 11 Version 22H2 (Build 22621.1992)
```

Reproduced the issue in `1.58.51`

brave://settings/appearance|Normal Window | Private window | Private window with Tor
-------- | ----------- |--------- | --------
<img width="935" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/8520073e-6c56-458e-9bd4-d7ff67b24e8c">|<img width="592" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/63d893dc-884c-41cb-b619-3085595b6237">|<img width="461" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/e1e31f26-da3b-41c6-b292-7ed179c93874">|<img width="354" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/6c8453ea-9a89-4780-8583-951e886e9126">

### Steps: 

1. Installed 1.58.51
2. launched Brave
3. install an extension (1Password) via `chrome.google.com/webstore`  
4. opened a new tab and play youtube playlists
5. opened `brave://settings/appearance` in a new tab
6. enabled `Use vertical tabs` 
7. unchecked the checkbox for `Show title bar` 
8. opened New private window 
9. opened New private window with Tor

#### Confirmed Toolbar buttons placed correctly on the toolbar for all three windows (Normal, Private window & Private window with Tor)

step 5 | Normal window | Private window | Private window with Tor
------- | ---------- | ---------- | ------------
<img width="955" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/2393e3a2-80ff-400b-9bf0-ea8955717390">|<img width="591" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/ca1f01ba-2a29-4789-9c11-9e9b9be6d3e2">|<img width="967" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/b39a06fe-a572-4779-9643-8533e36839b4">|<img width="531" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/14f06e20-d25a-488d-9b0d-5836966f7539">


10. Returned to the default value (checked the checkbox) for `Show titlebar` in `brave://settings/appearance`

#### Confirmed Toolbar buttons placed correctly on the toolbar for all three windows (Normal, Private window & Private window with Tor)

step 10 | Normal window | Private window | Private window with Tor
------- | ---------- | ---------- | ------------
<img width="950" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/164e5a62-4b6b-409e-94c3-9e7551f3189b">|<img width="955" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/32545d12-609e-45f6-870b-8a268f7f6221">|<img width="358" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/7409d076-3ba9-42ea-aec2-9e448fbd4c40">|<img width="373" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/7742e284-2049-43fd-b223-4da2fd4c59db">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave	1.57.42 Chromium: 116.0.5845.51 (Official Build) (64-bit) 
Revision	e25036a089c476c56bf71774a898a1fee014e00d
OS	Linux
```

Reproduced the issue in `1.58.51`

Normal Window | Private window | Private window with Tor
----- | ----- | ----- 
![image](https://github.com/brave/brave-browser/assets/98358127/0cc5e57f-71e2-4c41-b0d3-c0b85ba50450)|![image](https://github.com/brave/brave-browser/assets/98358127/fb006f8f-2774-48a7-ae29-d47cdfbedf78)|![image](https://github.com/brave/brave-browser/assets/98358127/0ac405dd-c0ce-44b9-8cf8-7ca4baa9a062)


#### Steps: 

1. Installed 1.57.42
2. launched Brave
3. install an extension (simple translator) via chrome.google.com/webstore
4. opened a new tab and play youtube playlists
5. opened brave://settings/appearance in a new tab
6. enabled Use vertical tabs
7. unchecked the checkbox for Show title bar
8. opened New private window
9. opened New private window with Tor
10. Confirmed Toolbar buttons placed correctly on the toolbar for all three windows (Normal, Private window & Private window with Tor)
