### ISSUE TITLE
Sending a Solana NFT from NFT View tries to send as a Token

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#31905]
## Description 

Clicking `Send` on a `Solana NFT` from `NFT View` tries to send as a `Token`

## Steps to Reproduce

   1. Add a Solana NFT and click it to view more details
   2. Click on `Send` at the top right corner
   3. When routed to the `Send` page, `Send Token` will be selected but should be `Send NFT`

## Actual result:

https://github.com/brave/brave-browser/assets/40611140/89cf265e-acd9-47ca-9669-e100a852a182

## Expected result:
Should auto select `Send NFT`

## Reproduces how often: 

Easy

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.57.33` or higher for `1.57.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.57.33 Chromium: 115.0.5790.114 (Official Build) beta (64-bit)
-- | --
Revision | 86b4ea1d70ce73c4468d84cc8277f1f9de14b8bc
OS | Windows 11 Version 22H2 (Build 22621.1992)

- Verified steps from [brave/brave-core#19446](https://github.com/brave/brave-core/pull/19446)
- Verified selecting NFT shows `Send NFT`
- Verified selecting Send on NFT page shows the correct route path in the URL as well

https://github.com/brave/brave-browser/assets/17010094/54376c2c-0820-4be6-b515-7d53a5911d7b
