### ISSUE TITLE
Unable to change tabs on Send page with route params

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#31906]
## Description 

Unable to change tabs on Send page when there are route params

## Steps to Reproduce

   1. Go to the `NFT` tab and select an `NFT`
   2. Click on `Send` at the top right corner
   3. You will be routed to the `Send` page
   4. Try to change tabs between `Send Token` and `Send NFT`
   5. It doesn't let you

## Actual result:

https://github.com/brave/brave-browser/assets/40611140/f8941027-db5f-41ea-a0a8-02f64e8a5209

## Expected result:
Should clear the `Route` params and allow you to switch between tabs.

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.57.33 Chromium: 115.0.5790.114 (Official Build) beta (64-bit)
-- | --
Revision | 86b4ea1d70ce73c4468d84cc8277f1f9de14b8bc
OS | Windows 11 Version 22H2 (Build 22621.1992)

- Verified steps from [brave/brave-core#19446](https://github.com/brave/brave-core/pull/19446)
- Verified able to change tabs on Send page when selecting Send NFT

https://github.com/brave/brave-browser/assets/17010094/fda0056d-ff52-46c9-b0af-d9fe0848bf6c
