### ISSUE TITLE
Point to new channel file behind CDN

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-browser#3191]
## Description 
In order to make the channels file faster and more reliable for the browser to retrieve, the devops team has put it behind the CDN and defaulted the file to being gzip compressed at the edge. To ensure that both versions can run uninterrupted for existing clients, there is a new subdomain to retrieve the file.  Please change the URLs to request channel files to the following:

Staging: https://publishers-staging-distro.basicattentiontoken.org/api/v1/public/channels
Production: https://publishers-distro.basicattentiontoken.org/api/v1/public/channels

Keep in mind that to take advantage of the gzipping, you need to send a ""Accept-Encoding: gzip" header and confirm that the file is uncompressed client side.

**Comment by LaurenWags** [comment]
@NejcZdovc could you clarify which flags I should be using in the terminal? I'm launching with `/Applications/Brave\ Browser\ Beta.app/Contents/MacOS/Brave\ Browser\ Beta --v=3 --vmodule=*rewards*=6` but maybe I'm missing a necessary flag. I'm trying to follow the test plan in https://github.com/brave/brave-core/pull/1575 with 

Brave | 0.60.28 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Mac OS X



The only item I see about the publisher list is `[55344:26115:0213/173234.735493:ERROR:rewards_service_impl.cc(165)] Failed to read file: /Users/laurenwagner/Library/Application Support/BraveSoftware/Brave-Browser-Beta/Default/publishers_list`

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.60.28 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Mac OS X

* Verified test plan in https://github.com/brave/brave-core/pull/1575. Launched Brave with `--enable-logging=stderr --v=1 --vmodule=*rewards*=6`. Verified I saw this Request in the terminal:
```
[ REQUEST ]
> url: https://publishers-distro.basicattentiontoken.org/api/v1/public/channels
> method: GET
> content: 
> contentType: 
> headers: Accept-Encoding: gzip
[ END REQUEST ]
```
