### ISSUE TITLE
Unlocking on Buy screen shows no On-ramp provider/account details

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#31912]
## Description 

Unlocking on Buy screen shows no On-ramp provider/account details

## Steps to Reproduce

   1. Go to Buy screen
   2. Select a Token 
   3. Lock wallet on the token buy screen
   4. Unlock wallet, no token/accounts details are shown

## Actual result:

https://github.com/brave/brave-browser/assets/17010094/5fb005d8-62f9-4ce8-b43d-198f808377d5

## Expected result:
Should show account/token details 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.57.24 Chromium: 115.0.5790.136 (Official Build) beta (64-bit)
-- | --
Revision | 8099932ede6f8d4624fbddf39d27abb3b340d8c9
OS | Windows 11 Version 22H2 (Build 22621.1992)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel @josheleonard

**Comment by HEagle18** [comment]
assigning to you @Douglashdaniel because it was mentioned that you might have a fix for this.

**Comment by kjozwiak** [comment]
Closing as the above was fixed/uplifted into `1.57.x` via https://github.com/brave/brave-core/pull/19506. The above requires `1.57.35` or higher for `1.57.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.57.35 Chromium: 115.0.5790.171 (Official Build) beta (arm64)
-- | --
Revision | `776897328898241b35b83878040730e73e749c06`
OS | macOS Version 13.4.1 (c) (Build 22F770820d)

- Verified steps from issue description
- Verified unlocking on any step on the Buy screen shows the correct token selection screen on Buy screen

https://github.com/brave/brave-browser/assets/17010094/e3a041e2-5dcb-46d4-a031-654c86e0b781
