### ISSUE TITLE
Unable to select different Solana account from dropdown in Buy screen

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#31911]
## Description 

Unable to select different Solana account from dropdown in Buy screen

## Steps to Reproduce

   1. Create 2 Solana accuonts
   2. Go to Buy screen
   3. Select Account dropdown and try to select a different Solana account

## Actual result:

https://github.com/brave/brave-browser/assets/17010094/686da0b4-1a28-4bce-9fa0-af43d3d230c3

## Expected result:
Should be able to select different Solana Account

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.57.24 Chromium: 115.0.5790.136 (Official Build) beta (64-bit)
-- | --
Revision | 8099932ede6f8d4624fbddf39d27abb3b340d8c9
OS | Windows 11 Version 22H2 (Build 22621.1992)
 
## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel

**Comment by kjozwiak** [comment]
Closing as https://github.com/brave/brave-core/pull/19461 was uplifted into `1.57.x` 👍 The above requires `1.57.33` or higher for `1.57.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on  

Brave | 1.57.33 Chromium: 115.0.5790.114 (Official Build) beta (64-bit)
-- | --
Revision | 86b4ea1d70ce73c4468d84cc8277f1f9de14b8bc
OS | Windows 11 Version 22H2 (Build 22621.1992)

- Verified steps from issue description
- Verified able to select different accounts from Buy screen

https://github.com/brave/brave-browser/assets/17010094/697aa810-fb2c-49b1-bbf6-3a59e3758115
