### ISSUE TITLE
User can reset rewards even though the rewards is not enabled

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#31914]
## Description 
Found while testing https://github.com/brave/brave-browser/issues/26902
User can reset rewards even though there is no active wallet
## Steps to reproduce 

   1. Clean profile 1.57.x
   2. Enable rewards
   3. Confirm that `Reset` gear icon is shown on the brave://rewards page
   4. Click on the `Reset` icon and go through the reset screens and complete the reset and relaunch the browser
   5. brave://rewards page is displayed with `Brave Private ads` switch disabled and Reset button visible and active, user can still click on `Reset` button and go through the reset process even though the rewards is NOT enabled
   6. if user reload the page `Start using Brave Rewards` modal popup is presented with brave://rewards page with reset button in the background

## Actual result 

brave://rewards page with Reset button is displayed when brave rewards is reset

https://github.com/brave/brave-browser/assets/38657976/43a0490a-5c0a-4204-87ac-4f3ad73bb2bb

## Expected result
Should work same as Desktop, after resetting rewards the page looks like this in desktop
![image](https://github.com/brave/brave-browser/assets/38657976/82bfea8d-90c1-481d-91d3-57e3197792a3)

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86): all
   - Device type (Phone, Tablet, Phablet): all
   - Android version: 12
   
## Brave version

1.57.19
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/qa-team @Miyayes @deeppandya

**Comment by Miyayes** [comment]
@GeetaSarvadnya Can you check this one now that https://github.com/brave/brave-browser/issues/31592#event-9989623701 has been merged?

**Comment by GeetaSarvadnya** [comment]
@Miyayes The issue https://github.com/brave/brave-browser/issues/31592#event-9989623701 is still not merged to beta `1.57.x` verified the latest beta version `1.57.41` (deployed yesterday). Verified the latest master and ensured that the issue #31592 is working fine in `1.59.1`

`1.59.1` | `1.57.41`
---------|---------
![Screenshot_20230809_110436](https://github.com/brave/brave-browser/assets/38657976/e154e8e8-7d5a-4a54-bc18-cafbb2dfcb63) | ![Screenshot_20230809_111417](https://github.com/brave/brave-browser/assets/38657976/788f1f45-4695-400d-8e6b-8e9653b812a8)

**Comment by GeetaSarvadnya** [comment]
The issue is fixed in the master/nightly `1.59.1` hence closing the issue.
