### ISSUE TITLE
NFTs stays visible after marked as invisible in edit visible

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#31915]
## Steps to reproduce 
   1. Open NFT tab
   2. Mark some NFTs as invisible via edit visible and save
   3. Open edit visible again

## Actual result 
[nft-visibility.webm](https://github.com/brave/brave-browser/assets/11755381/6673717f-92df-4cf0-9139-feaff1979d08)

## Expected result
Invisible/Hidden NFTs should not be shown as checked/visible

**Comment by kjozwiak** [comment]
The above requires `1.59.113` or higher for `1.59.x` verification 👍

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/33255#issuecomment-1752437399
