### ISSUE TITLE
Vertical tab bar issues

### ISSUE THREAD

**Issue by wknapik** [brave/brave-browser#31925]
## Description 

Once the vertical tab bar is full (has as many tabs as can be shown without scrolling), ctrl+tabbing from the last tab switches to the first one, but the tabs are bottom-aligned and only the active one and those before it are shown.

![image](https://github.com/brave/brave-browser/assets/1129003/395899ac-0a56-49c2-9219-1543482c14d1) | ![image](https://github.com/brave/brave-browser/assets/1129003/a8c0b0ac-a0f7-41ce-93cb-e45ac028dd1c) | ![image](https://github.com/brave/brave-browser/assets/1129003/072ddb5a-9351-4bd5-95d8-34393298b356)

## Steps to Reproduce

   1. Open enough tabs to fill the tab bar
   2. Go to the last tab
   3. Ctrl+tab

## Actual result:

Tabs bottom-aligned and ones after the active one not visible

## Expected result:
Tabs top-aligned and ones after the active one visible

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

1.56.11 Chromium: 115.0.5790.102 (Official Build) (64-bit) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? ?
- Can you reproduce this issue with the nightly channel? ?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? ?

## Miscellaneous Information:

[Slack thread](https://bravesoftware.slack.com/archives/C042KL922P3/p1690463587233439)

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave	1.56.18 Chromium: 115.0.5790.138 (Official Build) (64-bit) 
Revision	0567db0e7dcdfee5c109c167119ac2a92b9b3e1a-refs/branch-heads/5790_85@{#9}
OS	Linux
```
![image](https://github.com/brave/brave-browser/assets/38657976/44ac68da-952c-4b0a-84c1-8f88c575ee4b)
