### ISSUE TITLE
NFT section tabs [NFTs, Hidden]

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-browser#31922]
<img src="https://github.com/brave/brave-browser/assets/318119/52640dd7-3900-417a-b2a3-15220d145677" width="500">

**Comment by simoarpe** [comment]
Issue completed. For a full description of the issues related see https://github.com/brave/brave-browser/issues/32196

**Comment by simoarpe** [comment]
Reopening this to add some small tweaks.
