### ISSUE TITLE
CR 116 - In a narrow view mode the `Main menu` settings are missing in CR 116

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#31928]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/30747
CR 116 - In a narrow view mode the `Main menu` settings are missing in CR 116

## Steps to Reproduce

   1. Clean profile 1.58.51 - CR 116
   2. Set the browser in narrow view mode
   3. Click on `Main menu` 
   4. The settings are not shown

## Actual result:

![image](https://github.com/brave/brave-browser/assets/38657976/f7b55524-463c-42b4-a8bf-c339991b54e0)

## Expected result:

![image (1)](https://github.com/brave/brave-browser/assets/38657976/50ef3d86-1b0c-4081-b70a-2f85971afef4)

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.58.52 Chromium: 116.0.5845.51 (Official Build) nightly (64-bit)
-- | --
Revision | d5ec9991d084625358dae86ed02de8dc760d1985
OS | Windows 10 Version 22H2 (Build 19045.3208)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @rebron @mkarolin

**Comment by rebron** [comment]
cc: @fallaciousreasoning

**Comment by kjozwiak** [comment]
The above requires `1.57.42` or higher for `1.57.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.57.42 Chromium: 116.0.5845.51 (Official Build) (64-bit)
-- | --
Revision | e25036a089c476c56bf71774a898a1fee014e00d
OS | Windows 10 Version 22H2 (Build 19045.3208)

```
![image](https://github.com/brave/brave-browser/assets/38657976/e7169e11-4f89-4342-a978-5442f16c0435)
