### ISSUE TITLE
Issues with Token icons within account list item tokens stack

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#31923]
## Description 

- The token icons for tokens with a "placeholder" within account list item tokens stack is rendered with an abnormally large height.

- Solana Testnet tokens are rendered with the same icon as mainnet tokens.

## Steps to Reproduce

   1. Add goerli link to a wallet
   2. Add sol testnet/devnet tokens to a wallet
   3. view the accounts oage
   4. observe the rendered stack of tokens in the account list items

## Actual result:

![Screenshot 2023-07-27 at 11 01 42 AM](https://github.com/brave/brave-browser/assets/30185185/7129641c-3d65-4304-8002-a97c2c882bf2)

## Expected result:
Testnet icons should be rendered with a distinctive icon, or deduped with mainnet balances.
Placeholder icons for tokens should match the known token icons size

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.58.109 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | a4ad1fcdb550daf076384dbb280ae944274b3d35
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#19508](https://github.com/brave/brave-core/pull/19508)
- Verified tokens without an icon is shown correctly in accounts tab
- Encountered [#32666](https://github.com/brave/brave-browser/issues/32666)
![image](https://github.com/brave/brave-browser/assets/17010094/f7ff10bd-96d6-45cb-bc9b-c830f90dee35)
