### ISSUE TITLE
Adding a custom subscription list with a nonexistent URL crashes on Android

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#31938]
@tapanmodh noticed that adding a custom adblock subscription list with a random URL would cause the browser to crash, but only on Android.

Turns out https://github.com/brave/brave-browser/issues/28556 is back. We're [using](https://github.com/brave/brave-core/blob/d5673c71917c84b268319bdb1cc1a66f2a484d0d/components/brave_shields/browser/ad_block_subscription_filters_provider.cc#L49) `std::vector<T>::data()` [without](https://github.com/brave/brave-core/blob/d5673c71917c84b268319bdb1cc1a66f2a484d0d/components/adblock_rust_ffi/src/lib.rs#L129) a corresponding zero-length check.

**Comment by antonok-edm** [comment]
Looks like we're missing some zero-length checks in a few other FFI functions too.

I am praying for the imminent merge of https://github.com/brave/brave-core/pull/17368, but in the meantime https://github.com/brave/brave-core/pull/19462 will have to do.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 14` using the following build(s):

```
Brave | 1.57.50 Chromium: 116.0.5845.96 (Official Build) (64-bit)
--- | ---
Revision | dd68ca599736ea1ec946e2e9def70f3c705895e1
OS | Android 14; Build/UPB5.230623.003; 34; REL
```

Using the STR/Cases outlined via,https://github.com/brave/brave-browser/issues/32301#issue-1853629674, ensured that Brave wasn't crashing when adding `https://antonok.com/tmp/empty.txt` into `brave://adblock`. Restarted Brave several times and ensured there's no crashes/issues.

![Screenshot_20230819-002913](https://github.com/brave/brave-browser/assets/2602313/e14b5ee6-3727-4699-b2f4-97007e843b29)
