### ISSUE TITLE
Few upstream tests are failing when SYSTEM account is used (Windows)

### ISSUE THREAD

**Issue by goodov** [brave/brave-browser#31948]
disable these tests while we're investigating CI issues.
```
test-unit-chromium / All/ShortcutSubManagerExecuteTest.UpdateAppVerifyCorrectShortcuts/OSIntegrationSubManager
test-unit-chromium / LaunchModeRecorderTest.SlowModeChromeShortcut
test-unit-chromium / LaunchModeRecorderTest.SlowModeWebAppShortcut
```

the underlying issue most likely will be fixed as a part of https://github.com/brave/devops/issues/10172. we should be able to revert this when it'll be complete.

**Comment by LaurenWags** [comment]
@goodov this seems like it would be `QA/No` and `release-notes/exclude`, but could you confirm please?

cc @kjozwiak @rebron

**Comment by kjozwiak** [comment]
> @goodov this seems like it would be `QA/No` and `release-notes/exclude`, but could you confirm please?
> 
> cc @kjozwiak @rebron

Nothing for us to do in terms of verifications so labelled as `QA/No` & `release-notes/exclude` 👍
