### ISSUE TITLE
Update P3A metrics for search conversion

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#31941]
We updated search conversion UI and added more banner types via https://github.com/brave/brave-core/pull/19402
Previously we had one banner type but now we have four types of banner like below.
P3A metric should be updated to reflect this changes at components\brave_search_conversion\p3a.cc.
```
enum class ConversionType {
  kNone = 0,
  kButton,
  kBanner,  // deprecated.
  kNTP,
  kBannerTypeA,
  kBannerTypeB,
  kBannerTypeC,
  kBannerTypeD,
};
```

**Comment by simonhong** [comment]
cc @rebron @DJAndries

**Comment by DJAndries** [comment]
closing in favor of https://github.com/brave/brave-browser/issues/32130
