### ISSUE TITLE
Issues with EIP-1559 fee estimation on zksync (part 2)

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#31959]
zksync strikes back!

|Community|https://community.brave.com/t/zksync-era-failed-transactions-due-to-eip-1559-error|
-|-

It appears that zksync Era has finally implemented the [`eth_feeHistory`](https://docs.alchemy.com/reference/eth-feehistory) RPC, absence of which previously broke EIP-1559 fee estimation (https://github.com/brave/brave-browser/issues/30473), but the response breaks our parser. As a result, users are unable to transact on zksync anymore. See an example from syncswap below.

<img width="240" alt="Screenshot 2023-07-29 at 01 10 40" src="https://github.com/brave/brave-browser/assets/3684187/4ff28205-38cc-42e9-ae79-73900f655bf3">

On the bright side, getting fee estimates is now 2x faster on zksync.

**Comment by kjozwiak** [comment]
The above requires `1.56.18` or higher for `1.56.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.56.18 Chromium: 115.0.5790.138 (Official Build) (64-bit)
-- | --
Revision | 0567db0e7dcdfee5c109c167119ac2a92b9b3e1a-refs/branch-heads/5790_85@{#9}
OS | Windows 11 Version 22H2 (Build 22621.1992)

- Verified steps from [brave/brave-core#19481](https://github.com/brave/brave-core/pull/19481)
- Verified panel shows correct fee estimates for zksync transactions

https://github.com/brave/brave-browser/assets/17010094/bcf679ad-7203-4abd-b93d-a7f05c869e02
