### ISSUE TITLE
Unable to remove custom networks in settings

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#31953]
The option to remove a custom network that was previously added doesn't appear anymore in brave://settings/wallet/networks.

<img width="637" alt="Screenshot 2023-07-28 at 21 54 50" src="https://github.com/brave/brave-browser/assets/3684187/77cb83a8-a88c-47d2-9a11-6722dcced4f5">

**Comment by kjozwiak** [comment]
The above requires `1.56.120` or higher for `1.56.x` verification 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.56.20 Chromium: 115.0.5790.171 (Official Build) (64-bit)
-- | --
Revision | cf9067bf10d8f798c24643029af1d24e275646d6-refs/branch-heads/5790@{#1924}
OS | Windows 11 Version 22H2 (Build 22621.1992)
```

Using the STR/Cases outlined via https://github.com/brave/brave-core/pull/19533#issuecomment-1663216291, ensured that `Remove` is being displayed under the `hamburger menu` under `brave://settings/wallet/networks` when adding custom networks as per the following:

**`Example`** | **`Example`**
----------------|------------------
![image](https://github.com/brave/brave-browser/assets/2602313/0deb8c2a-20c2-4b3b-8dfb-fe0a8d14f893) | ![image](https://github.com/brave/brave-browser/assets/2602313/2e45d404-cff8-4c5f-9859-5f06fdaeeebf)

Also ensured that clicking on `Remove` removes the custom network without any issues/failures.
