### ISSUE TITLE
Hint for "Brave News" on "Brave Rewards" screen is too big and overlaps the text when device in Portrait Mode

### ISSUE THREAD

**Issue by vlad-hoff** [brave/brave-browser#31956]
## Description 

Hint for `Brave News` on `Brave Rewards` screen is too big and overlaps the text

## Steps to reproduce 

   1. Launch Brave
   2. Enable Staging server for `Brave Rewards`
   3. Enable Rewards > Open `Brave Rewards` settings screen
   4. Tap hint icon next to `Brave News` > Observe

## Actual result 

Hint for `Brave News` on `Brave Rewards` screen is too big and overlaps the text when device in `Portrait Mode`

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/0422af72-4160-4063-a20c-9c918b8a7e1d) | ![2](https://github.com/brave/brave-browser/assets/128532965/028ef1ff-b40e-47a1-abbf-c0fbb082c43a) |

## Expected result

There must be no overlapping text.

## Issue reproduces how often 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? No
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Pixel 7 [phone]
   - Android version: Android 14 [panther_beta-user 14 UPB4.230623.007 release-keys]
   
## Brave version

Brave build: 1.58.52 
Chromium: 116.0.5845.51 (Official Build) canary (64-bit) 
Revision: d5ec9991d084625358dae86ed02de8dc760d1985

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by Miyayes** [comment]
Let's just resolve the z-index problem.
