### ISSUE TITLE
Additional NTP is needed to show NTP SI in opt-in state when `initial_count_to_branded_wallpaper` is zero

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#31951]
Follow up to https://github.com/brave/brave-browser/issues/30974

In opt-in state user needs to open one more NTP compared to opt-out state when `initial_count_to_branded_wallpaper=0`

### opt-in
1. Clean profile
2. Run Brave with
```
--enable-features=BraveNTPBrandedWallpaper:initial_count_to_branded_wallpaper/0/count_to_branded_wallpaper/3,ShouldAlwaysTriggerBraveNewTabPageAdEvents
```
3. Enable rewards and ads
4. Open NTP

## Actual result:

NTP SI is not shown on 1st NTP
NTP SI is shown on 2nd NTP in opt-in state.
In opt-in state user needs to open one more NTP compared to opt-out state

Note: it behaves as if `initial_count_to_branded_wallpaper = 1`

## Expected result:
NTP SI is shown on 1st NTP

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.57.27 Chromium: 115.0.5790.114 (Official Build) beta (64-bit) 
-- | --
Revision | 18977fb43f693d5a8deeb48bd1cfa52651d3f73e
OS | Ubuntu 18.04 LTS

cc @tmancey @aseren

**Comment by tmancey** [comment]
There were no plans to set this to zero. Unless this is something that QA would need? Thanks

**Comment by btlechowski** [comment]
Reopened as dev team changed `initial_count_to_branded_wallpaper` to `0`  https://github.com/brave/brave-core/pull/19823#pullrequestreview-1591650329 cc @petemill 

Reproduced on 

Brave | 1.60.87 Chromium: 118.0.5993.70 (Official Build) beta (64-bit)
-- | --
Revision | 854c1e600054dfca6842cebaf729f100f4b0f066
OS | Linux

**Comment by btlechowski** [comment]
The point of this issue that when ads components are downloaded and initialized then opening first NTP should be NTP SI. This is not the case right now. 

If we ever want to change `initial_count_to_branded_wallpaper=0`, it will not work.
