### ISSUE TITLE
Add DNS-over-HTTPS P3A metrics

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#31965]
Add weekly P3A metrics for DNS-over-HTTPS usage.

"If you have secure DNS enabled, what setting are you using?"
`Brave.DNS.SecureSetting`

1. Current service provider
2. Predefined / custom provider

"If your secure DNS setting is set to "current service provider" and at least one DNS request was auto-upgraded in the past week, what percent of queries were made over DoH in the past week?"
`Brave.DNS.AutoSecureRequests`

0. Greater than 0%, less than 5%
1. Greater than 5%, less than 50%
2. Greater than 50%, less than 90%
3. Greater than 90%

**Comment by kjozwiak** [comment]
The above requires `1.60.98` or higher for `1.60.x` verification 👍

**Comment by kjozwiak** [comment]
Labelling as `QA/No` as we're pretty tight on time for `1.60.x`. The above was already verified on Nightly via https://github.com/brave/brave-core/pull/19479#issuecomment-1760990527 so it should work via `1.60.x`. @DJAndries please keep an eye on server-side and create and follow ups if there's any issues.

**Comment by bridiver** [comment]
Does this really have value to justify the patches? Why do we need to know this? It would be really helpful to have more information in the issue or some other link explaining why we are adding these and how they will be used. Don't they go through some kind of review process?

**Comment by DJAndries** [comment]
> Does this really have value to justify the patches? Why do we need to know this? It would be really helpful to have more information in the issue or some other link explaining why we are adding these and how they will be used. Don't they go through some kind of review process?

More info + review: https://bravesoftware.slack.com/archives/CDNJ9SVUL/p1687897087350139
