### ISSUE TITLE
`WireGuard` Brave VPN connection does *NOT* survive Windows restart

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#31966]
## Description 

`WireGuard` Brave VPN connection does **NOT** survive Windows restart

Found while testing https://github.com/brave/brave-browser/issues/30486

## Steps to Reproduce

   1. install `1.58.57`
   2. launch Brave
   3. enabled `WireGuard` support via `brave://flags`
   4. restart Brave
   5. purchase, configure, and connect to `Brave VPN`
   6. note that you're connected via WireGuard via the system-tray icon
   7. note that you're connected to `Brave VPN` via `https://whatismyipaddress.com`
   8. click on the `Windows`  logo
   9. click `Power`
   10. click `Restart`
   11. wait until Windows returns
   12. check to see if you're connected via `WireGuard` to `Brave VPN`

## Actual result:

Disconnected from `Brave VPN`; `WireGuard` also doesn't appear to be running

`initial WireGuard connection` | `step 11, after restart` | `relaunched Brave`
---------------|-------------------|----------
![image (2)](https://github.com/brave/brave-browser/assets/387249/ad9e71c4-9c7a-45c1-acf5-3449bf53830e) | ![image (1)](https://github.com/brave/brave-browser/assets/387249/f6b1c85f-19f7-498e-afef-3fa41323bb6b) | ![image](https://github.com/brave/brave-browser/assets/387249/51524274-fa33-4b8b-9870-84ffe9409e7c)

## Expected result:

Even though Brave was shut down and closed, `WireGuard` should have persisted the `Brave VPN` connection upon restart

![image (2)](https://github.com/brave/brave-browser/assets/387249/ad9e71c4-9c7a-45c1-acf5-3449bf53830e) 

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave	1.58.57 Chromium: 116.0.5845.51 (Official Build) nightly (64-bit) 
Revision	6c19156899db69697aa5667a5d61e8cf4a11f2f6
OS	Windows 10 Version 22H2 (Build 19045.3271)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

/cc @spylogsster @bsclifton @rebron @mattmcalister @simonhong @brave/qa-team

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.58.80 Chromium: 116.0.5845.51 (Official Build) nightly (64-bit)
-- | --
Revision | 4408cc9795df260c5d5f033660ce757782b53b32
OS | Windows 10 Version 22H2 (Build 19045.3324)
```

![image](https://github.com/brave/brave-browser/assets/387249/4c06d69b-a85e-4ec4-86e5-8b912adf1865) | reboot | after reboot

**Comment by stephendonner** [comment]
@MadhaviSeelam I didn't mark the above since we'll probably want a `Windows 11` verification, as per usual.  Mind adding the label once you get a chance to verify? Thanks!

**Comment by MadhaviSeelam** [comment]
Verification `In Progress` using
```
Brave | 1.58.91 Chromium: 116.0.5845.96 (Official Build) beta (64-bit)
-- | --
Revision | 620fa9c0307b294dd6e7c6b0976bc1f93fecf369
OS | Windows 11 Version 22H2 (Build 22621.2134)
```
### Steps:

1. installed `1.58.91`
2. launched Brave
3. enabled `Wireguard` via `brave://flags`
4. purchased, configured, and connected to `Brave VPN`
5. confirmed I was connected to `Brave VPN` via Wireguard
6. clicked the `Windows` logo
7. clicked the `Power` button
8. clicked the `Restart` button
9. waited for reboot
10. after reboot, took stock of the desktop and connection
11. confirmed I was connected to `Brave VPN` still via `Wireguard`
12. launched Brave
13. confirmed `Connected` status and IP address were from `Brave VPN`, via `whatismyipaddress.com`

step 3 | step 5 
<img width="951" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/184d80af-415a-42cc-9b51-9fd1dbc17576">
<img width="955" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/0558551e-14cc-4028-bed4-6e6fb8b5b0de">
