### ISSUE TITLE
Tabs title/favicon shifting to the left on hover after switching from Vertical Tabs to Horizontal

### ISSUE THREAD

**Issue by Emi-TheDhamphirInLoveUnderTheFrozenStar** [brave/brave-browser#31961]
## Description 

There is a tiny shift happening when you hover the tabs after switching from Vertical to Horizontal tabs.

1.58.57 Chromium: 116.0.5845.51 (Official Build) nightly (64-bit)
Windows 11 22H2

https://github.com/brave/brave-browser/assets/122518587/1a5732a4-b1cb-4f9f-b3b6-60c53718ed16

## Steps to Reproduce

   1. Right click on a Vertical Tab and uncheck `Use vertical tabs`
   2. hover on any tab on now in Horizontal mode
   3. The title will slightly shift to the left.

**Comment by Emi-TheDhamphirInLoveUnderTheFrozenStar** [comment]
@sangwoo108 
I noticed this also happens when opening the browser with horizontal tabs on, so not only switching causes it.

Also this happens when there is a tab with NTP (which means it has no favicon and just text), and then you switch from horizontal to vertical tabs, and the vertical tabstrip is expanded.

**Comment by Emi-TheDhamphirInLoveUnderTheFrozenStar** [comment]
well, I guess this doesn't matter and reporting this kind of stuff is useless, when it is obvious a problem that makes Brave looks unpolished.
I am really going to give up reporting anything since it is nonsense to think Developers missed this, and don't care to fix it.

**Comment by sangwoo108** [comment]
Hi, @Emi-TheDhamphirInLoveUnderTheFrozenStar . I'm really sorry for keeping you to wait too long. Somehow I didn't realize about this issue. 

>  I guess this doesn't matter and reporting this kind of stuff is useless, when it is obvious a problem that makes Brave looks unpolished.

I feel really bad for making you frustrated, and I sincerely apologize for that. The reason why we miss this kind of stuff doesn't mean that we're ignoring these. It could be just me, but I usually miss many newly opened issues unless I mentioned. I feel like we need better triage process so that new issues can be triaged and assigned properly.

And for my excuse, many developers are using their time on code editors and looking at the very limited feature that they're working on. Let's say I'm making a jump button in a game, then I would be jumping hundreds of time, rather than play the game from start to the end. Likewise, for now I'm working on the Playlist, I spend most of my time on clicking playlist. So please don't think we're ignoring the tiny details. And especially, your reporting with that quality always helps me a lot. I really appreciate that.

@bsclifton Could we have better triage process for issues that users open? Like, when OS-dekstop label is added, then assign someone automatically first so that they can assign a proper developer. Or batch newly opend issue about desktop and notify it to our slack?

**Comment by Emi-TheDhamphirInLoveUnderTheFrozenStar** [comment]
@sangwoo108
I apologize for my comment, it is not meant towards you, and didn't think you would read it, it just fell here, and when I was going to delete it and close the issue, I saw you commented on it.

But I know you are with Playlist and you have done a lot in my report for vertical tabs, you work hard on Brave, and it is good the 100% CPU issue got resolved so now I can truly use and test your work.

I guess I just can't stand reporting issues in generally in software too much and deal with developers and all that, because many don't care and then worrying about wording, screenshots, recording, testing, etc, so it properly so I don't report something that is not an issue.
The main problem is Brave Github Issues.... it is a complete mess and makes it hard to love it. Seeing 5K thousand issues opened and how it is random the way developers see the issues, take care of the issues, and work to fix the issues. Like seeing big bugs for months and even more than a year still not fixed, not like this one, a visual bug that many would even notice.

Tagging/forcing developers to read the issue, shouldn't be the case, sometimes I feel I am being annoying for tagging hoping to be seen.

But brave issues with all the duplicates posts not getting closed, non-issues reported as issues like if this was a forum or search engines didn't exist or community to seek the 'answer' before reporting, many times 'issues' being just user errors. People reporting in non-Nigthly versions where many times the issue was already fixed by either Chromium or Brave, many answered issues (questions), not being closed, because people don't accept the answer or don't understand what they are reporting is not accurate and insist on keep it an 'issue' or it is a behavior they don't like, like when Chromium removes a flag and complain about it.
I see the Issues page and wish I would never open it again.

But the worst part of reporting Brave bugs is the question "is it a Chromium or Brave issue?" and then I need to wait weeks for a new Chromium version to know if it was just Chromium or Brave. I have opened and closed some issues because of this.

I guess I think it is 'useless' to report bugs because they will not stop coming, it is an endless cycle, a new Chromium version, can break or fix things, and usually it does both.
I am usually not the type that creates feature request or anything, most of my issues are usually bug reports, but most of the time it feels like if I don't report a bug, it won't be fixed and then people on 'Stable' will complain and flame and trash Brave, because something is not working as expected.
Sometimes my reports are the most obvious bugs, like when Filter lists page wasn't working right and it was going to be pushed to stable builds, something easy to see, but I still had to report to get it fixed.

I mean, I see how MacOS and Linux has bugs that should have been easily noticed, reported and fixed before stable, but nobody did report like if nobody in those platforms are using Nightly. For example, non-US layout keyboards in MacOS having issues with Custom Shortcuts or how Linux was problems detecting dark mode.
Sometimes I feel I am forced to report, because I don't see many people reporting **real** issues, and I like Brave and I don't want it to fail and get more crap from haters than it deserves.

I still remove my comment. I mean, I try to be patient, but sometimes I can't, I see serious bugs (not reported by me) not getting the treatment and priority they need to have by other Brave developers. And then it seems like between old bugs, recent bugs and then new bugs that will appear... like an awful cycle to be trapped, especially from a perfectionist seeing the smallest tiny detail.

I apologize and hope you have a good day.

**Comment by sangwoo108** [comment]
Thanks @Emi-TheDhamphirInLoveUnderTheFrozenStar . I read your comment and no worries about me. I was to reply, but I guess you don't want to talk about it publicly. Let me escalate it to the team, and if you want to talk about it more, please feel free to email me - I tried to find yours, but I couldn't.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.60.81 Chromium: 118.0.5993.54 (Official Build) beta (64-bit)
-- | --
Revision | 1efb3f333eb41cc34af46ca31fb33c30e0afbfae
OS | Windows 11 Version 22H2 (Build 22621.2283)
```

Reproduced the issue in `1.58.137 Chromium: 117.0.5938.153` using STR from https://github.com/brave/brave-browser/issues/31961#issue-1827030761
<details>
https://github.com/brave/brave-browser/assets/98358127/798f5b99-6411-4a1c-a8a2-410be0756015
</details>

Steps: 
1. Installed 1.60.81
2. launched Brave
3. opened few tabs in horizontal view
4. enabled vertical tabs via context menu of a tab
5. clicked on minimize button to collapse vertical view panel
5. opened brave://settings/appearance 
6. unchecked `Expand vertical tabs panel on mouseover when collapsed` option
7. added few more tabs
8. unselected `Use vertical tabs` to switch to horizontal view
9. Try moving mouse over tabs

### Confirmed when mouse over tabs, favicon didn't move around in the collapsed mode
### Confirmed when mouse over tabs, favicon didn't move around in the mouseover` mode


https://github.com/brave/brave-browser/assets/98358127/2d6e64c9-6899-44ce-8183-41358cfbb0f1
