### ISSUE TITLE
Amend rewards tips sent P3A metric to report zero tips when applicable

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#31967]
Amend "tips sent" metric to report zero tips.

If you have Brave Rewards enabled with a custodial account connected, how many tips did you make in the past month?
`Brave.Rewards.TipsSent.2`

0. 0 tips
1. 1 tip
2. 2-3 tips
3. 4+ tips

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave | 1.58.90 Chromium: 116.0.5845.96 (Official Build) beta (64-bit)
-- | --
Revision | c112ad8c854bd34b48f4e87bfb3f7951e426a1d4
OS | Windows 10 Version 22H2 (Build 19045.3324)

```

**Comment by GeetaSarvadnya** [comment]
@DJAndries Test plan https://github.com/brave/brave-core/pull/19480 needs to be updated for the step 3 and 4. When 2 monthly tips and 2 one-time tips are sent, total tip count becomes 6 (when 2 monthly tips are sent by default 2 one times tips are also sent) 2 (monthly tips) + 4 (one-time tips) = 6 tips, the response value at step 3 should `3` and the response value at step 4 should be `2`

**Comment by GeetaSarvadnya** [comment]
>If you have Brave Rewards enabled with a custodial account connected, how many tips did you make in the past month? 

@DJAndries @Miyayes the condition `how many tips did you make in the past month?` this statement is applicable only for the monthly tips not for the one-time tips. Could you check the case below and let me know if this is the correct behavior?

- When we send one time tips and monthly tips to publishers, the one-time tips and monthly tips are shown under the `Contributions` and `Monthly Contributions` table respectively in brave://rewards pag, if we set the sys date ahead by `31 days` or begining of the next month (1st Sep) the one-time tips are NOT shown under the `Contributions` table hence the response value is always `0` as the one-time tips are shown only for the current month . But In case of monthly tips, the monthly tips are retained in the monthly contribution table and response value is shown as `1` or `2` based on the no of monthly tips set.

**Comment by DJAndries** [comment]
please see https://github.com/brave/brave-browser/issues/30350#issuecomment-1553995530

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Vivo x70 Pro version 12` running `Bravemonoarm64.apk_1.58.100`

- Verified the test plan from https://github.com/brave/brave-core/pull/19480

**_Important_**: When a monthly tip is sent one-time tip sent under the hood is NOT considered for the metrics calculation https://github.com/brave/brave-browser/issues/30350#issuecomment-1553995530

<details>
<summary>Brave.Rewards.TipsSent.2 = Metrics not shown_PASSED</summary>

1. Clean profile 1.58.x
2. Enable rewards
3. Open brave://local-state file
4. Look for the metrics `Brave.Rewards.TipsSent.2`
5. Confirmed that the metrics `Brave.Rewards.TipsSent.2` is NOT shown under the local state file

Example | Example
----------|----------
![image](https://github.com/brave/brave-browser/assets/38657976/92dce930-17ff-46a4-bb3e-bb441960e5bd) | ![image](https://github.com/brave/brave-browser/assets/38657976/835aa038-ba7f-48e3-919e-e7cd9714dc81)


</details>

<details>
<summary>Brave.Rewards.TipsSent.2 = 0_PASSED</summary>

1. Clean profile 1.58.x
2. Enable rewards
3. Connect to a custodian
4. Restart the browser
5. Wait for 30 secs
6. Open brave://local-state file
7. Look for the metrics `Brave.Rewards.TipsSent.2`
8. Confirmed that the metrics `Brave.Rewards.TipsSent.2` response value is `0` as expected

Example | Example
----------|----------
![image](https://github.com/brave/brave-browser/assets/38657976/fb0c3087-2f90-4a52-ab4e-2857a2a3d86f) | ![image](https://github.com/brave/brave-browser/assets/38657976/3b0a9be5-8187-4941-9a30-54d17457c219)

</details>

<details>
<summary>Brave.Rewards.TipsSent.2 = 1_PASSED</summary>

<details>
<summary>Case 1: Send a one-time tip_PASSED</summary>

1. Clean profile 1.58.x
2. Enable rewards
3. Connect to a custodian
4. Send a one-time tip to a verified pubs laurenwags.github.io
5. Confirmed that one-time tip is shown under the `Contributions` panel
6. Open brave://local-state 
7. Look for the metrics `Brave.Rewards.TipsSent.2` (if metrics is not shown restart the browser and wait for 30 secs)
8. Confirmed that the metrics `Brave.Rewards.TipsSent.2` response value is `1` `1 tip` as expected 

![image](https://github.com/brave/brave-browser/assets/38657976/13f42eef-a7ee-40e5-bc6f-01a367b9b118)

</details>

<details>
<summary>Case 2: Send a monthly tip_PASSED</summary>

**Note**: When a monthly tip is sent one-time tip sent under the hood is NOT considered for the metrics calculation 

1. Clean profile 1.58.x
2. Enable rewards
3. Connect to a custodian
4. Send a monthly tip to a verified pubs laurenwags.github.io
5. Confirmed that monthly tip is shown under the `Monthly Contributions` panel
6. Open brave://local-state 
7. Look for the metrics `Brave.Rewards.TipsSent.2` (if metrics is not shown restart the browser and wait for 30 secs)
8. Confirmed that the metrics `Brave.Rewards.TipsSent.2` response value is `1` `1 tip` as expected 

</details>

</details>

<details>
<summary>Brave.Rewards.TipsSent.2 = 2_PASSED</summary>

1. Clean profile 1.58.x
2. Enable rewards
3. Connect to a custodian
4. Send 2 one-time tip to a verified pubs laurenwags.github.io
5. Confirmed that one-time tips are shown under the `Contributions` panel
6. Open brave://local-state 
7. Look for the metrics `Brave.Rewards.TipsSent.2` (if metrics is not shown restart the browser and wait for 30 secs)
8. Confirmed that the metrics `Brave.Rewards.TipsSent.2` response value is `2` `2 -3 tips` as expected 

![image](https://github.com/brave/brave-browser/assets/38657976/e0e013c1-d986-4c03-a21f-4311425c9c13)

</details>

<details>
<summary>Brave.Rewards.TipsSent.2 = 3_PASSED</summary>

1. Clean profile 1.58.x
2. Enable rewards
3. Connect to a custodian
4. Send 3 monthly tips or 3 one-time tips to a verified pubs laurenwags.github.io
5. Confirmed that monthly tips are shown under the `Monthly contributions` panel
6. Open brave://local-state 
7. Look for the metrics `Brave.Rewards.TipsSent.2` (if metrics is not shown restart the browser and wait for 30 secs)
8. Confirmed that the metrics `Brave.Rewards.TipsSent.2` response value is `2` `2-3 tips` as expected 

![image](https://github.com/brave/brave-browser/assets/38657976/1d29fb63-0a59-4cc8-9d37-7d35bbb9dd52)

</details>

<details>
<summary>Test plan scenarios_PASSED</summary>

<details>
<summary>Case 1: Sent one-time and monthly tip and set sys date ahead by 31 days_PASSED</summary>

**Note**: When a monthly tip is sent one-time tip sent under the hood is NOT considered for the metrics calculation

1.Set sys date to 1st Aug, clean profile 1.58.x
2. Enable rewards
3. Connect to a custodian
4. Send a one-time tip and a monthly tip to a verified pubs laurenwags.github.io
5. Confirmed that one-time tip and monthly tip is shown under the `Contributions` and `Monthly contributions` panel respectively
6. Open brave://local-state 
7. Look for the metrics `Brave.Rewards.TipsSent.2` (if metrics is not shown restart the browser and wait for 30 secs)
8. Confirmed that the metrics `Brave.Rewards.TipsSent.2` response value is `2` `2 tip` as expected  (1 one-time tip + 1 monthly)
9. Close the browser 
10. Set the sys date ahead by 30 days (i.e Aug 30)
11. Reluanch the browser
12. Open brave://rewrads and confirmed that one-time tip is not shown in the Contributions panel
13. Reload brave://local-state file
14.  Confirmed that the metrics `Brave.Rewards.TipsSent.2` response value is `2` as expected
15. Close the browser 
16. Set the sys date ahead by 31 days (i.e Aug 31)
17. Reluanch the browser
18. Reload brave://local-state file
19. Confirmed that the metrics `Brave.Rewards.TipsSent.2` response value is `1` as expected (1 monthly tip)

</details>

<details>
<summary>Case 2: Sent one-time tips and set sys date ahead by 31 days_PASSED</summary>

1.Set sys date to 1st Aug, clean profile 1.58.x
2. Enable rewards
3. Connect to a custodian
4. Send a one-time tip to a verified pubs laurenwags.github.io
5. Confirmed that one-time tip is shown under the `Contributions` panel
6. Open brave://local-state 
7. Look for the metrics `Brave.Rewards.TipsSent.2` (if metrics is not shown restart the browser and wait for 30 secs)
8. Confirmed that the metrics `Brave.Rewards.TipsSent.2` response value is `1` `1 tip` as expected 
9. Close the browser 
10. Set the sys date ahead by 31 days (i.e Aug 31)
11. Reluanch the browser
12. Open brave://rewrads and confirmed that one-time tip is not shown in the Contributions panel
13. Reload brave://local-state file
14. Confirmed that the metrics `Brave.Rewards.TipsSent.2` response value is `0` as expected

</details>

<details>
<summary>Case 3: Sent 2 one-time tips and 2 monthly tips and set sys date ahead by 31 days_PASSED</summary>

**Note**: When a monthly tip is sent one-time tip sent under the hood is NOT considered for the metrics calculation

1.Set sys date to 1st Aug, clean profile 1.58.x
2. Enable rewards
3. Connect to a custodian
4. Send 2 - one-time tips and 2 - monthly tips to a verified pubs laurenwags.github.io
5. Confirmed that one-time tip and monthly contributions shown under the `Contributions` and `Monthly contributions` panel
6. Open brave://local-state 
7. Look for the metrics `Brave.Rewards.TipsSent.2` (if metrics is not shown restart the browser and wait for 30 secs)
8. Confirmed that the metrics `Brave.Rewards.TipsSent.2` response value is `3` `4+ tip` as expected (total tips sent is 4)
9. Close the browser 
10. Set the sys date ahead by 31 days  (i.e Aug 31)
11. Reluanch the browser
12. Reload brave://local-state file
13. Confirmed that the metrics `Brave.Rewards.TipsSent.2` response value is `2` as expected (2 monthly tips )

</details>


</details>
