### ISSUE TITLE
Do not download language resources if notification ads are opted-out

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#31963]

**Comment by kjozwiak** [comment]
The above requires `1.57.35` or higher for `1.57.x` verification 👍

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.57.36 Chromium: 115.0.5790.171 (Official Build) beta (64-bit) 
-- | --
Revision | a4bb683f14dc402f5da13707e13559dc4d5ef08b
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-core/pull/19478

Verified `ocilmpijebaopmdifcomolmpigakocmo` is not downloaded on clean profile
![image](https://github.com/brave/brave-browser/assets/34715963/7cdcd43e-b4c5-43ad-8054-7b2ae46a81a6)


Verified `ocilmpijebaopmdifcomolmpigakocmo` is downloaded after enabling rewards
![image](https://github.com/brave/brave-browser/assets/34715963/810af509-c091-4c37-8001-4c7aa046b8ae)


Verified `text processing` resource is loaded: Successfully loaded `feibnmjhecfbjpeciancnchbmlobenjn` text classification resource
```
[14525:14525:0804/215420.141911:VERBOSE1:text_classification_resource.cc(74)] Successfully loaded feibnmjhecfbjpeciancnchbmlobenjn text classification resource

```

Verified `text embedding` resource is loaded: Successfully loaded `wtpwsrqtjxmfdwaymauprezkunxprysm` text embedding resource

```
[14525:14525:0804/215419.527803:VERBOSE1:text_embedding_resource.cc(73)] Successfully loaded wtpwsrqtjxmfdwaymauprezkunxprysm text embedding resource

```

**Comment by Uni-verse** [comment]
Removing `OS/Android` label as this cannot be tested on Android at this time due to restricted access to file system.

**Comment by btlechowski** [comment]
Verification passed on Brave v1.57.47 on Lenovo TB-8506FS (Android 11.0)

Verified test plan from https://github.com/brave/brave-core/pull/19478

Verified through Charles that non of the components downloaded are `ocilmpijebaopmdifcomolmpigakocmo`
Example:
![image](https://github.com/brave/brave-browser/assets/34715963/7b423235-486b-4106-88d8-f859336ca684)

Verified that `ocilmpijebaopmdifcomolmpigakocmo` component is downloaded after enabling rewards
![image](https://github.com/brave/brave-browser/assets/34715963/245ac823-fda4-47df-b23b-908337a51a82)

Verified `text processing` resource is loaded: Successfully loaded `feibnmjhecfbjpeciancnchbmlobenjn` text classification resource
```
14:41:07.793  V  [VERBOSE1:text_classification_resource.cc(74)] Successfully loaded feibnmjhecfbjpeciancnchbmlobenjn text classification resource
```

Verified `text embedding` resource is loaded: Successfully loaded `wtpwsrqtjxmfdwaymauprezkunxprysm` text embedding resource

```
14:41:07.069  V  [VERBOSE1:text_embedding_resource.cc(73)] Successfully loaded wtpwsrqtjxmfdwaymauprezkunxprysm text embedding resource

```
