### ISSUE TITLE
Window control's size isn't updated when switching tab strip orientation

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#31971]
Original report: https://github.com/brave/brave-browser/issues/31908#issuecomment-1656404430
by @Emi-TheDhamphirInLoveUnderTheFrozenStar

```
Also, I noticed a tiny little visual bug when the title bar is showing. The window buttons hovering effect, when the window is maximized and you switch tabs from Horizontal / Vertical mode. The height between the title bar in Horizontal Mode is different than the one in Vertical tabs, causing the Window buttons hovering effect to not change height and then causing some overlap the toolbar buttons from horizontal -> vertical) or being smaller from vertical to horizontal.

The only way to fix it is to change window size and maximize it again.

I show both situations, because the size of the hovering effect changes depending on if the window was opened with Horizontal tabs or Vertical tabs.
```

Opening window in Horizontal tabs and switching to Vertical:

https://github.com/brave/brave-browser/assets/122518587/5dd72cd9-eda1-47af-a341-dbbc2d2ec543

Opening window with Vertical tabs and switching to Horizontal:

https://github.com/brave/brave-browser/assets/122518587/ed9c909c-3823-463d-8b89-731503fd6de6

**Comment by sangwoo108** [comment]
When the a window is maximized, then maybe switching orientation wouldn't trigger relayout.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.58.88 Chromium: 116.0.5845.82 (Official Build) beta (64-bit)
-- | --
Revision | acf16e35d5897fd4bf9b1b5a93b56aff2ed64bba
OS | Windows 11 Version 22H2 (Build 22621.2134)
```


Reproduced the issue in 1.57.47 

Verified the issue with the testplan from https://github.com/brave/brave-core/pull/19488#issue-1828519172

Install 1.58.88
launch Brave
Confirmed window controls, minimize, restore, close, did not overlap with toolbar
When vertical tabs is enabled with show window title  unchecked 
When vertical tabs is enabled with show window title checked
When vertical tabs is not enabled 
when 
turned off "show window title" and "Use vertical tab option"
Maximize the window
Turn on "Use vertical tab" and "Show window title"
The window controls, such as minimize, restore, close, shouldn't overlap with toolbar


https://github.com/brave/brave-browser/assets/98358127/6db7b074-1446-4607-8548-1e86e1865d4d
