### ISSUE TITLE
Development of floating tab on brave browser V 1.0.72

### ISSUE THREAD

**Issue by peerzadaaabid** [brave/brave-browser#3197]
## Description 
Development of floating tab V 1.0.72

## Steps to Reproduce

   1. Just develop a floating tab in options
   2. After clicking on this tab the,the small head like structure should open in home screen
   
![img_20190202_131046](https://user-images.githubusercontent.com/45705767/52161722-92983a80-26ef-11e9-91be-4a95e3f4f27d.jpg)

# Actual result:
I found that there is nothing like floating tab in mentioned browser

## Expected result:
A man can access other functions too, during using brave browser. ko
![img_20190202_130752](https://user-images.githubusercontent.com/45705767/52161728-b8254400-26ef-11e9-9026-1d53b5699d0d.jpg)

## Brave version (brave://version info)
Brave version 1.0.72 Chromium 71.0.3578.99
0S  Android 7.1.2

**Comment by eljuno** [comment]
You may want to open it on https://github.com/brave/browser-android-tabs/issues because this repo is for desktop version.

Or community.brave.com for more user-friendly forum.
