### ISSUE TITLE
Auto-fill Coingecko IDs while adding custom tokens

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#31975]
Thanks to https://github.com/brave/token-lists/pull/71, we now have access to all possible Coingecko IDs mapped for each chain ID and contract address pair.

### Definition of done

- The Coingecko ID field gets pre-filled when adding a custom token under Visible Assets
- The Coingecko ID is inferred automatically when adding a custom token through `wallet_watchAsset` method.

<img width="420" alt="Screenshot 2023-07-31 at 11 33 43" src="https://github.com/brave/brave-browser/assets/3684187/f74546b0-94e6-472b-a755-332390446718">

**Comment by srirambv** [comment]
Verification passed on  

Brave | 1.58.100 Chromium: 116.0.5845.114 (Official Build) beta (64-bit)
-- | --
Revision | a8c0058265009a1858c4502b9ba413671fbb61e1
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#19489](https://github.com/brave/brave-core/pull/19489)
- Verified CoinGecko ID is auto populated when adding custom tokens

https://github.com/brave/brave-browser/assets/17010094/f7cf8450-5b53-4b3b-b608-ad38b3e1e3d9
