### ISSUE TITLE
Codesign Windows delta update files

### ISSUE THREAD

**Issue by mherrmann** [brave/brave-browser#31977]
## Description 

Our delta update installers are currently not code-signed. This is not user-visible because they are downloaded and executed programatically. But as a security measure, they should be codesigned.

## Steps to Reproduce

We produce delta installers between subsequent _public_ releases. For example, at the time of this writing, the Nightly releases are:

```
Nightly v1.58.49 (Chromium 115.0.5790.114)		v1.58.49
Nightly v1.58.48 (Chromium 115.0.5790.136)	Pre-release	
Nightly v1.58.47 (Chromium 115.0.5790.136)	Pre-release	
Nightly v1.58.46 (Chromium 115.0.5790.136)		v1.58.46
```

So v1.58.46 and v1.58.49 are the public releases. This means that we have a delta installer that takes users from .46 to .49. .47 and .48 are not public releases, so there is no delta update for them.

The delta update installers have URL `https://updates-cdn.bravesoftware.com/delta/Brave-Browser-<Channel>/<channel>/win/<new version>/<old version>/brave_installer-delta-x64.exe`. For Nightly, the Channel is `Nightly` and channel is `x64-ni`. So in the above example, the delta update installer to go from .46 to .49 has URL https://updates-cdn.bravesoftware.com/delta/Brave-Browser-Nightly/x64-ni/win/115.1.58.49/115.1.58.46/brave_installer-delta-x64.exe.

For Beta, the Channel is Beta and channel is `x64-be`. For release, the application is `Brave-Browser` and the channel is `x64-rel`.

## Actual result:

Delta update installers are not code signed. This can be checked in Windows Explorer by rightclicking on the file, selecting Properties and then Digital Signatures.

## Expected result:

They should be codesigned.

## Reproduces how often: 

Always.

**Comment by DesertBear** [comment]
@mherrmann 


There's definitely something odd happening with Brave code-signing recently.  In the current Brave Stable (115.1.56.20), it is now not just the delta installer that isn't code-signed, but some other executables are now also not digitally-signed as well.


**PowerShell script (run as administrator):**
```
# Path
$Path = @(
    "$env:ProgramFiles\BraveSoftware"
    "${env:ProgramFiles(x86)}\BraveSoftware"
    "$env:AllUsersProfile\BraveSoftware"
    "$env:LocalAppData\BraveSoftware"
)

# Run
Get-ChildItem -Recurse -File -Path $Path | 
Where-Object { ($_.Extension -eq ".exe") -or ($_.Extension -eq ".dll") } | 
Get-AuthenticodeSignature | 
Where-Object { ($_.Status -ne "Valid") } | 
Format-List -Property Path, Status, StatusMessage, SignatureType, IsOSBinary, SignerCertificate
```

**PowerShell results:**
```
Path              : C:\Program Files\BraveSoftware\Brave-Browser\Application\115.1.56.20\Installer\chrmstp.exe
Status            : NotSigned

Path              : C:\Program Files\BraveSoftware\Brave-Browser\Application\115.1.56.20\Installer\setup.exe
Status            : NotSigned

Path              : C:\Program Files (x86)\BraveSoftware\Update\Download\{AFE6A462-C574-4B8A-AF43-4CC60DF4563B}\115.1.56.20\brave_installer-delta-x64.exe
Status            : NotSigned
```

**Brave version:**
```
Brave:    1.56.20 Chromium: 115.0.5790.171 (Official Build) (64-bit) 
Revision: cf9067bf10d8f798c24643029af1d24e275646d6-refs/branch-heads/5790@{#1924}
OS:       Windows 10 Version 22H2 (Build 19045.3208)
```

**Comment by mherrmann** [comment]
Thank you for reporting @DesertBear ! We will investigate.

**Comment by mherrmann** [comment]
I cannot reproduce after a clean install for `chrmstp.exe` and `setup.exe`:

```
PS C:\Windows\system32> Get-AuthenticodeSignature -FilePath "C:\Program Files\BraveSoftware\Brave-Browser\Application\115.1.56.20\Installer\chrmstp.exe"


    Directory: C:\Program Files\BraveSoftware\Brave-Browser\Application\115.1.56.20\Installer


SignerCertificate                         Status                                 Path
-----------------                         ------                                 ----
8903F2BD47465A4F0F080AA7CEEC31A31B74DE42  Valid                                  chrmstp.exe


PS C:\Windows\system32> Get-AuthenticodeSignature -FilePath "C:\Program Files\BraveSoftware\Brave-Browser\Application\115.1.56.20\Installer\setup.exe"


    Directory: C:\Program Files\BraveSoftware\Brave-Browser\Application\115.1.56.20\Installer


SignerCertificate                         Status                                 Path
-----------------                         ------                                 ----
8903F2BD47465A4F0F080AA7CEEC31A31B74DE42  Valid                                  setup.exe
```

Maybe the problem only appears after a (delta) update.

**Comment by kjozwiak** [comment]
@LaurenWags @brave/qa-team as per the discussion via https://bravesoftware.slack.com/archives/CHGKGMHDJ/p1692594877479669, we won't be able to verify the above with `1.57.x` RC builds. So what we'll need to do is basically run through https://github.com/brave/brave-core/pull/19659#issuecomment-1697979753 but on `Beta`. If that works, then both `Nightly` & `Beta` are working as expected. In theory, the above is low risk so it should work on `Release`. Worst case, we can just disable `delta` upgrades on `Release`. I started `1.58.107` on `Win` only so we'll have new builds with the above fix on `Beta`.

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.58.107 Chromium: 116.0.5845.114 (Official Build) beta (64-bit)
-- | --
Revision | 7d50fba6a1cbc12ba13e1c675e2298d5721458f6
OS | Windows 10 Version 22H2 (Build 19045.3324)

```

**Comment by MadhaviSeelam** [comment]
Verification `In progress`



Quick note: as of writing/running through the above, the current public beta version is 1.58.108. The previous public beta version was 1.58.106

1. using the information from https://github.com/brave/brave-browser/issues/29474, downloaded/installed `1.58.106`
2. once installed, closed Brave and setup logging following https://github.com/brave/brave-browser/wiki/Desktop-Release-Checklist#enabling-logging-to-check-delta-upgrades-on-win-x64--win-x86
3. once logging has been setup, launched Brave and initiated an update via `brave://settings/help`





step 1
----
<img width="730" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/45ec72c3-7b9e-4402-aaa4-9ca2af5807bb">

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 10 x86` using the following build(s):

```
Brave | 1.58.107 Chromium: 116.0.5845.114 (Official Build) beta (32-bit)
-- | --
Revision | 7d50fba6a1cbc12ba13e1c675e2298d5721458f6
OS | Windows 10 Version 22H2 (Build 19045.3393)
```

Quick note: as of writing/running through the above, the current `BETA` version is `1.58.107 Chromium: 116.0.5845.114`. The previous release version was `1.58.106 Chromium: 116.0.5845.114`.

* using the information from https://github.com/brave/brave-browser/issues/29474, downloaded/installed `1.58.106 Chromium: 116.0.5845.114`.
* once installed, closed Brave and setup logging following https://github.com/brave/brave-browser/wiki/Desktop-Release-Checklist#enabling-logging-to-check-delta-upgrades-on-win-x64--win-x86
* once logging has been setup, launched Brave and initiated an update via `brave://settings/help`
* checked and ensured that `C:\Program Files\BraveSoftware\Update\Download\{103BD053-949B-43A8-9120-2E424887DE11}\116.1.58.107\brave_installer-delta-ia32.exe` was codesigned
* checked `C:\ProgramData\BraveSoftware\Update\Log\BraveUpdate.log` and ensured that `brave_installer-delta-ia32.exe` is mentioned as per the following:

**`Quick Note:`** Ensure that there's no mention of `brave_installer.exe` in the logs other than `brave_installer-delta-ia32.exe`. This basically indicates that the `delta` was used and Brave didn't fall back on `brave_installer.exe`.

```
[08/30/23 13:14:54.377][BraveUpdate:goopdate][9636:3796][Installing][display name: Brave Beta][app id: {103BD053-949B-43A8-9120-2E424887DE11}][installer path: C:\Program Files\BraveSoftware\Update\Install\{C1456C4A-458F-44BC-AD73-80E8F9039087}\brave_installer-delta-ia32.exe][manifest args: --chrome-beta][installer data: ][untrusted data: ][priority: 10]
[08/30/23 13:14:54.378][BraveUpdate:goopdate][9636:3796][Running installer][C:\Program Files\BraveSoftware\Update\Install\{C1456C4A-458F-44BC-AD73-80E8F9039087}\brave_installer-delta-ia32.exe][--chrome-beta][{103BD053-949B-43A8-9120-2E424887DE11}]
[08/30/23 13:15:11.747][BraveUpdate:goopdate][9636:3796][InstallerResult][{103BD053-949B-43A8-9120-2E424887DE11}][0]
[08/30/23 13:15:11.747][BraveUpdate:goopdate][9636:3796][InstallApp returned][0x0][{103BD053-949B-43A8-9120-2E424887DE11}][type:1][code: 30][][]
[08/30/23 13:15:11.800][BraveUpdate:goopdate][9636:3796][Started process][9080]
[08/30/23 13:15:11.807][BraveCrashHandler][9080:9260][ConfigManager::LoadGroupPolicies][Machine is not Enterprise Managed]
[08/30/23 13:15:11.807][BraveCrashHandler][9080:9260][ConfigManager::LoadGroupPolicies][No Group Policies found under key][HKLM\Software\Policies\BraveSoftware\Update\]
[08/30/23 13:15:11.807][BraveCrashHandler][9080:9260][OmahaPolicyManager::set_policy][Group Policy][[CachedOmahaPolicy][is_initialized][0][is_managed][0][auto_update_check_period_minutes][-1][download_preference][][cache_size_limit][-1][cache_life_limit][-1][updates_suppressed][-1][-1][-1][proxy_mode][][proxy_server][][proxy_pac_url][][install_default][-1][update_default][-1]]
[08/30/23 13:15:11.809][BraveCrashHandler][9080:9260][CrashHandler::RunUntilShutdown]
[08/30/23 13:15:11.964][BraveUpdate:goopdate][6768:3968][DllEntry exit][0x00000000]
```

* Updated Brave via `brave://settings/help` by clicking on `Relaunch`
* ensured that Brave was updated to `1.58.107 Chromium: 116.0.5845.114` without any issues/failures
* ensured that you can relaunch Brave several times without any issues/crashes

**`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------
![image](https://github.com/brave/brave-browser/assets/2602313/ad1254e0-8c7b-4471-b001-faf419d1645d) | ![image](https://github.com/brave/brave-browser/assets/2602313/5677b63a-d53c-46b0-873c-463eec180226) | ![image](https://github.com/brave/brave-browser/assets/2602313/454bff65-cd82-4777-909c-7ff9c75dab90)

Using the information/guide from https://github.com/brave/brave-browser/issues/31977#issue-1828603967, downloaded the `delta` via https://updates-cdn.bravesoftware.com/delta/Brave-Browser-Beta/x86-be/win/116.1.58.107/116.1.58.106/brave_installer-delta-ia32.exe and ensured that the `delta` has been codesigned as per the following:

![image](https://github.com/brave/brave-browser/assets/2602313/5d5b8227-0dd8-4cc9-9e69-dcb9a6afa462)
