### ISSUE TITLE
Panel doesn't list all Swap details 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#31982]
## Description 

Panel doesn't list any Swap details for Ethereum transactions

## Steps to Reproduce

Ethereum Swaps

   1. Submit a Swap transaction on Ethereum network
   2. Open panel and open Activity 
   3. Doesn't show the Swap from and to tokens details 

Solana Swaps
   1. Submit a Swap transaction on Solana Mainnet network
   2. Open panel and open Activity
   3. For Swap to it just show blank

## Actual result:

https://github.com/brave/brave-browser/assets/17010094/19659a92-8183-4b7c-9100-7a47f598a0ec

## Expected result:
Show swap details

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.57.27 Chromium: 115.0.5790.114 (Official Build) beta (64-bit)
-- | --
Revision | 18977fb43f693d5a8deeb48bd1cfa52651d3f73e
OS | Windows 11 Version 22H2 (Build 22621.1992)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Not checked

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @onyb @Douglashdaniel @josheleonard

**Comment by kjozwiak** [comment]
Closing as the above was fixed via https://github.com/brave/brave-core/pull/19149 and uplifted into `1.57.x` via https://github.com/brave/brave-core/pull/19534. The above requires `1.57.41` or higher for `1.57.x` verification 👍

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/31456#issuecomment-1671125765
