### ISSUE TITLE
Token balance doesn't automatically update after a transaction is completed

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#31980]
## Description 

Token balance doesn't automatically update after a transaction is completed

## Steps to Reproduce

   1. Initiate a Swap transaction for any token on any network
   2. Wait till the token swap is completed
   3. Token balance remains same as before Swap transaction, only updates after a page refresh or reselecting the token 

## Actual result:

https://github.com/brave/brave-browser/assets/17010094/740c028a-deee-46fa-8d39-708bd589d484

## Expected result:
Should auto update token balance when a transaction is successful

## Reproduces how often: 

Easy

## Brave version (brave://version info)

All

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @onyb @Douglashdaniel @josheleonard

**Comment by josheleonard** [comment]
@srirambv, is this still valid?

**Comment by srirambv** [comment]
This is fixed as part of https://github.com/brave/brave-browser/issues/37610
