### ISSUE TITLE
PDF files are not opening in brave, they get downloaded

### ISSUE THREAD

**Issue by TontyTon** [brave/brave-browser#3198]
## Description 

PDF files are not opening in brave, they get downloaded. I have checked the setting '_Download PDF files instead of automatically opening them in Brave_' is disabled. Have been experiencing this issue since version 0.58.21 .

## Steps to Reproduce

   1. Open any pdf file on computer or online
    

## Actual result:

pdf file gets downloaded

## Expected result:
pdf file is shown

## Reproduces how often: 

always

## Brave version (brave://version info)

Brave | 0.59.34 Chromium: 72.0.3626.81 (Official Build) (64-bit)
-- | --
OS | Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? no
- Is the issue reproducible on the latest version of Chrome?  not relevent

**Comment by TontyTon** [comment]
@srirambv Use **any** pdf, offline or online.

---
Tried reinstalling, but same problem persists.

**Comment by srirambv** [comment]
Cant reproduce on release build. Do you mind recording the steps that you are following. 
![vokoscreen20190204_202941](https://user-images.githubusercontent.com/17010094/52216555-857c7680-28bc-11e9-978f-58d5f3dfb279.gif)

**Comment by TontyTon** [comment]
Here it is
![vr](https://user-images.githubusercontent.com/35778430/52278641-83c6b780-297d-11e9-95ce-67be7bfb48d0.gif)


---
by the way, which screen recorder did you used

**Comment by rebron** [comment]
@TontyTon can you open brave://components/ and see if this is installed: PDF Viewer (PDF.js) - Version: 2.0.673

**Comment by TontyTon** [comment]
In brave://components/ PDF Viewer was on version 0.0.0, that is it was not installed. Si, updated it and PDF Viewer is now working fine.

BUT why the problem was not solved on reinstalling or updating. Also the component should have auto updated.

BTW Now the problem is solved. Thanks @rebron
