### ISSUE TITLE
Sometimes unblinded tokens are not refilled on clean profile after enabling rewards

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#31985]
There seems to be race condition when unblinded token are not refilled till browser restart
This is a regression in 1.58.x

## Steps to Reproduce

1. Clean profile
1. Run Brave with:
```
--enable-logging=stderr --vmodule="*/variations/*"=6,"*/bat-native-ledger/*"=6,"*/brave_rewards/*"=6,"*/bat-native-ads/*"=6,"*bat-native-confirmations/*"=6,"*/brave_ads/*"=9,"*/brave_user_model/*"=6,"*/bat_ads/*"=6,"*/whats_new/*"=9 --variations-server-url=https://variations.bravesoftware.com/seed1 --rewards=staging=true,debug=true --use-dev-goupdater-url --enable-features=ShouldAlwaysRunBraveAdsService,ShouldAlwaysTriggerBraveSearchResultAdEvents,ShouldLaunchBraveAdsAsInProcessService,ShouldSupportSearchResultAds,BraveNTPBrandedWallpaper:initial_count_to_branded_wallpaper/0/count_to_branded_wallpaper/0,ShouldAlwaysTriggerBraveNewTabPageAdEvents,CustomNotificationAds
```
3. Enable rewards
1. Check the logs

## Actual result:

unblinded tokens are not refilled
Check the logs:
[31985.txt](https://github.com/brave/brave-browser/files/12214354/31985.txt)

## Expected result:
unblinded tokens are refilled

## Reproduces how often: 

Intermittent issue

## Brave version (brave://version info)

Brave | 1.58.60 Chromium: 116.0.5845.51 (Official Build) nightly (64-bit)
-- | --
Revision | aac052a4468918f949ea940b88865764a72cea14
OS | Linux

cc @tmancey @aseren

**Comment by kjozwiak** [comment]
The above requires `1.57.35` or higher for `1.57.x` verification 👍

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.57.36 Chromium: 115.0.5790.171 (Official Build) beta (64-bit) 
-- | --
Revision | a4bb683f14dc402f5da13707e13559dc4d5ef08b
OS | Ubuntu 18.04 LTS

Verified test plan from https://github.com/brave/brave-browser/issues/31985#issue-1828949112

Verified that unblinded tokens are always refilled. Verified 10 times
```
[14077:14077:0804/214344.029856:VERBOSE1:refill_unblinded_tokens.cc(339)] Added 50 unblinded tokens, you now have 50 unblinded tokens

```
