### ISSUE TITLE
Crashing when picking `Open Guest Profile`

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#31997]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

## Version info
Brave Version: 1.58.52 Chromium: 116.0.5845.51
Operating System: Windows NT 10.0.22621

Windows 11 x64 (22H2, OS build 22621.1992)

## Steps to Reproduce / Test Plan
1. Fresh profile
2. Enable brave://flags/#quick-commands and restart if needed
3. Use the hamburger menu and scroll down and pick `Open Guest Profile`
    ![image](https://github.com/brave/brave-browser/assets/4733304/d9416b19-2d80-4010-92aa-f0e408307f56)
4. Crash happens

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/a00d0800-0f67-770a-0000-000000000000

**Comment by bsclifton** [comment]
I can repro on a fresh profile after enabling brave://flags/#quick-commands

**Comment by GeetaSarvadnya** [comment]
The issue is reproducible in `Windows 10 x64 - 1.56.20` 

```
Brave | 1.56.20 Chromium: 115.0.5790.171 (Official Build) (64-bit)
-- | --
Revision | cf9067bf10d8f798c24643029af1d24e275646d6-refs/branch-heads/5790@{#1924}
OS | Windows 10 Version 22H2 (Build 19045.3208)

```

**Comment by bsclifton** [comment]
Added `release-notes/exclude` since this flag is off by default

**Comment by kjozwiak** [comment]
The above requires `1.57.42` or higher for `1.57.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.57.42 Chromium: 116.0.5845.51 (Official Build) (64-bit)
-- | --
Revision | e25036a089c476c56bf71774a898a1fee014e00d
OS | Windows 10 Version 22H2 (Build 19045.3208)
```
Confirmed that no crash while opening Guest window after enabling brave://flags/#quick-commands via brave://flags
