### ISSUE TITLE
`Disconnected`-button state toggle transition is janky/glitchy

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#31998]
## Description 

`Disconnected`-button state toggle transition is janky/glitchy

## Steps to Reproduce

1. install `1.57.27`
2. launch Brave
3. purchase, configure, and connect to `Brave VPN`
4. while `Connected`, click on the `VPN` button in the browser toolbar
5. click again to toggle to `Disconnected`
6. wait
7. watch the button's state while it toggles

## Actual result:

The button glitches a bit when going from `Connected` -> `Disconnected`, but seemingly not the around way 'round?

![vpn-button-janky](https://github.com/brave/brave-browser/assets/387249/5169351b-3328-4834-b56c-2405e03f36fc)

## Expected result:

Should be a smoother transition

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.57.27 Chromium: 115.0.5790.114 (Official Build) beta (64-bit)
-- | --
Revision | 18977fb43f693d5a8deeb48bd1cfa52651d3f73e
OS | Windows 10 Version 22H2 (Build 19045.3271)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @aguscruiz @spylogsster @simonhong @rebron @mattmcalister @brave/qa-team

**Comment by akashdubey2211** [comment]
Heyy @stephendonner, i want to fix that issue.

**Comment by bsclifton** [comment]
@stephendonner is this still an issue? Underlying code has changed a bit - it should be more responsive and accurate now

**Comment by stephendonner** [comment]
> @stephendonner is this still an issue? Underlying code has changed a bit - it should be more responsive and accurate now

It's looking really good on macOS-x64 (and I've thrashed it around a good bit):

```
Brave | 1.65.28 Chromium: 122.0.6261.57 (Official Build) nightly (x86_64)
-- | --
Revision | c2e055a7ad1af320de4bc12174dde12172d9ebf7
OS | macOS Version 11.7.10 (Build 20G1427)
```

Haven't-yet made it to WireGuard testing, but now that I'm hopefully unblocked, I'll report back soon 👍

**Comment by stephendonner** [comment]
Yeah, no longer janky.
