### ISSUE TITLE
Private tabs mixed with normal tabs

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#32]

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/requests-for-brave-0-55-18-plus-button-right-click-private-tabs-as-tabs/35248?u=eljuno

**Comment by eljuno** [comment]
+1 from Twitter https://twitter.com/Ja1andral/status/1071445920812752896?s=09

**Comment by alexeib** [comment]
What’s the rationale for wontfix?
