### ISSUE TITLE
[Tor] Follow HTTP/2 ALTSVC upgrade announcements to .onion routes

### ISSUE THREAD

**Issue by da2x** [brave/brave-browser#3200]
## Description 
The Tor Browser can upgrade a connection that uses a Tor exit node (onto the public web) to use Tor onion routing instead. This increases privacy and performance and reduces the load on exit nodes by allowing more traffic to be kept entirely inside the Tor onion network.

Technically, this upgrade happens using a HTTP/2 ALTSVC frame that announces a new route to a .onion domain. See [RFC 7838](https://tools.ietf.org/html/rfc7838) and [Introducing the Cloudflare Onion Service](https://blog.cloudflare.com/cloudflare-onion-service/).
## Steps to Reproduce

   1. Open a Tor window
   2. Go to https://www.facebook.com/si/proxy
   3. Wait a 5–10 seconds and reload. Note the word displayed on the page.
   4. Repeat 3. a few times.

## Actual result:
Page repeatedly says "tor".

## Expected result:
Page should say "tor" for the first page load and afterwards say "onion" on subsequent page loads.

You can also test with https://perfectoid.space/test.php (ignore the expired certificate). Page is expected to be yellow on the first load and then turn green.

## Reproduces how often: 
Every time.

## Brave version (brave://version info)
Brave | 0.58.21 Chromium: 71.0.3578.98 (Official Build)(64-bit)
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Linux

### Reproducible on current release:
- Yes.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information
Facebook (!) and all Cloudflare hosted websites [announce an .onion route via HTTP/2 ALTSVC.](https://blog.cloudflare.com/cloudflare-onion-service/) Meaning this feature should work with a whole lot of websites.

**Comment by srirambv** [comment]
cc: @tomlowenthal @riastradh-brave

**Comment by tomlowenthal** [comment]
@da2x This is already planned, and thanks for useful additional references! The current issue tracking this work is #1121.
