### ISSUE TITLE
Add Brave VPN WireGuard setting to brave://settings/system

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#32002]
## Description 

Add a new section to brave://settings/system called `Brave VPN` and put a toggler `Use WireGuard for Brave VPN` defaulted to true

![image](https://github.com/brave/brave-browser/assets/2965009/47cc9439-c871-4c2c-97ac-6ad4ab7ff45f)

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.59.95 Chromium: 117.0.5938.88 (Official Build) beta (64-bit)
-- | --
Revision | a2cb6fb53ea2c9ab356de955aab8505f5455b8bb
OS | Windows 11 Version 22H2 (Build 22621.2283)
```


Case 1: Removed Wireguard feature flag - `PASSED`
<details>

1. Install 1.59.95
2. launched Brave
3. opened `brave://flags` in a new tab

#### confirmed `#brave-vpn-wireguard` flag is removed 

1.58.131 | 1.59.95
------ | ----
<img width="646" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/f76ce1dd-9519-4fb7-b5a1-03cb049ee61c">|<img width="648" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/48073cdc-ee89-467b-abe1-82762870bca2">

</details>

Case 2: Added Brave VPN section **brave://settings/system** and option to enable/disable - `PASSED`
<details>

1. continued from Case 1
2. open `brave://settings/system`

#### Confirmed a new setting `Use WireGuard protocol in Brave VPN` with a toggle to enable/disable the protocol
#### Confirmed `Use WireGuard protocol in Brave VPN` setting is enabled as a default 

<img width="952" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/08db8552-9935-4a84-9072-c1b58a3837cf">

</details>

Case 3:  Checking if the wireguard service was not registered and register it with elevated request.
<details>

1. continue from Case 2:
     - `Use WireGuard protocol in Brave VPN` setting is enabled as a default 
2. toggled `off` the `Use WireGuard protocol in Brave VPN` 
3. clicked `Relaunch` button
4. opened cmd line prompt as an administrator and ran `sc.exe delete BraveBetaVpnWireguardService`
5. toggled `On` the `Use WireGuard protocol in Brave VPN` in `brave://settings/system`
6. clicked `Relaunch` button

#### Confirmed UAC prompt shown when `Wireguard protocol` was enabled

https://github.com/brave/brave-browser/assets/98358127/f0d07bbb-91d4-442b-853a-526b410fe3a4
</details>

Case 4:  Disabling the option if Brave VPN connected - `PASSED`
<details>

1. continue from Case 3
      - `Use WireGuard protocol in Brave VPN` setting is enabled as a default 
2. purchase, configure Brave VPN
3. disabled `Use WireGuard protocol in Brave VPN` from default state (which was enabled)
4. enabled `Use WireGuard protocol in Brave VPN` 
5. connected to VPN via VPN panel 

### Confirmed `Use WireGuard Protocol in Brave VPN` is disabled and grayed out when VPN is 
### Confirmed the option is reset to initial value (toggle on/off) and disabled while the vpn connected.


https://github.com/brave/brave-browser/assets/98358127/3f2ba290-f843-4bd9-a745-f05673fa5268

</details>

Case 5: Status Tray icon should be hidden if Wireguard protocol is turned off - `PASSED`
<details>

1. continue from Case 3
2.       - `Use WireGuard protocol in Brave VPN` setting is enabled as a default 
3. disabled `Use WireGuard protocol in Brave VPN` in brave://settings/system
4. clicked `Relaunch` button
5. clicked hamburger menu >> Brave VPN

Actual results: Flyout menu shows `Hide VPN tray icon` regardless of changing `Use WireGuard protocol` setting to enable/disable
Expected results: if Status Tray icon launched it should be stopped when Wireguard protocol is turned off.
</details>

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
<html>
<body>
<!--StartFragment-->

Brave | 1.59.100 Chromium: 117.0.5938.92 (Official Build) beta (64-bit)
-- | --
Revision | 3243fffc43431ab8677e8139859670b4cd2df843
OS | Windows 10 Version 22H2 (Build 19045.3448)
```

Case 1
Case 2
Case 3
Case 4
Case 5
