### ISSUE TITLE
"Learn more" link is broken within SPL associated token account creation tooltip

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#32016]
## Description 

The provided "Learn more" link within the Solana Associated SPL token account creation tooltip.

## Steps to Reproduce

   1. Queue a transaction to send a SPL token to an address that has not owned that token before
   2. view warning regarding the account creation fees within the transaction confirmation panel
   3. click the "learn more" link

OR

view link directly: https://support.brave.com/hc/en-us/articles/5546517853325

## Actual result:

A new tab is created. The URL results in a 404.

## Expected result:
A new tab is created. The tab contain information regarding Solana token account creation.

## Reproduces how often: 

easy

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc: @HEagle18

**Comment by kjozwiak** [comment]
The above requires `1.67.119` or higher for `1.67.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.67.119 Chromium: 126.0.6478.114 (Official Build) (64-bit)
-- | --
Revision | 36e2dbd9e397c3a8a4d54a741ea5a6316eab0203
OS | Windows 11 Version 23H2 (Build 22631.3737)

- Verified steps from issue description
- Verified `Learn more` on send SPL token confirmation screen points to `https://support.brave.com/hc/en-us/articles/27490686330125-What-is-the-Associated-Token-Account-Program`
- Logged [#39159](https://github.com/brave/brave-browser/issues/39159)

https://github.com/brave/brave-browser/assets/17010094/c11b81c5-55dd-4674-9fd3-71d10db671d9
