### ISSUE TITLE
Manage Brave Ads: Update ad format names (August 2023)

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#32011]
## Description

Change ad format names to the following:

![image](https://github.com/brave/brave-browser/assets/11497541/3a5ee82f-e68e-45da-bd3b-3b62e9e66734)

**Comment by LaurenWags** [comment]
Verified with

```
Brave | 1.58.100 Chromium: 116.0.5845.114 (Official Build) beta (x86_64)
-- | --
Revision | a8c0058265009a1858c4502b9ba413671fbb61e1
OS | macOS Version 13.5.1 (Build 22G90)
```

Confirmed ad format names displayed as per the description.
 
Connected User | Connected User
--- | ---
<img width="657" alt="1" src="https://github.com/brave/brave-browser/assets/28145373/039ce9ad-c0d0-4a7b-9aed-7e73ee641382"> | <img width="663" alt="2" src="https://github.com/brave/brave-browser/assets/28145373/cc750dec-f135-4b83-8125-4cec1a3b0645">
