### ISSUE TITLE
Reload Brave Private Ads resources after Brave Rewards reset

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#32017]
Need to reload Brave Private Ads resources after Brave Rewards reset only if `brave-ads-should-always-run-brave-ads-service` flag is enabled.

**Comment by btlechowski** [comment]
Verification PASSED

Brave | 1.58.97 Chromium: 116.0.5845.96 (Official Build) beta (64-bit)
-- | --
Revision | c983323d5ff7738a3c8d3bf491a7241c24b4d65a
OS | Linux


<details>


</details>
