### ISSUE TITLE
Autoredirect IPFS resources promo infobar

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#32010]
When user visits some IPFS-related resource which is available for redirect when "Automatically redirect requests for IPFS network resources to the configured gateway."  setting, promo infobar should be shown, so user could enable this setting from the tab.

**Comment by kjozwiak** [comment]
The above requires `1.58.99` or higher for `1.58.x` verification 👍

**Comment by kjozwiak** [comment]
@srirambv @cypt4 thoughts on this being `QA/Test-All-Platforms`? Or should one device/platform for `Android` & `Desktop` be enough?

**Comment by srirambv** [comment]
Should be Test all platforms

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.58.109 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | a4ad1fcdb550daf076384dbb280ae944274b3d35
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#19588](https://github.com/brave/brave-core/pull/19588)
- Verified new promo info bar is shown for links that can be loaded via IPFS
- Verified selecting `Always` doesn't show for other links opened after it
- Verified selecting `Only once` continues to show the info bar every time the link is visited
- Verified selecting `No Thanks` doesn't show the info bar any more
- Verified selecting `Always` enables `Automatically redirect requests for IPFS network resources to the configured gateway.` setting

https://github.com/brave/brave-browser/assets/17010094/159e0406-6610-407c-be23-5d1999cdfa97

-----------
Verification passed on

Brave | 1.58.109 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | a4ad1fcdb550daf076384dbb280ae944274b3d35
OS | Linux

- Verified steps from [brave/brave-core#19588](https://github.com/brave/brave-core/pull/19588)
- Verified new promo info bar is shown for links that can be loaded via IPFS
- Verified selecting `Always` doesn't show for other links opened after it
- Verified selecting `Only once` continues to show the info bar every time the link is visited
- Verified selecting `No Thanks` doesn't show the info bar any more
- Verified selecting `Always` enables `Automatically redirect requests for IPFS network resources to the configured gateway.` setting

https://github.com/brave/brave-browser/assets/17010094/7a78dad5-9b69-406b-888f-88ca4cb23df2


---------
Verification passed on

Brave | 1.58.109 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | a4ad1fcdb550daf076384dbb280ae944274b3d35
OS | macOS Version 13.4.1 (c) (Build 22F770820d)

- Verified steps from [brave/brave-core#19588](https://github.com/brave/brave-core/pull/19588)
- Verified new promo info bar is shown for links that can be loaded via IPFS
- Verified selecting `Always` doesn't show for other links opened after it
- Verified selecting `Only once` continues to show the info bar every time the link is visited
- Verified selecting `No Thanks` doesn't show the info bar any more
- Verified selecting `Always` enables `Automatically redirect requests for IPFS network resources to the configured gateway.` setting

https://github.com/brave/brave-core/assets/17010094/860dc2f8-e571-456d-bf9c-ef8ef2aedf41
