### ISSUE TITLE
Unable to interact with tooltip text

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#32015]
## Description 

Certain tooltips are rendered in a way that prevents the user from moving the mouse over the tooltip content area. This prevents the user from being able to select text from the tooltip, and from clicking links within the tooltip content.

We should allow the user to click the tooltip trigger to "lock" the tooltip's state to "open". Clicking the mouse anywhere outside of the tooltip should re-enable the hover events and unlock the open state.

## Steps to Reproduce

   1. Queue up a transaction
   2. open the panel
   3. hover over an account name
   5. try to select the address value shown within the tooltip

## Actual result:

The tooltip closes before the mouse can be used to select text from the visible tooltip content

## Expected result:
The tooltip stays open as the mouse selects text from the visible tooltip content

## Reproduces how often: 

Easy

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.59.112 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | `967f25f295938c64c24e2e6a1790470668757655`
OS | Windows 11 Version 22H2 (Build 22621.2283)

- Verified steps from [brave/brave-core#19993](https://github.com/brave/brave-core/pull/19993)
- Verified able to interact with tooltip text and able to select it

https://github.com/brave/brave-browser/assets/17010094/9cb7f3e1-9df8-4143-8d1c-2531aef5dfdd


---------------------

**Verification passed on**

Brave | 1.59.112 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | `967f25f295938c64c24e2e6a1790470668757655`
OS | Linux

- Verified steps from [brave/brave-core#19993](https://github.com/brave/brave-core/pull/19993)
- Verified able to interact with tooltip text and able to select it

https://github.com/brave/brave-browser/assets/17010094/aa9a8f82-fd9e-485c-b840-a24ca2794201


---------------------

**Verification passed on**

Brave | 1.59.112 Chromium: 118.0.5993.54 (Official Build) (arm64)
-- | --
Revision | `967f25f295938c64c24e2e6a1790470668757655`
OS | macOS Version 14.0 (Build 23A344)

- Verified steps from [brave/brave-core#19993](https://github.com/brave/brave-core/pull/19993)
- Verified able to interact with tooltip text and able to select it

https://github.com/brave/brave-browser/assets/17010094/5e53f42e-abe2-4970-a0b3-db46bd7198c8
