### ISSUE TITLE
Implement Move to Spam and Unspam feature in the frontend

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#32028]
Test Plan:
- Go to NFT tab
- There should be a new sub-tab named Spam
- Click on the sub-tab, it should display a list of NFTs
- Click on `More` icon on an NFT, and select `Unspam`. The NFT should be removed from Spam sub-tab to `NFTs` sub-tab
- On the NFTs tab, clicking on `Move to Spam` should add the NFT to spam list.

**Comment by LaurenWags** [comment]
@srirambv said this was not implemented, so have changed this one to `release-notes/exclude`.
