### ISSUE TITLE
Balance is not updated on Nightly

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#32029]
## Description 

Balance is not updated on Nightly

## Steps to Reproduce

   1. Create a new wallet or restore one with balance
   2. Open Console
   3. Balance doesn't show on portfolio and shows errors in console

## Actual result:

https://github.com/brave/brave-browser/assets/17010094/e1ee0904-5f0e-4e62-84f7-47ce13f65353

## Expected result:
Show balance

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.58.63 Chromium: 116.0.5845.51 (Official Build) nightly (arm64)
-- | --
Revision | c833a91b3f998d27b033c8f4ccf5ae686543b21d
OS | All

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel @onyb @josheleonard @HEagle18

**Comment by kjozwiak** [comment]
The above requires `1.60.104` or higher for `1.60.x` verification 👍

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.60.104 Chromium: 118.0.5993.117 (Official Build) (64-bit)
-- | --
Revision | 5dfa047eac682ad367174af6503fc21b59db5977
OS | Windows 11 Version 22H2 (Build 22621.2428)

- Verified steps from [brave/brave-core#20589](https://github.com/brave/brave-core/pull/20589)
- Verified no error message in console when using the wallet, loading balance/NFT, loading graph
- Verified balance is loaded successfully when loading localhost EVM account
