### ISSUE TITLE
Build out Panel V2 Connect Screens

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#32035]
## Description 

We need to build out the `Panel V2` Connect screens

![Screenshot 43](https://github.com/brave/brave-browser/assets/40611140/4d0d7d6f-4c08-4b5f-8232-1bc46e546e97)

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.59.115 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | `82b05012fc6b5ab8535cf283db6856ad5eedd7eb`
OS | Windows 11 Version 22H2 (Build 22621.2283)

- Verified steps from [brave/brave-core#19616](https://github.com/brave/brave-core/pull/19616)
- Verified the `Connection status` is correct on a Dapp
- Verified `Disconnecting` and `Connecting` works as expected
- Verified switching `Accounts` works as expected
- Verified switching `Networks` works as expected

https://github.com/brave/brave-browser/assets/17010094/235951c4-9374-4fb1-a634-f8ae72f307cc


---------------------

**Verification passed on**

Brave | 1.59.115 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | `82b05012fc6b5ab8535cf283db6856ad5eedd7eb`
OS | Linux

- Verified steps from [brave/brave-core#19616](https://github.com/brave/brave-core/pull/19616)
- Verified the `Connection status` is correct on a Dapp
- Verified `Disconnecting` and `Connecting` works as expected
- Verified switching `Accounts` works as expected
- Verified switching `Networks` works as expected

https://github.com/brave/brave-browser/assets/17010094/bb80c1c0-4857-4425-92e4-4fb0d64a30ec


---------------------

**Verification passed on**

Brave | 1.59.115 Chromium: 118.0.5993.54 (Official Build) (arm64)
-- | --
Revision | `82b05012fc6b5ab8535cf283db6856ad5eedd7eb`
OS | macOS Version 14.0 (Build 23A344)

- Verified steps from [brave/brave-core#19616](https://github.com/brave/brave-core/pull/19616)
- Verified the `Connection status` is correct on a Dapp
- Verified `Disconnecting` and `Connecting` works as expected
- Verified switching `Accounts` works as expected
- Verified switching `Networks` works as expected

https://github.com/brave/brave-browser/assets/17010094/3a5aa5f7-4ba0-485c-8af4-4ef37b36f824
