### ISSUE TITLE
ZebPay — Phase1

### ISSUE THREAD

**Issue by szilardszaloki** [brave/brave-browser#32036]

**Comment by LaurenWags** [comment]
Full checks on Windows and macOS, reduced cases on Linux.

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave | 1.58.91 Chromium: 116.0.5845.96 (Official Build) beta (64-bit)
-- | --
Revision | 620fa9c0307b294dd6e7c6b0976bc1f93fecf369
OS | Windows 10 Version 22H2 (Build 19045.3324)

```

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.58.100 Chromium: 116.0.5845.114 (Official Build) beta (x86_64)
-- | --
Revision | a8c0058265009a1858c4502b9ba413671fbb61e1
OS | macOS Version 13.5 (Build 22G74)
```

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.58.100 Chromium: 116.0.5845.114 (Official Build) beta (x86_64)
-- | --
Revision | a8c0058265009a1858c4502b9ba413671fbb61e1
OS | macOS Version 13.5.1 (Build 22G90)
```

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.58.116 Chromium: 116.0.5845.180 (Official Build) beta (64-bit) 
Revision	a35434b49b9cb7675b96179d5994e1f6a21954de
OS	Linux
```

**Comment by SibahleRwaqa** [comment]
I am searching for part time job..I saw post zebpay bitcoin trading option and apply on FB and redirected to watsapp. Isabella who recruit me and advice to register.after registration she teach how to do task. Recharge 14 and first for task .after two task again task came with difference 61 and . When I ask she told you will get back this amount with your commission at end of task. She advised to complete 10 task and advised to contact service manager Alina in telegram. I can't message her.

I report it to Isabella. Alina contact me and advised to pay 615548aed. I paid and continue the task. After 5th task again 538 and need to pay. She assured me you need to complete task and you can withdraw money immediately. I paid again money. After that 10 task came with high commission. I paid 1470 and and completed all task.I ask her to money back . She told me I needed to upgrade my account VIP LEVEL THEN ONLY I CAN withdraw. I asked her why didn't not tell before . I borrowed money from friends and pay. I can't withdraw.they are not willing to payback . I need to pay more for my commission withdrawal so I had no choice than to seek help to claim  my  money  then a friend  introduce me to reclaim collector expert . They gave me steps to take and  they  help me recover  my  money  . for more  info you can message them on telegram : @banninksolutions

Step 1: Report  to  your local police.
Step 2:  stop Contact with  the scams ...
Step 3: File All  Documentation  ...
Step 4: Speak to  BanninkSolutions reclaim collector agent( Banninksolutions (at) proton.me) 
Step 5:  Proceed  with  BanninkSolutions  to get your money
