### ISSUE TITLE
Add disconnect button to favicon/title 

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#32039]
## Description 

- Add Disconnect button to favicon / title (Clicking will reset conversation state and prevent page context being used / sent for that page load only)
- Eraser button will only remove conversation history but keep page context
- Hover over title / favicon area will show message about page content will be sent when favicon / title is showing and that the user can disconnect to stop it doing that for a page

## Design/Expected result:
<img width="611" alt="Screenshot 2023-08-09 at 12 18 25 PM" src="https://github.com/brave/brave-browser/assets/5951041/bb39455f-5cb2-4610-aa37-e311b15362f1">

https://www.figma.com/file/h7fKSJF2P556bZWfyLTfwD/Brave-AI?type=design&node-id=1902%3A42546&mode=design&t=iPOuz3YZxZNeq9lU-1

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by petemill** [comment]
That issue has a duplicate at https://github.com/brave/brave-browser/issues/31741 with a somewhat different description in case we go that direction:
> Whilst we do show when the AI Chat sidebar is Tab-related via the favicon and page title, it could be considered too subtle to let the user know that all page content will be sent to the AI Chat server when any user input is submitted.
>
>(Page content is sent for any user submission on that conversation and not just requests for summaries.)
>
>It could be a short message attached to the favicon and page title:
"Page content will be sent to Brave Leo along with your messages."
>
>We could also provide with a button which disconnects the conversation from the page in order to not send the page content, or have a standalone conversation.
>
>This would be disabled after the conversation is started. The conversation would need to be cleared to use this button again. OR the button could remain enabled and could clear the conversation when it is disconnected from the Page.

**Comment by stephendonner** [comment]
@nullhook can we get a test plan here with (any additional) details (especially around conversation contexts, etc.)?  🙏

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using 

```
1.60.79
```
