### ISSUE TITLE
Add support for b:// protocol

### ISSUE THREAD

**Issue by Kinnardian** [brave/brave-browser#3203]
Could Brave add support for the `b://` Bitcoin simple storage protocol?

It's a new protocol developed by @unwriter:
https://github.com/unwriter/B

What would it take to get this done?

**Comment by attilaaf** [comment]
+ additional background information:

`b://` links are rendered by sites like https://b.bitdb.network (what started it all), www.bitcoinfiles.org, www.bitpaste.app, www.bico.media, www.svblox.com, www.whatsonchain.com, www.pagereturn.com and more.

At a high level any URL like `b://transaction-id-uri` is a reference to a file on the Bitcoin SV blockchain stored in a transaction defined by the `b://` protocol.

### Method 1) User Chooses their `b://` Provider Settings

This is basically a method for dynamically replacing all URLs in memory (DOM rendering and JS AJAX execution) of URLs of the form `b://....` with a provider that serves the content from the blockchain.

One way to handle `b://....` URLS is to provide the user with an option to "Choose their b:// provider" like one of the sites above (Shameless plug) such as: https://static.bitcoinfiles.org/a5712a1de9811bde1785fbc8359cc2bfd9c20914d0c3c7e1a5ca15c419720f7e

We can convert any link such as `b://a5712a1de9811bde1785fbc8359cc2bfd9c20914d0c3c7e1a5ca15c419720f7e?foo=bar` into 

`https://static.bitcoinfiles.org/a5712a1de9811bde1785fbc8359cc2bfd9c20914d0c3c7e1a5ca15c419720f7e?foo=bar`

...by merely replacing the `b://` part with `https://static.bitcoinfiles.org/`

HTML example:
```
<html>
<body>
<img src="b://a5712a1de9811bde1785fbc8359cc2bfd9c20914d0c3c7e1a5ca15c419720f7e">
</body>
</html>
```

Can become:

```
<html>
<body>
<img src="https://static.bitcoinfiles.org/a5712a1de9811bde1785fbc8359cc2bfd9c20914d0c3c7e1a5ca15c419720f7e">
</body>
</html>
```

or another provider such as 

```
<html>
<body>
<img src="https://bico.media/a5712a1de9811bde1785fbc8359cc2bfd9c20914d0c3c7e1a5ca15c419720f7e">
</body>
</html>
```

### Method 2) User Choose their Bitdb provider and then sets preset rule for handling `b://` links.

https://bitdb.network/ is a standard way of aggregating, indexing, and querying Bitcoin data.  Bitdb is created and maintained by Unwriter and provides a standard way of interacting with the Bitcoin SV network.

This opens up unique possibilities and very complex interactions in the future.  It is more work, but can be worth it long term.

In this method, what can be done is that User can "Configure Bitdb Provider" to use a URL (such as https://babel.bitdb.network).

Then...  preset rules can be chosen for how to handle `b://` links.   For instance, we can specify that when the browser sees a `b://` link, that it calls the `https://babel.bitdb.network` endpoint and performs a custom Bitdb query to fetch and parse the `b://` protocol format!

In this manner, the user can configure which public Bitdb provider they wish to use and also specify their rules (preset in this case for convenient) for being able to handle these links.

----

The above is not meant to be an 'implementation guide', but just an overview of 2 ideas on how to accomplish this.  If anyone would like to take it on, then I'm available for help with implementation and also document a more technical specification to make it more understandable.

**Comment by Kinnardian** [comment]
Chrome extension that allows you to browse b://protocol directly approved: https://twitter.com/prayer0000/status/1106008944898646016

**Comment by tomlowenthal** [comment]
Sounds like this can be done in an extension.

**Comment by Kinnardian** [comment]
A standalone browser has also been developed: https://twitter.com/_unwriter/status/1108761025388728320
