### ISSUE TITLE
Add vpn section to brave://skus-internals

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#32030]
## Test plan
See https://github.com/brave/brave-core/pull/19857

## Description
VPN section can have
* last connection error
* vpn purchase info such as order id

**Comment by kjozwiak** [comment]
The above requires `1.57.55` or higher for `1.57.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.57.56 Chromium: 116.0.5845.114 (Official Build) (64-bit)
-- | --
Revision | 6fa63f5677a245eb7834718cd2ab3d87c7eabc45
OS | Windows 11 Version 22H2 (Build 22621.2134)
```

### Steps:

1. installed `1.59.56`
2. launched Brave
3. purchased, configured, and connected to `Brave VPN`
4. confirmed connection via `WireGuard` which is now default on `nightly` 👍 
5. opened `brave://skus-internals`
6. confirmed new `VPN State:` field and `Fetch VPN state` button
7. clicked on `Fetch VPN state` button
8. confirmed `order_id` and other fields were present
9. compared the above with the `Local State` entries in my user profile directory
10. additionally confirmed toggle to collapse/expand further, as well as the existing `Fetch SKUs state` button

example | example | example | example | example
---------|----------|---------|----------|--------
<img width="944" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/af70678c-411e-4255-bb34-cd2e1160ee10">|<img width="959" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/2eee69f9-bdf0-4852-a017-9401699eac53">|<img width="960" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/08cdd498-d517-4570-bd5f-bf45d52b91da">|<img width="949" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/341286b0-0e60-4096-94a4-c5c4cc2aa1a0">|<img width="959" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/5a1fdb1a-9502-482f-a86b-2db204415531">

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.57.56 Chromium: 116.0.5845.114 (Official Build) (64-bit)
-- | --
Revision | 6fa63f5677a245eb7834718cd2ab3d87c7eabc45
OS | Windows 10 Version 22H2 (Build 19045.3393)
```

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.57.56 Chromium: 116.0.5845.114 (Official Build) (x86_64)
-- | --
Revision | 6fa63f5677a245eb7834718cd2ab3d87c7eabc45
OS | macOS Version 11.7.9 (Build 20G1426)
```
