### ISSUE TITLE
Brave crashes when multiple windows are opened from private window

### ISSUE THREAD

**Issue by Gamekiller17** [brave/brave-browser#32031]
## Description 

When a new Brave window is opened while a **Private Window** is already open and in focus, the entire browser session crashes. The same issue arises when launching a private window directly from the terminal using `/bin/brave --incognito`. These crashes specifically happen in **Private Window** and **Private Window with Tor**.

Update 05/08/2023:
Upon further investigation, it has been determined that crashes can be avoided by opening multiple private windows from a regular window instead of an already open private window. This applies to shortcuts such as Ctrl+Shift+n and Alt+Shift+n. As long as a regular window is in focus, any number of private windows can be opened without encountering any crashes.

Update 14/08/2023
Thanks to the efforts of [atuchin-m](https://github.com/atuchin-m) and [bambalamm](https://github.com/bambalamm), we have identified the recurring problem in the latest versions of Chromium-based web browsers.

For more information, please check the following upstream issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1470877.

## Exceptional Cases

- Crash doesn't happen if one **Private Window** and one **Private Window with Tor** are open. 
- Crash doesn't occur if multiple normal windows are opened, as long as another normal window is in focus. 
- Crash doesn't occur if multiple tabs are open in a single private window.

## Steps to Reproduce

   1. Open Brave Browser
   2. Open a New Private window
   3. Open another New Private window.

## Actual result: 

Brave freezes briefly and the entire browser terminates.

Below are the logs that appear when a normal window is launched from terminal and then two private windows are opened through the GUI menus.

```
[0802/193853.810234:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0802/193853.813361:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0802/193853.813634:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0802/193853.813837:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[56553:56559:0802/193855.565045:ERROR:ssl_client_socket_impl.cc(980)] handshake failed; returned -1, SSL error code 1, net_error -3
[56553:56559:0802/193855.566023:ERROR:ssl_client_socket_impl.cc(980)] handshake failed; returned -1, SSL error code 1, net_error -3
```

## Expected result: 

Two or more normally functioning private windows.

## Reproduces how often: 

Every time

## Brave version
1.56.14 Chromium: 115.0.5790.114 (Official Build) (64-bit) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? **Yes**
- Can you reproduce this issue with the beta channel? **Not sure**
- Can you reproduce this issue with the nightly channel? **Not sure**

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? **No**
- Does the issue resolve itself when disabling Brave Rewards? **No**
- Is the issue reproducible on the latest version of Chrome? **Yes**
- Does the issue resolve itself when disabling all 3rd party extensions? **No**

## Installation Source: 

[AUR](https://aur.archlinux.org/packages/brave-bin)

## OS Info:
- Distro: Arch Linux
- Kernal: linux-zen (6.4.7-zen1-1-zen)
- Desktop Environment: KDE Plasma
- Windowing System: X11
- Window Manager: Kwin

## Mitigation Attempts

A complete reinstallation of Brave was performed using the command `yay -Rns brave-bin && yay -S brave-bin`.
The folder `~/.config/BraveSoftware` was deleted, and then Brave was launched.

Despite applying the aforementioned measures, the crash continues to occur.

**Comment by rebron** [comment]
@Gamekiller17 Can you send the crash from brave://crashes and post the crash id here when you get a chance.

**Comment by Gamekiller17** [comment]
> @Gamekiller17 Can you send the crash from brave://crashes and post the crash id here when you get a chance.

Sure.

Crash Report ID: | d9990100-79a9-800a-0000-000000000000

**Comment by bambalamm** [comment]
The same thing happens in Google Chrome.

**Comment by atuchin-m** [comment]
The upstream issue:
https://bugs.chromium.org/p/chromium/issues/detail?id=1470877

**Comment by Gamekiller17** [comment]
After the latest update, this particular crash is not occurring. Therefore, I will proceed to close this thread.

**Comment by Gamekiller17** [comment]
Or so I thought. No, the crashes didn't go away. It's the exact same issue. So I am reopening it until the upstream issue gets solved.

**Comment by iefremov** [comment]
fixed upstream
