### ISSUE TITLE
Upgrade from Chromium 115.0.5790.114/115.0.5790.138 to Chromium 115.0.5790.171.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#32040]
# Minor Chromium bump

https://chromium.googlesource.com/chromium/src/+log/115.0.5790.114..115.0.5790.171?pretty=fuller&n=10000

# QA tests:

* Check branding items
* Check for version bump

# Additional checks:
* No specific code changes in Brave (only line number changes in patches)

**Comment by kjozwiak** [comment]
Closing as https://github.com/brave/brave-core/pull/19542 & https://github.com/brave/brave-core/pull/19542 have been uplifted into `1.57.x` & `1.56.x`.

**Comment by kjozwiak** [comment]
The above requires `1.56.20` or higher for `1.56.x` verification 👍

**Comment by LaurenWags** [comment]
Verified with

```
Brave	1.56.20 Chromium: 115.0.5790.171 (Official Build) (arm64) 
Revision	cf9067bf10d8f798c24643029af1d24e275646d6-refs/branch-heads/5790@{#1924}
OS	macOS Version 13.5 (Build 22G74)
```

![M1](https://github.com/brave/brave-browser/assets/28145373/64b80ba2-92e9-4e8c-b66c-005adbd44e5b)

**Comment by Uni-verse** [comment]
Verified on Samsung Galaxy S 21 using version: 

```
Brave	1.56.20 Chromium: 115.0.5790.171 (Official Build) (32-bit) 
Revision	cf9067bf10d8f798c24643029af1d24e275646d6-refs/branch-heads/5790@{#1924}
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

- [x] version bump
- [x] branding

Example | Example
-|-
![Screenshot 2023-08-03 at 12 05 01 PM](https://github.com/brave/brave-browser/assets/17885425/0d79e1d3-93ee-4a35-8df3-4137247dbd36) | ![Screenshot 2023-08-03 at 12 06 54 PM](https://github.com/brave/brave-browser/assets/17885425/53ef90e2-a854-40f0-8e3f-0e09686e0a3b)

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy Tab S7` using version: 

```
Brave	1.56.20 Chromium: 115.0.5790.171 (Official Build) (32-bit) 
Revision	cf9067bf10d8f798c24643029af1d24e275646d6-refs/branch-heads/5790@{#1924}
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
- [x] version bump
- [x] branding

Example | Example
-|-
![Screenshot 2023-08-03 at 12 18 22 PM](https://github.com/brave/brave-browser/assets/17885425/69d2b722-fea0-40d3-a992-5b5fcf9c8191) | ![Screenshot 2023-08-03 at 12 18 54 PM](https://github.com/brave/brave-browser/assets/17885425/b0c4b450-02cd-4cb8-89f0-2edb9863d211)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.56.20 Chromium: 115.0.5790.171 (Official Build) (64-bit)
-- | --
Revision | cf9067bf10d8f798c24643029af1d24e275646d6-refs/branch-heads/5790@{#1924}
OS | Windows 11 Version 22H2 (Build 22621.1992)
```


<img width="530" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/38fa5193-f5f6-4dd2-91eb-7b3d19bc27e8">

**Comment by LaurenWags** [comment]
Verified with

```
Brave | 1.56.20 Chromium: 115.0.5790.171 (Official Build) (x86_64)
-- | --
Revision | cf9067bf10d8f798c24643029af1d24e275646d6-refs/branch-heads/5790@{#1924}
OS | macOS Version 13.5 (Build 22G74)
```

<img width="1193" alt="Intel" src="https://github.com/brave/brave-browser/assets/28145373/cd54ba34-645f-4fc9-a96e-f54467743bc0">
