### ISSUE TITLE
[Android] Move notifications permission prompt

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#32047]
## Requirements
1. Move the Android 13+ notifications permission prompt to first open. Display it immediately as you are looking at the Brave logo on the first onboarding screen.
2. Do not show the explainer modal, just go straight to the system dialog.
3. Do not continue the onboarding until the user selects `Allow` or `Don't allow`.

![image](https://github.com/brave/brave-browser/assets/28269287/545a5449-3672-4959-ae22-8b8015ba5e75)

cc @anthonypkeane @bradleyrichter @deeppandya

**Comment by kjozwiak** [comment]
The above requires `1.58.121` or higher for `1.58.x` verification 👍 @Uni-verse @vlad-hoff can use the STR/Cases from https://github.com/brave/brave-core/pull/19603#issuecomment-1714929128. Please add any checks that I might have missed.

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version(s):

```
Brave	1.58.121 Chromium: 117.0.5938.48 (Official Build) (32-bit) 
Revision	d80a8110b88df6ae5073d8420fada4168542786f
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

### Selecting `Allow` via the system notification

* ensured that the `System Notification` appears when launching Brave
  * ensured that it re-appears if you restart Brave without making a decision (closing Brave while notification is visible)
* ensured when `Allow` is selected, that all the notification categories are enabled via `Settings` -> `Notifications`
* ensured that you don't receive the `Brave notifications make it easier` modal when going back into `Settings` from `Notifications` when notifications are enabled
* ensured that you can enable both `Rewards` & `Privacy Stats` without any warnings re: notifications not being enabled
* ensured that `Ad notifications` are still appearing without any issues
* ensured that the old `System Notification` doesn't appear after restarting browser several times
  * also ensured that it doesn't appear after opening several tabs
* ensured that the `Notifications are disabled` appears in `brave://rewards` when notifications have been disabled
  * ensured that `TURN ON` re-directs the user to Androids system notifications for `Release`
* ensured that `Privacy Report` displays the `Turn on notifications` modal when notifications have been disabled
  * ensured that `Turn on notifications` re-directs the user to Androids system notifications for `Release`
* ensured that you receive the `Brave notifications make it easier` modal when going back into `Settings` from `Notifications` when notifications have been disabled
  * ensured that tapping on `Continue` re-directs the user to Androids system notifications for `Release`
    * ensured that you never see the modal again once you've clicked `Continue`. For example, going back to `Settings` -> `Notifications` and then going back to `Settings` shouldn't display the modal as you've already seen it
  * ensured that tapping on `Not now` dismisses the modal without any issues
    * ensured that you never see the modal again once you've clicked `Not now`. For example, going back to `Settings` -> `Notifications` and then going back to `Settings` shouldn't display the modal as you've already seen it

Example | Example | Example | Example | Example
-|-|-|-|-
![Screenshot 2023-09-12 at 12 49 55 PM](https://github.com/brave/brave-browser/assets/17885425/3b4b912b-7168-4d4a-94a3-2694139ba99d) | ![Screenshot 2023-09-12 at 12 50 52 PM](https://github.com/brave/brave-browser/assets/17885425/8896e438-68ae-4f56-8263-540d1a62d636) | ![Screenshot 2023-09-12 at 12 54 12 PM](https://github.com/brave/brave-browser/assets/17885425/3c8a4219-5229-4cf5-9225-ea63239b8aa7) | ![Screenshot 2023-09-12 at 12 56 48 PM](https://github.com/brave/brave-browser/assets/17885425/d370fa02-8bf6-47b9-81ba-0cf7fea17771) | ![Screenshot 2023-09-12 at 12 58 42 PM](https://github.com/brave/brave-browser/assets/17885425/741f5b21-5f5b-46ab-963e-b81d756f02c9)


### Selecting `Don't Allow` via the system notification

* ensured that the `System Notification` appears when launching Brave
  * ensured that it re-appears if you restart Brave without making a decision (closing Brave while notification is visible)
* ensured that tapping anywhere within the NTP when notification modal is visible counts as selecting `Don't Allow`
* ensured when `Don't Allow` is selected, that all the notification categories are disabled via `Settings` -> `Notifications`
* ensured that you receive the `Brave notifications make it easier` modal when going back into `Settings` from `Notifications` when notifications are disabled
* ensured that you receive the `Allow Brave - Nightly to send you notifications` modal when running through the `rewards` onboarding when you haven't enabled notifications when launching Brave.
  * ensured that both `Allow` & `Don't Allow` work as expected
* ensured that you receive the `Enable notifications from Brave to earn Brave Rewards` if you've disabled notifications after they've been enabled and attempt to run through `rewards` onboarding
  * ensured that tapping on `Open Settings` opens the `Notifications` setting and allows you to enable notifications
* ensured that `Privacy Report` displays the `Get Weekly privacy updates on tracker & ad blocking` modal when enabling `Privacy Report` when notifications are disabled
  * ensured that `Turn on notifications` re-directs the user to Androids system notifications for `Release`

Example | Example | Example | Example | Example
-|-|-|-|-
![Screenshot 2023-09-12 at 1 16 10 PM](https://github.com/brave/brave-browser/assets/17885425/c93ee3b0-5fba-4661-bb79-a88165cdb999) | ![Screenshot 2023-09-12 at 1 18 20 PM](https://github.com/brave/brave-browser/assets/17885425/7929ba44-38c3-4ff6-8adf-29961515052a) | ![Screenshot 2023-09-12 at 1 18 32 PM](https://github.com/brave/brave-browser/assets/17885425/2180c7bb-c30a-4c5d-95ae-4e014cd4e37a) | ![Screenshot 2023-09-12 at 1 18 45 PM](https://github.com/brave/brave-browser/assets/17885425/cbfd19e4-8cd1-465c-a5f0-84c654bb4b38) | ![Screenshot 2023-09-12 at 9 56 50 AM](https://github.com/brave/brave-browser/assets/17885425/a394ef53-a214-4735-ae40-e7c19598f741)

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy Tab S7` using version(s):

```
Brave	1.58.121 Chromium: 117.0.5938.48 (Official Build) (32-bit) 
Revision	d80a8110b88df6ae5073d8420fada4168542786f
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
### Selecting `Allow` via the system notification

* ensured that the `System Notification` appears when launching Brave
  * ensured that it re-appears if you restart Brave without making a decision (closing Brave while notification is visible)
* ensured when `Allow` is selected, that all the notification categories are enabled via `Settings` -> `Notifications`
* ensured that you don't receive the `Brave notifications make it easier` modal when going back into `Settings` from `Notifications` when notifications are enabled
* ensured that you can enable both `Rewards` & `Privacy Stats` without any warnings re: notifications not being enabled
* ensured that `Ad notifications` are still appearing without any issues
* ensured that the old `System Notification` doesn't appear after restarting browser several times
  * also ensured that it doesn't appear after opening several tabs
* ensured that the `Notifications are disabled` appears in `brave://rewards` when notifications have been disabled
  * ensured that `TURN ON` re-directs the user to Androids system notifications for `Release`
* ensured that `Privacy Report` displays the `Turn on notifications` modal when notifications have been disabled
  * ensured that `Turn on notifications` re-directs the user to Androids system notifications for `Release`
* ensured that you receive the `Brave notifications make it easier` modal when going back into `Settings` from `Notifications` when notifications have been disabled
  * ensured that tapping on `Continue` re-directs the user to Androids system notifications for `Release`
    * ensured that you never see the modal again once you've clicked `Continue`. For example, going back to `Settings` -> `Notifications` and then going back to `Settings` shouldn't display the modal as you've already seen it
  * ensured that tapping on `Not now` dismisses the modal without any issues
    * ensured that you never see the modal again once you've clicked `Not now`. For example, going back to `Settings` -> `Notifications` and then going back to `Settings` shouldn't display the modal as you've already seen it

Example | Example | Example | Example
-|-|-|-
![Screenshot 2023-09-12 at 1 35 35 PM](https://github.com/brave/brave-browser/assets/17885425/f7439486-1f2e-478e-8af4-16d61d9746f5) | ![Screenshot 2023-09-12 at 1 36 16 PM](https://github.com/brave/brave-browser/assets/17885425/08045305-1727-442b-a169-4331b02bb884) | ![Screenshot 2023-09-12 at 1 36 47 PM](https://github.com/brave/brave-browser/assets/17885425/69cb1938-2301-4561-885a-08be957980bc) | ![Screenshot 2023-09-12 at 1 37 06 PM](https://github.com/brave/brave-browser/assets/17885425/1e411de1-8dbc-4d2a-adaa-4103ac60ee5d)


### Selecting `Don't Allow` via the system notification

* ensured that the `System Notification` appears when launching Brave
  * ensured that it re-appears if you restart Brave without making a decision (closing Brave while notification is visible)
* ensured that tapping anywhere within the NTP when notification modal is visible counts as selecting `Don't Allow`
* ensured when `Don't Allow` is selected, that all the notification categories are disabled via `Settings` -> `Notifications`
* ensured that you receive the `Brave notifications make it easier` modal when going back into `Settings` from `Notifications` when notifications are disabled
* ensured that you receive the `Allow Brave - Nightly to send you notifications` modal when running through the `rewards` onboarding when you haven't enabled notifications when launching Brave.
  * ensured that both `Allow` & `Don't Allow` work as expected
* ensured that you receive the `Enable notifications from Brave to earn Brave Rewards` if you've disabled notifications after they've been enabled and attempt to run through `rewards` onboarding
  * ensured that tapping on `Open Settings` opens the `Notifications` setting and allows you to enable notifications
* ensured that `Privacy Report` displays the `Get Weekly privacy updates on tracker & ad blocking` modal when enabling `Privacy Report` when notifications are disabled
  * ensured that `Turn on notifications` re-directs the user to Androids system notifications for `Release`

Example | Example | Example | Example
-|-|-|-
![Screenshot 2023-09-12 at 1 39 15 PM](https://github.com/brave/brave-browser/assets/17885425/af01f089-fec7-46a5-88b5-1ebf1117387b) | ![Screenshot 2023-09-12 at 1 37 30 PM](https://github.com/brave/brave-browser/assets/17885425/6bba39df-89f0-4306-8cc0-1bc5d564d5c7) | ![Screenshot 2023-09-12 at 1 38 24 PM](https://github.com/brave/brave-browser/assets/17885425/00e464f0-f292-4638-9b26-aa082e985cf6) | ![Screenshot 2023-09-12 at 1 38 57 PM](https://github.com/brave/brave-browser/assets/17885425/392b8da8-6884-479b-9e20-c2fc0361f9f7)

**Comment by Uni-verse** [comment]
Verified on `Pixel 2 XL` using version 

```
Brave	1.58.121 Chromium: 117.0.5938.48 (Official Build) (32-bit) 
Revision	d80a8110b88df6ae5073d8420fada4168542786f
OS	Android 8.1.0; Build/OPM2.171026.006.H1; 27; REL
```
- Ensured notifications are enabled automatically on `Android 8` and user is able to disable them from the notification settings.
- Ensured notifications are shown in app. 

Example | Example | Example
-|-|-
![Screenshot 2023-09-12 at 2 17 50 PM](https://github.com/brave/brave-browser/assets/17885425/9a984a6f-3408-4f48-9f9d-d6b8de5bc6d2) | ![Screenshot 2023-09-12 at 2 38 15 PM](https://github.com/brave/brave-browser/assets/17885425/de0acf15-54b2-4afc-b34b-e02f748fd246) | ![Screenshot 2023-09-12 at 2 38 38 PM](https://github.com/brave/brave-browser/assets/17885425/16f3f8c1-1aaf-44e4-8378-f6cfe302a5a4)
