### ISSUE TITLE
Promote Wireguard based Brave VPN to users

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#32051]
Some users will get Wireguard via updates and we need a way to promote it. Maybe add a new view to Brave VPN popup or dialog/notification suggesting to try the new Wireguard-based VPN.

**Comment by spylogsster** [comment]
cc @bsclifton @rebron @aguscruiz

**Comment by stephendonner** [comment]
cc @mattmcalister @MadhaviSeelam

**Comment by mattmcalister** [comment]
Closing as stale
