### ISSUE TITLE
close `estimated earnings` tooltip when scrolling through `brave://rewards`

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#32052]
## Description 

Currently when you have the `estimated earnings` tooltip opened, scrolling through `brave://rewards` doesn't close the `tooltip`. The `tooltip` also doesn't close when tapping on the `estimated earnings` message again. Believe we should be closing the tooltip via:

* when a user starts scrolling, close the `tooltip` as I believe this is standard across many apps
* when a user taps on `estimated earnings` once again, they `tooltip` should probably be closed
* when a user taps somewhere on the screen (this is working as expected)

## Steps to reproduce 

   1. install a version of brave that's using the new rewards UI
   2. connect to a custodian (in this case, used Uphold on staging)
   3. tap on the `estimated earnings` and notice the tooltip appear
   4. scroll through `brave://rewards` and notice that the `tooltip` isn't being closed

## Actual result 

As mentioned above, the `estimated earnings` tooltip isn't being dismissed when either scrolling through `brave://rewards` or tapping on the `estimated earnings` message for a second time.

https://github.com/brave/brave-browser/assets/2602313/573a60a2-0755-4e17-9e22-4e806949ed89

## Expected result

As per the above, I believe we should be closing the `tooltip` in the following scenarios/cases:

* when a user starts scrolling, close the `tooltip` as I believe this is standard across many apps
* when a user taps on `estimated earnings` once again, they `tooltip` should probably be closed
* when a user taps somewhere on the screen (this is working as expected)

## Issue reproduces how often 

100% reproducible when using the STR/Cases outlined above.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `N/A`
- Can you reproduce this issue with the current Play Store Beta version? `Yes`
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Pixel 6`
   - Android version: `Android 14`
   
## Brave version

```
Brave | 1.58.66 Chromium: 116.0.5845.51 (Official Build) canary (64-bit)
--- | ---
Revision | 760f994002820ae85421061cfac48e987a605c03
OS | Android 14; Build/UPB4.230623.007; 34; REL
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by Miyayes** [comment]
Closing as will be superseded by Rewards 3.0.
