### ISSUE TITLE
Excess cursor on every paragraph element 

### ISSUE THREAD

**Issue by tristanisham** [brave/brave-browser#32054]
Description

The issue involves the presence of an unnecessary cursor on every paragraph (<p> HTML element) on every website while using the Brave browser. The cursor doesn't serve any function and is causing visual distraction.

[Example on YouTube](https://youtu.be/3gROMK5PuSw)

Steps to Reproduce

Open the Brave browser.
Navigate to any website.
Hover over any paragraph (<p> HTML element).
Actual result:

A cursor appears on the paragraph, which is distracting and doesn't serve any function.

Expected result:
The cursor should not appear unless the user is able to interact with the element (e.g., text boxes, links, etc.)

Reproduces how often:

Easily reproduced. This happens on every website with every paragraph element.

Brave version (brave://version info)

Brave v1.56.14. Chromium 115.0.5790.114 (Official Build) (64-bit). Windows 10, Desktop version.

Version/Channel Information:

Unknown, needs further testing.

Can you reproduce this issue with the current release?
 Yes

Can you reproduce this issue with the beta channel? 
Unknown

Can you reproduce this issue with the nightly channel?
Unknown
Other Additional Information:
 Does the issue resolve itself when disabling Brave Shields? 
No

Does the issue resolve itself when disabling Brave Rewards? 
No

Is the issue reproducible on the latest version of Chrome? 
I haven't been able to test on Chrome, but it is not reproduced on Microsoft Edge v115.0.1901.188 (Official build) (64-bit).

**Comment by rebron** [comment]
@tristanisham Do you have caret browsing turned on? If you select F7 that will toggle it on and off.

**Comment by tristanisham** [comment]
@rebron Holy crap, yeah, that turned it off. Must have hit it by accident. Thank you!
