### ISSUE TITLE
Remove provider scripts from devtools

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#32056]
Before migrating to native v8 we can remove this scripts from devtools
https://github.com/brave/brave-browser/issues/29921
https://github.com/brave/brave-browser/issues/29922

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.59.93 Chromium: 117.0.5938.88 (Official Build) beta (64-bit)
-- | --
Revision | 77474ed80832bd2c90be4ebf993b6c2a43f662b0
OS | Windows 11 Version 22H2 (Build 22621.2283)

- Verified steps from [brave/brave-core#19556](https://github.com/brave/brave-core/pull/19556)
- Verified Dapp connections work as expected
- Verified no provider.js files are loaded when connecting to a dapp

1.58.131 (Release) | 1.59.93 (Beta)
-- | --
![image](https://github.com/brave/brave-browser/assets/17010094/dd6ce2f3-4927-4873-870b-e647c40485c5) | ![image](https://github.com/brave/brave-browser/assets/17010094/f9ecd8ef-2d03-4463-8c02-a643d1716e69)

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 12 running 1.59.93 x64 Beta build
- Verified steps from [brave/brave-core#19556](https://github.com/brave/brave-core/pull/19556)
- Verified Dapp connections work as expected
- Verified no provider.js files are loaded when connecting to a Dapp


1.58.131 (Release) | 1.59.93 (Beta)
-- | --
![image](https://github.com/brave/brave-browser/assets/17010094/d74b09fe-0f0a-47cb-9cfe-b032087b811e) | ![image](https://github.com/brave/brave-browser/assets/17010094/bd9cebd6-af8e-42e7-be16-6ff6fc6f64a5)
