### ISSUE TITLE
Change `chrome://... says` to `brave://... says` in JavaScript popup boxes (`alert()`, `confirm()`, `prompt()`)

### ISSUE THREAD

**Issue by szilardszaloki** [brave/brave-browser#32060]
Fixing this based on our conversation [here](https://bravesoftware.slack.com/archives/C8MP8ME4C/p1654135745228199) with @bridiver, @thypon, and @fmarier.

**Comment by bsclifton** [comment]
Closing as a duplicate of https://github.com/brave/brave-browser/issues/32950
