### ISSUE TITLE
[Tablet] "Contribution sent!" bottom sheet banner stretched out on the tablets

### ISSUE THREAD

**Issue by vlad-hoff** [brave/brave-browser#32067]
## Description 

`Contribution sent!` bottom sheet banner stretched out on the tablets

## Steps to reproduce 

   1. Launch Brave on a `Tablet`
   2. Enable `Rewards Staging server`
   3. Enable `Rewards` and connect `Custodian`
   4. Open https://github.com/laurenwags > Send contribution > Observe `Contribution sent!` bottom sheet banner is stretched out

## Actual result 

`Contribution sent!` bottom sheet banner stretched out on the tablets. This is not happening on the phones.

|1|
|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/e4e8b78c-f3c4-4b12-a17a-9994778e3d83) |

## Expected result

`Contribution sent!` bottom sheet banner must not be stretched out.

## Issue reproduces how often 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Galaxy Tab S8 (Tablet)
   - Android version: Android 13
   
## Brave version

Brave build: 1.58.66
Chromium: 116.0.5845.51 (Official Build) canary (64-bit)
Revision: 760f994002820ae85421061cfac48e987a605c03

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by Miyayes** [comment]
@sujitacharya2005 I think the tablet-specific implementation of the Contribution Banner will solve this right?

**Comment by deeppandya** [comment]
i would be resolved as a part of https://github.com/brave/brave-browser/issues/30371
