### ISSUE TITLE
Sign-In with Ethereum (Desktop UI)

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#32078]
parent issue: https://github.com/brave/brave-browser/issues/32076

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.60.104 Chromium: 118.0.5993.117 (Official Build) (64-bit)
-- | --
Revision | `5dfa047eac682ad367174af6503fc21b59db5977`
OS | Windows 11 Version 22H2 (Build 22621.2283)

- Verified steps from [brave/brave-core#19443](https://github.com/brave/brave-core/pull/19443)
- Verified Sign-In with Ethereum UI is shown when trying to approve and sign-in on `https://login.xyz`
- Verified clicking on `See details` on SIWE UI shows details of the message
- Verified SIWE with resources list the resource details in the message details on `https://metamask.github.io/test-dapp`
- Verified error message is shown for `Wrong statement format`, `Domain mismatch`. `Account mismatch` and `Network mismatch` when format is wrong
- Verified no error message is shown and falls back to `EIP-191` format when an incorrect format is used

https://github.com/brave/brave-browser/assets/17010094/d8d7ab5d-c34b-4ef6-aa53-b794b44cfe6d

---------------------

**Verification passed on**

Brave | 1.60.104 Chromium: 118.0.5993.117 (Official Build) (64-bit)
-- | --
Revision | `5dfa047eac682ad367174af6503fc21b59db5977`
OS | Linux

- Verified steps from [brave/brave-core#19443](https://github.com/brave/brave-core/pull/19443)
- Verified Sign-In with Ethereum UI is shown when trying to approve and sign-in on `https://login.xyz`
- Verified clicking on `See details` on SIWE UI shows details of the message
- Verified SIWE with resources list the resource details in the message details on `https://metamask.github.io/test-dapp`
- Verified error message is shown for `Wrong statement format`, `Domain mismatch`. `Account mismatch` and `Network mismatch` when format is wrong
- Verified no error message is shown and falls back to `EIP-191` format when an incorrect format is used

https://github.com/brave/brave-browser/assets/17010094/a992943a-dc6f-46d7-8618-b3be24cc4f09


---------------------

**Verification passed on**

Brave | 1.60.104 Chromium: 118.0.5993.117 (Official Build) (64-bit)
-- | --
Revision | `5dfa047eac682ad367174af6503fc21b59db5977`
OS | macOS Version 14.0 (Build 23A344)

- Verified steps from [brave/brave-core#19443](https://github.com/brave/brave-core/pull/19443)
- Verified Sign-In with Ethereum UI is shown when trying to approve and sign-in on `https://login.xyz`
- Verified clicking on `See details` on SIWE UI shows details of the message
- Verified SIWE with resources list the resource details in the message details on `https://metamask.github.io/test-dapp`
- Verified error message is shown for `Wrong statement format`, `Domain mismatch`. `Account mismatch` and `Network mismatch` when format is wrong
- Verified no error message is shown and falls back to `EIP-191` format when an incorrect format is used

https://github.com/brave/brave-core/assets/17010094/7c6a6808-635c-465f-8426-c8914a323b38
