### ISSUE TITLE
Update sync common library

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#3207]
For this:
https://github.com/brave/sync/issues/277

User IDs could be wrong causing bookmarks not to sync because of an encoding problem for slashes. The problem only seems to happen around 1 in every 10 setups.  So it would likely be hard to test. 
But for QA'ing you can probably just make sure things aren't more broken than before.

**Comment by LaurenWags** [comment]
Verified passed with 

Brave | 0.59.35 Chromium: 72.0.3626.81 (Official Build) (64-bit)
-- | --
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS | Mac OS X

* Verified several sync scenarios:
- Android-Android (both devices have bookmarks prior to sync chain creation)
- macOS-Android (both devices have bookmarks prior to sync chain creation, after sync chain is created, try adding/moving/deleting a bookmark on each device)
- macOS-Android (macOS had bookmarks prior to sync, but Android was fresh install)
- macOS-Android (Android had bookmarks prior to sync, but macOS was fresh install)
- macOS-Android (neither has bookmarks prior to sync, added bookmarks after sync chain created)
