### ISSUE TITLE
Sign-In with Ethereum (Android UI)

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#32077]
parent issue: https://github.com/brave/brave-browser/issues/32076

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.60.106 x64 build
- Verified steps from [brave/brave-core#20168](https://github.com/brave/brave-core/pull/20168) & [rave/brave-core#19443](https://github.com/brave/brave-core/pull/19443)
- Verified Sign-In with Ethereum UI is shown when trying to approve and sign-in on `https://login.xyz`
- Verified clicking on `See details` on SIWE UI shows details of the message
- Verified SIWE with resources list the resource details in the message details on `https://metamask.github.io/test-dapp`
- Verified error message is shown for `Wrong statement format`, `Domain mismatch`. `Account mismatch` and `Network mismatch` when format is wrong
- Verified no error message is shown and falls back to `EIP-191` format when an incorrect format is used

https://github.com/brave/brave-browser/assets/17010094/59324f63-e32c-4c04-ace9-e686ec34138e


---------------
Verification passed on Lenovo Tab with Android 13 running 1.60.106 x64 build
- Verified steps from [brave/brave-core#20168](https://github.com/brave/brave-core/pull/20168) & [rave/brave-core#19443](https://github.com/brave/brave-core/pull/19443)
- Verified Sign-In with Ethereum UI is shown when trying to approve and sign-in on `https://login.xyz`
- Verified clicking on `See details` on SIWE UI shows details of the message
- Verified SIWE with resources list the resource details in the message details on `https://metamask.github.io/test-dapp`
- Verified error message is shown for `Wrong statement format`, `Domain mismatch`. `Account mismatch` and `Network mismatch` when format is wrong
- Verified no error message is shown and falls back to `EIP-191` format when an incorrect format is used

Different Domain | Different chain ID| Different Account | SWIE Sign+Resources
-- | -- | -- | --
![image](https://github.com/brave/brave-browser/assets/17010094/e9772c53-4413-420e-8ea2-d17ee978f20b) | ![image](https://github.com/brave/brave-browser/assets/17010094/1d02c7b3-a85c-4224-b3ea-8027a2a6bea7) | ![image](https://github.com/brave/brave-browser/assets/17010094/703934a2-8d86-4cf4-a06e-7c5459f58e02) | <video src=https://github.com/brave/brave-browser/assets/17010094/6198fce1-0820-4c6b-90dd-dbf0c51f0f56>
