### ISSUE TITLE
Sidebar UI is not hidden with tab-initiated full screen

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#32080]
## Description 

Sidebar UI is not hidden with tab-initiated full screen. Only happens from `1.58.x`

## Steps to Reproduce

STR 1. (Regression from https://github.com/brave/brave-core/pull/19080)
   1. Set `Show always` for sidebar show option
   2. Load any youtube clip
   3. Click `f` to show youtube clip in fullscreen mode

STR 2. (Only nightly as playlist is available from nightly now)
   1. Enable playlist feature
   2. Add any youtube playlist item
   3. Play it from sidebar and click full screen button
  
## Actual result:

Sidebar UI is still visible

## Expected result:
It should be hidden

## Reproduces how often: 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes -`1.58.x`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.58.78 Chromium: 116.0.5845.51 (Official Build) nightly (x86_64)
-- | --
Revision | ca260d83d1ffda3cb35bff4bdc3251f30f9c8ccd
OS | macOS Version 11.7.9 (Build 20G1426)
```

## Case 1 - `PASSED`
<details>

### Steps:

1. Set `Show Sidebar` set to `Alwaays`
2. Load a YouTube video
3. Pressed `f` to show YouTube clip in fullscreen mode

### Confirmed no sidebar UI when entering fullscreen mode

example | example
---------|---------
<img width="1584" alt="Screen Shot 2023-08-07 at 3 58 40 PM" src="https://github.com/brave/brave-browser/assets/387249/25b3bd95-58b3-49dd-b829-c58d586e2ce9"> | ![Screen Shot 2023-08-07 at 3 18 40 PM](https://github.com/brave/brave-browser/assets/387249/7790efb8-dd64-4b8b-b1e6-2a520151f204) 


</details>

## Case 2 - `PASSED`
<details>

### Steps:

1. Enabled the playlist feature via `brave://flags`
2. Add a YouTube video as a playlist item
3. Played it from the sidebar and clicked its full screen button


### Confirmed no sidebar UI present (but bookmarks is; I'll investigate separately)

example | example | example
---------|---------|---------
<img width="1276" alt="Screen Shot 2023-08-07 at 3 21 48 PM" src="https://github.com/brave/brave-browser/assets/387249/d9461cc3-f88e-4b66-b16a-7b2943b01a62"> | ![Screen Shot 2023-08-07 at 3 49 37 PM](https://github.com/brave/brave-browser/assets/387249/7a374fba-5bc3-4dad-9182-e496011583cb) | ![Screen Shot 2023-08-07 at 3 49 13 PM](https://github.com/brave/brave-browser/assets/387249/eb4d07b4-a0cc-47ae-b3ff-9062f2454acf)


</details>

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.58.82 Chromium: 116.0.5845.62 (Official Build) beta (64-bit)
-- | --
Revision | cb261a5d3842ca2bf03c7eaa4da1d823b5c11b4e
OS | Windows 11 Version 22H2 (Build 22621.1992)
```
#### Case 1 - PASSED

<details>

Steps:

1. Install 1.58.82 
2. launch Brave
3. Sidebar is shown on the right 
4. Load a YouTube video
5. Pressed f to show YouTube clip in fullscreen mode

 ### Confirmed no sidebar UI when entering fullscreen mode

step 4 | step 5
------ | -----
<img width="954" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/802033a0-e500-4038-b996-01a637a3bcf3">|<img width="957" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/bf545dbb-44a2-4d77-8931-687f985f2287">

</details>

#### Case 2 

1. Enabled the playlist feature via brave://flags
2. Add a YouTube video as a playlist item
3. Played it from the sidebar and clicked its full screen button
4. Confirmed no sidebar UI present (but bookmarks is; I'll investigate separately)

<img width="950" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/8b9af377-0280-4678-9e60-05845b57c4d4">
