### ISSUE TITLE
Add icons and streamline application menu

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#32089]
## Description 

Add icons and reorganize application (hamburger) menu to provide clarity and improve access to the most common tasks. See design and Figma link.
Figma: https://www.figma.com/file/H11ZOl6JMYbCTW4ZJXqR5V/%F0%9F%A6%81-Browser?type=design&node-id=229-18698&mode=design&t=33C4DlnBLjohqt8i-0

- [x] https://github.com/brave/brave-browser/issues/32410
- [ ] Add icons to the menu

## Design

![screenshot_2023-08-03_at_8 39 40___am](https://github.com/brave/brave-browser/assets/5951041/52843c7b-c92b-418b-b2c5-7c81859784fa)

## Brave version (brave://version info)

Target 1.59.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by simonhong** [comment]
Created subtask for app menu restructuring - https://github.com/brave/brave-browser/issues/32410

**Comment by simonhong** [comment]
@rebron couldn't find `Brave Rewards` entry in new design.
Maybe it should be the first item in second part?

**Comment by rebron** [comment]
@simonhong We removed Brave Rewards in the app menu as we have prominent placement on the Address bar. Also note that the IPFS menu item is the location for when users turn on IPFS Local node. Otherwise, IPFS item won't be in the menu.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.59.92 Chromium: 117.0.5938.88 (Official Build) beta (x86_64)
-- | --
Revision | cf6e2f14e9e5a022c570aaa24e8c7ff7e4a541e5
OS | macOS Version 11.7.10 (Build 20G1427)
```

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.59.103 Chromium: 117.0.5938.140 (Official Build) beta (64-bit)
-- | --
Revision | e0f257d585b29dd1194e82717cf18db50a7c0edb
OS | Windows 11 Version 22H2 (Build 22621.2283)
```
### Shared Steps:
<details>

1. installed `1.59.92`
2. launched Brave
3. switched to the respective `Dark` or `Light` mode
4. iterated through top and second-level menus
5. confirmed icons for each menu-item's entry


</details>

### _`Dark`_ - Top-level app menu - `Pending` (*)
<details>

app menu (*)| Brave VPN | history flyout | bookmarks flyout | more tools (*) | help
-----------|-----------|---------------|------------------|------------|-----



</details>

### _`Light`_ - Top-level app menu - `Pending` (*)
<details>

app menu (*) | Brave VPN | history flyout | bookmarks flyout | more tools (*) | help
-----------|-----------|---------------|------------------|------------|-----


## `Private`, `Private with Tor`, and `Guest Profile` windows - `Pending` (*)
<details>

`Private` | `Private with Tor` | `Guest Profile`
----------|-------------------|--------------



## IPFS - `Pending` 
<details>

### Light | ###Dark

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave	1.59.103 Chromium: 117.0.5938.140 (Official Build) beta (64-bit) 
Revision	e0f257d585b29dd1194e82717cf18db50a7c0edb
OS	Linux
```

### Shared Steps:
<details>

1. installed `1.59.103`
2. launched Brave
3. switched to the respective `Dark` or `Light` mode
4. iterated through top and second-level menus
5. confirmed icons for each menu-item's entry


### _`Dark`_ - Top-level app menu - `Pending` (*)
<details>

app menu (*)| Brave VPN | history flyout | bookmarks flyout | more tools
-------|-------|-------|----------|---------
![image](https://github.com/brave/brave-browser/assets/98358127/3ef1e86f-fb01-4f46-898d-2e22ed442c59)


</details>

### _`Light`_ - Top-level app menu - `Pending` (*)
<details>

app menu (*) | Brave VPN | history flyout | bookmarks flyout | more tools (*) | help
-----------|-----------|---------------|------------------|------------|-----
![image](https://github.com/brave/brave-browser/assets/98358127/becf25c5-124c-403f-9fd4-9e2bf433c9db)
