### ISSUE TITLE
Remove Fantom from preloaded chains

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#32085]
Removing due to lack of on-chain activity. Number of preloaded chains adversely impacts wallet performance, so we want to be conservative here.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.59.109 Chromium: 118.0.5993.21 (Official Build) beta (64-bit)
-- | --
Revision | aacb6a6f8bd916bd49f064b2137b007fa6c47b51
OS | Windows 11 Version 22H2 (Build 22621.2283)

- Verified steps from [brave/brave-core#19574](https://github.com/brave/brave-core/pull/19574)
- Verified Fantom Opera is removed from preloaded networks on a clean profile
- Verified if Fantom Opera is set as default, post upgrade its added as a custom network

<video src=https://github.com/brave/brave-browser/assets/17010094/8a09320f-7728-475d-a47f-8dbc57de826b> | <video src=https://github.com/brave/brave-browser/assets/17010094/a6fbad0b-d23d-42a8-be75-b83e928a07a8>
-- | --
