### ISSUE TITLE
Add coinbase on-ramp(frontend)

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#32083]
Figma [link](https://www.figma.com/file/muVcmcu4RFNu0LkXe9VRDl/Wallet-2.0?type=design&node-id=4846-354863&mode=design&t=1Lv8hgM4qmYvea1v-0)

Test Plan:
- Go to brave://wallet
- Click on Buy
- On the buy page, select a token e.g Ethereum
- Click on Continue
- On the onramp page, Coinbase Pay should listed as an option
- Select coinbase pay
- A new tab opens and loads coinbase pay widget

**Comment by srirambv** [comment]
Verification passed on  

Brave | 1.58.100 Chromium: 116.0.5845.114 (Official Build) beta (64-bit)
-- | --
Revision | a8c0058265009a1858c4502b9ba413671fbb61e1
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from issue description
- Verified Coinbase is shown as an On-ramp provider on Buy screen
- Verified selecting Coinbase opens Coinbase pay widget is loaded in a new tab

https://github.com/brave/brave-browser/assets/17010094/b6a22f51-0a3a-469d-a7d4-e4e3e4e7a4ed
