### ISSUE TITLE
Option to disable autofill while in private browsing mode (Android)

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#32096]
Moved Android part from https://github.com/brave/brave-browser/issues/9795

**Comment by bsclifton** [comment]
Quick note - this should be a piece of cake after https://github.com/brave/brave-core/pull/19585 😄 

Basically, the preference and logic checking it is added - we'd just need to create a UI for it on Android (where user can toggle).

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version: 

```
Brave	1.65.101 Chromium: 123.0.6312.86 (Official Build) beta (64-bit) 
Revision	538d36e197a22168b9bbd79f136891e971c78c60
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

- Ensured that `Autofill in private tabs` setting is shown in `Settings` in the autofill 
- Ensured that autofill is disabled in private browsing when `Autofill in private tabs` is disabled.
- Ensured that disabling `Autofill in private tabs` does not impact autofill in normal tabs.

Setting | Normal mode | Private mode (enabled) | Private mode (disabled)
-|-|-|-
![Screenshot 2024-04-04 at 2 48 00 PM](https://github.com/brave/brave-browser/assets/17885425/3cf3e06e-448f-4966-b832-701551bf6b4f) | ![Screenshot 2024-04-04 at 2 55 36 PM](https://github.com/brave/brave-browser/assets/17885425/ea2744eb-c60b-405a-a8f5-7aa8592d7d86) | ![Screenshot 2024-04-04 at 2 49 03 PM](https://github.com/brave/brave-browser/assets/17885425/d523f49d-ab53-4aba-8ae1-fbc717f3f0e8) | ![Screenshot 2024-04-04 at 2 49 09 PM](https://github.com/brave/brave-browser/assets/17885425/a0a55805-fabb-4ab1-96a6-ce73ff9b8d73)
