### ISSUE TITLE
Add support for specifying custom enable/disable feature switches

### ISSUE THREAD

**Issue by mrzealot** [brave/brave-browser#3209]
I've found a diff between how Chromium and Brave handle console messages over the devtools protocol where console events from a non-top-level frame are not transmitted to the remote debugging entity in Brave. This leads back to how strict site-per-process isolation is handled; at least, specifying `--site-per-process` on Chromium makes it behave like Brave in that they are both "wrong" from the console messages' POV. Making them both "right" would probably require setting `--disable-features=IsolateOrigins,site-per-process` as per [these docs](https://www.chromium.org/Home/chromium-security/site-isolation), but Brave overrides this flag [here](https://github.com/brave/brave-core/blob/adf9ea89fa654769104d649dbacc93fc4b1c760e/app/brave_main_delegate.cc#L134).

I think this could be solved by being able to set custom disable switches, but there could be other interactions in the background I'm not aware of yet. Can share a MWE to test console event on the remote side if needed.

**Comment by iefremov** [comment]
It seems that `base::CommandLine` can't merge two `--disable-features` switches

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.61.38 Chromium: 73.0.3683.39 (Official Build) beta (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

Default:
![image](https://user-images.githubusercontent.com/34715963/53383123-cd9c2f80-3976-11e9-80ea-a41e8f577e6d.png)

With `--disable-features=IsolateOrigins,site-per-process` flag
![image](https://user-images.githubusercontent.com/34715963/53383138-d987f180-3976-11e9-9e67-7f4011a68caa.png)

**Comment by kjozwiak** [comment]
> Navigation to chrome://process-internals/#general causing webview crash

@GeetaSarvadnya did you create an issue for the above? Looks like it's only happening when you launch `Brave` using `--disable-features=IsolateOrigins,site-per-process` and visit `chrome://process-internals/#general` instead of `brave://process-internals/#general`. If you haven't, please create a new issue and CC @mkarolin.
