### ISSUE TITLE
Quitting installed PWA now also quits Brave

### ISSUE THREAD

**Issue by JakobJingleheimer** [brave/brave-browser#32100]
## Description 
Until recently, quitting an installed PWA (eg open.spotify.com) quit only the PWA. Now it also quits Brave, which is extremely undesirable and causes work to be lost.

## Steps to Reproduce

Preconditions: Install a PWA (ex open.spotify.com)

   1. Open the installed PWA (with or without Brave already running)
   2. Ensure the PWA is focused
   3. Quit the PWA (<kbd>cmd</kbd> + <kbd>Q</kbd>)

## Actual result:

Both the PWA **and** Brave are terminated.

## Expected result:

Only the PWA is terminated.

## Reproduces how often: 
100%

## Brave version (brave://version info)
Brave is up to date
Version 1.56.20 Chromium: 115.0.5790.171 (Official Build) (arm64)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Unknown
- Can you reproduce this issue with the nightly channel? Unknown

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Unknown

**Comment by JakobJingleheimer** [comment]
Nudge.

This bug is super obnoxious.

**Comment by JakobJingleheimer** [comment]
This appears to be fixed as of `Version 1.57.57 Chromium: 116.0.5845.163`, but I don't see anything relevant in either the Brave or Chromium release notes.

**Comment by ejm554** [comment]
I recently created a PWA for a website (linkedin.com), and I'm encountering this issue, just as described by @JakobJingleheimer. 

My version info is different, however, from the ones reported ~18 months ago. I'm also not sure if the OS differs, of if that is even a factor.

**My Version Details**
Brave: `1.76.80 Chromium: 134.0.6998.118 (Official Build) (x86_64)`
OS: `macOS Version 11.7.10 (Build 20G1427)`
