### ISSUE TITLE
Unable to Sign Solana Transaction

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#32109]
## Description 

The Wallet `Panel` breaks when attempting to sign a `Solana` transaction

## Steps to Reproduce

   1. Go to https://raydium.io/swap and create a swap
   2. When the Wallet `Panel` prompts, click continue
   3. The `Panel` will break and you are unable to `Sign` the transaction

## Actual result:

![Screenshot 46](https://github.com/brave/brave-browser/assets/40611140/3aef969b-0c52-4390-ac2b-b7791a0d84a4)

## Expected result:
Should allow you to sign.

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.57.45` or higher for `1.57.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.57.45 Chromium: 116.0.5845.82 (Official Build) (64-bit)
-- | --
Revision | c43241b101a636729252df90d1a1a7b72f2a9f94
OS | Linux

- Verified steps from [brave/brave-core#19589](https://github.com/brave/brave-core/pull/19589)
- Verified able to Sign Swap transactions on Solana Dapps

https://github.com/brave/brave-browser/assets/17010094/2c26081f-eb07-4c52-b490-336d968b389e
