### ISSUE TITLE
Youtube Ads

### ISSUE THREAD

**Issue by AuracleTech** [brave/brave-browser#32115]
## Description 
YouTube has ads

## Steps to Reproduce

   1.  YouTube
   2.  Ads

## Actual result:
![image](https://github.com/brave/brave-browser/assets/40531871/e7673d4f-90df-4bf3-960e-9bd87af1a637)

## Expected result:
No ads

## Reproduces how often: 
101%

## Brave version (brave://version info)
1.56.20 Chromium: 115.0.5790.171

## Version/Channel Information:
Stable I guess

- Can you reproduce this issue with the current release?  Yeah
- Can you reproduce this issue with the beta channel?  No idea
- Can you reproduce this issue with the nightly channel?  Zero idea

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  No
- Does the issue resolve itself when disabling Brave Rewards?  No
- Is the issue reproducible on the latest version of Chrome? Yes

## Miscellaneous Information:
Man I hate ads

**Comment by AuracleTech** [comment]
I'll eat my own hands raw before paying for a problem they created

**Comment by BetaTester41** [comment]
I also started getting ads after it has worked so perfectly in the years before. Hopefully the ads can still be blocked in the future.

**Comment by yongjer** [comment]
I've faced the same issue that started this morning

**Comment by sinha5432** [comment]
For me, just the audio of ads is being played, no video.

If this is an intended change due to chromium, I will have to switch to some other browser

**Comment by twangodev** [comment]
The ad banners on the side of YouTube are also back too. We love it when Google throws new ad updates.

**Comment by aHappyConstant** [comment]
Same case for me, but the ads don't show up but instead a black screen is presented in the player.

![image](https://github.com/brave/brave-browser/assets/97287115/08b916ea-7252-4a95-9b21-1bcf91592ff1)

**Comment by hulpnano** [comment]
This sucks. Having the same issue on AUR version. Hope this is fixed soon for now im just going to use my phone because i dont wanna download any extensions.

**Comment by Fiksas** [comment]
I only get same ads from two same companies in 7 videos in a row. Thank god they are skippable.

**Comment by andrewharrop** [comment]
Noticed that some ads are not displaying(shows a black screen), but the audio plays

**Comment by anthony1x6000** [comment]
> Have you heard of ublock origin (which at least for me works better), noscript, youtube enhancer (in the settings you can disable ads)

I think big thing about having a built-in ad-blocker is to reduce the number of unnecessary extensions, which can be used to fingerprint users.

**Comment by CodeCubeNeo** [comment]
Thats fair ig. doesnt the browser hide which extensions you are using?

**Comment by bsclifton** [comment]
Hi folks - this issue has been resolved 😄 There are a few ways you can solve:
- Exit/relaunch Brave
- open `brave://components` in the URL bar, look for `Brave Ad Block Resources Library` and click `Check for update`

Once the component is updated to `1.0.54` or newer you're good to go. You can reload the YouTube page (Ctrl + Shift + R)

**Comment by bsclifton** [comment]
For reference, should have been fixed with https://github.com/brave/brave-core-crx-packager/pull/662

Job packaging up the new rules then ran at 10:14pm pacific (7 Aug)
