### ISSUE TITLE
Animal Planet videos do not load

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#3211]
## Description 
Videos on animalplanet.com do not load with Ads and Tracker blocking turned ON under shields.

## Steps to Reproduce
   1. Visit https://www.animalplanet.com/tv-shows/my-cat-from-hell/videos/dexter-the-meowing-machine

## Actual result:

![image](https://user-images.githubusercontent.com/741836/52227526-9e593d80-2864-11e9-825e-abcbdc77959a.png)

## Expected result:
![image](https://user-images.githubusercontent.com/741836/52227611-dbbdcb00-2864-11e9-98aa-e4286af96f72.png)

## Reproduces how often: 

100%

## Brave version (brave://version info)

Version 0.60.17 Chromium: 72.0.3626.64 (Official Build) dev (64-bit)

Brave Tracking Protection Updater - Version: 1.0.6
Status - Update error

Brave Ad Block Updater - Version: 1.0.121
Status - Update error

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? Yes
- Is the issue reproducible on the latest version of Chrome? **Reproduces with Chrome+uBlockOrigin.**

**Comment by ryanbr** [comment]
@petemill just tested this in Brave Release (Version 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit)) Video playback is fine.

**Comment by bsclifton** [comment]
Works great for me too- going to close this out
