### ISSUE TITLE
NFT images crashing storybook

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#32114]
## Description 

When viewing components that attempt to render NFT images from storybook, an error occurs
This has to do with the iframe sandboxing in production. We should remove this sandboxing in storybook since we use mocked data for NFTs

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.59.109 Chromium: 118.0.5993.21 (Official Build) beta (64-bit)
-- | --
Revision | aacb6a6f8bd916bd49f064b2137b007fa6c47b51
OS | Windows 11 Version 22H2 (Build 22621.2283)

- Verified steps from [brave/brave-core#19597](https://github.com/brave/brave-core/pull/19597)
- Verified no crash when loading NFT details on both NFT tab and Panel

https://github.com/brave/brave-browser/assets/17010094/3bdf307a-4789-484e-91d0-2dbe282026e8
