### ISSUE TITLE
Provide option to dismiss end of support notice message for macOS

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#32129]
## Description 

Follow-up of https://github.com/brave/brave-browser/issues/27122 but for macOS. Needed to support 1.57.x which is the last supported version for macOS 10.13 and 10.14.

## Expected result:
Same as ability to dismiss infobar as we did for Windows 7 or 8 with confirmation dialog. 
https://github.com/brave/brave-browser/issues/27649

Infobar
![259275473-9d19e3c9-8255-4641-99c6-91859e0254b7](https://github.com/brave/brave-browser/assets/5951041/cc0af0e5-749f-4ac2-ab1a-eb8c181ff231)

Learn more link should point to: 
`https://support.brave.com/hc/en-us/articles/18347246446733-Changes-to-macOS-desktop-browser-requirements`

Confirmation dialog
![image_720-1](https://github.com/brave/brave-browser/assets/5951041/570d6fe8-4ec4-429a-abcd-f8b0493ac295)

## Version/Channel Information:
 n/a

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

Need to add IS_MAC to https://github.com/brave/brave-core/blob/master/chromium_src/chrome/browser/ui/startup/infobar_utils.cc#L26

Additional strings for: 
https://github.com/brave/brave-browser/issues/27122#issuecomment-1396311656

**Comment by mkarolin** [comment]
Chromium's implementation without the dismiss option:

![image](https://github.com/brave/brave-browser/assets/41635752/cf24abd4-356c-4710-adb4-bfa6e86bbebd)

**Comment by mkarolin** [comment]
With dismiss option:

![image](https://github.com/brave/brave-browser/assets/41635752/9d19e3c9-8255-4641-99c6-91859e0254b7)

Dismissing with checkbox checked:

![image](https://github.com/brave/brave-browser/assets/41635752/842448e2-5309-455b-9f60-072f9b55ca11)

**Comment by kjozwiak** [comment]
Quick note to @brave/qa-team, the above won't be translated as it missed translations earlier in the week. We'll need to get the above translated in `1.58.x`. @mkarolin assuming this will be done automatically or should we create a new issue just in case?

**Comment by kjozwiak** [comment]
The above requires `1.57.47` or higher for `1.57.x` verification 👍 QA can use https://github.com/brave/brave-core/pull/19618#issuecomment-1678319664 as the template for STR/Cases to run through.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.57.47 Chromium: 116.0.5845.96 (Official Build) (x86_64) 
Revision	180d2fdf443f9be410c38fd8c4ccfe7e99ea2b16
OS	macOS Version 10.14.6 (Build 18G103)
```

**Comment by mkarolin** [comment]
> Quick note to @brave/qa-team, the above won't be translated as it missed translations earlier in the week. We'll need to get the above translated in `1.58.x`. @mkarolin assuming this will be done automatically or should we create a new issue just in case?

It will get translated automatically with `1.58.x`.

**Comment by mkarolin** [comment]
@kjozwiak created https://github.com/brave/brave-browser/issues/32259. Not sure if there's enough time to get it into the release, but could go into a HF or CR bump.
