### ISSUE TITLE
Bookmark button gets unfilled on bookmarked page when scrolling

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#32121]
## Description 
Bookmark button gets unfilled on bookmarked page when scrolling

https://github.com/brave/brave-browser/assets/30602739/ef29d9d9-19c4-4105-b159-bb8fbc2d2879

## Steps to reproduce 

   1. Bookmark any scrollable page.
   2. Start scrolling to make bottom toolbar disappear.
   3. Bookmark button gets unfilled.

## Actual result 
Bookmark button gets unfilled.

## Expected result
State of bookmark button not changed.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
1.57.x

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
awesome catch @samartnik 👍 The above requires `1.57.45` or higher for `1.57.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21 5G` using version(s):

```
Brave	1.57.45 Chromium: 116.0.5845.82 (Official Build) (32-bit) 
Revision	c43241b101a636729252df90d1a1a7b72f2a9f94
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

- Verified bookmark button stays filled when scrolling on the page on fresh and existing profile
- Verified scrolling on the page does not change bookmark button state when opening bookmarks from sync chain.

<table><tr><td>Fresh Profile</td><td>Existing Profile</td></tr>

<tr><td>

https://github.com/brave/brave-browser/assets/17885425/32fa21ee-4b85-44a8-aeee-25a2b2d442d7

</td><td>

https://github.com/brave/brave-browser/assets/17885425/fd8aa4ee-4514-43b5-8a13-39b40dbb6788

</td></tr></table>
