### ISSUE TITLE
Add P3A questions for search engine promo banner in address bar

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#32130]
Adding P3A questions for the Brave Search promo banner in the address bar. The will be four variations of the question below, one for each banner type (`Brave.Search.Promo.BannerA`, `Brave.Search.Promo.BannerB`, `Brave.Search.Promo.BannerC` and `Brave.Search.Promo.BannerD` ). Only one variant will be reported for a given user.

Did the participant in the search promo banner group click on the promo and did they switch their default engine to Brave Search?

0. Did not click on banner, did not switch their default engine
1. Did click on banner, did not switch their default engine
2. Switched default engine, but did not click on banner
3. Clicked banner & switched default engine

**Comment by kjozwiak** [comment]
The above requires `1.58.120` or higher for `1.58.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.58.120 Chromium: 117.0.5938.48 (Official Build) (64-bit)
-- | --
Revision | 8b2e2785c90c076fc1413acb2c003e603eac02d3
OS | Windows 10 Version 22H2 (Build 19045.3324)
```
