### ISSUE TITLE
Chrome Extension Sidepanel API not working in Brave

### ISSUE THREAD

**Issue by cyfung1031** [brave/brave-browser#32132]
## Description 

I am make a chrome extension MV3 with sidePanel API
It works normally in Chrome but not in Brave.
The sidepanel was successfully displayed with the correct content but after 1s it disappeared.
The "Show/Hide Sidebar" button's status remains unchanged.
No matter how many times I click it, it just toggle the icon status without actually showing the sidebar content.

## Steps to Reproduce

   1. Load unpacked extension, with MV3, sidePanel permission, side_panel's default_path, and action's default_title for the icon button pinned in the right of address bar.
   2. enable the extension if not enabled
   3. the icon of my extension is shown
   4. click it
   5. the sidepanel will be shown.
   6. after 1s, it disappears.

## Actual result:
<img width="204" alt="Screen Shot 2023-08-09 at 9 06 51" src="https://github.com/brave/brave-browser/assets/44498510/923fb8d7-fc5c-4eb8-8dc1-6b4c753eac23">

## Expected result:
sidepanel shall remain until the user closes it.

## Reproduces how often: 
100% when i try to open the sidepanel.

## Brave version (brave://version info)

Brave | 1.56.20 Chromium: 115.0.5790.171 (Official Build) (arm64)
-- | --
Revision | cf9067bf10d8f798c24643029af1d24e275646d6-refs/branch-heads/5790@{#1924}
OS | macOS Version 12.6.1 (Build 21G217)

**Comment by simonhong** [comment]
@cyfung1031 Would you check your side panel extension with nightly version?
We had some regression for side panel extension and most of them were fixed from current nightly.

**Comment by picsoung** [comment]
I had the same flow described by @cyfung1031 
And it worked well with nightly build.

**Comment by cyfung1031** [comment]
> @cyfung1031 Would you check your side panel extension with nightly version(1.58.x)? We had some regression for side panel extension and most of them were fixed from current nightly.

I would not use nightly version. I believe nightly version is just for testers not for the public. If those features are not available, warning messages shall be provided.

Anyway, I am glad that the side panel can be shown now in Brave v1.58.124 (Sep 14, 2023) as a stable release.

Issue can be closed now.
