### ISSUE TITLE
Update coinbase pay on-ramp description

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#32147]
Update coinbase description to: "Buy with the most trusted name in crypto."

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.59.109 Chromium: 118.0.5993.21 (Official Build) beta (64-bit)
-- | --
Revision | aacb6a6f8bd916bd49f064b2137b007fa6c47b51
OS | Windows 11 Version 22H2 (Build 22621.2283)

- Verified steps from issue description
- Verified Coinbase pay on-ramp description is updated to `Buy with the most trusted name in crypto.`
![brave_2Ys3Z1bq6x](https://github.com/brave/brave-browser/assets/17010094/1be2d0bc-ab63-481d-bf90-60ba382ed7cb)
