### ISSUE TITLE
Add support for IKEv2 to tray executable

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#32143]
## Description 

In https://github.com/brave/brave-browser/issues/32002 we added a toggler between WrieGuard and IKEv2 protocols. The executable started on each startup launch from https://github.com/brave/brave-browser/issues/32003 and need to add support for IKEv2 connection to it

![image](https://github.com/brave/brave-browser/assets/2965009/389f0b2b-d74c-4b81-a82a-f4844eb480fb)

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.59.95 Chromium: 117.0.5938.88 (Official Build) beta (64-bit)
-- | --
Revision | a2cb6fb53ea2c9ab356de955aab8505f5455b8bb
OS | Windows 11 Version 22H2 (Build 22621.2283)
```


Case 1:  Added IKEv2 support for status tray icon

1. Installed 1.59.95
2. launched Brave
3. purchase and configure Brave VPN
4. opened `brave://settings/system`
5. disabled `Use Wireguard protocol in Brave VPN` 
6. connected & disconnected to Brave VPN
   - via VPN panel
   - via Taskbar Network settings
   - via System >> Network & internet
   - via Brave VPN status tray icon

#### Confirmed when Brave VPN is connected via IKEv2 protocol, System tray icon shows correct connection status with green
#### Confirmed when Brave VPN is disconnected via IKEv2 protocol, System tray icon shows correct connection status







Status tray icon launched if any of BraveVPN protocols connected
Show system notifications if brave IKEv2 vpn connected (only if dns helper started)



Check that Brave VPN status tray icon allow to manage both BraveVPN protocols, Ras/Wireguard
Check if users enable vpn using system Brave VPN RAS connection entry, the tray icons shows and updates connection status correctly
Check that the icon becomes visible if it was not visible and IKEv2 connected.
Check that browser shows system notifications if Brave IKEv2 vpn connected (only if dns helper started)

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```

```
