### ISSUE TITLE
Add loading effect in portfolio asset view when balances are being fetched

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#32141]
When balances are being fetched, the highlighted section should display a loading effect.

<img width="753" alt="Screenshot 2023-08-09 at 12 26 33" src="https://github.com/brave/brave-browser/assets/3684187/07b7bb09-ad8e-4de2-8abf-1c474bb07659">

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.65.96 Chromium: 123.0.6312.86 (Official Build) beta (64-bit)
-- | --
Revision | 5d9143e1a0812c53bdc27fd5384591254306a88c
OS | Windows 11 Version 23H2 (Build 22631.3296)

- Verified steps from [brave/brave-core#22409](https://github.com/brave/brave-core/pull/22409)
- Verified loading state indicator is shown on portfolio asset view when balances are being fetched

https://github.com/brave/brave-browser/assets/17010094/a548acdd-e007-4db2-bda9-08a24da0c646
