### ISSUE TITLE
Add rounded corners to all panels from the navigation bar

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#32150]
## Description 

Follow-up to https://github.com/brave/brave-browser/issues/28622 which added rounded corners to the Brave Rewards panel.

- [ ] Bookmarks panel
- [ ] In address bar: Tune/site settings panel
- [ ] In address bar: PWA menu 
- [ ] In address bar: Brave News feeds menu
- [ ] In address bar: Share menu
- [ ] Shields panel
- [ ] Extensions panel
- [ ] Downloads panel 
- [ ] Wallet 2.0 panel

## Expected result:
[placeholder for Figma designs}

## Reproduces how often: 

n/a

## Brave version (brave://version info)

n/a

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.59.90 Chromium: 117.0.5938.88 (Official Build) beta (64-bit)
-- | --
Revision | 5272112c86588e44ec7c0b766c318cddccbced85
OS | Windows 11 Version 22H2 (Build 22621.2283)
```
Install 1.59.90
Launch Brave
open following panels from the navigation bar

  -  Bookmarks panel - [✓] 
  -  In address bar: Tune/site settings panel- [✓] 
  -  In address bar: PWA menu- [✓] 
  -  In address bar: Brave News feeds menu - [✓] 
  -  In address bar: Share menu- [✓] 
  -  Shields panel - [✓] 
  -  Extensions panel- [✓] 
  -  Downloads panel- [✓] 
  -  Wallet 2.0 panel - [✓] 

### Confirmed rounded corners are shown 

` Bookmarks panel`
`1.58.127` | `1.59.90(Light)`| `1.59.90(Dark)`
------ | ----- | -----
<img width="237" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/44773016-0fba-4e4b-8a73-7e7e5c11accc">|<img width="223" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/e2e5d687-e928-4754-b87c-dd787b3f8c5a">|<img width="220" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/6d8aa557-aa35-49a7-a862-b13bdd1267cc">


` In address bar: Tune/site settings panel`
`1.58.127` | `1.59.90(Light)`| `1.59.90(Dark)`
------ | ----- | -----
<img width="243" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/2abdff76-5d6f-463c-a34a-bf0d148c6878">|<img width="243" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/e813051b-fbf3-49c9-9c98-18ee1b8d6f69">|<img width="231" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/e1ce8038-d69f-4fda-92ed-5702c5ed3f73">

 In address bar: PWA menu
`1.58.127` | `1.59.90(Light)`| `1.59.90(Dark)`
------ | ----- | -----
<img width="208" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/74a422fa-e362-483e-8bf8-184aaf4014ef">|<img width="224" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/ee347cfe-177e-4ec5-a508-ac5f8a74117d">|<img width="208" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/89e82774-70df-4fab-b355-008f37dcc05a">

In address bar: Brave News feeds menu
`1.58.127` | `1.59.90(Light)`| `1.59.90(Dark)`
------ | ----- | -----
<img width="171" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/a4b878b3-ea15-4ba2-92d7-b3962aa95943">|<img width="178" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/d6f3f7f4-29ae-4c09-b083-99bec1d6aa30">|<img width="179" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/9c02c016-2735-47f4-9b58-a401a74abcf0">

 In address bar: Share menu
`1.58.127` | `1.59.90(Light)`| `1.59.90(Dark)`
------ | ----- | -----
<img width="213" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/546b7026-69ab-48d4-b751-b8c74d99a542">|<img width="213" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/8a3e68a3-b58c-46ff-8eac-cb2a1ef64a1b">|<img width="241" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/00a4b408-f215-469b-8106-c7d436863758">

`Shields panel` 
`1.58.127` | `1.59.90(Light)`| `1.59.90(Dark)`
------ | ----- | -----
<img width="278" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/7f911a12-a88c-426b-8af8-cecbe47f479e">|<img width="278" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/8f9d240f-194c-4433-a84e-621742385c6a">|<img width="278" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/cb1005e7-0dbd-4085-bfae-609e5c92b6dc">

`VPN Panel`
`1.58.127` | `1.59.90(Light)`| `1.59.90(Dark)`
------ | ----- | -----
<img width="221" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/ed2e4278-3549-40ff-b715-34c559fc3f88">|<img width="215" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/abb625b7-6c56-4d1f-9262-8e89080770ff">|<img width="218" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/104db06d-b0be-42bd-aff3-b0793598760a">

 `Extensions panel`
`1.58.127` | `1.59.90(Light)`| `1.59.90(Dark)`
------ | ----- | -----
<img width="219" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/964e6859-3ab1-4ab3-8953-2fef2f36d47e">|<img width="212" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/16268149-db88-4cf7-8c1e-ac9c1a3dd12c">|<img width="210" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/f15fdeea-57bf-404b-9ab5-c2d5d25aa19f">

 `Downloads panel`
`1.58.127` | `1.59.90(Light)`| `1.59.90(Dark)`
------ | ----- | -----
<img width="217" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/04d7a37b-b3a5-4292-ad58-c817394a1907">|<img width="230" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/9251f29f-105e-4801-8255-8c25e8717ac7">|<img width="224" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/b65b1503-722e-4b89-856e-f1581cc89c60">

 `Wallet 2.0 panel`
`1.58.127` | `1.59.90(Light)`| `1.59.90(Dark)`
------ | ----- | -----
<img width="213" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/2c1b462e-e4db-4522-afc2-056636253ad3">|<img width="210" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/63a79707-013d-4f34-bfe4-45059a0efdcc">|<img width="213" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/1d935458-bdbe-4d2d-9432-5e2b758b54fc">

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.59.92 Chromium: 117.0.5938.88 (Official Build) beta (x86_64)
-- | --
Revision | cf6e2f14e9e5a022c570aaa24e8c7ff7e4a541e5
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.59.92`
2. launched Brave
3. opened the following panels in the navigation bar

  -  Bookmarks panel - [✓] 
  -  In address bar: Tune/site settings panel - [✓] 
  -  In address bar: PWA menu - [✓] 
  -  In address bar: Brave News feeds menu - [✓] 
  -  In address bar: Share menu - [✓] 
  -  Shields panel - [✓] 
  -  Extensions panel - [✓] 
  -  Downloads panel - [✓] 
  -  Wallet 2.0 panel - [✓] 

### Confirmed rounded corners are shown for all the feature panels

` Bookmarks panel`
<details>

`1.58.127` | `1.59.92 (Light)`| `1.59.92 (Dark)`
------ | ----- | -----


</details>

` In address bar: Tune/site settings panel`
<details>

`1.58.127` | `1.59.92 (Light)`| `1.59.92 (Dark)`
------ | ----- | -----


</details> 

`In address bar: PWA menu`
<details>

`1.58.127` | `1.59.92 (Light)`| `1.59.92 (Dark)`
------ | ----- | -----


</details>

`In address bar: Brave News feeds menu`
<details>

`1.58.127` | `1.59.92 (Light)`| `1.59.92 (Dark)`
------ | ----- | -----



</details>

`In address bar: Share menu`
<details>

`1.58.127` | `1.59.92 (Light)`| `1.59.92 (Dark)`
------ | ----- | -----

</details>

`Shields panel` 
<details>

`1.58.127` | `1.59.92 (Light)`| `1.59.92 (Dark)`
------ | ----- | -----

</details>

`VPN Panel`
<details>

`1.58.127` | `1.59.92 (Light)`| `1.59.92 (Dark)`
------ | ----- | -----

</details>

 `Extensions panel`
<details>

`1.58.127` | `1.59.92 (Light)`| `1.59.92 (Dark)`
------ | ----- | -----



</details>

 `Downloads panel`
<details>

`1.58.127` | `1.59.92 (Light)`| `1.59.92 (Dark)`
------ | ----- | -----

</details>

 `Wallet 2.0 panel`
<details>

`1.58.127` | `1.59.92 (Light)`| `1.59.92 (Dark)`
------ | ----- | -----


</details>

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.59.107 Chromium: 117.0.5938.140 (Official Build) beta (64-bit) 
Revision	5bbd53ed3e41461e15555b7ce0490464656b236f
OS	Linux
```
