### ISSUE TITLE
Bookmarks order changes under same folder doesn't work

### ISSUE THREAD

**Issue by darkdh** [brave/brave-browser#3216]
## Steps to Reproduce

   1. Setup sync between device A and device B with `F1`, `F2` under toolbar
   2. Waiting for F1 and F2 show on both devices
   3. Swap the positions of F1 and F2 to make it `F2`, `F1` on device A

## Actual result:

device B still shows F1, F2

## Expected result:
device B should have F2, F1

## Reproduces how often: 

100%

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
Verification passed on

Brave | 0.62.28 Chromium: 73.0.3683.75 (Official Build) beta (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17134.523

Device1:

![image](https://user-images.githubusercontent.com/38657976/54620420-23528c00-4a8c-11e9-8796-735648bb1c3c.png)


Device2:
![image](https://user-images.githubusercontent.com/38657976/54620332-04ec9080-4a8c-11e9-9454-665ab66646d6.png)
