### ISSUE TITLE
WireGuard does not change servers when connected

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#32176]
## Description 

Connect to vpn using WireGuard protocol and switch servers, it connects to old server.

## Steps to Reproduce

   1. Connect to vpn using WireGuard protocol 
   2. switch servers,
   3. Check with browserleaks or any other site 

## Actual result:

it connects to old server.

## Expected result:

it connects to new selected server.

## Reproduces how often: 

often

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
## Verification `PASSED` using 

```
Brave | 1.59.94 Chromium: 117.0.5938.88 (Official Build) beta (64-bit)
-- | --
Revision | 2dca22d0a20096c32df5af4c88700a0b31acb55c
OS | Windows 10 Version 22H2 (Build 19045.3448)
```

### Steps:
1. installed `1.59.94`
2. launched Brave
3. confirmed `Use WireGuard protocol in Brave VPN` was enabled by default in `brave://settings/system`
4. purchased, configured, and connected to `Brave VPN`
5. clicked on the `VPN` button on the browser toolbar
6. clicked on the server/region-selection widget
7. selected various servers/regions, and clicked `Connect`

example | example | example | example
----------|-----------|----------|----------
![image](https://github.com/brave/brave-browser/assets/387249/aa9a9797-40ea-410c-8ef0-03e2ffb9c98d) | ![image (3)](https://github.com/brave/brave-browser/assets/387249/e9ed8d07-bcb1-4a7a-9f09-3604bb398641) | ![image (2)](https://github.com/brave/brave-browser/assets/387249/dc18251b-333e-4c02-bc42-853c06b1fbab) | ![image (1)](https://github.com/brave/brave-browser/assets/387249/4cbe9857-ae65-4177-aae2-89f799e98b60)

`Japan`| `Australia` | `USA (West)` | `Canada` | `France`
----------|-----------|----------|--------------|---------
![image (7)](https://github.com/brave/brave-browser/assets/387249/80bb0a14-8c81-46e3-9a36-2f1c16c7ed87) | ![image (6)](https://github.com/brave/brave-browser/assets/387249/9323ce4d-bb1f-43f6-8a24-f53c43b1e0d4) | ![image (5)](https://github.com/brave/brave-browser/assets/387249/6d840ea6-47fd-4a6f-b512-3cf7351ee54e) | ![image (4)](https://github.com/brave/brave-browser/assets/387249/321536d6-ce46-4750-bc70-2ff79ba845b5) | ![image](https://github.com/brave/brave-browser/assets/387249/988f2586-99f6-4f5d-b549-731654343a35)

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```

```

**Comment by LaurenWags** [comment]
Changing to `release-notes/exclude` per discussion with @kjozwiak @rebron - will use https://github.com/brave/brave-browser/issues/32002 as the main WireGuard issue in the notes.
