### ISSUE TITLE
typo in extension settings (Widevine)

### ISSUE THREAD

**Issue by radioactive1337** [brave/brave-browser#32184]
## Description 
typo in extension settings (Widevine)

## Steps to Reproduce

   1. open settings (настройки)
   2. open extensions tab (расширения)

## Actual result:

1. settings is opened
2. extensions tab is opened and description of 'Widevine' is correct

## Expected result:
1. settings is opened
2. the extensions tab is open and the description contains a typo
![image](https://github.com/brave/brave-browser/assets/101940002/71d53be8-e389-4390-8b67-ed2db9101109)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Version 1.56.20 Chromium: 115.0.5790.171

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? - no
- Does the issue resolve itself when disabling Brave Rewards? - no
- Is the issue reproducible on the latest version of Chrome? - no

**Comment by rebron** [comment]
cc: @mkarolin

**Comment by mkarolin** [comment]
Updated in Trasifex to

`Использовать компонент управления цифровыми правами (DRM) Widevine для просмотра защищенного потокового видео- и другого контента в браузере.`

The translation will be pulled down for 1.57.x release with https://github.com/brave/brave-browser/issues/32203

**Comment by kjozwiak** [comment]
Closing as the above was uplifted into `1.57.x` via https://github.com/brave/brave-core/pull/19669. The above requires `1.57.47` or higher for `1.57.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.57.47 Chromium: 116.0.5845.96 (Официальная сборка) (x86_64)
-- | --
Версия | 180d2fdf443f9be410c38fd8c4ccfe7e99ea2b16
ОС | macOS Версия 11.7.9 (Выпуск 20G1426)

### Steps:
1. installed `1.57.47`
2. changed system language to `Russian`
3. rebooted
4. launched Brave
5. opened `brave://settings/extensions`
6. checked strings for the Widevine setting

### Confirmed typo fix in Russian

<img width="1350" alt="Снимок экрана 2023-08-15 в 9 04 15 AM" src="https://github.com/brave/brave-browser/assets/387249/8408b7dd-ec2c-4866-8785-c766e48720a1">



before | after
-------|-----
<img width="558" alt="Screen Shot 2023-08-15 at 9 06 24 AM" src="https://github.com/brave/brave-browser/assets/387249/97a071fc-cdc7-4a07-b891-8fe3027ef640"> | <img width="577" alt="Screen Shot 2023-08-15 at 9 07 48 AM" src="https://github.com/brave/brave-browser/assets/387249/dfcc9ea1-d22f-426d-91fe-9d8d4a12250a">
