### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Voldemorten** [brave/brave-browser#32183]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.56.20 Chromium: 115.0.5790.171
Operating System: Mac OS X 13.4.1

URL (if applicable) where crash occurred: https://www.youtube.com/watch?v=-W2M9-B4NtM

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Watch any video
2. Make it full-screen
3. Click esc

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/cdb20100-b0e3-890a-0000-000000000000

**Comment by atuchin-m** [comment]
The dump shows the issue with https://github.com/brave/brave-core/blob/master/browser/ui/views/frame/vertical_tab_strip_region_view.cc#L1304-L1305.

@sangwoo108 Could you please take a look?
<img width="566" alt="image" src="https://github.com/brave/brave-browser/assets/45488748/acd114b0-80fb-4348-95fa-d8aa1e78f836">

**Comment by sangwoo108** [comment]
Unfortunately, I wasn't able to reproduce this on my Mac. @Voldemorten , I'm wondering if this always happen to you, and if you're using vertical tabs.

**Comment by Voldemorten** [comment]
@sangwoo108 I am using vertical tabs. I just tried to disable it, and the problem disappeared.

**Comment by kjozwiak** [comment]
> @sangwoo108 I am using vertical tabs. I just tried to disable it, and the problem disappeared.

Thanks @Voldemorten 👍 Going to label the above as `QA/No` as it seems to be hard to reproduce. However, we'll get this uplifted into `1.57.x` and push a release within the next week. Once there's a new version, mind letting us know if the issue has been resolved?

**Comment by Voldemorten** [comment]
Just wanted to update. When I do it on `Version 1.57.47 Chromium: 116.0.5845.96 (Official Build) (x86_64)` 
Now the tabs are disappearing in vertical pane, and it looks like they somehow get "behind" the address bar. Then when you disable vertical tabs, they glitch in the top. Reenable vertical tabs and they appear horizontal in the vertical pane. Disable and reenable again, and we're back to normal. 

I've uploaded a video of it here: https://youtu.be/hEtXWgdekYc

**Comment by Voldemorten** [comment]
It's the same with any full screen window. Not just videos. Try to go to: https://jsonformatter.curiousconcept.com/, input some json and click the full screen button. That also crashes the tabs as explained above. 

Ping @sangwoo108, @kjozwiak

**Comment by sangwoo108** [comment]
@Voldemorten Thank you for confirmation!

**Comment by Voldemorten** [comment]
This is an issue once more. And now you also don't get feedback when selecting multiple vertical tabs (i.e. for shutdown. They don't highlight)
@sangwoo108

**Comment by sangwoo108** [comment]
HI, @Voldemorten . Sorry for the inconvinience. The latter sounds like https://github.com/brave/brave-browser/issues/32892 . Could you let me know about your verision?

**Comment by Voldemorten** [comment]
@sangwoo108 [Version 1.59.122 Chromium: 118.0.5993.96 (Official Build) (x86_64)](https://brave.com/latest/)

**Comment by sangwoo108** [comment]
Yeah, that makes sense. A fix for the multi tab selection was merged to 1.60.x.

**Comment by sangwoo108** [comment]
As for the crash when exiting the fullscreen, I'm not seeing that on my machine. Do you happen to have a crash id?

**Comment by Voldemorten** [comment]
It's not exactly a crash. But it's the same thing that happens in this video: https://youtu.be/hEtXWgdekYc. It worked for a while, and then it didn't. Now i just tested on the nightly build and there it works again, so I don't know, if I should just wait.

**Comment by sangwoo108** [comment]
Thanks for the clarification. I couldn't find what might have caused that bug in the video while watching it repeatedly. But I'll keep track of it with a new issue.
