### ISSUE TITLE
Cancelling an unapproved transaction continues to show the pending transaction icon 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#32199]
## Description 
Cancelling an unapproved transaction continues to show the pending transaction icon 

## Steps to reproduce 

   1. Create a send transaction
   2. Close the approval screen to keep the transaction in unapproved state
   3. Go to Activity tab and click the unapproved transaction
   4. Reject the transaction
   5. Pending transaction bell icon is still shown
   6. Click the transaction bell icon, shows the rejected transaction
   7. Reject the transaction again, removes the pending transaction icon

## Actual result 

https://github.com/brave/brave-browser/assets/17010094/531eb831-e8a9-4854-8589-550b150d545d

## Expected result
Should not show pending transaction if the transaction is already rejected

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Maybe

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 13
   
## Brave version
1.57.44

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @Pavneet-Sing @simoarpe

**Comment by kjozwiak** [comment]
The above requires `1.57.53` or higher for `1.57.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.57.53 x64 build
- Verified steps from issue description
- Verified pending transaction button is dismissed when a transaction is submitted

https://github.com/brave/brave-browser/assets/17010094/39db6aab-4fb5-493c-997e-ddccccf92bb3
