### ISSUE TITLE
DApp Connection Settings Button Doesn't Close

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#32208]
## Description 

`DApp Connection Settings` button doesn't close the `Settings` popup.

## Steps to Reproduce

   1. Open the Wallet `Panel` and click on the `DApp Connection Settings` button
   2. Click on it again, it just keeps reopening the popup.

## Actual result:

https://github.com/brave/brave-browser/assets/40611140/be8383bd-7181-4107-8433-483b67ed4e9f

## Expected result:
Should just close the `Popup`

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.59.115 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | `82b05012fc6b5ab8535cf283db6856ad5eedd7eb`
OS | Windows 11 Version 22H2 (Build 22621.2283)

- Verified steps from [brave/brave-core#19656](https://github.com/brave/brave-core/pull/19656)
- Verified Dapp connection settings button closes when clicked on it again while showing the connected state

https://github.com/brave/brave-browser/assets/17010094/01060965-1699-4f39-9b1b-26cd1ecdd608

---------------------

**Verification passed on**

Brave | 1.59.115 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | `82b05012fc6b5ab8535cf283db6856ad5eedd7eb`
OS | Linux

- Verified steps from [brave/brave-core#19656](https://github.com/brave/brave-core/pull/19656)
- Verified Dapp connection settings button closes when clicked on it again while showing the connected state

https://github.com/brave/brave-browser/assets/17010094/09ff8731-3a68-466a-8eb3-06ffeab80e80

---------------------

**Verification passed on**

Brave | 1.59.115 Chromium: 118.0.5993.54 (Official Build) (arm64)
-- | --
Revision | `82b05012fc6b5ab8535cf283db6856ad5eedd7eb`
OS | macOS Version 14.0 (Build 23A344)

- Verified steps from [brave/brave-core#19656](https://github.com/brave/brave-core/pull/19656)
- Verified Dapp connection settings button closes when clicked on it again while showing the connected state

https://github.com/brave/brave-browser/assets/17010094/ac1d1950-4b62-49a3-b3ed-c2fff6964cf1
