### ISSUE TITLE
the Nightly  version cannt be opened

### ISSUE THREAD

**Issue by tim-wang-tmp** [brave/brave-browser#32212]
## Description 

The program cannot be opened

## Steps to Reproduce

   1. update to the lastest nightly version
   2. open it
   3. nothing happened

## Brave version (brave://version info)

version：1.59.9

## Version/Channel Information:

- nightly channel

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

```[tasklist]
### Tasks
```

**Comment by bsclifton** [comment]
@tim-wang-tmp do you have more information? What operating system? What architecture?
More details welcome 🙂

**Comment by bsclifton** [comment]
On Windows, there could be a hung process. A reboot would fix that - or you can check Task Manager for `brave.exe` and kill any open ones. Then you should be in good shape once you launch Brave again

**Comment by tim-wang-tmp** [comment]
> On Windows, there could be a hung process. A reboot would fix that - or you can check Task Manager for `brave.exe` and kill any open ones. Then you should be in good shape once you launch Brave again

I have already resolved this issue. First, open private mode once, and then reopen the browser, it will work fine😂
