### ISSUE TITLE
`brave://settings/autofill` panel is broken

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#32213]
## Description 

`brave://settings/autofill` panel is broken

## Steps to Reproduce

1. install `1.59.9`
2. launch Brave
3. open `brave://settings/autofill` (or any settings page)
4. open the `Console` panel of the `Developer Tools`
5. see the following exception

## Actual result:

<img width="1670" alt="Screenshot 2023-08-11 at 11 45 57 PM" src="https://github.com/brave/brave-browser/assets/387249/eaa273f0-400e-41d7-b687-db78163df95a">

```
Uncaught (in promise) Error: Assertion failed: Pref is missing: brave.brave_vpn.wireguard_enabled
    at assert (shared.rollup.js:27:55)
    at SettingsBraveVpnPageElement.getPref (shared.rollup.js:639:205)
    at SettingsBraveVpnPageElement.getCurrentPrefValue (settings.js:3561:997)
    at SettingsBraveVpnPageElement.ready (settings.js:3561:622)
    at SettingsBraveVpnPageElement._enableProperties (polymer_bundled.min.js:1:17854)
    at i.__enableOrFlushClients (polymer_bundled.min.js:1:35951)
    at i._readyClients (polymer_bundled.min.js:1:35994)
    at i._readyClients (polymer_bundled.min.js:1:49626)
    at i._flushClients (polymer_bundled.min.js:1:35725)
    at i._propertiesChanged (polymer_bundled.min.js:1:36475)
```

## Expected result:

Opens `brave://settings/autofill`

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.59.9 Chromium: 116.0.5845.82 (Official Build) nightly (x86_64)
-- | --
Revision | d3618c5c042f6d4a2451a054183b75901ba653cf
OS | macOS Version 14.0 (Build 23A5312d)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

/cc @bsclifton @simonhong @spylogsster @rebron @brave/qa-team

**Comment by bsclifton** [comment]
Windows is likely fine - this should only be affecting macOS and Linux

Unintentionally caused by https://github.com/brave/brave-core/pull/19531

**Comment by stephendonner** [comment]
> Windows is likely fine - this should only be affecting macOS and Linux
> 
> Unintentionally caused by [brave/brave-core#19531](https://github.com/brave/brave-core/pull/19531)

Confirmed; fine using

```
Brave | 1.59.9 Chromium: 116.0.5845.82 (Official Build) nightly (64-bit)
-- | --
Revision | d3618c5c042f6d4a2451a054183b75901ba653cf
OS | Windows 10 Version 22H2 (Build 19045.3324)
```

![image](https://github.com/brave/brave-browser/assets/387249/a6a7880a-4165-432f-a9f3-6190b0c353c7)

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.59.16 Chromium: 116.0.5845.82 (Official Build) nightly (x86_64)
-- | --
Revision | 45c39559e59916195de203de16211915b0148f71
OS | macOS Version 11.7.9 (Build 20G1426)
```

### Followed https://github.com/brave/brave-browser/issues/32213#issue-1847806717

<img width="2032" alt="Screen Shot 2023-08-14 at 4 15 57 PM" src="https://github.com/brave/brave-browser/assets/387249/f38f2581-3112-40d9-b3c3-6c21ede154f8">

**Comment by btlechowski** [comment]
Verified PASSED

Brave | 1.59.115 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | 82b05012fc6b5ab8535cf283db6856ad5eedd7eb
OS | Linux

Verified test plan from the description

![image](https://github.com/brave/brave-browser/assets/34715963/81fb5435-93ed-4a6b-91c7-cf50c5e042c0)|![image](https://github.com/brave/brave-browser/assets/34715963/642deebd-2342-4b1e-86c3-451884f04996)
--|--
