### ISSUE TITLE
Add "search queries before churn" p3a metric

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#32210]
Add metric for the amount of queries before the user switches their default search engine away from Brave Search.

If you switched search engines this week from Brave Search to something else, how many queries did you do before switching? (via address bar only)
`Brave.Search.QueriesBeforeChurn`

0. 0
1. 1
2. 2
3. 3-5
4. 6-10
5. 11-20
6. 21-40
7. More than 40

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.60.81 Chromium: 118.0.5993.54 (Official Build) beta (64-bit)
-- | --
Revision | 1efb3f333eb41cc34af46ca31fb33c30e0afbfae
OS | Windows 10 Version 22H2 (Build 19045.3448)

```

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 [panther_beta-user 14 U1B2.230922.010 release-keys]
Brave build: 1.60.109
Chromium: 119.0.6045.59 (Official Build) (64-bit) 
Revision: fc399c7c433510eb03c2b35281bf8935804b99de
```
---------------------------

**STEPS:**
1. Clean profile > Launch Brave
2. Three-dot menu > Settings > Search engines > Confirm that `Brave` is set as SE
3. Open `brave://local-state file` > Look for metrics `Brave.Search.QueriesBeforeChurn` > Verify
4. Three-dot menu > Settings > Search engines > Change `Brave` to another SE
5. Open `brave://local-state file` > Look for metrics `Brave.Search.QueriesBeforeChurn` > Verify
6. Repeat steps 1 and 2 > Open `NTP` > Make a search query via the URL search bar
7. Change SE from `Brave` to another SE
8. Open `brave://local-state file` > Look for metrics `Brave.Search.QueriesBeforeChurn` > Verify
9. Repeat steps 6 - 8, but for multiple queries mentioned in https://github.com/brave/brave-browser/issues/32210#issue-1847470504 > Verify

**ACTUAL RESULTS:**
- Verified that the metrics `Brave.Search.QueriesBeforeChurn` is NOT shown in the local state file when no search requests were made
- Verified that the metrics `Brave.Search.QueriesBeforeChurn` is shown and the response value is `0` when no search requests were made
- Verified that the metrics `Brave.Search.QueriesBeforeChurn` is shown and the response value is `1` when only `1` search request was made
- Verified that the metrics `Brave.Search.QueriesBeforeChurn` is shown and the response value is `2` when a `2` search request was made

---------------------------

|No search requests|0|1|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/01570c25-bbcd-4473-a846-af8c82e2900b) | ![2](https://github.com/brave/brave-browser/assets/128532965/bb62584a-755d-4d44-bd56-da88d26873e1) | ![3](https://github.com/brave/brave-browser/assets/128532965/2cdbb752-acad-488c-a90d-9fc35413b22f) |
|2|3-5|6-10|
| ![1](https://github.com/brave/brave-browser/assets/128532965/eec141ee-55ac-404b-9560-39ebf475d5be) | ![2](https://github.com/brave/brave-browser/assets/128532965/15b3b606-0a1f-428e-996d-506083f552f1) | ![3](https://github.com/brave/brave-browser/assets/128532965/8274ca65-28cf-4da7-8b8e-c9e7d15a355b) |
|11-20|21-40|More than 40|
| ![1](https://github.com/brave/brave-browser/assets/128532965/ccb7dd98-d971-41a9-b680-81c41953b66b) | ![2](https://github.com/brave/brave-browser/assets/128532965/31be25d5-ad3d-4ba2-8e95-b362e10e73a7) | ![3](https://github.com/brave/brave-browser/assets/128532965/193a4bf7-dca3-494d-b9ff-56a6b047ff51) |
