### ISSUE TITLE
Web Store text regressed to Brave web store

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#3222]
## Description 

Web Store text regressed to Brave web store

## Steps to Reproduce

   1. Install 0.59.31 build
   2. Open brave://extensions, shows message `Find extensions and themes in the Web Store`
   3. Upgrade to `0.59.32`
   4. Open brave://extensions, shows message `Find extensions and themes in the Brave Web Store`

## Actual result:

Web Store text regressed to Brave web store

## Expected result:
Should have generic Web Store 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.59.32 Chromium: 72.0.3626.81 (Official Build) (64-bit)
-- | --
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes on both dev/Beta
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

#2983 
@kjozwiak confirmed the following 

• on macOS, checked `0.61.4 Chromium: 72.0.3626.81` --> Find extensions and themes in the Web Store
• on Win 10, checked `0.59.35 Chromium: 72.0.3626.81` --> Find extensions and themes in the Web Store
• on Win macOS, checked `0.59.35 Chromium: 72.0.3626.81` --> Find extensions and themes in the Web Store

**Comment by rebron** [comment]
@srirambv I'm not seeing this on Linux Mint 0.59.35 Chromium: 72.0.3626.81 or macOS 0.59.35 Chromium: 72.0.3626.81

I still see "Web Store".

**Comment by kjozwiak** [comment]
@rebron I checked on `Min 19.1 x64` on both a VM and a psychical laptop and got the following results both times:

<img width="1267" alt="screen shot 2019-02-05 at 5 33 42 pm" src="https://user-images.githubusercontent.com/2602313/52308830-5e7d7d80-296c-11e9-9a9c-17ea0738c151.png">

Used the following build:

Brave | 0.59.35 Chromium: 72.0.3626.81 (Official Build) (64-bit)
-- | --
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS | Linux

**Comment by rebron** [comment]
cc: @mkarolin can you check, this looks like Linux only.

**Comment by srirambv** [comment]
Still reproducible on Beta `0.61.47`

**Comment by mkarolin** [comment]
Just tried:
1. Built `0.61.47` on Linux (Mint 19): cannot repro.
2. Installed `0.61.43` on Linux (Mint 19) via `apt install`: cannot repro.

Not sure what's different about @srirambv's environment.

**Comment by kjozwiak** [comment]
@mkarolin I managed to reproduce it on the following platforms/machines:

* ` Mint 19.1 x64 VM` (fully updated) - **Reproduced**
* `Mint 19.1 x64` (physical machine that's fully updated) - **Reproduced**
* `Ubuntu 18.04.2 LTS VM` (fully updated) -  **Reproduced**

Example of the issue occurring:

<img width="1461" alt="screen shot 2019-03-06 at 6 40 05 pm" src="https://user-images.githubusercontent.com/2602313/53921945-76feb780-4040-11e9-84e7-0da660b65581.png">

<img width="1183" alt="screen shot 2019-03-06 at 7 22 08 pm" src="https://user-images.githubusercontent.com/2602313/53923154-2e95c880-4045-11e9-9476-ca373ddbfd1d.png">

@mkarolin we've had similar issues with https://github.com/brave/brave-browser/issues/2481 and https://github.com/brave/brave-browser/issues/2446 in terms of not being able to reproduce it on all Linux machines. @NejcZdovc couldn't see it on his VM's either but we were. Same version of the OS as well. Eventually it stopped being a problem.

Is there any other information that we can provide you with to narrow this down?

**Comment by mkarolin** [comment]
@kjozwiak, how are you installing on Mint? I want to make sure I am trying with the same installer.

**Comment by kjozwiak** [comment]
Downloaded https://github.com/brave/brave-browser/releases/download/untagged-f443043f888f18aa62a5/brave-browser-beta_0.61.47_amd64.deb and basically did the following:

*`sudo dpkg -i Download/brave-browser-beta_0.61.47_amd64.deb`
* once installed, launch via terminal using `brave-browser-beta`

Also tried launching via the shortcut and got the same results:

<img width="397" alt="screen shot 2019-03-06 at 7 51 49 pm" src="https://user-images.githubusercontent.com/2602313/53924236-538c3a80-4049-11e9-95c1-69ee6ee54404.png">

**Comment by mkarolin** [comment]
@kjozwiak tried with that installer and still no luck reproducing on my Mint. 
Are you testing with an existing or a fresh profile?

**Comment by kjozwiak** [comment]
It's always a new profile on the VM. I have a VM snapshot that's basically a clean installation which I always restore and install via the `deb` file.

Is there any dependencies that Brave might need? Maybe that's the issue? But I think the `deb` file would warn you if you were missing dependencies before installing?

**Comment by Sophist-UK** [comment]
Not seeing this on Windows v. 0.60.48

**Comment by kjozwiak** [comment]
> Not seeing this on Windows v. 0.60.48

Awesome, appreciate the double check 👍This seems to be only happening on Linux but not everyone is seeing it. This was originally fixed under https://github.com/brave/brave-browser/issues/2983 but seemed to regress on Linux.

**Comment by kjozwiak** [comment]
Quick update, still seeing this on `Ubuntu 18.04.2 LTS x64 VM`. Used the following build:

Brave | 0.63.45 Chromium: 74.0.3729.75 (Official Build) beta (64-bit)
--- | ---
Revision | fdb7915642fef8cf997beac2554709d148e3c187-refs/branch-heads/3729@{#754}
OS | Linux

Example:

<img width="1152" alt="Screen Shot 2019-04-18 at 2 00 35 AM" src="https://user-images.githubusercontent.com/2602313/56339859-e8707080-617d-11e9-8cae-ddf981f9f684.png">

**Comment by srirambv** [comment]
This still happens on the release build for me.

**Comment by bsclifton** [comment]
LGTM on 1.24.x on Ubuntu 20 🎉 
![image](https://user-images.githubusercontent.com/4733304/113943121-dd71d900-97b6-11eb-89be-8d8f392b5f34.png)

![image](https://user-images.githubusercontent.com/4733304/113943133-e2cf2380-97b6-11eb-8f94-fa67183acf94.png)
