### ISSUE TITLE
Walmart.com redirects to account sign-in screen

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#32229]
## Description 
Visiting https://www.walmart.com/ loads - but then quickly redirects to a login screen.

On other browsers, this doesn't happen

## Steps to Reproduce

   1. Load https://www.walmart.com/ in Brave
   2. Wait a moment

## Actual result:
![image](https://github.com/brave/brave-browser/assets/4733304/820681b5-8c7b-4060-8cfa-080703b208ac)

## Expected result:
You should be able to browse the site without logging in

## Reproduces how often: 
100%

Reported on Linux and Mac; happens on Windows and Android also.

**Comment by bsclifton** [comment]
Reported via community here:
https://community.brave.com/t/walmart-com-redirects-to-account-sign-in-screen-brave-linux-and-mac-not-ff-or-safari/500040

@ryanbr has already been investigating

**Comment by ryanbr** [comment]
Has been resolved, walmart removed offending code.
