### ISSUE TITLE
Fix toolbar and title not being displayed.

### ISSUE THREAD

**Issue by simoarpe** [brave/brave-browser#32222]
![Screenshot from 2023-08-14 12-09-32](https://github.com/brave/brave-browser/assets/3308503/2cb8c869-8b57-46ab-aa3a-e2876a2323bc)

## Description

Add a centered title to the toolbar.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.59.100 x64 beta build
- Verified steps from [brave/brave-core#19666](https://github.com/brave/brave-core/pull/19666)
- Verified `Wallet` header is shown when wallet is opened

Oppo Reno 5  (Android 13) | Lenovo Tab (Android 12)
-- | --
<img width=300 src=https://github.com/brave/brave-browser/assets/17010094/1ccff946-cfae-4c85-816b-41fc926d02b2> | <img width=400 src=https://github.com/brave/brave-browser/assets/17010094/c4a1c01a-5635-4f49-8a38-cd641c8cbd03>
