### ISSUE TITLE
Update Stripe text description

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#32226]
## Description 

Stripe would like their text and logos updated on Brave Wallet..

logo: ([Link logo (favicon Teal)](https://brandfolder.com/s/spbh4mt4mb6sszjkx5bt8))
name: Link by Stripe
description: Instantly buy crypto with credit card, debit card, or bank account at crypto.link.com
button: Buy with Link

Their brand guidelines are attached
[[Public] Onramp brand guidelines.pdf](https://github.com/brave/brave-browser/files/12362374/Public.Onramp.brand.guidelines.pdf)

There is also a slack with stripe, if you need to be added. (convo from slack channel https://stripe.slack.com/archives/C0525LVHJ65/p1692114249199379?thread_ts=1691186913.138699&cid=C0525LVHJ65)
## Steps to Reproduce

   1. go to brave wallet
   2. go to buys and pick an asset and an amount
   3. see list of third parties and text associated

## Actual result:

Screens that need updatingt
<img width="878" alt="Screenshot 2023-08-14 at 17 03 25" src="https://github.com/brave/brave-browser/assets/12224304/c331c927-7c56-41e0-8034-3fdf58861f7d">
<img width="390" alt="Screenshot 2023-08-14 at 17 03 51" src="https://github.com/brave/brave-browser/assets/12224304/22cfcc0a-864f-4d3d-8dd4-c0f3b2893fc5">

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.58.113` or higher for `1.58.x` verification 👍

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.58.109 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Linux

- Verified steps from [brave/brave-core#19866](https://github.com/brave/brave-core/pull/19866)
- Verified Stripe Onramp description and image is updated
![LInux](https://github.com/brave/brave-browser/assets/17010094/16c50ea1-b422-4a73-8d30-13f82608e22c)

---------------------

**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build)) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#19866](https://github.com/brave/brave-core/pull/19866)
- Verified Stripe Onramp description and image is updated
![brave_na3WS2fVHK](https://github.com/brave/brave-browser/assets/17010094/05c11571-458b-438f-b26d-161dd37912b8)

---------------------

**Verification passed on**

Brave | 1.57.27 Chromium: 115.0.5790.114 (Official Build) beta (arm64)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | macOS Version 13.4.1 (c) (Build 22F770820d)

- Verified steps from [brave/brave-core#19866](https://github.com/brave/brave-core/pull/19866)
- Verified Stripe Onramp description and image is updated
![image](https://github.com/brave/brave-browser/assets/17010094/fd04c504-6d0b-4019-8ec0-11d0de024275)
