### ISSUE TITLE
Unable to Edit an Account Name in Wallet Panel

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#32238]
## Description 

You are currently unable to `Edit` an `Account Name` in the Wallet `Panel`

## Steps to Reproduce

   1. Enable `Wallet Panel V2`
   2. Open the `Panel` and go to the `Accounts` tab
   3. Select an `Account` and try to `Edit` the name
   4. It does not update

## Actual result:

https://github.com/brave/brave-browser/assets/40611140/5ce7f892-687e-426c-84e5-4451da4e807b

## Expected result:
You should be able to `Edit` an `Account Name` in the Wallet `Panel`

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.59.112 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | `967f25f295938c64c24e2e6a1790470668757655`
OS | Windows 11 Version 22H2 (Build 22621.2283)

- Verified steps from [brave/brave-core#19676](https://github.com/brave/brave-core/pull/19676)
- Verified editing account name via panel works as expected

https://github.com/brave/brave-browser/assets/17010094/2d2e6d98-9e75-49ad-9400-02536360900d

---------------------

**Verification passed on**

Brave | 1.59.112 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | `967f25f295938c64c24e2e6a1790470668757655`
OS | Linux

- Verified steps from [brave/brave-core#19676](https://github.com/brave/brave-core/pull/19676)
- Verified editing account name via panel works as expected

https://github.com/brave/brave-browser/assets/17010094/255836cb-7ddc-4494-b138-37bcee6622d3

---------------------

**Verification passed on**

Brave | 1.59.112 Chromium: 118.0.5993.54 (Official Build) (arm64)
-- | --
Revision | `967f25f295938c64c24e2e6a1790470668757655`
OS | macOS Version 14.0 (Build 23A344)

- Verified steps from [brave/brave-core#19676](https://github.com/brave/brave-core/pull/19676)
- Verified editing account name via panel works as expected

https://github.com/brave/brave-browser/assets/17010094/2518fc55-83f5-4c7b-a3ed-c9f7d6951974
