### ISSUE TITLE
add GPC opt out

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#32231]
add a setting to brave://flags/ to disable the GPC signal

once this is done, we should mention how to opt out of GPC in  https://support.brave.com/hc/en-us/articles/360017989132-How-do-I-change-my-Privacy-Settings-.

**Comment by kjozwiak** [comment]
The above requires `1.58.128` or higher for `1.58.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.58.128 Chromium: 117.0.5938.88 (Official Build) (64-bit)
-- | --
Revision | 171b8e11a776dc3f1472bc4f593caf36463b40c7
OS | Windows 10 Version 22H2 (Build 19045.3448)
```
Using the STR/Cases outlined via https://github.com/brave/brave-core/pull/19953#issue-1874563357, went through the following:

* installed `1.58.128 Chromium: 117.0.5938.88`
* ensured that `brave://flags#brave-global-privacy-control-enabled` was `enabled` by default
* disabled `brave://flags#brave-global-privacy-control-enabled` and restarted the browser
* loaded https://global-privacy-control.glitch.me/ and ensured the following:
  * ` Server-side detection` section displays `Header not present`
  * `Client-side detection` section displays `navigator.globalPrivacyControl: false`

**`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|-----------------
![image](https://github.com/brave/brave-browser/assets/38657976/c643bc84-94f8-47e5-9a61-6cefff8fd78a) | ![image](https://github.com/brave/brave-browser/assets/38657976/2ae02dc3-2d27-42fd-9b9a-afa9364e02bd) | ![image](https://github.com/brave/brave-browser/assets/38657976/204bbd35-cb0b-48ab-8864-145f2c28f66f) | ![image](https://github.com/brave/brave-browser/assets/38657976/e982bca5-e790-44ca-ad95-653184d5fce4)

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.58.128 Chromium: 117.0.5938.88 (Official Build) (x86_64)
-- | --
Revision | 171b8e11a776dc3f1472bc4f593caf36463b40c7
OS | macOS Version 13.5.2 (Build 22G91)
```

**Comment by btlechowski** [comment]
Verified PASSED

Brave | 1.58.128 Chromium: 117.0.5938.88 (Official Build) (64-bit)
-- | --
Revision | 171b8e11a776dc3f1472bc4f593caf36463b40c7
OS | Linux


Verified test plan from https://github.com/brave/brave-core/pull/19953#issuecomment-1718761016

<details>

`brave://flags#brave-global-privacy-control-enabled` was enabled by default


![image](https://github.com/brave/brave-browser/assets/34715963/94b93bf0-ba14-4ee6-b45a-b27b7d377536)

disabled `brave://flags#brave-global-privacy-control-enabled`
![image](https://github.com/brave/brave-browser/assets/34715963/c6fb6944-027f-432e-b913-fbf4b6304cf3)

loaded https://global-privacy-control.glitch.me/ and ensured the following:
- Server-side detection section displays Header not present
- Client-side detection section displays navigator.globalPrivacyControl: false

![image](https://github.com/brave/brave-browser/assets/34715963/ec30fb64-94e0-4b1d-8c85-ccffd1024afb)


</details>

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 14` using the following build(s):

```
Brave | 1.58.129 Chromium: 117.0.5938.88 (Official Build) (64-bit)
--- | ---
Revision | 0ab74dc5473bd9dcd0a85653872988a5655aff6b
OS | Android 14; Build/UPB5.230623.009; 34; REL
```

Using STR/Cases from https://github.com/brave/brave-core/pull/19953#issuecomment-1718761016:

* installed `1.58.129 Chromium: 117.0.5938.88 `
* ensured that `brave://flags#brave-global-privacy-control-enabled` was `enabled` by default
* disabled `brave://flags#brave-global-privacy-control-enabled` and restarted the browser
* loaded https://global-privacy-control.glitch.me/ and ensured the following:
  * ` Server-side detection` section displays `Header not present`
  * `Client-side detection` section displays `navigator.globalPrivacyControl: false`

**`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|-----------------
![Screenshot_20230920-161817](https://github.com/brave/brave-browser/assets/2602313/f1ae0f1a-d458-4612-aa29-d4e3e27a13be) | ![Screenshot_20230920-161832](https://github.com/brave/brave-browser/assets/2602313/d45f8d8d-9383-4a99-b2d6-8321585d36e8) | ![Screenshot_20230920-161939](https://github.com/brave/brave-browser/assets/2602313/a7d2e533-bab5-4e7a-8978-95cc3854a6f6) | ![Screenshot_20230920-161949](https://github.com/brave/brave-browser/assets/2602313/b12af507-06ba-4edc-ba62-c7a716f34490)
