### ISSUE TITLE
Add support for swaps on Base

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#32235]
0x recently added support for Base.

### Test plan

Add Base as a custom network. Head over to "Swap" tab, and you should be able to select Base and generate swap quotes.

**Comment by kjozwiak** [comment]
The above requires `1.57.52` or higher for `1.57.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.57.52 Chromium: 116.0.5845.96 (Official Build) (64-bit)
-- | --
Revision | 1f876d1266f048189d3cc887cfa5208508ac8194
OS | Linux

- Verified steps from issue description
- Verified Base added as a a network shows up under Swaps
- Verified able to select Base as Swap network and able to generate swap quotes for tokens

https://github.com/brave/brave-browser/assets/17010094/c9a05ca7-ab46-41c6-b663-1a6951fb4fab
