### ISSUE TITLE
Unable to Remove an Account in Wallet Panel

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#32250]
## Description 

You are currently unable to `Remove` an `Account` in the Wallet `Panel`

## Steps to Reproduce

   1. Enable `Wallet Panel V2`
   2. Open the `Panel` and go to the `Accounts` tab
   3. Select an `Account` and try to `Remove` it
   4. It doesn't get `Removed`

## Actual result:

https://github.com/brave/brave-browser/assets/40611140/2218e97b-c466-4cd8-aa74-469e4de4cbc3

## Expected result:
You should be able to `Remove` an `Account` in the Wallet `Panel`

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.59.115 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | `82b05012fc6b5ab8535cf283db6856ad5eedd7eb`
OS | Windows 11 Version 22H2 (Build 22621.2283)

- Verified steps from [brave/brave-core#19684](https://github.com/brave/brave-core/pull/19684)
- Verified able to remove account from panel

https://github.com/brave/brave-browser/assets/17010094/bd353bf8-64dc-4736-aa1f-5a019f4fd8d0

---------------------

**Verification passed on**

Brave | 1.59.115 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | `82b05012fc6b5ab8535cf283db6856ad5eedd7eb`
OS | Linux

- Verified steps from [brave/brave-core#19684](https://github.com/brave/brave-core/pull/19684)
- Verified able to remove account from panel

https://github.com/brave/brave-browser/assets/17010094/533a18f4-50e4-411f-8b49-ef2cf1ccc19b

---------------------

**Verification passed on**

Brave | 1.59.115 Chromium: 118.0.5993.54 (Official Build) (arm64)
-- | --
Revision | `82b05012fc6b5ab8535cf283db6856ad5eedd7eb`
OS | macOS Version 14.0 (Build 23A344)

- Verified steps from [brave/brave-core#19684](https://github.com/brave/brave-core/pull/19684)
- Verified able to remove account from panel

https://github.com/brave/brave-browser/assets/17010094/e6100577-f4ea-4492-9c4c-11ba67cbff86
