### ISSUE TITLE
Update l10n for the macOS 10.15 announcement.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#32259]
Follow up to https://github.com/brave/brave-browser/issues/32129
Update localization for the infobar that macOS 10.15 being the minimum required version for Chromium 117.

**Comment by kjozwiak** [comment]
The above requires `1.57.50` or higher for `1.57.x` verification 👍

**Comment by LaurenWags** [comment]
Verification on macOS 10.13.x (High Sierra) in progress with

```
Brave	1.57.52 Chromium: 116.0.5845.96 (Official Build) (x86_64) 
Revision	1f876d1266f048189d3cc887cfa5208508ac8194
OS	macOS Version 10.13.6 (Build 17G66)
```
