### ISSUE TITLE
Allow/Block in permission dialog doesn't work sometimes

### ISSUE THREAD

**Issue by goodov** [brave/brave-browser#32258]
Allow/Block button is ignored when a permission lifetime was changed less than 500ms ago before pressing the button.

https://github.com/brave/brave-browser/assets/5928869/34bbef4b-5422-406e-afc9-7e3601bcb436

**Comment by goodov** [comment]
Test case:
1. Open https://permission.site
2. Click Location
3. Open lifetime combobox, select any value
4. Click Allow or Block quickly (less than 0.5s should pass between lifetime selection and a button click).
5. Expect permission bubble has closed

**Comment by kjozwiak** [comment]
The above requires `1.57.50` or higher for `1.57.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using 
```
Brave | 1.57.52 Chromium: 116.0.5845.96 (Official Build) (64-bit)
-- | --
Revision | 1f876d1266f048189d3cc887cfa5208508ac8194
OS | Windows 11 Version 22H2 (Build 22621.2134)
```
