### ISSUE TITLE
YOUTUBE VIDEO PLAYER getting BLOCKED says to DISABLE ad blocking

### ISSUE THREAD

**Issue by ParkerStones** [brave/brave-browser#32255]
Using Youtube on Brave with SHIELDS and U-Block Origin says to remove ad blocker or else it will not play the Video...........
But BRAVE was advertising that they will support ad-blocking irrespective of how GOOGLE would be eating their own SHIT......

Will this problem be addressed or this is just the beginning of the **END OF AD-BLOCKING ERA**

![Screenshot from 2023-08-15 12-35-53](https://github.com/brave/brave-browser/assets/38376474/a692d2bb-4ac2-48d9-a738-a550953c0ab6)

**Comment by bsclifton** [comment]
@ParkerStones do you have more information? You're on Windows - what version of Brave? What region are you in?

**Comment by ryanbr** [comment]
I noticed the amount of extenstions installed, any youtube extension will also trigger it. Does it work in private window mode?

**Comment by ParkerStones** [comment]
> @ParkerStones do you have more information? You're on Windows - what version of Brave? What region are you in?

Using **Brave 1.57.47** on **Ubuntu Linux** _22.04 from India (Asia)_

**Comment by ParkerStones** [comment]
> I noticed the amount of extenstions installed, any youtube extension will also trigger it. Does it work in private window mode?

Yeah.....can't be certain of this thing but i was using "enhancer for youtube" extension with block ad option enabled which might have triggered this issue as now i have disabled the option and ad-blocking is back on track !!......but it also might be GOOGLE allowed their aggressive video blocking campaign for just 24-Hours and now the storm has passed !!!!!!!

**Comment by ryanbr** [comment]
https://github.com/uBlockOrigin/uAssets/commit/a136b4d48c7a57c30f1c961f733465380f8ecfa2 rolled out a few hours ago,  ensure Brave Ad Block Updater - Version: 1.0.537 or better in brave://components/

Also not using any YT extensions would help

**Comment by ParkerStones** [comment]
> [uBlockOrigin/uAssets@a136b4d](https://github.com/uBlockOrigin/uAssets/commit/a136b4d48c7a57c30f1c961f733465380f8ecfa2) rolled out a few hours ago, ensure Brave Ad Block Updater - Version: 1.0.537 or better in brave://components/
> 
> Also not using any YT extensions would help

Okay Sir.........no more video blocking today and now after much evaluation i can safely assume and say that it was not a GOOGLE SIDE Rampant Behaviour against _Ublock Origin or Shields_ but something that was triggered by **"ENHANCER FOR YOUTUBE"** extention Block Ad option, enabled in the background (disabled-now)...........so thanks for your valuable time u invested in  addressing my issue,wish you a goof day/night ahead SIR !!....

**Comment by bsclifton** [comment]
Thanks @ParkerStones for helping diagnose! 😍
