### ISSUE TITLE
[Performance optimization] Avoid view pager instance recreation when state changes and improve layouts.

### ISSUE THREAD

**Issue by simoarpe** [brave/brave-browser#32256]
## Description

Current implementation recreates view pager each time the onboarding fragments are shown, draining device memory and offering a slow experience with a black screen lasting ~2 seconds when the initial onboarding fragment is skipped.

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.59.93 x64 beta build
- Verified steps from [brave/brave-core#19734](https://github.com/brave/brave-core/pull/19734)
- Verified skipping backup wallet on portfolio/account tabs doesn't slow down the apps performance
- Verified no performance degradation when navigating between screens

https://github.com/brave/brave-browser/assets/17010094/701387b5-0db2-42ec-812e-3f00f365f506
