### ISSUE TITLE
Sync: do not left zombie devices after chain delete

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#3225]
## Description 

When there are two devices in chain and the second device leaves the chain, the first get notified it is the only in chain and does reset without sending DELETE record. Then if connect to that chain later with saved code words or QR, zombie device can be seen.

## Steps to Reproduce

   1. Create sync chain brave-core device1
   2. Connect to sync chain brave-core device2
   3. Create bookmark on device1 and ensure it is synced to device2
   4. On device1 press `View sync code` -> `View QR code`, do the screenshot of QR code
   5. On device2 press `Leave Sync Chain`
   6. Wait until both devices will get sync turned off
   7. With the Android device connect to existing sync chain with QR at pt 4

## Actual result:

  You will see two devices in chain: android device and zombie.

## Expected result:
  You should see only android device.

## Reproduces how often: 

Easily

## Brave version (brave://version info)

0.61.6 

Brave | 0.61.6 Chromium: 72.0.3626.81 (Official Build) dev(64-bit)
-- | --
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
yes, both releases and beta

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.61.38 Chromium: 73.0.3683.39 (Official Build) beta (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

Used test plan from https://github.com/brave/brave-core/pull/1560.
