### ISSUE TITLE
Do not show bullet point #2 in custodian selection modal when country is India

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#32251]
## Description

For now, remove the second bullet point about being able to top up while Rewards country is India.

![image](https://github.com/brave/brave-browser/assets/11497541/80628f18-4e78-4c63-93c4-171eb97a74fc)

**Comment by kjozwiak** [comment]
The above requires `1.58.99` or higher for `1.58.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verificatio **PASSED** on

```
Brave | 1.58.100 Chromium: 116.0.5845.114 (Official Build) beta (64-bit)
-- | --
Revision | a8c0058265009a1858c4502b9ba413671fbb61e1
OS | Windows 10 Version 22H2 (Build 19045.3324)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/19693 and ensured that the bullet point `Top up your account with BAT you purchased` is removed when joining Rewards from India
![image](https://github.com/brave/brave-browser/assets/38657976/f366fcf6-259e-49ff-b0aa-7ce95164fc22)

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Samsung Galaxy version 12` running `Bravemonoarm54.apk_1.58.110`

- Verified the test plan from https://github.com/brave/brave-core/pull/19693 and ensured that the bullet point Top up your account with BAT you purchased is removed when joining Rewards from India

![image](https://github.com/brave/brave-browser/assets/38657976/e015fd67-acc6-44ec-914e-162afd124bfb)
