### ISSUE TITLE
Open Guest Profile keyboard shortcut disappeared in 1.57.47

### ISSUE THREAD

**Issue by valynor** [brave/brave-browser#32268]
1.57.47 Chromium: 116.0.5845.96 (Official Build) (arm64) on macOS 13.5

Prior to this version you could assign a keyboard shortcut to "open guest window" in settings - which I did. 
This shortcut is no longer functional in 1.57.47 and you can not set a new one for "open guest profile" (as it is now called) anymore - it is missing from brave://settings/system/shortcuts

Please fix, I've been actually using this shortcut a lot.

**Comment by rebron** [comment]
cc: @fallaciousreasoning

**Comment by fallaciousreasoning** [comment]
Thanks for bringing this up @valynor! I've got a PR for fixing this, so hopefully we'll get it out soon :smile:

**Comment by fallaciousreasoning** [comment]
@valynor this should be fixed in Nightly over the next day or two, and I'm going to try and get it uplifted to 1.58 & 1.57 :smile:

**Comment by kjozwiak** [comment]
The above requires `1.57.52` or higher for `1.57.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.57.52 Chromium: 116.0.5845.96 (Official Build) (64-bit)
-- | --
Revision | 1f876d1266f048189d3cc887cfa5208508ac8194
OS | Windows 11 Version 22H2 (Build 22621.2134)
```

Reproduced the issue in 1.57.49 Chromium: 116.0.5845.96. `Open Guest profile` shortcut option is not shown

<img width="640" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/48d63b35-a5ff-48b6-9793-b0627ab60ed6">


1. Install 1.57.52
2. launch Brave
3. open brave://settings/system/shortcuts in a new tab
4. search by `guest` 
5. confirmed `Open Guest profile` shortcut option is available
6. clicked `Add` 
7. pressed `Ctrl + I`
8. clicked Save
9. opened `Guest profile` via keyboard shortcut `Ctrl + I`

example | example | example | example 
----- | ----- | ---- | ----
<img width="646" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/8ffe5ed9-1211-482d-9710-6a552dc30e34">|<img width="646" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/764ad09b-4ab0-4844-a846-a5be4b1f58bc">|<img width="644" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/f799e604-91d4-4154-b2e7-cbcdf199c4d3">|<img width="947" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/1a35902d-f736-4664-a540-c27f34c89972">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.57.52 Chromium: 116.0.5845.96 (Official Build) (64-bit)
-- | --
Revision | 1f876d1266f048189d3cc887cfa5208508ac8194
OS | Linux
```

Reproduced the issue in 1.57.49 Chromium: 116.0.5845.96. `Open Guest profile` shortcut option is not shown

![Screenshot from 2023-08-22 09-50-53](https://github.com/brave/brave-browser/assets/98358127/b827d4d5-b314-4ebc-9ee2-c00d25a4a5a5)

Steps: 

1. Install 1.57.52
2. launch Brave
3. open brave://settings/system/shortcuts in a new tab
4. search by `guest` 
5. confirmed `Open Guest profile` shortcut option is available
6. clicked `Add` 
7. pressed `Ctrl + I`
8. clicked Save
9. opened `Guest profile` via keyboard shortcut `Ctrl + I`

example | example | example | example 
----- | ----- | ---- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/9b4fd981-f541-445e-830b-ed96beac72d8)|![image](https://github.com/brave/brave-browser/assets/98358127/7377152c-d356-4a57-859a-9baf0df5e498)|![image](https://github.com/brave/brave-browser/assets/98358127/3634dd8a-496a-4e34-87d0-e6db89d28638)|![image](https://github.com/brave/brave-browser/assets/98358127/cd1fcb0a-de37-4e34-a452-04e3ed9cdb09)

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.57.52 Chromium: 116.0.5845.96 (Official Build) (x86_64)
-- | --
Revision | 1f876d1266f048189d3cc887cfa5208508ac8194
OS | macOS Version 11.7.9 (Build 20G1426)
```

### Steps:
1. installed `1.57.52`
2. launched Brave
3. opened `brave://settings`
4. clicked on `System`
5. clicked on `Shortcuts`
6. typed `open guest profile`
7. clicked `Add`
8. pressed `^ Control` + `I`
9. examined the flyout application menu

### Confirmed new Guest window was opened, and the shortcut binding shows up in the app menu

example | example | example | example
---------|---------|----------|---------
<img width="1361" alt="Screenshot 2023-08-22 at 1 37 22 PM" src="https://github.com/brave/brave-browser/assets/387249/79cc3186-8f92-4c5f-823a-736ec97badf7"> | <img width="1361" alt="Screenshot 2023-08-22 at 1 37 48 PM" src="https://github.com/brave/brave-browser/assets/387249/5840b6f5-7fb5-45f8-8e5a-1f01e9943ecb"> | <img width="1361" alt="Screenshot 2023-08-22 at 1 38 06 PM" src="https://github.com/brave/brave-browser/assets/387249/24a87e6a-626e-46a7-a4c0-8d92192a25b8"> | <img width="1361" alt="Screenshot 2023-08-22 at 1 37 55 PM" src="https://github.com/brave/brave-browser/assets/387249/b7d8f98f-c778-470b-9d12-af1161cbcb3b">
