### ISSUE TITLE
Add Media Queries to the Select Token to Send Modal

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#32261]
## Description 

We need to add `Media Queries` to `Select Token to Send` modal for Wallet `Panel V2`

## Steps to Reproduce

   1. Open the Wallet `Panel` and navigate to the `Send` page
   2. Open the `Select Token to Send` modal
   3. The `modal` is being `padded`

## Actual result:

![Screenshot 68](https://github.com/brave/brave-browser/assets/40611140/49bf391c-e002-4b7e-af6a-a056c5d4f36d)

## Expected result:
The `modal` should be `Full Width` and stretch all the way to the bottom of the `panel`

![Screenshot 67](https://github.com/brave/brave-browser/assets/40611140/3604c63e-804a-4a87-bfb6-db0038bc31cc)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.59.115 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | `82b05012fc6b5ab8535cf283db6856ad5eedd7eb`
OS | Windows 11 Version 22H2 (Build 22621.2283)

- Verified steps from [brave/brave-core#19699](https://github.com/brave/brave-core/pull/19699)
- Verified Select token modal in Send screen is stretched to full panel 
![brave_FaOUdUJRj6](https://github.com/brave/brave-browser/assets/17010094/e8ce4759-b913-4510-ba1b-b6c4f1952e06)

---------------------

**Verification passed on**

Brave | 1.59.115 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | `82b05012fc6b5ab8535cf283db6856ad5eedd7eb`
OS | Linux

- Verified steps from [brave/brave-core#19699](https://github.com/brave/brave-core/pull/19699)
- Verified Select token modal in Send screen is stretched to full panel 
![Send Token](https://github.com/brave/brave-browser/assets/17010094/182b99ed-559d-4ea7-a390-64bf5f50016d)

---------------------

**Verification passed on**

Brave | 1.59.115 Chromium: 118.0.5993.54 (Official Build) (arm64)
-- | --
Revision | `82b05012fc6b5ab8535cf283db6856ad5eedd7eb`
OS | macOS Version 14.0 (Build 23A344)

- Verified steps from [brave/brave-core#19699](https://github.com/brave/brave-core/pull/19699)
- Verified Select token modal in Send screen is stretched to full panel 
![image](https://github.com/brave/brave-browser/assets/17010094/e2077c31-8dbe-4161-8a3c-ddabbebf5b1b)
