### ISSUE TITLE
Deprecate uncached token suggestion requests

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#32267]
## Description 

Utilize the API slice for handling retrieval and management of pending token addition requests

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.59.112 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | 967f25f295938c64c24e2e6a1790470668757655
OS | Windows 11 Version 22H2 (Build 22621.2283)

- Verified steps from [brave/brave-core#19704](https://github.com/brave/brave-core/pull/19704)
- Verified `Add to MetaMask` button works as expected without issues

https://github.com/brave/brave-browser/assets/17010094/8b327242-2bdf-4378-9bc7-4cfbe53324d9
