### ISSUE TITLE
Buy Screen is missing Select purchase method Button in Panel

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#32262]
## Description 

The `Buy` screen is missing the `Select purchase method` button in the Wallet `Panel`

## Steps to Reproduce

   1. Open the Wallet `Panel` and navigate to the `Buy` screen
   2. Select a `Token`
   3. The `Select purchase method` button is missing

## Actual result:

![Screenshot 69](https://github.com/brave/brave-browser/assets/40611140/35039108-9c30-4cd6-aee1-ce0f02cacfa4)

## Expected result:
The `Select purchase method` button should be visible

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Marking as `QA/No` as selecting Buy now loads the Buy screen in full view in a new tab as per https://github.com/brave/brave-browser/issues/33353
