### ISSUE TITLE
Remove threshold usage ping

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#32271]
Removing threshold usage ping, since there is no longer a use for it. 

Normal usage ping should still work as is.

**Comment by LaurenWags** [comment]
@DJAndries is usage ping the daily ping?

**Comment by DJAndries** [comment]
Hey @LaurenWags , yes the usage ping is sent daily.

All pings are sent to `laptop-updates.brave.com`. The usage ping is sent to the `/1/usage/brave-core` path and the threshold ping (which was removed in this issue) was sent to `/1/usage/brave-core-threshold`.

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.60.88 Chromium: 118.0.5993.70 (Official Build) beta (64-bit)
-- | --
Revision | ff9150ac5dd9934a7f431ddf478ad3e45ae68546
OS | Windows 10 Version 22H2 (Build 19045.3570)

```
- Verified the description from https://github.com/brave/brave-browser/issues/32271#issuecomment-1760185677
- Confirmed that the usage ping is sent to the `https://laptop-updates.brave.com/1/usage/brave-core` 
- Confirmed that usage ping `https://laptop-updates.brave.com/1/usage/brave-core-threshold` removed
![image](https://github.com/brave/brave-browser/assets/38657976/7499f38b-e478-42ac-bc6b-5496583775c1)

**Comment by hffvld** [comment]
Hi @DJAndries do you know how/where to find usage ping on Android?

**Comment by hffvld** [comment]
Verified on `Galaxy Tab S8` and `Pixel 7` using version(s):
```
Device/OS: 
- Galaxy Tab S8 [gts8wifixx-user 13 TP1A.220624.014 release-keys]
- Pixel 7 [panther_beta-user 14 U1B2.230922.010 release-keys]
Brave build: 1.59.124
Chromium: 118.0.5993.117 (Official Build) (64-bit)
Revision: 63d57e32ce0ff0a1e380461bc394351e97d1416a
```
---------------------------

**STEPS:**
1. Followed the description from https://github.com/brave/brave-browser/issues/32271#issuecomment-1760185677 to verify the fix.

**ACTUAL RESULTS:**
- Verified that the usage ping is sent to the `https://laptop-updates.brave.com/1/usage/brave-core`
- Verified that usage ping `https://laptop-updates.brave.com/1/usage/brave-core-threshold` is removed

---------------------------

|Galaxy Tab S8|Pixel 7|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/ed465edc-6f0d-4e86-9905-88a3be8f7a2c) | ![2](https://github.com/brave/brave-browser/assets/128532965/e69a970a-ab13-455c-bedd-ced9c0f5db12) |

**Comment by btlechowski** [comment]
Verified with 

Brave | 1.60.102 Chromium: 118.0.5993.96 (Official Build) beta (64-bit)
-- | --
Revision | 3598a9fc6b7752181feb25caa131bc386d6d054c
OS | Linux

- Verified the description from https://github.com/brave/brave-browser/issues/32271#issuecomment-1760185677
- Confirmed that the usage ping is sent to the `https://laptop-updates.brave.com/1/usage/brave-core` 
- Confirmed that usage ping `https://laptop-updates.brave.com/1/usage/brave-core-threshold` is removed

![image](https://github.com/brave/brave-browser/assets/34715963/1d7eab0c-386e-4440-9da9-9be7856f315b)

**Comment by LaurenWags** [comment]
Verified with

```
Brave | 1.60.110 Chromium: 119.0.6045.105 (Official Build) (x86_64)
-- | --
Revision | 0bb6e7a81aed340b5a9e8b752c1cf92768257c40
OS | macOS Version 13.6 (Build 22G120)
```

- Verified the description from https://github.com/brave/brave-browser/issues/32271#issuecomment-1760185677
- Confirmed that the usage ping is sent to `https://laptop-updates.brave.com/1/usage/brave-core` 
- Confirmed that a ping to `https://laptop-updates.brave.com/1/usage/brave-core-threshold` was not observed

<img width="2267" alt="Screenshot 2023-11-02 at 9 18 12 AM" src="https://github.com/brave/brave-browser/assets/28145373/2e041940-69a3-469b-b44e-5d672cefa34e">
