### ISSUE TITLE
Component updater should check for `Brave Ad Block Resources Library` updates more often

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#32274]
## Description 
Component updater by default checks for an update:
- Within a minute of launch
- Within 15 mins of launch
- Every 5 hours after that

That frequency can be seen here:
https://source.chromium.org/chromium/chromium/src/+/main:components/component_updater/configurator_impl.cc;l=53-81;drc=8c7b66805bf4b91c4ed772bb62fe9b0a7e2e427a

We need to check more often for the `Brave Ad Block Resources Library` component, because there could be adblock definition updates. Maybe we can check every 30 minutes or every hour. Exact frequency needs to be determined

cc: @mschfh @pes10k 

We can likely accomplish this the same way we check for sponsored image updates. Here's an example of that:
https://github.com/brave/brave-core/blob/e9f0de92096c80e74de5a7731590ec93ab08890e/components/ntp_background_images/browser/ntp_background_images_service.cc#L188-L198

**Comment by bsclifton** [comment]
tentatively assigning myself until we can find a resource to help

**Comment by bsclifton** [comment]
We'll likely want to do this for a few others (need to verify):
- Ad Block Updater
- Ad Block First Party

**Comment by kjozwiak** [comment]
The above requires `1.59.124` or higher for `1.59.x` verification 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.59.124 Chromium: 118.0.5993.117 (Official Build) (64-bit)
-- | --
Revision | 63d57e32ce0ff0a1e380461bc394351e97d1416a
OS | Windows 11 Version 22H2 (Build 22621.2428)
```

Using the STR/Cases outlined via https://github.com/brave/brave-core/pull/20557#issue-1946356819, ensured the following:

* launched `1.61.45 Chromium: 118.0.5993.96` using `brave.exe --enable-logging=stderr --variations-server-url=https://variations.bravesoftware.com/seed` and restarted the browser
* ensured that `AdBlockComponentUpdateIntervalStudy:Enabled` via `brave://version`
* ensured that `Brave Ad Block First Party Filters`, `Brave Ad Block Updater`, `Brave Ad Block Resources Library` were being updated every ~1min
   * open `brave://components` and refresh the page
   * all of the components should be appearing as `Up-to-date`
   * wait ~1min and you'll notice that `Brave Ad Block First Party Filters`, `Brave Ad Block Updater`, `Brave Ad Block Resources Library` will appear as `Status - Component already up to date`.

**`Example`** | **`Example`**
----------------|----------------
![image](https://github.com/brave/brave-browser/assets/2602313/2e85c5f6-edf4-4e22-af87-ff9343cb86a5) | ![image](https://github.com/brave/brave-browser/assets/2602313/70c5a8f9-e27d-4167-b71a-89b6bd47e427)
