### ISSUE TITLE
`add funds` link on tip banner yields no action - follow up to 2628

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#3227]
## Description 
Follow up to #2628 

Clicking on add funds link in site tipping banner doesn't do anything. It should link to brave://rewards/#add-funds as the panel does.

## Steps to Reproduce

* Clean install
* enable rewards
* Visit site and open rewards panel
* Click `Send a tip...`
* Choose tip amount
* Click `add funds` link

## Actual result:
Nothing happens
![screen shot 2019-02-05 at 1 25 30 pm](https://user-images.githubusercontent.com/28145373/52295401-bce53480-2949-11e9-963f-030ecad35eaa.png)

## Expected result:
Should link to brave://rewards/#add-funds
![screen shot 2019-02-05 at 1 27 16 pm](https://user-images.githubusercontent.com/28145373/52295444-d4242200-2949-11e9-998e-44f48743ede6.png)

## Reproduces how often: 
easy

## Brave version (brave://version info)

Brave | 0.60.19 Chromium: 72.0.3626.81 (Official Build) beta(64-bit)
-- | --
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by NejcZdovc** [comment]
link is there, but get this error in the console

![image](https://user-images.githubusercontent.com/9574457/52296160-f5066a80-297d-11e9-994f-c4e4003da17a.png)

If I have it like this:
![image](https://user-images.githubusercontent.com/9574457/52296194-0c455800-297e-11e9-90e2-619ccd24ea80.png)
then we get an error. But if I change it to 
![image](https://user-images.githubusercontent.com/9574457/52296222-1b2c0a80-297e-11e9-939e-3640b372bd6f.png)
then it works.

cc @bbondy @bridiver did we change some permissions where we only allow chrome links?

**Comment by NejcZdovc** [comment]
@LaurenWags so link is there and all code is correct. At some point we apparently changed permissions and brave links are blocked in webui

**Comment by GeetaSarvadnya** [comment]
Reproducible on windows 10 x64 - `0.60.19` -Getting console error, when click on add funds link:

![image](https://user-images.githubusercontent.com/38657976/52436858-65a6b600-2b3b-11e9-93d5-60ffe8fc3b93.png)

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.60.23 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/1580
