### ISSUE TITLE
[Android] Wrong selected country in rewards

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#32273]
## Description 
Rewards onboarding country selection should have only device region selected. 

https://github.com/brave/brave-browser/assets/5146988/f540a4c9-7ba5-40e2-b5da-e826aa7c9809

## Steps to reproduce 

   1. install fresh build
   2. click on BAT icon
   3. open country selection page

## Actual result 
It shows several countries as selected.

## Expected result
It should have only device region as selected.

## Issue reproduces how often 
Easily

## Version/Channel Information:

All
- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version? 1.59.14

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Vivo x70 Pro version 12` running `Bravemonoarm64,aapk_1.60.85`

- Confirmed OS country is selected first in the geo declaration dropdown

**OS country is `US`**

Example | Example | Example
----------|----------|----------
![Screenshot_20231012_164546](https://github.com/brave/brave-browser/assets/38657976/05fa6ec9-2452-4e6d-9614-e38cb4207132) | ![Screenshot_20231012_170624](https://github.com/brave/brave-browser/assets/38657976/3aa1a987-68eb-4c89-b803-dd32864dcee6)
