### ISSUE TITLE
Move clean url functionality to components and expose to iOS

### ISSUE THREAD

**Issue by cuba** [brave/brave-browser#32279]
## Description 

Our query filtering functionality is only available to desktop and android. It needs to be moved to components and layers have to be added for iOS to use

**Comment by cuba** [comment]
This should be assigned to me however I don't have permissions to do this

**Comment by mkarolin** [comment]
Resolved via https://github.com/brave/brave-core/pull/19633

**Comment by kylehickinson** [comment]
Code should be the same (just moved) but would be good to have QA sanity test clean copy URL on other platforms
