### ISSUE TITLE
Small update to the Cookie Notice 

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#32270]
## Description 
Update for https://github.com/brave/brave-browser/issues/31767

https://bravesoftware.slack.com/archives/C20HMJ62H/p1692129564514229?thread_ts=1687385543.249919&cid=C20HMJ62H

we need to update the image slight per the image attached
![image](https://github.com/brave/brave-browser/assets/7606853/9220b28e-cf07-4692-8ae9-1b9c3dd1d42e)

cc @pes10k

**Comment by Uni-verse** [comment]
Verified on Samsung Galaxy S21 using version(s):

```
Brave	1.59.93 Chromium: 117.0.5938.88 (Official Build) beta (64-bit) 
Revision	77474ed80832bd2c90be4ebf993b6c2a43f662b0
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

- Verified opt-out option is removed from the cookie blocking dialog
- Verified tapping on `Got it` will dismiss the cookie blocking dialog

![Screenshot 2023-09-21 at 1 43 43 PM](https://github.com/brave/brave-browser/assets/17885425/9760ffb7-abd2-4a6b-9647-9e7bc20edd2a)
