### ISSUE TITLE
Enable Wireguard vpn service by default for new users

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#32280]
Enable Wireguard vpn service by default for new users if the service was installed and registered

**Comment by spylogsster** [comment]
cc @bsclifton @rebron

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```

```

### WireGuard enabled by default
<details>

</details>

### Upgrade w/WireGuard disabled - `PENDING`
<details>

</details>

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.59.101 Chromium: 117.0.5938.92 (Official Build) beta (64-bit)
-- | --
Revision | 81840f55490b042e3c7a75e0cba633580ed5a1b6
OS | Windows 11 Version 22H2 (Build 22621.2283)
```
