### ISSUE TITLE
Line around search bar (graphical bug)

### ISSUE THREAD

**Issue by Ptaski** [brave/brave-browser#32288]
## Description 
After I updated to latest version (as of august 16), this line appeared, color red because of theme Crown. Persists after restart.
![image](https://github.com/brave/brave-browser/assets/132298731/4c5da155-4782-4f84-b42f-115f632ca85c)

## Steps to Reproduce
   1. Update to latest version (August 16th)
   2. Launch Brave
   3. The line

## Actual result:
![image](https://github.com/brave/brave-browser/assets/132298731/973ca5d3-ee94-4b59-a1a0-922ada03f417)

## Expected result:
Line shouldn't be seen.

## Reproduces how often: 
I checked other user account on my Linux desktop and there was no such issue. (Other user account has Brave installed too)

## Brave version (brave://version info)
1.57.47 Chromium: 116.0.5845.96 (Official Build) (64-bit)
180d2fdf443f9be410c38fd8c4ccfe7e99ea2b16
Linux

## Version/Channel Information:
- Can you reproduce this issue with the current release? 
- I checked other user account on my Linux desktop and there was no such issue. 
- Can you reproduce this issue with the beta channel? 
- I don't know
- Can you reproduce this issue with the nightly channel?
- I don't know

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- No
- Does the issue resolve itself when disabling Brave Rewards? 
- NO
- Is the issue reproducible on the latest version of Chrome? 
- I think no, did not test.

## Miscellaneous Information:
When attempting to upgrade my system, network was off, Nala (debian package manager) outputted bunch of error about something like "Unable to find _something_" and " Could not find upgrade file." Later I noticed network was off, so I turned it on and continued upgrading without issues. Then red line appeared.

**Comment by Anlanther** [comment]
Same on my mac with the Minimal Green theme. ([Version 1.57.47 Chromium: 116.0.5845.96 (Official Build) (arm64)](https://brave.com/latest/))
<img width="1386" alt="image" src="https://github.com/brave/brave-browser/assets/25150182/f4d903d5-8e6e-4574-84cf-97e2e86db684">

It used to only have a very thin green line at the bottom of the bar but now has a thick one above.
<img width="1224" alt="image" src="https://github.com/brave/brave-browser/assets/25150182/dc0426af-e167-4f9a-a8a1-fc1bae25ce72">

**Comment by rebron** [comment]
cc: @simonhong @fallaciousreasoning
