### ISSUE TITLE
Inconsistent URL Check Result Caused by Fragments in Playlist Page Source

### ISSUE THREAD

**Issue by thirumurugan-git** [brave/brave-browser#32295]
## Description 

The playlist feature currently treats URLs with and without fragments differently.

[Screencast from 15-08-23 06:53:49 PM IST.webm](https://github.com/brave/playlist-component/assets/67573527/a2e31603-e0b6-409c-84f5-763e67ec8543)

## Steps to Reproduce

   1. Go to youtube and play any video
   2. Add the video to the playlist.
   3. Now change the URL with fragment identifier(`#`).
   4. Now the edited URL treated as different one.

## Actual result:

URLs are treated differently depending on whether they have fragments or not.

## Expected result:
URLs should be considered the same regardless of the presence of fragments.

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by diracdeltas** [comment]
@bsclifton can this be closed by https://github.com/brave/brave-core/pull/19695 ?

**Comment by rebron** [comment]
cc: @sangwoo108 Ok to close?

**Comment by bsclifton** [comment]
Sorry for seeing this late - yup! We can close 😄👍
