### ISSUE TITLE
Sign Tor binary

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#3229]
We may be able to reduce anti-malware false-positives by specifically signing the Tor binary we distribute. Perhaps we should sign every file we install with the executable attribute.

**Comment by rebron** [comment]
cc: @mbacchi

**Comment by riastradh-brave** [comment]
Copying some tidbits from private discussion for posterity:

- This seems to be an issue only on Windows
  - (I have no idea what signing executables on Windows entails)
- Current build process for tor executable is at https://github.com/brave/tor_build_scripts
- We have an open ticket to transition this to jenkins: https://github.com/brave/devops/issues/27
- Only real criterion for tor executable build process is that pj and I be able to easily run the build scripts on Linux and macOS to build and test tor without all the CI rigmarole when updating

**Comment by kjozwiak** [comment]
Possibly another case of an anti-virus company blocking Brave downloads due to Tor. Reported from the community:

https://community.brave.com/t/dr-web-blocking-the-brave-download/45024

**Comment by diracdeltas** [comment]
@tomlowenthal mentions this is also an applicable issue on MacOS

**Comment by mbacchi** [comment]
I've created a signed Windows tor binary and @Brave-Matt is testing it. Will investigate Mac signing next.

**Comment by Brave-Matt** [comment]
@mbacchi,
I installed both Kaspersky AV on my Windows 7 and 10 machines and ran the signed binary file you provided. Installation went through without issue and I don't see anything flagged in Kaspersky. Note that this was done using Kaspersky "free" -- this is the same version I used to confirm that we were getting flagged when this issue first appeared.

Please let me know if there is any additional information or testing needed on my end.

**Comment by mbacchi** [comment]
I've signed the Mac tor binary. After a suggestion by @tomlowenthal, I ran a test with the before and after binaries. Using the unsigned tor binary, Little Snitch would show that the binary was unsigned:

![tor-3 4 9](https://user-images.githubusercontent.com/6763301/54719522-be964080-4b22-11e9-89f9-c9411d500fe5.png)

After signing it shows up as signed:

![tor-3 5 8](https://user-images.githubusercontent.com/6763301/54719573-db327880-4b22-11e9-814d-1f61083dc9df.png)

**Comment by mbacchi** [comment]
Since we've solved the problem of signing both Mac and Windows tor binaries, what's stopping us from doing the same on Linux? While Linux doesn't have the same concept of a 'signed binary' where the OS checks the signature validity(install packages are signed instead,) we could perform a `gpg2 --detach-sign` command thus creating an ASCII armored signature that can be verified by users.

@jumde would this be useful and is it possible to actually get the `.asc` signature with the tor binary when downloading the extension package?

**Comment by mbacchi** [comment]
For posterity I'll comment that it was discussed and for now we're not going to pursue signing the Linux binary.

**Comment by w0ts0n** [comment]
Hi @jumde I think we are waiting on you to give us 👍on this?

**Comment by jumde** [comment]
@w0ts0n - we are still waiting to publish the signed binaries to the crx buckets. Will close when that's complete. Should be wrapped up today. cc: @mbacchi

**Comment by mbacchi** [comment]
Packaged and released `0.3.5.7`.
