### ISSUE TITLE
Sends on BNB Chain are broken

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#32291]
| Community | https://community.brave.com/t/error-while-trying-to-send-coin-without-error-message/501581 |
-|-

**Comment by kjozwiak** [comment]
The above requires `1.57.56` or higher for `1.57.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.57.57 Chromium: 116.0.5845.163 (Official Build) (64-bit)
-- | --
Revision | d85db1f5df3b20ffecf96ab3f0dc7fca1d536955
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#19837](https://github.com/brave/brave-core/pull/19837)
- Verified Send/Approve-Swap on BSC is creating Type-0 transactions
- Verified Send/Approve-Swap on Polygon is creating Type-2 transactions

https://github.com/brave/brave-browser/assets/17010094/cbbe3c9f-14c8-4460-87b8-3b7944d1e57c
