### ISSUE TITLE
UI issues for Brave Wallet Swaps

### ISSUE THREAD

**Issue by lukaslevert** [brave/brave-browser#32292]
## Description 
Logo location on swap screen in Brave Wallet is very close to other elements (touching) and there appears to be a strange padding on the right side of the wallet screen.

<img width="392" alt="Screenshot 2023-08-16 at 11 27 09" src="https://github.com/brave/brave-browser/assets/79997955/2a183086-8277-4907-bf89-4ea26f2f3a8c">

## Steps to Reproduce
1. Open wallet on Nightly
2. Click on swap icon

## Brave version (brave://version info)
1.59.9 Chromium: 116.0.5845.82 (Official Build) nightly (arm64) 

## Version/Channel Information:
Happens only in Nightly with new swap screen in panel vs. expanded web view.

**Comment by rebron** [comment]
cc: @Douglashdaniel

**Comment by srirambv** [comment]
Marking as `QA/No` as the Swap option in panel now opens Swaps in full tab view
