### ISSUE TITLE
[Android] Rewards entering grandfathered state after upgrade instead of remaining in non-connected state

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#32300]
## Description 

When Rewards is enabled (Unverified state) and then upgrading Brave, the Rewards Panel UI looks wrong. It looks similar to what we see when `Custodian` is connected already.

## Steps to reproduce 

   1. Install older Brave build, for example, 1.53.x
   2. Enable `Rewards`, but do not connect `Custodian`
   3. Upgrade Brave to the newer build, for example, 1.57.x
   4. Open Brave Rewards panel > Observe

## Actual result 

Brave Rewards panel looks similar to what we see when `Custodian` is connected already when we're doing Brave upgrade, and BR is in an unverified state. According to @LaurenWags we introduced an updated `unverified state` for the Rewards in 1.48.x release, so this issue is in Prod for a while.

|Before upgrade|After upgrade|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/055bd1dc-43b1-4792-82f4-8b08160f9e08) | ![2](https://github.com/brave/brave-browser/assets/128532965/a5e331a6-8b8a-4769-b965-ade843cf718c) |

https://github.com/brave/brave-browser/assets/128532965/132fd9d6-51e4-4c52-99a6-15417b7a9c0d

## Expected result

Brave Rewards panel after upgrade must look the same as before the upgrade when Rewards is in `unverified state`.

## Issue reproduces how often 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): phone
   - Android version: Android 14
   
## Brave version

Brave build: 1.57.47

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc @deeppandya @Miyayes

**Comment by Miyayes** [comment]
I believe the issue is that users are entering the grandfathered state when they should just be remaining in the non-connected state.

**Comment by LaurenWags** [comment]
@Miyayes afaik the issue is only with the panel, not with brave://rewards page. @vlad-hoff video doesn't show that page unfortunately, but when I reproduced this brave://rewards page was as expected both before and after upgrade, just the panel was wrong.

**Comment by Miyayes** [comment]
@deeppandya Evaluate scope and weight.

**Comment by Miyayes** [comment]
Removing grandfathered code completely, so this will be superseded.
