### ISSUE TITLE
Update extension dialogue text so it's not as misleading

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#3231]
## Description 
When I try to add any extension to Brave from the Chrome Store, I get this message:
<img width="482" alt="screen shot 2019-02-05 at 12 11 45 pm" src="https://user-images.githubusercontent.com/2388823/52301535-77236e80-293f-11e9-9a88-5f5508e300ed.png">

We should improve the warning message so it doesn't send the wrong message to the user. 

## Steps to Reproduce
   1. Go to https://chrome.google.com/webstore/category/extensions
   2. Click on any extension
   3. Click "Add to Chrome"

## Designs
Update message to "Brave has not reviewed this extension for security and safety. Only install this extension if you trust the developer. It can:"
![extension dialogue text](https://user-images.githubusercontent.com/2388823/52301726-f618a700-293f-11e9-9dd9-dad256730257.png)

This text has been reviewed in #1408.

**Comment by tomlowenthal** [comment]
This text is security approved 👍

**Comment by rebron** [comment]
cc: @bbondy, @mkarolin can you guys take a look, will likely want to get this in as soon as we can e.g. 62.x.

**Comment by mkarolin** [comment]
@karenkliu, is it OK if "It can:" stays where it is or would you rather it moved to the title?

**Comment by mkarolin** [comment]
@karenkliu "It can:" label is tied to the permissions. If an extension doesn't ask for any permissions the label isn't shown:
![image](https://user-images.githubusercontent.com/41635752/53669569-81d2da00-3c45-11e9-884f-d673f807f917.png)
I assume we would still want the label there in such cases, just without "It can:" part?

**Comment by tomlowenthal** [comment]
I think it's better to keep the "It can:" separate.

**Comment by karenkliu** [comment]
@mkarolin @tomlowenthal Yes, correct, we keep "It can: ..." separate so that if the extension doesn't ask for any permissions, it will still say "Brave has not reviewed this extension for security and safety. Only install this extension if you trust the developer." without the "It can: ..." part.

**Comment by LaurenWags** [comment]
@karenkliu @tomlowenthal @simonhong @rebron 

A couple of questions:

1. We don't seem to show this new message for some extensions (LastPass, Honey, Grammarly, etc). Is this ok? If so, is it necessary to have a full list of extensions which would be exempt from this message for QA to check?

2. When this new message displays, we're no longer showing the extension name in the message box, is this ok?
ex. This is how the message displays for Google Translate:
https://chrome.google.com/webstore/detail/google-translate/aapbdbdomjkkjkaonfhkkikfgjllcleb
![Screen Shot 2019-08-06 at 8 29 31 AM](https://user-images.githubusercontent.com/28145373/62539940-638c8e00-b824-11e9-813d-27bd7742d0fb.png)

cc @kjozwiak

**Comment by tomlowenthal** [comment]
@LaurenWags 

1. Yes, there's a list of several extensions we've reviewed, and which shouldn't show this warning. I think @rebron owns that document.

2. No, that's a bug. The design spec up at the top shows the extension name by way of a header. That should be implemented.

**Comment by rebron** [comment]
@LaurenWags Should we keep this one closed and file a new issue for the extension name in header?
I'll get you the list of extensions where this warning isn't supposed to show up.

**Comment by LaurenWags** [comment]
@rebron yep - that's the correct process. I'll close this one again and have logged https://github.com/brave/brave-browser/issues/5575. Please take a look at the new issue - I added all the same labels as this (including priority) - which may need to be adjusted.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.68.118 Chromium: 76.0.3809.87 (Official Build) beta (64-bit)
-- | --
Revision | 111fe1e15d5ced26080a7dc239bcfe70f6c49aad-refs/branch-heads/3809@{#967}
OS | Ubuntu 18.04 LTS

Reproduced https://github.com/brave/brave-browser/issues/5575

![image](https://user-images.githubusercontent.com/34715963/62656367-4eb71400-b964-11e9-864c-ff30088f0140.png)
