### ISSUE TITLE
Forget by default not visible in Shields without flag on 1.57.47 

### ISSUE THREAD

**Issue by pjolt** [brave/brave-browser#32311]
## Description 
Updating from 1.56.x to 1.57.47 does not display "Forget me when i close this site" toggle under ```brave://settings/shields```. Needs ```brave://flags/#brave-forget-first-party-storage``` enabled for it to appear.

**Issue present on Windows and Linux**

Windows 11 Version 22H2 Build 22621.2134 - Upgraded
Fedora 38 (3 clients) - Upgraded
openSUSE TW (2 clients) - Upgraded 
All these are missing the toggle. Have to enable flag for it to appear. 

So i did a fresh install in a VM:
Windows 10 Version 22H2 Build 19045.3324
Fedora 38 

So these two are fresh install of both OS and Brave installed through brave.com
And "Forget by default" not visible under Shields here either. 

## Brave version (brave://version info)
Version 1.57.47 Chromium: 116.0.5845.96

- Can you reproduce this issue with the beta channel? 
On Beta the toggle is present under Shields w/o flags. 

## Other Additional Information:
- Also tested with a new profile on the Windows 11 install by using: 
```brave.exe --user-data-dir=C:\Users\[myuser name]\Desktop\test``` and no change 
- No other flags in use 
- Most marked **_upgraded_** are signed in to the same Brave Sync chain
- I have found [one other user](https://discuss.techlore.tech/t/brave-1-53-1-56-finally-released/4912/12?u=pjol) and they too seem to lack the toggle. 

I have no clue on how to proceed, or help isolate what is causing this. So please let me know with step by step instructions if you want more details and i´ll do my best to assist.

**Comment by pes10k** [comment]
@goodov is this a griffin issue?

**Comment by goodov** [comment]
> @goodov is this a griffin issue?

It's enabled on 10% in Release channel, so you need to be pretty lucky to get into that group currently.

https://github.com/brave/brave-variations/blob/136b440857f6a44461e91bb284a54696e848a402/seed/seed.json#L1841

**Comment by pjolt** [comment]
> It's enabled on 10% in Release channel, so you need to be pretty lucky to get into that group currently.


Thanks for the feedback!  

I think it would be good to include in future release notes when something substantial like this is on a staged rollout to reduce confusion or unneccessary reports like this being created.
