### ISSUE TITLE
Add Wallet NFT gallery P3A metrics

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#32315]
Add Wallet NFT gallery P3A metrics:

If you viewed the NFT gallery this week, how many NFTs are displayed in the gallery?
`Brave.Wallet.NFTCount`

0. 0
1. 1 - 4
2. 5 - 20
3. More than 20

Did you use the NFT gallery for the first time this week?
`Brave.Wallet.NFTNewUser`

1. Yes

As a user that has used the wallet at least once, do you have NFT discovery enabled?
`Brave.Wallet.NFTDiscoveryEnabled`

0. No
1. Yes

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave | 1.59.93 Chromium: 117.0.5938.88 (Official Build) beta (64-bit)
-- | --
Revision | 77474ed80832bd2c90be4ebf993b6c2a43f662b0
OS | Windows 10 Version 22H2 (Build 19045.3448)

```

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Vivo X70 Pro version 12`  running `Bravemonoarm64.apk_1.59.115`
