### ISSUE TITLE
Brave MacOS downloads should not use .pkg

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#32316]
Currently, downloading the MacOS build from brave.com gives a .pkg (macOS installer) binary with the refcode in the file and product name

![image](https://github.com/brave/brave-browser/assets/76526/859039b9-af1c-4584-b130-d76e572f707b)

This is bad for a bunch of reasons, inc
- the installer looks extremely fishy.  Other browsers don’t need this
- its not core, but it results in very fishy looking UI (I expect we could fix this w/in the installer approach, but its another thing to fix). See screenshot below
- I expect the installer is causing compat and other very-visible issues (https://bravesoftware.slack.com/archives/C7VLGSR55/p1691093591839749 / https://github.com/brave/brave-browser/issues/32074).  These might also be fixable w/in the installer approach, but its another footgun
- it makes the fact that we ship a referrer code very obvious to users (its in the UI and download name) when it doesn’t need to be.  - This is an optics concern, not a root-privacy one, but we should avoid unforced-optics problems where possible
it makes it more difficult for us to give advice to users on what downloads to trust, when the true brave downloads look “funny”

We should instead offer the binary as a standard .dmg, unprivileged app. We can solve the refcode problem by creating a different binary/.dmg for each refcode as needed

**Comment by rebron** [comment]
DevOps issue: https://github.com/brave/devops/issues/10373

**Comment by bsclifton** [comment]
The solution identified is that we'll have some new extended attributes on the `.app` file:
- `com.brave.refcode` has the referral code (ex: `BRV002`)
- `com.brave.privacypolicy` should be added with the value `https://brave.com/s/refcodes`

The code in `brave-core` should be adjusted to read this value (if present) and initialize the Referral Service with this value.
https://github.com/brave/brave-core/blob/db5c6571fd2c4036ed47a0a7f95b46a1a0517edb/components/brave_referrals/browser/brave_referrals_service.cc#L265-L268

Currently, the code looks for a file `promoCode` in the profile folder. We can still keep that check - but if the xattr `com.brave.refcode` is found, it should have higher precedence.

**Comment by bridiver** [comment]
similar upstream code
```
bool GetFileExtendedAttribute(const base::FilePath& path,
                              const char* name,
                              std::vector<char>* value) {
  ssize_t len = getxattr(path.value().c_str(), name, nullptr, 0);
  if (len < 0) {
    PLOG_IF(ERROR, errno != ENODATA) << "getxattr: " << path;
    return false;
  }
  value->resize(len);
  if (getxattr(path.value().c_str(), name, value->data(), len) != len) {
    PLOG(ERROR) << "getxattr: " << path;
    return false;
  }
  return true;
}
```
so looks like using #include <sys/xattr.h> is ok, but that definitely needs to run on a task runner and no UI thread

**Comment by LaurenWags** [comment]
@brave/qa-team labeling as `QA/Blocked` until we have clarification on test plan for this one. Waiting on more information regarding specific .dmg files and list of new promo codes. Also need to check backwards compatibility with .pkg files.

**Comment by kjozwiak** [comment]
## `macOS 14.0 Sonoma x64` using the `x64` dmg

Verification **PASSED** on `macOS 14.0 Sonoma x64` using the following build(s):

```
Brave | 1.59.124 Chromium: 118.0.5993.117 (Official Build) (x86_64)
--- | ---
Revision | 63d57e32ce0ff0a1e380461bc394351e97d1416a
OS | macOS Version 14.0 (Build 23A344)
```

**`Quick note:`** The above requires specific executables which can be downloaded via https://bravesoftware.slack.com/archives/C05FK45FN0M/p1697728273865229.

* downloaded `Brave-Browser-BRV001-x64.dmg` and ensured Brave installed without any issues/failures/crashes
* launched Brave and ensured there were no obvious issues (performance/crashes)
* checked `brave://local-state` and ensured that `“promo_code”: { “value”: “BRV001”};` as per the following:

```
“promo_code”: {
            “metadata”: [ “user_controlled”, “user_modifiable”, “extension_modifiable” ],
            “value”: “BRV001”
         },
```

![Screenshot 2023-11-01 at 12 13 28 AM](https://github.com/brave/brave-browser/assets/2602313/d47db4e9-b124-4b41-93a5-559a27489360)

* ensured that there was a `daily` usage ping via `laptop-updates.brave.com` that included the `BRV001` on first launch

```GET /1/usage/brave-core?platform=osx-bc&channel=release&version=1.59.124&daily=true&weekly=true&monthly=true&first=true&woi=2023-10-30&dtoi=2023-11-01&ref=BRV001&adsEnabled=false&arch=&wallet2=0 HTTP/1.1````

![Screenshot 2023-11-01 at 12 44 27 AM](https://github.com/brave/brave-browser/assets/2602313/7166076e-78ba-42f2-ba55-333baa52bd72)

* closed Brave/moved the date ahead by `1 day` and ensured that `daily=true` & `ref=BRV001`

```GET /1/usage/brave-core?platform=osx-bc&channel=release&version=1.59.124&daily=true&weekly=false&monthly=false&first=false&woi=2023-10-30&dtoi=2023-11-01&ref=BRV001&adsEnabled=false&arch=&wallet2=0 HTTP/1.1```

![Screenshot 2023-11-02 at 5 45 28 AM](https://github.com/brave/brave-browser/assets/2602313/46446235-841b-4d62-9f49-d96fb88fbbfd)

* closed Brave/moved the date ahead by `1 week` and ensured that `daily=true&weekly=true & `ref=BRV001`

```GET /1/usage/brave-core?platform=osx-bc&channel=release&version=1.59.124&daily=true&weekly=true&monthly=false&first=false&woi=2023-10-30&dtoi=2023-11-01&ref=BRV001&adsEnabled=false&arch=&wallet2=0 HTTP/1.1```

![Screenshot 2023-11-09 at 5 46 22 AM](https://github.com/brave/brave-browser/assets/2602313/c5a30051-cbf9-4af4-9fa0-56e6117367d7)

* closed Brave/moved the date ahead by `1 month` and ensured that `daily=true&weekly=true&monthly=true` & `ref=BRV001`

```GET /1/usage/brave-core?platform=osx-bc&channel=release&version=1.59.124&daily=true&weekly=true&monthly=true&first=false&woi=2023-10-30&dtoi=null&ref=BRV001&adsEnabled=false&arch=&wallet2=0 HTTP/1.1```

**Comment by LaurenWags** [comment]
## `macOS 14.0 Sonoma x64`

### `BRV001 Referral Code`

<details>
<summary>Using Brave-Browser-BRV001-arm64.dmg - InProgress</summary>

Verification **InProgress** on `macOS 14.0 Sonoma x64` using the following build(s):

```

```

**`Quick note:`** The above requires specific executables which can be downloaded via https://bravesoftware.slack.com/archives/C05FK45FN0M/p1698866128534639?thread_ts=1697728273.865229&cid=C05FK45FN0M.

* downloaded `Brave-Browser-BRV001-x64.dmg` and ensured Brave installed without any issues/failures/crashes
* launched Brave and ensured there were no obvious issues (performance/crashes)
* checked `brave://local-state` and ensured that `“promo_code”: { “value”: “BRV001”};` as per the following:

```
“promo_code”: {
            “metadata”: [ “user_controlled”, “user_modifiable”, “extension_modifiable” ],
            “value”: “BRV001”
         },
```

SS placeholder

* ensured that there was a `daily` usage ping via `laptop-updates.brave.com` that included the `BRV001` on first launch

```

```

SS placeholder

* closed Brave/moved the date ahead by `1 day` and ensured that `daily=true` & `ref=BRV001`

```

```

SS placeholder

* closed Brave/moved the date ahead by `1 week` and ensured that `daily=true&weekly=true & `ref=BRV001`

```

```

SS placeholder

* closed Brave/moved the date ahead by `1 month` and ensured that `daily=true&weekly=true&monthly=true` & `ref=BRV001`

```

```

SS placeholder

</details>

**Comment by stephendonner** [comment]
## `macOS 13.6.1 Ventura arm64`

## `BRV001 Referral Code` - `IN-PROGRESS`

## `BRV002 Referral Code` - `PENDING`

## `BRV010 Referral Code` - `PENDING`
