### ISSUE TITLE
Blank screen after upgrading to 1.57.47 on Ubuntu

### ISSUE THREAD

**Issue by jn-jairo** [brave/brave-browser#32318]
## Description 

After updating to version 1.57.47 it doesn't start, I just get a blank screen, I had to downgrade to version 1.56.20.

## Steps to Reproduce

   1. Upgrade brave-browser to version 1.57.47
   2. Run brave-browser

## Actual result:

Blank screen

![image](https://github.com/brave/brave-browser/assets/5104869/a0532dab-6940-4a11-bec2-19c94cdecd7e)

## Expected result:

Screen to select profile.

![image](https://github.com/brave/brave-browser/assets/5104869/d6f8e6d3-835e-47c0-87a3-fac9ddf94528)

## Reproduces how often: 

Intermittent issue.

## Brave version (brave://version info)

I cannot open brave://version so here is the info from the Ubuntu package.

```
Package: brave-browser
Version: 1.57.47
New: yes
State: installed
Automatically installed: no
Priority: optional
Section: web
Maintainer: Brave Software <support@brave.com>
Architecture: amd64
Uncompressed Size: 345 M
Depends: ca-certificates, fonts-liberation, libasound2 (>= 1.0.17), libatk-bridge2.0-0 (>= 2.5.3), libatk1.0-0 (>= 2.2.0), libatspi2.0-0 (>= 2.9.90), libc6 (>= 2.25), libcairo2 (>= 1.6.0), libcups2 (>= 1.6.0), libcurl3-gnutls | libcurl3-nss | libcurl4 | libcurl3,
         libdbus-1-3 (>= 1.9.14), libdrm2 (>= 2.4.75), libexpat1 (>= 2.0.1), libgbm1 (>= 17.1.0~rc2), libglib2.0-0 (>= 2.39.4), libgtk-3-0 (>= 3.9.10) | libgtk-4-1, libnspr4 (>= 2:4.9-2~), libnss3 (>= 2:3.35), libpango-1.0-0 (>= 1.14.0), libu2f-udev, libvulkan1, libx11-6
         (>= 2:1.4.99.1), libxcb1 (>= 1.9.2), libxcomposite1 (>= 1:0.4.4-1), libxdamage1 (>= 1:1.1), libxext6, libxfixes3, libxkbcommon0 (>= 0.5.0), libxrandr2, wget, xdg-utils (>= 1.0.2), brave-keyring
PreDepends: dpkg (>= 1.14.0)
Provides: www-browser
Description: The web browser from Brave
 Browse faster by blocking ads and trackers that violate your privacy and cost you time and money.
```

## Version/Channel Information:

Issue on version 1.57.47, but previous version 1.56.20 works.

## Other Additional Information:

- Is the issue reproducible on the latest version of Chrome? 
Latest version of Chrome works fine.

## Miscellaneous Information:

```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal

Kubuntu 20.04.6
KDE Plasma: 5.18.8
KDE Framework: 5.68.0
Qt: 5.12.8

Linux 5.4.0-156-generic #173-Ubuntu SMP Tue Jul 11 07:25:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

Output log when running (it is the same output of the working version):

```
[48863:48863:0816/193822.642008:ERROR:chrome_browser_cloud_management_controller.cc(163)] Cloud management controller initialization aborted as CBCM is not enabled.
[48863:48863:0816/193822.697579:ERROR:profile_attributes_storage.cc(894)] Failed to PNG encode the image.
[48863:48863:0816/193822.697607:ERROR:profile_attributes_storage.cc(894)] Failed to PNG encode the image.
```

**Comment by jn-jairo** [comment]
Bug persists with version 1.57.53

**Comment by sglkc** [comment]
I'd like to add as well, it still persists even after 1.57.57, I had to downgrade to 1.56.20 to use this.

![image](https://github.com/brave/brave-browser/assets/31957516/7029cc69-4168-4cc0-8fb7-4cd1c615843b)
![image](https://github.com/brave/brave-browser/assets/31957516/eecb9fac-caa2-4d23-9b34-240d6a7f3e38)

**Comment by sglkc** [comment]
Sorry, it's been a month and it's still not fixed. Brave told me to update my browser, logged me out from every sites, and every password are gone from my Linux' computer, and this is what I get from brave://sync-internals/

![image](https://github.com/brave/brave-browser/assets/31957516/3fc13d58-2abf-4d0c-857d-9b066f99171f)
![image](https://github.com/brave/brave-browser/assets/31957516/ebce43fe-c062-4a1c-b981-6067d15decab)

**Comment by jn-jairo** [comment]
I upgraded to kubuntu 24.04 and it works now.

**Comment by bsclifton** [comment]
Thanks for coming back to confirm, @jn-jairo! Glad you're sorted out 😄
