### ISSUE TITLE
[Debug] Check failed: !iterating_

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#3232]
## Description 
Brave debug build crashes on installing extensions.

## Steps to Reproduce

   1. Start with a clean profile
   2. Navigate to chrome webstore
   3. Install Grammarly

## Actual result:
Crash

## Expected result:
No Crash

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
0.62.0 Chromium: 72.0.3626.81 (Developer Build) (64-bit) (master)

**Comment by jonathanKingston** [comment]
I couldn't reproduce this on Linux using the latest master, has it gone @jumde?

**Comment by iefremov** [comment]
seems working
