### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by lunaflories** [brave/brave-browser#32324]
Brave Version: 1.57.47 Chromium: 116.0.5845.96
Operating System: Windows NT 10.0.22621

URL (if applicable) where crash occurred:

Can you reproduce this crash?
Yes, it crashes if I open that one specific profile that I always use.

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Opening one specific profile
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/31d80000-0e1b-930a-0000-000000000000

**Comment by rebron** [comment]
Hi @lunaflories Can you update to the latest 1.57.49 via brave://settings/help It might be what you're running into.

**Comment by lunaflories** [comment]
thank you very much @rebron the problem is solved.
