### ISSUE TITLE
https://github.com/brave/brave-browser/tree/b39e83b00897eac93edbf9ccb89debd375ea7bdb

### ISSUE THREAD

**Issue by Jailautner** [brave/brave-browser#32337]
## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
Closed. Invalid.
