### ISSUE TITLE
Improve pak file finding for Wireguard service

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#32340]
Currently it is inconvenient to debug release wireguard service due to rough pak relative paths, need to improve it to work smoothly in release and debug conditions

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave	1.59.94 Chromium: 117.0.5938.88 (Official Build) beta (64-bit) 
Revision	2dca22d0a20096c32df5af4c88700a0b31acb55c
OS	Windows 10 Version 22H2 (Build 19045.3448)
```

### Steps:
1. installed `1.59.94`
2. launched Brave
3. confirmed `Use WireGuard protocol in Brave VPN` was toggled to `On`/`Enabled`
4. purchased, configured, and connected to `Brave VPN`
5. confirmed `Brave VPN: Connected` system-tray icon
6. clicked on the above icon

### Confirmed appropriate context-menu items were present and worked

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.59.101 Chromium: 117.0.5938.92 (Official Build) beta (64-bit)
-- | --
Revision | 81840f55490b042e3c7a75e0cba633580ed5a1b6
OS | Windows 11 Version 22H2 (Build 22621.2283)
```

1. installed 1.59.101
2. launched Brave
3. confirmed `Use WireGuard protocol in Brave VPN` was toggled to On/Enabled
4. purchased, configured Brave VPN
5. connected VPN via VPN panel
6. confirmed Brave VPN: Connected system-tray icon is shown
7. selected `Manage Account` from the context menu of the system-tray 
8. confirmed `Subscription` page is shown
9. selected `About Brave VPN` option from system-tray
10. confirmed `firewall-vpn` page shown
11. selected `Disconnect` from system-tray
12. confirmed `Brave VPN` is disconnected
13. selected `Remove icon` from system-tray
14. confirmed `Brave VPN system-tray icon` is removed from the context menu


step 3 | step 4 | step 6 | step 7 | step 8| step 10 | step 14 
------ | ------ | ------ | ------ | ------ | ------ | ------
<img width="951" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/9da91747-b780-4ece-b989-537d4e0ce554">|<img width="951" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/e5b13bf6-aaba-4ac8-aa37-5846c0ea3f61">|<img width="954" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/6ef0ec04-fd6c-4acd-a66d-c37661dd0075">|<img width="957" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/fd772b63-432c-4f39-8b31-abc9dcb1793c">|<img width="951" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/3bbdc2f7-44ae-4ddf-bd76-19b86c548c7a">|<img width="957" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/9fba6a1a-d5f8-4d15-99a4-c0fbd704d10a">|<img width="951" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/5aff51c4-280e-47bb-8e25-29f5903af8d6">
