### ISSUE TITLE
APIRequestHelper is not reporting correct http status for SSE

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#32347]
Server is sending 500 but when SSE is enabled, it shows 200

**Comment by nullhook** [comment]
It seems that this issue originates from the server side itself. This occurs only when the input length is reached, and the streaming API doesn't appear to return the correct code, while the normal one-shot API returns a 500 code

> there may be some funkiness there - likely what is happening is we start the streaming response ( thus return 200 ) before we get the first token back from generate_stream

cc @evq

**Comment by petemill** [comment]
Closing as was a server issue
