### ISSUE TITLE
[Android] Redirect users to new custom filter settings

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#32350]
Since we have the new filter list settings option: https://github.com/brave/brave-browser/issues/26587
We need to redirect users to new filter list settings when they type `brave://adblock` in url bar.

**Comment by Uni-verse** [comment]
Changing to `QA/No` since this redirect has been reverted in https://github.com/brave/brave-browser/issues/33091

cc: @kjozwiak
