### ISSUE TITLE
Remove troublesome barrel files to prevent circular imports

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#32357]
## Description 

We should remove our large barrel files so that circular imports are less likely to occur

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.59.112 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | 967f25f295938c64c24e2e6a1790470668757655
OS | Windows 11 Version 22H2 (Build 22621.2283)

- Verified steps from [brave/brave-core#19758](https://github.com/brave/brave-core/pull/19758)
- Verified wallet features work as expected
