### ISSUE TITLE
Enable Panel V2 by Default

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#32352]
## Description 

We need to make the `Panel V2` feature `Enabled` by default

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.59.115 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | `82b05012fc6b5ab8535cf283db6856ad5eedd7eb`
OS | Windows 11 Version 22H2 (Build 22621.2283)

- Verified steps from [brave/brave-core#19751](https://github.com/brave/brave-core/pull/19751)
- Verified panel v2 is enabled by default

---------------------

**Verification passed on**

Brave | 1.59.115 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | `82b05012fc6b5ab8535cf283db6856ad5eedd7eb`
OS | Linux

- Verified steps from [brave/brave-core#19751](https://github.com/brave/brave-core/pull/19751)
- Verified panel v2 is enabled by default 

---------------------

**Verification passed on**

Brave | 1.59.115 Chromium: 118.0.5993.54 (Official Build) (arm64)
-- | --
Revision | `82b05012fc6b5ab8535cf283db6856ad5eedd7eb`
OS | macOS Version 14.0 (Build 23A344)

- Verified steps from [brave/brave-core#19751](https://github.com/brave/brave-core/pull/19751)
- Verified panel v2 is enabled by default
