### ISSUE TITLE
NTP always shows same background image

### ISSUE THREAD

**Issue by A-t-s-u-s-h-i** [brave/brave-browser#32359]
## Description 

https://community.brave.com/t/topic/500776

NTP shows same image no matter how many times they reload NTP.  

## Steps to Reproduce

   1. launch Brave(desktop)
   2. Show NTP
   3. Repeat reloading

## Actual result:

The same background image shows
![image](https://github.com/brave/brave-browser/assets/79502386/30cb73a0-3fae-42ca-afba-cdfc08ab9624)

## Expected result:
Shows other background images randomly

## Reproduces how often: 

Easily reproduced(only on specific devices)

## Brave version (brave://version info)

v1.57.47  
Windows10

**Comment by A-t-s-u-s-h-i** [comment]
Now same issue happens on my device. The issue happens only on a specific browser profile. NTP changes randomly on other profiles.

Brave 1.57.53
NTP Background Images - version: 1.0.11
Sponsored images enabled

https://github.com/brave/brave-browser/assets/79502386/a72c370d-477a-4b6b-88b0-1a8ed1059613

**Comment by kjozwiak** [comment]
The above requires `1.58.119` or higher for `1.58.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.58.120 Chromium: 117.0.5938.48 (Official Build) (x86_64)
-- | --
Revision | 8b2e2785c90c076fc1413acb2c003e603eac02d3
OS | macOS Version 13.5.2 (Build 22G91)
```
