### ISSUE TITLE
Resource not found when inflating HideBottomViewOnScrollBehavior class

### ISSUE THREAD

**Issue by simoarpe** [brave/brave-browser#32363]
## Description

Issue reproducible only on release builds, most likely due to some optimizations performed by Proguard.

## Steps to reproduce

   1. Open Brave Wallet

## Actual result

App crashes

## Expected result

Wallet opens without crashing

## Issue reproduces how often 

Always on release builds.

### Additional information

Slack discussion: https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1692312414275489

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.59.93 x64 Beta build
- Verified steps from [brave/brave-core#19764](https://github.com/brave/brave-core/pull/19764)
- Verified Wallet loads correctly on Beta build
- Verified no crash when navigating to wallet

Note: leaving the issue for RC build verification before adding label

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.59.111 x64 Beta build
- Verified steps from [brave/brave-core#19764](https://github.com/brave/brave-core/pull/19764)
- Verified Wallet loads correctly on the RC build
- Verified no crash when navigating to wallet
