### ISSUE TITLE
Refactor `EligibleAds/ad_predictor_weights` into seprate parameters

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#32367]
Currently `EligibleAds/ad_predictor_weights` is a string and it gives as problems because it contains `,` and `.`

Solution is to make all ad predictor weights into separate parameters

Paramters:
```
constexpr size_t kDoesMatchIntentChildSegmentsIndex = 0;
constexpr size_t kDoesMatchIntentParentSegmentsIndex = 1;
constexpr size_t kDoesMatchInterestChildSegmentsIndex = 2;
constexpr size_t kDoesMatchInterestParentSegmentsIndex = 3;
constexpr size_t kAdLastSeenHoursAgoIndex = 4;
constexpr size_t kAdvertiserLastSeenHoursAgoIndex = 5;
constexpr size_t kPriorityIndex = 6;
```

cc @iambrianfung @tmancey @aseren

**Comment by tmancey** [comment]
Closing as will be resolved by https://github.com/brave/brave-browser/issues/31736
