### ISSUE TITLE
`Upgrade connections to HTTPS` isn't working on `upgradable.arthuredelstein.net`

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#32372]
## Description 

`Upgrade connections to HTTPS` isn't working on `upgradable.arthuredelstein.net`

Found while testing https://github.com/brave/brave-browser/issues/31104

## Steps to Reproduce

1. install `1.59.26` or `1.58.92`
2. launch Brave
3. (no need for 2nd Griffin restart)
4. load `http://upgradable.arthuredelstein.net/`

## Actual result:

The user remains on `http://upgradable.arthuredelstein.net/`

<img width="1312" alt="Screen Shot 2023-08-18 at 11 41 29 AM" src="https://github.com/brave/brave-browser/assets/387249/03d01c10-eb8f-43d5-9c29-0803fab848c4">

## Expected result:

With `Upgrade connections to HTTPS` on by default, should be redirected to `https://upgradable.arthuredelstein.net/`

<img width="1312" alt="Screen Shot 2023-08-18 at 11 45 45 AM" src="https://github.com/brave/brave-browser/assets/387249/0d6a1d01-e750-45d2-8764-17da9a8115e1">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.59.26 Chromium: 116.0.5845.96 (Official Build) nightly (x86_64)
-- | --
Revision | 81593c18d5f9ca9f49df63d0c111747ea7324ff2
OS | macOS Version 11.7.9 (Build 20G1426)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron @arthuredelstein @fmarier @brave/qa-team

**Comment by stephendonner** [comment]
Sadly, this also affects 

```
Brave | 1.57.47 Chromium: 116.0.5845.96 (Official Build) (x86_64)
-- | --
Revision | 180d2fdf443f9be410c38fd8c4ccfe7e99ea2b16
OS | macOS Version 11.7.9 (Build 20G1426)
```

<img width="1830" alt="Screenshot 2023-08-22 at 1 06 35 PM" src="https://github.com/brave/brave-browser/assets/387249/4bfc895f-82ea-4b62-a822-67e4ac9e5a4c">

**Comment by kjozwiak** [comment]
The above requires `1.58.110` or higher for `1.58.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` from 
```
Brave | 1.58.110 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | 23c4f0dccc62dccb2724a84d9aed7c6c48644e77
OS | Windows 11 Version 22H2 (Build 22621.2134)
```

Reproduced the issue in `1.57.57 Chromium: 116.0.5845.163` using STR from  https://github.com/brave/brave-browser/issues/32372#issue-1857148595
<img width="535" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/d64f6ce0-68e5-4392-b290-33d6357606ec">



- Install 1.58.110 
- launched Brave
- load http://upgradable.arthuredelstein.net/ in a new tab 

### Confirmed `With Upgrade connections to HTTPS on by default`, it was redirected to https://upgradable.arthuredelstein.net/

example | example 
----- | -----
<img width="651" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/5c614b5f-4b32-41a1-b4b0-401a94a738fc">|<img width="651" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/8e1f40ab-456b-43f5-ac6d-8fcfac5bedca">

**Comment by Uni-verse** [comment]
This also impacted Android as well at the time but is no longer reproducible using https://github.com/brave/brave-browser/releases/tag/v1.58.115. Test notes can found in https://github.com/brave/brave-browser/issues/31104#issuecomment-1707433073
