### ISSUE TITLE
Switching tab orientation causes tabs to disappear in mouseover mode 

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#32377]
## Description 

Reproduced the issue https://github.com/brave/brave-browser/issues/32282#issuecomment-1682970665.  There seem to be couple of issues here.  
Have 10 tabs open in horizontal view, switch to vertical view and enable mouseover mode and switch back to horizontal view.
clicking `x` causes all of the tabs to shift to left.  And if I have more than 10 tabs (i.e. 38 tabs), some of the tabs disappear on the horizontal view.  And if I minimize the browser and reopen, rest of the tabs disappear except for one.  I can restore the view by closing and relaunching Brave.  This happens only mousover mode.  I couldn't reproduce the behavior in expanded mode or minimized mode. Also the issue is not reproducible if vertical tabs are enabled via `brave://settings/appearance` 

## Steps to Reproduce

   1. install 1.57.49
   2. launch Brave
   3. open few tabs (10 tabs)
   4. enable vertical tabs (via context menu)
   5. enable vertical tab view in mouseover mode
   6. switch back to horizontal view
   7. click `x` icon
   8. minimize the browser and reopen 

## Actual result:

When clicked `x` icon, all of the tabs pushed to left (but all 10 tabs are shown).  However, if there more tabs (i.e.38 tabs), not all tabs are shown shown. 
When browser is minimized and reopened, only a single tab is shown.

Fewer tabs (`10 tabs`)
https://github.com/brave/brave-browser/assets/98358127/45df7200-be1a-4787-979e-229d30c26a2c

more than 10 tabs (`38 tabs`)
https://github.com/brave/brave-browser/assets/98358127/24822546-0d5f-4e44-82ea-0ba32d864c8b

## Expected result:
Tabs should be shown as expected.

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.57.49 Chromium: 116.0.5845.96 (Official Build) (64-bit)
-- | --
Revision | 8d78ad7e96630cfcd3ab4165cf0fd421d3c4f068
OS | Windows 11 Version 22H2 (Build 22621.2134)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
@rebron @sangwoo108

**Comment by sangwoo108** [comment]
Similar to https://github.com/brave/brave-browser/issues/33213

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.60.81 Chromium: 118.0.5993.54 (Official Build) beta (64-bit)
-- | --
Revision | 1efb3f333eb41cc34af46ca31fb33c30e0afbfae
OS | Windows 11 Version 22H2 (Build 22621.2283)
```

Verified using original STR from https://github.com/brave/brave-browser/issues/32377#issue-1857217743
Verified with 10 tabs and more than 10 tabs in the horizontal view

#### Confirmed when clicked x icon, all of the tabs are shown on horizontal view as expected (without pushing to left)
#### Confirmed browser is minimized and reopened, all of the tabs are shown

more than 10 tabs:
https://github.com/brave/brave-browser/assets/98358127/adf3bb62-a228-4611-88a1-b8e016b0bb8d

less than 10 tabs:
https://github.com/brave/brave-browser/assets/98358127/7c3f6340-8f04-4d8c-bac2-69af2ebfad10

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.60.81 Chromium: 118.0.5993.54 (Official Build) beta (x86_64)
-- | --
Revision | 1efb3f333eb41cc34af46ca31fb33c30e0afbfae
OS | macOS Version 13.6 (Build 22G120)
```
