### ISSUE TITLE
[Android] Remove griffin flag dependency for cookie consent dialog

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#32378]
This issue is to remove griffin flag dependency to show the cookie consent dialog.

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using the following version(s):

```
Brave	1.59.93 Chromium: 117.0.5938.88 (Official Build) beta (64-bit) 
Revision	77474ed80832bd2c90be4ebf993b6c2a43f662b0
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

- Ensured that cookie consent dialog is presented on first launch when user meets the 5 refresh/reload condition. 
- Ensured that cookie consent dialog is shown when re-launching Brave app after 4th refresh.
- Ensured that `Block cookie consent notices` is not disabled in the settings.

Example | Example | Example
-|-|-
![Screenshot 2023-09-21 at 2 38 45 PM](https://github.com/brave/brave-browser/assets/17885425/c40733e4-cee4-4550-aa58-5da302e8325c) | ![Screenshot 2023-09-21 at 2 39 37 PM](https://github.com/brave/brave-browser/assets/17885425/f6263181-c0de-449f-9e69-367e8fd52ea9) | ![Screenshot 2023-09-21 at 3 11 15 PM](https://github.com/brave/brave-browser/assets/17885425/090d3239-e947-49e1-a72b-908ea6cc473d)
