### ISSUE TITLE
`brave://settings/passwords` is showing an extra toggle; the `Allow auto-fill in private windows` option from `brave://settings/autofill`.

### ISSUE THREAD

**Issue by Emi-TheDhamphirInLoveUnderTheFrozenStar** [brave/brave-browser#32381]
## Description 

I opened passwords page to check a password and found an extra toggle next to the Filter/Search passwords section.

`Allow auto-fill in private windows` can be found in `brave://settings/autofill`, and it is also showing in the Passwords setting page as an extra floating weird toggle not making sense.

![image](https://github.com/brave/brave-browser/assets/122518587/dd2b81b0-2928-4b7c-938a-34f97a25caab)

It is the `"autofill_private_windows": false,` in preferences file.

But you can toggle one off and the other will will also be off.

https://github.com/brave/brave-browser/assets/122518587/d34fd7be-751a-4376-938d-103f9cfcf193

## Brave version (brave://version info)

1.59.29 Chromium: 116.0.5845.96 (Official Build) nightly (64-bit)  Windows 11 22H2

**Comment by diracdeltas** [comment]
i assume due to https://github.com/brave/brave-core/pull/19585; @spylogsster please take a look

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.59.90 Chromium: 117.0.5938.88 (Official Build) beta (x86_64)
-- | --
Revision | 5272112c86588e44ec7c0b766c318cddccbced85
OS | macOS Version 11.7.10 (Build 20G1427)
```

NOTE: our new `Password Manager` has moved to `brave://password-manager/passwords`

### Steps:
1. first, reproduced the issue with `1.59.29`
2. installed `1.59.90`
3. launched Brave
4. loaded `brave://settings`
5. clicked on `Autofill & Passwords`
6. clicked on `Password Manager`

### Confirmed no extraneous toggle on either screen

`brave://settings/autofill` | `brave://password-manager` | `1.59.29`
---------|----------|----------
<img width="1172" alt="Screen Shot 2023-09-18 at 12 43 17 AM" src="https://github.com/brave/brave-browser/assets/387249/17358a30-f6b6-451b-933b-06a41bb1545b"> | <img width="1172" alt="Screen Shot 2023-09-18 at 12 43 26 AM" src="https://github.com/brave/brave-browser/assets/387249/fc076f06-1e9e-429c-b05c-b1784e4863ef">  | <img width="1966" alt="Screen Shot 2023-09-18 at 12 16 20 AM" src="https://github.com/brave/brave-browser/assets/387249/6ff65809-9c27-4f8d-9272-69c1ce5c407c">
