### ISSUE TITLE
The Rewards master switch is not always obvious as a switch rather than a header.

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#3238]
We've heard feedback that the master switch at the top of the Brave Rewards comes off as just being a heading — people miss the fact that there's a switch which controls all of Rewards.

![screen shot 2019-02-05 at 3 00 39 pm](https://user-images.githubusercontent.com/639937/52310105-1869ef00-2957-11e9-9ef7-ca7e229e3258.png)

**Comment by NejcZdovc** [comment]
closing as master switch is going away
