### ISSUE TITLE
clean up requests to wayback machine

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#32385]
hackerone: https://hackerone.com/reports/2117006
credit: [xiaoyinl](https://hackerone.com/xiaoyinl)

**Comment by kjozwiak** [comment]
The above requires `1.57.57` or higher for `1.57.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.57.57 Chromium: 116.0.5845.163 (Official Build) (arm64) 
Revision	d85db1f5df3b20ffecf96ab3f0dc7fca1d536955
OS	macOS Version 13.5.1 (Build 22G90)
```
