### ISSUE TITLE
If `#brave-vpn-wireguard` flag is disabled, Wireguard services should not run OR old flag should be removed

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#32382]
## Description 

If Brave VPN Wireguard services are not enabled via `brave://flags/#brave-vpn-wireguard` flag, the value should be respected, and the Service (BraveNightlyVpnWireguardService) should be in `Stopped` status instead of `Running` as can be verified via Task Manager > Services

## Steps to Reproduce

1. Install 1.59.28
2. launch Brave
3. turn off (inactive) company VPN (Wireguard)
4. disable the flag for `brave://flags/#brave-vpn-wireguard`
5. click VPN button >> Already purchased VPN button in a new tab
6. connect to VPN via VPN panel with the existing credentials
7. hovered over network connections and it shows `wireguard.brave` connected
6. open Task Manager > Services 

## Actual result:

Taskmanager shows `BraveVpnNightlyWireguardTunnelService` status `Running`

https://github.com/brave/brave-browser/assets/98358127/49bf4d96-3ee9-4efd-9823-c92337715c22

## Expected result:
Brave VPN wireguard service should not be running 

## Reproduces how often: 

Easily 

## Brave version (brave://version info)

```
Brave | 1.59.28 Chromium: 116.0.5845.96 (Official Build) nightly (64-bit)
-- | --
Revision | c5f495e1d4d870a7622249b14df7fa33a9e862b8
OS | Windows 11 Version 22H2 (Build 22621.2134)
```
## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
@spoletav @bsclifton 
cc: @stephendonner

**Comment by stephendonner** [comment]
Can also confirm using

```
Brave	1.59.29 Chromium: 116.0.5845.96 (Official Build) nightly (64-bit) 
Revision	3a222310a0138980acc0eede4999e516061ed8af
OS	Windows 10 Version 22H2 (Build 19045.3324)
```

![image](https://github.com/brave/brave-browser/assets/387249/fcb8954c-274b-4e96-9ef2-042f8fc573c0)

**Comment by bsclifton** [comment]
After https://github.com/brave/brave-core/pull/19531 you can toggle WireGuard via brave://settings/system

I think the solution would be to delete brave://flags/#brave-vpn-wireguard

It was raised here:
https://github.com/brave/brave-core/pull/19531/files#r1290332190

But problem was we needed to know value for migration. Now, we are enabling by default (with https://github.com/brave/brave-core/pull/19739). I think we're good to delete 😄👍

**Comment by spylogsster** [comment]
> After [brave/brave-core#19531](https://github.com/brave/brave-core/pull/19531) you can toggle WireGuard via brave://settings/system
> 
> I think the solution would be to delete brave://flags/#brave-vpn-wireguard
> 
> It was raised here: https://github.com/brave/brave-core/pull/19531/files#r1290332190
> 
> But problem was we needed to know value for migration. Now, we are enabling by default (with [brave/brave-core#19739](https://github.com/brave/brave-core/pull/19739)). I think we're good to delete 😄👍

done in https://github.com/brave/brave-core/pull/19794

**Comment by bridiver** [comment]
> I think the solution would be to delete brave://flags/#brave-vpn-wireguard

@bsclifton I don't think we should remove the flag. We can remove it from `about://flags`, but we should keep it so we can still remotely disable through griffin

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.59.93 Chromium: 117.0.5938.88 (Official Build) beta (64-bit)
-- | --
Revision | 77474ed80832bd2c90be4ebf993b6c2a43f662b0
OS | Windows 10 Version 22H2 (Build 19045.3448)
```

### Steps:
1. installed `1.59.93`
2. launched Brave
3. opened `brave://flags`
4. confirmed no `WireGuard` entry
5. restarted (to pick up Griffin seed)
6. opened `brave://version`
7. confirmed no `WireGuard` study enabled
8. opened `brave://settings/system`
9. disabled `Use WireGuard protocol in Brave VPN`
10. clicked `Relaunch`
11. purchased, configured, and connected to `BraveVPN`

### Confirmed I was connected using `IKEv2`, not `WireGuard`

`brave://flags`| `brave://version` | `brave://settings/system`, default | `pref-change pending` | `brave://settings/system`, `WireGuard disabled` | `Connected to Brave VPN via IKEv2`
----------|----------|-----------|-----------|-----------|---------
![image](https://github.com/brave/brave-browser/assets/387249/fa5d3cb8-bbe9-4074-bd9c-309a63f64c00) | ![image (1)](https://github.com/brave/brave-browser/assets/387249/0d38c376-8053-442a-aa1c-09cb04acc578) | ![image (2)](https://github.com/brave/brave-browser/assets/387249/0f7f8664-1bb5-4f91-a984-8c2a5c86ea87) | ![image (3)](https://github.com/brave/brave-browser/assets/387249/deb2149e-8e7b-424c-bd12-dafed00a6478) | ![image (4)](https://github.com/brave/brave-browser/assets/387249/0e6dc4b6-050a-43a0-8a6c-5c518d9ae294) | ![image (5)](https://github.com/brave/brave-browser/assets/387249/55d8bad5-555c-406b-82f1-9fd77278881d)

### Also confirmed the `BraveBetaVPNWireguardService` was stopped, via the `Services` tab in `Task Manager`

![image](https://github.com/brave/brave-browser/assets/387249/8f7f9f54-7a40-47c7-b379-4144bfe6dade)

**Comment by LaurenWags** [comment]
Changing to `release-notes/exclude` per discussion with @kjozwiak @rebron - will use https://github.com/brave/brave-browser/issues/32002 as the main WireGuard issue in the notes.
