### ISSUE TITLE
[Android] ZebPay — Phase 1

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#32386]
Android version of https://github.com/brave/brave-browser/issues/32036.

**Comment by kjozwiak** [comment]
The above requires `1.58.110` or higher for `1.58.x` verifications 👍

**Comment by kjozwiak** [comment]
@LaurenWags @GeetaSarvadnya added `QA/Test-All-Platforms` but please remove if you feel differently. Should at least check the above on `Tablet` to make sure none of the UI/UX is broken due to the different size. Probably a good idea to spot check `Android 8` to make sure there's no obvious issues/crashes.

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Samsung Galaxy version 12` running `Bravemonoarm54.apk_1.58.110`

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Samsung Galaxy Tab S8 Ultra` running `Android 14` using the following build(s):

```
Brave | 1.58.125 Chromium: 117.0.5938.62 (Official Build) (64-bit)
--- | ---
Revision | 8ed90c22c7a876855ef8cb4c2872dd7b69beb594
OS | Android 13; Build/TP1A.220624.014; 33; REL
```

As discussed with @LaurenWags, quickly checked the area's where we're showing logo's/UI and ensured that everything appears correctly on a `Tablet` as we've historically had issues with UI/UX on `Tablet` that worked fine on mobile devices.

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|----------------|-----------------
![Screenshot_20230914_214129_Brave](https://github.com/brave/brave-browser/assets/2602313/b052bb6a-fd89-47f0-bd0a-d4e91241e8ff) | ![Screenshot_20230914_214322_Brave](https://github.com/brave/brave-browser/assets/2602313/de52cdea-bd21-477f-9211-bfa5be95df76) | ![Screenshot_20230914_214551_Brave](https://github.com/brave/brave-browser/assets/2602313/007658e1-976b-4f4c-9bb7-d3f24d2db684) | ![Screenshot_20230914_214741_Brave](https://github.com/brave/brave-browser/assets/2602313/d79d26f0-c049-4182-9745-71425d10335b) | ![Screenshot_20230914_214747_Brave](https://github.com/brave/brave-browser/assets/2602313/cf16a47f-22e1-4923-b76d-834c6a815f57)

**Comment by SibahleRwaqa** [comment]
I had a similar bad experience with Zebpay. After responding to the ad in December 2023 I was contacted by zebpay who invited me to trade. I visited their website and was told I could make R30,000 to R50,000 pm on their platform. They told me I needed to add more funds. I began trading, always under the advice of a “success manager.” Three months later I have lost nearly R800,000 but I got my money back with the help of a good expert. BanninkSolutions is the licensed expert I use. Just research the name. You’d find the necessary details to work with a correspondence to set up an appointment.. You can also message them at telegram: @banninksolutions and also email: Banninksolutions @proton.me .
It's not a nice idea for anyone to trust this platform, they only extort from your account and disable everything when you request for withdrawal. I was only lucky enough to get it resolved.

**Comment by LebogangLebo22** [comment]
All task Mall PLATFORM ARE s*cams  kINDLY READ SO YOU DO NOT FALL VICTIM IF YOU DID ALREADY USE VOS RECOVERY TO GET YOUR  MONEY BACK . SEARCH VOS9112 ON TELEGRAM .

I saw post Amazon task mall online jobs and apply on FB and redirected to whatsapp. Isabella who recruit me and advice to register.after registration she teach how to do task. Recharge 14 and first for task .after two task again task came with difference 61 and . When I ask she told you will get back this amount with your commission at end of task. She advised to complete 10 task and advised to contact service manager Alina .

There are different accounts of the fake amazon people where they received the money, I have the list all of them given below
sadapay


03406167877
Zeenat Bibi
IBAN:PK08SADA0000003406167877
Easypaisa 12k

United bank limited
Asif mumtaz
PK27UNIL0109000242437932
UBL= 35k


Imran Ahmad
United bank limited
IBAN PK87UNIL0109000289867136
UBL= 72k

Imran Ahmad
United bank limited
IBAN :PK87UNIL0109000289867136
UBL= 138K

United bank limited
Hassan mumtaz
IBAN PK26UNIL0109000244622972
289k

I paid R148870 on AMAZON TASK MALL WORK AT HOME JOBS ONLINE PLATFORM  and completed all task. I wanted to withdraw she told me I needed to upgrade my account VIP LEVEL THEN ONLY I CAN withdraw. I asked her why didn’t not tell before . I borrowed money from friends and pay. I can’t withdraw. They are were not  willing to payback . I was told I  needed to pay more for my commission withdrawal so I had no choice than to seek help to get my money back then a friend introduce me to an expert popularly know as VOS  . They gave me steps to take and VOS  help me recover all my money .If you fall into something like this task mall platform then you need to go to telegram : vos9112 so you can get your money back before it is too late.
