### ISSUE TITLE
Android :: Update "lock" icon to "tune" icon in address bar

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-browser#32380]
## Description 

Needed for C117

Details: https://github.com/brave/brave-browser/issues/31642
Figma: https://www.figma.com/file/H11ZOl6JMYbCTW4ZJXqR5V/%F0%9F%A6%81-Browser?type=design&node-id=2050%3A19224&mode=design&t=eXPxIDq3WXHZFVxo-1

**Comment by samartnik** [comment]
This will be fixed in the context of rebasing to C177 https://github.com/brave/brave-browser/issues/31768

**Comment by samartnik** [comment]
![Screenshot_20230824-162256](https://github.com/brave/brave-browser/assets/30602739/050fd3bc-de9e-4476-aad7-2c0c5ebd58db)

**Comment by Uni-verse** [comment]
In progress on `Samsung GS 21`
