### ISSUE TITLE
[hackerone] validate wayback URL before navigating

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#32395]
see https://bravesoftware.slack.com/archives/C6R461GF4/p1692466879103279?thread_ts=1692442338.103219&cid=C6R461GF4 for details

reported at https://hackerone.com/reports/2117246 and https://hackerone.com/reports/2113111 by [xiaoyinl](https://hackerone.com/xiaoyinl)

STR:
1. Launch and load brave.com/bo
2. Check wayback infobar is loaded
3. By using proxy tool such as (Proxyman or fiddler), modify response for `https://brave-api.archive.org/wayback/available?url=https://brave.com/bo/`.
 ```
{
  "url": "https://brave.com/bo/",
  "archived_snapshots": {
    "closest": {
      "status": "200",
      "available": true,
      "url": "javascript:alert()",
      "timestamp": "20150906092942"
    }
  }
}
```
4. Check infobar says `Sorry, there is no saved version available.` 

Note: As it's platform independent, checking on one platform would be sufficient.

**Comment by kjozwiak** [comment]
The above requires `1.57.57` or higher for `1.57.x` verification 👍
