### ISSUE TITLE
Widen Shields panel to avoid text wrapping

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#3239]
Some of the legends on the Shields panel are cut off because of the panel's width. Let's make the panel wider so this doesn't happen, even in longer languages.

**Comment by karenkliu** [comment]
This is mostly avoided with the new updates in #2565, which includes widening the panel so that it's the same width as the Rewards panel. Please also take a look at the specs in #2996 which tests the UI in Russian, the language that usually has the longest text strings.

**Comment by cezaraugusto** [comment]
can we close this? I guess we're in a good size now cc @karenkliu

**Comment by karenkliu** [comment]
Yeah I think this issue is out of date.
