### ISSUE TITLE
Update Wayback Machine info bar `Don't show again` button to checkbox

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#32404]
## Description 

The current Wayback Machine info bar uses a button for `Don't show again`.
We should use a checkbox for consistency and minimize mis-clicks if a user meant to `Close` the info bar instead of `Don't show again`

## Steps to Reproduce

   1. Visit a page that will trigger the Wayback machine prompt `rebron.org/test.html`
   2. Notice Wayback machine info bar.
   3. Should be a Don't show again checkbox.

## Actual result:

<img width="1203" alt="Screenshot 2023-08-20 at 1 40 19 PM" src="https://github.com/brave/brave-browser/assets/5951041/3b899d7e-6556-43b7-848d-f452a9998fe9">

Example of checkbox in the info bar re: OS notification
![259514955-cc0af0e5-749f-4ac2-ab1a-eb8c181ff231](https://github.com/brave/brave-browser/assets/5951041/17fd7638-ba77-4072-8940-91c75509a176)

## Expected result:
Use checkbox instead of button.

## Reproduces how often: 

easily

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by simonhong** [comment]
Working on this.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.59.102 Chromium: 117.0.5938.140 (Official Build) beta (arm64)
-- | --
Revision | 11284b6d5d51252fe1a6fb6b5cba35ef98982357
OS | macOS Version 14.0 (Build 23A344)
```
