### ISSUE TITLE
Extensions cannot be updated

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#3240]
Extensions installed from the Chrome Web Store are not updated automatically. Manual update attempts are also unsuccessful. Extensions should be updated automatically.

**Comment by jumde** [comment]
Dupe: https://github.com/brave/brave-browser/issues/1319?  The fix has not been pushed into production yet.

**Comment by tomlowenthal** [comment]
Maybe? Not sure if extensions use the same method.

Also, here's a community comment: to the same effect: https://community.brave.com/t/how-to-get-chrome-extension-up-to-date/43177/2

**Comment by jumde** [comment]
This has been fixed: https://github.com/brave/brave-browser/issues/3258. Will open uplift requests for 0.60/0.61 soon

**Comment by rebron** [comment]
@jumde reminder to set milestone once prs are merged.

**Comment by jumde** [comment]
@rebron - I had the milestone set in the original issue (https://github.com/brave/brave-browser/issues/3258), will make sure to update the milestones for dupes as well. Thanks!

**Comment by srirambv** [comment]
Dupe of #3258 which is already verified
