### ISSUE TITLE
Don't show vertical tab strip when in Full screen mode 

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#32415]
## Description 

Filing this issue as per a user's request. "When watching twitch in theatre mode and F11, the vertical tab stays visible and takes away from the immersion”.  

## Steps to Reproduce

   1. Install 1.57.49
   2. launch Brave
   3. open twitch TV in a new tab 
   4. enable vertical tab view 
   5. click F11 for Fullscreen mode
   

## Actual result:

Vertical tab view panel is still shown 
Example | Example 
----- | ----
<img width="951" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/6e32f793-923f-4d55-af41-797c5eceba46">|<img width="955" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/21e0dbbe-5ee1-43cd-97ca-1b592c004213">

## Expected result:
<img width="959" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/8d6e5140-48f1-4096-9ac7-428cdc2001c6">

## Reproduces how often: 

Easily 

## Brave version (brave://version info)

```
Brave | 1.57.49 Chromium: 116.0.5845.96 (Official Build) (64-bit)
-- | --
Revision | 8d78ad7e96630cfcd3ab4165cf0fd421d3c4f068
OS | Windows 11 Version 22H2 (Build 22621.2134)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
@rebron @sangwoo108

**Comment by rebron** [comment]
Shouldn't disable vertical tabs. Clarifying request that in vertical tabs mode, choosing full screen should be true full screen and hide vertical tab strip.

**Comment by kjozwiak** [comment]
The above requires `1.58.109` or higher for `1.58.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.58.110 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | 23c4f0dccc62dccb2724a84d9aed7c6c48644e77
OS | Windows 11 Version 22H2 (Build 22621.2134)
```

- Installed 1.58.110
- launched Brave
- open https://www.twitch.tv/  in a new tab
- enable vertical tab view
- click F11 for Fullscreen mode

### Confirmed vertical tab strip no longer shown in in full screen mode 

vertical tabs enabled | F11-full screen | theater mode 
---- | ---- | -----
<img width="960" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/fc43c823-e6cf-420d-9d24-211e49fb3c8b">|<img width="951" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/f0758925-971f-4ac9-990d-002313c97fc8">|<img width="937" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/68154cd8-0ead-4c53-b44d-c8f8b193fc6d">

**Comment by kdenhartog** [comment]
It seems odd that tabs are no longer displayed in fullscreen mode at all whether enabled hover mode or not. It makes sense that this would be true theater mode of video content, but this change has now broken all tab usage on Mac OS.

![Screenshot 2023-09-05 at 12 40 47 PM](https://github.com/brave/brave-browser/assets/23125059/93ed3581-bd23-4173-9e89-3865defdf5a2)


cc @sangwoo108 or @rebron can we retake a look at this before shipping?

**Comment by sangwoo108** [comment]
Hello, we've gotten mixed response about this change. So we'll be reverting this change for the time being, and make a hover-and-show feature for vertical tabs. I'll try my best to get it done asap.
