### ISSUE TITLE
Redesign Wallet navigation and merge assets and NFTs into a single section

### ISSUE THREAD

**Issue by simoarpe** [brave/brave-browser#32411]
## Description

Overhaul Portfolio navigation following the latest Figma design and merge together assets and NFT using a chip tab layout.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.59.93 x64 Beta build
- Verified steps from [brave/brave-core#19811](https://github.com/brave/brave-core/pull/19811)
- Verified NFT is shown in a separate tab in portfolio
- Encountered [#33210](https://github.com/brave/brave-browser/issues/33210) on Tablet

Oppo Reno 5 (Android 13) | Lenovo Tab (Android 12)
-- | --
<video src=https://github.com/brave/brave-browser/assets/17010094/1a9fedc3-e41c-4b52-a1f4-22c230694910> | <video src=https://github.com/brave/brave-browser/assets/17010094/d6dbf6b9-a52c-4877-bf81-add766c21cd8>
