### ISSUE TITLE
Inspector closing after 2 seconds

### ISSUE THREAD

**Issue by OxyFlax** [brave/brave-browser#32412]
## Description 

From the last version of the Mac app, it is impossible to keep the console / inspector open. 

## Steps to Reproduce

   1. Open any website
   2. Right click and pick "inspect"
   3. Wait for 3 seconds

## Actual result:

Console opens and close itself without any action from our side

## Expected result:
Console should be kept open

## Reproduces how often: 

I can reproduce this in all tabs, any website, even after completely closing the browser.

## Brave version (brave://version info)

1.57.47 Chromium: 116.0.5845.96 (Official Build) (arm64) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? not tested
- Can you reproduce this issue with the nightly channel? not tested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by OxyFlax** [comment]
Issue looks to be resolved, not sure why as there was no update

**Comment by dimfeld** [comment]
I encountered this as well and it turned out to be https://bugs.chromium.org/p/chromium/issues/detail?id=1473992#c13. There's a workaround in comment 13

**Comment by rebron** [comment]
@OxyFlax No longer an issue for you? Not an issue in Chromium 117 which is what we have in 1.58.124?

**Comment by OxyFlax** [comment]
It happens randomly, yesterday still happening, today not...

**Comment by OxyFlax** [comment]
Closing as it's been a long time I'm not experiencing it
