### ISSUE TITLE
Reorganize application menu structure

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#32410]
Sub task of https://github.com/brave/brave-browser/issues/32089

**Comment by fallaciousreasoning** [comment]
Out of interest, there are a bunch of items that have disappeared. I take it that's intentional:
- Brave Rewards
- Sync
- Sidebar (and submenu)
- Add new profile (maybe in the separate profile menu already?)
- Open guest profile (maybe in the separate profile menu already?)
- Cast (personally, I use this one sometimes when sites don't natively support casting. Maybe it's being moved to the more tool submenu?)
- Report broken site (maybe going into the help menu?)
- About (maybe going into the new help menu?)

**Comment by simonhong** [comment]
> ~Out of interest, there are a bunch of items that have disappeared. I take it that's intentional:~
> 
> * ~Brave Rewards~
> * ~Sync~
> * ~Sidebar (and submenu)~
> * ~Add new profile (maybe in the separate profile menu already?)~
> * ~Open guest profile (maybe in the separate profile menu already?)~
> 
> edit: Don't worry, I found them all 😆 Should've zoomed out

I also couldn't find at first.
but still can't find `Brave Rewards` :)

**Comment by rebron** [comment]
We're leaveing out Brave Rewards from the menu as we have prominent position in the Address Bar.

**Comment by simonhong** [comment]
@rebron  When site support pwa, app manu has `Install Twitter` item like below.
It should be moved into `More tools` submenu also?
<img width="752" alt="image" src="https://github.com/brave/brave-browser/assets/6786187/424856ee-72bc-4ac9-9402-1e031db213f8">

**Comment by rebron** [comment]
We can keep that there. That's not going be there for all sites and I don't think we should bury that one. We should use our modified Installed App similar to the one in the address bar for that icon.

**Comment by aguscruiz** [comment]
Agree with @rebron, I think having it on the root level for sites that support it is nice, so it doesn't get buried. And yeah, we can use the same icon as in the url bar

**Comment by LaurenWags** [comment]
Have reached out to @rebron for additional information, marking as `QA/Blocked` for now.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED`
```
Brave | 1.59.103 Chromium: 117.0.5938.140 (Official Build) beta (64-bit)
-- | --
Revision | e0f257d585b29dd1194e82717cf18db50a7c0edb
OS | Windows 11 Version 22H2 (Build 22621.2283)
```
Per https://github.com/brave/brave-browser/issues/32410#issue-1858846626 this issue only covers placement/text, icons are covered under separate issue https://github.com/brave/brave-browser/issues/32089. Also, missing icons are logged under various issues, see 32089 for more information.

Normal Window - Light | Normal Window - Dark | Private Window | Tor Window | Guest Window
------------- | ------------ | -------------- | -------------- | -------------
<img width="186" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/80acfe8d-1587-479d-ba14-cc70ecc0145d">|<img width="181" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/8c7a4133-c25a-4115-8425-ae801e995030">|<img width="184" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/557b08f1-7765-4fd5-841f-f30464da8293">|<img width="178" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/c27a8543-c6a0-43c5-afc2-57a2b6928ead">|<img width="178" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/e6933840-70ec-4f1c-ac58-53636bf919ab">

<details>
<summary>Normal Window - PASSED</summary>

### **`Main level menu`**

Confirmed order/existence of below items for Normal Window menu as per text description of issue (not screenshot):

---
a. `New Tab`
b. `New Window`
c. `New Private Window`
d. `New Private with Tor`

---
e. `Wallet`
f. `Brave VPN`
(optional - only shows in certain cases, to be verified separately) g. `IPFS`

---
h. `History`
i. `Bookmarks`
j. `Downloads`
k. `Extensions`
l. `Password manager`

---
m. `Zoom`  `- 100% +` and `[ ]` for full screen

---
n. `Print...`
o. `Find...`
(optional - only shows in certain cases, to be verified separately) p. `Install [PWA name]` 
q. `More Tools`

---
r. `Edit` `Cut` `Copy` `Paste`

---
s. `Help` 
t. `Settings`
u. `Exit` 

---

Confirmed when IPFS is not enabled, it does not display (see above screenshots).
Confirmed when on a site that does not have a PWA to install (ex. brave.com), no PWA item displays in the menu (see above screenshots).


Confirmed when IPFS is not enabled, it does not display (see above screenshots).
Confirmed when on a site that does not have a PWA to install (ex. brave.com), no PWA item displays in the menu (see above screenshots).
Confirmed Exit does not show on menu for macOS.

Normal Window - Light | Normal Window - Dark 
--- | --- 
<img width="186" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/80acfe8d-1587-479d-ba14-cc70ecc0145d">|<img width="181" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/8c7a4133-c25a-4115-8425-ae801e995030">

### **`Optional main level menu items`**

Confirmed when IPFS is enabled, it displays in the application menu.
Confirmed when on a site that has a PWA available (ex. GitHub.com), PWA item displays in the menu.

IPFS enabled | PWA Available
--- | ---
<img width="191" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/5e20f628-4687-4917-85a1-c65ab12b03eb">|<img width="184" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/46793d27-99b3-4206-b66f-e359fe19854d">


### **`Submenus`**

1. Brave VPN
- Confirmed "Brave VPN" submenu displayed when VPN was purchased. 
- Confirmed "Brave VPN" submenu displayed as per issue description:
   - Brave VPN (on/off toggle) 
   - Send Feedback 
   - About Brave VPN 
   - Manage My Plan

2. IPFS sub-menu 
- Confirmed "IPFS" submenu displays when IPFS is enabled/running
   -  Import and Share a File
   - Import and Share a Directory 
   - Open Files 
   - Update IPNS (if applicable) 
      - With a File 
      - With a Directory

3. History sub-menu 
- History 
- Clear Browsing Data... (this was moved here from More Tools) 
- Recently closed [list of tabs] 
- Synced devices e.g. iPhone [list of tabs].

4. Bookmarks sub-menu 
- Bookmarks This Tab... 
- Bookmark All Tabs... 
- Show Bookmarks 
   - Always 
   - Never 
   - Only on the New Tab page 
- Bookmark manager... 
- Import Bookmarks and Settings... 
- [List of Bookmarks]
- [Recently Closed History items]

5. More tools sub-menu 
- Add New Profile 
- Open Guest Profile 
- Show Sidebar 
   - Always
   - On mouseover
   - Never 
- Sync 
- Save Page As... 
- Create Shortcut... 
- Name Window... 
- Performance 
- Developer Tools 
- Task Manager


6. Help sub-menu 
- About Brave 
- Help Center 
- Report a Broken Site

7. Exit 

Brave VPN | IPFS | History | Bookmarks | More Tools | Help | List of Bookmarks | History entries | Show Sidebar menu
------- | ------- | ------- | ------- | ------- | ------- | ------- | ------  | ------
<img width="316" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/3ebd20ee-f0ce-4ef2-8f75-98cce5a6062d">|<img width="269" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/04cf0557-9ae0-4fae-8782-82ba38ebfefa">|<img width="326" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/0729caad-0520-4113-a041-3305366d269c">|<img width="359" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/59a5218f-d038-4fb3-a317-6098a032d212">|<img width="330" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/810b71a8-b59f-4e18-bd8f-113343c34182">|<img width="270" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/087c7abd-2f3c-4260-80f2-91fe9f99d6ad">|<img width="316" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/158a963f-3a43-4b4e-baba-76f67af5b28a">|<img width="421" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/90cf5d8c-e09c-4154-a8ef-3c6d04134aad">|<img width="335" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/6994fbb9-d65d-4b1b-9488-c53a28baabcd">


</details>


<details>
<summary>Private Window - PASSED</summary>

### **`Main level menu`**

Confirmed order/existence of below items for Private Window menu as per text description of issue (not screenshot):

---
a. `New Private Tab`
b. `New Window`
c. `New Private Window`
d. `New Private Window with Tor`

---
e. `Wallet`

---
i. `Bookmarks`
j. `Downloads`
k. `Extensions`

---
m. `Zoom`  `- 100% +` and `[ ]` for full screen

---
n. `Print...`
o. `Find...`
q. `More Tools`

---
r. `Edit` `Cut` `Copy` `Paste`

---
s. `Help` 
t. `Settings`

---
q.  `Exit`

Confirmed Brave VPN does not display on Private Window menu.
Confirmed IPFS does not display on Private Window menu.
Confirmed History does not display on Private Window menu.
Confirmed Password Manager does not display on Private Window menu.
Confirmed when on a site that does have a PWA to install (ex. GitHub.com), no PWA item displays in the menu.


Example | Example
--- | ---
<img width="589" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/4809e1db-ab48-4744-b36b-a8e76e3e4eff">|<img width="959" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/272a3dc1-beab-4838-949f-3c6402d0f452">

</details>
<details>
<summary>Private Window with Tor - PASSED</summary>

### **`Main level menu`**

Confirmed order/existence of below items for Private Window with Tor menu as per text description of issue (not screenshot):

---
a. `New Private Tab`
b. `New Tor connection for this site`
c. `New Window`
d. `New Private Window`
e. `New Private Window with Tor`

---
f. `Wallet`

---
i. `Bookmarks`
j. `Downloads`
k. `Extensions`

---
m. `Zoom`  `- 100% +` and `[ ]` for full screen

---
n. `Print...`
o. `Find...`
q. `More Tools`

---
r. `Edit` `Cut` `Copy` `Paste`

---
s. `Help` 
t. `Settings`

---
q.  `Exit` 

Confirmed addition of New Tor connection for this site on Private Window with Tor menu.
Confirmed Brave VPN does not display on Private Window with Tor menu.
Confirmed IPFS does not display on Private Window with Tor menu.
Confirmed History does not display on Private Window with Tor menu.
Confirmed Password Manager does not display on Private Window with Tor menu.
Confirmed when on a site that does have a PWA to install (ex. GitHub.com), no PWA item displays in the menu.


Example | Example
--- | ---
<img width="392" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/9f725c03-50e1-4017-9d99-7cf2beeec5a5">|<img width="953" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/79756ea7-2320-45e6-ac3c-c244c9861694">


### **`Submenus`**

1. Bookmarks sub-menu 
- Bookmarks This Tab... 
- Bookmark All Tabs... 
- Show Bookmarks 
   - Always 
   - Never 
   - Only on the New Tab page 
- Bookmark manager... 
- Import Bookmarks and Settings... 
- [List of Bookmarks]

2. More tools sub-menu 
- Add New Profile 
- Open Guest Profile 
- Show Sidebar 
   - Always
   - On mouseover
   - Never 
- Sync 
- Save Page As... 
- Create Shortcut... 
- Name Window... 
- Performance 
- Developer Tools 
- Task Manager

3. Help sub-menu 
- About Brave 
- Help Center 
- Report a Broken Site

Bookmarks | More Tools | Help
--- | --- | ---
<img width="422" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/5607b727-c385-40dd-82b9-0ca9c931061f">|<img width="341" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/397e2603-f492-45ac-aa96-8bb6405b3fda">|<img width="282" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/f922d1cf-081f-46dc-be9a-a359b6c187d2">

</details>

<details>
<summary>Guest Window - PASSED</summary>

### **`Main level menu`**

Confirmed order/existence of below items for Guest Window menu as per text description of issue:
 
a. `New Tab`
b. `New Window`
c. `Downloads`
d. `Zoom`  `- 100% +` and `[ ]` for full screen
e. `Print...`
f. `Find`
g. `More Tools...`
h. `Edit` `Cut` `Copy` `Paste`
i. `Help`
j. `Settings`

<img width="586" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/85761715-e649-46be-acb9-c42188804be9">

### **`Submenus`**

Confirmed that `Sidebar` settings were moved to `More Tools` submenu.
Confirmed that `Help` submenu includes `Help Center` `About Brave` and `Report a Broken Site`

More Tools | Help | Sidebar menu
--- | ---| -----
<img width="319" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/fb29c8bc-12ce-4709-b225-01733ef72f0d">|<img width="275" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/bf908de1-36c8-4b9e-ad12-d2fcccf55a7f">|<img width="323" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/c910a765-659e-444b-bfc2-736d8f8063a5">

</details>

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using

```
Brave | 1.59.107 Chromium: 117.0.5938.140 (Official Build) beta (64-bit)
-- | --
Revision | 5bbd53ed3e41461e15555b7ce0490464656b236f
OS | Linux
```
