### ISSUE TITLE
Brave Wallet Freeze the mac, crash it and restart it since 3 months

### ISSUE THREAD

**Issue by nbdy-coder** [brave/brave-browser#32427]
## Description 
Hello,
Since 3 months, if i open the brave wallet with my macbook pro m1, my computer crash and reboot.
I also test with another macbook m1 and same problem.
Both mac are updated and brave browser have the last update. I had the same problem with the old updates.
I already created a ticket but i never had any response.
The issue is not normal, your browser is definitely unstable.

## Steps to Reproduce

connect brave wallet on a macbook pro m1
navigate in the wallet during few seconds/minutes
computer freeze, crash and reboot

## Actual result:
freeze, crash and reboot

## Expected result:
Should not crash

## Reproduces how often: 
easily

## Brave version (brave://version info)
Version 1.57.47 Chromium: 116.0.5845.96 (Build officiel) (arm64)

**Comment by rebron** [comment]
@nbdy-coder Can you update to our latest version 1.58.129 and let us know if you're still experiencing this freeze?

**Comment by nbdy-coder** [comment]
> @nbdy-coder Can you update to our latest version 1.58.129 and let us know if you're still experiencing this freeze?

it's working now. thanks
