### ISSUE TITLE
Update DApp Connection Button to be Oval Shaped

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#32429]
## Description 

We need to update the `DApp Connection` button to be `oval` shaped in the Wallet `Panel`

![Screenshot 23](https://github.com/brave/brave-browser/assets/40611140/70d01c1c-2800-4d72-aab2-e3c5b6ac893f)

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.59.112 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | `967f25f295938c64c24e2e6a1790470668757655`
OS | Windows 11 Version 22H2 (Build 22621.2283)

- Verified steps from [brave/brave-core#19816](https://github.com/brave/brave-core/pull/19816)
- Verified on  internal page/chrome origin pages, `DApp Connection Status` is hidden in panel
- Verified on a Dapp, `DApp Connection Status` is shown in panel UI

https://github.com/brave/brave-browser/assets/17010094/e550cece-9a14-4c81-9a7c-210df5a2684d

---------------------

**Verification passed on**

Brave | 1.59.112 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | `967f25f295938c64c24e2e6a1790470668757655`
OS | Linux

- Verified steps from [brave/brave-core#19816](https://github.com/brave/brave-core/pull/19816)
- Verified on  internal page/chrome origin pages, `DApp Connection Status` is hidden in panel
- Verified on a Dapp, `DApp Connection Status` is shown in panel UI

https://github.com/brave/brave-browser/assets/17010094/64119bc3-1594-4219-93fd-23872c7b0f81


---------------------

**Verification passed on**

Brave | 1.59.112 Chromium: 118.0.5993.54 (Official Build) (arm64)
-- | --
Revision | `967f25f295938c64c24e2e6a1790470668757655`
OS | macOS Version 14.0 (Build 23A344)

- Verified steps from [brave/brave-core#19816](https://github.com/brave/brave-core/pull/19816)
- Verified on  internal page/chrome origin pages, `DApp Connection Status` is hidden in panel
- Verified on a Dapp, `DApp Connection Status` is shown in panel UI

https://github.com/brave/brave-browser/assets/17010094/10fc39d7-dba9-4501-979b-6cdf01c37ad5
