### ISSUE TITLE
[hackerone] rewards navigation issues (Desktop)

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#32424]
Validate that origins are ONLY allowed to navigate to their own paths.

The first issue was reported at https://hackerone.com/reports/2117571 by [0xc4gr1](https://hackerone.com/0xc4gr1)

**Comment by szilardszaloki** [comment]
Corresponding Android issue: https://github.com/brave/brave-browser/issues/32498

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.59.86 Chromium: 117.0.5938.62 (Official Build) beta (x86_64)
-- | --
Revision | 3c4c1c3b2eef0fcbe8485c67e1df504942deadca
OS | macOS Version 13.5.2 (Build 22G91)
```
