### ISSUE TITLE
Hide Connection Status for Chrome Origins

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#32428]
## Description 

We need to hide the `DApp Connection` status in the Wallet `Panel` when you are on any `chrome://` or `chrome-untrusted://` origin.

![image](https://github.com/brave/brave-browser/assets/40611140/37ef8036-199e-47b1-8548-138bf1f12cce)

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/32429#issuecomment-1751076879
