### ISSUE TITLE
[hackerone] onion site referrer issue

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#32421]
https://hackerone.com/reports/2117537 reported by [xiaoyinl](https://hackerone.com/xiaoyinl)

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.62.33 Chromium: 119.0.6045.105 (Official Build) nightly (x86_64)
-- | --
Revision | f2e65ce54724df1b0d04a6f8b50ab9d97779a5b5
OS | macOS Version 14.2 (Build 23C5030f)
```

### Steps:
1. installed `1.62.33`
2. launched Brave
3. clicked on the "hamburger" menu
4. clicked on `New Private Window with Tor`
5. loaded `http://ixrdj3iwwhkuau5tby5jh3a536a2rdhpbdbu6ldhng43r47kim7a3lid.onion/referrer/onion.html`
6. compared the results of the two <iframe> tests below with those from the test plan

## Confirmed the results of the output match those provided in the test plan

Sub-resources, same-origin | Sub-resources, cross-origin <iframe>s
-----------------------------|----------------------------------------
<img width="1353" alt="Screenshot 2023-11-07 at 4 04 32 PM" src="https://github.com/brave/brave-core/assets/387249/fd85c8fe-f934-46c2-b33e-2b5aefe6ea1c"> | <img width="1348" alt="Screenshot 2023-11-07 at 4 05 28 PM" src="https://github.com/brave/brave-core/assets/387249/77ce0371-a711-4318-bc06-1f4e777f93f7">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.62.105 Chromium: 120.0.6099.71 (Official Build) beta (64-bit)
-- | --
Revision | f72c783bcd52110d026061575b4bef28ccb547f7
OS | Windows 11 Version 22H2 (Build 22621.2715)
```

### Steps:

1. installed `1.62.105`
2. launched Brave
3. clicked on the "hamburger" menu
4. clicked on `New Private Window with Tor`
5. loaded `http://ixrdj3iwwhkuau5tby5jh3a536a2rdhpbdbu6ldhng43r47kim7a3lid.onion/referrer/onion.html`
6. compared the results of the two <iframe> tests below with those from the test plan

## Confirmed the results of the output match those provided in the test plan

Sub-resources, same-origin | Sub-resources, cross-origin <iframe>s
-----------------------------|----------------------------------------
<img width="960" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/c55236ff-a9b3-40f2-8c99-e5a9d8e02b65">|<img width="958" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/d6cf67ce-a512-4f4c-9d08-b1163a75a19c">

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.62.112 Chromium: 120.0.6099.115 (Official Build) beta (64-bit) 
Revision	ae1e179b9884b2de2f4ba0bdea7da3beaad93ffa
OS	Linux
```
