### ISSUE TITLE
[hackerone] browser crash

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#32425]
reported at https://hackerone.com/reports/2117571 by [0xc4gr1](https://hackerone.com/0xc4gr1)

for STR see https://bravesoftware.slack.com/archives/C7VLGSR55/p1692649076620009?thread_ts=1692642768.785349&cid=C7VLGSR55

**Comment by kjozwiak** [comment]
@brave/qa-team please use https://github.com/brave/internal/issues/1064 for verification notes 👍

**Comment by kjozwiak** [comment]
The above requires `1.57.53` or higher for `1.57.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.57.53 Chromium: 116.0.5845.114 (Official Build) (x86_64)
-- | --
Revision | b7a154dc9e27b02528cb2cfc8010d8edf1e35571
OS | macOS Version 13.5 (Build 22G74)
```

See verification notes under https://github.com/brave/internal/issues/1064#issuecomment-1689802358

**Comment by btlechowski** [comment]
Verified with

Brave | 1.57.53 Chromium: 116.0.5845.114 (Official Build) (64-bit)
-- | --
Revision | b7a154dc9e27b02528cb2cfc8010d8edf1e35571
OS | Ubuntu 18.04 LTS

See verification notes under https://github.com/brave/internal/issues/1064#issuecomment-1690119222

**Comment by LaurenWags** [comment]
Updated to `release-notes/include` per discussion via https://bravesoftware.slack.com/archives/C7VLGSR55/p1692807268555479?thread_ts=1692642768.785349&cid=C7VLGSR55
