### ISSUE TITLE
Browser crash when clicking on `Summarize this page` and type in a query

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#32434]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.59.34 Chromium: 116.0.5845.96
Operating System: Windows NT 10.0.22621

URL (if applicable) where crash occurred: `https://www.espn.com/soccer/story/_/id/38232014/tottenham-rebuild-man-united-barcelona-montjuic-marcotti`

Can you reproduce this crash? Reproduced it twice

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Enable Brave VPN
2. Visit the above provided URL
3. Click on the Brave Leo button on sidebar
4. Click on `Summarize this page`
5. While its loading, type in a query (for example: `What sport is it about?`)
6. Browser crashes

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/67c90800-0e1b-930a-0000-000000000000
Crash ID: crash/cdc90800-0e1b-930a-0000-000000000000

cc: @rebron @iefremov

**Comment by bsclifton** [comment]
Being discussed on Slack here:
https://bravesoftware.slack.com/archives/C04KPE0BUDU/p1692661217037549

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```


```

Unable to reproduce the crash using

```
Brave | 1.59.34 Chromium: 116.0.5845.96 (Official Build) nightly (64-bit)
-- | --
Revision | 66df014750334ee8757db6c2d33d3623b3dfecaa
OS | Windows 10 Version 22H2 (Build 19045.3516)
```

![image](https://github.com/brave/brave-browser/assets/387249/86c952ae-135d-4cb9-9d1c-3f06dff393cc)
