### ISSUE TITLE
Fix Various Wallet Color Themes

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#32431]
## Description 

After the `leo` update, there are some `color` themes that are off, we need to go through and fix any regressions.

## Steps to Reproduce

   1. Change your browser theme to `Dark mode` and open the wallet
   2. The `Nav`, `Background` and `Button` colors are not correct

## Actual result:

![Screenshot 25](https://github.com/brave/brave-browser/assets/40611140/84b14348-8c6d-4ca3-87a3-c4b12553809e)

## Expected result:

![Screenshot 26](https://github.com/brave/brave-browser/assets/40611140/32772084-da1b-4bbc-a309-33e95ccef1ee)

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.59.112 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | `967f25f295938c64c24e2e6a1790470668757655`
OS | Windows 11 Version 22H2 (Build 22621.2283)

- Verified steps from [brave/brave-core#19808](https://github.com/brave/brave-core/pull/19808)
- Verified the `Portfolio`, `Linechart` and `Header` is darker than the rest on panel in dark theme
- Verified Wallet page and Panel looks correct on light/dark theme

Light | Dark
-- | --
![brave_srk6K405DH](https://github.com/brave/brave-browser/assets/17010094/2d8a8b92-d01c-4833-ba6e-58ae2c4698ae) | ![brave_5p7Iwh0eyz](https://github.com/brave/brave-browser/assets/17010094/775107aa-6ffb-4bd7-a15c-8b56e3d6cf9e)

---------------------

**Verification passed on**

Brave | 1.59.112 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | `967f25f295938c64c24e2e6a1790470668757655`
OS | Linux

- Verified steps from [brave/brave-core#19808](https://github.com/brave/brave-core/pull/19808)
- Verified the `Portfolio`, `Linechart` and `Header` is darker than the rest on panel in dark theme
- Verified Wallet page and Panel looks correct on light/dark theme

Light | Dark
-- | --
![Light](https://github.com/brave/brave-browser/assets/17010094/02e995b6-051e-42e5-9994-d5d4ebf66a8d) | ![Dark](https://github.com/brave/brave-browser/assets/17010094/5520a18f-7aac-4389-9d2b-31fea3e6de2c)

---------------------

**Verification passed on**

Brave | 1.59.112 Chromium: 118.0.5993.54 (Official Build) (arm64)
-- | --
Revision | `967f25f295938c64c24e2e6a1790470668757655`
OS | macOS Version 14.0 (Build 23A344)

- Verified steps from [brave/brave-core#19808](https://github.com/brave/brave-core/pull/19808)
- Verified the `Portfolio`, `Linechart` and `Header` is darker than the rest on panel in dark theme
- Verified Wallet page and Panel looks correct on light/dark theme

Light | Dark
-- | --
![image](https://github.com/brave/brave-browser/assets/17010094/51843f8a-1b26-4993-8b01-b6cb147b7602) | ![image](https://github.com/brave/brave-browser/assets/17010094/414f7d81-f6fc-4ca7-b4bb-5e55bf624a91)
