### ISSUE TITLE
Update Portfolio Background in Wallet Panel

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#32430]
## Description 

We need to update the `Portfolio` background in the Wallet `Panel` to be gray

![Screenshot 24](https://github.com/brave/brave-browser/assets/40611140/0193a620-9c90-444c-bae2-dacb121db7d3)

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/32431#issuecomment-1750487427
