### ISSUE TITLE
`Show sidebar on mouseover` keyboard shortcut doesn't work

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#32445]
## Description 

`Show sidebar on mouseover` keyboard shortcut doesn't work

Found while testing https://github.com/brave/brave-browser/issues/31064

## Steps to Reproduce

1. install `1.59.34`
2. launch Brave
3. open `brave://settings`
4. click `System`
5. click `Shortcuts`
6. search for `Show sidebar on mouseover`
7. click `Add`
8. add a keybinding/shortcut
9. click `Save`
10. confirmed the shortcut saved, as entered
11. press the keyboard-shortcut combination (in my case, `^ Control` + `S`

## Actual result:

Nothing seemingly happens.

## Expected result:

AFAICT, maybe it should toggle the 3-value `Show sidebar` pref state here?  Or something related?

<img width="1229" alt="Screenshot 2023-08-22 at 11 16 35 AM" src="https://github.com/brave/brave-browser/assets/387249/16589f7d-1c86-4193-b341-38543dc547e3">

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.59.34 Chromium: 116.0.5845.96 (Official Build) nightly (x86_64)
-- | --
Revision | 66df014750334ee8757db6c2d33d3623b3dfecaa
OS | macOS Version 14.0 (Build 23A5312d)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

/cc @fallaciousreasoning @rebron @MadhaviSeelam @LaurenWags @sangwoo108 @simonhong

**Comment by fallaciousreasoning** [comment]
I think I might just remove this command - it doesn't seem that useful when we already have Ctrl+B  for toggling the sidebar.

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.59.79 Chromium: 117.0.5938.48 (Official Build) beta (x86_64)
-- | --
Revision | b93ab5e51eb1080a6242fea103da637d542ca312
OS | macOS Version 14.0 (Build 23A5337a)
```

### Steps:
1. installed `1.59.79`
2. launched Brave
3. opened `brave://settings/system/shortcuts`
4. searched for `show sidebar` string (and substrings)

### Confirmed `Show sidebar on mouseover` is no longer present in `brave://settings/system/shortcuts`

<img width="1639" alt="Screenshot 2023-09-11 at 10 22 27 PM" src="https://github.com/brave/brave-browser/assets/387249/96de488d-1a61-420a-8bd8-c9be8ba8f7bf">
