### ISSUE TITLE
Fix NFTs in deposit screen

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#32446]
## Description 

We should group together NFT collections instead of showing a deposit item selection for each token ID. (for instance we should show one deposit selection item for the BAYC collection instead of one listing per Ape)

NFT icons are also not displayed correctly and should be fixed

## Steps to Reproduce

   1. Add multiple NFTs from the same collection to a wallet
   2. Open the deposit screen

## Actual result:

- A listing is shown for each item in the NFT collection (EVM only)
- The NFT image is not displayed

## Expected result:
- Only one listing should be per NFT collection (EVM only)
- The NFT image is displayed

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.59.112 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | 967f25f295938c64c24e2e6a1790470668757655
OS | Windows 11 Version 22H2 (Build 22621.2283)

- Verified steps from [brave/brave-core#19817](https://github.com/brave/brave-core/pull/19817)
- Verified NFTs show correctly in Deposit screen
![brave_wkctL7HSZI](https://github.com/brave/brave-browser/assets/17010094/60a43296-9218-41f7-8a65-3039b416daf8)
