### ISSUE TITLE
youtube publisher is shown for media publisher

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#3244]
## Description 

youtube publisher is shown instead of media publisher if you already visited that publisher in previous contribution cycle

## Steps to Reproduce

   1. clean profile
   2. visit some youtube publisher video
   3. make sure that publisher is recorded in ac table
   4. close browser
   5. open publisher db and modify reconcile stamp to something in the past
   6. open browser again and visit the same publisher (from step 2)

## Actual result:

youtube publisher is shown

## Expected result:
media publisher for that video should be shown

## Reproduces how often: 

100%

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by NejcZdovc** [comment]
@kjozwiak @rebron @bbondy would be really good to pull this one into 0.60

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.61.37 Chromium: 73.0.3683.39 (Official Build) beta (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

Used test plan from https://github.com/brave/brave-core/pull/1589
