### ISSUE TITLE
Form autofill is not cleared upon history and cash clear.

### ISSUE THREAD

**Issue by nagybarnabas** [brave/brave-browser#3245]
## Description 

Form autofill is not cleared upon history and cache clear.

## Steps to Reproduce

   1. Clear history and cache
   2. Go to a login form
   3. 

## Actual result:

Shows autofill results 

## Expected result:
Clear autofill form data

## Reproduces how often: 

always

## Brave version (brave://version info)

Latest

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Not sure

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
No
- Is the issue reproducible on the latest version of Chrome? 
Not sure

**Comment by srirambv** [comment]
Have you checked `Autofill form data` from advance options? Also please check the time line for clearing data. Default is last hour should be all time if you want to get rid of everything
![image](https://user-images.githubusercontent.com/17010094/52342483-8556b500-2a3b-11e9-82f9-c40ffc39ab9e.png)

**Comment by nagybarnabas** [comment]
Yes, checked and it was set to from beginning of time.

**Comment by rebron** [comment]
cc: @kjozwiak to reproduce

**Comment by nagybarnabas** [comment]
I think it works now

**Comment by kjozwiak** [comment]
Thanks for double checking @nagybarnabas 👍 Much appreciated.
