### ISSUE TITLE
`#brave-domain-block-1pes` regressed `query filter`

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#32462]
## Description 

Looks like the `query filter` feature has regressed when we enabled `#brave-domain-block-1pes`. Using the cases outlined via https://fmarier.github.io/brave-testing/query-filter.html under `Redirected same-site tests` & `Same-site tests`, the parameter is not being displayed in the URL nor via `Dev Tools`. @fmarier added some more context re: what he's seeing via https://bravesoftware.slack.com/archives/C6YNM6Y5S/p1692742963352529.

## Steps to Reproduce

   1. install `1.59.39 Chromium: 116.0.5845.96` (or any recent version as this has regressed a while ago)
   2. visit https://fmarier.github.io/brave-testing/query-filter.html
   3. run through any of the tests under either `Redirected same-site tests` or `Same-site tests`
   4. you'll notice that the `fbclid` is not being displayed in those cases even though the test page mentions the following:

```
In all of these cases, the fbclid parameter should be present on the landing page, but the gclid parameter should be missing in the intermediate step (client-side redirection).
```

## Actual result:

`fbclid` is not being displayed when running through the `Redirected same-site tests` or `Same-site tests` cases.

## Expected result:

`fbclid` should be visible/appearing under the URL bar for the cases under `Redirected same-site tests` or `Same-site tests`.

## Reproduces how often: 

100% reproducible using the STR/Cases mentioned above (@fmarier also reproduced)

## Brave version (brave://version info)

```
Brave | 1.59.39 Chromium: 116.0.5845.96 (Official Build) nightly (64-bit)
-- | --
Revision | 3fafa12c56ece8921f90593a446cde2c1867d02f
OS | Windows 11 Version 22H2 (Build 22621.2134)
```

```
Brave | 1.57.49 Chromium: 116.0.5845.96 (Official Build) (64-bit)
-- | --
Revision | 8d78ad7e96630cfcd3ab4165cf0fd421d3c4f068
OS | Windows 11 Version 22H2 (Build 22621.2134)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by fmarier** [comment]
According to @goodov , the reason for this is that with 1pes enabled, all requests go through adblocker, which since brave/brave-core#15943 also can remove URL params.

Since the `removeparam` rule is different from our [query string filtering policy](https://github.com/brave/brave-browser/wiki/Query-String-Filter), we need to ensure that **these rules are ignored** unless they come from a user-added filterlist.

**Comment by fmarier** [comment]
We do have an issue open to move the query filter rules to a proper list (https://github.com/brave/brave-browser/issues/10188) and ideally to reuse the implementation in our adblocker, but that is not currently ready due to the behavioral differences.

**Comment by kjozwiak** [comment]
The above requires `1.58.121` or higher for `1.58.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.58.121 Chromium: 117.0.5938.48 (Official Build) (x86_64)
-- | --
Revision | d80a8110b88df6ae5073d8420fada4168542786f
OS | macOS Version 13.5.2 (Build 22G91)
```
