### ISSUE TITLE
Why doesn't Brave have WidevineCdm component?

### ISSUE THREAD

**Issue by SilencerWeb** [brave/brave-browser#3246]
## Description 
I cannot watch movies on Netflix because Brave doesn't have WidevineCdm component in brave://components (also lol, try to open this link and then copy it from the address bar, it will be copied as _chrome_://components).

![image](https://user-images.githubusercontent.com/20713191/52341179-c1861780-2a33-11e9-92b7-68e7f5396686.png)

## Steps to Reproduce
   1.  Open netflix.com
   2. Open any movie.
   3. That's all

## Brave version (brave://version info)
0.59.35 Chromium: 72.0.3626.81 (Official Build) (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? I don't know

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields?  No
- Is the issue reproducible on the latest version of Chrome? I don't know

**Comment by srirambv** [comment]
If you are on Linux then its not available for that platform yet. If you are on Windows/macOS you should get a prompt on URL bar to run Widevine.

**Comment by SilencerWeb** [comment]
@srirambv I'm on macOS and there is no such component

**Comment by srirambv** [comment]
@SilencerWeb  If you are on mac you should be able to see the Widevine prompt show up on URL bar. If you still don't see it I'd suggest clearing browsing data and select all checkboxes and select `All time` and then close and reopen the browser and visit Netflix you should be able to see the Widevine prompt.

**Comment by SilencerWeb** [comment]
@srirambv could you, please, clarify about what checkboxes you are talking about?

**Comment by srirambv** [comment]
You need to clear the media license and select All Time from the drop down at the top. 
![image](https://user-images.githubusercontent.com/17010094/52407230-a8459f80-2af5-11e9-9526-c3a8ddc3267e.png)

**Comment by bsclifton** [comment]
@SilencerWeb it's REALLY easy to miss- there's a puzzle piece icon in the URL bar (ALL the way to the right). If you click that, it shows an opt-in modal for Widevine

We DO have an issue captured (because it's very well hidden) to make it more discoverable and obvious. You can subscribe to the issue and give it a thumbs up (there are also pics of the puzzle icon, in case you wanted to see what you SHOULD be seeing):
https://github.com/brave/brave-browser/issues/1940

Once Widevine is installed, you can confirm it shows up in chrome://components

**Comment by SilencerWeb** [comment]
@bsclifton thank you!

**Comment by clayms** [comment]
Same error on Windows 10 computer when going to Amazon Prime.

There is no "puzzle piece" icon in the URL bar.  
Clearing all browser data for all time, then reloading the web site does not change anything. 

The "puzzle piece" icon on the far right outside of the URL input, is the 'Extensions' menu button.

![image](https://user-images.githubusercontent.com/12793783/131575478-517a7fb1-ac2b-45f3-b1dc-db7c90e4bd18.png)

**Comment by simonhong** [comment]
@clayms How about checking `Widevine` toggle option from settings page?
![image](https://user-images.githubusercontent.com/6786187/131629631-a00c0000-0469-49aa-a535-a8ce62abe8aa.png)

**Comment by clayms** [comment]
@simonhong 
That worked, thanks.
