### ISSUE TITLE
Add mojo method to return swap protocol fees

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#32464]
- 0x recently started adding a 15 bps protocol fee to each trade for select tokens (ref: https://0x.org/pricing)
- Jupiter Swap API v6 will include a 20% rev share (ref: https://docs.jup.ag/docs/v6-beta/adding-fees)

Implement a backend method that computes the appropriate protocol fee to be displayed to users.

**Note:** The 0x protocol fee may be waived for some tokens, which can only be inferred from the quote response, i.e., cannot be known in advance.

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.59.93 x64 build
- Verified steps from [brave/brave-core#19834](https://github.com/brave/brave-core/pull/19834)
- Verified waived off fee is shown on some assets
- Encountered [#33256](https://github.com/brave/brave-browser/issues/33256)

https://github.com/brave/brave-browser/assets/17010094/65f94db2-a34b-4e15-a6d2-23e32e65a712

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.59.100 Chromium: 117.0.5938.92 (Official Build) beta (64-bit)
-- | --
Revision | 3243fffc43431ab8677e8139859670b4cd2df843
OS | Windows 11 Version 22H2 (Build 22621.2283)

- Verified steps from [brave/brave-core#19834](https://github.com/brave/brave-core/pull/19834)
- Verified d waived off fee is shown on some assets

https://github.com/brave/brave-browser/assets/17010094/30b6f75c-5115-4341-aa96-0889856a9528
