### ISSUE TITLE
Unable to Import Wallet with PrivateKey in Panel

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#32478]
## Description 

We are currently unable to `import` a wallet with a `PrivateKey` in the Wallet `Panel`.

https://github.com/brave/brave-browser/assets/40611140/0cdd38da-b523-4fbd-a6dc-33f669621cb5

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.59.115 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | `82b05012fc6b5ab8535cf283db6856ad5eedd7eb`
OS | Windows 11 Version 22H2 (Build 22621.2283)

- Verified steps from [brave/brave-core#19845](https://github.com/brave/brave-core/pull/19845)
- Verified importing account from panel works as expected

https://github.com/brave/brave-browser/assets/17010094/7b9c7695-d875-43ce-ac1b-a51d880e47b1

--------------------

**Verification passed on**

Brave | 1.59.115 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | `82b05012fc6b5ab8535cf283db6856ad5eedd7eb`
OS | Linux

- Verified steps from [brave/brave-core#19845](https://github.com/brave/brave-core/pull/19845)
- Verified importing account from panel works as expected

https://github.com/brave/brave-browser/assets/17010094/6ec857c5-ee13-4943-b358-3b977f2dcbf3

---------------------

**Verification passed on**

Brave | 1.59.115 Chromium: 118.0.5993.54 (Official Build) (arm64)
-- | --
Revision | `82b05012fc6b5ab8535cf283db6856ad5eedd7eb`
OS | macOS Version 14.0 (Build 23A344)

- Verified steps from [brave/brave-core#19845](https://github.com/brave/brave-core/pull/19845)
- Verified importing account from panel works as expected

https://github.com/brave/brave-browser/assets/17010094/27f60555-8d52-477b-85f2-dd9ca5481f89
