### ISSUE TITLE
"userdrain" tooltip cuts off the NTP screen in the default display settings

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#32470]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/32036
"userdrain" tooltip cuts off the NTP screen in the default display settings
## Steps to Reproduce

   1. Create profile on old version of Brave `1.45.100`
   2. Send yourself some vBAT
   3. Upgrade to a more recent version so that you are in the grandfathered-unverified state
   4. Connect to ZebPay
   5. Check the ZebPay balance is shown in the wallet
   6. Make sure “userdrain tooltip” (yellow question mark) appears on NTP widget, Rewards panel, and brave://rewards settings page. 
   7. "userdrain" tooltip cuts off the NTP screen in the default display settings
  
## Actual result:

"userdrain" tooltip cuts off the NTP screen in the default display settings
![image](https://github.com/brave/brave-browser/assets/38657976/b07b4e1c-f787-4085-86bd-e5a3e270d8ad)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.58.97 Chromium: 116.0.5845.96 (Official Build) beta (64-bit)
-- | --
Revision | c983323d5ff7738a3c8d3bf491a7241c24b4d65a
OS | Windows 10 Version 22H2 (Build 19045.3324)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @Miyayes @szilardszaloki

**Comment by kjozwiak** [comment]
The above requires `1.58.107` or higher for `1.58.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.58.109 Chromium: 116.0.5845.163 (Official Build) beta (x86_64)
-- | --
Revision | a4ad1fcdb550daf076384dbb280ae944274b3d35
OS | macOS Version 13.5.1 (Build 22G90)
```
