### ISSUE TITLE
Leo - Returning Brave-related outputs on unrelated inputs, then errors on repeat attempts (YT video)

### ISSUE THREAD

**Issue by lukemulks** [brave/brave-browser#32479]
## Description 

I've tested out two different paths here, and have run into similar results. 

1 path, asking Leo to summarize the video in-page, providing a video title in the prompt for reference. 

1 path, asking Leo to summarize the video from a URL provided in the input prompt. 

In both cases, the outputs were very similar, both unrelated to the video, and both related to Brave (as in, output refers to content related to the Brave browser). 

Example, notice the URL in Leo input matches the URL in the URL bar, and the output is unrelated. 

![brave-leo-feedback-08232023-allin](https://github.com/brave/brave-browser/assets/8979240/7a5f2ecc-67ea-40ab-a69e-539b1f1eb41d)

## Steps to Reproduce

   1.  Navigate to https://www.youtube.com/watch?v=dlzobkV_CgU
   2.  Open Leo in Sidebar
   3.  Input request to Leo to "summarize https://www.youtube.com/watch?v=dlzobkV_CgU"
   4. Observe output
   5. Open new tab, and repeat steps 1-4; notice that the Summarize video button displays, but in my case, there was an error when I clicked to summarize the content.
   6. When I refresh this new tab, I reproduce the summarization error 100% of the time.

## Expected result:
Leo should summarize the content in-page for the URL, and not for unrelated content specific to Brave. 

## Reproduces how often: 

When I attempted to reproduce the result from a new window, following the exact same STR above, I observed something different. 

The expected request to summarize the video content displayed in Leo. This was nice to see. 

When I clicked the button to summarize the video, there was an error 
![brave-leo-feedback-08232023-allin-error](https://github.com/brave/brave-browser/assets/8979240/c4219159-d739-4bc7-b82b-cd73d238613d)

I'm not really sure how to debug Leo to catch any console log type errors or messages (I admittedly tried playing with different levels via Dev Tools, but couldn't locate where Leo would be) 

## Brave version (brave://version info)

1.59.38 Chromium: 116.0.5845.96 (Official Build) nightly (64-bit) 
Revision | 1011f9e73a7e7bbdb11a53b1bb10f7d21db78c22
OS | Windows 11 Version 22H2 (Build 22621.2134)

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by lukemulks** [comment]
@rebron I assigned you on this, as I suspect you're likely the right person on triage, but LMK if I should be assigning others or if there's other process points that are more preferable! :-)

**Comment by petemill** [comment]
We could detect if the user input has a url. If so, a note could be attached to the message, something like "Note: Leo looks at the page you're on but does not fetch other content from the internet. Response may be inaccurate." What do you think @aguscruiz @mattmcalister ?
