### ISSUE TITLE
Move importAccountFromJson to Wallet Actions

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#32487]
## Description 

We need to move the `importAccountFromJson` action from the `Page` to `Wallet` actions to allow using this action in both the `Page` and `Panel`

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.59.112 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | `967f25f295938c64c24e2e6a1790470668757655`
OS | Windows 11 Version 22H2 (Build 22621.2283)

- Verified steps from [brave/brave-core#19849](https://github.com/brave/brave-core/pull/19849)
- Verified able to Import account from JSON file

https://github.com/brave/brave-browser/assets/17010094/8a2f661a-00ef-4589-bf1a-635e0cc0fd03

---------------------

**Verification passed on**

Brave | 1.59.112 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | `967f25f295938c64c24e2e6a1790470668757655`
OS | Linux

- Verified steps from [brave/brave-core#19849](https://github.com/brave/brave-core/pull/19849)
- Verified able to Import account from JSON file

https://github.com/brave/brave-browser/assets/17010094/5effe211-c282-43bd-930d-361a85d40061

---------------------

**Verification passed on**

Brave | 1.59.112 Chromium: 118.0.5993.54 (Official Build) (arm64)
-- | --
Revision | `967f25f295938c64c24e2e6a1790470668757655`
OS | macOS Version 14.0 (Build 23A344)

- Verified steps from [brave/brave-core#19849](https://github.com/brave/brave-core/pull/19849)
- Verified able to Import account from JSON file

https://github.com/brave/brave-browser/assets/17010094/1a7b677d-587a-414e-a96a-147dfc23e42d
