### ISSUE TITLE
Add clean copy service for iOS

### ISSUE THREAD

**Issue by cuba** [brave/brave-browser#32484]
We need move several components and expose them to iOS for the clean copy feature here:
https://github.com/brave/brave-ios/issues/6179

It is also a base requirement for the following features:
* https://github.com/brave/brave-ios/issues/7582
* https://github.com/brave/brave-ios/issues/6942

**Comment by kjozwiak** [comment]
Closing and moving into the `1.59.x` milestone as https://github.com/brave/brave-core/pull/19079 was merged into `master` when it was on `1.59.x`. Will be uplifted into `1.58.x` via https://github.com/brave/brave-core/pull/20017.
