### ISSUE TITLE
Playlist: use button elements for buttons

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#32486]
In the playlist sidebar, the buttons are not showing as interactive elements. This makes them impossible to use via non-mouse users, e.g. keyboard or screen readers. Using a <button> element gets those features (such as tabindex and role) for free. Additionally, we're not getting any styling for hover and click. Please use Leo's Button component so we get all those things. Probably the [PlainFaint variant](https://leo.bravesoftware.com/?path=/story/button--plain-faint) for icon buttons.

**Comment by sangwoo108** [comment]
I think I remember @fallaciousreasoning suggested that before, but the button couldn't have custom size back then. If it still doesn't have that, let me solve that first when I start polishing. Recently, icons are changed so need to bump up leo, so it could be good chance to improve leo compoents!

**Comment by fallaciousreasoning** [comment]
Looking at it, I think we just want to be able to remove the padding - is that right @sangwoo?
