### ISSUE TITLE
Allow syncing of Saved Group Tabs (as available in latest chromium)

### ISSUE THREAD

**Issue by zbugrkx** [brave/brave-browser#32480]
## Description 
<--As the title says, the latest chromium builds now allows to sync saved group tabs. Having this part of the sync chain would be very important for us heavy users of saved groups tabs accross devices-->

**Comment by simplerethink** [comment]
Please add Group Tabs to the sync chain. It's very annoying to have tab sync, but then lose all your Groups.

**Comment by AdnanHodzic** [comment]
Why is this issue closed? Brave still doesn't have an option to sync tab groups between devices.
