### ISSUE TITLE
Implement unified adblock list catalog

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#32482]
The adblock lists we use in Brave are organized [here](https://github.com/brave/adblock-resources/tree/master/filter_lists). We've served `regional.json` directly from the component updater for a fairly long time. More recently, the format of `default.json` was updated to match `regional.json`, allowing them to share codepaths.

The final step of this approach will be to merge the two catalogs together. We can use new fields in each entry to specify additional information about the lists. To begin with, that information is:
- should they be displayed in `brave://settings/shields/filters` as regional lists
- should they be enabled by default
- should first-party heuristics be applied to rules from the list

The benefit of this change will be the ability to add the following as well:
- what scriptlet permissions should be granted to rules from the list

### See also

https://github.com/brave/adblock-resources/pull/130
https://github.com/brave/brave-core-crx-packager/pull/687

**Comment by LaurenWags** [comment]
Labeling as `QA/Blocked` for now, as it looks like this will be reverted via https://github.com/brave/brave-core/pull/20459 which has been requested for uplift to 1.60.x.

**Comment by kjozwiak** [comment]
Labelling as `QA/No` and removing `QA/Blocked` now that the above has been reverted from `master` & `1.60.x` via https://github.com/brave/brave-core/pull/20442 & https://github.com/brave/brave-core/pull/20459.
