### ISSUE TITLE
Add AT Marketing tracking params to query filter

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#32488]
Some of the parameters listed in https://developers.atinternet-solutions.com/as2-tagging-en/javascript-en/campaigns-javascript-en/marketing-campaigns-v2/ look like they are identifying specific users.

**Comment by fmarier** [comment]
These two look like they should be blocked:
- `at_recipient_id` identifies a unique email address
- `at_recipient_list` identifies an email list, which could be a list of 1

**Comment by fmarier** [comment]
Sample URLs:
- https://www.france24.com/en/asia-pacific/20211117-india-shuts-down-delhi-schools-due-to-dangerous-levels-of-air-pollution?at_medium=email&at_emailtype=retention&at_campaign=Newsletter&at_creation=Quotidienne_F24&at_send_date=20211117&at_link=contenu&at_recipient_id=541029&actId=ebwp0YMB8s0TtZln5k-2gdUcvuQDVN7aqMHi_sC2WSqwQiPn7awyV_Nnh8c4m5j2&actCampaignType=CAMPAIGN_MAIL&actSource=508586
- https://www.fun-mooc.fr/fr/cours/violences-sexuelles-et-sexistes-au-travail-prevenir-et-reagir/?at_medium=email&at_emailtype=retention&at_campaign=newsgen&at_creation=lille&at_send_date=20210430&at_link=violences_sexuelles_et_sexistes_au_travail_prevenir_et_reagir&at_recipient_list=1

**Comment by LaurenWags** [comment]
Verified with

```
Brave | 1.60.81 Chromium: 118.0.5993.54 (Official Build) beta (x86_64)
-- | --
Revision | 1efb3f333eb41cc34af46ca31fb33c30e0afbfae
OS | macOS Version 13.6 (Build 22G120)
```

Reproduced using test plan from https://github.com/brave/brave-core/pull/20254#issue-1908139194 and 1.58.x
Verified test plan from https://github.com/brave/brave-core/pull/20254#issue-1908139194 and 1.60.x

1.58.x | 1.60.x
--- | ---
<img width="1197" alt="1 58" src="https://github.com/brave/brave-browser/assets/28145373/7cfefa28-4152-405f-909e-defa51a7c6b4"> | <img width="1197" alt="1 60" src="https://github.com/brave/brave-browser/assets/28145373/771b6355-06e1-44c8-ad9e-c4d462784ee1">

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 [panther_beta-user 14 U1B1.230908.003 release-keys]
Brave build: 1.60.96 
Chromium: 118.0.5993.88 (Official Build) beta (64-bit) 
Revision: b4c059ad1d32d6e0cd1466123f03ccb97b3cf858
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-core/pull/20254#issue-1908139194

**ACTUAL RESULTS:**
- Verified that the URL search bar contains only https://brave.com/
- Verified the same by copy & paste the link and by opening the link from another app

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/a5eccb5e-b2cc-455c-b1eb-b73a124e0a61) | ![2](https://github.com/brave/brave-browser/assets/128532965/9924f305-c35b-4874-9c35-088a47c4f26c) |

https://github.com/brave/brave-browser/assets/128532965/a81d87c0-be5f-4001-8d16-2c3f0bcdfeb0
