### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by color57465** [brave/brave-browser#32493]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.57.53 Chromium: 116.0.5845.114
Operating System: Windows NT 10.0.19042

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Go to mail.google.com
2. Open up any email
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/70400100-fa56-9c0a-0000-000000000000

**Comment by iefremov** [comment]
stale
