### ISSUE TITLE
Typing a question causes the response to start over

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#32491]
## Description 

Typing a question causes the response to start over

## Steps to Reproduce

   1. Ask a question to the AI assistant so that it gives a big response
   2. While its response is being printed ask another question or give any random input
   3. The typed response starts flashing and starts over from beginning 

## Actual result:

Typing a question causes the response to start over

## Expected result:
Should either disable input when response is being typed in or answer the new question 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

 
Brave | 1.59.41 Chromium: 116.0.5845.96 (Official Build) nightly (64-bit)
-- | --
Revision | f78ce7ef2bd29f512593c2c2e9a4cdc551f1c38b
OS | Windows 11 Version 22H2 (Build 22621.2134)
 

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @rebron @nullhook

**Comment by nullhook** [comment]
This should be resolved here: https://github.com/brave/brave-core/pull/19804

**Comment by nullhook** [comment]
On the updated UI the user could never send a query while the assistant is generating so this issue is obsolete. Could we close this?

**Comment by nullhook** [comment]
Closing due to obsoleteness

**Comment by stephendonner** [comment]
@nullhook this needs a milestone; please set it appropriately.  Thanks.
