### ISSUE TITLE
Align Group Description to the Left

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#32504]
## Description 

We need to align the `Asset Group` description to the `left` for panel views

## Steps to Reproduce

   1. Open the `Panel` and group your `Portfolio` by `Networks`
   2. Long `Network` names are aligned `center`

## Actual result:

![Screenshot 41](https://github.com/brave/brave-browser/assets/40611140/a6ea3f30-324a-4775-98a9-4db9cdf2741e)

## Expected result:
Should be aligned left

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.59.112 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | `967f25f295938c64c24e2e6a1790470668757655`
OS | Windows 11 Version 22H2 (Build 22621.2283)

- Verified steps from [brave/brave-core#19867](https://github.com/brave/brave-core/pull/19867)
- Verified Network name is left aligned when grouped by network
![brave_UPM6MW55VU](https://github.com/brave/brave-browser/assets/17010094/7d99f545-6731-4ff5-a855-57083e8d7c68)


---------------------

**Verification passed on**

Brave | 1.59.112 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | `967f25f295938c64c24e2e6a1790470668757655`
OS | Linux

- Verified steps from [brave/brave-core#19867](https://github.com/brave/brave-core/pull/19867)
- Verified Network name is left aligned when grouped by network
![Linux](https://github.com/brave/brave-browser/assets/17010094/608c7599-3c32-4ed9-a8bf-52caded42b8e)

---------------------

**Verification passed on**

Brave | 1.59.112 Chromium: 118.0.5993.54 (Official Build) (arm64)
-- | --
Revision | `967f25f295938c64c24e2e6a1790470668757655`
OS | macOS Version 14.0 (Build 23A344)

- Verified steps from [brave/brave-core#19867](https://github.com/brave/brave-core/pull/19867)
- Verified Network name is left aligned when grouped by network
