### ISSUE TITLE
opening invalid webui URL in private window shouldn't open a regular window

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#32503]
details: https://github.com/brave/internal/issues/1065

**Comment by LaurenWags** [comment]
@brave/qa-team please use above linked internal issue for where to put verification notes.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.60.81 Chromium: 118.0.5993.54 (Official Build) beta (x86_64)
-- | --
Revision | 1efb3f333eb41cc34af46ca31fb33c30e0afbfae
OS | macOS Version 13.6 (Build 22G120)
```

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.60.88 Chromium: 118.0.5993.70 (Official Build) beta (64-bit)
-- | --
Revision | ff9150ac5dd9934a7f431ddf478ad3e45ae68546
OS | Windows 11 Version 22H2 (Build 22621.2428)
```
Verification notes can be found under https://github.com/brave/internal/issues/1065#issuecomment-1760347348

**Comment by btlechowski** [comment]
Verified with

Brave | 1.60.102 Chromium: 118.0.5993.96 (Official Build) beta (64-bit)
-- | --
Revision | 3598a9fc6b7752181feb25caa131bc386d6d054c
OS | Linux


Verified in https://github.com/brave/internal/issues/1065#issuecomment-1786407097
