### ISSUE TITLE
Add type-safety to placeholder-wrapped icons

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#32507]
## Description 

We currently are not showing the correct component props when wrapping an icon component with a placeholder

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.59.112 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | 967f25f295938c64c24e2e6a1790470668757655
OS | Windows 11 Version 22H2 (Build 22621.2283)

- Verified steps from [v](https://github.com/brave/brave-core/pull/19870)
- Verified assets and network load without any issues
