### ISSUE TITLE
upgrade to 0.61.7 or later will show blank auto contribute table - follow up to 2110

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#3250]
## Description 
Once you upgrade to 0.61.7 or later on Dev channel, your auto contribute table will show as blank. Per discussion with @NejcZdovc we need to update existing entries in the table to have a visit number.

## Steps to Reproduce

   1. Create a clean profile on Dev channel using 0.61.6 or earlier.
   2. Enable Rewards
   3. Visit some sites (I had a mix of verified and non-verified sites).
   4. Visit brave://settings/help to trigger update. 
   5. Relaunch once update is complete.

## Actual result:
A-C table is blank.

## Expected result:
A-C table should not be blank.

## Reproduces how often: 
easily. Reproduced by @NejcZdovc and @kjozwiak 

## Brave version (brave://version info)

Brave | 0.61.10 Chromium: 72.0.3626.81 (Official Build) dev(64-bit)
-- | --
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS | Mac OS X

Also occurs if you update to 0.61.7 on Dev.

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Dev 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
Here is a macOS profile created using 0.61.6 that can be used to reproduce the issue:
[Brave-Browser-Dev-upgradeandACisblank.zip](https://github.com/brave/brave-browser/files/2837850/Brave-Browser-Dev-upgradeandACisblank.zip)

**Comment by GeetaSarvadnya** [comment]
Reproducible on Windows 10 x64. Upgraded from `0.61.6` to `0.61.10`


Brave | 0.61.10 Chromium: 72.0.3626.81 (Official Build) dev (64-bit)
-- | --
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS | Windows

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.61.38 Chromium: 73.0.3683.39 (Official Build) beta (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

Used test plan from the description. Renamed the dev profile to beta.
Made sure that `visits` in `publisher_info_db` was `0` before upgrade and after upgrade it was `1`.
