### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by serjon** [brave/brave-browser#32519]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.57.53 Chromium: 116.0.5845.114
Operating System: Mac OS X 13.5.0

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1.
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/20ef0200-fa56-9c0a-0000-000000000000

**Comment by serjon** [comment]
Hi Devs, when I open devtools in brave CPU it grows a lot and after a few seconds devtools disappears, every time I open it it closes after a few seconds. Thx

**Comment by dimfeld** [comment]
I encountered this as well and it turned out to be https://bugs.chromium.org/p/chromium/issues/detail?id=1473992#c13. There's a workaround in comment 13

**Comment by iefremov** [comment]
stale
