### ISSUE TITLE
Tor button is consistently displayed in address bar 

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#32513]
## Description 

Starting with ~1.59.44 the Tor button is showing permanently in the address bar. The Tor button should only appear when a .onion url is available like on brave.com or nytimes.com

<img width="170" alt="Screenshot 2023-08-24 at 7 46 34 PM" src="https://github.com/brave/brave-browser/assets/5951041/7cb31939-c73a-415e-affd-2121a8f2216f">

## Steps to Reproduce

   1. Use 1.59.44 and higher
   2. Visit a page that have an .onion address (brave.com)
   3. Visit a page that does not have an .onion address
   4. Notice that the Tor button appears in the address bar
   5. Clicking on this icon will open tor window with the address from 2.

## Expected result:
See description

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by rebron** [comment]
cc: @boocmp @fmarier

**Comment by rebron** [comment]
I toggled Tor on and off and can no longer reproduce.

**Comment by boocmp** [comment]
I've updated the reproduce steps

**Comment by boocmp** [comment]
The problem in the onion_location_view.cc,
![image](https://github.com/brave/brave-browser/assets/73575789/4539fd44-0a56-43ae-b764-ad2611a06d15)
once the button is shown, it will have no chance of being hidden.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.59.86 Chromium: 117.0.5938.62 (Official Build) beta (64-bit)
-- | --
Revision | 3c4c1c3b2eef0fcbe8485c67e1df504942deadca
OS | Windows 11 Version 22H2 (Build 22621.2283)
```

Reproduced the issue in 1.59.44 using STR from https://github.com/brave/brave-browser/issues/32513#issue-1866205241

example | example 
---- | ----
<img width="953" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/3b21a1bf-298a-459b-b435-5a46299d9134">|<img width="953" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/083881fd-1ae0-45ec-96c4-81169a260768">


Steps: 

1. Installed 1.59.86
2. launched Brave
3. visited a page that have an `.onion` address (brave.com)
4. verified `Tor button` is shown in the URL bar as expected
5. visited a page that does not have an .onion address (cnn.com)

### Confirmed `Tor button` is not shown in the URL bar 

 step 4 | step 5
---- | -----
<img width="955" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/c0308e5b-8540-45f0-9842-bc24d26c0567">|<img width="956" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/9f7ddee5-808d-43c9-90aa-f401c9b5ef0d">
