### ISSUE TITLE
Hide `ChromeRefresh2023` feature from brave://flags

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#32512]
## Description 

It could cause startup/runtime crash when `ChromeRefresh2023` feature is enabled via brave://flags
Block that flag until we handle it properly

## Steps to Reproduce

   1. Launch Brave nightly(1.59.x)
   2. Enable `ChromeRefresh2023` via brave://flags
   3. Relaunch

## Actual result:

Crashed while startup

## Expected result:
Not crash

## Version/Channel Information:

- Can you reproduce this issue with the current release?  No
- Can you reproduce this issue with the beta channel?  No
- Can you reproduce this issue with the nightly channel? Yes(1.59.x)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
@simonhong is this specific to a certain OS? Using macOS I tried enabling each of the below flags in 1.58.x (version before this fix) one by one to get a crash and didn't have any luck. So I enabled them all at once, and still no crash. I also tried this with `1.59.46` on Nightly which is another version before this fix and had the same results. Am I missing something here?


1.58.131 | 1.59.46
--- | ---
<img width="1191" alt="1 58 131" src="https://github.com/brave/brave-browser/assets/28145373/35fd2b92-32bd-4825-a58a-bf570950f489"> | <img width="1191" alt="1 59 46" src="https://github.com/brave/brave-browser/assets/28145373/7e37ac60-5145-4a23-b1bc-4e301433545c">

**Comment by simonhong** [comment]
Hmm, interesting. IIRC, it was crashed on all platforms when I enabled `Chrome Refresh 2023` feature.
Anyway, I think we should hide this feature as we don't support that feature properly.

**Comment by LaurenWags** [comment]
@simonhong so since I can't reproduce the crash, I can just confirm that all 3 of the flags from my screenshots in https://github.com/brave/brave-browser/issues/32512#issuecomment-1731977938 are hidden from brave://flags? That is sufficient testing for this issue?

**Comment by stephendonner** [comment]
> Hmm, interesting. IIRC, it was crashed on all platforms when I enabled `Chrome Refresh 2023` feature. Anyway, I think we should hide this feature as we don't support that feature properly.

Wasn't it https://github.com/brave/brave-browser/issues/30499?

**Comment by simonhong** [comment]
@LaurenWags Only `Chrome Refresh 2023` is hidden. As I wrote in DM, user could set other flags as enabled but it's no-op as `Chrome Refresh 2023` is disabled.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.59.100 Chromium: 117.0.5938.92 (Official Build) beta (arm64) 
Revision	3243fffc43431ab8677e8139859670b4cd2df843
OS	macOS Version 14.0 (Build 23A344)
```
