### ISSUE TITLE
Fallback to IKEv2 if wireguard service is not registered

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#32523]
## Description 

Users may delete service manually and we have to fallback in this case.

## Steps to Reproduce

   1. Enable Wireguard vpn 
   2. Run `sc.exe delete BraveDevelopmentVpnWireguardService` or `sc.exe delete BraveNightlyVpnWireguardService` for nightly

## Actual result:

- Try to connect to vpn

## Expected result:

- Browser is asking to fallback to IKEv2

## Reproduces how often: 

100% 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by MadhaviSeelam** [comment]
Verification ` In progress` using
```
Brave | 1.59.94 Chromium: 117.0.5938.88 (Official Build) beta (64-bit)
-- | --
Revision | 2dca22d0a20096c32df5af4c88700a0b31acb55c
OS | Windows 11 Version 22H2 (Build 22621.2283)
```

1. Install 1.59.94
2. launch Brave
3. confirmed brave://settings/system shows Wireguard VPN is enabled by default
4. purchased, configured and connected to Brave VPN
5. disconnected VPN in the VPN panel
6. opened cmd line prompt as an administrator and ran `sc.exe delete BraveBetaVpnWireguardService`
7. enabled VPN via Brave VPN panel
8. `Fallback to IKEv2` window is not shown
9. instead `Can't connect to the server` dialog is shown

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using
