### ISSUE TITLE
Email address should be shown in the Brave VPN subscription page in staging

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#32526]
## Description 

Email address is not populated in the Brave VPN subscription page in Staging (account.bravesoftware.com).  However, it is correctly shown in Production (account.brave.com)

## Steps to Reproduce

   1. Install 1.58.100
   2. launch Brave
   3. purchase, configure VPN via account.bravesoftware.com
   4. verify the subscription page

## Actual result:

Email address is not shown in staging (account.bravesoftware.com)
![image](https://github.com/brave/brave-browser/assets/98358127/22b77d36-7a5f-476b-b6fb-2d8f9652c164)

## Expected result:
(account.brave.com)
![image](https://github.com/brave/brave-browser/assets/98358127/8c2d1906-f9ad-4d8e-a7e9-51211ece1350)

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.58.100 Chromium: 116.0.5845.114 (Official Build) beta (64-bit)
-- | --
Revision | a8c0058265009a1858c4502b9ba413671fbb61e1
OS | Windows 11 Version 22H2 (Build 22621.2134)
```
## Version/Channel Information:

- Can you reproduce this issue with the current release? N/a
- Can you reproduce this issue with the beta channel? N/a
- Can you reproduce this issue with the nightly channel? N/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
@clifton @AlanBreck @johnhalbert

**Comment by johnhalbert** [comment]
PR to address: https://github.com/brave-intl/subscriptions/pull/434

**Comment by bsclifton** [comment]
Closing - this should have been resolved with https://github.com/brave-intl/subscriptions/pull/434
