### ISSUE TITLE
Go to the previous page with backspace

### ISSUE THREAD

**Issue by leobel96** [brave/brave-browser#3252]
I don't know if this is a feature request or an issue but I've found the lack of a useful feature: a shortcut to go back to the previous page without having to click on the left arrow on the top bar. In Firefox, you can use backspace to accomplish it.

**Comment by srirambv** [comment]
Based on https://github.com/brave/browser-laptop/issues/6156#issuecomment-408153493
> I believe the long term fix for this will be installing an extension ([like this one](https://chrome.google.com/webstore/detail/backspace-to-go-back/nlffgllnjjkheddehpolbanogdeaogbc)) 

Going to close this as wontfix as this can be achieved with an extension. 

cc: @bsclifton to confirm and reopen issue if required

**Comment by leobel96** [comment]
Ok, thank you.

**Comment by leobel96** [comment]
I've discovered now that it can be accomplished with ALT + LeftArrow !!

**Comment by bsclifton** [comment]
Yup- extension would be the way to go. Although, I prefer the ALT + LeftArrow (or Cmd + LeftArrow on macOS) 😄

**Comment by jexxadox** [comment]
so just fyi. i tried the TWO extensions i found and neither worked. whats is agravating me the most is before i synced on this fresh install it WORKED, and i didn't have any extensions installed. i have linux ubuntu based os.

can i just add a keyboard shortcut? cuz im not pressing 2 keys when i can quickly hit 1 larger one faster.
