### ISSUE TITLE
IPFS logo on NFT pinning banner is not visible on light theme

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#32522]
## Description 

IPFS logo on NFT pinning banner is not visible on light theme

## Steps to Reproduce

   1. Add an NFT to wallet that cannot be pinned
   2. Click the IPFS banner and click on get started with ipfs pinning in the interstitial page
   3. NFT banner shows up for a brief moment but the IPFS logo isn't clearly visible

## Actual result:

![image](https://github.com/brave/brave-browser/assets/17010094/10881965-639d-49bd-b409-254dddfe4007)

## Expected result:
![image](https://github.com/brave/brave-browser/assets/17010094/86106df9-ef98-462c-b593-fa6381efc13f)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.58.100 Chromium: 116.0.5845.114 (Official Build) beta (64-bit)
-- | --
Revision | a8c0058265009a1858c4502b9ba413671fbb61e1
OS | Windows 11 Version 22H2 (Build 22621.2134)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @muliswilliam @Douglashdaniel

**Comment by josheleonard** [comment]
Closing. IPFS pinning no longer supported as of: https://github.com/brave/brave-core/pull/23808
