### ISSUE TITLE
Expand to Desktop View to Connect Hardware Wallet in Panel

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#32524]
## Description 

Until https://github.com/brave/brave-browser/issues/31837 is implemented, we need to expand to the `Desktop View` to `Connect Hardware Wallets` from the `Panel`

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.59.112 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | `967f25f295938c64c24e2e6a1790470668757655`
OS | Windows 11 Version 22H2 (Build 22621.2283)

- Verified steps from [brave/brave-core#19882](https://github.com/brave/brave-core/pull/19882)
- Verified Connect Hardware Wallet from panel opens expanded desktop view

https://github.com/brave/brave-browser/assets/17010094/7238be2c-b8b7-49ba-9dc2-b2239f2e087a

---------------------

**Verification passed on**

Brave | 1.59.112 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | `967f25f295938c64c24e2e6a1790470668757655`
OS | Linux

- Verified steps from [brave/brave-core#19882](https://github.com/brave/brave-core/pull/19882)
- Verified Connect Hardware Wallet from panel opens expanded desktop view

https://github.com/brave/brave-browser/assets/17010094/d4d75a92-551e-400e-a76e-19d7a461c94a

---------------------

**Verification passed on**

Brave | 1.59.112 Chromium: 118.0.5993.54 (Official Build) (arm64)
-- | --
Revision | `967f25f295938c64c24e2e6a1790470668757655`
OS | macOS Version 14.0 (Build 23A344)

- Verified steps from [brave/brave-core#19882](https://github.com/brave/brave-core/pull/19882)
- Verified Connect Hardware Wallet from panel opens expanded desktop view

https://github.com/brave/brave-browser/assets/17010094/d56d1b08-2e88-4cb5-89b8-3e165cd88384
