### ISSUE TITLE
Brave VPN system-tray icon should show red warning-triangle when in error state

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#32534]
## Description 

Brave VPN system-tray icon should show red warning-triangle when in error state

Found while testing https://github.com/brave/brave-browser/issues/32281

## Steps to Reproduce

 1. install `1.59.49`
 2. launched Brave
 3. purchased, configured, and connected to `Brave VPN`
 4. disable Wi-Fi
 5. once `Disconnected`, click to try `Reconnecting...`
 6. wait until it errors out with a red `VPN` button

## Actual result:

Can't connect to server error has a red `VPN` button, but the system-tray icon is default

example | example
---------|---------
![image (5)](https://github.com/brave/brave-browser/assets/387249/77e7536d-eb49-4533-b719-4b2759196f49) | ![image (6)](https://github.com/brave/brave-browser/assets/387249/c7009a80-8ce2-474c-8061-c8fda868b7ac)

## Expected result:

According to Figma, it should look like the following, with a red warning triangle atop the icon

<img width="253" alt="Screenshot 2023-08-26 at 1 27 39 PM" src="https://github.com/brave/brave-browser/assets/387249/9f535549-7d09-4f32-82d4-7ddfa7fef353">

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave	1.59.49 Chromium: 116.0.5845.114 (Official Build) nightly (64-bit) 
Revision	064c02d8294715082ece089c05eb60726f1b01e9
OS	Windows 10 Version 22H2 (Build 19045.3393)
```
## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@rebron @spylogsster @simonhong @bsclifton @aguscruiz @MadhaviSeelam

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.59.78 Chromium: 117.0.5938.35 (Official Build) beta (64-bit)
-- | --
Revision | fb1f1c3b5b111f1e14183bf1a94cd8103269f5bf
OS | Windows 10 Version 22H2 (Build 19045.3393)
```

Followed my original steps to reproduce.

### Confirmed I saw the red error/warning system-tray icon

example | example
----------|----------
![Capture2](https://github.com/brave/brave-browser/assets/387249/3ef6dc9d-fcf6-467a-b9e2-c2a1c55c0ef5) | ![image](https://github.com/brave/brave-browser/assets/387249/3d0ec38f-0b4b-4bbe-8448-0834ad96c01e)

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.59.94 Chromium: 117.0.5938.88 (Official Build) beta (64-bit)
-- | --
Revision | 2dca22d0a20096c32df5af4c88700a0b31acb55c
OS | Windows 11 Version 22H2 (Build 22621.2283)
```

1. install 1.59.94
2. launched Brave
3. purchased, configured, and connected to Brave VPN
4. disabled Wi-Fi
5. disconnected and reconnected 
6. waited until it errored out with a red VPN button

#### Confirmed system-tray icons shows red error/warning system-tray icon 

VPN button | system-tray
------- | -------
<image width="800" alt="Image" src= "https://github.com/brave/brave-browser/assets/98358127/cd280e66-2d3a-4615-b84a-cf7d6ada3a19">|<image width="800" alt="Image" src= "https://github.com/brave/brave-browser/assets/98358127/f02dac75-559b-4609-8fad-fc40664c1ef3">
