### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by mohammedrattia** [brave/brave-browser#32538]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.57.53 Chromium: 116.0.5845.114
Operating System: Windows NT 10.0.19045

URL (if applicable) where crash occurred:
brave://welcome

Can you reproduce this crash?
yes

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. open brave://welcome or try to import data (bookmarks and passwords) from settings

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/3aa30600-fa56-9c0a-0000-000000000000

**Comment by iefremov** [comment]
stale
