### ISSUE TITLE
New privacy option “Allow app links to open in apps outside of Brave” disabled by default breaks Custom Tab authentication

### ISSUE THREAD

**Issue by alexboin** [brave/brave-browser#32537]
## Description
I was trying to log in to an application using Custom Tabs to manage its authentication and after authentication, I am not redirected in the application and therefore the connection cannot be done.

I saw that it came from a [new Privacy option](https://community.brave.com/t/brave-browser-not-redirecting-to-app/502840) “Allow app links to open in apps outside of Brave”, added recently and by default on off therefore breaking all applications using custom tabs as a basis for authentication.

Can’t this option be off by default only in the browser and enabled on custom tabs? Or display a prompt “Do you authorize [site address] to open [app name or scheme]”?

## Steps to reproduce

   1. Just go to an application that offers to connect via a web page in a Custom Tab.
   2. Enter your login credentials and validate.
   3. It is stuck.

## Actual result
After authentication, not automatically redirected to the source application so the login process fails

## Expected result
After authentication, be automatically redirected to the source application for the process to complete normally

## Issue reproduces how often
Every time as long as the option is not enabled by the user before authentication

## Version/Channel Information:
Play store version

## Device details
ARM Phone, Android 11
   
## Brave version
Brave 1.57.50, Chromium 116.0.5845.96

**Comment by doroshenkoira** [comment]
I have the same issue. With Android 13, 33) and Brave browser and Aouth0. (Chrome and Firefox for well on this device and with this  same app). When I enter my creds the Brave just stuck and does't redirect back to the app. I tried to debug the phone and I see the error in web console "Navigation is blocked". I tried to off shield, allow all cookies and allow ADS, but nothing helped.
<img width="370" alt="Screenshot 2023-08-27 at 18 15 46" src="https://github.com/brave/brave-browser/assets/18345811/814b9f8a-16bb-46fd-ba57-c2d75899caf5">

**Comment by TheColtron** [comment]
It's wild to me that the decision to set that flag false by default was because "it was causing some user confusion". I would assume many more users would be confused when phone links, email links, and any number of others suddenly stop working.

Adding an "Enabled with prompts" state or similar as the default seems like a better compromise. Building awareness that users can choose to open all links in the browser is more appropriate than forcing a breaking change, IMO.

**Comment by bsclifton** [comment]
Hi folks - thanks for the report. This should be fixed - it was tracked with https://github.com/brave/brave-browser/issues/32500 and https://github.com/brave/brave-browser/issues/32586
