### ISSUE TITLE
Brave VPN system-tray icon should show "blurple" while in `Connecting...` state

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#32535]
## Description 

Brave VPN system-tray icon should show "blurple" while in `Connecting...` state

Found while testing https://github.com/brave/brave-browser/issues/32281

## Steps to Reproduce

1. install `1.59.49`
2. launched Brave
3. purchased, configured, and connected to `Brave VPN`
4. disconnected
5. switched to a far-away server location (i.e. Switzerland, Australia, etc.)
6. clicked to try `Connecting....`

## Actual result:

The system-tray icon is default

example | example
---------|--------
![image (7)](https://github.com/brave/brave-browser/assets/387249/80be6cc3-a1a8-48a1-90f5-34bf219a4a99) | ![image (8)](https://github.com/brave/brave-browser/assets/387249/d303bf19-462b-4d99-9f3a-8687467a77ae)

## Expected result:

Should show the "blurple"-colored `Connecting...` icon, instead

example | example
---------|---------
<img width="800" alt="Screenshot 2023-08-26 at 1 16 21 PM" src="https://github.com/brave/brave-browser/assets/387249/f2f79ec7-125c-499c-986c-60b47f1af513"> | <img width="443" alt="Screenshot 2023-08-26 at 1 50 15 PM" src="https://github.com/brave/brave-browser/assets/387249/1ceec70f-a9ad-47b6-8ea1-239129d6ef3f">

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave	1.59.49 Chromium: 116.0.5845.114 (Official Build) nightly (64-bit) 
Revision	064c02d8294715082ece089c05eb60726f1b01e9
OS	Windows 10 Version 22H2 (Build 19045.3393)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@rebron @spylogsster @simonhong @bsclifton @aguscruiz @MadhaviSeelam

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.59.78 Chromium: 117.0.5938.35 (Official Build) beta (64-bit)
-- | --
Revision | fb1f1c3b5b111f1e14183bf1a94cd8103269f5bf
OS | Windows 10 Version 22H2 (Build 19045.3393)
```

Followed my original steps to reproduce.

### Confirmed while in `Connecting...` state, `Brave VPN`'s system-tray notification icon shows the "blurple"-colored status

example | example
---------|-----------
![image](https://github.com/brave/brave-browser/assets/387249/8efe19ed-7b1d-4795-8a53-4b182a5d2ccb) | ![image](https://github.com/brave/brave-browser/assets/387249/61236163-ebc2-4f8e-8906-6001b7cd4e52)

**Comment by stephendonner** [comment]
Note: leaving open so we can also verify on `Windows 11`, after which we can add `QA Pass-Win64` 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.59.94 Chromium: 117.0.5938.88 (Official Build) beta (64-bit)
-- | --
Revision | 2dca22d0a20096c32df5af4c88700a0b31acb55c
OS | Windows 11 Version 22H2 (Build 22621.2283)
```

1. Installed 1.59.94
2. launched Brave
3. purchased, configured, and connected to Brave VPN
4. disconnected
5. switched to a far-away server location (i.e. Switzerland, Australia, etc.)
6. clicked to try Connecting....
 
### Confirmed while in Connecting... state, Brave VPN's system-tray notification icon shows the "blurple"-colored status

VPN panel | system-tray| system-tray VPN icon
----- | ------ | -----
<image width="900" src="https://github.com/brave/brave-browser/assets/98358127/f77ffaec-bcfd-4906-b446-93726edae3ab">|<image width="900" src="https://github.com/brave/brave-browser/assets/98358127/b7632a70-ac60-4a1f-b1b8-53f2b1794c6f">|<image width="900" src="https://github.com/brave/brave-browser/assets/98358127/70440580-5ba5-424a-9c6c-7e5fefae6e14">
