### ISSUE TITLE
VPN toolbar button has green when it's not purchased state

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#32542]
## Description 

VPN button has connected state when it's not purchased state.
VPN button should not have connected state in not purchased state.

## Steps to Reproduce

   1. Launch browser and set purchased state
   2. Connect to vpn to create os vpn entry
   3. Disconnect vpn and reset skus state from brave://skus-internals
   4. Terminate browser
   5. Connect vpn from os vpn entry
   6. Launch browser and create another window
   7. Check vpn toolbar button state from newly created window

## Actual result:

VPN toolbar button has connected state

## Expected result:
VPN toolbar button has disconnected state

## Reproduces how often: 

Easily

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.59.90 Chromium: 117.0.5938.88 (Official Build) beta (64-bit)
-- | --
Revision | 5272112c86588e44ec7c0b766c318cddccbced85
OS | Windows 11 Version 22H2 (Build 22621.2283)
```
Reproduced the issue in `1.58.127` using the STR from https://github.com/brave/brave-browser/issues/32542#issue-1869034226

https://github.com/brave/brave-browser/assets/98358127/d7a220df-9b15-491f-beac-a1da7c9c270d


Pre-requisite: Removed any previous VPN entries in the Network settings.

1. Installed 1.59.90
2. launched Brave
3. logged in to VPN using existing credentials via account.brave.com  
4. configured and connected VPN via VPN panel
5. verified os vpn entry is created via settings >> Network & internet
6. disconnected vpn and reset skus state from brave://skus-internals
7. terminated browser
8. connected vpn via from os vpn entry via  settings >> Network & internet
9. launched browser
10. clicked hamburger menu >> new window
11. clicked VPN toolbar button

 Confirmed VPN toolbar button has disconnected state in the new window 


https://github.com/brave/brave-browser/assets/98358127/094f5822-279d-4687-b8e0-61466995a529

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.59.93 Chromium: 117.0.5938.88 (Official Build) beta (x86_64)
-- | --
Revision | 77474ed80832bd2c90be4ebf993b6c2a43f662b0
OS | macOS Version 14.0 (Build 23A339)
```

### Steps:
1. installed `1.59.93`
2. launched Brave
3. purchased, configured, and connected to `Brave VPN`
4. confirmed `Brave VPN` network entry is created in `macOS`
5. disconnected from `Brave VPN` via the macOS `VPN` panel
6. opened `brave://skus-internals` and clicked `Reset SKUs state`
7. closed Brave
8. connected to `Brave VPN` from the `VPN` panel
9. relaunched Brave
10. checked `brave://skus-internals`


example | example | example | example | `step 6a`
---------|---------|----------|----------|---------
<img width="1312" alt="Screenshot 2023-09-19 at 5 37 45 PM" src="https://github.com/brave/brave-browser/assets/387249/32c59615-cb79-4b49-b745-a13f5bde7633"> | <img width="827" alt="Screenshot 2023-09-19 at 5 37 58 PM" src="https://github.com/brave/brave-browser/assets/387249/0d76164c-84c0-4a62-82d6-953e054cc3dc"> | <img width="827" alt="Screenshot 2023-09-19 at 5 38 23 PM" src="https://github.com/brave/brave-browser/assets/387249/b44b3fcb-3048-40ba-96b0-60ecc01b46e3"> | <img width="1312" alt="Screenshot 2023-09-19 at 5 38 34 PM" src="https://github.com/brave/brave-browser/assets/387249/948643bb-60c1-48dd-a607-e5ea65a733c3"> | <img width="1312" alt="Screenshot 2023-09-19 at 5 39 04 PM" src="https://github.com/brave/brave-browser/assets/387249/3b08cb65-e855-4bb6-a0e0-3c241742d95a">


`step 6b` | example | example | example | example
---------|----------|---------|----------|---------
<img width="1312" alt="Screenshot 2023-09-19 at 5 39 13 PM" src="https://github.com/brave/brave-browser/assets/387249/045034a8-48e8-4a3b-97ab-a99845917b0c"> | <img width="1312" alt="Screenshot 2023-09-19 at 5 39 17 PM" src="https://github.com/brave/brave-browser/assets/387249/fe60d78d-f7bb-4f7a-83e4-01d46aaaa439"> | <img width="827" alt="Screenshot 2023-09-19 at 5 39 35 PM" src="https://github.com/brave/brave-browser/assets/387249/df65a22d-070f-4895-aa47-ea749f639091"> | <img width="1312" alt="Screenshot 2023-09-19 at 5 40 02 PM" src="https://github.com/brave/brave-browser/assets/387249/ee0e08c6-acd7-4038-9565-0609b02c1d80"> | <img width="1312" alt="Screenshot 2023-09-19 at 5 40 15 PM" src="https://github.com/brave/brave-browser/assets/387249/991cbd4a-b578-4e3b-b9a5-2d3b93275afe">

**Comment by stephendonner** [comment]
## Verified `PASSED` using

### Steps:

1. installed `1.59.93`
2. launched Brave
3. disabled `WireGuard` via the toggle in `brave://settings/system`
4. purchased, configured, and connected to Brave VPN
5. confirmed Brave VPN network entry is created in Windows
6. disconnected from `Brave VPN` via the Windows `VPN` panel
7. opened `brave://skus-internals` and clicked `Reset SKUs state`
8. confirmed SKUs were cleared out
9. closed Brave
10. connected to Brave VPN from Windows' VPN panel
11. relaunched Brave
12. checked `brave://skus-internals`

### Confirmed `VPN` toolbar button correctly shows disconnected state, after resetting the SKUs SDK

example | example | example | example | example | example
---------|----------|---------|----------|---------|---------
![image](https://github.com/brave/brave-browser/assets/387249/13da71e6-da0e-410c-8b4f-703090252558) | ![image (1)](https://github.com/brave/brave-browser/assets/387249/3947c677-9dab-41ed-9814-8e50e706fbf7) | ![image (2)](https://github.com/brave/brave-browser/assets/387249/2c16e198-f3e6-4634-8f22-c1849b88beb2) | ![image (3)](https://github.com/brave/brave-browser/assets/387249/51c9ed79-5b0b-4515-9457-e1f4dcb21123) | ![image (4)](https://github.com/brave/brave-browser/assets/387249/d589d2cb-eda5-4761-8e2d-2ec1bc1ace6a) | ![image (6)](https://github.com/brave/brave-browser/assets/387249/c766e31e-5a93-4793-a166-a7af19e4f60c)
