### ISSUE TITLE
Upgrade from Chromium 105 to Chromium 116 for slack.com

### ISSUE THREAD

**Issue by derde** [brave/brave-browser#32547]
slack say that they're dropping support for chrome <106 on 1 September 2023.  (Brave is 104)
![image](https://github.com/brave/brave-browser/assets/2578422/adad185e-0b47-4b23-be5f-e444550e9c43)
https://slack.com/help/articles/1500001836081-Slack-support-lifecycle-for-operating-systems-app-versions-and-browsers
Sorry about the links below that don't work ... 

# Minor Chromium bump

https://chromium.googlesource.com/chromium/src/+log/PREVIOUS_VERSION..NEW_VERSION?pretty=fuller&n=10000

# QA tests:

* Check branding items
* Check for version bump

# Additional checks:
* No specific code changes in Brave (only line number changes in patches)

**Comment by mkarolin** [comment]
@derde what is your computer's operating system and version?

**Comment by derde** [comment]
Linux, Ubuntu 23.04

**Comment by derde** [comment]
mea culpa - there's the problem - dist-upgrade disabled brave updates:

    Tue Aug 29 09:41:48 ~ $ cat /etc/apt/sources.list.d/brave-browser-release.list
    # deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main # disabled on upgrade to jammy

After taking out the comment, it seems a little happier:

    sudo apt upgrade brave-browser 
    Unpacking brave-browser (1.57.53) over (1.42.97) ...

**Comment by derde** [comment]
Yep, having the repository enabled really helps.
