### ISSUE TITLE
Tweak portfolio UI and add option to show hidden NFTs

### ISSUE THREAD

**Issue by simoarpe** [brave/brave-browser#32545]
### Tweak UI

* Remove bounce effect from bottom navigation view
* Remove indicator from bottom navigation view
* Change color for selected section in bottom navigation view
* Increase top padding of chip tab layout at the top
* Modify background color of chip tab layout into darker gray (check Figma)

### Hidden NFTs

Add an option in the action bar to show/hide hidden NFTs in the NFT section

**Comment by srirambv** [comment]
Currently blocked on https://github.com/brave/brave-browser/issues/33255

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.59.115 x64 build
- Verified steps from [brave/brave-core#19990](https://github.com/brave/brave-core/pull/19990)
- Verified no bounce effect is shown on navigation
- Verified bottom navigation is now shown in single colour
- Verified able to show/hide NFTs 
- Additional verification [here](https://github.com/brave/brave-browser/issues/33255#issuecomment-1752437399)
