### ISSUE TITLE
Folder's dropdown menu hinged backward to `Bookmark this tab` Menu View

### ISSUE THREAD

**Issue by adityagi02** [brave/brave-browser#32541]
## Description 

To Bookmark any tab, while selecting any folder other than Bookmark, it does not show as the dropdown menu hides behind `Bookmark this tab` menu.

## Steps to Reproduce

   1. Open any website
   2. Open `Bookmark this tab` menu
   3. Click on `Bookmarks bar` of Folder

## Actual result:

https://github.com/brave/brave-browser/assets/77538183/51e8f28f-8aa6-4874-90dc-ee23ff6dbbf9

## Expected result:
Folder's dropdown menu should we visible completely in front of `Bookmark this tab` menu.

## Reproduces how often: 

Everytime

## Brave version (brave://version info)

[Version 1.57.53 Chromium: 116.0.5845.114 (Official Build) (arm64)](https://brave.com/latest/)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
@adityagi02 Closing this one as stale, can't reproduce. This should be fixed with 1.61.109 due to some changes with that bookmarks dialog.

Let us know if you're still seeing this issue.
