### ISSUE TITLE
only verified sites can be added to auto contribute table

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#3254]
## Description 
Found the first time I encountered https://github.com/brave/brave-browser/issues/3250

On my personal profile I encountered #3250 when updating to 0.61.7 or higher. After that, I noticed that when visiting new sites after getting the blank a-c table, only verified sites could be added to my a-c table. Toggling the option in settings did not change this (it was already checked to allow non-verified, but turning that off and then back on did not help). 

## Steps to Reproduce

Unfortunately I haven't been able to reproduce. Best I can tell is that I had a mix of verified/non-verified sites in my a-c table, default settings for a-c, updated to 0.61.7 and then only verified sites could be added to my a-c table. Contribution is supposed to happen tonight so this might not be an issue for very long.

## Actual result:
Here's my a-c table. Note, verified sites are showing % values as if there are other sites (they're low %'s):
<img width="630" alt="screen shot 2019-02-06 at 5 52 10 pm" src="https://user-images.githubusercontent.com/28145373/52379368-512dc500-2a38-11e9-9db0-aca9e2ee8218.png">

## Expected result:
Verified and non-verified sites should be able to be added to a-c table with default settings.

## Reproduces how often: 
haven't reproduced yet, spent ~2hrs trying but no luck.

## Brave version (brave://version info)

Brave | 0.61.10 Chromium: 72.0.3626.81 (Official Build) dev(64-bit)
-- | --
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? only experienced on Dev once

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by NejcZdovc** [comment]
closing as stale
