### ISSUE TITLE
Remove userdrain tooltip ZebPay ("yellow question mark")

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#32552]
## Description

**Hold until after vBAT sunset is complete.**

Remove the following tooltips everywhere now that they no longer apply:

![image](https://github.com/brave/brave-browser/assets/11497541/b8a53d36-b248-488f-8597-113f69858e2f)

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.61.66 Chromium: 119.0.6045.105 (Official Build) beta (x86_64)
-- | --
Revision | aaaecfc0d925cde58e40e1b689464f1c630ef96d
OS | macOS Version 13.6.1 (Build 22G313)
```

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.61.67`
