### ISSUE TITLE
`Enable extension network blocking` in brave://flags is broken

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#32569]
## Description 

Ads are visible from side panel extension.
Enabling `Enable extension network blocking` flag form brave://flags doesn't work.
<img width="488"  src="https://github.com/brave/brave-browser/assets/6786187/0f1477a5-7cc0-4566-bf98-a641cd304762">
<img width="688"  src="https://github.com/brave/brave-browser/assets/6786187/0519520b-cfe6-43dc-aaa9-a98d0637deaf">

## Steps to Reproduce

   1. Install Flow: ChatGPT Sidebar - https://chrome.google.com/webstore/detail/flow-chatgpt-sidebar/ndmldohefgmnciihihioeeoiobchcmgi
   2. And open it from side panel
   3. 

## Actual result:

Ads should be blocked

## Expected result:
Ads visible

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by simonhong** [comment]
cc @antonok-edm

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using 
```
Brave | 1.59.86 Chromium: 117.0.5938.62 (Official Build) beta (64-bit)
-- | --
Revision | 3c4c1c3b2eef0fcbe8485c67e1df504942deadca
OS | Windows 11 Version 22H2 (Build 22621.2283)
```
Could not reproduce the issue in `1.58.124` and `1.60.19`

1. Installed 1.59.86
2. launched Brave
3. opened brave://flags in a new tab
4. enabled `Enable extension network blocking`
5. installed [Flow: ChatGPT Sidebar](https://chrome.google.com/webstore/detail/flow-chatgpt-sidebar/ndmldohefgmnciihihioeeoiobchcmgi) 
6. pressed `Alt + C` to open `ChatGPT` side panel (wait for few secs to ChatGPT to load)

### Confirmed no ads are shown in the ChatGPT side panel

step 4 | step 5 | step 6 | result
---- | ---- | --- | ----
<img width="950" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/17fd67ab-c825-438b-baef-f7c71eda094c">|<img width="952" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/8914a821-efdc-4511-a4d7-d4a9fa2037c1">|<img width="954" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/1a02fc73-85eb-44a3-99f6-a12b50773d5a">|<img width="955" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/243d62d8-4256-4770-b5b9-b729af7d98c9">

**Comment by LaurenWags** [comment]
Verified with

```
Brave | 1.59.115 Chromium: 118.0.5993.54 (Official Build) (x86_64)
-- | --
Revision | 82b05012fc6b5ab8535cf283db6856ad5eedd7eb
OS | macOS Version 13.6 (Build 22G120)
```

Reproduced the issue using `1.58.137 Chromium: 117.0.5938.153`, saw that after executing the test plan there were no blocked requests on the `Network` tab of dev tools.

Using `1.59.115 Chromium: 118.0.5993.54` and test plan from https://github.com/brave/brave-core/pull/19909#issue-1870819648, observed the blocked requests on the `Network` tab of dev tools.

1.58.137 | 1.59.115
--- | ---
<img width="1491" alt="1 58" src="https://github.com/brave/brave-browser/assets/28145373/5c09f3fc-3d54-4f66-a7d5-653ed333a87a"> | <img width="1512" alt="1 59" src="https://github.com/brave/brave-browser/assets/28145373/8efe184f-3eec-4d02-80e6-3fba75333551">
