### ISSUE TITLE
macOS sonoma public beta 4: Brave BETA and NIGHTLY both crash upon launch

### ISSUE THREAD

**Issue by julianpuffer** [brave/brave-browser#32566]
## Description 
On my system (macbook pro 14 + macOS sonoma public beta 4), both brave beta and nightly immediately crash when trying to launch. I can't even get the exact version from "about brave" because how quickly it crashes. MacOS generates it's auto-crash reporting popup, and trying to reopen from there leads to a cycle of crash reporting and relaunch attempts. 

***Brave stable doesn't have this issue. I'm writing this report on it right now. If it helps, brave stable version is: Version 1.57.53 Chromium: 116.0.5845.114 (Official Build) (arm64)

## Steps to Reproduce

   1. Launch brave browser beta (or nightly)
   2. Dock icon shows up very briefly, before it disappears as the app crashes

## Actual result:
![CleanShot 2023-08-28 at 14 58 56@2x](https://github.com/brave/brave-browser/assets/55923092/b51e8b31-c45e-4dd1-acc8-defd998e2cda)

![CleanShot 2023-08-28 at 14 58 43@2x](https://github.com/brave/brave-browser/assets/55923092/d2cae26c-490c-4954-9c4f-fafab36896cf)

## Expected result:
launch and stay open

## Reproduces how often: 
Every single launch attempt has crashed

## Brave version (brave://version info)
Unable to obtain, but I did use fresh installs of both nightly and beta today. 

## Version/Channel Information:
Only on beta and nightly

## Other Additional Information:
Log txt files are attached (copy paste of apple's crash report logging)

[brave-browser-beta-launch-crash-macos-sonoma.txt](https://github.com/brave/brave-browser/files/12458485/brave-browser-beta-launch-crash-macos-sonoma.txt)
[brave-nightly-launch-crash-macos-sonoma.txt](https://github.com/brave/brave-browser/files/12458486/brave-nightly-launch-crash-macos-sonoma.txt)

**Comment by rebron** [comment]
@jpufferfish Can you update to the latest version beta and nightly, that should have chromium 117 now. Also, did you have any flags enabled if you can remember that far back?

**Comment by jpufferfish** [comment]
Since I was never able to even launch the app, there wasn't a way to even enable any flags. So they're all fresh installs. And I just tried again with the latest chromium 117 issue, to no avail.

**Comment by jpufferfish** [comment]
@rebron, just curious. Given that I have Brave release installed, working, and regularly used on the same mac system (where beta and nightly still are unable to launch) - are beta and nightly allowed to be installed and used on the same system? Will there be their separate local browser data in the ~/Library/Application Support/ directory on mac? On iOS for example, I have both brave and brave beta via testflight working just fine.

**Comment by jpufferfish** [comment]
Also here's the .ips diagnostic file contents as .txt

[brave-nightly-crash-diagnostic.txt](https://github.com/brave/brave-browser/files/12667072/brave-nightly-crash-diagnostic.txt)

**Comment by julianpuffer** [comment]
This unofficial mac mpv build also has similar behavior. Shows up in dock temporarily, then auto closes/crashes. So it might not be brave-specific. 

https://laboratory.stolendata.net/~djinn/mpv_osx/

**Comment by julianpuffer** [comment]
Brave Browser Dev edition is also affected

**Comment by Coffeeling** [comment]
Just had this happen on macOS Sonoma 14.4. Brave beta works fine and updated itself without issue, but opening Nightly causes it to crash within a couple seconds.

I got it to stay up once by Cmd+Shift+T:ing to reopen a closed tab - that fixed the issue last I had it on Windows (there it was confined to a specific profile on Brave Beta), but now even that seems to not help.

**Comment by Coffeeling** [comment]
Aand got it on Windows 11, Nightly as well.

**Comment by julianpuffer** [comment]
> Just had this happen on macOS Sonoma 14.4. Brave beta works fine and updated itself without issue, but opening Nightly causes it to crash within a couple seconds.
> 
> 
> 
> I got it to stay up once by Cmd+Shift+T:ing to reopen a closed tab - that fixed the issue last I had it on Windows (there it was confined to a specific profile on Brave Beta), but now even that seems to not help.

I just updated to macOS 14.4, but both Nightly and Beta still don't open for me after dragging the .app file into the Applications folder

**Comment by julianpuffer** [comment]
Both Nightly v1.66.3 and Beta v1.65.82 now work on my end with macOS Sonoma 14.4 (23E214)
