### ISSUE TITLE
Update dark mode details for better readability

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#32565]
>  I feel like the text is hard to read because of the dark background

https://twitter.com/namgiangnet/status/1696240757408153675?s=20

**Comment by bbondy** [comment]
@aguscruiz this is how it looks, is that OK or did you want changes based on the above feedback? If you want to keep it the same I'll close this issue.
<img width="316" alt="Screenshot 2023-09-03 at 4 05 27 PM" src="https://github.com/brave/brave-browser/assets/831718/e741d567-d7c1-4810-8b64-e8c37e3b72ad">

**Comment by aguscruiz** [comment]
I have an update to those buttons look pending, I'll reach out to the devs.

**Comment by bbondy** [comment]
OK let's keep this issue for tracking the actual work needed for the updates.

**Comment by nullhook** [comment]
@fallaciousreasoning do you know if this has been updated?

**Comment by fallaciousreasoning** [comment]
The button does look slightly different to those screenshots, so it might well have been updated - the border is slightly subtler, like it is in the Figma, so I guess it probably has been :smile:

**Comment by nullhook** [comment]
<img width="1196" alt="image" src="https://github.com/brave/brave-browser/assets/8665427/2e0c550d-545f-4918-a902-4186353123d2">

this is resolved by: https://github.com/brave/brave-core/pull/21834

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.64.41 Chromium: 121.0.6167.139 (Official Build) nightly (x86_64)
-- | --
Revision | 1c56846eb16cec835298c09cd75ec45fc425507b
OS | macOS Version 14.4 (Build 23E5180j)
```

### Confirmed new color palette used which matches mocks/Figma

`beta` (`1.63.141`) | `current` (`1.64.41`)
--------------------|--------------------
<img width="340" alt="Screenshot 2024-02-01 at 10 37 33 PM" src="https://github.com/brave/brave-browser/assets/387249/fc1cee9d-11ef-42a9-aca1-e1dd4323a88e"> | <img width="422" alt="Screenshot 2024-02-01 at 10 38 05 PM" src="https://github.com/brave/brave-browser/assets/387249/231209b9-68e1-45fb-a4ce-2e59e2375d75">

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP21.240119.009 release-keys
Brave build: 1.64.95 
Chromium: 122.0.6261.94 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Install and launch Brave
2. Make sure `Dark Theme` is enabled on the device
3. Open `Leo` > send a query > *Verify*

**ACTUAL RESULTS:**
- Verified that the new color palette used which matches mocks/Figma
- Verified that no regression happened in `Light Theme`

---------------------------

|Old|New|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/069db677-2712-402b-8ec9-8431b37a503e) | ![2](https://github.com/brave/brave-browser/assets/128532965/b8c7635b-20b7-480f-9d20-cd6c5e897193) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/4462486c-f6d0-461f-be84-cebb8b45dd74) | ![2](https://github.com/brave/brave-browser/assets/128532965/b10863b0-3543-4243-bbe2-e5fb5bd9e5b9) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/85fb0948-fb14-422f-96c8-c7dc22ebccb8) | ![2](https://github.com/brave/brave-browser/assets/128532965/4e1b4ca8-f782-4aa5-a4f1-a3a029fb0fe7) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/4f8f316d-d153-432f-aeda-fafe1a15a411) | ![2](https://github.com/brave/brave-browser/assets/128532965/c4276a5c-8c68-42a5-8340-e3ba49ab3afd) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/43247c75-455a-4d29-82f8-5146a3dc746b) | ![2](https://github.com/brave/brave-browser/assets/128532965/90581d52-6756-4371-9c1c-737e86d5fc6e) |
