### ISSUE TITLE
Add UI to copy question / answers from browser-ai

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#32564]
Copies only the individual item. You can get at this menu for every answer individually. 

See [Figma](https://www.figma.com/file/h7fKSJF2P556bZWfyLTfwD/Brave-AI?type=design&node-id=2726-12088&mode=design&t=LxtYravMo4zX7cRx-0) for the latest design:

![Screenshot 2023-09-04 at 12 48 09 PM](https://github.com/brave/brave-browser/assets/831718/e647ac27-120b-4131-9751-1a7e00353e2a)

User requested here:
https://twitter.com/namgiangnet/status/1696242625886699584

**Comment by nullhook** [comment]
This has been resolved in the MVP
