### ISSUE TITLE
Follow up of PR #19803 - Userdrain tooltip (yellow question mark) is NOT shown in the BR panel

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#32576]
## Description 
Found while testing Follow up of PR #19803
Userdrain tooltip (yellow question mark) is NOT shown in the BR panel

## Steps to reproduce 

   1. Create profile on old version of Brave (e.g `1.47.96`)
   2. Enable rewards and select the country as "India"  
   3. Send yourself some vBAT
   4. Upgrade to a more recent version so that you are in the grandfathered-unverified state
   5. Connect to ZebPay
   6. Make sure “userdrain tooltip” (yellow question mark) appears on NTP widget, Rewards panel, and brave://rewards settings page

## Actual result 
Userdrain tooltip (yellow question mark) is NOT shown in the BR panel

![Screenshot_20230829-163003_Brave - Nightly](https://github.com/brave/brave-browser/assets/38657976/0c88cb8f-48fd-4a2c-bab8-a83fe9f33e0b)

## Expected result
Userdrain tooltip (yellow question mark) should be shown in the BR panel same as rewards settings page
![Screenshot_20230829-163159_Brave - Nightly](https://github.com/brave/brave-browser/assets/38657976/dda4033b-7292-4720-bb3d-b00545339486)

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86): all
   - Device type (Phone, Tablet, Phablet):all
   - Android version:12
   
## Brave version
1.59.55

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/qa-team @Miyayes @deeppandya

**Comment by Miyayes** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/32553.

**Comment by kjozwiak** [comment]
The above requires `1.58.121` or higher for `1.58.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Samsung Galaxy version 12` running `Bravemonoarm64.apk_1.58.121`

1. Installed older Nightly version (`1.45.116` is an older RC version)
2. Enabled staging env
3. Joined Rewards and selected "India" as the country
4. Confirmed no custodian available
5. Sent ad grant, confirmed ad grant received and claimed
6. Closed 1.47.x Nightly
7. Upgraded to `1.60.11`
8. Relaunched the browser 
9. Confirmed vBAT still displayed as part of balance
10. Confirmed ZebPay is available as a custodian
11. Confirmed able to connect to ZebPay
12. Confirmed after connecting to ZebPay the previous vBAT balance was removed from the account balance and a tooltip was displayed on brave://rewards and the panel.
13. Confirmed tooltip text displayed when tapped on.
14. Confirmed tooltip text displayed for both light and dark themes from the panel

Step 5 | Step 9 | Step 12 | Step 12 | Step 13 | Step 13 | Step 14 | Step 14
--- | --- | --- | --- | --- | --- | --- | ---
![Screenshot_20230912-165413_Brave](https://github.com/brave/brave-browser/assets/38657976/f608d147-3187-4e86-b444-9dd863869780) | ![Screenshot_20230912-165459_Brave](https://github.com/brave/brave-browser/assets/38657976/c256cb3f-4b2f-4338-9032-7a2778b26a91) | ![Screenshot_20230912-165655_Brave](https://github.com/brave/brave-browser/assets/38657976/37ecadae-fe3c-4560-9b25-9e6500c671e2) | 



Extra:
Confirmed claim displayed on metabase per instructions from https://bravesoftware.slack.com/archives/C0NPFB6H5/p1693900441745289?thread_ts=1692789212.170909&cid=C0NPFB6H5:
![image](https://github.com/brave/brave-browser/assets/38657976/c465abb8-a9cb-4de2-a666-56206a7220ed)
