### ISSUE TITLE
Follow up of PR #19803 - Cross custodian tipping banner shows the ZebPay account balance

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#32573]
## Description 
Found while testing the PR #19803
Cross custodian tipping banner shows the ZebPay account balance

## Steps to reproduce 

   1. Clean profile 1.59.x
   2. Select the country as "India"
   3. Connect to a ZebPay account
   4. Open any cross custodian publisher (e.g 1. https://laurenwags.github.io, https://github.com/miyayes, https://alexvincentmusic.com)
   5. Open the tipping banner
   6. Can't send contributions to cross custodian message is shown correctly, but the ZebPay wallet balance is shown on the tipping banner 

## Actual result 
ZebPay wallet balance is shown on the tipping banner 

Uphold | Gemini | bitFlyer 
---------|---------|---------
![Screenshot_20230829-152514_Brave - Nightly](https://github.com/brave/brave-core/assets/38657976/7af78908-1003-4fbf-83de-50a4de5310a1) | ![Screenshot_20230829-152554_Brave - Nightly](https://github.com/brave/brave-core/assets/38657976/60127df9-e4cc-44f6-95d7-23202b18d30c) | ![Screenshot_20230829-152621_Brave - Nightly](https://github.com/brave/brave-core/assets/38657976/bd27ed5c-5e8d-46af-87b0-b4ae4145516f)

## Expected result
ZebPay wallet balance should NOT be shown on the tipping banner for the cross custodian pubs

Desktop
![image](https://github.com/brave/brave-browser/assets/38657976/c95a2762-3451-48c1-a641-a76d1a7c9172)

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86): all
   - Device type (Phone, Tablet, Phablet):all
   - Android version: 12
   
## Brave version
1.59.55

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/qa-team @Miyayes @deeppandya

**Comment by Miyayes** [comment]
https://github.com/brave/brave-browser/issues/32584 <-- Will implement this instead.
