### ISSUE TITLE
First background image is skipped when branded image is shown after startup

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#32577]
## Description 

When first NTP loading is branded image,
background image(`Sean O' Riordan`'s image) index is also increased at the same time.
So, next NTP loading shows seconds background image.
First background image should not be skipped.

## Steps to Reproduce

   1. Change to region that has SI campaign
   2. Launch browser and open NTP and loading multiple times to set next loading will be NTP SI
   3. Shutdown and relaunch
   4. Check NTP shows NTP SI
   5. Reloading

## Actual result:

Show second background image

## Expected result:
Show first background image

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.59.102 Chromium: 117.0.5938.140 (Official Build) beta (arm64)
-- | --
Revision | 11284b6d5d51252fe1a6fb6b5cba35ef98982357
OS | macOS Version 14.0 (Build 23A344)
```
