### ISSUE TITLE
Extension update requests are sent in JSON are not handled correctly

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#3258]
From: https://github.com/brave/go-update/issues/17

## Description 
Requests to update extensions are sent in JSON instead of XML. These requests are not handled correctly by go-updater. 

## Test Plan
See issue: https://github.com/brave/brave-core/pull/1602

## Steps to Reproduce
   1. Run go-updater locally
   2. Try updating extensions
   3. See update request in JSON

## Actual result:
Update request in JSON

## Expected result:
Update request in XML

## Reproduces how often: 
Easily

## Brave version (brave://version info)
master

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.60.40 Chromium: 72.0.3626.109 (Official Build) (64-bit)
-- | --
Revision | fae8db7ab9280fa6704a59980263c804f809ebd5-refs/branch-heads/3626@{#857}
OS | Linux

* Verified test plan from brave/brave-core#1602
