### ISSUE TITLE
Move connections observers to separate classes

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#32582]
Before to add IKEv2 to tray icon need to do small refactoring:
1) Share RAS connection observer code between browser and tray icon
2) Observe 2 different connections(Wireguard and IKEv2) from tray icon, before doing this lets move wireguard connection observer to a separate class too

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.59.95 Chromium: 117.0.5938.88 (Official Build) beta (64-bit)
-- | --
Revision | a2cb6fb53ea2c9ab356de955aab8505f5455b8bb
OS | Windows 10 Version 22H2 (Build 19045.3448)
```

## RAS/IKEv2

## WireGuard

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.59.103 Chromium: 117.0.5938.140 (Official Build) beta (64-bit)
-- | --
Revision | e0f257d585b29dd1194e82717cf18db50a7c0edb
OS | Windows 11 Version 21H2 (Build 22000.2482)
```
