### ISSUE TITLE
Display user's custodial balance in Contribution banner in cross-custodial case (do not dash out)

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#32584]
## Description

Previous design was: 
![image](https://github.com/brave/brave-browser/assets/11497541/b3a05e5d-b44b-42b8-af36-e2090019e3a0)

Note the dashing out of the balance.

```[tasklist]
### Tasks
- [ ] Do not dash out balance anymore in this case
```

**Comment by zenparsing** [comment]
It seems that the cross-custodial balance is being displayed:

<img width="516" alt="Screenshot 2023-09-06 at 11 02 45 AM" src="https://github.com/brave/brave-browser/assets/5995084/96693e97-290d-4747-bed8-54d848df7b8d">

It might be the case that the balance is taking a long time to load from the wallet provider; I don't think we implemented the loading spinner for the balance that appears on the tip panel.

**Comment by zenparsing** [comment]
It appears that the tip panel will not show the UI until all data, including the balance, has loaded. (It will show a single spinner covering the panel instead.) If the balance is showing as dashes, then that would indicate that there was an error loading the balance.

**Comment by Miyayes** [comment]
Okay, thanks. So this is actually not a valid issue, and perhaps my profile was borked and unable to fetch the balance, even though I was not in the Logged Out state. (If I were in the logged out state, the UI would have been different.)
