### ISSUE TITLE
`Allow app links to open in apps outside of Brave` not being enabled after update - follow up to #32500

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#32586]
## Description 

The following is a follow up to https://github.com/brave/brave-browser/issues/32500 which should enable `Allow app links to open in apps outside of Brave` on  new/clean profiles and updated profiles. However, currently it only enables `Allow app links to open in apps outside of Brave` on new installs. As per @aekeus via https://bravesoftware.slack.com/archives/C03MMJ4CHEZ/p1693318208440149?thread_ts=1693289587.738989&cid=C03MMJ4CHEZ, we should be enabling `Allow app links to open in apps outside of Brave` on updated profiles that have not updated the default.

## Steps to reproduce 

* install `1.59.48 Chromium: 116.0.5845.114` via APK
* ensure that `Allow app links to open in apps outside of Brave` is disabled as `1.59.48` didn't have the fix
  * ensure that you don't touch/enable `Allow app links to open in apps outside of Brave`
* using GPS, update Nightly from `1.59.48 Chromium: 116.0.5845.114` --> `1.59.53 Chromium: 116.0.5845.114` (`1.59.53` has the fix)
* notice that `Allow app links to open in apps outside of Brave` is still disabled

The above STR/Cases might differ a bit as we'll most likely have a higher version of Brave on the Nightly channel at that point.

## Actual result 

Once updated, `Allow app links to open in apps outside of Brave` is still disabled.

## Expected result

`Allow app links to open in apps outside of Brave` should be enabled if the user hasn't changed the default/toggled the setting.

## Issue reproduces how often 

100% reproducible using the STR/Cases outlined above.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `No`
- Can you reproduce this issue with the current Play Store Beta version? `Yes` 
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Pixel 6`
   - Android version: `Android 14`
   
## Brave version

```
Brave | 1.59.54 Chromium: 116.0.5845.114 (Official Build) canary (64-bit)
--- | ---
Revision | 1cff2d5cf0c7486bad79efc2b91e7708aae2a741
OS | Android 14; Build/UPB5.230623.006; 34; REL
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by kjozwiak** [comment]
The above requires `1.57.59` or higher for `1.57.x` verification 👍

**Comment by kjozwiak** [comment]
We'll use https://github.com/brave/brave-browser/issues/32630 for the release notes on `Android` as per https://github.com/brave/brave-browser/issues/32630.

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy Tab S7` using the following version:

```
Brave	1.57.60 Chromium: 116.0.5845.163 (Official Build) (64-bit) 
Revision	7bc3c0bc8b1d330c8920b4d4e3278e0f04bbf0c9
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
- Verified test cases in https://github.com/brave/brave-browser/issues/32586#issue-1872144049
- Verified test cases in https://github.com/brave/brave-core/pull/19930#issuecomment-1699842905

_Fresh Profile_

- Ensured `Allow app links to open in apps outside of Brave` is enabled on fresh profile.

_Existing Profile_

- Ensured `Allow app links to open in apps outside of Brave` is enabled after upgrading app from `1.57.53, Chromium 116.0.5845.114` to `1.57.60, Chromium 116.0.5845.163`

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version 

```
Brave	1.57.60 Chromium: 116.0.5845.163 (Official Build) (64-bit) 
Revision	7bc3c0bc8b1d330c8920b4d4e3278e0f04bbf0c9
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
- Verified STR in https://github.com/brave/brave-browser/issues/32586#issue-1872144049
