### ISSUE TITLE
unable to get NTP ads after disabling notification ads - follow up to 30637

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#32581]
## Description 

Found while testing #30637 

If you disable notification ads, you cannot get NTP ads. It appears in the logs as though the catalog is reset, but it should not be per discussion with @btlechowski as it is still needed for NTP ads.

## Steps to Reproduce

   1. Clean profile 1.58.x (prod or staging env, doesn't matter)
   2. Close and relaunch to pull griffin
   3. Enable Rewards
   4. After Rewards are enabled, toggle off "Notification ads" from "Manage Brave Ads" under brave://rewards
   5. Attempt to trigger NTP SI ad ---> you will not get one

## Actual result:

After doing the above steps, I looked in the logs and conferred with @btlechowski and these parts seemed to indicate the problem.

Catalog is fetched/parsed after enabling ads:

```
[50417:259:0829/104039.623864:VERBOSE1:catalog_url_request.cc(93)] Parsing catalog
[50417:259:0829/104039.627361:VERBOSE1:catalog_url_request.cc(126)] Successfully fetched catalog
```

After disabling notification ads this was shown in the logs:

```
[50417:259:0829/104114.261206:VERBOSE1:catalog.cc(83)] Shutdown catalog URL request
[50417:259:0829/104114.261501:VERBOSE1:catalog.cc(86)] Reset catalog
```

When attempting to trigger an NTP SI ad:

```
[50417:259:0829/104127.439109:VERBOSE2:permission_rule_util.cc(18)] Catalog does not exist
```

## Expected result:

When notification ads are disabled, I should still be able to view NTP SI ads if the toggle is on for them.

## Reproduces how often: 

easily

## Brave version (brave://version info)

```
Brave | 1.58.106 Chromium: 116.0.5845.114 (Official Build) beta (x86_64)
-- | --
Revision | 601f5c9afccc48f581021ae0e0ee6c85b58821d2
OS | macOS Version 13.5.1 (Build 22G90)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a 
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? probably

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @Miyayes @zenparsing - full logs available if needed, just shared what looked important to me above

**Comment by kjozwiak** [comment]
The above requires `1.58.110` or higher for `1.58.x` verification 👍 Removing `QA/Blocked`.
