### ISSUE TITLE
AI Chat content extraction should fallback to all page text

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#32590]
## Description 

No content can be found on pages which don't define the html structure we're expecting (currently a `<main>` or `<article>` element containing `<p>` tags (amongst others).

We could fallback to the body's innerText (preserving line-breaks).

## Steps to Reproduce

   1. Visit https://coinmarketcap.com/
   2. Open Leo sidebar

## Actual result:

Leo does not know about the page content (the favicon and title and prompt to summarize is missing).

## Expected result:
Leo could know about some of the page content (aforementioned UI elements would be visible)

## Reproduces how often: 

100%

## Brave version (brave://version info)

1.59.47

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.60.64 Chromium: 118.0.5993.21 (Official Build) nightly (x86_64)
-- | --
Revision | f05e9ca819b9af4850b13764e15631322922d47c
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.60.64`
2. launched Brave
3. restarted (to pick up Griffin seed)
4. loaded `https://coinmarketcap.com/`
5. clicked on `Brave Leo` on the sidebar
6. clicked `Accept and begin`
7. confirmed the following:
* site favicon
* page title
* "Suggested follow-ups" section
* `Summarize this page` button

`1.60.64` | `1.59.47`
---------|---------
<img width="1632" alt="Screen Shot 2023-09-28 at 4 42 30 PM" src="https://github.com/brave/brave-browser/assets/387249/dfcef3f6-3729-4457-abc2-0dd4c2c63f87"> | <img width="1665" alt="Screenshot 2023-09-28 at 4 43 03 PM" src="https://github.com/brave/brave-browser/assets/387249/a48d0775-e417-450a-9488-d56590e6e51e">

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 [panther_beta-user 14 U1B1.230908.003 release-keys]
Brave build: 1.60.76 
Chromium: 118.0.5993.32 (Official Build) canary (64-bit) 
Revision: c66376dd699f9327afd2f556c90b029bf4aa32e9
```
---------------------------

**STEPS:**
1. Launch Brave
2. Go to `brave://flags`
3. Enable `brave-ai-chat` > Restart Brave
4. Go to https://coinmarketcap.com
5. Three-dot menu > Tap `Brave Leo`
6. Tap `Accept and begin` for the first launch
7. Tap `Enable` or `Skip` > Verify
8. Tap `Summarize this page` > Verify

**ACTUAL RESULTS:**
- Verified that website `icon`, `description` and `Summarize this page` are shown 
- Verified that `Summarize this page` button is working and results are shown when tapped on the button

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/678e0cae-a369-4a1d-8ae5-1685457259a6) | ![2](https://github.com/brave/brave-browser/assets/128532965/18703a09-453d-4450-8495-752aaca3167e) | ![3](https://github.com/brave/brave-browser/assets/128532965/940c71d9-9586-406d-9392-1d281901f61c) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/e9081611-4907-4923-a969-539c5bcfdb3e) | ![2](https://github.com/brave/brave-browser/assets/128532965/c115d443-98f2-41dc-b9d6-f2c1fb7f9a22) | ![3](https://github.com/brave/brave-browser/assets/128532965/7e0cc793-0e18-4f22-9b8b-412f552d4c60) |
