### ISSUE TITLE
VPN should be in disconnected state when SKUs are cleared in `brave://skus-internals` page

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#32596]
## Description 

Found while testing #https://github.com/brave/brave-browser/issues/32030.  When SKUs are cleared in `brave://skus-internals` page, VPN should get disconnected.  VPN shows connected state while when clicked it shows ` Not Purchased` state with VPN onboarding modal. 

## Steps to Reproduce

1. installed 1.59.56
2. launched Brave
3. purchased, configured, and connected to Brave VPN
4. clicked `Fetch VPN State` and `Fetch SKUs state` in `brave://skus-internals`
5. disabled and enabled VPN via vpn panel
6. clicked Reset SKUs state in `brave://skuss-internals`
7. clicked on VPN button

## Actual result:

Got onboarding boarding modal and VPN is still connected state
`brave://skus-internals` page shows blank fields for `Fetch VPN State` and `Fetch SKUs state` when clicked

https://github.com/brave/brave-browser/assets/98358127/12dd45dc-6278-474c-8fac-3b60ff0adb9c

## Expected result:
VPN should be in disconnected state in VPN panel

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.57.56 Chromium: 116.0.5845.114 (Official Build) (64-bit)
-- | --
Revision | 6fa63f5677a245eb7834718cd2ab3d87c7eabc45
OS | Windows 11 Version 22H2 (Build 22621.2134)
```
## Version/Channel Information:

- Can you reproduce this issue with the current release? No 
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
 @simonhong @bsclifton 
cc: @stephendonner

**Comment by simonhong** [comment]
Closed as duplicated with https://github.com/brave/brave-browser/issues/33023
