### ISSUE TITLE
Set sidebar button to default open with Leo

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#32601]
## Description 

When users select the sidebar button in the browser toolbar, default panel should open Brave Leo.

## Steps to Reproduce

   1. Use 1.59.57 and higher.
   2. Select the sidebar button.
   3. See expected result

## Expected result:

Current default panel when users select the sidebar button is Reading List. With Leo availability, default panel should be changed to Leo and then sidebar button should go to last used sidebar panel: bookmarks, reading list, Leo, (or playlist if playlist flag is enabled).

## Reproduces how often: 

Easily.

## Brave version (brave://version info)

1.59.x and higher

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by kjozwiak** [comment]
The above requires `1.64.103` or higher for `1.64.x` verification 👍
