### ISSUE TITLE
Hope to add an option to disable blocking third-party referer in Brave Shields

### ISSUE THREAD

**Issue by reguz** [brave/brave-browser#3260]
## Description 

Since Brave avoids cross-origin referer, videos can't be played in some websites if Brave Shields works. But if I disable Shields,  it will also stop blocking ads and trackers. So I hope brave can add an option to disable blocking third-party referer in Brave Shields.

## Brave version (brave://version info)

| Brave | 0.58.21 Chromium: 72.0.3626.81 (Official Build) (64-bit) |
| ------- | -------- |
| Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796} |

**Comment by srirambv** [comment]
Please upgrade to the new version that is `0.59.35`. CORS issue is fixed on the latest release. If you still have issues please log a new issue with details.
