### ISSUE TITLE
Add close function when selecting Brave Leo button in Speedreader

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#32610]
## Description 

Currently selecting the Brave Leo button in Speedreader opens up the Leo side panel. Upon clicking the Brave Leo button in Speedreader again, the sidepanel should be closed.

Also, update tooltip text to read `Brave Leo` instead of `Brave AI`

## Steps to Reproduce

   1. Use 1.59.57 and higher.
   2. Go to a page that can be speed read such as `https://www.sfgate.com/bayarea/article/where-to-see-super-blue-moon-bay-area-18337306.php`
   3. Hover to see tooltip and select Leo button. Notice it only opens the Leo side panel but doesn't close it.

<img width="174" alt="Screenshot 2023-08-29 at 9 29 33 PM" src="https://github.com/brave/brave-browser/assets/5951041/e33b3265-0172-4536-ab74-d7b211a74e77">

## Actual result:

See STR

## Expected result:
See Descriptio

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

Related: https://github.com/brave/brave-browser/issues/29075 and https://github.com/brave/brave-browser/issues/31583

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.60.60 Chromium: 117.0.5938.92 (Official Build) nightly (64-bit)
-- | --
Revision | 9a4644344a53150ebad5406037a6463714787348
OS | Windows 10 Version 22H2 (Build 19045.3516)
```

### Steps:
1. installed `1.60.60`
2. launched Brave
3. restarted (to pick up the Griffin seed)
4. loaded `https://www.sfgate.com/bayarea/article/target-closing-3-bay-area-stores-permanently-18390163.php` in Speedreader mode
5. clicked on the `Brave Leo` icon in the sidebar
6. confirmed `Brave Leo` opened
7. clicked on the `Brave Leo` icon on the top `Speedreader` toolbar

### Confirmed it snapped the `Brave Leo` sidebar pane closed


`Step 4`| `Step 5`| `Step 7`, before click | `Step 7`, after click
----------|----------|----------|-----------
![image](https://github.com/brave/brave-browser/assets/387249/6ddc8ec1-6291-457c-b124-397fae606c69) | ![image](https://github.com/brave/brave-browser/assets/387249/39d6d53c-d853-4bbd-9a23-282465f289d3) | ![image](https://github.com/brave/brave-browser/assets/387249/0d692fff-1bce-4b6a-a20c-d188370a461f) | ![image](https://github.com/brave/brave-browser/assets/387249/8a44322b-3cfb-4347-91bc-5864b67c62b0)
