### ISSUE TITLE
Send screen incorrectly lists NFTs with zero balance as valid options within the picker modal

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#32618]
## Description 

Send screen incorrectly shows insufficient balance error for NFTs

## Steps to Reproduce

   1. add an NFT asset that you do not own to the assets list
   2. go to send screen
   3. attempt select the NFT

## Actual result:
\
The token selection modal should not show assets that is not owned by an account
UI shows an insufficient funds error, cannot send NFT

## Expected result:
The NFT should not be a shown or selectable option

## Reproduces how often: 

Easy

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by josheleonard** [comment]
Fixed by: https://github.com/brave/brave-browser/issues/32618

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.124 Chromium: 127.0.6533.73 (Official Build) beta (64-bit)
-- | --
Revision | dbc9035349f74e493f3293d93f4cbf35c597dfec
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from issue description
- Verified Send button is not shown for unowned NFTs

https://github.com/user-attachments/assets/844e8d82-66e3-420e-a8c0-9db6991d8173
