### ISSUE TITLE
loading indicators stuck on buys

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#32623]
## Description 

Reported by @rebron that it happens on nightly and beta now (1.59 and 1.58) on desktop. I'm unable to reproduce right now. 

https://github.com/brave/brave-browser/assets/12224304/9a26ff2b-8e98-495a-9e57-d694fa2464d0

 
## Steps to Reproduce

Not able to reproduce
   1. 
   2. 
   3. 

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by Douglashdaniel** [comment]
May possibly be fixed by https://github.com/brave/brave-core/pull/19951 can have @rebron test once this PR makes it into the next `Nightly` build

**Comment by josheleonard** [comment]
@rebron , is this still occurring on nightly?

**Comment by josheleonard** [comment]
Closing, as this should be fixed via: https://github.com/brave/brave-core/pull/19951
