### ISSUE TITLE
Add EVM NFT owner address to NFT details screen

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#32622]
## Description 

We should show the NFT owner and token symbol in the NFT details screen

## Steps to Reproduce

   1. Import/restore a wallet with EVM NFTs
   2. go to the NFTs tab of the portfolio screen
   3. click on an EVM NFT
   4. observe the asset details

## Actual result:

The NFT's owner should is not displayed

## Expected result:
The NFT's owner should be displayed

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.70.107 Chromium: 128.0.6613.120 (Official Build) beta (64-bit)
-- | --
Revision | ab3f504ca4a15c330f60a93d5e3773d780498980
OS | Windows 11 Version 23H2 (Build 22631.4112)

- Verified steps from issue description
- Verified EVM NFT owner address is shown in NFT details screen

https://github.com/user-attachments/assets/324ed887-d46f-4a93-8d2f-a4759da4b5e6
