### ISSUE TITLE
Remove the assumption that sidebar item is always added as a last item

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#32637]
Now, new item is always added as a last item and UI code uses that assumption.
But, we could add item to any position soon.
Need to update UI to make it work regardless of newly added item's position.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.59.102 Chromium: 117.0.5938.140 (Official Build) beta (arm64)
-- | --
Revision | 11284b6d5d51252fe1a6fb6b5cba35ef98982357
OS | macOS Version 14.0 (Build 23A344)
```

**Comment by LaurenWags** [comment]
@simonhong looks like the item added bubble only displays for the first 3 items added to sidebar. Is that expected - or should that feedback bubble show each time an item is added to sidebar?
