### ISSUE TITLE
Allow Multiple Selection for Network Filters

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-browser#32644]
Allow selecting multiple networks in the Network selection screen for Portfolio tab and NFT tab along with:

- [x] Select and deselect all option
- [x] Close button
- [x] Show empty state with no assets (add description later once filter dialog is ready)
- [x] Update edit visible dialog to use all networks by default and remove passed single network

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.59.93 x64 Beta build
- Verified steps from [brave/brave-core#19959](https://github.com/brave/brave-core/pull/19959)
- Verified able to filter networks on both portfolio and NFT
- Verified when all networks are disabled empty state message is shown
- Verified selecting and closing the button updates the selections of networks
- Encountered [#33206](https://github.com/brave/brave-browser/issues/33206), [#33208](https://github.com/brave/brave-browser/issues/33208), [#33210](https://github.com/brave/brave-browser/issues/33210)

| Oppo Reno 5 (Android 13) | Lenovo Tab (Android 12)|
|--------|--------|
| <video src=https://github.com/brave/brave-browser/assets/17010094/b6220f19-88c7-42d7-a09b-a283a3821d37>| <video src=https://github.com/brave/brave-browser/assets/17010094/1d9b748d-4712-4d5e-abb0-1577a28d6d94> |
