### ISSUE TITLE
[Follow up #31208]: Unable to load NFT details page for hidden NFTs

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#32646]
## Description 

[Follow up #31208]: Unable to load NFT details page for hidden NFTs

## Steps to Reproduce

   1. Hide an NFT
   2. Click on the hidden NFT
   3. Goes back to NFT page instead of loading the NFT details page

## Actual result:

https://github.com/brave/brave-browser/assets/17010094/a3072a82-3be0-41e3-9fc8-bd3236e81790

## Expected result:
Should load the NFT details page

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.58.109 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | a4ad1fcdb550daf076384dbb280ae944274b3d35
OS | Windows 11 Version 22H2 (Build 22621.2215)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel

**Comment by kjozwiak** [comment]
The above requires `1.58.113` or higher for `1.58.x` verification 👍

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.58.109 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Linux

- Verified steps from [brave/brave-core#19961](https://github.com/brave/brave-core/pull/19961)
- Verified selecting hidden NFT loads the NFT details page

https://github.com/brave/brave-browser/assets/17010094/c7f4ee4c-a485-4401-8522-a1bc6890f6cf



---------------------

**Verification passed on**

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build)) beta (64-bit)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from [brave/brave-core#19961](https://github.com/brave/brave-core/pull/19961)
- Verified selecting hidden NFT loads the NFT details page

https://github.com/brave/brave-browser/assets/17010094/be27e39c-d705-4925-8202-2ffa87581ea8


---------------------

**Verification passed on**

Brave | 1.57.27 Chromium: 115.0.5790.114 (Official Build) beta (arm64)
-- | --
Revision | `21631edab5a70964c2f5817bfa4d06c32b4ab314`
OS | macOS Version 13.4.1 (c) (Build 22F770820d)

- Verified steps from [brave/brave-core#19961](https://github.com/brave/brave-core/pull/19961)
- Verified selecting hidden NFT loads the NFT details page

https://github.com/brave/brave-browser/assets/17010094/c4e9a39a-6f2c-421a-a724-481794588292
