### ISSUE TITLE
[Android] Submit shields report with origin + path

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#32640]
## Description 
This is to submit shields report with url instead of domain

## Steps to reproduce 

   1. open shields panel
   2. Have `Brave shields` DOWN
   3. Tap on `Report a broken site`
   4. Submit the report

## Actual result 
Currently we submit domain for the broken site

## Expected result
We should submit full url for the broken site

## Issue reproduces how often 
Easily

## Version/Channel Information:

All
- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.59.124` or higher for `1.59.x` verification 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Pixel 6` running `Android 14` using the following build(s):

```
Brave | 1.59.124 Chromium: 118.0.5993.117 (Official Build) (64-bit)
--- | ---
Revision | 63d57e32ce0ff0a1e380461bc394351e97d1416a
OS | Android 14; Build/U1B2.230922.010; 34; REL
```

Using the STR/information from https://github.com/brave/brave-core/pull/19958#issuecomment-1778362473, went through the following:

**`Quick Note:`** Still having the network/DB issues re: `500 internal error` as mentioned via https://github.com/brave/brave-core/pull/19958#issuecomment-1778362473 and discussed via https://bravesoftware.slack.com/archives/C03MMJ4CHEZ/p1698199867211709.

**`Example`** | **`Example`**
----------------|-----------------
![Screenshot_20231025-113132](https://github.com/brave/brave-browser/assets/2602313/9a2fd535-6e5e-40ec-9517-72c397667e65) | ![Screenshot 2023-10-25 at 11 36 35 AM](https://github.com/brave/brave-browser/assets/2602313/be883021-ae18-4c2a-b9af-b5ac0bbb4981)
