### ISSUE TITLE
Set focus to AI chat when the sidebar button is clicked

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#32650]
## Description 

Set focus to AI chat when the sidebar button is clicked

## Steps to Reproduce

   1. Click Leo AI chat button in sidebar
   2. Focus is not set to the input

## Actual result:

Focus is not set to the AI chat box when the sidebar button is clicked

## Expected result:
Set focus to AI chat when the sidebar button is clicked

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.59.56 Chromium: 116.0.5845.114 (Official Build) nightly (64-bit)
-- | --
Revision | 11676eb8c4bf058787c740d5fd2d089971f5d942
OS | Windows 11 Version 22H2 (Build 22621.2215)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @nullhook

**Comment by stephendonner** [comment]
## Verification `PASSED` using 

```
Brave | 1.60.60 Chromium: 117.0.5938.92 (Official Build) nightly (64-bit)
-- | --
Revision | 9a4644344a53150ebad5406037a6463714787348
OS | Windows 10 Version 22H2 (Build 19045.3516)
```

### Steps:
1. installed `1.60.60`
2. launched Brave
3. restarted (to pick up Griffin seed)
4. clicked on the `Brave Leo` icon in the sidebar
5. clicked again to collapse the `Leo` pane
6. clicked again on `Brave Leo` to open the pane in the sidebar

### Confirmed the focus was set to the caret on the `Enter a prompt here` textfield

example | example | example | example
----------|----------|----------|-----------
![image](https://github.com/brave/brave-browser/assets/387249/7296ce45-40f0-40f2-b0fb-aa4ef89a7ff5) | ![image](https://github.com/brave/brave-browser/assets/387249/27e9ef42-c56b-480e-b7a2-e3124f25a576) | ![image](https://github.com/brave/brave-browser/assets/387249/29f2f0aa-6f92-40e4-916c-3ed2d3c12bd8) | ![image](https://github.com/brave/brave-browser/assets/387249/68ea9a27-fd74-4cb5-9092-1e42bb58e57c) | ![image](https://github.com/brave/brave-browser/assets/387249/995da771-63d5-49f8-80e5-46e89af2fb02)
