### ISSUE TITLE
[Bug Report] Infinite Function Calling Stacks due to Adblock feature enabled for YouTube

### ISSUE THREAD

**Issue by cyfung1031** [brave/brave-browser#32658]
I found this issue as there is sometimes popup the maximum stack error in the console log which I am feeling bad to it.

I found that it is because of this section.

https://github.com/brave/uBlock/blob/master/assets/resources/scriptlets.js#L136-L148

```js

  function getExceptionToken() {
    const token =
        String.fromCharCode(Date.now() % 26 + 97) +
        Math.floor(Math.random() * 982451653 + 982451653).toString(36);
    const oe = self.onerror;
    self.onerror = function(msg, ...args) {
        if ( typeof msg === 'string' && msg.includes(token) ) { return true; }
        if ( oe instanceof Function ) {
            return oe.call(this, msg, ...args);
        }
    }.bind();
    return token;
}
```
https://github.com/brave/uBlock/blob/master/assets/resources/scriptlets.js#L830-L872
```js
function matchesStackTrace(
    needleDetails,
    logLevel = 0
) {
    const safe = safeSelf();
    const exceptionToken = getExceptionToken();
    const error = new safe.Error(exceptionToken);
    const docURL = new URL(self.location.href);
    docURL.hash = '';
    // Normalize stack trace
    const reLine = /(.*?@)?(\S+)(:\d+):\d+\)?$/;
    const lines = [];
    for ( let line of error.stack.split(/[\n\r]+/) ) {
        if ( line.includes(exceptionToken) ) { continue; }
        line = line.trim();
        const match = safe.RegExp_exec.call(reLine, line);
        if ( match === null ) { continue; }
        let url = match[2];
        if ( url.startsWith('(') ) { url = url.slice(1); }
        if ( url === docURL.href ) {
            url = 'inlineScript';
        } else if ( url.startsWith('<anonymous>') ) {
            url = 'injectedScript';
        }
        let fn = match[1] !== undefined
            ? match[1].slice(0, -1)
            : line.slice(0, match.index).trim();
        if ( fn.startsWith('at') ) { fn = fn.slice(2).trim(); }
        let rowcol = match[3];
        lines.push(' ' + `${fn} ${url}${rowcol}:1`.trim());
    }
    lines[0] = `stackDepth:${lines.length-1}`;
    const stack = lines.join('\t');
    const r = safe.testPattern(needleDetails, stack);
    if (
        logLevel === 1 ||
        logLevel === 2 && r ||
        logLevel === 3 && !r
    ) {
        safe.uboLog(stack.replace(/\t/g, '\n'));
    }
    return r;
}
```

which is applied to every `JSON.parse` due to the calling of function `objectPrune`.

## Root Cause

1st `JSON.parse` => `objectPrune` => `matchesStackTrace` => `getExceptionToken`: `OE = hackedOE (wrapping originalOE)`
2nd `JSON.parse` => `objectPrune` => `matchesStackTrace` => `getExceptionToken`: `OE = hackedOE_1 (wrapping hackedOE)`
3rd `JSON.parse` => `objectPrune` => `matchesStackTrace` => `getExceptionToken`: `OE = hackedOE_2 (wrapping hackedOE_1)`
...
(N+1)th `JSON.parse` => `objectPrune` => `matchesStackTrace` => `getExceptionToken`: `OE = hackedOE_N (wrapping hackedOE_(N-1))`

```js
    self.onerror = function(msg, ...args) {
        if ( typeof msg === 'string' && msg.includes(token4) ) { return true; }
        if ( oe4 instanceof Function ) {
                return (function oe4(msg, ...args) {
                    if ( typeof msg === 'string' && msg.includes(token3) ) { return true; }
                    if ( oe3 instanceof Function ) {
                              return (function oe3(msg, ...args) {
                                  if ( typeof msg === 'string' && msg.includes(token2) ) { return true; }
                                  if ( oe2 instanceof Function ) {
                                          return (function oe2(msg, ...args) {
                                              if ( typeof msg === 'string' && msg.includes(token1) ) { return true; }
                                              if ( oe1 instanceof Function ) {
                                                        return (function oe1(msg, ...args) {
                                                            if ( typeof msg === 'string' && msg.includes(token) ) { return true; }
                                                            if ( oe instanceof Function ) {
                                                                return oe.call(this, msg, ...args);
                                                            }
                                                        }.bind()).call(this, msg, ...args);
                                              }
                                          }.bind()).call(this, msg, ...args);
                                  }
                              }.bind()).call(this, msg, ...args);
                    }
                }.bind()).call(this, msg, ...args);
        }
    }.bind();
```

## Solution

1. For live chat, there shall be no ads. no need to detect inside live_chat pages. (`https://www.youtube.com/live_chat*`)
2. Whenever there is a `JSON.parse` call, it creates a new onerror function enclosing the original function and just detect one token tag.
3. The current implementation will detect infinitely many token tags. However I cannot find out why you need this detection. `new Error(...)` without `throw` would not cause firing `onerror`. Basically you can just remove the `onerror` hack.
4. If you really wants to do the hack, you should just hack at the first time, and create a Set to store all the listening tokens.

```js

function getExceptionToken() {
    const token =
        String.fromCharCode(Date.now() % 26 + 97) +
        Math.floor(Math.random() * 982451653 + 982451653).toString(36);
    const oe = self.onerror;
    if (oe && oe.__tokenSet__) {
        oe.__tokenSet__.add(token);
        return token;
    }
    const tokenSet = new Set([token]);
    self.onerror = function (msg, ...args) {
        if (typeof msg === 'string') {
            for (const token of tokenSet) {
                if (msg.includes(token) return true;
            }

        }
        if (oe instanceof Function) {
            return oe.call(this, msg, ...args);
        }
    }.bind();
    self.onerror.__tokenSet__ = tokenSet;
    return token;
}

```

5. But still there is no size control of the tokenSet. 
6. I think you just need (or even not need) to detect the last token right? So 
```js
    if (oe && oe.__tokenSet__) {
        oe.__tokenSet__.clear();
        oe.__tokenSet__.add(token);
        return token;
    }
```

## Related Issues

https://github.com/brave/brave-browser/issues/31098, https://github.com/brave/adblock-rust/issues/296

## Files to be fixed

Files to be changed based on https://github.com/search?q=org%3Abrave%20982451653&type=code

https://github.com/brave/uBlock/blob/master/src/web_accessible_resources/popads.js
https://github.com/brave/uBlock/blob/master/assets/resources/scriptlets.js
https://github.com/brave/adblock-rust/blob/master/data/test/fake-uBO-files/web_accessible_resources/popads.js

## Remarks

I have checked that **uBlock Origin 1.51.0** would not do the same hacking to `JSON.parse`, and `window.onerror` would not get modified in YouTube.

### Related Issues

* https://github.com/brave/brave-browser/issues/32665
* https://github.com/brave/brave-browser/issues/32660

**Comment by cyfung1031** [comment]
As a bug report, I would like to show you how to reproduce it as a bug.

Open https://www.youtube.com/robots.txt in normal window (not Private Window)

open DevTools to execute following:

```js
window.onerror=function(){ console.warn(arguments) };
for(let i =0;i< 1e5;i++) JSON.parse("{}");
setTimeout(`JSON.parse("CRASH");`);
```

### Incorrect Result (Brave)

<img width="751" alt="Screen Shot 2023-09-01 at 15 26 28" src="https://github.com/brave/brave-browser/assets/44498510/2bea13a3-52b0-4031-9085-4bd68b58a481">



## Correct Result (Chrome + uBlock Origin enabled)

<img width="743" alt="Screen Shot 2023-09-01 at 15 28 08" src="https://github.com/brave/brave-browser/assets/44498510/b2e8066b-d4d1-446a-b5b0-8a8b2556652d">


## Remarks
Apart from the the stack size, the execution of JSON.parse is much slower than the original since the code hacking.
This does not happen in Chrome + uBlock Origin.

**Comment by ryanbr** [comment]
cc @antonok-edm

**Comment by antonok-edm** [comment]
@cyfung1031 can you check again? I wasn't able to reproduce the issue; I believe this was fixed upstream in uBlock Origin.

**Comment by cyfung1031** [comment]
No longer reproducible.

**Comment by cyfung1031** [comment]
> @cyfung1031 can you check again? I wasn't able to reproduce the issue; I believe this was fixed upstream in uBlock Origin.

The issue comes back after i checked and unchecked the filter lists

brave://settings/shields/filters

It should be reproducible after checking the filter lists (e.g. EasyList Cookie)
