### ISSUE TITLE
Add additional details to webcompat report

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#32661]
Append the following additional details to each webcompat report:

- Brave VPN status at the time of the report
- List of enabled built-in ad block filter lists
- Tracker & adblock setting for the site, or the global setting
- Fingerprint setting for the site, or the global setting
- `Accept-Language` farbling setting
- List of user-configured languages, ordered by priority

Update the reporter disclaimer text to include the above.

**Comment by pes10k** [comment]
> Tracker & adblock setting for the site, or the global setting
> Fingerprint setting for the site, or the global setting

These should just be the version applicable to the site being reported.  I think thats what the above is saying, but just wanted to make certain

**Comment by kjozwiak** [comment]
The above requires `1.59.110` or higher for `1.59.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave | 1.59.111 Chromium: 118.0.5993.21 (Official Build) (64-bit)
-- | --
Revision | 73a6c272e4eec308fc7e9badfca4b49bdf068c59
OS | Windows 10 Version 22H2 (Build 19045.3448)

```
