### ISSUE TITLE
YT publisher loses an icon on rewards panel after accessed over other url. Observed on Android.

### ISSUE THREAD

**Issue by gdregalo** [brave/brave-browser#3266]
Here is a situation observed on Android.

A media publisher can be accessed over several URLs, for example:
`https://www.youtube.com/channel/UCtsfHRe2WQnkNH5WYJWL-Yw/videos`
`https://www.youtube.com/user/nickvonpentz/videos`

When browsing a page over first url, the `BatPublishers::saveVisitInternal` through
`RewardsServiceImpl::FetchFavIcon` fetches an icon and maps it on a custom url like "https://GUID.invalid" in FaviconService internal database Favicons.
When accessing the same publisher over second url, the same situation happens as above, but FaviconService doesn't download the icon because it's already saved and  
`RewardsServiceImpl::OnSetOnDemandFaviconComplete` returns `false` which echoes in `BatPublishers::onFetchFavIcon` as `Missing or corrupted favicon file for` error.
The above clears database field at `publisher_info_db.publisher_info.favIcon`. 

Fixed in: https://github.com/brave/brave-core/pull/1610

## Steps to Reproduce

   1. 
   2. 
   3. 

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by NejcZdovc** [comment]
closing as this was fixed
