### ISSUE TITLE
Add Sidebar enabled P3A metric

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#32662]
Add P3A metric for Sidebar enabled status, only reported for active sidebar users.

Do you have the Sidebar setting set to "Always" or "On mouseover"?

1. Yes

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.59.90 Chromium: 117.0.5938.88 (Official Build) beta (64-bit)
-- | --
Revision | 5272112c86588e44ec7c0b766c318cddccbced85
OS | Windows 10 Version 22H2 (Build 19045.3448)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/19967

<details>
<summary>Brave.Sidebar.Enabled = Always_PASSED</summary>

1. Clean profile 1.59.x
2. Open brave://settings
3. Confirmed that the `Always` sidebar settings is selected by default
4. Open brave://local-state file and ensured that the metrics `Brave.Sidebar.Enabled` response value is `1` as expected


Example | Example 
----------|-----------
![image](https://github.com/brave/brave-browser/assets/38657976/cd6fc537-6c80-41f2-baf1-def693ff1ab8) | ![image](https://github.com/brave/brave-browser/assets/38657976/b88c1100-d7cd-49f2-9441-7b46ad2a6374)

</details>


<details>
<summary>Brave.Sidebar.Enabled = On mouseover_PASSED</summary>

1. Clean profile 1.59.x
2. Open brave://settings
3. Select `On mouseove` sidebar settings from the `Show Sidebar` dropdown
4. Open brave://local-state file and ensured that the metrics `Brave.Sidebar.Enabled` response value is `1` as expected

Example | Example 
----------|-----------
![image](https://github.com/brave/brave-browser/assets/38657976/0e19591d-a7b3-4a27-94e6-6d8045d5ea1b) | ![image](https://github.com/brave/brave-browser/assets/38657976/a965dc65-17b4-4c32-b55d-35ea250ca075)


</details>

<details>
<summary>Brave.Sidebar.Enabled = Never_Metrics not shown_PASSED</summary>

1. Clean profile 1.59.x
2. Open brave://settings
3. Select `Never` sidebar settings from the `Show Sidebar` dropdown
4. Open brave://local-state file and ensured that the metrics `Brave.Sidebar.Enabled` is NOT shown

Example | Example 
----------|-----------
![image](https://github.com/brave/brave-browser/assets/38657976/0c820e67-6d26-41c4-96ea-50b88fa2b418) | ![image](https://github.com/brave/brave-browser/assets/38657976/d1a791a1-52ed-4a43-9f36-361f0e444286)

</details>
