### ISSUE TITLE
search icon in history tab is not visible in light mode 

### ISSUE THREAD

**Issue by kantakshay** [brave/brave-browser#32663]
## Description 

In light mode, while trying to delete history the search icon is not visible after selecting (checking) any history page. the search icon is available but only the icon color and the background color are similar, It is difficult to identify the search icon

## Steps to Reproduce

   1. Click on the history tab
   2. Check on any history page 
   3. You will see a delete button on the top right side of the screen
   4. Besides the delete button you will get a search option but it is not visible

## Actual result:

[brave light mode issue.webm](https://github.com/brave/brave-browser/assets/84266746/00545854-ca7c-4c3b-9406-55c7c86412f9)

## Brave version (brave://version info)

[Version 1.57.53 Chromium: 116.0.5845.114 (Official Build) (64-bit)](https://brave.com/latest/)
 Windows 10 

```[tasklist]
### Tasks
```

**Comment by rebron** [comment]
Closing as stale. The search icon has been removed and should not have been there next to the delete button in the first place.
