### ISSUE TITLE
Added custom tokens has the token icon stretched

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#32666]
## Description 

Added custom tokens has the token icon stretched

## Steps to Reproduce

   1. Add a custom token
   2. Open portfolio
   3. Token icon is stretched

## Actual result:

![image](https://github.com/brave/brave-browser/assets/17010094/55d19113-44ab-4085-b5a5-a10122db0fc3)

## Expected result:
Icon should be of proper size

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.58.109 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | a4ad1fcdb550daf076384dbb280ae944274b3d35
OS | Windows 11 Version 22H2 (Build 22621.2215)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Not checked

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @josheleonard @Douglashdaniel

**Comment by Douglashdaniel** [comment]
Was fixed via https://github.com/brave/brave-core/pull/19975 closing as `duplicate`
