### ISSUE TITLE
Data-URI Images not displayed correctly in Edit Visible Assets modal

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#32676]
## Description 

Data-URI Images not displayed correctly in Edit Visible Assets modal

## Steps to Reproduce

   1. Add an EVM NFT (with a "data" URI) to visible assets  (https://goerli-nfts.vercel.app/)
   2. Load the edit visible assets modal

## Actual result:

Asset icon image is broken

## Expected result:
Asset icon should be shown

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.59.115 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | `82b05012fc6b5ab8535cf283db6856ad5eedd7eb`
OS | Windows 11 Version 22H2 (Build 22621.2283)

- Verified steps from issue description
- Verified NFTs added from `https://goerli-nfts.vercel.app/)` shows image in edit visible assets list

https://github.com/brave/brave-browser/assets/17010094/4fdf7529-0c95-4b0e-b52e-84072182cd30

---------------------

**Verification passed on**

Brave | 1.59.115 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | `82b05012fc6b5ab8535cf283db6856ad5eedd7eb`
OS | Linux

- Verified steps from issue description
- Verified NFTs added from `https://goerli-nfts.vercel.app/)` shows image in edit visible assets list

https://github.com/brave/brave-browser/assets/17010094/0bb6e10e-40f2-4fde-b08d-9667eb7ff6e0


---------------------

**Verification passed on**

Brave | 1.59.115 Chromium: 118.0.5993.54 (Official Build) (arm64)
-- | --
Revision | `82b05012fc6b5ab8535cf283db6856ad5eedd7eb`
OS | macOS Version 14.0 (Build 23A344)

- Verified steps from issue description
- Verified NFTs added from `https://goerli-nfts.vercel.app/)` shows image in edit visible assets list

https://github.com/brave/brave-browser/assets/17010094/82de9bce-eb1e-480a-8da5-eb54c591429d
