### ISSUE TITLE
Follow up: Capitalize `Speedreader` text where needed

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#32677]
## Description 

Follow up to https://github.com/brave/brave-core/pull/19715.  Speedreader text should be capitalized where required

## Steps to Reproduce

   1. Install 1.59.62
   2. launch Brave
   3. navigate to an Speedreader capable article 
   4. mouseover on Speedreader button in the address bar

## Actual result:

<img width="959" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/75cb5301-78d9-4a8b-aac3-3c9937c3accb">

## Expected result:
Turn on speedreader text should be `Turn on Speedreader` 

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.59.62 Chromium: 116.0.5845.163 (Official Build) nightly (64-bit)
-- | --
Revision | 0018a11e701393659831fe88dea09e0d53b21840
OS | Windows 11 Version 22H2 (Build 22621.2134)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
@rebron @boocmp

**Comment by yehoki** [comment]
I am not completely sure but I think this is the line it's talking about:

`<message name="IDS_SPEEDREADER_ICON_TURN_ON_READER_MODE" desc="Accessible text shown when a page can be distilled">Turn on speedreader</message>`

Found it in https://github.com/brave/brave-core/blob/530486f348333445b616e19ba8162d0852dcbf93/components/resources/speedreader_strings.grdp

**Comment by mkarolin** [comment]
Thank you for fixing, @yehoki.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 


```
Brave | 1.60.81 Chromium: 118.0.5993.54 (Official Build) beta (x86_64)
-- | --
Revision | 1efb3f333eb41cc34af46ca31fb33c30e0afbfae
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.60.81`
2. launched Brave
3. loaded `https://www.usatoday.com/story/news/politics/2023/10/06/kevin-mccarthy-house-speaker-gop-government-shutdown/71076602007/`
4. hovered the mouse over the newspaper-looking option in the URL bar
5. confirmed it read `Turn on Speedreader`
6. clicked on it
7. confirmed the page rendered in Speedreader
8. hovered the mouse over the newspaper-looking option in the URL bar
9. confirmed it read `Turn off Speedreader`

`Turn on Speedreader` | `Turn off Speedreader`
------------------------|----------------------
<img width="1569" alt="Screen Shot 2023-10-06 at 2 24 25 PM" src="https://github.com/brave/brave-browser/assets/387249/4c07f714-9b42-4e6d-8652-a32273282159"> | <img width="1566" alt="Screen Shot 2023-10-06 at 2 23 54 PM" src="https://github.com/brave/brave-browser/assets/387249/3df82e41-73e3-431e-ab27-c896f00fe2a8">
