### ISSUE TITLE
Placeholder Icons are Smushed in Edit Visible Asset modal

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#32680]
## Description 

`Placeholder` Icons are being smushed in the `Edit Visible Asset` modal

## Steps to Reproduce

   1. Add a custom token without an Icon
   2. Go to the `My Assets` tab and search for you custom token
   3. The `Icon` is smushed

## Actual result:

![Screenshot 59](https://github.com/brave/brave-browser/assets/40611140/64b6b9cd-cea8-49dc-bc71-09f0632fd3f5)

## Expected result:

![Screenshot 58](https://github.com/brave/brave-browser/assets/40611140/851ad4b4-05ac-4c57-ac7c-6f78927753d5)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.59.115 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | `82b05012fc6b5ab8535cf283db6856ad5eedd7eb`
OS | Windows 11 Version 22H2 (Build 22621.2283)

- Verified steps from [brave/brave-core#19975](https://github.com/brave/brave-core/pull/19975)
- Verified custom tokens icon is shown properly
![brave_iycYFRxAJN](https://github.com/brave/brave-browser/assets/17010094/8374aef5-078a-49e2-a420-a7cada6f7ae4)

---------------------

**Verification passed on**

Brave | 1.59.115 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | `82b05012fc6b5ab8535cf283db6856ad5eedd7eb`
OS | Linux

- Verified steps from [brave/brave-core#19975](https://github.com/brave/brave-core/pull/19975)
- Verified custom tokens icon is shown properly
![Customtoken](https://github.com/brave/brave-browser/assets/17010094/8252d78e-7e87-462f-9c8a-ce1ff77b524f)

---------------------

**Verification passed on**

Brave | 1.59.115 Chromium: 118.0.5993.54 (Official Build) (arm64)
-- | --
Revision | `82b05012fc6b5ab8535cf283db6856ad5eedd7eb`
OS | macOS Version 14.0 (Build 23A344)

- Verified steps from [brave/brave-core#19975](https://github.com/brave/brave-core/pull/19975)
- Verified custom tokens icon is shown properly
![image](https://github.com/brave/brave-browser/assets/17010094/0b0daf39-c10d-43f1-9dbd-5f7bb7e58392)
