### ISSUE TITLE
pending BAT (for unverified creators) doubled when it shouldn't have

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#3268]
## Description 
On my personal dev channel profile I've hit a state where my rewards auto contribution appears to be in retries. No real BAT has left my wallet, but I got the message on brave://rewards that 19.6 BAT designated for creators who have not yet signed up (pending BAT). This value is accurate. I noticed a bit later that this number had gone up to 39.2. It seems as though the "pending" BAT has doubled during retries. 

## Steps to Reproduce
TBD - still trying to reproduce

General description of scenario - was waiting for auto contribute to occur yesterday (2/6) when I noticed today (2/7) that it didn't go thru. Saw 19.6 pending BAT on brave://rewards and that my wallet balance had not lowered. Looked at ledger_state and saw `"retry_step":3,"retry_level":3`. Later on I looked at brave://rewards again and saw 39.2 BAT. My ledger state had a second retry entry which said `"retry_step":3,"retry_level":0`.

## Actual result:
![screen shot 2019-02-07 at 4 16 42 pm](https://user-images.githubusercontent.com/28145373/52447595-278ba100-2aff-11e9-8234-4fbdc5805763.png)

## Expected result:
I didn't grab a screenshot from before since I didn't expect it to double, but it used to say 19.6 (which was the correct amount of pending BAT).

## Reproduces how often: 
Unsure

## Brave version (brave://version info)

Brave | 0.61.10 Chromium: 72.0.3626.81 (Official Build) dev(64-bit)
-- | --
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? experienced on Dev

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by LaurenWags** [comment]
Reproduced with these STR once, will try to get better steps:
1. Install 0.60.17 dev and launch with `--rewards=staging=true,reconcile-interval=10` (or shorter if you can work quickly)
2. Enable rewards and visit some sites (I visited 2 verified and 2 non-verified)
3. Visit brave://settings/help and update the browser.
4. Don't relaunch, just close Brave Dev. 
5. Locate ledger_state and find `reconcileStamp` value, note this value.
6. Launch from terminal with same flags as step 1.
7. You will encounter https://github.com/brave/brave-browser/issues/3250
8. Quickly add some sites to the table (you may encounter https://github.com/brave/brave-browser/issues/3254)
9. Open epochconverter.com in another window.
10. 1s before auto contribute is scheduled, turn off wifi. This should put you into retries.
11. You should see the pending BAT listed on brave://rewards:
<img width="609" alt="screen shot 2019-02-07 at 6 24 56 pm" src="https://user-images.githubusercontent.com/28145373/52452282-6d9d3080-2b10-11e9-99d5-37d2a0046520.png">
12. I waited 1 hr for the retry and turned off wifi 1s before retry was supposed to occur. This didn't cause the pending BAT to double.
13. I then closed and relaunched Brave again (with same command line flags) and at this point, the pending BAT doubled:
![doublependingbat](https://user-images.githubusercontent.com/28145373/52452457-00d66600-2b11-11e9-8b43-9bdc860d4a9d.png)

That's a lot of steps and waiting, I will try to get better/shorter steps.

**Comment by NejcZdovc** [comment]
@LaurenWags so at the beginning of AC contribution we check % and for publishers that are unverified we put them into pending table then we start contribution for verified. So unverified will never go into retries and will be logged first

**Comment by LaurenWags** [comment]
Then I'm not sure what caused the pending BAT to double, but it shouldn't have. I'll update the title.

**Comment by NejcZdovc** [comment]
@LaurenWags still a problem?

**Comment by LaurenWags** [comment]
Tried to reproduce on Nightly 5x, but was unable to do so. Will close for now and reopen if I encounter again.
