### ISSUE TITLE
`Help tips` for locale language simplified Chinese is incorrect

### ISSUE THREAD

**Issue by lovebigbear** [brave/brave-browser#32683]
## Description 

Help tips on simplified Chinese-"支助赏金“ is wrong， it should be “帮助提示” for Help tips on locale language simplified Chinese

## Expected result:

it should be “帮助提示” for "Help tips" on locale language simplified Chinese

## Brave version (brave://version info)

[Version 1.57.57 Chromium: 116.0.5845.163 (Official Build) (arm64)](https://brave.com/latest/)

**Comment by lovebigbear** [comment]
This bug exists on both Windows and Mac platforms

**Comment by mkarolin** [comment]
The string in question is no longer in the code base. Closing, as this is not actionable any more.
