### ISSUE TITLE
Daily & monthly News usage metrics are overestimated

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#32685]
Daily & monthly News usage metrics (`Brave.Today.UsageDaily` and `Brave.Today.UsageMonthly`) are not working correctly. Currently, the metrics are recorded when the NTP page is shown for users with News enabled, even if the user does not scroll down to view the feed.

**Comment by kjozwiak** [comment]
The above requires `1.58.117` or higher for `1.58.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.58.117`
