### ISSUE TITLE
does brave use 32bit date for certificate validation?

### ISSUE THREAD

**Issue by Basti77** [brave/brave-browser#32687]
I own a Bosch Indigo robotic lawnmower.
There was another app update and suddenly I could no longer log in with my account.
I think this app uses the system browser of the device in the background.
I have only installed Brave.
During my research I noticed that for this login CA certificates are used that are valid until 2042. but the end of the 32 bit time is 2038.
I reinstalled Chrome and set it as the default and it worked.

now the question is what is the reason that it does not work with brave and that it works with chrome?

## Steps to reproduce 

   1.  Own a Bosch Indigo 
   2.  Android 13 Handy
   3. 

## Actual result 

<img width="270" alt="Screenshot_20230830-155202" src="https://github.com/brave/brave-browser/assets/8112783/cc3d6086-ad58-48cc-ad16-3c0b8d5aacfd">

<img width="270" alt="Screenshot (02 09 2023 11_40_51) 2023 11_40_51)" src="https://github.com/brave/brave-browser/assets/8112783/0aba0480-277b-4306-8bcd-acc32b3ace6b">

## Expected result

64bit date format?
Using the bosh app without Crome installed

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? yes
- Can you reproduce this issue with the current Play Store Beta version?  yes
- Can you reproduce this issue with the current Play Store Nightly version? dont try

## Device details
   - Install type (ARM, x86): Sony XQ-cc54
   - Device type (Phone, Tablet, Phablet): Phne
   - Android version: 13
   
## Brave version
1.57.53

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome?  no

**Comment by diracdeltas** [comment]
cc @SergeyZhukovsky, there shouldn't be any difference between brave and chrome WRT cert validation on android

**Comment by Basti77** [comment]
And what can be different about brave that it only works with Chrone?

**Comment by SergeyZhukovsky** [comment]
I don't think we ever changed anything related to that. @Basti77 could you confirm that you see the same behaviour on the latest Brave version? Also by there was an app update do you mean Brave's update or the login page forwards you to some kind of a Bosch app? We had a bug recently that prevents users to open apps links which we fixed in `1.57.60`. Could you please check it out? https://github.com/brave/brave-browser/issues/32586

**Comment by Basti77** [comment]
Yesterday I was able to do a test. (the lawn mower was deactivated because it is much too warm to mow at the moment). 

Before the test I uninstalled Chrome and restarted the phone. 

the last update also fixed this problem. 

thanks for your time and help.
