### ISSUE TITLE
Add "new tab" customization

### ISSUE THREAD

**Issue by leobel96** [brave/brave-browser#3269]
Actually the user can only choose between the default new tab, continue from where he left or open a page chosen by the user. In my opinion the user should have the possibility to deeper customize the default "new tab" adding a search bar, hiding the websites tiles, choosing the backgrounds source, the colors palette, the elements position, ...

**Comment by Liunkae** [comment]
Duplicate of #353

**Comment by leobel96** [comment]
Oh, sorry. I've looked for something similar before opening the issue but I haven't seen it :(
