### ISSUE TITLE
Add premium badge for Leo

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#32696]
Show premium "PREMIUM" badge for users who are subscribed to the premium subscription. This is a non-interactive element.

<img width="326" alt="image" src="https://github.com/brave/brave-browser/assets/8665427/858beea7-a1af-45d7-acb1-92e848337647">

[Figma](https://www.figma.com/file/h7fKSJF2P556bZWfyLTfwD/Brave-Leo?type=design&node-id=3877-19868&mode=design&t=Hpq87kyErleqnzul-0)

**Comment by aguscruiz** [comment]
@bbondy @petemill At one point we decided not to show that the user was using the "free" version of Leo besides the feature name. 

We instead have a premium entry point from the main menu. If users click this, they would be taken to the premium flow

<img width="442" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/11174979-f206-42bd-b902-72a8747e14f8">

Do we want to close this issue?

**Comment by nullhook** [comment]
<img width="341" alt="image" src="https://github.com/brave/brave-browser/assets/8665427/be8a694a-6b59-48cf-bf96-bac6c3177fdb">

Rather than an interactive button I guess we've decided to show a badge? Maybe the issue can be updated with the above design?

**Comment by nullhook** [comment]
I have updated the PR's description.

**Comment by stephendonner** [comment]
So, this shows up by default for all users:.

![image](https://github.com/brave/brave-browser/assets/387249/342fc89b-268b-4ba3-8675-7d5360da0ac4)

Isn't this badge **still** supposed to be dynamic?  If so, we shouldn't be showing it by default to non-Premium subscribed/logged-out usrs.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.60.106 Chromium: 119.0.6045.59 (Official Build) (64-bit)
-- | --
Revision | 16064193dde8c55f64dabd32f125c0cd9380f96a
OS | Windows 11 Version 22H2 (Build 22621.2506)
```

Ensured that the `PERMIUM` bade is being displayed in the correct instances as per the following:

### Using `non-premium`/default installation without account:

**`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------|-----------------
![image](https://github.com/brave/brave-browser/assets/2602313/c7f67c2e-ad4d-455c-8a33-c2548b28e28f) | ![image](https://github.com/brave/brave-browser/assets/2602313/00d30709-05b4-4905-bb35-71e8c87bb821) | ![image](https://github.com/brave/brave-browser/assets/2602313/dd15e18f-0224-4d05-a499-84d6ecbee7a9) | ![image](https://github.com/brave/brave-browser/assets/2602313/d769a98c-3dde-485e-b1f5-e491150c44c8)

### With `premium` account:

**`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------|-----------------
![image](https://github.com/brave/brave-browser/assets/2602313/49977615-0ffb-4a9b-8f1c-2fba843a1dd5) | ![image](https://github.com/brave/brave-browser/assets/2602313/1c1b091c-fa85-4446-bc75-00e6e269757f) | ![image](https://github.com/brave/brave-browser/assets/2602313/a50a1224-6f0d-41fe-85fc-e087aff27c3e) | ![image](https://github.com/brave/brave-browser/assets/2602313/86f8f46c-8669-4f5a-a490-17bd028f17bc)

**Comment by stephendonner** [comment]
> So, this shows up by default for all users:.

<snip>

For posterity, the above was address/fixed when https://github.com/brave/brave-core/pull/20245 landed.
