### ISSUE TITLE
Add premium indicator for Leo when no context is associated

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#32695]
- Show when there is no page context
- This should only show if the user has not purchased a premium account
- Stop showing completely forever if the user hits Dismiss
- Resetting the feature in settings should show it again if the user re-opts in

I think we don't need to add any logic to do it only 1 in X times because if the user hits Dismiss we'll stop showing it. 

See [Figma](https://www.figma.com/file/h7fKSJF2P556bZWfyLTfwD/Brave-AI?type=design&node-id=2726-12088&mode=design&t=LxtYravMo4zX7cRx-0) for the latest design, at the time of posting the design looks like this:

<img width="1014" alt="Screenshot 2023-09-03 at 4 51 03 PM" src="https://github.com/brave/brave-browser/assets/831718/a5233c21-bca9-426c-8067-a5ea9bb58708">

**Comment by aguscruiz** [comment]
Updated screenshot here:
![image](https://github.com/brave/brave-browser/assets/15734630/765caa85-39ee-409e-9063-db93a5522059)

**Comment by petemill** [comment]
This should also show when you select a premium model but aren't premium subscribed

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.60.109 Chromium: 119.0.6045.59 (Official Build) (64-bit)
-- | --
Revision | fc399c7c433510eb03c2b35281bf8935804b99de
OS | Windows 10 Version 22H2 (Build 19045.3636)
```

### Shared Steps:
<details>

1. installed `1.60.109`
2. launched Brave using `--env-leo=staging --env-ai-chat.bsg=dev --env-ai-chat-premium.bsg=dev --enable-logging=stderr --v=2`
3. set `Brave AI chat` in `brave://flags`
4. enabled the `Sidebar`
5. clicked on `Leo` in the sidebar
6. clicked `Accept and begin`
7. clicked to enable suggested questions

</details>
