### ISSUE TITLE
Link to premium subscription management for Leo in settings

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#32699]
This should only show if the user has a premium account.

See [Figma](https://www.figma.com/file/h7fKSJF2P556bZWfyLTfwD/Leo-MVP?type=design&node-id=1105-28709&mode=design&t=pfsii0NXgpmjbru2-0) for the latest design, at the time of posting the design looks like this:

<img width="786" alt="Screenshot 2023-09-03 at 5 06 51 PM" src="https://github.com/brave/brave-browser/assets/831718/4b3895ac-2086-49d1-a6de-ad57ba3a0165">

**Comment by petemill** [comment]
![Image](https://github.com/brave/brave-browser/assets/741836/593cd376-a9e7-4d23-a7d6-121a95a0931a)

**Comment by bbondy** [comment]
I think your comment should be moved to this issue? https://github.com/brave/brave-browser/issues/32698

**Comment by petemill** [comment]
@aguscruiz should we update the premium upsell here to better match the new version at https://github.com/brave/brave-core/pull/21717. Or maybe even just re-use the exact same code?

**Comment by stephendonner** [comment]
## Verified `PENDING` using

```
Brave | 1.66.81 Chromium: 124.0.6367.60 (Official Build) beta (x86_64)
-- | --
Revision | ee44f88609d4a72c5d0cb3305c5f340b6203a917
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Default, non-Premium user

### Premium user

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.66.86 Chromium: 124.0.6367.60 (Official Build) beta (64-bit)
-- | --
Revision | f454ab878a85c5d1395e830089a2cb0a1ce77c4e
OS | Windows 11 Version 23H2 (Build 22631.3527)
```
<details>
<summary> Case 1: Default, non-Premium user - `PASSED` </summary>

1. installed `1.66.86`
2. launched Brave
3. opened `brave://settings`
4. clicked on `Leo` (`brave://settings/leo-assistant`)
5. confirmed no `Manage premium subscription` link

![image](https://github.com/brave/brave-browser/assets/98358127/1469f9f1-56c9-420e-a7a9-9c9de2212271)
</details>

<details>
<summary>Case 2: Premium user - `PASSED` </summary>

1. continue from Case 1
     - Not logged in as premium user
2. opened `account.bravesoftware.com`
3. entered basic-auth username/password
4. logged in with existing Leo premium account  and clicked `Get login link`
5 clicked on the `Log in to Brave` link in the resulting email
clicked `Refresh Leo`  button
6. relaunched Brave with `--env-leo=staging --env-ai-chat.bsg=dev --env-ai-chat-premium.bsg=dev`
7. confirmed `Leo Premium` status
8. opened `brave://settings`
9. clicked on `Leo`

### Confirmed `Manage premium subscription` link opened `account.brave.com`

new Leo subscription| Light theme| subscription page| query with Leo | Dark theme
---------|----------|--------|----------|--------
![image](https://github.com/brave/brave-browser/assets/98358127/24b58c65-752b-4cf7-ae31-c4a54baa8ad7)|![image](https://github.com/brave/brave-browser/assets/98358127/22cd6990-e8f2-4f00-8ce3-fedf604af6fb)|![image](https://github.com/brave/brave-browser/assets/98358127/30f848d7-4dd6-4f32-98b3-d455bbe6f11d)|![image](https://github.com/brave/brave-browser/assets/98358127/a908a333-c503-452b-ac53-9a053dce86ed)|![image](https://github.com/brave/brave-browser/assets/98358127/b3fad6cb-8ecc-4c21-8261-fb4923d3e4c2)
</details>

<details>
<summary>Case 3: Upgrade - PASSED </summary>

1. Installed 1.65.122
2. launched Brave
3. logged into account.brave.com with basic-auth username/password
4. logged in with existing leo subscription 
5. opened `brave://settings/leo-assistant`
6. verified `Manage premium subscription` option is not shown
7. closed the browser
8. renamed the browser
9. relaunched Brave with `--env-leo=staging --env-ai-chat.bsg=dev --env-ai-chat-premium.bsg=dev`
10. confirmed `Leo Premium` status
11. opened `brave://settings`
12. clicked on `Leo`

example | example | example | example | example 
----- | ----- | ------ | ----- | ------
![image](https://github.com/brave/brave-browser/assets/98358127/64c023df-89cf-4a6e-9af4-8a6a6d5cbfbc)|![image](https://github.com/brave/brave-browser/assets/98358127/141fc61c-432d-4358-b7a3-68534614fa2f)|![image](https://github.com/brave/brave-browser/assets/98358127/5392d233-5e64-4d56-b058-1e1bb7cf2a43)|![image](https://github.com/brave/brave-browser/assets/98358127/c998a712-3bf1-4e8f-87e2-92b76ef6fad0)|![image](https://github.com/brave/brave-browser/assets/98358127/47e5cfff-ac09-4857-8d33-3fd24a49d052)





</details>
