### ISSUE TITLE
Add premium offer when rate limiting is reached for Leo

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#32694]
This should only show if the user has not purchased a premium account. Note that it is still possible to hit rate limiting even with a premium account. It is just a higher limit (and of course better models)

See [Figma](https://www.figma.com/file/h7fKSJF2P556bZWfyLTfwD/Brave-AI?type=design&node-id=2726-12088&mode=design&t=LxtYravMo4zX7cRx-0) for the latest design, at the time of posting the design looks like this:
<img width="977" alt="Screenshot 2023-09-03 at 4 46 44 PM" src="https://github.com/brave/brave-browser/assets/831718/dee94447-424b-4244-a873-ac178b334fdc">

**Comment by petemill** [comment]
This seems like we should show it for both rate limiting _and_ when the conversation is deemed too long for the model

**Comment by aguscruiz** [comment]
Updated screenshot here:
![image](https://github.com/brave/brave-browser/assets/15734630/dc68c3ea-b9ac-4eb2-a12d-76dd74b1f7b3)

**Comment by stephendonner** [comment]
I couldn't yet find a way to trigger the upsell UI (it should be automatic, when hitting a rate-limit), but while reading the code to try to figure out why, I found and logged https://github.com/brave/brave-browser/issues/33507.  Please fix.

**Comment by stephendonner** [comment]
> I couldn't yet find a way to trigger the upsell UI (it should be automatic, when hitting a rate-limit), but while reading the code to try to figure out why, I found and logged #33507. Please fix.

Turns out we needed https://github.com/brave/brave-browser/issues/33143, which has since landed on `nightly`/`master` 👍 

As for https://github.com/brave/brave-browser/issues/33507 we'll fix that post-MVP.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.60.106 Chromium: 119.0.6045.59 (Official Build) (64-bit)
-- | --
Revision | 16064193dde8c55f64dabd32f125c0cd9380f96a
OS | Windows 11 Version 22H2 (Build 22621.2428)
```
Installed 1.60.106
launched Brave
enabled `#brave-ai-chat` via `brave://flags`
submit queries in the Leo sidepanel 

### Confirmed `Response rate limit` modal shows premium offer, shows `Go Premium` button, and matches to Figma screenshot


<img width="953" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/816d1999-1984-4e37-8538-6c7c00c034b6">
