### ISSUE TITLE
[hackerone]: Redirect with Tor tabs

### ISSUE THREAD

**Issue by kdenhartog** [brave/brave-browser#32706]
https://hackerone.com/bugs?subject=brave&report_id=2133384

credit: [xiaoyinl](https://hackerone.com/xiaoyinl)

**Comment by stephendonner** [comment]
Hi @boocmp can we get a testplan submitted for this, please?  Thanks!  🙏

**Comment by boocmp** [comment]
> Hi @boocmp can we get a testplan submitted for this, please? Thanks! 🙏

I've added steps to reproduce. Now only one tab should appear in the Tor window.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.60.81 Chromium: 118.0.5993.54 (Official Build) beta (x86_64)
-- | --
Revision | 1efb3f333eb41cc34af46ca31fb33c30e0afbfae
OS | macOS Version 13.6 (Build 22G120)
```

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.60.88 Chromium: 118.0.5993.70 (Official Build) beta (64-bit)
-- | --
Revision | ff9150ac5dd9934a7f431ddf478ad3e45ae68546
OS | Windows 10 Version 22H2 (Build 19045.3570)

```
Reproduced the issue on `1.58.137` using STR from description:
![image](https://github.com/brave/brave-browser/assets/38657976/14a47ca9-96a1-467f-94bf-8fe49cbb2704)

Verified only one tab is opened in Tor window when using 1.60.88 Chromium: 118.0.5993.70 and following STR from description.
![image](https://github.com/brave/brave-browser/assets/38657976/b00c5897-c3bb-489e-a73f-222e2e62163c)

**Comment by btlechowski** [comment]
Verified with

Brave | 1.60.102 Chromium: 118.0.5993.96 (Official Build) beta (64-bit)
-- | --
Revision | 3598a9fc6b7752181feb25caa131bc386d6d054c
OS | Linux


Reproduced the issue on 1.59.x
![image](https://github.com/brave/brave-browser/assets/34715963/c84a038b-a845-44d8-a6c2-d4f1be969b8d)

Verified in 1.60.x
![image](https://github.com/brave/brave-browser/assets/34715963/36171ed8-fe47-4aba-933b-e93f184bb5ba)
