### ISSUE TITLE
After enabling the new Google feature, Brave Browser crash and flash back.

### ISSUE THREAD

**Issue by azmove** [brave/brave-browser#32705]
## Description 
After enabling the new Google feature, Brave browser has a bug.
When I select "enabled" in brave://flags/#chrome-refresh-2023, the new feature will start, but I encounter a bug.
That is the issue where it crashes after clicking on the customize and control button in the upper right corner.

## Steps to Reproduce

   1. brave://flags/#chrome-refresh-2023 enabled
   2. Click the "customize and control" button in the upper right corner.
   3. bug exist

## Actual result:
Browser crash and flash back.
Unable to screenshot

## Reproduces how often: 
Every time you click the "customize and control" button, something happens.
## Brave version (brave://version info)

Version 1.57.57 Chromium: 116.0.5845.163 (Official Build) (arm64)

**Comment by azmove** [comment]
@brave-dev

**Comment by ReeSilva** [comment]
Facing the same, different profiles, and happening in Mac, Windows and Linux. Maybe the menu object is failing because some Brave menu or feature not being compatible with the new container with Material You design?

Extension menus working well, Brave Wallet and Brave VPN pop-ups also working.

**Comment by kreaninw** [comment]
I am on Version 1.59.120 Chromium: 118.0.5993.88, the flag to enable the new UI isn't available anymore.

**Comment by azmove** [comment]
> I am on Version 1.59.120 Chromium: 118.0.5993.88, the flag to enable the new UI isn't available anymore.

But after upgrade brave , I no longer have this bug.
