### ISSUE TITLE
VPN app menu doesn't give toggle button for vpn on/off

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#32703]
## Steps to Reproduce

   1. Set as purchased state
   2. Go to `Brave VPN` app menu
   3. Check toggle button is existed as a first item of  `Brave VPN` sub menu

## Actual result:

Toggle button is not shown

## Expected result:
Toggle button should be visible

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by simonhong** [comment]
It's weird that `BraveAppMenu::AddMenuItem()` is not called.
We made `AppMenu::AddMenuItem()` as virtual method and overridden it.

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.59.79 Chromium: 117.0.5938.48 (Official Build) beta (x86_64)
-- | --
Revision | b93ab5e51eb1080a6242fea103da637d542ca312
OS | macOS Version 14.0 (Build 23A5337a)
```

### Followed the steps to reproduce from https://github.com/brave/brave-browser/issues/32703#issue-1879297565.

## Confirmed the VPN app-menu flyout correctly shows the following states:
* `Disconnecting...`
* `Disconnected`
* `Connecting...`
* `Connected`


## _Disconnecting..._

`Light` | `Dark`
--------|-------
<img width="1857" alt="Screenshot 2023-09-11 at 9 44 18 PM" src="https://github.com/brave/brave-browser/assets/387249/ebb75aaf-01ee-48b4-b085-d9a53ca31dfd"> | <img width="1857" alt="Screenshot 2023-09-11 at 9 49 58 PM" src="https://github.com/brave/brave-browser/assets/387249/d8ad1b71-3bf9-4fc8-b0c4-978617ac1256">



## _Disconnected_

`Light` | `Dark`
--------|-------
<img width="1667" alt="Screenshot 2023-09-11 at 9 38 54 PM" src="https://github.com/brave/brave-browser/assets/387249/a72bdc91-b8eb-407b-a4a9-d2088d2a2776"> | <img width="1857" alt="Screenshot 2023-09-11 at 9 49 05 PM" src="https://github.com/brave/brave-browser/assets/387249/3454f468-5c0a-426a-9b17-ae1e840053cc">




## _Connecting..._

`Light` | `Dark`
--------|--------
<img width="1857" alt="Screenshot 2023-09-11 at 9 44 10 PM" src="https://github.com/brave/brave-browser/assets/387249/c1611d1b-b452-47bf-a6fe-12dd25343b00"> | <img width="1857" alt="Screenshot 2023-09-11 at 9 48 42 PM" src="https://github.com/brave/brave-browser/assets/387249/7e6a2f30-a293-4b0b-a325-ee63172a892c">



## _Connected_

`Light` | `Dark`
--------|--------
<img width="1706" alt="Screenshot 2023-09-11 at 9 39 08 PM" src="https://github.com/brave/brave-browser/assets/387249/c48a3912-5278-46c9-920f-aec87b595360"> | <img width="1857" alt="Screenshot 2023-09-11 at 9 51 46 PM" src="https://github.com/brave/brave-browser/assets/387249/12c43d29-7f96-4c49-a300-154e3695ba5f">

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.59.84 Chromium: 117.0.5938.48 (Official Build) beta (64-bit)
-- | --
Revision | 1dc90873649e32fb7d316ed9b238310d5e99b0f1
OS | Windows 10 Version 22H2 (Build 19045.3448)
```

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.59.86 Chromium: 117.0.5938.62 (Official Build) beta (64-bit)
-- | --
Revision | 3c4c1c3b2eef0fcbe8485c67e1df504942deadca
OS | Windows 11 Version 22H2 (Build 22621.2283)
```

Reproduced the issue in 1.58.124 using STR from https://github.com/brave/brave-browser/issues/32703#issue-1879297565

![image](https://github.com/brave/brave-browser/assets/98358127/01123fdf-0d21-4904-b3c3-cb3ac60b7e3f)

Installed 1.59.86
launched Brave
Purchased VPN 
clicked hamburger menu >> Brave VPN 

Confirmed Brave VPN `Disconnected` toggle is shown

VPN states 

#### *_`Disconnected`_*

Dark | Light
--- | ----
<img width="957" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/6f0dc7ae-ebae-4997-895e-83abb9525eab">|<img width="957" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/033b8747-0cb4-4151-b329-46faffbf2ba3">


#### *_`Connecting...`_*

Dark | Light
--- | ----
<img width="957" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/a7ba5eef-12c6-4e92-ae91-1c24a5b4d93b">|<img width="957" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/ee66db09-7ba6-4cdb-8258-9113ff79eeb2">


#### *_`Disconnecting...`_*

Dark | Light
--- | ----
<img width="957" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/392f8cdc-d8c8-4f2c-9ee2-1eb25eab9d11">|<img width="957" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/21ca9504-a002-4905-a388-031939ed443a">


#### *_`Connected`_*
Dark | Light
--- | ----
<img width="957" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/9bd8c382-10d3-49d3-814f-e91e8a6c411c">|<img width="957" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/5bac1ef9-d583-42dc-b7e1-c153f06c8e67">
