### ISSUE TITLE
Brave shields popup can be opened in a new tab

### ISSUE THREAD

**Issue by AnthonyLenglet** [brave/brave-browser#3271]
## Description 
The brave shields popup can be opened in a new tab, which shouldn't be possible

## Steps to Reproduce

   1. Open the brave shield popup
   2. Middle click the "global shield defaults" link in the popup

## Actual result:

The popup is now opened in its own tab
![image](https://user-images.githubusercontent.com/36004334/52452265-a9e98480-2b42-11e9-913f-f9b7b902a6f6.png)

## Expected result:
Middle click shouldn't do anything

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

Brave | 0.59.35 Chromium: 72.0.3626.81 (Official Build) (64-bit)
-- | --
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS | Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? **No**
- Is the issue reproducible on the latest version of Chrome? **No**

**Comment by srirambv** [comment]
Nice catch :+1:

**Comment by arsalankhalid** [comment]
Can I grab this?

**Comment by arsalankhalid** [comment]
@AnthonyLenglet are you performing the middle click through the track pad or mouse? Does it matter?

**Comment by AnthonyLenglet** [comment]
I'm doing it through a mouse, don't actually know if it should matter though (my guess would be that it doesn't, because its the shortcut to open a link in a new tab)

**Comment by bsclifton** [comment]
@arsalankhalid go for it 😄 Let us know if you need help

**Comment by meerasndr** [comment]
This seems solved?

**Comment by bsclifton** [comment]
Thanks for raising, @meerasndr - you're right, looks like it's resolved 😄 Closing
