### ISSUE TITLE
[Bitcoin] Android support

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#32721]

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.66.101 x64 Beta build
- Verified steps from [brave/brave-core#22962](https://github.com/brave/brave-core/pull/22962)
- Verified Bitcoin is listed during onboarding on the network selection screen
- Verified unchecking Bitcoin on network selection and creating wallet doesn't add the Bitcoin account
- Verified selecting show testnets and selecting Bitcoin Testnet and finishing onboarding creates both Mainnet and Testnet account
- Verified on upgrade from previous version, Add account modal shows Bitcoin as an option
- Verified on upgrade from previous version allows to create both Mainnet and Testnet Bitcoin account
