### ISSUE TITLE
Selecting Swap doesn't always pre-populates the correct token

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#32725]
## Description 

Selecting Swap doesn't always pre-populates the correct token

## Steps to Reproduce

   1. Filter portfolio by account
   2. Select a non-native token and select Swap
   3. Doesn't necessarily shows the token pre-selected in Swap screen

## Actual result:

https://github.com/brave/brave-browser/assets/17010094/fe00c03f-2746-4a91-9d24-766f7fc89154

## Expected result:
Should pre-set the token in Swap screen

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.58.114 Chromium: 116.0.5845.163 (Official Build) beta (64-bit)
-- | --
Revision | 21631edab5a70964c2f5817bfa4d06c32b4ab314
OS | Windows 11 Version 22H2 (Build 22621.2215)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel

**Comment by Douglashdaniel** [comment]
At the moment, we are just routing to `brave://wallet/swap` for every asset.
`route` params are not yet set up for `Swap` to achieve this.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.65.96 Chromium: 123.0.6312.86 (Official Build) beta (64-bit)
-- | --
Revision | 5d9143e1a0812c53bdc27fd5384591254306a88c
OS | Windows 11 Version 23H2 (Build 22631.3296)

- Verified steps from [brave/brave-core#22266](https://github.com/brave/brave-core/pull/22266)
- Verified filtering Portfolio by `Account` and clicking on `More Menu` for an asset and selecting `Swap` routes to Swap screen and pre-populates the token
- Verified by changing tokens and networks works fine 
- Verified `Select To` button is disabled unless a `From token` is already selected
- Verified `Flip Tokens` button is disabled until there is `From Token` and `To Token` selected

https://github.com/brave/brave-browser/assets/17010094/6f474881-0eb4-4f44-8b96-589345e5d841
