### ISSUE TITLE
[Bitcoin] P3A Support 

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#32723]
ActiveBtcAccounts and ActiveZecAccounts 
https://github.com/brave/brave-core/pull/22114
https://github.com/brave/reviews/issues/1519

**Comment by kjozwiak** [comment]
The above requires `1.64.97` or higher for `1.64.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.64.102 Chromium: 122.0.6261.111 (Official Build) beta (64-bit)
-- | --
Revision | c9343c77bd5dee3524fc45f89721ce0bf4c09b8d
OS | Windows 10 Version 22H2 (Build 19045.4046)
```
