### ISSUE TITLE
Can I add the function of manually blocking advertisements?

### ISSUE THREAD

**Issue by biange200** [brave/brave-browser#32735]
Request to add the function of manually filtering advertisements

**Comment by rebron** [comment]
Hi @biange200. You can already do that. I linked the support article for you. Hope that helps. 

https://support.brave.com/hc/en-us/articles/360018039072-How-do-I-use-the-Content-Filter-to-block-elements-on-a-webpage-

**Comment by biange200** [comment]
This is only useful on the pc version, right? I'm talking about the mobile phone version



---- Replied Message ----
| From | Rafael ***@***.***> |
| Date | 09/08/2023 23:31 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [brave/brave-browser] Can I add the function of manually blocking advertisements? (Issue #32735) |

Hi @biange200. You can already do that. I linked the support article for you. Hope that helps.

https://support.brave.com/hc/en-us/articles/360018039072-How-do-I-use-the-Content-Filter-to-block-elements-on-a-webpage-

**Comment by biange200** [comment]
> Hi @biange200. You can already do that. I linked the support article for you. Hope that helps. 
> 
> https://support.brave.com/hc/en-us/articles/360018039072-How-do-I-use-the-Content-Filter-to-block-elements-on-a-webpage-
> 
> 
手机上有没有解决问题的方法
