### ISSUE TITLE
Add Leo Llama 2 70B premium model choice for premium users

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#32739]
- Deploy a 70B Llama instance
- Make it possible to select this model from the client side

**Comment by petemill** [comment]
Is this all done? It is possible to use in the client already.

**Comment by bbondy** [comment]
Not on prod yet but I think @evq and @nvonpentz are still going to have it up before this hits release in a few days.

**Comment by petemill** [comment]
Test plan blocked on https://github.com/brave/aichat/issues/63

**Comment by petemill** [comment]
Closing so that we have an issue for the client work, which is in 1.60.x already. Made https://github.com/brave/aichat/issues/63 for the server-side.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.60.106 Chromium: 119.0.6045.59 (Official Build) (64-bit)
-- | --
Revision | 16064193dde8c55f64dabd32f125c0cd9380f96a
OS | Windows 11 Version 22H2 (Build 22621.2506)

```

* ensured that `llama2 70b` appears under the `Language models` hamburger menu via the `Leo` sidebar
* ensured that `llama2 70b` appears via `brave://settings/leo-assistant` under `Default model for new conversations`
* ensured that selecting `llama2 70b` while non-premium initiates the premium flow within the `Leo` sidebar panel
* ensured the correct model intro text is being used when `llama2 70b` is selected 
* ensured that once you go premium, that `llama2 70b` is accessible/usable.

**`Example`** | **`Example`** | **`Example`** | **`Example`**  | **`Example`** | **`Example`**
----------------|----------------|----------------|-----------------|----------------|------------------
![image](https://github.com/brave/brave-browser/assets/2602313/13cda4b4-d4e0-40fb-a76a-bfe5f7a97148) | ![image](https://github.com/brave/brave-browser/assets/2602313/65dfd289-e73d-4f19-8101-adbc45d3637e) | ![image](https://github.com/brave/brave-browser/assets/2602313/4b6bc50a-1c08-44ce-a569-1447cc6d2efd) | ![image](https://github.com/brave/brave-browser/assets/2602313/16e8e123-cc5b-4b25-a92d-8ab6e6eba41d)
![image](https://github.com/brave/brave-browser/assets/2602313/9129737a-2692-4097-995e-fe8fb6757d3b) | ![image](https://github.com/brave/brave-browser/assets/2602313/8e2ccb1a-d54c-4435-ad81-0594e9a77d93)
