### ISSUE TITLE
Allow for model selection within the Leo sidebar panel

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#32737]
- Model selection within the context of the sidebar
- Rename settings item to default model
- The default model depends on if a user has premium or not. If the default model is premium then the default is Anthropic. Otherwise it is Llama 2

Design is still needed for this. cc @aguscruiz

**Comment by aguscruiz** [comment]
Designs added here:
https://www.figma.com/file/h7fKSJF2P556bZWfyLTfwD/Brave-AI?type=design&node-id=3251%3A39624&mode=design&t=de7RyoSNeBpsd3Vm-1

**Comment by stephendonner** [comment]
@petemill mind adding in a test plan (in addition to the linked Figma), to help make verifications smoother/quicker?  Thanks!

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.60.106 Chromium: 119.0.6045.59 (Official Build) (x86_64)
-- | --
Revision | 16064193dde8c55f64dabd32f125c0cd9380f96a
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Shared Steps:
<details>

1. installed `1.60.106`
2. launched Brave using `--env-leo=staging --env-ai-chat.bsg-dev --env-ai-chat-premium.bsg=dev --enable-logging=stderr --v=1`
3. opened `brave://flags`
4. set `brave://flags/#brave-ai-chat` to `Enabled`
5. clicked `Relaunch`
6. clicked on `Leo` in the sidebar
7. clicked on `Accept and begin`


</details>
