### ISSUE TITLE
[Android] Adjust margin for `Earnings so far` in Rewards Panel 

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#32736]
Note that the estimated earnings so far are too close to the right edge of the Rewards panel:

![image](https://github.com/brave/brave-browser/assets/11497541/777a6316-de7b-407d-aa8d-033240c2cdfa)

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.60.85`

**_Clean profile:_**

Example | Example 
----------|-----------
![Screenshot_20231012_140441](https://github.com/brave/brave-browser/assets/38657976/a143d2b0-4d7e-4dfd-8a6c-82ddc4e7084d) | ![Screenshot_20231012_140359](https://github.com/brave/brave-browser/assets/38657976/e2a35578-22af-4242-9878-ca5272424c6e)



**_Grandfathered state_**

Example | Example 
----------|-----------
![Screenshot_20231012_141838](https://github.com/brave/brave-browser/assets/38657976/692d2468-0de5-4605-8af9-b9a1f1b5154a) | ![Screenshot_20231012_142238](https://github.com/brave/brave-browser/assets/38657976/bf27f112-cf20-40c3-9c12-5c3a0797d804)
