### ISSUE TITLE
Add Leo feedback form (server side)

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#32740]
[Feedback](https://bravesoftware.slack.com/archives/C04T4UB3HNV/p1693323641089429) form which allows you to report bad interactions and related back end work

**Comment by aguscruiz** [comment]
Design here:
https://www.figma.com/file/h7fKSJF2P556bZWfyLTfwD/Brave-AI?type=design&node-id=539%3A19624&mode=design&t=nXguS70mTLVV2pH5-1

**Comment by petemill** [comment]
Let's have separate issues for client frontend and server. Since @hspencer77 and @porteron are on this once, we can have this one be for the server and make a new one for the client.

**Comment by bbondy** [comment]
I think this can be closed, please re-open if anyone disagrees
