### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by kittehoverlord** [brave/brave-browser#32746]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.59.70 Chromium: 116.0.5845.163
Operating System: Windows NT 10.0.19044
Intel graphics driver : 20.19.15.5126
Nvidia graphics driver : 425.31

URL (if applicable) where crash occurred:
Open tabs:
brave://crashes/
This crash reporting page.

Can you reproduce this crash?
Yes. It occurs with hardware acceleration on and off.
It occurs regardless of Windows Graphics settings. Intel(power saving), Nvidia(High Performance), or Let Windows decide configurations all result in a crash.
It occurs on my main display and on the secondary display. It occurs when there is only one display. It occurs when maximized and when in a floating window. 
### This is the cause of my particular crashing
**The crash is related to _Tab Scrolling With Dragging_, disabling causes crashing to cease. All other Tab Scrolling flags are enabled.**

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Open Brave Browser.
1a. Restore Brave Browser after crash.
2. Have more than one tab open.
3. Click and hold left mouse button to select.
3. As soon as I move the tab with the mouse button held, the crash occurs. 

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/06470b00-958b-a50a-0000-000000000000

**Comment by iefremov** [comment]
stale

**Comment by iefremov** [comment]
experimental features are controlled by Chromium, not by us. We cannot guarantee stable work with upstream features toggled
