### ISSUE TITLE
Make Leo compatible with PDFs

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#32741]

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using


```
Brave | 1.64.41 Chromium: 121.0.6167.139 (Official Build) nightly (x86_64)
-- | --
Revision | 1c56846eb16cec835298c09cd75ec45fc425507b
OS | macOS Version 14.4 (Build 23E5180j)
```

## Shared Steps
<details>

1. installed `1.64.41`
2. launched Brave
3. clicked on `Leo` in the sidebar
4. typed `hi`
5. clicked `Accept and begin`

</details>

## Summarize page - `PENDING`
<details>

1. loaded and opened `https://arxiv.org/pdf/2401.01353.pdf`
2. clicked `Summarize this page`

### Confirmed page summarization

example | example | example
----------|-----------|----------




</details>

## Refresh and summarize page - `PENDING`
<details>
(continued from Summarize page, above)

1. refreshed the page
2. clicked on `Summarize this page`


### Confirmed page summarization



</details>

## Long PDF - `PENDING`
<details>

1. loaded and opened `https://arxiv.org/pdf/2312.03863.pdf`
2. clicked `Summarize this page`
3. reloaded the page
4. clicked `Summarize this page`

### Confirmed the button darkened whilst loading, at the end of which the summarization appeared

example | example | example
----------|-----------|----------


</details>

## Check a11y mode - `PENDING`
<details>

1. opened `https://arxiv.org/pdf/2312.03863.pdf`
2. opened `https://brave.com/static-assets/files/1.0-REVIEWERS-GUIDE-a5f1bca9-ea66-4445-806b-45e00038ff6c.pdf`
3. opened `https://research.cs.queensu.ca/home/ahmed/home/teaching/CISC322/F08/files/google-chrome-comic.pdf`
4. opened `brave://accessibility/`

### Confirmed only three (3) of the  chrome-extension://mhjfbmdgcfjbbpaeojofohoefgiehjai/index.html entries had `Native: true Web: true` attributes

example | example
----------|----------

**Comment by kjozwiak** [comment]
Removing the `QA Pass` label as the above needs to be re-verified on `1.63.x` as it was uplifted via https://github.com/brave/brave-core/pull/21912. Used https://github.com/brave/brave-browser/issues/32741#issuecomment-1922407298 as the needed verification on `Nightly`.

The above requires `1.63.147` or higher for `1.63.x` verification 👍

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.63.147 Chromium: 121.0.6167.139 (Official Build) beta (64-bit)
-- | --
Revision | 714ec16e326c20dcdd5c70524509c652734689e8
OS | Windows 10 Version 22H2 (Build 19045.3996)
```
