### ISSUE TITLE
[Commander]: Add custom icon for commands

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#32744]
Currently, the command icons just use the fallback icon. We should introduce an icon, just for commands.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.59.86 Chromium: 117.0.5938.62 (Official Build) beta (64-bit)
-- | --
Revision | 3c4c1c3b2eef0fcbe8485c67e1df504942deadca
OS | Windows 11 Version 22H2 (Build 22621.2283)
```

Reproduced the issue in 1.58.124 Chromium: 117.0.5938.62. 
<img width="803" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/ae3a38f7-e2a3-45f6-8207-8fbaf0fd8707">

Steps: 

1. Installed 1.59.86
2. launched Brave
3. opened `brave://flags` in a new tab page
4. enabled the `#quick-commands`
5. pressed `Ctrl+Space` to open quick commands
6. confirmed commands in the URL bar no longer have the ` :>` string prefixing them 
7. confirmed commands have the [carat-right](https://leo.bravesoftware.com/?path=/story/icon--default&args=name:carat-right) icon and no fallback `globe` icon is shown

step 4 | step 6-7
----- | ------
<img width="952" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/fb3542bf-3808-43c1-969b-73f91b3cc8e2">|<img width="952" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/18cb9e8e-f84c-41cf-a81a-bbae279c512d">
