### ISSUE TITLE
Craigslist site is not working on Brave 

### ISSUE THREAD

**Issue by otieonoradigo** [brave/brave-browser#3276]
Craigslist site is not working on Brave, anyhelp will be highly appreciated

**Comment by srirambv** [comment]
Please use the template to provide info and reopen the issue

**Comment by otieonoradigo** [comment]
Craigslist site is not working on Brave browser 
![capture](https://user-images.githubusercontent.com/47444958/52548214-5a72b500-2ddd-11e9-81ce-a7f8bc442662.PNG)
