### ISSUE TITLE
Show disclaimer in Rewards onboarding

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#32762]
## Description

```[tasklist]
### Tasks
- [x] Rewards panel
- [x] brave://rewards page
- [x] NTP Rewards widget (desktop only)
```

* [Terms of Service](https://basicattentiontoken.org/user-terms-of-service/)
* [Privacy Policy](https://brave.com/privacy/browser/#rewards)

For text, use existing string of "By proceeding, you agree to the...", regardless of Figma.

https://www.figma.com/file/VIkvO8TBQXVBnvKn4w8iYu/BR-onboarding?type=design&node-id=0%3A1&mode=design&t=MbkzJv4FJyyyVQTb-1

![image](https://github.com/brave/brave-browser/assets/11497541/b872d3cc-6c10-47f6-8ba2-4976163796aa)

![image](https://github.com/brave/brave-browser/assets/11497541/f74f4c0e-1063-4d6b-98c7-2f466b3da478)

**Comment by kjozwiak** [comment]
The above requires `1.58.117` or higher for `1.58.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.58.117 Chromium: 116.0.5845.180 (Official Build) (x86_64)
-- | --
Revision | 99255ad6abf2fa399c063683c051f973e1f5c0af
OS | macOS Version 13.5.1 (Build 22G90)
```
