### ISSUE TITLE
Add options to show network value in fiat/crypto, show/hide network logo

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#32768]
## Description 

Add options to show network value in fiat/crypto, show/hide network logo

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.59.109 Chromium: 118.0.5993.21 (Official Build) beta (64-bit)
-- | --
Revision | aacb6a6f8bd916bd49f064b2137b007fa6c47b51
OS | Windows 11 Version 22H2 (Build 22621.2283)

- Verified steps from [brave/brave-core#20000](https://github.com/brave/brave-core/pull/20000)
- Verified network fee is shown on all screens 

![brave_Q1fVkJTC4E](https://github.com/brave/brave-browser/assets/17010094/a2712a4b-dd08-4def-8ddd-621c7c376086) | ![brave_3gr5EMPsgS](https://github.com/brave/brave-browser/assets/17010094/51f69191-ccff-4d67-8840-1c9c7f311f79)
-- | --

![DFNpt8N1yJ](https://github.com/brave/brave-browser/assets/17010094/eaa28c70-809c-4df4-b5ad-916815900bbb) | ![vFZwmK4aFI](https://github.com/brave/brave-browser/assets/17010094/f6623cbd-fe07-4abd-a860-e92b83647a35) | ![MyKkzJP1Tl](https://github.com/brave/brave-browser/assets/17010094/091c6b54-95de-4dca-8ea6-3441f242ac95)
-- | -- | --
