### ISSUE TITLE
[Android] Show disclaimer in Rewards onboarding

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#32763]
Android version of https://github.com/brave/brave-browser/issues/32762

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Samsung Galaxy version 12` running `Bravemonoarm64.apk_1.58.121`

Verified test plan from https://github.com/brave/brave-core/pull/19997#issue-1882580204 and https://github.com/brave/brave-browser/issues/32762#issue-1882482189.

Confirmed `Terms of Service` links redirects to https://basicattentiontoken.org/user-terms-of-service/
Confirmed `Privacy Policy` links redirects to https://brave.com/privacy/browser/#rewards

Light Theme | Dark Theme
--- | ---
![Screenshot_20230912-163612_Brave](https://github.com/brave/brave-browser/assets/38657976/4c3b468f-0fb6-4bbb-812c-ce86567c8ce0) | ![Screenshot_20230912-163756_Brave](https://github.com/brave/brave-browser/assets/38657976/d4404701-1175-470d-b228-07b8bf841251)
![Screenshot_20230912-163907_Brave](https://github.com/brave/brave-browser/assets/38657976/3e29ccee-00ab-4ffe-a2b4-52d9ac2c4a1c) | ![Screenshot_20230912-163811_Brave](https://github.com/brave/brave-browser/assets/38657976/e109c7cf-fe90-4a18-9a13-ba0e5d4b7e75)
