### ISSUE TITLE
Enabling brave commands in flags has no effect

### ISSUE THREAD

**Issue by patrickmao93** [brave/brave-browser#32789]
## Description 

Enabling brave commands in flags has no effect

## Steps to Reproduce

   1. enable brave://flags/#brave-commands
   2. restart brave
   3. go to brave://commands

## Actual result:

brave://commands no such page

## Expected result:

brave://commands opens

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.57.57 Chromium: 116.0.5845.163 (Official Build) (arm64)
Revision | d85db1f5df3b20ffecf96ab3f0dc7fca1d536955
OS | macOS Version 13.5.1 (Build 22G90)

OR

Brave | 1.59.73 Chromium: 116.0.5845.163 (Official Build) nightly (arm64)
Revision | 259eb961182243cb66c7ce76dbd06dea400888bc
OS | macOS Version 13.5.1 (Build 22G90)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by rebron** [comment]
Hi @patrickmao93 Can you try it with brave://flags/#quick-commands and then control + space bar to invoke? 

Commands you may be looking for are also here in shortcut form: brave://settings/system/shortcuts

**Comment by patrickmao93** [comment]
Oh somehow I didn't notice that shortcuts can be set in brave://settings/system/shortcuts. All search online pointed me to brave://commands. Thanks for the help. I hope this issue thread will bring others answers too.
