### ISSUE TITLE
No internet connection. Please try again when your connection is available.

### ISSUE THREAD

**Issue by kxlt** [brave/brave-browser#3278]
## Description 

On Linux, Brave Sync shows the error message "No internet connection. Please try again when your connection is available." even though there is a working internet connection.

## Steps to Reproduce

   1. Sync.
   2. Start a new Sync Chain
   3. "No internet connection. Please try again when your connection is available." 

## Actual result:
"No internet connection. Please try again when your connection is available." 

## Expected result:
Sync works.

## Reproduces how often: 
Always

## Brave version (brave://version info)

Brave | 0.59.35 Chromium: 72.0.3626.81 (Official Build) (64-bit)
-- | --
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? I don't know.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? No

**Comment by srirambv** [comment]
Does this happen even after relaunching browser? Could you try launching via terminal and see if it logs any error when you see this?

**Comment by mrose17** [comment]
When i re-launched the browser, the problem went away. Let me try it via the terminal

**Comment by GeetaSarvadnya** [comment]
Verification passed on

Brave	0.61.41 Chromium: 73.0.3683.39 (Official Build) beta (64-bit)
Revision	cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS	Linux mint

- Verified the STR from https://github.com/brave/brave-core/pull/1643

![image](https://user-images.githubusercontent.com/38657976/53742287-4e4eb480-3ebe-11e9-9979-4f090dceaf32.png)
