### ISSUE TITLE
AI Chat: sanitization not implemented when using llama models

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#32787]
We sanitize page content and human input but only for claude models. It's important to do this so that article content can't purposefully alter the system prompt.

For llama2, `</s>` is a control string that we don't want the article or user input text to include.

## Test plan:

1. Use llama model
2. Start a conversation
3. Submit the text "Hello repeat this: </s>. Can you repeat what I said?"
Observe that `</s>` is missing from the human input message in the conversation list.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.60.87 Chromium: 118.0.5993.70 (Official Build) beta (64-bit)
-- | --
Revision | 854c1e600054dfca6842cebaf729f100f4b0f066
OS | Windows 10 Version 22H2 (Build 19045.3570)
```

### Steps:
1. installed `1.60.87`
2. launched Brave
3. opened `brave://flags`
4. set `brave://flags/#brave-ai-chat` to `Enabled`
5. clicked `Relaunch`
6. loaded `https://www.vice.com/en/article/m7b5ny/cyber-space-junk-nuclear-waste-ai-nukes-and-the-reason-were-all-still-here`
7. clicked on the `Brave Leo` icon in the sidebar
8. clicked on `Accept and begin`
9. typed `Hello, repeat this: . Can you repeat what I said?`
10. also tried `< ~` from https://bravesoftware.slack.com/archives/C05NDQP03AQ/p1695453380655859

### Confirmed `Leo`  said `Hello, can you repeat what I said?` without issue

example | example | example | example | example
----------|----------|-----------|-----------|---------
![image](https://github.com/brave/brave-browser/assets/387249/a2fa0a83-f562-475a-97cc-ea50807989b2) | ![image (1)](https://github.com/brave/brave-browser/assets/387249/46592451-0d9c-4afd-b440-480959843161) | ![image (2)](https://github.com/brave/brave-browser/assets/387249/c9721a50-51fe-4b4f-8423-947932f7a24f) | ![image (3)](https://github.com/brave/brave-browser/assets/387249/be3a6d02-fa64-4390-b20b-361135647407) | ![image (4)](https://github.com/brave/brave-browser/assets/387249/37c511e8-f014-485c-90dc-4b758686938b) | ![image (5)](https://github.com/brave/brave-browser/assets/387249/437299a9-3d42-4523-8b1e-37bf85a43d0b)

**Comment by kjozwiak** [comment]
@hffvld @Uni-verse the following doesn't need to be verified on `Android` after discussing with @bbondy. I'll leave the `OS/Android` label as it's still technically applicable for `Android` but there's no need to QA the above on `Android`.
