### ISSUE TITLE
[ads] Fix custom notification ad text is truncated when linking a Rewards custodian

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#32795]
After connecting to a custodian we show a notification. This notification is truncated for Custom notification

## Steps to Reproduce

1. Clean profile
1. Set `brave://flags/#brave-ads-custom-push-notifications-ads` to `Enabled`
3. Enable rewards
4. Connect to a custodian

## Actual result:

Custom notification is truncated
![image](https://github.com/brave/brave-browser/assets/34715963/1215def0-ec0a-4ce5-90d1-22c68d753530)

![image](https://github.com/brave/brave-browser/assets/34715963/7a7ffedf-5be4-413e-8acb-f7c5f914f64b)

## Expected result:
Custom notification is not truncated

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.57.62 Chromium: 116.0.5845.180 (Official Build) (64-bit)
-- | --
Revision | 77ae816289bb4557b7e04b3ff2e52d091ab68d66
OS | Linux

cc @tmancey @aseren @OdoCecII

**Comment by tmancey** [comment]
@aseren would this be resolved by https://github.com/brave/brave-browser/issues/31407?

**Comment by tmancey** [comment]
Closing issue as working as expected now that custom notification ads match the OS size.

**Comment by btlechowski** [comment]
Verified with

Brave | 1.62.107 Chromium: 120.0.6099.115 (Official Build) beta (64-bit)
-- | --
Revision | 67a3b21572338a0660bb25a5855da0f1e9372a39
OS | Linux


![image](https://github.com/brave/brave-browser/assets/34715963/99b9ee28-466a-443b-9d27-c7d2d8da1048)
