### ISSUE TITLE
[iOS] Use correct components for Adblock services

### ISSUE THREAD

**Issue by cuba** [brave/brave-browser#32799]
We use legacy components for Adblock services to fetch things like the default and custom filter lists. We need to use the correct components

* Use the unified `list_catalog.json` file for getting the correct default/custom component details
* see what we can re-use (maybe move) on desktop to use as many shared files as possible (if anything)

**Comment by antonok-edm** [comment]
For reference: https://github.com/brave/brave-browser/wiki/Brave-Components

### Can be migrated independently

- `Brave Ad Block List Catalog` (for `regional_lists.json`)
- `Brave Ad Block Resources Library` (for `resources.json`)

### Depends on all of the above

- `Brave Ad Block Updater`
- Regional lists

**Comment by kjozwiak** [comment]
The above requires `1.59.124` or higher for `1.59.x` verification 👍

**Comment by kjozwiak** [comment]
The above can also be verified alongside https://github.com/brave/brave-browser/issues/33718. Basically ensuring that adblocking is working as expected.

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.59.124 Chromium: 118.0.5993.117 (Official Build) (64-bit)
-- | --
Revision | 63d57e32ce0ff0a1e380461bc394351e97d1416a
OS | Windows 10 Version 22H2 (Build 19045.3570)

```

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.59.24`

**Comment by hffvld** [comment]
Verified on `Galaxy Tab S8` using version(s):
```
Device/OS: Galaxy Tab S8 [gts8wifixx-user 13 TP1A.220624.014 release-keys]
Brave build: 1.59.124
Chromium: 118.0.5993.117 (Official Build) (64-bit)
Revision: 63d57e32ce0ff0a1e380461bc394351e97d1416a
```
---------------------------

**STEPS:**
1. Followed the steps from https://github.com/brave/brave-browser/issues/32799#issue-1884399665

**ACTUAL RESULTS:**
- Verified that `ads` loaded within the page when visited https://www.zerohedge.com/ and disabled Shields. Re-enabled Shields and verified that ads were being blocked without issues.
- Verified that `first-party ads` were appearing when visited https://www.google.com/ and searched for Under Armour. Switched to `Aggressively block tracker & ads` and verified those `ads` were being removed/not being displayed anymore
- Verified that enabling `Block scripts` blocked the carousel when visiting https://www.blizzard.com.
- Verified that there was no cookie consent banner being displayed on the page when visiting https://digikey.com if `Block cookie consent notices` toggle is ON.
- Verified that the page appears grey when visiting https://mixed-script.badssl.com

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/2cc910e2-43c4-420d-a873-e8426602168d) | ![2](https://github.com/brave/brave-browser/assets/128532965/725a72c3-08a3-4240-ab83-528ac0576fa4) | ![3](https://github.com/brave/brave-browser/assets/128532965/bdb182cf-ec7d-45d4-b53f-bc92896b13b6) | ![4](https://github.com/brave/brave-browser/assets/128532965/b71282af-953c-44f8-ad1d-7f8e0fe28d0a) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/84d48de7-8649-4606-9bf1-b5369483eb30) | ![2](https://github.com/brave/brave-browser/assets/128532965/9448fe74-8a6a-4b36-b46c-313e1714819c) | ![3](https://github.com/brave/brave-browser/assets/128532965/b612da73-70fb-4eca-bd63-ec68f22aaf7e) | ![4](https://github.com/brave/brave-browser/assets/128532965/696321eb-c822-4a9b-98fc-4bc30539d1f9) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/28a2686f-48d9-405a-a4b8-75132961c65a) | ![2](https://github.com/brave/brave-browser/assets/128532965/fbba48b0-26e8-4801-a831-b8ac764a1694) | ![3](https://github.com/brave/brave-browser/assets/128532965/9a31897d-eec0-4279-a982-fcc4672b1a40) | ![4](https://github.com/brave/brave-browser/assets/128532965/056618cb-5470-4661-9f3b-ebaafed3bab2) |

**Comment by btlechowski** [comment]
Verified with

Brave | 1.59.124 Chromium: 118.0.5993.117 (Official Build) (64-bit)
-- | --
Revision | 63d57e32ce0ff0a1e380461bc394351e97d1416a
OS | Linux



Using the STR/information outlined via https://github.com/brave/brave-browser/issues/32799#issue-1884399665, ensured that `ad-blocking` was generally working as per the following:

* visited https://www.zerohedge.com and disabled shields and ensured that `ads` loaded within the page
  * re-enabled shields and ensured that ads were being blocked without issues

![image](https://github.com/brave/brave-browser/assets/34715963/56a32eed-368f-4c47-852b-b2d5e0cbed08)|![image](https://github.com/brave/brave-browser/assets/34715963/253b90ec-ead3-46a1-9e69-3ce569e8a42b)
--|--

* visited https://www.google.ca and searched for Under Armour and ensured that first-party ads were appearing
  * switched to `Aggressively block tracker & ads` and ensured those ads were being removed/not being displayed anymore
 
* visited https://www.blizzard.com/en-gb/ and ensured that enabling `Block scripts` blocked the carousel
![image](https://github.com/brave/brave-browser/assets/34715963/ba7b41f0-59d8-431b-944f-a9528063711b)


* visited https://digikey.com and ensured there was no `cookie consent` banner being displayed at the top of the page
 

* visited https://mixed-script.badssl.com and ensured the page appears `grey`

* verified filter lists work:
* 
![image](https://github.com/brave/brave-browser/assets/34715963/506e9776-5ba1-41f6-9569-557727e6a028)|![image](https://github.com/brave/brave-browser/assets/34715963/b3f4bb2f-8f71-4a12-afd9-ec4cd111cd4f)|![image](https://github.com/brave/brave-browser/assets/34715963/c877b8d8-467d-4eab-93f6-cae2d027a9de)
--|--|--

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 14.0 x64 Sonoma` using the following build(s):

```
Brave | 1.59.124 Chromium: 118.0.5993.117 (Official Build) (x86_64)
--- | ---
Revision | 63d57e32ce0ff0a1e380461bc394351e97d1416a
OS | macOS Version 14.0 (Build 23A344)
```

Using the STR/information outlined via https://github.com/brave/brave-browser/issues/32799#issue-1884399665, ensured that `ad-blocking` was generally working as per the following:

* visited https://www.zerohedge.com and disabled shields and ensured that `ads` loaded within the page
  * re-enabled shields and ensured that ads were being blocked without issues
* visited https://www.google.ca and searched for Under Armour and ensured that first-party ads were appearing
  * switched to `Aggressively block tracker & ads` and ensured those ads were being removed/not being displayed anymore
* visited https://www.blizzard.com/en-gb/ and ensured that enabling `Block scripts` blocked the carousel
* visited https://digikey.com and ensured there was no `cookie consent` banner being displayed at the top of the page
  * https://user-images.githubusercontent.com/2602313/245333866-0b9ce862-7c52-4381-af8b-a593ee32c3a3.png
* visited https://mixed-script.badssl.com and ensured the page appears `grey`
