### ISSUE TITLE
Remove unofficial Leo styles & components

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#32796]
## Description 

Now that @brave/Leo components are available for use, we can remove our custom components.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.59.109 Chromium: 118.0.5993.21 (Official Build) beta (64-bit)
-- | --
Revision | aacb6a6f8bd916bd49f064b2137b007fa6c47b51
OS | Windows 11 Version 22H2 (Build 22621.2283)

- Verified steps from [brave/brave-core#20016](https://github.com/brave/brave-core/pull/20016)
- Verified gas fee limit warning is still shown correctly
- Verified no regression when setting low gas fee 
- Encountered [#33373](https://github.com/brave/brave-browser/issues/33373)

https://github.com/brave/brave-browser/assets/17010094/1f426ebc-a5c7-4241-9558-0025273d951e
