### ISSUE TITLE
Wallet response is quite slow when selecting network

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#32791]
## Description 
Wallet response is quite slow when selecting network

## Steps to reproduce 

   1. Install 1.58.114 x64 Beta build
   2. Restore wallet with balance
   3. Select Send from action menu
   4. Select Network dropdown
   5. Response is quite slow

## Actual result 

https://github.com/brave/brave-browser/assets/17010094/e1934fde-c5d2-4280-8887-31ef58ffe735

## Expected result
Should have better response

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Not checked

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 13
   
## Brave version
1.58.114

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @simoarpe @Pavneet-Sing

**Comment by Pavneet-Sing** [comment]
This is observed on web wallet UI pages not on inbuilt native wallet (#31506 issue was for native wallet). Native android has no control over these factors and the speed/responsiveness depends on web-wallet, loading speed, phone-hardware etc. Discussion thread to explore options to speed up responsiveness of web wallet pages https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1693993360983839

**Comment by josheleonard** [comment]
@srirambv, is this still valid? The send screen received some performance optimizations here: [Fix: send screen performance refactor](https://github.com/brave/brave-core/pull/20219#top)

**Comment by srirambv** [comment]
Issue not relevant any more. Closing as stale

https://github.com/brave/brave-browser/assets/17010094/72d6aac0-8b8f-4fca-a970-4ee76f17675a
