### ISSUE TITLE
Enable SKU SDK on Linux

### ISSUE THREAD

**Issue by nvonpentz** [brave/brave-browser#32803]
We need the SKUs feature for AI chat, which will be available on Linux, so we should re-enable this.  My understanding is that the issue that originally caused the crashes on Linux related to SKUs has now been fixed https://github.com/brave/brave-browser/issues/23140.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.60.89 Chromium: 118.0.5993.70 (Official Build) beta (64-bit)
-- | --
Revision | 801f851e0c0664d110cccd46708cd084a83c3729
OS | Linux
```
