### ISSUE TITLE
Signing confirmation panel appears after the wallet locks

### ISSUE THREAD

**Issue by kdenhartog** [brave/brave-browser#32818]
Something odd is happening in the wallet SIWE panel.

https://github.com/brave/brave-core/assets/23125059/250e3bb4-7924-4b37-bcc4-daba5db21470

Steps to reproduce:

1. Connect wallet to https://metamask.github.io/test-dapp
2. Unlock wallet
3. Click "sign in with ethereum (w/ resources)"
4. Wait for wallet to re-lock (I set my timeout to 1 minutes to reproduce more easily)
5. click wallet icon and the SIWE panel will appear rather than the unlock

This doesn't appear to bypass any authorization checks, but probably still a bug that needs fixed.

**Comment by kjozwiak** [comment]
The above requires `1.59.94` or higher for `1.59.x` verification 👍

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.59.112 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | `967f25f295938c64c24e2e6a1790470668757655`
OS | Windows 11 Version 22H2 (Build 22621.2283)

- Verified steps from [brave/brave-core#20054](https://github.com/brave/brave-core/pull/20054)
- Verified sign prompt is not shown in panel if wallet is locked via another tab

https://github.com/brave/brave-browser/assets/17010094/77aefbaf-d5b6-4dcc-a173-8a9b4fb012d4

---------------------

**Verification passed on**

Brave | 1.59.112 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | `967f25f295938c64c24e2e6a1790470668757655`
OS | Linux

- Verified steps from [brave/brave-core#20054](https://github.com/brave/brave-core/pull/20054)
- Verified sign prompt is not shown in panel if wallet is locked via another tab

https://github.com/brave/brave-browser/assets/17010094/938433d6-bff3-4337-8476-e7e98e71dcca

---------------------

**Verification passed on**

Brave | 1.59.112 Chromium: 118.0.5993.54 (Official Build) (arm64)
-- | --
Revision | `967f25f295938c64c24e2e6a1790470668757655`
OS | macOS Version 14.0 (Build 23A344)

- Verified steps from [brave/brave-core#20054](https://github.com/brave/brave-core/pull/20054)
- Verified sign prompt is not shown in panel if wallet is locked via another tab

https://github.com/brave/brave-browser/assets/17010094/07dabe60-28f1-4b8c-add6-53c6dd4c3fc9
