### ISSUE TITLE
[App Menu]: Add icon for password manager

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#32817]
The CR117 bump added a new entry for the password manager. We should add an icon for this:

https://bravesoftware.slack.com/archives/CU5UXM3EC/p1694009822114299
(found by @mkarolin)

**Comment by kjozwiak** [comment]
The above requires `1.59.102` or higher for `1.59.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using


```
Brave | 1.59.102 Chromium: 117.0.5938.140 (Official Build) beta (x86_64)
-- | --
Revision | 11284b6d5d51252fe1a6fb6b5cba35ef98982357
OS | macOS Version 14.1 (Build 23B5046f)
```

### Steps:
1. installed `1.59.102`
2. launched Brave
3. clicked on the "hamburger" menu
4. looked at the `Password Manager` menu-item entry

### Confirmed icons for `Password Manager` in both `Dark` and `Light` modes

example | example
---------|---------
<img width="301" alt="Screenshot 2023-09-28 at 10 05 27" src="https://github.com/brave/brave-browser/assets/387249/9858a60f-6cff-47f6-a7ed-c3ff7c28b6ac"> | <img width="314" alt="Screenshot 2023-09-28 at 10 06 14" src="https://github.com/brave/brave-browser/assets/387249/993fba41-29e6-4087-b36e-c59c7cbee7de">
