### ISSUE TITLE
Sync: don't send record to sync cloud if bookmark metadata has changed

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#3281]
## Description 

Currently if bookmark metadata is changed, sync record UPDATED is sent to sync with all fields unchanged. Metadata of bookmark can be updated in 3 cases:
1. Our sync operations
2. Chromium sync operations
3. Chromium bookmarks api for extensions
4. Bookmark url is visited
We are not interested in any of these operations, so this should be removed.

## Steps to Reproduce

   1. Create chain brave-core1 <=> brave-core2
   2. On brave-core1 visit duckduckgo.com, bookmark it and close the tab
   3. Wait for this bookmark appear on brave-core2
   4. On brave-core1 open chrome://inspect/#extensions => inspect link under `Brave Sync` => console
   5. On brave-core1 open duckduckgo.com from bookmarks

## Actual result:

    6. See send sync record in console with `"action":1` in ~ 1 minute like
```
"send-sync-records" category_name="BOOKMARKS" records=[
{"action":1,
"bookmark":{
"hideInToolbar":false,
"isFolder":false,
"order":"1.0.0.1",
"site":{
"creationTime":0,
"customTitle":"DuckDuckGo — Privacy, simplified.",
"favicon":"https://duckduckgo.com/favicon.ico",
"lastAccessedTime":0,
"location":"https://duckduckgo.com/",
"title":"DuckDuckGo — Privacy, simplified."},
"parentFolderObjectId":{}},
"deviceId":{"0":0},
"objectData":"bookmark",
"objectId":{"0":57,"1":34,"2":27,"3":239,"4":42,"5":5,"6":222,"7":5,"8":36,"9":60,"10":109,"11":50,"12":160,"13":200,"14":177,"15":125},
"syncTimestamp":1549657807005.618}]
```

## Expected result:
    6. No send record  in console with `"action":1` in ~ 1 minute

## Reproduces how often: 

Easily

## Brave version (brave://version info)

Brave | 0.61.17 Chromium: 72.0.3626.81 (Official Build) dev(64-bit)
-- | --
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Yes

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.61.38 Chromium: 73.0.3683.39 (Official Build) beta (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

Used test plan from https://github.com/brave/brave-core/pull/1636
