### ISSUE TITLE
Hide Panel Nav when DApp Connection Settings is open

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#32815]
## Description 

We need to hide the `Panel Nav` when the `DApp Connection Settings` is open.

## Steps to Reproduce

   1. Open the Wallet `Panel` and then open the `DApp Connection Settings`
   2. The `Panel Nav` is still visible

## Actual result:

![Screenshot 76](https://github.com/brave/brave-browser/assets/40611140/a16b5915-d977-4b93-9214-b8d766aabe8f)

## Expected result:
Should be blurred out like everything else.

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.60.102 Chromium: 118.0.5993.96 (Official Build) beta (64-bit)
-- | --
Revision | 3598a9fc6b7752181feb25caa131bc386d6d054c
OS | Windows 11 Version 22H2 (Build 22621.2428)

- Verified steps from [brave/brave-core#20031](https://github.com/brave/brave-core/pull/20031)
- Verified Panel navigation bar is blurred when DApp connection settings is opened

https://github.com/brave/brave-browser/assets/17010094/a9af6c99-1045-4b47-a783-ecfbca865779
