### ISSUE TITLE
`Brave AI` tooltip text on the sidebar should read `Brave Leo`

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#32811]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/30590

## Steps to Reproduce

1. Install 1.59.76
2. launched Brave
3. opened `brave://flags` in a new tab
4. enabled `#brave-ai-chat`
5. mouseover on `BraveAI` icon on the Sidebar

## Actual result:

Tooltip text reads `BraveAI`  
<image width="400" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/e95d96db-5072-4046-85e9-1b536b970395">

## Expected result:
Tooltip text should read `Brave Leo` 

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.59.76 Chromium: 116.0.5845.163 (Official Build) nightly (64-bit)
-- | --
Revision | 882a1d617108cea1c78439e27c5f19c46b276508
OS | Windows 11 Version 22H2 (Build 22621.2134)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
@rebron @vadimstruts 
cc: @bbondy

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.61.5 Chromium: 118.0.5993.54 (Official Build) nightly (x86_64)
-- | --
Revision | 0787df601ff078d4344102d73a7be56d520137b0
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.61.5`
2. launched Brave
3. restarted (to pick up Griffin seed)
4. hovered over the `Brave Leo` icon on the sidebar
5. looked at the tooltip

### Confirmed tooltip reads `Brave Leo`

<img width="161" alt="Screen Shot 2023-10-08 at 9 57 16 PM" src="https://github.com/brave/brave-browser/assets/387249/225c862d-2230-4243-9851-6c4aa074449d">

**Comment by stephendonner** [comment]
Also verified using

```
Brave | 1.60.81 Chromium: 118.0.5993.54 (Official Build) beta (x86_64)
-- | --
Revision | 1efb3f333eb41cc34af46ca31fb33c30e0afbfae
OS | macOS Version 11.7.10 (Build 20G1427)
```

**Comment by stephendonner** [comment]
@vadimstruts this needs a milestone.  Please set the appropriate one it landed in.  Thanks.
