### ISSUE TITLE
Remove "passive" mouse events from the browser

### ISSUE THREAD

**Issue by pes10k** [brave/brave-browser#3282]
Seems like greater possibility for misuse than user-serving use

## Description 
> No doubt that there is some possible use for it, but I expect the common use is "users are complaining about the performance implications of my user tracking record-replay code, help me hide it better"

Passive mouse events allow JS code to register for "eventual", non-blocking callbacks for mouse events.  Currently covers touch events, new chromium adds mouse wheel events 

## References
https://blog.chromium.org/2019/02/chrome-73-beta-constructable.html

**Comment by tomlowenthal** [comment]
It'd be good to know if we're going to trip over a webcompat hurdle here, but 🤷‍♂️ .

**Comment by snyderp** [comment]
We still have a chance to get ahead of this and keep it from becoming (another) webcompat hell.  Mozilla and Safari seem to be on the fence about implementation.  Maybe we could try to do some (first of many?) PR release saying "WEB DON'T USE THIS".  EG a coordinate "intent to not implement" campaign
