### ISSUE TITLE
Brave crashes when navigate to More tools->Guest profile>settings menu

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#32825]
## Description 

Brave crashes when navigate to More tools->Guest profile>settings menu
## Steps to Reproduce

   1. Clean profile 1.60.1
   2. Click on the hamburger settings menu
   3. Click on More tools and select Guest profile
   4. Click on settings in guest window

## Actual result:

Brave crashes

```
Uploaded Crash Report ID:	51290100-30cd-ae0a-0000-000000000000
Upload Time:	Thursday, September 7, 2023 at 11:10:05 AM

```
## Expected result:
Should not be any crash

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.60.1 Chromium: 117.0.5938.35 (Official Build) nightly (64-bit)
-- | --
Revision | d50ecb0e74c51a1b522750008a9de6e61e8dabc8
OS | Windows 10 Version 22H2 (Build 19045.3324)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @rebron @mkarolin

**Comment by mkarolin** [comment]
Not related to cr117. Reproduceable in `1.59.76 Chromium: 116.0.5845.163 (Official Build) nightly (64-bit) `.
cc: @spylogsster

**Comment by LaurenWags** [comment]
Added `OS/Windows` label as this doesn't reproduce on macOS with same version

```
Brave | 1.59.76 Chromium: 116.0.5845.163 (Official Build) nightly (x86_64)
-- | --
Revision | 882a1d617108cea1c78439e27c5f19c46b276508
OS | macOS Version 13.5.1 (Build 22G90)
```

<img width="1203" alt="guest" src="https://github.com/brave/brave-browser/assets/28145373/09b1a303-401a-401f-ad23-ba1905553152">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.60.81 Chromium: 118.0.5993.54 (Official Build) beta (64-bit)
-- | --
Revision | 1efb3f333eb41cc34af46ca31fb33c30e0afbfae
OS | Windows 11 Version 22H2 (Build 22621.2283)
```

Reproduced the issue in `1.60.1 Chromium: 117.0.5938.35 nightly` using STR  https://github.com/brave/brave-browser/issues/32825#issue-1885159549 


1. Installed 1.60.81
2. launched Brave
3. Click on the hamburger settings menu
4. Click on More tools and select `Open Guest profile`
5. Click on hamburger menu > Settings in guest window

Confirmed brave://settings page shown without the crash

step 4 | step 5 | result
----- | ---- | ------
<img width="954" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/217e47b7-ef2b-4b1c-b2f2-68e89465bda9">|<img width="949" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/80bb67b8-b103-4e0f-b40d-8ba0abbf63b7">|<img width="956" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/eacddd34-9870-42cc-8bb0-580ee1b7fc00">

**Comment by kjozwiak** [comment]
Closing as https://github.com/brave/brave-core/pull/20041 fixes the above issue and is already in `1.61.x` (Nightly) & `1.60.x` (BETA) and will be uplifted into `1.59.x` via https://github.com/brave/brave-core/pull/20518.

**Comment by kjozwiak** [comment]
Removing `QA Pass-Win64` as the above will need to be rechecked via `1.59.x` now that it's been uplifted via https://github.com/brave/brave-core/pull/20518. The above requires `1.59.119` or higher for `1.59.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.59.120 Chromium: 118.0.5993.88 (Official Build) (64-bit)
-- | --
Revision | 135f92a9af2134bc7d7aeba82f87ff5e68669410
OS | Windows 10 Version 22H2 (Build 19045.3570)

```
- Verified the STR from the description and ensured there is no crash
