### ISSUE TITLE
Vertical tab  drag and drop support for links

### ISSUE THREAD

**Issue by samirgaire10** [brave/brave-browser#32821]
## Description 

ok!

## Steps to Reproduce

   1. hold a link 
   2. drag and try to drop link on vertical tab

## Reproduces how often: 

very often  // always 

## Brave version (brave://version info)

Desktop
Release Notes v1.57.62 (Sep 6, 2023)

## Version/Channel Information:

yes

- Can you reproduce this issue with the current release? 
-yes
- Can you reproduce this issue with the beta channel? 
yes
- Can you reproduce this issue with the nightly channel? 
yes
## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- no 
- Does the issue resolve itself when disabling Brave Rewards? 
- no
- Is the issue reproducible on the latest version of Chrome? 
no

## Miscellaneous Information:

 The brave  browser does not support drag and drop functionality on vertical tabs. However, Brave  do have drag and drop support on horizontal tabs, which you can use to easily move links around.
If you would like to request drag and drop support for vertical tabs, 
I am using garuda linux nightly build brave but vertical tabs drag and drop link doesn`t support on other build too .
```[tasklist]
### Tasks
```

**Comment by rebron** [comment]
@samirgaire10 Are you trying to drag a link from a web page over to the vertical tabs space?

**Comment by samirgaire10** [comment]
It doesnt work from  anywhere bookmarks , searchbar ,links . In horizental tab it works normally which is kinda useful .

**Comment by Emi-TheDhamphirInLoveUnderTheFrozenStar** [comment]
This is a duplicate, I made the issue https://github.com/brave/brave-browser/issues/31492 long time ago, and now it has a PR to address it https://github.com/brave/brave-core/pull/19785 which should be available in Nightly someday soon, and eventually reach Stable, someday later this year.

Next time use the search function first to avoid duplicates, people need to learn that; especially in this case where a simple search would have shown my issue easily. I know sometimes some issues might be hidden under a very specific way where you might file the issue and don't know you are creating a duplicate, but that's not the case here.

In fact, it is a problem with the Vertical tabs, a missing feature, so it will not work until that PR gets merged, it works in Horizontal tabs, so switch to it if you need that feature.

**Comment by samirgaire10** [comment]
Ok  thank you .I apologize for making a duplicate issue request .  I will try to not make any duplicate . this is my first few time to issue  Issue request 😅. I will close this issue . have a nice day🙂🙂
