### ISSUE TITLE
`Password manager` settings icon is missing 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#32826]
## Description 

`Password manager` settings icon is missing 

## Steps to Reproduce

   1. Clean profile 1.60.1
   2. Click on the Hamburger settings menu
   3. `Password manager` settings icon is missing 

## Actual result:

![image](https://github.com/brave/brave-browser/assets/38657976/43baa1ec-dbbf-47ac-ae68-d4484d12ef76)

## Expected result:

icon should be displayd
## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.60.1 Chromium: 117.0.5938.35 (Official Build) nightly (64-bit)
-- | --
Revision | d50ecb0e74c51a1b522750008a9de6e61e8dabc8
OS | Windows 10 Version 22H2 (Build 19045.3324)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @rebron @mkarolin

**Comment by LaurenWags** [comment]
Seems related to https://github.com/brave/brave-browser/issues/32089
