### ISSUE TITLE
When Autoredirect is enabled loading https link doesn't redirects to ipns. Only loads on ipns when clicking the IPFS badge

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#32829]
When `Automatically redirect requests for IPFS network resources to the configured gateway.` is enabled, visiting `https://en.wikipedia-on-ipfs.org/wiki/` doesn't redirect to `ipns://en.wikipedia-on-ipfs.org/wiki/`. Only loads the `ipns` link when clicking on the IPFS badge. 

https://github.com/brave/brave-browser/assets/17010094/0cae356d-1139-44d9-ad55-8cc77be6664c

Note: Loading `https://ipfs.io/ipfs/QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR` auto-redirects to `ipfs://bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi`

**Comment by kjozwiak** [comment]
The above requires `1.58.120` or higher for `1.58.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.58.120 Chromium: 117.0.5938.48 (Official Build) (64-bit)
-- | --
Revision | 8b2e2785c90c076fc1413acb2c003e603eac02d3
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from issue description
- Verified when auto redirect is enabled https link redirects to ipns link

https://github.com/brave/brave-browser/assets/17010094/a9c46bd1-6b04-4ce1-bcf6-5cc37936b598
