### ISSUE TITLE
Ensure 'Back up Now' button is also on hambuger menu in the panel

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#32839]
## Description 

Right now, you can only access the back up now button from the full window view. It should also be accessable from the panel view in the hamburger menu. 

cc @kleantzogu @Douglashdaniel 

![Screenshot 2023-05-18 at 15 51 23](https://github.com/brave/brave-browser/assets/12224304/b570a8c2-1404-4cb8-a08e-ea6a11103fe3)

## Steps to Reproduce

   1. try get your recovery phrase from the panel, you can't
   2. you have to access it via full webview
   3. 

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.59.93` or higher for `1.59.x` verification 👍

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.59.112 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | `967f25f295938c64c24e2e6a1790470668757655`
OS | Windows 11 Version 22H2 (Build 22621.2283)

- Verified steps from [brave/brave-core#20073](https://github.com/brave/brave-core/pull/20073)
- Verified backup button loads the backup screen in a new tab
- Encountered [#33112](https://github.com/brave/brave-browser/issues/33112)

https://github.com/brave/brave-browser/assets/17010094/0699ba4f-5b29-4b60-87f2-e9e18aab33e3

---------------------

**Verification passed on**

Brave | 1.59.112 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | `967f25f295938c64c24e2e6a1790470668757655`
OS | Linux

- Verified steps from [brave/brave-core#20073](https://github.com/brave/brave-core/pull/20073)
- Verified backup button loads the backup screen in a new tab
- Encountered [#33112](https://github.com/brave/brave-browser/issues/33112)

https://github.com/brave/brave-browser/assets/17010094/cde98388-ef3d-45bf-8103-8c26ef4b275a


---------------------

**Verification passed on**

Brave | 1.59.112 Chromium: 118.0.5993.54 (Official Build) (arm64)
-- | --
Revision | `967f25f295938c64c24e2e6a1790470668757655`
OS | macOS Version 14.0 (Build 23A344)

- Verified steps from [brave/brave-core#20073](https://github.com/brave/brave-core/pull/20073)
- Verified backup button loads the backup screen in a new tab
- Encountered [#33112](https://github.com/brave/brave-browser/issues/33112)

https://bravesoftware.slack.com/archives/D1U8KRFS5/p1696518840279569
