### ISSUE TITLE
Open about brave via Guest window causes brave crash

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#32831]
## Description 

Open about brave via Guest window causes brave crash
## Steps to Reproduce

   1. Clean profile 1.60.1
   2. Click on the hambuger settings menu
   3. Click on More tools and select Guest profile
   4. Click on  hambuger menu in guest window
   5. Click on `Help->About Brave`
   6. Brave crashes

## Actual result:

Open about brave via Guest window causes brave crash

```
Uploaded Crash Report ID:	117c0100-30cd-ae0a-0000-000000000000

```
## Expected result:
Should not be any crash

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.60.1 Chromium: 117.0.5938.35 (Official Build) nightly (64-bit)
-- | --
Revision | d50ecb0e74c51a1b522750008a9de6e61e8dabc8
OS | Windows 10 Version 22H2 (Build 19045.3324)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @rebron @mkarolin

**Comment by rebron** [comment]
@GeetaSarvadnya Can you check to see to see if we can close this one out too?
https://github.com/brave/brave-browser/issues/32825#issuecomment-1768305205

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.59.120 Chromium: 118.0.5993.88 (Official Build) (64-bit)
-- | --
Revision | 135f92a9af2134bc7d7aeba82f87ff5e68669410
OS | Windows 10 Version 22H2 (Build 19045.3570)

```

And

```
Brave | 1.61.50 Chromium: 119.0.6045.33 (Official Build) nightly (64-bit)
-- | --
Revision | af3c0e1d93ee4b2e9b98a4e4cf3e7fb2a85442ee
OS | Windows 10 Version 22H2 (Build 19045.3570)

```
- Verified the STR from the description and ensured there is no crash
