### ISSUE TITLE
IPFS badge is not shown when visiting a page for the first time that supports ipfs/ipns redirect. Reload shows the badge again

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#32830]
* Verify that loading `https://ipfs.io/ipns/libp2p.io/` shows an IPFS button in the URL bar, and clicking it redirects to `ipns://libp2p.io/`. Confirm it resolves and loads.
 
This test from IPFS manual test is failing. When the page is loaded for the first time it shows the new IPFS redirect bar. Selecting `Always` from the setting sets but visiting the same page again in a new tab it doesn't show the badge have to reload the page second time for it show up

https://github.com/brave/brave-browser/assets/17010094/405c26d6-4c5d-4926-a194-9ea03615b6c7

**Comment by kjozwiak** [comment]
The above requires `1.58.120` or higher for `1.58.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.58.120 Chromium: 117.0.5938.48 (Official Build) (64-bit)
-- | --
Revision | 8b2e2785c90c076fc1413acb2c003e603eac02d3
OS | Windows 11 Version 22H2 (Build 22621.2215)

- Verified steps from issue description
- Verified visiting `https://ipfs.io/ipns/libp2p.io/` with resolve set to local node is redirect to `ipns://ipfs.io/`

https://github.com/brave/brave-browser/assets/17010094/9d42cb02-8cae-40d9-bc34-9a4c58a75d04
