### ISSUE TITLE
[Android] YT Improvements: Quick-search engines bar

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#32843]
## Description
See `Quick-search engines bar with YouTube` and `Requirements` sections here:
https://bravesoftware.slack.com/archives/CELA35G5S/p1694106384308469?thread_ts=1671572756.471319&cid=CELA35G5S

**Comment by Uni-verse** [comment]
Need uplifts to 1.74 created

**Comment by hffvld** [comment]
Verified on `Galaxy Tab S8` and `Pixel 7` using version(s):
```
Device/OS: 
- Galaxy Tab S8 / gts8wifixx-user 14 UP1A.231005.007 release-keys
- Pixel 7 / panther_beta-user 15 AP41.240925.009 release-keys
Brave build: 1.74.13 
Chromium: 131.0.6778.85 (Official Build) beta (64-bit) 
```

Filed follow-up issue #42567
---------------------------
<details>
<summary> Fresh profile </summary>

**STEPS:**
1. Fresh install Brave Beta `1.74.13` or higher
2. Go through onboarding
3. Open `NTP`
4. Tap in the `URL search bar`
5. Type a query > *Verify that the QSE toolbar is shown and includes the `YT` thumbnail*
6. Tap `YT search` thumbnail > *Verify that the YT website is opened and search results are shown*
7. Type another query in the `URL search bar` > Tap ⚙️ icon > *Verify that `YT` is shown*
8. Disable `YT` > Close the settings screen
9. Type a query again > *Verify that `YT` is not shown*
10. Re-enable `YT` > Type a query > *Verify that `YT` is shown and works*
 
**ACTUAL RESULTS:**
- Verified that `QSE` is not shown until the user starts typing a query in the `URL search bar`.
- Verified that the `YT` search is shown in the QSE toolbar.
- Verified that the `YT search` works and that the search results are shown as expected on YT website.
- Verified that `YT` is shown in the QSE settings.
- Verified that `YT` can be disabled/enabled in the QSE settings.

---------------------------

`Galaxy Tab S8`

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/9bebae36-fe6d-4540-815a-7fca94e55397) | ![2](https://github.com/user-attachments/assets/349812cf-4f08-46b0-9296-8ed0d96af280) | ![3](https://github.com/user-attachments/assets/ba1b910c-6d77-4d88-9bd0-dfbf487e747a) |
| ![1](https://github.com/user-attachments/assets/9b04b5ac-d722-49d7-8f84-799eb0d0b05a) | ![2](https://github.com/user-attachments/assets/5f9e4930-b85f-49bb-ad81-c4004cd5245b) | ![3](https://github.com/user-attachments/assets/94870228-d24d-490f-bcba-160a1eaaf30a) |

`Pixel 7`

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/09570471-f2fa-4e7f-a593-1d5edb31f19d) | ![2](https://github.com/user-attachments/assets/00d4086c-ca0a-4f99-84a6-27f9e2bf0143) | ![3](https://github.com/user-attachments/assets/089bf723-c371-4864-87cf-6528bb304a61) |
| ![1](https://github.com/user-attachments/assets/e5c4f055-92fe-4b6b-b2ab-2efab69b2814) | ![2](https://github.com/user-attachments/assets/8e54d025-cebf-42ce-a1ea-10a7c66e0cc4) | ![3](https://github.com/user-attachments/assets/6b4df297-b917-4c4c-948f-20949747ee90) |
</details>

<details>
<summary> Upgraded profile </summary>

**STEPS:**
1. Install Brave Beta `1.74.10` (it was previously available in the Play Store)
2. Go through onboarding
3. Open `NTP`
4. Tap in the `URL search bar` > Type a query > *Observe that `YT search` thumbnail is not shown*
5. Tap ⚙️ icon > *Observe that `YT search` is not shown*
6. Upgrade Brave to Beta `1.74.13` or higher
7. Launch Brave > Type a query again > *Verify that `YT search` thumbnail is shown*
8. Tap ⚙️ icon > *Verify that `YT` is shown*
9. Close the settings screen
10. Type a query > Tap `YT` > *Verify that results are shown with `YT search`*

- Observed that the `YT` search didn't shown in the QSE toolbar and in the settings after Brave upgraded to a new build.

---------------------------

`Galaxy Tab S8`

https://github.com/user-attachments/assets/864cba11-2308-43ff-8a56-3cfa91b6d5f7

`Pixel 7`

https://github.com/user-attachments/assets/b964c296-c619-4a69-a18a-0491e9b1fb16
</details>
