### ISSUE TITLE
Externalize HTTP Accept-Language farbling

### ISSUE THREAD

**Issue by pilgrim-brave** [brave/brave-browser#32848]
We now have three semi-permanent hard-coded exceptions. When webcompat issues are identified, we need to be able to push out an exception quickly while we investigate the underlying issue. (This occurred recently with t-Mobile's account site -- now resolved, but without the ability to push out an exception, the site remained broken longer than it could have.)

**Comment by ShivanKaul** [comment]
This is superseded by the Webcompat Exception Manager.
