### ISSUE TITLE
Update `Add to Brave` text on extensions web store

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#32841]
## Description 

At the chrome web store (preview and upcoming redesign), the Add to Brave button has regressed and shows Add to Chrome. Needs to show Add to Brave.

## Steps to Reproduce

   1. Go to `https://chromewebstore.google.com/detail/webchatgpt-chatgpt-with-i/lpfemeioodjbpieminkklglpmhlngfcn`
   2. Notice Add to Chrome button
   3. Should say Add to Brave with our styling.

## Actual result:

![Screenshot 2023-09-07 at 9 56 11 AM](https://github.com/brave/brave-browser/assets/5951041/bef3bf65-a940-4e1f-ac6b-cd4a0700d866)

## Expected result:
`https://chrome.google.com/webstore/detail/webchatgpt-chatgpt-with-i/lpfemeioodjbpieminkklglpmhlngfcn`
![Screenshot 2023-09-07 at 9 58 50 AM](https://github.com/brave/brave-browser/assets/5951041/8a7c5278-a01a-40b3-b6f8-295d4a226b49)

## Reproduces how often: 

Easily.

## Brave version (brave://version info)

chrome web store preview version

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by kjozwiak** [comment]
The above requires `1.58.128` or higher for `1.58.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.58.128 Chromium: 117.0.5938.88 (Official Build) (64-bit)
-- | --
Revision | 171b8e11a776dc3f1472bc4f593caf36463b40c7
OS | Windows 10 Version 22H2 (Build 19045.3448)
```
Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/32841#issue-1886277897, ensured that the correct button was being used via `https://chrome.google.com/webstore` and ensured that `Brave` was being used rather than `Chrome` as per the following:

**`Example`** | **`Example`**
----------------|----------------
![image](https://github.com/brave/brave-browser/assets/38657976/2637754d-22e3-4e69-a7ec-530f8bd9db64) | ![image](https://github.com/brave/brave-browser/assets/38657976/a8c3c8c5-31e1-4f51-a7ea-7d328230d928)

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.58.128 Chromium: 117.0.5938.88 (Official Build) (x86_64)
-- | --
Revision | 171b8e11a776dc3f1472bc4f593caf36463b40c7
OS | macOS Version 13.5.2 (Build 22G91)
```

**Comment by LaurenWags** [comment]
@rebron @zenparsing looks like when viewing the chrome store redesign via the "Preview" option, the "Add to Brave" button is pill shaped (see my screenshots above), not the rectangle with rounded corners as it was previously (see @GeetaSarvadnya screenshots). Is this ok?

**Comment by rebron** [comment]
That's ok with the button shape. We just want the text to be updated.
