### ISSUE TITLE
"Open in new tab" is shown in the context menu, but corresponding toggle switch is still not added to the Settings -> Appearance

### ISSUE THREAD

**Issue by vlad-hoff** [brave/brave-browser#32854]
## Description 

`Open in new tab` is shown in the context menu, but the corresponding toggle switch `Only open links in current tab group` is still not added to the `Settings` -> `Appearance`.

## Steps to reproduce 

   1. Launch Brave
   2. Open NTP > Top sites
   3. Tap and hold on any of them > Confirm that `Open in new tab` is shown in the context menu
   4. Now go to `Settings` > Appearance > Observe that `Only open links in current tab group` toggle switch is not shown

## Actual result 

`Open in new tab` is shown in the context menu, but the corresponding toggle switch `Only open links in current tab group` is still not added to the `Settings` -> `Appearance`.

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/28a97847-fb45-4a24-93f4-f799bd43aba1) | ![2](https://github.com/brave/brave-browser/assets/128532965/95cab5d3-9c2d-46bf-910c-72d87822a639) |

## Expected result

`Only open links in current tab group` toggle switch must be shown in the `Settings` -> `Appearance` to match the tablet experience with the phone.

## Issue reproduces how often 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? No
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Galaxy Tab S8 (Tablet)
   - Android version: Android 13
   
## Brave version

Brave build: 1.60.3
Chromium: 117.0.5938.35 (Official Build) canary (64-bit)
Revision: 6f3491e9658c636314365097686bdbd636d39163

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.58.122` or higher for `1.58.x` verification 👍

**Comment by LaurenWags** [comment]
@samartnik should this be `release-notes/include` or `release-notes/exclude`?

**Comment by samartnik** [comment]
should this `release-notes/include`, i updated it
