### ISSUE TITLE
Log errors that occur within the api slice

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#32858]
## Description 

We should log errors that occur within the api slice to help troubleshoot production issues

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.60.81 Chromium: 118.0.5993.54 (Official Build) beta (64-bit)
-- | --
Revision | 1efb3f333eb41cc34af46ca31fb33c30e0afbfae
OS | Windows 11 Version 22H2 (Build 22621.2283)

- Verified steps from issue description
- Verified no errors show up when trying to send any tokens
