### ISSUE TITLE
"Open in new tab" is not working as expected and instead is opening a new tab in group

### ISSUE THREAD

**Issue by vlad-hoff** [brave/brave-browser#32853]
## Description 

`Open in new tab` is not working as expected and instead working the same way as `Open in new tab in group`.

## Steps to reproduce 

   1. Launch Brave
   2. Open NTP > Top sites
   3. Tap and hold on any of them > In the context menu tap `Open in new tab`
   4. Tap `Switch tabs` button > Observe
   5. Now close all tabs > Open https://wikipedia.org
   6. Tap and hold on any link > Open in new tab
   7.  Tap `Switch tabs` button > Observe

## Actual result 

`Open in new tab` is not working as expected and instead working the same way as `Open in new tab in group`. The issue is not happening in the previous Brave build with `C116`, because `Open in new tab` in the context menu is not available there.

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/0179eba1-590b-497c-9885-c3597df027a3) | ![2](https://github.com/brave/brave-browser/assets/128532965/50e11f5e-0bd4-4c19-a733-222f60e237bf) | ![3](https://github.com/brave/brave-browser/assets/128532965/cfeb8e2f-d892-474d-99bf-1ec7514f1931) |

https://github.com/brave/brave-browser/assets/128532965/b9dd7339-a001-4080-b53b-54f4ff8fddad

## Expected result

`Open in new tab` must open a link in the new tab, but not in the `group tab`.

## Issue reproduces how often 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? No
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Galaxy Tab S8 (Tablet)
   - Android version: Android 13
   
## Brave version

Brave build: 1.60.3
Chromium: 117.0.5938.35 (Official Build) canary (64-bit)
Revision: 6f3491e9658c636314365097686bdbd636d39163

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.58.122` or higher for `1.58.x` verification 👍

**Comment by LaurenWags** [comment]
@samartnik should this be `release-notes/include` or `release-notes/exclude`?

**Comment by samartnik** [comment]
should this `release-notes/include`, i updated it
