### ISSUE TITLE
WebTorrent imperfections

### ISSUE THREAD

**Issue by leobel96** [brave/brave-browser#3285]
## Description 
Missing percentage and measuring unit for file size in WebTorrent

## Test plan / Steps to Reproduce

   1. Visit https://webtorrent.io/torrents/sintel.torrent
   2. Click `Start torrent`

## Actual result:

![inkedannotazione 2019-02-08 230030_li](https://user-images.githubusercontent.com/19806799/52508940-a44d7680-2bf6-11e9-902a-b426f4612708.jpg)

## Expected result:

![inkedannotazione 2019-02-08 230030_li](https://user-images.githubusercontent.com/19806799/52509526-cd6f0680-2bf8-11e9-8073-f9efcd14026b.jpg)

## Reproduces how often: 
Easily

## Brave version (brave://version info):
0.59.35 Chromium: 72.0.3626.81 (Build ufficiale) (a 64 bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? No

### Additional Information
Also it would be good the presence of upload speed

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.69.119 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
OS | Linux

![image](https://user-images.githubusercontent.com/17010094/63974791-8b65bf00-ca7b-11e9-832b-bc7ed1f638df.png)
