### ISSUE TITLE
Folder icons for Bookmarks Toolbar changed

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#32851]
## Description 
Latest Nightly has updated the icons for folders in the bookmarks toolbar. This is a controversial change - I believe unintentionally changed by either by having chrome://flags/#chrome-refresh-2023 enabled OR after https://github.com/brave/brave-core/pull/19819 was merged.

## Steps to Reproduce

   1. Launch latest Nightly on Windows

## Actual result:
Shows as outlined
![image](https://github.com/brave/brave-browser/assets/4733304/9ff79a34-0b2d-4d83-a9a0-41e6b2332d7e)

## Expected result:
Should be yellow on Windows and Gray (gradient) on macOS/Linux
![image](https://github.com/brave/brave-browser/assets/4733304/aa362b86-f742-496f-aec3-57d2bca69377)

## Reproduces how often: 
100%

## Version/Channel Information:

- Can you reproduce this issue with the current release? N (1.57)
- Can you reproduce this issue with the beta channel? N (no on 1.58; yes on 1.59)
- Can you reproduce this issue with the nightly channel? Y (1.60)

**Comment by kjozwiak** [comment]
I could be wrong but I don't think it's related to `brave://flags/#chrome-webui-refresh-2023`. I have that flag disabled on my Nightly daily driver and seeing the non-yellow icons as well. Example:

**`Example`** | **`Example`**
----------------|-----------------
![image](https://github.com/brave/brave-browser/assets/2602313/9f14e762-b658-4a4b-ae77-eb5235a0e57c) | ![image (1)](https://github.com/brave/brave-browser/assets/2602313/5cb54ac1-4c1f-492e-a3e5-fec708ba19b3)

**Comment by kjozwiak** [comment]
Adding the `release/blocking` on `1.60.x` (Nightly) as we need to make sure this doesn't make it's way to release. We changed the icons once before which upset a good amount of users as per https://github.com/brave/brave-browser/issues/17463.

**Comment by Saikur0n** [comment]
I actually prefer those monochrome icons on windows. 😃 I don't like yellow icons on bookmarks toolbar. I mean at least the way how they look now. Open bookmarks settings page and you will see monochrome hollow icons, open sidebar - bookmarks section and you will see completely different yellow folders, then add any page to bookmark and edit it. In this bookmarks edit window the bookmarks folder icons same as in sidebar. There is no one design language. If bookmarks folder icons will be same everywhere, that would be nice, but now it seems completely inconsistent. I think chrome refresh design tends to have similar icons everywhere.

**Comment by fallaciousreasoning** [comment]
@Saikur0n me too :laughing: For now we're going to revert this change, but we'll have our design team take a look :smile:

**Comment by Saikur0n** [comment]
I would like to add that icon looks blurred on my Vivobook Pro 14 with screen resolution 2880x1800 on 14 inches. Implement higher resolution icon. For example on microsoft edge it looks great, also it has outlines. Take a look. There is room for improvement.

**Comment by fallaciousreasoning** [comment]
@Saikur0n agreed - we definitely need to introduce some higher res versions of these icons

**Comment by kjozwiak** [comment]
> @fallaciousreasoning @kjozwiak I would like to add that icon looks blurred on my Vivobook Pro 14 with screen resolution 2880x1800 on 14 inches. Implement higher resolution icon. For example on microsoft edge it looks great, also it has outlines. Take a look. There is room for improvement. Compare: ![Screenshot 2023-09-10 232535](https://user-images.githubusercontent.com/72514237/266861094-93d214c5-57ca-486a-ac94-bcc39064482d.png)
> 
> ![Screenshot 2023-09-10 232630](https://user-images.githubusercontent.com/72514237/266861100-e38e4596-4201-45a8-a476-3b11b2ca3d82.png)

@Saikur0n mind creating a new issue using the template [here](https://github.com/brave/brave-browser/issues/new?assignees=&labels=OS%2FDesktop&projects=&template=desktop.md&title=)? This way it will have a better chance to get prioritized/get worked on as the above issue is technically fixed re: reverting back to the old folders.

**Comment by kjozwiak** [comment]
The above requires `1.59.84` or higher for `1.59.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.59.86 Chromium: 117.0.5938.62 (Official Build) beta (64-bit)
-- | --
Revision | 3c4c1c3b2eef0fcbe8485c67e1df504942deadca
OS | Windows 11 Version 22H2 (Build 22621.2283)
```


Reproduced the issue in 1.59.78 using STR from https://github.com/brave/brave-browser/issues/32851#issue-1886350893

![image](https://github.com/brave/brave-browser/assets/98358127/e1f12c75-5204-4108-bd07-d67e80f14eac)

Steps: 

1. Installed 1.
2. launched Brave
3. clicked `Import bookmarks now.. link in the NTP
4. selected `Microsoft Edge Profile 1` in the `Import bookmarks and settings` dialog
5. retained all selections including `favorites/bookmarks and clicked `Import`
6. clicked `Done`

#### Confirmed yellow icons for folders are shown in the bookmarks toolbar 

step 4 | step 6 | result
---- | ----- | ----
<img width="954" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/609f9e05-90fd-4a6d-8955-f70134c56f5f">|<img width="958" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/502916dc-a997-4626-a381-b94e8850a238">|<img width="961" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/6d8143fb-d49a-4fae-92aa-6682aa1c31c6">

**Comment by stephendonner** [comment]
## Verification `PASSED` using 

```
Brave | 1.59.90 Chromium: 117.0.5938.88 (Official Build) beta (x86_64)
-- | --
Revision | 5272112c86588e44ec7c0b766c318cddccbced85
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.59.90`
2. launched Brave
3. imported profile w/bookmarks from `Google Chrome Person 1`
4. examined the bookmarks folders
5. switched from `Light` mode to `Dark` mode

### Confirmed the folder icons on the browser toolbar are a gray gradient (NOT outlined as was the regression)

`Dark` | `Light`
-------|-------
<img width="1771" alt="Screen Shot 2023-09-17 at 7 16 47 PM" src="https://github.com/brave/brave-browser/assets/387249/0ea8e780-7f2b-4ba9-83e7-7dbff99c4812"> | <img width="1771" alt="Screen Shot 2023-09-17 at 7 17 14 PM" src="https://github.com/brave/brave-browser/assets/387249/00e48161-e31b-4b13-a209-db7ce4396b68">

`Dark` | `Light`
-------|--------
<img width="228" alt="Screen Shot 2023-09-17 at 7 20 15 PM" src="https://github.com/brave/brave-browser/assets/387249/9033ab78-bb3d-4c3d-85ba-7f1ab44c137c"> | <img width="223" alt="Screen Shot 2023-09-17 at 7 19 53 PM" src="https://github.com/brave/brave-browser/assets/387249/8228f864-8e4c-4ec1-b38c-2979a5562294">

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave	1.59.103 Chromium: 117.0.5938.140 (Official Build) beta (64-bit) 
Revision	e0f257d585b29dd1194e82717cf18db50a7c0edb
OS	Linux
```

Steps: 

1. Installed 1.59.103
2. launched Brave
3. clicked `Import bookmarks now.. link in the NTP
4. selected `Microsoft Edge Profile 1` in the `Import bookmarks and settings` dialog
5. retained all selections including `favorites/bookmarks` and clicked `Import`
6. clicked `Done`

#### Confirmed gray icons for folders are shown in the bookmarks toolbar 

step 4-6 | result | result
---- | ----- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/1838863d-013e-4ea4-a0d9-2b568a3aea01)|![image](https://github.com/brave/brave-browser/assets/98358127/16d9c91b-17c5-4bdf-b880-5966ed29e788)|![image](https://github.com/brave/brave-browser/assets/98358127/e31de992-7990-4506-8f91-f4b563bde547)
