### ISSUE TITLE
History is not synced on fresh profile [C117]

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#32857]
## Description 
History is not synced on fresh profile [Android]

## Steps to reproduce 

   1. Create sync chain on MacOS client existing profile
   2. Connect to sync chain on fresh install
   3. Enable history syncing
   4. Open History page 

## Actual result 
![Screenshot 2023-09-07 at 4 32 05 PM](https://github.com/brave/brave-browser/assets/17885425/422320e4-c855-4f5e-9d64-386ab37464f3)

## Expected result
History should show up

## Issue reproduces how often 
Always (fresh profile)

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? TBD
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung GS 21
   - Android version: 13
   
## Brave version
`1.60.2 Chromium 117.0.5938.35`

**Comment by stephendonner** [comment]
This also affects desktop as well (`1.60.1`-`1.60.6`):

```
Brave | 1.60.6 Chromium: 117.0.5938.48 (Official Build) nightly (x86_64)
-- | --
Revision | 3729c99b569a7aab570e3f55471c699556e539f9
OS | macOS Version 14.0 (Build 23A5337a)
```


I tried the combinations of starting a Sync chain from either/both desktop and mobile, and connected those to `nightly` and `release` builds.

* `release` <-> `release` (android/desktop - and vice-versa) :white_check_mark:
* `nightly` <-> `release` (android/desktop - and vice-versa) :x:
* `nightly` <-> `nightly` (android/desktop - and vice-versa) :x:

The only time typed URLs are synced in `brave://history` between mobile and desktop clients are when both are on `release`, per my testing (likely works on `beta`, but I haven't yet checked there.)

Note: this only affects *typed* URLs; pages visited in tabs are synced correctly from mobile to desktop via `Synced tabs from other devices`.

**Comment by kjozwiak** [comment]
The above requires `1.58.121` or higher for `1.58.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version:

```
Brave	1.58.121 Chromium: 117.0.5938.48 (Official Build) (32-bit) 
Revision	d80a8110b88df6ae5073d8420fada4168542786f
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
- Verified fix using STR in https://github.com/brave/brave-browser/issues/32857#issue-1886583634
- Verified typed URLs are synced after connecting to sync chain. 

Example | Example
-|-
![Screenshot 2023-09-12 at 12 28 57 PM](https://github.com/brave/brave-browser/assets/17885425/5fb2e3c2-bdee-484e-a108-67d898e59db3) | ![Screenshot 2023-09-12 at 12 29 31 PM](https://github.com/brave/brave-browser/assets/17885425/32261108-d0e2-4ea6-9a45-afa53cda6988)

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.59.84 Chromium: 117.0.5938.48 (Official Build) beta (x86_64)
-- | --
Revision | 1dc90873649e32fb7d316ed9b238310d5e99b0f1
OS | macOS Version 11.7.10 (Build 20G1427)
```
