### ISSUE TITLE
Vertical tab's search button style mismatches

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#32861]
<img width="76" alt="image" src="https://github.com/brave/brave-browser/assets/5474642/cf28bca6-f7ee-49d3-a0a4-34409958c610">

This should have the same style with the toggle button

**Comment by kjozwiak** [comment]
The above requires `1.58.121` or higher for `1.58.x` verification 👍

**Comment by stephendonner** [comment]
## Verification `PASSED` using

```
Brave | 1.59.84 Chromium: 117.0.5938.48 (Official Build) beta (x86_64)
-- | --
Revision | 1dc90873649e32fb7d316ed9b238310d5e99b0f1
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.59.84`
2. launched Brave
3. context-clicked a tab and chose `Use Vertical Tabs`
4. loaded a few sites
5. examined, hovered over, and clicked on/use tab search
6. checked in both `Dark` and `Light` themes

### Confirmed the ` 🔍 ` replaces the `^`, and tab search works

### Full-size screenshot

`Dark` | `Light`
-------|-------
<img width="1397" alt="Screen Shot 2023-09-12 at 1 32 16 PM" src="https://github.com/brave/brave-browser/assets/387249/3063ac57-2cfe-499d-bb22-9a65ee3e2dcb"> | <img width="1261" alt="Screen Shot 2023-09-12 at 1 31 24 PM" src="https://github.com/brave/brave-browser/assets/387249/8deed446-688b-4183-a3c0-6ae9a00abe3a">


### On-hover, up close

`Dark` | `Light`
-------|-------
<img width="466" alt="Screen Shot 2023-09-12 at 1 32 31 PM" src="https://github.com/brave/brave-browser/assets/387249/0f836495-718f-4d4c-b12c-ceb609f9ced9"> | <img width="461" alt="Screen Shot 2023-09-12 at 1 32 56 PM" src="https://github.com/brave/brave-browser/assets/387249/780706b9-e739-4aab-b84b-40736868ab9a">
