### ISSUE TITLE
NFTs are re-enabled when opening Edit visible NFT

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#32864]
## Description 
NFTs are re-enabled when opening Edit visible NFT

## Steps to reproduce 

   1. Restore wallet which has a bunch of NFTs
   2. Go to NFT tab and select Edit visible NFT
   3. Uncheck a bunch of NFTs and save
   4. May hide the NFTs that are unchecked
   5. Click on Edit visible NFT again
   6. All NFTs are checked

## Actual result 

https://github.com/brave/brave-browser/assets/17010094/27e4220a-b47d-438f-9161-01d73fbce5db

## Expected result
Should retain the unchecked NFTs state

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? On RC build
- Can you reproduce this issue with the current Play Store Beta version? Not checked
- Can you reproduce this issue with the current Play Store Nightly version? Not checked

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 13
   
## Brave version
1.58.117

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @Pavneet-Sing @simoarpe

**Comment by Pavneet-Sing** [comment]
It's a known issue https://github.com/brave/brave-browser/issues/31915
