### ISSUE TITLE
AI Chat opt-in message is shown everytime the browser is restarted

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#32862]
## Description 

AI Chat opt-in message is shown everytime the browser is restarted

## Steps to Reproduce

   1. Enable AI Chat flag
   2. Click on the sidebar button
   3. Shows opt-in message
   4. Close browser and relaunch again
   5. Open a new tab and click no the AI chat button, shows the opt in message again

## Actual result:

AI Chat opt-in message is shown everytime the browser is restarted

## Expected result:
Once user accepts opt-in do not show until user clears data 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.59.76 Chromium: 116.0.5845.163 (Official Build) nightly (64-bit)
-- | --
Revision | 882a1d617108cea1c78439e27c5f19c46b276508
OS | Windows 11 Version 22H2 (Build 22621.2215)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @petemill @nullhook

**Comment by nullhook** [comment]
Which opt-in message are you referring to here?

**Comment by nullhook** [comment]
@srirambv I don't happen to see this issue as per your STR. Is this resolved now?

**Comment by bbondy** [comment]
I wonder if you were maybe seeing a browser crash? I'm going to close this given no new confirmation of a problem. Please feel free to re-open if it's a problem @srirambv

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.60.81 Chromium: 118.0.5993.54 (Official Build) beta (x86_64)
-- | --
Revision | 1efb3f333eb41cc34af46ca31fb33c30e0afbfae
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.60.81`
2. launched Brave
3. restarted (to pick up Griffin seed)
4.
