### ISSUE TITLE
Opening external links in the same tab groups stopped working

### ISSUE THREAD

**Issue by samartnik** [brave/brave-browser#32868]
## Description 
Opening external links in the same tab groups stopped working.

## Steps to reproduce 

   1. Make sure `Only open links in current tab group` option is on.
   2. Try to open external link.
   3. It opens in a different tab group (see example https://bravesoftware.slack.com/archives/C0816QH3R/p1694170188294899)

## Actual result 
Link opens in new tab group.

## Expected result
Link opens in the same tab group.

## Issue reproduces how often 
Always for me, but other devs reported it to be working on their devices.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? yes
- Can you reproduce this issue with the current Play Store Beta version? no, it is fixed in cr117
- Can you reproduce this issue with the current Play Store Nightly version? no, it is fixed in cr117

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:
   
## Brave version
1.57.x and 1.58.x

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
Closing as the above has been fixed via https://github.com/brave/brave-core/commit/145681c02a7f5db1eba25cb001423972e7bc65e0 as per https://github.com/brave/brave-core/pull/20069#issue-1887811529 & https://github.com/brave/brave-core/pull/20070#issue-1887828762.

**Comment by kjozwiak** [comment]
As per https://github.com/brave/brave-core/pull/20069#pullrequestreview-1620686582, the above can be verified with `1.58.120` as per the conversation via https://bravesoftware.slack.com/archives/CHGKGMHDJ/p1694459339315069.
