### ISSUE TITLE
Insufficient Funds notification text needs update

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#3286]
## Description 
Found while testing https://github.com/brave/brave-browser/issues/1479

Insufficient Funds notification references Brave Payments, this text should be updated. 

@mandar-brave please provide text for notification.

## Steps to Reproduce

   1. Launched Brave with `- -rewards=reconcile-interval=4340`
   2. Enable Rewards
   3. Visit a site.
   4. Wait 15-20 minutes

## Actual result:
Notification displays with text referencing Brave Payments:
![screen shot 2019-02-08 at 6 04 30 pm](https://user-images.githubusercontent.com/28145373/52511286-54a68500-2bcd-11e9-968f-4b9aac95e511.png)

## Expected result:
Notification should probably reference Brave Rewards, but @mandar-brave should provide text to be used.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.60.23 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by btlechowski** [comment]
Also reproduced on Ubuntu 17.10

Brave | 0.60.28 Chromium: 72.0.3626.96 (Official Build) beta (64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Linux

![image](https://user-images.githubusercontent.com/34715963/52827430-145f6f00-30c5-11e9-90e3-a8ff072154e2.png)

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.62.17 Chromium: 73.0.3683.39 (Official Build) dev (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

Used test plan from https://github.com/brave/brave-core/pull/1723

![image](https://user-images.githubusercontent.com/34715963/53852960-129e1280-3fc4-11e9-97d4-1815cc9b63f7.png)

**Comment by srirambv** [comment]
Seeing Brave Payments on 

Brave | 0.62.32 Chromium: 73.0.3683.75 (Official Build) beta(64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Linux

![image](https://user-images.githubusercontent.com/17010094/54632520-aa840d80-4a54-11e9-8572-9c8e65bcb019.png)


cc: @kjozwiak to try on his Linux machine

**Comment by srirambv** [comment]
Follow up issue logged for linux https://github.com/brave/brave-browser/issues/3786

**Comment by kjozwiak** [comment]
> cc: @kjozwiak to try on his Linux machine

Reproduced and commented results under https://github.com/brave/brave-browser/issues/3786#issuecomment-474547027.

**Comment by srirambv** [comment]
Marking as Windows and macOS as its still failing on Linux and followup issue(#3786 ) for Linux is logged
