### ISSUE TITLE
Incorrect Font displayed for Speedreader articles in Linux

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#32879]
## Description 

Found the issue while verifying https://github.com/brave/brave-browser/issues/29075.  @aguscruiz to confirm the Font display. 

## Steps to Reproduce

1. Install 1.58.101
2. launch Brave
3. navigated to `seattletimes.com` and opened an article (`https://www.seattletimes.com/business/pike-place-market-and-fish-throwing-vendor-battle-over-pike-place-use/`)
4. clicked `Speedreader` button
5. clicked `Appearance` button
6. click on each Font (Sans, Serif, Monospace & Dyslexic)

## Actual result:

Incorrect Font displayed for the article when selected each Font

Sans | Serif | Monospace | Dyslexic
----- | ---- | ------ | -----
![Screenshot from 2023-09-08 12-02-42](https://github.com/brave/brave-browser/assets/98358127/373003be-e7dc-4b94-bf72-469b41d021f9)|![Screenshot from 2023-09-08 12-03-00](https://github.com/brave/brave-browser/assets/98358127/000752ed-56ca-4936-a95e-38394bd6d7b6)|![Screenshot from 2023-09-08 12-03-14](https://github.com/brave/brave-browser/assets/98358127/c33ac80d-be62-42b6-8a8c-83ddb406538a)|![Screenshot from 2023-09-08 12-03-33](https://github.com/brave/brave-browser/assets/98358127/b1948211-79ea-44e6-8eaa-fdf15dcdf8a1)

## Expected result:
Article should display with correct Font

https://github.com/brave/brave-browser/issues/16882#issuecomment-1671305533

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.58.117 Chromium: 116.0.5845.180 (Official Build) (64-bit)
-- | --
Revision | 99255ad6abf2fa399c063683c051f973e1f5c0af
OS | Linux
```
## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@rebron @aguscruiz

**Comment by aguscruiz** [comment]
@rebron seems that Linux is still loading Atkinson Hyperlegible for the standar sans serif foint.

**Comment by rillian** [comment]
I can confirm this on my Linux system. The css style panel in dev-tools confirms it's preferring the Atkinson font over the system sans-serif, and if I change the run the font changes.

It also specifies Georgia over the system serif.

Atkinson Hyperlegible is a much nicer font than the default sans-serif though!

**Comment by fmarier** [comment]
Like @rillian, this is what I see in Beta:
- sans:
```
html[data-font-family='sans'] {
    font-family: 'Atkinson Hyperlegible', sans-serif;
}
```
- serif:
```
html[data-font-family='serif'] {
    font-family: Georgia, serif;
}
```
- monospace:
```
html[data-font-family='mono'] {
    font-family: Courier, monospace;
}
```

**Comment by MadhaviSeelam** [comment]
Closing this as `Atkinson Hyperlegible` font is expected per above  https://github.com/brave/brave-browser/issues/32879#issuecomment-1716400454 & https://github.com/brave/brave-browser/issues/32879#issuecomment-1716619733.

**Comment by boocmp** [comment]
@aguscruiz Could you please confirm we want to change Atkinson, Georgia, Courier font to sans-serif, serif, monospace as you wrote in  https://github.com/brave/brave-browser/issues/16882#issuecomment-1671305533
