### ISSUE TITLE
Contribution date text on Tips panel

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#3287]
## Description 
Per https://github.com/brave/brave-browser/issues/1834#issuecomment-455805100 the text for the 'contribution date' in Tips panel should be

"Monthly tips will next be sent" followed by the next contribution date.

However, the text exactly matches Auto Contribute table. Logging per discussion with @mandar-brave for him and @jenn-rhim to review.

## Steps to Reproduce

   1. Enable Rewards
   2. Navigate to verified site.
   3. Set up a monthly recurring tip.

## Actual result:
Note that contribution text in both Tips and Auto Contribute panels are the same:
![screen shot 2019-02-08 at 5 58 47 pm](https://user-images.githubusercontent.com/28145373/52511494-368d5480-2bce-11e9-8efc-35a3173859f9.png)

## Expected result:
Was expecting different language per the comment referenced above. If that's no longer accurate, please close this issue.

## Reproduces how often: 
easily

## Brave version (brave://version info)
Brave | 0.60.23 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.61.37 Chromium: 73.0.3683.39 (Official Build) beta (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

Used test plan from https://github.com/brave/brave-core/pull/1683

![image](https://user-images.githubusercontent.com/34715963/53378695-dd137c80-3966-11e9-85c4-6c4919111db2.png)
