### ISSUE TITLE
Omnibox rounded corners regressed with 117 update

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#32874]
## Description 

Omnibox corners top of the screen are too aggressively rounded off and shows artifacts.

## Steps to Reproduce

   1. Use 1.59.78 and higher with chromium 117
   2. Set focus to omnibox and enter a character(s) to trigger omnibox suggestions
   3. Notice the rounding of corners at the top see screenshots below.

## Actual result:

<img width="1126" alt="Screenshot 2023-09-08 at 11 04 04 AM" src="https://github.com/brave/brave-browser/assets/5951041/39bd58b1-650f-4943-9a48-13a3f533fa2f">

## Expected result:
Chromium 116 and 1.57.x
<img width="823" alt="Screenshot 2023-09-08 at 11 04 29 AM" src="https://github.com/brave/brave-browser/assets/5951041/a0e15c18-cd8d-4215-8678-33a5279f1b47">

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
cc: @zenparsing @mkarolin

**Comment by stephendonner** [comment]
Just to highlight the hard-to-spot difference, a bit:

`bad` | `good`
---------|---------
<img width="76" alt="Screenshot 2023-09-08 at 1 04 42 PM" src="https://github.com/brave/brave-browser/assets/387249/ad8807f8-ad18-4f2f-9708-967fde6fbcbf"> | <img width="73" alt="Screenshot 2023-09-08 at 1 04 46 PM" src="https://github.com/brave/brave-browser/assets/387249/465935ff-c419-4a01-8994-c8cf56d8de99">

**Comment by zenparsing** [comment]
It looks like there are a couple of features that are currently enabled by default which affect the styling of the omnibox popup. 

* Omnibox Expanded State Height (`omnibox::kExpandedStateHeight`)
* Omnibox Expanded State Shape (`omnibox::kExpandedStateShape`)

It looks like `kExpandedStateShape` is causing the excessive corner rounding. `kExpandedStateHeight` seems to expand the height of the popup 1px at the top and bottom, such that it overlaps the tabstrip by a pixel.

For now, we might be able to just turn these features off.

**Comment by kjozwiak** [comment]
The above requires `1.58.121` or higher for `1.58.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.58.121 Chromium: 117.0.5938.48 (Official Build) (x86_64)
-- | --
Revision | d80a8110b88df6ae5073d8420fada4168542786f
OS | macOS Version 13.5.2 (Build 22G91)
```

**Comment by rebron** [comment]
Verified `Passed` with: 
<html>
<body>


Brave | 1.58.122 Chromium: 117.0.5938.62 (Official Build) (64-bit)
-- | --
Revision | 623437a8c792953b7bc4574f2d9ccdfd59e0ca67
OS | Windows 11 Version 23H2 (Build 25931.1000)
JavaScript | V8 11.7.439.16
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36


</body>
</html>
