### ISSUE TITLE
AI Chat WebUI is scaled out when opening on Android

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#32871]
When opening AI Chat on android, it's showing as zoomed out. 

## Test Plan
Since AI Chat isn't enabled on Android yet, you can test via desktop:
1. Open a Tab and navigate to `chrome-untrusted://chat`
2. Open devtools
3. Click the emulate button
    <img width="134" alt="image" src="https://github.com/brave/brave-browser/assets/741836/eb35ba5c-5fbc-4c62-b121-ae93cc502d46">
5. Select an android device from the list of devices in the top mid
    <img width="282" alt="image" src="https://github.com/brave/brave-browser/assets/741836/f50afe5d-b6a5-4b82-884e-3995d475f6fb">

#### Actual
<img width="593" alt="image" src="https://github.com/brave/brave-browser/assets/741836/fe0f1b4a-15f7-497d-8c1b-6077b6baf85d">

#### Expected
<img width="1312" alt="image" src="https://github.com/brave/brave-browser/assets/741836/00ce3bb1-b341-4d08-9a27-bd5abda85478">

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version:

```
Brave	1.60.96 Chromium: 118.0.5993.88 (Official Build) beta (64-bit) 
Revision	b4c059ad1d32d6e0cd1466123f03ccb97b3cf858
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
_Test Plan_ 
1. Enable `Brave AI Chat` under `brave://flags`
2. Restart browser
3. Menu hamburger menu, select `Brave Leo`
4. Tap on the top of the AI Chat Slider to expand page all the way
5. Confirm UI and menus are scaled correctly.

- Ensured Brave Leo UI is scaled correctly on mobile devices
- Ensured expanded ai UI is scaled correctly.
- Ensured menus are correctly scaled.

Example | Example | Example | Example
-|-|-|-
![Screenshot 2023-10-23 at 3 38 31 PM](https://github.com/brave/brave-browser/assets/17885425/be0b3150-1750-4a9c-ae13-f9fbc5ab3b38) | ![Screenshot 2023-10-23 at 3 53 46 PM](https://github.com/brave/brave-browser/assets/17885425/a5cd3c8b-8aa5-44ad-84ab-6a274c250e69) | ![Screenshot 2023-10-23 at 3 53 53 PM](https://github.com/brave/brave-browser/assets/17885425/b626f0a0-ab78-4e85-8fea-1b994d57c06b) | ![Screenshot 2023-10-23 at 2 52 50 PM](https://github.com/brave/brave-browser/assets/17885425/05a48d20-76c6-41f4-8f33-33df81425663)
