### ISSUE TITLE
remove "New" label for Password manager item in app menu

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#32873]
## Description 

Remove "new" label in the app menu next to Password manager since this is an existing feature.

## Steps to Reproduce

   1. Use 1.59.78 and higher with Chromium 117.
   2. Open app menu and notice Password manager entry.
   3. "New" label is not necessary to be there as this is an existing feature.

## Actual result:

<img width="273" alt="Screenshot 2023-09-08 at 11 14 37 AM" src="https://github.com/brave/brave-browser/assets/5951041/6f59401b-accf-4e20-93cb-ec07db3c2455">

## Expected result:
Screenshot above without the "New" label.

## Reproduces how often: 

easily

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by rebron** [comment]
cc: @fmarier

**Comment by kjozwiak** [comment]
The above requires `1.58.121` or higher for `1.58.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.58.121 Chromium: 117.0.5938.48 (Official Build) (x86_64)
-- | --
Revision | d80a8110b88df6ae5073d8420fada4168542786f
OS | macOS Version 13.5.2 (Build 22G91)
```
