### ISSUE TITLE
[Android 14] Brave crashes on `C117` build when VPN is enabled.

### ISSUE THREAD

**Issue by vlad-hoff** [brave/brave-browser#32878]
## Description 

Brave crashes on `C117` build when VPN is enabled on Pixel 7 with Android 14.

```
2023-09-08 12:08:37.590 13610-13610 chromium                pid-13610                            I  [INFO:policy_logger.cc(142)] :components/enterprise/browser/controller/chrome_browser_cloud_management_controller.cc(273) Deferring CBCM Controller Initialization until it is unblocked.
2023-09-08 12:08:37.846 13610-13689 chromium                pid-13610                            W  [WARNING:ev_root_ca_metadata.cc(118)] Not implemented
2023-09-08 12:08:38.020 13804-13804 chromium                pid-13804                            E  [0908/120838.020539:ERROR:crashpad_info_reader.cc(72)] invalid signature 0x0
2023-09-08 12:08:38.031 13804-13804 chromium                pid-13804                            W  [0908/120838.031446:WARNING:exception_snapshot_linux.cc(263)] fpsimd not found
```

## Steps to reproduce 

   1. Install Brave Nightly `1.60.6` with `C117`
   2. Go to `Settings` > Dev options > Enable `Brave VPN` and relaunch Brave > Observe crash

## Actual result 

Brave crashes on `C117` build when VPN is enabled. The same is happening on Fresh install or Upgrade from lower build with `C116`.

I tried the same with `C114`, `C115` and `C116` builds, and the crash is not happening there. The issue is only reproducible on a device with Androud 14 and not with Android 13.

https://github.com/brave/brave-browser/assets/128532965/e94f4960-1ab1-43a8-a775-1170eab3baaa

## Expected result

Brave must not crash when VPN is enabled.

## Issue reproduces how often 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? No
- Can you reproduce this issue with the current Play Store Nightly version? No

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Pixel 7 (phone)
   - Android version: Android 14 [panther_beta-user 14 UPB5.230623.009 release-keys]
   
## Brave version

Brave build: 1.60.6
Chromium: 117.0.5938.48 (Official Build) canary (64-bit)
Revision: 3729c99b569a7aab570e3f55471c699556e539f9

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by bsclifton** [comment]
Should be fixed with https://github.com/brave/brave-core/pull/19576

Need to retest on 1.60.10 or higher

**Comment by kjozwiak** [comment]
Closing/Moving into `1.58.x` as the above is fixed by https://github.com/brave/brave-core/pull/19576 & https://github.com/brave/brave-core/pull/20099 which was uplifted into `1.58.x` via https://github.com/brave/brave-core/pull/20101. @vlad-hoff assuming the above will be verified by default when running through https://github.com/brave/brave-browser/issues/30673.

**Comment by kjozwiak** [comment]
Removing the `QA/Yes` label as we'll verify the above via https://github.com/brave/brave-browser/issues/33010 & https://github.com/brave/brave-browser/issues/33011.
