### ISSUE TITLE
[Sync] Enable History sync data type

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#32876]
Since CR117 Chromium uses history datatype instead of typed urls.
To fix https://github.com/brave/brave-browser/issues/32857 regression, was done https://github.com/brave/brave-core/pull/20071. But we need a proper PR which in fact uses history datatype.

**Comment by kjozwiak** [comment]
The above requires `1.60.105` or higher for `1.60.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Pixel 2 XL`, `Pixel 6` and `Pixel 7` using version(s):
```
Device/OS:
- Pixel 2 XL [taimen-user  8.1.0 OPM2.171026.006.H1 release-keys]
- Pixel 6 [oriole-user 13 TQ3A.230901.001 release-keys]
- Pixel 7 [panther_beta-user 14 U1B2.230922.010 release-keys]
Brave build: 1.60.108
Chromium: 119.0.6045.59 (Official Build) (64-bit) 
Revision: 3a68c09d9a18cd981fc6bdf3d9e4bda65f57024f
```
---------------------------

**STEPS:**
1. Followed the steps from https://github.com/brave/brave-core/pull/20329#issue-1917760373

**ACTUAL RESULTS:**
- Verified that history is `datatype` synced now.

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/28932cb5-269c-4f79-bae1-3e8795240872) | ![2](https://github.com/brave/brave-browser/assets/128532965/2ecf7270-a290-4881-a529-aa57225ab620) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/39d39658-9b0b-486e-bdee-d1611a9de52d) | ![2](https://github.com/brave/brave-browser/assets/128532965/ed003840-7e56-4a01-bd3c-943ac9b15853) |
|1|2|
| ![1](https://github.com/brave/brave-browser/assets/128532965/1a69749e-d224-42af-901c-70c19b10fb7c) | ![2](https://github.com/brave/brave-browser/assets/128532965/9d1bccf6-7d8f-47fd-9ed2-569293d2c83e) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/9553d392-e21b-4480-be7c-284887f19bfb) |

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.60.108 Chromium: 119.0.6045.59 (Official Build) (64-bit)
-- | --
Revision | 3a68c09d9a18cd981fc6bdf3d9e4bda65f57024f
OS | Windows 10 Version 22H2 (Build 19045.3570)

```
