### ISSUE TITLE
Have a Copy to clipboard and Download button on brave://skus-internals

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#32884]
## Description 
Internal information about the SKU SDK is shown on brave://skus-internals

The data itself is JSON and a viewer is used to explore the JSON. But when sharing this (in support scenarios),  JSON parsers do not like the extra characters and formatting

For the SKU state (not needed for VPN state), we should add a `Copy to clipboard` button (or icon, like the one on brave://version/). We should also have a `Download` button, to save the data to disk

**Comment by simonhong** [comment]
@bsclifton which data from `SKU` state should be copied to clipboard? whole its data or some part?

**Comment by bsclifton** [comment]
@simonhong the copy should copy the entire SKU state. The VPN one is only handy for viewing the date and order ID

**Comment by kjozwiak** [comment]
The above requires `1.59.100` or higher for `1.59.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using 

```
Brave | 1.59.100 Chromium: 117.0.5938.92 (Official Build) beta (x86_64)
-- | --
Revision | 3243fffc43431ab8677e8139859670b4cd2df843
OS | macOS Version 14.0 (Build 23A344)
```

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 [panther_beta-user 14 U1B1.230908.003 release-keys]
Brave build: 1.59.109
Chromium: 118.0.5993.21 (Official Build) beta (64-bit) 
Revision: aacb6a6f8bd916bd49f064b2137b007fa6c47b51
```

Filed follow-up issue #33395
---------------------------

**STEPS:**
1. Launch Brave
2. Go to `brave://skus-internals`
3. Tap `Copy` > Verify
4. Tap `Download` > Verify

**ACTUAL RESULTS:**
- Verified that `Copy` button is working and JASON content copied to the clipboard 
- Observed that `Download` button is not working as expected and a file is not downloaded

---------------------------

|brave://skus-internals|`Copy` button|`Download` button|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/6fdf4163-05ff-46a4-85e1-e61c3e6c24e5) | ![2](https://github.com/brave/brave-browser/assets/128532965/0d282559-b8e1-494e-9166-f7be093b1cee) | ![3](https://github.com/brave/brave-browser/assets/128532965/4c1168ce-4eaa-4220-a239-26a7c23d36af) |

https://github.com/brave/brave-browser/assets/128532965/f25a955c-c4ea-4c5f-ab07-3c46080d83d2
