### ISSUE TITLE
Window close button is not vertically centered in full screen mode

### ISSUE THREAD

**Issue by alperokur** [brave/brave-browser#32885]
![Ekran Görüntüsü - 2023-09-09 15-47-01](https://github.com/brave/brave-browser/assets/36308747/da12354a-4b7e-47e8-85bb-af46025c0e18)

Hello, when I enable the vertical tab menu, the window close button is not vertically centered in full screen mode. Could you please solve this problem?

**Comment by naayeemkhan** [comment]
hey i am new fresher software developer know js react basic nodejs should i try to solve it i could try may be with some guidance

**Comment by keshavjha018** [comment]
@alperokur is this on windows pc? I am unable to reproduce.

please follow the issue template provided by Brave Team.

**Comment by rillian** [comment]
I'm guessing from the :gnome: icon that this is specific to Linux. We believe we've addressed this under https://github.com/brave/brave-browser/issues/33928 which should be part of a new release soon. Feel free to reopen if the problem persists with Brave 1.62 or later.

Thanks for the report!
