### ISSUE TITLE
Claude Instant output in Leo shows only 1 word at a time

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#32882]
Instead of the output building over time, only 1 word is shown at a time:
https://github.com/brave/brave-browser/assets/831718/a6d1af7c-feb3-4566-9e5c-a722b203a094

<img width="319" alt="Screenshot 2023-09-08 at 5 00 38 PM" src="https://github.com/brave/brave-browser/assets/831718/fc288eb7-1369-4817-9409-0b79e5898252">

**Comment by nullhook** [comment]
Looks like this is due to a change in Claude's stream variant of the API. It now sends partial chunks: https://docs.anthropic.com/claude/reference/versioning 

This should be fixed on the proxy side as the client (browser) is treated as untrusted.

**Comment by kim0** [comment]
> This should be fixed on the proxy side

I think there is nothing to fix. The browser/client just needs to understand this new incremental way of sending updates as the LLM generates them and assemble the chunks into the final response. Anthropic mention if we're using their [sdks](https://docs.anthropic.com/claude/reference/client-sdks), this is done for us (no idea if we are)

**Comment by bbondy** [comment]
I believe this is working now. Closing.

**Comment by petemill** [comment]
Reopening as this is not fixed. The same endpoint and API is sometimes giving partial responses (with Claude models) and sometimes giving full responses (with other models). I'd rather it gets done with a simple header change on the proxy or, more preferred, allow the client to set the header so that we can 1) incrementally add support for this and 2) our llama2 server (which uses the same endpoint) can use that API header to gate the new format when it's ready to implement there too.

**Comment by kim0** [comment]
nginx now does not force set that header ([PR](https://github.com/brave/aichat-ops/pull/40)).
I think in the future it would be better security wise to strip all headers from the client and set them from the proxy side. Once that is possible, let me know. Testing now seems to repeat partial answers like below as needed
```
data: {"completion":" London, Berlin,","stop_reason":null,"model":"claude-1.3","truncated":false,"stop":null,"log_id":"ad8540ea0b5d176df3cee10b6684649907c1ff58f6173e3e9905a4f549a4d3cb","exception":null}

data: {"completion":" London, Berlin, Madrid","stop_reason":null,"model":"claude-1.3","truncated":false,"stop":null,"log_id":"ad8540ea0b5d176df3cee10b6684649907c1ff58f6173e3e9905a4f549a4d3cb","exception":null}
```
