### ISSUE TITLE
All of a sudden launching Brave shows Aw, Snap! for everything

### ISSUE THREAD

**Issue by Toninoso** [brave/brave-browser#3288]
This is on Windows 10. Everything worked fine until all of the sudden every new tab started showing Aw,Snap!

Uninstalled, reinstalled Brave using freshly downloaded BraveBrowserSilentSetup-BRT001.exe.

No change.

No site can be accessed, Aw Snap! appears for everything.

Even About menu results in Aw, Snap!

I am behind a proxy which is set up via Microsoft Edge since this is Windows 10.

The proxy has never been a problem before. The only other change that I am aware of that may be significant was that I finally installed Chrome browser since one specific site wouldn't work with Brave so I had to start using Chrome only for that site.

So Edge runs fine, Chrome runs fine but Brave wouldn't, after running fine for more than a year on the same Windows 10 machine in proxy environment.

Nevertheless, the fact remains that at home, where there is no proxy, I have no issues with either Brave or Chrome running together, whenever I want to use one or another.

**Comment by srirambv** [comment]
Can you try clearing browser data and check if it still happens?

**Comment by Toninoso** [comment]
Doing that from Brave menu or pressing Ctrl+Shift+Del didn't help.
I tried manually deleting the folder:
C:\Users\<username>\AppData\Local\BraveSoftware
but that didn't help either. Brave creates a new such folder when started and starts again with Aw,Snap! page.

**Comment by biff3342** [comment]
I have all the same issues as above. I am running Cylance Protect for antivirus. I will try to exclude Brave processes from Cylance and see what happens.

**Comment by biff3342** [comment]
To fix the problem I used Revo Uninstaller to completely uninstall the BRAVE browser. I then rebooted, then reinstalled brave. It's working ok now.

**Comment by jwmcintosh** [comment]
I am trying to use Brave on my corporate device and am getting this issue now. It worked for a short while (less than an hour) then stopped opening any page. Even the start page or Settings results in the aw,snap message screen and plug-ins instantly fail. I get the same System event log generated as above. Re-installations have not been successful and a separate corporate image device gave similar results. All my other stations (including mobile) are great, I really want to like and use this browser!

So on these corp stations we have McAfee which is being phased out by August and Cylance. If @biff3342 was able to remain stable with simply installing I have a hard time blaming Cylance - unless it is just a matter of different security policies being installed... I doubt much of anything can be done about this, just thought I'd comment saying the issue above does still manifest.

**Comment by chitalian** [comment]
I am having the same issue as @jwmcintosh, but I tried uninstalling using Revo as @biff3342 suggested and reinstalling it and no pages are loading, not even the settings page.

**Comment by jwmcintosh** [comment]
I was able to complete the AV cutover early and since removing McAfee my issues are all solved. Brave seems to work as intended.

**Comment by ryfo18** [comment]
I am also running into this issue.  I got a new laptop at work with Windows 10 Pro (coming from Windows 7 where Brave worked fine).  I have McAfee Virus Scan Enterprise on this new laptop.  All the same symptoms as it always says "Aw, Snap!" regardless of whether I'm trying to load a webpage or view the Browser settings.  It's completely unusable.

**Comment by kjozwiak** [comment]
@ryfo18 if you completely disable `McAfee Virus Scan Enterprise`, can you still reproduce the issue or does it go away?

**Comment by ryfo18** [comment]
Hi @kjozwiak - I wish I could do something to help here, but unfortunately I am unable to disable this since it's a corporate laptop.

**Comment by kjozwiak** [comment]
@ryfo18 no worries 👍 Completely understandable!

**Comment by bsclifton** [comment]
We've fixed a lot of crashes recently - let's create a new issue with specific information (the `Report ID` shown in brave://crashes is very helpful - you may need to click `Send now` and relaunch the browser for the report to be sent)

**Comment by AltVader** [comment]
Same issue. I've made no configuration changes on my laptop and have not made changes to antivirus software. One minute it was working and the next it wasn't. Can't get to history, it crashes as well.

**Comment by daniel0x00** [comment]
After updating to the new version today, I have this problem. I cannot open even the brave://help/ page. I've reinstalled it manually from the website, also failed.

**Comment by bsclifton** [comment]
For folks finding this, we're tracking the problem here:
https://github.com/brave/brave-browser/issues/6608

**Comment by ekfletcher** [comment]
I'm having the same issue with both Chrome and Brave.  I wonder if it is a Chromium issue.

**Comment by bsclifton** [comment]
@ekfletcher here's the official support doc from Symantec:
https://support.symantec.com/us/en/article.tech256047.html
