### ISSUE TITLE
ipfs:// and ipns:// are not preserved in address bar when clicking on a relative link 

### ISSUE THREAD

**Issue by lidel** [brave/brave-browser#32883]
## Description 

`ipfs://` and `ipns://` protocol is not preserved in address bar when user clicks on a relative link.

## Steps to Reproduce

(with enabled IPFS support)

1. Open `ipns://en.wikipedia-on-ipfs.org/`
2. Click on any of the relative links of the page: 
   >  ![2023-09-09_01-26](https://github.com/brave/brave-browser/assets/157609/3cc31e24-6b84-44bb-8940-ee222cd81a4e)

## Actual result:

Relative link is loaded from  `http://..localhost:48080`  URL instead of native `ipns://` 

> ![2023-09-09_01-26_1](https://github.com/brave/brave-browser/assets/157609/aa975d47-e11a-47af-9029-f184877a3252)

## Expected result:

Relative links should be resolved with the same protocol sheme as user has in the addressbar:

>  ![2023-09-09_01-35](https://github.com/brave/brave-browser/assets/157609/caf25a75-1d28-410e-a999-8e14aa57c87c)

HTML snippet confirms link was relative:

```html
<a href="../wiki/Architecture" title="Architecture" id="mwEA">Architecture</a>
```

## Reproduces how often: 

Every time.

## Desktop Brave version:

```
Brave	1.58.117 Chromium: 116.0.5845.180 (Official Build) unknown (64-bit) 
Revision	99255ad6abf2fa399c063683c051f973e1f5c0af
OS	Linux
JavaScript	V8 11.6.189.20
User agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Command Line	/opt/brave/brave --user-data-dir=/tmp/brave.21H --disable-domain-reliability --enable-dom-distiller --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --variations-insecure-server-url=https://variations.brave.com/seed --flag-switches-begin --flag-switches-end --component-updater=url-source=https://go-updater.brave.com/extensions --desktop-startup-id=i3/dmenu_run/9753-504-dybuk_TIME2684088558
Executable Path	/opt/brave/brave-browser-1.58.117-linux-amd64/brave
Profile Path	/tmp/brave.21H/Default
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? YES  (1.58.117)
- Can you reproduce this issue with the beta channel? did not check
- Can you reproduce this issue with the nightly channel?  YES (1.60.7)

cc @vadimstruts

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.60.102 Chromium: 118.0.5993.96 (Official Build) beta (64-bit)
-- | --
Revision | 3598a9fc6b7752181feb25caa131bc386d6d054c
OS | Windows 11 Version 22H2 (Build 22621.2428)
```

**`Example`** | **`Example`**
---------------|----------------
![image](https://github.com/brave/brave-browser/assets/2602313/957f45d7-474a-49c4-bb2a-06d1764ec576) | ![image](https://github.com/brave/brave-browser/assets/2602313/70b969ad-26df-4cbf-bc8c-4a1a7abe85bb)
