### ISSUE TITLE
Multiselected tabs are not represented on vertical tab strip

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#32892]
When selecting vertical tabs with Cmd(Ctrl) or Shift key, we should have visual representation about the multi-selected tabs. Currently, we can see only the active tab. Seems to be regression

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.60.88 Chromium: 118.0.5993.70 (Official Build) beta (64-bit)
-- | --
Revision | ff9150ac5dd9934a7f431ddf478ad3e45ae68546
OS | Windows 11 Version 22H2 (Build 22621.2428)
```

Reproduced the issue in `1.59.117 Chromium: 118.0.5993.70` using the STR from the description https://github.com/brave/brave-browser/issues/32892#issue-1889489439

<img width="942" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/9881be57-8e2b-4751-9737-8125c58954ff">


### Confirmed multi tab selection is shown/represented on the vertical tab strip as expected in both Light and Dark themes

Light | Dark
---- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/76eb496a-34d8-43af-94f6-2c4a0aa996de)|![image](https://github.com/brave/brave-browser/assets/98358127/40483c18-cb83-48fd-94e5-0ccc2cae634a)
