### ISSUE TITLE
[Playlist] Brave crashes when `Remove from Playlist` is clicked in the address bar playlist + button dropdown menu.

### ISSUE THREAD

**Issue by Emi-TheDhamphirInLoveUnderTheFrozenStar** [brave/brave-browser#32895]
## Description 

@sangwoo108

Clicking on `Remove from Playlist` is in the address bar is crashing the browser, it works fine when removing from the sidebar Playlist panel.
I also noticed the 'Open in playlist' doesn't work, but doesn't crash the browser. 

1.60.7 Chromium: 117.0.5938.48 (Official Build) nightly (64-bit)  Windows 11 22H2

https://github.com/brave/brave-browser/assets/122518587/20a51737-9390-433b-bc0a-7be85c7979b8

Have a good day!

BTW, something unrelated to this issue but about Playlist.
In the past, you could manually add links to playlist, will that come back at some point?
But more important, will Brave Playlist support grabbing many links/videos at once and using something like Youtube Playlists/Mixes?
There is the `More media on this site` button, for other type of sites, but I thought I would ask, since it would be nice to have like a way to just paste Playlists links or get them from a playlist link, just to get videos added more easily, instead of manually go one by one; also, that would be useful to to avoid going to Youtube to get videos in the playlist, like if someone got the the link from the search engine or something like that.

**Comment by sangwoo108** [comment]
> In the past, you could manually add links to playlist, will that come back at some point?

Yeah, We're looking for more ways to add items to the Playlist. 


> But more important, will Brave Playlist support grabbing many links/videos at once and using something like Youtube Playlists/Mixes?

Sure, we were talking about it. But I guess we need to investigate if we can get data about the Youtube mixes but I have yet to give it a try.

**Comment by sangwoo108** [comment]
Quite similar report with https://github.com/brave/brave-browser/issues/32233 . I'm going to again on Win11.

**Comment by Emi-TheDhamphirInLoveUnderTheFrozenStar** [comment]
@sangwoo108 nice, thanks for the answer, that would be cool!

I always used MPV with yt-dlp, which has support for playlists, so Brave Playlist having that would make things nice, especially on Android version.

And yeah, I get it about the Mixes, for example, yt-dlp can load mixes but they are different from what it loads versus what you see in YT as playlist.
In a quick test I made, it loaded 79 songs, while mixes only have 25, and some songs are missing, but I guess being able to quickly add different videos but still get some variety and not too terrible recommendations from whatever that playlist came from was cool to have in MPV, so hope it can be done in Brave, if not, at least more ways to add media will be  great for sure. 👍

**Comment by sangwoo108** [comment]
Looks like "Open in playlist" has regressed at some point. Split that into another issue https://github.com/brave/brave-browser/issues/32922
