### ISSUE TITLE
[App Menu]: Add missing open in PWA icon

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#32893]
Currently the `Open in <PWA>` app menu entry doesn't have an icon - we should add one.

**Comment by kjozwiak** [comment]
The above requires `1.59.86` or higher for `1.59.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.59.86 Chromium: 117.0.5938.62 (Official Build) beta (x86_64)
-- | --
Revision | 3c4c1c3b2eef0fcbe8485c67e1df504942deadca
OS | macOS Version 14.0 (Build 23A339)
```

### Steps:
1. installed `1.59.86`
2. launched Brave
3. loaded `rt.com`
4. clicked on the top-level app menu ("hamburger")
5. examined and clicked on `Install RT in English...` menu-item entry

### Confirmed the menu-item's icon is there in both `Dark` and `Light` modes, and works

### Full-size screenshot (in-context):


`Dark` mode | `Light` mode
---------|---------
<img width="1639" alt="Screenshot 2023-09-14 at 10 40 07 AM" src="https://github.com/brave/brave-browser/assets/387249/842fd222-ab6d-4941-bc99-843442a1c23e"> | <img width="1639" alt="Screenshot 2023-09-14 at 10 40 22 AM" src="https://github.com/brave/brave-browser/assets/387249/965c77f5-a59d-4aca-9ebf-593617030a47">


### App-menu icon (up close):


`Dark` mode | `Light` mode
---------|---------
<img width="276" alt="Screenshot 2023-09-14 at 10 48 50 AM" src="https://github.com/brave/brave-browser/assets/387249/a7f66aaf-a40d-4dac-b667-53a680042b14"> | <img width="277" alt="Screenshot 2023-09-14 at 10 49 56 AM" src="https://github.com/brave/brave-browser/assets/387249/1697d013-a657-4cef-8cff-8e1f9db9c6b2">
