### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by PsehoPL** [brave/brave-browser#32891]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.57.62 Chromium: 116.0.5845.180
Operating System: Windows NT 10.0.19045

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Playing Roblox downloaded form browser and not microsoft store
2. Watching youtube on the second monitor at 2.5 speed using enchancer for youtube
3. After some time browser stops responding but video still plays until the end of the video
4. Browers refuses to open untill either roblox is turned off or around 10-20min passes

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/421a0200-30cd-ae0a-0000-000000000000

**Comment by rebron** [comment]
Hi @PsehoPL Can you update to the latest 1.58.127 and let us know if you're still seeing this crash.

**Comment by iefremov** [comment]
stale
