### ISSUE TITLE
Copyright needs to be with Brave and not Google

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#3289]
This issue is copied from https://github.com/brave/devops/issues/563 to set milestone.

All Windows installers says `Copyright Google.inc`. This needs to be changed. 

![image](https://user-images.githubusercontent.com/17010094/51016826-bf957980-1597-11e9-9957-586135194dec.png)

**Comment by simonhong** [comment]
Fixed by https://github.com/brave/omaha/pull/23

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.60.28 Chromium: 72.0.3626.96 (Official Build) beta (64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Windows 7

Files checked:
```
BraveBrowserBetaSetup.exe
BraveBrowserBetaSetup32.exe
BraveBrowserSilentBetaSetup.exe
BraveBrowserSilentBetaSetup32.exe
BraveBrowserStandaloneBetaSetup.exe
BraveBrowserStandaloneBetaSetup32.exe
BraveBrowserStandaloneSilentBetaSetup.exe
BraveBrowserStandaloneSilentBetaSetup32.exe


```


![image](https://user-images.githubusercontent.com/34715963/52820058-39df7f00-30ab-11e9-89e0-70e5124b0c2e.png)
