### ISSUE TITLE
3rd party cookie block preventing login session

### ISSUE THREAD

**Issue by gartz** [brave/brave-browser#3291]
## Description 
Please add a whitelist option for non tracker domains so when blocking 3rd party domains, it won't prevent some websites session to work. 

## Steps to Reproduce
With 3rd party cookies blocked:

   1.  Open https://medium.freecodecamp.org/15-useful-javascript-examples-of-map-reduce-and-filter-74cbbb5e0a1f
   2. Login using Facebook
   3. Refresh the page

## Actual result:
You're logged out again

## Expected result:
Should keep the user session logged

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Version 0.59.35 Chromium: 72.0.3626.81 (Official Build) (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
I'm almost sure it will be reproducible in dev/beta builds

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
Yes
- Is the issue reproducible on the latest version of Chrome? 
Yes, if you delete 3rd party domains or block it will work same as Brave

### Additional Information
![image](https://user-images.githubusercontent.com/99608/52517707-13759b80-2bf4-11e9-8a88-c8658b7e22f8.png)
Picture of the cookie used to identify the user session from another domain.

**Comment by ryanbr** [comment]
Hey @gartz  is this still an issue?  Checked both medium and freecodecamp (no signin option, except forums)

**Comment by ryanbr** [comment]
Closing ticket
