### ISSUE TITLE
Crash when adding scriptlet injection filters with too many arguments

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#32916]
See https://github.com/brave/adblock-rust/issues/307 for details. This can be fixed by updating adblock-rust to v0.8.1.

**Comment by antonok-edm** [comment]
we'll want to uplift this one to 1.59.x.

**Comment by kjozwiak** [comment]
The above requires `1.59.87` or higher for `1.59.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.59.86 Chromium: 117.0.5938.62 (Official Build) beta (64-bit)
-- | --
Revision | 3c4c1c3b2eef0fcbe8485c67e1df504942deadca
OS | Windows 11 Version 22H2 (Build 22621.2283)
```

Reproduced the issue in `1.58.124 Chromium: 117.0.5938.62` using STR/Cases from https://github.com/brave/brave-core/pull/20113#issue-1891166019

example | example 
---- | -----
<img width="954" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/74573440-6865-44aa-95db-de6a750002eb">|<img width="953" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/e8a02941-b40e-4e09-91de-7911c3335f01">


1. Installed 1.59.86
2. launched Brave
3. opened `brave://settings/shields/filters` in a new tab page
4. Added `brave.com##+js(acs, this, probably, is, going, to, break, brave, and, crash, it, instead, of, ignoring, it)` to the custom filters  
5. visited https://brave.com/ in a new tab page

#### Confirmed browser not crashed


example | example 
----- | -----
<img width="965" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/c81c8aa6-7a13-449a-81b9-0f469629cf84">|<img width="959" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/756c8348-06af-4e1b-82cb-205b36f5f656">

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 [panther_beta-user 14 U1B1.230908.003 release-keys]
Brave build: 1.59.109
Chromium: 118.0.5993.21 (Official Build) beta (64-bit) 
Revision: aacb6a6f8bd916bd49f064b2137b007fa6c47b51
```
---------------------------

**STEPS:**
1. Launch Brave
2. Go to `brave://adblock` 
3. Add `brave.com##+js(acs, this, probably, is, going, to, break, brave, and, crash, it, instead, of, ignoring, it)` to `Custom Filters`
4. Go to https://brave.com > Verify

**ACTUAL RESULTS:**
- Verified that Brave is not crashing when `brave.com##+js(acs, this, probably, is, going, to, break, brave, and, crash, it, instead, of, ignoring, it)` added to the `Custom Filters`

---------------------------

|Crash on `1.58.135`|No crash on `1.59.109`|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/02a4dfdd-ece5-4924-aacb-5c2ddcf3813b) | ![2](https://github.com/brave/brave-browser/assets/128532965/d19c7378-1c08-4a2c-908f-75a4f8695dc7) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/a274c27f-7abb-486e-9c47-3cc87e38abf4) | ![2](https://github.com/brave/brave-browser/assets/128532965/6e270d92-ba5b-45cb-8aa7-4973a482262b) |

https://github.com/brave/brave-browser/assets/128532965/05acddfe-f555-40ed-a618-38c80ba99a47
