### ISSUE TITLE
Performance issues with buy screen

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#32921]
## Description 

Selecting assets and purchase amount from the buy screen are laggy (especially on android)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.60.81 Chromium: 118.0.5993.54 (Official Build) beta (64-bit)
-- | --
Revision | 1efb3f333eb41cc34af46ca31fb33c30e0afbfae
OS | Windows 11 Version 22H2 (Build 22621.2283)

- Verified steps from [brave/brave-core#20122](https://github.com/brave/brave-core/pull/20122)
- Verified there is no performance degradation on Buy screen
- Verified deposit screen works as expected on both wallet tab and on panel

**Comment by srirambv** [comment]
QA blocked on  #33966

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.60.110 x64 build
- Verified steps from [brave/brave-core#20122](https://github.com/brave/brave-core/pull/20122)
- Verified there is no performance degradation on Buy screen
