### ISSUE TITLE
No credentials are returned if an error happens during `refresh_order_credentials`

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#32924]
## Description 
Folks that purchase VPN or link their iOS/Android purchase can get a time limited v2 credential from account.brave.com

As they approach expiry (within 5 days) - a check is made which calls `refresh_order_credentials`. If this encounters an error, no credentials are returned.

**Comment by kjozwiak** [comment]
The above requires `1.58.129` or higher for `1.58.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave | 1.58.129 Chromium: 117.0.5938.88 (Official Build) (64-bit)
-- | --
Revision | 0ab74dc5473bd9dcd0a85653872988a5655aff6b
OS | Windows 10 Version 22H2 (Build 19045.3448)

```

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.58.129 Chromium: 117.0.5938.88 (Official Build) (x86_64)
-- | --
Revision | 0ab74dc5473bd9dcd0a85653872988a5655aff6b
OS | macOS Version 11.7.10 (Build 20G1427)
```

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.58.129 Chromium: 117.0.5938.88 (Official Build) (64-bit)
-- | --
Revision | 0ab74dc5473bd9dcd0a85653872988a5655aff6b
OS | Windows 11 Version 22H2 (Build 22621.2283)
```

### Ensure new purchases work - PASSED
<Details>
Steps:

1. installed 1.58.129
2. launched Brave
3. loaded account.bravesoftware.com
4. entered basic-auth credentials for staging
5. entered TestVPN_Sep20@mailinator.com into the textfield
6. clicked Get login link
7. clicked Log in to Brave in the resulting email
8. clicked Start free trial beside Brave VPN
9. completed Stripe checkout
10. connect to Brave VPN
11. disconnect from Brave VPN/switch servers
12. Confirmed You have active credentials loaded! banner and working credentials. Also confirmed ability to switch servers, and cleanly disconnect from Brave VPN

connected | disconnected
---- | ----
<img width="947" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/5d1354d4-de26-4ce7-b353-5605c3022aea">|<img width="945" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/4c521478-2ddc-4e01-99d0-a6d547925c40">

</details>

### Existing users (recent purchase) - `PASSED`
<details>

### Steps:
1. installed `1.58.129`
2. launched Brave
3. loaded `account.bravesoftware.com`
4. entered `ep1902@mailinator.com`
5. clicked `Get login link`
6. in the resulting email, clicked `Log in to Brave`
7. clicked on `Refresh Brave VPN` button
8. clicked on the `VPN` button
9. toggled from `Disconnected` to `Connected`
10. switched servers/region
11. disconnected from `Brave VPN`

`Refresh Brave VPN` | `Loading...` | `Connected` | `Switch region` | `Disconnected`
----------------------|-------------|--------------|-----------------|---------------
<img width="950" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/aff6b41a-5552-4825-9772-ef0bb55a1920">|<img width="943" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/2fba58d2-700a-4365-bf20-4ca5258bd9bf">|<img width="946" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/238dbc02-05ec-427a-94fb-6202f6deb74b">|<img width="947" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/b51edca3-7e71-4803-9912-8cfe6da760a8">|<img width="952" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/e6201a22-6a97-43f3-9ec2-a9460dbf523c">

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.58.129 Chromium: 117.0.5938.88 (Official Build) (64-bit)
-- | --
Revision | 0ab74dc5473bd9dcd0a85653872988a5655aff6b
OS | Windows 10 Version 22H2 (Build 19045.3448)
```

### Steps:
1. installed `1.58.129`
2. launched Brave
3. loaded `account.bravesoftware.com`
4. entered `aug1501@mailinator.com`
5. clicked `Get login link`
6. in the resulting email, clicked on `Log in to Brave`
7. confirmed I saw `You have active credentials loaded!` banner
8. connected to `Brave VPN`
9. confirmed I could switch servers/regions
10. disconnected from `Brave VPN`
11. opened `brave://skus-internals`
12. clicked on `Fetch VPN state`
13. clicked on `Fetch SKUs state`
14. collapsed the `creds` section
15. looked for the final day of credentials
16. cross-checked the above with the `expires_at` timestamp value

### Confirmed the final-day credential and the `expires_at` match its expiration/renewal date of `9-22` (`23 in UTC...`)

example | example | example | example | example | example | example
---------|-----------|-----------|----------|------------|----------|-----------
![image (6)](https://github.com/brave/brave-browser/assets/387249/cda33d7d-f21a-426c-b1e6-56a33750758c) | ![image (7)](https://github.com/brave/brave-browser/assets/387249/59322527-c294-49fe-8494-f6cb0a56c690) | ![image (8)](https://github.com/brave/brave-browser/assets/387249/e196b110-1e88-4bcf-95be-5f1c21fa00c7) | ![image (9)](https://github.com/brave/brave-browser/assets/387249/28da68c6-b167-414a-9577-df4e87791a43) | ![image (10)](https://github.com/brave/brave-browser/assets/387249/35b3c39e-6a00-41b7-a2fd-84aaece3c10b) | ![image (11)](https://github.com/brave/brave-browser/assets/387249/ea6c078e-b5f4-4eb5-94d5-ddc857f058ff) | ![image (12)](https://github.com/brave/brave-browser/assets/387249/bec7e179-c364-4cd6-8e34-796f7785fce3)

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave 1.58.129, Chromium 117.0.5938.88
Android 9.0, arm64
Google Pixel XL
```

## New subscription - Google Play Store/IAP card - `PENDING`
<details>

</details>


## New subscription - `account.bravesoftware.com` - `PENDING`
<details>

</details>

## Existing users (recent purchase) - `PENDING`
<details>

</details>
