### ISSUE TITLE
Add Github profile as a publisher channel

### ISSUE THREAD

**Issue by Sh1d0w** [brave/brave-browser#3293]
Currently as a publisher you have 3 different channels to add:

1. Website
2. Youtube channel
3. Twitch channel

It would be more than a great as an open source maintainer to be able to add a Github profile as a channel so you can accept tips.

This is win / win proposal - Brave will gain even more popularity as we will promote them in our repositories, and for us open source maintainers to be able to have additional source for donations.

**Comment by srirambv** [comment]
cc: @davidtemkin @mandar-brave

**Comment by NejcZdovc** [comment]
we have github support now

**Comment by emin-rcrypto** [comment]
@bbondy @NejcZdovc I am not able to see the github as a separate channel currently

How do we enable it?

<img width="1247" alt="image" src="https://user-images.githubusercontent.com/98781957/195487168-53b7414f-3fce-4015-a21b-659bb45e375c.png">
