### ISSUE TITLE
Share code to generate Brave VPN Wireguard keys between Windows and OSX

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#32937]
Placeholder to share code for keys generation

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on

```
Brave | 1.60.86 Chromium: 118.0.5993.54 (Official Build) beta (64-bit)
-- | --
Revision | a174cdee5ce1b329d409f3dd8c450e98b7ff4511
OS | Windows 10 Version 22H2 (Build 19045.3448)

```
- Verified the test plan from https://github.com/brave/brave-core/pull/20140

1. Clean profile 
2. Purchase and connect VPN via account.bravesoftware.com
3. Confirmed Brave VPN Wireguard is connected successfully 

Example | Example | Example
----------|-----------|----------
