### ISSUE TITLE
Shouldn't brave be updating 117 to 117.0.5938.79 

### ISSUE THREAD

**Issue by joejoejo** [brave/brave-browser#32942]
Shouldn't brave be updating to chromium 117.0.5938.79

**Comment by bsclifton** [comment]
Thanks for the query @joejoejo - yes, we have a release of Chromium 117 scheduled for this week (Sep 14th)

Our release schedule is here:
https://github.com/brave/brave-browser/wiki/Brave-Release-Schedule#release-channel-dates

Thanks! 😄
