### ISSUE TITLE
`Block cookie consent` entry being removed from `Settings` after being toggled off/disabled

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#32949]
## Description 

When disabling `Block cookie consent notices` from `Hamburger Menu` -> `Settings` -> `Brave Shields & privacy`, the setting disappears making it impossible to re-enable the feature as the setting isn't visible anymore.

## Steps to reproduce 

   1. download/install `1.60.14 Chromium: 117.0.5938.48`
   2. go into `Hamburger Menu` -> `Settings` -> `Brave Shields & privacy`
   3. disable `Block cookie consent notices`
   4. close `Settings` and go back into `Brave Shields & privacy` once again
   5. notice that `Block cookie consent notices` isn't visible anymore

## Actual result 

https://github.com/brave/brave-browser/assets/2602313/a5d00d89-f3e8-4d64-826d-d08be7835741

## Expected result

The `Block cookie consent notices` setting shouldn't be removed when disabled.

## Issue reproduces how often 

100% reproducible when using the STR/Cases outlined above.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `N/A`
- Can you reproduce this issue with the current Play Store Beta version? `Yes`
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Pixel 6`
   - Android version: `Android 14`
   
## Brave version

```
Brave | 1.60.14 Chromium: 117.0.5938.48 (Official Build) canary (64-bit)
--- | ---
Revision | 988f725c9e62f571c6622c233aa00ae129504fd3
OS | Android 14; Build/UPB5.230623.009; 34; REL
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by kjozwiak** [comment]
Labelling this as `release/blocking` for `1.59.x` so we don't forget the fix the above and also remove the cookie consent modal as per https://github.com/brave/brave-browser/issues/31767#issuecomment-1732073813.

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 [panther_beta-user 14 U1B1.230908.003 release-keys]
Brave build: 1.59.109
Chromium: 118.0.5993.21 (Official Build) beta (64-bit) 
Revision: aacb6a6f8bd916bd49f064b2137b007fa6c47b51
```
---------------------------

**STEPS:**
1. Followed the steps from https://github.com/brave/brave-browser/issues/32949#issue-1893223015

**ACTUAL RESULTS:**
- Verified that `Block cookie consent notices` toggle switch is not removed when closing `Settings`
- Verified that `Block cookie consent notices` toggle switch is not removed when closing and relaunching Brave
- Verified that no regression happened and `Block cookie consent notices` setting is working as expected

---------------------------

*`Block cookie consent notices` toggle switch visibility*

https://github.com/brave/brave-browser/assets/128532965/693ad631-9294-4dfe-8d56-2b0e9e87bf7c

*`Block cookie consent notices` toggle switch functionality*

https://github.com/brave/brave-browser/assets/128532965/6e02279d-7dda-4a6e-96f0-e0e0a3fd32b6
