### ISSUE TITLE
vBAT claim button not disappearing even after claim has expired

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#32941]
## Description

`1.58.x` 

**STR:** 
1. Get a vBAT claim
2. Advance system clock so that it's >90 days from date of vBAT claim. (vBAT claims live for 90 days. After 90 days, they are no longer valid.)

**Desktop:**
* vBAT claim still appears in Rewards panel on brave://rewards

**Android:**
* vBAT claim still appears on brave://rewards page

Note: Strangely, after 150 days or so, it does disappear.

## Expected behavior

1. If a vBAT claim is expired, it should not appear anywhere anymore in the UI. 

## Extra notes

<img src="https://github.com/brave/brave-browser/assets/11497541/e7fc936b-b297-427d-9bfd-7ceb5cd6ac9d" width=200px>
<img src="https://github.com/brave/brave-browser/assets/11497541/500d4bc4-400f-41c6-ad55-53029d041e52" width=200px>

@GeetaSarvadnya can provide more information if needed.

**Comment by GeetaSarvadnya** [comment]
1. claim message doesn't show the correct month on the settings and BR panel in Android, it works fine on Desktop, In settings page it says `Your August ad rewards are here` but in BR panel `Your September ad rewards are here`
2. no of days left is not same in both settings and BR panel on Android, it works fine on Desktop. 

**Android:**

settings page | BR panel
---------------|-----------
![Screenshot_20230912-180347_Brave](https://github.com/brave/brave-browser/assets/38657976/4e1f1598-9cf6-4674-b254-915d9c6d62fa) | ![Screenshot_20230912-180353_Brave](https://github.com/brave/brave-browser/assets/38657976/ebc94569-a0e0-4364-847a-f59ab59decd4)



**Desktop:**

settings page | BR panel
---------------|-----------
![image](https://github.com/brave/brave-browser/assets/38657976/996e35d6-4725-4197-87bb-8c015a4802a4) | ![image](https://github.com/brave/brave-browser/assets/38657976/6bd5dfff-9a89-4e3e-a84e-095612d59855)

**Comment by zenparsing** [comment]
I believe that when we implemented the countdowns in https://github.com/brave/brave-core/pull/11957, we didn't add any logic to auto-expire the grants. Instead, we rely on the grant to disappear from the server. Once it disappears from the server it won't be displayed in the UI.
