### ISSUE TITLE
Speedreader: appearance controls steal focus

### ISSUE THREAD

**Issue by rillian** [brave/brave-browser#32948]
## Description 

After clicking on one of the speedreader appearance controls added in 1.58, keyboard shortcuts stop working.

## Steps to Reproduce

   1. Visit a page where speedreader works, for example https://www.seattletimes.com/business/pike-place-market-and-fish-throwing-vendor-battle-over-pike-place-use/
   2. If necessary, click the 'enabled speedreader' button in the address bar
   3. Click the `Aa` appearance settings button on the speedreader header below the address bar.
   4. Click on one of the font or theme setting buttons
   5. Press `ctrl-t` to open a new tab

## Actual result:

The previously-clicked setting button highlights, as if it has stolen focus, or been activated by an accessibility framework?
![image](https://github.com/brave/brave-browser/assets/225102/2974820c-6c1e-414c-9af9-9ca00264ca82)
Clicking in the content area removes the highlight and shortcuts work again.

## Expected result:
Browser navigation keyboard shortcuts should continue to work.

## Reproduces how often: 

Seems reliable on my Fedora Linux 38 machine.

## Brave version (brave://version info)

1.58.101

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.60.102 Chromium: 118.0.5993.96 (Official Build) beta (64-bit)
-- | --
Revision | 3598a9fc6b7752181feb25caa131bc386d6d054c
OS | Windows 11 Version 22H2 (Build 22621.2428)
```

Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/32948#issue-1893216663, ensured the following:

* selected several `themes` from `Speedreader` bar and ensured that `CTRL + T` opened a new tab without any issues
* selected several `themes` from `Speedreader` bar and ensured that `CTRL + N` opened a new window without any issues
* selected several `fonts` from `Speedreader` bar and ensured that `CTRL + T` opened a new tab without any issues
* selected several `fonts` from `Speedreader` bar and ensured that `CTRL + N` opened a new window without any issues
