### ISSUE TITLE
In Shields, move toggle settings below the Shields settings

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#32957]
## Description 

In Shields settings, brave://settings/shields, the toggles not found in Shields proper should go below Content filtering and the actual Shield settings should be nearer to the top and description.

Show the number of blocked items, Auto-redirect AMP pages, Auto-redirect tracking URLs, and Prevent sites from fingerprinting me based on my language preferences should all be below Content Filtering. See mock-up in Expected result

## Expected result:

<img width="759" alt="267525107-5b50bc6b-2b0d-49a1-bd90-c1760dfbe63f" src="https://github.com/brave/brave-browser/assets/5951041/7ae056b7-70b7-4c40-afac-8317259176cf">

## Currently in release:
In 1.58.x and 1.59.x

<img width="738" alt="Screenshot 2023-09-12 at 8 37 46 PM" src="https://github.com/brave/brave-browser/assets/5951041/4e35a46c-00d2-4b38-b12c-ea215a343580">

## Brave version (brave://version info)

Target 1.60.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.60.81 Chromium: 118.0.5993.54 (Official Build) beta (x86_64)
-- | --
Revision | 1efb3f333eb41cc34af46ca31fb33c30e0afbfae
OS | macOS Version 13.6 (Build 22G120)
```
