### ISSUE TITLE
Override `FormatOriginForSecurityDisplay` to show brave:// instead of chrome://

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#32950]
Follow up to https://github.com/brave/brave-browser/issues/32827 (https://github.com/brave/brave-core/pull/20049).

Instead of overriding `CreateOriginLabel` in `chromium_src/chrome/browser/ui/views/web_apps/web_app_views_utils.cc` consider overriding `FormatOriginForSecurityDisplay` in `components/url_formatter/elide_url.cc`

**Test Plan:**
Same as https://github.com/brave/brave-browser/issues/32827

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.60.102 Chromium: 118.0.5993.96 (Official Build) beta (64-bit)
-- | --
Revision | 3598a9fc6b7752181feb25caa131bc386d6d054c
OS | Windows 11 Version 22H2 (Build 22621.2428)
```

Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/32827, ensured that the PWA confirmation bubble appears as `brave://` and not `chrome://` as per the following:

![image](https://github.com/brave/brave-browser/assets/2602313/6708b953-b2b4-44b9-9d30-81b99b56625a)
