### ISSUE TITLE
Move brave://settings/newTab to brave://settings/getStarted

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#32954]
## Description 

Move New Tab section of settings to brave://settings/getStarted
Remove "New Tab Page" from left column navigation.

Figma link: `https://www.figma.com/file/IXNCYwXmMWaF6u7Pdv1pOW/Desktop-settings---Leo?type=design&node-id=263-7333&mode=design&t=2kjoMpGZZbui6OP7-0`

## Expected result:

<img width="977" alt="Screenshot 2023-09-12 at 8 14 56 PM" src="https://github.com/brave/brave-browser/assets/5951041/4dcad974-05be-447a-9656-27db06953b9d">

## Currently in release:
In 1.58.x and 1.59.x

Get Started
<img width="1031" alt="Screenshot 2023-09-12 at 8 15 31 PM" src="https://github.com/brave/brave-browser/assets/5951041/f4353a09-1def-4e13-b9b5-88fcac40bac6">

New Tab Page
<img width="1026" alt="Screenshot 2023-09-12 at 8 15 25 PM" src="https://github.com/brave/brave-browser/assets/5951041/425d6446-64a9-4200-846b-84101793017f">

## Brave version (brave://version info)

Target 1.60.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.60.81 Chromium: 118.0.5993.54 (Official Build) beta (x86_64)
-- | --
Revision | 1efb3f333eb41cc34af46ca31fb33c30e0afbfae
OS | macOS Version 13.6 (Build 22G120)
```
