### ISSUE TITLE
Move Go Off-The-Record setting to below diagnostic reports

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#32955]
## Description 

In brave://settings/privacy `Go Off-The-Record` setting should go below the `Automatically send diagnostic reports` setting. 

## Expected result:

<img width="724" alt="Screenshot 2023-09-12 at 8 18 59 PM" src="https://github.com/brave/brave-browser/assets/5951041/0d081d9e-cd88-4595-a468-9e4d3c14d04b">

## Current result:
1.58.x and 1.59.x
<img width="713" alt="Screenshot 2023-09-12 at 8 22 18 PM" src="https://github.com/brave/brave-browser/assets/5951041/aaf98a1a-06d3-4a83-a0ab-08006b5dbaa3">

## Brave version (brave://version info)

Target 1.60.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by rebron** [comment]
cc: @ShivanKaul

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.60.81 Chromium: 118.0.5993.54 (Official Build) beta (x86_64)
-- | --
Revision | 1efb3f333eb41cc34af46ca31fb33c30e0afbfae
OS | macOS Version 13.6 (Build 22G120)
```
