### ISSUE TITLE
Add title to Reading list side panel

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#32953]
## Description 

Add icon and title to Reading list side panel

Figma link: `https://www.figma.com/file/HatZxtZooDutHqg5D03CZA/Reading-List?type=design&node-id=1-25&mode=design`

## Expected result:

![screen_shot_2023-09-12_at_19 03 15](https://github.com/brave/brave-browser/assets/5951041/c6665546-5c6e-449c-92ac-cb2dee471a3a)

## Brave version (brave://version info)

Target 1.60.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

cc: @minkyeongshin

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.60.81 Chromium: 118.0.5993.54 (Official Build) beta (x86_64)
-- | --
Revision | 1efb3f333eb41cc34af46ca31fb33c30e0afbfae
OS | macOS Version 13.6 (Build 22G120)
```
