### ISSUE TITLE
Move brave://settings/socialBlocking to brave://settings/shields

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#32956]
## Description 

Move brave://settings/socialBlocking section to brave://settings/shields.
Remove Social media blocking from left navigation.

## Expected result:

<img width="759" alt="Screenshot 2023-09-12 at 8 28 49 PM" src="https://github.com/brave/brave-browser/assets/5951041/5b50bc6b-2b0d-49a1-bd90-c1760dfbe63f">

## Current result:
In 1.58.x and 1.59.x
<img width="1052" alt="Screenshot 2023-09-12 at 8 29 11 PM" src="https://github.com/brave/brave-browser/assets/5951041/c025eaca-fdef-4f5f-bd7c-3ffbf2444ff9">
<img width="1033" alt="Screenshot 2023-09-12 at 8 29 23 PM" src="https://github.com/brave/brave-browser/assets/5951041/165964a8-3ca2-4e22-bb48-06eedc7ff5e7">

## Brave version (brave://version info)

Targeting 1.60.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? n/a

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.60.81 Chromium: 118.0.5993.54 (Official Build) beta (x86_64)
-- | --
Revision | 1efb3f333eb41cc34af46ca31fb33c30e0afbfae
OS | macOS Version 13.6 (Build 22G120)
```
