### ISSUE TITLE
AI Chat feedback UI and client

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#32951]
AI Chat messages will have an option for the user to provide feedback about a message:

- Context menu for each message
- Thumbs up button (sends the feedback immediately and shows a "success" notification
- Thumbs down button (sends the feedback immediately, shows a "success" notification and offers a form for the user to submit more information).

https://www.figma.com/file/h7fKSJF2P556bZWfyLTfwD/Brave-AI?type=design&node-id=539%3A19624&mode=design&t=nXguS70mTLVV2pH5-1

**Comment by kjozwiak** [comment]
The above requires `1.60.90` or higher for `1.60.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.60.96 Chromium: 118.0.5993.88 (Official Build) beta (64-bit)
-- | --
Revision | b4c059ad1d32d6e0cd1466123f03ccb97b3cf858
OS | Windows 10 Version 22H2 (Build 19045.3570)

```

**Comment by Uni-verse** [comment]
In Progress on `Samsung Galaxy S21` using version:

```
Brave	1.60.96 Chromium: 118.0.5993.88 (Official Build) beta (64-bit) 
Revision	b4c059ad1d32d6e0cd1466123f03ccb97b3cf858
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
