### ISSUE TITLE
[Cr117 follow up] Settings -> Sync -> Payment methods toggle is not hidden

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#32968]
In brave://settings/braveSync/setup the `Payment methods, offers, and addresses using Google Pay` toggle is no longer hidden in cr117 based builds.

The console shows the following error:

`settings.js:3381 [Brave Settings Overrides] Could not find sync control payment toggle`

Thanks @emerick for discovering this.

**Comment by kjozwiak** [comment]
The above requires `1.58.124` or higher for `1.58.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.58.124 Chromium: 117.0.5938.62 (Official Build) (x86_64)
-- | --
Revision | 5c0e98018fb16948401122cb9af1a5a0a6b40865
OS | macOS Version 13.5.2 (Build 22G91)
```
