### ISSUE TITLE
[Android] Adjust margin for Earnings so far in Rewards Panel

### ISSUE THREAD

**Issue by sujitacharya2005** [brave/brave-browser#32964]
## Description 
Note that the estimated earnings so far are too close to the right edge of the Rewards panel:
https://github.com/brave/brave-browser/issues/32736
Last PR got overwritten by other PR.

![image](https://github.com/brave/brave-browser/assets/32419898/8ce7e6bf-e126-4761-b221-a27e7f61383c)

**Comment by kjozwiak** [comment]
The above requires `1.59.100` for higher for `1.59.x` verification 👍 Adding `QA/Test-All-Platforms` as we should double check and ensure that the alignment on `Tablet` looks correct as well.
