### ISSUE TITLE
Register ai-chat side panel to contextual registry instead of global registry

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#32963]
It doesn't change current behavior. but code will be change a lot.
So need to check this refactoring causes regressions

STR
1. Enable ai-chat and restart
2. Open three tabs
3. Open bookmark panel at tab 1
4. Activate tab 2 and open ai-chat panel
5. Detach tab 1 and check ai-chat panel is still opened in new window 2
6. Toggle ai-chat in window 2 and side panel is toggled with animation
7. Open another NTP in window 2 and activate tab 1 and check ai-chat panel is opened w/o animation

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.60.79 Chromium: 118.0.5993.32 (Official Build) nightly (x86_64)
-- | --
Revision | 95cf2d4e2e2855bd58fe8002ccd32e3d673abafd
OS | macOS Version 11.7.10 (Build 20G1427)
```


Enable ai-chat and restart
Open three tabs
Open bookmark panel at tab 1
Activate tab 2 and open ai-chat panel
Detach tab 1 and check ai-chat panel is still opened in new window 2
Toggle ai-chat in window 2 and side panel is toggled with animation
Open another NTP in window 2 and activate tab 1 and check ai-chat panel is opened w/o animation
