### ISSUE TITLE
Improve Deposit Screen performance

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#32971]
## Description 

Refactor the deposit screen to improve performance on slow devices. Selecting assets should not take 10+ seconds on Android

## Steps to Reproduce

   1.  Open the deposit screen on android
   2. select an asset

## Actual result:

UI takes multiple seconds to update

## Expected result:
UI updates quickly to show updated selection

## Reproduces how often: 

Easy

## Desktop Brave version:

Nightly

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.60.102 Chromium: 118.0.5993.96 (Official Build) beta (64-bit)
-- | --
Revision | 3598a9fc6b7752181feb25caa131bc386d6d054c
OS | Windows 11 Version 22H2 (Build 22621.2428)

- Verified steps from issue description
- Verified Deposit screen doesn't slow down when selecting tokens
- Verified Buy screen works without any issues

**Comment by srirambv** [comment]
Android QA blocked on  #33966

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.60.110 x64 build
- Verified steps from issue description
- Verified Deposit screen doesn't slow down when selecting tokens
- Verified Buy screen works without any issues
