### ISSUE TITLE
Sync Bookmark - Sort by name by default

### ISSUE THREAD

**Issue by Firemad03** [brave/brave-browser#3297]
## Description 
When the bookmark are synced between brave they are not sorted by name.

## Steps to Reproduce
   1. Install Brave
   2. Add bookmarks
   3. Install another version of brave or on another computer and start the sync. This brave won't be sorted by name for the bookmark.

## Expected result:

I expected the bookmark be the same on both browser.

I can sort it manually but I expected it to be by default.

## Reproduces how often: 
Easily

## Brave version (brave://version info)
I tried: Version 0.59.35 Chromium: 72.0.3626.81 (Official Build) (64-bit) and Version 0.61.17 Chromium: 72.0.3626.81 (Official Build) dev (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Yes

### Additional Information
I don't know maybe add an option in the sync if people don't want it by default or add it by default and add an option to disable it.

**Comment by srirambv** [comment]
> 3. Install another version of brave or on another computer and start the sync. This brave won't be sorted by name for the bookmark. 

Dev version would be ahead of release so there might be a few fixes which are not part of release. This could be the reason for incorrect folder structure. Could you try with same release version on both system and check if the folder structure is maintained? This should have been fixed as part of https://github.com/brave/brave-browser/issues/2133

**Comment by AlexeyBarabash** [comment]
@Firemad03 bookmarks should be in the same order between different devices.

**Comment by mpaluta** [comment]
I don't believe the average user necessarily wants bookmarks sorted alphabetically whenever they sync (I for one don't - I sort portions of mine by time or by usage). However, I have some more information to add, which might make the issue more clear. I recently synced a new device and it scrambled up the previously established order of my Bookmarks bar quite a bit. I have about 50 items on the bookmarks bar, so it was very apparent. I believe the order did get scrambled in the same fashion across all devices in the chain. I do sometimes see bookmarks in slightly different orders across devices (for example right now, iOS has a couple bookmarks moved a few positions compared to Linux beta).

My sync chain is one Linux beta, one Windows beta, and one iOS.

Linux version:
Version 0.66.92 Chromium: 75.0.3770.90 (Official Build) beta (64-bit)
