### ISSUE TITLE
Leo eraser button should only show up when it can perform an action

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#32978]
The eraser button should only show up when there is text in the chat:

<img width="545" alt="Screenshot 2023-09-13 at 1 34 01 PM" src="https://github.com/brave/brave-browser/assets/831718/3ac2ad27-1848-4400-b550-b925e27298f3">

**Comment by stephendonner** [comment]
Cross-reference (slightly different): https://github.com/brave/brave-browser/issues/32959

**Comment by kjozwiak** [comment]
The above requires `1.60.94` or higher for `1.60.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.60.94 Chromium: 118.0.5993.70 (Official Build) beta (x86_64)
-- | --
Revision | 6a9dda6d700daa1da53ec97072458dd271ba5c01
OS | macOS Version 11.7.10 (Build 20G1427)
```
### First, reproduced using `1.61.60`

## Steps:
1. installed `1.60.94`
2. launched Brave
3. restarted Brave (to pick up Griffin seed)
4. clicked on `Brave Leo` on the sidebar
5. clicked on `Accept and begin` to opt-in
6. loaded `sunset.com`
7. examined the top controls


### Confirmed no `Erase conversation history` button until the user has interacted with `Leo`

`1.61.60` | `1.60.94` | `After interaction`
----------|-----------|------------------
<img width="496" alt="Screen Shot 2023-10-17 at 2 53 57 PM" src="https://github.com/brave/brave-browser/assets/387249/93ee815c-0f86-48f1-99d3-7e640bc64581"> | <img width="553" alt="Screen Shot 2023-10-17 at 2 54 25 PM" src="https://github.com/brave/brave-browser/assets/387249/6c6b861d-6f1e-497b-92a4-05b7f694a8b6"> | <img width="507" alt="Screen Shot 2023-10-17 at 3 06 06 PM" src="https://github.com/brave/brave-browser/assets/387249/1a2e7f62-a32f-4a49-be67-2b30202089cb">
