### ISSUE TITLE
Add Android tab usage metrics

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#32989]
Add weekly tab usage metrics for Android.

In the past week, how often are address bar entries/queries performed in new tabs compared to existing tabs?
`Brave.Core.LocationNewEntries`

0. Less than 25% of total address bar entries performed in new tabs
1. 25% -50% of total address bar entries performed in new tabs
2. 50% -75% of total address bar entries performed in new tabs
3. More than 75% of total address bar entries performed in new tabs

In the past week, when creating new tabs, how often do you use the [+] button compared to the tab switcher button?
`Brave.Core.NewTabMethods`

0. Less than 25% of total new tabs created using [+] button
1. 25% -50% of total new tabs created using [+] button
2. 50% -75% of total new tabs created using [+] button
3. More than 75% of total new tabs created using [+] button

**Comment by GeetaSarvadnya** [comment]
@DJAndries I need a clearification one of the scenario, In what condition we will get the `0` response value for the metrics `Brave.Core.LocationNewEntries`? I tried couple of cases but I am not getting `0` in any of the cases

**Comment by DJAndries** [comment]
> @DJAndries I need a clarification one of the scenario, In what condition we will get the `0` response value for the metrics `Brave.Core.LocationNewEntries`? I tried couple of cases but I am not getting `0` in any of the cases

If you're using a fresh profile, try performing 10-15 search queries. You should get a `0` value.

**Comment by GeetaSarvadnya** [comment]
@DJAndries I have opened 15 tabs still I am not seeing the response value `0` also I have opened the new sites in the existing tabs  in all the tabs still I am not getting the response value `0`

**Comment by DJAndries** [comment]
@GeetaSarvadnya 

Please try:

0. Clean profile
1. Open one site in one new tab
2. Open several more sites in the same tab
3. Check response value
