### ISSUE TITLE
Update left navigation order in brave://settings

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#32990]
## Description 

Update left navigation order in brave://settings.
Move `Privacy and security` immediately below `Shields`
Move `Web3` below Brave Rewards.

## Expected result:

<img width="292" alt="Screenshot 2023-09-12 at 8 52 54 PM" src="https://github.com/brave/brave-browser/assets/5951041/9a5247e2-6075-4585-8d43-9a8d8f4409b1">

## Current result:
In 1.58.x/1.59.x
<img width="288" alt="Screenshot 2023-09-13 at 5 14 37 PM" src="https://github.com/brave/brave-browser/assets/5951041/6c951daf-72fa-4018-94d0-3315108f6938">

## Brave version (brave://version info)

Target 1.60.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

Brave | 1.60.81 Chromium: 118.0.5993.54 (Official Build) beta (x86_64)
-- | --
Revision | 1efb3f333eb41cc34af46ca31fb33c30e0afbfae
OS | macOS Version 11.7.10 (Build 20G1427)

## `Dark` mode

## `Light` mode

## Migration/upgrade
