### ISSUE TITLE
Add native media keys support

### ISSUE THREAD

**Issue by leobel96** [brave/brave-browser#3299]
Google chrome [has recently announced](https://www.zdnet.com/article/chrome-73-to-officially-support-the-multimedia-keys-on-your-keyboard/) support to media keys without the necessity of extensions. Users will be able to control youtube, spotify, vimeo,... using the media keys of their keyboard also when the browser is on background. What about adding it also in Brave?

**Comment by srirambv** [comment]
This should be available as part of [Chromium 73](https://bugs.chromium.org/p/chromium/issues/detail?id=921281) upgrade to Brave as well. Nothing specific to be done on Brave. cc: @bbondy to confirm or reopen the issue if otherwise

**Comment by leobel96** [comment]
Fantastic
