### ISSUE TITLE
Cursor focus is not retained in the chat box when a response is being typed in

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#32998]
## Description 

Cursor focus is not retained in the chat box when a response is being typed in

## Steps to Reproduce

   1. Open Brave AI Chat from side bar
   2. Ask a question 
   3. Once the chat bot starts responding the cursor focus is removed from the input. Need to click every time you want to ask a question

## Actual result:

Cursor focus is not retained in the chat box when a response is being typed in

## Expected result:
Cursor focus should remain in the input box until user clicks away

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.60.14 Chromium: 117.0.5938.48 (Official Build) nightly (64-bit)
-- | --
Revision | 988f725c9e62f571c6622c233aa00ae129504fd3
OS | Windows 11 Version 22H2 (Build 22621.2283)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @nullhook @petemill @rebron

**Comment by bbondy** [comment]
Can you still reproduce this @srirambv ?

**Comment by srirambv** [comment]
This seems fixed on current Nightly `1.62.52`. Not sure which PR fixed it but closing as stale
