### ISSUE TITLE
The latest Release Build v1.57.64 is missing the Arm APKs

### ISSUE THREAD

**Issue by Mobe1969** [brave/brave-browser#32999]
The latest Release Build is missing the Arm APKs

https://github.com/brave/brave-browser/releases/tag/v1.57.64

**Comment by djmaze** [comment]
It seems APKs are completely gone from Github releases. (IOS builds missing as well.)

**Comment by bsclifton** [comment]
@Mobe1969 some releases only run for a particular OS. For example, if we have a Desktop only release.

Please do let us know if a release is missing the assets. Here are some quick links:
- [Desktop](https://github.com/brave/brave-browser/blob/master/CHANGELOG_DESKTOP.md)
- [Android](https://github.com/brave/brave-browser/blob/master/CHANGELOG_ANDROID.md)

The last 1.57 release on Android for example was [1.57.62](https://github.com/brave/brave-browser/releases/tag/v1.57.62) and the APKs are there

The iOS one is a bit tricky as older builds will use the iOS binary along with the code in https://github.com/brave/brave-ios ([see here for the CHANGELOG](https://github.com/brave/brave-ios/blob/development/CHANGELOG.md)). We're currently moving that code into the code-base here too and we may have a release notes file in this repo eventually.
cc: @kjozwiak 

@djmaze I'll check with devops team about why there aren't the files matching `brave-core-ios.*`

**Comment by djmaze** [comment]
Okay, thanks. There is another problem. It seems not all nightlies are marked as _Pre-release_ on the releases page. That's why Obtainium on Android finds [1.65.30](https://github.com/brave/brave-browser/releases/tag/v1.65.30) as the latest stable release. Would be cool if that could be fixed (at least for future releases).

**Comment by mihaiplesa** [comment]
@djmaze some nightly channel builds are internal and some are public, hence the distinction.

We recommend using https://versions.brave.com/ and the direct links to version files you see referenced there.
