### ISSUE TITLE
Wallet Confirm Spend Approval Panel UI Issues

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#32996]
## Description 

The Wallet `Confirm Spend Approval` Panel UI has some styling issues
## Steps to Reproduce

1. Go to the `Swap` page and create a `Swap` transaction with a token that doesn't have an `Approve Spend` yet.
2. Take a look at the `Confirm Spend Approval` Panel UI
3. The `Header` is bunched together
4. The `Transaction Info` box is barely visible

## Actual result:

https://github.com/brave/brave-browser/assets/40611140/fc6a9928-137c-405e-96bf-12b0aba58265

![Screenshot 9](https://github.com/brave/brave-browser/assets/40611140/55837611-5f75-4111-8f73-fb6d21c83884)

## Expected result:

Needs polishing

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by 19PA1A0535** [comment]
I can take this

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.60.109 Chromium: 119.0.6045.59 (Official Build) (64-bit)
-- | --
Revision | fc399c7c433510eb03c2b35281bf8935804b99de
OS | Windows 11 Version 22H2 (Build 22621.2506)

- Verified steps from [brave/brave-core#20697](https://github.com/brave/brave-core/pull/20697)
- Verified Swap approval screen is shown as per new design

https://github.com/brave/brave-browser/assets/17010094/d56a305d-89a9-4e3a-b641-d927e66d54b2
