### ISSUE TITLE
Give Leo information about when text is being truncated so it can better formulate an answer. 

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#33006]
> Could we do better at making the model aware that it didn’t consume the full content? I didn’t verify but I’m assuming it stopped at 13 because the text got truncated?
https://music.youtube.com/playlist?list=OLAK5uy_lm33KX5L-19O27gjy9IrZCQJEFxx00WMQ

![Screenshot 2023-09-13 at 4 05 41 PM](https://github.com/brave/brave-browser/assets/831718/0270f760-654f-4342-a6ec-8c853b18b242)

**Comment by petemill** [comment]
Is it enough to make the _user_ aware it's cut off? https://github.com/brave/brave-browser/issues/31405

**Comment by bbondy** [comment]
For MVP? I think so

**Comment by stevelaskaridis** [comment]
Given that Llama-13B does not particularly "care" about this prompt change anyways (which is our public offering), I propose that we close this for now.

**Comment by bbondy** [comment]
thanks for checking 👍
