### ISSUE TITLE
Wallet response is quite slow when rendering the networks filter dropdown

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#33004]
## Description 

Wallet response is quite slow when rendering the networks filter dropdown

## Steps to Reproduce

   1. Create a wallet
   2. Open fund wallet screen
   3. Select Network dropdown

## Actual result:

Response is quite slow

## Expected result:
Response not be slow

## Reproduces how often: 

Easy

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.60.102 Chromium: 118.0.5993.96 (Official Build) beta (64-bit)
-- | --
Revision | 3598a9fc6b7752181feb25caa131bc386d6d054c
OS | Windows 11 Version 22H2 (Build 22621.2428)

- Verified steps from issue description
- Verified wallet response is not slow when rendering network filter dropdown on Buy/Deposit screens

**Comment by srirambv** [comment]
Verification passed on Lenovo Tab with Android 13 running 1.60.106 x64 build
- Verified steps from issue description
- Verified wallet response is not slow when rendering network filter dropdown on Buy/Deposit screens
- Encountered [#34011](https://github.com/brave/brave-browser/issues/34011)
----------------
Verification passed on Oppo Reno 5 with Android 13 running 1.60.106 x64 build
- Verified steps from issue description
- Verified wallet response is not slow when rendering network filter dropdown on Buy/Deposit screens
