### ISSUE TITLE
Wallet Swap Panel Showing Unnecessary Scroll Bar

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#33013]
## Description 

The Wallet `Swap Panel` is showing an unnecessary `Scroll Bar`

## Steps to Reproduce

   1. Open the Wallet `Panel` and navigate to the `Swap` tab
   2. There is an unnecessary `Scroll Bar

## Actual result:

![Screenshot 12](https://github.com/brave/brave-browser/assets/40611140/0eb92195-4148-4e5c-ab56-ed7291054550)

## Expected result:
Should not show a `Scroll Bar` unless necessary.

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.59.94` or higher for `1.59.x` verification 👍

**Comment by srirambv** [comment]
This issue is irrelevant now as Swap opens in full view as per https://github.com/brave/brave-browser/issues/33353 and verified here https://github.com/brave/brave-browser/issues/33353#issuecomment-1748187713
