### ISSUE TITLE
Restrict custom-headers for partners

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#3301]
## Background
When creating the referral program, we designed it so that partners can send custom headers. The intention is so that partners can detect a user is using Brave and customize the experience for them (ex: allow them to read articles or use the service for free, etc)

An example of the headers (which are all `X-Brave-Partner`) can be seen here:
https://laptop-updates.brave.com/promo/custom-headers

This design and implementation was originally security reviewed (and approved) by @tomlowenthal here (private repo link):
https://github.com/brave/internal/issues/250#issuecomment-379076770

## Description
We should restrict this list so that it can ONLY use this list for sending the `X-Brave-Partner` header. No custom header *names* should be allowed

## Related
- For Android, see: https://github.com/brave/browser-android-tabs/issues/1104
- For iOS, see https://github.com/brave/brave-ios/issues/887

**Comment by kjozwiak** [comment]
@bsclifton is there anything QA can do here? Can we get some test cases added into the issue or the PR? Assuming we need to check and make sure that only `X-Brave-Partner` is being accepted and anything else throws an error.

**Comment by diracdeltas** [comment]
@kjozwiak at the very least QA can test that referral promo sites like dow jones still work (same as original test plan for DJ promo)

if @aekeus adds an entry like `[{"domains":["brave.com"],"headers":{"foo":"bar"},"cookieNames":[],"expiration":31536000000}]` to the promo headers endpoint, then we can also test that going to brave.com does not add any extra headers.

**Comment by kjozwiak** [comment]
Thanks @diracdeltas 👍 @aekeus would it be possible to add the above? Maybe we can use the staging server for that portion of the test so we don't need to add the above entry into production?

**Comment by aekeus** [comment]
Yes, we can add `brave.com` to the custom-headers to help in testing.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 10.14.2 x64` using the following build:

Brave | 0.60.44 Chromium: 72.0.3626.109 (Official Build) (64-bit)
-- | --
Revision | fae8db7ab9280fa6704a59980263c804f809ebd5-refs/branch-heads/3626@{#857}
OS | Mac OS X

* Went through the test plan outlined under https://github.com/brave/brave-browser/issues/3301#issue-408638670
