### ISSUE TITLE
Vertical tabs disapear in full screen macOS

### ISSUE THREAD

**Issue by VIXI0** [brave/brave-browser#33020]
**Description of the issue:**
Vertical tabs disapear in full screen macOS

<strong>Steps to Reproduce:
1.</strong> Launch Brave
<strong>2.</strong> Activate Vertical tabs
<strong>3.</strong> Open multilpe web pages Vertical tabs 
<strong>3.</strong> Click full screen in the window (Green button)

<strong>Actual Result:</strong>
tabs disapperar, cant navigate between tabs, I have to exit full screen.

IM SURE THIS HAS ITS ORIGIN TRYING TO FIX THE VERTICAL BAR IN FULLSCREEN VIDEOS, BUT ENDED UP DISAPEARING THE TAB ALSO WHEN THE WINDOW IS IN FULLSCREEN.

ALSO A GOOD FEATURE (OR FIX) IS TO SHOW THE TABS BAR WHEN THE MOUSE PASS BY LIKE LATERAL BAR.

![bug](https://github.com/brave/brave-browser/assets/43118641/d906f67f-b7b4-46b1-b367-ab61d68450f8)

**Expected** <strong> Result:</strong>
To see ther vertical tabs.

<strong>Reproduces how often:</strong>
Always

<strong>Brave Version(See the About Brave page in the main menu):</strong>
Brave release - Versión 1.58.124

<strong>Reproducible on current live release (yes/no):</strong>
Yes

**Additional information:**
I'm using macOS Ventura v 13.5.2 (22G91)

PD: This is extremely stressing

**Comment by rebron** [comment]
@VIXI0 We're taking another look to see if on hover, we can show you the vertical tabs bar. You can access your tabs by going to the top of the screen. 

If you can understand, we have gotten feedback where users who go into full screen mode want true full screen mode which means no UI.

**Comment by VIXI0** [comment]
@rebron I completed understand your approach, but it really doesn't make sense that **I can navigate** in full screen when vertical tabs are **disabled** but **unable to navigate** when they're enabled, please pay attention to the next Screenshots.

in short if I want to change tabs (to do research, play/pause music, see above student navigation) i have so exit/enter fullscreen, on a daily basis i'll have to exit/enter fullscreen like 100 times per hour.

If you are a developer you will understand how important is to be able to navigate in a efficient way, vertical tabs help me a lot managing multiple sources of information but now im unable to do so.
**FULL SCREN VERTICAL TABS DISABLED**
<img width="960" alt="image" src="https://github.com/brave/brave-browser/assets/43118641/35df7974-878f-4243-98eb-a2e02d896709">
**FULL SCREN VERTICAL TABS ENABLED**
<img width="960" alt="image" src="https://github.com/brave/brave-browser/assets/43118641/6fffd3d1-5806-479d-9151-fa319a0f77f8">

**student navigation with vertical tabs enabled using full screen**

1. exit fullscreen (FS)
2. open new tab
3. enter FS
4. got to the academic platform and search homework
5. exit FS
6. open new tab
7. enter FS
8. search homework ( but i need to keep this tab open in order to keep the information)
5. exit FS
6. open new tab
7. enter FS
8. do research
9. **I NEED TO GO TO THE ACADEMIC PLATFORM** 
10. exit FS
11. GO TO THE ACADEMIC PLATFORM
12. enter FS

**Comment by rebron** [comment]
@VIXI0 Yes you're correct. We'll be working on making the vertical tabs available via hover on the left side.

**Comment by VIXI0** [comment]
@rebron @jbleahy thank you guys I appreciate your hard work!!

**Comment by raduc** [comment]
Can vertical tabs follow the behavior of horizontal tabs? Those are visible in full screen mode but disappear when a full screen video is playing. Or at least can there be an option to keep them visible in full screen mode? E.g. always shown vs on hover only. That would allow everyone to use them as they feel like.

**Comment by Sohampatra1** [comment]
I completely agree with you and also desire this feature. It would be great if vertical tabs could behave like horizontal tabs, remaining visible in full-screen mode instead of disappearing when a full-screen video is playing. Having the option to keep vertical tabs always visible or only when hovering over them would give users the flexibility to customize their browsing experience according to their preferences.

**Comment by raduc** [comment]
Also, MacOS Chrome treats full screen mode differently wrt tabs:
On MacOS there is a difference between full-screen mode (tabs available) and presentation mode (tabs hidden):
https://apple.stackexchange.com/a/113736

**Comment by sangwoo108** [comment]
Hello, everyone. W'll be reverting the previous change and start working on hover mode and etc asap.

**Comment by jbleahy** [comment]
@sangwoo108 , what release will have the reverted changes?

**Comment by samoritano** [comment]
Same here, vertical tabs went away.

MacOS: Ventura 13.5.2 (22G91).

I tried with the latest beta version and it works, maybe you guys already have fixed it...

**Comment by thenabeel** [comment]
Same happened with me. Vertical tabs disappeared after the latest update.

**Comment by sangwoo108** [comment]
I think it's going to be September 27, which is a maintenance release for 1.58

**Comment by rebron** [comment]
Actually the revert/fix maybe coming later this week, likely this Thursday with https://github.com/brave/brave-browser/issues/33106

**Comment by sangwoo108** [comment]
Let me close this issue as the revert was merged. I made another issue for hiding + mousehover to showing up. https://github.com/brave/brave-browser/issues/33136

**Comment by thenabeel** [comment]
The issue has been resolved after updating to latest. Now navigation does not disappear in full screen mode.

**Comment by rebron** [comment]
@thenabeel You're quick. brave://settings/help for 1.58.129 to get it now.

**Comment by raduc** [comment]
This has regressed and it's happening again in 1.63.174.

**Comment by sangwoo108** [comment]
@raduc Could you check if that vertical tab shows up when you move mouse to the edge of screen?

**Comment by raduc** [comment]
I can see the tabs now, but I needed to enable "Always show toolbar in full screen". For some reason they got reset after latest update.
