### ISSUE TITLE
Missing icon for `Show VPN tray icon` vpn app menu

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#33025]
![Screenshot 2023-09-15 113529](https://github.com/brave/brave-browser/assets/6786187/51d0642a-77d5-4a12-93cb-fd70bbcb2f8f)

cc @rebron @fallaciousreasoning

**Comment by simonhong** [comment]
`Hide VPN button in toolbar` and `Hide VPN try icon` will be removed by https://github.com/brave/brave-browser/issues/33027

**Comment by bsclifton** [comment]
Menu is removed now- closing
