### ISSUE TITLE
VPN toolbar button should have disconnected state when changed to not-purchased state during the runtime

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#33023]
For now vpn toolbar button can have green state
when purchased state is entered into `non-purchased`(ex, `not purchased` or `session expired`) during the runtime.
It should be gray state in this situation.

STR
1. Set purchased state and connect to vpn
2. Check vpn button is green
3. Reset skus state from brave://skus-internals
4. Check vpn button is gray

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.61.60 Chromium: 119.0.6045.105 (Official Build) beta (64-bit)
-- | --
Revision | 1ecda441378e2e473fd84b38456413224121751c
````

installed 1.61.60
launched Brave
purchase and configure VPN on account.bravesoftware.com
connect to VPN

![image](https://github.com/brave/brave-browser/assets/98358127/85df36d3-8ef3-4a28-8a56-cd11bb7add34)

**Comment by MadhaviSeelam** [comment]
Not adding `QA Pass - Win 64` label for Win 10 verification

**Comment by stephendonner** [comment]
## Verification `PASSED` using 

```
Brave | 1.61.62 Chromium: 119.0.6045.105 (Official Build) beta (64-bit)
-- | --
Revision | 435a38586472c662beec0fc75f622b7dfaa1e77d
OS | Windows 10 Version 22H2 (Build 19045.3636)
```

### Steps:
1. installed `1.61.62`
2. launched Brave
3. purchased, configured, and connected to `Brave VPN` using `account.bravesoftware.com`
4. confirmed VPN toolbar button shows `green`
5. opened `brave://skus-internals`
6. clicked `Reset SKUs state` button
7. clicked `OK`

### Confirmed VPN toolbar button shows `grey`, disconnected state

### Confirmed when clicking on the VPN button, not-purchased state modal shown

`Step 5` | `Step 6` | `Step 8` | `Disconnected` state | `Not purchased` state
---------|---------|----------|------------------------|------------------------
![image](https://github.com/brave/brave-browser/assets/387249/3406d3fd-0084-486d-bf01-48f082851cd5) | ![image](https://github.com/brave/brave-browser/assets/387249/fc3c9e99-9f70-41c9-bc36-e366178d672f) | ![image](https://github.com/brave/brave-browser/assets/387249/8b6b1cc5-945a-4e13-86ab-9a6084c9edea) | ![image](https://github.com/brave/brave-browser/assets/387249/634158d6-9c4b-467f-9acf-803845af3fbb) | ![image](https://github.com/brave/brave-browser/assets/387249/b74629bf-52de-43d3-9084-e11b510e04d3) | ![image](https://github.com/brave/brave-browser/assets/387249/e0bc478b-a97f-4c2f-951c-f2b0bbea7c31)

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.61.67 Chromium: 119.0.6045.105 (Official Build) beta (x86_64)
-- | --
Revision | 09cc687dc27ccd8acafeebf5af1dc620b4d9cb22
OS | macOS Version 14.2 (Build 23C5030f)
```

`step 5` | `step 6` | `step 8` | `Disconnected` state | `Not purchased` state
---------|----------|---------|-----------------------|-----------------------
<img width="1231" alt="Screenshot 2023-11-07 at 1 04 15 PM" src="https://github.com/brave/brave-browser/assets/387249/8b109a82-a82c-4ed6-b49b-700c83b935ab"> | <img width="1231" alt="Screenshot 2023-11-07 at 1 06 10 PM" src="https://github.com/brave/brave-browser/assets/387249/49117751-211f-4c3b-9d9d-b297d4afe2ce"> | <img width="1231" alt="Screenshot 2023-11-07 at 1 07 14 PM" src="https://github.com/brave/brave-browser/assets/387249/e891672d-4e22-408c-acd4-c3f2dff45267"> | <img width="1231" alt="Screenshot 2023-11-07 at 1 07 17 PM" src="https://github.com/brave/brave-browser/assets/387249/14278ffb-c221-4e17-8122-b69e7091d300"> | <img width="1231" alt="Screenshot 2023-11-07 at 1 08 56 PM" src="https://github.com/brave/brave-browser/assets/387249/f7e8d0d5-f4ff-431d-ace9-6401c6eb3dc8">

**Comment by kjozwiak** [comment]
Removing the `QA-Pass` labels as the above was uplifted from `1.61.x` into `1.60.x` so we'll need to re-check against the `1.60.x` branch once we have RC's available with the above fix. The above requires `1.60.123` or higher for `1.60.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.60.124 Chromium: 119.0.6045.163 (Official Build) (x86_64)
-- | --
Revision | 803c85554783c998a840f4b211c94236409a9928
OS | macOS Version 13.6.1 (Build 22G313)
```

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.60.124 Chromium: 119.0.6045.163 (Official Build) (x86_64)
-- | --
Revision | 803c85554783c998a840f4b211c94236409a9928
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed 1.60.x
2. launched Brave
3. purchased, configured, and connected to Brave VPN using account.bravesoftware.com
4. confirmed VPN toolbar button shows green
5. opened brave://skus-internals
6. clicked Fetch SKUs state
7. confirmed it populated with credentials
8. clicked Reset SKUs state button
9. clicked OK


## Confirmed VPN toolbar button shows grey, disconnected state

## Confirmed when clicking on the VPN button, not-purchased state modal shown (on the panel)


step 4 | step 6 | step 8 | `Disconnected` state (button) | `Not purchased` state (panel)
-------|-------|--------|--------------------------------|------------------------------
<img width="1513" alt="Screen Shot 2023-11-27 at 9 11 05 AM" src="https://github.com/brave/brave-browser/assets/387249/d1d71055-5422-4917-a917-e53373e0a594"> | <img width="1513" alt="Screen Shot 2023-11-27 at 9 14 33 AM" src="https://github.com/brave/brave-browser/assets/387249/01231848-275e-46c1-9265-7a5580b03976"> | <img width="1513" alt="Screen Shot 2023-11-27 at 9 14 41 AM" src="https://github.com/brave/brave-browser/assets/387249/96477922-a383-45af-a78b-9ccaf17fc28a"> | <img width="1513" alt="Screen Shot 2023-11-27 at 9 14 48 AM" src="https://github.com/brave/brave-browser/assets/387249/0b825c87-ac10-481d-bac2-21b84f43b183"> | <img width="1513" alt="Screen Shot 2023-11-27 at 9 15 18 AM" src="https://github.com/brave/brave-browser/assets/387249/939db0f5-904c-44a2-9919-36f5ecda7a27">
