### ISSUE TITLE
Add YouTube si param (JS) to copy clean link filter

### ISSUE THREAD

**Issue by cadatoiva** [brave/brave-browser#33037]
## Description 
SI (Source ID?) is a new query parameter found in YouTube share links when using their native share feature. I'd like to see it added to the filter for the Copy Clean Link feature. 

## Brave version (brave://version info)
1.58.124 Chromium: 117.0.5938.62 (Official Build) (64-bit) 

## Miscellaneous Information:
There is a tampermonkey script already made that also removes if from the share window entirely as if YouTube never changed the feature, for reference: https://github.com/Xenorio/YTShareAntiTrack

Is it also possible to get something similar to this included natively? Or to override the default javascript copy functions used by the copy button on the site to utilize copy clean link?

**Comment by rebron** [comment]
cc: @fmarier

**Comment by fmarier** [comment]
That's interesting, if I share a video while logged **in**, I get this (no `si` param):

https://youtu.be/dQw4w9WgXcQ?feature=shared

but if I share a video while logged **out** (in a private window), then I do get the `si` param:

https://youtu.be/dQw4w9WgXcQ?si=YjziZuccJeIE-b6z

It's a different ID if I open another private window:

https://youtu.be/dQw4w9WgXcQ?si=-L1iutc6oF6I9fkR

@cadatoiva Do you see the same thing as me or is it perhaps related to something in my Google account settings?

**Comment by fmarier** [comment]
Note: this issue is about extending the copy-clean link feature to hook into the "copy to clipboard" JS code (what gets triggered when clicking YouTube's copy button instead of using regular copy/paste).

The regular copy-clean link list has already been updated in https://github.com/brave/adblock-lists/pull/1317.

**Comment by fmarier** [comment]
Note that this also affects Instagram: https://github.com/brave/brave-browser/issues/35094

**Comment by fmarier** [comment]
Test plan is (in a **private window**):
1. Open https://www.youtube.com/watch?v=G1IbRujko-A
2. Click the _Share_ button
3. Click the _Copy_ button
4. Paste in a text editor

Actual:
* `https://youtu.be/G1IbRujko-A?si=E2YqZmvcWqjSh8cW`

Expected:
* `https://youtu.be/G1IbRujko-A`

The `si` parameter gets removed via the [clean-urls list](https://github.com/brave/adblock-lists/blob/ac04436134fceb01ed4e5416428468df29a4d3f3/brave-lists/clean-urls.json#L264).

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.68.106 Chromium: 126.0.6478.126 (Official Build) beta (64-bit)
-- | --
Revision | 8d682ca0cb836cac019e09be7744d3852e68953e
OS | Windows 11 Version 23H2 (Build 22631.3810)
```

Verified using the testplan from https://github.com/brave/brave-core/pull/24207#issue-2353215767

Normal window

1. Installed 1.68.106
2. launched Brave
3. loaded  https://boocmp.github.io/clipboard/ in a new tab

**Comment by fmarier** [comment]
> Note: currently step 4 modification is needed to pass this test as per @boocmp. Once the bug is fixed, no need to do modify the `clean-urls-permissions.json` file.

Fix for that is here: https://github.com/brave/adblock-lists/pull/1879
