### ISSUE TITLE
Several tabs simultaneously crash with `Error code: STATUS_ACCESS_VIOLATION`

### ISSUE THREAD

**Issue by hamirmahal** [brave/brave-browser#33046]

**Comment by hamirmahal** [comment]
## Description 

I was doing regular web browsing when several tabs crashed with the message `Error code: STATUS_ACCESS_VIOLATION`.


## Steps to Reproduce


   1. Browse the web.

## Actual result:

Several tabs crash with the message `Error code: STATUS_ACCESS_VIOLATION`.

## Expected result:
No tabs crash.


## Reproduces how often: 

Intermittently

## Brave version (brave://version info)

Unable to determine because I can't use Brave.

![image](https://github.com/brave/brave-browser/assets/43425812/0d9e01c5-a248-436a-8a37-6fc4dc62b7a5)

## Version/Channel Information:


- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? I'm using Edge to report this, and it works without any issues.
```
Microsoft Edge	116.0.1938.81 (Official build) (64-bit)
Revision	bc0eb28b55bd39571b5d9b4b46f78b06ab9e80b0
Chromium version	116.0.5845.188
```

## Miscellaneous Information:

**Comment by hamirmahal** [comment]
Brave started working again after restarting my PC.

**Comment by hamirmahal** [comment]
## Brave version (brave://version info)


1.58.124 Chromium: 117.0.5938.62 (Official Build) (64-bit) 
5c0e98018fb16948401122cb9af1a5a0a6b40865
Windows 10 Version 22H2 (Build 19045.3448)

**Comment by rebron** [comment]
@hamirmahal Is it working fine now?

**Comment by hamirmahal** [comment]
@rebron I haven't run into the issue again since I've reported it.

**Comment by rebron** [comment]
@hamirmahal I'm going to go ahead and close this one then. Thanks for filing.

**Comment by hamirmahal** [comment]
@rebron it just happened again.

**Comment by hamirmahal** [comment]
![image](https://github.com/brave/brave-browser/assets/43425812/7c70898d-78fd-4592-994d-51b460622268)

`Error code: STATUS_ACCESS_VIOLATION`

**Comment by hamirmahal** [comment]
It just happened again when visiting LinkedIn.

**Comment by hamirmahal** [comment]
![image](https://github.com/brave/brave-browser/assets/43425812/8b9478cf-180a-4ba7-94c9-229b04c83677)

**Comment by hamirmahal** [comment]
I'm happy to provide any metadata that could help triage or troubleshoot this. Let me know what data would be helpful, and how to get it.

**Comment by hamirmahal** [comment]
It occurred again just now.

![image](https://github.com/brave/brave-browser/assets/43425812/d407a6bd-8e7a-45c4-bb8a-4f756486255e)

**Comment by hamirmahal** [comment]
It happened again right now.

![image](https://github.com/brave/brave-browser/assets/43425812/89449322-1257-4ee7-ad2c-a842e6458329)

**Comment by hamirmahal** [comment]
That was on YouTube.

**Comment by hamirmahal** [comment]
Memory usage seems fine, at about 50% usage of available memory.

![image](https://github.com/brave/brave-browser/assets/43425812/158344a5-ea7b-4d64-9b57-a78f810600c9)

**Comment by hamirmahal** [comment]
@rebron let me know if you want me to reopen this as a separate issue, or if you want me to provide more data.

**Comment by hamirmahal** [comment]
It just happened again.

![image](https://github.com/brave/brave-browser/assets/43425812/3595985f-734b-460a-83b4-10142f21f46f)

**Comment by hamirmahal** [comment]
I entered a search query on YouTube in a private browsing window.

**Comment by hamirmahal** [comment]
I entered a search query on YouTube via a Brave search shortcut, in a private browsing window.

**Comment by hamirmahal** [comment]
It just happened again.

![image](https://github.com/brave/brave-browser/assets/43425812/52137eaa-b732-4bf9-aa54-49355ab8d854)

**Comment by hamirmahal** [comment]
I just ran into it again.

**Comment by hamirmahal** [comment]
It was while watching a YouTube video in a private browsing window.

![image](https://github.com/brave/brave-browser/assets/43425812/227195de-d1c7-44ca-bb8c-6a9edfafb39c)

**Comment by hamirmahal** [comment]
It just happened again while on GitHub.

**Comment by hamirmahal** [comment]
![image](https://github.com/brave/brave-browser/assets/43425812/5b86d3ba-bf79-48e4-ba99-f8841cd42977)

**Comment by jackschedel** [comment]
@hamirmahal were you ever able to resolve this? Sorry to necro.

**Comment by hirehamir** [comment]
@jackschedel No worries.

It's been a while, but I think this issue either went away on its own, or after I manually updated the CPU drivers for my i7-6700K.
