### ISSUE TITLE
Incorrect text on forgetful browsing settings entry

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#33048]
## Description 
The toggle for forgetful browsing in `brave://settings/shields` reads as follows:
```
Forget me when I close this site
Clears cookies and other site data when you close a site.
```

## Expected result
This is confusing because "this site" doesn't exist in the case of the settings page. It should actually say "every site, by default" (or something along those lines).

```
Forget me when I close every site, by default
Clears cookies and other site data when you close a site.
```

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.62.32 Chromium: 119.0.6045.105 (Official Build) nightly (64-bit)
-- | --
Revision | 76f975d47c49751a29f222762c1a24bd7df88cef
OS | Windows 11 Version 22H2 (Build 22621.2428)
```

1. Installed 1.62.32
2. launched Brave
3. opened `brave://settings/shields` in a new tab
4. close and relaunch to pull in Griffin
5. confirmed `Clear session data when a site is closed` setting available and is disabled by default

#### Confirmed correct text displayed as below for the setting and matched to the screenshot https://github.com/brave/brave-core/pull/20808#issue-1973340631
`"Clear session data when a site is closed".  `                                                          
`"Clears cookies and other site data when you close a site."`


step 4 | step 5
---- | -----
<img width="646" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/f99cc5a8-83bf-4125-8812-214fd8cc7fbe">|<img width="645" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/0d76c5de-180a-433f-acf3-e24e58eff392">

**Comment by LaurenWags** [comment]
@simonhong is there a reason this was reopened? We don't reopen issues, we log a new one/follow up if needed. 

I'm closing this one so please open a new issue if needed.

**Comment by simonhong** [comment]
> @simonhong is there a reason this was reopened? We don't reopen issues, we log a new one/follow up if needed.
> 
> I'm closing this one so please open a new issue if needed.

Fix for this PR was reverted by https://github.com/brave/brave-browser/issues/34504#issuecomment-1830881329
so this was reopened. Should we reopen another one?

**Comment by LaurenWags** [comment]
@simonhong we generally always open a new issue otherwise things get messy if code landed in a milestone with an issue and then that issue gets reopened.

However, if this one is already reverted and is in the appropriate milestone, I'll let @kjozwiak weigh in on this in case he feels differently.

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.62.121`

- As per the comments https://github.com/brave/brave-browser/issues/33048#issuecomment-1848828430 from @simonhong, the PR which is merged in this issue is reverted. Just verified the strings `Forget me when I close this site` in the Shields menu and in `brave://settings/shields` is same as in 1.60.x/1.61.x

Example | Example
----------|----------
![Screenshot_20231228_105047](https://github.com/brave/brave-browser/assets/38657976/b5c377ae-1a97-4ffe-8bfe-6e6c92a5f230) | ![Screenshot_20231228_105107](https://github.com/brave/brave-browser/assets/38657976/9aa63f08-675a-44a2-800e-0e01eb665182)

**Comment by LaurenWags** [comment]
Per discussion with @kjozwiak, re-labeled this one as `QA Pass-Win64` as it was verified prior to the revert by @MadhaviSeelam via https://github.com/brave/brave-browser/issues/33048#issuecomment-1800329654.

The revert was tested by @stephendonner on desktop via https://github.com/brave/brave-browser/issues/34504#issuecomment-1830920465.
