### ISSUE TITLE
Conditions acceptance

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#33042]
There is no way to view a top portion of a page to accept conditions when the page isn't full screen.

[Screen_recording_20230915_162855.webm](https://github.com/brave/brave-browser/assets/12011303/f0d12294-6c17-46ed-acc2-e3ade5611016)

**Comment by petemill** [comment]
Container just needs padding-top for the height of the fixed toolbar @nullhook

**Comment by SergeyZhukovsky** [comment]
a dup https://github.com/brave/brave-browser/issues/33320
