### ISSUE TITLE
Unsupported ads per hour value for notification ads for default_ads_per_hour = 0

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#33044]
`NotificationAds:default_ads_per_hour/0` flag breaks ads per hour value for notification ads

## Steps to Reproduce

1. Clean install
2. Run Brave:
```
--enable-features=NotificationAds:default_ads_per_hour/0
```
3. Enable rewards
4. Open `brave://rewards`

## Actual result:

`None` as value
![image](https://github.com/brave/brave-browser/assets/34715963/01d61962-5c61-4561-8718-775603929a32)
![image](https://github.com/brave/brave-browser/assets/34715963/6cef837b-65ed-4c6b-8458-7afe885d1682)

## Expected result:
Notification ads are disabled
![image](https://github.com/brave/brave-browser/assets/34715963/025e433d-30c8-44ab-8181-7f7c5d657a0f)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.58.124 Chromium: 117.0.5938.62 (Official Build) (64-bit)
-- | --
Revision | 5c0e98018fb16948401122cb9af1a5a0a6b40865
OS | Linux

cc @aseren @tmancey @LaurenWags

**Comment by tmancey** [comment]
This would only affect staging environment and those users who override features via command-line args. Will not fix at this time, unless of course this is causing issues for testing.
