### ISSUE TITLE
‘Brave exe-Entry Point Not Found.’

### ISSUE THREAD

**Issue by Saoiray** [brave/brave-browser#33058]
## Description 
Brave is not opening and is providing message:

> Brave exe-Entry Point Not Found
> 
> The procedure entry point lsEnclaveTypeSupported could not be located in the dynamic link library C:\Program Files\ BraveSoftware\Brave-Browser/Application\117.1.58.124\chrome.dll

## Steps to Reproduce

Try to open Brave

## Actual result:

![image](https://github.com/brave/brave-browser/assets/99627477/e3d08def-5a8b-4441-a774-14649f44c3b9)

## Expected result:

Brave opens

## Reproduces how often: 
Every time

## Brave version (brave://version info)
1.58.124

## Version/Channel Information:
Release

## Miscellaneous Information:

I am merging all topics from users experiencing this issue over to https://community.brave.com/t/brave-entry-point-not-found-error-in-windows/505944 and trying to gather more information and troubleshooting. 

@rebron @Brave-Matt just tagging you two to try to put this on your radar.

**Comment by rebron** [comment]
cc: @iefremov @atuchin-m

**Comment by Saoiray** [comment]
Oh, just found https://support.google.com/chrome/thread/234827907?hl=en&msgid=235106432

So guess was a Chromium issue already identified and resolved. So just needs to be rolled into Brave I guess.

**Comment by rebron** [comment]
Fix is here: https://github.com/brave/brave-core/pull/20193

**Comment by kjozwiak** [comment]
Just an update. We've merged `117.0.5938.88` into `master`, `BETA` and `Nightly` as per https://github.com/brave/brave-core/pull/20193, https://github.com/brave/brave-core/pull/20194 & https://github.com/brave/brave-core/pull/20193. We started `nightly-v1.60.30-public` & `beta-v1.59.90-public` which should be pushed out within ~4-5hrs once the builds complete.

We also started `release-v1.58.127` for the `release` channel which should go by EOD today (Sat Sept, 16, 2023).

**Comment by rebron** [comment]
Closing as fixed with https://github.com/brave/brave-browser/issues/33058#issuecomment-1722266869

**Comment by kjozwiak** [comment]
**`Quick note:`** Unfortunately I don't have a machine that can reproduce the above issue as I basically verified that installing `1.58.127 Chromium: 117.0.5938.88` didn't cause any issues on `Win 11` & `Win 10`

Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.58.127 Chromium: 117.0.5938.88 (Official Build) (64-bit)
-- | --
Revision | ed4ee11d4f6add8e0885cfab17943837d3d426c1
OS | Windows 11 Version 22H2 (Build 22621.2283)
```

Installed/launched `1.58.127 Chromium: 117.0.5938.88` and ensured that the above issue didn't occur/crash Brave.

-----------------

Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.58.127 Chromium: 117.0.5938.88 (Official Build) (64-bit)
-- | --
Revision | ed4ee11d4f6add8e0885cfab17943837d3d426c1
OS | Windows 11 Version 22H2 (Build 22621.2283)
```

Installed/launched `1.58.127 Chromium: 117.0.5938.88` and ensured that the above issue didn't occur/crash Brave.
