### ISSUE TITLE
Account Icon and Info need alignment in SIWE Panel

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#33051]
## Description 

The Account `Icon` and `Info` need to be center aligned in the SIWE Panel

## Steps to Reproduce

   1. 
   2. 
   3. 

## Actual result:

![image](https://github.com/brave/brave-browser/assets/40611140/472a082f-ad4c-45aa-b6df-1afca83d862f)

## Expected result:
Should be center aligned

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.60.81 Chromium: 118.0.5993.54 (Official Build) beta (64-bit)
-- | --
Revision | `1efb3f333eb41cc34af46ca31fb33c30e0afbfae`
OS | Windows 11 Version 22H2 (Build 22621.2283)

- Verified steps from [brave/brave-core#20242](https://github.com/brave/brave-core/pull/20242)
- Verified Account Icon and Info are properly aligned on SIWE panel
![brave_6teGPdfhX6](https://github.com/brave/brave-browser/assets/17010094/0680e0d4-e258-46cf-adc6-269f75fab74b)

---------------------

**Verification passed on**

Brave | 1.60.81 Chromium: 118.0.5993.54 (Official Build) beta (64-bit)
-- | --
Revision | `1efb3f333eb41cc34af46ca31fb33c30e0afbfae`
OS | Linux

- Verified steps from [brave/brave-core#20242](https://github.com/brave/brave-core/pull/20242)
- Verified Account Icon and Info are properly aligned on SIWE panel
![SIWE_Linux](https://github.com/brave/brave-browser/assets/17010094/faeeb553-a128-4578-94ce-55639e564bf9)

---------------------

**Verification passed on**

Brave | 1.60.81 Chromium: 118.0.5993.54 (Official Build) beta (arm64)
-- | --
Revision | `1efb3f333eb41cc34af46ca31fb33c30e0afbfae`
OS | macOS Version 14.0 (Build 23A344)

- Verified steps from [brave/brave-core#20242](https://github.com/brave/brave-core/pull/20242)
- Verified Account Icon and Info are properly aligned on SIWE panel
![image](https://github.com/brave/brave-browser/assets/17010094/ebc9a0c9-5a66-4f4c-9c73-480c9c488048)
