### ISSUE TITLE
Delay in loading page objects - slight performance degrade on 0.60.x

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#3306]
## Description 

Due to delay in loading page objects, `Allow contribution to videos` checkbox is unchecked by default. When we refresh the brave://rewards page or visit other pages and navigate back to auto contribution settings page, the `Allow contribution to videos` checkbox is checked automatically.

## Steps to Reproduce

   1. Clean profile 0.60.25
   2. Enable rewards through rewards panel
   3. Open Auto contribution settings page

## Actual result:
`Allow contribution to videos` checkbox is unchecked by default
![unchecked by default](https://user-images.githubusercontent.com/38657976/52553089-78a1da80-2e08-11e9-84cf-a8451f4428e0.gif)

## Expected result:
`Allow contribution to videos` checkbox should be checked by default

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 0.60.25 Chromium: 72.0.3626.96 (Official Build) beta (64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Windows 10

### Reproducible on current release: no
- Does it reproduce on brave-browser dev/beta builds? yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? na
- Is the issue reproducible on the latest version of Chrome? na

### Additional Information

@brave/legacy_qa @NejcZdovc

**Comment by kjozwiak** [comment]
@GeetaSarvadnya can you reproduce this every time on a clean profile? I tried reproducing the above on the following platforms:

* `Win 10 x64 VM` using `0.60.26 Chromium: 72.0.3626.96` - Couldn't reproduce
* `macOS 10.14.2 x64` using `0.60.26 Chromium: 72.0.3626.96` - Couldn't reproduce
* `Win 10 x64 (psychical machine)` using `0.60.26 Chromium: 72.0.3626.96` - Couldn't reproduce

For the above, I launched brave using a new profile and ensured that `Allow contribution to videos` was enabled by default when enabling Rewards via the Rewards panel and through `brave://rewards`.

**Comment by GeetaSarvadnya** [comment]
@kjozwiak I am able to reproduce the issue on `0.60.26`. This issue is happening due to delay in loading the page objects. If i keep open the auto contribute settings page and visit other pages, issues gets resolved automatically. 

![0 60 26_allow auto contribution is unchecked by default](https://user-images.githubusercontent.com/38657976/52583422-934e7080-2e55-11e9-89de-937a022395b7.gif)

But, on release version this delay is not there. I guess there is some performance degrade on `0.60.26`

**Comment by NejcZdovc** [comment]
I think something else is going, don't think it's related to performance

**Comment by kjozwiak** [comment]
STR seem easy enough but I haven't ran into the above on a VM nor my psychical machine. Wonder what the difference between @GeetaSarvadnya's machine/STR and mine are.

@LaurenWags can you see if you can reproduce this when you have some time?

**Comment by LaurenWags** [comment]
I have not been able to reproduce this - tried with below build. Will keep an eye out for it.


Brave | 0.60.48 Chromium: 72.0.3626.121 (Official Build) (64-bit)
-- | --
Revision | da3787ba355f18db7db52abf75c42afb408d656f-refs/branch-heads/3626@{#883}
OS | Mac OS X

**Comment by kjozwiak** [comment]
@GeetaSarvadnya can you still reproduce this?

**Comment by GeetaSarvadnya** [comment]
Unable to reproduce the issue on the current Release (`0.63.48`) and Beta build (`0.64.60`)
