### ISSUE TITLE
Unable to install Cookie AutoDelete extension

### ISSUE THREAD

**Issue by MuhammedKpln** [brave/brave-browser#3307]
## Description 
Cannot install 'Cookie AutoDelete' extension

## Steps to Reproduce

   1. Visit chrome.google.com/webstore
   2. Find and install Cookie AutoDelete
   3. And wala! gives Extension invalid. Details: 'Variable $matchedExpression$ used but not defined.'

## Actual result:
Should install the extension

## Expected result:
Gives `Extension invalid. Details: 'Variable $matchedExpression$ used but not defined.'`

## Brave version (brave://version info)
Brave | 0.59.35 Chromium: 72.0.3626.81 (Resmi Derleme) (64 bit)

### Reproducible on current release:
Yes it does on brave browser dev version 0.61.20 Chromium: 72.0.3626.81 (Resmi Derleme) dev (64 bit) Sürümü

**Comment by srirambv** [comment]
Can't reproduce on Linux on release/beta/dev channels.  @MuhammedKpln which OS are you running ?

cc: @brave/legacy_qa to verify on other platforms.

**Comment by MuhammedKpln** [comment]
Running on Fedora 29

**Comment by srirambv** [comment]
Could you screen record the steps? I am unable to reproduce the issue on Ubuntu with any of the builds
![image](https://user-images.githubusercontent.com/17010094/52571694-182c9080-2e3c-11e9-87ec-ecfe6c14d142.png)

**Comment by MuhammedKpln** [comment]
Sure, here.
https://youtu.be/5VuuosGS0lE

**Comment by srirambv** [comment]
Still can't reproduce. 
![vokoscreen20190211_211244](https://user-images.githubusercontent.com/17010094/52574295-fdf5b100-2e41-11e9-8221-756aa5412b84.gif)


cc: @bbondy could this be due to different locale on the browser?

**Comment by kjozwiak** [comment]
Couldn't reproduce this either using the following build:

Brave | 0.61.38 Chromium: 73.0.3683.39 (Official Build) beta(64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Mac OS X

**Comment by DrSelami** [comment]
I solved the issue by changing the language to "English (United States)" in the settings.

**Comment by bsclifton** [comment]
@DrSelami thanks for the clue - I suspect user would need to change locale when trying to reproduce this issue

**Comment by rebron** [comment]
> I solved the issue by changing the language to "English (United States)" in the settings.

Closing as stale with workaround provided by @DrSelami
