### ISSUE TITLE
Linux enable Widevine on all architectures if present (patch included)

### ISSUE THREAD

**Issue by theofficialgman** [brave/brave-browser#33081]
## Description 
Widevine only checked for on x64

## Steps to Reproduce

   1.  supply widevine on non-x64 architecture (eg: linux arm64)
   2. see that widevine isn't even attempted to be loaded

## Actual result:
widevine not attempted to be loaded

## Expected result:
widevine is attempted to be loaded if present

## Reproduces how often: 
every time

## Brave version (brave://version info)
all versions

## Patch
https://git.launchpad.net/~chromium-team/chromium-browser/+git/snap-from-source/tree/build/chromium-patches/widevine-enable-version-string.patch?h=dev

refer to https://bugs.launchpad.net/ubuntu/bionic/+source/chromium-browser/+bug/2008433

this was added on chromium on ubuntu bionic and snap in March of this year.

**Comment by Emi-TheDhamphirInLoveUnderTheFrozenStar** [comment]
https://github.com/brave/brave-core/pull/19919

**Comment by btlechowski** [comment]
Issue still reproducible

Brave | 1.63.161 Chromium: 122.0.6261.57 (Official Build) (64-bit) 
-- | --
Revision | 37b02b4a373f40114e70cc034e491bcc8380f23a
OS | Ubuntu ARM 64

The prompt to install Widevine is not shown

![image](https://github.com/brave/brave-browser/assets/34715963/0c99b915-a301-46a2-a19d-305ac34c028c)

Per our process logged a follow up 

------------

Verified with

Brave | 1.63.161 Chromium: 122.0.6261.57 (Official Build) (64-bit) 
-- | --
Revision | 37b02b4a373f40114e70cc034e491bcc8380f23a
OS | Ubuntu x64

**Comment by theofficialgman** [comment]
this issue is solved and can stay closed.
