### ISSUE TITLE
[Android] Payout begin banner is not shown in the BR panel

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#33088]
## Description 
Found while testing https://github.com/brave/brave-browser/issues/28052
Payout begin payout banner is not shown in the BR panel
## Steps to reproduce 

1. Clean profile 1.59.x
2. Enable rewards and connect a custodian
3. View a couple of Ads and confirm ads are cashed in with the server
4. Close the browser
5. Advance the sys clock to any date between 1st to 7th of next month (I have set date as 1st Oct)
6. Use Charles Proxy to simulate pending message being returned from the `/parameter` endpoint (set empty string or `off` to the  `/parameter` endpoint )
7. Relaunch the browser
8. Confirmed that `The payout for [previous month] rewards will begin processing by [payment date]” message is shown in the rewards settings page as expected in the rewards settings page. But there is no begin payout message displayed in the BR panel.

## Actual result 
Payout begin payout banner is not shown in the BR panel

## Expected result
Payout begin banner should be shown in the BR panel

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version?Not sure

## Device details
   - Install type (ARM, x86): all
   - Device type (Phone, Tablet, Phablet): all
   - Android version:12
   
## Brave version
1.59.86

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?NA 
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/qa-team @Miyayes @deeppandya @sujitacharya2005

**Comment by Miyayes** [comment]
@deeppandya Just a point of clarification: At the /parameters endpoint, the payoutStatus can only be `off`, `processing`, or `completed`. There is no `pending` string that appears at the /parameters endpoint itself. The "pending" status (i.e., the countdown from the 1st till the 7th of the month) is built into the browser/client, and not received from the endpoint.

**Comment by kjozwiak** [comment]
The above requires `1.59.111` or higher for `1.59.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.59.112`


- Verified the STR from the https://github.com/brave/brave-browser/issues/33088#issue-1900592263
- Confirmed that the Payout begin banner is shown in the BR panel as well on the ads panel in the rewrads settings page when the sys date is set to any date between 1 to 7th of the next month and `/parameter` endpoint value is set to empty or `off`
- Confirmed that none of the banner are shown when the system date is set to payout date or after the payout date when the `/parameter` endpoint value is set to empty or `off`
- Confirmed that the payout complete banner is shown in the BR panel as well on the ads panel in the rewrads settings page when the sys date is set to any date between 1 to 7th of the next month and `/parameter` endpoint value is set to `complete`
- Confirmed that the payout processing banner is shown in the BR panel as well on the ads panel in the rewrads settings page when the sys date is set to any date between 1 to 7th of the next month and `/parameter` endpoint value is set to `processing`

Example | Example
----------|----------
![Screenshot_20231103_172939](https://github.com/brave/brave-browser/assets/38657976/e3874b4c-5b0d-4106-8946-a1b4d22acfce) | ![Screenshot_20231103_172945](https://github.com/brave/brave-browser/assets/38657976/eaf358ed-1143-49ed-8eba-de64858c8aa6)



```
[ REQUEST ]
    > URL: https://api.rewards.bravesoftware.com/v1/parameters
    > Method: GET
-------
     [ RESPONSE - OnResponse ]
    > Url: ***************************************************
    > Result: Success
    > HTTP Code: 200
    > Body: {"autocontribute":{"choices":[1,2,3,5,7,10,20],"defaultChoice":1},"batRate":0.170927,"custodianRegions":{"bitflyer":{"allow":["JP"],"block":[]},"gemini":{"allow":["US","CA","SG","GB"],"block":[]},"uphold":{"allow":["AD","AU","AR","AT","BE","BR","BS","BZ","CA","CH","CL","CO","CR","CY","CZ","DK","EC","EE","FI","FR","GD","GT","GR","HK","HN","HU","IE","IS","IT","JM","KY","LI","LT","LV","LU","MC","MT","MX","NI","NO","NZ","PE","PT","PY","SG","TR","UY","ES","SE","GB","US","UM","ZA","PL","SK","HR","SI","GR","TW"],"block":[]},"zebpay":{"allow":["IN"],"block":[]}},"payoutStatus":{"bitflyer":"complete","gemini":"complete","payoutDate":"","unverified":"complete","uphold":"","zebpay":"complete"},"tips":{"defaultMonthlyChoices":[1.25,5,10.5],"defaultTipChoices":[1.25,5,10.5]},"vbatDeadline":"2023-01-25T04:00:00Z","vbatExpired":false}
2023-11-03 17:29:02.218 25339-25339/? V/chromium: [VERBOSE1:api_parameters.cc(88)] Params timer set for 10928 s
```
