### ISSUE TITLE
Update attribution link

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#33080]
## Description 

Update the attribution link for Gordon Ross NTP background image
<img width="1478" alt="Screenshot 2023-09-17 at 5 22 49 PM" src="https://github.com/brave/brave-browser/assets/5951041/178d466d-9042-4ee7-85f8-73944415af63">
Current is a mailto to gordonsross 
Attribution link needs to change to `https://www.etsy.com/uk/listing/1518462333/pontoon-lake-annecy`

## Steps to Reproduce

   1. Open new tab page until you get to Gordon Ross' ntp.
   2. Hover or click on link
   3. Link should be the etsy link above.

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by simonhong** [comment]
Tested with prod. We'll see updated link after updating background components to `1.0.12`.
![image](https://github.com/brave/brave-browser/assets/6786187/793c35d4-d06e-4f2e-87ae-c410fe7061ec)

**Comment by simonhong** [comment]
Closed as updated on all platforms.
