### ISSUE TITLE
Crash when prompted for Bluetooth-enabled permission

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#33082]
## Description 

Crash when prompted for Bluetooth-enabled permission

Found while testing https://github.com/brave/brave-browser/issues/31605

## Steps to Reproduce

1. install `1.59.90`
2. launch Brave
3. open `brave://flags`
4. set the `Web Bluetooth API` flag to `Enabled`
5. click on `Relaunch`
6. load `permission.site`
7. click on `Bluetooth`

## Actual result:

Crashes:

```
[ 00 ] 0x7fff2031554e
[ 01 ] 0x7fff20316fe7
[ 02 ] __TCC_CRASHING_DUE_TO_PRIVACY_VIOLATION__
[ 03 ] __TCCAccessRequest_block_invoke.130
[ 04 ] __tccd_send_message_block_invoke
[ 05 ] _xpc_connection_reply_callout
[ 06 ] _xpc_connection_call_reply_async
[ 07 ] _dispatch_client_callout3
[ 08 ] _dispatch_mach_msg_async_reply_invoke
[ 09 ] _dispatch_kevent_worker_thread
[ 10 ] _pthread_wqthread
[ 11 ] start_wqthread
[ 12 ] 0x700003a73900
```

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave | 1.59.90 Chromium: 117.0.5938.88 (Official Build) beta (x86_64)
-- | --
Revision | 5272112c86588e44ec7c0b766c318cddccbced85
OS | macOS Version 11.7.10 (Build 20G1427)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `No`

cc @rebron @goodov @brave/qa-team @fmarier @ShivanKaul

**Comment by goodov** [comment]
looks like we need to add `NSBluetoothAlwaysUsageDescription` into plist.

https://developer.apple.com/documentation/bundleresources/information_property_list/nsbluetoothalwaysusagedescription

**Comment by stephendonner** [comment]
Yeah, this is fine on Windows (same build)

![image](https://github.com/brave/brave-browser/assets/387249/d9773044-c59f-46d9-bdd8-ce7008e64d83)

**Comment by goodov** [comment]
@stephendonner 

Hm. I tried `nightly` and `beta` builds, but I cannot reproduce this. We do have the right strings in plist, so this should work without issues. I'm on MacOS Version 13.5.2 (22G91).

It might be because of an old MacOS version. Can you try to run Chrome on the same MacOS? Does it work?

**Comment by stephendonner** [comment]
@goodov I retested using

```
Brave | 1.59.94 Chromium: 117.0.5938.88 (Official Build) beta (x86_64)
-- | --
Revision | 2dca22d0a20096c32df5af4c88700a0b31acb55c
OS | macOS Version 11.7.10 (Build 20G1427)
```

and this works again on both Big Sur and Sonoma macOS versions:

Big Sur 11.7.0 | Sonoma 14.0
--------------|-------------
<img width="1312" alt="Screen Shot 2023-09-21 at 10 51 27 AM" src="https://github.com/brave/brave-browser/assets/387249/7c298a1b-9ec3-4334-861b-7c2cc368e4e0"> | ![Screenshot 2023-09-21 at 10 45 35 AM](https://github.com/brave/brave-browser/assets/387249/94115f15-a3d9-4e74-a250-6cf3ae26c496)
