### ISSUE TITLE
Brave crashes on first launch since [1.58.124]

### ISSUE THREAD

**Issue by penguine0815** [brave/brave-browser#33086]
## Description 

Brave crashes on first launch since [1.58.124]

## Steps to Reproduce

   1. Update Brave
   2. Start Brave
   3. Brave doesn't start

## Actual result:

Brave doesn't start. Not possible to launch Brave anymore since version 1.58.124!

## Expected result:
Brave should start after update

## Reproduces how often: 

Every time

## Brave version (brave://version info)

Brave | 1.57.64 Chromium: 116.0.5845.188 (Offizieller Build) (64-Bit)
-- | --
Überarbeitung | 25c5f0154a27707e95614f4ae5c79975958e2d09

Betriebssystem | Linux Ubuntu 16.04
-- | --
JavaScript | V8 11.6.189.20
User-Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

## Version/Channel Information:

- Can you reproduce this issue with the current release? Y
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the nightly channel? N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

## Miscellaneous Information:

Version 1.58.124, 1.58.127, 1.58.129 and also latest version 1.58.131 are crashing at start. Version 1.57.64 is fine

Terminal output:
andre@thinkpad-e570:~$ brave-browser
[0917/123816.461318:ERROR:elf_dynamic_array_reader.h(64)] tag not found
/usr/bin/brave-browser: Zeile 48: 10134 Speicherzugriffsfehler  (Speicherabzug geschrieben) "$HERE/brave" "$@"

**Comment by LaurenWags** [comment]
@penguine0815 looks like you mention you have Ubuntu 16.04, but the lowest version listed in https://support.brave.com/hc/en-us/articles/360021357112-What-are-the-system-requirements-to-install-Brave- for Ubuntu is 18+.

**Comment by penguine0815** [comment]
@LaurenWags Thanks for feedback, but bad news for me.
That’s right I’m on Ubuntu 16.04. Is there no way to get newer Brave to run anyway?

**Comment by LaurenWags** [comment]
@penguine0815 not to my knowledge, but possible that others will have a better idea.

**Comment by iefremov** [comment]
stale
