### ISSUE TITLE
[Android] Incorrect month is shown in the payout banner in the BR panel 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#33087]
## Description 
Found while testing https://github.com/brave/brave-browser/issues/28052
Incorrect month is shown in the payout banner in the BR panel 
## Steps to reproduce 

Case 1:

1. Clean profile 1.59.x
2. Enable rewards and connect a custodian
3. View a couple of Ads and confirm ads are cashed in with the server
4. Close the browser
5. Advance the sys clock to any date in the next month (I set date to 30th Oct)
6. Use Charles Proxy to simulate "Processing" message being returned from the `/parameter` endpoint
7. Relaunch the browser

**Actual** : `The payout for September rewards is in progress. Check status` message is shown in the rewards settings page as expected. But in the BR panel the message is shown as `The payout for October rewards is in progress. Check status` 

Case 2:

1. Clean profile 1.59.x
2. Enable rewards and connect a custodian
3. View a couple of Ads and confirm ads are cashed in with the server
4. Close the browser
5. Advance the sys clock to any date in the next month (I set date to 30th Oct)
6. Use Charles Proxy to simulate "Complete" message being returned from the `/parameter` endpoint
7. Relaunch the browser

**Actual** : `The payout for September rewards has completed. Support` message is shown in the rewards settings page. But in the BR panel the message is shown as  `The payout for October rewards has completed. Support` 

## Actual result 

1. `The payout for September rewards is in progress. Check status` message is shown in the rewards settings page as expected. But in the BR panel the message is shown as `The payout for October rewards is in progress. Check status` 

2. `The payout for September rewards has completed. Support` message is shown in the rewards settings page. But in the BR panel the message is shown as  `The payout for October rewards has completed. Support` 

Example | Example
----------|--------
![Screenshot_20231028_145559](https://github.com/brave/brave-browser/assets/38657976/73b68367-da22-4f01-a1c9-af73d8a9eac8) | ![Screenshot_20231028_144937](https://github.com/brave/brave-browser/assets/38657976/ac38aff9-1b44-4d9e-9d65-ae4834e4cc32)

## Expected result

1. `The payout for September rewards is in progress. Check status` message should be shown in both rewards settings and BR panel

2. `The payout for September rewards has completed. Support` message should be shown in both rewards settings and BR panel

## Issue reproduces how often 

Easy
## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version?not sure

## Device details
   - Install type (ARM, x86): all
   - Device type (Phone, Tablet, Phablet):all
   - Android version: 12
   
## Brave version
1.59.86

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/qa-team @deeppandya @sujitacharya2005 @Miyayes

**Comment by Miyayes** [comment]
Conceptual note: Payouts in a given month (e.g., payout on October 7) are for rewards earned in the previous month (e.g., in September).

So, a payout in month `n` is always for earnings in month `n - 1`.

**Comment by kjozwiak** [comment]
The above requires `1.59.111` or higher for `1.59.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.59.112`

- Verified the cases from https://github.com/brave/brave-browser/issues/33087#issue-1900571197
- Confirmed that correct month is shown in the payout processing banner message in both BR panel and settings page
- Confirmed that correct month is shown in the payout complete banner message in both BR panel and settings page

**_Month display in Payout complete message:_**

Example | Example
----------|---------- 


**_Month display in Payout processing message:_**

Example | Example
----------|---------- 
![Screenshot_20231101_171541](https://github.com/brave/brave-browser/assets/38657976/ab56497b-e0f7-44de-8c79-f58157b7056a) | ![Screenshot_20231101_171549](https://github.com/brave/brave-browser/assets/38657976/48c1eeb2-46f8-4a05-a1b9-aaf4b1978a40)


```
[ REQUEST ]
    > URL: https://api.rewards.bravesoftware.com/v1/parameters
    > Method: GET
-------
[ RESPONSE - OnResponse ]
    > Url: https://api.rewards.bravesoftware.com/v1/parameters
    > Result: Success
    > HTTP Code: 200
    > Body: {"autocontribute":{"choices":[1,2,3,5,7,10,20],"defaultChoice":1},"batRate":0.170927,"custodianRegions":{"bitflyer":{"allow":["JP"],"block":[]},"gemini":{"allow":["US","CA","SG","GB"],"block":[]},"uphold":{"allow":["AD","AU","AR","AT","BE","BR","BS","BZ","CA","CH","CL","CO","CR","CY","CZ","DK","EC","EE","FI","FR","GD","GT","GR","HK","HN","HU","IE","IS","IT","JM","KY","LI","LT","LV","LU","MC","MT","MX","NI","NO","NZ","PE","PT","PY","SG","TR","UY","ES","SE","GB","US","UM","ZA","PL","SK","HR","SI","GR","TW"],"block":[]},"zebpay":{"allow":["IN"],"block":[]}},"payoutStatus":{"bitflyer":"complete","gemini":"complete","payoutDate":"","unverified":"complete","uphold":"processing","zebpay":"complete"},"tips":{"defaultMonthlyChoices":[1.25,5,10.5],"defaultTipChoices":[1.25,5,10.5]},"vbatDeadline":"2023-01-25T04:00:00Z","vbatExpired":false}
2023-11-01 12:46:31.525 32138-32138/? V/chromium: [VERBOSE1:api_parameters.cc(88)] Params timer set for 11469 s
```
