### ISSUE TITLE
Implement NFT management v2

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#33095]
Spec Document: https://docs.google.com/document/d/1Bexsf_A8CnSqy9jMx6d3P20mEer0oqKxMzycuGo9Cx4/edit#heading=h.a5obfplu7jk1

**Comment by kjozwiak** [comment]
The above requires `1.59.104` or higher for `1.59.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.59.112 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | 967f25f295938c64c24e2e6a1790470668757655
OS | Windows 11 Version 22H2 (Build 22621.2283)

- Verified steps from issue description
- Verified NFT tab is according to spec 
- Verified NFT tab has a dropdown list for Collected/Hidden 
- Verified Collected/Hidden shows the number of NFTs 
- Verified Spam NFT is marked as Junk
- Verified able to hide/unhide NFTs
- Verified able to remove a NFT from the list
- Verified NFT logo is shown when enabled in menu
- Verified marking an NFT as not Junk and hiding it again doesn't show the Junk label
- Verified a warning message is shown before removing NFT from wallet
- Encountered [#33306](https://github.com/brave/brave-browser/issues/33306)

https://github.com/brave/brave-browser/assets/17010094/fd6a40fd-cd6e-4e5f-aa3a-09cadfd187e3
