### ISSUE TITLE
`promo_code` not being created with builds using `C117`

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#33097]
## Description 

During the weekend, we noticed that DAU dropped ~90%. After investigation, looks like `promo_code` is not being created when installing build with `C117`. Hence, users are being placed into the `BRV001` bucket by default rather than the ref code that was attached to the executable. For example, downloading `BraveBrowserSetup-BRV002.exe` but being placed within `BRV001` as per the following:

```
         "promo_code": {
            "metadata": [ "user_controlled", "user_modifiable", "extension_modifiable" ],
            "value": "BRV001"
```

## Steps to Reproduce

   1. download `1.58.127 Chromium: 117.0.5938.88` from brave.com (should get something similar to `BraveBrowserSetup-BRV002.exe`
   2. during installation, keep an eye on `C:\Users\kamil\AppData\Local\BraveSoftware\Brave-Browser\User Data`
   3. notice that the `promo_code` never gets created/applied and then removed
   4. view `brave://local-state` and notice that `BRV001` is being used rather than `BRV002`

## Actual result:`

`promo_code` is not being created into  `C:\Users\kamil\AppData\Local\BraveSoftware\Brave-Browser\User Data` when installing

## Expected result:

Brave should be creating `promo_code` when being installed. The ref code appearing on the executable should be used via `brave://local-state`

## Reproduces how often: 

100% reproducible using the STR/Cases outlined above.

## Brave version (brave://version info)

```
Brave | 1.58.127 Chromium: 117.0.5938.88 (Official Build) (64-bit)
-- | --
Revision | ed4ee11d4f6add8e0885cfab17943837d3d426c1
OS | Windows 11 Version 22H2 (Build 22621.2283)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

## Miscellaneous Information:

CCing @bsclifton @rebron @aekeus @chrismore

**Comment by DJAndries** [comment]
Caused by upstream change: https://source.chromium.org/chromium/chromium/src/+/6a008b16fa4519f4164a5ecc5478645e334b4982

**Comment by GeetaSarvadnya** [comment]
The issue is Reproducible on `Windows 10 x64 - 1.58.127`

![image](https://github.com/brave/brave-browser/assets/38657976/e354a17a-d5b3-42ba-a108-134668a8db61)

**Comment by kjozwiak** [comment]
The above requires `1.58.129` or higher for `1.58.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.58.129 Chromium: 117.0.5938.88 (Official Build) (64-bit)
-- | --
Revision | 0ab74dc5473bd9dcd0a85653872988a5655aff6b
OS | Windows 10 Version 22H2 (Build 19045.3448)
```

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.58.129 Chromium: 117.0.5938.88 (Official Build) (x86_64)
-- | --
Revision | 0ab74dc5473bd9dcd0a85653872988a5655aff6b
OS | macOS Version 13.5.2 (Build 22G91)
```

**Comment by MadhaviSeelam** [comment]
Verification `In orogress` using
```
Brave | 1.58.129 Chromium: 117.0.5938.88 (Official Build) (64-bit)
-- | --
Revision | 0ab74dc5473bd9dcd0a85653872988a5655aff6b
OS | Windows 11 Version 22H2 (Build 22621.2283)
```



* downloaded `BraveBrowserStandaloneSetup.exe` via https://github.com/brave/brave-browser/releases/tag/v1.58.129
* renamed `BraveBrowserStandaloneSetup.exe` --> `BraveBrowserStandaloneSetup-BRV002.exe`

<img width="605" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/e352e46e-a77b-49b0-99c2-118567cf3df1">
