### ISSUE TITLE
Rewards ON/OFF state doesn't toggle Ads switch to ON/OFF, when rewards is opened in multiple tabs

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#3309]
## Description 
Found while testing #2961
Rewards ON/OFF state doesn't toggle Ads switch to ON/OFF, when rewards is opened in multiple tabs

## Steps to Reproduce

   1. Open brave 0.60.25
   2. Enable Rewards through rewards panel
   3. Turn OFF Rewards switch
   4. Click on BAT logo, click on `Settings` link which is displayed under `Brave Rewards is Off` popup 
        (Rewards page opened in 2nd tab)
   5. Turn ON Rewards in 2nd rewards tab.
   6. Verify that Ads switch is still in OFF state in 2nd rewards tab

Note: Reload the rewards page, resolve the issue

## Actual result:

Rewards ON/OFF state doesn't change Ads switch to ON/OFF, when rewards is opened in multiple tabs

![3309](https://user-images.githubusercontent.com/38657976/52584677-b169a000-2e58-11e9-8b21-b497483aebb0.gif)

## Expected result:
Rewards ON/OFF state should change Ads switch to ON/OFF without page refresh.

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.60.25 Chromium: 72.0.3626.96 (Official Build) beta (64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Windows 10

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds?  yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? na
- Is the issue reproducible on the latest version of Chrome? na

### Additional Information
@brave/legacy_qa @NejcZdovc

**Comment by LaurenWags** [comment]
Reproduced on macOS

Brave | 0.60.23 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Mac OS X
