### ISSUE TITLE
Devtools theme is different now in latest upgrade (1.58.127)

### ISSUE THREAD

**Issue by AustinGitHub** [brave/brave-browser#33094]
Version - Version 1.58.127 Chromium: 117.0.5938.88 (Official Build) (arm64)

![Screenshot 2023-09-18 at 8 37 43 AM](https://github.com/brave/brave-browser/assets/10100397/54c6048d-149b-4855-b905-adb3d4ed9e96)

Why did the theme change? It wasn't like this before and now it is like a lighter theme than before. Quite annoying as a developer myself that color schemes like this changed without me being able to change it back or have a custom theme. Should this not have been a new theme users can use rather than changing the overall default? 

On my other laptop at home I have older version so I can get an image of what it used to look like for frame of reference. Thanks!

**Comment by AustinGitHub** [comment]
<img width="1350" alt="Screenshot 2023-09-18 at 6 22 36 PM" src="https://github.com/brave/brave-browser/assets/10100397/2034a7f9-c72d-4591-912c-5e75ad08d12b">

This was old display

**Comment by AustinGitHub** [comment]
See how the tab headers are darker in older version than newer one?

**Comment by wsor4035** [comment]
im assume brave is using the same chromium commit chrome is https://developer.chrome.com/blog/new-in-devtools-117/?utm_source=devtools#colors

**Comment by AustinGitHub** [comment]
> i assume brave is using the same chromium commit chrome is https://developer.chrome.com/blog/new-in-devtools-117/#colors

ughhhh, ok. Then I hope Brave can correct this action by bringing back the old stylings 💀

**Comment by wsor4035** [comment]
> > i assume brave is using the same chromium commit chrome is https://developer.chrome.com/blog/new-in-devtools-117/#colors
> 
> ughhhh, ok. Then I hope Brave can correct this action by bringing back the old stylings 💀 Chrome literally has no reason to change those colors but to annoy developers unfortunately

🤷 i dont mind it.

as an aside, i think it would be cool to have (predefined and custom) themes like edge does https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/customize/theme

**Comment by AustinGitHub** [comment]
Thanks, I will check it out and close this
