### ISSUE TITLE
Safe Sign support for CoW 🐮 orders

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#33093]
Parse EIP-712 messages corresponding to CoW swap and limit orders, and render them in the Safe Sign UI, previously designed for 0x swaps.

**Example swap:** https://swap.cow.fi/#/100/swap/WXDAI

<img width="240" src="https://github.com/brave/brave-browser/assets/3684187/85b94f6c-ad51-419f-94c0-2a6bc8d49002">

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.60.104 Chromium: 118.0.5993.117 (Official Build) (64-bit)
-- | --
Revision | 5dfa047eac682ad367174af6503fc21b59db5977
OS | Windows 11 Version 22H2 (Build 22621.2428)

- Verified steps from [brave/brave-core#20203](https://github.com/brave/brave-core/pull/20203)
- Verified able to place order on `https://swap.cow.fi`
- Verified able to place order with a custom recipient on `https://swap.cow.fi`
- Verified able to view order details by clicking on the `Details` button in the confirmation screen
- Verified able to place Swap order on native tokens on `https://swap.cow.fi`
- Verified able to place Swap order on unknown tokens via 0x Swap

**Case A: CoW Swap trade**

Raw | Details
-- | --
![brave_n3ehi3E6Bw](https://github.com/brave/brave-browser/assets/17010094/1c4d1c9c-a3d0-4222-bf65-39e3d9643ad1) | ![brave_pNoXAiuhCM](https://github.com/brave/brave-browser/assets/17010094/112eeb07-ff58-4dcd-b035-133387a9e7d1)

 **Case B: CoW Swap trade with custom recipient**

Raw | Details
-- | --
![brave_IcKitSiteR](https://github.com/brave/brave-browser/assets/17010094/c3ef7ebd-6db1-4ad4-84f4-4ffbcf6d6eae) | ![brave_OvvUIQqOeu](https://github.com/brave/brave-browser/assets/17010094/4b06e48c-50c1-45b6-ab78-b7ae5adba7e4)

**Case C: CoW swap trade selling native asset (ETH on Ethereum)**
![brave_buaTl6oUq9](https://github.com/brave/brave-browser/assets/17010094/75ce843b-975e-41b1-8af2-e7e06d28260a)

**Case D: 0x Swap involving unknown tokens**
![brave_kDgZkIYRz4](https://github.com/brave/brave-browser/assets/17010094/e7f4a231-a503-46ce-ab7c-f2b515427dbe)
