### ISSUE TITLE
[Android] Remove redirection to brave://adblock

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#33091]
This issue is to remove an option to redirect users to new native option for filter list as we still need to work on https://github.com/brave/brave-browser/issues/33015. 

So after this change, by default whenever users type `brave://adblock`, they would still have access to the web page with creating new custom filter similar to desktop. 

We need to uplift the changes to 1.59 as https://github.com/brave/brave-browser/issues/32350 is already a part of 1.59

**Comment by kjozwiak** [comment]
The above requires `1.59.100` or higher for `1.59.x` verification 👍
