### ISSUE TITLE
`Performance` menu item entry has a `New` icon beside it

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#33105]
## Description 

`Performance` menu item entry has a `New` icon beside it (we recently removed the one beside `Password Manager`)

Found while testing https://github.com/brave/brave-browser/issues/32089

## Steps to Reproduce

1. install `1.60.34`
2. launch Brave
3. click on the application/"hamburger" menu
4. hover over `More tools`
5. look at the flyout menu-item

## Actual result:

The `Performance` entry still has Chrome's `New` icon beside it

<img width="1312" alt="Screen Shot 2023-09-18 at 3 40 46 PM" src="https://github.com/brave/brave-browser/assets/387249/dcd59a80-ab0d-45ab-9edc-62cb067d235c">

## Expected result:

No `New` icon beside the `Performance` menu-item entry

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave | 1.60.34 Chromium: 117.0.5938.88 (Official Build) nightly (x86_64)
-- | --
Revision | 780ad58fcc8bc6a420bb0b5502669ccef653a907
OS | macOS Version 11.7.10 (Build 20G1427)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Miscellaneous Information:

cc @aguscruiz @rebron @fallaciousreasoning @brave/qa-team

**Comment by kjozwiak** [comment]
The above requires `1.59.102` or higher for `1.59.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.59.102 Chromium: 117.0.5938.140 (Official Build) beta (x86_64)
-- | --
Revision | 11284b6d5d51252fe1a6fb6b5cba35ef98982357
OS | macOS Version 14.1 (Build 23B5046f)
```

Followed my original steps to reproduce.

### Confirmed there's no longer a `New` icon beside `Performance`

`Dark` | `Light`
-------|--------
<img width="1789" alt="Screenshot 2023-09-28 at 03 05 22" src="https://github.com/brave/brave-browser/assets/387249/9988b138-9d24-4804-80ea-ee3a5bdc4f29"> | <img width="1789" alt="Screenshot 2023-09-28 at 03 05 39" src="https://github.com/brave/brave-browser/assets/387249/926af491-10d4-4789-9ba6-f49d9462dbc4">
