### ISSUE TITLE
`No tabs from other devices` app-menu item should have an icon

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#33104]
## Description 

`No tabs from other devices` app-menu item should have an icon

Found while testing https://github.com/brave/brave-browser/issues/32089

## Steps to Reproduce

1. install `1.60.34`
2. launch Brave
3. click on the "hamburger"/top-level application menu
4. choose `History`
5. examine the flyout menu item for `No tabs from other devices`

### It's missing its icon

example 1 | example 2
----------|-----------
<img width="1312" alt="Screen Shot 2023-09-18 at 3 09 41 PM" src="https://github.com/brave/brave-browser/assets/387249/b50ec48a-76a8-4abf-8cd4-b75ae20a09b3"> | <img width="1312" alt="Screen Shot 2023-09-18 at 3 20 29 PM" src="https://github.com/brave/brave-browser/assets/387249/1a8f6e58-932e-435c-ac47-ad987f5f5409">

### Per Figma, it should have an icon, even when empty:

<img width="332" alt="Screen Shot 2023-09-18 at 3 13 42 PM" src="https://github.com/brave/brave-browser/assets/387249/06e431a9-6a3e-480d-baf7-80d8f1a51156">

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave | 1.60.34 Chromium: 117.0.5938.88 (Official Build) nightly (x86_64)
-- | --
Revision | 780ad58fcc8bc6a420bb0b5502669ccef653a907
OS | macOS Version 11.7.10 (Build 20G1427)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @aguscruiz @rebron @fallaciousreasoning @brave/qa-team

**Comment by kjozwiak** [comment]
The above requires `1.59.102` or higher for `1.59.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.59.102 Chromium: 117.0.5938.140 (Official Build) beta (x86_64)
-- | --
Revision | 11284b6d5d51252fe1a6fb6b5cba35ef98982357
OS | macOS Version 14.1 (Build 23B5046f)
```

### Followed my original steps to reproduce

### Confirmed appropriate Figma-matching icon in both `Light` and `Dark` modes


_`Light`_ mode |  _`Dark`_ mode
----------------|-----------------
<img width="695" alt="Screenshot 2023-09-28 at 03 20 32" src="https://github.com/brave/brave-browser/assets/387249/ffb6658e-0a51-4c6f-8aad-c44a6e02ba0b"> | <img width="713" alt="Screenshot 2023-09-28 at 03 22 37" src="https://github.com/brave/brave-browser/assets/387249/0cae53bd-7ca0-4010-99f9-95bee63515ea">
