### ISSUE TITLE
`New Tor connection for this site` menu item is missing its icon

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#33100]
## Description 

`New Tor connection for this site` menu item is missing its icon

Found while testing https://github.com/brave/brave-browser/issues/32089

## Steps to Reproduce

1. install `1.60.34`
2. launch Brave
3. open a `New Private Window with Tor`
4. click on the application/"hamburger" menu icon
5. look at the entry for `New Tor connection for a site`

## Actual result:

It's missing its icon

<img width="967" alt="Screen Shot 2023-09-18 at 2 06 54 PM" src="https://github.com/brave/brave-browser/assets/387249/7c417baf-7164-4c8d-9dc6-8f47ef00332e">

## Expected result:

It should probably have an icon

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave | 1.60.34 Chromium: 117.0.5938.88 (Official Build) nightly (x86_64)
-- | --
Revision | 780ad58fcc8bc6a420bb0b5502669ccef653a907
OS | macOS Version 11.7.10 (Build 20G1427)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @fallaciousreasoning @rebron @brave/qa-team

**Comment by kjozwiak** [comment]
The above requires `1.59.102` or higher for `1.59.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.59.102 Chromium: 117.0.5938.140 (Official Build) beta (x86_64)
-- | --
Revision | 11284b6d5d51252fe1a6fb6b5cba35ef98982357
OS | macOS Version 14.1 (Build 23B5046f)
```

#### Followed my original steps to reproduce

### Confirmed appropriate icon present now for `New Tor connection for this site`

example | example
---------|---------
<img width="354" alt="Screenshot 2023-09-28 at 03 16 32" src="https://github.com/brave/brave-browser/assets/387249/99656e97-c258-4645-afe7-a59d3fe91ccd"> | <img width="1674" alt="Screenshot 2023-09-28 at 03 13 54" src="https://github.com/brave/brave-browser/assets/387249/166a7411-1c0e-4f81-900a-dd2462144802">
