### ISSUE TITLE
Use intersection observer to load only visible NFT images

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#33114]

**Comment by kjozwiak** [comment]
Changing to `QA/Yes` as we have a test plan video via https://github.com/brave/brave-core/pull/20213#issue-1902566980. Should at least double check that NFT images are still loading without any issues/failures.

**Comment by kjozwiak** [comment]
The above requires `1.59.104` or higher for `1.59.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.59.111 Chromium: 118.0.5993.21 (Official Build) (64-bit)
-- | --
Revision | 73a6c272e4eec308fc7e9badfca4b49bdf068c59
OS | Windows 11 Version 22H2 (Build 22621.2283)

- Verified steps from [brave/brave-core#20213](https://github.com/brave/brave-core/pull/20213)
- Verified NFT work as expected onboth NFT tab and inpanel
