### ISSUE TITLE
[Android] Payout complete banner is shown forever on the BR Panel in a connected state

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#33119]
## Description 
Found while testing https://github.com/brave/brave-browser/issues/28258
Payout complete banner is shown forever on the BR Panel in a connected state

## Steps to reproduce 

   1. Clean profile 1.59.x
   2. Enable rewards and connect a custodian
   3. Open BR panel
   4. Payout complete banner is shown forever on the BR Panel in a connected state

## Actual result 

Payout complete banner is shown forever on the BR Panel in a connected state
![Screenshot_20230919_190348](https://github.com/brave/brave-browser/assets/38657976/3b3879b6-76f8-4145-8135-0229ff5949ad)

## Expected result
Payout complete banner should not be shown

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version?Not sure

## Device details
   - Install type (ARM, x86): All
   - Device type (Phone, Tablet, Phablet):All
   - Android version:12
   
## Brave version
1.59.86

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/qa-team @Miyayes @deeppandya @sujitacharya2005

**Comment by GeetaSarvadnya** [comment]
This issue is not reproducible on Desktop

**Comment by GeetaSarvadnya** [comment]
The issue was introduced while implementing https://github.com/brave/brave-browser/issues/28052

**Comment by kjozwiak** [comment]
The above requires `1.59.111` or higher for `1.59.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.59.112`

- Verified the STR from the https://github.com/brave/brave-browser/issues/33119#issue-1903032284
- Confirmed that the Payout complete banner is NOT shown forever on the BR Panel in a connected state

Example | Example
----------|----------
![Screenshot_20231005_165941](https://github.com/brave/brave-browser/assets/38657976/256e39e4-2bc4-4451-8641-a303312a68eb) | ![Screenshot_20231005_165949](https://github.com/brave/brave-browser/assets/38657976/ad651c29-d238-4180-b75f-06e31c216e06)
