### ISSUE TITLE
Deprecate uncached name service lookups (ENS, SNS, UD)

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#33117]
## Description 

We should cache results from name service address lookups to prevent refetching previous results

## Steps to Reproduce

   1. Go to "Send" screen in wallet
   2. select ETH
   3. enter "vitalik.eth" as the "to" address
   4. edit the text to something else
   5. change the text back to "vitalik.eth"

## Actual result:

address is refetched

## Expected result:
address should appear without needing to fetch again (shouldn't see loading spinner)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.61.61 Chromium: 119.0.6045.105 (Official Build) beta (64-bit)
-- | --
Revision | 6bbedb0b809f83b08334ffa36b1ea9df92e86245
OS | Windows 11 Version 22H2 (Build 22621.2506)

- Verified steps from [brave/brave-core#20219](https://github.com/brave/brave-core/pull/20219)
- Verified ENS/SNS/UD domains address are cached and not re-fetched every time

https://github.com/brave/brave-browser/assets/17010094/341b1dc4-534e-4184-ac64-aecdac8976b4
