### ISSUE TITLE
Update brave://settings/appearance with section titles and better grouping

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#33128]
## Description 

Update brave://settings/appearance page with sub-titles and grouping.
This will bring the Brave Wallet button show/hide to the appearance page from web3 section.
Add section titles for Address bar, Tabs, Sidebar, and Content.
Figma link: `https://www.figma.com/file/IXNCYwXmMWaF6u7Pdv1pOW/Desktop-settings---Leo?type=design&node-id=1-17&mode=design&t=k9wGm2Ix9QSrfSZB-0` 

## Design:

<img width="538" alt="Screenshot 2023-09-19 at 5 07 38 PM" src="https://github.com/brave/brave-browser/assets/5951041/8de5c237-3eda-466d-868c-c7bbd22178f9">

## Reproduces how often: 

Easily.

## Brave version (brave://version info)

Target 1.60.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

Related pr: https://github.com/brave/brave-core/pull/20160

**Comment by simonhong** [comment]
Working on this.

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.60.95 Chromium: 118.0.5993.88 (Official Build) beta (64-bit)
-- | --
Revision | d65c9c374e175c06c50025db46cf953fd200e9cc
OS | Windows 10 Version 22H2 (Build 19045.3570)

```

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.60.106 Chromium: 119.0.6045.59 (Official Build) (x86_64)
-- | --
Revision | 16064193dde8c55f64dabd32f125c0cd9380f96a
OS | macOS Version 14.2 (Build 23C5030f)
```

**Comment by btlechowski** [comment]
Verified with

Brave | 1.60.110 Chromium: 119.0.6045.105 (Official Build) (64-bit)
-- | --
Revision | 0bb6e7a81aed340b5a9e8b752c1cf92768257c40
OS | Linux



Basically using the information & screenshots examples from https://github.com/brave/brave-core/pull/20409#issue-1927313539, ensured the following:

* ensured that the new `brave://settings/appearance` grouping matches the examples from https://github.com/brave/brave-core/pull/20409#issue-1927313539 & https://www.figma.com/file/IXNCYwXmMWaF6u7Pdv1pOW/Desktop-settings---Nala?type=design&node-id=1-17&mode=design&t=y5GTL3Vs121di4m5-0
  * the title should be `Toolbar` and not `Address Bar` (Figma and some other screenshots are showing `Address Bar`)
* went through most of the settings via `brave://settings/appearance` and ensured that everything is working
  * ensured there was no obvious crashes/visual issues when enabling/disabling various features
* ensured that https://github.com/brave/brave-browser/issues/30100 was fixed/address via `Vertical Tabs` grouping
* ensured that `Leo` is now underneath `Web3`
* ensured that the correct logo/branding is being used under `brave://settings`
  * bottom `About Brave` logo that points to `brave://settings/help`
* ensured that the redundant `Settings` text is removed from navigation menu on the left via `brave://settings` 
* ensured that `Always show toolbar in fullscreen` is NOT displayed on Windows, it shows only on `macOS` via the `Toolbar` grouping

### `Vertical Tabs` using `Light` theme

**`Example`** | **`Example`**
----------------|----------------
![image](https://github.com/brave/brave-browser/assets/34715963/161a5a1f-2349-4256-9fc9-c54f2c7c18d8)|![image](https://github.com/brave/brave-browser/assets/34715963/ad4d53ee-be58-4487-ac22-6f11d0415b41)




### `Vertical Tabs` using `Dark` theme

![image](https://github.com/brave/brave-browser/assets/34715963/6343b687-985f-4c63-9aa7-dc2106c232a7)|![image](https://github.com/brave/brave-browser/assets/34715963/714d4b1c-7c3d-4ff1-b9c8-d58675daf8f3)
--|--

### `Horizontal Tabs` using `Light` theme

**`Example`** | **`Example`**
----------------|----------------
![image](https://github.com/brave/brave-browser/assets/34715963/c70af08c-0e83-4c1f-ae7d-441fa7f606fa)|![image](https://github.com/brave/brave-browser/assets/34715963/9b172a63-d65f-4a7f-84a1-003faf2083a4)



### `Horizontal Tabs` using `Dark` theme

**`Example`** | **`Example`**
----------------|----------------
![image](https://github.com/brave/brave-browser/assets/34715963/2faa4b2e-8ee4-4c5b-8937-de45d96757ec)|![image](https://github.com/brave/brave-browser/assets/34715963/7d7c9d24-7e7f-4486-a3bf-e96bf2739b23)


### `Leo` position (below `Web3`)

**`Example`** | **`Example`**
----------------|----------------
![image](https://github.com/brave/brave-browser/assets/34715963/57d67ca5-65ac-4de2-af88-66ea77c01b16)


### Removing `Setting` text from navigation via `brave://settings`

![image](https://github.com/brave/brave-browser/assets/34715963/ae940216-a6c8-4c16-aeed-248131524c5a)|![image](https://github.com/brave/brave-browser/assets/34715963/34301b3f-22cd-49a7-8878-2141583e2489)
