### ISSUE TITLE
Verified publisher status is inconsistent in tipping panel between YouTube channel page and on a video page

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#3312]
**Description:** Tipping panel says YouTube channel is unverified on channel page, but says verified on a specific video page. See screenshots below. 

**Version:** 0.59.35

**Platform I reproduced on:** MacOS. 

This has also been reproduced by many other users, as I've seen it during many times the course of providing Brave support to users. 

**Expected:** Verified status should be consistent in the tipping panel regardless of whether you are on the channel page or an individual video. 

**Extra notes:** I was afflicted by the "contribution date in the past" issue, and am currently afflicted with the "says insufficient balance even though there is enough balance" issue.

_Screenshots:_

_On YouTube channel page:_
<img width="365" alt="screen shot 2019-02-10 at 12 17 20 pm" src="https://user-images.githubusercontent.com/11497541/52578943-91da7380-2e68-11e9-8ba1-32345a87e516.png">

_On an individual video by this channel:_
<img width="420" alt="screen shot 2019-02-10 at 12 18 21 pm" src="https://user-images.githubusercontent.com/11497541/52578952-94d56400-2e68-11e9-834b-5e9c9632196a.png">

**Comment by NejcZdovc** [comment]
@Miyayes which url's are this?

**Comment by Miyayes** [comment]
> @Miyayes which url's are this?

Channel page: https://www.youtube.com/channel/UCRkcacarvLbUfygxUVg7mhQ?view_as=subscriber

Video page: https://www.youtube.com/watch?v=u7VXJtS9k_0

Still reproducing exactly for me.

**Comment by NejcZdovc** [comment]
@Miyayes I see the problem. Problem is with this addition to the url `?view_as=subscriber`. Will check it out

**Comment by Miyayes** [comment]
+1 from community. You can see `view_as=subscriber` in the URL: https://community.brave.com/t/verified-channel-not-showing-as-verified-in-browser/44763/4?u=chriscat

**Comment by NejcZdovc** [comment]
@Miyayes yup will be working on it today

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.61.37 Chromium: 73.0.3683.39 (Official Build) beta (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

Used test plan from https://github.com/brave/brave-core/pull/1699
