### ISSUE TITLE
Hide vertical tabs in browser fullscreen and support revealing by mouse hover

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#33136]
Sub task of https://github.com/brave/brave-browser/issues/2635 and https://github.com/brave/brave-browser/issues/33020

We were showing vertical tabs on browser fullscreen. But we've got mixed response about the visibility. Some want it to be visible on the browser fullscreen mode, while others want the opposite.

So we're going to hide vertical tabs by default but support revealing it by mouse hovering. And especially on Mac, there's a pref named "Always show toolbar in fullscreen". Vertical tab strip will be applied that pref too so that users can decide the default visibility.

#### Common
* Enable browser fullscreen via F11 or app menu -> fullscreen (square icon)
* Vertical tab should be hidden
* When moving mouse over the edge where the vertical tab should be, vertical tab should show up  in few seconds.

#### On Mac OS
* From the OS's app menu on top of screen, toggle on `View -> Always show toolbar in fullscreen`
* Enable browser fullscreen
* Vertical tab should be visible just like toolbar.
* turning off the option should make vertical tab works as described from `Common`

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.60.85 Chromium: 118.0.5993.54 (Official Build) beta (64-bit)
-- | --
Revision | 9f9613953350c4efd0170fe90031c1df4ea5aae3
OS | Windows 10 Version 22H2 (Build 19045.3570)

```

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.60.89 Chromium: 118.0.5993.70 (Official Build) beta (x86_64)
-- | --
Revision | 801f851e0c0664d110cccd46708cd084a83c3729
OS | macOS Version 11.7.10 (Build 20G1427)
```

**Comment by btlechowski** [comment]
Verified with

Brave | 1.60.102 Chromium: 118.0.5993.96 (Official Build) beta (64-bit)
-- | --
Revision | 3598a9fc6b7752181feb25caa131bc386d6d054c
OS | Linux


**Steps:**

1. Enable browser fullscreen via F11 or app menu -> fullscreen (square icon)
2. Vertical tab should be hidden
3. When moving mouse over the edge where the vertical tab should be, vertical tab should show up in few seconds.

![image](https://github.com/brave/brave-browser/assets/34715963/ea2e8b22-c90d-4979-bf37-6a8797a9fc9d)|![image](https://github.com/brave/brave-browser/assets/34715963/19877c9b-d6b3-4ff5-8897-7ccd7ba97b2e)
--|--
