### ISSUE TITLE
Unable to stream from Xfinity on Windows machines

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#3314]
## Description 

When trying to stream content through an Xfinity account (https://xfinity.com/stream), Xfinity shows "Sorry, we're having some trouble" error (see images below).
This is true for Windows systems but MacOS streams Xfinity without issue.

## Steps to Reproduce

   1. Ensure that Widevine plugin is installed
   2. Visit xfinity.com/stream and login to your account
   3. Enable flash for the site (required)

## Actual result:

Error is thrown and streaming is not initiated:
![image](https://user-images.githubusercontent.com/3299098/52593484-ec8ab580-2dfd-11e9-91ef-197f4538244c.png)

## Expected result:
Authenticate into Xfinity.com/stream and stream video content.

## Reproduces how often: 

Always

## Brave version (brave://version info)

Tested on
**Developer Build** - `v0.61.20`
**Beta Build** - `v0.60.23`
**Release Channel** - `v0.59.35`

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? No

### Additional Information

Console view and user reports:
![image](https://user-images.githubusercontent.com/3299098/52593646-4db28900-2dfe-11e9-931e-f71e0d25d493.png)
https://www.reddit.com/r/brave_browser/comments/anewog/cannot_get_xfinity_stream_to_work_in_brave/eftmhmj/

**Comment by Samdvich** [comment]
I've seen this issue around with other services using Caddy. 

- https://caddyserver.com

**Comment by SevilleCode** [comment]
Got an interesting result when I tried to stream Xfinity in Brave Nightly (0.68.48). First I received a message that there was a problem authenticating my account, and it needed me to sign out and sign back in. When I signed back in, however, I was back to the "Sorry, we're having some trouble" message.

**Comment by rebron** [comment]
cc: @simonhong

**Comment by Brave-Matt** [comment]
Lots of discussion happening on Reddit -- 35+ comments
https://www.reddit.com/r/brave_browser/comments/anewog/cannot_get_xfinity_stream_to_work_in_brave/

**Comment by indyodie** [comment]
Same issue here: Version 0.68.132 Chromium: 76.0.3809.132 (Official Build) (64-bit)

**Comment by Brave-Matt** [comment]
Several users on Community reporting this (again):
https://community.brave.com/t/problem-with-flash-player-loading-running/78862/4

**Comment by Brave-Matt** [comment]
+1 from Community:
https://community.brave.com/t/flash-player-will-not-load-on-comcast-xfinity-tv-streaming-xfinity-com-stream/83172/4

**Comment by WiCarr** [comment]
Not really familiar with Brave - but saw this thread and have been looking at some similar issues - so just a couple things to check out:

Does Brave use Chromium's PPAPI integration of Flash? If so Flash DRM relies on the RLZ buildflag being enabled or otherwise unblocking the GetMachineIDAsync call in device_id_fetcher.cc (https://cs.chromium.org/chromium/src/chrome/browser/renderer_host/pepper/device_id_fetcher.cc?l=46) in order to perform the DRM individualization step.

There was also a regression in Chromium where the origin header for a CORS call was set to null that broke xfinity.com/stream scenarios if the "Out of Blink CORS" experiment was enabled (the default state): https://bugs.chromium.org/p/chromium/issues/detail?id=994461&can=1&q=xfinity&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

**Comment by Brave-Matt** [comment]
+1 from community:
https://community.brave.com/t/problems-with-video-streaming-services-websites-while-using-brave/86664/7

**Comment by murphyd** [comment]
+1 -- Received input from the community that stated he could not stream from Xfinity.com. He turned on Flash.

Tried this myself -- turned on Flash in Brave 1.0 and went to Xfinity.com/stream and it continues to say "Let’s get your Adobe Flash Player up and running." but doesn't prompt for the install.

**Comment by dodossssssssss** [comment]
+1 -- just encountered this issue today, constantly being prompted to install flash with flash already allowed (On flash test sites it is not noticing flash being allowed either even when I allow it. Maybe its a pepper flash issue?). I did notice that I can still stream tv on other sites (such as espn.com and foxsports.com/live) with my xfinity account, the xfinity.com/stream app is the only site with the issue.

I was also never prompted for widevine on netflix or hulu (I installed brave a few days ago now).

Version 1.0.0 Chromium: 78.0.3904.97 (Official Build) (64-bit)

**Comment by bsclifton** [comment]
@Brave-Matt @hollons have you all seen reports of this recently?

**Comment by hollons** [comment]
@bsclifton it's not something that I've seen reported recently. Will keep a close eye out.

**Comment by bsclifton** [comment]
OK I'll close this out - we can re-open if we see it again 😄 Thanks @hollons
