### ISSUE TITLE
Re-enable VariationsSeedFetcher to fetch Griffin seed on first run on Android

### ISSUE THREAD

**Issue by goodov** [brave/brave-browser#33141]
We disabled upstream `VariationsSeedFetcher` in https://github.com/brave/brave-browser/issues/21187

Instead we should enable it, but point to our server. ~~There's one catch though: our server requires `BraveServicesKey` header to be set, but this value is not available in Java codebase as far as I can see, so we need to store it somewhere (in resources?). We cannot request it via JNI, because native part is not loaded yet at this point.~~

We will remove `BraveServicesKey` requirement from Griffin seed endpoint. This task should just re-enable upstream fetcher and change URL.

**Comment by goodov** [comment]
Test case:

1. Cleanup all data related to Brave browser on Android device
2. Install and run browser, make sure this is a "first run" of the browser.
3. Open `brave://version`
4. Expect "Active variations" list is filled with some data.

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 [panther_beta-user 14 U1B2.230922.010 release-keys]
Brave build: 1.60.96 
Chromium: 118.0.5993.88 (Official Build) beta (64-bit) 
Revision: b4c059ad1d32d6e0cd1466123f03ccb97b3cf858
```
---------------------------

**STEPS:**
1. Followed the steps from https://github.com/brave/brave-browser/issues/33141#issuecomment-1731393417

**ACTUAL RESULTS:**
- Verified that the `Active variations` list is filled with some data on the first Brave launch.

---------------------------

|1|
|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/8c80372f-7da7-4760-a501-0833853c293f) |

https://github.com/brave/brave-browser/assets/128532965/dd8885d0-f1cd-4fc3-8e8c-91817d00ed8d
