### ISSUE TITLE
text mistake on torrent page - follow up to 3034

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#3315]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/3034

In the 'Privacy Warning' on the torrent page, it looks like it should say 'begin' instead of 'beging'. cc @rossmoody for confirmation.

## Steps to Reproduce

   1. Visit https://webtorrent.io/free-torrents
   2. Open one of the demo URLs (the torrent link)
   3. `Start torrenting` page shows
   4. Read Privacy Warning

## Actual result:
![screen shot 2019-02-11 at 4 55 16 pm](https://user-images.githubusercontent.com/28145373/52596543-8b270e80-2e1e-11e9-866e-c0b9b3657820.png)

## Expected result:
Probably should be begin instead of beging.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.60.23 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.61.37 Chromium: 73.0.3683.39 (Official Build) beta (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

![image](https://user-images.githubusercontent.com/34715963/53379078-64152480-3968-11e9-9954-7e318275b658.png)
