### ISSUE TITLE
Add the feature to send tabs from synced mobile app to desktop.

### ISSUE THREAD

**Issue by Luis-gd** [brave/brave-browser#33159]
## Description 
The idea is to implement a functionality similar to the one that exists on brave desktop but with brave mobile. 

In the picture below we can see that there is an option that says: "Enviar a tus dispositivos", in English is something like: "send to your devices". 
![image](https://github.com/brave/brave-browser/assets/56192640/18b62350-fbd9-47fc-a4d6-2a6698910c63)

The idea is to get this function in the phone version to make it easier to share tabs between devices. I don't know if this functionality is being implemented, but if not, it would be great idea.

**Comment by Luis-gd** [comment]
I can't see that option on phone 
![Uploading Screenshot_2023-10-05-19-40-02-207_android.jpg…]()

**Comment by Luis-gd** [comment]
![Screenshot_2023-10-05-19-39-35-175_com brave browser](https://github.com/brave/brave-browser/assets/56192640/e0f2203b-31b9-4367-87e0-f99db539e1cf)

**Comment by Coffeeling** [comment]
It's the three connected dots at the bottom of the menu.

**Comment by Luis-gd** [comment]
Excuse me, I forgot the second screen shot.
![Uploading Screenshot_2023-10-05-22-36-41-312_android.jpg…]()

**Comment by Luis-gd** [comment]
![Uploading Screenshot_2023-10-05-22-36-41-312_android.jpg…]()

**Comment by Luis-gd** [comment]
![Screenshot_2023-10-05-22-36-41-312_android](https://github.com/brave/brave-browser/assets/56192640/87d0fafa-c750-4aec-b12d-933a9464d727)

**Comment by Luis-gd** [comment]
@Coffeeling
