### ISSUE TITLE
[Android] Remove cookie consent modal

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#33151]
With this issue, we need to remove cookie consent modal and all logic from the code. 

**Test Plan**
Plan 1 : 
1. fresh install
2. go to settings - > `Brave Shields & privacy` 
3. `Block cookie consent notices` option should be enabled by default. 

Plan 2 : 
1. upgrade an app version
2. `Block cookie consent notices` option should respect the change from previous version

Plan 3 :
1. Verify with `https://www.cookieyes.com/blog/gdpr-cookie-consent-banner-examples/` if it respects the option `Block cookie consent notices`

**Comment by kjozwiak** [comment]
The above requires `1.59.100` or higher for `1.59.x` verification 👍
