### ISSUE TITLE
Still Encountering Error: Device limit reached

### ISSUE THREAD

**Issue by Thaler-AB** [brave/brave-browser#33169]
## Description 
While I've read in previous posts that there used to be device limits for Uphold account linking, I still receive this error when attempting to use Brave to link to Uphold.

## Steps to Reproduce
I had to reformat my computer. Afterwards, I encounter this error every time I attempt to link Brave Rewards to my Uphold account.

## Expected result:
I expected that my Uphold account would link - especially now with device limits having been removed from Brave.

## Reproduces how often: 
Every time I attempt to link Brave Rewards to my Uphold account.

## Desktop Brave version:
Brave | 1.58.129 Chromium: 117.0.5938.88 (Official Build) (64-bit)
Revision | 0ab74dc5473bd9dcd0a85653872988a5655aff6b
OS | Windows 11 Version 22H2 (Build 22621.2283)

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:
I've only tried to produce this problem using the current release of Brave browser.

**Comment by Miyayes** [comment]
You can file a support ticket here: https://support.brave.com/hc/en-us/requests/new. Thanks!
