### ISSUE TITLE
Enable search promotion from omnibox

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#33160]
Enable search promotion from omnibox via griffin.

Related issue - https://github.com/brave/brave-browser/issues/31746

**Comment by kjozwiak** [comment]
Closing as https://github.com/brave/brave-variations/pull/747 was merged into `production`.

**Comment by LaurenWags** [comment]
Per discussion with @kjozwiak this has already been verified via 1.58.x with https://github.com/brave/brave-browser/issues/31746 (on all platforms), so labeling as `QA/No`. 

@rebron does this need to be enabled on Beta or is this just going to remain on Nightly for now?
