### ISSUE TITLE
remove webtorrent resources from web_accessible_resources

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#33163]
cf https://hackerone.com/reports/2174793

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.61.61 Chromium: 119.0.6045.105 (Official Build) beta (64-bit)
-- | --
Revision | 6bbedb0b809f83b08334ffa36b1ea9df92e86245
OS | Windows 11 Version 22H2 (Build 22621.2428)
```

1. Installed 1.61.61
2. launched Brave
3. opened https://webtorrent.io/free-torrents in a new tab
4. clicked `torrent` link
5. clicked `magnet` link
6. confirmed `webtorrent` pages opened
7. opened https://j5q9w7.csb.app/ (my fake phising site)
8. clicked the "Check for viruses" link 
9. confirmed blocked page is displayed 
10. clicked the "Check for viruses (direct)" link
11. confirmed 404 page on microsoft.com is displayed


step 3 | step 6a | step 6b | step 7 | step 9 | step 11
----- | ----- | ---- | ----- | ----- | ------
![image](https://github.com/brave/brave-browser/assets/98358127/a3b9fc39-9721-4a6e-93cb-c06cace1faf5)|![image](https://github.com/brave/brave-browser/assets/98358127/35b5a9e7-50a4-42ef-aabd-ce8fe35b294a)|![image](https://github.com/brave/brave-browser/assets/98358127/f1ca98e6-7755-4b5b-947c-ad8964ca9b9c)|![image](https://github.com/brave/brave-browser/assets/98358127/10792a9b-ac8e-4ffb-86b4-bbd813219b9d)|![image](https://github.com/brave/brave-browser/assets/98358127/52cf4089-542e-45fa-9ba9-e8fc73966960)|![image](https://github.com/brave/brave-browser/assets/98358127/8d883f22-795c-42f3-8ab8-4767767a4121)

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.61.66 Chromium: 119.0.6045.105 (Official Build) beta (x86_64)
-- | --
Revision | aaaecfc0d925cde58e40e1b689464f1c630ef96d
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.61.66`
2. launched Brave
3. opened `https://webtorrent.io/free-torrents` in a new tab
4. clicked torrent link
5. clicked magnet link
6. confirmed torrent and magnet pages opened
7. opened https://j5q9w7.csb.app/ (fake phishing site)
8. clicked the "Check for viruses" link
9. confirmed blocked page is displayed
10. clicked the `Check for viruses (direct)` link
11. confirmed 404 page on `microsoft.com` is displayed

`step 3` | `step 6a` | `step 6b` | `step 7` | `step 9` | `step 11`
---------|-----------|-----------|---------|---------|----------

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.61.76 Chromium: 119.0.6045.134 (Official Build) beta (64-bit) 
Revision	4d380733de55473426f2b32bf51f7124711b7a9e
OS	Linux
```
