### ISSUE TITLE
add ads-serve.bravesoftware.com to network audit whitelist

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#3317]
getting

```
NETWORK AUDIT FAIL: https://ads-serve.bravesoftware.com/v1/catalog
NETWORK AUDIT FAIL: https://ads-serve.bravesoftware.com/v1/catalog
NETWORK AUDIT FAIL: https://ads-serve.bravesoftware.com/v1/catalog
NETWORK AUDIT FAIL: https://ads-serve.bravesoftware.com/v1/catalog
```

when enabling rewards and running brave using `npm run network-audit`

@amirsaber is there any particular reason we are using bravesoftware.com instead of brave.com?

**Comment by amirsaber** [comment]
@diracdeltas no specific reason on our side, Devops provisioned the `staging` server on that domain. Production is on `brave.com`
