### ISSUE TITLE
Remove Unicorn Media Connected TV trackers from the query string

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#33172]
Unicorn was apparently a marketing platform for [connected TVs](https://www.prnewswire.com/news-releases/blue-wave-media-chooses-unicorn-media-to-monetize-and-deliver-mobile-and-connected-tv-content-146256845.html) that Adjust integrates with: https://help.adjust.com/en/article/set-up-connected-tv-campaigns-on-unicorn-classic

It looks like the purpose of the `unicorn_click_id` query parameter is to track individual TVs.

e.g. The following [URL](https://github.com/AdguardTeam/AdguardFilters/commit/920d973db052ded91b48fbb8c7ca3fe2fdeda237):
https://app.adjust.com/9ovnvzz?campaign=9056-%E3%83%9E%E3%82%AC%E3%82%B8%E3%83%B3%E3%83%9D%E3%82%B1%E3%83%83%E3%83%88%EF%BC%88%E3%82%B6%E3%83%BB%E3%83%95%E3%82%A1%E3%83%96%E3%83%AB%EF%BC%89_Android&adgroup=16105-%E3%80%90%E6%96%B0%E8%A6%8F%E7%8D%B2%E5%BE%97_%E3%82%B6%E3%83%BB%E3%83%95%E3%82%A1%E3%83%96%E3%83%AB%E3%80%912021%2F06%2F11%200%3A00%EF%BD%9E2022%2F01%2F07%20%E3%81%BE%E3%81%A7&creative=hl0liV8D-044543_0800x0800_211126181630.jpg&idfa=&gps_adid=&unicorn_click_id=c712d2d3-9333-4644-a77f-c53af4653b85
redirects to the Play Store after consuming the `unicorn_click_id` parameter:
https://play.google.com/store/apps/details?id=jp.co.kodansha.android.magazinepocket&referrer=adjust_reftag%3DcOuZZUpwC8K2v%26utm_source%3DUNICORN%2BAdways%26utm_campaign%3D9056-%25E3%2583%259E%25E3%2582%25AC%25E3%2582%25B8%25E3%2583%25B3%25E3%2583%259D%25E3%2582%25B1%25E3%2583%2583%25E3%2583%2588%25EF%25BC%2588%25E3%2582%25B6%25E3%2583%25BB%25E3%2583%2595%25E3%2582%25A1%25E3%2583%2596%25E3%2583%25AB%25EF%25BC%2589_Android%26utm_content%3D16105-%25E3%2580%2590%25E6%2596%25B0%25E8%25A6%258F%25E7%258D%25B2%25E5%25BE%2597_%25E3%2582%25B6%25E3%2583%25BB%25E3%2583%2595%25E3%2582%25A1%25E3%2583%2596%25E3%2583%25AB%25E3%2580%25912021%252F06%252F11%2B0%253A00%25EF%25BD%259E2022%252F01%252F07%2B%25E3%2581%25BE%25E3%2581%25A7%26utm_term%3Dhl0liV8D-044543_0800x0800_211126181630.jpg

**Comment by fmarier** [comment]
[They](https://www.unicornmedia.com/) are no longer in business after being [acquired by BrightCove](https://www.crunchbase.com/organization/unicorn-media).

It's not clear whether their old platform is still in use, but given the fairly specific parameter name, I don't see any harm in including it in our list.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.60.81 Chromium: 118.0.5993.54 (Official Build) beta (x86_64)
-- | --
Revision | 1efb3f333eb41cc34af46ca31fb33c30e0afbfae
OS | macOS Version 13.6 (Build 22G120)
```

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 [panther_beta-user 14 U1B2.230922.010 release-keys]
Brave build: 1.60.96 
Chromium: 118.0.5993.88 (Official Build) beta (64-bit) 
Revision: b4c059ad1d32d6e0cd1466123f03ccb97b3cf858
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-core/pull/20254#issue-1908139194

**ACTUAL RESULTS:**
- Verified that the URL search bar contains only https://brave.com/
- Verified the same by copy & paste the link and by opening the link from another app

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/a5eccb5e-b2cc-455c-b1eb-b73a124e0a61) | ![2](https://github.com/brave/brave-browser/assets/128532965/9924f305-c35b-4874-9c35-088a47c4f26c) |

https://github.com/brave/brave-browser/assets/128532965/a81d87c0-be5f-4001-8d16-2c3f0bcdfeb0
