### ISSUE TITLE
[Android] Add save path to bookmark exported successfully dialog

### ISSUE THREAD

**Issue by timchilds** [brave/brave-browser#33171]
## Description
**Problem:** some users are unable to find where we export bookmarks.
https://community.brave.com/t/export-and-import-feature-on-android-app/506777

**Solution:** show the export path in the dialog. Make it tappable to open folder in default files app (if possible).

![image](https://github.com/brave/brave-browser/assets/28269287/78443330-16ac-4c3c-b1c6-5219a3b7fdf0)

**Comment by Uni-verse** [comment]
In progress on Samsung Galaxy S21 using version:

```
Brave	1.61.77 Chromium: 119.0.6045.163 (Official Build) beta (64-bit) 
Revision	d0b89bdae9ecff96899c68447dae4a2c45c51e2a
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy Tab S7` using version: 

```
Brave	1.61.97 Chromium: 120.0.6099.56 (Official Build) (64-bit) 
Revision	06ca6e12ac1f53536386f61c923915da7d128e75
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

- Ensured that export path is shown in the Export successful message.
- Ensured that confirmation message closes when tapping Close button.
- Ensured that tapping Open folder will open files explorer view.
- Ensured that bookmarks are successfully downloaded to the path location.
- Ensured that selecting Always Open for app selection will successfully export bookmarks next time without the prompt.

_Export flow_

Example | Example | Example | Example
-|-|-|-
![Screenshot 2023-12-05 at 12 32 35 PM](https://github.com/brave/brave-browser/assets/17885425/b3e7a45f-75f5-4c4d-8f17-27584e50e9ec) | ![Screenshot 2023-12-05 at 12 32 40 PM](https://github.com/brave/brave-browser/assets/17885425/0a93e60a-6733-4a3c-9a67-9a83fb52ccb0) | ![Screenshot 2023-12-05 at 12 32 50 PM](https://github.com/brave/brave-browser/assets/17885425/475b0fdb-a7a6-4861-90da-444db791e0b6) | ![Screenshot 2023-12-05 at 12 32 57 PM](https://github.com/brave/brave-browser/assets/17885425/66f43ba2-751e-4f65-97b3-15a2b41a0a57)

_Import flow_

Example | Example | Example | Example
-|-|-|-
![Screenshot 2023-12-05 at 1 19 06 PM](https://github.com/brave/brave-browser/assets/17885425/a23bbd98-1f9f-4a28-96c3-dec3949da7ce) | ![Screenshot 2023-12-05 at 1 19 23 PM](https://github.com/brave/brave-browser/assets/17885425/fa663bac-e811-4d6c-a311-07b7049602b5) | ![Screenshot 2023-12-05 at 1 19 32 PM](https://github.com/brave/brave-browser/assets/17885425/986e2c6b-9930-48f0-88fa-be6d48a2011b) | ![Screenshot 2023-12-05 at 1 19 42 PM](https://github.com/brave/brave-browser/assets/17885425/049771ed-1ee5-4a18-b83c-f22195a48e9a)

_Orientation & Appearance_ 

Landscape | Portrait
-|-
![Screenshot 2023-12-05 at 1 27 34 PM](https://github.com/brave/brave-browser/assets/17885425/16da8f84-b0a5-4ea1-81be-98cc2981f9e8) | ![Screenshot 2023-12-05 at 1 27 38 PM](https://github.com/brave/brave-browser/assets/17885425/0c450dd7-54af-4471-889c-e6a59da53ea7)
![Screenshot 2023-12-05 at 1 27 26 PM](https://github.com/brave/brave-browser/assets/17885425/f5927a61-78fd-45b2-b27f-a02dcae8b911) | ![Screenshot 2023-12-05 at 1 27 05 PM](https://github.com/brave/brave-browser/assets/17885425/aec19a3d-d839-48b5-b0db-b9aea638698a)
