### ISSUE TITLE
Wallet - Incorrect balances and infinite loading for amounts (Error: unable to fetch getTokenBalancesForChainId)

### ISSUE THREAD

**Issue by lukemulks** [brave/brave-browser#33187]
## Description 

I have a strong suspicion that this is a duplicate or related to other issues, but what I'm observing appears to be persistently occurring post-2.0 design refresh, and appears to have regressed to a state that doesn't end up correcting (whereas, in the previous 1.0 version, the state would correct and show proper balances on refresh or when brave://wallet was opened on another tab). 

Feel free to close-merge this to another issue if it is indeed a dupe, but it was a bad one that I wanted to quickly report because I noticed it persisting for more than one day, and after closing/re-opening and updating/relaunching Brave. 

## Steps to Reproduce

   1. Auth in to brave://wallet
   2. Observe infinite loading of balances, with a $0.00 top-level value.
   3. Toggle back and forth between different views; but continue to see the infinite loading.

## Actual result:

This is how it appears to the end user, from within the UI - it makes it seem like they have no assets, and with recent drains happening, may spook users into thinking they fell victim to an incident on first glance. 
![brave-wallet-loading-09212023-UI](https://github.com/brave/brave-browser/assets/8979240/ff186c47-e88b-44df-ae62-ea6f0fefd8eb)

I inspected via Dev Tools, and am noticing repeat `Error: failed to fetch getTokenBalancesForChainId` messages in the console. 
![brave-wallet-loading-09212023-console-expand-error](https://github.com/brave/brave-browser/assets/8979240/915cf15d-79a3-4da2-9c2d-7db8f3ad43c4)

I let the Wallet run in foreground for several minutes, and the error count increased a lot as the browser retries the fetch. In the time it took from my last screenshot to now, the error count has increased from the amount in the screenshot to 52 errors, 148 user messages and 164 total messages. 
![brave-wallet-loading-09212023-console-error-count](https://github.com/brave/brave-browser/assets/8979240/9e320cf3-8ac3-404c-9b73-b98457cd0b03)

## Expected result:
Wallet should quickly display assets and amounts when opened.

## Reproduces how often: 

Consistently. When I open new tabs for Wallet. After closing and relaunching. After updating and relaunching. 

## Brave version (brave://version info)

1.60.44 Chromium: 117.0.5938.88 (Official Build) nightly (64-bit) 

## Version/Channel Information:

Have only observed on Nightly so far. 
- Can you reproduce this issue with the current release? TBD
- Can you reproduce this issue with the beta channel? TBD
- Can you reproduce this issue with the nightly channel? Yes.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc'ing @jamesmudgett @Douglashdaniel @husobee  and @bbondy - this is a pretty gnarly UI bug. Tried monkeying around with enabling/disabling internal brave VPN and issue persists either way.

**Comment by josheleonard** [comment]
I saw a related error on CI today when trying to add balance prefetching to the send screen. Had a parsing error

**Comment by kay-is** [comment]
This bug has prevented me from using the wallet for days now.

**Comment by kjozwiak** [comment]
The above requires `1.60.104` or higher for `1.60.x` verification 👍

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.60.104 Chromium: 118.0.5993.117 (Official Build) (64-bit)
-- | --
Revision | 5dfa047eac682ad367174af6503fc21b59db5977
OS | Windows 11 Version 22H2 (Build 22621.2428)

- Verified steps from [brave/brave-core#20589](https://github.com/brave/brave-core/pull/20589)
- Verified no error message in console when using the wallet, loading balance/NFT, loading graph
- Verified balance is loaded successfully when loading localhost EVM account

**Comment by kay-is** [comment]
I'm still getting this error on v1.61.120 

Brave retries for around a minute or so before it finally works.
