### ISSUE TITLE
Remove GA4's cross-domain measurement query parameter

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#33188]
Google Analytics 4 uses the `_gl` query string parameter in order to sync first-party cookies across different domains owned by the same entity: https://support.google.com/analytics/answer/10071811

These first party cookies include unique identifiers such as client IDs and session IDs: https://www.youtube.com/watch?v=LA2dPVj5y4Y

Therefore this is cross-site user tracking and so it's in scope for our query string filter.

**Comment by fmarier** [comment]
Sample URLs:
- https://mc.manuscriptcentral.com/bmjsrh?_gl=1*1x8u1yj*_ga*MTI1NjIzNjUxOS4xNjc3MDkyMTYx*_ga_EXTSVLH45V*MTY3NzA5MjE2MC4xLjEuMTY3NzA5Mjk0Ni41OS4wLjA.*_fplc*UGhwTDBLM0twUURxUnZvb2lZUVg3ODJacDIlMkJzSGs4SHVjSmFrZTk5ZUFlTFRTUk5oJTJCOU5KYW9IOVhwd2VjUU93VEZHZDI5a1NmcGg5b2p0SktOcWtHJTJGMmJmTVhXJTJGNFdnbUtWM0VDZG0lMkZGQSUyRjB3ZlNqQ1RFbSUyQmRaJTJCVTJ0QSUzRCUzRA..
- https://www.cancerresearchuk.org/sites/default/files/cruk_covid_and_cancer_key_stats_june_2021.pdf?_gl=1*7gat3o*_ga*MjQ3MjU1MDU5LjE2MjE4NDk3MjY.*_ga_58736Z2GNN*MTYzMDU2ODI4NS4xNi4xLjE2MzA1NjkzODUuNg..&_ga=2.152235897.1749986361.1630568286-247255059.1621849726

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.60.79 Chromium: 118.0.5993.32 (Official Build) nightly (x86_64)
-- | --
Revision | 95cf2d4e2e2855bd58fe8002ccd32e3d673abafd
OS | macOS Version 11.7.10 (Build 20G1427)
```


Use a new browser profile.
Ensure adblocking is set to standard mode.
Open https://brave.com/?at_recipient_id=1234&at_recipient_list=5678&unicorn_click_id=abcde&_gl=abc123
Confirm that the URL bar just shows https://brave.com/

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 [panther_beta-user 14 U1B1.230908.003 release-keys]
Brave build: 1.60.96 
Chromium: 118.0.5993.88 (Official Build) beta (64-bit) 
Revision: b4c059ad1d32d6e0cd1466123f03ccb97b3cf858
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-core/pull/20254#issue-1908139194

**ACTUAL RESULTS:**
- Verified that the URL search bar contains only https://brave.com/
- Verified the same by copy & paste the link and by opening the link from another app

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/a5eccb5e-b2cc-455c-b1eb-b73a124e0a61) | ![2](https://github.com/brave/brave-browser/assets/128532965/9924f305-c35b-4874-9c35-088a47c4f26c) |

https://github.com/brave/brave-browser/assets/128532965/a81d87c0-be5f-4001-8d16-2c3f0bcdfeb0
