### ISSUE TITLE
Missing notifications for Brave VPN - Connected state

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#33185]
## Description 

Missing notifications for Brave VPN - Connected state

## Steps to Reproduce

1. install `1.59.94`
2. launch Brave
3. purchase, configured, and connect to `Brave VPN`
4. disconnect from `Brave VPN`
5. wait
6. look at the system tray
7. there should be a notification
8. now, reconnect to `Brave VPN`

## Actual result:

On beta, I've only seen the `Disconnected` notifications; missing `Brave VPN: Connected` state notification

## Expected result:

There should be a notification for the `Brave VPN: Connected` event/state

## Reproduces how often: 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

example | example
---------|----------
![269785295-eb64ae64-b86b-4665-a17c-c95470ec6c44](https://github.com/brave/brave-browser/assets/387249/f7d6bc07-8778-469b-8060-9aa2cc77f6b1) | ![image](https://github.com/brave/brave-browser/assets/387249/441a4730-8eb8-469d-8b1a-4a0c54ffffd1)

cc @spylogsster @MadhaviSeelam @GeetaSarvadnya

**Comment by stephendonner** [comment]
Note: this eventually showed up (once!) after playing with it for a while

![image](https://github.com/brave/brave-browser/assets/387249/025216b1-7b80-4f4e-90af-8e9c6dc0854a)

**Comment by stephendonner** [comment]
I appear to have misunderstood (greatly) how Windows' notifications work 😆 

Here's the same build, after a restart, showing the notifications for both `Connected` and `Disconnected` just fine.

I thought the notification-display panel would _mirror_, not _subsume_, and supplant, the few visual notifications I got.

![image](https://github.com/brave/brave-browser/assets/387249/69ac5abc-24ed-4ee2-8635-cd8770afa2bc)

**Comment by stephendonner** [comment]
@spylogsster @bsclifton @simonhong @MadhaviSeelam as best as we know it, is this issue of mine invalid/worksforme?

**Comment by bsclifton** [comment]
@stephendonner does this still happen for you?

**Comment by stephendonner** [comment]
> @stephendonner does this still happen for you?

Nope, we can and probably should close this.  I believe @MadhaviSeelam also used to see this and both of us haven't really noticed it since the connection-logic rewrite 👍

**Comment by mattmcalister** [comment]
Closing as stale
