### ISSUE TITLE
AC table not working if min visit is set to 1min

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#3320]
## Steps to Reproduce

   1.  clean profile
   2. enable rewards
   3. set min visit to 1min
   4. restart browser
   5. go to site and stay there for 2min
   6. open new tab and visit a site for 2min
   7. go to rewards and check ac table

## Actual result:

no entry into the db

## Expected result:
![image](https://user-images.githubusercontent.com/9574457/52625294-fc170680-2eb0-11e9-893c-568f02905792.png)
(in this image min visit was set to 8s)

## Reproduces how often: 

100%

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
@NejcZdovc was this a regression or a new issue that appeared in `0.60.x`?

**Comment by NejcZdovc** [comment]
@kjozwiak this issue was uncovered when we fixed https://github.com/brave/brave-browser/issues/3134

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.60.40 Chromium: 72.0.3626.109 (Official Build) (64-bit)
-- | --
Revision | fae8db7ab9280fa6704a59980263c804f809ebd5-refs/branch-heads/3626@{#857}
OS | Windows 7

Used STR from description.
