### ISSUE TITLE
Use Constellation for express & slow P3A metrics

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#33217]
Add Constellation support for express/daily & slow/monthly metrics. Use new randomness server & collector endpoints.

**Comment by GeetaSarvadnya** [comment]
@DJAndries Can you add the test plan? Thanks!

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.62.107 Chromium: 120.0.6099.115 (Official Build) beta (64-bit)
-- | --
Revision | 67a3b21572338a0660bb25a5855da0f1e9372a39
OS | Windows 10 Version 22H2 (Build 19045.3803)
```

- Verified the test plan from https://github.com/brave/brave-core/pull/20264

**Comment by GeetaSarvadnya** [comment]
@DJAndries I need a clarification on the point below:

- Only 3 metrics are shown under the `logs_express` but in p3a-json endpoint, I could see only two cadence `express` metrics sent, one metric is not shown I waited for more than one hour but the 3rd metrics is not shown, but 3 `randomness` encrypted metrics are shown for the cadence `logs_express` in the https://star-randsrv.bsg.brave.com/ endpoint (4th screenshot below)

Example | Example | Example | Example
----------|----------|---------- |--------
![image (5)](https://github.com/brave/brave-browser/assets/38657976/e174cb49-c327-4d43-9919-a29a7d063234) | ![image (6)](https://github.com/brave/brave-browser/assets/38657976/6b089ebd-c597-4589-8781-6b6a9fbfb8ec) | ![image (7)](https://github.com/brave/brave-browser/assets/38657976/5b8af2db-7685-443a-9a03-833af820d601) | ![image](https://github.com/brave/brave-browser/assets/38657976/bef72056-dcb7-4c33-b0eb-46b70d8add4b)

**Comment by DJAndries** [comment]
@GeetaSarvadnya 

> Q - Based on what condition the metrics are classified into slow/express/typical? and the metrics that fall under each bucket will remain the same, I mean the same metrics listed under slow/express whenever we launch the browser with the new profile?

Yes, the "reporting cadence" of each metric is hardcoded in the client. You can see the three different lists in [metric_names.h](https://github.com/brave/brave-core/blob/master/components/p3a/metric_names.h).

> Only 3 metrics are shown under the logs_express but in p3a-json endpoint, I could see only two cadence express metrics sent. Q - One metric is not shown I waited for more than one hour but the 3rd metrics is not shown, but 3 randomness encrypted metrics are shown for the cadence logs_express in the https://star-randsrv.bsg.brave.com/ endpoint (4th screenshot below)

P3A JSON "creative" metrics are sent to `p3a-creative-brave.com`. This applies to the metric that you were probably looking for: `creativeInstanceId.total.count`

> Q. I waited for enough time to send all the typical metrics to the endpoint https://star-randsrv.bsg.brave.com (I waited for more than 3 hours) but even after 3 hours I could see only 39 typical randomness metrics at the endpoint. also why does only 39 typical metrics are sent to the server?

Could it be the case that the metrics under `logs_constellation_prep` were miscounted, or perhaps Charles missed some of the requests? Would it be possible to try again? 

> Why does the no of metrics count vary in logs and logs_constellation_prep any idea? 

Either a miscount, or perhaps you advanced the system time by 1 week after all JSON measurements were sent, which would clear out the ephemeral metrics. Ephemeral STAR metrics are not cleared from the log store when the system time is advanced, they only get cleared when the current STAR epoch expires (dictated by randomness server). This would result in a difference in metric count.

> - Instead of three only two express metrics are sent to the endpoint collector.bsg.brave.com ?
- There is one creative cadence type metrics sent to the endpoint collector.bsg.brave.com - Not sure whether this is expected or not there is no mention of this metrics in the test plan

Yes, both of these are expected.
