### ISSUE TITLE
Assets/NFT tabs looks really small on a large screen

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#33210]
## Description 
Assets/NFT tabs looks really small on a large screen

## Steps to reproduce 

   1. Open Wallet in a tab
   2. Assets and NFT tabs highlights are really small

## Actual result 

Asset | NFT
-- | --
<img width=400 src=https://github.com/brave/brave-browser/assets/17010094/4aaf0159-b2cb-48f7-9f81-df12e3be0c85> | <img width=400 src=https://github.com/brave/brave-browser/assets/17010094/d0f4252a-9e77-40d5-b20b-6a2beefa3723>

## Expected result
Better design for tablet view

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Not checked

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Tablet
   - Android version:12
   
## Brave version
1.59.93

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @simoarpe @Pavneet-Sing

**Comment by simoarpe** [comment]
🙌 Nice catch @srirambv! It should be a pretty quick fix, I'm assigning this to me. 
What's the device you used to observe the issue? Thanks

**Comment by srirambv** [comment]
> What's the device you used to observe the issue?

Lenovo Tab with Android 12.

**Comment by simoarpe** [comment]
Issue not relevant anymore as we switched to WebUI where Assets and NFTs tabs have responsive design, and they are shown correctly on tablets. I'm closing this.
