### ISSUE TITLE
Empty side panel is visible when mouse hovered

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#33224]
## Description 

<img width="494" alt="image" src="https://github.com/brave/brave-browser/assets/6786187/fd8d75e6-6b20-471d-a3db-57ccd9b1514c">

This bug is regression from https://github.com/brave/brave-core/pull/20068

## Steps to Reproduce

   1. Set `Show sidebar` option as `On mouseover`
   2. Creating two NTPs
   3. Change active tab and mouse hover to sidebar area to show sidebar UI

## Actual result:

Empty side panel is shown

## Expected result:
Only sidebar UI should be visible

## Reproduces how often: 

Easy

## Version/Channel Information:

- Can you reproduce this issue with the current release? No (1.58.x)
- Can you reproduce this issue with the beta channel? No (1.59.x)
- Can you reproduce this issue with the nightly channel? Yes (1.60.x)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
1.60.79
```

Reproduced the issue using 

```
Brave | 1.60.54 Chromium: 117.0.5938.92 (Official Build) nightly (x86_64)
-- | --
Revision | 3514ee57da8a4987bacc9bcb56cdc5ec0d11ac0a
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.60.54`

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.60.81 Chromium: 118.0.5993.54 (Official Build) beta (64-bit)
-- | --
Revision | 1efb3f333eb41cc34af46ca31fb33c30e0afbfae
OS | Windows 11 Version 22H2 (Build 22621.2283)
```


Reproduced the issue in `1.60.54 Chromium: 117.0.5938.92 nightly` using STR from https://github.com/brave/brave-browser/issues/33224#issue-1910532019

![2023-10-05_16h24_08](https://github.com/brave/brave-browser/assets/98358127/4c8ef833-59e4-4724-b9d5-6395bef6569d)

Steps:

- installed 1.60.81
- launched Brave
- set More Tools -> Show Sidebar to On mouseover
- hovered over the right-most region

### Confirmed no empty side panel is shown
### Confirmed sidebar UI shown 

example | example | example 
----- | ----- | -----
<img width="957" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/cd62f707-5911-4901-95dd-0c0bb706acb5">|<img width="960" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/615ab3f8-ae51-4f14-80d2-61dc79f6c04d">|<img width="958" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/1b4d65df-75d2-4921-87f8-6de13baa1ad6">
