### ISSUE TITLE
NTT (aka SI) should show every 3 NTP view instead of every 4

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#33228]
After the initial count of NTP view to see the first NTT (currently set to 2nd NTP view), there should be additional opportunities for NTT on every 3rd NTP view. Currently this is set to on every 4th NTP view.

**Comment by btlechowski** [comment]
Verified with 

Brave | 1.60.87 Chromium: 118.0.5993.70 (Official Build) beta (64-bit)
-- | --
Revision | 854c1e600054dfca6842cebaf729f100f4b0f066
OS | Linux

#### opted out

Verified initial NTP SI is on 2nd tab:
![image](https://github.com/brave/brave-browser/assets/34715963/b36cdbdc-ce3b-4195-bd27-0f797b77a2f7)

Verified subsequent NTP SI are every 3rd tab:
![image](https://github.com/brave/brave-browser/assets/34715963/42aad11f-37e1-4d62-b4fd-97324b91657b)|![image](https://github.com/brave/brave-browser/assets/34715963/303a5e61-894f-41ad-887c-b91be144fcaf)
--|--

#### opted in

Verified initial NTP SI is on 2nd tab:
![image](https://github.com/brave/brave-browser/assets/34715963/b8b79874-7ae0-4448-8eb2-7eceabac2f77)


Verified subsequent NTP SI are every 3rd tab:
![image](https://github.com/brave/brave-browser/assets/34715963/3fa2ad3e-25e8-4809-b29f-5e47f8c5f72d)|![image](https://github.com/brave/brave-browser/assets/34715963/024b3fce-707e-4030-9060-5de0c27bf075)
--|--

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 [panther_beta-user 14 U1B1.230908.003 release-keys]
Brave build: 1.60.96 
Chromium: 118.0.5993.88 (Official Build) beta (64-bit) 
Revision: b4c059ad1d32d6e0cd1466123f03ccb97b3cf858
```
Filed follow-up issue #33837
---------------------------

<details>
<summary> Fresh install </summary>

**STEPS:**
1. Fresh install and launch Brave
2. Go through onboarding until you land on NTP
3. Open new tab > Confirm that 1st `NTP SI` is shown on the 2nd `NTP`
4. Open a few more now tabs > Confirm that all next `NTP SI` is shown on the 3rd `NTP`
5. Close and restart Brave > Open a few tabs > Verify
6. Enable `Brave News` > Open a few tabs > Verify
7. Enable `Brave Rewards` > Open a few tabs > Verify

**ACTUAL RESULTS:**
- Verified that the 1st `NTP SI` is shown on the 2nd `NTP` and all following `NTP SI` are shown on the 3rd `NTP`.
- Verified that restarting Brave is resetting the counter for the `NTP SI`.
- Verified the same behavior after enabling `Brave News`
- Verified the same behavior after enabling `Brave Rewards`

---------------------------

https://github.com/brave/brave-browser/assets/128532965/2406952d-cf10-450f-b08f-91c86404f3ad

</details>

<details>
<summary> Upgrade install </summary>

**STEPS:**
1. Install build `1.59.x` and launch Brave
2. Go through onboarding until you land on NTP
3. Open a few `NTP` > Confirm that 1st `NTP SI` is shown on the 2nd `NTP` and all following on the 4th `NTP`
4. Now upgrade Brave to build `1.60.96` and launch it
5. Open a few `NTP` > Confirm that 1st `NTP SI` is shown on the 2nd `NTP` and all following on the 3rd `NTP`

**ACTUAL RESULTS:**
- Verified that the 1st `NTP SI` is shown on the 2nd `NTP` and all following `NTP SI` are shown on the 3rd `NTP`.
- Verified that restarting Brave is resetting the counter for the `NTP SI`.

---------------------------

https://github.com/brave/brave-browser/assets/128532965/d97d70c3-73a3-44f8-a253-c98d499dd34c

</details>
