### ISSUE TITLE
Rewards page element alignment issue when browser window is resized

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#3323]
## Description 

Rewards page element alignment issue when browser window is resized

## Steps to Reproduce

   1. Open rewards page and resize and see the magic else watch the video 

## Actual result:

https://youtu.be/TKu9cHLY-e0

## Expected result:
Not what it looks like in the video 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.60.26 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @ryanml @brave/design

**Comment by ryanml** [comment]
@jenn-rhim do you think we should do a minimum width (similar to rewards settings) for the welcome page on desktop?

**Comment by jenn-rhim** [comment]
Yes. Let's keep it 1024 so it'll work also on tablets.

**Comment by kjozwiak** [comment]
Reproduced this on `macOS 10.14.2 x64` using the following build:

Brave | 0.60.44 Chromium: 72.0.3626.109 (Official Build) (64-bit)
-- | --
Revision | fae8db7ab9280fa6704a59980263c804f809ebd5-refs/branch-heads/3626@{#857}
OS | Mac OS X

Example of the issue occurring:

<img width="590" alt="screen shot 2019-02-20 at 5 25 04 pm" src="https://user-images.githubusercontent.com/2602313/53129083-940d9380-3534-11e9-9a4c-f455a734a61d.png">

**Comment by NejcZdovc** [comment]
not reproduce anymore
