### ISSUE TITLE
Element Picker on Android

### ISSUE THREAD

**Issue by Krishna-art-dev** [brave/brave-browser#33241]
Does brave browser on Android gonna support element picker like ubo it will be a great help

**Comment by antonok-edm** [comment]
(moved to `brave-browser`, since this is not related to the rule matching engine)

**Comment by Krishna-art-dev** [comment]
Any progress on this?

**Comment by atuchin-m** [comment]
@rebron @ShivanKaul 
I've tried to enable the feature for Android. The engine itself is cross-platform and works well.
There are 2 questions:
1. how we should trigger the feature? The suggested way is to implement a new app menu item (i.e. near to `Translate..`) 

2. we need to adopt the picker UI to support the mobile device. The main issue that it overlaps a large part of the bottom page area. It's impossible to select elements under the UI.
<img width="25%" src=https://github.com/user-attachments/assets/d33743dd-e776-474e-8226-4cf6b4f2ef8b/>

The picker UI now has 2 states: when you're selecting an element (semi-transparent) and when you've selected one (visible). The simplest fix is to make UI invisible in the first mode.

The screencast how it works now: https://github.com/user-attachments/assets/7292f411-820f-4575-96b2-120b39f96f41

**Comment by Krishna-art-dev** [comment]
@atuchin-m how you enabled it

**Comment by atuchin-m** [comment]
@Krishna-art-dev by modifying the source code and building the binary.

There is no way to enable it for end users until we prepare and merge the changes in the code.

**Comment by Krishna-art-dev** [comment]
@atuchin-m thanks for the information, please add this feature in brave

**Comment by ShivanKaul** [comment]
> but only if this feature is behind a flag and disabled by default

We definitely don't want a feature that we plan to always keep disabled by default. I don't have a good sense for how cluttered the menu currently is on Android but do we not have space for a new item (albeit one that's mainly for more power users)?

**Comment by ShivanKaul** [comment]
@atuchin-m how hard would it be to change the UI for this? What if we restrict this to hiding just one element at a time and not showing the picker UI? I'm thinking the following experience:
1. You select "Block element" via menu
2. Tap on an element on the page
3. That element gets highlighted (like right now) and blurred with just a button on top saying "Block?"
4. If the user presses Block, then we block the element. 
Ideally, we would also have a way for the user to see which elements they're blocking on the current page.

**Comment by atuchin-m** [comment]
> It does not seem like something that the average Brave user will want on the (already cluttered) main menu

@timchilds If you believe that the average Brave user doesn't want it then there is no sense in spending time to implement and to support such "optional" features.

**Comment by atuchin-m** [comment]
> how hard would it be to change the UI for this?
It will work, but the main issue that you can't tune the selector to add. There is no way to block a one particular element, it's alway about using a selector. Cutting ability to tune is a major limitation for the feature.
WDYT about adding a small button to switch bottom/top position of UI.?

Another thing that we need to improve is the adblock settings for Android to manage the added rules. Otherwise, it's just no way to delete them.

Optionally, we can also make the pref syncable. That way the rules you added on your desktop device will be used on a mobile.

**Comment by Krishna-art-dev** [comment]
What if you guys add that feature in brave shild?

**Comment by Krishna-art-dev** [comment]
![Image](https://github.com/user-attachments/assets/fb2e9174-f084-41f5-8b83-6cc1bf2b6fcb)
Somewhere here, then "ads and other creepy things blocked" will be in center and element picker will be in left side, after blocked ad count

**Comment by atuchin-m** [comment]
Here is an example branch to activate content picker for android:
https://github.com/brave/brave-core/pull/new/content-picker-android-testing

@ShivanKaul 
The topic was discussed in slack for some time, but here we need to fix the further steps.

The plan the way I see it:
* Create a UI to activate the feature for Android (a design
* Modify the TypeScript code and adjust the layout for mobile devices (a product description needed)
* Implement additional improvements, such as capturing the menu coordinates and syncing user preferences.

Also, we already have a submenu in settings to manage the custom rules.

**Comment by hffvld** [comment]
Verified on `Galaxy Z Fold 6` using version(s):
```
Device/OS: Galaxy Z Fold 6 / q6quew-user 14 UP1A.231005.007 release-keys
Brave build: 1.75.115
Chromium: 132.0.6834.57 (Official Build) canary (64-bit) 
```

Filed follow-up issue #43038 and 43040
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/26725#issue-2691031091
2. *Verify*

**ACTUAL RESULTS:**
- Verified that Brave flag `#block-element-feature` is OFF by `default` and `Block element` is unavailable in `Brave Shields`.
- Verified that `Block element` is shown in `Brave Shields` after enabling Brave flag `#block-element-feature`.
- Verified that the user can block distracting elements on the page, and `Xpath` of the blocked element is added to the `Custom filters` list.

---------------------------

|Flag is OFF by default|Flag is manually ON|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/43889f41-c033-472b-86e2-6eb367fefd2e) | ![2](https://github.com/user-attachments/assets/3738c301-f33f-46a4-9473-8529b0f1048a) |
| ![1](https://github.com/user-attachments/assets/bf3910a1-581b-4752-9d3a-5edf07a8b9c6) | ![2](https://github.com/user-attachments/assets/b58255c0-c312-452c-8da0-6c7acb3e8a12) |
| ![1](https://github.com/user-attachments/assets/b18c0313-c811-4e0f-95a9-fbda1e3ca1ef) | ![2](https://github.com/user-attachments/assets/d1816c51-a2b2-4b55-b566-2e90b682f979) |

https://github.com/user-attachments/assets/8b37b133-5a7a-4cd7-a162-923090444205

**Comment by hffvld** [comment]
Verified on `Galaxy Tab S8` using version(s):
```
Device/OS: Galaxy Tab S8 / gts8wifixx-user 14 UP1A.231005.007 release-keys
Brave build: 1.75.161
Chromium: 132.0.6834.83 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-core/pull/26725#issue-2691031091
2. *Verify*

**ACTUAL RESULTS:**
- Verified that Brave flag `#block-element-feature` is ON by `default` and `Block element` is available in `Brave Shields`.
- Verified that the user can block distracting elements on the page, and `Xpath` of the blocked element is added to the `Custom filters` list.

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/8831165c-1f57-4b0c-9fa5-4cf28823cfec) | ![2](https://github.com/user-attachments/assets/9ba2fb1d-83ad-4564-9af0-408464f9ceab) | ![3](https://github.com/user-attachments/assets/02e99c4d-395b-4172-933b-1f1ca492c9db) |
| ![1](https://github.com/user-attachments/assets/1ec34ce6-3420-4cb1-92df-b3550d1d0494) | ![2](https://github.com/user-attachments/assets/931180c0-4054-4f6d-a9b5-ad8e22a9e65e) | ![3](https://github.com/user-attachments/assets/80ccf7ea-c805-42dd-93d3-1126de0ec9f9) |
