### ISSUE TITLE
Brave News only download the page's linked alternate feeds when UI list is opened

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#33246]
When visiting a site and the site advertises RSS feeds (via `<link>` elements), Brave downloads the content of those URLs in order to determine feed type, validity and the feed name.

Instead, we should use the existance of those elements to determine whether to show the url bar icon:
![image](https://github.com/brave/brave-browser/assets/741836/c0166262-faee-4ae7-808d-09d0296b9b16)

And only when that icon is clicked, should we fetch the feeds to get the necessary information (if needed).
We can show a loading indicator in the UI whilst the information is being fetched.

**Comment by fallaciousreasoning** [comment]
Hi @LaurenWags, this one probably needs something like Fiddler too, unfortunately:

1. Setup Fiddler
2. Navigate to https://hacks.mozilla.org/ with Brave News enabled
3. The feed should not be fetched yet in Fiddler (the feed url is https://hacks.mozilla.org/feed/)
4. Click the Brave News button in the LocationBar
5. The feed should be fetched https://hacks.mozilla.org/feed/ and the title of the Feed should populate

**Comment by LaurenWags** [comment]
thanks @fallaciousreasoning! we can give that a try and report back if we have problems 👍🏻

**Comment by fallaciousreasoning** [comment]
Let me know if it's not working / if we need to work out an easier way to test :smile:

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.60.94 Chromium: 118.0.5993.70 (Official Build) beta (64-bit)
-- | --
Revision | 6a9dda6d700daa1da53ec97072458dd271ba5c01
OS | Windows 10 Version 22H2 (Build 19045.3570)
```

## Steps:
1. launched `Fiddler Everywhere`
2. installed `1.60.94`
3. launched Brave
4. loaded `hacks.mozilla.org`
5. confirmed webpage (HTML, CSS, JS)-associated traffic in `Fiddler Everywhere`
6. clicked on the `Manage Subscriptions` RSS-feed icon in the URL bar
7. confirmed `https://hacks.mozilla.org/feed` traffic in `Fiddler Everywhere`

`traffic before` | `traffic after`
-----------------|------------
![image](https://github.com/brave/brave-browser/assets/387249/ac840084-d0cf-4deb-9dd2-b9728dfdd471) | ![image (1)](https://github.com/brave/brave-browser/assets/387249/25f7bea6-efca-4c3c-9f02-1715b0de2806)

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 [panther_beta-user 14 U1B2.230922.010 release-keys]
Brave build: 1.60.96 
Chromium: 118.0.5993.88 (Official Build) beta (64-bit) 
Revision: b4c059ad1d32d6e0cd1466123f03ccb97b3cf858
```
---------------------------

**STEPS:**
1. Fresh install and launch Brave
2. Enalbe `Brave News`
3. Navigate to https://hacks.mozilla.org/ > Verify via Fiddler/Charles Proxy that the feed has not been fetched yet (the feed URL is https://hacks.mozilla.org/feed/)
4. Thre-dot menu > Enable `Desktop site`
5. Tap the `Feed` button on the top right side > Verify via Fiddler/Charles Proxy that the feed is fetched now (the feed URL is https://hacks.mozilla.org/feed/)

**ACTUAL RESULTS:**
- Verified that the feed is not fetched yet (the feed URL is https://hacks.mozilla.org/feed/) when the website loads
- Verified that the feed is fetched (the feed URL is https://hacks.mozilla.org/feed/) after the `Feed` button on the website tapped

---------------------------

*Reproduced the issue with older build `1.59.120`*

https://github.com/brave/brave-browser/assets/128532965/2e7dc0a3-77ac-417b-930e-4659b9564d46

*VERIFIED in the newer build `1.60.96`*

https://github.com/brave/brave-browser/assets/128532965/e23f3152-baf5-41cb-8e21-d2493d6a87e9
