### ISSUE TITLE
incorrect verified youtube publisher favicons in auto contribute table

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#3324]
## Description 

Incorrect youtube publisher favicons are displayed in auto contribute table.

## Steps to Reproduce

   1. Install 0.60.26 and launch with clean profile
   2. Enable rewards (I used panel)
   3. Visit a verified youtube publisher (such as https://www.youtube.com/channel/UCqluXkpvWxWBz6sI1JPAsaA)
   4. I stayed on this page for about 8s.
   5. I then clicked on a video.
   6. Once video started I clicked on BAT logo. At this point, I encountered #3043 as the panel changed from publisher info (showing generic YT icon) to youtube.com (showing empty favicon)
   7. Go to view brave://rewards.

## Actual result:
![screen shot 2019-02-12 at 11 42 57 am](https://user-images.githubusercontent.com/28145373/52652052-5f0d9b00-2ebb-11e9-815e-fa090457878d.png)

![screen shot 2019-02-12 at 11 43 39 am](https://user-images.githubusercontent.com/28145373/52652096-7482c500-2ebb-11e9-9f70-3879594e05f8.png)

## Expected result:
Since publisher is verified, I should see their favicon from their channel.
youtube.com should be showing the youtube icon (not empty favicon).
This image is from 0.59.35 (current release version):
![screen shot 2019-02-12 at 11 45 58 am](https://user-images.githubusercontent.com/28145373/52652267-d17e7b00-2ebb-11e9-9d45-cefb55a1c8eb.png)

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.60.26 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Mac OS X

Brave | 0.61.20 Chromium: 72.0.3626.81 (Official Build) dev(64-bit)
-- | --
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS | Mac OS X

### Reproducible on current release: no, does not reproduce on 0.59.35
- Does it reproduce on brave-browser dev/beta builds? yes, dev and beta

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
cc @brave/legacy_qa

**Comment by LaurenWags** [comment]
cc @kjozwiak @rebron @NejcZdovc

**Comment by LaurenWags** [comment]
Also, here are how some other sites behave. Looks like regular website favicons (verified/not verified) appear fine. Unverified youtube channels display generic youtube favicon as expected. Youtube site and verified yt channel favicons do not display correctly.

This is 0.60.26:
![screen shot 2019-02-12 at 11 54 10 am](https://user-images.githubusercontent.com/28145373/52653002-1951d200-2ebd-11e9-979b-7b341c70baec.png)

This is from 0.59.35 for comparison:
![screen shot 2019-02-12 at 11 54 03 am](https://user-images.githubusercontent.com/28145373/52653020-1fe04980-2ebd-11e9-89c7-03a5e10069c6.png)

**Comment by GeetaSarvadnya** [comment]
Reproducible on Windows 10 x64 - 0.60.27

![image](https://user-images.githubusercontent.com/38657976/52653489-10411f00-2f16-11e9-9a3b-4ef630a297fc.png)

**Comment by LaurenWags** [comment]
Looks like Verified twitch publishers are showing their favicon and unverified twitch publishers just show standard twitch icon:
![screen shot 2019-02-12 at 3 38 46 pm](https://user-images.githubusercontent.com/28145373/52666459-5b3e4080-2edc-11e9-990b-1d53ac1ab34a.png)

**Comment by btlechowski** [comment]
Reproduced on Ubuntu 17.10

Brave | 0.60.26 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Linux

![image](https://user-images.githubusercontent.com/34715963/52678935-97e95680-2f33-11e9-8389-449b0229185b.png)

**Comment by srirambv** [comment]
Verification passed **only** for YT publishers on 

Brave | 0.60.34 Chromium: 72.0.3626.109 (Official Build) beta(64-bit)
-- | --
Revision | fae8db7ab9280fa6704a59980263c804f809ebd5-refs/branch-heads/3626@{#857}
OS | Linux

* Verified YT publishers favicon is shown on both BR panel and in a-c table
* Verified Twitch publishers favicon not shown on both BR panel and in a-c table (logged #3404)
![image](https://user-images.githubusercontent.com/17010094/52950285-ab1d7b80-33a4-11e9-913d-a640747ab2b4.png)

![image](https://user-images.githubusercontent.com/17010094/52950115-2599cb80-33a4-11e9-8b1a-9861f2807a92.png)
![image](https://user-images.githubusercontent.com/17010094/52950198-698cd080-33a4-11e9-80a5-9407845c1455.png)
