### ISSUE TITLE
hardware acceleration broken in Raspberry Pi OS

### ISSUE THREAD

**Issue by wenqingj** [brave/brave-browser#33249]
## Description 
Many web pages are broken in Brave browser when the "use hardware acceleration when available" is turned on in Raspberry Pi OS. The easiest way to reproduce is to play a Youtube video.

## Steps to Reproduce
   1. Go to youtube.com 
   2. click on any one video
   3. when the video plays, watch the control buttons (pause, volume, caption, etc.). Try to click or adjust via the controls.

## Actual result:
The control buttons are rendered wrong and are hard to use.
However, if you turn off the "use hardware acceleration when available" (and restart browser), the issue is no more.

## Expected result:
The control buttons should be rendered similarly as done in other browsers, even when "use hardware acceleration when available" turned on.

## Reproduces how often: 
Every time.

## Brave version (brave://version info)
[Version 1.58.131 Chromium: 117.0.5938.92 (Official Build) (64-bit)]
Raspberry Pi OS - latest version, with latest update, on a Raspberry Pi 4B 64-bit ARM.

## Version/Channel Information:
I don't understand what's a channel?

- Can you reproduce this issue with the current release? Yes the latest release 
- Can you reproduce this issue with the beta channel?  I've not tested any beta release
- Can you reproduce this issue with the nightly channel?  I've not tested any nightly release

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 
Tested a Chromium version 113 with hardware acceleration turned on, without any issue.

## Miscellaneous Information:
Other web site pages may also be rendered in a mess. But I'm not sure how reproducible they are. Try marketwatch.com home page, if it looks well, try to scroll up and down a little bit.

**Comment by wenqingj** [comment]
This might help: this started around one or two weeks ago. Before that Brave had been running flawlessly.
The firmware of the Raspberry Pi 4B that I use has the latest update in May 2023. Since May the firmware (and the underlying hardware) is not changed. The Brave browser ran well until earlier this month (September). It's very likely due to some Brave version updates around that time...

**Comment by joaquinbvw** [comment]
I just installed Brave today on my Raspberry Pi 4 and I have the same issue. I disabled "use hardware acceleration when available" and followed the usual instructions to enable hardware acceleration on chromium for the Raspberry Pi (https://www.linuxuprising.com/2021/04/how-to-enable-hardware-acceleration-in.html). I'm not really sure if this is working better than before I haven't compared both approaches. By the way, thank you for the post, I was starting to think I messed something very badly while installing brave because I couldn't find any reference on the internet until I found this issue.

**Comment by wenqingj** [comment]
Chromium v 116 for Pi 4B is also good. It's likely to be Chromium v117's problem (the Brave I am using is based on Chromium v117), instead of Brave's. But that's just my speculation.

**Comment by mateli** [comment]
Did anyone try Chromium 117 to see if it has the same problem?
Did anyone try to compile brave on Raspbian OS to see what happens?
What about other Linux distributions?

**Comment by wenqingj** [comment]
Well, the Pi OS update only advances to version 116 as of today. To try out 117 I guess you have to know how to build the browser for ARM 64-bit. A skill I don't have ...

**Comment by wenqingj** [comment]
The Chromium in Pi OS is now updated to version 119.0.6045.171, and its software acceleration is still working well. The Brave browser (latest) in Pi OS is version 119.0.6045.199, and its software acceleration is still broken. Since there is no big difference in the version, I guess the bug is more likely on the Brave side?

**Comment by wenqingj** [comment]
The issue is no more. The OS is now based on Debian 12, and the Brave browser is also based on a much later version. I'm closing this issue, and thanks a lot for all your efforts!
