### ISSUE TITLE
Change Password Manager tab icon to match Brave brand

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#33242]
## Description 

The icon on the password manager tab looks like it was pulled straight from Chrome/Chromium — even through Chrome's does look slightly different (both shown below). The icon in the tab should match the rest of the Brave brand.

Icon in Brave:
![image](https://github.com/brave/brave-browser/assets/3299098/6ef5b359-fafc-4fd7-944c-fb43ef4ea10e)

Icon in Chrome:
![image](https://github.com/brave/brave-browser/assets/3299098/502984bb-05ce-4744-9470-abf790795d47)

**Comment by rebron** [comment]
cc: @aguscruiz

**Comment by aguscruiz** [comment]
@fallaciousreasoning we should use the same one we have in the menu here 👀

**Comment by fallaciousreasoning** [comment]
The one in the menu looks a little odd next to our other icons, as it doesn't have much height and looks a wee bit small:
![image](https://github.com/brave/brave-browser/assets/7678024/1283fb28-4a70-41dc-9091-fd6e1f3d330f)

Do you think the `key-lock` icon is better?
https://nala.bravesoftware.com/icons/key-lock.svg

**Comment by fallaciousreasoning** [comment]
I also feel like it doesn't look great as an installed app icon:
![image](https://github.com/brave/brave-browser/assets/7678024/c2cc6bd4-1452-4e5d-9ec5-91c539435e34)

**Comment by fallaciousreasoning** [comment]
Just to prove I'm not and should never be a designer, what about something like this:
![image](https://github.com/brave/brave-browser/assets/7678024/8e616239-48d5-402c-9809-00919efdf1a7)

(I'm using the release gradient for the background `--leo-gradient-brave-release`)

**Comment by aguscruiz** [comment]
Ugh, I didn't know you could install it as a web app and it'd look THAT big hah. I think the one in the tab is ok. But I'll have to spend more time with the big one. 

I'll put it in my backlog for now, is that ok?

**Comment by fallaciousreasoning** [comment]
@aguscruiz's much nicer icon:
![PWA Icon](https://github.com/brave/brave-browser/assets/7678024/2862c768-3635-48e5-a758-d59329d617c2)

**Comment by fallaciousreasoning** [comment]
Exported the wrong layer - actual icon is this:
![Password manager](https://github.com/brave/brave-browser/assets/7678024/e26d9ce7-bc6a-469d-9d87-856fc6abc695)

**Comment by stephendonner** [comment]
## Verification `PASSED` using

```
Brave | 1.62.52 Chromium: 119.0.6045.134 (Official Build) nightly (x86_64)
-- | --
Revision | f73c8c1e096256f71307b56c8f7180fc85028d85
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Confirmed the new key icon is very "Bravey", in all the places I knew to check

`Install app?` prompt |`brave://settings/autofill` | `brave://settings/autofill` | `brave://password-manager/passwords` | `brave://password-manager/passwords`
---------|---------|----------|----------|------------
<img width="1692" alt="Screen Shot 2023-11-14 at 1 34 14 PM" src="https://github.com/brave/brave-browser/assets/387249/04612803-67f7-446d-a924-f188d0a0aaff"> | <img width="1692" alt="Screen Shot 2023-11-14 at 1 34 55 PM" src="https://github.com/brave/brave-browser/assets/387249/be8dbe36-8bae-40a3-a76d-ff51fdab7415"> | <img width="1692" alt="Screen Shot 2023-11-14 at 1 35 11 PM" src="https://github.com/brave/brave-browser/assets/387249/8ba7d2be-d551-479a-8d5f-b8c2077b1e65"> | <img width="611" alt="Screen Shot 2023-11-14 at 1 43 01 PM" src="https://github.com/brave/brave-browser/assets/387249/b44e2536-aca0-4520-b0cf-646e5b2a81df"> | <img width="604" alt="Screen Shot 2023-11-14 at 1 43 17 PM" src="https://github.com/brave/brave-browser/assets/387249/08a843ba-6190-403d-ba96-e76e17fcfae9">

`Key` icon | `Finder` icon
-----------|------------
<img width="100" alt="Screen Shot 2023-11-14 at 1 34 42 PM" src="https://github.com/brave/brave-browser/assets/387249/9c35e014-c99a-48d5-899a-7af681382108"> | <img width="1032" alt="Screen Shot 2023-11-14 at 1 36 01 PM" src="https://github.com/brave/brave-browser/assets/387249/7d1a513e-9f4a-4803-982a-e4d9c2e3620e">
