### ISSUE TITLE
Hide/unhide NFT doesn't work as expected

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#33255]
## Description 
Hide/unhide NFT doesn't work as expected

## Steps to reproduce 

   1. Restore wallet that has a few NFTs
   2. Enable NFT view to list the NFTs
   3. Add a new NFT that you don't own and make sure it lists in visible NFTs
   4. Go to Edit NFT and uncheck the newly added NFT and an existing one
   5. Refreshes and hides the NFTs 
   6. Go to Hidden tab of NFT and open edit visible NFT
   7. All NFTs are selected
   8. Uncheck the added NFT from step 3 
   9. NFT tab reloads but doesn't unhide the NFT

## Actual result 

https://github.com/brave/brave-browser/assets/17010094/a82285b3-8bdb-4f81-8159-495ade3ee21d

## Expected result
Hidden NFTs should not be selected when edit NFT is hidden tab. Also should be able to unhide NFTs

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Not checked

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 13
   
## Brave version
1.59.93 x64 Beta build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @simoarpe @Pavneet-Sing

**Comment by kjozwiak** [comment]
The above requires `1.59.113` or higher for `1.59.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.59.115 x64 build
- Verified steps from issue description and [brave/brave-core#20361](https://github.com/brave/brave-core/pull/20361)
- Verified unchecking NFTs moves them into hidden tab
- Verified checking NFTs moves them back into collected tab

https://github.com/brave/brave-browser/assets/17010094/2e4a65ac-80e8-499f-8afc-4ce596750101
