### ISSUE TITLE
Double `Summarize this page` buttons when using the browser's `Back` button on `github.com`

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#33268]
## Description 

Double `Summarize this page` buttons when using the browser's `Back` button on `github.com`

## Steps to Reproduce

1. install `1.60.60`
2. launch Brave
3. restart (to pick up Griffin seed)
4. click on the `Brave Leo` icon
5. click `Accept and begin`
6. load `github.com`
7. load an issue page or two
8. click back (to the homepage)
9. repeat until you see double `Summarize this page` buttons

## Actual result:

example | example
---------|---------
<img width="1948" alt="Screenshot 2023-09-27 at 1 03 39 AM" src="https://github.com/brave/brave-browser/assets/387249/b3eea30f-f30b-43b5-8d4f-3676b4ea5567"> | <img width="1470" alt="Screenshot 2023-09-27 at 1 56 39 AM" src="https://github.com/brave/brave-browser/assets/387249/f1b8409a-723a-412b-80fb-dbea86ad9f3a">

## Expected result:

Should only have a single (`1`) `Summarize this page` button

## Reproduces how often: 

100% / easily

## Brave version (brave://version info)

```
Brave | 1.60.60 Chromium: 117.0.5938.92 (Official Build) nightly (x86_64)
-- | --
Revision | 9a4644344a53150ebad5406037a6463714787348
OS | macOS Version 14.0 (Build 23A344)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @bbondy @mattmcalister @rebron @aguscruiz @petemill @nullhook @brave/qa-team

**Comment by stephendonner** [comment]
Also, just browsing around our Jenkins CI instance, too.



![Image](https://github.com/brave/brave-browser/assets/387249/8b0a0fda-b569-4985-9575-421320c6a9c8)

**Comment by kjozwiak** [comment]
The above requires `1.60.102` or higher for `1.60.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 


```
Brave	1.60.102 Chromium: 118.0.5993.96 (Official Build) beta (64-bit) 
Revision	3598a9fc6b7752181feb25caa131bc386d6d054c
OS	Windows 10 Version 22H2 (Build 19045.3570)
```

### Followed my original steps to reproduce, and confirmed no more duplicate/repeated `Summarize this page` buttons

Jenkins | GitHub
---------|--------
![image (7)](https://github.com/brave/brave-browser/assets/387249/59742296-e383-478e-9f80-e05038dd54a6) | ![image (6)](https://github.com/brave/brave-browser/assets/387249/75bf2bad-7fcb-4f33-908a-027d1bf92803)
