### ISSUE TITLE
[ads] Decouple user rewards from account

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#33260]

**Comment by btlechowski** [comment]
Verified with


Brave | 1.63.159 Chromium: 122.0.6261.57 (Official Build) (64-bit)
-- | --
Revision | 118f746822a0acc7abc8c48993a704fcd0e29122
OS | Linux

Verified test plan from https://github.com/brave/brave-core/pull/20301

### rewards - opted out 

<details>

### NTT



### Brave News inline ad

<details>

### rewards - opted in

<details>


### NTT



### Brave News inline ad



### Notification ad

<details>
