### ISSUE TITLE
[Nala (nee Leo)]: Event handler names are wrong

### ISSUE THREAD

**Issue by fallaciousreasoning** [brave/brave-browser#33264]
A while back we migrated some components from using `onChanged` events to `onChange` events. Looks like we didn't migrate the stuff in brave-core which was using them.

I imagine this means those `Toggles`/`Checkboxes` which are using the wrong events don't work :fearful: 

@Douglashdaniel I might need your help testing this :laughing: 

Additionally, it looks like some dropdowns were broken by https://github.com/brave/leo/pull/395

**Comment by fallaciousreasoning** [comment]
Offending commits in Leo:
1. https://github.com/brave/leo/commit/a2e6e7244a66f1ba9c5defdf76303695a64adb57 (changes Checkboxes)
2. https://github.com/brave/leo/commit/570fa5165a9c5fa6aaa0a0fec654346ca899ff2c (changes Toggles)

It might be that everything still works (though I'd be surprised)

**Comment by petemill** [comment]
This is for the design system formerly known as Leo 😄

**Comment by petemill** [comment]
The confusion likely comes from the fact that the design system components are still called "Leo" in brave-core code, and the (more newly introduced) Leo AI Chat components are named "AI Chat"

**Comment by bbondy** [comment]
Sorry!

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.60.81 Chromium: 118.0.5993.54 (Official Build) beta (64-bit)
-- | --
Revision | 1efb3f333eb41cc34af46ca31fb33c30e0afbfae
OS | Windows 11 Version 22H2 (Build 22621.2283)

- Verified steps from https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1695842869492959
- Verified toggles work as expected

https://github.com/brave/brave-browser/assets/17010094/d15054b5-da07-4310-9eed-bf65513b3502
