### ISSUE TITLE
Return sensible lies with fingerprinting protection

### ISSUE THREAD

**Issue by tomlowenthal** [brave/brave-browser#3326]
It's been reported that we return null rather than an empty array for `WebGLRenderingContext` `getSupportedExtensions` when device recognition blocking is on. This might unnecessarily rek things calling that API, so maybe we should return lies of the right type instead.

https://community.brave.com/t/device-recognition-blocking-may-broke-some-site/44487

**Comment by pes10k** [comment]
Fixed by farbling (tm)
