### ISSUE TITLE
Fix NFT image flashing HTML broken image

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#33261]
- Open NFT details
- Wait for the NFT image to load
- After the image skeleton disappears, there is a flash of HTML broken image before the correct NFT image shows

https://github.com/brave/brave-browser/assets/48117473/eb2828fa-9c4f-4c26-9827-01263c1ed15c

**Comment by kjozwiak** [comment]
The above requires `1.59.109` or higher for `1.59.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.59.109 Chromium: 118.0.5993.21 (Official Build) beta (64-bit)
-- | --
Revision | aacb6a6f8bd916bd49f064b2137b007fa6c47b51
OS | Windows 11 Version 22H2 (Build 22621.2283)

- Verified steps from [brave/brave-core#20302](https://github.com/brave/brave-core/pull/20302)
- Verified throttling network speed and loading the NFT doesn't show any HTML broken image before loading the NFT image

https://github.com/brave/brave-browser/assets/17010094/cb47b533-b99c-40eb-8947-2e2c00bc093a
