### ISSUE TITLE
`Brave News` onboarding card displaying on unsupported regions (not respecting locale check)

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#33267]
## Description 

While verifying/running through https://github.com/brave/brave-core/pull/20197 on `desktop`, noticed that the `Brave News` onboarding card was still being displayed for `fr-FR` & `de-DE` even though they technically shouldn't. Currently on `desktop`, we're only displaying the `Brave News` animation/card on certain locales as per https://github.com/brave/brave-core/blob/master/components/brave_news/browser/locales_helper.cc#L39.

I'm assuming we'll want to do the following:

* on new installs while on an unsupported region, don't display the `Brave News` onboarding card via the NTP
  * assuming users can still enable this on their own via `Hamburger Menu` -> `Settings` -> `Brave News`
* do nothing for users who are in unsupported regions but already enabled Brave News

## Steps to reproduce 

**`Prerequisites before launching Brave:`** Set the OS language to either `French - France` or `German - Deutschland"

   1. install `1.60.38 Chromium 117.0.5938.88`
   2. launch `Brave` and run through onboarding (doesn't really matter what you select/skip)
   3. you'll notice that the `Brave News` card is still visible for unsupported regions

QA will basically need to run through the same STR/Cases outlined via https://github.com/brave/brave-core/pull/20197#issuecomment-1736601293 once the issue has been resolved/fixed.

## Actual result 

**`Example`** | **`Example`** | **`Example`**
---------------|-----------------|------------------
![Screenshot_20230926-234608](https://github.com/brave/brave-browser/assets/2602313/c9d2037e-0537-4916-b006-582e17fa4dfe) | ![Screenshot_20230926-234731](https://github.com/brave/brave-browser/assets/2602313/12392453-89f3-4920-8f70-81a363f8dc72) | ![Screenshot_20230926-234649](https://github.com/brave/brave-browser/assets/2602313/19ea5b7f-244e-4f93-946a-4384027e8681)

## Expected result

The `Brave News` onboarding card shouldn't be displayed for unsupported regions. Quick example of `Desktop` working:

**`Example`** | **`Example`** | **`Example`**
---------------|-----------------|------------------
![1](https://user-images.githubusercontent.com/2602313/270849546-ebb4db83-d4f3-4b43-a0fd-30b82dcc4eba.png) | ![2](https://user-images.githubusercontent.com/2602313/270849551-c99c5673-52a9-41a8-b2a5-dfe32a48c0a8.png) | ![2](https://user-images.githubusercontent.com/2602313/270849564-88d8e035-30b6-40a7-8b1c-85e4560b9655.png)

## Issue reproduces how often 

100% reproducible using the STR/Cases outlined above.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `Yes`
- Can you reproduce this issue with the current Play Store Beta version? `Yes` 
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `ARM`
   - Device type (Phone, Tablet, Phablet): `Pixel 6` (Phone)
   - Android version: `Android 14`
   
## Brave version

```
Brave | 1.60.38 Chromium: 117.0.5938.88 (Official Build) canary (64-bit)
--- | ---
Revision | 89f7ea7a01a3ab15163916a9441c473ab1021372
OS | Android 14; Build/U1B1.230908.003; 34; REL
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by Uni-verse** [comment]
In progress on Android ARM
