### ISSUE TITLE
Add brave-core debounce layers for iOS

### ISSUE THREAD

**Issue by cuba** [brave/brave-browser#33275]
## Description 

Debounce in iOS is using custom code. Let's use the code in brave-core instead.

## Test strategy
1. Test the debouncing feature in desktop [here](https://dev-pages.brave.software/navigation-tracking/debouncing.html)

**Comment by btlechowski** [comment]
Verified with

Brave | 1.64.91 Chromium: 122.0.6261.94 (Official Build) beta (64-bit)
-- | --
Revision | 939586e20d208404b83713ea05cf5f6fa7fe3dd5
OS | Linux


### Default

<details>

![image](https://github.com/brave/brave-browser/assets/34715963/03455785-fe17-4298-9460-37cd0c47af20)


</details>


### Base64

<details>

![image](https://github.com/brave/brave-browser/assets/34715963/c140e2f2-a3be-406c-b02a-4e5b33bc1143)


</details>


### Regex

<details>

![image](https://github.com/brave/brave-browser/assets/34715963/6b7685ff-d3c0-47ed-b7b8-b1fbb45aa6c1)


</details>

### Regex (multi)

<details>

![image](https://github.com/brave/brave-browser/assets/34715963/534388cb-218d-4602-9045-058cae610292)


</details>

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.64.90 Chromium: 122.0.6261.94 (Official Build) beta (x86_64)
-- | --
Revision | 726c6970a1e9c057c69d80e03ad95a7c561fbfe7
OS | macOS Version 13.6.4 (Build 22G513)
```

**Comment by hffvld** [comment]
### IN PROGRESS...

Verified on `Galaxy Tab S8` and `Pixel 7` using version(s):
```
Device/OS: 
- Galaxy Tab S8 / gts8wifixx-user 14 UP1A.231005.007 release-keys
- Pixel 7 / panther_beta-user 14 AP21.240119.009 release-keys
Brave build: 1.64.95 
Chromium: 122.0.6261.94 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-browser/issues/33275#issue-1915961065
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the results are correct

---------------------------

|Enabled|Default|Base64|Regex|Regex (multi)|
|:-:|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/a1a9b81d-84aa-4d6b-bfbd-952de96e04c9) | ![2](https://github.com/brave/brave-browser/assets/128532965/ab68c6fe-e17f-40cb-b27d-479f18e853dd) | ![3](https://github.com/brave/brave-browser/assets/128532965/661ca656-92f0-4dc7-9e92-4858af00ff48) | ![4](https://github.com/brave/brave-browser/assets/128532965/bb4913c0-f732-47be-b393-dc62cac9abc6) | ![5](https://github.com/brave/brave-browser/assets/128532965/9611814f-7517-4818-9a56-1ec6844409b6) |
|Disabled|Default|Base64|Regex|Regex (multi)|
| ![1](https://github.com/brave/brave-browser/assets/128532965/e31ae9cd-4b28-443a-b1f6-58e9e286f40f) | ![2](https://github.com/brave/brave-browser/assets/128532965/ba99331e-e579-4b12-89b7-3a984d820a59) | ![3](https://github.com/brave/brave-browser/assets/128532965/832e8f8c-1612-4ea7-9747-463d9aa1cfa9) | ![4](https://github.com/brave/brave-browser/assets/128532965/9833007d-7961-47df-91d8-d453be631d93) | ![5](https://github.com/brave/brave-browser/assets/128532965/a980ded7-07cb-4d1c-84be-20b0d90c4a44) |

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.64.104 Chromium: 123.0.6312.46 (Official Build) (64-bit)
-- | --
Revision | 0ca3d372cf8aab96fafdd75f5c5c8d2012bc0cc6
OS | Windows 11 Version 23H2 (Build 22631.3296)
```
brave://flags/#brave-debounce

Enabled | Disabled
---- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/8eb4283e-cea9-46cf-b6a2-9a4c5892379c)|![image](https://github.com/brave/brave-browser/assets/98358127/b2cc60d1-3fb3-4a1b-9290-3bb68db380f3)


Debouncing
Enabled | Disabled
---- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/e1bd4701-32cf-4a9d-8963-d4ad09728ec2)|![image](https://github.com/brave/brave-browser/assets/98358127/195ff6fa-f19c-4872-94fb-5370ad9870f4)

Base64
Enabled | Disabled
---- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/90738964-5af9-4a82-800f-552e8096185d)|![image](https://github.com/brave/brave-browser/assets/98358127/de5a83c6-3d49-485c-9037-4c1efab770f8)

Regex
Enabled | Disabled
---- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/076e07a2-6484-4e76-ba35-9c3191fabcfc)|![image](https://github.com/brave/brave-browser/assets/98358127/03223a0c-81b5-4843-9b0b-4f6dbc76d068)

Regex (multi)
Enabled | Disabled
---- | ----
![image](https://github.com/brave/brave-browser/assets/98358127/d0b652ae-bd49-4ca1-b088-879b58e3bd8b)|![image](https://github.com/brave/brave-browser/assets/98358127/d888a89d-1b2a-49e3-a62a-c7c23fb455ec)

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.4
- iPad Air / iPadOS 16.7.2
Brave build: 1.64 (109)
BraveCore: 1.64.109 (123.0.6312.58)
```
Filed follow-up issue #37026
---------------------------

**STEPS:**
  1. Launch Brave
  2. Go to https://dev-pages.brave.software/navigation-tracking/debouncing.html
  3. Tap `Run` for the `Default` test case > *Verify results*
  4. Open NTP > Go to https://dev-pages.brave.software/navigation-tracking/debouncing.html
  5. Tap `Run` for the `Base64` test case > *Verify results*
  6. Open NTP > Go to https://dev-pages.brave.software/navigation-tracking/debouncing.html
  7. Tap `Run` for the `Regex` test case > *Verify results*
  8. Open NTP > Go to https://dev-pages.brave.software/navigation-tracking/debouncing.html
  9. Tap `Run` for the `Regex (multi)` test case > *Verify results*

**ACTUAL RESULTS:**
- Verified that the results are correct

---------------------------

<details>
<summary> iPhone </summary>

|Enabled|Default|Base64|Regex|Regex (multi)|
|:-:|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/e1d03929-1153-4fd0-98d5-0f49d7c48cfe) | ![2](https://github.com/brave/brave-browser/assets/128532965/780903cb-4b74-43fe-86de-dfb7504460a3) | ![3](https://github.com/brave/brave-browser/assets/128532965/521b6532-cf28-4aca-bbdc-8943f615259f) | ![4](https://github.com/brave/brave-browser/assets/128532965/83dce6b1-dc64-462c-b5c3-008ddcf0dd4f) | ![5](https://github.com/brave/brave-browser/assets/128532965/94a402a8-68e4-4820-988f-4c8a12f10ff4) |
|Disabled|Default|Base64|Regex|Regex (multi)|
| ![1](https://github.com/brave/brave-browser/assets/128532965/297314bd-5999-4a46-ae39-c5efefc4f90d) | ![2](https://github.com/brave/brave-browser/assets/128532965/6523002a-779a-4485-b208-2fe0b3576b18) | ![3](https://github.com/brave/brave-browser/assets/128532965/3e6e759b-6e54-4704-93fe-01ffd7e28092) | ![4](https://github.com/brave/brave-browser/assets/128532965/e9a91d19-9918-46b5-a4e0-a56cbc9a2d1b) | ![5](https://github.com/brave/brave-browser/assets/128532965/f50082bc-b452-4bbc-a954-1ae2c3b62f83) |
</details>

<details>
<summary> iPad </summary>

|Enabled|Default|Base64|Regex|Regex (multi)|
|:-:|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/44753058-3a78-4f45-b859-3d50c15e5c9b) | ![2](https://github.com/brave/brave-browser/assets/128532965/33c1d6ac-1dc8-438c-83ea-453c6f2577b6) | ![3](https://github.com/brave/brave-browser/assets/128532965/bd349061-8640-4d81-b344-e3d197be5d8d) | ![4](https://github.com/brave/brave-browser/assets/128532965/51da1b55-44c4-4ae3-8e52-e2fa6f4d4b6f) | ![5](https://github.com/brave/brave-browser/assets/128532965/7027c900-8a3a-4444-9265-f2c84c2f554f) |
|Disabled|Default|Base64|Regex|Regex (multi)|
| ![1](https://github.com/brave/brave-browser/assets/128532965/e556be8b-3ef3-4a19-833e-a7e0eaee431f) | ![2](https://github.com/brave/brave-browser/assets/128532965/b0cab8ad-4f9b-4055-8d14-92374bae969f) | ![3](https://github.com/brave/brave-browser/assets/128532965/86f669a8-93dc-430c-a985-7d9ef4d7aca3) | ![4](https://github.com/brave/brave-browser/assets/128532965/6afca00a-a402-4ca8-ad37-f88a64eb7498) | ![5](https://github.com/brave/brave-browser/assets/128532965/77e9ce9f-d1c1-4a72-acc5-322402f07c57) |
</details>
