### ISSUE TITLE
Entering/pasting more than character limit leaves prompt text input/editing disabled

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#33286]
## Description 

Entering/pasting more than character limit leaves prompt text input/editing disabled

## Steps to Reproduce

1. install `1.60.62`
2. launch Brave
3. restart Brave (to pick up the Griffin seed)
4. copy the [entire plain text of the Declaration of Independence](https://d32ogoqmya1dw8.cloudfront.net/files/teaching_computation/workshop_2018/activities/plain_text_version_declaration_inde.txt) (or any `2,000-character+` document)
5. paste into the `Enter a prompt here` textfield
6. (might have to press `return`, I forget)

## Actual result:

`2112/2000`

Your input text is still selectable, but it's not editable/deletable, leaving the input textfield seemingly disabled

![image](https://github.com/brave/brave-browser/assets/387249/f59a26c8-c45b-4945-a46c-24ac46ef29ec)

## Expected result:

After getting the

`2112/2000` indicator, the text in question should be editable/deletable

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave | 1.60.62 Chromium: 118.0.5993.21 (Official Build) nightly (64-bit)
-- | --
Revision | 09501c861a903b5c98cecfb3a75d9f08898f61d2
OS | Windows 10 Version 22H2 (Build 19045.3516)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A`
- Can you reproduce this issue with the beta channel? `N/A`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @bbondy @mattmcalister @petemill @nullhook @rebron @brave/qa-team

**Comment by kjozwiak** [comment]
The above requires `1.60.102` or higher for `1.60.x` verification 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.60.102 Chromium: 118.0.5993.96 (Official Build) beta (64-bit)
-- | --
Revision | 3598a9fc6b7752181feb25caa131bc386d6d054c
OS | Windows 11 Version 22H2 (Build 22621.2428)
```

Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/33286#issue-1916527677, ensured that the text field was editable once enough text was pasted to go over the `2000` character limit as per the following:

https://github.com/brave/brave-browser/assets/2602313/17574dbd-a092-4335-af35-657230c43ba4
