### ISSUE TITLE
VPN button doesn't sync with System tray icon when disconnected via System tray icon

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#33284]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/32003.  Connect/Disconnect status correctly showing when connected/disconnected via App menu.  However, when disconnected via System tray icon, VPN button shows Green and also when try to click the button, it appears freeze. 

## Steps to Reproduce

   1. Install 1.59.101
   2. launch Brave
   3. Purchase, configure & connect to Wireguard VPN
   4. Connect & Disconnect quickly via App menu (couple of times)
   5. verified VPN button, system tray and App menu shows correct connection status
   6. disconnect via system tray icon. 
   

## Actual result:

VPN button still shows connection status.  Also it appears when you try to click on VPN button, it freezes.

https://github.com/brave/brave-browser/assets/98358127/6aa81487-0e68-479d-8884-1cc34787ad77

## Expected result:
System tray icon and VPN button connection statuses should sync

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.59.101 Chromium: 117.0.5938.92 (Official Build) beta (64-bit)
-- | --
Revision | 81840f55490b042e3c7a75e0cba633580ed5a1b6
OS | Windows 11 Version 22H2 (Build 22621.2283)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:
 @spylogsster  @bsclifton 
cc: @stephendonner

**Comment by spylogsster** [comment]
Looks fixed after https://github.com/brave/brave-core/pull/20275, @MadhaviSeelam please check on your side in latest Nightly

**Comment by MadhaviSeelam** [comment]
@spylogsster appears to be working in `1.60.73`

**Comment by LaurenWags** [comment]
Closing this issue due to above comments which reference a PR and @MadhaviSeelam notes that it seems to be working for her on 1.60.x.

Leaving the `QA Pass-Win64` label off until this is officially verified on Win 10 and 11.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.60.87 Chromium: 118.0.5993.70 (Official Build) beta (64-bit)
-- | --
Revision | 854c1e600054dfca6842cebaf729f100f4b0f066
OS | Windows 11 Version 22H2 (Build 22621.2283)
```

Verified using original STR https://github.com/brave/brave-browser/issues/33284#issue-1916353492

- Confirmed VPN button connection status syncs with System tray icon when connected/disconnected via System tray icon for both Wireguard VPN and IKEv2 connections. 
- Verified connected/disconnected status for VPN button, VPN toggle via App menu & System tray icon. 

https://github.com/brave/brave-browser/assets/98358127/5316aecb-95f0-40ce-96f7-2e403b8b1a05

**Comment by stephendonner** [comment]
I went to verify this on `Windows 10` but was unable to.  I logged https://github.com/brave/brave-browser/issues/33585 instead.

@MadhaviSeelam since your case is fixed and I've logged the above issue, did we want to mark this as `QA-Pass/Win64`?

**Comment by bsclifton** [comment]
Verified on `1.60.102` (Beta) on Windows 11 (x64, 22H2, OS Build 22621.2428)

There is a bit of a pitfall though - I want to capture. Each release channel will install a separate service and tray icon. With the tray icon, basically the last one installed "wins". To test this, I had to remove Beta and reinstall it. At that point, it works beautifully.

Specifically, I did ~6 connect/disconnects using hamburger menu and then I used the system tray to disconnect and reconnect. Worked beautifully! 😄 

cc: @kjozwiak

**Comment by kjozwiak** [comment]
> Verified on `1.60.102` (Beta) on Windows 11 (x64, 22H2, OS Build 22621.2428)
> 
> There is a bit of a pitfall though - I want to capture. Each release channel will install a separate service and tray icon. With the tray icon, basically the last one installed "wins". To test this, I had to remove Beta and reinstall it. At that point, it works beautifully.
> 
> Specifically, I did ~6 connect/disconnects using hamburger menu and then I used the system tray to disconnect and reconnect. Worked beautifully! 😄
> 
> cc: @kjozwiak

Thanks @bsclifton! Really appreciate the help verifying the above. Definitely saved some time!
