### ISSUE TITLE
"Can't update Brave" notification links to Chrome webpage

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#3328]
## Description 

The `Reinstall Brave` link provided in the pop-up notification when Brave is unable to update links to a chrome webpage instead of Brave webpage (or wherever it should point to).

![image](https://user-images.githubusercontent.com/3299098/52668255-ebbe5600-2ec7-11e9-9cc5-69c5f3ea9611.png)

Reinstall link (`kDownloadChromeUrl`)points to this address:
https://www.google.com/chrome/?&brand=CHWL&utm_campaign=en&utm_source=en-et-na-us-chrome-bubble&utm_medium=et

Should point to https://brave.com/

Seems to be inherited from Chromium (cc @rebron):
https://cs.chromium.org/chromium/src/chrome/browser/ui/views/outdated_upgrade_bubble_view.cc?q=chrome-bubble&sq=package:chromium&g=0&l=36

## Brave version (brave://version info)

Release channel, v0.59.35

### Reproducible on current release: Yes - although hard to reproduce given the nature of the notification.
- Does it reproduce on brave-browser dev/beta builds? 
Unclear - but most likely
### Additional Information

User report:
https://www.reddit.com/r/brave_browser/comments/apr18g/brave_update_directs_to_google_chrome/

**Comment by rebron** [comment]
@simonhong Are we still pointing to Chrome or is this fixed per this patch? https://github.com/brave/brave-core/blob/7eafb22d839b76e6a1420b972e9709eb62c2d972/patches/chrome-browser-ui-views-outdated_upgrade_bubble_view.cc.patch

**Comment by simonhong** [comment]
@rebron That was fixed by https://github.com/brave/brave-core/pull/1318 and will be in effect from 0.61.x.
However, I'm curious about which version that users uses because there was some installer(`brave_installer.exe`) around 0.56.x I think.
Recently @jonathansampson also saw an user that has same issue from twitter advised to fix.

**Comment by simonhong** [comment]
Today, I also saw this notification with latest release (0.59.35) on Win10.
This is very strange because this dialog only should be visible when installed browser is very old.

**Comment by eljuno** [comment]
+1 from Community https://community.brave.com/t/brave-says-it-is-not-up-to-date-and-redirects-me-to-chrome/45821?u=eljuno

**Comment by rebron** [comment]
@simonhong This is fixed right, starting with 61.x? Is there a way to verify?

**Comment by simonhong** [comment]
Duplicated with https://github.com/brave/brave-browser/issues/2942.

@rebron Yup, fixed. You can test with below steps.
```
Launch browser with yarn start --simulate-outdated
Click Reinstall Brave button in launched dialog
```

**Comment by jaminroe** [comment]
This is happening again for me. `Version 0.60.48 Chromium: 72.0.3626.121 (Official Build) (64-bit)` I'm on Windows 10

**Comment by bsclifton** [comment]
@jaminroe I think the only solution for this is to go to https://brave.com/download and grab the latest version

The good news is: this shouldn't happen anymore, going forward 😄

**Comment by jaminroe** [comment]
> @jaminroe I think the only solution for this is to go to https://brave.com/download and grab the latest version
> 
> The good news is: this shouldn't happen anymore, going forward 😄

Yeah, I did that, but was worried I'd lose all my settings! 😆I didn't thankfully! Thanks!
