### ISSUE TITLE
`Summarize this page` question and its suggested followups are sometimes disabled/gray/inactive

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#33285]
## Description 

`Summarize this page` question and its suggested followups are sometimes disabled/gray/inactive

## Steps to Reproduce

1. install `1.60.62`
2. launch Brave
3. restart Brave (to pick up Griffin seed)
4. click on the `Brave Leo` icon in the sidebar
5. click `Accept and begin`
6. load various sites (I landed on `https://slate.com/technology/2023/09/sharks-survived-golf-course-17-years-what-made-them-go-away.html` when it broke) and note the state of the `Summarize this page` and associated suggested-question bubbles
7. keep going until they appear disabled (gray in `Dark` mode - should be blue)
8. try to click on the links

## Actual result:

Nothing happens

![image](https://github.com/brave/brave-browser/assets/387249/b74d8a1f-7b0b-45c9-85da-cef812cbb098)

## Expected result:

These links should be `blue`, and active

![image](https://github.com/brave/brave-browser/assets/387249/a25435ef-acdc-4b89-a6a6-22b2bbf56918)

## Reproduces how often: 

80%  (Just keep trying, eventually you'll see it)

## Brave version (brave://version info)

```
Brave | 1.60.62 Chromium: 118.0.5993.21 (Official Build) nightly (64-bit)
-- | --
Revision | 09501c861a903b5c98cecfb3a75d9f08898f61d2
OS | Windows 10 Version 22H2 (Build 19045.3516)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A`
- Can you reproduce this issue with the beta channel? `N/A`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @bbondy @mattmcalister @petemill @nullhook @brave/qa-team

**Comment by petemill** [comment]
I don't think this is an issue anymore. Or at least I'd like to know if it is. Since this issue has been reported, this logic has been rewritten.

**Comment by bbondy** [comment]
@stephendonner please close if you agree

**Comment by stephendonner** [comment]
> @stephendonner please close if you agree

Thanks, closing; I haven't yet seen this again, in the wild.
