### ISSUE TITLE
Opening a new-tab window from one with the `Brave Leo`-sidebar-panel open drops URL-bar focus

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#33299]
## Description 

Opening a new-tab window from one with the `Brave Leo`-sidebar-panel open drops URL-bar focus

## Steps to Reproduce

1. install `1.60.83`
2. launched Brave
3. press `command` + `T` to open a new-tab page
4. note the URL bar has focus (blinking caret)
5. restart Brave (to pick up Griffin seed)
6. click on now-enabled `Brave Leo` button
7. leave the sidebar panel for this tab open
8. press `command` + `T` to open a new-tab page
9. note the new-tab page opens
10. try typing

## Actual result:

Focus is _not_ set to the only input source available: the URL bar/omnibar

`Step 4` | `Brave Leo` panel open | `Focus-disabled` new-tab page
---------|----------|---------
<img width="1312" alt="Screenshot 2023-09-28 at 12 44 15 AM" src="https://github.com/brave/brave-browser/assets/387249/4ff565e3-538a-431f-b3cb-d707faa3601c"> | <img width="1312" alt="Screenshot 2023-09-28 at 12 45 52 AM" src="https://github.com/brave/brave-browser/assets/387249/242ded32-da21-41ff-81f7-95c5dab7607d"> |<img width="1312" alt="Screenshot 2023-09-28 at 12 45 49 AM" src="https://github.com/brave/brave-browser/assets/387249/852efa3b-8dff-44c3-b61b-d37c521b1b74">

## Expected result:

Focus should be set to the new-tab's URL bar/omnibar

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave | 1.60.63 Chromium: 118.0.5993.21 (Official Build) nightly (x86_64)
-- | --
Revision | 3c2401f1c61504c037363a33b8f4f1fc7423a95f
OS | macOS Version 14.1 (Build 23B5046f)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A`
- Can you reproduce this issue with the beta channel? `N/A`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @bbondy @mattmcalister @larreewong @petemill @nullhook @brave/qa-team

**Comment by kjozwiak** [comment]
The above requires `1.60.105` or higher for `1.60.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.60.106 Chromium: 119.0.6045.59 (Official Build) (x86_64)
-- | --
Revision | 16064193dde8c55f64dabd32f125c0cd9380f96a
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Followed my original steps to reproduce

## Confirmed focus is correctly set to the URL bar when opening a new-tab window

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave	1.60.106 Chromium: 119.0.6045.59 (Official Build) (64-bit) 
Revision	16064193dde8c55f64dabd32f125c0cd9380f96a
OS	Linux
```

### Followed my original steps to reproduce

## Confirmed focus is correctly set to the URL bar when opening a new-tab window

**Comment by stephendonner** [comment]
## Verified `PASSED` using


```
Brave | 1.60.106 Chromium: 119.0.6045.59 (Official Build) (64-bit)
-- | --
Revision | 16064193dde8c55f64dabd32f125c0cd9380f96a
OS | Windows 10 Version 22H2 (Build 19045.3636)
```

### Followed my original steps to reproduce

## Confirmed focus is correctly set to the URL bar when opening a new-tab window
