### ISSUE TITLE
panel shows 0% Attention but a-c table has a value for attention %

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#3329]
## Description 
Rewards Panel shows Attention as 0% when site does have an attention percentage value.

Does not occur on 0.59.35 (currently released version) or Dev 0.61.20.

## Steps to Reproduce

   1. Clean profile.
   2. Launch Brave and enable rewards.
   3. Visit some sites so you have some attention % values in auto contribute table.
   4. Visit a site where you have an attention %.
   5. Click on BAT logo.

## Actual result:
Panel shows 0% but ac table shows a value. Reproduces for YT and Twitch sites as well.
![screen shot 2019-02-12 at 4 27 43 pm](https://user-images.githubusercontent.com/28145373/52669108-4add9400-2ee3-11e9-8ffc-a5b4f28150ec.png)

## Expected result:
Panel should show value from a-c table (this is from 0.59.35):
![screen shot 2019-02-12 at 4 30 20 pm](https://user-images.githubusercontent.com/28145373/52669299-ba538380-2ee3-11e9-8142-8b0dac71198e.png)

![screen shot 2019-02-12 at 4 30 41 pm](https://user-images.githubusercontent.com/28145373/52669305-bde70a80-2ee3-11e9-8123-350a58487d62.png)

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.60.26 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Mac OS X

### Reproducible on current release: no, not on 0.59.35
- Does it reproduce on brave-browser dev/beta builds? beta yes, dev (0.61.20) no.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
cc @brave/legacy_qa @NejcZdovc

**Comment by NejcZdovc** [comment]
@LaurenWags this one should be fixed with https://github.com/brave/brave-core/pull/1642

**Comment by NejcZdovc** [comment]
fixed with https://github.com/brave/brave-core/pull/1642

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.60.40 Chromium: 72.0.3626.109 (Official Build) (64-bit)
-- | --
Revision | fae8db7ab9280fa6704a59980263c804f809ebd5-refs/branch-heads/3626@{#857}
OS | Windows 7

Verified STR from the description.
![image](https://user-images.githubusercontent.com/34715963/52982163-cf00b180-33e4-11e9-8288-99359689fa26.png)
![image](https://user-images.githubusercontent.com/34715963/52982178-d922b000-33e4-11e9-82bb-7b7de55fd554.png)

Logged https://github.com/brave/brave-browser/issues/3409
