### ISSUE TITLE
Edit NFT doesn't update the NFT

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#33306]
## Description 

Edit NFT doesn't update the NFT

## Steps to Reproduce

   1. Restore wallet with NFT
   2. Edit NFT value (token ID)
   3. Save changes
   4. Doesn't update the NFT to new value

## Actual result:

Edit NFT doesn't update the NFT

## Expected result:
Edit NFT should update the NFT

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.60.63 Chromium: 118.0.5993.21 (Official Build) nightly (64-bit)
-- | --
Revision | 3c2401f1c61504c037363a33b8f4f1fc7423a95f
OS | Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @muliswilliam @HEagle18

**Comment by kjozwiak** [comment]
The above requires `1.69.123` or higher for `1.69.x` verification 👍

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/39921#issuecomment-2250172192
