### ISSUE TITLE
Portfolio filter is broken on nightly

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#33301]
## Description 

Portfolio filter is broken on nightly

## Steps to Reproduce

   1. Open Portfolio
   2. Select filters and select a single network and save
   3. Doesn't show any assets
   4. Open filter again, selected network is unchecked

## Actual result:

https://github.com/brave/brave-browser/assets/17010094/465271e3-c34a-4770-8d97-9a3688937341

## Expected result:
Should filter networks and show assets 

## Brave version (brave://version info)

<html>
<body>

Brave | 1.60.63 Chromium: 118.0.5993.21 (Official Build) nightly (64-bit)
-- | --
Revision | 3c2401f1c61504c037363a33b8f4f1fc7423a95f
OS | Linux

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel @josheleonard @muliswilliam

**Comment by muliswilliam** [comment]
@srirambv I have confirmed this bug exists in `1.60.63`. On the latest master `1.60.72`, the filter is working as expected. Please test and confirm if we can close this issue. See video below:


https://github.com/brave/brave-browser/assets/48117473/b48698d1-b74f-43f0-9c84-8d86bd956af9

**Comment by josheleonard** [comment]
Closing as this is currently working
