### ISSUE TITLE
Improve items spacing and padding in Browser menus

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#33315]
## Description 

We need to adjust the spacing, padding and general sizing of the items in the browser menues so they can adopt the icons a bit better. That includes updating the spacing between icon and text too.

https://www.figma.com/file/H11ZOl6JMYbCTW4ZJXqR5V/%F0%9F%A6%81-Browser?type=design&node-id=229%3A18699&mode=design&t=OcyBfbSXBnCF3DfD-1

## Actual result:

<img width="300" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/54367360-2931-4d94-ad19-fbb53fcd5c1a">

## Expected result:
<img width="384" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/0c2c3bc5-f876-40f2-993d-de54e194ebee">

**Comment by rebron** [comment]
cc: @fallaciousreasoning @simonhong

**Comment by fallaciousreasoning** [comment]
I've started on this, but no promises on how quick I'm going to be, I suddenly got super busy :laughing:

**Comment by stephendonner** [comment]
Setting to `QA/Test-All-Platforms`, as this should be a quick check to make sure there are no surprises.

**Comment by Coffeeling** [comment]
Can we get a compact mode or something? Feels like many things in the UI are getting a ton of padding, and I at least prefer compact context menus, address bars, and tab lists over the amounts of padding that are presently in Nightly.

The new context menus especially are just disturbingly giant, and feel largely unnecessary when on the desktop and using a mouse. The initial no-design prototype Sangwoo threw up for Vertical Tabs in the beginning was delightful because it was so dense and would let me have a really nice overview of my tabs. Now Brave's vertical tabs are less dense than Edge's, nevermind coming close to the information density of the original prototype.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.62.56 Chromium: 119.0.6045.163 (Official Build) nightly (x86_64)
-- | --
Revision | 79218385332970e2282a9cb36c629b933b4e763a
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Shared Steps:
1. installed `1.62.56`
2. launched Brave
3. opened the various top-level and flyout menus noted
4. compared to `1.60.118`

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.62.94 Chromium: 120.0.6099.35 (Official Build) beta (64-bit)
-- | --
Revision | e0c8a0307f7aad8a0f79a5540dccc57d561daf8a
OS | Windows 11 Version 22H2 (Build 22621.2715)
```
## Confirmed:
### * vertical height/padding looks the same
### * more horizontal space/padding between the icon on the left and its menu-container's border

### Shared Steps:
<details>

1. installed `1.62.94`
2. launched Brave
3. opened the various top-level and flyout menus noted below
4. examined the vertical and horizontal spacing between menus' UI elements
5. compared to `1.60.125`

</details>

## Top-level menu - `PASSED`
<details>

1.60.125 | 1.62.94
---- | -----
![image](https://github.com/brave/brave-browser/assets/98358127/815c0532-5dec-404f-a57b-d964b2932042)|![image](https://github.com/brave/brave-browser/assets/98358127/c94eb04e-e0ea-401c-b882-e23c04e3d72d)
</details>

## `History` - `PASSED`
<details>

1.60.125 | 1.62.94
---- | -----
<img width="955" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/66d8add6-9e6d-4090-a587-0d2afa42e811">|<img width="967" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/bb55b625-177f-40d1-b61f-a4ce7fe87da0">
<img width="957" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/b42a1d61-7c39-4da0-a93a-1d4604eeb961">|<img width="958" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/b2f5daa4-adbd-4a7b-9246-fbfcaa1d88c9">
</details>

## `Bookmarks` - `PASSED`
<details>

1.60.125 | 1.62.94
---- | -----
<img width="956" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/38de90ff-273c-43f3-8dc7-2014d186b517">|<img width="956" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/fa297968-8f58-41d9-9016-ef7b51f1bb0b">
<img width="949" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/6f74e509-2845-4c5c-8118-7a0812205d2e">|<img width="962" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/99127d73-ef10-491c-8e31-cdb14954739c">
</details>

## `More Tools` - `PASSED`
<details>

1.60.125 | 1.62.94
---- | -----
<img width="407" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/a4b8347c-eed2-4e78-bb1b-82f904d55590">|<img width="391" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/94f9066f-5a30-41d7-8579-b36b1ec7764f">

</details>

## `Help` - `PASSED`

1.60.125 | 1.62.94
---- | -----
<img width="319" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/92af77b5-2efd-46ed-a1e9-59e2c92ab05d">|<img width="357" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/fa6a1051-3c5d-4ce2-9e58-26a6609877e6">
</details>

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.62.112 Chromium: 120.0.6099.115 (Official Build) beta (64-bit) 
Revision	ae1e179b9884b2de2f4ba0bdea7da3beaad93ffa
OS	Linux
```
