### ISSUE TITLE
Autofill decimals, symbol, name when adding ERC20 tokens

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#33314]
Query the ERC20 contract to extract the decimals, symbol, and name, and autofill the details when adding a new token.

Blocked by: https://github.com/brave/brave-browser/issues/33162

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.63.155 Chromium: 122.0.6261.29 (Official Build) (64-bit)
-- | --
Revision | b2be2c6f5b7340629f672ce706f5bfd62b113f82
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from [brave/brave-core#21191](https://github.com/brave/brave-core/pull/21191)
- Verified adding ERC20 tokens auto-populates Name, Symbol and decimal fields
- Verified able to Edit and existing NFT and works as expected
- Encountered [#36195](https://github.com/brave/brave-browser/issues/36195), [#36196](https://github.com/brave/brave-browser/issues/36196) & [#36197](https://github.com/brave/brave-browser/issues/36197)

https://github.com/brave/brave-browser/assets/17010094/6a4493b9-67a8-4134-a260-bef14ee4cfb3
