### ISSUE TITLE
[PSST] Component and script injection logic

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#33319]
We'll need changes brave-core side for the new PSST component which will include a bunch of script files and site-to-script mappings. Also, we will need a tab helper to inject those scripts for specified sites.

Also add feature flag which is default OFF (will be switched on via Griffin).

[Spec](https://docs.google.com/document/d/1ccnBWBV_KkknZpZYxcOXTwtfIiaSzeLS5dMd08N2pbs/edit#heading=h.67sluvgr97jn).

**Comment by bridiver** [comment]
Please add link to the spec and also specify any feature flag and default state. How/when are we planning to do QA?

**Comment by ShivanKaul** [comment]
Added spec and flag. I don't think this needs separate QA, it should be QAed when the rest of the feature is in place, which is why I marked this as `dev-concern`.
