### ISSUE TITLE
Golfnow.com blocks login forms due to Googletagmanager 

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#3331]
## Description 

Brave blocks users from authenticating into goflnow.com (and likely other sites) due to the `Googletagmanager` present on the forms iframe.

Lowering Shields will allow the site to function and for users to authenticate in but also opens them up to tracking.

## Steps to Reproduce

   1. Visit goflnow.com
   2. Click `Login` even if you don't have an account
   3. Try and find the hidden form fields

## Actual result:

Shields blocks form fields from being displayed

## Expected result:
Should be able to authenticate into site without being tracked.

## Reproduces how often: 

Always

## Brave version (brave://version info)

v0.59.35

### Reproducible on current release: Yes
- Does it reproduce on brave-browser dev/beta builds? Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields?  Yes
- Is the issue reproducible on the latest version of Chrome? No

### Additional Information

Screenshot and user report:
![image](https://user-images.githubusercontent.com/3299098/52674734-5cba3980-2ed9-11e9-9dde-45b5762c38fe.png)
https://community.brave.com/t/golfnow-no-longer-able-to-log-in/44876/3

**Comment by lukemulks** [comment]
+1
Confirm that it appears GTM being blocked is preventing the user from authenticating in Brave (repro'd on win10 x64)

**Comment by ryanbr** [comment]
@lukemulks @Brave-Matt is this still occuring? I Couldn't see it from my end

**Comment by ryanbr** [comment]
Signed up, and re-tested before closing. Tested the login/logout process too. everything working well. Login window shows up in Brave Release.
