### ISSUE TITLE
Bottom bar doesn't always hide when scrolling through the tokens

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#33312]
## Description 
Bottom bar doesn't always hide when scrolling through the tokens

## Steps to reproduce 

   1. Open portfolio 
   2. Scroll through the tokens
   3. Sometimes the bottom bar doesn't auto-hide

## Actual result 

https://github.com/brave/brave-browser/assets/17010094/e3904706-ccee-4ff0-8f15-3d756bba0dc2

## Expected result
Always scrolling through tokens should hide the bottom bar

## Issue reproduces how often 
Intermittent

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Tablet
   - Android version: 12
   
## Brave version
1.59.93 x64 Beta build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @simoarpe

**Comment by simoarpe** [comment]
Issue not relevant anymore as we switched to WebUI where bottom navigation bar is always kept visible. I'm closing this.
