### ISSUE TITLE
Brave - Address bar missing in full screen mode

### ISSUE THREAD

**Issue by bilaharipg** [brave/brave-browser#33329]
## Description 
The latest version of Brave browser on Mac OS has some full-screen issues. When using the browser in full-screen mode the address bar disappeared and unable to access it.

## Steps to Reproduce

   1. Update Brave to the latest version on Mac OS (Version 1.58.135 Chromium: 117.0.5938.140).
   2. Put the browser in full-screen mode.
   3. The Address bar goes missing and is unable to be accessed even with shortcuts (Command + L)

## Brave version (brave://version info)

Version 1.58.135 Chromium: 117.0.5938.140 (Official Build) (arm64)

## Version/Channel Information:

- Can you reproduce this issue with the current release?  Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:
<img width="1440" alt="Screenshot 2023-09-29 at 18 51 04" src="https://github.com/brave/brave-browser/assets/64525386/3d1fddc9-890f-4789-aad4-f5f8609ae0d4">

**Comment by rebron** [comment]
@bilaharipg In the View menu, do you have `Always Show Toolbar in Full Screen` selected.

**Comment by bilaharipg** [comment]
> @bilaharipg In the View menu, do you have `Always Show Toolbar in Full Screen` selected.

Thank you. Now it is working as before.
