### ISSUE TITLE
Unable to scroll opt-in agreement inner text up

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#33320]
## Description 

Unable to scroll opt-in agreement inner text up

## Steps to reproduce 

1. install `1.60.65`
2. launch Brave
3. open `brave://flags`
4. tap to set Brave AI chat to `Enabled`
5. tap to `Relaunch` Brave
6. tap on the app menu
7. tap on `Brave Leo`
8. try to tap and read the beginning of the inner opt-in text

## Actual result 

Unable to tap + hold to scroll the text `UP` in the clipped viewport (but I can swipe `DOWN` LOL)

https://github.com/brave/brave-browser/assets/387249/1d8abbe4-111b-4b53-b850-cbbd020cdde7

## Expected result

Should be able to tap and scroll that inner text

## Issue reproduces how often 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? `N/A`
- Can you reproduce this issue with the current Play Store Beta version? `N/A`
- Can you reproduce this issue with the current Play Store Nightly version? `Yes`

## Device details
   - Install type (ARM, x86): `arm64`
   - Device type (Phone, Tablet, Phablet): `Google Pixel XL`
   - Android version: `Android 9.0`
   
## Brave version

`1.60.65`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc @bbondy @mattmcalister @vlad-hoff @kjozwiak @srirambv

**Comment by stephendonner** [comment]
This issue doesn't reproduce any longer using

```
Brave	1.64.12 Chromium: 121.0.6167.75 (Official Build) canary (32-bit) 
Revision	fd767e458bb4d51a01353163774bb73fd6bc7e0d
OS	Android 9; Build/PQ2A.190305.002; 28; REL
```


https://github.com/brave/brave-browser/assets/387249/7f300117-cf5c-444c-aed1-767a3401d69d

**Comment by nullhook** [comment]
this should be updated as we're using a modal from nala @stephendonner
