### ISSUE TITLE
Text in URL bar is not highlighted when focused [CR118]

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#33333]
## Description 
Text in URL bar is not highlighted when focused, regression in Chromium 118

## Steps to reproduce 

   1. Open website
   2. Tap on the URL bar
   3. Observe

## Actual result 
![Screenshot 2023-09-29 at 11 52 19 AM](https://github.com/brave/brave-browser/assets/17885425/1129ec51-f705-49a2-8148-65e7a444a0a4)

## Expected result
![Screenshot 2023-09-29 at 11 55 41 AM](https://github.com/brave/brave-browser/assets/17885425/cd8e2710-e60a-4332-94b2-550dc742061e)

## Issue reproduces how often 
Always

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? TBD 
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Samsung GS 21
   - Android version: 13
   
## Brave version
`1.60.64, Chromium 118.0.5593.21`

**Comment by kjozwiak** [comment]
The above requires `1.59.112` or higher for `1.59.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 [panther_beta-user 14 U1B1.230908.003 release-keys]
Brave build: 1.59.112
Chromium: 118.0.5993.54 (Official Build) (64-bit) 
Revision: 967f25f295938c64c24e2e6a1790470668757655
```
---------------------------

**STEPS:**
Followed the steps from https://github.com/brave/brave-browser/issues/33333#issue-1919564277

**ACTUAL RESULTS:**
- Verified that the text in the URL bar is highlighted when tapping on it

---------------------------

https://github.com/brave/brave-browser/assets/128532965/4d566a29-8e2c-46e2-a78e-7877d0ac1753
