### ISSUE TITLE
Browser tab becomes unresponsive after completing Leo Premium purchase

### ISSUE THREAD

**Issue by nvonpentz** [brave/brave-browser#33339]
It also happens every time a user refreshes their subscription on account.brave.com.

**Comment by stephendonner** [comment]
https://github.com/brave/brave-browser/assets/387249/9cd4f076-6ac0-415d-8a72-620f5007c480

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.60.79 Chromium: 118.0.5993.32 (Official Build) nightly (64-bit)
-- | --
Revision | 95cf2d4e2e2855bd58fe8002ccd32e3d673abafd
OS | Windows 10 Version 22H2 (Build 19045.3516)
```

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.60.81 Chromium: 118.0.5993.54 (Official Build) beta (x86_64)
-- | --
Revision | 1efb3f333eb41cc34af46ca31fb33c30e0afbfae
OS | macOS Version 11.7.10 (Build 20G1427)
```

## New account - `PENDING`

## Subscription refresh - `PENDING`

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.60.87 Chromium: 118.0.5993.70 (Official Build) beta (64-bit)
-- | --
Revision | 854c1e600054dfca6842cebaf729f100f4b0f066
OS | Linux
```

1. installed `1.60.87`
2. launched Brave
3. set `brave://flags/#brave-ai-chat` to `Enabled`
4. clicked `Relaunch`
5. loaded `account.bravesoftware.com`
6. logged in using `issue33339@mailinator.com`
7. purchased Brave Leo

### Confirmed I could purchase `Brave Leo` without hanging/locking up Brave, using `account.bravesoftware.com`
