### ISSUE TITLE
Claim grant not always shown in rewards settings

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#3333]
## Steps to Reproduce

   1. Clean install
   2. Enable rewards through Brave Panel
   3. Go to Brave settings through hamburger menu

## Actual result:

Claim grant is not shown in rewards settings page
![image](https://user-images.githubusercontent.com/34715963/52681141-24e3de00-2f3b-11e9-8d61-efaec8626b99.png)

Note: reload the page to show Claim grant modal

![claim grant 2](https://user-images.githubusercontent.com/34715963/52681254-7d1ae000-2f3b-11e9-8ac5-0394c7654580.gif)

## Expected result:
Claim grant is shown in rewards settings page

## Reproduces how often: 

Intermittent issue

## Brave version (brave://version info)

Brave | 0.60.26 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Linux

cc @brave/legacy_qa @NejcZdovc

**Comment by LaurenWags** [comment]
I can reproduce fairly reliably with the following STR:
Launch Brave with clean profile.
Click on BAT logo.
Click on Join Rewards
Click elsewhere before you see the summary panel. (while wallet is being created)
Open a tab and navigate to brave://rewards
No message about grant is shown. No grant notification on panel.
Refresh page. 
Grant message shown on brave://rewards and notification shown on panel.

Brave | 0.60.28 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Mac OS X

**Comment by kjozwiak** [comment]
@LaurenWags @btlechowski is this a `0.60.x` regression? Reproducible under `0.59.35`?

**Comment by btlechowski** [comment]
Not a regression. Reproduced on 

Brave | 0.59.35 Chromium: 72.0.3626.81 (Official Build) (64-bit)
-- | --
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS | Windows 7

**Comment by NejcZdovc** [comment]
closing as this is working for me on 1.9.x
