### ISSUE TITLE
Formatting bug on Market tab on Panel

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-browser#33331]
## Description 

See Screenshots. Text is cut off.
![Screenshot 2023-09-29 at 17 51 37](https://github.com/brave/brave-browser/assets/12224304/b146bbfa-441c-4580-a6f6-7894e23a6962)
 
 See Price off bitcoin on the list
 Market cap on asset list

## Steps to Reproduce

   1. 
   2. 
   3. 

## Actual result:

![Screenshot 2023-09-29 at 17 51 29](https://github.com/brave/brave-browser/assets/12224304/311418bc-ee6c-4f42-a7f1-9d3378c5b8d6)

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.60.81 Chromium: 118.0.5993.54 (Official Build) beta (64-bit)
-- | --
Revision | `1efb3f333eb41cc34af46ca31fb33c30e0afbfae`
OS | Windows 11 Version 22H2 (Build 22621.2283)

- Verified steps from [brave/brave-core#20359](https://github.com/brave/brave-core/pull/20359)
- Verified Market tab is properly formatted in panel
- Verified token details are shown correctly in Market tab in panel

![brave_vScNKWqbdL](https://github.com/brave/brave-browser/assets/17010094/a25d0792-70e1-47cb-b388-2e6d889db394) | ![brave_z9Fc5gpif5](https://github.com/brave/brave-browser/assets/17010094/a97aec06-7159-4437-8b39-358b76dd94d4)
-- | --

---------------------

**Verification passed on**

Brave | 1.60.81 Chromium: 118.0.5993.54 (Official Build) beta (64-bit)
-- | --
Revision | `1efb3f333eb41cc34af46ca31fb33c30e0afbfae`
OS | Linux

- Verified steps from [brave/brave-core#20359](https://github.com/brave/brave-core/pull/20359)
- Verified Market tab is properly formatted in panel
- Verified token details are shown correctly in Market tab in panel

![Market_Token](https://github.com/brave/brave-browser/assets/17010094/4814cc03-f0a5-4cf3-bb4a-9b24460d3b80) | ![Market_Token1](https://github.com/brave/brave-browser/assets/17010094/95d94c61-150b-4dec-998f-7728d2e29503)
-- | --

---------------------

**Verification passed on**

Brave | 1.60.81 Chromium: 118.0.5993.54 (Official Build) beta (arm64)
-- | --
Revision | `1efb3f333eb41cc34af46ca31fb33c30e0afbfae`
OS | macOS Version 14.0 (Build 23A344)

- Verified steps from [brave/brave-core#20359](https://github.com/brave/brave-core/pull/20359)
- Verified Market tab is properly formatted in panel
- Verified token details are shown correctly in Market tab in panel

![image](https://github.com/brave/brave-browser/assets/17010094/dfc35fdb-31e3-4a73-b06f-bbc353234e5b) | ![image](https://github.com/brave/brave-browser/assets/17010094/12924167-6eb8-4b45-aca1-7533a19c4478)
-- | --
