### ISSUE TITLE
Integrate Ankr for querying balances and asset discovery

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#33330]
Add [`ankr_getAccountBalance`](https://api-docs.ankr.com/reference/post_ankr-getaccountbalance-1) method to `JsonRpcService` for efficiently querying balances of multiple chains in one HTTP request.

Nice to have - integrate the same in `AssetDiscoveryService`.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.62.128 Chromium: 120.0.6099.144 (Official Build) beta (64-bit)
-- | --
Revision | 41f5844c06c7db1017f39b5b6dc9ba81a6b1b9d6

- Verified steps from [brave/brave-core#20342](https://github.com/brave/brave-core/pull/20342)
- Verified balance query works as expected without any regressions
- Verified Portfolio view by `None`/`Account`/`Network` all work as expected and balance is fetched correctly
- Verified Account view works as expected and balance is fetched correctly
- Verified Token view works as expected and balance is fetched correctly
- Verified Send token view loads balances correctly
- Verified Swap token view loads balances correctly

https://github.com/brave/brave-browser/assets/17010094/4fe261d2-f2ec-46c5-b43d-3614264a5953
