### ISSUE TITLE
Send Constellation P3A metrics before epoch expiry

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#33359]
Currently, Constellation metrics are sent after measurement's epoch expires. They should be sent immediately so we can receive data from new users, as well as infrequent users.

Spec discussed on Slack.

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.61.61 Chromium: 119.0.6045.105 (Official Build) beta (64-bit)
-- | --
Revision | 6bbedb0b809f83b08334ffa36b1ea9df92e86245
OS | Windows 10 Version 22H2 (Build 19045.3570)

```

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.61.83`
