### ISSUE TITLE
Redirect Buy and Swap in panel to full page view

### ISSUE THREAD

**Issue by muliswilliam** [brave/brave-browser#33353]
Currently Buy and Swap pages  for panel view are not ready. In the meantime, we need to redirect users to full page view until these pages are ready.

## Test Plan
- Open wallet panel
- Click on Buy action
- It should open buy page in full wallet page
- Repeat the same action for swap.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.59.112 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | 967f25f295938c64c24e2e6a1790470668757655
OS | Linux

- Verified steps from [brave/brave-core#20350](https://github.com/brave/brave-core/pull/20350)
- Verified Buy & Swap from panel opens a new tab and loads the specific routes in full page view

https://github.com/brave/brave-browser/assets/17010094/4da3ee2a-f4d6-4b97-b0e3-2488480b53a7
