### ISSUE TITLE
Tipping panel view not showing on some YouTube channels

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#3335]
**Issue:** Tipping panel not showing on some YouTube channels when they should be. Tipping interface only shows "Rewards Summary" view.

**Platform:** MacOS, `0.59.35`. 

**Reproduce:** Navigate to https://www.youtube.com/watch?v=9y2EvgxxMXc, and open the tipping panel. 

![image](https://user-images.githubusercontent.com/11497541/52689665-3ca07e00-2f9e-11e9-9e0d-ea686c9046d2.png)
_Should show tipping view._

**Notes:** Early suspicions are that this related to localization, as this channel is in Korean.

**Comment by jasonrsadler** [comment]
@Miyayes @NejcZdovc 

This publisher has turned off embedding for all of their videos. We cannot get the publisher information when they have this turned off. 

Go to:
`https://www.youtube.com/oembed?format=json&url=https://www.youtube.com/watch?v=9y2EvgxxMXc` and you will see Unauthorized. Other videos that have embedding enabled you can plug in to see the json results using `https://www.youtube.com/oembed?format=json&url=` + the entire video url.

The panel shows the publisher on their channel page.

**Comment by jasonrsadler** [comment]
@NejcZdovc How should we handle the panel for publisher videos that have embedding disabled?

**Comment by NejcZdovc** [comment]
@jasonrsadler if we get 401 let's get info from the page

**Comment by rebron** [comment]
@NejcZdovc Does this need to be uplifted to 62.x, make the appropriate PR and tag us again please.

**Comment by NejcZdovc** [comment]
@rebron we have uplift for 0.63 https://github.com/brave/brave-core/pull/2092

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.63.30 Chromium: 73.0.3683.75 (Official Build) beta (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17134.523

Used test plan from https://github.com/brave/brave-core/pull/1756

**Comment by GeetaSarvadnya** [comment]
The issue is still reproducible for a few YT videos. When we video is opened in a new tab, pubs info will not be shown in BR panel.
https://www.youtube.com/channel/UCU_JoWTHBXzbfEByl5GahYg
https://www.youtube.com/channel/UC6uj6iimYkg4f1lpc7BItoA

https://drive.google.com/open?id=1mWcZnwy3z0mmk0id8Wj6cOBFpzCkErxa

Brave | 0.63.31 Chromium: 73.0.3683.75 (Official Build) beta (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Linux

**Comment by jasonrsadler** [comment]
@NejcZdovc I'm on latest master and no media publishers are showing for me (youtube or twitch).

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.63.42 Chromium: 74.0.3729.75 (Official Build) beta(64-bit)
-- | --
Revision | fdb7915642fef8cf997beac2554709d148e3c187-refs/branch-heads/3729@{#754}
OS | Ubuntu 18.04 LTS

Used test plan from https://github.com/brave/brave-core/pull/1756 and https://github.com/brave/brave-browser/issues/3335#issuecomment-480575488
