### ISSUE TITLE
Account Icons lost Border Radius

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#33362]
## Description 

The `Account` icons are missing their `border-radius`

## Steps to Reproduce

   1. Open the Wallet
   2. Anywhere the `Account` icon is shown, it is missing it's `border-radius`

## Actual result:

![Screenshot 26](https://github.com/brave/brave-browser/assets/40611140/a615ed77-72eb-43d6-bf42-05353ffd93cc)

## Expected result:

![Screenshot 27](https://github.com/brave/brave-browser/assets/40611140/cc686e43-bf3f-4a4c-8321-7473eeb0355e)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.59.111` or higher for `1.59.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.59.112 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | 967f25f295938c64c24e2e6a1790470668757655
OS | Windows 11 Version 22H2 (Build 22621.2283)

- Verified steps from issue description
- Verified accounts have border radius on both accounts tab and panel
![brave_5lDjlyKEjQ](https://github.com/brave/brave-browser/assets/17010094/97c2e1c1-d034-4361-91c7-b7fd4a40dfeb)
