### ISSUE TITLE
Feature Request: Add Chromium "Tab to Search" feature

### ISSUE THREAD

**Issue by mickdekkers** [brave/brave-browser#3337]
Note: this feature request was originally posted by @eljuno at brave/browser-laptop#10675. I'm posting it here since that repo and its issues have been archived.

---

- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
From community https://community.brave.com/t/implement-the-open-search-client-specification-like-chromiums-tab-to-search-feature/6677?u=eljuno

On Chrome, after you visit a website that adheres to the open search standard, Chrome enables this feature where:
a. You begin typing the domain name
b. It suggests a domain completion
c. You hit Tab and it scopes the search to within that domain (like “Search on en.wikipedia.org:”)
![image](https://user-images.githubusercontent.com/25360853/29753342-d3e8aec2-8b99-11e7-942e-891b42dbaaad.png)
d. You type the search term and hit Enter, and it takes you to that website’s search results page (not the default search engine’s)

>Engine Go Key is a good solution for the most common websites, but it requires manually adding new ones, remembering the key combination, and misses some other benefits of the Open Search specification like autocomplete.
>
>IE, Firefox, and Chrome all adopt the standard, and well as 200,000+ websites, including most if not all the ones listed in the default Engine Go Key settings.
>
>I do think Engine Go Keys and Open Search are complementary though, so not advocating for one to take the other’s place, but for Open Search to be considered as a future enhancement alongside EGKs.

Here are the relevant references:
a. Details about Chromium’s Tab to Search feature https://www.chromium.org/tab-to-search
b. Open Search FAQ and specification http://www.opensearch.org/Documentation/Frequently_asked_questions

- Screenshot if needed:
Here's the record how this feature work in Chrome
![chrome-tab-to-search](https://user-images.githubusercontent.com/25360853/29753427-6c4df720-8b9b-11e7-9a14-5413a62124c8.gif)

**Comment by eljuno** [comment]
This feature already available with the new Brave 0.59.x and higher. 🙂

**Comment by mickdekkers** [comment]
@eljuno ah, my bad. Great! You're right, I think I was confused because when I type "wikipedia" in the omnibar after visiting [en.wikipedia.org](https://en.wikipedia.org), it doesn't actually list "en.wikipedia.org" in the results and so tab-to-search is not available. (The results only contain a Google search for "wikipedia" and various wikipedia pages I've visited.) It does actually work when I type "en.wikipedia.org" in the omnibar. I checked, and Chrome behaves the same. 🙂

**Comment by CaptJakk** [comment]
Looks like this feature was removed, or turned off by default. How do I reenable it?

**Comment by rebron** [comment]
@CaptJakk You have to visit en.wikipedia.org I believe and if you type in en.wikipedia.org and tab it should show the tab search option. Can also see it working on ebay.com and typing ebay.com and tab.

**Comment by MVrachev** [comment]
@eljuno do you have access to that feature yet?
What about Brave for MAC is this feature existing there?

**Comment by MVrachev** [comment]
> Looks like this feature was removed, or turned off by default. How do I reenable it?

I found it! 
On macOS Mojave with Brave version `0.67.124` you should enable that option
![image](https://user-images.githubusercontent.com/16246778/63262989-17afff00-c290-11e9-9b7b-d668033c50c1.png)
