### ISSUE TITLE
Scripts shows blocked on shields but shows 307 redirect on console

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#3338]
## Description 

Scripts shows blocked on shields but shows 307 redirect on console

## Steps to Reproduce

   1. Visit mixer.com and play any video
   2. Check shields shows scripts from web.vortex.data.microsoft.com as blocked
   3. Check network tab, shows the same script as 307 redirects and not blocked

## Actual result:

Chrome with uBO
![screenshot from 2019-02-13 11-26-46](https://user-images.githubusercontent.com/17010094/52691347-a01eb180-2f86-11e9-9b99-9da2dace4e84.png)
Brave Shields
![screenshot from 2019-02-13 11-45-43](https://user-images.githubusercontent.com/17010094/52691361-a745bf80-2f86-11e9-83d2-e0b6a8f0514c.png)
Brave Network tab
![screenshot from 2019-02-13 11-29-35](https://user-images.githubusercontent.com/17010094/52691385-b2005480-2f86-11e9-89f2-a9f748dfe6f8.png)

## Expected result:
Should be same as Chrome with uBO

## Reproduces how often: 

Easy

## Brave version (brave://version info)

All

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

Issue reported on community https://community.brave.com/t/is-brave-really-blocking-ads-and-tackers-on-mixer-com-or-now-just-partially/44768

**Comment by bbondy** [comment]
This is working as expected, it used to show 307 and now 200. But the content is still replaced.  The devtools should show what's actually going on with network traffic which it does.
