### ISSUE TITLE
no icon for "Don't allow sites to connect to HID devices"

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#33380]
## Description 

The "Don't allow sites to connect to HID devices" option does not have an icon in 1.59.x, it does in 1.58.x.

## Steps to Reproduce

   1. Navigate to brave://settings/content/hidDevices 

## Actual result:

<img width="1179" alt="1 59" src="https://github.com/brave/brave-browser/assets/28145373/25b5869e-277c-47b1-95bd-ab659c2386de">

## Expected result:

Setting should have an icon as it does in 1.58.x, although likely a different one than below.

<img width="1182" alt="1 58" src="https://github.com/brave/brave-browser/assets/28145373/4e065ec5-bd18-4169-88d2-c2c9bee3996f">

## Reproduces how often: 

easily

## Brave version (brave://version info)

```
Brave | 1.59.109 Chromium: 118.0.5993.21 (Official Build) beta (x86_64)
-- | --
Revision | aacb6a6f8bd916bd49f064b2137b007fa6c47b51
OS | macOS Version 13.6 (Build 22G120)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 1.58.x no
- Can you reproduce this issue with the beta channel? 1.59.x yes
- Can you reproduce this issue with the nightly channel? 1.60.x yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron

**Comment by rebron** [comment]
cc: @aguscruiz

**Comment by aguscruiz** [comment]
@fallaciousreasoning we have this as `sparkles-off` in Nala

**Comment by MadhaviSeelam** [comment]
Reproduced the issue in Linux & Windows 11.

**Comment by kjozwiak** [comment]
The above requires `1.59.116` or higher for `1.59.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.59.116 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | 90abf7b54063101d6494b361dcadeea7c9a4b366
OS | Windows 11 Version 22H2 (Build 22621.2283)
```

Verified using original STR from https://github.com/brave/brave-browser/issues/33380#issue-1924365685

- Confirmed the icon is shown for `Don't allow sites to connect to HID devices` 
- Confirmed the icon matches to the screenshot in https://github.com/brave/brave-core/pull/20449#issue-1932078049

![image](https://github.com/brave/brave-browser/assets/98358127/767dd6cc-d605-493e-92cc-85fb01e413b3)

**Comment by fallaciousreasoning** [comment]
Thanks for looking at this so quickly @MadhaviSeelam!
