### ISSUE TITLE
Prevent transfers to addresses on the OFAC SDN list

### ISSUE THREAD

**Issue by nvonpentz** [brave/brave-browser#33387]
Currently handled by our RPC provider, we should also do this client side. We should cover
* Standard transfers where the to_address is on the block list
* Common smart contract calls in which the to address is a (non-blocked) smart contract address, but a blocked address would receive value, e.g. erc20::Transfer.

Related to https://github.com/brave/token-lists/pull/81

**Comment by LaurenWags** [comment]
@nvonpentz could you add the appropriate QA label (`QA/Yes` or `QA/No`) and the appropriate release notes label (`release-notes/exclude` or `release-notes/include`) for this one? Thanks!

cc @srirambv @kjozwiak @rebron

**Comment by nvonpentz** [comment]
@LaurenWags Updated!

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.61.61 Chromium: 119.0.6045.105 (Official Build) beta (64-bit)
-- | --
Revision | 6bbedb0b809f83b08334ffa36b1ea9df92e86245
OS | Windows 11 Version 22H2 (Build 22621.2506)

- Verified steps from [brave/brave-core#20375](https://github.com/brave/brave-core/pull/20375)
- Verified unable to submit a Send transaction for addresses listed in OFAC SDN List

https://github.com/brave/brave-browser/assets/17010094/7c08461d-3e9e-49c1-a7b3-ff45fc07268a
