### ISSUE TITLE
Add a "manual refresh" button to fetch a new version of the verified publishers list, on demand

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#3339]
### Description and motivation for feature request

 At the moment, the browser updates the verified `publishers_list` file only once per 48 hours. (In an upcoming release, this will be reduced to 24h). However, this fetching process has been error-prone and can be interrupted by regular use of the browser. There have been a high number of reports of the `publishers_list` becoming stale and failing to update on schedule.

Furthermore, given the new flow for tips to unverified creators, time-to-browser-side-verification-status has become especially important to publishers, as verification status now has material—i.e., financial—ramifications for publishers. (E.g., Tips may be delayed or not sent due to browser-side unverified status.) Providing more ways to stay up to date with the verified publishers list will help, in addition to being satisfying for publishers who just verified their channels and would like to be reassured of their verification status browser-side. 

The current workaround solution requires the user to manually rename, move or delete the `publishers_list` file from their `brave-browser/default` folder. However, this is beyond the ken of many mainstream users, and like all "workarounds", is fundamentally unsustainable. Overall, stale `publishers_list` issues have imposed a substantial tax on the support teams. 

### Solution

Add a button in the browser that forces the browser to download a new version of the `publishers_list` from the appropriate API endpoint (e.g., https://publishers.basicattentiontoken.org/api/v1/public/channels). Users can manually click this button to refresh their verification list.

### Community support for feature

This has been brought up internally, and has also received support in the community. See, for example, https://community.brave.com/t/add-setting-to-refresh-list-of-verified-sites/44924.

**Comment by Miyayes** [comment]
Another +1 from community: https://community.brave.com/t/verified-channel-not-showing-as-verified-in-browser/44763/3?u=chriscat

> Is there someplace in the browser where we can manually kick off the publisher update?
> 
> Would have been nice to see a warning in the publisher profile indicating to the user that it could take up to 48 hours.

**Comment by Miyayes** [comment]
+1 from Reddit: https://www.reddit.com/r/BATProject/comments/atjkxg/delay_period_after_verification_one_suggestion/

> add an option "Update list of creators" in the Browser (probably in the settings, not in the main GUI). So people can "update" their list when they want, without waiting 48h

**Comment by Miyayes** [comment]
**Note for triage:** 65% of my day is spent handling cases related to this issue. This will only increase as more publishers verify (charts on batgrowth.com show an accelerating curve). Even with the 24h update now live, downloading of the `publisher_list` by the browser seems _very_ unreliable and fickle.  

Again, this has material consequences for publishers because of the new client-side tipping flow for unverified channels.

_If there were a button to simply refresh the `publisher_list`, this would eliminate ~65% of support queries._ @rebron

**Comment by bsclifton** [comment]
cc: @jsecretan for prioritization

**Comment by NejcZdovc** [comment]
currently blocked on new settings dialog for rewards

**Comment by mandar-brave** [comment]
@jenn-rhim can we get this prioritized for @NejcZdovc from a design perspective.
I think you have an idea where to place the setting to get a manual refresh done for the Publisher list.

**Comment by jenn-rhim** [comment]
![image](https://user-images.githubusercontent.com/4369856/54938137-0d592700-4ee3-11e9-87eb-44793a65000b.png)

**Comment by bradleyrichter** [comment]
![image](https://user-images.githubusercontent.com/13509546/54938315-5c06c100-4ee3-11e9-8f46-0b383a27c5f3.png)

**Comment by NejcZdovc** [comment]
@bradleyrichter @jenn-rhim should we should only this when publisher is unverified?

**Comment by bradleyrichter** [comment]
@NejcZdovc non-verified only.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.64.72 Chromium: 74.0.3729.131 (Official Build) beta(64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2121
