### ISSUE TITLE
Add P3A metrics for Leo omnibox option and user acquisition source

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#33393]
Add the following desktop metrics for Leo:

If you are an opted-in Leo user, what % of your Omnibox selections were the Ask Leo option?
`Brave.AIChat.OmniboxOpens`

0. None
1. Less than 1%
2. Between 1% and 3%
3. Between 3% and 5%
4. Between 5% and 10%
5. Between 10% and 25%
6. More than 25%

If you are an opted-in Leo user, and you used the Leo omnibox option in the previous week, did you select the Leo omnibox option proportionally more this week vs last week?
`Brave.AIChat.OmniboxWeekCompare`

0. More last week
1. More this week

As a first time Leo user, what was your entry point?
`Brave.AIChat.AcquisitionSource`

0. Omnibox option
1. Sidebar

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.62.107 Chromium: 120.0.6099.115 (Official Build) beta (64-bit)
-- | --
Revision | 67a3b21572338a0660bb25a5855da0f1e9372a39
OS | Windows 10 Version 22H2 (Build 19045.3803)
```
