### ISSUE TITLE
[Follow up to #32884] `Download` button on `brave://skus-internals` is not working

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#33395]
## Description 

Follow up to #32884

## Steps to reproduce 

1. Launch Brave
2. Go to `brave://skus-internals`
3. Tap `Download` > Observe

## Actual result 

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/2ecc0172-9ab9-4e16-85a4-cd8cc386af2a) | ![2](https://github.com/brave/brave-browser/assets/128532965/942b4a52-052e-4b98-a58a-fbd34f635b2a) |

https://github.com/brave/brave-browser/assets/128532965/e9b55c11-ab2b-4999-a9a4-89fe72cb254c

The `Download` button on `brave://skus-internals` is not working. Instead `Share sheet` is opened.

## Expected result

When tapping the `Download` button a pop-up message with file name must be shown. Confirm it, and a file must be downloaded.

## Issue reproduces how often 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? YES
- Can you reproduce this issue with the current Play Store Nightly version? YES

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Pixel 2 XL, Pixel 6, Pixel 7 (phone)
   - Android version: Android 8, 13, 14
   
## Brave version

Brave build: 1.59.109
Chromium: 118.0.5993.21 (Official Build) beta (64-bit) 
Revision: aacb6a6f8bd916bd49f064b2137b007fa6c47b51

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by mattmcalister** [comment]
Fixed
