### ISSUE TITLE
Tray icon flashes when clicking "Try again" in the VPN panel

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#33405]
## Description 

The tray icon of Wireguard vpn flashes in and out when clicking "try again" multiple times in the vpn panel

https://github.com/brave/brave-browser/assets/2965009/87fe1055-92b0-41e6-9982-7951a40e9ca3

## Steps to Reproduce

   1. Connect Brave VPN Wireguard VPN
   2. Disconnect internet in the system
   3. Click "Try again" multiple times in the VPN panel

## Actual result:

- Tray icon flashes

## Expected result:

- Tray icon shows current state stable without flashing

## Reproduces how often: 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
## Verified `PASSED` using


```
Brave | 1.60.81 Chromium: 118.0.5993.54 (Official Build) beta (64-bit)
-- | --
Revision | 1efb3f333eb41cc34af46ca31fb33c30e0afbfae
OS | Windows 10 Version 22H2 (Build 19045.3516)
```

### Steps:
1. installed `1.60.81`
2. launched Brave
3. logged in to `account.bravesoftware.com` using `oct6@mailinator.com`
4. clicked on `Refresh Brave VPN`
5. connected to `Brave VPN`
6. disabled Wi-Fi
7. confirmed `Brave VPN` error
8. clicked on `Try again`
9. looked at the system-tray icon

### Confirmed the `Brave VPN` system-tray icon did NOT flash when clicking `Try again`

https://github.com/brave/brave-browser/assets/387249/74d5a23a-1c3d-4148-8d48-67d5b7250b52

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
```
### Steps:
1. installed `1.60.81`
2. launched Brave
3. logged in to `account.bravesoftware.com` using `oct6@mailinator.com`
4. clicked on `Refresh Brave VPN`
5. connected to `Brave VPN`
6. disabled Wi-Fi
7. confirmed `Brave VPN` error
8. clicked on `Try again`
9. looked at the system-tray icon

### Confirmed the `Brave VPN` system-tray icon did NOT flash when clicking `Try again`

**Comment by MadhaviSeelam** [comment]
I couldn't validate the issue on Win 11 x64 so filed a follow up bug #33600 so adding the label `QAPass-Win64`
