### ISSUE TITLE
Certain publishers are added twice in database with different score and % values

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#3340]
## Description 

Certain publishers are added twice in database with different score and % values

## Steps to Reproduce (Not reliable may be different)

   1. Enable rewards
   2. Visit a couple of sites and ensure they get added to the list
   3. Remove the sites from ac list
   4. Visit the site again after removing them from ac, disable ac switch from BR panel
   5. Check database, site is added twice to the list for the same month but has different value
   6. Certain sites have less score but has higher % value (second screenshot)

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/52716952-ef380700-2fc5-11e9-84ea-360127cbfebb.png)
Visits 0 but still has % values assigned 
![image](https://user-images.githubusercontent.com/17010094/52718662-011ba900-2fca-11e9-84d3-2cf5aee2e0b4.png)

## Expected result:
Duplicate entries for the same site 

## Reproduces how often: 

May be easy 

## Brave version (brave://version info)

Brave | 0.61.22 Chromium: 72.0.3626.81 (Official Build) dev(64-bit)
-- | --
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes. This is on my personal profile on dev channel

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @brave/legacy_qa @NejcZdovc @jasonrsadler

**Comment by NejcZdovc** [comment]
@srirambv that is expected as you have publisher per month and per reconcile stamp

**Comment by NejcZdovc** [comment]
month is the same, but reconcile stamp is different

**Comment by NejcZdovc** [comment]
closing as entries are different. @srirambv please reopen if I am missing something
