### ISSUE TITLE
nightly and beta not on same 118 version

### ISSUE THREAD

**Issue by joejoejo** [brave/brave-browser#33415]
Why is Nightly on version 118.0.5993.32, when Beta is not yet on that version, but is on version 118.0.5993.21?

**Comment by bsclifton** [comment]
@joejoejo we don't build Beta everyday - Nightly will always have the most up to date version

You can see the schedule here:
https://github.com/brave/brave-browser/wiki/Brave-Release-Schedule#current-build-schedule
