### ISSUE TITLE
NFTs added manually show up for pinning but not when owned

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#33410]
## Description 

NFTs added manually show up for pinning but not when owned

## Steps to Reproduce

   1. Restore wallet that has NFTs auto discovered
   2. Click on NFT pinning message
   3. Doesn't show the NFT as available for pinning
   4. Create a new Wallet 
   5. Manually add the same NFT for pinning
   6. Shows 1 NFT available for pinning

## Actual result:

![image](https://github.com/brave/brave-browser/assets/17010094/f22cea9f-0f67-4bd2-9cd6-c8e49e648e4e)

## Expected result:
![image](https://github.com/brave/brave-browser/assets/17010094/874f814d-0265-49cc-8ffd-82921c7becb2)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.59.109 Chromium: 118.0.5993.21 (Official Build) beta (64-bit)
-- | --
Revision | aacb6a6f8bd916bd49f064b2137b007fa6c47b51
OS | Windows 11 Version 22H2 (Build 22621.2283)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @muliswilliam @nvonpentz

**Comment by josheleonard** [comment]
Closing. Pinning is no longer supported as of https://github.com/brave/brave-core/pull/23808
