### ISSUE TITLE
CBS.com content blocked by Shields — disabling ads/trackers resolves

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#33419]
## Description 

Trying to stream content on CBS.com fails when ads & trackers are blocked. Content plays when ads & trackers are allowed on the site:
![image](https://github.com/brave/brave-browser/assets/3299098/eb885a4b-6916-4ba1-8d74-83f58b31c8b4)

cc @ryanbr 

## Reproduces how often: 

Every time

## Brave version (brave://version info)

v.1.58.137

**Comment by Gitchick57** [comment]
Unfortunately, this might have something to do with the TV station.  ABC doesn't allow blockers, VPNs, etc., when I use Brave.



Oct 4, 2023, 2:10 PM by ***@***.***:

**Comment by stephendonner** [comment]
I can reproduce this too using


```
Brave | 1.59.110 Chromium: 118.0.5993.21 (Official Build) beta (x86_64)
-- | --
Revision | e035b2582c778b683c1121599d849eb1591cf810
OS | macOS Version 11.7.10 (Build 20G1427)
```

example | example | example
---------|---------|----------
<img width="1711" alt="Screen Shot 2023-10-04 at 4 59 04 PM" src="https://github.com/brave/brave-browser/assets/387249/314eb4fa-d26a-48b3-ab0c-95532b271c51"> | <img width="1711" alt="Screen Shot 2023-10-04 at 4 59 30 PM" src="https://github.com/brave/brave-browser/assets/387249/0d17226d-2aed-41c9-b8c8-6bf188a099a9"> | <img width="1711" alt="Screen Shot 2023-10-04 at 4 59 46 PM" src="https://github.com/brave/brave-browser/assets/387249/a6185f3b-01f9-4014-9d4a-759dc89bd6dc">

**Comment by ryanbr** [comment]
Resolved @stephendonner @Brave-Matt ?
