### ISSUE TITLE
Migrated Brave VPN IKEv2 connection switches to `WireGuard`, but should stay on `IKEv2`

### ISSUE THREAD

**Issue by spylogsster** [brave/brave-browser#33418]
Clone of https://github.com/brave/brave-browser/issues/33382 to fix the rest part of the issue

Steps same as initial issue

## Steps to Reproduce

1. installed `1.58.33` (`nightly`)
2. launched Brave
3. opened `brave://flags/`
4. set `Enable experimental WireGuard Brave VPN service` to Disabled
5. clicked `Relaunch`
6. purchased, configured, and connected to `Brave VPN` using [account.bravesoftware.com](http://account.bravesoftware.com/)
7. confirmed IKEv2 connection using `BraveVPNNightly` RAS connection in the VPN panel
8. closed Brave
9. installed `1.59.109` (`beta`)
10. renamed `Brave-Browser-Nightly` profile to `Brave-Browser-Beta`
11. launched Brave
12. opened `brave://settings/system`
13. checked the setting for `WireGuard`

## Actual result:

* `Brave VPN` connects via `WireGuard`
* `brave://settings/system` shows `Use WireGuard protocol in Brave VPN` togled to `On`/`Enabled`

![image](https://github.com/brave/brave-browser/assets/387249/b0d837a0-7ca0-42b5-9944-649b14ecf032)

## Expected result:

* Should be connected via `IKEv2`
* `brave://settings/system` should show `Use WireGuard protocol in Brave VPN` toggled to `Off`/`Disabled`

![image](https://github.com/brave/brave-browser/assets/387249/d47d4561-736d-44ed-8719-c16ed35e4f1c)

## Reproduces how often: 

100%

**Comment by kjozwiak** [comment]
The above requires `1.59.115` or higher for `1.59.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.59.115 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | 82b05012fc6b5ab8535cf283db6856ad5eedd7eb
OS | Windows 10 Version 22H2 (Build 19045.3448)

```
### Steps:
1. installed `1.58.137`
2. launched Brave
3. opened `brave://flags`
4. set `Enable experimental Wireguard Brave VPN service` to `Disabled`
5. clicked `Relaunch`
6. purchased, configured, and connected to `Brave VPN` using [account.bravesoftware.com](http://account.bravesoftware.com/)
7. confirmed `IKEv2` connection using BraveVPNNightly RAS connection in the Windows VPN panel
8. disconnected from `Brave VPN`
9. quit Brave completely
10. uninstalled Brave, but left the profile folder intact
11. downloaded `1.59.115`
12. installed Brave
13. launched Brave
14. connected to `Brave VPN`

* Confirmed I was connected via `IKEv2`
* Confirmed `Use WireGuard protocol for Brave VPN` is toggled to `Off`/`Disabled` in `brave://settings/system`

`1.58.137`| `1.58.137` | `1.59.115` | `brave://settings/system`
---------|--------------|------------|------------
![image (1)](https://github.com/brave/brave-browser/assets/38657976/f23fe989-9786-40c3-9c45-c5c73b53fffb) | ![image](https://github.com/brave/brave-browser/assets/38657976/f6e6a45b-dc70-4efa-ab4d-0d7b4eb25d30) | ![image](https://github.com/brave/brave-browser/assets/38657976/6abc0758-9515-4bde-99dc-91055b194489) | ![image](https://github.com/brave/brave-browser/assets/38657976/aa3207da-b2e5-43fd-bae8-fab257863feb)

**Comment by LaurenWags** [comment]
Changing to `release-notes/exclude` per discussion with @kjozwiak @rebron - will use https://github.com/brave/brave-browser/issues/32002 as the main WireGuard issue in the notes.

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave	1.59.115 Chromium: 118.0.5993.54 (Official Build) (64-bit) 
Revision	82b05012fc6b5ab8535cf283db6856ad5eedd7eb
OS	Windows 10 Version 22H2 (Build 19045.3516)
```

1. installed `1.58.137`
2. launched Brave
3. opened `brave://flags`
4. set `Enable experimental Wireguard Brave VPN service` to `Disabled`
5. clicked `Relaunch`
6. purchased, configured, and connected to Brave VPN using [account.bravesoftware.com](http://account.bravesoftware.com/)
7. confirmed IKEv2 connection using BraveVPN RAS connection in the Windows VPN panel
8. disconnected from Brave VPN
9. quit Brave completely
10. uninstalled Brave, but left the profile folder intact
11. downloaded `1.59.115`
12. installed Brave
13. launched Brave
14. connected to Brave VPN
15. open `brave://settings/system` in a new tab


Confirmed I was connected via IKEv2
Confirmed Use WireGuard protocol for Brave VPN is toggled to Off/Disabled in brave://settings/system

example | example | example | example | example | example
---------|----------|---------|----------|---------|---------
![image](https://github.com/brave/brave-browser/assets/387249/ce6422ab-3c6c-4ca6-8e55-7505d0a2a7e8) | ![image (1)](https://github.com/brave/brave-browser/assets/387249/4bc663aa-4df3-4795-aba9-ee18ede0f2e0) | ![image (2)](https://github.com/brave/brave-browser/assets/387249/2ec655b6-8d95-48ec-90db-f1b60dea398c) | ![image (3)](https://github.com/brave/brave-browser/assets/387249/40c56889-28e6-418e-8cd9-b1be99a39bad) | ![image (4)](https://github.com/brave/brave-browser/assets/387249/d56bbe7c-deff-4136-bc56-cbd1922864a4) | ![image (5)](https://github.com/brave/brave-browser/assets/387249/d5fa8d3b-eab1-44fb-9b30-0e44bcdbc937)
