### ISSUE TITLE
incorrect attention % values in ac table after visiting excluded site

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#3341]
## Description 
If you exclude a site from your ac table and then visit it later, your attention percentage values in the table won't add up to 100%. It seems as though your table is counting the excluded site in your % values even though it's not listed in the table itself.

## Steps to Reproduce
Found with an upgrade profile, but happens on a clean profile as well. Steps below are for clean profile.

   1. Clean profile. Enable Rewards.
   2. Visit some sites (4-5) for min time needed.
   3. Exclude a site or two. Note which site(s) you exclude.
   4. Visit a site not in the table for min time needed.
   5. View ac table. Note that all % values add up to 100.
   6. Revisit one of the excluded sites for min time needed.
   7. View ac table.

## Actual result:
![screen shot 2019-02-13 at 12 54 36 pm](https://user-images.githubusercontent.com/28145373/52732567-884b2b80-2f8e-11e9-9422-8f4dee6067d7.png)

## Expected result:
All attention values should add up to 100%. Visiting the excluded site should not have any effect on the attention values since it is excluded.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.60.28 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Mac OS X

### Reproducible on current release: does not reproduce on 0.59.35
- Does it reproduce on brave-browser dev/beta builds? yes beta

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
cc @brave/legacy_qa @NejcZdovc

**Comment by GeetaSarvadnya** [comment]
Reproduced on windows 10 x64 - 0.60.27

![image](https://user-images.githubusercontent.com/38657976/52736886-f9bbc600-2ff0-11e9-92e6-e7b29266456a.png)

**Comment by LaurenWags** [comment]
Verified this issue does not reproduce on latest Dev

Brave | 0.61.22 Chromium: 72.0.3626.81 (Official Build) dev(64-bit)
-- | --
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}

**Comment by NejcZdovc** [comment]
@kjozwiak should we create custom fix for 0.60 or are we ok with just closing it as it will be fixed in 0.61?

**Comment by rebron** [comment]
Closing this issue. Fixed in 61.x with: https://github.com/brave/brave-core/pull/1600

**Comment by LaurenWags** [comment]
@brave/legacy_qa when verifying this issue we will need to see what happens if you encounter this issue on 0.60.x and then update to a build (in 0.61.x) with the fix.

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.61.38 Chromium: 73.0.3683.39 (Official Build) beta (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

Used test plan from https://github.com/brave/brave-core/pull/1589
Used STR from the description.
Upgrading from 0.60.28 retains the corrupted profile. Logged https://github.com/brave/brave-browser/issues/3510
