### ISSUE TITLE
`Ask Leo` is enabled in the Omnibar for `Private with Tor` windows, but should be disabled, just like its `Brave Leo` icon

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#33429]
## Description 

`Ask Leo` is enabled in the Omnibar for `Private with Tor` windows, but should be disabled, just like its `Brave Leo` icon

## Steps to Reproduce

1. install `1.61.1`
2. launch Brave
3. click on the "hamburger" menu
4. click on `New Private Window with Tor`
5. type anything
6. select `[your term] - Ask Leo`

## Actual result:

`chat is blocked` internal error message

<img width="1395" alt="Screen Shot 2023-10-05 at 1 45 37 AM" src="https://github.com/brave/brave-browser/assets/387249/c9812921-c73a-4841-8624-054e12315467">

## Expected result:

The `Leo` Omnibar-integration should be disabled whilst in `Private with Tor` windows

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave | 1.61.1 Chromium: 118.0.5993.32 (Official Build) nightly (x86_64)
-- | --
Revision | 5568565eb293b0fd70f66d781b3715e14aa23ce3
OS | macOS Version 11.7.10 (Build 20G1427)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @petemill @sangwoo108 @mattmcalister @bbondy @brave/qa-team

**Comment by kjozwiak** [comment]
The above requires `1.60.89` or higher for `1.60.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.60.89 Chromium: 118.0.5993.70 (Official Build) beta (x86_64)
-- | --
Revision | 801f851e0c0664d110cccd46708cd084a83c3729
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.60.89`
2. launched Brave
3. enabled `AI chat` via `brave://flags`
4. clicked `Relaunch`
5. opened the following window/profile types
6. checked for `Brave Leo`-enabled sidebar and Omnibar integration

### Confirmed `Ask Leo` present for all window/profile types except `Private with Tor` windows, as expected

## Normal windows - `PASSED`
<details>


<img width="1312" alt="Screen Shot 2023-10-13 at 9 40 29 AM" src="https://github.com/brave/brave-browser/assets/387249/8a74ec8b-b5e0-4834-9912-612a97ffde53">

</details>

## Private Window - `PASSED`
<details>


<img width="1312" alt="Screen Shot 2023-10-13 at 9 47 42 AM" src="https://github.com/brave/brave-browser/assets/387249/e2a130e0-2612-4f62-80c1-cff2d4de25ab">

</details>

## Private Window with Tor - `PASSED`
<details>

<img width="1312" alt="Screen Shot 2023-10-13 at 9 36 36 AM" src="https://github.com/brave/brave-browser/assets/387249/33c866c1-5193-4751-9af3-189526729f1d">

</details>

## Guest profile - `PASSED`
<details>


<img width="1312" alt="Screen Shot 2023-10-13 at 9 45 44 AM" src="https://github.com/brave/brave-browser/assets/387249/fb8b4eea-69c2-4e1c-8d1b-a74f3e7f6aae">

</details>
