### ISSUE TITLE
Deposit Crypto needs text wrapping in Wallet Panel

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#33425]
## Description 

The `Deposit Crypto` screen need text wrapping in the Wallet `Panel`

## Steps to Reproduce

   1. Open the `Panel` and navigate to the `Deposit` screen
   2. Select Solana to deposit
   3. The text needs to be wrapped

## Actual result:

![image](https://github.com/brave/brave-browser/assets/40611140/6b6adba5-e749-45a9-82be-6df7f93a1e45)

## Expected result:
Text should wrap and not get cut off by the screen.

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.59.113` or higher for `1.59.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.59.115 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | 82b05012fc6b5ab8535cf283db6856ad5eedd7eb
OS | Windows 11 Version 22H2 (Build 22621.2283)

- Verified steps from [brave/brave-core#20435](https://github.com/brave/brave-core/pull/20435)
- Verified Deposit crypto text is wrapped properly to show within the panel
- Encountered [#33514](https://github.com/brave/brave-browser/issues/33514)

https://github.com/brave/brave-browser/assets/17010094/362aac25-9120-4ee0-b0a2-ac61aeb80174
