### ISSUE TITLE
Layout reflow makes `Dislike answer` option text start off wrapped, and then reflow into inline

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#33431]
## Description 

Layout reflow makes `Dislike answer` option text start off wrapped, and then reflow into inline

## Steps to Reproduce

1. install `1.61.1`
2. launch Brave
3. restart (to pick up Griffin seed)
4. click on `Brave Leo`
5. click `Accept and begin`
6. load any page/article
7. click on `Summarize this page`
8. hover over `Leo's` generated response
9. within the circle, click on the vertical 3-dots menu
10. click on the vertical 3-dots menu again
11. toggled quickly and notice the `Dislike answer` option

## Actual result:

`Dislike answer` in this flyout menu starts off as a multi-line, wrapped string, but gets layout-reflowed back into inline

![layout-reflow](https://github.com/brave/brave-browser/assets/387249/1cbf2126-464d-4d3d-a2c7-b5f772763cec)

## Expected result:

Should have a one-time, fixed layout (hopefully)

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave | 1.61.1 Chromium: 118.0.5993.32 (Official Build) nightly (x86_64)
-- | --
Revision | 5568565eb293b0fd70f66d781b3715e14aa23ce3
OS | macOS Version 11.7.10 (Build 20G1427)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @petemill @nullhook @bbondy @mattmcalister @brave/qa-team

**Comment by mattmcalister** [comment]
I'm not seeing this anymore. check again @stephendonner ?
