### ISSUE TITLE
Dark site favicons are hard/impossible to see, in `Dark` mode

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#33437]
## Description 

Dark site favicons are hard/impossible to see, in `Dark` mode

## Steps to Reproduce

1. install `1.61.1`
2. launch Brave
3. restart (to pick up Griffin seed)
4. be in `Dark`-theme mode
5. load `nbcnews.com`
6. click on `Brave Leo`
7. click on `Accept and begin`
8. look at the site favicon in the AI chat pane

## Actual result:

`Dark` | `Light`
-------|--------
<img width="341" alt="Screen Shot 2023-10-05 at 4 17 09 AM" src="https://github.com/brave/brave-browser/assets/387249/49b74eaa-46a8-44e5-8f76-cdb7ad23b6ca"> | <img width="346" alt="Screen Shot 2023-10-05 at 4 16 56 AM" src="https://github.com/brave/brave-browser/assets/387249/6a5cc716-fd74-4e03-b09f-bf368096dfde">

`Dark` | `Light`
-------|--------
<img width="2014" alt="Screen Shot 2023-10-05 at 4 11 38 AM" src="https://github.com/brave/brave-browser/assets/387249/d6cef853-0670-47fa-8ca9-9fbbb44bf6f1"> | <img width="2014" alt="Screen Shot 2023-10-05 at 4 11 47 AM" src="https://github.com/brave/brave-browser/assets/387249/59832f2d-09c1-4f66-953f-2a2bb7c3d6bb">

## Expected result:

Logo should be visible somehow (opacity/other methods?)

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave | 1.61.1 Chromium: 118.0.5993.32 (Official Build) nightly (x86_64)
-- | --
Revision | 5568565eb293b0fd70f66d781b3715e14aa23ce3
OS | macOS Version 11.7.10 (Build 20G1427)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @sangwoo108 @bbondy @mattmcalister @petemill @nullhook @brave/qa-team

**Comment by Svvmy** [comment]
Hello, is it possible to assign me the issue. I would be happy to contribute.

**Comment by bbondy** [comment]
This issue will be somewhat adjusted in https://github.com/brave/brave-browser/issues/34099

**Comment by mattmcalister** [comment]
Tested a lot of sites and not seeing any problem here. Closing.
