### ISSUE TITLE
Improve Wallet dark theme

### ISSUE THREAD

**Issue by simoarpe** [brave/brave-browser#33439]
## Description

Improves dark theme for Brave Wallet based on Figma design.

## Dark theme Figma design
![image (11)](https://github.com/brave/brave-browser/assets/3308503/a9989f13-9f1c-4c3e-ad9e-8d3b59f7d4f0)

## Current dark theme
![image__12_](https://github.com/brave/brave-browser/assets/3308503/490f944f-e54e-4bfd-9edc-6ea8ffb74c92)

Elements to tweak:
- Action bar background color
- Wallet background color
- Selector main color and background color
- Network icon size
- "Assets" subtitle: color and text size
- ~Card view style: borders, color and background~
- Bottom navigation view style: colors and text size
- Divider line below action bar
- Divider line above bottom navigation view

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.61.61 x64 beta build
- Verified steps from [brave/brave-core#20465](https://github.com/brave/brave-core/pull/20465)
- Verified toolbar background color matches Figma design
- Verified toolbar does not have a shadow but a thin divider line
- Verified Wallet background color matches Figma design
- Verified selector (Assets - NFTs) main color and background color match Figma design
- Verified bottom navigation view colors and text size match Figma design
- Verified a thin divider line is shown above bottom navigation view
- Encountered [#34127](https://github.com/brave/brave-browser/issues/34127) & [#34128](https://github.com/brave/brave-browser/issues/34128) on Tablet

Oppo Reno 5 (Android 13) | Lenovo Tab (Android 13)
-- | --
<video src=https://github.com/brave/brave-browser/assets/17010094/09b47634-4dd4-459e-943e-a10c797cb9cf> | <video src=https://github.com/brave/brave-browser/assets/17010094/4be2e597-57ae-49f3-a058-da6ea95fe269>
