### ISSUE TITLE
Duplicate ` Answer Liked` feedback notifications

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#33433]
## Description 

Duplicate ` Answer Liked` feedback notifications

## Steps to Reproduce

1. install `1.61.1`
2. launch Brave
3. restart (to pick up Griffin seed)
4. load an article/webpage
5. click on `Brave Leo`
6. click on `Accept and begin`
7. click on `Summarize this article`
8. hover over the generated response
9. click on the vertical 3-dots menu
10. choose `Like Answer`

## Actual result:

You get duplicate notifications

example | example | example
---------|----------|---------
<img width="1312" alt="Screen Shot 2023-10-05 at 3 01 29 AM" src="https://github.com/brave/brave-browser/assets/387249/ce852b2d-411d-40cd-aa70-84d37eecca98"> | <img width="1312" alt="Screen Shot 2023-10-05 at 3 01 35 AM" src="https://github.com/brave/brave-browser/assets/387249/5b996c39-bc0a-48a4-a3f3-b09d81af5649"> | <img width="1312" alt="Screen Shot 2023-10-05 at 3 01 36 AM" src="https://github.com/brave/brave-browser/assets/387249/bd07bfa0-ac61-4597-8c7a-c89044092209"> | <img width="1312" alt="Screen Shot 2023-10-05 at 3 01 36 AM" src="https://github.com/brave/brave-browser/assets/387249/d10e02da-6124-4e88-bc3a-e324ad8d85ff">

## Expected result:

Only 1 notification per each`Like`/`Dislike` action

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave | 1.61.1 Chromium: 118.0.5993.32 (Official Build) nightly (x86_64)
-- | --
Revision | 5568565eb293b0fd70f66d781b3715e14aa23ce3
OS | macOS Version 11.7.10 (Build 20G1427)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @bbondy @mattmcalister @nullhook @sangwoo108 @petemill

**Comment by mattmcalister** [comment]
Done
