### ISSUE TITLE
`Like`/`Dislike answer` actions are repeatable, but should just be toggle-able

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#33434]
## Description 

`Like`/`Dislike answer` actions are repeatable, but should just be toggle-able

## Steps to Reproduce

1. install `1.61.1`
2. launch Brave
3. restart (to pick up Griffin seed)
4. load an article
5. click on `Brave Leo`
6. click on `Accept and begin`
7. click on `Summarize this article`
8. hover over the generated response
9. click on the 3-dots menu
10. click on `Like`
11. wait a bit
12. click again on `Like`
13. you are able to repeat the action, seemingly, and again get (duplicate: filed https://github.com/brave/brave-browser/issues/33433) notifications

## Actual result:

example | example
---------|---------
<img width="2014" alt="Screen Shot 2023-10-05 at 3 42 07 AM" src="https://github.com/brave/brave-browser/assets/387249/a48ba19b-fa31-49ef-aa59-a6ff024eb823"> | <img width="2014" alt="Screen Shot 2023-10-05 at 3 42 10 AM" src="https://github.com/brave/brave-browser/assets/387249/ada41ff9-4250-4d60-ac31-4d273a23363c">

## Expected result:

Maybe we should disable resubmission of the same selected `Like` or `Dislike answer` button, and only allow the other, non-selected option (i.e. you clicked `Like`, now `Like` is shown in green but disabled.  `Dislike answer` should still be enabled.

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave | 1.61.1 Chromium: 118.0.5993.32 (Official Build) nightly (x86_64)
-- | --
Revision | 5568565eb293b0fd70f66d781b3715e14aa23ce3
OS | macOS Version 11.7.10 (Build 20G1427)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @bbondy @mattmcalister @petemill @nullhook @sangwoo108 @brave/qa-team

**Comment by stephendonner** [comment]
![repeatable](https://github.com/brave/brave-browser/assets/387249/af0cd667-1fb0-42b8-93c7-a19b4bb2d3d8)

**Comment by kjozwiak** [comment]
The above requires `1.60.105` or higher for `1.60.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.60.106 Chromium: 119.0.6045.59 (Official Build) (64-bit)
-- | --
Revision | 16064193dde8c55f64dabd32f125c0cd9380f96a
OS | Windows 11 Version 22H2 (Build 22621.2428)
```
