### ISSUE TITLE
Like & Dislike answer both has 👍 icon 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#33441]
## Description 

Like & Dislike answer both has 👍 icon 

## Steps to Reproduce

   1. Ask a question to Leo
   2. Hover over the 3 dot menu on response
   3. Both Like and Dislike answer has a thumbs up icon

## Actual result:

![image](https://github.com/brave/brave-browser/assets/17010094/9fbd12ae-84b1-4df4-8b51-9d8b29f51cf3)

## Expected result:
Maybe 👎  for dislike for more of a visual cue

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.61.1 Chromium: 118.0.5993.32 (Official Build) nightly (64-bit)
-- | --
Revision | 5568565eb293b0fd70f66d781b3715e14aa23ce3
OS | Windows 11 Version 22H2 (Build 22621.2283)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @bbondy @brave/qa-team @nullhook @aguscruiz

**Comment by kjozwiak** [comment]
The above requires `1.60.94` or higher for `1.60.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.60.94 Chromium: 118.0.5993.70 (Official Build) beta (x86_64)
-- | --
Revision | 6a9dda6d700daa1da53ec97072458dd271ba5c01
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Confirmed `Like answer` and `Dislike answer` have the appropriate 👍 and 👎  icons

`Dark` | `Light`
-------|-------
<img width="1668" alt="Screen Shot 2023-10-17 at 1 46 40 PM" src="https://github.com/brave/brave-browser/assets/387249/848a7e18-a0df-47fc-ab09-380831b5b913"> | <img width="1668" alt="Screen Shot 2023-10-17 at 1 46 20 PM" src="https://github.com/brave/brave-browser/assets/387249/1044757f-6a5c-4e25-9629-156251c51b84">
