### ISSUE TITLE
Refactor AI_CHAT component to allow iOS to use MOST of the code & the feedback API

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-browser#33451]
## Description 
- Fix layering violations by moving the `ai_feedback` API to `core` instead of `content`/`browser`
- Refactor the `AI_Tab_Helper` to allow iOS to share the same core code and abstract away the `browser` specific code.

**Comment by kjozwiak** [comment]
Removing from `1.60.x` as https://github.com/brave/brave-core/pull/20425 hasn't landed into `master` yet.
