### ISSUE TITLE
[Speedreader] Return back the 'View original' link on desktop platforms.

### ISSUE THREAD

**Issue by boocmp** [brave/brave-browser#33460]

**Comment by kjozwiak** [comment]
The above requires `1.60.102` or higher for `1.60.x` verification 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.60.102 Chromium: 118.0.5993.96 (Official Build) beta (64-bit)
-- | --
Revision | 3598a9fc6b7752181feb25caa131bc386d6d054c
OS | Windows 11 Version 22H2 (Build 22621.2428)
```

Using the STR/information provided via https://github.com/brave/brave-browser/issues/33460#issue-1929977413, ensured that the `View original` text/link is appearing on articles page when viewed via Speedreader as per the following:

* ensured that articles viewed via Speedreader have the `View original` text/link within the article
* ensured that clicking on `View original` correctly loads the original article/content without issues

**`Example`** | **`Example`**
----------------|-----------------
![image](https://github.com/brave/brave-browser/assets/2602313/a3c3e2d5-962b-43a3-9db7-297c27602dd3) | ![image](https://github.com/brave/brave-browser/assets/2602313/468c200c-8bab-4172-907e-692fab325ae9)
