### ISSUE TITLE
Mixed Bookmark icons on new tab top sites

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#3347]
Follow up from https://github.com/brave/brave-browser/issues/633

## Test plan / Steps to Reproduce

   1. Clean install
   2. Open a page
   3. Open a new tab
4. Hover over a top site

## Actual result:

Not bookmarked top site has a bookmarked icon
Bookmarked top site has a not bookmarked icon
Bookmark icons are flipped

![new tiles](https://user-images.githubusercontent.com/34715963/52743772-1c42e480-2fdb-11e9-9465-43e4af3ca22e.gif)

## Expected result:
bookmarked top site has bookmarked icon

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.60.28 Chromium: 72.0.3626.96 (Official Build) beta (64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Windows 7

cc @brave/legacy_qa @cezaraugusto

**Comment by srirambv** [comment]
The bookmark icon and unbookmarked icons are flipped. Unbookmarked icon shows filled dark colour but bookmarking it fills with white colour making it look like unfilled icon.

**Comment by LaurenWags** [comment]
Reproduced on macOS

Brave | 0.60.28 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Mac OS X

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.63.4 Chromium: 73.0.3683.67 (Official Build) dev (64-bit)
-- | --
Revision | a83fd4f3207ae83412d329a9ca1239dd1e068345-refs/branch-heads/3683@{#760}
OS | Windows 7 Service Pack 1 Build 7601.24312

Used test plan from the description
Encountered top site bookmarking problems: https://github.com/brave/brave-browser/issues/2971

**Comment by GeetaSarvadnya** [comment]
Blocked and unable to test due to https://github.com/brave/brave-browser/issues/3805

**Comment by rebron** [comment]
@GeetaSarvadnya Can you try now? #3805 is fixed.
