### ISSUE TITLE
Block cross-site cookie settings option is not selectable in globals

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#33473]
## Description 
Block cross-site cookie settings option is not selectable in globals

## Steps to reproduce 

   1. Fresh install
   2. Open some tabs
   3. Check cookie settings in shields on the websites
   4. Open global cookie settings and try to select `Block cross-site cookies` or just press done because its selected by default already.
   5. Observe the cookie selection in settings
   6. Check the cookie settings per site in shields

## Actual result 
Example | Example
-|-
![Screenshot 2023-10-06 at 12 31 28 PM](https://github.com/brave/brave-browser/assets/17885425/bf44fe1e-ac85-4747-84dd-cbb63f6addf2) | ![Screenshot 2023-10-06 at 12 31 55 PM](https://github.com/brave/brave-browser/assets/17885425/870bf5fa-4ded-466c-b142-b417585c841d)

## Expected result
Should be selectable

## Issue reproduces how often 
Easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? TBD
- Can you reproduce this issue with the current Play Store Nightly version? TBD

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone & Tablet - Samsung Galaxy S21, Tab S7
   - Android version: 13, 14
   
## Brave version
1.58.x, 1.59.x

**Comment by deeppandya** [comment]
we missed `break` for switch in https://github.com/brave/brave-core/commit/3ee7f22fa0834e619cdbccfbbcfdc0890f9cb73c
