### ISSUE TITLE
`Available language models` should be `Language models` per Figma

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#33489]
## Description 

`Available language models` should be `Language models` per Figma

## Steps to Reproduce

1. install `1.61.3`
2. launch Brave
3. enable `Leo` via `brave://flags`
4. click `Relaunch`
5. click on `Brave Leo`
6. click `Accept and begin`
7. click on the 3-dots menu/ellipsis at the top right
8. look at the dropdown heading

## Actual result:

The heading reads `Available language models`

<img width="334" alt="Screen Shot 2023-10-06 at 8 45 19 PM" src="https://github.com/brave/brave-browser/assets/387249/0e52c509-c947-4248-927d-795055893d6f">

## Expected result:

Just `Language models`

<img width="332" alt="Screen Shot 2023-10-06 at 8 49 02 PM" src="https://github.com/brave/brave-browser/assets/387249/e182db0d-af5f-4c9b-ab09-01c08672ba85">

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave | 1.61.3 Chromium: 118.0.5993.54 (Official Build) nightly (x86_64)
-- | --
Revision | 65de72604895b354f3a9c4ad818b993028096814
OS | macOS Version 11.7.10 (Build 20G1427)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @bbondy @mattmcalister @nullhook @petemill @aguscruiz @brave/qa-team

**Comment by kjozwiak** [comment]
The above requires `1.60.105` or higher for `1.60.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.60.105 Chromium: 119.0.6045.59 (Official Build) (64-bit)
-- | --
Revision | a39727aa81373a09a915478fcb35826242c37335
OS | Windows 10 Version 22H2 (Build 19045.3570)
```
Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/33489#issue-1931091110, ensured that `Language models` was being used as per the following:

**`Example`** | **`Example`**
----------------|-----------------
![image](https://github.com/brave/brave-browser/assets/38657976/abc36cf3-feac-4044-8813-972ced898f20) | ![image](https://github.com/brave/brave-browser/assets/38657976/0eddbb09-047b-4e06-bc89-1dd1a1f7c789)
