### ISSUE TITLE
`Chat` heading should follow Figma spec

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#33484]
## Description 

`Chat` heading should follow Figma spec

## Steps to Reproduce

1. install `1.61.3`
2. launched Brave
3. enabled `brave://flags/#brave-ai-chat` and clicked `Relaunch`
4. click on `Brave Leo` in the sidebar
5. click on `Accept and begin`
6. click on the `3-dots` menu at the top
7. look at the styling of `Chat`

## Actual result:

1. font is too heavy
2. missing icon to the left of `Chat`

<img width="321" alt="Screen Shot 2023-10-06 at 5 37 47 PM" src="https://github.com/brave/brave-browser/assets/387249/d72ccf9b-fcff-415a-8d3e-5eef18e8e1cc">

## Expected result:

<img width="317" alt="Screen Shot 2023-10-06 at 5 38 55 PM" src="https://github.com/brave/brave-browser/assets/387249/ee7456a6-5303-4d20-b477-a74c2faef02f">

1. lighter-weight font
4. icon to the left of `Chat`

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave | 1.61.3 Chromium: 118.0.5993.54 (Official Build) nightly (x86_64)
-- | --
Revision | 65de72604895b354f3a9c4ad818b993028096814
OS | macOS Version 11.7.10 (Build 20G1427)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@bbondy @mattmcalister @petemill @nullhook

**Comment by kjozwiak** [comment]
The above requires `1.60.105` or higher for `1.60.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.60.105 Chromium: 119.0.6045.59 (Official Build) (64-bit)
-- | --
Revision | a39727aa81373a09a915478fcb35826242c37335
OS | Windows 10 Version 22H2 (Build 19045.3570)
```

Using the STR/information outlined via https://github.com/brave/brave-browser/issues/33484#issue-1930964653, ensured that that the text appeared a lighter compared to before and all the icons are appearing next to each link as per the following:

**`Example`** | **`Example`**
----------------|-----------------
![image](https://github.com/brave/brave-browser/assets/38657976/ef8bc42f-acbc-4cd5-92dd-80970e9399b5) | ![image](https://github.com/brave/brave-browser/assets/38657976/1720a9a2-5034-4cfc-b8b1-bcb1ec8f6e9b)
