### ISSUE TITLE
YouTube: Pre-roll ads, ads on page, and video "overlay" ads not blocked

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#3348]
## Description 

Seeing several reports recently about YouTube ads not being blocked. This seems to vary between but not be limited to: 

- **Pre-roll ads** that play before content streams
- Ads displayed on the YT **page itself** (outside of video)
- Ads that **display/overlay** the video itself ("inside" video)
Image below depicting all three types displayed. 
![image](https://user-images.githubusercontent.com/3299098/52738583-cabb3b00-2f83-11e9-9925-5ef1658c6e46.png)
User reports also show that this is not necessarily restricted by OS (although majority have been Windows) - Windows, macOs and Linux systems have reported this behavior. 

Diagnosing the issue is difficult given that I'm unable to reproduce this on my end when testing (using macOS and windows 7/10). Would be good to know if there is any specific or pertinent information to collect from users that would help highlight what the issue is (cc @lukemulks) - So far I've been collecting Brave version, OS info, and URLs to the videos where ads are displayed. 
 
## Steps to Reproduce

   1. Visit YT and stream video content (I imagine this would be easiest to produce when streaming videos with a high view count - more likely to be monetized).

## Actual result:

Ads are displayed on page and in video.

## Expected result:
Ads should be blocked.

## Reproduces how often: 

Users experiencing this issue report that this behavior is consistent for them.

## Brave version (brave://version info)

Release channel v0.59.35
Beta v0.60.23
Dev v0.61.16

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? **Yes**
- Is the issue reproducible on the latest version of Chrome? **No**

### Additional Information

User reports - will add more to the thread as I come across them:

- https://www.reddit.com/r/brave_browser/comments/ao4zah/youtube_ads/
- https://community.brave.com/t/brave-shields-not-working-even-when-turned-on/44830
- https://www.reddit.com/r/brave_browser/comments/amrpe5/im_starting_to_see_ads_on_youtube_is_anyone/
-

**Comment by rebron** [comment]
@Brave-Matt we need an example video, I'm having trouble reproducing this myself. Went through a handful of videos and can't find one yet.

**Comment by Brave-Matt** [comment]
@rebron that's the thing - I can't produce this personally. If you follow the links above you'll see user submitted images of the ads displaying.

**Comment by Brave-Matt** [comment]
From reddit:
https://www.reddit.com/r/brave_browser/comments/b0yqfw/youtube_ads_suddenly_started_appearing_using/

**Comment by JamesTheHacker** [comment]
I'm the Reddit poster. For me the following videos display ads:

* https://www.youtube.com/watch?v=v30wXiZ41Ds
* https://www.youtube.com/watch?v=bVu8OWN90eY

**Brave Version:** _Version 0.61.51 Chromium: 73.0.3683.75 (Official Build) (64-bit)_
**OS:** _Windows 10 Pro_

**Comment by Swennet** [comment]
Same issue. I have a lot of YouTube video ads that play, and the skip ad button is removed. Sometimes, after watching the entire first ad, it just repeats the same ad again or displays a new one, seemingly infinitely. Refreshing the page sometimes makes no ad play.

Very annoying and frustrating. Especially the fact that this happens with both the blocker turned on and off.

**Comment by Brave-Matt** [comment]
+1 from Community:
https://community.brave.com/t/youtube-masthead-ad-blocking-not-saving/51343/5

**Comment by Brave-Matt** [comment]
+1 from community:
https://community.brave.com/t/youtube-masthead-ad-blocking-not-saving/51343/4

**Comment by Brave-Matt** [comment]
+1 from Reddit:
https://www.reddit.com/r/brave_browser/comments/bh8hsu/shield_is_not_working_properly_ads_showing/

**Comment by Brave-Matt** [comment]
+1 from Community:
https://community.brave.com/t/youtube-ads-not-getting-blocked-by-shields-desktop-mobile/45671/8

**Comment by Brave-Matt** [comment]
+1 from Reddit:
https://www.reddit.com/r/brave_browser/comments/bco6jp/youtube_ads/

**Comment by Brave-Matt** [comment]
+1 from Reddit:
https://www.reddit.com/r/brave_browser/comments/b0yqfw/youtube_ads_suddenly_started_appearing_using/

**Comment by Brave-Matt** [comment]
+1 from Community:
https://community.brave.com/t/ad-blocking-problems/59959/4

**Comment by Brave-Matt** [comment]
+1 from community:
https://community.brave.com/t/youtube-ads-not-skippable/46179/12?u=mattches

**Comment by Brave-Matt** [comment]
+1 from reddit:
![image](https://user-images.githubusercontent.com/3299098/60491801-711b8a80-9c5e-11e9-80d8-ba038d630f5e.png)

**Comment by rebron** [comment]
cc: @ryanbr Can you take a look at this one?

**Comment by Brave-Matt** [comment]
Big/popular reddit thread on the subject:
https://www.reddit.com/r/brave_browser/comments/c7s7mi/youtube_is_bypassing_braves_ad_block_with_ads/

**Comment by ryanbr** [comment]
I'll take another look in the next few days (not easy since youtube uses many adservers), but will probably be fixed in adblock-rust.

**Comment by Brave-Matt** [comment]
+1 from Community:
https://community.brave.com/t/youtube-ads-continue-despite-ad-blocker/72052/2

**Comment by ryanbr** [comment]
Okay, From a private window. Cookies Cleared. And VPN'd to South Africa (Random I know).

http://secure.fanboy.co.nz/gif/youtube.gif

Note the Items (well the amount of items that are being blocked,) I didn't see any obvious ads? 

This is on Brave Release.

**Comment by Brave-Matt** [comment]
+1 from Community:
https://community.brave.com/t/can-there-be-an-option-to-allow-javascript-automatically-without-us-having-to-manually-do-it-everytime/57131/9?u=mattches

**Comment by Xronis** [comment]
Hi, 

For me it doesn't happen all times but when it does it is both banners and pre-roll ads.

OS: Win10
Installed Extensions: None
Connected to VPN: Yes (Corporate policy)
Shields: 3rd parties trackers and connections upgraded to HTTPS are ON, scripts blocked OFF.
brave://adblock: Nothing additional

I am still new with Brave, so if I am missing something let me know.

Cheers

**Comment by ryanbr** [comment]
With the new adblock in Brave Nightly, can we get that tested? does the ads show up there?

**Comment by Xronis** [comment]
Hi,

Sorry for the late response I was on vacation and didn't really check my emails until now that I returned. So far so good, no pre-roll ads yet. I will let you know if any pop up.

Thanks for the support,
Cheers

**Comment by Arcim** [comment]
Hello all,

all was fine and blocked, until I installed Adobe Acrobat Reader and unfortunately let it install with the browser add-on. Since then Youtube started push through adverts without the skip button. No popups or banners so far. Although I am not sure if there was any other update to system or to Brave itself. I will try to make a fresh install of Brave and let you know if anything changes.

Cheerio
Jan

**Comment by Arcim** [comment]
> Hello all,
> 
> all was fine and blocked, until I installed Adobe Acrobat Reader and unfortunately let it install with the browser add-on. Since then Youtube started push through adverts without the skip button. No popups or banners so far. Although I am not sure if there was any other update to system or to Brave itself. I will try to make a fresh install of Brave and let you know if anything changes.
> 
> Cheerio
> Jan

Also the ads are pre-and also mid-roled and I noticed that some are in my native language so it knows where I am...

**Comment by Brave-Matt** [comment]
+1
https://www.reddit.com/r/brave_browser/comments/cybigd/brave_stopped_blocking_yt_ads/

**Comment by Brave-Matt** [comment]
![image](https://user-images.githubusercontent.com/3299098/64196936-c1b78b80-ce39-11e9-8525-5ea11a2cb4a8.png)

**Comment by Brave-Matt** [comment]
![image](https://user-images.githubusercontent.com/3299098/64197021-ef9cd000-ce39-11e9-8478-ff4308a80fc2.png)

**Comment by Brave-Matt** [comment]
![image](https://user-images.githubusercontent.com/3299098/64197059-fdeaec00-ce39-11e9-8e3d-5b17aa94203a.png)

**Comment by Brave-Matt** [comment]
![image](https://user-images.githubusercontent.com/3299098/64197076-093e1780-ce3a-11e9-8475-336f386e8395.png)

**Comment by Brave-Matt** [comment]
![image](https://user-images.githubusercontent.com/3299098/64197132-1f4bd800-ce3a-11e9-9c17-1ab1dac81045.png)

**Comment by Brave-Matt** [comment]
+1
https://www.reddit.com/r/brave_browser/comments/czqgpm/anyone_else_getting_youtube_ads_on_the_desktop/

**Comment by Brave-Matt** [comment]
+1 from reddit: https://www.reddit.com/r/brave_browser/comments/d1oz7i/youtube_showing_midvideo_ads/

**Comment by ryanbr** [comment]
Okay, ads in the Youtube space are considered either pre-roll or mid-roll embedded videos. What Youtube ads aren't, Annotations, Cards  These are considered part of the site, while Annoying. They aren't considered an advert.

**What I'm trying to debug specifically is the pre-roll and mid-roll ads only.**

Okay, I tested 2 sites. One on a Norway IP (VPN). Checking from EU country:

https://secure.fanboy.co.nz/gif/youtube-ads.gif

From NZ: (using the sample clip provided by @JamesTheHacker 

https://secure.fanboy.co.nz/gif/youtube-ads2.gif

`TL;DR: From my testing on both videos. If Brave sheilds is enabled / Cross site trackers, I don't get ads. The moment I disable Shields and refresh the site I'll get an instant pre-roll ad as seen in the gifs. (may needed to clear the cookies to ensure youtube would show the pre-roll advert).`

**What I need from the users trying to help debug the issue:**

- Test in private mode with no extensions enabled, with only Sheilds enabled, 

- Clear Youtube cookies first in the options, then visit the problematic youtube site.

- A Screen shot of the sheilds window open and the sheilds cross-site trackers being listed., showing the ad in the background.  Like so: https://imgur.com/a/Ms9BT5Q  (I have no ad showing in my case, because I can't replicate it)

- Go into Shields / Cross-site trackers.

1. Ctrl-A (Select all Cross-site trackers) 
2. Crtl-C (Copy to Clipboard) 
3. Ctrl-V (Paste) into pastebin.com, 

Like so: https://pastebin.com/18EAphvt  (For Privacy, trim each line leaving the first 50-60 chars of each line or so)

- If you've used Ublock Origin, this may help also. Additional Testing with UBO (enable in private mode). **Only** enable these filter lists Easylist/Easprivacy in UBO options. Does enabling ublock origin extension stop the youtube ad? If it does block the ads, post a screenshot of (like so: https://imgur.com/a/Hov5tSF)

- Can you replicate the same ads on a different PC (with Brave Sheilds on)?

`Note: Some extensions will insert ads in to websites, which we can't block. Or possibly the PC is infected with malware?`

**Comment by Brave-Matt** [comment]
+1 from Reddit:
https://www.reddit.com/r/brave_browser/comments/fj72rz/youtube_has_apparently_partly_circumvented_braves/

**Comment by tstoeger2** [comment]
Here's what I'm getting:
Pre-roll and mid-roll ads.

Seems like all ads are typically 30 seconds and not skipable.  After they play, they sit on the end screen for several seconds before either playing a second ad or resuming the video.

The only extension I had was Google Translate, which I just removed in the hopes of fixing this issue (not sure why it would, but it's the only thing that's changed that I can see).

This just started happening last night after I forced my computer to shut down (it had been "powering off" for like 20 minutes, so I held down the power button).

Windows 10, Brave version 1.7.98

I have no cross-site trackers listed (in normal or private browsing), so there was nothing to copy into pastebin.

Successfully replicated in private and normal browsing

![Bravd ads private](https://user-images.githubusercontent.com/46796475/80141373-12b5f480-856f-11ea-8ad1-9ee429d821b1.PNG)

**Comment by bernardbr** [comment]
@tstoeger2, I've got the same behavior here!

**Comment by jonathansampson** [comment]
@tstoeger2 and @bernardbr, can you both navigate to `about:components` in the browser, and confirm that your _Brave Ad Block Updater_ is version 1.0.551 or greater? If it isn't, please click <kbd>Update</kbd> next to the entry.

**Comment by tstoeger2** [comment]
> @tstoeger2 and @bernardbr, can you both navigate to `about:components` in the browser, and confirm that your _Brave Ad Block Updater_ is version 1.0.551 or greater? If it isn't, please click Update next to it.

It is up to date.

**Comment by whitleyblaine** [comment]
AHHHHHHHHH. All of a sudden I get ads all the damn time on Youtube. They can't be skipped and shields are up. It is driving me crazy. They happen both before and in the middle of videos.

**Comment by whitleyblaine** [comment]
![image](https://user-images.githubusercontent.com/16406201/80268438-f2705d80-8674-11ea-8cc2-67582107047f.png)
Now it's not just YouTube, I'm getting ads on other sites, like babypips.com. But shields are up.

**Comment by bernardbr** [comment]
> @tstoeger2 and @bernardbr, can you both navigate to `about:components` in the browser, and confirm that your _Brave Ad Block Updater_ is version 1.0.551 or greater? If it isn't, please click Update next to it.

Hi, @jonathansampson!

Sorry about my delay!

My version is higher than 1.0.551
![image](https://user-images.githubusercontent.com/4705034/80527597-fbaa4480-896a-11ea-9c4a-aa0845dbf0b2.png)

**Comment by svaneke** [comment]
Same here. Latest version of Brave on MacOS High Sierra.
![YT](https://user-images.githubusercontent.com/64025084/80795197-1dd6d900-8b9c-11ea-971c-99e7e7b37f11.JPG)

**Comment by ThinkPadX220** [comment]
![image](https://user-images.githubusercontent.com/55105920/80920203-23801a80-8d66-11ea-8330-cc55a11f661c.png)
Same here too...
Windows 10 Pro x64 1909 - Brave Version 1.8.86 Chromium: 81.0.4044.129 (Official Build) (64-bit)

**Comment by ThinkPadX220** [comment]
This really feels like a cat and mouse game between ad blockers and YouTube/Google ad engineers.

**Comment by Sov3rain** [comment]
Same here 

Microsoft Windows [Version 10.0.18363.836]
Version 1.9.72 Chromium: 81.0.4044.138 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/10755450/82730159-fdfb8680-9cfd-11ea-8051-15906b25848c.png)

**Comment by melMass** [comment]
Same here on OSX Mojave using the release version

**Comment by Kalense** [comment]
Pre-roll ads, Mac OS High Sierra, shields up, Brave Version 1.9.80 Chromium: 81.0.4044.138 (Official Build) (64-bit)

**Comment by ryanbr** [comment]
@UndercoverNL @melMass @Kalense @Sov3rain 

Youtube has recently been testing ads on various regions. It's affecting all adblocking software (uBO and Adguard), some more than others. 

As a test, can someone test Brave Beta, `Site-ads/trackers = Aggressive in Shields` on youtube. and re-test these youtube ads? We have had some reports that Brave beta currently is less affected at the moment.

**Comment by cold-briu** [comment]
Same bug here
I'm using 1.8.90 Chromium: 81.0.4044.129 (Official Build) (64-bits)
On high sierra

**Comment by UndercoverNL** [comment]
> @UndercoverNL @melMass @Kalense @Sov3rain
> 
> Youtube has recently been testing ads on various regions. It's affecting all adblocking software (uBO and Adguard), some more than others.
> 
> As a test, can someone test Brave Beta, `Site-ads/trackers = Aggressive in Shields` on youtube. and re-test these youtube ads? We have had some reports that Brave beta currently is less affected at the moment.
> 
> https://brave.com/download-beta/

It seems that the Brave beta does work! Not sure but I have already been able to watch more than 10 videos without any prerole ads

**Comment by noircir** [comment]
The ads in Youtube started appearing in my Brave since April, 2020. After 2 months of quiet suffering, (and switching to Firefox which at least allows you to "skip ads") I decided to check on Github issues. Et voilà, installing Brave beta (the answer above) works!

**Comment by ryanbr** [comment]
We have an upcoming fix (hopefully to be rolled out next week), which should help with most of these ads. To be more uBO-like in blocking.

Google/Youtube have been testing their anti-adblock. And adblock extensions are still having issues, Some uBO users are still reporting ads. https://old.reddit.com/r/uBlockOrigin/comments/hchfuc/youtube_ads/

**Comment by AlvisonHunterArnuero** [comment]
New fixes coming soon, those are great news, guys!

Hopefully we are able to get rid of those annoying everlasting YouTube Ads once and for all. YT should give the user the chance of skipping all of them or place them in a container with a close button, that way once we close it, we won't be bothered with more ads anymore. It is not easy to be watching a JavaScript tutorial for example, and get invaded by an ad in the middle of a function explanation, it sucks!

Many thanks for the work and efforts doing for the upcoming fixes, you guys rock! **Brave mode ON!**

**Comment by GewoonJaap** [comment]
![image](https://user-images.githubusercontent.com/33700526/85834730-2b6fa000-b794-11ea-9b0e-d629d189612c.png)
![image](https://user-images.githubusercontent.com/33700526/85834831-54903080-b794-11ea-9a4a-fde31b1fa399.png)

Getting ads sometimes on YouTube (Netherlands): Versie 1.10.97 Chromium: 83.0.4103.116 (Officiële Versie) (64-bit)

**Comment by radocisar** [comment]
1) Pre-roll
2) Windows 10.0.18363 Build 18363
3) No
4) No
5) Default
6) No

**Comment by superspreader** [comment]
I am experiencing the issue as well. Here's some details:

- Pre-roll ads only
- Windows 10 64-bit build 17134.1550
- Extensions: 1Password, ExpressVPN
- Connected through ExpressVPN
- No custom/extra filters in Brave adblock

Thank you for your work.

**Comment by almindor** [comment]
Same as others:

Pre-roll ads only
Arch Linux updated to latest
Extensions: Disabled all to ensure
Connected directly
No custom/extra filters in Brave adblock

**Comment by A248** [comment]
For those searching this issue and coming here, I had a similar issue. Started happening today - yesterday, there were no ads.

Disabling the **Google Translate** extension solved the issue.

**Comment by almindor** [comment]
> For those searching the web and coming here, I had a similar issue. Started happening today - yesterday, there were no ads.
> 
> Disabling the **Google Translate** extension solved the issue.

I don't have google translate even installed...

**Comment by canvero** [comment]
I have been seeing pre-roll ads on YT in Brave since yesterday, never before.

1. only pre-roll as far as i'm aware (skippable)
2. Ubuntu 18.04.4
3. No extensions
4. No VPN
5. Default Shields
6. No additional filters in brave://adblock

Brave Version 1.10.93 Chromium: 83.0.4103.106 (Official Build) (64-bit)
Location:Netherlands

Perhaps this info helps. Thank you for looking into this.

**Comment by Xtortion** [comment]
Ads are showing here as well on YouTube again with Shield enabled.

No extensions, 
No VPN, 
Default Shield

Version: 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)
Location: The Netherlands

**Comment by darkin1** [comment]
Same here

No extensions,
No VPN,
Default Shield

Wersja 1.9.68 Chromium: 81.0.4044.138 (Official Build) unknown (64-bit)
Location: Poland

**Comment by gabrielacorona** [comment]
I've been seeing pre-roll ads on youtube using Brave. It started this week but I didn't seem to have this problem before.

only pre-roll as far as i'm aware (skippable)
MacOS 10.14.6 
No VPN
Default Shields
No additional filters in brave://adblock
Version 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)
Location: Mexico

If it's needed I can reproduce the issue since I will switch to nightly.
Thank you for looking into this

**Comment by ezranbayantemur** [comment]
Same here. 
I'm gonna hang myself because of YouTube Premium ads.

**Comment by micahn** [comment]
Been dealing with this for about 2 weeks now with 2 of my machines. i found that it is based on my login. logging out or using a private brave window i do not see any ads. 

PC1:
pre-roll - skippable. have not noticed any in video ads
Windows 10 - 1909 18363
no VPN
all brave settings default.
Version 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)
Location USA

PC2:
originally i had non-skippable pre-roll ads. however as of yesterday i have not had any ads with this machine. unsure if it's fixed or im just getting lucky. posting just for more info.
Ubuntu 20.04
no VPN
all brave settings default.
Version 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)
Location USA

**Comment by stendarr** [comment]
Pre-roll skippable ads for the past few days, currently on version 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit).
The OS is Debian testing, the shield settings are: scripts allowed, cross site cookies blocked, cross site trackers blocked, and fingerprinting blocked - all other settings are default.

Definitely gonna use Firefox with an ad blocker extension from now on.

**Comment by ryanbr** [comment]
If you're seeing ads, 

1. Make sure, `Subresource Filter Rules` is on: Version: 9.13.0 in `brave://components/`
2. Clear site-settings/Clear Data for youtube.com, and re-login.
3. Try opening youtube in private mode, and re-test.  

Tested with `https://www.youtube.com/watch?v=erQ_9yEz0ls`  (Mr Beasts, I Bought The World's Largest Firework ($600,000). Get 2 Ads in Chrome, Brave went straight to the video.

 Brave on the Left. Chrome on the right.
![comparison](https://user-images.githubusercontent.com/1659004/86982155-aeedb000-c1dc-11ea-8a59-006b90fd349d.png)

**Comment by ryanbr** [comment]
We have an additional fix in Brave Beta. which will be due out next week.

**Comment by amiremami** [comment]
I experience pre roll ads on many videos on Brave. I hope the fix will release to main Brave browser soon.

**Comment by antonok-edm** [comment]
This is resolved thanks to work from @ryanbr and others in the filter list community.

**Comment by severus-tux** [comment]
> This is resolved thanks to work from @ryanbr and others in the filter list community.

Nope. I am seeing YouTube ads on my iPad running iOS 14. 
Both preroll ads and banners. I’ll add more screenshots if I encounter them again. 


![EAADCA5D-FBA4-47EB-A01D-2633B6ED2B17](https://user-images.githubusercontent.com/21301040/102581403-7f958480-4126-11eb-99bd-c49bbe006b8c.jpeg)

**Comment by ryanbr** [comment]
@severus-tux note that Brave IOS doesn't have cosmetic filtering yet

Follow https://github.com/brave/brave-ios/issues/2683

**Comment by nithinkodadhavadee** [comment]
Okay fine, this thing is occurring quite frequently.  I didn't get any ads in between the video. It wasn't the banners. I get a video ad at the beginning or the end of the video. I'm not sure if this was a thing back in 2019, multiple ads in a video, as far as I remember it was just one ad in the video back then. I don't get this ad every time, I got it two times and am not getting any in that video. one ad just pops up here and there like four or five a day and I noticed it yesterday and today. It is a different video every time.


![Screenshot_20210515_050240](https://user-images.githubusercontent.com/50230678/118344091-310bdb00-b54a-11eb-966c-153748c30938.png)


![Screenshot_20210515_051149](https://user-images.githubusercontent.com/50230678/118344094-336e3500-b54a-11eb-8073-fa9d608f561c.png)

I use this 
Version 1.22.70 Chromium: 89.0.4389.105 (Official Build) (64-bit)
on an Arch Linux. 

I've tried a lot but couldn't reproduce this, it just happens. 

In some videos, I used to get a blank white screen with a skip button. but haven't seen that in quite a while.


> **What I need from the users trying to help debug the issue:**
> 
> * Test in private mode with no extensions enabled, with only Sheilds enabled,
> * Clear Youtube cookies first in the options, then visit the problematic youtube site.
> * A Screenshot of the shields window open and the shields cross-site trackers being listed., showing the ad in the background.  Like so: https://imgur.com/a/Ms9BT5Q  (I have no ad showing in my case, because I can't replicate it)
> * Go into Shields / Cross-site trackers.
> 
> 1. Ctrl-A (Select all Cross-site trackers)
> 2. Crtl-C (Copy to Clipboard)
> 3. Ctrl-V (Paste) into pastebin.com,
> 
> Like so: https://pastebin.com/18EAphvt (For Privacy, trim each line leaving the first 50-60 chars of each line or so)

@ryanbr There are more than 700 lines when I try to copy-paste the whole list of all the trackers blocked, and I'm not sure what I can share among those and what I can't.

**Comment by ryanbr** [comment]
youtube has implemented a new method of serving ads, we're still investigating this. @nithinkodadhavadee

**Comment by nithinkodadhavadee** [comment]
anything that I can help you guys with?

**Comment by Vista2003** [comment]
> Okay fine, this thing is occurring quite frequently.  I didn't get any ads in between the video. It wasn't the banners. I get a video ad at the beginning or the end of the video. I'm not sure if this was a thing back in 2019, multiple ads in a video, as far as I remember it was just one ad in the video back then. I don't get this ad every time, I got it two times and am not getting any in that video. one ad just pops up here and there like four or five a day and I noticed it yesterday and today. It is a different video every time.
> 
> 
> ![Screenshot_20210515_050240](https://user-images.githubusercontent.com/50230678/118344091-310bdb00-b54a-11eb-966c-153748c30938.png)
> 
> 
> ![Screenshot_20210515_051149](https://user-images.githubusercontent.com/50230678/118344094-336e3500-b54a-11eb-8073-fa9d608f561c.png)
> 
> I use this 
> Version 1.22.70 Chromium: 89.0.4389.105 (Official Build) (64-bit)
> on an Arch Linux. 
> 
> I've tried a lot but couldn't reproduce this, it just happens. 
> 
> In some videos, I used to get a blank white screen with a skip button. but haven't seen that in quite a while.
> 
> 
> > **What I need from the users trying to help debug the issue:**
> > 
> > * Test in private mode with no extensions enabled, with only Sheilds enabled,
> > * Clear Youtube cookies first in the options, then visit the problematic youtube site.
> > * A Screenshot of the shields window open and the shields cross-site trackers being listed., showing the ad in the background.  Like so: https://imgur.com/a/Ms9BT5Q  (I have no ad showing in my case, because I can't replicate it)
> > * Go into Shields / Cross-site trackers.
> > 
> > 1. Ctrl-A (Select all Cross-site trackers)
> > 2. Crtl-C (Copy to Clipboard)
> > 3. Ctrl-V (Paste) into pastebin.com,
> > 
> > Like so: https://pastebin.com/18EAphvt (For Privacy, trim each line leaving the first 50-60 chars of each line or so)
> 
> @ryanbr There are more than 700 lines when I try to copy-paste the whole list of all the trackers blocked, and I'm not sure what I can share among those and what I can't. 
> 
> 
> should I open this issue? 

If it's reappearing again, I would open a new ticket. Regarding what happened in 2019, ads would only play at the start and sometimes I would get an ad above suggested videos.

In the meantime, after flagging it as a workaround to this problem, use Unlock Origin along side Brave.

**Comment by stefanolomo** [comment]
Hi just had the same problem. **Cleaning the cache** and **removing google docs extension** seems to fix it. For some reason and somehow it looks like google is detecting adblocker via extensions
