### ISSUE TITLE
`New chat` icon should be the `Erase conversation history` icon, not a `+` sign

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#33485]
## Description 

`New chat` icon should be the `Erase conversation history` icon, not a `+` sign

## Steps to Reproduce

1. install `1.61.3`
2. launch Brave
3. enable Brave Leo in `brave://flags`
4. click `Relaunch`
5. click on `Brave Leo` in the sidebar
6. click on `Accept and begin`
7. click on the 3-dots menu in the upper right

## Actual result:

<img width="321" alt="Screen Shot 2023-10-06 at 5 37 47 PM" src="https://github.com/brave/brave-browser/assets/387249/85cf97fa-f389-46df-820f-f7af1744ef1b">

## Expected result:

<img width="225" alt="Screen Shot 2023-10-06 at 5 44 50 PM" src="https://github.com/brave/brave-browser/assets/387249/4cd41113-ac6d-41e1-8952-f2f19ccb1114">

## Reproduces how often: 

100%

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@bbondy @mattmcalister @petemill @nullhook @brave/qa-team

**Comment by kjozwiak** [comment]
The above requires `1.60.105` or higher for `1.60.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.60.105 Chromium: 119.0.6045.59 (Official Build) (64-bit)
-- | --
Revision | a39727aa81373a09a915478fcb35826242c37335
OS | Windows 10 Version 22H2 (Build 19045.3570)
```

### Confirmed the `New chat` menu item's icon is correct

![image](https://github.com/brave/brave-browser/assets/387249/bb324ba0-7938-4990-9ca2-52f0bd09da0d)
