### ISSUE TITLE
[Speedreader] TTS is skipping text to the bottom and missing the content.

### ISSUE THREAD

**Issue by boocmp** [brave/brave-browser#33496]
## Steps to Reproduce

   1.  Enable TTS, ```--enable-features=Speedreader:tts/true```
   2.  Navigate to nytimes.com (e.g. https://www.nytimes.com/2023/10/05/us/biden-border-wall-waiver.html)
   3.  Select TTS panel in the speedreader toolbar and click 'Play'

## Actual result:

Player skips most of the content.

## Expected result:

Player should play from the beginning.

## Reproduces how often: 
Easily

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.61.60 Chromium: 119.0.6045.105 (Official Build) beta (64-bit)
-- | --
Revision | 1ecda441378e2e473fd84b38456413224121751c
OS | Windows 11 Version 22H2 (Build 22621.2428)
```

1. Installed 1.61.60
2. launched Brave with `--enable-features=Speedreader:tts/true` to enable `Text to speech`
3. visited https://www.nytimes.com/2023/10/05/us/biden-border-wall-waiver.html in a new tab
4. clicked on `Speedreader` icon in the URL bar
5. clicked `TTS ` (headphone) button 

Actual results: Some text was skipped (`The decisions underscore......`)

https://github.com/brave/brave-browser/assets/98358127/ea76ece8-9108-42a2-a0ae-e55aa28b5daf
