### ISSUE TITLE
Add command line to disable the PDFJS extension

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#335]
`--disable_pdfjs_extension`

**Comment by srirambv** [comment]
Blocked on #1253

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.14 Chromium: 70.0.3538.54 (Official Build) beta(64-bit)
-- | --
Revision | 4f8e578b6680574714e9ed3bb9f02922b4dde40d-refs/branch-heads/3538@{#937}
OS | Linux

* PDFJS appears as component under `brave://components`
