### ISSUE TITLE
Wrong active item state after adding another item

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#33516]
## Steps to Reproduce

   1. Launch with clean profile
   2. Remove bookmark item from sidebar
   3. Activate reading list item
   4. Add back bookmarks item
   5. Check current active panel item icon

## Actual result:

Bookmark icon is activated one while reading list panel is opened

## Expected result:
Reading list icon should be active one

## Reproduces how often: 

Easy

## Brave version (brave://version info)

`1.61.x`, `1.60.x`

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.60.95 Chromium: 118.0.5993.88 (Official Build) beta (64-bit)
-- | --
Revision | d65c9c374e175c06c50025db46cf953fd200e9cc
OS | Windows 10 Version 22H2 (Build 19045.3570)

```

Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/33516#issue-1932506597, ensured that the sidebar index is being correctly updated when removing/re-adding the `Bookmark` while `Reading List` is opened as per the following:

- Reproduced the issue on `1.60.85` , `Bookmark` is active while re-adding it on the sidebar
- Confirmed that `Bookmark` is NOT active while re-adding it on the sidebar on `1.60.95` 

**`1.60.85`** | **`1.60.85`**
--------------|-----------------
![image](https://github.com/brave/brave-browser/assets/38657976/d10ef626-ae74-4c28-ba54-dd87c8d76b24) | ![image](https://github.com/brave/brave-browser/assets/38657976/07c8b96e-260c-4fce-8acb-5d86ca0ca1b3)



**`1.60.95`** | **`1.60.95`**
--------------|-----------------
![image](https://github.com/brave/brave-browser/assets/38657976/7d79f340-88e5-4b68-abf0-bbab4f34dce0) | ![image](https://github.com/brave/brave-browser/assets/38657976/f26f0ed4-06d2-4a93-80fc-280601075a02)
