### ISSUE TITLE
Brave forgetful browsing option missing on Brave 1.58.137 Chromium: 117.0.5938.153 (Official Build) (64-bit)  

### ISSUE THREAD

**Issue by ZOASR** [brave/brave-browser#33519]
Brave forgetful browsing option missing on latest version for Brave on Win11 Pro

## Steps to Reproduce

   1. Browse any site an open shields pane
   2. Open sheilds settings page
## Actual result:
![Screenshot 2023-10-09 160638](https://github.com/brave/brave-browser/assets/44146518/b740e4f2-30db-41d7-a537-8dbeeee44065)
![Screenshot 2023-10-09 160740](https://github.com/brave/brave-browser/assets/44146518/d921855f-0790-4f5f-b7f9-dd75a90796b9)

## Brave version (brave://version info)

1.58.137 Chromium: 117.0.5938.153 (Official Build) (64-bit) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? - Yes
- Can you reproduce this issue with the beta channel? - N/A
- Can you reproduce this issue with the nightly channel? - N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? Yes

**Comment by sandrocarval** [comment]
In one of the latest updates the option was removed from MacOS and Windows versions. In Linux (running Ubuntu) it still shows up. I am running version 1.60.110 on all of them.

Mac:

<img width="520" alt="Captura de Tela 2023-11-07 às 08 03 11" src="https://github.com/brave/brave-browser/assets/16933/7617054c-4bc8-402f-a113-c78c1c0e03a3">

<img width="398" alt="Captura de Tela 2023-11-07 às 08 06 37" src="https://github.com/brave/brave-browser/assets/16933/1d12df5a-0739-488c-902a-5c51f6a07a5d">

<img width="701" alt="Captura de Tela 2023-11-07 às 08 13 18" src="https://github.com/brave/brave-browser/assets/16933/5b1dad4b-aacb-4822-9002-26d978740da3">

Linux:

![Screenshot from 2023-11-07 08-08-24](https://github.com/brave/brave-browser/assets/16933/ff5691f2-1d6b-4e59-a112-b8f4408d00c2)

![Screenshot from 2023-11-07 08-07-52](https://github.com/brave/brave-browser/assets/16933/7dd34b94-a510-4be2-86c0-d6b922fdc4a8)

![Screenshot from 2023-11-07 08-09-03](https://github.com/brave/brave-browser/assets/16933/0bf19f08-eb4b-4fa9-80d5-48979f04802c)

**Comment by ZOASR** [comment]
> In one of the latest updates the option was removed from MacOS and Windows versions. In Linux (running Ubuntu) it still shows up. I am running version 1.60.110 on all of them.
> 
> Mac:
> 
> <img alt="Captura de Tela 2023-11-07 às 08 03 11" width="520" src="https://user-images.githubusercontent.com/16933/281017040-7617054c-4bc8-402f-a113-c78c1c0e03a3.png"> <img alt="Captura de Tela 2023-11-07 às 08 06 37" width="398" src="https://user-images.githubusercontent.com/16933/281017218-1d12df5a-0739-488c-902a-5c51f6a07a5d.png"> <img alt="Captura de Tela 2023-11-07 às 08 13 18" width="701" src="https://user-images.githubusercontent.com/16933/281018847-5b1dad4b-aacb-4822-9002-26d978740da3.png">
> Linux:
> 
> ![Screenshot from 2023-11-07 08-08-24](https://user-images.githubusercontent.com/16933/281018911-ff5691f2-1d6b-4e59-a112-b8f4408d00c2.png)
> 
> ![Screenshot from 2023-11-07 08-07-52](https://user-images.githubusercontent.com/16933/281018944-7dd34b94-a510-4be2-86c0-d6b922fdc4a8.png)
> 
> ![Screenshot from 2023-11-07 08-09-03](https://user-images.githubusercontent.com/16933/281018973-0bf19f08-eb4b-4fa9-80d5-48979f04802c.png)

Thanks, i also as soon as i updated to 1.59 the option returned back again
I'm closing this issue now as i forgot to when updating to 1.59.

**Comment by sandrocarval** [comment]
@ZOASR Why did you close the issue? It is happening in the latest version.

**Comment by sandrocarval** [comment]
Brave has just been updated to 1.60.114. The issue with "forgetful browsing" / "Forget me when I close this site" being removed from some operating systems still persists.

**Comment by ahydronous** [comment]
I have this issue as well.

NixOS 23.05
Brave 1.60.118 via Flathub
All the relevant flags are "enabled" in brave://flags

**Comment by ahydronous** [comment]
@LaurenWags 

Apologies for tagging you but I don't know how to specifically find a Brave linux dev, and you're the first member I could find.

It seems this issue has been flying under the radar. Would you be able to assign / mention a proper member? It'd be a tremendous help!

**Comment by LaurenWags** [comment]
Hi @ahydronous - I'm not experiencing this on macOS with `1.60.118`, but I've asked some others on @brave/qa-team to try.

<img width="448" alt="Screenshot 2023-11-28 at 4 43 32 PM" src="https://github.com/brave/brave-browser/assets/28145373/a13bb915-6f55-41d1-bd10-a1251b1e1808"> | <img width="1189" alt="Screenshot 2023-11-28 at 4 43 56 PM" src="https://github.com/brave/brave-browser/assets/28145373/d520af9b-a03e-4f8f-a5fc-2819c06d2d21">
-- | --

cc @rebron as well for prioritization.

**Comment by ahydronous** [comment]
Thanks for helping us out!

For what its worth (whoever ends up working on this):
- I'm also not seeing the option in iOS Brave 1.60 on iOS 17.1.1, although I have the suspicion the Brave client on iOS just misses certain features as it has to be based on WebKit and Swift / ObjC

- I do see the feature in Brave 1.60.118 on Windows 11 update 23.

**Comment by LaurenWags** [comment]
@ahydronous iOS is a different code base currently, so sometimes the features don't exactly line up. The issue to get this feature on iOS can be tracked via https://github.com/brave/brave-ios/issues/6931.

I'm curious, on the machine where you aren't seeing this, can you post a screenshot of your brave://verison page? I'd like to see what griffin studies are listed on this page.

**Comment by ahydronous** [comment]
- Brave - 1.60.118 Chromium: 119.0.6045.163 (Official Build) unknown (64-bit) 
- Revision - b0599b790dbdfe28428202afe2b54758a044ccfc
- OS - Linux
- JavaScript - V8 11.9.169.6
- User Agent - Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
- Command Line - /app/brave/brave --disable-features=WebAssemblyTrapHandler,DesktopPWAsRunOnOsLogin --no-default-browser-check --disable-domain-reliability --enable-dom-distiller --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --variations-insecure-server-url=https://variations.brave.com/seed --disable-features=DesktopPWAsRunOnOsLogin,WebAssemblyTrapHandler --flag-switches-begin --ozone-platform-hint=auto --flag-switches-end --component-updater=url-source=https://go-updater.brave.com/extensions --ozone-platform=wayland
- Executable Path - /app/brave/brave
- Profile Path - /home/redacteduser/.var/app/com.brave.Browser/config/BraveSoftware/Brave-Browser/Default

**Comment by LaurenWags** [comment]
@ahydronous so no section called "Active Variations" like I have?

<img width="1004" alt="Screenshot 2023-11-29 at 3 21 06 PM" src="https://github.com/brave/brave-browser/assets/28145373/cdf858a7-e2cd-4c86-9f79-edc241a0f472">

**Comment by ahydronous** [comment]
"Profile Path" is the last line for me

**Comment by LaurenWags** [comment]
@ahydronous thanks, so you're not getting any griffin studies (which is how this feature is enabled currently). I am unsure why this is.

You can try enabling this feature manually via flags in the mean time at brave://flags/#brave-forget-first-party-storage.

**Comment by ahydronous** [comment]
That made it work!

If I'm needed to chase down the Griffin studies rabbit hole, let me know!
If I had to guess it probably has something to do with either the way Linux launches binaries, or specifically the Brave flatpak..

**Comment by LaurenWags** [comment]
Thanks for the extra info @ahydronous - I've added some labels and will raise this issue in our next triage meeting to see if we can get some investigation going here.

**Comment by LaurenWags** [comment]
@ahydronous discussed this with some folks internally today and they asked that you navigate to `brave://flags/#enable-benchmarking` and see if this is enabled or disabled. Mind visiting this page and grabbing a screenshot of that flag value?

**Comment by bsclifton** [comment]
This should be rolled out to 100% now 👍 Closing as fixed

cc: @ShivanKaul
