### ISSUE TITLE
Extension permission control disable extension function on brave 1.59+ (Chrome 118)

### ISSUE THREAD

**Issue by fhoshino** [brave/brave-browser#33511]
## Description 
The following extension, Lazy Chrome,
https://chrome.google.com/webstore/detail/lazy-chrome/boijmdgjfcoancndoiclnglhjakeopch
has a function to use hot key for "select and search", requires site read/write access, it works before 1.59 and stopped working now.

## Steps to Reproduce

   1. Setting hot key "Alt + Q" for "select and search" function
   2. Pressing "Alt + Q" to call the function in the extension
   3.  Nothing happens.

## Actual result:

Nothing happens.

## Expected result:
The function of the extension should be called.

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave	1.59.115 Chromium: 118.0.5993.54 (Official Build) (64-bit) 
Revision	82b05012fc6b5ab8535cf283db6856ad5eedd7eb
OS	Windows 10 Version 1809 (Build 17763.292)
JavaScript	V8 11.8.172.12
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Command Line	"C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --disable-domain-reliability --enable-dom-distiller --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --variations-insecure-server-url=https://variations.brave.com/seed --flag-switches-begin --disable-smooth-scrolling --flag-switches-end --component-updater=url-source=https://go-updater.brave.com/extensions
Executable Path	C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path	C:\Users\f\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Active Variations	AllowCertainClientHintsStudy:Enabled
BraveAdblockMobileNotificationsListDefault:Enabled
BraveAds.AdServingStudy:DefaultAdNotificationsPerHour=10/MaximumAdNotificationsPerDay=100/MaximumInlineContentAdsPerHour=6/MaximumInlineContentAdsPerDay=20/AdServingVersion=2
BraveAutoTranslateStudy:AutoTranslateDisabled
BraveDebounceStudy:Enabled
BraveForgetFirstPartyStorage:Enabled
BraveGoogleSignInPermissionStudy:Enabled
BraveHttpsByDefaultRolloutStudy:Enabled
BraveP3AConstellationReleaseRollout:Enabled
BraveRewardsWebUiPanelStudy:Enabled
BraveScreenFingerprintingBlockerStudy:Enabled
BraveSearchAdStudy:Default
ClampPlatformVersionClientHint:Disabled
CookieListDefaultStudy:Enabled
CrossPlatformVPNStudy:Enabled
Default1pBlockingStudy:Disabled
DisableReduceLanguage:Enabled
EphemeralStorageStudy:Enabled
FirstPartyEphemeralDomainBlockStudy:Enabled
ForceDisableBlinkFeatures:Enabled
PartitionBlinkMemoryCacheStudy:Enabled
PartitionConnectionsByNetworkIsolationKeyStudy:Enabled
PermissionLifetimeReleaseStudy:Enabled
PrettyPrintJSONDocument:Disabled_EmergencyKillSwitch
SpeedreaderReleaseStudy:Enabled
UserActivityStudy:Triggers
WhatsNewStudy:Enabled

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? not tested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? no

**Comment by fhoshino** [comment]
Figured out due to change in brave's extension permission control
https://github.com/frog1014/lazy_chrome/issues/22

**Comment by bsclifton** [comment]
Thanks for following up @fhoshino - I'll close this out
