### ISSUE TITLE
Market cap value is not shown properly in panel

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#33515]
## Description 

Market cap value is not shown properly in panel

## Steps to Reproduce

   1. Open Market
   2. Select a token
   3. Market cap value is not shown properly and can't be scrolled horizontally

## Actual result:

![BNB](https://github.com/brave/brave-browser/assets/17010094/271628d2-0af6-45b9-a6de-a21a24addde9) | ![BTC](https://github.com/brave/brave-browser/assets/17010094/0a8e5174-e7bd-4c24-a8ed-992415d41e86) | ![OKB](https://github.com/brave/brave-browser/assets/17010094/ef295e2c-1bc5-4f86-bd12-1b4ca9ad2874)
-- | -- | --

## Expected result:
Show all values withing panel view

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.59.115 Chromium: 118.0.5993.54 (Official Build) (64-bit)
-- | --
Revision | 82b05012fc6b5ab8535cf283db6856ad5eedd7eb
OS | All

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel

**Comment by Douglashdaniel** [comment]
This was fixed via https://github.com/brave/brave-core/pull/20359
Closing as duplicate.
