### ISSUE TITLE
AI Chat settings default model selection

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#33527]
Create a preference that will determine which model new conversations start with. We should use the model key for the preference value.

Default model should be Claude Instant when the user is premium.

Settings page gets a model-selection dropdown which reflects that preference. Default is llama 2 13b.

<img width="481" alt="image" src="https://github.com/brave/brave-browser/assets/741836/7463b199-bf56-4506-9d5b-6dce7e545763">

<img width="356" alt="image" src="https://github.com/brave/brave-browser/assets/741836/f5c9e1cf-e82b-4320-9495-646305c2bda5">

https://www.figma.com/file/h7fKSJF2P556bZWfyLTfwD/Brave-Leo-MVP?type=design&node-id=1105-28709&mode=design&t=CANcYW0iZBYnyAQX-0

**Comment by petemill** [comment]
We should add those descriptions to the regular dropdown too. (and you could add the unlock item there for premium users).

- Strings in the figma
- Build the string key in TS (both in AI Chat and Settings)
- Add the strings in both C++ webuis
- Add a big TODO to all this code that we should figure out how to share the UI and the strings (and the data handlers via mojom) between the 2 versions.

**Comment by kjozwiak** [comment]
The above requires `1.60.105` or higher for `1.60.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.60.106 Chromium: 119.0.6045.59 (Official Build) (64-bit)
-- | --
Revision | 16064193dde8c55f64dabd32f125c0cd9380f96a
OS | Windows 11 Version 22H2 (Build 22621.2428)
```

1. Installed 1.60.106
2. launched Brave 
3. enabled `#brave-ai-chat` via `brave://flags`
4. opened `brave://settings/leo-assistant`
5. confirmed `IIama2 13b` is selected as a default selection in the `Default model for new conversations`
6. selected `IIama2 70b` and `Claude Instant` 
7. confirmed the 3 dots menu still shows `IIama2 13b`
8. clicked `Go Premium` via ellipsis (3 dots) menu inthe Leo sidepanel
9. subscribed to Brave Leo plan on account.brave.com
10. confirmed `claude -instant-v1` is selected automatically

example | example | example | example | example 
---- | ------- | ------- | ------- | -----
![image](https://github.com/brave/brave-browser/assets/98358127/a66d1640-ac5a-4ab1-8d21-032ff5f89fdd)|![image](https://github.com/brave/brave-browser/assets/98358127/decfef3b-d864-4dad-b088-6f1a647b1ed6)|![image](https://github.com/brave/brave-browser/assets/98358127/37a1a94b-c984-4100-ab07-d9653dfe5951)|![image](https://github.com/brave/brave-browser/assets/98358127/fd0320da-92af-4cef-a601-ff1fdcb8d3d0)|![image](https://github.com/brave/brave-browser/assets/98358127/4e78338b-883e-4b74-a711-e99722c0d5b8)


`Dark` | `Light`
![image](https://github.com/brave/brave-browser/assets/98358127/d217a4a8-667b-4994-90da-ee6294223513)|![image](https://github.com/brave/brave-browser/assets/98358127/4e63e845-3b29-4efd-9b24-6849a230efbd)

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version

```
Brave	1.60.109 Chromium: 119.0.6045.59 (Official Build) (64-bit) 
Revision	fc399c7c433510eb03c2b35281bf8935804b99de
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
- Ensured that Claude Instant is default model when user is premium
- Ensured that starting a new chat will create a new Claude chat instance for premium users
- Ensured that all chat models are unlocked in selection screen for premium users

Example | Example | Example
-|-|-
![Screenshot 2023-10-31 at 11 48 02 AM](https://github.com/brave/brave-browser/assets/17885425/67473dc1-3522-42dd-8365-99007a5416a7) | ![Screenshot 2023-10-31 at 11 48 11 AM](https://github.com/brave/brave-browser/assets/17885425/b336359d-543b-4906-9507-ded894a17650) | ![Screenshot 2023-10-31 at 11 51 43 AM](https://github.com/brave/brave-browser/assets/17885425/626b30a2-6afd-4af9-92d5-151a3521eb84)
