### ISSUE TITLE
Add publishining extension to the blessed extensions list

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#33523]
Publisher extension should have access to IPFS Extension API
cc @meandavejustice @vadimstruts @lidel

**Comment by cypt4** [comment]
@meandavejustice please provide us ID we should use

**Comment by meandavejustice** [comment]
[markdown-publish](https://github.com/JusticeEngineering/markdown-publish) `ioajeblglaafjfaepefmbohjlncbaaof`

[link-list](https://github.com/JusticeEngineering/link-list) `beppdjjojnaodnioccaagpgngahdejnk`
