### ISSUE TITLE
Add support to nano defender

### ISSUE THREAD

**Issue by leobel96** [brave/brave-browser#3352]
In brave/adblock repository none replies to issues, so I reopen it here.
I've seen that, years ago, you have tried to add support for anti-adblock-killer but it is a discontinued project. To block anti-adblockers, I suggest you nano defender(https://jspenguin2017.github.io/uBlockProtector/). It works pretty well with uBlock origin and I think it can be adapted to work with brave's adblock.

**Comment by tomlowenthal** [comment]
Anyone is welcome to install this extension, but we're not currently working on ad-blocker-blocking.

**Comment by leobel96** [comment]
@tomlowenthal It now supports only uBlock and nano AdBlock, so It can't be installed with brave adblock as extension.

**Comment by tomlowenthal** [comment]
Then you'd have to use it with one of those other tools.

**Comment by leobel96** [comment]
I mean: why don't you integrate in brave a component similar to nano defender to block adblock blockers, perhaps directly forking nano defender? Sorry if I wasn't clear.

**Comment by tomlowenthal** [comment]
We're not currently working on ad-blocker-blocking.

**Comment by leobel96** [comment]
Ok, no problem :)
