### ISSUE TITLE
perf: CPU usage issue related to adblock changes 

### ISSUE THREAD

**Issue by atuchin-m** [brave/brave-browser#33520]
perf thread: https://bravesoftware.slack.com/archives/C3T9S9WKD/p1695901547243849

The PR that makes issues: https://github.com/brave/brave-core/pull/19946/files

1. The initial problem: blocking work on UI thread, fixed by https://github.com/brave/brave-core/pull/20284
2. The following problem: the amount of total CPU work was increased by ~20%

![image](https://github.com/brave/brave-browser/assets/45488748/63a5ce43-5e99-4841-9b70-97f79246be5c)
![image](https://github.com/brave/brave-browser/assets/45488748/7c8a4816-f3d3-4b50-a734-f07e52962abd)
![image](https://github.com/brave/brave-browser/assets/45488748/993eb4e6-c05f-4ad0-91af-45b1d0205df0)

**Comment by kjozwiak** [comment]
Closing as https://github.com/brave/brave-core/pull/20442 was merged into `master` and will be uplifted into `1.60.x` via https://github.com/brave/brave-core/pull/20459.

**Comment by atuchin-m** [comment]
Adding some adblock metrics to the perf dashboard: https://github.com/brave/brave-browser/issues/34480
