### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by MrPeteH** [brave/brave-browser#33530]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.58.137 Chromium: 117.0.5938.153
Operating System: Windows NT 10.0.19045

URL (if applicable) where crash occurred:

Can you reproduce this crash? not on same url...

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. go to web page with a PDF link
2. in this case, link was to: https://multimedia.3m.com/mws/media/603272O/respirator-selection-for-diisocyanates.pdf
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/24f80a00-52b7-d30a-0000-000000000000

**Comment by iefremov** [comment]
stale
