### ISSUE TITLE
Tor window keeps showing 1 notification on BR panel

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#3353]
## Description 

Tor window keeps showing 1 notification on BR panel

## Steps to Reproduce

   1. Clean profile, normal tab shows 1 notification which is dismissed when BR panel is clicked
   2. Open a Private tab, no notification ever shows up on BR panel
   3. Open a Tor tab, always has 1 rewards notification on BR panel which can't be dismissed as its disabled

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/52780816-1dbeec00-3071-11e9-9835-2484b472bcc0.png)

## Expected result:
Tor window should not show any rewards notification similar to private window

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.60.26 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes and on release as well

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
This looks fixed in 61.x with @mkarolin work on hiding the Brave Rewards icon as there's no Rewards icon in Tor Window at all.

**Comment by riastradh-brave** [comment]
This does not appear to be specific to private windows with Tor: I see it in private windows without Tor.

**Comment by srirambv** [comment]
>This does not appear to be specific to private windows with Tor: I see it in private windows without Tor, and I _don't_ see it in (some?) windows with Tor.

The notification on private window is because there is notification on normal window. If you clear the notification on normal window then it wont show up on Private window without Tor as well.

**Comment by NejcZdovc** [comment]
closing this one as on 0.63 we don't show rewards icon in tor window
