### ISSUE TITLE
Trusted Scriptlets don't work with Custom filters = permission : 1

### ISSUE THREAD

**Issue by Emi-HoloGhostRevisionist88** [brave/brave-browser#33535]

**Comment by antonok-edm** [comment]
@Emi-HoloGhostRevisionist88 can you confirm which version of Brave this is?

**Comment by Emi-HoloGhostRevisionist88** [comment]
I accidentally hit Enter, and submitted the message when I wanted to add quotes to the "permission" : 1, I edited my message but doesn't display!.

I have Brave 1.61.11, and just downloaded the scriptlets and noticed the permission, now my existing trusted-scriptlets are not working.

So I have to set the permission to 0, which is easy, but it means Android can't take advantage of the Trusted scriptlets, as uBlock planned it with [* - The user's own filters as seen in "My filters" pane in uBO's dashboard.](https://github.com/gorhill/uBlock/blob/0a18f758973f293bdc52c9ef8117d772fc9b0d23/assets/resources/scriptlets.js#L3608)

For example won't be set:

```
brave.com##+js(trusted-set-local-storage-item, test, test2)
brave.com##+js(trusted-set-cookie, test, test2)
```

if I go to resources.json and change the permission to 0, reload the scriptlets (by turning off and on any regional list). then it works.

**Comment by antonok-edm** [comment]
thanks @Emi-HoloGhostRevisionist88 

> I mean, I don't know if this was meant to be

Custom filters are definitely intended to be able to use trusted/permissioned scriptlets, so this is a bug.

I confirmed this is working prior to 1.61.10 so I suspect this is also a side effect of @atuchin-m's recent revert. That was for performance reasons; I will be catching up on it tomorrow and proposing a followup shortly.

**Comment by Emi-HoloGhostRevisionist88** [comment]
Nice to know that. thanks!
I don't mind editing the resources.json, I still have to do it to add a domain property to the trusted-set-cookie which uBlock didn't seem interested in implementing when I made the request and show them the 5 lines of code to do it, in the end, it is good to know the trusted scriptlets can be used in Android out of the box soon. 👍
