### ISSUE TITLE
Feature request: Open downloaded file without saving

### ISSUE THREAD

**Issue by marc1uk** [brave/brave-browser#3354]
## Description 
This was a requested feature in the brave-laptop repository that had quite a lot of upvotes, but seems to have been dropped with the archived repository. 
Often users will want to view a file once, and be done with it. Currently with Brave this requires saving the file, choosing a suitable location, navigating there in a file explorer, double-clicking the item, and then remembering to delete it later. Other browsers allow the option to 'Open (With)' when downloading a file, in which case the browser saves the file to a temporary location, opens the file, and clears the temporary directory on close. This would be a nice addition to Brave.

## Steps to Reproduce
Click a file. 

## Actual result:
You must save the file. Then show it in explorer. Then open it. Then delete it when done.

## Expected result:
You can choose to 'Open' the file, in which case Brave downloads to a temporary directory and automatically opens it (possibly giving the user the option of which program to open with, as this can vary). 

## Reproduces how often: 
Always

## Brave version (brave://version info)
Brave | 0.59.35 Chromium: 72.0.3626.81 (Official Build) (64-bit)
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS | Linux

### Reproducible on current release:
Not sure

### Additional Information
Move of Brave-laptop issue 1924: https://github.com/brave/browser-laptop/issues/1924

**Comment by eljuno** [comment]
Duplicate of #2153?

**Comment by marc1uk** [comment]
Yep. Damnit, I did search the issues first, not sure how I didn't find that.
