### ISSUE TITLE
Remove horizontal line on account selector dropdown

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#33544]
## Description 

Remove horizontal line on account selector dropdown

## Steps to Reproduce

   1. Create multiple accounts
   2. Open account selector on Swap screen
   3. Shows horizontal line

## Actual result:

![image](https://github.com/brave/brave-browser/assets/17010094/a51590f3-7da0-482c-b276-50c600caf7bb)

## Expected result:
No horizontal line in account selector

## Brave version (brave://version info)

<html>
<body>

Brave | 1.60.81 Chromium: 118.0.5993.54 (Official Build) beta (64-bit)
-- | --
Revision | 1efb3f333eb41cc34af46ca31fb33c30e0afbfae
OS | Windows 11 Version 22H2 (Build 22621.2283)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel

**Comment by paigexx** [comment]
Hello I would like to take this issue.

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.61.67 Chromium: 119.0.6045.105 (Official Build) beta (64-bit)
-- | --
Revision | `09cc687dc27ccd8acafeebf5af1dc620b4d9cb22`
OS | Windows 11 Version 22H2 (Build 22621.2506)

- Verified steps from [brave/brave-core#20550](https://github.com/brave/brave-core/pull/20550)
- Verified no horizontal line shown on account selector dropdown on Swap screen
![brave_sjzyoHa1UC](https://github.com/brave/brave-browser/assets/17010094/ff52b88d-77f1-4945-aa63-a9f1a6ff1bc3)

---------------------

**Verification passed on**

Brave | 1.60.81 Chromium: 118.0.5993.117 (Official Build) (64-bit)
-- | --
Revision | `09cc687dc27ccd8acafeebf5af1dc620b4d9cb22`
OS | Linux

- Verified steps from [brave/brave-core#20550](https://github.com/brave/brave-core/pull/20550)
- Verified no horizontal line shown on account selector dropdown on Swap screen
![Account](https://github.com/brave/brave-browser/assets/17010094/b207007a-96c9-4ad0-9470-dbe4dd584c49)

---------------------

**Verification passed on**

Brave | 1.60.81 Chromium: 118.0.5993.117 (Official Build) (arm64)
-- | --
Revision | `09cc687dc27ccd8acafeebf5af1dc620b4d9cb22`
OS | macOS Version 14.1 (Build 23B74)

- Verified steps from [brave/brave-core#20550](https://github.com/brave/brave-core/pull/20550)
- Verified no horizontal line shown on account selector dropdown on Swap screen
<img width="1840" alt="Screenshot 2023-11-07 at 5 59 45 AM" src="https://github.com/brave/brave-browser/assets/17010094/827a3b83-566b-4b3c-85eb-9499ff8891a5">
