### ISSUE TITLE
iOS does not set up locale resource loading correctly for certain locales

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-browser#33554]
This PR https://github.com/brave/brave-core/pull/19472/files changed the logic around setting the overriden outer bundle for iOS however it turns out this causes a locale-mismatch between Brave iOS & Chromium's supported localizations which will cause a CHECK to occur when those supported localizations dont match, such as `pt` vs `pt_BR`

See https://github.com/brave/brave-ios/issues/8213 for testing

**Comment by kjozwiak** [comment]
This was technically merged after the `1.58.x - Release #7` but was only needed for `iOS` as we're already on `1.59.x`.
