### ISSUE TITLE
YouTube appears offline when shields are up

### ISSUE THREAD

**Issue by IogaMaster** [brave/brave-browser#33560]
## Description 

Youtube videos are not working when shields are up.

## Steps to Reproduce

   1. Navigate to a video on youtube
   2. Turn on shields
   3. Boom

## Actual result:

![image](https://github.com/brave/brave-browser/assets/67164465/d995a5cd-8733-478b-adfd-346c84075400)

## Expected result:

Videos to play as normal ad free.

## Reproduces how often: 

Everytime, unless you turn off shields and turn them back on again. Then it works for 1-2 videos.

## Brave version (brave://version info)

1.57.62 Chromium: 116.0.5845.180 (Official Build) (64-bit) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
Yes
- Does the issue resolve itself when disabling Brave Rewards? 
No
- Is the issue reproducible on the latest version of Chrome? 
No

**Comment by bsclifton** [comment]
@IogaMaster looks like you're on an older version of Brave - can you please update to a newer version?

I have seen this when the adblocking fails on iOS before. I'm curious if old adblock rules or older code is not handling the experience properly. This might have the same root case as https://github.com/brave/brave-browser/issues/33493

Please let us know after you update! Thanks 😄

**Comment by bsclifton** [comment]
@IogaMaster OK great - thanks for sharing 😄 Please try updating and let us know if you're good to go

**Comment by nishu-murmu** [comment]
Issue also was seen in ArchLinux,
Updating brave would fix the issue.

**Comment by bsclifton** [comment]
Going to go ahead and close this - updating Brave should be the next thing we can try. If that does not work, we can re-open this issue. Thanks!

**Comment by IogaMaster** [comment]
@bsclifton Sorry for the late reply, an update to nixpkgs required a big rework of my system config.
I can confirm the issue is no longer present.
Thanks for your help!

**Comment by lewisst** [comment]
How can we update the IOS version? 
On Ipad I get this when running in desktop mode with latest from app store - 1.57.2

**Comment by IogaMaster** [comment]
> On Ipad I get this when running in desktop mode with latest from app store - 1.57.2

Wait for the next IOS update, I don't think there is anything you can do
