### ISSUE TITLE
NTP SI when opted-out counts towards `maximum_ads_per_day` when opted-in to rewards

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#33579]
## Steps to Reproduce

1. Clean profile:
2. Run Brave with `--enable-features=NewTabPageAds:maximum_ads_per_day/1`
3. View an NTP SI
4. Join Rewards
5. Serve a NTP SI

## Actual result:

Was not able to serve NTP SI

## Expected result:
Was able to serve NTP SI

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 1.59.117 Chromium: 118.0.5993.70 (Official Build) (64-bit)
-- | --
Revision | 766577bee8f040990afcb32677dcab38ffcf0f06
OS | Linux

Brave | 1.60.87 Chromium: 118.0.5993.70 (Official Build) beta (64-bit)
-- | --
Revision | 854c1e600054dfca6842cebaf729f100f4b0f066
OS | Linux

cc @tmancey @aseren

**Comment by tmancey** [comment]
Closing as this is working as expected and ads will start showing after the cap has cleared.
