### ISSUE TITLE
Getting `The Redemption Code you entered is invalid` message after click on `Get My Subscription`  button

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#3357]
## Description 

Found white testing 1839, follow up of #1839
Getting `The Redemption Code you entered is invalid` message after click on `Get My Subscription`  button for Barrons and Market watch promos.

## Steps to Reproduce

   1. Uninstall Brave to have clean install
   2. Install below setup files
     `BraveBrowserBetaSetup-64-be-test-dowjones-barrons.exe`
     `BraveBrowserBetaSetup-64-be-test-dowjones-marketwatch.exe`
     `BraveBrowserBetaSetup-64-be-test-dowjones-marketwatch (1).exe`
     `BraveBrowserBetaSetup-64-be-test-dowjones-marketwatch(1).exe`
     `BraveBrowserBetaSetup-64-be-test-dowjones-barrons(1).exe`
     `BraveBrowserBetaSetup-64-be-test-dowjones-barrons (1).exe`
   3. After brave launch click on `Get My Subscription` button

## Actual result:

![image](https://user-images.githubusercontent.com/38657976/52795100-14e11100-3097-11e9-88f9-c2b681beeae3.png)

![image](https://user-images.githubusercontent.com/38657976/52795252-67223200-3097-11e9-801a-f884922bb03d.png)

## Expected result:
Should open subscription page

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 0.60.29 Chromium: 72.0.3626.96 (Official Build) beta (64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Windows 10

### Reproducible on current release: 
- Does it reproduce on brave-browser dev/beta builds? Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional Information
@brave/legacy_qa @aekeus @emerick

**Comment by kjozwiak** [comment]
I quickly did a check on `macOS 10.14.2 x64` and it looks like MW & Barrons are accepting the promotion codes that we're passing them now. Seems like this is intermittent. About a ~week ago, I was getting the same thing @GeetaSarvadnya mentioned. Went through the following:

* Downloaded Brave-Browser-dowjones-barrons.pkg using `0.59.35 Chromium: 72.0.3626.81`
* Downloaded Brave-Browser-dowjones-marketwatch.pkg using `0.59.35 Chromium: 72.0.3626.81`

Downloaded the `0.60.44 Chromium: 72.0.3626.109` `pkg` and renamed the file to the following:
* `Brave-Browser-dowjones-barrons.pkg`
* `Brave-Browser-dowjones-marketwatch.pkg`

All four cases passed without any issues. Example:

<img width="866" alt="screen shot 2019-02-20 at 5 40 38 pm" src="https://user-images.githubusercontent.com/2602313/53130514-7e01d200-3538-11e9-8311-32c252f14d42.png">

<img width="919" alt="screen shot 2019-02-20 at 5 50 01 pm" src="https://user-images.githubusercontent.com/2602313/53130518-81955900-3538-11e9-81c9-e615b9923486.png">

@GeetaSarvadnya are you still having issues? Still seeing `The Redemption Code you entered is invalid`?

@LaurenWags @srirambv are you guys getting the `Subscription` button or are you guys still running into the issue where you're only seeing the `Download` button?

**Comment by LaurenWags** [comment]
@kjozwiak tried today, and looks like I'm getting the 'Get my Subscription' button, not 'Download Brave' as I was previously.
![Screen Shot 2019-03-15 at 9 52 46 AM](https://user-images.githubusercontent.com/28145373/54436049-353cd380-4708-11e9-84a6-1247b0255d58.png)
![Screen Shot 2019-03-15 at 9 54 58 AM](https://user-images.githubusercontent.com/28145373/54436175-6ae1bc80-4708-11e9-8162-2db3da3565ef.png)

**Comment by GeetaSarvadnya** [comment]
@kjozwiak Issue is still reproducible. But it's intermittent, I have tried twice 1st time it worked fine, 2nd time I got the message as `The Redemption code you entered is invalid`

![image](https://user-images.githubusercontent.com/38657976/54491010-ec8c4280-48e0-11e9-8f29-1da4027d7519.png)

**Comment by kjozwiak** [comment]
Thanks for the double check @GeetaSarvadnya & @LaurenWags. @mandar-brave this is the issue I was mentioning earlier in our meeting. Seems to be intermittent as @GeetaSarvadnya mentioned above. Sometimes it works and sometimes it can go down for a few days. @srirambv and @LaurenWags couldn't get the above working for a few days before it started working again.
