### ISSUE TITLE
Make NTP SI `kCountsResetTimeDelay` configurable via griffin/feature

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#33571]
This blocks testing of https://github.com/brave/brave-browser/issues/31551

`kCountsResetTimeDelay` was introduced via https://github.com/brave/brave-core/pull/19823

## Brave version (brave://version info)

Brave | 1.60.87 Chromium: 118.0.5993.70 (Official Build) beta (64-bit)
-- | --
Revision | 854c1e600054dfca6842cebaf729f100f4b0f066
OS | Linux

cc  @tmancey @aseren @petemill

**Comment by LaurenWags** [comment]
Discussing this one with @btlechowski as it relates to testing https://github.com/brave/brave-browser/issues/31551.

From my understanding https://github.com/brave/brave-browser/issues/31551 requires us to keep the browser open for 24hours. This really isn't feasible for us as we can't be stuck on testing a particular issue for that long. Making this value configurable will help and allow us to test easier. As far as I know, changing the clock while the browser is open will not yield the results that we need.

@petemill if our understanding is incorrect here, please let us know.

cc @kjozwiak @rebron

**Comment by kjozwiak** [comment]
The above requires `1.60.102` or higher for `1.60.x` verification. @btlechowski feel free to change the `QA/Yes` flag if needed as the above is basically needed to run through https://github.com/brave/brave-browser/issues/31551 easier rather than waiting the ~24hrs. I'm not sure if you want to add any verification notes within this one.

**Comment by btlechowski** [comment]
Verified with

Brave | 1.60.102 Chromium: 118.0.5993.96 (Official Build) beta (64-bit)
-- | --
Revision | 3598a9fc6b7752181feb25caa131bc386d6d054c
OS | Linux


#### opted out

Verified the initial time is reset after 1 minute
Flags used:
```
BraveNTPBrandedWallpaper:initial_count_to_branded_wallpaper/1/count_to_branded_wallpaper/5/reset_counter_after/1m
```

1st NTP SI on 2nd NTP:
![image](https://github.com/brave/brave-browser/assets/34715963/c76ac454-75ab-48a8-a652-04df319fcda4)

2nd NTP SI on 4th NTP:
![image](https://github.com/brave/brave-browser/assets/34715963/006a9a53-f36d-439c-b42c-71768a8471b7)


#### opted in

Flags used:
```
BraveNTPBrandedWallpaper:initial_count_to_branded_wallpaper/1/count_to_branded_wallpaper/5/reset_counter_after/1m
```

1st NTP SI on 2nd NTP:
![image](https://github.com/brave/brave-browser/assets/34715963/fd763f87-7aed-41b0-9f13-66321a2aff0e)


2nd NTP SI on 4th NTP:
![image](https://github.com/brave/brave-browser/assets/34715963/847d10d0-a428-4c3c-90fd-84ab30013e42)
