### ISSUE TITLE
[ads] Fix custom notification ads are displayed in the wrong position

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#33577]
![image](https://github.com/brave/brave-browser/assets/1188719/10e83a66-32ed-4fac-8ff9-bfbe9cae3c36)

As discussed we agreed to make the following changes in positioning:
- Remove pixel insets parameter for default positioning
- Use default positioning values:
   - x: 100% and y: 20% for MacOS
   - x: 100% and y: 0% for Windows
- set popup margins to 16px for all edges on MacOS
- set popup margins to 12px for all edges on Windows
- change shadow elevation on Windows to fit 12px for the bottom edge

cc @aguscruiz @tmancey

**Comment by aseren** [comment]
As discussed we agreed to make the following changes in positioning:
- Remove pixel insets parameter for default positioning
- Use default positioning values:
   - x: 100% and y: 20% for MacOS
   - x: 100% and y: 0% for Windows
- set popup margins to 16px for all edges on MacOS
- set popup margins to 12px for all edges on Windows
- change shadow elevation on Windows to fit 12px for the bottom edge

**Comment by btlechowski** [comment]
Verified with

Brave | 1.62.107 Chromium: 120.0.6099.115 (Official Build) beta (64-bit)
-- | --
Revision | 67a3b21572338a0660bb25a5855da0f1e9372a39
OS | Windows 11 Version 22H2 (Build 22621.2861)

Verified testplan from https://github.com/brave/brave-core/pull/20619

<details>

#### default ad position

2 monitors:
![image](https://github.com/brave/brave-browser/assets/34715963/536dbd9c-d3b7-40ed-94ab-12c087e9bdf6)

Unplugged monitors:
![image](https://github.com/brave/brave-browser/assets/34715963/8c89eff7-985e-4e44-b255-2421880986e9)

replugged monitor:
![image](https://github.com/brave/brave-browser/assets/34715963/9a888692-5165-4a59-b1c8-73082d102453)

Closed ad:
![image](https://github.com/brave/brave-browser/assets/34715963/74536593-86a9-4fcb-b797-df2efa7f43f1)

Triggered another ad:
![image](https://github.com/brave/brave-browser/assets/34715963/d7d57bb2-b903-4855-911e-e324b2f75e2c)


#### custom ad position

2 monitors:
![image](https://github.com/brave/brave-browser/assets/34715963/8871df79-0ce6-4709-826f-b00d9729fe3d)

Unplugged monitor:
![image](https://github.com/brave/brave-browser/assets/34715963/0e25ca62-8112-450d-beeb-529a55b6a3fa)

replugged monitor:
![image](https://github.com/brave/brave-browser/assets/34715963/9b2cb6bd-e9d6-44cf-b28c-c71373c065e4)





</details>
