### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by sumandey07** [brave/brave-browser#33590]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.59.117 Chromium: 118.0.5993.70
Operating System: Windows NT 10.0.22631

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. open brave
2. click the settings button or about brave in help button on the three dot menu.
3. I cannot update or check the version of brave.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/217b0100-29ee-dc0a-0000-000000000000

**Comment by iefremov** [comment]
stale
