### ISSUE TITLE
Vertical tabs crash Brave when using a black theme

### ISSUE THREAD

**Issue by jpovixwm** [brave/brave-browser#33598]
Brave Version: 1.59.117 Chromium: 118.0.5993.70
Operating System: Windows NT 10.0.19041

URL (if applicable) where crash occurred: N/A

Can you reproduce this crash?
Yes.

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Enable vertical tabs
2. Apply a black theme, for example [this one](https://chrome.google.com/webstore/detail/morpheon-dark/mafbdhjdkjnoafhfelkjpchpaepjknad)

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/94570200-29ee-dc0a-0000-000000000000

**Comment by kjozwiak** [comment]
Reproduced as well when trying to find the cause due to various reports from the community as per https://community.brave.com/t/brave-crashes-immediately-upon-startup/509970/5 & https://community.brave.com/t/brave-crashes-immediately-on-opening/509982/3.

* install `1.59.117 Chromium: 118.0.5993.70`
* enable `vertical tabs` via `brave://settings/appearance`
* attempt installing https://chrome.google.com/webstore/detail/slinky-elegant/bmanlajnpdncmhfkiccmbgeocgbncfln
* you'll instantly crash as mentioned above
  * `06600200-29ee-dc0a-0000-000000000000` & `16650200-29ee-dc0a-0000-000000000000`

BTW, this only happens when you have vertical tabs enabled. For example, here's another version of the STR/Cases:

* install `1.59.117 Chromium: 118.0.5993.70`
* install https://chrome.google.com/webstore/detail/slinky-elegant/bmanlajnpdncmhfkiccmbgeocgbncfln
* once installed, the theme should be applied without any issues/failures/crashes
* go into `brave://settings/appearance` and enable `Vertical Tabs`
* you'll get an instant crash with the same reason mentioned below via the crash stack

```
[ 00 ] ImmediateCrash() ( immediate_crash.h:146 )
[ 01 ] CheckFailure() ( check.h:192 )
[ 02 ] views::View::ConvertPointToTarget(views::View const *,views::View const *,gfx::Point *) ( view.cc:1028 )
[ 03 ] TopContainerBackground::PaintThemeAlignedImage(gfx::Canvas *,views::View const *,BrowserView const *,gfx::ImageSkia *) ( top_container_background.cc:50 )
[ 04 ] NewTabButton::PaintFill(gfx::Canvas *) ( new_tab_button.cc:255 )
[ 05 ] BraveNewTabButton::OnPaintFill(gfx::Canvas *) ( brave_new_tab_button.cc:90 )
[ 06 ] `anonymous namespace'::VerticalTabNewTabButton::OnPaintFill(gfx::Canvas *) ( vertical_tab_strip_region_view.cc:369 )
[ 07 ] NewTabButton::PaintButtonContents(gfx::Canvas *) ( new_tab_button.cc:215 )
[ 08 ] views::Button::OnPaint(gfx::Canvas *) ( button.cc:557 )
[ 09 ] views::View::Paint(views::PaintInfo const &) ( view.cc:1273 )
[ 10 ] views::View::RecursivePaintHelper((views::PaintInfo const &),views::PaintInfo const &) ( view.cc:2849 )
[ 11 ] views::View::PaintChildren(views::PaintInfo const &) ( view.cc:2291 )
[ 12 ] views::View::Paint(views::PaintInfo const &) ( view.cc:1278 )
[ 13 ] views::View::RecursivePaintHelper((views::PaintInfo const &),views::PaintInfo const &) ( view.cc:2849 )
[ 14 ] views::View::PaintChildren(views::PaintInfo const &) ( view.cc:2291 )
[ 15 ] views::View::Paint(views::PaintInfo const &) ( view.cc:1278 )
[ 16 ] views::View::RecursivePaintHelper((views::PaintInfo const &),views::PaintInfo const &) ( view.cc:2849 )
[ 17 ] views::View::PaintChildren(views::PaintInfo const &) ( view.cc:2291 )
[ 18 ] views::View::Paint(views::PaintInfo const &) ( view.cc:1278 )
[ 19 ] views::View::PaintFromPaintRoot(ui::PaintContext const &) ( view.cc:2857 )
[ 20 ] ui::Layer::PaintContentsToDisplayList() ( layer.cc:1444 )
[ 21 ] cc::PictureLayer::Update() ( picture_layer.cc:162 )
[ 22 ] cc::LayerTreeHost::PaintContent(std::__Cr::vector<scoped_refptr<cc::Layer>,std::__Cr::allocator<scoped_refptr<cc::Layer> > > const &) ( layer_tree_host.cc:1654 )
[ 23 ] cc::LayerTreeHost::DoUpdateLayers() ( layer_tree_host.cc:974 )
[ 24 ] cc::LayerTreeHost::UpdateLayers() ( layer_tree_host.cc:829 )
[ 25 ] cc::SingleThreadProxy::DoPainting(viz::BeginFrameArgs const &) ( single_thread_proxy.cc:1121 )
[ 26 ] cc::SingleThreadProxy::BeginMainFrame(viz::BeginFrameArgs const &) ( single_thread_proxy.cc:1081 )
[ 27 ] base::OnceCallback<void ()>::Run() ( callback.h:152 )
[ 28 ] base::TaskAnnotator::RunTaskImpl(base::PendingTask &) ( task_annotator.cc:201 )
[ 29 ] base::TaskAnnotator::RunTask(perfetto::StaticString,base::PendingTask &,base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl::<lambda_0> &&) ( task_annotator.h:89 )
[ 30 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::LazyNow *) ( thread_controller_with_message_pump_impl.cc:480 )
[ 31 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() ( thread_controller_with_message_pump_impl.cc:345 )
[ 32 ] absl::optional<base::WatchHangsInScope>::emplace() ( optional.h:362 )
[ 33 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoIdleWork() ( thread_controller_with_message_pump_impl.cc:557 )
[ 34 ] base::MessagePumpForUI::DoRunLoop() ( message_pump_win.cc:212 )
[ 35 ] base::MessagePumpWin::Run(base::MessagePump::Delegate *) ( message_pump_win.cc:78 )
[ 36 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool,base::TimeDelta) ( thread_controller_with_message_pump_impl.cc:648 )
[ 37 ] base::RunLoop::Run(base::Location const &) ( run_loop.cc:136 )
[ 38 ] base::RunLoop::RunLoop(base::RunLoop::Type) ( run_loop.cc:92 )
[ 39 ] content::BrowserMainLoop::RunMainMessageLoop() ( browser_main_loop.cc:1073 )
[ 40 ] content::BrowserMainRunnerImpl::Run() ( browser_main_runner_impl.cc:159 )
[ 41 ] content::BrowserMain(content::MainFunctionParams) ( browser_main.cc:34 )
[ 42 ] RunBrowserProcessMain(content::MainFunctionParams,content::ContentMainDelegate *) ( content_main_runner_impl.cc:704 )
[ 43 ] content::ContentMainRunnerImpl::RunBrowser(content::MainFunctionParams,bool) ( content_main_runner_impl.cc:1288 )
[ 44 ] std::__Cr::basic_string<char,std::__Cr::char_traits<char>,std::__Cr::allocator<char> >::operator basic_string_view() ( string:1082 )
[ 45 ] content::ContentMainRunnerImpl::Run() ( content_main_runner_impl.cc:1138 )
[ 46 ] RunContentProcess(content::ContentMainParams,content::ContentMainRunner *) ( content_main.cc:326 )
[ 47 ] content::ContentMain(content::ContentMainParams) ( content_main.cc:343 )
[ 48 ] ChromeMain(HINSTANCE__ *,sandbox::SandboxInterfaceInfo *,__int64) ( chrome_main.cc:189 )
[ 49 ] MainDllLoader::Launch(HINSTANCE__ *,base::TimeTicks) ( main_dll_loader_win.cc:166 )
[ 50 ] wWinMain(HINSTANCE__ *,HINSTANCE__ *,wchar_t *,int) ( chrome_exe_main_win.cc:390 )
[ 51 ] invoke_main() ( exe_common.inl:118 )
[ 52 ] __scrt_common_main_seh() ( exe_common.inl:288 )
[ 53 ] 0x7ff9eb45257d
[ 54 ] 0x7ff9eb8aaa78
[ 55 ] 0x7ff9e91ac550
```

**Comment by LaurenWags** [comment]
Could not reproduce on macOS.

Tried both cases from https://github.com/brave/brave-browser/issues/33598#issuecomment-1760025022, no crash for either of them.

```
Brave | 1.59.117 Chromium: 118.0.5993.70 (Official Build) (x86_64)
-- | --
Revision | 766577bee8f040990afcb32677dcab38ffcf0f06
OS | macOS Version 13.6 (Build 22G120)
```

<img width="1193" alt="Screenshot 2023-10-12 at 1 31 14 PM" src="https://github.com/brave/brave-browser/assets/28145373/91e72a06-a32d-4fe2-aaaf-93b63b87d9af">

**Comment by zenparsing** [comment]
When a theme is installed with a tab strip background, the new tab button will paint itself using that background (instead of the just a normal solid color). In order to paint the "right" part of the background, it will offset the background image so that it matches up with the rest of the browser. To do that, it has do some some calculations involving the position of the button within the browser frame. As part of that, there's a check to make sure that the new tab button is actually contained within the browser view. For vertical tabs, this is not the case.

**Comment by kjozwiak** [comment]
The above requires `1.59.119` or higher for `1.59.x` verification 👍

**Comment by btlechowski** [comment]
Verified with

Brave | 1.59.120 Chromium: 118.0.5993.88 (Official Build) (64-bit)
-- | --
Revision | 135f92a9af2134bc7d7aeba82f87ff5e68669410
OS | Linux

Verified test plan from https://github.com/brave/brave-browser/issues/33598#issuecomment-1760025022

#### Test Case #1 (Vertical Tabs enabled before applying theme)

Verified no crash

![image](https://github.com/brave/brave-browser/assets/34715963/f474b17d-dbf3-4445-a721-407879becc01)|![image](https://github.com/brave/brave-browser/assets/34715963/46218b0d-aa93-44a3-966b-17eb6041446f)|![image](https://github.com/brave/brave-browser/assets/34715963/15054096-8b42-4457-8dcd-1d0c40205123)
--|--|--

#### Test Case #2 (Vertical Tabs enabled after applying theme)

Verified no crash

![image](https://github.com/brave/brave-browser/assets/34715963/8e80d59e-abd8-49a4-8464-f4093e907666)|![image](https://github.com/brave/brave-browser/assets/34715963/7e105840-201e-4eea-a7c2-c977025df722)|![image](https://github.com/brave/brave-browser/assets/34715963/0f0d106f-c66b-453a-95d8-5366e4ed7f7a)
--|--|--
