### ISSUE TITLE
Unrevert unified adblock catalog w/ perf fixes

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#33621]
https://github.com/brave/brave-core/pull/19946 was reverted by https://github.com/brave/brave-core/pull/20442 due to a performance regression.

The root cause of the regression was that adblock components would generally update in succession, each one triggering a new callback to re-parse the adblock lists and load them into the engine. There is a lot of wasted work, exacerbated in the change to parse lists up-front rather than collecting them all first and parsing at the end.

The regression could be fixed by tracking pending component updates and waiting for all to be completed before reloading the engine. However, it is important to balance this with load at initial app startup, when initial versions of the catalog and lists are not necessarily ready yet.

**Comment by antonok-edm** [comment]
The performance here will also be generally improved as of https://github.com/brave/brave-core/pull/20585

**Comment by LaurenWags** [comment]
Adding `QA/Blocked` label per discussion with @kjozwiak - we have some questions about this one. @kjozwiak will start a thread in slack for discussion 👍🏻

**Comment by kjozwiak** [comment]
Removing `QA/Yes` in favour of https://github.com/brave/brave-browser/issues/35922 👍
