### ISSUE TITLE
new tab flashes white - follow up to 1876

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#3362]
## Description 
Found while testing #1876 

When opening a new tab, the tab flashes white before the background image is loaded. This happens whether you use light or dark theme for Brave.

## Steps to Reproduce

   1. Launch Brave.
   2. Open a few new tabs. See white flash before tab image is loaded.
   3. Switch between the new tabs. Sometimes you will see a white flash when switching between tabs.

## Actual result:
![1876](https://user-images.githubusercontent.com/28145373/52822661-531f0600-3080-11e9-9a94-12d528532fd0.gif)

## Expected result:
No white flash.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.60.28 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Mac OS X

### Reproducible on current release: yes
- Does it reproduce on brave-browser dev/beta builds? yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
Reproduced by @kjozwiak on macOS (Mojave)

**Comment by srirambv** [comment]
Issue reproduced on Linux as well

**Comment by btlechowski** [comment]
Reproduced on Windows

Brave | 0.60.29 Chromium: 72.0.3626.96 (Official Build) beta (64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Windows 7

![3362](https://user-images.githubusercontent.com/34715963/52869907-03574200-3147-11e9-9d0b-1888c61c2f51.gif)

**Comment by kjozwiak** [comment]
@rebron moving this into `0.62.x` as https://github.com/brave/brave-core/pull/1680 is targetting `0.62.x`.

**Comment by rebron** [comment]
@rossmoody just a reminder, after you merge an uplift, in the issue set the milestone to where you merged it too, so 61.x in this case. Thanks for taking care of this one.

**Comment by rossmoody** [comment]
@rebron @kjozwiak thanks for fixing it up and the direction. appreciate it.

**Comment by GeetaSarvadnya** [comment]
The issue still persists on Linux `0.61.41`

![3362](https://user-images.githubusercontent.com/38657976/53747063-74795200-3ec8-11e9-810f-a0abe9af329d.gif)

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.61.45 Chromium: 73.0.3683.39 (Official Build) beta (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

The white does not flash in `Dark` mode.

![3362b](https://user-images.githubusercontent.com/34715963/53781231-44ea3a00-3f08-11e9-894d-f3b48d9c201f.gif)

Still reproducible for `Light` mode. Logged https://github.com/brave/brave-browser/issues/3575
