### ISSUE TITLE
clicking on either `Like` & `Dislike` triggers two submissions 

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#33622]
## Description 

While running through https://github.com/brave/brave-browser/issues/32951 to uplift into `1.60.x`, I noticed that clicking on either `Like` or `Dislike` triggers two submissions rather than one. You'll notice either two `Answered liked` & `Answered disliked` UI elements appearing alongside two unique requests to `https://feedback.brave.com/1/ai/feedback/rating`. So I'm assuming we're double counting a single click.

## Steps to Reproduce

   1. launch `1.61.21 Chromium: 118.0.5993.70`
   2. restart the browser once again so you're part of `BraveAIChatEnabledStudy:Enabled` (check via `brave://version`)
   3. on the sidebar, click on the `Leo` button and accept the `T&S`
   4. once accepted, ask `Leo` anything (in this case, I searched for `Brave Browser`)
   5. click on the hamburger menu on the answer and select either `Like` or `Dislike`

## Actual result:

**`Example`** of two `Answered liked` & `Answered disliked`

**`Example`** | **`Example`**
---------------|------------------
![twoLikes](https://github.com/brave/brave-browser/assets/2602313/21e4b933-4ff6-42a4-b749-4f61707c716c) | ![twoDislikes](https://github.com/brave/brave-browser/assets/2602313/09345f1e-4c80-4097-b672-79862809e49b)

**`Example`** of two `https://feedback.brave.com/1/ai/feedback/rating` being made at the same time

**`Example (Liked)`** | **`Example (Liked)`**
------------------------|----------------------
![request1](https://github.com/brave/brave-browser/assets/2602313/5cca84e1-93f6-4328-ba5b-2fd80e4a7d28) | ![request2](https://github.com/brave/brave-browser/assets/2602313/3f700260-78e6-4f06-9189-6d0e616ec71a)

**`Example (Disliked)`** | **`Example (Disliked)`**
--------------------------|------------------------
![requestDislike1](https://github.com/brave/brave-browser/assets/2602313/ebdfad72-c9d2-48b4-9795-4cc1af11f9d9) | ![requestDislike2](https://github.com/brave/brave-browser/assets/2602313/13e46c85-b8e3-4226-93b8-ea26f6c89b21)

## Expected result:

Assuming that we should only be displaying either one `Answered liked` or `Answered disliked` and only be doing a single request to ``https://feedback.brave.com/1/ai/feedback/rating`. If you look at the screenshots above, the two requests have unique ID's so assuming it's counting a single click as two submissions.

## Reproduces how often: 

100% reproducible using the STR/Cases outlined above.

## Brave version (brave://version info)

```
Brave | 1.61.21 Chromium: 118.0.5993.70 (Official Build) nightly (64-bit)
-- | --
Revision | ce51937f5b035db1f8c8173fc36df9140494d59a
OS | Windows 11 Version 22H2 (Build 22621.2428)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by stephendonner** [comment]
Related/cross-reference is https://github.com/brave/brave-browser/issues/33434

**Comment by stephendonner** [comment]
But this is really https://github.com/brave/brave-browser/issues/33433

**Comment by bbondy** [comment]
Fixed by https://github.com/brave/brave-core/pull/20418
