### ISSUE TITLE
Client Certificate not work with Brave Desktop version 1.59.117

### ISSUE THREAD

**Issue by anonid64** [brave/brave-browser#33628]
## Description 
After update Brave Desktop to version 1.59.117, Brave not show Client Certificate dialog when access to website require it (Cloudflare) while Microsoft Egde and Chrome normal access with Client Certificate dialog show and i can access same website normally

## Steps to Reproduce

   1. Update Brave Desktop to lastest version (1.59.117).
   2. Visit website require Client Certificate.
   3. Client Certificate dialog not show to choose and can't access this website.
   4. Try visit this website with Micsoroft Edge and Chrome then can access this website after choose correct Certificate from Client Certificate dialog.

## Actual result:

I use Client Certificate of Cloudflare
![image](https://github.com/brave/brave-browser/assets/34296806/196de644-61ab-4069-958f-364e8ebbf132)

## Expected result:
Client Certificate dialog show to choose my certificate and after that i can access website require Client Certificate. Same here
![image](https://github.com/brave/brave-browser/assets/34296806/38987ada-cdda-4620-bd58-13b7d14b234c)

## Reproduces how often: 
No steps to reproduce, only visit to website require Client Certificate and this error 

## Brave version (brave://version info)
_Brave	1.59.117 Chromium: 118.0.5993.70 (Phiên bản Chính thức) (64 bit) 
Bản sửa đổi	766577bee8f040990afcb32677dcab38ffcf0f06

## Version/Channel Information:

- Can you reproduce this issue with the current release?  **Yes**, i have been update to Brave Desktop version 1.59.117 and this version **have this issue**
- Can you reproduce this issue with the beta channel? **Yes**, Brave Desktop version 1.59.117 have **same issue**
- Can you reproduce this issue with the nightly channel? **Yes**, Brave Desktop version 1.59.117 have **same issue**

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? **No**
- Does the issue resolve itself when disabling Brave Rewards? **No, i not use it**
- Is the issue reproducible on the latest version of Chrome?  **No**, chrome version 118.0.5993.71 **not** have this issue

## Miscellaneous Information:
Previous Brave Desktop version not have this issue

**Comment by anonid64** [comment]
At now, Chrome and Edge have same issues

**Comment by anonid64** [comment]
At 2AM today, i updated to lastest version (1.59.120) it work, but at 06PM it not work.

**Comment by anonid64** [comment]
Microsoft Edge using normal but Brave 1.59.120 have this issues

**Comment by webster8347** [comment]
This is very annoying. Getting locked out of my Homeassistant randomly due to this new error.

**Comment by anonid64** [comment]
No one here?

**Comment by anonid64** [comment]
> This is very annoying. Getting locked out of my Homeassistant randomly due to this new error.

i try with curl it working but brave not show dialog to select certificate. About 2 month but no-one reply this issue. Haiz

**Comment by anonid64** [comment]
> This is very annoying. Getting locked out of my Homeassistant randomly due to this new error.

Hey, check your website is using HTTP/3 or not? If it is HTTP/3, disable QUIC in brave://flag and restart. It work for me.

**Comment by wildernessfamily** [comment]
I disabled QUIC, but that did not work for me.
