### ISSUE TITLE
Crash Report: Vertical tabs issue

### ISSUE THREAD

**Issue by soucelover** [brave/brave-browser#33631]
# Version info
Brave Version: 1.59.117 Chromium: 118.0.5993.70
Operating System: Windows NT 10.0.19045

# Preparation steps to reproduce the crash
1. Don't update windows for an hour
2. When you receive update ignore it
3. Open brave browser
4. Then turn on sleep mode
5. Voila, windows update fucked the brave when it was sleeping

# Steps to reproduce
Turn on vertical tabs and you see that brave immediately crashed. Now you've lost all your data in browser.

Also as the only true way:
1. Go to folder of your profile in brave and open file "Preferences" as .json file
7. Go to "brave" subkey (maybe you will prefer to format document for convenience)
8. Add "tabs" subkey with these attributes: {"hover_mode": 2,"vertical_tabs_collapsed": true,"vertical_tabs_enabled": true}
9. Alright. Now, Brave crashes down when you open it

# Epilogue
This crash work **only** for one of my profiles because only it were opened when brave was humiliated by windows update.

It's more likely that this setting conflict with some other files in profile folder. I will check it tomorrow.

# Crash ID
Crash ID: crash/11190700-29ee-dc0a-0000-000000000000

**Comment by bsclifton** [comment]
Unfortunately, the crash report doesn't appear to be available for this. If this is still an issue, let's re-open and share a crash ID again please. Thanks!
