### ISSUE TITLE
Update "Creator" text to not be capitalized and follow style guide

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#33635]
For example, "Creator" should not be capitalized in the first instance, but should remain capitalized in "Brave Creators". 

```[tasklist]
### Tasks
- [ ] Look for all instances of this and resolve
- [ ] Make list of places where this is changed for QA
```

![image](https://github.com/brave/brave-browser/assets/11497541/0ee6962e-b740-4f92-83b1-a924717098d2)

**Comment by LaurenWags** [comment]
@Miyayes @emerick description mentions a list of places where this change was made - does that exist?

Marking as `QA/Blocked` for now.

**Comment by emerick** [comment]
@LaurenWags

We now lowercase `creator` for the following items:

- The tooltip text for the "Refresh status" icon in the Rewards panel (`Refresh creator verification status`)
- The tooltip text for verified creators in the Contributions panel on brave://rewards (`This creator has registered with Brave and can receive contributions from Brave Rewards users.`)
- The monthly tip note in the Monthly Contributions panel on brave://rewards (`You can still send a contribution now, and you can cancel your monthly contributions to this creator by removing them from...`)
- The message shown on brave://rewards page before connecting a custodian account (`You'll be able to send on-demand contributions to your favorite creators with your Brave Rewards balance once you have a custodial account connected.`)
- The text shown in the Rewards panel for unverified creators (`This creator is not yet verified with Brave Creators. You'll be able to send them contributions once they're verified.`)

**Comment by LaurenWags** [comment]
Thank you! This is super helpful 👍🏻

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.61.66 Chromium: 119.0.6045.105 (Official Build) beta (x86_64)
-- | --
Revision | aaaecfc0d925cde58e40e1b689464f1c630ef96d
OS | macOS Version 13.6.1 (Build 22G313)
```
