### ISSUE TITLE
Youtube adblock-blocker is not blocked

### ISSUE THREAD

**Issue by bitGimmicks** [brave/brave-browser#33630]
## Description 
(searched if exists, couldn't find in the issue log)

Trying to browse youtube the adblock-blocker thing pops up in one's face, even though Brave supposed to prevent this.

## Steps to Reproduce
(NOTE: By nature google's fascist-warning is adhoc, and as such, steps don't necessarily work all the time, one might have to visit another channel / clip / etc)

   1. Visit e.g. this youtube clip: https://www.youtube.com/watch?v=ySWxnUqajQ0
   2. Observe

## Actual result:
Youtube adblock pops in one's face.

## Expected result:
No adblock-blocker appears

## Reproduces how often: 
Always

## Brave version (brave://version info)
1.59.117 Chromium: 118.0.5993.70 (Official Build) (64-bit) 

## Version/Channel Information:
OS: Windows 10 22H2, v19045.3570
JS (V8): v11.8.172.15

## Other Additional Information:
- Youtube status
Being logged-in ("since forever") with a gmail account, having multiple subscriptions

- Does the issue resolve itself when disabling Brave Shields (Rewards is OFF)? 
Unsure, as the popup comes ad-hoc (tried with Shields off, no warning, however, turning back on and refresh gave the same result - kept opening the same utube clip)

- Is the issue reproducible on the latest version of Chrome? 
Absolutely, sadly.
<img width="1280" alt="adblock_report_stuff" src="https://github.com/brave/brave-browser/assets/120049940/a3b7c39d-fb55-48d0-99d0-c8c59ec6abeb">

**Comment by antonok-edm** [comment]
@bitGimmicks YouTube has been frequently updating their detection methods, but we are working around them.

Can you let me know if visiting brave://components and pressing `Check for update` on the `Brave Ad Block Updater` entry solves this for you? You may also want to try a force-refresh on any youtube pages you have open (i.e. <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>R</kbd>).

**Comment by antonok-edm** [comment]
I'll close this in favor of https://github.com/brave/brave-browser/issues/33493, just to have a single point of coordination.

**Comment by bitGimmicks** [comment]
hi @antonok-edm Thanks for coming back, commented my answer to your question in the bug refferd.
