### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by exstocklet** [brave/brave-browser#33656]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.59.117 Chromium: 118.0.5993.70
Operating System: Windows NT 10.0.19045

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Updated Brave browser
2. Waited for it to restart itself automatically as it usually does
3. Tried to restart it manually

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/4e410b00-29ee-dc0a-0000-000000000000

**Comment by iefremov** [comment]
stale
