### ISSUE TITLE
Tracking protection entries with paths are not blocked by Shields

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#3365]
## Description 

The Disconnect list now contains [entries with paths](https://github.com/disconnectme/disconnect-tracking-protection/blob/25e6195ff6e943845beccfc30b5e69f0da61be07/services.json#L6531-L6535).

I added `yandex.ru/cycounter` to my test page and found that it's not blocked despite being [included in our fork of the Disconnect list](https://github.com/brave/tracking-protection/blob/132ac934be9dd0113a4bb4d041f7602a72c60662/data/disconnect.json#L6461) and being included in the `.dat` file that we generate:

    ~/devel/tracking-protection$ grep yandex.ru/cycounter data/TrackingProtection.dat 
    Binary file data/TrackingProtection.dat matches

## Steps to Reproduce

   1. Open <https://fmarier.github.io/brave-testing/tracking-protection.html>.
   2. Look at the last image under "Advertising".

## Actual result:

It's loaded and displayed.

## Expected result:

It should be replaced with an empty image just like the other images in this category.

## Brave version (brave://version info)

```
Brave | 0.59.35 Chromium: 72.0.3626.81 (Official Build) (64-bit)
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS | Linux
```

### Reproducible on current release:

It reproduces consistently on brave-browser dev and beta builds.

**Comment by fmarier** [comment]
This is also a problem for our pairwise whitelisting (i.e. grouping of related domains):

- `adgainersolutions.com/adgainer`
- `hotmart.com/en`
- `maxmind.com/en/home`
- `narrative.io/2: narrative.io`
- `tongdun.cn/?lan=EN`
- `ysance.com/data-services/fr/home`

**Comment by fmarier** [comment]
This will be fixed by moving the Disconnect rules to the EasyList format (https://github.com/brave/adblock-lists/pull/124) and removing the tracking protection component in favour of just adblock-rust.

**Comment by pes10k** [comment]
We no longer use disconnect rules so closing out
