### ISSUE TITLE
Acknowledging `Leo` with non-actionable input text ("ok", "thanks," etc.) will merely repeat `Leo's` last message

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#33664]
## Description 

Acknowledging `Leo` with non-actionable input text ("ok", "thanks," etc.) will merely repeat `Leo's` last message

## Steps to Reproduce

1. install `1.61.26`
2. launch Brave
3. restart (to pick up Griffin seed)
4. load `https://www.vox.com/23890764/healthcare-insurance-marketplace-open-enrollment-employer-sponsored-united-blue-cross-shield-aetna`
5. click `Summarize this page`
6. after `Leo` summarizes, type `OK` and press `return`/`enter`
7. note the response
8. type `thanks` and press `return`/`enter`
9. note the response

## Actual result:

`Leo` just repeats his last message/instruction

example | example | example
----------|-----------|----------
![image (2)](https://github.com/brave/brave-browser/assets/387249/3cdf4b0f-91b6-4f47-8b1e-f7899183ccc3) | ![image](https://github.com/brave/brave-browser/assets/387249/ea117655-6cc8-4212-b868-ca0a2e247fc2) | ![image (1)](https://github.com/brave/brave-browser/assets/387249/50473b8c-bb01-4c49-a854-7b56a476effc)

## Expected result:

Not sure, to be quite honest.  Is there a set of non-actionable inputs we can ignore or react to differently?

## Reproduces how often: 

100%/easily

## Brave version (brave://version info)

```
Brave | 1.61.26 Chromium: 118.0.5993.70 (Official Build) nightly (64-bit)
-- | --
Revision | 4b9be64f58df25fcafa007ffd7f494240f18751a
OS | Windows 10 Version 22H2 (Build 19045.3570)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

cc @bbondy @nullhook @petemill @jonathansampson @mattmcalister @brave/qa-team

**Comment by kjozwiak** [comment]
The above requires `1.60.106` or higher for `1.60.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.60.106 Chromium: 119.0.6045.59 (Official Build) (64-bit)
-- | --
Revision | 16064193dde8c55f64dabd32f125c0cd9380f96a
OS | Windows 10 Version 22H2 (Build 19045.3636)
```

### Followed my original steps to reproduce

## Confirmed followup prompts were appropriate after answering `ok` and `thanks!` after article summarization

example | example | example | example
----------|----------|-----------|----------
![image](https://github.com/brave/brave-browser/assets/387249/289af626-b23f-4534-b6c2-388150770a4c) | ![image](https://github.com/brave/brave-browser/assets/387249/50eb8d94-4ee9-41eb-8368-ebe27a65248a) | ![image](https://github.com/brave/brave-browser/assets/387249/d436d6eb-dacd-4b31-86b6-c422169bb1d8) | ![image](https://github.com/brave/brave-browser/assets/387249/1e6c3c77-3cf1-4a2e-a038-f82dfd7acff5)
