### ISSUE TITLE
`Switch to default model` button in dialog doesn't work; must manually switch

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#33673]
## Description 

`Switch to default model` button in dialog doesn't work; must manually switch

## Steps to Reproduce

1. install `1.61.28`
2. launch Brave
3. restart (to pick up Griffin seed)
4. click on `Brave Leo` in the sidebar
5. click `Accept and begin`
6. load an article (`https://www.vox.com/23890764/healthcare-insurance-marketplace-open-enrollment-employer-sponsored-united-blue-cross-shield-aetna`)
7. click on the `...` menu at the top right of `Brave Leo`
8. choose `llama-2-70b-chat`
9. in the `Unlock the full potential of Leo` dialog, click on `Switch to the default model`

## Actual result:

Nothing happens

https://github.com/brave/brave-browser/assets/387249/4553d5b9-e7f3-4db9-8e81-f656159f1793

## Expected result:

Should switch back to `llama-2-13b-chat` (must manually do this to clear the dialog)

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave | 1.61.28 Chromium: 118.0.5993.70 (Official Build) nightly (64-bit)
-- | --
Revision | e59d42d7d6be89b28e7b9542f52c4c248fa5923f
OS | Windows 10 Version 22H2 (Build 19045.3570)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A`
- Can you reproduce this issue with the beta channel? `N/A - needs uplift first`
- Can you reproduce this issue with the nightly channel? `Yes`

cc @bbondy @mattmcalister @petemill @nullhook @brave/qa-team

**Comment by kjozwiak** [comment]
The above requires `1.60.105` or higher for `1.60.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.60.106 Chromium: 119.0.6045.59 (Official Build) (x86_64)
-- | --
Revision | 16064193dde8c55f64dabd32f125c0cd9380f96a
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Followed my original steps to reproduce

## Confirmed clicking on `Switch to the default model` works, and puts me back on `llama2-13b`

example | example | example
---------|----------|--------
<img width="1312" alt="Screen Shot 2023-10-28 at 6 21 37 PM" src="https://github.com/brave/brave-browser/assets/387249/5a511527-68d1-48f5-91de-cfad5b18f390"> | <img width="1312" alt="Screen Shot 2023-10-28 at 6 21 47 PM" src="https://github.com/brave/brave-browser/assets/387249/3000e063-75b7-43b1-9b9c-acad5f6bcaa8"> | <img width="1312" alt="Screen Shot 2023-10-28 at 6 21 51 PM" src="https://github.com/brave/brave-browser/assets/387249/0e1798a7-5800-498c-949e-e44854bbc6f7">
