### ISSUE TITLE
Persist wallet panel navigation location

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#33677]
## Description 

The wallet panel should re-open to the same screen it was was on before it was closed.

## Steps to Reproduce

   1. Open the panel
   2. navigate to a different screen ("Activity")
   3. close the panel
   4. re-open the panel

## Actual result:

The "Portfolio" page is displayed

## Expected result:
The last opened screen ("Activity") should be displayed page

## Reproduces how often: 

Easily

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.61.85 Chromium: 119.0.6045.163 (Official Build) beta (64-bit)
-- | --
Revision | 5e2736df90772dd1b66ca5013e47c1fc467c9762
OS | Windows 11 Version 23H2 (Build 22631.2715)

- Verified steps from issue description
- Verified panel navigation retains the last opened bottom navigation

https://github.com/brave/brave-browser/assets/17010094/6bee069b-6db3-4556-9218-a72caeeb93ef
