### ISSUE TITLE
Enable AI Chat feature flag by default for Desktop 1.60.x+

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#33674]
On a fresh profile, the AI Chat feature flag should be enabled at first launch.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.61.62 Chromium: 119.0.6045.105 (Official Build) beta (x86_64)
-- | --
Revision | 435a38586472c662beec0fc75f622b7dfaa1e77d
OS | macOS Version 14.2 (Build 23C5030f)
```

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.61.62 Chromium: 119.0.6045.105 (Official Build) beta (64-bit)
-- | --
Revision | 435a38586472c662beec0fc75f622b7dfaa1e77d
OS | Windows 11 Version 22H2 (Build 22621.2428)
```

1. installed 1.61.62
2. launched Brave
3. opened brave://flags
4. opened brave://version
5. clicked on Leo in the sidebar

Confirmed the Leo AI chat feature is enabled by default, both in brave://flags and via the UI

brave://flags | brave://version (without Griffin studies) |brave://version (with Griffin studies)
------ | ------ | -------
<img width="958" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/68b60499-abe0-4367-9099-566850edcf04">|<img width="958" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/c9a978f3-1192-4134-8649-e9dffb3067fe">|<img width="954" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/dc23dc06-dec1-404a-8422-29c0a13d6262">

**Comment by kjozwiak** [comment]
Moving this back into `1.61.x` so we can complete the verification on `Linux`. Even though https://github.com/brave/brave-core/pull/20559 was uplifted into `1.60.x` via https://github.com/brave/brave-core/pull/20982, we'll verify the change in `1.60.x` using https://github.com/brave/brave-browser/issues/34257. This way both `1.61.x` & `1.60.x` will have issues.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.61.76 Chromium: 119.0.6045.134 (Official Build) beta (64-bit) 
Revision	4d380733de55473426f2b32bf51f7124711b7a9e
OS	Linux
```
