### ISSUE TITLE
[hackerone] wayback machine issue

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#33685]
reported by [xiaoyinl](https://hackerone.com/xiaoyinl) at https://hackerone.com/reports/2213049

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.61.61 Chromium: 119.0.6045.105 (Official Build) beta (64-bit)
-- | --
Revision | 6bbedb0b809f83b08334ffa36b1ea9df92e86245
OS | Windows 11 Version 22H2 (Build 22621.2428)
```


1. Installed 1.61.61
2. launched Brave
3. opened `brave://settings/braveHelpTips` in a new tab
4. verified `Show Wayback Machine prompt in 404 pages` is enabled
5. visited https://www.brave.com/bo
6. confirmed `Sorry, the page is missing.....` Wayback Machine infor bar is shown
7. opened view page source via page's context menu (or ctrl + u)
8. confirmed ` `Sorry, the page is missing.....`  Wayback machine info bar is not shown on view source page

step 6 | step 8
--- | -----
![image](https://github.com/brave/brave-browser/assets/98358127/c1daad01-25b8-466c-8c02-fb4d2fe29d7e)|![image](https://github.com/brave/brave-browser/assets/98358127/e5c17630-9666-4753-807b-1322baa77512)

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.61.66 Chromium: 119.0.6045.105 (Official Build) beta (x86_64)
-- | --
Revision | aaaecfc0d925cde58e40e1b689464f1c630ef96d
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.61.66`
2. launched Brave
3. opened `brave://settings`
4. verified Show Wayback Machine prompt in 404 pages is enabled
5. visited https://www.brave.com/bo
6. confirmed Sorry, the page is missing..... Wayback Machine infor bar is shown
7. opened view page source via page's context menu (or ctrl + u)
8. confirmed Sorry, the page is missing..... Wayback machine info bar is not shown on view source page

`step 6` | `step 8`
---------|---------
<img width="1312" alt="Screen Shot 2023-11-06 at 11 05 07 AM" src="https://github.com/brave/brave-browser/assets/387249/f4ab974e-d5f7-4a5e-a95c-1fd431cfe5a9"> | <img width="1312" alt="Screen Shot 2023-11-06 at 11 05 38 AM" src="https://github.com/brave/brave-browser/assets/387249/0d1061ba-e7ba-4a3d-9b97-a22ccd6fbe33">

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.61.76 Chromium: 119.0.6045.134 (Official Build) beta (64-bit) 
Revision	4d380733de55473426f2b32bf51f7124711b7a9e
OS	Linux
```
