### ISSUE TITLE
Brave Rewards balance not showing up in Portfolio History

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#33682]
## Description 

The Brave Rewards balance is not showing up in the `Portfolio` `Price history` chart.

## Steps to Reproduce

   1. Enable Rewards and Connect to your custodial account
   2. Open the Wallet and navigate to the `Portfolio`
   3. The Rewards balance does not reflect in the `Price History` chart

## Actual result:

https://github.com/brave/brave-browser/assets/40611140/5f25a071-21a9-43a7-bb1c-8180722eac4f

## Expected result:
Brave rewards balance should be include in the `Portfolio` `Price History` chart

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-browser/issues/31713#issuecomment-1831593705
