### ISSUE TITLE
Add Android support for daily browser session time P3A metric

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#33687]
Add Android support for the question defined in https://github.com/brave/brave-browser/issues/33459

**Comment by kjozwiak** [comment]
The above requires `1.60.108` or higher for `1.60.x` verification 👍

**Comment by hffvld** [comment]
### In progress...

Verified on `Pixel 6` using version(s):
```
Device/OS: Pixel 6 [oriole-user 13 TQ3A.230901.001 release-keys]
Brave build: 1.60.109
Chromium: 119.0.6045.59 (Official Build) (64-bit) 
Revision: fc399c7c433510eb03c2b35281bf8935804b99de
```
---------------------------

**STEPS:**
1. Fresh install and launch Brave
2. Open `brave://local-state`
3. Look for the metrics `Brave.Uptime.BrowserOpenTime` > Verify that no metrics are shown
4. Use Brave for ~20 mins
5. Close Brave > Change system date ahead by one day
6. Open Brave > Go to `brave://local-state`
7. Look for the metrics `Brave.Uptime.BrowserOpenTime` > Verify that metrics are shown
8. Repeat steps 4 - 7 according to https://github.com/brave/brave-browser/issues/33459#issue-1929653349 > Verify

**ACTUAL RESULTS:**
- Verified that the metrics `Brave.Uptime.BrowserOpenMinutes` or `Brave.Uptime.BrowserOpenTime` don't exist in the local state file if Brave wasn't used before
- Verified that `Brave.Uptime.BrowserOpenMinutes` replaced with `Brave.Uptime.BrowserOpenTime` metrics
- Verified that the metrics `Brave.Uptime.BrowserOpenTime` response value is `0` after ~20 min of usage 
- Verified that the metrics `Brave.Uptime.BrowserOpenTime` response is showing correct value according to https://github.com/brave/brave-browser/issues/33459#issue-1929653349

---------------------------

| Fresh launch | Less than 30 min | 30 min to 1 hour |
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/25608f55-be23-4cca-87f0-193dd8276a39) | ![2](https://github.com/brave/brave-browser/assets/128532965/c8d3563f-5f8a-456c-83e8-7873600c1604) | ![3]() |
| 1 - 2 hours | 2 - 3 hours | 3 - 5 hours |
| ![1]() | ![2]() | ![3]() |
| 5 - 7 hours | 7 - 10 hours | More than 10 hours |
| ![1]() | ![2]() | ![3]() |
