### ISSUE TITLE
Support languages that read from a different direction (e.g. right to left)

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#3368]
## Description
Currently, the Shields panel only supports reading from left to right. Update it to comfortably support Arabic / Hebrew / other languages that have a different reading direction.

## Designs
TBA

**Comment by rebron** [comment]
cc: @nullhook to close out with shields v2

**Comment by kjozwiak** [comment]
Closing as the above is labelled as `closed/works-for-me` so there's no need for the above to stay opened.
