### ISSUE TITLE
Vertical Tab causes browser crash issue

### ISSUE THREAD

**Issue by HamzaELKhatib** [brave/brave-browser#33680]
## Description 
When I toggle the vertical tab feature, the whole browser crashes.

## Steps to Reproduce

   1. Open a brave instance
   2. Toggle the vertical tabs feature either from the tab or from settings

## Actual result:
The browser just crashes after that. I don't know if there's something to screenshot.

## Expected result:
I expected the tabs to turn vertical.

## Brave version (brave://version info)
![image](https://github.com/brave/brave-browser/assets/58004240/7b1ebe9f-272a-41e6-b870-e74140ef46b7)

<html>
<body>

Brave | 1.59.117 Chromium: 118.0.5993.70 (Official Build) (64-bit)
-- | --
Revision | 766577bee8f040990afcb32677dcab38ffcf0f06
OS | Windows 10 Version 22H2 (Build 19045.3570)
JavaScript | V8 11.8.172.15

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
@HamzaELKhatib When you get a chance can update to 1.59.120 and let us know if you're still experiencing the crash.

**Comment by HamzaELKhatib** [comment]
@rebron I just did and it works well now. No crashes.
Thank you!!
