### ISSUE TITLE
Allow seeing which ads and trackers are blocked

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#337]
Allow clicking on the blocked number to see which resources are blocked.

**Comment by cezaraugusto** [comment]
closed by https://github.com/brave/brave-extension/pull/35

**Comment by srirambv** [comment]
Verification Passed on 

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | -- 
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Linux
