### ISSUE TITLE
Make a command line switch to disable vertical tabs

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#33711]
Recently, vertical tab strip caused crash on start-up. In this case, users can't disable vertical tabs without launching it. it'd be good to have command line switch for cases like this so that users can trun off the pref.

Expected behavior:

When passing `--disable-vertical-tabs` to the command line, the vertical tab should be disabled even when the pref is turned on.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.61.60 Chromium: 119.0.6045.105 (Official Build) beta (64-bit)
-- | --
Revision | 1ecda441378e2e473fd84b38456413224121751c
OS | Windows 11 Version 22H2 (Build 22621.2428)
```

1. Installed 1.61.60
2. launched Brave
3. opened few tabs (23 tabs)
4. enabled vertical tabs via context menu
5. close the browser
6. relaunch Brave with cmd line  `--disable-vertical-tabs`
7. opened brave://settings/appearance in a new tab

Confirmed vertical tab view is no longer shown and horizontal tab view is shown
Confirmed `Use vertical tabs` option is not available in the context menu
Confirmed `Use vertical tabs` toggle is `On` in `brave://settings/appearance`

step 4 | step 6 | results | results| results
---- | ----- | ----- | ----- |------
![image](https://github.com/brave/brave-browser/assets/98358127/86ceb610-2697-40aa-a41f-3fc4c1aa16f0)|![image](https://github.com/brave/brave-browser/assets/98358127/99948393-c7a5-4e7b-8b87-3073aeaa7ee9)|![image](https://github.com/brave/brave-browser/assets/98358127/9f60a44d-472a-4667-a416-3a59edc9253c)|![image](https://github.com/brave/brave-browser/assets/98358127/848a04ae-a6e8-41ba-b557-7ec97fe98fec)|![image](https://github.com/brave/brave-browser/assets/98358127/52e842f6-6fde-45fc-abc8-3e4fbcddb9aa)

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.61.62 Chromium: 119.0.6045.105 (Official Build) beta (x86_64)
-- | --
Revision | 435a38586472c662beec0fc75f622b7dfaa1e77d
OS | macOS Version 14.2 (Build 23C5030f)
```

### Steps:
1. installed `1.61.62`
2. launched Brave
3. opened few tabs
4. enabled vertical tabs via context menu
5. close the browser
6. relaunch Brave with cmd line `--disable-vertical-tabs`
7. opened `brave://settings/appearance` in a new tab


### Confirmed vertical tab view is no longer shown and horizontal tab view is shown
### Confirmed Use vertical tabs option is not available in the context menu
### Confirmed Use vertical tabs toggle is On in brave://settings/appearance

`step 4` | `step 6` | `results` | `results` | `results`
---------|----------|---------|-----------|---------

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.61.76 Chromium: 119.0.6045.134 (Official Build) beta (64-bit) 
Revision	4d380733de55473426f2b32bf51f7124711b7a9e
OS	Linux
```
