### ISSUE TITLE
Nightly crashes when attempting omnibox search in private window

### ISSUE THREAD

**Issue by moritzhaller** [brave/brave-browser#33716]
## Description 

Nightly crashes when attempting omnibox search in private window.

## Steps to Reproduce

   1. Open private window
   2. Type "youtube", "google" or any other search provider into the omnibox (reproduced with youtube and google scholar)
   3. Hit enter to activate the omnibox search feature
   4. Type anything and hit enter again to trigger the search
   5. Browser crashes

## Actual result:

Browser crashes after hitting enter
<img width="883" alt="Screenshot 2023-10-18 at 13 58 41" src="https://github.com/brave/brave-browser/assets/1259879/eb8d54ea-cc9b-40a1-a5f7-c968b191012a">

## Expected result:
Search result page

## Reproduces how often: 

Easily reproduced

## Desktop Brave version:

1.60.26 Chromium: 117.0.5938.62 (Official Build) nightly (x86_64) 

## Version/Channel Information:

Nightly on MBP

**Comment by Ticks-mentracorps-menti-TEMP** [comment]
If you are going to use Nightly and report issues, update it. Nightly is already in 1.61.x and this problem was fixed long time ago. Also, use the search function to avoid duplicates. https://github.com/brave/brave-core/pull/20173

**Comment by moritzhaller** [comment]
can confirm this is resolved - thanks
