### ISSUE TITLE
[perf] Fix double rebuilding of default ruleset

### ISSUE THREAD

**Issue by atuchin-m** [brave/brave-browser#33718]
## Description 
As investigated in [a thread](https://bravesoftware.slack.com/archives/C3T9S9WKD/p1696900419824629) we have double rebuilding the default adblock ruleset during the startup when one of the extra list is enabled. Sadly we have some extra lists enabled by default (`Fanboy's Mobile Notifications`, `EasyList Cookie`).
That significantly increase startup CPU usage. 

## Steps to Reproduce
There is no user-visible steps, it's about startup performance. Could be verified by perf tests.

## Reproduces how often: 
Always when at least one extra adblock list is enabled.

## Version/Channel Information:
All actual versions are affected (at least from 1.58.x), both Desktop & Android.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  
NO (because the engine are still loaded during the startup)  
- Does the issue resolve itself when disabling Brave Rewards? 
NO
- Is the issue reproducible on the latest version of Chrome? 
NO

## Miscellaneous Information:
QA: still need to verify that adblock engine works as expected.

**Comment by atuchin-m** [comment]
The PR  is merged to master. Perf metrics were improved as expected.

The dashboard shows about -300ms CPU usage on startup. Adblock CPU startup usage has been reduced by half in the default scenario.
2044ms (before) => 1757ms (after). Just to reference: 1368ms (before, without adblock).

Also, memory usage of the browser process was improved: private_footprint_size: 144MB => 135MB.  reported_by_chrome:allocated_objects_size hasn’t been changed. I suppose the PR reduced the peak memory usage during startup. Because some of that memory wasn’t returned to the OS (probably saved in the allocator cache for future usage), the only first metric was improved.
![image](https://github.com/brave/brave-browser/assets/45488748/6ed5b7cc-ea00-401d-b0d4-2e87da7ac1e5)

**Comment by kjozwiak** [comment]
@brave/qa-team re: the above, we'll basically need to ensure that adblocking is still working as expected. So basically run through a quick spot check to ensure that everything is working as expected. For example, here's a quick spot check that I ran through via https://github.com/brave/brave-core/pull/20585#issuecomment-1776235145 before uplifting into `1.60.x` & `1.59.x`.

**Comment by kjozwiak** [comment]
The above can also be verified alongside https://github.com/brave/brave-browser/issues/32799. Basically ensuring that adblocking is working as expected.

**Comment by GeetaSarvadnya** [comment]
Verification PASSED on

```
Brave | 1.59.124 Chromium: 118.0.5993.117 (Official Build) (64-bit)
-- | --
Revision | 63d57e32ce0ff0a1e380461bc394351e97d1416a
OS | Windows 10 Version 22H2 (Build 19045.3570)

```
Verification notes can be found under https://github.com/brave/brave-browser/issues/32799#issuecomment-1779569058

**Comment by hffvld** [comment]
Verified on `Galaxy Tab S8` using version(s):
```
Device/OS: Galaxy Tab S8 [gts8wifixx-user 13 TP1A.220624.014 release-keys]
Brave build: 1.59.124
Chromium: 118.0.5993.117 (Official Build) (64-bit)
Revision: 63d57e32ce0ff0a1e380461bc394351e97d1416a
```
---------------------------

**STEPS:**
1. Followed the steps from https://github.com/brave/brave-browser/issues/32799#issue-1884399665

**ACTUAL RESULTS:**
- Verified that `ads` loaded within the page when visited https://www.zerohedge.com/ and disabled Shields. Re-enabled Shields and verified that ads were being blocked without issues.
- Verified that `first-party ads` were appearing when visited https://www.google.com/ and searched for Under Armour. Switched to `Aggressively block tracker & ads` and verified those `ads` were being removed/not being displayed anymore
- Verified that enabling `Block scripts` blocked the carousel when visiting https://www.blizzard.com.
- Verified that there was no cookie consent banner being displayed on the page when visiting https://digikey.com if `Block cookie consent notices` toggle is ON.
- Verified that the page appears grey when visiting https://mixed-script.badssl.com

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/2cc910e2-43c4-420d-a873-e8426602168d) | ![2](https://github.com/brave/brave-browser/assets/128532965/725a72c3-08a3-4240-ab83-528ac0576fa4) | ![3](https://github.com/brave/brave-browser/assets/128532965/bdb182cf-ec7d-45d4-b53f-bc92896b13b6) | ![4](https://github.com/brave/brave-browser/assets/128532965/b71282af-953c-44f8-ad1d-7f8e0fe28d0a) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/84d48de7-8649-4606-9bf1-b5369483eb30) | ![2](https://github.com/brave/brave-browser/assets/128532965/9448fe74-8a6a-4b36-b46c-313e1714819c) | ![3](https://github.com/brave/brave-browser/assets/128532965/b612da73-70fb-4eca-bd63-ec68f22aaf7e) | ![4](https://github.com/brave/brave-browser/assets/128532965/696321eb-c822-4a9b-98fc-4bc30539d1f9) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/28a2686f-48d9-405a-a4b8-75132961c65a) | ![2](https://github.com/brave/brave-browser/assets/128532965/fbba48b0-26e8-4801-a831-b8ac764a1694) | ![3](https://github.com/brave/brave-browser/assets/128532965/9a31897d-eec0-4279-a982-fcc4672b1a40) | ![4](https://github.com/brave/brave-browser/assets/128532965/056618cb-5470-4661-9f3b-ebaafed3bab2) |

**Comment by btlechowski** [comment]
Verified with

Brave | 1.59.124 Chromium: 118.0.5993.117 (Official Build) (64-bit)
-- | --
Revision | 63d57e32ce0ff0a1e380461bc394351e97d1416a
OS | Linux

Verified in https://github.com/brave/brave-browser/issues/32799#issuecomment-1779810220

**Comment by kjozwiak** [comment]
Verification **PASSED** on `macOS 14.0 x64 Sonoma` using the following build(s):

```
Brave | 1.59.124 Chromium: 118.0.5993.117 (Official Build) (x86_64)
--- | ---
Revision | 63d57e32ce0ff0a1e380461bc394351e97d1416a
OS | macOS Version 14.0 (Build 23A344)
```

Using the STR/information outlined via https://github.com/brave/brave-browser/issues/32799#issue-1884399665, ensured that `ad-blocking` was generally working as per the following:

* visited https://www.zerohedge.com and disabled shields and ensured that `ads` loaded within the page
  * re-enabled shields and ensured that ads were being blocked without issues
* visited https://www.google.ca and searched for Under Armour and ensured that first-party ads were appearing
  * switched to `Aggressively block tracker & ads` and ensured those ads were being removed/not being displayed anymore
* visited https://www.blizzard.com/en-gb/ and ensured that enabling `Block scripts` blocked the carousel
* visited https://digikey.com and ensured there was no `cookie consent` banner being displayed at the top of the page
  * https://user-images.githubusercontent.com/2602313/245333866-0b9ce862-7c52-4381-af8b-a593ee32c3a3.png
* visited https://mixed-script.badssl.com and ensured the page appears `grey`
