### ISSUE TITLE
Add a setting for allowing .onion requests in normal windows

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#33735]
In https://github.com/brave/brave-browser/issues/32108, we blocked all network requests to `.onion` URLs outside of Tor windows. Such network request will fail due to the need to use the tor proxy in order to resolve and connect to them, but before failing they will [leak the name of the Onion services to the DNS resolver](https://hackerone.com/reports/2098135).

One use case we had not anticipated however was people installing the tor daemon on their (likely OpenWRT or Pi-hole-based) router and then letting all local clients resolve and connect to `.onion` normally outside of Tor windows (or in fact outside of Brave too).

The proposed fix is to add a setting in `brave://settings/privacy` under _Tor windows_:

> **Only resolve `.onion` addresses in Tor windows**
> Onion services will not be available outside of Tor windows.

The toggle will be **on** by default, in line with the [RFC 7686](https://datatracker.ietf.org/doc/html/rfc7686) recommendation:
> Applications that do not implement the Tor protocol SHOULD generate an error upon the use of .onion and SHOULD NOT perform a DNS lookup.

In addition, we should add a devtools console warning pointing to this setting when we block a network request for this reason.

**Comment by fmarier** [comment]
Noting that this is a [problem with cURL as well](https://lists.torproject.org/pipermail/tor-dev/2023-September/014850.html) and that this transparent proxying of `.onion` services is [considered "ill-advised"](https://lists.torproject.org/pipermail/tor-dev/2023-November/014865.html).

We'll still add the setting for users who want this use-case to work, but the default behavior will remain the same.

**Comment by jurglic** [comment]
Hi, do we have any ETA on this?

It is really annoying because I cannot use Brave if it updates (at restart)... there's no way to pin to last version when this worked...

**Comment by fmarier** [comment]
@jurglic I am currently working on this and I expect it will ship with Brave 1.62.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.62.104 Chromium: 120.0.6099.71 (Official Build) beta (64-bit)
-- | --
Revision | e2b266991247b909fa88520bb12d018223872d29
OS | Windows 11 Version 22H2 (Build 22621.2715)
```

1. installed 1.62.104
2. launched Brave
3. skipped onboarding
4. opened brave://settings/privacy and confirmed that Only resolve .onion in Tor windows was Enabled by defaullt
5. opened the developer tools and focused the Console pane
6. loaded https://fmarier.github.io/brave-testing/onion-subresource-33735.html and confirmed the broken image
7. confirmed the error for onion16.png is net::ERR_BLOCKED_BY_CLIENT
8. opened `brave://settings/privacy` and disabled `Only resolve .onion in Tor windows`
9. cleared the devtools console
10. force-refreshed the page and confirmed broken image
11. confirmed the error for onion16.png is now net::ERR_NAME_NOT_RESOLVED
12. repeated the above steps in a Private Window with Tor window pref = on 
13  repeated above steps in a Private Window with Tor window with pref = off 

step 4 | step 6-7 | step 8 | step 11 
---- | ---- | ----- | ------
<img width="539" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/fff1c207-ed02-4c63-b4ec-0bcbc68166bf">|<img width="539" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/454702d1-51a4-4307-b889-177c3f0952a4">|<img width="958" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/a3c71137-9df1-40aa-a178-cf74bcd9e325">|<img width="539" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/101b0787-04ab-4705-b8b6-cc3d9dc629ce">

step 12a | step 12b | step 13 a | step 13b
----- | ----- | ----- | ----
<img width="953" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/9ec6879b-bd1d-4816-9e1d-85031f8d7fbd">|<img width="953" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/31ab7191-5c39-4133-81ce-349d81b64566">|<img width="959" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/801d4252-b681-4d1c-9381-588b9c23928f">|<img width="955" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/a19931ca-b267-4a4c-9e1a-af297c4963f3">

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.62.112 Chromium: 120.0.6099.115 (Official Build) beta (64-bit) 
Revision	ae1e179b9884b2de2f4ba0bdea7da3beaad93ffa
OS	Linux
```

**Comment by king-11** [comment]
is there a way to add proxy configuration to redirect onion URL resolution to tor service running locally?

**Comment by fmarier** [comment]
@king-11 You may want to file a separate issue for this since it's either a separate feature request, or a bug for something that should already work as part of the PAC support.

**Comment by king-11** [comment]
Sure thanks @fmarier
