### ISSUE TITLE
Crash Report when Brave stays open too long

### ISSUE THREAD

**Issue by svalentin** [brave/brave-browser#33748]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.59.117 Chromium: 118.0.5993.70
Operating System: Windows NT 10.0.19045

URL (if applicable) where crash occurred: Everywhere. Happens when idling

Can you reproduce this crash?
Yes, just leave Brave running in the background or foreground and it will eventually crash

Happens about once daily.
Crash IDs:
October 19: 15ac0200-b526-e60a-0000-000000000000
October 18 (this one): 81550000-b526-e60a-0000-000000000000
October 16: 9d950b00-29ee-dc0a-0000-000000000000
October 14: 55d60b00-29ee-dc0a-0000-000000000000
October 13: f97f0400-29ee-dc0a-0000-000000000000
October 13: 79fe0300-29ee-dc0a-0000-000000000000
October 12: f45e0200-29ee-dc0a-0000-000000000000
(and many more, ever since I started using Brave)

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/81550000-b526-e60a-0000-000000000000

**Comment by rebron** [comment]
@svalentin Can you update to 1.59.120 and see if you're still experiencing those same crashes.

**Comment by svalentin** [comment]
Still crashing:
crash id 9a011000-b526-e60a-0000-000000000000

**Comment by iefremov** [comment]
stale
