### ISSUE TITLE
Do not parse JSON files in wallet component if wallet isn't created

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#33757]
As this affects everyone's startup performance.

As investigated in a [thread](https://bravesoftware.slack.com/archives/C3T9S9WKD/p1697754898821249?thread_ts=1697754201.567329&cid=C3T9S9WKD) we parse the Wallet component even if there is no wallet created.
* no wallet created => no startup work to read/parse json
* (the best option) don't even register the component. This could create extra slow down on the first load, need to check.
* add a (browser) test to verify that to prevent future regression.

**Comment by bbondy** [comment]
Maybe do this by not even getting the component until a wallet is being created? I'm pretty sure we did this for Android at least recently cc @SergeyZhukovsky

**Comment by SergeyZhukovsky** [comment]
Yeah @AlexeyBarabash made it happen(download component on demand only) on Android in that PR https://github.com/brave/brave-core/pull/19086. The main goal for Android was to not occupy space on devices unless wallet is created.

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.62.114 x64 Beta build
- Verified steps from [brave/brave-core#20741](https://github.com/brave/brave-core/pull/20741)
- Verified wallet component is only downloaded after the wallet is created
- Verified when wallet component is being downloaded loading state is shown
