### ISSUE TITLE
Support `#@#+js()` syntax for blanket scriptlet exception

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#33766]
See https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#scriptlet-injection

This is supported as of `adblock-rust 0.8.2`.

**Comment by kjozwiak** [comment]
The above requires `1.60.102` or higher for `1.60.x` verification 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.60.102 Chromium: 118.0.5993.96 (Official Build) beta (64-bit)
-- | --
Revision | 3598a9fc6b7752181feb25caa131bc386d6d054c
OS | Windows 11 Version 22H2 (Build 22621.2428)
```

Using the STR/Cases outlined via https://github.com/brave/brave-core/pull/20614#issue-1953545506, went through the following:

**`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|-----------------
![image](https://github.com/brave/brave-browser/assets/2602313/6c24894f-e814-491a-8f5a-3545e0e1c449) | ![image](https://github.com/brave/brave-browser/assets/2602313/da7cff11-6ee8-423b-b023-74383e5a584b) | ![image](https://github.com/brave/brave-browser/assets/2602313/13d2033d-bee3-4005-a70f-be1bb2ec13f3) | ![image](https://github.com/brave/brave-browser/assets/2602313/ac105734-ad42-4443-bb50-9bf8cef8971f)

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 [panther_beta-user 14 U1B2.230922.010 release-keys]
Brave build: 1.60.106
Chromium: 119.0.6045.59 (Official Build) (64-bit) 
Revision: 16064193dde8c55f64dabd32f125c0cd9380f96a
```
---------------------------

**STEPS:**
1. Followed the steps from https://github.com/brave/brave-core/pull/20614#issue-1953545506

**ACTUAL RESULTS:**
- Verified that the result is `{}` when custom filter is `example.com##+js(json-prune, test)` and pointing to `JSON.parse('{"test": true}')`
- Verified that result is `{test: true}` when custom filter is `example.com##+js(json-prune, test)`, `example.com#@#+js()` and pointing to `JSON.parse('{"test": true}')`

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/fa5589b3-1bbd-42ae-8f6f-f0bd814f3329) | ![2](https://github.com/brave/brave-browser/assets/128532965/e294f28f-ec01-4444-8d2c-7bf3e16d8a8f) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/0cbbf61e-a4d3-4cea-b354-9f4c52e64cce) | ![2](https://github.com/brave/brave-browser/assets/128532965/5376d0b1-a657-4f0e-8d67-abe5097b1ede) |

**Comment by superlex** [comment]
Hi,
just update to Brave 1.60.110.

```
example.org##+js(set-cookie, cookie, 1)
example.org#@#+js()
```
works

```
example.org##+js(set-cookie, cookie, 1)
#@#+js()
```
doesn't work

**Comment by antonok-edm** [comment]
@superlex yes, at the moment all cosmetic filters in Brave must be prefixed with a list of domains . We don't currently support wildcard injections (or exceptions).

**Comment by superlex** [comment]
Oh ok, thanks for your reply 😊
