### ISSUE TITLE
Default Fonts on WebUI should be Brave brand

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#3376]
Visit chromium webui pages (settings, history, bookmarks, downloads, extensions) and the typography is all in Roboto. This should be Muli (body) and Poppins (titles).

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.63.21 Chromium: 73.0.3683.75 (Official Build) dev(64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Mac OS X

- Verified test plan from https://github.com/brave/brave-core/pull/1422

**Comment by srirambv** [comment]
@petemill  on Linux all text(titles/body) on settings page is in Muli.
![image](https://user-images.githubusercontent.com/17010094/55168453-3aa70e80-5149-11e9-97be-496f7b5ac77c.png)
![image](https://user-images.githubusercontent.com/17010094/55168598-780b9c00-5149-11e9-95f2-5c6ada3a375a.png)

I only see Poppins used in Sync page
![image](https://user-images.githubusercontent.com/17010094/55168899-1ac41a80-514a-11e9-8d67-eaf3e8041fba.png)


Is this expected?

**Comment by petemill** [comment]
@srirambv this is the case on all platforms - some pages just require custom work to override each component. Settings will come with a more specific PR. Thanks for noticing 👍 

By the way, inspecting the css rules like that is less reliable than the following tip for detecting which fonts were actually used for any piece of text:
1. Inspect the element (as you have done here)
2. Click on the 'Computed' tab (next to Styles)
3. Scroll down to the very bottom of that tab and see the "Rendered Fonts" section
![image](https://user-images.githubusercontent.com/741836/55364632-46bb0500-5496-11e9-899d-6e2dd3dd52bd.png)

This may be quicker to mentally parse, and removes uncertainty around css rules or variables. Hope that helps!

**Comment by srirambv** [comment]
Thanks for the confirmation @petemill :+1:
