### ISSUE TITLE
Wallet Panel showing Blank Screen when locked

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#33779]
## Description 

The Wallet is showing a Blank screen when locked.

## Steps to Reproduce

   1. Go to brave://wallet and lock your wallet
   2. Open the Wallet `Panel`
   3. It shows a blank screen.

## Actual result:

![Screenshot](https://github.com/brave/brave-browser/assets/40611140/11de7724-b45d-482e-9d4f-39a8f7b5a3a9)

## Expected result:
Should show the `Unlock` screen

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? no
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.61.67 Chromium: 119.0.6045.105 (Official Build) beta (64-bit)
-- | --
Revision | `09cc687dc27ccd8acafeebf5af1dc620b4d9cb22`
OS | Windows 11 Version 22H2 (Build 22621.2506)

- Verified steps from [brave/brave-core#20618](https://github.com/brave/brave-core/pull/20618)
- Verified Wallet panel shows unlock screen when closing and reopening the panel

https://github.com/brave/brave-browser/assets/17010094/72b4568a-c81b-4123-b533-0d92e508cdc1

---------------------

**Verification passed on**

Brave | 1.60.81 Chromium: 118.0.5993.117 (Official Build) (64-bit)
-- | --
Revision | `09cc687dc27ccd8acafeebf5af1dc620b4d9cb22`
OS | Linux

- Verified steps from [brave/brave-core#20618](https://github.com/brave/brave-core/pull/20618)
- Verified Wallet panel shows unlock screen when closing and reopening the panel

https://github.com/brave/brave-browser/assets/17010094/1ce8f71e-d802-4cc7-8d58-11b7e28930a9

---------------------

**Verification passed on**

Brave | 1.60.81 Chromium: 118.0.5993.117 (Official Build) (arm64)
-- | --
Revision | `09cc687dc27ccd8acafeebf5af1dc620b4d9cb22`
OS | macOS Version 14.1 (Build 23B74)

- Verified steps from [brave/brave-core#20618](https://github.com/brave/brave-core/pull/20618)
- Verified Wallet panel shows unlock screen when closing and reopening the panel

https://github.com/brave/brave-browser/assets/17010094/53d564f0-bd9d-439f-91e2-3de1859e0849
