### ISSUE TITLE
Checkboxes should use Brave color palette

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#3377]
Chromium webui pages all use material color palette for checkboxes. These should use brave color palette. 

## Test plan
Check a checkbox on the left of any history item in chrome://history.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.63.21 Chromium: 73.0.3683.75 (Official Build) dev(64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Mac OS X

- Verified test plan from description
- Verified test plan from https://github.com/brave/brave-core/pull/1422
