### ISSUE TITLE
Too much spacing above tab strip on Linux in update horizontal tabs

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#33781]
## Description 

On Linux, the spacing above the tabstrip, when then "horizontal tabs update" is enabled, appears too large.

## Actual result:

![linux-top-spacing](https://github.com/brave/brave-browser/assets/5995084/9f8ef01f-413a-4971-8b2b-8b4723a42c6d)

**Comment by git-Hmmm** [comment]
I think it's to have some space for dragging
I personally like it
![image](https://github.com/brave/brave-browser/assets/102938585/a2f27777-c866-48d5-b64b-46c42c2a0737)
