### ISSUE TITLE
Buttons should use Brave brand style

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#3378]
Chromium webui pages all use material color palette for checkboxes. These should use brave color palette. 

## Test plan
Check a checkbox on the left of any history item in chrome://history and observe the buttons on the top for 'cancel' and 'delete'. They should be rounded with a black border and text.****
### Old
![image](https://user-images.githubusercontent.com/741836/52842041-b6299080-30b2-11e9-800d-cd635868cceb.png)

### New
![image](https://user-images.githubusercontent.com/741836/52842050-bb86db00-30b2-11e9-92ba-e3a020bc7db1.png)

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.63.21 Chromium: 73.0.3683.75 (Official Build) dev(64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Mac OS X

- Verified test plan from description
- Verified test plan from https://github.com/brave/brave-core/pull/1422
