### ISSUE TITLE
LastPass extension cannot contact server

### ISSUE THREAD

**Issue by cmavr8** [brave/brave-browser#3379]
## Description 
The Lastpass extension occasionally gives this error: 

> An error occurred while attempting to contact the server. Please check your internet connection.

## Steps to Reproduce

   1. Install lastpass 
   2. Log in to lastpass with an enterprise account
   3. Wait a 2-3 minutes

## Actual result:
![image](https://user-images.githubusercontent.com/843878/52850377-9ecebf80-3113-11e9-8024-e8f9cd055321.png)

## Expected result:
No errors, Lastpass should just work

## Reproduces how often: 
Easily reproduced once every few minutes

## Brave version (brave://version info)

> Brave | 0.59.35 Chromium: 72.0.3626.81 (Official Build) (64-bit)
> Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
> OS | Linux

Lastpass:

> LastPass Chrome Toolbar
> Version: 4.24.0
> Built: Thu Jan 31 2019 13:45:22 GMT+0000 (UTC)
> Binary Component: false

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Not sure, haven't tried dev/beta.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
No
- Is the issue reproducible on the latest version of Chrome? 
No.

### Additional Information
This is pretty much the same issue as in https://github.com/brave/browser-laptop/issues/12612. The resolution of that issue was that the bug was fixed in brave-core back in September. There's no reference of version but I'm assuming that the patch has reached stable by now. Someone should help determine if this assumption holds. I did not submit a question in the original ticket since the project is archived.

I tried clearing cookies for lastpass.com, logging out/in, clearing LP cache, whitelisting lastpass.com in 3rd-party cookie exception but nothing helped.

**Comment by alissa-huskey** [comment]
I've been having this issue within the last few days.

Brave Version 1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit)
Lastpass Chrome Extension Version 4.38.0

On my laptop I'm not having this issue, and there I'm running:

Version 0.69.135 Chromium: 77.0.3865.120 (Official Build) (64-bit)
Lastpass Chrome Extension Version 4.38.0

**Comment by ryanbr** [comment]
@alissa-huskey @cmavr8 

Just re-tested this, it's working okay, no issues?

**Comment by cmavr8** [comment]
Sorry, I can't test, I don't have access to LP enterprise anymore.
If @alissa-huskey can't confirm either, let's close the issue.
Thanks @ryanbr !

**Comment by alissa-huskey** [comment]
This works now, thank you.

**Comment by timing** [comment]
This is happening again on my new laptop. Maybe reopen this issue? Or am I the only one?

**Comment by cmavr8** [comment]
@timing are you using LP enterprise? I had no access to LP enterprise to test the fix in 2021 so there's a chance the issue still exists.

**Comment by ryanbr** [comment]
@timing still occuring? can you re-test. If it still fails, uninstall and reinstall the extension.

**Comment by timing** [comment]
I think the reinstallation of the extension made the error go away. Weird btw, it was a fresh install already. And I did delete all the lastpass cookies as well.
