### ISSUE TITLE
Brave Ads iOS unification prerequisites

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#33795]

**Comment by kjozwiak** [comment]
Related to https://github.com/brave/brave-ios/issues/8301 👍

**Comment by LaurenWags** [comment]
Per discussion with @kjozwiak changing this one to `QA/No` as it will be tested on iOS with https://github.com/brave/brave-ios/issues/8301.

Please let me know if there are any concerns with this @tmancey @btlechowski 👍🏻
