### ISSUE TITLE
Text in element Not Visible on Mobile with Brave Browser

### ISSUE THREAD

**Issue by akarshghildyal** [brave/brave-browser#33810]
## Description 

The issue involves the "srmkzilla.net/team" website when accessed through the Brave browser on mobile devices. Specifically, the problem is that the text within a thought bubble on the website is not visible. If you highlight the text only then it is visible. The expected behavior is that the text should be readily visible without the need for highlighting. This bug affects the user experience when viewing the website on the Brave browser on mobile devices.

## Steps to reproduce 

1. Open the Brave browser on a mobile device.
2. Navigate to the "https://www.srmkzilla.net/team" .
3. Click on/select any member image.
4. Observe that the thought bubble seems empty unless you select or highlight the text in it.

## Actual result 
Currently, when I visit the website on the Brave browser on my mobile device, the text in the thought bubble is not visible by default. I have to select or highlight the text to make it visible.
![dd9adf9f-e1f6-4413-8ba3-a91efcb232e9](https://github.com/brave/brave-browser/assets/129004417/30b48697-9f0f-4c0e-9b48-d9a1659d0f44)

## Expected result
When viewing the "Teams" page, I expect the text in the thought bubble to be visible when viewing the website on brave mobile browser without needing to select or highlight it.
![image_2023-10-22_164459361](https://github.com/srm-kzilla/srmkzilla-net/assets/129004417/70000a5e-6d44-4c96-a5ab-daf97eac2ee9)

## Issue reproduces how often 
Easily reproduced.

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes 
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86):
   - Device type : Phone (OnePlus Nord)
   - Android version: 12, Security Update : January 5, 2023
   
## Brave version
Brave 1.59.117, Chromium 118.0.5993.70

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? This issue does not arise in Chrome.

**Comment by mingkee27** [comment]
Here is a temporary workaround
Uninstall latest version
Download 1.58.135 from apkmirror and install
DO NOT AUTO UPDATE IN PLAY STORE!!! (or problem will come back)
Setup again
