### ISSUE TITLE
Download bar becomes white when browser is not in focus

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#3381]
## Description 

Download bar becomes white when browser is not in focus

## Steps to Reproduce (No guarantee)

Steps that i did when encountered the issue but no guarantee that it will be same

   1. Visit www.onlineconverter.com/gif
   2. Upload a video and convert it to gif, wait till the site completes the conversion and redirects to download page
   3. Switch focus to some other app so that file save prompt shows up on browser
   4. Save the file to a location, browser download bar becomes white. Close/reopen browser doesn't fix it

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/52852691-57f6bf00-313f-11e9-8eb4-eb976f150e0a.png)

## Expected result:
Shouldn't change the colour of the download bar

## Reproduces how often: 

No idea only happened once

## Brave version (brave://version info)

Brave | 0.61.24 Chromium: 73.0.3683.27 (Official Build) dev(64-bit)
-- | --
Revision | 7d14d84723e1d6512b0b5ed516aff92d12fd8aa9-refs/branch-heads/3683@{#290}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Only seen on dev build
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
n/a
- Is the issue reproducible on the latest version of Chrome? 
n/a
### Additional Information

cc: @petemill @karenkliu @brave/legacy_qa to check on other platforms

**Comment by GeetaSarvadnya** [comment]
Not Reproducible on Windows 10 x64 - 0.60.29

**Comment by GeetaSarvadnya** [comment]
1+ https://community.brave.com/t/when-downloading-files-with-the-gtk-theme-linux/54170/2
