### ISSUE TITLE
[Bug] Google translate doesnt work - cant connect to network

### ISSUE THREAD

**Issue by inson1** [brave/brave-browser#33823]
![brave_FwpA4m6ULw](https://github.com/brave/brave-browser/assets/75314629/48a7016f-f514-4e99-b6e1-f8a3758044df)

**Comment by rebron** [comment]
duplicate of https://github.com/brave/brave-browser/issues/3725

**Comment by inson1** [comment]
@rebron Sorry, I looked. I don't know how I could have missed that.

**Comment by inson1** [comment]
sorry for spam, I'm just reorganizing my solved issues - jg8tzJHCu0Qcc1zJGcht
