### ISSUE TITLE
Tab group background color removed

### ISSUE THREAD

**Issue by mifas** [brave/brave-browser#33824]
## Description 
A recent update removed the Tab group background color. now only applies foreground color
I even changed color setting in the manage profile section. not able to apply background color. 

See the difference between chrome and brave in the result section

## Steps to Reproduce

   1. Assign tabs to group
   2. Change the color

## Actual result:
<img width="243" alt="image" src="https://github.com/brave/brave-browser/assets/4384874/8545d21d-59a3-437a-b2f0-8674d92a8aad">

## Expected result:
<img width="334" alt="image" src="https://github.com/brave/brave-browser/assets/4384874/24195d40-ec90-40a9-978b-6dc2a5adf369">

## Reproduces how often: 
always

## Brave version (brave://version info)
Version 1.60.96 Chromium: 118.0.5993.88 (Official Build) beta (arm64)

**Comment by rebron** [comment]
@mifas Do you mean the green background or you want the Tab group colors more pronounced? We changed it so that the title has the color and the underline has the group color.

**Comment by rebron** [comment]
cc: @aguscruiz @zenparsing

**Comment by mifas** [comment]
As title says, this is about "Tab group". 
Not about theme colour
---

Now its very difficult to read and identify, not aligned with other browsers. 
Is there way make it optional or something, So people like low vision can still prefer the background color

**Comment by rebron** [comment]
@mifas Going to close this one in favor of https://github.com/brave/brave-browser/issues/34041 as we have a fix against that issue. Thanks for reporting and your feedback.

**Comment by mifas** [comment]
Thank you for improving the colors.
Now much better

**Comment by aguscruiz** [comment]
Glad you like the update @mifas!
