### ISSUE TITLE
Leo opt-in required on browser update

### ISSUE THREAD

**Issue by mattmcalister** [brave/brave-browser#33825]
## Description 
Leo opt-in appears on browser update, but I have Premium credentials. I shouldn't be required to opt-in again.

## Steps to Reproduce
   1. Purchase Leo Premium and verify credentials are present using skus-internals
   2. Update browser
   3. Open Leo from Sidebar
   4. See Premium indicator in logo bar and see Leo opt-in prompt

## Actual result:
![image](https://github.com/brave/brave-browser/assets/71029/7dbef8c9-07b3-4ae7-a8bb-1c955c0c5d53)

## Expected result:
If I've opted in to Leo I should not have to opt in again, particularly as a Leo Premium user

## Reproduces how often: 
Easily

## Brave version (brave://version info)
`Version 1.61.39 Chromium: 118.0.5993.96 (Official Build) nightly (arm64)`

## Version/Channel Information:
Nightly

**Comment by petemill** [comment]
We changed the pref key and format. This only impacted nightly users, possibly beta and it was a one-off. Decided not to migrate test users.
