### ISSUE TITLE
[ads] Generate and upload text classification CRX component resource packages

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#33832]

**Comment by ptjames** [comment]
Currently blocked by https://github.com/brave/brave-browser/issues/33829. Flat buffer versions of non-en v1 models needed until v2 models are created

**Comment by ptjames** [comment]
Packages have been successfully updated

**Comment by tmancey** [comment]
Closing issue as successfully updated

**Comment by tmancey** [comment]
@btlechowski setting to QA/No because this should be tested as part of https://github.com/brave/brave-browser/issues/33336
