### ISSUE TITLE
Market Tab showing wrong colors for Up and Down prices

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#33838]
## Description 

The `Market` tab is showing `red` for up and `green` for down

## Steps to Reproduce

   1. Open the `Market` tab
   2. It is showing `red` for when the price is up and `green` for when the price is `down`

## Actual result:

https://github.com/brave/brave-browser/assets/40611140/d2618422-5c63-43c0-a6df-690ee986a4ea

## Expected result:
Should show `green` when the price is up and `red when the price is `down`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.59.124` or higher for `1.59.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.59.124 Chromium: 118.0.5993.117 (Official Build) (64-bit)
-- | --
Revision | 63d57e32ce0ff0a1e380461bc394351e97d1416a
OS | Windows 11 Version 22H2 (Build 22621.2428)

- Verified steps from issue description
- Verified market price change colour is shown correctly red for price down and green for price up

https://github.com/brave/brave-browser/assets/17010094/21f6fd94-3509-4095-a559-c8ff25c749fc
