### ISSUE TITLE
Sign Data Panel is being persisted breaking the UI

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#33846]
## Description 

The `SignData` panel is being persisted which breaks the UI after it is reopened since `sign data` will return `undefined`

## Steps to Reproduce

   1. Go to https://pwgoom.csb.app/ and create a `Sign Message` request
   2. After the `Panel` displays the the `Message` request, dismiss the panel
   3. Try to reopen the `Panel`, it will be broken

## Actual result:

https://github.com/brave/brave-browser/assets/40611140/5c3a085c-4286-4e36-9369-06ccf1474e26

## Expected result:
We should not persist the `SignData` panel since it `Sign Data` will return undefined after dismissal.

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.61.85 Chromium: 119.0.6045.163 (Official Build) beta (64-bit)
-- | --
Revision | 5e2736df90772dd1b66ca5013e47c1fc467c9762
OS | Windows 11 Version 23H2 (Build 22631.2715)

- Verified steps from [brave/brave-core#20644](https://github.com/brave/brave-core/pull/20644)
- Verified Sign Data Panel is persisted between panel open-close state

https://github.com/brave/brave-browser/assets/17010094/3b41e044-d344-4b48-ac70-c9cb989591f0
