### ISSUE TITLE
Solana sign message not displaying message

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#33848]
## Description 

The `Solana Sign Message` panel is not displaying the `Message`

## Steps to Reproduce

   1. Go to https://pwgoom.csb.app/ and create a `Sign Message` request
   2. You will see that the `Solana Sign Message` panel does not display a message

## Actual result:

![Screenshot 6](https://github.com/brave/brave-browser/assets/40611140/d4c79c5c-22e9-4fe0-826f-ac313e081334)

## Expected result:
Should display the `Message`

![Screenshot 5](https://github.com/brave/brave-browser/assets/40611140/9ded46b2-fa54-4ab6-99c5-e4be5f69243f)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.60.104` or higher for `1.60.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.60.104 Chromium: 118.0.5993.117 (Official Build) (64-bit)
-- | --
Revision | 5dfa047eac682ad367174af6503fc21b59db5977
OS | Windows 11 Version 22H2 (Build 22621.2428)

- Verified steps from issue description
- Verified Solana Sign message shows message data in panel

https://github.com/brave/brave-browser/assets/17010094/fb8da86c-d0d5-4973-b27d-6230e41bf431
