### ISSUE TITLE
Clicking at top of updated horizontal tab does not activate the tab

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#33844]
## Description 

When the `#brave-horizontal-tabs-update` feature flag is enabled, on some platforms clicking a non-active tab at the very top of the tab shape will initiate a "window-drag" operation instead of activating the tab.

## Steps to Reproduce

   1. Enable `#brave-horizontal-tabs-update` and restart.
   2. Open several tabs.
   3. Click a non-active tab in the topmost portion of the tab shape.

## Actual result:

Tab will not be activated.

## Expected result:

Tab should be activated.

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Appears to affect Linux and Mac. Does not appear to affect Windows. (Edit: This does appear to affect some Windows users.)

## Version/Channel Information:

1.60, 1.61

## Additional Information

It appears that the active tab is not affected (it can still be clicked and dragged from the very top of the shape).

**Comment by zenparsing** [comment]
Chrome also exhibits this behavior, although with a smaller "top tab area". It is intentional; the idea is that treating clicks at the very top of inactive tabs will allow the user to more easily drag the window around the screen. The default algorithm to determine the height of this "window caption area" results in a value that is slightly too large and is more noticeable than it should be (at least for our updated tab design).

I think we should keep the behavior, but reduce the height of this area to roughly match Chrome.

**Comment by Brave-Matt** [comment]
@zenparsing  noticed that above you stated:

> _Appears to affect Linux and Mac. Does not appear to affect Windows._

I want to point out that Windows users are also encountering this.

**Comment by petersaints** [comment]
> Chrome also exhibits this behavior, although with a smaller "top tab area". It is intentional; the idea is that treating clicks at the very top of inactive tabs will allow the user to more easily drag the window around the screen. The default algorithm to determine the height of this "window caption area" results in a value that is slightly too large and is more noticeable than it should be (at least for our updated tab design).
> 
> I think we should keep the behavior, but reduce the height of this area to roughly match Chrome.

With the new Chrome Refresh 2023 flag enabled ([#chrome-refresh-2023](chrome://flags/#chrome-refresh-2023)) redesign the tabs look like they don't reach the top, but you can click them anyway.

See the following video:
https://streamable.com/x46mt2

**Comment by MadhaviSeelam** [comment]
Verification `In progress` usig
```
Brave | 1.61.60 Chromium: 119.0.6045.105 (Official Build) beta (64-bit)
-- | --
Revision | 1ecda441378e2e473fd84b38456413224121751c
OS | Windows 11 Version 22H2 (Build 22621.2428)
```

installed 1.61.60
launched Brave
opened `brave://flags` in a new tab
enabled `#brave-horizontal-tabs-update` and clicked `Relaunch`
opened several tabs.
clicked the top area of inactive tabs.

#### confirmed when clicking the very (very) top of the tab (upper ~10%), tab was not selected, instead, the window was minimized to allow dragging the window.
#### confirmed when clicking anywhere else in the tab, tab was selected



https://github.com/brave/brave-browser/assets/98358127/10adf015-62b3-437e-ac42-438e95b4a367

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using

```
Brave | 1.61.66 Chromium: 119.0.6045.105 (Official Build) beta (x86_64)
-- | --
Revision | aaaecfc0d925cde58e40e1b689464f1c630ef96d
OS | macOS Version 14.2 (Build 23C5030f)
```

### Steps:
1. installed `1.61.66`
2. launched Brave
3. ensured `brave://flags/#brave-horizontal-tabs-update` was `Enabled (default)`
4. opened several tabs
5. clicked the top area of inactive (backgrounded) tabs

**Comment by petersaints** [comment]
> ## Verified `PASSED` using
> ```
> Brave | 1.61.66 Chromium: 119.0.6045.105 (Official Build) beta (x86_64)
> -- | --
> Revision | aaaecfc0d925cde58e40e1b689464f1c630ef96d
> OS | macOS Version 14.2 (Build 23C5030f)
> ```
> 
> ### Steps:
> 1. installed `1.61.66`
> 2. launched Brave
> 3. ensured `brave://flags/#brave-horizontal-tabs-update` was `Enabled (default)`
> 4. opened several tabs
> 5. clicked the top area of inactive (backgrounded) tabs
> 
> ### Confirmed when clicking the very (very) top of the tab (upper ~10%), tab was not selected, instead, the window was minimized to allow dragging
> ### Confirmed when clicking anywhere else in the tab, tab was selected
> ![window-drag](https://user-images.githubusercontent.com/387249/280813529-8652498a-6bfb-4594-825f-e7a560ba010e.gif) [ ![window-drag](https://user-images.githubusercontent.com/387249/280813529-8652498a-6bfb-4594-825f-e7a560ba010e.gif) ](https://user-images.githubusercontent.com/387249/280813529-8652498a-6bfb-4594-825f-e7a560ba010e.gif) [ ](https://user-images.githubusercontent.com/387249/280813529-8652498a-6bfb-4594-825f-e7a560ba010e.gif)

This is the correct behavior when a window is not maximized. However, when a window is maximized the space on top of a tap should still select it. That is the behavior on the Chrome/Chromium redesign: https://streamable.com/x46mt2

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.61.82 Chromium: 119.0.6045.163 (Official Build) beta (64-bit) 
Revision	c5d19b3a31e7e3ddaaa1fa2ea52b9338003e754e
OS	Linux
```
