### ISSUE TITLE
Crash Report when reset rewards on android

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#33843]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.59.120 Chromium: 118.0.5993.88
Operating System: Android 13

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Reset rewards
2. Select `Restart later`
3. Kill the browser by swipe
4. Start browser

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/21140d00-b526-e60a-0000-000000000000

**Comment by iefremov** [comment]
@aseren is it still reproducible?

**Comment by aseren** [comment]
Closing as no longer reproducible.
