### ISSUE TITLE
AI Chat crashes in private windows

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#33842]
Open sidebar in a private window to AI Chat and it will crash. This is due to no skus service available in private windows. First we can fix the crash, which will prevent premium working in AI Chat, and then we can consider passing in the original profile skus service for private AI Chat sessions (https://github.com/brave/brave-browser/issues/33841)

**Comment by bbondy** [comment]
Adding QA/No because we're planning to disable it in guest and private windows in 1.60.x at least.
