### ISSUE TITLE
[ads] Add brand hostname to custom push notifications

### ISSUE THREAD

**Issue by aseren** [brave/brave-browser#33847]
See the thread for more details: https://bravesoftware.slack.com/archives/CJL3G0S95/p1694803727792639?thread_ts=1694798923.945899&cid=CJL3G0S95

**Comment by tmancey** [comment]
Closing as a duplicate of https://github.com/brave/brave-browser/issues/31119, @aguscruiz your thoughts on this change, and if design/product agree could you add to https://github.com/brave/brave-browser/issues/31119

**Comment by aguscruiz** [comment]
Added to the designs! 
https://www.figma.com/file/FW1XBDHAtZFUccI3cVUzeh/%F0%9F%93%A2-Ads?type=design&node-id=156%3A5428&mode=design&t=Gjek4MgZLRPe4Ant-1
