### ISSUE TITLE
one new tab page image links to a site which is not secure

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#3384]
## Description 
Found while testing https://github.com/brave/brave-browser/issues/2504

One of the new tab page images links to a site that is not secure and doesn't use HTTPS

## Steps to Reproduce

   1. Open new tabs until you get the one below.
   2. Hover over artist's name, link does not use HTTPS
   3. Click on link, site is not secure

## Actual result:
![screen shot 2019-02-15 at 12 03 36 pm](https://user-images.githubusercontent.com/28145373/52872363-54047600-311a-11e9-9c08-7dec884d9f0b.png)

![screen shot 2019-02-15 at 12 08 20 pm](https://user-images.githubusercontent.com/28145373/52872391-68e10980-311a-11e9-8a4c-ec52f4bc8c51.png)

## Expected result:
All links point to sites which use HTTPS

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.60.28 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Mac OS X

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by tomlowenthal** [comment]
It sounds like fixing this would mean requiring that any artist whose pictures we use on the new tab page has an HTTPS website?

**Comment by LaurenWags** [comment]
Seems like it to me, however if that's not something we want to do then please do close as `wontfix`.

**Comment by tomlowenthal** [comment]
I think it's okay to have an HTTP link to an artist's HTTP website.
