### ISSUE TITLE
AI Chat: Put ModelIntro on blank non-context conversations

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#33852]
Open AI Chat on NTP
Should see Model Intro.

Open AI Chat on page with content
Should not see Model Intro until model is changed in the current side panel.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.60.106 Chromium: 119.0.6045.59 (Official Build) (64-bit)
-- | --
Revision | 16064193dde8c55f64dabd32f125c0cd9380f96a
OS | Windows 10 Version 22H2 (Build 19045.3636)
```

## Steps:
1. installed `1.60.106`
2. launched Brave
3. enabled `AI chat` via `brave://flags`
4. clicked on `Relaunch`
5. opened a new-tab page
6. clicked on the `Leo` icon in the sidebar
7. clicked on `Accept and begin`
8. confirmed `llama2-13b` model intro
9. loaded `realsimple.com`
10. confirmed no model intro
11. clicked on the `...` ellipsis
12. chose `claude-instant-v1`
13. confirmed model intro
14. clicked on the `...` ellipsis
15. chose `llama2-70b`
16. confirmed model intro

### Confirmed model intro shows on new-tab pages and when switching to models, but not on pages with content, by default

`new-tab page` (`llama2-13b`) |  `realsimple.com` | `claude` | `llama2-70b`
------------------|--------------------|---------|---------------
![image](https://github.com/brave/brave-browser/assets/387249/321fec1e-d0ec-4ddb-9aaf-f4bba10304fd) | ![image](https://github.com/brave/brave-browser/assets/387249/1b82b356-d3b1-4463-9318-c8f2cd8684ed) | ![image](https://github.com/brave/brave-browser/assets/387249/dda66b3e-3e88-4f39-bcc1-c62072f8c8a9) | ![image](https://github.com/brave/brave-browser/assets/387249/ac80d424-add4-4f3b-b79e-5423cfdbc2ca)
