### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by tplon2001** [brave/brave-browser#33855]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.59.120 Chromium: 118.0.5993.88
Operating System: Windows NT 10.0.19045

URL (if applicable) where crash occurred:

Can you reproduce this crash? I don't know.

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. My computer was sitting idle for approximately 30 minutes when it crashed
2. In the past it has crashed while I was watching a video.
3. The browser has been crashing almost every night while it sits idle.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/541b0e00-b526-e60a-0000-000000000000

**Comment by iefremov** [comment]
stale
