### ISSUE TITLE
Disable AI Chat panel and features from Guest windows and private windows

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#33853]
Until https://github.com/brave/brave-browser/issues/33841 is resolved, the feature isn't usable in Private windows, so we should disable, and also make sure we're disabled in guest windows.

## Test Plan
Open Private Window
Verify AI Chat sidebar button is disabled
Verify that typing in Location Bar does not offer Brave Leo suggestions
Try to visit `chrome-untrusted://chat` in a Tab
Verify the page is blocked

Repeat the steps for Guest and Tor windows.

**Comment by petemill** [comment]
added test plan

**Comment by kjozwiak** [comment]
The above requires `1.60.105` or higher for `1.60.x` verification 👍

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version:

```
Brave	1.60.109 Chromium: 119.0.6045.59 (Official Build) (64-bit) 
Revision	fc399c7c433510eb03c2b35281bf8935804b99de
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
- Ensured that `chrome-untrusted://chat` is blocked in private window

Encountered:
https://github.com/brave/brave-browser/issues/34015
https://github.com/brave/brave-browser/issues/33995

![Screenshot 2023-10-31 at 11 19 05 AM](https://github.com/brave/brave-browser/assets/17885425/1091812d-1f52-4466-9bcf-44cace3afb7e)
