### ISSUE TITLE
Cannot click on upper section of brave browser while in full screen mode [mac]

### ISSUE THREAD

**Issue by PSkinnerTech** [brave/brave-browser#33851]
## Description 
When in fullscreen mode, I cannot click on tabs, domain field, and even upper sections of websites.  The only remedy I can find is to come out of full screen mode.  After that, I can access the tabs freely.

## Steps to Reproduce

Video of reproduced issue: https://www.loom.com/share/4d4bbf58bcc044cb97c9d3c102bf4ac3

## Actual result:

As you can see, I can kinda click around, but not consistently.  It's like there's something there blocking parts of the upper section of the browser while I'm in fullscreen mode.

## Expected result:

I should be able to click freely, but I'm only able to when I exit fullscreen mode.

## Reproduces how often: 

At first, this was only seldomly, but it seems to have become progressively worse.

## Brave version (brave://version info)

Version 1.59.122 Chromium: 118.0.5993.96 (Official Build) (x86_64)

## Other Additional Information:

- Is the issue reproducible on the latest version of Chrome? no

## Miscellaneous Information:
I'm on a 2019 Macbook Pro Intel processor.

**Comment by PSkinnerTech** [comment]
<img width="1792" alt="Screenshot 2023-10-23 at 7 08 29 PM" src="https://github.com/brave/brave-browser/assets/78289253/049c6c77-e305-4fe1-9572-0bcad4dcfe90">

After more investigation, something is blocking this exact area when I'm in fullscreen mode.  Anything within the box, I can't click in fullscreen mode.  I have to exit fullscreen mode to access anything within that red box.

**Comment by rebron** [comment]
duplicate of https://github.com/brave/brave-browser/issues/33646

**Comment by PSkinnerTech** [comment]
Solved by updating brave to Version 1.59.124 Chromium: 118.0.5993.117 (Official Build) (x86_64)
