### ISSUE TITLE
New `padding and shadow to main content window` is seen in Fullscreen videos.

### ISSUE THREAD

**Issue by Emi-HoloGhostRevisionist88** [brave/brave-browser#33879]
## Description 

I looks nice, but it shows even when going Fullscreen in videos, also in F11 mode.

As you can see here in Youtube in Private mode, it shows this padding 'border' in all videos.

![image](https://github.com/brave/brave-browser/assets/147446611/b267f02c-3901-4eca-9601-851fbb3f0543)

## Steps to Reproduce

   1. Press `F` in any any video
   2. or Press F11

## Actual result:

Border in all fullscreen videos caused by the padding

## Expected result:

no border in fullscreen videos

## Reproduces how often: 

100%

## Brave version (brave://version info)

1.61.47 Chromium: 119.0.6045.33 (Official Build) nightly (64-bit) Win11 22H2

**Comment by Emi-HoloGhostRevisionist88** [comment]
Also Devtools is getting it:

![image](https://github.com/brave/brave-browser/assets/147446611/7cd2093b-2aae-4179-a592-a9403b202876)

**Comment by rebron** [comment]
cc: @zenparsing @aguscruiz

**Comment by kjozwiak** [comment]
The above requires `1.61.67` or higher for `1.61.x` verification 👍
