### ISSUE TITLE
Wallet Menu Cut off By Header in Small Window Sizes

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#33877]
## Description 

The `Wallet Menu` is getting cut off by the page `Header` when the window size is small.

## Steps to Reproduce

   1. Open the `Wallet` and open the `Wallet Menu`
   2. Decrease the Browser window width really small
   3. The `Wallet Menu` gets cut off by the page `Header`

## Actual result:

![Screenshot 12](https://github.com/brave/brave-browser/assets/40611140/bc58d193-19e5-4781-96ee-a994ca9f422b)

## Expected result:

![Screenshot 13](https://github.com/brave/brave-browser/assets/40611140/066614d5-5442-4220-85f2-cf8231c87501)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.61.67 Chromium: 119.0.6045.105 (Official Build) beta (64-bit)
-- | --
Revision | `09cc687dc27ccd8acafeebf5af1dc620b4d9cb22`
OS | Windows 11 Version 22H2 (Build 22621.2506)

- Verified steps from [brave/brave-core#20657](https://github.com/brave/brave-core/pull/20657)
- Verified Wallet menu is shown correctly when the window size is quite small
<img width=300 src=https://github.com/brave/brave-browser/assets/17010094/f8480348-bc87-44a4-a122-5530ed2cc3c7>


---------------------

**Verification passed on**

Brave | 1.60.81 Chromium: 118.0.5993.117 (Official Build) (64-bit)
-- | --
Revision | `09cc687dc27ccd8acafeebf5af1dc620b4d9cb22`
OS | Linux

- Verified steps from [brave/brave-core#20657](https://github.com/brave/brave-core/pull/20657)
- Verified Wallet menu is shown correctly when the window size is quite small
<img width=300 src=https://github.com/brave/brave-browser/assets/17010094/c0377d88-9041-4977-a241-642b41cff85a>


---------------------

**Verification passed on**

Brave | 1.60.81 Chromium: 118.0.5993.117 (Official Build) (arm64)
-- | --
Revision | `09cc687dc27ccd8acafeebf5af1dc620b4d9cb22`
OS | macOS Version 14.1 (Build 23B74)

- Verified steps from [brave/brave-core#20657](https://github.com/brave/brave-core/pull/20657)
- Verified Wallet menu is shown correctly when the window size is quite small
<img width=300 src=https://github.com/brave/brave-browser/assets/17010094/d72213ee-62a2-49d8-b979-df4d61e3843b>
