### ISSUE TITLE
Compatibility issue with https://jsperf.com/

### ISSUE THREAD

**Issue by maikelmclauflin** [brave/brave-browser#3388]
## Description 

unable to sign in / navigate through a couple of pages like `popular` (nav at bottom)

## Steps to Reproduce

   1. try to login using login button (backed by github)
   2. failure

## Expected result:
should be able to connect to github

## Reproduces how often: 

easily reproduced as long as it is not rate limited

## Brave version (brave://version info)

Version 0.61.22 Chromium: 72.0.3626.81 (Official Build) dev (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
currently reproducing on dev

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
yes - seems to
- Is the issue reproducible on the latest version of Chrome? 
no

**Comment by ryanbr** [comment]
@maikelmclauflin is this still an issue? just tested it, seems fine?

**Comment by bsclifton** [comment]
Verified this works as expected 👍 

Closing- please re-open if you still run into this 😄
