### ISSUE TITLE
The `glasses` thumbnail is not aligned properly in the URL search bar in `Private` tab

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#33882]
## Description 

The `glasses` thumbnail is not aligned properly in the URL search bar in the `Private` tab. This is a `C119` related issue. I checked the same with Nightly build `1.61.46` which has `C118`, and the issue is not there.

## Steps to reproduce 

   1. Launch Brave Nightly `1.61.47` which has `C119`
   2. Open a `Private` tab > Observe

## Actual result 

The `glasses` thumbnail is not aligned properly in the URL search bar in the `Private` tab.

<img width="569" alt="2023-10-24_11-24-56" src="https://github.com/brave/brave-browser/assets/128532965/e48fa9b4-522a-49d9-8c9f-c924b9243531">

## Expected result

The `glasses` thumbnail must be properly aligned in the URL search bar in the `Private` tab.

<img width="569" alt="2023-10-24_11-24-28" src="https://github.com/brave/brave-browser/assets/128532965/f1e6b5a4-a1a6-425e-b7c3-59c5fa503108">

## Issue reproduces how often 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NO
- Can you reproduce this issue with the current Play Store Beta version? NO
- Can you reproduce this issue with the current Play Store Nightly version? YES

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Pixel 7 (phone)
   - Android version: Android 14
   
## Brave version

```
Brave build: 1.61.47 
Chromium: 119.0.6045.33 (Official Build) canary (64-bit) 
Revision: 63aeef007c8d6fa051b21b4c8cdc9667fb16b389
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.60.105` or higher for `1.60.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 [panther_beta-user 14 U1B2.230922.010 release-keys]
Brave build: 1.60.106
Chromium: 119.0.6045.59 (Official Build) (64-bit) 
Revision: 16064193dde8c55f64dabd32f125c0cd9380f96a
```
---------------------------

**STEPS:**
1. Followed the steps from https://github.com/brave/brave-browser/issues/33882#issue-1959891352

**ACTUAL RESULTS:**
- Verified that the `glasses` thumbnail is properly aligned in the URL search bar in the `Private tab`.

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/ff8ecffa-3798-456a-9401-d022ca3da59c) | ![2](https://github.com/brave/brave-browser/assets/128532965/1a036a09-c986-427c-8f69-c087efcf58e2) |
