### ISSUE TITLE
Disable #power-bookmarks-side-panel

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#33886]
## Description 

Disable #power-bookmarks-side-panel with Chromium 119 update for now. This flag is still available but flag is no longer visible via brave://flags

Related flag is currently disabled: brave://flags/#power-bookmark-backend and also needs to be evaluated if this needs to be enabled as part of power-bookmarks-side-panel in the future.

We do want to switch to the power bookmarks side panel but need to understand dependency with the related flag and other feedback and improvements on the Chromium side as it's a more complex UX (power bookmarks UX was not adopted by Edge).

## Actual result:

<img width="347" alt="Screenshot 2023-10-24 at 12 40 50 PM" src="https://github.com/brave/brave-browser/assets/5951041/3f5c1d08-8290-457d-9243-37db6cfc2f98">

Brave | 1.61.48 Chromium: 119.0.6045.33 (Official Build) nightly (arm64)
-- | --
Revision | 50bf5d137a72ac7dc6c4e5b137a7d7fa492befd1
OS | macOS Version 14.1 (Build 23B73)
JavaScript | V8 11.9.169.4
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36

## Expected result:
<img width="342" alt="Screenshot 2023-10-24 at 12 41 44 PM" src="https://github.com/brave/brave-browser/assets/5951041/402b703f-a551-415a-b77b-e84fc8a976c7">

## Reproduces how often: 

Easily.

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? yes with CR 119

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? yes. Their new bookmarks side panel.

**Comment by kjozwiak** [comment]
https://github.com/brave/brave-browser/issues/32876

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.60.105 Chromium: 119.0.6045.59 (Official Build) (64-bit)
-- | --
Revision | a39727aa81373a09a915478fcb35826242c37335
OS | Windows 10 Version 22H2 (Build 19045.3570)

```
