### ISSUE TITLE
Support `:remove`/`:remove-attr`/`:remove-class` adblock filter syntax

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#33881]
Support for these action operators was added to adblock-rust as of `v0.8.0`, but they still need to be recognized and acted on by the cosmetic filtering content script.

The behavior of these operators is described [here](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#action-operators).

When calling `url_specific_resources` from the adblock engine, the returned payload will include the fields `remove_selectors`, `remove_attrs` and `remove_classes`. See [the adblock-rust docs](https://docs.rs/adblock/latest/adblock/cosmetic_filter_cache/struct.UrlSpecificResources.html) for more information on how they should be interpreted.

Since these fields involve removing nodes from the DOM rather than restyling them with CSS, it will be necessary to check for mutations that might affect the applicability of the rules over time. It's recommended to use a `MutationObserver` in the cosmetic filtering content script for this purpose.

Implementation should begin from [`CosmeticFiltersJSHandler::ApplyRules`](https://github.com/brave/brave-core/blob/master/components/cosmetic_filters/renderer/cosmetic_filters_js_handler.cc#L412C6-L412C42). The relevant fields are already present in `resources_dict_` - they need to be templated into `kScriptletInitScript` like other fields, and then handled in-page by logic in the [`content_cosmetic.ts`](https://github.com/brave/brave-core/blob/master/components/cosmetic_filters/resources/data/content_cosmetic.ts) content script.

We're targeting this for 1.68.x

**Comment by bcaller** [comment]
Is this at all handled by the code at https://github.com/brave/uBlock/blob/89aa0b2a1653087885601c49667a38bf4fa87880/src/js/contentscript-extra.js#L605-L632

**Comment by antonok-edm** [comment]
@bcaller yes, that's handling the same filters

**Comment by petemill** [comment]
Doesn't cosmetic filtering already have some kind of mutation observer? Is this just changing where we get the list of nodes to be removed from or do we need to add another node processing mechanism?

**Comment by bcaller** [comment]
https://github.com/brave/brave-core/pull/23702

**Comment by MadhaviSeelam** [comment]
Verification In progress using
```
Brave | 1.69.89 Chromium: 127.0.6533.26 (Official Build) nightly (64-bit)
-- | --
Revision | f446f85ae826780dfae5356eeec4480c0415670c
OS | Windows 11 Version 23H2 (Build 22631.3810)
```

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version: 

```
Brave	1.69.131 Chromium: 127.0.6533.88 (Official Build) beta (64-bit) 
Revision	7f9c5cb9840ea18f57d485ee263b5bf4b1075953
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

Preconditions:

- Add the following rules to the custom filters list in `Brave Shields & privacy` -> `Content Filtering` -> Create custom filters
- Press `Save Changes` and restart the browser

    ```
    brave.com###ls-banner:remove-class(hidden)
    brave.com##a:remove-attr(href)
    brave.com##svg:remove()
    brave.com##a#home-download-button-hero:remove()
    ```
<hr>

- [x] Ensured that Yes/Dismiss banner at the top of the brave.com page is visible
- [x] Ensured that none of the links on the page do anything. 
- [x] Ensured that `Get Brave` button is removed.
    
 Example | Example | Example
 -|-|-
<img width="1808" alt="Screenshot 2024-08-06 at 2 33 54 PM" src="https://github.com/user-attachments/assets/161f6beb-bc2e-4088-bb1c-db822673e868"> | <img width="560" alt="Screenshot 2024-08-06 at 2 35 35 PM" src="https://github.com/user-attachments/assets/6b11768e-6431-4bcb-9779-8cdba32b004d"> | <img width="560" alt="Screenshot 2024-08-06 at 2 36 39 PM" src="https://github.com/user-attachments/assets/985893f6-08eb-42e7-b3ff-ad7c62ccac17">
