### ISSUE TITLE
AI Chat: update model strings

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#33894]
Copy

Hi, I'm Leo. I'm proxied by Brave and powered by Claude Instant, a model created by Anthropic to power conversational and text processing tasks.

Hi, I'm Leo. I'm a fully hosted AI assistant by Brave. I’m  powered by Llama 13B, a model created by Meta to be performant and applicable to many use cases.

Hi, I'm Leo. I'm a fully hosted AI assistant by Brave.  I’m powered by Llama 70B, a model created by Meta to handle more advanced tasks than 13B.

Model selection menu
Claude: Conversation and text generation
Llama 13b: General purpose chat
Llama 70b: Advanced chat tasks

**Comment by kjozwiak** [comment]
The above requires `1.60.106` or higher for `1.60.x` verification 👍

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.60.106 Chromium: 119.0.6045.59 (Official Build) (64-bit)
-- | --
Revision | 16064193dde8c55f64dabd32f125c0cd9380f96a
OS | Windows 10 Version 22H2 (Build 19045.3636)
```

## `llama-2-13b-chat`

## `llama-2-70b-chat`

## `claude-instant-v1`

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using the following version(s):

```
Brave	1.60.106 Chromium: 119.0.6045.59 (Official Build) (64-bit) 
Revision	16064193dde8c55f64dabd32f125c0cd9380f96a
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

- Ensured introduction copy and model selection strings are correct based on https://github.com/brave/brave-browser/issues/33894#issue-1960273897

**_Llama-2-13b-chat_**

Copy | Model Selection
-|-
![Screenshot 2023-10-30 at 12 16 50 PM](https://github.com/brave/brave-browser/assets/17885425/e60311a7-9131-483d-baa5-afd7170cefa3) | ![Screenshot 2023-10-30 at 11 57 59 AM](https://github.com/brave/brave-browser/assets/17885425/fb16d9d5-ae30-4b42-945e-4b0b318d70f8)


**_Llama-2-70b-chat_**

Copy | Model Selection
-|-
![Screenshot 2023-10-30 at 12 16 57 PM](https://github.com/brave/brave-browser/assets/17885425/b1681f84-8a29-4d8a-8d14-ce71b041006b) | ![Screenshot 2023-10-30 at 12 34 11 PM](https://github.com/brave/brave-browser/assets/17885425/0a928c43-c53e-4610-8f06-a13ed5255508)


**_Claude-instant-v1_**
Copy | Model Selection
-|-
![Screenshot 2023-10-30 at 12 17 56 PM](https://github.com/brave/brave-browser/assets/17885425/18c11918-2196-4ca7-acad-ae55452b73b6) | ![Screenshot 2023-10-30 at 12 34 17 PM](https://github.com/brave/brave-browser/assets/17885425/34022d74-234a-4ed2-be0d-f43971b89b93)
