### ISSUE TITLE
AI Chat: Model Intro is showing pre opt-in

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#33895]
This should not show on opt-in view:

![Image](https://github.com/brave/brave-browser/assets/741836/65c5444d-c99e-4c56-b051-e926c7327fd5)

**Comment by kjozwiak** [comment]
The above requires `1.60.106` or higher for `1.60.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.60.106 Chromium: 119.0.6045.59 (Official Build) (64-bit)
-- | --
Revision | 16064193dde8c55f64dabd32f125c0cd9380f96a
OS | Windows 10 Version 22H2 (Build 19045.3636)
```

### Followed the provided steps to reproduce

## Confirmed no more model-intro text in the opt-in dialog

`Dark` | `Light`
----------|----------
![image](https://github.com/brave/brave-browser/assets/387249/08fe83fa-fb1c-4116-b307-21b1b6af77a9) | ![image](https://github.com/brave/brave-browser/assets/387249/629b3eb3-828d-4561-b786-70b2d8fd5627)

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using the following version(s):

```
Brave	1.60.106 Chromium: 119.0.6045.59 (Official Build) (64-bit) 
Revision	16064193dde8c55f64dabd32f125c0cd9380f96a
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

- Ensured the opt in view does not show the chat copy

Light | Dark
-|-
![Screenshot 2023-10-30 at 1 16 53 PM](https://github.com/brave/brave-browser/assets/17885425/d58c8a4c-aafc-4b1e-9624-8a004a1388b4) | ![Screenshot 2023-10-30 at 1 20 22 PM](https://github.com/brave/brave-browser/assets/17885425/9a9e49a1-ca90-4748-a614-060ca731abfb)
