### ISSUE TITLE
AI Chat: Only allow premium features if premium authenticated

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#33891]
When the user is not premium authenticated, there should be:
- No premium tag on the side panel title
- A premium prompt when switching to a premium model
- No allowed usage of premium models

**Comment by petemill** [comment]
Fixed by https://github.com/brave/brave-core/pull/20480 (which was merged to https://github.com/brave/brave-core/pull/20245, and then master)

**Comment by kjozwiak** [comment]
@brave/qa-team using the information from https://github.com/brave/brave-browser/issues/33891#issue-1960055562, basically created the following cases via https://github.com/brave/brave-core/pull/20480#issuecomment-1778486819. @petemill let us know if we should check anything else within this issue as there's not much information in terms of cases.

**Comment by petemill** [comment]
@kjozwiak I suppose the inverse of all those should be tested. I think I left them out since they were verified in their original PRs, but we didn't verify as part of https://github.com/brave/brave-core/pull/20480 that they show up again once user is subscribed to premium, so:

When the user **is** premium authenticated, there should be:

A premium tag on the side panel title
No premium prompt when switching to a premium model
Allowed usage of premium models

**Comment by kjozwiak** [comment]
The above requires `1.60.105` or higher for `1.60.x` verification 👍

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.60.106 Chromium: 119.0.6045.59 (Official Build) (64-bit)
-- | --
Revision | 16064193dde8c55f64dabd32f125c0cd9380f96a
OS | Windows 10 Version 22H2 (Build 19045.3636)
```

## Default, non-Premium
<details>

</details>


## Premium-enabled
<details>

</details>

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version:

```
Brave	1.60.109 Chromium: 119.0.6045.59 (Official Build) (64-bit) 
Revision	fc399c7c433510eb03c2b35281bf8935804b99de
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

- Ensured that premium tag is not shown if user is not premium authenticated
- Ensured that premium prompt is shown when switching to a premium model
- Ensured that user cannot use the premium models and they are shown as locked in selection panel

Chat window | Model Selection | NTP | NTP | Website (Claude) | Website (Claude)
-|-|-|-|-|-
![Screenshot 2023-10-31 at 3 29 39 PM](https://github.com/brave/brave-browser/assets/17885425/dedd5379-5d23-4081-9ae5-550e7e1342f7) | ![Screenshot 2023-10-31 at 3 29 58 PM](https://github.com/brave/brave-browser/assets/17885425/86b1cc57-41d1-4f94-a03b-a26e17781b0d) | ![Screenshot 2023-10-31 at 3 30 24 PM](https://github.com/brave/brave-browser/assets/17885425/27a09c3e-6c99-4e13-ad08-2b9e15614d02) | ![Screenshot 2023-10-31 at 3 30 31 PM](https://github.com/brave/brave-browser/assets/17885425/4e5dd279-4acf-42bd-8520-5e62cac89d3f) | ![Screenshot 2023-10-31 at 3 36 13 PM](https://github.com/brave/brave-browser/assets/17885425/aff82169-86eb-4af8-bc6f-53a4cc2660fd) | ![Screenshot 2023-10-31 at 3 36 17 PM](https://github.com/brave/brave-browser/assets/17885425/467aea78-9f57-46b3-bb03-09b6babd974b)
