### ISSUE TITLE
unable to import Brave Payments data from muon

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#3390]
## Description 
Importing Brave Payments data from muon to b-c doesn't work.

## Steps to Reproduce

   1. Have a muon profile on 0.25.x set up with Brave Payments enabled. Have a wallet with balance, and some pinned sites which should convert to recurring tips.
   2. Open 0.60.28 with a fresh profile. (no need to enable rewards)
   3. Import data from muon (you only need to select Payments data)

## Actual result:
UI says import completed, but Payments data (wallet and pinned sites) did not import.

I saw this in the terminal 
```
[78588:775:0215/175053.310957:ERROR:brave_profile_writer.cc(221)] An error occurred while trying to create a wallet to restore into (error_code=12)
```

## Expected result:
Brave Payments data should import successfully.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.60.28 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Mac OS X

### Reproducible on current release: no, works on 0.59.35
- Does it reproduce on brave-browser dev/beta builds? reproduced on Beta

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
cc @brave/legacy_qa @NejcZdovc @rebron @mandar-brave

**Comment by kjozwiak** [comment]
@rebron @bbondy @bsclifton as mentioned on Slack, I think we should uplift this into `0.60.x` as it might hurt retention for `muon` - `b-c` users.

**Comment by GeetaSarvadnya** [comment]
Reproducible on Windows 10 x64


Brave | 0.60.34 Chromium: 72.0.3626.109 (Official Build) beta (64-bit)
-- | --
Revision | fae8db7ab9280fa6704a59980263c804f809ebd5-refs/branch-heads/3626@{#857}
OS | Windows

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.60.40 Chromium: 72.0.3626.109 (Official Build) (64-bit)
-- | --
Revision | fae8db7ab9280fa6704a59980263c804f809ebd5-refs/branch-heads/3626@{#857}
OS | Windows 7

Used STR from the description.
Wallet and pinned tabs were imported successfully.
