### ISSUE TITLE
Remove Fuse.js dependency

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#33908]
## Description 

Related to: https://github.com/brave/brave-browser/issues/22139

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.62.130 Chromium: 120.0.6099.199 (Official Build) beta (64-bit)
-- | --
Revision | `6d589c6dc0f3489830d40332c82cdd5597e41c88`
OS | Windows 11 Version 23H2 (Build 22631.2861)

- Verified steps from [brave/brave-core#20677](https://github.com/brave/brave-core/pull/20677)
- Verified search functionality works as expected on Market tab and Fund wallet tab

---------------------

**Verification passed on**

Brave | 1.62.130 Chromium: 120.0.6099.199 (Official Build) beta (64-bit)
-- | --
Revision | `6d589c6dc0f3489830d40332c82cdd5597e41c88`
OS | Linux

- Verified steps from [brave/brave-core#20677](https://github.com/brave/brave-core/pull/20677)
- Verified search functionality works as expected on Market tab and Fund wallet tab

---------------------

**Verification passed on**

Brave | 1.62.130 Chromium: 120.0.6099.199 (Official Build) beta (arm64)
-- | --
Revision | `6d589c6dc0f3489830d40332c82cdd5597e41c88`
OS | macOS Version 14.2.1 (Build 23C71)

- Verified steps from [brave/brave-core#20677](https://github.com/brave/brave-core/pull/20677)
- Verified search functionality works as expected on Market tab and Fund wallet tab
