### ISSUE TITLE
Reports of user being unable to login to Coinbase

### ISSUE THREAD

**Issue by lukemulks** [brave/brave-browser#3391]
## Description 

Community member reports being unable to login to Coinbase.com with 2FA 

Original thread: https://www.reddit.com/r/BATProject/comments/ar0spb/unable_to_log_onto_coinbase_with_brave/

> I've been trying to log into coinbase using Brave but am unable to do so. I do have the correct login credentials, but am continually put in an endless loop of returning to the log in screen. Other browsers (Firefox) work without issue. I've tried disabling the shields specifically for coinbase but still no success. Does anyone know how to get this to work?

> I do have 2FA enabled, so I don’t know if that has something to do with it

> I am immediately redirected to the main login page and not prompted to putting in a 6 digit code

> Version 0.59.35 Chromium: 72.0.3626.81 (Official Build) (64-bit)

## Steps to Reproduce

   1.  Spin up the version above 
   2.  Enable 2FA on Coinbase.com account in chrome
   3.  Attempt to login to same acct in Brave  

## Actual result:

Spinning loop (from reporter) 

## Expected result:
login to coinbase

## Brave version (brave://version info)

> Version 0.59.35 Chromium: 72.0.3626.81 (Official Build) (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by lukemulks** [comment]
Note: I also observed this on Twitter: 
https://twitter.com/Joe58011983/status/1095761105836797952

I attempted to repro from win10 x64, but was unable to. 

I dismissed the report at the time as someone mentioning a block count vs. real inaccessibility, but am now wondering if this user on twitter potentially had 2FA enabled and encountered the same issue. 

Will ask the user on twitter for more info.

**Comment by Brave-Matt** [comment]
+1 from Community as well
https://community.brave.com/t/unable-to-login-to-coinbase/45201/4

**Comment by mrzealot** [comment]
Wasn't able to repro either from win10 x64, 2FA worked fine.

**Comment by dalecooper** [comment]
I know that's an old problem, but since the issue is not closed I thought I'd report that I've been experiencing the exact same "login page loop" problem for 3 days now, with no error message. All went well before that.

2FA is enabled but I'm not going past the login page anyway.
Disabling the shield doesn't help, but It works OK with a private session.

I'm running Brave 0.69.135 on Ubuntu 19.04

**Comment by ryanbr** [comment]
retested this, seems fine now
