### ISSUE TITLE
Account Blockie Squished in Send Panel

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#33912]
## Description 

The account `Blockie` is squished when selecting an account to send to in the Wallet `Panel`

## Steps to Reproduce

   1. Open the Wallet `Panel` and navigate to the `Send` screen
   2. Select a token to send and enter an amount.
   3. Click on the `Dropdown` to select an account to send to
   4. Notice the account `Blockie` is squished

## Actual result:

![Screenshot 22](https://github.com/brave/brave-browser/assets/40611140/8eb5a651-601d-4b09-af17-fd91748e7b4d)

## Expected result:
Should not be squished

![Screenshot 23](https://github.com/brave/brave-browser/assets/40611140/f2f3a97e-b54b-44d3-ab4a-1479a38ef206)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.60.105` or higher for `1.60.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.60.105 Chromium: 119.0.6045.59 (Official Build) (64-bit)
-- | --
Revision | a39727aa81373a09a915478fcb35826242c37335
OS | Windows 11 Version 22H2 (Build 22621.2428)

- Verified steps from [rave/brave-core#20682](https://github.com/brave/brave-core/pull/20682)
- Verified account blockie is shown properly in account selection dropdown on Send screen
- Encountered [#33961](https://github.com/brave/brave-browser/issues/33961)

https://github.com/brave/brave-browser/assets/17010094/6bf55608-fea9-480e-ae64-11bf169ca3d9
