### ISSUE TITLE
Two errors/warnings when trying to summarize a huge plain-text article

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#33923]
## Description 

Two errors/warnings when trying to summarize a huge plain-text article

## Steps to Reproduce

1. install
2. launch
3. enable `Leo` in `brave://flags`
4. click `Restart`
5. click on `Leo` in the sidebar
6. click on `Accept and begin`
7. load `https://www.govinfo.gov/content/pkg/CDOC-110hdoc50/html/CDOC-110hdoc50.htm`
8. click on `Summarize this page`

## Actual result:

![image (2)](https://github.com/brave/brave-browser/assets/387249/6a48e49a-a8d3-4a11-a25e-e90ae3be71ce)

## Expected result:

Just one error message/condition

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave | 1.61.51 Chromium: 119.0.6045.33 (Official Build) nightly (64-bit)
-- | --
Revision | aa3f8a13e51b43e6a9110371d923d87c95342164
OS | Windows 10 Version 22H2 (Build 19045.3570)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @bbondy @petemill @mattmcalister @nullhook @brave/qa-team

**Comment by stephendonner** [comment]
(In this state, clicking `Got it` just results in that warning message dismissing, but no additional content/answer rendered.)

![image (1)](https://github.com/brave/brave-browser/assets/387249/0db096cb-8f12-4978-a55d-ee6f64e3e172)

**Comment by kjozwiak** [comment]
The above requires `1.60.106` or higher for `1.60.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.60.106 Chromium: 119.0.6045.59 (Official Build) (64-bit)
-- | --
Revision | 16064193dde8c55f64dabd32f125c0cd9380f96a
OS | Windows 10 Version 22H2 (Build 19045.3636)
```

### Followed my original steps to reproduce

## Confirmed I got the `This page is too long for Leo` warning, but not the `This conversation is too long for Leo` error

example | example | example
----------|----------|----------
![image](https://github.com/brave/brave-browser/assets/387249/fa0b193a-1250-4a9f-91fa-9ef772cea80a) | ![image](https://github.com/brave/brave-browser/assets/387249/41b1470c-1e65-4580-8dbd-013a81e36af4) | ![image](https://github.com/brave/brave-browser/assets/387249/e21bbf3f-5796-401d-b582-67c2f5c060fc)
