### ISSUE TITLE
Can't compose new messages on Twitter using Brave dev version 0.61.22

### ISSUE THREAD

**Issue by anarchitectures** [brave/brave-browser#3392]
Recently, typed characters stopped appearing in the compose new message box on Twitter. I turned off all my extensions and the issue persisted. I was only able to solve the problem by logging into my account on Chrome. I didn't find any other users reporting a similar case, so I don't believe it has to do with Twitter itself. As the issue started around the time of my last update, and I can't locate any other cause, I now suspect this is due to one of the recent nightly dev builds. Hope this is sufficiently self-explanatory.

I'm on Ubuntu 18.x LTS and running Brave dev version 0.61.22.

**Comment by anarchitectures** [comment]
This issue has disappeared since my latest update to Brave dev version 0.62.5. I'd considered it closed.

**Comment by bsclifton** [comment]
@anarchitectures great- thanks for the update! 😄
