### ISSUE TITLE
`Go Premium` callout link should reflect Premium-enabled status

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#33920]
## Description 

`Go Premium` callout link should reflect Premium-enabled status

## Actual result:

`Go Premium`

![image](https://github.com/brave/brave-browser/assets/387249/70d23a4a-6c4c-4fe9-bf93-e1248f84adfd)

## Expected result:

The menu-item text should be context-sensitive, and reflect that the user is already Premium-enabled

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave | 1.61.51 Chromium: 119.0.6045.33 (Official Build) nightly (64-bit)
-- | --
Revision | aa3f8a13e51b43e6a9110371d923d87c95342164
OS | Windows 10 Version 22H2 (Build 19045.3570)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @bbondy @mattmcalister @petemill @nullhook @rebron  @brave/qa-team

**Comment by kjozwiak** [comment]
The above requires `1.60.110` or higher for `1.60.x` verification 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.60.110 Chromium: 119.0.6045.105 (Official Build) (64-bit)
-- | --
Revision | 0bb6e7a81aed340b5a9e8b752c1cf92768257c40
OS | Windows 11 Version 22H2 (Build 22621.2506)
```

* ensured that users without accounts are seeing `Go Premium` via the `hamburger menu`
* ensured that users with accounts that don't have `Leo` premium are seeing `Go Premium` via the `hamburger menu`
* ensured that users with `Leo` premium are seeing `Manage subscription` via the `hamburger menu`
* ensured that clicking on `Manage subscription` opens `https://account.brave.com/account/`

**`No Account`** | **`Account without premium`** | **`Account with Leo premium`**
-------------------|------------------------------------|---------------------------------------
![image](https://github.com/brave/brave-browser/assets/2602313/abf73900-faab-4b41-bd26-2eb5a9485593) | ![image](https://github.com/brave/brave-browser/assets/2602313/358c4146-6be1-4787-bd69-d4704e9d175f) | ![image](https://github.com/brave/brave-browser/assets/2602313/453f915d-f17b-4db6-bf66-3a6cd1f27b75)
