### ISSUE TITLE
Anti-fingerprinting breaks video playback on NSFW site avgle.com

### ISSUE THREAD

**Issue by Yuki2718** [brave/brave-browser#33937]
## Description 
Anti-fingerprinting breaks video playback on the site.

## Steps to Reproduce

   1. Visit [NSFW] `https://avgle.com/video/_eORNRPA8Rm/%E7%B4%A0%E6%99%B4%E3%82%89%E3%81%97%E3%81%84%E8%8B%A5%E3%81%84%E5%A5%B3%E3%81%AE%E5%AD%90%E3%81%8C%E5%88%BA%E6%BF%80%E3%81%95%E3%82%8C%E3%81%BE%E3%81%99` (any video is okay)
   2. click the play button
   3. video won't play

## Actual result:

Video doesn't play

## Expected result:

Video plays fine

## Reproduces how often: 

Always as long as anti-fingerprinting is turned on regardless of the mode

## Desktop Brave version:

1.59.124

## Android Device details:
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: Android 13

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by ryanbr** [comment]
avgle.com Host Error CF Error @Yuki2718

**Comment by Yuki2718** [comment]
Yeah, confirmed but I'll watch a few weeks.

**Comment by Yuki2718** [comment]
Now removed https://github.com/AdguardTeam/AdguardFilters/commit/6405b7c14a131a5333c5d59d373372019b70b821
