### ISSUE TITLE
Weird border in Vertical tabs strip with `padding and shadow to main content window`

### ISSUE THREAD

**Issue by Emi-HoloGhostRevisionist88** [brave/brave-browser#33932]
## Description 

When you use collapsed VT and switch from Horizontal to Vertical mode, there is a misaligned border in the collapsed tabs strip, then if you use mouseover mode to expand and collapse, the border will stay in expanded VT.

If you click the Expand Tabs button to the border disappears and looks correctly, like sidebar.

If you collapse the tabs, the misaligned border doesn't appear anymore as well, so it is only when you switch the first time.

Also in Private mode the border looks even worst because it is too bright and like white, but in normal windows you can barely see it.

## Actual result:

![image](https://github.com/brave/brave-browser/assets/147446611/ee7d9eb8-db65-40fa-880b-012a6fd319b8)

https://github.com/brave/brave-browser/assets/147446611/0f70ad10-efbd-43bb-a06e-48baef7fd9be

https://github.com/brave/brave-browser/assets/147446611/031adaf3-167e-49f0-b608-5b40e4f5ab1a

## Brave version (brave://version info)

1.61.52 Chromium: 119.0.6045.33 (Official Build) nightly (64-bit) Windows 11 2H22****

**Comment by Emi-HoloGhostRevisionist88** [comment]
Well, the border was always there before `padding and shadow to main content window`, but now the border looks out of place.
Seems like it was a specific VT animation/transition when switching modes that was added and now it doesn't fit the whole design, now it is gone when collapsed and fully expanded mode tabs are used.

I mean, VT without it look better anyway and with the rounded corners and all.

**Comment by Emi-HoloGhostRevisionist88** [comment]
@sangwoo108 I better tag you so you notice this.

**Comment by sangwoo108** [comment]
Thanks @Emi-HoloGhostRevisionist88 ! I think @zenparsing would know better about the new padding policy

**Comment by zenparsing** [comment]
I noticed this before, and as @Emi-HoloGhostRevisionist88 it's an issue without the padding flag as well. If I recall correctly, it's not a border, but rather a 1px region that isn't getting painted correctly. I'll try to dig in a bit today.

**Comment by zenparsing** [comment]
@sangwoo108  Here's a screenshot of the artifact on a Windows dev build, with both the padding flag and the updated horizontal tabs flag disabled:

![vtabs-border](https://github.com/brave/brave-browser/assets/5995084/6617ef70-4c4e-41a0-a61a-e244f3d43caf)

`VerticalTabStripRegionView` has been given a blue background with a red right border. Somehow, the white line is rendered within the bounds of the view but outside of the border. I haven't been able to pin down why those pixels aren't getting painted correctly.

**Comment by Emi-HoloGhostRevisionist88** [comment]
Also, since I don't know who this belongs to, I better post it here so you take more feedback about the padding/rounded corners and the vertical tabs and fix it eventually if necessary.

But when you use mouseover mode, the vertical tab strip will not adopt the rounded corners, so it looks weird, especially if you hit the Expand tabs button, and then the corners and the padding appear. For comparison, sidebar doesn't show this either.

![image](https://github.com/brave/brave-browser/assets/147446611/882b3672-efd6-4a58-b7ea-2408b63d63af)

![image](https://github.com/brave/brave-browser/assets/147446611/be764edf-9e45-4c28-8b68-431a7edb17df)

**Comment by sangwoo108** [comment]
Sorry for getting back late. I've checked again and found

* The border is actually not misaligned. The gray right side of border is not part of vertical tab strip. It's a empty padding area for web contents.

* Why does the the border appear on mouse hover and disappear on expanding/collapsing? - it's what intended. We seem to want seamlessness between UI components but we draws the border only when vertical tab strip overlays the web view area.

* **BUT** when switching tab strip orientation, the border shows up, and this is a bug. I'm going to fix it.
