### ISSUE TITLE
Menu bar disabled, but it appears anyways and vanished after ~20 seconds

### ISSUE THREAD

**Issue by LunarCultist** [brave/brave-browser#3394]
## Description 
I dont like menu bars, so i disabled it in the preferrences. Anyways it appears when starting brave. After about 20 seconds it disappears.

## Steps to Reproduce
   1. Go to preferences and disable the menu bar 
   2. Close the brave browser
   3. Open the brave browser and look at the menu bar and wait 20-30 seconds

## Actual result:
After waiting this time the menu bar doesnt appear before restarting the browser again.

## Expected result:
The menu bar should be turned off permanently.

## Reproduces how often: 
Always after starting the brave browser.

## Brave version (brave://version info)
 
Brave: 0.23.105 
V8: 6.8.275.24 
rev: 0.23.105dev 
Muon: 8.0.9 
OS Release: 4.19.21-1-lts 
Update Channel: Veröffentlichung 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.84

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields?   No
- Is the issue reproducible on the latest version of Chrome?   No

**Comment by srirambv** [comment]
You are currently running an outdated browser which is not supported anymore. Please follow the [link ](https://brave-browser.readthedocs.io/en/latest/installing-brave.html#release-channel-installation) to install the current supported version
