### ISSUE TITLE
New AI Chat opt-in experience

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#33942]

**Comment by petemill** [comment]
@aguscruiz can you provide figma link please? I can't seem to find it anymore.

**Comment by aguscruiz** [comment]
Figma link here:
https://www.figma.com/file/m0Gdbf0wtqyfEFGm32VLLc/Leo?type=design&node-id=15-11967&mode=design

**Comment by kjozwiak** [comment]
The above requires `1.62.101` or higher for `1.62.x` verification 👍

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.62.105 Chromium: 120.0.6099.71 (Official Build) beta (64-bit)
-- | --
Revision | f72c783bcd52110d026061575b4bef28ccb547f7
OS | Windows 10 Version 22H2 (Build 19045.3758)
```

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.62.121`

**Comment by kjozwiak** [comment]
Removing the above from https://github.com/brave/brave-browser/issues/35625 as `Leo` is targeting `1.63.x` for `Android`.
