### ISSUE TITLE
AI Chat premium models should more obviously not appear locked for premium users

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#33944]
![Image](https://github.com/brave/brave-browser/assets/741836/425acada-ac64-4884-8b95-147f6fc3f4f6)

**Comment by kjozwiak** [comment]
The above requires `1.60.109` or higher for `1.60.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.60.109 Chromium: 119.0.6045.59 (Official Build) (64-bit)
-- | --
Revision | fc399c7c433510eb03c2b35281bf8935804b99de
OS | Windows 10 Version 22H2 (Build 19045.3570)
```
### Confirmed gray icons by default, with green icons once `Premium`-enabled

non-`Premium` - dark-gray icons | `Premium` - green lock icons
----------|----------
![image](https://github.com/brave/brave-browser/assets/38657976/14069370-4958-4d4d-84f1-8d7092d9869b) | ![image](https://github.com/brave/brave-browser/assets/38657976/1b2e7ffe-3fe5-4b1d-8f95-6bd726f15418) |

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version:

```
Brave	1.60.109 Chromium: 119.0.6045.59 (Official Build) (64-bit) 
Revision	fc399c7c433510eb03c2b35281bf8935804b99de
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
- Verified gray locked icons by default and green unlocked icons for premium users.

Example | Example
-|-
![Screenshot 2023-10-30 at 12 34 11 PM](https://github.com/brave/brave-browser/assets/17885425/8bd981a3-3531-4fc7-aa94-cb6664cb1a9b) | ![Screenshot 2023-10-31 at 4 20 50 PM](https://github.com/brave/brave-browser/assets/17885425/cb134f07-fb55-4db2-a6f3-f2b09aa8c0be)
