### ISSUE TITLE
AI Chat: 24hrs premium prompt instantly disappearing when opening Leo in a new conversation where there's activity

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-browser#33946]
## Description 

Follow up to the work done via https://github.com/brave/brave-browser/issues/33602 where the premium prompt should appear after ~24hrs. When `Leo` is opened in `brave://newtab`, the premium prompt appears without any issues. However, if you open a new website and then open `Leo`, you'll see the prompt for ~1-2ms before it disappears. Assuming the prompt should persist until the user clicks on `Dismiss`.

## Steps to Reproduce

   1. install `1.62.2 Chromium: 119.0.6045.33`
   2. once installed, open `Leo` and accept the `T&S`
   3. close the browser and move the time ahead ~24hrs
   4. re-open the browser and open a brand tab/website (used `brave.com` in this instant
   5. click on `Leo` and you'll see the premium prompt basically "blink" (appears/disappears instantly)

## Actual result:

https://github.com/brave/brave-browser/assets/2602313/c6daf4ba-1894-4158-82a6-f01dd5fd914c

## Expected result:

The `Premium` prompt should be visible/persistent till the user clicks on `Dismiss`

## Reproduces how often: 

100% reproducible using the STR/Cases outlined above.

## Brave version (brave://version info)

```
Brave | 1.62.2 Chromium: 119.0.6045.33 (Official Build) nightly (64-bit)
-- | --
Revision | 1ae4cbaeb4186df008e4562ed006f2c70a9beea8
OS | Windows 11 Version 22H2 (Build 22621.2428)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? `N/A`
- Does the issue resolve itself when disabling Brave Rewards? `N/A`
- Is the issue reproducible on the latest version of Chrome? `N/A`

**Comment by petemill** [comment]
This didn't actually get fixed

**Comment by kjozwiak** [comment]
Labelling as `QA/No` in favour of https://github.com/brave/brave-browser/issues/34155. The attempted fix via https://github.com/brave/brave-core/pull/20780 basically created the above where it now disappears after ~15s.
