### ISSUE TITLE
Remove Impact.com's irclickid from query string

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#33952]
Impact.com uses the `irclickid` query string parameter to [track a _consumer journey_](https://integrations.impact.com/impact-brand/docs/api-integration-implementation#capture--store-clickid) meaning that it is at the granularity of a single person. It does not appear to be linked to someone's identity and instead seems to be randomly generated, but it is meant to be used as a stable identifier to recognize a single user across different pages.

Sample URL:
```
$ curl --head -L https://effortlessgent.com/spier-and-mackay-donegal-coat/
HTTP/2 302 
date: Thu, 26 Oct 2023 18:03:08 GMT
content-type: text/html; charset=UTF-8
location: https://imp.i317572.net/PykDke

HTTP/2 301 
date: Thu, 26 Oct 2023 18:03:08 GMT
content-length: 0
location: https://www.spierandmackay.com/product/brown-donegal-overcoat--c3282-8011-sboc-fw22?irclickid=QQD2zbykJxyPTmGz47wiYyUCUkFQ2fRt028z140&irgwc=1

HTTP/2 200 
server: nginx
date: Thu, 26 Oct 2023 18:03:09 GMT
content-type: text/html; charset=UTF-8
```

**Comment by fmarier** [comment]
Other impact.com parameters are removed by the "copy clean link" feature: https://github.com/brave/adblock-lists/pull/1377

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.62.29 Chromium: 119.0.6045.105 (Official Build) nightly (x86_64)
-- | --
Revision | 722db0323f23c1aaee8a62326083bced61909279
OS | macOS Version 14.2 (Build 23C5030f)
```

### Steps:
1. installed `1.62.29`
2. launched Brave
3. loaded `https://brave.com/?foo=bar&irclickid=1234&ymclid=abcd&ysclid=efgh&fb_action_ids=5678&fb_comment_id=123456&clean=yes` with the `Developer Tools`' console open

### Confirmed entering and trying to load https://brave.com/?foo=bar&irclickid=1234&ymclid=abcd&ysclid=efgh&fb_action_ids=5678&fb_comment_id=123456&clean=yes resulted in only `https://brave.com/?foo=bar&clean=yes` being loaded

<img width="1897" alt="Screenshot 2023-11-06 at 3 22 59 PM" src="https://github.com/brave/brave-browser/assets/387249/8092c110-3baf-43f3-85db-9acd8cdfb204">

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.62.116`

- When `https://brave.com/?foo=bar&irclickid=1234&ymclid=abcd&ysclid=efgh&fb_action_ids=5678&fb_comment_id=123456&clean=yes` is loaded in the URL bar only `https://brave.com/?foo=bar&clean=yes` is loaded in the URL bar

![image](https://github.com/brave/brave-browser/assets/38657976/dd128a07-8aeb-402b-8e14-90a00e8e4000)
