### ISSUE TITLE
Update generic linking error text

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#33955]
## Current

![image](https://github.com/brave/brave-browser/assets/11497541/5ba298ad-9074-4075-bd19-d91494a581bc)

## New text

**Something went wrong**

We weren’t able to complete your request. Please try again, and [contact support](https://community.brave.com) if the problem persists. (Error code: `{{HTTP_STATUS_CODE}}`) 

(Close)

**Comment by Miyayes** [comment]
@emerick Is it possible to put the HTTP status code here? It'll give us some sense of what the issue is without having to collect full logs.

**Comment by emerick** [comment]
Should be doable, we just have to make sure to pass it through.

**Comment by mkarolin** [comment]
If I am looking at the code correctly, in order to get the http status code into the UI, we'd have to save it during post-connect, which happens in the engine, then pass it into rewards service with the connection result via mojom interface. That seems like quite a few changes. How badly do we need it in the UI, @Miyayes 😄 cc: @zenparsing: is there an easier way?

**Comment by Miyayes** [comment]
@mkarolin Sounds like it's too heavy. Unless there's a simple lightweight solution, let's just pare this down and do the text change and we can defer the status code part.

**Comment by zenparsing** [comment]
@mkarolin Sorry, didn't see your question before. I think it would be great to provide more context, but as you say it's complicated.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.64.90 Chromium: 122.0.6261.94 (Official Build) beta (x86_64)
-- | --
Revision | 726c6970a1e9c057c69d80e03ad95a7c561fbfe7
OS | macOS Version 13.6.4 (Build 22G513)
```

**Comment by Uni-verse** [comment]
In Progress on `Samsung Galaxy S21` using version: 

```
Brave	1.64.95 Chromium: 122.0.6261.94 (Official Build) beta (64-bit) 
Revision	6f4193fbcee7c358ae3684f777faa9f12e52206e
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
