### ISSUE TITLE
Webview crash when selecting token on deposit & buy screens

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#33966]
## Description 
Webview crash when selecting token on deposit screen

## Steps to reproduce 

   1. Restore/Create a new wallet
   2. Open Wallet and click on B/S/S/D button
   3. Click on Deposit to load the full screen deposit screen
   4. Select a token and click continue, webview crashes

## Actual result 

https://github.com/brave/brave-browser/assets/17010094/09cedc53-cd71-4468-acf7-0e04d08386a3

## Expected result
No webview crash

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 13
   
## Brave version
1.60.105

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @simoarpe

**Comment by srirambv** [comment]
This also happens on Buy screen

**Comment by simoarpe** [comment]
Thank you @srirambv ! Yes, I noticed. I'm working on a fix right now.

**Comment by kjozwiak** [comment]
The above requires `1.60.110` or higher for `1.60.x` verifications 👍

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.60.110 x64 build
- Verified steps from issue description
- Verified no webview crash when selecting token on deposit/buy screen
- Encountered [#34016](https://github.com/brave/brave-browser/issues/34016) & [#34054](https://github.com/brave/brave-browser/issues/34054)

https://github.com/brave/brave-browser/assets/17010094/9ff836b3-ed41-4c11-9e35-e4487cce50f7
