### ISSUE TITLE
SkuService does not check SkuResult in OnFetchOrderCredentials

### ISSUE THREAD

**Issue by nvonpentz** [brave/brave-browser#33973]
[Slack thread](https://bravesoftware.slack.com/archives/C021S0FN3V1/p1698375852842269)

https://github.com/brave/brave-core/blob/86bd12d157a9df38ba6b6cbdc8663106c7d2bcbf/components/skus/browser/skus_service_impl.cc#L31C6-L37

It should probably be passing the error back through the callback, then have JS api throw an exception.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.63.93 Chromium: 120.0.6099.199 (Official Build) nightly (64-bit)
-- | --
Revision | fe53852f13fee65ed436c65f07e7e1c00bf8d8e1
OS | Windows 11 Version 22H2 (Build 22621.2861)
```

1. Installed 1.63.93
2. launched Brave
3. logged into account.bravesoftware.com
4. purchased the subscription for Leo Premium and loaded credentials
5. opened console on subscription page
6. called following in the console
     -`await window.chrome.braveSkus.fetch_order_credentials(' ')`

Confirmed error shown as expected https://github.com/brave/brave-core/pull/20800#issue-1972788683

<img width="961" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/bff181b6-01b3-452c-88ed-14cc13e986e2">

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 


```
Brave | 1.63.104 Chromium: 120.0.6099.199 (Official Build) nightly (x86_64)
-- | --
Revision | 5b979a47b2ed5418e6c3a10d911bef8ec77b16bd
OS | macOS Version 11.7.10 (Build 20G1427)
```

**Comment by stephendonner** [comment]
Temporarily `QA/Blocked` from further verifications by the above https://github.com/brave/brave-browser/issues/35208.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.63.126 Chromium: 121.0.6167.57 (Official Build) beta (x86_64)
-- | --
Revision | 37cf1e839670a842970254b61cdd4ef63307c8f1
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.63.126`
2. launched Brave using `--env-leo=staging --env-ai-chat.bsg=dev --env-ai-chat-premium.bsg=dev`
3. purchased and loaded `Leo Premium` credentials from `account.bravesoftware.com` using `issue33973@mailinator.com`
4. clicked `Summarize this page` to confirm working credentials
5. waited
6. entered `await window.chrome.braveSkus.fetch_order_credentials(' ')` into the `Developer Tools` `Console`

### Confirmed `Uncaught Caller did not follow required call convention: ` was output (no crash)

example | example
---------|----------
<img width="1621" alt="Screen Shot 2024-01-22 at 2 20 03 PM" src="https://github.com/brave/brave-browser/assets/387249/224acc7b-8bdd-4a82-b000-16ebb08105cd"> | <img width="1621" alt="Screen Shot 2024-01-22 at 2 20 54 PM" src="https://github.com/brave/brave-browser/assets/387249/6f7a4e5b-7a40-49ea-84dd-14e7f8c44e45">

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using

```

```

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```

```

**Comment by LaurenWags** [comment]
Changed to `release-notes/exclude` per discussion with @rebron @kjozwiak
