### ISSUE TITLE
AI Chat opt-in string changes

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#33975]
## Privacy policy agreement text
Change **last** paragraph from:
> Leo does not collect or otherwise process identifiers such as IP Address that can be linked to you. No personal data is retained by the AI model or any 3rd-party model providers.

to:
> Leo does not collect identifiers such as your IP Address that can be linked to you. No personal data is retained by the AI model or any 3rd-party model providers.

## Suggested questions agreement text
Change from:
> Brave AI can automatically suggest questions based on the content of the site. You can disable it later in Settings.

to:
> Leo can automatically suggest questions based on the content of the site. To do this, the page contents of your navigations will be sent to Leo to generate these suggestions while Leo is open. You can disable it later in Settings.

_Note that screenshot does not reflect final text_
<img width="320" alt="image" src="https://github.com/brave/brave-browser/assets/741836/92e77c0f-bbe9-419c-8878-f323dda8e3e5">

**Comment by petemill** [comment]
@aguscruiz this has grown quite a bit!

**Comment by aguscruiz** [comment]
> @aguscruiz this has grown quite a bit!

Yeah, but I think it's ok to keep this design until post-mvp at least

**Comment by kjozwiak** [comment]
@brave/qa-team while verifying the above, I used the examples from https://github.com/brave/brave-core/pull/20746#issue-1969073921 and not https://github.com/brave/brave-browser/issues/33975#issue-1966032705. @petemill please let me know if that's not correct. Also asked via https://bravesoftware.slack.com/archives/C05NDQP03AQ/p1698777754522759.

**Comment by kjozwiak** [comment]
The above requires `1.60.110` or higher for `1.60.x` verification 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `Win 11 x64` using the following build(s):

```
Brave | 1.60.110 Chromium: 119.0.6045.105 (Official Build) (64-bit)
-- | --
Revision | 0bb6e7a81aed340b5a9e8b752c1cf92768257c40
OS | Windows 11 Version 22H2 (Build 22621.2506)
```

**`Example`** | **`Example`**
----------------|-----------------
![image](https://github.com/brave/brave-browser/assets/2602313/545a581a-6ae8-420d-b4a4-afca1ceb236e) | ![image](https://github.com/brave/brave-browser/assets/2602313/af7bdb7b-edd7-4595-9f1f-1b92bcf0992f)
![image](https://github.com/brave/brave-browser/assets/2602313/7875190b-d25f-489c-8c49-3e8d32f1ca26) | ![image](https://github.com/brave/brave-browser/assets/2602313/be59652e-283b-409b-9da9-2f495d905462)

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version:

```
Brave	1.60.110 Chromium: 119.0.6045.105 (Official Build) (64-bit) 
Revision	0bb6e7a81aed340b5a9e8b752c1cf92768257c40
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

- Verified opt-in string changes based on https://github.com/brave/brave-browser/issues/33975#issue-1966032705

Example | Example
-|-
![Screenshot 2023-11-01 at 12 04 32 PM](https://github.com/brave/brave-browser/assets/17885425/b1afcb4d-0d1b-44bf-aefa-788aaaf43af2) | ![Screenshot 2023-11-01 at 12 05 19 PM](https://github.com/brave/brave-browser/assets/17885425/0e1a3b7a-a8ea-449c-a865-77d12eddfb94)
![Screenshot 2023-11-01 at 12 36 28 PM](https://github.com/brave/brave-browser/assets/17885425/9b47b098-a486-4bf2-bbd9-00541604b185) | ![Screenshot 2023-11-01 at 12 36 51 PM](https://github.com/brave/brave-browser/assets/17885425/e76e3b7d-3ffe-484f-9a1c-73454bd1c872)
