### ISSUE TITLE
Graphics is overlapping on the text on the `About Leo` screen

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#33972]
## Description 

Graphics is overlapping on the text on the `About Leo` screen

## Steps to Reproduce

   1. Clean profile `1.60.105`
   2. Open brave://flags and enable the `Brave AI Chat` 
   3. Relaunch the browser
   4. Open `Leo` via sidebar
   5. Graphics is overlapping on the text `I'm here to help...` on the `About Leo` screen

## Actual result:

Graphics is overlapping on the text on the `About Leo` screen

![Graphics overlap](https://github.com/brave/brave-browser/assets/38657976/66af69e0-d55c-4e95-b497-d68a3cc9e4b2)

## Expected result:
Graphics should not overlap on the text on the `About Leo` screen

## Reproduces how often: 

100%

## Brave version (brave://version info)

Brave | 1.60.105 Chromium: 119.0.6045.59 (Official Build) (64-bit)
-- | --
Revision | a39727aa81373a09a915478fcb35826242c37335
OS | Windows 10 Version 22H2 (Build 19045.3570)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @stephendonner

**Comment by kjozwiak** [comment]
Can also reproduce this on my end. 

![image](https://github.com/brave/brave-browser/assets/2602313/bcae132f-7783-46b7-9e8e-670ee954e401)

**Comment by kjozwiak** [comment]
@GeetaSarvadnya hmmm actually, I think we might need https://github.com/brave/brave-browser/issues/33895 which will be in `1.60.106` as per https://github.com/brave/brave-browser/issues/33895#issuecomment-1782910604. Verified via https://github.com/brave/brave-core/pull/20668#issuecomment-1781912566 on Nightly. Believe we can close this off as it should be fixed in `1.60.106`.

**Comment by GeetaSarvadnya** [comment]
As per above comments closing the this issue as the fix will be available in the next RC build 1.60.106
