### ISSUE TITLE
Spelling error in Shortcuts menu — "P&ssword Manager"

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#33970]
## Description 

Go to `Settings --> System --> Shortcuts`, type in `Manager` and you'll see a spelling error for the `Password manager` keybinding where it shows the ampersand character in place of the `a`:

![image](https://github.com/brave/brave-browser/assets/3299098/76ad5ef7-2487-44a2-9baa-153222179310)

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.62.32 Chromium: 119.0.6045.105 (Official Build) nightly (x86_64)
-- | --
Revision | 76f975d47c49751a29f222762c1a24bd7df88cef
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.62.32`
2. launched Bave
3. opened `brave://settings`
4. clicked on `System`
5. clicked on `Shortcuts`
6. searched for `manager`

### Confirmed `Password Manager` is spelled correctly

`1.62.32` - `Password Manager` | `1.60.x` - `P&assword Manager`
----------|--------
<img width="1414" alt="Screen Shot 2023-11-07 at 1 58 01 PM" src="https://github.com/brave/brave-browser/assets/387249/41667cda-1fb2-4f56-ab7b-3d63e5b73fa7"> | <img width="1415" alt="Screen Shot 2023-11-07 at 1 55 19 PM" src="https://github.com/brave/brave-browser/assets/387249/be0c04fe-4cd1-49c4-8e3d-d8eec1f2b88c">
