### ISSUE TITLE
Update set of promo cards (Oct 2023)

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#33974]
## Description

https://github.com/brave/internal/issues/1085

**Comment by kjozwiak** [comment]
@brave/qa-team please use https://github.com/brave/internal/issues/1085 for verification notes 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.60.108 Chromium: 119.0.6045.59 (Official Build) (64-bit)
-- | --
Revision | 3a68c09d9a18cd981fc6bdf3d9e4bda65f57024f
OS | Windows 10 Version 22H2 (Build 19045.3570)

```
Verification notes can be found under https://github.com/brave/internal/issues/1085#issuecomment-1786511442
