### ISSUE TITLE
New tab button icon is misaligned in updated horizontal tabs

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#33976]
## Description 

In updated horizontal tabs mode, the new tab button icon is misaligned on Windows and Linux.

## Steps to Reproduce

   1. Enable the `#brave-horizontal-tabs-update` feature

## Actual result:

![new-tab-off-center](https://github.com/brave/brave-browser/assets/5995084/d65a2602-9fa7-4b7f-a3ff-c0a7d9b254ff)

## Version/Channel Information:

Nightly only

## Miscellaneous Information:

Appears to have been introduced after a Cr bump.

**Comment by kjozwiak** [comment]
The above requires `1.61.68` or higher for `1.61.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.61.69 Chromium: 119.0.6045.124 (Official Build) beta (64-bit)
-- | --
Revision | 802f2a3dd5b30780d7195156af577bc455f97ce9
OS | Windows 11 Version 22H2 (Build 22621.2428)
```

Reproduced the issue in `1.62.6 Chromium: 119.0.6045.59 nightly` using the STR from 

![image](https://github.com/brave/brave-browser/assets/98358127/43b30e40-a459-4f49-852a-233ed7fa57e2)

Steps: 

1. Installed 1.61.69
2. launched Brave
3. opened brave://flags in a new tab
4. enabled `#brave-horizontal-tabs-update`
5. hover over a new tab button


#### Confirmed new tab button icon is properly aligned https://github.com/brave/brave-browser/issues/33976#issue-1966077755

step 4 | step 5
----- | ----
<img width="960" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/6f90d2b6-6b24-4f92-9f7a-4f5bba5f7d4d">|<img width="958" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/64d7490b-3443-45eb-b1c1-35dd14769e2e">
