### ISSUE TITLE
Filter Facebook action and comment IDs from URLs

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#33984]
Facebook uses a number of query parameters on links to third-party pages. They all start with `fb_`.

`fb_comment_id` presumably helps to leak more information about the referring page than the referrer header:
- https://ciusssmcq.ca/blogue/4/outil-gastro-recette-de-liquide-de-rehydratation/?fb_comment_id=2018780648164493_2026993357343222
- https://www.caissepopulairedehearst.com/single-post/2016/03/06/Concours-Doublez-votre-ristourne?fb_comment_id=1374169219324702_1377119962362961
- https://chaudiereappalaches.com/fr/actualites/?fb_comment_id=592551850849568_594719467299473

`fb_ref` is not clear since it's often single words. It looks more like a campaign parameter. 

`fb_action_ids` is using very long IDs, enough to identify individuals.

`fb_source` and `fb_action_types` appear to always be single words from a small list of locations/actions on Facebook.

Example URLs:
- https://sailracer.net/windgame/?fb_ref=Default
- http://cheezburger.com/View/5933016064?fb_ref=shared_from_asset_view
- https://www.intel.sg/content/www/xa/en/newsroom/news/xeon-scalable-5g-network-portfolio-launch.html?fb_ref=r5oVU0pUqM-Tumblr&utm_source=Tumblr&utm_medium=ShareButton&utm_campaign=GetSocial&countrylabel=Asia%20Pacific
- https://www.entrust.cn/digital-security/hsm/products/nshield-hsms/nshield-edge?fb_ref=rDtmH8NdGu-Telegram
- http://www.magarderie.com/garderie-milieu-familial/36756-la-maison-du-bonheur.html?fb_ref=36756&fb_source=profile_onelin
- https://www.ted.com/talks/lori_gottlieb_how_changing_your_story_can_change_your_life?fb_ref=talk&language=fr
- https://www.nasa.gov/audience/foreducators/topnav/materials/listbytype/Orion_Model.html?fb_action_ids=10201679565844214&fb_action_types=og.likes&fb_ref=.UrJbyJguoz4.like&fb_source=other_multiline&action_object_map=%5B457911120947104%5D&action_type_map=%5B%22og.likes%22%5D&action_ref_map=%5B%22.UrJbyJguoz4.like%22%5D

**Comment by fmarier** [comment]
All of these will be removed by the "copy clean link" feature: https://github.com/brave/adblock-lists/pull/1379

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.62.29 Chromium: 119.0.6045.105 (Official Build) nightly (x86_64)
-- | --
Revision | 722db0323f23c1aaee8a62326083bced61909279
OS | macOS Version 14.2 (Build 23C5030f)
```

### Steps:
1. installed `1.62.29`
2. launched Brave
3. loaded `https://brave.com/?foo=bar&irclickid=1234&ymclid=abcd&ysclid=efgh&fb_action_ids=5678&fb_comment_id=123456&clean=yes` with the `Developer Tools`' console open

### Confirmed entering and trying to load https://brave.com/?foo=bar&irclickid=1234&ymclid=abcd&ysclid=efgh&fb_action_ids=5678&fb_comment_id=123456&clean=yes resulted in only `https://brave.com/?foo=bar&clean=yes` being loaded

<img width="1897" alt="Screenshot 2023-11-06 at 3 22 59 PM" src="https://github.com/brave/brave-browser/assets/387249/8092c110-3baf-43f3-85db-9acd8cdfb204">

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.62.121`

### Steps:
1. installed `1.62.x`
2. launched Brave
3. loaded `https://brave.com/?foo=bar&irclickid=1234&ymclid=abcd&ysclid=efgh&fb_action_ids=5678&fb_comment_id=123456&clean=yes` with the `Developer Tools`' console open

### Confirmed entering and trying to load https://brave.com/?foo=bar&irclickid=1234&ymclid=abcd&ysclid=efgh&fb_action_ids=5678&fb_comment_id=123456&clean=yes resulted in only `https://brave.com/?foo=bar&clean=yes` being loaded


![image](https://github.com/brave/brave-browser/assets/38657976/d45c3534-a1a9-49e2-aa88-f8829abfe722)
