### ISSUE TITLE
[Android] Update block app links feature

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#33981]
we need to update block app links feature as below, 

- [ ] Add `General` category and add `Widevine DRM` and `Background play` to newly created category
- [ ] Add `Youtube` category in `Media`
- [ ] Add option `Open YouTube links in Brave` under `Youtube` category
- [ ] Remove `Video playback in Brave` from `Site settings`

*Figma spec* : https://www.figma.com/file/eQclVYFfDpTgztKDCq9ROk/Youtube-Improvements?type=design&node-id=230-11489&mode=design&t=ybEsKOw1O2wMyJEy-0**

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` & `Samsung Galaxy Tab S7` using version: 

```
Brave	1.62.121 Chromium: 120.0.6099.144 (Official Build) beta (64-bit) 
Revision	ec4a006cb0f9a9d309ef78f6e11882e4bcf12c14
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
Acceptance Criteria: https://github.com/brave/brave-browser/issues/33981#issue-1966195911

- [x] Add `General` category and add `Widevine DRM` and `Background play` to newly created category
- [x] Add `Youtube` category in `Media`
- [x] Add option `Open YouTube links in Brave` under `Youtube` category
- [x] Remove `Video playback in Brave` from `Site settings`
- [x] UI conforms to Figma specs

Functional Scenarios: 

- Ensured Toggles are working and restart prompt is shown for `Widevine DRM` & `Background play` settings.
- Ensured Background play works.
- Ensured YT links open in Brave when `Open YouTube links in Brave` is enabled and vice versa. 

Default | Settings toggles (ON) | Settings toggles (OFF) | 1.61.x | 1.62.x
-|-|-|-|-
![Screenshot 2023-12-28 at 1 16 54 PM](https://github.com/brave/brave-browser/assets/17885425/9ce55224-d6fe-4a1a-80f9-95720c1def2f) | ![Screenshot 2023-12-28 at 12 26 02 PM](https://github.com/brave/brave-browser/assets/17885425/6f3aa854-bafc-48e9-8e4f-4f2333c500bd) | ![Screenshot 2023-12-28 at 1 10 57 PM](https://github.com/brave/brave-browser/assets/17885425/f444d01e-925a-4e93-aac5-c1cba0b592ce) | ![Screenshot 2023-12-28 at 1 07 06 PM](https://github.com/brave/brave-browser/assets/17885425/886308e3-af62-4dc8-8a44-45fd534b1bd3) | ![Screenshot 2023-12-28 at 1 07 17 PM](https://github.com/brave/brave-browser/assets/17885425/75285c7f-6201-4ec5-90f6-f456b1c7a98d)
![Screenshot 2023-12-28 at 1 32 37 PM](https://github.com/brave/brave-browser/assets/17885425/1da69f74-bd09-4e72-8184-d14287323650) | ![Screenshot 2023-12-28 at 1 22 55 PM](https://github.com/brave/brave-browser/assets/17885425/28414b8b-d20d-4224-84ff-e1ee774f5c8b) | ![Screenshot 2023-12-28 at 1 23 03 PM](https://github.com/brave/brave-browser/assets/17885425/cfe7cf74-3f1d-48c9-ba1f-367d474b0359) | ![Screenshot 2023-12-28 at 1 28 16 PM](https://github.com/brave/brave-browser/assets/17885425/c6559cc9-c713-4485-927e-1d067d91b2f3) | ![Screenshot 2023-12-28 at 1 23 25 PM](https://github.com/brave/brave-browser/assets/17885425/45f863da-05d9-4677-92ec-02fac3cad461)
