### ISSUE TITLE
`Like`/`Dislike` feedback context-menu "jumps" in certain viewport scroll positions

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#33988]
## Description 

`Like`/`Dislike` feedback context-menu "jumps" in certain viewport scroll positions

## Steps to Reproduce

1. install `1.60.106`
2. launch Brave
3. enable `AI chat` in `brave://flags`
4. click on `Relaunch`
5. click on `Leo` in the sidebar
6. click on `Accept and begin`
7. load a page (mine happened to be `https://www.gnc.com/protein-powder/556500.html#start=1`)
8. click on `Summarize this page`
9. click on the pre-suggested questions
10. hover over the responses
11. click on the `...` ellipsis icon

## Actual result:

Sometimes, it jumps, as I've captured below

https://github.com/brave/brave-browser/assets/387249/c3fa5c5a-ff1c-4dd2-a5e6-91b6439d00df

## Expected result:

No context-menu jump when clicking on the ellipsis

## Reproduces how often: 

Easily, but not all the time - depends on viewport, scroll positions, etc.

## Brave version (brave://version info)

```
Brave | 1.60.106 Chromium: 119.0.6045.59 (Official Build) (64-bit)
-- | --
Revision | 16064193dde8c55f64dabd32f125c0cd9380f96a
OS | Windows 10 Version 22H2 (Build 19045.3636)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A`
- Can you reproduce this issue with the beta channel? `Not sure`
- Can you reproduce this issue with the nightly channel? `Not sure`

## Miscellaneous Information:

cc @bbondy @petemill @nullhook @mattmcalister @brave/qa-team

**Comment by nullhook** [comment]
the latest nala upgrade should've fixed this.

**Comment by nullhook** [comment]
fixed here: https://github.com/brave/leo/pull/495
