### ISSUE TITLE
Remove `Browser` from macOS App menu title in beta and nightly channel

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#33987]
## Description 

In Release channel macOS App menu ensure that the title reads `Brave`. 

Currently, in Beta channel it should read `Brave Beta` and in Nightly channel it should read `Brave Nightly`. 
Having the title as `Brave Browser Beta` or `Brave Browser Nightly` is causing problems with MacBooks that include a notch.

Appears that Release channel is correct and macOS app title reads `Brave` with version 1.60.105.
Problem occurs with Beta and Nightly channel with versions 1.61.53 and 1.62.6

STR
1. Launch Brave and check `Brave Nightly` is shown at menu bar
2. Enter fullscreen

## Actual result:
<img width="308" alt="Screenshot 2023-10-28 at 8 25 29 PM" src="https://github.com/brave/brave-browser/assets/5951041/d2b0719e-44f6-4fb9-b906-4e82791f77d0">
<img width="196" alt="Screenshot 2023-10-28 at 8 25 20 PM" src="https://github.com/brave/brave-browser/assets/5951041/23ee0622-a792-46d3-8bcc-5374af27019c">

## Expected result:
It should be `Brave Nightly`, `Brave Beta` or `Brave`

## Version/Channel Information:

- Can you reproduce this issue with the current release? No.
- Can you reproduce this issue with the beta channel? Yes.
- Can you reproduce this issue with the nightly channel? Yes.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by rebron** [comment]
cc: @simonhong @emerick

**Comment by simonhong** [comment]
https://github.com/brave/brave-core/pull/16400 fixed but it seems regressed.

**Comment by simonhong** [comment]
Hmm, I'm seeing `Brave Nightly` for nightly channel but `Brave Browser Beta` for beta channel.

**Comment by simonhong** [comment]
I feel like this happens when another app is launched but not always...

**Comment by simonhong** [comment]
Changed to upstream-wait as upstream has a fix for this - https://bugs.chromium.org/p/chromium/issues/detail?id=1487224

**Comment by simonhong** [comment]
> @simonhong re:
> 
> > I feel like this happens when another app is launched but not always...
> 
> Same issue as #33280?

Yes! same issue.

**Comment by LaurenWags** [comment]
Thanks @simonhong! Commented on other issue to reference this one as there's some more action/info over here 👍🏻

**Comment by dryspeed** [comment]
Even in the current release channel (1.60.110) it reads `Brave Browser` instead of `Brave`
<img width="195" alt="Screenshot 2023-11-04 at 3 53 23 PM" src="https://github.com/brave/brave-browser/assets/142707208/42dbcb52-dd67-41cb-bbc8-a7ea967645aa">

**Comment by LaurenWags** [comment]
@dryspeed this is resolved on Nightly channel and we're looking to uplift the fix to other channels.

**Comment by kjozwiak** [comment]
The above requires `1.61.69` or higher for `1.61.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.61.69 Chromium: 119.0.6045.124 (Official Build) beta (x86_64)
-- | --
Revision | 802f2a3dd5b30780d7195156af577bc455f97ce9
OS | macOS Version 14.2 (Build 23C5030f)
```

## First, reproduced easily using `Brave` `1.62.6` on `macOS` `Sonoma`:

example | example
---------|----------
<img width="1920" alt="Screenshot 2023-11-08 at 1 59 13 PM" src="https://github.com/brave/brave-browser/assets/387249/8767583a-83ed-4007-9ba7-10015dfb442d"> | <img width="484" alt="Screenshot 2023-11-09 at 12 46 45 AM" src="https://github.com/brave/brave-browser/assets/387249/73f53dbe-07f5-4595-8479-bd07f0c753c7">
