### ISSUE TITLE
[Android] Use Brave Rewards CTA doesn't work

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#33980]
## Description 
Tipping using rewards is not working. Tapping Use Brave Rewards CTA does nothing.

## Steps to reproduce 

   1. Enable rewards
   2. connect to custodian (Uphold)
   3. go to verified publisher
   4. Open rewards panel
   5. Tap `Send Contribution`
   6. Tap `Use Brave Rewards`

## Actual result 
Tapping `Use Brave Rewards` CTA does nothing.

## Expected result
Tapping Use Brave Rewards CTA should open the contribution bottomsheet. 

## Issue reproduces how often 
Easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? yes
- Can you reproduce this issue with the current Play Store Nightly version? yes

## Device details
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.61.93` or higher for `1.61.x` verification 👍
