### ISSUE TITLE
dict.erase(it) causes crash in AIChatCredentialManager

### ISSUE THREAD

**Issue by nvonpentz** [brave/brave-browser#33999]
https://github.com/brave/brave-core/blob/master/components/ai_chat/core/ai_chat_credential_manager.cc#L169

Since erasing an iterator can invalidate the remainder of the to_erase list. Happens in cases when to_erase > 1.

**Comment by kjozwiak** [comment]
The above requires `1.60.109` or higher for `1.60.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.60.109 Chromium: 119.0.6045.59 (Official Build) (64-bit)
-- | --
Revision | fc399c7c433510eb03c2b35281bf8935804b99de
OS | Windows 10 Version 22H2 (Build 19045.3570)

```
