### ISSUE TITLE
Accounts Tab is showing $0.00 briefly before return

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#33993]
## Description 

The `Accounts` tab is showing `$0.00` for account fiat values briefly before the actual fiat value is returned

## Steps to Reproduce

   1. Open the Wallet and navigate to the `Accounts` tab
   2. The fiat value for every account will show `$0.00` value briefly before actually value is returned

## Actual result:

https://github.com/brave/brave-browser/assets/40611140/781c3d4a-3932-4edb-9df2-7be36eb61bcd

## Expected result:

Should continue to show the `Loading Skeleton` until we the actual fiat value is returned.

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.62.130 Chromium: 120.0.6099.199 (Official Build) beta (64-bit)
-- | --
Revision | `6d589c6dc0f3489830d40332c82cdd5597e41c88`
OS | Windows 11 Version 23H2 (Build 22631.2861)

- Verified steps from 
- Verified accounts tab doesn't show $0.00 when balance is being fetched

https://github.com/brave/brave-browser/assets/17010094/daeb0172-97de-4551-8f82-e102112f054e


---------------------

**Verification passed on**

Brave | 1.62.130 Chromium: 120.0.6099.199 (Official Build) beta (64-bit)
-- | --
Revision | `6d589c6dc0f3489830d40332c82cdd5597e41c88`
OS | Linux

- Verified steps from 
- Verified accounts tab doesn't show $0.00 when balance is being fetched

https://github.com/brave/brave-browser/assets/17010094/e4f76947-f804-4b0c-b488-ed91146fd76a


---------------------

**Verification passed on**

Brave | 1.62.130 Chromium: 120.0.6099.199 (Official Build) beta (arm64)
-- | --
Revision | `6d589c6dc0f3489830d40332c82cdd5597e41c88`
OS | macOS Version 14.2.1 (Build 23C71)

- Verified steps from 
- Verified accounts tab doesn't show $0.00 when balance is being fetched

https://github.com/brave/brave-browser/assets/17010094/cc78e2d8-5575-4e5c-b6d7-2fe4e28cc42b
