### ISSUE TITLE
Brave Player MVP for desktop

### ISSUE THREAD

**Issue by sangwoo108** [brave/brave-browser#33997]
[spec](https://docs.google.com/document/d/1wSAowffI_-KnBci8CHtT-f7hw-_YgTSj-nVkiU4tIZw/edit)

Implement MVP of Brave Player

* Show "Brave Player" Page action view on omnibox when visiting youtube videos
* When clicking it, opens a new tab which embed iframe-ed youtube video
* This new tab consists of two web ui pages
  * Outer, top-most frame: brave://player
  * Inner, embedder of external contents: brave-untrusted://player-embed

**Comment by MadhaviSeelam** [comment]
@sangwoo108 Can you attach testplan please?

**Comment by LaurenWags** [comment]
cc @rebron in case you (or others?) can add to the test plan as well.

**Comment by sangwoo108** [comment]
Hi, I updated Test plan in the PR

**Comment by LaurenWags** [comment]
thanks @sangwoo108!

There was also a bit of discussion around this one in today's desktop call - @kjozwiak suggested waiting to test this until it's dev complete as @rebron mentioned there's still some more parts to implement. I'll leave this one as `QA/Blocked` for now, and if they decide we can QA it as-is, then we can remove the label 👍🏻

**Comment by LaurenWags** [comment]
Update - per discussion with @rebron @kjozwiak today this will remain `QA/Blocked` until additional work has landed.
