### ISSUE TITLE
NTP background proper image sizing is not applied

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#33998]
## Description 

New tab page background image sizing is incorrect. Should be sized properly to fit new tab page window. 

Likely due to this commit: https://github.com/brave/brave-core/commit/723f1b21e91245bbcb037adb381facc91e807c2d

## Steps to Reproduce

   1. Update to latest 1.62.12
   2. Open new tab page and notice background image either Brave's or custom.
   3. Notice image sizing in Actual result below.

## Actual result:

<img width="1576" alt="Screenshot 2023-10-30 at 11 23 33 AM" src="https://github.com/brave/brave-browser/assets/5951041/c9a07f81-44ea-4afa-a94c-bafaf46b2002">

## Expected result:
<img width="1576" alt="Screenshot 2023-10-30 at 11 50 58 AM" src="https://github.com/brave/brave-browser/assets/5951041/63f27f8a-5cd2-4ff0-99db-6729459ff0c7">

## Reproduces how often: 

Easily.

## Brave version (brave://version info)

Starting with 1.62.12. 
Not an issue with 1.62.11 or lower.

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

## Miscellaneous Information:

Maybe Brave News feed v2 related.

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
.
```

First, reproduce the issue using `1.62.12`:

example | example
---------|---------
<img width="1897" alt="Screenshot 2023-11-06 at 3 48 10 PM" src="https://github.com/brave/brave-browser/assets/387249/2b679ef8-f8e7-41bb-8c89-cc81f3ae47c1"> | <img width="1897" alt="Screenshot 2023-11-06 at 3 48 17 PM" src="https://github.com/brave/brave-browser/assets/387249/92528154-fc61-4ed4-a56f-afeda5f3d75e">

**Comment by LaurenWags** [comment]
I'm still experiencing this with 1.62.105:

Example | Example
--- | ---
<img width="1560" alt="Screenshot 2023-12-12 at 12 22 16 PM" src="https://github.com/brave/brave-browser/assets/28145373/16733949-c3a2-4189-85d0-8152481f48d9"> | <img width="1555" alt="Screenshot 2023-12-12 at 12 22 28 PM" src="https://github.com/brave/brave-browser/assets/28145373/5e0c5d8a-a509-491a-93b8-5822d2225ccf">

It doesn't seem to happen right away, it happens after a few tabs have been opened and I've closed/reopened the browser.

```
Brave | 1.62.105 Chromium: 120.0.6099.71 (Official Build) beta (x86_64)
-- | --
Revision | f72c783bcd52110d026061575b4bef28ccb547f7
OS | macOS Version 13.6.1 (Build 22G313)
```

Will log a follow up issue.

**Comment by btlechowski** [comment]
Verified with


Brave | 1.62.123 Chromium: 120.0.6099.144 (Official Build) beta (64-bit)
-- | --
Revision | 680382264ff6ae655b3bba25e80567452f38fbee
OS | Linux


![image](https://github.com/brave/brave-browser/assets/34715963/b20ca916-dce0-474a-85b9-97db3552798b)|![image](https://github.com/brave/brave-browser/assets/34715963/e7a14e88-053d-426c-a380-c3fc7d9d3c34)
--|--

![image](https://github.com/brave/brave-browser/assets/34715963/36b07592-89ed-477c-9e49-a0bde9a68364)|![image](https://github.com/brave/brave-browser/assets/34715963/70f99b26-53ae-446d-9417-422bc00390de)
--|--
