### ISSUE TITLE
Browser crash when trying to SIWE 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#33991]
## Description 
Browser crash when trying to SIWE 

## Steps to reproduce 

   1. Upgrade to 1.60.106 
   2. Create Wallet 
   3. Visit `https://login.xyz` 
   4. Select `Sign-in with Ethereum`
   5. Connect account and wait for sign message
   6. Nothing shows on the sign message
   7. Click sign,  Browser crashes
   9. Change account from Solana to Ethereum and try again
   10. Able to see SIWE panel details

## Actual result 
https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1698654991343709

## Expected result
No crash should not show blank SIWE message panel 

## Issue reproduces how often 
Intermittent happened once

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? Not checked
- Can you reproduce this issue with the current Play Store Nightly version? Not checked

## Device details
   - Install type (ARM, x86):ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 13
   
## Brave version
1.60.106

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @simoarpe

**Comment by simoarpe** [comment]
Tried several times to reproduce the issue reported but was not able to observe any crash. Connected account always fell back to Ethereum. 
Tested on latest master branch [commit 0d36c4485cf4ac1702afb55ae44c5b43ee85b30e](https://github.com/brave/brave-core/commit/0d36c4485cf4ac1702afb55ae44c5b43ee85b30e).

**Comment by simoarpe** [comment]
Relentlessly tried to reproduce the issue but was unable to. I'm closing this now. @srirambv if you manage to observe the crash again feel free to reopen and ping me here. Thanks!
