### ISSUE TITLE
Rewards extension popup doesn't display translated strings on linux with dist executable

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#3399]
On local, executing brave in `src/out/Release/dist`, rewards popup doesn't show translated string.

Below is the result with korean locale.
<img width="445" alt="screen shot 2019-02-18 at 15 05 46" src="https://user-images.githubusercontent.com/6786187/52932257-7ef8ff00-3392-11e9-9ef1-48d9bcd59e01.png">

**Comment by simonhong** [comment]
`i18n: xxxx` is displayed because `chrome.i18n.getMessage()` returns null.
```
export const getMessage = (message: string, substitutions?: string[]): string => {
  if (chrome.i18n) {
    let translated = chrome.i18n.getMessage(message, substitutions)

    if (translated) {
      return translated
    } else {
      return `i18n: ${message}`
    }
  }

  return `i18n missing: ${message}`
}
```

**Comment by simonhong** [comment]
Duplicated issue with https://github.com/brave/brave-browser/issues/1555.

**Comment by srirambv** [comment]
Marking `QA/No` as its duplicated with #1555 which is on verification list.
