### ISSUE TITLE
UI regression in new tab button

### ISSUE THREAD

**Issue by kdenhartog** [brave/brave-browser#34008]
![Screenshot 2023-10-31 at 11 56 05 AM](https://github.com/brave/brave-browser/assets/23125059/2a0f1d06-57e6-4c3c-a889-d0d24e5a5dfe)

The new tab button appears like it's been changed recently and is now showing in the bottom left corner. This seems like it may be a regression so opening an issue for it.

cc @zenparsing since @fallaciousreasoning said you may have been working on something similar recently.

noticed this on the following build:

Brave | 1.62.6 Chromium: 119.0.6045.59 (Official Build) nightly (arm64)
-- | --
Revision | c68ed6fd2d7b5aa279d88882ad62b0589a256968
OS | macOS Version 14.0 (Build 23A344)

**Comment by Emi-HoloGhostRevisionist88** [comment]
Fixed 2 days ago https://github.com/brave/brave-core/pull/20724 and available since 1.62.10.

**Comment by kdenhartog** [comment]
Ahh yup, looks like my nightly hadn't updated that yet. I'm seeing it fine now. Thanks closing as won't fix.
