### ISSUE TITLE
Problem with the installer

### ISSUE THREAD

**Issue by Felipefpl** [brave/brave-browser#3400]
Hi, downloaded latest brave from website, started the download but the download progress bar kept going back and forth what obviously didnt show how long the download was going to last, neither there was any kind of % being shown, WHY cant we have a simple FULL installer like EVERY program out there that can save us from such problem? PLEASE, make those for us, we like them aside that lets us know what is the size of brave.

**Comment by srirambv** [comment]
What OS are you running the setup on? Were you able to install or did it fail?

**Comment by bsclifton** [comment]
Closing as there hasn't been any update

@Felipefpl please re-open if you want to troubleshoot and let us know your OS and version (sounds like you're on Windows... Windows 7? Windows 10?)

There are full installers available on the Releases page on GitHub (has `Standalone` in the name):
https://github.com/brave/brave-browser/releases
