### ISSUE TITLE
Add security access header to local node requests

### ISSUE THREAD

**Issue by cypt4** [brave/brave-browser#34000]
Initial idea is to make Kubo an ability to decide which extensions and sites are able to access it's API.
Since WebRequest API is available in the Brave Browser we need to research if it is possible to add headers which bypass this API.
For example - restore Origin header if it was modified, but only for localnode requests.
cc @lidel

**Comment by diracdeltas** [comment]
Slack discussion here: https://bravesoftware.slack.com/archives/C8MP8ME4C/p1698695590144259

**Comment by lidel** [comment]
[RPC API.Authorizations](https://github.com/ipfs/kubo/blob/master/docs/changelogs/v0.25.md#rpc-apiauthorizations) will be released in Kubo 0.25, allowing Brave to limit access to specific commands.

It relies on `Authorization: Bearer <token>` header, so once Brave hides requests to `127.0.0.1:485001` (Kubo RPC port), a token unique to browser extension could be added to lock this down.

There is also follow-up work in https://github.com/ipfs/kubo/issues/10229 to namespace things like MFS and IPNS keys per token, locking it down even further.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.63.157 Chromium: 122.0.6261.43 (Official Build) (64-bit)
-- | --
Revision | 5fbb7c60cc44e15a910a39a349e632f1b904c58e
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from [brave/brave-core#21159](https://github.com/brave/brave-core/pull/21159)
- Verified RPC traffic from the extensions is not visible for WebRequest API

Before | After
-- | --
![brave_s5Z4sb7hTL](https://github.com/brave/brave-browser/assets/17010094/81cc60e4-393e-4d01-83c6-0d77d01a8123) | ![brave_P9by8DwvOz](https://github.com/brave/brave-browser/assets/17010094/347d397c-8d25-491f-a4cc-5ff29caff264)
