### ISSUE TITLE
Add third-party adblock extension P3A metric

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#34006]
Add desktop metric for third-party adblock extensions:

Do you have a popular third-party adblock extension installed?
`Brave.Extensions.AdBlock`

0. No
1. Yes

The following extensions will be checked:
- uBlock Origin
- Ghostery
- AdGuard
- AdBlocker Ultimate

**Comment by kjozwiak** [comment]
The above requires `1.60.121` or higher for `1.60.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.60.124 Chromium: 119.0.6045.163 (Official Build) (64-bit)
-- | --
Revision | 803c85554783c998a840f4b211c94236409a9928
OS | Windows 10 Version 22H2 (Build 19045.3693)

```
