### ISSUE TITLE
Account is not selected on Deposit & Buy screen

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#34016]
## Description 
Account is not selected on Deposit screen causing no QR code to be shown. Similarly no account is selected on Buy screen

## Steps to reproduce 
Deposit screen

   1. Update to 1.62.15 
   2. Open Wallet and go to deposit screen
   3. Select any token
   4. No QR code is shown since no account is selected by default

Buy Screen

   1. Update to 1.62.15 
   2. Open Wallet and go to deposit screen
   3. Select any token
   4. No account is selected 

## Actual result 

Deposit | Buy
-- | --
<video src=https://github.com/brave/brave-browser/assets/17010094/845db31f-2441-454b-83d1-fc4fa424601b> | <video src=https://github.com/brave/brave-browser/assets/17010094/39137ad0-e169-401b-bad9-47f62adce950>

## Expected result
Account should be selected on both the screens

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? NA
- Can you reproduce this issue with the current Play Store Beta version? NA
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone 
   - Android version: 13
   
## Brave version
1.62.15

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @simoarpe

**Comment by simoarpe** [comment]
Issue fixed after rebasing on latest master. Closing this.
Feel free to reopen in case it could be observed again.
