### ISSUE TITLE
Update all panel UI to match V2 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#34014]
## Description 
Update all panel UI to match V2 

## Actual result 
Android panel still uses V1 UI at certain places

## Expected result
All UI should be V2 to have parity between iOS/Desktop

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
All

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @jamesmudgett

**Comment by simoarpe** [comment]
@srirambv I'm closing issue as it's not relevant anymore. Feel free to reopen is there are some panels to update to V2.
/cc @jamesmudgett
