### ISSUE TITLE
Leo is not blocked in private windows [Android]

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#34015]
## Description 
Brave Leo is not disabled from the menu for private windows

## Steps to reproduce 

   1. Enable the brave ai chat flag
   2. Open private tab
   3. Tap on the hamburger menu and check if Leo is present
   4. Tap on Leo in the menu

## Actual result 
Leo is not blocked

![Screenshot 2023-10-31 at 11 12 24 AM](https://github.com/brave/brave-browser/assets/17885425/055d7718-d007-4ffd-9a8e-3d8b570b1dc6)

## Expected result
Leo should be blocked

## Issue reproduces how often 
Always

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? TBD
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM 64
   - Device type (Phone, Tablet, Phablet): Samsung GS 21
   - Android version: 13
   
## Brave version
`1.60.109, Chromium 119.0.6045.59`

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.62.116`

- Verified the STR from the description and ensured that `Leo` settings is removed from the hamburger menu in Private Tab 

1.62.x | Release
-------|--------
![Screenshot_20231227_202439](https://github.com/brave/brave-browser/assets/38657976/f795604d-15e4-476b-949b-e9bb5c94237d) | ![Screenshot_20231227_202424](https://github.com/brave/brave-browser/assets/38657976/2ba59d83-5e81-4312-a6d8-9b3c35086a4b)
