### ISSUE TITLE
No Captcha display after DnD captcha from BR panel to incorrect target in Rewards settings page

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#3402]
## Description 
No Captcha display after DnD captcha from BR panle to incorrect target in Rewards settings page

## Steps to Reproduce

1. Clean profile 0.60.34, enable rewards through BR panel  (Don't click on `claim` button)
2. Select `Brave Rewards` from hamburger menu
3. Click on `claim` on BR panel
4. You can see Captcha displayed in both BR panel and rewards page
5. Drag and drop Source captcha from BR panel to incorrect target in rewards page
6. You can see try again message
7. Click on `claim` on BR panel - Nothing happens, no captcha display
8. Click on `CLAIM` on rewards page - Nothing happens no captcha display
9. Cannot claim grants from both places

## Actual result:

No captcha display after clicking on `claim` / `CLAIM` bitton - Unable to claim grants from BR panel as well as from Rewards settings page

## Expected result:
Captcha should be displayed and able to claim grants from both BR panel and rewards settings page.

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 0.60.34 Chromium: 72.0.3626.109 (Official Build) beta (64-bit)
-- | --
Revision | fae8db7ab9280fa6704a59980263c804f809ebd5-refs/branch-heads/3626@{#857}
OS | Windows 10

### Reproducible on current release: Yes
- Does it reproduce on brave-browser dev/beta builds? Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional Information

@brave/legacy_qa

**Comment by LaurenWags** [comment]
Reproduced up to step 7. However, when I tried step 8 I was able to claim from brave://rewards page.

Was using 

Brave | 0.60.28 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Mac OS X

**Comment by kjozwiak** [comment]
> Drag and drop Source captcha from BR panel to incorrect target in rewards page

not really sure how many folks will actually drag the BAT icon from the BR panel into the `brave://rewards` CAPTCHA area.

@GeetaSarvadnya when this happens, are you in a constant broken state? Does restarting the browser help? Either way, not urgent as this is marked as P5 which I agree. I don't think a lot of people will be dragging the BAT icon from the BR panel into the `brave://rewards` CAPTCHA area.
