### ISSUE TITLE
Brave crashing "randomly" Windows 11

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#34025]
## Description 

Opening this issue at the request of @iefremov —  just reporting what the user shared here:

> Brave crashes randomly upon opening it and loading different tabs.
> 
> I don’t know what else to share of this except that I clicked send now as I assume that it sends the log files to the support team?
> I have at least four extensions installed throughout and yes it crashes with them. As for when it crashes, I can only remember that it crashes whenever I just open the youtube website. Its not frequent and its occasional but that’s where it mostly happens. There was also one time that if I opened multiple tabs it did crash but I can’t remember beyond this.

> Uploaded crash report ID: 0b820d00-be6a-ef0a-0000-000000000000
> Uploaded crash report ID: 0d820d00-be6a-ef0a-0000-000000000000
> Uploaded crash report ID: 0a820d00-be6a-ef0a-0000-000000000000
> Uploaded crash report ID: 07820d00-be6a-ef0a-0000-000000000000
> Uploaded crash report ID: 00820d00-be6a-ef0a-0000-000000000000
> Uploaded crash report ID: 05820d00-be6a-ef0a-0000-000000000000
> 

## Reproduces how often: 

Intermittent for this use

## Brave version (brave://version info)

v1.59.124

## Miscellaneous Information:

Internal slack link:
https://bravesoftware.slack.com/archives/C01826CM3J9/p1698778800115179

**Comment by Brave-Matt** [comment]
User's extensions include:

- clipt 
- strong password generator 
- Bitdefender 
- tubebuddy

**Comment by iefremov** [comment]
stale
