### ISSUE TITLE
Reenable Power Bookmarks in side panel

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#34021]
Per @rebron, we should reenable Power Bookmarks in the side panel (previously disabled here https://github.com/brave/brave-core/pull/20664).

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using

```
Brave | 1.62.28 Chromium: 119.0.6045.105 (Official Build) nightly (x86_64)
-- | --
Revision | af1dadeae432bc6f1bed980ac4123d5b7dda6e24
OS | macOS Version 11.7.10 (Build 20G1427)
```




example | example
---------|---------
<img width="1414" alt="Screen Shot 2023-11-06 at 8 48 02 PM" src="https://github.com/brave/brave-browser/assets/387249/4c6324ef-f5e4-4e29-915b-6899f5e56b30"> | <img width="1909" alt="Screen Shot 2023-11-06 at 8 48 25 PM" src="https://github.com/brave/brave-browser/assets/387249/ed05ada3-0d19-4d55-ba0e-5504654b7e4b">

**Comment by GeetaSarvadnya** [comment]
Power bookmark has the new UI, t would be better to test on all platforms hence added `QA/Test-All-Platforms` label

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.62.87 Chromium: 120.0.6099.35 (Official Build) nightly (x86_64)
-- | --
Revision | e0cd7777fe0c2b5f4fe9e1bc27cedd1f87eac37f
OS | macOS Version 13.6.1 (Build 22G313)
```

Note - just checking this feature out and doing some comparison between version, per discussion in today's desktop meeting, as this was already verified on macOS.

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.62.90 Chromium: 120.0.6099.35 (Official Build) nightly (64-bit)
-- | --
Revision | 276c6d1745bff39888cedcc6aa54e9c5c35e764e
OS | Windows 11 Version 22H2 (Build 22621.2715)
```

1. Verified imported bookmarks via below methods are shown in the bookmarks sidebar panel
  - onboarding
  - bookmarks html file
  - imported from different browsers via brave://settings/importData

example | example | example | example 
---- | ----- | ----- | -----
<img width="956" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/71789efd-e385-4e34-a2e7-5fcd68d6f42d">|<img width="959" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/0c8186b3-f593-4b78-a13b-79c32cb323a8">|<img width="954" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/f38e7b27-b6d5-454c-8f60-45b386d51d99">|<img width="957" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/e4bf1f14-9df3-4ca5-801e-f7093a00a3a0">

2.  Verified bookmark dialog when clicked on bookmark next to URL bar
      - Added bookmark via dialog
      - Edited bookmark to move to different folder to "Banks-->Other bookmarks" but Other bookmarks was shown as "All bookmarks" at the top right corner.
      - Able to edit, delete & add new folder within the dialog

 example | example | example | example
 ------ | ----- | ------ | ----
<img width="330" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/f57b3518-936a-45d9-92a4-5cbe653c0c6e">|<img width="330" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/8ed10980-e988-4fc6-8753-cced5f7de70b">|<img width="472" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/2e629d78-3429-4e0c-8118-df624f58a89d">|<img width="286" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/66f991ba-60a8-4012-8208-8a9a5089226e">


3. Verified Search functionality in the bookmarks bar sidepanel worked as expected

![image](https://github.com/brave/brave-browser/assets/98358127/be40a565-9ec8-453f-b2b9-3a986c466e8b)

**Comment by kjozwiak** [comment]
The above requires `1.61.94` or higher for `1.61.x` verification 👍 Going to remove the `QA-Pass` labels as we'll need to re-check on `1.61.x`. However, as `macOS` & `Win` were pretty thoroughly checked via https://github.com/brave/brave-browser/issues/34021#issuecomment-1830662756 & https://github.com/brave/brave-browser/issues/34021#issuecomment-1832839326, we'll just need a quick spot check on those planforms.

* `macOS x64` - quick spot check as we already ran through the above via https://github.com/brave/brave-browser/issues/34021#issuecomment-1830662756
* `Win x64` - quick spot check as we already ran through the above via https://github.com/brave/brave-browser/issues/34021#issuecomment-1832839326
* `Linux x64` - Still needs to run through similar cases that were done on `macOS` & `Win`.

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.61.94 Chromium: 120.0.6099.56 (Official Build) (64-bit)
-- | --
Revision | 72759647494f071d653f8a61465fadf5f361b06e
OS | Windows 10 Version 22H2 (Build 19045.3693)

```

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.61.94 Chromium: 120.0.6099.56 (Official Build) (x86_64)
-- | --
Revision | 72759647494f071d653f8a61465fadf5f361b06e
OS | macOS Version 11.7.10 (Build 20G1427)
```

**Comment by btlechowski** [comment]
Verified with

Brave | 1.61.94 Chromium: 120.0.6099.56 (Official Build) (64-bit)
-- | --
Revision | 72759647494f071d653f8a61465fadf5f361b06e
OS | Linux



#### 1. Verified imported bookmarks via below methods are shown in the bookmarks sidebar panel
    
<details>

![image](https://github.com/brave/brave-browser/assets/34715963/a22eb423-521f-4450-bbf2-fae0653846fd)


</details>

#### 2.  Verified bookmark dialog when clicked on bookmark next to URL bar
 
<details>

![image](https://github.com/brave/brave-browser/assets/34715963/d78c79c4-048b-43c8-a8a5-75409bb1c134)
![image](https://github.com/brave/brave-browser/assets/34715963/5fd4661f-aa01-41e5-9841-e1c913a2bfd3)


</details>

#### 3. Verified Search functionality in the bookmarks bar sidepanel worked as expected.

<details>

![image](https://github.com/brave/brave-browser/assets/34715963/36bc544d-f7e6-439a-bad2-0871628df6a7)


</details>

#### 5. Clicked on Bookmarks manager button in the bookmarks bar sidepanel

<details>

![image](https://github.com/brave/brave-browser/assets/34715963/e7180fa1-e614-4917-a165-c5db4f230c19)


</details>

#### 6.  Bookmarks menu 

<details>  

Sorting
![image](https://github.com/brave/brave-browser/assets/34715963/46d607c0-99c0-40b4-ac46-dd7de212702a)
![image](https://github.com/brave/brave-browser/assets/34715963/719c431a-b4da-4da0-a87b-bd69674b5fb1)
![image](https://github.com/brave/brave-browser/assets/34715963/a502b05d-45d4-482c-8736-f513c2bf3aeb)
![image](https://github.com/brave/brave-browser/assets/34715963/d613c16c-2e5b-496c-a337-832b054ecbfc)
![image](https://github.com/brave/brave-browser/assets/34715963/3496a5e6-651f-4a50-b5c0-7b45bd9b518b)


</details>

#### 7. Bookmarks Visual view

<details>    

![image](https://github.com/brave/brave-browser/assets/34715963/2aac4c81-83d4-44d4-b1cf-67881436ea18)
![image](https://github.com/brave/brave-browser/assets/34715963/440cd4b8-ff1f-4259-80da-c75e8bcff3b5)


</details>

#### 8.  Bookmarks pencil/Edit  

<details>

![image](https://github.com/brave/brave-browser/assets/34715963/1264d8ce-2bfe-4648-ae51-9ca884507a3f)
![image](https://github.com/brave/brave-browser/assets/34715963/9cb587ad-363e-4610-915d-aa9974d66df6)
![image](https://github.com/brave/brave-browser/assets/34715963/30711547-a55c-4773-a75a-1d76b9c69093)


</details>

#### 9.  Ellipsis menu for bookmarks -  
 
<details>

![image](https://github.com/brave/brave-browser/assets/34715963/1bf9292e-68ae-4230-a499-3bbc18119f48)
![image](https://github.com/brave/brave-browser/assets/34715963/4abfa6aa-c102-4492-b747-bb2700d8fa24)


</details>

#### 10. Drag and drop bookmarks within the bookmarks bar sidepanel

<details>



</details>

#### 11. Open Sidepanel to see all bookmarks via `All Bookmarks` folder

<details>

![image](https://github.com/brave/brave-browser/assets/34715963/6c341f83-1d24-4e88-8810-b6f3c6f02b08)
![image](https://github.com/brave/brave-browser/assets/34715963/5ee40ad3-a1c7-4368-a537-63ca029c1113)


</details>

#### 12. Dark theme

<details>

![image](https://github.com/brave/brave-browser/assets/34715963/2a7043a4-57df-44cd-9e7a-7069a236be5b)


</details>

**Comment by N1k41d0** [comment]
Why was the "more" button removed from the bookmark dialog ? it's now one extra click to pick a folder that's not in the recently picked bookmark folders.

**Comment by kjeske** [comment]
The previous bookmarks view in sidebar was perfect, now it got those folders, same as in chrome. It's much more useful if you see full tree, like it used to be. With folders you loose your context once you go to a folder. Why such a move?
