### ISSUE TITLE
Updated horizontal tabs do not extend to the top of the screen in when window is maximized

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#34038]
## Description 

Currently, on Windows, when Brave is maximized, tabs extend to the very top of the screen so that user can select a tab by moving their pointer quickly to the top.

When the updated horizontal tabs flag is enabled, tabs do not extend to the very top of the screen.

## Steps to Reproduce

   1. Enable `#brave-horizontal-tabs-update`
   2. Restart the browser
   3. Maximize the window

## Actual result:

Tabs are not selectable at the top of the screen.

## Expected result:

Tabs should be selectable at the top of the screen.

**Comment by bsclifton** [comment]
Re-opening after https://github.com/brave/brave-core/pull/20862

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.62.38 Chromium: 119.0.6045.134 (Official Build) nightly (64-bit)
-- | --
Revision | 63d368dd4d01900c1f3f056b6371210d10899d5a
OS | Windows 11 Version 22H2 (Build 22621.2428)
```

1. Installed 1.62.35
2. launched Brave
3. opened `brave://flags` in a new tab
4. enabled #brave-horizontal-tabs-update
5. restarted the browser
6. opened several tabs
7. maximized the window

### Confirmed tabs are selectable at the top of the screen.

https://github.com/brave/brave-browser/assets/98358127/3750edcf-d7ea-40de-ba77-fe943cf16cfa

**Comment by kjozwiak** [comment]
The above requires `1.61.75` or higher for `1.61.x` verification 👍 Removing `QA Pass-Win64` as the above will need to be verified on `1.61.x` now that it's been uplifted into `1.61.x`. Used https://github.com/brave/brave-browser/issues/34038#issuecomment-1806504391 as the verification for Nightly as per https://github.com/brave/brave-core/pull/20947#pullrequestreview-1728400025.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.61.75 Chromium: 119.0.6045.134 (Official Build) beta (64-bit)
-- | --
Revision | 1b1191cb2465b2b90a5e8fea4a63aed1cfca47f5
OS | Windows 11 Version 22H2 (Build 22621.2428)
```

1. Installed 1.61.75
2. launched Brave
3. opened `brave://flags` in a new tab
4. verified #brave-horizontal-tabs-update enabled by default
5. opened several tabs
6. maximized the window

### Confirmed tabs are selectable at the top of the screen when the window is maximized

https://github.com/brave/brave-browser/assets/98358127/2f972839-9dd7-408a-aea5-8de93ab2d3b5

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.61.75 Chromium: 119.0.6045.134 (Official Build) beta (64-bit)
-- | --
Revision | 1b1191cb2465b2b90a5e8fea4a63aed1cfca47f5
OS | Windows 11 Version 22H2 (Build 22621.2428)
```

1. Installed 1.61.75
2. launched Brave
3. opened `brave://flags` in a new tab
4. verified #brave-horizontal-tabs-update is enabled by default
5. restarted the browser
6. opened several tabs
7. maximized the window

### Confirmed tabs are selectable at the top of the screen when the window is maximized


https://github.com/brave/brave-browser/assets/98358127/7196347d-8490-4f7e-a369-7b4adda09fef

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.61.83 Chromium: 119.0.6045.163 (Official Build) beta (64-bit) 
Revision	f5a497784a959e96317dc946d9086098d8fa6c50
OS	Linux
```
