### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Ziller321** [brave/brave-browser#34032]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.58.137 Chromium: 117.0.5938.153
Operating System: Mac OS X 13.3.1

URL (if applicable) where crash occurred: https://iltalehti.fi

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. navigate to page, will crash immediately 
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/69dd0e00-be6a-ef0a-0000-000000000000

**Comment by rebron** [comment]
@Ziller321 Can you update to the latest 1.60.110 and let us know if you're still experiencing this crash.
