### ISSUE TITLE
iOS crash logs seem to have corruption in Rust code

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#34045]
## Description 
Seems to have started with 1.57.x - but iOS crash logs are having rust symbols and not showing the true error.

Here's an example by @kylehickinson:
```
Thread 28 Crashed:
0   BraveCore                     	0x0000000105d21b54 gimli::read::unit::UnitHeader$LT$R$C$Offset$GT$::address_size::hd773f6fd2bfe7275 + 27588
1   BraveCore                     	0x0000000105d21a98 gimli::read::unit::UnitHeader$LT$R$C$Offset$GT$::address_size::hd773f6fd2bfe7275 + 27400
2   BraveCore                     	0x0000000105d21b70 gimli::read::unit::UnitHeader$LT$R$C$Offset$GT$::address_size::hd773f6fd2bfe7275 + 27616
3   BraveCore                     	0x0000000105d23550 gimli::read::unit::UnitHeader$LT$R$C$Offset$GT$::address_size::hd773f6fd2bfe7275 + 34240
4   BraveCore                     	0x0000000105d837d0 brave_wallet::EthereumProviderImpl::~EthereumProviderImpl() + 220 (ethereum_provider_impl.cc:139)
5   BraveCore                     	0x0000000105d83840 brave_wallet::EthereumProviderImpl::~EthereumProviderImpl() + 12 (ethereum_provider_impl.cc:135)
```

In this particular instance, there is a `CHECK()` failing and it's masked by the `gimli::read::unit::UnitHeader` lines. 

Per @kylehickinson - the crash is pulled in from Xcode and symbolized using symbols uploaded with the build on AppStore Connect

We're having trouble narrowing down root cause for https://github.com/brave/brave-ios/issues/8334 - there is an attempted fix, but because the call stack is corrupt, it's hard to know the exact condition it's failing on.

**Comment by iccub** [comment]
Closing. Looks like Apple fixed something on their end and the logs are visible again
