### ISSUE TITLE
Leo icon is overlapping on the `Enable suggested questions?` text in few locales

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#34042]
## Description 

Fouund while testing https://github.com/brave/brave-browser/issues/34017
Leo icon is overlapping on the `Enable suggested questions?` in few locales

## Steps to Reproduce

   1. Set OS locale to France
   2. Clean profile 1.60.110
   3. Open a site 
   4. Click on Leo icon via Sidebar
   5. Click on Accept button 
   6. Leo icon is overlapping on the `Enable suggested questions?` text in few locales

## Actual result:

Leo icon is overlapping on the `Enable suggested questions?` text in few locales
![image (4)](https://github.com/brave/brave-browser/assets/38657976/d913f34d-b138-4253-9cbc-19bf451148ad)

## Expected result:
Icon should not overlap on text

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.60.110 Chromium: 119.0.6045.105 (Official Build) (64-bit)
-- | --
Revision | 0bb6e7a81aed340b5a9e8b752c1cf92768257c40
OS | Windows 10 Version 22H2 (Build 19045.3570)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? NA

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @mkarolin @petemill

**Comment by bbondy** [comment]
This will become invalid when we implement https://github.com/brave/brave-browser/issues/33575 and that is higher priority. So I'm going to mark this as wontfix since it won't be like this for long.
