### ISSUE TITLE
Searching and viewing verified pub video doesn't show favicon in BR panel/a-c list

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#3404]
## Description 

Searching and viewing verified pub video doesn't show favicon in BR panel/a-c list

## Steps to Reproduce

   1. Enable rewards from BR panel
   2. Visit twitch.tv and search for `neoness007` or `ekan1975`
   3. Watch any clips from either of the publisher
   4. Check BR panel/a-c list, publisher favicon is not shown on both locations

## Actual result:

![image](https://user-images.githubusercontent.com/17010094/52950115-2599cb80-33a4-11e9-8b1a-9861f2807a92.png)
![image](https://user-images.githubusercontent.com/17010094/52950198-698cd080-33a4-11e9-80a5-9407845c1455.png)

## Expected result:
![image](https://user-images.githubusercontent.com/17010094/52952226-f38b6800-33a9-11e9-82f2-0ec0be4c8e56.png)

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.60.34 Chromium: 72.0.3626.109 (Official Build) beta(64-bit)
-- | --
Revision | fae8db7ab9280fa6704a59980263c804f809ebd5-refs/branch-heads/3626@{#857}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

cc: @brave/legacy_qa @NejcZdovc 
@GeetaSarvadnya was able to reproduce it on Windows 10 x64
Found while verifying #3324

**Comment by GeetaSarvadnya** [comment]
Reproducible on Windows 10 x64

A-C table - No favicon display for verified twitch pubs
![image](https://user-images.githubusercontent.com/38657976/52957337-736bff00-33b7-11e9-8a4a-ab5c65968eae.png)
BR Panel - No favicon display for verified twitch pubs

![image](https://user-images.githubusercontent.com/38657976/52957397-93032780-33b7-11e9-8262-11f605dbf2d1.png)

**Comment by LaurenWags** [comment]
I searched for xondak and viewed a VOD and got his verified favicon - using:

Brave | 0.60.28 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Mac OS X

![screen shot 2019-02-18 at 1 28 22 pm](https://user-images.githubusercontent.com/28145373/52970262-371dac00-3381-11e9-8174-24789db2dfeb.png)

**Comment by srirambv** [comment]
I can still reproduce with `neoness007` and `ekan1975` but not for `xondak` on `0.60.40` RC build

**Comment by LaurenWags** [comment]
Maybe related to https://github.com/brave/brave-browser/issues/3044 ?

**Comment by LaurenWags** [comment]
I can reproduce for neoness007 fairly consistently but not ekan1975:
![screen shot 2019-02-19 at 5 32 39 pm](https://user-images.githubusercontent.com/28145373/53052362-85f44000-346c-11e9-8fde-989a93b1b1d0.png)


Brave | 0.60.44 Chromium: 72.0.3626.109 (Official Build) (64-bit)
-- | --
Revision | fae8db7ab9280fa6704a59980263c804f809ebd5-refs/branch-heads/3626@{#857}
OS | Mac OS X

**Comment by kjozwiak** [comment]
Ran into a similar issue when going through `0.60.44 Chromium: 72.0.3626.109`.

**Example of the issue occurring:**

<img width="638" alt="screen shot 2019-02-20 at 3 29 27 pm" src="https://user-images.githubusercontent.com/2602313/53122698-37ef4300-3525-11e9-88f6-00d4a49f259b.png">

**Example of expected results:**

<img width="639" alt="screen shot 2019-02-20 at 3 33 45 pm" src="https://user-images.githubusercontent.com/2602313/53122710-4178ab00-3525-11e9-9f37-030d790d1ece.png">

**Comment by NejcZdovc** [comment]
Note to the issue is that you need to open panel to get favicon. From just regular watching clips and live streams we don't get favicon. We only get it for VOD's

**Comment by GeetaSarvadnya** [comment]
Reproducible on Windows 10 x64 - `0.63.5`


Brave | 0.63.5 Chromium: 73.0.3683.67 (Official Build) dev (64-bit)
-- | --
Revision | a83fd4f3207ae83412d329a9ca1239dd1e068345-refs/branch-heads/3683@{#760}
OS | Windows 10 OS Build 17134.523



![image](https://user-images.githubusercontent.com/38657976/54301306-b438eb80-45e4-11e9-8d13-2b038eb4e086.png)

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.63.14 Chromium: 73.0.3683.75 (Official Build) dev(64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Mac OS X

![Screen Shot 2019-03-20 at 2 17 12 PM](https://user-images.githubusercontent.com/28145373/54709055-234d9d00-4b1b-11e9-93da-1feafaca2fbe.png)

![Screen Shot 2019-03-20 at 2 18 39 PM](https://user-images.githubusercontent.com/28145373/54709062-29437e00-4b1b-11e9-9d22-8dc663c5b391.png)
