### ISSUE TITLE
Update Wallet Account Blockies to new Design

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#34052]
## Description 

We need to update the Wallet `Account` Blockies to the new design

![image](https://github.com/brave/brave-browser/assets/40611140/25ffca7c-933c-40a0-8b9e-0b0ccca8eaea)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.62.146 Chromium: 120.0.6099.234 (Official Build) beta (64-bit)
-- | --
Revision | 85d26e25365bbea90074b7bc40ab0c89bbbf26e8
OS | Windows 11 Version 23H2 (Build 22631.3007)

- Verified steps from [brave/brave-core#20879](https://github.com/brave/brave-core/pull/20879)
- Verified account blockies are as per new design and is shown in all the places 

Portfolio | Accounts | Portfolio Settings
-- | -- | --
![image](https://github.com/brave/brave-browser/assets/17010094/7df9bddf-6a12-4e48-9544-563ff31b9952) | ![image](https://github.com/brave/brave-browser/assets/17010094/dd7003aa-111b-40d2-8bc2-c0834778fcbb) | ![image](https://github.com/brave/brave-browser/assets/17010094/63df8997-9c5c-4baf-a04d-10767f12733a)
