### ISSUE TITLE
The string on `Rate Brave` bottom sheet notification doesn't fit the screen in Russian language

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#34051]
## Description 

The string on the `Rate Brave` bottom sheet notification doesn't fit the screen in the `Russian language`.

## Steps to reproduce 

   1. Change device language to `Russian`
   2. Launch Brave
   3. Three-dot menu > Settings
   4. Scroll to the bottom and find `Rate Brave`/`Оценить Brave` > Tap it > Observe

## Actual result 

The string on the `Rate Brave` bottom sheet notification doesn't fit the screen in the Russian language.

|Russian|English|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/e77faaf0-108f-4352-a462-9315b729c395) | ![2](https://github.com/brave/brave-browser/assets/128532965/67a7147e-9edc-4266-8c3e-388b3c46ecbd) |

## Expected result

All strings must fit the screen.

## Issue reproduces how often 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? YES
- Can you reproduce this issue with the current Play Store Beta version? YES 
- Can you reproduce this issue with the current Play Store Nightly version? YES

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: Any
   
## Brave version

```
Brave build: 1.60.110
Chromium: 119.0.6045.105 (Official Build) (64-bit)
Revision: 0bb6e7a81aed340b5a9e8b752c1cf92768257c40
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
@deeppandya can you please add the required labels:
- `release-notes/exclude` or `release-notes/include`

Thanks!

**Comment by hffvld** [comment]
Verified on `Galaxy Z Fold 6` and `Pixel 7` using version(s):
```
Device/OS: 
- Galaxy Z Fold 6 / q6quew-user 14 UP1A.231005.007 release-keys
- Pixel 7 / panther_beta-user 15 AP41.240823.009 release-keys
Brave build: 1.72.90 
Chromium: 130.0.6723.70 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the STR/TP from https://github.com/brave/brave-browser/issues/34051#issue-1973194827
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the strings on the `Rate Brave` pop-up fit the screen for some languages like Russian and Ukrainian.

---------------------------

|Pixel 7|Z Fold 6|
|:-:|:-:|
| ![1](https://github.com/user-attachments/assets/f30253ea-2967-4c82-9bf0-a549f3dbbe32) | ![2](https://github.com/user-attachments/assets/7d2f78e2-ce18-4bdd-a8f1-3faa439801ef) |
| ![1](https://github.com/user-attachments/assets/0c02dffb-5564-4cbb-92f7-8c541c7ad13f) | ![2](https://github.com/user-attachments/assets/3b056a96-d75f-4c21-a18d-98d4dcd570e8) |
