### ISSUE TITLE
Rendering Issue for Ligature-Based Scripts

### ISSUE THREAD

**Issue by ng4mf** [brave/brave-browser#3405]
Ligatures don't seem to render properly for some scripts in the dev build. I have specifically tested with Devanagari, an Indic script, though the problem may also exist for other scripts that heavily use ligatures. I've tested on Lubuntu 18.04.1 LTS.

This was an open issue on the Muon based version, and I've found it is still an issue. 
Here is the link to the old issue: https://github.com/brave/browser-laptop/issues/14569

## Steps to Reproduce

Dev Issue:
In the Wikipedia search bar, type क + ् + र (0x915 + 0x94D + 0x930)

## Actual result:

Brave:
![image](https://user-images.githubusercontent.com/6548274/52963830-d38a8300-336e-11e9-99a3-94a80270cfa1.png)

## Expected result:
Firefox:
![image](https://user-images.githubusercontent.com/6548274/52964279-e782b480-336f-11e9-9229-0b5d9687fc49.png)

## Reproduces how often: 

Easily reproduced for either dev or beta releases

## Brave version (brave://version info)

Dev Release:
Brave     | 0.61.22 Chromium: 72.0.3626.81 (Official Build) dev (64-bit)
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS          | Linux

Beta Release:
Brave     | 0.59.35 Chromium: 72.0.3626.81 (Official Build) (64-bit)
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS          | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 

No

- Is the issue reproducible on the latest version of Chrome? 

Yes

**Comment by srirambv** [comment]
If the issue is being reproduced on Chrome as well then this is more likely an upstream issue that needs to be fixed at Chromium level. 

cc: @bbondy to reopen if this is something we can fix
