### ISSUE TITLE
Tor requests in extensions (Bitwarden) blocked by client since 1.59.xxx

### ISSUE THREAD

**Issue by jurglic** [brave/brave-browser#34057]
## Description 
Extensions can no longer do requests over TOR (blocked by client).
For example, bitwarden extension cannot connect to self-hosted bitwarden instance over tor since stable 1.59, but it still works in 1.58.137. 

## Steps to Reproduce

   1. Install [brave browser 1.59](https://github.com/brave/brave-browser/releases/tag/v1.59.124) and [bitward extension](https://chrome.google.com/webstore/detail/bitwarden-free-password-m/nngceckbapebfimnlniiiahkandclblb).
   2. Open bitwarden extension and choose "Logging in on self-hosted", then input any tor address as server URL (e.g. http://s4k4ceiapwwgcm3mkb6e4diqecpo7kvdnfr5gg7sph7jjppqkvwwqtyd.onion/) and save.
   3. Then input any email address and password, and try to login. Observe instant "Failed to fetch" error.
   4. Additionally you can enable "developer mode" in [extensions settings](brave://extensions/), and then open "Inspect views" under Bitwarden extension.
   5. Try to log in with random email/password and observe "Error: blocked by client" in developer console for bitwarden extension.

## Actual result:
Error: blocked by client.

## Expected result:
It should try to connect to the server without being blocked by the client.

## Brave version (brave://version info)
[Version 1.59.111 Chromium (Official Build) (x86_64)] tested on macos 14.1.

## Version/Channel Information:
- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes
- What is latest version that you cannot reproduce this issue? v1.58.137

## Other Additional Information:
- Does the issue resolve itself when disabling Brave Shields? no
- Does the issue resolve itself when disabling Brave Rewards? no
- Is the issue reproducible on the latest version of Chrome? I don't know

## Miscellaneous Information:
Normally you need system-wide tor proxy enabled on connected network.

**Comment by fmarier** [comment]
@jurglic I think what you're asking is for [a way to enable `.onion` URLs to work outside of private windows with Tor](https://github.com/brave/brave-browser/issues/33735)?

**Comment by jurglic** [comment]
> @jurglic I think what you're asking is for [a way to enable `.onion` URLs to work outside of private windows with Tor](https://github.com/brave/brave-browser/issues/33735)?

Yes. The proposed setting from #33735 would allow this to work as it did before!

**Comment by fmarier** [comment]
Great, let's track it in https://github.com/brave/brave-browser/issues/33735 then.
