### ISSUE TITLE
SKUS enhancement: Submit and fetch credentials using new endpoints with request ids

### ISSUE THREAD

**Issue by evq** [brave/brave-browser#34069]
## Description 

This issue tracks an enhancement to the SKU SDK, whereby it utilize new APIs which are under development. These new APIs are parameterized by item id and request id and are a stepping stone toward better multi-device support.

**Comment by stephendonner** [comment]
@evq: what do you have in mind for a testplan, here?

Would a solid regression test (anything specific to look out for/test extra well?) suffice?

cc @brave/qa-team

**Comment by stephendonner** [comment]
Also: will this ride the trains, or would we uplift (assuming all testing goes well)?

**Comment by evq** [comment]
@stephendonner a general regression test covering `talk && ( vpn || leo )` should suffice. for now I'd say let's have it ride the trains

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```

```

**Comment by stephendonner** [comment]
Preliminary testing revealed the new endpoints aren't yet up: this is `QA/Blocked` until https://github.com/brave-intl/bat-go/pull/2183 is merged.

**Comment by MadhaviSeelam** [comment]
Encountered same with VPN in `1.63.45` nightly.  

https://github.com/brave/brave-browser/assets/98358127/4c4f4988-8a00-4bf2-a25a-186b6d60f9d0

**Comment by kjozwiak** [comment]
The above requires `1.62.145` or higher for `1.62.x` verification 👍

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using 

```
Brave | 1.62.145 Chromium: 120.0.6099.234 (Official Build) beta (64-bit)
-- | --
Revision | 431a4319968af133d1c7792ad66437061f95dd83
OS | Windows 10 Version 22H2 (Build 19045.3930)
```
