### ISSUE TITLE
Deposit screen allows selecting Filecoin testnet account for Filecoin mainnet

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#34065]
## Description 

Deposit screen allows selecting Filecoin testnet account for Filecoin mainnet. This should not be allowed

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.62.137 Chromium: 120.0.6099.217 (Official Build) beta (64-bit)
-- | --
Revision | `92c88bc64f4e5c37e60774394436493726ad7d63`
OS | Windows 11 Version 23H2 (Build 22631.2861)

- Verified steps from [brave/brave-core#20817](https://github.com/brave/brave-core/pull/20817)
- Verified Testnet FIL is not an available option when the deposit assets list is filtered to Filecoin mainnet.
- Verified Testnet FIL deposits preloads a testnet Filecoin address when a testnet account is present during deposit flow
- Verified Mainnet FIL is not be an available option when the deposit assets list is filtered to Filecoin testnet.
- Verified Mainnet FIL deposits preloads mainnet Filecoin address when mainnet account is present during deposit flow

https://github.com/brave/brave-browser/assets/17010094/2a79944b-ba6a-4862-a312-1e9aaf107d58
