### ISSUE TITLE
Sort Assets By Value on Account Details Screen

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#34064]
## Description 

We need to sort `Assets` by `Value` on the `Account Details` screen

![Screenshot 44](https://github.com/brave/brave-browser/assets/40611140/45318a3f-203c-4157-97b4-caec07e22779)

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.62.130 Chromium: 120.0.6099.199 (Official Build) beta (64-bit)
-- | --
Revision | `6d589c6dc0f3489830d40332c82cdd5597e41c88`
OS | Windows 11 Version 23H2 (Build 22631.2861)

- Verified steps from [brave/brave-core#20816](https://github.com/brave/brave-core/pull/20816)
- Verified asset are sorted by fiat value in Account details screen
![brave_ti4Lj7fDU0](https://github.com/brave/brave-browser/assets/17010094/e9e6dfe9-07ad-4398-94fa-f2d1439f3e17)

---------------------

**Verification passed on**

Brave | 1.62.130 Chromium: 120.0.6099.199 (Official Build) beta (64-bit)
-- | --
Revision | `6d589c6dc0f3489830d40332c82cdd5597e41c88`
OS | Linux

- Verified steps from [brave/brave-core#20816](https://github.com/brave/brave-core/pull/20816)
- Verified asset are sorted by fiat value in Account details screen
![Fiatvalue](https://github.com/brave/brave-browser/assets/17010094/648150b3-a0af-4348-8290-7c6f70b21bc3)

---------------------

**Verification passed on**

Brave | 1.62.130 Chromium: 120.0.6099.199 (Official Build) beta (arm64)
-- | --
Revision | `6d589c6dc0f3489830d40332c82cdd5597e41c88`
OS | macOS Version 14.2.1 (Build 23C71)

- Verified steps from [brave/brave-core#20816](https://github.com/brave/brave-core/pull/20816)
- Verified asset are sorted by fiat value in Account details screen
![image](https://github.com/brave/brave-browser/assets/17010094/87956ecf-0a96-4087-b21d-f7915a4251e8)
