### ISSUE TITLE
Link to support.brave.com from the private windows with tor setting

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#34076]
This setting in `brave://settings/privacy`:
![Screenshot from 2023-11-02 15-36-08](https://github.com/brave/brave-browser/assets/167821/db955898-f1b0-49e9-8a89-d218ede88ba1)

should have a _Learn more_ link to https://support.brave.com/hc/en-us/articles/360018121491-What-is-a-Private-Window-with-Tor-Connectivity-

**Comment by yashchaddha** [comment]
Hi @fmarier , I would like to contribute on this issue, could I please get assigned to it?

**Comment by fmarier** [comment]
@yashchaddha Sorry, I ended up fixing it as I was working on something else. I should not have used the `good first issue` label for it.

**Comment by yashchaddha** [comment]
No problem @fmarier , glad to know the issue was fixed.

Would look for another one until then.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.62.97 Chromium: 120.0.6099.56 (Official Build) beta (x86_64)
-- | --
Revision | 9561bb49dc23c407275af722586f045356609329
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.62.97`
2. launched Brave
3. opened `brave://settings/privacy`
4. confirmed Learn more` link beneath `Private Window with Tor`
5. clicked on the above

### Confirmed the link went to `https://support.brave.com/hc/en-us/articles/360018121491-What-is-a-Private-Window-with-Tor-Connectivity-`

example | example
---------|---------
<img width="1424" alt="Screen Shot 2023-12-06 at 4 27 45 PM" src="https://github.com/brave/brave-browser/assets/387249/ca6faa0a-a7a9-4658-99ac-24d9e5a2a6e0"> | <img width="1424" alt="Screen Shot 2023-12-06 at 4 27 55 PM" src="https://github.com/brave/brave-browser/assets/387249/fd38bf92-9265-4ab1-b8c8-50b1e4aa3536">
