### ISSUE TITLE
Problematic first party elements are not blocked by Shields in Standard mode

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#34081]
This was previously fixed in https://github.com/brave/brave-core/pull/19946, but since that was reverted it has come up again on a few sites such as:

- `dailymail.co.uk`

![image](https://github.com/brave/brave-browser/assets/22821309/5066feb3-75da-4f36-b287-a1c446d3bdea)

- `imdb.com`

![image](https://github.com/brave/brave-browser/assets/22821309/e40f5e1f-97a9-44af-a7b8-94c815f04cbf)

- `politico.com`

![image](https://github.com/brave/brave-browser/assets/22821309/17ba3543-44b6-455d-b82c-eab83ef153e7)

**Comment by kjozwiak** [comment]
The above requires `1.60.114` or higher for `1.60.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.60.114 Chromium: 119.0.6045.124 (Official Build) (64-bit)
-- | --
Revision | 99a34933fc6a44fdfe52dea41341927bbce3549a
OS | Windows 10 Version 22H2 (Build 19045.3570)

```

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using the following version:

```
Brave	1.60.116 Chromium: 119.0.6045.134 (Official Build) (32-bit) 
Revision	def53af41c7a126b2def06e7f6aa2063ad5364e7
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

dailymail.co.uk | imdb.com | Politico.com
-|-|-
![Screenshot 2023-11-09 at 11 20 08 AM](https://github.com/brave/brave-browser/assets/17885425/9441cca4-a272-4744-8628-207b8ceb8bd9) | ![Screenshot 2023-11-09 at 11 21 34 AM](https://github.com/brave/brave-browser/assets/17885425/bb2c4cc2-3cc2-42d9-829f-78d15614f55f) | ![Screenshot 2023-11-09 at 11 22 39 AM](https://github.com/brave/brave-browser/assets/17885425/c9599af2-0b03-4ea4-8b3e-b49e2eaa416d)
