### ISSUE TITLE
Ad notifications sometimes presented to user when Ads toggle is off - follow up to 2972

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#3408]
## Description 
Follow up to #2972 

Found an additional scenario when Ads are presented to the user when Ads toggle is off in the UI. 

If you toggle Rewards off, close and relaunch Brave, then toggle Rewards on, UI will show Ads as off, but in fact, Ads Service is running (you are able to see Ads Service messages in terminal if you've launched with the correct flags) and you will be presented with Ad notifications.

Seems as though there are two problems here:
1. When Rewards are toggled back on after browser restart, Ads are showing as off in the UI.
2. Ads Service isn't respecting UI toggle which is set to off.

## Steps to Reproduce

1. Launch Brave with a clean profile - I also used these flags `--enable-logging=stderr --vmodule=brave_ads=3 --brave-ads-debug`
2. Enable Rewards, Ads are enabled by default as expected.
3. Visit some sites - you will see AdsService messages in terminal as expected since Ads are on.
4. Toggle Rewards off.
5. Visit some sites, you will not see AdsService messages in terminal as expected since Ads are off.
6. Toggle Rewards back on.
7. Visit some sites, you will see AdsService messages in terminal as expected since Ads are on.
8. Toggle Rewards off.
9. Close Brave.
10. Relaunch Brave (I used the same flags as before)
11. Toggle Rewards on again.

## Actual result:
Ads toggle is off in UI, but if you visit pages you will see AdsService messages in the terminal. After a bit of browsing you will also start to get Ad notifications.

<img width="1207" alt="screen shot 2019-02-18 at 4 03 44 pm" src="https://user-images.githubusercontent.com/28145373/52976408-66d7ae80-3397-11e9-9776-fbb9d94444bf.png">

## Expected result:
Since Ads were on before Rewards was disabled, I'd expect toggling Rewards on to turn on Ads. However, if Ads toggle is off in the UI, then I should not be presented with Ad notifications.

## Reproduces how often: 
easily

## Brave version (brave://version info)

Brave | 0.60.28 Chromium: 72.0.3626.96 (Official Build) beta(64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Mac OS X

### Reproducible on current release: no, Ads are not available on 0.59.x
- Does it reproduce on brave-browser dev/beta builds? reproduced on beta 0.60.x

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
cc @brave/legacy_qa

**Comment by btlechowski** [comment]
Reproduced on Windows 7

Brave | 0.60.29 Chromium: 72.0.3626.96 (Official Build) beta (64-bit)
-- | --
Revision | 84098ee7ef8622a9defc2ef043cd8930b617b10e-refs/branch-heads/3626@{#836}
OS | Windows 7

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/brave-core/pull/1640

(Note, this should be re-verified on the latest version of `0.60`) cc: @LaurenWags @jsecretan

**Comment by kjozwiak** [comment]
@ryanml we just released `0.60.48` today which bumped the CR from `72.0.3626.119` to `72.0.3626.121`. Was there any work that needed to go into that build that's related to this? Or did `0.60.48` just need a recheck?

**Comment by ryanml** [comment]
@kjozwiak `0.60.48` should just need a recheck

**Comment by kjozwiak** [comment]
@RyanJarv sounds good 👍 I'll give this a check tomorrow. @LaurenWags mind giving this another recheck on `0.60.48` as well?

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.60.48 Chromium: 72.0.3626.121 (Official Build) (64-bit)
-- | --
Revision | da3787ba355f18db7db52abf75c42afb408d656f-refs/branch-heads/3626@{#883}
OS | Mac OS X

- Verified launching with `/Applications/Brave\ Browser.app/Contents/MacOS/Brave\ Browser --enable-logging=stderr --vmodule=brave_ads=3 --log-level=0`, enabling Rewards, and browsing did not show any `AdService Event Log` messages in terminal
- Verified turning Rewards off and browsing still did not show any `AdService Event Log` messages in terminal
- Verified closing/relaunching Brave, enabling Rewards again, and browsing did not show any `AdService Event Log` messages in terminal
- Verified to way to toggle Ads on in UI
- Verified no Ad notifications were presented while browsing
