### ISSUE TITLE
Add Rewards conversion P3A metrics for Android

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#34082]
Add additional Rewards metrics for Android only:

If you triggered the Rewards panel as a non-rewards user or a new Rewards user this week, did you enable Rewards?
`Brave.Rewards.MobileConversion`

0. No
1. Yes

If you triggered the Rewards panel at least once as a Rewards user in the last 7 days, how many times did you trigger the panel?
`Brave.Rewards.MobilePanelCount`

0. 1-5
1. 6-10
2. 11-50
3. 51+

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.62.99`

### Brave.Rewards.MobileConversion

<details>
<summary>Brave.Rewards.MobileConversion = No</summary>


</details>

<details>
<summary>Brave.Rewards.MobileConversion = Yes</summary>


</details>

### Brave.Rewards.MobilePanelCount

<details>
<summary>Brave.Rewards.MobilePanelCount = 0</summary>

</details>

<details>
<summary>Brave.Rewards.MobilePanelCount = 1</summary>

</details>

<details>
<summary>Brave.Rewards.MobilePanelCount = 2</summary>

</details>

<details>
<summary>Brave.Rewards.MobilePanelCount = 3</summary>

</details>
