### ISSUE TITLE
Wallet Account Icon Stack missing Dark Theme Text Color

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#34093]
## Description 

The `Icon Stack` for accounts on the `Accounts` tab is missing `Dark Theme` color for the text

## Steps to Reproduce

   1. Go to the `Accounts` tab and look at your list of accounts that have tokens
   2. The `Text` for the additional `Tokens` in the `Icon Stack` does not have a `Dark Theme` color

## Actual result:

![Screenshot 47](https://github.com/brave/brave-browser/assets/40611140/f2ef453f-9674-49de-8988-5d6d34ffaee0)

## Expected result:

![Screenshot 48](https://github.com/brave/brave-browser/assets/40611140/97d4a78a-9da7-4fb2-89c5-d0ecaf88c58a)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.62.130 Chromium: 120.0.6099.199 (Official Build) beta (64-bit)
-- | --
Revision | `6d589c6dc0f3489830d40332c82cdd5597e41c88`
OS | Windows 11 Version 23H2 (Build 22631.2861)

- Verified steps from [brave/brave-core#20833](https://github.com/brave/brave-core/pull/20833)
- Verified Wallet account icon stack text is shown in dark theme
![brave_2n0ktN8MZD](https://github.com/brave/brave-browser/assets/17010094/40b69e28-d906-412c-b3aa-520dc1644660)

---------------------

**Verification passed on**

Brave | 1.62.130 Chromium: 120.0.6099.199 (Official Build) beta (64-bit)
-- | --
Revision | `6d589c6dc0f3489830d40332c82cdd5597e41c88`
OS | Linux

- Verified steps from [brave/brave-core#20833](https://github.com/brave/brave-core/pull/20833)
- Verified Wallet account icon stack text is shown in dark theme
![stack](https://github.com/brave/brave-browser/assets/17010094/caf3a7cd-5a4d-48d5-9712-c1eb1fc86438)


---------------------

**Verification passed on**

Brave | 1.62.130 Chromium: 120.0.6099.199 (Official Build) beta (arm64)
-- | --
Revision | `6d589c6dc0f3489830d40332c82cdd5597e41c88`
OS | macOS Version 14.2.1 (Build 23C71)

- Verified steps from [brave/brave-core#20833](https://github.com/brave/brave-core/pull/20833)
- Verified Wallet account icon stack text is shown in dark theme
![image](https://github.com/brave/brave-browser/assets/17010094/e47d8536-d2a3-4138-940a-183a89a8930c)
