### ISSUE TITLE
Context indicator changes

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#34099]
- [ ] Change the connected to page UI to be less confusing. It will now be a toggle underneath and glued to the input box. Default to ON
- [ ] If the user turns it off, remove the Summarize this page button
- [ ] After context is included in a conversation the switch should disappear and it should go into the scrollable history instead.

![image (55)](https://github.com/brave/brave-browser/assets/831718/abc020cc-1477-4d70-a601-4e2bb6ea078e)
<img width="860" alt="Screenshot 2023-11-15 at 12 52 25 PM" src="https://github.com/brave/brave-browser/assets/831718/63be4c1d-d1c0-497e-b5da-0b5162c57aaf">

<img width="589" alt="Screenshot 2023-11-15 at 12 53 16 PM" src="https://github.com/brave/brave-browser/assets/831718/3331ec96-1774-4d24-a3cc-faf55ba489b8">

**Comment by aguscruiz** [comment]
Figma link for reference
https://www.figma.com/file/m0Gdbf0wtqyfEFGm32VLLc/Leo?type=design&node-id=345-16732&mode=design

**Comment by kjozwiak** [comment]
The above requires `1.62.101` or higher for `1.62.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```

```


### Steps:
1. installed `1.62.`
2. launched Brave
3. loaded `https://plus.nasa.gov/scheduled-video/iss-expedition-70-in-flight-event-to-mark-the-25th-anniversary-of-the-mating-of-the-zarya-and-unity-modules/`
4. clicked on `Leo` in the sidebar
5. toggled `Use page context for response` to `Off`
6. clicked on `Summarize this page`
7. clicked on `Accept and begin`
8. waited for the response output

## Confirmed `Summarize this page` button and the `Use page context for response` toggle are now hidden, with `Suggest questions...` still there


`step 4`| `step 5` | `step 6` | `step 7`
-------|----------|----------|--------

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.62.116`

**Comment by kjozwiak** [comment]
Removing the above from https://github.com/brave/brave-browser/issues/35625 as `Leo` is targeting `1.63.x` for `Android`.
