### ISSUE TITLE
Webpage Rendering issue in Moto G54, Dimensity 7020

### ISSUE THREAD

**Issue by Ravi-Kishor** [brave/brave-browser#34090]
Description:- sometimes font or images or both are not rendred properly, after clearing data of app fine for 2-3 days and again problem start.

## Steps to reproduce 

   1. open any url
   

## Actual result 

![Screenshot_20231103-184927](https://github.com/brave/brave-browser/assets/97280268/599891cb-15ab-419e-995f-faa3c9c022d0)
![Screenshot_20231103-184941](https://github.com/brave/brave-browser/assets/97280268/1c503bd7-456a-4b35-9779-1ee7d4d0de81)

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? 
- Can you reproduce this issue with the current Play Store Beta version? 
- Can you reproduce this issue with the current Play Store Nightly version?

## Device details
   - Install type (ARM, x86): Bravemonoarm.apk (from github)
   - Device type (Phone, Tablet, Phablet): Phablet, Moto G54 Dim 7020
   - Android version: 13, September security patch
   
## Brave version
1.60.110, (issue was 2-3 verison prior too, cann't say about more older verison cuz new device, haven't tested )

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 

no
- Does the issue resolve itself when disabling Brave Rewards?

no
- Is the issue reproducible on the latest version of Chrome? 
no, not a issue in any other chromium based browser.

**Comment by SergeyZhukovsky** [comment]
Closing that one as the main issue is that https://github.com/brave/brave-browser/issues/33941. @Ravi-Kishor we are working on it, trying to understand what is going on, having hard time to reproduce it currently.

**Comment by PrayasSamanta12** [comment]
It's not only for brave browser.The same thing is happenig in Google browser also.Kindly fix this issue

**Comment by SergeyZhukovsky** [comment]
@PrayasSamanta12 that issue is fixed 6+ months ago. Do you still experience the problem?
