### ISSUE TITLE
Resize window causes time to overlap on stats

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#341]
## Description 

Resize window causes time to overlap on stats
## Steps to Reproduce

   1. Open a new tab ensure you have stats value shown in new tab
   2. Resize the window by dragging the right side of the window to make it min width possible
   3. Time shown on new tab overlaps the stats 

 ## Actual result:
Comparison of browser-laptop vs brave-core
![image](https://user-images.githubusercontent.com/17010094/41419504-3e0163d4-6fc0-11e8-866a-5222245c40be.png)

## Expected result:
Nothing should overlap in new tab
## Reproduces how often: 

100%

## Brave version (about:brave info)

 332140d

cc: @bradleyrichter

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.60.19 Chromium: 72.0.3626.81 (Official Build) beta(64-bit)
-- | --
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS | Mac OS X

* Verified resizing the new tab page did not overlap time and stats
![screen shot 2019-02-05 at 1 01 48 pm](https://user-images.githubusercontent.com/28145373/52294052-43981280-2946-11e9-97fd-b759d6ad724d.png)
