### ISSUE TITLE
Cleanup showing sync & reward menu in app menu model

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#3410]
Sync & Rewards are only valid in normal window.
They are valid In private window because they are redirected to  normal window.
However, they doesn't work properly in tor(guest) window.
So, sync and rewards menu item should be visible only in normal & private window.
Also, corresponding commands should be disabled in tor(guest) window.

STR:
Case 1)
1. Open private window and click app menu button
2. Check rewards & sync menu are visible
(Current status is sync is hidden)

Case 2)
1. Open tor window and click app menu button
2. Check rewards & sync menu are hidden
(Current status is rewards is visible)

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.63.4 Chromium: 73.0.3683.67 (Official Build) dev (64-bit)
-- | --
Revision | a83fd4f3207ae83412d329a9ca1239dd1e068345-refs/branch-heads/3683@{#760}
OS | Windows 7 Service Pack 1 Build 7601.24312

Used test plan from the description

tor window
![image](https://user-images.githubusercontent.com/34715963/54332978-d0f31480-4620-11e9-9f84-c033499a524d.png)

guest window
![image](https://user-images.githubusercontent.com/34715963/54333020-fd0e9580-4620-11e9-8762-35b2e813097b.png)

private window
![image](https://user-images.githubusercontent.com/34715963/54333035-16afdd00-4621-11e9-9254-362ecad8075a.png)
