### ISSUE TITLE
Paste and search in private window does not respect default search engine for private windows

### ISSUE THREAD

**Issue by calebvisage** [brave/brave-browser#34111]
## Description 
In private windows, selecting "Paste and search for" from the right-click context menu in the search bar defaults to the searching with the default search engine for normal windows, instead of the default search engine for private windows, despite Brave Search (in this case) being set as the default in settings. This inconsistency is not observed when pasting text directly from the clipboard or using the search box in a new tab page.

## Steps to Reproduce
1. Copy text to clipboard.
2. Open new private window.
3. Right-click search box and click "Paste and search for".
4. Brave will now search with whatever the default search engine is for normal windows.

## Actual result:
![image](https://github.com/brave/brave-browser/assets/68855603/d204d054-82aa-42ee-ab0b-3ecf8d8c1a47)
![image](https://github.com/brave/brave-browser/assets/68855603/3c10e3e9-71e5-4425-b13f-5d77addfaf5c)

## Expected result:
Search with default search engine for private windows as defined in settings.

## Reproduces how often: 
Easily reproduced.

## Brave version (brave://version info)
Brave | 1.60.110 Chromium: 119.0.6045.105 (Official Build) (64-bit)
Revision | 0bb6e7a81aed340b5a9e8b752c1cf92768257c40
OS | Windows 10 Version 22H2 (Build 19045.3570)

## Version/Channel Information:
Only tested in Stable version.

## Other Additional Information:
- Brave shields and Brave rewards probably irrelevant.
- Cannot reproduce in Chrome as it does not have distinct search settings for normal and incognito windows.

## Miscellaneous Information:
**Issue can be resolved** by setting Brave search (in this case) as the default search engine for normal windows.

**Comment by diracdeltas** [comment]
@rebron

**Comment by andykamezou** [comment]
Drag & drop a text into a Private window's tab also does not respect my search engine choice for the Private window. It uses my search engine choice for the Normal window instead.

Brave: 1.66.118 Chromium: 125.0.6422.147 (Official Build) (64-bit) 
Revision:	07af53490e0a52336cfb99a376f87671be258049
OS: Windows 10 Version 22H2 (Build 19045.4170)

**Comment by calebvisage** [comment]
"Paste and search" is working here too. @andykamezou should perhaps create a new issue. Closing this as resolved.
