### ISSUE TITLE
Wrong location icon and page info bubble of brave page

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#3411]
<img width="495" alt="screen shot 2019-02-19 at 9 58 17 am" src="https://user-images.githubusercontent.com/6786187/52983138-fd09e400-342c-11e9-84c7-3c09eb57adf5.png">

This should be like below.
<img width="309" alt="screen shot 2019-02-19 at 9 59 49 am" src="https://user-images.githubusercontent.com/6786187/52983160-2165c080-342d-11e9-8143-1d23f65948c9.png">

This is regression of https://github.com/brave/brave-core/pull/1385 and only reproducible on master and latest 0.62.x branch.
Reproducible on dev branch and not on released stable/beta.

STR
1. Load brave url like brave://settings
2. Check location icon and proper page info bubble is used

**Comment by fmarier** [comment]
This also affects https://github.com/brave/brave-core/pull/1630.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.62.42 Chromium: 73.0.3683.86 (Official Build) beta (64-bit)
-- | --
Revision | f9b0bec6063ea50ce2b71f5b9abbae7beee319a6-refs/branch-heads/3683@{#858}
OS | Windows 10 OS Build 17134.523

Used test plan from https://github.com/brave/brave-core/pull/2024

![image](https://user-images.githubusercontent.com/34715963/54997831-ed059700-4fcc-11e9-8ab4-6e3f7f2fcd18.png)
![image](https://user-images.githubusercontent.com/34715963/54997938-3524b980-4fcd-11e9-8326-8249c0b03b2d.png)
![image](https://user-images.githubusercontent.com/34715963/54997964-4968b680-4fcd-11e9-86a3-e8149e76e2ac.png)
![image](https://user-images.githubusercontent.com/34715963/54997990-5b4a5980-4fcd-11e9-8751-26f5df479943.png)
