### ISSUE TITLE
Brave AI Chat (Leo) fails to open if scripts are blocked by default. [Android]

### ISSUE THREAD

**Issue by lewisje** [brave/brave-browser#34119]
## Description 
When I open Leo while the default Shields setting is to block scripts, I see just a white box; when I enable scripts by default in Settings, I am able to use Leo again; I have only seen this behavior in Nighly for Android, and it might occur in Windows too, except that I have a Group Policy that prevents Shields from blocking scripts.

## Steps to reproduce 

   1. Open Settings and go to Brave Shields.
   2. Make sure that Block Scripts is turned on, and close Settings.
   3. Open Ask Leo from the browser menu.

## Actual result 
Leo launches and allows you to ask a question.

## Expected result
A blank white box appears that cannot be interacted with and can be dismissed normally.

## Issue reproduces how often 
every time

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version?
- - N/A, doesn't support Leo yet
- Can you reproduce this issue with the current Play Store Beta version?
- - not if it doesn't support Leo yet either
- Can you reproduce this issue with the current Play Store Nightly version?
- - yes, it's what I'm using

## Device details
   - Install type (ARM, x86):
   - - ARM64
   - Device type (Phone, Tablet, Phablet):
   - - Phone
   - Android version:
   - - 13: Build/TP1A.220624.014; 33; REL
   
## Brave version
1.62.21 Chromium: 119.0.6045.105 (Official Build) canary (64-bit)

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome? 

N/A

### Additional information

I tried figuring out which domain names Brave Chat was being served from, in particular enabling scripts on nala.bravesoftware.com and ai-chat.bsg.brave.com (and ai-chat-premium.bsg.brave.com for good measure), but even then, the problem did not go away until I changed the default setting to allow scripts.

**Comment by SergeyZhukovsky** [comment]
a dup of https://github.com/brave/brave-browser/issues/36012
