### ISSUE TITLE
Prices cuts off the screen in Tradingview.com graphs

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#3412]
## Description 

Prices cuts off the screen in Tradingview.com graphs

## Steps to Reproduce

   1. Navigate to https://www.bitmex.com/app/trade/XBTUSD
   2. Click on full screen icon in the graph
   3. Verify that Price column cuts off the screen ( column is shrinked and values are not visible clearly)
   4. Navigate https://cryptowatch.net/
   5. Verify that Price column cuts off the screen ( column is shrinked and values are not visible clearly)

## Actual result:

https://www.bitmex.com/app/trade/XBTUSD
![image](https://user-images.githubusercontent.com/38657976/53003240-884aa000-3454-11e9-8123-2fe5e5ebaa1c.png)

https://cryptowatch.net/

![image](https://user-images.githubusercontent.com/38657976/53003326-b5974e00-3454-11e9-8d65-66e6bff4bf13.png)

## Expected result:

Screenshots collected from Chrome

![image](https://user-images.githubusercontent.com/38657976/53003391-deb7de80-3454-11e9-9fd1-a93558dc5455.png)

![image](https://user-images.githubusercontent.com/38657976/53003346-c942b480-3454-11e9-95fa-703cc7aec605.png)

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 0.59.35 Chromium: 72.0.3626.81 (Official Build) (64-bit)
-- | --
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS | Windows 10

### Reproducible on current release: Yes
- Does it reproduce on brave-browser dev/beta builds?  Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? No
- Is the issue reproducible on the latest version of Chrome? No

### Additional Information

Issue is reported by community user
https://community.brave.com/t/tradingview-com-embedded-prices-cut/45386

**Comment by eljuno** [comment]
+1 from Community https://community.brave.com/t/tradingview-price-axis-not-rendering/56027?u=eljuno

`Allow all device  recognition` seems to fix the issue.

**Comment by GeetaSarvadnya** [comment]
+1 https://community.brave.com/t/charts-dont-load-on-any-charting-site/64902/2

**Comment by Miyayes** [comment]
+1 https://www.reddit.com/r/brave_browser/comments/dg6y4h/tradingview_not_displayed_correctly_on_bitmex_and/

**Comment by ryanbr** [comment]
Yeah still an issue with device recognition causing the issue, just double checked referrer issues also. Seems to not apply on this fault.

**Comment by ryanbr** [comment]
@eljuno workaround/allow-device-recognition label?

**Comment by designerfx** [comment]
+1, I experience this on Version 1.1.23 Chromium: 79.0.3945.88 (Official Build) (64-bit).
Device recognition still triggers this; if this is a default by brave maybe device recognition should be clarified as to what it is doing/blocking?

**Comment by Miyayes** [comment]
cc: @ryanbr if you can help here, as this has been an issue for awhile!

**Comment by THATDONFC** [comment]
I'm having the same issue. [Here's my post](https://community.brave.com/t/tradingview-com-doesnt-display-properly-with-device-recognition-blocked/113192/2) on the community board. 

Tradingview charts work fine if I change to "Cross-site device recognition blocked".

**Comment by ryanbr** [comment]
Old ticket: https://github.com/brave/brave-browser/issues/2516

**Comment by ryanbr** [comment]
Still an issues @GeetaSarvadnya  ?

**Comment by GeetaSarvadnya** [comment]
@ryanbr Issue is NOT reproducible anymore. Thanks for closing the issue
