### ISSUE TITLE
Sometimes accounts are not shown in Accounts tab until a new account is created

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#34128]
## Description 
Sometimes accounts are not shown in Accounts tab until a new account is created

## Steps to reproduce 

   1. Create a new wallet
   2. Upgrade to 1.61.61
   3. Open Wallet and go to Accounts tab
   4. Created accounts are not listed 
   5. Click on create account and create one
   6. Lists the other accounts created during wallet creation

## Actual result 

https://github.com/brave/brave-browser/assets/17010094/2a6e5bfc-97c2-45a9-8d7f-033c0a6de9a3

## Expected result
Should show all the accounts all the time

## Issue reproduces how often 
Intermittent 

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Not checked/seen
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Not checked/seen

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Tablet
   - Android version: 13
   
## Brave version
1.61.61

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @simoarpe

**Comment by lukemulks** [comment]
Experiencing this frequently. 
When I connect an account to a dapp, not all of my other accounts display as available when trying to switch accounts on same network. Latest Nightly on desktop

**Comment by simoarpe** [comment]
Closing this issue as it's referring to the old native implementation. Checked on the latest Android using WebUI (`1.71.x`), issue seems to be fixed now.
