### ISSUE TITLE
Bottom navigation is not fully shown on tablet view

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#34127]
## Description 
Bottom navigation is not fully shown on tablet view

## Steps to reproduce 

   1. Open Wallet 
   2. Bottom navigation is not fully stretched

## Actual result 

Dark | Light
-- | --
![image](https://github.com/brave/brave-browser/assets/17010094/3f7aab7d-52b1-4de9-8a44-0cf36b2d702c) | ![image](https://github.com/brave/brave-browser/assets/17010094/6aa6e380-2b15-4fc6-b99b-43fa28cbe8fb)

## Expected result
<img width=400 src=https://github.com/brave/brave-browser/assets/17010094/6cc858ec-b583-42a8-83f4-9772c935c976>

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Tablet
   - Android version: 13
   
## Brave version
1.61.61 x64 Beta build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

**Comment by simoarpe** [comment]
Issue not relevant anymore as we switched to WebUI where bottom navigation bar has responsive design. I'm closing this.
