### ISSUE TITLE
Marvel Insider website does not load when logged in

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#34134]
## Description 

Using a full-copy of the users report as it describes everything nicely:

> I am having an issue on certain websites where certain portions of the site will not load. I have experienced this on a couple different sites including: godaddy and [marvel.com/insider/home 5](http://marvel.com/insider/home). For godaddy the chat now support box wouldn’t show. On [marvel.com/insider/home 5](http://marvel.com/insider/home) nothing in the center of the screen. The header, navigation menu and footer load but not content in the middle.
> 
> I have attempted clearing cookies/cache from all time, all shields are down for both websites. Updating to the latest browser, restarting computer. This issue is persisting on both Mobile iOS app and Desktop browser. If I visit site on safari mobile, everything loads just fine.
> 
> How can this issue be reproduced?
> 
> Visit [Marvel.com/insider/home 1](http://marvel.com/insider/home)
> See if any content loads in the middle
> Expected result:
> Content should fully load on any and all web pages with shields down. I have experienced this issue prior on some websites that was due to shields being up. However, even removing them on these sites I am still experiencing the issue on both mobile and desktop.
> 
> Version 1.59.117 Chromium: 118.0.5993.70 (Official Build) (64-bit)

Note that I can reproduce this issue as well consistently — also note that this issue only occurs if you are logged into the site. 
cc @ryanbr to take a look here.

- Can you reproduce this issue with the current release? Y
- Can you reproduce this issue with the beta channel? Y
- Can you reproduce this issue with the nightly channel? Y

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? Y
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? No

**Comment by arthuredelstein** [comment]
I wasn't able to reproduce on desktop. Is it fixed?

**Comment by ryanbr** [comment]
Sorry I missed the orginal request, I created a login and was able to login with default shields settings here
