### ISSUE TITLE
Add Placeholder Icons for Broken NFT images

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#34139]
## Description 

We need to implement a `Placeholder` icon for broken `NFT` images

![Screenshot 53](https://github.com/brave/brave-browser/assets/40611140/7e8fc321-5b8a-4ea3-b23c-a8289e33ed75)

![Screenshot 54](https://github.com/brave/brave-browser/assets/40611140/00b6293d-4125-478c-87b2-03b3f88c1254)

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.62.130 Chromium: 120.0.6099.199 (Official Build) beta (64-bit)
-- | --
Revision | `6d589c6dc0f3489830d40332c82cdd5597e41c88`
OS | Windows 11 Version 23H2 (Build 22631.2861)

- Verified steps from [brave/brave-core#20859](https://github.com/brave/brave-core/pull/20859)
- Verified NFT placeholder icon is shown for NFTs with broken images
![brave_GBzMR82vL9](https://github.com/brave/brave-browser/assets/17010094/63ca5e12-d9a7-4a51-ab62-584dd4fce46d)

---------------------

**Verification passed on**

Brave | 1.62.130 Chromium: 120.0.6099.199 (Official Build) beta (64-bit)
-- | --
Revision | `6d589c6dc0f3489830d40332c82cdd5597e41c88`
OS | Linux

- Verified steps from [brave/brave-core#20859](https://github.com/brave/brave-core/pull/20859)
- Verified NFT placeholder icon is shown for NFTs with broken images
![NFTPlaceholder](https://github.com/brave/brave-browser/assets/17010094/55e18e89-2429-4634-a8e0-70ad197583bd)

---------------------

**Verification passed on**

Brave | 1.62.130 Chromium: 120.0.6099.199 (Official Build) beta (arm64)
-- | --
Revision | `6d589c6dc0f3489830d40332c82cdd5597e41c88`
OS | macOS Version 14.2.1 (Build 23C71)

- Verified steps from [brave/brave-core#20859](https://github.com/brave/brave-core/pull/20859)
- Verified NFT placeholder icon is shown for NFTs with broken images
![image](https://github.com/brave/brave-browser/assets/17010094/deb79fcf-b3c0-45ed-aea3-16f63a47a6ca)
