### ISSUE TITLE
Remove code which detected Android system Auto Sync settings

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#34136]
Brave Browser has code which detects if Android system Auto Sync settings is turned off; if so, Brave Sync didn't work and then the informer was shown. This behavior was copied from Chromium. As for now, Chromium changed this behavior, it doesn't depend on that system settings. We should do the same for Brave and cleanup the code. 

Suggested by @bridiver .

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.62.116`
