### ISSUE TITLE
Account Details is showing Zero Balance

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#34142]
## Description 

The `Account Details` is showing a `$0.00` total fiat balance

## Steps to Reproduce

   1. Go to the `Accounts` tab and select and account with balances
   2. The `Total Fiat Balance` is showing `$0.00`

## Actual result:

![Screenshot 56](https://github.com/brave/brave-browser/assets/40611140/244292ec-11d0-4ae7-b6b4-14df273902e3)

## Expected result:
Should compute the full fiat balance.

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.62.130 Chromium: 120.0.6099.199 (Official Build) beta (64-bit)
-- | --
Revision | `6d589c6dc0f3489830d40332c82cdd5597e41c88`
OS | Windows 11 Version 23H2 (Build 22631.2861)

- Verified steps from [brave/brave-core#20860](https://github.com/brave/brave-core/pull/20860)
- Verified Account details shows correct Fiat value
![brave_dederAiy8r](https://github.com/brave/brave-browser/assets/17010094/058372c2-f6ee-4e84-a755-3587dd0bd57a)
---------------------

**Verification passed on**

Brave | 1.62.130 Chromium: 120.0.6099.199 (Official Build) beta (64-bit)
-- | --
Revision | `6d589c6dc0f3489830d40332c82cdd5597e41c88`
OS | Linux

- Verified steps from [brave/brave-core#20860](https://github.com/brave/brave-core/pull/20860)
- Verified Account details shows correct Fiat value
![FiatBalance](https://github.com/brave/brave-browser/assets/17010094/bb7a22d5-1128-4914-bc83-185a0e53c210)


---------------------

**Verification passed on**

Brave | 1.62.130 Chromium: 120.0.6099.199 (Official Build) beta (arm64)
-- | --
Revision | `6d589c6dc0f3489830d40332c82cdd5597e41c88`
OS | macOS Version 14.2.1 (Build 23C71)

- Verified steps from [brave/brave-core#20860](https://github.com/brave/brave-core/pull/20860)
- Verified Account details shows correct Fiat value
![image](https://github.com/brave/brave-browser/assets/17010094/9baf808e-092d-4890-9641-708005554b0a)
