### ISSUE TITLE
Title bar font color should adapt to theme

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#34154]
## Description 

The titlebar font color should adapt to the theme color better.

## Steps to Reproduce

   1. Enable "Show title bar" in tabs settings
   2. Change theme to a color theme
   3. See title bar

## Actual result:

<img width="1281" alt="image" src="https://github.com/brave/brave-browser/assets/15734630/e9be421e-9bbb-482d-8240-661f14199a81">

## Expected result:
Text color should be readable (in this case, use color for dark mode)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by simonhong** [comment]
This is macOS only issue.

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.62.74 Chromium: 119.0.6045.163 (Official Build) nightly (x86_64)
-- | --
Revision | 070cd801c60b65bed66cfed719aeab87384ec9b8
OS | macOS Version 14.2 (Build 23C5047e)
```

### Steps:
1. installed `1.62.74`
2. launched Brave
3. skipped onboarding
4. edited the profile's theme via `brave://settings/manageProfile`

## Confirmed a few configurations; all had clearly-readable text in the title bar, regardless of dark/light colors

example | example | example
---------|----------|---------
<img width="1807" alt="Screenshot 2023-11-22 at 1 16 13 PM" src="https://github.com/brave/brave-browser/assets/387249/3a1444bc-94fe-44e2-a341-10477c34859f"> | <img width="1807" alt="Screenshot 2023-11-22 at 1 16 26 PM" src="https://github.com/brave/brave-browser/assets/387249/b5404687-8ddb-4a0e-b8e1-56b434121026"> | <img width="1807" alt="Screenshot 2023-11-22 at 1 16 30 PM" src="https://github.com/brave/brave-browser/assets/387249/34eb41c9-77bf-4fcf-9f23-0f7ad10b1782">
