### ISSUE TITLE
Make it possible to run experiments on first run on Windows

### ISSUE THREAD

**Issue by mherrmann** [brave/brave-browser#34150]
## Description 

At the moment, Brave on Windows downloads the variations seed on first run - but it only takes effect after a browser restart. This means that we cannot run experiments for first-run behavior.

The goal of this issue is to make it possible to run experiments during first-run use on Windows via Griffin. It requires changes on the devops side as well as in the browser. This issue supersedes the [associated devops issue](https://github.com/brave/devops/issues/10466) for visibility in release notes and for QA. It is the Windows part of #15229.

cc @goodov @iefremov @chrismore

**Comment by kjozwiak** [comment]
@brave/qa-team I'll grab this one and run through a few checks/build off the STR/Cases that @mherrmann mentions via https://github.com/brave/brave-browser/issues/34150#issue-1981488746.

**Comment by kjozwiak** [comment]
@mherrmann unfortunately I don't think the above is working. When launching `1.62.134 Chromium: 120.0.6099.199` for the first time, I don't see any of the studies listed via `brave://version`. I also double checked and ensured that it wasn't just a UX issue re: maybe the studies are being applied but not listed via `brave://version`. However, that's not the case. Seems like the Griffin studies are not being applied still the second launch.

### STR/Cases:

**`Against Production`**

* install `1.62.134 Chromium: 120.0.6099.199` via https://github.com/brave/brave-browser/releases/download/v1.62.134/BraveBrowserStandaloneBetaSetup.exe
* once the browser launches, check `brave://version` and notice that there's no Griffin studies being listed
* visit https://www.cnn.com and click on any of the articles and click on the `Speedreader` icon (notice that TTS is not present)
* restart the browser and notice that the Griffin studies are now being applied
  * `Speedreader TTS:Speedreader: TTS enabled`
* visit the same article and notice that the TTS option is now available (which means that the Griffin study as been applied)

**`Against Staging`**

* install `1.62.134 Chromium: 120.0.6099.199` via https://github.com/brave/brave-browser/releases/download/v1.62.134/BraveBrowserStandaloneBetaSetup.exe
* once the browser launches, close the browser and remove `\AppData\Local\BraveSoftware\Brave-Browser-Beta`
* relaunch the browser with `brave.exe --enable-logging=stderr --reset-variation-state --variations-server-url=https://variations.bravesoftware.com/seed`
* visit `brave://version` and notice that the Griffin studies are not being applied
* close/restart the browser once again using `brave.exe --enable-logging=stderr --reset-variation-state --variations-server-url=https://variations.bravesoftware.com/seed`
* notice the Griffin studies are now visible/being applied via `brave://version`

### Installers Checked:

* `BraveBrowserStandaloneBetaSetup.exe` (offline installer) - Griffin **NOT** being applied on first launch
  * Correctly working on second launch once the browser as been restarted (studies listed via `brave://version`)
* `BraveBrowserBetaSetup.exe` (online installer) - Griffin **NOT** being applied on first launch
  * Correctly working on second launch once the browser as been restarted (studies listed via `brave://version`)

**`First Launch (Not working)`** | **`Second Launch (Working)`**
------------------------------------|-----------------------------------
![seedNotWorking](https://github.com/brave/brave-browser/assets/2602313/888309a8-8961-453d-b46b-22589299d82d) | ![seedWorking](https://github.com/brave/brave-browser/assets/2602313/cbd22718-4a02-48e6-a247-26074bdeb430)

**Comment by mherrmann** [comment]
Thank you for catching this @kjozwiak. I can reproduce the issue and will investigate. One thing I should have made clearer is that the variations seed only gets fetched by the online installer. So I do not expect it to be applied on first run when installing with the offline installer. I will update the issue description.

**Comment by kjozwiak** [comment]
Created https://github.com/brave/brave-browser/issues/35232 as a follow up. We'll keep the above as `QA/Blocked` for the time being. If we manage to get https://github.com/brave/brave-browser/issues/35232 resolved and uplifted into `1.62.x`, we can label the above as `QA/No` and use https://github.com/brave/brave-browser/issues/35232 as the QA issue. However, if we don't mange to get the fix into `1.62.x`, we'll label the above as `QA/No` and will verify https://github.com/brave/brave-browser/issues/35232 once ready.

**Comment by MadhaviSeelam** [comment]
@kjozwiak This issue is verified via https://github.com/brave/brave-browser/issues/35232#issuecomment-1906669532 so labelling this issue as `QA/No`.
