### ISSUE TITLE
Deprecate uncached coin market data

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#34153]
## Description 

Move fetched for coin market data to RTK-query so that data is not constantly refetched

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.62.99 Chromium: 120.0.6099.62 (Official Build) beta (64-bit)
-- | --
Revision | 0f3e892de210168e788b3418961f94c4d0c5942a
OS | Windows 11 Version 22H2 (Build 22621.2792)

- Verified steps from [brave/brave-core#20876](https://github.com/brave/brave-core/pull/20876)
- Verified market coin data works as before without any regressions
