### ISSUE TITLE
Disable to Bookmarks & Reading list buttons on the sidebar in the Guest window 

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#34162]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/31644

## Steps to Reproduce

   1. Install 1.62.32
   2. launch Brave
   3. click Hamburger >> More tools >> Open Guest profile
   4. click on Bookmarks button on the sidebar

## Actual result:

<img width="960" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/98e2ea99-e8ec-40ae-8c05-fcb655260924">

## Expected result:
Disable to Bookmarks & Reading list buttons on the sidebar in the Guest window```

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.62.32 Chromium: 119.0.6045.105 (Official Build) nightly (64-bit)
-- | --
Revision | 76f975d47c49751a29f222762c1a24bd7df88cef
OS | Windows 11 Version 22H2 (Build 22621.2428)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? N/A
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@rebron @aguscruiz

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.62.38 Chromium: 119.0.6045.134 (Official Build) nightly (x86_64)
-- | --
Revision | 63d368dd4d01900c1f3f056b6371210d10899d5a
OS | macOS Version 14.2 (Build 23C5041e)
```
### First, reproduced using `1.61.32`:

example | example
---------|---------
<img width="1686" alt="Screenshot 2023-11-10 at 4 04 42 PM" src="https://github.com/brave/brave-browser/assets/387249/ef752443-9576-4d2c-9d2c-47650a498fee"> | <img width="1840" alt="Screenshot 2023-11-10 at 4 43 00 PM" src="https://github.com/brave/brave-browser/assets/387249/6e5b1b07-220a-40cb-9846-85e360309a7d">

## Then, confirmed that `Bookmarks` and `Reading List` buttons are disabled when in a `Guest` window/profile

example | example
---------|---------
<img width="1462" alt="Screenshot 2023-11-10 at 3 29 13 PM" src="https://github.com/brave/brave-browser/assets/387249/fb6a2c04-008b-40b2-a615-9edd5e2f744e"> | <img width="1468" alt="Screenshot 2023-11-10 at 3 29 37 PM" src="https://github.com/brave/brave-browser/assets/387249/c6c9029e-ca73-49c7-bb6d-d06312140a2a">
