### ISSUE TITLE
Adjust private/tor window's profile button radius

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#34166]
It should use same radius with vpn button.
<img width="166" alt="image" src="https://github.com/brave/brave-browser/assets/6786187/55716c61-aefa-4b76-8b36-368c35bc915a">

<img width="118" alt="image" src="https://github.com/brave/brave-browser/assets/6786187/a01feb2b-f5e7-461f-8610-acc3f2e0974c">

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.62.38 Chromium: 119.0.6045.134 (Official Build) nightly (x86_64)
-- | --
Revision | 63d368dd4d01900c1f3f056b6371210d10899d5a
OS | macOS Version 11.7.10 (Build 20G1427)
```
