### ISSUE TITLE
[hackerone] Always show URL before onion redirects

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#34163]
https://hackerone.com/reports/2239946 reported by [newfunction](https://hackerone.com/newfunction)

1. Show the full URL that is about to be opened in a Tor window on mouseover over the "Open in Tor" button in the URL bar
2. Change the "Automatically redirect .onion sites" setting so that redirects to an .onion happen automatically ONLY in Tor windows and not in normal or private windows (https://github.com/brave/brave-browser/issues/15199#issuecomment-820564581)
3. Change the settings description for the automatic onion redirect from:

> Brave will switch to the .onion version of a website when available, and automatically open all .onion domains in a Tor window.

to:

> In Tor windows, Brave will automatically switch to the .onion version of a website when available. 

cc @fmarier

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.62.97 Chromium: 120.0.6099.56 (Official Build) beta (x86_64)
-- | --
Revision | 9561bb49dc23c407275af722586f045356609329
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Show the full URL as a tooltip in the `Open in Tor` button
### Redirects to `.onion` sites happen automatically now only in `Tor` windows
### Settings-description change for `Automatically redirect .onion sites`

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.62.99 Chromium: 120.0.6099.62 (Official Build) beta (64-bit)
-- | --
Revision | 0f3e892de210168e788b3418961f94c4d0c5942a
OS | Windows 11 Version 22H2 (Build 22621.2715)
```

## Show the full URL as a tooltip in the `Open in Tor` button - `PASSED`
<details>

### Steps:
1. installed `1.62.99`
2. launched Brave
3. loaded `brave.com` in a normal window/tab
4. hovered over the `Tor` button/icon in the URL bar

### Confirmed the full site URL is displayed as a tooltip, on hover

<img width="972" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/06569534-72d9-4acc-9174-88002c3feed8">

</details>

## Redirects to `.onion` sites happen automatically now only in `Tor` windows - `PASSED`

## Preference `ON` - `PASSED`
<details>

### Steps:

1. installed `1.62.99`
2. launched Brave
3. toggled `Automatically redirect .onion sites` to `ON` (defaults to `OFF`) in `brave://settings/privacy`
4. opened a new-tab window
5. loaded `nytimes.com`
6. confirmed `Tor` button with tooltip of full site URL
7. clicked on the `Tor` button
8. repeated steps but with the various window types below

#### `Normal window` - `PASSED`

example | example | example
---------|----------|---------
<img width="962" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/2c3b02ae-b362-4a8c-acd1-5247f9ad2e1d">|<img width="962" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/5f84565d-01c1-4f71-8cd4-caf583cf8cd7">|<img width="962" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/4783055c-36b7-4178-bd42-a5271797948f">

####`Private Window with Tor` - `PASSED`

example | example | example 
---------|----------|---------
<img width="959" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/d89d8ed8-1852-4683-9230-2f4ea1b672ee">|<img width="950" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/b2803a4d-de4c-4bce-9642-13cf66ddde11">|<img width="958" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/490f6b89-5955-443c-9c29-8b75b59771e7">

#### `Private Window` - `PASSED`

example | example 
----- | -----
<img width="959" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/d89d8ed8-1852-4683-9230-2f4ea1b672ee">|<img width="959" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/6c5deec1-85aa-4316-85e6-300147d89428">|<img width="959" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/23bc6215-3022-4032-85cc-91cfc888a76e">

#### `Guest-profile window` - `PASSED`

#### Confirmed nytimes.com only loaded in the Guest profile window, not the .onion URL

example | example 
----- | -----
<img width="959" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/d89d8ed8-1852-4683-9230-2f4ea1b672ee">|<img width="955" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/843948c1-09c0-49ad-9e74-b2f74cc52e63">
</details>

## Preference `OFF` - `PASSED`
<details>

1. installed `1.62.99`
2. launched Brave
3. opened a new-tab window
4. loaded `brave.com`
5. confirmed `Tor` button with tooltip of full site URL
6. clicked on the `Tor` button
7. repeated steps 3-6 but with the various window types below

### Confirmed `.onion` version of `brave.com` loaded

### `Normal window` - `PASSED`

example | example | example
---------|---------|----------
<img width="972" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/36c03947-5685-4084-828d-20b899db8be7">|<img width="972" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/b24b3058-9fd6-47fa-a047-40e9aeb80436">|<img width="957" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/43c01cef-091b-4735-853f-68775e14974d">

#### `Private Window with Tor` - `PASSED`

example | example | example 
---------|----------|---------
<img width="972" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/36c03947-5685-4084-828d-20b899db8be7">|<img width="961" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/a97f0f27-1308-4a38-b846-48608ace04ce">|<img width="956" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/d39ca9d5-5f7a-44c6-9124-f618b57c27e3">


#### `Private Window` - `PASSED`

example | example | example 
----- | ----- | -------
<img width="972" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/36c03947-5685-4084-828d-20b899db8be7">|<img width="972" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/05fbc09c-d007-4949-a9aa-e6dbdaca2d87">|<img width="971" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/238deccc-aabf-444f-aae1-327e47fe29b7">

#### `Guest-profile window` - `PASSED`

Confirmed brave.com only loaded in the Guest profile window, not the .onion URL

example | example 
----- | ----- 
<img width="972" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/36c03947-5685-4084-828d-20b899db8be7">|<img width="954" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/d865eb3c-e82f-45f7-a992-2ad246198760">


</details>
</details>

## Settings-description change for `Automatically redirect .onion sites` - `PASSED`

<details>

### Steps:
1. installed `1.62.99`
2. launched Brave
3. opened `brave://settings/privacy`
4. confirmed the descriptive text for `Automatically redirect .onion sites` reads, `"In Tor windows, Brave will automatically switch to the .onion version of a website when available."`


<img width="959" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/89bd1a6a-0f18-4157-b608-fa5d33b7f43f">

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.62.112 Chromium: 120.0.6099.115 (Official Build) beta (64-bit) 
Revision	ae1e179b9884b2de2f4ba0bdea7da3beaad93ffa
OS	Linux
```
