### ISSUE TITLE
White Flash when selecting some NFTs in Wallet

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#34161]
## Description 

There is a `White` flash that occurs sometimes when selecting certain `NFT's` in the `Wallet`, happening with UD nfts

## Steps to Reproduce

   1. Open the `Wallet` and go to the `NFTs` tab
   2. Select an `UD` NFT
   3. You will see a `White` flash before it loads

## Actual result:

https://github.com/brave/brave-browser/assets/40611140/8cfcced0-9119-4f69-9885-9a08f2267afc

## Expected result:
Should return an loading skeleton until the `NFT` metadata is returned.

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.62.130 Chromium: 120.0.6099.199 (Official Build) beta (64-bit)
-- | --
Revision | `6d589c6dc0f3489830d40332c82cdd5597e41c88`
OS | Windows 11 Version 23H2 (Build 22631.2861)

- Verified steps from [brave/brave-core#20880](https://github.com/brave/brave-core/pull/20880)
- Verified no white flash when selecting an NFT from UD

https://github.com/brave/brave-browser/assets/17010094/f36aeb61-eb12-4b38-ac85-204ac9a5881b


---------------------

**Verification passed on**

Brave | 1.62.130 Chromium: 120.0.6099.199 (Official Build) beta (64-bit)
-- | --
Revision | `6d589c6dc0f3489830d40332c82cdd5597e41c88`
OS | Linux

- Verified steps from [brave/brave-core#20880](https://github.com/brave/brave-core/pull/20880)
- Verified no white flash when selecting an NFT from UD

https://github.com/brave/brave-browser/assets/17010094/a632e0a0-2b81-4f7e-b16b-04ab6214e844


---------------------

**Verification passed on**

Brave | 1.62.130 Chromium: 120.0.6099.199 (Official Build) beta (arm64)
-- | --
Revision | `6d589c6dc0f3489830d40332c82cdd5597e41c88`
OS | macOS Version 14.2.1 (Build 23C71)

- Verified steps from [brave/brave-core#20880](https://github.com/brave/brave-core/pull/20880)
- Verified no white flash when selecting an NFT from UD

https://github.com/brave/brave-browser/assets/17010094/fe0983c4-ff37-42e7-85e2-9422911bddb7
