### ISSUE TITLE
Sidebar panel header & contents background colors are not matched

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#34165]
## Description 

@aguscruiz reported at https://github.com/brave/brave-browser/issues/31644#issuecomment-1798346038
![image](https://github.com/brave/brave-browser/assets/15734630/8d297f1d-7678-4de3-a7ca-0897c3871a96)

## Steps to Reproduce

   1. Launch brave and set light mode
   2. Open private window and open bookmarks panel
   3. 

## Actual result:

Panel header and contents bg colors are different

## Expected result:
Panel header and contents bg color should be matched

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using


```
Brave | 1.62.42 Chromium: 119.0.6045.134 (Official Build) nightly (x86_64)
-- | --
Revision | c1d29f97c9eaab2f5f11229fa93f725634f47e42
OS | macOS Version 14.2 (Build 23C5041e)
```


## `Normal window`

`Light` | `Dark`
-------|-------
<img width="1686" alt="Screenshot 2023-11-10 at 4 01 13 PM" src="https://github.com/brave/brave-browser/assets/387249/9797f8e1-66d3-4cf8-b226-2456f7501433"> | <img width="1686" alt="Screenshot 2023-11-10 at 4 03 20 PM" src="https://github.com/brave/brave-browser/assets/387249/6b17ea51-da40-4f40-9d9f-07a30a0cf961">

## `Private Window`

## `Private Window with Tor`
