### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by theja98** [brave/brave-browser#34172]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.60.110 Chromium: 119.0.6045.105
Operating System: Android 7.0

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. After reseting brave wallet
2.I tried to select country
3.It automatically select united kingdom and then the app starts crashing, it happens all time when I tried to select country

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/9f7e0e00-14aa-f80a-0000-000000000000
```[tasklist]
### Tasks
```

**Comment by bsclifton** [comment]
I can't find any occurrences of this in Backtrace (where the crash reports go)

cc: @brave/crypto-wallets-front-end on the above steps - but will close as stale
