### ISSUE TITLE
twitch.tv instead of publisher name is shown on Brave Panel

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#3417]
Follow up from https://github.com/brave/brave-browser/issues/3043

## Steps to Reproduce

1. Clean install
2. Open a twitch stream
3. Reload
4. Immediately open Rewards Panel

## Actual result:

twitch.tv is shown on Brave Panel
![twitch_panel](https://user-images.githubusercontent.com/34715963/53036012-159eec00-3477-11e9-80ec-5631b3d5e058.gif)

Note: After closing the Panel and opening it again. Publisher name is shown.

## Expected result:
publisher is shown on Brave Panel

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.60.40 Chromium: 72.0.3626.109 (Official Build) (64-bit)
-- | --
Revision | fae8db7ab9280fa6704a59980263c804f809ebd5-refs/branch-heads/3626@{#857}
OS | Windows 7

cc @brave/legacy_qa @jasonrsadler @NejcZdovc

**Comment by LaurenWags** [comment]
Reproduced on macOS

Brave | 0.60.44 Chromium: 72.0.3626.109 (Official Build) (64-bit)
-- | --
Revision | fae8db7ab9280fa6704a59980263c804f809ebd5-refs/branch-heads/3626@{#857}
OS | Mac OS X

**Comment by btlechowski** [comment]
Good work @NejcZdovc 

Verification passed on

Brave | 0.65.120 Chromium: 75.0.3770.90 (Official Build) (64-bit)
-- | --
Revision | a6dcaf7e3ec6f70a194cc25e8149475c6590e025-refs/branch-heads/3770@{#1003}
OS | Windows 7 Service Pack 1 (Build 7601.24468)

Verified the testplan from the description and https://github.com/brave/brave-core/pull/2618
