### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by theja98** [brave/brave-browser#34171]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.60.110 Chromium: 119.0.6045.105
Operating System: Android 7.0

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1.
2.
3.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/ef800e00-14aa-f80a-0000-000000000000

**Comment by bsclifton** [comment]
reported here with more details https://github.com/brave/brave-browser/issues/34172
