### ISSUE TITLE
Support quoted scriptlet arguments

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-browser#34170]
It's currently undocumented in the [uBlock Origin wiki](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#scriptlet-injection) at the moment, but uBO has supported a quoted scriptlet argument syntax for some time now. Many adblock rules designed to counter cookie consent notices take advantage of that syntax.

`adblock-rust` has supported this feature as of v0.8.3.

**Comment by kjozwiak** [comment]
The above requires `1.61.75` or higher for `1.61.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.61.75 Chromium: 119.0.6045.134 (Official Build) beta (x86_64)
-- | --
Revision | 1b1191cb2465b2b90a5e8fea4a63aed1cfca47f5
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.61.75`
2. launched Brave
3. loaded `notion.so`
4. confirmed cookie banner along bottom of the viewport
5. opened `brave://adblock`
6. unchecked `EasyList Cookie` from the `Filter LIsts` section
7. added the following rule supplied by @antonok-edm over Slack:
```
notion.so##+js(set-cookie, notion_check_cookie_consent, true)
notion.so##+js(trusted-set-cookie, notion_cookie_consent, '{%22id%22:%2282a41727-b652-4011-a0a4-13a4499c039a%22%2C%22permission%22:{%22necessary%22:true%2C%22preference%22:true%2C%22performance%22:false%2C%22targeting%22:false}%2C%22policy_version%22:%22v8%22}')
```
8. reloaded the page

### Confirmed the cookie banner disappeared on reload with the new ruleset

example | example | example
---------|----------|---------
<img width="1455" alt="Screen Shot 2023-11-14 at 3 26 58 PM" src="https://github.com/brave/brave-browser/assets/387249/f5c8fb50-7209-4d80-b3b8-31fe97b94ef2"> | <img width="1455" alt="Screen Shot 2023-11-14 at 3 27 40 PM" src="https://github.com/brave/brave-browser/assets/387249/e7b856fc-9cb2-49c8-928d-5a7d023d1439"> | <img width="1947" alt="Screen Shot 2023-11-14 at 3 28 09 PM" src="https://github.com/brave/brave-browser/assets/387249/a8eccfb6-86ce-43d7-9d5f-b7617747e46a">

**Comment by kjozwiak** [comment]
Removing the `QA Pass` label as the above was uplifted into `1.60.x` so we'll need to re-check/ensure it's working within `1.60.x` before releasing. The above requires `1.60.120` or higher for `1.60.x` verification.

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.60.124 Chromium: 119.0.6045.163 (Official Build) (64-bit)
-- | --
Revision | 803c85554783c998a840f4b211c94236409a9928
OS | Windows 10 Version 22H2 (Build 19045.3693)

```

### Steps:
1. installed `1.60.124`
2. launched Brave
3. loaded `notion.so`
4. confirmed cookie banner along bottom of the viewport
5. opened `brave://adblock`
6. unchecked `EasyList Cookie` from the `Filter LIsts` section
7. added the following rule supplied by @antonok-edm over Slack:
```
notion.so##+js(set-cookie, notion_check_cookie_consent, true)
notion.so##+js(trusted-set-cookie, notion_cookie_consent, '{%22id%22:%2282a41727-b652-4011-a0a4-13a4499c039a%22%2C%22permission%22:{%22necessary%22:true%2C%22preference%22:true%2C%22performance%22:false%2C%22targeting%22:false}%2C%22policy_version%22:%22v8%22}')
```
8. reloaded the page

### Confirmed the cookie banner disappeared on reload with the new ruleset

example | example | example
---------|----------|---------
![image](https://github.com/brave/brave-browser/assets/38657976/649abf77-18e5-4bb9-b3bb-7474589fc004) | ![image](https://github.com/brave/brave-browser/assets/38657976/eb900a37-a0ad-41a5-b03f-c193b8ea4748) | ![image](https://github.com/brave/brave-browser/assets/38657976/ea785e67-8309-4df0-aca0-885f82d78c5f)

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.60.124 Chromium: 119.0.6045.163 (Official Build) (x86_64)
-- | --
Revision | 803c85554783c998a840f4b211c94236409a9928
OS | macOS Version 13.6.1 (Build 22G313)
```

**Comment by btlechowski** [comment]
Verified with

Brave | 1.60.124 Chromium: 119.0.6045.163 (Official Build) (64-bit)
-- | --
Revision | 803c85554783c998a840f4b211c94236409a9928
OS | Linux

Verification **PASSED** on

### Steps:
1. installed `1.60.124`
2. launched Brave
3. loaded `notion.so`
4. confirmed cookie banner along bottom of the viewport
5. opened `brave://adblock`
6. unchecked `EasyList Cookie` from the `Filter LIsts` section
7. added the following rule:
```
notion.so##+js(set-cookie, notion_check_cookie_consent, true)
notion.so##+js(trusted-set-cookie, notion_cookie_consent, '{%22id%22:%2282a41727-b652-4011-a0a4-13a4499c039a%22%2C%22permission%22:{%22necessary%22:true%2C%22preference%22:true%2C%22performance%22:false%2C%22targeting%22:false}%2C%22policy_version%22:%22v8%22}')
```
8. reloaded the page

### Confirmed the cookie banner disappeared on reload with the new ruleset

example | example | example
---------|----------|---------
