### ISSUE TITLE
[Speedreader] TTS improvements.

### ISSUE THREAD

**Issue by boocmp** [brave/brave-browser#34187]
1.  Change TTS stylesheet according to the design (https://www.figma.com/file/YHMNRL2XpZDOUe6n1Dw6K1/Reader-mode?type=design&node-id=2294-15581&mode=design&t=xbq2C3UmyQ7O45pT-0 Text To Speech)
2. Change state of the inline tts button to show current action.
3. Do not show tts inline button if tts panel is not selected in the toolbar
4. Do not read text when tts panel is not selected in the toolbar
5. Add a highlight of the current reading position.

**Comment by kjozwiak** [comment]
Removing the `QA-Pass` label as the above will need to be re-verified using `1.61.94` or higher. @brave/qa-team please use `Windows` to verify the above on `1.61.x`. This way we at least verified the above on `macOS` via `1.62.x` and then on `Windows` via `1.61.x`.

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.61.94 Chromium: 120.0.6099.56 (Official Build) (64-bit)
-- | --
Revision | 72759647494f071d653f8a61465fadf5f361b06e
OS | Windows 10 Version 22H2 (Build 19045.3693)

```
