### ISSUE TITLE
Crucial Scripts Blocked on KBB

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#3418]
## Description 
Certain parts of kbb.com do not work as Brave is blocking crucial scripts.

## Steps to Reproduce
1. Navigate to https://www.kbb.com/honda/civic/2016/styles/?intent=trade-in-sell
2. Select _Sedan_

## Actual result:
No further information is revealed.

## Expected result:
The user should be prompted to select the Sedan _style_.

## Reproduces how often: 
Easily.

## Brave version (brave://version info)
0.59.35

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? Yes
- Is the issue reproducible on the latest version of Chrome? No

### Additional Information
Reported on Twitter: https://twitter.com/ThePatToner/status/1097859497492733953

**Comment by snyderp** [comment]
Looks like this will be automatically fixed by an upstream EasyList change from @ryanbr 

https://github.com/brave/adblock-lists/pull/83#issuecomment-501852869

@rebron is it good to close?

**Comment by bsclifton** [comment]
Verified this is good to go; closing
