### ISSUE TITLE
Remove Hardware Wallet Icon from Blockie Icons

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#34193]
## Description 

Now that we have updated the `Blockies` package, we need to remove the `Thumbdrive` icons for hardware wallets on the blockies

![Screenshot 65](https://github.com/brave/brave-browser/assets/40611140/cf672685-675b-4ce2-b6f2-ff4346a6d312)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.62.146 Chromium: 120.0.6099.234 (Official Build) beta (64-bit)
-- | --
Revision | 85d26e25365bbea90074b7bc40ab0c89bbbf26e8
OS | Windows 11 Version 23H2 (Build 22631.3007)

- Verified steps from [brave/brave-core#20899](https://github.com/brave/brave-core/pull/20899)
- Verified `Thumbdrive` icon is removed from hardware account blockie

![Screenshot 2024-01-18 031005](https://github.com/brave/brave-browser/assets/17010094/3e6cd94b-70e2-403c-8478-4848176b2ddd)
