### ISSUE TITLE
Updated horizontal tabs have unselectable space between them

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#34190]
## Description 

With updated horizontal tabs, there is a 4px gap between consecutive tab shapes. Currently, this space is not selectable. 

## Steps to Reproduce

   1. Enable `#brave-horizontal-tabs-update`
   2. Restart the browser
   3. Open several tabs
   4. Move the mouse between tabs

## Actual result:

When the mouse is between tabs, they cannot be selected.

## Expected result:

When the mouse is between tabs, the nearest one should be selectable (and show a hover state)

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.62.35 Chromium: 119.0.6045.105 (Official Build) nightly (64-bit)
-- | --
Revision | 7fd1f70f3e886d12f40eccbd712723b1662a1f38
OS | Windows 11 Version 22H2 (Build 22621.2428)
```

1. Installed 1.62.35
2. launched Brave
3. opened brave://flags in a new tab
4. enabled `#brave-horizontal-tabs-update`
5. restarted the browser
6. opened several tabs
7. moved the mouse between tabs

Actual results: Not seeing when the mouse is between tabs, the nearest one should be selectable and show a hover state


https://github.com/brave/brave-browser/assets/98358127/2d4fe585-4c3c-4081-b305-faf1720218e3

**Comment by aeimi** [comment]
🤦 Oh man, please. The "dead margin" between top of the screen and tabs is even more important.  Really I can't get it. Why you people make so obvious things so hard. While targeting tabs it's way easier to just move mouse up to the top of screen where it naturally stops. It's not about visual separation from the top, but functional. Check out Firefox if you will to see what I mean. 

And I'm sorry but I feel really weird about how such obvious thing can not be seen, while you recording demo. Use mouse as gamer. Fast movements to target the tabs. Then you'll get why tabs activating on edge of the screen is so important. As between as on top, 0px of inactive state. Visually they can have gap (as Firefox have, if you must impose this style) but not functionally.  And for a last time I suggest, give users and option in settings. To use classic tabs (as everyone knows it) or this new extra padded pill style tabs.

**Comment by kjozwiak** [comment]
The above requires `1.61.75` or higher for `1.61.x` verification 👍 Removing `QA Pass-Win64` as the above will need to be verified on `1.61.x` now that it's been uplifted into `1.61.x`. Used https://github.com/brave/brave-browser/issues/34190#issuecomment-1802768867 as the verification for Nightly as per https://github.com/brave/brave-core/pull/20947#pullrequestreview-1728400025.

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.61.75 Chromium: 119.0.6045.134 (Official Build) beta (64-bit)
-- | --
Revision | 1b1191cb2465b2b90a5e8fea4a63aed1cfca47f5
OS | Windows 11 Version 22H2 (Build 22621.2428)
```

1. Installed 1.61.75
2. launched Brave
3. opened `brave://flags` in a new tab
4. enabled `#brave-horizontal-tabs-update`
5. restarted the browser
6. opened several tabs
7. moved the mouse between tabs


https://github.com/brave/brave-browser/assets/98358127/fbd3e18f-35a4-4d72-99fd-48ea2b917260

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.61.75 Chromium: 119.0.6045.134 (Official Build) beta (x86_64)
-- | --
Revision | 1b1191cb2465b2b90a5e8fea4a63aed1cfca47f5
OS | macOS Version 11.7.10 (Build 20G1427)
```


### Steps:
1. installed `1.61.75`
2. launched Brave
3. opened `brave://flags`
4. set `brave://flags/#brave-horizontal-tabs-update` to `Enabled`
5. clicked `Relaunch`
6. loaded a bunch of news-related sites
7. moved the mouse between tabs

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.61.83 Chromium: 119.0.6045.163 (Official Build) beta (64-bit) 
Revision	f5a497784a959e96317dc946d9086098d8fa6c50
OS	Linux
```

**Comment by psarno** [comment]
The dead space is quite maddening.   `#brave-horizontal-tabs-update` went to "(Default*)" enabled at some point it seems (or A/B testing and I got it), as I just started noticing this.

Moving the mouse to the upper left corner no longer selects the first tab.  The gap between tabs means you can now click between them, which results in nothing happening.

If this is the desired behavior, then so be it, as long as the flag can be set to disable it.
