### ISSUE TITLE
Network Placeholder Icons are small

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#34194]
## Description 

The network `Placeholder` icons are smaller then they should be

## Steps to Reproduce

   1. Add a custom network and then open the network selector
   2. The `Placeholder` icon is smaller then the rest of the network icons

## Actual result:

![Screenshot 66](https://github.com/brave/brave-browser/assets/40611140/0be09361-e237-4773-af92-c2f4013cb0da)

## Expected result:
Should be the same size as the other network icons

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.62.130 Chromium: 120.0.6099.199 (Official Build) beta (64-bit)
-- | --
Revision | `6d589c6dc0f3489830d40332c82cdd5597e41c88`
OS | Windows 11 Version 23H2 (Build 22631.2861)

- Verified steps from [brave/brave-core#20901](https://github.com/brave/brave-core/pull/20901)
- Verified network placeholder icons are of the same size as default ones
![brave_vQD6ltJ4gN](https://github.com/brave/brave-browser/assets/17010094/89f1bb65-93e0-4ef3-85ff-2bba0641cc50)

---------------------

**Verification passed on**

Brave | 1.62.130 Chromium: 120.0.6099.199 (Official Build) beta (64-bit)
-- | --
Revision | `6d589c6dc0f3489830d40332c82cdd5597e41c88`
OS | Linux

- Verified steps from [brave/brave-core#20901](https://github.com/brave/brave-core/pull/20901)
- Verified network placeholder icons are of the same size as default ones
![NetworkLogo](https://github.com/brave/brave-browser/assets/17010094/3a6b7265-aab7-4089-84df-2c4d9187fc27)

---------------------

**Verification passed on**

Brave | 1.62.130 Chromium: 120.0.6099.199 (Official Build) beta (arm64)
-- | --
Revision | `6d589c6dc0f3489830d40332c82cdd5597e41c88`
OS | macOS Version 14.2.1 (Build 23C71)

- Verified steps from [brave/brave-core#20901](https://github.com/brave/brave-core/pull/20901)
- Verified network placeholder icons are of the same size as default ones
![image](https://github.com/brave/brave-browser/assets/17010094/f82baa41-2d83-4712-be82-63814e588c93)
