### ISSUE TITLE
Reduce patching for account consistency once this is available

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#342]
When this lands:

https://chromium.googlesource.com/chromium/src.git/+/4fd11d48d6c82826fe8c84aaaf81d9449d81c23e

We can check to see if this can be removed:
https://github.com/brave/brave-core/pull/170#issuecomment-397337596

cc @bridiver

**Comment by bsclifton** [comment]
Closing as stale - patches from https://github.com/brave/brave-core/pull/170 seem to be removed now 👍
