### ISSUE TITLE
Move default currency queries to dedicated endpoint file

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#34202]
## Description 

Move default currency queries from api.slice to an dedicated endpoint file

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.62.130 Chromium: 120.0.6099.199 (Official Build) beta (64-bit)
-- | --
Revision | `6d589c6dc0f3489830d40332c82cdd5597e41c88`
OS | Windows 11 Version 23H2 (Build 22631.2861)

- Verified steps from [brave/brave-core#20902](https://github.com/brave/brave-core/pull/20902)
- Verified Fiat currency value continue to render without any issues

---------------------

**Verification passed on**

Brave | 1.62.130 Chromium: 120.0.6099.199 (Official Build) beta (64-bit)
-- | --
Revision | `6d589c6dc0f3489830d40332c82cdd5597e41c88`
OS | Linux

- Verified steps from [brave/brave-core#20902](https://github.com/brave/brave-core/pull/20902)
- Verified Fiat currency value continue to render without any issues

---------------------

**Verification passed on**

Brave | 1.62.130 Chromium: 120.0.6099.199 (Official Build) beta (arm64)
-- | --
Revision | `6d589c6dc0f3489830d40332c82cdd5597e41c88`
OS | macOS Version 14.2.1 (Build 23C71)

- Verified steps from [brave/brave-core#20902](https://github.com/brave/brave-core/pull/20902)
- Verified Fiat currency value continue to render without any issues
