### ISSUE TITLE
[Vertical tabs] Frame button mis-positioned on linux with title bar

### ISSUE THREAD

**Issue by rillian** [brave/brave-browser#34201]
## Description 

Follow-up to https://github.com/brave/brave-browser/issues/33928 which showed a similar misalignment when the title bar was hidden, as it is by default on the more popular desktop environments.

## Steps to Reproduce

   1. Open settings (brave://settings in the address bar)
   2. Search for 'tab'
   3. Click to enable 'Use vertical tabs'
   4. Click to select 'Show title bar'

## Actual result:

Close button and other window decorations are drawn half on the toolbar, half on the title bar, neither aligned with the other toolbar buttons nor in the expected place in the title bar.

![image](https://github.com/brave/brave-browser/assets/225102/28896194-124d-4b0f-b736-9dc43ee383d0)

## Expected result:
Close button (and min/max buttons, if the desktop theme includes them) should be aligned with the other toolbar buttons as they are when the title bar is not shown

## Reproduces how often: 

Always. Tried both Fedora 39 (gnome-shell) and Pop OS 22.04.

## Brave version (brave://version info)

1.62.32 Chromium: 119.0.6045.105 (Official Build) nightly (64-bit) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by biohazard2117** [comment]
Having the same issue even without toggling on the "show title bar".  

[Version 1.60.114 Chromium: 119.0.6045.124 (Official Build) (64-bit)](https://brave.com/latest/)
![image](https://github.com/brave/brave-browser/assets/76464364/e46fb459-445d-4f35-bc8f-ed552d2c4937)

**Comment by kjozwiak** [comment]
The above requires `1.60.120` or higher for `1.60.x` verification 👍

**Comment by btlechowski** [comment]
Verified with

Brave | 1.60.124 Chromium: 119.0.6045.163 (Official Build) (64-bit)
-- | --
Revision | 803c85554783c998a840f4b211c94236409a9928
OS | Linux

Verified test plan for the description

Reproduced the issue:
![image](https://github.com/brave/brave-browser/assets/34715963/f8545305-966c-4f63-8e8f-f6e78fce0174)

Verified the issue:
![image](https://github.com/brave/brave-browser/assets/34715963/153d6e68-8d64-4645-a1af-48a00cacdc3b)
