### ISSUE TITLE
Perf: add erc721 token metadata to base query cache

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#34203]
## Description 

Allow erc721 token metadata  to be utilized by multiple endpoints without refetching or dispatching additional actions

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.62.130 Chromium: 120.0.6099.199 (Official Build) beta (64-bit)
-- | --
Revision | 6d589c6dc0f3489830d40332c82cdd5597e41c88
OS | Windows 11 Version 23H2 (Build 22631.2861)

- Verified steps from [brave/brave-core#20904](https://github.com/brave/brave-core/pull/20904)
- Verified ERC721 token metadata continue to function without regression
