### ISSUE TITLE
Pending verification's/Release Notes from 1.60.x - Release #2

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#34208]
Current list of issues that have been fixed/resolved in [`1.60.x - Release #2`](https://github.com/brave/brave-browser/milestone/440) but haven't been verified by QA and should be completed for `1.60.x - Release #3`

* Updated l10n for 1.60.x release. Round II. #34132
* Problematic first party elements are not blocked by Shields in Standard mode #34081

Current list of issues that were `release-notes/include` via `1.60.x Release #2` and should be added into the release notes for `1.60.x - Release #3`:

* Problematic first party elements are not blocked by Shields in Standard mode #34081

**Comment by kjozwiak** [comment]
Closing/Labelling as `QA-Pass` as both https://github.com/brave/brave-browser/issues/34132 & https://github.com/brave/brave-browser/issues/34081 have been verified on `Android` 👍
