### ISSUE TITLE
Token Placeholder Icons not working on Account Details

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#34204]
## Description 

The token `Placeholder` icons are not working on the `Account Details` tab

## Steps to Reproduce

   1. Add a custom token without an icon
   2. Go to an `Accounts Details`
   3. The `Placeholder` icon never loads for that custom token

## Actual result:

![Screenshot 72](https://github.com/brave/brave-browser/assets/40611140/ce52f38d-740d-4637-b93c-178142d76f25)

## Expected result:

![Screenshot 73](https://github.com/brave/brave-browser/assets/40611140/7974cb37-8917-4fb8-afce-c5816554c5f5)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.62.130 Chromium: 120.0.6099.199 (Official Build) beta (64-bit)
-- | --
Revision | `6d589c6dc0f3489830d40332c82cdd5597e41c88`
OS | Windows 11 Version 23H2 (Build 22631.2861)

- Verified steps from [brave/brave-core#20905](https://github.com/brave/brave-core/pull/20905) 
- Verified token placeholder icons work as expected
![image](https://github.com/brave/brave-browser/assets/17010094/deb04160-1366-4cd1-878a-0dc46d2e0459)


---------------------

**Verification passed on**

Brave | 1.62.130 Chromium: 120.0.6099.199 (Official Build) beta (64-bit)
-- | --
Revision | `6d589c6dc0f3489830d40332c82cdd5597e41c88`
OS | Linux

- Verified steps from [brave/brave-core#20905](https://github.com/brave/brave-core/pull/20905) 
- Verified token placeholder icons work as expected
![token](https://github.com/brave/brave-browser/assets/17010094/c35c3508-1269-447a-8ac0-45b2dc91cf95)

---------------------

**Verification passed on**

Brave | 1.62.130 Chromium: 120.0.6099.199 (Official Build) beta (arm64)
-- | --
Revision | `6d589c6dc0f3489830d40332c82cdd5597e41c88`
OS | macOS Version 14.2.1 (Build 23C71)

- Verified steps from [brave/brave-core#20905](https://github.com/brave/brave-core/pull/20905) 
- Verified token placeholder icons work as expected
![image](https://github.com/brave/brave-browser/assets/17010094/105d99ce-1981-4415-a75c-c772e33465a3)
