### ISSUE TITLE
Ads Panel in 0.60.x should have 'Coming Soon' text

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#3421]
## Description 
As per https://github.com/brave/brave-browser/issues/3141 Ads panel on 0.60.x Release Channel should reflect 'Coming Soon' as it did with 0.59.x on Release Channel

## Steps to Reproduce

Scenario 1
   1. Clean profile on 0.60.44 Release Channel build
   2. Enable Rewards
   3. View Ads Panel

Scenario 2
   1. Clean profile on 0.59.35 Release Channel version
   2. Enable Rewards
   3. Update to 0.60.44
   4. View Ads panel

## Actual result:
0.60.44 shows
![screen shot 2019-02-19 at 2 00 54 pm](https://user-images.githubusercontent.com/28145373/53041504-29842700-3452-11e9-9a4f-4deccabfbb7a.png)

## Expected result:
0.59.35
![screen shot 2019-02-19 at 1 55 52 pm](https://user-images.githubusercontent.com/28145373/53041509-2ee17180-3452-11e9-8490-c6f4b911eddf.png)

## Reproduces how often: 
Easily

## Brave version (brave://version info)

Brave | 0.60.44 Chromium: 72.0.3626.109 (Official Build) (64-bit)
-- | --
Revision | fae8db7ab9280fa6704a59980263c804f809ebd5-refs/branch-heads/3626@{#857}
OS | Mac OS X

### Reproducible on current release: 
- Does it reproduce on brave-browser dev/beta builds? n/a - this needs to be on Release Channel only 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

### Additional Information
cc @mandar-brave @jsecretan

**Comment by kjozwiak** [comment]
@LaurenWags ads are still disabled and there's no way of enabling them correct? It's just not using the correct "Coming soon" asset in `brave://rewards`?

**Comment by LaurenWags** [comment]
correct @kjozwiak . I launched 0.60.44 with `1. --enable-logging=stderr --vmodule=brave_ads=3 --brave-ads-debug`, enabled Rewards (not able to enable Ads), and verified no `AdsService` messages in terminal. If there's another way I can/should be checking that Ads isn't running in the background that would be good info to have as well.

**Comment by kjozwiak** [comment]
@mrose17 @jsecretan is there any other way to make sure that the ad service isn't running other than what @LaurenWags mentioned above?

@mandar-brave @rebron I don't think this is a blocker. As @LaurenWags mentioned above, seems like ads are disabled but the messaging is off under `brave://rewards` where it doesn't show the "Coming Soon" message. Thoughts?

**Comment by mrose17** [comment]
that is the only way that i know of.

**Comment by tmancey** [comment]
You can also check that files in the `Default/ads_service` directory are not created or updated when Ads is turned off

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.60.45 Chromium: 72.0.3626.109 (Official Build) (64-bit)
-- | --
Revision | fae8db7ab9280fa6704a59980263c804f809ebd5-refs/branch-heads/3626@{#857}
OS | Mac OS X

* Verified upgraded profiles and clean profiles show the 'Coming soon' text for Ads
![screen shot 2019-02-21 at 5 44 00 pm](https://user-images.githubusercontent.com/28145373/53206933-4a8a7a80-3600-11e9-8c8b-8824273e20eb.png)
