### ISSUE TITLE
update private key backup warning text

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#34228]
## Description 

This message should use the term "private key" instead of "recovery-phrase"

<img width="590" alt="Screenshot 2023-11-09 at 10 29 48 AM" src="https://github.com/brave/brave-browser/assets/30185185/eff5f593-d268-4d29-924d-3912465595d6">

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.62.130 Chromium: 120.0.6099.199 (Official Build) beta (64-bit)
-- | --
Revision | `6d589c6dc0f3489830d40332c82cdd5597e41c88`
OS | Windows 11 Version 23H2 (Build 22631.2861)

- Verified steps from [brave/brave-core#20925](https://github.com/brave/brave-core/pull/20925)
- Verified private key backup text is updated and doesn't mention about recovery phrase
![brave_RgyrtUKpW1](https://github.com/brave/brave-browser/assets/17010094/cb56aaf9-ddff-449a-8169-e4f3ed531764)

---------------------

**Verification passed on**

Brave | 1.62.130 Chromium: 120.0.6099.199 (Official Build) beta (64-bit)
-- | --
Revision | `6d589c6dc0f3489830d40332c82cdd5597e41c88`
OS | Linux

- Verified steps from [brave/brave-core#20925](https://github.com/brave/brave-core/pull/20925)
- Verified private key backup text is updated and doesn't mention about recovery phrase
![PrivateKey](https://github.com/brave/brave-browser/assets/17010094/07bd2f41-4016-45d4-bc64-71a5cbf9d24d)

---------------------

**Verification passed on**

Brave | 1.62.130 Chromium: 120.0.6099.199 (Official Build) beta (arm64)
-- | --
Revision | `6d589c6dc0f3489830d40332c82cdd5597e41c88`
OS | macOS Version 14.2.1 (Build 23C71)

- Verified steps from [brave/brave-core#20925](https://github.com/brave/brave-core/pull/20925)
- Verified private key backup text is updated and doesn't mention about recovery phrase
![image](https://github.com/brave/brave-browser/assets/17010094/bea519ac-30ed-472b-9721-11442cf10617)
