### ISSUE TITLE
Referrer spoofing could disable login CSRF protections on some sites

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#3422]
Some sites (e.g. anything using the default [Django](https://security.stackexchange.com/questions/96114/why-is-referer-checking-needed-for-django-to-prevent-csrf) authentication system) use the `Referer` header in order to prevent [CSRF attacks on their login pages](https://security.stackexchange.com/questions/59411/how-to-protect-against-login-csrfre).

By setting the `Referer` to be the destination's origin (for cross-origin requests), we are essentially making sure that these security checks always pass, therefore making them ineffective at preventing CSRF attacks.

@diracdeltas suggested changing the referrer-spoofing code to:

1. **strip the referrer entirely on cross-origin navigation requests and iframe sub-resources**,
2. continue to spoof the referrer on cross-origin sub-resource requests, and
3. continue to send the full referrer on all same-origin requests.

**Comment by diracdeltas** [comment]
If we go with 1, let's come up with a plan to QA it for new webcompatibility breakage.

**Comment by diracdeltas** [comment]
looking at https://github.com/brave/brave-browser/wiki/Brave-Release-Schedule, if we got this change into a dev release, it seems that it would be in dev for ~6 weeks and beta for ~3 weeks before hitting the stable release channel. that might be good enough, depending on how many people are actively using dev/beta

**Comment by bbondy** [comment]
Re-opening this because it was failing browser tests and had to be reverted. 

```
14:34:27 [  FAILED  ] BraveContentBrowserClientReferrerTest.DefaultBehaviour, where TypeParam =  and GetParam() =  (658 ms)
14:34:27 [191/191] BraveContentBrowserClientReferrerTest.DefaultBehaviour (805 ms)
14:34:27 Retrying 1 test (retry #3)
14:34:28 [ RUN      ] BraveContentBrowserClientReferrerTest.DefaultBehaviour
14:34:28 [23530:23811:0324/073427.977652:ERROR:rewards_service_impl.cc(185)] Failed to read file: /private/var/folders/h4/yxf5y9nx2nb9mv3rqqyj61gw0000gp/T/.com.brave.Browser.5fL2Jv/dkJpr8T/Default/ledger_state
14:34:28 [23534:775:0324/073427.990706:ERROR:ledger_impl.cc(338)] Failed to initialize wallet
14:34:28 ../../brave/browser/brave_content_browser_client_browsertest.cc:493: Failure
14:34:28 Expected equality of these values:
14:34:28   referrer.url
14:34:28     Which is: 
14:34:28   kDocumentUrl
14:34:28     Which is: http://document.com/path?query
14:34:28 Stack trace:
```

The revert was merged here:
https://github.com/brave/brave-core/pull/2049

**Comment by bsclifton** [comment]
re-opening because the PR hasn't been reviewed/merged yet: https://github.com/brave/brave-core/pull/2070
(merging will close if it includes closing keywords)

**Comment by bbondy** [comment]
Re-opening because it breaks playing youtube embed videos.
See this issue for steps to reproduce: https://github.com/brave/brave-browser/issues/3988

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.67.107 Chromium: 75.0.3770.100 (Official Build) beta(64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Mac OS X

* Verified test plan from https://github.com/brave/brave-core/pull/2260
* Verified embedded video from https://github.com/brave/brave-browser/issues/3988 works
