### ISSUE TITLE
Link by stripe in Brave wallet purchase link not working when amount is empty

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#34221]
## Description 

A purchase amount is needed before the link works. We should require an valid amount value before letting the user view the purchase button

## Steps to Reproduce

   1. brave://wallet/crypto/fund-wallet/purchase
   2. select ETH
   3. leave amount empty
   4. click continue
   5. click the buy with Link from Stripe button

## Actual result:

console error is thrown and link does not open

## Expected result:
no console error, purchase link opens correct URL

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.63.141 Chromium: 121.0.6167.139 (Official Build) beta (64-bit)
-- | --
Revision | aa92f6cecec7f6c576bd1cf120f4cf359d770159
OS | Windows 11 Version 23H2 (Build 22631.3007)

- Verified steps from issue description
- Verified when input value is not entered Stripe option is not shown on list of providers
- Verified when input value is specified, Stripe option shows up and loads the purchase page correctly
- Verified no console errors when input value is added for token selection 

https://github.com/brave/brave-browser/assets/17010094/9be5e0ef-dbad-4802-9965-79436baf7976
