### ISSUE TITLE
Avoid switching network and account in Swap screen

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#34224]
Following https://github.com/brave/brave-core/pull/20836, we should avoid switching networks/accounts in Swap screen, and instead use local React state.

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.62.123 x64 Beta build
- Verified steps from [brave/brave-core#20923](https://github.com/brave/brave-core/pull/20923)
- Verified Swaps continue to work as expected
- Verified switching network/accounts via dropdown updates the balance correctly

https://github.com/brave/brave-browser/assets/17010094/e273496b-abdd-4ed5-a4d1-4c9523112607

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.62.130 Chromium: 120.0.6099.199 (Official Build) beta (64-bit)
-- | --
Revision | 6d589c6dc0f3489830d40332c82cdd5597e41c88
OS | Windows 11 Version 23H2 (Build 22631.2861)

- Verified steps from [brave/brave-core#20923](https://github.com/brave/brave-core/pull/20923)
- Verified Swaps continue to work as expected
- Verified switching network/accounts via dropdown updates the balance correctly

https://github.com/brave/brave-browser/assets/17010094/2a4f6bbd-a185-4265-a423-eaab4feacaf8
