### ISSUE TITLE
Update tabs sizing and spacing polish

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-browser#34229]
## Description 

After getting some feedback, I'm updating the tab bar to be a little bit more compact. This change will affect both horizontal and vertical tabs. Also Sidebar.

Figma with specs:
https://www.figma.com/file/H11ZOl6JMYbCTW4ZJXqR5V/%F0%9F%A6%81-Browser?type=design&node-id=125-9047&mode=design

## Actual result:

![image](https://github.com/brave/brave-browser/assets/15734630/30fda580-8990-4fcb-b896-0bd155d07279)

![image](https://github.com/brave/brave-browser/assets/15734630/58dd3bff-681f-4523-a9db-de4104b7dd21)

## Expected result:
![image](https://github.com/brave/brave-browser/assets/15734630/80673039-134e-4812-88f0-f92162cbf512)
![image](https://github.com/brave/brave-browser/assets/15734630/dc124fbc-b649-45d2-a5c9-1d990e2d8e33)

**Horizontal tabs**
- Horizontal TabBar height should be 40px tall total.
- Tabs and pinned tabs are 32px high. (pinned tabs are 32x32).
- Tab group labels are 32px high.
- Margin between tabs and edges of tabbar: 4px (32+4+4 = 40px)

**Vertical tabs**
- Vertical tabs are now 32px high too.
- Pinned tabs are 32x32.
- Collapsed vertical tabs bar is 40px wide (32px buttons and 4px paddings).
- Expanded vertical tab bar is 220px wide by default (Should account for 6 pinned tabs per row, with 4px separation between each of them)

**Sidebar**
- Sidebar items are also 32x32px.
- Sidebar total width is 40px (32px buttons and 4px paddings)

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.62.49 Chromium: 119.0.6045.134 (Official Build) nightly (x86_64)
-- | --
Revision | ebbe0beec9dfdb603463869912ad4ec19899293d
OS | macOS Version 11.7.10 (Build 20G1427)
```

## Confirmed there is tighter/less vertical spacing between icons and UI elements in `1.62.49` than there was in `1.62.39`

`1.62.39` | `1.62.49` | `Side-by-side`
---------|---------|------------------
<img width="1407" alt="Screen Shot 2023-11-13 at 1 01 17 PM" src="https://github.com/brave/brave-browser/assets/387249/63884285-bbb7-49c8-baab-24182adf056b"> |  <img width="1407" alt="Screen Shot 2023-11-13 at 1 02 34 PM" src="https://github.com/brave/brave-browser/assets/387249/d9f39bbd-99a1-430a-8081-4cc06308d91b"> | <img width="1317" alt="Screen Shot 2023-11-13 at 1 06 53 PM" src="https://github.com/brave/brave-browser/assets/387249/c1780aa8-5bb0-43fe-94eb-a18adb0d33e6">

**Comment by kjozwiak** [comment]
Removing `QA-Pass` as the above was uplifted into `1.61.x` via https://github.com/brave/brave-core/pull/21075 and will need to be rechecked using using `1.61.x` as the original verification was done on `1.62.x`. The above requires `1.61.85` or higher for `1.61.x` verification 👍

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.61.90 Chromium: 119.0.6045.163 (Official Build) beta (x86_64)
-- | --
Revision | 0e0de020c4ef9621e8a67a103299899837ce85a1
OS | macOS Version 11.7.10 (Build 20G1427)
```


## `Horizontal tabs`

## `Vertical tabs`

## `Sidebar`
