### ISSUE TITLE
Padding 'border' is shown Full screen and Full screen mode

### ISSUE THREAD

**Issue by MadhaviSeelam** [brave/brave-browser#34239]
## Description 

Found this issue while testing https://github.com/brave/brave-browser/issues/33879.

## Steps to Reproduce

1. Installed 1.61.69
2. launched Brave
3. opened brave://flags in a new tab
4. enabled #brave-web-view-rounded-corners flag
5. opened Private window via hamburger menu
6. visited a youtube.com in a new tab
7. play any video 
8. pressed F11 
9. press F 

## Actual result:

Border is still shown

https://github.com/brave/brave-browser/assets/98358127/4cc9c10a-c533-4d66-8f37-fc715e9b484f

## Expected result:
Border should not be shown

## Reproduces how often: 

Easily

## Brave version (brave://version info)

```
Brave | 1.61.69 Chromium: 119.0.6045.124 (Official Build) beta (64-bit)
-- | --
Revision | 802f2a3dd5b30780d7195156af577bc455f97ce9
OS | Windows 11 Version 22H2 (Build 22621.2428)
```
## Version/Channel Information:

- Can you reproduce this issue with the current release? N/A
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@zenparsing @rebron

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.62.55 Chromium: 119.0.6045.163 (Official Build) nightly (64-bit)
-- | --
Revision | ce690ff7151c64571e4ef446a61391320c127ebd
OS | Windows 10 Version 22H2 (Build 19045.3693)
```

### Followed @MadhaviSeelam 's steps to reproduce.

## Confirmed no border when entering fullscreen mode via both `f` and `F11`

https://github.com/brave/brave-browser/assets/387249/357f86e4-3ee8-4412-b773-a008f7b03aa5

**Comment by kjozwiak** [comment]
Removing the `QA-Pass` label as the above was uplifted into `1.61.x` from `master` via https://github.com/brave/brave-core/pull/21073.The above requires `1.61.85` or higher for `1.61.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on 

```
Brave | 1.61.85 Chromium: 119.0.6045.163 (Official Build) beta (64-bit)
-- | --
Revision | 5e2736df90772dd1b66ca5013e47c1fc467c9762
OS | Windows 10 Version 22H2 (Build 19045.3693)
```
Confirmed no border when entering fullscreen mode via both f and F11

https://github.com/brave/brave-browser/assets/38657976/bfae1424-e954-4817-b661-00200292d46b
