### ISSUE TITLE
Migrate Rewards Publisher ID / Creator detection content scripts out of Greaselion

### ISSUE THREAD

**Issue by zenparsing** [brave/brave-browser#34237]
Currently, Greaselion is used to deploy content scripts that are used by the Rewards feature to figure out publisher information corresponding to the content loaded into the current tab. We should move away from using Greaselion and use another option instead:

* Use the new script injector component for deploying scripts.
* Create a new render frame observer which injects scripts into certain pages.
* Use a "scriptlet" to execute scripts on the page, which will then communicate back to a content script in the brave extension, which will then communicate with the brave extension background page. (The content scripts in the brave extension would act as a new proxy layer.)
* Move all content scripts into the brave extension (this would sacrifice the ability to update the scripts outside of the browser release process).

Questions to consider:

* Are all content scripts currently working?
* How often are we changing the content scripts?
* Greaselion will currently only load the scripts if certain conditions are met (i.e. AC is on, or Rewards is enabled). Do we need to respect these conditions? How?

**Comment by Miyayes** [comment]
P2 for now but depends on Greaselion timeline.

**Comment by Miyayes** [comment]
We will be removing GitHub detection from Brave Rewards, so we do not need to implement it anew with this new creator detection implementation. cc: @LaurenWags

**Comment by LaurenWags** [comment]
@zenparsing could we get a test plan for this one please? Marking as `QA/Blocked` for now until we have that 👍🏻

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.74.9 Chromium: 131.0.6778.85 (Official Build) beta (64-bit)
-- | --
Revision | 30ceb433b8a77b995214506d3d862edb3220614b
OS | Windows 10 Version 22H2 (Build 19045.5131)
```

**Comment by LaurenWags** [comment]
Per discussion with @Miyayes @zenparsing we should fully test this on one OS (Windows preferably) and then sanity check on macOS/Linux as time allows.

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.74.15 Chromium: 131.0.6778.85 (Official Build) beta (arm64)
-- | --
Revision | d1293587128488865fa61e9fa277dd54aa2270b0
OS | macOS Version 12.5 (Build 21G72)

```

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.74.20 Chromium: 131.0.6778.108 (Official Build) beta (64-bit)
-- | --
Revision | 6f52e170fb1611fc69347fb24bca600ed052f7b3
OS | Linux
```
