### ISSUE TITLE
[Android] Enable Brave VPN on beta/nightly channel

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#34230]
- [ ] Enable vpn flag by default
- [ ] Update changes for In app purchase on beta/nightly channel
- [ ] Update changes for linking subscription on beta/nightly channel

**Comment by Uni-verse** [comment]
Verified on `Samsung Galaxy S21` using version: 

```
Brave	1.62.116 Chromium: 120.0.6099.144 (Official Build) beta (64-bit) 
Revision	632ccd5061221cfe5e1b9f3d14345cfd62db9655
OS	Android 13; Build/TP1A.220624.014; 33; REL
```
- Ensured that VPN is enabled by default on Beta channel (1.62.x).
- Ensured linking VPN subscription to `account.brave.com` page is successful when using the `link your subscription` button in settings.
- Ensured restoring VPN on Android & iOS platforms.
- Ensured that restoring VPN on `Beta` channel that was purchased on `Release` channel and vice versa.
- Ensured tunneling is enabled when VPN is enabled.
- Ensured `Brave VPN` is displayed in the main menu on fresh profile. 
- Ensured that option for linking is not shown on profile with VPN purchased in-app. 

_**Flag**_

Example | Example | Example
-|-|-
![Screenshot 2023-12-22 at 1 37 00 PM](https://github.com/brave/brave-browser/assets/17885425/1cf68eac-5157-426c-87eb-7dc15390b887) | ![Screenshot 2023-12-22 at 1 35 59 PM](https://github.com/brave/brave-browser/assets/17885425/42c0223b-d47b-4d2a-a324-a991eb42a554) | ![Screenshot 2023-12-22 at 1 36 07 PM](https://github.com/brave/brave-browser/assets/17885425/6b7721bf-661e-4ff9-808c-07f993b2b7a5)

_**Linking Subscription**_

Example | Example | Example | Example | Example
-|-|-|-|-
![Screenshot 2023-12-22 at 2 06 57 PM](https://github.com/brave/brave-browser/assets/17885425/b7d0857e-d296-4fe9-96a7-f5445f5d3711) | ![Screenshot 2023-12-21 at 6 21 38 PM](https://github.com/brave/brave-browser/assets/17885425/ac9c0c71-8964-422c-9efe-c919bd14d75b) | ![Screenshot 2023-12-21 at 6 21 49 PM](https://github.com/brave/brave-browser/assets/17885425/ff5c0d99-bfc7-4998-9366-0967da9f8a8b) | ![Screenshot 2023-12-21 at 6 21 55 PM](https://github.com/brave/brave-browser/assets/17885425/dfd36a38-3b6c-46e9-9b4f-1b5b6afad61b) | ![Screenshot 2023-12-21 at 6 22 18 PM](https://github.com/brave/brave-browser/assets/17885425/874399f0-1b63-435b-a14d-183457729363)

_**Restoring VPN (Android)**_
Example | Example | Example
-|-|-
![Screenshot 2023-12-21 at 7 31 31 PM](https://github.com/brave/brave-browser/assets/17885425/0246280a-4d53-4fe8-bee4-bec6a0f8f818) | ![Screenshot 2023-12-21 at 7 31 42 PM](https://github.com/brave/brave-browser/assets/17885425/c35e0f57-b12d-42e5-b156-cfebc15c4038) | ![Screenshot 2023-12-21 at 7 31 58 PM](https://github.com/brave/brave-browser/assets/17885425/e18d4bbf-9817-47e8-b6b1-e3ec98fb7420)

_**Restoring VPN (iOS)**_
Example | Example
-|-
![IMG_5469](https://github.com/brave/brave-browser/assets/17885425/4ccc0a7c-f8ab-4416-9ac2-94171b096ae6) | ![IMG_5470](https://github.com/brave/brave-browser/assets/17885425/751264d4-3828-412f-a0cf-5f5e346bb4a9)
