### ISSUE TITLE
[ads] Refactor public facing enums to use mojom

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#34242]
- [x] confirmation_type.h
- [x] ad_type.h

**Comment by btlechowski** [comment]
Verified on

Brave | 1.71.105 Chromium: 129.0.6668.89 (Official Build) beta (64-bit)
-- | --
Revision | f69ba167992437799f1dbcce81e90ba501a3d63e
OS | Linux

Verified test plan from https://github.com/brave/brave-core/pull/25446

#### ad_events

<details>

Verified `type`, `confirmation_type`

![image](https://github.com/user-attachments/assets/0e28cb0f-bb91-4133-a9f6-8d3f79b43b44)



</details>

#### ad_history

<details>

Verified `type`, `confirmation_type`
![image](https://github.com/user-attachments/assets/71154ca7-8dde-4232-bc4e-237dc5d2b5e3)



</details>

#### confirmation_queue

<details>

Verified `type`, `ad_type`

![image](https://github.com/user-attachments/assets/b1213aff-36e5-4f7a-a5b1-2870f778b219)



</details>

#### transactions

<details>

Verified `ad_type`, `confirmation_type`

![image](https://github.com/user-attachments/assets/79fdaa34-7bb4-4877-9e8c-3ebc7f0efc7f)



</details>
