### ISSUE TITLE
Better coin selection algorithm for bitcoin

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#34254]
Some randomized approach like done by sparrow wallet for example
https://github.com/sparrowwallet/drongo/blob/28551247c699c79561180dfe1c2b02db2b742a27/src/main/java/com/sparrowwallet/drongo/wallet/KnapsackUtxoSelector.java

**Comment by yrliou** [comment]
Closing as duplicate of https://github.com/brave/brave-browser/issues/34508.
