### ISSUE TITLE
Crashes after ≈5 seconds

### ISSUE THREAD

**Issue by Champe20** [brave/brave-browser#34256]
## Steps to Reproduce

   1. Download app from flathub
   2. Open
   3. Crash

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

- 1.60.114
- Linux (Flatpak)

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
        N/A
- Can you reproduce this issue with the beta channel? 
        N/A
- Can you reproduce this issue with the nightly channel?
        N/A 

## Other Additional Information:

- Is the issue reproducible on the latest version of Chrome? 
  No

**Comment by rebron** [comment]
cc: @wknapik

**Comment by aneeshlingala** [comment]
This also happens with the non-flatpak package.

**Comment by Champe20** [comment]
@wknapik I am on x86_64

**Comment by Champe20** [comment]
@wknapik I have been able to replicate the issue on Fedora based immutable distros such as Fedora Kinoite and uBlue, however I could not do the same on non-immutable distros such as Fedora KDE.

**Comment by mkarolin** [comment]
@Champe20, crash reports are typically stored under your profile directory. For example, on Ubuntu it would be `~/.config/BraveSoftware/Brave-Browser/Crash\ Reports/`. Please, check the folders there for `.dmp` files.

**Comment by Champe20** [comment]
@wknapik I have not been able to reproduce the issue, flatpak or otherwise since November 28.
