### ISSUE TITLE
[Feature Req] Dedicated Youtube player. Similar to Duck Player.

### ISSUE THREAD

**Issue by voidastro4** [brave/brave-browser#34260]
DuckDuckGo Browser has the Duck Player which plays YouTube videos.
This method would allow bypassing Google serving any dedicated anti-adblock javascript.

It would be a nice feature to have for Brave.

My understanding is that Duck Player steals the YouTube player, which may present a future attack vector to smuggle in javascript.

Brave could instead use the same methods used by projects such as yt-dlp to serve video via a custom player. Integration with Return Youtube Dislike and SponsorBlock would be welcome too.

**Comment by Gitchick57** [comment]
Agreed 💯



Nov 10, 2023, 1:34 PM by ***@***.***:

**Comment by rebron** [comment]
Thanks for the suggestion. Closing as dupe of https://github.com/brave/brave-browser/issues/33997, can follow progress there.
