### ISSUE TITLE
Better indicate when a premium user is rate limited (backend)

### ISSUE THREAD

**Issue by nvonpentz** [brave/brave-browser#34261]
[Community report](https://community.brave.com/t/leo-premium-suddenly-stopped-working/515702/2).

Currently, when a premium user has used all their credentials for the current time period, we do not indicate that to the user. They are still able to select premium models, but attempts to use them result in the generic connection error.  This happens because without valid premium credentials, the client selects the default domain (ai-chat.bsg.brave.com) rather than the premium one (ai-chat-premium.bsg.brave.com).

While users are in this state, we should disable the premium options.  Also, we should tell the user how much time remains until their next batch of credentials become valid, at which point they can resume using premium models.

**Comment by petemill** [comment]
@aguscruiz I suppose we need design treatment for this. Users will be premium, but have run out of premium tokens. So only non-premium models will be available. We'll know in how long they'll be able to use Premium features again. Did I get that right @nvonpentz ?

**Comment by aguscruiz** [comment]
How about this? 
https://www.figma.com/file/h7fKSJF2P556bZWfyLTfwD/Leo-MVP?type=design&node-id=5747%3A87414&mode=design&t=IFrvYr3CX4bYuzq1-1

Actual copy may need tweaking, @mattmcalister ?

**Comment by mattmcalister** [comment]
We should include a 'Learn more' link with info about rate limits

**Comment by nvonpentz** [comment]
Going to say this is closed by https://github.com/brave/brave-core/pull/21186, we can create another issue for frontend
