### ISSUE TITLE
Integrate IAP flows for Android for Leo premium on Android

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#34264]
This needs to handle both IAP and restoring previous purchases to this device.

**Comment by kjozwiak** [comment]
The above requires `1.63.154` or higher for `1.63.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP21.240119.009 release-keys
Brave build: 1.63.156
Chromium: 122.0.6261.43 (Official Build) (64-bit) 
```
---------------------------
<details>
<summary> Purchase new subscription </summary>

**STEPS:**
1. Launch Brave
2. Three-dot menu > Leo
3. Type a query > Send query > I understand
4. Three-dot menu on the Leo screen > *Verify `Limited` is shown*
5. Keep `Mixtral` or set `Claude Instant` as the language model
6. Keep chatting with Leo until you see `Response rate limit reached`
7. Tap `Upgrade now` > *Verify `Leo Premium` screen is shown, and the subscription price is there*
8. On the `Leo Premium` screen tap `Upgrade now`
9. Follow the flow > *Verify subscription can be purchased, and email with receipt is sent*
10. Open `Subscriptions` via Play Store > Account > Payments & subscriptions > Subscriptions OR Brave > Tree-dot menu > Settings > Leo > Manage Subscriptions > *Verify active subscription*

**ACTUAL RESULTS:**
- Verified that `Limited` is shown next to `Mixtral` and `Claude Instant` language models for free tier users
- Verified that `Go Premium` is shown for free tier users
- Verified that the limit can be reached for the free users, and the subscription price is shown on the `Leo Premium` screen
- Verified that the user can purchase a Leo Premium subscription, and an email with the receipt is sent to the user
- Verified that an active Leo Premium subscription is shown under `Subscriptions` in the Play Store account
- Verified that `Premium`, `Unlimited`, and `Manage subscription` are shown for pid tier users

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/15c8a3d0-367c-4ef6-9311-e72ee52c7686) | ![2](https://github.com/brave/brave-browser/assets/128532965/5187e8c3-a755-4288-b064-df71aa7c9e7f) | ![3](https://github.com/brave/brave-browser/assets/128532965/e88104d9-5112-4ffe-9920-e89ddad4ed44) | ![4](https://github.com/brave/brave-browser/assets/128532965/2c605a61-2784-4a6d-8167-ca90c922672d) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/f815d8b7-8faf-42ee-8a98-b224171d6675) | ![2](https://github.com/brave/brave-browser/assets/128532965/b619120b-05cd-4ba6-9dc0-35f362cd7106) | ![3](https://github.com/brave/brave-browser/assets/128532965/5e8012c4-a4dd-4263-8a6b-8eb1dda992b4) | ![4](https://github.com/brave/brave-browser/assets/128532965/dcce4241-4154-47a7-9d6d-f26f83f08fe0) |
</details>

<details>
<summary> Cancel subscription </summary>

**STEPS:**
1. Launch Brave
2. Have an active Leo subscription via the 1st scenario
3. Open `Subscriptions` via Play Store > Account > Payments & subscriptions > Subscriptions OR Brave > Tree-dot menu > Settings > Leo > Manage Subscriptions
4. Cancel Leo's subscription > *Verify*

**ACTUAL RESULTS:**
- Verified that Leo's subscription can be canceled

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/61016216-f74a-4057-be79-39f8ba92943a) | ![2](https://github.com/brave/brave-browser/assets/128532965/e8526fe0-eff1-4ed6-bce9-87b0c2a9bb5d) | ![3](https://github.com/brave/brave-browser/assets/128532965/4603e729-d666-406e-bc47-8d6583d2f2bf) |
</details>

<details>
<summary> Restore subscription </summary>

**STEPS:**
1. Launch Brave
2. Have an active Leo subscription via the 1st scenario
3. Delete and reinstall Brave
4. Launch Brave > Go through onboarding 
5. Open `Leo` > *Verify Premium subscription is active*

**ACTUAL RESULTS:**
- Verified that Leo's Premium subscription can be restored

---------------------------

https://github.com/brave/brave-browser/assets/128532965/fdce3d75-efb6-4fba-8d5f-1bfdd0e3b9b2
</details>
