### ISSUE TITLE
`Add funds` and `Rewards settings` are not translated in Rewards Panel

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#3426]
## Steps to Reproduce

   1. Change the language to `Polish`
   2. Enable rewards
   3. Open a site
4. Open Rewards Panel

## Actual result:

`Add funds` and `Rewards settings` are not translated
![image](https://user-images.githubusercontent.com/34715963/53062221-60912180-34c0-11e9-8206-8154bc09361a.png)

Also reproduced on: Arabic, Bulgarian, Chinese(Traditional), Croatian, Czech, Danish, Dutch, Finish, French, German, Greek, Hebrew, Hungarian, Italian, Japanese, Korean, Lithuanian, Polish, Portuguese, Russian, Slovak, Slovenian, Spanish, Turkish, Vietnamese

Rewards Panel is not translated at all to Norwegian, logged https://github.com/brave/brave-browser/issues/3425

## Expected result:
`Add funds` and `Rewards settings` are translated

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.60.44 Chromium: 72.0.3626.109 (Official Build) (64-bit)
-- | --
Revision | fae8db7ab9280fa6704a59980263c804f809ebd5-refs/branch-heads/3626@{#857}
OS | Windows 7

cc @brave/legacy_qa @NejcZdovc @bbondy

**Comment by btlechowski** [comment]
The issue has not been fixed.

Tested on 

Brave | 0.63.4 Chromium: 73.0.3683.67 (Official Build) dev (64-bit)
-- | --
Revision | a83fd4f3207ae83412d329a9ca1239dd1e068345-refs/branch-heads/3683@{#760}
OS | Windows 7 Service Pack 1 Build 7601.24312

![image](https://user-images.githubusercontent.com/34715963/54251465-a3866800-4547-11e9-81b2-66f4abe714c4.png)

**Comment by NejcZdovc** [comment]
@btlechowski we added translation strings, but not sure if strings were actually translated yet

**Comment by NejcZdovc** [comment]
cc @bbondy

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.63.40 Chromium: 74.0.3729.61 (Oficjalna wersja) beta (64-bitowa)
-- | --
Wersja | 5df2c8936783bd7575987e45d72a92fcf528496b-refs/branch-heads/3729@{#645}

- Verified the test plan and STR from the description
![image](https://user-images.githubusercontent.com/38657976/56132036-9f19f880-5fa6-11e9-857c-fbb1894d03b4.png)
