### ISSUE TITLE
Omnibox hover shadow is not shown

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#34271]
## Steps to Reproduce

   1. Mouse hover over omnibox when it's not focused
   2. 
   3. 

## Actual result:

No shadow

## Expected result:
Shadow

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.62.49 Chromium: 119.0.6045.134 (Official Build) nightly (x86_64)
-- | --
Revision | ebbe0beec9dfdb603463869912ad4ec19899293d
OS | macOS Version 11.7.10 (Build 20G1427)
```

## `Light`

`Hover shadow` | `Default`
-----------------|----------

## `Dark`

`Hover shadow` | `Default`
-----------------|----------
