### ISSUE TITLE
Why the bot in this repo build brave everyday even there is no update?

### ISSUE THREAD

**Issue by cyfung1031** [brave/brave-browser#34295]
<img width="1282" alt="Screen Shot 2023-11-13 at 19 32 56" src="https://github.com/brave/brave-browser/assets/44498510/d199cfd9-d1fd-4e3b-b620-bedde10d7b31">

<img width="1435" alt="Screen Shot 2023-11-13 at 19 34 02" src="https://github.com/brave/brave-browser/assets/44498510/e1a68403-58dd-4838-9413-68802d449891">

**Comment by dpthegrey** [comment]
interesting

**Comment by cyfung1031** [comment]
Could any one fix it?

https://github.com/brave/brave-core/blob/master/.github/workflows/codeql-analysis.yml

**Comment by bsclifton** [comment]
Hi folks - thanks for noticing this

`brave-browser` is managing the issues and the code itself you'll find under `brave-core`. We update both repo version on each build.
https://github.com/brave/brave-core

Thanks!
