### ISSUE TITLE
Follow up of PR #20725 - Enable rewards enters into the `Start using rewards` infinite loop in 1.62.47/1.62.45

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#34290]
## Description 
Found while testing the PR https://github.com/brave/brave-core/pull/20725
Enable rewards enters into the `Start using rewards` infinite loop in 1.62.47/1.62.45
## Steps to reproduce 

   1. Clean profile 1.62.45 or 1.62.47
   2. Tap on BR panel icon and click `Start using rewards`
   3. Select country from country dropdown
   4. Click on `Continue` and `Done`
   5. Tap on BAT icon, `Start using rewards` panel is shown again

## Actual result 
Enable rewards enters into the `Start using rewards` infinite loop in 1.62.47/1.62.45
## Expected result
Once rewards is enabled tap on BR panel should show rewrads settings option

## Issue reproduces how often 

Easy
## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? No
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86): a;;
   - Device type (Phone, Tablet, Phablet):all
   - Android version: 12
   
## Brave version
1.62.47 or 1.62.45

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/qa-team @deeppandya @Miyayes

**Comment by GeetaSarvadnya** [comment]
I have done further investigation on the issue, verified older versions of nighly build, the issue starts arising from the version `1.62.23` I see there are 2 rewards PR's merged in this version (https://github.com/brave/brave-core/pull/20795 and https://github.com/brave/brave-core/pull/20815) looks like one of them is causing this issue. I don't see any issue with the version `1.62.22` 
cc: @Miyayes @deeppandya @zenparsing @emerick @kjozwiak

**Comment by deeppandya** [comment]
> I have done further investigation on the issue, verified older versions of nighly build, the issue starts arising from the version `1.62.23` I see there are 2 rewards PR's merged in this version (https://github.com/brave/brave-core/pull/20795 and https://github.com/brave/brave-core/pull/20815) looks like one of them is causing this issue. I don't see any issue with the version `1.62.22` 
> 
> cc: @Miyayes @deeppandya @zenparsing @emerick @kjozwiak 

Thank you @GeetaSarvadnya I have found the issue. I will be creating a PR soon.

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Samsung galaxy version 12` running `Bravemonoarm64.apk_1.62.105`

Verified the following scenarios and ensured enable rewards works fine without any issues.

1. Enable rewards via BR panel
2. Reset rewards and again enable rewrads via BR panel 
3. Enable rewards via Hamburger menu `Brave Rewards` 
4. Enable rewards via NTP Brave rewards notification 
5. Enable rewards via BR panel, connect a custodian and reset rewards and re-enable rewards
