### ISSUE TITLE
feature request: password system with keepass

### ISSUE THREAD

**Issue by gerardo-junior** [brave/brave-browser#3429]
KeePass Password Safe is a free and open-source password manager based on a safe encrypted file, which would be very useful because today there is manager software for all platforms.

https://keepassxc.org/
https://www.keepassdx.com/
https://subdavis.com/Tusk/

once with this file opened from some directory it could be synced to all devices by user with drive, dropbox or ipfs

**Comment by tomlowenthal** [comment]
This is the sort of work best-suited to an extension.

**Comment by gerardo-junior** [comment]
an extension would not have the dynamic reading on disk permission only by uploading file to each change by default and an extension would not have permission to change the browser internal autofill system.

would not it be better to have that embedded in the browser? or brave have support NPAPI Plugins?

**Comment by tomlowenthal** [comment]
Every other password-manager uses an extension to integrate with web browsers. There's no reason Keepass should be an exception.

**Comment by bsclifton** [comment]
@gerardo-junior looks like there are a few options available in the Chrome Web Store:
https://chrome.google.com/webstore/search/keepass

We can't recommend one, but you may check them out and see if any meet your needs (and let us know)
