### ISSUE TITLE
Community report of Cheddar video crashing in Brave Dev Channel

### ISSUE THREAD

**Issue by lukemulks** [brave/brave-browser#3430]
## Description 

Community member reports video on Cheddar.com are crashing in Brave Dev Channel

Link to original report: https://community.brave.com/t/cheddar-partnership-site-video-crashes/45551 

## Steps to Reproduce

   1.  Go to cheddar.com
   2.  play video 
   3. 

## Actual result:

http://recordit.co/M0ump2dMUR 1

## Expected result:
Video playback 

## Reproduces how often: 

consistently for user that reports issue. 

## Brave version (brave://version info)

Version 0.62.4 Chromium: 73.0.3683.39 (Official Build) dev (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by lukemulks** [comment]
Unable to repro on win10 x64 dev channel: 
Version 0.62.4 Chromium: 73.0.3683.39 (Official Build) dev (64-bit)

**Comment by BrendanEich** [comment]
Any crash reports?

**Comment by bbondy** [comment]
@lukemulks could you get a crash ID from about:crashes ?

**Comment by ryanbr** [comment]
Just tested this. `https://cheddar.com/media/social-media-stock-update-ahead-of-earnings-season`

Video playback is fine, no crash seen. Safe to close @lukemulks ?

**Comment by ryanbr** [comment]
Re-tested before closing, video on front page of `https://cheddar.com/`  works.
