### ISSUE TITLE
Clicking on the `Open Playlist settings` button opens a new `brave://settings/playlist` tab each time

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#34309]
## Description 

Clicking on the `Open Playlist settings` button opens a new `brave://settings/playlist` tab each time

## Steps to Reproduce

   1. install `1.62.49`
   2. launch Brave
   3. click on `Playlist` in the sidebar
   4. click on `Open Playlist settings` on the top right
   5. go back to the `Playlist` tab and click on the `Open Playlist settings` icon again
   6. another tab with `brave://settings/playlist` opens
   7. repeat...

## Actual result:

Keeps opening a new `brave://settings/playlist` tab

<img width="1937" alt="Screen Shot 2023-11-13 at 3 39 54 PM" src="https://github.com/brave/brave-browser/assets/387249/a66d9261-56a1-4a18-bec9-e6357e2c2970">

## Expected result:

No new windows if `brave://settings/playlist` is already open

<img width="1374" alt="Screen Shot 2023-11-13 at 3 55 42 PM" src="https://github.com/brave/brave-browser/assets/387249/fb5e962e-5761-4f04-bea0-86602eeb5a48">

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave | 1.62.49 Chromium: 119.0.6045.134 (Official Build) nightly (x86_64)
-- | --
Revision | ebbe0beec9dfdb603463869912ad4ec19899293d
OS | macOS Version 11.7.10 (Build 20G1427)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `N/A`
- Can you reproduce this issue with the beta channel? `Probably`
- Can you reproduce this issue with the nightly channel? `Yes`

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@sangwoo @rebron @brave/qa-team

**Comment by rebron** [comment]
cc: @simonhong wdyt? Should be opening in a new tab each time.

**Comment by simonhong** [comment]
> cc: @simonhong wdyt? Should be opening in a new tab each time.

IMO, singleton tab would be better. I think we don't need to create another one if current window already has it.
FYI, leo panel's settings button also has same behavior.

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
 Brave | 1.62.73 Chromium: 119.0.6045.163 (Official Build) nightly (x86_64)
-- | --
Revision | 522e9147d931744b1641084046c197caf7b341f0
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Followed my original steps to reproduce

## Confirmed clicking on the `Open Playlist settings` gear icon opens `brave://settings/playlist` only once

example | example
---------|---------
<img width="1312" alt="Screen Shot 2023-11-22 at 12 10 40 PM" src="https://github.com/brave/brave-browser/assets/387249/0d9d9a9d-d557-43f2-bee5-e74f5d163142"> | <img width="1312" alt="Screen Shot 2023-11-22 at 12 10 44 PM" src="https://github.com/brave/brave-browser/assets/387249/7d3e2e77-bcc1-4bea-a427-57a66445e040">
