### ISSUE TITLE
Inconsistency with back and forward keyboard shortcuts in context menu

### ISSUE THREAD

**Issue by niklasbergercom** [brave/brave-browser#34306]
## Description 

When right-clicking on a web page, the context menu shows the keyboard shortcuts for back and forward, but the word "arrow" is written with a lowercase "a" for back but with a uppercase "A" for forward.

## Steps to Reproduce

   1. open any web page
   2. right click

## Actual result:

![2023-11-13_21-28](https://github.com/brave/brave-browser/assets/77928586/a5c33845-1465-480f-8abb-ab9b9365a4ef)

## Expected result:

"arrow" with an "a" both times or with an "A" 

## Reproduces how often: 

every time

## Brave version (brave://version info)

1.60.114 Chromium: 119.0.6045.124 (Official Build) unknown (64-bit) 
on Pop!_OS (Ubuntu-like, installed with Flatpak)

## Version/Channel Information:

- Can you reproduce this issue with the current release?  Yes
- Can you reproduce this issue with the beta channel? I don't know
- Can you reproduce this issue with the nightly channel? I don't know

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? I don't know

**Comment by rebron** [comment]
cc: @fallaciousreasoning

**Comment by shresth06** [comment]
Hey, I would like to work on this issue.

**Comment by AnudeepReddyBondugula** [comment]
The Issue has been resolved, you can close the issue

**Comment by bsclifton** [comment]
Thanks for confirming @AnudeepReddyBondugula 😄
