### ISSUE TITLE
Make Blockies Size Bigger in Wallet

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#34307]
## Description 

We need to update the `Blockies` size in the `Wallet` to be bigger.

## Steps to Reproduce

   1. 
   2. 
   3. 

## Actual result:

![Screenshot 8](https://github.com/brave/brave-browser/assets/40611140/bad3e74e-7fab-43fe-84de-345757eca92c)

## Expected result:

![Screenshot 12](https://github.com/brave/brave-browser/assets/40611140/28122b2d-a483-47a7-b13c-009b54f5b841)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.62.128 Chromium: 120.0.6099.144 (Official Build) beta (64-bit)
-- | --
Revision | `41f5844c06c7db1017f39b5b6dc9ba81a6b1b9d6`
OS | Windows 11 Version 22H2 (Build 22621.2506)

- Verified steps from [brave/brave-core#20967](https://github.com/brave/brave-core/pull/20967)
- Verified blockie size is bigger 
![brave_R9WnlItqMA](https://github.com/brave/brave-browser/assets/17010094/d1676e30-8d14-4072-a0a7-53330d160b55)

---------------------

**Verification passed on**

Brave | 1.62.128 Chromium: 120.0.6099.144 (Official Build) beta (64-bit)
-- | --
Revision | `41f5844c06c7db1017f39b5b6dc9ba81a6b1b9d6`
OS | Linux

- Verified steps from [brave/brave-core#20967](https://github.com/brave/brave-core/pull/20967)
- Verified blockie size is bigger 
![LinuxBlockie](https://github.com/brave/brave-browser/assets/17010094/81ca94f1-faad-4126-95b4-390f80ac2458)

---------------------

**Verification passed on**

Brave | 1.62.128 Chromium: 120.0.6099.144 (Official Build) beta (arm64)
-- | --
Revision | `41f5844c06c7db1017f39b5b6dc9ba81a6b1b9d6`
OS | macOS Version 14.2.1 (Build 23C71)

- Verified steps from [brave/brave-core#20967](https://github.com/brave/brave-core/pull/20967)
- Verified blockie size is bigger 
![image](https://github.com/brave/brave-browser/assets/17010094/eb1ff379-25cf-4651-aa3f-37346ad4fffd)
