### ISSUE TITLE
Leo localization

### ISSUE THREAD

**Issue by yongjer** [brave/brave-browser#34312]
## Description 
when pressing the summarisation in Leo, it will summarise in English, while the page is written in traditional Chinese

## Steps to Reproduce

   1. open any website written in traditional Chinese
   2. press summarization in Leo 
   3. 

## Actual result:
<img width="322" alt="截圖 2023-11-14 上午10 48 33" src="https://github.com/brave/brave-browser/assets/54315206/de0ec008-559b-4819-91ba-78de76e500f0">

## Expected result:
summarize in traditional Chinese

## Reproduces how often: 
always

## Brave version (brave://version info)
1.60.114 Chromium: 119.0.6045.124 (正式版本) (arm64)

**Comment by devingfx** [comment]
Yep! +1
I have a franch localized Brave, and Leo panel. Every response from LLAMA is in english whatever what you ask!
I tried to instruct it to speak french, to respond in french and even to reformulate responses in french and way :)
I'm not sure have seen other LLMs that GPT managing translation though...

**Comment by devingfx** [comment]
I finally could get some french out of Leo !!

```
> #### USER
traduit ceci en français:
I have a french localized Brave, and Leo panel. Every response from LLAMA is in english whatever what you ask!
I tried to instruct it to speak french, to respond in french and even to reformulate responses in french and no way :)
I'm not sure have seen other LLMs that GPT managing localisation though...

> #### Leo
Here's the translation of the text you provided into French:

"J'ai une version française localisée de Brave et du panneau Leo. Tous les responses de LLAMA sont en anglais, quelle que soit la question que je pose ! J'ai essayé d'instruire LLAMA pour qu'elle parle français, de répondre en français et même de reformuler ses réponses en français, mais pas question :) Je ne suis pas sûr d'avoir vu d'autres LLMs (modèles de langage grand public) gérer la localisation comme ça..."

I hope this helps! Let me know if you have any other questions or if there's anything else I can help you with.
```

**Comment by devingfx** [comment]
Maybe a locale option is needed managing to add special intro instruction to force LLAMA to speak a custom language...

**Comment by bbondy** [comment]
Related: https://github.com/brave/brave-browser/issues/33667

**Comment by bbondy** [comment]
Marking as QA/No for now because the server doesn't enable the locales yet.
