### ISSUE TITLE
Playlist item's runtime briefly displays `Nan::Nan` before displaying the full runtime

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#34310]
## Description 

Playlist item's runtime briefly displays `Nan::Nan` before displaying the full runtime

## Steps to Reproduce

1. install `1.62.49`
2. launch Brave
3. load a rather large `YouTube` video
4. click on the `Add to Playlist` button/icon in the Omnibar
5. find and add another video to the playlist
6. double-click to play the large video

## Actual result:

<img width="1837" alt="Screen Shot 2023-11-13 at 4 34 30 PM" src="https://github.com/brave/brave-browser/assets/387249/d43ed80d-f12f-4341-8bc4-42dc2198a72a">

## Expected result:

<img width="1837" alt="Screen Shot 2023-11-13 at 4 34 33 PM" src="https://github.com/brave/brave-browser/assets/387249/2f35d303-e764-438a-ae40-de23df2378ec">

## Brave version (brave://version info)

```
Brave | 1.62.49 Chromium: 119.0.6045.134 (Official Build) nightly (x86_64)
-- | --
Revision | ebbe0beec9dfdb603463869912ad4ec19899293d
OS | macOS Version 11.7.10 (Build 20G1427)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

@sangwoo108 @rebron @brave/qa-team

**Comment by sangwoo108** [comment]
#20916 would fix this

**Comment by sangwoo108** [comment]
Merged! Thanks

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.62.54 Chromium: 119.0.6045.134 (Official Build) nightly (x86_64)
-- | --
Revision | 812e299b26872e85e7c47f76519a5490f908155f
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Confirmed `Nan::Nan` no longer displays, and is correctly replaced by `00:00` before playing

pre-roll (caching/loading) | playing
--------|-------
<img width="327" alt="Screen Shot 2023-11-15 at 12 00 06 PM" src="https://github.com/brave/brave-browser/assets/387249/3dc0175a-3048-4db7-9523-8aed8c614a05"> | <img width="326" alt="Screen Shot 2023-11-15 at 12 00 17 PM" src="https://github.com/brave/brave-browser/assets/387249/89f59891-04fa-40bc-9d99-72dd8c2c50a7">
