### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Johnmarare** [brave/brave-browser#34313]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.60.110 Chromium: 119.0.6045.105
Operating System: Windows NT 10.0.19045

URL (if applicable) where crash occurred:

Can you reproduce this crash?

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Using my initial profile
2. could not even load a single page
3. Had not used the internet for a while, blamed it on windows update

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/c0360900-14aa-f80a-0000-000000000000

**Comment by iefremov** [comment]
stale
