### ISSUE TITLE
[ads] Purchase Intent weighting improvements

### ISSUE THREAD

**Issue by iambrianfung** [brave/brave-browser#34318]
Sites: 
When a user navigates a purchase intent segment domain, they should get additional weighting.
When a user navigates the same URL of a purchase intent segment, they should not get additional weighting.

This should be tab agnostic. Users navigating within the same tab on the same domain should continue to be weighted.

**Comment by tmancey** [comment]
Closing as resolved by https://github.com/brave/brave-browser/issues/34716

**Comment by btlechowski** [comment]
Verified with

Brave | 1.63.149 Chromium: 121.0.6167.164 (Official Build) beta (64-bit)
-- | --
Revision | 16509c04a66afcc00d180c0b62a887b9fc4776a2
OS | Linux

Verified test plan from the description

<details>

</details>
