### ISSUE TITLE
Hide Initial Shadow in the Wallet Panel Header

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#34319]
## Description 

There is an initial shadow that is displayed in the Wallet `Panel` header on first `Panel` launch.

## Steps to Reproduce

   1. Open the Wallet `Panel`
   2. There is an initial shadow that is displayed in the header

## Actual result:

![image](https://github.com/brave/brave-browser/assets/40611140/95a3a69b-4ace-4338-9b42-0af6c4bc35b6)

## Expected result:
There should not be an initial shadow, the shadow should only appear when the users scrolls down.

![Screenshot 13](https://github.com/brave/brave-browser/assets/40611140/3d4debf1-e6b9-4801-b8fd-5882792b9b55)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.62.128 Chromium: 120.0.6099.144 (Official Build) beta (64-bit)
-- | --
Revision | `41f5844c06c7db1017f39b5b6dc9ba81a6b1b9d6`
OS | Windows 11 Version 22H2 (Build 22621.2506)
- Verified steps from [brave/brave-core#20973](https://github.com/brave/brave-core/pull/209730
- Verified shadow is not shown in wallet panel header
![image](https://github.com/brave/brave-browser/assets/17010094/b2a2cf0f-6672-4cd8-bbbb-572da4140be3)


---------------------

**Verification passed on**

Brave | 1.62.128 Chromium: 120.0.6099.144 (Official Build) beta (64-bit)
-- | --
Revision | `41f5844c06c7db1017f39b5b6dc9ba81a6b1b9d6`
OS | Linux
- Verified steps from [brave/brave-core#20973](https://github.com/brave/brave-core/pull/209730
- Verified shadow is not shown in wallet panel header
![PanelShadow](https://github.com/brave/brave-browser/assets/17010094/179a570f-9713-4cf2-9c72-699d32739ae8)


---------------------

**Verification passed on**

Brave | 1.62.128 Chromium: 120.0.6099.144 (Official Build) beta (arm64)
-- | --
Revision | `41f5844c06c7db1017f39b5b6dc9ba81a6b1b9d6`
OS | macOS Version 14.2.1 (Build 23C71)

- Verified steps from [brave/brave-core#20973](https://github.com/brave/brave-core/pull/209730
- Verified shadow is not shown in wallet panel header
![image](https://github.com/brave/brave-browser/assets/17010094/387b3682-134a-4081-a897-f36ac32231d4)
