### ISSUE TITLE
Fix lxml missing dep error when running `chromium_rebase_l10n`

### ISSUE THREAD

**Issue by cdesouza-chromium** [brave/brave-browser#34323]
For `chromium_rebase_l10n` to be run, it requires `lxml`. This has a been a source of issues in the past. A simple workaround used recently is to install the package through `pip` in the local `depot_tools` used by the local install, however a more permanent solution has to be studied. It appears that `gclient` has an `update_pip` hook, which could possibly be where this should be fixed.

**Comment by mkarolin** [comment]
Fixed via https://github.com/brave/brave-core/pull/21540
