### ISSUE TITLE
Leo sometimes gives incomplete answers/stops responding

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#34321]
## Description 

Some users — including @AlanBreck — have reported that Leo sometimes simply stops mid response. At least two of these instances are using the Claude model (will update when the third confirms that model is in use, along with other info). This behavior occurs when summarizing pages and during standard responses:
![image](https://github.com/brave/brave-browser/assets/3299098/4876f0f0-1e4d-4afa-8c0f-143d928b115f)
![image](https://github.com/brave/brave-browser/assets/3299098/2f701770-fd89-4db8-9279-fafd34954086)
![image](https://github.com/brave/brave-browser/assets/3299098/b5b96fba-c2fa-4cd5-8f42-708efd5d482b)

## Reproduces how often: 

Consistently 

## Version/Channel Information:

Nightly at least

## Miscellaneous Information:

User reports:
https://community.brave.com/t/leo-only-generates-partial-message/516363
https://community.brave.com/t/claude-cuts-off-mid-sentence/515934/10

**Comment by Brave-Matt** [comment]
One of the users reporting this has the following setup:

> Brave Version: 1.62.52 Chromium 119.0.6045.134 (Official Build) nightly (64bit)
> Language Model: Llama2 13b
> 
> Windows 11 Enterprise|
> Version 22H2
> OS build|22621.2428
> Experience Windows Feature Experience Pack 1000.22674.1000.0

**Comment by Brave-Matt** [comment]
The other user seeing this (link in OP) has:

> Version 1.60.114 Chromium: 119.0.6045.124 (Official Build) (64-bit)
> On Devuan Daedalus, which is essentially Debian Bookworm without SystemD.

**Comment by ksoutherland** [comment]
> One of the users reporting this has the following setup:
> 
> > Brave Version: 1.62.52 Chromium 119.0.6045.134 (Official Build) nightly (64bit)
> > Language Model: Llama2 13b
> > Windows 11 Enterprise|
> > Version 22H2
> > OS build|22621.2428
> > Experience Windows Feature Experience Pack 1000.22674.1000.0

I'd like to add where this was my post in the community support that I downloaded the stable version of the browser as well and am still getting the same issues with the stable version of the browser and no matter the question or site I'm on all responses are from Leo are being cut short. So with the stable browser my setup looks like this:
Brave Version: 1.60.114 Chromium 119.0.6045.124 (Official Build) (64bit)
Language Model: Llama2 13b

Windows 11 Enterprise
Version 22H2
OS build 22621.2428
Experience Windows Feature Experience Pack 1000.22674.1000.0

**Comment by kjozwiak** [comment]
The above requires `1.60.121` or higher for `1.60.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.60.124 Chromium: 119.0.6045.163 (Official Build) (64-bit)
-- | --
Revision | 803c85554783c998a840f4b211c94236409a9928
OS | Windows 10 Version 22H2 (Build 19045.3693)
```
