### ISSUE TITLE
Crash Report - The thread tried to read from or write to a virtual address for which it does not have the appropriate access.

### ISSUE THREAD

**Issue by Deathnetworks** [brave/brave-browser#34333]
Constantly getting 'The thread tried to read from or write to a virtual address for which it does not have the appropriate access.' error.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/ea5f1d00-14aa-f80a-0000-000000000000

**Comment by iefremov** [comment]
stale
