### ISSUE TITLE
Brave shields notification icon is not scaled for double digits

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#3434]
Follow up from https://github.com/brave/brave-browser/issues/2295

## Steps to Reproduce

   1. Open a stream on twitch.tv

## Actual result:

The notification icon width for double digits is 12px
![image](https://user-images.githubusercontent.com/34715963/53132812-39465d00-3571-11e9-93e8-aa1991a0f248.png)

## Expected result:
The notification icon width for double digits is 14px
![notificationspec](https://user-images.githubusercontent.com/29072694/49398209-7cbbc880-f6f2-11e8-930c-43aaedc5fa69.png)

Check comment: https://github.com/brave/brave-browser/issues/2295#issuecomment-443848378

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Brave | 0.60.44 Chromium: 72.0.3626.109 (Official Build) (64-bit)
-- | --
Revision | fae8db7ab9280fa6704a59980263c804f809ebd5-refs/branch-heads/3626@{#857}
OS | Windows 7

cc @brave/legacy_qa @petemill @rossmoody

**Comment by rossmoody** [comment]
We can close this one down. I tried to be as precise as possible with my pixel increments but in the end @petemill was able to responsively size that notification bubble based on text width. If you hit a 7 digit it'll go to to 14px. If we're ever fortunate enough to get to 99+ I believe the font decreases in size as well. 

![screen shot on 2019-02-27 at 20 15 57](https://user-images.githubusercontent.com/29072694/53541007-b707ec80-3acc-11e9-9c01-1afabf2631c9.png)
