### ISSUE TITLE
Rewards extension process needs to be terminated when disabled, Follow up to #1475

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#3436]
## Description 

Based on #1475, it only hides the extension from UI but the background process continues to run which is waste of resources. When the extension is hidden from UI corresponding extension process needs to be terminated/killed off to conserve resources

## Steps to Reproduce

   1. Disable rewards from UI 
   2. Open Browser Task manager
   3. Still shows extension process running even though its hidden 

## Actual result:

![screenshot from 2019-02-21 08-00-12](https://user-images.githubusercontent.com/17010094/53139756-b04f1600-35b0-11e9-81e7-e9030f578a98.png)

## Expected result:
Should terminate the process when extension is hidden from UI

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.61.34 Chromium: 73.0.3683.39 (Official Build) beta(64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kklot** [comment]
Because of this tiny icon Brave is a goner for me.

**Comment by lmaclaren** [comment]
Icon aside, the fact that I can't disable this extension is incredibly obnoxious and undermines a big reason for me to use Brave in the first place.

**Comment by maclarel** [comment]
Brave is getting a hard pass from me until this is resolved. Wasting resources on something that is claimed to "do nothing" is incredibly shady.

**Comment by gabrielhug** [comment]
Shouldn't disabling rewards also terminate the Bat Ledger Service?

The rewards extension can be manually disabled for now with the command line argument --disable-brave-rewards-extension, but the Bat Ledger Service cannot be so easily disabled yet.

**Comment by bsclifton** [comment]
I think a patch like this would work- but you'd need to restart the browser if you wanted to either stop the process now or re-enable rewards
```patch
diff --git a/browser/extensions/brave_component_loader.cc b/browser/extensions/brave_component_loader.cc
index 11f0ab83a..19b499715 100644
--- a/browser/extensions/brave_component_loader.cc
+++ b/browser/extensions/brave_component_loader.cc
@@ -108,7 +108,8 @@ void BraveComponentLoader::AddDefaultComponentExtensions(
   }

 #if BUILDFLAG(BRAVE_REWARDS_ENABLED)
-  if (!command_line.HasSwitch(switches::kDisableBraveRewardsExtension)) {
+  if (!profile_prefs_->GetBoolean(kHideBraveRewardsButton) &&
+    !command_line.HasSwitch(switches::kDisableBraveRewardsExtension)) {
     base::FilePath brave_rewards_path(FILE_PATH_LITERAL(""));
     brave_rewards_path =
         brave_rewards_path.Append(FILE_PATH_LITERAL("brave_rewards"));
```

**Comment by simonhong** [comment]
@bsclifton I think @gabrielhug also want to prevent launching `Bat Ledger Service`.
For now, I think we don't have command line switch for that.
Disabling brave rewards is needed to prevent extension and utility service process.(https://github.com/brave/brave-browser/issues/1475#issuecomment-471380598)

**Comment by dylanh724** [comment]
What is the current status of this issue?

**Comment by srirambv** [comment]
+1 from @foamz via #4659

**Comment by rebron** [comment]
+1 from @bughit via #4612

**Comment by bridiver** [comment]
This should be a very simple change. We should not be adding the rewards extension in `AddDefaultComponentExtensions`. The rewards extension should be enabled/disabled in ExtensionRewardsServiceObserver by calling 
```
extensions::ExtensionSystem* extension_system =
      extensions::ExtensionSystem::Get(profile_);
extensions::ExtensionService* extension_service =
      extension_system->extension_service();
 auto* component_loader extension_service->component_loader();
DCHECK(component_loader);
base::FilePath brave_rewards_path(FILE_PATH_LITERAL(""));
brave_rewards_path = brave_rewards_path.Append(FILE_PATH_LITERAL("brave_rewards"));
component_loader->Add(IDR_BRAVE_REWARDS, brave_rewards_path);
```
when rewards is enabled and `Remove(brave_rewards_extension_id)` when rewards is disabled

**Comment by bridiver** [comment]
a non persistent background page is also better for resource usage when rewards is enabled

**Comment by jhult** [comment]
Any updates on this? I'm losing ~200 MB to stuff I don't use.

**Comment by arpit9295** [comment]
As a user with 4 gigs of RAM, those ~200MBs are really precious to me.
+1

**Comment by ilyaigpetrov** [comment]
I'm on Brave Nightly 0.73.26 and still see Brave Rewards and Bat Ledger Service eating memory in task manager of brave. I made sure that I disabled rewards in settings and restarted brave.

**Comment by bsclifton** [comment]
@ilyaigpetrov looking at master:
https://github.com/brave/brave-core/commits/master

Doesn't seem there's been a version published (yet) which has this fix. You can either hang tight until a new one goes public (should happen tomorrow) or you can download the latest non-published Nightly here:
https://github.com/brave/brave-browser/releases/tag/v0.73.31

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.71.105 Chromium: 78.0.3904.70 (Official Build) beta (64-bit)
-- | --
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS | macOS Version 10.13.6 (Build 17G5019)

* Confirmed STR from description. Note, Bat Ledger Service and Bat Ads Service are still running in the background without Rewards enabled. This is logged with #5429
* Verified test plan from https://github.com/brave/brave-core/pull/3698
Test plan 1 (single profile) before clicking on BAT logo - Brave Rewards extension is not running:
<img width="1119" alt="1-before clicking on BAT logo" src="https://user-images.githubusercontent.com/28145373/67890982-1b7dbe80-fb28-11e9-8355-2fa08e051e4b.png">
After clicking on BAT logo:
<img width="1126" alt="1-after clicking on BAT logo" src="https://user-images.githubusercontent.com/28145373/67890998-220c3600-fb28-11e9-954f-e1ed9cba5499.png">

Test plan 2 (single profile) upgraded profile with BR already on/opt-ed in:
<img width="1196" alt="2" src="https://user-images.githubusercontent.com/28145373/67891042-33edd900-fb28-11e9-87ef-c8400252aac1.png">

* Confirmed test plans 1&2 work as expected when a second profile is added.

**Comment by ask1234560** [comment]
Hi guys, any updates on this. I am still facing the issue.
Brave version - `1.35.103 Chromium: 98.0.4758.102 (Official Build) (64-bit)`

**Comment by dpthegrey** [comment]
Utility: Bat Ledger Service Still running
![image](https://user-images.githubusercontent.com/49444980/226102647-db9e72a6-86ac-4ee1-9cd4-75cb519272ea.png)

**Comment by ask1234560** [comment]
> Utility: Bat Ledger Service Still running ![image](https://user-images.githubusercontent.com/49444980/226102647-db9e72a6-86ac-4ee1-9cd4-75cb519272ea.png)

+1, issue exists
