### ISSUE TITLE
Remove Rewards inline tipping functionality

### ISSUE THREAD

**Issue by emerick** [brave/brave-browser#34367]
We updated the client to remove inline tipping functionality in https://github.com/brave/brave-browser/issues/33783. While this removed the buttons and related settings from the client, the tipping scripts are still bundled with Greaselion. We should update Greaselion to remove those unused scripts.

**Comment by LaurenWags** [comment]
Verification in progress on macOS x64 13.x with `Brave Local Data Updater - Version: 1.0.1127` and

```
Brave | 1.60.118 Chromium: 119.0.6045.163 (Official Build) (x86_64)
-- | --
Revision | b0599b790dbdfe28428202afe2b54758a044ccfc
OS | macOS Version 13.6.1 (Build 22G313)
```

and 

```
Brave | 1.62.57 Chromium: 119.0.6045.163 (Official Build) nightly (x86_64)
-- | --
Revision | ecdbb542296c7f884caf28fd148835f3be5286e5
OS | macOS Version 13.6.1 (Build 22G313)
```

Verified test plan from https://github.com/brave/brave-site-specific-scripts/pull/105#issue-1995112952.
