### ISSUE TITLE
Move wallet creation an import from extension code to queries and mutations

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#34365]
## Description 

Move wallet creation an import from extension code to queries and mutations.

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by LaurenWags** [comment]
@josheleonard could you add `QA/No` or `QA/Yes` as appropriate for this one? Thanks!

**Comment by josheleonard** [comment]
@LaurenWags Added the QA/Yes label

**Comment by srirambv** [comment]
**Verification passed on**

Brave | 1.62.128 Chromium: 120.0.6099.144 (Official Build) beta (64-bit)
-- | --
Revision | `41f5844c06c7db1017f39b5b6dc9ba81a6b1b9d6`
OS | Windows 11 Version 22H2 (Build 22621.2506)

- Verified steps from [brave/brave-core#20997](https://github.com/brave/brave-core/pull/20997)
- Verified wallet creation flow works as expected without regressions
- Verified wallet import via seed phrases continue to work without regressions
- Verified wallet import via MetaMask continue to work without regressions
- Verified wallet import via Legacy Wallet continue to work without regressions
- Verified seed phrase backup continue to work without regressions

---------------------

**Verification passed on**

Brave | 1.62.128 Chromium: 120.0.6099.144 (Official Build) beta (64-bit)
-- | --
Revision | `41f5844c06c7db1017f39b5b6dc9ba81a6b1b9d6`
OS | Linux

- Verified steps from [brave/brave-core#20997](https://github.com/brave/brave-core/pull/20997)
- Verified wallet creation flow works as expected without regressions
- Verified wallet import via seed phrases continue to work without regressions
- Verified wallet import via MetaMask continue to work without regressions
- Verified wallet import via Legacy Wallet continue to work without regressions
- Verified seed phrase backup continue to work without regressions

---------------------

**Verification passed on**

Brave | 1.62.128 Chromium: 120.0.6099.144 (Official Build) beta (arm64)
-- | --
Revision | `41f5844c06c7db1017f39b5b6dc9ba81a6b1b9d6`
OS | macOS Version 14.2.1 (Build 23C71)

- Verified steps from [brave/brave-core#20997](https://github.com/brave/brave-core/pull/20997)
- Verified wallet creation flow works as expected without regressions
- Verified wallet import via seed phrases continue to work without regressions
- Verified wallet import via MetaMask continue to work without regressions
- Verified wallet import via Legacy Wallet continue to work without regressions
- Verified seed phrase backup continue to work without regressions
