### ISSUE TITLE
Avoid switching network and account in Send screen

### ISSUE THREAD

**Issue by onyb** [brave/brave-browser#34375]
Following https://github.com/brave/brave-core/pull/20836, we should avoid switching networks/accounts in Send screen, and instead use local React state.

Similar issue for Swap: https://github.com/brave/brave-browser/issues/34224

**Comment by srirambv** [comment]
Verification passed on 
Brave | 1.62.130 Chromium: 120.0.6099.199 (Official Build) beta (64-bit)
-- | --
Revision | 6d589c6dc0f3489830d40332c82cdd5597e41c88
OS | Windows 11 Version 23H2 (Build 22631.2861)

- Verified steps from [brave/brave-core#21007](https://github.com/brave/brave-core/pull/21007)
- Verified send flow works as expected
- Verified send flow works for Ethereum, Solana, Filecoin tokens
- Verified send flow works for ERC20/SPL tokens and NFTs
- Verified selecting asset updates the query params in URL
- Verified grouping Portfolio by accounts and selecting an asset auto populates it in Send screen
- Verified selecting an account and selecting token menu and selecting Send auto populates it in the Send screen

-----------
Added [follow up issue](https://github.com/brave/brave-browser/issues/35266) for Android as its not working on Android
