### ISSUE TITLE
web.archive.org gives ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by AronVanAmmers** [brave/brave-browser#3437]
## Description 

When opening https://web.archive.org, I get `ERR_CONNECTION_RESET` and sometimes `ERR_CONNECTION_CLOSED`.  My network connection is fine. I've seen this about a week ago and again today (not tried in between), so it's not an intermittent issue. This doesn't happen in Chrome and Microsoft Edge on the same machine. Have tried disabling Brave shields.

## Steps to Reproduce

   1. Open https://web.archive.org in Brave 

## Actual result:

Usually `ERR_CONNECTION_RESET`. Sometimes `ERR_CONNECTION_CLOSED`. Status bar says "Establishing secure connection", "Waiting for web.archive.org"

![2019-02-21 11_02_53-web archive org - brave](https://user-images.githubusercontent.com/1123543/53160447-4b9fb580-35c8-11e9-8484-707e40001fa8.png)

## Expected result:

![2019-02-21 11_03_46-wayback machine](https://user-images.githubusercontent.com/1123543/53160511-6540fd00-35c8-11e9-81f3-7a90db1d0141.png)

## Reproduces how often: 

Easily reproduced on this system. Have seen it about a week ago. Not tried in between, seen it again today.

## Brave version (brave://version info)

Brave | 0.59.35 Chromium: 72.0.3626.81 (Official Build) (64-bit)
Revision | ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS | Windows

OS is Windows 10 with latest updates (version 1809).

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

Not tested.

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 

No.

- Is the issue reproducible on the latest version of Chrome?

No, web.archive.org opens fine on Chrome on this machine. Chrome Version 72.0.3626.109 (Official Build) (64-bit).

**Comment by AronVanAmmers** [comment]
Additional info:
* Not reproducible in a Private window
* Not reproducible in another Brave profile on same machine (I have 2 profiles)
* Reproducible in a normal window with all extensions disabled, HTTPS everywhere disabled, Safe browsing disabled, Shields down.

**Comment by tomlowenthal** [comment]
FWIW, I see this issue in Chrome but not in Brave. This makes me think that it's a profile-specific issue rather than a browser-specific one.

**Comment by ryanbr** [comment]
@AronVanAmmers Just a check in, does this work? Seems to be resolved/fixed

**Comment by AronVanAmmers** [comment]
@ryanbr just checked with Brave 1.2.43. Results the same, I can still reproduce it with the profile I used before, but not in a private window and not with a different profile. So indeed seems to be a profile-specific issue as @tomlowenthal suggested.

I would be happy for this issue to be closed as I have a satisfactory workaround (use the other profile when this happens).

**Comment by konarkmodi** [comment]
@AronVanAmmers :  ERR_CONNECTION_RESET seems to happen when the server receives an arbitrary large client request.

My best guess, looking at the issue right now is, somehow your browser is sending a large payload of cookies/query parameters to web.archive.org.

Cleaning the cookies for this domain will most likely solve this particular issue.

**Comment by AronVanAmmers** [comment]
> @AronVanAmmers : ERR_CONNECTION_RESET could happen when the server receives an arbitrary large client request.
> 
> My best guess, looking at the issue right now is, somehow your browser is sending a large payload of cookies/query parameters to web.archive.org.
> 
> Cleaning the cookies for this domain will most likely solve this particular issue.

That did it! Indeed I had 75 cookies between archive.org and web.archive.org (size in bytes unspecified). Clearing cookies fixed it.

Thanks @konarkmodi. Will close the issue and adapt the title to reflect.
