### ISSUE TITLE
Starting brave from the command line starts two windows

### ISSUE THREAD

**Issue by tetrode** [brave/brave-browser#3438]
## Description 

When I start brave from the command line (or development environment or other GUI program) it launches two windows, one with the URL that was passed and a second one with no URL.

This also happens when all extensions are disabled.

Running Version 0.59.35 Chromium: 72.0.3626.81 (Official Build) (64-bit)

## Steps to Reproduce

   1. start a terminal
   2. start /usr/bin/brave-browser

## Actual result:

two windows are launched

## Expected result:
one window is launched

## Reproduces how often: 

Always

## Brave version (brave://version info)

Version 0.59.35 Chromium: 72.0.3626.81 (Official Build) (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Have not tried this

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
No
- Is the issue reproducible on the latest version of Chrome? 
No

**Comment by kjozwiak** [comment]
Possibly related to #1833? @tetrode are you still experiencing this issue? Does it only happen once on a clean profile or every single time?

**Comment by tetrode** [comment]
Not happening anymore with me.

Mark
+ 32 474 92 06 59
.

**Comment by kjozwiak** [comment]
Thanks @tetrode 👍 I'm going to close this off as we also have #1833. If you run into this issue again, just re-open the bug.
