### ISSUE TITLE
[Speedreader] Enable Distillablity Service

### ISSUE THREAD

**Issue by boocmp** [brave/brave-browser#34388]
We use chromium "DistillabilityService" in the "on demand" mode of the "SpeedReader" feature. This dependency is broken.

We need to add the command line argument `--enable-distillability-service` on desktop platforms. At the moment, this parameter is passed only on Android.

Repro:

1. Navigate to https://www.bbc.com/future/bespoke/made-on-earth/how-the-chip-changed-everything/ or to https://www.cnet.com/tech/mobile/ios-16-and-android-13-what-they-say-about-the-future-of-phones/
2. Wait for the page to load.

Result:
  Speedreader icon is not visible.

Expected:
  Speedreader icon appears.

**Comment by kjozwiak** [comment]
The above requires `1.61.84` or higher for `1.60.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.61.85 Chromium: 119.0.6045.163 (Official Build) beta (64-bit)
-- | --
Revision | 5e2736df90772dd1b66ca5013e47c1fc467c9762
OS | Windows 10 Version 22H2 (Build 19045.3693)
```
Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/34388#issue-1996847634, ensured the following:

* ensured that `--enable-distillability-service` was being displayed in `brave://version`
* ensured that the `Speedreader` icon appeared when loading https://www.bbc.com/future/bespoke/made-on-earth/how-the-chip-changed-everything/
* ensured that enabling/disabling the `Speedreader` icon was working as expected/without any issues

**`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------
![image](https://github.com/brave/brave-browser/assets/38657976/d2a13d57-6bb3-4e33-b07b-5e20e3f23219) | ![image](https://github.com/brave/brave-browser/assets/38657976/11e6f24f-1de6-4196-8f94-08b63cf1df97) | ![image](https://github.com/brave/brave-browser/assets/38657976/dcd2f2b0-5417-4dc3-8760-a6752ebc9153)
