### ISSUE TITLE
Browser crash when closing a detached tab

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#34385]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.62.55 Chromium: 119.0.6045.163
Operating System: Windows NT 10.0.22631

URL (if applicable) where crash occurred:

Can you reproduce this crash? Yes, consistently on Nightly 

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Enable Vertical tabs
2. Set vertical tabs to collapsed view
3. Open a new tab and drag it into its own window
4. Close the dragged out tab 
5. Browser crashes

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/d9d40100-6629-0b0b-0000-000000000000
cc: @iefremov @brave/qa-team

**Comment by simonhong** [comment]
This crash starts from `1.62.19` and maybe https://github.com/brave/brave-core/pull/20535 causes it.

**Comment by GeetaSarvadnya** [comment]
Reproduced the issue on 

```
Brave | 1.62.61 Chromium: 119.0.6045.163 (Official Build) nightly (64-bit)
-- | --
Revision | 954a3ab0ea251a3ba50c6320c3a256aae88420ce
OS | Windows 10 Version 22H2 (Build 19045.3693)

```
