### ISSUE TITLE
`Block fingerprinting` `Disabled` preference doesn't get set when the `#brave-show-strict-fingerprinting-mode` flag is `Disabled`

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#34398]
## Description 

`Block fingerprinting` `Disabled` preference doesn't get set when the `#brave-show-strict-fingerprinting-mode` flag is `Disabled`

(Found while testing https://github.com/brave/brave-browser/issues/31229.)

## Steps to Reproduce

1. install `1.62.59`
2. launch Brave
3. open `brave://settings/shields`
4. set `Block fingerprinting` to `Disabled`
5. set `brave://flags/#brave-show-strict-fingerprinting-mode` to Disabled
6. click `Relaunch`
7. open `brave://settings/shields`

## Actual result:

`Block fingerprinting` is toggled to `On`/`Enabled`

<img width="1398" alt="Screenshot 2023-11-16 at 2 58 50 PM" src="https://github.com/brave/brave-browser/assets/387249/56dba158-442a-4858-b6d0-d15e2f077409">

## Expected result:

`Block fingerprinting` should be toggled to `Off`/`Disabled`

<img width="1398" alt="Screenshot 2023-11-16 at 2 59 41 PM" src="https://github.com/brave/brave-browser/assets/387249/2fdc1106-6531-4339-bced-77bc6b8a87fc">

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave | 1.62.59 Chromium: 119.0.6045.163 (Official Build) nightly (x86_64)
-- | --
Revision | e1b8145b091a14990d50127dc7ac0c407f8a13a6
OS | macOS Version 14.2 (Build 23C5047e)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `No`
- Can you reproduce this issue with the beta channel? `No`
- Can you reproduce this issue with the nightly channel? `Yes`

cc @arthuredelstein @rebron @fmarier @pes @brave/qa-team

**Comment by stephendonner** [comment]
![film-at-eleven](https://github.com/brave/brave-browser/assets/387249/cbf07d67-52cc-4e4e-b655-eece2a4d83ac)

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.62.69 Chromium: 119.0.6045.163 (Official Build) nightly (x86_64)
-- | --
Revision | 271270f8302c71e63d6cca16eee5578836d3fd96
OS | macOS Version 14.2 (Build 23C5047e)
```

### Followed my original steps to reproduce

## Confirmed `Block fingerprinting` was set to `Off`/`Disabled`

example | example | example
---------|----------|---------
<img width="1312" alt="Screenshot 2023-11-20 at 11 15 22 PM" src="https://github.com/brave/brave-browser/assets/387249/88eefdd1-71be-4724-ad20-9fa58fe114be"> | <img width="1312" alt="Screenshot 2023-11-20 at 11 15 57 PM" src="https://github.com/brave/brave-browser/assets/387249/930f06b7-b96d-40c2-b9da-6b712a614a0d"> | <img width="1312" alt="Screenshot 2023-11-20 at 11 16 07 PM" src="https://github.com/brave/brave-browser/assets/387249/e5d758f2-aa4b-4f55-a790-8f273eb3ec0b">

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.62.74 Chromium: 119.0.6045.163 (Official Build) nightly (64-bit)
-- | --
Revision | 070cd801c60b65bed66cfed719aeab87384ec9b8
OS | Windows 11 Version 21H2 (Build 22000.2538)
```

example | example | example
----------|-----------|----------
![image](https://github.com/brave/brave-browser/assets/387249/c6fb01c5-a6e3-43a1-81dd-657e06a745aa) |

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave	1.62.74 Chromium: 119.0.6045.163 (Official Build) nightly (64-bit) 
Revision	070cd801c60b65bed66cfed719aeab87384ec9b8
OS	Linux
```

**Comment by LaurenWags** [comment]
@arthuredelstein @pes10k could one of you please add `release-notes/exclude` or `release-notes/include` label as appropriate for this one? Thanks!

**Comment by pes10k** [comment]
done and done!

**Comment by stephendonner** [comment]
> done and done!

it...can't be both include and exclude 😉 

<img width="512" alt="Screen Shot 2023-11-28 at 2 05 22 PM" src="https://github.com/brave/brave-browser/assets/387249/3e531fe8-b2fd-495c-8f9f-9b79eda356f3">

**Comment by pes10k** [comment]
ah, okie, i defer to @arthuredelstein on this then.  I'll remove "include"
