### ISSUE TITLE
Where does brave stores the sidebar items/links 

### ISSUE THREAD

**Issue by yhoungdev** [brave/brave-browser#34396]
I have been looking for where brave browser saves this sidebar item.

how can i see where brave is saving or storing this sidebar items. 

i am using Linux and i have checks the ~/.config/Bravebrowser but still cant find it. Been on this for some days now. but still no remedy, so i decided to ask it here

![Screenshot from 2023-11-16 19-57-12](https://github.com/brave/brave-browser/assets/54102389/c86ce908-d34c-462e-b909-1a68dea4173e)

**Comment by yhoungdev** [comment]
Still needs help with this

**Comment by simonhong** [comment]
You can find them from `sidebar_items` in brave://prefs-internals/

**Comment by yhoungdev** [comment]
Ok awesome thanks alot for  this.

   But does brave still saves like some copies locally? 

  Just like how it does for brave://extension

**Comment by simonhong** [comment]
For now, sidebar items list is only stored in user data dir on local machine.
It's not synced yet across devices.

**Comment by yhoungdev** [comment]
Awesome. Am gonna check that.
  I was asking because I wanna write a script that backups my sidebar link automatically.


    Do you have any better approach on that ?

**Comment by simonhong** [comment]
Well... maybe you can see items list data(`sidebar_items`)  from your_user_data_dir/`Default/Preferences` json file.

**Comment by yhoungdev** [comment]
Thanks alot for the help, God bless

**Comment by simonhong** [comment]
Please make a backup that file if you touch. Otherwise, you could lost all your data.

**Comment by yhoungdev** [comment]
Wow awesome

**Comment by rebron** [comment]
Closing. Thanks @simonhong. Sounds like you got everything answered @yhoungdev

**Comment by yhoungdev** [comment]
Yea sure
