### ISSUE TITLE
Console error on empty page

### ISSUE THREAD

**Issue by friou** [brave/brave-browser#3439]
## Description 
If I want to get opened console before I load my web page, I get an error, not reproduced into browsers like Chrome or Mozilla.

## Steps to Reproduce

   1. Open new console.
   2. Press F12 to show console.
   3. An error appear into the console.

## Actual result:
Error :
![image](https://user-images.githubusercontent.com/41961051/53182152-355e1d80-35f9-11e9-9956-79fd63981c44.png)

## Expected result:
Empty Console : 
![image](https://user-images.githubusercontent.com/41961051/53182117-28d9c500-35f9-11e9-963c-bff1b49feafb.png)

## Reproduces how often:
Always reproduce.

## Brave version (brave://version info)
Version : 71.0.3578.98

### Reproducible on current release:
Last release build.

### Website problems only: 
Not concerned.

### Additional Information
None.

**Comment by rebron** [comment]
Wontfix.
