### ISSUE TITLE
Try again wallet creation is not working

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#3440]
## Steps to Reproduce

   1.  pull the plug from the internet as soon as you click on join now
   2. plug it again after few minutes
   3. you will get error

## Actual result:

try again doesn't do anything. You get this error in the terminal `> response: {"statusCode":422,"error":"Unprocessable Entity","message":"persona credential exists: db1347beebe1e119fe1442086d044cf"}> headers cache-control: no-cache`

## Expected result:
Try again should clear state and start from scratch

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

[Brave-Browser-Development.zip](https://github.com/brave/brave-browser/files/2890008/Brave-Browser-Development.zip)

**Comment by NejcZdovc** [comment]
+1 from https://github.com/brave/brave-browser/issues/3646

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.62.25 Chromium: 73.0.3683.67 (Official Build) beta (64-bit)
-- | --
Revision | a83fd4f3207ae83412d329a9ca1239dd1e068345-refs/branch-heads/3683@{#760}
OS | Windows 7 Service Pack 1 Build 7601.24312

Used test plan from https://github.com/brave/brave-core/pull/1839
Used profile from https://github.com/brave/brave-browser/files/2890008/Brave-Browser-Development.zip

Brave Panel:
![3440 1](https://user-images.githubusercontent.com/34715963/54246950-35d24000-4537-11e9-8522-0b2e3031f0a8.gif)

`brave://rewards`
![3440 2](https://user-images.githubusercontent.com/34715963/54247049-b7c26900-4537-11e9-864a-ab7fc83d736b.gif)
