### ISSUE TITLE
Add webtorrent p3a metric

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#34401]
Add metric for weekly usage of webtorrent:

Did you view the WebTorrent page at least once this week?
`Brave.WebTorrent.UsageWeekly`

1. Yes

cc @jamesmudgett

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on

```
Brave | 1.62.97 Chromium: 120.0.6099.56 (Official Build) beta (64-bit)
-- | --
Revision | 9561bb49dc23c407275af722586f045356609329
OS | Windows 10 Version 22H2 (Build 19045.3693)

```

**Comment by GeetaSarvadnya** [comment]
@DJAndries When I click on the `torrent link` via https://webtorrent.io/free-torrents, I don't see metrics response value as `1` but if I click on the `magnet link` I am getting the metrics response value as `1` - Is this expected?

**Comment by DJAndries** [comment]
@GeetaSarvadnya 

1. Yes, this is expected as WebTorrent can only be invoked via magnet links
2. It would be a bug if the metric was marked as sent in the local state page on the first week.
