### ISSUE TITLE
[Android] - `Terms of service` and `Privacy policy` text is not shown in Dark theme in both Tablet and Android ARM

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#34417]
## Description 
Found while testing https://github.com/brave/brave-browser/issues/30371
`Terms of service` and `Privacy policy` text is not shown in Dark theme in both Tablet and Android ARM
## Steps to reproduce 

   1. Clean profile 1.61.67
   2. Enable rewards and connect bitFlyer custodian
   3. Change theme to Dark mode via appearance settings in hambuger menu 
   4. Open Alexvincentmusic.com pubs
   5. Open Tipping banner
   

## Actual result 
`Terms of service` and `Privacy policy` text is not shown in Dark theme in both Tablet and Android ARM
![image](https://github.com/brave/brave-browser/assets/38657976/fcfbb01f-8d95-4099-9fb7-f1b8ba8c2358)

## Expected result
`Terms of service` and `Privacy policy` text color needs to be changed in Dark theme

## Issue reproduces how often 

Easy
## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86): All
   - Device type (Phone, Tablet, Phablet): All
   - Android version: 12
   
## Brave version
1.61.67

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/qa-team @deeppandya @Miyayes

**Comment by kjozwiak** [comment]
The above requires `1.61.98` or higher for `1.61.x` verification 👍

**Comment by LaurenWags** [comment]
Confirmed `release-notes/exclude` label with @Miyayes
