### ISSUE TITLE
[Android Tab] - `Set as monthly contribution` tooltip hover text is shown far away from the exclamatory icon

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#34416]
## Description 
Found while testing https://github.com/brave/brave-browser/issues/30371
 `Set as monthly contribution` tooltip hover text is shown far away from the exclamatory icon
## Steps to reproduce 

   1. Clean profile 1.61.67
   2. Enable rewards and connect bitFlyer custodian
   3. Open Alexvincentmusic.com pubs
   4. Open Tipping banner
  

## Actual result 

![image](https://github.com/brave/brave-browser/assets/38657976/14a76832-fb84-4d56-9104-c758412dc137)

## Expected result

`Set as monthly contribution` tooltip hover text should not be shown far away from the exclamatory icon
## Issue reproduces how often 

Easy
## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86): All
   - Device type (Phone, Tablet, Phablet): All
   - Android version: 12
   
## Brave version
1.61.67

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

CC: @brave/qa-team @deeppandya @Miyayes

**Comment by Miyayes** [comment]
Also, check the line-height of the text inside the tooltip. It looks too small/short/low.

**Comment by kjozwiak** [comment]
The above requires `1.61.98` or higher for `1.61.x` verification 👍

**Comment by LaurenWags** [comment]
Confirmed `release-notes/exclude` label with @Miyayes

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `Samsung galaxy Tab A7 version 12` running `Bravemonoarm64.apk_1.61.98`

- Verified the STR from the description and ensured that `Set as monthly contribution` tooltip is shown correctly

**`Dark them`** | **`Light theme`**
------------------|-------------------
![Screenshot_20231206-161930_Brave](https://github.com/brave/brave-browser/assets/38657976/1d0d54a8-63ef-4cbf-8296-e6bbff19ec43) | ![Screenshot_20231206-162102_Brave](https://github.com/brave/brave-browser/assets/38657976/d5760261-e7c4-4067-8198-3923db412165)
