### ISSUE TITLE
[Android Tab] - Contribution banner bio description text and default cover photo is not displayed

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#34418]
## Description 
Found while testing https://github.com/brave/brave-browser/issues/30371
`User support this content creators...` text is not displayed on the tipping banner

```[tasklist]
### Tasks
- [ ] Bio description text
- [ ] Default contribution banner (fallback image)
```

## Steps to reproduce 

   1. Clean profile 1.61.67
   2. Enable rewards and connect bitFlyer custodian
   3. Open Alexvincentmusic.com pubs
   4. Open Tipping banner
  
 
## Actual result 

![image](https://github.com/brave/brave-browser/assets/38657976/017f2507-9034-4402-bfab-9a9bd000685b) 

## Expected result
Android ARM

Example | Example
---- | ---
![Screenshot_20231117_205547](https://github.com/brave/brave-browser/assets/38657976/63397026-1d15-40d5-a7ae-118c2ccbb433) | ![image](https://github.com/brave/brave-browser/assets/38657976/d1c43572-3efe-461b-88db-a9a014f36390)

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version?Yes

## Device details
   - Install type (ARM, x86): All
   - Device type (Phone, Tablet, Phablet): All
   - Android version: 12
   
## Brave version
1.61.67

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards?NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @brave/qa-team @Miyayes @deeppandya

**Comment by GeetaSarvadnya** [comment]
This issue is happening for all the pubs. the tipping banner background image is also missing in Android Tab tipping banner
![Screenshot_20231220-145345_Brave - Beta](https://github.com/brave/brave-browser/assets/38657976/0b3f813c-0d7b-4af6-99dc-77c768d8c484)

**Comment by kjozwiak** [comment]
The above requires `1.61.98` or higher for `1.61.x` verification 👍

**Comment by LaurenWags** [comment]
Confirmed `release-notes/exclude` label with @Miyayes
