### ISSUE TITLE
[Android] Move youtube related options

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#34420]
- [ ] Move `Block YouTube recommended content` to newly created `youtube` category in `Media`
- [ ] Move `Block YouTube distracting elements` to newly created `youtube` category in `Media`

**Comment by hffvld** [comment]
Verified on `Pixel 2 XL`, `Galaxy Tab S8` and `Pixel 7` using version(s):
```
Device/OS: 
- Pixel 2 XL / taimen-user  8.1.0 OPM2.171026.006.H1 release-keys
- Galaxy Tab S8 / gts8wifixx-user 13 TP1A.220624.014 release-keys
- Pixel 7 / panther_beta-user 14 AP11.231020.013.A1 release-keys
Brave build: 1.62.114
Chromium: 120.0.6099.115 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Launch Brave
2. Three-dot menu > Settings
3. Brave Shields & privacy > Verify that there is no `YouTube` section appeared
4. Go back to `Settings` > Media > Verify `YouTube` section with new settings
5. Enable `Block YouTube recommended content` and `Block YouTube distracting elements`
6. Close the settings and go to https://youtube.com > Verify that new settings are applied correctly

**ACTUAL RESULTS:**
- Verified that the whole `YouTube` section is moved from `Brave Shields & privacy` to `Media`
- Verified that `Block YouTube recommended content` and `Block YouTube distracting elements` works as expected
- Verified with `fresh` and `upgraded` profile

---------------------------

*Pixel 2 XL / Android 8*

| `Brave Shields & privacy` | `Media` | `Media` |
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/df22cd95-bbd2-408e-ad4b-b73166f4f464) | ![2](https://github.com/brave/brave-browser/assets/128532965/69a6b3ad-2eaf-4153-909b-62c8c631e0a1) | ![3](https://github.com/brave/brave-browser/assets/128532965/5e27b1ff-2968-42ed-a12a-49f0d7507b87) |
| `Block YouTube recommended content` | `lock YouTube distracting elements` | `lock YouTube recommended content` and `Block YouTube distracting elements` |
| ![1](https://github.com/brave/brave-browser/assets/128532965/40845c74-43e8-4fe1-a219-2b86be035416) | ![2](https://github.com/brave/brave-browser/assets/128532965/11decf84-36cc-46dd-a231-7c8c6fa1ff30) | ![3](https://github.com/brave/brave-browser/assets/128532965/f8327213-d651-4920-a3f7-f188ec118f03) |

*Galaxy Tab S8 / Android 14*

| `Brave Shields & privacy` | `Media` | `Media` |
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/602cdeb1-527d-4874-969d-b00067ca5957) | ![2](https://github.com/brave/brave-browser/assets/128532965/751cf1f0-0d5a-4c67-8071-aab269bb2ec1) | ![3](https://github.com/brave/brave-browser/assets/128532965/51395256-74b7-4e92-82c4-b0dda91e245f) |
| `Block YouTube recommended content` | `lock YouTube distracting elements` | `lock YouTube recommended content` and `Block YouTube distracting elements` |
| ![1](https://github.com/brave/brave-browser/assets/128532965/286889e9-80ec-469a-9acf-a03f0b7f8985) | ![2](https://github.com/brave/brave-browser/assets/128532965/4731eea5-3b28-4ec1-b2c0-c105ee0b5b73) | ![3](https://github.com/brave/brave-browser/assets/128532965/8f986fbc-c231-41bb-a9f6-5ac366bb0c40) |

*Pixel 7 / Android 14*

| `Brave Shields & privacy` | `Media` | `Media` |
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/e474b72f-135b-47fb-9c52-95f2c078add1) | ![2](https://github.com/brave/brave-browser/assets/128532965/d1acedd3-e148-4ec1-8182-f345131bc914) | ![3](https://github.com/brave/brave-browser/assets/128532965/b439e5d3-cc86-4204-8bcc-10bf8ff05f35) |
| `Block YouTube recommended content` | `lock YouTube distracting elements` | `lock YouTube recommended content` and `Block YouTube distracting elements` |
| ![1](https://github.com/brave/brave-browser/assets/128532965/ae9bd925-530c-4dcf-a0c4-b4356ce1dff3) | ![2](https://github.com/brave/brave-browser/assets/128532965/e7e50494-c007-46f2-a7a8-3d5310980bfb) | ![3](https://github.com/brave/brave-browser/assets/128532965/9cf3b21e-9da9-4c5d-ab9f-e45d9256b1b9) |
