### ISSUE TITLE
Youtube page opens in 6 seconds, its extremeley slow

### ISSUE THREAD

**Issue by GitAcc53** [brave/brave-browser#34438]
If I open a youtube video by opening it in a new tab, its extremely slow and it opens in 6 seconds. If I open the youtube video in the same tab, its fast, it opens in less than a second. I tried disabling extensions.

Version is updated : 1.60.118 Chromium: 119.0.6045.163

edit : I also have this very annoying problem too : https://github.com/brave/brave-browser/issues/29432
Youtube just doesn't work properly and its extremely annoying.

**Comment by ryanbr** [comment]
Could you test in a new profile, or test in a clean Brave Beta build?

**Comment by GitAcc53** [comment]
> Could you test in a new profile, or test in a clean Brave Beta build?

Nevermind clearing cookies from google & youtube fixed it. But this problem https://github.com/brave/brave-browser/issues/29432 is not fixed
