### ISSUE TITLE
Limit JS set cookie lifetime to 7 days

### ISSUE THREAD

**Issue by snyderp** [brave/brave-browser#3443]
Safari will start doing this soon, so that gives us some good webcompat cover

https://webkit.org/blog/8613/intelligent-tracking-prevention-2-1/

**Comment by diracdeltas** [comment]
Should we start with 7 days or shorter (like 1 day)?

**Comment by diracdeltas** [comment]
2nd question - should this be tied to a shield state or be on all the time?

**Comment by snyderp** [comment]
For my two cents, i suggest
1) 7 days (so that we can fly under Safari's web compat issues)
2) all the time (otherwise it'd get confusing, do we extend / decrease the life times of existing cookies, etc).  Plus, Safari hides the toggle to the point of it basically not existing, so seems like they don't expect web compat issues with it

**Comment by LaurenWags** [comment]
@fmarier can you provide a test plan for manual QA? if manual QA is not needed, can you please label as `QA/No`?

**Comment by fmarier** [comment]
I would suggest following the test plan on https://github.com/brave/brave-core/pull/1905. Let me know if anything on there is unclear.

**Comment by srirambv** [comment]
Verification passed on 

Brave | 0.64.72 Chromium: 74.0.3729.131 (Official Build) beta(64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Linux

7 Days cookie
![image](https://user-images.githubusercontent.com/17010094/57395965-56192680-7197-11e9-9a99-84b2751f042b.png)
6 Month Cookie
![image](https://user-images.githubusercontent.com/17010094/57396269-0c7d0b80-7198-11e9-97e3-613a2b11649f.png)
Except for https://fmarier.org/document-cookie/set-cookie4.html the other 3 is correctly set to 6 months

**Comment by ketys-from-meiro** [comment]
I can set expiration for half a year with max-age. Is it only a visual bug in cookie expiration column or does it really persist for half a year?

**Comment by fmarier** [comment]
> I can set expiration for half a year with max-age. Is it only a visual bug in cookie expiration column or does it really persist for half a year?

No, that looks like a regression. The "client-side cookies" portion of the test plan on https://github.com/brave/brave-core/pull/1905 now fails.

I filed https://github.com/brave/brave-browser/issues/15048 to track this.

**Comment by d4kir92** [comment]
well this 7 days expire thing destroys the youtube wide (theater mode)

each week i need to manually add a cookie to get it working again 
https://github.com/brave/brave-browser/issues/29591

**Comment by racofer** [comment]
Is there any way to override this behavior and have Brave work like any other browser? This things prevents me from using the browser as it is due to how annoying it gets to have a bunch of sites lose their settings every 7 days.

**Comment by ShivanKaul** [comment]
> well this 7 days expire thing destroys the youtube wide (theater mode)

Theater mode in youtube is set via a session cookie (null expiry), cookie lifetime doesn't apply.

**Comment by ShivanKaul** [comment]
> yes its very bad to click all cookie banners on 100+ sites each week -.- also breaks some sites

Can you mention which cookie banners you're seeing? We should be blocking those anyway @ryanbr

**Comment by d4kir92** [comment]
> > well this 7 days expire thing destroys the youtube wide (theater mode)
> 
> Theater mode in youtube is set via a session cookie (null expiry), cookie lifetime doesn't apply.

if i set theater mode it makes a cookie, when i restart brave its gone, on other browsers like chrome/edge it stays

**Comment by ryanbr** [comment]
Screenshot of cookie message, and inspect item?

**Comment by d4kir92** [comment]
it is maybe fixed, will come back if not

**Comment by AJolly** [comment]
Is this why Brave seems to always log me out of webpages, even if I click "remember me"?

I've seen a number of posts about this issue around the web, but So far no one seems to be mentioning brave changing the cookie lifetime

**Comment by d4kir92** [comment]
yes, but depends if the cookie is set to "auto reset 7 days" when you visit that page, i heard of

**Comment by flaviovs** [comment]
> but depends if the cookie is set to "auto reset 7 days" when you visit that page, i heard of

A page can set a cookie to expire in 30 seconds, 2 hours, days, "never", or "when the browser closes". The developer decides based on what they think is best for the user.

Now, cookies can be set in the HTTP response or by Javascript on the page. If I understand correctly, Brave is capping the expiration sent via Javascript to 7 days, regardless if the developer thought that a longer expiration date is safe and needed.

Many sites use Javascript to set user preferences and other data. This explains why you may need to re-login or reset preferences after a week or so on those sites when using Brave.

Apparently this expiration is to improve reliance against trackers which realized that they could circumvent cookie blockers by sending them via Javascript.

The problem (IMHO) is that, by doing so, Brave is crossing a dangerous line, the one that separates security/privacy from deteriorated user experience, **without giving people a way to opt-out**.

Notice that Brave is not doing anything wrong per se. As far as standards are concerned, a browser is free to expire cookies earlier that the indicated by the page as it sees fit, bearing in mind that this could affect user experiences.

Lastly, there's https://github.com/brave/brave-browser/issues/30634 which is a request to have a flag to turn off this behaviour. The request is over a year old with no response from the developers, so a change doesn't seem to be a high priority.

**Comment by minaby** [comment]
This is so annoying. I have been a Brave user for YEARS and introducing this browsers to my friends, but i think this is the limit and I have to give up.

**Comment by theblang** [comment]
Are there any plans to make this configurable? For those of us who prefer the convenience of auth/settings being remembered over the security benefit?

**Comment by geckon** [comment]
I agree that this gets into way of using web in some cases and it would be great to have a way to opt out. I'd be totally fine to be able to opt out on a per-site basis.

Example of where it is annoying is Dokuwiki which apparently sets `DOKU_PREFS` cookie via JS. That means that each week I need to reset my user preferences there. Using the site on multiple devices actually means I need to do it multiple times per week.

**Comment by fmarier** [comment]
https://github.com/brave/brave-browser/issues/30634 has been filed to make this configurable.
