### ISSUE TITLE
[Android] New feature - VPN pause timer

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#34445]
This issue is to add new feature to add a timer to pause VPN tunnel. 
Tasks are defined as below, 

- [x] Add light/dark mode UI for pause timer bottom sheet
- [x] Implement functionality to turn on vpn tunnel after selected time. 

**Figma spec : ** https://www.figma.com/file/PqLTp3DnANLQMM1XzaChqZ/Mobile-VPN?type=design&node-id=3757-42468&mode=design&t=43RhOmL3yxlcT8L9-0

**Test Plan : **

1. Install fresh application
2. Purchase VPN subscription
3. Turn on VPN connection
4. Try to tun off VPN tunnel via `Brave main menu` or `From Brave Firewall + VPN` menu in settings
5. Select Pause for `Desired time`
6. Make sure, VPN tunnel should be turned on after selected time.

**Note : ** Above steps should also work if DND option is enabled on the device.

**Comment by Uni-verse** [comment]
In Progress on `Samsung Galaxy S21` using version:

```
Brave	1.62.130 Chromium: 120.0.6099.199 (Official Build) beta (64-bit) 
Revision	6d589c6dc0f3489830d40332c82cdd5597e41c88
OS	Android 13; Build/TP1A.220624.014; 33; REL
```

- Ensured Pause Menu is displayed when tapping on `Brave VPN` from main menu or `Brave Firewall + VPN` in the settings menu
- Ensured VPN is paused on fresh profile as well as upgraded profile.
- Ensured VPN notification download-upload status is paused. 
- Ensured tunneling is re-enabled after pausing for the selected time.
- Ensured VPN message is removed after disabling VPN. 
- Ensured VPN can be disconnected using the VPN notification "disconnect" button.
- Ensured tapping "Cancel" will close the VPN menu.

Example | Example | Example
-|-|-
![Screenshot 2024-01-09 at 11 49 51 AM](https://github.com/brave/brave-browser/assets/17885425/a27bd6fe-590c-4108-85de-4a2ef7d57b8d) | ![Screenshot 2024-01-09 at 11 50 12 AM](https://github.com/brave/brave-browser/assets/17885425/6eb77d16-68dc-4c58-861a-690ee87e949f) | ![Screenshot 2024-01-09 at 5 51 36 PM](https://github.com/brave/brave-browser/assets/17885425/1a9c031d-16fa-4d0e-80c5-f597fc62ea66)
