### ISSUE TITLE
Crash when importing selected image

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#34443]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.61.77 Chromium: 119.0.6045.163
Operating System: Windows NT 10.0.22631

URL (if applicable) where crash occurred:

Can you reproduce this crash? Yes

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Install IPFS 0.24.0 via dev-goupdater command line args
2. Open Wikipedia and right click on any image on the home page
3. Right click on image and select Import to IPFS -> Select image
4. Browser crashes

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/6e4d0a00-6629-0b0b-0000-000000000000
Crash ID: crash/6b4d0a00-6629-0b0b-0000-000000000000
Crash ID: crash/694d0a00-6629-0b0b-0000-000000000000
Crash ID: crash/674d0a00-6629-0b0b-0000-000000000000
Crash ID: crash/664d0a00-6629-0b0b-0000-000000000000
Crash ID: crash/624d0a00-6629-0b0b-0000-000000000000
Crash ID: crash/414c0a00-6629-0b0b-0000-000000000000

cc: @vadimstruts

**Comment by kjozwiak** [comment]
The above requires `1.61.93` or higher for `1.61.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.61.93 Chromium: 119.0.6045.199 (Official Build) (64-bit)
-- | --
Revision | f707e858dc981208907fd0be3314d081a5dc86ae
OS | Windows 11 Version 23H2 (Build 22631.2715)

- Verified steps from issue description
- Verified no crash when importing images

https://github.com/brave/brave-browser/assets/17010094/b4f72d23-1189-4568-867d-b0ebd7c8b45f
