### ISSUE TITLE
Convert default search weekly metric to a daily metric

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#34457]
Change `Brave.Search.DefaultEngine.4` cadence from weekly to daily.

**Comment by kjozwiak** [comment]
The above requires `1.61.92` or higher for `1.61.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **INPROGRESS** on `Vivo X70 Pro version 12` running `Bravemonoarm64.apk_1.61.93`

- Verified the test plan from https://github.com/brave/brave-core/pull/21061#issue-2003122416

<details>
<summary>Brave.Search.DefaultEngine.4 = 8_PASSED</summary>

1. Clean profile `1.61.93`
2. Open brave://settings/search
3. Ensured that the default SE is `Brave` for the "India" region
4. Open brave://local-state file
5. Look for the metrics `Brave.Search.DefaultEngine.4` 
6. Confirm that the metrics is listed under `logs_express` 
7. Confirm that the metrics response value is `8` as expected [**Note**: The corresponding response value for the Brave SE is `8` in the P3A wiki https://github.com/brave/brave-browser/wiki/P3A]

step 3 | step 7
--------|--------
![image](https://github.com/brave/brave-browser/assets/38657976/65466978-aee1-4519-a6ef-d7df852524ef) | ![image](https://github.com/brave/brave-browser/assets/38657976/86725c70-f4ff-44b7-a849-7ea6bb0eabbf)

</details>

<details>
<summary>Brave.Search.DefaultEngine.4 = 1_PASSED</summary>

1. Clean profile `1.61.93`
2. Open brave://settings/search
3. Ensured that the default SE is `Brave` for the "India" region
4. Change the default SE to `Google`
5. Open brave://local-state file
6. Look for the metrics `Brave.Search.DefaultEngine.4` 
7. Confirm that the metrics is listed under `logs_express` 
8. Confirm that the metrics response value is `1` as expected [**Note**: The corresponding response value for the Google SE is `1` in the P3A wiki https://github.com/brave/brave-browser/wiki/P3A]

step 4 | step 8
--------|--------
![image](https://github.com/brave/brave-browser/assets/38657976/3e94c2cc-e268-43c9-a1ce-f52aa4bee33c) | ![image](https://github.com/brave/brave-browser/assets/38657976/a1ae7616-52f7-49ad-a396-5786525c328a)

</details>

<details>
<summary>Brave.Search.DefaultEngine.4 = 2_PASSED</summary>

1. Clean profile `1.61.93`
2. Open brave://settings/search
3. Ensured that the default SE is `Brave` for the "India" region
4. Change the default SE to `DDG`
5. Open brave://local-state file
6. Look for the metrics `Brave.Search.DefaultEngine.4` 
7. Confirm that the metrics is listed under `logs_express` 
8. Confirm that the metrics response value is `2` as expected [**Note**: The corresponding response value for the DDG SE is `2` in the P3A wiki https://github.com/brave/brave-browser/wiki/P3A]

step 4 | step 8
--------|--------
![image](https://github.com/brave/brave-browser/assets/38657976/d9b65383-db12-41b6-b3d8-4227c204ddcc) | ![image](https://github.com/brave/brave-browser/assets/38657976/31d6ad76-d6b8-44aa-827e-8240f8d227d4)

</details>

<details>
<summary>Brave.Search.DefaultEngine.4 = 5_PASSED</summary>

1. Clean profile `1.61.93`
2. Open brave://settings/search
3. Ensured that the default SE is `Brave` for the "India" region
4. Change the default SE to `Qwant`
5. Open brave://local-state file
6. Look for the metrics `Brave.Search.DefaultEngine.4` 
7. Confirm that the metrics is listed under `logs_express` 
8. Confirm that the metrics response value is `5` as expected [**Note**: The corresponding response value for the Qwant SE is `5` in the P3A wiki https://github.com/brave/brave-browser/wiki/P3A]

step 4 | step 8
--------|--------
![image](https://github.com/brave/brave-browser/assets/38657976/94bacf1f-a957-4b44-8432-5aaa9dc5b12f) | ![image](https://github.com/brave/brave-browser/assets/38657976/c4bf001e-cbde-4ab9-8e03-8e4b38645a8d)

</details>

<details>
<summary>Brave.Search.DefaultEngine.4 = 4_PASSED</summary>

1. Clean profile `1.61.93`
2. Open brave://settings/search
3. Ensured that the default SE is `Brave` for the "India" region
4. Change the default SE to `Bing`
5. Open brave://local-state file
6. Look for the metrics `Brave.Search.DefaultEngine.4` 
7. Confirm that the metrics is listed under `logs_express` 
8. Confirm that the metrics response value is `4` as expected [**Note**: The corresponding response value for the Bing SE is `4` in the P3A wiki https://github.com/brave/brave-browser/wiki/P3A]

step 4 | step 8
--------|--------
![image](https://github.com/brave/brave-browser/assets/38657976/5202cfbb-bad0-4235-8c74-49abff4b46b0) | ![image](https://github.com/brave/brave-browser/assets/38657976/2fcadf2b-3c27-4575-bf89-4ca040efa189)


</details>

<details>
<summary>Brave.Search.DefaultEngine.4 = 3_PASSED</summary>

1. Clean profile `1.61.93`
2. Open brave://settings/search
3. Ensured that the default SE is `Brave` for the "India" region
4. Change the default SE to `Startpage`
5. Open brave://local-state file
6. Look for the metrics `Brave.Search.DefaultEngine.4` 
7. Confirm that the metrics is listed under `logs_express` 
8. Confirm that the metrics response value is `3` as expected [**Note**: The corresponding response value for the Startpage SE is `3` in the P3A wiki https://github.com/brave/brave-browser/wiki/P3A]

step 4 | step 8
--------|--------
![image](https://github.com/brave/brave-browser/assets/38657976/b7cfa151-2044-401c-b6f1-dd224579a484) | ![image](https://github.com/brave/brave-browser/assets/38657976/07443cbd-0b5f-4c4b-b326-baa96d0b829b)


</details>
