### ISSUE TITLE
Add country code field to NTP-SI P3A metrics

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#34456]
Add `country_code` field to NTP metrics. Infer the country via user locale.

cc @iambrianfung

**Comment by pes10k** [comment]
Just to confirm, this is only for the STAR-encoded submissions right?  Non-STAR-encoded submissions will continue to NOT have country code?

**Comment by DJAndries** [comment]
> Just to confirm, this is only for the STAR-encoded submissions right? Non-STAR-encoded submissions will continue to NOT have country code?

correct
