### ISSUE TITLE
Perf: use less hooks in wallet page container

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#34455]
## Description 

Currently, the main wallet page container component still controls state of children components. Move the state down to the appropriate components to reduce the amount of logic performed at the App root

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.62.123 Chromium: 120.0.6099.144 (Official Build) beta (64-bit)
-- | --
Revision | 680382264ff6ae655b3bba25e80567452f38fbee
OS | Windows 11 Version 23H2 (Build 22631.2861)

- Verified steps from [brave/brave-core#21059](https://github.com/brave/brave-core/pull/21059)
- Verified lock/unlock wallet works as expected on both wallet page and panel
- Verified wallet backup banner works as expected on both wallet page and panel
- Verified Set default wallet banner works as expected on both wallet page and panel
- Verified Open settings button in wallet banner works as expected on both wallet page and panel

https://github.com/brave/brave-browser/assets/17010094/c42f99fa-eab3-4fae-b9de-21bc99b9b87d
