### ISSUE TITLE
bitcoin UTXO details should display the full address

### ISSUE THREAD

**Issue by kdenhartog** [brave/brave-browser#34465]
When displaying the additional details we just need to make sure the addresses are fully displayed. This can either be done by wrapping the text or making it scrollable. Wrapping seems like the better UX here.

![left scrollable or text wrap](https://github.com/brave/reviews/assets/23125059/c513ff34-2754-4b38-ad94-053b6df7586f)

**Comment by kdenhartog** [comment]
cc @supermassive

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.63.141 Chromium: 121.0.6167.139 (Official Build) beta (64-bit)
-- | --
Revision | aa92f6cecec7f6c576bd1cf120f4cf359d770159
OS | Windows 11 Version 23H2 (Build 22631.3007)

- Verified steps from [brave/brave-core#21266](https://github.com/brave/brave-core/pull/21266)
- Verified full address is shown in transaction details screen

https://github.com/brave/brave-browser/assets/17010094/7a644f73-34c7-4b0d-bb69-1add068b3aae
