### ISSUE TITLE
max transfer isn't behaving as expected

### ISSUE THREAD

**Issue by kdenhartog** [brave/brave-browser#34467]
https://github.com/brave/reviews/assets/23125059/30dc82cd-bf1d-49c9-8394-c5e63341db92

cc @supermassive

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.63.141 Chromium: 121.0.6167.139 (Official Build) beta (64-bit)
-- | --
Revision | aa92f6cecec7f6c576bd1cf120f4cf359d770159
OS | Windows 11 Version 23H2 (Build 22631.3007)

- Verified steps from [brave/brave-core#21266](https://github.com/brave/brave-core/pull/21266)
- Verified max value is selected and transaction is submitted 

https://github.com/brave/brave-browser/assets/17010094/43641db5-3bf5-44a2-9d56-6c6cf8b20c24
