### ISSUE TITLE
Too many decimals issue whe using "half" send button

### ISSUE THREAD

**Issue by kdenhartog** [brave/brave-browser#34468]
When hitting half amount it sometimes can display too many decimals error. This should instead just round up or down for a slightly improved UX.
![half transfer too many decimals](https://github.com/brave/reviews/assets/23125059/e6345397-7408-49e0-9e64-971e90a35034)

cc @supermassive

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.63.141 Chromium: 121.0.6167.139 (Official Build) beta (64-bit)
-- | --
Revision | aa92f6cecec7f6c576bd1cf120f4cf359d770159
OS | Windows 11 Version 23H2 (Build 22631.3007)

- Verified steps from [brave/brave-core#21266](https://github.com/brave/brave-core/pull/21266)
- Verified when using preset value of half, correct decimal values is shown

https://github.com/brave/brave-browser/assets/17010094/c15aad6d-7fe8-4152-a534-a07012c86b71
