### ISSUE TITLE
SIWE integration broken with Gitcoin Passport

### ISSUE THREAD

**Issue by kdenhartog** [brave/brave-browser#34470]
https://passport.gitcoin.co/#/ is hitting the failure case around domains not matching and dropping the flow. It's likely an integration issue

cc @onyb in case you get some time to look at it. It seems they're doing something with did:key which is causing the breakage, but I've not figured out what the site itself is sending as a request yet.

![Screenshot 2023-11-22 at 10 17 52 AM](https://github.com/brave/brave-browser/assets/23125059/5a846f2a-00d7-42cc-a636-5ed202c2e83b)

It appears the message format is the following:

```
passport.gitcoin.co wants you to sign in with your Ethereum account: 0x5bd8c4ec48cf3efdd791b5bab2d4869342605f98 
Give this application access to some of your data on Ceramic 
URI: did:key:z6MkkNKzqgC6UAjZ5QhN8naRSbKynUE2zcrKcrwsbBToyiR2
Version: 1
Nonce: uoW6QUReSm
Issued At: 2022-06-08T14:46:25.908Z
Expiration Time: 2022-06-09T14:46:25.908Z
Chain ID: 1
Resources: - ceramic://*
```

It appears the issue is the parsing logic of the URI doesn't match the domain listed in the beginning of the message.

**Comment by oed** [comment]
For context, the [SIWE spec](https://eips.ethereum.org/EIPS/eip-4361#verifying-the-request-origin) clearly says that the `domain` field should be used for origin verification, not `uri`.

**Comment by kjozwiak** [comment]
The above requires `1.68.92` or higher for `1.68.x` verification 👍
