### ISSUE TITLE
Center Wallet Navigation and Body Together

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#34471]
## Description 

We need to `center` the Wallet `Navigation` and `Body` together to match the new designs.

![Screenshot 19](https://github.com/brave/brave-browser/assets/40611140/1aa81fba-70fa-4bd1-be1a-7ff67882833d)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.64.90 Chromium: 122.0.6261.94 (Official Build) beta (64-bit)
-- | --
Revision | 726c6970a1e9c057c69d80e03ad95a7c561fbfe7
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from [brave/brave-core#21719](https://github.com/brave/brave-core/pull/21719)
- Verified wallet navigation and card body are both centre aligned 
- Verified reducing the browser size continues to centre wallet navigation and card body 

https://github.com/brave/brave-browser/assets/17010094/56889c0f-66a9-49c8-af4e-2cfbd45cb015
