### ISSUE TITLE
Upgrade from 72.0.3626.109 to 72.0.3626.119 on 0.60.x branch

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#3447]
QA tests:

* Check branding items
* Check for version bump

**Comment by kjozwiak** [comment]
PR https://github.com/brave/brave-core/pull/1757.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.60.47 Chromium: 72.0.3626.119 (Official Build) (64-bit)
-- | --
Revision | 9a65993e2cde1b5797ec98da4cd9abcea464cd7b-refs/branch-heads/3626@{#876}
OS | Mac OS X
