### ISSUE TITLE
Update Blockies

### ISSUE THREAD

**Issue by simoarpe** [brave/brave-browser#34482]
## Details

Update Blockie’s to the new styling: https://github.com/brave/blockies/pull/2

Slack discussion: [bravesoftware.slack.com/archives/C023VS4HJ6Q/p1699450616856909](https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1699450616856909)

iOS GitHub issue: https://github.com/brave/brave-ios/issues/8375

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.62.107 x64 Beta build
- Verified Account blockies are updated similar to desktop
- Verified each account blockie is different
- Encountered [#34965](https://github.com/brave/brave-browser/issues/34965)

Google Pixel 8 (Android 14) | Lenovo Tab (Android 13)
-- | --
<video src=https://github.com/brave/brave-browser/assets/17010094/4542f87a-5de7-41ba-af65-368cdeeb94f8> | <video src=https://github.com/brave/brave-browser/assets/17010094/0899c088-4de7-47ad-9bdd-a43fbe979f4f>
