### ISSUE TITLE
Add network selection step to wallet onboarding

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#34493]
## Description 

Spec: https://docs.google.com/document/d/1hAXcfs_6PadkoP69IbZsI3aMqH5YkhR9A95H1hyZ2rI

**Comment by srirambv** [comment]
Verification passed on <html>
<body>

Brave | 1.63.141 Chromium: 121.0.6167.139 (Official Build) beta (64-bit)
-- | --
Revision | aa92f6cecec7f6c576bd1cf120f4cf359d770159
OS | Windows 11 Version 23H2 (Build 22631.3007)

- Verified steps from [brave/brave-core#21088](https://github.com/brave/brave-core/pull/21088)
- Verified network selection is part of onboarding
- Verified only selected networks are added upon onboarding rest remains disabled
- Verified wallet restore/wallet backup screen works as expected without any regressions

https://github.com/brave/brave-browser/assets/17010094/97bbef1f-1fe9-4f87-b03c-9b4ff1ad8e75
