### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by LeOS-GSI** [brave/brave-browser#34494]
## Description 

Sorry, your build description is chaotic. I'm trying to build Brave for Android and following [these instructions](https://github.com/brave/brave-browser/wiki/Linux-Development-Environment). But the command `npm run init` is failing. Error message and logs attached. 

## Steps to Reproduce

   1. try your build script from clean system

## Actual result:

See attached logs

## Reproduces how often: 

working instructions

## Desktop Brave version:

nope

## Android Device details:
   - Install type (ARM, x86): --
   - Device type (Phone, Tablet, Phablet): --
   - Android version:---

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? -----
- Does the issue resolve itself when disabling Brave Rewards? -----
- Is the issue reproducible on the latest version of Chrome? ------

## Miscellaneous Information:
 none
[init_error.txt](https://github.com/brave/brave-browser/files/13443084/init_error.txt)

**Comment by LeOS-GSI** [comment]
logs
[2023-11-22T18_00_38_169Z-debug-0.log](https://github.com/brave/brave-browser/files/13443099/2023-11-22T18_00_38_169Z-debug-0.log)
[2023-11-22T18_00_27_708Z-debug-0.log](https://github.com/brave/brave-browser/files/13443104/2023-11-22T18_00_27_708Z-debug-0.log)

**Comment by bsclifton** [comment]
@LeOS-GSI looks like you're using Node.js version 12.22.9 - can you please try to install the latest Node.js LTS release?

I'll close this issue as there's nothing wrong with the code or product - but please continue replying here and I can help

**Comment by LeOS-GSI** [comment]
I don't have a .env file in my tree. So where to add this infos:

    brave_android_developer_options_code
    brave_android_key_password
    brave_android_keystore_name
    brave_android_keystore_password
    brave_android_keystore_path
    brave_safebrowsing_api_key
    brave_safetynet_api_key (not set in PRs)


and where can I get the values ?

**Comment by bsclifton** [comment]
@LeOS-GSI for those, you're going to have to provide your own values. Unfortunately, we don't share out build parameters. Anything built with those is a genuine version of Brave and that's controlled.

You should be able to setup your own Android app in Google Play Console and then use those values though. The Safe Browsing API is basically a Google API key. You can go to https://console.cloud.google.com/apis and create an app there and you'll get an API key also.

**Comment by LeOS-GSI** [comment]
I don't want ans Google shit. I'm a foss guy. Only open source and never ans Google stuff.

But I still need the info, where  these .env file should be located. It's not in your source tree and not in the synced.

**Comment by bsclifton** [comment]
Unfortunately, you have to provide something for them. We can't share our information as those details themselves are not source code, they're assets specifically used to build the official version of Brave. Just like signing keys, we can't share those. Sorry

**Comment by LeOS-GSI** [comment]
But how can I get a smaller apk ? 750 mb is really to heavy

**Comment by LeOS-GSI** [comment]
could you please tell me how to reduce the apk file size ? the debug version ist still to big with 360 mb.

thanks

**Comment by LeOS-GSI** [comment]
by the way, this link is dead https://github.com/brave/devops/wiki/npm-config-for-Brave-Developers

**Comment by bsclifton** [comment]
@LeOS-GSI that link is for employees only - that has the real values we use and is not intended to be public.

**Comment by SergeyZhukovsky** [comment]
@LeOS-GSI debug versions are always bigger compared to release binaries. arm64 apk contains both 32 bit and 64 bit. You can build `arm` it's about 2x smaller. `BraveMonoarm.apk` is 162Mb https://github.com/brave/brave-browser/releases/tag/v1.62.80

**Comment by deeppandya** [comment]
@LeOS-GSI generating .aab bundles would be even smaller in size if size is the concern.

**Comment by deeppandya** [comment]
> I don't have a .env file in my tree. So where to add this infos:
> 
>     brave_android_developer_options_code
>     brave_android_key_password
>     brave_android_keystore_name
>     brave_android_keystore_password
>     brave_android_keystore_path
>     brave_safebrowsing_api_key
>     brave_safetynet_api_key (not set in PRs)
> 
> 
> and where can I get the values ?

The above `keystore` keys are mainly to sign the release app. And you don't need it for debug builds.
