### ISSUE TITLE
[Brave News]: In-memory feed storage

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#34498]
- Navigating between feed filters within a session should keep exactly the same feed content (i.e. not regenerate)
- Opening a new session should keep the most-recently selected feed selected and keep the exactly the same feed content
- We should continue to support back-navigation keeping exactly the same feed content and selected feed.

**Comment by fallaciousreasoning** [comment]
Partially fixed by https://github.com/brave/brave-core/pull/21097
The rest should be covered by https://github.com/brave/brave-core/pull/21143
