### ISSUE TITLE
Icon for tab search should be down arrow in the menu bar

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#34503]
## Description 

The icon for tab search in the menu bar should use the down arrow. This appears to be an issue only on macOS and Linux.

See Expected result.

This is also only for horizontal tab view. In vertical tab view, the magnifying glass icon should be used.

## Steps to Reproduce

   1. Use 1.61.x in Beta
   2. Notice the tab search icon is a magnifying glass in the menu bar for macOS and Linux.
 

## Actual result:

<img width="494" alt="Screenshot 2023-11-22 at 3 12 04 PM" src="https://github.com/brave/brave-browser/assets/5951041/aaa026af-b92b-4234-a1b1-5ed4ffc71189">

## Expected result:

<img width="230" alt="Screenshot 2023-11-22 at 3 12 34 PM" src="https://github.com/brave/brave-browser/assets/5951041/d466cf62-395e-4ed8-8564-6517d6583f68">

## Reproduces how often: 

Easily

## Brave version (brave://version info)

In 1.61.x Beta and 1.62.x Nightly. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.62.76 Chromium: 119.0.6045.163 (Official Build) nightly (x86_64)
-- | --
Revision | 8b454b7ea4b543d9f66aeb6c18940a351f0c4d10
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.62.76`
2. launched Brave
3. opened a new-tab page
4. context-clicked on the tab
5. chose `Use Vertical Tabs`
6. looked at the tab-search icon

## Confirmed the tab-search icon is now a magnifying-glass icon

`1.61.85` | `1.62.76`
----------|---------
<img width="294" alt="Screen Shot 2023-11-23 at 1 24 47 PM" src="https://github.com/brave/brave-browser/assets/387249/b2fce8f7-50a4-46b6-8170-a6928f9a50db"> | <img width="216" alt="Screen Shot 2023-11-23 at 1 25 06 PM" src="https://github.com/brave/brave-browser/assets/387249/725ee60d-cb41-4454-91f8-142045844356">

**Comment by MadhaviSeelam** [comment]
Added OS/Linux  and OS/macOS as per the description https://github.com/brave/brave-browser/issues/34503#issue-2007323489

**Comment by btlechowski** [comment]
Verified with

Brave | 1.62.122 Chromium: 120.0.6099.144 (Official Build) beta (64-bit)
-- | --
Revision | cfddebe77d394064c472fda64afcd9fbed34ceb4
OS | Linux



Verified down arrow is shown in the menu bar for Horizontal tabs

![image](https://github.com/brave/brave-browser/assets/34715963/60222e68-e429-4c24-86ed-db392a309f6e)

Verified Magnifying glass is shown in the menu bar for Horizontal tabs

![image](https://github.com/brave/brave-browser/assets/34715963/3f2ddecb-2fb5-40db-8349-63b247e313a6)
