### ISSUE TITLE
follow-up to #33048, Update text string to both Shields and Settings for Forgetful browsing

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#34504]
## Description 

With the change to #33048, there was a text string change to Shields. Shields should still show the same `Forget me when I close this site` text.

## Steps to Reproduce

   1. Use 1.62.73 or higher. Notice that Shields text matches actual result. 
   2. Text should be what was in 1.60.x/1.61.x `Forget me when I close this site`
   3. Update brave://settings/shields text to add `, by default` as per description https://github.com/brave/brave-browser/issues/33048#issue-1899194449

## Actual result:

<img width="367" alt="Screenshot 2023-11-22 at 3 14 01 PM" src="https://github.com/brave/brave-browser/assets/5951041/5df3d0dc-81cc-4fe1-bfcd-09fe7dceda92">

## Expected result:
<img width="347" alt="Screenshot 2023-11-22 at 3 13 50 PM" src="https://github.com/brave/brave-browser/assets/5951041/1100aaa8-e9c4-4d37-83fc-774a651220b8">

## Reproduces how often: 

Easily.

## Brave version (brave://version info)

1.62.x

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? n/a
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a
- Does the issue resolve itself when disabling Brave Rewards? n/a 
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by stephendonner** [comment]
@rebron @simonhong there's no commit for this:

> Update brave://settings/shields text to add , by default as per description https://github.com/brave/brave-browser/issues/33048#issue-1899194449

Is that out-of-scope for this verification, and will be handled in a follow-up issue?

**Comment by simonhong** [comment]
> @rebron @simonhong there's no commit for this:
> 
> > Update brave://settings/shields text to add , by default as per description [#33048 (comment)](https://github.com/brave/brave-browser/issues/33048#issue-1899194449)
> 
> Is that out-of-scope for this verification, and will be handled in a follow-up issue?

Yes, currently it's just reverted. I think this don't need QA as it's same as before.
Let's trackt it with https://github.com/brave/brave-browser/issues/33048

**Comment by stephendonner** [comment]
## Verified `IN-PROGRESS` using

```
Brave | 1.62.87 Chromium: 120.0.6099.35 (Official Build) nightly (x86_64)
-- | --
Revision | e0cd7777fe0c2b5f4fe9e1bc27cedd1f87eac37f
OS | macOS Version 11.7.10 (Build 20G1427)
```
