### ISSUE TITLE
Crash when importing selected image

### ISSUE THREAD

**Issue by vadimstruts** [brave/brave-browser#34501]
## Description 

I tried with a build that has the fix and still able to crash. seems to fail everytime when it fails to import the first time

Crash IDs:
3c730f00-6629-0b0b-0000-000000000000
d0710f00-6629-0b0b-0000-000000000000
9a710f00-6629-0b0b-0000-000000000000

## Steps to Reproduce

   1. Install IPFS 0.24.0 via dev-goupdater command line args
   2. Open Wikipedia and right click on any image on the home page
   3. Right click on image and select Import to IPFS -> Select image
   4. Browser crashes

**Comment by kjozwiak** [comment]
The above requires `1.61.94` or higher for `1.61.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.61.94 Chromium: 120.0.6099.56 (Official Build) (64-bit)
-- | --
Revision | 72759647494f071d653f8a61465fadf5f361b06e
OS | Windows 11 Version 23H2 (Build 22631.2715)

- Verified steps from issue description
- Verified no crash when importing images

https://github.com/brave/brave-browser/assets/17010094/82972c14-1e23-4201-8a4b-c6acb76a185c
