### ISSUE TITLE
`Leo` and `Playlist` icons should be hidden, not just disabled in Private, Private with Tor, and Guest profile windows

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#34518]
## Description 

`Leo` and `Playlist` icons should be hidden, not just disabled in Private, Private with Tor, and Guest profile windows

## Steps to Reproduce

   1. install `1.62.76`
   2. launch Brave
   3. open a `New Private Window`
   4. open a `New Private Window with Tor`
   5. open a `Guest profile` window
   6. look at the `Leo` and `Playlist` (when enabled) icons

## Actual result:

`Leo` and `Playlist` icons are disabled

`Private Window with Tor` | `Private Window` | `Guest profile`
------------------|----------------------------|---------------
 <img width="1556" alt="Screenshot 2023-11-23 at 10 56 23 AM" src="https://github.com/brave/brave-browser/assets/387249/108af3dd-621c-4d23-9251-fd9e644b9c3a"> | <img width="1550" alt="Screenshot 2023-11-23 at 10 57 09 AM" src="https://github.com/brave/brave-browser/assets/387249/8dfd839a-834e-45ec-9fe7-4f0989f95d32"> | <img width="1551" alt="Screenshot 2023-11-23 at 10 56 43 AM" src="https://github.com/brave/brave-browser/assets/387249/ed9210dd-5d4b-4d49-ba85-5b5cc842c76f">

## Expected result:

The disabled `Leo` and `Playlist` icons should be hidden/removed while unavailable in these window types

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave | 1.62.76 Chromium: 119.0.6045.163 (Official Build) nightly (x86_64)
-- | --
Revision | 8b454b7ea4b543d9f66aeb6c18940a351f0c4d10
OS | macOS Version 14.2 (Build 23C5047e)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? `Yes`
- Can you reproduce this issue with the beta channel? `Yes`
- Can you reproduce this issue with the nightly channel? `Yes`

/cc @simonhong @rebron @brave/qa-team

**Comment by LaurenWags** [comment]
Removed `QA Pass-macOS` label as this was tested on 1.63.x but should be tested on 1.62.x per the milestone on the issue.

**Comment by stephendonner** [comment]
> Removed `QA Pass-macOS` label as this was tested on 1.63.x but should be tested on 1.62.x per the milestone on the issue.

Thanks, yes - redressing and retesting this on `1.62.x` now (train migrations!)
