### ISSUE TITLE
On-demand updates sometimes fail in per-user installations of Arm64 Brave on Windows

### ISSUE THREAD

**Issue by mherrmann** [brave/brave-browser#34523]
## Description 

`brave://settings/help` sometimes shows error `Update check failed to start (error code 3: 0x800700C1)`. This happens almost always when we update the Windows updater (Omaha). But also sometimes (rarely) after initial install of Brave.

## Steps to Reproduce

   1. Run Brave's installer.
   2. Reject the UAC prompt.
   3. In the following dialog, select "Yes, install without admin privileges" to install only for the current user.
   4. Open `brave://settings/help`.

## Actual result:

You get an error `Update check failed to start (error code 3: 0x800700C1)`.

## Expected result:

An update check should take place and no error should be shown.

## Reproduces how often: 

Rarely for initial installations of Brave, almost always after an update of current versions of the updater.

## Brave version (brave://version info)

1.61.x.

## Version/Channel Information:

The main affected version is 1.61.x (currently Beta), because it adds full Arm64 support for Windows.

- Can you reproduce this issue with the current release? 

No, because current Release doesn't support on-demand updates in Arm64 Brave.

- Can you reproduce this issue with the beta channel? 

Yes.

- Can you reproduce this issue with the nightly channel?

Probably.

**Comment by LaurenWags** [comment]
@mherrmann  @rebron could one of you please add `release-notes/exclude` or `release-notes/include` label as appropriate for this one? Thanks!

**Comment by mherrmann** [comment]
@LaurenWags done!

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.62.97 Chromium: 120.0.6099.56 (Official Build) beta (arm64)
-- | --
Revision | 9561bb49dc23c407275af722586f045356609329
OS | Windows 11 Version 23H2 (Build 22631.2715)
```
### ***_Machine-wide STR/Cases_*** - `PASSED`

`BraveBrowserStandaloneBetaSetupArm64.exe`

1. uninstalled all of the brave channels (Release, Beta and Nightly) via brave-manager tool
2. downloaded `BraveBrowserBetaSetupArm64.exe` from https://github.com/brave/brave-browser/releases/download/v1.62.92/BraveBrowserStandaloneBetaSetupArm64.exe
3. Installed Brave with Admin rights
4. opened brave://settings/help

#### Confirmed no errors shown and successfully updated to public beta version `1.62.97`

example | example | example 
----- | ------ | ------
![image](https://github.com/brave/brave-browser/assets/98358127/37808bae-8283-4c85-a137-3d88f2b32641)|![image](https://github.com/brave/brave-browser/assets/98358127/58d0f106-8f74-459f-a5df-e8ea1d9a870c)|![image](https://github.com/brave/brave-browser/assets/98358127/76a91da0-98b3-459a-9369-bea43ee0943c)

`BraveBrowserStandaloneSilentBetaSetupArm64`

1. uninstalled all of the brave channels (Release, Beta and Nightly) via brave-manager tool
2. downloaded `BraveBrowserStandaloneSilentBetaSetupArm64.exe` from https://github.com/brave/brave-browser/releases/download/v1.62.92/BraveBrowserStandaloneSilentBetaSetup.exe
3. Installed Brave with Admin rights
4. opened `brave://settings/help`

#### Confirmed no errors shown and successfully updated to public beta version `1.62.97`

example | example | example 
----- | ------ | ------
![image](https://github.com/brave/brave-browser/assets/98358127/b1af3d44-2266-4cbe-9624-dd3dd18d9ee7)
![image](https://github.com/brave/brave-browser/assets/98358127/4e53a8d8-e1d4-4fb9-af26-58a2b6f5f164)






### ***_Per User installation_*** - PASSED

`BraveBrowserStandaloneBetaSetupArm64`

1. uninstalled all of the brave channels (Release, Beta and Nightly) via brave-manager tool
2. downloaded `BraveBrowserBetaSetupArm64.exe` from https://github.com/brave/brave-browser/releases/download/v1.62.92/BraveBrowserStandaloneBetaSetupArm64.exe
3. Installed Brave without Admin rights
4. opened brave://settings/help

### Confirmed no errors shown and successfully updated to public beta version `1.62.97`

example | example | example | example 
----- | ------ | ------ | ------
![image](https://github.com/brave/brave-browser/assets/98358127/94c776a7-0688-4ed7-b234-eae6da074c9e)|![image](https://github.com/brave/brave-browser/assets/98358127/65066fae-736d-4cad-a310-a1e180844921)|![image](https://github.com/brave/brave-browser/assets/98358127/32d81324-3b0a-4bc8-838a-43a95f949725)|![image](https://github.com/brave/brave-browser/assets/98358127/03e38b70-0872-44bb-b8ba-b1937f836761)

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.62.97 Chromium: 120.0.6099.56 (Official Build) beta (64-bit)
-- | --
Revision | 9561bb49dc23c407275af722586f045356609329
OS | Windows 11 Version 22H2 (Build 22621.2715)
```

### Win 11 x64 - PASSED

### ***_Per User installation_*** 

`BraveBrowserStandaloneBetaSetup.exe`

1. uninstalled all of the brave channels (Release, Beta and Nightly) via brave-manager tool
2. downloaded and installed public beta `1.62.92` using standalone installer `BraveBrowserStandaloneBetaSetup.exe` from https://github.com/brave/brave-browser/releases/download/v1.62.92/BraveBrowserStandaloneBetaSetup.exe
3. Installed Brave without Admin rights
4. opened brave://settings/help

#### Confirmed no errors shown and successfully updated to public beta version `1.62.97`

example | example | example 
----- | ------ | ------ | ------
<img width="307" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/dc54fef8-af8d-4264-90ba-e204fc65e376">|<img width="506" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/0dae7c74-8b45-4e9b-8cd0-a485c693a969">|<img width="509" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/187a3c01-9c33-4712-9d59-b7fcd486c1d1">






### ***_Machine-wide STR/Cases_*** - ` `

`BraveBrowserStandaloneBetaSetup.exe`

1. uninstalled all of the brave channels (Release, Beta and Nightly) via brave-manager tool
2. downloaded and installed public beta `1.62.92` using standalone installer`BraveBrowserStandaloneBetaSetup.exe` from https://github.com/brave/brave-browser/releases/download/v1.62.92/BraveBrowserStandaloneBetaSetup.exe
3. Installed Brave with Admin rights
4. opened brave://settings/help

#### Confirmed no errors shown and successfully updated to public beta version `1.62.97`

example | example | example 
----- | ------ | ------
<img width="506" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/782ed2ae-d7da-4cc3-ab22-0e2b8ead38e0">|<img width="511" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/22bc8e87-64a0-4ab4-8ada-39c7f3f6e367">|<img width="511" alt="image" src="https://github.com/brave/brave-browser/assets/98358127/fd489fa9-97e5-478f-8fca-da5f303fecb6">

**Comment by MadhaviSeelam** [comment]
@GeetaSarvadnya @kjozwiak @LaurenWags - Verified the issue on `Win 11 arm64` and `Win 11 x64`, both Machine-wide & Per-user installations. (With all 3 installers - stub, standalone & silent, probably an overkill :)).  But please test the other architectures (Win 10 x64 & Win 10 x86) as per the [testplan](https://github.com/brave/brave-core/pull/21110#issue-2009274433).

**Comment by stephendonner** [comment]
Verification `IN-PROGRESS` using
```
.
```

### Win 11 arm64 - PASSED

### ***_Per User installation_*** - PASSED

`BraveBrowserStandaloneBetaSetupArm64`

1. uninstalled all of the brave channels (Release, Beta and Nightly) via brave-manager tool
2. downloaded and installed public beta `1.62.92` using standalone installer `BraveBrowserStandaloneBetaSetupArm64.exe` from https://github.com/brave/brave-browser/releases/download/v1.62.92/BraveBrowserStandaloneBetaSetupArm64.exe
3. Installed Brave without Admin rights
4. opened brave://settings/help

#### Confirmed no errors shown and successfully updated to public beta version `1.62.97`

example | example | example | example 
----- | ------ | ------ | ------


`BraveBrowserBetaSetupArm64`

1. uninstalled all of the brave channels (Release, Beta and Nightly) via brave-manager tool
2. downloaded and installed public beta 1.62.92 using stub installer `BraveBrowserBetaSetupArm64.exe` from https://github.com/brave/brave-browser/releases/download/v1.62.92/BraveBrowserBetaSetupArm64.exe
3. Installed Brave without Admin rights
4. opened brave://settings/help

#### Confirmed no errors shown and `brave://settings/help` page shown `Brave is up to date` message with public beta version `1.62.97`

example | example | example  
----- | ------ | ------  


### ***_Machine-wide Installation_*** - `PASSED`

`BraveBrowserStandaloneBetaSetupArm64.exe`

1. uninstalled all of the brave channels (Release, Beta and Nightly) via brave-manager tool
2. downloaded and installed public beta `1.62.92` using standalone installer`BraveBrowserStandaloneBetaSetupArm64.exe` from https://github.com/brave/brave-browser/releases/download/v1.62.92/BraveBrowserStandaloneBetaSetupArm64.exe
3. Installed Brave with Admin rights
4. opened brave://settings/help

#### Confirmed no errors shown and successfully updated to public beta version `1.62.97`

example | example | example 
----- | ------ | ------


`BraveBrowserBetaSetupArm64`

1. uninstalled all of the brave channels (Release, Beta and Nightly) via brave-manager tool
2. downloaded and installed public beta `1.62.92` using stub installer `BraveBrowserBetaSetupArm64.exe` from https://github.com/brave/brave-browser/releases/download/v1.62.92/BraveBrowserBetaSetupArm64.exe
3. Installed Brave with Admin rights
4. opened brave://settings/help

#### Confirmed no errors shown and `brave://settings/help` page shown `Brave is up to date` message with public beta version `1.62.97`

example | example  
----- | ------ 


`BraveBrowserStandaloneSilentBetaSetupArm64`

1. uninstalled all of the brave channels (Release, Beta and Nightly) via brave-manager tool
2. downloaded and installed public `1.62.92` using silent installer `BraveBrowserStandaloneSilentBetaSetupArm64.exe` from https://github.com/brave/brave-browser/releases/download/v1.62.92/BraveBrowserStandaloneSilentBetaSetupArm64.exe
3. Silent Installed Brave 
4. opened `brave://settings/help`

#### Confirmed no errors shown and successfully updated to public beta version `1.62.97`

example | example | example 
----- | ------ | ------

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.62.116 Chromium: 120.0.6099.144 (Official Build) beta (32-bit) 
Revision	632ccd5061221cfe5e1b9f3d14345cfd62db9655
OS	Windows 10 Version 22H2 (Build 19045.3803)
```
