### ISSUE TITLE
Follow up of #34249 - Update sidebar button's left & right margin

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#34522]
## Description 

Follow up of #34249 - Update sidebar button's left & right margin
## Steps to Reproduce

   1. Follow the description from https://github.com/brave/brave-browser/issues/34249#issue-1986965458
   2. examined the icon's border padding on both sides
   3. icon's border is still uneven
  

## Actual result:

![image](https://github.com/brave/brave-browser/assets/38657976/9f7ad6f1-c2e9-4169-a897-380ddf1e2563)

## Expected result:

icon's border should be even for both the sides
## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.61.85 Chromium: 119.0.6045.163 (Official Build) beta (64-bit)
-- | --
Revision | 5e2736df90772dd1b66ca5013e47c1fc467c9762
OS | Windows 10 Version 22H2 (Build 19045.3693)

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @simonhong @brave/qa-team @rebron

**Comment by stephendonner** [comment]
I can confirm too, using 

```
Brave | 1.61.85 Chromium: 119.0.6045.163 (Official Build) beta (x86_64)
-- | --
Revision | 5e2736df90772dd1b66ca5013e47c1fc467c9762
OS | macOS Version 14.2 (Build 23C5047e)
```

<img width="126" alt="Screenshot 2023-11-26 at 10 16 46 AM" src="https://github.com/brave/brave-browser/assets/387249/fa8074be-704f-4322-8d0f-3e6220ec43df">

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.61.86 Chromium: 119.0.6045.163 (Official Build) beta (64-bit)
-- | --
Revision | eedc411877761f42fd7da9e25f94701edf477ac8
OS | Windows 10 Version 22H2 (Build 19045.3693)

```
- Verified the few icons and ensured icon's border are even for both the sides

Light mode | Dark mode 
-------------|--------------
![image](https://github.com/brave/brave-browser/assets/38657976/de5d838f-9d65-4e88-a7d7-6608773b4812) | ![image](https://github.com/brave/brave-browser/assets/38657976/a81b85f0-a1e2-42d5-b0f1-85f52a932731)

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.61.90 Chromium: 119.0.6045.163 (Official Build) beta (x86_64)
-- | --
Revision | 0e0de020c4ef9621e8a67a103299899837ce85a1
OS | macOS Version 11.7.10 (Build 20G1427)
```

example | example
---------|---------
<img width="143" alt="Screen Shot 2023-11-27 at 10 14 48 AM" src="https://github.com/brave/brave-browser/assets/387249/f4d8c591-b932-44c3-beb2-b1b1b75fbff9"> | <img width="149" alt="Screen Shot 2023-11-27 at 10 16 01 AM" src="https://github.com/brave/brave-browser/assets/387249/7e09f4e7-ba2c-40dc-9971-6b3075f1826b">
