### ISSUE TITLE
Android: Addressbar on the bottom

### ISSUE THREAD

**Issue by ShalokShalom** [brave/brave-browser#34524]
## Description 

Android has currently no feature to put the addressbar on the bottom

## Steps to reproduce 

   1. Open Brave on Android
   2. Realize that your fingers can reach the bottom easier than the top of the screen
   3. Want a setting (ideally set as default) that puts the addressbar on the bottom. 

## Issue reproduces how often 
Always

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes 
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Phone
   - Android version: 13
   
## Brave version
1.60.118

### Additional information

I come from Firefox, and this would be the only issue, that stops me from full adoption.

**Comment by Sym8** [comment]
You can enable the bottom toolbar in brave and it makes up for not having the address bar itself at the bottom.
![IMG_20231124_222903](https://github.com/brave/brave-browser/assets/66876418/645240b6-0ac6-4bad-bd87-c933ac7646df)
![IMG_20231124_222834](https://github.com/brave/brave-browser/assets/66876418/85af52b4-9342-4174-9912-af518bd56515)
But however adding the address bar itself to the bottom gives an advantage while using custom tabs and not interacting with the browser. example between Firefox and brave in custom tabs view.
![IMG_20231124_223027](https://github.com/brave/brave-browser/assets/66876418/fcfce7ab-2586-41a5-8328-12e2e88bc91c)
![IMG_20231124_223001](https://github.com/brave/brave-browser/assets/66876418/70073e38-a023-4bab-a6bb-37265b6bdd86)

**Comment by ShalokShalom** [comment]
I do think of it as lessening the issue, and not solving it. 
To me, there is no replacement to an address bar on the bottom. 

Its simply inconvenient, and I would honestly ditch a browser entirely just because it is lacking that. 

Does the Brave team an UX designer, that did look into this issue?

**Comment by norabelrose** [comment]
Would like to bump this. I'm moving from iOS to android and I was surprised to see this isn't an option given that Android is more customizable in general.

**Comment by rgreco87** [comment]
In 2024 this should be a must since Smartphone Display are increasing year after year.

**Comment by ShalokShalom** [comment]
> In 2024 this should be a must since Smartphone Display are increasing year after year.

Enabling the toolbar really helps. 😃

**Comment by norabelrose** [comment]
The toolbar definitely does help, but I still prefer the whole address bar being on the bottom. I've switched to the Samsung Browser for this reason.

**Comment by rgreco87** [comment]
> The toolbar definitely does help, but I still prefer the whole address bar being on the bottom. I've switched to the Samsung Browser for this reason.

Same here!

**Comment by HelgiMagic** [comment]
They can't add one feature in a year. OMG

**Comment by rgreco87** [comment]
I abandoned Brave and I'm trying Vivaldi Browser since one month.

It's the best Android Browser I've ever tried with a really customizable UI and a lot of features!

**Comment by bsclifton** [comment]
Thanks for the recommendation folks - and apologies for lack of a response here! This issue is actually a duplicate - you can track the feature request at https://github.com/brave/brave-browser/issues/7356 and subscribe for updates
