### ISSUE TITLE
Remove Wallet unused code related to old native UI

### ISSUE THREAD

**Issue by simoarpe** [brave/brave-browser#34526]
## Description 

Introducing WebUI to show portfolio screens has led to many unused class in native Wallet implementation. 
We should remove them, refactor and prune the Android Wallet.

**Comment by srirambv** [comment]
Verification passed on Google Pixel 8 with Android 14 running 1.65.96 x64 Beta build
- Verified steps from [brave/brave-core#22119](https://github.com/brave/brave-core/pull/22119)
- Verified all native UI works as expected without any regression
