### ISSUE TITLE
With transition from fastly proxies to python redirector update the whitelisted URLs

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#3453]
## Description 
We recently transitioned from using fastly proxies to redirector (https://github.com/brave/redirector/blob/master/redirector/__init__.py#L30) hosted on heroku. Update URL whitelist accordingly.

## Steps to Reproduce
   1. npm run test-security should pass

**Comment by LaurenWags** [comment]
@jumde is there manual QA required for this? If not, can we mark as QA/No?

**Comment by jumde** [comment]
@LaurenWags - Updated.

**Comment by LaurenWags** [comment]
thanks @jumde! 😄
