### ISSUE TITLE
Deny refresh of Leo page by pull down gesture

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#34532]
## Steps to reproduce 

   1. Open Leo
   2. pull down

## Actual result 
Leo is refreshed

## Expected result
Leo must not be refreshed

## Issue reproduces how often 
Easily

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP11.231020.013.A1 release-keys
Brave build: 1.62.114
Chromium: 120.0.6099.115 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-browser/issues/34532#issue-2010988069

**ACTUAL RESULTS:**
- Verified that `Leo` UI is not refreshing when using the `pull down` gesture
- Verified that `Leo` UI is not refreshing in `full screen` and `half-screen` modes

---------------------------

https://github.com/brave/brave-browser/assets/128532965/0dd299e9-5397-4c32-bcd0-18b6b5eeb091
