### ISSUE TITLE
Update STAR, add `Brave-Constellation-Rev` header to uploaded measurements

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-browser#34530]
Update sta-rs crate to 0.3.0 to address broken measurements caused by https://github.com/brave/sta-rs/issues/339.

Add `Brave-P3A-Version` header with a value of `2` when uploading measurements, so that the aggregation/collector server can ignore broken measurements.

**Comment by rillian** [comment]
Having a ratchet header seems helpful, but if the issue in epochs >128, wouldn't it be better to reset the randomness server's schedule so we lose a week of data from current clients instead of everything they send until they upgrade?

**Comment by DJAndries** [comment]
> Having a ratchet header seems helpful, but if the issue is epochs >128, wouldn't it be better to reset the randomness server's schedule so we lose a week of data from current clients instead of everything they send until they upgrade?

this would be a good way to expedite getting useful daily data, but it might require some changes in the randomness server such as supporting multiple `--epoch-base-time` values. Since daily support was added in 1.62.x/nightly, it might just be easier to update the client since we were not receiving much data anyway.

**Comment by rillian** [comment]
So you're planning to set different minima for the different channels, so the week-cadence measurements won't be affected for a while?

**Comment by DJAndries** [comment]
> So you're planning to set different minima for the different channels, so the week-cadence measurements won't be affected for a while?

Only daily submissions will have an enforced minimum. Weekly and monthly submissions will have no minimum.
