### ISSUE TITLE
Can't package extension crx file with `--pack-extension`

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#34544]
It's upstream issue - https://bugs.chromium.org/p/chromium/issues/detail?id=1498558
This regression affects our several CI jobs such as NTP SI publish(https://bravesoftware.slack.com/archives/CG08GKTFS/p1701061771648879)

@linhkikuchi set older version brave to that CI job and it worked.

cc @bsclifton @rebron

**Comment by bsclifton** [comment]
Looks like this fix was targeting M120 - are we good to close @simonhong?

**Comment by simonhong** [comment]
Yes! confirmed that `--pack-extension` switch works well with stable.
