### ISSUE TITLE
Page is unresponsive on Linux for `http://www.pbs.org/earth-a-new-wild/episode-plains/reindeer/`

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#3454]
## Description 

Page is unresponsive on Linux for `http://www.pbs.org/earth-a-new-wild/episode-plains/reindeer/`

## Steps to Reproduce

   1. Clean profile 0.59.35
   2. Open `http://www.pbs.org/earth-a-new-wild/episode-plains/reindeer/`
   

## Actual result:

Page unresponsive dialog is displayed, page doesn't load. Can't scroll or perform any operation
![image](https://user-images.githubusercontent.com/38657976/53238588-9b14dd00-36bf-11e9-97e5-9e4d9349bd08.png)

## Expected result:
The page should be responsive

## Reproduces how often: 

Always
## Brave version (brave://version info)

Brave	0.59.35 Chromium: 72.0.3626.81 (Official Build) (64-bit)
Revision	ac8b982e05014492d1bd7d317628a4f22a97ffa0-refs/branch-heads/3626@{#796}
OS	Linux Mint

### Reproducible on current release: Yes
- Does it reproduce on brave-browser dev/beta builds? Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional Information

The issue is reported by the community
https://community.brave.com/t/brave-crashes-on-a-specific-page-page-unresponsive-dialog-is-unresponsive/45713

**Comment by rebron** [comment]
@srirambv to reproduce.

**Comment by srirambv** [comment]
Reproduced the issue on Beta `0.61.47`. Loading the page and scrolling down it causes it to be freeze

**Comment by rebron** [comment]
fixed in 62?

**Comment by srirambv** [comment]
Sorry for delayed response. @rebron this looks fixed on 62. Closing the issue for now. Can reopen if it resurfaces
