### ISSUE TITLE
Brave News inline ad disappears after changing tabs

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#34543]
Found while testing #33578 

## Steps to reproduce 

1. Clean profile
1. Enable rewards
1. Join Brave News
1. Serve a Brave News inline ad
1. Switch tabs
1. Go back to the tab with Brave News

## Actual result 
Ad disappears

## Expected result
Ad does not disappear

## Issue reproduces how often 
Easily reproduced

Brave v1.61.86 on Lenovo TB-8506FS (Android 11.0)

cc @aseren @tmancey

**Comment by aseren** [comment]
The issue is not reproducible in Beta version 1.62.99.

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP11.231020.013.A1 release-keys
Brave build: 1.62.116
Chromium: 120.0.6099.144 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Followed the steps from https://github.com/brave/brave-browser/issues/34543#issue-2012060430

**ACTUAL RESULTS:**
- Verified that `news inline ad` is not removed when switching the tabs

---------------------------

https://github.com/brave/brave-browser/assets/128532965/7db13e40-b22a-4cb9-a9d3-e187c9cbed98
