### ISSUE TITLE
Tab crash at [*.]slack.com

### ISSUE THREAD

**Issue by wknapik** [brave/brave-browser#34545]
## Description 

See: https://bravesoftware.slack.com/archives/C01826CM3J9/p1699963966284039

A few sample crash IDs:
* d44c1c00-14aa-f80a-0000-000000000000
* bfb70000-6629-0b0b-0000-000000000000
* d8bc0000-6629-0b0b-0000-000000000000
* d3230200-f35a-140b-0000-000000000000

## Steps to Reproduce

   1. Go to api.slack.com (or any other subdomain of slack.com I've tried)

## Actual result:

Crash

![image](https://github.com/brave/brave-browser/assets/1129003/7e1b272e-5296-4698-b320-5aaeae59900f)
![image](https://github.com/brave/brave-browser/assets/1129003/8c945d75-0ef2-4cb6-bf37-94b6051e8fe0)

## Expected result:
No crash

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

1.60.118 Chromium: 119.0.6045.163 (Official Build) (64-bit) 

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

Arch Linux, x64
Also reported by @Sneagan on Manjaro Linux

**Comment by TechShooter** [comment]
Same problem on Windows x64 Brave 1.60.118 Chromium: 119.0.6045.163

**Comment by kjozwiak** [comment]
awesome, nice find @wknapik 👍 @TechShooter do you by any chance have the above extension installed? Or similar extensions by any chance? If so, does removing the extension fix the issue/crash?

**Comment by TechShooter** [comment]
I confirm Dark Reader causes the crash
