### ISSUE TITLE
Perf: reduce amount of function declarations in wallet panel container

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#34568]
## Description 

Currently, the main "container" component of the wallet panel declares many functions that may not be immediately needed. Move these functions to their applicable screens

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.62.128 Chromium: 120.0.6099.144 (Official Build) beta (64-bit)
-- | --
Revision | 41f5844c06c7db1017f39b5b6dc9ba81a6b1b9d6
OS | Windows 11 Version 23H2 (Build 22631.2861)

- Verified steps from [brave/brave-core#21130](https://github.com/brave/brave-core/pull/21130)
- Verified `Change network` works as expected in wallet panel
- Verified `Connect hardware Wallet` opens up a new tab and loads `brave://wallet/crypto/accounts/add-account/hardware`
- Verified `ProvidePubKeyPanel (encryption key panel)` works as expected
- Verified `Sign Panel` works as expected
- Verified `Welcome` panel works as expected and loads onboarding in a new tab
