### ISSUE TITLE
VPN up, geolocation leaked

### ISSUE THREAD

**Issue by ParaplegicRacehorse** [brave/brave-browser#34560]
## Description 

GeoLocation leaked when operating behind a VPN.

## Steps to Reproduce

   1.  Start ProtonVPN and select a country 10 time-zones different from my actual geolocation for exit node.
   2.  Start Brave browser. Configure to universally block geolocation sharing.
   3.  Visit a site known to geoblock my country.
   4.  Note that I am blocked and, further, the site correctly identified my country.

## Expected result:

   1.  Start ProtonVPN and select country 10 time-zones different from my actual geolocation for exit node.
   2.  Start Brave browser. Configure to universally block geolocation sharing.
   3.  Visit a site known to geoblock my country.
   4.  Pleasantly interact with visited website.

## Reproduces how often: 

Easily reproduced, though not universally reproducible. Reproducible with all proxies and all VPNs I tested under.

## Brave version (brave://version info)

Brave: 1.60.118 Chromium: 119.0.6045.163 (Official Build) unknown (64-bit) 
Revision: b0599b790dbdfe28428202afe2b54758a044ccfc
OS: Linux
JavaScript: V8 11.9.169.6
Package Format: Flatpak; source: Flathub

## Version/Channel Information:

This is reproducible with current stable release, linux flatpak from flathub.
I did not attempt with unstable or nightly.

## Other Additional Information:

- Is the issue reproducible on the latest version of Chrome? 
Unknown, I don't Google Chrome. This is also reproducible with same reliability with  Firefox v119.

**Comment by fmarier** [comment]
Another thing to check: what do you have the -_WebRTC IP handling policy_ set to in `brave://settings/privacy`?

The value that's guaranteed not to leak any of your IP addresses is _Disable non-proxied UDP_.

**Comment by ParaplegicRacehorse** [comment]
> The value that's guaranteed not to leak any of your IP addresses is _Disable non-proxied UDP_.

Just tried this. Sadly, it failed.

I begin to wonder if the problem is an extension?  I don't know how to test for this, though, except to disable extensions.  Since the site(s) I'm particularly interested in accessing are web3 and the extension(s) in question are wallets, disabling them would defeat the purpose.

**Comment by fmarier** [comment]
> I begin to wonder if the problem is an extension? 

That's also a possibility. Extensions can do a lot of things in the browser.

Maybe you could try disabling all of your extensions instead of the one that is required for the web3 connection?

**Comment by bsclifton** [comment]
Interesting - I've only seen this happen on Windows (which has a problem with Smart Multi-homed Name Resolution)

A good test page is https://dnsleaktest.com/

@ParaplegicRacehorse did you have an update if disabling extensions did anything? Also curious if you have any proxy settings setup? Something you might try - visit brave://settings/security and enable secure DNS. Basically make sure you're using DNS over HTTPS. 

Let us know please. Thanks!

**Comment by mattmcalister** [comment]
Closing this issue, though please re-open if you're still seeing this issue. Thanks!
