### ISSUE TITLE
Gemini disabled Brave integration 

### ISSUE THREAD

**Issue by DemonRx** [brave/brave-browser#34562]
![Screenshot20231128Gmail.jpg](https://github.com/brave/brave-browser/assets/18432686/3de0fe34-1d0b-4932-86ad-d87b6e202a16)

Is there an alternative option ?

**Comment by evanrgardner** [comment]
Please see the latest below regarding Gemini connections.
 
https://community.brave.com/t/gemini-logged-out-and-your-request-is-still-being-processed-issue-faq/513629/2
 
Thanks!

**Comment by DemonRx** [comment]
> Please see the latest below regarding Gemini connections.
>  
> https://community.brave.com/t/gemini-logged-out-and-your-request-is-still-being-processed-issue-faq/513629/2
>  
> Thanks!

https://community.brave.com/t/gemini-logged-out-and-your-request-is-still-being-processed-issue-faq/513629/6?u=demonfury

Well to be honest thanks for the link to this post but it really doesn't say much more than we're pretty much stuck where we're at right now. 

So the question is what happens to the BAT rewards we're getting within Brave can we send them to another wallet?

**Comment by Miyayes** [comment]
Yes, Gemini is currently not taking in new users via Brave Rewards. So, you won't be able to connect a new device or Rewards profile to your Gemini account. However, if your Brave Rewards profile is _already_ connected to Gemini, then the integration should continue to work.

**Comment by Miyayes** [comment]
>So the question is what happens to the BAT rewards we're getting within Brave can we send them to another wallet?

So, if you don't have a custodial account (e.g., Gemini, Uphold, etc.) account connected to Brave Rewards, you won't be earning BAT rewards in the first place. You only start earning for yourself once you connect an account, which gives us a place to send you your BAT. Hope that helps!

**Comment by DemonRx** [comment]
Brave needs to provide a non centralized method to store our BAT token rewards. It is not acceptable in a decentralized system that the only choice to control our tokens is through a CEX. 

They should be able to adapt to be able to provide a wallet address to send them to or store them into the integrated brave wallet and transfer them as we please. 

So I need a better solution than what @Miyayes provided. His comment contradicted himself, because, Gemini has stopped connecting with Brave entirely, regardless of customer status or device. (See my first comment on this issue). 

Furthermore, they disconnected accounts that were already connected (as mine was), and I'm a customer with them for over 5 years. 

So again how can we get our BAT out of brave without using a CEX?

**Comment by DemonRx** [comment]
> >So the question is what happens to the BAT rewards we're getting within Brave can we send them to another wallet?
> 
> So, if you don't have a custodial account (e.g., Gemini, Uphold, etc.) account connected to Brave Rewards, you won't be earning BAT rewards in the first place. You only start earning for yourself once you connect an account, which gives us a place to send you your BAT. Hope that helps! 

Sir, do you understand they disconnected Brave completely?  There is no logging in anymore. Everyone is affected ! We have no option to connect to any other platform to transfer the BAT we earn. 

There needs to be a new solution we can't wait for Gemini to fix it. They have enough problems right now that their future is unknown. 

Also I think you don't realize that many users had their BAT in the Gemini earn program that's now in court and we are waiting for them to compensate us. I believe this is why they discontinued the connection with Brave.

This issue needs to be reopened and addressed accordingly.

**Comment by Miyayes** [comment]
>Sir, do you understand they disconnected Brave completely? There is no logging in anymore. Everyone is affected ! We have no option to connect to any other platform to transfer the BAT we earn.

Sorry, can you clarify what you mean by not being able to log in anymore? What are you seeing in your UI? For example, are you seeing "Gemini" grayed out as an option? Or, are you in the "Logged out" state, and when you try to log back into Gemini, you get an "Error processing request" error? 

>We have no option to connect to any other platform to transfer the BAT we earn.

Please note that by definition, you can only earn BAT from Brave Rewards after you have connected a custodial account (such as a Gemini, Uphold, ZebPay, etc.) to your Brave Rewards profile. Accordingly, there is no such thing as "transfer the BAT we earn", since you are not earning anything prior to connecting an account.

**Comment by DemonRx** [comment]
> >Sir, do you understand they disconnected Brave completely? There is no logging in anymore. Everyone is affected ! We have no option to connect to any other platform to transfer the BAT we earn.
> 
> Sorry, can you clarify what you mean by not being able to log in anymore? What are you seeing in your UI? For example, are you seeing "Gemini" grayed out as an option? Or, are you in the "Logged out" state, and when you try to log back into Gemini, you get an "Error processing request" error? 
> 
> >We have no option to connect to any other platform to transfer the BAT we earn.
> 
> Please note that by definition, you can only earn BAT from Brave Rewards after you have connected a custodial account (such as a Gemini, Uphold, ZebPay, etc.) to your Brave Rewards profile. Accordingly, there is no such thing as "transfer the BAT we earn", since there are no earnings prior to connecting an account.

![Screenshot_20231129_082832_Brave.jpg](https://github.com/brave/brave-browser/assets/18432686/939bc462-3861-42a0-8f1f-b4248dde8253)

![Screenshot_20231129_082927_Brave.jpg](https://github.com/brave/brave-browser/assets/18432686/37e29a34-9f1e-4451-97e8-f98f187532ac)

![Screenshot_20231129_082938_Brave.jpg](https://github.com/brave/brave-browser/assets/18432686/2e2e8290-adf0-4982-baf2-523d4d0f6d50)

**Comment by Miyayes** [comment]
Okay, so you're in the logged out state and unable to log in again. **Please see this post:** https://community.brave.com/t/gemini-logged-out-and-your-request-is-still-being-processed-issue-faq/513629 

Note that this does not affect your payouts, and you should still be receiving payouts just fine. The above post covers all points.

**Comment by DemonRx** [comment]
> Okay, so you're in the logged out state and unable to log in again. **Please see this post:** https://community.brave.com/t/gemini-logged-out-and-your-request-is-still-being-processed-issue-faq/513629 
> 
> Note that this does not affect your payouts, and you should still be receiving payouts just fine. The above post covers all points. Thanks!
> 
> P.S., The response you received from Gemini support is unrelated. The support agent was probably referring to the fact that Gemini is not taking in new users via Brave Rewards right now, and wasn’t familiar with this other more specific issue.

Ok I should be getting a payout next month. I'll confirm here if it is received.

**Comment by DemonRx** [comment]
I explained to Gemini support everything I've learned from here. They responded with this
 today![Screenshot_20231130_122333_Gmail.jpg](https://github.com/brave/brave-browser/assets/18432686/b197987a-7873-46f5-bcb2-006724fa7b7b)

They are clearly saying there is no connectivity with brave as they have disable it entirely, regardless of old or new accounts. 

So does anyone know here what exactly is going on ?

But this goes to say what I was exclaiming previously that Brave needs to not use a CEX and stay decentralized keeping our $BAT in an integrated browser wallet or be able to add an EVM address that we can send the funds out to.

**Comment by DemonRx** [comment]
> > They are clearly saying there is no connectivity with brave as they have disabled it entirely, regardless of old or new accounts.
> 
> @DemonRx you seem to not be seeing what they have written. They said **If you try to link your wallet for the first time....**

Yes I understood this regarding **new** links. 

> 
> They didn't say you won't be able to reconnect on an existing device/profile. 
> 
> When it's been spoken that older accounts will be able to connect, they are referring to people who have already had their existing Rewards profile linked to Gemini. Brave is working with Gemini to make sure that if you get in a logged out state, you'll reconnect. 

Right, this is what I'm waiting to see get resolved.
At the same time, as was posted previously, even so we're in a *logged out* state, rewards should be still received into our Gemini account... And I'm waiting for this to happen over the next days as I have pending $BAT rewards waiting to transfer. 

I'll update here if I see them received or not. 
 
> 
> However, if you get a new device or Reset your Rewards, then you would not be able to connect again. No new connections can be made through the integration. 

Got it 👍

Thank you as well for providing insight on this. Sorry for the late response being a weekend.

**Comment by DemonRx** [comment]
@Saoiray @Miyayes I received my November payout. So at least that is working. 👍

Hopefully however Brave will migrate to a fully decentralized wallet or method of transferring tokens to our own self-custody wallets. 🙏

![Screenshot20231207175805Gemini.jpg](https://github.com/brave/brave-browser/assets/18432686/a26ff609-ac20-4cdf-ae72-f77c791ae7f0)
