### ISSUE TITLE
Perf: cache connected site info for origins

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#34572]
## Description 

cache connected site info for origins and add to queries to fetch this data on demand

**Comment by srirambv** [comment]
Verification passed on <html>
<body>

Brave | 1.63.146 Chromium: 121.0.6167.139 (Official Build) beta (64-bit)
-- | --
Revision | cb9ee9c98182a64716e4237bf1202f1aec3bcff8
OS | Windows 11 Version 23H2 (Build 22631.3007)

- Verified steps from [brave/brave-core#21136](https://github.com/brave/brave-core/pull/21136)
- Verified site connection features work as expected without regressions
