### ISSUE TITLE
CR 120 - Cookies and site data and `Manage on-device site date` settings are separated by two horizontal lines

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#34571]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/33471
Cookies and site data and `Manage on-device site date` settings are separated by two horizontal lines
## Steps to Reproduce

   1. Clean profile 1.62.86 CR 120
   2. Open cnn.com
   3. Open site settings 
   4. Click on `Cookies and site data`
   5. Two horizontal lines are added in `Cookies and site data` modal

## Actual result:

Cookies and site data and `Manage on-device site date` settings are separated by two horizontal lines

![image](https://github.com/brave/brave-browser/assets/38657976/c1cc9af7-6742-4c4c-a131-11c5814a75fa)

## Expected result:
Not sure whether to keep `Manage on-device site date` settings in brave or retain the old settings. Refer the thread for more info https://bravesoftware.slack.com/archives/C7VLGSR55/p1701180529136849?thread_ts=1701121933.276189&cid=C7VLGSR55 

RC 1.60.x
![image](https://github.com/brave/brave-browser/assets/38657976/104af3a6-03ce-49af-98e4-ae19c36eb6e8)

## Reproduces how often: 

Easy
## Brave version (brave://version info)

Brave | 1.62.86 Chromium: 120.0.6099.35 (Official Build) nightly (64-bit)
-- | --
Revision | f248c65a74007536fb36959f92fc01fcb752e5fc
OS | Windows 10 Version 22H2 (Build 19045.3693)

## Version/Channel Information:

- Can you reproduce this issue with the current release?  No
- Can you reproduce this issue with the beta channel? No 
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @rebron @mkarolin

**Comment by rebron** [comment]
cc: @mkarolin

**Comment by kjozwiak** [comment]
The above will be uplifted into `1.61.x` via https://github.com/brave/brave-core/pull/21135 hence not adding the required version for verification on `1.62.x`. However, the above was verified on Nightly via https://github.com/brave/brave-core/pull/21152#issuecomment-1836734273 before uplifting.

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.61.94 Chromium: 120.0.6099.56 (Official Build) (64-bit)
-- | --
Revision | 72759647494f071d653f8a61465fadf5f361b06e
OS | Windows 10 Version 22H2 (Build 19045.3693)

```
Using the STR/Cases outlined via https://github.com/brave/brave-browser/issues/34571#issue-2014914947, ensured that there's only a single horizontal separator as per the following:

**`Example`** | **`Example`** | **`Example`**
----------------|----------------|-----------------
![image](https://github.com/brave/brave-browser/assets/38657976/591033a4-ce7d-4275-8e01-fcbba2988ae8) | ![image](https://github.com/brave/brave-browser/assets/38657976/85de6407-c2a5-4f38-b748-f3749dc03a68) | ![image](https://github.com/brave/brave-browser/assets/38657976/ac5e239e-6c12-450f-95d9-9e3123552bfa)
