### ISSUE TITLE
[Leo] The `Three-dot` menu button overlaps the response text

### ISSUE THREAD

**Issue by hffvld** [brave/brave-browser#34579]
## Description 

The `Three-dot` menu button overlaps the response text.

## Steps to reproduce 

   1. Launch Brave (Nightly)
   2. Three dot menu > Leo
   3. Ask anything and wait for a response > Observe 

## Actual result 

The `Three-dot` menu button overlaps the response text.

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/567f0ae5-c77a-4dc0-a3ad-1d2a73ed251a) | ![2](https://github.com/brave/brave-browser/assets/128532965/3e3eb93c-da20-4699-bd59-ee3e009a3d8e) |

## Expected result

The `Three-dot` menu button must not overlap the text.

## Issue reproduces how often 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? N/A
- Can you reproduce this issue with the current Play Store Beta version? N/A
- Can you reproduce this issue with the current Play Store Nightly version? YES

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Any
   - Android version: Any
   
## Brave version

```
Brave build: 1.62.84 
Chromium: 119.0.6045.163 (Official Build) canary (64-bit)
```

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by mattmcalister** [comment]
Should be resolved by https://github.com/brave/brave-browser/issues/35587

**Comment by SergeyZhukovsky** [comment]
closing as it's a dup and resolved by https://github.com/brave/brave-browser/issues/35587
