### ISSUE TITLE
Filter out Klaviyo's user identifier from URLs

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#34578]
Klaviyo uses the `_kx` parameter to [track individual users](https://help.klaviyo.com/hc/en-us/articles/115005248128#section2) clicking on email links.

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.62.93 Chromium: 120.0.6099.35 (Official Build) beta (x86_64)
-- | --
Revision | 2032da61e85b8d826ab474ee36fee9a9cee09907
OS | macOS Version 14.2 (Build 23C5055b)
```

### Steps:
1. installed `1.62.93`
2. launched Brave
3. loaded `https://brave.com/?foo=yes&_kx=1234`
4. checked developer tools' `Network` tab

### Confirmed only `https://brave.com/?foo=yes` was loaded

<img width="1806" alt="Screenshot 2023-12-02 at 3 13 20 AM" src="https://github.com/brave/brave-browser/assets/387249/a6438da5-0db3-49c6-a45d-ea773f32946f">

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP11.231020.013.A1 release-keys
Brave build: 1.61.100
Chromium: 120.0.6099.62 (Official Build) (64-bit) 
```
---------------------------

**STEPS:**
1. Launch Brave
2. Go to `https://brave.com/?foo=yes&_kx=1234`
checked developer tools' Network tab

**ACTUAL RESULTS:**
- Verified that only `https://brave.com/?foo=yes` was loaded

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/c529ffd5-691a-4d00-be94-09656175193c) | ![2](https://github.com/brave/brave-browser/assets/128532965/a9196cbf-741b-4bd4-acf9-96fa9e50e418) | ![3](https://github.com/brave/brave-browser/assets/128532965/199609d0-c64a-4954-ab19-325727da677c) |
