### ISSUE TITLE
Build out Composer UI Select Address Modal

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#34581]
## Description 

We need to build out the new `Composer UI` `Select Address` Modal

![Screenshot 22](https://github.com/brave/brave-browser/assets/40611140/789cfde8-057c-4d3a-995f-38e2dcff45bd)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.66.97 Chromium: 124.0.6367.118 (Official Build) beta (64-bit)
-- | --
Revision | 94909f2aaefd7a8137c8b4fa27235378e79231e3
OS | Windows 11 Version 23H2 (Build 22631.3527)

- Verified steps from [brave/brave-core#22720](https://github.com/brave/brave-core/pull/22720)
- Verified new composer UI is shown for Select Address modal
- Verified for valid/invalid/invalid extension/same address/missing checksum and offchain address resolution

https://github.com/brave/brave-browser/assets/17010094/5cf1b147-8a15-408a-95c3-40f661a32236
