### ISSUE TITLE
Build out New Quote Countdown

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#34583]
## Description 

For `Bridge` and `Swap` we need to display a `countdown` ticker showing the time in `seconds` until a new `quote` is fetched.

![Screenshot 24](https://github.com/brave/brave-browser/assets/40611140/04d6290a-3418-438a-a6a1-79791cc180ed)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.69.124 Chromium: 127.0.6533.73 (Official Build) beta (64-bit)
-- | --
Revision | dbc9035349f74e493f3293d93f4cbf35c597dfec
OS | Windows 11 Version 23H2 (Build 22631.3880)

- Verified steps from [brave/brave-core#24050](https://github.com/brave/brave-core/pull/24050)
- Verified countdown starts for 10sec when quote is fetched for Swap/Bridge
- Verified `Review Swap` or `Review Bridge` button changes to `Fetching quote` when the countdown ends or manually refreshed

https://github.com/user-attachments/assets/b7972083-5ac6-4a7c-b53d-140fd8fa497f
