### ISSUE TITLE
Build out Composer UI Advanced Settings Modal

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#34582]
## Description 

We need to build out the new `Composer UI` `Advanced Settings` modal

![Screenshot 23](https://github.com/brave/brave-browser/assets/40611140/ead66d97-53d8-46b8-8508-368f4f16ae95)

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.63.155 Chromium: 122.0.6261.29 (Official Build) (64-bit)
-- | --
Revision | b2be2c6f5b7340629f672ce706f5bfd62b113f82
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from [brave/brave-core#21377](https://github.com/brave/brave-core/pull/21377)
- Verified Swap settings is updated to new UI
- Verified settings works as expected without any regression

https://github.com/brave/brave-browser/assets/17010094/7fcf0b63-772c-40c0-a104-8b12bb951c60
