### ISSUE TITLE
AC delete doesn't remove duration from the table

### ISSUE THREAD

**Issue by NejcZdovc** [brave/brave-browser#3459]
## Steps to Reproduce

   1.  enable rewards
   2. visit a site
   3. make sure that you see it in ac table
   4. delete that site
   5. restore this site

## Actual result:

Site is listed with duration and %.

## Expected result:
Site shouldn't be shown and data in the db should be deleted for the current month

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by GeetaSarvadnya** [comment]
Blocked and unable to test due to https://github.com/brave/brave-browser/issues/3850

**Comment by kjozwiak** [comment]
@GeetaSarvadnya what you noticed in #3850 is expected behaviour. This issue fixes that. When you're restoring a removed website from the table, it won't restore the past duration.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.64.24 Chromium: 73.0.3683.75 (Official Build) nightly (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17134.523

Used test plan from https://github.com/brave/brave-core/pull/1889
Also checked that the publisher can be re-added to the a-c table after being restored.
