### ISSUE TITLE
Keyboard shortcuts and context menu options should be retained similar to browser-laptop

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#346]
## Description 
Keyboard shortcuts and context menu should be retained similar to browser-laptop? There are a few differences and some missing listed below

Action | b-l shortcut | brave-core shortcut 
--|--|--
History | Ctrl+Y | Ctrl+H
Reopen Last Window | Ctrl+Shift+Alt+T | Ctrl+Shift+T (no dedicated shortcut for reopen closed window)
Exit/Quit browser | Ctrl+Q | Ctrl+Shift+Q
Jump into the URL bar | Ctrl+L | Ctrl+K
Open Dev tools | Ctrl+Shift+I | Ctrl+Shift+C
Reload/Clean Reload | Context menu on reload button | No context menu on reload button
Detach Tab | Context menu option on tab | No context menu option
Close tabs to left | Context menu option on tab | No context menu option
Mute other tabs | Context menu option on tab | No context menu option
Settings | Ctrl+, | No KB shortcut
Back | Ctrl+[ | No KB shortcut
Forward | Ctrl+] | No KB Shortcut
Minimize Window | Ctrl+M | No KB Shortcut
Move tab to right | Ctrl+Shift+PageDwn | No KB Shortcut
Move tab to left | Ctrl+Shift+PageUp | No KB Shortcut
Search from anywhere on the page | No KB Shortcut | Ctrl+E or Ctrl+K
Submit Feedback(Open a feedback form) | No KB Shortcut | Alt+Shift+I (Shortcut doesn't work on brave-core at the moment but can be utilized to open community page)

## Brave version (about:brave info)
Verified on release build(332140d)

cc: @bbondy

**Comment by bbondy** [comment]
Nice info and comparison. I don't think we need to block on the differences, I think we should sit on it a bit and see what becomes important from reports.

**Comment by AndrewNduati** [comment]
I don't know whether this belongs here but I would like the **Quit/Exit Browser** shortcut (**Cmd + Q**) to  require a "hold" similar to Chrome.

The reason being that the **close Tab** shortcut is (**Cmd +W**) thereby leading to many accidental browser exits when the intention was closing a Tab.

**Comment by bbondy** [comment]
@srirambv I think we want to keep parity with Chrome shortcuts, but for any additional features we have we'd do our own.  That means that people that migrate might have to learn some new shortcuts. But more users will be familiar with the Chrome shortcuts.

**Comment by srirambv** [comment]
Closing based on @bbondy comment. can create or reopen issue if too many request come for browser-laptop shortcuts to be implemented.
