### ISSUE TITLE
 CR 120 - Redundant settings `Show images on tab hover preview cards` is inherited from chrome

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#34608]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/33471
CR120 - Redundant settings `Show images on tab hover preview cards` is inherited from chrome

Brave has `Card with preview` settings already which is the same as the `Show images on tab hover preview cards` settings, not sure why this redundant settings is added in brave://settings/appearance
## Steps to Reproduce

  NA
## Actual result:

![image](https://github.com/brave/brave-browser/assets/38657976/8d582a38-92cc-4ff0-9908-8c74cd7c382c)

## Expected result:
Brave has `Card with preview` settings already which is the same as the `Show images on tab hover preview cards` settings. I don't think we need this settings cc: @rebron 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.62.87 Chromium: 120.0.6099.35 (Official Build) nightly (64-bit)
-- | --
Revision | e0cd7777fe0c2b5f4fe9e1bc27cedd1f87eac37f
OS | Windows 10 Version 22H2 (Build 19045.3693)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/qa-team @rebron @mkarolin

**Comment by sebastianmariani** [comment]
I would like to work on this

**Comment by kjozwiak** [comment]
The above will be uplifted into `1.61.x` via https://github.com/brave/brave-core/pull/21135 hence not adding the required version for verification on `1.62.x`. However, the above was verified on Nightly via https://github.com/brave/brave-core/pull/21153#issuecomment-1836770483 before uplifting.

**Comment by kjozwiak** [comment]
The above requires `1.61.94` or higher for `1.61.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.61.94 Chromium: 120.0.6099.56 (Official Build) (64-bit)
-- | --
Revision | 72759647494f071d653f8a61465fadf5f361b06e
OS | Windows 10 Version 22H2 (Build 19045.3693)
```

Using the STR/information via https://github.com/brave/brave-browser/issues/34608#issue-2016251035, ensured that the redundant `Show images on tab hover preview cards` toggle was removed from `brave://settings/appearance` as per the following:

* ensured that `Tab hover mode` was still visible under `Tabs` via `brave://settings/appearance`
* ensured that `Card` was set as the default on new installs/new profile
* ensured that `Card with preview` & `Tooltip` were working as expected

**`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|-----------------
![image](https://github.com/brave/brave-browser/assets/38657976/34710411-e114-4588-bd31-f207db25804b) | ![image](https://github.com/brave/brave-browser/assets/38657976/33889050-2964-445d-bb30-66cb64d474c2) | ![image](https://github.com/brave/brave-browser/assets/38657976/0ac628a3-49c2-4b84-9d2b-abdde9a9f5d8) | ![image](https://github.com/brave/brave-browser/assets/38657976/a8db4062-432b-464e-b9f3-8fa2024aec5e)
