### ISSUE TITLE
`Leo` switches identities/contexts within the same article

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#34609]
## Description 

`Leo` switches identities/contexts within the same article

## Steps to Reproduce

   1. install `1.62.89`
   2. launch Brave
   3. load `https://www.foodnetwork.com/healthy/articles/how-much-sugar-banana`
   4. click on `Leo` in the sidebar
   5. click on `Summarize this page`
   6. note the response preamble `As a helpful AI assistant...`
   7. click on `Suggest questions...` 
   8. click through each of the `Suggested follow-ups` and note the response preamble/mini-intro `"As a registered dietrition nutritionist"` (that's a mouthful, straight from the article)

## Actual result:

`Summarize this page` | `registered dietitian nutritionist` | `helpful AI assistant`
---------|----------|--------
<img width="1466" alt="Screen Shot 2023-11-29 at 1 30 18 AM" src="https://github.com/brave/brave-browser/assets/387249/304f165b-647a-4c61-ab9b-2e6156a528bb"> | <img width="1466" alt="Screen Shot 2023-11-29 at 1 30 36 AM" src="https://github.com/brave/brave-browser/assets/387249/28b1cdad-fcb5-43db-8412-450f25233d2a"> | <img width="1466" alt="Screen Shot 2023-11-29 at 1 44 45 AM" src="https://github.com/brave/brave-browser/assets/387249/1263ba78-3523-4a1a-92c0-33c8ad69ae91">

## Expected result:

It should stay `...helpful AI assistant` and not claim to be a `registered dietitian nutritionist`

## Reproduces how often: 

100% with the above article

## Brave version (brave://version info)

```
Brave | 1.62.89 Chromium: 120.0.6099.35 (Official Build) nightly (x86_64)
-- | --
Revision | f68a18538c0af7dba0f91c6176be4c1eee17101c
OS | macOS Version 11.7.10 (Build 20G1427)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

/cc @LorenzoMinto @mattmcalister @bbondy @petemill @brave/qa-team

**Comment by mattmcalister** [comment]
Not seeing this behavior anymore. Closing.
