### ISSUE TITLE
Dump without crashing when trying to import image via IPFS

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#34611]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.62.87 Chromium: 120.0.6099.35
Operating System: Windows NT 10.0.22631

URL (if applicable) where crash occurred:

Can you reproduce this crash? Yes, when Image import fails

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Install IPFS and set to localhost resolve
2. Right click on any image on any page and try to import
3. Creates a dump file when import fails but doesn't cause any crash

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/d7910e00-f35a-140b-0000-000000000000
Crash ID: crash/5a8d0e00-f35a-140b-0000-000000000000

cc: @vadimstruts

**Comment by iefremov** [comment]
It seems this one was fixed at some point, doesn't repro after cr123

**Comment by iefremov** [comment]
sorry posted the comment to a wrong issue. The backtrace entries are dead, so if @srirambv you could repro and upload new dumps we can reevaluate

**Comment by iefremov** [comment]
stale
