### ISSUE TITLE
[Brave News]: Feed v2 tweaks round

### ISSUE THREAD

**Issue by LorenzoMinto** [brave/brave-browser#34621]
Minor visual tweaks from discussion with @martin-c0des 

**General**
- [x] Top and bottom margins on cards should be adjusted
- [x] Card titles should be pinned to metadata (now vertically centered)
- [x] Bump up font weight for headline text
- [x] Remove "(discovering)" tag
- [x] Ad button different from designs (see Figma)
- ~Open in New Tab by default~

**Empty Feeds**
- [x] Empty feed UI tweaks (see Figma)
- [x] Change copy from "Feed is empty" to "There doesn't seem to be any articles in this feed at this moment. Try coming back later."

**Suggestion Cards**
- [x] Cover images look too big, see Customize interface (could we reuse component from there?)
- [x] Publisher titles should be centred wrt to cover image
- [x] Change copy from "Sources You'll Enjoy" to "You might also like"

**RSS Feeds**
- [x] Publisher name missing, should fallback to domain

**Comment by fallaciousreasoning** [comment]
Going to move the `Open in New Tab` by default to a new issue.

**Comment by kjozwiak** [comment]
The above requires `1.62.109` or higher for `1.62.x` verification 👍

**Comment by stephendonner** [comment]
## Verification `PASSED` using

```
Brave | 1.62.112 Chromium: 120.0.6099.115 (Official Build) beta (x86_64)
-- | --
Revision | ae1e179b9884b2de2f4ba0bdea7da3beaad93ffa
OS | macOS Version 11.7.10 (Build 20G1427)
```

## "(discovering)" tag should not appear in feed - `PENDING`
<details>

### Steps:
1. installed `1.62.112`
2. launched Brave
3. skipped onboarding
4. scrolled down
5. clicked on `Turn on Brave News`
6. scrolled down

## Confirmed the `(discovering)` tag did NOT appear in my feed, using `Top Sources`


example | example | example
---------|------------|----------




</details>

## Publisher suggestions should be tagged with `You might also like` - `PENDING`
<details>

### Steps:
1. installed `1.62.112`
2. launched Brave
3. skipped onboarding
4. scrolled down
5. clicked on `Enable Brave News`
8. clicked on `Customize`
9. added `CNN`
10. refreshed my feed
11. scrolled down

### Confirmed publisher-suggested sources are tagged with `You might also like`





</details>


## Empty-feed UI/UX - `PENDING`
<details>

### Steps:
1. installed `1.62.112`
2. launched Brave
3. skipped onboarding
4. scrolled down
5. clicked on `Enable Brave News`
6. clicked on `Customize`
7. unsubscribed from `Top Sources`
8. clicked on the `x` to close the `Customize` dialog

## Confirmed `This feed is empty` with `Refresh` button (and repopulation of feed)

example | example | example
----------|-----------|----------




</details>


## Direct feeds - `PENDING`
<details>

### Steps:
1. installed `1.62.112`
2. launched Brave
3. skipped onboarding
4. scrolled down
5. clicked on `Turn on Brave News`
6. clicked on `Customize`
7. unsubscribed from `Top Sources`
8. subscribed to `chriscoyier.net`

### Confirmed feed articles from `chriscoyier.net` appeared, with working links

example | example | example | example
----------|-----------|----------|----------




</details>


## Ad button should NOT be "blurple" - `PENDING`
<details>

### Steps:
1. installed `1.62.112`
10. launched Brave
11. skipped onboarding
12. scrolled down
13. clicked on `Turn on Brave News`
14. scrolled down until I saw a "promoted content" (formerly known as) advertisement

### Confirmed the `Ad` icon was marked and appeared in gray




</details>

**Comment by sfenne** [comment]
I'm sorry, but is it necessary to include "You might also like"? 
I consider this as ads, especially since I've added my own trusted news sources.

"You might also like" is the only thing that prevents me from having a 100% clean news feed.

Please make this feature optional.

On an unrelated note, I recently deleted Spotify because of their excessive use of "You might also like".

I understand the feature and I know some appreciate it, but the suggestions are wrong 99% of the time which makes it a more a disturbance than anything else.

Thanks

**Comment by fallaciousreasoning** [comment]
cc @LorenzoMinto - we could remove suggestions in the Following feed?
