### ISSUE TITLE
just installed brave and can't log in twitch

### ISSUE THREAD

**Issue by Makezu90** [brave/brave-browser#34627]
## Description 

Installed Brave first time, cant log in twitch. Accept cookies on twitch.tv site not will clear that banner. I tried turn off couple extension which im 99% sure these can cause issues, but that not helped. These same extension have also on other browser and log in works fine.

## Steps to Reproduce

   1.  install brave
   2.  go to twitch.tv site
   3. log in

## Actual result:

Not supported browser.

## Expected result:

Browser supported and can log in.
## Brave version (brave://version info)

W11 Pro, 22631.2715

1.60.125 Chromium: 119.0.6045.199 (Virallinen koontiversio) (64-bittinen) 
 
## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
<img width="509" alt="Screenshot 2023-11-29 at 12 02 32 PM" src="https://github.com/brave/brave-browser/assets/5951041/5c5f3b8d-96eb-4c47-979e-2a76e9bd6461">
I ran into this screen on beta but not on 1.60.125

**Comment by Makezu90** [comment]
i got it work now not sure what caused that. 

atleast i imported data from chrome to brave firstly and then tried log in, not worked. But then i tried trick reinstall fully browser and import data after i have logged twitch already and now i tried log out and log in back, it works.
