### ISSUE TITLE
URL check in bat_get_media.cc is not strict enough

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-browser#3462]
https://github.com/brave/brave-core/blob/194e5db6b091490576ce8bd191004cd12dc5c7d6/vendor/bat-native-ledger/src/bat_get_media.cc#L46

i assume `url.find(".ttvnw.net/v1/segment/")` is trying to match subdomains of ttvnw.net, but it would actually match arbitrary domains like this: `https://example.com/something.ttvnw.net/v1/segment/` because `.` is valid in URL paths.

cc @SergeyZhukovsky @jasonrsadler

**Comment by jasonrsadler** [comment]
We're going to need some kind of url parser for this. 

@bridiver Can we use GURL for this?

https://github.com/brave/brave-core/blob/194e5db6b091490576ce8bd191004cd12dc5c7d6/vendor/bat-native-ledger/src/bat_get_media.cc#L47

`url.find("https://ttvnw.net/v1/segment/") != std::string::npos` would match: `https://baddomain.com?maliciousparam=https://ttvnw.net/v1/segment/`

**Comment by jasonrsadler** [comment]
Adding QA-Yes for regression testing

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.63.14 Chromium: 73.0.3683.75 (Official Build) dev (64-bit)
-- | --
Revision | 909ee014fcea6828f9a610e6716145bc0b3ebf4a-refs/branch-heads/3683@{#803}
OS | Windows 10 OS Build 17134.523

Verified test plan from https://github.com/brave/brave-core/pull/1792
Encountered https://github.com/brave/brave-browser/issues/3590
