### ISSUE TITLE
App exits when accessing 'send to devices' in share menu

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-browser#34636]
## Description 
Crash when accessing 'send to your devices' in share menu

Reproducible on existing Profile & fresh Profile (with sync enabled)

## Steps to reproduce 

   1. Join sync chain with some devices
   2. Open any url
   3. Open hamburger menu -> share -> send to devices

## Actual result 
Crash / App exist

https://github.com/brave/brave-browser/assets/17885425/734ec011-2a1a-48a6-95c1-7c6113c318d9

## Expected result
App should not quit

## Issue reproduces how often 
Easily

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? No
- Can you reproduce this issue with the current Play Store Beta version? Yes
- Can you reproduce this issue with the current Play Store Nightly version? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): ARM + ARM Tablet. Samsung GS 21
   - Android version: 13, 14
   
## Brave version
`Brave	1.62.92 Chromium: 120.0.6099.35 (Official Build) beta (64-bit) `

**Comment by hffvld** [comment]
I checked with the latest `C119` build `1.62.85`  and the issue is not reproducible, then I checked with the first `C120` build `1.62.86` and observed the issue.

**Comment by kjozwiak** [comment]
The above will be uplifted into `1.61.x` via https://github.com/brave/brave-core/pull/21135 hence not adding the required version for verification on `1.62.x`. However, the above was verified on Nightly via https://github.com/brave/brave-core/pull/21168#issuecomment-1836835850 before uplifting.

**Comment by kjozwiak** [comment]
The above requires `1.61.94` or higher for `1.61.x` verification 👍
