### ISSUE TITLE
Uphold listed on brave://rewards/#verify in regions it should not be listed

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#34646]
## Description 

Starting with 1.62.x, Uphold is listed (as grayed out) as an option for custodial partner on the brave://rewards/#verify page in regions where it should not be, ex. India and Japan.

I am unsure if this is an issue on Android also, so it should be checked there also.

## Steps to Reproduce

   1. Be using 1.62.x or 1.63.x
   2. Join Rewards with India or Japan
   3. Go to connect a custodian

## Actual result:

1.62.x | 1.63.x
--- | ---
<img width="1191" alt="62 zeb" src="https://github.com/brave/brave-browser/assets/28145373/533c2728-eee3-49ec-845b-939752ca45be"> | <img width="1193" alt="63 zeb" src="https://github.com/brave/brave-browser/assets/28145373/83b531c7-a4e5-43a0-a222-f2e177f27f46">
<img width="1194" alt="62 j" src="https://github.com/brave/brave-browser/assets/28145373/143c9aa6-7651-4b71-b70e-d489dbc90926"> | <img width="1190" alt="63 j" src="https://github.com/brave/brave-browser/assets/28145373/cac252ab-6952-4e0d-90ab-9bdd88fd3252">

## Expected result:

Should be as it is in 1.61.x:

<img width="1194" alt="61 zeb" src="https://github.com/brave/brave-browser/assets/28145373/5b14c926-29f3-45e2-8bb3-a73d275effbc"> | <img width="1193" alt="61 j" src="https://github.com/brave/brave-browser/assets/28145373/d5c018bd-0783-4170-a3e7-ee574f8583c1">
-- | --

## Reproduces how often: 

easily

## Desktop Brave version:

Brave | 1.62.93 Chromium: 120.0.6099.35 (Official Build) beta (x86_64)
-- | --
Revision | 2032da61e85b8d826ab474ee36fee9a9cee09907
OS | macOS Version 13.6.1 (Build 22G313)

Brave | 1.63.1 Chromium: 120.0.6099.35 (Official Build) nightly (x86_64)
-- | --
Revision | 96919ee80aa1034307f2bde0963150c45193c99e
OS | macOS Version 13.6.1 (Build 22G313)

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 1.60.x no, 1.61.x (RC) no
- Can you reproduce this issue with the beta channel? 1.62.x yes
- Can you reproduce this issue with the nightly channel? 1.63.x yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @Miyayes @brave/qa-team

**Comment by kjozwiak** [comment]
The above requires `1.62.101` or higher for `1.62.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification INPROGRESS on `Samsung galaxy version 12` running `Bravemonoarm64.apk_1.62.105`
