### ISSUE TITLE
Why Brave don't have some Brave account login to synchronize all my data?

### ISSUE THREAD

**Issue by LeandroVCastro** [brave/brave-browser#34642]
## Description 

Hello.
I just love using Brave. But I miss something very important to me: Login on Brave account.
When I'm using Chrome, I can login on my Google Account and all my history and favorites and etc will be saved.
And when I need change my Desktop or smartphone I just need login on my Google Account on this new device and voila! All my data is here.

Why Brave don't have some feature like that?
Or maybe it have but I don't know.

Any plans to implements something on this way?

## Steps to Reproduce

There's no.

## Actual result:

 There's no.

## Expected result:
There's no.

## Reproduces how often: 

There's no.

## Desktop Brave version:

All

**Comment by jonathan-nielsen** [comment]
[Here's an article](https://support.brave.com/hc/en-us/articles/360021218111-How-do-I-set-up-Sync-) of how to synchronize all your existing and new devices. Essentially you get a code which you share amongst all your devices to keep them up to date.

**Comment by LeandroVCastro** [comment]
> [Here's an article](https://support.brave.com/hc/en-us/articles/360021218111-How-do-I-set-up-Sync-) of how to synchronize all your existing and new devices. Essentially you get a code which you share amongst all your devices to keep them up to date.

Nice. Thank you for sharing.
Is this like a seed on Bitcoin Wallet, right?
I liked.
