### ISSUE TITLE
Active sidebar item is visible even if it's scrolled to invisible area

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#34657]
## Description 

Maybe ink drop layer is visible even that view is hidden.
![image](https://github.com/brave/brave-browser/assets/6786187/97873f46-e447-4cdf-ae00-4aa5ee5a7017)

## Steps to Reproduce

   1. Open playlist item and close it
   2. Add many sidebar items to make sidebar items scrollable
   3. Open playlist item again via shortcut such as ctrl + b
   4. 

## Actual result:

playlist item is visible like above

## Expected result:
It should be hidden

## Reproduces how often: 

Yes

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
@simonhong Linux only?

**Comment by simonhong** [comment]
> @simonhong Linux only?

Reproduced on all desktops.

**Comment by simonhong** [comment]
@sangwoo108 Do you have any ideas to prevent this Or we shouldn't use inkdrop's highlight for activated item?

**Comment by sangwoo108** [comment]
Well, Off the top of my head
* Set clip path to the parent view or make mask layer
* Hide items on layout when items are out of bounds

**Comment by sangwoo108** [comment]
Ah, sidebar is already using scroll view, isn't it? Then I think we should hide the item view when it's scrolled. I think there's on scrolled callback in ScrollView

**Comment by simonhong** [comment]
Oh, thanks for the advice. Calling below in parent view seems fixed this issue!
```
  layer()->SetMasksToBounds(true);
  layer()->SetFillsBoundsOpaquely(false);
```

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.63.25 Chromium: 120.0.6099.71 (Official Build) nightly (x86_64)
-- | --
Revision | 93d23f5c19a6cf149d04ab7aef4c02b1b4f23e1f
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.63.25`
2. launched Brave
3. enabled `Playlist` via its `brave://flags` entry
4. restarted Brave
5. loaded a bunch of websites and added them to the sidebar (enough to cause vertical scroll)
6. loaded an awesome progressive-house set: https://www.youtube.com/watch?v=4QKrt5tkclU
7. clicked `Play`
8. clicked `Add to Playlist` 
9. confirmed `Playlist` controls w/media opened
10. closed the `Playlist` panel
11. scrolled the sidebar's contents so the `Playlist` icon is out of view
12. pressed `command` + `b` to open `Playlist` in the sidebar

### Confirmed correct placement and rendering of the `Playlist` icon, relative to scroll position

example | example | example | example | example
---------|----------|---------|----------|--------
<img width="1516" alt="Screen Shot 2023-12-07 at 4 38 21 PM" src="https://github.com/brave/brave-browser/assets/387249/65d2afb5-8552-4f76-a0c3-727b414b15fc"> | <img width="1516" alt="Screen Shot 2023-12-07 at 4 38 25 PM" src="https://github.com/brave/brave-browser/assets/387249/9d8916f3-49eb-4b44-b22e-aa244a890f5d"> | <img width="1516" alt="Screen Shot 2023-12-07 at 4 38 29 PM" src="https://github.com/brave/brave-browser/assets/387249/391e93fe-6727-415e-9766-1f6a73a190cb"> | <img width="1516" alt="Screen Shot 2023-12-07 at 4 38 33 PM" src="https://github.com/brave/brave-browser/assets/387249/486bfe44-7c5c-4e63-8b6c-f317f56b588e"> | <img width="1516" alt="Screen Shot 2023-12-07 at 4 38 37 PM" src="https://github.com/brave/brave-browser/assets/387249/5bd6b8a9-2102-4402-9fb3-0f16f26e13c8">
