### ISSUE TITLE
This version of the Chrome Web Store will be discontinued in January.

### ISSUE THREAD

**Issue by solrevdev** [brave/brave-browser#34659]
## Description 
Visiting the [chrome store](https://chrome.google.com/webstore/detail/nighthawk-by-phishfort/bdiohckpogchppdldbckcdjlklanhkfc) to download an extension for Brave Browser I get a warning that 

"This version of the Chrome Web Store will be discontinued in January."

Doing a bit of research on twitter suggests this is being shown to non chrome browsers for example "Like Opera etc" 

https://twitter.com/BrendanOConnel/status/1729938704792166466 

## Steps to Reproduce

   1. Visit https://chrome.google.com/webstore/detail/nighthawk-by-phishfort/bdiohckpogchppdldbckcdjlklanhkfc
   2. See message
 

## Actual result:

![Screenshot 2023-12-01 at 13 30 43](https://github.com/brave/brave-browser/assets/374863/9903d586-c2d8-44f2-b5af-2fddf1d819c7)

## Expected result:

Is this something to be concerned about?

## Brave version (brave://version info)

```
Brave	1.60.125 Chromium: 119.0.6045.199 (Official Build) (arm64) 
Revision	9c1f9e267d7ef50aefbe434e616e05290536926b
OS	macOS Version 14.1.2 (Build 23B92)
JavaScript	V8 11.9.169.7
User agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
```

**Comment by rebron** [comment]
@solrevdev I believe they're just updating their website. You should still be able to `Add to Brave` like below

<img width="1195" alt="Screenshot 2023-12-01 at 2 12 43 PM" src="https://github.com/brave/brave-browser/assets/5951041/6a6c0056-b2ba-4daf-b9e5-fae6d5ba578b">

I'm going to go ahead and close this off but if this does become a problem in the future we'll file a new issue.

**Comment by solrevdev** [comment]
@rebron Cool thanks for taking a look.🙏

**Comment by ElijahLynn** [comment]
Thanks for explaining this! This was the second Google result for "This version of the Chrome Web Store will be discontinued in January.". 

For those who arrive here, probably clicked the link from Brave like I did to get to the store. And the the gist of it is that it is that https://chrome.google.com/ (the one with the warning) is moving to https://chromewebstore.google.com/. It would be good to link a PR with this link change in Brave to this issue.
