### ISSUE TITLE
Some web pages are no longer displayed.

### ISSUE THREAD

**Issue by Johann999** [brave/brave-browser#34656]
Since the update to Brave Ver. 1.60.125 some web pages are not displayed or displayed incorrectly.
![Fehler 20min](https://github.com/brave/brave-browser/assets/53431361/ba680a38-9c7e-461d-936e-6ce401c635c6)

Brave	1.60.125 Chromium: 119.0.6045.199 (Offizieller Build) (32-Bit) 
Überarbeitung	9c1f9e267d7ef50aefbe434e616e05290536926b
Betriebssystem	Windows 10 Version 1909 (Build 18363.592)

**Comment by Johann999** [comment]
This page is displayed correctly.
The problem was that cookies for 20min.ch were blocked.
This showed this error message, but only on pages with videos.

**Comment by ryanbr** [comment]
Safe to close ticket I take it? We shouldn't be blocking cookies from the site by default

**Comment by ryanbr** [comment]
Closing, if its still causing issues. reopen ticket
