### ISSUE TITLE
Chore: cleanup transaction endpoints

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#34651]
## Description 

Move transaction endpoints out of `api.slice.ts` and into it's own endpoints file. Refactor logic to not dispatch queries from inside other queries.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.63.155 Chromium: 122.0.6261.29 (Official Build) (64-bit)
-- | --
Revision | b2be2c6f5b7340629f672ce706f5bfd62b113f82
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from [brave/brave-core#21170](https://github.com/brave/brave-core/pull/21170)
- Verified transactions continue to work as expected for all networks
- Verified send screen continue to work without regressions
- Verified swap screen continue to work without regressions
- Verified transaction activity screen continue to work without regressions
