### ISSUE TITLE
Properly recognize Linux for allowlisting fonts

### ISSUE THREAD

**Issue by arthuredelstein** [brave/brave-browser#34653]
## Description 

We recently introduced font whitelists for three flavors of Linux in https://github.com/brave/brave-browser/issues/34169. However, the `base::GetLinuxDistro` call appears to fail to recognize the Linux distro unless it is called very early. We need to call it earlier for the font restriction to work.

**Comment by btlechowski** [comment]
Verified with

Brave | 1.63.72 Chromium: 120.0.6099.144 (Official Build) nightly (64-bit)
-- | --
Revision | 6b596bddc3f41510050fe7486f3bbe86cf48a7f2
OS | Ubuntu 22.04.03 LTS


Verified test plan from: https://github.com/brave/brave-browser/issues/34169#issuecomment-1847992427


Without the Pacifico font:
![image](https://github.com/brave/brave-browser/assets/34715963/c8b45745-2b66-40da-9a7d-1425eb7aa96e)


Installed Pacifico font base on https://linuxhint.com/manually-install-fonts-ubuntu-22-04/
![image](https://github.com/brave/brave-browser/assets/34715963/0adcbf72-4120-4b9d-9ece-f7b206c691c7)

With Pacifico font and Shields enabled:
![image](https://github.com/brave/brave-browser/assets/34715963/51735c4e-410e-42f5-a03f-7e55c37c5e0c)

With Pacifico font and Shields disabled:
![image](https://github.com/brave/brave-browser/assets/34715963/25c1043e-424c-4d35-8534-281d612456f5)

With Pacifico font and Shields re-enabled:
![image](https://github.com/brave/brave-browser/assets/34715963/07f0750e-9217-40b8-b13e-37c8d6b28877)
