### ISSUE TITLE
Remove brave://settings/rewards and move `Show Rewards button` to Appearance 

### ISSUE THREAD

**Issue by rebron** [brave/brave-browser#34667]
## Description 

All of Brave Rewards settings can be accomplished in brave://rewards 

Remove brave://settings/rewards and place `Show Brave Rewards button` setting in brave://settings/appearance. 
Also, move `Show Sidebar button` to be directly below `Show Brave Rewards button` so the ordering in settings appear top to bottom as the toolbar buttons are ordered left to right.
Remove `Brave Rewards` from brave://settings left column navigation.

See screenshot in Expected Result or Figma file. https://www.figma.com/file/tLXWGCpNoiJxDZDdpfordj/%5BARCHIVE%5D-Desktop-Settings?type=design&node-id=4243%3A41392&mode=design&t=Q3urBeUayOxlrNdo-1

## Actual result:

![screenshot_2023-11-29_at_10 25 31___am](https://github.com/brave/brave-browser/assets/5951041/cca4c3ad-cca7-4a77-a23c-4cff31a00660)

## Expected result:
<img width="984" alt="Screenshot 2023-12-01 at 11 01 31 AM" src="https://github.com/brave/brave-browser/assets/5951041/674ded7d-c4c2-4e06-b500-deb903b232d3">

## Reproduces how often: 

Easily.

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? n/a 
- Does the issue resolve itself when disabling Brave Rewards? n/a
- Is the issue reproducible on the latest version of Chrome? n/a

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.63.137 Chromium: 121.0.6167.85 (Official Build) beta (x86_64)
-- | --
Revision | a6b00decf1359e10a0937fdb75983baaf1eb100b
OS | macOS Version 13.6.4 (Build 22G513)
```
