### ISSUE TITLE
ability to "scroll to top" of page for brave://skus-internals/

### ISSUE THREAD

**Issue by iambrianfung** [brave/brave-browser#34664]
## Description 

It is difficult for users to easily return to the top of the brave://skus-internals page if they have scrolled deep into the JSON.
Have a button to help users return to the top of the page easily

## Steps to Reproduce

   1.  visit brave://skus-internals/
   2. Click `Fetch SKUs State`
   3. scroll deep into the page
   4. try to get back to the top of the page easily

## Actual result:
must scroll or drag scrollbar

## Expected result:
button to jump to top of the page for easier access

## Reproduces how often: 
Easily reproducible

## Brave version (brave://version info)
1.60.118 Chromium: 119.0.6045.163 (Official Build) (arm64) 

cc: @aguscruiz @rebron

**Comment by bsclifton** [comment]
There's always the <kbd>Home</kbd> key 🙂 That should bring you back to the top on all platforms

**Comment by iambrianfung** [comment]
ah, thanks @bsclifton 
`fn` + `left arrow` is the equivalent on macos.
