### ISSUE TITLE
Make Youtube to work with Leo for transcripts

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#34666]
We should re-use desktop's functionality for that

**Comment by petemill** [comment]
It should already be using desktop functionality for Youtube, there is no platform conditional code for this as far as I'm aware

**Comment by mattmcalister** [comment]
Hoping Leo with Youtube on Android gets resolved by https://github.com/brave/brave-browser/issues/34945

**Comment by petemill** [comment]
Closing as duplicate of https://github.com/brave/brave-browser/issues/34945
