### ISSUE TITLE
Sign Transaction Panel is being persisted breaking the UI

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#34668]
## Description 

The `Sign Transaction` panel is being persisted which breaks the UI after it is reopened since `Sign Transaction` will return `undefined`

## Steps to Reproduce

   1. Go to https://pwgoom.csb.app/ and create a `Sign Transaction` request
   2. After the `Panel` displays the the `Message` request, click `Cancel`
   3. Reopen the `Panel`, it will be broken and the `Sign Transaction` panel will be persisted.

## Actual result:

https://github.com/brave/brave-browser/assets/40611140/3a9d538d-e445-4f47-be64-93b1328e629f

## Expected result:
Should not persist the `Sign Transaction` panel if it was `Signed` or `Rejected`

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by kjozwiak** [comment]
The above requires `1.61.97` or higher for `1.61.x` verification 👍
