### ISSUE TITLE
Combine transaction confirmation panel components

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#34661]
## Description 

Combine transaction confirmation panel components to help prevent regressions between panels when editing styles

**Comment by kjozwiak** [comment]
The above requires `1.62.148` or higher for `1.62.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.62.149 Chromium: 121.0.6167.75 (Official Build) (64-bit)
-- | --
Revision | ff84587bd70af9fcbcbe59fc5194ca65082759c4
OS | Windows 11 Version 23H2 (Build 22631.3007)

- Verified steps from [brave/brave-core#21188](https://github.com/brave/brave-core/pull/21188)
- Verified transaction confirmation panel continue to show all transaction information for all transaction types without any regression
