### ISSUE TITLE
Auto-contribution list disappears showing only one entry at 100%

### ISSUE THREAD

**Issue by da2x** [brave/brave-browser#3466]
## Suspected Steps to Reproduce
(May not be exact but this is the rough outline of what I’ve been doing every time this has happen.)

1. Open the Rewards settings page in a tab
2. Open any website not on the auto-contribute list (e.g. cnn.com) in a new tab and wait 10 seconds
3. Close that tab and be returned to the Rewards settings tab
4. Click “See all sites”

## Actual result:
The entire auto-contribute list disappears and is replaced by a single entry for cnn.com. cnn.com is given 100% attention. Visiting other websites won’t be recorded and cnn.com will stay on the list at 100%.

## Work-around:
Click the X next to cnn.com to restore the old list. Restarting won’t fix the problem. Other websites visited while cnn.com was the only entry also appear on the list.

Clicking X may shows a “Your scheduled monthly payment for Auto-Contribute and monthly tips could not be completed due to insufficient funds. We’ll try again in 30 days.” notice. HOWEVER, the next contribution date was shown as 2019-03-05 before this happen (and I believe this is the date that has been shown for at least a week) and the date remains unchanged after this happen.

## Expected result:
Utter perfection.

## Reproduces how often: 
It has happen at least every two weeks or so and have been observed on macOS, Linux, and Windows.

## Brave version (brave://version info)
Version 0.60.45 Chromium: 72.0.3626.109 (Official Build) (64-bit)

### Reproducible on current release:
Yes.

## Additional details:
This may be a variation of #3393?

**Comment by NejcZdovc** [comment]
@brave/legacy_qa did we see anything like this?

**Comment by LaurenWags** [comment]
I have not experienced this, @btlechowski or @GeetaSarvadnya - have either of you seen anything like this?

**Comment by Miyayes** [comment]
Reopen if we observe this again.
