### ISSUE TITLE
Incorrect custodian listed in updated "Logged out" notice text - follow up to #33583

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#34670]
## Description 

Wrong custodian listed in the updated text implemented with https://github.com/brave/brave-browser/issues/33583.

Reproduces with Gemini or ZebPay as custodian but currently unable to check bitFlyer.

## Steps to Reproduce

   1. Clean profile 1.62.x
   2. Close and relaunch to pull griffin
   3. Join Rewards (staging env)
   4. Connect Gemini as custodian
   5. Navigate to Gemini site, revoke authorization
   6. Wait for the disconnected state to be reflected on the panel by way of the notification dot (manually navigating to brave://rewards in a new tab speeds this up)
   7. Open the panel
   8. See "Uphold" listed in the notice text but custodian is Gemini.

## Actual result:

<img width="1337" alt="2" src="https://github.com/brave/brave-browser/assets/28145373/90c12d5d-be14-4b0c-bbde-d4059be952ee">

## Expected result:

Should say "Gemini" instead of "Uphold" in the above

## Reproduces how often: 

easily

## Brave version (brave://version info)

```
Brave | 1.62.93 Chromium: 120.0.6099.35 (Official Build) beta (x86_64)
-- | --
Revision | 2032da61e85b8d826ab474ee36fee9a9cee09907
OS | macOS Version 13.6.1 (Build 22G313)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? 1.62.x yes
- Can you reproduce this issue with the nightly channel? unsure but likely

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @Miyayes

**Comment by kjozwiak** [comment]
The above requires `1.62.101` or higher for `1.62.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.62.104 Chromium: 120.0.6099.71 (Official Build) beta (x86_64)
-- | --
Revision | e2b266991247b909fa88520bb12d018223872d29
OS | macOS Version 13.6.1 (Build 22G313)
```
