### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by brian-smith-0** [brave/brave-browser#34677]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.60.118 Chromium: 119.0.6045.163
Operating System: Mac OS X 14.1.1

URL (if applicable) where crash occurred: https://twitter.com/

Can you reproduce this crash? Yes

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Brave crashes almost every time I scroll past the first 10-20 tweets on my twitter timeline. Happens occasionally on non-twitter sites but guaranteed on twitter. Just reproduced two in a row with only 15 tweets. It's extremely annoying since now I can't use twitter on desktop. Will have to ditch Brave if it isn't resolved in the next week or two.

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/59530800-8698-1d0b-0000-000000000000

**Comment by brian-smith-0** [comment]
This shows the frequency of crashes even when I'm intentionally not using much twitter on desktop. One out of every 5 or so is caused by browsing non-twitter sites.
<img width="493" alt="image" src="https://github.com/brave/brave-browser/assets/92126383/4be447cd-6f89-4165-a0b3-640ed32a464d">

**Comment by rebron** [comment]
@brian-smith-0 Can you update to our latest 1.61.100 and let us know if you're still experiencing this crash.

**Comment by bsclifton** [comment]
Unfortunately, I can't find any crash IDs in our system with those IDs. Usually, some part of the crash (ex: signature) is stored, but it doesn't look like this has occurred and may have been purged. Closing as stale
