### ISSUE TITLE
Limit max attention given to one creator/website to 15%

### ISSUE THREAD

**Issue by da2x** [brave/brave-browser#3467]
## Description 
I often find myself excluding websites that I actually like a lot from the auto-contribution list because they get all the attention and I don’t want all my contributions to go to only one creator/publisher.

## Steps to Reproduce

   1. Set duckduckgo.com as your default search engine
   2. Do some research and read a lot of Wikipedia
   3. Review your auto-contribution list

## Actual result:
My entire monthly contribution is awarded to one or two website/creators (DuckDuckGo and Wikipedia)  that I use all the time. While I may like these creator/websites, I don’t want them to receive all of my monthly contributions.

## Expected result:
There should be a upper limit on how large a percentage of the monthly contribution can go to any one creator/website. I’d be happy with a default limit at 15 % but it maybe should be configurable (up to 50 %.)

I believe this would be **healthier for the Brave and web ecosystems** if funds are spread around a bit instead of ending up in the hands of just a few attention-grabbing creator/websites. (Even attention-grabbing creator/websites that you really appreciate.) This might even make Brave less of an attractive target for automates scams and abuse schemes as it could help reduce the amount of money one entity could hope to get per compromised Brave installation.

## Reproduces how often: 
Every time.

## Brave version (brave://version info)
Version 0.60.45 Chromium: 72.0.3626.109 (Official Build) (64-bit)

### Reproducible on current release:
Yes.

**Comment by btlechowski** [comment]
This use case is mostly covered by Monthly recurring tips. You setup how much you would like to give to a creator each month.
