### ISSUE TITLE
Ad Ads info to settings box

### ISSUE THREAD

**Issue by ryanml** [brave/brave-browser#3468]
Tracker: https://github.com/brave/brave-browser/issues/3141

We are only going to be showing the estimated earnings and the notifications received data points. The monthly payment date is hard coded for now per @jsecretan 

![46828601-6af02180-cd50-11e8-98dc-1b709a4a2460](https://user-images.githubusercontent.com/8732757/53285248-be6d7580-371b-11e9-96b6-4e40eefd009f.png)

**Comment by mandar-brave** [comment]
@jsecretan and @ryanml to simplify -

a) all stats including estimated earnings reset as month changes (local TZ midnight reset)
b) payment days stays static - i think it is the 8th (in sync with the pub date)

**Comment by mandar-brave** [comment]
On review - the assumption for the original requirements was that we ask user to claim rewards as the month changes; here are the new requirements ---- when the month changes.

a) keep the estimated rewards to keep collecting 
c) only when the rewards claim is made and rewards are captured, the estimated rewards resets with the next payment

**Comment by NejcZdovc** [comment]
@tmancey @ryanml please check if this is implemented

**Comment by jsecretan** [comment]
Let's hold off on these changes for right now, get this merged in and make another story after some additional discussion.

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 0.63.44 Chromium: 74.0.3729.75 (Official Build) beta(64-bit)
-- | --
Revision | fdb7915642fef8cf997beac2554709d148e3c187-refs/branch-heads/3729@{#754}
OS | Mac OS X

* Verified test plan and screenshot from https://github.com/brave/brave-core/pull/1768
![Screen Shot 2019-04-17 at 4 09 00 PM](https://user-images.githubusercontent.com/28145373/56318154-92271180-612c-11e9-97d3-3b3c2b67abeb.png)
![Screen Shot 2019-04-17 at 4 18 19 PM](https://user-images.githubusercontent.com/28145373/56318158-94896b80-612c-11e9-8faa-ed2b5ced873a.png)
