### ISSUE TITLE
Deprecate uncached wallet Fiat currency lookup

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#34686]
## Description 

Deprecate uncached wallet Fiat currency lookup

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.63.155 Chromium: 122.0.6261.29 (Official Build) (64-bit)
-- | --
Revision | b2be2c6f5b7340629f672ce706f5bfd62b113f82
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from [brave/brave-core#21210](https://github.com/brave/brave-core/pull/21210)
- Verified Fiat balance correctly shows up in the following area
   - Swap screen and quote 
   - Portfolio accounts list
   - "Hide small balances" portfolio filter
   - Portfolio account details page
   - "Market" tab
   - Account transactions
   - Portfolio overview chart
   - Confirm transaction panel
   - Approve ERC20 panel
   - "Fund Wallet" page
   - "Send" screen (and token selection)
