### ISSUE TITLE
Move account management handlers to mutations

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#34694]
## Description 

Move account management handlers to mutations

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.63.146 Chromium: 121.0.6167.139 (Official Build) beta (64-bit)
-- | --
Revision | cb9ee9c98182a64716e4237bf1202f1aec3bcff8
OS | Windows 11 Version 23H2 (Build 22631.3007)

- Verified steps from [brave/brave-core#21214](https://github.com/brave/brave-core/pull/21214)
- Verified adding, renaming, and importing accounts work as expected without any regression
