### ISSUE TITLE
[ads] Send placement id in payload when redeeming a confirmation token

### ISSUE THREAD

**Issue by tmancey** [brave/brave-browser#34697]

**Comment by ShivanKaul** [comment]
(Talked to Terry about this over DM, he'll raise a review for this once it's ready to be worked on)

**Comment by tmancey** [comment]
Blocking while discussing a/b testing as that would resolve this issue.

**Comment by tmancey** [comment]
Closing issue as no longer required once https://github.com/brave/reviews/issues/1507 has been approved
