### ISSUE TITLE
Cache default wallet lookups

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#34699]
## Description 

Cache results for default Ethereum and Solana Wallets. Also cache results for MetaMask installation check

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.63.146 Chromium: 121.0.6167.139 (Official Build) beta (64-bit)
-- | --
Revision | cb9ee9c98182a64716e4237bf1202f1aec3bcff8
OS | Windows 11 Version 23H2 (Build 22631.3007)

- Verified steps from [brave/brave-core#21222](https://github.com/brave/brave-core/pull/21222)
- Verified warning banner on portfolio overview screen appears when Web3 setting is change to `Prefer extensions` for both Metamask and Phantom extensions

https://github.com/brave/brave-browser/assets/17010094/98463549-8119-4821-9707-8d70b94c72ae
