### ISSUE TITLE
totally blank window

### ISSUE THREAD

**Issue by tortino** [brave/brave-browser#3469]
## Steps to Reproduce

   1. hardware tested: hp dv6-3145sl
   2. https://icecat.biz/p/hp/xz440ea/notebook-portatili-dv6-3145sl-6997021.html
   3. just run brave

## Actual result:

totally blank user interface. only visible is popup menu (when right clicking)
all other browsers are working correctly (chrome, opera, firefox)

## Expected result:
I want to see the user interface :-)

## Reproduces how often: 

always on this hardware (on pther pc is working correctly)

## Brave version (brave://version info)

Brave | 0.60.45 Chromium: 72.0.3626.109 (Official Build) (64-bit)
-- | --
Revision | fae8db7ab9280fa6704a59980263c804f809ebd5-refs/branch-heads/3626@{#857}
OS | Windows

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
not tried

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? not tested
- Is the issue reproducible on the latest version of Chrome?  NO

**Comment by Brave-Matt** [comment]
Windows 7 or windows 10?

**Comment by tortino** [comment]
Hi, it's windows 10.

**Comment by Brave-Matt** [comment]
Can you share a screen shot of what you see? I've only seen what this [sounds like] in Win 7. Solution is to launch using `--disable-gpu` flag as seen in the solution here:
https://community.brave.com/t/error-on-yesterdays-update/39287

**Comment by tortino** [comment]
yes, using --disable-gpu works correctly! thanks.
however I think you should blacklist my drivers/hardware combo and disable gpu automatically.
