### ISSUE TITLE
Main menu shows "Enter reader mode" button text [Nightly]

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#34707]
## Description 

In the Nightly build (v1.63.12), the main menu shows text for an `Enter reader mode` button (apparently) that shouldn't be appearing there, nor does it serve any function:

![image](https://github.com/brave/brave-browser/assets/3299098/5deeedb4-c570-44d7-af43-b551ba8d97f2)

cc @rebron

**Comment by rebron** [comment]
cc: @boocmp @simonhong

**Comment by kjozwiak** [comment]
The above requires `1.62.101` or higher for `1.62.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.62.101 Chromium: 120.0.6099.71 (Official Build) beta (x86_64)
-- | --
Revision | 754b62f4b0a8a9c4e281d2f11a1f4269432edf30
OS | macOS Version 14.2 (Build 23C64)
```

`before` | `post-fix`
---------|----------
<img width="1216" alt="Screenshot 2023-12-09 at 2 34 17 AM" src="https://github.com/brave/brave-browser/assets/387249/51d4a03e-98c7-4ed5-b92d-51321a601075"> | <img width="1627" alt="Screenshot 2023-12-09 at 2 36 29 AM" src="https://github.com/brave/brave-browser/assets/387249/c7cc7b96-7d29-4c80-aaaa-26dd3e5ddd64">
