### ISSUE TITLE
Update SNS interstitial page copy for new provider

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-browser#34700]
## Description 

Update the copy for the SNS interstitial page for change of provider.

More info:

https://github.com/brave/devops/issues/10126#issuecomment-1830367288

https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1701455844311989

**Comment by kjozwiak** [comment]
The above requires `1.62.115` or higher for `1.62.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Pixel 7` using version(s):
```
Device/OS: Pixel 7 / panther_beta-user 14 AP11.231020.013.A1 release-keys
Brave build: 1.62.128
Chromium: 120.0.6099.144 (Official Build) beta (64-bit) 
```
---------------------------

**STEPS:**
1. Launch Brave
2. Go to `https://onybose.sol/` > Verify
3. Tap `help page` URL > Verify
4. Go back to `https://onybose.sol/` > Tap `Disable` > Verify
5. Three-dot menu > Settings > Brave Shields & privacy > Solana Name Service > Verify
6. Change to `Ask` > Go back and reload the page > Verify
7. Tap `Proceed using an SNS server` > Verify
8. Go to Settings > Brave Shields & privacy > Solana Name Service > Verify

**ACTUAL RESULTS:**
- Verified that visiting https://onybose.sol/ loads the correct interstitial page mentioned via https://github.com/brave/brave-core/pull/21353#issue-2038723510
- Verified that tapping on the `help page` opens https://github.com/brave/brave-browser/wiki/Resolve-Methods-for-Solana-Name-Service
- Verified that tapping on `Disable` loads the `This site can’t be reached` page
- Verified that `Resolve Method` in `Solana Name Service` (SNS) is set as `Disabled`
- Verified that changing SNS `Resolve Method` to `Ask` loads the correct interstitial page
- Verified that tapping on `Proceed using an SNS server` correctly resolves https://anirudha.co/ without any issues
- Verified that `Resolve Method` in `Solana Name Service` (SNS) is set as `Enabled`

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/395a6e6b-d9b0-43aa-9d62-c792bd921959) | ![2](https://github.com/brave/brave-browser/assets/128532965/58a9d2ce-2fe5-4c47-925f-d9ae2cc0ac41) | ![3](https://github.com/brave/brave-browser/assets/128532965/12328d7f-aa27-47ea-8b67-d1ca1d0d0065) | ![4](https://github.com/brave/brave-browser/assets/128532965/88118ed9-2b4a-475a-89df-2ee3f9ebb0b4) |
| ![1](https://github.com/brave/brave-browser/assets/128532965/026ba641-f723-4f4f-bce0-e23189f04fc3) | ![2](https://github.com/brave/brave-browser/assets/128532965/f199538b-b7e7-4c99-8cb4-f2b70e5af906) | ![3](https://github.com/brave/brave-browser/assets/128532965/dcf76efd-62d6-48b9-b55d-b34c65b2ce51) | ![4](https://github.com/brave/brave-browser/assets/128532965/e00a2ef6-aca6-4273-83a3-d9745c3f8037) |

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.62.149 Chromium: 121.0.6167.75 (Official Build) (64-bit)
-- | --
Revision | ff84587bd70af9fcbcbe59fc5194ca65082759c4
OS | Windows 11 Version 23H2 (Build 22631.3007)

- Verified steps from [brave/brave-core#21353](https://github.com/brave/brave-core/pull/21353)
- Verified on upgrade from 1.61.x SNS interstitial page shows new provider name 
- Verified selecting `Disable` on the interstitial page sets the setting to disable
- Verified selecting `Proceed using SNS Server` loads the URL correctly and sets the setting to `Enabled`
- Verified the new interstitial page doesn't have any mention of `Syndica` in the message or on the button

https://github.com/brave/brave-browser/assets/17010094/bd8e8400-1dea-458a-a084-d9016cd62ea9
