### ISSUE TITLE
Find in page bubble is hidden when speedreader is used

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#34708]
## Description 

![image](https://github.com/brave/brave-browser/assets/6786187/e3a5efb3-f972-49aa-9209-1dd1da315481)

## Steps to Reproduce

   1. Load https://www.wired.com/story/alternative-browsers-built-in-ai-arc-sigmaos-brave-opera/ with speedreader
   2. `ctrl + f` to launch find in page bubble
   3. 

## Actual result:

Find in page bubble is behind the speedreader

## Expected result:
speedreader toolbar should be behind the find in page bubble

## Reproduces how often: 

Easy

## Version/Channel Information:

- Can you reproduce this issue with the current release? No (1.60.x)
- Can you reproduce this issue with the beta channel? Yes (1.62.x)
- Can you reproduce this issue with the nightly channel? Yes (1.63.x)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

It's not reproducible on macOS
cc @rebron @kjozwiak

**Comment by kjozwiak** [comment]
The above requires `1.61.98` or higher for `1.61.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on

```
Brave | 1.61.98 Chromium: 120.0.6099.62 (Official Build) (64-bit)
-- | --
Revision | 3c3d173dc7609eee669907c7fca0ede8c64611be
OS | Windows 10 Version 22H2 (Build 19045.3693)
```

![image](https://github.com/brave/brave-browser/assets/38657976/2b210035-21ff-4c74-bf23-a5674f2d42d9)

**Comment by btlechowski** [comment]
Verified with

Brave | 1.61.98 Chromium: 120.0.6099.62 (Official Build) (64-bit)
-- | --
Revision | 3c3d173dc7609eee669907c7fca0ede8c64611be
OS | Linux

Verified test plan from the description

![image](https://github.com/brave/brave-browser/assets/34715963/400869b1-fec9-4eea-b3d7-e65e07491806)
