### ISSUE TITLE
Change premium indicator for new Claude

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#34718]
See Figma for the latest iteration of this:

https://www.figma.com/file/m0Gdbf0wtqyfEFGm32VLLc/Leo?type=design&node-id=964%3A66122&mode=design&t=3Q3VSkQeOaXVsDzb-1

<img width="843" alt="Screenshot 2023-12-05 at 4 09 14 PM" src="https://github.com/brave/brave-browser/assets/831718/3602db12-3eb9-43c5-8b43-4c7d4adb1ac5">

cc @petemill @nullhook

**Comment by kjozwiak** [comment]
The above requires `1.62.147` or higher for `1.62.x` verification 👍

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

```
Brave | 1.62.149 Chromium: 121.0.6167.75 (Official Build) (x86_64)
-- | --
Revision | ff84587bd70af9fcbcbe59fc5194ca65082759c4
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.62.149`
2. launched Brave using `--env-leo=staging --env-ai-chat.bsg=dev --env-ai-chat-premium.bsg=dev`
3. purchased and loaded `Leo Premium` credentials from `account.bravesoftware.com` using `jan22@mailinator.com`
4. clicked on `Leo` in the sidebar
5. typed `test`
6. clicked on `Accept and begin`
7. clicked on the `...` menu
8. confirmed `Unlimited` badge for `Premium`-enabled models
9. shut down
10. relaunched without command line (so `Premium` credentials won't be detected`)
11. clicked on the `...` menu in `Leo`

### Confirmed `Limited` badge while in default/non-`Premium` mode; confirmed `Unlimited` whilst `Premium`-enabled

## `Light` mode

Basic/`Limited` | `Premium`/`Unlimited`
----------------|-----------------------
<img width="323" alt="Screen Shot 2024-01-22 at 11 57 23 AM" src="https://github.com/brave/brave-browser/assets/387249/bb643d0c-19b1-4e95-83e5-1f43a8c9024f"> | <img width="323" alt="Screen Shot 2024-01-22 at 12 00 50 PM" src="https://github.com/brave/brave-browser/assets/387249/55cee11e-2d05-42f8-8313-a22e0bd7d2c0">

## `Dark` mode
Basic/`Limited` | `Premium`/`Unlimited`
----------------|-----------------------
