### ISSUE TITLE
Implement countUp animation on Rewards panel and brave://rewards page 

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-browser#34715]
```[tasklist]
### Tasks
- [ ] Rewards balance and estimated earnings on brave://rewards page
- [ ] Rewards balance and estimated earnings on Rewards panel
```
Do not show animation in any case if the value in question is 0.00. 

See counter animation here: https://www.youtube.com/watch?v=kqgg5ZQ9mig

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave	1.65.88 Chromium: 123.0.6312.58 (Official Build) beta (x86_64) 
Revision	e260e641e7db9e88b9b51112f4f00febf5a2f5eb
OS	macOS Version 13.6.4 (Build 22G513)
```

**Comment by MadhaviSeelam** [comment]
Verification `In progress` using
```
Brave | 1.65.93 Chromium: 123.0.6312.58 (Official Build) beta (64-bit)
-- | --
Revision | a6eee503125f9441360861f96cfdcccf43b6fee0
OS | Windows 11 Version 23H2 (Build 22631.3296)
```

Confirmed "count up" animation on brave://rewards and panel for various custodians.

<details>
<summary>Uphold - PASSED</summary>

https://github.com/brave/brave-browser/assets/98358127/b8a80d08-07b2-41ab-b138-1d6682247811
</details>

<details>
<summary>Gemini - PASSED</summary>

https://github.com/brave/brave-browser/assets/98358127/e6c2825a-2ffc-437d-a698-665e9fc90ec4
</details>

<details>
<summary>ZebPay - PASSED</summary>

https://github.com/brave/brave-browser/assets/98358127/f7b212c1-d165-4ae3-83ff-ede3ce72a308
</details>

<details>
<summary>bitFlyer - PASSED</summary>

https://github.com/brave/brave-browser/assets/98358127/d4e08736-d16c-452d-b03c-b4570509b8db

</details>

<details>
<summary>Self Custody - Pending</summary>

</details>
