### ISSUE TITLE
Remove YouTube's `si` URL parameter from URLs

### ISSUE THREAD

**Issue by fmarier** [brave/brave-browser#34719]
https://github.com/brave/brave-browser/issues/33037 is about removing a user's own "share identifier" from links that YouTube copies to the clipboard in JS and that they later paste elsewhere.

This will remove other's people's "share identifier" from cross-site navigations to YouTube.

`si` was also added to the clean-urls list in https://github.com/brave/adblock-lists/pull/1317.

**Comment by fmarier** [comment]
YouTube also uses Service Workers and so the parameter will only be fully removed from navigations once https://github.com/brave/brave-browser/issues/23742 is fixed.

**Comment by stephendonner** [comment]
## Verification `IN-PROGRESS` using

```
Brave | 1.62.134 Chromium: 120.0.6099.199 (Official Build) beta (x86_64)
-- | --
Revision | 62903636ca583d9c0a0f758e98d15da6c3ee08e7
OS | macOS Version 14.3 (Build 23D5043d)
```


https://www.youtube.com/watch?v=dQw4w9WgXcQ&si=YjziZuccJeIE-b6z
https://youtu.be/watch?v=dQw4w9WgXcQ&si=YjziZuccJeIE-b6z
https://www.instagram.com/p/C1nNxSbsAzk/?utm_source=ig_web_button_share_sheet&igsh=ZDNl...IxNw==

**Comment by stephendonner** [comment]
## Verified `PASSED` in https://github.com/brave/brave-browser/issues/35094#issuecomment-1881725142

**Comment by hffvld** [comment]
Verified this issue as part of https://github.com/brave/brave-browser/issues/35094#issuecomment-1931090698 verification.
