### ISSUE TITLE
Leo feedback payload include Premium and Locale fields

### ISSUE THREAD

**Issue by porteron** [brave/brave-browser#34722]
In effort to distinguish feedback between premium and non premium users we'll include a `premium` param. Additionally we need to include `locale` in the form payload for backend optimization in translating non english user feedback.

- [ ] Add `locale` param to `/1/ai/feedback/form` request payload
- [ ] Add `premium: true|false` to `/1/ai/feedback/rating` request payload

@nullhook @aekeus @bbondy

**Comment by LaurenWags** [comment]
@nullhook could you please add either `QA/Yes` or `QA/No` label, depending on if manual QA is required?

If `QA/Yes`, please also add a test plan, thanks!
