### ISSUE TITLE
Add Route Params to Swap Screen

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#34725]
## Description 

We need to refactor the `Swap` screen to use route `params` similar to the `Send` screen.

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.65.96 Chromium: 123.0.6312.86 (Official Build) beta (64-bit)
-- | --
Revision | 5d9143e1a0812c53bdc27fd5384591254306a88c
OS | Windows 11 Version 23H2 (Build 22631.3296)

- Verified steps from [brave/brave-core#22266](https://github.com/brave/brave-core/pull/22266)
- Verified filtering Portfolio by `Account` and clicking on `More Menu` for an asset and selecting `Swap` routes to Swap screen and pre-populates the token
- Verified by changing tokens and networks works fine 
- Verified `Select To` button is disabled unless a `From token` is already selected
- Verified `Flip Tokens` button is disabled until there is `From Token` and `To Token` selected

https://github.com/brave/brave-browser/assets/17010094/6f474881-0eb4-4f44-8b96-589345e5d841
