### ISSUE TITLE
Add griffin feature flag for setting Llama13B as the default

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#34721]
- Change the default to Mixtral
- Make it controllable via a feature flag that we can set remotely to make it go to Llama2 13B as the default

**Comment by bbondy** [comment]
cc @petemill @nullhook

**Comment by bbondy** [comment]
FYI @petemill: Updated to Mixtral

**Comment by petemill** [comment]
The feature flags available are:

`is_freemium_available` - if `true` then all freemium models are actually freemium, if `false` then all freemium models are only available to premium users.

`default_model` - hard-coded value is `chat-leo-expanded` (mistral). If we disable freemium from the server-side, then we would change this in feature flag to `chat-basic`.

`default_premium_model` - hard-coded value is `chat-leo-expanded`. We would probably just keep this the same.

**Comment by kjozwiak** [comment]
The above requires `1.62.147` or higher for `1.62.x` verification 👍
