### ISSUE TITLE
[Android] Disable vpn support for not subscribed users

### ISSUE THREAD

**Issue by deeppandya** [brave/brave-browser#34724]
We need to disable `Contact Technical Support` option in `Settings` -> `Brave Firewall + VPN` if user is not subscribed the the vpn subscription. 

**Test Plan : **

1. Install fresh profile
2. Go to `Settings` -> `Brave Firewall + VPN`
3. Notice `Contact Technical Support` option if it's in disabled state.
4. Buy a subscription 
5. Go to `Settings` -> `Brave Firewall + VPN`
6. `Contact Technical Support` should be enabled.

**Comment by kjozwiak** [comment]
The above requires `1.61.98` or higher for `1.61.x` verification 👍

**Comment by hffvld** [comment]
Verified on `Galaxy Tab S8` and `Pixel 7` using version(s):
```
Device/OS: 
- Galaxy Tab S8 / gts8wifixx-user 13 TP1A.220624.014 release-keys
- Pixel 7 / panther_beta-user 14 AP11.231020.013.A1 release-keys
Brave build: 1.61.100
Chromium: 120.0.6099.62 (Official Build) (64-bit) 
```
---------------------------

**STEPS:**
1. Followed the steps from https://github.com/brave/brave-browser/issues/34724#issue-2027328200 

**ACTUAL RESULTS:**
- Verified that `Contact Technical Support` is disabled (grayed out) if no VPN subscription is purchased
- Verified that `Contact Technical Support` is enabled if a VPN subscription is purchased
- Verified that `Contact Technical Support` is enabled when a VPN subscription is purchased and the VPN is ON or OFF
- Verified that after canceling the VPN subscription, and after it expired, `Contact Technical Support` is grayed out again

---------------------------

<details>
<summary> Galaxy Tab S8 </summary>

|No Subscription|Subscription and VPN is ON|Subscription and VPN is OFF|Contact Technical Support|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/ac451825-bf2d-47dd-a201-f52f1f57fe1c) | ![2](https://github.com/brave/brave-browser/assets/128532965/eacb90c1-55cf-4dd7-a769-a45a501578f7) | ![3](https://github.com/brave/brave-browser/assets/128532965/dfdb315c-2aad-4dc7-a1ac-585dd4221b13) | ![4](https://github.com/brave/brave-browser/assets/128532965/225a7f7b-1751-4ebc-ad84-6ba70aa3869a) |

</details>

<details>
<summary> Pixel 7 </summary>

|No Subscription|Subscription and VPN is ON|Subscription and VPN is OFF|Contact Technical Support|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-browser/assets/128532965/c6881a1e-6975-4060-abb3-babc434d6248) | ![2](https://github.com/brave/brave-browser/assets/128532965/48ff35fe-3c02-45ad-af4e-5a561296abf7) | ![3](https://github.com/brave/brave-browser/assets/128532965/49e270b5-f358-46f3-9264-7827e2a610a3) | ![4](https://github.com/brave/brave-browser/assets/128532965/a8b00d47-af4a-4220-88eb-fa819c9c1e67) |

</details>
