### ISSUE TITLE
Playlist shouldn't create background WebContents on initial user navigation

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#34730]
The playlist feature currently opens a duplicate background WebContents when a user visits some pages.  This affects performance. We should only perform these actions when the user requests an item be added to the Playlist.

Background: The Playlist feature uses injected Javascript to determine any sources of videos on a Page. This script finds media elements and obtains their source attributes. Some sites use the JS MediaSource API to provide source data to a media element. This prevents the Playlist feature obtaining a source that can be simply network-fetched. These sites usually use feature-detection to check if the browser supports the MediaSource API and, when it doesn't, provide sources to the media elements that can be simply network-fetched. In order to support these sites, the Playlist feature creates a duplicate of the WebContents in the background, with the MediaSource API disabled. (It also fakes a different user agent for a subset of those sites in order to force the same result.)

In order to accomplish this, I suggest we split the logic:
1. **_Discovery_** - Perform the minimum necessary actions on load for any page to find out if the page has media element(s) that the user can add to Playlist
2. **_Extraction_** - Perform the source retrieval (and necessary renderer environment changes to facilitate that).

There is an added complication - that if the _Discovery_ script finds multiple media elements, then it might be challenging to a) provide meaningful metadata information to the user to distinguish the differences between the media elements and b) inform the _Extraction_ script as to which media element the user chose to add to Playlist.

Therefore I suggest the _Discovery_ script considers only 1 media element per page. Support for multiple media elements could come in a follow-up. I don't think this will be a meaningful feature loss since most media pages will only have a single element, or at least a single meaningful media element.

The _Discovery_ algorithm could work as follows:
- Find all media elements on the page as per current script **(but remove its condition on having a valid source Url)**
- If single, return that items metadata to Playlist feature
- If multiple:
  - Find largest media element in pixel size. If there are multiple of the same size, or it is audio elements with no size, then find the first where it is actively playing.
  - Return that items metadata to Playlist feature

The _Extraction_ algorithm could work as follows:
_It would only run after the user actions any "add to playlist" button_
- Start a background WebContents if necessary to force the renderer environment to provide a good media source
- Use the same _Discovery_ algorithm to find the appropriate media element
- Extract source url

_Note that if the current _Discovery_ algorithm causes a performance degradation on its own, then we should simplify to simply detect the presence of an active playing media element at any time. We don't really need metadata if we're not returning multiple media elements._

**Comment by ioc2e3** [comment]
Agree~

These actions should only be performed when the user requests to add an item to the playlist ...

**Comment by sangwoo108** [comment]
This would need investigation on how Android works when (+) button is clicked.

**Comment by deeppandya** [comment]
> This would need investigation on how Android works when (+) button is clicked.

@sangwoo108 i can work with you on android changes. let's connect in the DM.

**Comment by sangwoo108** [comment]
Thanks @deeppandya . Now @szilardszaloki is checking if the MediaSource can be used to download video instead of this trick. So Let's wait and see.

**Comment by szilardszaloki** [comment]
@sangwoo108 We'll be able to download videos via the `MediaSource` API, but we'll still need a background `WebContents` for it. Regardless of why we create the background `WebContents`, though, it'll need to be created on demand (when the user clicks on the `Add to Playlist` button — on desktop), as opposed to when navigating to the page. Not sure how it works on Android @deeppandya?

**Comment by sangwoo108** [comment]
It seems like the logic for the Playlist resides partly in [playlist-kotlin](https://github.com/brave-experiments/playlist-kotlin), and we're manually upgrading the playlist library. I feel I might lack the necessary expertise in this area. @deeppandya, would you mind reviewing the draft PR and implementing similar steps for Android?

**Comment by deeppandya** [comment]
> It seems like the logic for the Playlist resides partly in [playlist-kotlin](https://github.com/brave-experiments/playlist-kotlin), and we're manually upgrading the playlist library. I feel I might lack the necessary expertise in this area. @deeppandya, would you mind reviewing the draft PR and implementing similar steps for Android?

Sorry @sangwoo108 I have been on PTO. I will look at the PR tomorrow.

**Comment by deeppandya** [comment]
> It seems like the logic for the Playlist resides partly in [playlist-kotlin](https://github.com/brave-experiments/playlist-kotlin), and we're manually upgrading the playlist library. I feel I might lack the necessary expertise in this area. @deeppandya, would you mind reviewing the draft PR and implementing similar steps for Android?

@sangwoo108 all the detection and adding an item to playlist happens in brave core. and we have playlist kotlin module to use the same data from playlist service.

**Comment by sangwoo108** [comment]
Yeah, I was wondering if I can add PlaylistOptions and so on, but they seem to be in the Kotlin module.

**Comment by deeppandya** [comment]
> Yeah, I was wondering if I can add PlaylistOptions and so on, but they seem to be in the Kotlin module.

@sangwoo108 what options are you referring to ? I can add it in the kotlin module right away.
