### ISSUE TITLE
Youtube detects brave's AdBlocker on the latest version

### ISSUE THREAD

**Issue by a4addel** [brave/brave-browser#34737]
## Description 
Youtube detects brave's AdBlocker on the latest version

## Brave version (brave://version info)

 Version 1.60.125 Chromium: 119.0.6045.199 (Official Build) (64-bit)

![asdasdas](https://github.com/brave/brave-browser/assets/84184203/803b1a08-2c81-40a7-8e42-f87d8d30649e)
![sssssssssssssssssssssssssss](https://github.com/brave/brave-browser/assets/84184203/77da962f-a391-48cc-8751-ffe4bb6bacf9)

**Comment by Pugsrgreat** [comment]
I have this same issue, I didn't have it yesterday

**Comment by NileshDebix** [comment]
same issue

**Comment by ryanbr** [comment]
@a4addel  is it working for you?

**Comment by NileshDebix** [comment]
it's working for me

**Comment by a4addel** [comment]
Yes it did @NileshDebix

**Comment by ryanbr** [comment]
If it occurs again check https://drhyperion451.github.io/does-uBO-bypass-yt/  (and try forcing an update Brave Ad Block Updater - Version: 1.0.2693 in brave://components)

**Comment by cosmarc** [comment]
they just updated the script on the YT side.
