### ISSUE TITLE
Enable bitcoin feature by default for Nightly and Development channels

### ISSUE THREAD

**Issue by supermassive** [brave/brave-browser#34731]
on desktop

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.63.155 Chromium: 122.0.6261.29 (Official Build) (64-bit)
-- | --
Revision | b2be2c6f5b7340629f672ce706f5bfd62b113f82
OS | Windows 11 Version 23H2 (Build 22631.3155)

<details>
<summary><b>Onboarding</b></summary>
<ul>

- Verified Bitcoin Mainnet is shown as an option for available networks and enabled by default
![image](https://github.com/brave/brave-browser/assets/17010094/ca9b1d7a-5a42-48a7-a4e1-d7cb673164b8)
- Verified Bitcoin Testnet is shown when Show Testnet is enabled
![image](https://github.com/brave/brave-browser/assets/17010094/9f91caea-8962-4030-982c-3944aa2f2db7)
- Verified Bitcoin network is shown for both Create New Wallet and Restore Wallet

https://github.com/brave/brave-browser/assets/17010094/2d2a6762-a67b-4d6e-b1bf-7bacef083e27

- Verified if Bitcoin is enabled during onboarding then account is created 
 
https://github.com/brave/brave-browser/assets/17010094/2d2a6762-a67b-4d6e-b1bf-7bacef083e27

- Verified if Bitcoin is not enabled during onboarding no account is created

https://github.com/brave/brave-browser/assets/17010094/3698f0e0-7ca3-4aa8-98ac-1d902c6b80ff

</ul>
</details>

<details>
<summary><b>Account Creation</b></summary>
<ul>

- Verified account is automatically created during onboarding if network is selected
- Verified account creation message is shown if there is no account created and when you select Deposit for Bitcoin

https://github.com/brave/brave-browser/assets/17010094/212ab29f-ccd8-46cb-b3bb-e6db7379fce8

- Verified only SigWit accounts are created for Bitcoin (account starting with `bc`)
![image](https://github.com/brave/brave-browser/assets/17010094/f2cdcbe4-184f-419e-a17e-122c517bddc1)

- Verified creating testnet account creates wallet starting with `tb`
![image](https://github.com/brave/brave-browser/assets/17010094/a5a75153-55a6-4b53-9e99-19c0dc3ae0bf)

- Verified able to select Mainnet or Testnet during account creation
- Verified account creation is shown in panel as well wallet page

https://github.com/brave/brave-browser/assets/17010094/0072ea2c-9e36-4cb4-b4ae-d9823d755d17

</ul>
</details>


<details>
<summary><b>Restore Wallet</b></summary>
<ul>

- Verified Bitcoin accounts with transactions are restored when restoring wallet via seed
- Verify if no balance/transactions on BTC, Bitcoin accounts are not restored
- Encountered [#35954](https://github.com/brave/brave-browser/issues/35954)

</ul>
</details>

<details>
<summary><b>Import/Hardware Wallet</b></summary>
<ul>

- Verified there is no Bitcoin option available for import wallet

https://github.com/brave/brave-browser/assets/17010094/eea7e3da-8c03-418d-afb4-6cd01f61f095


- Verified there is no Bitcoin wallet option for hardware wallet 

https://github.com/brave/brave-browser/assets/17010094/e49140cc-6f99-48c2-8025-157f3be8f812


</ul>
</details>

<details>
<summary><b>Send BTC</b></summary>
<ul>

- Verified able to send BTC to a different account within Brave Wallet
- Verified able to send BTC to a different account on an external wallet 
- Verified until transactions are confirmed, available text is shown next to balance
- Verified details button is shown next to the balance
- Verified clicking on details shows the info about pending, available and total balance available for spending
- Verified transaction details shows input and output values in the details screen

<br>


<details>
<summary><b>Send Transaction Types</b></summary>
<ul>

- Verified sending BTC transaction to all address type works as expected
   - P2PKH - [Send](https://blockstream.info/testnet/tx/a2eab981a683cc72f3d23c99799b49b467d9947f175b8f6e7a40fab26dfd346a?expand), [Receive](https://blockstream.info/testnet/tx/a9e8d13db1ce8ab9ea74b9c41fcb2dcf35cce205ca65bce0c58c4b0694bbbbdc)
![image](https://github.com/brave/brave-browser/assets/17010094/86914002-cd05-4ede-adec-02097431b843)

   - P2WPH - [Send](https://blockstream.info/testnet/tx/69482f6580ce3623497d40abc0d53bb49510a403dc5d9e161792711ee9072172), [Receive](https://blockstream.info/testnet/tx/0f9fb3dfc62ae3d1e2525d7e2cc151943ee885e4ee1556d3774376222eb52677)
![image](https://github.com/brave/brave-browser/assets/17010094/817add66-7392-4758-bc85-961c161a5812)

   - P2TR - [Send](https://blockstream.info/testnet/tx/2867509834cb4581171196017e3cda0bbbc880dedae470df2b42106e5b8de5e3), [Receive](https://blockstream.info/testnet/tx/b27246e5b6c27d79aac310c4f640dc9102e807417c2eed45f95c66ad1c008fb1?expand)
![image](https://github.com/brave/brave-browser/assets/17010094/28cbdd49-8775-4568-8f7b-88134d5e71b0)

   - P2SH - Send, Receive
   - P2SH-P2WPKH  - [Send](https://blockstream.info/testnet/tx/8073884931a0b668135efc2207f4754e641d598e2fcc240b71f869b0d9064b94), [Receive](https://blockstream.info/testnet/tx/27de58dbb7ce97f996543c50a1a505eae42fc2e7c448931f5367bc02721bc394)
![image](https://github.com/brave/brave-browser/assets/17010094/2225771b-b0f2-4b60-b129-81f6abe01967)


</ul>
</details>
</ul>

</details>

<details>
<summary><b>Swap BTC</b></summary>
<ul>

- Verified BTC doesn’t show up for Swaps

https://github.com/brave/brave-browser/assets/17010094/a610d720-3d4b-46f8-b080-b4f8d6947ba5

</ul>
</details>

<details>
<summary><b>Buy BTC</b></summary>
<ul>

- Verified Bitcoin is shown in the list of tokens in Buy screen
- Verified able to switch between Bitcoin accounts on Buy screen
- Verified available On ramp providers pre-populate BTC on the popup tab

https://github.com/brave/brave-browser/assets/17010094/c4b5c3e3-1885-4f4d-9dbb-ecfbfe5e36b4

</ul>
</details>

<details>
<summary><b>Deposit BTC</b></summary>
<ul>

- Verified QR code is generated when Deposit screen is loaded
- Verified  for mainnet account address created starts with `bc`
- Verified for testnet account address created starts with `tb`

https://github.com/brave/brave-browser/assets/17010094/104ba8ef-f87a-4003-bdd1-f5424acd7023

</ul>
</details>

<details>
<summary><b>Address generation</b></summary>
<ul>

- Verified after a send transaction is done the deposit address changes to the next internal address
- Verified next internal address is correct before and after doing a transaction via `brave://wallet/dev-bitcoin`

https://github.com/brave/brave-browser/assets/17010094/3cf6f97b-1328-4403-ace5-94792cdf1d71

</ul>
</details>

<details>
<summary><b>Activity Tab</b></summary>
<ul>

- Verified submitted transaction show up in Activity tab
- Verified submitted transaction shows loading indicator when transaction is being confirmed
- Verified transaction gets confirmed 
- Verified able to view transaction on block explorer by clicking on the explorer button on the transaction hash

https://github.com/brave/brave-browser/assets/17010094/30882b05-ab80-4255-a124-d2373f4cd798


</ul>
</details>
