### ISSUE TITLE
Crash Report using Brave Wallet to connect to a site

### ISSUE THREAD

**Issue by kdenhartog** [brave/brave-browser#34748]
IMPORTANT: Your crash has already been automatically reported to our crash system. Please file this bug only if you can provide more information about it.

Brave Version: 1.63.5 Chromium: 120.0.6099.35
Operating System: Mac OS X 14.1.1

URL (if applicable) where crash occurred: https://fleek.co

Can you reproduce this crash? Yes, consistently

What steps will reproduce this crash? (If it's not reproducible, what were you doing just before the crash?)
1. Set wallet to "Brave Wallet" setting
2. Visit fleek.co
3. Connect to Brave Wallet with Metamask button
4. Enter password to unlock wallet

****DO NOT CHANGE BELOW THIS LINE****
Crash ID: crash/d3e20000-8bde-260b-0000-000000000000

cc @supermassive @yrliou

**Comment by iefremov** [comment]
@kdenhartog is it reproducible?

**Comment by kdenhartog** [comment]
I'm not able to reproduce this anymore. It likely was a regression that was fixed either intentionally or got fixed during a refactor of other code. I'm going to close this as won't fix.
