### ISSUE TITLE
Backup wallet doesn't complete

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#34758]
## Description 

Backup wallet doesn't complete

## Steps to Reproduce

   1. Clean profile on `1.62.99`
   2. Create a new wallet
   3. Skip backup wallet flow during onboarding
   4. Click the backup wallet from notification bar
   5. Follow the steps to finish backup
   6. Goes back to wallet home page and continues to show the backup wallet notification message

## Actual result:

https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1701945544304439

## Expected result:
Should complete wallet backup 

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.62.99 Chromium: 120.0.6099.62 (Official Build) beta (64-bit)
-- | --
Revision | 0f3e892de210168e788b3418961f94c4d0c5942a
OS | Windows 11 Version 22H2 (Build 22621.2792)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel @josheleonard @onyb

**Comment by kjozwiak** [comment]
Closing as https://github.com/brave/brave-core/pull/21287 was uplifted into `1.62.x`. The above requires `1.62.101` or higher for `1.62.x` verification 👍

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.62.105 Chromium: 120.0.6099.71 (Official Build) beta (64-bit)
-- | --
Revision | f72c783bcd52110d026061575b4bef28ccb547f7
OS | Windows 11 Version 23H2 (Build 22631.2715)

- Verified steps from issue description and [brave/brave-core#21287](https://github.com/brave/brave-core/pull/21287)
- Verified backup wallet banner is not shown when wallet backup is completed via onboarding
- Encountered [#34838](https://github.com/brave/brave-browser/issues/34838)
