### ISSUE TITLE
Youtube adblocker

### ISSUE THREAD

**Issue by prajjwaldevkota** [brave/brave-browser#34753]
## Description 

Anyone facing the issue I am facing using Brave? Started just today. 

## Steps to Reproduce

   1. 
![image](https://github.com/brave/brave-browser/assets/68115199/4bc4089c-0a42-41d7-a6de-90d7880fd09f)

   2. 
   3. 

## Brave version (brave://version info)
Brave	1.60.125 Chromium: 119.0.6045.199 (Official Build) (64-bit) 
Revision	9c1f9e267d7ef50aefbe434e616e05290536926b
OS	Windows 11 Version 23H2 (Build 22635.2841)
JavaScript	V8 11.9.169.7
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Command Line	"C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe" --disable-domain-reliability --enable-dom-distiller --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --variations-insecure-server-url=https://variations.brave.com/seed --flag-switches-begin --disable-smooth-scrolling --flag-switches-end --component-updater=url-source=https://go-updater.brave.com/extensions
Executable Path	C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path	C:\Users\PC\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Active Variations	AllowCertainClientHintsStudy:Enabled
BraveAIChatEnabledStudy:Enabled
BraveAdblockMobileNotificationsListDefault:Enabled
BraveAds.AdServingStudy:DefaultAdNotificationsPerHour=10/MaximumAdNotificationsPerDay=100/MaximumInlineContentAdsPerHour=6/MaximumInlineContentAdsPerDay=20/AdServingVersion=2
BraveAutoTranslateStudy:AutoTranslateDisabled
BraveDebounceStudy:Enabled
BraveForgetFirstPartyStorage:Enabled
BraveGoogleSignInPermissionStudy:Disabled
BraveHttpsByDefaultRolloutStudy:Enabled
BraveP3AConstellationReleaseRollout:Enabled
BraveRewardsWebUiPanelStudy:Enabled
BraveScreenFingerprintingBlockerStudy:Enabled
BraveSearchAdStudy:EnabledInProcessDesktop
ClampPlatformVersionClientHint:Disabled
CookieListDefaultStudy:Enabled
CrossPlatformVPNStudy:Enabled
Default1pBlockingStudy:Disabled
DisableReduceLanguage:Enabled
EphemeralStorageStudy:Enabled
FirstPartyEphemeralDomainBlockStudy:Enabled
ForceDisableBlinkFeatures:Enabled
PartitionBlinkMemoryCacheStudy:Enabled
PartitionConnectionsByNetworkIsolationKeyStudy:Enabled
PermissionLifetimeReleaseStudy:Enabled
PrettyPrintJSONDocument:Disabled_EmergencyKillSwitch
SmilAutoSuspendOnLagKillSwitch:Disabled_EmergencyKillSwitch
UserActivityStudy:Triggers
WhatsNewStudy:Enabled

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Yes
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
@prajjwaldevkota Are you still seeing it? Fixed here: https://github.com/brave/brave-browser/issues/34737#issuecomment-1843928952 I'll close this out as a dupe but want to see if you're stilling encountering that message.

**Comment by prajjwaldevkota** [comment]
Yup seems to be working now.
