### ISSUE TITLE
Deselect all, deselects default networks as well

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#34759]
## Description 

Uncheck select all, deselects default networks as well

## Steps to Reproduce

   1. Install nightly 
   2. Start wallet creation flow
   3. On network selector screen, click on `Deselect all`
   4. Solana/Ethereum networks also gets unchecked which is a read only field
   5. Search for ETH, shows Ethereum in list
   6. Click on `Select all`
   7. Clear search item
   8. Secondary network is all selected again

## Actual result:

https://github.com/brave/brave-browser/assets/17010094/19ab3055-02d1-40cb-b030-fd639bab7759

## Expected result:
Should probably not remove SOL/ETH networks

## Reproduces how often: 

Easy

## Brave version (brave://version info)

<html>
<body>

Brave | 1.63.20 Chromium: 120.0.6099.62 (Official Build) nightly (64-bit)
-- | --
Revision | 458935430c4b639cbc37cf6a39768b28befe0786
OS | Windows 11 Version 22H2 (Build 22621.2792)

</body>
</html>

## Version/Channel Information:

- Can you reproduce this issue with the current release? NA
- Can you reproduce this issue with the beta channel? NA
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @Douglashdaniel @kleantzogu

**Comment by Douglashdaniel** [comment]
cc: @josheleonard

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.63.141 Chromium: 121.0.6167.139 (Official Build) beta (64-bit)
-- | --
Revision | aa92f6cecec7f6c576bd1cf120f4cf359d770159
OS | Windows 11 Version 23H2 (Build 22631.3007)

- Verified steps from issue description and [brave/brave-core#21292](https://github.com/brave/brave-core/pull/21292)
- Verified Ethereum/Solana is not unchecked when deselecting all networks during onboarding (new wallet/restore wallet)

https://github.com/brave/brave-browser/assets/17010094/d715537e-0baa-41fc-8030-fb057bac2c79
