### ISSUE TITLE
Cannot switch off `Include in Auto-contribute` in BR panel

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#3476]
## Description 

Cannot switch off `Include in Auto-contribute` in BR panel

## Steps to Reproduce

   1. Open brave Dev or Beta
   2. Enable Rewards
   3. Open any website
   4. Open BR panel for the website
   5. Try to turn off `Include in Auto-contribute` 

## Actual result:

Cannot switch off `Include in Auto-contribute` in BR panel

![3476](https://user-images.githubusercontent.com/38657976/53308176-07146280-38c5-11e9-951d-27010f86e7ad.gif)

## Expected result:
Should be able to turn off `Include in Auto-contribute` 

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 0.61.36 Chromium: 73.0.3683.39 (Official Build) beta (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 10 OS Build 17134.523

### Reproducible on current release: No
- Does it reproduce on brave-browser dev/beta builds? Yes

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional Information

The issue is reported by the community
https://community.brave.com/t/cannot-switch-off-include-in-auto-contribute-anymore/45874

@brave/legacy_qa

**Comment by GeetaSarvadnya** [comment]
Further investigation of the issue is as below:
1. Clean profile 0.61.36
2. Enable Rewards
3. Add DDG to a-c table
4. Open on BR panel for DDG
5. Click on `Include in Auto-Contribute` switch multiple times
The site which is added in a-c table gets deleted, and below message is displayed
`Total number of sites you excluded from Auto-Contribute: 34(Restore All)`
6. At one point, switch gets turned off in BR panel for DDG
7. Click on `Include in Auto-Contribute` switch multiple times 

The site which is added in a-c table gets deleted, and below message is displayed
`Total number of sites you excluded from Auto-Contribute: 4294967286 (Restore All)`

Please find the GIF file below.
![issue with a-c table exclude sites](https://user-images.githubusercontent.com/38657976/53344446-b50d2480-3938-11e9-96d4-d00e98f91020.gif)

**Comment by LaurenWags** [comment]
Reproduced original issue from description and https://github.com/brave/brave-browser/issues/3476#issuecomment-467033829 with build below.

Brave | 0.61.45 Chromium: 73.0.3683.39 (Official Build) beta(64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Mac OS X

**Comment by NejcZdovc** [comment]
@LaurenWags this is still in 0.63, it's waiting for uplift

**Comment by btlechowski** [comment]
Verification passed on 

Brave | 0.61.47 Chromium: 73.0.3683.39 (Official Build) beta (64-bit)
-- | --
Revision | cc53b0e12fcaf42e4bab8d6c23bd4fb7aae99f6c-refs/branch-heads/3683@{#413}
OS | Windows 7 Service Pack 1 Build 7601.24312

Used test plan from the description.
Encountered https://github.com/brave/brave-browser/issues/3551 while testing.
