### ISSUE TITLE
Cleanup Hide/Delete NFT logic

### ISSUE THREAD

**Issue by josheleonard** [brave/brave-browser#34763]
## Description 

Move the hide/delete NFT logic from async handlers to RTK Queries and mutations

## Regression Testing
- Hide / Delete NFTs should continue to work without regressions. 
- Token lists should continue to render appropriate items without regressions

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.65.89 Chromium: 123.0.6312.58 (Official Build) beta (64-bit)
-- | --
Revision | 2975bd8d3905ed79de82dd9fa11b6e4019075dd6
OS | Windows 11 Version 23H2 (Build 22631.3296)

- Verified steps from issue description
- Verified Hide/Unhide NFT works as expected without any regression
- Verified Remove NFT from wallet works as expected without any regression
- Verified Token lists work as expected without any regression
