### ISSUE TITLE
Creating a Solana Transaction Causes the Browser to Crash

### ISSUE THREAD

**Issue by Douglashdaniel** [brave/brave-browser#34779]
## Description 

Creating a `Solana` transaction in the `Wallet` causes the `Browser` to crash

## Steps to Reproduce

   1. Open the `Wallet` and create a `Solana` transaction
   2. The `Browser` will crash after clicking `Send`

## Actual result:

https://github.com/brave/brave-browser/assets/40611140/2fc17d51-e316-4b9a-8311-53bf90add91d

## Expected result:
Should not crash the `Browser`

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on

Brave | 1.63.155 Chromium: 122.0.6261.29 (Official Build) (64-bit)
-- | --
Revision | b2be2c6f5b7340629f672ce706f5bfd62b113f82
OS | Windows 11 Version 23H2 (Build 22631.3155)

- Verified steps from [brave/brave-core#21296](https://github.com/brave/brave-core/pull/21296)
- Verified no crash when trying to submit a Solana transaction

https://github.com/brave/brave-browser/assets/17010094/3fdc12bb-702a-490f-ad62-fdb63fa24d63
