### ISSUE TITLE
Promo-card images (Creator, Tap) are missing from `brave://rewards`

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-browser#34775]
## Description 

Promo-card images (Creator, Tap) are missing from `brave://rewards`

## Steps to Reproduce

   1. install `1.63.24`
   2. launch Brave
   3. load `brave://rewards`
   4. opt-in
   5. look at the right-hand side

## Actual result:

The promo-card images are missing for `Brave Creators` and the `TAP` network

![image](https://github.com/brave/brave-browser/assets/387249/2cc5f0d7-543b-4c18-9b22-470b0d4caa5b)

## Expected result:

![image](https://github.com/brave/brave-browser/assets/387249/925dc9db-235b-48c6-9792-6b49b4608dfa)

## Reproduces how often: 

100%

## Brave version (brave://version info)

```
Brave | 1.63.24 Chromium: 120.0.6099.71 (Official Build) nightly (64-bit)
-- | --
Revision | 8858c508f9a33d9cb69c2b3f2da81a52a15040f6
OS | Windows 10 Version 22H2 (Build 19045.3758)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @LaurenWags @Miyayes @fallaciousreasoning @zenparsing

**Comment by fallaciousreasoning** [comment]
Nice catch @stephendonner!

**Comment by kjozwiak** [comment]
Removing `QA Pass` label as the above was uplifted into `1.62.x` via https://github.com/brave/brave-core/pull/21465#pullrequestreview-1809926298 and will need to be rechecked using `1.62.x`. The above requires `1.62.135` or higher for `1.62.x` verification 👍

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.62.135 Chromium: 120.0.6099.199 (Official Build) beta (x86_64)
-- | --
Revision | c66fd7306403245e6c370da9f287f69a5cf46a10
OS | macOS Version 13.6.3 (Build 22G436)
```
